Terraria Decompiled: Terraria.WorldItem.GetShimmered
GetShimmered()
void Terraria.WorldItem.GetShimmered () inline
Definition at line 2141 of file WorldItem.cs.
        {
            int shimmerEquivalentType = this.inner.GetShimmerEquivalentType(false);
            int decraftingRecipeIndex = ShimmerTransforms.GetDecraftingRecipeIndex(this.inner.GetShimmerEquivalentType(true));
            int transformToItem = ShimmerTransforms.GetTransformToItem(shimmerEquivalentType);
            if (ItemID.Sets.CommonCoin[shimmerEquivalentType])
            {
                if (shimmerEquivalentType == 72)
                {
                    this.stack *= 100;
                }
                else if (shimmerEquivalentType == 73)
                {
                    this.stack *= 10000;
                }
                else if (shimmerEquivalentType == 74)
                {
                    if (this.stack > 1)
                    {
                        this.stack = 1;
                    }
                    this.stack *= 1000000;
                }
                Main.player[Main.myPlayer].AddCoinLuck(base.Center, this.stack);
                NetMessage.SendData(146, -1, -1, null, 1, (float)((int)base.Center.X), (float)((int)base.Center.Y), (float)this.stack, 0, 0, 0);
                this.type = 0;
                this.stack = 0;
            }
            else if (transformToItem > 0)
            {
                int stack = this.stack;
                this.SetDefaults(transformToItem);
                this.stack = stack;
                this.shimmered = true;
            }
            else if (this.type == 4986)
            {
                if (NPC.unlockedSlimeRainbowSpawn)
                {
                    return;
                }
                NPC.unlockedSlimeRainbowSpawn = true;
                NetMessage.SendData(7, -1, -1, null, 0, 0f, 0f, 0f, 0, 0, 0);
                int num = NPC.NewNPC(this.GetNPCSource_FromThis(), (int)base.Center.X + 4, (int)base.Center.Y, 681, 0, 0f, 0f, 0f, 0f, 255);
                if (num >= 0)
                {
                    NPC npc = Main.npc[num];
                    npc.velocity = this.velocity;
                    npc.shimmerTransparency = 1f;
                }
                WorldGen.CheckAchievement_RealEstateAndTownSlimes();
                int num2 = this.stack;
                this.stack = num2 - 1;
                if (this.stack <= 0)
                {
                    this.type = 0;
                }
            }
            else if (this.type == 560)
            {
                if (Main.slimeRain)
                {
                    return;
                }
                Main.StartSlimeRain(true);
                int num2 = this.stack;
                this.stack = num2 - 1;
                if (this.stack <= 0)
                {
                    this.type = 0;
                }
                else
                {
                    this.shimmered = true;
                }
            }
            else if (this.makeNPC > 0)
            {
                int num3 = 50;
                int maxNPCs = Main.maxNPCs;
                int num4 = NPC.GetAvailableAmountOfNPCsToSpawnUpToSlot(this.stack, maxNPCs);
                while (num3 > 0 && num4 > 0 && this.stack > 0)
                {
                    num3--;
                    num4--;
                    int num2 = this.stack;
                    this.stack = num2 - 1;
                    int num5;
                    if (NPCID.Sets.ShimmerTransformToNPC[(int)this.makeNPC] >= 0)
                    {
                        num5 = NPC.ReleaseNPC((int)base.Center.X, (int)base.Bottom.Y, NPCID.Sets.ShimmerTransformToNPC[(int)this.makeNPC], 0, Main.myPlayer);
                    }
                    else
                    {
                        num5 = NPC.ReleaseNPC((int)base.Center.X, (int)base.Bottom.Y, (int)this.makeNPC, this.placeStyle, Main.myPlayer);
                    }
                    if (num5 >= 0)
                    {
                        Main.npc[num5].shimmerTransparency = 1f;
                    }
                }
                this.shimmered = true;
                if (this.stack <= 0)
                {
                    this.type = 0;
                }
            }
            else if (decraftingRecipeIndex >= 0)
            {
                int num6 = this.inner.FindDecraftAmount();
                Recipe recipe = Main.recipe[decraftingRecipeIndex];
                bool flag = recipe.requiredItem[1].stack > 0;
                IEnumerable<Recipe.RequiredItemEntry> enumerable = recipe.requiredItemQuickLookup;
                if (recipe.customShimmerResults != null)
                {
                    enumerable = recipe.customShimmerResults.Select((Item item) => new Recipe.RequiredItemEntry
                    {
                        itemIdOrRecipeGroup = item.type,
                        stack = item.stack
                    });
                }
                int num7 = 0;
                foreach (Recipe.RequiredItemEntry requiredItemEntry in enumerable)
                {
                    if (requiredItemEntry.itemIdOrRecipeGroup <= 0)
                    {
                        break;
                    }
                    num7++;
                    int i = num6 * requiredItemEntry.stack;
                    int num8 = (requiredItemEntry.IsRecipeGroup ? requiredItemEntry.RecipeGroup.DecraftItemId : requiredItemEntry.itemIdOrRecipeGroup);
                    if (recipe.alchemy)
                    {
                        for (int j = i; j > 0; j--)
{
                            if (Main.rand.Next(3) == 0)
{
                                i--;
                            }
                        }
                    }
                    while (i > 0)
                    {
                        int num9 = i;
                        if (num9 > 9999)
{
                            num9 = 9999;
                        }
                        i -= num9;
                        int num10 = Item.NewItem(this.GetItemSource_Misc(ItemSourceID.Shimmer), (int)this.position.X, (int)this.position.Y, this.width, this.height, num8, 1, false, 0, false);
                        WorldItem worldItem = Main.item[num10];
                        worldItem.stack = num9;
                        worldItem.shimmerTime = 1f;
                        worldItem.shimmered = true;
                        worldItem.shimmerWet = true;
                        worldItem.wet = true;
                        worldItem.velocity *= 0.1f;
                        worldItem.playerIndexTheItemIsReservedFor = Main.myPlayer;
                        if (flag)
{
                            worldItem.velocity.X = 1f * (float)num7;
                            WorldItem worldItem2 = worldItem;
                            worldItem2.velocity.X = worldItem2.velocity.X * (1f + (float)num7 * 0.05f);
                            if (num7 % 2 == 0)
{
                                WorldItem worldItem3 = worldItem;
                                worldItem3.velocity.X = worldItem3.velocity.X * -1f;
                            }
                        }
                        NetMessage.SendData(145, -1, -1, null, num10, 1f, 0f, 0f, 0, 0, 0);
                    }
                }
                this.stack -= num6 * recipe.createItem.stack;
                if (this.stack <= 0)
                {
                    this.stack = 0;
                    this.type = 0;
                }
            }
            if (this.stack > 0)
            {
                this.shimmerTime = 1f;
            }
            else
            {
                this.shimmerTime = 0f;
            }
            this.shimmerWet = true;
            this.wet = true;
            this.velocity *= 0.1f;
            if (Main.netMode == 0)
            {
                WorldItem.ShimmerEffect(base.Center);
            }
            else
            {
                NetMessage.SendData(146, -1, -1, null, 0, (float)((int)base.Center.X), (float)((int)base.Center.Y), 0f, 0, 0, 0);
                NetMessage.SendData(145, -1, -1, null, this.whoAmI, 1f, 0f, 0f, 0, 0, 0);
            }
            AchievementsHelper.NotifyProgressionEvent(27);
            if (this.stack == 0)
            {
                this.makeNPC = -1;
                this.TurnToAir(false);
            }
        }
References Terraria.Player.AddCoinLuck(), Terraria.Recipe.alchemy, Terraria.WorldGen.CheckAchievement_RealEstateAndTownSlimes(), Terraria.ID.ItemID.Sets.CommonCoin, Terraria.Recipe.createItem, Terraria.Recipe.customShimmerResults, Terraria.Item.FindDecraftAmount(), Terraria.NPC.GetAvailableAmountOfNPCsToSpawnUpToSlot(), Terraria.GameContent.ShimmerTransforms.GetDecraftingRecipeIndex(), Terraria.WorldItem.GetItemSource_Misc(), Terraria.WorldItem.GetNPCSource_FromThis(), Terraria.Item.GetShimmerEquivalentType(), Terraria.GameContent.ShimmerTransforms.GetTransformToItem(), Terraria.Entity.height, Terraria.WorldItem.inner, int, System.item, Terraria.Main.item, Terraria.WorldItem.makeNPC, Terraria.Main.maxNPCs, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.NPC.NewNPC(), Terraria.GameContent.Achievements.AchievementsHelper.NotifyProgressionEvent(), Terraria.Main.npc, Terraria.Main.player, Terraria.Entity.position, Terraria.Main.rand, Terraria.Main.recipe, Terraria.NPC.ReleaseNPC(), Terraria.Recipe.requiredItem, Terraria.Recipe.requiredItemQuickLookup, Terraria.NetMessage.SendData(), Terraria.WorldItem.SetDefaults(), Terraria.ID.ItemSourceID.Shimmer, Terraria.WorldItem.ShimmerEffect(), Terraria.ID.NPCID.Sets.ShimmerTransformToNPC, Terraria.NPC.shimmerTransparency, Terraria.Main.slimeRain, Terraria.Item.stack, Terraria.WorldItem.stack, Terraria.Main.StartSlimeRain(), Terraria.WorldItem.TurnToAir(), Terraria.WorldItem.type, Terraria.NPC.unlockedSlimeRainbowSpawn, Terraria.Entity.velocity, Terraria.Entity.whoAmI, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.WorldItem.Shimmering().