Terraria Decompiled: Terraria.WorldItem.CheckInWorld
CheckInWorld()
void Terraria.WorldItem.CheckInWorld (int i) inline private
Definition at line 810 of file WorldItem.cs.
        {
            if (WorldGen.InWorld(this.position.ToTileCoordinates(), 20))
            {
                return;
            }
            if (ItemID.Sets.RecoverableImportantItem[this.type])
            {
                Point point;
                if ((this.instanced || Main.netMode == 0) && Main.LocalPlayer.SpawnX >= 0)
                {
                    point = new Point(Main.LocalPlayer.SpawnX, Main.LocalPlayer.SpawnY);
                }
                else
                {
                    point = new Point(Main.spawnTileX, Main.spawnTileY);
                }
                base.Center = point.ToWorldCoordinates(8f, 8f);
                this.velocity = Vector2.Zero;
            }
            else
            {
                this.TurnToAir(false);
            }
            if (Main.netMode == 2)
            {
                NetMessage.SendData(21, -1, -1, null, i, 0f, 0f, 0f, 0, 0, 0);
            }
        }
References Terraria.WorldItem.instanced, Terraria.WorldGen.InWorld(), Terraria.Main.LocalPlayer, Terraria.Main.netMode, Terraria.ID.ItemID.Sets.RecoverableImportantItem, Terraria.NetMessage.SendData(), Terraria.Main.spawnTileX, Terraria.Main.spawnTileY, Terraria.Player.SpawnX, Terraria.Player.SpawnY, Terraria.WorldItem.TurnToAir(), and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.WorldItem.UpdateItem().