Terraria Decompiled: Terraria.WorldItem.TryGrantingMakeAWishSet
TryGrantingMakeAWishSet()
void Terraria.WorldItem.TryGrantingMakeAWishSet () inline private
Definition at line 841 of file WorldItem.cs.
        {
            if (this.playerIndexTheItemIsReservedFor != Main.myPlayer)
            {
                return;
            }
            if (!this.wet || this.stack != 1)
            {
                return;
            }
            if (this.ownIgnore == 1 && this.noGrabDelay <= 0)
            {
                return;
            }
            byte b = Player.FindClosest(this.position, this.width, this.height);
            if (b == 255)
            {
                return;
            }
            if (!Main.player[(int)b].ZoneDesert)
            {
                return;
            }
            this.TurnToAir(false);
            if (Main.netMode != 0)
            {
                NetMessage.SendData(21, -1, -1, null, this.whoAmI, 0f, 0f, 0f, 0, 0, 0);
            }
            bool flag = true;
            int num = 5;
            this.SpawnShimmeredItem(5655, flag, num);
            this.SpawnShimmeredItem(5656, flag, num);
            this.SpawnShimmeredItem(5657, flag, num);
            this.SpawnShimmeredItem(5658, flag, num);
            this.SpawnShimmeredItem(5661, flag, num);
            ParticleOrchestrator.BroadcastOrRequestParticleSpawn(ParticleOrchestraType.HeroicisSetSpawnSound, new ParticleOrchestraSettings
            {
                PositionInWorld = base.Center
            });
        }
References Terraria.GameContent.Drawing.ParticleOrchestrator.BroadcastOrRequestParticleSpawn(), Terraria.Player.FindClosest(), Terraria.Entity.height, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.WorldItem.noGrabDelay, Terraria.WorldItem.ownIgnore, Terraria.Main.player, Terraria.WorldItem.playerIndexTheItemIsReservedFor, Terraria.Entity.position, Terraria.NetMessage.SendData(), Terraria.WorldItem.SpawnShimmeredItem(), Terraria.WorldItem.stack, Terraria.WorldItem.TurnToAir(), Terraria.Entity.wet, Terraria.Entity.whoAmI, Terraria.Entity.width, and Terraria.Player.ZoneDesert.
Referenced by Terraria.WorldItem.UpdateItem().