Terraria Decompiled: Terraria.WorldItem.UpdateItem
UpdateItem()
void Terraria.WorldItem.UpdateItem (int i) inline
Definition at line 581 of file WorldItem.cs.
        {
            this.UpdateEntityFields();
            this.whoAmI = i;
            if (Main.timeItemSlotCannotBeReusedFor[i] > 0)
            {
                if (Main.netMode == 2)
                {
                    Main.timeItemSlotCannotBeReusedFor[i]--;
                    return;
                }
                Main.timeItemSlotCannotBeReusedFor[i] = 0;
            }
            if (!this.active)
            {
                return;
            }
            if (this.instanced)
            {
                if (Main.netMode == 2)
                {
                    this.TurnToAir(false);
                    return;
                }
                this.keepTime = 6000;
                this.ownTime = 0;
                this.noGrabDelay = 0;
                this.playerIndexTheItemIsReservedFor = Main.myPlayer;
            }
            if (Main.netMode == 0)
            {
                this.playerIndexTheItemIsReservedFor = Main.myPlayer;
            }
            float num = 0.1f;
            float num2 = 7f;
            if (Main.netMode == 1)
            {
                Point point = base.Bottom.ToTileCoordinates();
                if (WorldGen.InWorld(point, 0) && Main.tile[point.X, point.Y] == null)
                {
                    num = 0f;
                    this.velocity = Vector2.Zero;
                    if (this.instanced && Main.GameUpdateCount % 10U == 0U)
                    {
                        NetMessage.SendData(159, -1, -1, null, point.X / 200, (float)(point.Y / 150), 0f, 0f, 0, 0, 0);
                    }
                }
            }
            Vector2 vector = this.velocity * 0.5f;
            if (this.shimmerWet)
            {
                num = 0.065f;
                num2 = 4f;
                vector = this.velocity * 0.375f;
            }
            else if (this.honeyWet)
            {
                num = 0.05f;
                num2 = 3f;
                vector = this.velocity * 0.25f;
            }
            else if (this.wet)
            {
                num = 0.08f;
                num2 = 5f;
            }
            if (this.ownTime > 0)
            {
                this.ownTime--;
            }
            else
            {
                this.ownIgnore = -1;
            }
            if (this.keepTime > 0)
            {
                this.keepTime--;
            }
            if (!this.beingGrabbed)
            {
                if (this.type == 205 && this.playerIndexTheItemIsReservedFor == Main.myPlayer && Main.raining && (Main.isThereAWorldSurface || Main.remixWorld) && WorldGen.IsSurfaceForAtmospherics(this.position.ToTileCoordinates()))
                {
                    int num3 = (int)base.Center.X / 16;
                    int num4 = (int)base.Center.Y / 16;
                    if (WorldGen.InWorld(num3, num4, 0) && WallID.Sets.AllowsWind[(int)Main.tile[num3, num4].wall])
                    {
                        int num5 = 600;
                        if (Main.dayRate > 0 && Main.dayRate < num5)
{
                            num5 /= Main.dayRate;
                        }
                        if (Main.rand.Next(num5) == 0 && Main.rand.NextFloat() < Main.maxRaining)
{
                            int stack = this.stack;
                            this.SetDefaults(206);
                            this.playerIndexTheItemIsReservedFor = Main.myPlayer;
                            this.stack = stack;
                            NetMessage.SendData(21, -1, -1, null, i, 0f, 0f, 0f, 0, 0, 0);
                        }
                    }
                }
                if (this.shimmered)
                {
                    if (Main.rand.Next(30) == 0)
                    {
                        int num6 = Dust.NewDust(this.position, this.width, this.height, 309, 0f, 0f, 0, default(Color), 1f);
                        Dust dust = Main.dust[num6];
                        dust.position.X = dust.position.X + (float)Main.rand.Next(-8, 5);
                        Dust dust2 = Main.dust[num6];
                        dust2.position.Y = dust2.position.Y + (float)Main.rand.Next(-8, 5);
                        Main.dust[num6].scale *= 1.1f;
                        Main.dust[num6].velocity *= 0.3f;
                        int num7 = Main.rand.Next(6);
                        if (num7 == 0)
{
                            Main.dust[num6].color = new Color(255, 255, 210);
                        }
                        else if (num7 == 1)
{
                            Main.dust[num6].color = new Color(190, 245, 255);
                        }
                        else if (num7 == 2)
{
                            Main.dust[num6].color = new Color(255, 150, 255);
                        }
                        else
{
                            Main.dust[num6].color = new Color(190, 175, 255);
                        }
                    }
                    Lighting.AddLight(base.Center, (1f - this.shimmerTime) * 0.8f, (1f - this.shimmerTime) * 0.8f, (1f - this.shimmerTime) * 0.8f);
                    num = 0f;
                    if (this.shimmerWet)
                    {
                        if (this.velocity.Y > -4f)
{
                            this.velocity.Y = this.velocity.Y - 0.05f;
                        }
                    }
                    else
                    {
                        int num8 = 2;
                        int num9 = (int)(base.Center.X / 16f);
                        int num10 = (int)(base.Center.Y / 16f);
                        bool flag = false;
                        for (int j = num10; j < num10 + num8; j++)
{
                            if (WorldGen.InWorld(num9, j, 0) && Main.tile[num9, j] != null && Main.tile[num9, j].shimmer() && Main.tile[num9, j].liquid > 0)
{
                                flag = true;
                                break;
                            }
                        }
                        if (flag)
{
                            if (this.velocity.Y > -4f)
{
                                this.velocity.Y = this.velocity.Y - 0.05f;
                            }
                        }
                        else
{
                            this.velocity.Y = this.velocity.Y * 0.9f;
                        }
                    }
                }
                if (this.shimmerWet && !this.shimmered)
                {
                    this.Shimmering();
                }
                else if (this.shimmerTime > 0f)
                {
                    this.shimmerTime -= 0.01f;
                    if (this.shimmerTime < 0f)
                    {
                        this.shimmerTime = 0f;
                    }
                }
                if (this.shimmerTime == 0f)
                {
                    this.TryCombiningIntoNearbyItems(i);
                }
                if (this.timeLeftInWhichTheItemCannotBeTakenByEnemies > 0)
                {
                    this.timeLeftInWhichTheItemCannotBeTakenByEnemies--;
                }
                if (this.timeLeftInWhichTheItemCannotBeTakenByEnemies == 0 && this.playerIndexTheItemIsReservedFor == Main.myPlayer)
                {
                    this.GetPickedUpByMonsters_Special(i);
                    if (Main.expertMode && this.IsACoin)
                    {
                        this.GetPickedUpByMonsters_Money(i);
                    }
                }
                this.MoveInWorld(num, num2, ref vector, i);
                if (this.lavaWet)
                {
                    this.CheckLavaDeath(i);
                }
                this.CheckInWorld(i);
                this.DespawnIfMeetingConditions(i);
                if (this.type == 74)
                {
                    this.TryGrantingMakeAWishSet();
                }
            }
            else
            {
                this.wet = false;
                this.wetCount = 0;
                this.lavaWet = false;
                this.honeyWet = false;
                this.shimmerWet = false;
                this.beingGrabbed = false;
                this.onConveyor = false;
                this.ApplyMovement(ref vector);
            }
            this.UpdateItem_VisualEffects();
            if (this.timeSinceItemSpawned < 2147483547)
            {
                this.timeSinceItemSpawned++;
            }
            if (this.noGrabDelay > 0)
            {
                this.noGrabDelay--;
            }
        }
References Terraria.WorldItem.active, Terraria.Lighting.AddLight(), Terraria.ID.WallID.Sets.AllowsWind, Terraria.WorldItem.ApplyMovement(), Terraria.WorldItem.beingGrabbed, Terraria.WorldItem.CheckInWorld(), Terraria.WorldItem.CheckLavaDeath(), Terraria.Dust.color, Terraria.Main.dayRate, Terraria.WorldItem.DespawnIfMeetingConditions(), Terraria.Main.dust, Terraria.Main.expertMode, Terraria.Main.GameUpdateCount, Terraria.WorldItem.GetPickedUpByMonsters_Money(), Terraria.WorldItem.GetPickedUpByMonsters_Special(), Terraria.Entity.height, Terraria.Entity.honeyWet, Terraria.WorldItem.instanced, int, Terraria.WorldGen.InWorld(), Terraria.WorldGen.IsSurfaceForAtmospherics(), Terraria.Main.isThereAWorldSurface, Terraria.WorldItem.keepTime, Terraria.Entity.lavaWet, Terraria.Tile.liquid, Terraria.Main.maxRaining, Terraria.WorldItem.MoveInWorld(), Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Dust.NewDust(), Terraria.WorldItem.noGrabDelay, Terraria.WorldItem.ownTime, Terraria.WorldItem.playerIndexTheItemIsReservedFor, Terraria.Entity.position, Terraria.Main.raining, Terraria.Main.rand, Terraria.Main.remixWorld, Terraria.Dust.scale, Terraria.NetMessage.SendData(), Terraria.WorldItem.SetDefaults(), Terraria.Tile.shimmer(), Terraria.WorldItem.shimmered, Terraria.WorldItem.Shimmering(), Terraria.WorldItem.shimmerTime, Terraria.Entity.shimmerWet, Terraria.WorldItem.stack, Terraria.Main.tile, Terraria.Main.timeItemSlotCannotBeReusedFor, Terraria.WorldItem.timeLeftInWhichTheItemCannotBeTakenByEnemies, Terraria.WorldItem.timeSinceItemSpawned, Terraria.WorldItem.TryCombiningIntoNearbyItems(), Terraria.WorldItem.TryGrantingMakeAWishSet(), Terraria.WorldItem.TurnToAir(), Terraria.WorldItem.type, System.U, Terraria.WorldItem.UpdateEntityFields(), Terraria.WorldItem.UpdateItem_VisualEffects(), Terraria.Dust.velocity, Terraria.Entity.velocity, Terraria.Tile.wall, Terraria.Entity.wet, Terraria.Entity.width, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Point.Y, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.Main.DoUpdateInWorld().