Terraria Decompiled: Terraria.GameContent.NearbyChests.GetBanksInRangeOf
GetBanksInRangeOf()
static List< PositionedChest > Terraria.GameContent.NearbyChests.GetBanksInRangeOf (Player player, float range = 0f) inline static
Definition at line 35 of file NearbyChests.cs.
        {
            if (range <= 0f)
            {
                range = 600f;
            }
            List<PositionedChest> scratch = NearbyChests._scratch;
            scratch.Clear();
            int num = (int)(range / 16f + 2f);
            Point point = player.Center.ToTileCoordinates();
            Rectangle rectangle = new Rectangle(point.X - num, point.Y - num, num * 2 + 1, num * 2 + 1);
            for (int i = 0; i < 1000; i++)
            {
                Projectile projectile = Main.projectile[i];
                if (projectile.active)
                {
                    int num2 = -1;
                    if (projectile.TryGetContainerIndex(out num2))
                    {
                        Vector2 vector = projectile.Hitbox.ClosestPointInRect(player.Center);
                        Chest chest;
                        if (rectangle.Contains(vector.ToTileCoordinates()) && NearbyChests.ContainerIndexToPlayerBank(player, num2, out chest) && !scratch.Contains(chest))
{
                            scratch.Add(new PositionedChest(chest, projectile.Center));
                        }
                    }
                }
            }
            for (int j = rectangle.Left; j < rectangle.Right; j++)
            {
                for (int k = rectangle.Top; k < rectangle.Bottom; k++)
                {
                    if (WorldGen.InWorld(j, k, 0))
                    {
                        int num3 = 0;
                        int type = (int)Main.tile[j, k].type;
                        if (type == 29)
{
                            num3 = -2;
                        }
                        else if (type == 97)
{
                            num3 = -3;
                        }
                        else if (type == 463)
{
                            num3 = -4;
                        }
                        else if (type == 491)
{
                            num3 = -5;
                        }
                        Chest chest2;
                        if (NearbyChests.ContainerIndexToPlayerBank(player, num3, out chest2) && !scratch.Contains(chest2))
{
                            scratch.Add(new PositionedChest(chest2, new Vector2((float)(j * 16 + 16), (float)(k * 16 + 16))));
                        }
                    }
                }
            }
            return scratch;
        }
References Terraria.GameContent.NearbyChests._scratch, Terraria.Projectile.active, System.Collections.Generic.List< T >.Add(), Microsoft.Xna.Framework.Rectangle.Bottom, Terraria.Entity.Center, System.Collections.Generic.List< T >.Clear(), Terraria.GameContent.NearbyChests.ContainerIndexToPlayerBank(), Microsoft.Xna.Framework.Rectangle.Contains(), System.Collections.Generic.List< T >.Contains(), Terraria.Entity.Hitbox, int, Terraria.WorldGen.InWorld(), Microsoft.Xna.Framework.Rectangle.Left, Terraria.Main.projectile, Microsoft.Xna.Framework.Rectangle.Right, Terraria.Main.tile, Microsoft.Xna.Framework.Rectangle.Top, Terraria.Projectile.TryGetContainerIndex(), Terraria.Tile.type, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.Recipe.CollectItemsFromChests(), and Terraria.GameContent.QuickStacking.QuickStackToNearbyBanks().