Terraria Decompiled: Terraria.WorldItem.FindOwner
FindOwner()
void Terraria.WorldItem.FindOwner () inline
Definition at line 474 of file WorldItem.cs.
        {
            if (Main.netMode == 1 && this.shimmerTime > 0f)
            {
                this.keepTime = 0;
            }
            if (this.keepTime > 0)
            {
                return;
            }
            int num = this.playerIndexTheItemIsReservedFor;
            int num2 = 255;
            bool flag = true;
            if (this.type == 267 && this.ownIgnore != -1)
            {
                flag = false;
            }
            if (EmergencyStacking.HasPendingTransferInvolving(this))
            {
                num2 = 255;
            }
            else if (this.shimmerTime > 0f)
            {
                num2 = 255;
            }
            else if (flag)
            {
                float num3 = (float)NPC.sWidth;
                for (int i = 0; i < 255; i++)
                {
                    if (this.ownIgnore != i)
                    {
                        Player player = Main.player[i];
                        if (player.active && !player.dead)
{
                            Player.ItemSpaceStatus itemSpaceStatus = player.ItemSpace(Main.item[this.whoAmI]);
                            if (player.CanPullItem(Main.item[this.whoAmI], itemSpaceStatus))
{
                                float num4 = Math.Abs(player.position.X + (float)(player.width / 2) - this.position.X - (float)(this.width / 2)) + Math.Abs(player.position.Y + (float)(player.height / 2) - this.position.Y - (float)this.height);
                                if (player.manaMagnet && (this.type == 184 || this.type == 1735 || this.type == 1868))
{
                                    num4 -= (float)Item.manaGrabRange;
                                }
                                if (player.lifeMagnet && (this.type == 58 || this.type == 1734 || this.type == 1867))
{
                                    num4 -= (float)Item.lifeGrabRange;
                                }
                                if (this.type == 4143)
{
                                    num4 -= (float)Item.manaGrabRange;
                                }
                                if (num3 > num4)
{
                                    num3 = num4;
                                    num2 = i;
                                }
                            }
                        }
                    }
                }
                if (Main.netMode != 0 && num2 != 255)
                {
                    Player player2 = Main.player[num2];
                    int itemGrabRange = player2.GetItemGrabRange(this);
                    Rectangle hitbox = player2.Hitbox;
                    hitbox.Inflate(itemGrabRange, itemGrabRange);
                    if (!hitbox.Intersects(base.Hitbox) && Wiring.IsHopperInRangeOf(this))
                    {
                        num2 = 255;
                    }
                }
            }
            if (num2 == num)
            {
                return;
            }
            if (Main.netMode == 1)
            {
                this.playerIndexTheItemIsReservedFor = 255;
                NetMessage.SendData(39, -1, -1, null, this.whoAmI, 0f, 0f, 0f, 0, 0, 0);
                return;
            }
            if (num != Main.myPlayer && Main.player[num].active)
            {
                this.playerIndexTheItemIsReservedFor = num;
                if (this.timeSinceTheItemHasBeenReservedForSomeone >= 0)
                {
                    this.timeSinceTheItemHasBeenReservedForSomeone = -1;
                    NetMessage.SendData(39, num, -1, null, this.whoAmI, 0f, 0f, 0f, 0, 0, 0);
                    return;
                }
            }
            else
            {
                this.playerIndexTheItemIsReservedFor = num2;
                this.timeSinceTheItemHasBeenReservedForSomeone = 0;
                NetMessage.SendData(22, -1, -1, null, this.whoAmI, 0f, 0f, 0f, 0, 0, 0);
            }
        }
References System.Math.Abs(), Terraria.Player.active, Terraria.Player.CanPullItem(), Terraria.Player.dead, Terraria.Player.GetItemGrabRange(), Terraria.GameContent.EmergencyStacking.HasPendingTransferInvolving(), Terraria.Entity.height, Terraria.Entity.Hitbox, Microsoft.Xna.Framework.Rectangle.Inflate(), Microsoft.Xna.Framework.Rectangle.Intersects(), Terraria.Wiring.IsHopperInRangeOf(), Terraria.Main.item, Terraria.Player.ItemSpace(), Terraria.WorldItem.keepTime, Terraria.Item.lifeGrabRange, Terraria.Player.lifeMagnet, Terraria.Item.manaGrabRange, Terraria.Player.manaMagnet, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.WorldItem.ownIgnore, Terraria.Main.player, Terraria.WorldItem.playerIndexTheItemIsReservedFor, Terraria.Entity.position, Terraria.NetMessage.SendData(), Terraria.WorldItem.shimmerTime, Terraria.NPC.sWidth, Terraria.WorldItem.timeSinceTheItemHasBeenReservedForSomeone, Terraria.WorldItem.type, Terraria.Entity.whoAmI, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.MessageBuffer.GetData(), Terraria.GameContent.EmergencyStacking.RequestOwnershipReleaseForPendingTransfers(), Terraria.Main.UpdateClient(), and Terraria.Main.UpdateServer().