Terraria Decompiled: CsvHelper.Configuration.CsvClassMap.References
References()
virtual CsvPropertyReferenceMap CsvHelper.Configuration.CsvClassMap< T >.References (Type type, Expression< Func< T, object > > expression, params object[] constructorArgs) inline protected virtual
Definition at line 52 of file CsvClassMap.2.cs.
        {
            PropertyInfo property = ReflectionHelper.GetProperty<T>(expression);
            CsvPropertyReferenceMap csvPropertyReferenceMap = Enumerable.SingleOrDefault<CsvPropertyReferenceMap>(this.ReferenceMaps, (CsvPropertyReferenceMap m) => m.Data.Property == property || (m.Data.Property.Name == property.Name && (m.Data.Property.DeclaringType.IsAssignableFrom(property.DeclaringType) || property.DeclaringType.IsAssignableFrom(m.Data.Property.DeclaringType))));
            if (csvPropertyReferenceMap != null)
            {
                return csvPropertyReferenceMap;
            }
            CsvClassMap csvClassMap = (CsvClassMap)ReflectionHelper.CreateInstance(type, constructorArgs);
            csvClassMap.CreateMap();
            csvClassMap.ReIndex(base.GetMaxIndex() + 1);
            CsvPropertyReferenceMap csvPropertyReferenceMap2 = new CsvPropertyReferenceMap(property, csvClassMap);
            this.ReferenceMaps.Add(csvPropertyReferenceMap2);
            return csvPropertyReferenceMap2;
        }
References CsvHelper.ReflectionHelper.CreateInstance(), CsvHelper.Configuration.CsvClassMap< T >.CreateMap(), CsvHelper.Configuration.CsvClassMap< T >.CsvClassMap(), System.Reflection.MemberInfo.DeclaringType, System.Reflection.MemberInfo.Name, CsvHelper.Configuration.CsvClassMap< T >.property, CsvHelper.Configuration.CsvClassMap< T >.ReferenceMaps, and CsvHelper.Configuration.CsvClassMap< T >.ReIndex().