Terraria Decompiled: CsvHelper.Configuration.CsvClassMap.GetMaxIndex
GetMaxIndex()
int CsvHelper.Configuration.CsvClassMap< T >.GetMaxIndex () inline package
Definition at line 87 of file CsvClassMap.cs.
        {
            if (this.PropertyMaps.Count == 0 && this.ReferenceMaps.Count == 0)
            {
                return -1;
            }
            List<int> list = new List<int>();
            if (this.PropertyMaps.Count > 0)
            {
                list.Add(Enumerable.Max<CsvPropertyMap>(this.PropertyMaps, (CsvPropertyMap pm) => pm.Data.Index));
            }
            list.AddRange(Enumerable.Select<CsvPropertyReferenceMap, int>(this.ReferenceMaps, (CsvPropertyReferenceMap referenceMap) => referenceMap.GetMaxIndex()));
            return Enumerable.Max(list);
        }
References System.Collections.Generic.List< T >.Add(), CsvHelper.Configuration.CsvPropertyMapCollection.Count, CsvHelper.Configuration.CsvPropertyMap.Data, CsvHelper.Configuration.CsvPropertyReferenceMap.GetMaxIndex(), CsvHelper.Configuration.CsvPropertyMapData.Index, System.list, and CsvHelper.Configuration.CsvClassMap< T >.PropertyMaps.
Referenced by CsvHelper.Configuration.CsvClassMap< T >.AutoMapInternal(), CsvHelper.Configuration.CsvPropertyReferenceMap.GetMaxIndex(), and CsvHelper.Configuration.CsvClassMap< T >.PropertyMap< T >().