Terraria Decompiled: System.WindowsConsoleDriver.Clear
Clear()
void System.WindowsConsoleDriver.Clear () inline
Implements System.IConsoleDriver.
Definition at line 445 of file WindowsConsoleDriver.cs.
        {
            Coord coord = default(Coord);
            ConsoleScreenBufferInfo consoleScreenBufferInfo = default(ConsoleScreenBufferInfo);
            WindowsConsoleDriver.GetConsoleScreenBufferInfo(this.outputHandle, out consoleScreenBufferInfo);
            int num = (int)(consoleScreenBufferInfo.Size.X * consoleScreenBufferInfo.Size.Y);
            int num2;
            WindowsConsoleDriver.FillConsoleOutputCharacter(this.outputHandle, ' ', num, coord, out num2);
            WindowsConsoleDriver.GetConsoleScreenBufferInfo(this.outputHandle, out consoleScreenBufferInfo);
            WindowsConsoleDriver.FillConsoleOutputAttribute(this.outputHandle, consoleScreenBufferInfo.Attribute, num, coord, out num2);
            WindowsConsoleDriver.SetConsoleCursorPosition(this.outputHandle, coord);
        }
References System.ConsoleScreenBufferInfo.Attribute, System.WindowsConsoleDriver.FillConsoleOutputAttribute(), System.WindowsConsoleDriver.FillConsoleOutputCharacter(), System.WindowsConsoleDriver.GetConsoleScreenBufferInfo(), int, System.WindowsConsoleDriver.outputHandle, System.WindowsConsoleDriver.SetConsoleCursorPosition(), System.ConsoleScreenBufferInfo.Size, System.Coord.X, and System.Coord.Y.