Terraria Decompiled: System.WindowsConsoleDriver.MoveBufferArea
MoveBufferArea()
unsafe void System.WindowsConsoleDriver.MoveBufferArea (int sourceLeft, int sourceTop, int sourceWidth, int sourceHeight, int targetLeft, int targetTop, char sourceChar, ConsoleColor sourceForeColor, ConsoleColor sourceBackColor) inline
Implements System.IConsoleDriver.
Definition at line 459 of file WindowsConsoleDriver.cs.
        {
            if (sourceForeColor < ConsoleColor.Black)
            {
                throw new ArgumentException("Cannot be less than 0.", "sourceForeColor");
            }
            if (sourceBackColor < ConsoleColor.Black)
            {
                throw new ArgumentException("Cannot be less than 0.", "sourceBackColor");
            }
            if (sourceWidth == 0 || sourceHeight == 0)
            {
                return;
            }
            ConsoleScreenBufferInfo consoleScreenBufferInfo = default(ConsoleScreenBufferInfo);
            WindowsConsoleDriver.GetConsoleScreenBufferInfo(this.outputHandle, out consoleScreenBufferInfo);
            CharInfo[] array = new CharInfo[sourceWidth * sourceHeight];
            Coord coord = new Coord(sourceWidth, sourceHeight);
            Coord coord2 = new Coord(0, 0);
            SmallRect smallRect = new SmallRect(sourceLeft, sourceTop, sourceLeft + sourceWidth - 1, sourceTop + sourceHeight - 1);
            fixed (CharInfo* ptr = &array[0])
            {
                void* ptr2 = (void*)ptr;
                if (!WindowsConsoleDriver.ReadConsoleOutput(this.outputHandle, ptr2, coord, coord2, ref smallRect))
                {
                    throw new ArgumentException(string.Empty, "Cannot read from the specified coordinates.");
                }
            }
            short num = WindowsConsoleDriver.GetAttrForeground(0, sourceForeColor);
            num = WindowsConsoleDriver.GetAttrBackground((int)num, sourceBackColor);
            coord2 = new Coord(sourceLeft, sourceTop);
            int i = 0;
            while (i < sourceHeight)
            {
                int num2;
                WindowsConsoleDriver.FillConsoleOutputCharacter(this.outputHandle, sourceChar, sourceWidth, coord2, out num2);
                WindowsConsoleDriver.FillConsoleOutputAttribute(this.outputHandle, num, sourceWidth, coord2, out num2);
                i++;
                coord2.Y += 1;
            }
            coord2 = new Coord(0, 0);
            smallRect = new SmallRect(targetLeft, targetTop, targetLeft + sourceWidth - 1, targetTop + sourceHeight - 1);
            if (!WindowsConsoleDriver.WriteConsoleOutput(this.outputHandle, array, coord, coord2, ref smallRect))
            {
                throw new ArgumentException(string.Empty, "Cannot write to the specified coordinates.");
            }
        }
References System.array, System.WindowsConsoleDriver.FillConsoleOutputAttribute(), System.WindowsConsoleDriver.FillConsoleOutputCharacter(), System.WindowsConsoleDriver.GetAttrBackground(), System.WindowsConsoleDriver.GetAttrForeground(), System.WindowsConsoleDriver.GetConsoleScreenBufferInfo(), System.WindowsConsoleDriver.outputHandle, System.WindowsConsoleDriver.ReadConsoleOutput(), and System.WindowsConsoleDriver.WriteConsoleOutput().