Terraria Decompiled: System.WindowsConsoleDriver.SetWindowPosition
SetWindowPosition()
void System.WindowsConsoleDriver.SetWindowPosition (int left, int top) inline
Implements System.IConsoleDriver.
Definition at line 582 of file WindowsConsoleDriver.cs.
        {
            ConsoleScreenBufferInfo consoleScreenBufferInfo = default(ConsoleScreenBufferInfo);
            WindowsConsoleDriver.GetConsoleScreenBufferInfo(this.outputHandle, out consoleScreenBufferInfo);
            SmallRect window = consoleScreenBufferInfo.Window;
            window.Left = (short)left;
            window.Top = (short)top;
            if (!WindowsConsoleDriver.SetConsoleWindowInfo(this.outputHandle, true, ref window))
            {
                throw new ArgumentOutOfRangeException("left/top", "Windows error " + Marshal.GetLastWin32Error().ToString());
            }
        }
References System.WindowsConsoleDriver.GetConsoleScreenBufferInfo(), System.Runtime.InteropServices.Marshal.GetLastWin32Error(), System.WindowsConsoleDriver.outputHandle, System.WindowsConsoleDriver.SetConsoleWindowInfo(), and System.ConsoleScreenBufferInfo.Window.