Terraria Decompiled: Terraria.Main.DrawThickCursor
DrawThickCursor()
static Vector2 Terraria.Main.DrawThickCursor (bool smart = false) inline static
Definition at line 48432 of file Main.cs.
        {
            if (!Main.ThickMouse)
            {
                return Vector2.Zero;
            }
            bool showGamepadCursor = PlayerInput.SettingsForUI.ShowGamepadCursor;
            if (Main.gameMenu && Main.alreadyGrabbingSunOrMoon)
            {
                return Vector2.Zero;
            }
            if (showGamepadCursor && PlayerInput.InvisibleGamepadInMenus)
            {
                return Vector2.Zero;
            }
            if (showGamepadCursor && Main.player[Main.myPlayer].dead && !Main.player[Main.myPlayer].ghost && !Main.gameMenu)
            {
                return Vector2.Zero;
            }
            if (showGamepadCursor && Main.player[Main.myPlayer].spectating >= 0)
            {
                return Vector2.Zero;
            }
            bool flag = UILinkPointNavigator.Available && !PlayerInput.InBuildingMode;
            Microsoft.Xna.Framework.Color color = Main.MouseBorderColor;
            int num = 11;
            num += smart.ToInt();
            for (int i = 0; i < 4; i++)
            {
                Vector2 vector = Vector2.Zero;
                switch (i)
                {
                case 0:
                    vector = new Vector2(0f, 1f);
                    break;
                case 1:
                    vector = new Vector2(1f, 0f);
                    break;
                case 2:
                    vector = new Vector2(0f, -1f);
                    break;
                case 3:
                    vector = new Vector2(-1f, 0f);
                    break;
                }
                vector *= 1f;
                vector += Vector2.One * 2f;
                Vector2 vector2 = new Vector2(2f);
                Microsoft.Xna.Framework.Rectangle? rectangle = null;
                float num2 = Main.cursorScale * 1.1f;
                if (showGamepadCursor)
                {
                    if (smart && !flag)
                    {
                        num = 13;
                        int num3 = 0;
                        vector = Vector2.One;
                        rectangle = new Microsoft.Xna.Framework.Rectangle?(TextureAssets.Cursors[num].Frame(2, 1, num3, 0, 0, 0));
                        vector2 = TextureAssets.Cursors[num].Frame(2, 1, num3, 0, 0, 0).Size() / 2f;
                        color *= Main.GamepadCursorAlpha;
                    }
                    else
                    {
                        num = 15;
                        vector = Vector2.One;
                        vector2 = TextureAssets.Cursors[num].Value.Size() / 2f;
                    }
                }
                Main.spriteBatch.Draw(TextureAssets.Cursors[num].Value, new Vector2((float)Main.mouseX, (float)Main.mouseY) + vector, rectangle, color, 0f, vector2, num2, SpriteEffects.None, 0f);
            }
            return new Vector2(2f);
        }
References Terraria.Main.alreadyGrabbingSunOrMoon, Terraria.GameContent.TextureAssets.Cursors, Terraria.Player.dead, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Main.gameMenu, Terraria.Main.GamepadCursorAlpha, Terraria.Player.ghost, Terraria.GameInput.PlayerInput.InBuildingMode, Terraria.GameInput.PlayerInput.InvisibleGamepadInMenus, Terraria.Main.MouseBorderColor, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Microsoft.Xna.Framework.Vector2.One, Terraria.Main.player, Terraria.GameInput.PlayerInput.SettingsForUI.ShowGamepadCursor, Terraria.Player.spectating, Terraria.Main.spriteBatch, Terraria.Main.ThickMouse, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.UI.IngameFancyUI.Draw(), Terraria.Utils.DrawCursorSingle(), Terraria.Main.DrawInterface_36_Cursor(), Terraria.Main.DrawMap(), and Terraria.Main.DrawMenu().