Terraria Decompiled: Terraria.Main.CheckForMoonEventsStartingTemporarySeasons
CheckForMoonEventsStartingTemporarySeasons()
static void Terraria.Main.CheckForMoonEventsStartingTemporarySeasons () inline static
Definition at line 9027 of file Main.cs.
        {
            if (Main.netMode == 1)
            {
                return;
            }
            bool flag = Main.forceHalloweenForToday;
            bool flag2 = Main.forceXMasForToday;
            Main.forceXMasForToday = false;
            Main.forceHalloweenForToday = false;
            int waveNumber = NPC.waveNumber;
            float waveKills = NPC.waveKills;
            if (Main.pumpkinMoon && waveNumber >= 15)
            {
                Main.forceHalloweenForToday = true;
            }
            if (Main.snowMoon && waveNumber >= 15)
            {
                Main.forceXMasForToday = true;
            }
            if (Main.forceHalloweenForever)
            {
                Main.forceHalloweenForToday = false;
            }
            if (Main.forceXMasForever)
            {
                Main.forceXMasForToday = false;
            }
            Microsoft.Xna.Framework.Color world = ChatColors.World;
            if (flag != Main.forceHalloweenForToday)
            {
                WorldGen.BroadcastText(NetworkText.FromKey(Main.forceHalloweenForToday ? "Misc.StartedVictoryHalloween" : "Misc.EndedVictoryHalloween", new object[0]), world);
            }
            if (flag2 != Main.forceXMasForToday)
            {
                WorldGen.BroadcastText(NetworkText.FromKey(Main.forceXMasForToday ? "Misc.StartedVictoryXmas" : "Misc.EndedVictoryXmas", new object[0]), world);
            }
        }
References Terraria.WorldGen.BroadcastText(), Terraria.Main.forceHalloweenForever, Terraria.Main.forceHalloweenForToday, Terraria.Main.forceXMasForever, Terraria.Main.forceXMasForToday, Terraria.Localization.NetworkText.FromKey(), Terraria.Main.netMode, Terraria.Main.pumpkinMoon, Terraria.Main.snowMoon, Terraria.NPC.waveKills, Terraria.NPC.waveNumber, and Terraria.Chat.ChatColors.World.
Referenced by Terraria.Main.UpdateTime_StartDay().