Terraria Decompiled: Terraria.Main.NPCChatText_DoNurseHeal
NPCChatText_DoNurseHeal()
static void Terraria.Main.NPCChatText_DoNurseHeal (int healCost) inline static
Definition at line 39844 of file Main.cs.
        {
            SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
            if (healCost > 0)
            {
                if (Main.player[Main.myPlayer].BuyItem((long)healCost, -1))
                {
                    AchievementsHelper.HandleNurseService(healCost);
                    SoundEngine.PlaySound(SoundID.Item4, -1, -1, 0f, 1f);
                    Main.player[Main.myPlayer].HealEffect(Main.player[Main.myPlayer].statLifeMax2 - Main.player[Main.myPlayer].statLife, true);
                    if ((double)Main.player[Main.myPlayer].statLife < (double)Main.player[Main.myPlayer].statLifeMax2 * 0.25)
                    {
                        Main.npcChatText = Lang.dialog(227, false);
                    }
                    else if ((double)Main.player[Main.myPlayer].statLife < (double)Main.player[Main.myPlayer].statLifeMax2 * 0.5)
                    {
                        Main.npcChatText = Lang.dialog(228, false);
                    }
                    else if ((double)Main.player[Main.myPlayer].statLife < (double)Main.player[Main.myPlayer].statLifeMax2 * 0.75)
                    {
                        Main.npcChatText = Lang.dialog(229, false);
                    }
                    else
                    {
                        Main.npcChatText = Lang.dialog(230, false);
                    }
                    Main.player[Main.myPlayer].statLife = Main.player[Main.myPlayer].statLifeMax2;
                    for (int i = 0; i < Player.maxBuffs; i++)
                    {
                        int num = Main.player[Main.myPlayer].buffType[i];
                        if (Main.debuff[num] && Main.player[Main.myPlayer].buffTime[i] > 0 && (num < 0 || num >= BuffID.Count || !BuffID.Sets.NurseCannotRemoveDebuff[num]))
{
                            Main.player[Main.myPlayer].DelBuff(i);
                            i = -1;
                        }
                    }
                }
                else
                {
                    int num2 = Main.rand.Next(3);
                    if (num2 == 0)
                    {
                        Main.npcChatText = Lang.dialog(52, false);
                    }
                    if (num2 == 1)
                    {
                        Main.npcChatText = Lang.dialog(53, false);
                    }
                    if (num2 == 2)
                    {
                        Main.npcChatText = Lang.dialog(54, false);
                    }
                }
            }
            else
            {
                int num3 = Main.rand.Next(3);
                if (!ChildSafety.Disabled)
                {
                    num3 = Main.rand.Next(1, 3);
                }
                if (num3 == 0)
                {
                    Main.npcChatText = Lang.dialog(55, false);
                }
                else if (num3 == 1)
                {
                    Main.npcChatText = Lang.dialog(56, false);
                }
                else if (num3 == 2)
                {
                    Main.npcChatText = Lang.dialog(57, false);
                }
            }
            Main.DoNPCPortraitHop();
        }
References Terraria.Player.buffTime, Terraria.Player.buffType, Terraria.Player.BuyItem(), Terraria.ID.BuffID.Count, Terraria.Main.debuff, Terraria.Player.DelBuff(), Terraria.Lang.dialog(), Terraria.GameContent.ChildSafety.Disabled, Terraria.Main.DoNPCPortraitHop(), Terraria.GameContent.Achievements.AchievementsHelper.HandleNurseService(), Terraria.Player.HealEffect(), Terraria.ID.SoundID.Item4, Terraria.Player.maxBuffs, Terraria.Main.myPlayer, Terraria.Utilities.UnifiedRandom.Next(), Terraria.ID.BuffID.Sets.NurseCannotRemoveDebuff, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.rand, Terraria.Player.statLife, and Terraria.Player.statLifeMax2.
Referenced by Terraria.GameContent.NPCInteractions.Actions.NurseHeal.Interact().