Terraria Decompiled: Terraria.Main.DoDraw_WallsAndBlacks
DoDraw_WallsAndBlacks()
void Terraria.Main.DoDraw_WallsAndBlacks () inline private
Definition at line 64498 of file Main.cs.
        {
            if (Main.drawToScreen)
            {
                Main.spriteBatch.End();
                this.DrawBlack(false, false);
                this.DrawWalls(false);
                Main.spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, Main.DefaultSamplerState, DepthStencilState.None, Main.Rasterizer, null, Main.Transform);
            }
            else
            {
                Main.spriteBatch.Draw(Main.wallTarget.Texture, Main.wallTarget.Position - Main.screenPosition, Microsoft.Xna.Framework.Color.White);
            }
            Overlays.Scene.Draw(Main.spriteBatch, RenderLayers.Walls);
        }
References Microsoft.Xna.Framework.Graphics.BlendState.AlphaBlend, Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(), Terraria.Main.DefaultSamplerState, Terraria.Graphics.Effects.OverlayManager.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Main.drawToScreen, Microsoft.Xna.Framework.Graphics.SpriteBatch.End(), Microsoft.Xna.Framework.Graphics.DepthStencilState.None, Terraria.Graphics.WorldSceneLayerTarget.Position, Terraria.Main.Rasterizer, Terraria.Graphics.Effects.Overlays.Scene, Terraria.Main.screenPosition, Terraria.Main.spriteBatch, Terraria.Graphics.WorldSceneLayerTarget.Texture, Terraria.Main.Transform, Terraria.Main.wallTarget, and Microsoft.Xna.Framework.Color.White.