Terraria Decompiled: Terraria.Main.RegisterItemAnimation
RegisterItemAnimation()
static void Terraria.Main.RegisterItemAnimation (int index, DrawAnimation animation) inline static
Definition at line 1556 of file Main.cs.
        {
            if (!Main.itemAnimationsRegistered.Contains(index))
            {
                Main.itemAnimationsRegistered.Add(index);
            }
            Main.itemAnimations[index] = animation;
        }
References System.Collections.Generic.List< T >.Add(), System.Collections.Generic.List< T >.Contains(), System.index, Terraria.Main.itemAnimations, and Terraria.Main.itemAnimationsRegistered.
Referenced by Terraria.Main.InitializeItemAnimations().