Terraria Decompiled: Terraria.Main.GetWorldPathFromName
GetWorldPathFromName()
static string Terraria.Main.GetWorldPathFromName (string worldName, bool cloudSave) inline static
Definition at line 2954 of file Main.cs.
        {
            char[] invalidFileNameChars = Path.GetInvalidFileNameChars();
            string text = "";
            foreach (char c in worldName)
            {
                char c2;
                if (invalidFileNameChars.Contains(c))
                {
                    c2 = '-';
                }
                else if (c == ' ')
                {
                    c2 = '_';
                }
                else
                {
                    c2 = c;
                }
                text += c2.ToString();
            }
            text = text.Replace(".", "_");
            text = text.Replace("*", "_");
            string text2 = (cloudSave ? Main.CloudWorldPath : Main.WorldPath);
            if (FileUtilities.GetFullPath(text2 + Path.DirectorySeparatorChar.ToString() + text + ".wld", cloudSave).StartsWith("\\\\.\\", StringComparison.Ordinal))
            {
                text += "_";
            }
            if (FileUtilities.Exists(text2 + Path.DirectorySeparatorChar.ToString() + text + ".wld", cloudSave))
            {
                int num = 2;
                while (FileUtilities.Exists(string.Concat(new object[]
                {
                    text2,
                    Path.DirectorySeparatorChar.ToString(),
                    text,
                    num,
                    ".wld"
                }), cloudSave))
                {
                    num++;
                }
                text += num;
            }
            return text2 + Path.DirectorySeparatorChar.ToString() + text + ".wld";
        }
References System.IO.Path.DirectorySeparatorChar, Terraria.Utilities.FileUtilities.Exists(), Terraria.Utilities.FileUtilities.GetFullPath(), System.IO.Path.GetInvalidFileNameChars(), System.text, Terraria.Main.worldName, and Terraria.Main.WorldPath.
Referenced by Terraria.IO.WorldFileData.CopyToLocal(), Terraria.IO.WorldFile.CreateMetadata(), Terraria.IO.WorldFileData.MoveToCloud(), and Terraria.IO.WorldFileData.MoveToLocal().