Terraria Decompiled: Terraria.Main.ChangeRain
ChangeRain()
static void Terraria.Main.ChangeRain (bool instant = false, float? strengthOverride = null) inline static
Definition at line 66007 of file Main.cs.
        {
            float num;
            if (strengthOverride != null)
            {
                num = strengthOverride.Value;
            }
            else if (Main.cloudBGActive >= 1f || (double)Main.numClouds > 150.0)
            {
                if (Main.rand.Next(3) == 0)
                {
                    num = (float)Main.rand.Next(20, 91) * 0.01f;
                }
                else
                {
                    num = (float)Main.rand.Next(40, 91) * 0.01f;
                }
            }
            else if ((double)Main.numClouds > 100.0)
            {
                if (Main.rand.Next(3) == 0)
                {
                    num = (float)Main.rand.Next(10, 71) * 0.01f;
                }
                else
                {
                    num = (float)Main.rand.Next(20, 61) * 0.01f;
                }
            }
            else if (Main.rand.Next(3) == 0)
            {
                num = (float)Main.rand.Next(5, 41) * 0.01f;
            }
            else
            {
                num = (float)Main.rand.Next(5, 31) * 0.01f;
            }
            if (Main.IsRainingForever)
            {
                num = Math.Max(num, 0.01f);
            }
            Main.maxRaining = num;
            if (instant)
            {
                Main.cloudAlpha = Main.maxRaining;
            }
        }
References Terraria.Main.cloudBGActive, Terraria.Main.IsRainingForever, System.Math.Max(), Terraria.Main.maxRaining, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.numClouds, and Terraria.Main.rand.
Referenced by Terraria.WorldGen.SecretSeed.DoRainsForAYear(), Terraria.Main.StartRain(), and Terraria.Main.UpdateTime().