Terraria Decompiled: Terraria.Main.DrawNPCDirect_Faeling
DrawNPCDirect_Faeling()
static void Terraria.Main.DrawNPCDirect_Faeling (SpriteBatch mySpriteBatch, NPC rCurrentNPC, ref Vector2 screenPos, int typeCache, ref Microsoft::Xna::Framework::Color npcColor, ref Vector2 halfSize, SpriteEffects npcSpriteEffect) inline static private
Definition at line 25403 of file Main.cs.
        {
            Texture2D value = TextureAssets.Npc[typeCache].Value;
            Vector2 vector = rCurrentNPC.Center - screenPos;
            int num = 5;
            int num2 = 4;
            float num3 = ((float)rCurrentNPC.whoAmI * 0.11f + (float)Main.timeForVisualEffects / 360f) % 1f;
            Microsoft.Xna.Framework.Color color = Main.hslToRgb(num3, 1f, 0.65f, byte.MaxValue);
            color.A /= 2;
            float rotation = rCurrentNPC.rotation;
            Microsoft.Xna.Framework.Rectangle rectangle = value.Frame(num2, num, 0, rCurrentNPC.frame.Y, 0, 0);
            Vector2 vector2 = rectangle.Size() / 2f;
            float scale = rCurrentNPC.scale;
            Microsoft.Xna.Framework.Rectangle rectangle2 = value.Frame(num2, num, 2, 0, 0, 0);
            Microsoft.Xna.Framework.Color color2 = new Microsoft.Xna.Framework.Color(255, 255, 255, 0) * 1f;
            int num4 = rCurrentNPC.oldPos.Length;
            int num5 = num4 - 1 - 5;
            int num6 = 5;
            int num7 = 3;
            float num8 = 32f;
            float num9 = 16f;
            float num10 = new Vector2(num8, num9).Length();
            float num11 = Utils.Remap(Vector2.Distance(rCurrentNPC.oldPos[num5], rCurrentNPC.position), 0f, num10, 0f, 100f, true);
            num11 = (float)((int)num11 / 5);
            num11 *= 5f;
            num11 /= 100f;
            num9 *= num11;
            num8 *= num11;
            float num12 = 9f;
            float num13 = 0.5f;
            float num14 = 3.1415927f;
            for (int i = num5; i >= num6; i -= num7)
            {
                Vector2 vector3 = rCurrentNPC.oldPos[i] - rCurrentNPC.position;
                float num15 = Utils.Remap((float)i, 0f, (float)num4, 1f, 0f, true);
                float num16 = 1f - num15;
                Vector2 vector4 = new Vector2((float)Math.Sin((double)((float)rCurrentNPC.whoAmI / 17f) + Main.timeForVisualEffects / (double)num12 + (double)(num15 * 2f * 6.2831855f)) * num9, -num8) * num16;
                vector3 += vector4.RotatedBy((double)num14, default(Vector2));
                Microsoft.Xna.Framework.Color color3 = Main.hslToRgb((num3 + num16 * num13) % 1f, 1f, 0.5f, byte.MaxValue);
                color3.A = 0;
                mySpriteBatch.Draw(value, vector + vector3, new Microsoft.Xna.Framework.Rectangle?(rectangle2), color3 * num15 * 0.16f, rotation, vector2, scale * Utils.Remap(num15 * num15, 0f, 1f, 0f, 2.5f, true), npcSpriteEffect, 0f);
            }
            mySpriteBatch.Draw(value, vector, new Microsoft.Xna.Framework.Rectangle?(rectangle2), color2, rotation, vector2, scale, npcSpriteEffect, 0f);
            Microsoft.Xna.Framework.Rectangle rectangle3 = value.Frame(num2, num, 1, rCurrentNPC.frame.Y, 0, 0);
            Microsoft.Xna.Framework.Color white = Microsoft.Xna.Framework.Color.White;
            white.A /= 2;
            mySpriteBatch.Draw(value, vector, new Microsoft.Xna.Framework.Rectangle?(rectangle3), white, rotation, vector2, scale, npcSpriteEffect, 0f);
            mySpriteBatch.Draw(value, vector, new Microsoft.Xna.Framework.Rectangle?(rectangle), color, rotation, vector2, scale, npcSpriteEffect, 0f);
            float num17 = MathHelper.Clamp((float)Math.Sin(Main.timeForVisualEffects / 60.0) * 0.3f + 0.3f, 0f, 1f);
            float num18 = 0.8f + (float)Math.Sin(Main.timeForVisualEffects / 15.0 * 6.2831854820251465) * 0.3f;
            Microsoft.Xna.Framework.Rectangle rectangle4 = value.Frame(num2, num, 3, rCurrentNPC.whoAmI % num, 0, 0);
            Microsoft.Xna.Framework.Color color4 = Microsoft.Xna.Framework.Color.Lerp(color, new Microsoft.Xna.Framework.Color(255, 255, 255, 0), 0.5f) * num17;
            mySpriteBatch.Draw(value, vector, new Microsoft.Xna.Framework.Rectangle?(rectangle4), color4, rotation, vector2, scale * num18, SpriteEffects.None, 0f);
            Microsoft.Xna.Framework.Rectangle rectangle5 = value.Frame(num2, num, 3, 1, 0, 0);
            Microsoft.Xna.Framework.Color color5 = Microsoft.Xna.Framework.Color.Lerp(color, new Microsoft.Xna.Framework.Color(255, 255, 255, 0), 0.5f) * num17;
            mySpriteBatch.Draw(value, vector, new Microsoft.Xna.Framework.Rectangle?(rectangle5), color5, rotation, vector2, scale * num18, SpriteEffects.None, 0f);
        }
References Microsoft.Xna.Framework.MathHelper.Clamp(), Microsoft.Xna.Framework.Vector2.Distance(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.NPC.frame, Terraria.Main.hslToRgb(), Microsoft.Xna.Framework.Vector2.Length(), Microsoft.Xna.Framework.Color.Lerp(), System.Reflection.MaxValue, Terraria.GameContent.TextureAssets.Npc, Terraria.NPC.oldPos, Terraria.Entity.position, Terraria.Utils.Remap(), Terraria.NPC.rotation, Terraria.NPC.scale, System.Math.Sin(), Terraria.Main.timeForVisualEffects, System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Color.White, Terraria.Entity.whoAmI, and Microsoft.Xna.Framework.Rectangle.Y.
Referenced by Terraria.Main.DrawNPCDirect().