Terraria Decompiled: Terraria.Main.DrawWOFRopeToTheHungry
DrawWOFRopeToTheHungry()
static void Terraria.Main.DrawWOFRopeToTheHungry (int i) inline static private
Definition at line 37887 of file Main.cs.
        {
            float num = Main.npc[Main.wofNPCIndex].position.X + (float)(Main.npc[Main.wofNPCIndex].width / 2);
            float num2 = Main.npc[Main.wofNPCIndex].position.Y;
            float num3 = (float)(Main.wofDrawAreaBottom - Main.wofDrawAreaTop);
            bool flag = false;
            if (Main.npc[i].frameCounter > 7.0)
            {
                flag = true;
            }
            num2 = (float)Main.wofDrawAreaTop + num3 * Main.npc[i].ai[0];
            float scale = Main.npc[i].scale;
            float x = Main.npc[i].Center.X;
            float num4 = Main.npc[i].Bottom.Y - (float)Main.npc[i].height * 0.5f * scale;
            Vector2 vector = new Vector2(x, num4);
            vector += Main.npc[i].netOffset;
            float num5 = num - vector.X;
            float num6 = num2 - vector.Y;
            float num7 = (float)Math.Atan2((double)num6, (double)num5) - 1.57f;
            bool flag2 = true;
            while (flag2)
            {
                SpriteEffects spriteEffects = SpriteEffects.None;
                if (flag)
                {
                    spriteEffects = SpriteEffects.FlipHorizontally;
                    flag = false;
                }
                else
                {
                    flag = true;
                }
                int num8 = 28;
                int num9 = (int)(40f * scale);
                float num10 = (float)Math.Sqrt((double)(num5 * num5 + num6 * num6));
                if (num10 < (float)num9)
                {
                    num8 = (int)num10 - num9 + 28;
                    flag2 = false;
                }
                num10 = 28f * scale / num10;
                num5 *= num10;
                num6 *= num10;
                vector.X += num5;
                vector.Y += num6;
                num5 = num - vector.X;
                num6 = num2 - vector.Y;
                Microsoft.Xna.Framework.Color color = Lighting.GetColor((int)vector.X / 16, (int)(vector.Y / 16f));
                Main.spriteBatch.Draw(TextureAssets.Chain12.Value, new Vector2(vector.X - Main.screenPosition.X, vector.Y - Main.screenPosition.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain4.Width(), num8)), color, num7, new Vector2((float)TextureAssets.Chain4.Width() * 0.5f, (float)TextureAssets.Chain4.Height() * 0.5f), scale, spriteEffects, 0f);
            }
        }
References Terraria.NPC.ai, System.Math.Atan2(), Terraria.Entity.Bottom, Terraria.Entity.Center, Terraria.GameContent.TextureAssets.Chain12, Terraria.GameContent.TextureAssets.Chain4, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.NPC.frameCounter, Terraria.Lighting.GetColor(), Terraria.Entity.height, int, Terraria.NPC.netOffset, Terraria.Main.npc, Terraria.Entity.position, Terraria.NPC.scale, Terraria.Main.screenPosition, Terraria.Main.spriteBatch, System.Math.Sqrt(), ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Entity.width, Terraria.Main.wofDrawAreaBottom, Terraria.Main.wofDrawAreaTop, Terraria.Main.wofNPCIndex, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Main.DrawWoF().