Terraria Decompiled: Terraria.Main.DrawBackground_DirtBackground
DrawBackground_DirtBackground()
void Terraria.Main.DrawBackground_DirtBackground (float localShimmerAlpha, int q1, int q2, ref Vector2 drawOffset, ref Vector3 backgroundColor) inline private
Definition at line 53975 of file Main.cs.
        {
            int rockTransitionPoint = this.GetRockTransitionPoint();
            float x = backgroundColor.X;
            float y = backgroundColor.Y;
            float z = backgroundColor.Z;
            this.bgTopY = (float)Main.worldSurface * 16f - Main.screenPosition.Y + 16f;
            bool flag = false;
            if (Main.worldSurface * 16.0 <= (double)(Main.screenPosition.Y + (float)Main.screenHeight + (float)Main.offScreenRange))
            {
                this.bgParallax = (double)Main.caveParallax;
                int num = TextureAssets.Background[this._drawBackground_backTexture[1]].Width() - 32;
                this.bgStartX = (int)(-Math.IEEERemainder((double)num + (double)Main.screenPosition.X * this.bgParallax, (double)num) - (double)(num / 2)) - (int)drawOffset.X;
                this.bgLoops = (Main.screenWidth + (int)drawOffset.X * 2) / num + 2;
                if (Main.worldSurface * 16.0 < (double)(Main.screenPosition.Y - 16f))
                {
                    this.bgStartY = (int)(Math.IEEERemainder((double)this.bgTopY, (double)Main.backgroundHeight[2]) - (double)Main.backgroundHeight[2]);
                    this.bgLoopsY = (Main.screenHeight - this.bgStartY + (int)drawOffset.Y * 2) / Main.backgroundHeight[2] + 1;
                }
                else
                {
                    this.bgStartY = (int)this.bgTopY;
                    this.bgLoopsY = (int)((float)Main.screenHeight - this.bgTopY + drawOffset.Y * 2f) / Main.backgroundHeight[2] + 1;
                }
                if ((float)rockTransitionPoint < Main.Camera.ScaledPosition.Y + (float)Main.screenHeight - 16f)
                {
                    this.bgLoopsY = (int)((float)rockTransitionPoint - Main.screenPosition.Y - (float)this.bgStartY) / Main.backgroundHeight[2];
                    flag = true;
                }
                int num2 = (int)((float)Math.Round((double)(-(double)((float)Math.IEEERemainder((double)((float)this.bgStartX + Main.screenPosition.X), 16.0)))));
                if (num2 == -8)
                {
                    num2 = 8;
                }
                for (int i = 0; i < this.bgLoops; i++)
                {
                    for (int j = 0; j < this.bgLoopsY; j++)
                    {
                        for (int k = 0; k < num / 16; k++)
{
                            for (int l = 0; l < 6; l++)
{
                                float num3 = (float)(this.bgStartY + j * 96 + l * 16 + 8);
                                int num4 = (int)(((float)(this.bgStartX + num * i + k * 16 + 8) + Main.screenPosition.X) / 16f);
                                int num5 = (int)((num3 + Main.screenPosition.Y) / 16f);
                                Microsoft.Xna.Framework.Color color = Lighting.GetColor(num4, num5);
                                if (WorldGen.InWorld(num4, num5, 0))
{
                                    if (Main.tile[num4, num5] == null)
{
                                        Main.tile[num4, num5] = new Tile();
                                    }
                                    if (localShimmerAlpha == 0f && (color.R > 0 || color.G > 0 || color.B > 0))
{
                                        if (!Main.drawToScreen)
{
                                            VertexColors vertexColors;
                                            Lighting.GetCornerColors(num4, num5, out vertexColors, 1f);
                                            vertexColors.BottomLeftColor = new Microsoft.Xna.Framework.Color(vertexColors.BottomLeftColor.ToVector3() * backgroundColor);
                                            vertexColors.BottomRightColor = new Microsoft.Xna.Framework.Color(vertexColors.BottomRightColor.ToVector3() * backgroundColor);
                                            Main.tileBatch.Draw(TextureAssets.Background[this._drawBackground_backTexture[1]].Value, new Vector2((float)(this.bgStartX + num * i + 16 * k + num2), (float)(this.bgStartY + Main.backgroundHeight[this._drawBackground_backTexture[1]] * j + 16 * l)) + drawOffset, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * k + num2 + 16, 16 * l, 16, 16)), vertexColors, Vector2.Zero, 1f, SpriteEffects.None);
                                        }
                                        else
{
                                            if (((int)color.R > q1 || (double)color.G > (double)q1 * 1.1 || (double)color.B > (double)q1 * 1.2) && !Main.tile[num4, num5].active() && Main.WallLightAt(num4, num5) && Main.ugBackTransition == 0f)
{
                                                Lighting.GetColor9Slice(num4, num5, ref this._drawbackground_colorSlices);
                                                try
{
                                                    for (int m = 0; m < 9; m++)
{
                                                        int num6 = 0;
                                                        int num7 = 0;
                                                        int num8 = 4;
                                                        int num9 = 4;
                                                        Microsoft.Xna.Framework.Color color2 = color;
                                                        Microsoft.Xna.Framework.Color color3 = color;
                                                        switch (m)
{
                                                        case 0:
                                                            if (!Main.tile[num4 - 1, num5 - 1].active())
{
                                                                color3 = this._drawbackground_colorSlices[m];
                                                            }
                                                            break;
                                                        case 1:
                                                            num8 = 8;
                                                            num6 = 4;
                                                            if (!Main.tile[num4, num5 - 1].active())
{
                                                                color3 = this._drawbackground_colorSlices[m];
                                                            }
                                                            break;
                                                        case 2:
                                                            num6 = 12;
                                                            if (!Main.tile[num4 + 1, num5 - 1].active())
{
                                                                color3 = this._drawbackground_colorSlices[m];
                                                            }
                                                            break;
                                                        case 3:
                                                            num9 = 8;
                                                            num7 = 4;
                                                            if (!Main.tile[num4 - 1, num5].active())
{
                                                                color3 = this._drawbackground_colorSlices[m];
                                                            }
                                                            break;
                                                        case 4:
                                                            num8 = 8;
                                                            num9 = 8;
                                                            num6 = 4;
                                                            num7 = 4;
                                                            break;
                                                        case 5:
                                                            num6 = 12;
                                                            num7 = 4;
                                                            num9 = 8;
                                                            if (!Main.tile[num4 + 1, num5].active())
{
                                                                color3 = this._drawbackground_colorSlices[m];
                                                            }
                                                            break;
                                                        case 6:
                                                            num7 = 12;
                                                            if (!Main.tile[num4 - 1, num5 + 1].active())
{
                                                                color3 = this._drawbackground_colorSlices[m];
                                                            }
                                                            break;
                                                        case 7:
                                                            num8 = 8;
                                                            num9 = 4;
                                                            num6 = 4;
                                                            num7 = 12;
                                                            if (!Main.tile[num4, num5 + 1].active())
{
                                                                color3 = this._drawbackground_colorSlices[m];
                                                            }
                                                            break;
                                                        case 8:
                                                            num6 = 12;
                                                            num7 = 12;
                                                            if (!Main.tile[num4 + 1, num5 + 1].active())
{
                                                                color3 = this._drawbackground_colorSlices[m];
                                                            }
                                                            break;
                                                        }
                                                        color2.R = (color.R + color3.R) / 2;
                                                        color2.G = (color.G + color3.G) / 2;
                                                        color2.B = (color.B + color3.B) / 2;
                                                        color2.R = (byte)((float)color2.R * x);
                                                        color2.G = (byte)((float)color2.G * y);
                                                        color2.B = (byte)((float)color2.B * z);
                                                        Main.spriteBatch.Draw(TextureAssets.Background[this._drawBackground_backTexture[1]].Value, new Vector2((float)(this.bgStartX + num * i + 16 * k + num6 + num2), (float)(this.bgStartY + Main.backgroundHeight[this._drawBackground_backTexture[1]] * j + 16 * l + num7)) + drawOffset, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * k + num6 + num2 + 16, 16 * l + num7, num8, num9)), color2);
                                                        if (Main.ugBackTransition > 0f)
{
                                                            Microsoft.Xna.Framework.Color color4 = color2;
                                                            color4.R = (byte)((float)color4.R * Main.ugBackTransition);
                                                            color4.G = (byte)((float)color4.G * Main.ugBackTransition);
                                                            color4.B = (byte)((float)color4.B * Main.ugBackTransition);
                                                            color4.A = (byte)((float)color4.A * Main.ugBackTransition);
                                                            Main.spriteBatch.Draw(TextureAssets.Background[this._drawBackground_oldBackTexture[1]].Value, new Vector2((float)(this.bgStartX + num * i + 16 * k + num6 + num2), (float)(this.bgStartY + Main.backgroundHeight[this._drawBackground_oldBackTexture[1]] * j + 16 * l + num7)) + drawOffset, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * k + num6 + num2 + 16, 16 * l + num7, num8, num9)), color4);
                                                        }
                                                    }
                                                    goto IL_0E5E;
                                                }
                                                catch
{
                                                    color.R = (byte)((float)color.R * x);
                                                    color.G = (byte)((float)color.G * y);
                                                    color.B = (byte)((float)color.B * z);
                                                    Main.spriteBatch.Draw(TextureAssets.Background[this._drawBackground_backTexture[1]].Value, new Vector2((float)(this.bgStartX + num * i + 16 * k + num2), (float)(this.bgStartY + Main.backgroundHeight[this._drawBackground_backTexture[1]] * j + 16 * l)) + drawOffset, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * k + num2 + 16, 16 * l, 16, 16)), color);
                                                    goto IL_0E5E;
                                                }
                                            }
                                            if (((int)color.R > q2 || (double)color.G > (double)q2 * 1.1 || (double)color.B > (double)q2 * 1.2) && Main.ugBackTransition == 0f)
{
                                                Lighting.GetColor4Slice(num4, num5, ref this._drawbackground_colorSlices);
                                                for (int n = 0; n < 4; n++)
{
                                                    int num10 = 0;
                                                    int num11 = 0;
                                                    Microsoft.Xna.Framework.Color color5 = color;
                                                    Microsoft.Xna.Framework.Color color6 = this._drawbackground_colorSlices[n];
                                                    switch (n)
{
                                                    case 1:
                                                        num10 = 8;
                                                        break;
                                                    case 2:
                                                        num11 = 8;
                                                        break;
                                                    case 3:
                                                        num10 = 8;
                                                        num11 = 8;
                                                        break;
                                                    }
                                                    color5.R = (color.R + color6.R) / 2;
                                                    color5.G = (color.G + color6.G) / 2;
                                                    color5.B = (color.B + color6.B) / 2;
                                                    color5.R = (byte)((float)color5.R * x);
                                                    color5.G = (byte)((float)color5.G * y);
                                                    color5.B = (byte)((float)color5.B * z);
                                                    Main.spriteBatch.Draw(TextureAssets.Background[this._drawBackground_backTexture[1]].Value, new Vector2((float)(this.bgStartX + num * i + 16 * k + num10 + num2), (float)(this.bgStartY + Main.backgroundHeight[this._drawBackground_backTexture[1]] * j + 16 * l + num11)) + drawOffset, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * k + num10 + num2 + 16, 16 * l + num11, 8, 8)), color5);
                                                    if (Main.ugBackTransition > 0f)
{
                                                        Microsoft.Xna.Framework.Color color7 = color5;
                                                        color7.R = (byte)((float)color7.R * Main.ugBackTransition);
                                                        color7.G = (byte)((float)color7.G * Main.ugBackTransition);
                                                        color7.B = (byte)((float)color7.B * Main.ugBackTransition);
                                                        color7.A = (byte)((float)color7.A * Main.ugBackTransition);
                                                        Main.spriteBatch.Draw(TextureAssets.Background[this._drawBackground_oldBackTexture[1]].Value, new Vector2((float)(this.bgStartX + num * i + 16 * k + num10 + num2), (float)(this.bgStartY + Main.backgroundHeight[this._drawBackground_oldBackTexture[1]] * j + 16 * l + num11)) + drawOffset, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * k + num10 + num2 + 16, 16 * l + num11, 8, 8)), color7);
                                                    }
                                                }
                                            }
                                            else
{
                                                color.R = (byte)((float)color.R * x);
                                                color.G = (byte)((float)color.G * y);
                                                color.B = (byte)((float)color.B * z);
                                                Main.spriteBatch.Draw(TextureAssets.Background[this._drawBackground_backTexture[1]].Value, new Vector2((float)(this.bgStartX + num * i + 16 * k + num2), (float)(this.bgStartY + Main.backgroundHeight[this._drawBackground_backTexture[1]] * j + 16 * l)) + drawOffset, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * k + num2 + 16, 16 * l, 16, 16)), color);
                                                if (Main.ugBackTransition > 0f)
{
                                                    Microsoft.Xna.Framework.Color color8 = color;
                                                    color8.R = (byte)((float)color8.R * Main.ugBackTransition);
                                                    color8.G = (byte)((float)color8.G * Main.ugBackTransition);
                                                    color8.B = (byte)((float)color8.B * Main.ugBackTransition);
                                                    color8.A = (byte)((float)color8.A * Main.ugBackTransition);
                                                    Main.spriteBatch.Draw(TextureAssets.Background[this._drawBackground_oldBackTexture[1]].Value, new Vector2((float)(this.bgStartX + num * i + 16 * k + num2), (float)(this.bgStartY + Main.backgroundHeight[this._drawBackground_oldBackTexture[1]] * j + 16 * l)) + drawOffset, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * k + num2 + 16, 16 * l, 16, 16)), color8);
                                                }
                                            }
                                        }
                                    }
                                    else
{
                                        color.R = (byte)((float)color.R * x);
                                        color.G = (byte)((float)color.G * y);
                                        color.B = (byte)((float)color.B * z);
                                        if (localShimmerAlpha > 0f)
{
                                            color *= 1f - localShimmerAlpha;
                                        }
                                        Main.spriteBatch.Draw(TextureAssets.Background[this._drawBackground_backTexture[1]].Value, new Vector2((float)(this.bgStartX + num * i + 16 * k + num2), (float)(this.bgStartY + Main.backgroundHeight[this._drawBackground_backTexture[1]] * j + 16 * l)) + drawOffset, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * k + num2 + 16, 16 * l, 16, 16)), color);
                                    }
                                }
                                IL_0E5E:;
                            }
                        }
                    }
                }
                if (Main.ugBackTransition > 0f)
                {
                    num = TextureAssets.Background[this._drawBackground_oldBackTexture[1]].Width() - 32;
                    this.bgStartX = (int)(-Math.IEEERemainder((double)num + (double)Main.screenPosition.X * this.bgParallax, (double)num) - (double)(num / 2)) - (int)drawOffset.X;
                    this.bgLoops = (Main.screenWidth + (int)drawOffset.X * 2) / num + 2;
                    num2 = (int)((float)Math.Round((double)(-(double)((float)Math.IEEERemainder((double)((float)this.bgStartX + Main.screenPosition.X), 16.0)))));
                    if (num2 == -8)
                    {
                        num2 = 8;
                    }
                    for (int num12 = 0; num12 < this.bgLoops; num12++)
                    {
                        for (int num13 = 0; num13 < this.bgLoopsY; num13++)
{
                            for (int num14 = 0; num14 < num / 16; num14++)
{
                                for (int num15 = 0; num15 < 6; num15++)
{
                                    float num16 = (float)(this.bgStartY + num13 * 96 + num15 * 16 + 8);
                                    int num17 = (int)(((float)(this.bgStartX + num * num12 + num14 * 16 + 8) + Main.screenPosition.X) / 16f);
                                    int num18 = (int)((num16 + Main.screenPosition.Y) / 16f);
                                    if (WorldGen.InWorld(num17, num18, 0))
{
                                        Microsoft.Xna.Framework.Color color9 = Lighting.GetColor(num17, num18);
                                        if (Main.tile[num17, num18] == null)
{
                                            Main.tile[num17, num18] = new Tile();
                                        }
                                        if (color9.R > 0 || color9.G > 0 || color9.B > 0)
{
                                            VertexColors vertexColors2;
                                            Lighting.GetCornerColors(num17, num18, out vertexColors2, Main.ugBackTransition);
                                            byte b = (byte)(255f * Main.ugBackTransition);
                                            vertexColors2.BottomLeftColor.A = b;
                                            vertexColors2.BottomRightColor.A = b;
                                            vertexColors2.TopLeftColor.A = b;
                                            vertexColors2.TopRightColor.A = b;
                                            Main.tileBatch.Draw(TextureAssets.Background[this._drawBackground_oldBackTexture[1]].Value, new Vector2((float)(this.bgStartX + num * num12 + 16 * num14 + num2), (float)(this.bgStartY + Main.backgroundHeight[this._drawBackground_oldBackTexture[1]] * num13 + 16 * num15)) + drawOffset, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * num14 + num2 + 16, 16 * num15, 16, 16)), vertexColors2, Vector2.Zero, 1f, SpriteEffects.None);
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
                num = 128;
                if (flag)
                {
                    this.bgParallax = (double)Main.caveParallax;
                    this.bgStartX = (int)(-Math.IEEERemainder((double)num + (double)Main.screenPosition.X * this.bgParallax, (double)num) - (double)(num / 2)) - (int)drawOffset.X;
                    this.bgLoops = (Main.screenWidth + (int)drawOffset.X * 2) / num + 2;
                    this.bgTopY = (float)rockTransitionPoint - Main.screenPosition.Y - 16f;
                    if (this.bgTopY > -32f)
                    {
                        for (int num19 = 0; num19 < this.bgLoops; num19++)
{
                            for (int num20 = 0; num20 < num / 16; num20++)
{
                                float num21 = (float)(this.bgStartX + num * num19 + num20 * 16 + 8);
                                float num22 = this.bgTopY;
                                Microsoft.Xna.Framework.Color color10 = Lighting.GetColor((int)((num21 + Main.screenPosition.X) / 16f), (int)((Main.screenPosition.Y + num22) / 16f));
                                color10.R = (byte)((float)color10.R * x);
                                color10.G = (byte)((float)color10.G * y);
                                color10.B = (byte)((float)color10.B * z);
                                if (localShimmerAlpha > 0f)
{
                                    color10 *= 1f - localShimmerAlpha;
                                }
                                Main.spriteBatch.Draw(TextureAssets.Background[this._drawBackground_backTexture[2]].Value, new Vector2((float)(this.bgStartX + num * num19 + 16 * num20 + num2), this.bgTopY) + drawOffset, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * num20 + num2 + 16, 0, 16, 16)), color10);
                                if (Main.ugBackTransition > 0f)
{
                                    Microsoft.Xna.Framework.Color color11 = color10;
                                    color11.R = (byte)((float)color11.R * Main.ugBackTransition);
                                    color11.G = (byte)((float)color11.G * Main.ugBackTransition);
                                    color11.B = (byte)((float)color11.B * Main.ugBackTransition);
                                    color11.A = (byte)((float)color11.A * Main.ugBackTransition);
                                    Main.spriteBatch.Draw(TextureAssets.Background[this._drawBackground_oldBackTexture[2]].Value, new Vector2((float)(this.bgStartX + num * num19 + 16 * num20 + num2), this.bgTopY) + drawOffset, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * num20 + num2 + 16, 0, 16, 16)), color11);
                                }
                            }
                        }
                    }
                }
            }
        }
References Terraria.Tile.active(), Microsoft.Xna.Framework.Color.B, Terraria.GameContent.TextureAssets.Background, Terraria.Main.backgroundHeight, Terraria.Graphics.VertexColors.BottomLeftColor, Terraria.Graphics.VertexColors.BottomRightColor, Terraria.Main.Camera, Terraria.Main.caveParallax, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Graphics.TileBatch.Draw(), Terraria.Main.drawToScreen, Microsoft.Xna.Framework.Color.G, Terraria.Lighting.GetColor(), Terraria.Lighting.GetColor4Slice(), Terraria.Lighting.GetColor9Slice(), Terraria.Lighting.GetCornerColors(), System.Math.IEEERemainder(), int, Terraria.WorldGen.InWorld(), Terraria.Main.offScreenRange, Microsoft.Xna.Framework.Color.R, System.Math.Round(), Terraria.Graphics.Camera.ScaledPosition, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.spriteBatch, Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.Main.tileBatch, Microsoft.Xna.Framework.Color.ToVector3(), Terraria.Main.ugBackTransition, ReLogic.Content.Asset< T >.Value, Terraria.Main.WallLightAt(), Terraria.Main.worldSurface, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.