Terraria Decompiled: Terraria.Main.DoUpdate_F7_ToggleGraphicsDiagnostics
DoUpdate_F7_ToggleGraphicsDiagnostics()
static void Terraria.Main.DoUpdate_F7_ToggleGraphicsDiagnostics () inline static private
Definition at line 16870 of file Main.cs.
        {
            if (Main.keyState.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.F7) && !Main.drawingPlayerChat && !Main.editSign && !Main.editChest)
            {
                if (Main.drawRelease)
                {
                    SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                    if (Main.keyState.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.LeftAlt) || Main.keyState.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.RightAlt))
                    {
                        TimeLogger.ToggleLogging();
                    }
                    else
                    {
                        Main.drawDiag = (Main.drawDiag + 1) % 3;
                        if (Main.drawDiag > 0)
{
                            Main.shouldDrawNetDiagnosticsUI = false;
                        }
                    }
                }
                Main.drawRelease = false;
                return;
            }
            Main.drawRelease = true;
        }
References Terraria.Main.drawDiag, Terraria.Main.drawingPlayerChat, Terraria.Main.drawRelease, Terraria.Main.editChest, Terraria.Main.editSign, Microsoft.Xna.Framework.Input.KeyboardState.IsKeyDown(), Terraria.Main.keyState, Terraria.Audio.SoundEngine.PlaySound(), and Terraria.TimeLogger.ToggleLogging().
Referenced by Terraria.Main.DoUpdate().