Terraria Decompiled: Terraria.Main.DrawInterface_1_1_DrawEmoteBubblesInWorld
DrawInterface_1_1_DrawEmoteBubblesInWorld()
static void Terraria.Main.DrawInterface_1_1_DrawEmoteBubblesInWorld () inline static private
Definition at line 46649 of file Main.cs.
        {
            Main.spriteBatch.End();
            Main.spriteBatch.Begin(SpriteSortMode.Deferred, null, SamplerState.PointClamp, null, null, null, Main.GameViewMatrix.ZoomMatrix);
            EmoteBubble.DrawAll(Main.spriteBatch);
            if (Main.instance.currentNPCShowingChatBubble != -1)
            {
                Main.DrawNPCChatBubble(Main.instance.currentNPCShowingChatBubble);
            }
            Main.instance.currentNPCShowingChatBubble = -1;
        }
References Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(), Terraria.Main.currentNPCShowingChatBubble, Terraria.GameContent.UI.EmoteBubble.DrawAll(), Terraria.Main.DrawNPCChatBubble(), Microsoft.Xna.Framework.Graphics.SpriteBatch.End(), Terraria.Main.GameViewMatrix, Terraria.Main.instance, Microsoft.Xna.Framework.Graphics.SamplerState.PointClamp, Terraria.Main.spriteBatch, and Terraria.Graphics.SpriteViewMatrix.ZoomMatrix.
Referenced by Terraria.Main.SetupDrawInterfaceLayers().