Terraria Decompiled: Terraria.Main.DrawProj_Flamethrower_Foxsparks
DrawProj_Flamethrower_Foxsparks()
static void Terraria.Main.DrawProj_Flamethrower_Foxsparks (Projectile proj, Player theOwner) inline static private
Definition at line 34332 of file Main.cs.
        {
            bool flag = proj.ai[0] == 1f;
            float num = 60f;
            float num2 = 12f;
            float num3 = num + num2;
            Texture2D value = TextureAssets.Projectile[proj.type].Value;
            Microsoft.Xna.Framework.Color color = Microsoft.Xna.Framework.Color.Transparent;
            Microsoft.Xna.Framework.Color color2 = new Microsoft.Xna.Framework.Color(255, 80, 20, 200);
            Microsoft.Xna.Framework.Color color3 = new Microsoft.Xna.Framework.Color(255, 255, 20, 70);
            Microsoft.Xna.Framework.Color color4 = Microsoft.Xna.Framework.Color.Lerp(new Microsoft.Xna.Framework.Color(255, 80, 20, 100), color3, 0.25f);
            Microsoft.Xna.Framework.Color color5 = new Microsoft.Xna.Framework.Color(80, 80, 80, 100);
            float num4 = 0.35f;
            float num5 = 0.7f;
            float num6 = 0.85f;
            float num7 = ((proj.localAI[0] > num - 10f) ? 0.175f : 0.2f);
            num7 *= 0.7f;
            color2 = new Microsoft.Xna.Framework.Color(95, 120, 255, 200);
            color3 = new Microsoft.Xna.Framework.Color(50, 180, 255, 70);
            int num8 = 7;
            float num9 = Utils.Remap(proj.localAI[0], num, num3, 1f, 0f, true);
            float num10 = Math.Min(proj.localAI[0], 20f);
            float num11 = Utils.Remap(proj.localAI[0], 0f, num3, 0f, 1f, true);
            float num12 = Utils.Remap(num11, 0.2f, 0.5f, 0.25f, 1f, true) * 0.5f;
            Microsoft.Xna.Framework.Rectangle rectangle;
            if (flag)
            {
                rectangle = value.Frame(1, num8, 0, (int)Utils.Remap(num11, 0.5f, 1f, 3f, 5f, true), 0, 0);
            }
            else
            {
                rectangle = value.Frame(1, num8, 0, 3, 0, 0);
            }
            if (num11 < 1f)
            {
                for (int i = 0; i < 2; i++)
                {
                    for (float num13 = 1f; num13 >= 0f; num13 -= num7)
                    {
                        if (num11 < 0.1f)
{
                            color = Microsoft.Xna.Framework.Color.Lerp(Microsoft.Xna.Framework.Color.Transparent, color2, Utils.GetLerpValue(0f, 0.1f, num11, true));
                        }
                        else if (num11 < 0.2f)
{
                            color = Microsoft.Xna.Framework.Color.Lerp(color2, color3, Utils.GetLerpValue(0.1f, 0.2f, num11, true));
                        }
                        else if (num11 < num4)
{
                            color = color3;
                        }
                        else if (num11 < num5)
{
                            color = Microsoft.Xna.Framework.Color.Lerp(color3, color4, Utils.GetLerpValue(num4, num5, num11, true));
                        }
                        else if (num11 < num6)
{
                            color = Microsoft.Xna.Framework.Color.Lerp(color4, color5, Utils.GetLerpValue(num5, num6, num11, true));
                        }
                        else if (num11 < 1f)
{
                            color = Microsoft.Xna.Framework.Color.Lerp(color5, Microsoft.Xna.Framework.Color.Transparent, Utils.GetLerpValue(num6, 1f, num11, true));
                        }
                        else
{
                            color = Microsoft.Xna.Framework.Color.Transparent;
                        }
                        float num14 = (1f - num13) * Utils.Remap(num11, 0f, 0.2f, 0f, 1f, true);
                        float num15 = proj.Distance(theOwner.Center) / 120f;
                        if (num15 > 1f)
{
                            num15 = 1f;
                        }
                        Vector2 vector = proj.DirectionTo(theOwner.Center + proj.velocity * 6f).SafeNormalize(Vector2.Zero) * -proj.velocity.Length();
                        Vector2 vector2 = proj.Center - Main.screenPosition + vector * -num10 * num13 * num15;
                        Microsoft.Xna.Framework.Color color6 = color * num14;
                        Microsoft.Xna.Framework.Color color7 = color6;
                        if (!flag)
{
                            color7.G /= 2;
                            color7.B /= 2;
                            color7.A = (byte)Math.Min((float)color6.A + 80f * num14, 255f);
                            float num16 = Utils.Remap(proj.localAI[0], 20f, num3, 0f, 1f, true);
                            num16 *= num16 * num16;
                            vector2 += new Vector2(0f, -46f) * num16;
                        }
                        float num17 = 1f / num7 * (num13 + 1f);
                        float num18 = proj.rotation + num13 * 1.5707964f + Main.GlobalTimeWrappedHourly * num17 * 2f;
                        float num19 = proj.rotation - num13 * 1.5707964f - Main.GlobalTimeWrappedHourly * num17 * 2f;
                        if (i == 0)
{
                            Main.EntitySpriteDraw(value, vector2 + proj.velocity * -num10 * num7 * 0.5f, new Microsoft.Xna.Framework.Rectangle?(rectangle), color7 * num9 * 0.25f, num18 + 0.7853982f, rectangle.Size() / 2f, num12, SpriteEffects.None, 0f);
                            Main.EntitySpriteDraw(value, vector2, new Microsoft.Xna.Framework.Rectangle?(rectangle), color7 * num9, num19, rectangle.Size() / 2f, num12, SpriteEffects.None, 0f);
                        }
                        else if (i == 1 && !flag)
{
                            Main.EntitySpriteDraw(value, vector2 + proj.velocity * -num10 * num7 * 0.2f, new Microsoft.Xna.Framework.Rectangle?(rectangle), color6 * num9 * 0.25f, num18 + 1.5707964f, rectangle.Size() / 2f, num12 * 0.75f, SpriteEffects.None, 0f);
                            Main.EntitySpriteDraw(value, vector2, new Microsoft.Xna.Framework.Rectangle?(rectangle), color6 * num9, num19 + 1.5707964f, rectangle.Size() / 2f, num12 * 0.75f, SpriteEffects.None, 0f);
                        }
                    }
                }
            }
        }
References Terraria.Projectile.ai, Terraria.Entity.Center, Terraria.Entity.DirectionTo(), Terraria.Entity.Distance(), Terraria.Main.EntitySpriteDraw(), Terraria.Utils.GetLerpValue(), Microsoft.Xna.Framework.Vector2.Length(), Microsoft.Xna.Framework.Color.Lerp(), Terraria.Projectile.localAI, System.Math.Min(), Terraria.GameContent.TextureAssets.Projectile, Terraria.Utils.Remap(), Microsoft.Xna.Framework.Color.Transparent, Terraria.Projectile.type, System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Entity.velocity, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.Main.DrawProjDirect().