Terraria Decompiled: Terraria.Main.EndDraw
EndDraw()
override void Terraria.Main.EndDraw () inline protected virtual
Reimplemented from Microsoft.Xna.Framework.Game.
Definition at line 62639 of file Main.cs.
        {
            if (this._isDrawingOrUpdating)
            {
                return;
            }
            if (Main.CollectGen0EveryFrame)
            {
                NewRuntimeMethods.GC_Collect(0, GCCollectionMode.Forced, false);
            }
            bool flag = false;
            if (Program.IsMono)
            {
                flag = true;
            }
            if (Main.FrameSkipMode == FrameSkipMode.Subtle && Main.improvedSubtleFrameSkip)
            {
                for (;;)
                {
                    long num = this.presentTimestamp;
                    this.presentTimestamp = Stopwatch.GetTimestamp();
                    Main.UpdateTimeAccumulator += Utils.SWTicksToTimeSpan(this.presentTimestamp - num).TotalSeconds;
                    if (Main.UpdateTimeAccumulator >= Main.TARGET_FRAME_TIME * 599.0 / 600.0)
                    {
                        break;
                    }
                    DetailedFPS.Begin(DetailedFPS.OperationCategory.Idle);
                    if (!flag && Main.UpdateTimeAccumulator < Main.TARGET_FRAME_TIME * 0.9)
                    {
                        flag = true;
                        NewRuntimeMethods.GC_Collect(2, GCCollectionMode.Optimized, false);
                    }
                }
            }
            DetailedFPS.Begin(DetailedFPS.OperationCategory.Present);
            if (Main.FrameSkipMode == FrameSkipMode.Subtle && Main.improvedSubtleFrameSkip && !flag && DetailedFPS.CurrentFrameTime.TotalSeconds < Main.TARGET_FRAME_TIME * 0.9 && DetailedFPS.VsyncAppearsActive())
            {
                NewRuntimeMethods.GC_Collect(2, GCCollectionMode.Optimized, false);
            }
            base.EndDraw();
            DetailedFPS.End();
            DetailedFPS.StartNextFrame();
        }
References Terraria.Testing.DetailedFPS.Begin(), Terraria.Main.CollectGen0EveryFrame, Terraria.Testing.DetailedFPS.CurrentFrameTime, Terraria.Testing.DetailedFPS.End(), Terraria.Main.FrameSkipMode, Terraria.Utilities.NewRuntimeMethods.GC_Collect(), Terraria.Main.improvedSubtleFrameSkip, Terraria.Program.IsMono, Terraria.Testing.DetailedFPS.StartNextFrame(), Terraria.Utils.SWTicksToTimeSpan(), Terraria.Main.TARGET_FRAME_TIME, System.TimeSpan.TotalSeconds, Terraria.Main.UpdateTimeAccumulator, and Terraria.Testing.DetailedFPS.VsyncAppearsActive().