Terraria Decompiled: Terraria.Main.CraftItem_GrantItem
CraftItem_GrantItem()
static void Terraria.Main.CraftItem_GrantItem (Recipe recipe, Item result, bool quickCraft) inline static
Definition at line 42595 of file Main.cs.
        {
            result.stack += Main.mouseItem.stack;
            Main.mouseItem = result;
            if (quickCraft && !Main.mouseItem.IsAir)
            {
                if (CraftingRequests.HasPendingRequests)
                {
                    Main.LocalPlayer.GetOrDropItem(Main.mouseItem, GetItemSettings.ReturnItemShowAsNew);
                    Main.mouseItem = new Item();
                }
                else
                {
                    Main.mouseItem = Main.LocalPlayer.GetItem(Main.mouseItem, GetItemSettings.ReturnItemShowAsNew);
                }
            }
            CraftingEffects.OnCraftItemGranted(recipe, result, quickCraft);
            AchievementsHelper.NotifyItemCraft(recipe);
            AchievementsHelper.NotifyItemPickup(Main.player[Main.myPlayer], recipe.createItem);
        }
References Terraria.Recipe.createItem, Terraria.Player.GetItem(), Terraria.Player.GetOrDropItem(), Terraria.GameContent.CraftingRequests.HasPendingRequests, Terraria.Item.IsAir, Terraria.Main.LocalPlayer, Terraria.Main.mouseItem, Terraria.Main.myPlayer, Terraria.GameContent.Achievements.AchievementsHelper.NotifyItemCraft(), Terraria.GameContent.Achievements.AchievementsHelper.NotifyItemPickup(), Terraria.GameContent.CraftingEffects.OnCraftItemGranted(), Terraria.Main.player, Terraria.GetItemSettings.ReturnItemShowAsNew, and Terraria.Item.stack.
Referenced by Terraria.GameContent.CraftingRequests.CraftLocally(), and Terraria.GameContent.CraftingRequests.HandleResponse().