Terraria Decompiled: Terraria.Main.AnimateTiles
AnimateTiles()
static void Terraria.Main.AnimateTiles () inline static private
Definition at line 16956 of file Main.cs.
        {
            Main.tileFrameCounter[12]++;
            if (Main.tileFrameCounter[12] > 5)
            {
                Main.tileFrameCounter[12] = 0;
                Main.tileFrame[12]++;
                if (Main.tileFrame[12] >= 10)
                {
                    Main.tileFrame[12] = 0;
                }
            }
            Main.tileFrameCounter[665] = Main.tileFrameCounter[12];
            Main.tileFrame[665] = Main.tileFrame[12];
            Main.tileFrameCounter[639]++;
            if (Main.tileFrameCounter[639] > 5)
            {
                Main.tileFrameCounter[639] = 0;
                Main.tileFrame[639]++;
                if (Main.tileFrame[639] >= 10)
                {
                    Main.tileFrame[639] = 0;
                }
            }
            Main.tileFrameCounter[739]++;
            if (Main.tileFrameCounter[739] > 10)
            {
                Main.tileFrameCounter[739] = 0;
                Main.tileFrame[739]++;
                if (Main.tileFrame[739] >= 4)
                {
                    Main.tileFrame[739] = 0;
                }
            }
            Main.tileFrameCounter[748]++;
            if (Main.tileFrameCounter[748] > 7)
            {
                Main.tileFrameCounter[748] = 0;
                Main.tileFrame[748]++;
                if (Main.tileFrame[748] >= 8)
                {
                    Main.tileFrame[748] = 0;
                }
            }
            Main.tileFrameCounter[17]++;
            if (Main.tileFrameCounter[17] > 5)
            {
                Main.tileFrameCounter[17] = 0;
                Main.tileFrame[17]++;
                if (Main.tileFrame[17] >= 12)
                {
                    Main.tileFrame[17] = 0;
                }
            }
            int[] array = Main.tileFrameCounter;
            int num = 133;
            int num2 = array[num] + 1;
            array[num] = num2;
            if (num2 >= 4)
            {
                Main.tileFrameCounter[133] = 0;
                int[] array2 = Main.tileFrame;
                int num3 = 133;
                num2 = array2[num3] + 1;
                array2[num3] = num2;
                if (num2 >= 6)
                {
                    Main.tileFrame[133] = 0;
                }
            }
            Main.tileFrameCounter[31]++;
            if (Main.tileFrameCounter[31] >= 8)
            {
                Main.tileFrameCounter[31] = 0;
                Main.tileFrame[31]++;
                if (Main.tileFrame[31] >= 4)
                {
                    Main.tileFrame[31] = 0;
                }
            }
            Main.tileFrame[696] = Main.tileFrame[31];
            Main.tileFrameCounter[77]++;
            if (Main.tileFrameCounter[77] > 5)
            {
                Main.tileFrameCounter[77] = 0;
                Main.tileFrame[77]++;
                if (Main.tileFrame[77] >= 12)
                {
                    Main.tileFrame[77] = 0;
                }
            }
            Main.tileFrameCounter[106]++;
            if (Main.tileFrameCounter[106] > 4)
            {
                Main.tileFrameCounter[106] = 0;
                Main.tileFrame[106]++;
                if (Main.tileFrame[106] >= 2)
                {
                    Main.tileFrame[106] = 0;
                }
            }
            Main.tileFrameCounter[207]++;
            if (Main.tileFrameCounter[207] > 4)
            {
                Main.tileFrameCounter[207] = 0;
                Main.tileFrame[207]++;
                if (Main.tileFrame[207] >= 6)
                {
                    Main.tileFrame[207] = 0;
                }
            }
            Main.tileFrameCounter[215]++;
            if (Main.tileFrameCounter[215] >= 4)
            {
                Main.tileFrameCounter[215] = 0;
                Main.tileFrame[215]++;
                if (Main.tileFrame[215] >= 8)
                {
                    Main.tileFrame[215] = 0;
                }
            }
            Main.tileFrameCounter[592]++;
            if (Main.tileFrameCounter[592] >= 5)
            {
                Main.tileFrameCounter[592] = 0;
                Main.tileFrame[592]++;
                if (Main.tileFrame[592] >= 8)
                {
                    Main.tileFrame[592] = 0;
                }
            }
            Main.tileFrameCounter[217]++;
            if (Main.tileFrameCounter[217] > 4)
            {
                Main.tileFrameCounter[217] = 0;
                Main.tileFrame[217]++;
                if (Main.tileFrame[217] >= 5)
                {
                    Main.tileFrame[217] = 0;
                }
            }
            Main.tileFrameCounter[218]++;
            if (Main.tileFrameCounter[218] > 4)
            {
                Main.tileFrameCounter[218] = 0;
                Main.tileFrame[218]++;
                if (Main.tileFrame[218] >= 2)
                {
                    Main.tileFrame[218] = 0;
                }
            }
            Main.tileFrameCounter[219]++;
            if (Main.tileFrameCounter[219] > 4)
            {
                Main.tileFrameCounter[219] = 0;
                Main.tileFrame[219]++;
                if (Main.tileFrame[219] >= 10)
                {
                    Main.tileFrame[219] = 0;
                }
            }
            Main.tileFrameCounter[642]++;
            if (Main.tileFrameCounter[642] > 4)
            {
                Main.tileFrameCounter[642] = 0;
                Main.tileFrame[642]++;
                if (Main.tileFrame[642] >= 6)
                {
                    Main.tileFrame[642] = 0;
                }
            }
            Main.tileFrameCounter[220]++;
            if (Main.tileFrameCounter[220] > 4)
            {
                Main.tileFrameCounter[220] = 0;
                Main.tileFrame[220]++;
                if (Main.tileFrame[220] >= 4)
                {
                    Main.tileFrame[220] = 0;
                }
            }
            Main.tileFrameCounter[231]++;
            if (Main.tileFrameCounter[231] > 16)
            {
                Main.tileFrameCounter[231] = 0;
                Main.tileFrame[231]++;
                if (Main.tileFrame[231] >= 7)
                {
                    Main.tileFrame[231] = 0;
                }
            }
            Main.tileFrameCounter[235]++;
            if (Main.tileFrameCounter[235] > 20)
            {
                Main.tileFrameCounter[235] = 0;
                Main.tileFrame[235]++;
                if (Main.tileFrame[235] >= 4)
                {
                    Main.tileFrame[235] = 0;
                }
            }
            Main.tileFrameCounter[238]++;
            if (Main.tileFrameCounter[238] > 20)
            {
                Main.tileFrameCounter[238] = 0;
                Main.tileFrame[238]++;
                if (Main.tileFrame[238] >= 4)
                {
                    Main.tileFrame[238] = 0;
                }
            }
            Main.tileFrameCounter[243]++;
            if (Main.tileFrameCounter[243] > 4)
            {
                Main.tileFrameCounter[243] = 0;
                Main.tileFrame[243]++;
                if (Main.tileFrame[243] >= 6)
                {
                    Main.tileFrame[243] = 0;
                }
            }
            Main.tileFrameCounter[244]++;
            if (Main.tileFrameCounter[244] > 4)
            {
                Main.tileFrameCounter[244] = 0;
                Main.tileFrame[244]++;
                if (Main.tileFrame[244] >= 6)
                {
                    Main.tileFrame[244] = 0;
                }
            }
            Main.tileFrameCounter[247]++;
            if (Main.tileFrameCounter[247] > 4)
            {
                Main.tileFrameCounter[247] = 0;
                Main.tileFrame[247]++;
                if (Main.tileFrame[247] > 7)
                {
                    Main.tileFrame[247] = 0;
                }
            }
            Main.tileFrameCounter[96]++;
            if (Main.tileFrameCounter[96] > 4)
            {
                Main.tileFrameCounter[96] = 0;
                Main.tileFrame[96]++;
                if (Main.tileFrame[96] > 3)
                {
                    Main.tileFrame[96] = 0;
                }
            }
            Main.tileFrameCounter[171]++;
            if (Main.tileFrameCounter[171] > 16)
            {
                Main.tileFrameCounter[171] = 0;
                Main.tileFrame[171]++;
                if (Main.tileFrame[171] > 3)
                {
                    Main.tileFrame[171] = 0;
                }
            }
            Main.tileFrameCounter[270]++;
            if (Main.tileFrameCounter[270] > 8)
            {
                Main.tileFrameCounter[270] = 0;
                Main.tileFrame[270]++;
                if (Main.tileFrame[270] > 5)
                {
                    Main.tileFrame[270] = 0;
                }
            }
            int num4 = Main.tileFrame[270];
            Main.tileFrame[271] = num4;
            Main.tileFrame[581] = num4;
            Main.tileFrameCounter[660]++;
            if (Main.tileFrameCounter[660] > 8)
            {
                Main.tileFrameCounter[660] = 0;
                Main.tileFrame[660]++;
                if (Main.tileFrame[660] > 4)
                {
                    Main.tileFrame[660] = 0;
                }
            }
            Main.tileFrameCounter[272]++;
            if (Main.tileFrameCounter[272] >= 10)
            {
                Main.tileFrameCounter[272] = 0;
                Main.tileFrame[272]++;
                if (Main.tileFrame[272] > 1)
                {
                    Main.tileFrame[272] = 0;
                }
            }
            Main.tileFrameCounter[300]++;
            if (Main.tileFrameCounter[300] >= 5)
            {
                Main.tileFrameCounter[300] = 0;
                Main.tileFrame[300]++;
                if (Main.tileFrame[300] > 6)
                {
                    Main.tileFrame[300] = 0;
                }
            }
            Main.tileFrameCounter[301]++;
            if (Main.tileFrameCounter[301] >= 5)
            {
                Main.tileFrameCounter[301] = 0;
                Main.tileFrame[301]++;
                if (Main.tileFrame[301] > 7)
                {
                    Main.tileFrame[301] = 0;
                }
            }
            Main.tileFrameCounter[302]++;
            if (Main.tileFrameCounter[302] >= 5)
            {
                Main.tileFrameCounter[302] = 0;
                Main.tileFrame[302]++;
                if (Main.tileFrame[302] > 3)
                {
                    Main.tileFrame[302] = 0;
                }
            }
            Main.tileFrameCounter[303]++;
            if (Main.tileFrameCounter[303] >= 5)
            {
                Main.tileFrameCounter[303] = 0;
                Main.tileFrame[303]++;
                if (Main.tileFrame[303] > 4)
                {
                    Main.tileFrame[303] = 0;
                }
            }
            Main.tileFrameCounter[305]++;
            if (Main.tileFrameCounter[305] >= 5)
            {
                Main.tileFrameCounter[305] = 0;
                Main.tileFrame[305]++;
                if (Main.tileFrame[305] > 11)
                {
                    Main.tileFrame[305] = 0;
                }
            }
            Main.tileFrameCounter[306]++;
            if (Main.tileFrameCounter[306] >= 5)
            {
                Main.tileFrameCounter[306] = 0;
                Main.tileFrame[306]++;
                if (Main.tileFrame[306] > 11)
                {
                    Main.tileFrame[306] = 0;
                }
            }
            Main.tileFrameCounter[307]++;
            if (Main.tileFrameCounter[307] >= 5)
            {
                Main.tileFrameCounter[307] = 0;
                Main.tileFrame[307]++;
                if (Main.tileFrame[307] > 1)
                {
                    Main.tileFrame[307] = 0;
                }
            }
            Main.tileFrameCounter[308]++;
            if (Main.tileFrameCounter[308] >= 5)
            {
                Main.tileFrameCounter[308] = 0;
                Main.tileFrame[308]++;
                if (Main.tileFrame[308] > 7)
                {
                    Main.tileFrame[308] = 0;
                }
            }
            Main.tileFrameCounter[314]++;
            if (Main.tileFrameCounter[314] >= 10)
            {
                Main.tileFrameCounter[314] = 0;
                Main.tileFrame[314]++;
                if (Main.tileFrame[314] > 4)
                {
                    Main.tileFrame[314] = 0;
                }
            }
            Main.tileFrameCounter[326]++;
            if (Main.tileFrameCounter[326] >= 5)
            {
                Main.tileFrameCounter[326] = 0;
                Main.tileFrame[326]++;
                if (Main.tileFrame[326] > 7)
                {
                    Main.tileFrame[326] = 0;
                }
            }
            Main.tileFrameCounter[327]++;
            if (Main.tileFrameCounter[327] >= 10)
            {
                Main.tileFrameCounter[327] = 0;
                Main.tileFrame[327]++;
                if (Main.tileFrame[327] > 7)
                {
                    Main.tileFrame[327] = 0;
                }
            }
            Main.tileFrameCounter[345]++;
            if (Main.tileFrameCounter[345] >= 10)
            {
                Main.tileFrameCounter[345] = 0;
                Main.tileFrame[345]++;
                if (Main.tileFrame[345] > 7)
                {
                    Main.tileFrame[345] = 0;
                }
            }
            Main.tileFrameCounter[458]++;
            if (Main.tileFrameCounter[458] >= 10)
            {
                Main.tileFrameCounter[458] = 0;
                Main.tileFrame[458]++;
                if (Main.tileFrame[458] > 7)
                {
                    Main.tileFrame[458] = 0;
                }
            }
            Main.tileFrameCounter[459]++;
            if (Main.tileFrameCounter[459] >= 10)
            {
                Main.tileFrameCounter[459] = 0;
                Main.tileFrame[459]++;
                if (Main.tileFrame[459] > 7)
                {
                    Main.tileFrame[459] = 0;
                }
            }
            Main.tileFrameCounter[708]++;
            if (Main.tileFrameCounter[708] >= 10)
            {
                Main.tileFrameCounter[708] = 0;
                Main.tileFrame[708]++;
                if (Main.tileFrame[708] > 7)
                {
                    Main.tileFrame[708] = 0;
                }
            }
            Main.tileFrameCounter[336]++;
            if (Main.tileFrameCounter[336] >= 5)
            {
                Main.tileFrameCounter[336] = 0;
                Main.tileFrame[336]++;
                if (Main.tileFrame[336] > 3)
                {
                    Main.tileFrame[336] = 0;
                }
            }
            Main.tileFrameCounter[328]++;
            if (Main.tileFrameCounter[328] >= 5)
            {
                Main.tileFrameCounter[328] = 0;
                Main.tileFrame[328]++;
                if (Main.tileFrame[328] > 7)
                {
                    Main.tileFrame[328] = 0;
                }
            }
            Main.tileFrameCounter[329]++;
            if (Main.tileFrameCounter[329] >= 5)
            {
                Main.tileFrameCounter[329] = 0;
                Main.tileFrame[329]++;
                if (Main.tileFrame[329] > 7)
                {
                    Main.tileFrame[329] = 0;
                }
            }
            int num5 = 20;
            int[] array3 = Main.tileFrameCounter;
            int num6 = 507;
            num2 = array3[num6] + 1;
            array3[num6] = num2;
            if (num2 >= num5 * 8)
            {
                Main.tileFrameCounter[507] = 0;
            }
            int[] array4 = Main.tileFrameCounter;
            int num7 = 508;
            num2 = array4[num7] + 1;
            array4[num7] = num2;
            if (num2 >= num5 * 8)
            {
                Main.tileFrameCounter[508] = 0;
            }
            for (int i = 340; i <= 344; i++)
            {
                Main.tileFrameCounter[i]++;
                if (Main.tileFrameCounter[i] >= 5)
                {
                    Main.tileFrameCounter[i] = 0;
                    Main.tileFrame[i]++;
                    if (Main.tileFrame[i] > 3)
                    {
                        Main.tileFrame[i] = 0;
                    }
                }
            }
            Main.tileFrameCounter[351]++;
            if (Main.tileFrameCounter[351] >= 5)
            {
                Main.tileFrameCounter[351] = 0;
                Main.tileFrame[351]++;
                if (Main.tileFrame[351] > 2)
                {
                    Main.tileFrame[351] = 0;
                }
            }
            Main.tileFrameCounter[354]++;
            if (Main.tileFrameCounter[354] >= 5)
            {
                Main.tileFrameCounter[354] = 0;
                Main.tileFrame[354]++;
                if (Main.tileFrame[354] >= 8)
                {
                    Main.tileFrame[354] = 0;
                }
            }
            Main.tileFrame[355] = Main.tileFrame[354];
            Main.tileFrameCounter[377]++;
            if (Main.tileFrameCounter[377] >= 5)
            {
                Main.tileFrameCounter[377] = 0;
                Main.tileFrame[377]++;
                if (Main.tileFrame[377] >= 4)
                {
                    Main.tileFrame[377] = 0;
                }
            }
            Main.tileFrameCounter[379]++;
            if (Main.tileFrameCounter[379] >= 10)
            {
                Main.tileFrameCounter[379] = 0;
                Main.tileFrame[379]++;
                if (Main.tileFrame[379] >= 4)
                {
                    Main.tileFrame[379] = 0;
                }
            }
            int[] array5 = Main.tileFrameCounter;
            int num8 = 390;
            num2 = array5[num8] + 1;
            array5[num8] = num2;
            if (num2 >= 8)
            {
                Main.tileFrameCounter[390] = 0;
                int[] array6 = Main.tileFrame;
                int num9 = 390;
                num2 = array6[num9] + 1;
                array6[num9] = num2;
                if (num2 >= 7)
                {
                    Main.tileFrame[390] = 0;
                }
            }
            int[] array7 = Main.tileFrameCounter;
            int num10 = 228;
            num2 = array7[num10] + 1;
            array7[num10] = num2;
            if (num2 >= 5)
            {
                Main.tileFrameCounter[228] = 0;
                int[] array8 = Main.tileFrame;
                int num11 = 228;
                num2 = array8[num11] + 1;
                array8[num11] = num2;
                if (num2 >= 3)
                {
                    Main.tileFrame[228] = 0;
                }
            }
            int[] array9 = Main.tileFrameCounter;
            int num12 = 405;
            num2 = array9[num12] + 1;
            array9[num12] = num2;
            if (num2 >= 5)
            {
                Main.tileFrameCounter[405] = 0;
                int[] array10 = Main.tileFrame;
                int num13 = 405;
                num2 = array10[num13] + 1;
                array10[num13] = num2;
                if (num2 >= 8)
                {
                    Main.tileFrame[405] = 0;
                }
            }
            int[] array11 = Main.tileFrameCounter;
            int num14 = 406;
            num2 = array11[num14] + 1;
            array11[num14] = num2;
            if (num2 >= 8)
            {
                Main.tileFrameCounter[406] = 0;
                int[] array12 = Main.tileFrame;
                int num15 = 406;
                num2 = array12[num15] + 1;
                array12[num15] = num2;
                if (num2 >= 6)
                {
                    Main.tileFrame[406] = 0;
                }
            }
            int[] array13 = Main.tileFrameCounter;
            int num16 = 452;
            num2 = array13[num16] + 1;
            array13[num16] = num2;
            if (num2 >= 5)
            {
                Main.tileFrameCounter[452] = 0;
                int[] array14 = Main.tileFrame;
                int num17 = 452;
                num2 = array14[num17] + 1;
                array14[num17] = num2;
                if (num2 >= 15)
                {
                    Main.tileFrame[452] = 0;
                }
            }
            int[] array15 = Main.tileFrameCounter;
            int num18 = 455;
            num2 = array15[num18] + 1;
            array15[num18] = num2;
            if (num2 >= 5)
            {
                Main.tileFrameCounter[455] = 0;
                int[] array16 = Main.tileFrame;
                int num19 = 455;
                num2 = array16[num19] + 1;
                array16[num19] = num2;
                if (num2 >= 6)
                {
                    Main.tileFrame[455] = 0;
                }
            }
            int[] array17 = Main.tileFrameCounter;
            int num20 = 499;
            num2 = array17[num20] + 1;
            array17[num20] = num2;
            if (num2 >= 5)
            {
                Main.tileFrameCounter[499] = 0;
                int[] array18 = Main.tileFrame;
                int num21 = 499;
                num2 = array18[num21] + 1;
                array18[num21] = num2;
                if (num2 >= 8)
                {
                    Main.tileFrame[499] = 0;
                }
            }
            int[] array19 = Main.tileFrameCounter;
            int num22 = 129;
            num2 = array19[num22] + 1;
            array19[num22] = num2;
            if (num2 >= 8)
            {
                Main.tileFrameCounter[129] = 0;
                int[] array20 = Main.tileFrame;
                int num23 = 129;
                num2 = array20[num23] + 1;
                array20[num23] = num2;
                if (num2 >= 6)
                {
                    Main.tileFrame[129] = 0;
                }
            }
            Main.tileFrameCounter[453] += (WorldGen.isGeneratingOrLoadingWorld ? 0 : Main.rand.Next(3));
            int[] array21 = Main.tileFrameCounter;
            int num24 = 453;
            num2 = array21[num24] + 1;
            array21[num24] = num2;
            if (num2 >= 60)
            {
                Main.tileFrameCounter[453] = 0;
            }
            int[] array22 = Main.tileFrame;
            int num25 = 412;
            num2 = array22[num25] + 1;
            array22[num25] = num2;
            if (num2 >= 240)
            {
                Main.tileFrame[412] = 0;
            }
            Main.tileFrameCounter[456] += (WorldGen.isGeneratingOrLoadingWorld ? 0 : Main.rand.Next(3));
            int[] array23 = Main.tileFrameCounter;
            int num26 = 456;
            num2 = array23[num26] + 1;
            array23[num26] = num2;
            if (num2 >= 80)
            {
                Main.tileFrameCounter[456] = 0;
            }
            int[] array24 = Main.tileFrame;
            int num27 = 456;
            num2 = array24[num27] + 1;
            array24[num27] = num2;
            if (num2 >= 240)
            {
                Main.tileFrame[456] = 0;
            }
            int[] array25 = Main.tileFrameCounter;
            int num28 = 410;
            num2 = array25[num28] + 1;
            array25[num28] = num2;
            if (num2 >= 8)
            {
                Main.tileFrameCounter[410] = 0;
                int[] array26 = Main.tileFrame;
                int num29 = 410;
                num2 = array26[num29] + 1;
                array26[num29] = num2;
                if (num2 >= 8)
                {
                    Main.tileFrame[410] = 0;
                }
            }
            int[] array27 = Main.tileFrameCounter;
            int num30 = 480;
            num2 = array27[num30] + 1;
            array27[num30] = num2;
            if (num2 >= 8)
            {
                Main.tileFrameCounter[480] = 0;
                int[] array28 = Main.tileFrame;
                int num31 = 480;
                num2 = array28[num31] + 1;
                array28[num31] = num2;
                if (num2 >= 8)
                {
                    Main.tileFrame[480] = 0;
                }
            }
            int[] array29 = Main.tileFrameCounter;
            int num32 = 509;
            num2 = array29[num32] + 1;
            array29[num32] = num2;
            if (num2 >= 8)
            {
                Main.tileFrameCounter[509] = 0;
                int[] array30 = Main.tileFrame;
                int num33 = 509;
                num2 = array30[num33] + 1;
                array30[num33] = num2;
                if (num2 >= 8)
                {
                    Main.tileFrame[509] = 0;
                }
            }
            int[] array31 = Main.tileFrameCounter;
            int num34 = 657;
            num2 = array31[num34] + 1;
            array31[num34] = num2;
            if (num2 >= 8)
            {
                Main.tileFrameCounter[657] = 0;
                int[] array32 = Main.tileFrame;
                int num35 = 657;
                num2 = array32[num35] + 1;
                array32[num35] = num2;
                if (num2 >= 8)
                {
                    Main.tileFrame[657] = 0;
                }
            }
            int[] array33 = Main.tileFrameCounter;
            int num36 = 658;
            num2 = array33[num36] + 1;
            array33[num36] = num2;
            if (num2 >= 4)
            {
                Main.tileFrameCounter[658] = 0;
                int[] array34 = Main.tileFrame;
                int num37 = 658;
                num2 = array34[num37] + 1;
                array34[num37] = num2;
                if (num2 >= 10)
                {
                    Main.tileFrame[658] = 0;
                }
            }
            int[] array35 = Main.tileFrameCounter;
            int num38 = 720;
            num2 = array35[num38] + 1;
            array35[num38] = num2;
            if (num2 >= 8)
            {
                Main.tileFrameCounter[720] = 0;
                int[] array36 = Main.tileFrame;
                int num39 = 720;
                num2 = array36[num39] + 1;
                array36[num39] = num2;
                if (num2 >= 16)
                {
                    Main.tileFrame[720] = 0;
                }
            }
            int[] array37 = Main.tileFrameCounter;
            int num40 = 721;
            num2 = array37[num40] + 1;
            array37[num40] = num2;
            if (num2 >= 8)
            {
                Main.tileFrameCounter[721] = 0;
                int[] array38 = Main.tileFrame;
                int num41 = 721;
                num2 = array38[num41] + 1;
                array38[num41] = num2;
                if (num2 >= 32)
                {
                    Main.tileFrame[721] = 0;
                }
            }
            int[] array39 = Main.tileFrameCounter;
            int num42 = 725;
            num2 = array39[num42] + 1;
            array39[num42] = num2;
            if (num2 >= 8)
            {
                Main.tileFrameCounter[725] = 0;
                int[] array40 = Main.tileFrame;
                int num43 = 725;
                num2 = array40[num43] + 1;
                array40[num43] = num2;
                if (num2 >= 4)
                {
                    Main.tileFrame[725] = 0;
                }
            }
            int[] array41 = Main.tileFrameCounter;
            int num44 = 421;
            num2 = array41[num44] + 1;
            array41[num44] = num2;
            if (num2 >= 4)
            {
                Main.tileFrameCounter[421] = 0;
                int[] array42 = Main.tileFrame;
                int num45 = 421;
                num2 = array42[num45] + 1;
                array42[num45] = num2;
                if (num2 >= 4)
                {
                    Main.tileFrame[421] = 0;
                }
            }
            int[] array43 = Main.tileFrameCounter;
            int num46 = 422;
            num2 = array43[num46] + 1;
            array43[num46] = num2;
            if (num2 >= 4)
            {
                Main.tileFrameCounter[422] = 0;
                int[] array44 = Main.tileFrame;
                int num47 = 422;
                num2 = array44[num47] - 1;
                array44[num47] = num2;
                if (num2 < 0)
                {
                    Main.tileFrame[422] = 3;
                }
            }
            int[] array45 = Main.tileFrameCounter;
            int num48 = 463;
            num2 = array45[num48] + 1;
            array45[num48] = num2;
            if (num2 >= 10)
            {
                Main.tileFrameCounter[463] = 0;
                int[] array46 = Main.tileFrame;
                int num49 = 463;
                num2 = array46[num49] + 1;
                array46[num49] = num2;
                if (num2 >= 6)
                {
                    Main.tileFrame[463] = 0;
                }
            }
            int[] array47 = Main.tileFrameCounter;
            int num50 = 464;
            num2 = array47[num50] + 1;
            array47[num50] = num2;
            if (num2 >= 5)
            {
                Main.tileFrameCounter[464] = 0;
                int[] array48 = Main.tileFrame;
                int num51 = 464;
                num2 = array48[num51] + 1;
                array48[num51] = num2;
                if (num2 >= 23)
                {
                    Main.tileFrame[464] = 0;
                }
            }
            int[] array49 = Main.tileFrameCounter;
            int num52 = 485;
            num2 = array49[num52] + 1;
            array49[num52] = num2;
            if (num2 >= 20)
            {
                Main.tileFrameCounter[485] = 0;
            }
            int[] array50 = Main.tileFrameCounter;
            int num53 = 491;
            num2 = array50[num53] + 1;
            array50[num53] = num2;
            if (num2 >= 40)
            {
                Main.tileFrameCounter[491] = 0;
            }
            int[] array51 = Main.tileFrameCounter;
            int num54 = 564;
            num2 = array51[num54] + 1;
            array51[num54] = num2;
            if (num2 >= 5)
            {
                Main.tileFrameCounter[564] = 0;
                Main.tileFrame[564]++;
                if (Main.tileFrame[564] >= 36)
                {
                    Main.tileFrame[564] = 0;
                }
            }
            int[] array52 = Main.tileFrameCounter;
            int num55 = 593;
            num2 = array52[num55] + 1;
            array52[num55] = num2;
            if (num2 >= 5)
            {
                Main.tileFrameCounter[593] = 0;
                Main.tileFrame[593]++;
                if (Main.tileFrame[593] >= 9)
                {
                    Main.tileFrame[593] = 5;
                }
            }
            int[] array53 = Main.tileFrameCounter;
            int num56 = 594;
            num2 = array53[num56] + 1;
            array53[num56] = num2;
            if (num2 >= 5)
            {
                Main.tileFrameCounter[594] = 0;
                Main.tileFrame[594]++;
                if (Main.tileFrame[594] >= 9)
                {
                    Main.tileFrame[594] = 5;
                }
            }
            int[] array54 = Main.tileFrameCounter;
            int num57 = 614;
            num2 = array54[num57] + 1;
            array54[num57] = num2;
            if (num2 >= 5)
            {
                Main.tileFrameCounter[614] = 0;
                Main.tileFrame[614]++;
                if (Main.tileFrame[614] >= 6)
                {
                    Main.tileFrame[614] = 0;
                }
            }
            int[] array55 = Main.tileFrameCounter;
            int num58 = 565;
            num2 = array55[num58] + 1;
            array55[num58] = num2;
            if (num2 >= 4)
            {
                Main.tileFrameCounter[565] = 0;
                Main.tileFrame[565]++;
                if (Main.tileFrame[565] >= 5)
                {
                    Main.tileFrame[565] = 0;
                }
            }
            int[] array56 = Main.tileFrameCounter;
            int num59 = 572;
            num2 = array56[num59] + 1;
            array56[num59] = num2;
            if (num2 >= 6)
            {
                Main.tileFrameCounter[572] = 0;
                int[] array57 = Main.tileFrame;
                int num60 = 572;
                num2 = array57[num60] + 1;
                array57[num60] = num2;
                if (num2 >= 4)
                {
                    Main.tileFrame[572] = 0;
                }
            }
            int[] array58 = Main.tileFrameCounter;
            int num61 = 597;
            num2 = array58[num61] + 1;
            array58[num61] = num2;
            if (num2 >= 64)
            {
                Main.tileFrameCounter[597] = 0;
            }
            int num62 = (int)MathHelper.Clamp((float)Math.Floor((double)(Math.Abs(Main.WindForVisuals) * 10f)) * (float)Math.Sign(Main.WindForVisuals), -5f, 5f);
            Main.tileFrameCounter[489] += num62;
            Main.tileFrameCounter[489] %= 320;
            if (Main.tileFrameCounter[489] < 0)
            {
                Main.tileFrameCounter[489] += 320;
            }
            Main.AnimateTiles_WeatherVane();
            int num63 = (int)MathHelper.Clamp((float)Math.Floor((double)(Math.Abs(Main.WindForVisuals) * 10f)) * (float)Math.Sign(Main.WindForVisuals), -5f, 5f);
            Main.tileFrameCounter[493] += num63;
            Main.tileFrameCounter[493] %= 120;
            if (Main.tileFrameCounter[493] < 0)
            {
                Main.tileFrameCounter[493] += 120;
            }
            Main.AnimateTiles_CritterCages();
        }
References System.Math.Abs(), Terraria.Main.AnimateTiles_CritterCages(), Terraria.Main.AnimateTiles_WeatherVane(), System.array, Microsoft.Xna.Framework.MathHelper.Clamp(), System.Math.Floor(), int, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, System.Math.Sign(), Terraria.Main.tileFrame, Terraria.Main.tileFrameCounter, and Terraria.Main.WindForVisuals.
Referenced by Terraria.Main.DoUpdate().