Terraria Decompiled: Terraria.Main.GetPlayerPathFromName
GetPlayerPathFromName()
static string Terraria.Main.GetPlayerPathFromName (string playerName, bool cloudSave) inline static
Definition at line 2907 of file Main.cs.
        {
            char[] invalidFileNameChars = Path.GetInvalidFileNameChars();
            string text = "";
            playerName = playerName.Replace(".", "_");
            foreach (char c in playerName.Replace("*", "_"))
            {
                char c2;
                if (invalidFileNameChars.Contains(c))
                {
                    c2 = '-';
                }
                else if (c == ' ')
                {
                    c2 = '_';
                }
                else
                {
                    c2 = c;
                }
                text += c2.ToString();
            }
            string text2 = (cloudSave ? Main.CloudPlayerPath : Main.PlayerPath);
            if (FileUtilities.GetFullPath(text2 + Path.DirectorySeparatorChar.ToString() + text + ".plr", cloudSave).StartsWith("\\\\.\\", StringComparison.Ordinal))
            {
                text += "_";
            }
            if (FileUtilities.Exists(text2 + Path.DirectorySeparatorChar.ToString() + text + ".plr", cloudSave))
            {
                int num = 2;
                while (FileUtilities.Exists(string.Concat(new object[]
                {
                    text2,
                    Path.DirectorySeparatorChar.ToString(),
                    text,
                    num,
                    ".plr"
                }), cloudSave))
                {
                    num++;
                }
                text += num;
            }
            return text2 + Path.DirectorySeparatorChar.ToString() + text + ".plr";
        }
References System.IO.Path.DirectorySeparatorChar, Terraria.Utilities.FileUtilities.Exists(), Terraria.Utilities.FileUtilities.GetFullPath(), System.IO.Path.GetInvalidFileNameChars(), Terraria.Main.PlayerPath, and System.text.
Referenced by Terraria.IO.PlayerFileData.CreateAndSave(), Terraria.IO.PlayerFileData.MoveToCloud(), and Terraria.IO.PlayerFileData.MoveToLocal().