Terraria Decompiled: Terraria.Main.DrawSpectatingControlHint
DrawSpectatingControlHint()
static void Terraria.Main.DrawSpectatingControlHint () inline static private
Definition at line 45110 of file Main.cs.
        {
            if ((!Main.LocalPlayer.CanDeathSpectate || !Main.LocalPlayer.AnyoneToSpectate()) && Main.LocalPlayer.spectating < 0)
            {
                return;
            }
            if (Main.drawingPlayerChat || PlayerInput.SettingsForUI.ShowGamepadHints)
            {
                return;
            }
            string textValue = Language.GetTextValue((Main.LocalPlayer.spectating >= 0) ? "Game.SpectateHintChangeTarget" : "Game.SpectateHint");
            ChatManager.DrawColorCodedStringWithShadow(Main.spriteBatch, FontAssets.MouseText.Value, textValue, new Vector2((float)(Main.screenWidth / 2) - FontAssets.MouseText.Value.MeasureString(textValue).X / 2f, (float)(Main.screenHeight - 30)), new Microsoft.Xna.Framework.Color((int)Main.mouseTextColor, (int)Main.mouseTextColor, (int)Main.mouseTextColor, (int)Main.mouseTextColor), 0f, Vector2.Zero, Vector2.One, -1f, 2f);
        }
References Terraria.Player.AnyoneToSpectate(), Terraria.Player.CanDeathSpectate, Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.Main.drawingPlayerChat, Terraria.Localization.Language.GetTextValue(), Terraria.Main.LocalPlayer, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.mouseTextColor, Microsoft.Xna.Framework.Vector2.One, Terraria.Main.screenHeight, Terraria.Main.screenWidth, Terraria.GameInput.PlayerInput.SettingsForUI.ShowGamepadHints, Terraria.Player.spectating, Terraria.Main.spriteBatch, ReLogic.Content.Asset< T >.Value, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.Main.DrawInterface_29B_ControlHints().