Terraria Decompiled: Terraria.Main.DrawInterface_6_TileGridOption
DrawInterface_6_TileGridOption()
static void Terraria.Main.DrawInterface_6_TileGridOption () inline static private
Definition at line 46420 of file Main.cs.
        {
            bool flag = Main.MouseShowBuildingGrid && !Main.SmartCursorIsUsed;
            if (PlayerInput.UsingGamepad && !Main.SmartCursorIsUsed)
            {
                bool flag2 = !PlayerInput.UsingGamepadUI;
            }
            if (flag && !Main.player[Main.myPlayer].dead && !PlayerInput.CursorIsBusy)
            {
                float num = Main.player[Main.myPlayer].velocity.Length();
                float num2 = 6f;
                float num3 = MathHelper.Lerp(0f, 0.7f, MathHelper.Clamp(1f - num / num2, 0f, 1f));
                Main.MouseBuildingGridAlpha = MathHelper.Lerp(Main.MouseBuildingGridAlpha, num3, 0.2f);
                num3 = Main.MouseBuildingGridAlpha;
                if (num3 > 0f)
                {
                    Vector2 vector = Main.MouseWorld.ToTileCoordinates().ToVector2() * 16f;
                    new Vector2((float)Main.offScreenRange, (float)Main.offScreenRange);
                    bool flag3 = Main.drawToScreen;
                    vector -= Main.screenPosition;
                    vector += new Vector2(8f);
                    if (Main.player[Main.myPlayer].gravDir == -1f)
                    {
                        vector.Y = (float)Main.screenHeight - vector.Y;
                    }
                    Texture2D value = TextureAssets.CursorRadial.Value;
                    Main.spriteBatch.Draw(value, vector, null, Microsoft.Xna.Framework.Color.White * 0.5f * num3, 0f, value.Size() / 2f, 1f, SpriteEffects.None, 0f);
                    return;
                }
            }
            else
            {
                Main.MouseBuildingGridAlpha = MathHelper.Clamp(Main.MouseBuildingGridAlpha - 0.05f, 0f, 1f);
            }
        }
References Microsoft.Xna.Framework.MathHelper.Clamp(), Terraria.GameInput.PlayerInput.CursorIsBusy, Terraria.GameContent.TextureAssets.CursorRadial, Terraria.Player.dead, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Main.drawToScreen, Terraria.Player.gravDir, Microsoft.Xna.Framework.Vector2.Length(), Microsoft.Xna.Framework.MathHelper.Lerp(), Terraria.Main.MouseBuildingGridAlpha, Terraria.Main.MouseWorld, Terraria.Main.myPlayer, Terraria.Main.offScreenRange, Terraria.Main.player, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.SmartCursorIsUsed, Terraria.Main.spriteBatch, Terraria.GameInput.PlayerInput.UsingGamepad, Terraria.GameInput.PlayerInput.UsingGamepadUI, System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Entity.velocity, Microsoft.Xna.Framework.Color.White, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Main.SetupDrawInterfaceLayers().