Terraria Decompiled: Terraria.Main.InitializeItemAnimations
InitializeItemAnimations()
static void Terraria.Main.InitializeItemAnimations () inline static
Definition at line 1566 of file Main.cs.
        {
            for (int i = 0; i < Main.itemAnimations.Length; i++)
            {
                Main.itemAnimations[i] = null;
            }
            Main.itemAnimationsRegistered.Clear();
            Main.RegisterItemAnimation(3581, new DrawAnimationVertical(4, 4, false));
            Main.RegisterItemAnimation(3580, new DrawAnimationVertical(6, 4, false));
            Main.RegisterItemAnimation(75, new DrawAnimationVertical(5, 8, false)
            {
                PingPong = true
            });
            Main.RegisterItemAnimation(575, new DrawAnimationVertical(6, 4, false));
            Main.RegisterItemAnimation(547, new DrawAnimationVertical(6, 4, false));
            Main.RegisterItemAnimation(520, new DrawAnimationVertical(6, 4, false));
            Main.RegisterItemAnimation(548, new DrawAnimationVertical(6, 4, false));
            Main.RegisterItemAnimation(521, new DrawAnimationVertical(6, 4, false));
            Main.RegisterItemAnimation(549, new DrawAnimationVertical(6, 4, false));
            Main.RegisterItemAnimation(3453, new DrawAnimationVertical(6, 4, false));
            Main.RegisterItemAnimation(3454, new DrawAnimationVertical(6, 4, false));
            Main.RegisterItemAnimation(3455, new DrawAnimationVertical(6, 4, false));
            Main.RegisterItemAnimation(4068, new DrawAnimationVertical(6, 4, false)
            {
                NotActuallyAnimating = true
            });
            Main.RegisterItemAnimation(4069, new DrawAnimationVertical(6, 4, false)
            {
                NotActuallyAnimating = true
            });
            Main.RegisterItemAnimation(4070, new DrawAnimationVertical(6, 4, false)
            {
                NotActuallyAnimating = true
            });
            for (int j = 0; j < ItemID.Sets.IsFood.Length; j++)
            {
                if (ItemID.Sets.IsFood[j])
                {
                    Main.RegisterItemAnimation(j, new DrawAnimationVertical(int.MaxValue, 3, false));
                }
            }
            Main.RegisterItemAnimation(5644, new DrawAnimationScryingOrb
            {
                TicksPerFrame = 7,
                FrameCount = 9
            });
        }
References System.Collections.Generic.List< T >.Clear(), Terraria.ID.ItemID.Sets.IsFood, Terraria.Main.itemAnimations, Terraria.Main.itemAnimationsRegistered, System.Reflection.MaxValue, and Terraria.Main.RegisterItemAnimation().
Referenced by Terraria.Main.Initialize_AlmostEverything().