Terraria Decompiled: Terraria.Main.LoadPlayers
LoadPlayers()
static void Terraria.Main.LoadPlayers () inline static
Definition at line 2077 of file Main.cs.
        {
            Main.PlayerList.Clear();
            if (!Utils.TryCreatingDirectory(Main.PlayerPath))
            {
                return;
            }
            string[] files = Directory.GetFiles(Main.PlayerPath, "*.plr");
            int num = Math.Min(Main.maxLoadPlayer, files.Length);
            for (int i = 0; i < num; i++)
            {
                PlayerFileData fileData = Player.GetFileData(files[i], false);
                if (fileData != null)
                {
                    Main.PlayerList.Add(fileData);
                }
            }
            if (SocialAPI.Cloud != null)
            {
                foreach (string text in from path in SocialAPI.Cloud.GetFiles()
                    where path.StartsWith(Main.CloudPlayerPath, StringComparison.CurrentCultureIgnoreCase) && path.EndsWith(".plr", StringComparison.CurrentCultureIgnoreCase)
                    select path)
                {
                    PlayerFileData fileData2 = Player.GetFileData(text, true);
                    if (fileData2 != null)
                    {
                        Main.PlayerList.Add(fileData2);
                    }
                }
            }
            Main.PlayerList.Sort(new Comparison<PlayerFileData>(Main.PlayerListSortMethod));
        }
References System.Collections.Generic.List< T >.Add(), System.Collections.Generic.List< T >.Clear(), Terraria.Social.SocialAPI.Cloud, Terraria.Main.CloudPlayerPath, Terraria.Player.GetFileData(), System.IO.Directory.GetFiles(), Terraria.Main.maxLoadPlayer, System.Math.Min(), Terraria.Main.PlayerList, Terraria.Main.PlayerListSortMethod(), Terraria.Main.PlayerPath, System.Collections.Generic.List< T >.Sort(), System.text, and Terraria.Utils.TryCreatingDirectory().
Referenced by Terraria.Main.DrawMenu(), Terraria.Main.ErasePlayer(), Terraria.GameContent.UI.States.UICharacterCreation.FinishCreatingCharacter(), Terraria.GameContent.UI.States.UICharacterSelect.OnActivate(), Terraria.Main.OnCharacterNamed(), Terraria.Main.OpenPlayerSelect(), and Terraria.Testing.QuickLoad.JoinWorld.SelectPlayerAndWorld().