Terraria Decompiled: Terraria.Main.IsItDay
IsItDay()
static bool Terraria.Main.IsItDay () inline static
Definition at line 63848 of file Main.cs.
        {
            return !Main.remixWorld && Main.dayTime;
        }
References Terraria.Main.dayTime.
Referenced by Terraria.NPC.AI(), Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_005_EaterOfSouls(), Terraria.NPC.AI_037_Destroyer(), Terraria.NPC.checkDead(), Terraria.GameContent.NPCInteractions.Actions.OldManCurse.Condition(), Terraria.NPC.DespawnEncouragement_AIStyle2_FloatingEye_IsDiscouraged(), Terraria.NPC.DespawnEncouragement_AIStyle3_Fighters_NotDiscouraged(), Terraria.Player.ItemCheck_CheckCanUse_Inner(), Terraria.Player.ItemCheck_UseBossSpawners(), Terraria.NPC.RedHatSkeletron(), and Terraria.GameContent.PlayerSittingHelper.UpdateSitting().