Terraria Decompiled: Terraria.Main.DrawTileCracks
DrawTileCracks()
void Terraria.Main.DrawTileCracks (int crackType, HitTile hitter) inline
Definition at line 62490 of file Main.cs.
        {
            Vector2 zero = new Vector2((float)Main.offScreenRange, (float)Main.offScreenRange);
            if (Main.drawToScreen)
            {
                zero = Vector2.Zero;
            }
            bool flag = Main.ShouldShowInvisibleBlocksAndWalls();
            for (int i = 0; i < hitter.data.Length; i++)
            {
                if (hitter.data[i].type == crackType)
                {
                    int damage = hitter.data[i].damage;
                    if (damage >= 20)
                    {
                        int x = hitter.data[i].X;
                        int y = hitter.data[i].Y;
                        if (WorldGen.InWorld(x, y, 0))
{
                            bool flag2 = Main.tile[x, y] != null;
                            if (flag2 && crackType == 1)
{
                                flag2 = flag2 && Main.tile[x, y].active() && (flag || !Main.tile[x, y].invisibleBlock());
                            }
                            if (flag2 && crackType == 2)
{
                                flag2 = flag2 && Main.tile[x, y].wall != 0 && (flag || !Main.tile[x, y].invisibleWall());
                            }
                            if (flag2)
{
                                bool flag3 = false;
                                bool flag4 = false;
                                if (Main.tile[x, y].type == 10)
{
                                    flag3 = false;
                                }
                                else if (Main.tileSolid[(int)Main.tile[x, y].type] && !Main.tileSolidTop[(int)Main.tile[x, y].type])
{
                                    flag3 = true;
                                }
                                else if (WorldGen.IsTreeType((int)Main.tile[x, y].type))
{
                                    flag4 = true;
                                    int num = (int)(Main.tile[x, y].frameX / 22);
                                    int num2 = (int)(Main.tile[x, y].frameY / 22);
                                    if (num2 < 9)
{
                                        flag3 = ((num != 1 && num != 2) || num2 < 6 || num2 > 8) && (num != 3 || num2 > 2) && (num != 4 || num2 < 3 || num2 > 5) && (num != 5 || num2 < 6 || num2 > 8);
                                    }
                                }
                                else if (Main.tile[x, y].type == 72)
{
                                    flag4 = true;
                                    if (Main.tile[x, y].frameX <= 34)
{
                                        flag3 = true;
                                    }
                                }
                                if (flag3 && Main.tile[x, y].slope() == 0 && !Main.tile[x, y].halfBrick())
{
                                    int num3 = 0;
                                    if (damage >= 80)
{
                                        num3 = 3;
                                    }
                                    else if (damage >= 60)
{
                                        num3 = 2;
                                    }
                                    else if (damage >= 40)
{
                                        num3 = 1;
                                    }
                                    else if (damage >= 20)
{
                                        num3 = 0;
                                    }
                                    Microsoft.Xna.Framework.Rectangle rectangle = new Microsoft.Xna.Framework.Rectangle(hitter.data[i].crackStyle * 18, num3 * 18, 16, 16);
                                    if (flag4)
{
                                        rectangle.X = (4 + hitter.data[i].crackStyle / 2) * 18;
                                    }
                                    Main.spriteBatch.Draw(TextureAssets.TileCrack.Value, new Vector2((float)(x * 16 - (int)Main.screenPosition.X), (float)(y * 16 - (int)Main.screenPosition.Y)) + zero, new Microsoft.Xna.Framework.Rectangle?(rectangle), Lighting.GetColor(x, y), 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
                                }
                            }
                        }
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.HitTile.data, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Main.drawToScreen, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Lighting.GetColor(), Terraria.Tile.halfBrick(), int, Terraria.Tile.invisibleBlock(), Terraria.Tile.invisibleWall(), Terraria.WorldGen.InWorld(), Terraria.WorldGen.IsTreeType(), Terraria.Main.offScreenRange, Terraria.Main.screenPosition, Terraria.Main.ShouldShowInvisibleBlocksAndWalls(), Terraria.Tile.slope(), Terraria.Main.spriteBatch, Terraria.Main.tile, Terraria.GameContent.TextureAssets.TileCrack, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Tile.type, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Tile.wall, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.Drawing.TileDrawing.Draw(), and Terraria.GameContent.Drawing.WallDrawing.DrawWalls().