Terraria Decompiled: Terraria.Main.DrawSimpleSurfaceBackground
DrawSimpleSurfaceBackground()
void Terraria.Main.DrawSimpleSurfaceBackground (Vector2 areaPosition, int areaWidth, int areaHeight) inline
Definition at line 57461 of file Main.cs.
        {
            float num = (float)(Main.worldSurface + 1.0) * 16f;
            float num2 = Math.Min(areaPosition.Y + (float)areaHeight, num) - areaPosition.Y;
            float y = areaPosition.Y;
            float num3 = areaPosition.Y + num2;
            Vector4 vector = Main.ColorOfTheSkies.ToVector4();
            Vector4 vector2 = new Microsoft.Xna.Framework.Color(53, 43, 243).ToVector4() * vector;
            Vector4 vector3 = new Microsoft.Xna.Framework.Color(132, 170, 248).ToVector4() * vector;
            Microsoft.Xna.Framework.Color color = new Microsoft.Xna.Framework.Color(Vector4.Lerp(vector2, vector3, y / num));
            Microsoft.Xna.Framework.Color color2 = new Microsoft.Xna.Framework.Color(Vector4.Lerp(vector2, vector3, num3 / num));
            VertexColors vertexColors;
            vertexColors.TopLeftColor = color;
            vertexColors.TopRightColor = color;
            vertexColors.BottomLeftColor = color2;
            vertexColors.BottomRightColor = color2;
            Main.tileBatch.Draw(TextureAssets.BlackTile.Value, new Vector4(0f, 0f, (float)areaWidth, num2), vertexColors);
            float num4 = (float)areaHeight - num2;
            if (num4 > 0f)
            {
                vertexColors.TopLeftColor = Microsoft.Xna.Framework.Color.Black;
                vertexColors.TopRightColor = Microsoft.Xna.Framework.Color.Black;
                vertexColors.BottomLeftColor = Microsoft.Xna.Framework.Color.Black;
                vertexColors.BottomRightColor = Microsoft.Xna.Framework.Color.Black;
                Main.tileBatch.Draw(TextureAssets.BlackTile.Value, new Vector4(0f, num2, (float)areaWidth, num4), vertexColors);
            }
        }
References Microsoft.Xna.Framework.Color.Black, Terraria.GameContent.TextureAssets.BlackTile, Terraria.Main.ColorOfTheSkies, Terraria.Graphics.TileBatch.Draw(), Microsoft.Xna.Framework.Vector4.Lerp(), System.Math.Min(), Terraria.Main.tileBatch, Microsoft.Xna.Framework.Color.ToVector4(), ReLogic.Content.Asset< T >.Value, Terraria.Main.worldSurface, and Microsoft.Xna.Framework.Vector2.Y.