Terraria Decompiled: Terraria.Main.DrawInterface_3_LaserRuler
DrawInterface_3_LaserRuler()
static void Terraria.Main.DrawInterface_3_LaserRuler () inline static private
Definition at line 46564 of file Main.cs.
        {
            if (Main.player[Main.myPlayer].rulerGrid && Main.player[Main.myPlayer].builderAccStatus[1] == 0)
            {
                float num = Main.player[Main.myPlayer].velocity.Length();
                num = Vector2.Distance(Main.player[Main.myPlayer].position, Main.player[Main.myPlayer].shadowPos[2]);
                float num2 = 6f;
                Texture2D value = TextureAssets.Extra[68].Value;
                float num3 = MathHelper.Lerp(0.2f, 0.7f, MathHelper.Clamp(1f - num / num2, 0f, 1f));
                Vector2 vector = Main.screenPosition;
                vector += new Vector2(-50f);
                vector = vector.ToTileCoordinates().ToVector2() * 16f;
                int num4 = (Main.screenWidth + 100) / 16;
                int num5 = (Main.screenHeight + 100) / 16;
                Microsoft.Xna.Framework.Point point = Main.MouseWorld.ToTileCoordinates();
                point.X -= (int)vector.X / 16;
                point.Y -= (int)vector.Y / 16;
                Microsoft.Xna.Framework.Color color = new Microsoft.Xna.Framework.Color(0.24f, 0.8f, 0.9f, 0.5f) * 0.4f * num3;
                Microsoft.Xna.Framework.Color color2 = new Microsoft.Xna.Framework.Color(1f, 0.8f, 0.9f, 0.5f) * 0.5f * num3;
                Microsoft.Xna.Framework.Rectangle rectangle = new Microsoft.Xna.Framework.Rectangle(0, 18, 18, 18);
                vector -= Vector2.One;
                for (int i = 0; i < num4; i++)
                {
                    for (int j = 0; j < num5; j++)
                    {
                        Microsoft.Xna.Framework.Color color3 = color;
                        Vector2 zero = Vector2.Zero;
                        if (i != point.X && j != point.Y)
{
                            if (i != point.X + 1)
{
                                rectangle.X = 0;
                                rectangle.Width = 16;
                            }
                            else
{
                                rectangle.X = 2;
                                rectangle.Width = 14;
                                zero.X = 2f;
                            }
                            if (j != point.Y + 1)
{
                                rectangle.Y = 18;
                                rectangle.Height = 16;
                            }
                            else
{
                                rectangle.Y = 2;
                                rectangle.Height = 14;
                                zero.Y = 2f;
                            }
                            Main.spriteBatch.Draw(value, Main.ReverseGravitySupport(new Vector2((float)i, (float)j) * 16f - Main.screenPosition + vector + zero, 16f), new Microsoft.Xna.Framework.Rectangle?(rectangle), color3, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                        }
                    }
                }
                rectangle = new Microsoft.Xna.Framework.Rectangle(0, 0, 16, 18);
                for (int k = 0; k < num4; k++)
                {
                    if (k == point.X)
                    {
                        Main.spriteBatch.Draw(value, Main.ReverseGravitySupport(new Vector2((float)k, (float)point.Y) * 16f - Main.screenPosition + vector, 16f), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, 16, 16)), color2, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                    }
                    else
                    {
                        Main.spriteBatch.Draw(value, Main.ReverseGravitySupport(new Vector2((float)k, (float)point.Y) * 16f - Main.screenPosition + vector, 16f), new Microsoft.Xna.Framework.Rectangle?(rectangle), color2, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                    }
                }
                rectangle = new Microsoft.Xna.Framework.Rectangle(0, 0, 18, 16);
                for (int l = 0; l < num5; l++)
                {
                    if (l != point.Y)
                    {
                        Main.spriteBatch.Draw(value, Main.ReverseGravitySupport(new Vector2((float)point.X, (float)l) * 16f - Main.screenPosition + vector, 16f), new Microsoft.Xna.Framework.Rectangle?(rectangle), color2, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                    }
                }
            }
        }
References Terraria.Player.builderAccStatus, Microsoft.Xna.Framework.MathHelper.Clamp(), Microsoft.Xna.Framework.Vector2.Distance(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.GameContent.TextureAssets.Extra, int, Microsoft.Xna.Framework.Vector2.Length(), Microsoft.Xna.Framework.MathHelper.Lerp(), Terraria.Main.MouseWorld, Terraria.Main.myPlayer, Microsoft.Xna.Framework.Vector2.One, Terraria.Main.player, Terraria.Entity.position, Terraria.Main.ReverseGravitySupport(), Terraria.Player.rulerGrid, Terraria.Main.screenPosition, Terraria.Player.shadowPos, Terraria.Main.spriteBatch, System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Entity.velocity, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Point.Y, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.Main.SetupDrawInterfaceLayers().