Terraria Decompiled: Terraria.Main.DrawItem
DrawItem()
void Terraria.Main.DrawItem (WorldItem item, int whoami) inline protected
Definition at line 38057 of file Main.cs.
        {
            if (!item.active || item.IsAir)
            {
                return;
            }
            Main.instance.LoadItem(item.type);
            Texture2D texture2D;
            Microsoft.Xna.Framework.Rectangle rectangle;
            Microsoft.Xna.Framework.Rectangle rectangle2;
            this.DrawItem_GetBasics(item.inner, whoami, out texture2D, out rectangle, out rectangle2);
            Vector2 vector = rectangle.Size() / 2f;
            Vector2 vector2 = new Vector2((float)(item.width / 2) - vector.X, (float)(item.height - rectangle.Height));
            Vector2 vector3 = item.position - Main.screenPosition + vector + vector2;
            float num = ((!item.onConveyor) ? (item.velocity.X * 0.2f) : 0f);
            if (item.shimmered)
            {
                num = 0f;
            }
            float num2 = 1f;
            Microsoft.Xna.Framework.Color color = Lighting.GetColor(item.Center.ToTileCoordinates());
            Microsoft.Xna.Framework.Color alpha = item.GetAlpha(color);
            if (item.shimmered)
            {
                alpha.R = (byte)(255f * (1f - item.shimmerTime));
                alpha.G = (byte)(255f * (1f - item.shimmerTime));
                alpha.B = (byte)(255f * (1f - item.shimmerTime));
                alpha.A = (byte)(255f * (1f - item.shimmerTime));
            }
            else if (item.shimmerTime > 0f)
            {
                alpha.R = (byte)((float)alpha.R * (1f - item.shimmerTime));
                alpha.G = (byte)((float)alpha.G * (1f - item.shimmerTime));
                alpha.B = (byte)((float)alpha.B * (1f - item.shimmerTime));
                alpha.A = (byte)((float)alpha.A * (1f - item.shimmerTime));
            }
            ItemSlot.GetItemLight(ref alpha, ref num2, item.inner, false, 1f);
            int num3 = item.glowMask;
            if (FocusHelper.AllowWorldItemsToEmitEffects && (item.IsACoin || item.type == 58 || item.type == 109) && color.R > 60 && (float)Main.rand.Next(500) - (Math.Abs(item.velocity.X) + Math.Abs(item.velocity.Y)) * 10f < (float)(color.R / 50))
            {
                int num4 = 43;
                Microsoft.Xna.Framework.Color color2 = Microsoft.Xna.Framework.Color.White;
                int num5 = 254;
                float num6 = 0.5f;
                if (item.IsACoin)
                {
                    color2 = default(Microsoft.Xna.Framework.Color);
                    num5 = 0;
                    num6 = 1f;
                }
                switch (item.type)
                {
                case 71:
                    num4 = 244;
                    break;
                case 72:
                    num4 = 245;
                    break;
                case 73:
                    num4 = 246;
                    break;
                case 74:
                    num4 = 247;
                    break;
                }
                int num7 = Dust.NewDust(item.position, item.width, item.height, num4, 0f, 0f, num5, color2, num6);
                Main.dust[num7].velocity *= 0f;
            }
            if (ItemID.Sets.BossBag[item.type])
            {
                float num8 = (float)item.timeSinceItemSpawned / 240f + Main.GlobalTimeWrappedHourly * 0.04f;
                float num9 = Main.GlobalTimeWrappedHourly;
                num9 %= 4f;
                num9 /= 2f;
                if (num9 >= 1f)
                {
                    num9 = 2f - num9;
                }
                num9 = num9 * 0.5f + 0.5f;
                for (float num10 = 0f; num10 < 1f; num10 += 0.25f)
                {
                    Main.spriteBatch.Draw(texture2D, vector3 + new Vector2(0f, 8f).RotatedBy((double)((num10 + num8) * 6.2831855f), default(Vector2)) * num9, new Microsoft.Xna.Framework.Rectangle?(rectangle), new Microsoft.Xna.Framework.Color(90, 70, 255, 50), num, vector, num2, SpriteEffects.None, 0f);
                }
                for (float num11 = 0f; num11 < 1f; num11 += 0.34f)
                {
                    Main.spriteBatch.Draw(texture2D, vector3 + new Vector2(0f, 4f).RotatedBy((double)((num11 + num8) * 6.2831855f), default(Vector2)) * num9, new Microsoft.Xna.Framework.Rectangle?(rectangle), new Microsoft.Xna.Framework.Color(140, 120, 255, 77), num, vector, num2, SpriteEffects.None, 0f);
                }
            }
            else if (item.type == 75)
            {
                float num12 = (float)item.timeSinceItemSpawned / 240f + Main.GlobalTimeWrappedHourly * 0.04f;
                float num13 = Main.GlobalTimeWrappedHourly;
                num13 %= 5f;
                num13 /= 2.5f;
                if (num13 >= 1f)
                {
                    num13 = 2f - num13;
                }
                num13 = num13 * 0.5f + 0.5f;
                for (float num14 = 0f; num14 < 1f; num14 += 0.25f)
                {
                    Main.spriteBatch.Draw(TextureAssets.Item[item.type].Value, vector3 + new Vector2(0f, 8f).RotatedBy((double)((num14 + num12) * 6.2831855f), default(Vector2)) * num13, new Microsoft.Xna.Framework.Rectangle?(rectangle), new Microsoft.Xna.Framework.Color(50, 50, 255, 50), num, vector, num2, SpriteEffects.None, 0f);
                }
                for (float num15 = 0f; num15 < 1f; num15 += 0.34f)
                {
                    Main.spriteBatch.Draw(TextureAssets.Item[item.type].Value, vector3 + new Vector2(0f, 4f).RotatedBy((double)((num15 + num12) * 6.2831855f), default(Vector2)) * num13, new Microsoft.Xna.Framework.Rectangle?(rectangle), new Microsoft.Xna.Framework.Color(120, 120, 255, 127), num, vector, num2, SpriteEffects.None, 0f);
                }
            }
            else if (item.type == 4143)
            {
                float num16 = (float)item.timeSinceItemSpawned / 240f + Main.GlobalTimeWrappedHourly * 0.04f;
                float num17 = Main.GlobalTimeWrappedHourly;
                num17 %= 5f;
                num17 /= 2.5f;
                if (num17 >= 1f)
                {
                    num17 = 2f - num17;
                }
                num17 = num17 * 0.5f + 0.5f;
                for (float num18 = 0f; num18 < 1f; num18 += 0.34f)
                {
                    Main.spriteBatch.Draw(TextureAssets.Item[item.type].Value, vector3 + new Vector2(0f, 8f).RotatedBy((double)((num18 + num16) * 6.2831855f), default(Vector2)) * num17, new Microsoft.Xna.Framework.Rectangle?(rectangle), new Microsoft.Xna.Framework.Color(30, 30, 155, 60), num, vector, num2, SpriteEffects.None, 0f);
                }
                for (float num19 = 0f; num19 < 1f; num19 += 0.34f)
                {
                    Main.spriteBatch.Draw(TextureAssets.Item[item.type].Value, vector3 + new Vector2(0f, 4f).RotatedBy((double)((num19 + num16) * 6.2831855f), default(Vector2)) * num17, new Microsoft.Xna.Framework.Rectangle?(rectangle), new Microsoft.Xna.Framework.Color(60, 60, 127, 57), num, vector, num2, SpriteEffects.None, 0f);
                }
                Main.spriteBatch.Draw(texture2D, vector3, new Microsoft.Xna.Framework.Rectangle?(rectangle), new Microsoft.Xna.Framework.Color(255, 255, 255, 128), num, vector, num2, SpriteEffects.None, 0f);
            }
            if ((item.type >= 1522 && item.type <= 1527) || item.type == 3643)
            {
                if (item.shimmerTime > 0f)
                {
                    alpha = new Microsoft.Xna.Framework.Color((int)(250f * (1f - item.shimmerTime)), (int)(250f * (1f - item.shimmerTime)), (int)(250f * (1f - item.shimmerTime)), (int)((float)(Main.mouseTextColor / 2) * (1f - item.shimmerTime)));
                }
                else
                {
                    alpha = new Microsoft.Xna.Framework.Color(250, 250, 250, (int)(Main.mouseTextColor / 2));
                }
                num2 = (float)Main.mouseTextColor / 1000f + 0.8f;
            }
            if (item.type == 3779)
            {
                num3 = -1;
            }
            Main.spriteBatch.Draw(texture2D, vector3, new Microsoft.Xna.Framework.Rectangle?(rectangle), alpha, num, vector, num2, SpriteEffects.None, 0f);
            if (item.shimmered)
            {
                Main.spriteBatch.Draw(texture2D, vector3, new Microsoft.Xna.Framework.Rectangle?(rectangle), new Microsoft.Xna.Framework.Color((int)alpha.R, (int)alpha.G, (int)alpha.B, 0), num, vector, num2, SpriteEffects.None, 0f);
            }
            if (item.color != Microsoft.Xna.Framework.Color.Transparent)
            {
                Main.spriteBatch.Draw(texture2D, vector3, new Microsoft.Xna.Framework.Rectangle?(rectangle), item.GetColor(color), num, vector, num2, SpriteEffects.None, 0f);
            }
            if (num3 != -1 && item.type != 46 && item.type != 5462)
            {
                Microsoft.Xna.Framework.Color color3 = Microsoft.Xna.Framework.Color.White;
                int type = item.type;
                if (type <= 5146)
                {
                    if (type != 3858)
                    {
                        if (type == 5146)
{
                            color3 = new Microsoft.Xna.Framework.Color(Main.DiscoR, Main.DiscoG, Main.DiscoB);
                        }
                    }
                    else
                    {
                        color3 = new Microsoft.Xna.Framework.Color(255, 255, 255, 63) * 0.75f;
                    }
                }
                else if (type != 5462)
                {
                    if (type != 5669)
                    {
                        if (type - 5670 <= 1)
{
                            color3 = Item.GetPhaseColor(item.shoot, false);
                        }
                    }
                    else
                    {
                        float num20 = Utils.WrappedLerp(0.5f, 1f, (float)(Main.LocalPlayer.miscCounter % 100) / 100f);
                        color3 = Microsoft.Xna.Framework.Color.Lerp(color3, new Microsoft.Xna.Framework.Color(180, 85, 30), num20);
                        color3.A = (byte)item.alpha;
                    }
                }
                else
                {
                    color3 = new Microsoft.Xna.Framework.Color(255, 140, 0, 5);
                }
                if (item.type == 5670 || item.type == 5671)
                {
                    Main.spriteBatch.Draw(TextureAssets.GlowMask[num3].Value, vector3, new Microsoft.Xna.Framework.Rectangle?(rectangle2), color3, num, rectangle2.Size() / 2f, num2, SpriteEffects.None, 0f);
                    color3 = Item.GetPhaseColor(item.shoot, true);
                }
                Main.spriteBatch.Draw(TextureAssets.GlowMask[num3].Value, vector3, new Microsoft.Xna.Framework.Rectangle?(rectangle2), color3, num, rectangle2.Size() / 2f, num2, SpriteEffects.None, 0f);
            }
            if (ItemID.Sets.TrapSigned[item.type])
            {
                Main.spriteBatch.Draw(TextureAssets.Wire.Value, vector3 + rectangle.Size().RotatedBy((double)(num - 1.5707964f), default(Vector2)) * 0.45f * item.scale, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(4, 58, 8, 8)), alpha, 0f, new Vector2(4f), 1f, SpriteEffects.None, 0f);
            }
            if (ItemID.Sets.DrawUnsafeIndicator[item.type])
            {
                Vector2 vector4 = rectangle.Size() * 0.45f + new Vector2(-4f, -4f);
                Texture2D value = TextureAssets.Extra[258].Value;
                Microsoft.Xna.Framework.Rectangle rectangle3 = value.Frame(1, 1, 0, 0, 0, 0);
                Main.spriteBatch.Draw(value, vector3 + vector4.RotatedBy((double)(num - 1.5707964f), default(Vector2)) * item.scale, new Microsoft.Xna.Framework.Rectangle?(rectangle3), alpha, num, rectangle3.Size() / 2f, 1f, SpriteEffects.None, 0f);
            }
        }
References System.Math.Abs(), Terraria.FocusHelper.AllowWorldItemsToEmitEffects, Microsoft.Xna.Framework.Color.B, Terraria.ID.ItemID.Sets.BossBag, Terraria.Main.DiscoB, Terraria.Main.DiscoG, Terraria.Main.DiscoR, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.ID.ItemID.Sets.DrawUnsafeIndicator, Terraria.Main.dust, Terraria.GameContent.TextureAssets.Extra, Microsoft.Xna.Framework.Color.G, Terraria.Lighting.GetColor(), Terraria.UI.ItemSlot.GetItemLight(), Terraria.Item.GetPhaseColor(), Terraria.Main.GlobalTimeWrappedHourly, Terraria.GameContent.TextureAssets.GlowMask, Microsoft.Xna.Framework.Rectangle.Height, Terraria.Main.instance, System.item, Terraria.GameContent.TextureAssets.Item, Microsoft.Xna.Framework.Color.Lerp(), Terraria.Main.LoadItem(), Terraria.Main.LocalPlayer, Terraria.Player.miscCounter, Terraria.Main.mouseTextColor, Terraria.Dust.NewDust(), Terraria.Utilities.UnifiedRandom.Next(), Microsoft.Xna.Framework.Color.R, Terraria.Main.rand, Terraria.Main.spriteBatch, Microsoft.Xna.Framework.Color.Transparent, Terraria.ID.ItemID.Sets.TrapSigned, System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Dust.velocity, Microsoft.Xna.Framework.Color.White, Terraria.GameContent.TextureAssets.Wire, Terraria.Utils.WrappedLerp(), and Microsoft.Xna.Framework.Vector2.X.