Terraria Decompiled: Terraria.Main.UpdateTimeRate
UpdateTimeRate()
static void Terraria.Main.UpdateTimeRate () inline static
Definition at line 4414 of file Main.cs.
        {
            if (Main.IsFastForwardingTime())
            {
                Main.dayRate = 60;
                Main.desiredWorldTilesUpdateRate = 1;
                return;
            }
            bool enabled = CreativePowerManager.Instance.GetPower<CreativePowers.FreezeTime>().Enabled;
            int targetTimeRate = CreativePowerManager.Instance.GetPower<CreativePowers.ModifyTimeRate>().TargetTimeRate;
            bool flag = Main.CurrentFrameFlags.SleepingPlayersCount == Main.CurrentFrameFlags.ActivePlayersCount && Main.CurrentFrameFlags.SleepingPlayersCount > 0;
            int num = targetTimeRate;
            if (!Main.gameMenu && flag)
            {
                num *= 5;
            }
            if (enabled)
            {
                num = 0;
            }
            Main.dayRate = num;
            Main.desiredWorldTilesUpdateRate = num;
            if (Main.gameMenu)
            {
                Main.dayRate = 1;
                Main.desiredWorldTilesUpdateRate = 1;
            }
        }
References Terraria.Main.gameMenu, Terraria.GameContent.Creative.CreativePowerManager.Instance, and Terraria.Main.IsFastForwardingTime().
Referenced by Terraria.WorldGen.clearWorld(), Terraria.MessageBuffer.GetData(), Terraria.WorldGen.JustQuit(), Terraria.IO.WorldFile.LoadHeader(), Terraria.WorldGen.RenameWorldCallBack(), Terraria.WorldGen.SaveAndQuitCallBack(), Terraria.Main.UpdateTime(), Terraria.Main.UpdateTime_StartDay(), and Terraria.Main.UpdateTime_StartNight().