Terraria Decompiled: Terraria.Main.DrawInterface_9_WireSelection
DrawInterface_9_WireSelection()
static void Terraria.Main.DrawInterface_9_WireSelection () inline static private
Definition at line 46378 of file Main.cs.
        {
            if (!Main.hideUI)
            {
                Main.DrawInterface_Resources_GolfPower();
                Main.DrawInterface_GolfBallIndicator();
            }
            WiresUI.HandleWiresUI(Main.spriteBatch);
        }
References Terraria.Main.DrawInterface_GolfBallIndicator(), Terraria.Main.DrawInterface_Resources_GolfPower(), Terraria.GameContent.UI.WiresUI.HandleWiresUI(), Terraria.Main.hideUI, and Terraria.Main.spriteBatch.
Referenced by Terraria.Main.SetupDrawInterfaceLayers().