Terraria Decompiled: Terraria.Main.DrawSurfaceBG_Forest
DrawSurfaceBG_Forest()
void Terraria.Main.DrawSurfaceBG_Forest (float backgroundTopMagicNumber, float bgGlobalScaleMultiplier, int pushBGTopHack, int[] bgTexIndexes) inline private
Definition at line 62226 of file Main.cs.
        {
            Main.bgScale = 1.25f;
            this.bgParallax = 0.4;
            this.bgTopY = backgroundTopMagicNumber * 1800f + 1500f + this.scAdj + (float)pushBGTopHack;
            if (bgTexIndexes[0] == 91)
            {
                this.bgParallax = 0.27000001072883606;
                Main.bgScale = 1.2f;
            }
            if (bgTexIndexes[0] == 173)
            {
                this.bgParallax = 0.25;
                Main.bgScale = 1.3f;
            }
            if (bgTexIndexes[0] == 178)
            {
                this.bgParallax = 0.30000001192092896;
                Main.bgScale = 1.2f;
            }
            if (bgTexIndexes[0] == 184)
            {
                this.bgParallax = 0.25;
                Main.bgScale = 1.2f;
            }
            if (bgTexIndexes[0] == 282)
            {
                Main.bgScale = 1.4f;
            }
            this.SetBackgroundOffsets(bgTexIndexes[0], backgroundTopMagicNumber, pushBGTopHack);
            Main.bgScale *= bgGlobalScaleMultiplier;
            SkyManager.Instance.DrawToDepth(Main.spriteBatch, 1f / (float)this.bgParallax);
            if (bgTexIndexes[0] >= 0)
            {
                this.SetBackgroundOffsets(bgTexIndexes[0], backgroundTopMagicNumber, pushBGTopHack);
                this.LoadBackground(bgTexIndexes[0]);
                Main.bgWidthScaled = (int)((float)Main.backgroundWidth[bgTexIndexes[0]] * Main.bgScale);
                this.bgStartX = (int)(-Math.IEEERemainder((double)Main.screenPosition.X * this.bgParallax, (double)Main.bgWidthScaled) - (double)(Main.bgWidthScaled / 2));
                if (bgTexIndexes[0] == 91)
                {
                    this.bgTopY = backgroundTopMagicNumber * 1600f + 1400f + this.scAdj + (float)pushBGTopHack;
                }
                if (bgTexIndexes[0] == 173)
                {
                    this.bgTopY = backgroundTopMagicNumber * 1600f + 1400f + this.scAdj + (float)pushBGTopHack;
                }
                if (bgTexIndexes[0] == 184)
                {
                    this.bgTopY = backgroundTopMagicNumber * 1600f + 1400f + this.scAdj + (float)pushBGTopHack;
                }
                if (Main.gameMenu)
                {
                    this.bgTopY = (float)(320 + pushBGTopHack);
                }
                if (bgTexIndexes[0] == 50)
                {
                    this.bgTopY -= 50f;
                }
                if (bgTexIndexes[0] == 53)
                {
                    this.bgTopY -= 100f;
                }
                if (bgTexIndexes[0] == 91)
                {
                    this.bgTopY += 200f;
                }
                if (bgTexIndexes[0] == 173)
                {
                    this.bgTopY += 200f;
                }
                if (bgTexIndexes[0] == 178)
                {
                    this.bgTopY += 75f;
                }
                if (bgTexIndexes[0] == 330)
                {
                    this.bgTopY -= 150f;
                }
                if (bgTexIndexes[0] == 335)
                {
                    this.bgTopY -= 150f;
                }
                if (bgTexIndexes[0] == 343)
                {
                    this.bgTopY -= 300f;
                }
                if (Main.bgWidthScaled == 0)
                {
                    return;
                }
                this.bgLoops = Main.screenWidth / Main.bgWidthScaled + 2;
                if ((double)Main.screenPosition.Y < Main.worldSurface * 16.0 + 16.0)
                {
                    for (int i = 0; i < this.bgLoops; i++)
                    {
                        if (bgTexIndexes[0] != -1)
{
                            Asset<Texture2D> asset = TextureAssets.Background[bgTexIndexes[0]];
                            int num = bgTexIndexes[0];
                            if (num == 173)
{
                                int num2 = (int)(this.GetBackgroundCounter() / 10U);
                                num2 %= 4;
                                int num3 = 251 + num2;
                                this.LoadBackground(num3);
                                asset = TextureAssets.Background[num3];
                            }
                            if (asset.Value != null)
{
                                Main.spriteBatch.Draw(asset.Value, new Vector2((float)(this.bgStartX + Main.bgWidthScaled * i), this.bgTopY), this.GetBackgroundRect(bgTexIndexes[0]), Main.ColorOfSurfaceBackgroundsModified, 0f, default(Vector2), Main.bgScale, SpriteEffects.None, 0f);
                            }
                        }
                    }
                }
            }
            if (bgTexIndexes[1] >= 0)
            {
                this.LoadBackground(bgTexIndexes[1]);
                Main.bgScale = 1.31f;
                Main.bgScale *= bgGlobalScaleMultiplier;
                this.bgParallax = 0.43;
                this.SetBackgroundOffsets(bgTexIndexes[1], backgroundTopMagicNumber, pushBGTopHack);
                Main.bgWidthScaled = (int)((float)Main.backgroundWidth[bgTexIndexes[1]] * Main.bgScale);
                if (Main.bgWidthScaled == 0)
                {
                    Main.bgWidthScaled = 1;
                }
                SkyManager.Instance.DrawToDepth(Main.spriteBatch, 1f / (float)this.bgParallax);
                this.bgStartX = (int)(-Math.IEEERemainder((double)Main.screenPosition.X * this.bgParallax, (double)Main.bgWidthScaled) - (double)(Main.bgWidthScaled / 2));
                this.bgTopY = backgroundTopMagicNumber * 1950f + 1750f + this.scAdj + (float)pushBGTopHack;
                if (bgTexIndexes[1] == 329)
                {
                    this.bgTopY = backgroundTopMagicNumber * 1900f + 1600f + this.scAdj + (float)pushBGTopHack;
                }
                if (bgTexIndexes[1] == 334)
                {
                    this.bgTopY = backgroundTopMagicNumber * 1900f + 1650f + this.scAdj + (float)pushBGTopHack;
                }
                if (bgTexIndexes[1] == 334)
                {
                    this.bgTopY = backgroundTopMagicNumber * 1900f + 1650f + this.scAdj + (float)pushBGTopHack;
                }
                if (Main.gameMenu)
                {
                    this.bgTopY = (float)(400 + pushBGTopHack);
                    this.bgStartX -= 80;
                }
                if (bgTexIndexes[1] == 51)
                {
                    this.bgTopY -= 50f;
                }
                if (bgTexIndexes[1] == 54)
                {
                    this.bgTopY -= 100f;
                }
                if (bgTexIndexes[1] == 329)
                {
                    this.bgTopY -= 150f;
                }
                if (bgTexIndexes[1] == 334)
                {
                    this.bgTopY -= 150f;
                }
                if (bgTexIndexes[1] == 342)
                {
                    this.bgTopY -= 300f;
                }
                this.bgLoops = Main.screenWidth / Main.bgWidthScaled + 2;
                if ((double)Main.screenPosition.Y < Main.worldSurface * 16.0 + 16.0)
                {
                    SpriteEffects spriteEffects = ((bgTexIndexes[1] == 51 || bgTexIndexes[1] == 54) ? SpriteEffects.FlipHorizontally : SpriteEffects.None);
                    for (int j = 0; j < this.bgLoops; j++)
                    {
                        Main.spriteBatch.Draw(TextureAssets.Background[bgTexIndexes[1]].Value, new Vector2((float)(this.bgStartX + Main.bgWidthScaled * j), this.bgTopY), this.GetBackgroundRect(bgTexIndexes[1]), Main.ColorOfSurfaceBackgroundsModified, 0f, default(Vector2), Main.bgScale, spriteEffects, 0f);
                    }
                }
            }
            if (bgTexIndexes[2] >= 0)
            {
                this.LoadBackground(bgTexIndexes[2]);
                Main.bgScale = 1.34f;
                Main.bgScale *= bgGlobalScaleMultiplier;
                this.bgParallax = 0.49;
                this.SetBackgroundOffsets(bgTexIndexes[2], backgroundTopMagicNumber, pushBGTopHack);
                SkyManager.Instance.DrawToDepth(Main.spriteBatch, 1f / (float)this.bgParallax);
                if (bgTexIndexes[0] == 91)
                {
                    Main.bgScale = 1.3f;
                    Main.bgScale *= bgGlobalScaleMultiplier;
                    this.bgParallax = 0.42;
                }
                if (bgTexIndexes[2] < 0)
                {
                    return;
                }
                Main.bgWidthScaled = (int)((float)Main.backgroundWidth[bgTexIndexes[2]] * Main.bgScale);
                if (Main.bgWidthScaled == 0)
                {
                    Main.bgWidthScaled = 1;
                }
                this.bgStartX = (int)(-Math.IEEERemainder((double)Main.screenPosition.X * this.bgParallax, (double)Main.bgWidthScaled) - (double)(Main.bgWidthScaled / 2));
                this.bgTopY = backgroundTopMagicNumber * 2100f + 2000f + this.scAdj + (float)pushBGTopHack;
                if (bgTexIndexes[2] == 328)
                {
                    this.bgTopY = backgroundTopMagicNumber * 2600f + 2300f + this.scAdj + (float)pushBGTopHack;
                }
                if (bgTexIndexes[2] == 333)
                {
                    this.bgTopY = backgroundTopMagicNumber * 2800f + 2550f + this.scAdj + (float)pushBGTopHack;
                }
                if (Main.gameMenu)
                {
                    this.bgTopY = (float)(480 + pushBGTopHack);
                    this.bgStartX -= 120;
                }
                if (bgTexIndexes[2] == 52)
                {
                    this.bgTopY -= 50f;
                }
                if (bgTexIndexes[2] == 55)
                {
                    this.bgTopY -= 100f;
                }
                if (bgTexIndexes[2] == 92)
                {
                    this.bgTopY += 150f;
                }
                if (bgTexIndexes[2] == 328)
                {
                    this.bgTopY -= 150f;
                }
                if (bgTexIndexes[2] == 333)
                {
                    this.bgTopY -= 150f;
                }
                if (bgTexIndexes[2] == 341)
                {
                    this.bgTopY -= 50f;
                }
                this.bgLoops = Main.screenWidth / Main.bgWidthScaled + 2;
                if ((double)Main.screenPosition.Y < Main.worldSurface * 16.0 + 16.0)
                {
                    for (int k = 0; k < this.bgLoops; k++)
                    {
                        Main.spriteBatch.Draw(TextureAssets.Background[bgTexIndexes[2]].Value, new Vector2((float)(this.bgStartX + Main.bgWidthScaled * k), this.bgTopY), this.GetBackgroundRect(bgTexIndexes[2]), Main.ColorOfSurfaceBackgroundsModified, 0f, default(Vector2), Main.bgScale, SpriteEffects.None, 0f);
                    }
                }
            }
        }
References Terraria.GameContent.TextureAssets.Background, Terraria.Main.backgroundWidth, Terraria.Main.bgScale, Terraria.Main.bgWidthScaled, Terraria.Main.ColorOfSurfaceBackgroundsModified, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Graphics.Effects.SkyManager.DrawToDepth(), Terraria.Main.gameMenu, System.Math.IEEERemainder(), Terraria.Graphics.Effects.SkyManager.Instance, int, Terraria.Main.spriteBatch, Microsoft.Xna.Framework.Input.U, and ReLogic.Content.Asset< T >.Value.