Terraria Decompiled: Terraria.Main.DrawNPCHousesInUI
DrawNPCHousesInUI()
void Terraria.Main.DrawNPCHousesInUI (int inventoryTop) inline private
Definition at line 41938 of file Main.cs.
        {
            if (Main.mouseX > Main.screenWidth - 64 - 28 && Main.mouseX < (int)((float)(Main.screenWidth - 64 - 28) + 56f * Main.inventoryScale) && Main.mouseY > inventoryTop && Main.mouseY < (int)((float)inventoryTop + 448f * Main.inventoryScale) && !PlayerInput.IgnoreMouseInterface)
            {
                Main.player[Main.myPlayer].mouseInterface = true;
            }
            int num = 0;
            string text = "";
            int num2 = 0;
            int num3 = 0;
            this._npcTypesThatAlreadyDrewAHead.Clear();
            for (int i = 0; i < this._npcIndexWhoHoldsHeadIndex.Length; i++)
            {
                this._npcIndexWhoHoldsHeadIndex[i] = -1;
            }
            for (int j = 0; j < Main.maxNPCs; j++)
            {
                if (Main.npc[j].active && !this._npcTypesThatAlreadyDrewAHead.Contains(Main.npc[j].type))
                {
                    int headIndexSafe = TownNPCProfiles.GetHeadIndexSafe(Main.npc[j]);
                    if (headIndexSafe > 0 && headIndexSafe <= NPCHeadID.Count && !NPCHeadID.Sets.CannotBeDrawnInHousingUI[headIndexSafe] && this._npcIndexWhoHoldsHeadIndex[headIndexSafe] == -1)
                    {
                        this._npcIndexWhoHoldsHeadIndex[headIndexSafe] = j;
                        this._npcTypesThatAlreadyDrewAHead.Add(Main.npc[j].type);
                    }
                }
            }
            Main.hidePVPAndTeamIcons = false;
            int num4 = 0;
            int num5 = 0;
            UILinkPointNavigator.Shortcuts.NPCS_IconsPerColumn = 1;
            UILinkPointNavigator.Shortcuts.NPCS_SelectedNPC = -2;
            Vector2 vector = TextureAssets.InventoryBack.Size();
            foreach (int num6 in NPCHeadID.Sets.HeadListOrder)
            {
                if (num6 == 0 || this._npcIndexWhoHoldsHeadIndex[num6] != -1)
                {
                    int num7 = this._npcIndexWhoHoldsHeadIndex[num6];
                    int num8 = Main.screenWidth - 64 - 28 + num3;
                    int num9 = (int)((float)inventoryTop + (float)(num * 56) * Main.inventoryScale) + num2;
                    Microsoft.Xna.Framework.Color white = new Microsoft.Xna.Framework.Color(100, 100, 100, 100);
                    if (num9 > Main.screenHeight - 80)
                    {
                        num3 -= 48;
                        num2 -= num9 - inventoryTop;
                        num8 = Main.screenWidth - 64 - 28 + num3;
                        num9 = (int)((float)inventoryTop + (float)(num * 56) * Main.inventoryScale) + num2;
                        UILinkPointNavigator.Shortcuts.NPCS_IconsPerColumn = num5;
                        if (num3 <= -144)
{
                            Main.hidePVPAndTeamIcons = true;
                        }
                        num5 = 0;
                    }
                    if (Main.mouseX >= num8 && (float)Main.mouseX <= (float)num8 + (float)((int)vector.X) * Main.inventoryScale && Main.mouseY >= num9 && (float)Main.mouseY <= (float)num9 + (float)((int)vector.Y) * Main.inventoryScale)
                    {
                        Main.mouseText = true;
                        if (num6 == 0)
{
                            text = Lang.inter[8].Value;
                        }
                        else
{
                            text = Main.npc[num7].FullName;
                        }
                        UILinkPointNavigator.Shortcuts.NPCS_SelectedNPC = num7;
                        if (!PlayerInput.IgnoreMouseInterface)
{
                            Main.player[Main.myPlayer].mouseInterface = true;
                            if (Main.mouseLeftRelease && Main.mouseLeft && !PlayerInput.UsingGamepadUI && Main.mouseItem.type == 0)
{
                                SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                                if (num6 == 0)
{
                                    this.SetMouseNPC_ToHousingQuery();
                                }
                                else
{
                                    this.SetMouseNPC(num7, Main.npc[num7].type);
                                }
                                Main.mouseLeftRelease = false;
                            }
                        }
                    }
                    UILinkPointNavigator.SetPosition(600 + num, new Vector2((float)num8, (float)num9) + vector * 0.75f);
                    Texture2D texture2D = TextureAssets.InventoryBack11.Value;
                    Microsoft.Xna.Framework.Color white2 = Main.inventoryBack;
                    if (UILinkPointNavigator.CurrentPoint - 600 == num)
                    {
                        texture2D = TextureAssets.InventoryBack14.Value;
                        white2 = Microsoft.Xna.Framework.Color.White;
                    }
                    Main.spriteBatch.Draw(texture2D, new Vector2((float)num8, (float)num9), null, white2, 0f, default(Vector2), Main.inventoryScale, SpriteEffects.None, 0f);
                    white = Microsoft.Xna.Framework.Color.White;
                    Texture2D value = TextureAssets.NpcHead[num6].Value;
                    Vector2 vector2 = value.Size();
                    float num10 = 1f;
                    float num11 = Math.Max(vector2.X, vector2.Y);
                    if (num11 > 36f)
                    {
                        num10 = 36f / num11;
                    }
                    Main.spriteBatch.Draw(value, new Vector2((float)num8 + 26f * Main.inventoryScale, (float)num9 + 26f * Main.inventoryScale), null, white, 0f, vector2 / 2f, num10, SpriteEffects.None, 0f);
                    num++;
                    num4++;
                    num5++;
                }
            }
            if (UILinkPointNavigator.Shortcuts.NPCS_IconsPerColumn < num5)
            {
                UILinkPointNavigator.Shortcuts.NPCS_IconsPerColumn = num5;
            }
            UILinkPointNavigator.Shortcuts.NPCS_IconsTotal = num4;
            if (text != "" && Main.mouseItem.type == 0)
            {
                this.MouseText(text, 0, 0, -1, -1, -1, -1, 0);
            }
            PlayerInput.UpdateHousingCursor();
        }
References Terraria.NPC.active, Terraria.ID.NPCHeadID.Sets.CannotBeDrawnInHousingUI, Terraria.ID.NPCHeadID.Count, Terraria.UI.Gamepad.UILinkPointNavigator.CurrentPoint, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.NPC.FullName, Terraria.GameContent.TownNPCProfiles.GetHeadIndexSafe(), Terraria.ID.NPCHeadID.Sets.HeadListOrder, Terraria.GameInput.PlayerInput.IgnoreMouseInterface, int, Terraria.Lang.inter, Terraria.GameContent.TextureAssets.InventoryBack, Terraria.Main.inventoryBack, Terraria.GameContent.TextureAssets.InventoryBack11, Terraria.GameContent.TextureAssets.InventoryBack14, Terraria.Main.inventoryScale, System.Math.Max(), Terraria.Main.maxNPCs, Terraria.Player.mouseInterface, Terraria.Main.mouseItem, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Main.npc, Terraria.GameContent.TextureAssets.NpcHead, Terraria.UI.Gamepad.UILinkPointNavigator.Shortcuts.NPCS_IconsPerColumn, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.screenHeight, Terraria.Main.screenWidth, Terraria.UI.Gamepad.UILinkPointNavigator.SetPosition(), Terraria.Main.spriteBatch, System.text, Terraria.Item.type, Terraria.NPC.type, Terraria.GameInput.PlayerInput.UpdateHousingCursor(), Terraria.GameInput.PlayerInput.UsingGamepadUI, System.value, ReLogic.Content.Asset< T >.Value, Terraria.Localization.LocalizedText.Value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.