Terraria Decompiled: Terraria.Main.LoadMusic_InSteps
LoadMusic_InSteps()
IEnumerator Terraria.Main.LoadMusic_InSteps () inline private
Definition at line 9005 of file Main.cs.
        {
            IEnumerator sub = Main.audioSystem.PrepareWaveBank();
            while (sub.MoveNext())
            {
                object obj = sub.Current;
                yield return obj;
            }
            for (int i = 1; i < Main.maxMusic; i++)
            {
                Main.audioSystem.LoadCue(i, "Music_" + i);
            }
            Main.audioSystem.LoadFromSources();
            yield break;
        }
References Terraria.Main.audioSystem, System.Collections.Generic.IEnumerator< out T >.Current, Terraria.Audio.IAudioSystem.LoadCue(), Terraria.Audio.IAudioSystem.LoadFromSources(), Terraria.Main.maxMusic, System.Collections.IEnumerator.MoveNext(), System.obj, and Terraria.Audio.IAudioSystem.PrepareWaveBank().