Terraria Decompiled: Terraria.Main.SetIMEPanelAnchor
SetIMEPanelAnchor()
void Terraria.Main.SetIMEPanelAnchor (Vector2 position, float xAnchor) inline
Definition at line 40664 of file Main.cs.
        {
            Main.imePanelAnchor = new Main.IMEPanelAnchor?(new Main.IMEPanelAnchor
            {
                Position = position,
                XAnchor = xAnchor
            });
        }
References Microsoft.Xna.Framework.Graphics.Position.
Referenced by Terraria.UI.ChestUI.DrawName(), Terraria.GameContent.UI.Elements.UISearchBar.DrawSelf(), Terraria.GameContent.UI.States.UIVirtualKeyboard.DrawSelf(), and Terraria.GameContent.UI.NPCChatPanel.DrawText().