Terraria Decompiled: Terraria.Main.DrawWithOutlines
DrawWithOutlines()
static void Terraria.Main.DrawWithOutlines (Entity entity, Texture2D tex, Vector2 position, Microsoft::Xna::Framework::Rectangle? rect, Microsoft::Xna::Framework::Color color, float rotation, Vector2 origin, float scale, SpriteEffects effects) inline static private
Definition at line 57375 of file Main.cs.
        {
            float num = 2f * scale;
            Microsoft.Xna.Framework.Color white = Microsoft.Xna.Framework.Color.White;
            int colorOnlyShaderIndex = ContentSamples.DyeShaderIDs.ColorOnlyShaderIndex;
            DrawData drawData = new DrawData(tex, position, rect, color, rotation, origin, scale, effects, 0f);
            GameShaders.Armor.Apply(colorOnlyShaderIndex, entity, new DrawData?(drawData));
            Microsoft.Xna.Framework.Color color2 = Microsoft.Xna.Framework.Color.Black;
            color2 *= (float)color.A / 255f;
            color2 *= (float)color.A / 255f;
            Microsoft.Xna.Framework.Color color3 = white;
            color3 *= (float)color.A / 255f;
            color3 *= (float)color.A / 255f;
            int num2 = 2;
            Vector2 vector;
            for (int i = -num2; i <= num2; i++)
            {
                for (int j = -num2; j <= num2; j++)
                {
                    if (Math.Abs(i) + Math.Abs(j) == num2)
                    {
                        vector = new Vector2((float)i * num, (float)j * num).RotatedBy((double)rotation, default(Vector2));
                        Main.spriteBatch.Draw(tex, position + vector, rect, color2, rotation, origin, scale, effects, 0f);
                    }
                }
            }
            num2 = 1;
            vector = Vector2.Zero;
            for (int k = -num2; k <= num2; k++)
            {
                for (int l = -num2; l <= num2; l++)
                {
                    if (Math.Abs(k) + Math.Abs(l) == num2)
                    {
                        vector = new Vector2((float)k * num, (float)l * num).RotatedBy((double)rotation, default(Vector2));
                        Main.spriteBatch.Draw(tex, position + vector, rect, color3, rotation, origin, scale, effects, 0f);
                    }
                }
            }
            Main.pixelShader.CurrentTechnique.Passes[0].Apply();
            Main.spriteBatch.Draw(tex, position, rect, color, rotation, origin, scale, effects, 0f);
        }
References Microsoft.Xna.Framework.Color.A, System.Math.Abs(), Terraria.Graphics.Shaders.ArmorShaderDataSet.Apply(), Terraria.Graphics.Shaders.GameShaders.Armor, Microsoft.Xna.Framework.Color.Black, Terraria.ID.ContentSamples.DyeShaderIDs.ColorOnlyShaderIndex, Microsoft.Xna.Framework.Graphics.Effect.CurrentTechnique, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.EffectTechnique.Passes, Terraria.Main.pixelShader, Terraria.Main.spriteBatch, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Color.White, and Microsoft.Xna.Framework.Vector2.Zero.