Terraria Decompiled: Terraria.Main.DrawProj_FairyQueenRangedItemShot
DrawProj_FairyQueenRangedItemShot()
void Terraria.Main.DrawProj_FairyQueenRangedItemShot (Projectile proj) inline private
Definition at line 35237 of file Main.cs.
        {
            Vector2 vector = proj.Center - Main.screenPosition;
            Microsoft.Xna.Framework.Color fairyQueenWeaponsColor = proj.GetFairyQueenWeaponsColor(0f, 0f, null);
            Microsoft.Xna.Framework.Color fairyQueenWeaponsColor2 = proj.GetFairyQueenWeaponsColor(0.5f, 0f, null);
            Texture2D value = TextureAssets.Projectile[proj.type].Value;
            Vector2 vector2 = value.Frame(1, 1, 0, 0, 0, 0).Size() / 2f;
            Microsoft.Xna.Framework.Color color = Microsoft.Xna.Framework.Color.White * proj.Opacity;
            color.A /= 2;
            float num = MathHelper.Lerp(0.7f, 1f, Utils.GetLerpValue(0f, 5f, proj.ai[0], true));
            float opacity = proj.Opacity;
            if (opacity > 0f)
            {
                float lerpValue = Utils.GetLerpValue(0f, 1f, proj.velocity.Length(), true);
                for (float num2 = 0f; num2 < 1f; num2 += 0.16666667f)
                {
                    Vector2 vector3 = proj.rotation.ToRotationVector2() * -120f * num2 * lerpValue;
                    Main.spriteBatch.Draw(value, vector + vector3, null, fairyQueenWeaponsColor * opacity * (1f - num2), proj.rotation, vector2, num, SpriteEffects.None, 0f);
                }
                for (float num3 = 0f; num3 < 1f; num3 += 0.25f)
                {
                    Vector2 vector4 = (num3 * 6.2831855f + proj.rotation).ToRotationVector2() * 4f * num;
                    Main.spriteBatch.Draw(value, vector + vector4, null, fairyQueenWeaponsColor2 * opacity, proj.rotation, vector2, num, SpriteEffects.None, 0f);
                }
            }
            Main.spriteBatch.Draw(value, vector, null, color, proj.rotation, vector2, num, SpriteEffects.None, 0f);
        }
References Terraria.Projectile.ai, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Projectile.GetFairyQueenWeaponsColor(), Terraria.Utils.GetLerpValue(), Microsoft.Xna.Framework.Vector2.Length(), Microsoft.Xna.Framework.MathHelper.Lerp(), Terraria.Projectile.Opacity, Terraria.GameContent.TextureAssets.Projectile, Terraria.Projectile.rotation, Terraria.Main.screenPosition, Terraria.Main.spriteBatch, Terraria.Projectile.type, System.value, ReLogic.Content.Asset< T >.Value, and Terraria.Entity.velocity.