Terraria Decompiled: Terraria.Main.StartSlimeRain
StartSlimeRain()
static void Terraria.Main.StartSlimeRain (bool announce = true) inline static
Definition at line 66056 of file Main.cs.
        {
            if (Main.remixWorld)
            {
                return;
            }
            if (!Main.isThereAWorldSurface)
            {
                return;
            }
            if (Main.slimeRain)
            {
                return;
            }
            if (Main.netMode == 1)
            {
                if (announce)
                {
                    NetMessage.SendData(61, -1, -1, null, Main.myPlayer, -19f, 0f, 0f, 0, 0, 0);
                    return;
                }
                Main.slimeRainTime = 54000.0;
                Main.slimeRain = true;
                SkyManager.Instance.Activate("Slime", default(Vector2), new object[0]);
                return;
            }
            else
            {
                if (Main.raining)
                {
                    return;
                }
                if (Main.slimeRainTime <= 0.0)
                {
                    Main.slimeRainTime = (double)Main.rand.Next(32400, 54000);
                }
                Main.slimeRain = true;
                Main.slimeRainKillCount = 0;
                if (Main.netMode == 0)
                {
                    SkyManager.Instance.Activate("Slime", default(Vector2), new object[0]);
                    if (announce)
                    {
                        Main.slimeWarningTime = Main.slimeWarningDelay;
                        return;
                    }
                }
                else if (announce)
                {
                    Main.slimeWarningTime = Main.slimeWarningDelay;
                    NetMessage.SendData(7, -1, -1, null, 0, 0f, 0f, 0f, 0, 0, 0);
                }
                return;
            }
        }
References Terraria.Graphics.Effects.EffectManager< T >.Activate(), Terraria.Graphics.Effects.SkyManager.Instance, Terraria.Main.isThereAWorldSurface, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.raining, Terraria.Main.rand, Terraria.Main.remixWorld, Terraria.NetMessage.SendData(), Terraria.Main.slimeRain, Terraria.Main.slimeRainTime, and Terraria.Main.slimeWarningDelay.
Referenced by Terraria.MessageBuffer.GetData(), Terraria.WorldItem.GetShimmered(), Terraria.IO.WorldFile.LoadWorld(), and Terraria.Main.UpdateTime().