Terraria Decompiled: Terraria.Main.NewLightning
NewLightning()
static void Terraria.Main.NewLightning (bool instant = false, bool skipSound = false) inline static
Definition at line 59484 of file Main.cs.
        {
            if (!Main.FlashyEffectsWorld || Main.shimmerAlpha > 0f)
            {
                return;
            }
            if (Main.rand.Next(3) == 0)
            {
                Main.thunderDelay = Main.rand.Next(1, 31);
            }
            else if (Main.rand.Next(2) == 0)
            {
                Main.thunderDelay = Main.rand.Next(31, 121);
            }
            else
            {
                Main.thunderDelay = Main.rand.Next(11, 61);
            }
            Main.thunderDistance = Main.thunderDelay;
            Main.lightningDecay = Main.rand.NextFloat() * 0.05f + 0.008f;
            Main.lightningSpeed = Main.rand.NextFloat() * 0.05f + 0.05f;
            Main.thunderSkipSound = skipSound;
            if (instant)
            {
                Main.lightningSpeed = 0.2f;
                Main.thunderDelay = 1;
                Main.thunderDistance = 0;
            }
        }
References Terraria.Main.FlashyEffectsWorld, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, Terraria.Main.shimmerAlpha, and Terraria.Main.thunderDelay.
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_StormLightning(), and Terraria.Main.UpdateWeather().