Terraria Decompiled: Terraria.Main.DrawInterface_Resources_Buffs
DrawInterface_Resources_Buffs()
void Terraria.Main.DrawInterface_Resources_Buffs () inline
Definition at line 43202 of file Main.cs.
        {
            Main.PipsUseGrid = false;
            int num = -1;
            int num2 = 11;
            int num3 = 0;
            for (int i = 0; i < Player.maxBuffs; i++)
            {
                if (Main.player[Main.myPlayer].buffType[i] > 0)
                {
                    int num4 = Main.player[Main.myPlayer].buffType[i];
                    int num5 = 32 + num3 * 38;
                    int num6 = 76;
                    int j = num3;
                    while (j >= num2)
                    {
                        j -= num2;
                        num5 = 32 + j * 38;
                        num6 += 50;
                    }
                    num = Main.DrawBuffIcon(num, i, num5, num6);
                    num3++;
                }
                else
                {
                    Main.buffAlpha[i] = 0.4f;
                }
            }
            if (num >= 0)
            {
                int num7 = Main.player[Main.myPlayer].buffType[num];
                if (num7 > 0)
                {
                    string buffName = Lang.GetBuffName(num7);
                    string buffTooltip = Main.GetBuffTooltip(Main.player[Main.myPlayer], num7);
                    if (num7 == 147)
                    {
                        Main.bannerMouseOver = true;
                    }
                    if (Main.meleeBuff[num7])
                    {
                        this.MouseTextHackZoom(buffName, -10, 0, buffTooltip);
                        return;
                    }
                    this.MouseTextHackZoom(buffName, buffTooltip);
                }
            }
        }
References Terraria.Main.buffAlpha, Terraria.Player.buffType, Terraria.Main.DrawBuffIcon(), Terraria.Lang.GetBuffName(), Terraria.Main.GetBuffTooltip(), Terraria.Player.maxBuffs, Terraria.Main.meleeBuff, Terraria.Main.myPlayer, and Terraria.Main.player.