Terraria Decompiled: Terraria.Main.ClearVisualPostProcessEffects
ClearVisualPostProcessEffects()
static void Terraria.Main.ClearVisualPostProcessEffects () inline static
Definition at line 52670 of file Main.cs.
        {
            for (int i = 0; i < 13; i++)
            {
                string text = "";
                switch (i)
                {
                case 0:
                    text = "Solar";
                    break;
                case 1:
                    text = "Vortex";
                    break;
                case 2:
                    text = "Nebula";
                    break;
                case 3:
                    text = "Stardust";
                    break;
                case 4:
                    text = "MoonLord";
                    break;
                case 5:
                    text = "MonolithSolar";
                    break;
                case 6:
                    text = "MonolithVortex";
                    break;
                case 7:
                    text = "MonolithNebula";
                    break;
                case 8:
                    text = "MonolithStardust";
                    break;
                case 9:
                    text = "Blizzard";
                    break;
                case 10:
                    text = "HeatDistortion";
                    break;
                case 11:
                    text = "Sandstorm";
                    break;
                case 12:
                    text = "MonolithMoonLord";
                    break;
                }
                if (SkyManager.Instance[text] != null && SkyManager.Instance[text].IsActive())
                {
                    SkyManager.Instance[text].Deactivate(new object[0]);
                }
                if (Overlays.Scene[text] != null && Overlays.Scene[text].IsVisible())
                {
                    Overlays.Scene[text].Deactivate(new object[0]);
                }
                if (Terraria.Graphics.Effects.Filters.Scene[text] != null && Terraria.Graphics.Effects.Filters.Scene[text].IsActive())
                {
                    Terraria.Graphics.Effects.Filters.Scene[text].Deactivate(new object[0]);
                }
            }
            if (Terraria.Graphics.Effects.Filters.Scene["BloodMoon"].IsActive())
            {
                Terraria.Graphics.Effects.Filters.Scene["BloodMoon"].Deactivate(new object[0]);
            }
            if (Terraria.Graphics.Effects.Filters.Scene["Graveyard"].IsActive())
            {
                Terraria.Graphics.Effects.Filters.Scene["Graveyard"].Deactivate(new object[0]);
            }
            if (Terraria.Graphics.Effects.Filters.Scene["Sepia"].IsActive())
            {
                Terraria.Graphics.Effects.Filters.Scene["Sepia"].Deactivate(new object[0]);
            }
            if (Terraria.Graphics.Effects.Filters.Scene["Noir"].IsActive())
            {
                Terraria.Graphics.Effects.Filters.Scene["Noir"].Deactivate(new object[0]);
            }
            if (Terraria.Graphics.Effects.Filters.Scene["BloodMoon"].IsActive())
            {
                Terraria.Graphics.Effects.Filters.Scene["BloodMoon"].Deactivate(new object[0]);
            }
            if (Terraria.Graphics.Effects.Filters.Scene["MoonLordShake"].IsActive())
            {
                Terraria.Graphics.Effects.Filters.Scene["MoonLordShake"].Deactivate(new object[0]);
            }
            if (Terraria.Graphics.Effects.Filters.Scene["WaterDistortion"].IsActive())
            {
                Terraria.Graphics.Effects.Filters.Scene["WaterDistortion"].Deactivate(new object[0]);
            }
            if (Terraria.Graphics.Effects.Filters.Scene["CRT"].IsActive())
            {
                Terraria.Graphics.Effects.Filters.Scene["CRT"].Deactivate(new object[0]);
            }
            if (Terraria.Graphics.Effects.Filters.Scene["Test2"].IsActive())
            {
                Terraria.Graphics.Effects.Filters.Scene["Test2"].Deactivate(new object[0]);
            }
            if (SkyManager.Instance["Martian"].IsActive())
            {
                SkyManager.Instance["Martian"].Deactivate(new object[0]);
            }
            if (SkyManager.Instance["Party"].IsActive())
            {
                SkyManager.Instance["Party"].Deactivate(new object[0]);
            }
            if (SkyManager.Instance["Slime"].IsActive())
            {
                SkyManager.Instance["Slime"].Deactivate(new object[0]);
            }
            if (SkyManager.Instance["Ambience"].IsActive())
            {
                SkyManager.Instance["Ambience"].Deactivate(new object[0]);
            }
            if (SkyManager.Instance["Aurora"].IsActive())
            {
                SkyManager.Instance["Aurora"].Deactivate(new object[0]);
            }
            Main.slimeRain = false;
            Main.slimeRainTime = 0.0;
            Main.slimeWarningTime = 0;
            BirthdayParty.WorldClear();
            LanternNight.WorldClear();
            Sandstorm.WorldClear();
            CreditsRollEvent.Reset();
            Main.maxRaining = 0f;
            Main.raining = false;
            Main.ClearWorldSeedFlags();
        }
References Terraria.Main.ClearWorldSeedFlags(), Terraria.Graphics.Effects.EffectManager< T >.Deactivate(), Terraria.Graphics.Effects.SkyManager.Instance, Terraria.GameContent.Events.CreditsRollEvent.Reset(), Terraria.Graphics.Effects.Filters.Scene, Terraria.Graphics.Effects.Overlays.Scene, System.text, Terraria.GameContent.Events.BirthdayParty.WorldClear(), Terraria.GameContent.Events.LanternNight.WorldClear(), and Terraria.GameContent.Events.Sandstorm.WorldClear().
Referenced by Terraria.Main.DrawMenu(), Terraria.WorldGen.JustQuit(), and Terraria.WorldGen.SaveAndQuitCallBack().