Terraria Decompiled: Terraria.Main.DrawNPCMapIcons2
DrawNPCMapIcons2()
static string Terraria.Main.DrawNPCMapIcons2 (string mouseTextString, float X2, float Y2, float scale, byte alpha, float xOff, float yOff, float left, float top, float headScale) inline static private
Definition at line 56833 of file Main.cs.
        {
            for (int i = 0; i < Main.maxNPCs; i++)
            {
                if (Main.npc[i].active && Main.npc[i].townNPC && Main.DrawNPCMapIcon_CanBeSeen_Townie(Main.npc[i]))
                {
                    int headIndexSafe = TownNPCProfiles.GetHeadIndexSafe(Main.npc[i]);
                    if (headIndexSafe > 0)
                    {
                        SpriteEffects spriteEffects = SpriteEffects.None;
                        if (Main.npc[i].direction > 0)
{
                            spriteEffects = SpriteEffects.FlipHorizontally;
                        }
                        Vector2 vector = Main.npc[i].Center + new Vector2(0f, Main.npc[i].gfxOffY) + Main.npc[i].netOffset;
                        float num = (vector.X / 16f - left) * scale;
                        float num2 = (vector.Y / 16f - top) * scale;
                        num += X2;
                        num2 += Y2;
                        num2 -= 2f * scale / 5f;
                        num += xOff;
                        num2 += yOff;
                        if (num > (float)(Main.miniMapX + 12) && num < (float)(Main.miniMapX + Main.miniMapWidth - 16) && num2 > (float)(Main.miniMapY + 10) && num2 < (float)(Main.miniMapY + Main.miniMapHeight - 14))
{
                            float num3 = num - (float)(TextureAssets.NpcHead[headIndexSafe].Width() / 2) * headScale;
                            float num4 = num2 - (float)(TextureAssets.NpcHead[headIndexSafe].Height() / 2) * headScale;
                            float num5 = num3 + (float)TextureAssets.NpcHead[headIndexSafe].Width() * headScale;
                            float num6 = num4 + (float)TextureAssets.NpcHead[headIndexSafe].Height() * headScale;
                            if ((float)Main.mouseX >= num3 && (float)Main.mouseX <= num5 && (float)Main.mouseY >= num4 && (float)Main.mouseY <= num6)
{
                                mouseTextString = Main.npc[i].FullName;
                            }
                            Main.DrawNPCHeadFriendly(Main.npc[i], alpha, headScale, spriteEffects, headIndexSafe, num, num2);
                        }
                    }
                }
                if (Main.npc[i].active && Main.npc[i].GetBossHeadTextureIndex() != -1)
                {
                    float bossHeadRotation = Main.npc[i].GetBossHeadRotation();
                    SpriteEffects bossHeadSpriteEffects = Main.npc[i].GetBossHeadSpriteEffects();
                    Vector2 vector2 = Main.npc[i].Center + new Vector2(0f, Main.npc[i].gfxOffY) + Main.npc[i].netOffset;
                    if (Main.npc[i].type == 134)
                    {
                        Vector2 vector3 = Main.npc[i].Center;
                        int num7 = 1;
                        int num8 = (int)Main.npc[i].ai[0];
                        while (num7 < 15 && Main.npc[num8].active && Main.npc[num8].type >= 134 && Main.npc[num8].type <= 136)
{
                            num7++;
                            vector3 += Main.npc[num8].Center;
                            num8 = (int)Main.npc[num8].ai[0];
                        }
                        vector3 /= (float)num7;
                        vector2 = vector3;
                    }
                    int bossHeadTextureIndex = Main.npc[i].GetBossHeadTextureIndex();
                    float num9 = (vector2.X / 16f - left) * scale;
                    float num10 = (vector2.Y / 16f - top) * scale;
                    num9 += X2;
                    num10 += Y2;
                    num10 -= 2f * scale / 5f;
                    num9 += xOff;
                    num10 += yOff;
                    if (num9 > (float)(Main.miniMapX + 12) && num9 < (float)(Main.miniMapX + Main.miniMapWidth - 16) && num10 > (float)(Main.miniMapY + 10) && num10 < (float)(Main.miniMapY + Main.miniMapHeight - 14))
                    {
                        float num11 = num9 - (float)(TextureAssets.NpcHeadBoss[bossHeadTextureIndex].Width() / 2) * headScale;
                        float num12 = num10 - (float)(TextureAssets.NpcHeadBoss[bossHeadTextureIndex].Height() / 2) * headScale;
                        float num13 = num11 + (float)TextureAssets.NpcHeadBoss[bossHeadTextureIndex].Width() * headScale;
                        float num14 = num12 + (float)TextureAssets.NpcHeadBoss[bossHeadTextureIndex].Height() * headScale;
                        if ((float)Main.mouseX >= num11 && (float)Main.mouseX <= num13 && (float)Main.mouseY >= num12 && (float)Main.mouseY <= num14)
{
                            mouseTextString = Main.npc[i].GivenOrTypeName;
                        }
                        Main.DrawNPCHeadBoss(Main.npc[i], alpha, headScale, bossHeadRotation, bossHeadSpriteEffects, bossHeadTextureIndex, num9, num10);
                    }
                }
            }
            return mouseTextString;
        }
References Terraria.NPC.active, Terraria.NPC.ai, Terraria.Entity.Center, Terraria.Entity.direction, Terraria.Main.DrawNPCHeadBoss(), Terraria.Main.DrawNPCHeadFriendly(), Terraria.Main.DrawNPCMapIcon_CanBeSeen_Townie(), Terraria.NPC.FullName, Terraria.NPC.GetBossHeadRotation(), Terraria.NPC.GetBossHeadSpriteEffects(), Terraria.NPC.GetBossHeadTextureIndex(), Terraria.GameContent.TownNPCProfiles.GetHeadIndexSafe(), Terraria.NPC.gfxOffY, Terraria.NPC.GivenOrTypeName, int, Terraria.Main.maxNPCs, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.NPC.netOffset, Terraria.Main.npc, Terraria.GameContent.TextureAssets.NpcHead, Terraria.GameContent.TextureAssets.NpcHeadBoss, Terraria.NPC.townNPC, Terraria.NPC.type, and Microsoft.Xna.Framework.Graphics.Vector2.
Referenced by Terraria.Main.DrawMap().