Terraria Decompiled: Terraria.Main.DamageVar
DamageVar()
static int Terraria.Main.DamageVar (float dmg, float luck = 0f) inline static
Definition at line 67466 of file Main.cs.
        {
            if (DebugOptions.NoDamageVar)
            {
                return (int)dmg;
            }
            float num = dmg * (1f + (float)Main.rand.Next(-15, 16) * 0.01f);
            if (luck > 0f)
            {
                if (Main.rand.NextFloat() < luck)
                {
                    float num2 = dmg * (1f + (float)Main.rand.Next(-15, 16) * 0.01f);
                    if (num2 > num)
                    {
                        num = num2;
                    }
                }
            }
            else if (luck < 0f && Main.rand.NextFloat() < -luck)
            {
                float num3 = dmg * (1f + (float)Main.rand.Next(-15, 16) * 0.01f);
                if (num3 < num)
                {
                    num = num3;
                }
            }
            return (int)Math.Round((double)num);
        }
References Terraria.Utilities.UnifiedRandom.Next(), Terraria.Testing.DebugOptions.NoDamageVar, Terraria.Main.rand, and System.Math.Round().
Referenced by Terraria.Player.ApplyTouchDamage(), Terraria.NPC.BeHurtByOtherNPC(), Terraria.Projectile.BombsHurtPlayers(), Terraria.Projectile.Damage_EVP(), Terraria.Projectile.Damage_PVE_Inner(), Terraria.Projectile.Damage_PVP(), Terraria.Player.GetMinecartDamage(), Terraria.Player.ItemCheck_MeleeHitPVP(), Terraria.Player.ItemCheck_UseMiningTools_ActuallyUseMiningTool(), Terraria.Player.ProcessHitAgainstNPC(), and Terraria.Player.Update_NPCCollision().