Terraria Decompiled: Terraria.Main.DrawNPCHousesInWorld
DrawNPCHousesInWorld()
void Terraria.Main.DrawNPCHousesInWorld () inline protected
Definition at line 40533 of file Main.cs.
        {
            this._npcsWithBannersToDraw.Clear();
            this._occupantsListToDrawNPCHouses.Clear();
            for (int i = 0; i < Main.maxNPCs; i++)
            {
                if (Main.npc[i].active && Main.npc[i].townNPC && !Main.npc[i].homeless && Main.npc[i].homeTileX > 0 && Main.npc[i].homeTileY > 0 && Main.npc[i].type != 37)
                {
                    this._npcsWithBannersToDraw.Add(i);
                }
            }
            this._npcsWithBannersToDraw.Sort(new Comparison<int>(this.NPCBannerSorter));
            UILinkPointNavigator.Shortcuts.NPCS_HoveredBanner = -2;
            for (int j = 0; j < this._npcsWithBannersToDraw.Count; j++)
            {
                int num = this._npcsWithBannersToDraw[j];
                NPC npc = Main.npc[num];
                if (npc.active && npc.townNPC && !npc.homeless && npc.homeTileX > 0 && npc.homeTileY > 0 && npc.type != 37)
                {
                    int num2 = 0;
                    int housingCategory = npc.housingCategory;
                    int num3 = npc.homeTileX;
                    int num4 = npc.homeTileY - 1;
                    WorldGen.TownManager.AddOccupantsToList(num3, num4 + 1, this._occupantsListToDrawNPCHouses);
                    if (this._occupantsListToDrawNPCHouses.Contains(npc.type))
                    {
                        num2 = 1;
                    }
                    int num5 = 0;
                    for (int k = this._npcsWithBannersToDraw.Count - 1; k > j; k--)
                    {
                        int num6 = this._npcsWithBannersToDraw[k];
                        if (Main.npc[num6].homeTileX == num3 && Main.npc[num6].homeTileY == num4 + 1)
{
                            num5++;
                        }
                    }
                    int num7 = num5 * 26;
                    if (Main.tile[num3, num4] != null)
                    {
                        bool flag = false;
                        while (!Main.tile[num3, num4].active() || !Main.tileSolid[(int)Main.tile[num3, num4].type])
{
                            num4--;
                            if (num4 < 10)
{
                                break;
                            }
                            if (Main.tile[num3, num4] == null)
{
                                flag = true;
                                break;
                            }
                        }
                        if (!flag)
{
                            int num8 = 8;
                            int num9 = 18;
                            if (Main.tile[num3, num4].type == 19)
{
                                num9 -= 8;
                            }
                            num4++;
                            int num10 = 0;
                            float num11 = (float)(num4 * 16);
                            num11 += (float)num7;
                            SpriteEffects spriteEffects = SpriteEffects.None;
                            Texture2D value = TextureAssets.HouseBanner.Value;
                            Microsoft.Xna.Framework.Rectangle rectangle = value.Frame(2, 2, 0, 0, 0, 0);
                            if (num2 > 0)
{
                                rectangle.X += rectangle.Width * num2;
                            }
                            if (housingCategory > 0)
{
                                rectangle.Y += rectangle.Height * housingCategory;
                            }
                            if (Main.player[Main.myPlayer].gravDir == -1f)
{
                                num11 -= Main.screenPosition.Y;
                                num11 = Main.screenPosition.Y + (float)Main.screenHeight - num11;
                                num11 -= (float)rectangle.Height;
                                spriteEffects = SpriteEffects.FlipVertically;
                                num10 = 4;
                            }
                            Main.spriteBatch.Draw(value, new Vector2((float)(num3 * 16 - (int)Main.screenPosition.X + num8), num11 - (float)((int)Main.screenPosition.Y) + (float)num9 + (float)num10), new Microsoft.Xna.Framework.Rectangle?(rectangle), Lighting.GetColor(num3, num4), 0f, new Vector2((float)(rectangle.Width / 2), (float)(rectangle.Height / 2)), 1f, spriteEffects, 0f);
                            int headIndexSafe = TownNPCProfiles.GetHeadIndexSafe(npc);
                            float num12 = 1f;
                            float num13;
                            if (TextureAssets.NpcHead[headIndexSafe].Width() > TextureAssets.NpcHead[headIndexSafe].Height())
{
                                num13 = (float)TextureAssets.NpcHead[headIndexSafe].Width();
                            }
                            else
{
                                num13 = (float)TextureAssets.NpcHead[headIndexSafe].Height();
                            }
                            if (num13 > 24f)
{
                                num12 = 24f / num13;
                            }
                            Main.spriteBatch.Draw(TextureAssets.NpcHead[headIndexSafe].Value, new Vector2((float)(num3 * 16 - (int)Main.screenPosition.X + num8), num11 - (float)((int)Main.screenPosition.Y) + (float)num9 + 2f), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.NpcHead[headIndexSafe].Width(), TextureAssets.NpcHead[headIndexSafe].Height())), Lighting.GetColor(num3, num4), 0f, new Vector2((float)(TextureAssets.NpcHead[headIndexSafe].Width() / 2), (float)(TextureAssets.NpcHead[headIndexSafe].Height() / 2)), num12, spriteEffects, 0f);
                            num3 = num3 * 16 - (int)Main.screenPosition.X + num8 - rectangle.Width / 2;
                            num4 = (int)num11 - (int)Main.screenPosition.Y + 4;
                            int num14 = -8;
                            if (PlayerInput.ControllerHousingCursorActive)
{
                                Vector2 vector = PlayerInput.HousingWorldPosition - Main.screenPosition;
                                if (vector.X >= (float)num3 && vector.X <= (float)(num3 + rectangle.Width) && vector.Y >= (float)num4 && vector.Y <= (float)(num4 + rectangle.Height + num14))
{
                                    UILinkPointNavigator.Shortcuts.NPCS_HoveredBanner = num;
                                }
                            }
                            else if (Main.mouseX >= num3 && Main.mouseX <= num3 + rectangle.Width && Main.mouseY >= num4 && Main.mouseY <= num4 + rectangle.Height + num14)
{
                                string npchouseBannerText = Lang.GetNPCHouseBannerText(npc, num2);
                                this.MouseText(npchouseBannerText, 0, 0, -1, -1, -1, -1, 0);
                                if (Main.mouseRightRelease && Main.mouseRight)
{
                                    Main.mouseRightRelease = false;
                                    WorldGen.kickOut(num);
                                    SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                                }
                            }
                        }
                    }
                }
            }
        }
References Terraria.NPC.active, Terraria.Tile.active(), Terraria.GameContent.TownRoomManager.AddOccupantsToList(), Terraria.GameInput.PlayerInput.ControllerHousingCursorActive, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Lighting.GetColor(), Terraria.GameContent.TownNPCProfiles.GetHeadIndexSafe(), Terraria.Lang.GetNPCHouseBannerText(), Terraria.Player.gravDir, Microsoft.Xna.Framework.Rectangle.Height, Terraria.NPC.homeless, Terraria.NPC.homeTileX, Terraria.NPC.homeTileY, Terraria.GameContent.TextureAssets.HouseBanner, Terraria.NPC.housingCategory, int, Terraria.WorldGen.kickOut(), Terraria.Main.maxNPCs, Terraria.Main.mouseRight, Terraria.Main.mouseRightRelease, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Main.npc, Terraria.GameContent.TextureAssets.NpcHead, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.spriteBatch, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.WorldGen.TownManager, Terraria.NPC.townNPC, Terraria.NPC.type, Terraria.Tile.type, System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Rectangle.Width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.