Terraria Decompiled: Terraria.Main.DoScrollingInInventory
DoScrollingInInventory()
static void Terraria.Main.DoScrollingInInventory () inline static
Definition at line 15912 of file Main.cs.
        {
            int num = PlayerInput.ScrollWheelDelta / 120;
            bool flag = true;
            if (Main.PipsUseGrid)
            {
                int num2 = 42;
                int num3 = 340;
                int num4 = 310;
                PlayerInput.SetZoom_UI();
                int num5 = (Main.screenWidth - num4 - 280) / num2;
                int num6 = (Main.screenHeight - num3 - 20) / num2;
                if (new Microsoft.Xna.Framework.Rectangle(num4, num3, num5 * num2, num6 * num2).Contains(Main.MouseScreen.ToPoint()))
                {
                    int num7 = Math.Sign(num);
                    while (num != 0)
                    {
                        Main.ScrollCraftingGrid(num, num5);
                        num -= num7;
                    }
                }
                PlayerInput.SetZoom_World();
            }
            if (Main.LocalPlayer.chest != -1 && ChestUI.LastHighestChestRow > 0)
            {
                int num8 = 42;
                int num9 = 340;
                int num10 = 310;
                PlayerInput.SetZoom_UI();
                int num11 = (Main.screenWidth - num10 - 280) / num8;
                int num12 = (Main.screenHeight - num9 - 20) / num8;
                Microsoft.Xna.Framework.Rectangle lastChestDisplayRectangle = ChestUI.LastChestDisplayRectangle;
                if (lastChestDisplayRectangle.Contains(Main.MouseScreen.ToPoint()))
                {
                    flag = false;
                    int num13 = Math.Sign(num);
                    while (num != 0)
                    {
                        ChestUI.Scroll(num);
                        num -= num13;
                    }
                }
                PlayerInput.SetZoom_World();
            }
            if (NewCraftingUI.Visible)
            {
                flag = false;
            }
            if (flag)
            {
                Main.ScrollCraftingList(num);
            }
        }
References Terraria.Player.chest, Microsoft.Xna.Framework.Rectangle.Contains(), Terraria.UI.ChestUI.LastChestDisplayRectangle, Terraria.UI.ChestUI.LastHighestChestRow, Terraria.Main.LocalPlayer, Terraria.Main.MouseScreen, Terraria.Main.PipsUseGrid, Terraria.UI.ChestUI.Scroll(), Terraria.Main.ScrollCraftingGrid(), Terraria.Main.ScrollCraftingList(), Terraria.GameInput.PlayerInput.SetZoom_UI(), Terraria.GameInput.PlayerInput.SetZoom_World(), System.Math.Sign(), and Terraria.GameContent.UI.NewCraftingUI.Visible.
Referenced by Terraria.Main.DoUpdate_WhilePaused(), and Terraria.Player.Update().