Terraria Decompiled: Terraria.Main.DrawProj_StardustGuardianPunching
DrawProj_StardustGuardianPunching()
void Terraria.Main.DrawProj_StardustGuardianPunching (Projectile proj) inline private
Definition at line 35062 of file Main.cs.
        {
            if (Main.gamePaused)
            {
                return;
            }
            int num = 6;
            Texture2D value = TextureAssets.Extra[46].Value;
            int num2 = 20;
            Vector2 vector = proj.Center - proj.rotation.ToRotationVector2() * (float)num2 * (float)proj.spriteDirection;
            for (int i = 0; i < num; i++)
            {
                float num3 = Main.rand.NextFloat();
                float num4 = Utils.GetLerpValue(0f, 0.3f, num3, true) * Utils.GetLerpValue(1f, 0.5f, num3, true);
                float num5 = Utils.GetLerpValue(0f, 0.3f, num3, true) * Utils.GetLerpValue(1f, 0.5f, num3, true);
                float num6 = MathHelper.Lerp(0.6f, 1f, num5);
                Microsoft.Xna.Framework.Color color = new Microsoft.Xna.Framework.Color(255, 255, 255, 127);
                color *= num4 * 0.5f;
                Vector2 vector2 = value.Size() / 2f;
                Microsoft.Xna.Framework.Color color2 = Microsoft.Xna.Framework.Color.White * num4;
                color2.A /= 2;
                Microsoft.Xna.Framework.Color color3 = color2 * 0.5f;
                float num7 = 1f;
                float num8 = 1f + Main.rand.NextFloat() * 0.5f;
                float num9 = Main.rand.NextFloatDirection();
                Vector2 vector3 = new Vector2(0.8f) * num8 * num7 * num6;
                float num10 = 20f + MathHelper.Lerp(0f, 20f, num3) + num8 * 16f;
                float num11 = proj.rotation + ((proj.direction == 1) ? 0f : 3.1415927f) + num9 * 6.2831855f * 0.04f;
                float num12 = num11 + 1.5707964f;
                Vector2 vector4 = vector + num11.ToRotationVector2() * num10 + Main.rand.NextVector2Circular(20f, 20f) - Main.screenPosition;
                color *= num7;
                color3 *= num7;
                SpriteEffects spriteEffects = SpriteEffects.None;
                Main.spriteBatch.Draw(value, vector4, null, color, num12, vector2, vector3, spriteEffects, 0f);
                Main.spriteBatch.Draw(value, vector4, null, color3, num12, vector2, vector3 * 0.8f, spriteEffects, 0f);
            }
        }
References Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.GameContent.TextureAssets.Extra, Terraria.Main.gamePaused, Terraria.Utils.GetLerpValue(), Microsoft.Xna.Framework.MathHelper.Lerp(), Terraria.Main.rand, Terraria.Projectile.rotation, Terraria.Main.screenPosition, Terraria.Main.spriteBatch, Terraria.Projectile.spriteDirection, System.value, ReLogic.Content.Asset< T >.Value, and Microsoft.Xna.Framework.Graphics.Vector2.