Terraria Decompiled: Terraria.Main.DoUpdate
DoUpdate()
void Terraria.Main.DoUpdate (ref GameTime gameTime) inline protected
Definition at line 15304 of file Main.cs.
        {
            Main.gameTimeCache = gameTime;
            if (Main.showSplash)
            {
                bool flag;
                FocusHelper.UpdateFocus(out flag);
                this.UpdateAudio();
                Main.GlobalTimeWrappedHourly = (float)(gameTime.TotalGameTime.TotalSeconds % 3600.0);
                ChromaInitializer.UpdateEvents();
                Main.Chroma.Update(Main.GlobalTimeWrappedHourly);
                return;
            }
            PartySky.MultipleSkyWorkaroundFix = true;
            Main.LocalPlayer.cursorItemIconReversed = false;
            if (!Main.GlobalTimerPaused)
            {
                Main.GlobalTimeWrappedHourly = (float)(gameTime.TotalGameTime.TotalSeconds % 3600.0);
            }
            Main.UpdateCreativeGameModeOverride();
            Main.UpdateWorldPreparationState();
            if (Player.BlockInteractionWithProjectiles > 0 && !Main.mouseRight && Main.mouseRightRelease)
            {
                Player.BlockInteractionWithProjectiles--;
            }
            PlayerInput.SetZoom_UI();
            for (int i = Main.DelayedProcesses.Count - 1; i >= 0; i--)
            {
                IEnumerator enumerator = Main.DelayedProcesses[i];
                if (!enumerator.MoveNext())
                {
                    Main.DelayedProcesses.Remove(enumerator);
                }
            }
            if (!Main.gameMenu || Main.menuMode != 888)
            {
                Main.MenuUI.SetState(null);
            }
            if (Main.gameMenu)
            {
                IngameUIWindows.CloseAll(true);
            }
            Main.CurrentInputTextTakerOverride = null;
            if (!Main.dedServ)
            {
                Main.AchievementAdvisor.Update();
            }
            PlayerInput.SetZoom_Unscaled();
            PlayerInput.ResetInputsOnActiveStateChange();
            if (Main.OnTickForThirdPartySoftwareOnly != null)
            {
                Main.OnTickForThirdPartySoftwareOnly();
            }
            if (Main._hasPendingNetmodeChange)
            {
                Main.netMode = Main._targetNetMode;
                Main._hasPendingNetmodeChange = false;
            }
            if (CaptureManager.Instance.IsCapturing)
            {
                bool flag2;
                FocusHelper.UpdateFocus(out flag2);
                return;
            }
            if (Main.ActivePlayerFileData != null)
            {
                Main.ActivePlayerFileData.UpdatePlayTimer();
            }
            Netplay.UpdateInMainThread();
            if (Main.changeTheTitle)
            {
                Main.changeTheTitle = false;
                this.SetTitle(false);
            }
            this._worldUpdateTimeTester.Restart();
            if (!WorldGen.isGeneratingOrLoadingWorld)
            {
                WorldGen.destroyObject = false;
            }
            if (Main.gameMenu)
            {
                Main.mapFullscreen = false;
            }
            Main.UpdateSettingUnlocks();
            if (DebugOptions.UpdateWaitInMs > 0.0)
            {
                ThreadUtilities.HighPrecisionSleep(DebugOptions.UpdateWaitInMs);
            }
            NPC.UpdateProtectedSpawnSlots();
            if (Main.dedServ)
            {
                if (Main.dedServFPS)
                {
                    Main.updatesCountedForFPS++;
                    if (!Main.fpsTimer.IsRunning)
                    {
                        Main.fpsTimer.Restart();
                    }
                    if (Main.fpsTimer.ElapsedMilliseconds >= 1000L)
                    {
                        Main.dedServCount1 += Main.updatesCountedForFPS;
                        Main.dedServCount2++;
                        float num = (float)Main.dedServCount1 / (float)Main.dedServCount2;
                        Console.WriteLine(string.Concat(new object[]
{
                            Main.updatesCountedForFPS,
                            "  (",
                            num,
                            ")"
                        }));
                        Main.updatesCountedForFPS = 0;
                        Main.fpsTimer.Restart();
                    }
                }
                else
                {
                    if (Main.fpsTimer.IsRunning)
                    {
                        Main.fpsTimer.Stop();
                    }
                    Main.updatesCountedForFPS = 0;
                }
            }
            if (!WorldGen.generatingWorld)
            {
                Main.DoUpdate_AutoSave();
            }
            if (!Main.dedServ)
            {
                ChromaInitializer.UpdateEvents();
                Main.Chroma.Update(Main.GlobalTimeWrappedHourly);
                if (Main.FrameSkipMode == FrameSkipMode.Off || Main.FrameSkipMode == FrameSkipMode.Subtle)
                {
                    base.IsFixedTimeStep = Main.ThrottleWhenInactive && !base.IsActive;
                    Main.graphics.SynchronizeWithVerticalRetrace = true;
                }
                else
                {
                    base.IsFixedTimeStep = true;
                    Main.graphics.SynchronizeWithVerticalRetrace = true;
                }
                base.InactiveSleepTime = (Main.ThrottleWhenInactive ? TimeSpan.FromMilliseconds(20.0) : TimeSpan.Zero);
                if (Main.showSplash)
                {
                    return;
                }
                Main.updatesCountedForFPS++;
                if (Main.fpsTimer.ElapsedMilliseconds >= 1000L)
                {
                    if ((float)Main.fpsCount >= 30f + 30f * Main.gfxQuality)
                    {
                        Main.gfxQuality += Main.gfxRate;
                        Main.gfxRate += 0.005f;
                    }
                    else if ((float)Main.fpsCount < 29f + 30f * Main.gfxQuality)
                    {
                        Main.gfxRate = 0.01f;
                        Main.gfxQuality -= 0.1f;
                    }
                    if (Main.gfxQuality < 0f)
                    {
                        Main.gfxQuality = 0f;
                    }
                    if (Main.gfxQuality > 1f)
                    {
                        Main.gfxQuality = 1f;
                    }
                    if (Main.maxQ && base.IsActive)
                    {
                        Main.gfxQuality = 1f;
                        Main.maxQ = false;
                    }
                    Main.updateRate = Main.uCount;
                    Main.frameRate = Main.fpsCount;
                    Main.fpsCount = 0;
                    Main.fpsTimer.Restart();
                    Main.updatesCountedForFPS = 0;
                    Main.drawsCountedForFPS = 0;
                    Main.uCount = 0;
                    if (Main.gfxQuality < 0.8f)
                    {
                        Main.mapTimeMax = (int)((1f - Main.gfxQuality) * 60f);
                    }
                    else
                    {
                        Main.mapTimeMax = 0;
                    }
                }
                if (Main.FrameSkipMode == FrameSkipMode.Off || (Main.FrameSkipMode == FrameSkipMode.Subtle && !Main.improvedSubtleFrameSkip))
                {
                    Main.UpdateTimeAccumulator += gameTime.ElapsedGameTime.TotalSeconds;
                    if (Main.UpdateTimeAccumulator < Main.TARGET_FRAME_TIME)
                    {
                        if (Main.FrameSkipMode == FrameSkipMode.Subtle || CaptureInterface.CameraLock)
{
                            Main.instance.SuppressDraw();
                        }
                        return;
                    }
                    gameTime = new GameTime(gameTime.TotalGameTime, new TimeSpan((long)(Main.TARGET_FRAME_TIME * 10000000.0)));
                }
                if (Main.FrameSkipMode == FrameSkipMode.Off || Main.FrameSkipMode == FrameSkipMode.Subtle)
                {
                    Main.UpdateTimeAccumulator -= Main.TARGET_FRAME_TIME;
                    Main.UpdateTimeAccumulator = Utils.Clamp<double>(Main.UpdateTimeAccumulator, 0.0, 3.0 * Main.TARGET_FRAME_TIME);
                    int num2 = 0;
                    if (Main.UpdateTimeAccumulator > Main.TARGET_FRAME_TIME && ++Main.successiveSkippedDraws <= num2)
                    {
                        base.InactiveSleepTime = TimeSpan.Zero;
                        Main.instance.SuppressDraw();
                    }
                    else
                    {
                        Main.successiveSkippedDraws = 0;
                    }
                }
                Main.uCount++;
                DebugLineDraw.PreUpdate();
                Main.MouseOversClear();
                PlayerInput.AllowExecutionOfGamepadInstructions = true;
                Main.TryPlayingCreditsRoll();
                PlayerInput.SetZoom_UI();
                Main.UpdateUIStates(gameTime);
                PlayerInput.SetZoom_Unscaled();
                Terraria.Graphics.Effects.Filters.Scene.Update(gameTime);
                Overlays.Scene.Update(gameTime);
                LiquidRenderer.Instance.Update(gameTime);
                this.UpdateAudio();
                InGameNotificationsTracker.Update();
                ItemSlot.UpdateInterface();
                CraftingEffects.Update();
                if (Main.teamCooldown > 0)
                {
                    Main.teamCooldown--;
                }
                Main.DoUpdate_AnimateBackgrounds();
                Animation.UpdateAll();
                if (Main.qaStyle == 1)
                {
                    Main.gfxQuality = 1f;
                }
                else if (Main.qaStyle == 2)
                {
                    Main.gfxQuality = 0.5f;
                }
                else if (Main.qaStyle == 3)
                {
                    Main.gfxQuality = 0f;
                }
                Main.maxDustToDraw = (int)(6000f * (Main.gfxQuality * 0.7f + 0.3f));
                if ((double)Main.gfxQuality < 0.9)
                {
                    Main.maxDustToDraw = (int)((float)Main.maxDustToDraw * Main.gfxQuality);
                }
                if (Main.maxDustToDraw < 1000)
                {
                    Main.maxDustToDraw = 1000;
                }
                Gore.goreTime = (int)(600f * Main.gfxQuality);
                if (!WorldGen.isGeneratingOrLoadingWorld)
                {
                    Liquid.cycles = (int)(17f - 10f * Main.gfxQuality);
                    Liquid.curMaxLiquid = (int)((double)Liquid.maxLiquid * 0.25 + (double)Liquid.maxLiquid * 0.75 * (double)Main.gfxQuality);
                    if (Main.Setting_UseReducedMaxLiquids)
                    {
                        Liquid.curMaxLiquid = (int)(2500f + 2500f * Main.gfxQuality);
                    }
                }
                if ((double)Main.gfxQuality < 0.2)
                {
                    LegacyLighting.RenderPhases = 8;
                }
                else if ((double)Main.gfxQuality < 0.4)
                {
                    LegacyLighting.RenderPhases = 7;
                }
                else if ((double)Main.gfxQuality < 0.6)
                {
                    LegacyLighting.RenderPhases = 6;
                }
                else if ((double)Main.gfxQuality < 0.8)
                {
                    LegacyLighting.RenderPhases = 5;
                }
                else
                {
                    LegacyLighting.RenderPhases = 4;
                }
                if (!WorldGen.isGeneratingOrLoadingWorld && Liquid.quickSettle)
                {
                    Liquid.curMaxLiquid = Liquid.maxLiquid;
                    if (Main.Setting_UseReducedMaxLiquids)
                    {
                        Liquid.curMaxLiquid = 5000;
                    }
                    Liquid.cycles = 1;
                }
                if (!Main.gameMenu || Math.Abs(this.logoRotationSpeed) > 1000f)
                {
                    this.logoRotation = 0f;
                    this.logoRotationSpeed = 0f;
                    this.logoScale = 1f;
                }
                Main.UpdateOldNPCShop();
                if (Main.reforgeCooldown > 0)
                {
                    Main.reforgeCooldown--;
                }
                bool flag3 = false;
                FocusHelper.UpdateFocus(out flag3);
                if (flag3)
                {
                    if (Main.netMode != 2 && Main.myPlayer >= 0)
                    {
                        Main.player[Main.myPlayer].delayUseItem = true;
                    }
                    Main.mouseLeftRelease = false;
                    Main.mouseRightRelease = false;
                    if (Main.gameMenu)
                    {
                        Main.UpdateMenu();
                    }
                    Main.gamePaused = true;
                    return;
                }
                SkyManager.Instance.Update(gameTime);
                if (!Main.gamePaused)
                {
                    EmoteBubble.UpdateAll();
                }
                Main.DoUpdate_AnimateCursorColors();
                Main.DoUpdate_AnimateTileGlows();
                this.DoUpdate_AnimateDiscoRGB();
                Main.DoUpdate_AnimateVisualPlayerAura();
                this.DoUpdate_AnimateWaterfalls();
                Main.DoUpdate_AnimateWalls();
                Main.AnimateTiles();
                Main.DoUpdate_AnimateItemIcons();
                Main.DoUpdate_F10_ToggleFPS();
                Main.DoUpdate_F9_ToggleLighting();
                Main.DoUpdate_F8_ToggleNetDiagnostics();
                Main.DoUpdate_F7_ToggleGraphicsDiagnostics();
                Main.DoUpdate_F11_ToggleUI();
                Main.DoUpdate_AltEnter_ToggleFullscreen();
                this.DoDebugFunctions();
                this.DoUpdate_HandleInput();
                Main.DoUpdate_HandleChat();
                Main.DoUpdate_Enter_ToggleChat();
                if ((Main.timeForVisualEffects += 1.0) >= 216000.0)
                {
                    Main.timeForVisualEffects = 0.0;
                }
                if (Main.gameMenu)
                {
                    Main.UpdateMenu();
                    if (Main.netMode != 2)
                    {
                        return;
                    }
                    Main.gamePaused = false;
                }
                this.UpdateParticleSystems_UI();
                Main.EverLastingTicker += 1UL;
                if (!Main.CanUpdateGameplay && Main.netMode != 2)
                {
                    return;
                }
                Main.CheckInvasionProgressDisplay();
            }
            this.UpdateWindyDayState();
            if (Main.netMode == 2)
            {
                Main.cloudAlpha = Main.maxRaining;
            }
            if (Main.netMode == 1)
            {
                Main.TrySyncingMyPlayer();
            }
            if (Main.CanPauseGame())
            {
                Main.DoUpdate_WhilePaused();
                Main.gamePaused = true;
                return;
            }
            Main.gamePaused = false;
            if (Main.OnTickForInternalCodeOnly != null)
            {
                Main.OnTickForInternalCodeOnly();
            }
            for (int j = Main.DelayedProcessesInGame.Count - 1; j >= 0; j--)
            {
                IEnumerator enumerator2 = Main.DelayedProcessesInGame[j];
                if (!enumerator2.MoveNext())
                {
                    Main.DelayedProcessesInGame.Remove(enumerator2);
                }
            }
            if ((Main.dedServ || (Main.netMode != 1 && !Main.gameMenu && !Main.gamePaused)) && Main.AmbienceServer != null)
            {
                Main.AmbienceServer.Update();
            }
            WorldGen.BackgroundsCache.UpdateFlashValues();
            Main.LocalGolfState.Update();
            if (FocusHelper.AllowRain && Main.cloudAlpha > 0f)
            {
                Rain.MakeRain();
            }
            if (Main.netMode != 1)
            {
                this.updateCloudLayer();
            }
            for (int k = 0; k < Main.dayRate; k++)
            {
                this.UpdateWeather(gameTime, k);
            }
            Main.UnpausedUpdateSeed = Utils.RandomNextSeed(Main.UnpausedUpdateSeed);
            Main.Ambience();
            if (Main.netMode != 2)
            {
                try
                {
                    Main.snowing();
                }
                catch
                {
                    if (!Main.ignoreErrors)
                    {
                        throw;
                    }
                }
                Sandstorm.EmitDust();
            }
            if (Main.netMode != 2)
            {
                if ((double)Main.screenPosition.Y < Main.worldSurface * 16.0 + 16.0)
                {
                    Star.UpdateStars();
                    Cloud.UpdateClouds();
                }
                else if (Main.shimmerAlpha > 0f)
                {
                    Star.UpdateStars();
                    int num3 = Main.rand.Next(Main.numStars);
                    if (Main.rand.Next(90) == 0)
                    {
                        if (Main.star[num3] != null && !Main.star[num3].hidden && !Main.star[num3].falling)
{
                            Main.star[num3].Fall();
                        }
                        for (int l = 0; l < Main.numStars; l++)
{
                            if (Main.star[l].hidden)
{
                                Star.SpawnStars(l);
                            }
                        }
                    }
                }
            }
            PortalHelper.UpdatePortalPoints();
            LucyAxeMessage.UpdateMessageCooldowns();
            if (this.ShouldUpdateEntities())
            {
                this.DoUpdateInWorld(this._worldUpdateTimeTester);
            }
            if (Main.netMode != 2)
            {
                Main.ChromaPainter.Update();
            }
            if (Main.OnTickForThirdPartySoftwareOnly != null)
            {
                Main.OnTickForThirdPartySoftwareOnly();
            }
        }
References Terraria.Main._hasPendingNetmodeChange, Terraria.Main._targetNetMode, System.Math.Abs(), Terraria.Main.AchievementAdvisor, Terraria.Main.ActivePlayerFileData, Terraria.FocusHelper.AllowRain, Terraria.Main.Ambience(), Terraria.Main.AmbienceServer, Terraria.Main.AnimateTiles(), Terraria.WorldGen.BackgroundsCache, Terraria.Player.BlockInteractionWithProjectiles, Terraria.Graphics.Capture.CaptureInterface.CameraLock, Terraria.Main.CanPauseGame(), Terraria.Main.CanUpdateGameplay, Terraria.Main.changeTheTitle, Terraria.Main.CheckInvasionProgressDisplay(), Terraria.Main.Chroma, Terraria.Main.ChromaPainter, Terraria.Utils.Clamp(), Terraria.UI.IngameUIWindows.CloseAll(), Terraria.Main.cloudAlpha, Newtonsoft.Json.Linq.Concat, System.Collections.Generic.List< T >.Count, Terraria.Main.dayRate, Terraria.Main.dedServ, Terraria.Main.dedServCount1, Terraria.Main.dedServCount2, Terraria.Main.dedServFPS, Terraria.Main.DelayedProcesses, Terraria.Main.DelayedProcessesInGame, Terraria.Player.delayUseItem, Terraria.Main.DoUpdate_AltEnter_ToggleFullscreen(), Terraria.Main.DoUpdate_AnimateBackgrounds(), Terraria.Main.DoUpdate_AnimateCursorColors(), Terraria.Main.DoUpdate_AnimateItemIcons(), Terraria.Main.DoUpdate_AnimateTileGlows(), Terraria.Main.DoUpdate_AnimateVisualPlayerAura(), Terraria.Main.DoUpdate_AnimateWalls(), Terraria.Main.DoUpdate_AutoSave(), Terraria.Main.DoUpdate_Enter_ToggleChat(), Terraria.Main.DoUpdate_F10_ToggleFPS(), Terraria.Main.DoUpdate_F11_ToggleUI(), Terraria.Main.DoUpdate_F7_ToggleGraphicsDiagnostics(), Terraria.Main.DoUpdate_F8_ToggleNetDiagnostics(), Terraria.Main.DoUpdate_F9_ToggleLighting(), Terraria.Main.DoUpdate_HandleChat(), Terraria.Main.DoUpdate_WhilePaused(), Terraria.GameContent.Events.Sandstorm.EmitDust(), Terraria.Star.Fall(), Terraria.Star.falling, Terraria.Main.fpsCount, Terraria.Main.fpsTimer, Terraria.Main.FrameSkipMode, System.TimeSpan.FromMilliseconds(), Terraria.Main.gameMenu, Terraria.Main.gamePaused, Terraria.WorldGen.generatingWorld, Terraria.Main.gfxQuality, Terraria.Main.gfxRate, Terraria.Main.GlobalTimerPaused, Terraria.Main.GlobalTimeWrappedHourly, Terraria.Star.hidden, ReLogic.Threading.ThreadUtilities.HighPrecisionSleep(), Terraria.Main.ignoreErrors, Terraria.Main.improvedSubtleFrameSkip, Terraria.GameContent.Liquid.LiquidRenderer.Instance, Terraria.Graphics.Capture.CaptureManager.Instance, Terraria.Graphics.Effects.SkyManager.Instance, Terraria.Main.instance, int, Terraria.Graphics.Capture.CaptureManager.IsCapturing, Terraria.WorldGen.isGeneratingOrLoadingWorld, Microsoft.Xna.Framework.Input.L, Terraria.Main.LocalGolfState, Terraria.Rain.MakeRain(), Terraria.Main.maxDustToDraw, Terraria.Liquid.maxLiquid, Terraria.Main.maxQ, Terraria.Main.maxRaining, Terraria.Main.menuMode, Terraria.Main.MenuUI, Terraria.Main.MouseOversClear(), Terraria.Main.mouseRight, Terraria.Main.mouseRightRelease, System.Collections.IEnumerator.MoveNext(), Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.numStars, Terraria.Main.OnTickForInternalCodeOnly, Terraria.Main.OnTickForThirdPartySoftwareOnly, Terraria.Main.player, Terraria.Testing.DebugLineDraw.PreUpdate(), Terraria.Main.qaStyle, Terraria.Liquid.quickSettle, Terraria.Main.rand, Terraria.Utils.RandomNextSeed(), Terraria.Main.reforgeCooldown, System.Collections.Generic.List< T >.Remove(), Terraria.GameInput.PlayerInput.ResetInputsOnActiveStateChange(), Terraria.Graphics.Effects.Filters.Scene, Terraria.Graphics.Effects.Overlays.Scene, Terraria.Main.screenPosition, Terraria.UI.UserInterface.SetState(), Terraria.Main.Setting_UseReducedMaxLiquids, Terraria.GameInput.PlayerInput.SetZoom_UI(), Terraria.GameInput.PlayerInput.SetZoom_Unscaled(), Terraria.Main.shimmerAlpha, Terraria.Main.showSplash, Terraria.Main.snowing(), Terraria.Star.SpawnStars(), Terraria.Main.star, Terraria.Main.successiveSkippedDraws, Microsoft.Xna.Framework.Game.SuppressDraw(), Terraria.Main.TARGET_FRAME_TIME, Terraria.Main.teamCooldown, Terraria.Main.timeForVisualEffects, Terraria.Main.TryPlayingCreditsRoll(), Terraria.Main.TrySyncingMyPlayer(), Terraria.Main.uCount, Terraria.Main.UnpausedUpdateSeed, Terraria.GameContent.Ambience.AmbienceServer.Update(), Terraria.GameContent.ChromaHotkeyPainter.Update(), Terraria.GameContent.CraftingEffects.Update(), Terraria.GameContent.Golf.GolfState.Update(), Terraria.UI.AchievementAdvisor.Update(), Terraria.UI.InGameNotificationsTracker.Update(), ReLogic.Peripherals.RGB.ChromaEngine.Update(), Terraria.GameContent.Liquid.LiquidRenderer.Update(), Terraria.Graphics.Effects.FilterManager.Update(), Terraria.Graphics.Effects.OverlayManager.Update(), Terraria.Graphics.Effects.SkyManager.Update(), Terraria.Animation.UpdateAll(), Terraria.GameContent.UI.EmoteBubble.UpdateAll(), Terraria.Cloud.UpdateClouds(), Terraria.Main.UpdateCreativeGameModeOverride(), Terraria.Initializers.ChromaInitializer.UpdateEvents(), Terraria.GameContent.BackgroundChangeFlashInfo.UpdateFlashValues(), Terraria.FocusHelper.UpdateFocus(), Terraria.Netplay.UpdateInMainThread(), Terraria.UI.ItemSlot.UpdateInterface(), Terraria.Main.UpdateMenu(), Terraria.GameContent.LucyAxeMessage.UpdateMessageCooldowns(), Terraria.Main.UpdateOldNPCShop(), Terraria.IO.PlayerFileData.UpdatePlayTimer(), Terraria.GameContent.PortalHelper.UpdatePortalPoints(), Terraria.NPC.UpdateProtectedSpawnSlots(), Terraria.Main.updatesCountedForFPS, Terraria.Main.UpdateSettingUnlocks(), Terraria.Star.UpdateStars(), Terraria.Main.UpdateTimeAccumulator, Terraria.Main.UpdateUIStates(), Terraria.Testing.DebugOptions.UpdateWaitInMs, Terraria.Main.UpdateWorldPreparationState(), Terraria.Main.worldSurface, System.Console.WriteLine(), Microsoft.Xna.Framework.Vector2.Y, and System.TimeSpan.Zero.