Terraria Decompiled: Terraria.Main.wallDungeon
wallDungeon
bool [] Terraria.Main.wallDungeon = new bool[(int)WallID.Count] static
Definition at line 69859 of file Main.cs.
Referenced by Terraria.WorldGen.AddLifeCrystal(), Terraria.WorldGen.AddManaCrystal(), Terraria.NPC.AI_AttemptToFindTeleportSpot(), Terraria.NPC.AI_AttemptToFindTeleportSpotNearBooks(), Terraria.WorldGen.badOceanCaveTiles(), Terraria.WorldGen.Skyblock.Calculate(), Terraria.SceneMetrics.CalculateZones(), Terraria.WorldGen.CanEvilReplace(), Terraria.GameContent.Generation.Dungeon.Halls.StairwellDungeonHall.CanPlaceTileAt(), Terraria.WorldGen.Cavinator(), Terraria.Utils.CheckForGoodTeleportationSpot(), Terraria.WorldGen.closeEnoughToDungeonToSpawnGhoulder(), Terraria.WorldGen.SecretSeed.DoAddTeleporters_CanPutTeleporterHere(), Terraria.NPC.DoDeathEvents_SummonDungeonSpirit(), Terraria.WorldGen.SecretSeed.DoNoSurfaceFillTheTop(), Terraria.WorldGen.SecretSeed.DoPaintEverythingNegative(), Terraria.WorldGen.SecretSeed.DoPooEverywhere(), Terraria.WorldGen.FinishDrunkGen(), Terraria.WorldGen.FinishGetGoodWorld(), Terraria.WorldGen.FinishRemixWorld(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GetTierForDungeonWall(), Terraria.WorldGen.GrowLivingTree(), Terraria.WorldGen.GrowLivingTree_CanPlaceLeaves(), Terraria.WorldGen.GrowLivingTree_HorizontalTunnel(), Terraria.WorldGen.GrowLivingTree_MakePassage(), Terraria.Main.Initialize_TileAndNPCData1(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.IsConsideredDungeonWall(), Terraria.WorldGen.IsDungeon(), Terraria.WorldGen.IslandHouse(), Terraria.WorldGen.KillWall_CheckFailure(), Terraria.WorldGen.LavaLayerCaverer(), Terraria.GameContent.Generation.Dungeon.Entrances.LegacyDungeonEntrance.LegacyEntrance(), Terraria.WorldGen.NotTheBees(), Terraria.WorldGen.OverGrownDungeon(), Terraria.WorldGen.OverGrownDungeonWithRainbowMoss(), Terraria.WorldGen.PaintTheDungeon(), Terraria.WorldGen.Pyramid(), Terraria.GameContent.Generation.Dungeon.DungeonCrawler.SetupDungeonGenVarVariables(), Terraria.WorldGen.ShimmerifySideOfWorld(), Terraria.WorldGen.SpawnThingsFromPot(), Terraria.GameContent.TeleportHelpers.TileIsDangerous(), Terraria.Player.TorchGodsFlavor(), Terraria.NPC.Spawner.TrySpawnAnNPC(), and Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalWallVariants.WallVariants().