Terraria Decompiled: Terraria.Main.HandleMeteorFall
HandleMeteorFall()
static void Terraria.Main.HandleMeteorFall () inline static private
Definition at line 66816 of file Main.cs.
        {
            if (Main.netMode != 1 && WorldGen.spawnMeteor)
            {
                if (Main.time < 15000.0)
                {
                    Main._canShowMeteorFall = true;
                }
                else
                {
                    if (Main._canShowMeteorFall && Main.time <= 16200.0)
                    {
                        Main.AmbienceServer.ForceEntitySpawn(new AmbienceServer.AmbienceSpawnInfo
{
                            skyEntityType = SkyEntityType.Meteor,
                            targetPlayer = -1
                        });
                    }
                    Main._canShowMeteorFall = false;
                }
            }
            if (Main.time > 16200.0 && WorldGen.spawnMeteor)
            {
                WorldGen.spawnMeteor = false;
                if (WorldGen.Skyblock.lowTiles)
                {
                    WorldGen.StartMeteorShower();
                    return;
                }
                if (!WorldGen.dropMeteor(false) && Main.rand.Next(3) == 0)
                {
                    WorldGen.StartMeteorShower();
                }
            }
        }
References Terraria.Main._canShowMeteorFall, Terraria.Main.AmbienceServer, Terraria.WorldGen.dropMeteor(), Terraria.GameContent.Ambience.AmbienceServer.ForceEntitySpawn(), Terraria.WorldGen.Skyblock.lowTiles, Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, Terraria.WorldGen.spawnMeteor, Terraria.WorldGen.StartMeteorShower(), and Terraria.Main.time.
Referenced by Terraria.Main.UpdateTime().