Terraria Decompiled: Terraria.Main.DrawUnderworldBackgroundLayer
DrawUnderworldBackgroundLayer()
static void Terraria.Main.DrawUnderworldBackgroundLayer (Vector2 screenOffset, float pushUp, int layerTextureIndex) inline static private
Definition at line 53254 of file Main.cs.
        {
            int num = Main.underworldBG[layerTextureIndex];
            Asset<Texture2D> asset = TextureAssets.Underworld[num];
            if (!asset.IsLoaded)
            {
                Main.Assets.Request<Texture2D>(asset.Name, 1);
            }
            Texture2D value = asset.Value;
            Vector2 vector = new Vector2((float)value.Width, (float)value.Height) * 0.5f;
            float num2 = (float)(layerTextureIndex * 2) + 3f;
            Vector2 vector2 = new Vector2(1f / num2);
            Microsoft.Xna.Framework.Rectangle rectangle = new Microsoft.Xna.Framework.Rectangle(0, 0, value.Width, value.Height);
            float num3 = 1.3f;
            Vector2 zero = Vector2.Zero;
            int num4 = 0;
            switch (num)
            {
            case 1:
            {
                int num5 = (int)(Main.GlobalTimeWrappedHourly * 8f) % 4;
                rectangle = new Microsoft.Xna.Framework.Rectangle((num5 >> 1) * (value.Width >> 1), num5 % 2 * (value.Height >> 1), value.Width >> 1, value.Height >> 1);
                vector *= 0.5f;
                zero.Y += 175f;
                break;
            }
            case 2:
                zero.Y += 100f;
                break;
            case 3:
                zero.Y += 75f;
                break;
            case 4:
                num3 = 0.5f;
                zero.Y -= 0f;
                break;
            case 5:
                zero.Y += (float)num4;
                break;
            case 6:
            {
                int num6 = (int)(Main.GlobalTimeWrappedHourly * 8f) % 4;
                rectangle = new Microsoft.Xna.Framework.Rectangle(num6 % 2 * (value.Width >> 1), (num6 >> 1) * (value.Height >> 1), value.Width >> 1, value.Height >> 1);
                vector *= 0.5f;
                zero.Y += (float)num4;
                zero.Y += -60f;
                break;
            }
            case 7:
            {
                int num7 = (int)(Main.GlobalTimeWrappedHourly * 8f) % 4;
                rectangle = new Microsoft.Xna.Framework.Rectangle(num7 % 2 * (value.Width >> 1), (num7 >> 1) * (value.Height >> 1), value.Width >> 1, value.Height >> 1);
                vector *= 0.5f;
                zero.Y += (float)num4;
                zero.X -= 400f;
                zero.Y += 90f;
                break;
            }
            case 8:
            {
                int num8 = (int)(Main.GlobalTimeWrappedHourly * 8f) % 4;
                rectangle = new Microsoft.Xna.Framework.Rectangle(num8 % 2 * (value.Width >> 1), (num8 >> 1) * (value.Height >> 1), value.Width >> 1, value.Height >> 1);
                vector *= 0.5f;
                zero.Y += (float)num4;
                zero.Y += 90f;
                break;
            }
            case 9:
                zero.Y += (float)num4;
                zero.Y -= 30f;
                break;
            case 10:
                zero.Y += 250f * num2;
                break;
            case 11:
                zero.Y += 100f * num2;
                break;
            case 12:
                zero.Y += 20f * num2;
                break;
            case 13:
            {
                zero.Y += 20f * num2;
                int num9 = (int)(Main.GlobalTimeWrappedHourly * 8f) % 4;
                rectangle = new Microsoft.Xna.Framework.Rectangle(num9 % 2 * (value.Width >> 1), (num9 >> 1) * (value.Height >> 1), value.Width >> 1, value.Height >> 1);
                vector *= 0.5f;
                break;
            }
            }
            vector *= num3;
            SkyManager.Instance.DrawToDepth(Main.spriteBatch, 1f / vector2.X);
            zero.Y -= pushUp;
            float num10 = num3 * (float)rectangle.Width;
            int num11 = (int)((float)((int)(screenOffset.X * vector2.X - vector.X + zero.X - (float)(Main.screenWidth >> 1))) / num10);
            vector = vector.Floor();
            int num12 = (int)Math.Ceiling((double)((float)Main.screenWidth / num10));
            int num13 = (int)(num3 * ((float)(rectangle.Width - 1) / vector2.X));
            Vector2 vector3 = (new Vector2((float)((num11 - 2) * num13), (float)Main.UnderworldLayer * 16f) + vector - screenOffset) * vector2 + screenOffset - Main.screenPosition - vector + zero;
            vector3 = vector3.Floor();
            while (vector3.X + num10 < 0f)
            {
                num11++;
                vector3.X += num10;
            }
            for (int i = num11 - 2; i <= num11 + 4 + num12; i++)
            {
                Main.spriteBatch.Draw(value, vector3, new Microsoft.Xna.Framework.Rectangle?(rectangle), Microsoft.Xna.Framework.Color.White, 0f, Vector2.Zero, num3, SpriteEffects.None, 0f);
                if (layerTextureIndex == 0)
                {
                    int num14 = (int)(vector3.Y + (float)rectangle.Height * num3);
                    Main.spriteBatch.Draw(TextureAssets.BlackTile.Value, new Microsoft.Xna.Framework.Rectangle((int)vector3.X, num14, (int)((float)rectangle.Width * num3), Math.Max(0, Main.screenHeight - num14)), new Microsoft.Xna.Framework.Color(11, 3, 7));
                }
                vector3.X += num10;
            }
        }
References Terraria.Main.Assets, Terraria.GameContent.TextureAssets.BlackTile, System.Math.Ceiling(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Graphics.Effects.SkyManager.DrawToDepth(), Terraria.Main.GlobalTimeWrappedHourly, Terraria.Graphics.Effects.SkyManager.Instance, int, ReLogic.Content.Asset< T >.IsLoaded, System.Math.Max(), ReLogic.Content.Asset< T >.Name, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Terraria.Main.spriteBatch, Terraria.GameContent.TextureAssets.Underworld, Terraria.Main.underworldBG, Terraria.Main.UnderworldLayer, System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Rectangle.Width, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.Main.DrawUnderworldBackground().