Terraria Decompiled: Terraria.Main.LoadContent_Deferred
LoadContent_Deferred()
IEnumerator Terraria.Main.LoadContent_Deferred () inline protected
Definition at line 8948 of file Main.cs.
        {
            QuickLoad.Load();
            Main.IssueReporter = new GeneralIssueReporter();
            bool doneLoadingMusic = false;
            IEnumerator musicLoadProcedure = this.LoadMusic_InSteps();
            while (!doneLoadingMusic)
            {
                try
                {
                    if (!musicLoadProcedure.MoveNext())
                    {
                        doneLoadingMusic = true;
                    }
                }
                catch
                {
                    doneLoadingMusic = true;
                    Main.musicVolume = 0f;
                    Main.soundVolume = 0f;
                }
                yield return null;
            }
            this._musicLoaded = true;
            Main.splashTimer.Start();
            yield return null;
            AssetInitializer.Load(true);
            Main.TownNPCHeadRenderer = new OutlinedTextureRenderer(TextureAssets.NpcHead);
            Main.ContentThatNeedsRenderTargets.Add(Main.TownNPCHeadRenderer);
            Main.BossNPCHeadRenderer = new OutlinedTextureRenderer(TextureAssets.NpcHeadBoss);
            Main.ContentThatNeedsRenderTargets.Add(Main.BossNPCHeadRenderer);
            Main.ItemMapIconRenderer = new OutlinedTextureRenderer(TextureAssets.Item);
            Main.ContentThatNeedsRenderTargets.Add(Main.ItemMapIconRenderer);
            yield break;
        }
References System.Collections.Generic.List< T >.Add(), Terraria.Main.BossNPCHeadRenderer, Terraria.Main.ContentThatNeedsRenderTargets, Terraria.GameContent.TextureAssets.Item, Terraria.Main.ItemMapIconRenderer, Terraria.Testing.QuickLoad.Load(), Terraria.Initializers.AssetInitializer.Load(), System.Collections.IEnumerator.MoveNext(), Terraria.GameContent.TextureAssets.NpcHead, Terraria.GameContent.TextureAssets.NpcHeadBoss, Terraria.Main.splashTimer, and Terraria.Main.TownNPCHeadRenderer.