Terraria Decompiled: Terraria.Main.UpdateClient
UpdateClient()
static void Terraria.Main.UpdateClient () inline static private
Definition at line 65761 of file Main.cs.
        {
            if (Main.myPlayer == 255)
            {
                Netplay.Disconnect = true;
            }
            Main.netPlayCounter++;
            if (Main.netPlayCounter > 3600)
            {
                Main.netPlayCounter = 0;
            }
            if (Main.netPlayCounter % 420 == 0)
            {
                NetMessage.SendData(13, -1, -1, null, Main.myPlayer, 0f, 0f, 0f, 0, 0, 0);
            }
            if (Main.netPlayCounter % 900 == 0)
            {
                NetMessage.SendData(36, -1, -1, null, Main.myPlayer, 0f, 0f, 0f, 0, 0, 0);
                NetMessage.SendData(16, -1, -1, null, Main.myPlayer, 0f, 0f, 0f, 0, 0, 0);
                NetMessage.SendData(40, -1, -1, null, Main.myPlayer, 0f, 0f, 0f, 0, 0, 0);
            }
            if (Netplay.Connection.IsActive)
            {
                Netplay.Connection.TimeOutTimer++;
                if (!Main.stopTimeOuts && Netplay.Connection.TimeOutTimer > 7200)
                {
                    Main.statusText = Lang.inter[43].Value;
                    Netplay.Disconnect = true;
                }
            }
            for (int i = 0; i < 400; i++)
            {
                if (Main.item[i].active && Main.item[i].playerIndexTheItemIsReservedFor == Main.myPlayer)
                {
                    Main.item[i].FindOwner();
                }
            }
        }
References Terraria.WorldItem.active, Terraria.Netplay.Connection, Terraria.WorldItem.FindOwner(), Terraria.Lang.inter, Terraria.RemoteServer.IsActive, Terraria.Main.item, Terraria.Main.myPlayer, Terraria.Main.netPlayCounter, Terraria.WorldItem.playerIndexTheItemIsReservedFor, Terraria.NetMessage.SendData(), Terraria.Main.stopTimeOuts, Terraria.RemoteServer.TimeOutTimer, and Terraria.Localization.LocalizedText.Value.
Referenced by Terraria.Main.DoUpdateInWorld().