Terraria Decompiled: Terraria.Main.tileSolidTop
tileSolidTop
bool [] Terraria.Main.tileSolidTop = new bool[(int)TileID.Count] static
Definition at line 69898 of file Main.cs.
Referenced by Terraria.WorldGen.AddBuriedChest(), Terraria.NPC.AddKingSlimeTeleportCacheTiles(), Terraria.Liquid.AddWater(), Terraria.Collision.AdvancedTileCollision(), Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_006_Worms(), Terraria.NPC.AI_007_TownEntities(), Terraria.Projectile.AI_016_Bombs(), Terraria.NPC.AI_026_Unicorns(), Terraria.NPC.AI_037_Destroyer(), Terraria.Projectile.AI_062(), Terraria.Projectile.AI_113_TargetSticker(), Terraria.Projectile.AI_135_OgreStomp(), Terraria.WorldGen.AnchorValid(), Terraria.Collision.AnyCollision(), Terraria.Collision.AnyCollisionWithSpecificTiles(), Terraria.WorldGen.BottomEdgeCanBeAttachedTo(), Terraria.Collision.BuildTileContacts(), Terraria.Collision.CanHit(), Terraria.Collision.CanHitLine(), Terraria.Collision.CanHitWithCheck(), Terraria.TileObject.CanPlace(), Terraria.NPCSpawningFlagsForDualDungeons.CanScan(), Terraria.DelegateMethods.CastLightOpen(), Terraria.DelegateMethods.CastLightOpen_StopForSolids(), Terraria.DelegateMethods.CastLightOpen_StopForSolids_ScaleWithDistance(), Terraria.WorldGen.Check1x2Top(), Terraria.WorldGen.Check2x2(), Terraria.WorldGen.Check3x2(), Terraria.WorldGen.Check3x3(), Terraria.WorldGen.Check6x3(), Terraria.WorldGen.CheckAndAdjustMultiDirectionalTile(), Terraria.WorldGen.CheckBanner(), Terraria.WorldGen.CheckCatTail(), Terraria.WorldGen.CheckChand(), Terraria.Player.CheckDrowning(), Terraria.Utils.CheckForGoodTeleportationSpot(), Terraria.WorldGen.CheckLilyPad(), Terraria.Player.CheckSpawn_Internal(), Terraria.DelegateMethods.CheckStopForSolids(), Terraria.WorldGen.CheckTileBreakability(), Terraria.Projectile.CreateGroundExplosion(), Terraria.Projectile.CreateImpactExplosion(), Terraria.Liquid.DelWater(), Terraria.WorldGen.SecretSeed.DoErrorWorldGetRandomBlock(), Terraria.WorldGen.SecretSeed.DoErrorWorldShuffleBlocks(), Terraria.HitTile.DrawFreshAnimations(), Terraria.GameContent.Drawing.TileDrawing.DrawTile_LiquidBehindTile(), Terraria.Main.DrawTileCracks(), Terraria.WaterfallManager.DrawWaterfall(), Terraria.Collision.DrownCollision(), Terraria.DelegateMethods.EmitGolfCartDust_StopForSolids(), Terraria.WorldGen.EmptyLiquid(), Terraria.Mount.FindTileHeight(), Terraria.GameContent.Drawing.WallDrawing.FullTile(), Terraria.Physics.BallCollision.GetCollisionPointForTile(), Terraria.ID.ContentSamples.CreativeHelper.GetItemGroup(), Terraria.Collision.GetTileRotation(), Terraria.WorldGen.GrowCatTail(), Terraria.Collision.HitLine(), Terraria.Collision.HitTiles(), Terraria.Collision.HitTilesInACircle(), Terraria.Collision.HitWallSubstep(), Terraria.Main.Initialize_TileAndNPCData1(), Terraria.Main.Initialize_TileAndNPCData2(), Terraria.GameContent.Biomes.DeadMansChestBiome.IsGoodSpotsForExplosive(), Terraria.Physics.BallCollision.IsNeighborSolid(), Terraria.NPC.Spawner.IsValidSpawningGroundTile(), Terraria.GameContent.SmartCursorHelper.IsValidSpotForTorch(), Terraria.Player.ItemCheck_Shoot(), Terraria.Player.ItemCheck_UseBuckets(), Terraria.Player.ItemCheck_UseMiningTools_TryPoundingTile(), Terraria.WorldGen.LeftEdgeCanBeAttachedTo(), Terraria.Player.MinionRestTargetAim(), Terraria.Collision.noSlopeCollision(), Terraria.Main.oldDrawWater(), Terraria.TileObject.Place(), Terraria.WorldGen.Place1x2Top(), Terraria.WorldGen.Place2x2(), Terraria.WorldGen.Place3x2(), Terraria.WorldGen.Place3x3(), Terraria.WorldGen.Place6x3(), Terraria.WorldGen.PlaceBanner(), Terraria.WorldGen.PlaceCatTail(), Terraria.WorldGen.PlaceChand(), Terraria.WorldGen.placeLavaTrap(), Terraria.WorldGen.PlaceLilyPad(), Terraria.WorldGen.PlaceLiquid(), Terraria.WorldGen.PlaceOasis(), Terraria.WorldGen.PlaceSign(), Terraria.Player.PlaceThing_Tiles_BlockPlacementForAssortedThings(), Terraria.WorldGen.PlaceTile(), Terraria.WorldGen.ReplaceTile_IsValidSolid(), Terraria.WorldGen.RightEdgeCanBeAttachedTo(), Terraria.Liquid.SettleWaterAt(), Terraria.Main.SetupTileMerge(), Terraria.Collision.SlopeCollision(), Terraria.Collision.SolidCollision(), Terraria.Collision.SolidCollision(), Terraria.Collision.SolidFullTiles(), Terraria.WorldGen.SolidOrSlopedTile(), Terraria.NPC.SolidOrSlopedTileOrPlatform(), Terraria.WorldGen.SolidTile(), Terraria.WorldGen.SolidTile(), Terraria.WorldGen.SolidTile3(), Terraria.WorldGen.SolidTileAllowBottomSlope(), Terraria.WorldGen.SolidTileNoPlatforms(), Terraria.Collision.SolidTiles(), Terraria.Collision.SolidTiles(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsDownDashExplosion(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsFlint(), Terraria.Player.Spawn_DescendFromDefaultSpace(), Terraria.Player.Spawn_ForceClearArea(), Terraria.Player.Spawn_IsAreaValidSpawn(), Terraria.WorldGen.SpawnHomelessNPC(), Terraria.WorldGen.SpawnTravelNPC(), Terraria.DelegateMethods.SpreadLightOpen_StopForSolids(), Terraria.Physics.BallCollision.Step(), Terraria.GameContent.SmartCursorHelper.Step_BlocksFilling(), Terraria.GameContent.SmartCursorHelper.Step_BlocksLines(), Terraria.GameContent.SmartCursorHelper.Step_ForceCursorToAnyMinableThing(), Terraria.GameContent.SmartCursorHelper.Step_PaintRoller(), Terraria.GameContent.SmartCursorHelper.Step_Pickaxe_MineSolids(), Terraria.GameContent.SmartCursorHelper.Step_Walls(), Terraria.Collision.StepDown(), Terraria.Collision.StepUp(), Terraria.Collision.TileCollision(), Terraria.WorldGen.TileFrameCosmetic(), Terraria.WorldGen.TileFrameImportant(), Terraria.WorldGen.TopEdgeCanBeAttachedTo(), Terraria.Liquid.Update(), Terraria.Collision.WalkDownSlope(), Terraria.WorldGen.WaterCheck(), and Terraria.WorldGen.WillWaterPlacedHereStayPut().