Terraria Decompiled: Terraria.Main.HoverOverNPCs
HoverOverNPCs()
void Terraria.Main.HoverOverNPCs (Microsoft::Xna::Framework::Rectangle mouseRectangle) inline private
Definition at line 42961 of file Main.cs.
        {
            Player player = Main.player[Main.myPlayer];
            Microsoft.Xna.Framework.Rectangle worldRegion = TileReachCheckSettings.Simple.GetWorldRegion(player, 0);
            for (int i = 0; i < Main.maxNPCs; i++)
            {
                NPC npc = Main.npc[i];
                if (npc.active && !npc.CurrentlyShimmerTransparent())
                {
                    int type = npc.type;
                    this.LoadNPC(type);
                    npc.position += npc.netOffset;
                    Microsoft.Xna.Framework.Rectangle rectangle = new Microsoft.Xna.Framework.Rectangle((int)npc.Bottom.X - npc.frame.Width / 2, (int)npc.Bottom.Y - npc.frame.Height, npc.frame.Width, npc.frame.Height);
                    if (npc.type >= 87 && npc.type <= 92)
                    {
                        rectangle = new Microsoft.Xna.Framework.Rectangle((int)((double)npc.position.X + (double)npc.width * 0.5 - 32.0), (int)((double)npc.position.Y + (double)npc.height * 0.5 - 32.0), 64, 64);
                    }
                    if (npc.type == 677)
                    {
                        rectangle = Utils.CenteredRectangle(npc.Center, new Vector2(20f, 20f));
                    }
                    if (npc.type == 696 || npc.type == 695)
                    {
                        rectangle = Utils.CenteredRectangle(npc.Bottom - new Vector2((float)(npc.direction * -10), 20f), new Vector2(60f, 40f));
                    }
                    bool flag = mouseRectangle.Intersects(rectangle);
                    bool flag2 = flag || (Main.SmartInteractShowingGenuine && Main.SmartInteractNPC == i);
                    if (flag2 && ((npc.type != 85 && npc.type != 341 && npc.type != 629 && npc.aiStyle != 87) || npc.ai[0] != 0f) && (npc.type != 694 || npc.ai[3] != 3f) && npc.type != 690 && npc.type != 488)
                    {
                        if (npc.type == 685)
{
                            if (!Main.mouseText)
{
                                player.cursorItemIconEnabled = true;
                                player.cursorItemIconID = 327;
                                player.cursorItemIconText = "";
                            }
                            if (!player.dead)
{
                                player.noThrow = 4;
                                if (Main.mouseRight && Main.npcChatRelease)
{
                                    Main.npcChatRelease = false;
                                    if (PlayerInput.UsingGamepad)
{
                                        player.releaseInventory = false;
                                    }
                                    if (player.talkNPC != i && !player.tileInteractionHappened && Main.TryFreeingElderSlime(i))
{
                                        NPC.TransformElderSlime(i);
                                        SoundEngine.PlaySound(22, -1, -1, 1, 1f, 0f);
                                    }
                                }
                            }
                        }
                        else
{
                            bool flag3 = Main.SmartInteractShowingGenuine && Main.SmartInteractNPC == i;
                            if (npc.townNPC || npc.type == 105 || npc.type == 106 || npc.type == 123 || npc.type == 354 || npc.type == 376 || npc.type == 579 || npc.type == 453 || npc.type == 589)
{
                                Microsoft.Xna.Framework.Rectangle rectangle2 = new Microsoft.Xna.Framework.Rectangle((int)npc.position.X, (int)npc.position.Y, npc.width, npc.height);
                                if (worldRegion.Intersects(rectangle2))
{
                                    flag3 = true;
                                }
                            }
                            if (player.ownedProjectileCounts[651] > 0)
{
                                flag3 = false;
                            }
                            if (player.stinky)
{
                                flag3 = false;
                            }
                            if (player.mouseInterface)
{
                                flag3 = false;
                            }
                            if (flag3 && !player.dead)
{
                                player.noThrow = 4;
                                Main.HoveringOverAnNPC = true;
                                this.currentNPCShowingChatBubble = i;
                                if (Main.mouseRight && Main.npcChatRelease)
{
                                    Main.npcChatRelease = false;
                                    if (PlayerInput.UsingGamepad)
{
                                        player.releaseInventory = false;
                                    }
                                    if (player.talkNPC != i && !player.tileInteractionHappened)
{
                                        IngameUIWindows.CloseAll(true);
                                        player.dropItemCheck();
                                        player.SetTalkNPC(i);
                                        Main.npcChatText = npc.GetChat();
                                        SoundEngine.PlaySound(24, -1, -1, 1, 1f, 0f);
                                    }
                                }
                            }
                            if (flag && !Main.mouseText)
{
                                player.cursorItemIconEnabled = false;
                                string text = npc.GivenOrTypeName;
                                int num = i;
                                if (npc.realLife >= 0)
{
                                    num = npc.realLife;
                                }
                                if (Main.npc[num].lifeMax > 1 && !Main.npc[num].dontTakeDamage)
{
                                    text = string.Concat(new object[]
{
                                        text,
                                        ": ",
                                        Main.npc[num].life,
                                        "/",
                                        Main.npc[num].lifeMax
                                    });
                                }
                                this.MouseTextHackZoom(text, null);
                                Main.mouseText = true;
                                npc.position -= npc.netOffset;
                                return;
                            }
                            if (flag2)
{
                                npc.position -= npc.netOffset;
                                return;
                            }
                        }
                    }
                    npc.position -= npc.netOffset;
                }
            }
        }
References Terraria.NPC.active, Terraria.NPC.ai, Terraria.NPC.aiStyle, Terraria.Entity.Bottom, Terraria.Entity.Center, Terraria.Utils.CenteredRectangle(), Terraria.UI.IngameUIWindows.CloseAll(), Terraria.NPC.CurrentlyShimmerTransparent(), Terraria.Player.dead, Terraria.Entity.direction, Terraria.NPC.dontTakeDamage, Terraria.Player.dropItemCheck(), Terraria.NPC.frame, Terraria.NPC.GetChat(), Terraria.DataStructures.TileReachCheckSettings.GetWorldRegion(), Terraria.NPC.GivenOrTypeName, Microsoft.Xna.Framework.Rectangle.Height, Terraria.Entity.height, int, Microsoft.Xna.Framework.Rectangle.Intersects(), Terraria.NPC.life, Terraria.NPC.lifeMax, Terraria.Main.maxNPCs, Terraria.Player.mouseInterface, Terraria.Main.mouseRight, Terraria.Main.mouseText, Terraria.Main.myPlayer, Terraria.NPC.netOffset, Terraria.Main.npc, Terraria.Main.npcChatRelease, Terraria.Player.ownedProjectileCounts, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.NPC.realLife, Terraria.Player.SetTalkNPC(), Terraria.DataStructures.TileReachCheckSettings.Simple, Terraria.Player.stinky, Terraria.Player.talkNPC, System.text, Terraria.Player.tileInteractionHappened, Terraria.NPC.townNPC, Terraria.NPC.TransformElderSlime(), Terraria.Main.TryFreeingElderSlime(), Terraria.NPC.type, Terraria.GameInput.PlayerInput.UsingGamepad, Microsoft.Xna.Framework.Rectangle.Width, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.