Terraria Decompiled: Terraria.Main.LoadSettings
LoadSettings()
void Terraria.Main.LoadSettings () inline protected
Definition at line 2343 of file Main.cs.
        {
            if (File.Exists(Main.SavePath + Path.DirectorySeparatorChar.ToString() + "config.dat"))
            {
                this.OpenLegacySettings();
                if (Main.SaveSettings())
                {
                    File.Delete(Main.SavePath + Path.DirectorySeparatorChar.ToString() + "config.dat");
                }
                return;
            }
            Main.IsInTheMiddleOfLoadingSettings = true;
            Preferences configuration = Main.Configuration;
            configuration.Load();
            int num = 0;
            configuration.Get<int>("LastLaunchedVersion", ref num);
            bool flag = false;
            if (num < 219)
            {
                flag = true;
            }
            if (!flag)
            {
                configuration.Get<bool>("ResetDefaultUIScale", ref Main.shouldSetDefaultUIScale);
                configuration.Get<bool>("Fullscreen", ref Main.startFullscreen);
                configuration.Get<bool>("WindowMaximized", ref Main.screenMaximized);
                configuration.Get<bool>("WindowBorderless", ref Main.screenBorderless);
            }
            Main.PendingBorderlessState = Main.screenBorderless;
            Main.screenBorderlessPendingResizes = (Main.screenBorderless ? 6 : 0);
            if (Platform.IsWindows && !Main.dedServ)
            {
                Form form = Control.FromHandle(Main.instance.Window.Handle);
                if (Main.screenBorderless)
                {
                    Main.SetBorderlessFormStyle(form);
                }
                else if (Main.screenMaximized)
                {
                    form.FormBorderStyle = FormBorderStyle.Sizable;
                    form.WindowState = FormWindowState.Maximized;
                }
                else
                {
                    form.FormBorderStyle = FormBorderStyle.Sizable;
                }
                form.BringToFront();
            }
            int preferredBackBufferWidth = Main.graphics.PreferredBackBufferWidth;
            int preferredBackBufferHeight = Main.graphics.PreferredBackBufferHeight;
            configuration.Get<int>("DisplayWidth", ref preferredBackBufferWidth);
            configuration.Get<int>("DisplayHeight", ref preferredBackBufferHeight);
            Main.LastLoadedResolution = new Microsoft.Xna.Framework.Point(preferredBackBufferWidth, preferredBackBufferHeight);
            if (!Main.startFullscreen)
            {
                if (Main.PendingBorderlessState)
                {
                    Main.screenBorderlessPendingResizes = 1;
                }
                Main.SetDisplayMode(preferredBackBufferWidth, preferredBackBufferHeight, false);
                Main.TryPickingDefaultUIScale((float)preferredBackBufferHeight);
            }
            configuration.Get<bool>("SmartCursorToggle", ref Main.cSmartCursorModeIsToggleAndNotHold);
            configuration.Get<bool>("MapEnabled", ref Main.mapEnabled);
            configuration.Get<int>("InvasionBarMode", ref Main.invasionProgressMode);
            configuration.Get<bool>("AutoSave", ref Main.autoSave);
            configuration.Get<bool>("AutoPause", ref Main.autoPause);
            Main._needsLanguageSelect = !configuration.Contains("Language");
            string text = configuration.Get<string>("Language", "en-US");
            int num2 = 0;
            if (int.TryParse(text, out num2))
            {
                LanguageManager.Instance.SetLanguage(num2);
                this.SetTitle(true);
            }
            else
            {
                LanguageManager.Instance.SetLanguage(text);
                this.SetTitle(true);
            }
            configuration.Get<bool>("PlacementPreview", ref Main.placementPreview);
            configuration.Get<bool>("GoreVisualsAllowed", ref ChildSafety.Disabled);
            configuration.Get<bool>("FlashyEffectsWorld", ref Main.FlashyEffectsWorld);
            configuration.Get<bool>("FlashyEffectsInterface", ref Main.FlashyEffectsInterface);
            configuration.Get<bool>("PlayWhenUnfocused", ref Main.SettingPlayWhenUnfocused);
            if (!flag)
            {
                configuration.Get<float>("VolumeSound", ref Main.soundVolume);
                configuration.Get<float>("VolumeAmbient", ref Main.ambientVolume);
                configuration.Get<float>("VolumeMusic", ref Main.musicVolume);
            }
            configuration.Get<string>("KeyFavoriteModifier", ref Main.cFavoriteKey);
            Microsoft.Xna.Framework.Input.Keys keys;
            if (Enum.TryParse<Microsoft.Xna.Framework.Input.Keys>(Main.cFavoriteKey, out keys))
            {
                Main.FavoriteKey = keys;
            }
            GlyphTagHandler.GlyphStyle = configuration.Get<int>("ControllerGlyphs", 0);
            if (GlyphTagHandler.GlyphStyle < 0 || GlyphTagHandler.GlyphStyle > 2)
            {
                GlyphTagHandler.GlyphStyle = 0;
            }
            if (!flag)
            {
                configuration.Get<int>("GraphicsQuality", ref Main.qaStyle);
                configuration.Get<bool>("BackgroundEnabled", ref Main.BackgroundEnabled);
            }
            if (configuration.GetAllKeys().Contains("FrameSkip"))
            {
                bool flag2 = false;
                configuration.Get<bool>("FrameSkip", ref flag2);
                if (!flag2)
                {
                    Main.FrameSkipMode = FrameSkipMode.Subtle;
                }
                else
                {
                    Main.FrameSkipMode = FrameSkipMode.On;
                }
            }
            int num3 = (int)Main.FrameSkipMode;
            configuration.Get<int>("FrameSkipMode", ref num3);
            if (num3 < 0)
            {
                num3 = 0;
            }
            if (num3 > 2)
            {
                num3 = 2;
            }
            Main.FrameSkipMode = (FrameSkipMode)num3;
            int mode = (int)Lighting.Mode;
            if (!flag)
            {
                configuration.Get<int>("LightingMode", ref mode);
            }
            Lighting.Mode = (LightMode)mode;
            configuration.Get<bool>("UnlockMusicSwap", ref Main.TOWMusicUnlocked);
            configuration.Get<float>("Parallax", ref Main.caveParallax);
            Main.bgScroll = (int)((1f - Main.caveParallax) * 500f);
            configuration.Get<int>("BackgroundParallax", ref Main.bgScroll);
            Main.caveParallax = 1f - (float)Main.bgScroll / 500f;
            configuration.Get<bool>("ShowItemText", ref Main.showItemText);
            configuration.Get<string>("ClientUUID", ref Main.clientUUID);
            configuration.Get<bool>("UseSmartCursorForCommonBlocks", ref Player.SmartCursorSettings.SmartBlocksEnabled);
            configuration.Get<bool>("UseSmartAxeAfterSmartPickaxe", ref Player.SmartCursorSettings.SmartAxeAfterPickaxe);
            configuration.Get<bool>("SmartCursorHoldCanReleaseMidUse", ref Player.SmartCursorSettings.SmartCursorHoldCanReleaseMidUse);
            if (!flag)
            {
                configuration.Get<bool>("DisableLeftShiftTrashCan", ref ItemSlot.Options.DisableLeftShiftTrashCan);
            }
            if (!flag)
            {
                configuration.Get<bool>("DisableQuickTrash", ref ItemSlot.Options.DisableQuickTrash);
            }
            configuration.Get<bool>("HidePasswords", ref Main.HidePassword);
            configuration.Get<bool>("HighlightNewItems", ref ItemSlot.Options.HighlightNewItems);
            configuration.Get<bool>("ReverseUpDownForArmorSetBonuses", ref Main.ReversedUpDownArmorSetBonuses);
            configuration.Get<bool>("MouseShowBuildingGrid", ref Main.MouseShowBuildingGrid);
            configuration.Get<bool>("AllowUnfocusedInputOnGamepad", ref Main.AllowUnfocusedInputOnGamepad);
            configuration.Get<bool>("GamepadDisableInstructionsDisplay", ref Main.GamepadDisableInstructionsDisplay);
            configuration.Get<bool>("SettingDontScaleMainMenuUp", ref Main.SettingDontScaleMainMenuUp);
            configuration.Get<int>("WorldRollbacksToKeep", ref Main.WorldRollingBackupsCountToKeep);
            configuration.Get<int>("TeamNameplateDistance", ref Main.teamNamePlateDistance);
            if (num < 230)
            {
                configuration.Get<int>("MultiplayerNPCSmoothingRange", ref Main.multiplayerNPCSmoothingRange);
            }
            configuration.Get<bool>("UseStormEffect", ref Main.UseStormEffects);
            configuration.Get<bool>("ForegroundSunlightEffects", ref Main.ForegroundSunlightEffects);
            configuration.Get<bool>("UseHeatDistortion", ref Main.UseHeatDistortion);
            configuration.Get<int>("WaveQuality", ref Main.WaveQuality);
            if (Main.WaveQuality > 3)
            {
                Main.WaveQuality = 3;
            }
            if (Main.WaveQuality < 0)
            {
                Main.WaveQuality = 0;
            }
            Dictionary<string, byte> dictionary = new Dictionary<string, byte>();
            configuration.Get<Dictionary<string, byte>>("MouseColor", ref dictionary);
            byte b;
            if (dictionary.TryGetValue("R", out b))
            {
                Main.mouseColor.R = b;
            }
            if (dictionary.TryGetValue("G", out b))
            {
                Main.mouseColor.G = b;
            }
            if (dictionary.TryGetValue("B", out b))
            {
                Main.mouseColor.B = b;
            }
            dictionary.Clear();
            configuration.Get<Dictionary<string, byte>>("MouseBorderColor", ref dictionary);
            if (dictionary.TryGetValue("R", out b))
            {
                Main.MouseBorderColor.R = b;
            }
            if (dictionary.TryGetValue("G", out b))
            {
                Main.MouseBorderColor.G = b;
            }
            if (dictionary.TryGetValue("B", out b))
            {
                Main.MouseBorderColor.B = b;
            }
            if (dictionary.TryGetValue("A", out b))
            {
                Main.MouseBorderColor.A = b;
            }
            configuration.Get<bool>("QuickLaunch", ref Main.SkipAssemblyLoad);
            configuration.Get<bool>("AssetFileWatcherEnabled", ref Main.Setting_AssetFileWatcherEnabled);
            if (!flag)
            {
                Main.GameZoomTarget = configuration.Get<float>("Zoom", 1f);
            }
            if (!flag)
            {
                Main.UIScale = configuration.Get<float>("UIScale", Platform.Get<IWindowService>().GetScaling());
            }
            if (Main.newDefaultUIScale > 0f)
            {
                Main.UIScale = Main.newDefaultUIScale;
                Main.newDefaultUIScale = 0f;
            }
            Main.MapScale = MathHelper.Clamp(configuration.Get<float>("MapScale", Main.InitialMapScale), 0.5f, 1f);
            int num4 = -1;
            configuration.Get<int>("LockOnPriority", ref num4);
            if (num4 < 0)
            {
                num4 = 0;
            }
            if (num4 > 2)
            {
                num4 = 2;
            }
            LockOnHelper.UseMode = (LockOnHelper.LockOnMode)num4;
            if (LockOnHelper.UseMode == LockOnHelper.LockOnMode.FocusTarget)
            {
                LockOnHelper.UseMode = LockOnHelper.LockOnMode.ThreeDS;
            }
            Main.TitleMusicStyle titleMusicStyle;
            if (Enum.TryParse<Main.TitleMusicStyle>(configuration.Get<string>("TitleMusic", "Current"), out titleMusicStyle))
            {
                Main.titleMusicStyle = titleMusicStyle;
                if (Main.titleMusicStyle == Main.TitleMusicStyle.Random)
                {
                    Main.titleMusicStyleRandom = (Main.TitleMusicStyle)new UnifiedRandom((int)DateTime.Now.Ticks).Next(3);
                }
            }
            configuration.Get<bool>("InvisibleCursorForGamepad", ref Main.InvisibleCursorForGamepad);
            GameNotificationType gameNotificationType;
            if (Enum.TryParse<GameNotificationType>(configuration.Get<string>("FlashIconForEvents", "All"), out gameNotificationType))
            {
                Main._flashNotificationType = gameNotificationType;
            }
            if (!flag)
            {
                string text2 = configuration.Get<string>("DisplayScreen", "");
                Main._windowMover.TryMovingToScreen(text2);
                Main.ThrottleWhenInactive = configuration.Get<bool>("ThrottleWhenInactive", true);
                Main.UnpinFromCore0 = configuration.Get<bool>("UnpinFromCore0", false);
                if (Main.UnpinFromCore0 && Platform.IsWindows)
                {
                    WindowsPerformanceDiagnostics.UnpinFromCore0();
                }
            }
            if (!flag)
            {
                configuration.Get<bool>("Support4K", ref Main.Support4K);
            }
            configuration.Get<bool>("UseExperimentalFeatures", ref Main.UseExperimentalFeatures);
            configuration.Get<bool>("SettingsUnlock_WorldEvil", ref Main.SettingsUnlock_WorldEvil);
            configuration.Get<bool>("SettingsEnabled_MinersWobble", ref Main.SettingsEnabled_MinersWobble);
            configuration.Get<bool>("SettingBlockGamepadsEntirely", ref Main.SettingBlockGamepadsEntirely);
            configuration.Get<bool>("SettingsEnabled_OpaqueBoxBehindTooltips", ref Main.SettingsEnabled_OpaqueBoxBehindTooltips);
            configuration.Get<bool>("SettingsEnabled_TilesSwayInWind", ref Main.SettingsEnabled_TilesSwayInWind);
            configuration.Get<bool>("SettingsEnabled_AutoReuseAllItems", ref Main.SettingsEnabled_AutoReuseAllItems);
            configuration.Get<DoorOpeningHelper.DoorAutoOpeningPreference>("DoorAutoOpeningMode", ref DoorOpeningHelper.PreferenceSettings);
            configuration.Get<Player.Settings.HoverControlMode>("HoverControlMode", ref Player.Settings.HoverControl);
            configuration.Get<Player.Settings.DashPreference>("DashControlMode", ref Player.Settings.DashControl);
            configuration.Get<Player.Settings.CraftingGridMode>("CraftingControlMode", ref Player.Settings.CraftingGridControl);
            configuration.Get<Player.Settings.StackToNearbyChestsMode>("StackToChestsPreferredMode", ref Player.Settings.StackToChestsPreferredMode);
            configuration.Get<bool>("CraftFromNearbyChests", ref Player.Settings.CraftFromNearbyChests);
            configuration.Get<Main.DialoguePortraitDrawOption>("PortraitPreference", ref Main.DialoguePortraitPreference);
            configuration.Get<bool>("UseScreenShake", ref Main.UseScreenShake);
            JArray jarray = configuration.Get<JArray>("SecretSeeds", new JArray());
            try
            {
                if (jarray != null && jarray.Count != 0)
                {
                    SecretSeedsTracker.SetstringsFromConfig(jarray.ToObject<List<string>>());
                }
            }
            catch (JsonReaderException ex)
            {
                Console.WriteLine("Failed to parse configuration entry for secret seed list. {0}", ex);
            }
            if (num <= 162)
            {
                bool flag3 = false;
                uint num5 = 0U;
                configuration.Get<bool>("ThickMouseEdges", ref flag3);
                if (flag3)
                {
                    configuration.Get<uint>("ThickMouseEdgesPackedColor", ref num5);
                    Main.MouseBorderColor.PackedValue = num5;
                    Main.mouseColor.R = configuration.Get<byte>("MouseColorR", Main.mouseColor.R);
                    Main.mouseColor.G = configuration.Get<byte>("MouseColorG", Main.mouseColor.G);
                    Main.mouseColor.B = configuration.Get<byte>("MouseColorB", Main.mouseColor.B);
                }
            }
            if (num <= 162)
            {
                configuration.Get<string>("KeyUp", ref Main.cUp);
                configuration.Get<string>("KeyDown", ref Main.cDown);
                configuration.Get<string>("KeyLeft", ref Main.cLeft);
                configuration.Get<string>("KeyRight", ref Main.cRight);
                configuration.Get<string>("KeyJump", ref Main.cJump);
                configuration.Get<string>("KeyThrowItem", ref Main.cThrowItem);
                configuration.Get<string>("KeyInventory", ref Main.cInv);
                configuration.Get<string>("KeyQuickHeal", ref Main.cHeal);
                configuration.Get<string>("KeyQuickMana", ref Main.cMana);
                configuration.Get<string>("KeyQuickBuff", ref Main.cBuff);
                configuration.Get<string>("KeyUseHook", ref Main.cHook);
                configuration.Get<string>("KeyAutoSelect", ref Main.cTorch);
                configuration.Get<string>("KeySmartCursor", ref Main.cSmart);
                configuration.Get<string>("KeyMount", ref Main.cMount);
                configuration.Get<string>("KeyMapStyle", ref Main.cMapStyle);
                configuration.Get<string>("KeyFullscreenMap", ref Main.cMapFull);
                configuration.Get<string>("KeyMapZoomIn", ref Main.cMapZoomIn);
                configuration.Get<string>("KeyMapZoomOut", ref Main.cMapZoomOut);
                configuration.Get<string>("KeyMapAlphaUp", ref Main.cMapAlphaUp);
                configuration.Get<string>("KeyMapAlphaDown", ref Main.cMapAlphaDown);
                PlayerInput.CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus["Up"] = new List<string> { Main.cUp };
                PlayerInput.CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus["Down"] = new List<string> { Main.cDown };
                PlayerInput.CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus["Left"] = new List<string> { Main.cLeft };
                PlayerInput.CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus["Right"] = new List<string> { Main.cRight };
                PlayerInput.CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus["Jump"] = new List<string> { Main.cJump };
                PlayerInput.CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus["Throw"] = new List<string> { Main.cThrowItem };
                PlayerInput.CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus["Inventory"] = new List<string> { Main.cInv };
                PlayerInput.CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus["QuickHeal"] = new List<string> { Main.cHeal };
                PlayerInput.CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus["QuickMana"] = new List<string> { Main.cMana };
                PlayerInput.CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus["QuickBuff"] = new List<string> { Main.cBuff };
                PlayerInput.CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus["Grapple"] = new List<string> { Main.cHook };
                PlayerInput.CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus["SmartSelect"] = new List<string> { Main.cTorch };
                PlayerInput.CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus["SmartCursor"] = new List<string> { Main.cSmart };
                PlayerInput.CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus["QuickMount"] = new List<string> { Main.cMount };
                PlayerInput.CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus["MapStyle"] = new List<string> { Main.cMapStyle };
                PlayerInput.CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus["MapFull"] = new List<string> { Main.cMapFull };
                PlayerInput.CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus["MapZoomIn"] = new List<string> { Main.cMapZoomIn };
                PlayerInput.CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus["MapZoomOut"] = new List<string> { Main.cMapZoomOut };
                PlayerInput.CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus["MapAlphaUp"] = new List<string> { Main.cMapAlphaUp };
                PlayerInput.CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus["MapAlphaDown"] = new List<string> { Main.cMapAlphaDown };
            }
            PlayerInput.Load();
            if (num < 165)
            {
                try
                {
                    PlayerInput.ManageVersion_1_3();
                }
                catch (Exception)
                {
                }
            }
            Main.mouseColorSlider.SetHSL(Main.mouseColor);
            Main.mouseBorderColorSlider.SetHSL(Main.MouseBorderColor);
            Main.mouseBorderColorSlider.Alpha = (float)Main.MouseBorderColor.A / 255f;
            if (num != 319)
            {
                Main.SaveSettings();
            }
            Main.IsInTheMiddleOfLoadingSettings = false;
        }
References Terraria.Main._windowMover, Terraria.Main.AllowUnfocusedInputOnGamepad, Terraria.Main.ambientVolume, Terraria.Main.autoPause, Terraria.Main.autoSave, Terraria.Main.BackgroundEnabled, Terraria.Main.bgScroll, Terraria.Main.caveParallax, Terraria.Main.cBuff, Terraria.Main.cDown, Terraria.Main.cFavoriteKey, Terraria.Main.cHeal, Terraria.Main.cHook, Terraria.Main.cInv, Terraria.Main.cJump, Microsoft.Xna.Framework.MathHelper.Clamp(), System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), Terraria.Main.cLeft, Terraria.Main.clientUUID, Terraria.Main.cMana, Terraria.Main.cMapAlphaDown, Terraria.Main.cMapAlphaUp, Terraria.Main.cMapFull, Terraria.Main.cMapStyle, Terraria.Main.cMapZoomIn, Terraria.Main.cMapZoomOut, Terraria.Main.cMount, Terraria.Main.Configuration, Terraria.IO.Preferences.Contains(), System.Collections.Generic.List< T >.Contains(), Terraria.Player.Settings.CraftFromNearbyChests, Terraria.Player.Settings.CraftingGridControl, Terraria.Main.cRight, Terraria.Main.cSmart, Terraria.Main.cSmartCursorModeIsToggleAndNotHold, Terraria.Main.cThrowItem, Terraria.Main.cTorch, Terraria.Main.cUp, Terraria.GameInput.PlayerInput.CurrentProfile, Terraria.Player.Settings.DashControl, Terraria.Main.dedServ, System.IO.File.Delete(), Terraria.Main.DialoguePortraitPreference, System.dictionary, System.IO.Path.DirectorySeparatorChar, Terraria.GameContent.ChildSafety.Disabled, Terraria.UI.ItemSlot.Options.DisableLeftShiftTrashCan, Terraria.UI.ItemSlot.Options.DisableQuickTrash, System.IO.File.Exists(), Terraria.Main.FlashyEffectsInterface, Terraria.Main.FlashyEffectsWorld, Terraria.Main.ForegroundSunlightEffects, Terraria.Main.FrameSkipMode, Terraria.Control.FromHandle(), Terraria.Main.GamepadDisableInstructionsDisplay, Terraria.IO.Preferences.GetAllKeys(), Terraria.GameContent.UI.Chat.GlyphTagHandler.GlyphStyle, Terraria.Main.graphics, Microsoft.Xna.Framework.GameWindow.Handle, Terraria.Main.HidePassword, Terraria.UI.ItemSlot.Options.HighlightNewItems, Terraria.Player.Settings.HoverControl, Terraria.Main.InitialMapScale, Terraria.GameInput.PlayerInputProfile.InputModes, Terraria.Localization.LanguageManager.Instance, Terraria.Main.instance, int, Terraria.Main.invasionProgressMode, Terraria.Main.InvisibleCursorForGamepad, ReLogic.OS.Platform.IsWindows, Terraria.GameInput.PlayerInput.Load(), Terraria.IO.Preferences.Load(), Terraria.GameInput.PlayerInput.ManageVersion_1_3(), Terraria.Main.mapEnabled, System.mode, Terraria.Lighting.Mode, Terraria.Main.MouseBorderColor, Terraria.Main.mouseBorderColorSlider, Terraria.Main.mouseColor, Terraria.Main.mouseColorSlider, Terraria.Main.MouseShowBuildingGrid, Terraria.Main.multiplayerNPCSmoothingRange, Terraria.Main.musicVolume, Terraria.Main.newDefaultUIScale, System.DateTime.Now, Terraria.Main.OpenLegacySettings(), Terraria.Main.PendingBorderlessState, Terraria.Main.placementPreview, Terraria.GameContent.DoorOpeningHelper.PreferenceSettings, Microsoft.Xna.Framework.GraphicsDeviceManager.PreferredBackBufferHeight, Microsoft.Xna.Framework.GraphicsDeviceManager.PreferredBackBufferWidth, Terraria.Main.qaStyle, Terraria.Main.ReversedUpDownArmorSetBonuses, Terraria.Main.SavePath, Terraria.Main.SaveSettings(), Terraria.Main.screenBorderless, Terraria.Main.screenMaximized, Terraria.Main.SetBorderlessFormStyle(), Terraria.Main.SetDisplayMode(), Terraria.DataStructures.ColorSlidersSet.SetHSL(), Terraria.Localization.LanguageManager.SetLanguage(), Terraria.GameContent.SecretSeedsTracker.SetstringsFromConfig(), Terraria.Main.Setting_AssetFileWatcherEnabled, Terraria.Main.SettingBlockGamepadsEntirely, Terraria.Main.SettingDontScaleMainMenuUp, Terraria.Main.SettingPlayWhenUnfocused, Terraria.Main.SettingsEnabled_AutoReuseAllItems, Terraria.Main.SettingsEnabled_MinersWobble, Terraria.Main.SettingsEnabled_OpaqueBoxBehindTooltips, Terraria.Main.SettingsEnabled_TilesSwayInWind, Terraria.Main.SettingsUnlock_WorldEvil, Terraria.Main.SetTitle(), Terraria.Main.shouldSetDefaultUIScale, Terraria.Main.showItemText, Terraria.Main.SkipAssemblyLoad, Terraria.Player.SmartCursorSettings.SmartAxeAfterPickaxe, Terraria.Player.SmartCursorSettings.SmartBlocksEnabled, Terraria.Player.SmartCursorSettings.SmartCursorHoldCanReleaseMidUse, Terraria.Main.soundVolume, Terraria.Player.Settings.StackToChestsPreferredMode, Terraria.Main.startFullscreen, Terraria.Main.Support4K, Terraria.Main.teamNamePlateDistance, System.text, System.DateTime.Ticks, Terraria.Main.titleMusicStyle, Terraria.Main.TOWMusicUnlocked, Terraria.Graphics.WindowStateController.TryMovingToScreen(), System.Enum.TryParse(), Terraria.Main.TryPickingDefaultUIScale(), Microsoft.Xna.Framework.Input.U, Terraria.Main.UnpinFromCore0, Terraria.Testing.WindowsPerformanceDiagnostics.UnpinFromCore0(), Terraria.Main.UseExperimentalFeatures, Terraria.Main.UseHeatDistortion, Terraria.GameInput.LockOnHelper.UseMode, Terraria.Main.UseScreenShake, Terraria.Main.UseStormEffects, Terraria.Main.WaveQuality, Microsoft.Xna.Framework.Game.Window, Terraria.Main.WorldRollingBackupsCountToKeep, and System.Console.WriteLine().