Terraria Decompiled: Terraria.Main.LoadDedConfig
LoadDedConfig()
void Terraria.Main.LoadDedConfig (string configPath) inline
Definition at line 3056 of file Main.cs.
        {
            if (File.Exists(configPath))
            {
                using (StreamReader streamReader = new StreamReader(configPath))
                {
                    string text = string.Empty;
                    string text2;
                    while ((text2 = streamReader.ReadLine()) != null)
                    {
                        try
{
                            if (text2.Length > 6 && text2.Substring(0, 6).ToLower() == "world=")
{
                                string text3 = text2.Substring(6);
                                string text4;
                                try
{
                                    text4 = Platform.Get<IPathService>().ExpandPathVariables(text3);
                                    new FileInfo(text4);
                                }
                                catch
{
                                    continue;
                                }
                                Main.autoGenFileLocation = text4;
                                if (!File.Exists(text4))
{
                                    Main.ActiveWorldFileData = new WorldFileData(text4, false);
                                }
                                else
{
                                    WorldFile.GetAllMetadata(text4, false).SetAsActive();
                                }
                            }
                            if (text2.Length > 5 && text2.Substring(0, 5).ToLower() == "port=")
{
                                string text5 = text2.Substring(5);
                                try
{
                                    Netplay.ListenPort = Convert.ToInt32(text5);
                                }
                                catch
{
                                }
                            }
                            if (text2.Length > 21 && text2.Substring(0, 21).ToLower() == "worldrollbackstokeep=")
{
                                string text6 = text2.Substring(21);
                                try
{
                                    Main.WorldRollingBackupsCountToKeep = Convert.ToInt32(text6);
                                }
                                catch
{
                                }
                            }
                            if (text2.Length > 11 && text2.Substring(0, 11).ToLower() == "maxplayers=")
{
                                string text7 = text2.Substring(11);
                                try
{
                                    int num = Convert.ToInt32(text7);
                                    if (num <= 255 && num >= 1)
{
                                        this.SetNetPlayers(num);
                                    }
                                }
                                catch
{
                                }
                            }
                            if (text2.Length > 11 && text2.Substring(0, 9).ToLower() == "priority=" && !Program.LaunchParameters.ContainsKey("-forcepriority"))
{
                                string text8 = text2.Substring(9);
                                try
{
                                    int num2 = Convert.ToInt32(text8);
                                    if (num2 >= 0 && num2 <= 5)
{
                                        Process currentProcess = Process.GetCurrentProcess();
                                        if (num2 == 0)
{
                                            currentProcess.PriorityClass = ProcessPriorityClass.RealTime;
                                        }
                                        else if (num2 == 1)
{
                                            currentProcess.PriorityClass = ProcessPriorityClass.High;
                                        }
                                        else if (num2 == 2)
{
                                            currentProcess.PriorityClass = ProcessPriorityClass.AboveNormal;
                                        }
                                        else if (num2 == 3)
{
                                            currentProcess.PriorityClass = ProcessPriorityClass.Normal;
                                        }
                                        else if (num2 == 4)
{
                                            currentProcess.PriorityClass = ProcessPriorityClass.BelowNormal;
                                        }
                                        else if (num2 == 5)
{
                                            currentProcess.PriorityClass = ProcessPriorityClass.Idle;
                                        }
                                    }
                                }
                                catch
{
                                }
                            }
                            if (text2.Length > 9 && text2.Substring(0, 9).ToLower() == "password=")
{
                                Netplay.ServerPassword = Main.ConvertFromSafeArgument(text2.Substring(9));
                            }
                            if (text2.Length > 5 && text2.Substring(0, 5).ToLower() == "motd=")
{
                                Main.motd = text2.Substring(5);
                            }
                            if (text2.Length > 5 && text2.Substring(0, 5).ToLower() == "lang=")
{
                                string text9 = text2.Substring(5);
                                LanguageManager.Instance.SetLanguage(Convert.ToInt32(text9));
                            }
                            if (text2.Length > 9 && text2.Substring(0, 9).ToLower() == "language=")
{
                                string text10 = text2.Substring(9);
                                LanguageManager.Instance.SetLanguage(text10);
                            }
                            if (text2.Length >= 10 && text2.Substring(0, 10).ToLower() == "worldpath=")
{
                                string text11 = text2.Substring(10);
                                Main.WorldPath = Platform.Get<IPathService>().ExpandPathVariables(text11);
                            }
                            if (text2.Length >= 10 && text2.Substring(0, 10).ToLower() == "worldname=")
{
                                Main.worldName = text2.Substring(10);
                            }
                            if (text2.Length >= 5 && text2.Substring(0, 5).ToLower() == "seed=")
{
                                Main.AutogenSeedName = text2.Substring(5);
                            }
                            if (text2.Length > 8 && text2.Substring(0, 8).ToLower() == "banlist=")
{
                                string text12 = text2.Substring(8);
                                Netplay.BanFilePath = Platform.Get<IPathService>().ExpandPathVariables(text12);
                            }
                            if (text2.Length > 11 && text2.Substring(0, 11).ToLower() == "difficulty=")
{
                                text = text2.Substring(11);
                            }
                            if (text2.Length > 11 && text2.Substring(0, 11).ToLower() == "autocreate=")
{
                                string text13 = text2.Substring(11);
                                this.autoCreate(text13);
                            }
                            if (text2.Length > 7 && text2.Substring(0, 7).ToLower() == "secure=" && text2.Substring(7) == "1")
{
                                Netplay.SpamCheck = true;
                            }
                            if (text2.Length > 5 && text2.Substring(0, 5).ToLower() == "upnp=" && text2.Substring(5) != "1")
{
                                Netplay.UseUPNP = false;
                            }
                            string text14 = "slowliquids=";
                            if (text2.Length > text14.Length && text2.Substring(0, text14.Length).ToLower() == text14 && text2.Substring(text14.Length) == "1")
{
                                Main.Setting_UseReducedMaxLiquids = true;
                            }
                            if (text2.Length > 10 && text2.Substring(0, 10).ToLower() == "npcstream=")
{
                                string text15 = text2.Substring(10);
                                try
{
                                    Main.npcStreamSpeed = Convert.ToInt32(text15);
                                }
                                catch
{
                                }
                            }
                            CreativePowerManager.TryListingPermissionsFrom(text2);
                            WorldGenerationOptions.TryEnablingFlagFrom(text2);
                        }
                        catch
{
                        }
                    }
                    if (!string.IsNullOrEmpty(text))
                    {
                        if (text == "0")
{
                            Main.GameMode = 0;
                        }
                        else if (text == "1")
{
                            Main.GameMode = 1;
                        }
                        else if (text == "2")
{
                            Main.GameMode = 2;
                        }
                        else if (text == "3")
{
                            Main.GameMode = 3;
                        }
                    }
                }
            }
        }
References Terraria.Main.autoCreate(), System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), Terraria.Main.ConvertFromSafeArgument(), System.IO.File.Exists(), Terraria.IO.WorldFile.GetAllMetadata(), Terraria.Localization.LanguageManager.Instance, Terraria.Program.LaunchParameters, System.Process, System.IO.StreamReader.ReadLine(), Terraria.IO.WorldFileData.SetAsActive(), Terraria.Localization.LanguageManager.SetLanguage(), Terraria.Main.SetNetPlayers(), System.text, System.Convert.ToInt32(), Terraria.WorldBuilding.WorldGenerationOptions.TryEnablingFlagFrom(), and Terraria.GameContent.Creative.CreativePowerManager.TryListingPermissionsFrom().
Referenced by Terraria.Initializers.LaunchInitializer.LoadServerParameters().