Terraria Decompiled: Terraria.Main.ReverseGravitySupport
ReverseGravitySupport() [3/3]
static Vector2 Terraria.Main.ReverseGravitySupport (Vector2 pos, float height = 0f) inline static
Definition at line 541 of file Main.cs.
        {
            if (Main.player[Main.myPlayer].gravDir != -1f)
            {
                return pos;
            }
            pos.Y = (float)Main.screenHeight - pos.Y - height;
            return pos;
        }
References Terraria.Player.gravDir, Terraria.Main.myPlayer, Terraria.Main.player, Terraria.Main.screenHeight, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Projectile.AI_099_2_Yoyos(), Terraria.Projectile.AI_165_Whip(), Terraria.Projectile.AI_198_Flint(), Terraria.GameContent.ObjectInteractions.AHoverInteractionChecker.AttemptInteraction(), Terraria.Graphics.Capture.CaptureInterface.ModeDragBounds.DragBounds(), Terraria.GameContent.UI.EmoteBubble.Draw(), Terraria.GameInput.LockOnHelper.Draw(), Terraria.Graphics.Capture.CaptureInterface.ModeEdgeSelection.DrawCursors(), Terraria.Main.DrawInterface_14_EntityHealthBars(), Terraria.Main.DrawInterface_38_MouseCarriedObject(), Terraria.Main.DrawInterface_3_LaserRuler(), Terraria.Main.DrawInterface_4_Ruler(), Terraria.Graphics.Capture.CaptureInterface.ModeEdgeSelection.DrawMarkedArea(), Terraria.Graphics.Capture.CaptureInterface.ModeDragBounds.DrawMarkedArea(), Terraria.Main.DrawMouseOver(), Terraria.Utils.DrawNotificationIcon(), Terraria.GameContent.Drawing.NextNatureRenderer.DrawWithLitNatureShader(), Terraria.Player.DropItemFromExtractinator(), Terraria.GameInput.PlayerInput.GamePadInput(), Terraria.Player.GetFarthestSpawnPositionOnLine(), Terraria.Player.ItemCheck_Shoot(), Terraria.GameInput.LockOnHelper.SetUP(), Terraria.Player.SmartInteractLookup_PrepareCommonlyUsedInfo(), Terraria.Main.TryInteractingWithMoneyTrough(), Terraria.Main.TryInteractingWithVoidLens(), Terraria.Main.TryPetting(), Terraria.Mount.TryPettingMount(), Terraria.GameContent.Drawing.HorizonHelper.UpdateSunVisibility(), and Terraria.Player.WingFrame().