Terraria Decompiled: Terraria.Main.GetItemDrawFrame
GetItemDrawFrame()
static void Terraria.Main.GetItemDrawFrame (int item, out Texture2D itemTexture, out Microsoft::Xna::Framework::Rectangle itemFrame) inline static
Definition at line 26006 of file Main.cs.
        {
            Main.instance.LoadItem(item);
            itemTexture = TextureAssets.Item[item].Value;
            if (Main.itemAnimations[item] != null)
            {
                itemFrame = Main.itemAnimations[item].GetFrame(itemTexture, -1);
                return;
            }
            itemFrame = itemTexture.Frame(1, 1, 0, 0, 0, 0);
        }
References Terraria.DataStructures.DrawAnimation.GetFrame(), Terraria.Main.instance, System.item, Terraria.GameContent.TextureAssets.Item, Terraria.Main.itemAnimations, Terraria.Main.LoadItem(), and ReLogic.Content.Asset< T >.Value.
Referenced by Terraria.Main.DrawNPC_SlimeItem(), Terraria.Main.DrawNPCChatBottomRightItem(), Terraria.Main.DrawNPCDirect(), Terraria.Main.DrawNPCExtras(), Terraria.GameContent.UI.NewMultiplayerClosePlayersOverlay.PlayerOffScreenCache.DrawPlayerHead(), Terraria.Main.DrawPlayerItemPos(), Terraria.UI.ItemSlot.DrawSavings(), and Terraria.GameContent.UI.CustomCurrencyManager.DrawSavings().