Terraria Decompiled: Terraria.Main.UpdateServer
UpdateServer()
static void Terraria.Main.UpdateServer () inline static private
Definition at line 65801 of file Main.cs.
        {
            Main.netPlayCounter++;
            if (Main.netPlayCounter % 3600 == 0)
            {
                NetMessage.SendData(7, -1, -1, null, 0, 0f, 0f, 0f, 0, 0, 0);
                Main.netPlayCounter = 0;
            }
            for (int i = 0; i < Main.maxNetPlayers; i++)
            {
                if (Main.player[i].active && Netplay.Clients[i].IsActive)
                {
                    Netplay.Clients[i].SpamUpdate();
                }
            }
            if (Math.IEEERemainder((double)Main.netPlayCounter, 900.0) == 0.0)
            {
                bool flag = true;
                int num = Main.lastItemUpdate;
                int num2 = 0;
                while (flag)
                {
                    num++;
                    if (num >= 400)
                    {
                        num = 0;
                    }
                    num2++;
                    if (!Main.item[num].active || Main.item[num].playerIndexTheItemIsReservedFor == 255)
                    {
                        NetMessage.SendData(21, -1, -1, null, num, 0f, 0f, 0f, 0, 0, 0);
                    }
                    if (num2 >= Main.maxItemUpdates || num == Main.lastItemUpdate)
                    {
                        flag = false;
                    }
                }
                Main.lastItemUpdate = num;
            }
            for (int j = 0; j < 400; j++)
            {
                WorldItem worldItem = Main.item[j];
                if (worldItem.active)
                {
                    if (worldItem.playerIndexTheItemIsReservedFor == 255)
                    {
                        if (Main.netPlayCounter % 5 == 0)
{
                            worldItem.FindOwner();
                        }
                    }
                    else
                    {
                        if (worldItem.timeSinceTheItemHasBeenReservedForSomeone >= 0)
{
                            worldItem.timeSinceTheItemHasBeenReservedForSomeone++;
                        }
                        if (!Main.player[worldItem.playerIndexTheItemIsReservedFor].active || worldItem.timeSinceTheItemHasBeenReservedForSomeone % 300 == 0)
{
                            worldItem.FindOwner();
                        }
                    }
                }
            }
            EmergencyStacking.ProcessPendingTransfers();
            for (int k = 0; k < 255; k++)
            {
                if (Netplay.Clients[k].IsActive)
                {
                    Netplay.Clients[k].TimeOutTimer++;
                    if (Netplay.Clients[k].State == 0)
                    {
                        Netplay.Clients[k].TimeOutTimer += 3;
                    }
                    if (!Main.stopTimeOuts && Netplay.Clients[k].TimeOutTimer > 7200)
                    {
                        Netplay.Clients[k].PendingTermination = true;
                        Netplay.Clients[k].PendingTerminationApproved = true;
                    }
                }
                if (Main.player[k].active)
                {
                    RemoteClient.CheckSection(k, Main.player[k].position, 1);
                }
            }
        }
References Terraria.Player.active, Terraria.WorldItem.active, Terraria.RemoteClient.CheckSection(), Terraria.Netplay.Clients, Terraria.WorldItem.FindOwner(), System.Math.IEEERemainder(), Terraria.RemoteClient.IsActive, Terraria.Main.item, Terraria.Main.lastItemUpdate, Terraria.Main.maxItemUpdates, Terraria.Main.maxNetPlayers, Terraria.Main.netPlayCounter, Terraria.RemoteClient.PendingTermination, Terraria.RemoteClient.PendingTerminationApproved, Terraria.Main.player, Terraria.WorldItem.playerIndexTheItemIsReservedFor, Terraria.Entity.position, Terraria.GameContent.EmergencyStacking.ProcessPendingTransfers(), Terraria.NetMessage.SendData(), Terraria.RemoteClient.SpamUpdate(), Terraria.RemoteClient.State, Terraria.Main.stopTimeOuts, Terraria.RemoteClient.TimeOutTimer, and Terraria.WorldItem.timeSinceTheItemHasBeenReservedForSomeone.
Referenced by Terraria.Main.DoUpdateInWorld().