Terraria Decompiled: Terraria.Main.GetPreferredBGStyleForPlayer
GetPreferredBGStyleForPlayer()
static int Terraria.Main.GetPreferredBGStyleForPlayer () inline static
Definition at line 65308 of file Main.cs.
        {
            int num = Main.bgStyle;
            int num2 = (int)((Main.screenPosition.X + (float)(Main.screenWidth / 2)) / 16f);
            if (Main.SceneMetrics.ZoneBeach)
            {
                if (Main.SceneMetrics.ZoneHallow)
                {
                    num = 6;
                }
                else if (Main.SceneMetrics.ZoneCorrupt)
                {
                    if (Main.SceneMetrics.BloodTileCount > Main.SceneMetrics.EvilTileCount)
                    {
                        num = 8;
                    }
                    else
                    {
                        num = 1;
                    }
                }
                else if (Main.SceneMetrics.ZoneCrimson)
                {
                    num = 8;
                }
                else if (Main.SceneMetrics.HoneyBlockCount > 400)
                {
                    num = 3;
                }
                else
                {
                    num = 4;
                }
            }
            else if (Main.SceneMetrics.ZoneGlowshroom)
            {
                num = 9;
            }
            else if (Main.SceneMetrics.ZoneDesert)
            {
                if (Main.SceneMetrics.ZoneCorrupt && Main.SceneMetrics.EvilTileCount > Main.SceneMetrics.BloodTileCount && Main.SceneMetrics.EvilTileCount > Main.SceneMetrics.HolyTileCount)
                {
                    num = 5;
                }
                else if (Main.SceneMetrics.ZoneCrimson && Main.SceneMetrics.BloodTileCount > Main.SceneMetrics.HolyTileCount)
                {
                    num = 14;
                }
                else if (Main.SceneMetrics.ZoneHallow)
                {
                    num = 13;
                }
                else
                {
                    num = 2;
                }
            }
            else if (Main.SceneMetrics.ZoneHallow)
            {
                num = 6;
            }
            else if (Main.SceneMetrics.ZoneCorrupt)
            {
                if (Main.SceneMetrics.BloodTileCount > Main.SceneMetrics.EvilTileCount)
                {
                    num = 8;
                }
                else
                {
                    num = 1;
                }
            }
            else if (Main.SceneMetrics.ZoneCrimson)
            {
                num = 8;
            }
            else if (Main.SceneMetrics.ZoneJungle)
            {
                num = 3;
            }
            else if (Main.SceneMetrics.ZoneSnow)
            {
                num = 7;
            }
            else
            {
                num = 0;
                if (num2 >= Main.treeX[0])
                {
                    if (num2 < Main.treeX[1])
                    {
                        num = 10;
                    }
                    else if (num2 < Main.treeX[2])
                    {
                        num = 11;
                    }
                    else
                    {
                        num = 12;
                    }
                }
            }
            return num;
        }
References Terraria.Main.bgStyle, Terraria.SceneMetrics.BloodTileCount, Terraria.SceneMetrics.EvilTileCount, Terraria.SceneMetrics.HolyTileCount, Terraria.SceneMetrics.HoneyBlockCount, int, Terraria.Main.SceneMetrics, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Terraria.Main.treeX, Microsoft.Xna.Framework.Vector2.X, Terraria.SceneMetrics.ZoneBeach, Terraria.SceneMetrics.ZoneCorrupt, Terraria.SceneMetrics.ZoneCrimson, Terraria.SceneMetrics.ZoneDesert, Terraria.SceneMetrics.ZoneGlowshroom, Terraria.SceneMetrics.ZoneHallow, Terraria.SceneMetrics.ZoneJungle, and Terraria.SceneMetrics.ZoneSnow.
Referenced by Terraria.Main.BlackFadeCameraTeleport(), Terraria.Main.DrawBG(), and Terraria.Graphics.Capture.CaptureBiome.GetBiomeByLocation().