Terraria Decompiled: Terraria.Main.UpdateWorldPreparationState
UpdateWorldPreparationState()
static void Terraria.Main.UpdateWorldPreparationState () inline static
Definition at line 2004 of file Main.cs.
        {
            if (Main.netMode != 1)
            {
                Main._worldPreparationState = Main.WorldPreparationState.Ready;
                return;
            }
            if (Main.netMode == 1 && Main.gameMenu && Main._worldPreparationState == Main.WorldPreparationState.Ready)
            {
                Main._worldPreparationState = Main.WorldPreparationState.AwaitingData;
            }
            if (Main.netMode == 1 && Main._worldPreparationState == Main.WorldPreparationState.ProcessingData)
            {
                Main._worldPreparationState = Main.WorldPreparationState.Ready;
                Main.gameMenu = false;
                Main.FixUIScale();
                ChatHelper.ShowCachedMessages();
                ChatHelper.ClearDelayedMessagesCache();
            }
        }
References Terraria.Main._worldPreparationState, Terraria.Chat.ChatHelper.ClearDelayedMessagesCache(), Terraria.Main.FixUIScale(), Terraria.Main.gameMenu, Terraria.Main.netMode, and Terraria.Chat.ChatHelper.ShowCachedMessages().
Referenced by Terraria.Main.DoUpdate().