Terraria Decompiled: Terraria.Main.DrawStar
DrawStar()
void Terraria.Main.DrawStar (ref Main::SceneArea sceneArea, float starOpacity, Microsoft::Xna::Framework::Color bgColorForStars, int i, Star theStar, bool artificial) inline private
Definition at line 64093 of file Main.cs.
        {
            if (theStar == null || theStar.hidden)
            {
                return;
            }
            float num = Main.shimmerAlpha;
            Microsoft.Xna.Framework.Color color = default(Microsoft.Xna.Framework.Color);
            float num2 = 1f - theStar.fadeIn;
            int num3 = (int)((float)(byte.MaxValue - bgColorForStars.R - 100) * theStar.twinkle * num2);
            int num4 = (int)((float)(byte.MaxValue - bgColorForStars.G - 100) * theStar.twinkle * num2);
            int num5 = (int)((float)(byte.MaxValue - bgColorForStars.B - 100) * theStar.twinkle * num2);
            num3 = (num3 + num5 + num4) / 3;
            if (num3 <= 0)
            {
                return;
            }
            num3 = (int)((double)num3 * 1.4);
            if (num3 > 255)
            {
                num3 = 255;
            }
            num4 = num3;
            num5 = num3;
            color.R = (byte)num3;
            color.G = (byte)num4;
            color.B = (byte)num5;
            color *= starOpacity;
            if (num > 0f)
            {
                Microsoft.Xna.Framework.Color color2 = color;
                if (i % 3 == 0)
                {
                    color2.G = (byte)((float)color.G * (1f - num * 0f) * theStar.twinkle * theStar.twinkle);
                }
                else if (i % 3 == 1)
                {
                    color2.B = (byte)((float)color.B * (1f - num * 0f) * theStar.twinkle * theStar.twinkle);
                }
                else if (i % 3 == 2)
                {
                    color2.R = (byte)((float)color.R * (1f - num * 0f) * theStar.twinkle * theStar.twinkle);
                }
                color = Microsoft.Xna.Framework.Color.Lerp(color, color2, num);
                if (artificial)
                {
                    color *= num;
                }
                else
                {
                    color *= 1f - num;
                }
            }
            Vector2 vector = new Vector2(theStar.position.X / 1920f, theStar.position.Y / 1200f);
            int num6 = sceneArea.bgTopY;
            if (Main.worldSurface <= 30.0)
            {
                num6 = 0;
            }
            Vector2 vector2 = vector * new Vector2(sceneArea.totalWidth, sceneArea.totalHeight) + new Vector2(0f, (float)num6);
            if (!theStar.falling)
            {
                if (vector2.X < 0f)
                {
                    vector2.X += sceneArea.totalWidth;
                }
                if (vector2.X > sceneArea.totalWidth)
                {
                    vector2.X -= sceneArea.totalWidth;
                }
                if (vector2.Y < 0f)
                {
                    vector2.Y += sceneArea.totalHeight;
                }
                if (vector2.Y > sceneArea.totalHeight)
                {
                    vector2.Y -= sceneArea.totalHeight;
                }
            }
            Texture2D value = TextureAssets.Star[theStar.type].Value;
            Vector2 vector3 = value.Size() / 2f;
            if (theStar.falling)
            {
                theStar.fadeIn = 0f;
                int num7 = theStar.fallTime;
                float num8 = 30f;
                if ((float)num7 > num8)
                {
                    num7 = (int)num8;
                }
                for (int j = 1; j < num7; j++)
                {
                    Vector2 vector4 = theStar.fallSpeed * (float)j * 0.4f;
                    float num9 = theStar.scale * (1f - (float)j * 1f / num8);
                    Microsoft.Xna.Framework.Color color3 = color;
                    float rotation = theStar.rotation;
                    color3 *= 1f - (float)j * 1f / num8;
                    Main.spriteBatch.Draw(value, vector2 - vector4, null, color3, theStar.rotation, vector3, num9 * theStar.twinkle, SpriteEffects.None, 0f);
                }
                if (Main.starGame && theStar.fallSpeed.Y > 0f && Vector2.Distance(new Vector2((float)Main.mouseX, (float)Main.mouseY), vector2) < 70f)
                {
                    Main.starsHit++;
                    theStar.fallSpeed = vector2 - new Vector2((float)Main.mouseX, (float)Main.mouseY);
                    theStar.fallSpeed.Normalize();
                    theStar.fallSpeed *= 10f;
                    if (theStar.fallSpeed.Y > 0f)
                    {
                        theStar.fallSpeed.Y = theStar.fallSpeed.Y * -1f;
                    }
                    SoundEngine.PlaySound(38, -1, -1, 1, 1f, 0f);
                    SoundEngine.PlaySound(37, -1, -1, 1, 1f, 0f);
                }
            }
            Main.spriteBatch.Draw(value, vector2, null, color, theStar.rotation, vector3, theStar.scale * theStar.twinkle, SpriteEffects.None, 0f);
        }
References Microsoft.Xna.Framework.Vector2.Distance(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Star.fadeIn, Terraria.Star.falling, Terraria.Star.fallSpeed, Terraria.Star.fallTime, Terraria.Star.hidden, int, Microsoft.Xna.Framework.Color.Lerp(), Terraria.Main.mouseX, Terraria.Main.mouseY, Microsoft.Xna.Framework.Vector2.Normalize(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.Star.position, Terraria.Star.rotation, Terraria.Star.scale, Terraria.Main.shimmerAlpha, Terraria.Main.spriteBatch, Terraria.GameContent.TextureAssets.Star, Terraria.Main.starGame, Terraria.Main.starsHit, Terraria.Star.twinkle, Terraria.Star.type, System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Main.worldSurface, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.