Terraria Decompiled: Terraria.Main.DrawInfoAccs
DrawInfoAccs()
void Terraria.Main.DrawInfoAccs () inline private
Definition at line 46959 of file Main.cs.
        {
            int num = -1;
            if (Main.CanShowInfoAccs)
            {
                bool flag = false;
                bool flag2 = false;
                bool flag3 = false;
                bool flag4 = false;
                bool flag5 = false;
                bool flag6 = false;
                bool flag7 = false;
                bool flag8 = false;
                bool flag9 = false;
                bool flag10 = false;
                bool flag11 = false;
                bool flag12 = false;
                int num2 = -1;
                int num3 = -10;
                int num4 = 0;
                string text = "";
                float num5 = 215f;
                int num6 = 0;
                if (!Main.playerInventory && GameCulture.FromCultureName(GameCulture.CultureName.Russian).IsActive)
                {
                    num6 = -50;
                    num5 += 50f;
                }
                Microsoft.Xna.Framework.Color color = new Microsoft.Xna.Framework.Color(100, 100, 100, (int)Main.mouseTextColor);
                for (int i = 0; i < 12; i++)
                {
                    string text2 = "";
                    string text3 = "";
                    Microsoft.Xna.Framework.Color color2 = new Microsoft.Xna.Framework.Color((int)Main.mouseTextColor, (int)Main.mouseTextColor, (int)Main.mouseTextColor, (int)Main.mouseTextColor);
                    Microsoft.Xna.Framework.Color black = Microsoft.Xna.Framework.Color.Black;
                    if (Main.player[Main.myPlayer].accWatch > 0 && !flag && (!Main.player[Main.myPlayer].hideInfo[0] || Main.playerInventory))
                    {
                        num2 = 0;
                        text3 = Lang.inter[95].Value;
                        string text4 = Language.GetTextValue("GameUI.TimeAtMorning");
                        double num7 = Main.time;
                        if (Main.player[Main.myPlayer].accWatchTime != 0.0)
{
                            num7 = Main.player[Main.myPlayer].accWatchTime;
                        }
                        if (!Main.dayTime)
{
                            num7 += 54000.0;
                        }
                        num7 = num7 / 86400.0 * 24.0;
                        double num8 = 7.5;
                        num7 = num7 - num8 - 12.0;
                        if (num7 < 0.0)
{
                            num7 += 24.0;
                        }
                        if (num7 >= 12.0)
{
                            text4 = Language.GetTextValue("GameUI.TimePastMorning");
                        }
                        int num9 = (int)num7;
                        double num10 = num7 - (double)num9;
                        num10 = (double)((int)(num10 * 60.0));
                        string text5 = string.Concat(num10);
                        if (num10 < 10.0)
{
                            text5 = "0" + text5;
                        }
                        if (num9 > 12)
{
                            num9 -= 12;
                        }
                        if (num9 == 0)
{
                            num9 = 12;
                        }
                        if (Main.player[Main.myPlayer].accWatch == 1)
{
                            text5 = "00";
                        }
                        else if (Main.player[Main.myPlayer].accWatch == 2)
{
                            if (num10 < 30.0)
{
                                text5 = "00";
                            }
                            else
{
                                text5 = "30";
                            }
                        }
                        text2 = string.Concat(new object[] { num9, ":", text5, " ", text4 });
                        flag = true;
                    }
                    else if (Main.player[Main.myPlayer].accWeatherRadio && !flag5 && (!Main.player[Main.myPlayer].hideInfo[1] || Main.playerInventory))
                    {
                        num2 = 1;
                        text3 = Lang.inter[96].Value;
                        string text6;
                        if (Main.IsItStorming)
{
                            text6 = Language.GetTextValue("GameUI.Storm");
                        }
                        else if ((double)Main.maxRaining > 0.6)
{
                            text6 = Language.GetTextValue("GameUI.HeavyRain");
                        }
                        else if ((double)Main.maxRaining >= 0.2)
{
                            text6 = Language.GetTextValue("GameUI.Rain");
                        }
                        else if (Main.maxRaining > 0f)
{
                            text6 = Language.GetTextValue("GameUI.LightRain");
                        }
                        else if (Main.cloudBGActive > 0f)
{
                            text6 = Language.GetTextValue("GameUI.Overcast");
                        }
                        else if (Main.numClouds > 90)
{
                            text6 = Language.GetTextValue("GameUI.MostlyCloudy");
                        }
                        else if (Main.numClouds > 55)
{
                            text6 = Language.GetTextValue("GameUI.Cloudy");
                        }
                        else if (Main.numClouds > 15)
{
                            text6 = Language.GetTextValue("GameUI.PartlyCloudy");
                        }
                        else
{
                            text6 = Language.GetTextValue("GameUI.Clear");
                        }
                        text2 = text6;
                        int num11 = (int)(Main.windSpeedCurrent * 50f);
                        if (num11 < 0)
{
                            text2 += Language.GetTextValue("GameUI.EastWind", Math.Abs(num11));
                        }
                        else if (num11 > 0)
{
                            text2 += Language.GetTextValue("GameUI.WestWind", num11);
                        }
                        if (Sandstorm.Happening)
{
                            if (Main.GlobalTimeWrappedHourly % 10f >= 5f)
{
                                text2 = Language.GetTextValue("GameUI.Sandstorm");
                            }
                            text2 += " +";
                        }
                        flag5 = true;
                    }
                    else if (Main.player[Main.myPlayer].accCalendar && !flag8 && (!Main.player[Main.myPlayer].hideInfo[7] || Main.playerInventory))
                    {
                        if (Main.bloodMoon && !Main.dayTime)
{
                            num2 = 8;
                        }
                        else if (Main.eclipse && Main.dayTime)
{
                            num2 = 8;
                        }
                        else
{
                            num2 = 7;
                        }
                        text3 = Lang.inter[102].Value;
                        if (Main.moonPhase == 0)
{
                            text2 = Language.GetTextValue("GameUI.FullMoon");
                        }
                        else if (Main.moonPhase == 1)
{
                            text2 = Language.GetTextValue("GameUI.WaningGibbous");
                        }
                        else if (Main.moonPhase == 2)
{
                            text2 = Language.GetTextValue("GameUI.ThirdQuarter");
                        }
                        else if (Main.moonPhase == 3)
{
                            text2 = Language.GetTextValue("GameUI.WaningCrescent");
                        }
                        else if (Main.moonPhase == 4)
{
                            text2 = Language.GetTextValue("GameUI.NewMoon");
                        }
                        else if (Main.moonPhase == 5)
{
                            text2 = Language.GetTextValue("GameUI.WaxingCrescent");
                        }
                        else if (Main.moonPhase == 6)
{
                            text2 = Language.GetTextValue("GameUI.FirstQuarter");
                        }
                        else if (Main.moonPhase == 7)
{
                            text2 = Language.GetTextValue("GameUI.WaxingGibbous");
                        }
                        flag8 = true;
                    }
                    else if (Main.player[Main.myPlayer].accFishFinder && !flag4 && (!Main.player[Main.myPlayer].hideInfo[2] || Main.playerInventory))
                    {
                        bool flag13 = false;
                        num2 = 2;
                        text3 = Lang.inter[97].Value;
                        for (int j = 0; j < 1000; j++)
{
                            if (Main.projectile[j].active && Main.projectile[j].owner == Main.myPlayer && Main.projectile[j].bobber)
{
                                flag13 = true;
                                break;
                            }
                        }
                        if (flag13)
{
                            text2 = Main.player[Main.myPlayer].displayedFishingInfo;
                        }
                        else
{
                            PlayerFishingConditions fishingConditions = Main.player[Main.myPlayer].GetFishingConditions();
                            if (fishingConditions.BaitItemType == 2673)
{
                                text2 = Language.GetTextValue("GameUI.FishingWarning");
                            }
                            else
{
                                text2 = (Main.player[Main.myPlayer].displayedFishingInfo = Language.GetTextValue("GameUI.FishingPower", fishingConditions.FinalFishingLevel));
                            }
                        }
                        flag4 = true;
                    }
                    else if (Main.player[Main.myPlayer].accOreFinder && !flag10 && (!Main.player[Main.myPlayer].hideInfo[10] || Main.playerInventory))
                    {
                        num2 = 10;
                        text3 = Lang.inter[104].Value;
                        if (Main.PlayerSceneMetrics.BestOreType <= 0)
{
                            text2 = Language.GetTextValue("GameUI.NoTreasureNearby");
                            color2 = color;
                        }
                        else
{
                            int num12 = 0;
                            int num13 = Main.PlayerSceneMetrics.BestOreType;
                            Microsoft.Xna.Framework.Point bestOrePosition = Main.PlayerSceneMetrics.BestOrePosition;
                            Tile tileSafely = Framing.GetTileSafely(bestOrePosition);
                            if (tileSafely.active())
{
                                MapHelper.GetTileBaseOption(bestOrePosition.X, bestOrePosition.Y, (int)tileSafely.type, tileSafely, ref num12);
                                num13 = (int)tileSafely.type;
                                if (num12 >= 13 || TileID.Sets.BasicChest[num13] || TileID.Sets.BasicChestFake[num13])
{
                                    num12 = 0;
                                }
                            }
                            text2 = Language.GetTextValue("GameUI.OreDetected", Lang.GetMapObjectName(MapHelper.TileToLookup(num13, num12)));
                        }
                        flag10 = true;
                    }
                    else if (Main.player[Main.myPlayer].accCritterGuide && !flag11 && (!Main.player[Main.myPlayer].hideInfo[11] || Main.playerInventory))
                    {
                        flag11 = true;
                        num2 = 11;
                        text3 = Lang.inter[105].Value;
                        int num14 = 1300;
                        int num15 = 0;
                        int num16 = -1;
                        if (Main.player[Main.myPlayer].accCritterGuideCounter <= 0)
{
                            Main.player[Main.myPlayer].accCritterGuideCounter = 15;
                            for (int k = 0; k < Main.maxNPCs; k++)
{
                                if (Main.npc[k].active && Main.npc[k].rarity > num15 && (Main.npc[k].Center - Main.player[Main.myPlayer].Center).Length() < (float)num14)
{
                                    num16 = k;
                                    num15 = Main.npc[k].rarity;
                                }
                            }
                            Main.player[Main.myPlayer].accCritterGuideNumber = (byte)num16;
                        }
                        else
{
                            Player player = Main.player[Main.myPlayer];
                            player.accCritterGuideCounter -= 1;
                            num16 = (int)Main.player[Main.myPlayer].accCritterGuideNumber;
                        }
                        if (num16 >= 0 && num16 < Main.maxNPCs && Main.npc[num16].active && Main.npc[num16].rarity > 0)
{
                            text2 = Main.npc[num16].GivenOrTypeName;
                            this.DrawInfoAccs_AdjustInfoTextColorsForNPC(Main.npc[num16], ref color2, ref black);
                        }
                        else
{
                            text2 = Language.GetTextValue("GameUI.NoRareCreatures");
                            color2 = color;
                        }
                    }
                    else if (Main.player[Main.myPlayer].accThirdEye && !flag6 && (!Main.player[Main.myPlayer].hideInfo[5] || Main.playerInventory))
                    {
                        flag6 = true;
                        num2 = 5;
                        text3 = Lang.inter[100].Value;
                        int num17 = 2000;
                        if (Main.player[Main.myPlayer].accThirdEyeCounter == 0)
{
                            Main.player[Main.myPlayer].accThirdEyeNumber = 0;
                            Main.player[Main.myPlayer].accThirdEyeCounter = 15;
                            for (int l = 0; l < Main.maxNPCs; l++)
{
                                if (Main.npc[l].active && !Main.npc[l].friendly && Main.npc[l].damage > 0 && Main.npc[l].lifeMax > 5 && !Main.npc[l].dontCountMe && (Main.npc[l].Center - Main.player[Main.myPlayer].Center).Length() < (float)num17)
{
                                    Player player2 = Main.player[Main.myPlayer];
                                    player2.accThirdEyeNumber += 1;
                                }
                            }
                        }
                        else
{
                            Player player3 = Main.player[Main.myPlayer];
                            player3.accThirdEyeCounter -= 1;
                        }
                        if (Main.player[Main.myPlayer].accThirdEyeNumber == 0)
{
                            text2 = Language.GetTextValue("GameUI.NoEnemiesNearby");
                            color2 = color;
                        }
                        else if (Main.player[Main.myPlayer].accThirdEyeNumber == 1)
{
                            text2 = Language.GetTextValue("GameUI.OneEnemyNearby");
                        }
                        else
{
                            text2 = Language.GetTextValue("GameUI.EnemiesNearby", Main.player[Main.myPlayer].accThirdEyeNumber);
                        }
                    }
                    else if (Main.player[Main.myPlayer].accJarOfSouls && !flag7 && (!Main.player[Main.myPlayer].hideInfo[6] || Main.playerInventory))
                    {
                        flag7 = true;
                        num2 = 6;
                        text3 = Lang.inter[101].Value;
                        int lastCreatureHit = Main.player[Main.myPlayer].lastCreatureHit;
                        if (lastCreatureHit <= 0)
{
                            text2 = Language.GetTextValue("GameUI.NoKillCount");
                            color2 = color;
                        }
                        else
{
                            text2 = Lang.GetNPCNameValue(BannerSystem.BannerToNPC(lastCreatureHit)) + ": " + BannerSystem.GetKillCount(lastCreatureHit);
                        }
                    }
                    else if (Main.player[Main.myPlayer].accDreamCatcher && !flag12 && (!Main.player[Main.myPlayer].hideInfo[12] || Main.playerInventory))
                    {
                        num2 = 12;
                        text3 = Lang.inter[106].Value;
                        Main.player[Main.myPlayer].checkDPSTime();
                        bool dps = Main.player[Main.myPlayer].getDPS() != 0;
                        flag12 = true;
                        if (!dps)
{
                            text2 = Language.GetTextValue("GameUI.NoDPS");
                            color2 = color;
                        }
                        else
{
                            text2 = Language.GetTextValue("GameUI.DPS", Main.player[Main.myPlayer].getDPS());
                        }
                    }
                    else if (Main.player[Main.myPlayer].accStopwatch && !flag9 && (!Main.player[Main.myPlayer].hideInfo[9] || Main.playerInventory))
                    {
                        num2 = 9;
                        text3 = Lang.inter[103].Value;
                        Vector2 vector = Main.player[Main.myPlayer].velocity + Main.player[Main.myPlayer].instantMovementAccumulatedThisFrame;
                        if (Main.player[Main.myPlayer].mount.Active && Main.player[Main.myPlayer].mount.IsConsideredASlimeMount && Main.player[Main.myPlayer].velocity.Y != 0f && !Main.player[Main.myPlayer].SlimeDontHyperJump)
{
                            vector.Y += Main.player[Main.myPlayer].velocity.Y;
                        }
                        int num18 = (int)(1f + vector.Length() * 6f);
                        if (num18 > Main.player[Main.myPlayer].speedSlice.Length)
{
                            num18 = Main.player[Main.myPlayer].speedSlice.Length;
                        }
                        float num19 = 0f;
                        for (int m = num18 - 1; m > 0; m--)
{
                            Main.player[Main.myPlayer].speedSlice[m] = Main.player[Main.myPlayer].speedSlice[m - 1];
                        }
                        Main.player[Main.myPlayer].speedSlice[0] = vector.Length();
                        for (int n = 0; n < Main.player[Main.myPlayer].speedSlice.Length; n++)
{
                            if (n < num18)
{
                                num19 += Main.player[Main.myPlayer].speedSlice[n];
                            }
                            else
{
                                Main.player[Main.myPlayer].speedSlice[n] = num19 / (float)num18;
                            }
                        }
                        num19 /= (float)num18;
                        int num20 = 42240;
                        int num21 = 216000;
                        float num22 = num19 * (float)num21 / (float)num20;
                        if (!Main.player[Main.myPlayer].merman && !Main.player[Main.myPlayer].ignoreWater)
{
                            if (Main.player[Main.myPlayer].honeyWet)
{
                                num22 /= 4f;
                            }
                            else if (Main.player[Main.myPlayer].shimmerWet)
{
                                num22 *= 0.375f;
                            }
                            else if (Main.player[Main.myPlayer].wet && !Main.player[Main.myPlayer].trident)
{
                                num22 /= 2f;
                            }
                        }
                        text2 = Language.GetTextValue("GameUI.Speed", Math.Round((double)num22));
                        flag9 = true;
                    }
                    else if (Main.player[Main.myPlayer].accCompass > 0 && !flag3 && (!Main.player[Main.myPlayer].hideInfo[3] || Main.playerInventory))
                    {
                        num2 = 3;
                        text3 = Lang.inter[98].Value;
                        int num23 = (int)((Main.player[Main.myPlayer].position.X + (float)(Main.player[Main.myPlayer].width / 2)) * 2f / 16f - (float)Main.maxTilesX);
                        if (num23 > 0)
{
                            text2 = Language.GetTextValue("GameUI.CompassEast", num23);
                        }
                        else if (num23 < 0)
{
                            text2 = Language.GetTextValue("GameUI.CompassWest", -num23);
                        }
                        else
{
                            text2 = Language.GetTextValue("GameUI.CompassCenter");
                        }
                        flag3 = true;
                    }
                    else if (Main.player[Main.myPlayer].accDepthMeter > 0 && !flag2 && (!Main.player[Main.myPlayer].hideInfo[4] || Main.playerInventory))
                    {
                        num2 = 4;
                        text3 = Lang.inter[99].Value;
                        int num24 = (int)((double)((Main.player[Main.myPlayer].position.Y + (float)Main.player[Main.myPlayer].height) * 2f / 16f) - Main.worldSurface * 2.0);
                        float num25 = (float)Main.maxTilesX / 4200f;
                        num25 *= num25;
                        float num26 = (float)((double)(Main.player[Main.myPlayer].Center.Y / 16f - (65f + 10f * num25)) / (Main.worldSurface / 5.0));
                        string text7;
                        if (Main.player[Main.myPlayer].Bottom.Y > (float)((Main.maxTilesY - 204) * 16))
{
                            text7 = Language.GetTextValue("GameUI.LayerUnderworld");
                        }
                        else if ((double)Main.player[Main.myPlayer].Bottom.Y > Main.rockLayer * 16.0)
{
                            text7 = Language.GetTextValue("GameUI.LayerCaverns");
                        }
                        else if (num24 > 0)
{
                            text7 = Language.GetTextValue("GameUI.LayerUnderground");
                        }
                        else if (num26 >= 1f)
{
                            text7 = Language.GetTextValue("GameUI.LayerSurface");
                        }
                        else
{
                            text7 = Language.GetTextValue("GameUI.LayerSpace");
                        }
                        num24 = Math.Abs(num24);
                        string text8;
                        if (num24 == 0)
{
                            text8 = Language.GetTextValue("GameUI.DepthLevel");
                        }
                        else
{
                            text8 = Language.GetTextValue("GameUI.Depth", num24);
                        }
                        text2 = text8 + " " + text7;
                        flag2 = true;
                    }
                    if (text2 != "")
                    {
                        int num27;
                        int num28;
                        Main.GetInfoAccIconPosition(num4, num6, out num27, out num28);
                        if (num2 >= 0)
{
                            num4++;
                            int num29 = 22;
                            if (Main.screenHeight < 650)
{
                                num29 = 20;
                            }
                            Vector2 vector2 = new Vector2((float)num27, (float)(num28 + 74 + num29 * i + 52));
                            int num30 = num2;
                            if (num30 == 8)
{
                                num30 = 7;
                            }
                            Microsoft.Xna.Framework.Color white = Microsoft.Xna.Framework.Color.White;
                            bool flag14 = false;
                            if (Main.playerInventory)
{
                                vector2 = new Vector2((float)num27, (float)num28);
                                if ((float)Main.mouseX >= vector2.X && (float)Main.mouseY >= vector2.Y && (float)Main.mouseX <= vector2.X + (float)TextureAssets.InfoIcon[num2].Width() && (float)Main.mouseY <= vector2.Y + (float)TextureAssets.InfoIcon[num2].Height())
{
                                    num = num4;
                                    if (!PlayerInput.IgnoreMouseInterface)
{
                                        flag14 = true;
                                        Main.player[Main.myPlayer].mouseInterface = true;
                                        if (Main.mouseLeft && Main.mouseLeftRelease)
{
                                            SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                                            Main.mouseLeftRelease = false;
                                            Main.player[Main.myPlayer].hideInfo[num30] = !Main.player[Main.myPlayer].hideInfo[num30];
                                        }
                                        if (!Main.mouseText)
{
                                            text = text3;
                                            Main.mouseText = true;
                                        }
                                    }
                                }
                                if (Main.player[Main.myPlayer].hideInfo[num30])
{
                                    white = new Microsoft.Xna.Framework.Color(80, 80, 80, 70);
                                }
                            }
                            else if ((float)Main.mouseX >= vector2.X && (float)Main.mouseY >= vector2.Y && (float)Main.mouseX <= vector2.X + (float)TextureAssets.InfoIcon[num2].Width() && (float)Main.mouseY <= vector2.Y + (float)TextureAssets.InfoIcon[num2].Height() && !Main.mouseText)
{
                                num3 = i;
                                text = text3;
                                Main.mouseText = true;
                            }
                            UILinkPointNavigator.SetPosition(1558 + num4 - 1, vector2 + TextureAssets.InfoIcon[num2].Value.Size() * 0.75f);
                            Main.spriteBatch.Draw(TextureAssets.InfoIcon[num2].Value, vector2, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.InfoIcon[num2].Width(), TextureAssets.InfoIcon[num2].Height())), white, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
                            if (flag14)
{
                                Main.spriteBatch.Draw(TextureAssets.InfoIcon[13].Value, vector2 - Vector2.One * 2f, null, Main.OurFavoriteColor, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
                            }
                            num27 += 20;
                        }
                        UILinkPointNavigator.Shortcuts.INFOACCCOUNT = num4;
                        if (!Main.playerInventory)
{
                            Vector2 vector3 = new Vector2(1f);
                            Vector2 vector4 = FontAssets.MouseText.Value.MeasureString(text2);
                            if (vector4.X > num5)
{
                                vector3.X = num5 / vector4.X;
                            }
                            if (vector3.X < 0.58f)
{
                                vector3.Y = 1f - vector3.X / 3f;
                            }
                            for (int num31 = 0; num31 < 5; num31++)
{
                                int num32 = 0;
                                int num33 = 0;
                                Microsoft.Xna.Framework.Color color3 = black;
                                if (num31 == 0)
{
                                    num32 = -2;
                                }
                                if (num31 == 1)
{
                                    num32 = 2;
                                }
                                if (num31 == 2)
{
                                    num33 = -2;
                                }
                                if (num31 == 3)
{
                                    num33 = 2;
                                }
                                if (num31 == 4)
{
                                    color3 = color2;
                                }
                                if (i > num3 && i < num3 + 2)
{
                                    color3 = new Microsoft.Xna.Framework.Color((int)(color3.R / 3), (int)(color3.G / 3), (int)(color3.B / 3), (int)(color3.A / 3));
                                }
                                int num34 = 22;
                                if (Main.screenHeight < 650)
{
                                    num34 = 20;
                                }
                                DynamicSpriteFontExtensionMethods.DrawString(Main.spriteBatch, FontAssets.MouseText.Value, text2, new Vector2((float)(num27 + num32), (float)(num28 + 74 + num34 * i + num33 + 48)), color3, 0f, default(Vector2), vector3, SpriteEffects.None, 0f);
                            }
                        }
                    }
                }
                if (!string.IsNullOrEmpty(text))
                {
                    if (Main.playerInventory)
                    {
                        Main.player[Main.myPlayer].mouseInterface = true;
                    }
                    this.MouseTextNoOverride(text, 0, 0, -1, -1, -1, -1, 0);
                }
                Main.DoStatefulTickSound(ref Main.infoAccMouseOver, num);
            }
        }
References Microsoft.Xna.Framework.Color.A, System.Math.Abs(), Terraria.Player.accCalendar, Terraria.Player.accCompass, Terraria.Player.accCritterGuide, Terraria.Player.accCritterGuideCounter, Terraria.Player.accCritterGuideNumber, Terraria.Player.accDepthMeter, Terraria.Player.accDreamCatcher, Terraria.Player.accFishFinder, Terraria.Player.accJarOfSouls, Terraria.Player.accOreFinder, Terraria.Player.accStopwatch, Terraria.Player.accThirdEye, Terraria.Player.accThirdEyeCounter, Terraria.Player.accThirdEyeNumber, Terraria.Player.accWatch, Terraria.Player.accWatchTime, Terraria.Player.accWeatherRadio, Terraria.Mount.Active, Terraria.NPC.active, Terraria.Projectile.active, Terraria.Tile.active(), Microsoft.Xna.Framework.Color.B, Terraria.DataStructures.PlayerFishingConditions.BaitItemType, Terraria.GameContent.BannerSystem.BannerToNPC(), Terraria.ID.TileID.Sets.BasicChest, Terraria.ID.TileID.Sets.BasicChestFake, Terraria.SceneMetrics.BestOrePosition, Terraria.SceneMetrics.BestOreType, Microsoft.Xna.Framework.Color.Black, Terraria.Main.bloodMoon, Terraria.Projectile.bobber, Terraria.Entity.Bottom, Terraria.Main.CanShowInfoAccs, Terraria.Entity.Center, Terraria.Player.checkDPSTime(), Terraria.Main.cloudBGActive, Terraria.NPC.damage, Terraria.Main.dayTime, Terraria.Player.displayedFishingInfo, Terraria.NPC.dontCountMe, Terraria.Main.DoStatefulTickSound(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), ReLogic.Graphics.DynamicSpriteFontExtensionMethods.DrawString(), Terraria.Main.eclipse, Terraria.DataStructures.PlayerFishingConditions.FinalFishingLevel, Terraria.NPC.friendly, Terraria.Localization.GameCulture.FromCultureName(), Microsoft.Xna.Framework.Color.G, Terraria.Player.getDPS(), Terraria.Player.GetFishingConditions(), Terraria.Main.GetInfoAccIconPosition(), Terraria.GameContent.BannerSystem.GetKillCount(), Terraria.Lang.GetMapObjectName(), Terraria.Lang.GetNPCNameValue(), Terraria.Localization.Language.GetTextValue(), Terraria.Map.MapHelper.GetTileBaseOption(), Terraria.Framing.GetTileSafely(), Terraria.NPC.GivenOrTypeName, Terraria.Main.GlobalTimeWrappedHourly, Terraria.GameContent.Events.Sandstorm.Happening, Terraria.Entity.height, Terraria.Player.hideInfo, Terraria.Entity.honeyWet, Terraria.GameInput.PlayerInput.IgnoreMouseInterface, Terraria.Player.ignoreWater, Terraria.Main.infoAccMouseOver, Terraria.GameContent.TextureAssets.InfoIcon, Terraria.Player.instantMovementAccumulatedThisFrame, int, Terraria.Lang.inter, Terraria.Localization.GameCulture.IsActive, Terraria.Mount.IsConsideredASlimeMount, Terraria.Main.IsItStorming, Terraria.Player.lastCreatureHit, Microsoft.Xna.Framework.Vector2.Length(), Terraria.NPC.lifeMax, Terraria.Main.maxNPCs, Terraria.Main.maxRaining, Terraria.Main.maxTilesX, Terraria.Player.merman, Terraria.Main.moonPhase, Terraria.Player.mount, Terraria.Player.mouseInterface, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.mouseText, Terraria.Main.mouseTextColor, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Main.npc, Terraria.Main.numClouds, Microsoft.Xna.Framework.Vector2.One, Terraria.Main.OurFavoriteColor, Terraria.Projectile.owner, Terraria.Main.player, Terraria.Main.playerInventory, Terraria.Main.PlayerSceneMetrics, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Main.projectile, Microsoft.Xna.Framework.Color.R, Terraria.NPC.rarity, System.Math.Round(), Terraria.Main.screenHeight, Terraria.UI.Gamepad.UILinkPointNavigator.SetPosition(), Terraria.Entity.shimmerWet, Terraria.Player.SlimeDontHyperJump, Terraria.Player.speedSlice, Terraria.Main.spriteBatch, System.text, Terraria.Map.MapHelper.TileToLookup(), Terraria.Main.time, Terraria.Player.trident, Terraria.Tile.type, ReLogic.Content.Asset< T >.Value, Terraria.Localization.LocalizedText.Value, Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Entity.velocity, Terraria.Entity.wet, Microsoft.Xna.Framework.Color.White, Terraria.Entity.width, Terraria.Main.windSpeedCurrent, Terraria.Main.worldSurface, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Point.Y, and Microsoft.Xna.Framework.Vector2.Y.