Terraria Decompiled: Terraria.Main.HelpText
HelpText()
static void Terraria.Main.HelpText () inline static
Definition at line 38492 of file Main.cs.
        {
            bool flag = false;
            if (Main.player[Main.myPlayer].statLifeMax > 100)
            {
                flag = true;
            }
            bool flag2 = false;
            if (Main.player[Main.myPlayer].statManaMax > 20)
            {
                flag2 = true;
            }
            bool flag3 = Main.LocalPlayer.difficulty == 3;
            short num = (flag3 ? 1 : 3509);
            short num2 = (flag3 ? 10 : 3506);
            bool flag4 = true;
            bool flag5 = false;
            bool flag6 = false;
            bool flag7 = false;
            bool flag8 = false;
            bool flag9 = false;
            bool flag10 = !Main.LocalPlayer.miscEquips[4].IsAir;
            bool flag11 = false;
            bool flag12 = false;
            bool flag13 = false;
            bool flag14 = false;
            for (int i = 0; i < 58; i++)
            {
                Item item = Main.LocalPlayer.inventory[i];
                if (!item.IsAir)
                {
                    if (item.pick > 0 && item.type != (int)num)
                    {
                        flag4 = false;
                    }
                    if (item.axe > 0 && item.type != (int)num2)
                    {
                        flag4 = false;
                    }
                    if (item.hammer > 0 && (!flag3 || item.type != 7))
                    {
                        flag4 = false;
                    }
                    if (item.type == 11 || item.type == 12 || item.type == 13 || item.type == 14 || item.type == 699 || item.type == 700 || item.type == 701 || item.type == 702)
                    {
                        flag5 = true;
                    }
                    if (item.type == 19 || item.type == 20 || item.type == 21 || item.type == 22 || item.type == 703 || item.type == 704 || item.type == 705 || item.type == 706)
                    {
                        flag6 = true;
                    }
                    if (item.type == 75)
                    {
                        flag7 = true;
                    }
                    if (item.type == 38)
                    {
                        flag8 = true;
                    }
                    if (item.type == 68 || item.type == 70 || item.type == 1330 || item.type == 1331 || item.type == 67 || item.type == 2886)
                    {
                        flag9 = true;
                    }
                    if (!flag10 && item.shoot > 0 && Main.projHook[item.shoot])
                    {
                        flag10 = true;
                    }
                    if (item.type == 3347)
                    {
                        flag11 = true;
                    }
                    if (item.type == 174)
                    {
                        flag12 = true;
                    }
                    if (item.type == 1141)
                    {
                        flag13 = true;
                    }
                    if (item.type == 1533 || item.type == 1534 || item.type == 1535 || item.type == 1536 || item.type == 1537 || item.type == 4714)
                    {
                        flag14 = true;
                    }
                }
            }
            bool flag15 = false;
            bool flag16 = false;
            bool flag17 = false;
            bool flag18 = false;
            bool flag19 = false;
            bool flag20 = false;
            bool flag21 = false;
            bool flag22 = false;
            bool flag23 = false;
            bool flag24 = false;
            bool flag25 = false;
            bool flag26 = false;
            bool flag27 = false;
            bool flag28 = false;
            bool flag29 = false;
            bool flag30 = false;
            bool flag31 = false;
            bool flag32 = false;
            bool flag33 = false;
            bool flag34 = false;
            bool flag35 = false;
            bool flag36 = false;
            bool flag37 = false;
            bool flag38 = false;
            bool flag39 = false;
            int num3 = 0;
            for (int j = 0; j < Main.maxNPCs; j++)
            {
                if (Main.npc[j].active)
                {
                    if (Main.npc[j].townNPC && Main.npc[j].type != 37)
                    {
                        num3++;
                    }
                    if (Main.npc[j].type == 17)
                    {
                        flag15 = true;
                    }
                    if (Main.npc[j].type == 18)
                    {
                        flag16 = true;
                    }
                    if (Main.npc[j].type == 19)
                    {
                        flag18 = true;
                    }
                    if (Main.npc[j].type == 20)
                    {
                        flag17 = true;
                    }
                    if (Main.npc[j].type == 54)
                    {
                        flag23 = true;
                    }
                    if (Main.npc[j].type == 124)
                    {
                        flag20 = true;
                    }
                    if (Main.npc[j].type == 38)
                    {
                        flag19 = true;
                    }
                    if (Main.npc[j].type == 108)
                    {
                        flag21 = true;
                    }
                    if (Main.npc[j].type == 107)
                    {
                        flag22 = true;
                    }
                    if (Main.npc[j].type == 228)
                    {
                        flag24 = true;
                    }
                    if (Main.npc[j].type == 178)
                    {
                        flag25 = true;
                    }
                    if (Main.npc[j].type == 209)
                    {
                        flag26 = true;
                    }
                    if (Main.npc[j].type == 353)
                    {
                        flag27 = true;
                    }
                    if (Main.npc[j].type == 633)
                    {
                        flag39 = true;
                    }
                    if (Main.npc[j].type == 369)
                    {
                        flag28 = true;
                    }
                    if (Main.npc[j].type == 441)
                    {
                        flag29 = true;
                    }
                    if (Main.npc[j].type == 229)
                    {
                        flag30 = true;
                    }
                    if (Main.npc[j].type == 207)
                    {
                        flag31 = true;
                    }
                    if (Main.npc[j].type == 160)
                    {
                        flag32 = true;
                    }
                    if (Main.npc[j].type == 588)
                    {
                        flag33 = true;
                    }
                    if (Main.npc[j].type == 227)
                    {
                        flag34 = true;
                    }
                    if (Main.npc[j].type == 208)
                    {
                        flag35 = true;
                    }
                    if (Main.npc[j].type == 550)
                    {
                        flag36 = true;
                    }
                    if (Main.npc[j].type == 368)
                    {
                        flag37 = true;
                    }
                    if (Main.npc[j].type == 453)
                    {
                        flag38 = true;
                    }
                }
            }
            for (;;)
            {
                Main.helpText++;
                if (Language.Exists("GuideHelpText.Help_" + Main.helpText) && Language.GetText("GuideHelpText.Help_" + Main.helpText).GetValueIfConditionsMet(out Main.npcChatText))
                {
                    break;
                }
                if (flag4)
                {
                    if (Main.helpText == 1)
                    {
                        goto Block_76;
                    }
                    if (Main.helpText == 2)
                    {
                        goto Block_77;
                    }
                    if (Main.helpText == 3)
                    {
                        goto Block_78;
                    }
                    if (Main.helpText == 4)
                    {
                        goto Block_79;
                    }
                    if (Main.helpText == 5)
                    {
                        goto Block_80;
                    }
                    if (Main.helpText == 6)
                    {
                        goto Block_81;
                    }
                }
                if (flag4 && !flag5 && !flag6 && Main.helpText == 11)
                {
                    goto Block_85;
                }
                if (flag4 && flag5 && !flag6)
                {
                    if (Main.helpText == 21)
                    {
                        goto Block_88;
                    }
                    if (Main.helpText == 22)
                    {
                        goto Block_89;
                    }
                }
                if (flag4 && flag6)
                {
                    if (Main.helpText == 31)
                    {
                        goto Block_91;
                    }
                    if (Main.helpText == 32)
                    {
                        goto Block_92;
                    }
                }
                if (!flag && Main.helpText == 41)
                {
                    goto Block_94;
                }
                if (!flag2 && Main.helpText == 42)
                {
                    goto Block_96;
                }
                if (!flag2 && !flag7 && Main.helpText == 43)
                {
                    goto Block_99;
                }
                if (!flag15 && !flag16)
                {
                    if (Main.helpText == 51)
                    {
                        goto Block_102;
                    }
                    if (Main.helpText == 52)
                    {
                        goto Block_103;
                    }
                    if (Main.helpText == 53)
                    {
                        goto Block_104;
                    }
                    if (Main.helpText == 54)
                    {
                        goto Block_105;
                    }
                    if (Main.helpText == 55)
                    {
                        goto Block_106;
                    }
                }
                if (!flag15 && Main.helpText == 61)
                {
                    goto Block_108;
                }
                if (!flag16 && Main.helpText == 62)
                {
                    goto Block_110;
                }
                if (!flag18 && Main.helpText == 63)
                {
                    goto Block_112;
                }
                if (!flag17 && Main.helpText == 64)
                {
                    goto Block_114;
                }
                if (!flag20 && Main.helpText == 65 && NPC.downedBoss3)
                {
                    goto Block_117;
                }
                if (!flag23 && Main.helpText == 66 && NPC.downedBoss3)
                {
                    goto Block_120;
                }
                if (!flag19 && Main.helpText == 67)
                {
                    goto Block_122;
                }
                if (!flag22 && NPC.downedBoss2 && Main.helpText == 68)
                {
                    goto Block_125;
                }
                if (!flag21 && Main.hardMode && Main.helpText == 69)
                {
                    goto Block_128;
                }
                if (!flag24 && Main.helpText == 70 && NPC.downedBoss2)
                {
                    goto Block_131;
                }
                if (!flag25 && Main.helpText == 71 && Main.hardMode)
                {
                    goto Block_134;
                }
                if (!flag26 && Main.helpText == 72 && NPC.downedMechBoss1 && NPC.downedMechBoss2 && NPC.downedMechBoss3)
                {
                    goto Block_139;
                }
                if (!flag27 && Main.helpText == 73)
                {
                    goto Block_141;
                }
                if (!flag28 && Main.helpText == 74)
                {
                    goto Block_143;
                }
                if (!flag29 && Main.helpText == 75 && Main.hardMode)
                {
                    goto Block_146;
                }
                if (!flag30 && Main.helpText == 76 && Main.hardMode)
                {
                    goto Block_149;
                }
                if (!flag31 && Main.helpText == 77)
                {
                    goto Block_151;
                }
                if (!flag32 && Main.helpText == 78 && Main.hardMode)
                {
                    goto Block_154;
                }
                if (!flag33 && Main.helpText == 79)
                {
                    goto Block_156;
                }
                if (!flag34 && Main.helpText == 80 && num3 >= 5)
                {
                    goto Block_159;
                }
                if (!flag35 && Main.helpText == 81 && num3 >= 17)
                {
                    goto Block_162;
                }
                if (!flag36 && NPC.downedBoss2 && Main.helpText == 82)
                {
                    goto Block_165;
                }
                if (!flag37 && Main.helpText == 83 && flag15)
                {
                    goto Block_167;
                }
                if (!flag38 && Main.helpText == 84 && !Main.hardMode)
                {
                    goto Block_170;
                }
                if (!flag39 && Main.helpText == 85 && !Main.hardMode)
                {
                    goto Block_173;
                }
                if (flag8 && !WorldGen.crimson && Main.helpText == 100)
                {
                    goto Block_176;
                }
                if (flag9 && Main.helpText == 101)
                {
                    goto Block_178;
                }
                if ((flag8 || flag9) && Main.helpText == 102)
                {
                    goto Block_181;
                }
                if (flag8 && WorldGen.crimson && Main.helpText == 103)
                {
                    goto Block_185;
                }
                if (!flag10 && Main.helpText == 201 && !Main.hardMode && !NPC.downedBoss3 && !NPC.downedBoss2)
                {
                    goto Block_190;
                }
                if (Main.helpText == 202 && !Main.hardMode && Main.player[Main.myPlayer].statLifeMax >= 140)
                {
                    goto Block_193;
                }
                if (Main.helpText == 203 && Main.hardMode && NPC.downedMechBossAny)
                {
                    goto Block_196;
                }
                if (Main.helpText == 204 && !NPC.downedGoblins && Main.player[Main.myPlayer].statLifeMax >= 200 && WorldGen.shadowOrbSmashed)
                {
                    goto Block_200;
                }
                if (Main.helpText == 205 && Main.hardMode && !NPC.downedPirates && Main.player[Main.myPlayer].statLifeMax >= 200)
                {
                    goto Block_204;
                }
                if (Main.helpText == 206 && Main.hardMode && NPC.downedGolemBoss && !NPC.downedMartians)
                {
                    goto Block_208;
                }
                if (Main.helpText == 207 && (NPC.downedBoss1 || NPC.downedBoss2 || NPC.downedBoss3))
                {
                    goto IL_0D8D;
                }
                if (Main.helpText == 208 && !Main.hardMode)
                {
                    goto Block_213;
                }
                if (Main.helpText == 209 && !Main.hardMode)
                {
                    goto Block_215;
                }
                if (Main.helpText == 210 && !Main.hardMode)
                {
                    goto Block_217;
                }
                if (Main.helpText == 211 && !Main.hardMode)
                {
                    goto Block_219;
                }
                if (Main.helpText == 212 && !Main.hardMode)
                {
                    goto Block_221;
                }
                if (Main.helpText == 213 && !Main.hardMode)
                {
                    goto Block_223;
                }
                if (Main.helpText == 214 && !Main.hardMode && (flag5 || flag6))
                {
                    goto Block_226;
                }
                if (Main.helpText == 215 && Main.LocalPlayer.anglerQuestsFinished < 1)
                {
                    goto Block_228;
                }
                if (Main.helpText == 216 && !Main.hardMode)
                {
                    goto Block_230;
                }
                if (Main.helpText == 1000 && !NPC.downedBoss1 && !NPC.downedBoss2)
                {
                    goto Block_233;
                }
                if (Main.helpText == 1001 && !NPC.downedBoss1 && !NPC.downedBoss2)
                {
                    goto Block_236;
                }
                if (Main.helpText == 1002 && !NPC.downedBoss2)
                {
                    goto Block_238;
                }
                if (Main.helpText == 1050 && !NPC.downedBoss1 && Main.player[Main.myPlayer].statLifeMax < 200)
                {
                    goto Block_242;
                }
                if (Main.helpText == 1051 && !NPC.downedBoss1 && Main.player[Main.myPlayer].statDefense <= 10)
                {
                    goto Block_245;
                }
                if (Main.helpText == 1052 && !NPC.downedBoss1 && Main.player[Main.myPlayer].statLifeMax >= 200 && Main.player[Main.myPlayer].statDefense > 10)
                {
                    goto Block_249;
                }
                if (Main.helpText == 1053 && NPC.downedBoss1 && !NPC.downedBoss2 && Main.player[Main.myPlayer].statLifeMax < 300)
                {
                    goto Block_254;
                }
                if (Main.helpText == 1054 && NPC.downedBoss1 && !NPC.downedBoss2 && !WorldGen.crimson && Main.player[Main.myPlayer].statLifeMax >= 300)
                {
                    goto Block_259;
                }
                if (Main.helpText == 1055 && NPC.downedBoss1 && !NPC.downedBoss2 && !WorldGen.crimson && Main.player[Main.myPlayer].statLifeMax >= 300)
                {
                    goto Block_264;
                }
                if (Main.helpText == 1056 && NPC.downedBoss1 && NPC.downedBoss2 && !NPC.downedBoss3)
                {
                    goto Block_268;
                }
                if (Main.helpText == 1057 && NPC.downedBoss1 && NPC.downedBoss2 && NPC.downedBoss3 && !Main.hardMode && Main.player[Main.myPlayer].statLifeMax < 400)
                {
                    goto Block_274;
                }
                if (Main.helpText == 1058 && NPC.downedBoss1 && NPC.downedBoss2 && NPC.downedBoss3 && !Main.hardMode && Main.player[Main.myPlayer].statLifeMax >= 400)
                {
                    goto Block_280;
                }
                if (Main.helpText == 1059 && NPC.downedBoss1 && NPC.downedBoss2 && NPC.downedBoss3 && !Main.hardMode && Main.player[Main.myPlayer].statLifeMax >= 400)
                {
                    goto Block_286;
                }
                if (Main.helpText == 1060 && NPC.downedBoss1 && NPC.downedBoss2 && NPC.downedBoss3 && !Main.hardMode && Main.player[Main.myPlayer].statLifeMax >= 400)
                {
                    goto Block_292;
                }
                if (Main.helpText == 1061 && Main.hardMode && !NPC.downedPlantBoss)
                {
                    goto Block_295;
                }
                if (Main.helpText == 1062 && Main.hardMode && !NPC.downedPlantBoss)
                {
                    goto Block_299;
                }
                if (Main.helpText == 1140 && NPC.downedBoss1 && !NPC.downedBoss2 && WorldGen.crimson && Main.player[Main.myPlayer].statLifeMax >= 300)
                {
                    goto Block_304;
                }
                if (Main.helpText == 1141 && NPC.downedBoss1 && !NPC.downedBoss2 && WorldGen.crimson && Main.player[Main.myPlayer].statLifeMax >= 300)
                {
                    goto Block_309;
                }
                if (Main.helpText == 1142 && NPC.downedBoss2 && !Main.hardMode)
                {
                    goto Block_312;
                }
                if (Main.helpText == 1143 && NPC.downedBoss2 && !NPC.downedQueenBee && Main.player[Main.myPlayer].statLifeMax >= 300)
                {
                    goto Block_316;
                }
                if (Main.helpText == 1144 && flag11)
                {
                    goto Block_317;
                }
                if (Main.helpText == 1145 && flag12 && !Main.hardMode)
                {
                    goto Block_319;
                }
                if (Main.helpText == 1146 && Main.hardMode && Main.player[Main.myPlayer].wingsLogic == 0 && !Main.LocalPlayer.mount.Active && !NPC.downedPlantBoss)
                {
                    goto Block_324;
                }
                if (Main.helpText == 1147 && Main.hardMode && WorldGen.SavedOreTiers.Adamantite == 111 && !NPC.downedMechBossAny)
                {
                    goto Block_328;
                }
                if (Main.helpText == 1148 && Main.hardMode && WorldGen.SavedOreTiers.Adamantite == 223 && !NPC.downedMechBossAny)
                {
                    goto Block_332;
                }
                if (Main.helpText == 1149 && Main.hardMode && NPC.downedMechBossAny && Main.player[Main.myPlayer].statLifeMax < 500)
                {
                    goto Block_336;
                }
                if (Main.helpText == 1150 && Main.hardMode && NPC.downedMechBoss1 && NPC.downedMechBoss2 && NPC.downedMechBoss3 && !NPC.downedPlantBoss)
                {
                    goto Block_342;
                }
                if (Main.helpText == 1151 && Main.hardMode && NPC.downedPlantBoss && !NPC.downedGolemBoss && flag13)
                {
                    goto Block_346;
                }
                if (Main.helpText == 1152 && Main.hardMode && NPC.downedPlantBoss && !NPC.downedGolemBoss && !flag13)
                {
                    goto Block_351;
                }
                if (Main.helpText == 1153 && Main.hardMode && flag14)
                {
                    goto Block_353;
                }
                if (Main.helpText == 1154 && Main.hardMode && !NPC.downedFishron)
                {
                    goto Block_356;
                }
                if (Main.helpText == 1155 && Main.hardMode && NPC.downedGolemBoss && !NPC.downedHalloweenTree && !NPC.downedHalloweenKing)
                {
                    goto Block_361;
                }
                if (Main.helpText == 1156 && Main.hardMode && NPC.downedGolemBoss && !NPC.downedChristmasIceQueen && !NPC.downedChristmasTree && !NPC.downedChristmasSantank)
                {
                    goto Block_367;
                }
                if (Main.helpText == 1157 && Main.hardMode && NPC.downedGolemBoss && NPC.AnyNPCs(437) && !NPC.downedMoonlord)
                {
                    goto Block_372;
                }
                if (Main.helpText == 1158 && Main.hardMode && NPC.LunarApocalypseIsUp && !NPC.downedMoonlord)
                {
                    goto Block_376;
                }
                if (Main.helpText == 1159 && NPC.downedBoss1 && NPC.downedBoss2 && !NPC.downedDeerclops)
                {
                    goto Block_380;
                }
                if (Main.helpText > 1200)
                {
                    Main.helpText = 0;
                }
            }
            return;
            Block_76:
            Main.npcChatText = Lang.dialog(177, false);
            return;
            Block_77:
            Main.npcChatText = Lang.dialog(178, false);
            return;
            Block_78:
            Main.npcChatText = Lang.dialog(179, false);
            return;
            Block_79:
            Main.npcChatText = Lang.dialog(180, false);
            return;
            Block_80:
            Main.npcChatText = Lang.dialog(181, false);
            return;
            Block_81:
            Main.npcChatText = Lang.dialog(182, false);
            return;
            Block_85:
            Main.npcChatText = Lang.dialog(183, false);
            return;
            Block_88:
            Main.npcChatText = Lang.dialog(184, false);
            return;
            Block_89:
            Main.npcChatText = Lang.dialog(185, false);
            return;
            Block_91:
            Main.npcChatText = Lang.dialog(186, false);
            return;
            Block_92:
            Main.npcChatText = Lang.dialog(187, false);
            return;
            Block_94:
            Main.npcChatText = Lang.dialog(188, false);
            return;
            Block_96:
            Main.npcChatText = Lang.dialog(189, false);
            return;
            Block_99:
            Main.npcChatText = Lang.dialog(190, false);
            return;
            Block_102:
            Main.npcChatText = Lang.dialog(191, false);
            return;
            Block_103:
            Main.npcChatText = Lang.dialog(192, false);
            return;
            Block_104:
            Main.npcChatText = Lang.dialog(193, false);
            return;
            Block_105:
            Main.npcChatText = Lang.dialog(194, false);
            return;
            Block_106:
            Main.npcChatText = Language.GetTextValue("GuideHelpText.Help_1065");
            return;
            Block_108:
            Main.npcChatText = Lang.dialog(195, false);
            return;
            Block_110:
            Main.npcChatText = Lang.dialog(196, false);
            return;
            Block_112:
            Main.npcChatText = Lang.dialog(197, false);
            return;
            Block_114:
            Main.npcChatText = Lang.dialog(198, false);
            return;
            Block_117:
            Main.npcChatText = Lang.dialog(199, false);
            return;
            Block_120:
            Main.npcChatText = Lang.dialog(200, false);
            return;
            Block_122:
            Main.npcChatText = Lang.dialog(201, false);
            return;
            Block_125:
            Main.npcChatText = Lang.dialog(202, false);
            return;
            Block_128:
            Main.npcChatText = Lang.dialog(203, false);
            return;
            Block_131:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1100");
            return;
            Block_134:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1101");
            return;
            Block_139:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1102");
            return;
            Block_141:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1103");
            return;
            Block_143:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1104");
            return;
            Block_146:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1105");
            return;
            Block_149:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1106");
            return;
            Block_151:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1107");
            return;
            Block_154:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1108");
            return;
            Block_156:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1109");
            return;
            Block_159:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1110");
            return;
            Block_162:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1111");
            return;
            Block_165:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1112");
            return;
            Block_167:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1113");
            return;
            Block_170:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1114");
            return;
            Block_173:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1115");
            return;
            Block_176:
            Main.npcChatText = Lang.dialog(204, false);
            return;
            Block_178:
            Main.npcChatText = Lang.dialog(WorldGen.crimson ? 403 : 205, false);
            return;
            Block_181:
            Main.npcChatText = Lang.dialog(WorldGen.crimson ? 402 : 206, false);
            return;
            Block_185:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1159");
            return;
            Block_190:
            Main.npcChatText = Lang.dialog(207, false);
            return;
            Block_193:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1120");
            return;
            Block_196:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1121");
            return;
            Block_200:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1122");
            return;
            Block_204:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1123");
            return;
            Block_208:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1124");
            return;
            IL_0D8D:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1125");
            return;
            Block_213:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1130");
            return;
            Block_215:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1131");
            return;
            Block_217:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1132");
            return;
            Block_219:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1133");
            return;
            Block_221:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1134");
            return;
            Block_223:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1135");
            return;
            Block_226:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1136");
            return;
            Block_228:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1137");
            return;
            Block_230:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1138");
            return;
            Block_233:
            Main.npcChatText = Lang.dialog(208, false);
            return;
            Block_236:
            Main.npcChatText = Lang.dialog(209, false);
            return;
            Block_238:
            if (WorldGen.crimson)
            {
                Main.npcChatText = Lang.dialog(331, false);
                return;
            }
            Main.npcChatText = Lang.dialog(210, false);
            return;
            Block_242:
            Main.npcChatText = Lang.dialog(211, false);
            return;
            Block_245:
            Main.npcChatText = Lang.dialog(212, false);
            return;
            Block_249:
            Main.npcChatText = Lang.dialog(WorldGen.crimson ? 404 : 213, false);
            return;
            Block_254:
            Main.npcChatText = Lang.dialog(214, false);
            return;
            Block_259:
            Main.npcChatText = Lang.dialog(215, false);
            return;
            Block_264:
            Main.npcChatText = Lang.dialog(216, false);
            return;
            Block_268:
            Main.npcChatText = Lang.dialog(217, false);
            return;
            Block_274:
            Main.npcChatText = Lang.dialog(218, false);
            return;
            Block_280:
            Main.npcChatText = Lang.dialog(219, false);
            return;
            Block_286:
            Main.npcChatText = Lang.dialog(220, false);
            return;
            Block_292:
            Main.npcChatText = Lang.dialog(221, false);
            return;
            Block_295:
            Main.npcChatText = Lang.dialog(WorldGen.crimson ? 401 : 222, false);
            return;
            Block_299:
            Main.npcChatText = Lang.dialog(223, false);
            return;
            Block_304:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1140");
            return;
            Block_309:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1141");
            return;
            Block_312:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1142");
            return;
            Block_316:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1143");
            return;
            Block_317:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1144");
            return;
            Block_319:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1145");
            return;
            Block_324:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1146");
            return;
            Block_328:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1147");
            return;
            Block_332:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1148");
            return;
            Block_336:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1149");
            return;
            Block_342:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1150");
            return;
            Block_346:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1151");
            return;
            Block_351:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1152");
            return;
            Block_353:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1153");
            return;
            Block_356:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1154");
            return;
            Block_361:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1155");
            return;
            Block_367:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1156");
            return;
            Block_372:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1157");
            return;
            Block_376:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1158");
            return;
            Block_380:
            Main.npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1160");
        }
References Terraria.Mount.Active, Terraria.NPC.active, Terraria.WorldGen.SavedOreTiers.Adamantite, Terraria.Player.anglerQuestsFinished, Terraria.NPC.AnyNPCs(), Terraria.WorldGen.crimson, Terraria.Lang.dialog(), Terraria.NPC.downedBoss1, Terraria.NPC.downedBoss2, Terraria.NPC.downedBoss3, Terraria.NPC.downedChristmasIceQueen, Terraria.NPC.downedChristmasSantank, Terraria.NPC.downedChristmasTree, Terraria.NPC.downedDeerclops, Terraria.NPC.downedFishron, Terraria.NPC.downedGoblins, Terraria.NPC.downedGolemBoss, Terraria.NPC.downedHalloweenKing, Terraria.NPC.downedHalloweenTree, Terraria.NPC.downedMartians, Terraria.NPC.downedMechBoss1, Terraria.NPC.downedMechBoss2, Terraria.NPC.downedMechBoss3, Terraria.NPC.downedMechBossAny, Terraria.NPC.downedMoonlord, Terraria.NPC.downedPirates, Terraria.NPC.downedPlantBoss, Terraria.NPC.downedQueenBee, Terraria.Localization.Language.Exists(), Terraria.Localization.Language.GetText(), Terraria.Localization.Language.GetTextValue(), Terraria.Localization.LocalizedText.GetValueIfConditionsMet(), Terraria.Main.hardMode, Terraria.Main.helpText, Terraria.Player.inventory, Terraria.Item.IsAir, System.item, Terraria.Main.LocalPlayer, Terraria.NPC.LunarApocalypseIsUp, Terraria.Main.maxNPCs, Terraria.Player.miscEquips, Terraria.Player.mount, Terraria.Main.myPlayer, Terraria.Main.npc, Terraria.Main.npcChatText, Terraria.Main.player, Terraria.Main.projHook, Terraria.WorldGen.shadowOrbSmashed, Terraria.Player.statDefense, Terraria.Player.statLifeMax, Terraria.Player.statManaMax, Terraria.NPC.townNPC, Terraria.NPC.type, and Terraria.Player.wingsLogic.
Referenced by Terraria.GameContent.NPCInteractions.Actions.GuideTip.Interact(), and Terraria.Main.NPCChatText_TavernkeepAdvice().