Terraria Decompiled: Terraria.Main.DrawFPS
DrawFPS()
void Terraria.Main.DrawFPS () inline package
Definition at line 20332 of file Main.cs.
        {
            if (Main.showFrameRate)
            {
                string text = string.Concat(new object[]
                {
                    Main.frameRate,
                    "fps ",
                    Main.updateRate,
                    "ups"
                });
                text = string.Concat(new object[]
                {
                    text,
                    " (",
                    Liquid.numLiquid + LiquidBuffer.numLiquidBuffer,
                    ")"
                });
                text = string.Concat(new object[]
                {
                    text,
                    " (",
                    (int)(Main.gfxQuality * 100f),
                    "%)"
                });
                if (Main.netMode == 1)
                {
                    text = string.Concat(new object[]
                    {
                        text,
                        " (",
                        Ping.CurrentPing,
                        "ms)"
                    });
                }
                if (DebugOptions.Shared_ServerPing > 0)
                {
                    text = string.Concat(new object[]
                    {
                        text,
                        " target ~",
                        DebugOptions.Shared_ServerPing,
                        "ms"
                    });
                }
                if (Main.netMode == 1 && Main.shouldDrawNetDiagnosticsUI)
                {
                    int num;
                    int num2;
                    Main.ActiveNetDiagnosticsUI.GetLastSentRecvBytes(out num, out num2);
                    text += string.Format(" ↑{0:0.0} ↓{1:0.0} kB/s", (double)num / 1024.0, (double)num2 / 1024.0);
                }
                string text2 = text + " " + Main.debugWords;
                int num3 = 4;
                if (!Main.gameMenu)
                {
                    num3 = Main.screenHeight - 24;
                }
                Vector2 vector = new Vector2(4f, (float)num3);
                Vector2 vector2 = new Vector2(0f, 0f);
                Vector2 vector3 = FontAssets.MouseText.Value.MeasureString(text2);
                if (PlayerInput.SettingsForUI.ShowGamepadHints && !Main.gameMenu)
                {
                    vector.X = (float)(Main.screenWidth - 4) - vector3.X;
                }
                DynamicSpriteFontExtensionMethods.DrawString(Main.spriteBatch, FontAssets.MouseText.Value, text2, vector, new Microsoft.Xna.Framework.Color((int)Main.mouseTextColor, (int)Main.mouseTextColor, (int)Main.mouseTextColor, (int)Main.mouseTextColor), 0f, vector2, 1f, SpriteEffects.None, 0f, null, null);
            }
        }
References Terraria.Main.ActiveNetDiagnosticsUI, Terraria.Net.Ping.CurrentPing, Terraria.Main.debugWords, ReLogic.Graphics.DynamicSpriteFontExtensionMethods.DrawString(), Terraria.Main.frameRate, Terraria.Main.gameMenu, Terraria.UI.INetDiagnosticsUI.GetLastSentRecvBytes(), Terraria.Main.gfxQuality, int, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.mouseTextColor, Terraria.Main.netMode, Terraria.LiquidBuffer.numLiquidBuffer, Terraria.Main.screenWidth, Terraria.Testing.DebugOptions.Shared_ServerPing, Terraria.Main.shouldDrawNetDiagnosticsUI, Terraria.Main.showFrameRate, Terraria.GameInput.PlayerInput.SettingsForUI.ShowGamepadHints, Terraria.Main.spriteBatch, System.text, Terraria.Main.updateRate, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, and Microsoft.Xna.Framework.Vector2.X.
Referenced by Terraria.GameContent.UI.States.UIWorldGenDebug.DrawSelf().