Terraria Decompiled: Terraria.Main.OnSeedSelected
OnSeedSelected()
void Terraria.Main.OnSeedSelected (string text) inline private
Definition at line 48515 of file Main.cs.
        {
            text = text.Trim();
            if (text.Length == 0)
            {
                Main.ActiveWorldFileData.SetSeedToRandom();
            }
            else
            {
                Main.ActiveWorldFileData.SetSeed(text);
            }
            Main.menuMode = 10;
            WorldGen.CreateNewWorld(null, null, null);
        }
References Terraria.Main.ActiveWorldFileData, Terraria.WorldGen.CreateNewWorld(), Terraria.IO.WorldFileData.SetSeed(), Terraria.IO.WorldFileData.SetSeedToRandom(), and System.text.