Terraria Decompiled: Terraria.Main.SetDisplayMode
SetDisplayMode()
static void Terraria.Main.SetDisplayMode (int width, int height, bool fullscreen) inline static
Definition at line 67618 of file Main.cs.
        {
            bool flag = false;
            Form form = null;
            if (Platform.IsWindows)
            {
                form = Control.FromHandle(Main.instance.Window.Handle);
                Main.screenMaximized = form.WindowState == FormWindowState.Maximized;
                if (Main.screenBorderless && Main.screenMaximized && !Main.graphics.IsFullScreen)
                {
                    Main.screenMaximized = false;
                    form.WindowState = FormWindowState.Normal;
                }
                flag = form.FormBorderStyle == FormBorderStyle.None;
            }
            else
            {
                Main.screenMaximized = false;
            }
            bool flag2 = false;
            int num3;
            int num4;
            if (Main.screenBorderless || Main.screenMaximized || Main.graphics.IsFullScreen || fullscreen)
            {
                bool flag3 = false;
                if (PlayerInput.SteamDeckIsUsed)
                {
                    flag3 = true;
                    if (!fullscreen && !Main.graphics.IsFullScreen)
                    {
                        width = 1280;
                        height = 800;
                        Main.TryPickingDefaultUIScale(800f);
                    }
                }
                if (Platform.IsWindows)
                {
                    form.MinimumSize = new Size(0, 0);
                    if (!fullscreen && !flag3)
                    {
                        Main.SetDisplayModeAsBorderless(ref width, ref height, form);
                    }
                }
                if (width > Main.maxScreenW)
                {
                    float num = (float)height / (float)width;
                    width = Main.maxScreenW;
                    height = (int)(num * (float)width);
                }
                if (height > Main.maxScreenH)
                {
                    float num2 = (float)width / (float)height;
                    height = Main.maxScreenH;
                    width = (int)(num2 * (float)height);
                }
                PlayerInput.RawMouseScale = new Vector2((float)width / (float)Main.instance.Window.ClientBounds.Width, (float)height / (float)Main.instance.Window.ClientBounds.Height);
                if (!Main.graphics.IsFullScreen)
                {
                    num3 = Math.Max(Main.graphics.PreferredBackBufferWidth, Main.graphics.GraphicsDevice.Viewport.Width);
                    num4 = Math.Max(Main.graphics.PreferredBackBufferHeight, Main.graphics.GraphicsDevice.Viewport.Height);
                    if (num3 != Main.graphics.PreferredBackBufferWidth || num4 != Main.graphics.PreferredBackBufferHeight)
                    {
                        flag2 = true;
                    }
                }
                else
                {
                    num3 = Main.graphics.PreferredBackBufferWidth;
                    num4 = Main.graphics.PreferredBackBufferHeight;
                }
            }
            else
            {
                PlayerInput.RawMouseScale = Vector2.One;
                if (Platform.IsWindows)
                {
                    form.MinimumSize = new Size(Main.minScreenW, Main.minScreenH);
                    if (flag)
                    {
                        width = Main.displayWidth[0];
                        height = Main.displayHeight[0];
                    }
                }
                width = Math.Min(width, Main.maxScreenW);
                height = Math.Min(height, Main.maxScreenH);
                num3 = Main.graphics.GraphicsDevice.Viewport.Width;
                num4 = Main.graphics.GraphicsDevice.Viewport.Height;
                flag2 = Main.graphics.PreferredBackBufferWidth != Main.graphics.GraphicsDevice.Viewport.Width || Main.graphics.PreferredBackBufferHeight != Main.graphics.GraphicsDevice.Viewport.Height;
            }
            if (Platform.IsWindows && !fullscreen && !flag2)
            {
                if (form.ClientSize.Width < Main.graphics.PreferredBackBufferWidth)
                {
                    width = form.ClientSize.Width;
                    flag2 = true;
                }
                if (form.ClientSize.Height < Main.graphics.PreferredBackBufferHeight)
                {
                    height = form.ClientSize.Height;
                    flag2 = true;
                }
            }
            width &= 2147483646;
            height &= 2147483646;
            width = Math.Max(width, Main.minScreenW);
            height = Math.Max(height, Main.minScreenH);
            if (Main.graphics.IsFullScreen != fullscreen)
            {
                Main.graphics.PreferredBackBufferWidth = width;
                Main.graphics.PreferredBackBufferHeight = height;
                Main.graphics.ApplyChanges();
                Main.graphics.ToggleFullScreen();
            }
            if (width != num3 || height != num4 || flag2)
            {
                Main.mapTime = 0;
                if (Main.gamePaused)
                {
                    Main.renderNow = true;
                }
                Main.screenWidth = width;
                Main.screenHeight = height;
                Main.graphics.PreferredBackBufferWidth = Main.screenWidth;
                Main.graphics.PreferredBackBufferHeight = Main.screenHeight;
                Main.graphics.ApplyChanges();
                PlayerInput.CacheOriginalScreenDimensions();
                Main.FixUIScale();
                if (Main.OnResolutionChanged != null)
                {
                    Main.OnResolutionChanged(new Vector2((float)Main.screenWidth, (float)Main.screenHeight));
                }
                Main.PendingResolutionWidth = Main.screenWidth;
                Main.PendingResolutionHeight = Main.screenHeight;
                PlayerInput.CacheOriginalScreenDimensions();
                if (Platform.IsWindows && !fullscreen)
                {
                    if (Main.screenBorderless)
                    {
                        Main.ApplyBorderlessResolution(form);
                        form.FormBorderStyle = FormBorderStyle.None;
                    }
                    else
                    {
                        form.FormBorderStyle = FormBorderStyle.Sizable;
                    }
                    form.SendToBack();
                    form.BringToFront();
                }
                Lighting.Initialize();
                if (!Main.drawToScreen && !Main._isResizingAndRemakingTargets)
                {
                    Main._isResizingAndRemakingTargets = true;
                    Main.instance.InitTargets();
                    Main._isResizingAndRemakingTargets = false;
                }
                UserInterface.ActiveInstance.Recalculate();
                Main.instance._needsMenuUIRecalculation = true;
                Console.WriteLine(Language.GetTextValue("Misc.ResolutionChanged", width, height));
            }
            if (!Main.graphics.SynchronizeWithVerticalRetrace)
            {
                Main.graphics.SynchronizeWithVerticalRetrace = true;
                Main.graphics.ApplyChanges();
            }
        }
References Terraria.Main._isResizingAndRemakingTargets, Terraria.UI.UserInterface.ActiveInstance, Terraria.Main.ApplyBorderlessResolution(), Microsoft.Xna.Framework.GraphicsDeviceManager.ApplyChanges(), Terraria.GameInput.PlayerInput.CacheOriginalScreenDimensions(), Microsoft.Xna.Framework.GameWindow.ClientBounds, Terraria.Main.displayHeight, Terraria.Main.displayWidth, Terraria.Main.drawToScreen, Terraria.Main.FixUIScale(), Terraria.Control.FromHandle(), Terraria.Main.gamePaused, Terraria.Localization.Language.GetTextValue(), Terraria.Main.graphics, Microsoft.Xna.Framework.GraphicsDeviceManager.GraphicsDevice, Microsoft.Xna.Framework.GameWindow.Handle, Microsoft.Xna.Framework.Graphics.Viewport.Height, Microsoft.Xna.Framework.Rectangle.Height, Terraria.Lighting.Initialize(), Terraria.Main.InitTargets(), Terraria.Main.instance, int, Microsoft.Xna.Framework.GraphicsDeviceManager.IsFullScreen, ReLogic.OS.Platform.IsWindows, System.Math.Max(), Terraria.Main.maxScreenH, Terraria.Main.maxScreenW, System.Math.Min(), Terraria.Main.minScreenH, Terraria.Main.minScreenW, Microsoft.Xna.Framework.Vector2.One, Terraria.Main.OnResolutionChanged, Microsoft.Xna.Framework.GraphicsDeviceManager.PreferredBackBufferHeight, Microsoft.Xna.Framework.GraphicsDeviceManager.PreferredBackBufferWidth, Terraria.UI.UserInterface.Recalculate(), Terraria.Main.screenBorderless, Terraria.Main.screenHeight, Terraria.Main.screenMaximized, Terraria.Main.screenWidth, Terraria.Main.SetDisplayModeAsBorderless(), Terraria.GameInput.PlayerInput.SteamDeckIsUsed, Microsoft.Xna.Framework.GraphicsDeviceManager.SynchronizeWithVerticalRetrace, Microsoft.Xna.Framework.GraphicsDeviceManager.ToggleFullScreen(), Terraria.Main.TryPickingDefaultUIScale(), Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Graphics.GraphicsDevice.Viewport, Microsoft.Xna.Framework.Graphics.Viewport.Width, Microsoft.Xna.Framework.Rectangle.Width, Microsoft.Xna.Framework.Game.Window, and System.Console.WriteLine().
Referenced by Terraria.Main.FullscreenStartup(), Terraria.Main.LoadSettings(), Terraria.Main.OpenLegacySettings(), Terraria.Main.SetFullScreen(), and Terraria.Main.SetResolution().