Terraria Decompiled: Terraria.Main.DrawNPCDirect_HallowBoss
DrawNPCDirect_HallowBoss()
static void Terraria.Main.DrawNPCDirect_HallowBoss (SpriteBatch mySpriteBatch, NPC rCurrentNPC, ref Vector2 screenPos, int typeCache, ref Microsoft::Xna::Framework::Color npcColor, ref Vector2 halfSize, SpriteEffects npcSpriteEffect) inline static private
Definition at line 25462 of file Main.cs.
        {
            Texture2D value = TextureAssets.Npc[typeCache].Value;
            Vector2 vector = rCurrentNPC.Center - screenPos;
            bool flag = rCurrentNPC.AI_120_HallowBoss_IsInPhase2();
            int num = (int)rCurrentNPC.ai[0];
            Texture2D value2 = TextureAssets.Extra[159].Value;
            Microsoft.Xna.Framework.Rectangle rectangle = value2.Frame(1, 11, 0, (int)(rCurrentNPC.localAI[0] / 4f) % 11, 0, 0);
            Microsoft.Xna.Framework.Color color = rCurrentNPC.GetAlpha(npcColor);
            Texture2D value3 = TextureAssets.Extra[158].Value;
            Texture2D value4 = TextureAssets.Extra[160].Value;
            Texture2D value5 = TextureAssets.Extra[157].Value;
            int num2;
            int num3;
            int num4;
            Main.DrawNPCDirect_GetHallowBossArmFrame(rCurrentNPC, out num2, out num3, out num4);
            Microsoft.Xna.Framework.Rectangle rectangle2 = value3.Frame(1, num2, 0, num3, 0, 0);
            Microsoft.Xna.Framework.Rectangle rectangle3 = value4.Frame(1, num2, 0, num4, 0, 0);
            Vector2 vector2 = rectangle2.Size() / 2f;
            Vector2 vector3 = rectangle3.Size() / 2f;
            int num5 = 0;
            int num6 = 0;
            if (num3 == 5)
            {
                num5 = 1;
            }
            if (num4 == 5)
            {
                num6 = 1;
            }
            float num7 = 1f;
            int num8 = 0;
            int num9 = 0;
            float num10 = 0f;
            float num11 = 0f;
            float num12 = 0f;
            if (num == 8 || num == 9)
            {
                num10 = Utils.GetLerpValue(0f, 30f, rCurrentNPC.ai[1], true) * Utils.GetLerpValue(90f, 30f, rCurrentNPC.ai[1], true);
                num11 = Utils.GetLerpValue(0f, 30f, rCurrentNPC.ai[1], true) * Utils.GetLerpValue(90f, 70f, rCurrentNPC.ai[1], true);
                num12 = Utils.GetLerpValue(0f, 15f, rCurrentNPC.ai[1], true) * Utils.GetLerpValue(45f, 30f, rCurrentNPC.ai[1], true);
                color = Microsoft.Xna.Framework.Color.Lerp(color, Microsoft.Xna.Framework.Color.White, num10);
                num7 *= 1f - num12;
                num8 = 4;
                num9 = 3;
            }
            if (num == 10)
            {
                num10 = Utils.GetLerpValue(30f, 90f, rCurrentNPC.ai[1], true) * Utils.GetLerpValue(165f, 90f, rCurrentNPC.ai[1], true);
                num11 = Utils.GetLerpValue(0f, 60f, rCurrentNPC.ai[1], true) * Utils.GetLerpValue(180f, 120f, rCurrentNPC.ai[1], true);
                num12 = Utils.GetLerpValue(0f, 60f, rCurrentNPC.ai[1], true) * Utils.GetLerpValue(180f, 120f, rCurrentNPC.ai[1], true);
                color = Microsoft.Xna.Framework.Color.Lerp(color, Microsoft.Xna.Framework.Color.White, num10);
                num7 *= 1f - num12;
                num9 = 4;
            }
            if (num9 + num8 > 0)
            {
                for (int i = -num9; i <= num9 + num8; i++)
                {
                    if (i != 0)
                    {
                        Microsoft.Xna.Framework.Color color2 = Microsoft.Xna.Framework.Color.White;
                        Vector2 vector4 = vector;
                        if (num == 8 || num == 9)
{
                            float num13 = ((float)i + 5f) / 10f;
                            float num14 = 200f;
                            float num15 = (float)Main.timeForVisualEffects / 60f;
                            Matrix matrix = Matrix.CreateRotationX((num15 - 0.3f + (float)i * 0.1f) * 0.7f * 6.2831855f) * Matrix.CreateRotationY((num15 - 0.8f + (float)i * 0.3f) * 0.7f * 6.2831855f) * Matrix.CreateRotationZ((num15 + (float)i * 0.5f) * 0.1f * 6.2831855f);
                            Vector3 vector5 = Vector3.Transform(Vector3.Forward, matrix);
                            num14 += Utils.GetLerpValue(-1f, 1f, vector5.Z, true) * 150f;
                            Vector2 vector6 = new Vector2(vector5.X, vector5.Y) * num14 * num10;
                            float lerpValue = Utils.GetLerpValue(90f, 0f, rCurrentNPC.ai[1], true);
                            color2 = Main.hslToRgb(num13, 1f, MathHelper.Lerp(0.5f, 1f, lerpValue), byte.MaxValue) * 0.8f * num11;
                            color2.A /= 3;
                            vector4 += vector6.RotatedBy((double)(rCurrentNPC.ai[1] / 180f * 6.2831855f), default(Vector2));
                        }
                        if (num == 10)
{
                            if (rCurrentNPC.ai[1] >= 90f)
{
                                float num16 = (float)Main.timeForVisualEffects / 90f;
                                int num17 = i;
                                if (num17 < 0)
{
                                    num17++;
                                }
                                Vector2 vector7 = (((float)num17 + 0.5f) * 0.7853982f + 6.2831855f * num16).ToRotationVector2();
                                vector4 += vector7 * new Vector2(600f * num10, 150f * num10);
                            }
                            else
{
                                vector4 += 200f * new Vector2((float)i, 0f) * num10;
                            }
                            color2 = Microsoft.Xna.Framework.Color.White * 0.8f * num11 * num7;
                            color2.A /= 3;
                        }
                        if (i > num9)
{
                            float lerpValue2 = Utils.GetLerpValue(30f, 70f, rCurrentNPC.ai[1], true);
                            if (lerpValue2 == 0f)
{
                                goto IL_0713;
                            }
                            vector4 = vector + rCurrentNPC.velocity * -3f * ((float)i - 4f) * lerpValue2;
                            color2 *= 1f - num12;
                        }
                        mySpriteBatch.Draw(value2, vector4, new Microsoft.Xna.Framework.Rectangle?(rectangle), color2, rCurrentNPC.rotation, rectangle.Size() / 2f, rCurrentNPC.scale * 2f, npcSpriteEffect, 0f);
                        mySpriteBatch.Draw(value5, vector4, new Microsoft.Xna.Framework.Rectangle?(rectangle), color2, rCurrentNPC.rotation, rectangle.Size() / 2f, rCurrentNPC.scale * 2f, npcSpriteEffect, 0f);
                        if (flag)
{
                            Texture2D value6 = TextureAssets.Extra[187].Value;
                            Microsoft.Xna.Framework.Rectangle rectangle4 = value6.Frame(1, 8, 0, (int)(rCurrentNPC.localAI[0] / 4f) % 8, 0, 0);
                            mySpriteBatch.Draw(value6, vector4, new Microsoft.Xna.Framework.Rectangle?(rectangle4), color2, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, npcSpriteEffect, 0f);
                        }
                        mySpriteBatch.Draw(value, vector4, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), color2, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, npcSpriteEffect, 0f);
                        for (int j = 0; j < 2; j++)
{
                            if (j == num5)
{
                                mySpriteBatch.Draw(value3, vector4, new Microsoft.Xna.Framework.Rectangle?(rectangle2), color2, rCurrentNPC.rotation, vector2, rCurrentNPC.scale, npcSpriteEffect, 0f);
                            }
                            if (j == num6)
{
                                mySpriteBatch.Draw(value4, vector4, new Microsoft.Xna.Framework.Rectangle?(rectangle3), color2, rCurrentNPC.rotation, vector3, rCurrentNPC.scale, npcSpriteEffect, 0f);
                            }
                        }
                    }
                    IL_0713:;
                }
            }
            color *= num7;
            mySpriteBatch.Draw(value2, vector, new Microsoft.Xna.Framework.Rectangle?(rectangle), color, rCurrentNPC.rotation, rectangle.Size() / 2f, rCurrentNPC.scale * 2f, npcSpriteEffect, 0f);
            if (!rCurrentNPC.IsABestiaryIconDummy)
            {
                mySpriteBatch.End();
                mySpriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend, SamplerState.PointClamp, DepthStencilState.Default, RasterizerState.CullNone, null, Main.Transform);
            }
            DrawData drawData = new DrawData(value5, vector, new Microsoft.Xna.Framework.Rectangle?(rectangle), color, rCurrentNPC.rotation, rectangle.Size() / 2f, rCurrentNPC.scale * 2f, npcSpriteEffect, 0f);
            GameShaders.Misc["HallowBoss"].Apply(new DrawData?(drawData));
            drawData.Draw(mySpriteBatch);
            Main.pixelShader.CurrentTechnique.Passes[0].Apply();
            if (!rCurrentNPC.IsABestiaryIconDummy)
            {
                mySpriteBatch.End();
                mySpriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, Main.DefaultSamplerState, DepthStencilState.None, Main.Rasterizer, null, Main.Transform);
            }
            float num18 = (float)Math.Sin((double)(Main.GlobalTimeWrappedHourly * 6.2831855f * 0.5f)) * 0.5f + 0.5f;
            Microsoft.Xna.Framework.Color color3 = Main.hslToRgb((num18 * 0.08f + 0.6f) % 1f, 1f, 0.5f, byte.MaxValue);
            color3.A = 0;
            color3 *= 0.6f;
            if (NPC.ShouldEmpressBeEnraged())
            {
                color3 = Main.OurFavoriteColor;
                color3.A = 0;
                color3 *= 0.3f;
            }
            color3 *= num7 * rCurrentNPC.Opacity;
            if (flag)
            {
                Texture2D value7 = TextureAssets.Extra[187].Value;
                Microsoft.Xna.Framework.Rectangle rectangle5 = value7.Frame(1, 8, 0, (int)(rCurrentNPC.localAI[0] / 4f) % 8, 0, 0);
                mySpriteBatch.Draw(value7, vector, new Microsoft.Xna.Framework.Rectangle?(rectangle5), color, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, npcSpriteEffect, 0f);
                for (float num19 = 0f; num19 < 1f; num19 += 0.25f)
                {
                    Vector2 vector8 = rCurrentNPC.rotation.ToRotationVector2().RotatedBy((double)(num19 * 6.2831855f + 0.7853982f), default(Vector2)) * MathHelper.Lerp(2f, 8f, num18);
                    mySpriteBatch.Draw(value7, vector + vector8, new Microsoft.Xna.Framework.Rectangle?(rectangle5), color3, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, npcSpriteEffect, 0f);
                }
            }
            mySpriteBatch.Draw(value, vector, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), color, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, npcSpriteEffect, 0f);
            if (flag)
            {
                Texture2D value8 = TextureAssets.Extra[188].Value;
                for (float num20 = 0f; num20 < 1f; num20 += 0.25f)
                {
                    Vector2 vector9 = rCurrentNPC.rotation.ToRotationVector2().RotatedBy((double)(num20 * 6.2831855f + 0.7853982f), default(Vector2)) * MathHelper.Lerp(2f, 8f, num18);
                    mySpriteBatch.Draw(value8, vector + vector9, null, color3, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, npcSpriteEffect, 0f);
                }
            }
            for (int k = 0; k < 2; k++)
            {
                if (k == num5)
                {
                    mySpriteBatch.Draw(value3, vector, new Microsoft.Xna.Framework.Rectangle?(rectangle2), color, rCurrentNPC.rotation, vector2, rCurrentNPC.scale, npcSpriteEffect, 0f);
                }
                if (k == num6)
                {
                    mySpriteBatch.Draw(value4, vector, new Microsoft.Xna.Framework.Rectangle?(rectangle3), color, rCurrentNPC.rotation, vector3, rCurrentNPC.scale, npcSpriteEffect, 0f);
                }
            }
        }
References Terraria.NPC.ai, Terraria.NPC.AI_120_HallowBoss_IsInPhase2(), Microsoft.Xna.Framework.Graphics.BlendState.AlphaBlend, Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(), Microsoft.Xna.Framework.Matrix.CreateRotationX(), Microsoft.Xna.Framework.Matrix.CreateRotationY(), Microsoft.Xna.Framework.Matrix.CreateRotationZ(), Microsoft.Xna.Framework.Graphics.RasterizerState.CullNone, Microsoft.Xna.Framework.Graphics.Effect.CurrentTechnique, Microsoft.Xna.Framework.Graphics.DepthStencilState.Default, Terraria.Main.DefaultSamplerState, Terraria.DataStructures.DrawData.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Main.DrawNPCDirect_GetHallowBossArmFrame(), Microsoft.Xna.Framework.Graphics.SpriteBatch.End(), Terraria.GameContent.TextureAssets.Extra, Microsoft.Xna.Framework.Vector3.Forward, Terraria.NPC.frame, Terraria.NPC.GetAlpha(), Terraria.Utils.GetLerpValue(), Terraria.Main.hslToRgb(), int, Terraria.NPC.IsABestiaryIconDummy, Microsoft.Xna.Framework.Color.Lerp(), Microsoft.Xna.Framework.MathHelper.Lerp(), Terraria.NPC.localAI, Terraria.Graphics.Shaders.GameShaders.Misc, Microsoft.Xna.Framework.Graphics.DepthStencilState.None, Terraria.GameContent.TextureAssets.Npc, Terraria.NPC.Opacity, Terraria.Main.OurFavoriteColor, Microsoft.Xna.Framework.Graphics.EffectTechnique.Passes, Terraria.Main.pixelShader, Microsoft.Xna.Framework.Graphics.SamplerState.PointClamp, Terraria.Main.Rasterizer, Terraria.NPC.rotation, Terraria.NPC.scale, Terraria.NPC.ShouldEmpressBeEnraged(), System.Math.Sin(), Terraria.Main.timeForVisualEffects, Microsoft.Xna.Framework.Vector3.Transform(), Terraria.Main.Transform, System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Vector3.X, Microsoft.Xna.Framework.Vector3.Y, and Microsoft.Xna.Framework.Vector3.Z.
Referenced by Terraria.Main.DrawNPCDirect().