Terraria Decompiled: Terraria.Main.MouseText_DrawItemTooltip_GetLinesInfo
MouseText_DrawItemTooltip_GetLinesInfo()
static void Terraria.Main.MouseText_DrawItemTooltip_GetLinesInfo (Item item, ref int yoyoLogo, ref int researchLine, float oldKB, ref int numLines, string[] toolTipLine, Microsoft::Xna::Framework::Color[] lineColors) inline static
Definition at line 19468 of file Main.cs.
        {
            int num = ItemSlot.EstimateDisplayStack(item);
            toolTipLine[0] = Item.GetHoverName(item, num);
            Microsoft.Xna.Framework.Color color = new Microsoft.Xna.Framework.Color(190, 120, 120);
            Microsoft.Xna.Framework.Color color2 = new Microsoft.Xna.Framework.Color(120, 190, 120);
            if (item.favorited)
            {
                int i = numLines;
                numLines = i + 1;
                toolTipLine[i] = Lang.tip[56].Value;
                i = numLines;
                numLines = i + 1;
                toolTipLine[i] = Lang.tip[57].Value;
                if (Main.LocalPlayer.chest != -1)
                {
                    Item[] array = Main.LocalPlayer.GetCurrentContainer().item;
                    if (ChestUI.IsBlockedFromTransferIntoChest(item, array))
                    {
                        i = numLines;
                        numLines = i + 1;
                        toolTipLine[i] = Language.GetTextValue("UI.ItemCannotBePlacedInsideItself");
                    }
                }
            }
            if (item.social && !item.vanity && !item.hasVanityEffects)
            {
                toolTipLine[numLines] = Lang.tip[61].Value;
                numLines++;
            }
            if (item.damage > 0 && (!item.notAmmo || item.useStyle != 0) && (item.type < 71 || item.type > 74 || Main.player[Main.myPlayer].HasItem(905)))
            {
                float num2 = 5E-06f;
                int num3 = item.damage;
                num3 = (int)((float)num3 * ItemID.Sets.ToolTipDamageMultiplier[item.type]);
                if (ItemID.Sets.RapidAttackBonusDamage[item.type])
                {
                    num3 = Main.LocalPlayer.ApplyRapidAttackBonus(num3, item.type, false);
                }
                toolTipLine[numLines] = string.Concat((int)(Main.LocalPlayer.GetWeaponDamageMultiplier(item) * (float)num3 + num2));
                if (item.melee)
                {
                    int num4 = numLines;
                    toolTipLine[num4] += Lang.tip[2].Value;
                }
                else if (item.ranged)
                {
                    int num5 = numLines;
                    toolTipLine[num5] += Lang.tip[3].Value;
                }
                else if (item.magic)
                {
                    int num6 = numLines;
                    toolTipLine[num6] += Lang.tip[4].Value;
                }
                else if (item.summon)
                {
                    int num7 = numLines;
                    toolTipLine[num7] += Lang.tip[53].Value;
                }
                else
                {
                    int num8 = numLines;
                    toolTipLine[num8] += Lang.tip[55].Value;
                }
                numLines++;
                if (item.melee)
                {
                    int num9 = Main.player[Main.myPlayer].meleeCrit - Main.LocalPlayer.inventory[Main.LocalPlayer.selectedItem].crit + item.GetVisualCritChance(Main.LocalPlayer);
                    toolTipLine[numLines] = num9 + Lang.tip[5].Value;
                    numLines++;
                }
                else if (item.ranged)
                {
                    int num10 = Main.player[Main.myPlayer].rangedCrit - Main.LocalPlayer.inventory[Main.LocalPlayer.selectedItem].crit + item.GetVisualCritChance(Main.LocalPlayer);
                    toolTipLine[numLines] = num10 + Lang.tip[5].Value;
                    numLines++;
                }
                else if (item.magic)
                {
                    int num11 = Main.player[Main.myPlayer].magicCrit - Main.LocalPlayer.inventory[Main.LocalPlayer.selectedItem].crit + item.GetVisualCritChance(Main.LocalPlayer);
                    toolTipLine[numLines] = num11 + Lang.tip[5].Value;
                    numLines++;
                }
                if (item.useStyle != 0 && (!item.summon || (item.shoot >= 0 && ProjectileID.Sets.IsAWhip[item.shoot])))
                {
                    if (item.useAnimation <= 8)
                    {
                        toolTipLine[numLines] = Lang.tip[6].Value;
                    }
                    else if (item.useAnimation <= 20)
                    {
                        toolTipLine[numLines] = Lang.tip[7].Value;
                    }
                    else if (item.useAnimation <= 25)
                    {
                        toolTipLine[numLines] = Lang.tip[8].Value;
                    }
                    else if (item.useAnimation <= 30)
                    {
                        toolTipLine[numLines] = Lang.tip[9].Value;
                    }
                    else if (item.useAnimation <= 35)
                    {
                        toolTipLine[numLines] = Lang.tip[10].Value;
                    }
                    else if (item.useAnimation <= 45)
                    {
                        toolTipLine[numLines] = Lang.tip[11].Value;
                    }
                    else if (item.useAnimation <= 55)
                    {
                        toolTipLine[numLines] = Lang.tip[12].Value;
                    }
                    else
                    {
                        toolTipLine[numLines] = Lang.tip[13].Value;
                    }
                    numLines++;
                }
                float num12 = item.knockBack;
                if (item.summon)
                {
                    num12 += Main.player[Main.myPlayer].minionKB;
                }
                if ((Main.player[Main.myPlayer].magicQuiver && item.useAmmo == AmmoID.Arrow) || item.useAmmo == AmmoID.Stake)
                {
                    num12 = (float)((int)(num12 * 1.1f));
                }
                if (Main.player[Main.myPlayer].inventory[Main.player[Main.myPlayer].selectedItem].type == 3106 && item.type == 3106)
                {
                    num12 += num12 * (1f - Main.player[Main.myPlayer].stealth);
                }
                if (num12 == 0f)
                {
                    toolTipLine[numLines] = Lang.tip[14].Value;
                }
                else if ((double)num12 <= 1.5)
                {
                    toolTipLine[numLines] = Lang.tip[15].Value;
                }
                else if (num12 <= 3f)
                {
                    toolTipLine[numLines] = Lang.tip[16].Value;
                }
                else if (num12 <= 4f)
                {
                    toolTipLine[numLines] = Lang.tip[17].Value;
                }
                else if (num12 <= 6f)
                {
                    toolTipLine[numLines] = Lang.tip[18].Value;
                }
                else if (num12 <= 7f)
                {
                    toolTipLine[numLines] = Lang.tip[19].Value;
                }
                else if (num12 <= 9f)
                {
                    toolTipLine[numLines] = Lang.tip[20].Value;
                }
                else if (num12 <= 11f)
                {
                    toolTipLine[numLines] = Lang.tip[21].Value;
                }
                else
                {
                    toolTipLine[numLines] = Lang.tip[22].Value;
                }
                numLines++;
            }
            if (item.fishingPole > 0)
            {
                toolTipLine[numLines] = Language.GetTextValue("GameUI.PrecentFishingPower", item.fishingPole);
                numLines++;
                toolTipLine[numLines] = Language.GetTextValue("GameUI.BaitRequired");
                numLines++;
            }
            if (item.bait > 0)
            {
                toolTipLine[numLines] = Language.GetTextValue("GameUI.BaitPower", item.bait);
                numLines++;
            }
            if (item.headSlot > 0 || item.bodySlot > 0 || item.legSlot > 0 || item.accessory || Main.projHook[item.shoot] || item.mountType != -1 || (item.buffType > 0 && (Main.lightPet[item.buffType] || Main.vanityPet[item.buffType])))
            {
                if ((item.type == 854 || item.type == 3035) && Main.npcShop > 0)
                {
                    toolTipLine[numLines] = Lang.tip[60].Value;
                }
                else
                {
                    toolTipLine[numLines] = Lang.tip[23].Value;
                }
                numLines++;
            }
            if (item.tileWand > 0)
            {
                toolTipLine[numLines] = Lang.tip[52].Value + Lang.GetItemNameValue(item.tileWand);
                numLines++;
            }
            if (item.questItem)
            {
                toolTipLine[numLines] = Lang.inter[65].Value;
                numLines++;
            }
            if (item.vanity)
            {
                toolTipLine[numLines] = Lang.tip[24].Value;
                numLines++;
            }
            if (item.defense > 0)
            {
                toolTipLine[numLines] = item.defense + Lang.tip[25].Value;
                numLines++;
            }
            if (item.pick > 0)
            {
                toolTipLine[numLines] = item.pick + Lang.tip[26].Value;
                numLines++;
            }
            if (item.axe > 0)
            {
                toolTipLine[numLines] = item.axe * 5 + Lang.tip[27].Value;
                numLines++;
            }
            if (item.hammer > 0)
            {
                toolTipLine[numLines] = item.hammer + Lang.tip[28].Value;
                numLines++;
            }
            if (item.tileBoost != 0)
            {
                int tileBoost = item.tileBoost;
                if (tileBoost > 0)
                {
                    toolTipLine[numLines] = "+" + tileBoost + Lang.tip[54].Value;
                }
                else
                {
                    toolTipLine[numLines] = tileBoost + Lang.tip[54].Value;
                }
                numLines++;
            }
            if (item.healLife > 0)
            {
                if (item.type == 3001)
                {
                    int healLife = item.healLife;
                    int num13 = 120;
                    toolTipLine[numLines] = Language.GetTextValue("CommonItemTooltip.RestoresLifeRange", healLife, num13);
                }
                else
                {
                    toolTipLine[numLines] = Language.GetTextValue("CommonItemTooltip.RestoresLife", item.healLife);
                }
                numLines++;
            }
            if (item.healMana > 0)
            {
                toolTipLine[numLines] = Language.GetTextValue("CommonItemTooltip.RestoresMana", item.healMana);
                numLines++;
            }
            if (item.mana > 0 && ((item.type != 127 && item.type != 4347 && item.type != 4348 && item.type != 514) || !Main.player[Main.myPlayer].spaceGun))
            {
                toolTipLine[numLines] = Language.GetTextValue("CommonItemTooltip.UsesMana", (int)((float)item.mana * Main.player[Main.myPlayer].manaCost));
                numLines++;
            }
            if (item.createWall > 0 || item.createTile > -1 || item.type == 849)
            {
                if (ItemID.Sets.PlaceTileOnAltUse[item.type] || item.consumable)
                {
                    toolTipLine[numLines] = Lang.tip[33].Value;
                    numLines++;
                }
            }
            else if (item.ammo > 0 && !item.notAmmo)
            {
                toolTipLine[numLines] = Lang.tip[34].Value;
                numLines++;
            }
            else if (item.consumable && !item.chlorophyteExtractinatorConsumable)
            {
                toolTipLine[numLines] = Lang.tip[35].Value;
                numLines++;
            }
            if (item.material)
            {
                toolTipLine[numLines] = Lang.tip[36].Value;
                numLines++;
            }
            if ((item.createTile > -1 && (TileID.Sets.Wiring.IsATrigger[item.createTile] || TileID.Sets.Wiring.IsAMechanism[item.createTile])) & (item.createTile != 105 || ItemID.Sets.IsWireableStatue[item.type]))
            {
                toolTipLine[numLines] = Language.GetTextValue("CommonItemTooltip.Wireable");
                numLines++;
            }
            if (item.createTile == 21 || item.createTile == 467)
            {
                toolTipLine[numLines] = Language.GetTextValue("CommonItemTooltip.Container");
                numLines++;
            }
            if (item.createTile == 441 || item.createTile == 468)
            {
                toolTipLine[numLines] = Language.GetTextValue("CommonItemTooltip.WireTrigger");
                numLines++;
            }
            if (item.ToolTip != null)
            {
                for (int j = 0; j < item.ToolTip.Lines; j++)
                {
                    if (j == 0 && ItemID.Sets.UsesCursedByPlanteraTooltip[item.type] && !NPC.downedPlantBoss)
                    {
                        toolTipLine[numLines] = Lang.tip[59].Value;
                        numLines++;
                    }
                    else
                    {
                        toolTipLine[numLines] = item.ToolTip.GetLine(j);
                        numLines++;
                    }
                }
            }
            if (Main.tenthAnniversaryWorld && item.type == 238)
            {
                toolTipLine[numLines] = Language.GetTextValue("CommonItemTooltip.WizardHatDuringAnniversary");
                numLines++;
            }
            if (Main.getGoodWorld && item.type == 1127)
            {
                toolTipLine[numLines] = Language.GetTextValue("CommonItemTooltip.BurningBlock");
                numLines++;
            }
            if (SpecialSeedFeatures.Mechdusa)
            {
                if (item.type == 556 || item.type == 557 || item.type == 544)
                {
                    numLines--;
                    toolTipLine[numLines] = Language.GetTextValue("CommonItemTooltip.MechSummonDuringEverything");
                    numLines++;
                }
            }
            else if (item.type == 5334)
            {
                numLines--;
                toolTipLine[numLines] = "";
                numLines--;
                toolTipLine[numLines] = Language.GetTextValue("CommonItemTooltip.MechdusaSummonNotDuringEverything");
                numLines++;
            }
            if ((item.type == 3818 || item.type == 3819 || item.type == 3820 || item.type == 3824 || item.type == 3825 || item.type == 3826 || item.type == 3829 || item.type == 3830 || item.type == 3831 || item.type == 3832 || item.type == 3833 || item.type == 3834) && !Main.player[Main.myPlayer].downedDD2EventAnyDifficulty)
            {
                toolTipLine[numLines] = Lang.misc[104].Value;
                numLines++;
            }
            if (item.buffType > 0 && BuffID.Sets.IsWellFed[item.buffType] && Main.expertMode)
            {
                toolTipLine[numLines] = Lang.misc[40].Value;
                numLines++;
            }
            if (item.buffTime > 0)
            {
                string text;
                if (item.buffTime / 60 >= 60)
                {
                    text = Language.GetTextValue("CommonItemTooltip.MinuteDuration", Math.Round((double)(item.buffTime / 60) / 60.0));
                }
                else
                {
                    text = Language.GetTextValue("CommonItemTooltip.SecondDuration", Math.Round((double)item.buffTime / 60.0));
                }
                toolTipLine[numLines] = text;
                numLines++;
            }
            if (item.type == 3262 || item.type == 3282 || item.type == 3283 || item.type == 3284 || item.type == 3285 || item.type == 3286 || item.type == 3316 || item.type == 3315 || item.type == 3317 || item.type == 3291 || item.type == 3389)
            {
                toolTipLine[numLines] = " ";
                yoyoLogo = numLines;
                numLines++;
            }
            if (item.prefix > 0)
            {
                Item item2 = Main.tooltipPrefixComparisonItem;
                if (item2 == null || item2.type != item.type)
                {
                    item2 = new Item();
                    item2.SetDefaults(item.type, null);
                }
                if (item2.damage != item.damage)
                {
                    double num14 = (double)((float)item.damage - (float)item2.damage);
                    num14 = num14 / (double)item2.damage * 100.0;
                    num14 = Math.Round(num14);
                    if (num14 > 0.0)
                    {
                        toolTipLine[numLines] = "+" + num14 + Lang.tip[39].Value;
                    }
                    else
                    {
                        toolTipLine[numLines] = num14 + Lang.tip[39].Value;
                    }
                    lineColors[numLines] = ((num14 < 0.0) ? color : color2);
                    numLines++;
                }
                if (item2.useAnimation != item.useAnimation)
                {
                    double num15 = (double)((float)item.useAnimation - (float)item2.useAnimation);
                    num15 = num15 / (double)item2.useAnimation * 100.0;
                    num15 = Math.Round(num15);
                    num15 *= -1.0;
                    if (num15 > 0.0)
                    {
                        toolTipLine[numLines] = "+" + num15 + Lang.tip[40].Value;
                    }
                    else
                    {
                        toolTipLine[numLines] = num15 + Lang.tip[40].Value;
                    }
                    lineColors[numLines] = ((num15 < 0.0) ? color : color2);
                    numLines++;
                }
                if (item2.crit != item.crit)
                {
                    double num16 = (double)((float)item.crit - (float)item2.crit);
                    if (num16 > 0.0)
                    {
                        toolTipLine[numLines] = "+" + num16 + Lang.tip[41].Value;
                    }
                    else
                    {
                        toolTipLine[numLines] = num16 + Lang.tip[41].Value;
                    }
                    lineColors[numLines] = ((num16 < 0.0) ? color : color2);
                    numLines++;
                }
                if (item2.mana != item.mana)
                {
                    double num17 = (double)((float)item.mana - (float)item2.mana);
                    num17 = num17 / (double)item2.mana * 100.0;
                    num17 = Math.Round(num17);
                    if (num17 > 0.0)
                    {
                        toolTipLine[numLines] = "+" + num17 + Lang.tip[42].Value;
                    }
                    else
                    {
                        toolTipLine[numLines] = num17 + Lang.tip[42].Value;
                    }
                    lineColors[numLines] = ((num17 > 0.0) ? color : color2);
                    numLines++;
                }
                if (item2.scale != item.scale)
                {
                    double num18 = (double)(item.scale - item2.scale);
                    num18 = num18 / (double)item2.scale * 100.0;
                    num18 = Math.Round(num18);
                    if (num18 > 0.0)
                    {
                        toolTipLine[numLines] = "+" + num18 + Lang.tip[43].Value;
                    }
                    else
                    {
                        toolTipLine[numLines] = num18 + Lang.tip[43].Value;
                    }
                    lineColors[numLines] = ((num18 < 0.0) ? color : color2);
                    numLines++;
                }
                if (item2.shootSpeed != item.shootSpeed)
                {
                    double num19 = (double)(item.shootSpeed - item2.shootSpeed);
                    num19 = num19 / (double)item2.shootSpeed * 100.0;
                    num19 = Math.Round(num19);
                    if (num19 > 0.0)
                    {
                        toolTipLine[numLines] = "+" + num19 + Lang.tip[44].Value;
                    }
                    else
                    {
                        toolTipLine[numLines] = num19 + Lang.tip[44].Value;
                    }
                    lineColors[numLines] = ((num19 < 0.0) ? color : color2);
                    numLines++;
                }
                if (item2.knockBack != oldKB)
                {
                    double num20 = (double)(oldKB - item2.knockBack);
                    num20 = num20 / (double)item2.knockBack * 100.0;
                    num20 = Math.Round(num20);
                    if (num20 > 0.0)
                    {
                        toolTipLine[numLines] = "+" + num20 + Lang.tip[45].Value;
                    }
                    else
                    {
                        toolTipLine[numLines] = num20 + Lang.tip[45].Value;
                    }
                    lineColors[numLines] = ((num20 < 0.0) ? color : color2);
                    numLines++;
                }
                if (item2.armorPenetration != item.armorPenetration)
                {
                    int num21 = item.armorPenetration - item2.armorPenetration;
                    toolTipLine[numLines] = Language.GetTextValue("CommonItemTooltip.PrefixArmorPenetration", num21);
                    lineColors[numLines] = ((num21 < 0) ? color : color2);
                    numLines++;
                }
                if (item2.bonusTagDamage != item.bonusTagDamage)
                {
                    int num22 = item.bonusTagDamage - item2.bonusTagDamage;
                    toolTipLine[numLines] = Language.GetTextValue("CommonItemTooltip.PrefixTagDamage", num22);
                    lineColors[numLines] = ((num22 < 0) ? color : color2);
                    numLines++;
                }
                if (item.prefix == 62)
                {
                    toolTipLine[numLines] = "+1" + Lang.tip[25].Value;
                    lineColors[numLines] = color2;
                    numLines++;
                }
                if (item.prefix == 63)
                {
                    toolTipLine[numLines] = "+2" + Lang.tip[25].Value;
                    lineColors[numLines] = color2;
                    numLines++;
                }
                if (item.prefix == 64)
                {
                    toolTipLine[numLines] = "+3" + Lang.tip[25].Value;
                    lineColors[numLines] = color2;
                    numLines++;
                }
                if (item.prefix == 65)
                {
                    toolTipLine[numLines] = "+4" + Lang.tip[25].Value;
                    lineColors[numLines] = color2;
                    numLines++;
                }
                if (item.prefix == 66)
                {
                    toolTipLine[numLines] = "+20 " + Lang.tip[31].Value;
                    lineColors[numLines] = color2;
                    numLines++;
                }
                if (item.prefix == 67)
                {
                    toolTipLine[numLines] = "+2" + Lang.tip[5].Value;
                    lineColors[numLines] = color2;
                    numLines++;
                }
                if (item.prefix == 68)
                {
                    toolTipLine[numLines] = "+4" + Lang.tip[5].Value;
                    lineColors[numLines] = color2;
                    numLines++;
                }
                if (item.prefix == 69)
                {
                    toolTipLine[numLines] = "+1" + Lang.tip[39].Value;
                    lineColors[numLines] = color2;
                    numLines++;
                }
                if (item.prefix == 70)
                {
                    toolTipLine[numLines] = "+2" + Lang.tip[39].Value;
                    lineColors[numLines] = color2;
                    numLines++;
                }
                if (item.prefix == 71)
                {
                    toolTipLine[numLines] = "+3" + Lang.tip[39].Value;
                    lineColors[numLines] = color2;
                    numLines++;
                }
                if (item.prefix == 72)
                {
                    toolTipLine[numLines] = "+4" + Lang.tip[39].Value;
                    lineColors[numLines] = color2;
                    numLines++;
                }
                if (item.prefix == 73)
                {
                    toolTipLine[numLines] = "+1" + Lang.tip[46].Value;
                    lineColors[numLines] = color2;
                    numLines++;
                }
                if (item.prefix == 74)
                {
                    toolTipLine[numLines] = "+2" + Lang.tip[46].Value;
                    lineColors[numLines] = color2;
                    numLines++;
                }
                if (item.prefix == 75)
                {
                    toolTipLine[numLines] = "+3" + Lang.tip[46].Value;
                    lineColors[numLines] = color2;
                    numLines++;
                }
                if (item.prefix == 76)
                {
                    toolTipLine[numLines] = "+4" + Lang.tip[46].Value;
                    lineColors[numLines] = color2;
                    numLines++;
                }
                if (item.prefix == 77)
                {
                    toolTipLine[numLines] = "+1" + Lang.tip[47].Value;
                    lineColors[numLines] = color2;
                    numLines++;
                }
                if (item.prefix == 78)
                {
                    toolTipLine[numLines] = "+2" + Lang.tip[47].Value;
                    lineColors[numLines] = color2;
                    numLines++;
                }
                if (item.prefix == 79)
                {
                    toolTipLine[numLines] = "+3" + Lang.tip[47].Value;
                    lineColors[numLines] = color2;
                    numLines++;
                }
                if (item.prefix == 80)
                {
                    toolTipLine[numLines] = "+4" + Lang.tip[47].Value;
                    lineColors[numLines] = color2;
                    numLines++;
                }
            }
            if (true)
            {
                ArmorSetBonus[] array2 = ArmorSetBonuses.SetsContaining[item.type];
                if (array2.Length != 0)
                {
                    if (!item.wornArmor)
                    {
                        toolTipLine[numLines] = array2[0].GetTooltipForSinglePiece(item.type);
                        lineColors[numLines] = new Microsoft.Xna.Framework.Color(130, 130, 130, 190);
                        numLines++;
                    }
                    else
                    {
                        ArmorSetBonus.QueryResult queryResult = default(ArmorSetBonus.QueryResult);
                        ArmorSetBonus.QueryContext queryContext = new ArmorSetBonus.QueryContext(Main.LocalPlayer);
                        ArmorSetBonus armorSetBonus = null;
                        foreach (ArmorSetBonus armorSetBonus2 in ArmorSetBonuses.SetsContaining[item.type])
{
                            if (armorSetBonus == null)
{
                                armorSetBonus = armorSetBonus2;
                            }
                            ArmorSetBonus.QueryResult queryResult2 = armorSetBonus2.QueryCount(queryContext);
                            bool flag = false;
                            if (queryResult.ItemsNeeded < queryResult2.ItemsNeeded)
{
                                flag = true;
                            }
                            if (queryResult.ItemsNeeded == queryResult2.ItemsNeeded && queryResult.ItemsFound < queryResult2.ItemsFound)
{
                                flag = true;
                            }
                            if (flag)
{
                                queryResult = queryResult2;
                                armorSetBonus = armorSetBonus2;
                            }
                        }
                        toolTipLine[numLines] = armorSetBonus.GetTooltipForWornArmor(queryContext, queryResult);
                        lineColors[numLines] = (queryResult.Complete ? Microsoft.Xna.Framework.Color.LimeGreen : new Microsoft.Xna.Framework.Color(130, 130, 130));
                        numLines++;
                    }
                }
                if (Main.player[Main.myPlayer].setBonus != "")
                {
                    toolTipLine[numLines] = Lang.tip[48].Value + " " + Main.player[Main.myPlayer].setBonus;
                    numLines++;
                }
            }
            if (item.expert)
            {
                toolTipLine[numLines] = Language.GetTextValue("GameUI.Expert");
                numLines++;
            }
            if (item.rare == -13)
            {
                toolTipLine[numLines] = Language.GetTextValue("GameUI.Master");
                numLines++;
            }
            int num23;
            int num24;
            if ((item.tooltipContext == 0 || item.tooltipContext == 2 || item.tooltipContext == 1 || item.tooltipContext == 3 || item.tooltipContext == 4 || item.tooltipContext == 32 || item.tooltipContext == 15 || item.tooltipContext == 6 || item.tooltipContext == 22 || item.tooltipContext == 35 || item.tooltipContext == 7 || item.tooltipContext == 5 || item.tooltipContext == 29 || item.tooltipContext == 34 || item.tooltipContext == 41 || item.tooltipContext == 42 || item.tooltipContext == 43) && Main.LocalPlayer.difficulty == 3 && Main.LocalPlayerCreativeTracker.ItemSacrifices.TryGetSacrificeNumbers(item.type, out num23, out num24))
            {
                string text2;
                if (num23 < num24)
                {
                    toolTipLine[numLines] = Language.GetTextValue("CommonItemTooltip.CreativeSacrificeNeeded", num24 - num23);
                    researchLine = numLines;
                    numLines++;
                }
                else if (item.tooltipContext == 29 && Main.LocalPlayerCreativeTracker.ItemSacrifices.TryGetTeammateUnlockCredit(item.type, out text2))
                {
                    toolTipLine[numLines] = Language.GetTextValue("CommonItemTooltip.ItemUnlockedByTeammate", text2);
                    researchLine = numLines;
                    numLines++;
                }
            }
            string bestiaryNotes = item.BestiaryNotes;
            if (!string.IsNullOrWhiteSpace(bestiaryNotes))
            {
                foreach (string text3 in bestiaryNotes.Split(new char[] { '\n' }))
                {
                    int num25 = numLines;
                    numLines = num25 + 1;
                    toolTipLine[num25] = text3;
                }
            }
        }
References Terraria.Player.ApplyRapidAttackBonus(), Terraria.Item.armorPenetration, System.array, Terraria.ID.AmmoID.Arrow, Terraria.Item.bonusTagDamage, Terraria.Player.chest, Terraria.Item.crit, Terraria.Item.damage, Terraria.Player.downedDD2EventAnyDifficulty, Terraria.NPC.downedPlantBoss, Microsoft.Xna.Framework.Input.E, Terraria.UI.ItemSlot.EstimateDisplayStack(), Terraria.Main.expertMode, Terraria.Player.GetCurrentContainer(), Terraria.Main.getGoodWorld, Terraria.Item.GetHoverName(), Terraria.Lang.GetItemNameValue(), Terraria.Localization.Language.GetTextValue(), Terraria.DataStructures.ArmorSetBonus.GetTooltipForSinglePiece(), Terraria.Player.GetWeaponDamageMultiplier(), Terraria.Player.HasItem(), int, Terraria.Lang.inter, Terraria.Player.inventory, Terraria.ID.TileID.Sets.Wiring.IsAMechanism, Terraria.ID.TileID.Sets.Wiring.IsATrigger, Terraria.ID.ProjectileID.Sets.IsAWhip, Terraria.UI.ChestUI.IsBlockedFromTransferIntoChest(), Terraria.ID.BuffID.Sets.IsWellFed, Terraria.ID.ItemID.Sets.IsWireableStatue, System.item, Terraria.Chest.item, Terraria.GameContent.Creative.CreativeUnlocksTracker.ItemSacrifices, Terraria.DataStructures.ArmorSetBonus.QueryResult.ItemsFound, Terraria.DataStructures.ArmorSetBonus.QueryResult.ItemsNeeded, Terraria.Item.knockBack, Terraria.Main.lightPet, Terraria.Main.LocalPlayer, Terraria.Main.LocalPlayerCreativeTracker, Terraria.Player.magicCrit, Terraria.Player.magicQuiver, Terraria.Item.mana, Terraria.Player.manaCost, Terraria.GameContent.SpecialSeedFeatures.Mechdusa, Terraria.Player.meleeCrit, Terraria.Player.minionKB, Terraria.Lang.misc, Terraria.Main.myPlayer, Terraria.ID.ItemID.Sets.PlaceTileOnAltUse, Terraria.Main.player, Terraria.Main.projHook, Terraria.DataStructures.ArmorSetBonus.QueryCount(), Terraria.Player.rangedCrit, Terraria.ID.ItemID.Sets.RapidAttackBonusDamage, System.Math.Round(), Terraria.Item.scale, Terraria.Player.selectedItem, Terraria.Player.setBonus, Terraria.Item.SetDefaults(), Terraria.DataStructures.ArmorSetBonuses.SetsContaining, Terraria.Item.shootSpeed, Terraria.Player.spaceGun, Terraria.ID.AmmoID.Stake, Terraria.Player.stealth, Terraria.Main.tenthAnniversaryWorld, System.text, Terraria.Lang.tip, Terraria.ID.ItemID.Sets.ToolTipDamageMultiplier, Terraria.Main.tooltipPrefixComparisonItem, Terraria.GameContent.Creative.ItemsSacrificedUnlocksTracker.TryGetSacrificeNumbers(), Terraria.GameContent.Creative.ItemsSacrificedUnlocksTracker.TryGetTeammateUnlockCredit(), Terraria.Item.type, Terraria.Item.useAnimation, Terraria.ID.ItemID.Sets.UsesCursedByPlanteraTooltip, Terraria.Localization.LocalizedText.Value, and Terraria.Main.vanityPet.
Referenced by Terraria.GameContent.Creative.ItemFilters.BySearch.FitsFilter(), and Terraria.Main.MouseText_DrawItemTooltip().