Terraria Decompiled: Terraria.Main.DrawTrail
DrawTrail()
static void Terraria.Main.DrawTrail (Projectile proj, Vector2 rotatableOffsetFromCenter, Microsoft::Xna::Framework::Color baseColor) inline static private
Definition at line 27097 of file Main.cs.
        {
            Vector2 vector = proj.Size / 2f;
            Texture2D value = TextureAssets.MagicPixel.Value;
            Microsoft.Xna.Framework.Rectangle rectangle = new Microsoft.Xna.Framework.Rectangle(0, 0, 1, 1);
            Vector2[] oldPos = proj.oldPos;
            float[] oldRot = proj.oldRot;
            int num = oldPos.Length;
            for (int i = num - 1; i > 0; i--)
            {
                if (!(oldPos[i] == Vector2.Zero))
                {
                    Vector2 vector2 = oldPos[i] + vector + rotatableOffsetFromCenter.RotatedBy((double)oldRot[i], default(Vector2));
                    Vector2 vector3 = oldPos[i - 1] + vector + rotatableOffsetFromCenter.RotatedBy((double)oldRot[i - 1], default(Vector2)) - vector2;
                    float num2 = vector3.Length();
                    float num3 = vector3.ToRotation();
                    float num4 = Utils.Remap((float)i, 0f, (float)num, 1f, 0f, true);
                    Main.EntitySpriteDraw(value, vector2 - Main.screenPosition, new Microsoft.Xna.Framework.Rectangle?(rectangle), baseColor * num4, num3 + 1.5707964f, new Vector2((float)rectangle.Width / 2f, (float)rectangle.Height), new Vector2(4f, num2), SpriteEffects.None, 0f);
                }
            }
        }
References Terraria.Main.EntitySpriteDraw(), Microsoft.Xna.Framework.Rectangle.Height, Microsoft.Xna.Framework.Vector2.Length(), Terraria.GameContent.TextureAssets.MagicPixel, Terraria.Projectile.oldPos, Terraria.Projectile.oldRot, Terraria.Utils.Remap(), Terraria.Main.screenPosition, System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Rectangle.Width, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.Main.DrawContinuousTrail(), and Terraria.Main.DrawProjDirect().