Terraria Decompiled: Terraria.Main.TriggerPing
TriggerPing()
static void Terraria.Main.TriggerPing (Vector2 position) inline static
Definition at line 57344 of file Main.cs.
        {
            if (Main.dedServ)
            {
                return;
            }
            Main.Pings.Add(position);
            if (Main.netMode == 1)
            {
                NetManager.Instance.SendToServer(NetPingModule.Serialize(position));
            }
        }
References Terraria.Map.PingMapLayer.Add(), Terraria.Main.dedServ, Terraria.Net.NetManager.Instance, Terraria.Main.netMode, Terraria.Main.Pings, Terraria.Net.NetManager.SendToServer(), and Terraria.GameContent.NetModules.NetPingModule.Serialize().
Referenced by Terraria.Main.DrawMap().