Terraria Decompiled: Terraria.Main.LoadItem
LoadItem()
void Terraria.Main.LoadItem (int i) inline
Definition at line 59888 of file Main.cs.
        {
            if (TextureAssets.Item[i].State == null)
            {
                Main.Assets.Request<Texture2D>(TextureAssets.Item[i].Name, 1);
            }
        }
References Terraria.Main.Assets, Terraria.GameContent.TextureAssets.Item, ReLogic.Content.Asset< T >.Name, and ReLogic.Content.Asset< T >.State.
Referenced by Terraria.Map.BossBagMapLayer.Draw(), Terraria.Graphics.Renderers.FakeFishParticle.Draw(), Terraria.Main.DrawInterface_40_InteractItemIcon(), Terraria.Main.DrawItem(), Terraria.UI.ItemSlot.DrawItemIcon(), Terraria.UI.ItemSlot.DrawMoney(), Terraria.Main.DrawNPCExtras(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_27_HeldItem(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_30_BladedGlove(), Terraria.Main.DrawProjDirect(), Terraria.Main.DrawProjWithStarryTrail(), Terraria.GameContent.UI.CustomCurrencySingleCoin.DrawSavingsMoney(), Terraria.GameContent.UI.Elements.UIDynamicItemCollection< TEntry >.DrawSelf(), Terraria.GameContent.Drawing.TileDrawing.DrawSpecialTilesLegacy(), Terraria.Main.DrawWallOfFish(), Terraria.Item.GetDrawHitbox(), Terraria.Main.GetItemDrawFrame(), Terraria.Player.GetItemDrawFrame(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_SkeletonMerchantSearchesThroughBones(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_SantaItemExample(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_PaladinsShieldHit(), and Terraria.GameContent.UI.Chat.ItemTagHandler.ItemSnippet.UniqueDraw().