Terraria Decompiled: Terraria.Main.startDedInputCallBack
startDedInputCallBack()
static void Terraria.Main.startDedInputCallBack () inline static
Definition at line 4035 of file Main.cs.
        {
            while (!Netplay.Disconnect)
            {
                Console.Write(": ");
                string text = Main.ReadLineInput();
                text = text;
                try
                {
                    if (Language.GetText("CLI.Help_Command").EqualsCommand(text))
                    {
                        Console.WriteLine(Language.GetTextValue("CLI.AvailableCommands"));
                        Console.WriteLine("");
                        List<string> list = new List<string>
{
                            "Help", "Playing", "Clear", "Exit", "ExitNoSave", "Save", "Kick", "Ban", "Password", "SetPassword",
                            "Version", "Time", "Port", "MaxPlayers", "Say", "MOTD", "SetMOTD", "Dawn", "Noon", "Dusk",
                            "Midnight", "Settle", "Seed"
                        };
                        int num = 0;
                        for (int i = 0; i < list.Count; i++)
{
                            string text2 = (Language.Exists("CLI." + list[i] + "_Example") ? Language.GetTextValue("CLI." + list[i] + "_Example") : Language.GetTextValue("CLI." + list[i] + "_Command"));
                            num = Math.Max(num, Main.EstimatedMonospacedWidth(text2));
                        }
                        int num2 = (num + 1) / 8;
                        for (int j = 0; j < list.Count; j++)
{
                            string text3 = (Language.Exists("CLI." + list[j] + "_Example") ? Language.GetTextValue("CLI." + list[j] + "_Example") : Language.GetTextValue("CLI." + list[j] + "_Command"));
                            Console.WriteLine(text3 + new string('\t', num2 - Main.EstimatedMonospacedWidth(text3) / 8) + Language.GetTextValue("CLI." + list[j] + "_Description"));
                        }
                    }
                    else if (Language.GetText("CLI.Settle_Command").EqualsCommand(text))
                    {
                        if (!Liquid.panicMode)
{
                            Liquid.StartPanic();
                        }
                        else
{
                            Console.WriteLine(Language.GetTextValue("CLI.WaterIsAlreadySettling"));
                        }
                    }
                    else if (Language.GetText("CLI.Dawn_Command").EqualsCommand(text))
                    {
                        Main.dayTime = true;
                        Main.time = 0.0;
                        NetMessage.SendData(7, -1, -1, null, 0, 0f, 0f, 0f, 0, 0, 0);
                    }
                    else if (Language.GetText("CLI.Dusk_Command").EqualsCommand(text))
                    {
                        Main.dayTime = false;
                        Main.time = 0.0;
                        NetMessage.SendData(7, -1, -1, null, 0, 0f, 0f, 0f, 0, 0, 0);
                    }
                    else if (Language.GetText("CLI.Noon_Command").EqualsCommand(text))
                    {
                        Main.dayTime = true;
                        Main.time = 27000.0;
                        NetMessage.SendData(7, -1, -1, null, 0, 0f, 0f, 0f, 0, 0, 0);
                    }
                    else if (Language.GetText("CLI.Midnight_Command").EqualsCommand(text))
                    {
                        Main.dayTime = false;
                        Main.time = 16200.0;
                        NetMessage.SendData(7, -1, -1, null, 0, 0f, 0f, 0f, 0, 0, 0);
                    }
                    else if (Language.GetText("CLI.ExitNoSave_Command").EqualsCommand(text))
                    {
                        Netplay.SaveOnServerExit = false;
                        Netplay.Disconnect = true;
                    }
                    else if (Language.GetText("CLI.Exit_Command").EqualsCommand(text))
                    {
                        Netplay.Disconnect = true;
                        SocialAPI.Shutdown();
                    }
                    else if (Language.GetText("CLI.FPS_Command").EqualsCommand(text))
                    {
                        if (!Main.dedServFPS)
{
                            Main.dedServFPS = true;
                            Main.fpsTimer.Reset();
                        }
                        else
{
                            Main.dedServCount1 = 0;
                            Main.dedServCount2 = 0;
                            Main.dedServFPS = false;
                        }
                    }
                    else if (Language.GetText("CLI.Save_Command").EqualsCommand(text))
                    {
                        WorldFile.SaveWorld(false, false, false);
                    }
                    else if (Language.GetText("CLI.Time_Command").EqualsCommand(text))
                    {
                        string text4 = Language.GetTextValue("GameUI.TimeAtMorning");
                        double num3 = Main.time;
                        if (!Main.dayTime)
{
                            num3 += 54000.0;
                        }
                        num3 = num3 / 86400.0 * 24.0;
                        double num4 = 7.5;
                        num3 = num3 - num4 - 12.0;
                        if (num3 < 0.0)
{
                            num3 += 24.0;
                        }
                        if (num3 >= 12.0)
{
                            text4 = Language.GetTextValue("GameUI.TimePastMorning");
                        }
                        int num5 = (int)num3;
                        double num6 = (double)((int)((num3 - (double)num5) * 60.0));
                        string text5 = string.Concat(num6);
                        if (num6 < 10.0)
{
                            text5 = "0" + text5;
                        }
                        if (num5 > 12)
{
                            num5 -= 12;
                        }
                        if (num5 == 0)
{
                            num5 = 12;
                        }
                        Console.WriteLine(Language.GetTextValue("CLI.Time", string.Concat(new object[] { num5, ":", text5, " ", text4 })));
                    }
                    else if (Language.GetText("CLI.MaxPlayers_Command").EqualsCommand(text))
                    {
                        Console.WriteLine(Language.GetTextValue("CLI.PlayerLimit", Main.maxNetPlayers));
                    }
                    else if (Language.GetText("CLI.Port_Command").EqualsCommand(text))
                    {
                        Console.WriteLine(Language.GetTextValue("CLI.Port", Netplay.ListenPort));
                    }
                    else if (Language.GetText("CLI.Version_Command").EqualsCommand(text))
                    {
                        Console.WriteLine(Language.GetTextValue("CLI.Server", Main.versionNumber));
                    }
                    else
                    {
                        if (Language.GetText("CLI.Clear_Command").EqualsCommand(text))
{
                            try
{
                                Console.Clear();
                                continue;
                            }
                            catch
{
                                continue;
                            }
                        }
                        if (Language.GetText("CLI.Playing_Command").EqualsCommand(text))
{
                            int num7 = 0;
                            for (int k = 0; k < 255; k++)
{
                                if (Main.player[k].active)
{
                                    num7++;
                                    Console.WriteLine(string.Concat(new object[]
{
                                        Main.player[k].name,
                                        " (",
                                        Netplay.Clients[k].Socket.GetRemoteAddress(),
                                        ")"
                                    }));
                                }
                            }
                            if (num7 == 0)
{
                                Console.WriteLine(Language.GetTextValue("CLI.NoPlayers"));
                            }
                            else if (num7 == 1)
{
                                Console.WriteLine(Language.GetTextValue("CLI.OnePlayerConnected"));
                            }
                            else
{
                                Console.WriteLine(Language.GetTextValue("CLI.PlayersConnected", num7));
                            }
                        }
                        else if (!(text == ""))
{
                            string text6;
                            if (Language.GetText("CLI.MOTD_Command").EqualsCommand(text))
{
                                if (Main.motd == "")
{
                                    Console.WriteLine(Language.GetTextValue("CLI.NoMOTD", Main.worldName));
                                }
                                else
{
                                    Console.WriteLine(Language.GetTextValue("CLI.MOTD", Main.motd));
                                }
                            }
                            else if (Language.GetText("CLI.MOTD_Command").ParseCommandPrefix(text, out text6))
{
                                Main.motd = text6;
                            }
                            else if (Language.GetText("CLI.Password_Command").EqualsCommand(text))
{
                                if (Netplay.ServerPassword == "")
{
                                    Console.WriteLine(Language.GetTextValue("CLI.NoPassword"));
                                }
                                else
{
                                    Console.WriteLine(Language.GetTextValue("CLI.Password", Netplay.ServerPassword));
                                }
                            }
                            else if (Language.GetText("CLI.SetPassword_Command").ParseCommandPrefix(text, out text6))
{
                                if (string.IsNullOrWhiteSpace(text6))
{
                                    Netplay.ServerPassword = "";
                                    Console.WriteLine(Language.GetTextValue("CLI.PasswordDisabled"));
                                }
                                else
{
                                    Netplay.ServerPassword = text6;
                                    Console.WriteLine(Language.GetTextValue("CLI.PasswordSet", Netplay.ServerPassword));
                                }
                            }
                            else if (Language.GetText("CLI.Say_Command").ParseCommandPrefix(text, out text6))
{
                                if (string.IsNullOrWhiteSpace(text6))
{
                                    Console.WriteLine(Language.GetTextValue("CLI.Say_Usage"));
                                }
                                else
{
                                    string text7 = text6;
                                    Console.WriteLine(Language.GetTextValue("CLI.ServerMessage", text7));
                                    ChatHelper.BroadcastChatMessage(NetworkText.FromKey("CLI.ServerMessage", new object[] { text7 }), ChatColors.ServerMessage, -1);
                                }
                            }
                            else if (Language.GetText("CLI.Kick_Command").ParseCommandPrefix(text, out text6))
{
                                if (string.IsNullOrWhiteSpace(text6))
{
                                    Console.WriteLine(Language.GetTextValue("CLI.Kick_Usage"));
                                }
                                else
{
                                    string text8 = text6;
                                    text8 = text8.ToLower();
                                    for (int l = 0; l < 255; l++)
{
                                        if (Main.player[l].active && Main.player[l].name.ToLower() == text8)
{
                                            NetMessage.SendData(2, l, -1, NetworkText.FromKey("CLI.KickMessage", new object[0]), 0, 0f, 0f, 0f, 0, 0, 0);
                                        }
                                    }
                                }
                            }
                            else if (Language.GetText("CLI.Seed_Command").EqualsCommand(text))
{
                                if (Main.ActiveWorldFileData == null || !Main.ActiveWorldFileData.HasValidSeed)
{
                                    Console.WriteLine(Language.GetTextValue("CLI.NoValidSeed"));
                                }
                                else
{
                                    Console.WriteLine(Language.GetTextValue("CLI.DisplaySeed", Main.ActiveWorldFileData.GetFullSeedText(false)));
                                }
                            }
                            else if (Language.GetText("CLI.Ban_Command").ParseCommandPrefix(text, out text6))
{
                                if (string.IsNullOrWhiteSpace(text6))
{
                                    Console.WriteLine(Language.GetTextValue("CLI.Ban_Usage"));
                                }
                                else
{
                                    string text9 = text6;
                                    text9 = text9.ToLower();
                                    for (int m = 0; m < 255; m++)
{
                                        if (Main.player[m].active && Main.player[m].name.ToLower() == text9)
{
                                            Netplay.AddBan(m);
                                            NetMessage.SendData(2, m, -1, NetworkText.FromKey("CLI.BanMessage", new object[0]), 0, 0f, 0f, 0f, 0, 0, 0);
                                        }
                                    }
                                }
                            }
                            else if (!ChatManager.DebugCommands.Process((byte)Main.myPlayer, "/" + text))
{
                                Console.WriteLine(Language.GetTextValue("CLI.InvalidCommand"));
                            }
                        }
                    }
                }
                catch
                {
                    Console.WriteLine(Language.GetTextValue("CLI.InvalidCommand"));
                }
            }
        }
References Terraria.Player.active, Terraria.Main.ActiveWorldFileData, Terraria.Netplay.AddBan(), Terraria.Chat.ChatHelper.BroadcastChatMessage(), System.Console.Clear(), Terraria.Netplay.Clients, Newtonsoft.Json.Linq.Concat, Terraria.Main.dayTime, Terraria.UI.Chat.ChatManager.DebugCommands, Terraria.Main.dedServFPS, Terraria.Netplay.Disconnect, Terraria.Localization.LocalizedText.EqualsCommand(), Terraria.Main.EstimatedMonospacedWidth(), Terraria.Localization.Language.Exists(), Terraria.Main.fpsTimer, Terraria.Localization.NetworkText.FromKey(), Terraria.IO.WorldFileData.GetFullSeedText(), Terraria.Localization.Language.GetText(), Terraria.Localization.Language.GetTextValue(), Terraria.IO.WorldFileData.HasValidSeed, int, System.list, Terraria.Netplay.ListenPort, System.Math.Max(), Terraria.Main.maxNetPlayers, Terraria.Main.motd, Terraria.Main.myPlayer, Terraria.Player.name, Terraria.Liquid.panicMode, Terraria.Localization.LocalizedText.ParseCommandPrefix(), Terraria.Main.player, Terraria.Main.ReadLineInput(), Terraria.IO.WorldFile.SaveWorld(), Terraria.NetMessage.SendData(), Terraria.Chat.ChatColors.ServerMessage, Terraria.Netplay.ServerPassword, Terraria.Social.SocialAPI.Shutdown(), Terraria.RemoteClient.Socket, Terraria.Liquid.StartPanic(), System.text, Terraria.Main.time, Terraria.Main.versionNumber, Terraria.Main.worldName, System.Console.Write(), and System.Console.WriteLine().
Referenced by Terraria.Main.startDedInput().