Terraria Decompiled: Terraria.Main.DrawNPCPortrait
DrawNPCPortrait()
static void Terraria.Main.DrawNPCPortrait (Microsoft::Xna::Framework::Color chatBack, Vector2 npcChatTopLeft) inline static
Definition at line 40084 of file Main.cs.
        {
            Main.DialoguePortraitDrawOption dialoguePortraitPreference = Main.DialoguePortraitPreference;
            if (dialoguePortraitPreference == Main.DialoguePortraitDrawOption.Disabled)
            {
                return;
            }
            NPCID.Sets.NPCPortraitProvider npcportraitProvider = Main.npcChatPortrait;
            if (npcportraitProvider == null)
            {
                return;
            }
            Texture2D texture2D;
            Microsoft.Xna.Framework.Rectangle rectangle;
            npcportraitProvider.GetDrawData(out texture2D, out rectangle);
            if (texture2D == null)
            {
                return;
            }
            int num = Main.npcChatPortraitFrameCounter++;
            int num2 = 56;
            Vector2 vector = npcChatTopLeft + new Vector2((float)(-(float)num2 - 6), (float)(num2 + 6));
            Asset<Texture2D> npcPortraitBackground = TextureAssets.NpcPortraitBackground;
            Microsoft.Xna.Framework.Rectangle rectangle2 = npcPortraitBackground.Frame(1, 1, 0, 0, 0, 0);
            Vector2 vector2 = new Vector2(1f, 1f);
            int num3 = num % 120;
            int num4 = num / 120;
            SpriteEffects spriteEffects = SpriteEffects.None;
            float num5 = 0f;
            bool flag = num4 == 0;
            bool flag2 = false;
            bool flag3 = false;
            if (flag2)
            {
                double num6 = 15.0;
                double num7 = Utils.Clamp<double>((double)num3, 0.0, num6);
                Vector2 vector3 = vector + new Vector2(0f, (float)num2);
                num5 = (float)Math.Sin(6.2831854820251465 * (num7 / num6)) * 6.2831855f * 0.0045f;
                vector = vector.RotatedBy((double)num5, vector3);
            }
            if (flag)
            {
                double num8 = 80.0;
                float num9 = 0.25f;
                float num10 = (float)Utils.EaseOutBounce(Utils.Clamp<double>((double)num3, 0.0, num8) / num8);
                vector += new Vector2(0f, (float)(-(float)num2) * num9 * (1f - num10));
            }
            if (flag3)
            {
                double num11 = 120.0;
                int num12 = 30;
                double num13;
                double num14;
                Utils.GetPortraitMovement(Utils.Clamp<double>((double)num3, 0.0, num11) / num11, out num13, out num14);
                vector2.X = (float)num14;
                vector.X += (float)num12 * (float)num13;
                if (vector2.X < 0f)
                {
                    vector2.X *= -1f;
                    spriteEffects ^= SpriteEffects.FlipHorizontally;
                }
            }
            Main.spriteBatch.Draw(npcPortraitBackground.Value, vector, new Microsoft.Xna.Framework.Rectangle?(rectangle2), chatBack, num5, rectangle2.Size() / 2f, vector2, spriteEffects, 0f);
            NPC npc = Main.npc[Main.LocalPlayer.talkNPC];
            if (dialoguePortraitPreference == Main.DialoguePortraitDrawOption.Detailed)
            {
                Main.spriteBatch.Draw(texture2D, vector, new Microsoft.Xna.Framework.Rectangle?(rectangle), Microsoft.Xna.Framework.Color.White, num5, rectangle.Size() / 2f, vector2, spriteEffects, 0f);
            }
            if (dialoguePortraitPreference == Main.DialoguePortraitDrawOption.CloseUp)
            {
                NPC portraitDummy = Main._portraitDummy;
                portraitDummy.SetDefaults(npc.type, default(NPCSpawnParams));
                portraitDummy.whoAmI = npc.whoAmI;
                portraitDummy.GivenName = npc.GivenName;
                portraitDummy.townNpcVariationIndex = npc.townNpcVariationIndex;
                portraitDummy.FindFrame();
                int num15 = 16;
                portraitDummy.scale = 3f;
                int num16 = -portraitDummy.width / 2;
                if (NPCID.Sets.IsTownPet[portraitDummy.type])
                {
                    num15 = -20;
                    portraitDummy.scale = 3f;
                    int num17 = 96;
                    num17 -= npc.frame.Width;
                    num17 /= 2;
                    num17 /= 6;
                    num17 *= 6;
                    num16 = -36 + num17;
                }
                Dictionary<int, Vector2> npcportraitsCloseUpOffsets = NPCID.Sets.NPCPortraitsCloseUpOffsets;
                portraitDummy.position = vector + new Vector2((float)num16, (float)(48 + num15));
                Vector2 zero = Vector2.Zero;
                if (npcportraitsCloseUpOffsets.TryGetValue(npc.type, out zero))
                {
                    portraitDummy.position += zero;
                }
                portraitDummy.IsABestiaryIconDummy = true;
                portraitDummy.IsAPortraitDummy = true;
                Main.spriteBatch.End();
                Microsoft.Xna.Framework.Rectangle scissorRectangle = Main.spriteBatch.GraphicsDevice.ScissorRectangle;
                Main.spriteBatch.Begin(SpriteSortMode.Deferred, null, SamplerState.PointClamp, null, Main.ScissorState, null, Main.UIScaleMatrix);
                Microsoft.Xna.Framework.Rectangle rectangle3 = Utils.CenteredRectangle(vector * Main.UIScaleMatrix.M11, new Vector2(96f, 96f) * Main.UIScaleMatrix.M11);
                rectangle3.Y -= 50;
                rectangle3.Height += 50;
                Main.spriteBatch.GraphicsDevice.ScissorRectangle = rectangle3;
                Main.instance.DrawNPCDirect(Main.spriteBatch, portraitDummy, false, Vector2.Zero);
                Main.spriteBatch.End();
                Main.spriteBatch.GraphicsDevice.ScissorRectangle = scissorRectangle;
                Main.spriteBatch.Begin(SpriteSortMode.Deferred, null, null, null, null, null, Main.UIScaleMatrix);
            }
            if (dialoguePortraitPreference == Main.DialoguePortraitDrawOption.FullBodyRetro)
            {
                NPC portraitDummy2 = Main._portraitDummy;
                portraitDummy2.SetDefaults(npc.type, default(NPCSpawnParams));
                portraitDummy2.whoAmI = npc.whoAmI;
                portraitDummy2.GivenName = npc.GivenName;
                portraitDummy2.townNpcVariationIndex = npc.townNpcVariationIndex;
                portraitDummy2.FindFrame();
                int num18 = -portraitDummy2.height;
                portraitDummy2.scale = 2f;
                int num19 = -portraitDummy2.width / 2;
                Dictionary<int, Vector2> npcportraitsFullBodyRetroOffsets = NPCID.Sets.NPCPortraitsFullBodyRetroOffsets;
                portraitDummy2.position = vector + new Vector2((float)num19, (float)(48 + num18));
                Vector2 zero2 = Vector2.Zero;
                if (npcportraitsFullBodyRetroOffsets.TryGetValue(npc.type, out zero2))
                {
                    portraitDummy2.position += zero2;
                }
                portraitDummy2.IsABestiaryIconDummy = true;
                portraitDummy2.IsAPortraitDummy = true;
                Main.spriteBatch.End();
                Microsoft.Xna.Framework.Rectangle scissorRectangle2 = Main.spriteBatch.GraphicsDevice.ScissorRectangle;
                Main.spriteBatch.Begin(SpriteSortMode.Deferred, null, SamplerState.PointClamp, null, null, null, Main.UIScaleMatrix);
                Main.instance.DrawNPCDirect(Main.spriteBatch, portraitDummy2, false, Vector2.Zero);
                Main.spriteBatch.End();
                Main.spriteBatch.Begin(SpriteSortMode.Deferred, null, null, null, null, null, Main.UIScaleMatrix);
            }
            string givenName = npc.GivenName;
            DynamicSpriteFont value = FontAssets.ItemStack.Value;
            Vector2 vector4 = value.MeasureString(givenName);
            float num20 = 1f;
            ChatManager.DrawColorCodedStringWithShadow(Main.spriteBatch, value, givenName, vector + new Vector2(0f, (float)(num2 + 1)), Microsoft.Xna.Framework.Color.White, 0f, vector4 / 2f, Vector2.One * num20, -1f, 2f);
        }
References Terraria.Main._portraitDummy, Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(), Terraria.Utils.CenteredRectangle(), Terraria.Utils.Clamp(), Terraria.Main.DialoguePortraitPreference, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.Main.DrawNPCDirect(), Terraria.Utils.EaseOutBounce(), Microsoft.Xna.Framework.Graphics.SpriteBatch.End(), Terraria.NPC.FindFrame(), Terraria.NPC.frame, Terraria.ID.NPCID.Sets.NPCPortraitProvider.GetDrawData(), Terraria.Utils.GetPortraitMovement(), Terraria.NPC.GivenName, Microsoft.Xna.Framework.Graphics.GraphicsResource.GraphicsDevice, Terraria.Entity.height, Terraria.Main.instance, Terraria.ID.NPCID.Sets.IsTownPet, Terraria.GameContent.FontAssets.ItemStack, Terraria.Main.LocalPlayer, Microsoft.Xna.Framework.Matrix.M11, Terraria.Main.npc, Terraria.Main.npcChatPortrait, Terraria.Main.npcChatPortraitFrameCounter, Terraria.GameContent.TextureAssets.NpcPortraitBackground, Terraria.ID.NPCID.Sets.NPCPortraitsCloseUpOffsets, Terraria.ID.NPCID.Sets.NPCPortraitsFullBodyRetroOffsets, Microsoft.Xna.Framework.Vector2.One, Microsoft.Xna.Framework.Graphics.SamplerState.PointClamp, Microsoft.Xna.Framework.Graphics.GraphicsDevice.ScissorRectangle, Terraria.Main.ScissorState, Terraria.NPC.SetDefaults(), System.Math.Sin(), Terraria.Main.spriteBatch, Terraria.Player.talkNPC, Terraria.NPC.townNpcVariationIndex, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), Terraria.NPC.type, Terraria.Main.UIScaleMatrix, System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Color.White, Terraria.Entity.whoAmI, Microsoft.Xna.Framework.Rectangle.Width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.UI.NPCChatPanel.Draw().