Terraria Decompiled: Terraria.Main.DedServ_SeedFlagsMenu
DedServ_SeedFlagsMenu()
static void Terraria.Main.DedServ_SeedFlagsMenu () inline static private
Definition at line 3961 of file Main.cs.
        {
            List<AWorldGenerationOption> list = WorldGenerationOptions.Options.ToList<AWorldGenerationOption>();
            foreach (AWorldGenerationOption aworldGenerationOption in list)
            {
                aworldGenerationOption.Load();
            }
            string text = "[x]";
            string text2 = "[ ]";
            string text3 = "\t";
            for (;;)
            {
                Console.Clear();
                Console.WriteLine(Language.GetTextValue("CLI.Server", Main.versionNumber2));
                Console.WriteLine();
                int num = 0;
                foreach (AWorldGenerationOption aworldGenerationOption2 in list)
                {
                    num++;
                    Console.Write(string.Format("{0,-2}", num));
                    Console.Write(text3);
                    Console.Write(aworldGenerationOption2.Enabled ? text : text2);
                    Console.Write(text3);
                    Console.Write(aworldGenerationOption2.Title);
                    Console.WriteLine();
                }
                Console.WriteLine();
                Console.Write(Language.GetTextValue("CLI.EnterSeedToggleNumber"));
                string text4 = Main.ReadLineInput();
                if (text4 == string.Empty)
                {
                    break;
                }
                int num2;
                if (!int.TryParse(text4, out num2))
                {
                    Console.Clear();
                }
                else
                {
                    int num3 = num2 - 1;
                    if (num3 < 0 || num3 >= list.Count)
                    {
                        Console.Clear();
                    }
                    else
                    {
                        list[num3].Enabled = !list[num3].Enabled;
                    }
                }
            }
        }
References System.Console.Clear(), Terraria.WorldBuilding.AWorldGenerationOption.Enabled, System.Format, Terraria.Localization.Language.GetTextValue(), System.list, Terraria.WorldBuilding.AWorldGenerationOption.Load(), Terraria.WorldBuilding.WorldGenerationOptions.Options, Terraria.Main.ReadLineInput(), System.text, Terraria.WorldBuilding.AWorldGenerationOption.Title, Terraria.Main.versionNumber2, System.Console.Write(), and System.Console.WriteLine().
Referenced by Terraria.Main.DedServ().