Terraria Decompiled: Terraria.Main.DrawBG
DrawBG()
void Terraria.Main.DrawBG (SpriteBatchBeginner parentSpriteBatchBeginner) inline private
Definition at line 65050 of file Main.cs.
        {
            this.scAdj = Main.ComputeScAdj(Main.screenPosition.Y, (float)Main.screenHeight);
            if (Main.gameMenu)
            {
                this.scAdj = 0f;
            }
            if (Main.resetClouds)
            {
                Cloud.resetClouds();
                Main.resetClouds = false;
            }
            Main.bgScale = 1f;
            Main.bgWidthScaled = (int)((float)Main.backgroundWidth[Main.treeMntBGSet1[0]] * Main.bgScale);
            Main.ColorOfSurfaceBackgroundsModified = Main.ColorOfTheSkies;
            Main.ColorOfSurfaceBackgroundsBase = Main.ColorOfTheSkies;
            int preferredBGStyleForPlayer = Main.GetPreferredBGStyleForPlayer();
            Main.backgroundLayerTransitionSpeed = 0.05f;
            if (Main.bgDelay < 0)
            {
                Main.bgDelay++;
            }
            else if (preferredBGStyleForPlayer != Main.bgStyle)
            {
                this.DrawBG_HandleBackgroundTransition(preferredBGStyleForPlayer);
            }
            else if (Main.bgDelay > 0)
            {
                Main.bgDelay--;
            }
            if (Main.gameMenu)
            {
                Main.backgroundLayerTransitionSpeed = 0.02f;
                if (!Main.dayTime)
                {
                    Main.bgStyle = 1;
                }
                else if (Main.notTheBeesWorld && !Main.remixWorld)
                {
                    Main.bgStyle = 3;
                }
                else
                {
                    Main.bgStyle = 0;
                }
                preferredBGStyleForPlayer = Main.bgStyle;
                if (WorldGen.drunkWorldGen)
                {
                    if (Main.onlyShimmerOceanWorldsGeneration)
                    {
                        Main.bgStyle = 6;
                    }
                    else if (Main.vampireSeed)
                    {
                        Main.bgStyle = 8;
                    }
                    else if (WorldGen.notTheBees)
                    {
                        Main.bgStyle = 3;
                    }
                    else
                    {
                        Main.bgStyle = 9;
                    }
                }
            }
            if (Main.instantBGTransitionCounter > 0)
            {
                Main.instantBGTransitionCounter--;
                Main.bgStyle = preferredBGStyleForPlayer;
                Main.backgroundLayerTransitionSpeed = 1f;
            }
            this.UpdateBGVisibility_BackLayer(null, null);
            this.UpdateBGVisibility_FrontLayer(null, null);
            try
            {
                this.DrawSurfaceBG(parentSpriteBatchBeginner, null);
                if (Main.BackgroundEnabled)
                {
                    this.DrawUnderworldBackground(Main.GameZoomTarget);
                }
            }
            catch (Exception ex)
            {
                if (!Main.ignoreErrors)
                {
                    throw ex;
                }
                TimeLogger.DrawException(ex);
            }
        }
References Terraria.Main.BackgroundEnabled, Terraria.Main.backgroundWidth, Terraria.Main.bgDelay, Terraria.Main.bgScale, Terraria.Main.bgStyle, Terraria.Main.ColorOfTheSkies, Terraria.Main.ComputeScAdj(), Terraria.Main.dayTime, Terraria.TimeLogger.DrawException(), Terraria.WorldGen.drunkWorldGen, Terraria.Main.gameMenu, Terraria.Main.GameZoomTarget, Terraria.Main.GetPreferredBGStyleForPlayer(), Terraria.Main.ignoreErrors, Terraria.Main.instantBGTransitionCounter, int, Terraria.WorldGen.notTheBees, Terraria.Main.notTheBeesWorld, Terraria.Main.onlyShimmerOceanWorldsGeneration, Terraria.Main.remixWorld, Terraria.Cloud.resetClouds(), Terraria.Main.resetClouds, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.treeMntBGSet1, Terraria.Main.vampireSeed, and Microsoft.Xna.Framework.Vector2.Y.