Terraria Decompiled: Terraria.Main.GetBestiaryProgressReport
GetBestiaryProgressReport()
static BestiaryUnlockProgressReport Terraria.Main.GetBestiaryProgressReport () inline static
Definition at line 66871 of file Main.cs.
        {
            float num = 0f;
            int num2 = 0;
            List<BestiaryEntry> entries = Main.BestiaryDB.Entries;
            for (int i = 0; i < entries.Count; i++)
            {
                int num3 = ((entries[i].UIInfoProvider.GetEntryUICollectionInfo().UnlockState > BestiaryEntryUnlockState.NotKnownAtAll_0) ? 1 : 0);
                num2++;
                num += (float)num3;
            }
            return new BestiaryUnlockProgressReport
            {
                EntriesTotal = num2,
                CompletionAmountTotal = num
            };
        }
References Terraria.Main.BestiaryDB, System.Collections.Generic.List< T >.Count, and Terraria.GameContent.Bestiary.BestiaryDatabase.Entries.
Referenced by Terraria.Chest.SetupShop(), Terraria.GameContent.Achievements.AchievementsHelper.TryGrantingBestiary100PercentAchievement(), and Terraria.Main.UpdateTime_SpawnTownNPCs().