Terraria Decompiled: Terraria.Main.DrawWallOfCopperShortswords
DrawWallOfCopperShortswords()
static void Terraria.Main.DrawWallOfCopperShortswords () inline static private
Definition at line 45043 of file Main.cs.
        {
            UnifiedRandom unifiedRandom = new UnifiedRandom(5000);
            Texture2D value = TextureAssets.Cloud[28].Value;
            Vector2 vector = Main.ScreenSize.ToVector2();
            Main.spriteBatch.Begin();
            for (int i = 0; i < 20000; i++)
            {
                Vector2 vector2 = unifiedRandom.NextVector2Square(-0.1f, 1.1f);
                vector2.X -= 0.1f;
                vector2.X += Main.GlobalTimeWrappedHourly % 10f / 10f * 1.2f;
                vector2.Y -= Main.GlobalTimeWrappedHourly % 10f / 10f;
                if (vector2.Y < -0.2f)
                {
                    vector2.Y += 1.4f;
                }
                if (vector2.X > 1.1f)
                {
                    vector2.X -= 1.2f;
                }
                Vector2 vector3 = vector2 * vector;
                Main.spriteBatch.Draw(value, vector3, Microsoft.Xna.Framework.Color.White);
            }
            Main.spriteBatch.End();
        }
References Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(), Terraria.GameContent.TextureAssets.Cloud, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.End(), Terraria.Main.ScreenSize, Terraria.Main.spriteBatch, System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.