Terraria Decompiled: Terraria.Main.TryApplyingPlayerStringColor
TryApplyingPlayerStringColor()
static Microsoft.Xna.Framework.Color Terraria.Main.TryApplyingPlayerStringColor (int playerStringColor, Microsoft::Xna::Framework::Color stringColor) inline static private
Definition at line 34753 of file Main.cs.
        {
            if (playerStringColor > 0)
            {
                stringColor = WorldGen.paintColor(playerStringColor);
                if (stringColor.R < 75)
                {
                    stringColor.R = 75;
                }
                if (stringColor.G < 75)
                {
                    stringColor.G = 75;
                }
                if (stringColor.B < 75)
                {
                    stringColor.B = 75;
                }
                if (playerStringColor == 13)
                {
                    stringColor = new Microsoft.Xna.Framework.Color(20, 20, 20);
                }
                else if (playerStringColor == 14 || playerStringColor == 0)
                {
                    stringColor = new Microsoft.Xna.Framework.Color(200, 200, 200);
                }
                else if (playerStringColor == 28)
                {
                    stringColor = new Microsoft.Xna.Framework.Color(163, 116, 91);
                }
                else if (playerStringColor == 27)
                {
                    stringColor = new Microsoft.Xna.Framework.Color(Main.DiscoR, Main.DiscoG, Main.DiscoB);
                }
                else if (playerStringColor == 30)
                {
                    stringColor = new Microsoft.Xna.Framework.Color(226, 228, 142);
                }
                stringColor.A = (byte)((float)stringColor.A * 0.4f);
                if (playerStringColor == 29)
                {
                    float num = (float)(((double)Main.mouseTextColor - 190.0) / 65.0);
                    num += (float)Main.rand.Next(-100, 101) * 0.005f;
                    num = Utils.Clamp<float>(num, 0f, 1f);
                    float num2 = 1f - num;
                    byte b = (byte)(184f * num + 255f * num2);
                    byte b2 = (byte)(116f * num + 184f * num2);
                    byte b3 = (byte)(255f * num + 116f * num2);
                    b = (byte)((int)b + Main.rand.Next(-40, 41));
                    b2 = (byte)((int)b2 + Main.rand.Next(-40, 41));
                    b3 = (byte)((int)b3 + Main.rand.Next(-40, 41));
                    stringColor = new Microsoft.Xna.Framework.Color((int)b, (int)b2, (int)b3, 0);
                }
            }
            return stringColor;
        }
References Terraria.Utils.Clamp(), Terraria.Main.DiscoB, Terraria.Main.DiscoG, Terraria.Main.DiscoR, int, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.paintColor(), and Terraria.Main.rand.
Referenced by Terraria.Main.DrawProj_FishingLine(), and Terraria.Main.DrawProjDirect().