Terraria Decompiled: Terraria.Main.OpenRecent
OpenRecent()
void Terraria.Main.OpenRecent () inline protected
Definition at line 2117 of file Main.cs.
        {
            try
            {
                if (File.Exists(Main.SavePath + Path.DirectorySeparatorChar.ToString() + "servers.dat"))
                {
                    using (FileStream fileStream = new FileStream(Main.SavePath + Path.DirectorySeparatorChar.ToString() + "servers.dat", FileMode.Open))
                    {
                        using (BinaryReader binaryReader = new BinaryReader(fileStream))
{
                            binaryReader.ReadInt32();
                            for (int i = 0; i < 10; i++)
{
                                Main.recentWorld[i] = binaryReader.ReadString();
                                Main.recentIP[i] = binaryReader.ReadString();
                                Main.recentPort[i] = binaryReader.ReadInt32();
                            }
                        }
                    }
                }
            }
            catch
            {
            }
        }
References System.IO.Path.DirectorySeparatorChar, System.IO.File.Exists(), System.IO.BinaryReader.ReadInt32(), System.IO.BinaryReader.ReadString(), Terraria.Main.recentIP, Terraria.Main.recentPort, Terraria.Main.recentWorld, and Terraria.Main.SavePath.