Terraria Decompiled: Terraria.Main.NewToken
NewToken()
static string Terraria.Main.NewToken () inline static private
Definition at line 52491 of file Main.cs.
        {
            string text;
            using (RandomNumberGenerator randomNumberGenerator = RandomNumberGenerator.Create())
            {
                byte[] array = new byte[16];
                randomNumberGenerator.GetBytes(array);
                text = Convert.ToBase64String(array);
            }
            return text;
        }
References System.array, System.Security.Cryptography.RandomNumberGenerator.Create(), System.Security.Cryptography.RandomNumberGenerator.GetBytes(), System.text, and System.Convert.ToBase64String().
Referenced by Terraria.Main.HostAndPlay().