Terraria Decompiled: Terraria.Main.HoverOverCraftingItemButton
HoverOverCraftingItemButton()
static void Terraria.Main.HoverOverCraftingItemButton (int recipeIndex) inline static
Definition at line 42206 of file Main.cs.
        {
            Recipe recipe = Main.recipe[Main.availableRecipe[recipeIndex]];
            Main.player[Main.myPlayer].mouseInterface = true;
            bool flag = (Main.mouseLeftRelease && Main.mouseLeft) || (Main.mouseRightRelease && Main.mouseRight);
            bool flag2 = Main.mouseLeft || Main.mouseRight;
            Main.craftingHide = true;
            Main.HoverItem = recipe.createItem.Clone();
            Main.HoverItem.tooltipSlot = 0;
            ItemSlot.MouseHover(22);
            if (ItemSlot.HoverOverrideClick(recipe.createItem, 22))
            {
                Main._preventCraftingBecauseClickWasUsedToChangeFocusedRecipe = true;
            }
            else if (Main.focusRecipe == recipeIndex && Main.guideItem.IsAir)
            {
                bool flag3 = !Main.LocalPlayer.UsingOrReusingItem && !Main.player[Main.myPlayer].IsLockedFromCrafting() && !Main._preventCraftingBecauseClickWasUsedToChangeFocusedRecipe;
                bool flag4 = Main._currentRecipeBeingCrafted != -1 && Main._currentRecipeBeingCrafted != Main.availableRecipe[recipeIndex];
                bool flag5 = Main._currentRecipeBeingCrafted != -1 && Main.recipe[Main._currentRecipeBeingCrafted].createItem.maxStack == 1;
                bool flag6 = flag4 || flag5;
                int num = Main.superFastStack + 1;
                if (ItemSlot.ShiftInUse)
                {
                    num *= 10;
                }
                if (flag2 && !flag6 && flag3 && Main.stackSplit <= 1)
                {
                    bool usingGamepad = PlayerInput.UsingGamepad;
                    bool flag8;
                    bool flag7 = Main.TryAllowingToCraftRecipe(recipe, usingGamepad, out flag8);
                    if (flag8)
                    {
                        Main._preventCraftingBecauseClickWasUsedToChangeFocusedRecipe = true;
                    }
                    if (flag7 && !flag8)
                    {
                        if (Main._currentRecipeBeingCrafted == -1)
{
                            Main._currentRecipeBeingCrafted = Main.availableRecipe[recipeIndex];
                        }
                        ItemSlot.RefreshStackSplitCooldown();
                        CraftingRequests.CraftItem(recipe, num, false);
                    }
                }
            }
            else if (flag)
            {
                Main.focusRecipe = recipeIndex;
                Main.stackSplit = 15;
                Main._preventCraftingBecauseClickWasUsedToChangeFocusedRecipe = true;
                SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
            }
            if (!flag2)
            {
                Main._preventCraftingBecauseClickWasUsedToChangeFocusedRecipe = false;
                Main._currentRecipeBeingCrafted = -1;
            }
        }
References Terraria.Main._currentRecipeBeingCrafted, Terraria.Main._preventCraftingBecauseClickWasUsedToChangeFocusedRecipe, Terraria.Main.availableRecipe, Terraria.Item.Clone(), Terraria.GameContent.CraftingRequests.CraftItem(), Terraria.Recipe.createItem, Terraria.Main.focusRecipe, Terraria.Main.guideItem, Terraria.UI.ItemSlot.HoverOverrideClick(), Terraria.Item.IsAir, Terraria.Player.IsLockedFromCrafting(), Terraria.Item.maxStack, Terraria.UI.ItemSlot.MouseHover(), Terraria.Player.mouseInterface, Terraria.Main.mouseLeft, Terraria.Main.mouseRight, Terraria.Main.mouseRightRelease, Terraria.Main.myPlayer, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.recipe, Terraria.UI.ItemSlot.RefreshStackSplitCooldown(), Terraria.UI.ItemSlot.ShiftInUse, Terraria.Main.stackSplit, Terraria.Main.TryAllowingToCraftRecipe(), and Terraria.GameInput.PlayerInput.UsingGamepad.
Referenced by Terraria.UI.CraftingUI.DrawRecipesList(), and Terraria.GameContent.UI.NewCraftingUI.HandleCraftSlot().