Terraria Decompiled: Terraria.Main.DrawGuideCraftText
DrawGuideCraftText()
static void Terraria.Main.DrawGuideCraftText (int inventoryX, int inventoryY) inline static
Definition at line 42132 of file Main.cs.
        {
            Microsoft.Xna.Framework.Color color = new Microsoft.Xna.Framework.Color((int)Main.mouseTextColor, (int)Main.mouseTextColor, (int)Main.mouseTextColor, (int)Main.mouseTextColor);
            Vector2 vector = new Vector2((float)(inventoryX + 50), (float)(inventoryY + 12));
            DynamicSpriteFont value = FontAssets.MouseText.Value;
            if (Main.guideItem.IsAir)
            {
                string value2 = Lang.inter[24].Value;
                DynamicSpriteFontExtensionMethods.DrawString(Main.spriteBatch, value, value2, vector, color, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f, null, null);
                return;
            }
            string text = Lang.inter[21].Value + " " + Main.guideItem.Name;
            string recipeRequirementsText = Main.GetRecipeRequirementsText(Main.recipe[Main.availableRecipe[Main.focusRecipe]], true);
            vector.Y -= 14f;
            DynamicSpriteFontExtensionMethods.DrawString(Main.spriteBatch, value, text, vector, color, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f, null, null);
            Vector2 vector2 = vector + new Vector2(0f, 26f);
            DynamicSpriteFontExtensionMethods.DrawString(Main.spriteBatch, value, recipeRequirementsText, vector2, color, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f, null, null);
        }
References Terraria.Main.availableRecipe, ReLogic.Graphics.DynamicSpriteFontExtensionMethods.DrawString(), Terraria.Main.focusRecipe, Terraria.Main.GetRecipeRequirementsText(), Terraria.Main.guideItem, Terraria.Lang.inter, Terraria.Item.IsAir, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.mouseTextColor, Terraria.Item.Name, Terraria.Main.recipe, Terraria.Main.spriteBatch, System.text, System.value, ReLogic.Content.Asset< T >.Value, Terraria.Localization.LocalizedText.Value, Microsoft.Xna.Framework.Graphics.Vector2, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.Main.DrawInventory().