Terraria Decompiled: Terraria.Main.GetPlayerHeadBordersColor
GetPlayerHeadBordersColor()
static Microsoft.Xna.Framework.Color Terraria.Main.GetPlayerHeadBordersColor (Player plr) inline static
Definition at line 57419 of file Main.cs.
        {
            if (plr.ghost || plr.dead)
            {
                return Microsoft.Xna.Framework.Color.Transparent;
            }
            if (Main.netMode == 0)
            {
                return Main.teamColor[0];
            }
            if (plr.whoAmI == Main.myPlayer)
            {
                return Main.teamColor[plr.team];
            }
            if (plr.hostile && (plr.team != Main.LocalPlayer.team || plr.team == 0))
            {
                return Microsoft.Xna.Framework.Color.Transparent;
            }
            return Main.teamColor[plr.team];
        }
References Terraria.Player.dead, Terraria.Player.ghost, Terraria.Player.hostile, Terraria.Main.LocalPlayer, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Player.team, Terraria.Main.teamColor, Microsoft.Xna.Framework.Color.Transparent, and Terraria.Entity.whoAmI.
Referenced by Terraria.GameContent.UI.LegacyMultiplayerClosePlayersOverlay.Draw(), Terraria.Main.DrawMap(), and Terraria.GameContent.UI.NewMultiplayerClosePlayersOverlay.PlayerOffScreenCache.DrawPlayerHead().