Terraria Decompiled: Terraria.Main.UpdateSceneMetrics
UpdateSceneMetrics()
static void Terraria.Main.UpdateSceneMetrics () inline static
Definition at line 63528 of file Main.cs.
        {
            if (CaptureManager.Instance.IsCapturing)
            {
                return;
            }
            Player player = Main.LocalPlayer;
            Vector2 center;
            float num;
            float num2;
            Main._usingSeparateCameraSceneMetrics = Main.GetObjectTrackingCameraPan(out center, out num, out num2);
            if (Main._usingSeparateCameraSceneMetrics)
            {
                Main.LocalPlayer.UpdateSceneMetrics();
                if (Main.LocalPlayer.spectating >= 0)
                {
                    player = Main.player[Main.LocalPlayer.spectating];
                }
            }
            else
            {
                center = Main.LocalPlayer.Center;
            }
            Microsoft.Xna.Framework.Rectangle areaToLight = Main.GetAreaToLight();
            areaToLight.Inflate(28, 28);
            Main.SceneMetrics.Scan(new SceneMetricsScanSettings
            {
                VisualScanArea = new Microsoft.Xna.Framework.Rectangle?(areaToLight),
                BiomeScanCenterPositionInWorld = center,
                ScanNPCPositions = true,
                PerspectivePlayer = player
            });
        }
References Terraria.Main._usingSeparateCameraSceneMetrics, Terraria.Entity.Center, Terraria.Main.GetAreaToLight(), Terraria.Main.GetObjectTrackingCameraPan(), Microsoft.Xna.Framework.Rectangle.Inflate(), Terraria.Graphics.Capture.CaptureManager.Instance, Terraria.Graphics.Capture.CaptureManager.IsCapturing, Terraria.Main.LocalPlayer, Terraria.Main.player, Terraria.SceneMetrics.Scan(), Terraria.Main.SceneMetrics, Terraria.Player.spectating, and Terraria.Player.UpdateSceneMetrics().
Referenced by Terraria.Main.BlackFadeCameraTeleport(), Terraria.Graphics.Light.LegacyLighting.PreRenderPhase(), and Terraria.Graphics.Light.LightingEngine.ProcessArea().