Terraria Decompiled: Terraria.Main.hslToRgb
hslToRgb() [2/2]
static Microsoft.Xna.Framework.Color Terraria.Main.hslToRgb (Vector3 hslVector) inline static
Definition at line 48229 of file Main.cs.
        {
            return Main.hslToRgb(hslVector.X, hslVector.Y, hslVector.Z, byte.MaxValue);
        }
References Terraria.Main.hslToRgb(), Microsoft.Xna.Framework.Vector3.X, Microsoft.Xna.Framework.Vector3.Y, and Microsoft.Xna.Framework.Vector3.Z.
Referenced by Terraria.Projectile.AI(), Terraria.Projectile.AI_001(), Terraria.NPC.AI_001_Slimes(), Terraria.NPC.AI_007_TownEntities(), Terraria.NPC.AI_065_Butterflies(), Terraria.Projectile.AI_075(), Terraria.NPC.AI_120_HallowBoss(), Terraria.NPC.AI_120_HallowBoss_DoMagicEffect(), Terraria.Projectile.AI_165_Whip(), Terraria.Projectile.AI_171_GetColor(), Terraria.Projectile.AI_173_GetColor(), Terraria.Projectile.AI_180_FairyQueenSunDance(), Terraria.Projectile.AI_186_PrincessWeapon(), Terraria.Graphics.Light.TileLightScanner.ApplyTileLight(), Terraria.DataStructures.PlayerDrawSet.BoringSetup(), Terraria.DelegateMethods.ColorLerp_HSL_H(), Terraria.DelegateMethods.ColorLerp_HSL_L(), Terraria.DelegateMethods.ColorLerp_HSL_O(), Terraria.DelegateMethods.ColorLerp_HSL_S(), Terraria.GameContent.TownRoomManager.DisplayRooms(), Terraria.Projectile.DoRainbowCrystalStaffExplosion(), Terraria.GameContent.Animations.Segments.LocalizedTextSegment.Draw(), Terraria.UI.ItemSlot.Draw(), Terraria.GameContent.Skies.AuroraSky.DrawAuroraSky(), Terraria.GameContent.Drawing.TileDrawing.DrawBasicTile(), Terraria.Main.DrawClothesWindow(), Terraria.UI.NetDiagnosticsUI.DrawCounter(), Terraria.Main.DrawCursor(), Terraria.Graphics.Capture.CaptureInterface.ModeEdgeSelection.DrawCursors(), Terraria.UI.UIElement.DrawDebugHitbox(), Terraria.Main.DrawHairWindow(), Terraria.GameContent.UI.UIPopupTextManager.DrawItemTextPopups(), Terraria.PopupText.DrawItemTextPopups(), Terraria.Main.DrawMenu(), Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileVinesInWind(), Terraria.Main.DrawMurderAurora(), Terraria.Main.DrawNPCDirect(), Terraria.Main.DrawNPCDirect_Faeling(), Terraria.Main.DrawNPCDirect_HallowBoss(), Terraria.Main.DrawProjDirect(), Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile(), Terraria.GameContent.Drawing.TileDrawing.DrawSpecialTilesLegacy(), Terraria.Main.DrawWhip(), Terraria.Main.DrawWhip_Constellation(), Terraria.Main.DrawWhip_MoonLordWhip(), Terraria.Main.DrawWhip_RainbowWhip(), Terraria.GameContent.Drawing.NextNatureRenderer.DrawWithLitNatureShader(), Terraria.GameContent.Golf.GolfHelper.ContactListener.EmitGolfballExplosion(), Terraria.DataStructures.ColorSlidersSet.GetColor(), Terraria.Projectile.GetConstellationColor(), Terraria.Projectile.GetFairyQueenWeaponsColorFull(), Terraria.Projectile.GetFirstFractalColor(), Terraria.Projectile.GetFloatingDaggerMinionGlowColor(), Terraria.UI.ItemSlot.GetLoadoutColor(), Terraria.GameContent.PortalHelper.GetPortalColor(), Terraria.GameContent.Liquid.LiquidRenderer.GetShimmerGlitterColor(), Terraria.Projectile.HandleMovement(), Terraria.Initializers.UILinksInitializer.HandleOptionsSpecials(), Terraria.NPC.HitEffect(), Terraria.Main.hslToRgb(), Terraria.Player.ItemCheck_ApplyHoldStyle(), Terraria.Player.ItemCheck_ApplyUseStyle(), Terraria.Player.ItemCheck_EmitUseVisuals(), Terraria.Initializers.ChromaInitializer.Load(), Terraria.GameContent.RGB.EmpressShader.ProcessHighDetail(), Terraria.GameContent.UI.States.UICharacterCreation.ScaledHslToRgb(), Terraria.Utils.ShiftHue(), Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.Spawn_BestReforge(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsDownDashExplosion(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsFlint(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_LeafCrystalShot(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_LoadOutChange(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_NatureFly(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_PrincessWeapon(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_RainbowBoulder1(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_RainbowBoulder2(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_RainbowBoulder3(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_RainbowBoulder4(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_RainbowRodHit(), Terraria.GameContent.UI.States.UIWorldCreation.Spawn_RainbowRodHit(), Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.Spawn_RainbowRodHit(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ShadowOrbExplosion(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ShimmerArrow(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ShimmerBlock(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ShimmerTownNPC(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ShimmerTownNPCSend(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_StardustPunch(), Terraria.GameContent.UI.States.UIWorldCreation.StripColors(), Terraria.Graphics.RainbowRodDrawer.StripColors(), Terraria.Main.TeleportEffect(), Terraria.NPC.UpdateNPC_TeleportVisuals(), Terraria.GameContent.LeashedEntities.EmpressButterflyLeashedCritter.VisualEffects(), Terraria.Player.WingFrame(), and Terraria.Player.Yoraiz0rEye().