Terraria Decompiled: Terraria.Main.UpdateTime_StartDay
UpdateTime_StartDay()
static void Terraria.Main.UpdateTime_StartDay (ref bool stopEvents) inline static
Definition at line 66716 of file Main.cs.
        {
            WorldGen.ResetTreeShakes();
            if (Main.fastForwardTimeToDawn)
            {
                Main.fastForwardTimeToDawn = false;
                Main.UpdateTimeRate();
            }
            Main.AnglerQuestSwap();
            BirthdayParty.CheckMorning();
            LanternNight.CheckMorning();
            if (Main.invasionDelay > 0)
            {
                Main.invasionDelay--;
            }
            WorldGen.prioritizedTownNPCType = 0;
            Main.checkForSpawns = 0;
            Main.time = 0.0;
            if (Main.bloodMoon && Main.netMode != 1)
            {
                AchievementsHelper.NotifyProgressionEvent(5);
            }
            Main.bloodMoon = false;
            Main.CheckForMoonEventsScoreDisplay();
            Main.CheckForMoonEventsStartingTemporarySeasons();
            Main.checkXMas();
            Main.checkHalloween();
            Main.stopMoonEvent();
            Main.dayTime = true;
            if (Main.sundialCooldown > 0)
            {
                Main.sundialCooldown--;
            }
            Main.moonPhase++;
            if (Main.moonPhase >= 8)
            {
                Main.moonPhase = 0;
            }
            if (Main.drunkWorld && Main.netMode != 1)
            {
                WorldGen.crimson = !WorldGen.crimson;
            }
            if (Main.netMode == 2)
            {
                NetMessage.SendData(7, -1, -1, null, 0, 0f, 0f, 0f, 0, 0, 0);
            }
            if (Main.netMode != 1)
            {
                AchievementsHelper.NotifyProgressionEvent(1);
                if (!stopEvents)
                {
                    if (Main.hardMode && NPC.downedMechBossAny && Main.rand.Next(20) == 0)
                    {
                        Main.sundialCooldown = 0;
                        Main.moondialCooldown = 0;
                        Main.eclipse = true;
                        AchievementsHelper.NotifyProgressionEvent(2);
                        if (Main.eclipse)
{
                            if (Main.remixWorld)
{
                                ChatHelper.BroadcastChatMessage(Lang.misc[106].ToNetworkText(), ChatColors.World, -1);
                            }
                            else
{
                                ChatHelper.BroadcastChatMessage(Lang.misc[20].ToNetworkText(), ChatColors.World, -1);
                            }
                        }
                        if (Main.netMode == 2)
{
                            NetMessage.SendData(7, -1, -1, null, 0, 0f, 0f, 0f, 0, 0, 0);
                            return;
                        }
                    }
                    else if (!Main.snowMoon && !Main.pumpkinMoon && !DD2Event.Ongoing)
                    {
                        if (WorldGen.shadowOrbSmashed)
{
                            if (!NPC.downedGoblins)
{
                                if (Main.rand.Next(3) == 0)
{
                                    Main.StartInvasion(1);
                                }
                            }
                            else if ((Main.hardMode && Main.rand.Next(60) == 0) || (!Main.hardMode && Main.rand.Next(30) == 0))
{
                                Main.StartInvasion(1);
                            }
                        }
                        if (Main.invasionType == 0 && Main.hardMode && (WorldGen.altarCount > 0 || WorldGen.Skyblock.lowTiles) && ((NPC.downedPirates && Main.rand.Next(60) == 0) || (!NPC.downedPirates && Main.rand.Next(30) == 0)))
{
                            Main.StartInvasion(3);
                        }
                    }
                }
            }
        }
References Terraria.WorldGen.altarCount, Terraria.Main.AnglerQuestSwap(), Terraria.Main.bloodMoon, Terraria.Chat.ChatHelper.BroadcastChatMessage(), Terraria.Main.CheckForMoonEventsScoreDisplay(), Terraria.Main.CheckForMoonEventsStartingTemporarySeasons(), Terraria.Main.checkHalloween(), Terraria.GameContent.Events.BirthdayParty.CheckMorning(), Terraria.GameContent.Events.LanternNight.CheckMorning(), Terraria.Main.checkXMas(), Terraria.WorldGen.crimson, Terraria.NPC.downedGoblins, Terraria.NPC.downedMechBossAny, Terraria.NPC.downedPirates, Terraria.Main.drunkWorld, Terraria.Main.eclipse, Terraria.Main.fastForwardTimeToDawn, Terraria.Main.hardMode, Terraria.Main.invasionDelay, Terraria.Main.invasionType, Terraria.WorldGen.Skyblock.lowTiles, Terraria.Lang.misc, Terraria.Main.moonPhase, Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.GameContent.Achievements.AchievementsHelper.NotifyProgressionEvent(), Terraria.GameContent.Events.DD2Event.Ongoing, Terraria.Main.pumpkinMoon, Terraria.Main.rand, Terraria.Main.remixWorld, Terraria.WorldGen.ResetTreeShakes(), Terraria.NetMessage.SendData(), Terraria.WorldGen.shadowOrbSmashed, Terraria.Main.snowMoon, Terraria.Main.StartInvasion(), Terraria.Main.stopMoonEvent(), Terraria.Main.sundialCooldown, Terraria.Localization.LocalizedText.ToNetworkText(), Terraria.Main.UpdateTimeRate(), and Terraria.Chat.ChatColors.World.
Referenced by Terraria.Main.SkipToTime(), and Terraria.Main.UpdateTime().