Terraria Decompiled: Terraria.Main.DrawBackground_DrawRockLayer
DrawBackground_DrawRockLayer()
void Terraria.Main.DrawBackground_DrawRockLayer (float localShimmerAlpha, double magmaLayer, int q1, int q2, ref Vector2 drawOffset, ref Vector3 backgroundColor) inline private
Definition at line 53674 of file Main.cs.
        {
            int rockTransitionPoint = this.GetRockTransitionPoint();
            bool flag = (float)rockTransitionPoint <= Main.screenPosition.Y + (float)Main.screenHeight && magmaLayer * 16.0 < (double)(Main.screenPosition.Y + (float)Main.screenHeight);
            int num = rockTransitionPoint;
            double num2 = magmaLayer * 16.0 + 600.0;
            this.bgTopY = (float)num - Main.screenPosition.Y;
            float x = backgroundColor.X;
            float y = backgroundColor.Y;
            float z = backgroundColor.Z;
            int num3 = 128;
            if ((float)rockTransitionPoint <= Main.screenPosition.Y + (float)Main.screenHeight)
            {
                this.bgParallax = (double)Main.caveParallax;
                this.bgStartX = (int)(-Math.IEEERemainder((double)num3 + (double)Main.screenPosition.X * this.bgParallax, (double)num3) - (double)(num3 / 2)) - (int)drawOffset.X;
                this.bgLoops = (Main.screenWidth + (int)drawOffset.X * 2) / num3 + 2;
                if ((float)(rockTransitionPoint + Main.screenHeight) < Main.screenPosition.Y - 16f)
                {
                    this.bgStartY = (int)(Math.IEEERemainder((double)this.bgTopY, (double)Main.backgroundHeight[3]) - (double)Main.backgroundHeight[3]);
                    this.bgLoopsY = (Main.screenHeight - this.bgStartY + (int)drawOffset.Y * 2) / Main.backgroundHeight[2] + 1;
                }
                else
                {
                    this.bgStartY = (int)this.bgTopY;
                    this.bgLoopsY = (int)((float)Main.screenHeight - this.bgTopY + drawOffset.Y * 2f) / Main.backgroundHeight[2] + 1;
                }
                if (magmaLayer * 16.0 < (double)(Main.screenPosition.Y + (float)Main.screenHeight))
                {
                    this.bgLoopsY = (int)(num2 - (double)this.bgStartY - (double)Main.screenPosition.Y) / Main.backgroundHeight[2];
                }
                int num4 = (int)((float)Math.Round((double)(-(double)((float)Math.IEEERemainder((double)((float)this.bgStartX + Main.screenPosition.X), 16.0)))));
                if (num4 == -8)
                {
                    num4 = 8;
                }
                for (int i = 0; i < this.bgLoops; i++)
                {
                    for (int j = 0; j < this.bgLoopsY; j++)
                    {
                        for (int k = 0; k < num3 / 16; k++)
{
                            for (int l = 0; l < 6; l++)
{
                                float num5 = (float)(this.bgStartY + j * 96 + l * 16 + 8);
                                int num6 = (int)(((float)(this.bgStartX + num3 * i + k * 16 + 8) + Main.screenPosition.X) / 16f);
                                int num7 = (int)((num5 + Main.screenPosition.Y) / 16f);
                                if (WorldGen.InWorld(num6, num7, 1))
{
                                    Microsoft.Xna.Framework.Color color = Lighting.GetColor(num6, num7);
                                    if ((Main.ShouldDrawBackgroundTileAt(num6, num7) || color.R == 0 || color.G == 0 || color.B == 0) && (color.R > 0 || color.G > 0 || color.B > 0) && (Main.WallLightAt(num6, num7) || Main.caveParallax != 0f))
{
                                        if (localShimmerAlpha == 0f && Lighting.NotRetro && color.R < 230 && color.G < 230 && color.B < 230 && Main.ugBackTransition == 0f)
{
                                            if (((int)color.R > q1 || (double)color.G > (double)q1 * 1.1 || (double)color.B > (double)q1 * 1.2) && !Main.tile[num6, num7].active())
{
                                                Lighting.GetColor9Slice(num6, num7, ref this._drawbackground_colorSlices);
                                                for (int m = 0; m < 9; m++)
{
                                                    int num8 = 0;
                                                    int num9 = 0;
                                                    int num10 = 4;
                                                    int num11 = 4;
                                                    Microsoft.Xna.Framework.Color color2 = color;
                                                    Microsoft.Xna.Framework.Color color3 = color;
                                                    switch (m)
{
                                                    case 0:
                                                        if (!Main.tile[num6 - 1, num7 - 1].active())
{
                                                            color3 = this._drawbackground_colorSlices[m];
                                                        }
                                                        break;
                                                    case 1:
                                                        num10 = 8;
                                                        num8 = 4;
                                                        if (!Main.tile[num6, num7 - 1].active())
{
                                                            color3 = this._drawbackground_colorSlices[m];
                                                        }
                                                        break;
                                                    case 2:
                                                        num8 = 12;
                                                        if (!Main.tile[num6 + 1, num7 - 1].active())
{
                                                            color3 = this._drawbackground_colorSlices[m];
                                                        }
                                                        break;
                                                    case 3:
                                                        num11 = 8;
                                                        num9 = 4;
                                                        if (!Main.tile[num6 - 1, num7].active())
{
                                                            color3 = this._drawbackground_colorSlices[m];
                                                        }
                                                        break;
                                                    case 4:
                                                        num10 = 8;
                                                        num11 = 8;
                                                        num8 = 4;
                                                        num9 = 4;
                                                        break;
                                                    case 5:
                                                        num8 = 12;
                                                        num9 = 4;
                                                        num11 = 8;
                                                        if (!Main.tile[num6 + 1, num7].active())
{
                                                            color3 = this._drawbackground_colorSlices[m];
                                                        }
                                                        break;
                                                    case 6:
                                                        num9 = 12;
                                                        if (!Main.tile[num6 - 1, num7 + 1].active())
{
                                                            color3 = this._drawbackground_colorSlices[m];
                                                        }
                                                        break;
                                                    case 7:
                                                        num10 = 8;
                                                        num11 = 4;
                                                        num8 = 4;
                                                        num9 = 12;
                                                        if (!Main.tile[num6, num7 + 1].active())
{
                                                            color3 = this._drawbackground_colorSlices[m];
                                                        }
                                                        break;
                                                    case 8:
                                                        num8 = 12;
                                                        num9 = 12;
                                                        if (!Main.tile[num6 + 1, num7 + 1].active())
{
                                                            color3 = this._drawbackground_colorSlices[m];
                                                        }
                                                        break;
                                                    }
                                                    color2.R = (color.R + color3.R) / 2;
                                                    color2.G = (color.G + color3.G) / 2;
                                                    color2.B = (color.B + color3.B) / 2;
                                                    color2.R = (byte)((float)color2.R * x);
                                                    color2.G = (byte)((float)color2.G * y);
                                                    color2.B = (byte)((float)color2.B * z);
                                                    Main.spriteBatch.Draw(TextureAssets.Background[this._drawBackground_backTexture[3]].Value, new Vector2((float)(this.bgStartX + num3 * i + 16 * k + num8 + num4), (float)(this.bgStartY + Main.backgroundHeight[this._drawBackground_backTexture[3]] * j + 16 * l + num9)) + drawOffset, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * k + num8 + num4 + 16, 16 * l + num9, num10, num11)), color2);
                                                    if (Main.ugBackTransition > 0f)
{
                                                        Microsoft.Xna.Framework.Color color4 = color2;
                                                        color4.R = (byte)((float)color4.R * Main.ugBackTransition);
                                                        color4.G = (byte)((float)color4.G * Main.ugBackTransition);
                                                        color4.B = (byte)((float)color4.B * Main.ugBackTransition);
                                                        color4.A = (byte)((float)color4.A * Main.ugBackTransition);
                                                        Main.spriteBatch.Draw(TextureAssets.Background[this._drawBackground_oldBackTexture[3]].Value, new Vector2((float)(this.bgStartX + num3 * i + 16 * k + num8 + num4), (float)(this.bgStartY + Main.backgroundHeight[this._drawBackground_oldBackTexture[3]] * j + 16 * l + num9)) + drawOffset, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * k + num8 + num4 + 16, 16 * l + num9, num10, num11)), color4);
                                                    }
                                                }
                                            }
                                            else if ((int)color.R > q2 || (double)color.G > (double)q2 * 1.1 || (double)color.B > (double)q2 * 1.2)
{
                                                Lighting.GetColor4Slice(num6, num7, ref this._drawbackground_colorSlices);
                                                for (int n = 0; n < 4; n++)
{
                                                    int num12 = 0;
                                                    int num13 = 0;
                                                    Microsoft.Xna.Framework.Color color5 = color;
                                                    Microsoft.Xna.Framework.Color color6 = this._drawbackground_colorSlices[n];
                                                    switch (n)
{
                                                    case 1:
                                                        num12 = 8;
                                                        break;
                                                    case 2:
                                                        num13 = 8;
                                                        break;
                                                    case 3:
                                                        num12 = 8;
                                                        num13 = 8;
                                                        break;
                                                    }
                                                    color5.R = (color.R + color6.R) / 2;
                                                    color5.G = (color.G + color6.G) / 2;
                                                    color5.B = (color.B + color6.B) / 2;
                                                    color5.R = (byte)((float)color5.R * x);
                                                    color5.G = (byte)((float)color5.G * y);
                                                    color5.B = (byte)((float)color5.B * z);
                                                    Main.spriteBatch.Draw(TextureAssets.Background[this._drawBackground_backTexture[3]].Value, new Vector2((float)(this.bgStartX + num3 * i + 16 * k + num12 + num4), (float)(this.bgStartY + Main.backgroundHeight[this._drawBackground_backTexture[3]] * j + 16 * l + num13)) + drawOffset, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * k + num12 + num4 + 16, 16 * l + num13, 8, 8)), color5);
                                                    if (Main.ugBackTransition > 0f)
{
                                                        Microsoft.Xna.Framework.Color color7 = color5;
                                                        color7.R = (byte)((float)color7.R * Main.ugBackTransition);
                                                        color7.G = (byte)((float)color7.G * Main.ugBackTransition);
                                                        color7.B = (byte)((float)color7.B * Main.ugBackTransition);
                                                        color7.A = (byte)((float)color7.A * Main.ugBackTransition);
                                                        Main.spriteBatch.Draw(TextureAssets.Background[this._drawBackground_oldBackTexture[3]].Value, new Vector2((float)(this.bgStartX + num3 * i + 16 * k + num12 + num4), (float)(this.bgStartY + Main.backgroundHeight[this._drawBackground_oldBackTexture[3]] * j + 16 * l + num13)) + drawOffset, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * k + num12 + num4 + 16, 16 * l + num13, 8, 8)), color7);
                                                    }
                                                }
                                            }
                                            else
{
                                                color.R = (byte)((float)color.R * x);
                                                color.G = (byte)((float)color.G * y);
                                                color.B = (byte)((float)color.B * z);
                                                Main.spriteBatch.Draw(TextureAssets.Background[this._drawBackground_backTexture[3]].Value, new Vector2((float)(this.bgStartX + num3 * i + 16 * k + num4), (float)(this.bgStartY + Main.backgroundHeight[this._drawBackground_backTexture[3]] * j + 16 * l)) + drawOffset, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * k + num4 + 16, 16 * l, 16, 16)), color);
                                                if (Main.ugBackTransition > 0f)
{
                                                    Microsoft.Xna.Framework.Color color8 = color;
                                                    color8.R = (byte)((float)color8.R * Main.ugBackTransition);
                                                    color8.G = (byte)((float)color8.G * Main.ugBackTransition);
                                                    color8.B = (byte)((float)color8.B * Main.ugBackTransition);
                                                    color8.A = (byte)((float)color8.A * Main.ugBackTransition);
                                                    Main.spriteBatch.Draw(TextureAssets.Background[this._drawBackground_oldBackTexture[3]].Value, new Vector2((float)(this.bgStartX + num3 * i + 16 * k + num4), (float)(this.bgStartY + Main.backgroundHeight[this._drawBackground_oldBackTexture[3]] * j + 16 * l)) + drawOffset, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * k + num4 + 16, 16 * l, 16, 16)), color8);
                                                }
                                            }
                                        }
                                        else
{
                                            color.R = (byte)((float)color.R * x);
                                            color.G = (byte)((float)color.G * y);
                                            color.B = (byte)((float)color.B * z);
                                            if (localShimmerAlpha > 0f)
{
                                                color *= 1f - localShimmerAlpha;
                                            }
                                            Main.spriteBatch.Draw(TextureAssets.Background[this._drawBackground_backTexture[3]].Value, new Vector2((float)(this.bgStartX + num3 * i + 16 * k + num4), (float)(this.bgStartY + Main.backgroundHeight[this._drawBackground_backTexture[3]] * j + 16 * l)) + drawOffset, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * k + num4 + 16, 16 * l, 16, 16)), color);
                                            if (Main.ugBackTransition > 0f)
{
                                                Microsoft.Xna.Framework.Color color9 = color;
                                                color9.R = (byte)((float)color9.R * Main.ugBackTransition);
                                                color9.G = (byte)((float)color9.G * Main.ugBackTransition);
                                                color9.B = (byte)((float)color9.B * Main.ugBackTransition);
                                                color9.A = (byte)((float)color9.A * Main.ugBackTransition);
                                                Main.spriteBatch.Draw(TextureAssets.Background[this._drawBackground_oldBackTexture[3]].Value, new Vector2((float)(this.bgStartX + num3 * i + 16 * k + num4), (float)(this.bgStartY + Main.backgroundHeight[this._drawBackground_oldBackTexture[3]] * j + 16 * l)) + drawOffset, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * k + num4 + 16, 16 * l, 16, 16)), color9);
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
                this.DrawBackground_DrawMagmaTransition(ref drawOffset, flag, ref backgroundColor, ref num3, num4);
            }
        }
References Terraria.Tile.active(), Microsoft.Xna.Framework.Color.B, Terraria.GameContent.TextureAssets.Background, Terraria.Main.backgroundHeight, Terraria.Main.caveParallax, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Color.G, Terraria.Lighting.GetColor(), Terraria.Lighting.GetColor4Slice(), Terraria.Lighting.GetColor9Slice(), System.Math.IEEERemainder(), int, Terraria.WorldGen.InWorld(), Terraria.Lighting.NotRetro, Microsoft.Xna.Framework.Color.R, System.Math.Round(), Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.ShouldDrawBackgroundTileAt(), Terraria.Main.spriteBatch, Terraria.Main.tile, Terraria.Main.ugBackTransition, ReLogic.Content.Asset< T >.Value, Terraria.Main.WallLightAt(), Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.