Terraria Decompiled: Terraria.Main.DrawGamepadInstructions
DrawGamepadInstructions()
static void Terraria.Main.DrawGamepadInstructions () inline static
Definition at line 20402 of file Main.cs.
        {
            if (Main.drawingPlayerChat)
            {
                return;
            }
            if (!PlayerInput.SettingsForUI.ShowGamepadHints)
            {
                return;
            }
            string text = PlayerInput.ComposeInstructionsForGamepad();
            PlayerInput.AllowExecutionOfGamepadInstructions = false;
            if (Main.GamepadDisableInstructionsDisplay)
            {
                return;
            }
            if (text.Length > 0)
            {
                float num = 35f;
                float num2 = 1f;
                Vector2 vector = new Vector2(num2);
                if (Main.gameMenu)
                {
                    num = 55f;
                }
                if (Main.menuMode == 0)
                {
                    num += 32f;
                }
                Vector2 stringSize = ChatManager.GetStringSize(FontAssets.MouseText.Value, text, new Vector2(1f), -1f);
                float num3 = num2;
                Utils.Swap<float>(ref GlyphTagHandler.GlyphsScale, ref num3);
                ChatManager.DrawColorCodedStringWithShadow(Main.spriteBatch, FontAssets.MouseText.Value, text, new Vector2(12f, (float)Main.screenHeight - num) - stringSize * new Vector2(0f, 0f), Microsoft.Xna.Framework.Color.White, 0f, Vector2.Zero, vector, -1f, num2 * 2f);
                Utils.Swap<float>(ref GlyphTagHandler.GlyphsScale, ref num3);
            }
        }
References Terraria.GameInput.PlayerInput.ComposeInstructionsForGamepad(), Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.Main.drawingPlayerChat, Terraria.Main.gameMenu, Terraria.Main.GamepadDisableInstructionsDisplay, Terraria.UI.Chat.ChatManager.GetStringSize(), Terraria.GameContent.UI.Chat.GlyphTagHandler.GlyphsScale, Terraria.Main.menuMode, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.screenHeight, Terraria.GameInput.PlayerInput.SettingsForUI.ShowGamepadHints, Terraria.Main.spriteBatch, System.text, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Color.White, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.Main.DrawInterface_35_YouDied(), and Terraria.Main.DrawPendingMouseText().