Terraria Decompiled: Terraria.Main.DrawBlack
DrawBlack()
void Terraria.Main.DrawBlack (bool intoRenderTargets = false, bool force = false) inline protected
Definition at line 58685 of file Main.cs.
        {
            if (Main.shimmerAlpha == 1f || TileDrawingBase.DrawOwnBlacks)
            {
                return;
            }
            TimeLogger.StartTimestamp startTimestamp = TimeLogger.Start();
            Main.spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, Main.DefaultSamplerState, DepthStencilState.None, intoRenderTargets ? RasterizerState.CullCounterClockwise : Main.Rasterizer, null, intoRenderTargets ? Matrix.Identity : Main.Transform);
            int num = (int)((Main.tileColor.R + Main.tileColor.G + Main.tileColor.B) / 3);
            float num2 = (float)((double)num * 0.4) / 255f;
            if (Lighting.Mode == LightMode.Retro)
            {
                num2 = (float)(Main.tileColor.R - 55) / 255f;
                if (num2 < 0f)
                {
                    num2 = 0f;
                }
            }
            else if (Lighting.Mode == LightMode.Trippy)
            {
                num2 = (float)(num - 55) / 255f;
                if (num2 < 0f)
                {
                    num2 = 0f;
                }
            }
            Vector2 vector;
            int num3;
            int num4;
            int num5;
            int num6;
            TileDrawing.GetScreenDrawArea(!Main.drawToScreen, out vector, out num3, out num4, out num5, out num6);
            if (!force)
            {
                if (num5 < Main.maxTilesY / 2)
                {
                    num6 = Math.Min(num6, (int)Main.worldSurface + 1);
                    num5 = Math.Min(num5, (int)Main.worldSurface + 1);
                }
                else
                {
                    num6 = Math.Max(num6, Main.UnderworldLayer);
                    num5 = Math.Max(num5, Main.UnderworldLayer);
                }
            }
            bool flag = Main.ShouldShowInvisibleBlocksAndWalls();
            for (int i = num5; i < num6; i++)
            {
                bool flag2 = i >= Main.UnderworldLayer;
                if (flag2)
                {
                    num2 = 0.2f;
                }
                for (int j = num3; j < num4; j++)
                {
                    int num7 = j;
                    while (j < num4)
                    {
                        if (!WorldGen.InWorld(j, i, 0))
{
                            return;
                        }
                        if (Main.tile[j, i] == null)
{
                            Main.tile[j, i] = new Tile();
                        }
                        Tile tile = Main.tile[j, i];
                        float num8 = Lighting.Brightness(j, i);
                        num8 = (float)Math.Floor((double)(num8 * 255f)) / 255f;
                        byte b = tile.liquid;
                        bool flag3 = num8 <= num2 && ((!flag2 && b < 250) || WorldGen.SolidTile(tile) || (b >= 200 && num8 == 0f));
                        bool flag4 = tile.active() && Main.tileBlockLight[(int)tile.type] && (!tile.invisibleBlock() || flag);
                        bool flag5 = !WallID.Sets.Transparent[(int)tile.wall] && (!tile.invisibleWall() || flag);
                        if (!flag3 || (!flag5 && !flag4) || (!Main.drawToScreen && LiquidRenderer.Instance.HasFullWater(j, i) && tile.wall == 0 && !tile.halfBrick() && (double)i > Main.worldSurface))
{
                            break;
                        }
                        j++;
                    }
                    if (j - num7 > 0)
                    {
                        Main.spriteBatch.Draw(TextureAssets.BlackTile.Value, new Vector2((float)(num7 << 4), (float)(i << 4)) - Main.screenPosition + vector, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, j - num7 << 4, 16)), Microsoft.Xna.Framework.Color.Black);
                    }
                }
            }
            Main.spriteBatch.End();
            TimeLogger.DrawBlackTiles.AddTime(startTimestamp);
        }
References Terraria.Tile.active(), Microsoft.Xna.Framework.Graphics.BlendState.AlphaBlend, Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(), Microsoft.Xna.Framework.Color.Black, Terraria.GameContent.TextureAssets.BlackTile, Terraria.Lighting.Brightness(), Microsoft.Xna.Framework.Graphics.RasterizerState.CullCounterClockwise, Terraria.Main.DefaultSamplerState, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.TimeLogger.DrawBlackTiles, Terraria.GameContent.Drawing.TileDrawingBase.DrawOwnBlacks, Terraria.Main.drawToScreen, Microsoft.Xna.Framework.Graphics.SpriteBatch.End(), System.Math.Floor(), Terraria.GameContent.Drawing.TileDrawing.GetScreenDrawArea(), Terraria.Tile.halfBrick(), Terraria.GameContent.Liquid.LiquidRenderer.HasFullWater(), Terraria.GameContent.Liquid.LiquidRenderer.Instance, int, Terraria.Tile.invisibleBlock(), Terraria.Tile.invisibleWall(), Terraria.WorldGen.InWorld(), Terraria.Tile.liquid, System.Math.Max(), Terraria.Main.maxTilesY, System.Math.Min(), Terraria.Lighting.Mode, Microsoft.Xna.Framework.Graphics.DepthStencilState.None, Terraria.Main.Rasterizer, Terraria.Main.shimmerAlpha, Terraria.Main.ShouldShowInvisibleBlocksAndWalls(), Terraria.WorldGen.SolidTile(), Terraria.Main.spriteBatch, Terraria.TimeLogger.Start(), Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.Main.tileBlockLight, Terraria.Main.tileColor, Terraria.Main.Transform, Terraria.ID.WallID.Sets.Transparent, Terraria.Tile.type, Terraria.Main.UnderworldLayer, ReLogic.Content.Asset< T >.Value, Terraria.Tile.wall, and Terraria.Main.worldSurface.