Terraria Decompiled: Terraria.Main.DrawProj_TrueNightsEdge
DrawProj_TrueNightsEdge()
void Terraria.Main.DrawProj_TrueNightsEdge (Projectile proj) inline private
Definition at line 26917 of file Main.cs.
        {
            Asset<Texture2D> asset = TextureAssets.Projectile[proj.type];
            Microsoft.Xna.Framework.Rectangle rectangle = asset.Frame(1, 4, 0, 0, 0, 0);
            Vector2 vector = rectangle.Size() / 2f;
            float num = proj.scale * 1.1f;
            SpriteEffects spriteEffects = ((proj.ai[0] >= 0f) ? SpriteEffects.None : SpriteEffects.FlipVertically);
            float num2 = 0.975f;
            float num3 = Lighting.GetColor(proj.Center.ToTileCoordinates()).ToVector3().Length() / (float)Math.Sqrt(3.0);
            num3 = Utils.Remap(num3, 0.2f, 1f, 0f, 1f, true);
            float num4 = MathHelper.Min(0.15f + num3 * 0.85f, Utils.Remap(proj.localAI[0], 30f, 96f, 1f, 0f, true));
            proj.Size / 2f;
            float num5 = 2f;
            for (float num6 = num5; num6 >= 0f; num6 -= 1f)
            {
                if (!(proj.oldPos[(int)num6] == Vector2.Zero))
                {
                    Vector2 vector2 = proj.Center - proj.velocity * 0.5f * num6;
                    float num7 = proj.oldRot[(int)num6] + proj.ai[0] * 6.2831855f * 0.1f * -num6;
                    Vector2 vector3 = vector2 - Main.screenPosition;
                    float num8 = 1f - num6 / num5;
                    float num9 = proj.Opacity * num8 * num8 * 0.85f;
                    float num10 = proj.Opacity * proj.Opacity;
                    Microsoft.Xna.Framework.Color color = Microsoft.Xna.Framework.Color.Lerp(new Microsoft.Xna.Framework.Color(40, 20, 60, 120), new Microsoft.Xna.Framework.Color(80, 160, 50, 120), num10);
                    Main.spriteBatch.Draw(asset.Value, vector3, new Microsoft.Xna.Framework.Rectangle?(rectangle), color * num4 * num9, num7 + proj.ai[0] * 0.7853982f * -1f, vector, num * num2, spriteEffects, 0f);
                    Microsoft.Xna.Framework.Color color2 = Microsoft.Xna.Framework.Color.Lerp(new Microsoft.Xna.Framework.Color(80, 40, 180), new Microsoft.Xna.Framework.Color(155, 255, 100), num10);
                    Microsoft.Xna.Framework.Color color3 = Microsoft.Xna.Framework.Color.White * num9 * 0.5f;
                    color3.A = (byte)((float)color3.A * (1f - num4));
                    Microsoft.Xna.Framework.Color color4 = color3 * num4 * 0.5f;
                    color4.G = (byte)((float)color4.G * num4);
                    color4.R = (byte)((float)color4.R * (0.25f + num4 * 0.75f));
                    float num11 = 3f;
                    for (float num12 = -6.2831855f + 6.2831855f / num11; num12 < 0f; num12 += 6.2831855f / num11)
                    {
                        float num13 = Utils.Remap(num12, -6.2831855f, 0f, 0f, 0.5f, true);
                        Main.spriteBatch.Draw(asset.Value, vector3, new Microsoft.Xna.Framework.Rectangle?(rectangle), color4 * 0.15f * num13, num7 + proj.ai[0] * 0.01f + num12, vector, num, spriteEffects, 0f);
                        Main.spriteBatch.Draw(asset.Value, vector3, new Microsoft.Xna.Framework.Rectangle?(rectangle), Microsoft.Xna.Framework.Color.Lerp(new Microsoft.Xna.Framework.Color(80, 30, 160), new Microsoft.Xna.Framework.Color(200, 255, 0), num10) * num3 * num9 * num13, num7 + num12, vector, num * 0.8f, spriteEffects, 0f);
                        Main.spriteBatch.Draw(asset.Value, vector3, new Microsoft.Xna.Framework.Rectangle?(rectangle), color2 * num3 * num9 * MathHelper.Lerp(0.05f, 0.4f, num3) * num13, num7 + num12, vector, num * num2, spriteEffects, 0f);
                        Main.spriteBatch.Draw(asset.Value, vector3, new Microsoft.Xna.Framework.Rectangle?(asset.Frame(1, 4, 0, 3, 0, 0)), Microsoft.Xna.Framework.Color.White * MathHelper.Lerp(0.05f, 0.5f, num3) * num9 * num13, num7 + num12, vector, num, spriteEffects, 0f);
                    }
                    Main.spriteBatch.Draw(asset.Value, vector3, new Microsoft.Xna.Framework.Rectangle?(rectangle), color4 * 0.15f, num7 + proj.ai[0] * 0.01f, vector, num, spriteEffects, 0f);
                    Main.spriteBatch.Draw(asset.Value, vector3, new Microsoft.Xna.Framework.Rectangle?(rectangle), Microsoft.Xna.Framework.Color.Lerp(new Microsoft.Xna.Framework.Color(80, 30, 160), new Microsoft.Xna.Framework.Color(200, 255, 0), num10) * num4 * num9, num7, vector, num * 0.8f, spriteEffects, 0f);
                    Main.spriteBatch.Draw(asset.Value, vector3, new Microsoft.Xna.Framework.Rectangle?(rectangle), color2 * num3 * num9 * MathHelper.Lerp(0.05f, 0.4f, num4), num7, vector, num * num2, spriteEffects, 0f);
                    Main.spriteBatch.Draw(asset.Value, vector3, new Microsoft.Xna.Framework.Rectangle?(asset.Frame(1, 4, 0, 3, 0, 0)), Microsoft.Xna.Framework.Color.White * MathHelper.Lerp(0.05f, 0.5f, num4) * num9, num7, vector, num, spriteEffects, 0f);
                }
            }
            float num14 = 1f - proj.localAI[0] * 1f / 80f;
            if (num14 < 0.5f)
            {
                num14 = 0.5f;
            }
            Vector2 vector4 = proj.Center - Main.screenPosition + (proj.rotation + 0.47123894f * proj.ai[0]).ToRotationVector2() * ((float)asset.Width() * 0.5f - 4f) * num * num14;
            float num15 = MathHelper.Min(num4, MathHelper.Lerp(1f, num3, Utils.Remap(proj.localAI[0], 0f, 80f, 0f, 1f, true)));
            Main.DrawPrettyStarSparkle(proj.Opacity, SpriteEffects.None, vector4, new Microsoft.Xna.Framework.Color(255, 255, 255, 0) * proj.Opacity * 0.5f * num15, new Microsoft.Xna.Framework.Color(150, 255, 100) * num15, proj.Opacity, 0f, 1f, 1f, 2f, 0.7853982f, new Vector2(2f, 2f), Vector2.One);
        }
References Terraria.Projectile.ai, Terraria.Entity.Center, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Main.DrawPrettyStarSparkle(), Terraria.Lighting.GetColor(), int, Microsoft.Xna.Framework.Color.Lerp(), Microsoft.Xna.Framework.MathHelper.Lerp(), Terraria.Projectile.localAI, Microsoft.Xna.Framework.MathHelper.Min(), Terraria.Projectile.oldPos, Terraria.Projectile.oldRot, Microsoft.Xna.Framework.Vector2.One, Terraria.Projectile.Opacity, Terraria.GameContent.TextureAssets.Projectile, Terraria.Utils.Remap(), Terraria.Main.screenPosition, Terraria.Main.spriteBatch, System.Math.Sqrt(), Terraria.Projectile.type, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Color.White, and Microsoft.Xna.Framework.Vector2.Zero.