Terraria Decompiled: Terraria.Main.DrawSurfaceBG
DrawSurfaceBG()
void Terraria.Main.DrawSurfaceBG (SpriteBatchBeginner parentSpriteBatchBeginner, float? verticalParallaxOverride = null) inline protected
Definition at line 60134 of file Main.cs.
        {
            Main.LatestSurfaceBackgroundBeginner = parentSpriteBatchBeginner;
            bool flag = Main.ShouldDrawSurfaceBackground();
            Microsoft.Xna.Framework.Color colorOfSurfaceBackgroundsBase = Main.ColorOfSurfaceBackgroundsBase;
            int num = 30;
            if (Main.gameMenu)
            {
                num = 0;
            }
            if (WorldGen.drunkWorldGen)
            {
                if (Main.onlyShimmerOceanWorldsGeneration)
                {
                    num = -240;
                }
                else if (Main.vampireSeed)
                {
                    num = -100;
                }
                else if (!Main.notTheBeesWorld)
                {
                    num = -180;
                }
            }
            float num2 = (float)Main.worldSurface;
            if (num2 == 0f)
            {
                num2 = 1f;
            }
            float num3 = verticalParallaxOverride ?? (-(Main.screenPosition.Y - 300f) / (num2 * 16f));
            this.bgTopY = num3 * 1200f + 1190f + this.scAdj;
            float num4 = 2f;
            int num5 = 0;
            float num6 = SkyManager.Instance.ProcessCloudAlpha() * Main.atmo;
            int num7 = 0;
            this.HorizonRenderer.DrawSurfaceLayer(num7++);
            this.DrawClouds_Distant(flag, num3, num5, num6);
            this.HorizonRenderer.DrawSurfaceLayer(num7++);
            if (Main.invasionType == 4 && !SkyManager.Instance["Martian"].IsActive())
            {
                SkyManager.Instance.Activate("Martian", default(Vector2), new object[0]);
            }
            else if (Main.invasionType != 4 && SkyManager.Instance["Martian"].IsActive())
            {
                SkyManager.Instance.Deactivate("Martian", new object[0]);
            }
            SkyManager.Instance.ResetDepthTracker();
            this.bgParallax = 0.15;
            int num8 = -180;
            bool flag2 = true;
            int num9 = 0;
            if (Main.gameMenu)
            {
                num9 -= num8;
            }
            num5 = num9;
            num5 += num;
            if (!WorldGen.drunkWorldGen && flag && (double)(Main.screenPosition.Y / 16f) <= Main.worldSurface + 10.0)
            {
                if (Main.BackgroundEnabled)
                {
                    if (Main.cloudBGActive > 0f)
                    {
                        Main.cloudBGAlpha += 0.0005f * (float)Main.dayRate;
                        if (Main.cloudBGAlpha > 1f)
{
                            Main.cloudBGAlpha = 1f;
                        }
                    }
                    else
                    {
                        Main.cloudBGAlpha -= 0.0005f * (float)Main.dayRate;
                        if (Main.cloudBGAlpha < 0f)
{
                            Main.cloudBGAlpha = 0f;
                        }
                    }
                    if (Main.cloudBGAlpha > 0f)
                    {
                        this.LoadBackground(Main.cloudBG[0]);
                        this.LoadBackground(Main.cloudBG[1]);
                        float num10 = Main.cloudBGAlpha;
                        if (num10 > 1f)
{
                            num10 = 1f;
                        }
                        Main.bgScale = 1.65f;
                        this.bgParallax = 0.09000000357627869;
                        if (FocusHelper.AllowSkyMovement)
{
                            Main.cloudBGX[0] += Main.windSpeedCurrent * (float)this.bgParallax * 9f * (float)Main.dayRate;
                        }
                        if (Main.cloudBGX[0] > (float)Main.backgroundWidth[Main.cloudBG[0]] * Main.bgScale)
{
                            Main.cloudBGX[0] -= (float)Main.backgroundWidth[Main.cloudBG[0]] * Main.bgScale;
                        }
                        if (Main.cloudBGX[0] < (float)(-(float)Main.backgroundWidth[Main.cloudBG[0]]) * Main.bgScale)
{
                            Main.cloudBGX[0] += (float)Main.backgroundWidth[Main.cloudBG[0]] * Main.bgScale;
                        }
                        float num11 = (float)Main.backgroundWidth[Main.cloudBG[0]] * Main.bgScale;
                        this.bgTopY = num3 * 900f + 600f + this.scAdj + (float)num5;
                        if (Main.gameMenu)
{
                            this.bgTopY = (float)(-150 + num5);
                        }
                        this.bgStartX = (int)(-Math.IEEERemainder((double)Main.screenPosition.X * this.bgParallax, (double)num11) - (double)(num11 / 2f) - (double)num11);
                        this.bgStartX += (int)Main.cloudBGX[0];
                        this.bgLoops = Main.screenWidth / (int)num11 + 2 + 2;
                        Main.ColorOfSurfaceBackgroundsModified = colorOfSurfaceBackgroundsBase * num10;
                        SkyManager.Instance.DrawToDepth(Main.spriteBatch, 1f / (float)this.bgParallax);
                        for (int i = 0; i < this.bgLoops; i++)
{
                            Main.spriteBatch.Draw(TextureAssets.Background[Main.cloudBG[0]].Value, new Vector2((float)this.bgStartX + num11 * (float)i, this.bgTopY), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, Main.backgroundWidth[Main.cloudBG[0]], Main.backgroundHeight[Main.cloudBG[0]])), Main.ColorOfSurfaceBackgroundsModified * num6, 0f, default(Vector2), Main.bgScale, SpriteEffects.None, 0f);
                        }
                        num10 = Main.cloudBGAlpha * 1.5f;
                        if (num10 > 1f)
{
                            num10 = 1f;
                        }
                        Main.ColorOfSurfaceBackgroundsModified = colorOfSurfaceBackgroundsBase * num10;
                        Main.bgScale = 1.85f;
                        this.bgParallax = 0.12;
                        if (FocusHelper.AllowSkyMovement)
{
                            Main.cloudBGX[1] += Main.windSpeedCurrent * (float)this.bgParallax * 9f * (float)Main.dayRate;
                        }
                        if (Main.cloudBGX[1] > (float)Main.backgroundWidth[Main.cloudBG[1]] * Main.bgScale)
{
                            Main.cloudBGX[1] -= (float)Main.backgroundWidth[Main.cloudBG[1]] * Main.bgScale;
                        }
                        if (Main.cloudBGX[1] < (float)(-(float)Main.backgroundWidth[Main.cloudBG[1]]) * Main.bgScale)
{
                            Main.cloudBGX[1] += (float)Main.backgroundWidth[Main.cloudBG[1]] * Main.bgScale;
                        }
                        num11 = (float)Main.backgroundWidth[Main.cloudBG[1]] * Main.bgScale;
                        this.bgTopY = num3 * 1100f + 750f + this.scAdj + (float)num5;
                        if (Main.gameMenu)
{
                            this.bgTopY = (float)(-50 + num5);
                        }
                        this.bgStartX = (int)(-Math.IEEERemainder((double)Main.screenPosition.X * this.bgParallax, (double)num11) - (double)(num11 / 2f) - (double)num11);
                        this.bgStartX += (int)Main.cloudBGX[1];
                        this.bgLoops = Main.screenWidth / (int)num11 + 2 + 2;
                        SkyManager.Instance.DrawToDepth(Main.spriteBatch, 1f / (float)this.bgParallax);
                        for (int j = 0; j < this.bgLoops; j++)
{
                            Main.spriteBatch.Draw(TextureAssets.Background[Main.cloudBG[1]].Value, new Vector2((float)this.bgStartX + num11 * (float)j, this.bgTopY), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, Main.backgroundWidth[Main.cloudBG[1]], Main.backgroundHeight[Main.cloudBG[1]])), Main.ColorOfSurfaceBackgroundsModified * num6, 0f, default(Vector2), Main.bgScale, SpriteEffects.None, 0f);
                        }
                    }
                    this.DrawSurfaceBG_BackMountainsStep1(num3, num4, num5);
                }
                this.DrawClouds_Closer(num6);
                if (Main.SceneMetrics.HolyTileCount > 0 && Main.BackgroundEnabled)
                {
                    double num12 = 0.17;
                    float num13 = 1.1f;
                    int num14 = 1400;
                    int num15 = 900;
                    if (WorldGen.hallowBG == 3)
                    {
                        num15 = 1100;
                    }
                    float num16 = num3 * (float)num14 + (float)num15 + this.scAdj + (float)num5;
                    num13 *= num4;
                    int num17 = (int)((double)(2100f * num13) * 1.05);
                    int num18 = (int)(-Math.IEEERemainder((double)Main.screenPosition.X * num12, (double)num17) - (double)(num17 / 2));
                    int num19 = Main.screenWidth / num17;
                    if (Main.gameMenu)
                    {
                        num16 = (float)(230 + num5);
                        num18 -= 500;
                    }
                    SkyManager.Instance.DrawToDepth(Main.spriteBatch, 1f / (float)num12);
                    Microsoft.Xna.Framework.Color color = colorOfSurfaceBackgroundsBase;
                    float num20 = (float)(Main.SceneMetrics.HolyTileCount - SceneMetrics.HallowTileThreshold) / (float)(SceneMetrics.HallowTileMax - SceneMetrics.HallowTileThreshold);
                    if (num20 > 0.5f)
                    {
                        num20 = 0.5f;
                    }
                    else if (num20 < 0f)
                    {
                        num20 = 0f;
                    }
                    color.R = (byte)((float)color.R * num20);
                    color.G = (byte)((float)color.G * num20);
                    color.B = (byte)((float)color.B * num20);
                    color.A = (byte)((float)color.A * num20 * 0.8f);
                    if ((double)Main.screenPosition.Y < Main.worldSurface * 16.0 + 16.0)
                    {
                        this.LoadBackground(18);
                        this.LoadBackground(19);
                        for (int k = 0; k < this.bgLoops; k++)
{
                            Main.spriteBatch.Draw(TextureAssets.Background[18].Value, new Vector2((float)(num18 + num17 * k), num16), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, Main.backgroundWidth[18], Main.backgroundHeight[18])), color, 0f, default(Vector2), num13, SpriteEffects.None, 0f);
                            Main.spriteBatch.Draw(TextureAssets.Background[19].Value, new Vector2((float)(num18 + num17 * k + 1900), num16 + 100f), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, Main.backgroundWidth[19], Main.backgroundHeight[19])), color, 0f, default(Vector2), num13 * 0.9f, SpriteEffects.None, 0f);
                        }
                    }
                }
                if (Main.treeMntBGSet1[1] > -1)
                {
                    this.LoadBackground(Main.treeMntBGSet1[1]);
                    this.bgParallax = 0.2;
                    Main.bgScale = 1.15f;
                    Main.bgScale *= num4;
                    int num21 = Main.backgroundWidth[Main.treeMntBGSet1[1]];
                    if (num21 == 0)
                    {
                        num21 = 1;
                    }
                    Main.bgWidthScaled = (int)((float)num21 * Main.bgScale);
                    this.bgStartX = (int)(-Math.IEEERemainder((double)Main.screenPosition.X * this.bgParallax, (double)Main.bgWidthScaled) - (double)(Main.bgWidthScaled / 2));
                    this.bgLoops = Main.screenWidth / Main.bgWidthScaled + 2;
                    if (Main.treeMntBGSet1[1] == 172)
                    {
                        this.bgLoops++;
                    }
                    this.bgTopY = num3 * 1400f + 1260f + this.scAdj + (float)num5;
                }
                if (Main.BackgroundEnabled)
                {
                    this.DrawSurfaceBG_BackMountainsStep2(num5);
                }
                this.DrawClouds_Closest(num6);
            }
            this.HorizonRenderer.DrawSurfaceLayer(num7++);
            if (flag2)
            {
                num5 += num8;
            }
            if (flag)
            {
                for (int l = 0; l < Main.bgAlphaFrontLayer.Length; l++)
                {
                    if (Main.BackgroundEnabled)
                    {
                        Main.ColorOfSurfaceBackgroundsModified = colorOfSurfaceBackgroundsBase * Main.bgAlphaFrontLayer[l];
                        if (Main.bgAlphaFrontLayer[l] > 0f && l == 0)
{
                            this.DrawSurfaceBG_Forest(num3, num4, num5, Main.treeBGSet1);
                            this.DrawSurfaceBG_DrawChangeOverlay(0);
                        }
                        if (Main.bgAlphaFrontLayer[l] > 0f && l == 10)
{
                            this.DrawSurfaceBG_Forest(num3, num4, num5, Main.treeBGSet2);
                            this.DrawSurfaceBG_DrawChangeOverlay(1);
                        }
                        if (Main.bgAlphaFrontLayer[l] > 0f && l == 11)
{
                            this.DrawSurfaceBG_Forest(num3, num4, num5, Main.treeBGSet3);
                            this.DrawSurfaceBG_DrawChangeOverlay(2);
                        }
                        if (Main.bgAlphaFrontLayer[l] > 0f && l == 12)
{
                            this.DrawSurfaceBG_Forest(num3, num4, num5, Main.treeBGSet4);
                            this.DrawSurfaceBG_DrawChangeOverlay(3);
                        }
                        if (Main.bgAlphaFrontLayer[l] > 0f && l == 1)
{
                            int[] array = Main.corruptBG;
                            this.DrawSurfaceBG_Corrupt(num3, num4, num5, array);
                            this.DrawSurfaceBG_DrawChangeOverlay(4);
                        }
                        if (Main.bgAlphaFrontLayer[l] > 0f && l == 2)
{
                            int[] backgrounds = Main.desertBackgroundSet.Pure.Backgrounds;
                            this.DrawSurfaceBG_Desert(num3, num4, num5, backgrounds);
                            this.DrawSurfaceBG_DrawChangeOverlay(9);
                        }
                        if (Main.bgAlphaFrontLayer[l] > 0f && l == 3)
{
                            int[] array2 = Main.jungleBG;
                            this.DrawSurfaceBG_Jungle(num3, num4, num5, array2);
                            this.DrawSurfaceBG_DrawChangeOverlay(5);
                        }
                        if (Main.bgAlphaFrontLayer[l] > 0f && l == 4)
{
                            this.DrawSurfaceBG_DrawChangeOverlay(10);
                        }
                        if (Main.bgAlphaFrontLayer[l] > 0f && (l == 5 || l == 13 || l == 14))
{
                            this.DrawSurfaceBG_GoodEvilDesert(num3, num4, num5, l);
                            this.DrawSurfaceBG_DrawChangeOverlay(9);
                        }
                        if (Main.bgAlphaFrontLayer[l] > 0f && l == 6)
{
                            int[] array3 = Main.hallowBG;
                            this.DrawSurfaceBG_Hallow(num3, num4, num5, array3);
                            this.DrawSurfaceBG_DrawChangeOverlay(7);
                        }
                        if (Main.bgAlphaFrontLayer[l] > 0f && l == 7)
{
                            int[] array4 = Main.snowBG;
                            this.DrawSurfaceBG_Snow(num3, num4, num5, array4);
                            this.DrawSurfaceBG_DrawChangeOverlay(6);
                        }
                        if (Main.bgAlphaFrontLayer[l] > 0f && l == 8)
{
                            int[] array5 = Main.crimsonBG;
                            this.DrawSurfaceBG_Crimson(num3, num4, num5, array5);
                            this.DrawSurfaceBG_DrawChangeOverlay(8);
                        }
                        if (Main.bgAlphaFrontLayer[l] > 0f && l == 9)
{
                            int[] array6 = Main.mushroomBG;
                            this.DrawSurfaceBG_Mushroom(num3, num4, num5, array6);
                            this.DrawSurfaceBG_DrawChangeOverlay(11);
                        }
                    }
                }
            }
            this.HorizonRenderer.DrawSurfaceLayer(num7++);
            if (flag2)
            {
                num5 -= num8;
            }
            float num22 = Main.DrawSurfaceBG_GetFogPower();
            if (flag && num22 > 0f && !Main.gameMenu && (double)Main.screenPosition.Y < Main.worldSurface * 16.0 + 16.0)
            {
                this.bgParallax = 0.1;
                this.bgStartX = (int)(-Math.IEEERemainder((double)Main.screenPosition.X * this.bgParallax, (double)Main.backgroundWidth[Main.background]) - (double)(Main.backgroundWidth[Main.background] / 2));
                this.bgLoops = Main.screenWidth / Main.backgroundWidth[Main.background] + 2;
                this.bgStartY = 0;
                this.bgLoopsY = 0;
                this.bgTopY = -Main.screenPosition.Y / ((float)Main.worldSurface * 16f - 600f) * 200f;
                Texture2D value = TextureAssets.Background[49].Value;
                for (int m = 0; m < this.bgLoops; m++)
                {
                    this.bgStartX = 0;
                    Microsoft.Xna.Framework.Color color2 = Main.ColorOfTheSkies * num22 * Main.atmo;
                    int num23 = Math.Max(Main.screenHeight + 210, value.Height);
                    Main.spriteBatch.Draw(value, new Microsoft.Xna.Framework.Rectangle(this.bgStartX + value.Width * m, (int)this.bgTopY, value.Width, num23), color2);
                }
            }
            if (!Main.mapFullscreen)
            {
                SkyManager.Instance.DrawRemainingDepth(Main.spriteBatch);
            }
        }
References Terraria.Graphics.Effects.EffectManager< T >.Activate(), Terraria.FocusHelper.AllowSkyMovement, System.array, Terraria.Main.atmo, Terraria.GameContent.TextureAssets.Background, Terraria.Main.background, Terraria.Main.BackgroundEnabled, Terraria.Main.backgroundHeight, Terraria.DataStructures.BackgroundVariant.Backgrounds, Terraria.Main.backgroundWidth, Terraria.Main.bgAlphaFrontLayer, Terraria.Main.bgScale, Terraria.Main.bgWidthScaled, Terraria.Main.cloudBG, Terraria.Main.cloudBGActive, Terraria.Main.cloudBGAlpha, Terraria.Main.cloudBGX, Terraria.Main.ColorOfSurfaceBackgroundsBase, Terraria.Main.ColorOfSurfaceBackgroundsModified, Terraria.Main.corruptBG, Terraria.Main.crimsonBG, Terraria.Main.dayRate, Terraria.Graphics.Effects.EffectManager< T >.Deactivate(), Terraria.Main.desertBackgroundSet, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Graphics.Effects.SkyManager.DrawRemainingDepth(), Terraria.Main.DrawSurfaceBG_GetFogPower(), Terraria.Graphics.Effects.SkyManager.DrawToDepth(), Terraria.WorldGen.drunkWorldGen, Terraria.Main.gameMenu, Terraria.Main.hallowBG, Terraria.WorldGen.hallowBG, Terraria.SceneMetrics.HallowTileMax, Terraria.SceneMetrics.HallowTileThreshold, Terraria.SceneMetrics.HolyTileCount, System.Math.IEEERemainder(), Terraria.Graphics.Effects.SkyManager.Instance, int, Terraria.Main.invasionType, Terraria.Main.jungleBG, Terraria.Main.mapFullscreen, System.Math.Max(), Terraria.Main.mushroomBG, Terraria.Main.notTheBeesWorld, Terraria.Main.onlyShimmerOceanWorldsGeneration, Terraria.Graphics.Effects.SkyManager.ProcessCloudAlpha(), Terraria.DataStructures.BackgroundVariantSet.Pure, Terraria.Graphics.Effects.SkyManager.ResetDepthTracker(), Terraria.Main.SceneMetrics, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.ShouldDrawSurfaceBackground(), Terraria.Main.snowBG, Terraria.Main.spriteBatch, Terraria.Main.treeBGSet1, Terraria.Main.treeBGSet2, Terraria.Main.treeBGSet3, Terraria.Main.treeBGSet4, Terraria.Main.treeMntBGSet1, System.value, ReLogic.Content.Asset< T >.Value, Terraria.Main.vampireSeed, Terraria.Main.worldSurface, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.