Terraria Decompiled: Terraria.Main.DrawNPCChatBubble
DrawNPCChatBubble()
static void Terraria.Main.DrawNPCChatBubble (int i) inline static private
Definition at line 43129 of file Main.cs.
        {
            int num = -(Main.npc[i].width / 2 + 8);
            float num2 = Main.npc[i].position.Y - (float)TextureAssets.Chat.Height() - (float)((int)Main.screenPosition.Y);
            if (Main.npc[i].type == 637 && Main.npc[i].ai[0] == 5f)
            {
                num2 -= 18f;
            }
            SpriteEffects spriteEffects = SpriteEffects.None;
            if (Main.npc[i].spriteDirection == -1)
            {
                spriteEffects = SpriteEffects.FlipHorizontally;
                num = Main.npc[i].width / 2 + 8;
            }
            if (Main.player[Main.myPlayer].gravDir != 1f)
            {
                spriteEffects |= SpriteEffects.FlipVertically;
                num2 = (float)Main.screenHeight - num2 - (float)TextureAssets.Chat.Height();
            }
            Vector2 vector = new Vector2(Main.npc[i].position.X + (float)(Main.npc[i].width / 2) - Main.screenPosition.X - (float)(TextureAssets.Chat.Width() / 2) - (float)num, num2);
            Main.spriteBatch.End();
            Main.spriteBatch.Begin(SpriteSortMode.Deferred, null, SamplerState.PointClamp, null, null, null, Main.GameViewMatrix.ZoomMatrix);
            PlayerInput.SetZoom_UI();
            Main.spriteBatch.Draw(TextureAssets.Chat.Value, vector, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chat.Width(), TextureAssets.Chat.Height())), new Microsoft.Xna.Framework.Color((int)Main.mouseTextColor, (int)Main.mouseTextColor, (int)Main.mouseTextColor, (int)Main.mouseTextColor), 0f, default(Vector2), 1f, spriteEffects, 0f);
            Main.spriteBatch.End();
            Main.spriteBatch.Begin(SpriteSortMode.Deferred, null, null, null, null, null, Main._uiScaleMatrix);
        }
References Terraria.Main._uiScaleMatrix, Terraria.NPC.ai, Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(), Terraria.GameContent.TextureAssets.Chat, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.End(), Terraria.Main.GameViewMatrix, Terraria.Player.gravDir, Terraria.Main.mouseTextColor, Terraria.Main.myPlayer, Terraria.Main.npc, Terraria.Main.player, Microsoft.Xna.Framework.Graphics.SamplerState.PointClamp, Terraria.Entity.position, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.GameInput.PlayerInput.SetZoom_UI(), Terraria.Main.spriteBatch, Terraria.NPC.spriteDirection, Terraria.NPC.type, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Terraria.Graphics.SpriteViewMatrix.ZoomMatrix.
Referenced by Terraria.Main.DrawInterface_1_1_DrawEmoteBubblesInWorld().