Terraria Decompiled: Terraria.Main.StartRain
StartRain()
static void Terraria.Main.StartRain (bool instant = false, float? strengthOverride = null, bool garenteeCoinRain = false) inline static
Definition at line 65936 of file Main.cs.
        {
            if (!Main.remixWorld && Main.isThereAWorldSurface && !Main.raining)
            {
                int num = 25;
                if (Main.tenthAnniversaryWorld && !Main.getGoodWorld)
                {
                    num = 5;
                }
                num = Player.GetPlayerWithHighestLuck().RollLuck(num);
                if (num == 0 || garenteeCoinRain)
                {
                    float num2 = (float)Main.maxTilesX / 4200f;
                    ChatHelper.BroadcastChatMessage(NetworkText.FromKey(Lang.gen[93].Key, new object[0]), new Microsoft.Xna.Framework.Color(255, 200, 150), -1);
                    Main.coinRain = Main.rand.Next(75, 151) * 100 * 100;
                    Main.coinRain = (int)((float)Main.coinRain * num2);
                }
            }
            int num3 = 86400;
            int num4 = num3 / 24;
            int num5 = Main.rand.Next(num4 * 8, num3);
            if (Main.rand.Next(3) == 0)
            {
                num5 += Main.rand.Next(0, num4);
            }
            if (Main.rand.Next(4) == 0)
            {
                num5 += Main.rand.Next(0, num4 * 2);
            }
            if (Main.rand.Next(5) == 0)
            {
                num5 += Main.rand.Next(0, num4 * 2);
            }
            if (Main.rand.Next(6) == 0)
            {
                num5 += Main.rand.Next(0, num4 * 3);
            }
            if (Main.rand.Next(7) == 0)
            {
                num5 += Main.rand.Next(0, num4 * 4);
            }
            if (Main.rand.Next(8) == 0)
            {
                num5 += Main.rand.Next(0, num4 * 5);
            }
            float num6 = 1f;
            if (Main.rand.Next(2) == 0)
            {
                num6 += 0.05f;
            }
            if (Main.rand.Next(3) == 0)
            {
                num6 += 0.1f;
            }
            if (Main.rand.Next(4) == 0)
            {
                num6 += 0.15f;
            }
            if (Main.rand.Next(5) == 0)
            {
                num6 += 0.2f;
            }
            if (!Main.IsRainingForever)
            {
                Main.rainTime = (int)((float)num5 * num6);
            }
            Main.ChangeRain(instant, strengthOverride);
            Main.raining = true;
        }
References Terraria.Chat.ChatHelper.BroadcastChatMessage(), Terraria.Main.ChangeRain(), Terraria.Localization.NetworkText.FromKey(), Terraria.Lang.gen, Terraria.Main.getGoodWorld, Terraria.Player.GetPlayerWithHighestLuck(), int, Terraria.Main.IsRainingForever, Terraria.Main.isThereAWorldSurface, Terraria.Localization.LocalizedText.Key, Terraria.Main.maxTilesX, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.raining, Terraria.Main.rand, Terraria.Main.remixWorld, Terraria.Player.RollLuck(), and Terraria.Main.tenthAnniversaryWorld.
Referenced by Terraria.GameContent.Creative.CreativePowers.ModifyRainPower.UpdateInfoFromSliderValueCache(), and Terraria.Main.UpdateTime().