Terraria Decompiled: Terraria.Main.DrawBackground_SurfaceTransitionBackground
DrawBackground_SurfaceTransitionBackground()
void Terraria.Main.DrawBackground_SurfaceTransitionBackground (float localShimmerAlpha, ref Vector2 drawOffset, ref Vector3 backgroundColor) inline private
Definition at line 54313 of file Main.cs.
        {
            int num = TextureAssets.Background[this._drawBackground_backTexture[0]].Width() - 32;
            this.bgParallax = (double)Main.caveParallax;
            this.bgStartX = (int)(-Math.IEEERemainder((double)num + (double)Main.screenPosition.X * this.bgParallax, (double)num) - (double)(num / 2)) - (int)drawOffset.X;
            this.bgLoops = (Main.screenWidth + (int)drawOffset.X * 2) / num + 2;
            this.bgTopY = (float)Main.worldSurface * 16f - 16f - Main.screenPosition.Y + 16f;
            float x = backgroundColor.X;
            float y = backgroundColor.Y;
            float z = backgroundColor.Z;
            for (int i = 0; i < this.bgLoops; i++)
            {
                for (int j = 0; j < num / 16; j++)
                {
                    int num2 = (int)((float)Math.Round((double)(-(double)((float)Math.IEEERemainder((double)((float)this.bgStartX + Main.screenPosition.X), 16.0)))));
                    if (num2 == -8)
                    {
                        num2 = 8;
                    }
                    float num3 = (float)(this.bgStartX + num * i + j * 16 + 8);
                    float num4 = this.bgTopY;
                    Microsoft.Xna.Framework.Color color = Lighting.GetColor((int)((num3 + Main.screenPosition.X) / 16f), (int)((Main.screenPosition.Y + num4) / 16f));
                    color.R = (byte)((float)color.R * x);
                    color.G = (byte)((float)color.G * y);
                    color.B = (byte)((float)color.B * z);
                    if (localShimmerAlpha > 0f)
                    {
                        color *= 1f - localShimmerAlpha;
                    }
                    Main.spriteBatch.Draw(TextureAssets.Background[this._drawBackground_backTexture[0]].Value, new Vector2((float)(this.bgStartX + num * i + 16 * j + num2), this.bgTopY) + drawOffset, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * j + num2 + 16, 0, 16, 16)), color);
                }
            }
            if (Main.ugBackTransition > 0f)
            {
                num = TextureAssets.Background[this._drawBackground_oldBackTexture[0]].Width() - 32;
                this.bgStartX = (int)(-Math.IEEERemainder((double)num + (double)Main.screenPosition.X * this.bgParallax, (double)num) - (double)(num / 2)) - (int)drawOffset.X;
                this.bgLoops = (Main.screenWidth + (int)drawOffset.X * 2) / num + 2;
                for (int k = 0; k < this.bgLoops; k++)
                {
                    for (int l = 0; l < num / 16; l++)
                    {
                        int num5 = (int)((float)Math.Round((double)(-(double)((float)Math.IEEERemainder((double)((float)this.bgStartX + Main.screenPosition.X), 16.0)))));
                        if (num5 == -8)
{
                            num5 = 8;
                        }
                        float num6 = (float)(this.bgStartX + num * k + l * 16 + 8);
                        float num7 = this.bgTopY;
                        Microsoft.Xna.Framework.Color color2 = Lighting.GetColor((int)((num6 + Main.screenPosition.X) / 16f), (int)((Main.screenPosition.Y + num7) / 16f));
                        color2.R = (byte)((float)color2.R * x);
                        color2.G = (byte)((float)color2.G * y);
                        color2.B = (byte)((float)color2.B * z);
                        Microsoft.Xna.Framework.Color color3 = color2;
                        color3.R = (byte)((float)color3.R * Main.ugBackTransition);
                        color3.G = (byte)((float)color3.G * Main.ugBackTransition);
                        color3.B = (byte)((float)color3.B * Main.ugBackTransition);
                        color3.A = (byte)((float)color3.A * Main.ugBackTransition);
                        Main.spriteBatch.Draw(TextureAssets.Background[this._drawBackground_oldBackTexture[0]].Value, new Vector2((float)(this.bgStartX + num * k + 16 * l + num5), this.bgTopY) + drawOffset, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * l + num5 + 16, 0, 16, 16)), color3);
                    }
                }
            }
        }
References Terraria.GameContent.TextureAssets.Background, Terraria.Main.caveParallax, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Lighting.GetColor(), System.Math.IEEERemainder(), int, System.Math.Round(), Terraria.Main.screenPosition, Terraria.Main.spriteBatch, Terraria.Main.ugBackTransition, ReLogic.Content.Asset< T >.Value, Terraria.Main.worldSurface, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.