Terraria Decompiled: Terraria.Main.DisplayAndGetFakeItem
DisplayAndGetFakeItem()
static Item Terraria.Main.DisplayAndGetFakeItem (ItemRarityColor color) inline static
Definition at line 18920 of file Main.cs.
        {
            Main._mouseTextFakeItem.SetDefaults(0, null);
            Main._mouseTextFakeItem.type = 1;
            Main._mouseTextFakeItem.scale = 0f;
            Main._mouseTextFakeItem.value = -1;
            Main._mouseTextFakeItem.rare = (int)color;
            Main.HoverItem = Main._mouseTextFakeItem;
            Main.instance.MouseText("", 0, 0, -1, -1, -1, -1, 0);
            Main.mouseText = true;
            return Main._mouseTextFakeItem;
        }
References Terraria.Main._mouseTextFakeItem, Terraria.Main.instance, int, Terraria.Main.MouseText(), and Terraria.Item.SetDefaults().
Referenced by Terraria.UI.AchievementAdvisor.DrawMouseHover(), Terraria.GameContent.UI.Elements.UIDebugCommandItem.DrawSelf(), and Terraria.GameContent.UI.States.UIWorldGenDebug.TooltipElement.DrawSelf().