Terraria Decompiled: Terraria.Main.rgbToHsl
rgbToHsl()
static Vector3 Terraria.Main.rgbToHsl (Microsoft::Xna::Framework::Color newColor) inline static
Definition at line 48299 of file Main.cs.
        {
            float num = (float)newColor.R;
            float num2 = (float)newColor.G;
            float num3 = (float)newColor.B;
            num /= 255f;
            num2 /= 255f;
            num3 /= 255f;
            float num4 = Math.Max(num, num2);
            num4 = Math.Max(num4, num3);
            float num5 = Math.Min(num, num2);
            num5 = Math.Min(num5, num3);
            float num6 = 0f;
            float num7 = (num4 + num5) / 2f;
            float num8;
            if (num4 == num5)
            {
                num8 = (num6 = 0f);
            }
            else
            {
                float num9 = num4 - num5;
                num8 = (((double)num7 > 0.5) ? (num9 / (2f - num4 - num5)) : (num9 / (num4 + num5)));
                if (num4 == num)
                {
                    num6 = (num2 - num3) / num9 + (float)((num2 < num3) ? 6 : 0);
                }
                if (num4 == num2)
                {
                    num6 = (num3 - num) / num9 + 2f;
                }
                if (num4 == num3)
                {
                    num6 = (num - num2) / num9 + 4f;
                }
                num6 /= 6f;
            }
            return new Vector3(num6, num8, num7);
        }
References System.Math.Max(), System.Math.Min(), and Microsoft.Xna.Framework.Graphics.Vector3.
Referenced by Terraria.Projectile.AI(), Terraria.Main.DrawClothesWindow(), Terraria.Graphics.Capture.CaptureInterface.ModeEdgeSelection.DrawCursors(), Terraria.Main.DrawHairWindow(), Terraria.PopupText.DrawItemTextPopups(), Terraria.Main.DrawMenu(), Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileVinesInWind(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_07_LeinforsHairShampoo(), Terraria.Main.DrawProjDirect(), Terraria.GameContent.Drawing.NextNatureRenderer.DrawWithLitNatureShader(), Terraria.Projectile.GetLastPrismHue(), Terraria.Player.HeroicisWingDust(), Terraria.GameContent.UI.States.UICharacterCreation.RgbToScaledHsl(), Terraria.DataStructures.ColorSlidersSet.SetHSL(), Terraria.Utils.ShiftHue(), Terraria.Player.WingFrame(), and Terraria.Player.Yoraiz0rEye().