Terraria Decompiled: Terraria.Main.DrawNPCDirect_Deerclops
DrawNPCDirect_Deerclops()
static void Terraria.Main.DrawNPCDirect_Deerclops (SpriteBatch mySpriteBatch, NPC rCurrentNPC, ref Vector2 screenPos, int typeCache, ref Microsoft::Xna::Framework::Color npcColor, ref Vector2 halfSize, SpriteEffects npcSpriteEffect) inline static private
Definition at line 25303 of file Main.cs.
        {
            Texture2D value = TextureAssets.Npc[typeCache].Value;
            Vector2 vector = rCurrentNPC.Bottom - screenPos;
            Microsoft.Xna.Framework.Rectangle rectangle = value.Frame(5, 5, rCurrentNPC.frame.Y / 5, rCurrentNPC.frame.Y % 5, 2, 2);
            Vector2 vector2 = rectangle.Size() * new Vector2(0.5f, 1f);
            vector2.Y -= 4f;
            int num = 106;
            if (rCurrentNPC.spriteDirection == 1)
            {
                vector2.X = (float)num;
            }
            else
            {
                vector2.X = (float)(rectangle.Width - num);
            }
            Microsoft.Xna.Framework.Color color = Microsoft.Xna.Framework.Color.White;
            float num2 = 0f;
            float num3 = 0f;
            int num4 = 0;
            float num5 = 0f;
            float num6 = 0f;
            float num7 = 10f;
            Microsoft.Xna.Framework.Color color2 = npcColor;
            if (rCurrentNPC.localAI[3] > 0f)
            {
                float num8 = 20f;
                float num9 = rCurrentNPC.localAI[3] / 36f;
                num4 = 2;
                num5 = num9 * num9;
                num6 = num8;
                color = new Microsoft.Xna.Framework.Color(80, 0, 0, 255) * 0.5f;
                num3 = 1f;
                color2 = Microsoft.Xna.Framework.Color.Lerp(Microsoft.Xna.Framework.Color.Transparent, color2, 1f - num9 * num9);
            }
            for (int i = 0; i < num4; i++)
            {
                Microsoft.Xna.Framework.Color color3 = npcColor;
                color3 = Microsoft.Xna.Framework.Color.Lerp(color3, color, num2);
                color3 = rCurrentNPC.GetAlpha(color3);
                color3 = Microsoft.Xna.Framework.Color.Lerp(color3, color, num3);
                color3 *= 1f - num5 * 0.5f;
                Vector2 vector3 = vector;
                mySpriteBatch.Draw(value, vector3 + new Vector2(0f, 1f).RotatedBy((double)((float)i * 6.2831855f / (float)num4 + Main.GlobalTimeWrappedHourly * num7), default(Vector2)) * num5 * num6, new Microsoft.Xna.Framework.Rectangle?(rectangle), color3, rCurrentNPC.rotation, vector2, rCurrentNPC.scale, npcSpriteEffect ^ SpriteEffects.FlipHorizontally, 0f);
            }
            Microsoft.Xna.Framework.Color color4 = rCurrentNPC.GetAlpha(color2);
            Microsoft.Xna.Framework.Color color5 = new Microsoft.Xna.Framework.Color(50, 0, 160);
            float num10 = 0f;
            if (rCurrentNPC.localAI[3] > 0f)
            {
                float num11 = Utils.Remap(rCurrentNPC.localAI[3], 0f, 20f, 0f, 1f, true);
                color4 = Microsoft.Xna.Framework.Color.Lerp(color4, color5, num11);
            }
            if (rCurrentNPC.ai[0] == 7f || rCurrentNPC.ai[0] == 8f)
            {
                num10 = Utils.Remap(rCurrentNPC.ai[1], 20f, 60f, 0f, 2f, true);
                if (num10 > 1f)
                {
                    num10 = 2f - num10;
                }
                color4 = Microsoft.Xna.Framework.Color.Lerp(color4, color5, num10);
                color4 *= 1f - num10;
                float num12 = 5f;
                int num13 = 0;
                while ((float)num13 < num12)
                {
                    Vector2 vector4 = vector;
                    float num14 = num10 * num10;
                    float num15 = 80f * num14;
                    float num16 = 80f * num14 + (float)(30 * num13) * num14;
                    Vector2 vector5 = Vector2.UnitX.RotatedBy((double)((float)num13 * 6.2831855f / num12 + Main.GlobalTimeWrappedHourly * 6f), default(Vector2)) * num15;
                    Vector2 vector6 = Vector2.UnitX.RotatedBy((double)((float)num13 * 6.2831855f / num12 + Main.GlobalTimeWrappedHourly * 3f * ((float)num13 * 0.5f)), default(Vector2)) * num16;
                    mySpriteBatch.Draw(value, vector4 + vector5 + vector6, new Microsoft.Xna.Framework.Rectangle?(rectangle), color4 * 0.5f, rCurrentNPC.rotation, vector2, rCurrentNPC.scale, npcSpriteEffect ^ SpriteEffects.FlipHorizontally, 0f);
                    num13++;
                }
            }
            mySpriteBatch.Draw(value, vector, new Microsoft.Xna.Framework.Rectangle?(rectangle), color4, rCurrentNPC.rotation, vector2, rCurrentNPC.scale, npcSpriteEffect ^ SpriteEffects.FlipHorizontally, 0f);
            if (rCurrentNPC.localAI[3] > 0f)
            {
                Texture2D value2 = TextureAssets.Extra[245].Value;
                float num17 = Utils.Remap(rCurrentNPC.localAI[3], 0f, 20f, 0f, 1f, true);
                Microsoft.Xna.Framework.Color color6 = new Microsoft.Xna.Framework.Color(255, 30, 30, 66) * rCurrentNPC.Opacity * num17 * 0.25f * (1f - num10);
                for (int j = 0; j < num4; j++)
                {
                    Vector2 vector7 = vector;
                    mySpriteBatch.Draw(value2, vector7 + new Vector2(0f, 1f).RotatedBy((double)((float)j * 6.2831855f / (float)num4 + Main.GlobalTimeWrappedHourly * num7), default(Vector2)) * num5 * 4f, new Microsoft.Xna.Framework.Rectangle?(rectangle), color6, rCurrentNPC.rotation, vector2, rCurrentNPC.scale, npcSpriteEffect ^ SpriteEffects.FlipHorizontally, 0f);
                }
            }
        }
References Terraria.NPC.ai, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.GameContent.TextureAssets.Extra, Terraria.NPC.frame, Terraria.NPC.GetAlpha(), Terraria.Main.GlobalTimeWrappedHourly, Microsoft.Xna.Framework.Color.Lerp(), Terraria.NPC.localAI, Terraria.GameContent.TextureAssets.Npc, Terraria.Utils.Remap(), Terraria.NPC.rotation, Terraria.NPC.scale, Terraria.NPC.spriteDirection, Microsoft.Xna.Framework.Color.Transparent, Microsoft.Xna.Framework.Vector2.UnitX, System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Rectangle.Width, and Microsoft.Xna.Framework.Rectangle.Y.
Referenced by Terraria.Main.DrawNPCDirect().