Terraria Decompiled: Terraria.Main.UpdateInvasion
UpdateInvasion()
static void Terraria.Main.UpdateInvasion () inline static private
Definition at line 65497 of file Main.cs.
        {
            if (Main.invasionType > 0)
            {
                if (Main.invasionSize <= 0)
                {
                    if (Main.invasionType == 1)
                    {
                        NPC.SetEventFlagCleared(ref NPC.downedGoblins, 0);
                        AchievementsHelper.NotifyProgressionEvent(10);
                    }
                    else if (Main.invasionType == 2)
                    {
                        NPC.SetEventFlagCleared(ref NPC.downedFrost, 1);
                        AchievementsHelper.NotifyProgressionEvent(12);
                    }
                    else if (Main.invasionType == 3)
                    {
                        NPC.SetEventFlagCleared(ref NPC.downedPirates, 2);
                        AchievementsHelper.NotifyProgressionEvent(11);
                    }
                    else if (Main.invasionType == 4)
                    {
                        NPC.SetEventFlagCleared(ref NPC.downedMartians, 3);
                        AchievementsHelper.NotifyProgressionEvent(13);
                    }
                    Main.InvasionWarning();
                    Main.invasionType = 0;
                    Main.invasionDelay = 0;
                    if (Main.netMode == 2)
                    {
                        NetMessage.SendData(7, -1, -1, null, 0, 0f, 0f, 0f, 0, 0, 0);
                    }
                }
                if (Main.invasionX != (double)Main.spawnTileX)
                {
                    float num = (float)Main.dayRate;
                    if (num < 1f)
                    {
                        num = 1f;
                    }
                    if (Main.invasionX > (double)Main.spawnTileX)
                    {
                        Main.invasionX -= (double)num;
                        if (Main.invasionX <= (double)Main.spawnTileX)
{
                            Main.invasionX = (double)Main.spawnTileX;
                            Main.InvasionWarning();
                        }
                        else if (num > 0f)
{
                            Main.invasionWarn--;
                        }
                    }
                    else if (Main.invasionX < (double)Main.spawnTileX)
                    {
                        Main.invasionX += (double)num;
                        if (Main.invasionX >= (double)Main.spawnTileX)
{
                            Main.invasionX = (double)Main.spawnTileX;
                            Main.InvasionWarning();
                        }
                        else if (num > 0f)
{
                            Main.invasionWarn--;
                        }
                    }
                    if (Main.invasionWarn <= 0)
                    {
                        Main.invasionWarn = 3600;
                        Main.InvasionWarning();
                    }
                }
            }
        }
References Terraria.Main.dayRate, Terraria.NPC.downedFrost, Terraria.NPC.downedGoblins, Terraria.NPC.downedMartians, Terraria.NPC.downedPirates, Terraria.Main.invasionSize, Terraria.Main.invasionType, Terraria.Main.invasionWarn, Terraria.Main.InvasionWarning(), Terraria.Main.invasionX, Terraria.Main.netMode, Terraria.GameContent.Achievements.AchievementsHelper.NotifyProgressionEvent(), Terraria.NetMessage.SendData(), Terraria.NPC.SetEventFlagCleared(), and Terraria.Main.spawnTileX.
Referenced by Terraria.Main.DoUpdateInWorld().