Terraria Decompiled: Terraria.Main.OpenPlayerSelect
OpenPlayerSelect()
static void Terraria.Main.OpenPlayerSelect (Action onPlayerSelected) inline static private
Definition at line 67821 of file Main.cs.
        {
            if (Main.gameMenu && (Main.menuMode == 10 || Main.menuMode == 14))
            {
                return;
            }
            if (WorldGen.isGeneratingOrLoadingWorld)
            {
                return;
            }
            if (!Main.gameMenu)
            {
                WorldGen.SaveAndQuit(delegate
                {
                    Main.OpenPlayerSelect(onPlayerSelected);
                });
                return;
            }
            Main.menuMode = 888;
            Main._blockFancyUIWhileLoading = true;
            Main.LoadPlayers();
            Main.MenuUI.SetState(Main._characterSelectMenu);
            Main._blockFancyUIWhileLoading = false;
            Main._pendingCharacterSelect = onPlayerSelected;
        }
References Terraria.Main._characterSelectMenu, Terraria.Main.gameMenu, Terraria.WorldGen.isGeneratingOrLoadingWorld, Terraria.Main.LoadPlayers(), Terraria.Main.menuMode, Terraria.Main.MenuUI, Terraria.Main.OpenPlayerSelect(), Terraria.WorldGen.SaveAndQuit(), and Terraria.UI.UserInterface.SetState().
Referenced by Terraria.Main.OpenPlayerSelect(), and Terraria.Main.OpenPlayerSelectFromNet().