Terraria Decompiled: Terraria.Main.DrawPaladinsShieldBoundary
DrawPaladinsShieldBoundary()
void Terraria.Main.DrawPaladinsShieldBoundary (Vector2 from, Vector2 to) inline private
Definition at line 57949 of file Main.cs.
        {
            float num = Vector2.Distance(from, to);
            float paladinsShieldRange = Player.PaladinsShieldRange;
            float num2 = Math.Abs(num - paladinsShieldRange);
            bool flag = num < paladinsShieldRange;
            float num3 = 1f;
            float num4 = Utils.Remap(num2, paladinsShieldRange * 0.15f, 0f, 0f, 1f, true);
            if (num4 <= 0f)
            {
                return;
            }
            float num5 = num4;
            float num6 = (to - from).ToRotation();
            Texture2D value = TextureAssets.Extra[98].Value;
            float num7 = 0.33f;
            Microsoft.Xna.Framework.Color ourFavoriteColor = Main.OurFavoriteColor;
            Microsoft.Xna.Framework.Color color = new Microsoft.Xna.Framework.Color(255, 255, 255, 255);
            float num8 = (flag ? 0.5f : 0.25f);
            for (float num9 = -0.01f; num9 <= 0.01f; num9 += 0.005f)
            {
                float num10 = num6 + 6.2831855f * num9 * 0.5f;
                Vector2 vector = from + num10.ToRotationVector2() * paladinsShieldRange;
                Microsoft.Xna.Framework.Color color2 = ourFavoriteColor;
                color2 *= num7;
                Main.EntitySpriteDraw(value, vector - Main.screenPosition, null, color2 * num4, num10, value.Size() / 2f, new Vector2(0.5f, 1.5f), SpriteEffects.None, 0f);
            }
            for (float num11 = -0.01f; num11 <= 0.01f; num11 += 0.005f)
            {
                float num12 = num6 + 6.2831855f * num11;
                Vector2 vector2 = from + num12.ToRotationVector2() * paladinsShieldRange;
                Main.EntitySpriteDraw(value, vector2 - Main.screenPosition, null, color * num4 * num7 * num8, num12, value.Size() / 2f, new Vector2(0.5f, 1.5f) * 0.5f, SpriteEffects.None, 0f);
            }
            Vector2 vector3 = new Vector2(1f, 1.5f);
            float num13 = 0f;
            Main.DrawPrettyStarSparkle(num3, SpriteEffects.None, to - Main.screenPosition, color * num3 * num8, ourFavoriteColor, num5, 0f, 1f, 1f, 2f, num13, vector3, Vector2.One);
            this.LoadItem(938);
            Asset<Texture2D> asset = TextureAssets.Item[938];
            if (!asset.IsLoaded)
            {
                return;
            }
            Microsoft.Xna.Framework.Color color3 = ourFavoriteColor;
            color3.A = 200;
            Vector2 vector4 = num6.ToRotationVector2() * Math.Min(paladinsShieldRange - num, 0f);
            Main.spriteBatch.Draw(asset.Value, to - Main.screenPosition + vector4, null, color3 * num5, 0f, asset.Size() / 2f, flag ? new Vector2(1.5f, 1.5f) : new Vector2(1f, 1f), SpriteEffects.None, 0f);
        }
References System.Math.Abs(), Microsoft.Xna.Framework.Vector2.Distance(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Main.DrawPrettyStarSparkle(), Terraria.Main.EntitySpriteDraw(), Terraria.GameContent.TextureAssets.Extra, ReLogic.Content.Asset< T >.IsLoaded, Terraria.GameContent.TextureAssets.Item, System.Math.Min(), Microsoft.Xna.Framework.Vector2.One, Terraria.Main.OurFavoriteColor, Terraria.Player.PaladinsShieldRange, Terraria.Utils.Remap(), Terraria.Main.screenPosition, Terraria.Main.spriteBatch, System.value, ReLogic.Content.Asset< T >.Value, and Microsoft.Xna.Framework.Graphics.Vector2.