Terraria Decompiled: Terraria.Main.GetPlayerControlledCameraPan
GetPlayerControlledCameraPan()
static bool Terraria.Main.GetPlayerControlledCameraPan (ref Vector2 targetPan, ref float maxPanSpeed) inline static private
Definition at line 63786 of file Main.cs.
        {
            if (Main.LocalPlayer.dead)
            {
                return false;
            }
            if ((Main.LocalPlayer.noThrow > 0 || Main.LocalPlayer.lastMouseInterface) && Main.CurrentPan == Vector2.Zero)
            {
                return false;
            }
            Item item = Main.LocalPlayer.inventory[Main.LocalPlayer.selectedItem];
            float num = -1f;
            bool flag = true;
            bool flag2 = true;
            if (Main.LocalPlayer.mount.Active && MountID.Sets.DontHoldItems[Main.LocalPlayer.mount.Type])
            {
                flag2 = false;
            }
            if (flag2)
            {
                if (Main.LocalPlayer.scope)
                {
                    num = 0.5f;
                }
                if (item.type == 1254)
                {
                    num = 0.6666667f;
                }
                if (item.type == 1254 && Main.LocalPlayer.scope)
                {
                    num = 0.8f;
                }
                if (item.type == 1299)
                {
                    num = 0.6666667f;
                    flag = false;
                }
            }
            if (num <= 0f)
            {
                return false;
            }
            float num2 = (float)Utils.Clamp<int>(Main.mouseX, 0, Main.screenWidth);
            int num3 = Utils.Clamp<int>(Main.mouseY, 0, Main.screenHeight);
            Vector2 vector = new Vector2(num2, (float)num3) / Main.Camera.UnscaledSize * 2f - Vector2.One;
            if (PlayerInput.UsingGamepad)
            {
                if (PlayerInput.GamepadThumbstickRight.Length() == 0f && Main.SmartCursorIsUsed)
                {
                    return false;
                }
                maxPanSpeed = 48f;
            }
            else if ((flag && !Main.mouseRight) || Main.LocalPlayer.selectedItem == 58)
            {
                return false;
            }
            targetPan = vector * Main.Camera.ScaledSize / 2f * num;
            return true;
        }
References Terraria.Mount.Active, Terraria.Utils.Clamp(), Terraria.Main.CurrentPan, Terraria.Player.dead, Terraria.ID.MountID.Sets.DontHoldItems, Terraria.GameInput.PlayerInput.GamepadThumbstickRight, Terraria.Player.inventory, System.item, Terraria.Player.lastMouseInterface, Microsoft.Xna.Framework.Vector2.Length(), Terraria.Main.LocalPlayer, Terraria.Player.mount, Terraria.Main.mouseRight, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Player.noThrow, Microsoft.Xna.Framework.Vector2.One, Terraria.Player.scope, Terraria.Main.screenHeight, Terraria.Main.screenWidth, Terraria.Player.selectedItem, Terraria.Main.SmartCursorIsUsed, Terraria.Mount.Type, Terraria.GameInput.PlayerInput.UsingGamepad, Microsoft.Xna.Framework.Graphics.Vector2, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.Main.UpdateCameraPan().