Terraria Decompiled: Terraria.Main.OpenLegacySettings
OpenLegacySettings()
void Terraria.Main.OpenLegacySettings () inline protected
Definition at line 2723 of file Main.cs.
        {
            try
            {
                if (File.Exists(Main.SavePath + Path.DirectorySeparatorChar.ToString() + "config.dat"))
                {
                    using (FileStream fileStream = new FileStream(Main.SavePath + Path.DirectorySeparatorChar.ToString() + "config.dat", FileMode.Open))
                    {
                        using (BinaryReader binaryReader = new BinaryReader(fileStream))
{
                            int num = binaryReader.ReadInt32();
                            if (num >= 68)
{
                                if (num >= 67)
{
                                    Main.clientUUID = binaryReader.ReadString();
                                }
                                bool flag = binaryReader.ReadBoolean();
                                Main.mouseColor.R = binaryReader.ReadByte();
                                Main.mouseColor.G = binaryReader.ReadByte();
                                Main.mouseColor.B = binaryReader.ReadByte();
                                Main.soundVolume = binaryReader.ReadSingle();
                                if (num >= 90)
{
                                    Main.ambientVolume = binaryReader.ReadSingle();
                                }
                                Main.musicVolume = binaryReader.ReadSingle();
                                Main.cUp = binaryReader.ReadString();
                                Main.cDown = binaryReader.ReadString();
                                Main.cLeft = binaryReader.ReadString();
                                Main.cRight = binaryReader.ReadString();
                                Main.cJump = binaryReader.ReadString();
                                Main.cThrowItem = binaryReader.ReadString();
                                if (num >= 1)
{
                                    Main.cInv = binaryReader.ReadString();
                                }
                                if (num >= 12)
{
                                    Main.cHeal = binaryReader.ReadString();
                                    Main.cMana = binaryReader.ReadString();
                                    Main.cBuff = binaryReader.ReadString();
                                }
                                if (num >= 13)
{
                                    Main.cHook = binaryReader.ReadString();
                                }
                                Main.caveParallax = binaryReader.ReadSingle();
                                if (num >= 2)
{
                                    binaryReader.ReadBoolean();
                                }
                                if (num >= 91 && binaryReader.ReadBoolean() && !Main.dedServ && Platform.IsWindows)
{
                                    Control.FromHandle(base.Window.Handle).WindowState = FormWindowState.Maximized;
                                }
                                if (num >= 4)
{
                                    int num2 = binaryReader.ReadInt32();
                                    int num3 = binaryReader.ReadInt32();
                                    Main.SetDisplayMode(num2, num3, flag);
                                }
                                if (num >= 8)
{
                                    Main.autoSave = binaryReader.ReadBoolean();
                                }
                                if (num >= 9)
{
                                    Main.autoPause = binaryReader.ReadBoolean();
                                }
                                if (num >= 19)
{
                                    Main.showItemText = binaryReader.ReadBoolean();
                                }
                                if (num >= 30)
{
                                    Main.cTorch = binaryReader.ReadString();
                                    Lighting.Mode = (LightMode)binaryReader.ReadByte();
                                    Main.qaStyle = (int)binaryReader.ReadByte();
                                }
                                if (num >= 37)
{
                                    Main.BackgroundEnabled = binaryReader.ReadBoolean();
                                }
                                if (num >= 39)
{
                                    byte b = binaryReader.ReadByte();
                                    Main._needsLanguageSelect = b == 0;
                                    LanguageManager.Instance.SetLanguage((int)b);
                                }
                                if (num >= 46)
{
                                    Main.mapEnabled = binaryReader.ReadBoolean();
                                    Main.cMapStyle = binaryReader.ReadString();
                                    Main.cMapFull = binaryReader.ReadString();
                                    Main.cMapZoomIn = binaryReader.ReadString();
                                    Main.cMapZoomOut = binaryReader.ReadString();
                                    Main.cMapAlphaUp = binaryReader.ReadString();
                                    Main.cMapAlphaDown = binaryReader.ReadString();
                                }
                                if (num >= 89)
{
                                    binaryReader.ReadInt32();
                                }
                                if (num >= 100)
{
                                    Main.cSmart = binaryReader.ReadString();
                                    Main.cSmartCursorModeIsToggleAndNotHold = binaryReader.ReadBoolean();
                                }
                                if (num >= 107)
{
                                    Main.invasionProgressMode = (int)binaryReader.ReadByte();
                                }
                                if (num >= 111)
{
                                    Main.placementPreview = binaryReader.ReadBoolean();
                                }
                                if (num >= 111)
{
                                    Main.placementPreview = binaryReader.ReadBoolean();
                                }
                                Main.SetFullScreen(flag);
                            }
                            binaryReader.Close();
                        }
                    }
                }
            }
            catch
            {
            }
        }
References System.IO.BinaryReader.Close(), System.IO.Path.DirectorySeparatorChar, System.IO.File.Exists(), Terraria.Control.FromHandle(), Terraria.Localization.LanguageManager.Instance, int, ReLogic.OS.Platform.IsWindows, System.IO.BinaryReader.ReadBoolean(), System.IO.BinaryReader.ReadByte(), System.IO.BinaryReader.ReadInt32(), System.IO.BinaryReader.ReadSingle(), System.IO.BinaryReader.ReadString(), Terraria.Main.SavePath, Terraria.Main.SetDisplayMode(), Terraria.Main.SetFullScreen(), and Terraria.Localization.LanguageManager.SetLanguage().
Referenced by Terraria.Main.LoadSettings().