Terraria Decompiled: Terraria.Main.DrawProj_Spear
DrawProj_Spear()
static void Terraria.Main.DrawProj_Spear (Projectile proj, Player theOwner, ref Microsoft::Xna::Framework::Color projectileColor, ref SpriteEffects dir) inline static private
Definition at line 34437 of file Main.cs.
        {
            dir = SpriteEffects.None;
            float num = (float)Math.Atan2((double)proj.velocity.Y, (double)proj.velocity.X) + 2.355f;
            Asset<Texture2D> asset = TextureAssets.Projectile[proj.type];
            Microsoft.Xna.Framework.Rectangle rectangle = asset.Frame(1, 1, 0, 0, 0, 0);
            Microsoft.Xna.Framework.Rectangle rect = proj.getRect();
            Vector2 zero = Vector2.Zero;
            if (theOwner.direction > 0)
            {
                dir = SpriteEffects.FlipHorizontally;
                zero.X = (float)asset.Width();
                num -= 1.5707964f;
            }
            if (theOwner.gravDir == -1f)
            {
                if (proj.direction == 1)
                {
                    dir = SpriteEffects.FlipHorizontally | SpriteEffects.FlipVertically;
                    zero = new Vector2((float)asset.Width(), (float)asset.Height());
                    num -= 1.5707964f;
                }
                else if (proj.direction == -1)
                {
                    dir = SpriteEffects.FlipVertically;
                    zero = new Vector2(0f, (float)asset.Height());
                    num += 1.5707964f;
                }
            }
            Vector2.Lerp(zero, rectangle.Center.ToVector2(), 0.25f);
            float num2 = 0f;
            Vector2 vector = proj.Center + new Vector2(0f, proj.gfxOffY);
            Microsoft.Xna.Framework.Rectangle rectangle2;
            if (!theOwner.isDisplayDollOrInanimate && proj.AI_019_Spears_GetExtensionHitbox(theOwner, out rectangle2))
            {
                Vector2 vector2 = theOwner.RotatedRelativePoint(theOwner.MountedCenter, false, true);
                float num3 = rectangle2.Size().Length() / proj.Hitbox.Size().Length();
                new Microsoft.Xna.Framework.Color(255, 255, 255, 0) * 1f;
                float num4 = Utils.Remap((float)theOwner.itemAnimation, (float)theOwner.itemAnimationMax, (float)theOwner.itemAnimationMax / 3f, 0f, 1f, true);
                float num5 = Utils.Remap(num4, 0f, 0.3f, 0f, 1f, true) * Utils.Remap(num4, 0.3f, 1f, 1f, 0f, true);
                num5 = 1f - (1f - num5) * (1f - num5);
                Vector2 vector3 = rectangle2.Center.ToVector2() + new Vector2(0f, proj.gfxOffY);
                Vector2.Lerp(vector2, vector3, 1.1f);
                Texture2D value = TextureAssets.Extra[98].Value;
                Vector2 vector4 = value.Size() / 2f;
                Microsoft.Xna.Framework.Color color = new Microsoft.Xna.Framework.Color(255, 255, 255, 0) * 0.5f;
                int type = proj.type;
                if (type <= 105)
                {
                    if (type != 46)
                    {
                        if (type == 105)
{
                            color = new Microsoft.Xna.Framework.Color(255, 220, 80, 0);
                        }
                    }
                    else
                    {
                        color = new Microsoft.Xna.Framework.Color(180, 80, 255, 0);
                    }
                }
                else if (type != 153)
                {
                    if (type == 342)
                    {
                        color = new Microsoft.Xna.Framework.Color(80, 140, 255, 0);
                    }
                }
                else
                {
                    color = new Microsoft.Xna.Framework.Color(255, 50, 30, 15);
                }
                float num6 = num - 0.7853982f * (float)proj.spriteDirection;
                if (theOwner.gravDir < 0f)
                {
                    num6 -= 1.5707964f * (float)proj.spriteDirection;
                }
                Main.EntitySpriteDraw(value, Vector2.Lerp(vector3, vector, 0.5f) - Main.screenPosition, null, color * num5, num6, vector4, new Vector2(num5 * num3, num3) * proj.scale * num3, dir, 0f);
                Main.EntitySpriteDraw(value, Vector2.Lerp(vector3, vector, 1f) - Main.screenPosition, null, color * num5, num6, vector4, new Vector2(num5 * num3, num3 * 1.5f) * proj.scale * num3, dir, 0f);
                Main.EntitySpriteDraw(value, Vector2.Lerp(vector2, vector, num4 * 1.5f - 0.5f) - Main.screenPosition + new Vector2(0f, 2f), null, color * num5, num6, vector4, new Vector2(num5 * num3 * 1f * num5, num3 * 2f * num5) * proj.scale * num3, dir, 0f);
                for (float num7 = 0.4f; num7 <= 1f; num7 += 0.1f)
                {
                    Vector2 vector5 = Vector2.Lerp(vector2, vector3, num7 + 0.2f);
                    Main.EntitySpriteDraw(value, vector5 - Main.screenPosition + new Vector2(0f, 2f), null, color * num5 * 0.75f * num7, num6, vector4, new Vector2(num5 * num3 * 1f * num5, num3 * 2f * num5) * proj.scale * num3, dir, 0f);
                }
                rectangle2.Offset((int)(-(int)Main.screenPosition.X), (int)(-(int)Main.screenPosition.Y));
            }
            Main.EntitySpriteDraw(asset.Value, vector - Main.screenPosition, new Microsoft.Xna.Framework.Rectangle?(rectangle), proj.GetAlpha(projectileColor), num, zero, proj.scale, dir, 0f);
            rect.Offset((int)(-(int)Main.screenPosition.X), (int)(-(int)Main.screenPosition.Y));
            Main.spriteBatch.Draw(TextureAssets.MagicPixel.Value, rect, Microsoft.Xna.Framework.Color.White * num2);
        }
References Terraria.Projectile.AI_019_Spears_GetExtensionHitbox(), System.Math.Atan2(), Microsoft.Xna.Framework.Rectangle.Center, Terraria.Entity.direction, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Main.EntitySpriteDraw(), Terraria.GameContent.TextureAssets.Extra, Terraria.Projectile.GetAlpha(), Terraria.Projectile.getRect(), Terraria.Projectile.gfxOffY, Terraria.Player.gravDir, Terraria.Entity.Hitbox, Terraria.Player.isDisplayDollOrInanimate, Terraria.Player.itemAnimation, Terraria.Player.itemAnimationMax, Microsoft.Xna.Framework.Vector2.Lerp(), Terraria.GameContent.TextureAssets.MagicPixel, Terraria.Player.MountedCenter, Microsoft.Xna.Framework.Rectangle.Offset(), Terraria.GameContent.TextureAssets.Projectile, Terraria.Utils.Remap(), Terraria.Player.RotatedRelativePoint(), Terraria.Projectile.scale, Terraria.Main.screenPosition, Terraria.Main.spriteBatch, Terraria.Projectile.spriteDirection, Terraria.Projectile.type, System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Entity.velocity, Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.Main.DrawProjDirect().