Terraria Decompiled: Terraria.Main.DrawWhip_MeteorWhip
DrawWhip_MeteorWhip()
static Vector2 Terraria.Main.DrawWhip_MeteorWhip (Projectile proj, List< Vector2 > controlPoints) inline static
Definition at line 35879 of file Main.cs.
        {
            int num = 6;
            Texture2D value = TextureAssets.Projectile[proj.type].Value;
            Microsoft.Xna.Framework.Rectangle rectangle = value.Frame(1, num, 0, 0, 0, 0);
            int height = rectangle.Height;
            rectangle.Height -= 2;
            Vector2 vector = rectangle.Size() / 2f;
            Vector2 vector2 = controlPoints[0];
            int num2 = 1;
            int num3 = (int)MathHelper.Max(1f, (float)(num - 2));
            int num4 = controlPoints.Count - 1;
            for (int i = 0; i < num4; i++)
            {
                bool flag = true;
                Vector2 vector3 = vector;
                if (i == 0)
                {
                    rectangle.Y = 0;
                }
                else if (i == num4 - 1)
                {
                    rectangle.Y = height * (num - 1);
                }
                else
                {
                    float num5 = ((float)i - 1f) / ((float)num4 - 2f);
                    int num6 = (int)Math.Round((double)MathHelper.Lerp((float)num2, (float)num3, num5));
                    rectangle.Y = height * num6;
                    if (i % 3 != 0)
                    {
                        flag = false;
                    }
                }
                Vector2 vector4 = controlPoints[i];
                Vector2 vector5 = controlPoints[i + 1] - vector4;
                if (flag)
                {
                    float num7 = vector5.ToRotation() - 1.5707964f;
                    Microsoft.Xna.Framework.Color color = new Microsoft.Xna.Framework.Color(255, 255, 255, 255);
                    Main.spriteBatch.Draw(value, vector2 - Main.screenPosition, new Microsoft.Xna.Framework.Rectangle?(rectangle), color, num7, vector3, 1f, SpriteEffects.None, 0f);
                }
                vector2 += vector5;
            }
            return vector2;
        }
References Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Rectangle.Height, int, Microsoft.Xna.Framework.MathHelper.Lerp(), Microsoft.Xna.Framework.MathHelper.Max(), Terraria.GameContent.TextureAssets.Projectile, System.Math.Round(), Terraria.Main.screenPosition, Terraria.Main.spriteBatch, Terraria.Projectile.type, System.value, and ReLogic.Content.Asset< T >.Value.
Referenced by Terraria.Main.DrawWhip().