Terraria Decompiled: Terraria.Main.OpenClothesWindow
OpenClothesWindow()
static void Terraria.Main.OpenClothesWindow () inline static
Definition at line 44208 of file Main.cs.
        {
            if (Main.clothesWindow)
            {
                Main.CancelClothesWindow(false);
                return;
            }
            Main.hBar = -1f;
            Main.lBar = -1f;
            Main.sBar = -1f;
            IngameUIWindows.CloseAll(true);
            Main.clothesWindow = true;
            SoundEngine.PlaySound(10, -1, -1, 1, 1f, 0f);
            Main.selClothes = 0;
            Main.oldClothesColor[0] = Main.player[Main.myPlayer].shirtColor;
            Main.oldClothesColor[1] = Main.player[Main.myPlayer].underShirtColor;
            Main.oldClothesColor[2] = Main.player[Main.myPlayer].pantsColor;
            Main.oldClothesColor[3] = Main.player[Main.myPlayer].shoeColor;
            Main.oldClothesColor[4] = Main.player[Main.myPlayer].eyeColor;
            Main.oldClothesColor[5] = Main.player[Main.myPlayer].skinColor;
            if (Main.dresserInterfaceDummy == null)
            {
                Main.dresserInterfaceDummy = new Player();
            }
            Main.oldClothesStyle = Main.player[Main.myPlayer].skinVariant;
            Main.oldVoiceStyle = Main.player[Main.myPlayer].voiceVariant;
            Main.oldVoicePitch = Main.player[Main.myPlayer].voicePitchOffset;
        }
References Terraria.Main.CancelClothesWindow(), Terraria.UI.IngameUIWindows.CloseAll(), Terraria.Main.clothesWindow, Terraria.Main.dresserInterfaceDummy, Terraria.Player.eyeColor, Terraria.Main.myPlayer, Terraria.Main.oldClothesColor, Terraria.Player.pantsColor, Terraria.Enums.Player, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Player.shirtColor, Terraria.Player.shoeColor, Terraria.Player.skinColor, Terraria.Player.skinVariant, Terraria.Player.underShirtColor, Terraria.Player.voicePitchOffset, and Terraria.Player.voiceVariant.
Referenced by Terraria.Player.TileInteractionsUse().