Terraria Decompiled: Terraria.Main.HostAndPlay
HostAndPlay()
static void Terraria.Main.HostAndPlay () inline static package
Definition at line 52504 of file Main.cs.
        {
            string text = string.Concat(new object[]
            {
                "-autoshutdown -password \"",
                Main.ConvertToSafeArgument(Netplay.ServerPassword),
                "\" -lang ",
                Language.ActiveCulture.LegacyId
            });
            if (Platform.IsLinux)
            {
                if (IntPtr.Size == 8)
                {
                    text += " -x64";
                }
                else
                {
                    text += " -x86";
                }
            }
            if (Main.ActiveWorldFileData.IsCloudSave)
            {
                text += Main.SanitizePathArgument("cloudworld", Main.worldPathName);
            }
            else
            {
                text += Main.SanitizePathArgument("world", Main.worldPathName);
            }
            text = text + " -worldrollbackstokeep " + Main.WorldRollingBackupsCountToKeep;
            Netplay.HostToken = Main.NewToken();
            text = text + " -hosttoken " + Netplay.HostToken;
            Main.tServer = new Process();
            if (Platform.IsLinux)
            {
                Main.tServer.StartInfo.FileName = "TerrariaServer";
            }
            else if (Platform.IsOSX)
            {
                Main.tServer.StartInfo.FileName = "../MacOS/TerrariaServer";
            }
            else
            {
                Main.tServer.StartInfo.FileName = "TerrariaServer.exe";
            }
            Main.tServer.StartInfo.Arguments = text;
            if (Main.libPath != "")
            {
                ProcessStartInfo startInfo = Main.tServer.StartInfo;
                startInfo.Arguments = startInfo.Arguments + " -loadlib " + Main.libPath;
            }
            Main.tServer.StartInfo.UseShellExecute = false;
            Main.tServer.StartInfo.CreateNoWindow = true;
            if (SocialAPI.Network != null)
            {
                SocialAPI.Network.LaunchLocalServer(Main.tServer, Main.MenuServerMode);
            }
            else
            {
                Main.tServer.Start();
            }
            Netplay.SetRemoteIP("127.0.0.1");
            Netplay.ListenPort = 7777;
            Netplay.IsHostAndPlay = true;
            Main.autoPass = true;
            Main.statusText = Lang.menu[8].Value;
            Netplay.StartTcpClient();
            Main.menuMode = 10;
        }
References Terraria.Localization.Language.ActiveCulture, Terraria.Main.ActiveWorldFileData, Terraria.Main.ConvertToSafeArgument(), Terraria.Netplay.HostToken, Terraria.IO.FileData.IsCloudSave, ReLogic.OS.Platform.IsLinux, ReLogic.OS.Platform.IsOSX, Terraria.Localization.GameCulture.LegacyId, Terraria.Main.libPath, Terraria.Lang.menu, Terraria.Main.MenuServerMode, Terraria.Social.SocialAPI.Network, Terraria.Main.NewToken(), System.Process, Terraria.Main.SanitizePathArgument(), Terraria.Netplay.ServerPassword, Terraria.Netplay.SetRemoteIP(), System.IntPtr.Size, Terraria.Netplay.StartTcpClient(), System.text, Terraria.Main.tServer, Terraria.Localization.LocalizedText.Value, Terraria.Main.worldPathName, and Terraria.Main.WorldRollingBackupsCountToKeep.
Referenced by Terraria.Main.DrawMenu(), Terraria.Main.OnSubmitServerPassword(), and Terraria.Testing.QuickLoad.JoinWorld.PlayWorldOrJoinServer().