Terraria Decompiled: Terraria.Main.DrawSurfaceBG_Corrupt
DrawSurfaceBG_Corrupt()
void Terraria.Main.DrawSurfaceBG_Corrupt (float backgroundTopMagicNumber, float bgGlobalScaleMultiplier, int pushBGTopHack, int[] bgTexIndexes) inline private
Definition at line 62029 of file Main.cs.
        {
            Main.bgScale = 1.25f;
            this.bgParallax = 0.4;
            this.bgTopY = backgroundTopMagicNumber * 1800f + 1500f + this.scAdj + (float)pushBGTopHack;
            this.SetBackgroundOffsets(bgTexIndexes[0], backgroundTopMagicNumber, pushBGTopHack);
            Main.bgScale *= bgGlobalScaleMultiplier;
            this.LoadBackground(bgTexIndexes[0]);
            if (Main.backgroundWidth[bgTexIndexes[0]] == 0 || Main.backgroundHeight[bgTexIndexes[0]] == 0)
            {
                return;
            }
            Main.bgWidthScaled = (int)((float)Main.backgroundWidth[bgTexIndexes[0]] * Main.bgScale);
            SkyManager.Instance.DrawToDepth(Main.spriteBatch, 1f / (float)this.bgParallax);
            this.bgStartX = (int)(-Math.IEEERemainder((double)Main.screenPosition.X * this.bgParallax, (double)Main.bgWidthScaled) - (double)(Main.bgWidthScaled / 2));
            if (Main.gameMenu)
            {
                this.bgTopY = (float)(320 + pushBGTopHack);
            }
            if (bgTexIndexes[0] == 56)
            {
                this.bgTopY -= 100f;
            }
            this.bgLoops = Main.screenWidth / Main.bgWidthScaled + 2;
            if ((double)Main.screenPosition.Y < Main.worldSurface * 16.0 + 16.0)
            {
                for (int i = 0; i < this.bgLoops; i++)
                {
                    Main.spriteBatch.Draw(TextureAssets.Background[bgTexIndexes[0]].Value, new Vector2((float)(this.bgStartX + Main.bgWidthScaled * i), this.bgTopY), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, Main.backgroundWidth[bgTexIndexes[0]], Main.backgroundHeight[bgTexIndexes[0]])), Main.ColorOfSurfaceBackgroundsModified, 0f, default(Vector2), Main.bgScale, SpriteEffects.None, 0f);
                }
            }
            Main.bgScale = 1.31f;
            this.bgParallax = 0.43;
            this.bgTopY = backgroundTopMagicNumber * 1950f + 1750f + this.scAdj + (float)pushBGTopHack;
            this.SetBackgroundOffsets(bgTexIndexes[1], backgroundTopMagicNumber, pushBGTopHack);
            Main.bgScale *= bgGlobalScaleMultiplier;
            this.LoadBackground(bgTexIndexes[1]);
            Main.bgWidthScaled = (int)((float)Main.backgroundWidth[bgTexIndexes[1]] * Main.bgScale);
            SkyManager.Instance.DrawToDepth(Main.spriteBatch, 1f / (float)this.bgParallax);
            this.bgStartX = (int)(-Math.IEEERemainder((double)Main.screenPosition.X * this.bgParallax, (double)Main.bgWidthScaled) - (double)(Main.bgWidthScaled / 2));
            if (Main.gameMenu)
            {
                this.bgTopY = (float)(400 + pushBGTopHack);
                this.bgStartX -= 80;
            }
            if (bgTexIndexes[0] == 56)
            {
                this.bgTopY -= 100f;
            }
            if (Main.bgWidthScaled == 0)
            {
                Main.bgWidthScaled = 1;
            }
            this.bgLoops = Main.screenWidth / Main.bgWidthScaled + 2;
            if ((double)Main.screenPosition.Y < Main.worldSurface * 16.0 + 16.0)
            {
                try
                {
                    Texture2D value = TextureAssets.Background[bgTexIndexes[1]].Value;
                    if (value != null)
                    {
                        for (int j = 0; j < this.bgLoops; j++)
{
                            Main.spriteBatch.Draw(value, new Vector2((float)(this.bgStartX + Main.bgWidthScaled * j), this.bgTopY), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, Main.backgroundWidth[bgTexIndexes[1]], Main.backgroundHeight[bgTexIndexes[1]])), Main.ColorOfSurfaceBackgroundsModified, 0f, default(Vector2), Main.bgScale, SpriteEffects.FlipHorizontally, 0f);
                        }
                    }
                }
                catch
                {
                    this.LoadBackground(bgTexIndexes[1]);
                }
            }
            Main.bgScale = 1.34f;
            this.bgParallax = 0.49;
            this.bgTopY = backgroundTopMagicNumber * 2100f + 2000f + this.scAdj + (float)pushBGTopHack;
            this.SetBackgroundOffsets(bgTexIndexes[2], backgroundTopMagicNumber, pushBGTopHack);
            Main.bgScale *= bgGlobalScaleMultiplier;
            this.LoadBackground(bgTexIndexes[2]);
            Main.bgWidthScaled = (int)((float)Main.backgroundWidth[bgTexIndexes[2]] * Main.bgScale);
            if (Main.bgWidthScaled == 0)
            {
                Main.bgWidthScaled = 150;
            }
            SkyManager.Instance.DrawToDepth(Main.spriteBatch, 1f / (float)this.bgParallax);
            this.bgStartX = (int)(-Math.IEEERemainder((double)Main.screenPosition.X * this.bgParallax, (double)Main.bgWidthScaled) - (double)(Main.bgWidthScaled / 2));
            if (Main.gameMenu)
            {
                this.bgTopY = (float)(480 + pushBGTopHack);
                this.bgStartX -= 120;
            }
            if (bgTexIndexes[0] == 56)
            {
                this.bgTopY -= 100f;
            }
            this.bgLoops = Main.screenWidth / Main.bgWidthScaled + 2;
            try
            {
                if ((double)Main.screenPosition.Y < Main.worldSurface * 16.0 + 16.0)
                {
                    for (int k = 0; k < this.bgLoops; k++)
                    {
                        Main.spriteBatch.Draw(TextureAssets.Background[bgTexIndexes[2]].Value, new Vector2((float)(this.bgStartX + Main.bgWidthScaled * k), this.bgTopY), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, Main.backgroundWidth[bgTexIndexes[2]], Main.backgroundHeight[bgTexIndexes[2]])), Main.ColorOfSurfaceBackgroundsModified, 0f, default(Vector2), Main.bgScale, SpriteEffects.None, 0f);
                    }
                }
            }
            catch
            {
                this.LoadBackground(bgTexIndexes[2]);
            }
        }
References Terraria.GameContent.TextureAssets.Background, Terraria.Main.backgroundHeight, Terraria.Main.backgroundWidth, Terraria.Main.bgScale, Terraria.Main.bgWidthScaled, Terraria.Main.ColorOfSurfaceBackgroundsModified, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Graphics.Effects.SkyManager.DrawToDepth(), Terraria.Main.gameMenu, System.Math.IEEERemainder(), Terraria.Graphics.Effects.SkyManager.Instance, int, Terraria.Main.spriteBatch, System.value, ReLogic.Content.Asset< T >.Value, and Microsoft.Xna.Framework.Graphics.Vector2.