Terraria Decompiled: Terraria.Main.TrySyncingMyPlayer
TrySyncingMyPlayer()
static void Terraria.Main.TrySyncingMyPlayer () inline static private
Definition at line 16049 of file Main.cs.
        {
            Player player = Main.clientPlayer;
            bool flag = false;
            for (int i = 0; i < 59; i++)
            {
                if (Main.player[Main.myPlayer].inventory[i].IsNetStateDifferent(player.inventory[i]))
                {
                    flag = true;
                    NetMessage.SendData(5, -1, -1, null, Main.myPlayer, (float)(PlayerItemSlotID.Inventory0 + i), 0f, 0f, 0, 0, 0);
                }
            }
            Main.TrySyncingItemArray(ref flag, Main.player[Main.myPlayer].armor, player.armor, PlayerItemSlotID.Armor0);
            Main.TrySyncingItemArray(ref flag, Main.player[Main.myPlayer].dye, player.dye, PlayerItemSlotID.Dye0);
            Main.TrySyncingItemArray(ref flag, Main.player[Main.myPlayer].miscEquips, player.miscEquips, PlayerItemSlotID.Misc0);
            Main.TrySyncingItemArray(ref flag, Main.player[Main.myPlayer].miscDyes, player.miscDyes, PlayerItemSlotID.MiscDye0);
            Main.TrySyncingItemArray(ref flag, Main.player[Main.myPlayer].bank.item, player.bank.item, PlayerItemSlotID.Bank1_0);
            Main.TrySyncingItemArray(ref flag, Main.player[Main.myPlayer].bank2.item, player.bank2.item, PlayerItemSlotID.Bank2_0);
            if (Main.player[Main.myPlayer].trashItem.IsNetStateDifferent(player.trashItem))
            {
                flag = true;
                NetMessage.SendData(5, -1, -1, null, Main.myPlayer, (float)PlayerItemSlotID.TrashItem, 0f, 0f, 0, 0, 0);
            }
            Main.TrySyncingItemArray(ref flag, Main.player[Main.myPlayer].bank3.item, player.bank3.item, PlayerItemSlotID.Bank3_0);
            Main.TrySyncingItemArray(ref flag, Main.player[Main.myPlayer].bank4.item, player.bank4.item, PlayerItemSlotID.Bank4_0);
            Main.TrySyncingItemArray(ref flag, Main.player[Main.myPlayer].Loadouts[0].Armor, player.Loadouts[0].Armor, PlayerItemSlotID.Loadout1_Armor_0);
            Main.TrySyncingItemArray(ref flag, Main.player[Main.myPlayer].Loadouts[0].Dye, player.Loadouts[0].Dye, PlayerItemSlotID.Loadout1_Dye_0);
            Main.TrySyncingItemArray(ref flag, Main.player[Main.myPlayer].Loadouts[1].Armor, player.Loadouts[1].Armor, PlayerItemSlotID.Loadout2_Armor_0);
            Main.TrySyncingItemArray(ref flag, Main.player[Main.myPlayer].Loadouts[1].Dye, player.Loadouts[1].Dye, PlayerItemSlotID.Loadout2_Dye_0);
            Main.TrySyncingItemArray(ref flag, Main.player[Main.myPlayer].Loadouts[2].Armor, player.Loadouts[2].Armor, PlayerItemSlotID.Loadout3_Armor_0);
            Main.TrySyncingItemArray(ref flag, Main.player[Main.myPlayer].Loadouts[2].Dye, player.Loadouts[2].Dye, PlayerItemSlotID.Loadout3_Dye_0);
            if (Main.player[Main.myPlayer].chest != player.chest && Main.player[Main.myPlayer].chest < 0 && player.chest >= 0)
            {
                if (Main.player[Main.myPlayer].editedChestName)
                {
                    if (Main.chest[player.chest] != null)
                    {
                        NetMessage.SendData(33, -1, -1, NetworkText.FromLiteral(Main.chest[player.chest].name), Main.player[Main.myPlayer].chest, 1f, 0f, 0f, 0, 0, 0);
                    }
                    else
                    {
                        NetMessage.SendData(33, -1, -1, null, Main.player[Main.myPlayer].chest, 0f, 0f, 0f, 0, 0, 0);
                    }
                    Main.player[Main.myPlayer].editedChestName = false;
                }
                else
                {
                    NetMessage.SendData(33, -1, -1, null, Main.player[Main.myPlayer].chest, 0f, 0f, 0f, 0, 0, 0);
                }
            }
            if (Main.player[Main.myPlayer].talkNPC != player.talkNPC)
            {
                NetMessage.SendData(40, -1, -1, null, Main.myPlayer, 0f, 0f, 0f, 0, 0, 0);
            }
            if (false | (Main.player[Main.myPlayer].voidLensChest != player.voidLensChest) | (Main.player[Main.myPlayer].piggyBankProjTracker != player.piggyBankProjTracker))
            {
                NetMessage.SendData(142, -1, -1, null, Main.myPlayer, 0f, 0f, 0f, 0, 0, 0);
            }
            if (Main.LocalPlayer.tileEntityAnchor.interactEntityID != player.tileEntityAnchor.interactEntityID && Main.LocalPlayer.tileEntityAnchor.interactEntityID < 0)
            {
                NetMessage.SendData(122, -1, -1, null, -1, (float)Main.myPlayer, 0f, 0f, 0, 0, 0);
            }
            bool flag2 = false;
            if (Main.player[Main.myPlayer].zone1 != player.zone1)
            {
                flag2 = true;
            }
            if (Main.player[Main.myPlayer].zone2 != player.zone2)
            {
                flag2 = true;
            }
            if (Main.player[Main.myPlayer].zone3 != player.zone3)
            {
                flag2 = true;
            }
            if (Main.player[Main.myPlayer].zone4 != player.zone4)
            {
                flag2 = true;
            }
            if (Main.player[Main.myPlayer].zone5 != player.zone5)
            {
                flag2 = true;
            }
            if (Main.player[Main.myPlayer].townNPCs != player.townNPCs)
            {
                flag2 = true;
            }
            if (flag2)
            {
                NetMessage.SendData(36, -1, -1, null, Main.myPlayer, 0f, 0f, 0f, 0, 0, 0);
            }
            if (Main.player[Main.myPlayer].statLife != player.statLife || Main.player[Main.myPlayer].statLifeMax != player.statLifeMax)
            {
                Main.player[Main.myPlayer].netLife = true;
            }
            if (Main.player[Main.myPlayer].netLifeTime > 0)
            {
                Main.player[Main.myPlayer].netLifeTime--;
            }
            else if (Main.player[Main.myPlayer].netLife)
            {
                Main.player[Main.myPlayer].netLife = false;
                Main.player[Main.myPlayer].netLifeTime = 60;
                NetMessage.SendData(16, -1, -1, null, Main.myPlayer, 0f, 0f, 0f, 0, 0, 0);
            }
            if (Main.player[Main.myPlayer].statMana != player.statMana || Main.player[Main.myPlayer].statManaMax != player.statManaMax)
            {
                Main.player[Main.myPlayer].netMana = true;
            }
            if (Main.player[Main.myPlayer].netManaTime > 0)
            {
                Main.player[Main.myPlayer].netManaTime--;
            }
            else if (Main.player[Main.myPlayer].netMana)
            {
                Main.player[Main.myPlayer].netMana = false;
                Main.player[Main.myPlayer].netManaTime = 60;
                NetMessage.SendData(42, -1, -1, null, Main.myPlayer, 0f, 0f, 0f, 0, 0, 0);
            }
            bool flag3 = false;
            for (int j = 0; j < Player.maxBuffs; j++)
            {
                if (Main.player[Main.myPlayer].buffType[j] != player.buffType[j])
                {
                    flag3 = true;
                    break;
                }
            }
            if (flag3)
            {
                NetMessage.SendData(50, -1, -1, null, Main.myPlayer, 0f, 0f, 0f, 0, 0, 0);
                NetMessage.SendData(13, -1, -1, null, Main.myPlayer, 0f, 0f, 0f, 0, 0, 0);
            }
            bool flag4 = false;
            if (Main.player[Main.myPlayer].MinionRestTargetPoint != player.MinionRestTargetPoint)
            {
                flag4 = true;
            }
            if (flag4)
            {
                NetMessage.SendData(99, -1, -1, null, Main.myPlayer, 0f, 0f, 0f, 0, 0, 0);
            }
            bool flag5 = false;
            if (Main.player[Main.myPlayer].MinionAttackTargetNPC != player.MinionAttackTargetNPC)
            {
                flag5 = true;
            }
            if (flag5)
            {
                NetMessage.SendData(115, -1, -1, null, Main.myPlayer, 0f, 0f, 0f, 0, 0, 0);
            }
            if (player.shieldRaised != Main.player[Main.myPlayer].shieldRaised)
            {
                NetMessage.SendData(13, -1, -1, null, Main.myPlayer, 0f, 0f, 0f, 0, 0, 0);
            }
            if (flag)
            {
                NetMessage.SendData(138, -1, -1, null, 0, 0f, 0f, 0f, 0, 0, 0);
            }
            Main.player[Main.myPlayer].clientClone(Main.clientPlayer);
        }
References Terraria.EquipmentLoadout.Armor, Terraria.Player.armor, Terraria.ID.PlayerItemSlotID.Armor0, Terraria.Player.bank, Terraria.ID.PlayerItemSlotID.Bank1_0, Terraria.Player.bank2, Terraria.ID.PlayerItemSlotID.Bank2_0, Terraria.Player.bank3, Terraria.ID.PlayerItemSlotID.Bank3_0, Terraria.Player.bank4, Terraria.ID.PlayerItemSlotID.Bank4_0, Terraria.Player.buffType, Terraria.Main.chest, Terraria.Player.chest, Terraria.Player.clientClone(), Terraria.Main.clientPlayer, Terraria.EquipmentLoadout.Dye, Terraria.Player.dye, Terraria.ID.PlayerItemSlotID.Dye0, Terraria.Player.editedChestName, Terraria.Localization.NetworkText.FromLiteral(), Terraria.DataStructures.PlayerInteractionAnchor.interactEntityID, Terraria.Player.inventory, Terraria.ID.PlayerItemSlotID.Inventory0, Terraria.Item.IsNetStateDifferent(), Terraria.Chest.item, Terraria.ID.PlayerItemSlotID.Loadout1_Armor_0, Terraria.ID.PlayerItemSlotID.Loadout1_Dye_0, Terraria.ID.PlayerItemSlotID.Loadout2_Armor_0, Terraria.ID.PlayerItemSlotID.Loadout2_Dye_0, Terraria.ID.PlayerItemSlotID.Loadout3_Armor_0, Terraria.ID.PlayerItemSlotID.Loadout3_Dye_0, Terraria.Player.Loadouts, Terraria.Main.LocalPlayer, Terraria.Player.maxBuffs, Terraria.Player.MinionAttackTargetNPC, Terraria.Player.MinionRestTargetPoint, Terraria.ID.PlayerItemSlotID.Misc0, Terraria.ID.PlayerItemSlotID.MiscDye0, Terraria.Player.miscDyes, Terraria.Player.miscEquips, Terraria.Main.myPlayer, Terraria.Chest.name, Terraria.Player.netLife, Terraria.Player.netLifeTime, Terraria.Player.netMana, Terraria.Player.netManaTime, Terraria.Player.piggyBankProjTracker, Terraria.Main.player, Terraria.NetMessage.SendData(), Terraria.Player.shieldRaised, Terraria.Player.statLife, Terraria.Player.statLifeMax, Terraria.Player.statMana, Terraria.Player.statManaMax, Terraria.Player.talkNPC, Terraria.Player.tileEntityAnchor, Terraria.Player.townNPCs, Terraria.ID.PlayerItemSlotID.TrashItem, Terraria.Player.trashItem, Terraria.Main.TrySyncingItemArray(), Terraria.Player.voidLensChest, Terraria.Player.zone1, Terraria.Player.zone2, Terraria.Player.zone3, Terraria.Player.zone4, and Terraria.Player.zone5.
Referenced by Terraria.Main.DoUpdate().