Terraria Decompiled: Terraria.Main.DrawInterface_32_GamepadRadialHotbars
DrawInterface_32_GamepadRadialHotbars()
static void Terraria.Main.DrawInterface_32_GamepadRadialHotbars () inline static private
Definition at line 45628 of file Main.cs.
        {
            ItemSlot.DrawRadialCircular(Main.spriteBatch, new Vector2((float)Main.screenWidth, (float)Main.screenHeight) / 2f, Main.LocalPlayer.CircularRadial, Main.LocalPlayer.inventory);
            ItemSlot.DrawRadialQuicks(Main.spriteBatch, new Vector2((float)Main.screenWidth, (float)Main.screenHeight) / 2f);
        }
References Terraria.Player.CircularRadial, Terraria.UI.ItemSlot.DrawRadialCircular(), Terraria.UI.ItemSlot.DrawRadialQuicks(), Terraria.Player.inventory, Terraria.Main.LocalPlayer, Terraria.Main.screenHeight, Terraria.Main.screenWidth, and Terraria.Main.spriteBatch.
Referenced by Terraria.Main.SetupDrawInterfaceLayers().