Terraria Decompiled: Terraria.Main.Initialize_AlmostEverything
Initialize_AlmostEverything()
void Terraria.Main.Initialize_AlmostEverything () inline private
Definition at line 4643 of file Main.cs.
        {
            this.TilePaintSystem = new TilePaintSystemV2();
            this.TilesRenderer = new TileDrawing(this.TilePaintSystem);
            this.WallsRenderer = new WallDrawing(this.TilePaintSystem);
            CreativePowerManager.Initialize();
            Main.LocalFavoriteData.Load();
            Main.CloudFavoritesData.Load();
            this.Initialize_Entities();
            Main.FindAnnouncementBoxStatus();
            CustomCurrencyManager.Initialize();
            WingStatsInitializer.Load();
            TileObjectData.Initialize();
            Animation.Initialize();
            Chest.Initialize();
            Wiring.Initialize();
            Framing.Initialize();
            ItemRarity.Initialize();
            TileEntity.InitializeAll();
            Projectile.InitializeStaticThings();
            TorchID.Initialize();
            LeashedEntity.Registry.RegisterAll();
            NPCInteractions.Initialize();
            Main.InitializeItemAnimations();
            BestiaryDatabase bestiaryDatabase = new BestiaryDatabase();
            BestiaryDatabaseNPCsPopulator bestiaryDatabaseNPCsPopulator = new BestiaryDatabaseNPCsPopulator();
            bestiaryDatabaseNPCsPopulator.Populate(bestiaryDatabase);
            Main.BestiaryDB = bestiaryDatabase;
            ContentSamples.RebuildBestiarySortingIDsByBestiaryDatabaseContents(bestiaryDatabase);
            Main.BestiaryTracker = new BestiaryUnlocksTracker();
            ItemDropDatabase itemDropDatabase = new ItemDropDatabase();
            itemDropDatabase.Populate();
            Main.ItemDropsDB = itemDropDatabase;
            bestiaryDatabase.Merge(Main.ItemDropsDB);
            bestiaryDatabaseNPCsPopulator.AddDropOverrides(bestiaryDatabase);
            FishDropRuleList fishDropRuleList = new FishDropRuleList();
            new GameContentFishDropPopulator(fishDropRuleList).Populate();
            Main.FishDropsDB = fishDropRuleList;
            Main.PylonSystem = new TeleportPylonsSystem();
            Main.ItemDropSolver = new ItemDropResolver(itemDropDatabase);
            Main.ShopHelper = new ShopHelper();
            CreativeItemSacrificesCatalog.Instance.Initialize();
            if (!Main.dedServ)
            {
                Main.BestiaryUI = new UIBestiaryTest(Main.BestiaryDB);
                Main.ContentThatNeedsRenderTargets.Add(Main.MapPlayerRenderer);
            }
            if (!Main.dedServ)
            {
                Lighting.Initialize();
                MapHelper.Initialize();
            }
            else
            {
                Mount.Initialize();
                Minecart.Initialize();
            }
            WorldGen.RandomizeBackgrounds(Main.rand);
            if (Main.treeBGSet1[0] == 173)
            {
                WorldGen.RandomizeBackgrounds(Main.rand);
            }
            if (Main.treeBGSet1[0] == 173)
            {
                WorldGen.RandomizeBackgrounds(Main.rand);
            }
            WorldGen.RandomizeCaveBackgrounds();
            WorldGen.Hooks.Initialize();
            WorldGen.Hooks.OnWorldLoad += Main.ResetGameCounter;
            Main.bgAlphaFrontLayer[0] = 1f;
            Main.bgAlphaFarBackLayer[0] = 1f;
            this.invBottom = 258;
            Main.Initialize_TileAndNPCData1();
            Main.Initialize_TileAndNPCData2();
            Main.Initialize_Items();
            for (int i = 1; i < (int)ProjectileID.Count; i++)
            {
                Projectile projectile = new Projectile();
                projectile.SetDefaults(i);
                if (projectile.hostile)
                {
                    Main.projHostile[i] = true;
                }
                if (projectile.aiStyle == 7)
                {
                    Main.projHook[i] = true;
                }
            }
            Recipe.SetupRecipeGroups();
            ConditionalDialogue.Init();
            ArmorSetBonuses.Initialize();
            ArmorSetBonuses.BuildLookup();
            ItemID.Sets.PostSetupContent();
            TileID.Sets.PostSetupContent();
            ConditionalDialogue.ItemGroups.PostSetupContent();
            DyeInitializer.Load();
            ContentSamples.DyeShaderIDs.Initialize();
            for (int j = 0; j < Recipe.maxRecipes; j++)
            {
                Main.recipe[j] = new Recipe();
            }
            Recipe.SetupRecipes();
            ContentSamples.FixItemsAfterRecipesAreAdded();
            ItemSorting.SetupWhiteLists();
            ContentSamples.RebuildItemCreativeSortingIDsAfterRecipesAreSetUp();
            for (int k = 0; k < Liquid.maxLiquid; k++)
            {
                Main.liquid[k] = new Liquid();
            }
            for (int l = 0; l < 50000; l++)
            {
                Main.liquidBuffer[l] = new LiquidBuffer();
            }
            this.shop[0] = Chest.CreateShop();
            Chest.SetupTravelShop();
            for (int m = 1; m < 100; m++)
            {
                this.shop[m] = Chest.CreateShop();
                this.shop[m].SetupShop(m);
            }
            Main.teamColor[0] = Microsoft.Xna.Framework.Color.White;
            Main.teamColor[1] = new Microsoft.Xna.Framework.Color(218, 59, 59);
            Main.teamColor[2] = new Microsoft.Xna.Framework.Color(59, 218, 85);
            Main.teamColor[3] = new Microsoft.Xna.Framework.Color(59, 149, 218);
            Main.teamColor[4] = new Microsoft.Xna.Framework.Color(242, 221, 100);
            Main.teamColor[5] = new Microsoft.Xna.Framework.Color(224, 100, 242);
            Netplay.Initialize();
            NetworkInitializer.Load();
            ChatInitializer.Load();
            LucyAxeMessage.Initialize();
            if (Platform.IsWindows && !Main.dedServ)
            {
                IntPtr systemMenu = Main.GetSystemMenu(base.Window.Handle, false);
                int menuItemCount = Main.GetMenuItemCount(systemMenu);
                Main.RemoveMenu(systemMenu, menuItemCount - 1, 1024);
            }
            if (!Main.dedServ)
            {
                SoundID.FillAccessMap();
                Star.SpawnStars(-1);
            }
        }
References System.Collections.Generic.List< T >.Add(), Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.AddDropOverrides(), Terraria.Projectile.aiStyle, Terraria.Main.BestiaryDB, Terraria.Main.bgAlphaFarBackLayer, Terraria.Main.bgAlphaFrontLayer, Terraria.DataStructures.ArmorSetBonuses.BuildLookup(), Terraria.Main.CloudFavoritesData, Terraria.Main.ContentThatNeedsRenderTargets, Terraria.ID.ProjectileID.Count, Terraria.Chest.CreateShop(), Terraria.Main.dedServ, Terraria.ID.SoundID.FillAccessMap(), Terraria.Main.FindAnnouncementBoxStatus(), Terraria.ID.ContentSamples.FixItemsAfterRecipesAreAdded(), Terraria.Main.GetMenuItemCount(), Terraria.Main.GetSystemMenu(), Terraria.Projectile.hostile, Terraria.GameContent.ConditionalDialogue.Init(), Terraria.Animation.Initialize(), Terraria.Chest.Initialize(), Terraria.DataStructures.ArmorSetBonuses.Initialize(), Terraria.Framing.Initialize(), Terraria.GameContent.Creative.CreativeItemSacrificesCatalog.Initialize(), Terraria.GameContent.Creative.CreativePowerManager.Initialize(), Terraria.GameContent.LucyAxeMessage.Initialize(), Terraria.GameContent.NPCInteractions.Initialize(), Terraria.GameContent.UI.CustomCurrencyManager.Initialize(), Terraria.GameContent.UI.ItemRarity.Initialize(), Terraria.ID.ContentSamples.DyeShaderIDs.Initialize(), Terraria.ID.TorchID.Initialize(), Terraria.Lighting.Initialize(), Terraria.Map.MapHelper.Initialize(), Terraria.Minecart.Initialize(), Terraria.Mount.Initialize(), Terraria.Netplay.Initialize(), Terraria.ObjectData.TileObjectData.Initialize(), Terraria.Wiring.Initialize(), Terraria.WorldGen.Hooks.Initialize(), Terraria.Main.Initialize_Items(), Terraria.Main.Initialize_TileAndNPCData1(), Terraria.Main.Initialize_TileAndNPCData2(), Terraria.DataStructures.TileEntity.InitializeAll(), Terraria.Main.InitializeItemAnimations(), Terraria.Projectile.InitializeStaticThings(), Terraria.GameContent.Creative.CreativeItemSacrificesCatalog.Instance, int, ReLogic.OS.Platform.IsWindows, Terraria.Main.ItemDropsDB, Terraria.Main.liquid, Terraria.Main.liquidBuffer, Terraria.Initializers.ChatInitializer.Load(), Terraria.Initializers.DyeInitializer.Load(), Terraria.Initializers.NetworkInitializer.Load(), Terraria.Initializers.WingStatsInitializer.Load(), Terraria.IO.FavoritesFile.Load(), Terraria.Main.LocalFavoriteData, Terraria.Main.MapPlayerRenderer, Terraria.Liquid.maxLiquid, Terraria.Recipe.maxRecipes, Terraria.GameContent.Bestiary.BestiaryDatabase.Merge(), Terraria.GameContent.FishDropRules.GameContentFishDropPopulator.Populate(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.Populate(), Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.Populate(), Terraria.GameContent.ConditionalDialogue.ItemGroups.PostSetupContent(), Terraria.ID.ItemID.Sets.PostSetupContent(), Terraria.ID.TileID.Sets.PostSetupContent(), Terraria.Main.projHook, Terraria.Main.projHostile, Terraria.Main.rand, Terraria.WorldGen.RandomizeBackgrounds(), Terraria.WorldGen.RandomizeCaveBackgrounds(), Terraria.ID.ContentSamples.RebuildBestiarySortingIDsByBestiaryDatabaseContents(), Terraria.ID.ContentSamples.RebuildItemCreativeSortingIDsAfterRecipesAreSetUp(), Terraria.Main.recipe, Terraria.GameContent.LeashedEntity.Registry.RegisterAll(), Terraria.Main.RemoveMenu(), Terraria.Main.ResetGameCounter(), Terraria.Projectile.SetDefaults(), Terraria.Recipe.SetupRecipeGroups(), Terraria.Recipe.SetupRecipes(), Terraria.Chest.SetupShop(), Terraria.Chest.SetupTravelShop(), Terraria.UI.ItemSorting.SetupWhiteLists(), Terraria.Star.SpawnStars(), Terraria.Main.teamColor, Terraria.Main.treeBGSet1, and Microsoft.Xna.Framework.Color.White.