Terraria Decompiled: Terraria.Main.NPCChatText_GuideReverseCrafting
NPCChatText_GuideReverseCrafting()
static void Terraria.Main.NPCChatText_GuideReverseCrafting () inline static
Definition at line 39768 of file Main.cs.
        {
            Main.playerInventory = true;
            Main.npcChatText = "";
            SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
            Main.InGuideCraftMenu = true;
            if (Player.Settings.CraftingGridControl == Player.Settings.CraftingGridMode.Modern)
            {
                NewCraftingUI.Open(true, null);
            }
            Main.TryChangePipsPage(Main.PipPage.Recipes);
            UILinkPointNavigator.GoToDefaultPage(0);
        }
References Terraria.Player.Settings.CraftingGridControl, Terraria.UI.Gamepad.UILinkPointNavigator.GoToDefaultPage(), Terraria.GameContent.UI.NewCraftingUI.Open(), Terraria.Audio.SoundEngine.PlaySound(), and Terraria.Main.TryChangePipsPage().
Referenced by Terraria.GameContent.NPCInteractions.Actions.GuideReverseCrafting.Interact().