Terraria Decompiled: Terraria.Main.UpdateAudio_DecideOnNewMusic
UpdateAudio_DecideOnNewMusic()
void Terraria.Main.UpdateAudio_DecideOnNewMusic () inline private
Definition at line 10480 of file Main.cs.
        {
            bool flag = false;
            bool flag2 = false;
            bool flag3 = false;
            bool flag4 = false;
            bool flag5 = false;
            bool flag6 = false;
            bool flag7 = false;
            bool flag8 = false;
            bool flag9 = false;
            bool flag10 = false;
            bool flag11 = false;
            bool flag12 = false;
            bool flag13 = false;
            bool flag14 = false;
            bool flag15 = false;
            bool flag16 = false;
            bool flag17 = false;
            bool flag18 = false;
            bool flag19 = false;
            bool flag20 = false;
            bool flag21 = false;
            bool flag22 = false;
            bool flag23 = Main.SceneMetrics.TownNPCCount >= 3 && !Main.SceneMetrics.ZoneShadowCandle;
            bool flag24 = Main.slimeRain;
            bool flag25 = false;
            bool flag26 = false;
            float num = 0f;
            for (int i = 0; i < Main.maxMusic; i++)
            {
                if (Main.musicFade[i] > num)
                {
                    num = Main.musicFade[i];
                    if (num == 1f)
                    {
                        this.lastMusicPlayed = i;
                    }
                }
            }
            if (this.lastMusicPlayed == 50)
            {
                Main.musicNoCrossFade[51] = true;
            }
            if (!Main.showSplash)
            {
                Microsoft.Xna.Framework.Rectangle rectangle = new Microsoft.Xna.Framework.Rectangle((int)Main.screenPosition.X, (int)Main.screenPosition.Y, Main.screenWidth, Main.screenHeight);
                for (int j = 0; j < Main.maxNPCs; j++)
                {
                    if (Main.npc[j].active)
                    {
                        int num2 = 5000;
                        int num3 = 0;
                        int type = Main.npc[j].type;
                        if (type <= 266)
{
                            if (type <= 114)
{
                                if (type <= 36)
{
                                    if (type - 13 > 2)
{
                                        if (type - 26 <= 3)
{
                                            goto IL_03D4;
                                        }
                                        if (type - 35 <= 1)
{
                                            num3 = 24;
                                        }
                                    }
                                    else
{
                                        num3 = 23;
                                    }
                                }
                                else if (type != 50)
{
                                    if (type == 111)
{
                                        goto IL_03D4;
                                    }
                                    if (type - 113 <= 1)
{
                                        num3 = 2;
                                    }
                                }
                                else
{
                                    num3 = 19;
                                }
                            }
                            else
{
                                if (type <= 222)
{
                                    switch (type)
{
                                    case 125:
                                    case 126:
                                        num3 = 21;
                                        goto IL_049B;
                                    case 127:
                                    case 128:
                                    case 129:
                                    case 130:
                                    case 131:
                                        num3 = 22;
                                        goto IL_049B;
                                    case 132:
                                    case 133:
                                    case 137:
                                    case 138:
                                    case 139:
                                    case 140:
                                    case 141:
                                    case 142:
                                        goto IL_049B;
                                    case 134:
                                    case 135:
                                    case 136:
                                        num3 = 18;
                                        goto IL_049B;
                                    case 143:
                                    case 144:
                                    case 145:
                                        break;
                                    default:
                                        if (type - 212 <= 4)
{
                                            goto IL_0408;
                                        }
                                        if (type != 222)
{
                                            goto IL_049B;
                                        }
                                        num3 = 5;
                                        goto IL_049B;
                                    }
                                }
                                else if (type <= 252)
{
                                    if (type == 245)
{
                                        num3 = 4;
                                        goto IL_049B;
                                    }
                                    if (type != 252)
{
                                        goto IL_049B;
                                    }
                                    goto IL_0408;
                                }
                                else
{
                                    if (type - 262 <= 2)
{
                                        num3 = 6;
                                        goto IL_049B;
                                    }
                                    if (type != 266)
{
                                        goto IL_049B;
                                    }
                                }
                                num3 = 3;
                            }
                        }
                        else
{
                            if (type <= 493)
{
                                if (type <= 438)
{
                                    switch (type)
{
                                    case 370:
                                        num3 = 15;
                                        goto IL_049B;
                                    case 371:
                                    case 372:
                                    case 373:
                                    case 374:
                                    case 375:
                                    case 376:
                                    case 377:
                                    case 378:
                                    case 380:
                                    case 393:
                                    case 394:
                                    case 396:
                                    case 397:
                                        goto IL_049B;
                                    case 379:
                                        if (Main.npc[j].ai[3] >= 0f)
{
                                            num2 = 1600;
                                            num3 = 20;
                                            goto IL_049B;
                                        }
                                        goto IL_049B;
                                    case 381:
                                    case 382:
                                    case 383:
                                    case 384:
                                    case 385:
                                    case 386:
                                    case 387:
                                    case 388:
                                    case 389:
                                    case 390:
                                    case 391:
                                    case 392:
                                    case 395:
                                        break;
                                    case 398:
                                        num3 = 7;
                                        goto IL_049B;
                                    default:
                                        if (type == 422)
{
                                            goto IL_042D;
                                        }
                                        if (type != 438)
{
                                            goto IL_049B;
                                        }
                                        if (Main.npc[j].ai[1] == 1f)
{
                                            num2 = 1600;
                                            num3 = 20;
                                            goto IL_049B;
                                        }
                                        goto IL_049B;
                                    }
                                }
                                else if (type <= 472)
{
                                    if (type == 439)
{
                                        num3 = 20;
                                        goto IL_049B;
                                    }
                                    if (type - 471 > 1)
{
                                        goto IL_049B;
                                    }
                                    goto IL_03D4;
                                }
                                else
{
                                    if (type == 491)
{
                                        goto IL_0408;
                                    }
                                    if (type != 493)
{
                                        goto IL_049B;
                                    }
                                    goto IL_042D;
                                }
                            }
                            else if (type <= 520)
{
                                if (type == 507 || type == 517)
{
                                    goto IL_042D;
                                }
                                if (type != 520)
{
                                    goto IL_049B;
                                }
                            }
                            else if (type <= 657)
{
                                if (type == 636)
{
                                    num3 = 14;
                                    goto IL_049B;
                                }
                                if (type != 657)
{
                                    goto IL_049B;
                                }
                                num3 = 13;
                                goto IL_049B;
                            }
                            else
{
                                if (type == 662)
{
                                    goto IL_0408;
                                }
                                if (type != 668)
{
                                    goto IL_049B;
                                }
                                num3 = 16;
                                goto IL_049B;
                            }
                            num3 = 9;
                            goto IL_049B;
                            IL_042D:
                            num3 = 10;
                        }
                        IL_049B:
                        if (NPCID.Sets.BelongsToInvasionOldOnesArmy[Main.npc[j].type])
{
                            num3 = 12;
                        }
                        if (num3 == 0 && Main.npc[j].boss)
{
                            num3 = 1;
                        }
                        if (Main.remixWorld && Main.getGoodWorld && (Main.npc[j].type == 127 || Main.npc[j].type == 134 || Main.npc[j].type == 125 || Main.npc[j].type == 126))
{
                            num3 = 17;
                        }
                        if (num3 == 0)
{
                            goto IL_06B8;
                        }
                        Microsoft.Xna.Framework.Rectangle rectangle2 = new Microsoft.Xna.Framework.Rectangle((int)(Main.npc[j].position.X + (float)(Main.npc[j].width / 2)) - num2, (int)(Main.npc[j].position.Y + (float)(Main.npc[j].height / 2)) - num2, num2 * 2, num2 * 2);
                        if (!rectangle.Intersects(rectangle2))
{
                            goto IL_06B8;
                        }
                        if (num3 == 1)
{
                            flag = true;
                            break;
                        }
                        if (num3 == 2)
{
                            flag3 = true;
                            break;
                        }
                        if (num3 == 3)
{
                            flag4 = true;
                            break;
                        }
                        if (num3 == 4)
{
                            flag5 = true;
                            break;
                        }
                        if (num3 == 5)
{
                            flag6 = true;
                            break;
                        }
                        if (num3 == 6)
{
                            flag7 = true;
                            break;
                        }
                        if (num3 == 7)
{
                            flag8 = true;
                            break;
                        }
                        if (num3 == 8)
{
                            flag9 = true;
                            break;
                        }
                        if (num3 == 9)
{
                            flag10 = true;
                            break;
                        }
                        if (num3 == 10)
{
                            flag11 = true;
                            break;
                        }
                        if (num3 == 11)
{
                            flag12 = true;
                            break;
                        }
                        if (num3 == 12)
{
                            flag13 = true;
                            break;
                        }
                        if (num3 == 13)
{
                            flag14 = true;
                            break;
                        }
                        if (num3 == 14)
{
                            flag15 = true;
                            break;
                        }
                        if (num3 == 15)
{
                            flag16 = true;
                            break;
                        }
                        if (num3 == 16)
{
                            flag2 = true;
                            break;
                        }
                        if (num3 == 17)
{
                            flag17 = true;
                            break;
                        }
                        if (num3 == 18)
{
                            flag18 = true;
                            break;
                        }
                        if (num3 == 19)
{
                            flag19 = true;
                            break;
                        }
                        if (num3 == 20)
{
                            flag20 = true;
                            break;
                        }
                        if (num3 == 21)
{
                            flag21 = true;
                            break;
                        }
                        if (num3 == 22)
{
                            flag22 = true;
                            break;
                        }
                        if (num3 == 23)
{
                            flag25 = true;
                            break;
                        }
                        if (num3 == 24)
{
                            flag26 = true;
                            break;
                        }
                        break;
                        IL_03D4:
                        num3 = 11;
                        goto IL_049B;
                        IL_0408:
                        num3 = 8;
                        goto IL_049B;
                    }
                    IL_06B8:;
                }
            }
            float num4 = (Main.screenPosition.X + (float)(Main.screenWidth / 2)) / 16f;
            if (Main.musicVolume == 0f)
            {
                Main.newMusic = 0;
                return;
            }
            if (Main.gameMenu)
            {
                if (Main.netMode == 2)
                {
                    Main.newMusic = 0;
                    return;
                }
                if (WorldGen.drunkWorldGen)
                {
                    if (WorldGen.remixWorldGen)
                    {
                        Main.newMusic = 70;
                        return;
                    }
                    if (Main.onlyShimmerOceanWorldsGeneration)
                    {
                        Main.newMusic = 72;
                        return;
                    }
                    if (Main.vampireSeed)
                    {
                        Main.newMusic = 75;
                        return;
                    }
                    if (Main.notTheBeesWorld)
                    {
                        Main.newMusic = 86;
                        return;
                    }
                    Main.newMusic = 60;
                    return;
                }
                else
                {
                    if (WorldGen.remixWorldGen)
                    {
                        Main.newMusic = 8;
                        return;
                    }
                    if (Main.menuMode == 3000)
                    {
                        Main.newMusic = 89;
                        return;
                    }
                    if (WorldGen.tenthAnniversaryWorldGen)
                    {
                        Main.newMusic = 11;
                        return;
                    }
                    if (this.playOldTile && Main.titleMusicStyle == Main.TitleMusicStyle.Current)
                    {
                        Main.newMusic = 6;
                        return;
                    }
                    if (!Main._isAsyncLoadComplete && (Main.titleMusicStyle == Main.TitleMusicStyle.Current || (Main.titleMusicStyle == Main.TitleMusicStyle.Random && Main.titleMusicStyleRandom == Main.TitleMusicStyle.Current)))
                    {
                        Main.newMusic = 50;
                        return;
                    }
                    if (!Main.audioSystem.IsTrackPlaying(50))
                    {
                        Main.TitleMusicStyle titleMusicStyle = Main.titleMusicStyle;
                        if (titleMusicStyle == Main.TitleMusicStyle.Random)
{
                            titleMusicStyle = Main.titleMusicStyleRandom;
                        }
                        if (titleMusicStyle == Main.TitleMusicStyle.Console)
{
                            Main.newMusic = 60;
                        }
                        else if (titleMusicStyle == Main.TitleMusicStyle.Old)
{
                            Main.newMusic = 6;
                        }
                        else
{
                            Main.newMusic = 51;
                        }
                        if (Main.musicNoCrossFade[Main.newMusic])
{
                            Main.musicFade[Main.newMusic] = 1f;
                            return;
                        }
                    }
                }
            }
            else
            {
                float num5 = (float)Main.maxTilesX / 4200f;
                num5 *= num5;
                float num6 = (float)((double)((Main.screenPosition.Y + (float)(Main.screenHeight / 2)) / 16f - (65f + 10f * num5)) / (Main.worldSurface / 5.0));
                int num7 = (int)(Main.SceneMetrics.Center.X / 16f);
                int num8 = (int)(Main.SceneMetrics.Center.Y / 16f);
                Tile tile = (WorldGen.InWorld(num7, num8, 0) ? Main.tile[num7, num8] : null);
                if (CreditsRollEvent.IsEventOngoing)
                {
                    Main.newMusic = 89;
                }
                else if (Main.SceneMetrics.InTorchGodMinigame)
                {
                    Main.newMusic = 101;
                }
                else if (flag8)
                {
                    Main.newMusic = 38;
                }
                else if (flag17)
                {
                    Main.newMusic = 25;
                }
                else if (flag10)
                {
                    Main.newMusic = 37;
                }
                else if (flag11)
                {
                    Main.newMusic = 34;
                }
                else if (flag7)
                {
                    Main.newMusic = 24;
                }
                else if (flag15)
                {
                    Main.newMusic = 57;
                }
                else if (flag16)
                {
                    Main.newMusic = 58;
                }
                else if (flag18)
                {
                    Main.newMusic = 92;
                }
                else if (flag21)
                {
                    Main.newMusic = 97;
                }
                else if (flag22)
                {
                    Main.newMusic = 98;
                }
                else if (flag19)
                {
                    Main.newMusic = 93;
                }
                else if (flag20)
                {
                    Main.newMusic = 94;
                }
                else if (flag3)
                {
                    Main.newMusic = 12;
                }
                else if (flag)
                {
                    Main.newMusic = 5;
                }
                else if (flag4)
                {
                    Main.newMusic = 13;
                }
                else if (flag5)
                {
                    Main.newMusic = 17;
                }
                else if (flag26)
                {
                    Main.newMusic = 104;
                }
                else if (flag6)
                {
                    Main.newMusic = 96;
                }
                else if (flag14)
                {
                    Main.newMusic = 56;
                }
                else if (flag25)
                {
                    Main.newMusic = 99;
                }
                else if (flag2)
                {
                    Main.newMusic = 90;
                }
                else if (Main.ShouldPlayRainbowBoulderMusic)
                {
                    Main.newMusic = (Main._finishedRainbowBoulderStart ? 103 : 102);
                }
                else if (flag9)
                {
                    Main.newMusic = 35;
                }
                else if (flag12)
                {
                    Main.newMusic = 39;
                }
                else if (flag13)
                {
                    Main.newMusic = 41;
                }
                else if (Main.eclipse && !Main.remixWorld && (double)Main.SceneMetrics.Center.Y < Main.worldSurface * 16.0 + (double)(Main.screenHeight / 2))
                {
                    Main.newMusic = 27;
                }
                else if (Main.eclipse && Main.remixWorld && (double)Main.SceneMetrics.Center.Y > Main.rockLayer * 16.0)
                {
                    Main.newMusic = 27;
                }
                else if (flag24 && !Main.SceneMetrics.ZoneGraveyard && (!Main.bloodMoon || Main.dayTime) && (double)Main.SceneMetrics.Center.Y < Main.worldSurface * 16.0 + (double)(Main.screenHeight / 2))
                {
                    Main.newMusic = 48;
                }
                else if (Main.remixWorld && Main.bloodMoon && !Main.SceneMetrics.ZoneCrimson && !Main.SceneMetrics.ZoneCorrupt && (double)Main.SceneMetrics.Center.Y > Main.rockLayer * 16.0 && Main.SceneMetrics.Center.Y <= (float)(Main.UnderworldLayer * 16))
                {
                    Main.newMusic = 2;
                }
                else if (Main.remixWorld && Main.bloodMoon && Main.SceneMetrics.Center.Y > (float)(Main.UnderworldLayer * 16) && (double)(Main.SceneMetrics.Center.X / 16f) > (double)Main.maxTilesX * 0.37 + 50.0 && (double)(Main.SceneMetrics.Center.X / 16f) < (double)Main.maxTilesX * 0.63)
                {
                    Main.newMusic = 2;
                }
                else if (Main.SceneMetrics.ZoneShimmer)
                {
                    Main.newMusic = 91;
                }
                else if (flag23 && Main.dayTime && ((Main.cloudAlpha == 0f && !Main._shouldUseWindyDayMusic) || (double)Main.SceneMetrics.Center.Y >= Main.worldSurface * 16.0 + (double)(Main.screenHeight / 2)) && !Main.SceneMetrics.ZoneGraveyard)
                {
                    Main.newMusic = 46;
                }
                else if (flag23 && !Main.dayTime && ((!Main.bloodMoon && Main.cloudAlpha == 0f) || (double)Main.SceneMetrics.Center.Y >= Main.worldSurface * 16.0 + (double)(Main.screenHeight / 2)) && !Main.SceneMetrics.ZoneGraveyard)
                {
                    Main.newMusic = 47;
                }
                else if (Main.SceneMetrics.ZoneSandstorm)
                {
                    Main.newMusic = 40;
                }
                else if (Main.SceneMetrics.Center.Y > (float)(Main.UnderworldLayer * 16))
                {
                    Main.newMusic = 36;
                }
                else if (num6 < 1f)
                {
                    Main.newMusic = (Main.dayTime ? 42 : 15);
                }
                else if (tile != null && tile.wall == 87)
                {
                    Main.newMusic = 26;
                }
                else if (Main.SceneMetrics.ZoneDungeon)
                {
                    Main.newMusic = 23;
                }
                else if ((Main.bgStyle == 9 && (double)Main.SceneMetrics.Center.Y < Main.worldSurface * 16.0 + (double)(Main.screenHeight / 2)) || Main.undergroundBackground == 2)
                {
                    Main.newMusic = 29;
                }
                else if (Main.SceneMetrics.ZoneCorrupt)
                {
                    if (Main.SceneMetrics.ZoneCrimson && Main.SceneMetrics.BloodTileCount > Main.SceneMetrics.EvilTileCount)
                    {
                        if ((double)Main.SceneMetrics.Center.Y > Main.worldSurface * 16.0 + (double)(Main.screenHeight / 2))
{
                            Main.newMusic = 33;
                        }
                        else
{
                            Main.newMusic = 16;
                        }
                    }
                    else if ((double)Main.SceneMetrics.Center.Y > Main.worldSurface * 16.0 + (double)(Main.screenHeight / 2))
                    {
                        Main.newMusic = 10;
                    }
                    else
                    {
                        Main.newMusic = 8;
                    }
                }
                else if (Main.SceneMetrics.ZoneCrimson)
                {
                    if ((double)Main.SceneMetrics.Center.Y > Main.worldSurface * 16.0 + (double)(Main.screenHeight / 2))
                    {
                        Main.newMusic = 33;
                    }
                    else
                    {
                        Main.newMusic = 16;
                    }
                }
                else if (Main.SceneMetrics.ZoneMeteor)
                {
                    Main.newMusic = 2;
                }
                else if (Main.SceneMetrics.ZoneGraveyard)
                {
                    Main.newMusic = 53;
                }
                else if (Main.SceneMetrics.ZoneUndergroundDesert)
                {
                    Main.newMusic = 61;
                }
                else if (Main.SceneMetrics.ZoneDesert)
                {
                    Main.newMusic = 21;
                }
                else if (Main.SceneMetrics.ZoneJungle)
                {
                    if (Main.remixWorld)
                    {
                        if ((double)Main.SceneMetrics.Center.Y > Main.rockLayer * 16.0 + (double)(Main.screenHeight / 2))
{
                            Main.newMusic = 7;
                        }
                        else if (Main.newMusic == 7 && (double)Main.SceneMetrics.Center.Y > (Main.rockLayer - 50.0) * 16.0 + (double)(Main.screenHeight / 2))
{
                            Main.newMusic = 7;
                        }
                        else if ((double)Main.SceneMetrics.Center.Y < Main.worldSurface * 16.0 + (double)(Main.screenHeight / 2))
{
                            Main.newMusic = (Main.dayTime ? 42 : 15);
                        }
                        else
{
                            Main.newMusic = 54;
                        }
                    }
                    else if ((double)Main.SceneMetrics.Center.Y > Main.rockLayer * 16.0 + (double)(Main.screenHeight / 2))
                    {
                        Main.newMusic = 54;
                    }
                    else if (Main.newMusic == 54 && (double)Main.SceneMetrics.Center.Y > (Main.rockLayer - 50.0) * 16.0 + (double)(Main.screenHeight / 2))
                    {
                        Main.newMusic = 54;
                    }
                    else if (Main._shouldUseStormMusic && (double)Main.SceneMetrics.Center.Y < Main.worldSurface * 16.0 + (double)(Main.screenHeight / 2))
                    {
                        Main.newMusic = 52;
                    }
                    else if (Main.dayTime)
                    {
                        Main.newMusic = 7;
                    }
                    else
                    {
                        Main.newMusic = 55;
                    }
                }
                else if (Main.SceneMetrics.ZoneSnow)
                {
                    if ((double)Main.SceneMetrics.Center.Y > Main.worldSurface * 16.0 + (double)(Main.screenHeight / 2))
                    {
                        if (Main.remixWorld && (double)Main.SceneMetrics.Center.Y > Main.rockLayer * 16.0 + (double)(Main.screenHeight / 2))
{
                            Main.newMusic = 14;
                        }
                        else
{
                            Main.newMusic = 20;
                        }
                    }
                    else if (Main.remixWorld)
                    {
                        Main.newMusic = (Main.dayTime ? 42 : 15);
                    }
                    else
                    {
                        Main.newMusic = 14;
                    }
                }
                else if ((double)Main.SceneMetrics.Center.Y >= Main.worldSurface * 16.0 + (double)(Main.screenHeight / 2) && (Main.remixWorld || !WorldGen.oceanDepths((int)(Main.screenPosition.X + (float)(Main.screenWidth / 2)) / 16, (int)(Main.screenPosition.Y + (float)(Main.screenHeight / 2)) / 16)))
                {
                    if (Main.SceneMetrics.ZoneHallow)
                    {
                        if (Main.remixWorld && (double)Main.SceneMetrics.Center.Y >= Main.rockLayer * 16.0 + (double)(Main.screenHeight / 2))
{
                            Main.newMusic = 9;
                        }
                        else
{
                            Main.newMusic = 11;
                        }
                    }
                    else
                    {
                        if (Main.ugMusic == 0)
{
                            Main.ugMusic = 4;
                        }
                        if (!Main.audioSystem.IsTrackPlaying(4) && !Main.audioSystem.IsTrackPlaying(31))
{
                            if (Main.musicFade[4] == 1f)
{
                                Main.musicFade[31] = 1f;
                            }
                            if (Main.musicFade[31] == 1f)
{
                                Main.musicFade[4] = 1f;
                            }
                            int num9 = Main.rand.Next(2);
                            if (num9 == 0)
{
                                Main.ugMusic = 4;
                                Main.musicFade[31] = 0f;
                            }
                            else if (num9 == 1)
{
                                Main.ugMusic = 31;
                                Main.musicFade[4] = 0f;
                            }
                        }
                        Main.newMusic = Main.ugMusic;
                        if (Main.remixWorld && (double)(Main.SceneMetrics.Center.Y / 16f) > Main.rockLayer && Main.SceneMetrics.Center.Y / 16f < (float)(Main.maxTilesY - 350))
{
                            if (Main.cloudAlpha > 0f)
{
                                Main.newMusic = 19;
                            }
                            else if (Main.SceneMetrics.ZoneDesert)
{
                                Main.newMusic = 21;
                            }
                            else if (Main._shouldUseWindyDayMusic)
{
                                Main.newMusic = 44;
                            }
                        }
                    }
                }
                else if (Main.dayTime && Main.SceneMetrics.ZoneHallow)
                {
                    if (Main._shouldUseStormMusic)
                    {
                        Main.newMusic = 52;
                    }
                    else if (Main.cloudAlpha > 0f && !Main.gameMenu)
                    {
                        Main.newMusic = 19;
                    }
                    else if (Main._shouldUseWindyDayMusic && !Main.remixWorld)
                    {
                        Main.newMusic = 44;
                    }
                    else
                    {
                        Main.newMusic = 9;
                    }
                }
                else if (Main._shouldUseStormMusic)
                {
                    if (Main.bloodMoon)
                    {
                        Main.newMusic = 2;
                    }
                    else
                    {
                        Main.newMusic = 52;
                    }
                }
                else if (WorldGen.oceanDepths((int)(Main.screenPosition.X + (float)(Main.screenWidth / 2)) / 16, (int)(Main.screenPosition.Y + (float)(Main.screenHeight / 2)) / 16))
                {
                    if (Main.bloodMoon)
                    {
                        Main.newMusic = 2;
                    }
                    else if (flag23)
                    {
                        if (Main.dayTime)
{
                            Main.newMusic = 46;
                        }
                        else
{
                            Main.newMusic = 47;
                        }
                    }
                    else
                    {
                        Main.newMusic = (Main.dayTime ? 22 : 43);
                    }
                }
                else if (Main.remixWorld)
                {
                    Main.newMusic = (Main.dayTime ? 42 : 15);
                }
                else if (Main.dayTime)
                {
                    if (Main.cloudAlpha > 0f && !Main.gameMenu)
                    {
                        if (Main.time < 10800.0)
{
                            Main.newMusic = 59;
                        }
                        else
{
                            Main.newMusic = 19;
                        }
                    }
                    else
                    {
                        if (Main.dayMusic == 0)
{
                            Main.dayMusic = 1;
                        }
                        if (!Main.audioSystem.IsTrackPlaying(1) && !Main.audioSystem.IsTrackPlaying(18))
{
                            if (Main.rand.Next(2) == 0)
{
                                Main.dayMusic = 1;
                            }
                            else
{
                                Main.dayMusic = 18;
                            }
                        }
                        Main.newMusic = Main.dayMusic;
                        if (Main._shouldUseWindyDayMusic && !Main.remixWorld)
{
                            Main.newMusic = 44;
                        }
                    }
                }
                else if (!Main.dayTime)
                {
                    if (Main.bloodMoon)
                    {
                        Main.newMusic = 2;
                    }
                    else if (Main.cloudAlpha > 0f && !Main.gameMenu)
                    {
                        Main.newMusic = 19;
                    }
                    else
                    {
                        Main.newMusic = 3;
                    }
                }
                if (((double)(Main.screenPosition.Y / 16f) < Main.worldSurface + 10.0 || Main.remixWorld) && Main.pumpkinMoon)
                {
                    Main.newMusic = 30;
                }
                if (((double)(Main.screenPosition.Y / 16f) < Main.worldSurface + 10.0 || Main.remixWorld) && Main.snowMoon)
                {
                    Main.newMusic = 32;
                }
            }
        }
References Terraria.Main._isAsyncLoadComplete, Terraria.Main._shouldUseStormMusic, Terraria.Main._shouldUseWindyDayMusic, Terraria.NPC.active, Terraria.NPC.ai, Terraria.Main.audioSystem, Terraria.ID.NPCID.Sets.BelongsToInvasionOldOnesArmy, Terraria.Main.bgStyle, Terraria.Main.bloodMoon, Terraria.SceneMetrics.BloodTileCount, Terraria.NPC.boss, Terraria.SceneMetrics.Center, Terraria.Main.cloudAlpha, Terraria.Main.dayMusic, Terraria.Main.dayTime, Terraria.WorldGen.drunkWorldGen, Terraria.Main.eclipse, Terraria.SceneMetrics.EvilTileCount, Terraria.Main.gameMenu, Terraria.Main.getGoodWorld, Terraria.Entity.height, int, Microsoft.Xna.Framework.Rectangle.Intersects(), Terraria.SceneMetrics.InTorchGodMinigame, Terraria.WorldGen.InWorld(), Terraria.GameContent.Events.CreditsRollEvent.IsEventOngoing, Terraria.Audio.IAudioSystem.IsTrackPlaying(), Terraria.Main.maxMusic, Terraria.Main.maxNPCs, Terraria.Main.maxTilesX, Terraria.Main.menuMode, Terraria.Main.musicFade, Terraria.Main.musicNoCrossFade, Terraria.Main.musicVolume, Terraria.Main.netMode, Terraria.Main.newMusic, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.notTheBeesWorld, Terraria.Main.npc, Terraria.WorldGen.oceanDepths(), Terraria.Main.onlyShimmerOceanWorldsGeneration, Terraria.Entity.position, Terraria.Main.pumpkinMoon, Terraria.Main.rand, Terraria.Main.remixWorld, Terraria.WorldGen.remixWorldGen, Terraria.Main.rockLayer, Terraria.Main.SceneMetrics, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Terraria.Main.ShouldPlayRainbowBoulderMusic, Terraria.Main.showSplash, Terraria.Main.slimeRain, Terraria.Main.snowMoon, Terraria.WorldGen.tenthAnniversaryWorldGen, Terraria.Main.tile, Terraria.Main.time, Terraria.Main.titleMusicStyle, Terraria.Main.titleMusicStyleRandom, Terraria.NPC.type, Terraria.Main.ugMusic, Terraria.Main.undergroundBackground, Terraria.Main.UnderworldLayer, Terraria.Main.vampireSeed, Terraria.Tile.wall, Terraria.Entity.width, Terraria.Main.worldSurface, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, Terraria.SceneMetrics.ZoneCorrupt, Terraria.SceneMetrics.ZoneCrimson, Terraria.SceneMetrics.ZoneDesert, Terraria.SceneMetrics.ZoneDungeon, Terraria.SceneMetrics.ZoneGraveyard, Terraria.SceneMetrics.ZoneHallow, Terraria.SceneMetrics.ZoneJungle, Terraria.SceneMetrics.ZoneMeteor, Terraria.SceneMetrics.ZoneSandstorm, Terraria.SceneMetrics.ZoneShadowCandle, Terraria.SceneMetrics.ZoneShimmer, Terraria.SceneMetrics.ZoneSnow, and Terraria.SceneMetrics.ZoneUndergroundDesert.