Terraria Decompiled: Terraria.Main.DrawBackground_DrawMagmaLayer
DrawBackground_DrawMagmaLayer()
void Terraria.Main.DrawBackground_DrawMagmaLayer (double magmaLayer, int q1, int q2, ref Vector2 drawOffset, ref Vector3 backgroundColor) inline private
Definition at line 53431 of file Main.cs.
        {
            float x = backgroundColor.X;
            float y = backgroundColor.Y;
            float z = backgroundColor.Z;
            this.bgTopY = (float)magmaLayer * 16f - Main.screenPosition.Y + 16f + 600f - 8f;
            bool flag = false;
            int num = 128;
            if (magmaLayer * 16.0 <= (double)(Main.screenPosition.Y + (float)Main.screenHeight))
            {
                this.bgStartX = (int)(-Math.IEEERemainder((double)num + (double)Main.screenPosition.X * this.bgParallax, (double)num) - (double)(num / 2)) - (int)drawOffset.X;
                this.bgLoops = (Main.screenWidth + (int)drawOffset.X * 2) / num + 2;
                if (magmaLayer * 16.0 + (double)Main.screenHeight < (double)(Main.screenPosition.Y - 16f))
                {
                    this.bgStartY = (int)(Math.IEEERemainder((double)this.bgTopY, (double)Main.backgroundHeight[2]) - (double)Main.backgroundHeight[2]);
                    this.bgLoopsY = (Main.screenHeight - this.bgStartY + (int)drawOffset.Y * 2) / Main.backgroundHeight[2] + 1;
                }
                else
                {
                    this.bgStartY = (int)this.bgTopY;
                    this.bgLoopsY = (int)((float)Main.screenHeight - this.bgTopY + drawOffset.Y * 2f) / Main.backgroundHeight[2] + 1;
                }
                if ((float)Main.UnderworldLayer * 16f < Main.screenPosition.Y + (float)Main.screenHeight)
                {
                    this.bgLoopsY = (int)Math.Ceiling((double)(((float)Main.UnderworldLayer * 16f - Main.screenPosition.Y - (float)this.bgStartY) / (float)Main.backgroundHeight[2]));
                    flag = true;
                }
                q1 = (int)((double)q1 * 1.5);
                q2 = (int)((double)q2 * 1.5);
                int num2 = (int)((float)Math.Round((double)(-(double)((float)Math.IEEERemainder((double)((float)this.bgStartX + Main.screenPosition.X), 16.0)))));
                if (num2 == -8)
                {
                    num2 = 8;
                }
                for (int i = 0; i < this.bgLoops; i++)
                {
                    for (int j = 0; j < this.bgLoopsY; j++)
                    {
                        for (int k = 0; k < num / 16; k++)
{
                            for (int l = 0; l < 6; l++)
{
                                float num3 = (float)(this.bgStartY + j * 96 + l * 16 + 8);
                                int num4 = (int)(((float)(this.bgStartX + num * i + k * 16 + 8) + Main.screenPosition.X) / 16f);
                                int num5 = (int)((num3 + Main.screenPosition.Y) / 16f);
                                if (WorldGen.InWorld(num4, num5, 1))
{
                                    Microsoft.Xna.Framework.Color color = Lighting.GetColor(num4, num5);
                                    if ((Main.ShouldDrawBackgroundTileAt(num4, num5) || color.R == 0 || color.G == 0 || color.B == 0) && (color.R > 0 || color.G > 0 || color.B > 0 || num5 > Main.maxTilesY - 300) && (Main.WallLightAt(num4, num5) || Main.caveParallax != 0f))
{
                                        if (Lighting.NotRetro && color.R < 230 && color.G < 230 && color.B < 230)
{
                                            if (((int)color.R > q1 || (double)color.G > (double)q1 * 1.1 || (double)color.B > (double)q1 * 1.2) && !Main.tile[num4, num5].active())
{
                                                Lighting.GetColor9Slice(num4, num5, ref this._drawbackground_colorSlices);
                                                for (int m = 0; m < 9; m++)
{
                                                    int num6 = 0;
                                                    int num7 = 0;
                                                    int num8 = 4;
                                                    int num9 = 4;
                                                    Microsoft.Xna.Framework.Color color2 = color;
                                                    Microsoft.Xna.Framework.Color color3 = color;
                                                    switch (m)
{
                                                    case 0:
                                                        if (!Main.tile[num4 - 1, num5 - 1].active())
{
                                                            color3 = this._drawbackground_colorSlices[m];
                                                        }
                                                        break;
                                                    case 1:
                                                        num8 = 8;
                                                        num6 = 4;
                                                        if (!Main.tile[num4, num5 - 1].active())
{
                                                            color3 = this._drawbackground_colorSlices[m];
                                                        }
                                                        break;
                                                    case 2:
                                                        num6 = 12;
                                                        if (!Main.tile[num4 + 1, num5 - 1].active())
{
                                                            color3 = this._drawbackground_colorSlices[m];
                                                        }
                                                        break;
                                                    case 3:
                                                        num9 = 8;
                                                        num7 = 4;
                                                        if (!Main.tile[num4 - 1, num5].active())
{
                                                            color3 = this._drawbackground_colorSlices[m];
                                                        }
                                                        break;
                                                    case 4:
                                                        num8 = 8;
                                                        num9 = 8;
                                                        num6 = 4;
                                                        num7 = 4;
                                                        break;
                                                    case 5:
                                                        num6 = 12;
                                                        num7 = 4;
                                                        num9 = 8;
                                                        if (!Main.tile[num4 + 1, num5].active())
{
                                                            color3 = this._drawbackground_colorSlices[m];
                                                        }
                                                        break;
                                                    case 6:
                                                        num7 = 12;
                                                        if (!Main.tile[num4 - 1, num5 + 1].active())
{
                                                            color3 = this._drawbackground_colorSlices[m];
                                                        }
                                                        break;
                                                    case 7:
                                                        num8 = 8;
                                                        num9 = 4;
                                                        num6 = 4;
                                                        num7 = 12;
                                                        if (!Main.tile[num4, num5 + 1].active())
{
                                                            color3 = this._drawbackground_colorSlices[m];
                                                        }
                                                        break;
                                                    case 8:
                                                        num6 = 12;
                                                        num7 = 12;
                                                        if (!Main.tile[num4 + 1, num5 + 1].active())
{
                                                            color3 = this._drawbackground_colorSlices[m];
                                                        }
                                                        break;
                                                    }
                                                    color2.R = (color.R + color3.R) / 2;
                                                    color2.G = (color.G + color3.G) / 2;
                                                    color2.B = (color.B + color3.B) / 2;
                                                    color2.R = (byte)((float)color2.R * x);
                                                    color2.G = (byte)((float)color2.G * y);
                                                    color2.B = (byte)((float)color2.B * z);
                                                    Main.spriteBatch.Draw(TextureAssets.Background[this._drawBackground_backTexture[5]].Value, new Vector2((float)(this.bgStartX + num * i + 16 * k + num6 + num2), (float)(this.bgStartY + Main.backgroundHeight[2] * j + 16 * l + num7)) + drawOffset, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * k + num6 + num2 + 16, 16 * l + Main.backgroundHeight[2] * Main.magmaBGFrame + num7, num8, num9)), color2, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
                                                }
                                            }
                                            else if ((int)color.R > q2 || (double)color.G > (double)q2 * 1.1 || (double)color.B > (double)q2 * 1.2)
{
                                                Lighting.GetColor4Slice(num4, num5, ref this._drawbackground_colorSlices);
                                                for (int n = 0; n < 4; n++)
{
                                                    int num10 = 0;
                                                    int num11 = 0;
                                                    Microsoft.Xna.Framework.Color color4 = color;
                                                    Microsoft.Xna.Framework.Color color5 = this._drawbackground_colorSlices[n];
                                                    switch (n)
{
                                                    case 1:
                                                        num10 = 8;
                                                        break;
                                                    case 2:
                                                        num11 = 8;
                                                        break;
                                                    case 3:
                                                        num10 = 8;
                                                        num11 = 8;
                                                        break;
                                                    }
                                                    color4.R = (color.R + color5.R) / 2;
                                                    color4.G = (color.G + color5.G) / 2;
                                                    color4.B = (color.B + color5.B) / 2;
                                                    color4.R = (byte)((float)color4.R * x);
                                                    color4.G = (byte)((float)color4.G * y);
                                                    color4.B = (byte)((float)color4.B * z);
                                                    Main.spriteBatch.Draw(TextureAssets.Background[this._drawBackground_backTexture[5]].Value, new Vector2((float)(this.bgStartX + num * i + 16 * k + num10 + num2), (float)(this.bgStartY + Main.backgroundHeight[2] * j + 16 * l + num11)) + drawOffset, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * k + num10 + num2 + 16, 16 * l + Main.backgroundHeight[2] * Main.magmaBGFrame + num11, 8, 8)), color4, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
                                                }
                                            }
                                            else
{
                                                color.R = (byte)((float)color.R * x);
                                                color.G = (byte)((float)color.G * y);
                                                color.B = (byte)((float)color.B * z);
                                                Main.spriteBatch.Draw(TextureAssets.Background[this._drawBackground_backTexture[5]].Value, new Vector2((float)(this.bgStartX + num * i + 16 * k + num2), (float)(this.bgStartY + Main.backgroundHeight[2] * j + 16 * l)) + drawOffset, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * k + num2 + 16, 16 * l + Main.backgroundHeight[2] * Main.magmaBGFrame, 16, 16)), color, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
                                            }
                                        }
                                        else
{
                                            color.R = (byte)((float)color.R * x);
                                            color.G = (byte)((float)color.G * y);
                                            color.B = (byte)((float)color.B * z);
                                            Main.spriteBatch.Draw(TextureAssets.Background[this._drawBackground_backTexture[5]].Value, new Vector2((float)(this.bgStartX + num * i + 16 * k + num2), (float)(this.bgStartY + Main.backgroundHeight[2] * j + 16 * l)) + drawOffset, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * k + num2 + 16, 16 * l + Main.backgroundHeight[2] * Main.magmaBGFrame, 16, 16)), color, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
                if (flag)
                {
                    this.bgParallax = (double)Main.caveParallax;
                    this.bgStartX = (int)(-Math.IEEERemainder((double)num + (double)Main.screenPosition.X * this.bgParallax, (double)num) - (double)(num / 2)) - (int)drawOffset.X;
                    this.bgLoops = (Main.screenWidth + (int)drawOffset.X * 2) / num + 2;
                    this.bgTopY = (float)(this.bgStartY + this.bgLoopsY * Main.backgroundHeight[2]);
                    this.hellBlackBoxBottom = this.bgTopY + Main.screenPosition.Y;
                    for (int num12 = 0; num12 < this.bgLoops; num12++)
                    {
                        for (int num13 = 0; num13 < num / 16; num13++)
{
                            float num14 = (float)(this.bgStartX + num * num12 + num13 * 16 + 8);
                            float num15 = this.bgTopY;
                            Microsoft.Xna.Framework.Color color6 = Lighting.GetColor((int)((num14 + Main.screenPosition.X) / 16f), (int)((Main.screenPosition.Y + num15) / 16f));
                            color6.R = (byte)((float)color6.R * x);
                            color6.G = (byte)((float)color6.G * y);
                            color6.B = (byte)((float)color6.B * z);
                            Main.spriteBatch.Draw(TextureAssets.Background[this._drawBackground_backTexture[6]].Value, new Vector2((float)(this.bgStartX + num * num12 + 16 * num13 + num2), this.bgTopY) + drawOffset, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * num13 + num2 + 16, Main.magmaBGFrame * 16, 16, 16)), color6);
                            if (Main.ugBackTransition > 0f)
{
                                Microsoft.Xna.Framework.Color color7 = color6;
                                color7.R = (byte)((float)color7.R * Main.ugBackTransition);
                                color7.G = (byte)((float)color7.G * Main.ugBackTransition);
                                color7.B = (byte)((float)color7.B * Main.ugBackTransition);
                                color7.A = (byte)((float)color7.A * Main.ugBackTransition);
                                Main.spriteBatch.Draw(TextureAssets.Background[this._drawBackground_oldBackTexture[6]].Value, new Vector2((float)(this.bgStartX + num * num12 + 16 * num13 + num2), this.bgTopY) + drawOffset, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * num13 + num2 + 16, Main.magmaBGFrame * 16, 16, 16)), color7);
                            }
                        }
                    }
                }
            }
        }
References Terraria.Tile.active(), Microsoft.Xna.Framework.Color.B, Terraria.GameContent.TextureAssets.Background, Terraria.Main.backgroundHeight, Terraria.Main.caveParallax, System.Math.Ceiling(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Color.G, Terraria.Lighting.GetColor(), Terraria.Lighting.GetColor4Slice(), Terraria.Lighting.GetColor9Slice(), System.Math.IEEERemainder(), int, Terraria.WorldGen.InWorld(), Terraria.Main.magmaBGFrame, Terraria.Main.maxTilesY, Terraria.Lighting.NotRetro, Microsoft.Xna.Framework.Color.R, System.Math.Round(), Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.ShouldDrawBackgroundTileAt(), Terraria.Main.spriteBatch, Terraria.Main.tile, Terraria.Main.ugBackTransition, Terraria.Main.UnderworldLayer, ReLogic.Content.Asset< T >.Value, Terraria.Main.WallLightAt(), Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.