Terraria Decompiled: Terraria.Main.DrawNPC_SlimeItem
DrawNPC_SlimeItem()
static void Terraria.Main.DrawNPC_SlimeItem (NPC rCurrentNPC, int typeCache, Microsoft::Xna::Framework::Color npcColor, float addedRotation) inline static private
Definition at line 25910 of file Main.cs.
        {
            int num = (int)rCurrentNPC.ai[1];
            float num2 = 1f;
            float num3 = 22f * rCurrentNPC.scale;
            float num4 = 18f * rCurrentNPC.scale;
            Texture2D texture2D;
            Microsoft.Xna.Framework.Rectangle rectangle;
            Main.GetItemDrawFrame(num, out texture2D, out rectangle);
            float num5 = (float)rectangle.Width;
            float num6 = (float)rectangle.Height;
            bool flag = (int)rCurrentNPC.ai[0] == -999;
            if (flag)
            {
                num3 = 14f * rCurrentNPC.scale;
                num4 = 14f * rCurrentNPC.scale;
            }
            if (num5 > num3)
            {
                num2 *= num3 / num5;
                num5 *= num2;
                num6 *= num2;
            }
            if (num6 > num4)
            {
                num2 *= num4 / num6;
                num5 *= num2;
                num6 *= num2;
            }
            float num7 = -1f;
            float num8 = 1f;
            int num9 = rCurrentNPC.frame.Y / (TextureAssets.Npc[typeCache].Height() / Main.npcFrameCount[typeCache]);
            float num10 = 0.2f;
            if (rCurrentNPC.type == 537)
            {
                num10 = 0f;
                num9 = 0;
                num8 += 4f;
            }
            num8 -= (float)num9;
            num7 += (float)(num9 * 2);
            num10 -= 0.3f * (float)num9;
            if (flag)
            {
                if (rCurrentNPC.velocity.X < 0f)
                {
                    num10 *= -1f;
                }
                num8 -= 6f;
                if ((double)num2 >= 0.8)
                {
                    num8 -= 1f;
                }
                if (num2 >= 1f)
                {
                    num8 -= 3f;
                }
                if (num == 1345)
                {
                    num8 -= 4f * num2;
                }
                else if (addedRotation < 0f)
                {
                    addedRotation *= 5.5f;
                }
                else
                {
                    addedRotation *= 4.5f;
                }
                if (num == 150)
                {
                    addedRotation *= 2f;
                    num8 -= 3f;
                }
                if (num == 1345)
                {
                    addedRotation *= 5f;
                }
                num7 -= num5 * addedRotation;
            }
            if (num == 75)
            {
                npcColor = new Microsoft.Xna.Framework.Color(255, 255, 255, 0);
                num10 *= 0.3f;
                num8 -= 2f;
            }
            npcColor = rCurrentNPC.GetShimmerColor(npcColor);
            SpriteEffects spriteEffects = SpriteEffects.None;
            if (num == 539 && rCurrentNPC.direction < 0)
            {
                spriteEffects = SpriteEffects.FlipHorizontally;
            }
            Main.spriteBatch.Draw(texture2D, new Vector2(rCurrentNPC.Center.X - Main.screenPosition.X + num7, rCurrentNPC.Center.Y - Main.screenPosition.Y + rCurrentNPC.gfxOffY + num8), new Microsoft.Xna.Framework.Rectangle?(rectangle), npcColor, num10, rectangle.Size() / 2f, num2, spriteEffects, 0f);
        }
References Terraria.NPC.ai, Terraria.Entity.Center, Terraria.Entity.direction, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Main.GetItemDrawFrame(), Terraria.NPC.GetShimmerColor(), Terraria.NPC.gfxOffY, Microsoft.Xna.Framework.Rectangle.Height, int, Terraria.GameContent.TextureAssets.Npc, Terraria.Main.npcFrameCount, Terraria.NPC.scale, Terraria.Main.screenPosition, Terraria.Main.spriteBatch, Terraria.NPC.type, Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Entity.velocity, Microsoft.Xna.Framework.Rectangle.Width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Main.DrawNPCDirect().