Terraria Decompiled: Terraria.Main.GetPlayerArmPosition
GetPlayerArmPosition()
static Vector2 Terraria.Main.GetPlayerArmPosition (Projectile proj, Player theOwner) inline static
Definition at line 37044 of file Main.cs.
        {
            Vector2 vector = Main.OffsetsPlayerOnhand[theOwner.bodyFrame.Y / 56] * 2f;
            if (theOwner.direction != 1)
            {
                vector.X = (float)theOwner.bodyFrame.Width - vector.X;
            }
            if (theOwner.gravDir != 1f)
            {
                vector.Y = (float)theOwner.bodyFrame.Height - vector.Y;
            }
            vector -= new Vector2((float)(theOwner.bodyFrame.Width - theOwner.width), (float)theOwner.bodyFrame.Height - theOwner.BaseHeight) / 2f;
            Vector2 vector2 = theOwner.MountedCenter - new Vector2((float)theOwner.width, theOwner.BaseHeight) / 2f + vector;
            if (theOwner.mount.Active && theOwner.mount.Type == 52)
            {
                vector2.Y -= (float)theOwner.mount.PlayerOffsetHitbox;
                vector2 += new Vector2((float)(12 * theOwner.direction), -12f);
            }
            theOwner.ApplyItemPositionOffsetFromMount(ref vector2);
            return theOwner.RotatedRelativePoint(vector2, false, true);
        }
References Terraria.Mount.Active, Terraria.Player.ApplyItemPositionOffsetFromMount(), Terraria.Player.BaseHeight, Terraria.Player.bodyFrame, Terraria.Entity.direction, Terraria.Player.gravDir, Microsoft.Xna.Framework.Rectangle.Height, Terraria.Player.mount, Terraria.Main.OffsetsPlayerOnhand, Terraria.Mount.PlayerOffsetHitbox, Terraria.Player.RotatedRelativePoint(), Terraria.Mount.Type, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Rectangle.Width, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Projectile.AI_075(), Terraria.Projectile.AI_160_Kites(), Terraria.Projectile.AI_165_Whip(), Terraria.Projectile.AI_DisplayDoll(), Terraria.Main.DrawProj_FlailChains(), Terraria.Main.DrawProjDirect(), and Terraria.Projectile.FillWhipControlPoints().