Terraria Decompiled: Terraria.Main.DrawSurfaceBG_GoodEvilDesert
DrawSurfaceBG_GoodEvilDesert()
void Terraria.Main.DrawSurfaceBG_GoodEvilDesert (float backgroundTopMagicNumber, float bgGlobalScaleMultiplier, int pushBGTopHack, int layerIndex) inline private
Definition at line 61784 of file Main.cs.
        {
            if (layerIndex == 5 && Main.desertBackgroundSet.Corrupt.HasAny)
            {
                this.DrawSurfaceBG_Desert(backgroundTopMagicNumber, bgGlobalScaleMultiplier, pushBGTopHack, Main.desertBackgroundSet.Corrupt.Backgrounds);
                return;
            }
            if (layerIndex == 14 && Main.desertBackgroundSet.Crimson.HasAny)
            {
                this.DrawSurfaceBG_Desert(backgroundTopMagicNumber, bgGlobalScaleMultiplier, pushBGTopHack, Main.desertBackgroundSet.Crimson.Backgrounds);
                return;
            }
            if (layerIndex == 13 && Main.desertBackgroundSet.Hallow.HasAny)
            {
                this.DrawSurfaceBG_Desert(backgroundTopMagicNumber, bgGlobalScaleMultiplier, pushBGTopHack, Main.desertBackgroundSet.Hallow.Backgrounds);
                return;
            }
            this.LoadBackground(26);
            Main.bgScale = 1.25f;
            Main.bgScale *= bgGlobalScaleMultiplier;
            Main.bgWidthScaled = (int)((float)Main.backgroundWidth[26] * Main.bgScale);
            this.bgParallax = 0.37;
            SkyManager.Instance.DrawToDepth(Main.spriteBatch, 1f / (float)this.bgParallax);
            this.bgStartX = (int)(-Math.IEEERemainder((double)Main.screenPosition.X * this.bgParallax, (double)Main.bgWidthScaled) - (double)(Main.bgWidthScaled / 2));
            this.bgTopY = backgroundTopMagicNumber * 1800f + 1750f + this.scAdj + (float)pushBGTopHack;
            if (Main.gameMenu)
            {
                this.bgTopY = (float)(320 + pushBGTopHack);
            }
            this.bgLoops = Main.screenWidth / Main.bgWidthScaled + 2;
            if ((double)Main.screenPosition.Y < Main.worldSurface * 16.0 + 16.0)
            {
                for (int i = 0; i < this.bgLoops; i++)
                {
                    Main.spriteBatch.Draw(TextureAssets.Background[26].Value, new Vector2((float)(this.bgStartX + Main.bgWidthScaled * i), this.bgTopY), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, Main.backgroundWidth[26], Main.backgroundHeight[26])), Main.ColorOfSurfaceBackgroundsModified, 0f, default(Vector2), Main.bgScale, SpriteEffects.None, 0f);
                }
            }
            Main.bgScale = 1.34f;
            Main.bgScale *= bgGlobalScaleMultiplier;
            this.LoadBackground(27);
            Main.bgWidthScaled = (int)((float)Main.backgroundWidth[27] * Main.bgScale);
            this.bgParallax = 0.49;
            SkyManager.Instance.DrawToDepth(Main.spriteBatch, 1f / (float)this.bgParallax);
            this.bgStartX = (int)(-Math.IEEERemainder((double)Main.screenPosition.X * this.bgParallax, (double)Main.bgWidthScaled) - (double)(Main.bgWidthScaled / 2));
            this.bgTopY = backgroundTopMagicNumber * 2100f + 2150f + this.scAdj + (float)pushBGTopHack;
            if (Main.gameMenu)
            {
                this.bgTopY = (float)(480 + pushBGTopHack);
                this.bgStartX -= 120;
            }
            this.bgLoops = Main.screenWidth / Main.bgWidthScaled + 2;
            if ((double)Main.screenPosition.Y < Main.worldSurface * 16.0 + 16.0)
            {
                for (int j = 0; j < this.bgLoops; j++)
                {
                    Main.spriteBatch.Draw(TextureAssets.Background[27].Value, new Vector2((float)(this.bgStartX + Main.bgWidthScaled * j), this.bgTopY), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, Main.backgroundWidth[27], Main.backgroundHeight[27])), Main.ColorOfSurfaceBackgroundsModified, 0f, default(Vector2), Main.bgScale, SpriteEffects.None, 0f);
                }
            }
        }
References Terraria.GameContent.TextureAssets.Background, Terraria.Main.backgroundHeight, Terraria.DataStructures.BackgroundVariant.Backgrounds, Terraria.Main.backgroundWidth, Terraria.Main.bgScale, Terraria.Main.bgWidthScaled, Terraria.Main.ColorOfSurfaceBackgroundsModified, Terraria.DataStructures.BackgroundVariantSet.Corrupt, Terraria.DataStructures.BackgroundVariantSet.Crimson, Terraria.Main.desertBackgroundSet, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Graphics.Effects.SkyManager.DrawToDepth(), Terraria.Main.gameMenu, Terraria.DataStructures.BackgroundVariantSet.Hallow, Terraria.DataStructures.BackgroundVariant.HasAny, System.Math.IEEERemainder(), Terraria.Graphics.Effects.SkyManager.Instance, int, Terraria.Main.screenPosition, Terraria.Main.spriteBatch, ReLogic.Content.Asset< T >.Value, and Microsoft.Xna.Framework.Vector2.X.