Terraria Decompiled: Terraria.Main.DedServ
DedServ()
void Terraria.Main.DedServ () inline
Definition at line 3348 of file Main.cs.
        {
            this.NeverSleep();
            Main.rand = new UnifiedRandom();
            if (Main.autoShutdown)
            {
                string text = "terraria" + Main.rand.Next(int.MaxValue);
                Console.Title = text;
                if (Platform.IsWindows)
                {
                    IntPtr intPtr = Main.FindWindow(null, text);
                    if (intPtr != IntPtr.Zero)
                    {
                        Main.ShowWindow(intPtr, 0);
                    }
                }
            }
            else
            {
                Console.Title = "Terraria Server " + Main.versionNumber2;
            }
            Main.dedServ = true;
            Main.showSplash = false;
            this.Initialize();
            while (Main.worldPathName == null || Main.worldPathName == "")
            {
                bool flag = true;
                while (flag)
                {
                    Main.LoadWorlds();
                    Console.WriteLine(Language.GetTextValue("CLI.Server", Main.versionNumber2));
                    Console.WriteLine("");
                    for (int i = 0; i < Main.WorldList.Count; i++)
                    {
                        WorldFileData worldFileData = Main.WorldList[i];
                        string text2 = Main.WorldList[i].Name;
                        if (!worldFileData.IsValid)
{
                            text2 = "(" + StatusID.Search.GetName(worldFileData.LoadStatus) + ") " + text2;
                        }
                        Console.WriteLine(i + 1 + "\t\t" + text2);
                    }
                    string text3 = Language.GetTextValue("CLI.NewWorld_Command");
                    string text4 = Language.GetTextValue("CLI.DeleteWorld_Example");
                    int num = (Math.Max(Main.newWorldName.Length, text4.Length) + 1) / 8 + 1;
                    text3 = text3 + new string('\t', num - text3.Length / 8) + Language.GetTextValue("CLI.NewWorld_Description");
                    text4 = text4 + new string('\t', num - text4.Length / 8) + Language.GetTextValue("CLI.DeleteWorld_Description");
                    Console.WriteLine(text3);
                    Console.WriteLine(text4);
                    Console.WriteLine("");
                    Console.Write(Language.GetTextValue("CLI.ChooseWorld"));
                    string text5 = Main.ReadLineInput();
                    if (text5 == null)
                    {
                        text5 = "";
                    }
                    try
                    {
                        Console.Clear();
                    }
                    catch
                    {
                    }
                    string text6;
                    if (Language.GetText("CLI.DeleteWorld_Command").ParseCommandPrefix(text5, out text6))
                    {
                        try
{
                            int num2 = Convert.ToInt32(text6) - 1;
                            if (num2 < Main.WorldList.Count)
{
                                Console.WriteLine(Language.GetTextValue("CLI.Server", Main.versionNumber2));
                                Console.WriteLine("");
                                Console.WriteLine(Language.GetTextValue("CLI.DeleteConfirmation", Main.WorldList[num2].Name));
                                Console.Write("({0}/{1}): ", Language.GetTextValue("CLI.ShortYes"), Language.GetTextValue("CLI.ShortNo"));
                                string text7 = Main.ReadLineInput();
                                if (Language.GetText("CLI.ShortYes").EqualsCommand(text7) || Language.GetText("CLI.Yes").EqualsCommand(text7))
{
                                    Main.EraseWorld(num2);
                                }
                            }
                        }
                        catch
{
                        }
                        try
{
                            Console.Clear();
                            continue;
                        }
                        catch
{
                            continue;
                        }
                    }
                    if (Language.GetText("CLI.NewWorld_Command").EqualsCommand(text5))
                    {
                        bool flag2 = true;
                        while (flag2)
{
                            Console.WriteLine(Language.GetTextValue("CLI.Server", Main.versionNumber2));
                            Console.WriteLine("");
                            Console.WriteLine("1\t" + Language.GetTextValue("UI.WorldSizeSmall"));
                            Console.WriteLine("2\t" + Language.GetTextValue("UI.WorldSizeMedium"));
                            Console.WriteLine("3\t" + Language.GetTextValue("UI.WorldSizeLarge"));
                            Console.WriteLine("");
                            Console.Write(Language.GetTextValue("CLI.ChooseSize"));
                            string text8 = Main.ReadLineInput();
                            try
{
                                int num3 = Convert.ToInt32(text8);
                                if (num3 == 1)
{
                                    Main.maxTilesX = 4200;
                                    Main.maxTilesY = 1200;
                                    flag2 = false;
                                }
                                else if (num3 == 2)
{
                                    Main.maxTilesX = 6400;
                                    Main.maxTilesY = 1800;
                                    flag2 = false;
                                }
                                else if (num3 == 3)
{
                                    Main.maxTilesX = 8400;
                                    Main.maxTilesY = 2400;
                                    flag2 = false;
                                }
                            }
                            catch
{
                            }
                            try
{
                                Console.Clear();
                            }
                            catch
{
                            }
                        }
                        flag2 = true;
                        while (flag2)
{
                            Console.WriteLine(Language.GetTextValue("CLI.Server", Main.versionNumber2));
                            Console.WriteLine("");
                            Console.WriteLine("1\t" + Language.GetTextValue("UI.Normal"));
                            Console.WriteLine("2\t" + Language.GetTextValue("UI.Expert"));
                            Console.WriteLine("3\t" + Language.GetTextValue("UI.Master"));
                            Console.WriteLine("4\t" + Language.GetTextValue("UI.Creative"));
                            Console.WriteLine("");
                            Console.Write(Language.GetTextValue("CLI.ChooseDifficulty"));
                            string text8 = Main.ReadLineInput();
                            try
{
                                int num4 = Convert.ToInt32(text8);
                                if (num4 == 1)
{
                                    Main.GameMode = 0;
                                    flag2 = false;
                                }
                                else if (num4 == 2)
{
                                    Main.GameMode = 1;
                                    flag2 = false;
                                }
                                else if (num4 == 3)
{
                                    Main.GameMode = 2;
                                    flag2 = false;
                                }
                                else if (num4 == 4)
{
                                    Main.GameMode = 3;
                                    flag2 = false;
                                }
                            }
                            catch
{
                            }
                            try
{
                                Console.Clear();
                            }
                            catch
{
                            }
                        }
                        flag2 = true;
                        while (flag2)
{
                            Console.WriteLine(Language.GetTextValue("CLI.Server", Main.versionNumber2));
                            Console.WriteLine("");
                            Console.WriteLine("1\t" + Language.GetTextValue("CLI.Random"));
                            Console.WriteLine("2\t" + Language.GetTextValue("CLI.Corrupt"));
                            Console.WriteLine("3\t" + Language.GetTextValue("CLI.Crimson"));
                            Console.WriteLine("");
                            Console.Write(Language.GetTextValue("CLI.ChooseEvil"));
                            string text8 = Main.ReadLineInput();
                            try
{
                                int num5 = Convert.ToInt32(text8);
                                if (num5 == 1)
{
                                    WorldGen.WorldGenParam_Evil = -1;
                                    flag2 = false;
                                }
                                else if (num5 == 2)
{
                                    WorldGen.WorldGenParam_Evil = 0;
                                    flag2 = false;
                                }
                                else if (num5 == 3)
{
                                    WorldGen.WorldGenParam_Evil = 1;
                                    flag2 = false;
                                }
                            }
                            catch
{
                            }
                            try
{
                                Console.Clear();
                            }
                            catch
{
                            }
                        }
                        flag2 = true;
                        Console.WriteLine(Language.GetTextValue("CLI.Server", Main.versionNumber2));
                        while (flag2)
{
                            Console.WriteLine("");
                            Console.Write(Language.GetTextValue("CLI.EnterWorldName"));
                            Main.newWorldName = Main.ReadLineInput();
                            if (Main.newWorldName != null && Main.newWorldName != "" && Main.newWorldName != " ")
{
                                if (Main.newWorldName.Length >= 27)
{
                                    Console.WriteLine("");
                                    Console.WriteLine(Language.GetTextValue("CLI.WorldNameLengthTooLong", 26));
                                    continue;
                                }
                                flag2 = false;
                                try
{
                                    Console.Clear();
                                    continue;
                                }
                                catch
{
                                    continue;
                                }
                            }
                            try
{
                                Console.Clear();
                            }
                            catch
{
                            }
                            Console.WriteLine(Language.GetTextValue("CLI.Server", Main.versionNumber2));
                        }
                        string text9 = "";
                        flag2 = true;
                        Console.WriteLine(Language.GetTextValue("CLI.Server", Main.versionNumber2));
                        string text10;
                        List<string> list;
                        while (flag2)
{
                            Console.WriteLine("");
                            Console.Write(Language.GetTextValue("CLI.EnterSeed"));
                            text9 = Main.ReadLineInput();
                            if (text9 != null)
{
                                text9 = text9.Trim();
                                if (!WorldFileData.TryApplyingCopiedSeed(text9, false, out text10, out text10, out list) && text9.Length > WorldFileData.MAX_USER_SEED_TEXT_LENGTH)
{
                                    Console.WriteLine("");
                                    Console.WriteLine(Language.GetTextValue("CLI.SeedLengthTooLong", WorldFileData.MAX_USER_SEED_TEXT_LENGTH));
                                    continue;
                                }
                                WorldGen.SecretSeed secretSeed;
                                if (WorldGen.SecretSeed.CheckInputForSecretSeed(text9, out secretSeed))
{
                                    WorldGen.SecretSeed.Enable(secretSeed, true);
                                    Console.WriteLine("");
                                    Console.WriteLine(Language.GetTextValue("CLI.SecretSeedEnabled"));
                                    continue;
                                }
                                flag2 = false;
                                try
{
                                    Console.Clear();
                                    continue;
                                }
                                catch
{
                                    continue;
                                }
                            }
                            text9 = "";
                        }
                        Main.worldName = Main.newWorldName;
                        Main.ActiveWorldFileData = WorldFile.CreateMetadata(Main.worldName, SocialAPI.Cloud != null && SocialAPI.Cloud.EnabledByDefault, Main.GameMode);
                        string text11;
                        if (WorldFileData.TryApplyingCopiedSeed(text9, true, out text10, out text11, out list))
{
                            Main.ActiveWorldFileData.SetSeed(text11);
                        }
                        else
{
                            AWorldGenerationOption optionFromSeedText = WorldGenerationOptions.GetOptionFromSeedText(text9);
                            WorldGenerationOptions.SelectOption(optionFromSeedText);
                            if (optionFromSeedText != null || string.IsNullOrWhiteSpace(text9))
{
                                Main.ActiveWorldFileData.SetSeedToRandomWithCurrentEvents();
                            }
                            else
{
                                Main.ActiveWorldFileData.SetSeed(text9);
                            }
                            Main.DedServ_SeedFlagsMenu();
                        }
                        Main.menuMode = 10;
                        GenerationProgress generationProgress = new GenerationProgress();
                        Task task = WorldGen.CreateNewWorld(generationProgress, null, null);
                        flag2 = false;
                        while (Main.menuMode == 10)
{
                            if (Main.oldStatusText != Main.statusText && !WorldGen.drunkWorldGen)
{
                                Main.oldStatusText = Main.statusText;
                                Console.WriteLine(Main.statusText);
                            }
                        }
                        try
{
                            Console.Clear();
                            goto IL_091F;
                        }
                        catch
{
                            goto IL_091F;
                        }
                        goto IL_0878;
                        IL_091F:
                        if (task.IsCompleted)
{
                            continue;
                        }
                        IL_0878:
                        Main.statusText = string.Format("{0:0.0%} - " + generationProgress.Message + " - {1:0.0%}", generationProgress.TotalProgress, generationProgress.Value);
                        if (Main.oldStatusText != Main.statusText)
{
                            Main.oldStatusText = Main.statusText;
                            string text12 = Main.statusText;
                            if (WorldGen.notTheBees && !WorldGen.getGoodWorldGen)
{
                                text12 = string.Format("{0:0.0%} - " + Language.GetTextValue("UI.WorldGenEasterEgg_GeneratingBees") + " - {1:0.0%}", generationProgress.TotalProgress, generationProgress.Value);
                            }
                            Console.WriteLine(text12);
                            goto IL_091F;
                        }
                        goto IL_091F;
                    }
                    else
                    {
                        try
{
                            int num6 = Convert.ToInt32(text5);
                            num6--;
                            if (num6 >= 0 && num6 < Main.WorldList.Count && Main.WorldList[num6].IsValid)
{
                                bool flag3 = true;
                                while (flag3)
{
                                    Console.WriteLine(Language.GetTextValue("CLI.Server", Main.versionNumber2));
                                    Console.WriteLine("");
                                    Console.Write(Language.GetTextValue("CLI.SetInitialMaxPlayers"));
                                    string text13 = Main.ReadLineInput();
                                    try
{
                                        if (text13 == "")
{
                                            text13 = "16";
                                        }
                                        int num7 = Convert.ToInt32(text13);
                                        if (num7 <= 255 && num7 >= 1)
{
                                            this.SetNetPlayers(num7);
                                            flag3 = false;
                                        }
                                        flag3 = false;
                                    }
                                    catch
{
                                    }
                                    try
{
                                        Console.Clear();
                                    }
                                    catch
{
                                    }
                                }
                                flag3 = true;
                                while (flag3)
{
                                    Console.WriteLine(Language.GetTextValue("CLI.Server", Main.versionNumber2));
                                    Console.WriteLine("");
                                    Console.Write(Language.GetTextValue("CLI.SetInitialPort"));
                                    string text14 = Main.ReadLineInput();
                                    try
{
                                        if (text14 == "")
{
                                            text14 = "7777";
                                        }
                                        int num8 = Convert.ToInt32(text14);
                                        if (num8 <= 65535)
{
                                            Netplay.ListenPort = num8;
                                            flag3 = false;
                                        }
                                    }
                                    catch
{
                                    }
                                    try
{
                                        Console.Clear();
                                    }
                                    catch
{
                                    }
                                }
                                flag3 = true;
                                while (flag3)
{
                                    Console.WriteLine(Language.GetTextValue("CLI.Server", Main.versionNumber2));
                                    Console.WriteLine("");
                                    Console.Write(Language.GetTextValue("CLI.AutomaticPortForward", Language.GetTextValue("CLI.ShortYes"), Language.GetTextValue("CLI.ShortNo")));
                                    string text15 = Main.ReadLineInput();
                                    try
{
                                        if (text15 == "" || Language.GetText("CLI.ShortYes").EqualsCommand(text15) || Language.GetText("CLI.Yes").EqualsCommand(text15))
{
                                            Netplay.UseUPNP = true;
                                            flag3 = false;
                                        }
                                        else if (Language.GetText("CLI.ShortNo").EqualsCommand(text15) || Language.GetText("CLI.No").EqualsCommand(text15))
{
                                            Netplay.UseUPNP = false;
                                            flag3 = false;
                                        }
                                    }
                                    catch
{
                                    }
                                    try
{
                                        Console.Clear();
                                    }
                                    catch
{
                                    }
                                }
                                Console.WriteLine(Language.GetTextValue("CLI.Server", Main.versionNumber2));
                                Console.WriteLine("");
                                Console.Write(Language.GetTextValue("CLI.EnterServerPassword"));
                                Netplay.ServerPassword = Main.ReadLineInput();
                                Main.WorldList[num6].SetAsActive();
                                flag = false;
                                try
{
                                    Console.Clear();
                                }
                                catch
{
                                }
                            }
                        }
                        catch
{
                        }
                    }
                }
            }
            try
            {
                Console.Clear();
            }
            catch
            {
            }
            Task task2 = WorldGen.serverLoadWorld();
            Console.WriteLine(Language.GetTextValue("CLI.Server", Main.versionNumber));
            Console.WriteLine("");
            while (!task2.IsCompleted)
            {
                if (WorldFile.LastThrownLoadException == null)
                {
                    if (Main.AutogenProgress.TotalProgress != 0.0)
                    {
                        Main.statusText = string.Format("{0:0.0%} - " + Main.AutogenProgress.Message + " - {1:0.0%}", Main.AutogenProgress.TotalProgress, Main.AutogenProgress.Value);
                    }
                    if (Main.oldStatusText != Main.statusText)
                    {
                        Main.oldStatusText = Main.statusText;
                        Console.WriteLine(Main.statusText);
                    }
                }
            }
            try
            {
                if (WorldFile.LastThrownLoadException == null)
                {
                    Console.Clear();
                }
            }
            catch
            {
            }
            if (WorldGen.loadFailed)
            {
                Main.WriteFancyWorldLoadErrorToConsole();
                if (!Main.autoShutdown)
                {
                    Console.ReadKey();
                }
                this.YouCanSleepNow();
                return;
            }
            Console.WriteLine(Language.GetTextValue("CLI.Server", Main.versionNumber));
            Console.WriteLine("");
            Console.WriteLine(Language.GetTextValue("CLI.ListeningOnPort", Netplay.ListenPort));
            Console.WriteLine(Language.GetTextValue("CLI.HelpHint"));
            Console.WriteLine("");
            Console.Title = "Terraria Server: " + Main.worldName;
            Stopwatch stopwatch = new Stopwatch();
            if (!Main.autoShutdown)
            {
                Main.startDedInput();
            }
            stopwatch.Start();
            double num9 = 16.666666666666668;
            double num10 = 0.0;
            int num11 = 0;
            new Stopwatch().Start();
            Netplay.StartServer();
            Main.gameMenu = false;
            while (!Netplay.Disconnect)
            {
                double totalMilliseconds = stopwatch.Elapsed.TotalMilliseconds;
                if (totalMilliseconds + num10 >= num9)
                {
                    num11++;
                    num10 += totalMilliseconds - num9;
                    stopwatch.Reset();
                    stopwatch.Start();
                    if (Main.oldStatusText != Main.statusText)
                    {
                        Main.oldStatusText = Main.statusText;
                        Console.WriteLine(Main.statusText);
                    }
                    if (Netplay.HasClients)
                    {
                        DetailedFPS.StartNextFrame();
                        this.Update(new GameTime());
                    }
                    else
                    {
                        if (Main.OnTickForThirdPartySoftwareOnly != null)
{
                            Main.OnTickForThirdPartySoftwareOnly();
                        }
                        if (Main.saveTime.IsRunning)
{
                            Main.saveTime.Stop();
                            if (!Main.autoShutdown)
{
                                WorldGen.saveAndPlay();
                            }
                        }
                    }
                    double num12 = stopwatch.Elapsed.TotalMilliseconds + num10;
                    if (num12 < num9)
                    {
                        int num13 = (int)(num9 - num12) - 1;
                        if (num13 > 1)
{
                            Thread.Sleep(num13 - 1);
                            if (!Netplay.HasClients)
{
                                num10 = 0.0;
                                Thread.Sleep(10);
                            }
                        }
                    }
                }
                Thread.Sleep(0);
            }
            if (Netplay.SaveOnServerExit)
            {
                Console.WriteLine(Language.GetTextValue("Net.ServerSavingOnExit"));
                WorldFile.SaveWorld(false, false, false);
            }
            this.YouCanSleepNow();
        }
References Terraria.Main.ActiveWorldFileData, Terraria.Main.AutogenProgress, Terraria.Main.autoShutdown, Terraria.WorldGen.SecretSeed.CheckInputForSecretSeed(), System.Console.Clear(), Terraria.Social.SocialAPI.Cloud, System.Collections.Generic.List< T >.Count, Terraria.IO.WorldFile.CreateMetadata(), Terraria.WorldGen.CreateNewWorld(), Terraria.Main.DedServ_SeedFlagsMenu(), Terraria.Netplay.Disconnect, Terraria.WorldGen.drunkWorldGen, Terraria.WorldGen.SecretSeed.Enable(), Terraria.Localization.LocalizedText.EqualsCommand(), Terraria.Main.EraseWorld(), Terraria.Main.FindWindow(), Terraria.Main.GameMode, Terraria.WorldGen.getGoodWorldGen, Terraria.WorldBuilding.WorldGenerationOptions.GetOptionFromSeedText(), Terraria.Localization.Language.GetText(), Terraria.Localization.Language.GetTextValue(), Terraria.Netplay.HasClients, Terraria.Main.Initialize(), int, System.Threading.Tasks.Task< TResult >.IsCompleted, Terraria.IO.WorldFileData.IsValid, ReLogic.OS.Platform.IsWindows, Terraria.IO.WorldFile.LastThrownLoadException, System.list, Terraria.Netplay.ListenPort, Terraria.WorldGen.loadFailed, Terraria.IO.WorldFileData.LoadStatus, Terraria.Main.LoadWorlds(), System.Math.Max(), Terraria.IO.WorldFileData.MAX_USER_SEED_TEXT_LENGTH, System.Reflection.MaxValue, Terraria.Main.menuMode, Terraria.WorldBuilding.GenerationProgress.Message, Terraria.Main.NeverSleep(), Terraria.Main.newWorldName, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.notTheBees, Terraria.Main.oldStatusText, Terraria.Main.OnTickForThirdPartySoftwareOnly, Terraria.Localization.LocalizedText.ParseCommandPrefix(), Terraria.Main.rand, System.Console.ReadKey(), Terraria.Main.ReadLineInput(), Terraria.WorldGen.saveAndPlay(), Terraria.Netplay.SaveOnServerExit, Terraria.Main.saveTime, Terraria.IO.WorldFile.SaveWorld(), Terraria.ID.StatusID.Search, Terraria.WorldBuilding.WorldGenerationOptions.SelectOption(), Terraria.WorldGen.serverLoadWorld(), Terraria.Main.SetNetPlayers(), Terraria.IO.WorldFileData.SetSeed(), Terraria.IO.WorldFileData.SetSeedToRandomWithCurrentEvents(), Terraria.Main.ShowWindow(), System.Threading.Thread.Sleep(), Terraria.Main.startDedInput(), Terraria.Testing.DetailedFPS.StartNextFrame(), Terraria.Netplay.StartServer(), Terraria.Main.statusText, System.task, System.text, System.Convert.ToInt32(), Terraria.WorldBuilding.GenerationProgress.TotalProgress, Terraria.IO.WorldFileData.TryApplyingCopiedSeed(), Terraria.Main.Update(), Terraria.WorldBuilding.GenerationProgress.Value, Terraria.Main.versionNumber, Terraria.Main.versionNumber2, Terraria.Main.WorldList, Terraria.Main.worldName, Terraria.Main.worldPathName, System.Console.Write(), Terraria.Main.WriteFancyWorldLoadErrorToConsole(), System.Console.WriteLine(), Terraria.Main.YouCanSleepNow(), and System.IntPtr.Zero.
Referenced by Terraria.Program.RunGame().