Terraria Decompiled: Terraria.Main.snowing
snowing()
static void Terraria.Main.snowing () inline static
Definition at line 11534 of file Main.cs.
        {
            if (Main.remixWorld)
            {
                return;
            }
            Vector2 scaledSize = Main.Camera.ScaledSize;
            Vector2 scaledPosition = Main.Camera.ScaledPosition;
            if (Main.gamePaused)
            {
                return;
            }
            if (Main.SceneMetrics.SnowTileCount > 0 && Main.SceneMetrics.SurfaceAtmospherics)
            {
                float num = (float)Main.SceneMetrics.SnowTileCount / (float)SceneMetrics.SnowTileMax;
                float num2 = 4f - Main.cloudAlpha * 3f;
                num = (float)Math.Pow((double)num, (double)num2);
                float num3 = Main.Camera.ScaledSize.X / (float)Main.maxScreenW;
                int num4 = (int)(500f * num3);
                num4 = (int)((float)num4 * (1f + 2f * Main.cloudAlpha));
                float num5 = 1f + 50f * Main.cloudAlpha;
                bool flag = NPC.IsADeerclopsNearScreen();
                if (flag)
                {
                    num /= 20f;
                    num4 /= 3;
                }
                int num6 = 0;
                while ((float)num6 < num5)
                {
                    try
                    {
                        if ((float)Main.snowDust >= (float)num4 * (Main.gfxQuality / 2f + 0.5f) + (float)num4 * 0.1f)
{
                            break;
                        }
                        if (Main.rand.NextFloat() < num)
{
                            int num7 = Main.rand.Next((int)scaledSize.X + 1500) - 750;
                            int num8 = (int)scaledPosition.Y - Main.rand.Next(50);
                            if (Main.player[Main.myPlayer].velocity.Y > 0f)
{
                                num8 -= (int)Main.player[Main.myPlayer].velocity.Y;
                            }
                            if (Main.rand.Next(5) == 0)
{
                                num7 = Main.rand.Next(500) - 500;
                            }
                            else if (Main.rand.Next(5) == 0)
{
                                num7 = Main.rand.Next(500) + (int)scaledSize.X;
                            }
                            if (num7 < 0 || (float)num7 > scaledSize.X)
{
                                num8 += Main.rand.Next((int)((double)scaledSize.Y * 0.8)) + (int)((double)scaledSize.Y * 0.1);
                            }
                            num7 += (int)scaledPosition.X;
                            int num9 = num7 / 16;
                            int num10 = num8 / 16;
                            if (WorldGen.InWorld(num9, num10, 0))
{
                                if (Main.tile[num9, num10] != null && !Main.tile[num9, num10].nactive() && Main.tile[num9, num10].wall == 0)
{
                                    int num11 = Dust.NewDust(new Vector2((float)num7, (float)num8), 10, 10, 76, 0f, 0f, 0, default(Microsoft.Xna.Framework.Color), 1f);
                                    Main.dust[num11].scale += Main.cloudAlpha * 0.2f;
                                    Main.dust[num11].velocity.Y = 3f + (float)Main.rand.Next(30) * 0.1f;
                                    Dust dust = Main.dust[num11];
                                    dust.velocity.Y = dust.velocity.Y * Main.dust[num11].scale;
                                    if (!Main.raining)
{
                                        Main.dust[num11].velocity.X = Main.windSpeedCurrent + (float)Main.rand.Next(-10, 10) * 0.1f;
                                        Dust dust2 = Main.dust[num11];
                                        dust2.velocity.X = dust2.velocity.X + Main.windSpeedCurrent * 15f;
                                    }
                                    else
{
                                        Main.dust[num11].velocity.X = (float)Math.Sqrt((double)Math.Abs(Main.windSpeedCurrent)) * (float)Math.Sign(Main.windSpeedCurrent) * (Main.cloudAlpha + 0.5f) * 10f + Main.rand.NextFloat() * 0.2f - 0.1f;
                                        Dust dust3 = Main.dust[num11];
                                        dust3.velocity.Y = dust3.velocity.Y * 0.5f;
                                    }
                                    Dust dust4 = Main.dust[num11];
                                    dust4.velocity.Y = dust4.velocity.Y * (1f + 0.3f * Main.cloudAlpha);
                                    Main.dust[num11].scale += Main.cloudAlpha * 0.2f;
                                    if (flag)
{
                                        Main.dust[num11].scale -= 0.5f;
                                    }
                                    Main.dust[num11].velocity *= 1f + Main.cloudAlpha * 0.5f;
                                }
                            }
                        }
                    }
                    catch
                    {
                    }
                    num6++;
                }
            }
        }
References System.Math.Abs(), Terraria.Main.Camera, Terraria.Main.cloudAlpha, Terraria.Main.dust, Terraria.Main.gamePaused, Terraria.Main.gfxQuality, int, Terraria.WorldGen.InWorld(), Terraria.NPC.IsADeerclopsNearScreen(), Terraria.Main.maxScreenW, Terraria.Main.myPlayer, Terraria.Tile.nactive(), Terraria.Dust.NewDust(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.player, System.Math.Pow(), Terraria.Main.raining, Terraria.Main.rand, Terraria.Main.remixWorld, Terraria.Dust.scale, Terraria.Graphics.Camera.ScaledPosition, Terraria.Graphics.Camera.ScaledSize, Terraria.Main.SceneMetrics, System.Math.Sign(), Terraria.SceneMetrics.SnowTileCount, Terraria.SceneMetrics.SnowTileMax, System.Math.Sqrt(), Terraria.SceneMetrics.SurfaceAtmospherics, Terraria.Main.tile, Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Dust.velocity, Terraria.Entity.velocity, Terraria.Tile.wall, Terraria.Main.windSpeedCurrent, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Main.DoUpdate().