Terraria Decompiled: Terraria.Main.DoDraw_Waterfalls
DoDraw_Waterfalls()
void Terraria.Main.DoDraw_Waterfalls () inline private
Definition at line 64364 of file Main.cs.
        {
            if (DebugOptions.hideWater)
            {
                return;
            }
            TimeLogger.StartTimestamp startTimestamp = TimeLogger.Start();
            Main.tileBatch.Begin(Main.Rasterizer, Main.Transform);
            this.waterfallManager.Draw();
            Main.tileBatch.End();
            TimeLogger.Waterfalls.AddTime(startTimestamp);
        }
References Terraria.Graphics.TileBatch.Begin(), Terraria.Graphics.TileBatch.End(), Terraria.Testing.DebugOptions.hideWater, Terraria.Main.Rasterizer, Terraria.TimeLogger.Start(), Terraria.Main.tileBatch, Terraria.Main.Transform, and Terraria.TimeLogger.Waterfalls.