Terraria Decompiled: Terraria.Main.DrawWhip
DrawWhip()
void Terraria.Main.DrawWhip (Projectile proj, Player theOwner) inline private
Definition at line 35368 of file Main.cs.
        {
            List<Vector2> list = new List<Vector2>();
            Projectile.FillWhipControlPoints(proj, list, theOwner, false);
            Texture2D value = TextureAssets.FishingLine.Value;
            Microsoft.Xna.Framework.Rectangle rectangle = value.Frame(1, 1, 0, 0, 0, 0);
            Vector2 vector = new Vector2((float)(rectangle.Width / 2), 2f);
            Microsoft.Xna.Framework.Color color = Microsoft.Xna.Framework.Color.White;
            bool flag = false;
            bool flag2 = true;
            bool flag3 = false;
            int num = proj.type;
            if (num <= 915)
            {
                switch (num)
                {
                case 847:
                    color = Microsoft.Xna.Framework.Color.OrangeRed;
                    break;
                case 848:
                    color = Microsoft.Xna.Framework.Color.DarkBlue;
                    break;
                case 849:
                    color = Microsoft.Xna.Framework.Color.SlateBlue;
                    color = Microsoft.Xna.Framework.Color.Black;
                    break;
                default:
                    switch (num)
                    {
                    case 912:
                        color = Microsoft.Xna.Framework.Color.LightBlue;
                        break;
                    case 913:
                        color = Microsoft.Xna.Framework.Color.Firebrick;
                        break;
                    case 914:
                        color = Microsoft.Xna.Framework.Color.ForestGreen;
                        break;
                    case 915:
                        color = Microsoft.Xna.Framework.Color.White;
                        break;
                    }
                    break;
                }
            }
            else if (num != 952)
            {
                switch (num)
                {
                case 1028:
                    flag = true;
                    color = Microsoft.Xna.Framework.Color.Gray;
                    break;
                case 1029:
                    flag = true;
                    color = Microsoft.Xna.Framework.Color.Purple;
                    break;
                case 1030:
                    flag = true;
                    color = Microsoft.Xna.Framework.Color.Red;
                    break;
                case 1031:
                    flag = true;
                    color = new Microsoft.Xna.Framework.Color(88, 85, 155);
                    break;
                case 1032:
                    flag = true;
                    color = new Microsoft.Xna.Framework.Color(143, 215, 29);
                    break;
                case 1033:
                    flag = true;
                    color = Microsoft.Xna.Framework.Color.Blue;
                    break;
                case 1034:
                    flag = true;
                    color = Main.hslToRgb(0.6f, 1f, 0.5f, 20) * 0.6f;
                    flag3 = true;
                    break;
                case 1035:
                    flag = true;
                    color = Microsoft.Xna.Framework.Color.Lime;
                    flag2 = false;
                    break;
                default:
                    if (num == 1104)
                    {
                        color = new Microsoft.Xna.Framework.Color(78, 136, 255);
                    }
                    break;
                }
            }
            else
            {
                color = Microsoft.Xna.Framework.Color.Tan;
            }
            Vector2 vector2 = list[0];
            int num2 = list.Count - 1;
            if (flag)
            {
                num2--;
            }
            if (flag2)
            {
                for (int i = 0; i < num2; i++)
                {
                    Vector2 vector3 = list[i];
                    Vector2 vector4 = list[i + 1] - vector3;
                    float num3 = vector4.ToRotation() - 1.5707964f;
                    Microsoft.Xna.Framework.Color color2 = Lighting.GetColor(vector3.ToTileCoordinates(), color);
                    Vector2 vector5 = new Vector2(1f, (vector4.Length() + 2f) / (float)rectangle.Height);
                    if (flag3)
                    {
                        color2 = color;
                    }
                    if (proj.type == 1104)
                    {
                        color2 *= 0.5f;
                    }
                    Main.spriteBatch.Draw(value, vector2 - Main.screenPosition, new Microsoft.Xna.Framework.Rectangle?(rectangle), color2, num3, vector, vector5, SpriteEffects.None, 0f);
                    vector2 += vector4;
                }
            }
            num = proj.type;
            if (num <= 915)
            {
                if (num == 841)
                {
                    vector2 = Main.DrawWhip_WhipBland(proj, list);
                    return;
                }
                switch (num)
                {
                case 847:
                    vector2 = Main.DrawWhip_WhipSword(proj, list);
                    return;
                case 848:
                    vector2 = Main.DrawWhip_WhipMace(proj, list);
                    return;
                case 849:
                    vector2 = Main.DrawWhip_WhipScythe(proj, list);
                    return;
                default:
                    switch (num)
                    {
                    case 912:
                        vector2 = Main.DrawWhip_CoolWhip(proj, list);
                        return;
                    case 913:
                        vector2 = Main.DrawWhip_FireWhip(proj, list);
                        return;
                    case 914:
                        vector2 = Main.DrawWhip_ThornWhip(proj, list);
                        return;
                    case 915:
                        vector2 = Main.DrawWhip_RainbowWhip(proj, theOwner, list);
                        return;
                    default:
                        return;
                    }
                    break;
                }
            }
            else
            {
                if (num == 952)
                {
                    vector2 = Main.DrawWhip_BoneWhip(proj, list);
                    return;
                }
                switch (num)
                {
                case 1028:
                    vector2 = Main.DrawWhip_GenericWhip(proj, list, 6, 1f, 1f);
                    return;
                case 1029:
                    vector2 = Main.DrawWhip_GenericWhip(proj, list, 6, 0.5f, 1f);
                    return;
                case 1030:
                    vector2 = Main.DrawWhip_GenericWhip(proj, list, 6, 0.5f, 1f);
                    return;
                case 1031:
                    vector2 = Main.DrawWhip_MeteorWhip(proj, list);
                    return;
                case 1032:
                    vector2 = Main.DrawWhip_FlowerWhip(proj, list, 5, 0.5f, 1f);
                    return;
                case 1033:
                    vector2 = Main.DrawWhip_EelWhip(proj, list);
                    return;
                case 1034:
                    vector2 = Main.DrawWhip_Constellation(proj, list, 6, 1f, 1f);
                    return;
                case 1035:
                    vector2 = Main.DrawWhip_MoonLordWhip(proj, list);
                    return;
                default:
                    if (num != 1104)
                    {
                        return;
                    }
                    vector2 = Main.DrawWhip_SlimeWhip(proj, list);
                    return;
                }
            }
        }
References Microsoft.Xna.Framework.Color.Black, Microsoft.Xna.Framework.Color.Blue, Microsoft.Xna.Framework.Color.DarkBlue, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Main.DrawWhip_BoneWhip(), Terraria.Main.DrawWhip_Constellation(), Terraria.Main.DrawWhip_CoolWhip(), Terraria.Main.DrawWhip_EelWhip(), Terraria.Main.DrawWhip_FireWhip(), Terraria.Main.DrawWhip_FlowerWhip(), Terraria.Main.DrawWhip_GenericWhip(), Terraria.Main.DrawWhip_MeteorWhip(), Terraria.Main.DrawWhip_MoonLordWhip(), Terraria.Main.DrawWhip_RainbowWhip(), Terraria.Main.DrawWhip_SlimeWhip(), Terraria.Main.DrawWhip_ThornWhip(), Terraria.Main.DrawWhip_WhipBland(), Terraria.Main.DrawWhip_WhipMace(), Terraria.Main.DrawWhip_WhipScythe(), Terraria.Main.DrawWhip_WhipSword(), Terraria.Projectile.FillWhipControlPoints(), Microsoft.Xna.Framework.Color.Firebrick, Terraria.GameContent.TextureAssets.FishingLine, Microsoft.Xna.Framework.Color.ForestGreen, Terraria.Lighting.GetColor(), Microsoft.Xna.Framework.Color.Gray, Microsoft.Xna.Framework.Rectangle.Height, Terraria.Main.hslToRgb(), Microsoft.Xna.Framework.Vector2.Length(), Microsoft.Xna.Framework.Color.LightBlue, Microsoft.Xna.Framework.Color.Lime, System.list, Microsoft.Xna.Framework.Color.OrangeRed, Microsoft.Xna.Framework.Color.Purple, Microsoft.Xna.Framework.Color.Red, Terraria.Main.screenPosition, Microsoft.Xna.Framework.Color.SlateBlue, Terraria.Main.spriteBatch, Microsoft.Xna.Framework.Color.Tan, Terraria.Projectile.type, System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Color.White, and Microsoft.Xna.Framework.Rectangle.Width.