Terraria Decompiled: Terraria.Main.TryMovingNPC
TryMovingNPC()
void Terraria.Main.TryMovingNPC (int x, int y, int selectedNPC) inline
Definition at line 45293 of file Main.cs.
        {
            if (WorldGen.MoveTownNPC(x, y, selectedNPC, null))
            {
                this.SetMouseNPC(-1, -1);
                WorldGen.moveRoom(x, y, selectedNPC);
                SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
            }
        }
References Terraria.WorldGen.moveRoom(), Terraria.WorldGen.MoveTownNPC(), and Terraria.Audio.SoundEngine.PlaySound().