Terraria Decompiled: Terraria.Main.NPCChatText_DyeTraderRarePlant
NPCChatText_DyeTraderRarePlant()
static void Terraria.Main.NPCChatText_DyeTraderRarePlant () inline static
Definition at line 39737 of file Main.cs.
        {
            Main.npcChatCornerItem = 0;
            SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
            bool flag = false;
            int num = Main.player[Main.myPlayer].FindItem(ItemID.Sets.ExoticPlantsForDyeTrade);
            if (num != -1)
            {
                Main.player[Main.myPlayer].inventory[num].stack--;
                if (Main.player[Main.myPlayer].inventory[num].stack <= 0)
                {
                    Main.player[Main.myPlayer].inventory[num] = new Item();
                }
                flag = true;
                SoundEngine.PlaySound(24, -1, -1, 1, 1f, 0f);
                Main.player[Main.myPlayer].GetDyeTraderReward(Main.npc[Main.player[Main.myPlayer].talkNPC]);
            }
            Main.npcChatText = Lang.DyeTraderQuestChat(flag);
        }
References Terraria.Lang.DyeTraderQuestChat(), Terraria.ID.ItemID.Sets.ExoticPlantsForDyeTrade, Terraria.Player.FindItem(), Terraria.Player.GetDyeTraderReward(), Terraria.Player.inventory, Terraria.Main.myPlayer, Terraria.Main.npc, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Item.stack, and Terraria.Player.talkNPC.
Referenced by Terraria.GameContent.NPCInteractions.Actions.DyeTraderRarePlant.Interact().