Terraria Decompiled: Terraria.Main.InputTextSign
InputTextSign()
static void Terraria.Main.InputTextSign () inline static
Definition at line 18528 of file Main.cs.
        {
            if (IngameFancyUI.CanShowVirtualKeyboard(1) && UIVirtualKeyboard.KeyboardContext == 1)
            {
                return;
            }
            PlayerInput.WritingText = true;
            Main.instance.HandleIME();
            Main.npcChatText = Main.GetInputText(Main.npcChatText, true);
            if (Main.inputTextEnter)
            {
                byte[] array = new byte[] { 10 };
                Main.npcChatText += Encoding.ASCII.GetString(array);
                return;
            }
            if (Main.inputTextEscape)
            {
                Main.InputTextSignCancel();
            }
        }
References System.array, System.Text.Encoding.ASCII, Terraria.UI.IngameFancyUI.CanShowVirtualKeyboard(), Terraria.Main.GetInputText(), System.Text.Encoding.GetString(), Terraria.Main.HandleIME(), Terraria.Main.inputTextEnter, Terraria.Main.inputTextEscape, Terraria.Main.InputTextSignCancel(), Terraria.Main.instance, Terraria.GameContent.UI.States.UIVirtualKeyboard.KeyboardContext, and Terraria.Main.npcChatText.
Referenced by Terraria.Main.DoUpdate_WhilePaused().