Terraria Decompiled: Terraria.Main.DrawDefenseCounter
DrawDefenseCounter()
static void Terraria.Main.DrawDefenseCounter (int inventoryX, int inventoryY) inline static private
Definition at line 42059 of file Main.cs.
        {
            Vector2 vector = new Vector2((float)(inventoryX - 10 - 47 - 47 - 14), (float)inventoryY + (float)TextureAssets.InventoryBack.Height() * 0.5f);
            Texture2D value = TextureAssets.Extra[58].Value;
            int num = 0;
            Microsoft.Xna.Framework.Color color = Microsoft.Xna.Framework.Color.Transparent;
            float num2 = 3f;
            int statDefense = Main.player[Main.myPlayer].statDefense;
            double num3 = 0.5;
            if (Main.masterMode)
            {
                num3 = 1.0;
            }
            else if (Main.expertMode)
            {
                num3 = 0.75;
            }
            int num4 = (int)Math.Ceiling((double)statDefense * num3);
            float difficulty = Main.Difficulty;
            if (difficulty >= GameDifficultyLevel.Expert)
            {
                num = 1;
                color = new Microsoft.Xna.Framework.Color((int)((byte)Main.DiscoR), (int)((byte)Main.DiscoG), (int)((byte)Main.DiscoB));
            }
            if (difficulty >= GameDifficultyLevel.Master)
            {
                num = 2;
                float num5 = 6f;
                color = new Microsoft.Xna.Framework.Color(255, (int)((byte)(((float)Math.Sin((double)(Main.GlobalTimeWrappedHourly % num5 / num5 * 6.2831855f)) * 0.5f + 0.5f) * 120f)), 0);
            }
            if (num == 0 || statDefense == 0)
            {
                color = Microsoft.Xna.Framework.Color.Transparent;
            }
            color *= Utils.Remap(MathHelper.Clamp((float)Math.Sin((double)(Main.GlobalTimeWrappedHourly % num2 / num2 * 6.2831855f)), 0f, 1f), 0f, 1f, 0.4f, 1f, true);
            Microsoft.Xna.Framework.Rectangle rectangle = value.Frame(3, 2, num, 0, 0, 0);
            Microsoft.Xna.Framework.Rectangle rectangle2 = value.Frame(3, 2, num, 1, 0, 0);
            Vector2 vector2 = rectangle.Size() / 2f;
            Main.spriteBatch.Draw(value, vector, new Microsoft.Xna.Framework.Rectangle?(rectangle), Microsoft.Xna.Framework.Color.White, 0f, vector2, Main.inventoryScale, SpriteEffects.None, 0f);
            if (color != Microsoft.Xna.Framework.Color.Transparent)
            {
                Main.spriteBatch.Draw(value, vector, new Microsoft.Xna.Framework.Rectangle?(rectangle2), color, 0f, vector2, Main.inventoryScale, SpriteEffects.None, 0f);
            }
            string text = statDefense.ToString();
            Vector2 vector3 = FontAssets.MouseText.Value.MeasureString(text);
            Vector2 vector4 = new Vector2(0f, 2f) * Main.inventoryScale;
            ChatManager.DrawColorCodedStringWithShadow(Main.spriteBatch, FontAssets.MouseText.Value, text, vector - vector3 * 0.5f * Main.inventoryScale + vector4, Microsoft.Xna.Framework.Color.White, 0f, Vector2.Zero, new Vector2(Main.inventoryScale), -1f, 2f);
            if (Utils.CenteredRectangle(vector, rectangle.Size()).Contains(new Microsoft.Xna.Framework.Point(Main.mouseX, Main.mouseY)) && !PlayerInput.IgnoreMouseInterface)
            {
                Main.player[Main.myPlayer].mouseInterface = true;
                string text2 = text + " " + Lang.inter[10].Value;
                text2 = text2 + "\n" + Language.GetTextValue("UI.DefenseDamageReduction", num4);
                if (difficulty >= GameDifficultyLevel.Legendary)
                {
                    text2 = text2 + "\n" + Language.GetTextValue("UI.Legendary");
                }
                else if (difficulty >= GameDifficultyLevel.Master)
                {
                    text2 = text2 + "\n" + Language.GetTextValue("UI.Master");
                }
                else if (difficulty >= GameDifficultyLevel.Expert)
                {
                    text2 = text2 + "\n" + Language.GetTextValue("UI.Expert");
                }
                if (!string.IsNullOrEmpty(text2))
                {
                    Main.hoverItemName = text2;
                }
            }
            UILinkPointNavigator.SetPosition(1557, vector + rectangle.Size() * Main.inventoryScale / 4f);
        }
References System.Math.Ceiling(), Terraria.Utils.CenteredRectangle(), Microsoft.Xna.Framework.MathHelper.Clamp(), Microsoft.Xna.Framework.Rectangle.Contains(), Terraria.Main.Difficulty, Terraria.Main.DiscoB, Terraria.Main.DiscoG, Terraria.Main.DiscoR, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.DataStructures.GameDifficultyLevel.Expert, Terraria.Main.expertMode, Terraria.GameContent.TextureAssets.Extra, Terraria.Localization.Language.GetTextValue(), Terraria.GameInput.PlayerInput.IgnoreMouseInterface, int, Terraria.Lang.inter, Terraria.GameContent.TextureAssets.InventoryBack, Terraria.Main.inventoryScale, Terraria.DataStructures.GameDifficultyLevel.Legendary, Terraria.DataStructures.GameDifficultyLevel.Master, Terraria.Main.masterMode, Terraria.Player.mouseInterface, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Main.player, Terraria.Utils.Remap(), Terraria.UI.Gamepad.UILinkPointNavigator.SetPosition(), System.Math.Sin(), Terraria.Main.spriteBatch, Terraria.Player.statDefense, System.text, Microsoft.Xna.Framework.Color.Transparent, System.value, ReLogic.Content.Asset< T >.Value, Terraria.Localization.LocalizedText.Value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Color.White, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.Main.DrawInventory().