Terraria Decompiled: Terraria.Main.DrawUnderworldBackground
DrawUnderworldBackground()
void Terraria.Main.DrawUnderworldBackground (float zoomForPushUp = 1f) inline protected
Definition at line 53233 of file Main.cs.
        {
            if (Main.screenPosition.Y + (float)Main.screenHeight < (float)(Main.maxTilesY - 220) * 16f)
            {
                return;
            }
            Vector2 vector = Main.screenPosition + new Vector2((float)(Main.screenWidth >> 1), (float)(Main.screenHeight >> 1));
            float num = (zoomForPushUp - 1f) * 0.5f * 200f;
            SkyManager.Instance.ResetDepthTracker();
            for (int i = 4; i >= 0; i--)
            {
                Main.DrawUnderworldBackgroundLayer(vector, num, i);
            }
            if (!Main.mapFullscreen)
            {
                SkyManager.Instance.DrawRemainingDepth(Main.spriteBatch);
            }
            this.DrawSurfaceBG_DrawChangeOverlay(12);
        }
References Terraria.Graphics.Effects.SkyManager.DrawRemainingDepth(), Terraria.Main.DrawUnderworldBackgroundLayer(), Terraria.Graphics.Effects.SkyManager.Instance, Terraria.Main.mapFullscreen, Terraria.Main.maxTilesY, Terraria.Graphics.Effects.SkyManager.ResetDepthTracker(), Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Terraria.Main.spriteBatch, Microsoft.Xna.Framework.Graphics.Vector2, and Microsoft.Xna.Framework.Vector2.Y.