Terraria Decompiled: Terraria.Main.OurFavoriteColor
OurFavoriteColor
Microsoft.Xna.Framework.Color Terraria.Main.OurFavoriteColor = new Microsoft.Xna.Framework.Color(255, 231, 69) static
Definition at line 68972 of file Main.cs.
Referenced by Terraria.NPC.AI_047_GolemFist(), Terraria.Projectile.AI_067_FreakingPirates(), Terraria.Projectile.AI_171_GetColor(), Terraria.Projectile.AI_173_GetColor(), Terraria.GameContent.Creative.CreativePowers.ModifyTimeRate.Button_OnMouseOver(), Terraria.GameContent.Creative.CreativePowers.ModifyWindDirectionAndStrength.Button_OnMouseOver(), Terraria.GameContent.Creative.CreativePowers.ModifyRainPower.Button_OnMouseOver(), Terraria.GameContent.Creative.CreativePowers.SpawnRateSliderPerPlayerPower.Button_OnMouseOver(), Terraria.GameContent.Creative.CreativePowersHelper.CreateToggleButton(), Terraria.GameInput.LockOnHelper.Draw(), Terraria.UI.ItemSlot.Draw(), Terraria.Main.DrawBlockReplacementIcon(), Terraria.Main.DrawBuilderAccToggles(), Terraria.UI.ChestUI.DrawButton(), Terraria.UI.AchievementAdvisor.DrawCard(), Terraria.Main.DrawClothesWindow(), Terraria.Main.DrawHairWindow(), Terraria.Main.DrawHotbarLockIcon(), Terraria.Main.DrawInfoAccs(), Terraria.Main.DrawInfoAccs_AdjustInfoTextColorsForNPC(), Terraria.Main.DrawLoadoutButtons(), Terraria.Main.DrawMap(), Terraria.Main.DrawMenu(), Terraria.Main.DrawNPCChatBottomRightItem(), Terraria.Main.DrawNPCDirect_HallowBoss(), Terraria.Main.DrawPageIcons(), Terraria.Main.DrawPaladinsShieldBoundary(), Terraria.Main.DrawProjDirect(), Terraria.Utils.DrawSelectedCraftingBarIndicator(), Terraria.GameContent.UI.Elements.EmoteButton.DrawSelf(), Terraria.Main.DrawTorchBiomeSwapIcon(), Terraria.IngameOptions.DrawValueBar(), Terraria.GameContent.UI.Elements.UIColoredSlider.DrawValueBar(), Terraria.GameContent.Drawing.ParticleOrchestrator.ElderSlimeEffect(), Terraria.DataStructures.RichRoomCheckFeedback.EndScoring(), Terraria.GameContent.UI.States.UIManageControls.ManageBorderGamepadOn(), Terraria.GameContent.UI.States.UIManageControls.ManageBorderGameplayOn(), Terraria.GameContent.UI.States.UIManageControls.ManageBorderKeyboardOn(), Terraria.GameContent.UI.States.UIManageControls.ManageBorderMenuOn(), Terraria.GameContent.UI.Elements.UIWrappedSearchBar.OnStartTakingInput(), Terraria.GameContent.Creative.CreativePowers.APerPlayerTogglePower.ProvidePowerButtons(), and Terraria.GameContent.Creative.CreativePowers.ASharedTogglePower.ProvidePowerButtons().