Terraria Decompiled: Terraria.Main.DrawTorchBiomeSwapIcon
DrawTorchBiomeSwapIcon()
bool Terraria.Main.DrawTorchBiomeSwapIcon (int pivotTopLeftX, int pivotTopLeftY, bool pushSideToolsUp, int gamepadPointOffset) inline private
Definition at line 42534 of file Main.cs.
        {
            if (!Main.playerInventory)
            {
                return false;
            }
            int num = 68 + pivotTopLeftY;
            Player player = Main.player[Main.myPlayer];
            if (pushSideToolsUp)
            {
                num = 47 + pivotTopLeftY;
            }
            float num2 = 0.9f;
            int num3 = 11;
            bool flag = Main.player[Main.myPlayer].builderAccStatus[num3] == 0;
            Texture2D value = TextureAssets.Extra[211].Value;
            Microsoft.Xna.Framework.Rectangle rectangle = value.Frame(4, 1, flag ? 1 : 0, 0, 0, 0);
            bool flag2 = false;
            if (Main.mouseX > pivotTopLeftX && (float)Main.mouseX < (float)pivotTopLeftX + (float)rectangle.Width * num2 && Main.mouseY > num && (float)Main.mouseY < (float)num + (float)rectangle.Height * num2 && !PlayerInput.IgnoreMouseInterface)
            {
                flag2 = true;
                Main.player[Main.myPlayer].mouseInterface = true;
                this.MouseText(flag ? Language.GetTextValue("GameUI.TorchTypeSwapperOn") : Language.GetTextValue("GameUI.TorchTypeSwapperOff"), 0, 0, -1, -1, -1, -1, 0);
                Main.mouseText = true;
                if (Main.mouseLeft && Main.mouseLeftRelease)
                {
                    SoundEngine.PlaySound(22, -1, -1, 1, 1f, 0f);
                    Main.player[Main.myPlayer].builderAccStatus[num3] = (flag ? 1 : 0);
                }
            }
            Vector2 vector = new Vector2((float)pivotTopLeftX, (float)num);
            Main.spriteBatch.Draw(value, vector, new Microsoft.Xna.Framework.Rectangle?(rectangle), Microsoft.Xna.Framework.Color.White, 0f, default(Vector2), num2, SpriteEffects.None, 0f);
            if (flag2)
            {
                Main.spriteBatch.Draw(value, vector, new Microsoft.Xna.Framework.Rectangle?(value.Frame(4, 1, flag ? 3 : 2, 0, 0, 0)), Main.OurFavoriteColor, 0f, default(Vector2), num2, SpriteEffects.None, 0f);
            }
            UILinkPointNavigator.SetPosition(6000 + gamepadPointOffset, vector + rectangle.Size() * 0.65f);
            return flag2;
        }
References Terraria.Player.builderAccStatus, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.GameContent.TextureAssets.Extra, Terraria.Localization.Language.GetTextValue(), Microsoft.Xna.Framework.Rectangle.Height, Terraria.GameInput.PlayerInput.IgnoreMouseInterface, Terraria.Player.mouseInterface, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Main.OurFavoriteColor, Terraria.Main.player, Terraria.Main.playerInventory, Terraria.Audio.SoundEngine.PlaySound(), Terraria.UI.Gamepad.UILinkPointNavigator.SetPosition(), Terraria.Main.spriteBatch, System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, and Microsoft.Xna.Framework.Color.White.