Terraria Decompiled: Terraria.Main.DrawSmartInteract
DrawSmartInteract()
static void Terraria.Main.DrawSmartInteract () inline static private
Definition at line 46863 of file Main.cs.
        {
            if (Main.SmartInteractShowingGenuine && Main.SmartInteractNPC == -1 && Main.SmartInteractProj == -1 && !Main.player[Main.myPlayer].dead)
            {
                Vector2 vector = new Vector2((float)Main.SmartInteractX, (float)Main.SmartInteractY) * 16f;
                new Vector2((float)Main.offScreenRange, (float)Main.offScreenRange);
                bool flag = Main.drawToScreen;
                vector -= Main.screenPosition;
                if (Main.player[Main.myPlayer].gravDir == -1f)
                {
                    vector.Y = (float)Main.screenHeight - vector.Y - 16f;
                }
                Microsoft.Xna.Framework.Color color = Lighting.GetColor(Main.SmartInteractX, Main.SmartInteractY) * 1f;
                Microsoft.Xna.Framework.Rectangle rectangle = new Microsoft.Xna.Framework.Rectangle(0, 0, 1, 1);
                float num = 0.1f;
                float num2 = 0.9f;
                float num3 = 1f;
                float num4 = 1f;
                float num5 = 0.6f;
                Main.spriteBatch.Draw(TextureAssets.MagicPixel.Value, vector, new Microsoft.Xna.Framework.Rectangle?(rectangle), Main.buffColor(color, num, num2, num3, num4) * num5, 0f, Vector2.Zero, 8f, SpriteEffects.None, 0f);
                Main.spriteBatch.Draw(TextureAssets.MagicPixel.Value, vector + Vector2.UnitX * 8f, new Microsoft.Xna.Framework.Rectangle?(rectangle), Main.buffColor(color, num, num2, num3, num4) * num5, 0f, Vector2.Zero, 8f, SpriteEffects.None, 0f);
                Main.spriteBatch.Draw(TextureAssets.MagicPixel.Value, vector + Vector2.UnitY * 8f, new Microsoft.Xna.Framework.Rectangle?(rectangle), Main.buffColor(color, num, num2, num3, num4) * num5, 0f, Vector2.Zero, 8f, SpriteEffects.None, 0f);
                Main.spriteBatch.Draw(TextureAssets.MagicPixel.Value, vector + Vector2.One * 8f, new Microsoft.Xna.Framework.Rectangle?(rectangle), Main.buffColor(color, num, num2, num3, num4) * num5, 0f, Vector2.Zero, 8f, SpriteEffects.None, 0f);
                num = 0.3f;
                num2 = 0.95f;
                num5 = (num4 = 1f);
                Main.spriteBatch.Draw(TextureAssets.MagicPixel.Value, vector + Vector2.UnitX * -2f, new Microsoft.Xna.Framework.Rectangle?(rectangle), Main.buffColor(color, num, num2, num3, num4) * num5, 0f, Vector2.Zero, new Vector2(2f, 16f), SpriteEffects.None, 0f);
                Main.spriteBatch.Draw(TextureAssets.MagicPixel.Value, vector + Vector2.UnitX * 16f, new Microsoft.Xna.Framework.Rectangle?(rectangle), Main.buffColor(color, num, num2, num3, num4) * num5, 0f, Vector2.Zero, new Vector2(2f, 16f), SpriteEffects.None, 0f);
                Main.spriteBatch.Draw(TextureAssets.MagicPixel.Value, vector + Vector2.UnitY * -2f, new Microsoft.Xna.Framework.Rectangle?(rectangle), Main.buffColor(color, num, num2, num3, num4) * num5, 0f, Vector2.Zero, new Vector2(16f, 2f), SpriteEffects.None, 0f);
                Main.spriteBatch.Draw(TextureAssets.MagicPixel.Value, vector + Vector2.UnitY * 16f, new Microsoft.Xna.Framework.Rectangle?(rectangle), Main.buffColor(color, num, num2, num3, num4) * num5, 0f, Vector2.Zero, new Vector2(16f, 2f), SpriteEffects.None, 0f);
            }
        }
References Terraria.Main.buffColor(), Terraria.Player.dead, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Main.drawToScreen, Terraria.Lighting.GetColor(), Terraria.Player.gravDir, Terraria.GameContent.TextureAssets.MagicPixel, Terraria.Main.myPlayer, Terraria.Main.offScreenRange, Microsoft.Xna.Framework.Vector2.One, Terraria.Main.player, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.SmartInteractNPC, Terraria.Main.SmartInteractProj, Terraria.Main.SmartInteractShowingGenuine, Terraria.Main.SmartInteractX, Terraria.Main.SmartInteractY, Terraria.Main.spriteBatch, Microsoft.Xna.Framework.Vector2.UnitX, Microsoft.Xna.Framework.Vector2.UnitY, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.