Terraria Decompiled: Terraria.Main.DrawIMEPanel
DrawIMEPanel()
void Terraria.Main.DrawIMEPanel () inline
Definition at line 40674 of file Main.cs.
        {
            if (Main.imePanelAnchor == null || !Platform.Get<IImeService>().IsCandidateListVisible)
            {
                return;
            }
            Vector2 vector = Main.imePanelAnchor.Value.Position;
            float xanchor = Main.imePanelAnchor.Value.XAnchor;
            List<string> list = new List<string>();
            for (uint num = 0U; num < Platform.Get<IImeService>().CandidateCount; num += 1U)
            {
                string candidate = Platform.Get<IImeService>().GetCandidate(num);
                list.Add(candidate);
            }
            if (list.Count == 0)
            {
                return;
            }
            PlayerInput.SetZoom_UI();
            Main.spriteBatch.Begin(SpriteSortMode.Deferred, null, null, null, null, null, Main.UIScaleMatrix);
            uint? selectedCandidate = Platform.Get<IImeService>().SelectedCandidate;
            DynamicSpriteFont value = FontAssets.MouseText.Value;
            float num2 = 0.85f;
            float num3 = 14f;
            float num4 = 0f;
            int num5 = 32;
            num4 += num3;
            string text = "{0,2}: {1}";
            string text2 = "  ";
            for (int i = 0; i < list.Count; i++)
            {
                int num6 = i + 1;
                string text3 = text;
                if (i < list.Count - 1)
                {
                    text3 += text2;
                }
                num4 += value.MeasureString(string.Format(text3, num6, list[i])).X * num2;
                num4 += num3;
            }
            vector += new Vector2(num4 * -xanchor, 0f);
            vector.X = Math.Min(vector.X, (float)Main.screenWidth - num4);
            vector.X = Math.Max(vector.X, 0f);
            Utils.DrawSettings2Panel(Main.spriteBatch, vector + new Vector2(0f, (float)(-(float)num5)), num4, new Microsoft.Xna.Framework.Color(63, 65, 151, 255) * 0.785f);
            vector += new Vector2(10f, (float)(-(float)num5 / 2));
            uint num7 = 0U;
            while ((ulong)num7 < (ulong)((long)list.Count))
            {
                Microsoft.Xna.Framework.Color color = Microsoft.Xna.Framework.Color.Gray;
                uint num8 = num7;
                uint? num9 = selectedCandidate;
                if ((num8 == num9.GetValueOrDefault()) & (num9 != null))
                {
                    color = Microsoft.Xna.Framework.Color.White;
                }
                uint num10 = num7 + 1U;
                string text4 = text;
                if ((ulong)num7 < (ulong)((long)(list.Count - 1)))
                {
                    text4 += text2;
                }
                string text5 = string.Format(text4, num10, list[(int)num7]);
                Vector2 vector2 = value.MeasureString(text5) * num2;
                Utils.DrawBorderString(Main.spriteBatch, text5, vector, color, num2, 0f, 0.4f, -1);
                vector.X += vector2.X + num3;
                num7 += 1U;
            }
            Main.spriteBatch.End();
        }
References Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(), Terraria.Utils.DrawBorderString(), Terraria.Utils.DrawSettings2Panel(), Microsoft.Xna.Framework.Graphics.SpriteBatch.End(), System.Format, Microsoft.Xna.Framework.Color.Gray, Terraria.Main.imePanelAnchor, ReLogic.Localization.IME.IImeService.IsCandidateListVisible, System.list, System.Math.Max(), System.Math.Min(), Terraria.GameContent.FontAssets.MouseText, Terraria.Main.screenWidth, Terraria.GameInput.PlayerInput.SetZoom_UI(), Terraria.Main.spriteBatch, System.text, Microsoft.Xna.Framework.Input.U, Terraria.Main.UIScaleMatrix, System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Input.X, and Microsoft.Xna.Framework.Vector2.X.