Terraria Decompiled: Terraria.Main.tileSolid
tileSolid
bool [] Terraria.Main.tileSolid = new bool[(int)TileID.Count] static
Definition at line 69901 of file Main.cs.
Referenced by Terraria.WorldGen.ActiveAndWalkableTile(), Terraria.GameContent.Biomes.DeadMansChestBiome.ActuallyPlaceBoulderTrap(), Terraria.WorldGen.AddBuriedChest(), Terraria.NPC.AddKingSlimeTeleportCacheTiles(), Terraria.WorldGen.AddLifeCrystal(), Terraria.WorldGen.AddManaCrystal(), Terraria.WorldGen.AddPasses(), Terraria.WorldGen.AddSpikeCaves(), Terraria.Liquid.AddWater(), Terraria.Collision.AdvancedTileCollision(), Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_006_Worms(), Terraria.Projectile.AI_007_GrapplingHooks_CanTileBeLatchedOnTo(), Terraria.NPC.AI_007_TownEntities(), Terraria.NPC.AI_007_TownEntities_GetWalkPrediction(), Terraria.Projectile.AI_016_Bombs(), Terraria.NPC.AI_026_Unicorns(), Terraria.NPC.AI_037_Destroyer(), Terraria.Projectile.AI_062(), Terraria.NPC.AI_065_Butterflies(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_109_DarkMage(), Terraria.NPC.AI_110_Betsy(), Terraria.NPC.AI_112_FairyCritter(), Terraria.Projectile.AI_113_TargetSticker(), Terraria.NPC.AI_113_WindyBalloon(), Terraria.NPC.AI_114_Dragonflies(), Terraria.NPC.AI_115_LadyBugs(), Terraria.NPC.AI_125_ClumsySlimeBalloon(), Terraria.Projectile.AI_135_OgreStomp(), Terraria.NPC.AI_AttemptToFindTeleportSpot(), Terraria.NPC.AI_AttemptToFindTeleportSpotNearBooks(), Terraria.NPC.AI_AttemptToFindTeleportSpotNearBooks_SearchWall(), Terraria.WorldGen.AnchorValid(), Terraria.WorldGen.BlockBelowMakesSandConvertIntoHardenedSand(), Terraria.WorldGen.BlockBelowMakesSandFall(), Terraria.GameContent.PortalHelper.BlockPortals(), Terraria.WorldGen.BottomEdgeCanBeAttachedTo(), Terraria.Collision.BuildTileContacts(), Terraria.WorldGen.CactusFrame(), Terraria.Collision.CanHit(), Terraria.Collision.CanHitLine(), Terraria.Collision.CanHitWithCheck(), Terraria.TileObject.CanPlace(), Terraria.NPCSpawningFlagsForDualDungeons.CanScan(), Terraria.NPC.Spawner.CanSpawnInTile(), Terraria.DelegateMethods.CastLightOpen(), Terraria.DelegateMethods.CastLightOpen_StopForSolids(), Terraria.DelegateMethods.CastLightOpen_StopForSolids_ScaleWithDistance(), Terraria.WorldGen.Check1x2Top(), Terraria.WorldGen.Check2x2(), Terraria.WorldGen.Check3x3(), Terraria.WorldGen.CheckAndAdjustMultiDirectionalTile(), Terraria.WorldGen.CheckBanner(), Terraria.WorldGen.CheckCatTail(), Terraria.WorldGen.CheckChand(), Terraria.WorldGen.CheckChest(), Terraria.Player.CheckDrowning(), Terraria.Utils.CheckForGoodTeleportationSpot(), Terraria.WorldGen.CheckForHousesNearAPlayer(), Terraria.WorldGen.CheckLilyPad(), Terraria.WorldGen.CheckMB(), Terraria.WorldGen.CheckProjectilePressurePad_GetPossiblePlacementDirections(), Terraria.WorldGen.CheckRoom(), Terraria.Player.CheckSpawn(), Terraria.Player.CheckSpawn_Internal(), Terraria.DelegateMethods.CheckStopForSolids(), Terraria.WorldGen.CheckSuper(), Terraria.WorldGen.CheckTileBreakability(), Terraria.WorldGen.CheckTorch(), Terraria.WorldBuilding.Conditions.IsSolid.CheckValidity(), Terraria.NPC.Collision_MoveSlopesAndStairFall(), Terraria.Projectile.CreateGroundExplosion(), Terraria.Projectile.CreateImpactExplosion(), Terraria.Liquid.CreateLiquidMergeTile(), Terraria.Wiring.DeActive(), Terraria.NetMessage.DecompressTileBlock_Inner(), Terraria.Liquid.DelWater(), Terraria.WorldGen.SecretSeed.DoErrorWorldGetRandomBlock(), Terraria.WorldGen.SecretSeed.DoErrorWorldShuffleBlocks(), Terraria.GameContent.AmbientWindSystem.DoesTileAllowWind(), Terraria.WorldGen.SecretSeed.DoExtraLiquidAddBubbleBlocks(), Terraria.WorldGen.SecretSeed.DoExtraLiquidFinish(), Terraria.WorldGen.SecretSeed.DoRainbowStuff(), Terraria.Main.DoUpdateInWorld(), Terraria.GameContent.Drawing.TileDrawing.DrawBasicTile(), Terraria.HitTile.DrawFreshAnimations(), Terraria.Main.DrawNPCHousesInWorld(), Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile(), Terraria.GameContent.Drawing.TileDrawing.DrawTile_LiquidBehindTile(), Terraria.Main.DrawTileCracks(), Terraria.GameContent.Drawing.TileDrawing.DrawTiles_EmitParticles(), Terraria.WaterfallManager.DrawWaterfall(), Terraria.WorldGen.dropMeteor(), Terraria.GameContent.Generation.Dungeon.Features.DungeonDropTrap.DropTrap(), Terraria.Collision.DrownCollision(), Terraria.DelegateMethods.EmitGolfCartDust_StopForSolids(), Terraria.WorldGen.EmptyLiquid(), Terraria.GameContent.Biomes.DeadMansChestBiome.FindDartTrapSpotSingle(), Terraria.NPC.Spawner.FindSpawnTile(), Terraria.Mount.FindTileHeight(), Terraria.WorldGen.FinishNotTheBees(), Terraria.WorldGen.FixHeart(), Terraria.GameContent.Drawing.WallDrawing.FullTile(), Terraria.GameContent.ExtraSpawnPointManager.GenerateExtraSpawns_IterateDownToFloor(), Terraria.NPC.GetBirdFlightRecommendation(), Terraria.WorldGen.GetCactusType(), Terraria.Physics.BallCollision.GetCollisionPointForTile(), Terraria.Player.GetFloorTile(), Terraria.ID.ContentSamples.CreativeHelper.GetItemGroup(), Terraria.Collision.GetTileRotation(), Terraria.WorldGen.GrowCatTail(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GrowDungeonTree(), Terraria.WorldGen.GrowLivingTree(), Terraria.NPC.HaveDryadDoStardewAnimation(), Terraria.Collision.HitLine(), Terraria.Collision.HitTiles(), Terraria.Collision.HitTilesInACircle(), Terraria.Collision.HitWallSubstep(), Terraria.Main.Initialize_TileAndNPCData1(), Terraria.Main.Initialize_TileAndNPCData2(), Terraria.GameContent.Biomes.DeadMansChestBiome.IsGoodSpotsForExplosive(), Terraria.Physics.BallCollision.IsNeighborSolid(), Terraria.Player.IsTilePoundable(), Terraria.NPC.Spawner.IsValidSpawningGroundTile(), Terraria.GameContent.SmartCursorHelper.IsValidSpotForTorch(), Terraria.Collision.IsWorldPointSolid(), Terraria.Player.ItemCheck_Shoot(), Terraria.Player.ItemCheck_UseBuckets(), Terraria.Player.ItemCheck_UseMiningTools_TryPoundingTile(), Terraria.WorldGen.KillTile_GetItemDrops(), Terraria.WorldGen.KillTile_MakeTileDust(), Terraria.WorldGen.LeftEdgeCanBeAttachedTo(), Terraria.WorldGen.meteor(), Terraria.Player.MinionRestTargetAim(), Terraria.Collision.noSlopeCollision(), Terraria.DelegateMethods.NotSolidOrPlatforms(), Terraria.NPC.NPCCanStickToWalls(), Terraria.Main.oldDrawWater(), Terraria.TileObject.Place(), Terraria.WorldGen.Place1x2Top(), Terraria.WorldGen.Place2x2(), Terraria.WorldGen.Place3x3(), Terraria.WorldGen.PlaceBanner(), Terraria.GameContent.Biomes.DeadMansChestBiome.PlaceBoulderTrapSpot(), Terraria.WorldGen.PlaceCatTail(), Terraria.WorldGen.PlaceChand(), Terraria.WorldGen.PlaceDoor(), Terraria.WorldGen.placeLavaTrap(), Terraria.WorldGen.PlaceLilyPad(), Terraria.WorldGen.PlaceLiquid(), Terraria.WorldGen.PlaceMB(), Terraria.WorldGen.PlaceOasis(), Terraria.WorldGen.PlaceOnTable1x1(), Terraria.WorldGen.PlacePot(), Terraria.WorldGen.PlaceSandTrap(), Terraria.WorldGen.PlaceSign(), Terraria.Player.PlaceThing_Tiles_BlockPlacementForAssortedThings(), Terraria.Player.PlaceThing_Tiles_IsBlockedByLava(), Terraria.Player.PlaceThing_Tiles_PlaceIt_AutoPaintAndActuate(), Terraria.Player.PlaceThing_Tiles_PlaceIt_KillGrassForSolids(), Terraria.Player.PlaceThing_Tiles_PlaceIt_UnslopeForSolids(), Terraria.WorldGen.PlaceTile(), Terraria.ID.TileID.Sets.PostSetupContent(), Terraria.WorldGen.QuickFindHome(), Terraria.Liquid.QuickWater(), Terraria.WorldGen.ReplaceTile_IsValidSolid(), Terraria.WorldGen.Reset(), Terraria.WorldGen.RestoreTemporaryStateChanges(), Terraria.WorldGen.RightEdgeCanBeAttachedTo(), Terraria.WorldGen.ScanTileColumnAndRemoveClumps(), Terraria.WorldGen.ScoreRoom(), Terraria.WorldGen.SetBoulderSolidity(), Terraria.WorldGen.SetCrackedBrickSolidity(), Terraria.Liquid.SettleWaterAt(), Terraria.Main.SetupTileMerge(), Terraria.GameContent.Drawing.TileDrawing.ShouldTileShine(), Terraria.Collision.SlopeCollision(), Terraria.Collision.SolidCollision(), Terraria.Collision.SolidCollision(), Terraria.Collision.SolidFullTiles(), Terraria.WorldGen.SolidOrSlopedTile(), Terraria.NPC.SolidOrSlopedTileOrPlatform(), Terraria.WorldGen.SolidTile(), Terraria.WorldGen.SolidTile(), Terraria.WorldGen.SolidTile2(), Terraria.WorldGen.SolidTile2(), Terraria.WorldGen.SolidTile3(), Terraria.WorldGen.SolidTileAllowBottomSlope(), Terraria.WorldGen.SolidTileAllowLeftSlope(), Terraria.WorldGen.SolidTileAllowRightSlope(), Terraria.WorldGen.SolidTileAllowTopSlope(), Terraria.WorldGen.SolidTileNoAttach(), Terraria.WorldGen.SolidTileNoPlatforms(), Terraria.Collision.SolidTiles(), Terraria.Collision.SolidTiles(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsDownDashExplosion(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsFlint(), Terraria.Player.Spawn_DescendFromDefaultSpace(), Terraria.Player.Spawn_ForceClearArea(), Terraria.Player.Spawn_IsAreaValidSpawn(), Terraria.WorldGen.SpawnGraveyardBiome(), Terraria.WorldGen.SpawnHomelessNPC(), Terraria.WorldGen.SpawnTownNPC(), Terraria.WorldGen.SpawnTravelNPC(), Terraria.WorldGen.SpreadGrass(), Terraria.DelegateMethods.SpreadLightOpen_StopForSolids(), Terraria.DelegateMethods.SpreadTile(), Terraria.WorldGen.StartRoomCheck(), Terraria.Physics.BallCollision.Step(), Terraria.GameContent.SmartCursorHelper.Step_BlocksFilling(), Terraria.GameContent.SmartCursorHelper.Step_BlocksLines(), Terraria.GameContent.SmartCursorHelper.Step_Boulders(), Terraria.GameContent.SmartCursorHelper.Step_ClayPots(), Terraria.GameContent.SmartCursorHelper.Step_ForceCursorToAnyMinableThing(), Terraria.GameContent.SmartCursorHelper.Step_PaintRoller(), Terraria.GameContent.SmartCursorHelper.Step_Pickaxe_MineSolids(), Terraria.GameContent.SmartCursorHelper.Step_PumpkinSeeds(), Terraria.GameContent.SmartCursorHelper.Step_Walls(), Terraria.Collision.StepDown(), Terraria.Collision.StepUp(), Terraria.WorldGen.StonePatch(), Terraria.GameContent.PortalHelper.SupportedHalfbrick(), Terraria.GameContent.PortalHelper.SupportedNormal(), Terraria.GameContent.PortalHelper.SupportedSlope(), Terraria.WorldGen.templePart2(), Terraria.Collision.TileCollision(), Terraria.WorldGen.tileCounterNext(), Terraria.WorldGen.TileFrame(), Terraria.WorldGen.TileFrameCosmetic(), Terraria.WorldGen.TileFrameImportant(), Terraria.WorldGen.TileIsExposedToAir(), Terraria.Liquid.tilesIgnoreWater(), Terraria.WorldGen.TopEdgeCanBeAttachedTo(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalTraps.Traps(), Terraria.NPC.TryFindingFloor(), Terraria.WorldGen.TrySpawningTownNPC(), Terraria.GameContent.AmbientWindSystem.TrySpawningWind(), Terraria.Liquid.Update(), Terraria.GameContent.Golf.FancyGolfPredictionLine.Update(), Terraria.Collision.WalkDownSlope(), Terraria.WorldGen.WaterCheck(), Terraria.WorldGen.WillWaterPlacedHereStayPut(), and Terraria.Liquid.worldGenTilesIgnoreWater().