Terraria Decompiled: Terraria.Main.TryPetting
TryPetting()
static int Terraria.Main.TryPetting (Projectile proj, int itemIcon) inline static private
Definition at line 37342 of file Main.cs.
        {
            if (Main.gamePaused || Main.gameMenu)
            {
                return 0;
            }
            Player localPlayer = Main.LocalPlayer;
            Vector2 center = localPlayer.Center;
            if (!localPlayer.IsProjectileInteractableAndInInteractionRange(proj, ref center))
            {
                return 0;
            }
            Vector2 vector = Main.ReverseGravitySupport(Main.MouseScreen, 0f) + Main.screenPosition;
            Microsoft.Xna.Framework.Rectangle hitbox = proj.Hitbox;
            if (proj.type == 1094)
            {
                hitbox.Inflate(6, 6);
            }
            bool flag = hitbox.Contains(vector.ToPoint());
            bool flag2 = (flag || Main.SmartInteractProj == proj.whoAmI) & !localPlayer.lastMouseInterface;
            bool flag3 = !Main.SmartCursorIsUsed && !PlayerInput.UsingGamepad;
            if (!flag2)
            {
                if (!flag3)
                {
                    return 1;
                }
                return 0;
            }
            else
            {
                Main.HasInteractableObjectThatIsNotATile = true;
                if (flag)
                {
                    localPlayer.noThrow = 4;
                    localPlayer.cursorItemIconEnabled = true;
                    localPlayer.cursorItemIconID = itemIcon;
                }
                if (PlayerInput.UsingGamepad)
                {
                    localPlayer.GamepadEnableGrappleCooldown();
                }
                if (Main.mouseRight && Main.mouseRightRelease && Player.BlockInteractionWithProjectiles == 0)
                {
                    Main.mouseRightRelease = false;
                    localPlayer.tileInteractAttempted = true;
                    localPlayer.tileInteractionHappened = true;
                    localPlayer.releaseUseTile = false;
                    localPlayer.PetAnimal(proj.GetPettingInfo(localPlayer));
                }
                if (!Main.SmartCursorIsUsed && !PlayerInput.UsingGamepad)
                {
                    return 0;
                }
                if (!flag3)
                {
                    return 2;
                }
                return 0;
            }
        }
References Terraria.Player.BlockInteractionWithProjectiles, Terraria.Entity.Center, Microsoft.Xna.Framework.Rectangle.Contains(), Terraria.Main.gameMenu, Terraria.Player.GamepadEnableGrappleCooldown(), Terraria.Main.gamePaused, Terraria.Projectile.GetPettingInfo(), Terraria.Entity.Hitbox, Microsoft.Xna.Framework.Rectangle.Inflate(), Terraria.Player.IsProjectileInteractableAndInInteractionRange(), Terraria.Player.lastMouseInterface, Terraria.Main.LocalPlayer, Terraria.Main.mouseRight, Terraria.Main.mouseRightRelease, Terraria.Main.MouseScreen, Terraria.Player.PetAnimal(), Terraria.Main.ReverseGravitySupport(), Terraria.Main.screenPosition, Terraria.Main.SmartCursorIsUsed, Terraria.Projectile.type, Terraria.GameInput.PlayerInput.UsingGamepad, and Terraria.Entity.whoAmI.
Referenced by Terraria.Main.DrawProjDirect().