Terraria Decompiled: Terraria.Main.DrawKite
DrawKite()
static void Terraria.Main.DrawKite (Projectile proj, Vector2 anchorPos) inline static
Definition at line 36579 of file Main.cs.
        {
            Texture2D value = TextureAssets.Projectile[proj.type].Value;
            Texture2D texture2D = TextureAssets.Extra[103].Value;
            int num = 15;
            float num2 = 0f;
            int num3 = 10;
            int num4 = 5;
            float num5 = 10f;
            float num6 = 0f;
            int num7 = -14;
            float num8 = -2f;
            int num9 = -1;
            float num10 = -1f;
            int num11 = 8;
            int num12 = 0;
            int num13 = 1;
            float num14 = 0f;
            float num15 = 0f;
            bool flag = true;
            bool flag2 = false;
            float num16 = 0f;
            float num17 = Math.Abs(Main.WindForVisuals);
            float num18 = Utils.Remap(num17, 0.24f, 0.2f, 0f, 1f, true);
            num18 = Utils.Remap(proj.localAI[0], 0f, 300f, 0f, 1f, true);
            float num19 = proj.localAI[1];
            int type = proj.type;
            if (type - 766 > 4)
            {
                if (type != 771)
                {
                    switch (type)
                    {
                    case 822:
                        texture2D = TextureAssets.Extra[132].Value;
                        num = 7;
                        num12 = 7;
                        num2 = ((proj.spriteDirection == 1) ? 1.5707964f : (-1.5707964f));
                        num3 = 7;
                        num5 = 22f;
                        num6 += 0.2617994f * (float)proj.spriteDirection;
                        num7 = -20;
                        num8 = -6f;
                        num11 = 12;
                        num16 = 0.19634955f;
                        break;
                    case 823:
                    case 846:
                        texture2D = TextureAssets.Extra[133].Value;
                        if (proj.type == 846)
{
                            texture2D = TextureAssets.Extra[146].Value;
                        }
                        num = 6;
                        num12 = 6;
                        num2 = ((proj.spriteDirection == 1) ? 1.5707964f : (-1.5707964f));
                        num3 = 6;
                        num5 = 40f;
                        num6 += 0.2617994f * (float)proj.spriteDirection;
                        num7 = -16;
                        num8 = -10f;
                        num11 = 30;
                        num16 = 0.5890486f;
                        break;
                    case 824:
                    case 826:
                    case 839:
                    case 840:
                    case 853:
                        num13 = 0;
                        num6 = num18 * num19 * 6.2831855f * -0.125f * (float)proj.spriteDirection;
                        num6 = 0f;
                        break;
                    case 827:
                    case 844:
                        texture2D = TextureAssets.Extra[135].Value;
                        if (proj.type == 844)
{
                            texture2D = TextureAssets.Extra[144].Value;
                        }
                        num = 4;
                        num12 = 3;
                        num2 = ((proj.spriteDirection == 1) ? 1.5707964f : (-1.5707964f));
                        num3 = 16;
                        num5 = 10f;
                        num6 += 0.2617994f * (float)proj.spriteDirection;
                        num8 = -4f;
                        num4 = 4;
                        flag2 = true;
                        num16 = 0.09817477f;
                        break;
                    case 828:
                    case 829:
                        texture2D = TextureAssets.Extra[136].Value;
                        if (proj.type == 829)
{
                            texture2D = TextureAssets.Extra[137].Value;
                        }
                        num = 2;
                        num12 = 1;
                        num2 = ((proj.spriteDirection == 1) ? 1.5707964f : (-1.5707964f));
                        num3 = 6;
                        num5 = 10f;
                        num6 += 0.2617994f * (float)proj.spriteDirection;
                        num11 = 10;
                        num8 = -4f;
                        num13 = 3;
                        flag = false;
                        flag2 = true;
                        num16 = 0.5890486f;
                        break;
                    case 830:
                    case 838:
                        texture2D = TextureAssets.Extra[138].Value;
                        if (proj.type == 838)
{
                            texture2D = TextureAssets.Extra[139].Value;
                        }
                        num = 3;
                        num12 = 3;
                        num2 = ((proj.spriteDirection == 1) ? 1.5707964f : (-1.5707964f));
                        num3 = 3;
                        num5 = 60f;
                        num10 = 40f;
                        num9 = 3;
                        num6 += 0.2617994f * (float)proj.spriteDirection;
                        num11 = 50;
                        num8 = -20f;
                        num14 = -10f;
                        num16 = 0.7853982f;
                        break;
                    case 843:
                        texture2D = TextureAssets.Extra[140].Value;
                        num = 2;
                        num12 = 2;
                        num2 = ((proj.spriteDirection == 1) ? 1.5707964f : (-1.5707964f));
                        num3 = 2;
                        num5 = 30f;
                        num6 += 0.2617994f * (float)proj.spriteDirection;
                        num11 = 20;
                        num8 = -16f;
                        num14 = -10f;
                        num16 = 0.7853982f;
                        break;
                    case 845:
                        texture2D = TextureAssets.Extra[145].Value;
                        num = 3;
                        num12 = 3;
                        num2 = ((proj.spriteDirection == 1) ? 1.5707964f : (-1.5707964f));
                        num3 = 3;
                        num5 = 42f;
                        num10 = 50f;
                        num9 = 2;
                        num6 += 0.2617994f * (float)proj.spriteDirection;
                        num11 = 30;
                        num8 = -8f;
                        num14 = -10f;
                        break;
                    case 850:
                        texture2D = TextureAssets.Extra[147].Value;
                        num = 8;
                        num12 = 8;
                        num2 = ((proj.spriteDirection == 1) ? 1.5707964f : (-1.5707964f));
                        num3 = 8;
                        num5 = 22f;
                        num6 += 0.2617994f * (float)proj.spriteDirection;
                        num7 = -20;
                        num8 = -38f;
                        num11 = 12;
                        num14 = 6f;
                        num15 = 2f;
                        flag = false;
                        num16 = 0.49087387f;
                        break;
                    case 852:
                        texture2D = TextureAssets.Extra[148].Value;
                        num = 2;
                        num12 = 1;
                        num2 = ((proj.spriteDirection == 1) ? 1.5707964f : (-1.5707964f));
                        num3 = 6;
                        num5 = 10f;
                        num6 += 0.2617994f * (float)proj.spriteDirection;
                        num11 = 10;
                        num8 = -4f;
                        num13 = 4;
                        flag = false;
                        flag2 = true;
                        num16 = 0.98174775f;
                        break;
                    }
                }
                else
                {
                    texture2D = TextureAssets.Extra[104].Value;
                    num = 12;
                    num12 = 12;
                    num2 = ((proj.spriteDirection == 1) ? 1.5707964f : (-1.5707964f));
                    num3 = 12;
                    num5 = 22f;
                    num6 += 0.3926991f * (float)proj.spriteDirection;
                    num7 = -8;
                    num8 = -6f;
                    num9 = 10;
                    num10 = 8f;
                    num11 = 12;
                    num16 = 0.19634955f;
                }
            }
            else
            {
                num12 = (proj.type - 766) * 3 + 3;
            }
            SpriteEffects spriteEffects = ((proj.spriteDirection == 1) ? SpriteEffects.None : SpriteEffects.FlipHorizontally);
            Microsoft.Xna.Framework.Rectangle rectangle = value.Frame(Main.projFrames[proj.type], 1, proj.frame, 0, 0, 0);
            Vector2 vector = rectangle.Size() / 2f;
            Vector2 vector2 = proj.Center - Main.screenPosition;
            Microsoft.Xna.Framework.Color color = Lighting.GetColor(proj.Center.ToTileCoordinates());
            Microsoft.Xna.Framework.Color alpha = proj.GetAlpha(color);
            Texture2D value2 = TextureAssets.FishingLine.Value;
            Microsoft.Xna.Framework.Rectangle rectangle2 = value2.Frame(1, 1, 0, 0, 0, 0);
            Vector2 vector3 = new Vector2((float)(rectangle2.Width / 2), 2f);
            Microsoft.Xna.Framework.Rectangle rectangle3 = texture2D.Frame(num, 1, 0, 0, 0, 0);
            int width = rectangle3.Width;
            rectangle3.Width -= 2;
            Vector2 vector4 = rectangle3.Size() / 2f;
            rectangle3.X = width * (num - 1);
            vector.X += (float)(-2 * proj.spriteDirection);
            Vector2 center = proj.Center;
            Vector2.Distance(center, anchorPos);
            float num20 = 12f;
            (anchorPos - center).SafeNormalize(Vector2.Zero) * num20;
            Vector2 vector5 = anchorPos;
            Vector2 vector6 = center - vector5;
            Vector2 velocity = proj.velocity;
            if (Math.Abs(velocity.X) > Math.Abs(velocity.Y))
            {
                Utils.Swap<float>(ref velocity.X, ref velocity.Y);
            }
            float num21 = vector6.Length();
            float num22 = Vector2.Distance(proj.Center, anchorPos);
            if (num22 == 0f)
            {
                num22 = 1f;
            }
            float num23 = 16f;
            float num24 = 80f;
            bool flag3 = true;
            if (num21 == 0f)
            {
                flag3 = false;
            }
            else
            {
                vector6 *= 12f / num21;
                vector5 -= vector6;
                vector6 = center - vector5;
            }
            while (flag3)
            {
                float num25 = 12f;
                float num26 = vector6.Length();
                float num27 = num26;
                if (float.IsNaN(num26) || num26 == 0f)
                {
                    flag3 = false;
                }
                else
                {
                    if (num26 < 20f)
                    {
                        flag3 = false;
                        vector5 += vector6.SafeNormalize(Vector2.Zero) * num25;
                        vector6 = center - vector5;
                        num25 = vector6.Length() + 4f;
                    }
                    else
                    {
                        num26 = 12f / num26;
                        vector6 *= num26;
                        vector5 += vector6;
                        vector6 = center - vector5;
                        if (num27 > 12f)
{
                            float num28 = 0.3f;
                            float num29 = Math.Abs(velocity.X) + Math.Abs(velocity.Y);
                            if (num29 > num23)
{
                                num29 = num23;
                            }
                            num29 = 1f - num29 / num23;
                            num28 *= num29;
                            num29 = num27 / num24;
                            if (num29 > 1f)
{
                                num29 = 1f;
                            }
                            num28 *= num29;
                            if (num28 < 0f)
{
                                num28 = 0f;
                            }
                            num29 = 1f;
                            num28 *= num29;
                            if (vector6.Y > 0f)
{
                                vector6.Y *= 1f + num28;
                                vector6.X *= 1f - num28;
                            }
                            else
{
                                num29 = Math.Abs(velocity.X) / 3f;
                                if (num29 > 1f)
{
                                    num29 = 1f;
                                }
                                num29 -= 0.5f;
                                num28 *= num29;
                                if (num28 > 0f)
{
                                    num28 *= 2f;
                                }
                                vector6.Y *= 1f + num28;
                                vector6.X *= 1f - num28;
                            }
                        }
                    }
                    float num30 = vector6.ToRotation() - 1.5707964f;
                    if (!flag3)
                    {
                        rectangle2.Height = (int)num25;
                    }
                    Microsoft.Xna.Framework.Color color2 = Lighting.GetColor(center.ToTileCoordinates());
                    color2 *= 0.42745098f;
                    float num31 = Vector2.Distance(proj.Center, vector5);
                    float num32 = 1f - num31 / num22;
                    color2 *= Utils.Remap(num32, 0f, 1f, 0.5f, 1f, true);
                    Vector2 vector7 = new Vector2(0.8f, 1f);
                    Main.EntitySpriteDraw(value2, vector5 - Main.screenPosition, new Microsoft.Xna.Framework.Rectangle?(rectangle2), color2, num30, vector3, vector7, SpriteEffects.None, 0f);
                }
            }
            Vector2 vector8 = proj.Size / 2f;
            float num33 = MathHelper.Lerp(0.5f, 1f, num17);
            float num34 = num17;
            if (vector6.Y >= -0.02f && vector6.Y < 1f)
            {
                num34 = Utils.GetLerpValue(0.2f, 0.5f, num17, true);
            }
            int num35 = num4;
            int num36 = num3 + 1;
            for (int i = 0; i < num13; i++)
            {
                rectangle3.X = width * (num - 1);
                List<Vector2> list = new List<Vector2>();
                Vector2 vector9 = new Vector2(num33 * (float)num11 * (float)proj.spriteDirection, (float)Math.Sin(Main.timeForVisualEffects / 300.0 * 6.2831854820251465) * num34) * 2f;
                float num37 = (float)num7 + num14;
                float num38 = num8 + num15;
                float num39 = 0.5f;
                switch (i)
                {
                case 1:
                    vector9 = new Vector2(num33 * (float)num11 * (float)proj.spriteDirection, (float)Math.Sin(Main.timeForVisualEffects / 300.0 * 6.2831854820251465) * num34 + 0.5f * (1f - num18)) * 2f;
                    num37 -= 8f;
                    num38 -= 8f;
                    break;
                case 2:
                    vector9 = new Vector2(num33 * (float)num11 * (float)proj.spriteDirection, (float)Math.Sin(Main.timeForVisualEffects / 300.0 * 6.2831854820251465) * num34 + 1f * (1f - num18)) * 2f;
                    num37 -= 4f;
                    num38 -= 4f;
                    break;
                case 3:
                    vector9 = new Vector2(num33 * (float)num11 * (float)proj.spriteDirection, (float)Math.Sin(Main.timeForVisualEffects / 300.0 * 6.2831854820251465) * num34 + 1.5f * (1f - num18)) * 2f;
                    num37 -= 12f;
                    num38 -= 12f;
                    break;
                }
                if (num18 > 0f)
                {
                    vector9 = vector9.RotatedBy((double)(num18 * 1.5707964f * (float)proj.spriteDirection), default(Vector2));
                    num8 *= 1f - num18;
                    num14 *= 1f - num18;
                    num15 *= 1f - num18;
                    float num40 = 1f - num19;
                    num40 *= num18;
                    num6 *= 1f - num40;
                    num6 -= 0.7853982f * num40 * (float)proj.spriteDirection;
                    num6 += num40 * num16 * (float)proj.spriteDirection;
                    if (num5 != -1f)
                    {
                        num5 *= MathHelper.Lerp(1f, 0.7f, num18);
                    }
                    num10 *= MathHelper.Lerp(1f, 0.7f, num18);
                }
                Vector2 vector10 = proj.Center + new Vector2(((float)rectangle.Width * num39 + num37) * (float)proj.spriteDirection, num38).RotatedBy((double)(proj.rotation + num6), default(Vector2));
                list.Add(vector10);
                int j = num35;
                int num41 = 1;
                while (j < num36 * num35)
                {
                    if (num9 != -1 && num9 == num41)
                    {
                        num5 = num10;
                    }
                    Vector2 vector11 = proj.oldPos[j];
                    if (vector11.X == 0f && vector11.Y == 0f)
                    {
                        list.Add(vector10);
                    }
                    else
                    {
                        Vector2 vector12 = new Vector2(((float)rectangle.Width * num39 + num37) * (float)proj.oldSpriteDirection[j], num38);
                        float num42 = proj.oldRot[j] + num6;
                        vector11 += vector8 + vector12.RotatedBy((double)num42, default(Vector2));
                        vector11 += vector9 * (float)(num41 + 1);
                        Vector2 vector13 = vector10 - vector11;
                        float num43 = vector13.Length();
                        if (num43 > num5)
{
                            vector13 *= num5 / num43;
                        }
                        vector11 = vector10 - vector13;
                        list.Add(vector11);
                        vector10 = vector11;
                    }
                    j += num35;
                    num41++;
                }
                if (flag)
                {
                    Microsoft.Xna.Framework.Rectangle rectangle4 = value2.Frame(1, 1, 0, 0, 0, 0);
                    for (int k = list.Count - 2; k >= 0; k--)
                    {
                        Vector2 vector14 = list[k];
                        Vector2 vector15 = list[k + 1] - vector14;
                        float num44 = vector15.Length();
                        if (num44 >= 2f)
{
                            float num45 = vector15.ToRotation() - 1.5707964f;
                            Main.EntitySpriteDraw(value2, vector14 - Main.screenPosition, new Microsoft.Xna.Framework.Rectangle?(rectangle4), alpha * 0.42745098f, num45, vector3, new Vector2(1f, num44 / (float)rectangle4.Height), SpriteEffects.None, 0f);
                        }
                    }
                }
                for (int l = list.Count - 2; l >= 0; l--)
                {
                    Vector2 vector16 = list[l];
                    Vector2 vector17 = list[l + 1];
                    Vector2 vector18 = vector17 - vector16;
                    vector18.Length();
                    float num46 = vector18.ToRotation() - 1.5707964f + num2;
                    Main.EntitySpriteDraw(texture2D, vector17 - Main.screenPosition, new Microsoft.Xna.Framework.Rectangle?(rectangle3), alpha, num46, vector4, proj.scale, spriteEffects, 0f);
                    rectangle3.X -= width;
                    if (rectangle3.X < 0)
                    {
                        int num47 = num12;
                        if (flag2)
{
                            num47--;
                        }
                        rectangle3.X = num47 * width;
                    }
                }
            }
            Main.EntitySpriteDraw(value, vector2, new Microsoft.Xna.Framework.Rectangle?(rectangle), alpha, proj.rotation + num6, vector, proj.scale, spriteEffects, 0f);
        }
References System.Math.Abs(), Microsoft.Xna.Framework.Vector2.Add(), Terraria.Entity.Center, Microsoft.Xna.Framework.Vector2.Distance(), Terraria.Main.EntitySpriteDraw(), Terraria.GameContent.TextureAssets.Extra, Terraria.GameContent.TextureAssets.FishingLine, Terraria.Projectile.frame, Terraria.Projectile.GetAlpha(), Terraria.Lighting.GetColor(), Terraria.Utils.GetLerpValue(), Microsoft.Xna.Framework.Rectangle.Height, int, Microsoft.Xna.Framework.Vector2.Length(), Microsoft.Xna.Framework.MathHelper.Lerp(), System.list, Terraria.Projectile.localAI, Terraria.Projectile.oldPos, Terraria.Projectile.oldRot, Terraria.Projectile.oldSpriteDirection, Terraria.GameContent.TextureAssets.Projectile, Terraria.Main.projFrames, Terraria.Utils.Remap(), Terraria.Projectile.rotation, Terraria.Projectile.scale, Terraria.Main.screenPosition, System.Math.Sin(), Terraria.Projectile.spriteDirection, Terraria.Main.timeForVisualEffects, Terraria.Projectile.type, System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Entity.velocity, Microsoft.Xna.Framework.Rectangle.Width, Terraria.Main.WindForVisuals, Microsoft.Xna.Framework.Rectangle.X, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.LeashedEntities.LeashedKite.Draw(), and Terraria.Main.DrawProjDirect().