Terraria Decompiled: Terraria.Main.DrawInterface_Resources_Breath
DrawInterface_Resources_Breath()
static void Terraria.Main.DrawInterface_Resources_Breath () inline static private
Definition at line 43410 of file Main.cs.
        {
            bool flag = false;
            if (Main.player[Main.myPlayer].dead)
            {
                return;
            }
            if (Main.player[Main.myPlayer].lavaTime < Main.player[Main.myPlayer].lavaMax && Main.player[Main.myPlayer].lavaWet)
            {
                flag = true;
            }
            else if (Main.player[Main.myPlayer].lavaTime < Main.player[Main.myPlayer].lavaMax && Main.player[Main.myPlayer].breath == Main.player[Main.myPlayer].breathMax)
            {
                flag = true;
            }
            Vector2 vector = Main.player[Main.myPlayer].Top + new Vector2(0f, Main.player[Main.myPlayer].gfxOffY);
            if (Main.playerInventory && Main.screenHeight < 1000)
            {
                vector.Y += (float)(Main.player[Main.myPlayer].height - 20);
            }
            vector = Vector2.Transform(vector - Main.screenPosition, Main.GameViewMatrix.ZoomMatrix);
            if (!Main.playerInventory || Main.screenHeight >= 1000)
            {
                vector.Y -= 100f;
            }
            vector /= Main.UIScale;
            if (Main.ingameOptionsWindow || Main.InGameUI.IsVisible)
            {
                vector = new Vector2((float)(Main.screenWidth / 2), (float)(Main.screenHeight / 2 + 236));
                if (Main.InGameUI.IsVisible)
                {
                    vector.Y = (float)(Main.screenHeight - 64);
                }
            }
            if (Main.player[Main.myPlayer].breath < Main.player[Main.myPlayer].breathMax && !Main.player[Main.myPlayer].ghost && !flag)
            {
                int num = Main.player[Main.myPlayer].breathMax / 20;
                int num2 = 20;
                for (int i = 1; i < Main.player[Main.myPlayer].breathMax / num2 + 1; i++)
                {
                    float num3 = 1f;
                    int num4;
                    if (Main.player[Main.myPlayer].breath >= i * num2)
                    {
                        num4 = 255;
                    }
                    else
                    {
                        float num5 = (float)(Main.player[Main.myPlayer].breath - (i - 1) * num2) / (float)num2;
                        num4 = (int)(30f + 225f * num5);
                        if (num4 < 30)
{
                            num4 = 30;
                        }
                        num3 = num5 / 4f + 0.75f;
                        if ((double)num3 < 0.75)
{
                            num3 = 0.75f;
                        }
                    }
                    int num6 = 0;
                    int num7 = 0;
                    if (i > 10)
                    {
                        num6 -= 260;
                        num7 += 26;
                    }
                    Main.spriteBatch.Draw(TextureAssets.Bubble.Value, vector + new Vector2((float)(26 * (i - 1) + num6) - 125f, 32f + ((float)TextureAssets.Bubble.Height() - (float)TextureAssets.Bubble.Height() * num3) / 2f + (float)num7), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Bubble.Width(), TextureAssets.Bubble.Height())), new Microsoft.Xna.Framework.Color(num4, num4, num4, num4), 0f, default(Vector2), num3, SpriteEffects.None, 0f);
                }
            }
            if (Main.player[Main.myPlayer].lavaTime < Main.player[Main.myPlayer].lavaMax && !Main.player[Main.myPlayer].ghost && flag)
            {
                int num8 = Main.player[Main.myPlayer].lavaMax / 10;
                int num9 = Main.player[Main.myPlayer].breathMax / num8;
                for (int j = 1; j < Main.player[Main.myPlayer].lavaMax / num8 + 1; j++)
                {
                    float num10 = 1f;
                    int num11;
                    if (Main.player[Main.myPlayer].lavaTime >= j * num8)
                    {
                        num11 = 255;
                    }
                    else
                    {
                        float num12 = (float)(Main.player[Main.myPlayer].lavaTime - (j - 1) * num8) / (float)num8;
                        num11 = (int)(30f + 225f * num12);
                        if (num11 < 30)
{
                            num11 = 30;
                        }
                        num10 = num12 / 4f + 0.75f;
                        if ((double)num10 < 0.75)
{
                            num10 = 0.75f;
                        }
                    }
                    int num13 = 0;
                    int num14 = 0;
                    if (j > 10)
                    {
                        num13 -= 260;
                        num14 += 26;
                    }
                    Main.spriteBatch.Draw(TextureAssets.Flame.Value, vector + new Vector2((float)(26 * (j - 1) + num13) - 125f, 32f + ((float)TextureAssets.Flame.Height() - (float)TextureAssets.Flame.Height() * num10) / 2f + (float)num14), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Bubble.Width(), TextureAssets.Bubble.Height())), new Microsoft.Xna.Framework.Color(num11, num11, num11, num11), 0f, default(Vector2), num10, SpriteEffects.None, 0f);
                }
            }
        }
References Terraria.Player.breath, Terraria.Player.breathMax, Terraria.GameContent.TextureAssets.Bubble, Terraria.Player.dead, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.GameContent.TextureAssets.Flame, Terraria.Main.GameViewMatrix, Terraria.Player.gfxOffY, Terraria.Player.ghost, Terraria.Entity.height, Terraria.Main.ingameOptionsWindow, Terraria.Main.InGameUI, int, Terraria.UI.UserInterface.IsVisible, Terraria.Player.lavaMax, Terraria.Player.lavaTime, Terraria.Entity.lavaWet, Terraria.Main.myPlayer, Terraria.Main.player, Terraria.Main.playerInventory, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Terraria.Main.spriteBatch, Terraria.Entity.Top, Microsoft.Xna.Framework.Vector2.Transform(), Terraria.Main.UIScale, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, and Terraria.Graphics.SpriteViewMatrix.ZoomMatrix.
Referenced by Terraria.Main.GUIBarsDrawInner().