Terraria Decompiled: Terraria.Main.WriteFancyWorldLoadErrorToConsole
WriteFancyWorldLoadErrorToConsole()
static void Terraria.Main.WriteFancyWorldLoadErrorToConsole () inline static private
Definition at line 4015 of file Main.cs.
        {
            Console.WriteLine();
            if (WorldFile.LastThrownLoadException != null)
            {
                Console.WriteLine(WorldFile.LastThrownLoadException.ToString());
            }
        }
References Terraria.IO.WorldFile.LastThrownLoadException, System.Exception.ToString(), and System.Console.WriteLine().
Referenced by Terraria.Main.DedServ().