Terraria Decompiled: Terraria.Main.DoUpdate_AutoSave
DoUpdate_AutoSave()
static void Terraria.Main.DoUpdate_AutoSave () inline static private
Definition at line 18475 of file Main.cs.
        {
            if (!Main.gameMenu && Main.netMode == 1)
            {
                if (!Main.saveTime.IsRunning)
                {
                    Main.saveTime.Start();
                }
                if (Main.saveTime.ElapsedMilliseconds > 300000L)
                {
                    Main.saveTime.Reset();
                    WorldGen.saveToonWhilePlaying();
                    return;
                }
            }
            else if (!Main.gameMenu && (Main.autoSave || Main.netMode == 2))
            {
                if (!Main.saveTime.IsRunning)
                {
                    Main.saveTime.Start();
                }
                if (Main.saveTime.ElapsedMilliseconds > 600000L)
                {
                    Main.saveTime.Reset();
                    if (Main.netMode != 2)
                    {
                        WorldGen.saveToonWhilePlaying();
                    }
                    WorldGen.saveAndPlay();
                    return;
                }
            }
            else if (Main.saveTime.IsRunning)
            {
                Main.saveTime.Stop();
            }
        }
References Terraria.Main.autoSave, Terraria.Main.gameMenu, Microsoft.Xna.Framework.Input.L, Terraria.Main.netMode, Terraria.WorldGen.saveAndPlay(), Terraria.Main.saveTime, and Terraria.WorldGen.saveToonWhilePlaying().
Referenced by Terraria.Main.DoUpdate().