Terraria Decompiled: Terraria.Main.TryPickingDefaultUIScale
TryPickingDefaultUIScale()
static void Terraria.Main.TryPickingDefaultUIScale (float displayHeight) inline static private
Definition at line 2330 of file Main.cs.
        {
            if (!Main.shouldSetDefaultUIScale)
            {
                return;
            }
            Main.newDefaultUIScale = displayHeight / 1080f * 1.1f;
            Main.shouldSetDefaultUIScale = false;
            Main.Configuration.Put("UIScale", Main.newDefaultUIScale);
            Main.Configuration.Save(true);
        }
References Terraria.Main.Configuration, Terraria.Main.displayHeight, Terraria.Main.newDefaultUIScale, Terraria.IO.Preferences.Put(), Terraria.IO.Preferences.Save(), and Terraria.Main.shouldSetDefaultUIScale.
Referenced by Terraria.Main.LoadSettings(), Terraria.Main.SetDisplayMode(), and Terraria.Main.SetDisplayModeAsBorderless().