Terraria Decompiled: Terraria.Main.DrawBestiaryIcon
DrawBestiaryIcon()
static void Terraria.Main.DrawBestiaryIcon (int pivotTopLeftX, int pivotTopLeftY) inline static private
Definition at line 42396 of file Main.cs.
        {
            Main.inventoryScale = 0.85f;
            int num = (int)((float)(450 + pivotTopLeftX) - 56f * Main.inventoryScale * 2f);
            int num2 = 258 + pivotTopLeftY;
            int num3 = 30;
            int num4 = 30;
            int num5 = 498;
            int num6 = 244;
            num = num5;
            num2 = num6 + num4 + 4;
            if (Main.ChestOrShopUIVisible)
            {
                num2 += 168;
                Main.inventoryScale = 0.755f;
                num += 5;
                num6 += 24;
            }
            if (Main.editChest)
            {
                num2 += 24;
            }
            Microsoft.Xna.Framework.Rectangle rectangle = new Microsoft.Xna.Framework.Rectangle(num, num2, (int)((float)TextureAssets.InventoryBack.Width() * Main.inventoryScale), (int)((float)TextureAssets.InventoryBack.Height() * Main.inventoryScale));
            rectangle = new Microsoft.Xna.Framework.Rectangle(num, num2, num3, num4);
            bool flag = false;
            if (rectangle.Contains(new Microsoft.Xna.Framework.Point(Main.mouseX, Main.mouseY)) && !PlayerInput.IgnoreMouseInterface && !Main.LocalPlayerHasPendingInventoryActions())
            {
                Main.player[Main.myPlayer].mouseInterface = true;
                flag = true;
                if (Main.mouseLeft && Main.mouseLeftRelease)
                {
                    Main.player[Main.myPlayer].SetTalkNPC(-1);
                    Main.npcChatCornerItem = 0;
                    Main.npcChatText = "";
                    Main.mouseLeftRelease = false;
                    SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                    IngameFancyUI.OpenUIState(Main.BestiaryUI);
                    Main.BestiaryUI.OnOpenPage();
                }
            }
            Main.DoStatefulTickSound(ref Main.bestiaryMouseOver, flag);
            Texture2D value = TextureAssets.BestiaryMenuButton.Value;
            Vector2 vector = rectangle.Center.ToVector2();
            Microsoft.Xna.Framework.Rectangle rectangle2 = value.Frame(2, 1, flag ? 1 : 0, 0, 0, 0);
            rectangle2.Width -= 2;
            rectangle2.Height -= 2;
            Vector2 vector2 = rectangle2.Size() / 2f;
            Microsoft.Xna.Framework.Color white = Microsoft.Xna.Framework.Color.White;
            Main.spriteBatch.Draw(value, vector, new Microsoft.Xna.Framework.Rectangle?(rectangle2), white, 0f, vector2, 1f, SpriteEffects.None, 0f);
            UILinkPointNavigator.SetPosition(310, vector);
            if (!Main.mouseText && flag)
            {
                Main.instance.MouseTextNoOverride(Language.GetTextValue("GameUI.Bestiary"), 0, 0, -1, -1, -1, -1, 0);
            }
        }
References Terraria.GameContent.TextureAssets.BestiaryMenuButton, Terraria.Main.bestiaryMouseOver, Terraria.Main.BestiaryUI, Microsoft.Xna.Framework.Rectangle.Center, Terraria.Main.ChestOrShopUIVisible, Microsoft.Xna.Framework.Rectangle.Contains(), Terraria.Main.DoStatefulTickSound(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Main.editChest, Terraria.Localization.Language.GetTextValue(), Terraria.GameInput.PlayerInput.IgnoreMouseInterface, Terraria.Main.instance, int, Terraria.GameContent.TextureAssets.InventoryBack, Terraria.Main.inventoryScale, Terraria.Main.LocalPlayerHasPendingInventoryActions(), Terraria.Player.mouseInterface, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.Main.mouseText, Terraria.Main.MouseTextNoOverride(), Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.GameContent.UI.States.UIBestiaryTest.OnOpenPage(), Terraria.UI.IngameFancyUI.OpenUIState(), Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.UI.Gamepad.UILinkPointNavigator.SetPosition(), Terraria.Player.SetTalkNPC(), Terraria.Main.spriteBatch, System.value, ReLogic.Content.Asset< T >.Value, and Microsoft.Xna.Framework.Color.White.
Referenced by Terraria.Main.DrawInventory().