Terraria Decompiled: Terraria.Main.ClampScreenPositionToWorld
ClampScreenPositionToWorld()
static void Terraria.Main.ClampScreenPositionToWorld () inline static
Definition at line 65007 of file Main.cs.
        {
            if (DebugOptions.noLimits)
            {
                return;
            }
            Microsoft.Xna.Framework.Rectangle worldPlayArea = WorldUtils.GetWorldPlayArea();
            Vector2 vector = worldPlayArea.TopLeft() - Main.GameViewMatrix.Translation;
            Vector2 vector2 = worldPlayArea.BottomRight() - Main.Camera.ScaledSize - Main.GameViewMatrix.Translation;
            vector = Utils.Round(vector);
            vector2 = Utils.Round(vector2);
            Main.screenPosition = Vector2.Clamp(Main.screenPosition, vector, vector2);
        }
References Microsoft.Xna.Framework.Vector2.Clamp(), Terraria.Main.GameViewMatrix, Terraria.WorldBuilding.WorldUtils.GetWorldPlayArea(), Terraria.Testing.DebugOptions.noLimits, Terraria.Utils.Round(), Terraria.Main.screenPosition, and Terraria.Graphics.SpriteViewMatrix.Translation.
Referenced by Terraria.Main.DoDraw_UpdateCameraPosition(), and Terraria.GameContent.UI.States.UIWorldGenDebug.Update().