Terraria Decompiled: Terraria.Main.SelectPlayer
SelectPlayer()
static void Terraria.Main.SelectPlayer (PlayerFileData data) inline static
Definition at line 67555 of file Main.cs.
        {
            if (data.Player.loadStatus != StatusID.Ok)
            {
                throw new Exception("Tried to select a player with loadStatus: " + data.Player.loadStatus);
            }
            Main.myPlayer = 0;
            Main.ServerSideCharacter = false;
            data.SetAsActive();
            if (Main._pendingCharacterSelect != null)
            {
                Main._pendingCharacterSelect();
                Main._pendingCharacterSelect = null;
                return;
            }
            if (!Main.menuMultiplayer)
            {
                Main.LocalPlayer.position = Vector2.Zero;
                Main.LoadWorlds();
                SoundEngine.PlaySound(10, -1, -1, 1, 1f, 0f);
                Main.menuMode = 6;
                return;
            }
            SoundEngine.PlaySound(10, -1, -1, 1, 1f, 0f);
            if (Main.autoJoin)
            {
                if (Netplay.SetRemoteIP(Main.getIP))
                {
                    Main.menuMode = 10;
                    Netplay.StartTcpClient();
                }
                Main.autoJoin = false;
                return;
            }
            if (Main.menuServer)
            {
                Main.LoadWorlds();
                Main.menuMode = 6;
                return;
            }
            Main.menuMode = 13;
            Main.clrInput();
        }
References Terraria.Main._pendingCharacterSelect, Terraria.Main.autoJoin, Terraria.Main.clrInput(), Terraria.Main.getIP, Terraria.Player.loadStatus, Terraria.Main.LoadWorlds(), Terraria.Main.menuMultiplayer, Terraria.Main.menuServer, Terraria.ID.StatusID.Ok, Terraria.IO.PlayerFileData.Player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.IO.PlayerFileData.SetAsActive(), Terraria.Netplay.SetRemoteIP(), Terraria.Netplay.StartTcpClient(), and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.UI.Elements.UICharacterListItem.PlayGame(), and Terraria.Testing.QuickLoad.JoinWorld.SelectPlayerAndWorld().