Terraria Decompiled: Terraria.Main.updateCloudLayer
updateCloudLayer()
void Terraria.Main.updateCloudLayer () inline
Definition at line 11686 of file Main.cs.
        {
            if (Main.netMode == 1)
            {
                return;
            }
            if (Main.netMode == 0 && Main.gameMenu)
            {
                return;
            }
            int num = 86400;
            int num2 = num / 24;
            float num3 = Math.Max(1f, 1f + 4f * Main.cloudAlpha);
            if (Main.cloudBGActive > 0f)
            {
                if (Main.cloudBGActive > 1f)
                {
                    Main.cloudBGActive -= (float)Main.dayRate / num3;
                }
                if (Main.cloudBGActive < 1f)
                {
                    Main.cloudBGActive = 1f;
                }
                if (Main.cloudBGActive == 1f && Main.rand.Next((int)((float)(num2 * 2 / Math.Max(Main.dayRate, 1)) * num3)) == 0)
                {
                    Main.cloudBGActive = (float)(-(float)Main.rand.Next(num2 * 4, num * 4));
                    if (Main.netMode == 2)
                    {
                        NetMessage.SendData(7, -1, -1, null, 0, 0f, 0f, 0f, 0, 0, 0);
                        return;
                    }
                }
            }
            else
            {
                if (Main.cloudBGActive < 0f)
                {
                    Main.cloudBGActive += (float)Main.dayRate * num3;
                    if (Main.raining)
                    {
                        Main.cloudBGActive += (float)(2 * Main.dayRate) * num3;
                    }
                }
                if (Main.cloudBGActive > 0f)
                {
                    Main.cloudBGActive = 0f;
                }
                if (Main.cloudBGActive == 0f && Main.rand.Next((int)((float)(num2 * 12 / ((Main.dayRate == 0) ? 1 : Main.dayRate)) / num3)) == 0)
                {
                    Main.cloudBGActive = (float)Main.rand.Next(num2 * 3, num * 2);
                    if (Main.netMode == 2)
                    {
                        NetMessage.SendData(7, -1, -1, null, 0, 0f, 0f, 0f, 0, 0, 0);
                        return;
                    }
                }
                else if (Main.IsItStorming)
                {
                    Main.cloudBGActive = (float)Main.rand.Next(num2, num2 * 4);
                    if (Main.netMode == 2)
                    {
                        NetMessage.SendData(7, -1, -1, null, 0, 0f, 0f, 0f, 0, 0, 0);
                    }
                }
            }
        }
References Terraria.Main.cloudAlpha, Terraria.Main.cloudBGActive, Terraria.Main.dayRate, Terraria.Main.gameMenu, Terraria.Main.IsItStorming, System.Math.Max(), Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.raining, Terraria.Main.rand, and Terraria.NetMessage.SendData().