Terraria Decompiled: Terraria.Main.DrawDebugSectionsOnMap
DrawDebugSectionsOnMap()
void Terraria.Main.DrawDebugSectionsOnMap (float X, float Y, float left, float top, float scale) inline private
Definition at line 57006 of file Main.cs.
        {
            for (int i = 0; i < Main.maxSectionsX; i++)
            {
                for (int j = 0; j < Main.maxSectionsY; j++)
                {
                    if (ActiveSections.IsSectionActive(new Microsoft.Xna.Framework.Point(i, j)))
                    {
                        float num = ((float)(i * 200) - left) * scale + X;
                        float num2 = ((float)(j * 150) - top) * scale + Y;
                        Microsoft.Xna.Framework.Color color = Microsoft.Xna.Framework.Color.DarkGreen * Utils.Remap((float)ActiveSections.TimeTillInactive(new Microsoft.Xna.Framework.Point(i, j)), 0f, ActiveSections.SectionInactiveTime, 0.25f, 0.6f, true);
                        Main.spriteBatch.Draw(TextureAssets.MagicPixel.Value, new Vector2(num, num2), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, 1, 1)), color, 0f, Vector2.Zero, new Vector2(200f * scale, 150f * scale), SpriteEffects.None, 0f);
                    }
                }
            }
        }
References Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.DataStructures.ActiveSections.IsSectionActive(), Terraria.GameContent.TextureAssets.MagicPixel, Terraria.Main.maxSectionsX, Terraria.Main.maxSectionsY, Terraria.Utils.Remap(), Terraria.DataStructures.ActiveSections.SectionInactiveTime, Terraria.Main.spriteBatch, Terraria.DataStructures.ActiveSections.TimeTillInactive(), ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Input.X, Microsoft.Xna.Framework.Input.Y, and Microsoft.Xna.Framework.Vector2.Zero.