Terraria Decompiled: Terraria.Main.IsTileBiomeSightable
IsTileBiomeSightable()
static bool Terraria.Main.IsTileBiomeSightable (ushort type, short tileFrameX, short tileFrameY, ref Microsoft::Xna::Framework::Color sightColor) inline static
Definition at line 20676 of file Main.cs.
        {
            if (TileID.Sets.CorruptBiomeSight[(int)type] || (Main.remixWorld && type == 474))
            {
                sightColor = new Microsoft.Xna.Framework.Color(200, 100, 240);
                return true;
            }
            if (TileID.Sets.CrimsonBiomeSight[(int)type] || (Main.remixWorld && type == 195))
            {
                sightColor = new Microsoft.Xna.Framework.Color(255, 100, 100);
                return true;
            }
            if (TileID.Sets.HallowBiomeSight[(int)type])
            {
                sightColor = new Microsoft.Xna.Framework.Color(255, 160, 240);
                return true;
            }
            return false;
        }
References Terraria.ID.TileID.Sets.CorruptBiomeSight, Terraria.ID.TileID.Sets.CrimsonBiomeSight, Terraria.ID.TileID.Sets.HallowBiomeSight, and Terraria.Main.remixWorld.
Referenced by Terraria.GameContent.Drawing.TileDrawing.DrawAnimatedTile_AdjustForVisionChangers(), Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile(), and Terraria.GameContent.Drawing.TileDrawing.DrawVineStrip().