Terraria Decompiled: Terraria.Main.DoUpdateInWorld
DoUpdateInWorld()
void Terraria.Main.DoUpdateInWorld (Stopwatch sw) inline private
Definition at line 16231 of file Main.cs.
        {
            DebugLineDraw.PreWorldUpdate();
            this.UpdateParticleSystems_World();
            Main.tileSolid[379] = false;
            int num = 0;
            int num2 = 0;
            Main.sittingManager.ClearPlayerAnchors();
            Main.sleepingManager.ClearPlayerAnchors();
            for (int i = 0; i < 255; i++)
            {
                if (Main.player[i].active)
                {
                    try
                    {
                        Main.player[i].Update(i);
                        if (Main.player[i].active && !Main.player[i].ghost)
{
                            num++;
                            if (Main.player[i].sleeping.FullyFallenAsleep)
{
                                num2++;
                            }
                        }
                    }
                    catch
                    {
                        if (!Main.ignoreErrors)
{
                            throw;
                        }
                    }
                }
            }
            Main.CurrentFrameFlags.ActivePlayersCount = num;
            Main.CurrentFrameFlags.SleepingPlayersCount = num2;
            if (Main.netMode != 2)
            {
                int num3 = Main.myPlayer;
                if (Main.player[num3].creativeGodMode)
                {
                    Main.player[num3].statLife = Main.player[num3].statLifeMax2;
                    Main.player[num3].statMana = Main.player[num3].statManaMax2;
                    Main.player[num3].breath = Main.player[num3].breathMax;
                }
            }
            Main._gameUpdateCount += 1U;
            NPC.RevengeManager.Update();
            if (Main.netMode != 1)
            {
                try
                {
                    NPC.SpawnNPC();
                }
                catch
                {
                }
            }
            if (Main.netMode != 1)
            {
                PressurePlateHelper.Update();
            }
            for (int j = 0; j < 255; j++)
            {
                Main.player[j].nearbyActiveNPCs = 0f;
            }
            Main.CheckBossIndexes();
            Main.sittingManager.ClearNPCAnchors();
            Main.sleepingManager.ClearNPCAnchors();
            NPC.taxCollector = false;
            NPC.ClearFoundActiveNPCs();
            NPC.UpdateFoundActiveNPCs();
            FixExploitManEaters.Update();
            if (Main.netMode != 1)
            {
                Main.BestiaryTracker.Sights.ScanWorldForFinds();
            }
            NPCDamageTracker.Update();
            bool flag = false;
            if (NPC.offSetDelayTime > 0)
            {
                NPC.offSetDelayTime--;
            }
            if (Main.remixWorld && NPC.empressRageMode && !NPC.AnyNPCs(636))
            {
                NPC.empressRageMode = false;
            }
            if (Main.netMode != 1 && Main.afterPartyOfDoom && !BirthdayParty.PartyIsUp)
            {
                for (int k = 0; k < Main.maxNPCs; k++)
                {
                    NPC npc = Main.npc[k];
                    if (npc.active && npc.townNPC && npc.type != 37 && npc.type != 453 && npc.type != 368 && npc.type != 680 && npc.type != 20)
                    {
                        npc.StrikeNPCNoInteraction(9999, 10f, -npc.direction, false, false, false);
                        if (Main.netMode == 2)
{
                            NetMessage.SendData(28, -1, -1, null, k, 9999f, 10f, (float)(-(float)npc.direction), 0, 0, 0);
                        }
                    }
                }
                NPC.savedMech = false;
                NPC.unlockedPartyGirlSpawn = false;
                NPC.unlockedPrincessSpawn = false;
                NPC.unlockedSlimeRainbowSpawn = false;
                NPC.unlockedSlimeGreenSpawn = false;
                NPC.boughtBunny = false;
                Main.afterPartyOfDoom = false;
            }
            if (NPC.brainOfGravity >= 0 && NPC.brainOfGravity < Main.maxNPCs && (!Main.npc[NPC.brainOfGravity].active || Main.npc[NPC.brainOfGravity].type != 266))
            {
                NPC.brainOfGravity = -1;
            }
            int l = 0;
            while (l < Main.maxNPCs)
            {
                if (Main.ignoreErrors)
                {
                    try
                    {
                        Main.npc[l].UpdateNPC(l);
                        if (Main.npc[l].active && (Main.npc[l].boss || NPCID.Sets.DangerThatPreventsOtherDangers[Main.npc[l].type]))
{
                            flag = true;
                        }
                        goto IL_03B3;
                    }
                    catch (Exception)
                    {
                        Main.npc[l] = new NPC();
                        goto IL_03B3;
                    }
                    goto IL_03A4;
                }
                goto IL_03A4;
                IL_03B3:
                l++;
                continue;
                IL_03A4:
                Main.npc[l].UpdateNPC(l);
                goto IL_03B3;
            }
            Main.CurrentFrameFlags.AnyActiveBossNPC = flag;
            if (Main.netMode != 2)
            {
                int m = 0;
                while (m < 600)
                {
                    if (Main.ignoreErrors)
                    {
                        try
{
                            Main.gore[m].Update();
                            goto IL_0408;
                        }
                        catch
{
                            Main.gore[m] = new Gore();
                            goto IL_0408;
                        }
                        goto IL_03FB;
                    }
                    goto IL_03FB;
                    IL_0408:
                    m++;
                    continue;
                    IL_03FB:
                    Main.gore[m].Update();
                    goto IL_0408;
                }
            }
            LockOnHelper.SetUP();
            Main.CurrentFrameFlags.HadAnActiveInteractableProjectile = false;
            this.PreUpdateAllProjectiles();
            int n = 0;
            while (n < 1000)
            {
                Main.ProjectileUpdateLoopIndex = n;
                if (Main.ignoreErrors)
                {
                    try
                    {
                        Main.projectile[n].Update(n);
                        goto IL_046B;
                    }
                    catch
                    {
                        Main.projectile[n] = new Projectile();
                        goto IL_046B;
                    }
                    goto IL_045C;
                }
                goto IL_045C;
                IL_046B:
                n++;
                continue;
                IL_045C:
                Main.projectile[n].Update(n);
                goto IL_046B;
            }
            Main.ProjectileUpdateLoopIndex = -1;
            this.PostUpdateAllProjectiles();
            LockOnHelper.SetDOWN();
            int num4 = 0;
            while (num4 < 400)
            {
                if (Main.ignoreErrors)
                {
                    try
                    {
                        Main.item[num4].UpdateItem(num4);
                        goto IL_04D6;
                    }
                    catch
                    {
                        Main.item[num4] = new WorldItem();
                        Main.item[num4].whoAmI = num4;
                        goto IL_04D6;
                    }
                    goto IL_04C7;
                }
                goto IL_04C7;
                IL_04D6:
                num4++;
                continue;
                IL_04C7:
                Main.item[num4].UpdateItem(num4);
                goto IL_04D6;
            }
            if (Main.netMode != 2)
            {
                if (Main.ignoreErrors)
                {
                    try
                    {
                        Dust.UpdateDust();
                        goto IL_0533;
                    }
                    catch
                    {
                        for (int num5 = 0; num5 < 6000; num5++)
{
                            Main.dust[num5] = new Dust();
                            Main.dust[num5].dustIndex = num5;
                        }
                        goto IL_0533;
                    }
                }
                Dust.UpdateDust();
            }
            IL_0533:
            LeashedEntity.UpdateEntities();
            if (Main.netMode != 2)
            {
                CombatText.UpdateCombatText();
                PopupText.UpdateItemText();
            }
            if (Main.ignoreErrors)
            {
                try
                {
                    Main.UpdateTime();
                    goto IL_0566;
                }
                catch
                {
                    Main.checkForSpawns = 0;
                    goto IL_0566;
                }
            }
            Main.UpdateTime();
            IL_0566:
            Main.tileSolid[379] = true;
            if (Main.gameMenu && Main.netMode != 2)
            {
                return;
            }
            if (Main.netMode != 1)
            {
                if (Main.ignoreErrors)
                {
                    try
                    {
                        WorldGen.UpdateWorld();
                        Main.UpdateInvasion();
                        goto IL_05AA;
                    }
                    catch
                    {
                        goto IL_05AA;
                    }
                }
                WorldGen.UpdateWorld();
                Main.UpdateInvasion();
            }
            IL_05AA:
            if (Main.ignoreErrors)
            {
                try
                {
                    if (Main.netMode == 2)
                    {
                        Main.UpdateServer();
                    }
                    if (Main.netMode == 1)
                    {
                        Main.UpdateClient();
                    }
                    goto IL_05F2;
                }
                catch
                {
                    int num6 = Main.netMode;
                    goto IL_05F2;
                }
            }
            if (Main.netMode == 2)
            {
                Main.UpdateServer();
            }
            if (Main.netMode == 1)
            {
                Main.UpdateClient();
            }
            IL_05F2:
            Main.chatMonitor.Update();
            Main.upTimer = (float)sw.Elapsed.TotalMilliseconds;
            if (Main.upTimerMaxDelay > 0f)
            {
                Main.upTimerMaxDelay -= 1f;
            }
            else
            {
                Main.upTimerMax = 0f;
            }
            if (Main.upTimer > Main.upTimerMax)
            {
                Main.upTimerMax = Main.upTimer;
                Main.upTimerMaxDelay = 400f;
            }
            Chest.UpdateChestFrames();
            this._ambientWindSys.Update();
            this.TilesRenderer.Update();
            this.WallsRenderer.Update();
            Main.UpdateCameraPan();
            if (Main.cameraLerp > 0f)
            {
                Main.cameraLerpTimer++;
                if (Main.cameraLerpTimer >= Main.cameraLerpTimeToggle)
                {
                    Main.cameraLerp += (float)((Main.cameraLerpTimer - Main.cameraLerpTimeToggle) / 3 + 1) * 0.001f;
                }
                if (Main.cameraLerp > 1f)
                {
                    Main.cameraLerp = 1f;
                }
            }
            Main.SceneState.Update(Main.SceneMetrics);
            if (Main.netMode == 1)
            {
                Ping.Update();
            }
        }
References Terraria.NPC.active, Terraria.Player.active, Terraria.Main.afterPartyOfDoom, Terraria.NPC.AnyNPCs(), Terraria.Main.BestiaryTracker, Terraria.NPC.boss, Terraria.NPC.brainOfGravity, Terraria.Player.breath, Terraria.Player.breathMax, Terraria.Main.cameraLerp, Terraria.Main.cameraLerpTimer, Terraria.Main.cameraLerpTimeToggle, Terraria.Main.chatMonitor, Terraria.Main.CheckBossIndexes(), Terraria.NPC.ClearFoundActiveNPCs(), Terraria.DataStructures.AnchoredEntitiesCollection.ClearNPCAnchors(), Terraria.DataStructures.AnchoredEntitiesCollection.ClearPlayerAnchors(), Terraria.Player.creativeGodMode, Terraria.ID.NPCID.Sets.DangerThatPreventsOtherDangers, Terraria.Entity.direction, Terraria.Main.dust, Terraria.Dust.dustIndex, Terraria.NPC.empressRageMode, Terraria.GameContent.PlayerSleepingHelper.FullyFallenAsleep, Terraria.Main.gameMenu, Terraria.Player.ghost, Terraria.Main.gore, Terraria.Main.ignoreErrors, Terraria.Main.item, Terraria.Main.maxNPCs, Terraria.Main.myPlayer, Terraria.Player.nearbyActiveNPCs, Terraria.Main.netMode, Terraria.Enums.NPC, Terraria.Main.npc, Terraria.NPC.offSetDelayTime, Terraria.GameContent.Events.BirthdayParty.PartyIsUp, Terraria.Main.player, Terraria.Testing.DebugLineDraw.PreWorldUpdate(), Terraria.Main.projectile, Terraria.Main.remixWorld, Terraria.NPC.RevengeManager, Terraria.GameContent.Bestiary.NPCWasNearPlayerTracker.ScanWorldForFinds(), Terraria.Main.SceneMetrics, Terraria.Main.SceneState, Terraria.NetMessage.SendData(), Terraria.GameInput.LockOnHelper.SetDOWN(), Terraria.GameInput.LockOnHelper.SetUP(), Terraria.GameContent.Bestiary.BestiaryUnlocksTracker.Sights, Terraria.Main.sittingManager, Terraria.Player.sleeping, Terraria.Main.sleepingManager, Terraria.NPC.SpawnNPC(), Terraria.Player.statLife, Terraria.Player.statLifeMax2, Terraria.Player.statMana, Terraria.Player.statManaMax2, Terraria.NPC.StrikeNPCNoInteraction(), Terraria.Main.tileSolid, Terraria.NPC.townNPC, Terraria.NPC.type, Microsoft.Xna.Framework.Input.U, Terraria.GameContent.CoinLossRevengeSystem.Update(), Terraria.GameContent.FixExploitManEaters.Update(), Terraria.GameContent.NPCDamageTracker.Update(), Terraria.GameContent.PressurePlateHelper.Update(), Terraria.GameContent.UI.Chat.IChatMonitor.Update(), Terraria.Gore.Update(), Terraria.Net.Ping.Update(), Terraria.Player.Update(), Terraria.Projectile.Update(), Terraria.SceneState.Update(), Terraria.Main.UpdateCameraPan(), Terraria.Chest.UpdateChestFrames(), Terraria.Main.UpdateClient(), Terraria.CombatText.UpdateCombatText(), Terraria.Dust.UpdateDust(), Terraria.GameContent.LeashedEntity.UpdateEntities(), Terraria.NPC.UpdateFoundActiveNPCs(), Terraria.Main.UpdateInvasion(), Terraria.WorldItem.UpdateItem(), Terraria.PopupText.UpdateItemText(), Terraria.NPC.UpdateNPC(), Terraria.Main.UpdateServer(), Terraria.Main.UpdateTime(), Terraria.WorldGen.UpdateWorld(), Terraria.Main.upTimer, Terraria.Main.upTimerMax, Terraria.Main.upTimerMaxDelay, and Terraria.Entity.whoAmI.