Terraria Decompiled: Terraria.Main.Camera
Camera
Camera Terraria.Main.Camera = new Camera() static
Definition at line 68128 of file Main.cs.
Referenced by Terraria.Main.Ambience(), Terraria.GameContent.Skies.AmbientSky.SkyEntity.CommonDraw(), Terraria.Audio.ActiveSound.DetermineIntendedVolume(), Terraria.GameContent.UI.LegacyMultiplayerClosePlayersOverlay.Draw(), Terraria.GameContent.Drawing.TileDrawing.Draw(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.Draw(), Terraria.GameContent.Tile_Entities.TEHatRack.Draw(), Terraria.GameContent.Animations.Segments.PlayerSegment.Draw(), Terraria.GameContent.Drawing.TileDrawing.DrawAnyDirectionalGrass(), Terraria.Main.DrawBackground_DirtBackground(), Terraria.Main.DrawClothesWindow(), Terraria.GameContent.Drawing.TileDrawing.DrawGrass(), Terraria.Main.DrawInterface_GolfBallIndicator(), Terraria.Main.DrawInterface_Resources_GolfPower(), Terraria.GameContent.Drawing.TileDrawing.DrawLiquidBehindTiles(), Terraria.Main.DrawMap(), Terraria.Main.DrawMenu(), Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileGrass(), Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileVines(), Terraria.GameContent.UI.NewMultiplayerClosePlayersOverlay.PlayerOffScreenCache.DrawPlayerHead(), Terraria.Main.DrawPlayers_AfterProjectiles(), Terraria.Main.DrawPlayers_BehindNPCs(), Terraria.GameContent.Golf.GolfHelper.DrawPredictionLine(), Terraria.Main.DrawProj(), Terraria.GameContent.Drawing.TileDrawing.DrawReverseVines(), Terraria.GameContent.UI.Elements.UICharacter.DrawSelf(), Terraria.GameContent.UI.Elements.UIHairStyleButton.DrawSelf(), Terraria.Main.DrawSuperSpecialProjectiles(), Terraria.GameContent.Drawing.TileDrawing.DrawTrees(), Terraria.GameContent.Drawing.TileDrawing.DrawVines(), Terraria.Graphics.Capture.CaptureInterface.FullScreenArea(), Terraria.Main.GetAreaToLight(), Terraria.GameContent.Skies.AmbientSky.SkyEntity.GetDrawPositionByDepth(), Terraria.GameContent.Drawing.TileDrawing.GetScreenDrawArea(), Terraria.GameContent.Skies.AmbientSky.SkyEntity.Helper_GetOpacityWithAccountingForOceanWaterLine(), Terraria.Player.ItemCheck_PlayInstruments(), Terraria.Player.ItemCheck_Shoot(), Terraria.Main.OldDrawBackground(), Terraria.Audio.LegacySoundPlayer.PlaySound(), Terraria.Graphics.Light.LegacyLighting.ProcessArea(), Terraria.GameContent.Drawing.WindGrid.ScanPlayer(), Terraria.GameContent.Skies.AmbientSky.SkyEntity.SetPositionInWorldBasedOnScreenSpace(), Terraria.Main.snowing(), Terraria.Cloud.UpdateCloudParallax(), and Terraria.Graphics.WorldSceneLayerTarget.UpdateContent().