Terraria Decompiled: Terraria.Main.SetBackColor
SetBackColor()
static void Terraria.Main.SetBackColor (Main::InfoToSetBackColor info, out Microsoft::Xna::Framework::Color sunColor, out Microsoft::Xna::Framework::Color moonColor) inline static private
Definition at line 64515 of file Main.cs.
        {
            double num = Main.time;
            Microsoft.Xna.Framework.Color white = Microsoft.Xna.Framework.Color.White;
            sunColor = Microsoft.Xna.Framework.Color.White;
            moonColor = Microsoft.Xna.Framework.Color.White;
            bool isInGameMenuOrIsServer = info.isInGameMenuOrIsServer;
            if (Main.dayTime)
            {
                if (num < 13500.0)
                {
                    float num2 = (float)(num / 13500.0);
                    sunColor.R = (byte)(num2 * 200f + 55f);
                    sunColor.G = (byte)(num2 * 180f + 75f);
                    sunColor.B = (byte)(num2 * 250f + 5f);
                    white.R = (byte)(num2 * 230f + 25f);
                    white.G = (byte)(num2 * 220f + 35f);
                    white.B = (byte)(num2 * 220f + 35f);
                }
                if (num > 45900.0)
                {
                    float num2 = (float)(1.0 - (num / 54000.0 - 0.85) * 6.666666666666667);
                    sunColor.R = (byte)(num2 * 120f + 55f);
                    sunColor.G = (byte)(num2 * 100f + 25f);
                    sunColor.B = (byte)(num2 * 120f + 55f);
                    white.R = (byte)(num2 * 200f + 35f);
                    white.G = (byte)(num2 * 85f + 35f);
                    white.B = (byte)(num2 * 135f + 35f);
                }
                else if (num > 37800.0)
                {
                    float num2 = (float)(1.0 - (num / 54000.0 - 0.7) * 6.666666666666667);
                    sunColor.R = (byte)(num2 * 80f + 175f);
                    sunColor.G = (byte)(num2 * 130f + 125f);
                    sunColor.B = (byte)(num2 * 100f + 155f);
                    white.R = (byte)(num2 * 20f + 235f);
                    white.G = (byte)(num2 * 135f + 120f);
                    white.B = (byte)(num2 * 85f + 170f);
                }
            }
            if (!Main.dayTime)
            {
                if (info.BloodMoonActive)
                {
                    if (num < 16200.0)
                    {
                        float num2 = (float)(1.0 - num / 16200.0);
                        moonColor.R = (byte)(num2 * 10f + 205f);
                        moonColor.G = (byte)(num2 * 170f + 55f);
                        moonColor.B = (byte)(num2 * 200f + 55f);
                        white.R = (byte)(40f - num2 * 40f + 35f);
                        white.G = (byte)(num2 * 20f + 15f);
                        white.B = (byte)(num2 * 20f + 15f);
                    }
                    else if (num >= 16200.0)
                    {
                        float num2 = (float)((num / 32400.0 - 0.5) * 2.0);
                        moonColor.R = (byte)(num2 * 50f + 205f);
                        moonColor.G = (byte)(num2 * 100f + 155f);
                        moonColor.B = (byte)(num2 * 100f + 155f);
                        moonColor.R = (byte)(num2 * 10f + 205f);
                        moonColor.G = (byte)(num2 * 170f + 55f);
                        moonColor.B = (byte)(num2 * 200f + 55f);
                        white.R = (byte)(40f - num2 * 40f + 35f);
                        white.G = (byte)(num2 * 20f + 15f);
                        white.B = (byte)(num2 * 20f + 15f);
                    }
                }
                else if (num < 16200.0)
                {
                    float num2 = (float)(1.0 - num / 16200.0);
                    moonColor.R = (byte)(num2 * 10f + 205f);
                    moonColor.G = (byte)(num2 * 70f + 155f);
                    moonColor.B = (byte)(num2 * 100f + 155f);
                    white.R = (byte)(num2 * 30f + 5f);
                    white.G = (byte)(num2 * 30f + 5f);
                    white.B = (byte)(num2 * 30f + 5f);
                }
                else if (num >= 16200.0)
                {
                    float num2 = (float)((num / 32400.0 - 0.5) * 2.0);
                    moonColor.R = (byte)(num2 * 50f + 205f);
                    moonColor.G = (byte)(num2 * 100f + 155f);
                    moonColor.B = (byte)(num2 * 100f + 155f);
                    white.R = (byte)(num2 * 20f + 5f);
                    white.G = (byte)(num2 * 30f + 5f);
                    white.B = (byte)(num2 * 30f + 5f);
                }
                if (Main.dontStarveWorld)
                {
                    DontStarveSeed.ModifyNightColor(ref white, ref moonColor);
                }
            }
            if (Main.cloudAlpha > 0f && !Main.remixWorld)
            {
                float num3 = 1f - Main.cloudAlpha * 0.9f * Main.atmo;
                white.R = (byte)((float)white.R * num3);
                white.G = (byte)((float)white.G * num3);
                white.B = (byte)((float)white.B * num3);
            }
            if (info.GraveyardInfluence > 0f && !Main.remixWorld)
            {
                float num4 = 1f - info.GraveyardInfluence * 0.6f;
                white.R = (byte)((float)white.R * num4);
                white.G = (byte)((float)white.G * num4);
                white.B = (byte)((float)white.B * num4);
            }
            if (isInGameMenuOrIsServer && !Main.dayTime)
            {
                white.R = 35;
                white.G = 35;
                white.B = 35;
            }
            if (info.CorruptionBiomeInfluence > 0f)
            {
                float num5 = info.CorruptionBiomeInfluence;
                if (num5 > 1f)
                {
                    num5 = 1f;
                }
                int num6 = (int)white.R;
                int num7 = (int)white.G;
                int num8 = (int)white.B;
                num6 -= (int)(90f * num5 * ((float)white.R / 255f));
                num7 -= (int)(140f * num5 * ((float)white.G / 255f));
                num8 -= (int)(70f * num5 * ((float)white.B / 255f));
                if (num6 < 15)
                {
                    num6 = 15;
                }
                if (num7 < 15)
                {
                    num7 = 15;
                }
                if (num8 < 15)
                {
                    num8 = 15;
                }
                DontStarveSeed.FixBiomeDarkness(ref white, ref num6, ref num7, ref num8);
                white.R = (byte)num6;
                white.G = (byte)num7;
                white.B = (byte)num8;
                num6 = (int)sunColor.R;
                num7 = (int)sunColor.G;
                num8 = (int)sunColor.B;
                num6 -= (int)(100f * num5 * ((float)sunColor.R / 255f));
                num7 -= (int)(100f * num5 * ((float)sunColor.G / 255f));
                num8 -= (int)(0f * num5 * ((float)sunColor.B / 255f));
                if (num6 < 15)
                {
                    num6 = 15;
                }
                if (num7 < 15)
                {
                    num7 = 15;
                }
                if (num8 < 15)
                {
                    num8 = 15;
                }
                sunColor.R = (byte)num6;
                sunColor.G = (byte)num7;
                sunColor.B = (byte)num8;
            }
            if (info.CrimsonBiomeInfluence > 0f)
            {
                float num9 = info.CrimsonBiomeInfluence;
                if (num9 > 1f)
                {
                    num9 = 1f;
                }
                int num10 = (int)white.R;
                int num11 = (int)white.G;
                int num12 = (int)white.B;
                num10 -= (int)(40f * num9 * ((float)white.G / 255f));
                num11 -= (int)(110f * num9 * ((float)white.G / 255f));
                num12 -= (int)(140f * num9 * ((float)white.B / 255f));
                if (num10 < 15)
                {
                    num10 = 15;
                }
                if (num11 < 15)
                {
                    num11 = 15;
                }
                if (num12 < 15)
                {
                    num12 = 15;
                }
                DontStarveSeed.FixBiomeDarkness(ref white, ref num10, ref num11, ref num12);
                white.R = (byte)num10;
                white.G = (byte)num11;
                white.B = (byte)num12;
                num10 = (int)sunColor.R;
                num11 = (int)sunColor.G;
                num12 = (int)sunColor.B;
                num11 -= (int)(90f * num9 * ((float)sunColor.G / 255f));
                num12 -= (int)(110f * num9 * ((float)sunColor.B / 255f));
                if (num10 < 15)
                {
                    num10 = 15;
                }
                if (num11 < 15)
                {
                    num11 = 15;
                }
                if (num12 < 15)
                {
                    num12 = 15;
                }
                sunColor.R = (byte)num10;
                sunColor.G = (byte)num11;
                sunColor.B = (byte)num12;
            }
            if (info.JungleBiomeInfluence > 0f)
            {
                float num13 = info.JungleBiomeInfluence;
                if (num13 > 1f)
                {
                    num13 = 1f;
                }
                int num14 = (int)white.R;
                int num15 = (int)white.G;
                int num16 = (int)white.B;
                num14 -= (int)(40f * num13 * ((float)white.R / 255f));
                num16 -= (int)(70f * num13 * ((float)white.B / 255f));
                if (num15 > 255)
                {
                    num15 = 255;
                }
                if (num15 < 15)
                {
                    num15 = 15;
                }
                if (num14 > 255)
                {
                    num14 = 255;
                }
                if (num14 < 15)
                {
                    num14 = 15;
                }
                if (num16 < 15)
                {
                    num16 = 15;
                }
                DontStarveSeed.FixBiomeDarkness(ref white, ref num14, ref num15, ref num16);
                white.R = (byte)num14;
                white.G = (byte)num15;
                white.B = (byte)num16;
                num14 = (int)sunColor.R;
                num15 = (int)sunColor.G;
                num16 = (int)sunColor.B;
                num14 -= (int)(30f * num13 * ((float)sunColor.R / 255f));
                num16 -= (int)(10f * num13 * ((float)sunColor.B / 255f));
                if (num14 < 15)
                {
                    num14 = 15;
                }
                if (num15 < 15)
                {
                    num15 = 15;
                }
                if (num16 < 15)
                {
                    num16 = 15;
                }
                sunColor.R = (byte)num14;
                sunColor.G = (byte)num15;
                sunColor.B = (byte)num16;
            }
            if (info.MushroomBiomeInfluence > 0f)
            {
                float mushroomBiomeInfluence = info.MushroomBiomeInfluence;
                int num17 = (int)white.R;
                int num18 = (int)white.G;
                int num19 = (int)white.B;
                num18 -= (int)(250f * mushroomBiomeInfluence * ((float)white.G / 255f));
                num17 -= (int)(250f * mushroomBiomeInfluence * ((float)white.R / 255f));
                num19 -= (int)(250f * mushroomBiomeInfluence * ((float)white.B / 255f));
                if (num18 < 15)
                {
                    num18 = 15;
                }
                if (num17 < 15)
                {
                    num17 = 15;
                }
                if (num19 < 15)
                {
                    num19 = 15;
                }
                DontStarveSeed.FixBiomeDarkness(ref white, ref num17, ref num18, ref num19);
                white.R = (byte)num17;
                white.G = (byte)num18;
                white.B = (byte)num19;
                num17 = (int)sunColor.R;
                num18 = (int)sunColor.G;
                num19 = (int)sunColor.B;
                num18 -= (int)(10f * mushroomBiomeInfluence * ((float)sunColor.G / 255f));
                num17 -= (int)(30f * mushroomBiomeInfluence * ((float)sunColor.R / 255f));
                num19 -= (int)(10f * mushroomBiomeInfluence * ((float)sunColor.B / 255f));
                if (num17 < 15)
                {
                    num17 = 15;
                }
                if (num18 < 15)
                {
                    num18 = 15;
                }
                if (num19 < 15)
                {
                    num19 = 15;
                }
                sunColor.R = (byte)num17;
                sunColor.G = (byte)num18;
                sunColor.B = (byte)num19;
                num17 = (int)moonColor.R;
                num18 = (int)moonColor.G;
                num19 = (int)moonColor.B;
                num18 -= (int)(140f * mushroomBiomeInfluence * ((float)moonColor.R / 255f));
                num17 -= (int)(170f * mushroomBiomeInfluence * ((float)moonColor.G / 255f));
                num19 -= (int)(190f * mushroomBiomeInfluence * ((float)moonColor.B / 255f));
                if (num17 < 15)
                {
                    num17 = 15;
                }
                if (num18 < 15)
                {
                    num18 = 15;
                }
                if (num19 < 15)
                {
                    num19 = 15;
                }
                moonColor.R = (byte)num17;
                moonColor.G = (byte)num18;
                moonColor.B = (byte)num19;
            }
            byte b = 15;
            switch (Main.GetMoonPhase())
            {
            case MoonPhase.Full:
                b = 19;
                break;
            case MoonPhase.ThreeQuartersAtLeft:
            case MoonPhase.ThreeQuartersAtRight:
                b = 17;
                break;
            case MoonPhase.HalfAtLeft:
            case MoonPhase.HalfAtRight:
                b = 15;
                break;
            case MoonPhase.QuarterAtLeft:
            case MoonPhase.QuarterAtRight:
                b = 13;
                break;
            case MoonPhase.Empty:
                b = 11;
                break;
            }
            if (Main.dontStarveWorld)
            {
                DontStarveSeed.ModifyMinimumLightColorAtNight(ref b);
            }
            if (white.R < b)
            {
                white.R = b;
            }
            if (white.G < b)
            {
                white.G = b;
            }
            if (white.B < b)
            {
                white.B = b;
            }
            if (info.BloodMoonActive)
            {
                if (white.R < 25)
                {
                    white.R = 25;
                }
                if (white.G < 25)
                {
                    white.G = 25;
                }
                if (white.B < 25)
                {
                    white.B = 25;
                }
            }
            if (Main.eclipse && Main.dayTime)
            {
                float num20 = 1242f;
                Main.eclipseLight = (float)(num / (double)num20);
                if (Main.eclipseLight > 1f)
                {
                    Main.eclipseLight = 1f;
                }
            }
            else if (Main.eclipseLight > 0f)
            {
                Main.eclipseLight -= 0.01f;
                if (Main.eclipseLight < 0f)
                {
                    Main.eclipseLight = 0f;
                }
            }
            if (Main.eclipseLight > 0f)
            {
                float num21 = 1f - 0.925f * Main.eclipseLight;
                float num22 = 1f - 0.96f * Main.eclipseLight;
                float num23 = 1f - 1f * Main.eclipseLight;
                int num24 = (int)((float)white.R * num21);
                int num25 = (int)((float)white.G * num22);
                int num26 = (int)((float)white.B * num23);
                white.R = (byte)num24;
                white.G = (byte)num25;
                white.B = (byte)num26;
                sunColor.R = byte.MaxValue;
                sunColor.G = 127;
                sunColor.B = 67;
                if (white.R < 20)
                {
                    white.R = 20;
                }
                if (white.G < 10)
                {
                    white.G = 10;
                }
                if (!Lighting.NotRetro)
                {
                    if (white.R < 20)
                    {
                        white.R = 20;
                    }
                    if (white.G < 14)
                    {
                        white.G = 14;
                    }
                    if (white.B < 6)
                    {
                        white.B = 6;
                    }
                }
            }
            if ((Main.remixWorld && !Main.gameMenu) || WorldGen.remixWorldGen)
            {
                white.R = 1;
                white.G = 1;
                white.B = 1;
            }
            if (Main.lightning > 0f)
            {
                float num27 = (float)white.R / 255f;
                float num28 = (float)white.G / 255f;
                float num29 = (float)white.B / 255f;
                num27 = MathHelper.Lerp(num27, 1f, Main.lightning);
                num28 = MathHelper.Lerp(num28, 1f, Main.lightning);
                num29 = MathHelper.Lerp(num29, 1f, Main.lightning);
                white.R = (byte)(num27 * 255f);
                white.G = (byte)(num28 * 255f);
                white.B = (byte)(num29 * 255f);
            }
            if (!info.BloodMoonActive)
            {
                moonColor = Microsoft.Xna.Framework.Color.White;
            }
            Main.instance.HorizonRenderer.ModifyHorizonLight(ref white);
            AuroraSky.ModifyTileColor(ref white, 0.08f);
            Main.ColorOfTheSkies = white;
        }
References Terraria.Main.atmo, Microsoft.Xna.Framework.Color.B, Terraria.Main.cloudAlpha, Terraria.Main.dayTime, Terraria.Main.dontStarveWorld, Terraria.Main.eclipse, Terraria.Main.eclipseLight, Terraria.GameContent.DontStarveSeed.FixBiomeDarkness(), Microsoft.Xna.Framework.Color.G, Terraria.Main.gameMenu, Terraria.Main.GetMoonPhase(), Terraria.Main.HorizonRenderer, System.info, Terraria.Main.instance, int, Microsoft.Xna.Framework.MathHelper.Lerp(), Terraria.Main.lightning, Terraria.GameContent.Drawing.IHorizonRenderer.ModifyHorizonLight(), Terraria.GameContent.DontStarveSeed.ModifyMinimumLightColorAtNight(), Terraria.GameContent.DontStarveSeed.ModifyNightColor(), Terraria.GameContent.Skies.AuroraSky.ModifyTileColor(), Terraria.Lighting.NotRetro, Microsoft.Xna.Framework.Color.R, Terraria.Main.remixWorld, Terraria.WorldGen.remixWorldGen, Terraria.Main.time, and Microsoft.Xna.Framework.Color.White.
Referenced by Terraria.Main.DoDraw(), and Terraria.Main.DrawCapture().