Terraria Decompiled: Terraria.Main.DrawWhip_RainbowWhip
DrawWhip_RainbowWhip()
static Vector2 Terraria.Main.DrawWhip_RainbowWhip (Projectile proj, Player theOwner, List< Vector2 > controlPoints) inline static
Definition at line 36139 of file Main.cs.
        {
            Texture2D value = TextureAssets.Projectile[proj.type].Value;
            Microsoft.Xna.Framework.Rectangle rectangle = value.Frame(1, 5, 0, 0, 0, 0);
            int height = rectangle.Height;
            rectangle.Height -= 2;
            Vector2 vector = rectangle.Size() / 2f;
            Vector2 vector2 = controlPoints[0];
            float miscCounterNormalized = theOwner.miscCounterNormalized;
            for (int i = 0; i < controlPoints.Count - 1; i++)
            {
                bool flag = true;
                Vector2 vector3 = vector;
                if (i != 0)
                {
                    if (i != 39)
                    {
                        flag = i % 2 == 0;
                        rectangle.Y = height * (1 + i % 3);
                    }
                    else
                    {
                        rectangle.Y = height * 4;
                    }
                }
                else
                {
                    vector3.Y -= 4f;
                }
                Vector2 vector4 = controlPoints[i];
                Vector2 vector5 = controlPoints[i + 1] - vector4;
                if (flag)
                {
                    Microsoft.Xna.Framework.Color color = Main.hslToRgb((miscCounterNormalized * 5f + (float)i * 0.05f) % 1f, 1f, 0.5f, byte.MaxValue);
                    Microsoft.Xna.Framework.Color color2 = color;
                    float lerpValue = Utils.GetLerpValue((float)(controlPoints.Count - 10), (float)(controlPoints.Count - 2), (float)i, true);
                    float num = MathHelper.Lerp(1f, 1f, lerpValue);
                    color2.A /= 2;
                    color2.A = (byte)((float)color2.A * lerpValue);
                    float num2 = vector5.ToRotation() - 1.5707964f;
                    Microsoft.Xna.Framework.Color color3 = Lighting.GetColor(vector4.ToTileCoordinates());
                    Main.spriteBatch.Draw(value, vector2 - Main.screenPosition, new Microsoft.Xna.Framework.Rectangle?(rectangle), Microsoft.Xna.Framework.Color.Lerp(color3, color2, 0.5f), num2, vector3, num, SpriteEffects.None, 0f);
                    color2.A = 0;
                    Main.spriteBatch.Draw(value, vector2 - Main.screenPosition, new Microsoft.Xna.Framework.Rectangle?(rectangle), color2 * 0.1f, num2, vector3, num * 1.2f, SpriteEffects.None, 0f);
                    if (i == 39)
                    {
                        color2 = color;
                        color2.A = 127;
                        Main.spriteBatch.Draw(value, vector2 - Main.screenPosition, new Microsoft.Xna.Framework.Rectangle?(rectangle), color2 * 0.3f, num2, vector3, num * 1.4f, SpriteEffects.None, 0f);
                    }
                }
                vector2 += vector5;
            }
            return vector2;
        }
References Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Lighting.GetColor(), Terraria.Utils.GetLerpValue(), Microsoft.Xna.Framework.Rectangle.Height, Terraria.Main.hslToRgb(), Microsoft.Xna.Framework.Color.Lerp(), Microsoft.Xna.Framework.MathHelper.Lerp(), Terraria.Player.miscCounterNormalized, Terraria.GameContent.TextureAssets.Projectile, Terraria.Main.screenPosition, Terraria.Main.spriteBatch, Terraria.Projectile.type, System.value, and ReLogic.Content.Asset< T >.Value.
Referenced by Terraria.Main.DrawWhip().