Terraria Decompiled: Terraria.Main.UpdateAudio_DecideOnTOWMusic
UpdateAudio_DecideOnTOWMusic()
void Terraria.Main.UpdateAudio_DecideOnTOWMusic () inline private
Definition at line 9797 of file Main.cs.
        {
            bool flag = false;
            bool flag2 = false;
            bool flag3 = false;
            bool flag4 = false;
            bool flag5 = false;
            bool flag6 = false;
            bool flag7 = false;
            bool flag8 = false;
            bool flag9 = false;
            bool flag10 = false;
            bool flag11 = false;
            bool flag12 = false;
            bool flag13 = false;
            bool flag14 = false;
            bool flag15 = false;
            bool flag16 = false;
            bool flag17 = false;
            if (!Main.showSplash)
            {
                Microsoft.Xna.Framework.Rectangle rectangle = new Microsoft.Xna.Framework.Rectangle((int)Main.screenPosition.X, (int)Main.screenPosition.Y, Main.screenWidth, Main.screenHeight);
                for (int i = 0; i < Main.maxNPCs; i++)
                {
                    if (Main.npc[i].active)
                    {
                        int num = 5000;
                        int num2 = 0;
                        int type = Main.npc[i].type;
                        if (type <= 266)
{
                            if (type <= 127)
{
                                if (type <= 111)
{
                                    if (type - 13 <= 2)
{
                                        num2 = 1;
                                        goto IL_0377;
                                    }
                                    if (type - 26 > 3 && type != 111)
{
                                        goto IL_0377;
                                    }
                                    goto IL_02C1;
                                }
                                else
{
                                    if (type - 113 <= 1)
{
                                        num2 = 3;
                                        goto IL_0377;
                                    }
                                    if (type - 125 <= 1)
{
                                        num2 = 2;
                                        goto IL_0377;
                                    }
                                    if (type != 127)
{
                                        goto IL_0377;
                                    }
                                }
                            }
                            else if (type <= 216)
{
                                if (type != 134)
{
                                    if (type - 143 <= 2)
{
                                        num2 = 11;
                                        goto IL_0377;
                                    }
                                    if (type - 212 > 4)
{
                                        goto IL_0377;
                                    }
                                    goto IL_02F3;
                                }
                            }
                            else if (type <= 245)
{
                                if (type == 222)
{
                                    num2 = 1;
                                    goto IL_0377;
                                }
                                if (type != 245)
{
                                    goto IL_0377;
                                }
                                num2 = 2;
                                goto IL_0377;
                            }
                            else
{
                                if (type - 262 <= 2)
{
                                    num2 = 6;
                                    goto IL_0377;
                                }
                                if (type != 266)
{
                                    goto IL_0377;
                                }
                                num2 = 1;
                                goto IL_0377;
                            }
                            num2 = 2;
                        }
                        else
{
                            if (type <= 491)
{
                                if (type <= 422)
{
                                    if (type == 370)
{
                                        num2 = 15;
                                        goto IL_0377;
                                    }
                                    switch (type)
{
                                    case 379:
                                        if (Main.npc[i].ai[3] >= 0f)
{
                                            num = 1600;
                                            num2 = 2;
                                            goto IL_0377;
                                        }
                                        goto IL_0377;
                                    case 380:
                                    case 384:
                                    case 387:
                                    case 392:
                                    case 393:
                                    case 394:
                                    case 396:
                                    case 397:
                                        goto IL_0377;
                                    case 381:
                                    case 382:
                                    case 383:
                                    case 385:
                                    case 386:
                                    case 388:
                                    case 389:
                                    case 390:
                                    case 391:
                                    case 395:
                                        break;
                                    case 398:
                                        num2 = 7;
                                        goto IL_0377;
                                    default:
                                        if (type != 422)
{
                                            goto IL_0377;
                                        }
                                        goto IL_0312;
                                    }
                                }
                                else if (type <= 439)
{
                                    if (type != 438)
{
                                        if (type != 439)
{
                                            goto IL_0377;
                                        }
                                        num2 = 2;
                                        goto IL_0377;
                                    }
                                    else
{
                                        if (Main.npc[i].ai[1] == 1f)
{
                                            num = 1600;
                                            num2 = 2;
                                            goto IL_0377;
                                        }
                                        goto IL_0377;
                                    }
                                }
                                else
{
                                    if (type == 471)
{
                                        goto IL_02C1;
                                    }
                                    if (type != 491)
{
                                        goto IL_0377;
                                    }
                                    goto IL_02F3;
                                }
                            }
                            else if (type <= 517)
{
                                if (type != 493 && type != 507 && type != 517)
{
                                    goto IL_0377;
                                }
                                goto IL_0312;
                            }
                            else if (type <= 636)
{
                                if (type != 520)
{
                                    if (type != 636)
{
                                        goto IL_0377;
                                    }
                                    num2 = 14;
                                    goto IL_0377;
                                }
                            }
                            else
{
                                if (type == 657)
{
                                    num2 = 13;
                                    goto IL_0377;
                                }
                                if (type != 668)
{
                                    goto IL_0377;
                                }
                                num2 = 16;
                                goto IL_0377;
                            }
                            num2 = 9;
                            goto IL_0377;
                            IL_0312:
                            num2 = 10;
                        }
                        IL_0377:
                        if (NPCID.Sets.BelongsToInvasionOldOnesArmy[Main.npc[i].type])
{
                            num2 = 12;
                        }
                        if (Main.remixWorld && Main.getGoodWorld && (Main.npc[i].type == 127 || Main.npc[i].type == 134 || Main.npc[i].type == 125 || Main.npc[i].type == 126))
{
                            num2 = 17;
                        }
                        if (num2 == 0 && Main.npc[i].boss)
{
                            num2 = 1;
                        }
                        if (num2 == 0)
{
                            goto IL_0532;
                        }
                        Microsoft.Xna.Framework.Rectangle rectangle2 = new Microsoft.Xna.Framework.Rectangle((int)(Main.npc[i].position.X + (float)(Main.npc[i].width / 2)) - num, (int)(Main.npc[i].position.Y + (float)(Main.npc[i].height / 2)) - num, num * 2, num * 2);
                        if (!rectangle.Intersects(rectangle2))
{
                            goto IL_0532;
                        }
                        if (num2 == 1)
{
                            flag = true;
                            break;
                        }
                        if (num2 == 2)
{
                            flag3 = true;
                            break;
                        }
                        if (num2 == 3)
{
                            flag4 = true;
                            break;
                        }
                        if (num2 == 4)
{
                            flag5 = true;
                            break;
                        }
                        if (num2 == 5)
{
                            flag6 = true;
                            break;
                        }
                        if (num2 == 6)
{
                            flag7 = true;
                            break;
                        }
                        if (num2 == 7)
{
                            flag8 = true;
                            break;
                        }
                        if (num2 == 8)
{
                            flag9 = true;
                            break;
                        }
                        if (num2 == 9)
{
                            flag10 = true;
                            break;
                        }
                        if (num2 == 10)
{
                            flag11 = true;
                            break;
                        }
                        if (num2 == 11)
{
                            flag12 = true;
                            break;
                        }
                        if (num2 == 12)
{
                            flag13 = true;
                            break;
                        }
                        if (num2 == 13)
{
                            flag14 = true;
                            break;
                        }
                        if (num2 == 14)
{
                            flag15 = true;
                            break;
                        }
                        if (num2 == 15)
{
                            flag16 = true;
                            break;
                        }
                        if (num2 == 16)
{
                            flag2 = true;
                            break;
                        }
                        if (num2 == 17)
{
                            flag17 = true;
                            break;
                        }
                        break;
                        IL_02C1:
                        num2 = 11;
                        goto IL_0377;
                        IL_02F3:
                        num2 = 8;
                        goto IL_0377;
                    }
                    IL_0532:;
                }
            }
            float num3 = (Main.screenPosition.X + (float)(Main.screenWidth / 2)) / 16f;
            if (Main.musicVolume == 0f)
            {
                Main.newMusic = 0;
                return;
            }
            float num4 = (float)Main.maxTilesX / 4200f;
            num4 *= num4;
            float num5 = (float)((double)((Main.screenPosition.Y + (float)(Main.screenHeight / 2)) / 16f - (65f + 10f * num4)) / (Main.worldSurface / 5.0));
            int num6 = (int)(Main.SceneMetrics.Center.X / 16f);
            int num7 = (int)(Main.SceneMetrics.Center.Y / 16f);
            Tile tile = (WorldGen.InWorld(num6, num7, 0) ? Main.tile[num6, num7] : null);
            if (CreditsRollEvent.IsEventOngoing)
            {
                Main.newMusic = 89;
            }
            else if (Main.SceneMetrics.InTorchGodMinigame)
            {
                Main.newMusic = 87;
            }
            else if (flag8)
            {
                Main.newMusic = 84;
            }
            else if (flag17)
            {
                Main.newMusic = 81;
            }
            else if (flag10)
            {
                Main.newMusic = 82;
            }
            else if (flag11)
            {
                Main.newMusic = 83;
            }
            else if (flag7)
            {
                Main.newMusic = 85;
            }
            else if (flag15)
            {
                Main.newMusic = 80;
            }
            else if (flag16)
            {
                Main.newMusic = 80;
            }
            else if (flag3)
            {
                Main.newMusic = 80;
            }
            else if (flag)
            {
                Main.newMusic = 81;
            }
            else if (flag4)
            {
                Main.newMusic = 87;
            }
            else if (flag5)
            {
                Main.newMusic = 81;
            }
            else if (flag6)
            {
                Main.newMusic = 81;
            }
            else if (flag14)
            {
                Main.newMusic = 80;
            }
            else if (flag2)
            {
                Main.newMusic = 80;
            }
            else if (flag9)
            {
                Main.newMusic = 82;
            }
            else if (flag12)
            {
                Main.newMusic = 82;
            }
            else if (flag13)
            {
                Main.newMusic = 82;
            }
            else if (Main.eclipse && (double)Main.SceneMetrics.Center.Y < Main.worldSurface * 16.0 + (double)(Main.screenHeight / 2))
            {
                Main.newMusic = 79;
            }
            else if (Main.eclipse && Main.remixWorld)
            {
                Main.newMusic = 79;
            }
            else if (Main.remixWorld && Main.bloodMoon && !Main.SceneMetrics.ZoneCrimson && !Main.SceneMetrics.ZoneCorrupt && (double)Main.SceneMetrics.Center.Y > Main.rockLayer * 16.0 && Main.SceneMetrics.Center.Y <= (float)(Main.UnderworldLayer * 16))
            {
                Main.newMusic = 79;
            }
            else if (Main.remixWorld && Main.bloodMoon && Main.SceneMetrics.Center.Y > (float)(Main.UnderworldLayer * 16) && (double)(Main.SceneMetrics.Center.X / 16f) > (double)Main.maxTilesX * 0.37 + 50.0 && (double)(Main.SceneMetrics.Center.X / 16f) < (double)Main.maxTilesX * 0.63)
            {
                Main.newMusic = 79;
            }
            else if (Main.SceneMetrics.ZoneShimmer)
            {
                Main.newMusic = 72;
            }
            else if (Main.SceneMetrics.ZoneSandstorm)
            {
                Main.newMusic = 66;
            }
            else if (Main.SceneMetrics.Center.Y > (float)(Main.UnderworldLayer * 16))
            {
                Main.newMusic = 71;
            }
            else if (num5 < 1f)
            {
                Main.newMusic = 70;
            }
            else if (tile != null && tile.wall == 87)
            {
                Main.newMusic = 69;
            }
            else if (Main.SceneMetrics.ZoneDungeon)
            {
                Main.newMusic = 69;
            }
            else if ((Main.bgStyle == 9 && (double)Main.SceneMetrics.Center.Y < Main.worldSurface * 16.0 + (double)(Main.screenHeight / 2)) || Main.undergroundBackground == 2)
            {
                Main.newMusic = 68;
            }
            else if (Main.SceneMetrics.ZoneCorrupt)
            {
                if (Main.SceneMetrics.ZoneCrimson && Main.SceneMetrics.BloodTileCount > Main.SceneMetrics.EvilTileCount)
                {
                    if ((double)Main.SceneMetrics.Center.Y > Main.worldSurface * 16.0 + (double)(Main.screenHeight / 2))
                    {
                        Main.newMusic = 76;
                    }
                    else
                    {
                        Main.newMusic = 75;
                    }
                }
                else if ((double)Main.SceneMetrics.Center.Y > Main.worldSurface * 16.0 + (double)(Main.screenHeight / 2))
                {
                    Main.newMusic = 74;
                }
                else
                {
                    Main.newMusic = 73;
                }
            }
            else if (Main.SceneMetrics.ZoneCrimson)
            {
                if ((double)Main.SceneMetrics.Center.Y > Main.worldSurface * 16.0 + (double)(Main.screenHeight / 2))
                {
                    Main.newMusic = 76;
                }
                else
                {
                    Main.newMusic = 75;
                }
            }
            else if (Main.SceneMetrics.ZoneMeteor)
            {
                Main.newMusic = 79;
            }
            else if (Main.SceneMetrics.ZoneGraveyard)
            {
                Main.newMusic = 79;
            }
            else if (Main.SceneMetrics.ZoneJungle)
            {
                if (Main.remixWorld && (double)Main.SceneMetrics.Center.Y < Main.worldSurface * 16.0 + (double)(Main.screenHeight / 2))
                {
                    Main.newMusic = 70;
                }
                else
                {
                    Main.newMusic = 86;
                }
            }
            else if (Main.SceneMetrics.ZoneSnow)
            {
                if (Main.remixWorld)
                {
                    if ((double)Main.SceneMetrics.Center.Y < Main.rockLayer * 16.0 + (double)(Main.screenHeight / 2))
                    {
                        if ((double)Main.SceneMetrics.Center.Y <= Main.worldSurface * 16.0 + (double)(Main.screenHeight / 2))
{
                            Main.newMusic = 70;
                        }
                        else
{
                            Main.newMusic = 77;
                        }
                    }
                    else
                    {
                        Main.newMusic = 72;
                    }
                }
                else if ((double)Main.SceneMetrics.Center.Y > Main.worldSurface * 16.0 + (double)(Main.screenHeight / 2))
                {
                    Main.newMusic = 77;
                }
                else
                {
                    Main.newMusic = 72;
                }
            }
            else if ((double)Main.SceneMetrics.Center.Y >= Main.worldSurface * 16.0 + (double)(Main.screenHeight / 2) && !WorldGen.oceanDepths((int)(Main.screenPosition.X + (float)(Main.screenWidth / 2)) / 16, (int)(Main.screenPosition.Y + (float)(Main.screenHeight / 2)) / 16))
            {
                if (Main.remixWorld && (double)Main.SceneMetrics.Center.Y >= Main.rockLayer * 16.0 + (double)(Main.screenHeight / 2))
                {
                    if (Main.SceneMetrics.ZoneUndergroundDesert)
                    {
                        Main.newMusic = 66;
                    }
                    else if (Main.cloudAlpha > 0f)
                    {
                        Main.newMusic = 62;
                    }
                    else if (Main.SceneMetrics.ZoneHallow)
                    {
                        Main.newMusic = 88;
                    }
                    else if (Main.SceneMetrics.ZoneDesert)
                    {
                        Main.newMusic = 66;
                    }
                    else
                    {
                        Main.newMusic = 62;
                    }
                }
                else if (Main.SceneMetrics.ZoneHallow)
                {
                    Main.newMusic = 78;
                }
                else if (Main.SceneMetrics.ZoneUndergroundDesert)
                {
                    Main.newMusic = 66;
                }
                else
                {
                    Main.newMusic = 65;
                }
            }
            else if (Main.dayTime && Main.SceneMetrics.ZoneHallow)
            {
                if (Main.cloudAlpha > 0f && !Main.gameMenu)
                {
                    Main.newMusic = 62;
                }
                else
                {
                    Main.newMusic = 88;
                }
            }
            else if (Main._shouldUseStormMusic)
            {
                if (Main.bloodMoon)
                {
                    Main.newMusic = 79;
                }
                else
                {
                    Main.newMusic = 62;
                }
            }
            else if (WorldGen.oceanDepths((int)(Main.screenPosition.X + (float)(Main.screenWidth / 2)) / 16, (int)(Main.screenPosition.Y + (float)(Main.screenHeight / 2)) / 16))
            {
                if (Main.bloodMoon)
                {
                    Main.newMusic = 79;
                }
                else
                {
                    Main.newMusic = 67;
                }
            }
            else if (Main.SceneMetrics.ZoneDesert)
            {
                Main.newMusic = 66;
            }
            else if (Main.remixWorld)
            {
                Main.newMusic = 70;
            }
            else if (Main.dayTime)
            {
                if (Main.cloudAlpha > 0f && !Main.gameMenu)
                {
                    Main.newMusic = 62;
                }
                else
                {
                    Main.newMusic = 63;
                }
            }
            else if (!Main.dayTime)
            {
                if (Main.bloodMoon)
                {
                    Main.newMusic = 79;
                }
                else if (Main.cloudAlpha > 0f && !Main.gameMenu)
                {
                    Main.newMusic = 64;
                }
                else
                {
                    Main.newMusic = 64;
                }
            }
            if (((double)(Main.screenPosition.Y / 16f) < Main.worldSurface + 10.0 || Main.remixWorld) && Main.pumpkinMoon)
            {
                Main.newMusic = 82;
            }
            if (((double)(Main.screenPosition.Y / 16f) < Main.worldSurface + 10.0 || Main.remixWorld) && Main.snowMoon)
            {
                Main.newMusic = 82;
            }
        }
References Terraria.Main._shouldUseStormMusic, Terraria.NPC.active, Terraria.NPC.ai, Terraria.ID.NPCID.Sets.BelongsToInvasionOldOnesArmy, Terraria.Main.bgStyle, Terraria.Main.bloodMoon, Terraria.SceneMetrics.BloodTileCount, Terraria.NPC.boss, Terraria.SceneMetrics.Center, Terraria.Main.cloudAlpha, Terraria.Main.dayTime, Terraria.Main.eclipse, Terraria.SceneMetrics.EvilTileCount, Terraria.Main.gameMenu, Terraria.Main.getGoodWorld, Terraria.Entity.height, int, Microsoft.Xna.Framework.Rectangle.Intersects(), Terraria.SceneMetrics.InTorchGodMinigame, Terraria.WorldGen.InWorld(), Terraria.GameContent.Events.CreditsRollEvent.IsEventOngoing, Terraria.Main.maxNPCs, Terraria.Main.maxTilesX, Terraria.Main.musicVolume, Terraria.Main.npc, Terraria.WorldGen.oceanDepths(), Terraria.Entity.position, Terraria.Main.pumpkinMoon, Terraria.Main.remixWorld, Terraria.Main.SceneMetrics, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Terraria.Main.showSplash, Terraria.Main.snowMoon, Terraria.Main.tile, Terraria.NPC.type, Terraria.Main.undergroundBackground, Terraria.Main.UnderworldLayer, Terraria.Tile.wall, Terraria.Entity.width, Terraria.Main.worldSurface, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, Terraria.SceneMetrics.ZoneCorrupt, Terraria.SceneMetrics.ZoneCrimson, Terraria.SceneMetrics.ZoneDesert, Terraria.SceneMetrics.ZoneDungeon, Terraria.SceneMetrics.ZoneGraveyard, Terraria.SceneMetrics.ZoneHallow, Terraria.SceneMetrics.ZoneJungle, Terraria.SceneMetrics.ZoneMeteor, Terraria.SceneMetrics.ZoneSandstorm, Terraria.SceneMetrics.ZoneShimmer, Terraria.SceneMetrics.ZoneSnow, and Terraria.SceneMetrics.ZoneUndergroundDesert.