Terraria Decompiled: Terraria.Main.DrawInterface_29_SettingsButton
DrawInterface_29_SettingsButton()
static void Terraria.Main.DrawInterface_29_SettingsButton () inline static
Definition at line 45647 of file Main.cs.
        {
            Main._settingsButtonIsPushedToSide = false;
            if (Main.playerInventory || Main.ingameOptionsWindow || Main.LocalPlayer.dead)
            {
                string value = Lang.inter[62].Value;
                string text = "Settings";
                int num = Main.screenWidth - 110;
                int num2 = Main.screenHeight - 20;
                int num3 = 620;
                int num4 = 870;
                int amountOfExtraAccessorySlotsToShow = Main.player[Main.myPlayer].GetAmountOfExtraAccessorySlotsToShow();
                if (amountOfExtraAccessorySlotsToShow >= 1)
                {
                    int num5 = (int)(56f * Main.inventoryScale * (float)amountOfExtraAccessorySlotsToShow);
                    num3 += num5;
                    num4 += num5;
                }
                if (Main.LocalPlayer.dead)
                {
                    num += 40;
                }
                else if (amountOfExtraAccessorySlotsToShow >= 1 && (Main.screenHeight < num3 || (Main.screenHeight < num4 && Main.mapStyle == 1)))
                {
                    num -= 140;
                    num2 -= PlayerInput.SettingsForUI.PushEquipmentAreaUp.ToInt() * 30;
                    Main._settingsButtonIsPushedToSide = true;
                }
                Action action = new Action(IngameOptions.Open);
                if (Main.ingameOptionsWindow)
                {
                    action = new Action(IngameOptions.Close);
                }
                Main.DrawSettingButton(ref Main.mouseExit, ref Main.exitScale, num, num2, value, text, action);
            }
        }
References System.Action(), System.action, Terraria.IngameOptions.Close(), Terraria.Player.dead, Terraria.Main.DrawSettingButton(), Terraria.Main.exitScale, Terraria.Player.GetAmountOfExtraAccessorySlotsToShow(), Terraria.Main.ingameOptionsWindow, int, Terraria.Lang.inter, Terraria.Main.inventoryScale, Terraria.Main.LocalPlayer, Terraria.Main.mapStyle, Terraria.Main.mouseExit, Terraria.Main.myPlayer, Terraria.IngameOptions.Open(), Terraria.Main.player, Terraria.Main.playerInventory, Terraria.GameInput.PlayerInput.SettingsForUI.PushEquipmentAreaUp, Terraria.Main.screenHeight, System.text, System.value, and Terraria.Localization.LocalizedText.Value.
Referenced by Terraria.Main.SetupDrawInterfaceLayers().