Terraria Decompiled: Terraria.Main.maxTilesY
maxTilesY
int Terraria.Main.maxTilesY = (int)Main.bottomWorld / 16 + 1 static
Definition at line 69318 of file Main.cs.
Referenced by Terraria.WorldGen.AddBuriedChest(), Terraria.WorldGen.AddHellHouses(), Terraria.WorldGen.AddLifeCrystal(), Terraria.WorldGen.AddManaCrystal(), Terraria.WorldGen.AddPasses(), Terraria.WorldGen.AddShadowOrb(), Terraria.WorldGen.AddSpikeCaves(), Terraria.Liquid.AddWater(), Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.NPC.AI_003_Gnomes_ShouldTurnToStone(), Terraria.NPC.AI_006_Worms(), Terraria.NPC.AI_007_FindGoodRestingSpot(), Terraria.Projectile.AI_007_GrapplingHooks(), Terraria.NPC.AI_015_KingSlime(), Terraria.Projectile.AI_016_Bombs(), Terraria.NPC.AI_037_Destroyer(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.Projectile.AI_113_TargetSticker(), Terraria.NPC.AI_123_Deerclops_FindSpotToSpawnSpike(), Terraria.NPC.AI_123_Deerclops_TryMakingSpike_FindBestY(), Terraria.NPC.AI_AttemptToFindTeleportSpotNearBooks_SearchWall(), Terraria.NPC.AI_FindNearbyBook(), Terraria.Collision.AnyCollision(), Terraria.Collision.AnyCollisionWithSpecificTiles(), Terraria.WorldGen.AnyLiquidAt(), Terraria.Collision.AnyWallOfTypeOnLine(), Terraria.GameContent.Biomes.TerrainPass.ApplyPass(), Terraria.GameContent.Biomes.JunglePass.ApplyRandomMovement(), Terraria.SceneState.ApplyVisuals(), Terraria.GameContent.Biomes.CaveHouse.HouseUtils.AreRoomLocationsValid(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeRuggedDungeonRoom.BiomeRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeSquareDungeonRoom.BiomeRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeStructuredDungeonRoom.BiomeRoom(), Terraria.WorldGen.BlockBelowMakesSandConvertIntoHardenedSand(), Terraria.WorldGen.BlockBelowMakesSandFall(), Terraria.WorldGen.Skyblock.Calculate(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.CalculatePlatformsAndDoorsOnEdgesOfRoom(), Terraria.SceneMetrics.CalculateZones(), Terraria.GameContent.ItemDropRules.Conditions.YoyoCascade.CanDrop(), Terraria.GameContent.ItemDropRules.Conditions.YoyosHelFire.CanDrop(), Terraria.Collision.CanHit(), Terraria.Collision.CanHitLine(), Terraria.Collision.CanHitWithCheck(), Terraria.WorldGen.CanKillTile(), Terraria.TileObject.CanPlace(), Terraria.WorldBuilding.StructureMap.CanPlace(), Terraria.WorldGen.CanPlaceSink(), Terraria.DelegateMethods.CastLight(), Terraria.DelegateMethods.CastLightOpen(), Terraria.DelegateMethods.CastLightOpen_StopForSolids(), Terraria.DelegateMethods.CastLightOpen_StopForSolids_ScaleWithDistance(), Terraria.WorldGen.CaveOpenater(), Terraria.WorldGen.Cavinator(), Terraria.WorldGen.ChasmRunner(), Terraria.WorldGen.ChasmRunnerSideways(), Terraria.WorldGen.CheckCatTail(), Terraria.NPC.checkDead(), Terraria.WorldGen.CheckLilyPad(), Terraria.Wiring.CheckLogicGate(), Terraria.WorldGen.CheckSign(), Terraria.DelegateMethods.CheckStopForSolids(), Terraria.WorldGen.CheckTileBreakability(), Terraria.NPC.Spawner.CheckToSpawnUndergroundGnomes(), Terraria.WorldBuilding.WorldUtils.ClampToWorld(), Terraria.GameContent.Biomes.DesertBiome.CleanupArea(), Terraria.IO.WorldFile.ClearTempTiles(), Terraria.WorldGen.ClearUnbreakableWallsWithPaintUpTo(), Terraria.WorldGen.clearWorld(), Terraria.WorldGen.CloudIsland(), Terraria.WorldGen.CloudLake(), Terraria.Utilities.TileSnapshot.Compare(), Terraria.Main.ComputeScAdj(), Terraria.WorldGen.Convert(), Terraria.IO.WorldFile.ConvertIlluminantPaintToNewField(), Terraria.IO.WorldFile.ConvertOldTileEntities(), Terraria.WorldGen.CountTileTypesInWorld(), Terraria.GameContent.Drawing.TileDrawing.CrawlToBottomOfReverseVineAndAddSpecialPoint(), Terraria.GameContent.Biomes.HiveBiome.CreateHiveTunnel(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.CreatePotentialDungeonBounds(), Terraria.GameContent.Biomes.HiveBiome.CreateStandForLarva(), Terraria.GameContent.Biomes.JunglePass.CreateStartPoint(), Terraria.Projectile.CutTilesAt(), Terraria.WorldBuilding.WorldUtils.DebugRotate(), Terraria.WorldGen.DesertCloudIsland(), Terraria.WorldGen.DestroyHeart(), Terraria.WorldGen.digTunnel(), Terraria.WorldGen.DirtyRockRunner(), Terraria.Program.DisplayException(), Terraria.WorldGen.SecretSeed.DoActuallyNoTraps(), Terraria.WorldGen.SecretSeed.DoCoatEverythingEcho(), Terraria.WorldGen.SecretSeed.DoCoatEverythingIlluminant(), Terraria.WorldGen.SecretSeed.DoDigExtraHoles(), Terraria.WorldGen.SecretSeed.DoErrorWorldShuffleBlocks(), Terraria.GameContent.TeleportPylonsSystem.DoesPylonAcceptTeleportation(), Terraria.WorldGen.SecretSeed.DoExtraLiquidAddBubbleBlocks(), Terraria.WorldGen.SecretSeed.DoExtraLiquidFinish(), Terraria.WorldGen.SecretSeed.DoNoInfection(), Terraria.WorldGen.SecretSeed.DoPaintEverythingGray(), Terraria.WorldGen.SecretSeed.DoPaintEverythingNegative(), Terraria.WorldGen.SecretSeed.DoPooEverywhere(), Terraria.WorldGen.SecretSeed.DoRainbowStuff(), Terraria.WorldGen.SecretSeed.DoRoundLandMasses(), Terraria.WorldGen.SecretSeed.DoSurfaceIsMushrooms(), Terraria.WorldGen.SecretSeed.DoWorldIsInfected(), Terraria.Main.DrawBackground(), Terraria.Main.DrawBackground_DrawMagmaLayer(), Terraria.Main.DrawBackground_PickUndergroundBackgroundStyle(), Terraria.Main.DrawBackgroundBlackFill(), Terraria.Main.DrawBlack(), Terraria.Main.DrawMap(), Terraria.Main.DrawUnderworldBackground(), Terraria.WaterfallManager.DrawWaterfall(), Terraria.WorldGen.dropMeteor(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalEarlyDualDungeonFeatures.EarlyDungeonFeatures(), Terraria.DelegateMethods.EmitGolfCartDust_StopForSolids(), Terraria.WorldGen.EmptyTileCheck(), Terraria.Collision.ExpandVertically(), Terraria.Graphics.Light.LightingEngine.ExportToMiniMap(), Terraria.GameContent.Biomes.TerrainPass.FillColumn(), Terraria.WorldGen.FillWallHolesInColumn(), Terraria.WorldBuilding.Searches.Down.Find(), Terraria.Projectile.FindBlockCeiling(), Terraria.Projectile.FindBlockSurface(), Terraria.Player.FindSentryRestingSpot(), Terraria.Player.FindSharpTearsSpot(), Terraria.NPC.Spawner.FindSpawnTile(), Terraria.Testing.ChatCommands.ToolkitDebugCommands.FindTiles(), Terraria.WaterfallManager.FindWaterfalls(), Terraria.WorldGen.FinishDrunkGen(), Terraria.WorldGen.FinishGetGoodWorld(), Terraria.WorldGen.FinishNotTheBees(), Terraria.WorldGen.FinishRemixWorld(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.FirstSolid(), Terraria.IO.WorldFile.FixDresserChests(), Terraria.WorldGen.FixHeart(), Terraria.WorldGen.FixHearts(), Terraria.WorldGen.FloatingIsland(), Terraria.GameContent.Biomes.HiveBiome.FrameOutAllHiveContents(), Terraria.GameContent.ExtraSpawnPointManager.GenerateExtraSpawns_IterateDownToFloor(), Terraria.GameContent.ExtraSpawnPointManager.GenerateExtraSpawns_TryFindSpawnRandomly(), Terraria.GameContent.Biomes.JunglePass.GenerateFinishingTouches(), Terraria.WorldGen.GenerateSkyBlockWorld(), Terraria.GameContent.Generation.Dungeon.Features.DungeonPillar.GenerateTileStrip(), Terraria.WorldGen.GenerateUnderworldStartingMound(), Terraria.WorldBuilding.WorldGenerator.GenerateWorld(), Terraria.WorldGen.GenerateWorld(), Terraria.WorldGen.GERunner(), Terraria.MessageBuffer.GetData(), Terraria.NPC.GetFairyTreasureCoords(), Terraria.Projectile.GetFishingPondState(), Terraria.Graphics.Capture.CaptureInterface.GetMapCoords(), Terraria.GameContent.Drawing.TileDrawing.GetScreenDrawArea(), Terraria.WorldGen.GetSectionBounds(), Terraria.Collision.GetTileRotation(), Terraria.WorldGen.GetTreeBottom(), Terraria.WorldGen.GetWaterDepth(), Terraria.WorldGen.GrowAlch(), Terraria.WorldGen.GrowCatTail(), Terraria.WorldGen.GrowCheckSeaweed(), Terraria.WorldGen.GrowLivingTree(), Terraria.WorldGen.GrowLivingTree_MakePassage(), Terraria.GameContent.LeashedEntities.WalkerLeashedCritter.HandleFalling(), Terraria.Projectile.HandleMovement(), Terraria.WorldBuilding.WorldGenerator.HashWorld(), Terraria.WorldGen.HellFort(), Terraria.WorldGen.HellHouse(), Terraria.WorldGen.HellRoom(), Terraria.Collision.HitLineWall(), Terraria.Collision.HitTiles(), Terraria.Collision.HitTilesInACircle(), Terraria.Wiring.HitWire(), Terraria.WorldGen.Housing_GetTestedRoomBounds(), Terraria.Collision.HurtTiles(), Terraria.Map.MapHelper.InternalSaveMap(), Terraria.WorldGen.IsFitToPlaceFlowerIn(), Terraria.WorldGen.IslandHouse(), Terraria.Player.ItemCheck_Shoot(), Terraria.Player.ItemCheck_UseTeleportRod(), Terraria.WorldGen.KillTile(), Terraria.WorldGen.KillWall(), Terraria.WorldGen.Lakinater(), Terraria.GameContent.Generation.Dungeon.Entrances.LegacyDungeonEntrance.LegacyEntrance(), Terraria.GameContent.Generation.Dungeon.Halls.LegacyDungeonHall.LegacyHall(), Terraria.GameContent.Generation.Dungeon.Halls.LegacyEntranceDungeonHall.LegacyHall(), Terraria.GameContent.Generation.Dungeon.Rooms.LegacyDungeonRoom.LegacyRoom(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalLights.Lights(), Terraria.Utilities.TileSnapshot.Load(), Terraria.Initializers.DyeInitializer.LoadLegacyHairdyes(), Terraria.Map.MapHelper.LoadMapVersion1(), Terraria.Map.MapHelper.LoadMapVersion2(), Terraria.Map.MapHelper.LoadMapVersionCompressed(), Terraria.IO.WorldFile.LoadWorld(), Terraria.IO.WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), Terraria.IO.WorldFile.LoadWorldTiles(), Terraria.Player.MagicConch(), Terraria.Main.Main(), Terraria.Rain.MakeRain(), Terraria.WorldGen.MakeWateryIceThing(), Terraria.WorldGen.meteor(), Terraria.WorldGen.MineHouse(), Terraria.Player.MinionRestTargetAim(), Terraria.WorldGen.Mountinater(), Terraria.WorldGen.MudWallRunner(), Terraria.WorldGen.nearbyChlorophyte(), Terraria.WorldGen.NearFriendlyWall(), Terraria.WorldGen.neonMossBiome(), Terraria.Animation.NewTemporaryAnimation(), Terraria.WorldGen.nextCount(), Terraria.WorldGen.nextDirtCount(), Terraria.WorldGen.oceanCave(), Terraria.Main.OldDrawBackground(), Terraria.Main.oldDrawWater(), Terraria.GameContent.UI.States.UIWorldGenDebug.OnActivate(), Terraria.GameContent.SpelunkerProjectileHelper.OnPreUpdateAllProjectiles(), Terraria.WorldGen.OreRunner(), Terraria.WorldGen.OverGrownDungeon(), Terraria.WorldGen.OverGrownDungeonWithRainbowMoss(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalPaintings.Paintings(), Terraria.WorldGen.PaintTheClouds(), Terraria.WorldGen.PaintTheDungeon(), Terraria.WorldGen.PaintTheLivingTrees(), Terraria.WorldGen.PaintTheMushrooms(), Terraria.WorldGen.PaintThePurityGrass(), Terraria.WorldGen.PaintThePyramids(), Terraria.GameContent.Generation.ShapeFloodFill.Perform(), Terraria.Player.PickSentryLandingSpot(), Terraria.GameContent.Generation.Dungeon.Features.DungeonPitTrap.PitTrap(), Terraria.WorldGen.Place2x2(), Terraria.WorldGen.Place2x2Horizontal(), Terraria.WorldGen.Place2x2Style(), Terraria.WorldGen.Place3x1(), Terraria.WorldGen.Place3x2(), Terraria.WorldGen.Place3x4(), Terraria.WorldGen.Place4x2(), Terraria.WorldGen.Place5x4(), Terraria.WorldGen.Place6x3(), Terraria.WorldGen.PlaceCannon(), Terraria.WorldGen.PlaceCatTail(), Terraria.WorldGen.PlaceChilletEggs(), Terraria.WorldGen.PlaceJunglePlant(), Terraria.WorldGen.placeLavaTrap(), Terraria.WorldGen.PlaceLilyPad(), Terraria.WorldGen.PlaceMB(), Terraria.WorldGen.PlaceOasis(), Terraria.WorldGen.PlaceOasisPlant(), Terraria.WorldGen.PlacePot(), Terraria.WorldGen.PlacePumpkin(), Terraria.WorldGen.PlaceSign(), Terraria.Player.PlaceThing_Tiles_CheckRopeUsability(), Terraria.WorldGen.PlaceTile(), Terraria.WorldGen.placeTNTBarrel(), Terraria.WorldGen.placeTrap(), Terraria.WorldGen.PlaceWall(), Terraria.WorldGen.PlantAlch(), Terraria.WorldGen.PlantCheck(), Terraria.WorldGen.PlantCheck_CanPlaceHook(), Terraria.WorldGen.plantDye(), Terraria.Graphics.Capture.CaptureInterface.PointWorldClamp(), Terraria.DataStructures.PlayerIntentionGuesser.PrepareUsageProxy(), Terraria.GameContent.UI.EmoteBubble.ProbeBiomes(), Terraria.GameContent.UI.EmoteBubble.ProbeDebuffs(), Terraria.WorldGen.QuickFindHome(), Terraria.Projectile.RainbowBoulder_GetTreasureCoords(), Terraria.WorldGen.RandomWorldPoint(), Terraria.Projectile.ReduceRemainingChumsInPool(), Terraria.WorldGen.Reset(), Terraria.Utilities.TileSnapshot.Restore(), Terraria.Utilities.TileSnapshot.RestoreTiles(), Terraria.GameContent.Biomes.TerrainPass.RetargetColumn(), Terraria.IO.WorldFile.SaveChests(), Terraria.Utilities.TileSnapshot.SaveTiles(), Terraria.IO.WorldFile.SaveWorldHeader(), Terraria.IO.WorldFile.SaveWorldTiles(), Terraria.WorldBuilding.WorldGenRange.ScaleValue(), Terraria.NetMessage.SendData(), Terraria.NPC.Spawner.SetSpawnFlagsForChosenTile(), Terraria.Liquid.SettleWaterAt(), Terraria.WorldGen.setWorldSize(), Terraria.WorldGen.ShimmeratorNext(), Terraria.WorldGen.ShroomPatch(), Terraria.WorldGen.SkyblockIsland(), Terraria.WorldGen.SmashAltar(), Terraria.WorldGen.SnowCloudIsland(), Terraria.Collision.SolidFullTiles(), Terraria.Collision.SolidTiles(), Terraria.Collision.SolidTiles(), Terraria.WorldGen.SonOfLakinater(), Terraria.NPC.Spawner.SpawnAnNPC(), Terraria.Projectile.SpawnFakeFishInWater(), Terraria.WorldGen.SpawnFallingObjects(), Terraria.WorldGen.SpawnThingsFromPot(), Terraria.Projectile.SpawnWebs(), Terraria.NPC.SpawnWOF(), Terraria.WorldGen.SpiderWallRemover(), Terraria.WorldGen.SpreadGrass(), Terraria.Liquid.StartPanic(), Terraria.WorldGen.Statue(), Terraria.GameContent.SmartCursorHelper.Step_Hammers(), Terraria.GameContent.SmartCursorHelper.Step_Pickaxe_MineSolids(), Terraria.Collision.StepUp(), Terraria.Collision.StickyTiles(), Terraria.Utilities.TileSnapshot.Swap(), Terraria.Utilities.TileSnapshot.SwapTiles(), Terraria.Collision.SwitchTiles(), Terraria.DelegateMethods.TestDust(), Terraria.GameContent.Generation.Dungeon.Features.DungeonTileClump.TileClump(), Terraria.WorldGen.tileCounterNext(), Terraria.WorldGen.TileFrame(), Terraria.WorldGen.TileFrameCosmetic(), Terraria.WorldGen.TileRunner(), Terraria.GameContent.Biomes.HiveBiome.TooCloseToImportantLocations(), Terraria.GameContent.Biomes.HoneyPatchBiome.TooCloseToImportantLocations(), Terraria.Projectile.TryBuildFishingContext(), Terraria.WorldGen.TryGrowingAbigailsFlower(), Terraria.WorldGen.TryGrowingGlowTulip(), Terraria.WorldGen.TryPlacingChilletEgg(), Terraria.Player.TryRecalculatingTorchLuck(), Terraria.Player.TrySpawnDigtoiseAt(), Terraria.GameContent.Events.CultistRitual.TrySpawning(), Terraria.Player.Update(), Terraria.GameContent.UI.States.UIWorldGenDebug.UpdateAndDrawMap(), Terraria.NPC.UpdateNPC(), Terraria.WorldGen.UpdateWorld(), Terraria.WorldGen.UpdateWorld_GrassGrowth(), Terraria.WorldGen.UpdateWorld_OvergroundTile(), Terraria.WorldGen.UpdateWorld_UndergroundTile(), Terraria.Framing.WallFrame(), Terraria.WorldGen.WaterCheck(), and Terraria.Player.WOFTongue().