Terraria Decompiled: Terraria.Main.DrawProj_FlailChains_Old
DrawProj_FlailChains_Old()
static void Terraria.Main.DrawProj_FlailChains_Old (Projectile proj, Vector2 mountedCenter) inline static private
Definition at line 34672 of file Main.cs.
        {
            Vector2 vector = new Vector2(proj.position.X + (float)proj.width * 0.5f, proj.position.Y + (float)proj.height * 0.5f);
            float num = mountedCenter.X - vector.X;
            float num2 = mountedCenter.Y - vector.Y;
            float num3 = (float)Math.Atan2((double)num2, (double)num) - 1.57f;
            bool flag = true;
            int num4 = 0;
            int num5 = 25;
            if (proj.type == 757)
            {
                num5 = 12;
            }
            while (flag)
            {
                float num6 = (float)Math.Sqrt((double)(num * num + num2 * num2));
                if (num6 < (float)num5)
                {
                    flag = false;
                }
                else if (float.IsNaN(num6))
                {
                    flag = false;
                }
                else
                {
                    if (proj.type == 154 || proj.type == 247)
                    {
                        num6 = 18f / num6;
                    }
                    else if (proj.type == 757)
                    {
                        num6 = 16f / num6;
                    }
                    else
                    {
                        num6 = 12f / num6;
                    }
                    num *= num6;
                    num2 *= num6;
                    vector.X += num;
                    vector.Y += num2;
                    num = mountedCenter.X - vector.X;
                    num2 = mountedCenter.Y - vector.Y;
                    Microsoft.Xna.Framework.Color color = Lighting.GetColor((int)vector.X / 16, (int)(vector.Y / 16f));
                    if (proj.type == 25)
                    {
                        Main.EntitySpriteDraw(TextureAssets.Chain2.Value, new Vector2(vector.X - Main.screenPosition.X, vector.Y - Main.screenPosition.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain2.Width(), TextureAssets.Chain2.Height())), color, num3, new Vector2((float)TextureAssets.Chain2.Width() * 0.5f, (float)TextureAssets.Chain2.Height() * 0.5f), 1f, SpriteEffects.None, 0f);
                    }
                    else if (proj.type == 35)
                    {
                        Main.EntitySpriteDraw(TextureAssets.Chain6.Value, new Vector2(vector.X - Main.screenPosition.X, vector.Y - Main.screenPosition.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain6.Width(), TextureAssets.Chain6.Height())), color, num3, new Vector2((float)TextureAssets.Chain6.Width() * 0.5f, (float)TextureAssets.Chain6.Height() * 0.5f), 1f, SpriteEffects.None, 0f);
                    }
                    else if (proj.type == 757)
                    {
                        Texture2D value = TextureAssets.Extra[99].Value;
                        Microsoft.Xna.Framework.Rectangle rectangle = value.Frame(1, 6, 0, num4 % 6, 0, 0);
                        Main.EntitySpriteDraw(value, new Vector2(vector.X - Main.screenPosition.X, vector.Y - Main.screenPosition.Y), new Microsoft.Xna.Framework.Rectangle?(value.Frame(1, 6, 0, num4 % 6, 0, 0)), color, num3, rectangle.Size() / 2f, 1f, SpriteEffects.None, 0f);
                    }
                    else if (proj.type == 247)
                    {
                        Main.EntitySpriteDraw(TextureAssets.Chain19.Value, new Vector2(vector.X - Main.screenPosition.X, vector.Y - Main.screenPosition.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain19.Width(), TextureAssets.Chain19.Height())), color, num3, new Vector2((float)TextureAssets.Chain19.Width() * 0.5f, (float)TextureAssets.Chain19.Height() * 0.5f), 1f, SpriteEffects.None, 0f);
                    }
                    else if (proj.type == 63)
                    {
                        Main.EntitySpriteDraw(TextureAssets.Chain7.Value, new Vector2(vector.X - Main.screenPosition.X, vector.Y - Main.screenPosition.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain7.Width(), TextureAssets.Chain7.Height())), color, num3, new Vector2((float)TextureAssets.Chain7.Width() * 0.5f, (float)TextureAssets.Chain7.Height() * 0.5f), 1f, SpriteEffects.None, 0f);
                    }
                    else if (proj.type == 154)
                    {
                        Main.EntitySpriteDraw(TextureAssets.Chain13.Value, new Vector2(vector.X - Main.screenPosition.X, vector.Y - Main.screenPosition.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain13.Width(), TextureAssets.Chain13.Height())), color, num3, new Vector2((float)TextureAssets.Chain13.Width() * 0.5f, (float)TextureAssets.Chain13.Height() * 0.5f), 1f, SpriteEffects.None, 0f);
                    }
                    else
                    {
                        Main.EntitySpriteDraw(TextureAssets.Chain3.Value, new Vector2(vector.X - Main.screenPosition.X, vector.Y - Main.screenPosition.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain3.Width(), TextureAssets.Chain3.Height())), color, num3, new Vector2((float)TextureAssets.Chain3.Width() * 0.5f, (float)TextureAssets.Chain3.Height() * 0.5f), 1f, SpriteEffects.None, 0f);
                    }
                }
                num4++;
            }
        }
References System.Math.Atan2(), Terraria.GameContent.TextureAssets.Chain13, Terraria.GameContent.TextureAssets.Chain19, Terraria.GameContent.TextureAssets.Chain2, Terraria.GameContent.TextureAssets.Chain3, Terraria.GameContent.TextureAssets.Chain6, Terraria.GameContent.TextureAssets.Chain7, Terraria.Main.EntitySpriteDraw(), Terraria.GameContent.TextureAssets.Extra, Terraria.Lighting.GetColor(), Terraria.Entity.height, int, Terraria.Entity.position, Terraria.Main.screenPosition, System.Math.Sqrt(), Terraria.Projectile.type, System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.