Terraria Decompiled: Terraria.Main.DrawInterface_4_Ruler
DrawInterface_4_Ruler()
static void Terraria.Main.DrawInterface_4_Ruler () inline static private
Definition at line 46463 of file Main.cs.
        {
            if (Main.LocalPlayer.spectating >= 0)
            {
                return;
            }
            if (Main.player[Main.myPlayer].rulerLine && Main.player[Main.myPlayer].builderAccStatus[0] == 0)
            {
                float num = Main.player[Main.myPlayer].velocity.Length();
                float num2 = 6f;
                float num3 = 2f;
                if (num <= num2)
                {
                    float num4 = 1f;
                    if (num >= num3)
                    {
                        num4 = 1f - (num - num3) / num2;
                    }
                    int num5 = 1;
                    if ((float)Main.mouseX + Main.screenPosition.X < Main.player[Main.myPlayer].Center.X)
                    {
                        num5 = -1;
                    }
                    int num6 = (int)(Main.player[Main.myPlayer].position.X + (float)(Main.player[Main.myPlayer].width / 2)) / 16;
                    int num7 = (int)(Main.player[Main.myPlayer].position.Y + (float)Main.player[Main.myPlayer].height - 2f) / 16;
                    if (Main.player[Main.myPlayer].gravDir == -1f)
                    {
                        num7--;
                    }
                    Vector2 vector = Main.MouseWorld;
                    if (Math.Abs(num6 - (int)(Main.MouseWorld.X / 16f)) > 0)
                    {
                        num6 += num5;
                    }
                    if (Main.player[Main.myPlayer].gravDir == -1f)
                    {
                        vector.Y += 16f;
                    }
                    vector /= 16f;
                    new Vector2((float)num6, (float)num7);
                    int num8 = (int)vector.X - num6;
                    int num9 = (int)vector.Y - num7;
                    Math.Abs(num8);
                    Math.Abs(num9);
                    Main.rulerLineDisplayValues.X = num8;
                    Main.rulerLineDisplayValues.Y = num9;
                    if (num8 != 0 || num9 != 0)
                    {
                        Texture2D value = TextureAssets.Extra[2].Value;
                        Microsoft.Xna.Framework.Rectangle rectangle = new Microsoft.Xna.Framework.Rectangle(0, 0, 16, 16);
                        int num10 = num6;
                        int num11 = num7;
                        if (Main.player[Main.myPlayer].gravDir == -1f)
{
                            num11--;
                        }
                        float num12 = 0.24f;
                        float num13 = 0.8f;
                        float num14 = 0.9f;
                        float num15 = 1f;
                        float num16 = 0.8f;
                        Microsoft.Xna.Framework.Color color = new Microsoft.Xna.Framework.Color(num12, num13, num14, num15) * num16 * num4;
                        Main.spriteBatch.Draw(value, Main.ReverseGravitySupport(new Vector2((float)num10, (float)num11) * 16f - Main.screenPosition, 16f), new Microsoft.Xna.Framework.Rectangle?(rectangle), color, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                        if (num8 != 0)
{
                            int num17 = Math.Sign(num8);
                            rectangle.Y = ((num17 == 1) ? 16 : 32);
                            while (num8 != 0)
{
                                num8 -= num17;
                                num10 += num17;
                                if (num8 == 0)
{
                                    rectangle.Y = 0;
                                }
                                color = new Microsoft.Xna.Framework.Color(num12, num13, num14, num15) * num16 * num4;
                                Main.spriteBatch.Draw(value, Main.ReverseGravitySupport(new Vector2((float)num10, (float)num11) * 16f - Main.screenPosition, 16f), new Microsoft.Xna.Framework.Rectangle?(rectangle), color, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                            }
                        }
                        if (num9 != 0)
{
                            int num18 = Math.Sign(num9);
                            rectangle.Y = ((num18 == 1) ? 48 : 64);
                            while (num9 != 0)
{
                                num9 -= num18;
                                num11 += num18;
                                if (num9 == 0)
{
                                    rectangle.Y = 0;
                                }
                                color = new Microsoft.Xna.Framework.Color(num12, num13, num14, num15) * num16 * num4;
                                Main.spriteBatch.Draw(value, Main.ReverseGravitySupport(new Vector2((float)num10, (float)num11) * 16f - Main.screenPosition, 16f), new Microsoft.Xna.Framework.Rectangle?(rectangle), color, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                            }
                        }
                    }
                }
            }
        }
References System.Math.Abs(), Terraria.Player.builderAccStatus, Terraria.Entity.Center, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.GameContent.TextureAssets.Extra, Terraria.Player.gravDir, Terraria.Entity.height, int, Microsoft.Xna.Framework.Vector2.Length(), Terraria.Main.LocalPlayer, Terraria.Main.MouseWorld, Terraria.Main.myPlayer, Terraria.Main.player, Terraria.Entity.position, Terraria.Main.ReverseGravitySupport(), Terraria.Player.rulerLine, Terraria.Main.screenPosition, System.Math.Sign(), Terraria.Player.spectating, Terraria.Main.spriteBatch, System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Entity.velocity, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.Main.SetupDrawInterfaceLayers().