Terraria Decompiled: Terraria.Main.GetBuffTooltip
GetBuffTooltip()
static string Terraria.Main.GetBuffTooltip (Player player, int buffType) inline static
Definition at line 43252 of file Main.cs.
        {
            string text = Lang.GetBuffDescription(buffType);
            if (buffType <= 94)
            {
                if (buffType != 26)
                {
                    if (buffType == 94)
                    {
                        int num = (int)(player.manaSickReduction * 100f) + 1;
                        text = text + num + "%";
                    }
                }
                else if (Main.expertMode)
                {
                    text = Language.GetTextValue("BuffDescription.WellFed_Expert");
                }
            }
            else if (buffType != 206)
            {
                if (buffType == 207)
                {
                    if (Main.expertMode)
                    {
                        text = Language.GetTextValue("BuffDescription.WellFed3_Expert");
                    }
                }
            }
            else if (Main.expertMode)
            {
                text = Language.GetTextValue("BuffDescription.WellFed2_Expert");
            }
            return text;
        }
References Terraria.Main.expertMode, Terraria.Lang.GetBuffDescription(), Terraria.Localization.Language.GetTextValue(), int, Terraria.Player.manaSickReduction, and System.text.
Referenced by Terraria.Main.DrawInterface_Resources_Buffs(), and Terraria.Main.DrawInventory().