Terraria Decompiled: Terraria.Main.UpdateMenu
UpdateMenu()
static void Terraria.Main.UpdateMenu () inline static private
Definition at line 18581 of file Main.cs.
        {
            if (WorldGen.drunkWorldGen)
            {
                if (WorldGen.remixWorldGen)
                {
                    Main.screenPosition.X = Main.screenPosition.X - 20f;
                }
                if (WorldGen.drunkWorldGenText)
                {
                    if (WorldGen.dontStarveWorldGen)
                    {
                        Main.numClouds = 50;
                    }
                    else
                    {
                        Main.numClouds = Main.rand.Next(100, 200);
                    }
                    Main.statusText = string.Concat(Main.rand.Next(999999999));
                    for (int i = 0; i < 3; i++)
                    {
                        if (Main.rand.Next(2) == 0)
{
                            Main.statusText += Main.rand.Next(999999999);
                        }
                    }
                }
            }
            Main.gamePaused = false;
            Main.thunderDelay = 0;
            Main.lightning = 0f;
            Main.lightningSpeed = 0f;
            Main.GraveyardVisualIntensity = 0f;
            Main.playerInventory = false;
            Main.exitScale = 0.8f;
            if (Main.netMode == 0)
            {
                if (FocusHelper.LetStarsFallInMenu && (!Main.dayTime || WorldGen.remixWorldGen) && (Main.rand.Next(12) == 0 || (WorldGen.drunkWorldGen && !Main.remixWorld)))
                {
                    int num = Main.rand.Next(Main.numStars);
                    if (Main.star[num] != null && !Main.star[num].hidden && !Main.star[num].falling)
                    {
                        Main.star[num].Fall();
                    }
                }
                if (Main.gameMenu)
                {
                    if (WorldGen.isGeneratingOrLoadingWorld)
                    {
                        Main.lockMenuBGChange = true;
                    }
                    else if (Main.menuMode == 0)
                    {
                        Main.lockMenuBGChange = false;
                    }
                    if (!Main.lockMenuBGChange)
                    {
                        if (Main.dayTime)
{
                            Main.menuBGChangedDay = false;
                        }
                        else if (!Main.menuBGChangedDay && Main.time >= 16200.0)
{
                            Main.menuBGChangedDay = true;
                            int num2 = WorldGen.corruptBG;
                            WorldGen.RandomizeBackgrounds(Main.rand);
                            if (Main.treeBGSet1[0] == 173)
{
                                WorldGen.RandomizeBackgrounds(Main.rand);
                            }
                            if (Main.treeBGSet1[0] == 173)
{
                                WorldGen.RandomizeBackgrounds(Main.rand);
                            }
                            WorldGen.setBG(1, num2);
                        }
                        if (!Main.dayTime)
{
                            Main.menuBGChangedNight = false;
                        }
                        else if (!Main.menuBGChangedNight && Main.time >= 27000.0)
{
                            Main.moonType = Main.rand.Next(9);
                            Main.menuBGChangedNight = true;
                            int treeBG = WorldGen.treeBG1;
                            WorldGen.RandomizeBackgrounds(Main.rand);
                            WorldGen.setBG(0, treeBG);
                        }
                    }
                    else
                    {
                        Main.menuBGChangedDay = true;
                        Main.menuBGChangedNight = true;
                    }
                }
                if (!Main.alreadyGrabbingSunOrMoon)
                {
                    if (WorldGen.drunkWorldGen && !WorldGen.remixWorldGen)
                    {
                        if (Main.dayTime)
{
                            Main.time -= 1000.0;
                        }
                        if (Main.dontStarveWorld)
{
                            int num3 = 200;
                            if (Main.rand.Next(300) == 0)
{
                                Main.seedMoonGoal = Main.rand.Next(100, 32300);
                            }
                            if (Main.time < (double)(Main.seedMoonGoal - num3 - 1))
{
                                Main.time += (double)num3;
                            }
                            else if (Main.time > (double)(Main.seedMoonGoal + num3 + 1))
{
                                Main.time -= (double)num3;
                            }
                            else
{
                                Main.time = (double)Main.seedMoonGoal;
                            }
                        }
                        else
{
                            Main.time -= 6.0;
                        }
                        if (Main.time < 0.0)
{
                            Main.time = 32400.0;
                            Main.dayTime = false;
                        }
                    }
                    else if (Main.dayTime)
                    {
                        Main.time += 33.88235294117647;
                    }
                    else
                    {
                        Main.time += 30.857142857142858;
                    }
                    if (!Main.dayTime)
                    {
                        if (Main.time > 32400.0)
{
                            Main.bloodMoon = false;
                            Main.time = 0.0;
                            Main.dayTime = true;
                            if (Main.starGame)
{
                                Main.dayTime = false;
                            }
                            Main.moonPhase++;
                            if (Main.moonPhase > 7)
{
                                Main.moonPhase = 0;
                                return;
                            }
                        }
                    }
                    else if (Main.time > 54000.0)
                    {
                        Main.time = 0.0;
                        Main.dayTime = false;
                        return;
                    }
                }
            }
            else if (Main.netMode == 1)
            {
                Main.UpdateTime();
            }
        }
References Terraria.Main.alreadyGrabbingSunOrMoon, Terraria.WorldGen.corruptBG, Terraria.Main.dayTime, Terraria.Main.dontStarveWorld, Terraria.WorldGen.dontStarveWorldGen, Terraria.WorldGen.drunkWorldGen, Terraria.WorldGen.drunkWorldGenText, Terraria.Star.Fall(), Terraria.Star.falling, Terraria.Main.gameMenu, Terraria.Star.hidden, Terraria.WorldGen.isGeneratingOrLoadingWorld, Terraria.FocusHelper.LetStarsFallInMenu, Terraria.Main.lockMenuBGChange, Terraria.Main.menuBGChangedDay, Terraria.Main.menuBGChangedNight, Terraria.Main.menuMode, Terraria.Main.moonPhase, Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.numStars, Terraria.Main.rand, Terraria.WorldGen.RandomizeBackgrounds(), Terraria.Main.remixWorld, Terraria.WorldGen.remixWorldGen, Terraria.Main.seedMoonGoal, Terraria.WorldGen.setBG(), Terraria.Main.star, Terraria.Main.starGame, Terraria.Main.time, Terraria.WorldGen.treeBG1, Terraria.Main.treeBGSet1, and Terraria.Main.UpdateTime().
Referenced by Terraria.Main.DoUpdate().