Terraria Decompiled: Terraria.Main.DrawMapFullscreenBackground
DrawMapFullscreenBackground()
static void Terraria.Main.DrawMapFullscreenBackground (Vector2 screenPosition, int screenWidth, int screenHeight) inline static private
Definition at line 57038 of file Main.cs.
        {
            Asset<Texture2D> asset = TextureAssets.MapBGs[0];
            int num = -1;
            Microsoft.Xna.Framework.Color color = Microsoft.Xna.Framework.Color.White;
            if (!WorldGen.InWorld((int)(Main.player[Main.myPlayer].Center.X / 16f), (int)(Main.player[Main.myPlayer].Center.Y / 16f), 10))
            {
                return;
            }
            if (Main.tile[(int)(Main.player[Main.myPlayer].Center.X / 16f), (int)(Main.player[Main.myPlayer].Center.Y / 16f)] == null)
            {
                return;
            }
            int wall = (int)Main.tile[(int)(Main.player[Main.myPlayer].Center.X / 16f), (int)(Main.player[Main.myPlayer].Center.Y / 16f)].wall;
            if (screenPosition.Y > (float)((Main.maxTilesY - 232) * 16))
            {
                num = 2;
            }
            else if (Main.player[Main.myPlayer].ZoneDungeon)
            {
                num = 4;
            }
            else if (wall == 87)
            {
                num = 13;
            }
            else if ((double)screenPosition.Y > Main.worldSurface * 16.0)
            {
                if (wall == 86 || wall == 108)
                {
                    num = 15;
                }
                else if (wall == 180 || wall == 184)
                {
                    num = 16;
                }
                else if (wall == 178 || wall == 183)
                {
                    num = 17;
                }
                else if (wall == 62 || wall == 263)
                {
                    num = 18;
                }
                else if (Main.player[Main.myPlayer].ZoneGlowshroom)
                {
                    num = 20;
                }
                else if (Main.player[Main.myPlayer].ZoneCorrupt)
                {
                    if (Main.player[Main.myPlayer].ZoneDesert)
                    {
                        num = 39;
                    }
                    else if (Main.player[Main.myPlayer].ZoneSnow)
                    {
                        num = 33;
                    }
                    else
                    {
                        num = 22;
                    }
                }
                else if (Main.player[Main.myPlayer].ZoneCrimson)
                {
                    if (Main.player[Main.myPlayer].ZoneDesert)
                    {
                        num = 40;
                    }
                    else if (Main.player[Main.myPlayer].ZoneSnow)
                    {
                        num = 34;
                    }
                    else
                    {
                        num = 23;
                    }
                }
                else if (Main.player[Main.myPlayer].ZoneHallow)
                {
                    if (Main.player[Main.myPlayer].ZoneDesert)
                    {
                        num = 41;
                    }
                    else if (Main.player[Main.myPlayer].ZoneSnow)
                    {
                        num = 35;
                    }
                    else
                    {
                        num = 21;
                    }
                }
                else if (Main.player[Main.myPlayer].ZoneSnow)
                {
                    num = 3;
                }
                else if (Main.player[Main.myPlayer].ZoneJungle)
                {
                    num = 12;
                }
                else if (Main.player[Main.myPlayer].ZoneDesert)
                {
                    num = 14;
                }
                else if (Main.player[Main.myPlayer].ZoneRockLayerHeight)
                {
                    num = 31;
                }
                else
                {
                    num = 1;
                }
            }
            else if (Main.player[Main.myPlayer].ZoneGlowshroom)
            {
                num = 19;
            }
            else
            {
                color = Main.ColorOfTheSkies;
                int num2 = (int)((screenPosition.X + (float)(screenWidth / 2)) / 16f);
                if (Main.player[Main.myPlayer].ZoneSkyHeight)
                {
                    num = 32;
                }
                else if (Main.player[Main.myPlayer].ZoneCorrupt)
                {
                    if (Main.player[Main.myPlayer].ZoneDesert)
                    {
                        num = 36;
                    }
                    else
                    {
                        num = 5;
                    }
                }
                else if (Main.player[Main.myPlayer].ZoneCrimson)
                {
                    if (Main.player[Main.myPlayer].ZoneDesert)
                    {
                        num = 37;
                    }
                    else
                    {
                        num = 6;
                    }
                }
                else if (Main.player[Main.myPlayer].ZoneHallow)
                {
                    if (Main.player[Main.myPlayer].ZoneDesert)
                    {
                        num = 38;
                    }
                    else
                    {
                        num = 7;
                    }
                }
                else if ((double)(screenPosition.Y / 16f) < Main.worldSurface + 10.0 && (num2 < 380 || num2 > Main.maxTilesX - 380))
                {
                    num = 10;
                }
                else if (Main.player[Main.myPlayer].ZoneSnow)
                {
                    num = 11;
                }
                else if (Main.player[Main.myPlayer].ZoneJungle)
                {
                    num = 8;
                }
                else if (Main.player[Main.myPlayer].ZoneDesert)
                {
                    num = 9;
                }
                else if (Main.bloodMoon)
                {
                    color *= 2f;
                    num = 25;
                }
                else if (Main.player[Main.myPlayer].ZoneGraveyard)
                {
                    num = 26;
                }
            }
            if (num > -1)
            {
                asset = TextureAssets.MapBGs[num];
            }
            Main.spriteBatch.Draw(asset.Value, new Microsoft.Xna.Framework.Rectangle(0, 0, screenWidth, screenHeight), color);
        }
References Terraria.Main.bloodMoon, Terraria.Entity.Center, Terraria.Main.ColorOfTheSkies, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), int, Terraria.WorldGen.InWorld(), Terraria.GameContent.TextureAssets.MapBGs, Terraria.Main.maxTilesX, Terraria.Main.myPlayer, Terraria.Main.player, Terraria.Main.spriteBatch, Terraria.Main.tile, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Color.White, Terraria.Main.worldSurface, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, Terraria.Player.ZoneCorrupt, Terraria.Player.ZoneCrimson, Terraria.Player.ZoneDesert, Terraria.Player.ZoneDungeon, Terraria.Player.ZoneGlowshroom, Terraria.Player.ZoneGraveyard, Terraria.Player.ZoneHallow, Terraria.Player.ZoneJungle, Terraria.Player.ZoneRockLayerHeight, Terraria.Player.ZoneSkyHeight, and Terraria.Player.ZoneSnow.
Referenced by Terraria.Main.DrawMap().