Terraria Decompiled: Terraria.Main.GUIBarsDrawInner
GUIBarsDrawInner()
void Terraria.Main.GUIBarsDrawInner () inline protected
Definition at line 43177 of file Main.cs.
        {
            Main.ResourceSetsManager.Draw();
            Main.spriteBatch.End();
            Main.spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, SamplerState.PointClamp, DepthStencilState.None, RasterizerState.CullCounterClockwise, null, Main.UIScaleMatrix);
            Main.DrawInterface_Resources_Breath();
            Main.DrawInterface_Resources_ClearBuffs();
            if (!Main.ingameOptionsWindow && !Main.playerInventory && !Main.inFancyUI && !CaptureManager.Instance.Active)
            {
                this.DrawInterface_Resources_Buffs();
            }
        }
References Terraria.Graphics.Capture.CaptureManager.Active, Microsoft.Xna.Framework.Graphics.BlendState.AlphaBlend, Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(), Microsoft.Xna.Framework.Graphics.RasterizerState.CullCounterClockwise, Terraria.GameContent.UI.ResourceSets.PlayerResourceSetsManager.Draw(), Terraria.Main.DrawInterface_Resources_Breath(), Terraria.Main.DrawInterface_Resources_ClearBuffs(), Microsoft.Xna.Framework.Graphics.SpriteBatch.End(), Terraria.Main.inFancyUI, Terraria.Main.ingameOptionsWindow, Terraria.Graphics.Capture.CaptureManager.Instance, Microsoft.Xna.Framework.Graphics.DepthStencilState.None, Terraria.Main.playerInventory, Microsoft.Xna.Framework.Graphics.SamplerState.PointClamp, Terraria.Main.ResourceSetsManager, Terraria.Main.spriteBatch, and Terraria.Main.UIScaleMatrix.