Terraria Decompiled: Terraria.Main.ParticleSystem_World_OverPlayers
ParticleSystem_World_OverPlayers
ParticleRenderer Terraria.Main.ParticleSystem_World_OverPlayers = new ParticleRenderer() static
Definition at line 71064 of file Main.cs.
Referenced by Terraria.WorldGen.clearWorld(), Terraria.DataStructures.RichRoomCheckFeedback.EndScoring(), Terraria.DataStructures.RichRoomCheckFeedback.EndSpread(), Terraria.Chest.IndicateBlockedChest(), Terraria.GameContent.Drawing.ParticleOrchestrator.RepelAt(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_BestReforge(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_BlackLightningHit(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_BlackLightningSmall(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_BlueLightningSmall(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_CattivaHit(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsBarrelExplosion(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsDownDashExplosion(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsFlint(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsMushroomBoiExplosion(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_Excalibur(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ItemTransfer(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_Keybrand(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_LeafCrystalPassive(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_LeafCrystalShot(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_MoonLordWhip(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_NatureFly(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_NightsEdge(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_PaladinsHammer(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_PaladinsShieldHit(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_PooFly(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_PrincessWeapon(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_RainbowBoulder1(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_RainbowBoulder2(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_RainbowBoulder3(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_RainbowBoulder4(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_RainbowRodHit(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ShadowOrbExplosion(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ShimmerArrow(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ShimmerBlock(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ShimmerTownNPC(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ShimmerTownNPCSend(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_SilverBulletSparkle(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_StardustPunch(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_StellarTune(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_StormLightning(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_StormLightningWindup(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_TerraBlade(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_TrueExcalibur(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_TrueNightsEdge(), and Terraria.Main.UpdateParticleSystems_World().