Terraria Decompiled: Terraria.Main.GUIHotbarDrawInner
GUIHotbarDrawInner()
void Terraria.Main.GUIHotbarDrawInner () inline protected
Definition at line 43599 of file Main.cs.
        {
            if (!Main.playerInventory && !Main.LocalPlayer.ghost && Main.LocalPlayer.spectating < 0)
            {
                string text = Lang.inter[37].Value;
                if (Main.player[Main.myPlayer].inventory[Main.player[Main.myPlayer].selectedItem].Name != null && Main.player[Main.myPlayer].inventory[Main.player[Main.myPlayer].selectedItem].Name != "")
                {
                    text = Main.player[Main.myPlayer].inventory[Main.player[Main.myPlayer].selectedItem].AffixName();
                }
                Vector2 vector = FontAssets.MouseText.Value.MeasureString(text) / 2f;
                DynamicSpriteFontExtensionMethods.DrawString(Main.spriteBatch, FontAssets.MouseText.Value, text, new Vector2(236f - vector.X, 0f), new Microsoft.Xna.Framework.Color((int)Main.mouseTextColor, (int)Main.mouseTextColor, (int)Main.mouseTextColor, (int)Main.mouseTextColor), 0f, default(Vector2), 1f, SpriteEffects.None, 0f, null, null);
                int num = 20;
                for (int i = 0; i < 10; i++)
                {
                    if (i == Main.LocalPlayer.selectedItem && !Main.LocalPlayer.selectedItemState.HasActiveOverride)
                    {
                        if (Main.hotbarScale[i] < 1f)
{
                            Main.hotbarScale[i] += 0.05f;
                        }
                    }
                    else if ((double)Main.hotbarScale[i] > 0.75)
                    {
                        Main.hotbarScale[i] -= 0.05f;
                    }
                    float num2 = Main.hotbarScale[i];
                    int num3 = (int)(20f + 22f * (1f - num2));
                    int num4 = (int)(75f + 150f * num2);
                    Microsoft.Xna.Framework.Color color = new Microsoft.Xna.Framework.Color(255, 255, 255, num4);
                    if (!Main.player[Main.myPlayer].hbLocked && !PlayerInput.IgnoreMouseInterface && !Main.LocalPlayer.controlTorch && Main.mouseX >= num && (float)Main.mouseX <= (float)num + (float)TextureAssets.InventoryBack.Width() * Main.hotbarScale[i] && Main.mouseY >= num3 && (float)Main.mouseY <= (float)num3 + (float)TextureAssets.InventoryBack.Height() * Main.hotbarScale[i] && !Main.player[Main.myPlayer].channel)
                    {
                        Main.player[Main.myPlayer].mouseInterface = true;
                        Main.player[Main.myPlayer].cursorItemIconEnabled = false;
                        if (Main.mouseLeft && !Main.player[Main.myPlayer].hbLocked && !Main.blockMouse)
{
                            Main.player[Main.myPlayer].changeItem = i;
                        }
                        Main.hoverItemName = Main.player[Main.myPlayer].inventory[i].AffixName();
                        if (Main.player[Main.myPlayer].inventory[i].stack > 1)
{
                            Main.hoverItemName = string.Concat(new object[]
{
                                Main.hoverItemName,
                                " (",
                                Main.player[Main.myPlayer].inventory[i].stack,
                                ")"
                            });
                        }
                        Main.rare = Main.player[Main.myPlayer].inventory[i].rare;
                        if (Main.player[Main.myPlayer].inventory[i].expert)
{
                            Main.rare = -12;
                        }
                    }
                    float num5 = Main.inventoryScale;
                    Main.inventoryScale = num2;
                    ItemSlot.Draw(Main.spriteBatch, Main.player[Main.myPlayer].inventory, 13, i, new Vector2((float)num, (float)num3), color);
                    Main.inventoryScale = num5;
                    num += (int)((float)TextureAssets.InventoryBack.Width() * Main.hotbarScale[i]) + 4;
                }
                if ((Main.LocalPlayer.selectedItemState.HasActiveOverride || Main.LocalPlayer.selectedItem >= 10) && Main.LocalPlayer.selectedItem != 58 && !Main.LocalPlayer.HeldItem.IsAir)
                {
                    float num6 = 1f;
                    int num7 = (int)(20f + 22f * (1f - num6));
                    int num8 = (int)(75f + 150f * num6);
                    Microsoft.Xna.Framework.Color color2 = new Microsoft.Xna.Framework.Color(255, 255, 255, num8);
                    float num9 = Main.inventoryScale;
                    Main.inventoryScale = num6;
                    ItemSlot.Draw(Main.spriteBatch, Main.player[Main.myPlayer].inventory, 36, Main.LocalPlayer.selectedItem, new Vector2((float)num, (float)num7), color2);
                    Main.inventoryScale = num9;
                }
            }
        }
References Terraria.Item.AffixName(), Terraria.Main.blockMouse, Terraria.Player.changeItem, Terraria.Player.channel, Terraria.Player.controlTorch, Terraria.Player.cursorItemIconEnabled, Terraria.UI.ItemSlot.Draw(), ReLogic.Graphics.DynamicSpriteFontExtensionMethods.DrawString(), Terraria.Item.expert, Terraria.Player.ghost, Terraria.Player.hbLocked, Terraria.Player.HeldItem, Terraria.Main.hotbarScale, Terraria.Main.hoverItemName, Terraria.GameInput.PlayerInput.IgnoreMouseInterface, int, Terraria.Lang.inter, Terraria.Player.inventory, Terraria.GameContent.TextureAssets.InventoryBack, Terraria.Main.inventoryScale, Terraria.Item.IsAir, Terraria.Main.LocalPlayer, Terraria.Player.mouseInterface, Terraria.Main.mouseLeft, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.mouseTextColor, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Item.Name, Terraria.Main.player, Terraria.Main.playerInventory, Terraria.Item.rare, Terraria.Player.selectedItem, Terraria.Player.selectedItemState, Terraria.Player.spectating, Terraria.Main.spriteBatch, Terraria.Item.stack, System.text, ReLogic.Content.Asset< T >.Value, Terraria.Localization.LocalizedText.Value, and Microsoft.Xna.Framework.Vector2.X.