Terraria Decompiled: Terraria.Main.InputTextSignCancel
InputTextSignCancel()
static void Terraria.Main.InputTextSignCancel () inline static
Definition at line 18569 of file Main.cs.
        {
            Main.editSign = false;
            Main.blockKey = Microsoft.Xna.Framework.Input.Keys.Escape.ToString();
            UIVirtualKeyboard.CacheCanceledInput(1);
            if (Main.player[Main.myPlayer].sign >= 0)
            {
                Main.npcChatText = Main.sign[Main.player[Main.myPlayer].sign].text;
            }
        }
References Terraria.GameContent.UI.States.UIVirtualKeyboard.CacheCanceledInput(), Terraria.Main.myPlayer, Terraria.Main.player, Terraria.Main.sign, Terraria.Player.sign, and Terraria.Sign.text.
Referenced by Terraria.Main.InputTextSign(), Terraria.UI.IngameFancyUI.OpenVirtualKeyboard(), and Terraria.GameContent.UI.States.UIVirtualKeyboard.TryEscapingMenu().