Terraria Decompiled: Terraria.Main.DrawNPCChatButtons
DrawNPCChatButtons()
static void Terraria.Main.DrawNPCChatButtons (int superColor, Microsoft::Xna::Framework::Color chatColor, int numLines, string focusText, string focusText3) inline static private
Definition at line 40254 of file Main.cs.
        {
            float num = (float)(130 + numLines * 30);
            int num2 = 180 + (Main.screenWidth - 800) / 2;
            Vector2 vector = new Vector2((float)Main.mouseX, (float)Main.mouseY);
            Player player = Main.player[Main.myPlayer];
            Vector2 vector2 = new Vector2((float)num2, num);
            DynamicSpriteFont dynamicSpriteFont = FontAssets.MouseText.Value;
            Vector2 vector3 = vector2;
            Vector2 vector4 = new Vector2(0.9f);
            Vector2 vector5 = ChatManager.GetStringSize(dynamicSpriteFont, focusText, vector4, -1f);
            Microsoft.Xna.Framework.Color color = chatColor;
            Microsoft.Xna.Framework.Color color2 = Microsoft.Xna.Framework.Color.Black;
            Vector2 vector6 = new Vector2(1f);
            Microsoft.Xna.Framework.Color brown = Microsoft.Xna.Framework.Color.Brown;
            float num3 = 1.2f;
            if (vector5.X > 260f)
            {
                vector6.X *= 260f / vector5.X;
            }
            if (vector.Between(vector3, vector3 + vector5 * vector4 * vector6.X) && !PlayerInput.IgnoreMouseInterface)
            {
                player.mouseInterface = true;
                player.releaseUseItem = false;
                vector4 *= num3;
                if (!Main.npcChatFocus2)
                {
                    SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                }
                Main.npcChatFocus2 = true;
            }
            else
            {
                if (Main.npcChatFocus2)
                {
                    SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                }
                Main.npcChatFocus2 = false;
            }
            if (Main.npcChatFocus2)
            {
                color2 = brown;
            }
            else
            {
                color2 = Microsoft.Xna.Framework.Color.Black;
            }
            ChatManager.DrawColorCodedStringShadow(Main.spriteBatch, dynamicSpriteFont, focusText, vector3 + vector5 * vector6 * 0.5f, color2, 0f, vector5 * 0.5f, vector4 * vector6, -1f, 2f);
            ChatManager.DrawColorCodedString(Main.spriteBatch, dynamicSpriteFont, focusText, vector3 + vector5 * vector6 * 0.5f, color, 0f, vector5 * 0.5f, vector4 * vector6, -1f, false);
            if (focusText.Length > 0)
            {
                UILinkPointNavigator.SetPosition(2500, vector3 + vector5 * 0.5f);
                UILinkPointNavigator.Shortcuts.NPCCHAT_ButtonsLeft = true;
            }
            Vector2 vector7 = new Vector2((float)num2 + vector5.X * vector6.X + 30f, num);
            string text = Lang.inter[52].Value;
            dynamicSpriteFont = FontAssets.MouseText.Value;
            vector3 = vector7;
            vector4 = new Vector2(0.9f);
            vector5 = ChatManager.GetStringSize(dynamicSpriteFont, text, vector4, -1f);
            color = new Microsoft.Xna.Framework.Color(superColor, (int)((double)superColor / 1.1), superColor / 2, superColor);
            vector6 = new Vector2(1f);
            if (vector.Between(vector3, vector3 + vector5 * vector4 * vector6.X) && !PlayerInput.IgnoreMouseInterface)
            {
                player.mouseInterface = true;
                player.releaseUseItem = false;
                vector4 *= num3;
                if (!Main.npcChatFocus1)
                {
                    SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                }
                Main.npcChatFocus1 = true;
            }
            else
            {
                if (Main.npcChatFocus1)
                {
                    SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                }
                Main.npcChatFocus1 = false;
            }
            if (Main.npcChatFocus1)
            {
                color2 = brown;
            }
            else
            {
                color2 = Microsoft.Xna.Framework.Color.Black;
            }
            ChatManager.DrawColorCodedStringShadow(Main.spriteBatch, dynamicSpriteFont, text, vector3 + vector5 * vector6 * 0.5f, color2, 0f, vector5 * 0.5f, vector4 * vector6, -1f, 2f);
            ChatManager.DrawColorCodedString(Main.spriteBatch, dynamicSpriteFont, text, vector3 + vector5 * vector6 * 0.5f, color, 0f, vector5 * 0.5f, vector4 * vector6, -1f, false);
            if (text.Length > 0)
            {
                UILinkPointNavigator.SetPosition(2501, vector3 + vector5 * 0.5f);
                UILinkPointNavigator.Shortcuts.NPCCHAT_ButtonsMiddle = true;
            }
            if (string.IsNullOrWhiteSpace(focusText3))
            {
                Main.npcChatFocus3 = false;
                UILinkPointNavigator.Shortcuts.NPCCHAT_ButtonsRight = false;
            }
            else
            {
                Vector2 vector8 = new Vector2(vector7.X + vector5.X * vector6.X + 30f, num);
                dynamicSpriteFont = FontAssets.MouseText.Value;
                vector3 = vector8;
                vector4 = new Vector2(0.9f);
                vector5 = ChatManager.GetStringSize(dynamicSpriteFont, focusText3, vector4, -1f);
                color = chatColor;
                vector6 = new Vector2(1f);
                vector7.X = vector8.X;
                if (vector.Between(vector3, vector3 + vector5 * vector4 * vector6.X) && !PlayerInput.IgnoreMouseInterface)
                {
                    player.mouseInterface = true;
                    player.releaseUseItem = false;
                    vector4 *= num3;
                    if (!Main.npcChatFocus3)
                    {
                        SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                    }
                    Main.npcChatFocus3 = true;
                }
                else
                {
                    if (Main.npcChatFocus3)
                    {
                        SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                    }
                    Main.npcChatFocus3 = false;
                }
                if (Main.npcChatFocus3)
                {
                    color2 = brown;
                }
                else
                {
                    color2 = Microsoft.Xna.Framework.Color.Black;
                }
                ChatManager.DrawColorCodedStringShadow(Main.spriteBatch, dynamicSpriteFont, focusText3, vector3 + vector5 * vector6 * 0.5f, color2, 0f, vector5 * 0.5f, vector4 * vector6, -1f, 2f);
                ChatManager.DrawColorCodedString(Main.spriteBatch, dynamicSpriteFont, focusText3, vector3 + vector5 * vector6 * 0.5f, color, 0f, vector5 * 0.5f, vector4 * vector6, -1f, false);
                UILinkPointNavigator.SetPosition(2502, vector3 + vector5 * 0.5f);
                UILinkPointNavigator.Shortcuts.NPCCHAT_ButtonsRight = true;
            }
            if (!Main.remixWorld)
            {
                if (Main.LocalPlayer.talkNPC >= 0 && Main.npc[Main.LocalPlayer.talkNPC].homeless && Main.npc[Main.LocalPlayer.talkNPC].type != 37 && Main.npc[Main.LocalPlayer.talkNPC].type != 368 && Main.npc[Main.LocalPlayer.talkNPC].type != 453)
                {
                    string textValue = Language.GetTextValue("UI.NPCHousing");
                    Vector2 vector9 = new Vector2(vector7.X + vector5.X * vector6.X + 30f, num);
                    text = textValue;
                    dynamicSpriteFont = FontAssets.MouseText.Value;
                    vector3 = vector9;
                    vector4 = new Vector2(0.9f);
                    vector5 = ChatManager.GetStringSize(dynamicSpriteFont, text, vector4, -1f);
                    color = new Microsoft.Xna.Framework.Color(superColor, (int)((double)superColor / 1.1), superColor / 2, superColor);
                    vector6 = new Vector2(1f);
                    if (vector.Between(vector3, vector3 + vector5 * vector4 * vector6.X) && !PlayerInput.IgnoreMouseInterface)
                    {
                        player.mouseInterface = true;
                        player.releaseUseItem = false;
                        vector4 *= num3;
                        if (!Main.npcChatFocus4)
{
                            SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                        }
                        Main.npcChatFocus4 = true;
                    }
                    else
                    {
                        if (Main.npcChatFocus4)
{
                            SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                        }
                        Main.npcChatFocus4 = false;
                    }
                    if (Main.npcChatFocus4)
                    {
                        color2 = brown;
                    }
                    else
                    {
                        color2 = Microsoft.Xna.Framework.Color.Black;
                    }
                    ChatManager.DrawColorCodedStringShadow(Main.spriteBatch, dynamicSpriteFont, text, vector3 + vector5 * vector6 * 0.5f, color2, 0f, vector5 * 0.5f, vector4 * vector6, -1f, 2f);
                    ChatManager.DrawColorCodedString(Main.spriteBatch, dynamicSpriteFont, text, vector3 + vector5 * vector6 * 0.5f, color, 0f, vector5 * 0.5f, vector4 * vector6, -1f, false);
                    UILinkPointNavigator.SetPosition(2503, vector3 + vector5 * 0.5f);
                    UILinkPointNavigator.Shortcuts.NPCCHAT_ButtonsRight2 = true;
                    return;
                }
                if (Main.player[Main.myPlayer].currentShoppingSettings.HappinessReport == "")
                {
                    Main.npcChatFocus4 = false;
                    UILinkPointNavigator.Shortcuts.NPCCHAT_ButtonsRight2 = false;
                    return;
                }
                string textValue2 = Language.GetTextValue("UI.NPCCheckHappiness");
                Vector2 vector10 = new Vector2(vector7.X + vector5.X * vector6.X + 30f, num);
                text = textValue2;
                dynamicSpriteFont = FontAssets.MouseText.Value;
                vector3 = vector10;
                vector4 = new Vector2(0.9f);
                vector5 = ChatManager.GetStringSize(dynamicSpriteFont, text, vector4, -1f);
                color = new Microsoft.Xna.Framework.Color(superColor, (int)((double)superColor / 1.1), superColor / 2, superColor);
                vector6 = new Vector2(1f);
                if (vector.Between(vector3, vector3 + vector5 * vector4 * vector6.X) && !PlayerInput.IgnoreMouseInterface)
                {
                    player.mouseInterface = true;
                    player.releaseUseItem = false;
                    vector4 *= num3;
                    if (!Main.npcChatFocus4)
                    {
                        SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                    }
                    Main.npcChatFocus4 = true;
                }
                else
                {
                    if (Main.npcChatFocus4)
                    {
                        SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                    }
                    Main.npcChatFocus4 = false;
                }
                if (Main.npcChatFocus4)
                {
                    color2 = brown;
                }
                else
                {
                    color2 = Microsoft.Xna.Framework.Color.Black;
                }
                ChatManager.DrawColorCodedStringShadow(Main.spriteBatch, dynamicSpriteFont, text, vector3 + vector5 * vector6 * 0.5f, color2, 0f, vector5 * 0.5f, vector4 * vector6, -1f, 2f);
                ChatManager.DrawColorCodedString(Main.spriteBatch, dynamicSpriteFont, text, vector3 + vector5 * vector6 * 0.5f, color, 0f, vector5 * 0.5f, vector4 * vector6, -1f, false);
                UILinkPointNavigator.SetPosition(2503, vector3 + vector5 * 0.5f);
                UILinkPointNavigator.Shortcuts.NPCCHAT_ButtonsRight2 = true;
            }
        }
References Microsoft.Xna.Framework.Color.Black, Microsoft.Xna.Framework.Color.Brown, Terraria.Player.currentShoppingSettings, Terraria.UI.Chat.ChatManager.DrawColorCodedString(), Terraria.UI.Chat.ChatManager.DrawColorCodedStringShadow(), Terraria.UI.Chat.ChatManager.GetStringSize(), Terraria.Localization.Language.GetTextValue(), Terraria.ShoppingSettings.HappinessReport, Terraria.NPC.homeless, Terraria.GameInput.PlayerInput.IgnoreMouseInterface, Terraria.Lang.inter, Terraria.Main.LocalPlayer, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Main.npc, Terraria.Main.npcChatFocus1, Terraria.Main.npcChatFocus2, Terraria.Main.npcChatFocus3, Terraria.Main.npcChatFocus4, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.remixWorld, Terraria.UI.Gamepad.UILinkPointNavigator.SetPosition(), Terraria.Main.spriteBatch, Terraria.Player.talkNPC, System.text, Terraria.NPC.type, ReLogic.Content.Asset< T >.Value, Terraria.Localization.LocalizedText.Value, Microsoft.Xna.Framework.Graphics.Vector2, and Microsoft.Xna.Framework.Vector2.X.