Terraria Decompiled: Terraria.Main.DrawInterface
DrawInterface()
void Terraria.Main.DrawInterface (GameTime gameTime) inline protected
Definition at line 45015 of file Main.cs.
        {
            Main._drawInterfaceGameTime = gameTime;
            if (this._needToSetupDrawInterfaceLayers)
            {
                this.SetupDrawInterfaceLayers();
            }
            using (List<GameInterfaceLayer>.Enumerator enumerator = this._gameInterfaceLayers.GetEnumerator())
            {
                while (enumerator.MoveNext())
                {
                    if (!enumerator.Current.Draw())
                    {
                        break;
                    }
                }
            }
            CoinSlot.UpdateSlotAnims();
            PlayerInput.SetZoom_UI();
            Main.spriteBatch.Begin(SpriteSortMode.Deferred, null, null, null, null, null, Main.UIScaleMatrix);
            Main.DrawPendingMouseText();
            Main.spriteBatch.End();
            Main.cursorOverride = -1;
            DebugLineDraw.UI.Draw(Main.spriteBatch);
            PlayerInput.SetZoom_World();
        }
References Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(), Terraria.Testing.DebugLineDraw.Draw(), Terraria.Main.DrawPendingMouseText(), Microsoft.Xna.Framework.Graphics.SpriteBatch.End(), Terraria.GameInput.PlayerInput.SetZoom_UI(), Terraria.GameInput.PlayerInput.SetZoom_World(), Terraria.Main.spriteBatch, Terraria.Testing.DebugLineDraw.UI, Terraria.Main.UIScaleMatrix, and Terraria.UI.CoinSlot.UpdateSlotAnims().