Terraria Decompiled: Terraria.Main.ShouldDrawSurfaceBackground
ShouldDrawSurfaceBackground()
static bool Terraria.Main.ShouldDrawSurfaceBackground () inline static
Definition at line 60476 of file Main.cs.
        {
            bool flag = false;
            if ((!Main.remixWorld || (Main.gameMenu && !WorldGen.remixWorldGen)) && (!WorldGen.remixWorldGen || !WorldGen.drunkWorldGen))
            {
                flag = true;
            }
            if (Main.mapFullscreen)
            {
                flag = false;
            }
            return flag;
        }
References Terraria.WorldGen.drunkWorldGen, Terraria.Main.gameMenu, Terraria.Main.mapFullscreen, Terraria.Main.remixWorld, and Terraria.WorldGen.remixWorldGen.
Referenced by Terraria.GameContent.Drawing.BackgroundGradientDrawer.Draw(), Terraria.GameContent.Drawing.NextNatureRenderer.DrawAfterAllObjects(), Terraria.GameContent.Drawing.EmptyHorizonRenderer.DrawHorizon(), Terraria.GameContent.Drawing.NextHorizonRenderer.DrawHorizon(), Terraria.GameContent.Drawing.NextHorizonRenderer.DrawLensFlare(), Terraria.Main.DrawSurfaceBG(), Terraria.GameContent.Drawing.NextHorizonRenderer.DrawSurfaceLayer(), and Terraria.GameContent.Drawing.NextHorizonRenderer.ModifyHorizonLight().