Terraria Decompiled: Terraria.Main.OldDrawBackground
OldDrawBackground()
void Terraria.Main.OldDrawBackground () inline protected
Definition at line 54713 of file Main.cs.
        {
            Microsoft.Xna.Framework.Color[] array = new Microsoft.Xna.Framework.Color[9];
            TimeLogger.StartTimestamp startTimestamp = TimeLogger.Start();
            Main.tileBatch.Begin();
            int num = (int)(255f * (1f - Main.gfxQuality) + 140f * Main.gfxQuality);
            int num2 = (int)(200f * (1f - Main.gfxQuality) + 40f * Main.gfxQuality);
            int num3 = 128;
            Vector2 zero = new Vector2((float)Main.offScreenRange, (float)Main.offScreenRange);
            if (Main.drawToScreen)
            {
                zero = Vector2.Zero;
            }
            float num6;
            float num5;
            float num4 = (num5 = (num6 = 0.9f));
            float num7 = 0f;
            if (Main.SceneMetrics.BloodTileCount > Main.SceneMetrics.EvilTileCount && Main.SceneMetrics.BloodTileCount > Main.SceneMetrics.HolyTileCount)
            {
                num7 = (float)Main.SceneMetrics.BloodTileCount;
            }
            else if (Main.SceneMetrics.HolyTileCount > Main.SceneMetrics.EvilTileCount)
            {
                num7 = (float)Main.SceneMetrics.HolyTileCount;
            }
            else if (Main.SceneMetrics.EvilTileCount > Main.SceneMetrics.HolyTileCount)
            {
                num7 = (float)Main.SceneMetrics.EvilTileCount;
            }
            num7 = MathHelper.Clamp(num7 / 800f, 0f, 1f);
            float num8 = (float)((double)Main.screenPosition.Y - Main.worldSurface * 16.0) / 300f;
            if (num8 < 0f)
            {
                num8 = 0f;
            }
            else if (num8 > 1f)
            {
                num8 = 1f;
            }
            float num9 = 1f * (1f - num8) + num6 * num8;
            float num10 = Lighting.GlobalBrightness;
            Lighting.GlobalBrightness = num10 * (1f - num8) + 1f * num8;
            float num11 = (float)((double)(Main.screenPosition.Y - (float)(Main.screenHeight / 2) + 200f) - Main.rockLayer * 16.0) / 300f;
            num11 = MathHelper.Clamp(num11, 0f, 1f);
            if (Main.SceneMetrics.BloodTileCount > Main.SceneMetrics.EvilTileCount && Main.SceneMetrics.BloodTileCount > Main.SceneMetrics.HolyTileCount)
            {
                num6 = 1f * num7 + num6 * (1f - num7);
                num4 = 0.55f * num7 + num4 * (1f - num7);
                num5 = 0.5f * num7 + num5 * (1f - num7);
            }
            else if (Main.SceneMetrics.EvilTileCount > 0)
            {
                num6 = 0.8f * num7 + num6 * (1f - num7);
                num4 = 0.75f * num7 + num4 * (1f - num7);
                num5 = 1.1f * num7 + num5 * (1f - num7);
            }
            else if (Main.SceneMetrics.HolyTileCount > 0)
            {
                num6 = 1f * num7 + num6 * (1f - num7);
                num4 = 0.7f * num7 + num4 * (1f - num7);
                num5 = 0.9f * num7 + num5 * (1f - num7);
            }
            num6 = 1f * (num9 - num11) + num6 * num11;
            num4 = 1f * (num9 - num11) + num4 * num11;
            num5 = 1f * (num9 - num11) + num5 * num11;
            int num12 = (int)((Main.screenPosition.X + (float)(Main.screenWidth / 2)) / 16f);
            int num13;
            if (num12 <= Main.caveBackX[0])
            {
                num13 = Main.caveBackStyle[0];
            }
            else if (num12 <= Main.caveBackX[1])
            {
                num13 = Main.caveBackStyle[1];
            }
            else if (num12 <= Main.caveBackX[2])
            {
                num13 = Main.caveBackStyle[2];
            }
            else
            {
                num13 = Main.caveBackStyle[3];
            }
            num13 += 3;
            if (Main.SceneMetrics.SnowTileCount > SceneMetrics.SnowTileThreshold && (Main.screenPosition.Y + (float)Main.screenHeight) / 16f < (float)(Main.maxTilesY - 250))
            {
                num13 = 1;
            }
            if (Main.SceneMetrics.JungleTileCount > SceneMetrics.JungleTileThreshold)
            {
                if (num13 == 1)
                {
                    if (Main.SceneMetrics.JungleTileCount > Main.SceneMetrics.SnowTileCount)
                    {
                        num13 = 11;
                    }
                }
                else
                {
                    num13 = 11;
                }
            }
            if (Main.SceneMetrics.ZoneGlowshroom)
            {
                num13 = 2;
            }
            if (num13 != Main.undergroundBackground)
            {
                Main.oldUndergroundBackground = Main.undergroundBackground;
                Main.undergroundBackground = num13;
                Main.ugBackTransition = 1f;
            }
            if (Main.ugBackTransition > 0f)
            {
                Main.ugBackTransition -= 0.25f;
            }
            if (Main.ugBackTransition < 0f)
            {
                Main.ugBackTransition = 0f;
            }
            int[] array2 = new int[6];
            int[] array3 = new int[6];
            for (int i = 0; i < 2; i++)
            {
                int num14 = Main.undergroundBackground;
                if (i == 1)
                {
                    num14 = Main.oldUndergroundBackground;
                }
                int[] array4 = new int[6];
                if (num14 == 0)
                {
                    array4[0] = 1;
                    array4[1] = 2;
                    array4[2] = 4;
                    array4[3] = 3;
                    array4[4] = 6;
                    array4[5] = 5;
                }
                else if (num14 == 1)
                {
                    if (Main.iceBackStyle == 0)
                    {
                        array4[1] = 33;
                        array4[3] = 32;
                        array4[0] = 40;
                        array4[2] = 34;
                    }
                    else if (Main.iceBackStyle == 1)
                    {
                        array4[1] = 118;
                        array4[3] = 117;
                        array4[0] = 160;
                        array4[2] = 161;
                    }
                    else if (Main.iceBackStyle == 2)
                    {
                        array4[1] = 165;
                        array4[3] = 167;
                        array4[0] = 164;
                        array4[2] = 166;
                    }
                    else
                    {
                        array4[1] = 120;
                        array4[3] = 119;
                        array4[0] = 162;
                        array4[2] = 163;
                    }
                    array4[4] = array4[3];
                }
                else if (num14 == 2)
                {
                    array4[0] = 62;
                    array4[1] = 63;
                    array4[2] = 64;
                    array4[3] = 65;
                    array4[4] = 143 + Main.hellBackStyle;
                }
                else if (num14 == 3)
                {
                    array4[0] = 66;
                    array4[1] = 67;
                    array4[2] = 68;
                    array4[3] = 69;
                    array4[4] = 128 + Main.hellBackStyle;
                }
                else if (num14 == 4)
                {
                    array4[0] = 70;
                    array4[1] = 71;
                    array4[2] = 68;
                    array4[3] = 72;
                    array4[4] = 128 + Main.hellBackStyle;
                }
                else if (num14 == 5)
                {
                    array4[0] = 73;
                    array4[1] = 74;
                    array4[2] = 75;
                    array4[3] = 76;
                    array4[4] = 131 + Main.hellBackStyle;
                }
                else if (num14 == 6)
                {
                    array4[0] = 77;
                    array4[1] = 78;
                    array4[2] = 79;
                    array4[3] = 80;
                    array4[4] = 134 + Main.hellBackStyle;
                }
                else if (num14 == 7)
                {
                    array4[0] = 77;
                    array4[1] = 81;
                    array4[2] = 79;
                    array4[3] = 82;
                    array4[4] = 134 + Main.hellBackStyle;
                }
                else if (num14 == 8)
                {
                    array4[0] = 83;
                    array4[1] = 84;
                    array4[2] = 85;
                    array4[3] = 86;
                    array4[4] = 137 + Main.hellBackStyle;
                }
                else if (num14 == 9)
                {
                    array4[0] = 83;
                    array4[1] = 87;
                    array4[2] = 88;
                    array4[3] = 89;
                    array4[4] = 137 + Main.hellBackStyle;
                }
                else if (num14 == 10)
                {
                    array4[0] = 121;
                    array4[1] = 122;
                    array4[2] = 123;
                    array4[3] = 124;
                    array4[4] = 140 + Main.hellBackStyle;
                }
                else if (num14 == 11)
                {
                    if (Main.jungleBackStyle == 0)
                    {
                        array4[0] = 153;
                        array4[1] = 147;
                        array4[2] = 148;
                        array4[3] = 149;
                        array4[4] = 150 + Main.hellBackStyle;
                    }
                    else
                    {
                        array4[0] = 146;
                        array4[1] = 154;
                        array4[2] = 155;
                        array4[3] = 156;
                        array4[4] = 157 + Main.hellBackStyle;
                    }
                }
                if (Main.hellBackStyle == 0)
                {
                    array4[5] = 125;
                }
                if (Main.hellBackStyle == 1)
                {
                    array4[5] = 126;
                }
                if (Main.hellBackStyle == 2)
                {
                    array4[5] = 127;
                }
                this.LoadBackground(array4[0]);
                this.LoadBackground(array4[1]);
                this.LoadBackground(array4[2]);
                this.LoadBackground(array4[3]);
                this.LoadBackground(array4[4]);
                this.LoadBackground(array4[5]);
                if (i == 0)
                {
                    for (int j = 0; j < 6; j++)
                    {
                        array2[j] = array4[j];
                    }
                }
                else
                {
                    for (int k = 0; k < 6; k++)
                    {
                        array3[k] = array4[k];
                    }
                }
            }
            num10 = 1.2f * (1f - num11) + 1f * num11;
            this.bgParallax = (double)Main.caveParallax;
            this.bgStartX = (int)(-Math.IEEERemainder((double)num3 + (double)Main.screenPosition.X * this.bgParallax, (double)num3) - (double)(num3 / 2)) - (int)zero.X;
            this.bgLoops = (Main.screenWidth + (int)zero.X * 2) / num3 + 2;
            this.bgTopY = (float)Main.worldSurface * 16f - 16f - Main.screenPosition.Y + 16f;
            for (int l = 0; l < this.bgLoops; l++)
            {
                for (int m = 0; m < num3 / 16; m++)
                {
                    int num15 = (int)((float)Math.Round((double)(-(double)((float)Math.IEEERemainder((double)((float)this.bgStartX + Main.screenPosition.X), 16.0)))));
                    if (num15 == -8)
                    {
                        num15 = 8;
                    }
                    float num16 = (float)(this.bgStartX + num3 * l + m * 16 + 8);
                    float num17 = this.bgTopY;
                    Microsoft.Xna.Framework.Color color = Lighting.GetColor((int)((num16 + Main.screenPosition.X) / 16f), (int)((Main.screenPosition.Y + num17) / 16f));
                    color.R = (byte)((float)color.R * num6);
                    color.G = (byte)((float)color.G * num4);
                    color.B = (byte)((float)color.B * num5);
                    Main.spriteBatch.Draw(TextureAssets.Background[array2[0]].Value, new Vector2((float)(this.bgStartX + num3 * l + 16 * m + num15), this.bgTopY) + zero, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * m + num15 + 16, 0, 16, 16)), color);
                    if (Main.ugBackTransition > 0f)
                    {
                        Microsoft.Xna.Framework.Color color2 = color;
                        color2.R = (byte)((float)color2.R * Main.ugBackTransition);
                        color2.G = (byte)((float)color2.G * Main.ugBackTransition);
                        color2.B = (byte)((float)color2.B * Main.ugBackTransition);
                        color2.A = (byte)((float)color2.A * Main.ugBackTransition);
                        Main.spriteBatch.Draw(TextureAssets.Background[array3[0]].Value, new Vector2((float)(this.bgStartX + num3 * l + 16 * m + num15), this.bgTopY) + zero, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * m + num15 + 16, 0, 16, 16)), color2);
                    }
                }
            }
            double num18 = (double)(Main.maxTilesY - 230);
            double num19 = (double)((int)((num18 - Main.worldSurface) / 6.0) * 6);
            num18 = Main.worldSurface + num19 - 5.0;
            bool flag = false;
            bool flag2 = false;
            this.bgTopY = (float)Main.worldSurface * 16f - Main.screenPosition.Y + 16f;
            if (Main.worldSurface * 16.0 <= (double)(Main.screenPosition.Y + (float)Main.screenHeight + (float)Main.offScreenRange))
            {
                this.bgParallax = (double)Main.caveParallax;
                this.bgStartX = (int)(-Math.IEEERemainder((double)num3 + (double)Main.screenPosition.X * this.bgParallax, (double)num3) - (double)(num3 / 2)) - (int)zero.X;
                this.bgLoops = (Main.screenWidth + (int)zero.X * 2) / num3 + 2;
                if (Main.worldSurface * 16.0 < (double)(Main.screenPosition.Y - 16f))
                {
                    this.bgStartY = (int)(Math.IEEERemainder((double)this.bgTopY, (double)Main.backgroundHeight[2]) - (double)Main.backgroundHeight[2]);
                    this.bgLoopsY = (Main.screenHeight - this.bgStartY + (int)zero.Y * 2) / Main.backgroundHeight[2] + 1;
                }
                else
                {
                    this.bgStartY = (int)this.bgTopY;
                    this.bgLoopsY = (int)((float)Main.screenHeight - this.bgTopY + zero.Y * 2f) / Main.backgroundHeight[2] + 1;
                }
                if (Main.rockLayer * 16.0 < (double)(Main.Camera.ScaledPosition.Y + 600f))
                {
                    this.bgLoopsY = (int)(Main.rockLayer * 16.0 - (double)Main.screenPosition.Y + 600.0 - (double)this.bgStartY) / Main.backgroundHeight[2];
                    flag2 = true;
                }
                int num20 = (int)((float)Math.Round((double)(-(double)((float)Math.IEEERemainder((double)((float)this.bgStartX + Main.screenPosition.X), 16.0)))));
                if (num20 == -8)
                {
                    num20 = 8;
                }
                for (int n = 0; n < this.bgLoops; n++)
                {
                    for (int num21 = 0; num21 < this.bgLoopsY; num21++)
                    {
                        for (int num22 = 0; num22 < num3 / 16; num22++)
{
                            for (int num23 = 0; num23 < 6; num23++)
{
                                float num24 = (float)(this.bgStartY + num21 * 96 + num23 * 16 + 8);
                                int num25 = (int)(((float)(this.bgStartX + num3 * n + num22 * 16 + 8) + Main.screenPosition.X) / 16f);
                                int num26 = (int)((num24 + Main.screenPosition.Y) / 16f);
                                Microsoft.Xna.Framework.Color color3 = Lighting.GetColor(num25, num26);
                                if (Main.tile[num25, num26] == null)
{
                                    Main.tile[num25, num26] = new Tile();
                                }
                                if (color3.R > 0 || color3.G > 0 || color3.B > 0)
{
                                    if (!Main.drawToScreen)
{
                                        VertexColors vertexColors;
                                        Lighting.GetCornerColors(num25, num26, out vertexColors, 1f);
                                        Main.tileBatch.Draw(TextureAssets.Background[array2[1]].Value, new Vector2((float)(this.bgStartX + num3 * n + 16 * num22 + num20), (float)(this.bgStartY + Main.backgroundHeight[array2[1]] * num21 + 16 * num23)) + zero, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * num22 + num20 + 16, 16 * num23, 16, 16)), vertexColors, Vector2.Zero, 1f, SpriteEffects.None);
                                    }
                                    else
{
                                        if (((int)color3.R > num || (double)color3.G > (double)num * 1.1 || (double)color3.B > (double)num * 1.2) && !Main.tile[num25, num26].active() && Main.WallLightAt(num25, num26) && Main.ugBackTransition == 0f)
{
                                            Lighting.GetColor9Slice(num25, num26, ref array);
                                            try
{
                                                for (int num27 = 0; num27 < 9; num27++)
{
                                                    int num28 = 0;
                                                    int num29 = 0;
                                                    int num30 = 4;
                                                    int num31 = 4;
                                                    Microsoft.Xna.Framework.Color color4 = color3;
                                                    Microsoft.Xna.Framework.Color color5 = color3;
                                                    switch (num27)
{
                                                    case 0:
                                                        if (!Main.tile[num25 - 1, num26 - 1].active())
{
                                                            color5 = array[num27];
                                                        }
                                                        break;
                                                    case 1:
                                                        num30 = 8;
                                                        num28 = 4;
                                                        if (!Main.tile[num25, num26 - 1].active())
{
                                                            color5 = array[num27];
                                                        }
                                                        break;
                                                    case 2:
                                                        num28 = 12;
                                                        if (!Main.tile[num25 + 1, num26 - 1].active())
{
                                                            color5 = array[num27];
                                                        }
                                                        break;
                                                    case 3:
                                                        num31 = 8;
                                                        num29 = 4;
                                                        if (!Main.tile[num25 - 1, num26].active())
{
                                                            color5 = array[num27];
                                                        }
                                                        break;
                                                    case 4:
                                                        num30 = 8;
                                                        num31 = 8;
                                                        num28 = 4;
                                                        num29 = 4;
                                                        break;
                                                    case 5:
                                                        num28 = 12;
                                                        num29 = 4;
                                                        num31 = 8;
                                                        if (!Main.tile[num25 + 1, num26].active())
{
                                                            color5 = array[num27];
                                                        }
                                                        break;
                                                    case 6:
                                                        num29 = 12;
                                                        if (!Main.tile[num25 - 1, num26 + 1].active())
{
                                                            color5 = array[num27];
                                                        }
                                                        break;
                                                    case 7:
                                                        num30 = 8;
                                                        num31 = 4;
                                                        num28 = 4;
                                                        num29 = 12;
                                                        if (!Main.tile[num25, num26 + 1].active())
{
                                                            color5 = array[num27];
                                                        }
                                                        break;
                                                    case 8:
                                                        num28 = 12;
                                                        num29 = 12;
                                                        if (!Main.tile[num25 + 1, num26 + 1].active())
{
                                                            color5 = array[num27];
                                                        }
                                                        break;
                                                    }
                                                    color4.R = (color3.R + color5.R) / 2;
                                                    color4.G = (color3.G + color5.G) / 2;
                                                    color4.B = (color3.B + color5.B) / 2;
                                                    color4.R = (byte)((float)color4.R * num6);
                                                    color4.G = (byte)((float)color4.G * num4);
                                                    color4.B = (byte)((float)color4.B * num5);
                                                    Main.spriteBatch.Draw(TextureAssets.Background[array2[1]].Value, new Vector2((float)(this.bgStartX + num3 * n + 16 * num22 + num28 + num20), (float)(this.bgStartY + Main.backgroundHeight[array2[1]] * num21 + 16 * num23 + num29)) + zero, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * num22 + num28 + num20 + 16, 16 * num23 + num29, num30, num31)), color4);
                                                    if (Main.ugBackTransition > 0f)
{
                                                        Microsoft.Xna.Framework.Color color6 = color4;
                                                        color6.R = (byte)((float)color6.R * Main.ugBackTransition);
                                                        color6.G = (byte)((float)color6.G * Main.ugBackTransition);
                                                        color6.B = (byte)((float)color6.B * Main.ugBackTransition);
                                                        color6.A = (byte)((float)color6.A * Main.ugBackTransition);
                                                        Main.spriteBatch.Draw(TextureAssets.Background[array3[1]].Value, new Vector2((float)(this.bgStartX + num3 * n + 16 * num22 + num28 + num20), (float)(this.bgStartY + Main.backgroundHeight[array3[1]] * num21 + 16 * num23 + num29)) + zero, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * num22 + num28 + num20 + 16, 16 * num23 + num29, num30, num31)), color6);
                                                    }
                                                }
                                                goto IL_187D;
                                            }
                                            catch
{
                                                color3.R = (byte)((float)color3.R * num6);
                                                color3.G = (byte)((float)color3.G * num4);
                                                color3.B = (byte)((float)color3.B * num5);
                                                Main.spriteBatch.Draw(TextureAssets.Background[array2[1]].Value, new Vector2((float)(this.bgStartX + num3 * n + 16 * num22 + num20), (float)(this.bgStartY + Main.backgroundHeight[array2[1]] * num21 + 16 * num23)) + zero, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * num22 + num20 + 16, 16 * num23, 16, 16)), color3);
                                                goto IL_187D;
                                            }
                                        }
                                        if (((int)color3.R > num2 || (double)color3.G > (double)num2 * 1.1 || (double)color3.B > (double)num2 * 1.2) && Main.ugBackTransition == 0f)
{
                                            Lighting.GetColor4Slice(num25, num26, ref array);
                                            for (int num32 = 0; num32 < 4; num32++)
{
                                                int num33 = 0;
                                                int num34 = 0;
                                                Microsoft.Xna.Framework.Color color7 = color3;
                                                Microsoft.Xna.Framework.Color color8 = array[num32];
                                                switch (num32)
{
                                                case 1:
                                                    num33 = 8;
                                                    break;
                                                case 2:
                                                    num34 = 8;
                                                    break;
                                                case 3:
                                                    num33 = 8;
                                                    num34 = 8;
                                                    break;
                                                }
                                                color7.R = (color3.R + color8.R) / 2;
                                                color7.G = (color3.G + color8.G) / 2;
                                                color7.B = (color3.B + color8.B) / 2;
                                                color7.R = (byte)((float)color7.R * num6);
                                                color7.G = (byte)((float)color7.G * num4);
                                                color7.B = (byte)((float)color7.B * num5);
                                                Main.spriteBatch.Draw(TextureAssets.Background[array2[1]].Value, new Vector2((float)(this.bgStartX + num3 * n + 16 * num22 + num33 + num20), (float)(this.bgStartY + Main.backgroundHeight[array2[1]] * num21 + 16 * num23 + num34)) + zero, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * num22 + num33 + num20 + 16, 16 * num23 + num34, 8, 8)), color7);
                                                if (Main.ugBackTransition > 0f)
{
                                                    Microsoft.Xna.Framework.Color color9 = color7;
                                                    color9.R = (byte)((float)color9.R * Main.ugBackTransition);
                                                    color9.G = (byte)((float)color9.G * Main.ugBackTransition);
                                                    color9.B = (byte)((float)color9.B * Main.ugBackTransition);
                                                    color9.A = (byte)((float)color9.A * Main.ugBackTransition);
                                                    Main.spriteBatch.Draw(TextureAssets.Background[array3[1]].Value, new Vector2((float)(this.bgStartX + num3 * n + 16 * num22 + num33 + num20), (float)(this.bgStartY + Main.backgroundHeight[array3[1]] * num21 + 16 * num23 + num34)) + zero, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * num22 + num33 + num20 + 16, 16 * num23 + num34, 8, 8)), color9);
                                                }
                                            }
                                        }
                                        else
{
                                            color3.R = (byte)((float)color3.R * num6);
                                            color3.G = (byte)((float)color3.G * num4);
                                            color3.B = (byte)((float)color3.B * num5);
                                            Main.spriteBatch.Draw(TextureAssets.Background[array2[1]].Value, new Vector2((float)(this.bgStartX + num3 * n + 16 * num22 + num20), (float)(this.bgStartY + Main.backgroundHeight[array2[1]] * num21 + 16 * num23)) + zero, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * num22 + num20 + 16, 16 * num23, 16, 16)), color3);
                                            if (Main.ugBackTransition > 0f)
{
                                                Microsoft.Xna.Framework.Color color10 = color3;
                                                color10.R = (byte)((float)color10.R * Main.ugBackTransition);
                                                color10.G = (byte)((float)color10.G * Main.ugBackTransition);
                                                color10.B = (byte)((float)color10.B * Main.ugBackTransition);
                                                color10.A = (byte)((float)color10.A * Main.ugBackTransition);
                                                Main.spriteBatch.Draw(TextureAssets.Background[array3[1]].Value, new Vector2((float)(this.bgStartX + num3 * n + 16 * num22 + num20), (float)(this.bgStartY + Main.backgroundHeight[array3[1]] * num21 + 16 * num23)) + zero, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * num22 + num20 + 16, 16 * num23, 16, 16)), color10);
                                            }
                                        }
                                    }
                                }
                                else
{
                                    color3.R = (byte)((float)color3.R * num6);
                                    color3.G = (byte)((float)color3.G * num4);
                                    color3.B = (byte)((float)color3.B * num5);
                                    Main.spriteBatch.Draw(TextureAssets.Background[array2[1]].Value, new Vector2((float)(this.bgStartX + num3 * n + 16 * num22 + num20), (float)(this.bgStartY + Main.backgroundHeight[array2[1]] * num21 + 16 * num23)) + zero, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * num22 + num20 + 16, 16 * num23, 16, 16)), color3);
                                }
                                IL_187D:;
                            }
                        }
                    }
                }
                if (Main.ugBackTransition > 0f)
                {
                    for (int num35 = 0; num35 < this.bgLoops; num35++)
                    {
                        for (int num36 = 0; num36 < this.bgLoopsY; num36++)
{
                            for (int num37 = 0; num37 < num3 / 16; num37++)
{
                                for (int num38 = 0; num38 < 6; num38++)
{
                                    float num39 = (float)(this.bgStartY + num36 * 96 + num38 * 16 + 8);
                                    int num40 = (int)(((float)(this.bgStartX + num3 * num35 + num37 * 16 + 8) + Main.screenPosition.X) / 16f);
                                    int num41 = (int)((num39 + Main.screenPosition.Y) / 16f);
                                    Microsoft.Xna.Framework.Color color11 = Lighting.GetColor(num40, num41);
                                    if (Main.tile[num40, num41] == null)
{
                                        Main.tile[num40, num41] = new Tile();
                                    }
                                    if (color11.R > 0 || color11.G > 0 || color11.B > 0)
{
                                        VertexColors vertexColors2;
                                        Lighting.GetCornerColors(num40, num41, out vertexColors2, Main.ugBackTransition);
                                        byte b = (byte)(255f * Main.ugBackTransition);
                                        vertexColors2.BottomLeftColor.A = b;
                                        vertexColors2.BottomRightColor.A = b;
                                        vertexColors2.TopLeftColor.A = b;
                                        vertexColors2.TopRightColor.A = b;
                                        Main.tileBatch.Draw(TextureAssets.Background[array3[1]].Value, new Vector2((float)(this.bgStartX + num3 * num35 + 16 * num37 + num20), (float)(this.bgStartY + Main.backgroundHeight[array3[1]] * num36 + 16 * num38)) + zero, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * num37 + num20 + 16, 16 * num38, 16, 16)), vertexColors2, Vector2.Zero, 1f, SpriteEffects.None);
                                    }
                                }
                            }
                        }
                    }
                }
                if (flag2)
                {
                    this.bgParallax = (double)Main.caveParallax;
                    this.bgStartX = (int)(-Math.IEEERemainder((double)num3 + (double)Main.screenPosition.X * this.bgParallax, (double)num3) - (double)(num3 / 2)) - (int)zero.X;
                    this.bgLoops = (Main.screenWidth + (int)zero.X * 2) / num3 + 2;
                    this.bgTopY = (float)(this.bgStartY + this.bgLoopsY * Main.backgroundHeight[2]);
                    if (this.bgTopY > -32f)
                    {
                        for (int num42 = 0; num42 < this.bgLoops; num42++)
{
                            for (int num43 = 0; num43 < num3 / 16; num43++)
{
                                float num44 = (float)(this.bgStartX + num3 * num42 + num43 * 16 + 8);
                                float num45 = this.bgTopY;
                                Microsoft.Xna.Framework.Color color12 = Lighting.GetColor((int)((num44 + Main.screenPosition.X) / 16f), (int)((Main.screenPosition.Y + num45) / 16f));
                                color12.R = (byte)((float)color12.R * num6);
                                color12.G = (byte)((float)color12.G * num4);
                                color12.B = (byte)((float)color12.B * num5);
                                Main.spriteBatch.Draw(TextureAssets.Background[array2[2]].Value, new Vector2((float)(this.bgStartX + num3 * num42 + 16 * num43 + num20), this.bgTopY) + zero, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * num43 + num20 + 16, 0, 16, 16)), color12);
                                if (Main.ugBackTransition > 0f)
{
                                    Microsoft.Xna.Framework.Color color13 = color12;
                                    color13.R = (byte)((float)color13.R * Main.ugBackTransition);
                                    color13.G = (byte)((float)color13.G * Main.ugBackTransition);
                                    color13.B = (byte)((float)color13.B * Main.ugBackTransition);
                                    color13.A = (byte)((float)color13.A * Main.ugBackTransition);
                                    Main.spriteBatch.Draw(TextureAssets.Background[array3[2]].Value, new Vector2((float)(this.bgStartX + num3 * num42 + 16 * num43 + num20), this.bgTopY) + zero, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * num43 + num20 + 16, 0, 16, 16)), color13);
                                }
                            }
                        }
                    }
                }
            }
            this.bgTopY = (float)Main.rockLayer * 16f - Main.screenPosition.Y + 16f + 600f - 8f;
            if (Main.rockLayer * 16.0 <= (double)(Main.screenPosition.Y + 600f))
            {
                this.bgParallax = (double)Main.caveParallax;
                this.bgStartX = (int)(-Math.IEEERemainder((double)num3 + (double)Main.screenPosition.X * this.bgParallax, (double)num3) - (double)(num3 / 2)) - (int)zero.X;
                this.bgLoops = (Main.screenWidth + (int)zero.X * 2) / num3 + 2;
                if (Main.rockLayer * 16.0 + (double)Main.screenHeight < (double)(Main.screenPosition.Y - 16f))
                {
                    this.bgStartY = (int)(Math.IEEERemainder((double)this.bgTopY, (double)Main.backgroundHeight[3]) - (double)Main.backgroundHeight[3]);
                    this.bgLoopsY = (Main.screenHeight - this.bgStartY + (int)zero.Y * 2) / Main.backgroundHeight[2] + 1;
                }
                else
                {
                    this.bgStartY = (int)this.bgTopY;
                    this.bgLoopsY = (int)((float)Main.screenHeight - this.bgTopY + zero.Y * 2f) / Main.backgroundHeight[2] + 1;
                }
                if (num18 * 16.0 < (double)(Main.screenPosition.Y + 600f))
                {
                    this.bgLoopsY = (int)(num18 * 16.0 - (double)Main.screenPosition.Y + 600.0 - (double)this.bgStartY) / Main.backgroundHeight[2];
                    flag = true;
                }
                int num46 = (int)((float)Math.Round((double)(-(double)((float)Math.IEEERemainder((double)((float)this.bgStartX + Main.screenPosition.X), 16.0)))));
                if (num46 == -8)
                {
                    num46 = 8;
                }
                for (int num47 = 0; num47 < this.bgLoops; num47++)
                {
                    for (int num48 = 0; num48 < this.bgLoopsY; num48++)
                    {
                        for (int num49 = 0; num49 < num3 / 16; num49++)
{
                            for (int num50 = 0; num50 < 6; num50++)
{
                                float num51 = (float)(this.bgStartY + num48 * 96 + num50 * 16 + 8);
                                int num52 = (int)(((float)(this.bgStartX + num3 * num47 + num49 * 16 + 8) + Main.screenPosition.X) / 16f);
                                int num53 = (int)((num51 + Main.screenPosition.Y) / 16f);
                                Microsoft.Xna.Framework.Color color14 = Lighting.GetColor(num52, num53);
                                if ((Main.ShouldDrawBackgroundTileAt(num52, num53) || color14.R == 0 || color14.G == 0 || color14.B == 0) && (color14.R > 0 || color14.G > 0 || color14.B > 0) && (Main.WallLightAt(num52, num53) || Main.caveParallax != 0f))
{
                                    if (Lighting.NotRetro && color14.R < 230 && color14.G < 230 && color14.B < 230 && Main.ugBackTransition == 0f)
{
                                        if (((int)color14.R > num || (double)color14.G > (double)num * 1.1 || (double)color14.B > (double)num * 1.2) && !Main.tile[num52, num53].active())
{
                                            Lighting.GetColor9Slice(num52, num53, ref array);
                                            for (int num54 = 0; num54 < 9; num54++)
{
                                                int num55 = 0;
                                                int num56 = 0;
                                                int num57 = 4;
                                                int num58 = 4;
                                                Microsoft.Xna.Framework.Color color15 = color14;
                                                Microsoft.Xna.Framework.Color color16 = color14;
                                                switch (num54)
{
                                                case 0:
                                                    if (!Main.tile[num52 - 1, num53 - 1].active())
{
                                                        color16 = array[num54];
                                                    }
                                                    break;
                                                case 1:
                                                    num57 = 8;
                                                    num55 = 4;
                                                    if (!Main.tile[num52, num53 - 1].active())
{
                                                        color16 = array[num54];
                                                    }
                                                    break;
                                                case 2:
                                                    num55 = 12;
                                                    if (!Main.tile[num52 + 1, num53 - 1].active())
{
                                                        color16 = array[num54];
                                                    }
                                                    break;
                                                case 3:
                                                    num58 = 8;
                                                    num56 = 4;
                                                    if (!Main.tile[num52 - 1, num53].active())
{
                                                        color16 = array[num54];
                                                    }
                                                    break;
                                                case 4:
                                                    num57 = 8;
                                                    num58 = 8;
                                                    num55 = 4;
                                                    num56 = 4;
                                                    break;
                                                case 5:
                                                    num55 = 12;
                                                    num56 = 4;
                                                    num58 = 8;
                                                    if (!Main.tile[num52 + 1, num53].active())
{
                                                        color16 = array[num54];
                                                    }
                                                    break;
                                                case 6:
                                                    num56 = 12;
                                                    if (!Main.tile[num52 - 1, num53 + 1].active())
{
                                                        color16 = array[num54];
                                                    }
                                                    break;
                                                case 7:
                                                    num57 = 8;
                                                    num58 = 4;
                                                    num55 = 4;
                                                    num56 = 12;
                                                    if (!Main.tile[num52, num53 + 1].active())
{
                                                        color16 = array[num54];
                                                    }
                                                    break;
                                                case 8:
                                                    num55 = 12;
                                                    num56 = 12;
                                                    if (!Main.tile[num52 + 1, num53 + 1].active())
{
                                                        color16 = array[num54];
                                                    }
                                                    break;
                                                }
                                                color15.R = (color14.R + color16.R) / 2;
                                                color15.G = (color14.G + color16.G) / 2;
                                                color15.B = (color14.B + color16.B) / 2;
                                                color15.R = (byte)((float)color15.R * num6);
                                                color15.G = (byte)((float)color15.G * num4);
                                                color15.B = (byte)((float)color15.B * num5);
                                                Main.spriteBatch.Draw(TextureAssets.Background[array2[3]].Value, new Vector2((float)(this.bgStartX + num3 * num47 + 16 * num49 + num55 + num46), (float)(this.bgStartY + Main.backgroundHeight[array2[3]] * num48 + 16 * num50 + num56)) + zero, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * num49 + num55 + num46 + 16, 16 * num50 + num56, num57, num58)), color15);
                                                if (Main.ugBackTransition > 0f)
{
                                                    Microsoft.Xna.Framework.Color color17 = color15;
                                                    color17.R = (byte)((float)color17.R * Main.ugBackTransition);
                                                    color17.G = (byte)((float)color17.G * Main.ugBackTransition);
                                                    color17.B = (byte)((float)color17.B * Main.ugBackTransition);
                                                    color17.A = (byte)((float)color17.A * Main.ugBackTransition);
                                                    Main.spriteBatch.Draw(TextureAssets.Background[array3[3]].Value, new Vector2((float)(this.bgStartX + num3 * num47 + 16 * num49 + num55 + num46), (float)(this.bgStartY + Main.backgroundHeight[array3[3]] * num48 + 16 * num50 + num56)) + zero, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * num49 + num55 + num46 + 16, 16 * num50 + num56, num57, num58)), color17);
                                                }
                                            }
                                        }
                                        else if ((int)color14.R > num2 || (double)color14.G > (double)num2 * 1.1 || (double)color14.B > (double)num2 * 1.2)
{
                                            Lighting.GetColor4Slice(num52, num53, ref array);
                                            for (int num59 = 0; num59 < 4; num59++)
{
                                                int num60 = 0;
                                                int num61 = 0;
                                                Microsoft.Xna.Framework.Color color18 = color14;
                                                Microsoft.Xna.Framework.Color color19 = array[num59];
                                                switch (num59)
{
                                                case 1:
                                                    num60 = 8;
                                                    break;
                                                case 2:
                                                    num61 = 8;
                                                    break;
                                                case 3:
                                                    num60 = 8;
                                                    num61 = 8;
                                                    break;
                                                }
                                                color18.R = (color14.R + color19.R) / 2;
                                                color18.G = (color14.G + color19.G) / 2;
                                                color18.B = (color14.B + color19.B) / 2;
                                                color18.R = (byte)((float)color18.R * num6);
                                                color18.G = (byte)((float)color18.G * num4);
                                                color18.B = (byte)((float)color18.B * num5);
                                                Main.spriteBatch.Draw(TextureAssets.Background[array2[3]].Value, new Vector2((float)(this.bgStartX + num3 * num47 + 16 * num49 + num60 + num46), (float)(this.bgStartY + Main.backgroundHeight[array2[3]] * num48 + 16 * num50 + num61)) + zero, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * num49 + num60 + num46 + 16, 16 * num50 + num61, 8, 8)), color18);
                                                if (Main.ugBackTransition > 0f)
{
                                                    Microsoft.Xna.Framework.Color color20 = color18;
                                                    color20.R = (byte)((float)color20.R * Main.ugBackTransition);
                                                    color20.G = (byte)((float)color20.G * Main.ugBackTransition);
                                                    color20.B = (byte)((float)color20.B * Main.ugBackTransition);
                                                    color20.A = (byte)((float)color20.A * Main.ugBackTransition);
                                                    Main.spriteBatch.Draw(TextureAssets.Background[array3[3]].Value, new Vector2((float)(this.bgStartX + num3 * num47 + 16 * num49 + num60 + num46), (float)(this.bgStartY + Main.backgroundHeight[array3[3]] * num48 + 16 * num50 + num61)) + zero, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * num49 + num60 + num46 + 16, 16 * num50 + num61, 8, 8)), color20);
                                                }
                                            }
                                        }
                                        else
{
                                            color14.R = (byte)((float)color14.R * num6);
                                            color14.G = (byte)((float)color14.G * num4);
                                            color14.B = (byte)((float)color14.B * num5);
                                            Main.spriteBatch.Draw(TextureAssets.Background[array2[3]].Value, new Vector2((float)(this.bgStartX + num3 * num47 + 16 * num49 + num46), (float)(this.bgStartY + Main.backgroundHeight[array2[3]] * num48 + 16 * num50)) + zero, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * num49 + num46 + 16, 16 * num50, 16, 16)), color14);
                                            if (Main.ugBackTransition > 0f)
{
                                                Microsoft.Xna.Framework.Color color21 = color14;
                                                color21.R = (byte)((float)color21.R * Main.ugBackTransition);
                                                color21.G = (byte)((float)color21.G * Main.ugBackTransition);
                                                color21.B = (byte)((float)color21.B * Main.ugBackTransition);
                                                color21.A = (byte)((float)color21.A * Main.ugBackTransition);
                                                Main.spriteBatch.Draw(TextureAssets.Background[array3[3]].Value, new Vector2((float)(this.bgStartX + num3 * num47 + 16 * num49 + num46), (float)(this.bgStartY + Main.backgroundHeight[array3[3]] * num48 + 16 * num50)) + zero, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * num49 + num46 + 16, 16 * num50, 16, 16)), color21);
                                            }
                                        }
                                    }
                                    else
{
                                        color14.R = (byte)((float)color14.R * num6);
                                        color14.G = (byte)((float)color14.G * num4);
                                        color14.B = (byte)((float)color14.B * num5);
                                        Main.spriteBatch.Draw(TextureAssets.Background[array2[3]].Value, new Vector2((float)(this.bgStartX + num3 * num47 + 16 * num49 + num46), (float)(this.bgStartY + Main.backgroundHeight[array2[3]] * num48 + 16 * num50)) + zero, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * num49 + num46 + 16, 16 * num50, 16, 16)), color14);
                                        if (Main.ugBackTransition > 0f)
{
                                            Microsoft.Xna.Framework.Color color22 = color14;
                                            color22.R = (byte)((float)color22.R * Main.ugBackTransition);
                                            color22.G = (byte)((float)color22.G * Main.ugBackTransition);
                                            color22.B = (byte)((float)color22.B * Main.ugBackTransition);
                                            color22.A = (byte)((float)color22.A * Main.ugBackTransition);
                                            Main.spriteBatch.Draw(TextureAssets.Background[array3[3]].Value, new Vector2((float)(this.bgStartX + num3 * num47 + 16 * num49 + num46), (float)(this.bgStartY + Main.backgroundHeight[array3[3]] * num48 + 16 * num50)) + zero, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * num49 + num46 + 16, 16 * num50, 16, 16)), color22);
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
                num3 = 128;
                if (flag)
                {
                    this.bgParallax = (double)Main.caveParallax;
                    this.bgStartX = (int)(-Math.IEEERemainder((double)num3 + (double)Main.screenPosition.X * this.bgParallax, (double)num3) - (double)(num3 / 2)) - (int)zero.X;
                    this.bgLoops = (Main.screenWidth + (int)zero.X * 2) / num3 + 2;
                    this.bgTopY = (float)(this.bgStartY + this.bgLoopsY * Main.backgroundHeight[2]);
                    for (int num62 = 0; num62 < this.bgLoops; num62++)
                    {
                        for (int num63 = 0; num63 < num3 / 16; num63++)
{
                            float num64 = (float)(this.bgStartX + num3 * num62 + num63 * 16 + 8);
                            float num65 = this.bgTopY;
                            Microsoft.Xna.Framework.Color color23 = Lighting.GetColor((int)((num64 + Main.screenPosition.X) / 16f), (int)((Main.screenPosition.Y + num65) / 16f));
                            color23.R = (byte)((float)color23.R * num6);
                            color23.G = (byte)((float)color23.G * num4);
                            color23.B = (byte)((float)color23.B * num5);
                            Main.spriteBatch.Draw(TextureAssets.Background[array2[4]].Value, new Vector2((float)(this.bgStartX + num3 * num62 + 16 * num63 + num46), this.bgTopY) + zero, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * num63 + num46 + 16, Main.magmaBGFrame * 16, 16, 16)), color23);
                            if (Main.ugBackTransition > 0f)
{
                                Microsoft.Xna.Framework.Color color24 = color23;
                                color24.R = (byte)((float)color24.R * Main.ugBackTransition);
                                color24.G = (byte)((float)color24.G * Main.ugBackTransition);
                                color24.B = (byte)((float)color24.B * Main.ugBackTransition);
                                color24.A = (byte)((float)color24.A * Main.ugBackTransition);
                                Main.spriteBatch.Draw(TextureAssets.Background[array3[4]].Value, new Vector2((float)(this.bgStartX + num3 * num62 + 16 * num63 + num46), this.bgTopY) + zero, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * num63 + num46 + 16, Main.magmaBGFrame * 16, 16, 16)), color24);
                            }
                        }
                    }
                }
            }
            this.bgTopY = (float)num18 * 16f - Main.screenPosition.Y + 16f + 600f - 8f;
            if (num18 * 16.0 <= (double)(Main.screenPosition.Y + 600f))
            {
                this.bgStartX = (int)(-Math.IEEERemainder((double)num3 + (double)Main.screenPosition.X * this.bgParallax, (double)num3) - (double)(num3 / 2)) - (int)zero.X;
                this.bgLoops = (Main.screenWidth + (int)zero.X * 2) / num3 + 2;
                if (num18 * 16.0 + (double)Main.screenHeight < (double)(Main.screenPosition.Y - 16f))
                {
                    this.bgStartY = (int)(Math.IEEERemainder((double)this.bgTopY, (double)Main.backgroundHeight[2]) - (double)Main.backgroundHeight[2]);
                    this.bgLoopsY = (Main.screenHeight - this.bgStartY + (int)zero.Y * 2) / Main.backgroundHeight[2] + 1;
                }
                else
                {
                    this.bgStartY = (int)this.bgTopY;
                    this.bgLoopsY = (int)((float)Main.screenHeight - this.bgTopY + zero.Y * 2f) / Main.backgroundHeight[2] + 1;
                }
                num = (int)((double)num * 1.5);
                num2 = (int)((double)num2 * 1.5);
                int num66 = (int)((float)Math.Round((double)(-(double)((float)Math.IEEERemainder((double)((float)this.bgStartX + Main.screenPosition.X), 16.0)))));
                if (num66 == -8)
                {
                    num66 = 8;
                }
                for (int num67 = 0; num67 < this.bgLoops; num67++)
                {
                    for (int num68 = 0; num68 < this.bgLoopsY; num68++)
                    {
                        for (int num69 = 0; num69 < num3 / 16; num69++)
{
                            for (int num70 = 0; num70 < 6; num70++)
{
                                float num71 = (float)(this.bgStartY + num68 * 96 + num70 * 16 + 8);
                                int num72 = (int)(((float)(this.bgStartX + num3 * num67 + num69 * 16 + 8) + Main.screenPosition.X) / 16f);
                                int num73 = (int)((num71 + Main.screenPosition.Y) / 16f);
                                Microsoft.Xna.Framework.Color color25 = Lighting.GetColor(num72, num73);
                                if ((Main.ShouldDrawBackgroundTileAt(num72, num73) || color25.R == 0 || color25.G == 0 || color25.B == 0) && (color25.R > 0 || color25.G > 0 || color25.B > 0) && (Main.WallLightAt(num72, num73) || Main.caveParallax != 0f))
{
                                    if (Lighting.NotRetro && color25.R < 230 && color25.G < 230 && color25.B < 230)
{
                                        if (((int)color25.R > num || (double)color25.G > (double)num * 1.1 || (double)color25.B > (double)num * 1.2) && !Main.tile[num72, num73].active())
{
                                            Lighting.GetColor9Slice(num72, num73, ref array);
                                            for (int num74 = 0; num74 < 9; num74++)
{
                                                int num75 = 0;
                                                int num76 = 0;
                                                int num77 = 4;
                                                int num78 = 4;
                                                Microsoft.Xna.Framework.Color color26 = color25;
                                                Microsoft.Xna.Framework.Color color27 = color25;
                                                switch (num74)
{
                                                case 0:
                                                    if (!Main.tile[num72 - 1, num73 - 1].active())
{
                                                        color27 = array[num74];
                                                    }
                                                    break;
                                                case 1:
                                                    num77 = 8;
                                                    num75 = 4;
                                                    if (!Main.tile[num72, num73 - 1].active())
{
                                                        color27 = array[num74];
                                                    }
                                                    break;
                                                case 2:
                                                    num75 = 12;
                                                    if (!Main.tile[num72 + 1, num73 - 1].active())
{
                                                        color27 = array[num74];
                                                    }
                                                    break;
                                                case 3:
                                                    num78 = 8;
                                                    num76 = 4;
                                                    if (!Main.tile[num72 - 1, num73].active())
{
                                                        color27 = array[num74];
                                                    }
                                                    break;
                                                case 4:
                                                    num77 = 8;
                                                    num78 = 8;
                                                    num75 = 4;
                                                    num76 = 4;
                                                    break;
                                                case 5:
                                                    num75 = 12;
                                                    num76 = 4;
                                                    num78 = 8;
                                                    if (!Main.tile[num72 + 1, num73].active())
{
                                                        color27 = array[num74];
                                                    }
                                                    break;
                                                case 6:
                                                    num76 = 12;
                                                    if (!Main.tile[num72 - 1, num73 + 1].active())
{
                                                        color27 = array[num74];
                                                    }
                                                    break;
                                                case 7:
                                                    num77 = 8;
                                                    num78 = 4;
                                                    num75 = 4;
                                                    num76 = 12;
                                                    if (!Main.tile[num72, num73 + 1].active())
{
                                                        color27 = array[num74];
                                                    }
                                                    break;
                                                case 8:
                                                    num75 = 12;
                                                    num76 = 12;
                                                    if (!Main.tile[num72 + 1, num73 + 1].active())
{
                                                        color27 = array[num74];
                                                    }
                                                    break;
                                                }
                                                color26.R = (color25.R + color27.R) / 2;
                                                color26.G = (color25.G + color27.G) / 2;
                                                color26.B = (color25.B + color27.B) / 2;
                                                color26.R = (byte)((float)color26.R * num6);
                                                color26.G = (byte)((float)color26.G * num4);
                                                color26.B = (byte)((float)color26.B * num5);
                                                Main.spriteBatch.Draw(TextureAssets.Background[array2[5]].Value, new Vector2((float)(this.bgStartX + num3 * num67 + 16 * num69 + num75 + num66), (float)(this.bgStartY + Main.backgroundHeight[2] * num68 + 16 * num70 + num76)) + zero, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * num69 + num75 + num66 + 16, 16 * num70 + Main.backgroundHeight[2] * Main.magmaBGFrame + num76, num77, num78)), color26, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
                                            }
                                        }
                                        else if ((int)color25.R > num2 || (double)color25.G > (double)num2 * 1.1 || (double)color25.B > (double)num2 * 1.2)
{
                                            Lighting.GetColor4Slice(num72, num73, ref array);
                                            for (int num79 = 0; num79 < 4; num79++)
{
                                                int num80 = 0;
                                                int num81 = 0;
                                                Microsoft.Xna.Framework.Color color28 = color25;
                                                Microsoft.Xna.Framework.Color color29 = array[num79];
                                                switch (num79)
{
                                                case 1:
                                                    num80 = 8;
                                                    break;
                                                case 2:
                                                    num81 = 8;
                                                    break;
                                                case 3:
                                                    num80 = 8;
                                                    num81 = 8;
                                                    break;
                                                }
                                                color28.R = (color25.R + color29.R) / 2;
                                                color28.G = (color25.G + color29.G) / 2;
                                                color28.B = (color25.B + color29.B) / 2;
                                                color28.R = (byte)((float)color28.R * num6);
                                                color28.G = (byte)((float)color28.G * num4);
                                                color28.B = (byte)((float)color28.B * num5);
                                                Main.spriteBatch.Draw(TextureAssets.Background[array2[5]].Value, new Vector2((float)(this.bgStartX + num3 * num67 + 16 * num69 + num80 + num66), (float)(this.bgStartY + Main.backgroundHeight[2] * num68 + 16 * num70 + num81)) + zero, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * num69 + num80 + num66 + 16, 16 * num70 + Main.backgroundHeight[2] * Main.magmaBGFrame + num81, 8, 8)), color28, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
                                            }
                                        }
                                        else
{
                                            color25.R = (byte)((float)color25.R * num6);
                                            color25.G = (byte)((float)color25.G * num4);
                                            color25.B = (byte)((float)color25.B * num5);
                                            Main.spriteBatch.Draw(TextureAssets.Background[array2[5]].Value, new Vector2((float)(this.bgStartX + num3 * num67 + 16 * num69 + num66), (float)(this.bgStartY + Main.backgroundHeight[2] * num68 + 16 * num70)) + zero, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * num69 + num66 + 16, 16 * num70 + Main.backgroundHeight[2] * Main.magmaBGFrame, 16, 16)), color25, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
                                        }
                                    }
                                    else
{
                                        color25.R = (byte)((float)color25.R * num6);
                                        color25.G = (byte)((float)color25.G * num4);
                                        color25.B = (byte)((float)color25.B * num5);
                                        Main.spriteBatch.Draw(TextureAssets.Background[array2[5]].Value, new Vector2((float)(this.bgStartX + num3 * num67 + 16 * num69 + num66), (float)(this.bgStartY + Main.backgroundHeight[2] * num68 + 16 * num70)) + zero, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(16 * num69 + num66 + 16, 16 * num70 + Main.backgroundHeight[2] * Main.magmaBGFrame, 16, 16)), color25, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
                                    }
                                }
                            }
                        }
                    }
                }
            }
            Main.tileBatch.End();
            Lighting.GlobalBrightness = num10;
            TimeLogger.DrawOldUndergroundBackground.AddTime(startTimestamp);
        }
References Terraria.Tile.active(), System.array, Microsoft.Xna.Framework.Color.B, Terraria.GameContent.TextureAssets.Background, Terraria.Main.backgroundHeight, Terraria.Graphics.TileBatch.Begin(), Terraria.SceneMetrics.BloodTileCount, Terraria.Main.Camera, Terraria.Main.caveBackStyle, Terraria.Main.caveBackX, Terraria.Main.caveParallax, Microsoft.Xna.Framework.MathHelper.Clamp(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Graphics.TileBatch.Draw(), Terraria.TimeLogger.DrawOldUndergroundBackground, Terraria.Main.drawToScreen, Terraria.Graphics.TileBatch.End(), Terraria.SceneMetrics.EvilTileCount, Microsoft.Xna.Framework.Color.G, Terraria.Lighting.GetColor(), Terraria.Lighting.GetColor4Slice(), Terraria.Lighting.GetColor9Slice(), Terraria.Lighting.GetCornerColors(), Terraria.Main.gfxQuality, Terraria.Lighting.GlobalBrightness, Terraria.Main.hellBackStyle, Terraria.SceneMetrics.HolyTileCount, Terraria.Main.iceBackStyle, System.Math.IEEERemainder(), int, Terraria.Main.jungleBackStyle, Terraria.SceneMetrics.JungleTileCount, Terraria.SceneMetrics.JungleTileThreshold, Terraria.Main.magmaBGFrame, Terraria.Main.maxTilesY, Terraria.Lighting.NotRetro, Terraria.Main.offScreenRange, Terraria.Main.oldUndergroundBackground, Microsoft.Xna.Framework.Color.R, Terraria.Main.rockLayer, System.Math.Round(), Terraria.Graphics.Camera.ScaledPosition, Terraria.Main.SceneMetrics, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.ShouldDrawBackgroundTileAt(), Terraria.SceneMetrics.SnowTileCount, Terraria.SceneMetrics.SnowTileThreshold, Terraria.Main.spriteBatch, Terraria.TimeLogger.Start(), Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.Main.tileBatch, Terraria.Main.ugBackTransition, Terraria.Main.undergroundBackground, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Main.WallLightAt(), Terraria.Main.worldSurface, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, Microsoft.Xna.Framework.Vector2.Zero, and Terraria.SceneMetrics.ZoneGlowshroom.