Terraria Decompiled: Terraria.Main.CanDryadPlayStardewAnimation
CanDryadPlayStardewAnimation()
static bool Terraria.Main.CanDryadPlayStardewAnimation (Player player, NPC npc) inline static
Definition at line 40230 of file Main.cs.
        {
            Item heldItem = player.HeldItem;
            return !heldItem.IsAir && heldItem.type == 5275 && npc.ai[0] != 24f && npc.type == 20;
        }
References Terraria.NPC.ai, and Terraria.Player.HeldItem.
Referenced by Terraria.GameContent.NPCInteractions.Actions.StardewValleyBit.Condition(), Terraria.GameContent.NPCInteractions.Actions.DryadPurification.Condition(), Terraria.Main.DryadText_WorldPurityOrStardewValleyBit(), and Terraria.GameContent.UI.NPCChatPanel.OverrideChatTextWithShenanigans().