Terraria Decompiled: Terraria.Main.buffColor
buffColor()
static Microsoft.Xna.Framework.Color Terraria.Main.buffColor (Microsoft::Xna::Framework::Color newColor, float R, float G, float B, float A) inline static
Definition at line 37495 of file Main.cs.
        {
            newColor.R = (byte)((float)newColor.R * R);
            newColor.G = (byte)((float)newColor.G * G);
            newColor.B = (byte)((float)newColor.B * B);
            newColor.A = (byte)((float)newColor.A * A);
            return newColor;
        }
References Microsoft.Xna.Framework.Input.A, Microsoft.Xna.Framework.Input.B, Microsoft.Xna.Framework.Input.G, and Microsoft.Xna.Framework.Input.R.
Referenced by Terraria.DataStructures.PlayerDrawSet.BoringSetup(), Terraria.Main.DrawNPCDirect(), Terraria.Main.DrawSmartCursor(), and Terraria.Main.DrawSmartInteract().