Terraria Decompiled: Terraria.Main.GetInfoAccIconPosition
GetInfoAccIconPosition()
static void Terraria.Main.GetInfoAccIconPosition (int drawnCount, int StartX, out int X, out int Y) inline static private
Definition at line 47589 of file Main.cs.
        {
            if (!Main.playerInventory)
            {
                X = Main.screenWidth - 280;
                Y = -32;
                if (Main.mapStyle == 1 && Main.mapEnabled)
                {
                    Y += 261;
                }
            }
            else if (Main.ShouldDrawInfoIconsHorizontally)
            {
                X = Main.screenWidth - 280 + 20 * drawnCount - 10;
                Y = 94;
                if (Main.mapStyle == 1 && Main.mapEnabled)
                {
                    Y += 261;
                }
            }
            else
            {
                int num = (int)(52f * Main.inventoryScale);
                float num2 = 0.85f;
                int num3 = (int)(52f * num2);
                int npcs_IconsPerColumn = UILinkPointNavigator.Shortcuts.NPCS_IconsPerColumn;
                int npcs_IconsTotal = UILinkPointNavigator.Shortcuts.NPCS_IconsTotal;
                int num4 = (int)Math.Ceiling((double)((float)npcs_IconsTotal / (float)npcs_IconsPerColumn));
                int num5 = npcs_IconsTotal - Math.Max(0, (num4 - 1) * npcs_IconsPerColumn);
                int num6 = npcs_IconsPerColumn - num5;
                int num7 = Math.Max(0, num4 - 4);
                if (num4 >= 4 && num6 < 5)
                {
                    num7++;
                }
                int num8 = num7 * (num3 + 4);
                if (Main.EquipPage != 1)
                {
                    num8 = 0;
                }
                X = 697 - num * 4 + Main.screenWidth - 800 + 20 * (drawnCount % 2) - num8;
                Y = 114 + Main.mH + num * 7 + num / 2 + 20 * (drawnCount / 2) + 8 * (drawnCount / 4) - 20;
                if (Main.EquipPage == 2)
                {
                    X += num + num / 2;
                    Y -= num;
                }
            }
            X += StartX;
        }
References System.Math.Ceiling(), Terraria.Main.EquipPage, int, Terraria.Main.inventoryScale, Terraria.Main.mapEnabled, Terraria.Main.mapStyle, System.Math.Max(), Terraria.UI.Gamepad.UILinkPointNavigator.Shortcuts.NPCS_IconsPerColumn, Terraria.UI.Gamepad.UILinkPointNavigator.Shortcuts.NPCS_IconsTotal, Terraria.Main.playerInventory, Terraria.Main.ShouldDrawInfoIconsHorizontally, Microsoft.Xna.Framework.Input.X, and Microsoft.Xna.Framework.Input.Y.
Referenced by Terraria.Main.DrawInfoAccs().