Terraria Decompiled: Terraria.Main.CycleVoiceStyle
CycleVoiceStyle()
static void Terraria.Main.CycleVoiceStyle (Player plr, int offset) inline static
Definition at line 52931 of file Main.cs.
        {
            int num = 0;
            int[] variantOrder = PlayerVoiceID.VariantOrder;
            for (int i = 0; i < variantOrder.Length; i++)
            {
                if (variantOrder[i] == plr.voiceVariant)
                {
                    num = i;
                    break;
                }
            }
            num = (num + offset) % variantOrder.Length;
            if (num < 0)
            {
                num += variantOrder.Length;
            }
            plr.voiceVariant = variantOrder[num];
        }
References System.offset, Terraria.ID.PlayerVoiceID.VariantOrder, and Terraria.Player.voiceVariant.
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.Click_VoiceCycleBack(), Terraria.GameContent.UI.States.UICharacterCreation.Click_VoiceCycleForward(), and Terraria.Main.DrawClothesWindow().