Terraria Decompiled: Terraria.Main.DrawPlayerItemPos
DrawPlayerItemPos()
static Vector2 Terraria.Main.DrawPlayerItemPos (float gravdir, int itemtype) inline static
Definition at line 1120 of file Main.cs.
        {
            float num = 10f;
            Texture2D texture2D;
            Microsoft.Xna.Framework.Rectangle rectangle;
            Main.GetItemDrawFrame(itemtype, out texture2D, out rectangle);
            Vector2 vector = rectangle.Size() / 2f;
            if (itemtype == 95)
            {
                num = 6f;
                vector.Y += 2f * gravdir;
            }
            else if (itemtype == 5629)
            {
                num = 4f;
                vector.Y -= 2f * gravdir;
            }
            else if (itemtype == 1295)
            {
                num = 4f;
            }
            else if (itemtype == 5464)
            {
                num -= 8f;
            }
            else if (itemtype == 3611)
            {
                num = 2f;
            }
            else if (itemtype == 5495)
            {
                num = -2f;
            }
            else if (itemtype == 3350)
            {
                num = 2f;
            }
            else if (itemtype == 2624)
            {
                num = 4f;
            }
            else if (itemtype == 3018)
            {
                num = 2f;
            }
            else if (itemtype == 3007)
            {
                num = 4f;
                vector.Y -= 1f * gravdir;
            }
            else if (itemtype == 3107)
            {
                num = 4f;
                vector.Y += 2f * gravdir;
            }
            else if (itemtype == 3008)
            {
                num = -7f;
                vector.Y += 2f * gravdir;
            }
            else if (itemtype == 1255)
            {
                num = 6f;
                vector.Y += 0f * gravdir;
            }
            else if (itemtype == 2269)
            {
                num = 2f;
                vector.Y += 2f * gravdir;
            }
            else if (itemtype == 1265)
            {
                num = -8f;
                vector.Y += 4f * gravdir;
            }
            else if (itemtype == 2272)
            {
                num = 0f;
                vector.Y += 4f * gravdir;
            }
            else if (itemtype == 3029)
            {
                num = 4f;
            }
            else if (itemtype == 4381)
            {
                num = 4f;
            }
            else if (itemtype == 2796)
            {
                num = -28f;
                vector.Y += 2f * gravdir;
            }
            else if (itemtype == 2797)
            {
                num = 0f;
            }
            else if (itemtype == 2610)
            {
                num = 0f;
            }
            else if (itemtype == 2623)
            {
                num = -30f;
                vector.Y -= 4f * gravdir;
            }
            else if (itemtype == 3546)
            {
                num = -14f;
                vector.Y -= 6f * gravdir;
            }
            else if (itemtype == 1835)
            {
                num = -2f;
                vector.Y += 2f * gravdir;
            }
            else if (itemtype == 2624)
            {
                num = -4f;
            }
            else if (itemtype == 3859)
            {
                num = -2f;
            }
            else if (itemtype == 2888)
            {
                num = 6f;
            }
            else if (itemtype == 2223)
            {
                num = 2f;
                vector.Y -= 2f * gravdir;
            }
            else if (itemtype == 1782)
            {
                num = 0f;
                vector.Y += 4f * gravdir;
            }
            else if (itemtype == 1929)
            {
                num = 0f;
                vector.Y += 2f * gravdir;
            }
            else if (itemtype == 2270)
            {
                num = -4f;
            }
            else if (itemtype == 1784)
            {
                num = 0f;
                vector.Y += 4f * gravdir;
            }
            else if (itemtype == 1000)
            {
                num = 6f;
                vector.Y += 0f * gravdir;
            }
            else if (itemtype == 1178)
            {
                num = 4f;
                vector.Y += 0f * gravdir;
            }
            else if (itemtype == 1319)
            {
                num = 0f;
                vector.Y += 0f * gravdir;
            }
            else if (itemtype == 1297)
            {
                num = -8f;
                vector.Y += 0f * gravdir;
            }
            else if (itemtype == 1121)
            {
                num = 6f;
                vector.Y -= 2f * gravdir;
            }
            else if (itemtype == 1314)
            {
                num = 2f;
            }
            else if (itemtype == 1258)
            {
                num = 2f;
                vector.Y -= 2f * gravdir;
            }
            else if (itemtype == 1155)
            {
                num = -10f;
                vector.Y -= 2f * gravdir;
            }
            else if (itemtype == 1156)
            {
                num = -2f;
            }
            else if (itemtype == 4703)
            {
                num = -3f;
                vector.Y -= 2f * gravdir;
            }
            else if (itemtype == 5117)
            {
                num = -1f;
            }
            else if (itemtype == 96)
            {
                num = -8f;
                vector.Y += 2f * gravdir;
            }
            else if (itemtype == 1870)
            {
                num = -8f;
                vector.Y += 2f * gravdir;
            }
            else if (itemtype == 1260)
            {
                num = -8f;
                vector.Y += 2f * gravdir;
            }
            else if (itemtype == 1254)
            {
                num = -6f;
                vector.Y += 2f * gravdir;
            }
            else if (itemtype == 98)
            {
                num = -5f;
                vector.Y -= 2f * gravdir;
            }
            else if (itemtype == 534)
            {
                num = -2f;
                vector.Y += 1f * gravdir;
            }
            else if (itemtype == 679)
            {
                num = 0f;
                vector.Y += 2f * gravdir;
            }
            else if (itemtype == 964)
            {
                num = 0f;
                vector.Y += 0f * gravdir;
            }
            else if (itemtype == 533)
            {
                num = -7f;
                vector.Y -= 2f * gravdir;
            }
            else if (itemtype == 1553)
            {
                num = -10f;
                vector.Y -= 2f * gravdir;
            }
            else if (itemtype == 506)
            {
                num = 0f;
                vector.Y -= 2f * gravdir;
            }
            else if (itemtype == 1910)
            {
                num = 0f;
                vector.Y -= 2f * gravdir;
            }
            else if (itemtype == 494 || itemtype == 508)
            {
                num = -2f;
            }
            else if (itemtype == 434)
            {
                num = 0f;
                vector.Y -= 2f * gravdir;
            }
            else if (itemtype == 514)
            {
                num = 0f;
                vector.Y += 3f * gravdir;
            }
            else if (itemtype == 435 || itemtype == 436 || itemtype == 481 || itemtype == 578 || itemtype == 1187 || itemtype == 1194 || itemtype == 1201 || itemtype == 1229)
            {
                num = -2f;
                vector.Y -= 2f * gravdir;
            }
            else if (itemtype == 197)
            {
                num = -5f;
                vector.Y += 4f * gravdir;
            }
            else if (itemtype == 4060)
            {
                num = -2f;
                vector.Y += 4f * gravdir;
            }
            else if (itemtype == 126)
            {
                num = 4f;
                vector.Y += 4f * gravdir;
            }
            else if (itemtype == 800)
            {
                num = 4f;
                vector.Y += 2f * gravdir;
            }
            else if (itemtype == 127)
            {
                num = 4f;
                vector.Y += 2f * gravdir;
            }
            else if (itemtype == 157)
            {
                num = 6f;
                vector.Y += 2f * gravdir;
            }
            else if (itemtype == 160)
            {
                num = -8f;
            }
            else if (itemtype == 164 || itemtype == 219)
            {
                num = 0f;
                vector.Y += 2f * gravdir;
            }
            else if (itemtype == 165 || itemtype == 272)
            {
                num = 4f;
                vector.Y += 4f * gravdir;
            }
            else if (itemtype == 3870)
            {
                num = 4f;
                vector.Y += 4f * gravdir;
            }
            else if (itemtype == 266)
            {
                num = 0f;
                vector.Y += 2f * gravdir;
            }
            else if (itemtype == 281)
            {
                num = 6f;
                vector.Y -= 6f * gravdir;
            }
            else if (itemtype == 986)
            {
                num = 6f;
                vector.Y -= 10f * gravdir;
            }
            else if (itemtype == 682)
            {
                num = 4f;
            }
            else if (itemtype == 4953)
            {
                num = -4f;
            }
            else if (itemtype == 758)
            {
                num -= 20f;
                vector.Y += 0f * gravdir;
            }
            else if (itemtype == 759)
            {
                num -= 18f;
                vector.Y += 2f * gravdir;
            }
            else if (itemtype == 5460)
            {
                num -= 10f;
                vector.Y += -6f * gravdir;
            }
            else if (itemtype == 760)
            {
                num -= 12f;
                vector.Y += 2f * gravdir;
            }
            else if (itemtype == 1946)
            {
                num -= 12f;
                vector.Y += 2f * gravdir;
            }
            else if (itemtype == 779)
            {
                num = 0f;
                vector.Y += 2f * gravdir;
            }
            else if (itemtype == 5134)
            {
                num = 0f;
                vector.Y += 2f * gravdir;
            }
            else if (itemtype == 905)
            {
                num = -5f;
                vector.Y += 0f * gravdir;
            }
            else if (itemtype == 930)
            {
                num = 4f;
                vector.Y += 2f * gravdir;
            }
            else if (itemtype == 3788)
            {
                num = 2f;
                vector.Y += 2f * gravdir;
            }
            else if (itemtype == 5668)
            {
                num = -13f;
            }
            vector.X = num;
            return vector;
        }
References Terraria.Main.GetItemDrawFrame().
Referenced by Terraria.Main.DrawNPCExtras(), and Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_27_HeldItem().