Terraria Decompiled: Terraria.Main.MouseText_DrawItemTooltip
MouseText_DrawItemTooltip()
void Terraria.Main.MouseText_DrawItemTooltip (Main::MouseTextCache info, int rare, byte diff, int X, int Y) inline private
Definition at line 19108 of file Main.cs.
        {
            bool settingsEnabled_OpaqueBoxBehindTooltips = Main.SettingsEnabled_OpaqueBoxBehindTooltips;
            new Microsoft.Xna.Framework.Color((int)Main.mouseTextColor, (int)Main.mouseTextColor, (int)Main.mouseTextColor, (int)Main.mouseTextColor);
            Item hoverItem = Main.HoverItem;
            int num = -1;
            int num2 = -1;
            rare = hoverItem.rare;
            if (hoverItem.expert)
            {
                rare = -12;
            }
            float knockBack = hoverItem.knockBack;
            float num3 = 1f;
            if (hoverItem.melee && Main.player[Main.myPlayer].kbGlove)
            {
                num3 += 1f;
            }
            if (Main.player[Main.myPlayer].kbBuff)
            {
                num3 += 0.5f;
            }
            if (num3 != 1f)
            {
                hoverItem.knockBack *= num3;
            }
            if (hoverItem.ranged && Main.player[Main.myPlayer].shroomiteStealth)
            {
                hoverItem.knockBack *= 1f + (1f - Main.player[Main.myPlayer].stealth) * 0.5f;
            }
            int num4 = 1;
            string[] mouseTextTooltipLine_Text = Main._mouseTextTooltipLine_Text;
            Microsoft.Xna.Framework.Color[] mouseTextTooltipLine_Color = Main._mouseTextTooltipLine_Color;
            byte b = Main.mouseTextColor;
            float num5 = (float)Main.mouseTextColor / 255f;
            for (int i = 0; i < mouseTextTooltipLine_Text.Length; i++)
            {
                mouseTextTooltipLine_Color[i] = new Microsoft.Xna.Framework.Color(255, 255, 255);
            }
            mouseTextTooltipLine_Color[0] = Main.MouseText_DrawItemTooltip_GetItemNameColor(rare, diff);
            Main.MouseText_DrawItemTooltip_GetLinesInfo(hoverItem, ref num, ref num2, knockBack, ref num4, mouseTextTooltipLine_Text, mouseTextTooltipLine_Color);
            Main.MouseText_DrawItemTooltip_AddShopLines(hoverItem, ref num4, mouseTextTooltipLine_Text, mouseTextTooltipLine_Color);
            if (NewCraftingUI.Visible)
            {
                NewCraftingUI.AddTooltipLines(hoverItem, ref num4, mouseTextTooltipLine_Text, mouseTextTooltipLine_Color);
            }
            Vector2 zero = Vector2.Zero;
            int num6 = 0;
            for (int j = 0; j < num4; j++)
            {
                Vector2 stringSize = ChatManager.GetStringSize(FontAssets.MouseText.Value, mouseTextTooltipLine_Text[j], Vector2.One, -1f);
                if (stringSize.X > zero.X)
                {
                    zero.X = stringSize.X;
                }
                zero.Y += stringSize.Y + (float)num6;
            }
            X += Main.toolTipDistance;
            Y += Main.toolTipDistance;
            int num7 = 4;
            if (settingsEnabled_OpaqueBoxBehindTooltips)
            {
                X += 8;
                Y += 2;
                num7 = 18;
            }
            int num8 = Main.screenWidth;
            int num9 = Main.screenHeight;
            if ((float)X + zero.X + (float)num7 > (float)num8)
            {
                X = (int)((float)num8 - zero.X - (float)num7);
            }
            if ((float)Y + zero.Y + (float)num7 > (float)num9)
            {
                Y = (int)((float)num9 - zero.Y - (float)num7);
            }
            int num10 = 0;
            if (settingsEnabled_OpaqueBoxBehindTooltips)
            {
                int num11 = 14;
                int num12 = 9;
                Utils.DrawInvBG(Main.spriteBatch, new Microsoft.Xna.Framework.Rectangle(X - num11, Y - num12, (int)zero.X + num11 * 2, (int)zero.Y + num12 + num12 / 2), new Microsoft.Xna.Framework.Color(23, 25, 81, 255) * 0.925f);
            }
            for (int k = 0; k < mouseTextTooltipLine_Text.Length; k++)
            {
                mouseTextTooltipLine_Color[k] = new Microsoft.Xna.Framework.Color((int)((byte)((float)mouseTextTooltipLine_Color[k].R * num5)), (int)((byte)((float)mouseTextTooltipLine_Color[k].G * num5)), (int)((byte)((float)mouseTextTooltipLine_Color[k].B * num5)), (int)Main.mouseTextColor);
            }
            for (int l = 0; l < num4; l++)
            {
                if (l == num)
                {
                    float num13 = 1f;
                    int num14 = (int)((float)Main.mouseTextColor * num13);
                    Microsoft.Xna.Framework.Color black = Microsoft.Xna.Framework.Color.Black;
                    for (int m = 0; m < 5; m++)
                    {
                        int num15 = X;
                        int num16 = Y + num10;
                        if (m == 4)
{
                            black = new Microsoft.Xna.Framework.Color(num14, num14, num14, num14);
                        }
                        if (m == 0)
{
                            num15--;
                        }
                        else if (m == 1)
{
                            num15++;
                        }
                        else if (m == 2)
{
                            num16--;
                        }
                        else if (m == 3)
{
                            num16++;
                        }
                        Main.spriteBatch.Draw(TextureAssets.OneDropLogo.Value, new Vector2((float)num15, (float)num16), null, black, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
                    }
                }
                else
                {
                    Microsoft.Xna.Framework.Color color = mouseTextTooltipLine_Color[l];
                    if (l == num2)
                    {
                        color = Colors.JourneyMode;
                    }
                    ChatManager.DrawColorCodedStringWithShadow(Main.spriteBatch, FontAssets.MouseText.Value, mouseTextTooltipLine_Text[l], new Vector2((float)X, (float)(Y + num10)), color, 0f, Vector2.Zero, Vector2.One, -1f, 2f);
                }
                num10 += (int)(FontAssets.MouseText.Value.MeasureString(mouseTextTooltipLine_Text[l]).Y + (float)num6);
            }
        }
References Terraria.Main._mouseTextTooltipLine_Color, Terraria.Main._mouseTextTooltipLine_Text, Terraria.GameContent.UI.NewCraftingUI.AddTooltipLines(), Microsoft.Xna.Framework.Color.Black, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.Utils.DrawInvBG(), Terraria.Item.expert, Microsoft.Xna.Framework.Input.G, Terraria.UI.Chat.ChatManager.GetStringSize(), Terraria.Main.HoverItem, int, Terraria.ID.Colors.JourneyMode, Terraria.Player.kbBuff, Terraria.Player.kbGlove, Terraria.Item.knockBack, Terraria.Item.melee, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.MouseText_DrawItemTooltip_AddShopLines(), Terraria.Main.MouseText_DrawItemTooltip_GetItemNameColor(), Terraria.Main.MouseText_DrawItemTooltip_GetLinesInfo(), Terraria.Main.mouseTextColor, Terraria.Main.myPlayer, Microsoft.Xna.Framework.Vector2.One, Terraria.GameContent.TextureAssets.OneDropLogo, Terraria.Main.player, Terraria.Item.ranged, Terraria.Item.rare, Terraria.Main.screenHeight, Terraria.Main.screenWidth, Terraria.Main.SettingsEnabled_OpaqueBoxBehindTooltips, Terraria.Player.shroomiteStealth, Terraria.Main.spriteBatch, Terraria.Player.stealth, Terraria.Main.toolTipDistance, ReLogic.Content.Asset< T >.Value, Terraria.GameContent.UI.NewCraftingUI.Visible, Microsoft.Xna.Framework.Input.X, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Input.Y, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.