Terraria Decompiled: Terraria.Main.DryadText_Do_StardewValleyBit
DryadText_Do_StardewValleyBit()
static void Terraria.Main.DryadText_Do_StardewValleyBit () inline static
Definition at line 40044 of file Main.cs.
        {
            NPC.PreventJojaColaDialog = true;
            NPC.RerollDryadText = 2;
            Main.LocalPlayer.ConsumeItem(5275, true, false);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(144, -1, -1, null, 0, 0f, 0f, 0f, 0, 0, 0);
            }
            else
            {
                NPC.HaveDryadDoStardewAnimation();
            }
            Main.npcChatText = Language.GetTextValue("StardewTalk.PlayerGivesCola");
            AchievementsHelper.NotifyProgressionEvent(46);
        }
References Terraria.Player.ConsumeItem(), Terraria.Localization.Language.GetTextValue(), Terraria.NPC.HaveDryadDoStardewAnimation(), Terraria.Main.LocalPlayer, Terraria.Main.netMode, Terraria.GameContent.Achievements.AchievementsHelper.NotifyProgressionEvent(), and Terraria.NetMessage.SendData().
Referenced by Terraria.Main.DryadText_WorldPurityOrStardewValleyBit(), and Terraria.GameContent.NPCInteractions.Actions.StardewValleyBit.Interact().