Terraria Decompiled: Terraria.Main.DrawWOFBody
DrawWOFBody()
static void Terraria.Main.DrawWOFBody () inline static private
Definition at line 37834 of file Main.cs.
        {
            int num = TextureAssets.Wof.Height() / 3;
            float num2 = (float)Main.wofDrawAreaTop;
            float num3 = (float)Main.wofDrawAreaBottom;
            num3 = Main.screenPosition.Y + (float)Main.screenHeight;
            float num4 = (float)((int)((num2 - Main.screenPosition.Y) / (float)num) + 1);
            if (num4 > 12f)
            {
                return;
            }
            float num5 = num4 * (float)num;
            if (num5 > 0f)
            {
                num2 -= num5;
            }
            float num6 = Main.npc[Main.wofNPCIndex].position.X;
            if (Main.npc[Main.wofNPCIndex].direction > 0)
            {
                num6 -= 80f;
            }
            SpriteEffects spriteEffects = SpriteEffects.None;
            if (Main.npc[Main.wofNPCIndex].spriteDirection == 1)
            {
                spriteEffects = SpriteEffects.FlipHorizontally;
            }
            int num7 = Main.wofDrawFrameIndex / 6 * num;
            if (!Main.gamePaused && ++Main.wofDrawFrameIndex >= 18)
            {
                Main.wofDrawFrameIndex = 0;
            }
            float num8 = num3 - num2;
            int num9 = (int)num2;
            while ((float)num9 < num3)
            {
                num8 = num3 - (float)num9;
                if (num8 > (float)num)
                {
                    num8 = (float)num;
                }
                int num10 = 0;
                while ((float)num10 < num8)
                {
                    int num11 = (int)(num6 + (float)(TextureAssets.Wof.Width() / 2)) / 16;
                    int num12 = (num9 + num10) / 16;
                    Main.spriteBatch.Draw(TextureAssets.Wof.Value, new Vector2(num6 - Main.screenPosition.X, (float)(num9 + num10) - Main.screenPosition.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, num7 + num10, TextureAssets.Wof.Width(), 16)), Lighting.GetColor(num11, num12), 0f, default(Vector2), 1f, spriteEffects, 0f);
                    num10 += 16;
                }
                num9 += num;
            }
        }
References Terraria.Entity.direction, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Main.gamePaused, Terraria.Lighting.GetColor(), int, Terraria.Main.npc, Terraria.Entity.position, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.spriteBatch, Terraria.NPC.spriteDirection, ReLogic.Content.Asset< T >.Value, Terraria.GameContent.TextureAssets.Wof, Terraria.Main.wofDrawAreaBottom, Terraria.Main.wofDrawAreaTop, Terraria.Main.wofDrawFrameIndex, Terraria.Main.wofNPCIndex, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Main.DrawWoF().