Terraria Decompiled: Terraria.Main.MouseText_DrawItemTooltip_AddShopLines
MouseText_DrawItemTooltip_AddShopLines()
static void Terraria.Main.MouseText_DrawItemTooltip_AddShopLines (Item hoverItem, ref int numLines, string[] lineText, Microsoft::Xna::Framework::Color[] lineColors) inline static private
Definition at line 19243 of file Main.cs.
        {
            if (Main.npcShop > 0 && hoverItem.value >= 0 && (hoverItem.type < 71 || hoverItem.type > 74))
            {
                long num;
                long num2;
                Main.LocalPlayer.GetItemExpectedPrice(hoverItem, out num, out num2);
                long num3;
                if (!hoverItem.isAShopItem && !hoverItem.buyOnce)
                {
                    num3 = num;
                }
                else
                {
                    num3 = num2;
                }
                if (hoverItem.shopSpecialCurrency != -1)
                {
                    long num4 = num3 * (long)ItemSlot.EstimateDisplayStack(hoverItem);
                    CustomCurrencyManager.GetPriceText(hoverItem.shopSpecialCurrency, lineText, ref numLines, num4);
                    lineColors[numLines - 1] = new Microsoft.Xna.Framework.Color(255, 255, 255);
                    return;
                }
                if (num3 > 0L)
                {
                    string text = "";
                    long num5 = 0L;
                    long num6 = 0L;
                    long num7 = 0L;
                    long num8 = 0L;
                    long num9 = num3 * (long)ItemSlot.EstimateDisplayStack(hoverItem);
                    if (!hoverItem.buy)
                    {
                        num9 = num3 / 5L;
                        if (num9 < 1L)
{
                            num9 = 1L;
                        }
                        long num10 = num9;
                        num9 *= (long)hoverItem.stack;
                        int amount = Main.shopSellbackHelper.GetAmount(hoverItem);
                        if (amount > 0)
{
                            num9 += (-num10 + num2) * (long)Math.Min(amount, hoverItem.stack);
                        }
                    }
                    if (num9 < 1L)
                    {
                        num9 = 1L;
                    }
                    if (num9 >= 1000000L)
                    {
                        num5 = num9 / 1000000L;
                        num9 -= num5 * 1000000L;
                    }
                    if (num9 >= 10000L)
                    {
                        num6 = num9 / 10000L;
                        num9 -= num6 * 10000L;
                    }
                    if (num9 >= 100L)
                    {
                        num7 = num9 / 100L;
                        num9 -= num7 * 100L;
                    }
                    if (num9 >= 1L)
                    {
                        num8 = num9;
                    }
                    if (num5 > 0L)
                    {
                        text = string.Concat(new object[]
{
                            text,
                            num5,
                            " ",
                            Lang.inter[15].Value,
                            " "
                        });
                    }
                    if (num6 > 0L)
                    {
                        text = string.Concat(new object[]
{
                            text,
                            num6,
                            " ",
                            Lang.inter[16].Value,
                            " "
                        });
                    }
                    if (num7 > 0L)
                    {
                        text = string.Concat(new object[]
{
                            text,
                            num7,
                            " ",
                            Lang.inter[17].Value,
                            " "
                        });
                    }
                    if (num8 > 0L)
                    {
                        text = string.Concat(new object[]
{
                            text,
                            num8,
                            " ",
                            Lang.inter[18].Value,
                            " "
                        });
                    }
                    if (!hoverItem.buy)
                    {
                        lineText[numLines] = Lang.tip[49].Value + " " + text;
                    }
                    else
                    {
                        lineText[numLines] = Lang.tip[50].Value + " " + text;
                    }
                    if (num5 > 0L)
                    {
                        lineColors[numLines] = new Microsoft.Xna.Framework.Color(220, 220, 198);
                    }
                    else if (num6 > 0L)
                    {
                        lineColors[numLines] = new Microsoft.Xna.Framework.Color(224, 201, 92);
                    }
                    else if (num7 > 0L)
                    {
                        lineColors[numLines] = new Microsoft.Xna.Framework.Color(181, 192, 193);
                    }
                    else if (num8 > 0L)
                    {
                        lineColors[numLines] = new Microsoft.Xna.Framework.Color(246, 138, 96);
                    }
                    numLines++;
                    return;
                }
                if (hoverItem.type != 3817)
                {
                    lineText[numLines] = Lang.tip[51].Value;
                    lineColors[numLines] = new Microsoft.Xna.Framework.Color(120, 120, 120);
                    numLines++;
                }
            }
        }
References Terraria.Item.buy, Terraria.Item.buyOnce, Terraria.UI.ItemSlot.EstimateDisplayStack(), Terraria.GameContent.ItemShopSellbackHelper.GetAmount(), Terraria.Player.GetItemExpectedPrice(), Terraria.GameContent.UI.CustomCurrencyManager.GetPriceText(), Terraria.Lang.inter, Terraria.Item.isAShopItem, Microsoft.Xna.Framework.Input.L, Terraria.Main.LocalPlayer, long, System.Math.Min(), Terraria.Main.npcShop, Terraria.Main.shopSellbackHelper, Terraria.Item.shopSpecialCurrency, Terraria.Item.stack, System.text, Terraria.Lang.tip, Terraria.Item.type, Terraria.Item.value, and Terraria.Localization.LocalizedText.Value.
Referenced by Terraria.Main.MouseText_DrawItemTooltip().