Terraria Decompiled: Terraria.Main.StartInvasion
StartInvasion()
static void Terraria.Main.StartInvasion (int type = 1) inline static
Definition at line 65679 of file Main.cs.
        {
            if (Main.invasionType != 0 && Main.invasionSize == 0)
            {
                Main.invasionType = 0;
            }
            if (Main.invasionType == 0)
            {
                int num = 0;
                for (int i = 0; i < 255; i++)
                {
                    if (Main.player[i].active && Main.player[i].statLifeMax >= 200)
                    {
                        num++;
                    }
                }
                if (num > 0)
                {
                    Main.invasionType = type;
                    Main.invasionSize = 80 + 40 * num;
                    if (type == 3)
                    {
                        Main.invasionSize += 40 + 20 * num;
                    }
                    if (type == 4)
                    {
                        Main.invasionSize = 160 + 40 * num;
                    }
                    Main.invasionSizeStart = Main.invasionSize;
                    Main.invasionProgress = 0;
                    Main.invasionProgressIcon = type + 3;
                    Main.invasionProgressWave = 0;
                    Main.invasionProgressMax = Main.invasionSizeStart;
                    Main.invasionWarn = 0;
                    if (type == 4)
                    {
                        Main.invasionX = (double)(Main.spawnTileX - 1);
                        Main.invasionWarn = 2;
                    }
                    else if (Main.rand.Next(2) == 0)
                    {
                        Main.invasionX = 0.0;
                    }
                    else
                    {
                        Main.invasionX = (double)Main.maxTilesX;
                    }
                    NPCDamageTracker.Start(new InvasionDamageTracker(Main.invasionType, null));
                }
            }
        }
References Terraria.Player.active, Terraria.Main.invasionSize, Terraria.Main.invasionSizeStart, Terraria.Main.invasionType, Terraria.Main.maxTilesX, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.player, Terraria.Main.rand, Terraria.Main.spawnTileX, Terraria.GameContent.NPCDamageTracker.Start(), and Terraria.Player.statLifeMax.
Referenced by Terraria.NPC.AI(), Terraria.Player.ItemCheck_UseEventItems(), and Terraria.Main.UpdateTime_StartDay().