Terraria Decompiled: Terraria.Main.DrawSunAndMoon
DrawSunAndMoon()
void Terraria.Main.DrawSunAndMoon (Main::SceneArea sceneArea, Microsoft::Xna::Framework::Color moonColor, Microsoft::Xna::Framework::Color sunColor, float tempMushroomInfluence) inline private
Definition at line 63869 of file Main.cs.
        {
            Texture2D texture2D = TextureAssets.Sun.Value;
            int num = Main.moonType;
            if (!TextureAssets.Moon.IndexInRange(num))
            {
                num = Utils.Clamp<int>(num, 0, 8);
            }
            Texture2D value = TextureAssets.Moon[num].Value;
            int num2 = sceneArea.bgTopY;
            int num3 = (int)(Main.time / 54000.0 * (double)(sceneArea.totalWidth + (float)(texture2D.Width * 2))) - texture2D.Width;
            int num4 = 0;
            float num5 = 1f;
            float num6 = (float)(Main.time / 54000.0) * 2f - 7.3f;
            int num7 = (int)(Main.time / 32400.0 * (double)(sceneArea.totalWidth + (float)(value.Width * 2))) - value.Width;
            int num8 = 0;
            float num9 = 1f;
            float num10 = (float)(Main.time / 32400.0) * 2f - 7.3f;
            if (Main.dayTime)
            {
                double num11 = Math.Pow(Math.Abs(Main.time / 54000.0 * 2.0 - 1.0), 2.0);
                num4 = (int)((double)num2 + num11 * 250.0 + 180.0);
                num5 = (float)(1.2 - num11 * 0.4);
            }
            else
            {
                double num12 = Math.Pow(Math.Abs(Main.time / 32400.0 * 2.0 - 1.0), 2.0);
                num8 = (int)((double)num2 + num12 * 250.0 + 180.0);
                num9 = (float)(1.2 - num12 * 0.4);
            }
            if (Main.starGame)
            {
                if (WorldGen.generatingWorld)
                {
                    Main.alreadyGrabbingSunOrMoon = true;
                    if (Main.rand.Next(60) == 0)
                    {
                        for (int i = 0; i < Main.numStars; i++)
{
                            if (Main.star[i].hidden)
{
                                Star.SpawnStars(i);
                            }
                        }
                    }
                    if (Main.dayTime)
                    {
                        Main.dayTime = false;
                        Main.time = 0.0;
                    }
                }
                else
                {
                    Main.starGame = false;
                }
            }
            else
            {
                Main.starsHit = 0;
            }
            if (Main.dayTime)
            {
                if ((Main.remixWorld && !Main.gameMenu) || WorldGen.remixWorldGen)
                {
                    return;
                }
                num5 *= 1.1f;
                float num13 = 1f - tempMushroomInfluence;
                num13 -= Main.cloudAlpha * 1.5f * Main.atmo;
                if (num13 < 0f)
                {
                    num13 = 0f;
                }
                Microsoft.Xna.Framework.Color white = new Microsoft.Xna.Framework.Color((int)((byte)(255f * num13)), (int)((byte)((float)sunColor.G * num13)), (int)((byte)((float)sunColor.B * num13)), (int)((byte)(255f * num13)));
                Microsoft.Xna.Framework.Color color = new Microsoft.Xna.Framework.Color((int)((byte)((float)sunColor.R * num13)), (int)((byte)((float)sunColor.G * num13)), (int)((byte)((float)sunColor.B * num13)), (int)((byte)((float)sunColor.B * num13)));
                if (!Main.eclipse)
                {
                    white = Microsoft.Xna.Framework.Color.White;
                }
                bool flag = false;
                bool flag2 = false;
                if (Main.eclipse)
                {
                    texture2D = TextureAssets.Sun3.Value;
                    flag = true;
                }
                else if (!Main.gameMenu && Main.player[Main.myPlayer].head == 12)
                {
                    texture2D = TextureAssets.Sun2.Value;
                    flag2 = true;
                    flag = true;
                }
                if (flag)
                {
                    color = new Microsoft.Xna.Framework.Color((int)((byte)((float)sunColor.R * num13)), (int)((byte)((float)sunColor.G * num13)), (int)((byte)((float)sunColor.B * num13)), (int)((byte)((float)(sunColor.B - 60) * num13)));
                }
                Vector2 vector = texture2D.Size() / 2f;
                Vector2 vector2 = new Vector2((float)num3, (float)(num4 + (int)Main.sunModY));
                Main.spriteBatch.Draw(texture2D, vector2, null, white, num6, vector, num5, SpriteEffects.None, 0f);
                Main.spriteBatch.Draw(texture2D, vector2, null, color, num6, vector, num5, SpriteEffects.None, 0f);
                this.HorizonRenderer.DrawSun(vector2);
                if (flag2)
                {
                    Texture2D value2 = TextureAssets.Extra[280].Value;
                    Microsoft.Xna.Framework.Color color2 = new Microsoft.Xna.Framework.Color((int)white.R, (int)white.G, (int)white.B, 100);
                    Main.spriteBatch.Draw(value2, vector2, null, color2, num6, vector, num5, SpriteEffects.None, 0f);
                }
            }
            if (!Main.dayTime)
            {
                float num14 = 1f - Main.cloudAlpha * 1.5f * Main.atmo;
                if (num14 < 0f)
                {
                    num14 = 0f;
                }
                moonColor *= num14;
                Vector2 vector3 = new Vector2((float)num7, (float)(num8 + (int)Main.moonModY));
                if (WorldGen.drunkWorldGen)
                {
                    Main.spriteBatch.Draw(TextureAssets.SmileyMoon.Value, vector3, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.SmileyMoon.Width(), TextureAssets.SmileyMoon.Height())), moonColor, num10 / 2f + 3.1415927f, new Vector2((float)(TextureAssets.SmileyMoon.Width() / 2), (float)(TextureAssets.SmileyMoon.Height() / 2)), num9, SpriteEffects.None, 0f);
                }
                else if (Main.pumpkinMoon)
                {
                    Main.spriteBatch.Draw(TextureAssets.PumpkinMoon.Value, vector3, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, TextureAssets.PumpkinMoon.Width() * Main.moonPhase, TextureAssets.PumpkinMoon.Width(), TextureAssets.PumpkinMoon.Width())), moonColor, num10, new Vector2((float)(TextureAssets.PumpkinMoon.Width() / 2), (float)(TextureAssets.PumpkinMoon.Width() / 2)), num9, SpriteEffects.None, 0f);
                }
                else if (Main.snowMoon)
                {
                    Main.spriteBatch.Draw(TextureAssets.SnowMoon.Value, vector3, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, TextureAssets.SnowMoon.Width() * Main.moonPhase, TextureAssets.SnowMoon.Width(), TextureAssets.SnowMoon.Width())), moonColor, num10, new Vector2((float)(TextureAssets.SnowMoon.Width() / 2), (float)(TextureAssets.SnowMoon.Width() / 2)), num9, SpriteEffects.None, 0f);
                }
                else
                {
                    Main.spriteBatch.Draw(TextureAssets.Moon[num].Value, vector3, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, TextureAssets.Moon[num].Width() * Main.moonPhase, TextureAssets.Moon[num].Width(), TextureAssets.Moon[num].Width())), moonColor, num10, new Vector2((float)(TextureAssets.Moon[num].Width() / 2), (float)(TextureAssets.Moon[num].Width() / 2)), num9, SpriteEffects.None, 0f);
                }
            }
            Microsoft.Xna.Framework.Rectangle rectangle;
            if (Main.dayTime)
            {
                rectangle = new Microsoft.Xna.Framework.Rectangle((int)((double)num3 - (double)TextureAssets.Sun.Width() * 0.5 * (double)num5), (int)((double)num4 - (double)TextureAssets.Sun.Height() * 0.5 * (double)num5 + (double)Main.sunModY), (int)((float)TextureAssets.Sun.Width() * num5), (int)((float)TextureAssets.Sun.Width() * num5));
            }
            else
            {
                rectangle = new Microsoft.Xna.Framework.Rectangle((int)((double)num7 - (double)TextureAssets.Moon[num].Width() * 0.5 * (double)num9), (int)((double)num8 - (double)TextureAssets.Moon[num].Width() * 0.5 * (double)num9 + (double)Main.moonModY), (int)((float)TextureAssets.Moon[num].Width() * num9), (int)((float)TextureAssets.Moon[num].Width() * num9));
            }
            Microsoft.Xna.Framework.Rectangle rectangle2 = new Microsoft.Xna.Framework.Rectangle(Main.mouseX, Main.mouseY, 1, 1);
            Main.sunModY = (short)((double)Main.sunModY * 0.999);
            Main.moonModY = (short)((double)Main.moonModY * 0.999);
            if (Main.gameMenu && Main.netMode != 1)
            {
                if (rectangle2.Intersects(rectangle) || Main.alreadyGrabbingSunOrMoon)
                {
                    Main.player[Main.myPlayer].mouseInterface = true;
                }
                if ((Main.mouseLeft || Main.starGame) && FocusHelper.AllowUIInputs)
                {
                    if (rectangle2.Intersects(rectangle) || Main.alreadyGrabbingSunOrMoon)
                    {
                        if (Main.dayTime)
{
                            Main.time = 54000.0 * (double)((float)(Main.mouseX + TextureAssets.Sun.Width()) / ((float)Main.screenWidth + (float)(TextureAssets.Sun.Width() * 2)));
                            Main.sunModY = (short)(Main.mouseY - num4);
                            if (Main.time > 53990.0)
{
                                Main.time = 53990.0;
                            }
                        }
                        else
{
                            Main.time = 32400.0 * (double)((float)(Main.mouseX + TextureAssets.Moon[num].Width()) / ((float)Main.screenWidth + (float)(TextureAssets.Moon[num].Width() * 2)));
                            Main.moonModY = (short)(Main.mouseY - num8);
                            if (Main.time > 32390.0)
{
                                Main.time = 32390.0;
                            }
                        }
                        if (Main.time < 10.0)
{
                            Main.time = 10.0;
                        }
                        Main.alreadyGrabbingSunOrMoon = true;
                        AchievementsHelper.DoClassicTitleScreenAchievement();
                    }
                }
                else
                {
                    Main.alreadyGrabbingSunOrMoon = false;
                }
            }
            Main.LastCelestialBodyPosition = (Main.dayTime ? new Vector2((float)num3, (float)(num4 + (int)Main.sunModY)) : new Vector2((float)num7, (float)(num8 + (int)Main.moonModY)));
            Main.LastCelestialBodyPosition /= Main.ScreenSize.ToVector2();
        }
References System.Math.Abs(), Terraria.FocusHelper.AllowUIInputs, Terraria.Main.alreadyGrabbingSunOrMoon, Terraria.Main.atmo, Microsoft.Xna.Framework.Color.B, Terraria.Main.SceneArea.bgTopY, Terraria.Utils.Clamp(), Terraria.Main.dayTime, Terraria.GameContent.Achievements.AchievementsHelper.DoClassicTitleScreenAchievement(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.WorldGen.drunkWorldGen, Terraria.Main.eclipse, Terraria.GameContent.TextureAssets.Extra, Microsoft.Xna.Framework.Color.G, Terraria.Main.gameMenu, Terraria.WorldGen.generatingWorld, Terraria.Player.head, Terraria.Star.hidden, int, Microsoft.Xna.Framework.Rectangle.Intersects(), Terraria.GameContent.TextureAssets.Moon, Terraria.Main.moonModY, Terraria.Main.moonPhase, Terraria.Main.moonType, Terraria.Player.mouseInterface, Terraria.Main.mouseLeft, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.numStars, Terraria.Main.player, System.Math.Pow(), Terraria.GameContent.TextureAssets.PumpkinMoon, Terraria.Main.pumpkinMoon, Microsoft.Xna.Framework.Color.R, Terraria.Main.rand, Terraria.Main.remixWorld, Terraria.WorldGen.remixWorldGen, Terraria.Main.ScreenSize, Terraria.GameContent.TextureAssets.SmileyMoon, Terraria.GameContent.TextureAssets.SnowMoon, Terraria.Main.snowMoon, Terraria.Star.SpawnStars(), Terraria.Main.spriteBatch, Terraria.Main.star, Terraria.Main.starGame, Terraria.GameContent.TextureAssets.Sun, Terraria.GameContent.TextureAssets.Sun2, Terraria.GameContent.TextureAssets.Sun3, Terraria.Main.sunModY, Terraria.Main.time, System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Color.White, and Microsoft.Xna.Framework.Graphics.Texture2D.Width.