Terraria Decompiled: Terraria.Main.NPCChatText_DoTaxCollector
NPCChatText_DoTaxCollector()
static void Terraria.Main.NPCChatText_DoTaxCollector () inline static
Definition at line 39922 of file Main.cs.
        {
            if (Main.player[Main.myPlayer].taxMoney > 0)
            {
                int i = Main.player[Main.myPlayer].taxMoney;
                i = (int)((float)i / Main.player[Main.myPlayer].currentShoppingSettings.PriceAdjustment);
                while (i > 0)
                {
                    EntitySource_Gift entitySource_Gift = new EntitySource_Gift(Main.npc[Main.player[Main.myPlayer].talkNPC]);
                    if (i > 1000000)
                    {
                        int num = i / 1000000;
                        i -= 1000000 * num;
                        int num2 = Item.NewItem(entitySource_Gift, (int)Main.player[Main.myPlayer].position.X, (int)Main.player[Main.myPlayer].position.Y, Main.player[Main.myPlayer].width, Main.player[Main.myPlayer].height, 74, num, false, 0, false);
                        if (Main.netMode == 1)
{
                            NetMessage.SendData(21, -1, -1, null, num2, 1f, 0f, 0f, 0, 0, 0);
                        }
                    }
                    else if (i > 10000)
                    {
                        int num3 = i / 10000;
                        i -= 10000 * num3;
                        int num4 = Item.NewItem(entitySource_Gift, (int)Main.player[Main.myPlayer].position.X, (int)Main.player[Main.myPlayer].position.Y, Main.player[Main.myPlayer].width, Main.player[Main.myPlayer].height, 73, num3, false, 0, false);
                        if (Main.netMode == 1)
{
                            NetMessage.SendData(21, -1, -1, null, num4, 1f, 0f, 0f, 0, 0, 0);
                        }
                    }
                    else if (i > 100)
                    {
                        int num5 = i / 100;
                        i -= 100 * num5;
                        int num6 = Item.NewItem(entitySource_Gift, (int)Main.player[Main.myPlayer].position.X, (int)Main.player[Main.myPlayer].position.Y, Main.player[Main.myPlayer].width, Main.player[Main.myPlayer].height, 72, num5, false, 0, false);
                        if (Main.netMode == 1)
{
                            NetMessage.SendData(21, -1, -1, null, num6, 1f, 0f, 0f, 0, 0, 0);
                        }
                    }
                    else
                    {
                        int num7 = i;
                        if (num7 < 1)
{
                            num7 = 1;
                        }
                        i -= num7;
                        int num8 = Item.NewItem(entitySource_Gift, (int)Main.player[Main.myPlayer].position.X, (int)Main.player[Main.myPlayer].position.Y, Main.player[Main.myPlayer].width, Main.player[Main.myPlayer].height, 71, num7, false, 0, false);
                        if (Main.netMode == 1)
{
                            NetMessage.SendData(21, -1, -1, null, num8, 1f, 0f, 0f, 0, 0, 0);
                        }
                    }
                }
                Main.npcChatText = Lang.dialog(Main.rand.Next(380, 384), false);
                Main.player[Main.myPlayer].taxMoney = 0;
            }
            else
            {
                Main.npcChatText = Lang.dialog(Main.rand.Next(390, 401), false);
            }
            Main.DoNPCPortraitHop();
        }
References Terraria.Player.currentShoppingSettings, Terraria.Lang.dialog(), Terraria.Main.DoNPCPortraitHop(), Terraria.Entity.height, int, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.npc, Terraria.Main.player, Terraria.Entity.position, Terraria.ShoppingSettings.PriceAdjustment, Terraria.Main.rand, Terraria.NetMessage.SendData(), Terraria.Player.talkNPC, Terraria.Player.taxMoney, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.GameContent.NPCInteractions.Actions.TaxCollectorCollectTaxes.Interact().