Terraria Decompiled: Terraria.Main.DrawProjDirect
DrawProjDirect()
void Terraria.Main.DrawProjDirect (Projectile proj, Player overridePlayer = null) inline
Definition at line 27120 of file Main.cs.
        {
            this.PrepareDrawnProjectileDrawing(proj);
            Player player = Main.player[proj.owner];
            if (overridePlayer != null)
            {
                player = overridePlayer;
            }
            if (proj.type == 734)
            {
                VoidLensHelper voidLensHelper = new VoidLensHelper(proj);
                this._voidLensData.Clear();
                int num = Main.TryInteractingWithVoidLens(proj);
                voidLensHelper.DrawToDrawData(this._voidLensData, num);
                foreach (DrawData drawData in this._voidLensData)
                {
                    Main.EntitySpriteDraw(drawData);
                }
                return;
            }
            float num2 = 0f;
            float num3 = 0f;
            this.LoadProjectile(proj.type);
            Vector2 vector = player.MountedCenter;
            if (player.mount.Active && player.mount.Type == 52)
            {
                vector += new Vector2((float)(player.direction * 14), -10f);
            }
            if (proj.aiStyle == 99 && proj.ai[0] != -2f)
            {
                Vector2 vector2 = vector;
                vector2.Y += player.gfxOffY;
                player.ApplyItemPositionOffsetFromMount(ref vector2);
                float num4 = proj.Center.X - vector2.X;
                float num5 = proj.Center.Y - vector2.Y;
                Math.Sqrt((double)(num4 * num4 + num5 * num5));
                float num6 = (float)Math.Atan2((double)num5, (double)num4) - 1.57f;
                bool flag = true;
                bool flag2 = true;
                if (num4 == 0f && num5 == 0f)
                {
                    flag = false;
                }
                else
                {
                    float num7 = (float)Math.Sqrt((double)(num4 * num4 + num5 * num5));
                    num7 = 12f / num7;
                    num4 *= num7;
                    num5 *= num7;
                    vector2.X -= num4 * 0.1f;
                    vector2.Y -= num5 * 0.1f;
                    num4 = proj.position.X + (float)proj.width * 0.5f - vector2.X;
                    num5 = proj.position.Y + (float)proj.height * 0.5f - vector2.Y;
                }
                while (flag)
                {
                    float num8 = 12f;
                    float num9 = (float)Math.Sqrt((double)(num4 * num4 + num5 * num5));
                    float num10 = num9;
                    if (float.IsNaN(num9) || float.IsNaN(num10))
                    {
                        flag = false;
                    }
                    else
                    {
                        if (num9 < 20f)
{
                            num8 = num9 - 8f;
                            flag = false;
                        }
                        num9 = 12f / num9;
                        num4 *= num9;
                        num5 *= num9;
                        if (flag2)
{
                            flag2 = false;
                        }
                        else
{
                            vector2.X += num4;
                            vector2.Y += num5;
                        }
                        num4 = proj.position.X + (float)proj.width * 0.5f - vector2.X;
                        num5 = proj.position.Y + (float)proj.height * 0.1f - vector2.Y;
                        if (num10 > 12f)
{
                            float num11 = 0.3f;
                            float num12 = Math.Abs(proj.velocity.X) + Math.Abs(proj.velocity.Y);
                            if (num12 > 16f)
{
                                num12 = 16f;
                            }
                            num12 = 1f - num12 / 16f;
                            num11 *= num12;
                            num12 = num10 / 80f;
                            if (num12 > 1f)
{
                                num12 = 1f;
                            }
                            num11 *= num12;
                            if (num11 < 0f)
{
                                num11 = 0f;
                            }
                            num11 *= num12;
                            num11 *= 0.5f;
                            if (num5 > 0f)
{
                                num5 *= 1f + num11;
                                num4 *= 1f - num11;
                            }
                            else
{
                                num12 = Math.Abs(proj.velocity.X) / 3f;
                                if (num12 > 1f)
{
                                    num12 = 1f;
                                }
                                num12 -= 0.5f;
                                num11 *= num12;
                                if (num11 > 0f)
{
                                    num11 *= 2f;
                                }
                                num5 *= 1f + num11;
                                num4 *= 1f - num11;
                            }
                        }
                        num6 = (float)Math.Atan2((double)num5, (double)num4) - 1.57f;
                        Microsoft.Xna.Framework.Color color = Microsoft.Xna.Framework.Color.White;
                        color.A = (byte)((float)color.A * 0.4f);
                        color = Main.TryApplyingPlayerStringColor(player.stringColor, color);
                        float num13 = 0.5f;
                        if (player.stringColor != 29)
{
                            color = Lighting.GetColor((int)vector2.X / 16, (int)(vector2.Y / 16f), color);
                        }
                        color = new Microsoft.Xna.Framework.Color((int)((byte)((float)color.R * num13)), (int)((byte)((float)color.G * num13)), (int)((byte)((float)color.B * num13)), (int)((byte)((float)color.A * num13)));
                        Main.EntitySpriteDraw(TextureAssets.FishingLine.Value, new Vector2(vector2.X - Main.screenPosition.X + (float)TextureAssets.FishingLine.Width() * 0.5f, vector2.Y - Main.screenPosition.Y + (float)TextureAssets.FishingLine.Height() * 0.5f) - new Vector2(6f, 0f), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.FishingLine.Width(), (int)num8)), color, num6, new Vector2((float)TextureAssets.FishingLine.Width() * 0.5f, 0f), 1f, SpriteEffects.None, 0f);
                    }
                }
                if (proj.ai[0] == -3f)
                {
                    return;
                }
            }
            else
            {
                if (proj.aiStyle == 160)
                {
                    Main.DrawKite(proj, Main.GetPlayerArmPosition(proj, player) + Main.player[proj.owner].netOffset);
                    return;
                }
                if (proj.aiStyle == 165)
                {
                    this.DrawWhip(proj, player);
                    return;
                }
            }
            if (proj.aiStyle == 174)
            {
                this.DrawMultisegmentPet(proj);
                return;
            }
            if (proj.type == 1020)
            {
                this.DrawContinuousTrail(proj);
            }
            else if (proj.type == 1091)
            {
                Vector2 vector3 = proj.Center - Main.screenPosition;
                Texture2D value = TextureAssets.Projectile[proj.type].Value;
                Vector2 vector4 = value.Frame(1, 1, 0, 0, 0, 0).Size() / 2f;
                int num14 = 240;
                if (num14 == 0)
                {
                    num14 = 1;
                }
                float num15 = Utils.Remap(proj.ai[1], 0f, (float)num14, 0f, 1f, true);
                float num16 = Utils.Remap(num15, 0f, 0.25f, 0f, 1f, true);
                float num17 = (float)Math.Sin((double)(num16 * 1.5707964f)) * 0.6f;
                Microsoft.Xna.Framework.Color color2 = proj.AI_203_GetLightningColor();
                Microsoft.Xna.Framework.Color color3 = new Microsoft.Xna.Framework.Color((int)color2.R, (int)color2.G, (int)color2.B, 0) * num17;
                Microsoft.Xna.Framework.Color color4 = new Microsoft.Xna.Framework.Color(255, 255, 255, 0) * num17;
                float num18 = Utils.Remap(num16, 0f, 0.7f, 0f, 1f, true);
                num18 *= num18;
                num18 *= Utils.Remap(num15, 0.7f, 1f, 0.7f, 1f, true);
                num18 *= Utils.Remap(num15, 0.6f, 0.8f, 1f, 0.7f, true);
                num18 *= Utils.Remap(num15, 0.8f, 1f, 1f, 2f, true);
                num18 *= 0.75f;
                float num19 = (1f - num15 * num15 * 20f) * Utils.Remap(num15, 0f, 0.035f, 0f, 1f, true);
                if (num19 > 0f)
                {
                    float num20 = 1.3f;
                    Main.spriteBatch.Draw(value, vector3, null, Microsoft.Xna.Framework.Color.Black * num19, proj.rotation, vector4, num20, SpriteEffects.None, 0f);
                    Main.spriteBatch.Draw(value, vector3, null, Microsoft.Xna.Framework.Color.Black * num19, proj.rotation + 1.5707964f, vector4, num20 * 0.7f, SpriteEffects.None, 0f);
                    float num21 = num20 * 0.65f;
                    Main.spriteBatch.Draw(value, vector3, null, color2 * num19 * 0.6f, proj.rotation, vector4, num21, SpriteEffects.None, 0f);
                    Main.spriteBatch.Draw(value, vector3, null, color2 * num19 * 0.6f, proj.rotation + 1.5707964f, vector4, num21 * 0.7f, SpriteEffects.None, 0f);
                }
                Main.spriteBatch.Draw(value, vector3, null, color3, proj.rotation, vector4, num18 + (float)Math.Sin((double)(6.2831855f * num15 * 8f)) * 0.09f, SpriteEffects.None, 0f);
                Main.spriteBatch.Draw(value, vector3, null, color4, proj.rotation, vector4, num18 * 0.7f + (float)Math.Sin((double)(6.2831855f * num15 * 24f)) * 0.09f, SpriteEffects.None, 0f);
                return;
            }
            if (proj.type == 1024)
            {
                Main.DrawTrail(proj, Vector2.Zero, new Microsoft.Xna.Framework.Color(140, 234, 180));
            }
            if (proj.type == 1026)
            {
                Main.DrawTrail(proj, Vector2.Zero, new Microsoft.Xna.Framework.Color(140, 234, 180));
            }
            bool flag3 = true;
            int num22 = proj.type;
            if (num22 <= 974)
            {
                if (num22 == 919)
                {
                    this.DrawProj_FairyQueenLance(proj);
                    goto IL_0AE3;
                }
                if (num22 == 932)
                {
                    this.DrawProj_FairyQueenRangedItemShot(proj);
                    goto IL_0AE3;
                }
                switch (num22)
                {
                case 972:
                    this.DrawProj_NightsEdge(proj);
                    goto IL_0AE3;
                case 973:
                    this.DrawProj_TrueNightsEdge(proj);
                    goto IL_0AE3;
                case 974:
                    this.DrawProj_LightsBane(proj);
                    goto IL_0AE3;
                }
            }
            else if (num22 <= 995)
            {
                switch (num22)
                {
                case 982:
                    this.DrawProj_Excalibur(proj);
                    goto IL_0AE3;
                case 983:
                    this.DrawProj_TrueExcalibur(proj);
                    goto IL_0AE3;
                case 984:
                    this.DrawProj_TerraBlade2(proj);
                    goto IL_0AE3;
                case 985:
                    this.DrawProj_TerraBlade2Shot(proj);
                    goto IL_0AE3;
                default:
                    if (num22 == 995)
                    {
                        Main._stardewAnimation.Draw(Main.spriteBatch, (int)proj.ai[0], proj.Center - Main.screenPosition);
                        flag3 = false;
                        goto IL_0AE3;
                    }
                    break;
                }
            }
            else
            {
                if (num22 == 997)
                {
                    this.DrawProj_TheHorsemansBlade(proj);
                    goto IL_0AE3;
                }
                if (num22 == 1043)
                {
                    this.DrawProj_DeadCellsFlintSlash(proj);
                    goto IL_0AE3;
                }
            }
            flag3 = false;
            IL_0AE3:
            if (flag3)
            {
                return;
            }
            if (proj.type == 34)
            {
                default(FlameLashDrawer).Draw(proj);
            }
            if (proj.type == 16)
            {
                default(MagicMissileDrawer).Draw(proj);
            }
            if (proj.type == 106)
            {
                default(LightDiscDrawer).Draw(proj);
            }
            if (proj.type == 933 || proj.type == 1100)
            {
                default(FinalFractalHelper).Draw(proj);
            }
            if (proj.type == 79)
            {
                default(RainbowRodDrawer).Draw(proj);
            }
            if (proj.type == 946)
            {
                EmpressBladeDrawer empressBladeDrawer = default(EmpressBladeDrawer);
                float num23 = Main.GlobalTimeWrappedHourly % 3f / 3f;
                Player player2 = player;
                float num24 = MathHelper.Max(1f, (float)player2.maxMinions);
                float num25 = (float)proj.identity % num24 / num24 + num23;
                Microsoft.Xna.Framework.Color fairyQueenWeaponsColor = proj.GetFairyQueenWeaponsColor(0f, 0f, new float?(num25 % 1f));
                Microsoft.Xna.Framework.Color fairyQueenWeaponsColor2 = proj.GetFairyQueenWeaponsColor(0f, 0f, new float?((num25 + 0.5f) % 1f));
                empressBladeDrawer.ColorStart = fairyQueenWeaponsColor;
                empressBladeDrawer.ColorEnd = fairyQueenWeaponsColor2;
                empressBladeDrawer.Draw(proj);
                this.DrawProj_EmpressBlade(proj, num25);
                return;
            }
            if (proj.type == 927)
            {
                this.DrawProj_PiercingStarlight(proj);
                return;
            }
            if (proj.type == 917)
            {
                this.DrawProj_CoolWhipMinion(proj);
                return;
            }
            if (proj.type == 923)
            {
                Vector2 vector5 = proj.Center - Main.screenPosition;
                Texture2D value2 = TextureAssets.Projectile[proj.type].Value;
                Microsoft.Xna.Framework.Rectangle rectangle = value2.Frame(1, 2, 0, 0, 0, 0);
                Microsoft.Xna.Framework.Rectangle rectangle2 = value2.Frame(1, 2, 0, 1, 0, 0);
                Vector2 vector6 = rectangle.Size() * new Vector2(0.03f, 0.5f);
                float num26 = 180f;
                float num27 = proj.ai[0] / 6.2831855f + proj.localAI[0] / num26;
                float num28 = Utils.GetLerpValue(0f, 30f, proj.localAI[0], true) * Utils.GetLerpValue(num26, num26 - 30f, proj.localAI[0], true);
                Microsoft.Xna.Framework.Color color5 = Main.hslToRgb(num27 % 1f, 1f, 1f, byte.MaxValue) * num28;
                float lerpValue = Utils.GetLerpValue(40f, 60f, proj.localAI[0], true);
                Vector2 vector7 = new Vector2(1f, MathHelper.Lerp(0.25f, 0.7f, lerpValue)) * proj.scale;
                Microsoft.Xna.Framework.Color color6 = Main.hslToRgb((num27 + 0.3f) % 1f, 1f, MathHelper.Lerp(0.3f, 0.66f, lerpValue), byte.MaxValue) * num28;
                if (NPC.ShouldEmpressBeEnraged())
                {
                    color6 = Main.OurFavoriteColor * num28;
                }
                color6 = Microsoft.Xna.Framework.Color.Lerp(color6, Microsoft.Xna.Framework.Color.White, 0.1f);
                color6.A /= 2;
                Main.spriteBatch.Draw(value2, vector5, new Microsoft.Xna.Framework.Rectangle?(rectangle2), color6, proj.rotation, vector6, vector7 * 1.2f, SpriteEffects.None, 0f);
                Microsoft.Xna.Framework.Color color7 = Main.hslToRgb((num27 + 0.15f) % 1f, 1f, MathHelper.Lerp(0.3f, 0.5f, lerpValue), byte.MaxValue) * num28;
                if (NPC.ShouldEmpressBeEnraged())
                {
                    color7 = Main.OurFavoriteColor * num28;
                }
                color7 = Microsoft.Xna.Framework.Color.Lerp(color7, Microsoft.Xna.Framework.Color.White, 0.1f);
                color7.A /= 2;
                Main.spriteBatch.Draw(value2, vector5, new Microsoft.Xna.Framework.Rectangle?(rectangle2), color7, proj.rotation, vector6, vector7 * 1.1f, SpriteEffects.None, 0f);
                Main.spriteBatch.Draw(value2, vector5, new Microsoft.Xna.Framework.Rectangle?(rectangle), color5 * 0.5f, proj.rotation, vector6, vector7, SpriteEffects.None, 0f);
                Main.spriteBatch.Draw(value2, vector5, new Microsoft.Xna.Framework.Rectangle?(rectangle2), color5 * lerpValue, proj.rotation, vector6, vector7, SpriteEffects.None, 0f);
                return;
            }
            if (proj.type == 950)
            {
                Vector2 vector8 = proj.Center - Main.screenPosition;
                Texture2D value3 = TextureAssets.Projectile[proj.type].Value;
                Microsoft.Xna.Framework.Rectangle rectangle3 = value3.Frame(1, 1, 0, 0, 0, 0);
                Vector2 vector9 = rectangle3.Size() * new Vector2(0.5f, 0.5f);
                Microsoft.Xna.Framework.Color color8 = new Microsoft.Xna.Framework.Color(255, 255, 255, 0) * proj.Opacity;
                float num29 = ((proj.ai[2] == 1f) ? 0.96f : 0.92f);
                if (proj.ai[2] == 1f)
                {
                    color8 = new Microsoft.Xna.Framework.Color(255, 0, 30, 180) * proj.Opacity;
                }
                Microsoft.Xna.Framework.Color color9 = Main.hslToRgb(num29, 1f, 0.5f, byte.MaxValue) * proj.Opacity;
                color9.A = 0;
                color8 *= 0.6f;
                color9 *= 0.6f;
                float scale = proj.scale;
                float num30 = proj.localAI[0];
                Main.spriteBatch.Draw(value3, vector8, new Microsoft.Xna.Framework.Rectangle?(rectangle3), color8, proj.rotation, vector9, num30, SpriteEffects.None, 0f);
                Main.spriteBatch.Draw(value3, vector8, new Microsoft.Xna.Framework.Rectangle?(rectangle3), color9, proj.rotation, vector9, num30 * 0.95f, SpriteEffects.None, 0f);
                Main.spriteBatch.Draw(value3, vector8, new Microsoft.Xna.Framework.Rectangle?(rectangle3), color8, proj.rotation, vector9, scale, SpriteEffects.None, 0f);
                Main.spriteBatch.Draw(value3, vector8, new Microsoft.Xna.Framework.Rectangle?(rectangle3), color9, proj.rotation, vector9, scale * 0.95f, SpriteEffects.None, 0f);
                return;
            }
            if (proj.type == 888)
            {
                this.DrawTwinsPet(proj);
                return;
            }
            if (proj.type == 874)
            {
                this.DrawMurderAurora(proj);
                return;
            }
            if (proj.type == 871)
            {
                Texture2D value4 = TextureAssets.Projectile[proj.type].Value;
                Microsoft.Xna.Framework.Rectangle rectangle4 = value4.Frame(1, 4, 0, 0, 0, 0);
                Vector2 vector10 = rectangle4.Size() / 2f;
                Microsoft.Xna.Framework.Color color10 = Microsoft.Xna.Framework.Color.White * proj.Opacity;
                SpriteEffects spriteEffects = SpriteEffects.None;
                color10.A /= 2;
                Microsoft.Xna.Framework.Color color11 = proj.AI_171_GetColor();
                color11.A /= 2;
                float num31 = proj.scale * 1.3f;
                float num32 = 1f;
                int num33 = proj.AI_172_GetPelletStormsCount();
                bool flag4 = false;
                float num34 = float.PositiveInfinity;
                for (int i = 0; i < num33; i++)
                {
                    Projectile.HallowBossPelletStormInfo hallowBossPelletStormInfo = proj.AI_172_GetPelletStormInfo(i);
                    for (int j = 0; j < hallowBossPelletStormInfo.BulletsInStorm; j++)
                    {
                        float bulletProgress = hallowBossPelletStormInfo.GetBulletProgress(j);
                        if (bulletProgress < num34)
{
                            num34 = bulletProgress;
                        }
                        if (hallowBossPelletStormInfo.IsValid(j))
{
                            if (i == num33 - 1 && bulletProgress > 0f)
{
                                flag4 = true;
                            }
                            rectangle4 = value4.Frame(1, 4, 0, (int)((double)(j + i * 6) + Main.timeForVisualEffects / 4.0) % 4, 0, 0);
                            float num35 = Utils.GetLerpValue(0f, 0.1f, bulletProgress, true) * Utils.GetLerpValue(1f, 0.8f, bulletProgress, true);
                            Vector2 bulletPosition = hallowBossPelletStormInfo.GetBulletPosition(j, proj.Center);
                            Main.EntitySpriteDraw(value4, bulletPosition - Main.screenPosition + new Vector2(0f, proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rectangle4), color11 * num35, proj.rotation, vector10, num31 * num32, spriteEffects, 0f);
                            Main.EntitySpriteDraw(value4, bulletPosition - Main.screenPosition + new Vector2(0f, proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rectangle4), color10 * num35, proj.rotation, vector10, proj.scale * num32, spriteEffects, 0f);
                        }
                    }
                }
                if (!flag4 && num34 <= 1f)
                {
                    Main.EntitySpriteDraw(value4, proj.Center - Main.screenPosition + new Vector2(0f, proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rectangle4), color11, proj.rotation, vector10, num31, spriteEffects, 0f);
                    Main.EntitySpriteDraw(value4, proj.Center - Main.screenPosition + new Vector2(0f, proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rectangle4), color10, proj.rotation, vector10, proj.scale, spriteEffects, 0f);
                }
                return;
            }
            if (proj.bobber && player.inventory[player.selectedItem].holdStyle != 0)
            {
                Main.DrawProj_FishingLine(proj, player, ref num2, ref num3, vector);
            }
            else if (proj.type == 32)
            {
                Vector2 vector11 = new Vector2(proj.position.X + (float)proj.width * 0.5f, proj.position.Y + (float)proj.height * 0.5f);
                float num36 = vector.X - vector11.X;
                float num37 = vector.Y - vector11.Y;
                float num38 = (float)Math.Atan2((double)num37, (double)num36) - 1.57f;
                bool flag5 = true;
                if (num36 == 0f && num37 == 0f)
                {
                    flag5 = false;
                }
                else
                {
                    float num39 = (float)Math.Sqrt((double)(num36 * num36 + num37 * num37));
                    num39 = 8f / num39;
                    num36 *= num39;
                    num37 *= num39;
                    vector11.X -= num36;
                    vector11.Y -= num37;
                    num36 = vector.X - vector11.X;
                    num37 = vector.Y - vector11.Y;
                }
                while (flag5)
                {
                    float num40 = (float)Math.Sqrt((double)(num36 * num36 + num37 * num37));
                    if (num40 < 28f)
                    {
                        flag5 = false;
                    }
                    else if (float.IsNaN(num40))
                    {
                        flag5 = false;
                    }
                    else
                    {
                        num40 = 28f / num40;
                        num36 *= num40;
                        num37 *= num40;
                        vector11.X += num36;
                        vector11.Y += num37;
                        num36 = vector.X - vector11.X;
                        num37 = vector.Y - vector11.Y;
                        Microsoft.Xna.Framework.Color color12 = Lighting.GetColor((int)vector11.X / 16, (int)(vector11.Y / 16f));
                        Main.EntitySpriteDraw(TextureAssets.Chain5.Value, new Vector2(vector11.X - Main.screenPosition.X, vector11.Y - Main.screenPosition.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain5.Width(), TextureAssets.Chain5.Height())), color12, num38, new Vector2((float)TextureAssets.Chain5.Width() * 0.5f, (float)TextureAssets.Chain5.Height() * 0.5f), 1f, SpriteEffects.None, 0f);
                    }
                }
            }
            else if (proj.type == 73)
            {
                Vector2 vector12 = new Vector2(proj.position.X + (float)proj.width * 0.5f, proj.position.Y + (float)proj.height * 0.5f);
                float num41 = vector.X - vector12.X;
                float num42 = vector.Y - vector12.Y;
                float num43 = (float)Math.Atan2((double)num42, (double)num41) - 1.57f;
                bool flag6 = true;
                while (flag6)
                {
                    float num44 = (float)Math.Sqrt((double)(num41 * num41 + num42 * num42));
                    if (num44 < 25f)
                    {
                        flag6 = false;
                    }
                    else if (float.IsNaN(num44))
                    {
                        flag6 = false;
                    }
                    else
                    {
                        num44 = 12f / num44;
                        num41 *= num44;
                        num42 *= num44;
                        vector12.X += num41;
                        vector12.Y += num42;
                        num41 = vector.X - vector12.X;
                        num42 = vector.Y - vector12.Y;
                        Microsoft.Xna.Framework.Color color13 = Lighting.GetColor((int)vector12.X / 16, (int)(vector12.Y / 16f));
                        Main.EntitySpriteDraw(TextureAssets.Chain8.Value, new Vector2(vector12.X - Main.screenPosition.X, vector12.Y - Main.screenPosition.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain8.Width(), TextureAssets.Chain8.Height())), color13, num43, new Vector2((float)TextureAssets.Chain8.Width() * 0.5f, (float)TextureAssets.Chain8.Height() * 0.5f), 1f, SpriteEffects.None, 0f);
                    }
                }
            }
            else if (proj.type == 186)
            {
                Vector2 vector13 = new Vector2(proj.localAI[0], proj.localAI[1]);
                float num45 = Vector2.Distance(proj.Center, vector13) - proj.velocity.Length();
                float num46 = (float)TextureAssets.Chain17.Height() - num45;
                if (num45 > 0f && proj.ai[1] > 0f)
                {
                    Microsoft.Xna.Framework.Color color14 = Lighting.GetColor((int)proj.position.X / 16, (int)proj.position.Y / 16);
                    Main.EntitySpriteDraw(TextureAssets.Chain17.Value, vector13 - Main.screenPosition, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, (int)num46, TextureAssets.Chain17.Width(), (int)num45)), color14, proj.rotation, new Vector2((float)(TextureAssets.Chain17.Width() / 2), 0f), 1f, SpriteEffects.None, 0f);
                }
            }
            else if (proj.type == 74)
            {
                Vector2 vector14 = new Vector2(proj.position.X + (float)proj.width * 0.5f, proj.position.Y + (float)proj.height * 0.5f);
                float num47 = vector.X - vector14.X;
                float num48 = vector.Y - vector14.Y;
                float num49 = (float)Math.Atan2((double)num48, (double)num47) - 1.57f;
                bool flag7 = true;
                while (flag7)
                {
                    float num50 = (float)Math.Sqrt((double)(num47 * num47 + num48 * num48));
                    if (num50 < 25f)
                    {
                        flag7 = false;
                    }
                    else if (float.IsNaN(num50))
                    {
                        flag7 = false;
                    }
                    else
                    {
                        num50 = 12f / num50;
                        num47 *= num50;
                        num48 *= num50;
                        vector14.X += num47;
                        vector14.Y += num48;
                        num47 = vector.X - vector14.X;
                        num48 = vector.Y - vector14.Y;
                        Microsoft.Xna.Framework.Color color15 = Lighting.GetColor((int)vector14.X / 16, (int)(vector14.Y / 16f));
                        Main.EntitySpriteDraw(TextureAssets.Chain9.Value, new Vector2(vector14.X - Main.screenPosition.X, vector14.Y - Main.screenPosition.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain8.Width(), TextureAssets.Chain8.Height())), color15, num49, new Vector2((float)TextureAssets.Chain8.Width() * 0.5f, (float)TextureAssets.Chain8.Height() * 0.5f), 1f, SpriteEffects.None, 0f);
                    }
                }
            }
            else if (proj.type == 171)
            {
                Vector2 vector15 = new Vector2(proj.position.X + (float)proj.width * 0.5f, proj.position.Y + (float)proj.height * 0.5f);
                float num51 = -proj.velocity.X;
                float num52 = -proj.velocity.Y;
                float num53 = 1f;
                if (proj.ai[0] <= 17f)
                {
                    num53 = proj.ai[0] / 17f;
                }
                int num54 = (int)(30f * num53);
                float num55 = 1f;
                if (proj.ai[0] <= 30f)
                {
                    num55 = proj.ai[0] / 30f;
                }
                float num56 = 0.4f * num55;
                float num57 = num56;
                num52 += num57;
                Vector2[] array = new Vector2[num54];
                float[] array2 = new float[num54];
                for (int k = 0; k < num54; k++)
                {
                    float num58 = (float)Math.Sqrt((double)(num51 * num51 + num52 * num52));
                    float num59 = 5.6f;
                    if (Math.Abs(num51) + Math.Abs(num52) < 1f)
                    {
                        num59 *= Math.Abs(num51) + Math.Abs(num52) / 1f;
                    }
                    num58 = num59 / num58;
                    num51 *= num58;
                    num52 *= num58;
                    float num60 = (float)Math.Atan2((double)num52, (double)num51) - 1.57f;
                    array[k].X = vector15.X;
                    array[k].Y = vector15.Y;
                    array2[k] = num60;
                    vector15.X += num51;
                    vector15.Y += num52;
                    num51 = -proj.velocity.X;
                    num52 = -proj.velocity.Y;
                    num57 += num56;
                    num52 += num57;
                }
                for (int l = num54 - 1; l >= 0; l--)
                {
                    vector15.X = array[l].X;
                    vector15.Y = array[l].Y;
                    float num61 = array2[l];
                    Microsoft.Xna.Framework.Color color16 = Lighting.GetColor((int)vector15.X / 16, (int)(vector15.Y / 16f));
                    Main.EntitySpriteDraw(TextureAssets.Chain16.Value, new Vector2(vector15.X - Main.screenPosition.X, vector15.Y - Main.screenPosition.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain16.Width(), TextureAssets.Chain16.Height())), color16, num61, new Vector2((float)TextureAssets.Chain16.Width() * 0.5f, (float)TextureAssets.Chain16.Height() * 0.5f), 0.8f, SpriteEffects.None, 0f);
                }
            }
            else if (proj.type == 475)
            {
                Vector2 vector16 = new Vector2(proj.position.X + (float)proj.width * 0.5f, proj.position.Y + (float)proj.height * 0.5f);
                float num62 = -proj.velocity.X;
                float num63 = -proj.velocity.Y;
                float num64 = 1f;
                if (proj.ai[0] <= 17f)
                {
                    num64 = proj.ai[0] / 17f;
                }
                int num65 = (int)(30f * num64);
                float num66 = 1f;
                if (proj.ai[0] <= 30f)
                {
                    num66 = proj.ai[0] / 30f;
                }
                float num67 = 0.4f * num66;
                float num68 = num67;
                num63 += num68;
                Vector2[] array3 = new Vector2[num65];
                float[] array4 = new float[num65];
                for (int m = 0; m < num65; m++)
                {
                    float num69 = (float)Math.Sqrt((double)(num62 * num62 + num63 * num63));
                    float num70 = 5.6f;
                    if (Math.Abs(num62) + Math.Abs(num63) < 1f)
                    {
                        num70 *= Math.Abs(num62) + Math.Abs(num63) / 1f;
                    }
                    num69 = num70 / num69;
                    num62 *= num69;
                    num63 *= num69;
                    float num71 = (float)Math.Atan2((double)num63, (double)num62) - 1.57f;
                    array3[m].X = vector16.X;
                    array3[m].Y = vector16.Y;
                    array4[m] = num71;
                    vector16.X += num62;
                    vector16.Y += num63;
                    num62 = -proj.velocity.X;
                    num63 = -proj.velocity.Y;
                    num68 += num67;
                    num63 += num68;
                }
                int num72 = 0;
                for (int n = num65 - 1; n >= 0; n--)
                {
                    vector16.X = array3[n].X;
                    vector16.Y = array3[n].Y;
                    float num73 = array4[n];
                    Microsoft.Xna.Framework.Color color17 = Lighting.GetColor((int)vector16.X / 16, (int)(vector16.Y / 16f));
                    if (num72 % 2 == 0)
                    {
                        Main.EntitySpriteDraw(TextureAssets.Chain38.Value, new Vector2(vector16.X - Main.screenPosition.X, vector16.Y - Main.screenPosition.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain38.Width(), TextureAssets.Chain38.Height())), color17, num73, new Vector2((float)TextureAssets.Chain38.Width() * 0.5f, (float)TextureAssets.Chain38.Height() * 0.5f), 0.8f, SpriteEffects.None, 0f);
                    }
                    else
                    {
                        Main.EntitySpriteDraw(TextureAssets.Chain39.Value, new Vector2(vector16.X - Main.screenPosition.X, vector16.Y - Main.screenPosition.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain39.Width(), TextureAssets.Chain39.Height())), color17, num73, new Vector2((float)TextureAssets.Chain39.Width() * 0.5f, (float)TextureAssets.Chain39.Height() * 0.5f), 0.8f, SpriteEffects.None, 0f);
                    }
                    num72++;
                }
            }
            else if (proj.type == 505 || proj.type == 506)
            {
                Vector2 vector17 = new Vector2(proj.position.X + (float)proj.width * 0.5f, proj.position.Y + (float)proj.height * 0.5f);
                float num74 = -proj.velocity.X;
                float num75 = -proj.velocity.Y;
                float num76 = 1f;
                if (proj.ai[0] <= 17f)
                {
                    num76 = proj.ai[0] / 17f;
                }
                int num77 = (int)(30f * num76);
                float num78 = 1f;
                if (proj.ai[0] <= 30f)
                {
                    num78 = proj.ai[0] / 30f;
                }
                float num79 = 0.4f * num78;
                float num80 = num79;
                num75 += num80;
                Vector2[] array5 = new Vector2[num77];
                float[] array6 = new float[num77];
                for (int num81 = 0; num81 < num77; num81++)
                {
                    float num82 = (float)Math.Sqrt((double)(num74 * num74 + num75 * num75));
                    float num83 = 5.6f;
                    if (Math.Abs(num74) + Math.Abs(num75) < 1f)
                    {
                        num83 *= Math.Abs(num74) + Math.Abs(num75) / 1f;
                    }
                    num82 = num83 / num82;
                    num74 *= num82;
                    num75 *= num82;
                    float num84 = (float)Math.Atan2((double)num75, (double)num74) - 1.57f;
                    array5[num81].X = vector17.X;
                    array5[num81].Y = vector17.Y;
                    array6[num81] = num84;
                    vector17.X += num74;
                    vector17.Y += num75;
                    num74 = -proj.velocity.X;
                    num75 = -proj.velocity.Y;
                    num80 += num79;
                    num75 += num80;
                }
                int num85 = 0;
                for (int num86 = num77 - 1; num86 >= 0; num86--)
                {
                    vector17.X = array5[num86].X;
                    vector17.Y = array5[num86].Y;
                    float num87 = array6[num86];
                    Microsoft.Xna.Framework.Color color18 = Lighting.GetColor((int)vector17.X / 16, (int)(vector17.Y / 16f));
                    int num88 = 4;
                    if (proj.type == 506)
                    {
                        num88 = 6;
                    }
                    num88 += num85 % 2;
                    Main.EntitySpriteDraw(TextureAssets.Chains[num88].Value, new Vector2(vector17.X - Main.screenPosition.X, vector17.Y - Main.screenPosition.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chains[num88].Width(), TextureAssets.Chains[num88].Height())), color18, num87, new Vector2((float)TextureAssets.Chains[num88].Width() * 0.5f, (float)TextureAssets.Chains[num88].Height() * 0.5f), 0.8f, SpriteEffects.None, 0f);
                    num85++;
                }
            }
            else if (proj.type == 165)
            {
                Vector2 vector18 = new Vector2(proj.position.X + (float)proj.width * 0.5f, proj.position.Y + (float)proj.height * 0.5f);
                float num89 = vector.X - vector18.X;
                float num90 = vector.Y - vector18.Y;
                float num91 = (float)Math.Atan2((double)num90, (double)num89) - 1.57f;
                bool flag8 = true;
                while (flag8)
                {
                    float num92 = (float)Math.Sqrt((double)(num89 * num89 + num90 * num90));
                    if (num92 < 25f)
                    {
                        flag8 = false;
                    }
                    else if (float.IsNaN(num92))
                    {
                        flag8 = false;
                    }
                    else
                    {
                        num92 = 24f / num92;
                        num89 *= num92;
                        num90 *= num92;
                        vector18.X += num89;
                        vector18.Y += num90;
                        num89 = vector.X - vector18.X;
                        num90 = vector.Y - vector18.Y;
                        Microsoft.Xna.Framework.Color color19 = Lighting.GetColor((int)vector18.X / 16, (int)(vector18.Y / 16f));
                        Main.EntitySpriteDraw(TextureAssets.Chain15.Value, new Vector2(vector18.X - Main.screenPosition.X, vector18.Y - Main.screenPosition.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain15.Width(), TextureAssets.Chain15.Height())), color19, num91, new Vector2((float)TextureAssets.Chain15.Width() * 0.5f, (float)TextureAssets.Chain15.Height() * 0.5f), 1f, SpriteEffects.None, 0f);
                    }
                }
            }
            else if (proj.type >= 230 && proj.type <= 235)
            {
                int num93 = proj.type - 229;
                Vector2 vector19 = new Vector2(proj.position.X + (float)proj.width * 0.5f, proj.position.Y + (float)proj.height * 0.5f);
                float num94 = vector.X - vector19.X;
                float num95 = vector.Y - vector19.Y;
                float num96 = (float)Math.Atan2((double)num95, (double)num94) - 1.57f;
                bool flag9 = true;
                while (flag9)
                {
                    float num97 = (float)Math.Sqrt((double)(num94 * num94 + num95 * num95));
                    if (num97 < 25f)
                    {
                        flag9 = false;
                    }
                    else if (float.IsNaN(num97))
                    {
                        flag9 = false;
                    }
                    else
                    {
                        num97 = (float)TextureAssets.GemChain[num93].Height() / num97;
                        num94 *= num97;
                        num95 *= num97;
                        vector19.X += num94;
                        vector19.Y += num95;
                        num94 = vector.X - vector19.X;
                        num95 = vector.Y - vector19.Y;
                        Microsoft.Xna.Framework.Color color20 = Lighting.GetColor((int)vector19.X / 16, (int)(vector19.Y / 16f));
                        Main.EntitySpriteDraw(TextureAssets.GemChain[num93].Value, new Vector2(vector19.X - Main.screenPosition.X, vector19.Y - Main.screenPosition.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.GemChain[num93].Width(), TextureAssets.GemChain[num93].Height())), color20, num96, new Vector2((float)TextureAssets.GemChain[num93].Width() * 0.5f, (float)TextureAssets.GemChain[num93].Height() * 0.5f), 1f, SpriteEffects.None, 0f);
                    }
                }
            }
            else if (proj.type == 753)
            {
                Vector2 vector20 = new Vector2(proj.position.X + (float)proj.width * 0.5f, proj.position.Y + (float)proj.height * 0.5f);
                float num98 = vector.X - vector20.X;
                float num99 = vector.Y - vector20.Y;
                float num100 = (float)Math.Atan2((double)num99, (double)num98) - 1.57f;
                bool flag10 = true;
                Texture2D value5 = TextureAssets.Extra[95].Value;
                while (flag10)
                {
                    float num101 = (float)Math.Sqrt((double)(num98 * num98 + num99 * num99));
                    if (num101 < 25f)
                    {
                        flag10 = false;
                    }
                    else if (float.IsNaN(num101))
                    {
                        flag10 = false;
                    }
                    else
                    {
                        num101 = (float)value5.Height / num101;
                        num98 *= num101;
                        num99 *= num101;
                        vector20.X += num98;
                        vector20.Y += num99;
                        num98 = vector.X - vector20.X;
                        num99 = vector.Y - vector20.Y;
                        Microsoft.Xna.Framework.Color color21 = Lighting.GetColor((int)vector20.X / 16, (int)(vector20.Y / 16f));
                        Main.EntitySpriteDraw(value5, new Vector2(vector20.X - Main.screenPosition.X, vector20.Y - Main.screenPosition.Y), null, color21, num100, value5.Size() / 2f, 1f, SpriteEffects.None, 0f);
                    }
                }
            }
            else if (proj.type == 865)
            {
                Vector2 vector21 = new Vector2(proj.position.X + (float)proj.width * 0.5f, proj.position.Y + (float)proj.height * 0.5f);
                float num102 = vector.X - vector21.X;
                float num103 = vector.Y - vector21.Y;
                float num104 = (float)Math.Atan2((double)num103, (double)num102) - 1.57f;
                bool flag11 = true;
                bool flag12 = true;
                Texture2D value6 = TextureAssets.Extra[154].Value;
                while (flag11)
                {
                    float num105 = (float)Math.Sqrt((double)(num102 * num102 + num103 * num103));
                    if (num105 < 25f)
                    {
                        flag11 = false;
                    }
                    else if (float.IsNaN(num105))
                    {
                        flag11 = false;
                    }
                    else
                    {
                        num105 = (float)value6.Height / num105;
                        num102 *= num105;
                        num103 *= num105;
                        vector21.X += num102;
                        vector21.Y += num103;
                        num102 = vector.X - vector21.X;
                        num103 = vector.Y - vector21.Y;
                        if (!flag12)
{
                            Microsoft.Xna.Framework.Color color22 = Lighting.GetColor((int)vector21.X / 16, (int)(vector21.Y / 16f));
                            Main.EntitySpriteDraw(value6, new Vector2(vector21.X - Main.screenPosition.X, vector21.Y - Main.screenPosition.Y), null, color22, num104, value6.Size() / 2f, 1f, SpriteEffects.None, 0f);
                        }
                        flag12 = false;
                    }
                }
            }
            else if (proj.type == 935)
            {
                Vector2 vector22 = new Vector2(proj.position.X + (float)proj.width * 0.5f, proj.position.Y + (float)proj.height * 0.5f);
                float num106 = vector.X - vector22.X;
                float num107 = vector.Y - vector22.Y;
                float num108 = (float)Math.Atan2((double)num107, (double)num106) - 1.57f;
                bool flag13 = true;
                bool flag14 = true;
                Texture2D value7 = TextureAssets.Extra[208].Value;
                while (flag13)
                {
                    float num109 = (float)Math.Sqrt((double)(num106 * num106 + num107 * num107));
                    if (num109 < 8f)
                    {
                        flag13 = false;
                    }
                    else if (float.IsNaN(num109))
                    {
                        flag13 = false;
                    }
                    else
                    {
                        num109 = (float)value7.Height / num109;
                        num106 *= num109;
                        num107 *= num109;
                        vector22.X += num106;
                        vector22.Y += num107;
                        num106 = vector.X - vector22.X;
                        num107 = vector.Y - vector22.Y;
                        if (!flag14)
{
                            Microsoft.Xna.Framework.Color color23 = Lighting.GetColor((int)vector22.X / 16, (int)(vector22.Y / 16f));
                            Main.EntitySpriteDraw(value7, new Vector2(vector22.X - Main.screenPosition.X, vector22.Y - Main.screenPosition.Y), null, color23, num108, value7.Size() / 2f, 1f, SpriteEffects.None, 0f);
                        }
                        flag14 = false;
                    }
                }
            }
            else if (proj.type == 256)
            {
                Vector2 vector23 = new Vector2(proj.position.X + (float)proj.width * 0.5f, proj.position.Y + (float)proj.height * 0.5f);
                float num110 = vector.X - vector23.X;
                float num111 = vector.Y - vector23.Y;
                float num112 = (float)Math.Atan2((double)num111, (double)num110) - 1.57f;
                bool flag15 = true;
                while (flag15)
                {
                    float num113 = (float)Math.Sqrt((double)(num110 * num110 + num111 * num111));
                    if (num113 < 26f)
                    {
                        flag15 = false;
                    }
                    else if (float.IsNaN(num113))
                    {
                        flag15 = false;
                    }
                    else
                    {
                        num113 = 26f / num113;
                        num110 *= num113;
                        num111 *= num113;
                        vector23.X += num110;
                        vector23.Y += num111;
                        num110 = player.position.X + (float)(player.width / 2) - vector23.X;
                        num111 = player.position.Y + (float)(player.height / 2) - vector23.Y;
                        Microsoft.Xna.Framework.Color color24 = Lighting.GetColor((int)vector23.X / 16, (int)(vector23.Y / 16f));
                        Main.EntitySpriteDraw(TextureAssets.Chain20.Value, new Vector2(vector23.X - Main.screenPosition.X, vector23.Y - Main.screenPosition.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain20.Width(), TextureAssets.Chain20.Height())), color24, num112 - 0.785f, new Vector2((float)TextureAssets.Chain20.Width() * 0.5f, (float)TextureAssets.Chain20.Height() * 0.5f), 1f, SpriteEffects.None, 0f);
                    }
                }
            }
            else if (proj.type == 322)
            {
                Vector2 vector24 = new Vector2(proj.position.X + (float)proj.width * 0.5f, proj.position.Y + (float)proj.height * 0.5f);
                float num114 = vector.X - vector24.X;
                float num115 = vector.Y - vector24.Y;
                float num116 = (float)Math.Atan2((double)num115, (double)num114) - 1.57f;
                bool flag16 = true;
                while (flag16)
                {
                    float num117 = (float)Math.Sqrt((double)(num114 * num114 + num115 * num115));
                    if (num117 < 22f)
                    {
                        flag16 = false;
                    }
                    else if (float.IsNaN(num117))
                    {
                        flag16 = false;
                    }
                    else
                    {
                        num117 = 22f / num117;
                        num114 *= num117;
                        num115 *= num117;
                        vector24.X += num114;
                        vector24.Y += num115;
                        num114 = vector.X - vector24.X;
                        num115 = vector.Y - vector24.Y;
                        Microsoft.Xna.Framework.Color color25 = Lighting.GetColor((int)vector24.X / 16, (int)(vector24.Y / 16f));
                        Main.EntitySpriteDraw(TextureAssets.Chain29.Value, new Vector2(vector24.X - Main.screenPosition.X, vector24.Y - Main.screenPosition.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain29.Width(), TextureAssets.Chain29.Height())), color25, num116, new Vector2((float)TextureAssets.Chain29.Width() * 0.5f, (float)TextureAssets.Chain29.Height() * 0.5f), 1f, SpriteEffects.None, 0f);
                    }
                }
            }
            else if (proj.type == 315)
            {
                Vector2 vector25 = new Vector2(proj.position.X + (float)proj.width * 0.5f, proj.position.Y + (float)proj.height * 0.5f);
                float num118 = vector.X - vector25.X;
                float num119 = vector.Y - vector25.Y;
                float num120 = (float)Math.Atan2((double)num119, (double)num118) - 1.57f;
                bool flag17 = true;
                while (flag17)
                {
                    float num121 = (float)Math.Sqrt((double)(num118 * num118 + num119 * num119));
                    if (num121 < 50f)
                    {
                        flag17 = false;
                    }
                    else if (float.IsNaN(num121))
                    {
                        flag17 = false;
                    }
                    else
                    {
                        num121 = 40f / num121;
                        num118 *= num121;
                        num119 *= num121;
                        vector25.X += num118;
                        vector25.Y += num119;
                        num118 = vector.X - vector25.X;
                        num119 = vector.Y - vector25.Y;
                        Microsoft.Xna.Framework.Color color26 = Lighting.GetColor((int)vector25.X / 16, (int)(vector25.Y / 16f));
                        Main.EntitySpriteDraw(TextureAssets.Chain28.Value, new Vector2(vector25.X - Main.screenPosition.X, vector25.Y - Main.screenPosition.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain28.Width(), TextureAssets.Chain28.Height())), color26, num120, new Vector2((float)TextureAssets.Chain28.Width() * 0.5f, (float)TextureAssets.Chain28.Height() * 0.5f), 1f, SpriteEffects.None, 0f);
                    }
                }
            }
            else if (proj.type == 331)
            {
                Vector2 vector26 = new Vector2(proj.position.X + (float)proj.width * 0.5f, proj.position.Y + (float)proj.height * 0.5f);
                float num122 = vector.X - vector26.X;
                float num123 = vector.Y - vector26.Y;
                float num124 = (float)Math.Atan2((double)num123, (double)num122) - 1.57f;
                bool flag18 = true;
                while (flag18)
                {
                    float num125 = (float)Math.Sqrt((double)(num122 * num122 + num123 * num123));
                    if (num125 < 30f)
                    {
                        flag18 = false;
                    }
                    else if (float.IsNaN(num125))
                    {
                        flag18 = false;
                    }
                    else
                    {
                        num125 = 24f / num125;
                        num122 *= num125;
                        num123 *= num125;
                        vector26.X += num122;
                        vector26.Y += num123;
                        num122 = vector.X - vector26.X;
                        num123 = vector.Y - vector26.Y;
                        Microsoft.Xna.Framework.Color color27 = Lighting.GetColor((int)vector26.X / 16, (int)(vector26.Y / 16f));
                        Main.EntitySpriteDraw(TextureAssets.Chain30.Value, new Vector2(vector26.X - Main.screenPosition.X, vector26.Y - Main.screenPosition.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain30.Width(), TextureAssets.Chain30.Height())), color27, num124, new Vector2((float)TextureAssets.Chain30.Width() * 0.5f, (float)TextureAssets.Chain30.Height() * 0.5f), 1f, SpriteEffects.None, 0f);
                    }
                }
            }
            else if (proj.type == 332)
            {
                int num126 = 0;
                Vector2 vector27 = new Vector2(proj.position.X + (float)proj.width * 0.5f, proj.position.Y + (float)proj.height * 0.5f);
                float num127 = vector.X - vector27.X;
                float num128 = vector.Y - vector27.Y;
                float num129 = (float)Math.Atan2((double)num128, (double)num127) - 1.57f;
                bool flag19 = true;
                while (flag19)
                {
                    float num130 = (float)Math.Sqrt((double)(num127 * num127 + num128 * num128));
                    if (num130 < 30f)
                    {
                        flag19 = false;
                    }
                    else if (float.IsNaN(num130))
                    {
                        flag19 = false;
                    }
                    else
                    {
                        int num131 = (int)vector27.X / 16;
                        int num132 = (int)vector27.Y / 16;
                        if (num126 == 0)
{
                            Lighting.AddLight(num131, num132, 0f, 0.2f, 0.2f);
                        }
                        if (num126 == 1)
{
                            Lighting.AddLight(num131, num132, 0.1f, 0.2f, 0f);
                        }
                        if (num126 == 2)
{
                            Lighting.AddLight(num131, num132, 0.2f, 0.1f, 0f);
                        }
                        if (num126 == 3)
{
                            Lighting.AddLight(num131, num132, 0.2f, 0f, 0.2f);
                        }
                        num130 = 16f / num130;
                        num127 *= num130;
                        num128 *= num130;
                        vector27.X += num127;
                        vector27.Y += num128;
                        num127 = vector.X - vector27.X;
                        num128 = vector.Y - vector27.Y;
                        Microsoft.Xna.Framework.Color color28 = Lighting.GetColor((int)vector27.X / 16, (int)(vector27.Y / 16f));
                        Main.EntitySpriteDraw(TextureAssets.Chain31.Value, new Vector2(vector27.X - Main.screenPosition.X, vector27.Y - Main.screenPosition.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, TextureAssets.Chain31.Height() / 4 * num126, TextureAssets.Chain31.Width(), TextureAssets.Chain31.Height() / 4)), color28, num129, new Vector2((float)TextureAssets.Chain30.Width() * 0.5f, (float)(TextureAssets.Chain30.Height() / 8)), 1f, SpriteEffects.None, 0f);
                        Main.EntitySpriteDraw(TextureAssets.Chain32.Value, new Vector2(vector27.X - Main.screenPosition.X, vector27.Y - Main.screenPosition.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, TextureAssets.Chain31.Height() / 4 * num126, TextureAssets.Chain31.Width(), TextureAssets.Chain31.Height() / 4)), new Microsoft.Xna.Framework.Color(200, 200, 200, 0), num129, new Vector2((float)TextureAssets.Chain30.Width() * 0.5f, (float)(TextureAssets.Chain30.Height() / 8)), 1f, SpriteEffects.None, 0f);
                        num126++;
                        if (num126 > 3)
{
                            num126 = 0;
                        }
                    }
                }
            }
            else if (proj.type == 372 || proj.type == 383 || proj.type == 396 || proj.type == 403 || proj.type == 404 || proj.type == 1058 || proj.type == 446 || (proj.type >= 486 && proj.type <= 489) || (proj.type >= 646 && proj.type <= 649) || proj.type == 652)
            {
                Texture2D texture2D = null;
                Microsoft.Xna.Framework.Color transparent = Microsoft.Xna.Framework.Color.Transparent;
                Texture2D texture2D2 = TextureAssets.Chain33.Value;
                if (proj.type == 383)
                {
                    texture2D2 = TextureAssets.Chain34.Value;
                }
                if (proj.type == 396)
                {
                    texture2D2 = TextureAssets.Chain35.Value;
                }
                if (proj.type == 403)
                {
                    texture2D2 = TextureAssets.Chain36.Value;
                }
                if (proj.type == 404 || proj.type == 1058)
                {
                    texture2D2 = TextureAssets.Chain37.Value;
                }
                if (proj.type == 446)
                {
                    texture2D2 = TextureAssets.Extra[3].Value;
                }
                if (proj.type >= 486 && proj.type <= 489)
                {
                    texture2D2 = TextureAssets.Chains[proj.type - 486].Value;
                }
                if (proj.type >= 646 && proj.type <= 649)
                {
                    texture2D2 = TextureAssets.Chains[proj.type - 646 + 8].Value;
                    texture2D = TextureAssets.Chains[proj.type - 646 + 12].Value;
                    transparent = new Microsoft.Xna.Framework.Color(255, 255, 255, 127);
                }
                if (proj.type == 652)
                {
                    texture2D2 = TextureAssets.Chains[16].Value;
                }
                Vector2 vector28 = proj.Center;
                Microsoft.Xna.Framework.Rectangle? rectangle5 = null;
                Vector2 vector29 = new Vector2((float)texture2D2.Width * 0.5f, (float)texture2D2.Height * 0.5f);
                float num133 = (float)texture2D2.Height;
                float num134 = 0f;
                if (proj.type == 446)
                {
                    int num135 = 7;
                    int num136 = (int)proj.localAI[0] / num135;
                    rectangle5 = new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, texture2D2.Height / 4 * num136, texture2D2.Width, texture2D2.Height / 4));
                    vector29.Y /= 4f;
                    num133 /= 4f;
                }
                num22 = proj.type;
                if (num22 <= 446)
                {
                    if (num22 != 383)
                    {
                        if (num22 == 446)
{
                            num134 = 20f;
                        }
                    }
                    else
                    {
                        num134 = 14f;
                    }
                }
                else if (num22 != 487)
                {
                    if (num22 == 489)
                    {
                        num134 = 10f;
                    }
                }
                else
                {
                    num134 = 8f;
                }
                if (num134 != 0f)
                {
                    float num137 = -1.57f;
                    Vector2 vector30 = new Vector2((float)Math.Cos((double)(proj.rotation + num137)), (float)Math.Sin((double)(proj.rotation + num137)));
                    vector28 -= vector30 * num134;
                    vector30 = vector - vector28;
                    vector30.Normalize();
                    vector28 -= vector30 * num133 / 2f;
                }
                Vector2 vector31 = vector - vector28;
                float num138 = (float)Math.Atan2((double)vector31.Y, (double)vector31.X) - 1.57f;
                bool flag20 = true;
                if (float.IsNaN(vector28.X) && float.IsNaN(vector28.Y))
                {
                    flag20 = false;
                }
                if (float.IsNaN(vector31.X) && float.IsNaN(vector31.Y))
                {
                    flag20 = false;
                }
                if (proj.type == 383)
                {
                    if (proj.ai[0] == 0f)
                    {
                        proj.localAI[1] = (-proj.velocity.X + proj.localAI[1]) / 2f;
                        proj.localAI[2] = (-proj.velocity.Y + proj.localAI[2]) / 2f;
                    }
                    else
                    {
                        proj.localAI[1] = (proj.velocity.X + proj.localAI[1] * 4f) / 5f;
                        proj.localAI[2] = (proj.velocity.Y + proj.localAI[2] * 4f) / 5f;
                    }
                }
                while (flag20)
                {
                    if (vector31.Length() < num133 + 1f)
                    {
                        flag20 = false;
                    }
                    else
                    {
                        Vector2 vector32 = vector31;
                        vector32.Normalize();
                        if (proj.type == 383)
{
                            float num139 = vector31.Length();
                            if (num139 > 12f)
{
                                float num140 = num139 / 1000f;
                                if ((double)num140 > 0.4)
{
                                    num140 = 0.4f;
                                }
                                Vector2 vector33 = vector - vector28;
                                Vector2 vector34 = new Vector2(proj.localAI[1], proj.localAI[2]);
                                vector33.Length();
                                vector33.Normalize();
                                vector34.Normalize();
                                vector32.X = vector33.X * (1f - num140) + vector34.X * num140;
                                vector32.Y = vector33.Y * (1f - num140) + vector34.Y * num140;
                                num138 = (float)Math.Atan2((double)vector32.Y, (double)vector32.X) - 1.57f;
                            }
                        }
                        vector28 += vector32 * num133;
                        vector31 = vector - vector28;
                        Microsoft.Xna.Framework.Color color29 = Lighting.GetColor((int)vector28.X / 16, (int)(vector28.Y / 16f));
                        if (proj.type == 396)
{
                            color29 *= (float)(255 - proj.alpha) / 255f;
                        }
                        if (proj.type == 446)
{
                            color29 = proj.GetAlpha(color29);
                        }
                        if (proj.type == 488)
{
                            Lighting.AddLight(vector28, 0.2f, 0f, 0.175f);
                            color29 = new Microsoft.Xna.Framework.Color(255, 255, 255, 255);
                        }
                        if (proj.type >= 646 && proj.type <= 649)
{
                            color29 = proj.GetAlpha(color29);
                        }
                        Main.EntitySpriteDraw(texture2D2, vector28 - Main.screenPosition, rectangle5, color29, num138, vector29, 1f, SpriteEffects.None, 0f);
                        if (texture2D != null)
{
                            Main.EntitySpriteDraw(texture2D, vector28 - Main.screenPosition, rectangle5, transparent, num138, vector29, 1f, SpriteEffects.None, 0f);
                        }
                    }
                }
            }
            else if (proj.aiStyle == 7)
            {
                Vector2 vector35 = new Vector2(proj.position.X + (float)proj.width * 0.5f, proj.position.Y + (float)proj.height * 0.5f);
                float num141 = vector.X - vector35.X;
                float num142 = vector.Y - vector35.Y;
                float num143 = (float)Math.Atan2((double)num142, (double)num141) - 1.57f;
                bool flag21 = true;
                while (flag21)
                {
                    float num144 = (float)Math.Sqrt((double)(num141 * num141 + num142 * num142));
                    if (num144 < 25f)
                    {
                        flag21 = false;
                    }
                    else if (float.IsNaN(num144))
                    {
                        flag21 = false;
                    }
                    else
                    {
                        num144 = 12f / num144;
                        num141 *= num144;
                        num142 *= num144;
                        vector35.X += num141;
                        vector35.Y += num142;
                        num141 = vector.X - vector35.X;
                        num142 = vector.Y - vector35.Y;
                        Microsoft.Xna.Framework.Color color30 = Lighting.GetColor((int)vector35.X / 16, (int)(vector35.Y / 16f));
                        Main.EntitySpriteDraw(TextureAssets.Chain.Value, new Vector2(vector35.X - Main.screenPosition.X, vector35.Y - Main.screenPosition.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain.Width(), TextureAssets.Chain.Height())), color30, num143, new Vector2((float)TextureAssets.Chain.Width() * 0.5f, (float)TextureAssets.Chain.Height() * 0.5f), 1f, SpriteEffects.None, 0f);
                    }
                }
            }
            else if (proj.type == 262)
            {
                float num145 = proj.Center.X;
                float num146 = proj.Center.Y;
                float num147 = proj.velocity.X;
                float num148 = proj.velocity.Y;
                float num149 = (float)Math.Sqrt((double)(num147 * num147 + num148 * num148));
                num149 = 4f / num149;
                if (proj.ai[0] == 0f)
                {
                    num145 -= proj.velocity.X * num149;
                    num146 -= proj.velocity.Y * num149;
                }
                else
                {
                    num145 += proj.velocity.X * num149;
                    num146 += proj.velocity.Y * num149;
                }
                Vector2 vector36 = new Vector2(num145, num146);
                num147 = vector.X - vector36.X;
                num148 = vector.Y - vector36.Y;
                float num150 = (float)Math.Atan2((double)num148, (double)num147) - 1.57f;
                bool flag22 = true;
                while (flag22)
                {
                    float num151 = (float)Math.Sqrt((double)(num147 * num147 + num148 * num148));
                    if (num151 < 25f)
                    {
                        flag22 = false;
                    }
                    else if (float.IsNaN(num151))
                    {
                        flag22 = false;
                    }
                    else
                    {
                        num151 = 12f / num151;
                        num147 *= num151;
                        num148 *= num151;
                        vector36.X += num147;
                        vector36.Y += num148;
                        num147 = vector.X - vector36.X;
                        num148 = vector.Y - vector36.Y;
                        Microsoft.Xna.Framework.Color color31 = Lighting.GetColor((int)vector36.X / 16, (int)(vector36.Y / 16f));
                        Main.EntitySpriteDraw(TextureAssets.Chain22.Value, new Vector2(vector36.X - Main.screenPosition.X, vector36.Y - Main.screenPosition.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain22.Width(), TextureAssets.Chain22.Height())), color31, num150, new Vector2((float)TextureAssets.Chain22.Width() * 0.5f, (float)TextureAssets.Chain22.Height() * 0.5f), 1f, SpriteEffects.None, 0f);
                    }
                }
            }
            else if (proj.type == 273)
            {
                float num152 = proj.Center.X;
                float num153 = proj.Center.Y;
                float num154 = proj.velocity.X;
                float num155 = proj.velocity.Y;
                float num156 = (float)Math.Sqrt((double)(num154 * num154 + num155 * num155));
                num156 = 4f / num156;
                if (proj.ai[0] == 0f)
                {
                    num152 -= proj.velocity.X * num156;
                    num153 -= proj.velocity.Y * num156;
                }
                else
                {
                    num152 += proj.velocity.X * num156;
                    num153 += proj.velocity.Y * num156;
                }
                Vector2 vector37 = new Vector2(num152, num153);
                num154 = vector.X - vector37.X;
                num155 = vector.Y - vector37.Y;
                float num157 = (float)Math.Atan2((double)num155, (double)num154) - 1.57f;
                bool flag23 = true;
                while (flag23)
                {
                    float num158 = (float)Math.Sqrt((double)(num154 * num154 + num155 * num155));
                    if (num158 < 25f)
                    {
                        flag23 = false;
                    }
                    else if (float.IsNaN(num158))
                    {
                        flag23 = false;
                    }
                    else
                    {
                        num158 = 12f / num158;
                        num154 *= num158;
                        num155 *= num158;
                        vector37.X += num154;
                        vector37.Y += num155;
                        num154 = vector.X - vector37.X;
                        num155 = vector.Y - vector37.Y;
                        Microsoft.Xna.Framework.Color color32 = Lighting.GetColor((int)vector37.X / 16, (int)(vector37.Y / 16f));
                        Main.EntitySpriteDraw(TextureAssets.Chain23.Value, new Vector2(vector37.X - Main.screenPosition.X, vector37.Y - Main.screenPosition.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain23.Width(), TextureAssets.Chain23.Height())), color32, num157, new Vector2((float)TextureAssets.Chain23.Width() * 0.5f, (float)TextureAssets.Chain23.Height() * 0.5f), 1f, SpriteEffects.None, 0f);
                    }
                }
            }
            else if (proj.type == 481)
            {
                float num159 = proj.Center.X;
                float num160 = proj.Center.Y;
                float num161 = proj.velocity.X;
                float num162 = proj.velocity.Y;
                float num163 = (float)Math.Sqrt((double)(num161 * num161 + num162 * num162));
                num163 = 4f / num163;
                if (proj.ai[0] == 0f)
                {
                    num159 -= proj.velocity.X * num163;
                    num160 -= proj.velocity.Y * num163;
                }
                else
                {
                    num159 += proj.velocity.X * num163;
                    num160 += proj.velocity.Y * num163;
                }
                Vector2 vector38 = new Vector2(num159, num160);
                num161 = vector.X - vector38.X;
                num162 = vector.Y - vector38.Y;
                float num164 = (float)Math.Atan2((double)num162, (double)num161) - 1.57f;
                bool flag24 = true;
                while (flag24)
                {
                    float num165 = 0.85f;
                    float num166 = vector38.Distance(vector);
                    float num167 = num166;
                    if ((double)num166 < (double)TextureAssets.Chain40.Height() * 1.5)
                    {
                        flag24 = false;
                    }
                    else if (float.IsNaN(num166))
                    {
                        flag24 = false;
                    }
                    else
                    {
                        num166 = (float)TextureAssets.Chain40.Height() * num165 / num166;
                        num161 *= num166;
                        num162 *= num166;
                        vector38.X += num161;
                        vector38.Y += num162;
                        num161 = vector.X - vector38.X;
                        num162 = vector.Y - vector38.Y;
                        if (num167 > (float)(TextureAssets.Chain40.Height() * 2))
{
                            for (int num168 = 0; num168 < 2; num168++)
{
                                float num169 = 0.75f;
                                float num170;
                                if (num168 == 0)
{
                                    num170 = Math.Abs(player.velocity.X);
                                }
                                else
{
                                    num170 = Math.Abs(player.velocity.Y);
                                }
                                if (num170 > 10f)
{
                                    num170 = 10f;
                                }
                                num170 /= 10f;
                                num169 *= num170;
                                num170 = num167 / 80f;
                                if (num170 > 1f)
{
                                    num170 = 1f;
                                }
                                num169 *= num170;
                                if (num169 < 0f)
{
                                    num169 = 0f;
                                }
                                if (!float.IsNaN(num169))
{
                                    if (num168 == 0)
{
                                        if (player.velocity.X < 0f && proj.Center.X < vector.X)
{
                                            num162 *= 1f - num169;
                                        }
                                        if (player.velocity.X > 0f && proj.Center.X > vector.X)
{
                                            num162 *= 1f - num169;
                                        }
                                    }
                                    else
{
                                        if (player.velocity.Y < 0f && proj.Center.Y < vector.Y)
{
                                            num161 *= 1f - num169;
                                        }
                                        if (player.velocity.Y > 0f && proj.Center.Y > vector.Y)
{
                                            num161 *= 1f - num169;
                                        }
                                    }
                                }
                            }
                        }
                        Microsoft.Xna.Framework.Color color33 = Lighting.GetColor((int)vector38.X / 16, (int)(vector38.Y / 16f));
                        Main.EntitySpriteDraw(TextureAssets.Chain40.Value, new Vector2(vector38.X - Main.screenPosition.X, vector38.Y - Main.screenPosition.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain40.Width(), TextureAssets.Chain40.Height())), color33, num164, new Vector2((float)TextureAssets.Chain40.Width() * 0.5f, (float)TextureAssets.Chain40.Height() * 0.5f), num165, SpriteEffects.None, 0f);
                    }
                }
            }
            else if (proj.type == 271)
            {
                float num171 = proj.Center.X;
                float num172 = proj.Center.Y;
                float num173 = proj.velocity.X;
                float num174 = proj.velocity.Y;
                float num175 = (float)Math.Sqrt((double)(num173 * num173 + num174 * num174));
                num175 = 4f / num175;
                if (proj.ai[0] == 0f)
                {
                    num171 -= proj.velocity.X * num175;
                    num172 -= proj.velocity.Y * num175;
                }
                else
                {
                    num171 += proj.velocity.X * num175;
                    num172 += proj.velocity.Y * num175;
                }
                Vector2 vector39 = new Vector2(num171, num172);
                num173 = vector.X - vector39.X;
                num174 = vector.Y - vector39.Y;
                float num176 = (float)Math.Atan2((double)num174, (double)num173) - 1.57f;
                bool flag25 = true;
                while (flag25)
                {
                    float num177 = (float)Math.Sqrt((double)(num173 * num173 + num174 * num174));
                    if (num177 < 25f)
                    {
                        flag25 = false;
                    }
                    else if (float.IsNaN(num177))
                    {
                        flag25 = false;
                    }
                    else
                    {
                        num177 = 12f / num177;
                        num173 *= num177;
                        num174 *= num177;
                        vector39.X += num173;
                        vector39.Y += num174;
                        num173 = vector.X - vector39.X;
                        num174 = vector.Y - vector39.Y;
                        Microsoft.Xna.Framework.Color color34 = Lighting.GetColor((int)vector39.X / 16, (int)(vector39.Y / 16f));
                        Main.EntitySpriteDraw(TextureAssets.Chain18.Value, new Vector2(vector39.X - Main.screenPosition.X, vector39.Y - Main.screenPosition.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain18.Width(), TextureAssets.Chain18.Height())), color34, num176, new Vector2((float)TextureAssets.Chain18.Width() * 0.5f, (float)TextureAssets.Chain18.Height() * 0.5f), 1f, SpriteEffects.None, 0f);
                    }
                }
            }
            else if (proj.aiStyle == 13)
            {
                float num178 = proj.position.X + 8f;
                float num179 = proj.position.Y + 2f;
                float num180 = proj.velocity.X;
                float num181 = proj.velocity.Y;
                if (num180 == 0f && num181 == 0f)
                {
                    num181 = 0.0001f;
                }
                float num182 = (float)Math.Sqrt((double)(num180 * num180 + num181 * num181));
                if (proj.type == 23)
                {
                    num182 = 40f / num182;
                }
                else
                {
                    num182 = 20f / num182;
                }
                if (proj.ai[0] == 0f)
                {
                    num178 -= proj.velocity.X * num182;
                    num179 -= proj.velocity.Y * num182;
                }
                else
                {
                    num178 += proj.velocity.X * num182;
                    num179 += proj.velocity.Y * num182;
                }
                Vector2 vector40 = new Vector2(num178, num179);
                if (proj.type == 23)
                {
                    if (proj.ai[0] == 0f)
                    {
                        proj.localAI[1] = (-proj.velocity.X + proj.localAI[1]) / 2f;
                        proj.localAI[2] = (-proj.velocity.Y + proj.localAI[2]) / 2f;
                    }
                    else
                    {
                        proj.localAI[1] = (proj.velocity.X + proj.localAI[1] * 4f) / 5f;
                        proj.localAI[2] = (proj.velocity.Y + proj.localAI[2] * 4f) / 5f;
                    }
                }
                if (proj.type == 23)
                {
                    Vector2 vector41 = vector40 - vector;
                    if (vector41.Length() > 20f)
                    {
                        vector41.Normalize();
                        vector41 *= 20f;
                        vector.X += vector41.X;
                        vector.Y += vector41.Y;
                    }
                    num180 = vector.X - vector40.X;
                    num181 = vector.Y - vector40.Y;
                    float num183 = (float)Math.Sqrt((double)(num180 * num180 + num181 * num181));
                    num183 = 12f / num183;
                    num180 *= num183;
                    num181 *= num183;
                    vector40.X -= num180 / 2f;
                    vector40.Y -= num181 / 2f;
                }
                num180 = vector.X - vector40.X;
                num181 = vector.Y - vector40.Y;
                float num184 = (float)Math.Atan2((double)num181, (double)num180) - 1.57f;
                bool flag26 = true;
                while (flag26)
                {
                    float num185 = (float)Math.Sqrt((double)(num180 * num180 + num181 * num181));
                    if (num185 < 25f)
                    {
                        flag26 = false;
                    }
                    else if (float.IsNaN(num185))
                    {
                        flag26 = false;
                    }
                    else
                    {
                        float num186 = num185;
                        num185 = 12f / num185;
                        num180 *= num185;
                        num181 *= num185;
                        vector40.X += num180;
                        vector40.Y += num181;
                        num180 = vector.X - vector40.X;
                        num181 = vector.Y - vector40.Y;
                        if (proj.type == 23 && num186 > 12f)
{
                            float num187 = num186 / 1000f;
                            if ((double)num187 > 0.5)
{
                                num187 = 0.5f;
                            }
                            Vector2 vector42 = vector - vector40;
                            Vector2 vector43 = new Vector2(proj.localAI[1], proj.localAI[2]);
                            float num188 = vector42.Length();
                            vector42.Normalize();
                            vector43.Normalize();
                            vector42 *= num188;
                            vector43 *= num188;
                            num180 = vector42.X * (1f - num187) + vector43.X * num187;
                            num181 = vector42.Y * (1f - num187) + vector43.Y * num187;
                            num184 = (float)Math.Atan2((double)num181, (double)num180) - 1.57f;
                        }
                        Microsoft.Xna.Framework.Color color35 = Lighting.GetColor((int)vector40.X / 16, (int)(vector40.Y / 16f));
                        Main.EntitySpriteDraw(TextureAssets.Chain.Value, new Vector2(vector40.X - Main.screenPosition.X, vector40.Y - Main.screenPosition.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain.Width(), TextureAssets.Chain.Height())), color35, num184, new Vector2((float)TextureAssets.Chain.Width() * 0.5f, (float)TextureAssets.Chain.Height() * 0.5f), 1f, SpriteEffects.None, 0f);
                    }
                }
            }
            else if (proj.aiStyle == 15)
            {
                Main.DrawProj_FlailChains(proj, player, vector);
            }
            Microsoft.Xna.Framework.Color color36 = Lighting.GetColor((int)((double)proj.position.X + (double)proj.width * 0.5) / 16, (int)(((double)proj.position.Y + (double)proj.height * 0.5) / 16.0));
            if (proj.usesOwnerLight)
            {
                color36 = Lighting.GetColor((int)vector.X / 16, (int)(vector.Y / 16f));
            }
            if (proj.type == 14)
            {
                color36 = Microsoft.Xna.Framework.Color.White;
            }
            int num189 = 0;
            int num190 = 0;
            if (proj.type == 1022)
            {
                num189++;
            }
            if (proj.type == 175)
            {
                num189 = 10;
            }
            if (proj.type == 392)
            {
                num189 = -2;
            }
            if (proj.type == 1036)
            {
                num189 = -4;
            }
            if (proj.type == 1025)
            {
                num189 = 22;
            }
            if (proj.type == 499)
            {
                num189 = 12;
            }
            if (proj.type == 765)
            {
                num189 = 22;
                num190 = -16;
            }
            if (proj.type == 966)
            {
                num189 = -26;
                num190 = -6;
            }
            if (proj.bobber)
            {
                num189 = 8;
            }
            if (proj.type == 519)
            {
                num189 = 6;
                num190 -= 6;
            }
            if (proj.type == 520)
            {
                num189 = 12;
            }
            if (proj.type == 492)
            {
                num190 -= 4;
                num189 += 5;
            }
            if (proj.type == 498)
            {
                num189 = 6;
            }
            if (proj.type == 489)
            {
                num189 = -2;
            }
            if (proj.type == 486)
            {
                num189 = -6;
            }
            if (proj.type == 525)
            {
                num189 = 5;
            }
            if (proj.type == 488)
            {
                num190 -= 8;
            }
            if (proj.type == 373)
            {
                num190 = -10;
                num189 = 6;
            }
            if (proj.type == 375)
            {
                num190 = -11;
                num189 = 12;
            }
            if (proj.type == 423)
            {
                num190 = -5;
            }
            if (proj.type == 346)
            {
                num189 = 4;
            }
            if (proj.type == 331)
            {
                num190 = -4;
            }
            if (proj.type == 254)
            {
                num189 = 3;
            }
            if (proj.type == 273)
            {
                num190 = 2;
            }
            if (proj.type == 335)
            {
                num189 = 6;
            }
            if (proj.type == 162)
            {
                num189 = 1;
                num190 = 1;
            }
            if (proj.type == 377)
            {
                num189 = -6;
            }
            if (proj.type == 353)
            {
                num189 = 36;
                num190 = -12;
            }
            if (proj.type == 324)
            {
                num189 = 22;
                num190 = -6;
            }
            if (proj.type == 266)
            {
                num189 = 6;
                num190 = -13;
            }
            if (proj.type == 319)
            {
                num189 = 10;
                num190 = -12;
            }
            if (proj.type == 315)
            {
                num189 = -13;
                num190 = -6;
            }
            if (proj.type == 313 && proj.height != 54)
            {
                num190 = -12;
                num189 = 20;
            }
            if (proj.type == 314)
            {
                num190 = -8;
                num189 = 0;
            }
            if (proj.type == 269)
            {
                num189 = 18;
                num190 = -14;
            }
            if (proj.type == 268)
            {
                num189 = 22;
                num190 = -2;
            }
            if (proj.type == 18)
            {
                num189 = 3;
                num190 = 3;
            }
            if (proj.type == 16)
            {
                num189 = 6;
            }
            if (proj.type == 17 || proj.type == 31)
            {
                num189 = 2;
            }
            if (proj.type == 25 || proj.type == 26 || proj.type == 35 || proj.type == 63 || proj.type == 154)
            {
                num189 = 6;
                num190 -= 6;
            }
            if (proj.type == 947 || proj.type == 948)
            {
                num189 = 4;
                num190 -= 4;
            }
            if (proj.type == 28 || proj.type == 37 || proj.type == 75 || proj.type == 1077)
            {
                num189 = 8;
            }
            if (proj.type == 29 || proj.type == 470 || proj.type == 637)
            {
                num189 = 11;
            }
            if (proj.type == 43)
            {
                num189 = 4;
            }
            if (proj.type == 208)
            {
                num189 = 2;
                num190 -= 12;
            }
            if (proj.type == 209)
            {
                num189 = 4;
                num190 -= 8;
            }
            if (proj.type == 210)
            {
                num189 = 2;
                num190 -= 22;
            }
            if (proj.type == 251)
            {
                num189 = 18;
                num190 -= 10;
            }
            if (proj.type == 163 || proj.type == 310 || proj.type == 1009 || proj.type == 1010 || proj.type == 1011 || proj.type == 1008)
            {
                num189 = 10;
            }
            if (proj.type == 69 || proj.type == 70)
            {
                num189 = 4;
                num190 = 4;
            }
            float num191 = (float)(TextureAssets.Projectile[proj.type].Width() - proj.width) * 0.5f + (float)proj.width * 0.5f;
            if (proj.type == 50 || proj.type == 53 || proj.type == 515 || proj.type == 870)
            {
                num190 = -8;
            }
            if (proj.type == 473)
            {
                num190 = -6;
                num189 = 2;
            }
            if (proj.type == 72 || proj.type == 86 || proj.type == 87)
            {
                num190 = -16;
                num189 = 8;
            }
            if (proj.type == 74)
            {
                num190 = -6;
            }
            if (proj.type == 99 || proj.type == 727 || proj.type == 1013 || proj.type == 1014 || proj.type == 1047 || proj.type == 1048 || proj.type == 1053 || proj.type == 1054 || proj.type == 1055 || proj.type == 1057)
            {
                num189 = 1;
            }
            if (proj.type == 655)
            {
                num189 = 1;
            }
            if (proj.type == 111)
            {
                num189 = 18;
                num190 = -16;
            }
            if (proj.type == 875)
            {
                num189 = 16;
                num190 = -16;
            }
            if (proj.type == 881)
            {
                num189 = 14;
                num190 = -8;
            }
            if (proj.type == 934)
            {
                num189 = 14;
                num190 = -20;
            }
            if (proj.type == 934)
            {
                num189 = 14;
                num190 = -20;
            }
            if (proj.type == 884)
            {
                num189 = 16;
                num190 = -12;
            }
            if (proj.type == 890)
            {
                num189 = 26;
                num190 = -9;
            }
            if (proj.type == 891)
            {
                num189 = 30;
                num190 = -12;
            }
            if (proj.type == 897)
            {
                num189 = 38;
                num190 = -13;
            }
            if (proj.type == 899)
            {
                num189 = 28;
                num190 = -12;
            }
            if (proj.type == 900)
            {
                num189 = 54;
                num190 = -30;
            }
            if (proj.type == 334)
            {
                num190 = -18;
                num189 = 8;
            }
            if (proj.type == 816)
            {
                num190 = -19;
                num189 = 6;
            }
            if (proj.type == 821)
            {
                num190 = -10;
                num189 = 6;
            }
            if (proj.type == 825)
            {
                num190 = -19;
                num189 = 14;
            }
            if (proj.type == 854)
            {
                num190 = -14;
                num189 = 10;
            }
            if (proj.type == 858)
            {
                num190 = -8;
                num189 = 16;
            }
            if (proj.type == 859)
            {
                num190 = -8;
                num189 = 8;
            }
            if (proj.type == 860)
            {
                num190 = -8;
                num189 = 34;
            }
            if (proj.type == 958)
            {
                num190 = -20;
                num189 = 48;
            }
            if (proj.type == 960)
            {
                num190 = -14;
                num189 = 24;
            }
            if (proj.type == 956)
            {
                num190 = -12;
                num189 = 16;
            }
            if (proj.type == 959)
            {
                num190 = -14 + ((proj.spriteDirection == -1) ? (-8) : 0);
                num189 = 40;
            }
            if (proj.type == 1095 || proj.type == 1096)
            {
                num190 = -14 + ((proj.spriteDirection == -1) ? (-8) : 0);
                num189 = 40;
            }
            if (proj.type == 994)
            {
                num190 = -10;
                num189 = 18;
            }
            if (proj.type == 998)
            {
                num190 = -10;
                num189 = 14;
            }
            if (proj.type == 1003)
            {
                num190 = -18 + ((proj.spriteDirection == 1) ? 8 : 0);
                num189 = 22;
            }
            if (proj.type == 1004)
            {
                num190 = -18 + ((proj.spriteDirection == 1) ? 6 : 0);
                num189 = 26;
            }
            if (proj.type == 1027)
            {
                num190 = -6;
                num189 = 4;
            }
            if (proj.type == 200)
            {
                num189 = 12;
                num190 = -12;
            }
            if (proj.type == 211)
            {
                num189 = 14;
                num190 = 0;
            }
            if (proj.type == 236)
            {
                num189 = 30;
                num190 = -14;
            }
            if (proj.type >= 191 && proj.type <= 194)
            {
                num189 = 26;
                if (proj.direction == 1)
                {
                    num190 = -10;
                }
                else
                {
                    num190 = -22;
                }
            }
            if (proj.type >= 390 && proj.type <= 392)
            {
                num190 = 4 * proj.direction;
            }
            if (proj.type == 112)
            {
                num189 = 14;
                num190 = -8 + 4 * proj.spriteDirection;
            }
            int type = proj.type;
            if (proj.type == 517 || proj.type == 681)
            {
                num189 = 6;
            }
            if (proj.type == 516)
            {
                num189 = 6;
            }
            if (proj.type == 127)
            {
                num189 = 8;
            }
            if (proj.type == 155)
            {
                num189 = 3;
                num190 = 3;
            }
            if (proj.type == 397)
            {
                num191 -= 1f;
                num189 = -2;
                num190 = -2;
            }
            SpriteEffects spriteEffects2 = SpriteEffects.None;
            if (proj.spriteDirection == -1)
            {
                spriteEffects2 = SpriteEffects.FlipHorizontally;
            }
            if (proj.type == 681 && proj.velocity.X > 0f)
            {
                spriteEffects2 ^= SpriteEffects.FlipHorizontally;
            }
            if (proj.type == 221)
            {
                for (int num192 = 1; num192 < 10; num192++)
                {
                    float num193 = proj.velocity.X * (float)num192 * 0.5f;
                    float num194 = proj.velocity.Y * (float)num192 * 0.5f;
                    Microsoft.Xna.Framework.Color alpha = proj.GetAlpha(color36);
                    float num195 = 0f;
                    if (num192 == 1)
                    {
                        num195 = 0.9f;
                    }
                    if (num192 == 2)
                    {
                        num195 = 0.8f;
                    }
                    if (num192 == 3)
                    {
                        num195 = 0.7f;
                    }
                    if (num192 == 4)
                    {
                        num195 = 0.6f;
                    }
                    if (num192 == 5)
                    {
                        num195 = 0.5f;
                    }
                    if (num192 == 6)
                    {
                        num195 = 0.4f;
                    }
                    if (num192 == 7)
                    {
                        num195 = 0.3f;
                    }
                    if (num192 == 8)
                    {
                        num195 = 0.2f;
                    }
                    if (num192 == 9)
                    {
                        num195 = 0.1f;
                    }
                    alpha.R = (byte)((float)alpha.R * num195);
                    alpha.G = (byte)((float)alpha.G * num195);
                    alpha.B = (byte)((float)alpha.B * num195);
                    alpha.A = (byte)((float)alpha.A * num195);
                    int num196 = TextureAssets.Projectile[proj.type].Height() / Main.projFrames[proj.type];
                    int num197 = num196 * proj.frame;
                    Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - Main.screenPosition.X + num191 + (float)num190 - num193, proj.position.Y - Main.screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY - num194), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, num197, TextureAssets.Projectile[proj.type].Width(), num196)), alpha, proj.rotation, new Vector2(num191, (float)(proj.height / 2 + num189)), proj.scale, spriteEffects2, 0f);
                }
            }
            if (proj.type == 408 || proj.type == 435 || proj.type == 436 || proj.type == 438 || proj.type == 452 || proj.type == 454 || proj.type == 459 || proj.type == 462 || proj.type == 503 || proj.type == 532 || proj.type == 533 || proj.type == 573 || proj.type == 582 || proj.type == 585 || proj.type == 592 || proj.type == 601 || proj.type == 636 || proj.type == 638 || proj.type == 640 || proj.type == 639 || proj.type == 424 || proj.type == 425 || proj.type == 426 || proj.type == 1037 || proj.type == 1049 || proj.type == 660 || proj.type == 661 || proj.type == 671 || proj.type == 664 || proj.type == 666 || proj.type == 668 || proj.type == 675 || proj.type == 680 || proj.type == 682 || proj.type == 684 || proj.type == 686 || proj.type == 700 || proj.type == 706 || proj.type == 709 || proj.type == 710 || proj.type == 711 || proj.type == 261 || ProjectileID.Sets.IsAGolfBall[proj.type] || proj.type == 729 || proj.type == 732 || proj.type == 731 || proj.type == 755 || proj.type == 811 || proj.type == 814 || proj.type == 819 || proj.type == 864 || proj.type == 873 || proj.type == 872 || proj.type == 833 || proj.type == 834 || proj.type == 835 || proj.type == 818 || proj.type == 902 || proj.type == 894 || proj.type == 901 || proj.type == 909 || proj.type == 916 || proj.type == 931 || proj.type == 933 || proj.type == 1100 || proj.type == 964 || proj.type == 965 || proj.type == 977 || proj.type == 976 || proj.type == 1001 || proj.type == 1039 || proj.type == 1026 || proj.type == 1045 || proj.type == 1055 || proj.type == 1097)
            {
                Texture2D texture2D3 = TextureAssets.Projectile[proj.type].Value;
                int num198 = TextureAssets.Projectile[proj.type].Height() / Main.projFrames[proj.type];
                int num199 = num198 * proj.frame;
                Microsoft.Xna.Framework.Rectangle rectangle6 = new Microsoft.Xna.Framework.Rectangle(0, num199, texture2D3.Width, num198);
                Vector2 vector44 = rectangle6.Size() / 2f;
                Vector2 zero = Vector2.Zero;
                float num200 = 0f;
                if (proj.type == 503)
                {
                    vector44.Y = 70f;
                }
                if (proj.type == 686 || proj.type == 711 || proj.type == 1097)
                {
                    vector44.Y = (float)(rectangle6.Height - 70);
                }
                if (proj.type == 438)
                {
                    rectangle6.Y = 0;
                }
                if (proj.type == 452)
                {
                    rectangle6.Y = 0;
                }
                if (proj.type == 408)
                {
                    rectangle6.Y = num198;
                }
                if (proj.type == 636)
                {
                    vector44.Y = 10f;
                }
                if (proj.type == 638)
                {
                    vector44.Y = 2f;
                }
                if (proj.type == 640 || proj.type == 639 || proj.type == 710)
                {
                    vector44.Y = 5f;
                }
                if (proj.type == 700)
                {
                    vector44.X = (float)((proj.spriteDirection == 1) ? (rectangle6.Width - 20) : 20);
                }
                if (proj.type == 965 || proj.type == 964)
                {
                    vector44.X = (float)((proj.spriteDirection == 1) ? (rectangle6.Width - 20) : 20);
                }
                if (proj.type == 872)
                {
                    rectangle6.Width /= 2;
                    vector44.X /= 2f;
                }
                if (proj.type == 933 || proj.type == 1100)
                {
                    int num201 = (int)proj.ai[1];
                    if (TextureAssets.Item.IndexInRange(num201))
                    {
                        Main.instance.LoadItem(num201);
                        texture2D3 = TextureAssets.Item[num201].Value;
                        rectangle6 = texture2D3.Frame(1, 1, 0, 0, 0, 0);
                        vector44 = rectangle6.Size() / 2f;
                        num200 = -0.7853982f * (float)proj.spriteDirection;
                    }
                }
                if (proj.type == 833 && proj.frame != 8)
                {
                    zero.Y += (float)(proj.height / 2);
                    vector44 = rectangle6.Size() * new Vector2(0.5f, 1f);
                    vector44.Y -= 4f;
                    vector44.X -= (float)(7 * ((spriteEffects2 & SpriteEffects.FlipHorizontally) > SpriteEffects.None).ToDirectionInt());
                }
                if ((proj.type == 834 || proj.type == 835) && proj.frame != 10)
                {
                    zero.Y += (float)(proj.height / 2);
                    vector44 = rectangle6.Size() * new Vector2(0.5f, 1f);
                    vector44.Y -= 4f;
                    vector44.X -= (float)(2 * ((spriteEffects2 & SpriteEffects.FlipHorizontally) > SpriteEffects.None).ToDirectionInt());
                }
                int num202 = 8;
                int num203 = 2;
                int num204 = 1;
                float num205 = 1f;
                float num206 = 15f;
                float num207 = 0f;
                Microsoft.Xna.Framework.Rectangle rectangle7 = rectangle6;
                UnifiedRandom unifiedRandom = null;
                if (proj.type == 1055)
                {
                    num203 = 1;
                    num202 = proj.frame;
                    if (proj.frame == 8)
                    {
                        num202--;
                    }
                    if (proj.frame == 9)
                    {
                        num202 -= 2;
                    }
                }
                if (proj.type == 1026)
                {
                    num204 = 8;
                    num202 = 0;
                    num203 = -2;
                    num205 = 0.5f;
                }
                else if (proj.type == 909)
                {
                    num204 = 5;
                    num202 = 0;
                    num203 = -1;
                }
                else if (proj.type == 503)
                {
                    num202 = 9;
                    num203 = 3;
                    num205 = 0.5f;
                }
                else if (proj.type == 261)
                {
                    num204 = 18;
                    num202 = 0;
                    num203 = -2;
                    num205 = 1.3f;
                }
                else if (proj.type == 833 || proj.type == 834 || proj.type == 835)
                {
                    num204 = 6;
                    num202 = 0;
                    num203 = -1;
                    num205 = 1.5f;
                }
                else if (proj.type == 818)
                {
                    num204 = 18;
                    num202 = 0;
                    num203 = -2;
                    num205 = 1f;
                }
                else if (proj.type == 729)
                {
                    num204 = 18;
                    num202 = 0;
                    num203 = -2;
                    num205 = 1.3f;
                }
                else if (proj.type == 977)
                {
                    num204 = 18;
                    num202 = 0;
                    num203 = -2;
                    num205 = 1.3f;
                }
                else if (proj.type == 1045)
                {
                    num204 = 18;
                    num202 = 0;
                    num203 = -2;
                    num205 = 1.3f;
                }
                else if (proj.type == 1001)
                {
                    num204 = 10;
                    num202 = 0;
                    num203 = -2;
                    num205 = 1.3f;
                    spriteEffects2 = ((proj.spriteDirection == 1) ? SpriteEffects.None : SpriteEffects.FlipVertically);
                }
                else if (proj.type == 976)
                {
                    num204 = 18;
                    num202 = 0;
                    num203 = -3;
                    num205 = 1.3f;
                    rectangle6 = new Microsoft.Xna.Framework.Rectangle(0, 20 * proj.frame, 32, 18);
                    rectangle7 = rectangle6;
                    vector44 = rectangle6.Size() / 2f;
                }
                else if (proj.type == 686 || proj.type == 711 || proj.type == 1097)
                {
                    num204 = 19;
                    num202 = 0;
                    num203 = -3;
                    num205 = 0.5f;
                }
                else if (ProjectileID.Sets.IsAGolfBall[proj.type])
                {
                    num204 = 0;
                    num202 = 0;
                    num203 = -1;
                    num205 = 2f;
                }
                else if (proj.type == 671)
                {
                    num204 = 5;
                    num202 = 0;
                    num203 = -1;
                    num205 = 2.6f;
                }
                else if (proj.type == 811)
                {
                    num204 = 5;
                    num202 = 0;
                    num203 = -1;
                    num205 = 2.6f;
                    color36 = Microsoft.Xna.Framework.Color.Lerp(color36, Microsoft.Xna.Framework.Color.White, Utils.Remap(proj.ai[0], 0f, 15f, 1f, 0.3f, true));
                }
                else if (proj.type == 814)
                {
                    num204 = 18;
                    num202 = 0;
                    num203 = -1;
                    num205 = 1f;
                    color36 = Microsoft.Xna.Framework.Color.Lerp(color36, Microsoft.Xna.Framework.Color.White, 0.35f);
                }
                else if (proj.type == 755)
                {
                    num204 = 5;
                    num202 = 0;
                    num203 = -1;
                    num205 = 2.6f;
                }
                else if (proj.type == 700)
                {
                    num202 = 5;
                    num203 = 1;
                    num205 = 2.6f;
                }
                else if (proj.type == 965 || proj.type == 964)
                {
                    num202 = 5;
                    num203 = 1;
                    num205 = 2.6f;
                }
                else if (proj.type == 731)
                {
                    num204 = 19;
                    num202 = 0;
                    num203 = -1;
                    num205 = 0.5f;
                }
                else if (proj.type == 864)
                {
                    num204 = 12;
                    num202 = 0;
                    num203 = -1;
                    num205 = 1.4f;
                    rectangle7.Y += rectangle7.Height;
                }
                else if (proj.type == 916)
                {
                    num204 = 19;
                    num202 = 0;
                    num203 = -1;
                    num205 = 1.4f;
                    rectangle7.Y += rectangle7.Height;
                    unifiedRandom = Main._tempSeededRandom;
                    unifiedRandom.SetSeed(proj.timeLeft);
                }
                else if (proj.type == 873)
                {
                    num204 = 39;
                    num206 = 40f;
                    num202 = 0;
                    num203 = -1;
                    num205 = 1.4f;
                }
                else if (proj.type == 931)
                {
                    num204 = 19;
                    num206 = 20f;
                    num202 = 0;
                    num203 = -1;
                    num205 = 0.7f;
                }
                else if (proj.type == 1039)
                {
                    num204 = 19;
                    num206 = 20f;
                    num202 = 0;
                    num203 = -1;
                    num205 = 0.7f;
                }
                else if (proj.type == 933 || proj.type == 1100)
                {
                    num204 = 60;
                    num206 = 60f;
                    num202 = 0;
                    num203 = -15;
                    num205 = 1f;
                }
                else if (proj.type == 872)
                {
                    num204 = 79;
                    num206 = 10f;
                    num202 = 0;
                    num203 = -1;
                    num205 = 1f;
                    rectangle7.X += rectangle7.Width;
                }
                else if (proj.type == 664 || proj.type == 666 || proj.type == 668)
                {
                    num202 = 8;
                    num203 = 2;
                    num205 = 0.4f;
                }
                else if (proj.type == 582 || proj.type == 902)
                {
                    if (proj.ai[2] == 1f)
                    {
                        texture2D3 = TextureAssets.Extra[263].Value;
                    }
                    num202 = 10;
                    num203 = 2;
                    num205 = 0.7f;
                    num207 = 0.2f;
                }
                else if (proj.type == 675)
                {
                    num202 = 5;
                    num203 = 1;
                    num205 = 0.4f;
                }
                else if (proj.type == 638)
                {
                    num202 = 5;
                    num203 = 1;
                    num205 = 1f;
                }
                else if (proj.type == 660)
                {
                    num202 = 3;
                    num203 = 1;
                    num205 = 8f;
                    rectangle6 = new Microsoft.Xna.Framework.Rectangle(38 * proj.frame, 0, 38, 38);
                    rectangle7 = rectangle6;
                    vector44 = rectangle6.Size() / 2f;
                }
                else if (proj.type == 684)
                {
                    num202 = 8;
                    num203 = 1;
                    num205 = 0.75f;
                }
                else if (proj.type == 639)
                {
                    num202 = 10;
                    num203 = 1;
                    num205 = 1f;
                }
                else if (proj.type == 710)
                {
                    num204 = 9;
                    num202 = 0;
                    num203 = -2;
                    num205 = 0.5f;
                }
                else if (proj.type == 640)
                {
                    num202 = 20;
                    num203 = 1;
                    num205 = 1f;
                }
                else if (proj.type == 436)
                {
                    num203 = 2;
                    num205 = 0.5f;
                }
                else if (proj.type == 424 || proj.type == 425 || proj.type == 426)
                {
                    num202 = 10;
                    num203 = 2;
                    num205 = 0.6f;
                }
                else if (proj.type == 1037 || proj.type == 1049)
                {
                    num202 = 10;
                    num203 = 2;
                    num205 = 0.6f;
                }
                else if (proj.type == 438)
                {
                    num202 = 10;
                    num203 = 2;
                    num205 = 1f;
                }
                else if (proj.type == 452)
                {
                    num202 = 10;
                    num203 = 3;
                    num205 = 0.5f;
                }
                else if (proj.type == 454)
                {
                    num202 = 5;
                    num203 = 1;
                    num205 = 0.2f;
                }
                else if (proj.type == 462)
                {
                    num202 = 7;
                    num203 = 1;
                    num205 = 0.2f;
                }
                else if (proj.type == 661)
                {
                    num202 = 0;
                    num203 = 1;
                    num205 = 0.5f;
                }
                else if (proj.type == 706)
                {
                    num204 = 9;
                    num202 = 0;
                    num203 = -2;
                    num205 = 0.5f;
                }
                else if (proj.type == 585)
                {
                    num202 = 7;
                    num203 = 1;
                    num205 = 0.2f;
                }
                else if (proj.type == 459)
                {
                    num202 = (int)(proj.scale * 8f);
                    num203 = num202 / 4;
                    if (num203 < 1)
                    {
                        num203 = 1;
                    }
                    num205 = 0.3f;
                }
                else if (proj.type == 709)
                {
                    num202 = 8;
                    num203 = num202 / 4;
                    if (num203 < 1)
                    {
                        num203 = 1;
                    }
                    num205 = 0.5f;
                }
                else if (proj.type == 532)
                {
                    num202 = 10;
                    num203 = 1;
                    num205 = 0.7f;
                    num207 = 0.2f;
                }
                else if (proj.type == 592)
                {
                    num202 = 10;
                    num203 = 2;
                    num205 = 1f;
                }
                else if (proj.type == 601)
                {
                    num202 = 8;
                    num203 = 1;
                    num205 = 0.3f;
                }
                else if (proj.type == 636)
                {
                    num202 = 20;
                    num203 = 3;
                    num205 = 0.5f;
                }
                else if (proj.type == 680)
                {
                    num202 = 9;
                    num203 = 3;
                    num205 = 0.5f;
                }
                else if (proj.type == 533)
                {
                    if (proj.ai[0] >= 6f && proj.ai[0] <= 8f)
                    {
                        num202 = ((proj.ai[0] == 6f) ? 8 : 4);
                        num203 = 1;
                        if (proj.ai[0] != 7f)
{
                            num207 = 0.2f;
                        }
                    }
                    else
                    {
                        num203 = (num202 = 0);
                    }
                }
                int num208 = num204;
                while ((num203 > 0 && num208 < num202) || (num203 < 0 && num208 > num202))
                {
                    if (num208 < proj.oldPos.Length)
                    {
                        Microsoft.Xna.Framework.Color color37 = color36;
                        if (proj.type == 408 || proj.type == 435 || proj.type == 682 || proj.type == 732 || proj.type == 731 || proj.type == 1026)
{
                            color37 = Microsoft.Xna.Framework.Color.Lerp(color37, Microsoft.Xna.Framework.Color.Blue, 0.5f);
                        }
                        else if (proj.type == 436)
{
                            color37 = Microsoft.Xna.Framework.Color.Lerp(color37, Microsoft.Xna.Framework.Color.LimeGreen, 0.5f);
                        }
                        else if (proj.type >= 424 && proj.type <= 426)
{
                            color37 = Microsoft.Xna.Framework.Color.Lerp(color37, Microsoft.Xna.Framework.Color.Red, 0.5f);
                        }
                        else if (proj.type == 1037 || proj.type == 1049)
{
                            color37 = Microsoft.Xna.Framework.Color.Lerp(color37, Microsoft.Xna.Framework.Color.Red, 0.5f);
                        }
                        else if (proj.type == 640 || proj.type == 639)
{
                            color37.A = 127;
                        }
                        else if (proj.type == 671)
{
                            color37 = Microsoft.Xna.Framework.Color.Lerp(color37, Microsoft.Xna.Framework.Color.Purple, (float)num208 / (float)num202);
                        }
                        else if (proj.type == 811)
{
                            color37 = Microsoft.Xna.Framework.Color.Lerp(color37, Microsoft.Xna.Framework.Color.Crimson * 0.5f, (float)num208 / (float)num202);
                        }
                        else if (proj.type == 814)
{
                            color37 = Microsoft.Xna.Framework.Color.Lerp(color37, color37 * 0.5f, (float)num208 / (float)num202);
                        }
                        else if (proj.type == 261)
{
                            color37 = Microsoft.Xna.Framework.Color.Lerp(color37, new Microsoft.Xna.Framework.Color(60, 60, 60, 60), (float)num208 / (float)num202);
                        }
                        else if (ProjectileID.Sets.IsAGolfBall[proj.type])
{
                            color37 = Microsoft.Xna.Framework.Color.Lerp(color37, new Microsoft.Xna.Framework.Color(255, 230, 40, 20), (float)num208 / (float)num202);
                        }
                        color37 = proj.GetAlpha(color37);
                        if (proj.type == 438)
{
                            color37.G /= (byte)num208;
                            color37.B /= (byte)num208;
                        }
                        else if (proj.type == 755)
{
                            color37 = proj.AI_156_GetColor();
                        }
                        else if (proj.type == 873)
{
                            color37 = proj.AI_171_GetColor();
                            color37.A /= 2;
                            color37 *= Utils.GetLerpValue(0f, 20f, (float)proj.timeLeft, true);
                        }
                        else if (proj.type == 931)
{
                            float num209 = 0.5f;
                            float num210 = 0f;
                            float? num211 = null;
                            color37 = proj.GetFairyQueenWeaponsColor(num209, num210, num211);
                            color37 *= Utils.GetLerpValue(0f, 20f, (float)proj.timeLeft, true);
                        }
                        else if (proj.type == 1039)
{
                            float num212 = 0.5f;
                            float num213 = 0f;
                            float? num211 = null;
                            color37 = proj.GetConstellationColor(num212, num213, num211);
                            color37 *= Utils.GetLerpValue(0f, 20f, (float)proj.timeLeft, true);
                        }
                        else if (proj.type == 872)
{
                            color37 = proj.AI_173_GetColor();
                            color37 *= 0.4f;
                            color37.A = (byte)((float)color37.A * 0.6f);
                            if (num208 > 80)
{
                                color37 *= 0.15f * Utils.GetLerpValue(120f, 80f, (float)num208, true);
                            }
                        }
                        else if (proj.type == 864)
{
                            color37 = proj.GetFloatingDaggerMinionGlowColor();
                            color37.A /= 4;
                        }
                        else if (proj.type == 682)
{
                            color37.G /= (byte)num208;
                        }
                        else if (proj.type == 686)
{
                            if (proj.oldPos[num208] == Vector2.Zero)
{
                                goto IL_8BF3;
                            }
                            float num214 = (float)num208 / (float)num204;
                            if (num214 < 0.5f)
{
                                color37 = Microsoft.Xna.Framework.Color.Lerp(color37, Microsoft.Xna.Framework.Color.Purple, Utils.GetLerpValue(0f, 0.5f, num214, false));
                            }
                            else
{
                                color37 = Microsoft.Xna.Framework.Color.Lerp(Microsoft.Xna.Framework.Color.Purple, Microsoft.Xna.Framework.Color.Black, Utils.GetLerpValue(0.5f, 1f, num214, false));
                            }
                        }
                        else if (proj.type == 1097)
{
                            if (proj.oldPos[num208] == Vector2.Zero)
{
                                goto IL_8BF3;
                            }
                            float num215 = (float)num208 / (float)num204;
                            if (num215 < 0.5f)
{
                                color37 = Microsoft.Xna.Framework.Color.Lerp(color37, Microsoft.Xna.Framework.Color.OrangeRed, Utils.GetLerpValue(0f, 0.5f, num215, false));
                            }
                            else
{
                                color37 = Microsoft.Xna.Framework.Color.Lerp(Microsoft.Xna.Framework.Color.OrangeRed, Microsoft.Xna.Framework.Color.Red, Utils.GetLerpValue(0.5f, 1f, num215, false));
                            }
                        }
                        else if (proj.type == 711)
{
                            if (proj.oldPos[num208] == Vector2.Zero)
{
                                goto IL_8BF3;
                            }
                            float num216 = (float)num208 / (float)num204;
                            if (num216 < 0.5f)
{
                                color37 = Microsoft.Xna.Framework.Color.Lerp(color37, new Microsoft.Xna.Framework.Color(128, 0, 255, 180), Utils.GetLerpValue(0f, 0.5f, num216, false));
                            }
                            else
{
                                color37 = Microsoft.Xna.Framework.Color.Lerp(new Microsoft.Xna.Framework.Color(128, 0, 255, 180), Microsoft.Xna.Framework.Color.Black, Utils.GetLerpValue(0.5f, 1f, num216, false));
                            }
                        }
                        else if (proj.type == 684)
{
                            if (num208 == 1)
{
                                color37.B /= 2;
                                color37.G /= 2;
                                color37.A /= 2;
                            }
                            color37.B /= (byte)num208;
                            color37.G /= (byte)num208;
                            color37.A /= (byte)num208;
                        }
                        else if (proj.type == 706 || proj.type == 710)
{
                            color37.B /= (byte)num208;
                            color37.G /= (byte)num208;
                            color37.A /= (byte)num208;
                        }
                        else if (proj.type == 818)
{
                            float num217 = 0.3f;
                            float num218 = Utils.GetLerpValue(0f, num217, proj.ai[0], true) * Utils.GetLerpValue(1f, 1f - num217, proj.ai[0], true);
                            Utils.GetLerpValue(0f, (float)(num203 * -3), (float)num208, true);
                            Utils.GetLerpValue((float)num204, (float)(num204 + num203 * 3), (float)num208, true);
                            Microsoft.Xna.Framework.Color color38 = new Microsoft.Xna.Framework.Color(255, 255, 255, 0);
                            Microsoft.Xna.Framework.Color color39 = Main.OurFavoriteColor;
                            color39.A = 0;
                            color39 *= num218;
                            color37 = Microsoft.Xna.Framework.Color.Lerp(color39, color38, num218);
                        }
                        else if (proj.type == 833 || proj.type == 834 || proj.type == 835)
{
                            float lerpValue2 = Utils.GetLerpValue(0f, 6f, proj.velocity.Length(), true);
                            color37 = Microsoft.Xna.Framework.Color.Lerp(color37, Microsoft.Xna.Framework.Color.White, lerpValue2 * 0.5f);
                            color37.A = 0;
                            color37 *= lerpValue2;
                        }
                        else if (proj.type == 592)
{
                            color37.R /= (byte)num208;
                            color37.G /= (byte)num208;
                        }
                        else if (proj.type == 640)
{
                            color37.R /= (byte)num208;
                            color37.A /= (byte)num208;
                        }
                        else if (proj.type >= 424 && proj.type <= 426)
{
                            color37.B /= (byte)num208;
                            color37.G /= (byte)num208;
                            color37.A /= (byte)num208;
                        }
                        else if (proj.type == 1037 || proj.type == 1049)
{
                            color37.B /= (byte)num208;
                            color37.G /= (byte)num208;
                            color37.A /= (byte)num208;
                        }
                        else if (proj.type == 964 || proj.type == 965)
{
                            color37 = Microsoft.Xna.Framework.Color.Black * proj.Opacity;
                        }
                        float num219 = (float)(num202 - num208);
                        if (num203 < 0)
{
                            num219 = (float)(num204 - num208);
                        }
                        color37 *= num219 / ((float)ProjectileID.Sets.TrailCacheLength[proj.type] * 1.5f);
                        Vector2 vector45 = proj.oldPos[num208];
                        float num220 = proj.rotation;
                        SpriteEffects spriteEffects3 = spriteEffects2;
                        if (ProjectileID.Sets.TrailingMode[proj.type] == 2 || ProjectileID.Sets.TrailingMode[proj.type] == 3 || ProjectileID.Sets.TrailingMode[proj.type] == 4)
{
                            num220 = proj.oldRot[num208];
                            SpriteEffects spriteEffects4 = ((proj.oldSpriteDirection[num208] == -1) ? SpriteEffects.FlipHorizontally : SpriteEffects.None);
                            spriteEffects3 ^= spriteEffects4;
                        }
                        if (!(vector45 == Vector2.Zero))
{
                            if (proj.type == 916)
{
                                rectangle7.Y += rectangle7.Height;
                                rectangle7.Y %= rectangle7.Height * Main.projFrames[proj.type];
                                float num221 = num219 / ((float)ProjectileID.Sets.TrailCacheLength[proj.type] * 1.5f);
                                Microsoft.Xna.Framework.Color color40 = new Microsoft.Xna.Framework.Color(0, 0, 0, 255);
                                int num222 = unifiedRandom.Next(3);
                                if (num222 == 2 || num222 == 1)
{
                                    color40 = Microsoft.Xna.Framework.Color.Lerp(new Microsoft.Xna.Framework.Color(106, 90, 205, 127), Microsoft.Xna.Framework.Color.Black, 0.2f + 0.8f * unifiedRandom.NextFloat());
                                }
                                color37 = color40;
                                float num223 = num219 / (float)ProjectileID.Sets.TrailCacheLength[proj.type];
                                num223 = Utils.GetLerpValue(0f, (float)ProjectileID.Sets.TrailCacheLength[proj.type] * 0.75f, num219, true);
                                color37 *= num223;
                                vector45 += unifiedRandom.NextVector2Circular(8f, 8f);
                            }
                            if (proj.type == 976)
{
                                int num224 = rectangle7.Height + 2;
                                rectangle7.Y += num224;
                                rectangle7.Y %= num224 * 7;
                                Microsoft.Xna.Framework.Color color41 = Lighting.GetColor((vector45 + zero + proj.Size / 2f).ToTileCoordinates());
                                color37 *= color41.ToVector3().Length() / 1.74f;
                            }
                            if (proj.type == 933 || proj.type == 1100)
{
                                float num225 = proj.localAI[0] - (float)num208;
                                float num226 = Utils.GetLerpValue(0f, 20f, num225, true) * Utils.GetLerpValue(68f, 60f, num225, true);
                                float lerpValue3 = Utils.GetLerpValue(0f, (float)ProjectileID.Sets.TrailCacheLength[proj.type], num219, true);
                                color37 = Microsoft.Xna.Framework.Color.White * lerpValue3 * proj.Opacity * num226;
                            }
                            Vector2 vector46 = vector45 + zero + proj.Size / 2f - Main.screenPosition + new Vector2(0f, proj.gfxOffY);
                            Main.EntitySpriteDraw(texture2D3, vector46, new Microsoft.Xna.Framework.Rectangle?(rectangle7), color37, num220 + num200 + proj.rotation * num207 * (float)(num208 - 1) * (float)(-(float)((spriteEffects2 & SpriteEffects.FlipHorizontally) > SpriteEffects.None).ToDirectionInt()), vector44, MathHelper.Lerp(proj.scale, num205, (float)num208 / num206), spriteEffects3, 0f);
                        }
                    }
                    IL_8BF3:
                    num208 += num203;
                }
                if (proj.type == 661)
                {
                    Microsoft.Xna.Framework.Color color42 = new Microsoft.Xna.Framework.Color(120, 40, 222, 120);
                    for (int num227 = 0; num227 < 4; num227++)
                    {
                        Texture2D value8 = TextureAssets.Extra[75].Value;
                        Vector2 vector47 = proj.Center - Main.screenPosition + new Vector2(0f, proj.gfxOffY);
                        Vector2 vector48 = proj.rotation.ToRotationVector2();
                        double num228 = (double)(1.5707964f * (float)num227);
                        Vector2 vector49 = default(Vector2);
                        Main.EntitySpriteDraw(value8, vector47 + vector48.RotatedBy(num228, vector49) * 4f, new Microsoft.Xna.Framework.Rectangle?(rectangle6), color42, proj.rotation, vector44, proj.scale, spriteEffects2, 0f);
                    }
                }
                if (proj.type == 864)
                {
                    Microsoft.Xna.Framework.Color floatingDaggerMinionGlowColor = proj.GetFloatingDaggerMinionGlowColor();
                    floatingDaggerMinionGlowColor.A /= 4;
                    Microsoft.Xna.Framework.Rectangle rectangle8 = rectangle6;
                    rectangle8.Y += rectangle8.Height;
                    for (int num229 = 0; num229 < 4; num229++)
                    {
                        Texture2D texture2D4 = texture2D3;
                        Vector2 vector50 = proj.Center - Main.screenPosition + new Vector2(0f, proj.gfxOffY);
                        Vector2 vector51 = proj.rotation.ToRotationVector2();
                        double num230 = (double)(1.5707964f * (float)num229);
                        Vector2 vector49 = default(Vector2);
                        Main.EntitySpriteDraw(texture2D4, vector50 + vector51.RotatedBy(num230, vector49) * 2f, new Microsoft.Xna.Framework.Rectangle?(rectangle8), floatingDaggerMinionGlowColor, proj.rotation, vector44, proj.scale, spriteEffects2, 0f);
                    }
                }
                if (proj.type == 873 || proj.type == 931 || proj.type == 1039)
                {
                    Microsoft.Xna.Framework.Color color43 = proj.AI_171_GetColor() * 0.5f;
                    color43.A = 0;
                    if (proj.type == 931)
                    {
                        float num231 = 0f;
                        float num232 = 0f;
                        float? num211 = null;
                        color43 = proj.GetFairyQueenWeaponsColor(num231, num232, num211);
                    }
                    if (proj.type == 1039)
                    {
                        float num233 = 0f;
                        float num234 = 0f;
                        float? num211 = null;
                        color43 = proj.GetConstellationColor(num233, num234, num211);
                    }
                    Vector2 vector52 = proj.Center - Main.screenPosition + new Vector2(0f, proj.gfxOffY);
                    Main.EntitySpriteDraw(texture2D3, vector52, new Microsoft.Xna.Framework.Rectangle?(rectangle6), color43, proj.rotation, vector44, proj.scale * 0.9f, spriteEffects2, 0f);
                    Texture2D value9 = TextureAssets.Extra[98].Value;
                    Microsoft.Xna.Framework.Color color44 = color43;
                    Vector2 vector53 = value9.Size() / 2f;
                    Microsoft.Xna.Framework.Color color45 = color43 * 0.5f;
                    float num235 = Utils.GetLerpValue(15f, 30f, (float)proj.timeLeft, true) * Utils.GetLerpValue(240f, 200f, (float)proj.timeLeft, true) * (1f + 0.2f * (float)Math.Cos((double)(Main.GlobalTimeWrappedHourly % 30f / 0.5f * 6.2831855f * 3f))) * 0.8f;
                    Vector2 vector54 = vector52 + proj.velocity.SafeNormalize(Vector2.Zero) * MathHelper.Lerp(0.5f, 1f, proj.localAI[0] / 60f);
                    Vector2 vector55 = new Vector2(0.5f, 5f) * num235;
                    Vector2 vector56 = new Vector2(0.5f, 2f) * num235;
                    color44 *= num235;
                    color45 *= num235;
                    if (proj.type == 931 || proj.type == 1039)
                    {
                        vector55 *= 0.4f;
                        vector56 *= 0.4f;
                    }
                    Main.EntitySpriteDraw(value9, vector54, null, color44, 1.5707964f, vector53, vector55, spriteEffects2, 0f);
                    Main.EntitySpriteDraw(value9, vector54, null, color44, 0f, vector53, vector56, spriteEffects2, 0f);
                    Main.EntitySpriteDraw(value9, vector54, null, color45, 1.5707964f, vector53, vector55 * 0.6f, spriteEffects2, 0f);
                    Main.EntitySpriteDraw(value9, vector54, null, color45, 0f, vector53, vector56 * 0.6f, spriteEffects2, 0f);
                }
                if (proj.type == 755)
                {
                    Microsoft.Xna.Framework.Color color46 = proj.AI_156_GetColor();
                    color46.A = 120;
                    for (int num236 = 0; num236 < 4; num236++)
                    {
                        Texture2D texture2D5 = texture2D3;
                        Vector2 vector57 = proj.Center - Main.screenPosition + new Vector2(0f, proj.gfxOffY);
                        Vector2 vector58 = proj.rotation.ToRotationVector2();
                        double num237 = (double)(1.5707964f * (float)num236);
                        Vector2 vector49 = default(Vector2);
                        Main.EntitySpriteDraw(texture2D5, vector57 + vector58.RotatedBy(num237, vector49) * 2f, new Microsoft.Xna.Framework.Rectangle?(rectangle6), color46, proj.rotation, vector44, proj.scale, spriteEffects2, 0f);
                    }
                }
                else if (proj.type == 684)
                {
                    float x = (proj.localAI[0] * 6.2831855f / 30f).ToRotationVector2().X;
                    Microsoft.Xna.Framework.Color color47 = new Microsoft.Xna.Framework.Color(220, 40, 30, 40);
                    color47 *= 0.75f + 0.25f * x;
                    for (int num238 = 0; num238 < 8; num238++)
                    {
                        Texture2D texture2D6 = texture2D3;
                        Vector2 vector59 = proj.Center - Main.screenPosition + new Vector2(0f, proj.gfxOffY);
                        Vector2 vector60 = proj.rotation.ToRotationVector2();
                        double num239 = (double)(0.7853982f * (float)num238);
                        Vector2 vector49 = default(Vector2);
                        Main.EntitySpriteDraw(texture2D6, vector59 + vector60.RotatedBy(num239, vector49) * (4f + 1f * x), new Microsoft.Xna.Framework.Rectangle?(rectangle6), color47, proj.rotation, vector44, proj.scale, spriteEffects2, 0f);
                    }
                }
                else if (ProjectileID.Sets.IsAGolfBall[proj.type])
                {
                    Player player3 = player;
                    bool flag27 = GolfHelper.IsPlayerHoldingClub(player3);
                    bool flag28 = false;
                    if (flag27)
                    {
                        flag28 |= player3.ownedProjectileCounts[722] > 0 && player3.itemAnimation >= player3.itemAnimationMax;
                        flag28 |= player3.itemAnimation == 0;
                        flag28 &= player3.velocity.Y == 0f;
                    }
                    Vector2 vector61 = Main.MouseWorld - proj.Center;
                    if (proj.owner == Main.myPlayer && flag27 && flag28 && GolfHelper.IsGolfBallResting(proj) && GolfHelper.ValidateShot(proj, player3, ref vector61))
                    {
                        color36 = Microsoft.Xna.Framework.Color.White;
                        Projectile projectile = null;
                        for (int num240 = 0; num240 < 1000; num240++)
{
                            Projectile projectile2 = Main.projectile[num240];
                            if (projectile2.active && projectile2.owner == player3.whoAmI && projectile2.type == 722)
{
                                projectile = projectile2;
                                break;
                            }
                        }
                        if (projectile != null)
{
                            GolfHelper.ShotStrength shotStrength = GolfHelper.CalculateShotStrength(projectile, proj);
                            Vector2 vector62 = Vector2.Normalize(vector61) * shotStrength.AbsoluteStrength;
                            if (vector62.Length() > 0.05f)
{
                                GolfHelper.DrawPredictionLine(proj, vector62, shotStrength.RelativeStrength, shotStrength.RoughLandResistance);
                            }
                        }
                    }
                    if (!GolfHelper.IsGolfBallResting(proj))
                    {
                        Microsoft.Xna.Framework.Color color48 = Projectile.GetGolfTrailColor(proj);
                        float num241 = proj.velocity.Length() / 16f;
                        if (num241 > 1f)
{
                            num241 = 1f;
                        }
                        color48 *= num241;
                        if (proj.oldPos[4] != Vector2.Zero)
{
                            color36 = Microsoft.Xna.Framework.Color.White;
                            for (float num242 = 0f; num242 <= 1f; num242 += 0.04f)
{
                                Main.EntitySpriteDraw(texture2D3, Vector2.Lerp(proj.oldPos[4], proj.position, num242) + proj.Size / 2f - Main.screenPosition + new Vector2(0f, proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rectangle6), color48 * num242, proj.rotation, vector44, proj.scale * MathHelper.Lerp(0.7f, 1.5f, num242), spriteEffects2, 0f);
                            }
                        }
                        Main.EntitySpriteDraw(texture2D3, proj.position + proj.Size / 2f - Main.screenPosition + new Vector2(0f, proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rectangle6), color48, proj.rotation, vector44, proj.scale * 1.5f, spriteEffects2, 0f);
                    }
                }
                else if (proj.type == 1049)
                {
                    this.DrawProjWithStarryTrail(proj, player, color36, spriteEffects2);
                }
                if (proj.type == 964 || proj.type == 965)
                {
                    Microsoft.Xna.Framework.Color color49 = Microsoft.Xna.Framework.Color.Violet;
                    if (proj.type == 965)
                    {
                        color49 = Microsoft.Xna.Framework.Color.Lerp(Microsoft.Xna.Framework.Color.Red, Microsoft.Xna.Framework.Color.White, 0.5f);
                    }
                    Microsoft.Xna.Framework.Color color50 = color49 * 0.5f * proj.Opacity;
                    float num243 = (float)((proj.type == 964) ? 60 : 30);
                    for (int num244 = 0; num244 < 4; num244++)
                    {
                        Texture2D texture2D7 = texture2D3;
                        Vector2 vector63 = proj.Center - Main.screenPosition + new Vector2(0f, proj.gfxOffY);
                        Vector2 vector64 = proj.rotation.ToRotationVector2();
                        double num245 = (double)(proj.ai[0] / num243 * 6.2831855f + 1.5707964f * (float)num244);
                        Vector2 vector49 = default(Vector2);
                        Main.EntitySpriteDraw(texture2D7, vector63 + vector64.RotatedBy(num245, vector49) * 6f, new Microsoft.Xna.Framework.Rectangle?(rectangle6), color50, proj.rotation, vector44, proj.scale, spriteEffects2, 0f);
                    }
                }
                Microsoft.Xna.Framework.Color color51 = proj.GetAlpha(color36);
                float num246 = proj.scale;
                float num247 = proj.rotation + num200;
                if (proj.type == 640)
                {
                    color51 = Microsoft.Xna.Framework.Color.Transparent;
                }
                if (proj.type == 684)
                {
                    color51.A = 127;
                }
                if (proj.type == 873)
                {
                    color51.A /= 2;
                }
                if (proj.type == 931 || proj.type == 1039)
                {
                    color51.A /= 2;
                }
                if (proj.type == 872)
                {
                    color51 = new Microsoft.Xna.Framework.Color(255, 255, 255, 0) * proj.Opacity;
                    num246 *= 0.9f;
                }
                if (proj.type == 818)
                {
                    color51 = Microsoft.Xna.Framework.Color.Transparent;
                }
                if (proj.type == 916)
                {
                    color51 = Microsoft.Xna.Framework.Color.Black;
                }
                if (proj.type == 964 || proj.type == 965)
                {
                    color51 = Microsoft.Xna.Framework.Color.Black * proj.Opacity;
                }
                if (proj.type == 933 || proj.type == 1100)
                {
                    float num248 = proj.localAI[0];
                    float num249 = Utils.GetLerpValue(0f, 20f, num248, true) * Utils.GetLerpValue(68f, 60f, num248, true);
                    color51 *= num249;
                }
                Main.EntitySpriteDraw(texture2D3, proj.Center + zero - Main.screenPosition + new Vector2(0f, proj.gfxOffY + (float)num189), new Microsoft.Xna.Framework.Rectangle?(rectangle6), color51, num247, vector44, num246, spriteEffects2, 0f);
                if (proj.type == 894)
                {
                    float num250 = Utils.WrappedLerp(0.6f, 1f, (float)((int)Main.timeForVisualEffects % 70) / 70f);
                    Microsoft.Xna.Framework.Color color52 = new Microsoft.Xna.Framework.Color(num250, num250, num250, 150f);
                    Main.EntitySpriteDraw(TextureAssets.GlowMask[282].Value, proj.Center + zero - Main.screenPosition + new Vector2(0f, proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rectangle6), color52, proj.rotation, vector44, proj.scale, spriteEffects2, 0f);
                }
                if (proj.type == 503)
                {
                    Main.EntitySpriteDraw(TextureAssets.Extra[36].Value, proj.Center - Main.screenPosition + new Vector2(0f, proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rectangle6), Microsoft.Xna.Framework.Color.White, proj.localAI[0], vector44, proj.scale, spriteEffects2, 0f);
                }
                else if (proj.type == 533)
                {
                    Main.EntitySpriteDraw(TextureAssets.GlowMask[128].Value, proj.Center - Main.screenPosition + new Vector2(0f, proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rectangle6), Microsoft.Xna.Framework.Color.White * 0.3f, proj.rotation, vector44, proj.scale, spriteEffects2, 0f);
                }
                else if (proj.type == 261)
                {
                    float num251 = 0.7f;
                    float num252 = proj.velocity.Length();
                    if (num252 < 0.3f && proj.velocity.Y == 0f)
                    {
                        num251 = Utils.GetLerpValue(0.02f, 0.3f, num252, true) * 0.7f;
                    }
                    Main.EntitySpriteDraw(TextureAssets.GlowMask[252].Value, proj.Center - Main.screenPosition + new Vector2(0f, proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rectangle6), Microsoft.Xna.Framework.Color.White * num251, proj.rotation, vector44, proj.scale, spriteEffects2, 0f);
                }
                else if (proj.type == 601)
                {
                    Microsoft.Xna.Framework.Color white = Microsoft.Xna.Framework.Color.White;
                    white.A = 0;
                    Main.EntitySpriteDraw(texture2D3, proj.Center - Main.screenPosition + new Vector2(0f, proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rectangle6), white, proj.rotation, vector44, proj.scale * 0.7f, spriteEffects2, 0f);
                }
                else if (ProjectileID.Sets.IsAGolfBall[proj.type] && GolfHelper.IsGolfBallResting(proj) && GolfHelper.IsPlayerHoldingClub(Main.LocalPlayer) && GolfHelper.IsGolfShotValid(proj, Main.LocalPlayer) && proj.owner == Main.myPlayer)
                {
                    Main.EntitySpriteDraw(TextureAssets.GolfBallOutline.Value, proj.Center - Main.screenPosition + new Vector2(0f, proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rectangle6), Microsoft.Xna.Framework.Color.White, proj.rotation, vector44, proj.scale, spriteEffects2, 0f);
                }
                if (proj.type == 933 || proj.type == 1100)
                {
                    float num253 = proj.localAI[0];
                    float num254 = Utils.GetLerpValue(0f, 20f, num253, true) * Utils.GetLerpValue(68f, 60f, num253, true);
                    Main.EntitySpriteDraw(texture2D3, proj.Center + zero - Main.screenPosition + new Vector2(0f, proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rectangle6), new Microsoft.Xna.Framework.Color(255, 255, 255, 127) * proj.Opacity * num254, num247, vector44, num246 * 1.25f, spriteEffects2, 0f);
                    FinalFractalHelper.FinalFractalProfile finalFractalProfile = FinalFractalHelper.GetFinalFractalProfile((int)proj.ai[1]);
                    Microsoft.Xna.Framework.Color trailColor = finalFractalProfile.trailColor;
                    trailColor.A /= 2;
                    Main.DrawPrettyStarSparkle(proj.Opacity, spriteEffects2, proj.Center + zero - Main.screenPosition + new Vector2(0f, proj.gfxOffY) + (proj.rotation - 1.5707964f).ToRotationVector2() * finalFractalProfile.trailWidth, Microsoft.Xna.Framework.Color.White * num254, trailColor * num254, proj.localAI[0], 15f, 30f, 30f, 45f, 0f, new Vector2(5f, 2f), Vector2.One);
                    return;
                }
            }
            else if (proj.type == 672)
            {
                Vector2 vector65 = proj.Center - Main.screenPosition;
                if (proj.localAI[1] == 0f)
                {
                    vector65.Y += 60f;
                    float num255 = proj.localAI[0] / 120f;
                    for (int num256 = 0; num256 < 4; num256++)
                    {
                        float num257 = num255 * 2f - (float)num256 / 3f;
                        num257 = MathHelper.Clamp(num257, 0f, 1f);
                        float num258 = 1f - MathHelper.Clamp((num255 - 0.8f) / 0.2f, 0f, 1f);
                        Main.EntitySpriteDraw(TextureAssets.MagicPixel.Value, vector65, null, new Microsoft.Xna.Framework.Color(0.4f, 0.17f, 0.4f, 0f) * (num257 * num258) * 1.3f, 0f, new Vector2((float)TextureAssets.MagicPixel.Width() / 2f, (float)TextureAssets.MagicPixel.Height()), new Vector2((float)Math.Sqrt((double)num257) * 100f, num257 * 2f), SpriteEffects.None, 0f);
                    }
                    return;
                }
                if (proj.localAI[1] == 1f)
                {
                    float num259 = proj.localAI[0] / 300f;
                    float num260 = Math.Min(1f, proj.localAI[0] / 30f);
                    int num261 = (int)(Main.GlobalTimeWrappedHourly * 10f) % 8;
                    this.DrawElderEye(Main.spriteBatch, proj.Center, 1f, 1f, num261, Microsoft.Xna.Framework.Color.White * num260);
                    this.DrawElderEye(Main.spriteBatch, proj.Center, 1f, 1f, (num261 + 1) % 8, new Microsoft.Xna.Framework.Color(0.2f, 0.2f, 0.2f, 0f) * num260);
                    return;
                }
                if (proj.localAI[1] == 2f)
                {
                    int num262 = (int)(Main.GlobalTimeWrappedHourly * 10f) % 8;
                    this.DrawElderEye(Main.spriteBatch, proj.Center, 1f, 1f, num262, Microsoft.Xna.Framework.Color.White);
                    this.DrawElderEye(Main.spriteBatch, proj.Center, 1f, 1f, (num262 + 1) % 8, new Microsoft.Xna.Framework.Color(0.2f, 0.2f, 0.2f, 0f));
                    return;
                }
            }
            else if (proj.type != 713)
            {
                if (proj.type == 754)
                {
                    Texture2D value10 = TextureAssets.Projectile[proj.type].Value;
                    Microsoft.Xna.Framework.Rectangle rectangle9 = value10.Frame(5, 2, proj.frame, 0, 0, 0);
                    rectangle9.Width -= 2;
                    rectangle9.Height -= 2;
                    Vector2 vector66 = new Vector2((float)(rectangle9.Width / 2), 0f);
                    float y = proj.position.Y;
                    float num263 = proj.ai[0] + 8f + 2f - (float)rectangle9.Height + 2f;
                    Microsoft.Xna.Framework.Color color53 = proj.GetAlpha(color36);
                    Vector2 top = proj.Top;
                    if (proj.ai[1] == 2f)
                    {
                        rectangle9 = value10.Frame(5, 2, 4, 0, 0, 0);
                        rectangle9.Width -= 2;
                        rectangle9.Height -= 2;
                        vector66 = new Vector2((float)(rectangle9.Width / 2), 0f);
                        color53 = proj.GetAlpha(Lighting.GetColor((int)(top.X + (float)(rectangle9.Width / 2)) / 16, (int)((num263 - 2f + (float)(rectangle9.Height / 2)) / 16f)));
                        Main.EntitySpriteDraw(value10, new Vector2(top.X, num263 - 2f) - Main.screenPosition + new Vector2(0f, proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rectangle9), color53, proj.rotation, vector66, proj.scale, spriteEffects2, 0f);
                        return;
                    }
                    for (float num264 = y; num264 < num263; num264 += (float)rectangle9.Height)
                    {
                        Vector2 vector67 = top;
                        vector67.Y = num264;
                        Microsoft.Xna.Framework.Rectangle rectangle10 = rectangle9;
                        float num265 = num263 - num264;
                        if (num265 < (float)rectangle10.Height)
{
                            rectangle10.Height = (int)num265;
                        }
                        color53 = proj.GetAlpha(Lighting.GetColor((int)(vector67.X + (float)(rectangle10.Width / 2)) / 16, (int)((vector67.Y + (float)(rectangle10.Height / 2)) / 16f)));
                        Main.EntitySpriteDraw(value10, vector67 - Main.screenPosition + new Vector2(0f, proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rectangle10), color53, proj.rotation, vector66, proj.scale, spriteEffects2, 0f);
                        if (rectangle9.Y == 0)
{
                            rectangle9.Y += rectangle9.Height + 2;
                        }
                    }
                    rectangle9 = value10.Frame(5, 2, 4, 0, 0, 0);
                    rectangle9.Width -= 2;
                    rectangle9.Height -= 2;
                    vector66 = new Vector2((float)(rectangle9.Width / 2), 0f);
                    color53 = proj.GetAlpha(Lighting.GetColor((int)(top.X + (float)(rectangle9.Width / 2)) / 16, (int)((num263 - 2f + (float)(rectangle9.Height / 2)) / 16f)));
                    Main.EntitySpriteDraw(value10, new Vector2(top.X, num263 - 2f) - Main.screenPosition + new Vector2(0f, proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rectangle9), color53, proj.rotation, vector66, proj.scale, spriteEffects2, 0f);
                    return;
                }
                else
                {
                    if (proj.type == 12 || proj.type == 728 || proj.type == 955)
                    {
                        Texture2D value11 = TextureAssets.Projectile[proj.type].Value;
                        Microsoft.Xna.Framework.Rectangle rectangle11 = new Microsoft.Xna.Framework.Rectangle(0, 0, value11.Width, value11.Height);
                        Vector2 vector68 = rectangle11.Size() / 2f;
                        Microsoft.Xna.Framework.Color alpha2 = proj.GetAlpha(color36);
                        Texture2D value12 = TextureAssets.Extra[91].Value;
                        Microsoft.Xna.Framework.Rectangle rectangle12 = value12.Frame(1, 1, 0, 0, 0, 0);
                        Vector2 vector69 = new Vector2((float)rectangle12.Width / 2f, 10f);
                        Vector2 vector70 = new Vector2(0f, proj.gfxOffY);
                        Vector2 vector71 = new Vector2(0f, -10f);
                        float num266 = (float)Main.timeForVisualEffects / 60f;
                        Vector2 vector72 = proj.Center + proj.velocity;
                        Microsoft.Xna.Framework.Color color54 = Microsoft.Xna.Framework.Color.Blue * 0.2f;
                        Microsoft.Xna.Framework.Color color55 = Microsoft.Xna.Framework.Color.White * 0.5f;
                        color55.A = 0;
                        float num267 = 0f;
                        if (Main.tenthAnniversaryWorld)
{
                            color54 = Microsoft.Xna.Framework.Color.HotPink * 0.3f;
                            color55 = Microsoft.Xna.Framework.Color.White * 0.75f;
                            color55.A = 0;
                            num267 = -0.1f;
                        }
                        if (proj.type == 728)
{
                            color54 = Microsoft.Xna.Framework.Color.Orange * 0.2f;
                            color55 = Microsoft.Xna.Framework.Color.Gold * 0.5f;
                            color55.A = 50;
                            num267 = -0.2f;
                        }
                        Microsoft.Xna.Framework.Color color56 = color54;
                        color56.A = 0;
                        Microsoft.Xna.Framework.Color color57 = color54;
                        color57.A = 0;
                        Microsoft.Xna.Framework.Color color58 = color54;
                        color58.A = 0;
                        Texture2D texture2D8 = value12;
                        Vector2 vector73 = vector72 - Main.screenPosition + vector70;
                        Vector2 vector74 = vector71;
                        double num268 = (double)(6.2831855f * num266);
                        Vector2 vector49 = default(Vector2);
                        Main.EntitySpriteDraw(texture2D8, vector73 + vector74.RotatedBy(num268, vector49), new Microsoft.Xna.Framework.Rectangle?(rectangle12), color56, proj.velocity.ToRotation() + 1.5707964f, vector69, 1.5f + num267, SpriteEffects.None, 0f);
                        Texture2D texture2D9 = value12;
                        Vector2 vector75 = vector72 - Main.screenPosition + vector70;
                        Vector2 vector76 = vector71;
                        double num269 = (double)(6.2831855f * num266 + 2.0943952f);
                        vector49 = default(Vector2);
                        Main.EntitySpriteDraw(texture2D9, vector75 + vector76.RotatedBy(num269, vector49), new Microsoft.Xna.Framework.Rectangle?(rectangle12), color57, proj.velocity.ToRotation() + 1.5707964f, vector69, 1.1f + num267, SpriteEffects.None, 0f);
                        Texture2D texture2D10 = value12;
                        Vector2 vector77 = vector72 - Main.screenPosition + vector70;
                        Vector2 vector78 = vector71;
                        double num270 = (double)(6.2831855f * num266 + 4.1887903f);
                        vector49 = default(Vector2);
                        Main.EntitySpriteDraw(texture2D10, vector77 + vector78.RotatedBy(num270, vector49), new Microsoft.Xna.Framework.Rectangle?(rectangle12), color58, proj.velocity.ToRotation() + 1.5707964f, vector69, 1.3f + num267, SpriteEffects.None, 0f);
                        Vector2 vector79 = proj.Center - proj.velocity * 0.5f;
                        for (float num271 = 0f; num271 < 1f; num271 += 0.5f)
{
                            float num272 = num266 % 0.5f / 0.5f;
                            num272 = (num272 + num271) % 1f;
                            float num273 = num272 * 2f;
                            if (num273 > 1f)
{
                                num273 = 2f - num273;
                            }
                            Main.EntitySpriteDraw(value12, vector79 - Main.screenPosition + vector70, new Microsoft.Xna.Framework.Rectangle?(rectangle12), color55 * num273, proj.velocity.ToRotation() + 1.5707964f, vector69, 0.3f + num272 * 0.5f, SpriteEffects.None, 0f);
                        }
                        Main.EntitySpriteDraw(value11, proj.Center - Main.screenPosition + new Vector2(0f, proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rectangle11), alpha2, proj.rotation, vector68, proj.scale + 0.1f, spriteEffects2, 0f);
                        return;
                    }
                    if (proj.type == 756)
                    {
                        Texture2D value13 = TextureAssets.Projectile[proj.type].Value;
                        Microsoft.Xna.Framework.Rectangle rectangle13 = value13.Frame(1, 6, 0, proj.frame, 0, 0);
                        Vector2 vector80 = new Vector2(16f, (float)(rectangle13.Height / 2));
                        Microsoft.Xna.Framework.Color alpha3 = proj.GetAlpha(color36);
                        Vector2 vector81 = new Vector2(proj.scale);
                        float num274 = 35f;
                        float lerpValue4 = Utils.GetLerpValue(num274, num274 - 5f, proj.ai[0], true);
                        vector81.Y *= lerpValue4;
                        Vector4 vector82 = color36.ToVector4();
                        Vector4 vector83 = new Microsoft.Xna.Framework.Color(67, 17, 17).ToVector4();
                        vector83 *= vector82;
                        Main.EntitySpriteDraw(TextureAssets.Extra[98].Value, proj.Center - Main.screenPosition + new Vector2(0f, proj.gfxOffY) - proj.velocity * proj.scale * 0.5f, null, proj.GetAlpha(new Microsoft.Xna.Framework.Color(vector83.X, vector83.Y, vector83.Z, vector83.W)) * 1f, proj.rotation + 1.5707964f, TextureAssets.Extra[98].Value.Size() / 2f, proj.scale * 0.9f, spriteEffects2, 0f);
                        Main.EntitySpriteDraw(value13, proj.Center - Main.screenPosition + new Vector2(0f, proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rectangle13), alpha3, proj.rotation, vector80, vector81, spriteEffects2, 0f);
                        return;
                    }
                    if (proj.type == 961)
                    {
                        Texture2D value14 = TextureAssets.Projectile[proj.type].Value;
                        Microsoft.Xna.Framework.Rectangle rectangle14 = value14.Frame(1, 5, 0, proj.frame, 0, 0);
                        Vector2 vector84 = new Vector2(16f, (float)(rectangle14.Height / 2));
                        Microsoft.Xna.Framework.Color alpha4 = proj.GetAlpha(color36);
                        Vector2 vector85 = new Vector2(proj.scale);
                        float lerpValue5 = Utils.GetLerpValue(30f, 25f, proj.ai[0], true);
                        vector85.Y *= lerpValue5;
                        Vector4 vector86 = color36.ToVector4();
                        Vector4 vector87 = new Microsoft.Xna.Framework.Color(67, 17, 17).ToVector4();
                        vector87 *= vector86;
                        Main.EntitySpriteDraw(TextureAssets.Extra[98].Value, proj.Center - Main.screenPosition + new Vector2(0f, proj.gfxOffY) - proj.velocity * proj.scale * 0.5f, null, proj.GetAlpha(new Microsoft.Xna.Framework.Color(vector87.X, vector87.Y, vector87.Z, vector87.W)) * 1f, proj.rotation + 1.5707964f, TextureAssets.Extra[98].Value.Size() / 2f, proj.scale * 0.9f, spriteEffects2, 0f);
                        Microsoft.Xna.Framework.Color color59 = proj.GetAlpha(Microsoft.Xna.Framework.Color.White) * Utils.Remap(proj.ai[0], 0f, 20f, 0.5f, 0f, true);
                        color59.A = 0;
                        for (int num275 = 0; num275 < 4; num275++)
{
                            Texture2D texture2D11 = value14;
                            Vector2 vector88 = proj.Center - Main.screenPosition + new Vector2(0f, proj.gfxOffY);
                            Vector2 vector89 = proj.rotation.ToRotationVector2();
                            double num276 = (double)(1.5707964f * (float)num275);
                            Vector2 vector49 = default(Vector2);
                            Main.EntitySpriteDraw(texture2D11, vector88 + vector89.RotatedBy(num276, vector49) * 2f * vector85, new Microsoft.Xna.Framework.Rectangle?(rectangle14), color59, proj.rotation, vector84, vector85, spriteEffects2, 0f);
                        }
                        Main.EntitySpriteDraw(value14, proj.Center - Main.screenPosition + new Vector2(0f, proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rectangle14), alpha4, proj.rotation, vector84, vector85, spriteEffects2, 0f);
                        return;
                    }
                    if (proj.type == 1041)
                    {
                        Texture2D value15 = TextureAssets.Projectile[proj.type].Value;
                        Microsoft.Xna.Framework.Rectangle rectangle15 = value15.Frame(1, 8, 0, proj.frame, 0, 0);
                        Vector2 vector90 = new Vector2(16f, (float)(rectangle15.Height / 2));
                        Microsoft.Xna.Framework.Color alpha5 = proj.GetAlpha(color36);
                        Vector2 vector91 = new Vector2(proj.scale);
                        float lerpValue6 = Utils.GetLerpValue(30f, 25f, proj.ai[0], true);
                        vector91.Y *= lerpValue6;
                        Vector4 vector92 = color36.ToVector4();
                        new Microsoft.Xna.Framework.Color(67, 17, 17).ToVector4() * vector92;
                        float num277 = Utils.Remap(proj.ai[0], 0f, 17f, 1f, 0f, true);
                        (proj.GetAlpha(Microsoft.Xna.Framework.Color.White) * num277).A = 0;
                        Main.EntitySpriteDraw(value15, proj.Center - Main.screenPosition + new Vector2(0f, proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rectangle15), alpha5, proj.rotation, vector90, vector91, spriteEffects2, 0f);
                        return;
                    }
                    if (proj.type == 723 || proj.type == 726 || proj.type == 725 || proj.type == 724 || proj.type == 9)
                    {
                        Texture2D texture2D12 = TextureAssets.Projectile[proj.type].Value;
                        Microsoft.Xna.Framework.Rectangle rectangle16 = new Microsoft.Xna.Framework.Rectangle(0, 0, texture2D12.Width, texture2D12.Height);
                        Vector2 vector93 = rectangle16.Size() / 2f;
                        Microsoft.Xna.Framework.Color color60 = proj.GetAlpha(color36);
                        Texture2D value16 = TextureAssets.Extra[91].Value;
                        Microsoft.Xna.Framework.Rectangle rectangle17 = value16.Frame(1, 1, 0, 0, 0, 0);
                        Vector2 vector94 = new Vector2((float)rectangle17.Width / 2f, 10f);
                        Microsoft.Xna.Framework.Color.White * 0.2f;
                        Vector2 vector95 = new Vector2(0f, proj.gfxOffY);
                        Vector2 vector96 = new Vector2(0f, -5f);
                        float num278 = (float)Main.timeForVisualEffects / 60f;
                        Vector2 vector97 = proj.Center + proj.velocity;
                        float num279 = 1.5f;
                        float num280 = 1.1f;
                        float num281 = 1.3f;
                        Microsoft.Xna.Framework.Color color61 = Microsoft.Xna.Framework.Color.Blue * 0.1f;
                        Microsoft.Xna.Framework.Color color62 = Microsoft.Xna.Framework.Color.White * 0.3f;
                        color62.A = 0;
                        byte b = 0;
                        float num282 = 1f;
                        bool flag29 = true;
                        float num283 = proj.scale + 0.1f;
                        if (proj.type == 726)
{
                            Microsoft.Xna.Framework.Color color63 = new Microsoft.Xna.Framework.Color(180, 20, 255);
                            color61 = color63 * 0.3f;
                            color62 = color63 * 0.3f;
                            b = 60;
                            float num284 = 0.6f;
                            num279 -= num284;
                            num280 -= num284;
                            num281 -= num284;
                        }
                        if (proj.type == 725)
{
                            Microsoft.Xna.Framework.Color color64 = new Microsoft.Xna.Framework.Color(255, 80, 255);
                            Microsoft.Xna.Framework.Color color65 = new Microsoft.Xna.Framework.Color(255, 255, 0);
                            color61 = Microsoft.Xna.Framework.Color.Lerp(color64, color65, 0.2f) * 0.3f;
                            color62 = Microsoft.Xna.Framework.Color.Lerp(color64, color65, 0.8f) * 0.4f;
                            b = 50;
                            float num285 = 0.5f;
                            num279 -= num285;
                            num280 -= num285;
                            num281 -= num285;
                        }
                        if (proj.type == 724)
{
                            Microsoft.Xna.Framework.Color.Lerp(Microsoft.Xna.Framework.Color.Black, Microsoft.Xna.Framework.Color.Orange, 0.75f);
                            Microsoft.Xna.Framework.Color color66 = Microsoft.Xna.Framework.Color.Lerp(Microsoft.Xna.Framework.Color.Black, Microsoft.Xna.Framework.Color.Yellow, 0.5f);
                            Microsoft.Xna.Framework.Color color67 = Microsoft.Xna.Framework.Color.Orange * 0.75f;
                            color66 = Microsoft.Xna.Framework.Color.Yellow * 0.5f;
                            color61 = Microsoft.Xna.Framework.Color.Lerp(color67, color66, 0.2f) * 0.3f;
                            color62 = Microsoft.Xna.Framework.Color.Lerp(color67, color66, 0.8f) * 0.4f;
                            b = 0;
                            float num286 = 0.5f;
                            num279 -= num286;
                            num280 -= num286;
                            num281 -= num286;
                        }
                        if (proj.type == 9)
{
                            num279 = 0.9f;
                            num280 = 0f;
                            num281 = 0f;
                            flag29 = false;
                            vector96 = Vector2.Zero;
                            vector95 += proj.velocity.SafeNormalize(Vector2.Zero) * 8f;
                            num282 *= 0.75f;
                            vector97 -= proj.velocity;
                            Microsoft.Xna.Framework.Color color68 = new Microsoft.Xna.Framework.Color(194, 22, 134);
                            color68 *= 0.75f;
                            color68.A /= 2;
                            Microsoft.Xna.Framework.Color color69 = Microsoft.Xna.Framework.Color.Lerp(Microsoft.Xna.Framework.Color.Gold, Microsoft.Xna.Framework.Color.White, 0.5f);
                            color69.A /= 4;
                            color69 *= 0.85f;
                            color69 *= 0.75f;
                            Microsoft.Xna.Framework.Color gold = Microsoft.Xna.Framework.Color.Gold;
                            gold.A = 180;
                            Microsoft.Xna.Framework.Color color70 = new Microsoft.Xna.Framework.Color(194, 22, 134, 127);
                            Microsoft.Xna.Framework.Color color71 = new Microsoft.Xna.Framework.Color(180, 20, 255) * 0.75f * 0.3f;
                            Microsoft.Xna.Framework.Color color72 = new Microsoft.Xna.Framework.Color(255, 255, 255, 0) * 0.5f * 0.3f;
                            float num287 = 0.5f;
                            float num288 = proj.rotation * num287 % 6.2831855f;
                            if (num288 < 0f)
{
                                num288 += 6.2831855f;
                            }
                            num288 /= 6.2831855f;
                            float num289 = Utils.Remap(num288, 0.15f, 0.5f, 0f, 1f, true) * Utils.Remap(num288, 0.5f, 0.85f, 1f, 0f, true);
                            num289 = 1f - num289;
                            color60 = Microsoft.Xna.Framework.Color.Lerp(gold, color70, num289);
                            color61 = Microsoft.Xna.Framework.Color.Lerp(color68, color71, num289);
                            color62 = Microsoft.Xna.Framework.Color.Lerp(color69, color72, num289);
                            num283 += num289 * 0.2f;
                        }
                        if (proj.type == 1037 || proj.type == 1049)
{
                            int num290 = 424 + Math.Max(0, Math.Min(2, (int)proj.ai[0]));
                            Main.instance.LoadProjectile(num290);
                            texture2D12 = TextureAssets.Projectile[num290].Value;
                            rectangle16 = new Microsoft.Xna.Framework.Rectangle(0, 0, texture2D12.Width, texture2D12.Height);
                            vector93 = rectangle16.Size() / 2f;
                            num279 = 0.9f;
                            num280 = 0f;
                            num281 = 0f;
                            flag29 = false;
                            vector96 = Vector2.Zero;
                            vector95 += proj.velocity.SafeNormalize(Vector2.Zero) * 8f;
                            num282 *= 0.75f;
                            vector97 -= proj.velocity;
                            Microsoft.Xna.Framework.Color color73 = new Microsoft.Xna.Framework.Color(194, 134, 22);
                            color73 *= 0.75f;
                            color73.A /= 2;
                            Microsoft.Xna.Framework.Color color74 = Microsoft.Xna.Framework.Color.Lerp(Microsoft.Xna.Framework.Color.Gold, Microsoft.Xna.Framework.Color.White, 0.5f);
                            color74.A /= 4;
                            color74 *= 0.85f;
                            color74 *= 0.75f;
                            Microsoft.Xna.Framework.Color gold2 = Microsoft.Xna.Framework.Color.Gold;
                            gold2.A = 180;
                            Microsoft.Xna.Framework.Color color75 = new Microsoft.Xna.Framework.Color(255, 150, 150, 127);
                            Microsoft.Xna.Framework.Color color76 = new Microsoft.Xna.Framework.Color(180, 140, 50) * 0.75f * 0.3f;
                            Microsoft.Xna.Framework.Color color77 = new Microsoft.Xna.Framework.Color(255, 50, 50, 0) * 0.5f * 0.3f;
                            float num291 = 0.5f;
                            float num292 = proj.rotation * num291 % 6.2831855f;
                            if (num292 < 0f)
{
                                num292 += 6.2831855f;
                            }
                            num292 /= 6.2831855f;
                            float num293 = Utils.Remap(num292, 0.15f, 0.5f, 0f, 1f, true) * Utils.Remap(num292, 0.5f, 0.85f, 1f, 0f, true);
                            num293 = 1f - num293;
                            color60 = Microsoft.Xna.Framework.Color.Lerp(gold2, color75, num293);
                            color61 = Microsoft.Xna.Framework.Color.Lerp(color73, color76, num293);
                            color62 = Microsoft.Xna.Framework.Color.Lerp(color74, color77, num293);
                            num283 += num293 * 0.2f;
                        }
                        Microsoft.Xna.Framework.Color color78 = color61;
                        Microsoft.Xna.Framework.Color color79 = color61;
                        Microsoft.Xna.Framework.Color color80 = color61;
                        if (flag29)
{
                            color78.A = b;
                            color79.A = b;
                            color80.A = b;
                        }
                        Texture2D texture2D13 = value16;
                        Vector2 vector98 = vector97 - Main.screenPosition + vector95;
                        Vector2 vector99 = vector96;
                        double num294 = (double)(6.2831855f * num278);
                        Vector2 vector49 = default(Vector2);
                        Main.EntitySpriteDraw(texture2D13, vector98 + vector99.RotatedBy(num294, vector49), new Microsoft.Xna.Framework.Rectangle?(rectangle17), color78, proj.velocity.ToRotation() + 1.5707964f, vector94, num279, SpriteEffects.None, 0f);
                        Texture2D texture2D14 = value16;
                        Vector2 vector100 = vector97 - Main.screenPosition + vector95;
                        Vector2 vector101 = vector96;
                        double num295 = (double)(6.2831855f * num278 + 2.0943952f);
                        vector49 = default(Vector2);
                        Main.EntitySpriteDraw(texture2D14, vector100 + vector101.RotatedBy(num295, vector49), new Microsoft.Xna.Framework.Rectangle?(rectangle17), color79, proj.velocity.ToRotation() + 1.5707964f, vector94, num280, SpriteEffects.None, 0f);
                        Texture2D texture2D15 = value16;
                        Vector2 vector102 = vector97 - Main.screenPosition + vector95;
                        Vector2 vector103 = vector96;
                        double num296 = (double)(6.2831855f * num278 + 4.1887903f);
                        vector49 = default(Vector2);
                        Main.EntitySpriteDraw(texture2D15, vector102 + vector103.RotatedBy(num296, vector49), new Microsoft.Xna.Framework.Rectangle?(rectangle17), color80, proj.velocity.ToRotation() + 1.5707964f, vector94, num281, SpriteEffects.None, 0f);
                        Vector2 vector104 = proj.Center - proj.velocity * 0.5f;
                        for (float num297 = 0f; num297 < 1f; num297 += 0.5f)
{
                            float num298 = num278 % 0.5f / 0.5f;
                            num298 = (num298 + num297) % 1f;
                            float num299 = num298 * 2f;
                            if (num299 > 1f)
{
                                num299 = 2f - num299;
                            }
                            Main.EntitySpriteDraw(value16, vector104 - Main.screenPosition + vector95, new Microsoft.Xna.Framework.Rectangle?(rectangle17), color62 * num299, proj.velocity.ToRotation() + 1.5707964f, vector94, (0.5f + num298 * 0.5f) * num282, SpriteEffects.None, 0f);
                        }
                        Main.EntitySpriteDraw(texture2D12, proj.Center - Main.screenPosition + new Vector2(0f, proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rectangle16), color60, proj.rotation, vector93, num283, spriteEffects2, 0f);
                        return;
                    }
                    if (proj.type == 674)
                    {
                        Texture2D value17 = TextureAssets.Extra[60].Value;
                        Vector2 vector105 = new Vector2(66f, 86f);
                        Vector2 vector106 = proj.Center - Main.screenPosition;
                        Vector2 vector107 = Vector2.One;
                        vector107 = new Vector2(4f, 1f) * 1.4f;
                        Microsoft.Xna.Framework.Color color81 = new Microsoft.Xna.Framework.Color(115, 0, 155, 0);
                        Microsoft.Xna.Framework.Color color82 = new Microsoft.Xna.Framework.Color(255, 180, 255, 0);
                        float num300 = 0f;
                        if (proj.ai[0] < 30f)
{
                            num300 = Utils.GetLerpValue(0f, 30f, proj.ai[0], true);
                        }
                        else if (proj.ai[0] < 40f)
{
                            num300 = 1f + Utils.GetLerpValue(30f, 40f, proj.ai[0], true);
                        }
                        Vector2 vector108 = new Vector2(1f, 1f);
                        Vector2 vector109 = new Vector2(0.8f, 2f);
                        if (num300 < 1f)
{
                            vector108.X *= num300;
                        }
                        vector107 *= num300;
                        if (num300 < 1f)
{
                            color81 *= num300;
                            color82 *= num300;
                        }
                        if (num300 > 1.5f)
{
                            float lerpValue7 = Utils.GetLerpValue(2f, 1.5f, num300, true);
                            color81 *= lerpValue7;
                            color82 *= lerpValue7;
                        }
                        float num301 = 0.42f;
                        color81 *= num301;
                        color82 *= num301;
                        Main.EntitySpriteDraw(value17, vector106, null, color81, 0f, vector105, vector107 * vector108, SpriteEffects.None, 0f);
                        Main.EntitySpriteDraw(value17, vector106, null, color82, 0f, vector105, vector107 * vector109, SpriteEffects.None, 0f);
                        Main.EntitySpriteDraw(TextureAssets.Extra[59].Value, vector106, null, color81, 0f, vector105, vector107 * vector108 * new Vector2(1f, 0.3f), SpriteEffects.None, 0f);
                        return;
                    }
                    if (proj.type == 440 || proj.type == 449 || proj.type == 606)
                    {
                        Microsoft.Xna.Framework.Rectangle rectangle18 = new Microsoft.Xna.Framework.Rectangle((int)Main.screenPosition.X - 500, (int)Main.screenPosition.Y - 500, Main.screenWidth + 1000, Main.screenHeight + 1000);
                        if (proj.getRect().Intersects(rectangle18))
{
                            Vector2 vector110 = new Vector2(proj.position.X - Main.screenPosition.X + num191 + (float)num190, proj.position.Y - Main.screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY);
                            float num302 = 100f;
                            float num303 = 3f;
                            if (proj.type == 606)
{
                                num302 = 150f;
                                num303 = 3f;
                            }
                            if (proj.ai[1] == 1f)
{
                                num302 = (float)((int)proj.localAI[0]);
                            }
                            for (int num304 = 1; num304 <= (int)proj.localAI[0]; num304++)
{
                                Vector2 vector111 = Vector2.Normalize(proj.velocity) * (float)num304 * num303;
                                Microsoft.Xna.Framework.Color color83 = proj.GetAlpha(color36);
                                color83 *= (num302 - (float)num304) / num302;
                                color83.A = 0;
                                Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, vector110 - vector111, null, color83, proj.rotation, new Vector2(num191, (float)(proj.height / 2 + num189)), proj.scale, spriteEffects2, 0f);
                            }
                            return;
                        }
                    }
                    else
                    {
                        if (proj.type == 85)
{
                            Main.DrawProj_Flamethrower(proj);
                            return;
                        }
                        if (proj.type == 1106)
{
                            Main.DrawProj_Flamethrower_Foxsparks(proj, player);
                            return;
                        }
                        if (proj.type == 687)
{
                            Vector2 vector112 = proj.Center;
                            vector112 -= Main.screenPosition;
                            float num305 = 40f;
                            float num306 = num305 * 2f;
                            float num307 = (float)proj.frameCounter / num305;
                            Texture2D value18 = TextureAssets.Projectile[proj.type].Value;
                            Microsoft.Xna.Framework.Color color84 = Microsoft.Xna.Framework.Color.Transparent;
                            Microsoft.Xna.Framework.Color color85 = new Microsoft.Xna.Framework.Color(255, 255, 255, 0);
                            Microsoft.Xna.Framework.Color color86 = new Microsoft.Xna.Framework.Color(180, 30, 30, 200);
                            Microsoft.Xna.Framework.Color color87 = new Microsoft.Xna.Framework.Color(0, 0, 0, 30);
                            ulong num308 = 1UL;
                            for (float num309 = 0f; num309 < 15f; num309 += 1f)
{
                                float num310 = Utils.RandomFloat(ref num308) * 0.25f - 0.125f;
                                Vector2 vector113 = (proj.rotation + num310).ToRotationVector2();
                                Vector2 vector114 = vector112 + vector113 * 400f;
                                float num311 = num307 + num309 * 0.06666667f;
                                int num312 = (int)(num311 / 0.06666667f);
                                num311 %= 1f;
                                if ((num311 <= num307 % 1f || (float)proj.frameCounter >= num305) && (num311 >= num307 % 1f || (float)proj.frameCounter < num306 - num305))
{
                                    if (num311 < 0.1f)
{
                                        color84 = Microsoft.Xna.Framework.Color.Lerp(Microsoft.Xna.Framework.Color.Transparent, color85, Utils.GetLerpValue(0f, 0.1f, num311, true));
                                    }
                                    else if (num311 < 0.35f)
{
                                        color84 = color85;
                                    }
                                    else if (num311 < 0.7f)
{
                                        color84 = Microsoft.Xna.Framework.Color.Lerp(color85, color86, Utils.GetLerpValue(0.35f, 0.7f, num311, true));
                                    }
                                    else if (num311 < 0.9f)
{
                                        color84 = Microsoft.Xna.Framework.Color.Lerp(color86, color87, Utils.GetLerpValue(0.7f, 0.9f, num311, true));
                                    }
                                    else if (num311 < 1f)
{
                                        color84 = Microsoft.Xna.Framework.Color.Lerp(color87, Microsoft.Xna.Framework.Color.Transparent, Utils.GetLerpValue(0.9f, 1f, num311, true));
                                    }
                                    else
{
                                        color84 = Microsoft.Xna.Framework.Color.Transparent;
                                    }
                                    float num313 = 0.9f + num311 * 0.8f;
                                    num313 *= num313;
                                    num313 *= 0.8f;
                                    Vector2 vector115 = Vector2.SmoothStep(vector112, vector114, num311);
                                    Microsoft.Xna.Framework.Rectangle rectangle19 = value18.Frame(1, 7, 0, (int)(num311 * 7f), 0, 0);
                                    Main.EntitySpriteDraw(value18, vector115, new Microsoft.Xna.Framework.Rectangle?(rectangle19), color84, proj.rotation + 6.2831855f * (num311 + Main.GlobalTimeWrappedHourly * 1.2f) * 0.2f + (float)num312 * 1.2566371f, rectangle19.Size() / 2f, num313, SpriteEffects.None, 0f);
                                }
                            }
                            return;
                        }
                        if (proj.type == 651)
{
                            if (proj.owner != Main.myPlayer)
{
                                return;
                            }
                            Player player4 = player;
                            Microsoft.Xna.Framework.Point point = new Vector2(proj.ai[0], proj.ai[1]).ToPoint();
                            Microsoft.Xna.Framework.Point point2 = proj.Center.ToTileCoordinates();
                            Microsoft.Xna.Framework.Color color88 = new Microsoft.Xna.Framework.Color(255, 255, 255, 0);
                            Microsoft.Xna.Framework.Color color89 = new Microsoft.Xna.Framework.Color(127, 127, 127, 0);
                            int num314 = 1;
                            float num315 = 0f;
                            WiresUI.Settings.MultiToolMode toolMode = WiresUI.Settings.ToolMode;
                            bool flag30 = (toolMode & WiresUI.Settings.MultiToolMode.Actuator) > (WiresUI.Settings.MultiToolMode)0;
                            if ((toolMode & WiresUI.Settings.MultiToolMode.Red) != (WiresUI.Settings.MultiToolMode)0)
{
                                num315 += 1f;
                                color89 = Microsoft.Xna.Framework.Color.Lerp(color89, Microsoft.Xna.Framework.Color.Red, 1f / num315);
                            }
                            if ((toolMode & WiresUI.Settings.MultiToolMode.Blue) != (WiresUI.Settings.MultiToolMode)0)
{
                                num315 += 1f;
                                color89 = Microsoft.Xna.Framework.Color.Lerp(color89, Microsoft.Xna.Framework.Color.Blue, 1f / num315);
                            }
                            if ((toolMode & WiresUI.Settings.MultiToolMode.Green) != (WiresUI.Settings.MultiToolMode)0)
{
                                num315 += 1f;
                                color89 = Microsoft.Xna.Framework.Color.Lerp(color89, new Microsoft.Xna.Framework.Color(0, 255, 0), 1f / num315);
                            }
                            if ((toolMode & WiresUI.Settings.MultiToolMode.Yellow) != (WiresUI.Settings.MultiToolMode)0)
{
                                num315 += 1f;
                                color89 = Microsoft.Xna.Framework.Color.Lerp(color89, new Microsoft.Xna.Framework.Color(255, 255, 0), 1f / num315);
                            }
                            if ((toolMode & WiresUI.Settings.MultiToolMode.Cutter) != (WiresUI.Settings.MultiToolMode)0)
{
                                color88 = new Microsoft.Xna.Framework.Color(50, 50, 50, 255);
                            }
                            color89.A = 0;
                            if (point == point2)
{
                                Vector2 vector116 = point2.ToVector2() * 16f - Main.screenPosition;
                                Microsoft.Xna.Framework.Rectangle rectangle20 = new Microsoft.Xna.Framework.Rectangle(0, 0, 16, 16);
                                if (flag30)
{
                                    Main.EntitySpriteDraw(TextureAssets.WireUi[11].Value, vector116, null, color88, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                                }
                                Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, vector116, new Microsoft.Xna.Framework.Rectangle?(rectangle20), color89, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                                rectangle20.Y = 18;
                                Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, vector116, new Microsoft.Xna.Framework.Rectangle?(rectangle20), color88, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                                return;
                            }
                            if (point.X == point2.X)
{
                                int num316 = point2.Y - point.Y;
                                int num317 = Math.Sign(num316);
                                Vector2 vector117 = point.ToVector2() * 16f - Main.screenPosition;
                                Microsoft.Xna.Framework.Rectangle rectangle21 = new Microsoft.Xna.Framework.Rectangle((num316 * num314 > 0) ? 72 : 18, 0, 16, 16);
                                if (flag30)
{
                                    Main.EntitySpriteDraw(TextureAssets.WireUi[11].Value, vector117, null, color88, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                                }
                                Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, vector117, new Microsoft.Xna.Framework.Rectangle?(rectangle21), color89, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                                rectangle21.Y = 18;
                                Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, vector117, new Microsoft.Xna.Framework.Rectangle?(rectangle21), color88, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                                for (int num318 = point.Y + num317; num318 != point2.Y; num318 += num317)
{
                                    vector117 = new Vector2((float)(point.X * 16), (float)(num318 * 16)) - Main.screenPosition;
                                    rectangle21.Y = 0;
                                    rectangle21.X = 90;
                                    if (flag30)
{
                                        Main.EntitySpriteDraw(TextureAssets.WireUi[11].Value, vector117, null, color88, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                                    }
                                    Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, vector117, new Microsoft.Xna.Framework.Rectangle?(rectangle21), color89, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                                    rectangle21.Y = 18;
                                    Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, vector117, new Microsoft.Xna.Framework.Rectangle?(rectangle21), color88, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                                }
                                vector117 = point2.ToVector2() * 16f - Main.screenPosition;
                                rectangle21 = new Microsoft.Xna.Framework.Rectangle((num316 * num314 > 0) ? 18 : 72, 0, 16, 16);
                                if (flag30)
{
                                    Main.EntitySpriteDraw(TextureAssets.WireUi[11].Value, vector117, null, color88, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                                }
                                Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, vector117, new Microsoft.Xna.Framework.Rectangle?(rectangle21), color89, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                                rectangle21.Y = 18;
                                Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, vector117, new Microsoft.Xna.Framework.Rectangle?(rectangle21), color88, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                                return;
                            }
                            if (point.Y == point2.Y)
{
                                int num319 = point2.X - point.X;
                                int num320 = Math.Sign(num319);
                                Vector2 vector118 = point.ToVector2() * 16f - Main.screenPosition;
                                Microsoft.Xna.Framework.Rectangle rectangle22 = new Microsoft.Xna.Framework.Rectangle((num319 > 0) ? 36 : 144, 0, 16, 16);
                                if (flag30)
{
                                    Main.EntitySpriteDraw(TextureAssets.WireUi[11].Value, vector118, null, color88, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                                }
                                Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, vector118, new Microsoft.Xna.Framework.Rectangle?(rectangle22), color89, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                                rectangle22.Y = 18;
                                Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, vector118, new Microsoft.Xna.Framework.Rectangle?(rectangle22), color88, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                                for (int num321 = point.X + num320; num321 != point2.X; num321 += num320)
{
                                    vector118 = new Vector2((float)(num321 * 16), (float)(point.Y * 16)) - Main.screenPosition;
                                    rectangle22.Y = 0;
                                    rectangle22.X = 180;
                                    if (flag30)
{
                                        Main.EntitySpriteDraw(TextureAssets.WireUi[11].Value, vector118, null, color88, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                                    }
                                    Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, vector118, new Microsoft.Xna.Framework.Rectangle?(rectangle22), color89, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                                    rectangle22.Y = 18;
                                    Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, vector118, new Microsoft.Xna.Framework.Rectangle?(rectangle22), color88, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                                }
                                vector118 = point2.ToVector2() * 16f - Main.screenPosition;
                                rectangle22 = new Microsoft.Xna.Framework.Rectangle((num319 > 0) ? 144 : 36, 0, 16, 16);
                                if (flag30)
{
                                    Main.EntitySpriteDraw(TextureAssets.WireUi[11].Value, vector118, null, color88, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                                }
                                Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, vector118, new Microsoft.Xna.Framework.Rectangle?(rectangle22), color89, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                                rectangle22.Y = 18;
                                Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, vector118, new Microsoft.Xna.Framework.Rectangle?(rectangle22), color88, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                                return;
                            }
                            Math.Abs(point.X - point2.X);
                            Math.Abs(point.Y - point2.Y);
                            int num322 = Math.Sign(point2.X - point.X);
                            int num323 = Math.Sign(point2.Y - point.Y);
                            Microsoft.Xna.Framework.Point point3 = default(Microsoft.Xna.Framework.Point);
                            bool flag31 = false;
                            bool flag32 = player4.direction == 1;
                            int num324;
                            int num325;
                            int num326;
                            if (flag32)
{
                                point3.X = point.X;
                                num324 = point.Y;
                                num325 = point2.Y;
                                num326 = num323;
                            }
                            else
{
                                point3.Y = point.Y;
                                num324 = point.X;
                                num325 = point2.X;
                                num326 = num322;
                            }
                            Vector2 vector119 = point.ToVector2() * 16f - Main.screenPosition;
                            Microsoft.Xna.Framework.Rectangle rectangle23 = new Microsoft.Xna.Framework.Rectangle(0, 0, 16, 16);
                            if (!flag32)
{
                                rectangle23.X = ((num326 > 0) ? 36 : 144);
                            }
                            else
{
                                rectangle23.X = ((num326 > 0) ? 72 : 18);
                            }
                            if (flag30)
{
                                Main.EntitySpriteDraw(TextureAssets.WireUi[11].Value, vector119, null, color88, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                            }
                            Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, vector119, new Microsoft.Xna.Framework.Rectangle?(rectangle23), color89, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                            rectangle23.Y = 18;
                            Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, vector119, new Microsoft.Xna.Framework.Rectangle?(rectangle23), color88, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                            int num327 = num324 + num326;
                            while (num327 != num325 && !flag31)
{
                                if (flag32)
{
                                    point3.Y = num327;
                                }
                                else
{
                                    point3.X = num327;
                                }
                                if (WorldGen.InWorld(point3.X, point3.Y, 1) && Main.tile[point3.X, point3.Y] != null)
{
                                    vector119 = point3.ToVector2() * 16f - Main.screenPosition;
                                    rectangle23.Y = 0;
                                    if (!flag32)
{
                                        rectangle23.X = 180;
                                    }
                                    else
{
                                        rectangle23.X = 90;
                                    }
                                    if (flag30)
{
                                        Main.EntitySpriteDraw(TextureAssets.WireUi[11].Value, vector119, null, color88, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                                    }
                                    Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, vector119, new Microsoft.Xna.Framework.Rectangle?(rectangle23), color89, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                                    rectangle23.Y = 18;
                                    Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, vector119, new Microsoft.Xna.Framework.Rectangle?(rectangle23), color88, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                                }
                                num327 += num326;
                            }
                            if (flag32)
{
                                point3.Y = point2.Y;
                                num324 = point.X;
                                num325 = point2.X;
                                num326 = num322;
                            }
                            else
{
                                point3.X = point2.X;
                                num324 = point.Y;
                                num325 = point2.Y;
                                num326 = num323;
                            }
                            vector119 = point3.ToVector2() * 16f - Main.screenPosition;
                            rectangle23 = new Microsoft.Xna.Framework.Rectangle(0, 0, 16, 16);
                            if (!flag32)
{
                                rectangle23.X += ((num322 > 0) ? 144 : 36);
                                rectangle23.X += ((num323 * num314 > 0) ? 72 : 18);
                            }
                            else
{
                                rectangle23.X += ((num322 > 0) ? 36 : 144);
                                rectangle23.X += ((num323 * num314 > 0) ? 18 : 72);
                            }
                            if (flag30)
{
                                Main.EntitySpriteDraw(TextureAssets.WireUi[11].Value, vector119, null, color88, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                            }
                            Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, vector119, new Microsoft.Xna.Framework.Rectangle?(rectangle23), color89, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                            rectangle23.Y = 18;
                            Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, vector119, new Microsoft.Xna.Framework.Rectangle?(rectangle23), color88, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                            int num328 = num324 + num326;
                            while (num328 != num325 && !flag31)
{
                                if (!flag32)
{
                                    point3.Y = num328;
                                }
                                else
{
                                    point3.X = num328;
                                }
                                if (WorldGen.InWorld(point3.X, point3.Y, 1) && Main.tile[point3.X, point3.Y] != null)
{
                                    vector119 = point3.ToVector2() * 16f - Main.screenPosition;
                                    rectangle23.Y = 0;
                                    if (!flag32)
{
                                        rectangle23.X = 90;
                                    }
                                    else
{
                                        rectangle23.X = 180;
                                    }
                                    if (flag30)
{
                                        Main.EntitySpriteDraw(TextureAssets.WireUi[11].Value, vector119, null, color88, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                                    }
                                    Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, vector119, new Microsoft.Xna.Framework.Rectangle?(rectangle23), color89, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                                    rectangle23.Y = 18;
                                    Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, vector119, new Microsoft.Xna.Framework.Rectangle?(rectangle23), color88, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                                }
                                num328 += num326;
                            }
                            vector119 = point2.ToVector2() * 16f - Main.screenPosition;
                            rectangle23 = new Microsoft.Xna.Framework.Rectangle(0, 0, 16, 16);
                            if (!flag32)
{
                                rectangle23.X += ((num323 * num314 > 0) ? 18 : 72);
                            }
                            else
{
                                rectangle23.X += ((num322 > 0) ? 144 : 36);
                            }
                            if (flag30)
{
                                Main.EntitySpriteDraw(TextureAssets.WireUi[11].Value, vector119, null, color88, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                            }
                            Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, vector119, new Microsoft.Xna.Framework.Rectangle?(rectangle23), color89, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                            rectangle23.Y = 18;
                            Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, vector119, new Microsoft.Xna.Framework.Rectangle?(rectangle23), color88, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                            return;
                        }
                        else
{
                            if (proj.type == 586)
{
                                float num329 = 300f;
                                if (proj.ai[0] >= 100f)
{
                                    num329 = MathHelper.Lerp(300f, 600f, (proj.ai[0] - 100f) / 200f);
                                }
                                if (num329 > 600f)
{
                                    num329 = 600f;
                                }
                                if (proj.ai[0] >= 500f)
{
                                    num329 = MathHelper.Lerp(600f, 1200f, (proj.ai[0] - 500f) / 100f);
                                }
                                float rotation = proj.rotation;
                                Texture2D value19 = TextureAssets.Projectile[proj.type].Value;
                                int num330 = (int)(proj.ai[0] / 6f);
                                Vector2 vector120 = new Vector2(0f, -num329);
                                int num331 = 0;
                                while ((float)num331 < 10f)
{
                                    Microsoft.Xna.Framework.Rectangle rectangle24 = value19.Frame(1, 5, 0, (num330 + num331) % 5, 0, 0);
                                    float num332 = rotation + 0.62831855f * (float)num331;
                                    Vector2 vector121 = vector120;
                                    double num333 = (double)num332;
                                    Vector2 vector49 = default(Vector2);
                                    Vector2 vector122 = vector121.RotatedBy(num333, vector49) / 3f + proj.Center;
                                    Microsoft.Xna.Framework.Color color90 = proj.GetAlpha(Lighting.GetColor(vector122.ToTileCoordinates()));
                                    color90.A /= 2;
                                    Main.EntitySpriteDraw(value19, vector122 - Main.screenPosition, new Microsoft.Xna.Framework.Rectangle?(rectangle24), color90, num332, rectangle24.Size() / 2f, proj.scale, SpriteEffects.None, 0f);
                                    num331++;
                                }
                                int num334 = 0;
                                while ((float)num334 < 20f)
{
                                    Microsoft.Xna.Framework.Rectangle rectangle25 = value19.Frame(1, 5, 0, (num330 + num334) % 5, 0, 0);
                                    float num335 = -rotation + 0.31415927f * (float)num334;
                                    num335 *= 2f;
                                    Vector2 vector123 = vector120;
                                    double num336 = (double)num335;
                                    Vector2 vector49 = default(Vector2);
                                    Vector2 vector124 = vector123.RotatedBy(num336, vector49) + proj.Center;
                                    Microsoft.Xna.Framework.Color color90 = proj.GetAlpha(Lighting.GetColor(vector124.ToTileCoordinates()));
                                    color90.A /= 2;
                                    Main.EntitySpriteDraw(value19, vector124 - Main.screenPosition, new Microsoft.Xna.Framework.Rectangle?(rectangle25), color90, num335, rectangle25.Size() / 2f, proj.scale, SpriteEffects.None, 0f);
                                    num334++;
                                }
                                return;
                            }
                            if (proj.type == 536 || proj.type == 607)
{
                                Texture2D value20 = TextureAssets.Projectile[proj.type].Value;
                                Vector2 vector125 = proj.position + new Vector2((float)proj.width, (float)proj.height) / 2f + Vector2.UnitY * proj.gfxOffY - Main.screenPosition;
                                Vector2 vector126 = new Vector2(1f, proj.velocity.Length() / (float)value20.Height);
                                Main.EntitySpriteDraw(value20, vector125, null, proj.GetAlpha(color36), proj.rotation, value20.Frame(1, 1, 0, 0, 0, 0).Bottom(), vector126, spriteEffects2, 0f);
                                return;
                            }
                            if (proj.type == 591)
{
                                Texture2D value21 = TextureAssets.Projectile[proj.type].Value;
                                Vector2 vector127 = proj.position + new Vector2((float)proj.width, (float)proj.height) / 2f + Vector2.UnitY * proj.gfxOffY - Main.screenPosition;
                                Vector2 vector128 = new Vector2(1f, proj.velocity.Length() / (float)value21.Height);
                                this.LoadNPC(139);
                                Texture2D value22 = TextureAssets.Npc[139].Value;
                                bool flag33 = proj.velocity.X >= 0f;
                                float num337 = proj.velocity.ToRotation() + 3.1415927f;
                                SpriteEffects spriteEffects5 = (flag33 ? SpriteEffects.FlipVertically : SpriteEffects.None);
                                float num338 = 1f - proj.Opacity;
                                float num339 = Utils.Remap(num338, 0f, 0.2f, 0f, 1f, true) * Utils.Remap(num338, 0.2f, 1f, 1f, 0f, true);
                                Main.EntitySpriteDraw(value22, vector127, null, color36 * num339, num337, value22.Size() / 2f, 0.65f, spriteEffects5, 0f);
                                Microsoft.Xna.Framework.Color color91 = new Microsoft.Xna.Framework.Color(255, 189, 163, 127) * num339;
                                Microsoft.Xna.Framework.Color color92 = new Microsoft.Xna.Framework.Color(255, 21, 21, 127) * num339;
                                Microsoft.Xna.Framework.Rectangle rectangle26 = value21.Frame(2, 1, 0, 0, 0, 0);
                                Vector2 vector129 = rectangle26.Bottom();
                                Main.EntitySpriteDraw(value21, vector127, new Microsoft.Xna.Framework.Rectangle?(rectangle26), color91, proj.rotation, vector129, vector128, spriteEffects2, 0f);
                                rectangle26 = value21.Frame(2, 1, 1, 0, 0, 0);
                                Main.EntitySpriteDraw(value21, vector127, new Microsoft.Xna.Framework.Rectangle?(rectangle26), color92, proj.rotation, vector129, vector128, spriteEffects2, 0f);
                                return;
                            }
                            if (proj.type == 688 || proj.type == 689 || proj.type == 690)
{
                                Texture2D value23 = TextureAssets.Projectile[proj.type].Value;
                                Vector2 vector130 = proj.Top + Vector2.UnitY * proj.gfxOffY - Main.screenPosition;
                                Microsoft.Xna.Framework.Rectangle rectangle27 = value23.Frame(1, Main.projFrames[proj.type], 0, proj.frame, 0, 0);
                                Vector2 vector131 = rectangle27.Size() * new Vector2(0.5f, 0f);
                                Microsoft.Xna.Framework.Color color93 = Microsoft.Xna.Framework.Color.Lerp(proj.GetAlpha(color36), Microsoft.Xna.Framework.Color.White, 0.5f);
                                Microsoft.Xna.Framework.Color color94 = color93;
                                color94.A = 127;
                                Texture2D texture2D16 = null;
                                Texture2D texture2D17 = null;
                                switch (proj.type)
{
                                case 688:
                                    texture2D16 = TextureAssets.GlowMask[228].Value;
                                    texture2D17 = TextureAssets.Extra[86].Value;
                                    break;
                                case 689:
                                    texture2D16 = TextureAssets.GlowMask[229].Value;
                                    texture2D17 = TextureAssets.Extra[87].Value;
                                    break;
                                case 690:
                                    texture2D16 = TextureAssets.GlowMask[230].Value;
                                    texture2D17 = TextureAssets.Extra[88].Value;
                                    break;
                                }
                                Main.EntitySpriteDraw(value23, vector130, new Microsoft.Xna.Framework.Rectangle?(rectangle27), color93, proj.rotation, vector131, proj.scale, spriteEffects2, 0f);
                                if (texture2D16 != null)
{
                                    Main.EntitySpriteDraw(texture2D16, vector130, new Microsoft.Xna.Framework.Rectangle?(rectangle27), color94, proj.rotation, vector131, proj.scale, spriteEffects2, 0f);
                                }
                                if (texture2D17 != null)
{
                                    Vector2 vector132 = proj.Center + Vector2.UnitY * proj.gfxOffY - Main.screenPosition;
                                    rectangle27 = texture2D17.Frame(1, 1, 0, 0, 0, 0);
                                    vector131 = rectangle27.Size() * new Vector2(0.5f, 1f);
                                    vector131.Y -= 2f;
                                    Main.EntitySpriteDraw(texture2D17, vector132, new Microsoft.Xna.Framework.Rectangle?(rectangle27), color93, proj.rotation, vector131, proj.scale, spriteEffects2, 0f);
                                    return;
                                }
                            }
                            else
{
                                if (proj.type == 694 || proj.type == 695 || proj.type == 696)
{
                                    Texture2D value24 = TextureAssets.Projectile[proj.type].Value;
                                    Vector2 vector133 = proj.Bottom + Vector2.UnitY * proj.gfxOffY - Main.screenPosition;
                                    Microsoft.Xna.Framework.Rectangle rectangle28 = value24.Frame(1, Main.projFrames[proj.type], 0, proj.frame, 0, 0);
                                    Vector2 vector134 = rectangle28.Size() * new Vector2(0.5f, 1f);
                                    vector134.Y -= 8f;
                                    num22 = proj.type;
                                    if (num22 - 694 <= 1)
{
                                        vector134.X += 3f;
                                    }
                                    Microsoft.Xna.Framework.Color color95 = Microsoft.Xna.Framework.Color.Lerp(proj.GetAlpha(color36), Microsoft.Xna.Framework.Color.White, 0f);
                                    Main.EntitySpriteDraw(value24, vector133, new Microsoft.Xna.Framework.Rectangle?(rectangle28), color95, proj.rotation, vector134, proj.scale, spriteEffects2, 0f);
                                    Main.EntitySpriteDraw(value24, vector133, new Microsoft.Xna.Framework.Rectangle?(rectangle28), color95 * 0.3f, proj.rotation, vector134, proj.scale * 1.1f, spriteEffects2, 0f);
                                    return;
                                }
                                if (proj.type == 409)
{
                                    Texture2D value25 = TextureAssets.Projectile[proj.type].Value;
                                    int num340 = TextureAssets.Projectile[proj.type].Height() / Main.projFrames[proj.type];
                                    int num341 = num340 * proj.frame;
                                    int num342 = 10;
                                    int num343 = 2;
                                    float num344 = 0.5f;
                                    for (int num345 = 1; num345 < num342; num345 += num343)
{
                                        Vector2[] oldPos = proj.oldPos;
                                        Microsoft.Xna.Framework.Color color96 = color36;
                                        color96 = proj.GetAlpha(color96);
                                        color96 *= (float)(num342 - num345) / 15f;
                                        proj.oldPos[num345] - Main.screenPosition + new Vector2(num191 + (float)num190, (float)(proj.height / 2) + proj.gfxOffY);
                                        Main.EntitySpriteDraw(value25, proj.oldPos[num345] + new Vector2((float)proj.width, (float)proj.height) / 2f - Main.screenPosition + new Vector2(0f, proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, num341, value25.Width, num340)), color96, proj.rotation, new Vector2((float)value25.Width / 2f, (float)num340 / 2f), MathHelper.Lerp(proj.scale, num344, (float)num345 / 15f), spriteEffects2, 0f);
                                    }
                                    Main.EntitySpriteDraw(value25, proj.Center - Main.screenPosition + new Vector2(0f, proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, num341, value25.Width, num340)), proj.GetAlpha(color36), proj.rotation, new Vector2((float)value25.Width / 2f, (float)num340 / 2f), proj.scale, spriteEffects2, 0f);
                                    return;
                                }
                                if (proj.type == 437)
{
                                    Texture2D value26 = TextureAssets.Projectile[proj.type].Value;
                                    int num346 = TextureAssets.Projectile[proj.type].Height() / Main.projFrames[proj.type];
                                    int num347 = num346 * proj.frame;
                                    int num348 = 10;
                                    int num349 = 2;
                                    float num350 = 0.2f;
                                    for (int num351 = 1; num351 < num348; num351 += num349)
{
                                        Vector2[] oldPos2 = proj.oldPos;
                                        Microsoft.Xna.Framework.Color color97 = color36;
                                        color97 = proj.GetAlpha(color97);
                                        color97 *= (float)(num348 - num351) / 15f;
                                        proj.oldPos[num351] - Main.screenPosition + new Vector2(num191 + (float)num190, (float)(proj.height / 2) + proj.gfxOffY);
                                        Main.EntitySpriteDraw(value26, proj.oldPos[num351] + new Vector2((float)proj.width, (float)proj.height) / 2f - Main.screenPosition + new Vector2(0f, proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, num347, value26.Width, num346)), color97, proj.rotation, new Vector2((float)value26.Width / 2f, (float)num346 / 2f), MathHelper.Lerp(proj.scale, num350, (float)num351 / 15f), spriteEffects2, 0f);
                                    }
                                    Main.EntitySpriteDraw(value26, proj.Center - Main.screenPosition + new Vector2(0f, proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, num347, value26.Width, num346)), Microsoft.Xna.Framework.Color.White, proj.rotation, new Vector2((float)value26.Width / 2f, (float)num346 / 2f), proj.scale + 0.2f, spriteEffects2, 0f);
                                    Main.EntitySpriteDraw(value26, proj.Center - Main.screenPosition + new Vector2(0f, proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, num347, value26.Width, num346)), proj.GetAlpha(Microsoft.Xna.Framework.Color.White), proj.rotation, new Vector2((float)value26.Width / 2f, (float)num346 / 2f), proj.scale + 0.2f, spriteEffects2, 0f);
                                    return;
                                }
                                if (proj.type == 384 || proj.type == 386)
{
                                    Texture2D value27 = TextureAssets.Projectile[proj.type].Value;
                                    int num352 = TextureAssets.Projectile[proj.type].Height() / Main.projFrames[proj.type];
                                    int num353 = num352 * proj.frame;
                                    Main.EntitySpriteDraw(value27, proj.Center - Main.screenPosition + new Vector2(0f, proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, num353, value27.Width, num352)), proj.GetAlpha(color36), proj.rotation, new Vector2((float)value27.Width / 2f, (float)num352 / 2f), proj.scale, spriteEffects2, 0f);
                                    return;
                                }
                                if (proj.type == 439 || proj.type == 460 || proj.type == 600 || proj.type == 615 || proj.type == 630 || proj.type == 633 || proj.type == 705 || proj.type == 714)
{
                                    Texture2D texture2D18 = TextureAssets.Projectile[proj.type].Value;
                                    if (player.gravDir == -1f)
{
                                        if (proj.type == 705)
{
                                            spriteEffects2 |= SpriteEffects.FlipVertically;
                                        }
                                        if (proj.type == 615 || proj.type == 714)
{
                                            if (player.direction == 1)
{
                                                spriteEffects2 = SpriteEffects.FlipVertically;
                                            }
                                            else if (player.direction == -1)
{
                                                spriteEffects2 = SpriteEffects.FlipHorizontally | SpriteEffects.FlipVertically;
                                            }
                                        }
                                        else if (proj.type == 600 || proj.type == 439)
{
                                            if (player.direction == 1)
{
                                                spriteEffects2 = SpriteEffects.FlipHorizontally;
                                            }
                                            else if (player.direction == -1)
{
                                                spriteEffects2 = SpriteEffects.None;
                                            }
                                        }
                                    }
                                    int num354 = TextureAssets.Projectile[proj.type].Height() / Main.projFrames[proj.type];
                                    int num355 = num354 * proj.frame;
                                    Vector2 vector135 = (proj.position + new Vector2((float)proj.width, (float)proj.height) / 2f + Vector2.UnitY * proj.gfxOffY - Main.screenPosition).Floor();
                                    float num356 = 1f;
                                    if (player.shroomiteStealth && player.inventory[player.selectedItem].ranged)
{
                                        float num357 = player.stealth;
                                        if ((double)num357 < 0.03)
{
                                            num357 = 0.03f;
                                        }
                                        float num358 = (1f + num357 * 10f) / 11f;
                                        color36 *= num357;
                                        num356 = num357;
                                    }
                                    if (player.setVortex && player.inventory[player.selectedItem].ranged)
{
                                        float num359 = player.stealth;
                                        if ((double)num359 < 0.03)
{
                                            num359 = 0.03f;
                                        }
                                        float num360 = (1f + num359 * 10f) / 11f;
                                        color36 = color36.MultiplyRGBA(new Microsoft.Xna.Framework.Color(Vector4.Lerp(Vector4.One, new Vector4(0f, 0.12f, 0.16f, 0f), 1f - num359)));
                                        num356 = num359;
                                    }
                                    if (proj.type == 714)
{
                                        num355 = 0;
                                        Main.instance.LoadItem(3930);
                                        texture2D18 = TextureAssets.Item[3930].Value;
                                    }
                                    Main.EntitySpriteDraw(texture2D18, vector135, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, num355, texture2D18.Width, num354)), proj.GetAlpha(color36), proj.rotation, new Vector2((float)texture2D18.Width / 2f, (float)num354 / 2f), proj.scale, spriteEffects2, 0f);
                                    if (proj.type == 439)
{
                                        Main.EntitySpriteDraw(TextureAssets.GlowMask[35].Value, vector135, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, num355, texture2D18.Width, num354)), new Microsoft.Xna.Framework.Color(255, 255, 255, 0) * num356, proj.rotation, new Vector2((float)texture2D18.Width / 2f, (float)num354 / 2f), proj.scale, spriteEffects2, 0f);
                                        return;
                                    }
                                    if (proj.type == 714)
{
                                        num355 = num354 * proj.frame;
                                        Microsoft.Xna.Framework.Color color98 = Main.hslToRgb(proj.ai[0] / 90f % 1f, 1f, 0.5f, byte.MaxValue);
                                        color98.A = 120;
                                        Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, vector135, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, num355, texture2D18.Width, num354)), color98 * num356, proj.rotation, new Vector2((float)texture2D18.Width / 2f, (float)num354 / 2f), proj.scale, spriteEffects2, 0f);
                                        return;
                                    }
                                    if (proj.type == 615)
{
                                        Main.EntitySpriteDraw(TextureAssets.GlowMask[192].Value, vector135, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, num355, texture2D18.Width, num354)), new Microsoft.Xna.Framework.Color(255, 255, 255, 127) * num356, proj.rotation, new Vector2((float)texture2D18.Width / 2f, (float)num354 / 2f), proj.scale, spriteEffects2, 0f);
                                        return;
                                    }
                                    if (proj.type == 630)
{
                                        Main.EntitySpriteDraw(TextureAssets.GlowMask[200].Value, vector135, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, num355, texture2D18.Width, num354)), new Microsoft.Xna.Framework.Color(255, 255, 255, 127) * num356, proj.rotation, new Vector2((float)texture2D18.Width / 2f, (float)num354 / 2f), proj.scale, spriteEffects2, 0f);
                                        if (proj.localAI[0] > 0f)
{
                                            int num361 = 6 - (int)(proj.localAI[0] / 1f);
                                            texture2D18 = TextureAssets.Extra[65].Value;
                                            Main.EntitySpriteDraw(texture2D18, vector135 + Vector2.Normalize(proj.velocity) * 2f, new Microsoft.Xna.Framework.Rectangle?(texture2D18.Frame(1, 6, 0, num361, 0, 0)), new Microsoft.Xna.Framework.Color(255, 255, 255, 127) * num356, proj.rotation, new Vector2((float)(((spriteEffects2 & SpriteEffects.FlipHorizontally) != SpriteEffects.None) ? texture2D18.Width : 0), (float)num354 / 2f - 2f), proj.scale, spriteEffects2, 0f);
                                            return;
                                        }
                                    }
                                    else
{
                                        if (proj.type == 600)
{
                                            Microsoft.Xna.Framework.Color portalColor = PortalHelper.GetPortalColor(proj.owner, (int)proj.ai[1]);
                                            portalColor.A = 70;
                                            Main.EntitySpriteDraw(TextureAssets.GlowMask[173].Value, vector135, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, num355, texture2D18.Width, num354)), portalColor, proj.rotation, new Vector2((float)texture2D18.Width / 2f, (float)num354 / 2f), proj.scale, spriteEffects2, 0f);
                                            return;
                                        }
                                        if (proj.type == 460)
{
                                            if (Math.Abs(proj.rotation - 1.5707964f) > 1.5707964f)
{
                                                spriteEffects2 |= SpriteEffects.FlipVertically;
                                            }
                                            Main.EntitySpriteDraw(TextureAssets.GlowMask[102].Value, vector135, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, num355, texture2D18.Width, num354)), new Microsoft.Xna.Framework.Color(255, 255, 255, 0), proj.rotation - 1.5707964f, new Vector2((float)texture2D18.Width / 2f, (float)num354 / 2f), proj.scale, spriteEffects2, 0f);
                                            if (proj.ai[0] > 180f && Main.projectile[(int)proj.ai[1]].type == 461)
{
                                                this.DrawProj((int)proj.ai[1]);
                                                return;
                                            }
                                        }
                                        else if (proj.type == 633)
{
                                            float num362 = (float)Math.Cos((double)(6.2831855f * (proj.ai[0] / 30f))) * 2f + 2f;
                                            if (proj.ai[0] > 120f)
{
                                                num362 = 4f;
                                            }
                                            for (float num363 = 0f; num363 < 4f; num363 += 1f)
{
                                                Texture2D texture2D19 = texture2D18;
                                                Vector2 vector136 = vector135;
                                                Vector2 unitY = Vector2.UnitY;
                                                double num364 = (double)(num363 * 6.2831855f / 4f);
                                                Vector2 vector49 = default(Vector2);
                                                Main.EntitySpriteDraw(texture2D19, vector136 + unitY.RotatedBy(num364, vector49) * num362, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, num355, texture2D18.Width, num354)), proj.GetAlpha(color36).MultiplyRGBA(new Microsoft.Xna.Framework.Color(255, 255, 255, 0)) * 0.03f, proj.rotation, new Vector2((float)texture2D18.Width / 2f, (float)num354 / 2f), proj.scale, spriteEffects2, 0f);
                                            }
                                            return;
                                        }
                                    }
                                }
                                else
{
                                    if (proj.type == 442)
{
                                        Texture2D value28 = TextureAssets.Projectile[proj.type].Value;
                                        int num365 = TextureAssets.Projectile[proj.type].Height() / Main.projFrames[proj.type];
                                        int num366 = num365 * proj.frame;
                                        Vector2 vector137 = proj.position + new Vector2((float)proj.width, (float)proj.height) / 2f + Vector2.UnitY * proj.gfxOffY - Main.screenPosition;
                                        Main.EntitySpriteDraw(value28, vector137, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, num366, value28.Width, num365)), proj.GetAlpha(color36), proj.rotation, new Vector2((float)value28.Width / 2f, (float)num365 / 2f), proj.scale, spriteEffects2, 0f);
                                        Main.EntitySpriteDraw(TextureAssets.GlowMask[37].Value, vector137, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, num366, value28.Width, num365)), new Microsoft.Xna.Framework.Color(255, 255, 255, 0) * (1f - (float)proj.alpha / 255f), proj.rotation, new Vector2((float)value28.Width / 2f, (float)num365 / 2f), proj.scale, spriteEffects2, 0f);
                                        return;
                                    }
                                    if (proj.type == 447)
{
                                        Texture2D value29 = TextureAssets.Projectile[proj.type].Value;
                                        Texture2D value30 = TextureAssets.Extra[4].Value;
                                        int num367 = value29.Height / Main.projFrames[proj.type];
                                        int num368 = num367 * proj.frame;
                                        int num369 = value30.Height / Main.projFrames[proj.type];
                                        int num370 = num369 * proj.frame;
                                        Microsoft.Xna.Framework.Rectangle rectangle29 = new Microsoft.Xna.Framework.Rectangle(0, num370, value30.Width, num369);
                                        Vector2 vector138 = proj.position + new Vector2((float)proj.width, 0f) / 2f + Vector2.UnitY * proj.gfxOffY - Main.screenPosition;
                                        Main.EntitySpriteDraw(TextureAssets.Extra[4].Value, vector138, new Microsoft.Xna.Framework.Rectangle?(rectangle29), proj.GetAlpha(color36), proj.rotation, new Vector2((float)(value30.Width / 2), 0f), proj.scale, spriteEffects2, 0f);
                                        int num371 = proj.height - num367 - 14;
                                        if (num371 < 0)
{
                                            num371 = 0;
                                        }
                                        if (num371 > 0)
{
                                            if (num370 == num369 * 3)
{
                                                num370 = num369 * 2;
                                            }
                                            Main.EntitySpriteDraw(TextureAssets.Extra[4].Value, vector138 + Vector2.UnitY * (float)(num369 - 1), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, num370 + num369 - 1, value30.Width, 1)), proj.GetAlpha(color36), proj.rotation, new Vector2((float)(value30.Width / 2), 0f), new Vector2(1f, (float)num371), spriteEffects2, 0f);
                                        }
                                        rectangle29.Width = value29.Width;
                                        rectangle29.Y = num368;
                                        Main.EntitySpriteDraw(value29, vector138 + Vector2.UnitY * (float)(num369 - 1 + num371), new Microsoft.Xna.Framework.Rectangle?(rectangle29), proj.GetAlpha(color36), proj.rotation, new Vector2((float)value29.Width / 2f, 0f), proj.scale, spriteEffects2, 0f);
                                        return;
                                    }
                                    if (proj.type == 455)
{
                                        if (proj.velocity == Vector2.Zero)
{
                                            return;
                                        }
                                        Texture2D value31 = TextureAssets.Projectile[proj.type].Value;
                                        Texture2D value32 = TextureAssets.Extra[21].Value;
                                        Texture2D value33 = TextureAssets.Extra[22].Value;
                                        float num372 = proj.localAI[1];
                                        Microsoft.Xna.Framework.Color color99 = new Microsoft.Xna.Framework.Color(255, 255, 255, 0) * 0.9f;
                                        Main.EntitySpriteDraw(value31, proj.Center - Main.screenPosition, null, color99, proj.rotation, value31.Size() / 2f, proj.scale, SpriteEffects.None, 0f);
                                        num372 -= (float)(value31.Height / 2 + value33.Height) * proj.scale;
                                        Vector2 vector139 = proj.Center;
                                        vector139 += proj.velocity * proj.scale * (float)value31.Height / 2f;
                                        if (num372 > 0f)
{
                                            float num373 = 0f;
                                            Microsoft.Xna.Framework.Rectangle rectangle30 = new Microsoft.Xna.Framework.Rectangle(0, 16 * (proj.timeLeft / 3 % 5), value32.Width, 16);
                                            while (num373 + 1f < num372)
{
                                                if (num372 - num373 < (float)rectangle30.Height)
{
                                                    rectangle30.Height = (int)(num372 - num373);
                                                }
                                                Main.EntitySpriteDraw(value32, vector139 - Main.screenPosition, new Microsoft.Xna.Framework.Rectangle?(rectangle30), color99, proj.rotation, new Vector2((float)(rectangle30.Width / 2), 0f), proj.scale, SpriteEffects.None, 0f);
                                                num373 += (float)rectangle30.Height * proj.scale;
                                                vector139 += proj.velocity * (float)rectangle30.Height * proj.scale;
                                                rectangle30.Y += 16;
                                                if (rectangle30.Y + rectangle30.Height > value32.Height)
{
                                                    rectangle30.Y = 0;
                                                }
                                            }
                                        }
                                        Main.EntitySpriteDraw(value33, vector139 - Main.screenPosition, null, color99, proj.rotation, value33.Frame(1, 1, 0, 0, 0, 0).Top(), proj.scale, SpriteEffects.None, 0f);
                                        return;
                                    }
                                    else if (proj.type == 461)
{
                                        if (proj.velocity == Vector2.Zero)
{
                                            return;
                                        }
                                        Texture2D value34 = TextureAssets.Projectile[proj.type].Value;
                                        float num374 = proj.localAI[1];
                                        Microsoft.Xna.Framework.Color color100 = new Microsoft.Xna.Framework.Color(255, 255, 255, 0) * 0.9f;
                                        Microsoft.Xna.Framework.Rectangle rectangle31 = new Microsoft.Xna.Framework.Rectangle(0, 0, value34.Width, 22);
                                        Main.EntitySpriteDraw(value34, proj.Center.Floor() - Main.screenPosition, new Microsoft.Xna.Framework.Rectangle?(rectangle31), color100, proj.rotation, rectangle31.Size() / 2f, proj.scale, SpriteEffects.None, 0f);
                                        num374 -= 33f * proj.scale;
                                        Vector2 vector140 = proj.Center.Floor();
                                        vector140 += proj.velocity * proj.scale * 10.5f;
                                        rectangle31 = new Microsoft.Xna.Framework.Rectangle(0, 25, value34.Width, 28);
                                        if (num374 > 0f)
{
                                            float num375 = 0f;
                                            while (num375 + 1f < num374)
{
                                                if (num374 - num375 < (float)rectangle31.Height)
{
                                                    rectangle31.Height = (int)(num374 - num375);
                                                }
                                                Main.EntitySpriteDraw(value34, vector140 - Main.screenPosition, new Microsoft.Xna.Framework.Rectangle?(rectangle31), color100, proj.rotation, new Vector2((float)(rectangle31.Width / 2), 0f), proj.scale, SpriteEffects.None, 0f);
                                                num375 += (float)rectangle31.Height * proj.scale;
                                                vector140 += proj.velocity * (float)rectangle31.Height * proj.scale;
                                            }
                                        }
                                        rectangle31 = new Microsoft.Xna.Framework.Rectangle(0, 56, value34.Width, 22);
                                        Main.EntitySpriteDraw(value34, vector140 - Main.screenPosition, new Microsoft.Xna.Framework.Rectangle?(rectangle31), color100, proj.rotation, value34.Frame(1, 1, 0, 0, 0, 0).Top(), proj.scale, SpriteEffects.None, 0f);
                                        return;
                                    }
                                    else if (proj.type == 632)
{
                                        if (proj.velocity == Vector2.Zero)
{
                                            return;
                                        }
                                        Texture2D value35 = TextureAssets.Projectile[proj.type].Value;
                                        float num376 = proj.localAI[1];
                                        float num377 = 0.5f;
                                        float num378 = 0f;
                                        Microsoft.Xna.Framework.Color color101 = Main.hslToRgb(proj.GetLastPrismHue(proj.ai[0], ref num377, ref num378), 1f, num377, byte.MaxValue);
                                        color101.A = (byte)((float)color101.A * num378);
                                        Vector2 vector141 = proj.Center.Floor();
                                        vector141 += proj.velocity * proj.scale * 10.5f;
                                        num376 -= proj.scale * 14.5f * proj.scale;
                                        Vector2 vector142 = new Vector2(proj.scale);
                                        DelegateMethods.f_1 = 1f;
                                        DelegateMethods.c_1 = color101 * 0.75f * proj.Opacity;
                                        proj.oldPos[0] + new Vector2((float)proj.width, (float)proj.height) / 2f + Vector2.UnitY * proj.gfxOffY - Main.screenPosition;
                                        Utils.DrawLaser(Main.spriteBatch, value35, vector141 - Main.screenPosition, vector141 + proj.velocity * num376 - Main.screenPosition, vector142, new Utils.LaserLineFraming(DelegateMethods.RainbowLaserDraw));
                                        DelegateMethods.c_1 = new Microsoft.Xna.Framework.Color(255, 255, 255, 127) * 0.75f * proj.Opacity;
                                        Utils.DrawLaser(Main.spriteBatch, value35, vector141 - Main.screenPosition, vector141 + proj.velocity * num376 - Main.screenPosition, vector142 / 2f, new Utils.LaserLineFraming(DelegateMethods.RainbowLaserDraw));
                                        return;
                                    }
                                    else if (proj.type == 642)
{
                                        if (proj.velocity == Vector2.Zero)
{
                                            return;
                                        }
                                        Texture2D value36 = TextureAssets.Projectile[proj.type].Value;
                                        float num379 = proj.localAI[1];
                                        Microsoft.Xna.Framework.Color color102 = new Microsoft.Xna.Framework.Color(255, 255, 255, 127);
                                        Vector2 vector143 = proj.Center.Floor();
                                        num379 -= proj.scale * 10.5f;
                                        Vector2 vector144 = new Vector2(proj.scale);
                                        DelegateMethods.f_1 = 1f;
                                        DelegateMethods.c_1 = color102;
                                        DelegateMethods.i_1 = 54000 - (int)Main.time / 2;
                                        proj.oldPos[0] + new Vector2((float)proj.width, (float)proj.height) / 2f + Vector2.UnitY * proj.gfxOffY - Main.screenPosition;
                                        Utils.DrawLaser(Main.spriteBatch, value36, vector143 - Main.screenPosition, vector143 + proj.velocity * num379 - Main.screenPosition, vector144, new Utils.LaserLineFraming(DelegateMethods.TurretLaserDraw));
                                        DelegateMethods.c_1 = new Microsoft.Xna.Framework.Color(255, 255, 255, 127) * 0.75f * proj.Opacity;
                                        Utils.DrawLaser(Main.spriteBatch, value36, vector143 - Main.screenPosition, vector143 + proj.velocity * num379 - Main.screenPosition, vector144 / 2f, new Utils.LaserLineFraming(DelegateMethods.TurretLaserDraw));
                                        return;
                                    }
                                    else if (proj.type == 611)
{
                                        Texture2D value37 = TextureAssets.Projectile[proj.type].Value;
                                        Microsoft.Xna.Framework.Color alpha6 = proj.GetAlpha(color36);
                                        if (proj.velocity == Vector2.Zero)
{
                                            return;
                                        }
                                        float num380 = proj.velocity.Length() + 16f;
                                        bool flag34 = num380 < 100f;
                                        Vector2 vector145 = Vector2.Normalize(proj.velocity);
                                        Microsoft.Xna.Framework.Rectangle rectangle32 = new Microsoft.Xna.Framework.Rectangle(0, 2, value37.Width, 40);
                                        float num381 = proj.rotation + 3.1415927f;
                                        Main.EntitySpriteDraw(value37, proj.Center.Floor() - Main.screenPosition, new Microsoft.Xna.Framework.Rectangle?(rectangle32), alpha6, num381, rectangle32.Size() / 2f - Vector2.UnitY * 4f, proj.scale, SpriteEffects.None, 0f);
                                        num380 -= 40f * proj.scale;
                                        Vector2 vector146 = proj.Center.Floor();
                                        vector146 += vector145 * proj.scale * 24f;
                                        rectangle32 = new Microsoft.Xna.Framework.Rectangle(0, 68, value37.Width, 18);
                                        if (num380 > 0f)
{
                                            float num382 = 0f;
                                            while (num382 + 1f < num380)
{
                                                if (num380 - num382 < (float)rectangle32.Height)
{
                                                    rectangle32.Height = (int)(num380 - num382);
                                                }
                                                Main.EntitySpriteDraw(value37, vector146 - Main.screenPosition, new Microsoft.Xna.Framework.Rectangle?(rectangle32), alpha6, num381, new Vector2((float)(rectangle32.Width / 2), 0f), proj.scale, SpriteEffects.None, 0f);
                                                num382 += (float)rectangle32.Height * proj.scale;
                                                vector146 += vector145 * (float)rectangle32.Height * proj.scale;
                                            }
                                        }
                                        Vector2 vector147 = vector146;
                                        vector146 = proj.Center.Floor();
                                        vector146 += vector145 * proj.scale * 24f;
                                        rectangle32 = new Microsoft.Xna.Framework.Rectangle(0, 46, value37.Width, 18);
                                        int num383 = 18;
                                        if (flag34)
{
                                            num383 = 9;
                                        }
                                        float num384 = num380;
                                        if (num380 > 0f)
{
                                            float num385 = 0f;
                                            float num386 = num384 / (float)num383;
                                            num385 += num386 * 0.25f;
                                            vector146 += vector145 * num386 * 0.25f;
                                            for (int num387 = 0; num387 < num383; num387++)
{
                                                float num388 = num386;
                                                if (num387 == 0)
{
                                                    num388 *= 0.75f;
                                                }
                                                Main.EntitySpriteDraw(value37, vector146 - Main.screenPosition, new Microsoft.Xna.Framework.Rectangle?(rectangle32), alpha6, num381, new Vector2((float)(rectangle32.Width / 2), 0f), proj.scale, SpriteEffects.None, 0f);
                                                num385 += num388;
                                                vector146 += vector145 * num388;
                                            }
                                        }
                                        rectangle32 = new Microsoft.Xna.Framework.Rectangle(0, 90, value37.Width, 48);
                                        Main.EntitySpriteDraw(value37, vector147 - Main.screenPosition, new Microsoft.Xna.Framework.Rectangle?(rectangle32), alpha6, num381, value37.Frame(1, 1, 0, 0, 0, 0).Top(), proj.scale, SpriteEffects.None, 0f);
                                        return;
                                    }
                                    else if (proj.type == 537)
{
                                        if (proj.velocity == Vector2.Zero)
{
                                            return;
                                        }
                                        Texture2D value38 = TextureAssets.Projectile[proj.type].Value;
                                        float num389 = proj.localAI[1];
                                        float num390 = Utils.Remap(proj.localAI[0], 20f, 30f, 0f, 1f, true) * Utils.Remap(proj.localAI[0], 60f, 90f, 1f, 0f, true);
                                        float num391 = 1.5f;
                                        float num392 = Utils.Remap(num390, 0f, 1f, 0.25f, num391, true);
                                        Microsoft.Xna.Framework.Color color103 = new Microsoft.Xna.Framework.Color(255, 255, 255, 0) * 0.9f;
                                        Microsoft.Xna.Framework.Rectangle rectangle33 = new Microsoft.Xna.Framework.Rectangle(0, 0, value38.Width, 22);
                                        Vector2 vector148 = new Vector2(0f, Main.npc[(int)proj.ai[1]].gfxOffY);
                                        Main.EntitySpriteDraw(value38, proj.Center.Floor() - Main.screenPosition + vector148, new Microsoft.Xna.Framework.Rectangle?(rectangle33), color103, proj.rotation, rectangle33.Size() / 2f, num392, SpriteEffects.None, 0f);
                                        num389 -= 33f * proj.scale;
                                        Vector2 vector149 = proj.Center.Floor();
                                        vector149 += proj.velocity * num392 * 10.5f;
                                        rectangle33 = new Microsoft.Xna.Framework.Rectangle(0, 25, value38.Width, 28);
                                        if (num389 > 0f)
{
                                            float num393 = 0f;
                                            while (num393 + 1f < num389)
{
                                                if (num389 - num393 < (float)rectangle33.Height)
{
                                                    rectangle33.Height = (int)(num389 - num393);
                                                }
                                                Main.EntitySpriteDraw(value38, vector149 - Main.screenPosition + vector148, new Microsoft.Xna.Framework.Rectangle?(rectangle33), color103, proj.rotation, new Vector2((float)(rectangle33.Width / 2), 0f), num392, SpriteEffects.None, 0f);
                                                num393 += (float)rectangle33.Height * num392;
                                                vector149 += proj.velocity * (float)rectangle33.Height * num392;
                                            }
                                        }
                                        rectangle33 = new Microsoft.Xna.Framework.Rectangle(0, 56, value38.Width, 22);
                                        Main.EntitySpriteDraw(value38, vector149 - Main.screenPosition + vector148, new Microsoft.Xna.Framework.Rectangle?(rectangle33), color103, proj.rotation, value38.Frame(1, 1, 0, 0, 0, 0).Top(), num392, SpriteEffects.None, 0f);
                                        return;
                                    }
                                    else
{
                                        if (proj.type == 456)
{
                                            Texture2D value39 = TextureAssets.Projectile[proj.type].Value;
                                            Texture2D value40 = TextureAssets.Extra[23].Value;
                                            Texture2D value41 = TextureAssets.Extra[24].Value;
                                            Vector2 vector150 = new Vector2(0f, 216f);
                                            Vector2 vector151 = Main.npc[(int)Math.Abs(proj.ai[0]) - 1].Center - proj.Center + vector150;
                                            float num394 = vector151.Length();
                                            Vector2 vector152 = Vector2.Normalize(vector151);
                                            Microsoft.Xna.Framework.Rectangle rectangle34 = value39.Frame(1, 1, 0, 0, 0, 0);
                                            rectangle34.Height /= 4;
                                            rectangle34.Y += proj.frame * rectangle34.Height;
                                            color36 = Microsoft.Xna.Framework.Color.Lerp(color36, Microsoft.Xna.Framework.Color.White, 0.3f);
                                            Main.EntitySpriteDraw(value39, proj.Center - Main.screenPosition, new Microsoft.Xna.Framework.Rectangle?(rectangle34), proj.GetAlpha(color36), proj.rotation, rectangle34.Size() / 2f, proj.scale, SpriteEffects.None, 0f);
                                            num394 -= (float)(rectangle34.Height / 2 + value41.Height) * proj.scale;
                                            Vector2 vector153 = proj.Center;
                                            vector153 += vector152 * proj.scale * (float)rectangle34.Height / 2f;
                                            if (num394 > 0f)
{
                                                float num395 = 0f;
                                                Microsoft.Xna.Framework.Rectangle rectangle35 = new Microsoft.Xna.Framework.Rectangle(0, 0, value40.Width, value40.Height);
                                                while (num395 + 1f < num394)
{
                                                    if (num394 - num395 < (float)rectangle35.Height)
{
                                                        rectangle35.Height = (int)(num394 - num395);
                                                    }
                                                    Microsoft.Xna.Framework.Point point4 = vector153.ToTileCoordinates();
                                                    Microsoft.Xna.Framework.Color color104 = Lighting.GetColor(point4.X, point4.Y);
                                                    color104 = Microsoft.Xna.Framework.Color.Lerp(color104, Microsoft.Xna.Framework.Color.White, 0.3f);
                                                    Main.EntitySpriteDraw(value40, vector153 - Main.screenPosition, new Microsoft.Xna.Framework.Rectangle?(rectangle35), proj.GetAlpha(color104), proj.rotation, rectangle35.Bottom(), proj.scale, SpriteEffects.None, 0f);
                                                    num395 += (float)rectangle35.Height * proj.scale;
                                                    vector153 += vector152 * (float)rectangle35.Height * proj.scale;
                                                }
                                            }
                                            Microsoft.Xna.Framework.Point point5 = vector153.ToTileCoordinates();
                                            Microsoft.Xna.Framework.Color color105 = Lighting.GetColor(point5.X, point5.Y);
                                            color105 = Microsoft.Xna.Framework.Color.Lerp(color105, Microsoft.Xna.Framework.Color.White, 0.3f);
                                            Microsoft.Xna.Framework.Rectangle rectangle36 = value41.Frame(1, 1, 0, 0, 0, 0);
                                            if (num394 < 0f)
{
                                                rectangle36.Height += (int)num394;
                                            }
                                            Main.EntitySpriteDraw(value41, vector153 - Main.screenPosition, new Microsoft.Xna.Framework.Rectangle?(rectangle36), color105, proj.rotation, new Vector2((float)rectangle36.Width / 2f, (float)rectangle36.Height), proj.scale, SpriteEffects.None, 0f);
                                            return;
                                        }
                                        if (proj.type == 443 || proj.type == 1110)
{
                                            Texture2D value42 = TextureAssets.Projectile[proj.type].Value;
                                            float num396 = 30f;
                                            float num397 = num396 * 4f;
                                            float num398 = 6.2831855f * proj.ai[0] / num396;
                                            float num399 = 6.2831855f * proj.ai[0] / num397;
                                            Vector2 unitY2 = Vector2.UnitY;
                                            double num400 = (double)num398;
                                            Vector2 vector49 = default(Vector2);
                                            Vector2 vector154 = -unitY2.RotatedBy(num400, vector49);
                                            float num401 = 0.75f + vector154.Y * 0.25f;
                                            float num402 = 0.8f - vector154.Y * 0.2f;
                                            int num403 = TextureAssets.Projectile[proj.type].Height() / Main.projFrames[proj.type];
                                            int num404 = num403 * proj.frame;
                                            Vector2 vector155 = proj.position + new Vector2((float)proj.width, (float)proj.height) / 2f + Vector2.UnitY * proj.gfxOffY - Main.screenPosition;
                                            Main.EntitySpriteDraw(value42, vector155, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, num404, value42.Width, num403)), proj.GetAlpha(color36), proj.rotation + num399, new Vector2((float)value42.Width / 2f, (float)num403 / 2f), num401, spriteEffects2, 0f);
                                            Main.EntitySpriteDraw(value42, vector155, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, num404, value42.Width, num403)), proj.GetAlpha(color36), proj.rotation + (6.2831855f - num399), new Vector2((float)value42.Width / 2f, (float)num403 / 2f), num402, spriteEffects2, 0f);
                                            return;
                                        }
                                        if (proj.type == 656 || proj.type == 657)
{
                                            float num405 = 900f;
                                            if (proj.type == 657)
{
                                                num405 = 300f;
                                            }
                                            float num406 = 15f;
                                            float num407 = 15f;
                                            float num408 = proj.ai[0];
                                            float num409 = MathHelper.Clamp(num408 / 30f, 0f, 1f);
                                            if (num408 > num405 - 60f)
{
                                                num409 = MathHelper.Lerp(1f, 0f, (num408 - (num405 - 60f)) / 60f);
                                            }
                                            Microsoft.Xna.Framework.Point point6 = proj.Center.ToTileCoordinates();
                                            int num410;
                                            int num411;
                                            Collision.ExpandVertically(point6.X, point6.Y, out num410, out num411, (int)num406, (int)num407);
                                            num410++;
                                            num411--;
                                            float num412 = 0.2f;
                                            Vector2 vector156 = new Vector2((float)point6.X, (float)num410) * 16f + new Vector2(8f);
                                            Vector2 vector157 = new Vector2((float)point6.X, (float)num411) * 16f + new Vector2(8f);
                                            Vector2.Lerp(vector156, vector157, 0.5f);
                                            Vector2 vector158 = new Vector2(0f, vector157.Y - vector156.Y);
                                            vector158.X = vector158.Y * num412;
                                            new Vector2(vector156.X - vector158.X / 2f, vector156.Y);
                                            Texture2D value43 = TextureAssets.Projectile[proj.type].Value;
                                            Microsoft.Xna.Framework.Rectangle rectangle37 = value43.Frame(1, 1, 0, 0, 0, 0);
                                            Vector2 vector159 = rectangle37.Size() / 2f;
                                            float num413 = -0.06283186f * num408;
                                            Vector2 unitY3 = Vector2.UnitY;
                                            double num414 = (double)(num408 * 0.1f);
                                            Vector2 vector49 = default(Vector2);
                                            Vector2 vector160 = unitY3.RotatedBy(num414, vector49);
                                            float num415 = 0f;
                                            float num416 = 5.1f;
                                            Microsoft.Xna.Framework.Color color106 = new Microsoft.Xna.Framework.Color(212, 192, 100);
                                            for (float num417 = (float)((int)vector157.Y); num417 > (float)((int)vector156.Y); num417 -= num416)
{
                                                num415 += num416;
                                                float num418 = num415 / vector158.Y;
                                                float num419 = num415 * 6.2831855f / -20f;
                                                float num420 = num418 - 0.15f;
                                                Vector2 vector161 = vector160;
                                                double num421 = (double)num419;
                                                vector49 = default(Vector2);
                                                Vector2 vector162 = vector161.RotatedBy(num421, vector49);
                                                Vector2 vector163 = new Vector2(0f, num418 + 1f);
                                                vector163.X = vector163.Y * num412;
                                                Microsoft.Xna.Framework.Color color107 = Microsoft.Xna.Framework.Color.Lerp(Microsoft.Xna.Framework.Color.Transparent, color106, num418 * 2f);
                                                if (num418 > 0.5f)
{
                                                    color107 = Microsoft.Xna.Framework.Color.Lerp(Microsoft.Xna.Framework.Color.Transparent, color106, 2f - num418 * 2f);
                                                }
                                                color107.A = (byte)((float)color107.A * 0.5f);
                                                color107 *= num409;
                                                vector162 *= vector163 * 100f;
                                                vector162.Y = 0f;
                                                vector162.X = 0f;
                                                vector162 += new Vector2(vector157.X, num417) - Main.screenPosition;
                                                Main.EntitySpriteDraw(value43, vector162, new Microsoft.Xna.Framework.Rectangle?(rectangle37), color107, num413 + num419, vector159, 1f + num420, SpriteEffects.None, 0f);
                                            }
                                            return;
                                        }
                                        if (proj.type == 704)
{
                                            float num422 = 300f;
                                            float num423 = proj.ai[0];
                                            float num424 = MathHelper.Clamp(num423 / 30f, 0f, 1f);
                                            if (num423 > num422 - 60f)
{
                                                num424 = MathHelper.Lerp(1f, 0f, (num423 - (num422 - 60f)) / 60f);
                                            }
                                            float num425 = 0.2f;
                                            Vector2 top2 = proj.Top;
                                            Vector2 bottom = proj.Bottom;
                                            Vector2.Lerp(top2, bottom, 0.5f);
                                            Vector2 vector164 = new Vector2(0f, bottom.Y - top2.Y);
                                            vector164.X = vector164.Y * num425;
                                            new Vector2(top2.X - vector164.X / 2f, top2.Y);
                                            Texture2D value44 = TextureAssets.Projectile[proj.type].Value;
                                            Microsoft.Xna.Framework.Rectangle rectangle38 = value44.Frame(1, 1, 0, 0, 0, 0);
                                            Vector2 vector165 = rectangle38.Size() / 2f;
                                            float num426 = -0.15707964f * num423 * (float)((proj.velocity.X > 0f) ? (-1) : 1);
                                            SpriteEffects spriteEffects6 = ((proj.velocity.X > 0f) ? SpriteEffects.FlipVertically : SpriteEffects.None);
                                            bool flag35 = proj.velocity.X > 0f;
                                            Vector2 unitY4 = Vector2.UnitY;
                                            double num427 = (double)(num423 * 0.14f);
                                            Vector2 vector49 = default(Vector2);
                                            Vector2 vector166 = unitY4.RotatedBy(num427, vector49);
                                            float num428 = 0f;
                                            float num429 = 5.01f + num423 / 150f * -0.9f;
                                            if (num429 < 4.11f)
{
                                                num429 = 4.11f;
                                            }
                                            Microsoft.Xna.Framework.Color color108 = new Microsoft.Xna.Framework.Color(160, 140, 100, 127);
                                            Microsoft.Xna.Framework.Color color109 = new Microsoft.Xna.Framework.Color(140, 160, 255, 127);
                                            float num430 = num423 % 60f;
                                            if (num430 < 30f)
{
                                                color109 *= Utils.GetLerpValue(22f, 30f, num430, true);
                                            }
                                            else
{
                                                color109 *= Utils.GetLerpValue(38f, 30f, num430, true);
                                            }
                                            bool flag36 = color109 != Microsoft.Xna.Framework.Color.Transparent;
                                            for (float num431 = (float)((int)bottom.Y); num431 > (float)((int)top2.Y); num431 -= num429)
{
                                                num428 += num429;
                                                float num432 = num428 / vector164.Y;
                                                float num433 = num428 * 6.2831855f / -20f;
                                                if (flag35)
{
                                                    num433 *= -1f;
                                                }
                                                float num434 = num432 - 0.35f;
                                                Vector2 vector167 = vector166;
                                                double num435 = (double)num433;
                                                vector49 = default(Vector2);
                                                Vector2 vector168 = vector167.RotatedBy(num435, vector49);
                                                Vector2 vector169 = new Vector2(0f, num432 + 1f);
                                                vector169.X = vector169.Y * num425;
                                                Microsoft.Xna.Framework.Color color110 = Microsoft.Xna.Framework.Color.Lerp(Microsoft.Xna.Framework.Color.Transparent, color108, num432 * 2f);
                                                if (num432 > 0.5f)
{
                                                    color110 = Microsoft.Xna.Framework.Color.Lerp(Microsoft.Xna.Framework.Color.Transparent, color108, 2f - num432 * 2f);
                                                }
                                                color110.A = (byte)((float)color110.A * 0.5f);
                                                color110 *= num424;
                                                vector168 *= vector169 * 100f;
                                                vector168.Y = 0f;
                                                vector168.X = 0f;
                                                vector168 += new Vector2(bottom.X, num431) - Main.screenPosition;
                                                if (flag36)
{
                                                    Microsoft.Xna.Framework.Color color111 = Microsoft.Xna.Framework.Color.Lerp(Microsoft.Xna.Framework.Color.Transparent, color109, num432 * 2f);
                                                    if (num432 > 0.5f)
{
                                                        color111 = Microsoft.Xna.Framework.Color.Lerp(Microsoft.Xna.Framework.Color.Transparent, color109, 2f - num432 * 2f);
                                                    }
                                                    color111.A = (byte)((float)color111.A * 0.5f);
                                                    color111 *= num424;
                                                    Main.EntitySpriteDraw(value44, vector168, new Microsoft.Xna.Framework.Rectangle?(rectangle38), color111, num426 + num433, vector165, (1f + num434) * 0.8f, spriteEffects6, 0f);
                                                }
                                                Main.EntitySpriteDraw(value44, vector168, new Microsoft.Xna.Framework.Rectangle?(rectangle38), color110, num426 + num433, vector165, 1f + num434, spriteEffects6, 0f);
                                            }
                                            return;
                                        }
                                        if (proj.type == 444 || proj.type == 446 || proj.type == 490 || proj.type == 464 || proj.type == 502 || proj.type == 538 || proj.type == 540 || proj.type == 579 || proj.type == 578 || proj.type == 813 || proj.type == 583 || proj.type == 584 || proj.type == 616 || proj.type == 617 || proj.type == 618 || proj.type == 641 || (proj.type >= 646 && proj.type <= 649) || proj.type == 653 || proj.type == 186 || proj.type == 662 || proj.type == 685 || proj.type == 673 || proj.type == 676 || proj.type == 697 || proj.type == 699 || proj.type == 707 || proj.type == 708 || proj.type == 719 || proj.type == 761 || proj.type == 762 || proj.type == 763 || proj.type == 772 || proj.type == 802 || proj.type == 842 || proj.type == 865 || proj.type == 921 || proj.type == 926 || proj.type == 757 || proj.type == 25 || proj.type == 35 || proj.type == 63 || proj.type == 154 || proj.type == 247 || proj.type == 26 || proj.type == 928 || proj.type == 16 || proj.type == 34 || proj.type == 79 || proj.type == 936 || proj.type == 937 || proj.type == 938 || proj.type == 939 || proj.type == 940 || proj.type == 941 || proj.type == 942 || proj.type == 943 || proj.type == 944 || proj.type == 945 || proj.type == 971 || proj.type == 975 || proj.type == 1000 || proj.type == 1012 || proj.type == 1018 || proj.type == 1056 || proj.type == 1020 || proj.type == 1023 || proj.type == 1047 || proj.type == 1048 || proj.type == 1053 || proj.type == 1054 || proj.type == 1089 || proj.type == 1090 || proj.type == 1099 || (((proj.type >= 776 && proj.type <= 801) || (proj.type >= 803 && proj.type <= 810)) && proj.type != 779 && proj.type != 783 && proj.type != 862 && proj.type != 863))
{
                                            Vector2 vector170 = proj.position + new Vector2((float)proj.width, (float)proj.height) / 2f + Vector2.UnitY * proj.gfxOffY - Main.screenPosition;
                                            Texture2D texture2D20 = TextureAssets.Projectile[proj.type].Value;
                                            Microsoft.Xna.Framework.Color alpha7 = proj.GetAlpha(color36);
                                            Vector2 vector171 = new Vector2((float)texture2D20.Width, (float)texture2D20.Height) / 2f;
                                            float num436 = proj.rotation;
                                            Vector2 vector172 = Vector2.One * proj.scale;
                                            Microsoft.Xna.Framework.Rectangle? rectangle39 = null;
                                            if (proj.type == 1056)
{
                                                vector170.Y += 2f;
                                            }
                                            if (proj.type == 446)
{
                                                vector171.Y = 4f;
                                            }
                                            if (proj.type == 1020)
{
                                                vector171.Y = 14f;
                                            }
                                            if (proj.type == 865)
{
                                                vector170 += new Vector2(1f, -1f);
                                                spriteEffects2 = ((proj.DirectionFrom(player.Center).SafeNormalize(Vector2.Zero).X > 0f) ? SpriteEffects.FlipHorizontally : SpriteEffects.None);
                                            }
                                            if (proj.type == 16)
{
                                                float lerpValue8 = Utils.GetLerpValue(0f, 8f, proj.velocity.Length(), true);
                                                num436 *= lerpValue8;
                                                vector172 *= 0.6f;
                                                vector172.Y *= MathHelper.Lerp(1f, 0.8f, lerpValue8);
                                                vector172.X *= MathHelper.Lerp(1f, 1.5f, lerpValue8);
                                            }
                                            if (proj.type == 1047)
{
                                                Main._rainbowBoulderMusicFramesCounter = 6;
                                                vector172 *= 2f;
                                                rectangle39 = new Microsoft.Xna.Framework.Rectangle?(texture2D20.Frame(5, 20, proj.frame / 20, proj.frame % 20, 0, 0));
                                                vector171 = rectangle39.Value.Size() / 2f;
                                            }
                                            if (proj.type == 1090 && proj.ai[0] == 1f)
{
                                                this.LoadProjectile(1047);
                                                texture2D20 = TextureAssets.Projectile[1047].Value;
                                                vector172 *= 2f;
                                                rectangle39 = new Microsoft.Xna.Framework.Rectangle?(texture2D20.Frame(5, 20, proj.frame / 20, proj.frame % 20, 0, 0));
                                                vector171 = rectangle39.Value.Size() / 2f;
                                            }
                                            if (proj.type == 34)
{
                                                float lerpValue9 = Utils.GetLerpValue(0f, 8f, proj.velocity.Length(), true);
                                                num436 *= lerpValue9;
                                                vector172.X *= MathHelper.Lerp(1f, 0.8f, lerpValue9);
                                                num436 += -1.5707964f * lerpValue9;
                                                rectangle39 = new Microsoft.Xna.Framework.Rectangle?(texture2D20.Frame(1, Main.projFrames[proj.type], 0, proj.frame, 0, 0));
                                                vector171 = rectangle39.Value.Size() / 2f;
                                                vector170 -= proj.velocity * 1f;
                                                vector170 = proj.oldPos[0] + proj.Size / 2f - Main.screenPosition - proj.velocity / 2f;
                                            }
                                            if (proj.type == 79)
{
                                                num436 = 0f;
                                                vector172 *= Utils.GetLerpValue(32f, 0f, proj.position.Distance(proj.oldPos[12]), true);
                                                alpha7 = new Microsoft.Xna.Framework.Color(255, 255, 255, 0);
                                            }
                                            if (proj.type == 761 || proj.type == 762)
{
                                                spriteEffects2 = ((proj.spriteDirection > 0) ? SpriteEffects.None : SpriteEffects.FlipVertically);
                                            }
                                            if (proj.type == 662 || proj.type == 685)
{
                                                vector171 = new Vector2(6f, 6f);
                                            }
                                            if (proj.type == 699 || proj.type == 708)
{
                                                Player player5 = player;
                                                vector171 = new Vector2((proj.spriteDirection == 1) ? ((float)texture2D20.Width - -8f) : (-8f), (player5.gravDir == 1f) ? (-8f) : ((float)texture2D20.Height - -8f));
                                                if (player5.gravDir == -1f)
{
                                                    spriteEffects2 |= SpriteEffects.FlipVertically;
                                                    num436 += 1.5707964f * (float)(-(float)proj.spriteDirection);
                                                }
                                            }
                                            if (proj.type == 938 || proj.type == 939 || proj.type == 940 || proj.type == 941 || proj.type == 942 || proj.type == 943 || proj.type == 944 || proj.type == 945)
{
                                                num436 -= 0.7853982f * (float)proj.spriteDirection;
                                            }
                                            if (proj.type == 1089)
{
                                                this.LoadProjectile(250);
                                                Texture2D value45 = TextureAssets.MagicPixel.Value;
                                                float num437 = 2f;
                                                Vector2 vector173 = new Vector2((float)(value45.Width / 2), 0f);
                                                Vector2 vector174 = new Vector2((float)proj.width, (float)proj.height) / 2f;
                                                Microsoft.Xna.Framework.Color color112 = new Microsoft.Xna.Framework.Color(Main.DiscoR, Main.DiscoG, Main.DiscoB, 127);
                                                float num438 = 1f;
                                                float num439 = 1f;
                                                float num440 = 0f;
                                                float num441 = 13f;
                                                float num442 = 1f / num441;
                                                int num443 = -1;
                                                for (int num444 = proj.oldPos.Length - 1; num444 > 0; num444--)
{
                                                    Vector2 vector175 = proj.oldPos[num444] + vector174;
                                                    if (!(vector175 == vector174))
{
                                                        if (num443 == -1)
{
                                                            num443 = num444;
                                                        }
                                                        Vector2 vector176 = proj.oldPos[num444 - 1] + vector174;
                                                        float num445 = (vector176 - vector175).ToRotation() - 1.5707964f;
                                                        Vector2 vector177 = new Vector2(2.2f * num437, Vector2.Distance(vector175, vector176) / (float)value45.Height);
                                                        Microsoft.Xna.Framework.Color color113 = color112 * num440 * num438 * num439;
                                                        if (num444 <= 10)
{
                                                            num438 -= 0.1f;
                                                            if (num438 <= 0f)
{
                                                                num438 = 0f;
                                                            }
                                                        }
                                                        if ((float)num444 >= (float)num443 - num441)
{
                                                            num440 += num442;
                                                            if (num440 >= 1f)
{
                                                                num440 = 1f;
                                                            }
                                                        }
                                                        Main.EntitySpriteDraw(value45, vector175 - Main.screenPosition, null, color113, num445, vector173, vector177, spriteEffects2, 0f);
                                                    }
                                                }
                                            }
                                            if (proj.type == 502)
{
                                                this.LoadProjectile(250);
                                                Texture2D value46 = TextureAssets.Projectile[250].Value;
                                                Vector2 vector178 = new Vector2((float)(value46.Width / 2), 0f);
                                                Vector2 vector179 = new Vector2((float)proj.width, (float)proj.height) / 2f;
                                                Microsoft.Xna.Framework.Color white2 = Microsoft.Xna.Framework.Color.White;
                                                white2.A = 127;
                                                for (int num446 = proj.oldPos.Length - 1; num446 > 0; num446--)
{
                                                    Vector2 vector180 = proj.oldPos[num446] + vector179;
                                                    if (!(vector180 == vector179))
{
                                                        Vector2 vector181 = proj.oldPos[num446 - 1] + vector179;
                                                        float num447 = (vector181 - vector180).ToRotation() - 1.5707964f;
                                                        Vector2 vector182 = new Vector2(1f, Vector2.Distance(vector180, vector181) / (float)value46.Height);
                                                        Microsoft.Xna.Framework.Color color114 = white2 * (1f - (float)num446 / (float)proj.oldPos.Length);
                                                        Main.EntitySpriteDraw(value46, vector180 - Main.screenPosition, null, color114, num447, vector178, vector182, spriteEffects2, 0f);
                                                    }
                                                }
                                            }
                                            if (proj.type == 1047 || proj.type == 1090)
{
                                                float num448 = 0.5f;
                                                float num449 = 1f;
                                                if (proj.type == 1090)
{
                                                    bool flag37 = proj.ai[0] == 1f;
                                                    num449 = MathHelper.Clamp(proj.localAI[2], 0f, 1f);
                                                    if (num449 > 0f && flag37)
{
                                                        num449 *= Utils.GetLerpValue(3f, 5f, proj.velocity.Length(), true);
                                                    }
                                                    if (!flag37)
{
                                                        Texture2D value47 = TextureAssets.Extra[283].Value;
                                                        for (float num450 = 0f; num450 < 1f; num450 += 0.33333334f)
{
                                                            float num451 = Main.GlobalTimeWrappedHourly % 2f / 2f;
                                                            Microsoft.Xna.Framework.Color color115 = Main.hslToRgb((num451 + num450) % 1f, 1f, 0.5f, byte.MaxValue);
                                                            color115.A = 0;
                                                            color115 *= 0.3f;
                                                            Vector2 vector183 = vector170 + (((num451 + num450) * 6.2831855f).ToRotationVector2() * 4f).Floor();
                                                            Main.EntitySpriteDraw(value47, vector183, null, color115, num436, vector171, vector172, spriteEffects2, 0f);
                                                        }
                                                    }
                                                }
                                                Vector2 vector184 = new Vector2((float)proj.width, (float)proj.height) / 2f;
                                                if (num449 > 0f)
{
                                                    this.LoadProjectile(250);
                                                    Texture2D value48 = TextureAssets.Projectile[250].Value;
                                                    Vector2 vector185 = new Vector2((float)(value48.Width / 2), 0f);
                                                    Microsoft.Xna.Framework.Color color116 = Microsoft.Xna.Framework.Color.White;
                                                    color116.A = 127;
                                                    color116 *= num449;
                                                    for (int num452 = proj.oldPos.Length - 1; num452 > 0; num452--)
{
                                                        Vector2 vector186 = proj.oldPos[num452] + vector184;
                                                        if (!(vector186 == vector184))
{
                                                            Vector2 vector187 = proj.oldPos[num452 - 1] + vector184;
                                                            float num453 = (vector187 - vector186).ToRotation() - 1.5707964f;
                                                            Vector2 vector188 = new Vector2(2.2f * num448, Vector2.Distance(vector186, vector187) / (float)value48.Height);
                                                            float num454 = (float)num452 / (float)proj.oldPos.Length;
                                                            Microsoft.Xna.Framework.Color color117 = color116 * (1f - num454) * (1f - num454);
                                                            Main.EntitySpriteDraw(value48, vector186 - Main.screenPosition, null, color117, num453, vector185, vector188, spriteEffects2, 0f);
                                                        }
                                                    }
                                                    Texture2D value49 = TextureAssets.Extra[55].Value;
                                                    Vector2 vector189 = new Vector2((float)(value49.Width / 2), (float)(value49.Height / 8 + 14));
                                                    int num455 = proj.frame;
                                                    float num456 = -1.5707964f;
                                                    num455 %= 4;
                                                    for (int num457 = 3; num457 >= 0; num457--)
{
                                                        if (proj.oldPos[num457] != Vector2.Zero)
{
                                                            Vector2 vector190 = proj.oldPos[num457] + vector184;
                                                            Microsoft.Xna.Framework.Color color118 = Microsoft.Xna.Framework.Color.White;
                                                            color118.A = 0;
                                                            color118 *= 1f - (float)num457 / 3f;
                                                            color118 *= num449;
                                                            int num458 = (num455 - num457) % 4;
                                                            if (num458 < 0)
{
                                                                num458 += 4;
                                                            }
                                                            Microsoft.Xna.Framework.Rectangle rectangle40 = value49.Frame(1, 4, 0, num458, 0, 0);
                                                            Main.EntitySpriteDraw(value49, vector190 - Main.screenPosition, new Microsoft.Xna.Framework.Rectangle?(rectangle40), color118, proj.velocity.ToRotation() + num456, vector189, MathHelper.Lerp(0.1f, 0.8f, (10f - (float)num457) / 10f) * num448, SpriteEffects.None, 0f);
                                                        }
                                                    }
                                                }
                                            }
                                            else if (proj.type == 540 && proj.velocity != Vector2.Zero)
{
                                                float num459 = 0f;
                                                if (proj.ai[0] >= 10f)
{
                                                    num459 = (proj.ai[0] - 10f) / 10f;
                                                }
                                                if (proj.ai[0] >= 20f)
{
                                                    num459 = (20f - proj.ai[0]) / 10f;
                                                }
                                                if (num459 > 1f)
{
                                                    num459 = 1f;
                                                }
                                                if (num459 < 0f)
{
                                                    num459 = 0f;
                                                }
                                                if (num459 != 0f)
{
                                                    Texture2D value50 = TextureAssets.Extra[47].Value;
                                                    Vector2 vector191 = new Vector2((float)(value50.Width / 2), 0f);
                                                    Microsoft.Xna.Framework.Color color119 = alpha7 * num459 * 0.7f;
                                                    Vector2 vector192 = proj.Center - Main.screenPosition;
                                                    Vector2 vector193 = proj.velocity.ToRotation().ToRotationVector2() * (float)texture2D20.Width / 3f;
                                                    vector193 = Vector2.Zero;
                                                    vector192 += vector193;
                                                    float num460 = proj.velocity.ToRotation() - 1.5707964f;
                                                    Vector2 vector194 = new Vector2(1f, (proj.velocity.Length() - vector193.Length() * 2f) / (float)value50.Height);
                                                    Main.EntitySpriteDraw(value50, vector192, null, color119, num460, vector191, vector194, SpriteEffects.None, 0f);
                                                }
                                            }
                                            if (proj.type == 578 || proj.type == 579 || proj.type == 641 || proj.type == 813)
{
                                                Microsoft.Xna.Framework.Color color120 = alpha7 * 0.8f;
                                                color120.A /= 2;
                                                Microsoft.Xna.Framework.Color color121 = Microsoft.Xna.Framework.Color.Lerp(alpha7, Microsoft.Xna.Framework.Color.Black, 0.5f);
                                                color121.A = alpha7.A;
                                                float num461 = 0.95f + (proj.rotation * 0.75f).ToRotationVector2().Y * 0.1f;
                                                color121 *= num461;
                                                float num462 = 0.6f + proj.scale * 0.6f * num461;
                                                Texture2D texture2D21 = TextureAssets.Extra[50].Value;
                                                bool flag38 = true;
                                                if (proj.type == 813)
{
                                                    flag38 = false;
                                                    texture2D21 = TextureAssets.Extra[131].Value;
                                                }
                                                Vector2 vector195 = texture2D21.Size() / 2f;
                                                Main.EntitySpriteDraw(texture2D21, vector170, null, color121, -num436 + 0.35f, vector195, num462, spriteEffects2 ^ SpriteEffects.FlipHorizontally, 0f);
                                                Main.EntitySpriteDraw(texture2D21, vector170, null, alpha7, -num436, vector195, proj.scale, spriteEffects2 ^ SpriteEffects.FlipHorizontally, 0f);
                                                if (flag38)
{
                                                    Main.EntitySpriteDraw(texture2D20, vector170, null, color120, -num436 * 0.7f, vector171, proj.scale, spriteEffects2 ^ SpriteEffects.FlipHorizontally, 0f);
                                                }
                                                Main.EntitySpriteDraw(texture2D21, vector170, null, alpha7 * 0.8f, num436 * 0.5f, vector195, proj.scale * 0.9f, spriteEffects2, 0f);
                                                alpha7.A = 0;
                                                if (proj.type == 813)
{
                                                    num436 = 0f;
                                                }
                                            }
                                            if (proj.type == 617)
{
                                                Microsoft.Xna.Framework.Color color122 = alpha7 * 0.8f;
                                                color122.A /= 2;
                                                Microsoft.Xna.Framework.Color color123 = Microsoft.Xna.Framework.Color.Lerp(alpha7, Microsoft.Xna.Framework.Color.Black, 0.5f);
                                                color123.A = alpha7.A;
                                                float num463 = 0.95f + (proj.rotation * 0.75f).ToRotationVector2().Y * 0.1f;
                                                color123 *= num463;
                                                float num464 = 0.6f + proj.scale * 0.6f * num463;
                                                Main.EntitySpriteDraw(TextureAssets.Extra[50].Value, vector170, null, color123, -proj.rotation + 0.35f, vector171, num464, spriteEffects2 ^ SpriteEffects.FlipHorizontally, 0f);
                                                Main.EntitySpriteDraw(TextureAssets.Extra[50].Value, vector170, null, alpha7, -proj.rotation, vector171, proj.scale, spriteEffects2 ^ SpriteEffects.FlipHorizontally, 0f);
                                                Main.EntitySpriteDraw(texture2D20, vector170, null, color122, -proj.rotation * 0.7f, vector171, proj.scale, spriteEffects2 ^ SpriteEffects.FlipHorizontally, 0f);
                                                Main.EntitySpriteDraw(TextureAssets.Extra[50].Value, vector170, null, alpha7 * 0.8f, proj.rotation * 0.5f, vector171, proj.scale * 0.9f, spriteEffects2, 0f);
                                                alpha7.A = 0;
                                            }
                                            if (proj.type == 757 || proj.type == 25 || proj.type == 35 || proj.type == 63 || proj.type == 154 || proj.type == 247 || proj.type == 26)
{
                                                if (proj.ai[0] == 1f)
{
                                                    Microsoft.Xna.Framework.Color color124 = alpha7;
                                                    color124.A = 127;
                                                    color124 *= 0.5f;
                                                    int num465 = (int)proj.ai[1];
                                                    if (num465 > 5)
{
                                                        num465 = 5;
                                                    }
                                                    for (float num466 = 1f; num466 >= 0f; num466 -= 0.125f)
{
                                                        float num467 = 1f - num466;
                                                        Vector2 vector196 = proj.velocity * (float)(-(float)num465) * num466;
                                                        Main.EntitySpriteDraw(texture2D20, vector170 + vector196, null, color124 * num467, num436, vector171, proj.scale * 1.15f * MathHelper.Lerp(0.5f, 1f, num467), spriteEffects2, 0f);
                                                    }
                                                }
                                            }
                                            else if (proj.type == 79)
{
                                                Vector2 vector197 = vector172 * 1.4f;
                                                Vector2 vector198 = new Vector2(2f * vector197.X + (float)Math.Cos((double)(Main.GlobalTimeWrappedHourly * 6.2831855f)) * 0.4f, 0f);
                                                double num468 = (double)(num436 + Main.GlobalTimeWrappedHourly * 6.2831855f);
                                                Vector2 vector49 = default(Vector2);
                                                Vector2 vector199 = vector198.RotatedBy(num468, vector49);
                                                for (float num469 = 0f; num469 < 1f; num469 += 0.16666667f)
{
                                                    Microsoft.Xna.Framework.Color color125 = Main.hslToRgb(num469, 1f, 0.5f, byte.MaxValue) * 0.3f;
                                                    color125.A = 0;
                                                    Texture2D texture2D22 = texture2D20;
                                                    Vector2 vector200 = vector170;
                                                    Vector2 vector201 = vector199;
                                                    double num470 = (double)(num469 * 6.2831855f);
                                                    vector49 = default(Vector2);
                                                    Main.EntitySpriteDraw(texture2D22, vector200 + vector201.RotatedBy(num470, vector49), null, color125, num436, vector171, vector197, spriteEffects2, 0f);
                                                }
                                                Main.EntitySpriteDraw(texture2D20, vector170, null, alpha7, num436, vector171, vector172, spriteEffects2, 0f);
                                            }
                                            if (!(false | (proj.type == 464 && proj.ai[1] != 1f)))
{
                                                Main.EntitySpriteDraw(texture2D20, vector170, rectangle39, alpha7, num436, vector171, vector172, spriteEffects2, 0f);
                                            }
                                            if (proj.type == 464 && proj.ai[1] != 1f)
{
                                                texture2D20 = TextureAssets.Extra[35].Value;
                                                Microsoft.Xna.Framework.Rectangle rectangle41 = texture2D20.Frame(1, 3, 0, 0, 0, 0);
                                                vector171 = rectangle41.Size() / 2f;
                                                Vector2 vector202 = new Vector2(0f, -720f);
                                                double num471 = (double)proj.velocity.ToRotation();
                                                Vector2 vector49 = default(Vector2);
                                                Vector2 vector203 = vector202.RotatedBy(num471, vector49);
                                                float num472 = proj.ai[0] % 45f / 45f;
                                                Vector2 vector204 = vector203 * num472;
                                                for (int num473 = 0; num473 < 6; num473++)
{
                                                    float num474 = (float)num473 * 6.2831855f / 6f;
                                                    Vector2 center = proj.Center;
                                                    Vector2 vector205 = vector204;
                                                    double num475 = (double)num474;
                                                    vector49 = default(Vector2);
                                                    Vector2 vector206 = center + vector205.RotatedBy(num475, vector49);
                                                    Main.EntitySpriteDraw(texture2D20, vector206 - Main.screenPosition, new Microsoft.Xna.Framework.Rectangle?(rectangle41), alpha7, num474 + proj.velocity.ToRotation() + 3.1415927f, vector171, proj.scale, spriteEffects2, 0f);
                                                    rectangle41.Y += rectangle41.Height;
                                                    if (rectangle41.Y >= texture2D20.Height)
{
                                                        rectangle41.Y = 0;
                                                    }
                                                }
                                                return;
                                            }
                                            if (proj.type == 490)
{
                                                Main.EntitySpriteDraw(TextureAssets.Extra[34].Value, vector170, null, alpha7, -proj.rotation, TextureAssets.Extra[34].Value.Size() / 2f, proj.scale, spriteEffects2, 0f);
                                                Main.EntitySpriteDraw(texture2D20, vector170, null, alpha7, proj.rotation, vector171, proj.scale * 0.42f, spriteEffects2, 0f);
                                                Main.EntitySpriteDraw(TextureAssets.Extra[34].Value, vector170, null, alpha7, -proj.rotation, TextureAssets.Extra[34].Value.Size() / 2f, proj.scale * 0.42f, spriteEffects2, 0f);
                                                return;
                                            }
                                            if (proj.type == 1023)
{
                                                Texture2D value51 = TextureAssets.GlowMask[356].Value;
                                                Microsoft.Xna.Framework.Rectangle rectangle42 = value51.Frame(1, 1, 0, 0, 0, 0);
                                                Vector2 vector207 = rectangle42.Center();
                                                Microsoft.Xna.Framework.Color color126 = new Microsoft.Xna.Framework.Color(255, 255, 255, 100) * proj.Opacity;
                                                Main.EntitySpriteDraw(value51, vector170, new Microsoft.Xna.Framework.Rectangle?(rectangle42), color126, num436, vector207, vector172, spriteEffects2, 0f);
                                                return;
                                            }
                                            if (proj.type == 616)
{
                                                texture2D20 = TextureAssets.GlowMask[193].Value;
                                                Main.EntitySpriteDraw(texture2D20, vector170, null, new Microsoft.Xna.Framework.Color(127, 127, 127, 0), proj.rotation, vector171, proj.scale, spriteEffects2, 0f);
                                                return;
                                            }
                                            if (proj.type >= 646 && proj.type <= 649)
{
                                                texture2D20 = TextureAssets.GlowMask[203 + proj.type - 646].Value;
                                                Main.EntitySpriteDraw(texture2D20, vector170, null, new Microsoft.Xna.Framework.Color(255, 255, 255, 127), proj.rotation, vector171, proj.scale, spriteEffects2, 0f);
                                                return;
                                            }
                                            if (proj.type == 699)
{
                                                texture2D20 = TextureAssets.GlowMask[231].Value;
                                                Main.EntitySpriteDraw(texture2D20, vector170, null, new Microsoft.Xna.Framework.Color(255, 255, 255, 127), num436, vector171, proj.scale, spriteEffects2, 0f);
                                                return;
                                            }
                                            if (proj.type == 707 || proj.type == 708)
{
                                                float num476 = 0.5f;
                                                texture2D20 = TextureAssets.GlowMask[232].Value;
                                                Microsoft.Xna.Framework.Rectangle rectangle43 = texture2D20.Frame(1, 3, 0, (int)(proj.ai[0] % 9f) / 3, 0, 0);
                                                if (proj.type == 708)
{
                                                    rectangle43 = texture2D20.Frame(1, 3, 0, player.itemAnimation % 9 / 3, 0, 0);
                                                    num476 = 0.75f;
                                                }
                                                if (proj.isAPreviewDisplayDoll)
{
                                                    rectangle43 = texture2D20.Frame(1, 3, 0, (int)Main.timeForVisualEffects % 12 / 4, 0, 0);
                                                }
                                                Microsoft.Xna.Framework.Color color127 = new Microsoft.Xna.Framework.Color(255, 255, 255, 127) * num476;
                                                Vector2 vector208 = new Vector2(2f, 0f);
                                                double num477 = (double)proj.rotation;
                                                Vector2 vector49 = default(Vector2);
                                                Vector2 vector209 = vector208.RotatedBy(num477, vector49);
                                                for (float num478 = 0f; num478 < 4f; num478 += 1f)
{
                                                    Texture2D texture2D23 = texture2D20;
                                                    Vector2 vector210 = vector170;
                                                    Vector2 vector211 = vector209;
                                                    double num479 = (double)(num478 * 1.5707964f);
                                                    vector49 = default(Vector2);
                                                    Main.EntitySpriteDraw(texture2D23, vector210 + vector211.RotatedBy(num479, vector49), new Microsoft.Xna.Framework.Rectangle?(rectangle43), color127 * 0.5f, proj.rotation, vector171, proj.scale, spriteEffects2, 0f);
                                                }
                                                Main.EntitySpriteDraw(texture2D20, vector170, new Microsoft.Xna.Framework.Rectangle?(rectangle43), color127, proj.rotation, vector171, proj.scale, spriteEffects2, 0f);
                                                return;
                                            }
                                            if (proj.type == 719)
{
                                                float num480 = 0.3f;
                                                Microsoft.Xna.Framework.Color color128 = new Microsoft.Xna.Framework.Color(80, 80, 80, 255) * num480;
                                                float num481 = proj.scale * 1.5f;
                                                Vector2 vector212 = new Vector2(2f * num481, 0f);
                                                double num482 = (double)proj.rotation;
                                                Vector2 vector49 = default(Vector2);
                                                Vector2 vector213 = vector212.RotatedBy(num482, vector49);
                                                for (float num483 = 0f; num483 < 4f; num483 += 1f)
{
                                                    Main.EntitySpriteDraw(texture2D20, vector170 + -proj.velocity * num483 * 1.25f, null, color128 * 0.7f, proj.rotation, vector171, num481, spriteEffects2, 0f);
                                                }
                                                for (float num484 = 0f; num484 < 3f; num484 += 1f)
{
                                                    Texture2D texture2D24 = texture2D20;
                                                    Vector2 vector214 = vector170;
                                                    Vector2 vector215 = vector213;
                                                    double num485 = (double)(num484 * 1.5707964f);
                                                    vector49 = default(Vector2);
                                                    Main.EntitySpriteDraw(texture2D24, vector214 + vector215.RotatedBy(num485, vector49), null, color128 * 0.9f, proj.rotation, vector171, num481, spriteEffects2, 0f);
                                                }
                                                Main.EntitySpriteDraw(texture2D20, vector170, null, alpha7, proj.rotation, vector171, proj.scale, spriteEffects2, 0f);
                                                return;
                                            }
                                            if (proj.type == 16)
{
                                                Microsoft.Xna.Framework.Color color129 = new Microsoft.Xna.Framework.Color(80, 80, 80, 0);
                                                Vector2 vector216 = vector172 + vector172 * (float)Math.Cos((double)(Main.GlobalTimeWrappedHourly * 6.2831855f)) * 0.4f;
                                                Vector2 vector217 = new Vector2(2f * vector216.X, 0f);
                                                double num486 = (double)num436;
                                                Vector2 vector49 = default(Vector2);
                                                Vector2 vector218 = vector217.RotatedBy(num486, vector49);
                                                for (float num487 = 0f; num487 < 1f; num487 += 0.25f)
{
                                                    Texture2D texture2D25 = texture2D20;
                                                    Vector2 vector219 = vector170;
                                                    Vector2 vector220 = vector218;
                                                    double num488 = (double)(num487 * 6.2831855f);
                                                    vector49 = default(Vector2);
                                                    Main.EntitySpriteDraw(texture2D25, vector219 + vector220.RotatedBy(num488, vector49), null, color129, num436, vector171, vector216, spriteEffects2, 0f);
                                                }
                                                Main.EntitySpriteDraw(texture2D20, vector170, null, alpha7, num436, vector171, vector172, spriteEffects2, 0f);
                                                return;
                                            }
                                            if (proj.type == 34)
{
                                                float lerpValue10 = Utils.GetLerpValue(0f, 6f, proj.localAI[0], true);
                                                Microsoft.Xna.Framework.Color color130 = new Microsoft.Xna.Framework.Color(255, 255, 255, 127) * 0.75f;
                                                Vector2 vector221 = new Vector2(lerpValue10);
                                                Vector2 vector222 = new Vector2(4f * vector221.X, 0f);
                                                double num489 = (double)num436;
                                                Vector2 vector49 = default(Vector2);
                                                Vector2 vector223 = vector222.RotatedBy(num489, vector49);
                                                for (float num490 = 0f; num490 < 1f; num490 += 0.25f)
{
                                                    Texture2D texture2D26 = texture2D20;
                                                    Vector2 vector224 = vector170;
                                                    Vector2 vector225 = vector223;
                                                    double num491 = (double)(num490 * 6.2831855f);
                                                    vector49 = default(Vector2);
                                                    Main.EntitySpriteDraw(texture2D26, vector224 + vector225.RotatedBy(num491, vector49), rectangle39, color130, num436, vector171, vector221, spriteEffects2, 0f);
                                                }
                                                return;
                                            }
                                        }
                                        else if (proj.type == 465 || proj.type == 467 || proj.type == 468 || proj.type == 500 || proj.type == 518 || proj.type == 535 || proj.type == 539 || proj.type == 575 || proj.type == 574 || proj.type == 589 || proj.type == 590 || proj.type == 593 || proj.type == 602 || proj.type == 596 || proj.type == 612 || proj.type == 953 || proj.type == 613 || proj.type == 614 || proj.type == 623 || proj.type == 625 || proj.type == 626 || proj.type == 627 || proj.type == 628 || proj.type == 634 || proj.type == 635 || proj.type == 643 || proj.type == 644 || proj.type == 645 || proj.type == 650 || proj.type == 652 || proj.type == 658 || proj.type == 659 || proj.type == 663 || proj.type == 665 || proj.type == 667 || proj.type == 677 || proj.type == 678 || proj.type == 679 || proj.type == 691 || proj.type == 692 || proj.type == 693 || proj.type == 702 || proj.type == 703 || proj.type == 701 || proj.type == 712 || proj.type == 715 || proj.type == 716 || proj.type == 717 || proj.type == 718 || proj.type == 758 || proj.type == 759 || proj.type == 764 || proj.type == 779 || proj.type == 783 || proj.type == 773 || proj.type == 820 || proj.type == 831 || proj.type == 970 || proj.type == 836 || proj.type == 851 || proj.type == 855 || proj.type == 856 || proj.type == 857 || proj.type == 861 || proj.type == 862 || proj.type == 863 || proj.type == 866 || proj.type == 870 || proj.type == 882 || proj.type == 885 || proj.type == 889 || proj.type == 895 || proj.type == 896 || proj.type == 898 || proj.type == 903 || proj.type == 904 || proj.type == 905 || proj.type == 906 || proj.type == 908 || proj.type == 910 || proj.type == 911 || proj.type == 951 || proj.type == 957 || proj.type == 962 || proj.type == 963 || proj.type == 967 || proj.type == 968 || proj.type == 978 || proj.type == 995 || proj.type == 886 || proj.type == 892 || proj.type == 1024 || proj.type == 1044 || proj.type == 1038 || proj.type == 1050 || proj.type == 1086 || proj.type == 1087 || proj.type == 1088 || proj.type == 1092 || proj.type == 1098 || proj.type == 1105 || proj.type == 1094)
{
                                            Vector2 vector226 = proj.position + new Vector2((float)proj.width, (float)proj.height) / 2f + Vector2.UnitY * proj.gfxOffY - Main.screenPosition;
                                            Texture2D texture2D27 = TextureAssets.Projectile[proj.type].Value;
                                            Microsoft.Xna.Framework.Rectangle rectangle44 = texture2D27.Frame(1, Main.projFrames[proj.type], 0, proj.frame, 0, 0);
                                            if (proj.type == 963)
{
                                                rectangle44 = texture2D27.Frame(4, Main.projFrames[proj.type], 0, proj.frame, 0, 0);
                                            }
                                            if (proj.type == 957)
{
                                                int num492 = 3;
                                                int num493 = proj.frame / Main.projFrames[proj.type];
                                                int num494 = proj.frame % Main.projFrames[proj.type];
                                                rectangle44 = texture2D27.Frame(num492, Main.projFrames[proj.type], num493, num494, 0, 0);
                                            }
                                            if (proj.type == 962)
{
                                                int num495 = 4;
                                                int num496 = proj.frame / Main.projFrames[proj.type];
                                                int num497 = proj.frame % Main.projFrames[proj.type];
                                                rectangle44 = texture2D27.Frame(Main.projFrames[proj.type], num495, num497, num496, 0, 0);
                                            }
                                            if (proj.type == 1092)
{
                                                int num498 = proj.frame / 9;
                                                int num499 = proj.frame % 9;
                                                rectangle44 = texture2D27.Frame(6, 9, num498, num499, 0, 0);
                                            }
                                            if (proj.type == 1094)
{
                                                Main.TryPetting(proj, 5664);
                                                int num500 = 9;
                                                int num501 = proj.frame / num500;
                                                int num502 = proj.frame % num500;
                                                rectangle44 = new Microsoft.Xna.Framework.Rectangle(num501 * 64, num502 * 46, 62, 44);
                                                if (proj.ai[0] >= 1000f)
{
                                                    spriteEffects2 ^= SpriteEffects.FlipHorizontally;
                                                }
                                                vector226.Y -= 11f;
                                                int num503 = 60;
                                                int num504 = 0;
                                                if (proj.localAI[2] < (float)num503 && proj.localAI[2] > 1f)
{
                                                    EmoteBubble.DrawTemporaryBubble(Main.spriteBatch, num504, num503, (int)proj.localAI[2], proj);
                                                }
                                            }
                                            Microsoft.Xna.Framework.Color color131 = proj.GetAlpha(color36);
                                            if (proj.type == 623 && Main.CurrentDrawnEntityShader != 0)
{
                                                color131.A = 127;
                                            }
                                            if (proj.type == 995)
{
                                                float num505;
                                                float num506;
                                                Projectile.AI_192_GetJuminoFall(proj, out num505, out num506);
                                                vector226.Y -= 4f;
                                                vector226.Y += num506;
                                                float num507 = Utils.Remap(num505, 0f, 10f, 1f, 0f, true);
                                                color131 = Microsoft.Xna.Framework.Color.Lerp(color131, Microsoft.Xna.Framework.Color.White * proj.Opacity, num507);
                                            }
                                            if (proj.type == 1098)
{
                                                vector226.Y -= 2f;
                                            }
                                            if (proj.type == 1105)
{
                                                vector226.Y -= 2f;
                                                if (proj.velocity.Y == 0f)
{
                                                    vector226.Y += 4f * Utils.GetLerpValue(0f, 0.7853982f, Math.Abs(proj.rotation), true);
                                                }
                                                else
{
                                                    vector226.Y += 4f;
                                                }
                                            }
                                            Vector2 vector227 = rectangle44.Size() / 2f;
                                            if (proj.type == 703)
{
                                                rectangle44.Height -= 2;
                                            }
                                            if (proj.type == 1094)
{
                                                vector227.X += (float)(spriteEffects2.HasFlag(SpriteEffects.FlipHorizontally).ToDirectionInt() * -8);
                                                if (proj.ai[0] >= 1000f)
{
                                                    texture2D27 = TextureAssets.Extra[303].Value;
                                                    rectangle44 = texture2D27.Frame(1, 3, 0, 0, 0, 0);
                                                    vector227 = rectangle44.Size() / 2f;
                                                    vector227.X += (float)(proj.spriteDirection * -10);
                                                    vector227.Y += -6f;
                                                }
                                            }
                                            if (proj.type == 957)
{
                                                float num508 = (float)(Math.Cos((double)((float)Main.mouseTextColor / 255f * 6.2831855f * 2f)) * 4.0);
                                                num508 *= Math.Max(0f, Math.Min(1f, proj.localAI[0] / 100f));
                                                float num509 = 0f;
                                                if (proj.frame > Main.projFrames[proj.type] * 2)
{
                                                    switch (proj.frame % Main.projFrames[proj.type])
{
                                                    case 5:
                                                    case 11:
                                                        num509 = 2f;
                                                        break;
                                                    case 6:
                                                    case 10:
                                                        num509 = 6f;
                                                        break;
                                                    case 7:
                                                        num509 = 8f;
                                                        break;
                                                    case 8:
                                                    case 9:
                                                        num509 = 10f;
                                                        break;
                                                    }
                                                }
                                                vector226.Y += -2f + num508 + num509;
                                            }
                                            if (proj.type == 895 || proj.type == 896 || proj.type == 898 || proj.type == 963)
{
                                                float num510 = 2f;
                                                if (proj.isAPreviewDummy)
{
                                                    num510 = 0.5f;
                                                }
                                                vector226.Y += -num510 + (float)(Math.Cos((double)((float)Main.mouseTextColor / 255f * 6.2831855f * 2f)) * (double)(num510 * 2f));
                                            }
                                            if (proj.type == 963 && proj.localAI[1] >= 0f)
{
                                                float num511 = proj.localAI[1];
                                                float num512 = 1f - num511;
                                                Microsoft.Xna.Framework.Color color132 = proj.GetAlpha(new Microsoft.Xna.Framework.Color(255, 220, 220)) * num512 * num512 * 0.8f;
                                                color132.A = 0;
                                                short num513 = 536;
                                                this.LoadProjectile((int)num513);
                                                Texture2D value52 = TextureAssets.Projectile[(int)num513].Value;
                                                Vector2 vector228 = value52.Size() * new Vector2(0.5f, 1f);
                                                float num514 = 9f;
                                                float num515 = proj.velocity.ToRotation();
                                                if (proj.velocity.Length() < 0.1f)
{
                                                    num515 = ((proj.direction == 1) ? 0f : 3.1415927f);
                                                }
                                                Vector2 vector229 = (num515 + 1.5707964f).ToRotationVector2();
                                                int num516 = 0;
                                                while ((float)num516 < num514)
{
                                                    float num517 = (float)((num516 % 2 == 0) ? (-1) : 1);
                                                    float num518 = ((float)num516 + 1f) * num517 * 0.2f * (0.2f + 2f * num511) + num515 + 1.5707964f;
                                                    float num519 = Utils.Remap(Vector2.Dot(num518.ToRotationVector2(), vector229), -1f, 1f, 0f, 1f, true);
                                                    float num520 = proj.scale * (0.15f + 0.6f * (float)Math.Sin((double)(Main.GlobalTimeWrappedHourly + (float)num516 * 0.739f))) * num519;
                                                    Texture2D texture2D28 = value52;
                                                    Vector2 vector230 = vector226;
                                                    Vector2 vector231 = proj.rotation.ToRotationVector2();
                                                    double num521 = (double)(6.2831855f * (1f / num514) * (float)num516 + Main.GlobalTimeWrappedHourly);
                                                    Vector2 vector49 = default(Vector2);
                                                    Main.EntitySpriteDraw(texture2D28, vector230 + vector231.RotatedBy(num521, vector49) * 4f * proj.scale, null, color132 * num519, num518, vector228, new Vector2(num520 * 1.5f, num520), SpriteEffects.None, 0f);
                                                    num516++;
                                                }
                                            }
                                            if (proj.type == 962)
{
                                                float num522 = Utils.Remap(proj.ai[0], 0f, 30f, 1f, 0f, true);
                                                Microsoft.Xna.Framework.Color color133 = proj.GetAlpha(Microsoft.Xna.Framework.Color.White) * num522 * num522 * 0.3f;
                                                color133.A = 0;
                                                for (int num523 = 0; num523 < 4; num523++)
{
                                                    Texture2D texture2D29 = texture2D27;
                                                    Vector2 vector232 = vector226;
                                                    Vector2 vector233 = proj.rotation.ToRotationVector2();
                                                    double num524 = (double)(1.5707964f * (float)num523);
                                                    Vector2 vector49 = default(Vector2);
                                                    Main.EntitySpriteDraw(texture2D29, vector232 + vector233.RotatedBy(num524, vector49) * 2f * proj.scale, new Microsoft.Xna.Framework.Rectangle?(rectangle44), color133, proj.rotation, vector227, proj.scale, spriteEffects2, 0f);
                                                }
                                            }
                                            if (proj.type == 855)
{
                                                float y2 = (Main.GlobalTimeWrappedHourly % 6f / 6f * 6.2831855f).ToRotationVector2().Y;
                                                float num525 = y2 * 0.3f + 0.7f;
                                                Microsoft.Xna.Framework.Color color134 = color131 * num525 * 0.3f;
                                                for (int num526 = 0; num526 < 4; num526++)
{
                                                    float num527 = 0f;
                                                    float num528 = 0f;
                                                    switch (num526)
{
                                                    case 0:
                                                        num527 = 4f;
                                                        break;
                                                    case 1:
                                                        num527 = -4f;
                                                        break;
                                                    case 2:
                                                        num528 = 4f;
                                                        break;
                                                    case 3:
                                                        num528 = -4f;
                                                        break;
                                                    }
                                                    Vector2 vector234 = new Vector2(num527, num528);
                                                    double num529 = (double)proj.rotation;
                                                    Vector2 vector49 = default(Vector2);
                                                    Vector2 vector235 = vector234.RotatedBy(num529, vector49) * y2;
                                                    Main.spriteBatch.Draw(texture2D27, vector226 + vector235, new Microsoft.Xna.Framework.Rectangle?(rectangle44), color134, proj.rotation, rectangle44.Size() / 2f, 1f, SpriteEffects.None, 0f);
                                                }
                                            }
                                            else if (proj.type == 908)
{
                                                PlayerTitaniumStormBuffTextureContent playerTitaniumStormBuff = TextureAssets.RenderTargets.PlayerTitaniumStormBuff;
                                                vector226 += (Main.GlobalTimeWrappedHourly * 8f + (float)proj.whoAmI).ToRotationVector2() * 4f;
                                                playerTitaniumStormBuff.Request();
                                                if (playerTitaniumStormBuff.IsReady)
{
                                                    texture2D27 = playerTitaniumStormBuff.GetTarget();
                                                }
                                                rectangle44 = texture2D27.Frame(Main.projFrames[proj.type], 1, proj.frame, 0, 0, 0);
                                                vector227 = rectangle44.Size() / 2f;
                                            }
                                            else if (proj.type == 764)
{
                                                this.DrawProjWithStarryTrail(proj, player, color36, spriteEffects2);
                                            }
                                            else if (proj.type == 856)
{
                                                this.DrawProjWithStarryTrail(proj, player, color36, spriteEffects2);
                                            }
                                            else if (proj.type == 857)
{
                                                this.DrawProjWithStarryTrail(proj, player, color36, spriteEffects2);
                                                color131 = Microsoft.Xna.Framework.Color.White * proj.Opacity * 0.9f;
                                                color131.A /= 2;
                                                rectangle44 = texture2D27.Frame(15, 1, proj.frame, 0, 0, 0);
                                                vector227 = rectangle44.Size() / 2f;
                                                Main.DrawPrettyStarSparkle(proj.Opacity, spriteEffects2, vector226, color131, proj.GetFirstFractalColor(), proj.localAI[0], 15f, 30f, 30f, 45f, 0f, new Vector2(5f, 2f), Vector2.One);
                                            }
                                            else if (proj.type == 539)
{
                                                if (proj.ai[0] >= 210f)
{
                                                    float num530 = proj.ai[0] - 210f;
                                                    num530 /= 20f;
                                                    if (num530 > 1f)
{
                                                        num530 = 1f;
                                                    }
                                                    Main.EntitySpriteDraw(TextureAssets.Extra[46].Value, vector226, null, new Microsoft.Xna.Framework.Color(255, 255, 255, 128) * num530, proj.rotation, new Vector2(17f, 22f), proj.scale, spriteEffects2, 0f);
                                                }
                                            }
                                            else if (proj.type == 773)
{
                                                vector227.Y = (float)(rectangle44.Height - 12);
                                            }
                                            else if (proj.type == 866)
{
                                                vector227.X += 14f;
                                            }
                                            else if (proj.type == 759)
{
                                                vector227.Y = (float)(rectangle44.Height - 2);
                                                vector227.X += (float)(((spriteEffects2 & SpriteEffects.FlipHorizontally) != SpriteEffects.None) ? 1 : (-1));
                                            }
                                            else if (proj.type == 758)
{
                                                vector226.Y += (float)(proj.height / 2);
                                                vector227 = rectangle44.Size() * new Vector2(0.5f, 1f);
                                                vector227.Y -= 4f;
                                            }
                                            else if (proj.type == 951)
{
                                                vector226.Y += (float)(proj.height / 2);
                                                vector226.Y -= (float)rectangle44.Height * 0.5f;
                                                vector226.Y += 4f;
                                                vector227 = rectangle44.Size() * new Vector2(0.5f, 0.5f);
                                            }
                                            else if (proj.type == 833)
{
                                                if (proj.frame != 8)
{
                                                    vector226.Y += (float)(proj.height / 2);
                                                    vector227 = rectangle44.Size() * new Vector2(0.5f, 1f);
                                                    vector227.Y -= 4f;
                                                    vector227.X -= (float)(7 * ((spriteEffects2 & SpriteEffects.FlipHorizontally) > SpriteEffects.None).ToDirectionInt());
                                                }
                                            }
                                            else if (proj.type == 834 || proj.type == 835)
{
                                                if (proj.frame != 10)
{
                                                    vector226.Y += (float)(proj.height / 2);
                                                    vector227 = rectangle44.Size() * new Vector2(0.5f, 1f);
                                                    vector227.Y -= 4f;
                                                    vector227.X -= (float)(2 * ((spriteEffects2 & SpriteEffects.FlipHorizontally) > SpriteEffects.None).ToDirectionInt());
                                                }
                                            }
                                            else if (proj.type == 715 || proj.type == 716 || proj.type == 717 || proj.type == 718)
{
                                                rectangle44 = texture2D27.Frame(3, 1, 0, 0, 0, 0);
                                                vector227 = rectangle44.Size() / 2f;
                                                int num531 = (int)proj.ai[0];
                                                Vector2 vector236 = new Vector2((float)(rectangle44.Width / 2), 0f);
                                                Vector2 vector237 = proj.Size / 2f;
                                                Microsoft.Xna.Framework.Color color135 = proj.GetCeleb2Color();
                                                color135.A = 127;
                                                color135 *= 0.8f;
                                                Microsoft.Xna.Framework.Rectangle rectangle45 = rectangle44;
                                                rectangle45.X += rectangle45.Width * 2;
                                                for (int num532 = proj.oldPos.Length - 1; num532 > 0; num532--)
{
                                                    Vector2 vector238 = proj.oldPos[num532] + vector237;
                                                    if (!(vector238 == vector237))
{
                                                        Vector2 vector239 = proj.oldPos[num532 - 1] + vector237;
                                                        float num533 = proj.oldRot[num532];
                                                        Vector2 vector240 = new Vector2(Vector2.Distance(vector238, vector239) / (float)rectangle44.Width, 1f);
                                                        Microsoft.Xna.Framework.Color color136 = color135 * (1f - (float)num532 / (float)proj.oldPos.Length);
                                                        if (num531 != 2)
{
                                                            if (num531 == 5)
{
                                                                vector240 *= 0.5f;
                                                            }
                                                        }
                                                        else
{
                                                            Vector2 vector241 = num533.ToRotationVector2();
                                                            int num534 = num532 + proj.timeLeft;
                                                            if (num534 < 0)
{
                                                                num534 += 20 * (num534 / -20) + 20;
                                                            }
                                                            num534 %= 20;
                                                            float num535 = 0f;
                                                            vector240 *= 0.6f;
                                                            switch (num534)
{
                                                            case 1:
                                                                num535 = 1f;
                                                                break;
                                                            case 2:
                                                                num535 = 2f;
                                                                break;
                                                            case 3:
                                                                num535 = 3f;
                                                                break;
                                                            case 4:
                                                                num535 = 2f;
                                                                break;
                                                            case 5:
                                                                num535 = 1f;
                                                                break;
                                                            case 7:
                                                                num535 = -1f;
                                                                break;
                                                            case 8:
                                                                num535 = -2f;
                                                                break;
                                                            case 9:
                                                                num535 = -3f;
                                                                break;
                                                            case 10:
                                                                num535 = -2f;
                                                                break;
                                                            case 11:
                                                                num535 = -1f;
                                                                break;
                                                            }
                                                            vector238 += vector241 * num535 * 4f;
                                                        }
                                                        Main.EntitySpriteDraw(texture2D27, vector238 - Main.screenPosition, new Microsoft.Xna.Framework.Rectangle?(rectangle45), color136, num533, vector236, vector240, spriteEffects2, 0f);
                                                    }
                                                }
                                            }
                                            else if (proj.type == 663 || proj.type == 665 || proj.type == 667)
{
                                                vector226 = proj.Bottom + Vector2.UnitY * proj.gfxOffY - Main.screenPosition;
                                                vector227 = rectangle44.Size() * new Vector2(0.5f, 1f);
                                                vector227.Y -= 2f;
                                                vector227.Y -= 2f;
                                            }
                                            else if (proj.type == 691 || proj.type == 692 || proj.type == 693)
{
                                                vector226 = proj.Bottom + Vector2.UnitY * proj.gfxOffY - Main.screenPosition;
                                                vector227 = rectangle44.Size() * new Vector2(0.5f, 1f);
                                                vector227.Y -= 2f;
                                                vector227.Y -= 2f;
                                            }
                                            else if (proj.type == 677 || proj.type == 678 || proj.type == 679)
{
                                                if (proj.spriteDirection == -1)
{
                                                    spriteEffects2 ^= SpriteEffects.FlipHorizontally | SpriteEffects.FlipVertically;
                                                }
                                                Texture2D texture2D30 = TextureAssets.Extra[83].Value;
                                                if (proj.type == 678)
{
                                                    texture2D30 = TextureAssets.Extra[84].Value;
                                                }
                                                if (proj.type == 679)
{
                                                    texture2D30 = TextureAssets.Extra[85].Value;
                                                }
                                                Vector2 vector242 = proj.Bottom + Vector2.UnitY * proj.gfxOffY - Main.screenPosition;
                                                Vector2 vector243 = texture2D30.Size() * new Vector2(0.5f, 1f);
                                                vector243.Y -= 2f;
                                                Main.EntitySpriteDraw(texture2D30, vector242, null, color131, 0f, vector243, 1f, spriteEffects2 & SpriteEffects.FlipHorizontally, 0f);
                                                vector227.X += (float)((spriteEffects2 & SpriteEffects.FlipHorizontally) > SpriteEffects.None).ToDirectionInt();
                                                vector226.Y += 1f;
                                                vector226.Y += 2f;
                                                if (proj.type == 678)
{
                                                    vector226.Y += -4f;
                                                }
                                                if (proj.type == 679)
{
                                                    vector226.Y -= 2f;
                                                    if ((spriteEffects2 & SpriteEffects.FlipVertically) == SpriteEffects.None)
{
                                                        vector227.Y += 4f;
                                                    }
                                                    else
{
                                                        vector227.Y -= 4f;
                                                    }
                                                    vector227.X += (float)(((spriteEffects2 & SpriteEffects.FlipHorizontally) > SpriteEffects.None).ToDirectionInt() * 4);
                                                }
                                            }
                                            else if (proj.type == 602)
{
                                                vector227.X = (float)(rectangle44.Width - 6);
                                                vector227.Y -= 1f;
                                                rectangle44.Height -= 2;
                                            }
                                            else if (proj.type == 589)
{
                                                rectangle44 = texture2D27.Frame(5, 1, (int)proj.ai[1], 0, 0, 0);
                                                vector227 = rectangle44.Size() / 2f;
                                            }
                                            else if (proj.type == 590)
{
                                                if (proj.ai[2] == 1f && proj.frame < 3)
{
                                                    proj.frame = 3;
                                                }
                                                rectangle44 = texture2D27.Frame(6, 1, proj.frame, 0, 0, 0);
                                                vector227 = rectangle44.Size() / 2f;
                                            }
                                            else if (proj.type == 836)
{
                                                rectangle44 = texture2D27.Frame(4, 1, proj.frame, 0, 0, 0);
                                                vector227 = rectangle44.Size() / 2f;
                                            }
                                            else if (proj.type == 650 || proj.type == 882 || proj.type == 888 || proj.type == 894 || proj.type == 895 || proj.type == 896 || proj.type == 898 || proj.type == 901 || proj.type == 957)
{
                                                vector227.Y -= 4f;
                                            }
                                            else if (proj.type == 623)
{
                                                if (!Main.gamePaused && proj.ai[0] == 2f)
{
                                                    vector226 += Main.rand.NextVector2Circular(2f, 2f);
                                                }
                                                if (Main.CurrentDrawnEntityShader == 0)
{
                                                    color131.A /= 2;
                                                }
                                            }
                                            else if (proj.type >= 625 && proj.type <= 628)
{
                                                color131.A /= 2;
                                            }
                                            else if (proj.type == 644)
{
                                                Microsoft.Xna.Framework.Color color137 = Main.hslToRgb(proj.ai[0], 1f, 0.5f, byte.MaxValue).MultiplyRGBA(new Microsoft.Xna.Framework.Color(255, 255, 255, 0));
                                                Main.EntitySpriteDraw(texture2D27, vector226, new Microsoft.Xna.Framework.Rectangle?(rectangle44), color137, proj.rotation, vector227, proj.scale * 2f, spriteEffects2, 0f);
                                                Main.EntitySpriteDraw(texture2D27, vector226, new Microsoft.Xna.Framework.Rectangle?(rectangle44), color137, 0f, vector227, proj.scale * 2f, spriteEffects2, 0f);
                                                if (proj.ai[1] != -1f && proj.Opacity > 0.3f)
{
                                                    Vector2 vector244 = Main.projectile[(int)proj.ai[1]].Center - proj.Center;
                                                    Vector2 vector245 = new Vector2(1f, vector244.Length() / (float)texture2D27.Height);
                                                    float num536 = vector244.ToRotation() + 1.5707964f;
                                                    float num537 = MathHelper.Distance(30f, proj.localAI[1]) / 20f;
                                                    num537 = MathHelper.Clamp(num537, 0f, 1f);
                                                    if (num537 > 0f)
{
                                                        Main.EntitySpriteDraw(texture2D27, vector226 + vector244 / 2f, new Microsoft.Xna.Framework.Rectangle?(rectangle44), color137 * num537, num536, vector227, vector245, spriteEffects2, 0f);
                                                        Main.EntitySpriteDraw(texture2D27, vector226 + vector244 / 2f, new Microsoft.Xna.Framework.Rectangle?(rectangle44), color131 * num537, num536, vector227, vector245 / 2f, spriteEffects2, 0f);
                                                    }
                                                }
                                            }
                                            else if (proj.type == 658)
{
                                                Microsoft.Xna.Framework.Color color138 = Main.hslToRgb(0.136f, 1f, 0.5f, byte.MaxValue).MultiplyRGBA(new Microsoft.Xna.Framework.Color(255, 255, 255, 0));
                                                Main.EntitySpriteDraw(texture2D27, vector226, new Microsoft.Xna.Framework.Rectangle?(rectangle44), color138, 0f, vector227, new Vector2(1f, 5f) * proj.scale * 2f, spriteEffects2, 0f);
                                            }
                                            Main.EntitySpriteDraw(texture2D27, vector226, new Microsoft.Xna.Framework.Rectangle?(rectangle44), color131, proj.rotation, vector227, proj.scale, spriteEffects2, 0f);
                                            if (proj.type == 896)
{
                                                Texture2D value53 = TextureAssets.GlowMask[278].Value;
                                                Microsoft.Xna.Framework.Color color139 = new Microsoft.Xna.Framework.Color(150, 150, 150, 100);
                                                for (int num538 = 0; num538 < 2; num538++)
{
                                                    Vector2 vector246 = vector226 + new Vector2((float)Main.rand.Next(-10, 11) * 0.1f, (float)Main.rand.Next(-10, 11) * 0.1f);
                                                    Main.EntitySpriteDraw(value53, vector246, new Microsoft.Xna.Framework.Rectangle?(rectangle44), color139, proj.rotation, vector227, proj.scale, spriteEffects2, 0f);
                                                }
                                                Main.EntitySpriteDraw(value53, vector226, new Microsoft.Xna.Framework.Rectangle?(rectangle44), Microsoft.Xna.Framework.Color.White, proj.rotation, vector227, proj.scale, spriteEffects2, 0f);
                                            }
                                            if (proj.type == 1098)
{
                                                Texture2D value54 = TextureAssets.GlowMask[377].Value;
                                                Microsoft.Xna.Framework.Color color140 = new Microsoft.Xna.Framework.Color(255, 255, 255, 127);
                                                float num539 = 1f;
                                                if (proj.frame == 0)
{
                                                    color140 = Microsoft.Xna.Framework.Color.Lerp(color140, new Microsoft.Xna.Framework.Color(100, 210, 255, 127), Utils.Remap(proj.Opacity, 0f, 0.7f, 0f, 1f, true));
                                                    color140 *= Utils.Remap(proj.Opacity, 0f, 0.7f, 0f, 1f, true) * Utils.Remap(proj.Opacity, 0.7f, 1f, 1f, 0f, true);
                                                    num539 = Utils.Remap(proj.Opacity, 0f, 1f, 1f, 1.05f, true);
                                                }
                                                else
{
                                                    color140 *= Utils.Remap(proj.localAI[1], 5f, 10f, 0f, 1f, true);
                                                }
                                                Main.TryPetting(proj, 5667);
                                                Main.EntitySpriteDraw(value54, vector226, new Microsoft.Xna.Framework.Rectangle?(rectangle44), color140, proj.rotation, vector227, proj.scale * num539, spriteEffects2, 0f);
                                                proj.direction = -proj.spriteDirection;
                                                int num540 = 60;
                                                if (proj.ai[0] == 5f)
{
                                                    if (proj.ai[1] < (float)num540)
{
                                                        EmoteBubble.DrawTemporaryBubble(Main.spriteBatch, 0, num540, num540 - (int)proj.ai[1], proj);
                                                    }
                                                }
                                                else if (proj.ai[0] == 4f)
{
                                                    if (proj.ai[1] < (float)num540)
{
                                                        EmoteBubble.DrawTemporaryBubble(Main.spriteBatch, 17, num540, num540 - (int)proj.ai[1], proj);
                                                    }
                                                }
                                                else if (proj.ai[0] != 0f && proj.ai[1] < 40f)
{
                                                    EmoteBubble.DrawTemporaryBubble(Main.spriteBatch, 3, num540, 40 - (int)proj.ai[1], proj);
                                                }
                                                proj.direction = proj.spriteDirection;
                                            }
                                            if (proj.type == 889)
{
                                                Texture2D value55 = TextureAssets.GlowMask[276].Value;
                                                Microsoft.Xna.Framework.Color color141 = Microsoft.Xna.Framework.Color.White * (float)Main.mouseTextColor;
                                                Main.EntitySpriteDraw(value55, vector226, new Microsoft.Xna.Framework.Rectangle?(rectangle44), color141, proj.rotation, vector227, proj.scale, spriteEffects2, 0f);
                                                if (!proj.isAPreviewDummy)
{
                                                    for (int num541 = 0; num541 < 4; num541++)
{
                                                        int num542 = 28;
                                                        int num543 = 7 + num541;
                                                        float num544 = 100f;
                                                        bool flag39 = num543 == 8;
                                                        Microsoft.Xna.Framework.Rectangle rectangle46 = texture2D27.Frame(1, Main.projFrames[proj.type], 0, num543, 0, 0);
                                                        Vector2 vector247 = vector226;
                                                        Vector2 vector248 = vector226;
                                                        SpriteEffects spriteEffects7 = SpriteEffects.None;
                                                        float num545 = Main.GlobalTimeWrappedHourly * 2f;
                                                        switch (num541)
{
                                                        case 1:
                                                            num545 += 1.5707964f;
                                                            break;
                                                        case 2:
                                                            num545 += 3.1415927f;
                                                            break;
                                                        case 3:
                                                            num545 += 4.712389f;
                                                            break;
                                                        }
                                                        num545 *= 3f;
                                                        float num546 = num545;
                                                        vector248 += num545.ToRotationVector2() * (float)num542;
                                                        if (proj.localAI[0] == num544)
{
                                                            Main.EntitySpriteDraw(texture2D27, vector248, new Microsoft.Xna.Framework.Rectangle?(rectangle46), color131, num546, vector227, proj.scale, spriteEffects7, 0f);
                                                            if (flag39)
{
                                                                Main.EntitySpriteDraw(value55, vector248, new Microsoft.Xna.Framework.Rectangle?(rectangle46), color141, num546, vector227, proj.scale, spriteEffects7, 0f);
                                                            }
                                                        }
                                                        else
{
                                                            Vector2 vector249 = new Vector2((float)num542, -16f) + proj.velocity * 1.5f;
                                                            float num547 = 4f;
                                                            float num548 = -0.35f;
                                                            switch (num541)
{
                                                            case 1:
                                                                vector249.X *= -1f;
                                                                spriteEffects7 = SpriteEffects.FlipHorizontally;
                                                                num548 = 0.35f;
                                                                num547 = -3f;
                                                                break;
                                                            case 2:
                                                                vector249.Y = 16f;
                                                                num548 = 0.35f;
                                                                num547 = 2f;
                                                                break;
                                                            case 3:
                                                                vector249.X *= -1f;
                                                                vector249.Y = 16f;
                                                                spriteEffects7 = SpriteEffects.FlipHorizontally;
                                                                num548 = -0.35f;
                                                                num547 = -1f;
                                                                break;
                                                            }
                                                            vector249 += (Main.GlobalTimeWrappedHourly * num547).ToRotationVector2() * 4f;
                                                            vector247 += vector249;
                                                            float num549 = proj.localAI[0] / num544;
                                                            vector247 = Vector2.Lerp(vector247, vector248, num549);
                                                            num546 = ((num549 > 0.5f) ? num545 : num548);
                                                            Main.EntitySpriteDraw(texture2D27, vector247, new Microsoft.Xna.Framework.Rectangle?(rectangle46), color131, num546, vector227, proj.scale, spriteEffects7, 0f);
                                                            if (flag39)
{
                                                                Main.EntitySpriteDraw(value55, vector247, new Microsoft.Xna.Framework.Rectangle?(rectangle46), color141, num546, vector227, proj.scale, spriteEffects7, 0f);
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                            if (proj.type == 885 && !proj.isAPreviewDummy)
{
                                                for (int num550 = 0; num550 < 2; num550++)
{
                                                    SpriteEffects spriteEffects8 = SpriteEffects.None;
                                                    int num551 = -30;
                                                    if (num550 == 1)
{
                                                        num551 = 30;
                                                        spriteEffects8 = SpriteEffects.FlipHorizontally;
                                                    }
                                                    int num552 = (int)proj.localAI[0];
                                                    if (proj.frame == 6)
{
                                                        num552 = 0;
                                                    }
                                                    else if (num550 == 1)
{
                                                        num552 = 2 - num552;
                                                    }
                                                    num552 += 7;
                                                    Microsoft.Xna.Framework.Rectangle rectangle47 = texture2D27.Frame(1, Main.projFrames[proj.type], 0, num552, 0, 0);
                                                    Vector2 vector250 = vector226 + new Vector2((float)num551, 0f);
                                                    Vector2 vector251 = (Main.GlobalTimeWrappedHourly * 2f).ToRotationVector2() * 4f;
                                                    vector251 += proj.velocity * -1.5f;
                                                    Vector2 vector252 = (Main.GlobalTimeWrappedHourly * 1f).ToRotationVector2() * 3f;
                                                    if (num550 == 1)
{
                                                        vector250 += vector251 + vector252;
                                                    }
                                                    else
{
                                                        vector250 -= vector251;
                                                    }
                                                    Main.EntitySpriteDraw(texture2D27, vector250, new Microsoft.Xna.Framework.Rectangle?(rectangle47), color131, 0f, vector227, proj.scale, spriteEffects8, 0f);
                                                }
                                            }
                                            if (proj.type == 535)
{
                                                for (int num553 = 0; num553 < 1000; num553++)
{
                                                    if (Main.projectile[num553].active && Main.projectile[num553].owner == proj.owner && Main.projectile[num553].type == 536)
{
                                                        this.DrawProj(num553);
                                                    }
                                                }
                                            }
                                            if (proj.type == 1038)
{
                                                Microsoft.Xna.Framework.Color color142 = new Microsoft.Xna.Framework.Color(255, 0, 77);
                                                Main.DrawPrettyStarSparkle(proj.Opacity, SpriteEffects.None, vector226, new Microsoft.Xna.Framework.Color(255, 255, 255, 0) * 0.5f, color142, proj.ai[0], 0f, 5f, 5f, 20f, 1.5707964f, new Vector2(0.7f, 1.5f), Vector2.One);
                                            }
                                            else if (proj.type == 715 || proj.type == 716 || proj.type == 717 || proj.type == 718)
{
                                                rectangle44.X += rectangle44.Width;
                                                Microsoft.Xna.Framework.Color celeb2Color = proj.GetCeleb2Color();
                                                celeb2Color.A = 80;
                                                Main.EntitySpriteDraw(texture2D27, vector226, new Microsoft.Xna.Framework.Rectangle?(rectangle44), celeb2Color, proj.rotation, vector227, proj.scale, spriteEffects2, 0f);
                                            }
                                            else if (proj.type == 702)
{
                                                Texture2D value56 = TextureAssets.Flames[5].Value;
                                                Vector2 vector253 = value56.Size() / 2f;
                                                Vector2 vector254 = new Vector2((float)(5 * proj.spriteDirection), -10f);
                                                double num554 = (double)proj.rotation;
                                                Vector2 vector49 = default(Vector2);
                                                Vector2 vector255 = vector254.RotatedBy(num554, vector49);
                                                ulong num555 = (ulong)(proj.localAI[0] / 4f);
                                                for (int num556 = 0; num556 < 5; num556++)
{
                                                    Microsoft.Xna.Framework.Color color143 = new Microsoft.Xna.Framework.Color(100, 100, 100, 0);
                                                    float num557 = (float)Utils.RandomInt(ref num555, -10, 11) * 0.15f;
                                                    float num558 = (float)Utils.RandomInt(ref num555, -10, 1) * 0.35f;
                                                    Main.EntitySpriteDraw(value56, vector226 + vector255 + new Vector2(num557, num558), null, color143, proj.rotation, vector253, 1f, spriteEffects2, 0f);
                                                }
                                            }
                                            else if (proj.type == 663 || proj.type == 665 || proj.type == 667)
{
                                                Texture2D texture2D31 = TextureAssets.GlowMask[221].Value;
                                                num22 = proj.type;
                                                if (num22 != 665)
{
                                                    if (num22 == 667)
{
                                                        texture2D31 = TextureAssets.GlowMask[223].Value;
                                                    }
                                                }
                                                else
{
                                                    texture2D31 = TextureAssets.GlowMask[222].Value;
                                                }
                                                float num559 = (proj.localAI[0] / 100f * 6.2831855f).ToRotationVector2().X * 1f + 1f;
                                                Microsoft.Xna.Framework.Color color144 = new Microsoft.Xna.Framework.Color(140, 100, 40, 0) * (num559 / 4f + 0.5f) * 1f;
                                                for (float num560 = 0f; num560 < 4f; num560 += 1f)
{
                                                    Main.EntitySpriteDraw(texture2D31, vector226 + (num560 * 1.5707964f).ToRotationVector2() * num559, new Microsoft.Xna.Framework.Rectangle?(rectangle44), color144, proj.rotation, vector227, proj.scale, spriteEffects2, 0f);
                                                }
                                            }
                                            else if (proj.type == 644)
{
                                                Main.EntitySpriteDraw(texture2D27, vector226, new Microsoft.Xna.Framework.Rectangle?(rectangle44), color131, 0f, vector227, proj.scale, spriteEffects2, 0f);
                                            }
                                            else if (proj.type == 963)
{
                                                int num561 = player.ownedProjectileCounts[970] - 1;
                                                int num562 = (num561 + 3) % 3;
                                                int num563 = num561 / 3;
                                                Vector3 vector256 = Main.rgbToHsl(new Microsoft.Xna.Framework.Color(250, 150, 180));
                                                vector256 = new Vector3(0f, 1f, 0.6f);
                                                if (num563 == 1)
{
                                                    vector256 = Main.rgbToHsl(Microsoft.Xna.Framework.Color.HotPink);
                                                    vector256.Z += 0.1f;
                                                    vector256.X -= 0.05f;
                                                }
                                                vector256.X = (vector256.X - (float)num563 * 0.13f + 1f) % 1f;
                                                Microsoft.Xna.Framework.Color color145 = Main.hslToRgb(vector256);
                                                Microsoft.Xna.Framework.Color color146 = Lighting.GetColor((int)(proj.Center.X / 16f), (int)(proj.Center.Y / 16f), color145);
                                                rectangle44.X += rectangle44.Width * (1 + num562);
                                                Main.EntitySpriteDraw(texture2D27, vector226, new Microsoft.Xna.Framework.Rectangle?(rectangle44), color146, proj.rotation, vector227, proj.scale, spriteEffects2, 0f);
                                            }
                                            else if (proj.type == 773 && proj.velocity.Length() == 0f)
{
                                                Texture2D value57 = TextureAssets.GlowMask[266].Value;
                                                Microsoft.Xna.Framework.Color color147 = Microsoft.Xna.Framework.Color.White * (float)Main.mouseTextColor;
                                                Main.EntitySpriteDraw(value57, vector226, new Microsoft.Xna.Framework.Rectangle?(rectangle44), color147, proj.rotation, vector227, proj.scale, spriteEffects2, 0f);
                                            }
                                            else if (proj.type == 658)
{
                                                Main.EntitySpriteDraw(texture2D27, vector226, new Microsoft.Xna.Framework.Rectangle?(rectangle44), color131, 0f, vector227, new Vector2(1f, 8f) * proj.scale, spriteEffects2, 0f);
                                            }
                                            else if (proj.type == 602)
{
                                                texture2D27 = TextureAssets.Extra[60].Value;
                                                Microsoft.Xna.Framework.Color color148 = color131;
                                                color148.A = 0;
                                                color148 *= 0.3f;
                                                vector227 = texture2D27.Size() / 2f;
                                                Main.EntitySpriteDraw(texture2D27, vector226, null, color148, proj.rotation - 1.5707964f, vector227, proj.scale, spriteEffects2, 0f);
                                                texture2D27 = TextureAssets.Extra[59].Value;
                                                color148 = color131;
                                                color148.A = 0;
                                                color148 *= 0.13f;
                                                vector227 = texture2D27.Size() / 2f;
                                                Main.EntitySpriteDraw(texture2D27, vector226, null, color148, proj.rotation - 1.5707964f, vector227, proj.scale * 0.9f, spriteEffects2, 0f);
                                            }
                                            else if (proj.type == 539)
{
                                                Main.EntitySpriteDraw(TextureAssets.GlowMask[140].Value, vector226, new Microsoft.Xna.Framework.Rectangle?(rectangle44), new Microsoft.Xna.Framework.Color(255, 255, 255, 0), proj.rotation, vector227, proj.scale, spriteEffects2, 0f);
                                            }
                                            else if (proj.type == 613)
{
                                                Main.EntitySpriteDraw(TextureAssets.GlowMask[189].Value, vector226, new Microsoft.Xna.Framework.Rectangle?(rectangle44), new Microsoft.Xna.Framework.Color(128 - proj.alpha / 2, 128 - proj.alpha / 2, 128 - proj.alpha / 2, 0), proj.rotation, vector227, proj.scale, spriteEffects2, 0f);
                                            }
                                            else if (proj.type == 614)
{
                                                Main.EntitySpriteDraw(TextureAssets.GlowMask[190].Value, vector226, new Microsoft.Xna.Framework.Rectangle?(rectangle44), new Microsoft.Xna.Framework.Color(128 - proj.alpha / 2, 128 - proj.alpha / 2, 128 - proj.alpha / 2, 0), proj.rotation, vector227, proj.scale, spriteEffects2, 0f);
                                            }
                                            else if (proj.type == 574)
{
                                                Main.EntitySpriteDraw(TextureAssets.GlowMask[148].Value, vector226, new Microsoft.Xna.Framework.Rectangle?(rectangle44), new Microsoft.Xna.Framework.Color(255, 255, 255, 0), proj.rotation, vector227, proj.scale, spriteEffects2, 0f);
                                            }
                                            else if (proj.type == 691 || proj.type == 692 || proj.type == 693)
{
                                                Texture2D texture2D32 = TextureAssets.GlowMask[235].Value;
                                                num22 = proj.type;
                                                if (num22 != 692)
{
                                                    if (num22 == 693)
{
                                                        texture2D32 = TextureAssets.GlowMask[237].Value;
                                                    }
                                                }
                                                else
{
                                                    texture2D32 = TextureAssets.GlowMask[236].Value;
                                                }
                                                Main.EntitySpriteDraw(texture2D32, vector226, new Microsoft.Xna.Framework.Rectangle?(rectangle44), new Microsoft.Xna.Framework.Color(255, 255, 255, 127), proj.rotation, vector227, proj.scale, spriteEffects2, 0f);
                                            }
                                            else if (proj.type == 590)
{
                                                Main.EntitySpriteDraw(TextureAssets.GlowMask[168].Value, vector226, new Microsoft.Xna.Framework.Rectangle?(rectangle44), new Microsoft.Xna.Framework.Color(127 - proj.alpha / 2, 127 - proj.alpha / 2, 127 - proj.alpha / 2, 0), proj.rotation, vector227, proj.scale, spriteEffects2, 0f);
                                            }
                                            else if (proj.type == 623 || (proj.type >= 625 && proj.type <= 628))
{
                                                if (player.ghostFade != 0f)
{
                                                    float num564 = player.ghostFade * 5f;
                                                    for (float num565 = 0f; num565 < 4f; num565 += 1f)
{
                                                        Texture2D texture2D33 = texture2D27;
                                                        Vector2 vector257 = vector226;
                                                        Vector2 unitY5 = Vector2.UnitY;
                                                        double num566 = (double)(num565 * 6.2831855f / 4f);
                                                        Vector2 vector49 = default(Vector2);
                                                        Main.EntitySpriteDraw(texture2D33, vector257 + unitY5.RotatedBy(num566, vector49) * num564, new Microsoft.Xna.Framework.Rectangle?(rectangle44), color131 * 0.1f, proj.rotation, vector227, proj.scale, spriteEffects2, 0f);
                                                    }
                                                }
                                                if (proj.type == 623 && proj.ai[0] == 2f && proj.frame >= 14)
{
                                                    this.DrawProj_StardustGuardianPunching(proj);
                                                }
                                            }
                                            else if (proj.type == 643)
{
                                                float num567 = (float)Math.Cos((double)(6.2831855f * (proj.localAI[0] / 60f))) + 3f + 3f;
                                                for (float num568 = 0f; num568 < 4f; num568 += 1f)
{
                                                    Texture2D texture2D34 = texture2D27;
                                                    Vector2 vector258 = vector226;
                                                    Vector2 unitY6 = Vector2.UnitY;
                                                    double num569 = (double)(num568 * 1.5707964f);
                                                    Vector2 vector49 = default(Vector2);
                                                    Main.EntitySpriteDraw(texture2D34, vector258 + unitY6.RotatedBy(num569, vector49) * num567, new Microsoft.Xna.Framework.Rectangle?(rectangle44), color131 * 0.2f, proj.rotation, vector227, proj.scale, spriteEffects2, 0f);
                                                }
                                            }
                                            else if (proj.type == 650)
{
                                                float num570 = (float)((int)(proj.localAI[0] / 6.2831855f));
                                                float num571 = proj.localAI[0] % 6.2831855f - 3.1415927f;
                                                float num572 = (float)Math.IEEERemainder((double)proj.localAI[1], 1.0);
                                                if (num572 < 0f)
{
                                                    num572 += 1f;
                                                }
                                                int num573 = (int)Math.Floor((double)proj.localAI[1]);
                                                float num574 = 5f;
                                                float num575 = 1f + (float)num573 * 0.02f;
                                                if (num570 == 1f)
{
                                                    num574 = 7f;
                                                }
                                                Vector2 vector259 = num571.ToRotationVector2() * num572 * num574 * proj.scale;
                                                texture2D27 = TextureAssets.Extra[66].Value;
                                                Main.EntitySpriteDraw(texture2D27, vector226 + vector259, null, color131, proj.rotation, texture2D27.Size() / 2f, num575, SpriteEffects.None, 0f);
                                            }
                                            else if (proj.type == 1092)
{
                                                float num576 = Utils.Remap(proj.ai[1], 100f, 120f, 0f, 1f, true);
                                                Microsoft.Xna.Framework.Color color149 = new Microsoft.Xna.Framework.Color(1f, 1f, 1f, num576);
                                                Main.EntitySpriteDraw(texture2D27, vector226, new Microsoft.Xna.Framework.Rectangle?(rectangle44), color149, proj.rotation, vector227, proj.scale, spriteEffects2, 0f);
                                            }
                                            if (proj.type == 1094)
{
                                                Microsoft.Xna.Framework.Rectangle rectangle48 = rectangle44;
                                                int num577 = 414;
                                                if (proj.ai[0] >= 1000f)
{
                                                    num577 = rectangle44.Height + 2;
                                                }
                                                rectangle48.Offset(0, num577 * 2);
                                                ulong tileFrameSeed = Main.TileFrameSeed;
                                                for (int num578 = 0; num578 < 2; num578++)
{
                                                    Vector2 zero2 = new Vector2((float)Utils.RandomInt(ref tileFrameSeed, -1, 2), (float)Utils.RandomInt(ref tileFrameSeed, -1, 2));
                                                    if (num578 == 0)
{
                                                        zero2 = Vector2.Zero;
                                                    }
                                                    Main.EntitySpriteDraw(texture2D27, vector226 + zero2, new Microsoft.Xna.Framework.Rectangle?(rectangle48), new Microsoft.Xna.Framework.Color(255, 255, 255, 127) * proj.Opacity, proj.rotation, vector227, proj.scale, spriteEffects2, 0f);
                                                }
                                                if (proj.alpha > 0)
{
                                                    Microsoft.Xna.Framework.Color color150 = new Microsoft.Xna.Framework.Color(255, 255, 255, 127);
                                                    color150 = Microsoft.Xna.Framework.Color.Lerp(color150, new Microsoft.Xna.Framework.Color(100, 210, 255, 127), Utils.Remap(proj.Opacity, 0f, 0.7f, 0f, 1f, true));
                                                    color150 *= Utils.Remap(proj.Opacity, 0f, 0.7f, 0f, 1f, true) * Utils.Remap(proj.Opacity, 0.7f, 1f, 1f, 0f, true);
                                                    Microsoft.Xna.Framework.Rectangle rectangle49 = rectangle44;
                                                    rectangle49.Offset(0, num577);
                                                    Main.EntitySpriteDraw(texture2D27, vector226, new Microsoft.Xna.Framework.Rectangle?(rectangle49), color150, proj.rotation, vector227, proj.scale, spriteEffects2, 0f);
                                                    return;
                                                }
                                            }
                                        }
                                        else
{
                                            if (proj.type == 466)
{
                                                Vector2 vector260 = proj.position + new Vector2((float)proj.width, (float)proj.height) / 2f + Vector2.UnitY * proj.gfxOffY - Main.screenPosition;
                                                Texture2D value58 = TextureAssets.Extra[33].Value;
                                                proj.GetAlpha(color36);
                                                Vector2 vector261 = new Vector2(proj.scale) / 2f;
                                                for (int num579 = 0; num579 < 3; num579++)
{
                                                    if (num579 == 0)
{
                                                        vector261 = new Vector2(proj.scale) * 0.6f;
                                                        DelegateMethods.c_1 = new Microsoft.Xna.Framework.Color(115, 204, 219, 0) * 0.5f;
                                                    }
                                                    else if (num579 == 1)
{
                                                        vector261 = new Vector2(proj.scale) * 0.4f;
                                                        DelegateMethods.c_1 = new Microsoft.Xna.Framework.Color(113, 251, 255, 0) * 0.5f;
                                                    }
                                                    else
{
                                                        vector261 = new Vector2(proj.scale) * 0.2f;
                                                        DelegateMethods.c_1 = new Microsoft.Xna.Framework.Color(255, 255, 255, 0) * 0.5f;
                                                    }
                                                    DelegateMethods.f_1 = 1f;
                                                    for (int num580 = proj.oldPos.Length - 1; num580 > 0; num580--)
{
                                                        if (!(proj.oldPos[num580] == Vector2.Zero))
{
                                                            Vector2 vector262 = proj.oldPos[num580] + new Vector2((float)proj.width, (float)proj.height) / 2f + Vector2.UnitY * proj.gfxOffY - Main.screenPosition;
                                                            Vector2 vector263 = proj.oldPos[num580 - 1] + new Vector2((float)proj.width, (float)proj.height) / 2f + Vector2.UnitY * proj.gfxOffY - Main.screenPosition;
                                                            Utils.DrawLaser(Main.spriteBatch, value58, vector262, vector263, vector261, new Utils.LaserLineFraming(DelegateMethods.LightningLaserDraw));
                                                        }
                                                    }
                                                    if (proj.oldPos[0] != Vector2.Zero)
{
                                                        DelegateMethods.f_1 = 1f;
                                                        Vector2 vector264 = proj.oldPos[0] + new Vector2((float)proj.width, (float)proj.height) / 2f + Vector2.UnitY * proj.gfxOffY - Main.screenPosition;
                                                        Utils.DrawLaser(Main.spriteBatch, value58, vector264, vector260, vector261, new Utils.LaserLineFraming(DelegateMethods.LightningLaserDraw));
                                                    }
                                                }
                                                return;
                                            }
                                            if (proj.type == 580)
{
                                                Vector2 vector265 = proj.position + new Vector2((float)proj.width, (float)proj.height) / 2f + Vector2.UnitY * proj.gfxOffY - Main.screenPosition;
                                                Texture2D value59 = TextureAssets.Extra[33].Value;
                                                proj.GetAlpha(color36);
                                                Vector2 vector266 = new Vector2(proj.scale) / 2f;
                                                for (int num581 = 0; num581 < 2; num581++)
{
                                                    float num582 = ((proj.localAI[1] == -1f || proj.localAI[1] == 1f) ? (-0.2f) : 0f);
                                                    if (num581 == 0)
{
                                                        vector266 = new Vector2(proj.scale) * (0.5f + num582);
                                                        DelegateMethods.c_1 = new Microsoft.Xna.Framework.Color(115, 244, 219, 0) * 0.5f;
                                                    }
                                                    else
{
                                                        vector266 = new Vector2(proj.scale) * (0.3f + num582);
                                                        DelegateMethods.c_1 = new Microsoft.Xna.Framework.Color(255, 255, 255, 0) * 0.5f;
                                                    }
                                                    DelegateMethods.f_1 = 1f;
                                                    for (int num583 = proj.oldPos.Length - 1; num583 > 0; num583--)
{
                                                        if (!(proj.oldPos[num583] == Vector2.Zero))
{
                                                            Vector2 vector267 = proj.oldPos[num583] + new Vector2((float)proj.width, (float)proj.height) / 2f + Vector2.UnitY * proj.gfxOffY - Main.screenPosition;
                                                            Vector2 vector268 = proj.oldPos[num583 - 1] + new Vector2((float)proj.width, (float)proj.height) / 2f + Vector2.UnitY * proj.gfxOffY - Main.screenPosition;
                                                            Utils.DrawLaser(Main.spriteBatch, value59, vector267, vector268, vector266, new Utils.LaserLineFraming(DelegateMethods.LightningLaserDraw));
                                                        }
                                                    }
                                                    if (proj.oldPos[0] != Vector2.Zero)
{
                                                        DelegateMethods.f_1 = 1f;
                                                        Vector2 vector269 = proj.oldPos[0] + new Vector2((float)proj.width, (float)proj.height) / 2f + Vector2.UnitY * proj.gfxOffY - Main.screenPosition;
                                                        Utils.DrawLaser(Main.spriteBatch, value59, vector269, vector265, vector266, new Utils.LaserLineFraming(DelegateMethods.LightningLaserDraw));
                                                    }
                                                }
                                                return;
                                            }
                                            if (proj.type == 445)
{
                                                if (player.gravDir == -1f)
{
                                                    spriteEffects2 |= SpriteEffects.FlipVertically;
                                                }
                                                Vector2 vector270 = proj.position + new Vector2((float)proj.width, (float)proj.height) / 2f + Vector2.UnitY * proj.gfxOffY - Main.screenPosition;
                                                Texture2D value60 = TextureAssets.Projectile[proj.type].Value;
                                                Microsoft.Xna.Framework.Color alpha8 = proj.GetAlpha(color36);
                                                Vector2 vector271 = player.RotatedRelativePoint(vector, false, true) + Vector2.UnitY * player.gfxOffY;
                                                Vector2 vector272 = vector270 + Main.screenPosition - vector271;
                                                Vector2 vector273 = Vector2.Normalize(vector272);
                                                float num584 = vector272.Length();
                                                float num585 = vector272.ToRotation() + 1.5707964f;
                                                float num586 = -5f;
                                                float num587 = num586 + 30f;
                                                new Vector2(2f, num584 - num587);
                                                Vector2 vector274 = Vector2.Lerp(vector270 + Main.screenPosition, vector271 + vector273 * num587, 0.5f);
                                                Vector2 unitY7 = Vector2.UnitY;
                                                double num588 = (double)(proj.localAI[0] / 60f * 3.1415927f);
                                                Vector2 vector49 = default(Vector2);
                                                Vector2 vector275 = -unitY7.RotatedBy(num588, vector49);
                                                Vector2[] array7 = new Vector2[4];
                                                array7[0] = vector275;
                                                int num589 = 1;
                                                Vector2 vector276 = vector275;
                                                double num590 = 1.5707963705062866;
                                                vector49 = default(Vector2);
                                                array7[num589] = vector276.RotatedBy(num590, vector49);
                                                int num591 = 2;
                                                Vector2 vector277 = vector275;
                                                double num592 = 3.1415927410125732;
                                                vector49 = default(Vector2);
                                                array7[num591] = vector277.RotatedBy(num592, vector49);
                                                int num593 = 3;
                                                Vector2 vector278 = vector275;
                                                double num594 = 4.71238899230957;
                                                vector49 = default(Vector2);
                                                array7[num593] = vector278.RotatedBy(num594, vector49);
                                                Vector2[] array8 = array7;
                                                if (num584 > num587)
{
                                                    for (int num595 = 0; num595 < 2; num595++)
{
                                                        Microsoft.Xna.Framework.Color color151 = Microsoft.Xna.Framework.Color.White;
                                                        if (num595 % 2 == 0)
{
                                                            color151 = Microsoft.Xna.Framework.Color.LimeGreen;
                                                            color151.A = 128;
                                                            color151 *= 0.5f;
                                                        }
                                                        else
{
                                                            color151 = Microsoft.Xna.Framework.Color.CornflowerBlue;
                                                            color151.A = 128;
                                                            color151 *= 0.5f;
                                                        }
                                                        Vector2 vector279 = new Vector2(array8[num595].X, 0f);
                                                        double num596 = (double)num585;
                                                        vector49 = default(Vector2);
                                                        Vector2 vector280 = vector279.RotatedBy(num596, vector49) * 4f;
                                                        Main.EntitySpriteDraw(TextureAssets.MagicPixel.Value, vector274 - Main.screenPosition + vector280, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, 1, 1)), color151, num585, Vector2.One / 2f, new Vector2(2f, num584 - num587), spriteEffects2, 0f);
                                                    }
                                                }
                                                int type2 = player.inventory[player.selectedItem].type;
                                                Main.instance.LoadItem(type2);
                                                Texture2D value61 = TextureAssets.Item[type2].Value;
                                                Microsoft.Xna.Framework.Color color152 = Lighting.GetColor((int)vector271.X / 16, (int)vector271.Y / 16);
                                                Main.EntitySpriteDraw(value61, vector271 - Main.screenPosition + vector273 * num586, null, color152, proj.rotation + 1.5707964f + ((spriteEffects2 == SpriteEffects.None || spriteEffects2 == SpriteEffects.FlipVertically) ? 3.1415927f : 0f), new Vector2((float)((spriteEffects2 == SpriteEffects.None || spriteEffects2 == SpriteEffects.FlipVertically) ? 0 : value61.Width), (float)value61.Height / 2f) + Vector2.UnitY * 1f, player.inventory[player.selectedItem].scale, spriteEffects2, 0f);
                                                Main.EntitySpriteDraw(TextureAssets.GlowMask[39].Value, vector271 - Main.screenPosition + vector273 * num586, null, new Microsoft.Xna.Framework.Color(255, 255, 255, 0), proj.rotation + 1.5707964f + ((spriteEffects2 == SpriteEffects.None || spriteEffects2 == SpriteEffects.FlipVertically) ? 3.1415927f : 0f), new Vector2((float)((spriteEffects2 == SpriteEffects.None || spriteEffects2 == SpriteEffects.FlipVertically) ? 0 : value61.Width), (float)value61.Height / 2f) + Vector2.UnitY * 1f, player.inventory[player.selectedItem].scale, spriteEffects2, 0f);
                                                if (num584 > num587)
{
                                                    for (int num597 = 2; num597 < 4; num597++)
{
                                                        Microsoft.Xna.Framework.Color color153 = Microsoft.Xna.Framework.Color.White;
                                                        if (num597 % 2 == 0)
{
                                                            color153 = Microsoft.Xna.Framework.Color.LimeGreen;
                                                            color153.A = 128;
                                                            color153 *= 0.5f;
                                                        }
                                                        else
{
                                                            color153 = Microsoft.Xna.Framework.Color.CornflowerBlue;
                                                            color153.A = 128;
                                                            color153 *= 0.5f;
                                                        }
                                                        Vector2 vector281 = new Vector2(array8[num597].X, 0f);
                                                        double num598 = (double)num585;
                                                        vector49 = default(Vector2);
                                                        Vector2 vector282 = vector281.RotatedBy(num598, vector49) * 4f;
                                                        Main.EntitySpriteDraw(TextureAssets.MagicPixel.Value, vector274 - Main.screenPosition + vector282, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, 1, 1)), color153, num585, Vector2.One / 2f, new Vector2(2f, num584 - num587), spriteEffects2, 0f);
                                                    }
                                                }
                                                float num599 = proj.localAI[0] / 60f;
                                                if (num599 > 0.5f)
{
                                                    num599 = 1f - num599;
                                                }
                                                Main.EntitySpriteDraw(value60, vector270, null, alpha8 * num599 * 2f, proj.rotation, new Vector2((float)value60.Width, (float)value60.Height) / 2f, proj.scale, spriteEffects2, 0f);
                                                Main.EntitySpriteDraw(TextureAssets.GlowMask[40].Value, vector270, null, alpha8 * (0.5f - num599) * 2f, proj.rotation, new Vector2((float)value60.Width, (float)value60.Height) / 2f, proj.scale, spriteEffects2, 0f);
                                                return;
                                            }
                                            if ((proj.type >= 393 && proj.type <= 395) || proj.type == 398 || proj.type == 423 || proj.type == 1022 || proj.type == 1036 || proj.type == 450 || proj.type == 1093)
{
                                                Texture2D texture2D35 = TextureAssets.Projectile[proj.type].Value;
                                                int num600 = TextureAssets.Projectile[proj.type].Height() / Main.projFrames[proj.type];
                                                int num601 = num600 * proj.frame;
                                                int num602 = 2;
                                                if (proj.type == 1093)
{
                                                    num602 = 5;
                                                }
                                                Main.EntitySpriteDraw(texture2D35, proj.Center - Main.screenPosition + new Vector2(0f, proj.gfxOffY - (float)num602), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, num601, texture2D35.Width, num600)), proj.GetAlpha(color36), proj.rotation, new Vector2((float)texture2D35.Width / 2f, (float)num600 / 2f + (float)num189), proj.scale, spriteEffects2, 0f);
                                                if (proj.type == 423)
{
                                                    texture2D35 = TextureAssets.GlowMask[0].Value;
                                                    Main.EntitySpriteDraw(texture2D35, proj.Center - Main.screenPosition + new Vector2(0f, proj.gfxOffY - (float)num602), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, num601, texture2D35.Width, num600)), new Microsoft.Xna.Framework.Color(250, 250, 250, proj.alpha), proj.rotation, new Vector2((float)texture2D35.Width / 2f, (float)num600 / 2f + (float)num189), proj.scale, spriteEffects2, 0f);
                                                }
                                                if (proj.type == 1022)
{
                                                    texture2D35 = TextureAssets.GlowMask[354].Value;
                                                    Main.EntitySpriteDraw(texture2D35, proj.Center - Main.screenPosition + new Vector2(0f, proj.gfxOffY - (float)num602), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, num601, texture2D35.Width, num600)), new Microsoft.Xna.Framework.Color(250, 250, 250, proj.alpha), proj.rotation, new Vector2((float)texture2D35.Width / 2f, (float)num600 / 2f + (float)num189), proj.scale, spriteEffects2, 0f);
                                                }
                                                if (proj.type == 1093)
{
                                                    Main.TryPetting(proj, 5663);
                                                    int num603 = 60;
                                                    int num604 = ((player.petting.isPetting && player.petting.proj == proj.whoAmI) ? 0 : 3);
                                                    if (proj.localAI[0] < (float)num603 && proj.localAI[0] > 1f)
{
                                                        if (num604 == 0)
{
                                                            EmoteBubble.DrawTemporaryBubble(Main.spriteBatch, num604, num603, (int)proj.localAI[0], proj);
                                                        }
                                                        else
{
                                                            Utils.DrawNotificationIcon(Main.spriteBatch, Utils.CenteredRectangle(proj.Center + new Vector2(8f, -14f), Vector2.Zero), 0f, true);
                                                        }
                                                    }
                                                    if (proj.alpha > 0)
{
                                                        Microsoft.Xna.Framework.Color color154 = new Microsoft.Xna.Framework.Color(255, 255, 255, 127);
                                                        color154 = Microsoft.Xna.Framework.Color.Lerp(color154, new Microsoft.Xna.Framework.Color(100, 210, 255, 127), Utils.Remap(proj.Opacity, 0f, 0.7f, 0f, 1f, true));
                                                        color154 *= Utils.Remap(proj.Opacity, 0f, 0.7f, 0f, 1f, true) * Utils.Remap(proj.Opacity, 0.7f, 1f, 1f, 0f, true);
                                                        Main.EntitySpriteDraw(texture2D35, proj.Center - Main.screenPosition + new Vector2(0f, proj.gfxOffY - (float)num602), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, num601 + 13 * num600, texture2D35.Width, num600)), color154, proj.rotation, new Vector2((float)texture2D35.Width / 2f, (float)num600 / 2f + (float)num189), proj.scale, spriteEffects2, 0f);
                                                    }
                                                    int head = player.head;
                                                    if (head == 12)
{
                                                        this.LoadArmorHead(head);
                                                        Texture2D value62 = TextureAssets.ArmorHead[head].Value;
                                                        Microsoft.Xna.Framework.Rectangle rectangle50 = value62.Frame(1, 21, 0, 0, 0, 0);
                                                        int num605 = 4;
                                                        int num606 = -4;
                                                        if (proj.spriteDirection == 1)
{
                                                            num605 = -2;
                                                        }
                                                        int num607 = 0;
                                                        if (proj.frame == 7 || proj.frame == 11 || proj.frame == 12)
{
                                                            num607--;
                                                        }
                                                        if (proj.frame == 4 || proj.frame == 3)
{
                                                            num607++;
                                                        }
                                                        if (proj.frame == 2)
{
                                                            num606 -= 2;
                                                        }
                                                        num605 += num607 * 2;
                                                        Main.EntitySpriteDraw(value62, proj.Center - Main.screenPosition + new Vector2(0f, proj.gfxOffY - (float)num602) + new Vector2((float)(num605 * proj.spriteDirection), (float)num606), new Microsoft.Xna.Framework.Rectangle?(rectangle50), proj.GetAlpha(color36), proj.rotation, new Vector2((float)texture2D35.Width / 2f, (float)num600 / 2f + (float)num189), proj.scale, spriteEffects2, 0f);
                                                        Main.EntitySpriteDraw(value62, proj.Center - Main.screenPosition + new Vector2(0f, proj.gfxOffY - (float)num602) + new Vector2((float)((num605 - 6) * proj.spriteDirection), (float)num606), new Microsoft.Xna.Framework.Rectangle?(rectangle50), proj.GetAlpha(color36), proj.rotation, new Vector2((float)texture2D35.Width / 2f, (float)num600 / 2f + (float)num189), proj.scale, spriteEffects2, 0f);
                                                        return;
                                                    }
                                                }
                                            }
                                            else
{
                                                if (proj.type == 385)
{
                                                    Texture2D value63 = TextureAssets.Projectile[proj.type].Value;
                                                    int num608 = value63.Height / Main.projFrames[proj.type];
                                                    int num609 = num608 * proj.frame;
                                                    int num610 = 8;
                                                    int num611 = 2;
                                                    float num612 = 0.4f;
                                                    for (int num613 = 1; num613 < num610; num613 += num611)
{
                                                        Vector2[] oldPos3 = proj.oldPos;
                                                        Microsoft.Xna.Framework.Color color155 = color36;
                                                        color155 = proj.GetAlpha(color155);
                                                        color155 *= (float)(num610 - num613) / 15f;
                                                        Microsoft.Xna.Framework.Color alpha9 = proj.GetAlpha(color36);
                                                        proj.oldPos[num613] - Main.screenPosition + new Vector2(num191 + (float)num190, (float)(proj.height / 2) + proj.gfxOffY);
                                                        Main.EntitySpriteDraw(value63, proj.oldPos[num613] + new Vector2((float)proj.width, (float)proj.height) / 2f - Main.screenPosition + new Vector2(0f, proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, num609, value63.Width, num608)), Microsoft.Xna.Framework.Color.Lerp(alpha9, color155, 0.3f), proj.rotation, new Vector2((float)value63.Width / 2f, (float)num608 / 2f), MathHelper.Lerp(proj.scale, num612, (float)num613 / 15f), spriteEffects2, 0f);
                                                    }
                                                    Main.EntitySpriteDraw(value63, proj.Center - Main.screenPosition + new Vector2(0f, proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, num609, value63.Width, num608)), proj.GetAlpha(color36), proj.rotation, new Vector2((float)value63.Width / 2f, (float)num608 / 2f), proj.scale, spriteEffects2, 0f);
                                                    return;
                                                }
                                                if (proj.type == 388)
{
                                                    Texture2D value64 = TextureAssets.Projectile[proj.type].Value;
                                                    int num614 = value64.Height / Main.projFrames[proj.type];
                                                    int num615 = num614 * proj.frame;
                                                    int num616;
                                                    int num617;
                                                    if (proj.ai[0] == 2f)
{
                                                        num616 = 10;
                                                        num617 = 1;
                                                    }
                                                    else
{
                                                        num616 = 3;
                                                        num617 = 1;
                                                    }
                                                    for (int num618 = 1; num618 < num616; num618 += num617)
{
                                                        Vector2[] oldPos4 = proj.oldPos;
                                                        Microsoft.Xna.Framework.Color color156 = color36;
                                                        color156 = proj.GetAlpha(color156);
                                                        color156 *= (float)(num616 - num618) / 15f;
                                                        Vector2 vector283 = proj.oldPos[num618] - Main.screenPosition + new Vector2(num191 + (float)num190, (float)(proj.height / 2) + proj.gfxOffY);
                                                        Main.EntitySpriteDraw(value64, vector283, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, num615, value64.Width, num614)), color156, proj.rotation, new Vector2(num191, (float)(proj.height / 2 + num189)), proj.scale, spriteEffects2, 0f);
                                                    }
                                                    Main.EntitySpriteDraw(value64, proj.position - Main.screenPosition + new Vector2(num191 + (float)num190, (float)(proj.height / 2) + proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, num615, value64.Width, num614)), proj.GetAlpha(color36), proj.rotation, new Vector2(num191, (float)(proj.height / 2 + num189)), proj.scale, spriteEffects2, 0f);
                                                    return;
                                                }
                                                if (Main.projFrames[proj.type] > 1)
{
                                                    int num619 = TextureAssets.Projectile[proj.type].Height() / Main.projFrames[proj.type];
                                                    int num620 = num619 * proj.frame;
                                                    if (proj.type == 1025)
{
                                                        float num621 = 0f;
                                                        Microsoft.Xna.Framework.Color alpha10 = proj.GetAlpha(color36);
                                                        if (proj.ai[0] == 0f)
{
                                                            float num622 = (float)Main.LocalPlayer.miscCounter % 75f / 75f;
                                                            float num623 = (float)Main.LocalPlayer.miscCounter % 100f / 100f;
                                                            num621 += (float)Math.Sin((double)(num623 * 6.2831855f)) * 2f;
                                                            Main.instance.LoadNPC(594);
                                                            Texture2D value65 = TextureAssets.Npc[594].Value;
                                                            Vector2 vector284 = new Vector2(0f, -10f);
                                                            Vector2 vector285 = proj.Center + new Vector2(0f, proj.gfxOffY + num621) + vector284 - Main.screenPosition;
                                                            for (int num624 = 0; num624 < 3; num624++)
{
                                                                int num625 = ((num624 == 0) ? 1 : ((num624 == 1) ? 4 : 6));
                                                                Microsoft.Xna.Framework.Rectangle rectangle51 = value65.Frame(8, 1, 1 + num625, 0, 0, 0);
                                                                Vector2 vector286 = new Vector2((float)rectangle51.Width / 2f, (float)rectangle51.Height + (float)(num189 - 22));
                                                                float num626 = ((num624 == 0) ? 0.34906587f : ((num624 == 1) ? 0f : (-0.34906587f)));
                                                                float num627 = ((num624 == 1) ? ((float)Math.Sin((double)(num622 * 6.2831855f))) : ((float)Math.Cos((double)(num622 * 6.2831855f))));
                                                                num627 *= 0.025f;
                                                                num626 += num627;
                                                                Main.EntitySpriteDraw(value65, vector285, new Microsoft.Xna.Framework.Rectangle?(rectangle51), alpha10, num626, vector286, proj.scale, spriteEffects2, 0f);
                                                            }
                                                        }
                                                        Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - Main.screenPosition.X + num191 + (float)num190, proj.position.Y - Main.screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY + num621), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, num620, TextureAssets.Projectile[proj.type].Width(), num619 - 1)), alpha10, proj.rotation, new Vector2(num191, (float)(proj.height / 2 + num189)), proj.scale, spriteEffects2, 0f);
                                                        return;
                                                    }
                                                    if (proj.type == 111)
{
                                                        int r = (int)player.shirtColor.R;
                                                        int g = (int)player.shirtColor.G;
                                                        int b2 = (int)player.shirtColor.B;
                                                        Microsoft.Xna.Framework.Color color157 = new Microsoft.Xna.Framework.Color((int)((byte)r), (int)((byte)g), (int)((byte)b2));
                                                        color36 = Lighting.GetColor((int)((double)proj.position.X + (double)proj.width * 0.5) / 16, (int)(((double)proj.position.Y + (double)proj.height * 0.5) / 16.0), color157);
                                                        Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - Main.screenPosition.X + num191 + (float)num190, proj.position.Y - Main.screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, num620, TextureAssets.Projectile[proj.type].Width(), num619)), proj.GetAlpha(color36), proj.rotation, new Vector2(num191, (float)(proj.height / 2 + num189)), proj.scale, spriteEffects2, 0f);
                                                        return;
                                                    }
                                                    Microsoft.Xna.Framework.Color alpha11 = proj.GetAlpha(color36);
                                                    if (proj.type == 211 && Main.CurrentDrawnEntityShader != 0)
{
                                                        alpha11.A = 127;
                                                    }
                                                    if (proj.type == 344)
{
                                                        float num628 = MathHelper.Min(60f, proj.ai[0]) / 2f;
                                                        for (float num629 = 0.9f; num629 > 0f; num629 -= 0.25f)
{
                                                            Vector2 vector287 = num629 * (proj.velocity * 0.33f) * num628;
                                                            Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - Main.screenPosition.X + num191 + (float)num190, proj.position.Y - Main.screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY) - vector287, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, num620, TextureAssets.Projectile[proj.type].Width(), num619 - 1)), alpha11 * (1f - num629) * 0.75f, proj.rotation, new Vector2(num191, (float)(proj.height / 2 + num189)), proj.scale * (0.4f + (1f - num629) * 0.6f), spriteEffects2, 0f);
                                                        }
                                                    }
                                                    if (proj.type == 920 || proj.type == 921)
{
                                                        for (float num630 = 0.25f; num630 < 1f; num630 += 0.5f)
{
                                                            Vector2 vector288 = num630 * proj.velocity * 4f;
                                                            Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - Main.screenPosition.X + num191 + (float)num190, proj.position.Y - Main.screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY) - vector288, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, num620, TextureAssets.Projectile[proj.type].Width(), num619 - 1)), alpha11 * (1f - num630) * 0.75f, proj.rotation, new Vector2(num191, (float)(proj.height / 2 + num189)), proj.scale, spriteEffects2, 0f);
                                                        }
                                                    }
                                                    Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - Main.screenPosition.X + num191 + (float)num190, proj.position.Y - Main.screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, num620, TextureAssets.Projectile[proj.type].Width(), num619 - 1)), alpha11, proj.rotation, new Vector2(num191, (float)(proj.height / 2 + num189)), proj.scale, spriteEffects2, 0f);
                                                    if (proj.type == 966)
{
                                                        Vector2 vector289 = new Vector2(0f, -30f);
                                                        vector289.Y += -1f + (float)(Math.Cos((double)((float)Main.mouseTextColor / 255f * 6.2831855f * 2f)) * 2.0);
                                                        Vector2 vector290 = new Vector2(-1f, -1f);
                                                        float num631 = 3f;
                                                        Vector2 vector291 = proj.Center + vector289;
                                                        Vector2 vector292 = proj.Center;
                                                        int num632 = (int)proj.ai[1];
                                                        if (num632 >= 0)
{
                                                            if (Main.npc[num632].active)
{
                                                                vector292 = Main.npc[num632].Center;
                                                            }
                                                            else
{
                                                                num632 = -1;
                                                            }
                                                        }
                                                        if (num632 <= -1)
{
                                                            Player player6 = player;
                                                            if (player6.dead)
{
                                                                vector292 = vector291 + new Vector2(2f, 0f);
                                                            }
                                                            else
{
                                                                vector292 = player6.Center;
                                                            }
                                                        }
                                                        vector290 += (vector292 - vector291).SafeNormalize(Vector2.Zero) * num631;
                                                        Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - Main.screenPosition.X + num191 + (float)num190, proj.position.Y - Main.screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY) + vector289, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, num619, TextureAssets.Projectile[proj.type].Width(), num619 - 1)), alpha11, proj.rotation, new Vector2(num191, (float)(proj.height / 2 + num189)), proj.scale, spriteEffects2, 0f);
                                                        Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - Main.screenPosition.X + num191 + (float)num190, proj.position.Y - Main.screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY) + vector289 + vector290, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, num619 * 2, TextureAssets.Projectile[proj.type].Width(), num619 - 1)), alpha11, proj.rotation, new Vector2(num191, (float)(proj.height / 2 + num189)), proj.scale, spriteEffects2, 0f);
                                                    }
                                                    if (proj.type == 335)
{
                                                        Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - Main.screenPosition.X + num191 + (float)num190, proj.position.Y - Main.screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, num620, TextureAssets.Projectile[proj.type].Width(), num619 - 1)), new Microsoft.Xna.Framework.Color(100, 100, 100, 0), proj.rotation, new Vector2(num191, (float)(proj.height / 2 + num189)), proj.scale, spriteEffects2, 0f);
                                                    }
                                                    if (proj.type == 897 || proj.type == 899)
{
                                                        int num633 = 279;
                                                        if (proj.type == 899)
{
                                                            num633 = 281;
                                                        }
                                                        Main.EntitySpriteDraw(TextureAssets.GlowMask[num633].Value, new Vector2(proj.position.X - Main.screenPosition.X + num191 + (float)num190, proj.position.Y - Main.screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, num620, TextureAssets.Projectile[proj.type].Width(), num619 - 1)), Microsoft.Xna.Framework.Color.White, proj.rotation, new Vector2(num191, (float)(proj.height / 2 + num189)), proj.scale, spriteEffects2, 0f);
                                                    }
                                                    if (proj.type == 891)
{
                                                        float num634 = Utils.WrappedLerp(0.6f, 1f, (float)((int)Main.timeForVisualEffects % 100) / 100f);
                                                        Microsoft.Xna.Framework.Color color158 = new Microsoft.Xna.Framework.Color(num634, num634, num634, 150f);
                                                        Main.EntitySpriteDraw(TextureAssets.GlowMask[277].Value, new Vector2(proj.position.X - Main.screenPosition.X + num191 + (float)num190, proj.position.Y - Main.screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, num620, TextureAssets.Projectile[proj.type].Width(), num619 - 1)), color158, proj.rotation, new Vector2(num191, (float)(proj.height / 2 + num189)), proj.scale, spriteEffects2, 0f);
                                                    }
                                                    if (proj.type == 595)
{
                                                        Player player7 = player;
                                                        if (player7.active && player7.body == 208)
{
                                                            for (float num635 = 0f; num635 <= 1f; num635 += 0.2f)
{
                                                                Microsoft.Xna.Framework.Color underShirtColor = player7.underShirtColor;
                                                                underShirtColor.A = (byte)(120f * (1f - num635 * 0.5f));
                                                                Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - Main.screenPosition.X + num191 + (float)num190, proj.position.Y - Main.screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, num620, TextureAssets.Projectile[proj.type].Width(), num619 - 1)), underShirtColor, proj.rotation, new Vector2(num191, (float)(proj.height / 2 + num189)), proj.scale * MathHelper.Lerp(0.8f, 1.3f, num635), spriteEffects2, 0f);
                                                            }
                                                        }
                                                    }
                                                    if (proj.type == 387)
{
                                                        Main.EntitySpriteDraw(TextureAssets.EyeLaserSmall.Value, new Vector2(proj.position.X - Main.screenPosition.X + num191 + (float)num190, proj.position.Y - Main.screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, num620, TextureAssets.Projectile[proj.type].Width(), num619)), new Microsoft.Xna.Framework.Color(255, 255, 255, 0), proj.rotation, new Vector2(num191, (float)(proj.height / 2 + num189)), proj.scale, spriteEffects2, 0f);
                                                    }
                                                    if (proj.type == 525 || proj.type == 960)
{
                                                        int num636 = Main.TryInteractingWithMoneyTrough(proj);
                                                        if (num636 != 0)
{
                                                            int num637 = (int)((color36.R + color36.G + color36.B) / 3);
                                                            if (num637 > 10)
{
                                                                int num638 = 94;
                                                                if (proj.type == 960)
{
                                                                    num638 = 244;
                                                                }
                                                                Microsoft.Xna.Framework.Color selectionGlowColor = Colors.GetSelectionGlowColor(num636 == 2, num637);
                                                                Main.EntitySpriteDraw(TextureAssets.Extra[num638].Value, new Vector2(proj.position.X - Main.screenPosition.X + num191 + (float)num190, proj.position.Y - Main.screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, num620, TextureAssets.Projectile[proj.type].Width(), num619 - 1)), selectionGlowColor, proj.rotation, new Vector2(num191, (float)(proj.height / 2 + num189)), 1f, spriteEffects2, 0f);
                                                                return;
                                                            }
                                                        }
                                                    }
                                                }
                                                else
{
                                                    if (proj.type == 383 || proj.type == 399)
{
                                                        Texture2D value66 = TextureAssets.Projectile[proj.type].Value;
                                                        Main.EntitySpriteDraw(value66, proj.Center - Main.screenPosition, null, proj.GetAlpha(color36), proj.rotation, new Vector2((float)value66.Width, (float)value66.Height) / 2f, proj.scale, spriteEffects2, 0f);
                                                        return;
                                                    }
                                                    if (proj.type == 157 || proj.type == 378)
{
                                                        Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - Main.screenPosition.X + (float)(proj.width / 2), proj.position.Y - Main.screenPosition.Y + (float)(proj.height / 2)), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Projectile[proj.type].Width(), TextureAssets.Projectile[proj.type].Height())), proj.GetAlpha(color36), proj.rotation, new Vector2((float)(TextureAssets.Projectile[proj.type].Width() / 2), (float)(TextureAssets.Projectile[proj.type].Height() / 2)), proj.scale, spriteEffects2, 0f);
                                                        return;
                                                    }
                                                    if (proj.type == 306)
{
                                                        Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - Main.screenPosition.X + (float)(proj.width / 2), proj.position.Y - Main.screenPosition.Y + (float)(proj.height / 2)), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Projectile[proj.type].Width(), TextureAssets.Projectile[proj.type].Height())), proj.GetAlpha(color36), proj.rotation, new Vector2((float)(TextureAssets.Projectile[proj.type].Width() / 2), (float)(TextureAssets.Projectile[proj.type].Height() / 2)), proj.scale, spriteEffects2, 0f);
                                                        return;
                                                    }
                                                    if (proj.type == 256)
{
                                                        Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - Main.screenPosition.X + (float)(proj.width / 2), proj.position.Y - Main.screenPosition.Y + (float)(proj.height / 2)), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Projectile[proj.type].Width(), TextureAssets.Projectile[proj.type].Height())), proj.GetAlpha(color36), proj.rotation, new Vector2((float)(TextureAssets.Projectile[proj.type].Width() / 2), (float)(TextureAssets.Projectile[proj.type].Height() / 2)), proj.scale, spriteEffects2, 0f);
                                                        return;
                                                    }
                                                    if (proj.aiStyle == 27)
{
                                                        Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - Main.screenPosition.X + (float)(proj.width / 2), proj.position.Y - Main.screenPosition.Y + (float)(proj.height / 2)), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Projectile[proj.type].Width(), TextureAssets.Projectile[proj.type].Height())), proj.GetAlpha(color36), proj.rotation, new Vector2((float)TextureAssets.Projectile[proj.type].Width(), 0f), proj.scale, spriteEffects2, 0f);
                                                        return;
                                                    }
                                                    if (proj.aiStyle == 19)
{
                                                        Main.DrawProj_Spear(proj, player, ref color36, ref spriteEffects2);
                                                        return;
                                                    }
                                                    if (proj.type == 451)
{
                                                        Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, proj.Center - Main.screenPosition, null, proj.GetAlpha(color36), proj.rotation, new Vector2((float)TextureAssets.Projectile[proj.type].Width(), 0f), proj.scale, spriteEffects2, 0f);
                                                        return;
                                                    }
                                                    if (proj.type == 434)
{
                                                        Vector2 vector293 = new Vector2(proj.ai[0], proj.ai[1]);
                                                        Vector2 vector294 = proj.position - vector293;
                                                        float num639 = (float)Math.Sqrt((double)(vector294.X * vector294.X + vector294.Y * vector294.Y));
                                                        new Vector2(4f, num639);
                                                        float num640 = vector294.ToRotation() + 1.5707964f;
                                                        Vector2 vector295 = Vector2.Lerp(proj.position, vector293, 0.5f);
                                                        Microsoft.Xna.Framework.Color color159 = Microsoft.Xna.Framework.Color.Red;
                                                        color159.A = 0;
                                                        Microsoft.Xna.Framework.Color color160 = Microsoft.Xna.Framework.Color.White;
                                                        color159 *= proj.localAI[0];
                                                        color160 *= proj.localAI[0];
                                                        float num641 = (float)Math.Sqrt((double)(proj.damage / 50));
                                                        Main.EntitySpriteDraw(TextureAssets.MagicPixel.Value, vector295 - Main.screenPosition, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, 1, 1)), color159, num640, Vector2.One / 2f, new Vector2(2f * num641, num639 + 8f), spriteEffects2, 0f);
                                                        Main.EntitySpriteDraw(TextureAssets.MagicPixel.Value, vector295 - Main.screenPosition, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, 1, 1)), color159, num640, Vector2.One / 2f, new Vector2(4f * num641, num639), spriteEffects2, 0f);
                                                        Main.EntitySpriteDraw(TextureAssets.MagicPixel.Value, vector295 - Main.screenPosition, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, 1, 1)), color160, num640, Vector2.One / 2f, new Vector2(2f * num641, num639), spriteEffects2, 0f);
                                                        return;
                                                    }
                                                    if (proj.type == 94 && proj.ai[1] > 6f)
{
                                                        for (int num642 = 0; num642 < 10; num642++)
{
                                                            Microsoft.Xna.Framework.Color alpha12 = proj.GetAlpha(color36);
                                                            float num643 = (float)(9 - num642) / 9f;
                                                            alpha12.R = (byte)((float)alpha12.R * num643);
                                                            alpha12.G = (byte)((float)alpha12.G * num643);
                                                            alpha12.B = (byte)((float)alpha12.B * num643);
                                                            alpha12.A = (byte)((float)alpha12.A * num643);
                                                            float num644 = (float)(9 - num642) / 9f;
                                                            Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.oldPos[num642].X - Main.screenPosition.X + num191 + (float)num190, proj.oldPos[num642].Y - Main.screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Projectile[proj.type].Width(), TextureAssets.Projectile[proj.type].Height())), alpha12, proj.rotation, new Vector2(num191, (float)(proj.height / 2 + num189)), num644 * proj.scale, spriteEffects2, 0f);
                                                        }
                                                    }
                                                    if (proj.type == 301)
{
                                                        for (int num645 = 0; num645 < 10; num645++)
{
                                                            Microsoft.Xna.Framework.Color alpha13 = proj.GetAlpha(color36);
                                                            float num646 = (float)(9 - num645) / 9f;
                                                            alpha13.R = (byte)((float)alpha13.R * num646);
                                                            alpha13.G = (byte)((float)alpha13.G * num646);
                                                            alpha13.B = (byte)((float)alpha13.B * num646);
                                                            alpha13.A = (byte)((float)alpha13.A * num646);
                                                            float num647 = (float)(9 - num645) / 9f;
                                                            Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.oldPos[num645].X - Main.screenPosition.X + num191 + (float)num190, proj.oldPos[num645].Y - Main.screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Projectile[proj.type].Width(), TextureAssets.Projectile[proj.type].Height())), alpha13, proj.rotation, new Vector2(num191, (float)(proj.height / 2 + num189)), num647 * proj.scale, spriteEffects2, 0f);
                                                        }
                                                    }
                                                    if (proj.type == 323 && proj.alpha == 0)
{
                                                        for (int num648 = 1; num648 < 8; num648++)
{
                                                            float num649 = proj.velocity.X * (float)num648;
                                                            float num650 = proj.velocity.Y * (float)num648;
                                                            Microsoft.Xna.Framework.Color alpha14 = proj.GetAlpha(color36);
                                                            float num651 = 0f;
                                                            if (num648 == 1)
{
                                                                num651 = 0.7f;
                                                            }
                                                            if (num648 == 2)
{
                                                                num651 = 0.6f;
                                                            }
                                                            if (num648 == 3)
{
                                                                num651 = 0.5f;
                                                            }
                                                            if (num648 == 4)
{
                                                                num651 = 0.4f;
                                                            }
                                                            if (num648 == 5)
{
                                                                num651 = 0.3f;
                                                            }
                                                            if (num648 == 6)
{
                                                                num651 = 0.2f;
                                                            }
                                                            if (num648 == 7)
{
                                                                num651 = 0.1f;
                                                            }
                                                            alpha14.R = (byte)((float)alpha14.R * num651);
                                                            alpha14.G = (byte)((float)alpha14.G * num651);
                                                            alpha14.B = (byte)((float)alpha14.B * num651);
                                                            alpha14.A = (byte)((float)alpha14.A * num651);
                                                            Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - Main.screenPosition.X + num191 + (float)num190 - num649, proj.position.Y - Main.screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY - num650), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Projectile[proj.type].Width(), TextureAssets.Projectile[proj.type].Height())), alpha14, proj.rotation, new Vector2(num191, (float)(proj.height / 2 + num189)), num651 + 0.2f, spriteEffects2, 0f);
                                                        }
                                                    }
                                                    if (proj.type == 117 && proj.ai[0] > 3f)
{
                                                        for (int num652 = 1; num652 < 5; num652++)
{
                                                            float num653 = proj.velocity.X * (float)num652;
                                                            float num654 = proj.velocity.Y * (float)num652;
                                                            Microsoft.Xna.Framework.Color alpha15 = proj.GetAlpha(color36);
                                                            float num655 = 0f;
                                                            if (num652 == 1)
{
                                                                num655 = 0.4f;
                                                            }
                                                            if (num652 == 2)
{
                                                                num655 = 0.3f;
                                                            }
                                                            if (num652 == 3)
{
                                                                num655 = 0.2f;
                                                            }
                                                            if (num652 == 4)
{
                                                                num655 = 0.1f;
                                                            }
                                                            alpha15.R = (byte)((float)alpha15.R * num655);
                                                            alpha15.G = (byte)((float)alpha15.G * num655);
                                                            alpha15.B = (byte)((float)alpha15.B * num655);
                                                            alpha15.A = (byte)((float)alpha15.A * num655);
                                                            Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - Main.screenPosition.X + num191 + (float)num190 - num653, proj.position.Y - Main.screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY - num654), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Projectile[proj.type].Width(), TextureAssets.Projectile[proj.type].Height())), alpha15, proj.rotation, new Vector2(num191, (float)(proj.height / 2 + num189)), proj.scale, spriteEffects2, 0f);
                                                        }
                                                    }
                                                    if (proj.bobber)
{
                                                        if (proj.ai[1] > 0f && proj.ai[1] < (float)ItemID.Count && proj.ai[0] == 1f)
{
                                                            int num656 = (int)proj.ai[1];
                                                            Vector2 center2 = proj.Center;
                                                            float num657 = proj.rotation;
                                                            Vector2 vector296 = center2;
                                                            float num658 = num2 - vector296.X;
                                                            float num659 = num3 - vector296.Y;
                                                            num657 = (float)Math.Atan2((double)num659, (double)num658);
                                                            if (proj.velocity.X > 0f)
{
                                                                spriteEffects2 = SpriteEffects.None;
                                                                num657 = (float)Math.Atan2((double)num659, (double)num658);
                                                                num657 += 0.785f;
                                                                if (proj.ai[1] == 2342f)
{
                                                                    num657 -= 0.785f;
                                                                }
                                                            }
                                                            else
{
                                                                spriteEffects2 = SpriteEffects.FlipHorizontally;
                                                                num657 = (float)Math.Atan2((double)(-(double)num659), (double)(-(double)num658));
                                                                num657 -= 0.785f;
                                                                if (proj.ai[1] == 2342f)
{
                                                                    num657 += 0.785f;
                                                                }
                                                            }
                                                            Main.instance.LoadItem(num656);
                                                            Texture2D value67 = TextureAssets.Item[num656].Value;
                                                            Microsoft.Xna.Framework.Rectangle rectangle52 = value67.Frame(1, 1, 0, 0, 0, 0);
                                                            if (ItemID.Sets.IsFood[num656] && Main.itemAnimations[num656] != null)
{
                                                                rectangle52 = Main.itemAnimations[num656].GetFrame(value67, 0);
                                                            }
                                                            Main.EntitySpriteDraw(value67, new Vector2(center2.X - Main.screenPosition.X, center2.Y - Main.screenPosition.Y), new Microsoft.Xna.Framework.Rectangle?(rectangle52), color36, num657, new Vector2((float)(rectangle52.Width / 2), (float)(rectangle52.Height / 2)), proj.scale, spriteEffects2, 0f);
                                                        }
                                                        else if (proj.ai[0] <= 1f)
{
                                                            Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - Main.screenPosition.X + num191 + (float)num190, proj.position.Y - Main.screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Projectile[proj.type].Width(), TextureAssets.Projectile[proj.type].Height())), proj.GetAlpha(color36), proj.rotation, new Vector2(num191, (float)(proj.height / 2 + num189)), proj.scale, spriteEffects2, 0f);
                                                            if (proj.glowMask != -1)
{
                                                                Texture2D value68 = TextureAssets.GlowMask[(int)proj.glowMask].Value;
                                                                Microsoft.Xna.Framework.Color white3 = Microsoft.Xna.Framework.Color.White;
                                                                if (proj.type == 993)
{
                                                                    white3 = new Microsoft.Xna.Framework.Color(Main.DiscoR, Main.DiscoG, Main.DiscoB);
                                                                }
                                                                Main.EntitySpriteDraw(value68, new Vector2(proj.position.X - Main.screenPosition.X + num191 + (float)num190, proj.position.Y - Main.screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, value68.Width, value68.Height)), proj.GetAlpha(white3), proj.rotation, new Vector2(num191, (float)(proj.height / 2 + num189)), proj.scale, spriteEffects2, 0f);
                                                            }
                                                        }
                                                    }
                                                    else
{
                                                        if (proj.ownerHitCheck && player.gravDir == -1f)
{
                                                            if (player.direction == 1)
{
                                                                spriteEffects2 = SpriteEffects.FlipHorizontally;
                                                            }
                                                            else if (player.direction == -1)
{
                                                                spriteEffects2 = SpriteEffects.None;
                                                            }
                                                        }
                                                        Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - Main.screenPosition.X + num191 + (float)num190, proj.position.Y - Main.screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Projectile[proj.type].Width(), TextureAssets.Projectile[proj.type].Height())), proj.GetAlpha(color36), proj.rotation, new Vector2(num191, (float)(proj.height / 2 + num189)), proj.scale, spriteEffects2, 0f);
                                                        if (proj.glowMask != -1)
{
                                                            Microsoft.Xna.Framework.Color color161 = new Microsoft.Xna.Framework.Color(250, 250, 250, proj.alpha);
                                                            if (proj.type == 1101 || proj.type == 1102)
{
                                                                color161 = Item.GetPhaseColor(proj.type, false);
                                                                Main.EntitySpriteDraw(TextureAssets.GlowMask[(int)proj.glowMask].Value, new Vector2(proj.position.X - Main.screenPosition.X + num191 + (float)num190, proj.position.Y - Main.screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Projectile[proj.type].Width(), TextureAssets.Projectile[proj.type].Height())), color161, proj.rotation, new Vector2(num191, (float)(proj.height / 2 + num189)), proj.scale, spriteEffects2, 0f);
                                                                color161 = Item.GetPhaseColor(proj.type, true);
                                                            }
                                                            Main.EntitySpriteDraw(TextureAssets.GlowMask[(int)proj.glowMask].Value, new Vector2(proj.position.X - Main.screenPosition.X + num191 + (float)num190, proj.position.Y - Main.screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Projectile[proj.type].Width(), TextureAssets.Projectile[proj.type].Height())), color161, proj.rotation, new Vector2(num191, (float)(proj.height / 2 + num189)), proj.scale, spriteEffects2, 0f);
                                                        }
                                                        if (proj.type == 473)
{
                                                            Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - Main.screenPosition.X + num191 + (float)num190, proj.position.Y - Main.screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Projectile[proj.type].Width(), TextureAssets.Projectile[proj.type].Height())), new Microsoft.Xna.Framework.Color(255, 255, 0, 0), proj.rotation, new Vector2(num191, (float)(proj.height / 2 + num189)), proj.scale, spriteEffects2, 0f);
                                                        }
                                                        if (proj.type >= 511 && proj.type <= 513)
{
                                                            Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - Main.screenPosition.X + num191 + (float)num190, proj.position.Y - Main.screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Projectile[proj.type].Width(), TextureAssets.Projectile[proj.type].Height())), proj.GetAlpha(color36) * 0.25f, proj.rotation, new Vector2(num191, (float)(proj.height / 2 + num189)), proj.scale * (1f + proj.Opacity * 1.75f), spriteEffects2, 0f);
                                                        }
                                                        if (proj.type == 312)
{
                                                            ulong tileFrameSeed2 = Main.TileFrameSeed;
                                                            for (int num660 = 0; num660 < 4; num660++)
{
                                                                Vector2 vector297 = new Vector2((float)Utils.RandomInt(ref tileFrameSeed2, -2, 3), (float)Utils.RandomInt(ref tileFrameSeed2, -2, 3));
                                                                Main.EntitySpriteDraw(TextureAssets.GlowMask[(int)proj.glowMask].Value, new Vector2(proj.position.X - Main.screenPosition.X + num191 + (float)num190, proj.position.Y - Main.screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY) + vector297, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Projectile[proj.type].Width(), TextureAssets.Projectile[proj.type].Height())), new Microsoft.Xna.Framework.Color(255, 255, 255, 255) * 0.2f, proj.rotation, new Vector2(num191, (float)(proj.height / 2 + num189)), proj.scale, spriteEffects2, 0f);
                                                            }
                                                        }
                                                    }
                                                    if (proj.type == 106)
{
                                                        Texture2D value69 = TextureAssets.LightDisc.Value;
                                                        Vector2 vector298 = new Vector2(proj.position.X - Main.screenPosition.X + num191 + (float)num190, proj.position.Y - Main.screenPosition.Y + (float)(proj.height / 2));
                                                        Microsoft.Xna.Framework.Rectangle rectangle53 = value69.Frame(1, 1, 0, 0, 0, 0);
                                                        Main.EntitySpriteDraw(value69, vector298, new Microsoft.Xna.Framework.Rectangle?(rectangle53), new Microsoft.Xna.Framework.Color(200, 200, 200, 0), proj.rotation, new Vector2(num191, (float)(proj.height / 2 + num189)), proj.scale, spriteEffects2, 0f);
                                                    }
                                                    if (proj.type >= 326 && proj.type <= 328)
{
                                                        ulong tileFrameSeed3 = Main.TileFrameSeed;
                                                        for (int num661 = 0; num661 < 4; num661++)
{
                                                            Vector2 vector299 = new Vector2((float)Utils.RandomInt(ref tileFrameSeed3, -2, 3), (float)Utils.RandomInt(ref tileFrameSeed3, -2, 3));
                                                            Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - Main.screenPosition.X + num191 + (float)num190, proj.position.Y - Main.screenPosition.Y + (float)(proj.height / 2)) + vector299 - proj.velocity * 0.25f * (float)num661, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Projectile[proj.type].Width(), TextureAssets.Projectile[proj.type].Height())), new Microsoft.Xna.Framework.Color(120, 120, 120, 60) * 1f, proj.rotation, new Vector2(num191, (float)(proj.height / 2 + num189)), proj.scale - (float)num661 * 0.2f, spriteEffects2, 0f);
                                                        }
                                                    }
                                                    if (proj.type == 554 || proj.type == 603)
{
                                                        for (int num662 = 1; num662 < 5; num662++)
{
                                                            float num663 = proj.velocity.X * (float)num662 * 0.5f;
                                                            float num664 = proj.velocity.Y * (float)num662 * 0.5f;
                                                            Microsoft.Xna.Framework.Color alpha16 = proj.GetAlpha(color36);
                                                            float num665 = 0f;
                                                            if (num662 == 1)
{
                                                                num665 = 0.4f;
                                                            }
                                                            if (num662 == 2)
{
                                                                num665 = 0.3f;
                                                            }
                                                            if (num662 == 3)
{
                                                                num665 = 0.2f;
                                                            }
                                                            if (num662 == 4)
{
                                                                num665 = 0.1f;
                                                            }
                                                            alpha16.R = (byte)((float)alpha16.R * num665);
                                                            alpha16.G = (byte)((float)alpha16.G * num665);
                                                            alpha16.B = (byte)((float)alpha16.B * num665);
                                                            alpha16.A = (byte)((float)alpha16.A * num665);
                                                            Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - Main.screenPosition.X + num191 + (float)num190 - num663, proj.position.Y - Main.screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY - num664), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Projectile[proj.type].Width(), TextureAssets.Projectile[proj.type].Height())), alpha16, proj.rotation, new Vector2(num191, (float)(proj.height / 2 + num189)), proj.scale, spriteEffects2, 0f);
                                                        }
                                                        return;
                                                    }
                                                    if (proj.type == 604)
{
                                                        int num666 = (int)proj.ai[1] + 1;
                                                        if (num666 > 7)
{
                                                            num666 = 7;
                                                        }
                                                        for (int num667 = 1; num667 < num666; num667++)
{
                                                            float num668 = proj.velocity.X * (float)num667 * 1.5f;
                                                            float num669 = proj.velocity.Y * (float)num667 * 1.5f;
                                                            Microsoft.Xna.Framework.Color alpha17 = proj.GetAlpha(color36);
                                                            if (num667 == 1)
{
                                                            }
                                                            if (num667 == 2)
{
                                                            }
                                                            if (num667 == 3)
{
                                                            }
                                                            if (num667 == 4)
{
                                                            }
                                                            float num670 = 0.4f - (float)num667 * 0.06f;
                                                            num670 *= 1f - (float)proj.alpha / 255f;
                                                            alpha17.R = (byte)((float)alpha17.R * num670);
                                                            alpha17.G = (byte)((float)alpha17.G * num670);
                                                            alpha17.B = (byte)((float)alpha17.B * num670);
                                                            alpha17.A = (byte)((float)alpha17.A * num670 / 2f);
                                                            float num671 = proj.scale;
                                                            num671 -= (float)num667 * 0.1f;
                                                            Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - Main.screenPosition.X + num191 + (float)num190 - num668, proj.position.Y - Main.screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY - num669), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Projectile[proj.type].Width(), TextureAssets.Projectile[proj.type].Height())), alpha17, proj.rotation, new Vector2(num191, (float)(proj.height / 2 + num189)), num671, spriteEffects2, 0f);
                                                        }
                                                        return;
                                                    }
                                                    if (proj.type == 553)
{
                                                        for (int num672 = 1; num672 < 5; num672++)
{
                                                            float num673 = proj.velocity.X * (float)num672 * 0.4f;
                                                            float num674 = proj.velocity.Y * (float)num672 * 0.4f;
                                                            Microsoft.Xna.Framework.Color alpha18 = proj.GetAlpha(color36);
                                                            float num675 = 0f;
                                                            if (num672 == 1)
{
                                                                num675 = 0.4f;
                                                            }
                                                            if (num672 == 2)
{
                                                                num675 = 0.3f;
                                                            }
                                                            if (num672 == 3)
{
                                                                num675 = 0.2f;
                                                            }
                                                            if (num672 == 4)
{
                                                                num675 = 0.1f;
                                                            }
                                                            alpha18.R = (byte)((float)alpha18.R * num675);
                                                            alpha18.G = (byte)((float)alpha18.G * num675);
                                                            alpha18.B = (byte)((float)alpha18.B * num675);
                                                            alpha18.A = (byte)((float)alpha18.A * num675);
                                                            Main.EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - Main.screenPosition.X + num191 + (float)num190 - num673, proj.position.Y - Main.screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY - num674), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Projectile[proj.type].Width(), TextureAssets.Projectile[proj.type].Height())), alpha18, proj.rotation, new Vector2(num191, (float)(proj.height / 2 + num189)), proj.scale, spriteEffects2, 0f);
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
References Terraria.Main._stardewAnimation, Terraria.Main._tempSeededRandom, Microsoft.Xna.Framework.Color.A, Microsoft.Xna.Framework.Input.A, System.Math.Abs(), Terraria.GameContent.Golf.GolfHelper.ShotStrength.AbsoluteStrength, Terraria.Mount.Active, Terraria.NPC.active, Terraria.Player.active, Terraria.Projectile.active, Terraria.Lighting.AddLight(), Terraria.Projectile.ai, Terraria.Projectile.AI_156_GetColor(), Terraria.Projectile.AI_171_GetColor(), Terraria.Projectile.AI_172_GetPelletStormInfo(), Terraria.Projectile.AI_172_GetPelletStormsCount(), Terraria.Projectile.AI_173_GetColor(), Terraria.Projectile.AI_192_GetJuminoFall(), Terraria.Projectile.AI_203_GetLightningColor(), Terraria.Projectile.aiStyle, Terraria.Projectile.alpha, Terraria.Player.ApplyItemPositionOffsetFromMount(), Terraria.GameContent.TextureAssets.ArmorHead, System.array, System.Math.Atan2(), Microsoft.Xna.Framework.Color.B, Microsoft.Xna.Framework.Color.Black, Microsoft.Xna.Framework.Color.Blue, Terraria.Projectile.bobber, Terraria.Player.body, Microsoft.Xna.Framework.Rectangle.Bottom, Terraria.Entity.Bottom, Terraria.Projectile.HallowBossPelletStormInfo.BulletsInStorm, Terraria.GameContent.Golf.GolfHelper.CalculateShotStrength(), Microsoft.Xna.Framework.Rectangle.Center, Terraria.Entity.Center, Terraria.Utils.CenteredRectangle(), Terraria.GameContent.TextureAssets.Chain, Terraria.GameContent.TextureAssets.Chain15, Terraria.GameContent.TextureAssets.Chain16, Terraria.GameContent.TextureAssets.Chain17, Terraria.GameContent.TextureAssets.Chain18, Terraria.GameContent.TextureAssets.Chain20, Terraria.GameContent.TextureAssets.Chain22, Terraria.GameContent.TextureAssets.Chain23, Terraria.GameContent.TextureAssets.Chain28, Terraria.GameContent.TextureAssets.Chain29, Terraria.GameContent.TextureAssets.Chain30, Terraria.GameContent.TextureAssets.Chain31, Terraria.GameContent.TextureAssets.Chain32, Terraria.GameContent.TextureAssets.Chain33, Terraria.GameContent.TextureAssets.Chain34, Terraria.GameContent.TextureAssets.Chain35, Terraria.GameContent.TextureAssets.Chain36, Terraria.GameContent.TextureAssets.Chain37, Terraria.GameContent.TextureAssets.Chain38, Terraria.GameContent.TextureAssets.Chain39, Terraria.GameContent.TextureAssets.Chain40, Terraria.GameContent.TextureAssets.Chain5, Terraria.GameContent.TextureAssets.Chain8, Terraria.GameContent.TextureAssets.Chain9, Terraria.GameContent.TextureAssets.Chains, Microsoft.Xna.Framework.MathHelper.Clamp(), Microsoft.Xna.Framework.Color.CornflowerBlue, System.Math.Cos(), Microsoft.Xna.Framework.Color.Crimson, Terraria.Main.CurrentDrawnEntityShader, Terraria.Player.dead, Terraria.Entity.direction, Terraria.Entity.DirectionFrom(), Terraria.Main.DiscoB, Terraria.Main.DiscoG, Terraria.Main.DiscoR, Microsoft.Xna.Framework.MathHelper.Distance(), Microsoft.Xna.Framework.Vector2.Distance(), Microsoft.Xna.Framework.Vector2.Dot(), Terraria.Graphics.EmpressBladeDrawer.Draw(), Terraria.GameContent.Animations.StardewValleyAnimation.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Main.DrawKite(), Terraria.Utils.DrawLaser(), Terraria.Utils.DrawNotificationIcon(), Terraria.GameContent.Golf.GolfHelper.DrawPredictionLine(), Terraria.Main.DrawPrettyStarSparkle(), Terraria.Main.DrawProj_FishingLine(), Terraria.Main.DrawProj_FlailChains(), Terraria.Main.DrawProj_Flamethrower(), Terraria.Main.DrawProj_Flamethrower_Foxsparks(), Terraria.Main.DrawProj_Spear(), Terraria.GameContent.UI.EmoteBubble.DrawTemporaryBubble(), Terraria.GameContent.VoidLensHelper.DrawToDrawData(), Terraria.Main.DrawTrail(), Terraria.Main.EntitySpriteDraw(), Terraria.Collision.ExpandVertically(), Terraria.GameContent.TextureAssets.Extra, Terraria.GameContent.TextureAssets.EyeLaserSmall, Terraria.GameContent.TextureAssets.FishingLine, Terraria.GameContent.TextureAssets.Flames, System.Math.Floor(), Terraria.Projectile.frame, Terraria.Projectile.frameCounter, Microsoft.Xna.Framework.Color.G, Terraria.Main.gamePaused, Terraria.GameContent.TextureAssets.GemChain, Terraria.Projectile.GetAlpha(), Terraria.Projectile.HallowBossPelletStormInfo.GetBulletPosition(), Terraria.Projectile.HallowBossPelletStormInfo.GetBulletProgress(), Terraria.Projectile.GetCeleb2Color(), Terraria.Lighting.GetColor(), Terraria.Projectile.GetConstellationColor(), Terraria.Projectile.GetFairyQueenWeaponsColor(), Terraria.Graphics.FinalFractalHelper.GetFinalFractalProfile(), Terraria.Projectile.GetFirstFractalColor(), Terraria.Projectile.GetFloatingDaggerMinionGlowColor(), Terraria.DataStructures.DrawAnimation.GetFrame(), Terraria.Projectile.GetGolfTrailColor(), Terraria.Projectile.GetLastPrismHue(), Terraria.Utils.GetLerpValue(), Terraria.Item.GetPhaseColor(), Terraria.Main.GetPlayerArmPosition(), Terraria.GameContent.PortalHelper.GetPortalColor(), Terraria.Projectile.getRect(), Terraria.ID.Colors.GetSelectionGlowColor(), Terraria.GameContent.ARenderTargetContentByRequest.GetTarget(), Terraria.NPC.gfxOffY, Terraria.Player.gfxOffY, Terraria.Projectile.gfxOffY, Terraria.Player.ghostFade, Terraria.Main.GlobalTimeWrappedHourly, Terraria.GameContent.TextureAssets.GlowMask, Terraria.Projectile.glowMask, Microsoft.Xna.Framework.Color.Gold, Terraria.GameContent.TextureAssets.GolfBallOutline, Terraria.Player.gravDir, Terraria.Player.head, Microsoft.Xna.Framework.Graphics.Texture2D.Height, Microsoft.Xna.Framework.Rectangle.Height, Terraria.Entity.height, Terraria.Item.holdStyle, Microsoft.Xna.Framework.Color.HotPink, Terraria.Main.hslToRgb(), Terraria.Projectile.identity, System.Math.IEEERemainder(), Terraria.Main.instance, int, Microsoft.Xna.Framework.Rectangle.Intersects(), Terraria.Player.inventory, Terraria.WorldGen.InWorld(), Terraria.ID.ProjectileID.Sets.IsAGolfBall, Terraria.Projectile.isAPreviewDisplayDoll, Terraria.Projectile.isAPreviewDummy, Terraria.ID.ItemID.Sets.IsFood, Terraria.GameContent.Golf.GolfHelper.IsGolfBallResting(), Terraria.GameContent.Golf.GolfHelper.IsGolfShotValid(), Terraria.GameContent.Golf.GolfHelper.IsPlayerHoldingClub(), Terraria.GameContent.ARenderTargetContentByRequest.IsReady, Terraria.Projectile.HallowBossPelletStormInfo.IsValid(), Terraria.GameContent.TextureAssets.Item, Terraria.Player.itemAnimation, Terraria.Player.itemAnimationMax, Terraria.Main.itemAnimations, Terraria.Utils.LaserLineFraming(), Microsoft.Xna.Framework.Vector2.Length(), Microsoft.Xna.Framework.Vector3.Length(), Microsoft.Xna.Framework.Color.Lerp(), Microsoft.Xna.Framework.MathHelper.Lerp(), Microsoft.Xna.Framework.Vector2.Lerp(), Microsoft.Xna.Framework.Vector4.Lerp(), Terraria.GameContent.TextureAssets.LightDisc, Terraria.DelegateMethods.LightningLaserDraw(), Microsoft.Xna.Framework.Color.LimeGreen, Terraria.Main.LoadItem(), Terraria.Main.LoadNPC(), Terraria.Main.LoadProjectile(), Terraria.Projectile.localAI, Terraria.Main.LocalPlayer, Terraria.GameContent.TextureAssets.MagicPixel, System.Math.Max(), Microsoft.Xna.Framework.MathHelper.Max(), Terraria.Player.maxMinions, System.Reflection.MaxValue, System.Math.Min(), Microsoft.Xna.Framework.MathHelper.Min(), Terraria.Player.miscCounter, Terraria.Player.mount, Terraria.Player.MountedCenter, Terraria.Main.mouseTextColor, Terraria.Main.myPlayer, Terraria.Player.netOffset, Terraria.Utilities.UnifiedRandom.Next(), Microsoft.Xna.Framework.Vector2.Normalize(), Terraria.GameContent.TextureAssets.Npc, Terraria.Main.npc, Microsoft.Xna.Framework.Rectangle.Offset(), Terraria.Projectile.oldPos, Terraria.Projectile.oldRot, Terraria.Projectile.oldSpriteDirection, Microsoft.Xna.Framework.Vector2.One, Microsoft.Xna.Framework.Vector4.One, Terraria.Projectile.Opacity, Microsoft.Xna.Framework.Color.Orange, Microsoft.Xna.Framework.Color.OrangeRed, Terraria.Main.OurFavoriteColor, Terraria.Player.ownedProjectileCounts, Terraria.Projectile.owner, Terraria.Projectile.ownerHitCheck, Terraria.Main.player, Terraria.GameContent.TextureAssets.RenderTargets.PlayerTitaniumStormBuff, Terraria.Entity.position, Terraria.GameContent.TextureAssets.Projectile, Terraria.Main.projectile, Terraria.Main.projFrames, Microsoft.Xna.Framework.Color.Purple, Microsoft.Xna.Framework.Color.R, Terraria.DelegateMethods.RainbowLaserDraw(), Terraria.Main.rand, Terraria.Utils.RandomFloat(), Terraria.Utils.RandomInt(), Terraria.Item.ranged, Microsoft.Xna.Framework.Color.Red, Terraria.GameContent.Golf.GolfHelper.ShotStrength.RelativeStrength, Terraria.Utils.Remap(), Terraria.GameContent.ARenderTargetContentByRequest.Request(), Terraria.Main.rgbToHsl(), Terraria.Player.RotatedRelativePoint(), Terraria.Projectile.rotation, Terraria.GameContent.Golf.GolfHelper.ShotStrength.RoughLandResistance, Terraria.Item.scale, Terraria.Projectile.scale, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Terraria.Player.selectedItem, Terraria.Utilities.UnifiedRandom.SetSeed(), Terraria.Player.setVortex, Terraria.Player.shirtColor, Terraria.NPC.ShouldEmpressBeEnraged(), Terraria.Player.shroomiteStealth, System.Math.Sign(), System.Math.Sin(), Terraria.Entity.Size, Microsoft.Xna.Framework.Vector2.SmoothStep(), Terraria.Main.spriteBatch, Terraria.Projectile.spriteDirection, System.Math.Sqrt(), Terraria.Player.stealth, Terraria.Player.stringColor, Terraria.Main.tenthAnniversaryWorld, Terraria.Main.tile, Terraria.Main.TileFrameSeed, Terraria.Main.time, Terraria.Main.timeForVisualEffects, Terraria.Projectile.timeLeft, Terraria.GameContent.UI.WiresUI.Settings.ToolMode, Terraria.Entity.Top, Microsoft.Xna.Framework.Color.ToVector3(), Microsoft.Xna.Framework.Color.ToVector4(), Terraria.ID.ProjectileID.Sets.TrailCacheLength, Terraria.Graphics.FinalFractalHelper.FinalFractalProfile.trailColor, Terraria.ID.ProjectileID.Sets.TrailingMode, Terraria.Graphics.FinalFractalHelper.FinalFractalProfile.trailWidth, Microsoft.Xna.Framework.Color.Transparent, Terraria.Main.TryApplyingPlayerStringColor(), Terraria.Main.TryInteractingWithMoneyTrough(), Terraria.Main.TryInteractingWithVoidLens(), Terraria.Main.TryPetting(), Terraria.DelegateMethods.TurretLaserDraw(), Terraria.Item.type, Terraria.Mount.Type, Terraria.Projectile.type, Terraria.Player.underShirtColor, Microsoft.Xna.Framework.Vector2.UnitY, Terraria.Projectile.usesOwnerLight, Terraria.GameContent.Golf.GolfHelper.ValidateShot(), System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Graphics.Vector3, Terraria.Entity.velocity, Microsoft.Xna.Framework.Color.Violet, Microsoft.Xna.Framework.Vector4.W, Microsoft.Xna.Framework.Color.White, Terraria.Entity.whoAmI, Microsoft.Xna.Framework.Graphics.Texture2D.Width, Microsoft.Xna.Framework.Rectangle.Width, Terraria.Entity.width, Terraria.GameContent.TextureAssets.WireUi, Terraria.Utils.WrappedLerp(), Microsoft.Xna.Framework.Input.X, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector4.X, Microsoft.Xna.Framework.Point.Y, Microsoft.Xna.Framework.Rectangle.Y, Microsoft.Xna.Framework.Vector2.Y, Microsoft.Xna.Framework.Vector4.Y, Microsoft.Xna.Framework.Color.Yellow, Microsoft.Xna.Framework.Vector4.Z, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.Tile_Entities.TEDisplayDoll.Draw(), Terraria.DataStructures.PlayerDrawLayers.DrawHeldProj(), Terraria.GameContent.UI.Elements.UICharacter.DrawPets(), and Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_RenderAllLayersSlow().