Terraria Decompiled: Terraria.Main.CollectDisplayResolutionsFromAdapter
CollectDisplayResolutionsFromAdapter()
static void Terraria.Main.CollectDisplayResolutionsFromAdapter (GraphicsAdapter adapter) inline static private
Definition at line 8797 of file Main.cs.
        {
            foreach (DisplayMode displayMode in adapter.SupportedDisplayModes)
            {
                if (displayMode.Width >= Main.minScreenW && displayMode.Width <= Main.maxScreenW && displayMode.Height >= Main.minScreenH && displayMode.Height <= Main.maxScreenH && !Main.IsModeOfSameResolutionRegistered(displayMode))
                {
                    Main.RegisterDisplayResolution(displayMode.Width, displayMode.Height);
                }
            }
        }
References Microsoft.Xna.Framework.Graphics.DisplayMode.Height, Terraria.Main.IsModeOfSameResolutionRegistered(), Terraria.Main.maxScreenH, Terraria.Main.maxScreenW, Terraria.Main.minScreenH, Terraria.Main.minScreenW, Terraria.Main.RegisterDisplayResolution(), and Microsoft.Xna.Framework.Graphics.DisplayMode.Width.
Referenced by Terraria.Main.CacheSupportedDisplaySizes().