Terraria Decompiled: Terraria.Main.AnimateTiles_WeatherVane
AnimateTiles_WeatherVane()
static void Terraria.Main.AnimateTiles_WeatherVane () inline static private
Definition at line 17979 of file Main.cs.
        {
            int num = Math.Sign(Main.WindForVisuals);
            int num2 = (int)MathHelper.Clamp((float)Math.Floor((double)(Math.Abs(Main.WindForVisuals) * 10f)), -5f, 5f);
            int num3 = 6;
            Main.tileFrameCounter[490] += num2;
            if (Main.tileFrameCounter[490] >= num3)
            {
                Main.tileFrameCounter[490] -= num3 * Main.tileFrameCounter[490];
                if ((Main.tileFrame[490] != 0 || num != -1) && (Main.tileFrame[490] != 6 || num != 1))
                {
                    int[] array = Main.tileFrame;
                    int num4 = 490;
                    int num5 = array[num4] + 1;
                    array[num4] = num5;
                    if (num5 >= 12)
                    {
                        Main.tileFrame[490] = 0;
                        Main.weatherVaneBobframe = 0;
                        return;
                    }
                }
                else if (Main.rand.NextFloat() < Math.Abs(Main.WindForVisuals) * 0.5f && ++Main.weatherVaneBobframe == 8)
                {
                    Main.weatherVaneBobframe = 0;
                }
            }
        }
References System.Math.Abs(), System.array, Microsoft.Xna.Framework.MathHelper.Clamp(), System.Math.Floor(), int, Terraria.Main.rand, System.Math.Sign(), Terraria.Main.tileFrame, Terraria.Main.tileFrameCounter, and Terraria.Main.WindForVisuals.
Referenced by Terraria.Main.AnimateTiles().