Terraria Decompiled: Terraria.Main.GetAreaToLight
GetAreaToLight()
static Microsoft.Xna.Framework.Rectangle Terraria.Main.GetAreaToLight () inline static
Definition at line 64990 of file Main.cs.
        {
            Vector2 vector = Main.Camera.ScaledPosition;
            Vector2 vector2 = Main.Camera.ScaledSize;
            if (!Lighting.UsingNewLighting)
            {
                vector = Main.Camera.UnscaledPosition;
                vector2 = Main.Camera.UnscaledSize;
            }
            int num = (int)Math.Floor((double)(vector.X / 16f)) - 1;
            int num2 = (int)Math.Floor((double)((vector.X + vector2.X) / 16f)) + 2;
            int num3 = (int)Math.Floor((double)(vector.Y / 16f)) - 1;
            int num4 = (int)Math.Floor((double)((vector.Y + vector2.Y) / 16f)) + 2;
            return new Microsoft.Xna.Framework.Rectangle(num, num3, num2 - num, num4 - num3);
        }
References Terraria.Main.Camera, System.Math.Floor(), int, Terraria.Graphics.Camera.ScaledPosition, Terraria.Graphics.Camera.ScaledSize, Terraria.Graphics.Camera.UnscaledPosition, Terraria.Graphics.Camera.UnscaledSize, Terraria.Lighting.UsingNewLighting, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Main.DoDraw(), Terraria.Main.UpdateSceneMetrics(), and Terraria.Main.UpdateWeather().