Terraria Decompiled: Terraria.Main.NewText
NewText() [2/2]
static void Terraria.Main.NewText (string newText, Microsoft::Xna::Framework::Color color) inline static
Definition at line 65889 of file Main.cs.
        {
            Main.NewText(newText, color.R, color.G, color.B);
        }
References Microsoft.Xna.Framework.Color.B, Microsoft.Xna.Framework.Color.G, Terraria.Main.NewText(), and Microsoft.Xna.Framework.Color.R.
Referenced by Terraria.WorldBuilding.WorldGenerator.Controller.b__45_0(), Terraria.WorldBuilding.WorldGenerator.Controller.b__46_0(), Terraria.GameContent.CoinLossRevengeSystem.CacheEnemy(), Terraria.Graphics.Capture.CaptureCamera.Capture(), Terraria.Player.CheckSpawn_Internal(), Terraria.Utilities.TileSnapshot.Compare(), Terraria.WorldBuilding.WorldUtils.DebugRegen(), Terraria.Net.LegacyNetBufferPool.DisplayBufferSizes(), Terraria.Main.DrawPVPIcons(), Terraria.TimeLogger.EndDrawFrame(), Terraria.GameContent.Events.DD2Event.FailureMessage(), Terraria.Player.ItemCheck_UseCombatBook(), Terraria.Player.ItemCheck_UseEventItems(), Terraria.Player.ItemCheck_UsePeddlersSatchel(), Terraria.GameContent.UI.Elements.UIDebugCommandItem.LeftClick(), Terraria.WorldGen.MoveTownNPC(), Terraria.Main.NewText(), Terraria.Initializers.AchievementInitializer.OnAchievementCompleted(), Terraria.Cinematics.DD2Film.OnBegin(), Terraria.Cinematics.DD2Film.OnEnd(), Terraria.Main.PerformHousingCheck(), Terraria.Testing.DebugUtils.PracticeModeReset(), Terraria.WorldBuilding.WorldGenerator.Controller.ReportException(), Terraria.WorldBuilding.WorldGenSnapshot.Restore(), Terraria.GameContent.CoinLossRevengeSystem.RevengeMarker.SpawnEnemy(), Terraria.TimeLogger.StartNextFrame(), Terraria.GameContent.PortalHelper.SupportedTilesAreFine(), Terraria.GameContent.UI.States.UIWorldGenDebug.TestHiddenTileData(), Terraria.GameContent.UI.States.UIWorldGenDebug.TestResetFromPassesAndRegen(), Terraria.GameContent.UI.States.UIWorldGenDebug.TestResumeFromSnapshots(), Terraria.GameContent.UI.States.UIWorldGenDebug.TestSetupResetAndCreateSnapshots(), Terraria.Player.TileInteractionsUse(), Terraria.TimeLogger.ToggleLogging(), Terraria.WorldBuilding.WorldGenerator.Controller.TryCreateSnapshot(), Terraria.WorldBuilding.WorldGenerator.Controller.TryReset(), Terraria.TestHighFPSIssues.Update(), Terraria.Main.UpdateAudio(), and Terraria.GameContent.DontStarveDarknessDamageDealer.UpdateDarknessState().