Terraria Decompiled: Terraria.Main.ContentFileUpdated
ContentFileUpdated()
void Terraria.Main.ContentFileUpdated (IContentSource contentSource, string path, string fullPath) inline package
Definition at line 8859 of file Main.cs.
        {
            try
            {
                if (LanguageManager.Instance.HotReloadContentFile(contentSource, path, fullPath))
                {
                    Main.NewTextMultiline(Language.GetTextValue("HotReload.LocalizationsReloaded", path), false, new Microsoft.Xna.Framework.Color(250, 250, 0), -1);
                }
            }
            catch (Exception ex)
            {
                Main.NewTextMultiline(Language.GetTextValue("HotReload.ErrorUpdating", path, ex.Message), false, new Microsoft.Xna.Framework.Color(250, 50, 0), -1);
            }
        }
References Terraria.Localization.Language.GetTextValue(), Terraria.Localization.LanguageManager.HotReloadContentFile(), Terraria.Localization.LanguageManager.Instance, System.Exception.Message, and Terraria.Main.NewTextMultiline().