Terraria Decompiled: Terraria.Main.GetInputText
GetInputText()
static string Terraria.Main.GetInputText (string oldString, bool allowMultiLine = false) inline static
Definition at line 18767 of file Main.cs.
        {
            if (Main.dedServ)
            {
                return "";
            }
            if (!FocusHelper.AllowUIInputs)
            {
                return oldString;
            }
            Main.inputTextEnter = false;
            Main.inputTextEscape = false;
            string text = oldString;
            string text2 = "";
            if (text == null)
            {
                text = "";
            }
            bool flag = false;
            if (Main.inputText.PressingControl() && !Main.inputText.PressingAlt())
            {
                if (Main.inputText.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.Z) && !Main.oldInputText.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.Z))
                {
                    text = "";
                }
                else if (Main.inputText.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.X) && !Main.oldInputText.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.X))
                {
                    Platform.Get<IClipboard>().Value = oldString;
                    text = "";
                }
                else if ((Main.inputText.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.C) && !Main.oldInputText.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.C)) || (Main.inputText.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.Insert) && !Main.oldInputText.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.Insert)))
                {
                    Platform.Get<IClipboard>().Value = oldString;
                }
                else if (Main.inputText.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.V) && !Main.oldInputText.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.V))
                {
                    text2 = Main.PasteTextIn(allowMultiLine, text2);
                }
            }
            else
            {
                if (Main.inputText.PressingShift())
                {
                    if (Main.inputText.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.Delete) && !Main.oldInputText.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.Delete))
                    {
                        Platform.Get<IClipboard>().Value = oldString;
                        text = "";
                    }
                    if (Main.inputText.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.Insert) && !Main.oldInputText.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.Insert))
                    {
                        text2 = Main.PasteTextIn(allowMultiLine, text2);
                    }
                }
                if (!Platform.IsWindows && Main.inputText.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.Escape) && !Main.oldInputText.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.Escape))
                {
                    Main.inputTextEscape = true;
                }
                for (int i = 0; i < Main.keyCount; i++)
                {
                    int num = Main.keyInt[i];
                    string text3 = Main.keyString[i];
                    if (num == 13)
                    {
                        Main.inputTextEnter = true;
                    }
                    else if (num == 27)
                    {
                        Main.inputTextEscape = true;
                    }
                    else if (num >= 32 && num != 127)
                    {
                        text2 += text3;
                    }
                }
            }
            Main.keyCount = 0;
            text += text2;
            Main.oldInputText = Main.inputText;
            Main.inputText = Keyboard.GetState();
            if (Main.inputText.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.Back) && Main.oldInputText.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.Back) && !Main.imeCompositionActive)
            {
                Main.backSpaceRate -= 0.05f;
                if (Main.backSpaceRate < 0f)
                {
                    Main.backSpaceRate = 0f;
                }
                if (Main.backSpaceCount <= 0)
                {
                    Main.backSpaceCount = (int)Math.Round((double)Main.backSpaceRate);
                    flag = true;
                }
                Main.backSpaceCount--;
            }
            else
            {
                Main.backSpaceRate = 7f;
                Main.backSpaceCount = 15;
            }
            if (((Main.inputText.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.Back) && !Main.oldInputText.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.Back) && !Main.imeCompositionActive) || flag) && text.Length > 0)
            {
                TextSnippet[] array = ChatManager.ParseMessage(text, Microsoft.Xna.Framework.Color.White).ToArray();
                if (array[array.Length - 1].DeleteWhole)
                {
                    text = text.Substring(0, text.Length - array[array.Length - 1].TextOriginal.Length);
                }
                else
                {
                    text = Utils.TrimLastCharacter(text);
                }
            }
            Main.imeCompositionActive = !string.IsNullOrEmpty(Platform.Get<IImeService>().CompositionString);
            return text;
        }
References Terraria.FocusHelper.AllowUIInputs, System.array, Terraria.Main.backSpaceCount, Terraria.Main.backSpaceRate, ReLogic.Localization.IME.IImeService.CompositionString, Terraria.Main.dedServ, Microsoft.Xna.Framework.Input.Keyboard.GetState(), Terraria.Main.imeCompositionActive, Terraria.Main.inputText, int, Microsoft.Xna.Framework.Input.KeyboardState.IsKeyDown(), ReLogic.OS.Platform.IsWindows, Terraria.Main.keyCount, Terraria.Main.keyInt, Terraria.Main.keyString, Terraria.Main.oldInputText, Terraria.UI.Chat.ChatManager.ParseMessage(), Terraria.Main.PasteTextIn(), System.Math.Round(), System.text, Terraria.Utils.TrimLastCharacter(), and Microsoft.Xna.Framework.Color.White.
Referenced by Terraria.Main.DoUpdate_HandleChat(), Terraria.Main.DrawMenu(), Terraria.GameContent.UI.Elements.UISearchBar.DrawSelf(), Terraria.GameContent.UI.States.UIVirtualKeyboard.DrawSelf(), Terraria.Main.InputTextChest(), Terraria.Main.InputTextSign(), Terraria.Social.WeGame.NetClientSocialModule.OnAuthSuccess(), Terraria.Social.Steam.NetClientSocialModule.OnLobbyEntered(), and Terraria.GameContent.UI.Elements.UIWorldListItem.PlayGame().