Terraria Decompiled: Terraria.Main.MouseTextNoOverride
MouseTextNoOverride()
void Terraria.Main.MouseTextNoOverride (string cursorText, int rare = 0, byte diff = 0, int hackedMouseX = -1, int hackedMouseY = -1, int hackedScreenWidth = -1, int hackedScreenHeight = -1, int pushWidthX = 0) inline
Definition at line 18908 of file Main.cs.
        {
            this.MouseText(cursorText, null, rare, diff, hackedMouseX, hackedMouseY, hackedScreenWidth, hackedScreenHeight, pushWidthX, true);
        }
Referenced by Terraria.GameContent.Creative.CreativePowers.APerPlayerTogglePower.button_OnUpdate(), Terraria.GameContent.Creative.CreativePowers.ASharedButtonPower.button_OnUpdate(), Terraria.GameContent.Creative.CreativePowers.ASharedTogglePower.button_OnUpdate(), Terraria.GameContent.Creative.CreativePowers.APerPlayerSliderPower.categoryButton_OnUpdate(), Terraria.GameContent.Creative.CreativePowers.ASharedSliderPower.categoryButton_OnUpdate(), Terraria.GameContent.UI.States.UICreativePowersMenu.CategoryButton_OnUpdate_DisplayTooltips(), Terraria.Main.DrawBestiaryIcon(), Terraria.UI.CraftingUI.DrawCraftFromNearbyChestsToggle(), Terraria.Main.DrawEmoteBubblesButton(), Terraria.UI.BannerClaimingUI.DrawGridToggle(), Terraria.UI.CraftingUI.DrawGridToggle(), Terraria.GameContent.Creative.CreativeUI.DrawToggleButton(), Terraria.GameContent.Creative.CreativePowers.DifficultySliderPower.MouseOver_Expert(), Terraria.GameContent.Creative.CreativePowers.DifficultySliderPower.MouseOver_Journey(), Terraria.GameContent.Creative.CreativePowers.DifficultySliderPower.MouseOver_Master(), Terraria.GameContent.Creative.CreativePowers.DifficultySliderPower.MouseOver_Normal(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.research_OnUpdate(), Terraria.GameContent.UI.Elements.UICreativeItemsInfiniteFilteringOptions.ShowButtonName(), Terraria.GameContent.Creative.CreativePowers.ModifyTimeRate.UpdateMouseOverNoItemText(), Terraria.GameContent.Creative.CreativePowers.ModifyWindDirectionAndStrength.UpdateMouseOverNoItemText(), Terraria.GameContent.Creative.CreativePowers.ModifyRainPower.UpdateMouseOverNoItemText(), Terraria.GameContent.Creative.CreativePowers.SpawnRateSliderPerPlayerPower.UpdateMouseOverNoItemText(), Terraria.GameContent.Creative.CreativePowers.ModifyTimeRate.UpdateSliderAndShowMultiplierMouseOver(), Terraria.GameContent.Creative.CreativePowers.ModifyWindDirectionAndStrength.UpdateSliderAndShowMultiplierMouseOver(), Terraria.GameContent.Creative.CreativePowers.ModifyRainPower.UpdateSliderAndShowMultiplierMouseOver(), Terraria.GameContent.Creative.CreativePowers.SpawnRateSliderPerPlayerPower.UpdateSliderAndShowMultiplierMouseOver(), and Terraria.GameContent.Creative.CreativePowers.DifficultySliderPower.UpdateSliderColorAndShowMultiplierMouseOver().