Terraria Decompiled: Terraria.Main.DrawNPCMapIcons3
DrawNPCMapIcons3()
static void Terraria.Main.DrawNPCMapIcons3 (float X, float Y, float scale, byte alpha, float headScale) inline static private
Definition at line 56777 of file Main.cs.
        {
            for (int i = 0; i < Main.maxNPCs; i++)
            {
                if (Main.npc[i].active && Main.npc[i].townNPC && Main.DrawNPCMapIcon_CanBeSeen_Townie(Main.npc[i]))
                {
                    int headIndexSafe = TownNPCProfiles.GetHeadIndexSafe(Main.npc[i]);
                    if (headIndexSafe > 0)
                    {
                        SpriteEffects spriteEffects = SpriteEffects.None;
                        if (Main.npc[i].direction > 0)
{
                            spriteEffects = SpriteEffects.FlipHorizontally;
                        }
                        Vector2 vector = Main.npc[i].Center + new Vector2(0f, Main.npc[i].gfxOffY) + Main.npc[i].netOffset;
                        float num = vector.X / 16f * scale;
                        float num2 = vector.Y / 16f * scale;
                        num += X;
                        num2 += Y;
                        num -= 10f * scale;
                        num2 -= 10f * scale;
                        Main.DrawNPCHeadFriendly(Main.npc[i], alpha, headScale, spriteEffects, headIndexSafe, num, num2);
                    }
                }
                if (Main.npc[i].active && Main.npc[i].GetBossHeadTextureIndex() != -1)
                {
                    float bossHeadRotation = Main.npc[i].GetBossHeadRotation();
                    SpriteEffects bossHeadSpriteEffects = Main.npc[i].GetBossHeadSpriteEffects();
                    Vector2 vector2 = Main.npc[i].Center + new Vector2(0f, Main.npc[i].gfxOffY) + Main.npc[i].netOffset;
                    if (Main.npc[i].type == 134)
                    {
                        Vector2 vector3 = Main.npc[i].Center;
                        int num3 = 1;
                        int num4 = (int)Main.npc[i].ai[0];
                        while (num3 < 15 && Main.npc[num4].active && Main.npc[num4].type >= 134 && Main.npc[num4].type <= 136)
{
                            num3++;
                            vector3 += Main.npc[num4].Center;
                            num4 = (int)Main.npc[num4].ai[0];
                        }
                        vector3 /= (float)num3;
                        vector2 = vector3;
                    }
                    int bossHeadTextureIndex = Main.npc[i].GetBossHeadTextureIndex();
                    float num5 = vector2.X / 16f * scale;
                    float num6 = vector2.Y / 16f * scale;
                    num5 += X;
                    num6 += Y;
                    num5 -= 10f * scale;
                    num6 -= 10f * scale;
                    Main.DrawNPCHeadBoss(Main.npc[i], alpha, headScale, bossHeadRotation, bossHeadSpriteEffects, bossHeadTextureIndex, num5, num6);
                }
            }
        }
References Terraria.NPC.active, Terraria.NPC.ai, Terraria.Entity.Center, Terraria.Entity.direction, Terraria.Main.DrawNPCHeadBoss(), Terraria.Main.DrawNPCHeadFriendly(), Terraria.Main.DrawNPCMapIcon_CanBeSeen_Townie(), Terraria.NPC.GetBossHeadRotation(), Terraria.NPC.GetBossHeadSpriteEffects(), Terraria.NPC.GetBossHeadTextureIndex(), Terraria.GameContent.TownNPCProfiles.GetHeadIndexSafe(), Terraria.NPC.gfxOffY, int, Terraria.Main.maxNPCs, Terraria.NPC.netOffset, Terraria.Main.npc, Terraria.NPC.townNPC, Terraria.NPC.type, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Input.X, and Microsoft.Xna.Framework.Input.Y.
Referenced by Terraria.Main.DrawMap().