Terraria Decompiled: Terraria.Main.DoUpdate_Enter_ToggleChat
DoUpdate_Enter_ToggleChat()
static void Terraria.Main.DoUpdate_Enter_ToggleChat () inline static private
Definition at line 16707 of file Main.cs.
        {
            if (Main.keyState.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.Enter) && !Main.keyState.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.LeftAlt) && !Main.keyState.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.RightAlt) && FocusHelper.AllowUIInputs)
            {
                if (Main.chatRelease && !Main.drawingPlayerChat && !Main.editSign && !Main.editChest && (!Main.gameMenu || Main.menuChat) && !Main.ingameOptionsWindow && !Main.keyState.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.Escape))
                {
                    SoundEngine.PlaySound(10, -1, -1, 1, 1f, 0f);
                    Main.OpenPlayerChat();
                    Main.chatText = "";
                }
                Main.chatRelease = false;
                return;
            }
            Main.chatRelease = true;
        }
References Terraria.FocusHelper.AllowUIInputs, Terraria.Main.chatRelease, Terraria.Main.drawingPlayerChat, Terraria.Main.editChest, Terraria.Main.editSign, Terraria.Main.gameMenu, Terraria.Main.ingameOptionsWindow, Microsoft.Xna.Framework.Input.KeyboardState.IsKeyDown(), Terraria.Main.keyState, Terraria.Main.menuChat, Terraria.Main.OpenPlayerChat(), and Terraria.Audio.SoundEngine.PlaySound().
Referenced by Terraria.Main.DoUpdate().