Terraria Decompiled: Terraria.Main.DrawMapIcons_PotionOfReturnAppearAfterUsePosition
DrawMapIcons_PotionOfReturnAppearAfterUsePosition()
void Terraria.Main.DrawMapIcons_PotionOfReturnAppearAfterUsePosition (SpriteBatch spriteBatch, Vector2 mapTopLeft, Vector2 mapX2Y2AndOff, Microsoft::Xna::Framework::Rectangle? mapRect, float mapScale, float drawScale, ref string mouseTextString) inline private
Definition at line 57257 of file Main.cs.
        {
            Vector2? potionOfReturnOriginalUsePosition = Main.LocalPlayer.PotionOfReturnOriginalUsePosition;
            if (potionOfReturnOriginalUsePosition == null)
            {
                return;
            }
            Vector2? vector = potionOfReturnOriginalUsePosition;
            Vector2 vector2 = new Vector2(0f, (float)(-(float)Main.LocalPlayer.height / 2));
            Vector2 vector3 = (vector + vector2).Value / 16f - mapTopLeft;
            vector3 *= mapScale;
            vector3 += mapX2Y2AndOff;
            vector3 = vector3.Floor();
            if (mapRect != null && !mapRect.Value.Contains(vector3.ToPoint()))
            {
                return;
            }
            Texture2D value = TextureAssets.Extra[173].Value;
            Microsoft.Xna.Framework.Rectangle rectangle = value.Frame(1, 1, 0, 0, 0, 0);
            spriteBatch.Draw(value, vector3, new Microsoft.Xna.Framework.Rectangle?(rectangle), Microsoft.Xna.Framework.Color.White, 0f, rectangle.Size() / 2f, drawScale, SpriteEffects.None, 0f);
            if (Utils.CenteredRectangle(vector3, rectangle.Size() * drawScale).Contains(Main.MouseScreen.ToPoint()))
            {
                mouseTextString = Language.GetTextValue("GameUI.PotionOfReturnExitPortal");
                Main.MouseScreen + new Vector2(-28f) + new Vector2(4f, 0f);
            }
        }
References Terraria.Utils.CenteredRectangle(), Microsoft.Xna.Framework.Rectangle.Contains(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.GameContent.TextureAssets.Extra, Terraria.Localization.Language.GetTextValue(), Terraria.Entity.height, Terraria.Main.LocalPlayer, Terraria.Main.MouseScreen, Terraria.Player.PotionOfReturnOriginalUsePosition, System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, and Microsoft.Xna.Framework.Color.White.