Terraria Decompiled: Terraria.Main.OpenReportsMenu
OpenReportsMenu()
static void Terraria.Main.OpenReportsMenu () inline static
Definition at line 52903 of file Main.cs.
        {
            List<IProvideReports> list = new List<IProvideReports>();
            list.Add(Main.IssueReporter);
            if (SocialAPI.Workshop != null)
            {
                list.Add(SocialAPI.Workshop.IssueReporter);
            }
            UIReportsPage uireportsPage = new UIReportsPage(Main.MenuUI.CurrentState, Main.menuMode, list);
            Main.menuMode = 888;
            Main.MenuUI.SetState(uireportsPage);
        }
References Terraria.UI.UserInterface.CurrentState, Terraria.Main.IssueReporter, System.list, Terraria.Main.menuMode, Terraria.Main.MenuUI, Terraria.UI.UserInterface.SetState(), and Terraria.Social.SocialAPI.Workshop.
Referenced by Terraria.Social.Steam.WorkshopSocialModule._issueReporter_OnNeedToOpenUI(), Terraria.GameContent.UI.States.UIWorkshopHub.GoLogsClick(), and Terraria.GameContent.UI.IssueReportsIndicator.OpenUI().