Terraria Decompiled: Terraria.Main.DrawWOFTongueToPlayer
DrawWOFTongueToPlayer()
static void Terraria.Main.DrawWOFTongueToPlayer (int i) inline static private
Definition at line 37940 of file Main.cs.
        {
            float num = Main.npc[Main.wofNPCIndex].position.X + (float)(Main.npc[Main.wofNPCIndex].width / 2);
            float num2 = Main.npc[Main.wofNPCIndex].position.Y + (float)(Main.npc[Main.wofNPCIndex].height / 2);
            Vector2 vector = new Vector2(Main.player[i].position.X + (float)Main.player[i].width * 0.5f, Main.player[i].position.Y + (float)Main.player[i].height * 0.5f);
            float num3 = num - vector.X;
            float num4 = num2 - vector.Y;
            float num5 = (float)Math.Atan2((double)num4, (double)num3) - 1.57f;
            bool flag = true;
            while (flag)
            {
                float num6 = (float)Math.Sqrt((double)(num3 * num3 + num4 * num4));
                if (num6 < 40f)
                {
                    flag = false;
                }
                else
                {
                    num6 = (float)TextureAssets.Chain12.Height() / num6;
                    num3 *= num6;
                    num4 *= num6;
                    vector.X += num3;
                    vector.Y += num4;
                    num3 = num - vector.X;
                    num4 = num2 - vector.Y;
                    Microsoft.Xna.Framework.Color color = Lighting.GetColor((int)vector.X / 16, (int)(vector.Y / 16f));
                    Main.spriteBatch.Draw(TextureAssets.Chain12.Value, new Vector2(vector.X - Main.screenPosition.X, vector.Y - Main.screenPosition.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain12.Width(), TextureAssets.Chain12.Height())), color, num5, new Vector2((float)TextureAssets.Chain12.Width() * 0.5f, (float)TextureAssets.Chain12.Height() * 0.5f), 1f, SpriteEffects.None, 0f);
                }
            }
        }
References System.Math.Atan2(), Terraria.GameContent.TextureAssets.Chain12, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Lighting.GetColor(), Terraria.Entity.height, int, Terraria.Main.npc, Terraria.Main.player, Terraria.Entity.position, Terraria.Main.screenPosition, Terraria.Main.spriteBatch, System.Math.Sqrt(), ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Entity.width, Terraria.Main.wofNPCIndex, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Main.DrawWoF().