Terraria Decompiled: Terraria.Main.DrawSurfaceBG_Jungle
DrawSurfaceBG_Jungle()
void Terraria.Main.DrawSurfaceBG_Jungle (float backgroundTopMagicNumber, float bgGlobalScaleMultiplier, int pushBGTopHack, int[] bgTexIndexes) inline private
Definition at line 61845 of file Main.cs.
        {
            this.LoadBackground(bgTexIndexes[0]);
            Main.bgScale = 1.25f;
            Main.bgScale *= bgGlobalScaleMultiplier;
            this.bgParallax = 0.4;
            this.SetBackgroundOffsets(bgTexIndexes[0], backgroundTopMagicNumber, pushBGTopHack);
            Main.bgWidthScaled = (int)((float)Main.backgroundWidth[bgTexIndexes[0]] * Main.bgScale);
            SkyManager.Instance.DrawToDepth(Main.spriteBatch, 1f / (float)this.bgParallax);
            this.bgStartX = (int)(-Math.IEEERemainder((double)Main.screenPosition.X * this.bgParallax, (double)Main.bgWidthScaled) - (double)(Main.bgWidthScaled / 2));
            this.bgTopY = backgroundTopMagicNumber * 1800f + 1660f + this.scAdj + (float)pushBGTopHack;
            this.SetBackgroundOffsets(bgTexIndexes[0], backgroundTopMagicNumber, pushBGTopHack);
            if (Main.gameMenu)
            {
                this.bgTopY = (float)(320 + pushBGTopHack);
            }
            if (bgTexIndexes[0] == 59)
            {
                this.bgTopY -= 200f;
            }
            this.bgTopY += (float)this.DrawSurfaceBG_GetLayerYOffset(bgTexIndexes[0]);
            if (Main.bgWidthScaled <= 0)
            {
                return;
            }
            this.bgLoops = Main.screenWidth / Main.bgWidthScaled + 2;
            if ((double)Main.screenPosition.Y < Main.worldSurface * 16.0 + 16.0)
            {
                for (int i = 0; i < this.bgLoops; i++)
                {
                    Main.spriteBatch.Draw(TextureAssets.Background[bgTexIndexes[0]].Value, new Vector2((float)(this.bgStartX + Main.bgWidthScaled * i), this.bgTopY), this.GetBackgroundRect(bgTexIndexes[0]), Main.ColorOfSurfaceBackgroundsModified, 0f, default(Vector2), Main.bgScale, SpriteEffects.None, 0f);
                }
            }
            this.LoadBackground(bgTexIndexes[1]);
            Main.bgScale = 1.31f;
            Main.bgScale *= bgGlobalScaleMultiplier;
            this.bgParallax = 0.43;
            this.SetBackgroundOffsets(bgTexIndexes[1], backgroundTopMagicNumber, pushBGTopHack);
            Main.bgWidthScaled = (int)((float)Main.backgroundWidth[bgTexIndexes[1]] * Main.bgScale);
            SkyManager.Instance.DrawToDepth(Main.spriteBatch, 1f / (float)this.bgParallax);
            this.bgStartX = (int)(-Math.IEEERemainder((double)Main.screenPosition.X * this.bgParallax, (double)Main.bgWidthScaled) - (double)(Main.bgWidthScaled / 2));
            this.bgTopY = backgroundTopMagicNumber * 1950f + 1840f + this.scAdj + (float)pushBGTopHack;
            this.SetBackgroundOffsets(bgTexIndexes[1], backgroundTopMagicNumber, pushBGTopHack);
            if (Main.gameMenu)
            {
                this.bgTopY = (float)(400 + pushBGTopHack);
                this.bgStartX -= 80;
            }
            if (bgTexIndexes[1] == 60)
            {
                this.bgTopY -= 175f;
            }
            this.bgTopY += (float)this.DrawSurfaceBG_GetLayerYOffset(bgTexIndexes[1]);
            this.bgLoops = Main.screenWidth / Main.bgWidthScaled + 2;
            if ((double)Main.screenPosition.Y < Main.worldSurface * 16.0 + 16.0)
            {
                for (int j = 0; j < this.bgLoops; j++)
                {
                    Main.spriteBatch.Draw(TextureAssets.Background[bgTexIndexes[1]].Value, new Vector2((float)(this.bgStartX + Main.bgWidthScaled * j), this.bgTopY), this.GetBackgroundRect(bgTexIndexes[1]), Main.ColorOfSurfaceBackgroundsModified, 0f, default(Vector2), Main.bgScale, SpriteEffects.FlipHorizontally, 0f);
                }
            }
            Main.bgScale = 1.34f;
            Main.bgScale *= bgGlobalScaleMultiplier;
            this.LoadBackground(bgTexIndexes[2]);
            this.bgParallax = 0.49;
            this.SetBackgroundOffsets(bgTexIndexes[2], backgroundTopMagicNumber, pushBGTopHack);
            Main.bgWidthScaled = (int)((float)Main.backgroundWidth[bgTexIndexes[2]] * Main.bgScale);
            SkyManager.Instance.DrawToDepth(Main.spriteBatch, 1f / (float)this.bgParallax);
            this.bgStartX = (int)(-Math.IEEERemainder((double)Main.screenPosition.X * this.bgParallax, (double)Main.bgWidthScaled) - (double)(Main.bgWidthScaled / 2));
            this.bgTopY = backgroundTopMagicNumber * 2100f + 2060f + this.scAdj + (float)pushBGTopHack;
            this.SetBackgroundOffsets(bgTexIndexes[2], backgroundTopMagicNumber, pushBGTopHack);
            if (Main.gameMenu)
            {
                this.bgTopY = (float)(480 + pushBGTopHack);
                this.bgStartX -= 120;
            }
            if (bgTexIndexes[2] == 61)
            {
                this.bgTopY -= 150f;
            }
            this.bgTopY += (float)this.DrawSurfaceBG_GetLayerYOffset(bgTexIndexes[2]);
            this.bgLoops = Main.screenWidth / Main.bgWidthScaled + 2;
            if ((double)Main.screenPosition.Y < Main.worldSurface * 16.0 + 16.0)
            {
                for (int k = 0; k < this.bgLoops; k++)
                {
                    Main.spriteBatch.Draw(TextureAssets.Background[bgTexIndexes[2]].Value, new Vector2((float)(this.bgStartX + Main.bgWidthScaled * k), this.bgTopY), this.GetBackgroundRect(bgTexIndexes[2]), Main.ColorOfSurfaceBackgroundsModified, 0f, default(Vector2), Main.bgScale, SpriteEffects.None, 0f);
                }
            }
        }
References Terraria.GameContent.TextureAssets.Background, Terraria.Main.backgroundWidth, Terraria.Main.bgScale, Terraria.Main.bgWidthScaled, Terraria.Main.ColorOfSurfaceBackgroundsModified, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Graphics.Effects.SkyManager.DrawToDepth(), Terraria.Main.gameMenu, System.Math.IEEERemainder(), Terraria.Graphics.Effects.SkyManager.Instance, int, Terraria.Main.spriteBatch, and ReLogic.Content.Asset< T >.Value.