Terraria Decompiled: Terraria.Main.AnglerQuestSwap
AnglerQuestSwap()
static void Terraria.Main.AnglerQuestSwap () inline static
Definition at line 1742 of file Main.cs.
        {
            if (Main.netMode == 1)
            {
                return;
            }
            Main.anglerWhoFinishedToday.Clear();
            Main.anglerQuestFinished = false;
            bool flag = NPC.downedBoss1 || NPC.downedBoss2 || NPC.downedBoss3 || Main.hardMode || NPC.downedSlimeKing || NPC.downedQueenBee;
            bool flag2 = true;
            while (flag2)
            {
                flag2 = false;
                Main.anglerQuest = Main.rand.Next(Main.anglerQuestItemNetIDs.Length);
                int num = Main.anglerQuestItemNetIDs[Main.anglerQuest];
                if (num == 2454 && (!Main.hardMode || WorldGen.crimson))
                {
                    flag2 = true;
                }
                if (num == 2457 && WorldGen.crimson)
                {
                    flag2 = true;
                }
                if (num == 2462 && !Main.hardMode)
                {
                    flag2 = true;
                }
                if (num == 2463 && (!Main.hardMode || !WorldGen.crimson))
                {
                    flag2 = true;
                }
                if (num == 2465 && !Main.hardMode)
                {
                    flag2 = true;
                }
                if (num == 2468 && !Main.hardMode)
                {
                    flag2 = true;
                }
                if (num == 2471 && !Main.hardMode)
                {
                    flag2 = true;
                }
                if (num == 2473 && !Main.hardMode)
                {
                    flag2 = true;
                }
                if (num == 2477 && !WorldGen.crimson)
                {
                    flag2 = true;
                }
                if (num == 2480 && !Main.hardMode)
                {
                    flag2 = true;
                }
                if (num == 2483 && !Main.hardMode)
                {
                    flag2 = true;
                }
                if (num == 2484 && !Main.hardMode)
                {
                    flag2 = true;
                }
                if (num == 2485 && WorldGen.crimson)
                {
                    flag2 = true;
                }
                if ((num == 2476 || num == 2453 || num == 2473) && !flag)
                {
                    flag2 = true;
                }
                if (!Main.isThereAWorldSurface)
                {
                    if (num == 2476)
                    {
                        flag2 = true;
                    }
                    if (num == 2479)
                    {
                        flag2 = true;
                    }
                    if (num == 2480)
                    {
                        flag2 = true;
                    }
                    if (num == 2452)
                    {
                        flag2 = true;
                    }
                    if (num == 2453)
                    {
                        flag2 = true;
                    }
                    if (num == 2481)
                    {
                        flag2 = true;
                    }
                    if (num == 2483)
                    {
                        flag2 = true;
                    }
                    if (num == 2456)
                    {
                        flag2 = true;
                    }
                    if (num == 2458)
                    {
                        flag2 = true;
                    }
                    if (num == 2459)
                    {
                        flag2 = true;
                    }
                    if (num == 2461)
                    {
                        flag2 = true;
                    }
                    if (num == 2467)
                    {
                        flag2 = true;
                    }
                    if (num == 2468)
                    {
                        flag2 = true;
                    }
                    if (num == 2487)
                    {
                        flag2 = true;
                    }
                    if (num == 2488)
                    {
                        flag2 = true;
                    }
                    if (num == 2470)
                    {
                        flag2 = true;
                    }
                    if (num == 2473)
                    {
                        flag2 = true;
                    }
                    if (num == 2474)
                    {
                        flag2 = true;
                    }
                }
            }
            NetMessage.SendAnglerQuest(-1);
        }
References Terraria.Main.anglerQuest, Terraria.Main.anglerQuestItemNetIDs, Terraria.Main.anglerWhoFinishedToday, System.Collections.Generic.List< T >.Clear(), Terraria.WorldGen.crimson, Terraria.NPC.downedQueenBee, Terraria.Main.hardMode, Terraria.Main.isThereAWorldSurface, Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, and Terraria.NetMessage.SendAnglerQuest().
Referenced by Terraria.Main.UpdateTime_StartDay().