Terraria Decompiled: Terraria.Main.UpdateTime
UpdateTime()
static void Terraria.Main.UpdateTime () inline static private
Definition at line 66150 of file Main.cs.
        {
            if (LanternNight.LanternsUp)
            {
                Main.cloudBGActive = 0f;
                if (Main.numClouds > 30)
                {
                    Main.numClouds = 30;
                }
            }
            if (Main.ladyBugRainBoost > 0)
            {
                Main.ladyBugRainBoost -= Main.dayRate;
            }
            if (Main.pumpkinMoon)
            {
                Main.bloodMoon = false;
                Main.snowMoon = false;
            }
            if (Main.snowMoon)
            {
                Main.bloodMoon = false;
            }
            if (((Main.netMode != 1 && !Main.gameMenu) || Main.netMode == 2) && (Main.isThereAWorldSurface || Main.remixWorld))
            {
                if (Main.slimeRainTime > 0.0)
                {
                    Main.slimeRainTime -= (double)Main.dayRate;
                    if (Main.slimeRainTime <= 0.0)
                    {
                        Main.StopSlimeRain(true);
                    }
                }
                else if (Main.slimeRainTime < 0.0)
                {
                    Main.slimeRainTime += (double)Main.dayRate;
                    if (Main.slimeRainTime > 0.0)
                    {
                        Main.slimeRainTime = 0.0;
                    }
                }
                if (Main.raining)
                {
                    if (!CreativePowerManager.Instance.GetPower<CreativePowers.FreezeRainPower>().Enabled)
                    {
                        if (LanternNight.LanternsUp)
{
                            Main.StopRain(false);
                        }
                        else
{
                            Main.rainTime -= Main.dayRate;
                            if (Main.dayRate > 0)
{
                                int num = 86400 / Main.dayRate / 24;
                                if (Main.rainTime <= 0)
{
                                    Main.StopRain(false);
                                }
                                else if (Main.rand.Next(num * 2) == 0)
{
                                    Main.ChangeRain(false, null);
                                }
                            }
                        }
                    }
                }
                else if (!Main.slimeRain && !LanternNight.LanternsUp && !LanternNight.NextNightIsLanternNight)
                {
                    int num2 = 86400;
                    num2 /= ((Main.dayRate != 0) ? Main.dayRate : 1);
                    bool flag = !CreativePowerManager.Instance.GetPower<CreativePowers.FreezeRainPower>().Enabled && Main.dayRate != 0;
                    if (flag)
                    {
                        bool flag2 = false;
                        for (int i = 0; i < 255; i++)
{
                            if (Main.player[i].active && Main.player[i].statLifeMax >= 120)
{
                                flag2 = true;
                                break;
                            }
                        }
                        if (!flag2)
{
                            flag = false;
                        }
                    }
                    if (flag)
                    {
                        if (Main.rand.Next((int)((double)num2 * 5.75)) == 0)
{
                            Main.StartRain(false, null, false);
                        }
                        else if (Main.cloudBGActive >= 1f && Main.rand.Next((int)((double)num2 * 4.25)) == 0)
{
                            Main.StartRain(false, null, false);
                        }
                        else if (Main.ladyBugRainBoost > 0 && Main.rand.Next(num2) == 0)
{
                            Main.StartRain(false, null, false);
                        }
                    }
                    if (!Main.raining && !NPC.BusyWithAnyInvasionOfSorts() && Main.dayTime && Main.time < 27000.0 && Main.dayRate > 0)
                    {
                        int num3 = (int)(450000.00000000006 / (double)Main.dayRate);
                        if (!NPC.downedSlimeKing)
{
                            num3 /= 2;
                            if (WorldGen.Skyblock.lowTiles)
{
                                num3 /= 5;
                            }
                        }
                        else if (Main.hardMode)
{
                            num3 = (int)((double)num3 * 1.5);
                        }
                        bool flag3 = Main.AnyPlayerReadyToFightKingSlime();
                        if (!flag3)
{
                            num3 *= 5;
                        }
                        if (num3 > 0 && (flag3 || Main.expertMode) && Main.rand.Next(num3) == 0)
{
                            Main.StartSlimeRain(true);
                        }
                    }
                }
            }
            if (Main.maxRaining != Main.oldMaxRaining)
            {
                if (Main.netMode == 2)
                {
                    NetMessage.SendData(7, -1, -1, null, 0, 0f, 0f, 0f, 0, 0, 0);
                }
                Main.oldMaxRaining = Main.maxRaining;
            }
            Main.UpdateTimeRate();
            double num4 = Main.time;
            Main.time += (double)Main.dayRate;
            CultistRitual.UpdateTime();
            BirthdayParty.UpdateTime();
            LanternNight.UpdateTime();
            Sandstorm.UpdateTime();
            DD2Event.UpdateTime();
            CreditsRollEvent.UpdateTime();
            WorldGen.mysticLogsEvent.UpdateTime();
            Main.PylonSystem.Update();
            if (!Main.dedServ)
            {
                if (NPC.MoonLordCountdown > 0)
                {
                    float num5 = MathHelper.Clamp((float)Math.Sin((double)((float)NPC.MoonLordCountdown / 60f * 0.5f)) * 2f, 0f, 1f);
                    num5 *= 0.75f - 0.5f * ((float)NPC.MoonLordCountdown / (float)NPC.MaxMoonLordCountdown);
                    if (!Terraria.Graphics.Effects.Filters.Scene["MoonLordShake"].IsActive())
                    {
                        Terraria.Graphics.Effects.Filters.Scene.Activate("MoonLordShake", Main.player[Main.myPlayer].position, new object[0]);
                    }
                    Terraria.Graphics.Effects.Filters.Scene["MoonLordShake"].GetShader().UseIntensity(num5);
                }
                else if (Terraria.Graphics.Effects.Filters.Scene["MoonLordShake"].IsActive())
                {
                    Terraria.Graphics.Effects.Filters.Scene.Deactivate("MoonLordShake", new object[0]);
                }
            }
            if (NPC.MoonLordCountdown > 0)
            {
                NPC.MoonLordCountdown--;
                if (NPC.MoonLordCountdown <= 0 && Main.netMode != 1)
                {
                    NPC.SpawnOnPlayer((int)Player.FindClosest(new Vector2((float)(Main.maxTilesX / 2), (float)Main.worldSurface / 2f) * 16f, 0, 0), 398, 0f, 0f, 0f, 0f);
                }
            }
            if (NPC.taxCollector && Main.netMode != 2 && !Main.gameMenu)
            {
                Main.player[Main.myPlayer].taxTimer += Main.dayRate;
                if (Main.player[Main.myPlayer].taxTimer >= Player.taxRate)
                {
                    Main.player[Main.myPlayer].taxTimer -= Player.taxRate;
                    Main.player[Main.myPlayer].CollectTaxes();
                }
            }
            if (Main.netMode != 1)
            {
                Main.UpdateSlimeRainWarning();
            }
            if (Main.netMode != 1)
            {
                if (NPC.travelNPC)
                {
                    if (!Main.dayTime || Main.time > 48600.0)
                    {
                        WorldGen.UnspawnTravelNPC();
                    }
                }
                else if (!Main.IsFastForwardingTime() && Main.dayTime && Main.time < 27000.0)
                {
                    int num6 = Main.dayRate;
                    if (num6 < 1)
                    {
                        num6 = 1;
                    }
                    int num7 = (int)(27000.0 / (double)num6);
                    num7 *= 4;
                    if (Main.rand.Next(num7) == 0)
                    {
                        int num8 = 0;
                        for (int j = 0; j < Main.maxNPCs; j++)
{
                            if (Main.npc[j].active && Main.npc[j].townNPC && Main.npc[j].type != 37 && Main.npc[j].type != 453)
{
                                num8++;
                            }
                        }
                        if (num8 >= 2)
{
                            WorldGen.SpawnTravelNPC();
                        }
                    }
                }
                NPC.travelNPC = false;
            }
            if (Main.netMode != 1)
            {
                if (!Main.dayTime || Main.time > 48600.0)
                {
                    WorldGen.UnspawnHomelessNPC();
                }
                else if (!Main.IsFastForwardingTime() && Main.dayTime && Main.time < 27000.0)
                {
                    int num9 = Main.dayRate;
                    if (num9 < 1)
                    {
                        num9 = 1;
                    }
                    int num10 = (int)(27000.0 / (double)num9);
                    if (Main.rand.Next(num10) == 0)
                    {
                        int num11 = 0;
                        for (int k = 0; k < Main.maxNPCs; k++)
{
                            if (Main.npc[k].active && Main.npc[k].townNPC && !Main.npc[k].homeless && Main.npc[k].type != 37 && Main.npc[k].type != 453 && Main.npc[k].type != 368)
{
                                num11++;
                            }
                        }
                        if (num11 >= 1)
{
                            Main.UpdateTime_SpawnTownNPCs(true);
                            WorldGen.SpawnHomelessNPC();
                        }
                    }
                }
            }
            bool flag4 = Main.ShouldNormalEventsBeAbleToStart();
            if (!Main.dayTime)
            {
                Main.eclipse = false;
                if (!Main.IsFastForwardingTime() && !flag4)
                {
                    if (WorldGen.spawnEye && Main.netMode != 1 && Main.time > 4860.0)
                    {
                        for (int l = 0; l < 255; l++)
{
                            if (Main.player[l].active && !Main.player[l].dead && ((double)Main.player[l].position.Y < Main.worldSurface * 16.0 || (double)Main.spawnTileY > Main.worldSurface) && NPC.Spawner.CanSpawnEnemiesNear(Main.player[l]))
{
                                NPC.SpawnOnPlayer(l, 4, 0f, 0f, 0f, 0f);
                                WorldGen.spawnEye = false;
                                break;
                            }
                        }
                    }
                    if (WorldGen.spawnHardBoss > 0 && Main.netMode != 1 && Main.time > 4860.0)
                    {
                        bool flag5 = false;
                        for (int m = 0; m < Main.maxNPCs; m++)
{
                            if (Main.npc[m].active && Main.npc[m].boss)
{
                                flag5 = true;
                            }
                        }
                        if (!flag5)
{
                            int n = 0;
                            while (n < 255)
{
                                if (Main.player[n].active && !Main.player[n].dead && ((double)Main.player[n].position.Y < Main.worldSurface * 16.0 || (double)Main.spawnTileY > Main.worldSurface) && NPC.Spawner.CanSpawnEnemiesNear(Main.player[n]))
{
                                    if (SpecialSeedFeatures.Mechdusa)
{
                                        NPC.SpawnMechQueen(n);
                                        break;
                                    }
                                    if (WorldGen.spawnHardBoss == 1)
{
                                        NPC.SpawnOnPlayer(n, 134, 0f, 0f, 0f, 0f);
                                        break;
                                    }
                                    if (WorldGen.spawnHardBoss == 2)
{
                                        NPC.SpawnOnPlayer(n, 125, 0f, 0f, 0f, 0f);
                                        NPC.SpawnOnPlayer(n, 126, 0f, 0f, 0f, 0f);
                                        break;
                                    }
                                    if (WorldGen.spawnHardBoss == 3)
{
                                        NPC.SpawnOnPlayer(n, 127, 0f, 0f, 0f, 0f);
                                        break;
                                    }
                                    break;
                                }
                                else
{
                                    n++;
                                }
                            }
                        }
                        WorldGen.spawnHardBoss = 0;
                    }
                    if (Main.netMode != 1)
                    {
                        double num12 = 16200.0;
                        bool flag6 = num4 < num12 && Main.time >= num12;
                        bool flag7 = Main.raining;
                        if (flag6 && flag7 && (!NPC.downedDeerclops || Main.rand.Next(4) == 0))
{
                            for (int num13 = 0; num13 < 255; num13++)
{
                                Player player = Main.player[num13];
                                if (player.active && !player.dead && (double)player.position.Y < Main.worldSurface * 16.0 && player.ZoneSnow && player.townNPCs <= 0 && (player.statLifeMax2 >= 200 || player.statDefense >= 9) && NPC.Spawner.CanSpawnEnemiesNear(Main.player[num13]) && !NPC.AnyDanger(false, false))
{
                                    NPC.SpawnOnPlayer(num13, 668, 0f, 0f, 0f, 0f);
                                    break;
                                }
                            }
                        }
                    }
                }
                if (Main.time > 32400.0)
                {
                    Main.UpdateTime_StartDay(ref flag4);
                }
                Main.HandleMeteorFall();
            }
            else
            {
                WorldGen.spawnHardBoss = 0;
                WorldGen.spawnEye = false;
                Main.bloodMoon = false;
                Main.stopMoonEvent();
                if (Main.time > 54000.0)
                {
                    Main.UpdateTime_StartNight(ref flag4);
                }
                Main.UpdateTime_SpawnTownNPCs(false);
            }
            if (Main.dayTime)
            {
                Main.tileBlockLight[718] = false;
                return;
            }
            Main.tileBlockLight[718] = true;
        }
References Terraria.Graphics.Effects.EffectManager< T >.Activate(), Terraria.NPC.active, Terraria.Player.active, Terraria.NPC.AnyDanger(), Terraria.Main.AnyPlayerReadyToFightKingSlime(), Terraria.NPC.boss, Terraria.NPC.BusyWithAnyInvasionOfSorts(), Terraria.NPC.Spawner.CanSpawnEnemiesNear(), Terraria.Main.ChangeRain(), Microsoft.Xna.Framework.MathHelper.Clamp(), Terraria.Main.cloudBGActive, Terraria.Player.CollectTaxes(), Terraria.Main.dayRate, Terraria.Main.dayTime, Terraria.Graphics.Effects.EffectManager< T >.Deactivate(), Terraria.Player.dead, Terraria.Main.dedServ, Terraria.NPC.downedDeerclops, Terraria.NPC.downedSlimeKing, Terraria.GameContent.Creative.CreativePowers.ASharedTogglePower.Enabled, Terraria.Main.expertMode, Terraria.Player.FindClosest(), Terraria.Main.gameMenu, Terraria.Main.HandleMeteorFall(), Terraria.Main.hardMode, Terraria.NPC.homeless, Terraria.GameContent.Creative.CreativePowerManager.Instance, int, Terraria.Main.IsFastForwardingTime(), Terraria.Main.isThereAWorldSurface, Terraria.Main.ladyBugRainBoost, Terraria.GameContent.Events.LanternNight.LanternsUp, Terraria.WorldGen.Skyblock.lowTiles, Terraria.NPC.MaxMoonLordCountdown, Terraria.Main.maxNPCs, Terraria.Main.maxRaining, Terraria.Main.maxTilesX, Terraria.GameContent.SpecialSeedFeatures.Mechdusa, Terraria.NPC.MoonLordCountdown, Terraria.Main.myPlayer, Terraria.WorldGen.mysticLogsEvent, Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.GameContent.Events.LanternNight.NextNightIsLanternNight, Terraria.Main.npc, Terraria.Main.numClouds, Terraria.Main.oldMaxRaining, Terraria.Main.player, Terraria.Entity.position, Terraria.Main.pumpkinMoon, Terraria.Main.PylonSystem, Terraria.Main.raining, Terraria.Main.rainTime, Terraria.Main.rand, Terraria.Main.remixWorld, Terraria.Graphics.Effects.Filters.Scene, Terraria.NetMessage.SendData(), Terraria.Main.ShouldNormalEventsBeAbleToStart(), System.Math.Sin(), Terraria.Main.slimeRain, Terraria.Main.slimeRainTime, Terraria.Main.snowMoon, Terraria.WorldGen.spawnEye, Terraria.WorldGen.spawnHardBoss, Terraria.WorldGen.SpawnHomelessNPC(), Terraria.NPC.SpawnMechQueen(), Terraria.NPC.SpawnOnPlayer(), Terraria.Main.spawnTileY, Terraria.WorldGen.SpawnTravelNPC(), Terraria.Main.StartRain(), Terraria.Main.StartSlimeRain(), Terraria.Player.statDefense, Terraria.Player.statLifeMax, Terraria.Player.statLifeMax2, Terraria.Main.stopMoonEvent(), Terraria.Main.StopRain(), Terraria.Main.StopSlimeRain(), Terraria.NPC.taxCollector, Terraria.Player.taxRate, Terraria.Player.taxTimer, Terraria.Main.tileBlockLight, Terraria.Main.time, Terraria.NPC.townNPC, Terraria.Player.townNPCs, Terraria.NPC.travelNPC, Terraria.NPC.type, Terraria.WorldGen.UnspawnHomelessNPC(), Terraria.WorldGen.UnspawnTravelNPC(), Terraria.GameContent.TeleportPylonsSystem.Update(), Terraria.Main.UpdateSlimeRainWarning(), Terraria.GameContent.Events.BirthdayParty.UpdateTime(), Terraria.GameContent.Events.CreditsRollEvent.UpdateTime(), Terraria.GameContent.Events.CultistRitual.UpdateTime(), Terraria.GameContent.Events.DD2Event.UpdateTime(), Terraria.GameContent.Events.LanternNight.UpdateTime(), Terraria.GameContent.Events.MysticLogFairiesEvent.UpdateTime(), Terraria.GameContent.Events.Sandstorm.UpdateTime(), Terraria.Main.UpdateTime_SpawnTownNPCs(), Terraria.Main.UpdateTime_StartDay(), Terraria.Main.UpdateTime_StartNight(), Terraria.Main.UpdateTimeRate(), Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Main.worldSurface, Microsoft.Xna.Framework.Vector2.Y, and Terraria.Player.ZoneSnow.
Referenced by Terraria.Main.DoUpdateInWorld(), and Terraria.Main.UpdateMenu().