Terraria Decompiled: Terraria.Main.DrawNPCExtras
DrawNPCExtras()
void Terraria.Main.DrawNPCExtras (NPC n, bool beforeDraw, float addHeight, float addY, Microsoft::Xna::Framework::Color npcColor, Vector2 halfSize, SpriteEffects npcSpriteEffect, Vector2 screenPosition) inline protected
Definition at line 26019 of file Main.cs.
        {
            if (!beforeDraw && n.UsesPartyHat())
            {
                int num = n.frame.Y / n.frame.Height;
                int[] array = NPCID.Sets.TownNPCsFramingGroups[NPCID.Sets.NPCFramingGroup[n.type]];
                if (num >= array.Length)
                {
                    num = 0;
                }
                Texture2D value = TextureAssets.Extra[72].Value;
                int num2 = 0;
                switch (n.GetPartyHatColor())
                {
                case PartyHatColor.Pink:
                    num2 = 16;
                    break;
                case PartyHatColor.Cyan:
                    num2 = 17;
                    break;
                case PartyHatColor.Purple:
                    num2 = 18;
                    break;
                case PartyHatColor.White:
                    num2 = 19;
                    break;
                }
                Microsoft.Xna.Framework.Rectangle rectangle = value.Frame(20, 1, num2 % 20, 0, 0, 0);
                rectangle.Width -= 2;
                rectangle.Height -= 2;
                int num3 = 0;
                int num4 = 0;
                int num5 = n.spriteDirection;
                if (n.type == 663)
                {
                    num3 = 1;
                }
                if (n.type == 637)
                {
                    num3 = 6;
                    switch (num)
                    {
                    case 11:
                    case 12:
                    case 13:
                    case 14:
                    case 15:
                        num3 += 2;
                        break;
                    case 19:
                    case 22:
                    case 23:
                    case 24:
                    case 25:
                    case 26:
                    case 27:
                        num3 -= 2;
                        break;
                    }
                }
                if (n.type == 638)
                {
                    num3 = 12;
                }
                if (n.type == 656)
                {
                    num3 = 6;
                    if (num - 1 > 2)
                    {
                        if (num != 8)
{
                            if (num - 18 <= 7)
{
                                num3 -= 4;
                            }
                        }
                        else
{
                            num3 -= 2;
                        }
                    }
                    else
                    {
                        num3 -= 2;
                    }
                }
                int num6;
                if (NPCID.Sets.IsTownSlime[n.type])
                {
                    num5 *= -1;
                    num6 = n.type;
                    if (num6 != 670)
                    {
                        switch (num6)
{
                        case 679:
                            break;
                        default:
                            num3 = 1;
                            goto IL_01F7;
                        case 681:
                            num3 = -2;
                            goto IL_01F7;
                        case 682:
                            num3 = -1;
                            num4 = 2;
                            goto IL_01F7;
                        case 683:
                            num3 = -1;
                            num4 = -2;
                            goto IL_01F7;
                        case 684:
                            num3 = -4;
                            goto IL_01F7;
                        }
                    }
                    num3 = -1;
                }
                IL_01F7:
                if (n.IsShimmerVariant)
                {
                    num6 = n.type;
                    if (num6 > 124)
                    {
                        if (num6 <= 178)
{
                            if (num6 == 160)
{
                                num4 = -2;
                                goto IL_02A3;
                            }
                            if (num6 != 178)
{
                                goto IL_02A3;
                            }
                        }
                        else
{
                            if (num6 - 208 <= 1 || num6 == 227)
{
                                goto IL_029F;
                            }
                            if (num6 != 228)
{
                                goto IL_02A3;
                            }
                        }
                        num3 = -4;
                        num4 = -4;
                        goto IL_02A3;
                    }
                    if (num6 <= 54)
                    {
                        if (num6 == 38)
{
                            num3 += 2;
                            num4 = -2;
                            goto IL_02A3;
                        }
                        if (num6 != 54)
{
                            goto IL_02A3;
                        }
                        num4 = -6;
                        goto IL_02A3;
                    }
                    else
                    {
                        if (num6 == 107)
{
                            num3 = 2;
                            num4 = -6;
                            goto IL_02A3;
                        }
                        if (num6 != 108 && num6 != 124)
{
                            goto IL_02A3;
                        }
                    }
                    IL_029F:
                    num4 = -4;
                }
                IL_02A3:
                Vector2 vector = n.Bottom;
                Vector2 vector2 = -new Vector2(0f, (float)n.height) + new Vector2((float)(-2 * num5), n.gfxOffY);
                vector2.X += (float)(num3 * num5);
                vector2.Y += (float)array[num];
                vector2.Y += (float)num4;
                vector2.Y += (float)NPCID.Sets.HatOffsetY[n.type];
                int num7 = 0;
                if (n.ai[0] == 5f)
                {
                    num7 = -4;
                    if (n.type == 38)
                    {
                        num7 = -8;
                    }
                    if (n.type == 124)
                    {
                        num7 = -2;
                    }
                    if (n.type == 550)
                    {
                        num7 = -4;
                    }
                    if (n.type == 588)
                    {
                        num7 = -4;
                    }
                    if (n.type == 108 || n.type == 178)
                    {
                        num7 = -6;
                    }
                    if (n.type == 637)
                    {
                        num7 = -12;
                    }
                    if (n.type == 663)
                    {
                        num7 = -8;
                    }
                }
                vector2.Y += (float)num7;
                if (n.type == 229 && n.ai[0] == 12f)
                {
                    vector2.X -= (float)(num5 * 4);
                }
                if (n.type == 550 && n.ai[0] == 5f)
                {
                    vector2.X += (float)(num5 * 7);
                }
                Vector2 vector3 = rectangle.Size() - new Vector2((float)(rectangle.Width / 2), 12f);
                int num8 = 0;
                num6 = n.type;
                if (num6 <= 209)
                {
                    if (num6 <= 54)
                    {
                        if (num6 <= 22)
{
                            if (num6 - 17 > 3 && num6 != 22)
{
                                goto IL_05DF;
                            }
                            goto IL_05D1;
                        }
                        else if (num6 - 37 > 1 && num6 != 54)
{
                            goto IL_05DF;
                        }
                    }
                    else if (num6 <= 124)
                    {
                        if (num6 - 107 > 1)
{
                            if (num6 != 124)
{
                                goto IL_05DF;
                            }
                            goto IL_05D1;
                        }
                    }
                    else if (num6 != 160)
                    {
                        if (num6 == 178)
{
                            goto IL_05DC;
                        }
                        switch (num6)
{
                        case 207:
                        case 209:
                            break;
                        case 208:
                            goto IL_05DC;
                        default:
                            goto IL_05DF;
                        }
                    }
                    num8 = -3;
                    goto IL_05DF;
                }
                if (num6 <= 550)
                {
                    if (num6 <= 353)
                    {
                        switch (num6)
{
                        case 227:
                            num8 = -4;
                            goto IL_05DF;
                        case 228:
                            break;
                        case 229:
                            goto IL_05D1;
                        default:
                            if (num6 != 353)
{
                                goto IL_05DF;
                            }
                            goto IL_05D1;
                        }
                    }
                    else
                    {
                        if (num6 == 369)
{
                            goto IL_05DC;
                        }
                        if (num6 != 550)
{
                            goto IL_05DF;
                        }
                        num8 = -4;
                        goto IL_05DF;
                    }
                }
                else if (num6 <= 633)
                {
                    if (num6 == 588)
                    {
                        num8 = 0;
                        goto IL_05DF;
                    }
                    if (num6 != 633)
                    {
                        goto IL_05DF;
                    }
                    goto IL_05D1;
                }
                else
                {
                    if (num6 - 637 <= 1 || num6 == 656)
                    {
                        goto IL_05D1;
                    }
                    switch (num6)
                    {
                    case 670:
                    case 679:
                    case 680:
                    case 683:
                    case 684:
                        goto IL_05D1;
                    case 671:
                    case 672:
                    case 673:
                    case 674:
                    case 675:
                    case 676:
                    case 677:
                        goto IL_05DF;
                    case 678:
                    case 681:
                    case 682:
                        break;
                    default:
                        goto IL_05DF;
                    }
                }
                num8 = -2;
                goto IL_05DF;
                IL_05D1:
                num8 = -1;
                goto IL_05DF;
                IL_05DC:
                num8 = 1;
                IL_05DF:
                vector2.X += (float)(num8 * num5);
                vector2.X += (float)(4 * num5);
                vector2 *= n.scale;
                vector += vector2;
                SpriteEffects spriteEffects = npcSpriteEffect;
                if (NPCID.Sets.IsTownSlime[n.type])
                {
                    spriteEffects ^= SpriteEffects.FlipHorizontally;
                }
                float num9 = 1f;
                if (n.shimmerTransparency > 0f)
                {
                    num9 *= 1f - n.shimmerTransparency;
                }
                if (n.IsAPortraitDummy)
                {
                    if (n.scale == 2f)
                    {
                        vector.Y -= 4f;
                    }
                    if (n.scale == 3f)
                    {
                        vector.Y -= 8f;
                    }
                }
                vector -= screenPosition;
                Main.spriteBatch.Draw(value, vector, new Microsoft.Xna.Framework.Rectangle?(rectangle), npcColor * n.Opacity * num9, 0f, vector3, n.scale, spriteEffects, 0f);
            }
            if (!beforeDraw && n.type == 681)
            {
                Main.spriteBatch.Draw(TextureAssets.Extra[250].Value, new Vector2(n.position.X - screenPosition.X + (float)(n.width / 2) - (float)TextureAssets.Npc[n.type].Width() * n.scale / 2f + halfSize.X * n.scale, n.position.Y - screenPosition.Y + (float)n.height - (float)TextureAssets.Npc[n.type].Height() * n.scale / (float)Main.npcFrameCount[n.type] + 4f + halfSize.Y * n.scale + addHeight + addY + n.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(n.frame), n.GetAlpha(npcColor), n.rotation, halfSize, n.scale, npcSpriteEffect, 0f);
            }
            if (NPCID.Sets.AttackType[n.type] == 1 && n.ai[0] == 12f && !beforeDraw)
            {
                if (n.type == 228 || n.type == 229 || n.type == 209)
                {
                    return;
                }
                float num10 = n.ai[2];
                Vector2 vector4 = Main.OffsetsNPCOffhand[2];
                if (n.spriteDirection == 1)
                {
                    vector4.X *= -1f;
                }
                Vector2 vector5 = n.Bottom - vector4;
                if (n.type == 22 && n.ai[2] > -0.1f)
                {
                    vector5.Y += 4f;
                }
                if (n.type == 368 && Main.hardMode && n.ai[2] > -0.1f)
                {
                    vector5.Y += 4f;
                }
                if (n.type == 368 && !Main.hardMode && n.ai[2] < -0.1f)
                {
                    vector5.Y -= 8f;
                }
                float num11 = num10 * 1.5707964f * (float)n.spriteDirection;
                float num12 = 1f;
                int num13 = 0;
                int num14 = 4;
                if (n.type == 19)
                {
                    num13 = (Main.hardMode ? 98 : 95);
                    if (Main.hardMode)
                    {
                        vector5.X -= (float)(10 * n.direction);
                        vector5.Y += 4f;
                    }
                }
                else if (n.type == 22)
                {
                    num13 = 39;
                    num14 = 18;
                }
                else if (n.type == 178)
                {
                    num13 = 434;
                }
                else if (n.type == 227)
                {
                    num13 = 3350;
                    num14 = 16;
                    num12 = 0.85f;
                }
                else if (n.type == 368)
                {
                    num13 = (Main.hardMode ? 2223 : 2269);
                    if (Main.hardMode)
                    {
                        num14 = 18;
                    }
                    else
                    {
                        if (n.ai[2] < -0.1f)
{
                            num14 = 28;
                        }
                        num12 = 0.75f;
                    }
                }
                ref Vector2 ptr = Main.DrawPlayerItemPos(1f, num13);
                Texture2D texture2D;
                Microsoft.Xna.Framework.Rectangle rectangle2;
                Main.GetItemDrawFrame(num13, out texture2D, out rectangle2);
                int num15 = (int)ptr.X - num14;
                Vector2 vector6 = new Vector2((float)(-(float)num15), (float)(rectangle2.Height / 2));
                if (n.spriteDirection == -1)
                {
                    vector6 = new Vector2((float)(rectangle2.Width + num15), (float)(rectangle2.Height / 2));
                }
                Main.spriteBatch.Draw(texture2D, new Vector2((float)((int)(vector5.X - screenPosition.X)), (float)((int)(vector5.Y - screenPosition.Y))), new Microsoft.Xna.Framework.Rectangle?(rectangle2), npcColor, num11, vector6, n.scale * num12, npcSpriteEffect ^ SpriteEffects.FlipHorizontally, 0f);
                if (n.type == 22 && n.frame.Y / (TextureAssets.Npc[n.type].Height() / Main.npcFrameCount[n.type]) >= 21)
                {
                    Texture2D texture2D2 = TextureAssets.Extra[52].Value;
                    if (n.IsShimmerVariant)
                    {
                        texture2D2 = TextureAssets.Extra[264].Value;
                    }
                    Microsoft.Xna.Framework.Rectangle rectangle3 = texture2D2.Frame(1, 5, 0, n.frame.Y / (TextureAssets.Npc[n.type].Height() / Main.npcFrameCount[n.type]) - 21, 0, 0);
                    Main.spriteBatch.Draw(texture2D2, new Vector2(n.position.X - screenPosition.X + (float)(n.width / 2) - (float)TextureAssets.Npc[n.type].Width() * n.scale / 2f + halfSize.X * n.scale, n.position.Y - screenPosition.Y + (float)n.height - (float)TextureAssets.Npc[n.type].Height() * n.scale / (float)Main.npcFrameCount[n.type] + 4f + halfSize.Y * n.scale + addHeight + addY + n.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rectangle3), n.GetAlpha(npcColor), n.rotation, halfSize, n.scale, npcSpriteEffect, 0f);
                }
                else if (n.type == 368 && n.frame.Y / (TextureAssets.Npc[n.type].Height() / Main.npcFrameCount[n.type]) >= 21)
                {
                    Texture2D texture2D3 = TextureAssets.Extra[53].Value;
                    if (n.IsShimmerVariant)
                    {
                        texture2D3 = TextureAssets.Extra[265].Value;
                    }
                    Microsoft.Xna.Framework.Rectangle rectangle4 = texture2D3.Frame(1, 5, 0, n.frame.Y / (TextureAssets.Npc[n.type].Height() / Main.npcFrameCount[n.type]) - 21, 0, 0);
                    Main.spriteBatch.Draw(texture2D3, new Vector2(n.position.X - screenPosition.X + (float)(n.width / 2) - (float)TextureAssets.Npc[n.type].Width() * n.scale / 2f + halfSize.X * n.scale, n.position.Y - screenPosition.Y + (float)n.height - (float)TextureAssets.Npc[n.type].Height() * n.scale / (float)Main.npcFrameCount[n.type] + 4f + halfSize.Y * n.scale + addHeight + addY + n.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rectangle4), n.GetAlpha(npcColor), n.rotation, halfSize, n.scale, npcSpriteEffect, 0f);
                }
            }
            if (NPCID.Sets.AttackType[n.type] == 2 && (n.ai[0] == 14f || (n.ai[0] == 24f && n.frameCounter < 240.0)) && !beforeDraw)
            {
                Texture2D value2 = TextureAssets.Extra[51].Value;
                Vector2 vector7 = n.Bottom + new Vector2(0f, n.gfxOffY + 4f);
                Microsoft.Xna.Framework.Rectangle rectangle5 = value2.Frame(1, 4, 0, (int)n.frameCounter % 48 / 12, 0, 0);
                Vector2 vector8 = rectangle5.Size() * new Vector2(0.5f, 1f);
                Main.spriteBatch.Draw(value2, new Vector2((float)((int)(vector7.X - screenPosition.X)), (float)((int)(vector7.Y - screenPosition.Y))), new Microsoft.Xna.Framework.Rectangle?(rectangle5), n.GetMagicAuraColor(), 0f, vector8, n.scale, npcSpriteEffect ^ SpriteEffects.FlipHorizontally, 0f);
            }
            if (NPCID.Sets.AttackType[n.type] == 3 && n.ai[0] == 15f)
            {
                int num16 = 32;
                float num17 = 0f;
                Vector2 zero = Vector2.Zero;
                short num18 = 4;
                if (n.type == 207)
                {
                    num18 = 3349;
                    num17 = 0.15f;
                    if (beforeDraw)
                    {
                        return;
                    }
                    if (n.ai[1] > (float)NPCID.Sets.AttackTime[n.type] * 0.66f)
                    {
                        zero.Y = 12f;
                    }
                }
                else if (n.type == 353)
                {
                    num18 = 3352;
                    num17 = 0.15f;
                    if (!beforeDraw)
                    {
                        return;
                    }
                    if (n.ai[1] > (float)NPCID.Sets.AttackTime[n.type] * 0.66f)
                    {
                        zero.Y = 12f;
                    }
                }
                else if (n.type == 441)
                {
                    num18 = 3351;
                    num16 = 28;
                    num17 = 0.1f;
                    if (!beforeDraw)
                    {
                        return;
                    }
                    if (n.ai[1] > (float)NPCID.Sets.AttackTime[n.type] * 0.66f)
                    {
                        zero.Y = 12f;
                    }
                }
                Texture2D texture2D4;
                Microsoft.Xna.Framework.Rectangle rectangle6;
                Main.GetItemDrawFrame((int)num18, out texture2D4, out rectangle6);
                Tuple<Vector2, float> swingStats = n.GetSwingStats(NPCID.Sets.AttackTime[n.type] * 2, (int)n.ai[1], n.spriteDirection, num16, num16);
                Vector2 vector9 = swingStats.Item1 + (swingStats.Item1 - n.Center) * num17 + zero;
                Vector2 vector10 = rectangle6.Size() * new Vector2((float)((n.spriteDirection == 1) ? 0 : 1), 1f);
                Main.spriteBatch.Draw(texture2D4, new Vector2((float)((int)(vector9.X - screenPosition.X)), (float)((int)(vector9.Y - screenPosition.Y))), new Microsoft.Xna.Framework.Rectangle?(rectangle6), n.GetAlpha(npcColor), swingStats.Item2, vector10, n.scale, npcSpriteEffect ^ SpriteEffects.FlipHorizontally, 0f);
            }
            if (n.type == 550 && n.ai[0] == 18f)
            {
                if (beforeDraw)
                {
                    return;
                }
                Main.instance.LoadItem(353);
                Texture2D value3 = TextureAssets.Item[353].Value;
                int num19 = 32;
                float num20 = 0.15f;
                Vector2 zero2 = Vector2.Zero;
                Microsoft.Xna.Framework.Rectangle rectangle7 = value3.Frame(1, 3, 0, 1, 0, 0);
                int num21 = (int)n.ai[2];
                if (num21 >= 0 && num21 < 255)
                {
                    Player player = Main.player[num21];
                    bool flag = player.HeldItem.type == 353 && player.direction == Math.Sign(n.Center.X - player.Center.X);
                    float num22 = player.Hitbox.Distance(n.Center);
                    float num23 = n.localAI[3];
                    if (num22 < 46f && flag)
                    {
                        n.localAI[3] = 1f;
                        if (n.localAI[3] != num23)
{
                            Vector2 vector11 = n.Center + new Vector2((float)(n.spriteDirection * 30), -6f);
                            Vector2 vector12 = new Vector2(10f, 10f);
                            for (int i = 0; i < 30; i++)
{
                                Dust dust = Dust.NewDustDirect(vector11 - vector12 / 2f, (int)vector12.X, (int)vector12.Y, 4, 0f, 0f, 50, new Microsoft.Xna.Framework.Color(245, 200, 30, 155), 0.7f);
                                dust.noGravity = true;
                                dust.velocity *= 1f;
                                Dust.NewDustDirect(vector11 - vector12 / 2f, (int)vector12.X, (int)vector12.Y, 4, 0f, 0f, 50, new Microsoft.Xna.Framework.Color(245, 200, 30, 155), 0.6f).velocity *= 2f;
                            }
                        }
                    }
                    else if (n.localAI[3] == 1f)
                    {
                        n.localAI[3] = 2f;
                    }
                }
                Tuple<Vector2, float> swingStats2 = n.GetSwingStats(40, 12, n.spriteDirection, num19, num19);
                Vector2 vector13 = swingStats2.Item1 + (swingStats2.Item1 - n.Center) * num20 + zero2;
                Vector2 vector14 = rectangle7.Size() * new Vector2((float)((n.spriteDirection == 1) ? 0 : 1), 1f);
                Main.spriteBatch.Draw(value3, new Vector2((float)((int)(vector13.X - screenPosition.X)), (float)((int)(vector13.Y - screenPosition.Y))), new Microsoft.Xna.Framework.Rectangle?(rectangle7), n.GetAlpha(npcColor), swingStats2.Item2, vector14, n.scale, npcSpriteEffect ^ SpriteEffects.FlipHorizontally, 0f);
            }
            if (!beforeDraw && n.ai[0] == 23f)
            {
                int num24 = (int)n.ai[2];
                if (num24 <= 0 || num24 > (int)ItemID.Count)
                {
                    return;
                }
                Texture2D texture2D5;
                Microsoft.Xna.Framework.Rectangle rectangle8;
                Main.GetItemDrawFrame(num24, out texture2D5, out rectangle8);
                int num25;
                if ((int)n.frameCounter < 6)
                {
                    num25 = 1;
                }
                else
                {
                    num25 = 2;
                }
                if (n.ai[1] < 6f)
                {
                    num25 = 1;
                }
                if (num25 == 0)
                {
                    return;
                }
                Vector2 zero3 = Vector2.Zero;
                if (num25 == 1)
                {
                    zero3 = new Vector2(10f, 6f);
                }
                if (num25 == 2)
                {
                    zero3 = new Vector2(16f, 0f);
                }
                if ((npcSpriteEffect & SpriteEffects.FlipHorizontally) == SpriteEffects.None)
                {
                    zero3.X *= -1f;
                }
                if (n.type == 369)
                {
                    zero3.X *= 0.5f;
                    zero3.Y += 4f;
                }
                if (n.type == 453)
                {
                    zero3.Y += 8f;
                }
                if (n.type == 550)
                {
                    if (num24 == 353)
                    {
                        rectangle8 = texture2D5.Frame(1, 3, 0, 1, 0, 0);
                    }
                    zero3.Y += 6f;
                }
                Vector2 vector15 = n.Center + zero3;
                Vector2 vector16 = rectangle8.Size() * new Vector2((float)((n.spriteDirection == 1) ? 0 : 1), 1f);
                Vector2 vector17 = new Vector2((float)((int)(vector15.X - screenPosition.X)), (float)((int)(vector15.Y - screenPosition.Y)));
                Microsoft.Xna.Framework.Color alpha = n.GetAlpha(npcColor);
                Main.spriteBatch.Draw(texture2D5, vector17, new Microsoft.Xna.Framework.Rectangle?(rectangle8), alpha, 0f, vector16, n.scale, npcSpriteEffect ^ SpriteEffects.FlipHorizontally, 0f);
            }
        }
References Terraria.NPC.ai, System.array, Terraria.ID.NPCID.Sets.AttackTime, Terraria.ID.NPCID.Sets.AttackType, Terraria.Entity.Bottom, Terraria.Entity.Center, Terraria.ID.ItemID.Count, Terraria.Entity.direction, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Main.DrawPlayerItemPos(), Terraria.GameContent.TextureAssets.Extra, Terraria.NPC.frame, Terraria.NPC.frameCounter, Terraria.NPC.GetAlpha(), Terraria.Main.GetItemDrawFrame(), Terraria.NPC.GetMagicAuraColor(), Terraria.NPC.GetPartyHatColor(), Terraria.NPC.GetSwingStats(), Terraria.NPC.gfxOffY, Terraria.Main.hardMode, Terraria.ID.NPCID.Sets.HatOffsetY, Microsoft.Xna.Framework.Rectangle.Height, Terraria.Entity.height, Terraria.Entity.Hitbox, Terraria.Main.instance, int, Terraria.NPC.IsAPortraitDummy, Terraria.NPC.IsShimmerVariant, Terraria.ID.NPCID.Sets.IsTownSlime, Terraria.GameContent.TextureAssets.Item, System.Tuple< T1, T2, T3, T4, T5, T6, T7, TRest >.Item2, Terraria.Main.LoadItem(), Terraria.NPC.localAI, Terraria.Dust.NewDustDirect(), Terraria.GameContent.TextureAssets.Npc, Terraria.Main.npcFrameCount, Terraria.ID.NPCID.Sets.NPCFramingGroup, Terraria.Main.OffsetsNPCOffhand, Terraria.Main.player, Terraria.Entity.position, Terraria.NPC.rotation, Terraria.NPC.scale, Terraria.NPC.shimmerTransparency, System.Math.Sign(), Terraria.Main.spriteBatch, Terraria.NPC.spriteDirection, Terraria.ID.NPCID.Sets.TownNPCsFramingGroups, Terraria.NPC.type, Terraria.NPC.UsesPartyHat(), System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Dust.velocity, Microsoft.Xna.Framework.Rectangle.Width, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Rectangle.Y, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.