Terraria Decompiled: Terraria.Main.DrawProj_FishingLine
DrawProj_FishingLine()
static void Terraria.Main.DrawProj_FishingLine (Projectile proj, Player theOwner, ref float polePosX, ref float polePosY, Vector2 mountedCenter) inline static private
Definition at line 34810 of file Main.cs.
        {
            polePosX = mountedCenter.X;
            polePosY = mountedCenter.Y;
            if (theOwner.mount.Active)
            {
                if (theOwner.mount.Type == 52)
                {
                    polePosX -= (float)(theOwner.direction * 14);
                    polePosY -= -10f;
                }
                theOwner.ApplyItemPositionOffsetFromMount(ref mountedCenter);
                polePosX = mountedCenter.X;
                polePosY = mountedCenter.Y;
            }
            polePosY += theOwner.gfxOffY;
            int type = theOwner.inventory[theOwner.selectedItem].type;
            Microsoft.Xna.Framework.Color color = new Microsoft.Xna.Framework.Color(200, 200, 200, 100);
            if (type == 2294)
            {
                color = new Microsoft.Xna.Framework.Color(100, 180, 230, 100);
            }
            if (type == 2295)
            {
                color = new Microsoft.Xna.Framework.Color(250, 90, 70, 100);
            }
            if (type == 2293)
            {
                color = new Microsoft.Xna.Framework.Color(203, 190, 210, 100);
            }
            if (type == 2421)
            {
                color = new Microsoft.Xna.Framework.Color(183, 77, 112, 100);
            }
            if (type == 2422)
            {
                color = new Microsoft.Xna.Framework.Color(255, 226, 116, 100);
            }
            if (type == 4325)
            {
                color = new Microsoft.Xna.Framework.Color(200, 100, 100, 100);
            }
            if (type == 4442)
            {
                color = new Microsoft.Xna.Framework.Color(100, 100, 200, 100);
            }
            color = Main.TryApplyingPlayerStringColor(theOwner.stringColor, color);
            float gravDir = theOwner.gravDir;
            if (type == 2289)
            {
                polePosX += (float)(43 * theOwner.direction);
                if (theOwner.direction < 0)
                {
                    polePosX -= 13f;
                }
                polePosY -= 36f * gravDir;
            }
            else if (type == 2291)
            {
                polePosX += (float)(43 * theOwner.direction);
                if (theOwner.direction < 0)
                {
                    polePosX -= 13f;
                }
                polePosY -= 34f * gravDir;
            }
            else if (type == 2292)
            {
                polePosX += (float)(46 * theOwner.direction);
                if (theOwner.direction < 0)
                {
                    polePosX -= 13f;
                }
                polePosY -= 34f * gravDir;
            }
            else if (type == 2293)
            {
                polePosX += (float)(43 * theOwner.direction);
                if (theOwner.direction < 0)
                {
                    polePosX -= 13f;
                }
                polePosY -= 34f * gravDir;
            }
            else if (type == 2294)
            {
                polePosX += (float)(43 * theOwner.direction);
                if (theOwner.direction < 0)
                {
                    polePosX -= 13f;
                }
                polePosY -= 30f * gravDir;
            }
            else if (type == 2295)
            {
                polePosX += (float)(43 * theOwner.direction);
                if (theOwner.direction < 0)
                {
                    polePosX -= 13f;
                }
                polePosY -= 30f * gravDir;
            }
            else if (type == 2296)
            {
                polePosX += (float)(43 * theOwner.direction);
                if (theOwner.direction < 0)
                {
                    polePosX -= 13f;
                }
                polePosY -= 30f * gravDir;
            }
            else if (type == 2421)
            {
                polePosX += (float)(47 * theOwner.direction);
                if (theOwner.direction < 0)
                {
                    polePosX -= 13f;
                }
                polePosY -= 36f * gravDir;
            }
            else if (type == 2422)
            {
                polePosX += (float)(47 * theOwner.direction);
                if (theOwner.direction < 0)
                {
                    polePosX -= 13f;
                }
                polePosY -= 32f * gravDir;
            }
            else if (type == 4325)
            {
                polePosX += (float)(44 * theOwner.direction);
                if (theOwner.direction < 0)
                {
                    polePosX -= 13f;
                }
                polePosY -= 32f * gravDir;
            }
            else if (type == 4442)
            {
                polePosX += (float)(44 * theOwner.direction);
                if (theOwner.direction < 0)
                {
                    polePosX -= 13f;
                }
                polePosY -= 32f * gravDir;
            }
            if (gravDir == -1f)
            {
                polePosY -= 12f;
            }
            Vector2 vector = new Vector2(polePosX, polePosY);
            vector = theOwner.RotatedRelativePoint(vector + new Vector2(8f), false, true) - new Vector2(8f);
            float num = proj.position.X + (float)proj.width * 0.5f - vector.X;
            float num2 = proj.position.Y + (float)proj.height * 0.5f - vector.Y;
            Math.Sqrt((double)(num * num + num2 * num2));
            float num3 = (float)Math.Atan2((double)num2, (double)num) - 1.57f;
            bool flag = true;
            if (num == 0f && num2 == 0f)
            {
                flag = false;
            }
            else
            {
                float num4 = (float)Math.Sqrt((double)(num * num + num2 * num2));
                num4 = 12f / num4;
                num *= num4;
                num2 *= num4;
                vector.X -= num;
                vector.Y -= num2;
                num = proj.position.X + (float)proj.width * 0.5f - vector.X;
                num2 = proj.position.Y + (float)proj.height * 0.5f - vector.Y;
            }
            while (flag)
            {
                float num5 = 12f;
                float num6 = (float)Math.Sqrt((double)(num * num + num2 * num2));
                float num7 = num6;
                if (float.IsNaN(num6) || float.IsNaN(num7))
                {
                    flag = false;
                }
                else
                {
                    if (num6 < 20f)
                    {
                        num5 = num6 - 8f;
                        flag = false;
                    }
                    num6 = 12f / num6;
                    num *= num6;
                    num2 *= num6;
                    vector.X += num;
                    vector.Y += num2;
                    num = proj.position.X + (float)proj.width * 0.5f - vector.X;
                    num2 = proj.position.Y + (float)proj.height * 0.1f - vector.Y;
                    if (num7 > 12f)
                    {
                        float num8 = 0.3f;
                        float num9 = Math.Abs(proj.velocity.X) + Math.Abs(proj.velocity.Y);
                        if (num9 > 16f)
{
                            num9 = 16f;
                        }
                        num9 = 1f - num9 / 16f;
                        num8 *= num9;
                        num9 = num7 / 80f;
                        if (num9 > 1f)
{
                            num9 = 1f;
                        }
                        num8 *= num9;
                        if (num8 < 0f)
{
                            num8 = 0f;
                        }
                        num9 = 1f - proj.localAI[0] / 100f;
                        num8 *= num9;
                        if (num2 > 0f)
{
                            num2 *= 1f + num8;
                            num *= 1f - num8;
                        }
                        else
{
                            num9 = Math.Abs(proj.velocity.X) / 3f;
                            if (num9 > 1f)
{
                                num9 = 1f;
                            }
                            num9 -= 0.5f;
                            num8 *= num9;
                            if (num8 > 0f)
{
                                num8 *= 2f;
                            }
                            num2 *= 1f + num8;
                            num *= 1f - num8;
                        }
                    }
                    num3 = (float)Math.Atan2((double)num2, (double)num) - 1.57f;
                    Microsoft.Xna.Framework.Color color2 = Lighting.GetColor((int)vector.X / 16, (int)(vector.Y / 16f), color);
                    if (theOwner.stringColor == 29)
                    {
                        color2 = color;
                    }
                    Main.EntitySpriteDraw(TextureAssets.FishingLine.Value, new Vector2(vector.X - Main.screenPosition.X + (float)TextureAssets.FishingLine.Width() * 0.5f, vector.Y - Main.screenPosition.Y + (float)TextureAssets.FishingLine.Height() * 0.5f), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.FishingLine.Width(), (int)num5)), color2, num3, new Vector2((float)TextureAssets.FishingLine.Width() * 0.5f, 0f), 1f, SpriteEffects.None, 0f);
                }
            }
        }
References System.Math.Abs(), Terraria.Mount.Active, Terraria.Player.ApplyItemPositionOffsetFromMount(), System.Math.Atan2(), Terraria.Entity.direction, Terraria.Main.EntitySpriteDraw(), Terraria.GameContent.TextureAssets.FishingLine, Terraria.Lighting.GetColor(), Terraria.Player.gfxOffY, Terraria.Player.gravDir, Terraria.Entity.height, int, Terraria.Player.inventory, Terraria.Projectile.localAI, Terraria.Player.mount, Terraria.Player.RotatedRelativePoint(), Terraria.Main.screenPosition, Terraria.Player.selectedItem, System.Math.Sqrt(), Terraria.Player.stringColor, Terraria.Main.TryApplyingPlayerStringColor(), Terraria.Item.type, Terraria.Mount.Type, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Entity.velocity, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Main.DrawProjDirect().