Terraria Decompiled: Terraria.Main.GetRecipeRequirementsText
GetRecipeRequirementsText()
static string Terraria.Main.GetRecipeRequirementsText (Recipe recipe, bool explicitNone) inline static
Definition at line 42152 of file Main.cs.
        {
            Main._requiredObjectsForCraftingText.Clear();
            if (recipe.requiredTile >= 0)
            {
                Main._requiredObjectsForCraftingText.Add(Recipe.GetRequiredTileName(recipe.requiredTile));
            }
            if (recipe.needWater)
            {
                Main._requiredObjectsForCraftingText.Add(Lang.inter[53].Value);
            }
            if (recipe.needHoney)
            {
                Main._requiredObjectsForCraftingText.Add(Lang.inter[58].Value);
            }
            if (recipe.needLava)
            {
                Main._requiredObjectsForCraftingText.Add(Lang.inter[56].Value);
            }
            if (recipe.needSnowBiome)
            {
                Main._requiredObjectsForCraftingText.Add(Lang.inter[123].Value);
            }
            if (recipe.needGraveyardBiome)
            {
                Main._requiredObjectsForCraftingText.Add(Lang.inter[124].Value);
            }
            if (recipe.needTorchGodsFavor)
            {
                Main._requiredObjectsForCraftingText.Add(Lang.inter[125].Value);
            }
            if (explicitNone && Main._requiredObjectsForCraftingText.Count == 0)
            {
                string value = Lang.inter[23].Value;
                Main._requiredObjectsForCraftingText.Add(value);
            }
            string value2 = Lang.inter[22].Value;
            string text = string.Join(", ", Main._requiredObjectsForCraftingText);
            return value2 + " " + text;
        }
References Terraria.Main._requiredObjectsForCraftingText, System.Collections.Generic.List< T >.Add(), System.Collections.Generic.List< T >.Clear(), System.Collections.Generic.List< T >.Count, Terraria.Recipe.GetRequiredTileName(), Terraria.Lang.inter, Terraria.Recipe.needGraveyardBiome, Terraria.Recipe.needHoney, Terraria.Recipe.needLava, Terraria.Recipe.needSnowBiome, Terraria.Recipe.needTorchGodsFavor, Terraria.Recipe.needWater, Terraria.Recipe.requiredTile, System.text, System.value, and Terraria.Localization.LocalizedText.Value.
Referenced by Terraria.GameContent.UI.NewCraftingUI.DrawChildren(), and Terraria.Main.DrawGuideCraftText().