Terraria Decompiled: Terraria.Main.SaveRecent
SaveRecent()
static void Terraria.Main.SaveRecent () inline static
Definition at line 2144 of file Main.cs.
        {
            Utils.TryCreatingDirectory(Main.SavePath);
            try
            {
                File.SetAttributes(Main.SavePath + Path.DirectorySeparatorChar.ToString() + "servers.dat", FileAttributes.Normal);
            }
            catch
            {
            }
            try
            {
                using (FileStream fileStream = new FileStream(Main.SavePath + Path.DirectorySeparatorChar.ToString() + "servers.dat", FileMode.Create))
                {
                    using (BinaryWriter binaryWriter = new BinaryWriter(fileStream))
                    {
                        binaryWriter.Write(319);
                        for (int i = 0; i < 10; i++)
{
                            binaryWriter.Write(Main.recentWorld[i]);
                            binaryWriter.Write(Main.recentIP[i]);
                            binaryWriter.Write(Main.recentPort[i]);
                        }
                    }
                }
            }
            catch
            {
            }
        }
References System.IO.Path.DirectorySeparatorChar, Terraria.Main.recentIP, Terraria.Main.recentPort, Terraria.Main.recentWorld, Terraria.Main.SavePath, System.IO.File.SetAttributes(), Terraria.Utils.TryCreatingDirectory(), and System.IO.BinaryWriter.Write().
Referenced by Terraria.Netplay.AddCurrentServerToRecentList().