Terraria Decompiled: Terraria.Main.DoUpdate_HandleChat
DoUpdate_HandleChat()
static void Terraria.Main.DoUpdate_HandleChat () inline static private
Definition at line 16744 of file Main.cs.
        {
            if (Main.CurrentInputTextTakerOverride != null)
            {
                Main.drawingPlayerChat = false;
                return;
            }
            if (Main.editSign)
            {
                Main.drawingPlayerChat = false;
            }
            if (PlayerInput.UsingGamepad)
            {
                Main.drawingPlayerChat = false;
            }
            if (!Main.drawingPlayerChat)
            {
                Main.chatMonitor.ResetOffset();
                return;
            }
            if (!Main.imeCompositionActive)
            {
                int num = 0;
                if (Main.keyState.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.Up))
                {
                    num = 1;
                }
                else if (Main.keyState.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.Down))
                {
                    num = -1;
                }
                Main.chatMonitor.Offset(num);
            }
            if (Main.inputTextEscape && !Main.imeCompositionActive)
            {
                Main.drawingPlayerChat = false;
            }
            string text = Main.chatText;
            Main.chatText = Main.GetInputText(Main.chatText, false);
            if (text != Main.chatText)
            {
                int num2 = Main.ChatLineWidthLimit - 10;
                for (float num3 = ChatManager.GetStringSize(FontAssets.MouseText.Value, Main.chatText, Vector2.One, -1f).X; num3 > (float)num2; num3 = ChatManager.GetStringSize(FontAssets.MouseText.Value, Main.chatText, Vector2.One, -1f).X)
                {
                    int num4 = Math.Max(0, (int)(num3 - (float)num2) / 100);
                    Main.chatText = Utils.TrimUserString(Main.chatText, Main.chatText.Length - 1 - num4);
                }
            }
            if (text != Main.chatText)
            {
                SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
            }
            if (Main.inputTextEnter && Main.chatRelease)
            {
                if (Main.chatText != "" && !ChatManager.DebugCommands.Process((byte)Main.myPlayer, Main.chatText))
                {
                    ChatMessage chatMessage = ChatManager.Commands.CreateOutgoingMessage(Main.chatText);
                    if (Main.netMode == 1)
                    {
                        ChatHelper.SendChatMessageFromClient(chatMessage);
                    }
                    else if (Main.netMode == 0)
                    {
                        ChatManager.Commands.ProcessIncomingMessage(chatMessage, Main.myPlayer);
                    }
                }
                Main.chatText = "";
                Main.ClosePlayerChat();
                Main.chatRelease = false;
                SoundEngine.PlaySound(11, -1, -1, 1, 1f, 0f);
            }
        }
References Terraria.Main.chatMonitor, Terraria.Main.chatRelease, Terraria.Main.chatText, Terraria.Main.ClosePlayerChat(), Terraria.UI.Chat.ChatManager.Commands, Terraria.Chat.ChatCommandProcessor.CreateOutgoingMessage(), Terraria.Main.CurrentInputTextTakerOverride, Terraria.UI.Chat.ChatManager.DebugCommands, Terraria.Main.drawingPlayerChat, Terraria.Main.editSign, Terraria.Main.GetInputText(), Terraria.UI.Chat.ChatManager.GetStringSize(), Terraria.Main.imeCompositionActive, Terraria.Main.inputTextEnter, Terraria.Main.inputTextEscape, Microsoft.Xna.Framework.Input.KeyboardState.IsKeyDown(), Terraria.Main.keyState, System.Math.Max(), Terraria.GameContent.FontAssets.MouseText, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.GameContent.UI.Chat.IChatMonitor.Offset(), Microsoft.Xna.Framework.Vector2.One, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Chat.ChatCommandProcessor.ProcessIncomingMessage(), Terraria.GameContent.UI.Chat.IChatMonitor.ResetOffset(), Terraria.Chat.ChatHelper.SendChatMessageFromClient(), System.text, Terraria.Utils.TrimUserString(), Terraria.GameInput.PlayerInput.UsingGamepad, ReLogic.Content.Asset< T >.Value, and Microsoft.Xna.Framework.Vector2.X.
Referenced by Terraria.Main.DoUpdate().