Terraria Decompiled: Terraria.Main.DrawNPCDirect
DrawNPCDirect()
void Terraria.Main.DrawNPCDirect (SpriteBatch mySpriteBatch, NPC rCurrentNPC, bool behindTiles, Vector2 screenPos) inline
Definition at line 21405 of file Main.cs.
        {
            int type = rCurrentNPC.type;
            rCurrentNPC.SetFrameSize();
            if (rCurrentNPC.realLife == -1 && rCurrentNPC.life >= rCurrentNPC.lifeMax && !rCurrentNPC.boss)
            {
                bool flag = Lighting.GetColor((int)((double)rCurrentNPC.position.X + (double)rCurrentNPC.width * 0.5) / 16, (int)(((double)rCurrentNPC.position.Y + (double)rCurrentNPC.height * 0.5) / 16.0)).ToVector3().Length() > 0.4325f;
                bool flag2 = false;
                if (LockOnHelper.AimedTarget == rCurrentNPC)
                {
                    flag2 = true;
                }
                else if (rCurrentNPC.Distance(Main.player[Main.myPlayer].Center) < 350f && flag)
                {
                    flag2 = true;
                }
                if (flag2 && rCurrentNPC.lifeMax < 5)
                {
                    flag2 = false;
                }
                if (flag2 && rCurrentNPC.aiStyle == 25 && rCurrentNPC.ai[0] == 0f)
                {
                    flag2 = false;
                }
                if (flag2)
                {
                    rCurrentNPC.nameOver = MathHelper.Clamp(rCurrentNPC.nameOver + 0.025f, 0f, 1f);
                }
                else
                {
                    rCurrentNPC.nameOver = MathHelper.Clamp(rCurrentNPC.nameOver - 0.025f, 0f, 1f);
                }
            }
            else
            {
                rCurrentNPC.nameOver = MathHelper.Clamp(rCurrentNPC.nameOver - 0.025f, 0f, 1f);
            }
            if (type == 1 && rCurrentNPC.ai[0] == -999f)
            {
                return;
            }
            if (type == 101)
            {
                bool flag3 = true;
                Vector2 vector = new Vector2(rCurrentNPC.position.X + (float)(rCurrentNPC.width / 2), rCurrentNPC.position.Y + (float)(rCurrentNPC.height / 2));
                float num = rCurrentNPC.ai[0] * 16f + 8f - vector.X;
                float num2 = rCurrentNPC.ai[1] * 16f + 8f - vector.Y;
                float num3 = (float)Math.Atan2((double)num2, (double)num) - 1.57f;
                bool flag4 = true;
                while (flag4)
                {
                    float num4 = 0.75f;
                    int num5 = 28;
                    float num6 = (float)Math.Sqrt((double)(num * num + num2 * num2));
                    if (num6 < 28f * num4)
                    {
                        num5 = (int)num6 - 40 + 28;
                        flag4 = false;
                    }
                    num6 = 20f * num4 / num6;
                    num *= num6;
                    num2 *= num6;
                    vector.X += num;
                    vector.Y += num2;
                    num = rCurrentNPC.ai[0] * 16f + 8f - vector.X;
                    num2 = rCurrentNPC.ai[1] * 16f + 8f - vector.Y;
                    Microsoft.Xna.Framework.Color color = Lighting.GetColor((int)vector.X / 16, (int)(vector.Y / 16f));
                    if (rCurrentNPC.IsABestiaryIconDummy)
                    {
                        color = rCurrentNPC.GetBestiaryEntryColor();
                    }
                    if (!flag3)
                    {
                        flag3 = true;
                        mySpriteBatch.Draw(TextureAssets.Chain10.Value, new Vector2(vector.X - screenPos.X, vector.Y - screenPos.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain10.Width(), num5)), color, num3, new Vector2((float)TextureAssets.Chain10.Width() * 0.5f, (float)TextureAssets.Chain10.Height() * 0.5f), num4, SpriteEffects.None, 0f);
                    }
                    else
                    {
                        flag3 = false;
                        mySpriteBatch.Draw(TextureAssets.Chain11.Value, new Vector2(vector.X - screenPos.X, vector.Y - screenPos.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain10.Width(), num5)), color, num3, new Vector2((float)TextureAssets.Chain10.Width() * 0.5f, (float)TextureAssets.Chain10.Height() * 0.5f), num4, SpriteEffects.None, 0f);
                    }
                }
            }
            else if (rCurrentNPC.aiStyle == 13)
            {
                Vector2 vector2 = new Vector2(rCurrentNPC.position.X + (float)(rCurrentNPC.width / 2), rCurrentNPC.position.Y + (float)(rCurrentNPC.height / 2));
                float num7 = rCurrentNPC.ai[0] * 16f + 8f - vector2.X;
                float num8 = rCurrentNPC.ai[1] * 16f + 8f - vector2.Y;
                float num9 = (float)Math.Atan2((double)num8, (double)num7) - 1.57f;
                bool flag5 = true;
                while (flag5)
                {
                    int num10 = 28;
                    int num11 = 40;
                    if (type == 259 || type == 260)
                    {
                        num11 = 20;
                        num10 = 12;
                    }
                    float num12 = (float)Math.Sqrt((double)(num7 * num7 + num8 * num8));
                    if (num12 < (float)num11)
                    {
                        num10 = (int)num12 - num11 + num10;
                        flag5 = false;
                    }
                    num12 = (float)num10 / num12;
                    num7 *= num12;
                    num8 *= num12;
                    vector2.X += num7;
                    vector2.Y += num8;
                    num7 = rCurrentNPC.ai[0] * 16f + 8f - vector2.X;
                    num8 = rCurrentNPC.ai[1] * 16f + 8f - vector2.Y;
                    Microsoft.Xna.Framework.Color color2 = Lighting.GetColor((int)vector2.X / 16, (int)(vector2.Y / 16f));
                    if (rCurrentNPC.IsABestiaryIconDummy)
                    {
                        color2 = rCurrentNPC.GetBestiaryEntryColor();
                    }
                    if (type == 259 || type == 260)
                    {
                        color2.B = byte.MaxValue;
                        if (color2.R < 100)
{
                            color2.R = 100;
                        }
                        if (color2.G < 150)
{
                            color2.G = 150;
                        }
                    }
                    if (type == 56)
                    {
                        mySpriteBatch.Draw(TextureAssets.Chain5.Value, new Vector2(vector2.X - screenPos.X, vector2.Y - screenPos.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain4.Width(), num10)), color2, num9, new Vector2((float)TextureAssets.Chain4.Width() * 0.5f, (float)TextureAssets.Chain4.Height() * 0.5f), 1f, SpriteEffects.None, 0f);
                    }
                    else if (type == 175)
                    {
                        mySpriteBatch.Draw(TextureAssets.Chain14.Value, new Vector2(vector2.X - screenPos.X, vector2.Y - screenPos.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain14.Width(), num10)), color2, num9, new Vector2((float)TextureAssets.Chain14.Width() * 0.5f, (float)TextureAssets.Chain14.Height() * 0.5f), 1f, SpriteEffects.None, 0f);
                    }
                    else if (type == 259)
                    {
                        mySpriteBatch.Draw(TextureAssets.Chain24.Value, new Vector2(vector2.X - screenPos.X, vector2.Y - screenPos.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain24.Width(), num10)), color2, num9, new Vector2((float)TextureAssets.Chain24.Width() * 0.5f, (float)TextureAssets.Chain24.Height() * 0.5f), 1f, SpriteEffects.None, 0f);
                    }
                    else if (type == 260)
                    {
                        mySpriteBatch.Draw(TextureAssets.Chain25.Value, new Vector2(vector2.X - screenPos.X, vector2.Y - screenPos.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain25.Width(), num10)), color2, num9, new Vector2((float)TextureAssets.Chain25.Width() * 0.5f, (float)TextureAssets.Chain25.Height() * 0.5f), 1f, SpriteEffects.None, 0f);
                    }
                    else
                    {
                        mySpriteBatch.Draw(TextureAssets.Chain4.Value, new Vector2(vector2.X - screenPos.X, vector2.Y - screenPos.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain4.Width(), num10)), color2, num9, new Vector2((float)TextureAssets.Chain4.Width() * 0.5f, (float)TextureAssets.Chain4.Height() * 0.5f), 1f, SpriteEffects.None, 0f);
                    }
                }
            }
            if (type == 327)
            {
                float num13 = 0f;
                Vector2 vector3 = new Vector2(rCurrentNPC.Center.X, rCurrentNPC.Center.Y + 80f);
                int num14 = (int)rCurrentNPC.localAI[1];
                Microsoft.Xna.Framework.Color color3 = ((!rCurrentNPC.IsABestiaryIconDummy) ? Lighting.GetColor((int)vector3.X / 16, (int)(vector3.Y / 16f)) : rCurrentNPC.GetBestiaryEntryColor());
                mySpriteBatch.Draw(TextureAssets.PumpkingCloak.Value, new Vector2(vector3.X - screenPos.X, vector3.Y - screenPos.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, TextureAssets.PumpkingCloak.Height() / 5 * num14, TextureAssets.PumpkingCloak.Width(), TextureAssets.PumpkingCloak.Height() / 5)), color3, num13, new Vector2((float)TextureAssets.PumpkingCloak.Width() * 0.5f, (float)TextureAssets.PumpkingCloak.Height() * 0.5f / 5f), 1f, SpriteEffects.None, 0f);
            }
            if (type == 328)
            {
                Vector2 vector4 = new Vector2(rCurrentNPC.position.X + (float)rCurrentNPC.width * 0.5f - 5f * rCurrentNPC.ai[0], rCurrentNPC.position.Y + 20f);
                for (int i = 0; i < 2; i++)
                {
                    float num15 = Main.npc[(int)rCurrentNPC.ai[1]].position.X + (float)(Main.npc[(int)rCurrentNPC.ai[1]].width / 2) - vector4.X;
                    float num16 = Main.npc[(int)rCurrentNPC.ai[1]].position.Y + (float)(Main.npc[(int)rCurrentNPC.ai[1]].height / 2) - 30f - vector4.Y;
                    float num17;
                    if (i == 0)
                    {
                        num15 -= 200f * rCurrentNPC.ai[0];
                        num16 += 130f;
                        num17 = (float)Math.Sqrt((double)(num15 * num15 + num16 * num16));
                        num17 = 92f / num17;
                        vector4.X += num15 * num17;
                        vector4.Y += num16 * num17;
                    }
                    else
                    {
                        num15 -= 50f * rCurrentNPC.ai[0];
                        num16 += 80f;
                        num17 = (float)Math.Sqrt((double)(num15 * num15 + num16 * num16));
                        num17 = 60f / num17;
                        vector4.X += num15 * num17;
                        vector4.Y += num16 * num17;
                    }
                    float num18 = (float)Math.Atan2((double)num16, (double)num15) - 1.57f;
                    Microsoft.Xna.Framework.Color color4 = Lighting.GetColor((int)vector4.X / 16, (int)(vector4.Y / 16f));
                    mySpriteBatch.Draw(TextureAssets.PumpkingArm.Value, new Vector2(vector4.X - screenPos.X, vector4.Y - screenPos.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.PumpkingArm.Width(), TextureAssets.PumpkingArm.Height())), color4, num18, new Vector2((float)TextureAssets.PumpkingArm.Width() * 0.5f, (float)TextureAssets.PumpkingArm.Height() * 0.5f), 1f, SpriteEffects.None, 0f);
                    if (i == 0)
                    {
                        vector4.X += num15 * num17 / 2f;
                        vector4.Y += num16 * num17 / 2f;
                    }
                }
            }
            if (type == 36)
            {
                Vector2 vector5 = new Vector2(rCurrentNPC.position.X + (float)rCurrentNPC.width * 0.5f - 5f * rCurrentNPC.ai[0], rCurrentNPC.position.Y + 20f);
                for (int j = 0; j < 2; j++)
                {
                    float num19 = Main.npc[(int)rCurrentNPC.ai[1]].position.X + (float)(Main.npc[(int)rCurrentNPC.ai[1]].width / 2) - vector5.X;
                    float num20 = Main.npc[(int)rCurrentNPC.ai[1]].position.Y + (float)(Main.npc[(int)rCurrentNPC.ai[1]].height / 2) - vector5.Y;
                    float num21;
                    if (j == 0)
                    {
                        num19 -= 200f * rCurrentNPC.ai[0];
                        num20 += 130f;
                        num21 = (float)Math.Sqrt((double)(num19 * num19 + num20 * num20));
                        num21 = 92f / num21;
                        vector5.X += num19 * num21;
                        vector5.Y += num20 * num21;
                    }
                    else
                    {
                        num19 -= 50f * rCurrentNPC.ai[0];
                        num20 += 80f;
                        num21 = (float)Math.Sqrt((double)(num19 * num19 + num20 * num20));
                        num21 = 60f / num21;
                        vector5.X += num19 * num21;
                        vector5.Y += num20 * num21;
                    }
                    float num22 = (float)Math.Atan2((double)num20, (double)num19) - 1.57f;
                    Microsoft.Xna.Framework.Color color5 = Lighting.GetColor((int)vector5.X / 16, (int)(vector5.Y / 16f));
                    if (rCurrentNPC.localAI[3] == 1f)
                    {
                        mySpriteBatch.Draw(TextureAssets.BoneArm3.Value, new Vector2(vector5.X - screenPos.X, vector5.Y - screenPos.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.BoneArm.Width(), TextureAssets.BoneArm.Height())), color5, num22, new Vector2((float)TextureAssets.BoneArm.Width() * 0.5f, (float)TextureAssets.BoneArm.Height() * 0.5f), 1f, SpriteEffects.None, 0f);
                    }
                    else
                    {
                        mySpriteBatch.Draw(TextureAssets.BoneArm.Value, new Vector2(vector5.X - screenPos.X, vector5.Y - screenPos.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.BoneArm.Width(), TextureAssets.BoneArm.Height())), color5, num22, new Vector2((float)TextureAssets.BoneArm.Width() * 0.5f, (float)TextureAssets.BoneArm.Height() * 0.5f), 1f, SpriteEffects.None, 0f);
                    }
                    if (j == 0)
                    {
                        vector5.X += num19 * num21 / 2f;
                        vector5.Y += num20 * num21 / 2f;
                    }
                    else if (FocusHelper.AllowMiscDustEffects)
                    {
                        vector5.X += num19 * num21 - 16f;
                        vector5.Y += num20 * num21 - 6f;
                        int num23 = Dust.NewDust(new Vector2(vector5.X, vector5.Y), 30, 10, 5, num19 * 0.02f, num20 * 0.02f, 0, default(Microsoft.Xna.Framework.Color), 2f);
                        Main.dust[num23].noGravity = true;
                    }
                }
            }
            if (rCurrentNPC.aiStyle == 47)
            {
                float scale = rCurrentNPC.scale;
                Vector2 vector6 = new Vector2(rCurrentNPC.Center.X, rCurrentNPC.Center.Y);
                Vector2 vector7 = rCurrentNPC.Center;
                if (NPC.golemBoss != -1)
                {
                    vector7 = Main.npc[NPC.golemBoss].Center;
                }
                float num24 = vector7.X - vector6.X;
                float num25 = vector7.Y - vector6.Y;
                num25 -= 7f * scale;
                if (type == 247)
                {
                    num24 -= 70f * scale;
                }
                else
                {
                    num24 += 66f * scale;
                }
                float num26 = (float)Math.Atan2((double)num25, (double)num24) - 1.57f;
                bool flag6 = true;
                while (flag6)
                {
                    float num27 = (float)Math.Sqrt((double)(num24 * num24 + num25 * num25));
                    if (num27 < 16f)
                    {
                        flag6 = false;
                    }
                    else
                    {
                        num27 = 16f * scale / num27;
                        num24 *= num27;
                        num25 *= num27;
                        vector6.X += num24;
                        vector6.Y += num25;
                        num24 = vector7.X - vector6.X;
                        num25 = vector7.Y - vector6.Y;
                        num25 -= 7f * scale;
                        if (type == 247)
{
                            num24 -= 70f * scale;
                        }
                        else
{
                            num24 += 66f * scale;
                        }
                        if (Main.getGoodWorld)
{
                            num25 += 8f;
                        }
                        Microsoft.Xna.Framework.Color color6 = Lighting.GetColor((int)vector6.X / 16, (int)(vector6.Y / 16f));
                        mySpriteBatch.Draw(TextureAssets.Chain21.Value, new Vector2(vector6.X - screenPos.X, vector6.Y - screenPos.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain21.Width(), TextureAssets.Chain21.Height())), color6, num26, new Vector2((float)TextureAssets.Chain21.Width() * 0.5f, (float)TextureAssets.Chain21.Height() * 0.5f), scale, SpriteEffects.None, 0f);
                    }
                }
            }
            if (rCurrentNPC.aiStyle >= 33 && rCurrentNPC.aiStyle <= 36)
            {
                Vector2 vector8 = new Vector2(rCurrentNPC.position.X + (float)rCurrentNPC.width * 0.5f - 5f * rCurrentNPC.ai[0], rCurrentNPC.position.Y + 20f);
                for (int k = 0; k < 2; k++)
                {
                    float num28 = Main.npc[(int)rCurrentNPC.ai[1]].position.X + (float)(Main.npc[(int)rCurrentNPC.ai[1]].width / 2) - vector8.X;
                    float num29 = Main.npc[(int)rCurrentNPC.ai[1]].position.Y + (float)(Main.npc[(int)rCurrentNPC.ai[1]].height / 2) - vector8.Y;
                    float num30;
                    if (k == 0)
                    {
                        num28 -= 200f * rCurrentNPC.ai[0];
                        num29 += 130f;
                        num30 = (float)Math.Sqrt((double)(num28 * num28 + num29 * num29));
                        num30 = 92f / num30;
                        vector8.X += num28 * num30;
                        vector8.Y += num29 * num30;
                    }
                    else
                    {
                        num28 -= 50f * rCurrentNPC.ai[0];
                        num29 += 80f;
                        num30 = (float)Math.Sqrt((double)(num28 * num28 + num29 * num29));
                        num30 = 60f / num30;
                        vector8.X += num28 * num30;
                        vector8.Y += num29 * num30;
                    }
                    float num31 = (float)Math.Atan2((double)num29, (double)num28) - 1.57f;
                    Microsoft.Xna.Framework.Color color7 = Lighting.GetColor((int)vector8.X / 16, (int)(vector8.Y / 16f));
                    mySpriteBatch.Draw(TextureAssets.BoneArm2.Value, new Vector2(vector8.X - screenPos.X, vector8.Y - screenPos.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.BoneArm.Width(), TextureAssets.BoneArm.Height())), color7, num31, new Vector2((float)TextureAssets.BoneArm.Width() * 0.5f, (float)TextureAssets.BoneArm.Height() * 0.5f), 1f, SpriteEffects.None, 0f);
                    if (k == 0)
                    {
                        vector8.X += num28 * num30 / 2f;
                        vector8.Y += num29 * num30 / 2f;
                    }
                    else if (FocusHelper.AllowMiscDustEffects)
                    {
                        vector8.X += num28 * num30 - 16f;
                        vector8.Y += num29 * num30 - 6f;
                        int num32 = Dust.NewDust(new Vector2(vector8.X, vector8.Y), 30, 10, 6, num28 * 0.02f, num29 * 0.02f, 0, default(Microsoft.Xna.Framework.Color), 2.5f);
                        Main.dust[num32].noGravity = true;
                    }
                }
            }
            if (type == 693)
            {
                float num33 = rCurrentNPC.localAI[1];
                float num34 = num33 - 60f;
                float num35 = rCurrentNPC.localAI[0];
                Texture2D value = TextureAssets.Extra[289].Value;
                float num36 = 1f;
                float num37 = rCurrentNPC.localAI[3];
                float num38 = num35 * 0.016f * num37;
                float num39 = 1f;
                float num40 = rCurrentNPC.localAI[2] / 10f;
                if (num40 > 0f)
                {
                    num36 += num40 * 0.2f;
                    num39 -= num40 * 0.25f;
                }
                Microsoft.Xna.Framework.Color color8 = new Microsoft.Xna.Framework.Color(num39, num39, num39, num39 / 2f);
                if (num35 < 60f)
                {
                    float num41 = Utils.Remap(num35, 0f, 60f, 0f, 1f, true);
                    byte b = (byte)((num36 = num41 * num41) * 255f);
                    color8.R = b;
                    color8.G = b;
                    color8.B = b;
                    color8.A = b / 2;
                }
                else if (num35 > num34)
                {
                    float num42 = Utils.Remap(num35, num34, num33, 0f, 1f, true);
                    num42 *= num42;
                    num38 += num42 * 1.7f * num37;
                    num36 += num42;
                    byte b2 = (byte)((1f - num42) * 255f);
                    color8.R = b2;
                    color8.G = b2;
                    color8.B = b2;
                    color8.A = b2 / 2;
                }
                mySpriteBatch.Draw(value, rCurrentNPC.Top - screenPos, null, color8, num38, value.Size() * 0.5f, num36, SpriteEffects.None, 0f);
            }
            if (rCurrentNPC.aiStyle == 20)
            {
                Vector2 vector9 = new Vector2(rCurrentNPC.position.X + (float)(rCurrentNPC.width / 2), rCurrentNPC.position.Y + (float)(rCurrentNPC.height / 2));
                float num43 = rCurrentNPC.ai[1] - vector9.X;
                float num44 = rCurrentNPC.ai[2] - vector9.Y;
                float num45 = (float)Math.Atan2((double)num44, (double)num43) - 1.57f;
                rCurrentNPC.rotation = num45;
                bool flag7 = true;
                while (flag7)
                {
                    int num46 = 12;
                    float num47 = (float)Math.Sqrt((double)(num43 * num43 + num44 * num44));
                    if (num47 < 20f)
                    {
                        num46 = (int)num47 - 20 + 12;
                        flag7 = false;
                    }
                    num47 = 12f / num47;
                    num43 *= num47;
                    num44 *= num47;
                    vector9.X += num43;
                    vector9.Y += num44;
                    num43 = rCurrentNPC.ai[1] - vector9.X;
                    num44 = rCurrentNPC.ai[2] - vector9.Y;
                    Microsoft.Xna.Framework.Color color9 = Lighting.GetColor((int)vector9.X / 16, (int)(vector9.Y / 16f));
                    mySpriteBatch.Draw(TextureAssets.Chain.Value, new Vector2(vector9.X - screenPos.X, vector9.Y - screenPos.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain.Width(), num46)), color9, num45, new Vector2((float)TextureAssets.Chain.Width() * 0.5f, (float)TextureAssets.Chain.Height() * 0.5f), 1f, SpriteEffects.None, 0f);
                }
                mySpriteBatch.Draw(TextureAssets.SpikeBase.Value, new Vector2(rCurrentNPC.ai[1] - screenPos.X, rCurrentNPC.ai[2] - screenPos.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.SpikeBase.Width(), TextureAssets.SpikeBase.Height())), Lighting.GetColor((int)rCurrentNPC.ai[1] / 16, (int)(rCurrentNPC.ai[2] / 16f)), num45 - 0.75f, new Vector2((float)TextureAssets.SpikeBase.Width() * 0.5f, (float)TextureAssets.SpikeBase.Height() * 0.5f), 1f, SpriteEffects.None, 0f);
            }
            Microsoft.Xna.Framework.Color color10 = Lighting.GetColor((int)((double)rCurrentNPC.position.X + (double)rCurrentNPC.width * 0.5) / 16, (int)(((double)rCurrentNPC.position.Y + (double)rCurrentNPC.height * 0.5) / 16.0));
            if (rCurrentNPC.IsABestiaryIconDummy)
            {
                color10 = rCurrentNPC.GetBestiaryEntryColor();
            }
            if (type >= 277 && type <= 280)
            {
                if (color10.R < 255)
                {
                    color10.R = byte.MaxValue;
                }
                if (color10.G < 175)
                {
                    color10.G = 175;
                }
            }
            if (type == -4)
            {
                int num48 = (int)color10.R;
                int num49 = (int)color10.G;
                int num50 = (int)color10.B;
                num48 *= 2;
                if (num48 > 255)
                {
                    num48 = 255;
                }
                num49 *= 2;
                if (num49 > 255)
                {
                    num49 = 255;
                }
                num50 *= 2;
                if (num50 > 255)
                {
                    num50 = 255;
                }
                color10 = new Microsoft.Xna.Framework.Color(num48, num49, num50);
            }
            if (behindTiles && type != 113 && type != 114)
            {
                int num51 = (int)((rCurrentNPC.position.X - 8f) / 16f);
                int num52 = (int)((rCurrentNPC.position.X + (float)rCurrentNPC.width + 8f) / 16f);
                int num53 = (int)((rCurrentNPC.position.Y - 8f) / 16f);
                int num54 = (int)((rCurrentNPC.position.Y + (float)rCurrentNPC.height + 8f) / 16f);
                for (int l = num51; l <= num52; l++)
                {
                    for (int m = num53; m <= num54; m++)
                    {
                        if (Lighting.Brightness(l, m) == 0f)
{
                            color10 = Microsoft.Xna.Framework.Color.Black;
                        }
                    }
                }
            }
            color10 = rCurrentNPC.GetNPCColorTintedByBuffs(color10);
            if (type == 50)
            {
                Vector2 zero = Vector2.Zero;
                float num55 = 0f;
                zero.Y -= rCurrentNPC.velocity.Y;
                zero.X -= rCurrentNPC.velocity.X * 2f;
                num55 += rCurrentNPC.velocity.X * 0.05f;
                if (rCurrentNPC.frame.Y == 120)
                {
                    zero.Y += 2f;
                }
                if (rCurrentNPC.frame.Y == 360)
                {
                    zero.Y -= 2f;
                }
                if (rCurrentNPC.frame.Y == 480)
                {
                    zero.Y -= 6f;
                }
                mySpriteBatch.Draw(TextureAssets.Ninja.Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) + zero.X, rCurrentNPC.position.Y - screenPos.Y + (float)(rCurrentNPC.height / 2) + zero.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Ninja.Width(), TextureAssets.Ninja.Height())), color10, num55, new Vector2((float)(TextureAssets.Ninja.Width() / 2), (float)(TextureAssets.Ninja.Height() / 2)), 1f, SpriteEffects.None, 0f);
            }
            if (type == 71)
            {
                Vector2 zero2 = Vector2.Zero;
                float num56 = 0f;
                zero2.Y -= rCurrentNPC.velocity.Y * 0.3f;
                zero2.X -= rCurrentNPC.velocity.X * 0.6f;
                num56 += rCurrentNPC.velocity.X * 0.09f;
                if (rCurrentNPC.frame.Y == 120)
                {
                    zero2.Y += 2f;
                }
                if (rCurrentNPC.frame.Y == 360)
                {
                    zero2.Y -= 2f;
                }
                if (rCurrentNPC.frame.Y == 480)
                {
                    zero2.Y -= 6f;
                }
                Texture2D texture2D;
                Microsoft.Xna.Framework.Rectangle rectangle;
                Main.GetItemDrawFrame(327, out texture2D, out rectangle);
                mySpriteBatch.Draw(texture2D, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) + zero2.X, rCurrentNPC.position.Y - screenPos.Y + (float)(rCurrentNPC.height / 2) + zero2.Y), new Microsoft.Xna.Framework.Rectangle?(rectangle), color10, num56, rectangle.Size() / 2f, 1f, SpriteEffects.None, 0f);
            }
            if (type == 69)
            {
                mySpriteBatch.Draw(TextureAssets.AntLion.Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2), rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height + 14f), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.AntLion.Width(), TextureAssets.AntLion.Height())), color10, -rCurrentNPC.rotation * 0.3f, new Vector2((float)(TextureAssets.AntLion.Width() / 2), (float)(TextureAssets.AntLion.Height() / 2)), 1f, SpriteEffects.None, 0f);
            }
            if (NPCID.Sets.SlimeCanContainItems[type] && rCurrentNPC.ai[1] > 0f)
            {
                Main.DrawNPC_SlimeItem(rCurrentNPC, type, color10, 0f);
            }
            float num57 = 0f;
            float num58 = 0f;
            float num59 = Main.NPCAddHeight(rCurrentNPC);
            Vector2 vector10 = new Vector2((float)(TextureAssets.Npc[type].Width() / 2), (float)(TextureAssets.Npc[type].Height() / Main.npcFrameCount[type] / 2));
            if (type == 108 || type == 124 || type == 625)
            {
                num58 = 2f;
            }
            else if (type == 357)
            {
                num58 = rCurrentNPC.localAI[0];
            }
            else if (type == 467)
            {
                num58 = 7f;
            }
            else if (type == 537)
            {
                num58 = 2f;
            }
            else if (type == 581)
            {
                num58 = -6f;
            }
            else if (type == 490)
            {
                num58 = 4f;
            }
            else if (type == 484)
            {
                num58 = 2f;
            }
            else if (type == 483)
            {
                num58 = 14f;
            }
            else if (type == 477)
            {
                num59 = 22f;
            }
            else if (type == 478)
            {
                num58 -= 2f;
            }
            else if (type == 606)
            {
                num58 -= 2f;
            }
            else if (type == 612 || type == 613)
            {
                num58 -= 2f;
            }
            else if (type == 469 && rCurrentNPC.ai[2] == 1f)
            {
                num58 = 14f;
            }
            else if (type == 4)
            {
                vector10 = new Vector2(55f, 107f);
            }
            else if (type == 125)
            {
                vector10 = new Vector2(55f, 107f);
            }
            else if (type == 126)
            {
                vector10 = new Vector2(55f, 107f);
            }
            else if (type == 626 || type == 627)
            {
                if (rCurrentNPC.wet)
                {
                    num58 = -2f;
                    vector10 = rCurrentNPC.frame.Size() * new Vector2(0.5f, 0.5f) + new Vector2(0f, -4f);
                }
                else
                {
                    num58 = 2f;
                }
            }
            else if (type == 692)
            {
                if (rCurrentNPC.wet)
                {
                    num58 = 6f;
                }
                else
                {
                    num58 = 10f;
                }
            }
            else if (type == 63 || type == 64 || type == 103)
            {
                vector10.Y += 4f;
            }
            else if (type == 69)
            {
                vector10.Y += 8f;
            }
            else if (type == 262)
            {
                vector10.Y = 77f;
                num59 += 26f;
            }
            else if (type == 264)
            {
                vector10.Y = 21f;
                num59 += 2f;
            }
            else if (type == 266)
            {
                num59 += 50f * rCurrentNPC.scale;
            }
            else if (type == 268)
            {
                num59 += 16f;
            }
            else if (type == 288)
            {
                num59 += 6f;
            }
            else if (type == 694)
            {
                num57 += (float)rCurrentNPC.direction;
                num58 -= 2f;
                if (rCurrentNPC.ai[3] == 3f)
                {
                    num57 += 4f;
                    num58 += 16f;
                }
                else if (rCurrentNPC.ai[3] == 4f)
                {
                    float num60 = (float)rCurrentNPC.frame.Y / 40f;
                    float num61 = 17f;
                    float num62 = 1f - Math.Max(0f, Math.Min(1f, num60 / num61));
                    num57 += (float)((int)(4f * num62));
                    num58 += (float)((int)(16f * num62));
                }
            }
            else if (type == 688)
            {
                num58 += 10f;
            }
            if ((rCurrentNPC.aiStyle == 10 && type != 694) || type == 72)
            {
                color10 = Microsoft.Xna.Framework.Color.White;
            }
            SpriteEffects spriteEffects = SpriteEffects.None;
            if (rCurrentNPC.spriteDirection == 1)
            {
                spriteEffects = SpriteEffects.FlipHorizontally;
            }
            if (type == 124 && rCurrentNPC.localAI[0] == 0f)
            {
                int num63 = 0;
                if (rCurrentNPC.frame.Y > 56)
                {
                    num63 += 4;
                }
                num63 += rCurrentNPC.frame.Y / 56;
                if (num63 >= Main.OffsetsPlayerHeadgear.Length)
                {
                    num63 = 0;
                }
                float y = Main.OffsetsPlayerHeadgear[num63].Y;
                this.LoadProjectile(582);
                Texture2D texture2D2 = TextureAssets.Projectile[582].Value;
                if (rCurrentNPC.townNpcVariationIndex == 1)
                {
                    texture2D2 = TextureAssets.Extra[263].Value;
                }
                Vector2 vector11 = rCurrentNPC.Bottom - screenPos;
                Vector2 vector12 = Vector2.Zero;
                vector12 += new Vector2(0f, num58 + num59 + rCurrentNPC.gfxOffY + y);
                vector12 -= new Vector2(0f, (float)(rCurrentNPC.height / 2));
                vector12 -= new Vector2((float)(texture2D2.Width / 2), 0f);
                vector12 += new Vector2((float)(-(float)rCurrentNPC.spriteDirection * 2), -2f);
                vector12 += new Vector2((float)(-1 * rCurrentNPC.spriteDirection), 1f);
                vector12 *= rCurrentNPC.scale;
                if (rCurrentNPC.scale == 2f)
                {
                    vector12.Y += -6f;
                }
                if (rCurrentNPC.scale == 3f)
                {
                    vector12.Y += -12f;
                }
                vector11 += vector12;
                mySpriteBatch.Draw(texture2D2, vector11, null, rCurrentNPC.GetAlpha(color10), rCurrentNPC.rotation, texture2D2.Size() * new Vector2(0f, 0.5f), rCurrentNPC.scale, spriteEffects, 0f);
            }
            if (type == 427 || type == 426 || type == 428 || type == 581 || type == 521 || type == 523 || type == 541 || (type >= 542 && type <= 545) || type == 546 || type == 552 || type == 553 || type == 554 || type == 561 || type == 562 || type == 563 || type == 555 || type == 556 || type == 557 || type == 558 || type == 559 || type == 560 || type == 574 || type == 575 || type == 568 || type == 569 || type == 572 || type == 573 || type == 566 || type == 567 || type == 570 || type == 578 || type == 571 || type == 583 || type == 584 || type == 585 || type == 618 || type == 620 || type == 661)
            {
                Texture2D value2 = TextureAssets.Npc[type].Value;
                Microsoft.Xna.Framework.Color color11 = Microsoft.Xna.Framework.Color.White;
                float num64 = 0f;
                float num65 = 0f;
                int num66 = 0;
                int num67 = 0;
                int num68 = 1;
                int num69 = 15;
                int num70 = 0;
                float scale2 = rCurrentNPC.scale;
                float num71 = rCurrentNPC.scale;
                int num72 = 0;
                float num73 = 0f;
                float num74 = 0f;
                float num75 = 0f;
                Microsoft.Xna.Framework.Color color12 = color10;
                Vector2 vector13 = vector10;
                if (type <= 581)
                {
                    if (type != 426)
                    {
                        if (type != 427)
{
                            switch (type)
{
                            case 521:
                                num66 = 10;
                                num67 = 2;
                                num69 = num66;
                                num70 = 1;
                                num71 = 0.3f;
                                break;
                            case 523:
                                num72 = 3;
                                num74 = 10f * rCurrentNPC.scale;
                                num64 = 0.5f;
                                num65 = 0.8f;
                                color11 = Microsoft.Xna.Framework.Color.HotPink;
                                color11.A = 128;
                                num75 = rCurrentNPC.localAI[0];
                                num73 = rCurrentNPC.localAI[1];
                                break;
                            case 541:
                                num72 = 4;
                                num74 = 6f;
                                num73 = (float)Math.Cos((double)(Main.GlobalTimeWrappedHourly % 2.4f / 2.4f * 6.2831855f)) / 2f + 0.5f;
                                color11 = Microsoft.Xna.Framework.Color.Gold;
                                num64 = 0.5f;
                                break;
                            case 542:
                            case 543:
                            case 544:
                            case 545:
                                num66 = 6;
                                num67 = 3;
                                num69 = num66 * 2;
                                break;
                            case 546:
                                num66 = 8;
                                num67 = 2;
                                num69 = num66 * 3;
                                break;
                            case 552:
                            case 553:
                            case 554:
                            case 555:
                            case 556:
                            case 557:
                            case 561:
                            case 562:
                            case 563:
                            case 568:
                            case 569:
                            case 570:
                            case 571:
                            case 572:
                            case 573:
                                num66 = 0;
                                if (type == 561 || type == 562 || type == 563)
{
                                    num59 = -8f;
                                }
                                if (type == 555 || type == 556 || type == 557)
{
                                    num59 = -5f;
                                }
                                if (type == 572 || type == 573)
{
                                    num59 = -4f;
                                }
                                if (type == 570 || type == 571)
{
                                    spriteEffects ^= SpriteEffects.FlipHorizontally;
                                    num59 = -2f;
                                }
                                if (type == 568 || type == 569)
{
                                    spriteEffects ^= SpriteEffects.FlipHorizontally;
                                    num59 = -3f;
                                    num72 = 4;
                                    num74 = 4f;
                                    num73 = (float)Math.Cos((double)(Main.GlobalTimeWrappedHourly % 1.5f / 1.5f * 6.2831855f)) / 6f + 0.75f;
                                    color11 = Microsoft.Xna.Framework.Color.HotPink;
                                    color11.A = 127;
                                    num64 = 0.5f;
                                }
                                if (rCurrentNPC.localAI[3] < 60f)
{
                                    float num76 = 8f;
                                    float num77 = rCurrentNPC.localAI[3] / 60f;
                                    num72 = 3;
                                    num73 = 1f - num77 * num77;
                                    num74 = num76;
                                    color11 = new Microsoft.Xna.Framework.Color(127, 0, 255, 0);
                                    num65 = 1f;
                                    color12 = Microsoft.Xna.Framework.Color.Lerp(Microsoft.Xna.Framework.Color.Transparent, color12, num77 * num77);
                                }
                                break;
                            case 558:
                            case 559:
                            case 560:
                            case 574:
                            case 575:
                                if (rCurrentNPC.ai[0] != 2f)
{
                                    num66 = 0;
                                }
                                else
{
                                    num66 = 6;
                                    num67 = 2;
                                    num69 = num66 * 3;
                                    num70 = 1;
                                }
                                break;
                            case 566:
                            case 567:
                            case 578:
                                num66 = 0;
                                num59 = -2f;
                                break;
                            case 581:
                                num66 = 6;
                                num67 = 2;
                                num69 = num66 * 3;
                                break;
                            }
                        }
                        else
{
                            num66 = 8;
                            num67 = 2;
                            num69 = num66 * 3;
                        }
                    }
                    else
                    {
                        num72 = 4;
                        num74 = 4f;
                        num73 = (float)Math.Cos((double)(Main.GlobalTimeWrappedHourly % 1.2f / 1.2f * 6.2831855f)) / 2f + 0.5f;
                        color11 = Microsoft.Xna.Framework.Color.Turquoise;
                        num64 = 0.5f;
                        num66 = 6;
                        num67 = 2;
                        num69 = num66;
                    }
                }
                else if (type != 618)
                {
                    if (type != 620)
                    {
                        if (type == 661)
{
                            num72 = 6;
                            num74 = 6f;
                            num73 = (float)Math.Cos((double)(Main.GlobalTimeWrappedHourly % 2.4f / 2.4f * 6.2831855f)) / 2f + 0.5f;
                            num73 = MathHelper.Max(num73, Utils.GetLerpValue(0f, 60f, rCurrentNPC.ai[2], true));
                            num64 = 0.5f;
                        }
                    }
                    else
                    {
                        num59 = -9f;
                        vector13 = rCurrentNPC.frame.Size() * new Vector2(0.5f, 0.5f) + new Vector2((float)(-4 * rCurrentNPC.spriteDirection), 0f);
                        num72 = 4;
                        num74 = 6f;
                        num73 = (float)Math.Cos((double)(Main.GlobalTimeWrappedHourly % 2.4f / 2.4f * 6.2831855f)) / 2f + 0.5f;
                        color11 = Microsoft.Xna.Framework.Color.Gold;
                        num64 = 0.5f;
                        num66 = 6;
                        num67 = 2;
                        num69 = num66 * 3;
                        num70 = 1;
                    }
                }
                else
                {
                    float num78 = 90f;
                    float num79 = 180f;
                    if (rCurrentNPC.ai[0] == 1f && rCurrentNPC.ai[1] < num78)
                    {
                        int num80 = 3;
                        float num81 = num78 / (float)num80;
                        float num82 = rCurrentNPC.ai[1] % num81 / num81;
                        num72 = 6;
                        num74 = 15f;
                        num73 = num82 * 0.8f + 0.2f;
                    }
                    if (rCurrentNPC.ai[0] == 3f && rCurrentNPC.ai[1] < num79)
                    {
                        int num83 = 1;
                        float num84 = num79 / (float)num83;
                        float num85 = rCurrentNPC.ai[1] % num84 / num84;
                        num72 = 4;
                        num74 = 25f;
                        num73 = num85;
                        Vector2 vector14 = rCurrentNPC.scale * new Vector2(1f, 0.5f + num85 * 0.75f);
                        Texture2D value3 = TextureAssets.Extra[59].Value;
                        Microsoft.Xna.Framework.Rectangle rectangle2 = value3.Frame(1, 1, 0, 0, 0, 0);
                        Vector2 vector15 = rectangle2.Size() * new Vector2(0.5f, 0.5f);
                        for (int n = 0; n < num72; n++)
{
                            Microsoft.Xna.Framework.Color color13 = Microsoft.Xna.Framework.Color.White;
                            color13 *= Utils.GetLerpValue(0f, 0.5f, num73, false) * Utils.GetLerpValue(1f, 0.5f, num73, false) * 0.25f;
                            color13.A = 0;
                            color13.G = 0;
                            color13.B = 0;
                            float num86 = (float)n / (float)num72 * 6.2831855f + rCurrentNPC.rotation + num75;
                            Vector2 vector16 = rCurrentNPC.Center + num86.ToRotationVector2() * num74 * num73 - screenPos;
                            vector16 -= new Vector2((float)value2.Width, (float)(value2.Height / Main.npcFrameCount[type])) * rCurrentNPC.scale / 2f;
                            vector16 += vector10 * rCurrentNPC.scale + new Vector2(0f, num58 + num59 + rCurrentNPC.gfxOffY);
                            mySpriteBatch.Draw(value3, vector16, new Microsoft.Xna.Framework.Rectangle?(rectangle2), color13, num86, vector15, vector14 * 1.8f, spriteEffects, 0f);
                        }
                        for (int num87 = 0; num87 < num72; num87++)
{
                            Microsoft.Xna.Framework.Color color14 = Microsoft.Xna.Framework.Color.White;
                            color14 *= Utils.GetLerpValue(0f, 0.5f, num73, false) * Utils.GetLerpValue(1f, 0.5f, num73, false) * 0.25f;
                            color14.A = 0;
                            float num88 = (float)num87 / (float)num72 * 6.2831855f + rCurrentNPC.rotation + num75;
                            Vector2 vector17 = rCurrentNPC.Center + num88.ToRotationVector2() * num74 * num73 - screenPos;
                            vector17 -= new Vector2((float)value2.Width, (float)(value2.Height / Main.npcFrameCount[type])) * rCurrentNPC.scale / 2f;
                            vector17 += vector10 * rCurrentNPC.scale + new Vector2(0f, num58 + num59 + rCurrentNPC.gfxOffY);
                            mySpriteBatch.Draw(value3, vector17, new Microsoft.Xna.Framework.Rectangle?(rectangle2), color14, num88, vector15, vector14 * 1.5f, spriteEffects, 0f);
                        }
                    }
                }
                for (int num89 = num68; num89 < num66; num89 += num67)
                {
                    Vector2[] oldPos = rCurrentNPC.oldPos;
                    Microsoft.Xna.Framework.Color color15 = color12;
                    color15 = Microsoft.Xna.Framework.Color.Lerp(color15, color11, num64);
                    color15 = rCurrentNPC.GetAlpha(color15);
                    color15 *= (float)(num66 - num89) / (float)num69;
                    float rotation = rCurrentNPC.rotation;
                    if (num70 == 1)
                    {
                        float num90 = rCurrentNPC.oldRot[num89];
                    }
                    float num91 = MathHelper.Lerp(scale2, num71, 1f - (float)(num66 - num89) / (float)num69);
                    Vector2 vector18 = rCurrentNPC.oldPos[num89] + new Vector2((float)rCurrentNPC.width, (float)rCurrentNPC.height) / 2f - screenPos;
                    vector18 -= new Vector2((float)value2.Width, (float)(value2.Height / Main.npcFrameCount[type])) * rCurrentNPC.scale / 2f;
                    vector18 += vector10 * rCurrentNPC.scale + new Vector2(0f, num58 + num59 + rCurrentNPC.gfxOffY);
                    mySpriteBatch.Draw(value2, vector18, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), color15, rCurrentNPC.rotation, vector10, num91, spriteEffects, 0f);
                }
                for (int num92 = 0; num92 < num72; num92++)
                {
                    Microsoft.Xna.Framework.Color color16 = color10;
                    color16 = Microsoft.Xna.Framework.Color.Lerp(color16, color11, num64);
                    color16 = rCurrentNPC.GetAlpha(color16);
                    color16 = Microsoft.Xna.Framework.Color.Lerp(color16, color11, num65);
                    color16 *= 1f - num73;
                    Vector2 vector19 = rCurrentNPC.Center + ((float)num92 / (float)num72 * 6.2831855f + rCurrentNPC.rotation + num75).ToRotationVector2() * num74 * num73 - screenPos;
                    vector19 -= new Vector2((float)value2.Width, (float)(value2.Height / Main.npcFrameCount[type])) * rCurrentNPC.scale / 2f;
                    vector19 += vector10 * rCurrentNPC.scale + new Vector2(0f, num58 + num59 + rCurrentNPC.gfxOffY);
                    mySpriteBatch.Draw(value2, vector19, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), color16, rCurrentNPC.rotation, vector13, rCurrentNPC.scale, spriteEffects, 0f);
                }
                Vector2 vector20 = rCurrentNPC.Center - screenPos;
                vector20 -= new Vector2((float)value2.Width, (float)(value2.Height / Main.npcFrameCount[type])) * rCurrentNPC.scale / 2f;
                vector20 += vector10 * rCurrentNPC.scale + new Vector2(0f, num58 + num59 + rCurrentNPC.gfxOffY);
                mySpriteBatch.Draw(value2, vector20, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), rCurrentNPC.GetAlpha(color12), rCurrentNPC.rotation, vector13, rCurrentNPC.scale, spriteEffects, 0f);
                if (type == 427)
                {
                    mySpriteBatch.Draw(TextureAssets.GlowMask[152].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-(float)TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, (float)(-(float)TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 0), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                }
                else if (type == 426)
                {
                    mySpriteBatch.Draw(TextureAssets.GlowMask[153].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-(float)TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, (float)(-(float)TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 0), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                }
                if (type == 541)
                {
                    Microsoft.Xna.Framework.Color color17 = new Microsoft.Xna.Framework.Color(127 - rCurrentNPC.alpha, 127 - rCurrentNPC.alpha, 127 - rCurrentNPC.alpha, 0).MultiplyRGBA(Microsoft.Xna.Framework.Color.Gold);
                    for (int num93 = 0; num93 < num72; num93++)
                    {
                        Microsoft.Xna.Framework.Color color18 = color17;
                        color18 = rCurrentNPC.GetAlpha(color18);
                        color18 *= 1f - num73;
                        Vector2 vector21 = rCurrentNPC.Center + ((float)num93 / (float)num72 * 6.2831855f + rCurrentNPC.rotation + num75).ToRotationVector2() * (4f * num73 + 2f) - screenPos;
                        vector21 -= new Vector2((float)value2.Width, (float)(value2.Height / Main.npcFrameCount[type])) * rCurrentNPC.scale / 2f;
                        vector21 += vector10 * rCurrentNPC.scale + new Vector2(0f, num58 + num59 + rCurrentNPC.gfxOffY);
                        mySpriteBatch.Draw(TextureAssets.GlowMask[216].Value, vector21, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), color18, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                    }
                    mySpriteBatch.Draw(TextureAssets.GlowMask[216].Value, vector20, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), color17, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                }
                if (type == 661)
                {
                    num75 = MathHelper.Lerp(0f, 3f, Utils.GetLerpValue(0f, 60f, rCurrentNPC.ai[2], true));
                    for (int num94 = 0; num94 < num72; num94++)
                    {
                        Microsoft.Xna.Framework.Color color19 = new Microsoft.Xna.Framework.Color(127 - rCurrentNPC.alpha, 127 - rCurrentNPC.alpha, 127 - rCurrentNPC.alpha, 0).MultiplyRGBA(Main.hslToRgb((Main.GlobalTimeWrappedHourly + (float)num94 / (float)num72) % 1f, 1f, 0.5f, byte.MaxValue));
                        color19 = rCurrentNPC.GetAlpha(color19);
                        color19 *= 1f - num73 * 0.5f;
                        color19.A = 0;
                        float num95 = 2f + rCurrentNPC.ai[2];
                        Vector2 vector22 = rCurrentNPC.Center + ((float)num94 / (float)num72 * 6.2831855f + rCurrentNPC.rotation + num75).ToRotationVector2() * (num95 * num73 + 2f) - screenPos;
                        vector22 -= new Vector2((float)value2.Width, (float)(value2.Height / Main.npcFrameCount[type])) * rCurrentNPC.scale / 2f;
                        vector22 += vector10 * rCurrentNPC.scale + new Vector2(0f, num58 + num59 + rCurrentNPC.gfxOffY);
                        mySpriteBatch.Draw(value2, vector22, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), color19, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                    }
                    mySpriteBatch.Draw(value2, vector20, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(255, 255, 255, 0) * 0.1f, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                }
                if ((type == 568 || type == 569) && rCurrentNPC.localAI[3] >= 60f)
                {
                    Microsoft.Xna.Framework.Color color20 = new Microsoft.Xna.Framework.Color(127 - rCurrentNPC.alpha, 127 - rCurrentNPC.alpha, 127 - rCurrentNPC.alpha, 0).MultiplyRGBA(color11);
                    for (int num96 = 0; num96 < num72; num96++)
                    {
                        Microsoft.Xna.Framework.Color color21 = color20;
                        color21 = rCurrentNPC.GetAlpha(color21);
                        color21 *= 1f - num73;
                        Vector2 vector23 = rCurrentNPC.Center + ((float)num96 / (float)num72 * 6.2831855f + rCurrentNPC.rotation + num75).ToRotationVector2() * (4f * num73 + 2f) - screenPos;
                        vector23 -= new Vector2((float)value2.Width, (float)(value2.Height / Main.npcFrameCount[type])) * rCurrentNPC.scale / 2f;
                        vector23 += vector10 * rCurrentNPC.scale + new Vector2(0f, num58 + num59 + rCurrentNPC.gfxOffY);
                        mySpriteBatch.Draw(TextureAssets.GlowMask[224].Value, vector23, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), color21, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                    }
                    mySpriteBatch.Draw(TextureAssets.GlowMask[224].Value, vector20, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), color20, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                    float num97 = rCurrentNPC.localAI[0];
                    if (num97 > 0f)
                    {
                        byte b3 = (byte)((Math.Cos((double)(num97 * 6.2831855f / 60f)) * 0.5 + 0.5) * 32.0 + 0.0);
                        Microsoft.Xna.Framework.Color color22 = new Microsoft.Xna.Framework.Color(180, 90, 255, (int)b3) * 0.75f;
                        float num98 = 1f;
                        if (num97 < 60f)
{
                            float lerpValue = Utils.GetLerpValue(0f, 60f, num97, false);
                            color22 *= lerpValue;
                            num98 = MathHelper.Lerp(1f, 0.5f, 1f - lerpValue * lerpValue);
                        }
                        Texture2D value4 = TextureAssets.Extra[89].Value;
                        Vector2 vector24 = value4.Size() / 2f;
                        Vector2 vector25 = new Vector2(num98);
                        float num99 = num97 * 0.0041887905f;
                        float num100 = 1.5707964f;
                        vector25.Y *= 1f;
                        vector25.X *= 1f;
                        for (float num101 = 0f; num101 < 16f; num101 += 1f)
{
                            float num102 = num99 + 6.2831855f * (num101 / 16f);
                            Vector2 vector26 = rCurrentNPC.Center - screenPos + num102.ToRotationVector2() * 400f * num98;
                            mySpriteBatch.Draw(value4, vector26, null, color22, num102 + 1.5707964f + num100, vector24, vector25, SpriteEffects.None, 0f);
                        }
                    }
                }
                if (type == 546)
                {
                    mySpriteBatch.Draw(TextureAssets.Extra[76].Value, vector20, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(255, 255, 255, 200), MathHelper.Clamp(rCurrentNPC.velocity.X * 0.1f, -0.3926991f, 0.3926991f), vector10, rCurrentNPC.scale, spriteEffects, 0f);
                }
                if ((type == 566 || type == 567) && rCurrentNPC.localAI[3] >= 115f)
                {
                    int num103 = (int)(Main.GlobalTimeWrappedHourly % 0.5f / 0.5f * 4f);
                    Texture2D value5 = TextureAssets.Extra[80].Value;
                    Microsoft.Xna.Framework.Rectangle rectangle3 = value5.Frame(1, 4, 0, num103, 0, 0);
                    Vector2 vector27 = new Vector2((float)(rCurrentNPC.spriteDirection * 8), -26f) * rCurrentNPC.scale;
                    int num104 = rCurrentNPC.frame.Y / rCurrentNPC.frame.Height;
                    int num105 = 0;
                    switch (num104)
                    {
                    case 0:
                        num105 = 6;
                        break;
                    case 1:
                        num105 = 4;
                        break;
                    case 2:
                        num105 = 2;
                        break;
                    case 3:
                        num105 = 6;
                        break;
                    case 4:
                        num105 = 8;
                        break;
                    case 5:
                        num105 = 6;
                        break;
                    case 6:
                        num105 = 4;
                        break;
                    case 7:
                        num105 = 6;
                        break;
                    case 8:
                        num105 = 2;
                        break;
                    }
                    Microsoft.Xna.Framework.Color color23 = new Microsoft.Xna.Framework.Color(255, 255, 255, 130);
                    vector27.Y += (float)num105;
                    mySpriteBatch.Draw(value5, vector20 + vector27 * rCurrentNPC.scale, new Microsoft.Xna.Framework.Rectangle?(rectangle3), color23, MathHelper.Clamp(rCurrentNPC.velocity.X * 0.1f, -0.3926991f, 0.3926991f), rectangle3.Size() / 2f, rCurrentNPC.scale * 0.7f, spriteEffects ^ SpriteEffects.FlipHorizontally, 0f);
                }
                if (type == 618)
                {
                    mySpriteBatch.Draw(TextureAssets.Extra[129].Value, vector20, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), rCurrentNPC.GetAlpha(color12), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                    return;
                }
            }
            else
            {
                if (type == 551)
                {
                    Texture2D value6 = TextureAssets.Npc[type].Value;
                    Vector2 vector28 = rCurrentNPC.Center - screenPos;
                    Microsoft.Xna.Framework.Rectangle frame = rCurrentNPC.frame;
                    frame.Size() / 2f;
                    SpriteEffects spriteEffects2 = spriteEffects ^ SpriteEffects.FlipHorizontally;
                    float rotation2 = rCurrentNPC.rotation;
                    Microsoft.Xna.Framework.Color color24 = color10;
                    Microsoft.Xna.Framework.Color color25 = Microsoft.Xna.Framework.Color.Lerp(color24, Microsoft.Xna.Framework.Color.White, 0.6f);
                    color25.A = 66;
                    Vector2 vector29 = new Vector2(171f, 44f);
                    Vector2 vector30 = new Vector2(230f, 52f);
                    Vector2 vector31 = Vector2.Lerp(vector29, vector30, 0.5f) + new Vector2(-50f, 30f);
                    int num106 = (int)rCurrentNPC.localAI[0] / 4;
                    Vector2 vector32 = vector29 - vector31;
                    Vector2 vector33 = vector30 - vector31;
                    Texture2D value7 = TextureAssets.Extra[82].Value;
                    if ((spriteEffects2 & SpriteEffects.FlipHorizontally) != SpriteEffects.None)
                    {
                        vector33.X *= -1f;
                    }
                    Microsoft.Xna.Framework.Rectangle rectangle4 = value7.Frame(2, 5, num106 / 5, num106 % 5, 0, 0);
                    Vector2 vector34 = new Vector2(16f, 176f);
                    if ((spriteEffects2 & SpriteEffects.FlipHorizontally) != SpriteEffects.None)
                    {
                        vector34.X = (float)rectangle4.Width - vector34.X;
                    }
                    if ((spriteEffects2 & SpriteEffects.FlipHorizontally) != SpriteEffects.None)
                    {
                        vector31.X = (float)frame.Width - vector31.X;
                    }
                    Texture2D value8 = TextureAssets.Extra[81].Value;
                    if ((spriteEffects2 & SpriteEffects.FlipHorizontally) != SpriteEffects.None)
                    {
                        vector32.X *= -1f;
                    }
                    Microsoft.Xna.Framework.Rectangle rectangle5 = value8.Frame(2, 5, num106 / 5, num106 % 5, 0, 0);
                    Vector2 vector35 = new Vector2(215f, 170f);
                    if ((spriteEffects2 & SpriteEffects.FlipHorizontally) != SpriteEffects.None)
                    {
                        vector35.X = (float)rectangle5.Width - vector35.X;
                    }
                    float num107 = Utils.GetLerpValue(0f, 30f, rCurrentNPC.localAI[1], true);
                    if (num107 == 1f)
                    {
                        num107 = Utils.GetLerpValue(60f, 30f, rCurrentNPC.localAI[1], true);
                    }
                    num107 = 2f;
                    Vector2 vector36 = rCurrentNPC.Size / 2f - screenPos;
                    int num108 = 9;
                    int num109 = -3;
                    int num110 = 0;
                    byte b4 = 2;
                    for (int num111 = num108; num111 > num110; num111 += num109)
                    {
                        Vector2 vector37 = rCurrentNPC.oldPos[num111] + vector36;
                        float num112 = rCurrentNPC.oldRot[num111];
                        Microsoft.Xna.Framework.Color color26 = color24 * (1f - (float)num111 / 10f) * 0.35f;
                        color26.A /= b4;
                        mySpriteBatch.Draw(value7, vector37 + vector33.RotatedBy((double)num112, default(Vector2)), new Microsoft.Xna.Framework.Rectangle?(rectangle4), color26, num112, vector34, 1f, spriteEffects2, 0f);
                        mySpriteBatch.Draw(value6, vector37, new Microsoft.Xna.Framework.Rectangle?(frame), color26, num112, vector31, 1f, spriteEffects2, 0f);
                        mySpriteBatch.Draw(value8, vector37 + vector32.RotatedBy((double)num112, default(Vector2)), new Microsoft.Xna.Framework.Rectangle?(rectangle5), color26, num112, vector35, 1f, spriteEffects2, 0f);
                    }
                    mySpriteBatch.Draw(value7, vector28 + vector33.RotatedBy((double)rotation2, default(Vector2)), new Microsoft.Xna.Framework.Rectangle?(rectangle4), color24, rotation2, vector34, 1f, spriteEffects2, 0f);
                    mySpriteBatch.Draw(value6, vector28, new Microsoft.Xna.Framework.Rectangle?(frame), color24, rotation2, vector31, 1f, spriteEffects2, 0f);
                    mySpriteBatch.Draw(TextureAssets.GlowMask[226].Value, vector28, new Microsoft.Xna.Framework.Rectangle?(frame), color25 * (0.7f + 0.3f * num107), rotation2, vector31, 1f, spriteEffects2, 0f);
                    mySpriteBatch.Draw(value8, vector28 + vector32.RotatedBy((double)rotation2, default(Vector2)), new Microsoft.Xna.Framework.Rectangle?(rectangle5), color24, rotation2, vector35, 1f, spriteEffects2, 0f);
                    return;
                }
                if (type == 690)
                {
                    this.LoadTiles(105);
                    Texture2D value9 = TextureAssets.Tile[105].Value;
                    Vector2 vector38 = rCurrentNPC.Center - screenPos;
                    vector38.Y -= 3f;
                    float rotation3 = rCurrentNPC.rotation;
                    Microsoft.Xna.Framework.Color alpha = rCurrentNPC.GetAlpha(color10);
                    SpriteEffects spriteEffects3 = SpriteEffects.None;
                    int num113 = (int)rCurrentNPC.ai[1];
                    int num114 = 55;
                    int num115 = 3;
                    int num116 = num113 % num114;
                    int num117 = num113 / num114;
                    if (rCurrentNPC.direction == 1)
                    {
                        num117 += num115;
                    }
                    for (int num118 = 0; num118 < 2; num118++)
                    {
                        for (int num119 = 0; num119 < 3; num119++)
{
                            int num120 = num116 * 36 + num118 * 18;
                            int num121 = num117 * 54 + num119 * 18;
                            Microsoft.Xna.Framework.Rectangle rectangle6 = new Microsoft.Xna.Framework.Rectangle(num120, num121, 16, 16);
                            Vector2 vector39 = new Vector2(1f - (float)num118, 1.5f - (float)num119) * 16f;
                            mySpriteBatch.Draw(value9, vector38, new Microsoft.Xna.Framework.Rectangle?(rectangle6), alpha, rotation3, vector39, 1f, spriteEffects3, 0f);
                        }
                    }
                    return;
                }
                if (type == 657)
                {
                    Texture2D value10 = TextureAssets.Npc[type].Value;
                    Vector2 vector40 = rCurrentNPC.Bottom - screenPos;
                    vector40.Y += 2f;
                    int num122 = Main.npcFrameCount[rCurrentNPC.type];
                    int num123 = rCurrentNPC.frame.Y / rCurrentNPC.frame.Height;
                    Microsoft.Xna.Framework.Rectangle rectangle7 = value10.Frame(2, 16, num123 / num122, num123 % num122, 0, 0);
                    rectangle7.Inflate(0, -2);
                    Vector2 vector41 = rectangle7.Size() * new Vector2(0.5f, 1f);
                    Microsoft.Xna.Framework.Color color27 = Microsoft.Xna.Framework.Color.Lerp(Microsoft.Xna.Framework.Color.White, color10, 0.5f);
                    if (rCurrentNPC.life <= rCurrentNPC.lifeMax / 2)
                    {
                        this.DrawNPCDirect_QueenSlimeWings(rCurrentNPC, mySpriteBatch, screenPos, rCurrentNPC.Center, color27);
                    }
                    Texture2D value11 = TextureAssets.Extra[186].Value;
                    Microsoft.Xna.Framework.Rectangle rectangle8 = value11.Frame(1, 1, 0, 0, 0, 0);
                    Vector2 vector42 = rectangle8.Size() * new Vector2(0.5f, 0.5f);
                    Vector2 vector43 = new Vector2(rCurrentNPC.Center.X, rCurrentNPC.Center.Y);
                    float num124 = 0f;
                    switch (num123)
                    {
                    case 1:
                    case 6:
                        num124 -= 10f;
                        break;
                    case 3:
                    case 5:
                        num124 += 10f;
                        break;
                    case 4:
                    case 12:
                    case 13:
                    case 14:
                    case 15:
                        num124 += 18f;
                        break;
                    case 7:
                    case 8:
                        num124 -= 14f;
                        break;
                    case 9:
                        num124 -= 16f;
                        break;
                    case 10:
                        num124 -= 18f;
                        break;
                    case 11:
                        num124 += 20f;
                        break;
                    case 20:
                        num124 -= 14f;
                        break;
                    case 21:
                    case 23:
                        num124 -= 18f;
                        break;
                    case 22:
                        num124 -= 22f;
                        break;
                    }
                    vector43.Y += num124;
                    if (rCurrentNPC.rotation != 0f)
                    {
                        vector43 = vector43.RotatedBy((double)rCurrentNPC.rotation, rCurrentNPC.Bottom);
                    }
                    vector43 -= screenPos;
                    if (!rCurrentNPC.IsABestiaryIconDummy)
                    {
                        mySpriteBatch.End();
                        mySpriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend, SamplerState.PointClamp, DepthStencilState.Default, RasterizerState.CullNone, null, Main.Transform);
                    }
                    GameShaders.Misc["QueenSlime"].Apply(null);
                    if (rCurrentNPC.ai[0] == 4f && rCurrentNPC.velocity.Y != 0f)
                    {
                        float num125 = 1f;
                        if (rCurrentNPC.ai[2] == 1f)
{
                            num125 = 6f;
                        }
                        for (int num126 = 7; num126 >= 0; num126--)
{
                            float num127 = 1f - (float)num126 / 8f;
                            Vector2 vector44 = rCurrentNPC.oldPos[num126] + new Vector2((float)rCurrentNPC.width * 0.5f, (float)rCurrentNPC.height);
                            vector44 -= (rCurrentNPC.Bottom - Vector2.Lerp(vector44, rCurrentNPC.Bottom, 0.75f)) * num125;
                            vector44 -= screenPos;
                            Microsoft.Xna.Framework.Color color28 = color27 * num127;
                            mySpriteBatch.Draw(value10, vector44, new Microsoft.Xna.Framework.Rectangle?(rectangle7), color28, rCurrentNPC.rotation, vector41, rCurrentNPC.scale, spriteEffects ^ SpriteEffects.FlipHorizontally, 0f);
                        }
                    }
                    if (!rCurrentNPC.IsABestiaryIconDummy)
                    {
                        mySpriteBatch.End();
                        mySpriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, Main.DefaultSamplerState, DepthStencilState.None, Main.Rasterizer, null, Main.Transform);
                    }
                    Main.pixelShader.CurrentTechnique.Passes[0].Apply();
                    mySpriteBatch.Draw(value11, vector43, new Microsoft.Xna.Framework.Rectangle?(rectangle8), color27, rCurrentNPC.rotation, vector42, 1f, spriteEffects ^ SpriteEffects.FlipHorizontally, 0f);
                    GameShaders.Misc["QueenSlime"].Apply(null);
                    if (!rCurrentNPC.IsABestiaryIconDummy)
                    {
                        mySpriteBatch.End();
                        mySpriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend, SamplerState.PointClamp, DepthStencilState.Default, RasterizerState.CullNone, null, Main.Transform);
                    }
                    DrawData drawData = new DrawData(value10, vector40, new Microsoft.Xna.Framework.Rectangle?(rectangle7), rCurrentNPC.GetAlpha(color27), rCurrentNPC.rotation, vector41, rCurrentNPC.scale, spriteEffects ^ SpriteEffects.FlipHorizontally, 0f);
                    GameShaders.Misc["QueenSlime"].Apply(new DrawData?(drawData));
                    drawData.Draw(mySpriteBatch);
                    Main.pixelShader.CurrentTechnique.Passes[0].Apply();
                    if (!rCurrentNPC.IsABestiaryIconDummy)
                    {
                        mySpriteBatch.End();
                        mySpriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, Main.DefaultSamplerState, DepthStencilState.None, Main.Rasterizer, null, Main.Transform);
                    }
                    Texture2D value12 = TextureAssets.Extra[177].Value;
                    rectangle7 = value12.Frame(1, 1, 0, 0, 0, 0);
                    vector41 = rectangle7.Size() * new Vector2(0.5f, 0.5f);
                    vector40 = new Vector2(rCurrentNPC.Center.X, rCurrentNPC.Top.Y - (float)rectangle7.Bottom + 44f);
                    float num128 = 0f;
                    switch (num123)
                    {
                    case 1:
                        num128 -= 10f;
                        break;
                    case 3:
                    case 5:
                    case 6:
                        num128 += 10f;
                        break;
                    case 4:
                    case 12:
                    case 13:
                    case 14:
                    case 15:
                        num128 += 18f;
                        break;
                    case 7:
                    case 8:
                        num128 -= 14f;
                        break;
                    case 9:
                        num128 -= 16f;
                        break;
                    case 10:
                        num128 -= 18f;
                        break;
                    case 11:
                        num128 += 20f;
                        break;
                    case 20:
                        num128 -= 14f;
                        break;
                    case 21:
                    case 23:
                        num128 -= 18f;
                        break;
                    case 22:
                        num128 -= 22f;
                        break;
                    }
                    vector40.Y += num128;
                    if (rCurrentNPC.rotation != 0f)
                    {
                        vector40 = vector40.RotatedBy((double)rCurrentNPC.rotation, rCurrentNPC.Bottom);
                    }
                    vector40 -= screenPos;
                    mySpriteBatch.Draw(value12, vector40, new Microsoft.Xna.Framework.Rectangle?(rectangle7), color27, rCurrentNPC.rotation, vector41, 1f, spriteEffects ^ SpriteEffects.FlipHorizontally, 0f);
                    return;
                }
                if (type == 576 || type == 577)
                {
                    Texture2D value13 = TextureAssets.Npc[type].Value;
                    Vector2 vector45 = rCurrentNPC.Bottom - screenPos;
                    Microsoft.Xna.Framework.Rectangle rectangle9 = value13.Frame(5, 10, rCurrentNPC.frame.Y / 10, rCurrentNPC.frame.Y % 10, 0, 0);
                    Vector2 vector46 = rectangle9.Size() * new Vector2(0.5f, 1f);
                    vector46.Y -= 4f;
                    int num129 = 94;
                    if (rCurrentNPC.spriteDirection == 1)
                    {
                        vector46.X = (float)num129;
                    }
                    else
                    {
                        vector46.X = (float)(rectangle9.Width - num129);
                    }
                    Microsoft.Xna.Framework.Color white = Microsoft.Xna.Framework.Color.White;
                    float num130 = 0f;
                    float num131 = 0f;
                    int num132 = 0;
                    float num133 = 0f;
                    Microsoft.Xna.Framework.Color color29 = color10;
                    if (rCurrentNPC.localAI[3] < 60f)
                    {
                        float num134 = rCurrentNPC.localAI[3] / 60f;
                        num132 = 3;
                        num133 = 1f - num134 * num134;
                        white = new Microsoft.Xna.Framework.Color(127, 0, 255, 0);
                        num131 = 1f;
                        color29 = Microsoft.Xna.Framework.Color.Lerp(Microsoft.Xna.Framework.Color.Transparent, color29, num134 * num134);
                    }
                    for (int num135 = 0; num135 < num132; num135++)
                    {
                        Microsoft.Xna.Framework.Color color30 = color10;
                        color30 = Microsoft.Xna.Framework.Color.Lerp(color30, white, num130);
                        color30 = rCurrentNPC.GetAlpha(color30);
                        color30 = Microsoft.Xna.Framework.Color.Lerp(color30, white, num131);
                        color30 *= 1f - num133;
                        Vector2 vector47 = vector45;
                        vector47 -= new Vector2((float)value13.Width, (float)(value13.Height / Main.npcFrameCount[type])) * rCurrentNPC.scale / 2f;
                        vector47 += vector10 * rCurrentNPC.scale + new Vector2(0f, num58 + num59 + rCurrentNPC.gfxOffY);
                        mySpriteBatch.Draw(value13, vector47, new Microsoft.Xna.Framework.Rectangle?(rectangle9), color30, rCurrentNPC.rotation, vector46, rCurrentNPC.scale, spriteEffects ^ SpriteEffects.FlipHorizontally, 0f);
                    }
                    mySpriteBatch.Draw(value13, vector45, new Microsoft.Xna.Framework.Rectangle?(rectangle9), rCurrentNPC.GetAlpha(color29), rCurrentNPC.rotation, vector46, rCurrentNPC.scale, spriteEffects ^ SpriteEffects.FlipHorizontally, 0f);
                    return;
                }
                if (type == 696)
                {
                    Texture2D value14 = TextureAssets.Npc[type].Value;
                    Vector2 vector48 = rCurrentNPC.Bottom - screenPos;
                    Microsoft.Xna.Framework.Rectangle rectangle10 = value14.Frame(6, 27, rCurrentNPC.frame.Y / 9, rCurrentNPC.frame.Y % 9, 0, 0);
                    Vector2 vector49 = rectangle10.Size() * new Vector2(0.5f, 1f);
                    vector49.Y -= 4f;
                    Microsoft.Xna.Framework.Color color31 = color10;
                    mySpriteBatch.Draw(value14, vector48, new Microsoft.Xna.Framework.Rectangle?(rectangle10), rCurrentNPC.GetAlpha(color31), rCurrentNPC.rotation, vector49, rCurrentNPC.scale, spriteEffects, 0f);
                    rectangle10.Y += rectangle10.Height * 18;
                    ulong tileFrameSeed = Main.TileFrameSeed;
                    for (int num136 = 0; num136 < 2; num136++)
                    {
                        Vector2 zero3 = new Vector2((float)Utils.RandomInt(ref tileFrameSeed, -1, 2), (float)Utils.RandomInt(ref tileFrameSeed, -1, 2));
                        if (num136 == 0)
{
                            zero3 = Vector2.Zero;
                        }
                        mySpriteBatch.Draw(value14, vector48 + zero3, new Microsoft.Xna.Framework.Rectangle?(rectangle10), new Microsoft.Xna.Framework.Color(255, 255, 255, 127) * rCurrentNPC.Opacity, rCurrentNPC.rotation, vector49, rCurrentNPC.scale, spriteEffects, 0f);
                    }
                    if (rCurrentNPC.ai[0] == 2f)
                    {
                        int num137 = 60;
                        int num138 = 0;
                        if (rCurrentNPC.ai[1] < (float)num137)
{
                            EmoteBubble.DrawTemporaryBubble(Main.spriteBatch, num138, num137, num137 - (int)rCurrentNPC.ai[1], rCurrentNPC);
                            return;
                        }
                    }
                }
                else
                {
                    if (type == 594)
                    {
                        Texture2D value15 = TextureAssets.Npc[type].Value;
                        Vector2 vector50 = rCurrentNPC.Top - screenPos;
                        Microsoft.Xna.Framework.Rectangle rectangle11 = value15.Frame(8, 1, rCurrentNPC.frame.Y, 0, 0, 0);
                        Microsoft.Xna.Framework.Rectangle rectangle12 = value15.Frame(8, 1, 0, 0, 0, 0);
                        Vector2 vector51 = rectangle11.Size() * new Vector2(0.5f, 0f);
                        Microsoft.Xna.Framework.Color color32 = color10;
                        float num139 = 1f;
                        NPC npc = rCurrentNPC.AI_113_WindyBalloon_GetSlaveNPC();
                        if (npc != null)
{
                            num139 = npc.scale;
                            if (npc.ai[1] > 0f)
{
                                Main.DrawNPC_SlimeItem(npc, npc.type, color32, rCurrentNPC.rotation);
                            }
                            mySpriteBatch.Draw(value15, vector50, new Microsoft.Xna.Framework.Rectangle?(rectangle12), npc.GetAlpha(color32), rCurrentNPC.rotation, vector51, num139, spriteEffects, 0f);
                            mySpriteBatch.Draw(value15, vector50, new Microsoft.Xna.Framework.Rectangle?(rectangle12), npc.GetColor(color32), rCurrentNPC.rotation, vector51, num139, spriteEffects, 0f);
                        }
                        mySpriteBatch.Draw(value15, vector50, new Microsoft.Xna.Framework.Rectangle?(rectangle11), rCurrentNPC.GetAlpha(color32), rCurrentNPC.rotation, vector51, num139, spriteEffects, 0f);
                        return;
                    }
                    if (type == 686)
                    {
                        Texture2D value16 = TextureAssets.Npc[type].Value;
                        Vector2 vector52 = rCurrentNPC.Top - screenPos;
                        Microsoft.Xna.Framework.Rectangle rectangle13 = value16.Frame(1, 1, 0, 0, 0, 0);
                        Vector2 vector53 = rectangle13.Size() * new Vector2(0.5f, 0f);
                        Microsoft.Xna.Framework.Color color33 = color10;
                        mySpriteBatch.Draw(value16, vector52, new Microsoft.Xna.Framework.Rectangle?(rectangle13), rCurrentNPC.GetAlpha(color33), rCurrentNPC.rotation, vector53, rCurrentNPC.scale, spriteEffects, 0f);
                        return;
                    }
                    if (type == 564 || type == 565)
                    {
                        Texture2D value17 = TextureAssets.Npc[type].Value;
                        Vector2 vector54 = rCurrentNPC.Bottom - screenPos;
                        Microsoft.Xna.Framework.Rectangle rectangle14 = value17.Frame(5, 9, rCurrentNPC.frame.Y / 9, rCurrentNPC.frame.Y % 9, 0, 0);
                        Vector2 vector55 = rectangle14.Size() * new Vector2(0.5f, 1f);
                        vector55.Y -= 10f;
                        int num140 = 52;
                        if (rCurrentNPC.spriteDirection == 1)
{
                            vector55.X = (float)num140;
                        }
                        else
{
                            vector55.X = (float)(rectangle14.Width - num140);
                        }
                        Microsoft.Xna.Framework.Color white2 = Microsoft.Xna.Framework.Color.White;
                        float num141 = 0f;
                        float num142 = 0f;
                        int num143 = 0;
                        float num144 = 0f;
                        float num145 = 0f;
                        Microsoft.Xna.Framework.Color color34 = color10;
                        if (rCurrentNPC.localAI[3] < 60f)
{
                            float num146 = 8f;
                            float num147 = rCurrentNPC.localAI[3] / 60f;
                            num143 = 3;
                            num144 = 1f - num147 * num147;
                            num145 = num146;
                            white2 = new Microsoft.Xna.Framework.Color(127, 0, 255, 0);
                            num142 = 1f;
                            color34 = Microsoft.Xna.Framework.Color.Lerp(Microsoft.Xna.Framework.Color.Transparent, color34, num147 * num147);
                        }
                        for (int num148 = 0; num148 < num143; num148++)
{
                            Microsoft.Xna.Framework.Color color35 = color10;
                            color35 = Microsoft.Xna.Framework.Color.Lerp(color35, white2, num141);
                            color35 = rCurrentNPC.GetAlpha(color35);
                            color35 = Microsoft.Xna.Framework.Color.Lerp(color35, white2, num142);
                            color35 *= 1f - num144;
                            Vector2 vector56 = vector54;
                            vector56 -= new Vector2((float)value17.Width, (float)(value17.Height / Main.npcFrameCount[type])) * rCurrentNPC.scale / 2f;
                            vector56 += vector10 * rCurrentNPC.scale + new Vector2(0f, num58 + num59 + rCurrentNPC.gfxOffY);
                            vector56 += ((float)num148 / (float)num143 * 6.2831855f).ToRotationVector2() * num145 * num144;
                            mySpriteBatch.Draw(value17, vector56, new Microsoft.Xna.Framework.Rectangle?(rectangle14), color35, rCurrentNPC.rotation, vector55, rCurrentNPC.scale, spriteEffects ^ SpriteEffects.FlipHorizontally, 0f);
                        }
                        Microsoft.Xna.Framework.Color alpha2 = rCurrentNPC.GetAlpha(color34);
                        num143 = 4;
                        num145 = 4f;
                        num144 = 0.625f + (float)Math.Sin((double)(Main.GlobalTimeWrappedHourly * 6.2831855f * 0.75f + 3.1415927f)) * 0.125f;
                        for (int num149 = 0; num149 < num143; num149++)
{
                            Microsoft.Xna.Framework.Color color36 = alpha2;
                            color36 *= 1f - num144;
                            Vector2 vector57 = vector54;
                            vector57 -= new Vector2((float)value17.Width, (float)(value17.Height / Main.npcFrameCount[type])) * rCurrentNPC.scale / 2f;
                            vector57 += vector10 * rCurrentNPC.scale + new Vector2(0f, num58 + num59 + rCurrentNPC.gfxOffY);
                            vector57 += ((float)num149 / (float)num143 * 6.2831855f).ToRotationVector2() * num145 * num144;
                            mySpriteBatch.Draw(value17, vector57, new Microsoft.Xna.Framework.Rectangle?(rectangle14), color36, rCurrentNPC.rotation, vector55, rCurrentNPC.scale, spriteEffects ^ SpriteEffects.FlipHorizontally, 0f);
                        }
                        mySpriteBatch.Draw(value17, vector54, new Microsoft.Xna.Framework.Rectangle?(rectangle14), alpha2, rCurrentNPC.rotation, vector55, rCurrentNPC.scale, spriteEffects ^ SpriteEffects.FlipHorizontally, 0f);
                        if (rCurrentNPC.Opacity > 0f)
{
                            Microsoft.Xna.Framework.Color color37 = Microsoft.Xna.Framework.Color.White;
                            color37.A /= 2;
                            color37 *= rCurrentNPC.Opacity;
                            mySpriteBatch.Draw(TextureAssets.GlowMask[225].Value, vector54, new Microsoft.Xna.Framework.Rectangle?(rectangle14), color37, rCurrentNPC.rotation, vector55, rCurrentNPC.scale, spriteEffects ^ SpriteEffects.FlipHorizontally, 0f);
                            num143 = 4;
                            num145 = 4f;
                            num144 = 0.5f + (float)Math.Sin((double)(Main.GlobalTimeWrappedHourly * 6.2831855f * 0.75f)) * 0.5f;
                            for (int num150 = 0; num150 < num143; num150++)
{
                                Microsoft.Xna.Framework.Color color38 = color37 * 0.35f;
                                color38 *= 1f - num144;
                                Vector2 vector58 = vector54;
                                vector58 -= new Vector2((float)value17.Width, (float)(value17.Height / Main.npcFrameCount[type])) * rCurrentNPC.scale / 2f;
                                vector58 += vector10 * rCurrentNPC.scale + new Vector2(0f, num58 + num59 + rCurrentNPC.gfxOffY);
                                vector58 += ((float)num150 / (float)num143 * 6.2831855f).ToRotationVector2() * num145 * num144;
                                mySpriteBatch.Draw(TextureAssets.GlowMask[225].Value, vector58, new Microsoft.Xna.Framework.Rectangle?(rectangle14), color38, rCurrentNPC.rotation, vector55, rCurrentNPC.scale, spriteEffects ^ SpriteEffects.FlipHorizontally, 0f);
                            }
                            return;
                        }
                    }
                    else if (type == 548)
                    {
                        Texture2D texture2D3 = TextureAssets.Npc[type].Value;
                        Vector2 vector59 = rCurrentNPC.Bottom - screenPos;
                        Microsoft.Xna.Framework.Rectangle rectangle15 = texture2D3.Frame(1, 1, 0, 0, 0, 0);
                        Vector2 vector60 = rectangle15.Size() / 2f;
                        vector60.Y += 30f;
                        vector60.Y += 8f;
                        vector60.X -= 1f;
                        Microsoft.Xna.Framework.Color white3 = Microsoft.Xna.Framework.Color.White;
                        float num151 = 0f;
                        float num152 = 0f;
                        int num153 = 0;
                        float num154 = 0f;
                        float num155 = 0f;
                        Microsoft.Xna.Framework.Color color39 = color10;
                        for (int num156 = 0; num156 < num153; num156++)
{
                            Microsoft.Xna.Framework.Color color40 = color10;
                            color40 = Microsoft.Xna.Framework.Color.Lerp(color40, white3, num151);
                            color40 = rCurrentNPC.GetAlpha(color40);
                            color40 = Microsoft.Xna.Framework.Color.Lerp(color40, white3, num152);
                            color40 *= 1f - num154;
                            Vector2 vector61 = vector59;
                            vector61 -= new Vector2((float)texture2D3.Width, (float)(texture2D3.Height / Main.npcFrameCount[type])) * rCurrentNPC.scale / 2f;
                            vector61 += vector10 * rCurrentNPC.scale + new Vector2(0f, num58 + num59 + rCurrentNPC.gfxOffY);
                            vector61 += ((float)num156 / (float)num153 * 6.2831855f).ToRotationVector2() * num155 * num154;
                            mySpriteBatch.Draw(texture2D3, vector61, new Microsoft.Xna.Framework.Rectangle?(rectangle15), color40, rCurrentNPC.rotation, vector60, rCurrentNPC.scale, spriteEffects ^ SpriteEffects.FlipHorizontally, 0f);
                        }
                        Microsoft.Xna.Framework.Color alpha3 = rCurrentNPC.GetAlpha(color39);
                        num153 = 4;
                        num155 = 4f;
                        num154 = 0.625f + (float)Math.Sin((double)(Main.GlobalTimeWrappedHourly * 6.2831855f * 0.75f + 3.1415927f)) * 0.125f;
                        for (int num157 = 0; num157 < num153; num157++)
{
                            Microsoft.Xna.Framework.Color color41 = alpha3;
                            color41.A = 0;
                            color41 *= 1f - num154;
                            Vector2 vector62 = vector59;
                            vector62 -= new Vector2((float)texture2D3.Width, (float)(texture2D3.Height / Main.npcFrameCount[type])) * rCurrentNPC.scale / 2f;
                            vector62 += vector10 * rCurrentNPC.scale + new Vector2(0f, num58 + num59 + rCurrentNPC.gfxOffY);
                            vector62 += ((float)num157 / (float)num153 * 6.2831855f).ToRotationVector2() * num155 * num154;
                            mySpriteBatch.Draw(texture2D3, vector62, new Microsoft.Xna.Framework.Rectangle?(rectangle15), color41, rCurrentNPC.rotation, vector60, rCurrentNPC.scale, spriteEffects ^ SpriteEffects.FlipHorizontally, 0f);
                        }
                        mySpriteBatch.Draw(texture2D3, vector59, new Microsoft.Xna.Framework.Rectangle?(rectangle15), alpha3, rCurrentNPC.rotation, vector60, rCurrentNPC.scale, spriteEffects ^ SpriteEffects.FlipHorizontally, 0f);
                        if (rCurrentNPC.ai[1] == 2f)
{
                            float num158 = Math.Min(1f, rCurrentNPC.ai[0] / 120f);
                            mySpriteBatch.Draw(texture2D3, vector59, new Microsoft.Xna.Framework.Rectangle?(rectangle15), new Microsoft.Xna.Framework.Color(1f, 1f, 1f, 0f) * num158, rCurrentNPC.rotation, vector60, rCurrentNPC.scale, spriteEffects ^ SpriteEffects.FlipHorizontally, 0f);
                            float num159 = MathHelper.Clamp(rCurrentNPC.ai[0] / 450f, 0f, 1f);
                            if (!Terraria.Graphics.Effects.Filters.Scene["CrystalWin"].IsActive())
{
                                Terraria.Graphics.Effects.Filters.Scene.Activate("CrystalWin", rCurrentNPC.Center, new object[0]);
                            }
                            else
{
                                Terraria.Graphics.Effects.Filters.Scene["CrystalWin"].GetShader().UseProgress(num159);
                            }
                            Terraria.Graphics.Effects.Filters.Scene["CrystalWin"].GetShader().UseTargetPosition(rCurrentNPC.Center);
                        }
                        num153 = 4;
                        num155 = 4f;
                        num154 = 0.625f + (float)Math.Sin((double)(Main.GlobalTimeWrappedHourly * 6.2831855f * 0.75f)) * 0.125f;
                        for (int num160 = 0; num160 < num153; num160++)
{
                            Microsoft.Xna.Framework.Color color42 = alpha3;
                            color42.A = 0;
                            color42 *= 0.3f;
                            color42 *= 1f - num154;
                            Vector2 vector63 = vector59;
                            vector63 -= new Vector2((float)texture2D3.Width, (float)(texture2D3.Height / Main.npcFrameCount[type])) * rCurrentNPC.scale / 2f;
                            vector63 += vector10 * rCurrentNPC.scale + new Vector2(0f, num58 + num59 + rCurrentNPC.gfxOffY);
                            vector63 += ((float)num160 / (float)num153 * 6.2831855f).ToRotationVector2() * num155 * num154;
                            mySpriteBatch.Draw(texture2D3, vector63, new Microsoft.Xna.Framework.Rectangle?(rectangle15), color42, rCurrentNPC.rotation, vector60, rCurrentNPC.scale, spriteEffects ^ SpriteEffects.FlipHorizontally, 0f);
                        }
                        if (rCurrentNPC.alpha < 255)
{
                            float num161 = Main.GlobalTimeWrappedHourly % 3f / 3f;
                            float num162 = num161;
                            if (num162 > 0.5f)
{
                                num162 = 1f - num161;
                            }
                            if (num162 < 0f)
{
                                num162 = 0f;
                            }
                            float num163 = (num161 + 0.5f) % 1f;
                            float num164 = num163;
                            if (num164 > 0.5f)
{
                                num164 = 1f - num163;
                            }
                            if (num164 < 0f)
{
                                num164 = 0f;
                            }
                            texture2D3 = TextureAssets.GlowMask[239].Value;
                            rectangle15 = texture2D3.Frame(1, 1, 0, 0, 0, 0);
                            vector60 = rectangle15.Size() / 2f;
                            Vector2 vector64 = vector59 + new Vector2(0f, -40f);
                            Microsoft.Xna.Framework.Color color43 = new Microsoft.Xna.Framework.Color(140, 50, 255, 0);
                            color43 *= 0.6f;
                            mySpriteBatch.Draw(texture2D3, vector64, new Microsoft.Xna.Framework.Rectangle?(rectangle15), color43, rCurrentNPC.rotation, vector60, rCurrentNPC.scale * 0.75f, spriteEffects ^ SpriteEffects.FlipHorizontally, 0f);
                            num154 = 1f + num161 * 0.75f;
                            mySpriteBatch.Draw(texture2D3, vector64, new Microsoft.Xna.Framework.Rectangle?(rectangle15), color43 * num162, rCurrentNPC.rotation, vector60, rCurrentNPC.scale * 0.75f * num154, spriteEffects ^ SpriteEffects.FlipHorizontally, 0f);
                            num154 = 1f + num163 * 0.75f;
                            mySpriteBatch.Draw(texture2D3, vector64, new Microsoft.Xna.Framework.Rectangle?(rectangle15), color43 * num164, rCurrentNPC.rotation, vector60, rCurrentNPC.scale * 0.75f * num154, spriteEffects ^ SpriteEffects.FlipHorizontally, 0f);
                            texture2D3 = TextureAssets.Extra[89].Value;
                            rectangle15 = texture2D3.Frame(1, 1, 0, 0, 0, 0);
                            vector60 = rectangle15.Size() / 2f;
                            Vector2 vector65 = new Vector2(0.75f, 1f + num154) * 1.5f;
                            num154 = 1f + num163 * 0.75f;
                            if (rCurrentNPC.dontTakeDamageFromHostiles)
{
                                vector65.Y *= 0.6f;
                            }
                            vector64.Y -= 6f;
                            mySpriteBatch.Draw(texture2D3, vector64, new Microsoft.Xna.Framework.Rectangle?(rectangle15), color43 * num164, rCurrentNPC.rotation + 1.5707964f, vector60, vector65, spriteEffects ^ SpriteEffects.FlipHorizontally, 0f);
                            mySpriteBatch.Draw(texture2D3, vector64, new Microsoft.Xna.Framework.Rectangle?(rectangle15), Microsoft.Xna.Framework.Color.Lerp(color43, Microsoft.Xna.Framework.Color.White, 0.5f), rCurrentNPC.rotation + 1.5707964f, vector60, 1.5f, spriteEffects ^ SpriteEffects.FlipHorizontally, 0f);
                            return;
                        }
                    }
                    else
                    {
                        if (type == 371 || (type >= 454 && type <= 459) || (type >= 621 && type <= 623))
{
                            Texture2D value18 = TextureAssets.Npc[type].Value;
                            Vector2 vector66 = rCurrentNPC.Center - screenPos;
                            vector66 -= new Vector2((float)value18.Width, (float)(value18.Height / Main.npcFrameCount[type])) * rCurrentNPC.scale / 2f;
                            vector66 += vector10 * rCurrentNPC.scale + new Vector2(0f, num58 + num59 + rCurrentNPC.gfxOffY);
                            mySpriteBatch.Draw(value18, vector66, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), rCurrentNPC.GetAlpha(color10), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                            return;
                        }
                        if (type == 549)
{
                            Texture2D value19 = TextureAssets.Npc[type].Value;
                            Vector2 vector67 = rCurrentNPC.Center - screenPos;
                            Microsoft.Xna.Framework.Rectangle frame2 = rCurrentNPC.frame;
                            Vector2 vector68 = new Vector2(70f, 127f);
                            vector68.Y += 8f;
                            Vector2 vector69 = new Vector2(rCurrentNPC.scale);
                            float num165 = rCurrentNPC.localAI[0];
                            if (num165 < 120f)
{
                                vector69 *= num165 / 240f + 0.5f;
                            }
                            Microsoft.Xna.Framework.Color alpha4 = rCurrentNPC.GetAlpha(color10);
                            float lerpValue2 = Utils.GetLerpValue(0f, 120f, num165, true);
                            float num166 = MathHelper.Lerp(32f, 0f, lerpValue2);
                            Microsoft.Xna.Framework.Color color44 = alpha4;
                            color44.A = (byte)MathHelper.Lerp((float)color44.A, 0f, lerpValue2);
                            color44 *= lerpValue2;
                            if (num165 >= 120f)
{
                                color44 = alpha4;
                            }
                            mySpriteBatch.Draw(value19, vector67, new Microsoft.Xna.Framework.Rectangle?(frame2), color44, rCurrentNPC.rotation, vector68, vector69, spriteEffects, 0f);
                            float y2 = (((rCurrentNPC.ai[0] + 54f) % 180f - 120f) / 180f * 2f * 6.2831855f).ToRotationVector2().Y;
                            if (num165 >= 120f)
{
                                num166 = y2 * 0f;
                                color44.A = (byte)((float)color44.A * 0.5f);
                                color44 *= y2 / 2f + 0.5f;
                                float num167 = 1f;
                                for (float num168 = 0f; num168 < num167; num168 += 1f)
{
                                    mySpriteBatch.Draw(value19, vector67 + (6.2831855f / num167 * num168).ToRotationVector2() * num166, new Microsoft.Xna.Framework.Rectangle?(frame2), color44, rCurrentNPC.rotation, vector68, vector69, spriteEffects, 0f);
                                }
                            }
                            float num169 = rCurrentNPC.ai[0] / 180f - 0.76f;
                            if (num169 < 0f)
{
                                num169 += 1f;
                            }
                            float num170 = 0f;
                            float num171 = 0f;
                            float num172 = 0.6f;
                            float num173 = 0.8f;
                            if (num169 >= num172 && num169 <= num173)
{
                                num170 = Utils.GetLerpValue(num172, num173, num169, false);
                                num171 = MathHelper.Lerp(0.75f, 0.85f, num170);
                            }
                            num172 = num173;
                            num173 = num172 + 0.13f;
                            if (num169 >= num172 && num169 <= num173)
{
                                num170 = 1f - Utils.GetLerpValue(num172, num173, num169, false);
                                num171 = MathHelper.Lerp(1.3f, 0.85f, num170);
                            }
                            Vector2 vector70 = new Vector2(0f, -150f);
                            int num174 = frame2.Y / frame2.Height;
                            float num175 = MathHelper.Clamp((num165 - 100f) / 40f, 0f, 1f);
                            this.DrawElderEye(mySpriteBatch, rCurrentNPC.Center + vector70, 0.75f * num175, 0.75f, num174, Microsoft.Xna.Framework.Color.White);
                            this.DrawElderEye(mySpriteBatch, rCurrentNPC.Center + vector70, 0.75f * num175, 0.75f, num174, new Microsoft.Xna.Framework.Color(255, 255, 255, 127) * (y2 / 2f + 0.5f));
                            if (num170 > 0f && num171 > 0f)
{
                                this.DrawElderEye(mySpriteBatch, rCurrentNPC.Center + vector70, num170 * 0.5f, num171, num174, new Microsoft.Xna.Framework.Color(255, 255, 255, 127));
                            }
                            if (num165 < 120f)
{
                                float num176 = 6.2831855f * lerpValue2 * (float)Math.Pow((double)lerpValue2, 2.0) * 2f + lerpValue2;
                                color44.A = (byte)((float)alpha4.A * (float)Math.Pow((double)lerpValue2, 2.0) * 0.5f);
                                float num177 = 3f;
                                for (float num178 = 0f; num178 < num177; num178 += 1f)
{
                                    mySpriteBatch.Draw(value19, vector67 + (num176 + 6.2831855f / num177 * num178).ToRotationVector2() * num166, new Microsoft.Xna.Framework.Rectangle?(frame2), color44, rCurrentNPC.rotation, vector68, vector69, spriteEffects, 0f);
                                }
                                return;
                            }
                        }
                        else
{
                            if (type == 636)
{
                                Main.DrawNPCDirect_HallowBoss(mySpriteBatch, rCurrentNPC, ref screenPos, type, ref color10, ref vector10, spriteEffects);
                                return;
                            }
                            if (type == 677)
{
                                Main.DrawNPCDirect_Faeling(mySpriteBatch, rCurrentNPC, ref screenPos, type, ref color10, ref vector10, spriteEffects);
                                return;
                            }
                            if (type == 668)
{
                                Main.DrawNPCDirect_Deerclops(mySpriteBatch, rCurrentNPC, ref screenPos, type, ref color10, ref vector10, spriteEffects);
                                return;
                            }
                            if (type == 493 || type == 507 || type == 422 || type == 517)
{
                                Texture2D texture2D4 = TextureAssets.Npc[type].Value;
                                Vector2 vector71 = rCurrentNPC.Center - screenPos;
                                Vector2 vector72 = vector71 - new Vector2(300f, 310f);
                                vector71 -= new Vector2((float)texture2D4.Width, (float)(texture2D4.Height / Main.npcFrameCount[type])) * rCurrentNPC.scale / 2f;
                                vector71 += vector10 * rCurrentNPC.scale + new Vector2(0f, num58 + num59 + rCurrentNPC.gfxOffY);
                                mySpriteBatch.Draw(texture2D4, vector71, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), rCurrentNPC.GetAlpha(color10), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                if (type == 493)
{
                                    texture2D4 = TextureAssets.GlowMask[132].Value;
                                    float num179 = 4f + (rCurrentNPC.GetAlpha(color10).ToVector3() - new Vector3(0.5f)).Length() * 4f;
                                    for (int num180 = 0; num180 < 4; num180++)
{
                                        mySpriteBatch.Draw(texture2D4, vector71 + rCurrentNPC.velocity.RotatedBy((double)((float)num180 * 1.5707964f), default(Vector2)) * num179, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(64, 64, 64, 0) * rCurrentNPC.Opacity, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                    }
                                }
                                else if (type == 507)
{
                                    texture2D4 = TextureAssets.GlowMask[143].Value;
                                    float num181 = 4f + (rCurrentNPC.GetAlpha(color10).ToVector3() - new Vector3(0.5f)).Length() * 4f;
                                    for (int num182 = 0; num182 < 4; num182++)
{
                                        mySpriteBatch.Draw(texture2D4, vector71 + rCurrentNPC.velocity.RotatedBy((double)((float)num182 * 1.5707964f), default(Vector2)) * num181, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(64, 64, 64, 0) * rCurrentNPC.Opacity, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                    }
                                }
                                else if (type == 422)
{
                                    texture2D4 = TextureAssets.GlowMask[149].Value;
                                    float num183 = 4f + (rCurrentNPC.GetAlpha(color10).ToVector3() - new Vector3(0.5f)).Length() * 4f;
                                    for (int num184 = 0; num184 < 4; num184++)
{
                                        mySpriteBatch.Draw(texture2D4, vector71 + rCurrentNPC.velocity.RotatedBy((double)((float)num184 * 1.5707964f), default(Vector2)) * num183, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(64, 64, 64, 0) * rCurrentNPC.Opacity, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                    }
                                }
                                else if (type == 517)
{
                                    texture2D4 = TextureAssets.GlowMask[162].Value;
                                    float num185 = 2f + (rCurrentNPC.GetAlpha(color10).ToVector3() - new Vector3(0.5f)).Length() * 9f;
                                    for (int num186 = 0; num186 < 4; num186++)
{
                                        mySpriteBatch.Draw(texture2D4, vector71 + rCurrentNPC.velocity.RotatedBy((double)((float)num186 * 1.5707964f), default(Vector2)) * num185 + Vector2.UnitX * 2f, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(64, 64, 64, 0) * rCurrentNPC.Opacity, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                    }
                                }
                                int num187 = 0;
                                string text = "";
                                if (type <= 493)
{
                                    if (type != 422)
{
                                        if (type == 493)
{
                                            num187 = NPC.ShieldStrengthTowerStardust;
                                            text = "Stardust";
                                        }
                                    }
                                    else
{
                                        num187 = NPC.ShieldStrengthTowerVortex;
                                        text = "Vortex";
                                    }
                                }
                                else if (type != 507)
{
                                    if (type == 517)
{
                                        num187 = NPC.ShieldStrengthTowerSolar;
                                        text = "Solar";
                                    }
                                }
                                else
{
                                    num187 = NPC.ShieldStrengthTowerNebula;
                                    text = "Nebula";
                                }
                                float num188 = (float)num187 / (float)NPC.ShieldStrengthTowerMax;
                                if (!rCurrentNPC.IsABestiaryIconDummy)
{
                                    if (num187 > 0)
{
                                        mySpriteBatch.End();
                                        mySpriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend, SamplerState.PointWrap, DepthStencilState.Default, RasterizerState.CullNone, null, Main.Transform);
                                        float num189 = 0f;
                                        if (rCurrentNPC.ai[3] > 0f && rCurrentNPC.ai[3] <= 30f)
{
                                            num189 = 1f - rCurrentNPC.ai[3] / 30f;
                                        }
                                        Terraria.Graphics.Effects.Filters.Scene[text].GetShader().UseIntensity(1f + num189).UseProgress(0f);
                                        DrawData drawData2 = new DrawData(Main.Assets.Request<Texture2D>("Images/Misc/Perlin", 1).Value, vector72 + new Vector2(300f, 300f), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, 600, 600)), Microsoft.Xna.Framework.Color.White * (num188 * 0.8f + 0.2f), rCurrentNPC.rotation, new Vector2(300f, 300f), rCurrentNPC.scale * (1f + num189 * 0.05f), spriteEffects, 0f);
                                        GameShaders.Misc["ForceField"].UseColor(new Vector3(1f + num189 * 0.5f));
                                        GameShaders.Misc["ForceField"].Apply(new DrawData?(drawData2));
                                        drawData2.Draw(mySpriteBatch);
                                        mySpriteBatch.End();
                                        mySpriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, Main.DefaultSamplerState, DepthStencilState.None, Main.Rasterizer, null, Main.Transform);
                                        return;
                                    }
                                    if (rCurrentNPC.ai[3] > 0f)
{
                                        mySpriteBatch.End();
                                        mySpriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend, SamplerState.PointWrap, DepthStencilState.Default, RasterizerState.CullNone, null, Main.Transform);
                                        float num190 = rCurrentNPC.ai[3] / 120f;
                                        float num191 = Math.Min(rCurrentNPC.ai[3] / 30f, 1f);
                                        Terraria.Graphics.Effects.Filters.Scene[text].GetShader().UseIntensity(Math.Min(5f, 15f * num190) + 1f).UseProgress(num190);
                                        DrawData drawData3 = new DrawData(Main.Assets.Request<Texture2D>("Images/Misc/Perlin", 1).Value, vector72 + new Vector2(300f, 300f), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, 600, 600)), new Microsoft.Xna.Framework.Color(new Vector4(1f - (float)Math.Sqrt((double)num191))), rCurrentNPC.rotation, new Vector2(300f, 300f), rCurrentNPC.scale * (1f + num191), spriteEffects, 0f);
                                        GameShaders.Misc["ForceField"].UseColor(new Vector3(2f));
                                        GameShaders.Misc["ForceField"].Apply(new DrawData?(drawData3));
                                        drawData3.Draw(mySpriteBatch);
                                        mySpriteBatch.End();
                                        mySpriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, Main.DefaultSamplerState, DepthStencilState.None, Main.Rasterizer, null, Main.Transform);
                                        return;
                                    }
                                    Terraria.Graphics.Effects.Filters.Scene[text].GetShader().UseIntensity(0f).UseProgress(0f);
                                    return;
                                }
                            }
                            else
{
                                if (type == 402)
{
                                    this.LoadNPC(403);
                                    this.LoadNPC(404);
                                    Texture2D texture2D5 = TextureAssets.Npc[rCurrentNPC.type].Value;
                                    Vector2 vector73 = rCurrentNPC.Center - screenPos;
                                    vector73 -= new Vector2((float)texture2D5.Width, (float)(texture2D5.Height / Main.npcFrameCount[rCurrentNPC.type])) * rCurrentNPC.scale / 2f;
                                    vector73 += vector10 * rCurrentNPC.scale + new Vector2(0f, num58 + num59 + rCurrentNPC.gfxOffY);
                                    int num192 = 0;
                                    float num193 = 2f / (float)rCurrentNPC.oldPos.Length * 0.7f;
                                    float num194 = 600f;
                                    float num195 = num194 - 30f;
                                    float num196 = Utils.Remap(rCurrentNPC.ai[2], 0f, num194, 0f, 1f, true);
                                    float num197 = 1f - Utils.Remap(num196, 0.5f, num195 / num194, 0f, 1f, true) * Utils.Remap(num196, num195 / num194, 1f, 1f, 0f, true);
                                    int num198 = rCurrentNPC.oldPos.Length - 1;
                                    while ((float)num198 >= 1f)
{
                                        for (int num199 = 0; num199 < 2; num199++)
{
                                            if (num192 == 0)
{
                                                texture2D5 = TextureAssets.Npc[404].Value;
                                            }
                                            else
{
                                                texture2D5 = TextureAssets.Npc[403].Value;
                                            }
                                            Vector2 vector74 = vector73 + rCurrentNPC.oldPos[num198] - rCurrentNPC.position;
                                            float num200 = rCurrentNPC.oldRot[num198];
                                            if (num198 >= 1 && num199 == 1)
{
                                                Vector2 vector75 = Vector2.Lerp(rCurrentNPC.oldPos[num198], rCurrentNPC.oldPos[num198 - 1], 0.5f) - rCurrentNPC.oldPos[num198];
                                                num200 = MathHelper.WrapAngle(rCurrentNPC.oldRot[num198 - 1] * 0.5f + rCurrentNPC.oldRot[num198] * 0.5f);
                                                vector74 += vector75;
                                            }
                                            float scale3 = rCurrentNPC.scale;
                                            mySpriteBatch.Draw(texture2D5, vector74, null, rCurrentNPC.GetAlpha(color10) * (0.8f - num193 * (float)num198 / 2f) * num197, num200, vector10, scale3, spriteEffects, 0f);
                                            if (num192 == 0)
{
                                                texture2D5 = TextureAssets.GlowMask[134].Value;
                                            }
                                            else
{
                                                texture2D5 = TextureAssets.GlowMask[133].Value;
                                            }
                                            mySpriteBatch.Draw(texture2D5, vector74, null, new Microsoft.Xna.Framework.Color(255, 255, 255, 0) * (1f - num193 * (float)num198 / 2f) * num197, num200, vector10, scale3, spriteEffects, 0f);
                                            num192++;
                                        }
                                        num198 -= 2;
                                    }
                                    texture2D5 = TextureAssets.Npc[rCurrentNPC.type].Value;
                                    mySpriteBatch.Draw(texture2D5, vector73, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), rCurrentNPC.GetAlpha(color10), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                    texture2D5 = TextureAssets.GlowMask[135].Value;
                                    mySpriteBatch.Draw(texture2D5, vector73, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(255, 255, 255, 0) * num197, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                    Main.DrawPrettyStarSparkle(Utils.Remap(rCurrentNPC.ai[2], 0f, num194, 0f, 1f, true), SpriteEffects.None, vector73, new Microsoft.Xna.Framework.Color(255, 255, 255, 0), Microsoft.Xna.Framework.Color.CornflowerBlue, num196, 0.5f, num195 / num194, num195 / num194, 1f, 6.2831855f * num196, new Vector2(2f, 2f), new Vector2(2f, 2f));
                                    return;
                                }
                                if (type == 519)
{
                                    Texture2D texture2D6 = TextureAssets.Npc[rCurrentNPC.type].Value;
                                    Vector2 vector76 = rCurrentNPC.Center - screenPos;
                                    vector76 -= new Vector2((float)texture2D6.Width, (float)(texture2D6.Height / Main.npcFrameCount[rCurrentNPC.type])) * rCurrentNPC.scale / 2f;
                                    vector76 += vector10 * rCurrentNPC.scale + new Vector2(0f, num58 + num59 + rCurrentNPC.gfxOffY);
                                    texture2D6 = TextureAssets.Npc[rCurrentNPC.type].Value;
                                    mySpriteBatch.Draw(texture2D6, vector76, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), rCurrentNPC.GetAlpha(color10), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                    int num201 = 0;
                                    float num202 = 1f / (float)rCurrentNPC.oldPos.Length * 0.7f;
                                    int num203 = rCurrentNPC.oldPos.Length - 1;
                                    while ((float)num203 >= 0f)
{
                                        float num204 = (float)(rCurrentNPC.oldPos.Length - num203) / (float)rCurrentNPC.oldPos.Length;
                                        Microsoft.Xna.Framework.Color color45 = Microsoft.Xna.Framework.Color.Pink;
                                        color45 *= 1f - num202 * (float)num203 / 1f;
                                        color45.A = (byte)((float)color45.A * (1f - num204));
                                        mySpriteBatch.Draw(texture2D6, vector76 + rCurrentNPC.oldPos[num203] - rCurrentNPC.position, null, color45, rCurrentNPC.oldRot[num203], vector10, rCurrentNPC.scale * MathHelper.Lerp(0.3f, 1.1f, num204), spriteEffects, 0f);
                                        num201++;
                                        num203--;
                                    }
                                    return;
                                }
                                if (type == 522)
{
                                    Texture2D texture2D7 = TextureAssets.Npc[rCurrentNPC.type].Value;
                                    Vector2 vector77 = rCurrentNPC.Center - screenPos;
                                    vector77 -= new Vector2((float)texture2D7.Width, (float)(texture2D7.Height / Main.npcFrameCount[rCurrentNPC.type])) * rCurrentNPC.scale / 2f;
                                    vector77 += vector10 * rCurrentNPC.scale + new Vector2(0f, num58 + num59 + rCurrentNPC.gfxOffY);
                                    int num205 = 0;
                                    float num206 = 1f / (float)rCurrentNPC.oldPos.Length * 1.1f;
                                    int num207 = rCurrentNPC.oldPos.Length - 1;
                                    while ((float)num207 >= 0f)
{
                                        float num208 = (float)(rCurrentNPC.oldPos.Length - num207) / (float)rCurrentNPC.oldPos.Length;
                                        Microsoft.Xna.Framework.Color color46 = Microsoft.Xna.Framework.Color.White;
                                        color46 *= 1f - num206 * (float)num207 / 1f;
                                        color46.A = (byte)((float)color46.A * (1f - num208));
                                        mySpriteBatch.Draw(texture2D7, vector77 + rCurrentNPC.oldPos[num207] - rCurrentNPC.position, null, color46, rCurrentNPC.oldRot[num207], vector10, rCurrentNPC.scale * MathHelper.Lerp(0.8f, 0.3f, num208), spriteEffects, 0f);
                                        num205++;
                                        num207--;
                                    }
                                    texture2D7 = TextureAssets.Extra[57].Value;
                                    mySpriteBatch.Draw(texture2D7, vector77, null, new Microsoft.Xna.Framework.Color(255, 255, 255, 0), 0f, texture2D7.Size() / 2f, rCurrentNPC.scale, spriteEffects, 0f);
                                    return;
                                }
                                if (type != 488)
{
                                    if (type == 370 || type == 372 || type == 373)
{
                                        Texture2D texture2D8 = TextureAssets.Npc[type].Value;
                                        Microsoft.Xna.Framework.Color color47 = Microsoft.Xna.Framework.Color.White;
                                        float num209 = 0f;
                                        bool flag8 = type == 370 && rCurrentNPC.ai[0] > 4f;
                                        bool flag9 = type == 370 && rCurrentNPC.ai[0] > 9f;
                                        int num210 = 120;
                                        int num211 = 60;
                                        Microsoft.Xna.Framework.Color color48 = color10;
                                        if (flag9)
{
                                            color10 = Main.buffColor(color10, 0.4f, 0.8f, 0.4f, 1f);
                                        }
                                        else if (flag8)
{
                                            color10 = Main.buffColor(color10, 0.5f, 0.7f, 0.5f, 1f);
                                        }
                                        else if (type == 370 && rCurrentNPC.ai[0] == 4f && rCurrentNPC.ai[2] > (float)num210)
{
                                            float num212 = rCurrentNPC.ai[2] - (float)num210;
                                            num212 /= (float)num211;
                                            color10 = Main.buffColor(color10, 1f - 0.5f * num212, 1f - 0.3f * num212, 1f - 0.5f * num212, 1f);
                                        }
                                        int num213 = 10;
                                        int num214 = 2;
                                        if (type == 370)
{
                                            if (rCurrentNPC.ai[0] == -1f)
{
                                                num213 = 0;
                                            }
                                            if (rCurrentNPC.ai[0] == 0f || rCurrentNPC.ai[0] == 5f || rCurrentNPC.ai[0] == 10f)
{
                                                num213 = 7;
                                            }
                                            if (rCurrentNPC.ai[0] == 1f)
{
                                                color47 = Microsoft.Xna.Framework.Color.Blue;
                                                num209 = 0.5f;
                                            }
                                            else
{
                                                color48 = color10;
                                            }
                                        }
                                        else if ((type == 372 || type == 373) && rCurrentNPC.ai[0] == 1f)
{
                                            color47 = Microsoft.Xna.Framework.Color.Blue;
                                            num209 = 0.5f;
                                        }
                                        for (int num215 = 1; num215 < num213; num215 += num214)
{
                                            Vector2[] oldPos2 = rCurrentNPC.oldPos;
                                            Microsoft.Xna.Framework.Color color49 = color48;
                                            color49 = Microsoft.Xna.Framework.Color.Lerp(color49, color47, num209);
                                            color49 = rCurrentNPC.GetAlpha(color49);
                                            color49 *= (float)(num213 - num215) / 15f;
                                            Vector2 vector78 = rCurrentNPC.oldPos[num215] + new Vector2((float)rCurrentNPC.width, (float)rCurrentNPC.height) / 2f - screenPos;
                                            vector78 -= new Vector2((float)texture2D8.Width, (float)(texture2D8.Height / Main.npcFrameCount[type])) * rCurrentNPC.scale / 2f;
                                            vector78 += vector10 * rCurrentNPC.scale + new Vector2(0f, num58 + num59 + rCurrentNPC.gfxOffY);
                                            mySpriteBatch.Draw(texture2D8, vector78, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), color49, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                        }
                                        int num216 = 0;
                                        float num217 = 0f;
                                        float num218 = 0f;
                                        if (type == 370)
{
                                            if (rCurrentNPC.ai[0] == -1f)
{
                                                num216 = 0;
                                            }
                                            if (rCurrentNPC.ai[0] == 3f || rCurrentNPC.ai[0] == 8f)
{
                                                int num219 = 60;
                                                int num220 = 30;
                                                if (rCurrentNPC.ai[2] > (float)num219)
{
                                                    num216 = 6;
                                                    num217 = 1f - (float)Math.Cos((double)((rCurrentNPC.ai[2] - (float)num219) / (float)num220 * 6.2831855f));
                                                    num217 /= 3f;
                                                    num218 = 40f;
                                                }
                                            }
                                            if (rCurrentNPC.ai[0] == 4f && rCurrentNPC.ai[2] > (float)num210)
{
                                                num216 = 6;
                                                num217 = 1f - (float)Math.Cos((double)((rCurrentNPC.ai[2] - (float)num210) / (float)num211 * 6.2831855f));
                                                num217 /= 3f;
                                                num218 = 60f;
                                            }
                                            if (rCurrentNPC.ai[0] == 9f && rCurrentNPC.ai[2] > (float)num210)
{
                                                num216 = 6;
                                                num217 = 1f - (float)Math.Cos((double)((rCurrentNPC.ai[2] - (float)num210) / (float)num211 * 6.2831855f));
                                                num217 /= 3f;
                                                num218 = 60f;
                                            }
                                            if (rCurrentNPC.ai[0] == 12f)
{
                                                num216 = 6;
                                                num217 = 1f - (float)Math.Cos((double)(rCurrentNPC.ai[2] / 30f * 6.2831855f));
                                                num217 /= 3f;
                                                num218 = 20f;
                                            }
                                        }
                                        for (int num221 = 0; num221 < num216; num221++)
{
                                            Microsoft.Xna.Framework.Color color50 = color10;
                                            color50 = Microsoft.Xna.Framework.Color.Lerp(color50, color47, num209);
                                            color50 = rCurrentNPC.GetAlpha(color50);
                                            color50 *= 1f - num217;
                                            Vector2 vector79 = rCurrentNPC.Center + ((float)num221 / (float)num216 * 6.2831855f + rCurrentNPC.rotation).ToRotationVector2() * num218 * num217 - screenPos;
                                            vector79 -= new Vector2((float)texture2D8.Width, (float)(texture2D8.Height / Main.npcFrameCount[type])) * rCurrentNPC.scale / 2f;
                                            vector79 += vector10 * rCurrentNPC.scale + new Vector2(0f, num58 + num59 + rCurrentNPC.gfxOffY);
                                            mySpriteBatch.Draw(texture2D8, vector79, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), color50, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                        }
                                        Vector2 vector80 = rCurrentNPC.Center - screenPos;
                                        vector80 -= new Vector2((float)texture2D8.Width, (float)(texture2D8.Height / Main.npcFrameCount[type])) * rCurrentNPC.scale / 2f;
                                        vector80 += vector10 * rCurrentNPC.scale + new Vector2(0f, num58 + num59 + rCurrentNPC.gfxOffY);
                                        mySpriteBatch.Draw(texture2D8, vector80, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), rCurrentNPC.GetAlpha(color10), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                        if (type == 370 && rCurrentNPC.ai[0] >= 4f)
{
                                            texture2D8 = TextureAssets.DukeFishron.Value;
                                            Microsoft.Xna.Framework.Color color51 = Microsoft.Xna.Framework.Color.Lerp(Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Color.Yellow, 0.5f);
                                            color47 = Microsoft.Xna.Framework.Color.Yellow;
                                            num209 = 1f;
                                            num217 = 0.5f;
                                            num218 = 10f;
                                            num214 = 1;
                                            if (rCurrentNPC.ai[0] == 4f)
{
                                                float num222 = rCurrentNPC.ai[2] - (float)num210;
                                                num222 /= (float)num211;
                                                color47 *= num222;
                                                color51 *= num222;
                                            }
                                            if (rCurrentNPC.ai[0] == 12f)
{
                                                float num223 = rCurrentNPC.ai[2];
                                                num223 /= 30f;
                                                if (num223 > 0.5f)
{
                                                    num223 = 1f - num223;
                                                }
                                                num223 *= 2f;
                                                num223 = 1f - num223;
                                                color47 *= num223;
                                                color51 *= num223;
                                            }
                                            for (int num224 = 1; num224 < num213; num224 += num214)
{
                                                Vector2[] oldPos3 = rCurrentNPC.oldPos;
                                                Microsoft.Xna.Framework.Color color52 = color51;
                                                color52 = Microsoft.Xna.Framework.Color.Lerp(color52, color47, num209);
                                                color52 *= (float)(num213 - num224) / 15f;
                                                Vector2 vector81 = rCurrentNPC.oldPos[num224] + new Vector2((float)rCurrentNPC.width, (float)rCurrentNPC.height) / 2f - screenPos;
                                                vector81 -= new Vector2((float)texture2D8.Width, (float)(texture2D8.Height / Main.npcFrameCount[type])) * rCurrentNPC.scale / 2f;
                                                vector81 += vector10 * rCurrentNPC.scale + new Vector2(0f, num58 + num59 + rCurrentNPC.gfxOffY);
                                                mySpriteBatch.Draw(texture2D8, vector81, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), color52, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                            }
                                            for (int num225 = 1; num225 < num216; num225++)
{
                                                Microsoft.Xna.Framework.Color color53 = color51;
                                                color53 = Microsoft.Xna.Framework.Color.Lerp(color53, color47, num209);
                                                color53 = rCurrentNPC.GetAlpha(color53);
                                                color53 *= 1f - num217;
                                                Vector2 vector82 = rCurrentNPC.Center + ((float)num225 / (float)num216 * 6.2831855f + rCurrentNPC.rotation).ToRotationVector2() * num218 * num217 - screenPos;
                                                vector82 -= new Vector2((float)texture2D8.Width, (float)(texture2D8.Height / Main.npcFrameCount[type])) * rCurrentNPC.scale / 2f;
                                                vector82 += vector10 * rCurrentNPC.scale + new Vector2(0f, num58 + num59 + rCurrentNPC.gfxOffY);
                                                mySpriteBatch.Draw(texture2D8, vector82, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), color53, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                            }
                                            mySpriteBatch.Draw(texture2D8, vector80, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), color51, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                            return;
                                        }
                                    }
                                    else
{
                                        if (type == 439 || type == 440)
{
                                            int num226 = rCurrentNPC.frame.Y / (TextureAssets.Npc[type].Height() / Main.npcFrameCount[type]);
                                            Texture2D value20 = TextureAssets.Npc[type].Value;
                                            Texture2D value21 = TextureAssets.Extra[30].Value;
                                            Microsoft.Xna.Framework.Rectangle rectangle16 = value21.Frame(1, 1, 0, 0, 0, 0);
                                            rectangle16.Height /= 2;
                                            if (num226 >= 4)
{
                                                rectangle16.Y += rectangle16.Height;
                                            }
                                            Microsoft.Xna.Framework.Color color54 = Microsoft.Xna.Framework.Color.White;
                                            float num227 = 0f;
                                            Microsoft.Xna.Framework.Color color55 = color10;
                                            int num228 = 0;
                                            int num229 = 0;
                                            int num230 = 0;
                                            if (rCurrentNPC.ai[0] == -1f)
{
                                                if (rCurrentNPC.ai[1] >= 320f && rCurrentNPC.ai[1] < 960f)
{
                                                    color54 = Microsoft.Xna.Framework.Color.White;
                                                    num227 = 0.5f;
                                                    num228 = 6;
                                                    num229 = 2;
                                                    num230 = 1;
                                                }
                                            }
                                            else if (rCurrentNPC.ai[0] == 1f)
{
                                                color54 = Microsoft.Xna.Framework.Color.White;
                                                num227 = 0.5f;
                                                num228 = 4;
                                                num229 = 2;
                                                num230 = 1;
                                            }
                                            else
{
                                                color55 = color10;
                                            }
                                            for (int num231 = num230; num231 < num228; num231 += num229)
{
                                                Vector2[] oldPos4 = rCurrentNPC.oldPos;
                                                Microsoft.Xna.Framework.Color color56 = color55;
                                                color56 = Microsoft.Xna.Framework.Color.Lerp(color56, color54, num227);
                                                color56 = rCurrentNPC.GetAlpha(color56);
                                                color56 *= (float)(num228 - num231) / (float)num228;
                                                color56.A = 100;
                                                Vector2 vector83 = rCurrentNPC.oldPos[num231] + new Vector2((float)rCurrentNPC.width, (float)rCurrentNPC.height) / 2f - screenPos;
                                                vector83 -= rectangle16.Size() * rCurrentNPC.scale / 2f;
                                                vector83 += vector10 * rCurrentNPC.scale + new Vector2(0f, num58 + num59 + rCurrentNPC.gfxOffY);
                                                mySpriteBatch.Draw(value21, vector83, new Microsoft.Xna.Framework.Rectangle?(rectangle16), color56, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                            }
                                            int num232 = 0;
                                            float num233 = 0f;
                                            float num234 = 0f;
                                            if (rCurrentNPC.ai[0] == 5f && rCurrentNPC.ai[1] >= 0f && rCurrentNPC.ai[1] < 30f)
{
                                                num232 = 4;
                                                num233 = 1f - (float)Math.Cos((double)((rCurrentNPC.ai[1] - 0f) / 30f * 3.1415927f));
                                                num233 /= 2f;
                                                num234 = 70f;
                                            }
                                            for (int num235 = 0; num235 < num232; num235++)
{
                                                Microsoft.Xna.Framework.Color color57 = color10;
                                                color57 = Microsoft.Xna.Framework.Color.Lerp(color57, color54, num227);
                                                color57 = rCurrentNPC.GetAlpha(color57);
                                                color57 *= 1f - num233;
                                                Vector2 vector84 = rCurrentNPC.Center + ((float)num235 / (float)num232 * 6.2831855f + rCurrentNPC.rotation).ToRotationVector2() * num234 * num233 - screenPos;
                                                vector84 -= new Vector2((float)value20.Width, (float)(value20.Height / Main.npcFrameCount[type])) * rCurrentNPC.scale / 2f;
                                                vector84 += vector10 * rCurrentNPC.scale + new Vector2(0f, num58 + num59 + rCurrentNPC.gfxOffY);
                                                mySpriteBatch.Draw(value21, vector84, new Microsoft.Xna.Framework.Rectangle?(rectangle16), color57, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                            }
                                            Vector2 vector85 = rCurrentNPC.Center - screenPos;
                                            vector85 -= new Vector2((float)value20.Width, (float)(value20.Height / Main.npcFrameCount[type])) * rCurrentNPC.scale / 2f;
                                            vector85 += vector10 * rCurrentNPC.scale + new Vector2(0f, num58 + num59 + rCurrentNPC.gfxOffY);
                                            mySpriteBatch.Draw(value20, vector85, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), rCurrentNPC.GetAlpha(color10), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                            return;
                                        }
                                        if (type == 392 || type == 393 || type == 394 || type == 395)
{
                                            Texture2D value22 = TextureAssets.Npc[type].Value;
                                            Vector2 vector86 = rCurrentNPC.Center - screenPos + Vector2.UnitY * rCurrentNPC.gfxOffY;
                                            vector86 = vector86.Floor();
                                            float num236 = 0f;
                                            if (type == 393)
{
                                                num236 = -8f;
                                            }
                                            mySpriteBatch.Draw(value22, vector86, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), rCurrentNPC.GetAlpha(color10), rCurrentNPC.rotation, vector10 + Vector2.UnitY * num236, rCurrentNPC.scale, spriteEffects, 0f);
                                            if (type == 392)
{
                                                mySpriteBatch.Draw(TextureAssets.GlowMask[48].Value, vector86, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(200, 200, 200, 0), rCurrentNPC.rotation, vector10 + Vector2.UnitY * num236, rCurrentNPC.scale, spriteEffects, 0f);
                                            }
                                            if (type == 395)
{
                                                mySpriteBatch.Draw(TextureAssets.GlowMask[49].Value, vector86, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(200, 200, 200, 0), rCurrentNPC.rotation, vector10 + Vector2.UnitY * num236, rCurrentNPC.scale, spriteEffects, 0f);
                                            }
                                            if (type == 394)
{
                                                mySpriteBatch.Draw(TextureAssets.GlowMask[50].Value, vector86, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(200, 200, 200, 0), rCurrentNPC.rotation, vector10 + Vector2.UnitY * num236, rCurrentNPC.scale, spriteEffects, 0f);
                                                return;
                                            }
                                        }
                                        else
{
                                            if (type == 83 || type == 84 || type == 179)
{
                                                mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + num58), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), Microsoft.Xna.Framework.Color.White, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                return;
                                            }
                                            if (type >= 87 && type <= 92)
{
                                                Microsoft.Xna.Framework.Color alpha5 = rCurrentNPC.GetAlpha(color10);
                                                byte b5 = (Main.tileColor.R + Main.tileColor.G + Main.tileColor.B) / 3;
                                                if (alpha5.R < b5)
{
                                                    alpha5.R = b5;
                                                }
                                                if (alpha5.G < b5)
{
                                                    alpha5.G = b5;
                                                }
                                                if (alpha5.B < b5)
{
                                                    alpha5.B = b5;
                                                }
                                                mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + num58), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), alpha5, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                return;
                                            }
                                            if (type == 491)
{
                                                Texture2D texture2D9 = TextureAssets.Npc[rCurrentNPC.type].Value;
                                                Microsoft.Xna.Framework.Rectangle rectangle17 = rCurrentNPC.frame;
                                                Vector2 vector87 = rectangle17.OriginFlip(new Vector2(208f, 460f), spriteEffects);
                                                Vector2 vector88 = rCurrentNPC.Center - screenPos;
                                                Vector2 vector89 = new Vector2((float)(((spriteEffects & SpriteEffects.FlipHorizontally) != SpriteEffects.None) ? (-1) : 1), 1f);
                                                Microsoft.Xna.Framework.Color alpha6 = rCurrentNPC.GetAlpha(color10);
                                                mySpriteBatch.Draw(texture2D9, vector88, new Microsoft.Xna.Framework.Rectangle?(rectangle17), alpha6, rCurrentNPC.rotation, vector87, rCurrentNPC.scale, spriteEffects, 0f);
                                                int num237 = (int)rCurrentNPC.localAI[3] / 8;
                                                texture2D9 = TextureAssets.Extra[40].Value;
                                                rectangle17 = texture2D9.Frame(1, 4, 0, num237 % 4, 0, 0);
                                                vector87 = rectangle17.Size() * new Vector2(0.5f, 1f);
                                                mySpriteBatch.Draw(texture2D9, vector88 + (new Vector2(102f, -384f) * vector89).RotatedBy((double)rCurrentNPC.rotation, default(Vector2)), new Microsoft.Xna.Framework.Rectangle?(rectangle17), alpha6, rCurrentNPC.rotation, vector87, rCurrentNPC.scale, spriteEffects, 0f);
                                                texture2D9 = TextureAssets.Extra[41].Value;
                                                rectangle17 = texture2D9.Frame(1, 8, 0, num237 % 8, 0, 0);
                                                vector87 = rectangle17.Size() * new Vector2(0.5f, 0f) + new Vector2(0f, 10f);
                                                for (int num238 = 0; num238 < 5; num238++)
{
                                                    mySpriteBatch.Draw(texture2D9, vector88 + (new Vector2((float)(-96 + 34 * num238), 40f) * vector89).RotatedBy((double)rCurrentNPC.rotation, default(Vector2)), new Microsoft.Xna.Framework.Rectangle?(rectangle17), alpha6, rCurrentNPC.rotation, vector87, rCurrentNPC.scale, spriteEffects, 0f);
                                                }
                                                texture2D9 = TextureAssets.Extra[42].Value;
                                                rectangle17 = texture2D9.Frame(1, 4, 0, num237 % 4, 0, 0);
                                                vector87 = rectangle17.Size() * new Vector2(0.5f, 0f);
                                                for (int num239 = 0; num239 < 2; num239++)
{
                                                    mySpriteBatch.Draw(texture2D9, vector88 + (new Vector2((float)(158 - 106 * num239), -302f) * vector89).RotatedBy((double)rCurrentNPC.rotation, default(Vector2)), new Microsoft.Xna.Framework.Rectangle?(rectangle17), alpha6, rCurrentNPC.rotation, vector87, rCurrentNPC.scale, spriteEffects, 0f);
                                                }
                                                texture2D9 = TextureAssets.Extra[43].Value;
                                                rectangle17 = texture2D9.Frame(1, 4, 0, num237 % 4, 0, 0);
                                                vector87 = rectangle17.Size() * new Vector2(0.5f, 0f);
                                                for (int num240 = 0; num240 < 2; num240++)
{
                                                    mySpriteBatch.Draw(texture2D9, vector88 + (new Vector2((float)(42 - 178 * num240), -444f) * vector89).RotatedBy((double)rCurrentNPC.rotation, default(Vector2)), new Microsoft.Xna.Framework.Rectangle?(rectangle17), alpha6, rCurrentNPC.rotation, vector87, rCurrentNPC.scale, spriteEffects, 0f);
                                                }
                                                texture2D9 = TextureAssets.Extra[44].Value;
                                                rectangle17 = texture2D9.Frame(1, 4, 0, num237 % 4, 0, 0);
                                                vector87 = rectangle17.Size() * new Vector2(0.5f, 0f);
                                                mySpriteBatch.Draw(texture2D9, vector88 + (new Vector2(-134f, -302f) * vector89).RotatedBy((double)rCurrentNPC.rotation, default(Vector2)), new Microsoft.Xna.Framework.Rectangle?(rectangle17), alpha6, rCurrentNPC.rotation, vector87, rCurrentNPC.scale, spriteEffects, 0f);
                                                texture2D9 = TextureAssets.Extra[45].Value;
                                                rectangle17 = texture2D9.Frame(1, 4, 0, (2 + num237) % 4, 0, 0);
                                                vector87 = rectangle17.Size() * new Vector2(0.5f, 0f);
                                                mySpriteBatch.Draw(texture2D9, vector88 + (new Vector2(-60f, -330f) * vector89).RotatedBy((double)rCurrentNPC.rotation, default(Vector2)), new Microsoft.Xna.Framework.Rectangle?(rectangle17), alpha6, rCurrentNPC.rotation, vector87, rCurrentNPC.scale, spriteEffects, 0f);
                                                this.LoadNPC(492);
                                                if (TextureAssets.Npc[492].IsLoaded)
{
                                                    texture2D9 = TextureAssets.Npc[492].Value;
                                                    rectangle17 = texture2D9.Frame(1, 9, 0, 0, 0, 0);
                                                    vector87 = rectangle17.Size() * new Vector2(0.5f, 0f) + new Vector2(0f, 10f);
                                                    for (int num241 = 0; num241 < 4; num241++)
{
                                                        int num242 = (int)rCurrentNPC.ai[num241];
                                                        if (num242 >= 0)
{
                                                            rectangle17.Y = Main.npc[num242].frame.Y;
                                                            mySpriteBatch.Draw(texture2D9, vector88 + (new Vector2((float)(-122 + 68 * num241), -20f) * vector89).RotatedBy((double)rCurrentNPC.rotation, default(Vector2)), new Microsoft.Xna.Framework.Rectangle?(rectangle17), alpha6, rCurrentNPC.rotation, vector87, rCurrentNPC.scale, spriteEffects, 0f);
                                                        }
                                                    }
                                                    return;
                                                }
                                            }
                                            else
{
                                                if (type == 398)
{
                                                    bool flag10 = false;
                                                    Texture2D value23 = TextureAssets.Npc[type].Value;
                                                    Texture2D value24 = TextureAssets.Extra[16].Value;
                                                    Texture2D value25 = TextureAssets.Extra[14].Value;
                                                    float num243 = 340f;
                                                    float num244 = 0.5f;
                                                    Vector2 vector90 = new Vector2(220f, -60f);
                                                    Vector2 vector91 = new Vector2(76f, 66f);
                                                    Texture2D value26 = TextureAssets.Extra[13].Value;
                                                    Vector2 vector92 = new Vector2((float)value26.Width, 278f);
                                                    Vector2 vector93 = new Vector2(0f, 278f);
                                                    Vector2 vector94 = new Vector2(0f, 76f);
                                                    Vector2 center = rCurrentNPC.Center;
                                                    Microsoft.Xna.Framework.Point point = (rCurrentNPC.Center + new Vector2(0f, -150f)).ToTileCoordinates();
                                                    Microsoft.Xna.Framework.Color alpha7 = rCurrentNPC.GetAlpha(Microsoft.Xna.Framework.Color.Lerp(Lighting.GetColor(point.X, point.Y), Microsoft.Xna.Framework.Color.White, 0.3f));
                                                    for (int num245 = 0; num245 < 2; num245++)
{
                                                        bool flag11 = num245 == 0;
                                                        Vector2 vector95 = new Vector2((float)(flag11 ? (-1) : 1), 1f);
                                                        int num246 = -1;
                                                        for (int num247 = 0; num247 < Main.maxNPCs; num247++)
{
                                                            if (Main.npc[num247].active && Main.npc[num247].type == 397 && Main.npc[num247].ai[2] == (float)num245 && Main.npc[num247].ai[3] == (float)rCurrentNPC.whoAmI)
{
                                                                num246 = num247;
                                                                break;
                                                            }
                                                        }
                                                        if (num246 != -1)
{
                                                            Vector2 vector96 = center + vector90 * vector95;
                                                            Vector2 vector97 = (Main.npc[num246].Center + vector94 - vector96) * num244;
                                                            if (flag10)
{
                                                                Main.dust[Dust.NewDust(vector96 + vector97, 0, 0, 6, 0f, 0f, 0, default(Microsoft.Xna.Framework.Color), 1f)].noGravity = true;
                                                            }
                                                            float num248 = (float)Math.Acos((double)(vector97.Length() / num243)) * -vector95.X;
                                                            SpriteEffects spriteEffects4 = (flag11 ? SpriteEffects.None : SpriteEffects.FlipHorizontally);
                                                            Vector2 vector98 = vector91;
                                                            if (!flag11)
{
                                                                vector98.X = (float)value25.Width - vector98.X;
                                                            }
                                                            mySpriteBatch.Draw(value25, vector96 - screenPos, null, alpha7, vector97.ToRotation() - num248 - 1.5707964f, vector98, 1f, spriteEffects4, 0f);
                                                            if (flag10)
{
                                                                Main.dust[Dust.NewDust(vector96, 0, 0, 6, 0f, 0f, 0, default(Microsoft.Xna.Framework.Color), 1f)].noGravity = true;
                                                            }
                                                            if (flag10)
{
                                                                Main.dust[Dust.NewDust(center, 0, 0, 6, 0f, 0f, 0, default(Microsoft.Xna.Framework.Color), 1f)].noGravity = true;
                                                            }
                                                            if (flag10)
{
                                                                Main.dust[Dust.NewDust(vector96 + new Vector2(0f, num243).RotatedBy((double)(vector97.ToRotation() - num248 - 1.5707964f), default(Vector2)), 0, 0, 6, 0f, 0f, 0, default(Microsoft.Xna.Framework.Color), 1f)].noGravity = true;
                                                            }
                                                        }
                                                    }
                                                    mySpriteBatch.Draw(value26, center - screenPos, null, alpha7, 0f, vector92, 1f, SpriteEffects.None, 0f);
                                                    mySpriteBatch.Draw(value26, center - screenPos, null, alpha7, 0f, vector93, 1f, SpriteEffects.FlipHorizontally, 0f);
                                                    mySpriteBatch.Draw(value24, center - screenPos, null, alpha7, 0f, new Vector2(112f, 101f), 1f, SpriteEffects.None, 0f);
                                                    mySpriteBatch.Draw(value23, center - screenPos, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), alpha7, 0f, rCurrentNPC.frame.Size() / 2f, 1f, SpriteEffects.None, 0f);
                                                    return;
                                                }
                                                if (type == 397)
{
                                                    Texture2D value27 = TextureAssets.Npc[type].Value;
                                                    float num249 = 0.5f;
                                                    Vector2 vector99 = new Vector2(220f, -60f);
                                                    Vector2 vector100 = new Vector2(0f, 76f);
                                                    Texture2D value28 = TextureAssets.Extra[15].Value;
                                                    Vector2 vector101 = new Vector2(60f, 30f);
                                                    float num250 = 340f;
                                                    Vector2 center2 = Main.npc[(int)rCurrentNPC.ai[3]].Center;
                                                    Microsoft.Xna.Framework.Point point2 = rCurrentNPC.Center.ToTileCoordinates();
                                                    Microsoft.Xna.Framework.Color alpha8 = rCurrentNPC.GetAlpha(Microsoft.Xna.Framework.Color.Lerp(Lighting.GetColor(point2.X, point2.Y), Microsoft.Xna.Framework.Color.White, 0.3f));
                                                    bool flag12 = rCurrentNPC.ai[2] == 0f;
                                                    Vector2 vector102 = new Vector2((float)(flag12 ? (-1) : 1), 1f);
                                                    Vector2 vector103 = new Vector2(120f, 180f);
                                                    if (!flag12)
{
                                                        vector103.X = (float)value27.Width - vector103.X;
                                                    }
                                                    Texture2D value29 = TextureAssets.Extra[17].Value;
                                                    Texture2D value30 = TextureAssets.Extra[19].Value;
                                                    Vector2 vector104 = new Vector2(26f, 42f);
                                                    if (!flag12)
{
                                                        vector104.X = (float)value29.Width - vector104.X;
                                                    }
                                                    Vector2 vector105 = new Vector2(30f, 66f);
                                                    Vector2 vector106 = new Vector2(1f * -vector102.X, 3f);
                                                    Texture2D value31 = TextureAssets.Extra[26].Value;
                                                    Microsoft.Xna.Framework.Rectangle rectangle18 = value31.Frame(1, 1, 0, 0, 0, 0);
                                                    rectangle18.Height /= 4;
                                                    Vector2 vector107 = center2 + vector99 * vector102;
                                                    Vector2 vector108 = rCurrentNPC.Center + vector100;
                                                    Vector2 vector109 = vector107 - vector108;
                                                    vector109 *= 1f - num249;
                                                    Vector2 vector110 = vector101;
                                                    if (!flag12)
{
                                                        vector110.X = (float)value28.Width - vector110.X;
                                                    }
                                                    float num251 = (float)Math.Acos((double)(vector109.Length() / num250)) * -vector102.X;
                                                    mySpriteBatch.Draw(value28, vector108 - screenPos, null, alpha8, vector109.ToRotation() + num251 - 1.5707964f, vector110, 1f, spriteEffects, 0f);
                                                    if (rCurrentNPC.ai[0] == -2f)
{
                                                        int num252 = (int)rCurrentNPC.ai[1];
                                                        num252 /= 8;
                                                        rectangle18.Y += rectangle18.Height * num252;
                                                        mySpriteBatch.Draw(value31, rCurrentNPC.Center - screenPos, new Microsoft.Xna.Framework.Rectangle?(rectangle18), alpha8, 0f, vector104 - new Vector2(4f, 4f), 1f, spriteEffects, 0f);
                                                    }
                                                    else
{
                                                        mySpriteBatch.Draw(value29, rCurrentNPC.Center - screenPos, null, alpha8, 0f, vector104, 1f, spriteEffects, 0f);
                                                        Vector2 vector111 = Utils.Vector2FromElipse(rCurrentNPC.localAI[0].ToRotationVector2(), vector105 * rCurrentNPC.localAI[1]);
                                                        mySpriteBatch.Draw(value30, rCurrentNPC.Center - screenPos + vector111 + vector106, null, alpha8, 0f, new Vector2((float)value30.Width, (float)value30.Height) / 2f, 1f, SpriteEffects.None, 0f);
                                                    }
                                                    mySpriteBatch.Draw(value27, rCurrentNPC.Center - screenPos, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), alpha8, 0f, vector103, 1f, spriteEffects, 0f);
                                                    return;
                                                }
                                                if (type == 396)
{
                                                    Texture2D value32 = TextureAssets.Npc[type].Value;
                                                    Vector2 vector112 = new Vector2(191f, 130f) / 2f;
                                                    Texture2D value33 = TextureAssets.Extra[18].Value;
                                                    Texture2D value34 = TextureAssets.Extra[19].Value;
                                                    Vector2 vector113 = new Vector2(19f, 34f);
                                                    Vector2 vector114 = new Vector2(27f, 59f);
                                                    Vector2 vector115 = new Vector2(0f, 0f);
                                                    Texture2D value35 = TextureAssets.Extra[25].Value;
                                                    Vector2 vector116 = new Vector2(0f, 214f).RotatedBy((double)rCurrentNPC.rotation, default(Vector2));
                                                    Microsoft.Xna.Framework.Rectangle rectangle19 = value35.Frame(1, 1, 0, 0, 0, 0);
                                                    rectangle19.Height /= 3;
                                                    rectangle19.Y += rectangle19.Height * (int)(rCurrentNPC.localAI[2] / 7f);
                                                    Texture2D value36 = TextureAssets.Extra[29].Value;
                                                    Vector2 vector117 = new Vector2(0f, 4f).RotatedBy((double)rCurrentNPC.rotation, default(Vector2));
                                                    Microsoft.Xna.Framework.Rectangle rectangle20 = value36.Frame(1, 1, 0, 0, 0, 0);
                                                    rectangle20.Height /= 4;
                                                    rectangle20.Y += rectangle20.Height * (int)(rCurrentNPC.localAI[3] / 5f);
                                                    Texture2D value37 = TextureAssets.Extra[26].Value;
                                                    Microsoft.Xna.Framework.Rectangle rectangle21 = value37.Frame(1, 1, 0, 0, 0, 0);
                                                    rectangle21.Height /= 4;
                                                    Vector2 center3 = Main.npc[(int)rCurrentNPC.ai[3]].Center;
                                                    Microsoft.Xna.Framework.Point point3 = rCurrentNPC.Center.ToTileCoordinates();
                                                    Microsoft.Xna.Framework.Color alpha9 = rCurrentNPC.GetAlpha(Microsoft.Xna.Framework.Color.Lerp(Lighting.GetColor(point3.X, point3.Y), Microsoft.Xna.Framework.Color.White, 0.3f));
                                                    if (rCurrentNPC.ai[0] < 0f)
{
                                                        int num253 = (int)rCurrentNPC.ai[1];
                                                        num253 /= 8;
                                                        rectangle21.Y += rectangle21.Height * num253;
                                                        mySpriteBatch.Draw(value37, rCurrentNPC.Center - screenPos, new Microsoft.Xna.Framework.Rectangle?(rectangle21), alpha9, rCurrentNPC.rotation, vector113 + new Vector2(4f, 4f), 1f, spriteEffects, 0f);
                                                    }
                                                    else
{
                                                        mySpriteBatch.Draw(value33, rCurrentNPC.Center - screenPos, null, alpha9, rCurrentNPC.rotation, vector113, 1f, spriteEffects, 0f);
                                                        Vector2 vector118 = Utils.Vector2FromElipse(rCurrentNPC.localAI[0].ToRotationVector2(), vector114 * rCurrentNPC.localAI[1]);
                                                        mySpriteBatch.Draw(value34, rCurrentNPC.Center - screenPos + vector118 + vector115, null, alpha9, rCurrentNPC.rotation, new Vector2((float)value34.Width, (float)value34.Height) / 2f, 1f, SpriteEffects.None, 0f);
                                                    }
                                                    mySpriteBatch.Draw(value32, rCurrentNPC.Center - screenPos, new Microsoft.Xna.Framework.Rectangle?(value32.Frame(3, 3, rCurrentNPC.frame.Y / 3, rCurrentNPC.frame.Y % 3, 0, 0)), alpha9, rCurrentNPC.rotation, vector112, 2f, spriteEffects, 0f);
                                                    mySpriteBatch.Draw(value36, (rCurrentNPC.Center - screenPos + vector117).Floor(), new Microsoft.Xna.Framework.Rectangle?(rectangle20), alpha9, rCurrentNPC.rotation, rectangle20.Size() / 2f, 1f, spriteEffects, 0f);
                                                    mySpriteBatch.Draw(value35, (rCurrentNPC.Center - screenPos + vector116).Floor(), new Microsoft.Xna.Framework.Rectangle?(rectangle19), alpha9, rCurrentNPC.rotation, rectangle19.Size() / 2f, 1f, spriteEffects, 0f);
                                                    return;
                                                }
                                                if (type == 400)
{
                                                    Texture2D value38 = TextureAssets.Npc[type].Value;
                                                    Texture2D value39 = TextureAssets.Extra[19].Value;
                                                    Vector2 vector119 = new Vector2(40f, 40f);
                                                    Vector2 vector120 = new Vector2(30f, 30f);
                                                    Vector2 center4 = rCurrentNPC.Center;
                                                    Microsoft.Xna.Framework.Point point4 = rCurrentNPC.Center.ToTileCoordinates();
                                                    Microsoft.Xna.Framework.Color alpha10 = rCurrentNPC.GetAlpha(Microsoft.Xna.Framework.Color.Lerp(Lighting.GetColor(point4.X, point4.Y), Microsoft.Xna.Framework.Color.White, 0.3f));
                                                    mySpriteBatch.Draw(value38, rCurrentNPC.Center - screenPos, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), alpha10, rCurrentNPC.rotation, vector119, 1f, spriteEffects, 0f);
                                                    Vector2 vector121 = Utils.Vector2FromElipse(rCurrentNPC.localAI[0].ToRotationVector2(), vector120 * rCurrentNPC.localAI[1]);
                                                    mySpriteBatch.Draw(value39, rCurrentNPC.Center - screenPos + vector121, null, alpha10, rCurrentNPC.rotation, value39.Size() / 2f, rCurrentNPC.localAI[2], SpriteEffects.None, 0f);
                                                    return;
                                                }
                                                if (type != 384)
{
                                                    if (type == 416)
{
                                                        int num254 = -1;
                                                        int num255 = (int)rCurrentNPC.ai[0];
                                                        Vector2 vector122 = rCurrentNPC.position;
                                                        Vector2 vector123 = Vector2.Zero;
                                                        if (Main.npc[num255].active && Main.npc[num255].type == 415)
{
                                                            num254 = num255;
                                                        }
                                                        if (num254 != -1)
{
                                                            Vector2 position = rCurrentNPC.position;
                                                            rCurrentNPC.Bottom = Main.npc[num254].Bottom;
                                                            vector122 = rCurrentNPC.position;
                                                            rCurrentNPC.position = position;
                                                            rCurrentNPC.gfxOffY = Main.npc[num254].gfxOffY;
                                                            vector123 = Main.npc[num254].velocity;
                                                        }
                                                        Microsoft.Xna.Framework.Rectangle frame3 = rCurrentNPC.frame;
                                                        mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(vector122.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, vector122.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + num58 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(frame3), rCurrentNPC.GetAlpha(color10), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        if (rCurrentNPC.color != default(Microsoft.Xna.Framework.Color))
{
                                                            mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(vector122.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, vector122.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + num58 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(frame3), rCurrentNPC.GetColor(color10), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        }
                                                        mySpriteBatch.Draw(TextureAssets.GlowMask[156].Value, vector122 + rCurrentNPC.Size * new Vector2(0.5f, 1f) - screenPos + new Vector2((float)(-(float)TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, (float)(-(float)TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        float num256 = 0.5f + (rCurrentNPC.GetAlpha(color10).ToVector3() - new Vector3(0.5f)).Length() * 0.5f;
                                                        for (int num257 = 0; num257 < 4; num257++)
{
                                                            mySpriteBatch.Draw(TextureAssets.GlowMask[156].Value, vector122 + rCurrentNPC.Size * new Vector2(0.5f, 1f) - screenPos + new Vector2((float)(-(float)TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, (float)(-(float)TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + rCurrentNPC.gfxOffY) + vector123.RotatedBy((double)((float)num257 * 1.5707964f), default(Vector2)) * num256, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(64, 64, 64, 0), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        }
                                                        return;
                                                    }
                                                    if (type == 399)
{
                                                        Texture2D texture2D10 = TextureAssets.Npc[type].Value;
                                                        (rCurrentNPC.position - screenPos + Vector2.UnitY * rCurrentNPC.gfxOffY).Floor();
                                                        float num258 = 5f;
                                                        int num259 = 0;
                                                        while ((float)num259 < num258)
{
                                                            float num260 = 1f - (Main.GlobalTimeWrappedHourly + (float)num259) % num258 / num258;
                                                            Microsoft.Xna.Framework.Color color58 = Microsoft.Xna.Framework.Color.LimeGreen;
                                                            if (rCurrentNPC.ai[0] == 1f)
{
                                                                color58 = Microsoft.Xna.Framework.Color.Lerp(Microsoft.Xna.Framework.Color.LimeGreen, Microsoft.Xna.Framework.Color.Red, MathHelper.Clamp(rCurrentNPC.ai[1] / 20f, 0f, 1f));
                                                            }
                                                            if (rCurrentNPC.ai[0] == 2f)
{
                                                                color58 = Microsoft.Xna.Framework.Color.Red;
                                                            }
                                                            color58 *= 1f - num260;
                                                            color58.A = 0;
                                                            for (int num261 = 0; num261 < 2; num261++)
{
                                                                mySpriteBatch.Draw(TextureAssets.Extra[27].Value, rCurrentNPC.Center - screenPos + Vector2.UnitY * (rCurrentNPC.gfxOffY - 4f + 6f), null, color58, 1.5707964f, new Vector2(10f, 48f), num260 * 4f, SpriteEffects.None, 0f);
                                                            }
                                                            num259++;
                                                        }
                                                        mySpriteBatch.Draw(texture2D10, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + num58 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), rCurrentNPC.GetAlpha(color10), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        texture2D10 = TextureAssets.GlowMask[100].Value;
                                                        mySpriteBatch.Draw(texture2D10, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + num58 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(127 - rCurrentNPC.alpha / 2, 127 - rCurrentNPC.alpha / 2, 127 - rCurrentNPC.alpha / 2, 0), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        texture2D10 = TextureAssets.Extra[20].Value;
                                                        Microsoft.Xna.Framework.Rectangle rectangle22 = texture2D10.Frame(1, 4, 0, (int)rCurrentNPC.ai[0] + 1, 0, 0);
                                                        Vector2 vector124 = new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)texture2D10.Width * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + num58 + rCurrentNPC.gfxOffY + 18f + 6f);
                                                        mySpriteBatch.Draw(texture2D10, vector124, new Microsoft.Xna.Framework.Rectangle?(rectangle22), rCurrentNPC.GetAlpha(color10), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        texture2D10 = TextureAssets.GlowMask[101].Value;
                                                        mySpriteBatch.Draw(texture2D10, vector124, new Microsoft.Xna.Framework.Rectangle?(rectangle22), new Microsoft.Xna.Framework.Color(127 - rCurrentNPC.alpha / 2, 127 - rCurrentNPC.alpha / 2, 127 - rCurrentNPC.alpha / 2, 0), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        return;
                                                    }
                                                    if (type == 94)
{
                                                        for (int num262 = 1; num262 < 6; num262 += 2)
{
                                                            Vector2[] oldPos5 = rCurrentNPC.oldPos;
                                                            Microsoft.Xna.Framework.Color color59 = rCurrentNPC.GetAlpha(color10);
                                                            color59.R = (byte)((int)color59.R * (10 - num262) / 15);
                                                            color59.G = (byte)((int)color59.G * (10 - num262) / 15);
                                                            color59.B = (byte)((int)color59.B * (10 - num262) / 15);
                                                            color59.A = (byte)((int)color59.A * (10 - num262) / 15);
                                                            color59 = rCurrentNPC.GetShimmerColor(color59);
                                                            mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(rCurrentNPC.oldPos[num262].X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.oldPos[num262].Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), color59, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        }
                                                    }
                                                    if (type == 125 || type == 126 || type == 127 || type == 128 || type == 129 || type == 130 || type == 131 || (type == 139 && rCurrentNPC.ai[3] == 0f) || type == 140)
{
                                                        for (int num263 = 9; num263 >= 0; num263 -= 2)
{
                                                            Vector2[] oldPos6 = rCurrentNPC.oldPos;
                                                            Microsoft.Xna.Framework.Color alpha11 = rCurrentNPC.GetAlpha(color10);
                                                            alpha11.R = (byte)((int)alpha11.R * (10 - num263) / 20);
                                                            alpha11.G = (byte)((int)alpha11.G * (10 - num263) / 20);
                                                            alpha11.B = (byte)((int)alpha11.B * (10 - num263) / 20);
                                                            alpha11.A = (byte)((int)alpha11.A * (10 - num263) / 20);
                                                            mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(rCurrentNPC.oldPos[num263].X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.oldPos[num263].Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), alpha11, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        }
                                                    }
                                                    if (type == 417 && rCurrentNPC.ai[0] >= 6f && rCurrentNPC.ai[0] <= 6f)
{
                                                        for (int num264 = 5; num264 >= 0; num264--)
{
                                                            Vector2[] oldPos7 = rCurrentNPC.oldPos;
                                                            Microsoft.Xna.Framework.Color alpha12 = rCurrentNPC.GetAlpha(color10);
                                                            alpha12.R = (byte)((int)alpha12.R * (10 - num264) / 20);
                                                            alpha12.G = (byte)((int)alpha12.G * (10 - num264) / 20);
                                                            alpha12.B = (byte)((int)alpha12.B * (10 - num264) / 20);
                                                            alpha12.A = (byte)((int)alpha12.A * (10 - num264) / 20);
                                                            mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(rCurrentNPC.oldPos[num264].X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.oldPos[num264].Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), alpha12, rCurrentNPC.oldRot[num264], vector10, MathHelper.Lerp(0.5f, 1f, (5f - (float)num264) / 6f), spriteEffects, 0f);
                                                        }
                                                    }
                                                    if (type == 419 && rCurrentNPC.ai[2] <= -9f)
{
                                                        int num265 = TextureAssets.GlowMask[154].Height() / Main.npcFrameCount[type];
                                                        int num266 = rCurrentNPC.frame.Y / num265;
                                                        for (int num267 = 6; num267 >= 0; num267--)
{
                                                            Vector2[] oldPos8 = rCurrentNPC.oldPos;
                                                            Microsoft.Xna.Framework.Color white4 = Microsoft.Xna.Framework.Color.White;
                                                            white4.R = (byte)(255 * (10 - num267) / 20);
                                                            white4.G = (byte)(255 * (10 - num267) / 20);
                                                            white4.B = (byte)(255 * (10 - num267) / 20);
                                                            white4.A = 0;
                                                            Microsoft.Xna.Framework.Rectangle frame4 = rCurrentNPC.frame;
                                                            int num268 = (num266 - 3 - num267) % 3;
                                                            if (num268 < 0)
{
                                                                num268 += 3;
                                                            }
                                                            num268 += 5;
                                                            frame4.Y = num265 * num268;
                                                            mySpriteBatch.Draw(TextureAssets.GlowMask[154].Value, new Vector2(rCurrentNPC.oldPos[num267].X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.oldPos[num267].Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59), new Microsoft.Xna.Framework.Rectangle?(frame4), white4, rCurrentNPC.oldRot[num267], vector10, MathHelper.Lerp(0.75f, 1.2f, (10f - (float)num267) / 10f), spriteEffects, 0f);
                                                        }
                                                    }
                                                    if (type == 418 && (rCurrentNPC.ai[0] == 2f || rCurrentNPC.ai[0] == 4f))
{
                                                        Texture2D value40 = TextureAssets.Extra[55].Value;
                                                        Vector2 vector125 = new Vector2((float)(value40.Width / 2), (float)(value40.Height / 8 + 14));
                                                        int num269 = (int)rCurrentNPC.ai[1] / 2;
                                                        float num270 = -1.5707964f * (float)rCurrentNPC.spriteDirection;
                                                        float num271 = rCurrentNPC.ai[1] / 45f;
                                                        if (num271 > 1f)
{
                                                            num271 = 1f;
                                                        }
                                                        num269 %= 4;
                                                        for (int num272 = 6; num272 >= 0; num272--)
{
                                                            Vector2[] oldPos9 = rCurrentNPC.oldPos;
                                                            Microsoft.Xna.Framework.Color color60 = Microsoft.Xna.Framework.Color.Lerp(Microsoft.Xna.Framework.Color.Gold, Microsoft.Xna.Framework.Color.OrangeRed, num271);
                                                            color60 = Microsoft.Xna.Framework.Color.Lerp(color60, Microsoft.Xna.Framework.Color.Blue, (float)num272 / 12f);
                                                            color60.A = (byte)(64f * num271);
                                                            color60.R = (byte)((int)color60.R * (10 - num272) / 20);
                                                            color60.G = (byte)((int)color60.G * (10 - num272) / 20);
                                                            color60.B = (byte)((int)color60.B * (10 - num272) / 20);
                                                            color60.A = (byte)((int)color60.A * (10 - num272) / 20);
                                                            color60 *= num271;
                                                            int num273 = (num269 - num272) % 4;
                                                            if (num273 < 0)
{
                                                                num273 += 4;
                                                            }
                                                            Microsoft.Xna.Framework.Rectangle rectangle23 = value40.Frame(1, 4, 0, num273, 0, 0);
                                                            mySpriteBatch.Draw(value40, new Vector2(rCurrentNPC.oldPos[num272].X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.oldPos[num272].Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59), new Microsoft.Xna.Framework.Rectangle?(rectangle23), color60, rCurrentNPC.oldRot[num272] + num270, vector125, MathHelper.Lerp(0.1f, 1.2f, (10f - (float)num272) / 10f), spriteEffects, 0f);
                                                        }
                                                    }
                                                    if (type == 516)
{
                                                        int num274 = TextureAssets.Npc[type].Height() / Main.npcFrameCount[type];
                                                        int num275 = rCurrentNPC.frame.Y / num274;
                                                        for (int num276 = 6; num276 >= 0; num276--)
{
                                                            Vector2[] oldPos10 = rCurrentNPC.oldPos;
                                                            Microsoft.Xna.Framework.Color color61 = Microsoft.Xna.Framework.Color.White;
                                                            color61.R = (byte)(255 * (10 - num276) / 20);
                                                            color61.G = (byte)(255 * (10 - num276) / 20);
                                                            color61.B = (byte)(255 * (10 - num276) / 20);
                                                            color61.A = (byte)(255 * (10 - num276) / 20);
                                                            color61 = Microsoft.Xna.Framework.Color.Lerp(color61, Microsoft.Xna.Framework.Color.Transparent, (float)num276 / 6f);
                                                            Microsoft.Xna.Framework.Rectangle frame5 = rCurrentNPC.frame;
                                                            int num277 = (num275 - 4 - num276) % 4;
                                                            if (num277 < 0)
{
                                                                num277 += 4;
                                                            }
                                                            frame5.Y = num274 * num277;
                                                            mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(rCurrentNPC.oldPos[num276].X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.oldPos[num276].Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59), new Microsoft.Xna.Framework.Rectangle?(frame5), color61, rCurrentNPC.rotation, vector10, MathHelper.Lerp(0.35f, 1.2f, (10f - (float)num276) / 10f), spriteEffects, 0f);
                                                        }
                                                    }
                                                    if (rCurrentNPC.type == 390 && rCurrentNPC.IsABestiaryIconDummy)
{
                                                        this.LoadNPC(391);
                                                        Texture2D value41 = TextureAssets.Npc[391].Value;
                                                        Microsoft.Xna.Framework.Rectangle rectangle24 = value41.Frame(1, Main.npcFrameCount[391], 0, (int)rCurrentNPC.localAI[3], 0, 0);
                                                        Vector2 vector126 = new Vector2((float)(-(float)rCurrentNPC.width - 8), 10f);
                                                        mySpriteBatch.Draw(value41, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + num58 + rCurrentNPC.gfxOffY) + vector126, new Microsoft.Xna.Framework.Rectangle?(rectangle24), rCurrentNPC.GetAlpha(color10), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    Microsoft.Xna.Framework.Rectangle frame6 = rCurrentNPC.frame;
                                                    if (type == 182 || type == 289)
{
                                                        frame6.Height -= 2;
                                                    }
                                                    if (type - 420 > 1 && type - 423 > 1)
{
                                                        if (type == 662)
{
                                                            float num278 = 4f + 2f * (float)Math.Cos((double)(6.2831855f * Main.GlobalTimeWrappedHourly));
                                                            Vector2 vector127 = Vector2.UnitX * num278;
                                                            Microsoft.Xna.Framework.Color color62 = Microsoft.Xna.Framework.Color.Cyan * (num278 / 12f) * 0.4f;
                                                            color62.A /= 4;
                                                            for (float num279 = 0.9f; num279 >= 0f; num279 -= 0.125f)
{
                                                                Vector2 vector128 = rCurrentNPC.position - rCurrentNPC.velocity * 10f * num279;
                                                                mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(vector128.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, vector128.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + num58 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(frame6), color62 * (1f - num279), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                            }
                                                            for (float num280 = 0f; num280 < 6.2831855f; num280 += 1.5707964f)
{
                                                                Vector2 vector129 = rCurrentNPC.position + vector127.RotatedBy((double)num280, default(Vector2));
                                                                mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(vector129.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, vector129.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + num58 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(frame6), color62, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                            }
                                                        }
                                                    }
                                                    else
{
                                                        float num281 = 9f + 3f * (float)Math.Cos((double)(6.2831855f * Main.GlobalTimeWrappedHourly));
                                                        Vector2 vector130 = Vector2.UnitX * num281;
                                                        Microsoft.Xna.Framework.Color color63 = Microsoft.Xna.Framework.Color.Teal * (num281 / 12f) * 0.8f;
                                                        color63.A /= 2;
                                                        for (float num282 = 0f; num282 < 6.2831855f; num282 += 1.5707964f)
{
                                                            Vector2 vector131 = rCurrentNPC.position + vector130.RotatedBy((double)num282, default(Vector2));
                                                            mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(vector131.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, vector131.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + num58 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(frame6), color63, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        }
                                                    }
                                                    if (rCurrentNPC.aiStyle == 7)
{
                                                        this.DrawNPCExtras(rCurrentNPC, true, num59, num58, color10, vector10, spriteEffects, screenPos);
                                                    }
                                                    if (type == 346 && (double)rCurrentNPC.life < (double)rCurrentNPC.lifeMax * 0.5)
{
                                                        mySpriteBatch.Draw(TextureAssets.SantaTank.Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + num58 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(frame6), rCurrentNPC.GetAlpha(color10), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    else if (type == 356)
{
                                                        frame6.Height--;
                                                        mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + num58 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(frame6), rCurrentNPC.GetAlpha(color10), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    else if (type == 360)
{
                                                        int num283 = 0;
                                                        if (rCurrentNPC.ai[2] == 0f)
{
                                                            if (rCurrentNPC.rotation == 3.14f || rCurrentNPC.rotation == -3.14f)
{
                                                                num59 = 2f;
                                                            }
                                                            if (rCurrentNPC.direction < 0 && (rCurrentNPC.rotation == 1.57f || rCurrentNPC.rotation == 4.71f))
{
                                                                num283 = 1;
                                                            }
                                                            if (rCurrentNPC.direction > 0 && (rCurrentNPC.rotation == 1.57f || rCurrentNPC.rotation == 4.71f))
{
                                                                num283 = -1;
                                                            }
                                                        }
                                                        mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale + (float)num283, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + num58 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(frame6), rCurrentNPC.GetAlpha(color10), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    else if (type == 655)
{
                                                        int num284 = 0;
                                                        if (rCurrentNPC.ai[2] == 0f)
{
                                                            if (rCurrentNPC.rotation == 3.14f || rCurrentNPC.rotation == -3.14f)
{
                                                                num59 = 2f;
                                                            }
                                                            if (rCurrentNPC.direction < 0 && (rCurrentNPC.rotation == 1.57f || rCurrentNPC.rotation == 4.71f))
{
                                                                num284 = 1;
                                                            }
                                                            if (rCurrentNPC.direction > 0 && (rCurrentNPC.rotation == 1.57f || rCurrentNPC.rotation == 4.71f))
{
                                                                num284 = -1;
                                                            }
                                                        }
                                                        mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale + (float)num284, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + num58 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(frame6), rCurrentNPC.GetAlpha(Microsoft.Xna.Framework.Color.Orange), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    else if (type == 266 && rCurrentNPC.life < rCurrentNPC.lifeMax && (Main.expertMode || Main.getGoodWorld))
{
                                                        Microsoft.Xna.Framework.Color alpha13 = rCurrentNPC.GetAlpha(color10);
                                                        float num285 = 1f - (float)rCurrentNPC.life / (float)rCurrentNPC.lifeMax;
                                                        if (Main.expertMode)
{
                                                            num285 *= 2f;
                                                        }
                                                        num285 *= num285;
                                                        if (Main.getGoodWorld)
{
                                                            num285 = 1f;
                                                        }
                                                        num285 = MathHelper.Clamp(num285, 0f, 1f);
                                                        alpha13.R = (byte)((float)alpha13.R * num285);
                                                        alpha13.G = (byte)((float)alpha13.G * num285);
                                                        alpha13.B = (byte)((float)alpha13.B * num285);
                                                        alpha13.A = (byte)((float)alpha13.A * num285);
                                                        for (int num286 = 0; num286 < 4; num286++)
{
                                                            Vector2 position2 = rCurrentNPC.position;
                                                            float num287 = Math.Abs(rCurrentNPC.Center.X - Main.player[Main.myPlayer].Center.X);
                                                            float num288 = Math.Abs(rCurrentNPC.Center.Y - Main.player[Main.myPlayer].Center.Y);
                                                            if (num286 == 0 || num286 == 2)
{
                                                                position2.X = Main.player[Main.myPlayer].Center.X + num287;
                                                            }
                                                            else
{
                                                                position2.X = Main.player[Main.myPlayer].Center.X - num287;
                                                            }
                                                            position2.X -= (float)(rCurrentNPC.width / 2);
                                                            if (num286 == 0 || num286 == 1)
{
                                                                position2.Y = Main.player[Main.myPlayer].Center.Y + num288;
                                                            }
                                                            else
{
                                                                position2.Y = Main.player[Main.myPlayer].Center.Y - num288;
                                                            }
                                                            position2.Y -= (float)(rCurrentNPC.height / 2);
                                                            mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(position2.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, position2.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + num58 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(frame6), alpha13, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        }
                                                        mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + num58 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(frame6), rCurrentNPC.GetAlpha(color10), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    else if (type == 421 && rCurrentNPC.ai[0] == 5f)
{
                                                        Player player = Main.player[rCurrentNPC.target];
                                                        if (player.gravDir == -1f)
{
                                                            spriteEffects |= SpriteEffects.FlipVertically;
                                                        }
                                                        mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2((float)(player.direction * 4), player.gfxOffY) + ((player.gravDir == 1f) ? player.Top : player.Bottom) - screenPos, new Microsoft.Xna.Framework.Rectangle?(frame6), rCurrentNPC.GetAlpha(color10), rCurrentNPC.rotation, frame6.Size() / 2f, rCurrentNPC.scale, spriteEffects, 0f);
                                                        mySpriteBatch.Draw(TextureAssets.GlowMask[146].Value, new Vector2((float)(player.direction * 4), player.gfxOffY) + ((player.gravDir == 1f) ? player.Top : player.Bottom) - screenPos, new Microsoft.Xna.Framework.Rectangle?(frame6), rCurrentNPC.GetAlpha(color10), rCurrentNPC.rotation, frame6.Size() / 2f, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    else if (type == 518)
{
                                                        Vector2 vector132 = new Vector2(-10f, 0f);
                                                        mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + num58 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(frame6), rCurrentNPC.GetAlpha(color10), rCurrentNPC.rotation, vector10 + vector132, rCurrentNPC.scale, spriteEffects, 0f);
                                                        if (rCurrentNPC.color != default(Microsoft.Xna.Framework.Color))
{
                                                            mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + num58 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(frame6), rCurrentNPC.GetColor(color10), rCurrentNPC.rotation, vector10 + vector132, rCurrentNPC.scale, spriteEffects, 0f);
                                                        }
                                                    }
                                                    else if (type == 681 || type == 676)
{
                                                        if (rCurrentNPC.IsAPortraitDummy)
{
                                                            Matrix uiscaleMatrix = Main.UIScaleMatrix;
                                                            Microsoft.Xna.Framework.Rectangle scissorRectangle = mySpriteBatch.GraphicsDevice.ScissorRectangle;
                                                            mySpriteBatch.End();
                                                            mySpriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend, SamplerState.PointClamp, DepthStencilState.Default, Main.ScissorState, null, uiscaleMatrix);
                                                            mySpriteBatch.GraphicsDevice.ScissorRectangle = scissorRectangle;
                                                        }
                                                        else if (!rCurrentNPC.IsABestiaryIconDummy)
{
                                                            RasterizerState rasterizerState = mySpriteBatch.GraphicsDevice.RasterizerState;
                                                            mySpriteBatch.End();
                                                            mySpriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend, SamplerState.PointClamp, DepthStencilState.Default, rasterizerState, null, Main.Transform);
                                                        }
                                                        DrawData drawData4 = new DrawData(TextureAssets.Npc[type].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + num58 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(frame6), rCurrentNPC.GetAlpha(color10), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        GameShaders.Misc["RainbowTownSlime"].Apply(new DrawData?(drawData4));
                                                        drawData4.Draw(mySpriteBatch);
                                                        Main.pixelShader.CurrentTechnique.Passes[0].Apply();
                                                        if (rCurrentNPC.IsAPortraitDummy)
{
                                                            Matrix uiscaleMatrix2 = Main.UIScaleMatrix;
                                                            Microsoft.Xna.Framework.Rectangle scissorRectangle2 = mySpriteBatch.GraphicsDevice.ScissorRectangle;
                                                            mySpriteBatch.End();
                                                            mySpriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend, SamplerState.PointClamp, DepthStencilState.Default, Main.ScissorState, null, uiscaleMatrix2);
                                                            mySpriteBatch.GraphicsDevice.ScissorRectangle = scissorRectangle2;
                                                        }
                                                        else if (!rCurrentNPC.IsABestiaryIconDummy)
{
                                                            mySpriteBatch.End();
                                                            mySpriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, Main.DefaultSamplerState, DepthStencilState.None, Main.Rasterizer, null, Main.Transform);
                                                        }
                                                    }
                                                    else if (type == 685)
{
                                                        Vector2 vector133 = new Vector2(rCurrentNPC.scale);
                                                        float num289 = rCurrentNPC.rotation;
                                                        int num290 = 9;
                                                        Vector2 vector134 = rCurrentNPC.oldPos[num290];
                                                        if (vector134 != Vector2.Zero && rCurrentNPC.velocity.Y == 0f)
{
                                                            Vector2 position3 = rCurrentNPC.position;
                                                            Vector2 vector135 = vector134 - position3;
                                                            float num291 = (float)Math.Sin((double)(vector135.X / 30f * 6.2831855f));
                                                            float num292 = (float)Math.Sin((double)(vector135.Y / 30f * 6.2831855f));
                                                            float num293 = Utils.Remap(vector135.Length(), 0f, 30f, 0f, 1f, true);
                                                            vector133.X += num291 * num293 * 0.25f;
                                                            vector133.Y += num292 * num293 * 0.25f;
                                                            float num294 = (float)Math.Sin((double)(Utils.Remap(vector135.Length(), 0f, 20f, 0f, 1f, true) * 6.2831855f));
                                                            num289 += num294 * 0.7853982f * 0.1f * (float)rCurrentNPC.spriteDirection;
                                                        }
                                                        Vector2 vector136 = new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - 2f - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + num58 + rCurrentNPC.gfxOffY);
                                                        if (rCurrentNPC.velocity.Y == 0f)
{
                                                            vector136 = vector136.Floor();
                                                            int num295 = 2;
                                                            float num296 = vector136.X % 16f;
                                                            if (num296 < (float)num295)
{
                                                                vector136.X -= num296;
                                                            }
                                                            if (num296 > (float)(16 - num295))
{
                                                                vector136.X += 16f - num296;
                                                            }
                                                        }
                                                        mySpriteBatch.Draw(TextureAssets.Npc[type].Value, vector136, new Microsoft.Xna.Framework.Rectangle?(frame6), rCurrentNPC.GetAlpha(color10), num289, vector10, vector133, spriteEffects, 0f);
                                                    }
                                                    else if (type == 267)
{
                                                        Vector2 vector137 = rCurrentNPC.Center + new Vector2(0f, num59 + num58 + rCurrentNPC.gfxOffY) - screenPos;
                                                        mySpriteBatch.Draw(TextureAssets.Npc[type].Value, vector137, new Microsoft.Xna.Framework.Rectangle?(frame6), rCurrentNPC.GetAlpha(color10), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        if (rCurrentNPC.color != default(Microsoft.Xna.Framework.Color))
{
                                                            mySpriteBatch.Draw(TextureAssets.Npc[type].Value, vector137, new Microsoft.Xna.Framework.Rectangle?(frame6), rCurrentNPC.GetColor(color10), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        }
                                                    }
                                                    else if (rCurrentNPC.aiStyle == 7 && rCurrentNPC.ai[0] == 25f)
{
                                                        int num297 = type;
                                                        float num298 = Utils.Remap(rCurrentNPC.ai[1], 0f, 60f, 0f, 1f, true);
                                                        mySpriteBatch.End();
                                                        mySpriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend, SamplerState.PointClamp, DepthStencilState.Default, RasterizerState.CullNone, null, Main.Transform);
                                                        DrawData drawData5 = new DrawData(TextureAssets.Npc[num297].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + num58 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(frame6), Microsoft.Xna.Framework.Color.White * Utils.Remap(num298, 0f, 1f, 0f, 1f, true) * ((float)rCurrentNPC.GetAlpha(color10).A / 255f), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        drawData5.shader = ContentSamples.DyeShaderIDs.ColorOnlyShaderIndex;
                                                        GameShaders.Armor.Apply(ContentSamples.DyeShaderIDs.ColorOnlyShaderIndex, rCurrentNPC, new DrawData?(drawData5));
                                                        float num299 = Utils.Remap(rCurrentNPC.ai[1], 45f, 90f, 0f, 1f, true);
                                                        for (float num300 = 0f; num300 < 1f; num300 += 0.16666667f)
{
                                                            DrawData drawData6 = drawData5;
                                                            drawData6.color = Main.hslToRgb(num300, 0.9f, 0.65f, byte.MaxValue) * num299 * 0.5f;
                                                            drawData6.position += ((Main.GlobalTimeWrappedHourly + num300) * 6.2831855f).ToRotationVector2() * 4f * num299;
                                                            drawData6.Draw(mySpriteBatch);
                                                        }
                                                        drawData5.Draw(mySpriteBatch);
                                                        Main.pixelShader.CurrentTechnique.Passes[0].Apply();
                                                        Microsoft.Xna.Framework.Color color64 = new Microsoft.Xna.Framework.Color(255, 255, 255, 0);
                                                        float num301 = (float)Math.Sin(Main.timeForVisualEffects * 6.2831854820251465 / 20.0);
                                                        Main.DrawPrettyStarSparkle(num298, SpriteEffects.None, drawData5.position, color64, Main.hslToRgb(Main.GlobalTimeWrappedHourly % 1f, 1f, 0.65f, 127), Utils.Remap(rCurrentNPC.ai[1], 30f, 60f, 0f, 30f, true), 0f, 30f, 30f, 36f, 0f, new Vector2(1.5f, 2.5f) * (1f + num301 * 0.025f), new Vector2(2f, 2f));
                                                        Main.DrawPrettyStarSparkle(num298, SpriteEffects.None, drawData5.position, color64, Main.hslToRgb(Main.GlobalTimeWrappedHourly % 1f, 1f, 0.65f, 127), Utils.Remap(rCurrentNPC.ai[1], 30f, 60f, 0f, 30f, true), 0f, 30f, 30f, 36f, 0.7853982f, new Vector2(2.5f, 2.5f) * (1f + num301 * 0.025f), new Vector2(1f, 1f));
                                                        mySpriteBatch.End();
                                                        mySpriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, Main.DefaultSamplerState, DepthStencilState.None, Main.Rasterizer, null, Main.Transform);
                                                    }
                                                    else
{
                                                        int num302 = type;
                                                        if (NPC.IsMechQueenUp && num302 == 134)
{
                                                            num302 = 136;
                                                            this.LoadNPC(num302);
                                                        }
                                                        Vector2 vector138 = new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale + num57, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + num58 + rCurrentNPC.gfxOffY);
                                                        mySpriteBatch.Draw(TextureAssets.Npc[num302].Value, vector138, new Microsoft.Xna.Framework.Rectangle?(frame6), rCurrentNPC.GetAlpha(color10), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        if (rCurrentNPC.color != default(Microsoft.Xna.Framework.Color))
{
                                                            mySpriteBatch.Draw(TextureAssets.Npc[num302].Value, vector138, new Microsoft.Xna.Framework.Rectangle?(frame6), rCurrentNPC.GetColor(color10), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        }
                                                    }
                                                    if (rCurrentNPC.type == 695 && rCurrentNPC.ai[0] == 2f)
{
                                                        int num303 = 60;
                                                        int num304 = 0;
                                                        if (rCurrentNPC.ai[1] < (float)num303)
{
                                                            EmoteBubble.DrawTemporaryBubble(Main.spriteBatch, num304, num303, num303 - (int)rCurrentNPC.ai[1], rCurrentNPC);
                                                        }
                                                    }
                                                    if (rCurrentNPC.confused)
{
                                                        mySpriteBatch.Draw(TextureAssets.Confuse.Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + num58 - (float)TextureAssets.Confuse.Height() - 20f), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Confuse.Width(), TextureAssets.Confuse.Height())), rCurrentNPC.GetShimmerColor(new Microsoft.Xna.Framework.Color(250, 250, 250, 70)), rCurrentNPC.velocity.X * -0.05f, new Vector2((float)(TextureAssets.Confuse.Width() / 2), (float)(TextureAssets.Confuse.Height() / 2)), Main.essScale + 0.2f, SpriteEffects.None, 0f);
                                                    }
                                                    if (type == 247 || type == 248)
{
                                                        Vector2 vector139 = new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + num58 + rCurrentNPC.gfxOffY);
                                                        Texture2D value42 = TextureAssets.Npc[type].Value;
                                                        if (rCurrentNPC.ai[0] == 1f)
{
                                                            for (int num305 = 0; num305 < 3; num305++)
{
                                                                int num306 = num305 * 5;
                                                                int num307 = num306 + 15;
                                                                float num308 = Utils.Remap(rCurrentNPC.ai[1], (float)num306, (float)num307, 0f, 1f, true);
                                                                if (num308 != 0f)
{
                                                                    float num309 = Utils.Remap(num308, 0f, 1f, 2f, 1.1f + 0.1f * (float)num305, true);
                                                                    float num310 = num308;
                                                                    Microsoft.Xna.Framework.Color color65 = new Microsoft.Xna.Framework.Color(255, 255, 255, 0);
                                                                    mySpriteBatch.Draw(value42, vector139, new Microsoft.Xna.Framework.Rectangle?(frame6), color65 * num310, rCurrentNPC.rotation, vector10, rCurrentNPC.scale * num309, spriteEffects, 0f);
                                                                }
                                                            }
                                                        }
                                                        if (rCurrentNPC.ai[0] == 2f)
{
                                                            Microsoft.Xna.Framework.Color color66 = new Microsoft.Xna.Framework.Color(255, 255, 255, 0) * Utils.Remap(rCurrentNPC.ai[1], 0f, 30f, 1f, 0f, true);
                                                            for (int num311 = 0; num311 < 3; num311++)
{
                                                                float num312 = 1f;
                                                                Vector2 vector140 = vector139 + rCurrentNPC.velocity * (float)num311 * -2f;
                                                                float num313 = Utils.Remap((float)num311, 0f, 3f, 1f, 0f, true);
                                                                mySpriteBatch.Draw(value42, vector140, new Microsoft.Xna.Framework.Rectangle?(frame6), color66 * num313, rCurrentNPC.rotation, vector10, rCurrentNPC.scale * num312, spriteEffects, 0f);
                                                            }
                                                            for (int num314 = 0; num314 < 3; num314++)
{
                                                                float num315 = 1.1f + 0.1f * (float)num314;
                                                                mySpriteBatch.Draw(value42, vector139, new Microsoft.Xna.Framework.Rectangle?(frame6), color66, rCurrentNPC.rotation, vector10, rCurrentNPC.scale * num315, spriteEffects, 0f);
                                                            }
                                                        }
                                                    }
                                                    if (type == 24)
{
                                                        mySpriteBatch.Draw(TextureAssets.GlowMask[360].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + num58 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(frame6), rCurrentNPC.GetAlpha(Microsoft.Xna.Framework.Color.White), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    if (type >= 639 && type <= 645)
{
                                                        mySpriteBatch.Draw(TextureAssets.GlowMask[286].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + num58 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(frame6), rCurrentNPC.GetAlpha(Microsoft.Xna.Framework.Color.White), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    if (type >= 646 && type <= 652)
{
                                                        mySpriteBatch.Draw(TextureAssets.GlowMask[287].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + num58 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(frame6), rCurrentNPC.GetAlpha(Microsoft.Xna.Framework.Color.White), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    if (type >= 134 && type <= 136 && color10 != Microsoft.Xna.Framework.Color.Black)
{
                                                        mySpriteBatch.Draw(TextureAssets.Dest[type - 134].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + num58), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(255, 255, 255, 0) * (1f - (float)rCurrentNPC.alpha / 255f), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    else if (type == 125)
{
                                                        mySpriteBatch.Draw(TextureAssets.EyeLaser.Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + num58), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(255, 255, 255, 0), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    else if (type == 139)
{
                                                        mySpriteBatch.Draw(TextureAssets.Probe.Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + num58), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(255, 255, 255, 0), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    else if (type == 127)
{
                                                        if (NPC.IsMechQueenUp)
{
                                                            rCurrentNPC.whoAmI = rCurrentNPC.whoAmI;
                                                            for (int num316 = 0; num316 < Main.maxNPCs; num316++)
{
                                                                if (Main.npc[num316].active && (Main.npc[num316].type == 125 || Main.npc[num316].type == 126))
{
                                                                    float scale4 = Main.npc[num316].scale;
                                                                    float x = Main.npc[num316].Center.X;
                                                                    float y3 = Main.npc[num316].Center.Y;
                                                                    Vector2 mechQueenCenter = rCurrentNPC.GetMechQueenCenter();
                                                                    Vector2 vector141 = new Vector2((float)((Main.npc[num316].type == 125) ? (-18) : 20), -18f);
                                                                    vector141 = vector141.RotatedBy((double)rCurrentNPC.rotation, default(Vector2));
                                                                    Vector2 vector142 = mechQueenCenter + vector141;
                                                                    float num317 = x - vector142.X;
                                                                    float num318 = y3 - vector142.Y;
                                                                    float num319 = (float)Math.Atan2((double)num318, (double)num317) - 1.57f;
                                                                    bool flag13 = true;
                                                                    float num320 = (float)Math.Sqrt((double)(num317 * num317 + num318 * num318));
                                                                    if (num320 > 2000f)
{
                                                                        flag13 = false;
                                                                    }
                                                                    float num321 = 40f * scale4;
                                                                    while (flag13)
{
                                                                        num320 = (float)Math.Sqrt((double)(num317 * num317 + num318 * num318));
                                                                        if (num320 < num321)
{
                                                                            flag13 = false;
                                                                        }
                                                                        else
{
                                                                            num320 = (float)TextureAssets.Chain12.Height() * scale4 / num320;
                                                                            num317 *= num320;
                                                                            num318 *= num320;
                                                                            Microsoft.Xna.Framework.Color color67 = Lighting.GetColor((int)vector142.X / 16, (int)(vector142.Y / 16f));
                                                                            Main.spriteBatch.Draw(TextureAssets.Chain12.Value, new Vector2(vector142.X - Main.screenPosition.X, vector142.Y - Main.screenPosition.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain12.Width(), TextureAssets.Chain12.Height())), color67, num319, new Vector2((float)TextureAssets.Chain12.Width() * 0.5f, 0f), scale4, SpriteEffects.None, 0f);
                                                                            vector142.X += num317;
                                                                            vector142.Y += num318;
                                                                            num317 = x - vector142.X;
                                                                            num318 = y3 - vector142.Y;
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                        else
{
                                                            mySpriteBatch.Draw(TextureAssets.BoneEyes.Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + num58), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(200, 200, 200, 0), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        }
                                                    }
                                                    else if (type == 131)
{
                                                        mySpriteBatch.Draw(TextureAssets.BoneLaser.Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + num58), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(200, 200, 200, 0), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    else if (type == 120)
{
                                                        for (int num322 = 1; num322 < rCurrentNPC.oldPos.Length; num322++)
{
                                                            Vector2[] oldPos11 = rCurrentNPC.oldPos;
                                                            Microsoft.Xna.Framework.Color color68 = default(Microsoft.Xna.Framework.Color);
                                                            color68.R = (byte)(150 * (10 - num322) / 15);
                                                            color68.G = (byte)(100 * (10 - num322) / 15);
                                                            color68.B = (byte)(150 * (10 - num322) / 15);
                                                            color68.A = (byte)(50 * (10 - num322) / 15);
                                                            color68 = rCurrentNPC.GetShimmerColor(color68);
                                                            mySpriteBatch.Draw(TextureAssets.Chaos.Value, new Vector2(rCurrentNPC.oldPos[num322].X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.oldPos[num322].Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), color68, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        }
                                                    }
                                                    else if (type == 137 || type == 138)
{
                                                        for (int num323 = 1; num323 < rCurrentNPC.oldPos.Length; num323++)
{
                                                            Vector2[] oldPos12 = rCurrentNPC.oldPos;
                                                            Microsoft.Xna.Framework.Color color69 = default(Microsoft.Xna.Framework.Color);
                                                            color69.R = (byte)(150 * (10 - num323) / 15);
                                                            color69.G = (byte)(100 * (10 - num323) / 15);
                                                            color69.B = (byte)(150 * (10 - num323) / 15);
                                                            color69.A = (byte)(50 * (10 - num323) / 15);
                                                            color69 = rCurrentNPC.GetShimmerColor(color69);
                                                            mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(rCurrentNPC.oldPos[num323].X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.oldPos[num323].Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), color69, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        }
                                                    }
                                                    else if (type == 327)
{
                                                        mySpriteBatch.Draw(TextureAssets.PumpkingFace.Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), Microsoft.Xna.Framework.Color.White, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        for (int num324 = 1; num324 < 10; num324++)
{
                                                            Microsoft.Xna.Framework.Color color70 = new Microsoft.Xna.Framework.Color(110 - num324 * 10, 110 - num324 * 10, 110 - num324 * 10, 110 - num324 * 10);
                                                            Vector2 vector143 = new Vector2((float)Main.rand.Next(-10, 11) * 0.2f, (float)Main.rand.Next(-10, 11) * 0.2f);
                                                            mySpriteBatch.Draw(TextureAssets.PumpkingFace.Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59) + vector143, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), color70, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        }
                                                    }
                                                    else if (type == 325)
{
                                                        mySpriteBatch.Draw(TextureAssets.TreeFace.Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), Microsoft.Xna.Framework.Color.White, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        for (int num325 = 1; num325 < 10; num325++)
{
                                                            Microsoft.Xna.Framework.Color color71 = new Microsoft.Xna.Framework.Color(110 - num325 * 10, 110 - num325 * 10, 110 - num325 * 10, 110 - num325 * 10);
                                                            Vector2 vector144 = new Vector2((float)Main.rand.Next(-10, 11) * 0.2f, (float)Main.rand.Next(-10, 11) * 0.2f);
                                                            mySpriteBatch.Draw(TextureAssets.TreeFace.Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59) + vector144, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), color71, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        }
                                                    }
                                                    else if (type == 345)
{
                                                        mySpriteBatch.Draw(TextureAssets.IceQueen.Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), Microsoft.Xna.Framework.Color.White, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        for (int num326 = 1; num326 < 5; num326++)
{
                                                            Microsoft.Xna.Framework.Color color72 = new Microsoft.Xna.Framework.Color(100 - num326 * 10, 100 - num326 * 10, 100 - num326 * 10, 100 - num326 * 10);
                                                            mySpriteBatch.Draw(TextureAssets.IceQueen.Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59) - rCurrentNPC.velocity * (float)num326 * 0.2f, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), color72, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        }
                                                    }
                                                    else if (type == 355)
{
                                                        mySpriteBatch.Draw(TextureAssets.Firefly.Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(255, 255, 255, 0), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    else if (type == 358)
{
                                                        mySpriteBatch.Draw(TextureAssets.Lightningbug.Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(255, 255, 255, 0), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    else if (type == 654)
{
                                                        mySpriteBatch.Draw(TextureAssets.GlowMask[290].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(255, 255, 255, 0), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    else if (type == 653)
{
                                                        mySpriteBatch.Draw(TextureAssets.GlowMask[288].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 3f + vector10.Y * rCurrentNPC.scale + num59), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(255, 255, 255, 0), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    else if (type == 82)
{
                                                        mySpriteBatch.Draw(TextureAssets.WraithEye.Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), Microsoft.Xna.Framework.Color.White, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        for (int num327 = 1; num327 < 10; num327++)
{
                                                            Microsoft.Xna.Framework.Color color73 = new Microsoft.Xna.Framework.Color(110 - num327 * 10, 110 - num327 * 10, 110 - num327 * 10, 110 - num327 * 10);
                                                            mySpriteBatch.Draw(TextureAssets.WraithEye.Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59) - rCurrentNPC.velocity * (float)num327 * 0.5f, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), color73, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        }
                                                    }
                                                    else if (type == 253)
{
                                                        mySpriteBatch.Draw(TextureAssets.ReaperEye.Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 3f + vector10.Y * rCurrentNPC.scale + num59), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), Microsoft.Xna.Framework.Color.White, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        for (int num328 = 1; num328 < 20; num328++)
{
                                                            Microsoft.Xna.Framework.Color color74 = new Microsoft.Xna.Framework.Color(210 - num328 * 20, 210 - num328 * 20, 210 - num328 * 20, 210 - num328 * 20);
                                                            mySpriteBatch.Draw(TextureAssets.ReaperEye.Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 3f + vector10.Y * rCurrentNPC.scale + num59) - rCurrentNPC.velocity * (float)num328 * 0.5f, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), color74, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        }
                                                    }
                                                    else if (type == 245 && rCurrentNPC.alpha == 0 && !Main.getGoodWorld)
{
                                                        Microsoft.Xna.Framework.Color color75 = new Microsoft.Xna.Framework.Color((int)Main.mouseTextColor, (int)Main.mouseTextColor, (int)Main.mouseTextColor, 0);
                                                        mySpriteBatch.Draw(TextureAssets.Golem[3].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + num58 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(frame6), color75, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    else if (type == 246 && !Main.getGoodWorld)
{
                                                        Microsoft.Xna.Framework.Color color76 = new Microsoft.Xna.Framework.Color((int)Main.mouseTextColor, (int)Main.mouseTextColor, (int)Main.mouseTextColor, 0);
                                                        if (rCurrentNPC.frame.Y < 222)
{
                                                            if (!Main.getGoodWorld)
{
                                                                mySpriteBatch.Draw(TextureAssets.Golem[1].Value, new Vector2(rCurrentNPC.Center.X - screenPos.X - 20f, rCurrentNPC.Center.Y - screenPos.Y - 27f), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Golem[1].Width(), TextureAssets.Golem[1].Height() / 2)), color76, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
                                                            }
                                                            Microsoft.Xna.Framework.Rectangle rectangle25 = frame6;
                                                            rectangle25.Y = 0;
                                                            mySpriteBatch.Draw(TextureAssets.Extra[107].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + num58 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rectangle25), color76, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        }
                                                        else if (!Main.getGoodWorld && rCurrentNPC.frame.Y < 444)
{
                                                            mySpriteBatch.Draw(TextureAssets.Golem[2].Value, new Vector2(rCurrentNPC.Center.X - screenPos.X + 26f, rCurrentNPC.Center.Y - screenPos.Y - 28f), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Golem[2].Width(), TextureAssets.Golem[2].Height() / 4)), color76, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
                                                        }
                                                        else if (!Main.getGoodWorld)
{
                                                            mySpriteBatch.Draw(TextureAssets.Golem[2].Value, new Vector2(rCurrentNPC.Center.X - screenPos.X - 38f, rCurrentNPC.Center.Y - screenPos.Y - 28f), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, TextureAssets.Golem[2].Height() / 2, TextureAssets.Golem[2].Width(), TextureAssets.Golem[2].Height() / 4)), color76, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
                                                        }
                                                    }
                                                    else if (type == 249 && !Main.getGoodWorld)
{
                                                        Microsoft.Xna.Framework.Color color77 = new Microsoft.Xna.Framework.Color((int)Main.mouseTextColor, (int)Main.mouseTextColor, (int)Main.mouseTextColor, 0);
                                                        if (!Main.getGoodWorld)
{
                                                            mySpriteBatch.Draw(TextureAssets.Golem[1].Value, new Vector2(rCurrentNPC.Center.X - screenPos.X - 20f, rCurrentNPC.Center.Y - screenPos.Y - 47f), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Golem[1].Width(), TextureAssets.Golem[1].Height() / 2)), color77, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
                                                        }
                                                        int num329 = (int)rCurrentNPC.frameCounter / 4;
                                                        Texture2D texture2D11 = TextureAssets.Extra[106].Value;
                                                        Microsoft.Xna.Framework.Rectangle rectangle26 = texture2D11.Frame(1, 8, 0, 0, 0, 0);
                                                        Microsoft.Xna.Framework.Color white5 = Microsoft.Xna.Framework.Color.White;
                                                        rectangle26.Y += rectangle26.Height * 2 * num329 + frame6.Y;
                                                        mySpriteBatch.Draw(texture2D11, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + num58 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rectangle26), color77, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        texture2D11 = TextureAssets.Extra[107].Value;
                                                        rectangle26 = frame6;
                                                        mySpriteBatch.Draw(texture2D11, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + num58 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rectangle26), color77, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    else if (type == 383)
{
                                                        mySpriteBatch.Draw(TextureAssets.GlowMask[11].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + num58 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(frame6), new Microsoft.Xna.Framework.Color(255, 255, 255, 0), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        if (rCurrentNPC.ai[2] != 0f && Main.npc[(int)rCurrentNPC.ai[2] - 1].active && Main.npc[(int)rCurrentNPC.ai[2] - 1].type == 384)
{
                                                            float num330 = rCurrentNPC.ai[2];
                                                            mySpriteBatch.Draw(TextureAssets.Npc[384].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + num58 + rCurrentNPC.gfxOffY), null, new Microsoft.Xna.Framework.Color(100, 100, 100, 0), rCurrentNPC.rotation, new Vector2((float)TextureAssets.Npc[384].Width(), (float)TextureAssets.Npc[384].Height()) / 2f, rCurrentNPC.scale, spriteEffects, 0f);
                                                        }
                                                    }
                                                    else if (type == 381)
{
                                                        Vector2 vector145 = Vector2.Zero;
                                                        Vector2 zero4 = Vector2.Zero;
                                                        int num331 = TextureAssets.Npc[type].Height() / Main.npcFrameCount[type];
                                                        int num332 = rCurrentNPC.frame.Y / num331;
                                                        Microsoft.Xna.Framework.Rectangle rectangle27 = new Microsoft.Xna.Framework.Rectangle(0, 0, 32, 42);
                                                        switch (num332)
{
                                                        case 0:
                                                            vector145 += new Vector2(8f, 32f);
                                                            break;
                                                        case 1:
                                                            vector145 += new Vector2(6f, 72f);
                                                            break;
                                                        case 2:
                                                            vector145 += new Vector2(8f, 126f);
                                                            break;
                                                        case 3:
                                                            vector145 += new Vector2(6f, 174f);
                                                            break;
                                                        case 4:
                                                            vector145 += new Vector2(6f, 224f);
                                                            break;
                                                        case 5:
                                                            vector145 += new Vector2(8f, 272f);
                                                            break;
                                                        case 6:
                                                            vector145 += new Vector2(10f, 318f);
                                                            break;
                                                        case 7:
                                                            vector145 += new Vector2(14f, 366f);
                                                            break;
                                                        case 8:
                                                            vector145 += new Vector2(10f, 414f);
                                                            break;
                                                        }
                                                        vector145.Y -= (float)(num331 * num332);
                                                        vector145 -= vector10;
                                                        int num333 = 2;
                                                        if (rCurrentNPC.ai[2] > 0f)
{
                                                            num333 = (int)rCurrentNPC.ai[2] - 1;
                                                        }
                                                        if (rCurrentNPC.velocity.Y != 0f)
{
                                                            num333 = 3;
                                                        }
                                                        rectangle27.Y += 44 * num333;
                                                        switch (num333)
{
                                                        case 0:
                                                            zero4 = new Vector2(10f, 18f);
                                                            break;
                                                        case 1:
                                                            zero4 = new Vector2(8f, 20f);
                                                            break;
                                                        case 2:
                                                            zero4 = new Vector2(8f, 20f);
                                                            break;
                                                        case 3:
                                                            zero4 = new Vector2(8f, 20f);
                                                            break;
                                                        case 4:
                                                            zero4 = new Vector2(6f, 18f);
                                                            break;
                                                        }
                                                        if ((spriteEffects & SpriteEffects.FlipHorizontally) != SpriteEffects.None)
{
                                                            vector145.X *= -1f;
                                                            zero4.X = (float)rectangle27.Width - zero4.X;
                                                        }
                                                        vector145 += rCurrentNPC.Center;
                                                        vector145 -= screenPos;
                                                        vector145.Y += rCurrentNPC.gfxOffY;
                                                        mySpriteBatch.Draw(TextureAssets.Extra[0].Value, vector145, new Microsoft.Xna.Framework.Rectangle?(rectangle27), color10, rCurrentNPC.rotation, zero4, rCurrentNPC.scale, spriteEffects, 0f);
                                                        mySpriteBatch.Draw(TextureAssets.GlowMask[24].Value, vector145, new Microsoft.Xna.Framework.Rectangle?(rectangle27), new Microsoft.Xna.Framework.Color(255, 255, 255, 0), rCurrentNPC.rotation, zero4, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    else if (type == 382)
{
                                                        Vector2 vector146 = Vector2.Zero;
                                                        Vector2 zero5 = Vector2.Zero;
                                                        int num334 = TextureAssets.Npc[type].Height() / Main.npcFrameCount[type];
                                                        int num335 = rCurrentNPC.frame.Y / num334;
                                                        Microsoft.Xna.Framework.Rectangle rectangle28 = new Microsoft.Xna.Framework.Rectangle(0, 0, 30, 42);
                                                        switch (num335)
{
                                                        case 0:
                                                            vector146 += new Vector2(8f, 30f);
                                                            break;
                                                        case 1:
                                                            vector146 += new Vector2(6f, 68f);
                                                            break;
                                                        case 2:
                                                            vector146 += new Vector2(8f, 120f);
                                                            break;
                                                        case 3:
                                                            vector146 += new Vector2(6f, 166f);
                                                            break;
                                                        case 4:
                                                            vector146 += new Vector2(6f, 214f);
                                                            break;
                                                        case 5:
                                                            vector146 += new Vector2(8f, 260f);
                                                            break;
                                                        case 6:
                                                            vector146 += new Vector2(14f, 304f);
                                                            break;
                                                        case 7:
                                                            vector146 += new Vector2(14f, 350f);
                                                            break;
                                                        case 8:
                                                            vector146 += new Vector2(10f, 396f);
                                                            break;
                                                        }
                                                        vector146.Y -= (float)(num334 * num335);
                                                        vector146 -= vector10;
                                                        int num336 = 2;
                                                        if (rCurrentNPC.ai[2] > 0f)
{
                                                            num336 = (int)rCurrentNPC.ai[2] - 1;
                                                        }
                                                        if (rCurrentNPC.velocity.Y != 0f)
{
                                                            num336 = 3;
                                                        }
                                                        rectangle28.Y += 44 * num336;
                                                        switch (num336)
{
                                                        case 0:
                                                            zero5 = new Vector2(10f, 18f);
                                                            break;
                                                        case 1:
                                                            zero5 = new Vector2(8f, 20f);
                                                            break;
                                                        case 2:
                                                            zero5 = new Vector2(8f, 20f);
                                                            break;
                                                        case 3:
                                                            zero5 = new Vector2(8f, 20f);
                                                            break;
                                                        case 4:
                                                            zero5 = new Vector2(6f, 18f);
                                                            break;
                                                        }
                                                        if ((spriteEffects & SpriteEffects.FlipHorizontally) != SpriteEffects.None)
{
                                                            vector146.X *= -1f;
                                                            zero5.X = (float)rectangle28.Width - zero5.X;
                                                        }
                                                        vector146 += rCurrentNPC.Center;
                                                        vector146 -= screenPos;
                                                        vector146.Y += rCurrentNPC.gfxOffY;
                                                        mySpriteBatch.Draw(TextureAssets.Extra[1].Value, vector146, new Microsoft.Xna.Framework.Rectangle?(rectangle28), color10, rCurrentNPC.rotation, zero5, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    else if (type == 520)
{
                                                        mySpriteBatch.Draw(TextureAssets.GlowMask[164].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + num58 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(frame6), new Microsoft.Xna.Framework.Color(255, 255, 255, 0), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        Vector2 vector147 = Vector2.Zero;
                                                        Vector2 vector148 = new Vector2(4f, 4f);
                                                        int num337 = TextureAssets.Npc[type].Height() / Main.npcFrameCount[type];
                                                        int num338 = rCurrentNPC.frame.Y / num337;
                                                        if ((spriteEffects & SpriteEffects.FlipHorizontally) != SpriteEffects.None)
{
                                                            vector147.X *= -1f;
                                                            vector148.X = (float)TextureAssets.Extra[56].Width() - vector148.X;
                                                        }
                                                        vector147 += rCurrentNPC.Top + new Vector2(0f, 20f);
                                                        vector147 -= screenPos;
                                                        vector147.Y += rCurrentNPC.gfxOffY;
                                                        float num339 = rCurrentNPC.localAI[3];
                                                        if ((spriteEffects & SpriteEffects.FlipHorizontally) != SpriteEffects.None)
{
                                                            num339 += 3.1415927f;
                                                        }
                                                        mySpriteBatch.Draw(TextureAssets.Extra[56].Value, vector147, null, color10, num339, vector148, rCurrentNPC.scale, spriteEffects, 0f);
                                                        mySpriteBatch.Draw(TextureAssets.GlowMask[165].Value, vector147, null, new Microsoft.Xna.Framework.Color(255, 255, 255, 0), num339, vector148, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    else if (type == 386)
{
                                                        mySpriteBatch.Draw(TextureAssets.GlowMask[31].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + num58 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(frame6), new Microsoft.Xna.Framework.Color(255, 255, 255, 0), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    else if (type == 387)
{
                                                        Microsoft.Xna.Framework.Color color78 = new Microsoft.Xna.Framework.Color(1f, 1f, 1f, 1f) * 0.75f;
                                                        if (rCurrentNPC.ai[0] > 0f)
{
                                                            float num340 = (rCurrentNPC.ai[0] + 1f) / 60f;
                                                            color78 = Microsoft.Xna.Framework.Color.Lerp(color78, Microsoft.Xna.Framework.Color.White, num340);
                                                            color78.A = (byte)MathHelper.Lerp((float)color78.A, 0f, num340);
                                                        }
                                                        color78 *= (255f - (float)rCurrentNPC.alpha) / 255f;
                                                        mySpriteBatch.Draw(TextureAssets.GlowMask[32].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + num58 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(frame6), color78, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    else if (type == 388)
{
                                                        mySpriteBatch.Draw(TextureAssets.GlowMask[33].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + num58 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(frame6), new Microsoft.Xna.Framework.Color(255, 255, 255, 0), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    else if (type == 389)
{
                                                        mySpriteBatch.Draw(TextureAssets.GlowMask[34].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + num58 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(frame6), new Microsoft.Xna.Framework.Color(255, 255, 255, 0), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    else if (type == 4 && rCurrentNPC.ai[1] >= 4f && rCurrentNPC.ai[0] == 3f)
{
                                                        for (int num341 = 1; num341 < rCurrentNPC.oldPos.Length; num341++)
{
                                                            Vector2[] oldPos13 = rCurrentNPC.oldPos;
                                                            Microsoft.Xna.Framework.Color color79 = color10;
                                                            color79.R = (byte)(0.5 * (double)color79.R * (double)(10 - num341) / 20.0);
                                                            color79.G = (byte)(0.5 * (double)color79.G * (double)(10 - num341) / 20.0);
                                                            color79.B = (byte)(0.5 * (double)color79.B * (double)(10 - num341) / 20.0);
                                                            color79.A = (byte)(0.5 * (double)color79.A * (double)(10 - num341) / 20.0);
                                                            mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(rCurrentNPC.oldPos[num341].X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.oldPos[num341].Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), color79, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        }
                                                    }
                                                    else if (type == 437)
{
                                                        Microsoft.Xna.Framework.Color white6 = Microsoft.Xna.Framework.Color.White;
                                                        white6.A = 200;
                                                        mySpriteBatch.Draw(TextureAssets.GlowMask[109].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + num58 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(frame6), white6, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        mySpriteBatch.Draw(TextureAssets.GlowMask[108].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + num58 + rCurrentNPC.gfxOffY), null, white6, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    else if (type == 471 && rCurrentNPC.ai[3] < 0f)
{
                                                        for (int num342 = 1; num342 < rCurrentNPC.oldPos.Length; num342++)
{
                                                            Vector2[] oldPos14 = rCurrentNPC.oldPos;
                                                            Microsoft.Xna.Framework.Color color80 = color10;
                                                            color80.R = (byte)(0.5 * (double)color80.R * (double)(10 - num342) / 20.0);
                                                            color80.G = (byte)(0.5 * (double)color80.G * (double)(10 - num342) / 20.0);
                                                            color80.B = (byte)(0.5 * (double)color80.B * (double)(10 - num342) / 20.0);
                                                            color80.A = (byte)(0.5 * (double)color80.A * (double)(10 - num342) / 20.0);
                                                            mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(rCurrentNPC.oldPos[num342].X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.oldPos[num342].Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), color80, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        }
                                                    }
                                                    else if (type == 477 && rCurrentNPC.velocity.Length() > 9f)
{
                                                        for (int num343 = 1; num343 < rCurrentNPC.oldPos.Length; num343++)
{
                                                            Vector2[] oldPos15 = rCurrentNPC.oldPos;
                                                            Microsoft.Xna.Framework.Color color81 = color10;
                                                            color81.R = (byte)(0.5 * (double)color81.R * (double)(10 - num343) / 20.0);
                                                            color81.G = (byte)(0.5 * (double)color81.G * (double)(10 - num343) / 20.0);
                                                            color81.B = (byte)(0.5 * (double)color81.B * (double)(10 - num343) / 20.0);
                                                            color81.A = (byte)(0.5 * (double)color81.A * (double)(10 - num343) / 20.0);
                                                            Microsoft.Xna.Framework.Rectangle frame7 = rCurrentNPC.frame;
                                                            int num344 = TextureAssets.Npc[type].Height() / Main.npcFrameCount[type];
                                                            frame7.Y -= num344 * num343;
                                                            while (frame7.Y < 0)
{
                                                                frame7.Y += num344 * Main.npcFrameCount[type];
                                                            }
                                                            mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(rCurrentNPC.oldPos[num343].X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.oldPos[num343].Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59), new Microsoft.Xna.Framework.Rectangle?(frame7), color81, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        }
                                                    }
                                                    if (type == 479 && (double)rCurrentNPC.velocity.Length() > 6.5)
{
                                                        for (int num345 = 1; num345 < rCurrentNPC.oldPos.Length; num345++)
{
                                                            Vector2[] oldPos16 = rCurrentNPC.oldPos;
                                                            Microsoft.Xna.Framework.Color color82 = color10;
                                                            color82.R = (byte)(0.5 * (double)color82.R * (double)(10 - num345) / 20.0);
                                                            color82.G = (byte)(0.5 * (double)color82.G * (double)(10 - num345) / 20.0);
                                                            color82.B = (byte)(0.5 * (double)color82.B * (double)(10 - num345) / 20.0);
                                                            color82.A = (byte)(0.5 * (double)color82.A * (double)(10 - num345) / 20.0);
                                                            Microsoft.Xna.Framework.Rectangle frame8 = rCurrentNPC.frame;
                                                            int num346 = TextureAssets.Npc[type].Height() / Main.npcFrameCount[type];
                                                            frame8.Y -= num346 * num345;
                                                            while (frame8.Y < 0)
{
                                                                frame8.Y += num346 * Main.npcFrameCount[type];
                                                            }
                                                            mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(rCurrentNPC.oldPos[num345].X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.oldPos[num345].Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59), new Microsoft.Xna.Framework.Rectangle?(frame8), color82, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        }
                                                    }
                                                    else if (type == 472)
{
                                                        mySpriteBatch.Draw(TextureAssets.GlowMask[110].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 0), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    else if (rCurrentNPC.aiStyle == 87)
{
                                                        if ((int)rCurrentNPC.ai[0] == 4 || rCurrentNPC.ai[0] == 5f || rCurrentNPC.ai[0] == 6f)
{
                                                            for (int num347 = 1; num347 < rCurrentNPC.oldPos.Length; num347++)
{
                                                                Vector2[] oldPos17 = rCurrentNPC.oldPos;
                                                                Microsoft.Xna.Framework.Color color83 = color10;
                                                                color83.R = (byte)(0.5 * (double)color83.R * (double)(10 - num347) / 20.0);
                                                                color83.G = (byte)(0.5 * (double)color83.G * (double)(10 - num347) / 20.0);
                                                                color83.B = (byte)(0.5 * (double)color83.B * (double)(10 - num347) / 20.0);
                                                                color83.A = (byte)(0.5 * (double)color83.A * (double)(10 - num347) / 20.0);
                                                                color83 = rCurrentNPC.GetShimmerColor(color83);
                                                                mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(rCurrentNPC.oldPos[num347].X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, rCurrentNPC.oldPos[num347].Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), color83, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                            }
                                                        }
                                                    }
                                                    else if (type == 50)
{
                                                        Texture2D value43 = TextureAssets.Extra[39].Value;
                                                        Vector2 center5 = rCurrentNPC.Center;
                                                        float num348 = 0f;
                                                        switch (rCurrentNPC.frame.Y / (TextureAssets.Npc[type].Height() / Main.npcFrameCount[type]))
{
                                                        case 0:
                                                            num348 = 2f;
                                                            break;
                                                        case 1:
                                                            num348 = -6f;
                                                            break;
                                                        case 2:
                                                            num348 = 2f;
                                                            break;
                                                        case 3:
                                                            num348 = 10f;
                                                            break;
                                                        case 4:
                                                            num348 = 2f;
                                                            break;
                                                        case 5:
                                                            num348 = 0f;
                                                            break;
                                                        }
                                                        center5.Y += rCurrentNPC.gfxOffY - (70f - num348) * rCurrentNPC.scale;
                                                        mySpriteBatch.Draw(value43, center5 - screenPos, null, color10, 0f, value43.Size() / 2f, 1f, spriteEffects, 0f);
                                                    }
                                                    else if (type == 411)
{
                                                        mySpriteBatch.Draw(TextureAssets.GlowMask[136].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-(float)TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, (float)(-(float)TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 0), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    else if (type == 409)
{
                                                        mySpriteBatch.Draw(TextureAssets.GlowMask[138].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-(float)TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, (float)(-(float)TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    else if (type == 410)
{
                                                        mySpriteBatch.Draw(TextureAssets.GlowMask[137].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-(float)TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, (float)(-(float)TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    else if (type == 407)
{
                                                        mySpriteBatch.Draw(TextureAssets.GlowMask[139].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-(float)TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, (float)(-(float)TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    else if (type == 405)
{
                                                        mySpriteBatch.Draw(TextureAssets.GlowMask[141].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-(float)TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, (float)(-(float)TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 0), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    else if (type == 406)
{
                                                        mySpriteBatch.Draw(TextureAssets.GlowMask[142].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-(float)TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, (float)(-(float)TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 0), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    else if (type == 424)
{
                                                        mySpriteBatch.Draw(TextureAssets.GlowMask[144].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-(float)TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, (float)(-(float)TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 0), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    else if (type == 423)
{
                                                        mySpriteBatch.Draw(TextureAssets.GlowMask[145].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-(float)TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, (float)(-(float)TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 0), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    else if (type == 421)
{
                                                        mySpriteBatch.Draw(TextureAssets.GlowMask[146].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-(float)TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, (float)(-(float)TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 0), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    else if (type == 420)
{
                                                        mySpriteBatch.Draw(TextureAssets.GlowMask[147].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-(float)TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, (float)(-(float)TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 0), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    else if (type == 425)
{
                                                        Vector2 vector149 = rCurrentNPC.Bottom - screenPos + new Vector2((float)(-(float)TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, (float)(-(float)TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + rCurrentNPC.gfxOffY);
                                                        mySpriteBatch.Draw(TextureAssets.GlowMask[150].Value, vector149, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 0), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        Vector2 vector150 = vector149 + new Vector2((float)(27 * -(float)rCurrentNPC.spriteDirection), 0f);
                                                        float num349 = rCurrentNPC.ai[3];
                                                        Main.DrawPrettyStarSparkle(Utils.Remap(num349, 0f, 15f, 0f, 1f, true), SpriteEffects.None, vector150, new Microsoft.Xna.Framework.Color(255, 255, 255, 0), Microsoft.Xna.Framework.Color.Green, num349, 0f, 30f, 30f, 36f, 0f, new Vector2(3f, 1.5f), new Vector2(2f, 2f));
                                                    }
                                                    else if (type == 429)
{
                                                        mySpriteBatch.Draw(TextureAssets.GlowMask[151].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-(float)TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, (float)(-(float)TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 0), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    else if (type == 418)
{
                                                        mySpriteBatch.Draw(TextureAssets.GlowMask[161].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-(float)TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, (float)(-(float)TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        float num350 = 0.25f + (rCurrentNPC.GetAlpha(color10).ToVector3() - new Vector3(0.5f)).Length() * 0.25f;
                                                        for (int num351 = 0; num351 < 4; num351++)
{
                                                            mySpriteBatch.Draw(TextureAssets.GlowMask[161].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-(float)TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, (float)(-(float)TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + rCurrentNPC.gfxOffY) + rCurrentNPC.velocity.RotatedBy((double)((float)num351 * 1.5707964f), default(Vector2)) * num350, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(64, 64, 64, 0), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        }
                                                    }
                                                    else if (type >= 412 && type <= 414)
{
                                                        Microsoft.Xna.Framework.Color color84 = new Microsoft.Xna.Framework.Color(255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 0);
                                                        int num352 = 157 + type - 412;
                                                        if (type == 414 && rCurrentNPC.localAI[2] != 0f)
{
                                                            int num353 = (int)rCurrentNPC.localAI[2];
                                                            if (rCurrentNPC.localAI[2] < 0f)
{
                                                                num353 = 128 + (int)rCurrentNPC.localAI[2];
                                                            }
                                                            int num354 = 255 - num353;
                                                            color84 = new Microsoft.Xna.Framework.Color(num354, num353, num353, num354);
                                                        }
                                                        mySpriteBatch.Draw(TextureAssets.GlowMask[num352].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-(float)TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, (float)(-(float)TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), color84, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    else if (type == 415)
{
                                                        mySpriteBatch.Draw(TextureAssets.GlowMask[155].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-(float)TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, (float)(-(float)TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        float num355 = 0.5f + (rCurrentNPC.GetAlpha(color10).ToVector3() - new Vector3(0.5f)).Length() * 0.5f;
                                                        for (int num356 = 0; num356 < 4; num356++)
{
                                                            mySpriteBatch.Draw(TextureAssets.GlowMask[155].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-(float)TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, (float)(-(float)TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + rCurrentNPC.gfxOffY) + rCurrentNPC.velocity.RotatedBy((double)((float)num356 * 1.5707964f), default(Vector2)) * num355, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(64, 64, 64, 0), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        }
                                                    }
                                                    else if (type == 419)
{
                                                        mySpriteBatch.Draw(TextureAssets.GlowMask[154].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-(float)TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, (float)(-(float)TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        if (rCurrentNPC.ai[2] >= -6f)
{
                                                            float num357 = 0.5f + (rCurrentNPC.GetAlpha(color10).ToVector3() - new Vector3(0.5f)).Length() * 0.5f;
                                                            for (int num358 = 0; num358 < 4; num358++)
{
                                                                mySpriteBatch.Draw(TextureAssets.GlowMask[154].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-(float)TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, (float)(-(float)TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + rCurrentNPC.gfxOffY) + rCurrentNPC.velocity.RotatedBy((double)((float)num358 * 1.5707964f), default(Vector2)) * num357, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(64, 64, 64, 0), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                            }
                                                        }
                                                        else
{
                                                            float num359 = 4f;
                                                            for (int num360 = 0; num360 < 4; num360++)
{
                                                                mySpriteBatch.Draw(TextureAssets.GlowMask[154].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-(float)TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, (float)(-(float)TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + rCurrentNPC.gfxOffY) + Vector2.UnitX.RotatedBy((double)((float)num360 * 1.5707964f), default(Vector2)) * num359, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(64, 64, 64, 0), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                            }
                                                        }
                                                    }
                                                    else if (type == 417)
{
                                                        mySpriteBatch.Draw(TextureAssets.GlowMask[160].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-(float)TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, (float)(-(float)TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        float num361 = 0.25f + (rCurrentNPC.GetAlpha(color10).ToVector3() - new Vector3(0.5f)).Length() * 0.25f;
                                                        for (int num362 = 0; num362 < 4; num362++)
{
                                                            mySpriteBatch.Draw(TextureAssets.GlowMask[160].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-(float)TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, (float)(-(float)TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + rCurrentNPC.gfxOffY) + rCurrentNPC.velocity.RotatedBy((double)((float)num362 * 1.5707964f), default(Vector2)) * num361, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(64, 64, 64, 0), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        }
                                                    }
                                                    else if (type == 516)
{
                                                        mySpriteBatch.Draw(TextureAssets.Npc[type].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-(float)TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, (float)(-(float)TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        float num363 = 0.5f + (rCurrentNPC.GetAlpha(color10).ToVector3() - new Vector3(0.5f)).Length() * 0.5f;
                                                        for (int num364 = 0; num364 < 4; num364++)
{
                                                            mySpriteBatch.Draw(TextureAssets.Npc[type].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-(float)TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, (float)(-(float)TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + rCurrentNPC.gfxOffY) + rCurrentNPC.velocity.RotatedBy((double)((float)num364 * 1.5707964f), default(Vector2)) * num363, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(64, 64, 64, 0), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        }
                                                    }
                                                    else if (type == 518)
{
                                                        Vector2 vector151 = new Vector2(-10f, 0f);
                                                        mySpriteBatch.Draw(TextureAssets.GlowMask[163].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-(float)TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, (float)(-(float)TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha), rCurrentNPC.rotation, vector10 + vector151, rCurrentNPC.scale, spriteEffects, 0f);
                                                        float num365 = 0.5f + (rCurrentNPC.GetAlpha(color10).ToVector3() - new Vector3(0.5f)).Length() * 0.5f;
                                                        for (int num366 = 0; num366 < 4; num366++)
{
                                                            mySpriteBatch.Draw(TextureAssets.GlowMask[163].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-(float)TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, (float)(-(float)TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + rCurrentNPC.gfxOffY) + rCurrentNPC.velocity.RotatedBy((double)((float)num366 * 1.5707964f), default(Vector2)) * num365, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(64, 64, 64, 0), rCurrentNPC.rotation, vector10 + vector151, rCurrentNPC.scale, spriteEffects, 0f);
                                                        }
                                                    }
                                                    else if (type == 344)
{
                                                        mySpriteBatch.Draw(TextureAssets.GlowMask[253].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-(float)TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, (float)(-(float)TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(200, 200, 200, 100) * 0.5f, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    else if (type == 346)
{
                                                        float num367 = 4f;
                                                        for (int num368 = 0; num368 < 4; num368++)
{
                                                            mySpriteBatch.Draw(TextureAssets.GlowMask[254].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-(float)TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, (float)(-(float)TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + rCurrentNPC.gfxOffY) + Vector2.UnitX.RotatedBy((double)((float)num368 * 1.5707964f), default(Vector2)) * num367, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(64, 64, 64, 0), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        }
                                                        mySpriteBatch.Draw(TextureAssets.GlowMask[254].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-(float)TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, (float)(-(float)TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(200, 200, 200, 100), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    else if (type == 315)
{
                                                        float num369 = 2f;
                                                        for (int num370 = 0; num370 < 4; num370++)
{
                                                            mySpriteBatch.Draw(TextureAssets.GlowMask[255].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-(float)TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, (float)(-(float)TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + rCurrentNPC.gfxOffY) + Vector2.UnitX.RotatedBy((double)((float)num370 * 1.5707964f), default(Vector2)) * num369, new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(64, 64, 64, 0), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                        }
                                                        mySpriteBatch.Draw(TextureAssets.GlowMask[255].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-(float)TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, (float)(-(float)TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(200, 200, 200, 200), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    else if (type == 525)
{
                                                        mySpriteBatch.Draw(TextureAssets.GlowMask[169].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-(float)TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, (float)(-(float)TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(200, 200, 200, 100), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    else if (type == 526)
{
                                                        mySpriteBatch.Draw(TextureAssets.GlowMask[170].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-(float)TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, (float)(-(float)TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(200, 200, 200, 100), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    else if (type == 527)
{
                                                        mySpriteBatch.Draw(TextureAssets.GlowMask[171].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-(float)TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, (float)(-(float)TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(200, 200, 200, 100), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    else if (type == 533)
{
                                                        mySpriteBatch.Draw(TextureAssets.GlowMask[172].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-(float)TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, (float)(-(float)TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(255, 255, 255, 100), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    else if (type == 160)
{
                                                        Texture2D texture2D12;
                                                        if (rCurrentNPC.townNpcVariationIndex == 1)
{
                                                            texture2D12 = TextureAssets.GlowMask[352].Value;
                                                        }
                                                        else
{
                                                            texture2D12 = TextureAssets.GlowMask[166].Value;
                                                        }
                                                        Microsoft.Xna.Framework.Color color85 = new Microsoft.Xna.Framework.Color(128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 0);
                                                        if (rCurrentNPC.shimmerTransparency > 0f)
{
                                                            color85.R = (byte)((float)color85.R * (1f - rCurrentNPC.shimmerTransparency));
                                                            color85.G = (byte)((float)color85.G * (1f - rCurrentNPC.shimmerTransparency));
                                                            color85.B = (byte)((float)color85.B * (1f - rCurrentNPC.shimmerTransparency));
                                                        }
                                                        mySpriteBatch.Draw(texture2D12, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-(float)TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, (float)(-(float)TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), color85, rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    else if (type == 209)
{
                                                        Texture2D texture2D13;
                                                        if (rCurrentNPC.townNpcVariationIndex == 1)
{
                                                            if (rCurrentNPC.altTexture == 1)
{
                                                                texture2D13 = TextureAssets.GlowMask[351].Value;
                                                            }
                                                            else
{
                                                                texture2D13 = TextureAssets.GlowMask[350].Value;
                                                            }
                                                        }
                                                        else
{
                                                            texture2D13 = TextureAssets.GlowMask[167].Value;
                                                        }
                                                        mySpriteBatch.Draw(texture2D13, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-(float)TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + vector10.X * rCurrentNPC.scale, (float)(-(float)TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)Main.npcFrameCount[type] + 4f + vector10.Y * rCurrentNPC.scale + num59 + rCurrentNPC.gfxOffY), new Microsoft.Xna.Framework.Rectangle?(rCurrentNPC.frame), new Microsoft.Xna.Framework.Color(128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 0), rCurrentNPC.rotation, vector10, rCurrentNPC.scale, spriteEffects, 0f);
                                                    }
                                                    if (rCurrentNPC.aiStyle == 7)
{
                                                        this.DrawNPCExtras(rCurrentNPC, false, num59, num58, color10, vector10, spriteEffects, screenPos);
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
References Microsoft.Xna.Framework.Color.A, System.Math.Abs(), System.Math.Acos(), Terraria.Graphics.Effects.EffectManager< T >.Activate(), Terraria.NPC.active, Terraria.NPC.ai, Terraria.NPC.AI_113_WindyBalloon_GetSlaveNPC(), Terraria.GameInput.LockOnHelper.AimedTarget, Terraria.NPC.aiStyle, Terraria.FocusHelper.AllowMiscDustEffects, Terraria.NPC.alpha, Microsoft.Xna.Framework.Graphics.BlendState.AlphaBlend, Terraria.NPC.altTexture, Terraria.GameContent.TextureAssets.AntLion, Terraria.Graphics.Shaders.ArmorShaderDataSet.Apply(), Terraria.Graphics.Shaders.GameShaders.Armor, Terraria.Main.Assets, System.Math.Atan2(), Microsoft.Xna.Framework.Color.B, Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(), Microsoft.Xna.Framework.Color.Black, Microsoft.Xna.Framework.Color.Blue, Terraria.GameContent.TextureAssets.BoneArm, Terraria.GameContent.TextureAssets.BoneArm2, Terraria.GameContent.TextureAssets.BoneArm3, Terraria.GameContent.TextureAssets.BoneEyes, Terraria.GameContent.TextureAssets.BoneLaser, Terraria.NPC.boss, Microsoft.Xna.Framework.Rectangle.Bottom, Terraria.Entity.Bottom, Terraria.Lighting.Brightness(), Terraria.Main.buffColor(), Terraria.Entity.Center, Terraria.GameContent.TextureAssets.Chain, Terraria.GameContent.TextureAssets.Chain10, Terraria.GameContent.TextureAssets.Chain11, Terraria.GameContent.TextureAssets.Chain12, Terraria.GameContent.TextureAssets.Chain14, Terraria.GameContent.TextureAssets.Chain21, Terraria.GameContent.TextureAssets.Chain24, Terraria.GameContent.TextureAssets.Chain25, Terraria.GameContent.TextureAssets.Chain4, Terraria.GameContent.TextureAssets.Chain5, Terraria.GameContent.TextureAssets.Chaos, Microsoft.Xna.Framework.MathHelper.Clamp(), Terraria.NPC.color, Terraria.ID.ContentSamples.DyeShaderIDs.ColorOnlyShaderIndex, Terraria.GameContent.TextureAssets.Confuse, Terraria.NPC.confused, Microsoft.Xna.Framework.Color.CornflowerBlue, System.Math.Cos(), Microsoft.Xna.Framework.Graphics.RasterizerState.CullNone, Microsoft.Xna.Framework.Graphics.Effect.CurrentTechnique, Microsoft.Xna.Framework.Graphics.DepthStencilState.Default, Terraria.Main.DefaultSamplerState, Terraria.GameContent.TextureAssets.Dest, Terraria.Entity.direction, Terraria.Entity.Distance(), Terraria.NPC.dontTakeDamageFromHostiles, Terraria.DataStructures.DrawData.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Main.DrawNPC_SlimeItem(), Terraria.Main.DrawNPCDirect_Deerclops(), Terraria.Main.DrawNPCDirect_Faeling(), Terraria.Main.DrawNPCDirect_HallowBoss(), Terraria.Main.DrawPrettyStarSparkle(), Terraria.GameContent.UI.EmoteBubble.DrawTemporaryBubble(), Terraria.GameContent.TextureAssets.DukeFishron, Terraria.Main.dust, Microsoft.Xna.Framework.Graphics.SpriteBatch.End(), Terraria.Main.essScale, Terraria.Main.expertMode, Terraria.GameContent.TextureAssets.Extra, Terraria.GameContent.TextureAssets.EyeLaser, Terraria.GameContent.TextureAssets.Firefly, Terraria.NPC.frame, Terraria.NPC.frameCounter, Microsoft.Xna.Framework.Color.G, Terraria.NPC.GetAlpha(), Terraria.NPC.GetBestiaryEntryColor(), Terraria.NPC.GetColor(), Terraria.Lighting.GetColor(), Terraria.Main.getGoodWorld, Terraria.Main.GetItemDrawFrame(), Terraria.Utils.GetLerpValue(), Terraria.NPC.GetMechQueenCenter(), Terraria.NPC.GetNPCColorTintedByBuffs(), Terraria.NPC.GetShimmerColor(), Terraria.NPC.gfxOffY, Terraria.Player.gfxOffY, Terraria.Main.GlobalTimeWrappedHourly, Terraria.GameContent.TextureAssets.GlowMask, Microsoft.Xna.Framework.Color.Gold, Terraria.GameContent.TextureAssets.Golem, Terraria.NPC.golemBoss, Microsoft.Xna.Framework.Graphics.GraphicsResource.GraphicsDevice, Terraria.Player.gravDir, Microsoft.Xna.Framework.Color.Green, Microsoft.Xna.Framework.Graphics.Texture2D.Height, Microsoft.Xna.Framework.Rectangle.Height, Terraria.Entity.height, Microsoft.Xna.Framework.Color.HotPink, Terraria.Main.hslToRgb(), Terraria.GameContent.TextureAssets.IceQueen, Microsoft.Xna.Framework.Rectangle.Inflate(), int, Terraria.NPC.IsABestiaryIconDummy, Terraria.NPC.IsAPortraitDummy, ReLogic.Content.Asset< T >.IsLoaded, Terraria.NPC.IsMechQueenUp, Microsoft.Xna.Framework.Vector2.Length(), Microsoft.Xna.Framework.Vector3.Length(), Microsoft.Xna.Framework.Color.Lerp(), Microsoft.Xna.Framework.MathHelper.Lerp(), Microsoft.Xna.Framework.Vector2.Lerp(), Terraria.NPC.life, Terraria.NPC.lifeMax, Terraria.GameContent.TextureAssets.Lightningbug, Microsoft.Xna.Framework.Color.LimeGreen, Terraria.NPC.localAI, System.Math.Max(), Microsoft.Xna.Framework.MathHelper.Max(), Terraria.Main.maxNPCs, System.Reflection.MaxValue, System.Math.Min(), Terraria.Graphics.Shaders.GameShaders.Misc, Terraria.Main.mouseTextColor, Terraria.Main.myPlayer, Terraria.NPC.nameOver, Terraria.Dust.NewDust(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.GameContent.TextureAssets.Ninja, Terraria.Dust.noGravity, Microsoft.Xna.Framework.Graphics.DepthStencilState.None, Terraria.GameContent.TextureAssets.Npc, Terraria.Main.npc, Terraria.Main.NPCAddHeight(), Terraria.Main.npcFrameCount, Terraria.Main.OffsetsPlayerHeadgear, Terraria.NPC.oldPos, Terraria.NPC.oldRot, Terraria.NPC.Opacity, Microsoft.Xna.Framework.Color.Orange, Microsoft.Xna.Framework.Color.OrangeRed, Microsoft.Xna.Framework.Graphics.EffectTechnique.Passes, Microsoft.Xna.Framework.Color.Pink, Terraria.Main.pixelShader, Terraria.Main.player, Microsoft.Xna.Framework.Graphics.SamplerState.PointClamp, Microsoft.Xna.Framework.Graphics.SamplerState.PointWrap, Terraria.DataStructures.DrawData.position, Terraria.Entity.position, System.Math.Pow(), Terraria.GameContent.TextureAssets.Probe, Terraria.GameContent.TextureAssets.Projectile, Terraria.GameContent.TextureAssets.PumpkingArm, Terraria.GameContent.TextureAssets.PumpkingCloak, Terraria.GameContent.TextureAssets.PumpkingFace, Microsoft.Xna.Framework.Color.R, Terraria.Main.rand, Terraria.Utils.RandomInt(), Terraria.Main.Rasterizer, Microsoft.Xna.Framework.Graphics.GraphicsDevice.RasterizerState, Terraria.NPC.realLife, Terraria.GameContent.TextureAssets.ReaperEye, Microsoft.Xna.Framework.Color.Red, Terraria.Utils.Remap(), Terraria.NPC.rotation, Terraria.GameContent.TextureAssets.SantaTank, Terraria.NPC.scale, Terraria.Graphics.Effects.Filters.Scene, Microsoft.Xna.Framework.Graphics.GraphicsDevice.ScissorRectangle, Terraria.Main.ScissorState, Terraria.Main.screenPosition, Terraria.NPC.SetFrameSize(), Terraria.NPC.ShieldStrengthTowerMax, Terraria.NPC.ShieldStrengthTowerNebula, Terraria.NPC.ShieldStrengthTowerSolar, Terraria.NPC.ShieldStrengthTowerStardust, Terraria.NPC.ShieldStrengthTowerVortex, Terraria.NPC.shimmerTransparency, System.Math.Sin(), Terraria.Entity.Size, Terraria.ID.NPCID.Sets.SlimeCanContainItems, Terraria.GameContent.TextureAssets.SpikeBase, Terraria.Main.spriteBatch, Terraria.NPC.spriteDirection, System.Math.Sqrt(), Terraria.NPC.target, System.text, Terraria.GameContent.TextureAssets.Tile, Terraria.Main.tileColor, Terraria.Main.TileFrameSeed, Terraria.Main.timeForVisualEffects, Terraria.Entity.Top, Microsoft.Xna.Framework.Color.ToVector3(), Terraria.NPC.townNpcVariationIndex, Terraria.Main.Transform, Microsoft.Xna.Framework.Color.Transparent, Terraria.GameContent.TextureAssets.TreeFace, Microsoft.Xna.Framework.Color.Turquoise, Terraria.NPC.type, Terraria.Main.UIScaleMatrix, Microsoft.Xna.Framework.Vector2.UnitX, Microsoft.Xna.Framework.Vector2.UnitY, System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Utils.Vector2FromElipse(), Microsoft.Xna.Framework.Graphics.Vector3, Terraria.Entity.velocity, Terraria.Entity.wet, Microsoft.Xna.Framework.Color.White, Terraria.Entity.whoAmI, Microsoft.Xna.Framework.Graphics.Texture2D.Width, Microsoft.Xna.Framework.Rectangle.Width, Terraria.Entity.width, Terraria.GameContent.TextureAssets.WraithEye, Microsoft.Xna.Framework.MathHelper.WrapAngle(), Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Point.Y, Microsoft.Xna.Framework.Rectangle.Y, Microsoft.Xna.Framework.Vector2.Y, Microsoft.Xna.Framework.Color.Yellow, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.LeashedEntities.LeashedCritter.Draw(), Terraria.GameContent.Bestiary.UnlockableNPCEntryIcon.Draw(), Terraria.GameContent.Animations.Segments.NPCSegment.Draw(), and Terraria.Main.DrawNPCPortrait().