Terraria Decompiled: Terraria.Main.StopSlimeRain
StopSlimeRain()
static void Terraria.Main.StopSlimeRain (bool announce = true) inline static
Definition at line 66113 of file Main.cs.
        {
            if (!Main.slimeRain)
            {
                return;
            }
            if (Main.netMode == 1)
            {
                Main.slimeRainTime = 0.0;
                Main.slimeRain = false;
                SkyManager.Instance.Deactivate("Slime", new object[0]);
                return;
            }
            int num = 86400 * 7;
            if (Main.hardMode)
            {
                num *= 2;
            }
            Main.slimeRainTime = (double)(-(double)Main.rand.Next(3024, 6048) * 100);
            Main.slimeRain = false;
            if (Main.netMode == 0)
            {
                if (announce)
                {
                    Main.slimeWarningTime = Main.slimeWarningDelay;
                }
                SkyManager.Instance.Deactivate("Slime", new object[0]);
                return;
            }
            if (announce)
            {
                Main.slimeWarningTime = Main.slimeWarningDelay;
                NetMessage.SendData(7, -1, -1, null, 0, 0f, 0f, 0f, 0, 0, 0);
            }
        }
References Terraria.Graphics.Effects.EffectManager< T >.Deactivate(), Terraria.Main.hardMode, Terraria.Graphics.Effects.SkyManager.Instance, Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, Terraria.NetMessage.SendData(), Terraria.Main.slimeRain, and Terraria.Main.slimeWarningDelay.
Referenced by Terraria.NPC.DoDeathEvents(), Terraria.Main.DrawMenu(), Terraria.MessageBuffer.GetData(), and Terraria.Main.UpdateTime().