Terraria Decompiled: Terraria.Main.TeleportEffect
TeleportEffect()
static void Terraria.Main.TeleportEffect (Microsoft::Xna::Framework::Rectangle effectRect, int Style, int extraInfo = 0, float dustCountMult = 1f, TeleportationSide side = TeleportationSide::Entry, Vector2 otherPosition = default(Vector2)) inline static
Definition at line 11754 of file Main.cs.
        {
            if (Style == 0)
            {
                SoundEngine.PlaySound(SoundID.Item6, effectRect.X + effectRect.Width / 2, effectRect.Y + effectRect.Height / 2, 0f, 1f);
                int num = effectRect.Width * effectRect.Height / 5;
                num = (int)((float)num * dustCountMult);
                for (int i = 0; i < num; i++)
                {
                    int num2 = Dust.NewDust(new Vector2((float)effectRect.X, (float)effectRect.Y), effectRect.Width, effectRect.Height, 159, 0f, 0f, 0, default(Microsoft.Xna.Framework.Color), 1f);
                    Main.dust[num2].scale = (float)Main.rand.Next(20, 70) * 0.01f;
                    if (i < 10)
                    {
                        Main.dust[num2].scale += 0.25f;
                    }
                    if (i < 5)
                    {
                        Main.dust[num2].scale += 0.25f;
                    }
                }
                return;
            }
            if (Style == 1)
            {
                SoundEngine.PlaySound(SoundID.Item8, effectRect.X + effectRect.Width / 2, effectRect.Y + effectRect.Height / 2, 0f, 1f);
                int num3 = effectRect.Width * effectRect.Height / 5;
                num3 = (int)((float)num3 * dustCountMult);
                for (int j = 0; j < num3; j++)
                {
                    int num4 = Dust.NewDust(new Vector2((float)effectRect.X, (float)effectRect.Y), effectRect.Width, effectRect.Height, 164, 0f, 0f, 0, default(Microsoft.Xna.Framework.Color), 1f);
                    Main.dust[num4].scale = (float)Main.rand.Next(20, 70) * 0.01f;
                    if (j < 10)
                    {
                        Main.dust[num4].scale += 0.25f;
                    }
                    if (j < 5)
                    {
                        Main.dust[num4].scale += 0.25f;
                    }
                }
                return;
            }
            if (Style == 2)
            {
                int num5 = (int)(50f * dustCountMult);
                for (int k = 0; k < num5; k++)
                {
                    Main.dust[Dust.NewDust(new Vector2((float)effectRect.X, (float)effectRect.Y), effectRect.Width, effectRect.Height, 58, 0f, 0f, 150, Microsoft.Xna.Framework.Color.GhostWhite, 1.2f)].velocity *= 0.5f;
                }
                return;
            }
            if (Style == 3)
            {
                SoundEngine.PlaySound(SoundID.Item6, effectRect.X + effectRect.Width / 2, effectRect.Y + effectRect.Height / 2, 0f, 1f);
                int num6 = (int)(50f * dustCountMult);
                for (int l = 0; l < num6; l++)
                {
                    int num7 = Dust.NewDust(new Vector2((float)effectRect.X, (float)effectRect.Y), effectRect.Width, effectRect.Height, 180, 0f, 0f, 0, default(Microsoft.Xna.Framework.Color), 1f);
                    Main.dust[num7].noGravity = true;
                    for (int m = 0; m < 5; m++)
                    {
                        if (Main.rand.Next(3) == 0)
{
                            Main.dust[num7].velocity *= 0.75f;
                        }
                    }
                    if (Main.rand.Next(3) == 0)
                    {
                        Main.dust[num7].velocity *= 2f;
                        Main.dust[num7].scale *= 1.2f;
                    }
                    if (Main.rand.Next(3) == 0)
                    {
                        Main.dust[num7].velocity *= 2f;
                        Main.dust[num7].scale *= 1.2f;
                    }
                    if (Main.rand.Next(2) == 0)
                    {
                        Main.dust[num7].fadeIn = (float)Main.rand.Next(75, 100) * 0.01f;
                        Main.dust[num7].scale = (float)Main.rand.Next(25, 75) * 0.01f;
                    }
                    Main.dust[num7].scale *= 0.8f;
                }
                return;
            }
            if (Style == 4)
            {
                SoundEngine.PlaySound(SoundID.Item8, effectRect.X + effectRect.Width / 2, effectRect.Y + effectRect.Height / 2, 0f, 1f);
                int num8 = effectRect.Width * effectRect.Height / 5;
                num8 = (int)((float)num8 * dustCountMult);
                for (int n = 0; n < num8; n++)
                {
                    Dust dust = Main.dust[Dust.NewDust(effectRect.TopLeft(), effectRect.Width, effectRect.Height, 263, 0f, 0f, 0, default(Microsoft.Xna.Framework.Color), 1f)];
                    dust.color = PortalHelper.GetPortalColor(extraInfo);
                    dust.noLight = true;
                    dust.noGravity = true;
                    dust.scale = 1.2f;
                    dust.fadeIn = 0.4f;
                    dust.color.A = byte.MaxValue;
                }
                return;
            }
            if (Style == 5)
            {
                Vector2 vector = effectRect.TopLeft();
                int num9 = (int)(100f * dustCountMult);
                for (int num10 = 0; num10 < num9; num10++)
                {
                    Dust dust2 = Dust.NewDustDirect(vector, effectRect.Width, effectRect.Height + 24, Dust.dustWater(), 0f, 0f, 0, default(Microsoft.Xna.Framework.Color), 1f);
                    dust2.velocity.Y = dust2.velocity.Y * 0f;
                    dust2.velocity.Y = dust2.velocity.Y - 3.5f;
                    dust2.velocity.X = dust2.velocity.X * 1.5f;
                    dust2.scale = 0.8f;
                    dust2.alpha = 130;
                    dust2.noGravity = true;
                    dust2.fadeIn = 1.2f;
                }
                SoundEngine.PlaySound(19, effectRect.Center.ToVector2(), 0, 0f);
                return;
            }
            if (Style == 7)
            {
                Vector2 vector2 = effectRect.TopLeft();
                int num11 = (int)(50f * dustCountMult);
                for (int num12 = 0; num12 < num11; num12++)
                {
                    Dust dust3 = Dust.NewDustDirect(vector2, effectRect.Width, effectRect.Height + 24, 35, 0f, 0f, 0, default(Microsoft.Xna.Framework.Color), 1f);
                    dust3.velocity.Y = dust3.velocity.Y * 0f;
                    dust3.velocity.Y = dust3.velocity.Y - 3.5f;
                    dust3.velocity.X = dust3.velocity.X * 1.5f;
                    dust3.scale = 0.8f;
                    dust3.alpha = 130;
                    dust3.noGravity = true;
                    dust3.fadeIn = 1.2f;
                }
                SoundEngine.PlaySound(SoundID.Item8, effectRect.Center.ToVector2(), 0f, 1f);
                return;
            }
            if (Style == 9)
            {
                effectRect.Inflate(15, 15);
                int num13 = (int)(100f * dustCountMult);
                for (int num14 = 0; num14 < num13; num14++)
                {
                    TeleportPylonsSystem.SpawnInWorldDust(extraInfo, effectRect);
                }
                SoundEngine.PlaySound(SoundID.Item6, effectRect.Center.X, effectRect.Center.Y, 0f, 1f);
                return;
            }
            if (Style == 10)
            {
                effectRect.Inflate(15, 15);
                int num15 = (int)(60f * dustCountMult);
                Vector2 vector3 = otherPosition - effectRect.TopLeft();
                for (int num16 = 0; num16 < num15; num16++)
                {
                    float num17 = 0.4f + Main.rand.NextFloat();
                    float num18 = 0.4f + Main.rand.NextFloat();
                    Microsoft.Xna.Framework.Color color = Main.hslToRgb(0.66f + Main.rand.NextFloat() * 0.24f, 1f, 0.5f, byte.MaxValue);
                    Dust dust4 = Dust.NewDustDirect(effectRect.TopLeft(), effectRect.Width, effectRect.Height, 267, 0f, 0f, 127, color, 1f);
                    dust4.scale = (float)Main.rand.Next(20, 70) * 0.01f;
                    if (num16 < 10)
                    {
                        dust4.scale += 0.25f;
                    }
                    if (num16 < 5)
                    {
                        dust4.scale += 0.25f;
                    }
                    if ((float)num16 < (float)num15 * 0.8f)
                    {
                        dust4.velocity += vector3 * 0.1f * Main.rand.NextFloat();
                    }
                    dust4.noGravity = true;
                    dust4.noLight = true;
                    dust4.scale = num18;
                    dust4.fadeIn = num17;
                    if (dust4.dustIndex != 6000)
                    {
                        Dust dust5 = Dust.CloneDust(dust4);
                        dust5.scale *= 0.65f;
                        dust5.fadeIn *= 0.65f;
                        dust5.color = new Microsoft.Xna.Framework.Color(255, 255, 255, 255);
                    }
                }
                SoundEngine.PlaySound(SoundID.Item8, effectRect.Center.X, effectRect.Center.Y, 0f, 1f);
                return;
            }
            if (Style == 11)
            {
                for (int num19 = 0; num19 < 50; num19++)
                {
                    int num20 = Main.rand.Next(4);
                    Microsoft.Xna.Framework.Color color2 = Microsoft.Xna.Framework.Color.Green;
                    switch (num20)
                    {
                    case 0:
                    case 1:
                        color2 = new Microsoft.Xna.Framework.Color(100, 255, 100);
                        break;
                    case 2:
                        color2 = Microsoft.Xna.Framework.Color.Yellow;
                        break;
                    case 3:
                        color2 = Microsoft.Xna.Framework.Color.White;
                        break;
                    }
                    Dust dust6 = Dust.NewDustPerfect(Main.rand.NextVector2FromRectangle(effectRect), 267, null, 0, default(Microsoft.Xna.Framework.Color), 1f);
                    dust6.noGravity = true;
                    dust6.color = color2;
                    dust6.velocity *= 2f;
                    dust6.scale = 0.8f + Main.rand.NextFloat() * 0.6f;
                    dust6.fadeIn = 0.5f;
                }
                return;
            }
            if (Style == 13)
            {
                SoundEngine.PlaySound(SoundID.Item8, effectRect.Center.ToVector2(), 0f, 1f);
                for (int num21 = 0; num21 < 21; num21++)
                {
                    int num22 = Dust.NewDust(Main.rand.NextVector2FromRectangle(effectRect), 2, 2, 27, 0f, 0f, 100, default(Microsoft.Xna.Framework.Color), (float)Main.rand.Next(1, 3));
                    Main.dust[num22].velocity *= 1.75f;
                    if (num21 % 3 == 0)
                    {
                        Main.dust[num22].velocity *= 1.5f;
                    }
                    Main.dust[num22].noLightEmittance = true;
                    Main.dust[num22].noGravity = true;
                }
            }
        }
References Terraria.Dust.CloneDust(), Terraria.Main.dust, Terraria.Dust.dustIndex, Terraria.Dust.dustWater(), Terraria.Dust.fadeIn, Terraria.GameContent.PortalHelper.GetPortalColor(), Microsoft.Xna.Framework.Color.GhostWhite, Microsoft.Xna.Framework.Color.Green, Terraria.Main.hslToRgb(), int, Terraria.ID.SoundID.Item6, Terraria.ID.SoundID.Item8, Terraria.Dust.NewDust(), Terraria.Dust.NewDustDirect(), Terraria.Dust.NewDustPerfect(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Terraria.Dust.noLightEmittance, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.rand, Terraria.Dust.scale, Terraria.GameContent.TeleportPylonsSystem.SpawnInWorldDust(), Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Dust.velocity, Microsoft.Xna.Framework.Color.White, and Microsoft.Xna.Framework.Color.Yellow.
Referenced by Terraria.NPC.Teleport(), and Terraria.Player.Teleport().