Terraria Decompiled: Terraria.Main.MouseText_DrawBuffTooltip
MouseText_DrawBuffTooltip()
void Terraria.Main.MouseText_DrawBuffTooltip (string buffString, ref int X, ref int Y, Vector2 mouseTextSize) inline private
Definition at line 20184 of file Main.cs.
        {
            Microsoft.Xna.Framework.Point point = new Microsoft.Xna.Framework.Point(X, Y);
            int num = 220;
            int num2 = 72;
            int num3 = -1;
            float num4 = 1f;
            List<Vector2> list = new List<Vector2>();
            Vector2 vector = FontAssets.MouseText.Value.MeasureString(buffString);
            list.Add(vector);
            list.Add(mouseTextSize);
            int num5 = (int)((float)(Main.screenHeight - Y - 24 - num2) * num4) / 20;
            if (num5 < 1)
            {
                num5 = 1;
            }
            if (Main.bannerMouseOver)
            {
                int num6 = 0;
                for (int i = 0; i < BannerSystem.MaxBannerTypes; i++)
                {
                    if (BannerSystem.BannerToNPC(i) != 0 && Main.player[Main.myPlayer].HasNPCBannerBuff(i))
                    {
                        num6++;
                        string npcnameValue = Lang.GetNPCNameValue(BannerSystem.BannerToNPC(i));
                        Vector2 vector2 = FontAssets.MouseText.Value.MeasureString(npcnameValue);
                        int num7 = X;
                        int num8 = Y + (int)vector2.Y + num6 * 20 + 10;
                        int num9 = 0;
                        int num10 = num6 / num5;
                        for (int j = 0; j < num10; j++)
{
                            num9++;
                            num7 += num;
                            num8 -= num5 * 20;
                        }
                        if ((float)(num7 - 24 - num) > (float)Main.screenWidth * num4)
{
                            num3 = num6;
                            break;
                        }
                        list.Add(new Vector2((float)num7, (float)num8) + vector2 - point.ToVector2());
                    }
                }
            }
            Vector2 zero = Vector2.Zero;
            foreach (Vector2 vector3 in list)
            {
                if (zero.X < vector3.X)
                {
                    zero.X = vector3.X;
                }
                if (zero.Y < vector3.Y)
                {
                    zero.Y = vector3.Y;
                }
            }
            if ((float)X + zero.X + 24f > (float)Main.screenWidth * num4)
            {
                X = (int)((float)Main.screenWidth * num4 - zero.X - 24f);
            }
            if ((float)Y + zero.Y + 4f > (float)Main.screenHeight * num4)
            {
                Y = (int)((float)Main.screenHeight * num4 - zero.Y - 4f);
            }
            for (int k = 0; k < 5; k++)
            {
                int num11 = X;
                int num12 = Y + (int)mouseTextSize.Y;
                Microsoft.Xna.Framework.Color black = Microsoft.Xna.Framework.Color.Black;
                if (k == 0)
                {
                    num11 -= 2;
                }
                else if (k == 1)
                {
                    num11 += 2;
                }
                else if (k == 2)
                {
                    num12 -= 2;
                }
                else if (k == 3)
                {
                    num12 += 2;
                }
                else
                {
                    black = new Microsoft.Xna.Framework.Color((int)Main.mouseTextColor, (int)Main.mouseTextColor, (int)Main.mouseTextColor, (int)Main.mouseTextColor);
                }
                DynamicSpriteFontExtensionMethods.DrawString(Main.spriteBatch, FontAssets.MouseText.Value, buffString, new Vector2((float)num11, (float)num12), black, 0f, default(Vector2), 1f, SpriteEffects.None, 0f, null, null);
            }
            if (Main.bannerMouseOver)
            {
                int num13 = 0;
                for (int l = 0; l < BannerSystem.MaxBannerTypes; l++)
                {
                    if (BannerSystem.BannerToNPC(l) != 0 && Main.player[Main.myPlayer].HasNPCBannerBuff(l))
                    {
                        num13++;
                        bool flag = false;
                        for (int m = 0; m < 5; m++)
{
                            int num14 = X;
                            int num15 = Y + (int)mouseTextSize.Y + num13 * 20 + 10;
                            int num16 = (num13 - 1) / num5;
                            num14 += num * num16;
                            num15 -= num5 * 20 * num16;
                            string text = Lang.GetNPCNameValue(BannerSystem.BannerToNPC(l));
                            if (num3 == num13)
{
                                text = Language.GetTextValue("UI.Ellipsis");
                                flag = true;
                            }
                            Microsoft.Xna.Framework.Color black2 = Microsoft.Xna.Framework.Color.Black;
                            if (m == 0)
{
                                num14 -= 2;
                            }
                            else if (m == 1)
{
                                num14 += 2;
                            }
                            else if (m == 2)
{
                                num15 -= 2;
                            }
                            else if (m == 3)
{
                                num15 += 2;
                            }
                            else
{
                                float num17 = (float)Main.mouseTextColor / 255f;
                                black2 = new Microsoft.Xna.Framework.Color((int)((byte)(80f * num17)), (int)((byte)(255f * num17)), (int)((byte)(120f * num17)), (int)Main.mouseTextColor);
                            }
                            DynamicSpriteFontExtensionMethods.DrawString(Main.spriteBatch, FontAssets.MouseText.Value, text, new Vector2((float)num14, (float)num15), black2, 0f, default(Vector2), 1f, SpriteEffects.None, 0f, null, null);
                        }
                        if (flag)
{
                            break;
                        }
                    }
                }
            }
        }
References Terraria.Main.bannerMouseOver, Terraria.GameContent.BannerSystem.BannerToNPC(), Microsoft.Xna.Framework.Color.Black, ReLogic.Graphics.DynamicSpriteFontExtensionMethods.DrawString(), Terraria.Lang.GetNPCNameValue(), Terraria.Localization.Language.GetTextValue(), Terraria.Player.HasNPCBannerBuff(), int, System.list, Terraria.GameContent.BannerSystem.MaxBannerTypes, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.mouseTextColor, Terraria.Main.myPlayer, Terraria.Main.player, Terraria.Main.screenHeight, Terraria.Main.screenWidth, Terraria.Main.spriteBatch, System.text, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Input.X, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Input.Y, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.