Terraria Decompiled: Terraria.Main.UpdateCameraPan
UpdateCameraPan()
static void Terraria.Main.UpdateCameraPan () inline static private
Definition at line 63711 of file Main.cs.
        {
            Main.LocalPlayer.netCameraTarget = null;
            Main.disableDontStarveDarknessDamage = false;
            if (float.IsNaN(Main.CurrentPan.X))
            {
                Main.CurrentPan.X = 0f;
            }
            if (float.IsNaN(Main.CurrentPan.Y))
            {
                Main.CurrentPan.Y = 0f;
            }
            Vector2 vector = Vector2.Zero;
            float num = 36f;
            Vector2 vector2;
            float num2;
            float num3;
            if (Main.GetObjectTrackingCameraPan(out vector2, out num2, out num3))
            {
                Main.LocalPlayer.netCameraTarget = new Vector2?(vector2);
                vector = vector2 - Main.LocalPlayer.Center;
                float num4 = Vector2.Distance(Main.CurrentPan, vector);
                num2 *= 1f + Utils.Clamp<float>(num4 / num3, 0f, 1f);
                num = num4 * num2;
                Main.disableDontStarveDarknessDamage = true;
                Main.CurrentPan -= Main.LocalPlayer.velocity;
            }
            else if (Main.GetPlayerControlledCameraPan(ref vector, ref num))
            {
                Main.disableDontStarveDarknessDamage = true;
            }
            if (Vector2.Distance(Main.CurrentPan, vector) >= Main.BlackFadeDist)
            {
                Main.CurrentPan = vector;
                Main.BlackFadeCameraTeleport();
            }
            else
            {
                Main.CurrentPan = Main.CurrentPan.MoveTowards(vector, num);
            }
            if (Main.LocalPlayer.netCameraTarget != null != (Main.LocalPlayer.lastSyncedNetCameraTarget != null) || (Main.LocalPlayer.netCameraTarget != null && Vector2.Distance(Main.LocalPlayer.lastSyncedNetCameraTarget.Value, Main.LocalPlayer.netCameraTarget.Value) > 160f))
            {
                NetMessage.SendData(13, -1, -1, null, Main.myPlayer, 0f, 0f, 0f, 0, 0, 0);
            }
        }
References Terraria.Main.BlackFadeCameraTeleport(), Terraria.Main.BlackFadeDist, Terraria.Entity.Center, Terraria.Utils.Clamp(), Terraria.Main.CurrentPan, Microsoft.Xna.Framework.Vector2.Distance(), Terraria.Main.GetObjectTrackingCameraPan(), Terraria.Main.GetPlayerControlledCameraPan(), Terraria.Player.lastSyncedNetCameraTarget, Terraria.Main.LocalPlayer, Terraria.Main.myPlayer, Terraria.Player.netCameraTarget, Terraria.NetMessage.SendData(), Terraria.Entity.velocity, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.Main.DoUpdateInWorld().