Terraria Decompiled: Terraria.Main.ClientInitialize
ClientInitialize()
void Terraria.Main.ClientInitialize () inline private
Definition at line 8715 of file Main.cs.
        {
            MessageBuffer.OnTileChangeReceived += this.OnTileChangeEvent;
            LanguageManager.Instance.OnLanguageChanged += delegate(LanguageManager languageManager)
            {
                ItemTooltip.InvalidateTooltips();
            };
            PlayerInput.OnBindingChange += ItemTooltip.InvalidateTooltips;
            Main.clientUUID = Guid.NewGuid().ToString();
            FilterManager scene = Terraria.Graphics.Effects.Filters.Scene;
            Platform.Current.InitializeClientServices(base.Window.Handle);
            Platform.Get<IImeService>().AddKeyListener(delegate(char keyStroke)
            {
                if (Main.keyCount < Main.keyInt.Length)
                {
                    Main.keyInt[Main.keyCount] = (int)keyStroke;
                    Main.keyString[Main.keyCount] = keyStroke.ToString() ?? "";
                    Main.keyCount++;
                }
            });
            base.Window.AllowUserResizing = true;
            this.LoadSettings();
            Main.PreventUpdatingTargets = false;
            Main.SetDisplayMonitor();
            PlayerInput.CacheOriginalScreenDimensions();
            if (Main.screenWidth > GraphicsAdapter.DefaultAdapter.CurrentDisplayMode.Width)
            {
                Main.screenWidth = GraphicsAdapter.DefaultAdapter.CurrentDisplayMode.Width;
            }
            if (Main.screenHeight > GraphicsAdapter.DefaultAdapter.CurrentDisplayMode.Height)
            {
                Main.screenHeight = GraphicsAdapter.DefaultAdapter.CurrentDisplayMode.Height;
            }
            this.UpdateDisplaySettings();
            Main.graphics.ApplyChanges();
            if (Main.OnResolutionChanged != null)
            {
                Main.OnResolutionChanged(new Vector2((float)Main.screenWidth, (float)Main.screenHeight));
            }
            this.CheckBunny();
            base.GraphicsDevice.DeviceLost += this.GraphicsDeviceLost;
            base.GraphicsDevice.DeviceReset += this.GraphicsDeviceLost;
            base.GraphicsDevice.DeviceResetting += this.GraphicsDeviceLost;
            if (Main._needsLanguageSelect)
            {
                Main.menuMode = 1212;
            }
            this._achievements = new AchievementManager();
            this._achievementAdvisor = new AchievementAdvisor();
            this.OpenRecent();
            UILinksInitializer.Load();
            Main.Chroma = new ChromaEngine();
            Main.ChromaPainter = new ChromaHotkeyPainter();
            Main.ChromaPainter.CollectBoundKeys();
            Main.CacheSupportedDisplaySizes();
            if (Main.autoJoin)
            {
                Main.menuMode = 1;
                Main.menuMultiplayer = true;
            }
            Main.fpsTimer.Start();
        }
References Terraria.Main._needsLanguageSelect, Microsoft.Xna.Framework.GraphicsDeviceManager.ApplyChanges(), Terraria.Main.autoJoin, Terraria.GameInput.PlayerInput.CacheOriginalScreenDimensions(), Terraria.Main.CacheSupportedDisplaySizes(), Terraria.Main.ChromaPainter, Terraria.GameContent.ChromaHotkeyPainter.CollectBoundKeys(), ReLogic.OS.Platform.Current, Microsoft.Xna.Framework.Graphics.GraphicsAdapter.CurrentDisplayMode, Microsoft.Xna.Framework.Graphics.GraphicsAdapter.DefaultAdapter, Terraria.Main.fpsTimer, Terraria.Main.graphics, Microsoft.Xna.Framework.Graphics.DisplayMode.Height, ReLogic.OS.Platform.InitializeClientServices(), int, Terraria.UI.ItemTooltip.InvalidateTooltips(), Terraria.Main.keyCount, Terraria.Main.keyInt, Terraria.Main.keyString, Terraria.Initializers.UILinksInitializer.Load(), System.Guid.NewGuid(), Terraria.Main.OnResolutionChanged, Terraria.Graphics.Effects.Filters.Scene, Terraria.Main.screenHeight, Terraria.Main.screenWidth, Terraria.Main.SetDisplayMonitor(), System.Guid.ToString(), Microsoft.Xna.Framework.Graphics.Vector2, and Microsoft.Xna.Framework.Graphics.DisplayMode.Width.