Terraria Decompiled: Terraria.Main.DrawProjWithStarryTrail
DrawProjWithStarryTrail()
void Terraria.Main.DrawProjWithStarryTrail (Projectile proj, Player theOwner, Microsoft::Xna::Framework::Color projectileColor, SpriteEffects dir) inline private
Definition at line 37067 of file Main.cs.
        {
            Microsoft.Xna.Framework.Color color = new Microsoft.Xna.Framework.Color(255, 255, 255, (int)projectileColor.A - proj.alpha);
            Vector2 vector = proj.velocity;
            Microsoft.Xna.Framework.Color color2 = Microsoft.Xna.Framework.Color.Blue * 0.1f;
            Vector2 vector2 = new Vector2(0f, -4f);
            float num = 0f;
            float num2 = vector.Length();
            float num3 = Utils.GetLerpValue(3f, 5f, num2, true);
            bool flag = true;
            if (proj.type == 1049)
            {
                flag = false;
            }
            if (proj.type == 856 || proj.type == 857)
            {
                vector = proj.position - proj.oldPos[1];
                float num4 = vector.Length();
                if (num4 == 0f)
                {
                    vector = Vector2.UnitY;
                }
                else
                {
                    vector *= 5f / num4;
                }
                Vector2 vector3 = new Vector2(proj.ai[0], proj.ai[1]);
                Vector2 center = theOwner.Center;
                float num5 = Utils.GetLerpValue(0f, 120f, vector3.Distance(center), true);
                float num6 = 90f;
                if (proj.type == 857)
                {
                    num6 = 60f;
                    flag = false;
                }
                float num7 = Utils.GetLerpValue(num6, num6 * 0.8333333f, proj.localAI[0], true);
                float lerpValue = Utils.GetLerpValue(0f, 120f, proj.Center.Distance(center), true);
                num5 *= lerpValue;
                num7 *= Utils.GetLerpValue(0f, 15f, proj.localAI[0], true);
                color2 = Microsoft.Xna.Framework.Color.HotPink * 0.15f * (num7 * num5);
                if (proj.type == 857)
                {
                    color2 = proj.GetFirstFractalColor() * 0.15f * (num7 * num5);
                }
                vector2 = new Vector2(0f, -2f);
                float num8 = Utils.GetLerpValue(num6, num6 * 0.6666667f, proj.localAI[0], true);
                num8 *= Utils.GetLerpValue(0f, 20f, proj.localAI[0], true);
                num = -0.3f * (1f - num8);
                num += -1f * Utils.GetLerpValue(15f, 0f, proj.localAI[0], true);
                num *= num5;
                num3 = num7 * num5;
            }
            if (proj.type == 1049)
            {
                color2 = new Microsoft.Xna.Framework.Color(250, 150, 100) * 0.1f;
            }
            Vector2 vector4 = proj.Center + vector;
            Texture2D value = TextureAssets.Projectile[proj.type].Value;
            new Microsoft.Xna.Framework.Rectangle(0, 0, value.Width, value.Height).Size() / 2f;
            Texture2D value2 = TextureAssets.Extra[91].Value;
            Microsoft.Xna.Framework.Rectangle rectangle = value2.Frame(1, 1, 0, 0, 0, 0);
            Vector2 vector5 = new Vector2((float)rectangle.Width / 2f, 10f);
            Microsoft.Xna.Framework.Color.Cyan * 0.5f * num3;
            Vector2 vector6 = new Vector2(0f, proj.gfxOffY);
            float num9 = (float)Main.timeForVisualEffects / 60f;
            Vector2 vector7 = vector4 + vector * 0.5f;
            Microsoft.Xna.Framework.Color color3 = Microsoft.Xna.Framework.Color.White * 0.5f * num3;
            color3.A = 0;
            Microsoft.Xna.Framework.Color color4 = color2 * num3;
            color4.A = 0;
            Microsoft.Xna.Framework.Color color5 = color2 * num3;
            color5.A = 0;
            Microsoft.Xna.Framework.Color color6 = color2 * num3;
            color6.A = 0;
            float num10 = vector.ToRotation();
            Main.EntitySpriteDraw(value2, vector7 - Main.screenPosition + vector6 + vector2.RotatedBy((double)(6.2831855f * num9), default(Vector2)), new Microsoft.Xna.Framework.Rectangle?(rectangle), color4, num10 + 1.5707964f, vector5, 1.5f + num, SpriteEffects.None, 0f);
            Main.EntitySpriteDraw(value2, vector7 - Main.screenPosition + vector6 + vector2.RotatedBy((double)(6.2831855f * num9 + 2.0943952f), default(Vector2)), new Microsoft.Xna.Framework.Rectangle?(rectangle), color5, num10 + 1.5707964f, vector5, 1.1f + num, SpriteEffects.None, 0f);
            Main.EntitySpriteDraw(value2, vector7 - Main.screenPosition + vector6 + vector2.RotatedBy((double)(6.2831855f * num9 + 4.1887903f), default(Vector2)), new Microsoft.Xna.Framework.Rectangle?(rectangle), color6, num10 + 1.5707964f, vector5, 1.3f + num, SpriteEffects.None, 0f);
            Vector2 vector8 = vector4 - vector * 0.5f;
            for (float num11 = 0f; num11 < 1f; num11 += 0.5f)
            {
                float num12 = num9 % 0.5f / 0.5f;
                num12 = (num12 + num11) % 1f;
                float num13 = num12 * 2f;
                if (num13 > 1f)
                {
                    num13 = 2f - num13;
                }
                Main.EntitySpriteDraw(value2, vector8 - Main.screenPosition + vector6, new Microsoft.Xna.Framework.Rectangle?(rectangle), color3 * num13, num10 + 1.5707964f, vector5, 0.3f + num12 * 0.5f, SpriteEffects.None, 0f);
            }
            if (flag)
            {
                float num14 = proj.rotation + proj.localAI[1];
                float num15 = (float)Main.timeForVisualEffects / 240f;
                float globalTimeWrappedHourly = Main.GlobalTimeWrappedHourly;
                float num16 = Main.GlobalTimeWrappedHourly;
                num16 %= 5f;
                num16 /= 2.5f;
                if (num16 >= 1f)
                {
                    num16 = 2f - num16;
                }
                num16 = num16 * 0.5f + 0.5f;
                Vector2 vector9 = proj.Center - Main.screenPosition;
                Main.instance.LoadItem(75);
                Texture2D value3 = TextureAssets.Item[75].Value;
                Microsoft.Xna.Framework.Rectangle rectangle2 = value3.Frame(1, 8, 0, 0, 0, 0);
                Vector2 vector10 = rectangle2.Size() / 2f;
                Main.EntitySpriteDraw(value3, vector9, new Microsoft.Xna.Framework.Rectangle?(rectangle2), color, num14, vector10, proj.scale, SpriteEffects.None, 0f);
            }
        }
References Terraria.Projectile.ai, Terraria.Projectile.alpha, Terraria.Entity.Center, Microsoft.Xna.Framework.Vector2.Distance(), Terraria.Main.EntitySpriteDraw(), Terraria.GameContent.TextureAssets.Extra, Terraria.Projectile.GetFirstFractalColor(), Terraria.Utils.GetLerpValue(), Terraria.Projectile.gfxOffY, Terraria.Main.GlobalTimeWrappedHourly, Terraria.Main.instance, Terraria.GameContent.TextureAssets.Item, Microsoft.Xna.Framework.Vector2.Length(), Terraria.Main.LoadItem(), Terraria.Projectile.localAI, Terraria.Projectile.oldPos, Terraria.GameContent.TextureAssets.Projectile, Terraria.Projectile.scale, Terraria.Main.screenPosition, Terraria.Main.timeForVisualEffects, Terraria.Projectile.type, Microsoft.Xna.Framework.Vector2.UnitY, System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Entity.velocity, and Microsoft.Xna.Framework.Rectangle.Width.