Terraria Decompiled: Terraria.Main.DrawSurfaceBG_Mushroom
DrawSurfaceBG_Mushroom()
void Terraria.Main.DrawSurfaceBG_Mushroom (float backgroundTopMagicNumber, float bgGlobalScaleMultiplier, int pushBGTopHack, int[] bgTexIndexes) inline private
Definition at line 60899 of file Main.cs.
        {
            Vector3 vector = new Vector3(0.1f, 0.15f, 0.3f);
            Vector3 vector2 = new Vector3(0.1f, 0.175f, 0.3f);
            Vector3 vector3 = new Vector3(0.125f, 0.2f, 0.3f);
            float num = 0.5f;
            float num2 = 0.625f;
            float num3 = 0.75f;
            vector *= 3f;
            vector2 *= 3f;
            vector3 *= 3f;
            float num4 = (float)Main.ColorOfSurfaceBackgroundsModified.A / 255f;
            Microsoft.Xna.Framework.Color color = Main.ColorOfSurfaceBackgroundsModified;
            float num5 = (float)Main.rand.Next(28, 42) * 0.001f;
            num5 += (float)(270 - (int)Main.mouseTextColor) / 5000f;
            float num6 = vector.X;
            float num7 = vector.Y + num5 / 2f;
            float num8 = vector.Z + num5;
            num6 *= 255f;
            num7 *= 255f;
            num8 *= 255f;
            num6 *= num * num4;
            num7 *= num * num4;
            num8 *= num * num4;
            if (num6 > 255f)
            {
                num6 = 255f;
            }
            if (num7 > 255f)
            {
                num7 = 255f;
            }
            if (num8 > 255f)
            {
                num8 = 255f;
            }
            if (num6 > (float)color.R)
            {
                color.R = (byte)num6;
            }
            if (num7 > (float)color.G)
            {
                color.G = (byte)num7;
            }
            if (num8 > (float)color.B)
            {
                color.B = (byte)num8;
            }
            Main.bgScale = 1.25f;
            Main.bgScale *= bgGlobalScaleMultiplier;
            this.LoadBackground(bgTexIndexes[0]);
            Main.bgWidthScaled = (int)((float)Main.backgroundWidth[bgTexIndexes[0]] * Main.bgScale);
            this.bgParallax = 0.4;
            this.SetBackgroundOffsets(bgTexIndexes[0], backgroundTopMagicNumber, pushBGTopHack);
            SkyManager.Instance.DrawToDepth(Main.spriteBatch, 1f / (float)this.bgParallax);
            this.bgStartX = (int)(-Math.IEEERemainder((double)Main.screenPosition.X * this.bgParallax, (double)Main.bgWidthScaled) - (double)(Main.bgWidthScaled / 2));
            this.bgTopY = backgroundTopMagicNumber * 1800f + 1400f + this.scAdj + (float)pushBGTopHack;
            this.SetBackgroundOffsets(bgTexIndexes[0], backgroundTopMagicNumber, pushBGTopHack);
            if (Main.gameMenu)
            {
                this.bgTopY = (float)(320 + pushBGTopHack);
            }
            if (Main.bgWidthScaled != 0)
            {
                this.bgLoops = Main.screenWidth / Main.bgWidthScaled + 2;
            }
            if (TextureAssets.Background[bgTexIndexes[0]].Value == null)
            {
                return;
            }
            if ((double)Main.screenPosition.Y < Main.worldSurface * 16.0 + 16.0)
            {
                for (int i = 0; i < this.bgLoops; i++)
                {
                    Main.spriteBatch.Draw(TextureAssets.Background[bgTexIndexes[0]].Value, new Vector2((float)(this.bgStartX + Main.bgWidthScaled * i), this.bgTopY), this.GetBackgroundRect(bgTexIndexes[0]), color, 0f, default(Vector2), Main.bgScale, SpriteEffects.None, 0f);
                }
            }
            color = Main.ColorOfSurfaceBackgroundsModified;
            num5 = (float)Main.rand.Next(28, 42) * 0.001f;
            num5 += (float)(270 - (int)Main.mouseTextColor) / 5000f;
            num6 = vector2.X;
            num7 = vector2.Y + num5 / 2f;
            num8 = vector2.Z + num5;
            num6 *= 255f;
            num7 *= 255f;
            num8 *= 255f;
            num6 *= num2 * num4;
            num7 *= num2 * num4;
            num8 *= num2 * num4;
            if (num6 > 255f)
            {
                num6 = 255f;
            }
            if (num7 > 255f)
            {
                num7 = 255f;
            }
            if (num8 > 255f)
            {
                num8 = 255f;
            }
            if (num6 > (float)color.R)
            {
                color.R = (byte)num6;
            }
            if (num7 > (float)color.G)
            {
                color.G = (byte)num7;
            }
            if (num8 > (float)color.B)
            {
                color.B = (byte)num8;
            }
            Main.bgScale = 1.32f;
            Main.bgScale *= bgGlobalScaleMultiplier;
            this.LoadBackground(bgTexIndexes[1]);
            Main.bgWidthScaled = (int)((float)Main.backgroundWidth[bgTexIndexes[1]] * Main.bgScale);
            this.bgParallax = 0.43;
            this.SetBackgroundOffsets(bgTexIndexes[1], backgroundTopMagicNumber, pushBGTopHack);
            SkyManager.Instance.DrawToDepth(Main.spriteBatch, 1f / (float)this.bgParallax);
            this.bgStartX = (int)(-Math.IEEERemainder((double)Main.screenPosition.X * this.bgParallax, (double)Main.bgWidthScaled) - (double)(Main.bgWidthScaled / 2));
            this.bgTopY = backgroundTopMagicNumber * 1950f + 1675f + this.scAdj + (float)pushBGTopHack;
            this.SetBackgroundOffsets(bgTexIndexes[1], backgroundTopMagicNumber, pushBGTopHack);
            if (Main.gameMenu)
            {
                this.bgTopY = (float)(400 + pushBGTopHack);
                this.bgStartX -= 80;
            }
            if (Main.bgWidthScaled == 0)
            {
                return;
            }
            this.bgLoops = Main.screenWidth / Main.bgWidthScaled + 2;
            if ((double)Main.screenPosition.Y < Main.worldSurface * 16.0 + 16.0)
            {
                for (int j = 0; j < this.bgLoops; j++)
                {
                    Main.spriteBatch.Draw(TextureAssets.Background[bgTexIndexes[1]].Value, new Vector2((float)(this.bgStartX + Main.bgWidthScaled * j), this.bgTopY), this.GetBackgroundRect(bgTexIndexes[1]), color, 0f, default(Vector2), Main.bgScale, SpriteEffects.None, 0f);
                }
            }
            color = Main.ColorOfSurfaceBackgroundsModified;
            num5 = (float)Main.rand.Next(28, 42) * 0.001f;
            num5 += (float)(270 - (int)Main.mouseTextColor) / 3000f;
            num6 = vector3.X;
            num7 = vector3.Y + num5 / 2f;
            num8 = vector3.Z + num5;
            num6 *= 255f * num4 * num3;
            num7 *= 255f * num4 * num3;
            num8 *= 255f * num4 * num3;
            if (num6 > 255f)
            {
                num6 = 255f;
            }
            if (num7 > 255f)
            {
                num7 = 255f;
            }
            if (num8 > 255f)
            {
                num8 = 255f;
            }
            if (num6 > (float)color.R)
            {
                color.R = (byte)num6;
            }
            if (num7 > (float)color.G)
            {
                color.G = (byte)num7;
            }
            if (num8 > (float)color.B)
            {
                color.B = (byte)num8;
            }
            Main.bgScale = 1.36f;
            Main.bgScale *= bgGlobalScaleMultiplier;
            this.LoadBackground(bgTexIndexes[2]);
            Main.bgWidthScaled = (int)((float)Main.backgroundWidth[bgTexIndexes[2]] * Main.bgScale);
            this.bgParallax = 0.49;
            this.SetBackgroundOffsets(bgTexIndexes[2], backgroundTopMagicNumber, pushBGTopHack);
            SkyManager.Instance.DrawToDepth(Main.spriteBatch, 1f / (float)this.bgParallax);
            this.bgStartX = (int)(-Math.IEEERemainder((double)Main.screenPosition.X * this.bgParallax, (double)Main.bgWidthScaled) - (double)(Main.bgWidthScaled / 2));
            this.bgTopY = backgroundTopMagicNumber * 2100f + 1950f + this.scAdj + (float)pushBGTopHack;
            this.SetBackgroundOffsets(bgTexIndexes[2], backgroundTopMagicNumber, pushBGTopHack);
            if (Main.gameMenu)
            {
                this.bgTopY = (float)(480 + pushBGTopHack);
                this.bgStartX -= 120;
            }
            if (Main.bgWidthScaled == 0)
            {
                return;
            }
            this.bgLoops = Main.screenWidth / Main.bgWidthScaled + 2;
            if ((double)Main.screenPosition.Y < Main.worldSurface * 16.0 + 16.0)
            {
                for (int k = 0; k < this.bgLoops; k++)
                {
                    Main.spriteBatch.Draw(TextureAssets.Background[bgTexIndexes[2]].Value, new Vector2((float)(this.bgStartX + Main.bgWidthScaled * k), this.bgTopY), this.GetBackgroundRect(bgTexIndexes[2]), color, 0f, default(Vector2), Main.bgScale, SpriteEffects.None, 0f);
                }
            }
            SkyManager.Instance.DrawToDepth(Main.spriteBatch, 1f);
        }
References Microsoft.Xna.Framework.Color.B, Terraria.GameContent.TextureAssets.Background, Terraria.Main.backgroundWidth, Terraria.Main.bgScale, Terraria.Main.bgWidthScaled, Terraria.Main.ColorOfSurfaceBackgroundsModified, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Graphics.Effects.SkyManager.DrawToDepth(), Microsoft.Xna.Framework.Color.G, Terraria.Main.gameMenu, System.Math.IEEERemainder(), Terraria.Graphics.Effects.SkyManager.Instance, int, Terraria.Main.mouseTextColor, Terraria.Utilities.UnifiedRandom.Next(), Microsoft.Xna.Framework.Color.R, Terraria.Main.rand, Terraria.Main.screenPosition, Terraria.Main.spriteBatch, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector3, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector3.X.