Terraria Decompiled: Terraria.Main.DoUpdate_F11_ToggleUI
DoUpdate_F11_ToggleUI()
static void Terraria.Main.DoUpdate_F11_ToggleUI () inline static private
Definition at line 16847 of file Main.cs.
        {
            if (Main.keyState.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.F11))
            {
                if (Main.releaseUI)
                {
                    if (Main.hideUI)
                    {
                        Main.hideUI = false;
                    }
                    else
                    {
                        Main.hideUI = true;
                    }
                    SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                }
                Main.releaseUI = false;
                return;
            }
            Main.releaseUI = true;
        }
References Terraria.Main.hideUI, Microsoft.Xna.Framework.Input.KeyboardState.IsKeyDown(), Terraria.Main.keyState, Terraria.Audio.SoundEngine.PlaySound(), and Terraria.Main.releaseUI.
Referenced by Terraria.Main.DoUpdate().