Terraria Decompiled: Terraria.Main.UpdateAudio
UpdateAudio()
void Terraria.Main.UpdateAudio () inline protected
Definition at line 9154 of file Main.cs.
        {
            if (!SoundEngine.IsAudioSupported)
            {
                return;
            }
            if (!this._musicLoaded)
            {
                return;
            }
            if (!Main.dedServ && !Main.showSplash)
            {
                SoundEngine.Update();
            }
            if (Main.musicVolume == 0f)
            {
                Main.curMusic = 0;
            }
            try
            {
                if (!Main.dedServ)
                {
                    bool allowMusic = FocusHelper.AllowMusic;
                    if (!allowMusic)
                    {
                        Main.audioSystem.PauseAll();
                        SoundEngine.StopAmbientSounds();
                    }
                    else
                    {
                        Main.audioSystem.ResumeAll();
                    }
                    if (Main.drunkWorld)
                    {
                        Main.TOWMusicUnlocked = true;
                    }
                    if (Main.gameMenu)
                    {
                        Main.swapMusic = false;
                    }
                    bool flag = Main.drunkWorld && !Main.remixWorld && !Main.getGoodWorld;
                    if (Main.swapMusic)
                    {
                        if (flag)
{
                            this.UpdateAudio_DecideOnNewMusic();
                        }
                        else
{
                            this.UpdateAudio_DecideOnTOWMusic();
                        }
                    }
                    else if (!Main.gameMenu && flag)
                    {
                        this.UpdateAudio_DecideOnTOWMusic();
                    }
                    else
                    {
                        this.UpdateAudio_DecideOnNewMusic();
                    }
                    bool flag2 = false;
                    if (Main.SceneMetrics.ActiveMusicBox >= 0)
                    {
                        if (Main.SceneMetrics.ActiveMusicBox == 0)
{
                            Main.newMusic = 1;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 1)
{
                            Main.newMusic = 2;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 2)
{
                            Main.newMusic = 3;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 4)
{
                            Main.newMusic = 4;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 5)
{
                            Main.newMusic = 5;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 3)
{
                            Main.newMusic = 6;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 6)
{
                            Main.newMusic = 7;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 7)
{
                            Main.newMusic = 8;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 9)
{
                            Main.newMusic = 9;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 8)
{
                            Main.newMusic = 10;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 11)
{
                            Main.newMusic = 11;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 10)
{
                            Main.newMusic = 12;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 12)
{
                            Main.newMusic = 13;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 13)
{
                            Main.newMusic = 14;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 14)
{
                            Main.newMusic = 15;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 15)
{
                            Main.newMusic = 16;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 16)
{
                            Main.newMusic = 17;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 17)
{
                            Main.newMusic = 18;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 18)
{
                            Main.newMusic = 19;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 19)
{
                            Main.newMusic = 20;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 20)
{
                            Main.newMusic = 21;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 21)
{
                            Main.newMusic = 22;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 22)
{
                            Main.newMusic = 23;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 23)
{
                            Main.newMusic = 24;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 24)
{
                            Main.newMusic = 25;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 25)
{
                            Main.newMusic = 26;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 26)
{
                            Main.newMusic = 27;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 27)
{
                            Main.newMusic = 29;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 28)
{
                            Main.newMusic = 30;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 29)
{
                            Main.newMusic = 31;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 30)
{
                            Main.newMusic = 32;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 31)
{
                            Main.newMusic = 33;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 32)
{
                            Main.newMusic = 38;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 33)
{
                            Main.newMusic = 37;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 34)
{
                            Main.newMusic = 35;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 35)
{
                            Main.newMusic = 36;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 36)
{
                            Main.newMusic = 34;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 37)
{
                            Main.newMusic = 39;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 38)
{
                            Main.newMusic = 40;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 39)
{
                            Main.newMusic = 41;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 40)
{
                            Main.newMusic = 44;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 41)
{
                            Main.newMusic = 48;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 42)
{
                            Main.newMusic = 42;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 43)
{
                            Main.newMusic = 43;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 44)
{
                            Main.newMusic = 46;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 45)
{
                            Main.newMusic = 47;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 46)
{
                            Main.newMusic = 49;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 47)
{
                            Main.newMusic = 51;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 48)
{
                            Main.newMusic = 52;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 49)
{
                            Main.newMusic = 53;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 50)
{
                            Main.newMusic = 54;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 51)
{
                            Main.newMusic = 55;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 52)
{
                            Main.newMusic = 56;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 53)
{
                            Main.newMusic = 57;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 54)
{
                            Main.newMusic = 58;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 55)
{
                            Main.newMusic = 59;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 56)
{
                            Main.newMusic = 60;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 57)
{
                            Main.newMusic = 61;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 58)
{
                            Main.newMusic = 62;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 59)
{
                            Main.newMusic = 63;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 60)
{
                            Main.newMusic = 64;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 61)
{
                            Main.newMusic = 65;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 62)
{
                            Main.newMusic = 66;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 63)
{
                            Main.newMusic = 67;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 64)
{
                            Main.newMusic = 68;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 65)
{
                            Main.newMusic = 69;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 66)
{
                            Main.newMusic = 70;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 67)
{
                            Main.newMusic = 71;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 68)
{
                            Main.newMusic = 72;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 69)
{
                            Main.newMusic = 73;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 70)
{
                            Main.newMusic = 74;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 71)
{
                            Main.newMusic = 75;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 72)
{
                            Main.newMusic = 76;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 73)
{
                            Main.newMusic = 77;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 74)
{
                            Main.newMusic = 78;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 75)
{
                            Main.newMusic = 79;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 76)
{
                            Main.newMusic = 80;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 77)
{
                            Main.newMusic = 81;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 78)
{
                            Main.newMusic = 82;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 79)
{
                            Main.newMusic = 83;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 80)
{
                            Main.newMusic = 84;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 81)
{
                            Main.newMusic = 85;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 82)
{
                            Main.newMusic = 86;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 83)
{
                            Main.newMusic = 87;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 84)
{
                            Main.newMusic = 88;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 85)
{
                            Main.newMusic = 89;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 86)
{
                            Main.newMusic = 90;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 87)
{
                            Main.newMusic = 91;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 88)
{
                            Main.newMusic = 93;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 89)
{
                            Main.newMusic = 96;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 90)
{
                            Main.newMusic = 95;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 91)
{
                            Main.newMusic = 94;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 92)
{
                            Main.newMusic = 97;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 93)
{
                            Main.newMusic = 98;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 94)
{
                            Main.newMusic = 92;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 95)
{
                            Main.newMusic = 99;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 96)
{
                            Main.newMusic = 101;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 97)
{
                            Main.newMusic = 100;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 98)
{
                            Main.newMusic = 104;
                        }
                        if (Main.SceneMetrics.ActiveMusicBox == 99)
{
                            Main.newMusic = 103;
                        }
                    }
                    if (Main.SceneMetrics.MusicBoxSilence)
                    {
                        flag2 = true;
                    }
                    if (Main.musicVolume == 0f)
                    {
                        Main.newMusic = 0;
                    }
                    Main.audioSystem.Update();
                    Main.audioSystem.UpdateMisc();
                    Main.curMusic = Main.newMusic;
                    float num = 1f;
                    if (NPC.MoonLordCountdown > 0)
                    {
                        num = (float)NPC.MoonLordCountdown / (float)NPC.MaxMoonLordCountdown;
                        num *= num;
                        if ((float)NPC.MoonLordCountdown > (float)NPC.MaxMoonLordCountdown * 0.2f)
{
                            num = MathHelper.Lerp(0f, 1f, num);
                        }
                        else
{
                            num = 0f;
                            Main.curMusic = 0;
                        }
                        if (NPC.MoonLordCountdown == 1 && Main.curMusic >= 1 && Main.curMusic < Main.maxMusic)
{
                            Main.musicFade[Main.curMusic] = 0f;
                        }
                    }
                    this._musicSilencerCounter += (flag2 ? 1 : (-1));
                    int num2 = 240;
                    this._musicSilencerCounter = Utils.Clamp<int>(this._musicSilencerCounter, 0, num2);
                    if (this._musicSilencerCounter > 0)
                    {
                        float num3 = (float)this._musicSilencerCounter / (float)num2;
                        num3 *= num3;
                        num *= 1f - num3;
                        if (num3 == 1f)
{
                            Main.curMusic = 0;
                        }
                    }
                    bool flag3 = Main.musicFade[Main.curMusic] > 0.25f;
                    for (int i = 1; i < Main.maxMusic; i++)
                    {
                        float num4 = Main.musicFade[i] * Main.musicVolume * num;
                        if (i >= 62 && i <= 88)
{
                            num4 *= 0.9f;
                        }
                        else if (i == 52)
{
                            num4 *= 1.15f;
                            if (num4 > 1f)
{
                                num4 = 1f;
                            }
                        }
                        float num5 = Main.shimmerAlpha;
                        if (i == 28)
{
                            float num6 = 0.5f;
                            float num7 = Main.cloudAlpha / 9f * 10f * num6 + (1f - num6);
                            if (num5 > 0f)
{
                                num7 *= 1f - num5;
                            }
                            if (num7 > 1f)
{
                                num7 = 1f;
                            }
                            num7 *= (float)Math.Pow((double)Main.atmo, 4.0);
                            bool flag4 = Main.SceneMetrics.ZoneRain && !Main.SceneMetrics.ZoneSnow;
                            float num8 = Main.musicFade[i];
                            if (flag4)
{
                                Main.audioSystem.UpdateAmbientCueState(i, allowMusic, ref num8, Main.ambientVolume * num7);
                            }
                            else
{
                                Main.audioSystem.UpdateAmbientCueTowardStopping(i, 0.005f, ref num8, Main.ambientVolume * num7);
                            }
                            Main.musicFade[i] = num8;
                        }
                        else if (i == 45)
{
                            float num9 = 0.7f;
                            float num10 = Math.Abs(Main.windSpeedCurrent) * num9 + (1f - num9);
                            if (num5 > 0f)
{
                                num10 *= 1f - num5;
                            }
                            if (num10 > 1f)
{
                                num10 = 1f;
                            }
                            num10 *= 0.9f;
                            float num11 = 20f;
                            num10 *= (float)Math.Pow((double)Main.atmo, 4.0);
                            bool flag5 = Math.Abs(Main.windSpeedCurrent) >= num11 / 50f && Main.SceneMetrics.SurfaceAtmospherics;
                            float num12 = Main.musicFade[i];
                            if (flag5)
{
                                Main.audioSystem.UpdateAmbientCueState(i, allowMusic, ref num12, Main.ambientVolume * num10);
                            }
                            else
{
                                Main.audioSystem.UpdateAmbientCueTowardStopping(i, 0.005f, ref num12, Main.ambientVolume * num10);
                            }
                            Main.musicFade[i] = num12;
                        }
                        else if (i == Main.curMusic)
{
                            Main.audioSystem.UpdateCommonTrack(allowMusic, i, num4, ref Main.musicFade[i]);
                        }
                        else
{
                            Main.audioSystem.UpdateCommonTrackTowardStopping(i, num4, ref Main.musicFade[i], flag3);
                        }
                    }
                    Main.audioSystem.UpdateAudioEngine();
                    if (Main.musicError > 0)
                    {
                        Main.musicError--;
                    }
                }
            }
            catch (Exception ex)
            {
                if (Platform.IsLinux)
                {
                    if (Main.musicError == 0)
                    {
                        File.WriteAllText("musicerror.log", "");
                    }
                    File.AppendAllText("musicerror.log", ex.ToString() + "\n\n");
                }
                Main.musicError++;
                if (Main.musicError >= 100)
                {
                    Main.NewText("Music Disabled", byte.MaxValue, 0, 0);
                    Main.musicError = 0;
                    Main.musicVolume = 0f;
                }
            }
        }
References System.Math.Abs(), Terraria.SceneMetrics.ActiveMusicBox, Terraria.FocusHelper.AllowMusic, Terraria.Main.ambientVolume, System.IO.File.AppendAllText(), Terraria.Main.atmo, Terraria.Main.audioSystem, Terraria.Utils.Clamp(), Terraria.Main.curMusic, Terraria.Main.dedServ, Terraria.Main.drunkWorld, Terraria.Main.gameMenu, Terraria.Main.getGoodWorld, Terraria.Audio.SoundEngine.IsAudioSupported, ReLogic.OS.Platform.IsLinux, Microsoft.Xna.Framework.MathHelper.Lerp(), Terraria.NPC.MaxMoonLordCountdown, Terraria.Main.maxMusic, System.Reflection.MaxValue, Terraria.NPC.MoonLordCountdown, Terraria.SceneMetrics.MusicBoxSilence, Terraria.Main.musicError, Terraria.Main.musicFade, Terraria.Main.musicVolume, Terraria.Main.newMusic, Terraria.Main.NewText(), Terraria.Audio.IAudioSystem.PauseAll(), System.Math.Pow(), Terraria.Audio.IAudioSystem.ResumeAll(), Terraria.Main.SceneMetrics, Terraria.Main.shimmerAlpha, Terraria.Main.showSplash, Terraria.Audio.SoundEngine.StopAmbientSounds(), Terraria.SceneMetrics.SurfaceAtmospherics, Terraria.Main.swapMusic, System.Exception.ToString(), Terraria.Audio.IAudioSystem.Update(), Terraria.Audio.SoundEngine.Update(), Terraria.Audio.IAudioSystem.UpdateAmbientCueState(), Terraria.Audio.IAudioSystem.UpdateAmbientCueTowardStopping(), Terraria.Audio.IAudioSystem.UpdateAudioEngine(), Terraria.Audio.IAudioSystem.UpdateCommonTrack(), Terraria.Audio.IAudioSystem.UpdateCommonTrackTowardStopping(), Terraria.Audio.IAudioSystem.UpdateMisc(), Terraria.Main.windSpeedCurrent, System.IO.File.WriteAllText(), and Terraria.SceneMetrics.ZoneSnow.