Terraria Decompiled: Terraria.Main.MenuUI
MenuUI
UserInterface Terraria.Main.MenuUI = new UserInterface() static
Definition at line 68250 of file Main.cs.
Referenced by Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.Click_Info(), Terraria.GameContent.UI.States.UICharacterCreation.Click_Naming(), Terraria.GameContent.UI.States.UICharacterCreation.Click_NamingAndCreating(), Terraria.GameContent.UI.States.UIWorldCreation.Click_NamingAndCreating(), Terraria.GameContent.UI.States.UIWorkshopHub.Click_OpenResourcePackPublishMenu(), Terraria.GameContent.UI.States.UIWorkshopHub.Click_OpenWorldImportMenu(), Terraria.GameContent.UI.States.UIWorkshopHub.Click_OpenWorldPublishMenu(), Terraria.GameContent.UI.States.UIWorldCreation.Click_SetName(), Terraria.GameContent.UI.States.UIWorldCreation.ClickAdvancedSeedMenu(), Terraria.GameContent.UI.States.UIWorldGenDebug.Close(), Terraria.WorldGen.CreateNewWorld(), Terraria.Main.DoUpdate(), Terraria.GameContent.UI.States.UICharacterSelect.Draw(), Terraria.GameContent.UI.States.UIWorldSelect.Draw(), Terraria.Main.DrawMenu(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.GetCurrentInterface(), Terraria.GameContent.UI.States.UICharacterCreation.GoBack(), Terraria.GameContent.UI.States.UIWorldCreationAdvanced.GoBack(), Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.GoBack(), Terraria.GameContent.UI.States.UIReportsPage.GoBackClick(), Terraria.GameContent.UI.States.UIResourcePackInfoMenu.GoBackClick(), Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem.GoBackHere(), Terraria.GameContent.UI.States.UIWorldCreation.GoBackHere(), Terraria.UI.Gamepad.UILinkPointNavigator.GoToDefaultPage(), Terraria.GameContent.UI.States.WorkshopPublishInfoStateForResourcePack.GoToPublishConfirmation(), Terraria.GameContent.UI.States.WorkshopPublishInfoStateForWorld.GoToPublishConfirmation(), Terraria.Main.GoToWorldSelect(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.HandleBackButtonUsage(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.HandleBackButtonUsage(), Terraria.GameContent.UI.States.UIWorkshopHub.HandleBackButtonUsage(), Terraria.GameContent.UI.States.UIWorkshopSelectResourcePackToPublish.HandleBackButtonUsage(), Terraria.GameContent.UI.States.UIWorkshopSelectWorldToPublish.HandleBackButtonUsage(), Terraria.GameContent.UI.States.UIWorkshopWorldImport.HandleBackButtonUsage(), Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem.ImportButtonClick_ImportWorldToLocalFiles(), Terraria.GameContent.UI.States.UICharacterSelect.NewCharacterClick(), Terraria.GameContent.UI.States.UIWorldSelect.NewWorldClick(), Terraria.GameContent.UI.States.UICharacterCreation.OnCanceledNaming(), Terraria.GameContent.UI.States.UICharacterCreation.OnFinishedNaming(), Terraria.GameContent.UI.States.UICharacterCreation.OnFinishedNamingAndCreating(), Terraria.GameContent.UI.States.UIWorldGenDebug.Open(), Terraria.UI.IngameFancyUI.OpenAchievements(), Terraria.Main.OpenCharacterSelectUI(), Terraria.Main.OpenPlayerSelect(), Terraria.Main.OpenReportsMenu(), Terraria.Main.OpenResourcePacksMenu(), Terraria.GameContent.UI.States.UIWorldCreation.OpenSeedInputMenu(), Terraria.Main.OpenWorldSelectUI(), Terraria.Main.PreDrawMenu(), Terraria.GameContent.UI.Elements.UIWorkshopPublishResourcePackListItem.PublishButtonClick_ImportResourcePackToLocalFiles(), Terraria.GameContent.UI.Elements.UIWorkshopPublishWorldListItem.PublishButtonClick_ImportWorldToLocalFiles(), Terraria.GameContent.UI.Elements.UIWorkshopPublishResourcePackListItem.RejectionMenuExitAction(), Terraria.GameContent.UI.Elements.UICharacterListItem.RenameButtonClick(), Terraria.GameContent.UI.Elements.UIWorldListItem.RenameButtonClick(), Terraria.GameContent.UI.States.UIWorldCreationAdvanced.SecretSeedButton_OnLeftClick(), Terraria.UI.Gamepad.GamepadMainMenuHandler.Update(), Terraria.UI.Gamepad.UILinkPointNavigator.Update(), and Terraria.Main.UpdateUIStates().