Terraria Decompiled: Terraria.Main.DrawWhip_EelWhip
DrawWhip_EelWhip()
static Vector2 Terraria.Main.DrawWhip_EelWhip (Projectile proj, List< Vector2 > controlPoints) inline static
Definition at line 35927 of file Main.cs.
        {
            int num = 5;
            SpriteEffects spriteEffects = SpriteEffects.None;
            if (proj.spriteDirection == 1)
            {
                spriteEffects ^= SpriteEffects.FlipHorizontally;
            }
            Texture2D value = TextureAssets.Projectile[proj.type].Value;
            Microsoft.Xna.Framework.Rectangle rectangle = value.Frame(1, num, 0, 0, 0, 0);
            int height = rectangle.Height;
            rectangle.Height -= 2;
            Vector2 vector = rectangle.Size() / 2f;
            Vector2 vector2 = controlPoints[0];
            float whipAnimationPercent = Projectile.GetWhipAnimationPercent(proj);
            int num2 = controlPoints.Count - 1;
            for (int i = 0; i < num2; i++)
            {
                bool flag = true;
                Vector2 vector3 = vector;
                Vector2 zero = Vector2.Zero;
                if (i == 0)
                {
                    flag = false;
                }
                else if (i == 1)
                {
                    rectangle.Y = 0;
                    float num3 = -6f;
                    float num4 = whipAnimationPercent;
                    float[] array = new float[3];
                    array[1] = 1f;
                    zero = new Vector2(num3 * Utils.MultiLerp(num4, array), 0f);
                }
                else if (i == num2 - 1)
                {
                    rectangle.Y = height * (num - 1);
                }
                else
                {
                    int num5 = ((i < 25) ? 1 : ((i < 35) ? 2 : 3));
                    rectangle.Y = height * num5;
                }
                Vector2 vector4 = controlPoints[i];
                Vector2 vector5 = controlPoints[i + 1] - vector4;
                if (flag)
                {
                    float num6 = vector5.ToRotation();
                    float num7 = num6 - 1.5707964f;
                    Vector2 vector6 = new Vector2(Utils.Remap((float)i, 2f, (float)(num2 - 5), 0.5f, 1f, true), 1f) * proj.scale;
                    Microsoft.Xna.Framework.Color color = Lighting.GetColor(vector4.ToTileCoordinates());
                    Main.spriteBatch.Draw(value, vector2 - Main.screenPosition + zero.RotatedBy((double)num6, default(Vector2)), new Microsoft.Xna.Framework.Rectangle?(rectangle), color, num7, vector3, vector6, spriteEffects, 0f);
                    Microsoft.Xna.Framework.Color color2 = new Microsoft.Xna.Framework.Color(255, 255, 255, 0);
                    Main.spriteBatch.Draw(TextureAssets.GlowMask[358].Value, vector2 - Main.screenPosition + zero.RotatedBy((double)num6, default(Vector2)), new Microsoft.Xna.Framework.Rectangle?(rectangle), color2, num7, vector3, vector6, spriteEffects, 0f);
                }
                vector2 += vector5;
            }
            return vector2;
        }
References System.array, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Lighting.GetColor(), Terraria.Projectile.GetWhipAnimationPercent(), Terraria.GameContent.TextureAssets.GlowMask, Microsoft.Xna.Framework.Rectangle.Height, Terraria.Utils.MultiLerp(), Terraria.GameContent.TextureAssets.Projectile, Terraria.Utils.Remap(), Terraria.Projectile.scale, Terraria.Main.screenPosition, Terraria.Main.spriteBatch, Terraria.Projectile.spriteDirection, Terraria.Projectile.type, System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.Main.DrawWhip().