Terraria Decompiled: Terraria.Main.DrawNPCHeadFriendly
DrawNPCHeadFriendly()
static void Terraria.Main.DrawNPCHeadFriendly (Entity theNPC, byte alpha, float headScale, SpriteEffects dir, int townHeadId, float x, float y) inline static private
Definition at line 57358 of file Main.cs.
        {
            Main.TownNPCHeadRenderer.DrawWithOutlines(townHeadId, new Vector2(x, y), new Microsoft.Xna.Framework.Color((int)alpha, (int)alpha, (int)alpha, (int)alpha), 0f, headScale, dir);
            NPC npc = theNPC as NPC;
            if (npc != null && npc.nextDialogue != null && npc.nextDialogue.ShowIndicator)
            {
                Utils.DrawNotificationIcon(Main.spriteBatch, new Vector2(x, y - 20f), 1f, false);
            }
        }
References Terraria.Utils.DrawNotificationIcon(), Terraria.Graphics.Renderers.OutlinedTextureRenderer.DrawWithOutlines(), Terraria.NPC.nextDialogue, Terraria.Enums.NPC, Terraria.GameContent.ConditionalDialogue.ShowIndicator, Terraria.Main.spriteBatch, Terraria.Main.TownNPCHeadRenderer, and Microsoft.Xna.Framework.Graphics.Vector2.
Referenced by Terraria.Main.DrawNPCMapIcons(), Terraria.Main.DrawNPCMapIcons2(), and Terraria.Main.DrawNPCMapIcons3().