Terraria Decompiled: Terraria.Main.ReforgeItemInReforgeSlot
ReforgeItemInReforgeSlot()
static void Terraria.Main.ReforgeItemInReforgeSlot () inline static private
Definition at line 41846 of file Main.cs.
        {
            Main.reforgeItem.ResetPrefix();
            bool flag;
            Main.reforgeItem.Prefix(-2, out flag);
            PopupText.NewText(flag ? PopupTextContext.ItemReforge_Best : PopupTextContext.ItemReforge, Main.reforgeItem, Main.LocalPlayer.Center, Main.reforgeItem.stack, true, false);
            if (flag)
            {
                SoundEngine.PlaySound(SoundID.BestReforge, -1, -1, 0f, 1f);
                Main.reforgeCooldown = 60;
                ParticleOrchestrator.RequestParticleSpawn(true, ParticleOrchestraType.RainbowRodHit, new ParticleOrchestraSettings
                {
                    PositionInWorld = Main.LocalPlayer.MountedCenter + new Vector2(0f, -16f * Main.LocalPlayer.gravDir),
                    MovementVector = new Vector2(48f, 0f) + Main.rand.NextVector2Circular(16f, 16f)
                }, new int?(Main.myPlayer));
                ParticleOrchestrator.RequestParticleSpawn(true, ParticleOrchestraType.RainbowRodHit, new ParticleOrchestraSettings
                {
                    PositionInWorld = Main.LocalPlayer.MountedCenter + new Vector2(0f, -16f * Main.LocalPlayer.gravDir),
                    MovementVector = new Vector2(0f, 16f) + Main.rand.NextVector2Circular(5f, 5f)
                }, new int?(Main.myPlayer));
                for (int i = 0; i < 3; i++)
                {
                    ParticleOrchestrator.RequestParticleSpawn(true, ParticleOrchestraType.BestReforge, new ParticleOrchestraSettings
                    {
                        PositionInWorld = Main.LocalPlayer.MountedCenter + Main.rand.NextVector2Circular(16f, 16f)
                    }, new int?(Main.myPlayer));
                }
                return;
            }
            SoundEngine.PlaySound(SoundID.Item37, -1, -1, 0f, 1f);
        }
References Terraria.ID.SoundID.BestReforge, Terraria.Entity.Center, Terraria.Player.gravDir, Terraria.Main.LocalPlayer, Terraria.Player.MountedCenter, Terraria.Main.myPlayer, Terraria.PopupText.NewText(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.Item.Prefix(), Terraria.Main.rand, Terraria.Main.reforgeItem, Terraria.GameContent.Drawing.ParticleOrchestrator.RequestParticleSpawn(), Terraria.Item.ResetPrefix(), Terraria.Item.stack, and Microsoft.Xna.Framework.Graphics.Vector2.
Referenced by Terraria.Main.DrawInventory().