Terraria Decompiled: Terraria.Main.UpdateWeather
UpdateWeather()
void Terraria.Main.UpdateWeather (GameTime gameTime, int currentDayRateIteration) inline
Definition at line 59515 of file Main.cs.
        {
            if (Main.netMode != 2 && currentDayRateIteration == 0)
            {
                bool updateBackgroundThunder = FocusHelper.UpdateBackgroundThunder;
                if (Main.thunderDelay > 0)
                {
                    Main.thunderDelay--;
                    if (Main.thunderDelay == 0)
                    {
                        Vector2 center = Main.SceneMetrics.Center;
                        float num = (float)(Main.thunderDistance * 15);
                        if (Main.rand.Next(2) == 0)
{
                            num *= -1f;
                        }
                        center.X += num;
                        int num2 = (int)(Main.worldSurface * 16.0) - 500;
                        if (center.Y > (float)num2)
{
                            center.Y = (float)num2;
                        }
                        if (updateBackgroundThunder && !Main.thunderSkipSound)
{
                            SoundEngine.PlaySound(43, center, 1, 0f);
                        }
                    }
                }
                if (Main.lightningSpeed > 0f)
                {
                    Main.lightning += Main.lightningSpeed;
                    if (Main.lightning >= 1f)
                    {
                        Main.lightning = 1f;
                        Main.lightningSpeed = 0f;
                    }
                    Lighting.LightTiles(Main.GetAreaToLight());
                    Lighting.LightTiles(Main.GetAreaToLight());
                }
                else if (Main.lightning > 0f)
                {
                    Main.lightning -= Main.lightningDecay;
                    Lighting.LightTiles(Main.GetAreaToLight());
                    Lighting.LightTiles(Main.GetAreaToLight());
                }
                else if (Main.thunderDelay <= 0 && (double)Main.SceneMetrics.TileCenter.Y < Main.rockLayer && Main.atmo == 1f && !Main.remixWorld)
                {
                    if (Main.IsItStorming)
                    {
                        float num3 = 600f;
                        float num4 = 1600f;
                        if ((double)Main.maxRaining > 0.8)
{
                            num3 *= 0.6f;
                            num4 *= 0.8f;
                        }
                        if ((double)Main.maxRaining > 0.7)
{
                            num3 *= 0.7f;
                            num4 *= 0.9f;
                        }
                        if ((double)Main.maxRaining > 0.6)
{
                            num3 *= 0.8f;
                            num4 *= 0.95f;
                        }
                        if ((double)Math.Abs(Main.windSpeedTarget) > 0.7)
{
                            num3 *= 0.6f;
                            num4 *= 0.8f;
                        }
                        if ((double)Math.Abs(Main.windSpeedTarget) > 0.6)
{
                            num3 *= 0.7f;
                            num4 *= 0.9f;
                        }
                        if ((double)Math.Abs(Main.windSpeedTarget) > 0.5)
{
                            num3 *= 0.8f;
                            num4 *= 0.95f;
                        }
                        float num5 = (float)Main.rand.Next((int)num3, (int)num4);
                        num5 *= (1f - Main.maxRaining + 1f) / 2f;
                        num5 *= (1f - Main.windSpeedTarget + 1f) / 2f;
                        if (Main.rand.Next((int)num5) == 0)
{
                            Main.NewLightning(false, false);
                        }
                    }
                    else if ((double)Main.GraveyardVisualIntensity >= 0.9)
                    {
                        int num6 = 120;
                        if (Main.rand.Next(num6) == 0)
{
                            Main.NewLightning(false, false);
                        }
                    }
                }
            }
            float num7 = 0.8f;
            float num8 = 0.0003f;
            float num9 = Main.windSpeedTarget * (1f + 0.5555556f * Main.maxRaining);
            num8 += Math.Abs(num9 - Main.windSpeedCurrent) * 0.0015f;
            if (Main.windSpeedCurrent < num9)
            {
                Main.windSpeedCurrent += num8;
                if (Main.windSpeedCurrent > num9)
                {
                    Main.windSpeedCurrent = num9;
                }
            }
            else if (Main.windSpeedCurrent > num9)
            {
                Main.windSpeedCurrent -= num8;
                if (Main.windSpeedCurrent < num9)
                {
                    Main.windSpeedCurrent = num9;
                }
            }
            if (Main.netMode == 1)
            {
                return;
            }
            if (Main.netMode != 2 && Main.gameMenu)
            {
                return;
            }
            if (!CreativePowerManager.Instance.GetPower<CreativePowers.FreezeWindDirectionAndStrength>().Enabled)
            {
                if (LanternNight.LanternsUp)
                {
                    return;
                }
                Main.windCounter--;
                if (Main.windCounter <= 0)
                {
                    bool flag = false;
                    for (int i = 0; i < 255; i++)
                    {
                        if (Main.player[i].active && Main.player[i].statLifeMax >= 120)
{
                            flag = true;
                            break;
                        }
                    }
                    float num10 = 1f;
                    if (Main.windSpeedTarget < 0f)
                    {
                        num10 = -1f;
                    }
                    if (Main.rand.Next(4) == 0)
                    {
                        Main.windSpeedTarget += (float)Main.rand.Next(-25, 26) * 0.001f;
                    }
                    else if (Main.rand.Next(2) == 0)
                    {
                        Main.windSpeedTarget += (float)Main.rand.Next(-50, 51) * 0.001f;
                    }
                    else
                    {
                        Main.windSpeedTarget += (float)Main.rand.Next(-100, 101) * 0.001f;
                    }
                    if (!flag && Math.Abs(Main.windSpeedTarget) > 0.35f)
                    {
                        Main.windSpeedTarget = 0.35f * (float)Math.Sign(Main.windSpeedTarget);
                    }
                    Main.extremeWindCounter--;
                    if (Main.extremeWindCounter <= 0)
                    {
                        Main.ResetWindCounter(true);
                        if (Main.rand.Next(30) < 13)
{
                            if (Main.rand.Next(2) == 0)
{
                                Main.windSpeedTarget = 0f;
                                Main.windCounter = Main.rand.Next(7200, 28801);
                            }
                            else
{
                                Main.windSpeedTarget = (float)Main.rand.Next(-200, 201) * 0.001f;
                            }
                        }
                        else if (Main.rand.Next(20) < 13)
{
                            Main.windSpeedTarget = (float)Main.rand.Next(-400, 401) * 0.001f;
                        }
                        else
{
                            Main.windSpeedTarget = (float)Main.rand.Next(-850, 851) * 0.001f;
                        }
                        if (!flag && Math.Abs(Main.windSpeedTarget) > 0.35f)
{
                            Main.windSpeedTarget = 0.35f * (float)Math.Sign(Main.windSpeedTarget);
                        }
                        if ((double)Math.Abs(Main.windSpeedTarget) > 0.3)
{
                            Main.extremeWindCounter += Main.rand.Next(5, 11);
                        }
                        if ((double)Math.Abs(Main.windSpeedTarget) > 0.5)
{
                            Main.extremeWindCounter += Main.rand.Next(10, 21);
                        }
                        if ((double)Math.Abs(Main.windSpeedTarget) > 0.7)
{
                            Main.extremeWindCounter += Main.rand.Next(15, 31);
                        }
                    }
                    else
                    {
                        Main.ResetWindCounter(false);
                    }
                    if (Main.rand.Next(3) != 0 && ((num10 < 0f && Main.windSpeedTarget > 0f) || (num10 > 0f && Main.windSpeedTarget < 0f)))
                    {
                        Main.windSpeedTarget *= -1f;
                    }
                }
                if (Main.windSpeedTarget > num7)
                {
                    Main.windSpeedTarget = num7;
                }
                if (Main.windSpeedTarget < -num7)
                {
                    Main.windSpeedTarget = -num7;
                }
            }
            if (Main.rand.Next(60) == 0)
            {
                Main.numCloudsTemp += Main.rand.Next(-1, 2);
            }
            if ((float)Main.rand.Next(1000) < 50f * Main.cloudBGAlpha)
            {
                Main.numCloudsTemp++;
            }
            if ((float)Main.rand.Next(1300) < 25f * (1f - Main.cloudBGAlpha))
            {
                Main.numCloudsTemp--;
            }
            if ((float)Main.rand.Next(1000) < 200f * Main.cloudAlpha && Main.numCloudsTemp < 100)
            {
                Main.numCloudsTemp++;
            }
            if ((float)Main.rand.Next(1000) < 50f * Main.cloudAlpha)
            {
                Main.numCloudsTemp++;
            }
            if (Main.numCloudsTemp > 66 && Main.rand.Next(100) == 0)
            {
                Main.numCloudsTemp -= Main.rand.Next(1, 3);
            }
            if (Main.numCloudsTemp < 50 && Main.rand.Next(100) == 0)
            {
                Main.numCloudsTemp += Main.rand.Next(1, 3);
            }
            if (Main.cloudBGActive <= 0f && Main.numCloudsTemp > 100 && Main.cloudAlpha == 0f)
            {
                Main.numCloudsTemp = 100;
            }
            if (Main.numCloudsTemp < -20)
            {
                Main.numCloudsTemp = -20;
            }
            if (Main.cloudAlpha > 0f && (float)Main.numClouds < 200f * Main.cloudAlpha)
            {
                while ((float)Main.numClouds < 200f * Main.cloudAlpha)
                {
                    Main.numClouds += Main.rand.Next(30);
                    if (Main.numClouds > 200)
                    {
                        Main.numClouds = 200;
                    }
                    if (Main.numCloudsTemp < Main.numClouds)
                    {
                        Main.numCloudsTemp = Main.numClouds;
                    }
                }
                if (Main.netMode == 2)
                {
                    NetMessage.SendData(7, -1, -1, null, 0, 0f, 0f, 0f, 0, 0, 0);
                }
            }
            Main.weatherCounter--;
            if (Main.weatherCounter <= 0)
            {
                if (Main.rand.Next(2) == 0)
                {
                    if (Main.rand.Next(2) == 0)
                    {
                        Main.numCloudsTemp += Main.rand.Next(250);
                    }
                    else
                    {
                        Main.numCloudsTemp += Main.rand.Next(100);
                    }
                }
                if (Main.numCloudsTemp < 0)
                {
                    Main.numCloudsTemp = 0;
                }
                if (Main.numCloudsTemp > 200)
                {
                    Main.numCloudsTemp = 200;
                }
                Main.numClouds = Main.numCloudsTemp;
                Main.weatherCounter = Main.rand.Next(3600, 10800);
                if (Main.netMode == 2)
                {
                    NetMessage.SendData(7, -1, -1, null, 0, 0f, 0f, 0f, 0, 0, 0);
                }
            }
        }
References System.Math.Abs(), Terraria.Player.active, Terraria.SceneMetrics.Center, Terraria.Main.cloudAlpha, Terraria.Main.cloudBGActive, Terraria.Main.cloudBGAlpha, Terraria.GameContent.Creative.CreativePowers.ASharedTogglePower.Enabled, Terraria.Main.extremeWindCounter, Terraria.Main.gameMenu, Terraria.Main.GetAreaToLight(), Terraria.GameContent.Creative.CreativePowerManager.Instance, int, Terraria.Main.IsItStorming, Terraria.GameContent.Events.LanternNight.LanternsUp, Terraria.Main.lightning, Terraria.Main.lightningDecay, Terraria.Main.lightningSpeed, Terraria.Lighting.LightTiles(), Terraria.Main.maxRaining, Terraria.Main.netMode, Terraria.Main.NewLightning(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.numClouds, Terraria.Main.numCloudsTemp, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.rand, Terraria.Main.remixWorld, Terraria.Main.ResetWindCounter(), Terraria.Main.SceneMetrics, Terraria.NetMessage.SendData(), System.Math.Sign(), Terraria.Player.statLifeMax, Terraria.Main.thunderDelay, Terraria.Main.thunderDistance, Terraria.Main.thunderSkipSound, Terraria.FocusHelper.UpdateBackgroundThunder, Terraria.Main.weatherCounter, Terraria.Main.windCounter, Terraria.Main.windSpeedCurrent, Terraria.Main.windSpeedTarget, Terraria.Main.worldSurface, and Microsoft.Xna.Framework.Vector2.Y.