Terraria Decompiled: Terraria.Main.SortStardustDragonProjectiles
SortStardustDragonProjectiles()
void Terraria.Main.SortStardustDragonProjectiles (List< int > list) inline private
Definition at line 37750 of file Main.cs.
        {
            List<List<int>> list2 = new List<List<int>>();
            for (int i = 0; i < list.Count; i++)
            {
                int num = list[i];
                if (Main.projectile[num].type == 628)
                {
                    list.Remove(num);
                    List<int> list3 = new List<int>();
                    list3.Insert(0, num);
                    int num2 = Projectile.GetByUUID(Main.projectile[num].owner, Main.projectile[num].ai[0]);
                    while (num2 >= 0 && !list3.Contains(num2) && Main.projectile[num2].active && Main.projectile[num2].type >= 625 && Main.projectile[num2].type <= 627)
                    {
                        list3.Add(num2);
                        list.Remove(num2);
                        num2 = Projectile.GetByUUID(Main.projectile[num2].owner, Main.projectile[num2].ai[0]);
                    }
                    List<int> list4 = new List<int>();
                    for (int j = list3.Count - 2; j >= 0; j--)
                    {
                        list4.Add(list3[j]);
                    }
                    list4.Add(list3[list3.Count - 1]);
                    list2.Add(list4);
                    i = -1;
                }
            }
            List<int> list5 = new List<int>(list);
            list2.Add(list5);
            list.Clear();
            for (int k = 0; k < list2.Count; k++)
            {
                for (int l = 0; l < list2[k].Count; l++)
                {
                    list.Add(list2[k][l]);
                }
            }
            for (int m = 0; m < list.Count; m++)
            {
                Projectile projectile = Main.projectile[list[m]];
                int byUUID = Projectile.GetByUUID(projectile.owner, projectile.ai[0]);
                if (projectile.type >= 626 && projectile.type <= 628 && byUUID >= 0 && ProjectileID.Sets.StardustDragon[Main.projectile[byUUID].type])
                {
                    Vector2 vector = Main.projectile[byUUID].Center - projectile.Center;
                    if (vector != Vector2.Zero)
                    {
                        float num3 = Main.projectile[byUUID].scale * 16f;
                        float num4 = vector.Length();
                        float num5 = num3 - num4;
                        if (num5 != 0f)
{
                            projectile.Center += Vector2.Normalize(vector) * -num5;
                        }
                    }
                }
            }
        }
References Terraria.Projectile.active, System.Collections.Generic.List< T >.Add(), Terraria.Projectile.ai, Terraria.Entity.Center, System.Collections.Generic.List< T >.Contains(), System.Collections.Generic.List< T >.Count, Terraria.Projectile.GetByUUID(), System.Collections.Generic.List< T >.Insert(), Microsoft.Xna.Framework.Vector2.Length(), System.list, Microsoft.Xna.Framework.Vector2.Normalize(), Terraria.Projectile.owner, Terraria.Main.projectile, System.Collections.Generic.List< T >.Remove(), Terraria.Projectile.scale, Terraria.ID.ProjectileID.Sets.StardustDragon, Terraria.Projectile.type, and Microsoft.Xna.Framework.Vector2.Zero.