Terraria Decompiled: Terraria.Main.TryGetAmmo
TryGetAmmo()
bool Terraria.Main.TryGetAmmo (Item sourceItem, out Item ammoItem, out Microsoft::Xna::Framework::Color ammoColor, out float ammoScale, out Vector2 ammoOffset) inline private
Definition at line 45232 of file Main.cs.
        {
            ammoItem = null;
            ammoColor = Microsoft.Xna.Framework.Color.White;
            ammoScale = 0.8f;
            ammoOffset = Vector2.Zero;
            int type = sourceItem.type;
            if (type == 1071 || type == 1543 || type == 1072 || type == 1544)
            {
                int num = 22;
                int num2 = 22;
                if (type == 1072 || type == 1544)
                {
                    num = 28;
                    num2 = 28;
                }
                ammoOffset = new Vector2((float)num, (float)num2);
                ammoItem = Main.player[Main.myPlayer].FindPaintOrCoating();
                return ammoItem != null;
            }
            FlexibleTileWand flexibleTileWand = sourceItem.GetFlexibleTileWand();
            FlexibleTileWand.PlacementOption placementOption;
            if (flexibleTileWand != null && flexibleTileWand.ShowsHoverAmmoIcon && flexibleTileWand.TryGetPlacementOption(Main.LocalPlayer, Player.FlexibleWandRandomSeed, Player.FlexibleWandCycleOffset, out placementOption, out ammoItem))
            {
                ammoOffset = new Vector2(28f, 28f);
                return true;
            }
            return false;
        }
References Terraria.Player.FindPaintOrCoating(), Terraria.Player.FlexibleWandCycleOffset, Terraria.Player.FlexibleWandRandomSeed, Terraria.Item.GetFlexibleTileWand(), Terraria.Main.LocalPlayer, Terraria.Main.myPlayer, Terraria.Main.player, Terraria.GameContent.FlexibleTileWand.ShowsHoverAmmoIcon, Terraria.GameContent.FlexibleTileWand.TryGetPlacementOption(), Terraria.Item.type, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Color.White, and Microsoft.Xna.Framework.Vector2.Zero.