Terraria Decompiled: Terraria.Main.InitTargets
InitTargets()
void Terraria.Main.InitTargets () inline protected
Definition at line 58918 of file Main.cs.
        {
            if (!Main.PreventUpdatingTargets)
            {
                this.UpdateDisplaySettings();
            }
            this.ReleaseTargets();
            int num = Main.MaxWorldViewSize.X;
            Microsoft.Xna.Framework.Point maxWorldViewSize = Main.MaxWorldViewSize;
            if (Main.SupportWideScreen && Main._selectedGraphicsProfile == GraphicsProfile.HiDef)
            {
                num = 4096;
            }
            int num2 = Math.Min(base.GraphicsDevice.PresentationParameters.BackBufferWidth, num);
            int num3 = Math.Min(base.GraphicsDevice.PresentationParameters.BackBufferHeight, num);
            Main.offScreenRange = 192;
            if (num2 + Main.offScreenRange * 2 > Main._renderTargetMaxSize)
            {
                Main.offScreenRange = (Main._renderTargetMaxSize - num2) / 2;
            }
            num2 += Main.offScreenRange * 2;
            num3 += Main.offScreenRange * 2;
            try
            {
                if (!Main.dedServ)
                {
                    Main.targetSet = true;
                    Main.waterTarget = new WorldSceneLayerTarget(base.GraphicsDevice, num2, num3);
                    Main.backWaterTarget = new WorldSceneLayerTarget(base.GraphicsDevice, num2, num3);
                    Main.tileTarget = new WorldSceneLayerTarget(base.GraphicsDevice, num2, num3);
                    Main.tile2Target = new WorldSceneLayerTarget(base.GraphicsDevice, num2, num3);
                    Main.wallTarget = new WorldSceneLayerTarget(base.GraphicsDevice, num2, num3);
                    Main.backgroundTarget = new WorldSceneLayerTarget(base.GraphicsDevice, num2, num3);
                    Main.backgroundTargetSwap = new WorldSceneLayerTarget(base.GraphicsDevice, num2, num3);
                    Main.skyTarget = new RenderTarget2D(base.GraphicsDevice, base.GraphicsDevice.PresentationParameters.BackBufferWidth, base.GraphicsDevice.PresentationParameters.BackBufferHeight, false, base.GraphicsDevice.PresentationParameters.BackBufferFormat, DepthFormat.None);
                    Main.screenTarget = new RenderTarget2D(base.GraphicsDevice, base.GraphicsDevice.PresentationParameters.BackBufferWidth, base.GraphicsDevice.PresentationParameters.BackBufferHeight, false, base.GraphicsDevice.PresentationParameters.BackBufferFormat, DepthFormat.None);
                    Main.screenTargetSwap = new RenderTarget2D(base.GraphicsDevice, base.GraphicsDevice.PresentationParameters.BackBufferWidth, base.GraphicsDevice.PresentationParameters.BackBufferHeight, false, base.GraphicsDevice.PresentationParameters.BackBufferFormat, DepthFormat.None);
                    if (Main.OnRenderTargetsInitialized != null)
                    {
                        Main.OnRenderTargetsInitialized(base.GraphicsDevice.PresentationParameters.BackBufferWidth, base.GraphicsDevice.PresentationParameters.BackBufferHeight);
                    }
                }
            }
            catch
            {
                Lighting.Mode = LightMode.Retro;
                Main.mapEnabled = false;
                Main.SaveSettings();
                try
                {
                    this.ReleaseTargets();
                }
                catch
                {
                }
            }
        }
References Terraria.Main._renderTargetMaxSize, Terraria.Main._selectedGraphicsProfile, Terraria.Main.dedServ, Terraria.Main.MaxWorldViewSize, System.Math.Min(), Terraria.Main.offScreenRange, Terraria.Main.OnRenderTargetsInitialized, Terraria.Main.PreventUpdatingTargets, Terraria.Main.SaveSettings(), and Terraria.Main.SupportWideScreen.
Referenced by Terraria.Main.SetDisplayMode().