Terraria Decompiled: Terraria.Main.DrawCachedProjs
DrawCachedProjs()
void Terraria.Main.DrawCachedProjs (List< int > projCache, bool startSpriteBatch = true) inline package
Definition at line 37634 of file Main.cs.
        {
            TimeLogger.StartTimestamp startTimestamp = TimeLogger.Start();
            if (startSpriteBatch)
            {
                Main.spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, Main.DefaultSamplerState, DepthStencilState.None, Main.Rasterizer, null, Main.Transform);
            }
            Main.CurrentDrawnEntity = null;
            Main.CurrentDrawnEntityShader = 0;
            for (int i = 0; i < projCache.Count; i++)
            {
                try
                {
                    this.DrawProj(projCache[i]);
                }
                catch (Exception ex)
                {
                    TimeLogger.DrawException(ex);
                    Main.projectile[projCache[i]].active = false;
                }
            }
            Main.CurrentDrawnEntity = null;
            Main.CurrentDrawnEntityShader = 0;
            if (startSpriteBatch)
            {
                Main.spriteBatch.End();
            }
            TimeLogger.Projectiles.AddTime(startTimestamp);
        }
References Terraria.Projectile.active, Microsoft.Xna.Framework.Graphics.BlendState.AlphaBlend, Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(), System.Collections.Generic.List< T >.Count, Terraria.Main.DefaultSamplerState, Terraria.TimeLogger.DrawException(), Microsoft.Xna.Framework.Graphics.SpriteBatch.End(), Microsoft.Xna.Framework.Graphics.DepthStencilState.None, Terraria.Main.projectile, Terraria.TimeLogger.Projectiles, Terraria.Main.Rasterizer, Terraria.Main.spriteBatch, Terraria.TimeLogger.Start(), and Terraria.Main.Transform.