Terraria Decompiled: Terraria.Main.CheckForMoonEventsScoreDisplay
CheckForMoonEventsScoreDisplay()
static void Terraria.Main.CheckForMoonEventsScoreDisplay () inline static
Definition at line 9067 of file Main.cs.
        {
            if (Main.netMode == 1)
            {
                return;
            }
            if (!Main.pumpkinMoon && !Main.snowMoon)
            {
                return;
            }
            Microsoft.Xna.Framework.Color bossOrEvent = ChatColors.BossOrEvent;
            string text = "Misc.PumpkinMoonScore";
            if (Main.snowMoon)
            {
                text = "Misc.FrostMoonScore";
            }
            WorldGen.BroadcastText(NetworkText.FromKey(text, new object[] { NPC.totalInvasionPoints }), bossOrEvent);
        }
References Terraria.Chat.ChatColors.BossOrEvent, Terraria.WorldGen.BroadcastText(), Terraria.Localization.NetworkText.FromKey(), Terraria.Main.netMode, Terraria.Main.pumpkinMoon, Terraria.Main.snowMoon, and System.text.
Referenced by Terraria.Main.UpdateTime_StartDay().