Terraria Decompiled: Terraria.Main.DrawInfernoRings
DrawInfernoRings()
void Terraria.Main.DrawInfernoRings () inline
Definition at line 65446 of file Main.cs.
        {
            bool allowPlayerToEmitEffects = FocusHelper.AllowPlayerToEmitEffects;
            for (int i = 0; i < 255; i++)
            {
                if (Main.player[i].active && !Main.player[i].outOfRange && Main.player[i].inferno && !Main.player[i].dead)
                {
                    this.LoadFlameRing();
                    float num = 0.1f;
                    float num2 = 0.9f;
                    if (allowPlayerToEmitEffects)
                    {
                        Main.player[i].flameRingScale += 0.004f;
                    }
                    float num3;
                    if (Main.player[i].flameRingScale < 1f)
                    {
                        num3 = Main.player[i].flameRingScale;
                    }
                    else
                    {
                        Main.player[i].flameRingScale = 0.8f;
                        num3 = Main.player[i].flameRingScale;
                    }
                    if (allowPlayerToEmitEffects)
                    {
                        Main.player[i].flameRingRot += 0.05f;
                    }
                    if (Main.player[i].flameRingRot > 6.2831855f)
                    {
                        Main.player[i].flameRingRot -= 6.2831855f;
                    }
                    if (Main.player[i].flameRingRot < -6.2831855f)
                    {
                        Main.player[i].flameRingRot += 6.2831855f;
                    }
                    for (int j = 0; j < 3; j++)
                    {
                        float num4 = num3 + num * (float)j;
                        if (num4 > 1f)
{
                            num4 -= num * 2f;
                        }
                        float num5 = MathHelper.Lerp(0.8f, 0f, Math.Abs(num4 - num2) * 10f);
                        Main.spriteBatch.Draw(TextureAssets.FlameRing.Value, Main.player[i].Center - Main.screenPosition, new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 400 * j, 400, 400)), new Microsoft.Xna.Framework.Color(num5, num5, num5, num5 / 2f), Main.player[i].flameRingRot + 1.0471976f * (float)j, new Vector2(200f, 200f), num4, SpriteEffects.None, 0f);
                    }
                }
            }
        }
References System.Math.Abs(), Terraria.Player.active, Terraria.FocusHelper.AllowPlayerToEmitEffects, Terraria.Entity.Center, Terraria.Player.dead, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.GameContent.TextureAssets.FlameRing, Terraria.Player.flameRingRot, Terraria.Player.flameRingScale, Terraria.Player.inferno, Microsoft.Xna.Framework.MathHelper.Lerp(), Terraria.Player.outOfRange, Terraria.Main.player, Terraria.Main.screenPosition, Terraria.Main.spriteBatch, ReLogic.Content.Asset< T >.Value, and Microsoft.Xna.Framework.Graphics.Vector2.