Terraria Decompiled: Terraria.Main.DrawNPCChatBottomRightItem
DrawNPCChatBottomRightItem()
static void Terraria.Main.DrawNPCChatBottomRightItem (Vector2 bottomRight) inline static
Definition at line 39451 of file Main.cs.
        {
            if (Main.npcChatCornerItem > 0)
            {
                bottomRight -= Vector2.One * 8f;
                Item item = new Item();
                item.SetDefaults(Main.npcChatCornerItem, null);
                float num = 1f;
                Texture2D texture2D;
                Microsoft.Xna.Framework.Rectangle rectangle;
                Main.GetItemDrawFrame(item.type, out texture2D, out rectangle);
                if (rectangle.Width > 32 || rectangle.Height > 32)
                {
                    if (rectangle.Width > rectangle.Height)
                    {
                        num = 32f / (float)rectangle.Width;
                    }
                    else
                    {
                        num = 32f / (float)rectangle.Height;
                    }
                }
                Main.spriteBatch.Draw(texture2D, bottomRight, new Microsoft.Xna.Framework.Rectangle?(rectangle), item.GetAlpha(Microsoft.Xna.Framework.Color.White), 0f, rectangle.Size(), num, SpriteEffects.None, 0f);
                if (item.color != default(Microsoft.Xna.Framework.Color))
                {
                    Main.spriteBatch.Draw(texture2D, bottomRight, new Microsoft.Xna.Framework.Rectangle?(rectangle), item.GetColor(item.color), 0f, rectangle.Size(), num, SpriteEffects.None, 0f);
                }
                if (new Microsoft.Xna.Framework.Rectangle((int)bottomRight.X - (int)((float)rectangle.Width * num), (int)bottomRight.Y - (int)((float)rectangle.Height * num), (int)((float)rectangle.Width * num), (int)((float)rectangle.Height * num)).Contains(new Microsoft.Xna.Framework.Point(Main.mouseX, Main.mouseY)))
                {
                    Main.cursorOverride = 2;
                    if (Main.mouseLeftRelease && Main.mouseLeft)
                    {
                        if (!Main.drawingPlayerChat)
{
                            Main.OpenPlayerChat();
                        }
                        if (ChatManager.AddChatText(FontAssets.MouseText.Value, ItemTagHandler.GenerateTag(item), Vector2.One))
{
                            SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                        }
                    }
                    Main.instance.MouseText(item.Name, -11, 0, -1, -1, -1, -1, 0);
                    return;
                }
            }
            else if (Main.npcChatCornerItem == -1)
            {
                bottomRight -= Vector2.One * 12f;
                Texture2D value = TextureAssets.EquipPage[5].Value;
                float num2 = 1f;
                Microsoft.Xna.Framework.Rectangle rectangle2 = value.Frame(1, 1, 0, 0, 0, 0);
                if (rectangle2.Width > 32 || rectangle2.Height > 32)
                {
                    if (rectangle2.Width > rectangle2.Height)
                    {
                        num2 = 32f / (float)rectangle2.Width;
                    }
                    else
                    {
                        num2 = 32f / (float)rectangle2.Height;
                    }
                }
                Microsoft.Xna.Framework.Color white = Microsoft.Xna.Framework.Color.White;
                if (new Microsoft.Xna.Framework.Rectangle((int)bottomRight.X - (int)((float)rectangle2.Width * num2), (int)bottomRight.Y - (int)((float)rectangle2.Height * num2), (int)((float)rectangle2.Width * num2), (int)((float)rectangle2.Height * num2)).Contains(new Microsoft.Xna.Framework.Point(Main.mouseX, Main.mouseY)))
                {
                    Main.spriteBatch.Draw(TextureAssets.EquipPage[7].Value, bottomRight, null, Main.OurFavoriteColor, 0f, rectangle2.Size() + new Vector2(2f), num2, SpriteEffects.None, 0f);
                    if (Main.mouseLeftRelease && Main.mouseLeft)
                    {
                        Main.CloseNPCChatOrSign(true);
                        Player.OpenInventory(false);
                        Main.EquipPageSelected = 1;
                    }
                }
                Main.spriteBatch.Draw(value, bottomRight, new Microsoft.Xna.Framework.Rectangle?(rectangle2), Microsoft.Xna.Framework.Color.White, 0f, rectangle2.Size(), num2, SpriteEffects.None, 0f);
            }
        }
References Terraria.UI.Chat.ChatManager.AddChatText(), Terraria.Main.CloseNPCChatOrSign(), Microsoft.Xna.Framework.Rectangle.Contains(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Main.drawingPlayerChat, Terraria.GameContent.TextureAssets.EquipPage, Terraria.GameContent.UI.Chat.ItemTagHandler.GenerateTag(), Terraria.Main.GetItemDrawFrame(), Microsoft.Xna.Framework.Rectangle.Height, Terraria.Main.instance, System.item, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.MouseText(), Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.npcChatCornerItem, Microsoft.Xna.Framework.Vector2.One, Terraria.Player.OpenInventory(), Terraria.Main.OpenPlayerChat(), Terraria.Main.OurFavoriteColor, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.spriteBatch, System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Rectangle.Width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.GameContent.UI.NPCChatPanel.Draw().