Terraria Decompiled: Terraria.Main.tileFrameImportant
tileFrameImportant
bool [] Terraria.Main.tileFrameImportant = new bool[(int)TileID.Count] static
Definition at line 69937 of file Main.cs.
Referenced by Terraria.Main.AddEchoFurnitureTile(), Terraria.NPC.AI_110_Betsy(), Terraria.Projectile.AI_135_OgreStomp(), Terraria.NetMessage.CompressTileBlock_Inner(), Terraria.WorldGen.Convert(), Terraria.Projectile.CreateGroundExplosion(), Terraria.Projectile.CreateImpactExplosion(), Terraria.NetMessage.DecompressTileBlock_Inner(), Terraria.WorldGen.SecretSeed.DoActuallyNoTraps(), Terraria.WorldGen.SecretSeed.DoErrorWorldFinish(), Terraria.WorldGen.SecretSeed.DoErrorWorldGetRandomBlock(), Terraria.WorldGen.SecretSeed.DoErrorWorldShuffleBlocks(), Terraria.GameContent.Biomes.DeadMansChestBiome.FindDartTrapSpotSingle(), Terraria.GameContent.Creative.ItemFilters.BuildingBlock.FitsFilter(), Terraria.GameContent.Creative.ItemFilters.Furniture.FitsFilter(), Terraria.GameContent.Creative.SortingSteps.Blocks.FitsFilter(), Terraria.GameContent.Creative.SortingSteps.PlaceableObjects.FitsFilter(), Terraria.Utilities.TileSnapshot.TileStruct.From(), Terraria.GameContent.Drawing.WallDrawing.FullTile(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateDungeonStairs_CanPlaceTile(), Terraria.MessageBuffer.GetData(), Terraria.Testing.DebugUtils.GetTileDescription(), Terraria.Main.Initialize_TileAndNPCData1(), Terraria.Main.Initialize_TileAndNPCData2(), Terraria.GameContent.Biomes.DeadMansChestBiome.IsGoodSpotsForExplosive(), Terraria.Tile.isTheSameAs(), Terraria.IO.WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), Terraria.GameContent.Biomes.DeadMansChestBiome.PlaceBoulderTrapSpot(), Terraria.Player.PlaceThing_Tiles_PlaceIt_AutoPaintAndActuate(), Terraria.Player.PlaceThing_ValidTileForReplacement(), Terraria.WorldGen.PlaceTile(), Terraria.WorldGen.ReplaceTile_IsValidSolid(), Terraria.IO.WorldFile.SaveFileFormatHeader(), Terraria.IO.WorldFile.SaveWorldTiles(), Terraria.NetMessage.SendData(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsDownDashExplosion(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsFlint(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalSpikes.Spikes_CanSupportSpike(), Terraria.GameContent.SmartCursorHelper.Step_BlocksFilling(), Terraria.GameContent.SmartCursorHelper.Step_BlocksLines(), Terraria.WorldGen.TileFrame(), Terraria.WorldGen.TileFrameCosmetic(), Terraria.WorldGen.TileRunner(), and Terraria.Utilities.TileSnapshot.TileStruct.ToString().