Terraria Decompiled: Terraria.Main.DrawBuilderAccToggles
DrawBuilderAccToggles()
void Terraria.Main.DrawBuilderAccToggles (Vector2 start) inline private
Definition at line 47641 of file Main.cs.
        {
            if (!Main.playerInventory)
            {
                return;
            }
            int num = -1;
            string.IsNullOrEmpty(Main.npcChatText);
            if (false || Main.player[Main.myPlayer].sign >= 0)
            {
                return;
            }
            int num2 = 0;
            Player player = Main.player[Main.myPlayer];
            int[] builderAccStatus = Main.player[Main.myPlayer].builderAccStatus;
            int num3;
            int num4;
            int num5;
            Main.GetBuilderAccsCountToShow(player, out num3, out num4, out num5);
            start.Y += (float)(24 * num4);
            bool flag = num5 >= 10;
            int num6 = 10;
            int i = 0;
            while (i < num6)
            {
                int num7 = i - 2;
                if (i == 0)
                {
                    num7 = 8;
                }
                else if (i == 1)
                {
                    num7 = 9;
                }
                Texture2D value = TextureAssets.BuilderAcc.Value;
                Microsoft.Xna.Framework.Rectangle rectangle = new Microsoft.Xna.Framework.Rectangle(0, 16, 14, 14);
                Microsoft.Xna.Framework.Color color = Microsoft.Xna.Framework.Color.White;
                Microsoft.Xna.Framework.Color color2 = new Microsoft.Xna.Framework.Color(127, 127, 127);
                Vector2 vector = start + new Vector2(0f, (float)(num2 * 24));
                if (flag)
                {
                    vector.Y -= 24f;
                }
                bool flag2 = Utils.CenteredRectangle(vector, new Vector2(14f)).Contains(Main.MouseScreen.ToPoint()) && !PlayerInput.IgnoreMouseInterface;
                bool flag3 = flag2 && Main.mouseLeft && Main.mouseLeftRelease;
                switch (num7)
                {
                case 0:
                    if (player.rulerLine)
                    {
                        rectangle.X = num7 * 16;
                        color = ((builderAccStatus[num7] == 0) ? color : color2);
                        if (flag2)
{
                            player.mouseInterface = true;
                            this.MouseTextNoOverride((builderAccStatus[num7] == 0) ? Language.GetTextValue("GameUI.RulerOn") : Language.GetTextValue("GameUI.RulerOff"), 0, 0, -1, -1, -1, -1, 0);
                            Main.mouseText = true;
                        }
                        if (flag3)
{
                            builderAccStatus[num7] = ((builderAccStatus[num7] == 0) ? 1 : 0);
                            SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                            Main.mouseLeftRelease = false;
                            goto IL_05FD;
                        }
                        goto IL_05FD;
                    }
                    break;
                case 1:
                    if (player.rulerGrid)
                    {
                        rectangle.X = num7 * 16;
                        color = ((builderAccStatus[num7] == 0) ? color : color2);
                        if (flag2)
{
                            player.mouseInterface = true;
                            this.MouseTextNoOverride((builderAccStatus[num7] == 0) ? Language.GetTextValue("GameUI.MechanicalRulerOn") : Language.GetTextValue("GameUI.MechanicalRulerOff"), 0, 0, -1, -1, -1, -1, 0);
                            Main.mouseText = true;
                        }
                        if (flag3)
{
                            builderAccStatus[num7] = ((builderAccStatus[num7] == 0) ? 1 : 0);
                            SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                            Main.mouseLeftRelease = false;
                            goto IL_05FD;
                        }
                        goto IL_05FD;
                    }
                    break;
                case 2:
                    if (player.autoActuator)
                    {
                        rectangle.X = num7 * 16;
                        color = ((builderAccStatus[num7] == 0) ? color : color2);
                        if (flag2)
{
                            player.mouseInterface = true;
                            this.MouseTextNoOverride((builderAccStatus[num7] == 0) ? Language.GetTextValue("GameUI.ActuationDeviceOn") : Language.GetTextValue("GameUI.ActuationDeviceOff"), 0, 0, -1, -1, -1, -1, 0);
                            Main.mouseText = true;
                        }
                        if (flag3)
{
                            builderAccStatus[num7] = ((builderAccStatus[num7] == 0) ? 1 : 0);
                            SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                            Main.mouseLeftRelease = false;
                            goto IL_05FD;
                        }
                        goto IL_05FD;
                    }
                    break;
                case 3:
                    if (player.autoPaint)
                    {
                        rectangle.X = num7 * 16;
                        color = ((builderAccStatus[num7] == 0) ? color : color2);
                        if (flag2)
{
                            player.mouseInterface = true;
                            this.MouseTextNoOverride((builderAccStatus[num7] == 0) ? Language.GetTextValue("GameUI.PaintSprayerOn") : Language.GetTextValue("GameUI.PaintSprayerOff"), 0, 0, -1, -1, -1, -1, 0);
                            Main.mouseText = true;
                        }
                        if (flag3)
{
                            builderAccStatus[num7] = ((builderAccStatus[num7] == 0) ? 1 : 0);
                            SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                            Main.mouseLeftRelease = false;
                            goto IL_05FD;
                        }
                        goto IL_05FD;
                    }
                    break;
                case 4:
                case 5:
                case 6:
                case 7:
                case 9:
                    if (player.InfoAccMechShowWires)
                    {
                        rectangle.X = num7 * 16;
                        color = ((builderAccStatus[num7] == 0) ? color : ((builderAccStatus[num7] == 1) ? color2 : ((builderAccStatus[num7] == 2) ? color2.MultiplyRGBA(new Microsoft.Xna.Framework.Color(0.66f, 0.66f, 0.66f, 0.66f)) : color2.MultiplyRGBA(new Microsoft.Xna.Framework.Color(0.33f, 0.33f, 0.33f, 0.33f)))));
                        if (flag2)
{
                            player.mouseInterface = true;
                            string text = "";
                            switch (num7)
{
                            case 4:
                                text = Language.GetTextValue("Game.RedWires");
                                break;
                            case 5:
                                text = Language.GetTextValue("Game.BlueWires");
                                break;
                            case 6:
                                text = Language.GetTextValue("Game.GreenWires");
                                break;
                            case 7:
                                text = Language.GetTextValue("Game.YellowWires");
                                break;
                            case 9:
                                text = Language.GetTextValue("Game.Actuators");
                                break;
                            }
                            string text2 = "";
                            switch (builderAccStatus[num7])
{
                            case 0:
                                text2 = Language.GetTextValue("GameUI.Bright");
                                break;
                            case 1:
                                text2 = Language.GetTextValue("GameUI.Normal");
                                break;
                            case 2:
                                text2 = Language.GetTextValue("GameUI.Faded");
                                break;
                            case 3:
                                text2 = Language.GetTextValue("GameUI.Hidden");
                                break;
                            }
                            this.MouseTextNoOverride(string.Format("{0}: {1}", text, text2), 0, 0, -1, -1, -1, -1, 0);
                            Main.mouseText = true;
                        }
                        if (flag3)
{
                            builderAccStatus[num7]++;
                            if (builderAccStatus[num7] >= 3)
{
                                builderAccStatus[num7] = 0;
                            }
                            SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                            Main.mouseLeftRelease = false;
                            goto IL_05FD;
                        }
                        goto IL_05FD;
                    }
                    break;
                case 8:
                    if (player.InfoAccMechShowWires)
                    {
                        rectangle.X = num7 * 16;
                        color = ((builderAccStatus[num7] == 0) ? color : color2);
                        if (flag2)
{
                            player.mouseInterface = true;
                            this.MouseTextNoOverride((builderAccStatus[num7] == 0) ? Language.GetTextValue("GameUI.WireModeForced") : Language.GetTextValue("GameUI.WireModeNormal"), 0, 0, -1, -1, -1, -1, 0);
                            Main.mouseText = true;
                        }
                        if (flag3)
{
                            builderAccStatus[num7] = ((builderAccStatus[num7] == 0) ? 1 : 0);
                            SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                            Main.mouseLeftRelease = false;
                            goto IL_05FD;
                        }
                        goto IL_05FD;
                    }
                    break;
                case 10:
                    goto IL_05FD;
                case 11:
                    break;
                default:
                    goto IL_05FD;
                }
                IL_06C1:
                i++;
                continue;
                IL_05FD:
                Main.spriteBatch.Draw(value, vector, new Microsoft.Xna.Framework.Rectangle?(rectangle), color, 0f, rectangle.Size() / 2f, 1f, SpriteEffects.None, 0f);
                if (flag2)
                {
                    Main.spriteBatch.Draw(TextureAssets.InfoIcon[13].Value, vector, null, Main.OurFavoriteColor, 0f, TextureAssets.InfoIcon[13].Value.Size() / 2f, 1f, SpriteEffects.None, 0f);
                }
                UILinkPointNavigator.SetPosition(6000 + num2 + num3 + num4, vector + rectangle.Size() * 0.15f);
                if (flag2)
                {
                    num = num2;
                }
                num2++;
                goto IL_06C1;
            }
            if (this.DrawBlockReplacementIcon(0, 0, flag, 0))
            {
                num = num2;
            }
            num2++;
            if (player.unlockedBiomeTorches)
            {
                if (this.DrawTorchBiomeSwapIcon(0, 0, flag, 1))
                {
                    num = num2;
                }
                num2++;
            }
            Main.DoStatefulTickSound(ref Main.toggleAccMouseOver, num);
            UILinkPointNavigator.Shortcuts.BUILDERACCCOUNT = num2;
        }
References Terraria.Player.autoActuator, Terraria.Player.autoPaint, Terraria.GameContent.TextureAssets.BuilderAcc, Terraria.Player.builderAccStatus, Terraria.Utils.CenteredRectangle(), Microsoft.Xna.Framework.Rectangle.Contains(), Terraria.Main.DoStatefulTickSound(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), System.Format, Terraria.Main.GetBuilderAccsCountToShow(), Terraria.Localization.Language.GetTextValue(), Terraria.GameInput.PlayerInput.IgnoreMouseInterface, Terraria.Player.InfoAccMechShowWires, Terraria.GameContent.TextureAssets.InfoIcon, Terraria.Main.mouseLeftRelease, Terraria.Main.MouseScreen, Terraria.Main.myPlayer, Terraria.Main.npcChatText, Terraria.Main.OurFavoriteColor, Terraria.Main.player, Terraria.Main.playerInventory, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Player.rulerGrid, Terraria.Player.rulerLine, Terraria.UI.Gamepad.UILinkPointNavigator.SetPosition(), Terraria.Player.sign, Terraria.Main.spriteBatch, System.start, System.text, Terraria.Main.toggleAccMouseOver, Terraria.Player.unlockedBiomeTorches, System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, and Microsoft.Xna.Framework.Color.White.