Terraria Decompiled: Terraria.Main.DrawHealthBar
DrawHealthBar()
void Terraria.Main.DrawHealthBar (float X, float Y, int Health, int MaxHealth, float alpha, float scale = 1f, bool noFlip = false) inline
Definition at line 20787 of file Main.cs.
        {
            if (Health <= 0)
            {
                return;
            }
            float num = (float)Health / (float)MaxHealth;
            if (num > 1f)
            {
                num = 1f;
            }
            int num2 = (int)(36f * num);
            float num3 = X - 18f * scale;
            float num4 = Y;
            if (Main.player[Main.myPlayer].gravDir == -1f && !noFlip)
            {
                num4 -= Main.screenPosition.Y;
                num4 = Main.screenPosition.Y + (float)Main.screenHeight - num4;
            }
            float num5 = 0f;
            float num6 = 255f;
            num -= 0.1f;
            float num7;
            float num8;
            if ((double)num > 0.5)
            {
                num7 = 255f;
                num8 = 255f * (1f - num) * 2f;
            }
            else
            {
                num7 = 255f * num * 2f;
                num8 = 255f;
            }
            float num9 = 0.95f;
            num8 = num8 * alpha * num9;
            num7 = num7 * alpha * num9;
            num6 = num6 * alpha * num9;
            if (num8 < 0f)
            {
                num8 = 0f;
            }
            if (num8 > 255f)
            {
                num8 = 255f;
            }
            if (num7 < 0f)
            {
                num7 = 0f;
            }
            if (num7 > 255f)
            {
                num7 = 255f;
            }
            if (num6 < 0f)
            {
                num6 = 0f;
            }
            if (num6 > 255f)
            {
                num6 = 255f;
            }
            Microsoft.Xna.Framework.Color color = new Microsoft.Xna.Framework.Color((int)((byte)num8), (int)((byte)num7), (int)((byte)num5), (int)((byte)num6));
            if (num2 < 3)
            {
                num2 = 3;
            }
            if (num2 < 34)
            {
                if (num2 < 36)
                {
                    Main.spriteBatch.Draw(TextureAssets.Hb2.Value, new Vector2(num3 - Main.screenPosition.X + (float)num2 * scale, num4 - Main.screenPosition.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(2, 0, 2, TextureAssets.Hb2.Height())), color, 0f, new Vector2(0f, 0f), scale, SpriteEffects.None, 0f);
                }
                if (num2 < 34)
                {
                    Main.spriteBatch.Draw(TextureAssets.Hb2.Value, new Vector2(num3 - Main.screenPosition.X + (float)(num2 + 2) * scale, num4 - Main.screenPosition.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(num2 + 2, 0, 36 - num2 - 2, TextureAssets.Hb2.Height())), color, 0f, new Vector2(0f, 0f), scale, SpriteEffects.None, 0f);
                }
                if (num2 > 2)
                {
                    Main.spriteBatch.Draw(TextureAssets.Hb1.Value, new Vector2(num3 - Main.screenPosition.X, num4 - Main.screenPosition.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, num2 - 2, TextureAssets.Hb1.Height())), color, 0f, new Vector2(0f, 0f), scale, SpriteEffects.None, 0f);
                }
                Main.spriteBatch.Draw(TextureAssets.Hb1.Value, new Vector2(num3 - Main.screenPosition.X + (float)(num2 - 2) * scale, num4 - Main.screenPosition.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(32, 0, 2, TextureAssets.Hb1.Height())), color, 0f, new Vector2(0f, 0f), scale, SpriteEffects.None, 0f);
                return;
            }
            if (num2 < 36)
            {
                Main.spriteBatch.Draw(TextureAssets.Hb2.Value, new Vector2(num3 - Main.screenPosition.X + (float)num2 * scale, num4 - Main.screenPosition.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(num2, 0, 36 - num2, TextureAssets.Hb2.Height())), color, 0f, new Vector2(0f, 0f), scale, SpriteEffects.None, 0f);
            }
            Main.spriteBatch.Draw(TextureAssets.Hb1.Value, new Vector2(num3 - Main.screenPosition.X, num4 - Main.screenPosition.Y), new Microsoft.Xna.Framework.Rectangle?(new Microsoft.Xna.Framework.Rectangle(0, 0, num2, TextureAssets.Hb1.Height())), color, 0f, new Vector2(0f, 0f), scale, SpriteEffects.None, 0f);
        }
References Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Player.gravDir, Terraria.GameContent.TextureAssets.Hb1, Terraria.GameContent.TextureAssets.Hb2, int, Terraria.Main.myPlayer, Terraria.Main.player, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.spriteBatch, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Input.X, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Input.Y, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.GameContent.UI.LegacyMultiplayerClosePlayersOverlay.Draw(), and Terraria.GameContent.UI.NewMultiplayerClosePlayersOverlay.PlayerOffScreenCache.DrawLifeBar().