Terraria Decompiled: Terraria.Main.DrawProj_FlailChains
DrawProj_FlailChains()
static void Terraria.Main.DrawProj_FlailChains (Projectile proj, Player theOwner, Vector2 mountedCenter) inline static private
Definition at line 34549 of file Main.cs.
        {
            Vector2 playerArmPosition = Main.GetPlayerArmPosition(proj, theOwner);
            Microsoft.Xna.Framework.Rectangle? rectangle = null;
            float num = 0f;
            int num2 = proj.type;
            Asset<Texture2D> asset;
            if (num2 <= 154)
            {
                if (num2 <= 35)
                {
                    if (num2 == 25)
                    {
                        asset = TextureAssets.Chain2;
                        goto IL_00E3;
                    }
                    if (num2 == 35)
                    {
                        asset = TextureAssets.Chain6;
                        goto IL_00E3;
                    }
                }
                else
                {
                    if (num2 == 63)
                    {
                        asset = TextureAssets.Chain7;
                        goto IL_00E3;
                    }
                    if (num2 == 154)
                    {
                        asset = TextureAssets.Chain13;
                        goto IL_00E3;
                    }
                }
            }
            else if (num2 <= 757)
            {
                if (num2 == 247)
                {
                    asset = TextureAssets.Chain19;
                    goto IL_00E3;
                }
                if (num2 == 757)
                {
                    asset = TextureAssets.Extra[99];
                    rectangle = new Microsoft.Xna.Framework.Rectangle?(asset.Frame(1, 6, 0, 0, 0, 0));
                    num = -2f;
                    goto IL_00E3;
                }
            }
            else
            {
                if (num2 == 947)
                {
                    asset = TextureAssets.Chain41;
                    goto IL_00E3;
                }
                if (num2 == 948)
                {
                    asset = TextureAssets.Chain43;
                    goto IL_00E3;
                }
            }
            asset = TextureAssets.Chain3;
            IL_00E3:
            Vector2 vector = ((rectangle != null) ? (rectangle.Value.Size() / 2f) : (asset.Size() / 2f));
            Vector2 vector2 = proj.Center;
            Vector2 vector3 = playerArmPosition.MoveTowards(vector2, 4f) - vector2;
            Vector2 vector4 = vector3.SafeNormalize(Vector2.Zero);
            float num3 = (float)((rectangle != null) ? rectangle.Value.Height : asset.Height()) + num;
            float num4 = vector4.ToRotation() + 1.5707964f;
            int num5 = 0;
            float num6 = vector3.Length() + num3 / 2f;
            int num7 = 0;
            while (num6 > 0f)
            {
                Microsoft.Xna.Framework.Color color = Lighting.GetColor((int)vector2.X / 16, (int)(vector2.Y / 16f));
                num2 = proj.type;
                if (num2 != 757)
                {
                    if (num2 == 948)
                    {
                        if (num7 >= 6)
{
                            asset = TextureAssets.Chain41;
                        }
                        else if (num7 >= 4)
{
                            asset = TextureAssets.Chain42;
                            byte b = 140;
                            if (color.R < b)
{
                                color.R = b;
                            }
                            if (color.G < b)
{
                                color.G = b;
                            }
                            if (color.B < b)
{
                                color.B = b;
                            }
                        }
                        else
{
                            color = Microsoft.Xna.Framework.Color.White;
                        }
                        num7++;
                    }
                }
                else
                {
                    rectangle = new Microsoft.Xna.Framework.Rectangle?(asset.Frame(1, 6, 0, num5 % 6, 0, 0));
                }
                Main.spriteBatch.Draw(asset.Value, vector2 - Main.screenPosition, rectangle, color, num4, vector, 1f, SpriteEffects.None, 0f);
                vector2 += vector4 * num3;
                num5++;
                num6 -= num3;
            }
        }
References Microsoft.Xna.Framework.Color.B, Terraria.Entity.Center, Terraria.GameContent.TextureAssets.Chain13, Terraria.GameContent.TextureAssets.Chain19, Terraria.GameContent.TextureAssets.Chain2, Terraria.GameContent.TextureAssets.Chain3, Terraria.GameContent.TextureAssets.Chain41, Terraria.GameContent.TextureAssets.Chain42, Terraria.GameContent.TextureAssets.Chain43, Terraria.GameContent.TextureAssets.Chain6, Terraria.GameContent.TextureAssets.Chain7, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.GameContent.TextureAssets.Extra, Microsoft.Xna.Framework.Color.G, Terraria.Lighting.GetColor(), Terraria.Main.GetPlayerArmPosition(), int, Microsoft.Xna.Framework.Vector2.Length(), Microsoft.Xna.Framework.Color.R, Terraria.Main.screenPosition, Terraria.Main.spriteBatch, Terraria.Projectile.type, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.Main.DrawProjDirect().