Terraria Decompiled: Terraria.Main.NPCChatText_DoAnglerQuest
NPCChatText_DoAnglerQuest()
static void Terraria.Main.NPCChatText_DoAnglerQuest () inline static
Definition at line 39987 of file Main.cs.
        {
            Main.npcChatCornerItem = 0;
            SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
            bool flag = false;
            if (!Main.anglerQuestFinished && !Main.anglerWhoFinishedToday.Contains(Main.player[Main.myPlayer].name))
            {
                int num = Main.player[Main.myPlayer].FindItem(Main.anglerQuestItemNetIDs[Main.anglerQuest]);
                if (num != -1)
                {
                    Main.player[Main.myPlayer].inventory[num].stack--;
                    if (Main.player[Main.myPlayer].inventory[num].stack <= 0)
                    {
                        Main.player[Main.myPlayer].inventory[num] = new Item();
                    }
                    flag = true;
                    SoundEngine.PlaySound(24, -1, -1, 1, 1f, 0f);
                    Main.player[Main.myPlayer].anglerQuestsFinished++;
                    Main.player[Main.myPlayer].GetAnglerReward(Main.npc[Main.player[Main.myPlayer].talkNPC], Main.anglerQuestItemNetIDs[Main.anglerQuest]);
                }
            }
            Main.npcChatText = Lang.AnglerQuestChat(flag);
            if (flag)
            {
                Main.anglerQuestFinished = true;
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(75, -1, -1, null, 0, 0f, 0f, 0f, 0, 0, 0);
                }
                else
                {
                    Main.anglerWhoFinishedToday.Add(Main.player[Main.myPlayer].name);
                }
                AchievementsHelper.HandleAnglerService();
            }
            Main.DoNPCPortraitHop();
        }
References System.Collections.Generic.List< T >.Add(), Terraria.Main.anglerQuest, Terraria.Lang.AnglerQuestChat(), Terraria.Main.anglerQuestFinished, Terraria.Main.anglerQuestItemNetIDs, Terraria.Player.anglerQuestsFinished, Terraria.Main.anglerWhoFinishedToday, System.Collections.Generic.List< T >.Contains(), Terraria.Main.DoNPCPortraitHop(), Terraria.Player.FindItem(), Terraria.Player.GetAnglerReward(), Terraria.GameContent.Achievements.AchievementsHelper.HandleAnglerService(), Terraria.Player.inventory, Terraria.Main.myPlayer, Terraria.Player.name, Terraria.Main.netMode, Terraria.Main.npc, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.NetMessage.SendData(), Terraria.Item.stack, and Terraria.Player.talkNPC.
Referenced by Terraria.GameContent.NPCInteractions.Actions.AnglerQuest.Interact().