Terraria Decompiled: Terraria.Main.ActiveWorldFileData
ActiveWorldFileData
WorldFileData Terraria.Main.ActiveWorldFileData = new WorldFileData() static
Definition at line 70632 of file Main.cs.
Referenced by Terraria.Netplay.BroadcastThread(), Terraria.Utilities.TileSnapshot.Create(), Terraria.WorldGen.CreateNewWorld(), Terraria.Main.DedServ(), Terraria.Program.DisplayException(), Terraria.Main.DrawMenu(), Terraria.GameContent.UI.States.UIWorldCreation.FinishCreatingWorld(), Terraria.IO.WorldFile.FixEndlessRainWorlds(), Terraria.WorldBuilding.WorldGenerator.GenerateWorld(), Terraria.WorldGen.GenerateWorld(), Terraria.GameContent.Bestiary.BestiaryPortraitBackgroundBasedOnWorldEvilProviderPreferenceInfoElement.GetPreferredProvider(), Terraria.Main.HostAndPlay(), Terraria.Map.WorldMap.Load(), Terraria.Utilities.TileSnapshot.Load(), Terraria.IO.WorldFile.LoadFooter(), Terraria.IO.WorldFile.LoadHeader(), Terraria.IO.WorldFile.LoadWorld(), Terraria.GameContent.Bestiary.BestiaryPortraitBackgroundBasedOnWorldEvilProviderPreferenceInfoElement.Matches(), Terraria.Main.OnSeedSelected(), Terraria.Testing.QuickLoad.JoinWorld.OnWorldLoad(), Terraria.GameContent.Biomes.Desert.DesertHive.PlaceClustersArea(), Terraria.GameContent.Biomes.GraniteBiome.PlaceDecorations(), Terraria.WorldGen.playWorldCallBack(), Terraria.WorldGen.PrepForRegen(), Terraria.WorldGen.RenameWorldCallBack(), Terraria.WorldGen.Reset(), Terraria.IO.WorldFile.SaveFooter(), Terraria.IO.WorldFile.SaveNewWorld(), Terraria.IO.WorldFile.SaveWorldHeader(), Terraria.NetMessage.SendData(), Terraria.WorldGen.serverLoadWorldCallBack(), Terraria.Main.startDedInputCallBack(), Terraria.Utilities.TileSnapshot.Swap(), and Terraria.Testing.QuickLoad.JoinWorld.WithCurrentState().