Terraria Decompiled: System.Runtime.Remoting.Contexts.DynamicPropertyCollection.NotifyMessage
NotifyMessage()
void System.Runtime.Remoting.Contexts.DynamicPropertyCollection.NotifyMessage (bool start, IMessage msg, bool client_site, bool async) inline
Definition at line 63 of file DynamicPropertyCollection.cs.
        {
            ArrayList properties = this._properties;
            if (start)
            {
                using (IEnumerator enumerator = properties.GetEnumerator())
                {
                    while (enumerator.MoveNext())
                    {
                        object obj = enumerator.Current;
                        DynamicPropertyCollection.DynamicPropertyReg dynamicPropertyReg = (DynamicPropertyCollection.DynamicPropertyReg)obj;
                        if (dynamicPropertyReg.Sink != null)
{
                            dynamicPropertyReg.Sink.ProcessMessageStart(msg, client_site, async);
                        }
                    }
                    return;
                }
            }
            foreach (object obj2 in properties)
            {
                DynamicPropertyCollection.DynamicPropertyReg dynamicPropertyReg2 = (DynamicPropertyCollection.DynamicPropertyReg)obj2;
                if (dynamicPropertyReg2.Sink != null)
                {
                    dynamicPropertyReg2.Sink.ProcessMessageFinish(msg, client_site, async);
                }
            }
        }
References System.Runtime.Remoting.Contexts.DynamicPropertyCollection._properties, System.Collections.IEnumerator.Current, System.Collections.ArrayList.GetEnumerator(), System.Collections.IEnumerator.MoveNext(), System.obj, System.Runtime.Remoting.Contexts.IDynamicMessageSink.ProcessMessageFinish(), System.Runtime.Remoting.Contexts.IDynamicMessageSink.ProcessMessageStart(), and System.Runtime.Remoting.Contexts.DynamicPropertyCollection.DynamicPropertyReg.Sink.
Referenced by System.Runtime.Remoting.Identity.NotifyClientDynamicSinks(), System.Runtime.Remoting.Contexts.Context.NotifyDynamicSinks(), System.Runtime.Remoting.Contexts.Context.NotifyGlobalDynamicSinks(), and System.Runtime.Remoting.Identity.NotifyServerDynamicSinks().