Terraria Decompiled: System.Runtime.Remoting.Contexts.DynamicPropertyCollection.RegisterDynamicProperty
RegisterDynamicProperty()
bool System.Runtime.Remoting.Contexts.DynamicPropertyCollection.RegisterDynamicProperty (IDynamicProperty prop) inline
Definition at line 21 of file DynamicPropertyCollection.cs.
        {
            bool flag2;
            lock (this)
            {
                if (this.FindProperty(prop.Name) != -1)
                {
                    throw new InvalidOperationException("Another property by this name already exists");
                }
                ArrayList arrayList = new ArrayList(this._properties);
                DynamicPropertyCollection.DynamicPropertyReg dynamicPropertyReg = new DynamicPropertyCollection.DynamicPropertyReg();
                dynamicPropertyReg.Property = prop;
                IContributeDynamicSink contributeDynamicSink = prop as IContributeDynamicSink;
                if (contributeDynamicSink != null)
                {
                    dynamicPropertyReg.Sink = contributeDynamicSink.GetDynamicSink();
                }
                arrayList.Add(dynamicPropertyReg);
                this._properties = arrayList;
                flag2 = true;
            }
            return flag2;
        }
References System.Runtime.Remoting.Contexts.DynamicPropertyCollection._properties, System.Collections.ArrayList.Add(), System.Runtime.Remoting.Contexts.DynamicPropertyCollection.FindProperty(), System.Runtime.Remoting.Contexts.IContributeDynamicSink.GetDynamicSink(), and System.Runtime.Remoting.Contexts.IDynamicProperty.Name.
Referenced by System.Runtime.Remoting.Contexts.Context.RegisterDynamicProperty().