Terraria Decompiled: System.Runtime.Remoting.Contexts.DynamicPropertyCollection.UnregisterDynamicProperty
UnregisterDynamicProperty()
bool System.Runtime.Remoting.Contexts.DynamicPropertyCollection.UnregisterDynamicProperty (string name) inline
Definition at line 46 of file DynamicPropertyCollection.cs.
        {
            bool flag2;
            lock (this)
            {
                int num = this.FindProperty(name);
                if (num == -1)
                {
                    throw new RemotingException("A property with the name " + name + " was not found");
                }
                this._properties.RemoveAt(num);
                flag2 = true;
            }
            return flag2;
        }
References System.Runtime.Remoting.Contexts.DynamicPropertyCollection._properties, System.Runtime.Remoting.Contexts.DynamicPropertyCollection.FindProperty(), System.name, and System.Collections.ArrayList.RemoveAt().
Referenced by System.Runtime.Remoting.Contexts.Context.UnregisterDynamicProperty().