Terraria Decompiled: Terraria.GameContent.DoorOpeningHelper.LookForDoorsToOpen
LookForDoorsToOpen()
void Terraria.GameContent.DoorOpeningHelper.LookForDoorsToOpen (Player player) inline
Definition at line 89 of file DoorOpeningHelper.cs.
        {
            DoorOpeningHelper.PlayerInfoForOpeningDoors playerInfoForOpeningDoor = this.GetPlayerInfoForOpeningDoor(player);
            if (playerInfoForOpeningDoor.intendedOpeningDirection == 0 && player.velocity.X == 0f)
            {
                return;
            }
            Point point = default(Point);
            for (int i = playerInfoForOpeningDoor.tileCoordSpaceForCheckingForDoors.Left; i <= playerInfoForOpeningDoor.tileCoordSpaceForCheckingForDoors.Right; i++)
            {
                for (int j = playerInfoForOpeningDoor.tileCoordSpaceForCheckingForDoors.Top; j <= playerInfoForOpeningDoor.tileCoordSpaceForCheckingForDoors.Bottom; j++)
                {
                    point.X = i;
                    point.Y = j;
                    this.TryAutoOpeningDoor(point, playerInfoForOpeningDoor);
                }
            }
        }
References Microsoft.Xna.Framework.Rectangle.Bottom, Terraria.GameContent.DoorOpeningHelper.GetPlayerInfoForOpeningDoor(), Terraria.GameContent.DoorOpeningHelper.PlayerInfoForOpeningDoors.intendedOpeningDirection, Microsoft.Xna.Framework.Rectangle.Left, Microsoft.Xna.Framework.Rectangle.Right, Terraria.GameContent.DoorOpeningHelper.PlayerInfoForOpeningDoors.tileCoordSpaceForCheckingForDoors, Microsoft.Xna.Framework.Rectangle.Top, Terraria.GameContent.DoorOpeningHelper.TryAutoOpeningDoor(), Terraria.Entity.velocity, and Microsoft.Xna.Framework.Vector2.X.
Referenced by Terraria.GameContent.DoorOpeningHelper.Update().