Terraria Decompiled: Terraria.GameContent.DoorOpeningHelper.GetPlayerInfoForOpeningDoor
GetPlayerInfoForOpeningDoor()
DoorOpeningHelper.PlayerInfoForOpeningDoors Terraria.GameContent.DoorOpeningHelper.GetPlayerInfoForOpeningDoor (Player player) inline private
Definition at line 109 of file DoorOpeningHelper.cs.
        {
            int num = player.controlRight.ToInt() - player.controlLeft.ToInt();
            int num2 = (int)player.gravDir;
            Rectangle hitbox = player.Hitbox;
            hitbox.Y -= -1;
            hitbox.Height += -2;
            float num3 = player.GetAutoDoorVelocityContribution();
            if (num == 0 && this._timeWeCanOpenDoorsUsingVelocityAlone == 0)
            {
                num3 = 0f;
            }
            float num4 = (float)num + num3;
            int num5 = Math.Sign(num4) * (int)Math.Ceiling((double)Math.Abs(num4));
            hitbox.X += num5;
            if (num == 0)
            {
                num = Math.Sign(num4);
            }
            Rectangle hitbox2;
            Rectangle rectangle = (hitbox2 = player.Hitbox);
            hitbox2.X += num5;
            Rectangle rectangle2 = Rectangle.Union(rectangle, hitbox2);
            Point point = rectangle2.TopLeft().ToTileCoordinates();
            Point point2 = rectangle2.BottomRight().ToTileCoordinates();
            Rectangle rectangle3 = new Rectangle(point.X, point.Y, point2.X - point.X, point2.Y - point.Y);
            return new DoorOpeningHelper.PlayerInfoForOpeningDoors
            {
                hitboxToOpenDoor = hitbox,
                intendedOpeningDirection = num,
                playerGravityDirection = num2,
                tileCoordSpaceForCheckingForDoors = rectangle3
            };
        }
References Terraria.GameContent.DoorOpeningHelper._timeWeCanOpenDoorsUsingVelocityAlone, System.Math.Abs(), System.Math.Ceiling(), Terraria.Player.controlLeft, Terraria.Player.controlRight, Terraria.Player.GetAutoDoorVelocityContribution(), Terraria.Player.gravDir, Terraria.Entity.Hitbox, int, System.Math.Sign(), Microsoft.Xna.Framework.Rectangle.Union(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.DoorOpeningHelper.LookForDoorsToOpen().