Terraria Decompiled: Terraria.GameContent.UI.States.UIAchievementsMenu.OnActivate
OnActivate()
override void Terraria.GameContent.UI.States.UIAchievementsMenu.OnActivate () inline virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 194 of file UIAchievementsMenu.cs.
        {
            this.InitializePage();
            if (Main.gameMenu)
            {
                this._outerContainer.Top.Set(220f, 0f);
                this._outerContainer.Height.Set(-220f, 1f);
            }
            else
            {
                this._outerContainer.Top.Set(120f, 0f);
                this._outerContainer.Height.Set(-120f, 1f);
            }
            this._achievementsList.UpdateOrder();
            if (PlayerInput.UsingGamepadUI)
            {
                UILinkPointNavigator.ChangePoint(3002);
            }
        }
References Terraria.GameContent.UI.States.UIAchievementsMenu._achievementsList, Terraria.GameContent.UI.States.UIAchievementsMenu._outerContainer, Terraria.UI.Gamepad.UILinkPointNavigator.ChangePoint(), Terraria.Main.gameMenu, Terraria.UI.UIElement.Height, Terraria.GameContent.UI.States.UIAchievementsMenu.InitializePage(), Terraria.UI.StyleDimension.Set(), Terraria.UI.UIElement.Top, Terraria.GameContent.UI.Elements.UIList.UpdateOrder(), and Terraria.GameInput.PlayerInput.UsingGamepadUI.