Terraria Decompiled: Terraria.GameContent.UI.States.UIAchievementsMenu.SetupGamepadPoints
SetupGamepadPoints()
void Terraria.GameContent.UI.States.UIAchievementsMenu.SetupGamepadPoints (SpriteBatch spriteBatch) inline private
Definition at line 215 of file UIAchievementsMenu.cs.
        {
            UILinkPointNavigator.Shortcuts.BackButtonCommand = 3;
            int num = 3000;
            UILinkPointNavigator.SetPosition(num, this._backpanel.GetInnerDimensions().ToRectangle().Center.ToVector2());
            UILinkPointNavigator.SetPosition(num + 1, this._outerContainer.GetInnerDimensions().ToRectangle().Center.ToVector2());
            int num2 = num;
            UILinkPoint uilinkPoint = UILinkPointNavigator.Points[num2];
            uilinkPoint.Unlink();
            uilinkPoint.Up = num2 + 1;
            num2++;
            UILinkPoint uilinkPoint2 = UILinkPointNavigator.Points[num2];
            uilinkPoint2.Unlink();
            uilinkPoint2.Up = num2 + 1;
            uilinkPoint2.Down = num2 - 1;
            for (int i = 0; i < this._categoryButtons.Count; i++)
            {
                num2++;
                UILinkPointNavigator.Shortcuts.FANCYUI_HIGHEST_INDEX = num2;
                UILinkPointNavigator.SetPosition(num2, this._categoryButtons[i].GetInnerDimensions().ToRectangle().Center.ToVector2());
                UILinkPoint uilinkPoint3 = UILinkPointNavigator.Points[num2];
                uilinkPoint3.Unlink();
                uilinkPoint3.Left = ((i == 0) ? (-3) : (num2 - 1));
                uilinkPoint3.Right = ((i == this._categoryButtons.Count - 1) ? (-4) : (num2 + 1));
                uilinkPoint3.Down = num;
            }
        }
References Terraria.GameContent.UI.States.UIAchievementsMenu._backpanel, Terraria.GameContent.UI.States.UIAchievementsMenu._categoryButtons, Terraria.GameContent.UI.States.UIAchievementsMenu._outerContainer, Microsoft.Xna.Framework.Rectangle.Center, System.Collections.Generic.List< T >.Count, Terraria.UI.UIElement.GetInnerDimensions(), Terraria.UI.Gamepad.UILinkPointNavigator.Points, Terraria.UI.Gamepad.UILinkPointNavigator.SetPosition(), Terraria.UI.CalculatedStyle.ToRectangle(), and Terraria.UI.Gamepad.UILinkPoint.Unlink().
Referenced by Terraria.GameContent.UI.States.UIAchievementsMenu.Draw().