Terraria Decompiled: Terraria.GameContent.UI.States.UIAchievementsMenu.InitializePage
InitializePage()
void Terraria.GameContent.UI.States.UIAchievementsMenu.InitializePage () inline
Definition at line 22 of file UIAchievementsMenu.cs.
        {
            base.RemoveAllChildren();
            this._categoryButtons.Clear();
            this._achievementElements.Clear();
            this._achievementsList = null;
            bool flag = true;
            int num = flag.ToInt() * 100;
            UIElement uielement = new UIElement();
            uielement.Width.Set(0f, 0.8f);
            uielement.MaxWidth.Set(800f + (float)num, 0f);
            uielement.MinWidth.Set(600f + (float)num, 0f);
            uielement.Top.Set(220f, 0f);
            uielement.Height.Set(-220f, 1f);
            uielement.HAlign = 0.5f;
            this._outerContainer = uielement;
            base.Append(uielement);
            UIPanel uipanel = new UIPanel();
            uipanel.Width.Set(0f, 1f);
            uipanel.Height.Set(-110f, 1f);
            uipanel.BackgroundColor = new Color(33, 43, 79) * 0.8f;
            uipanel.PaddingTop = 0f;
            uielement.Append(uipanel);
            this._achievementsList = new UIList();
            this._achievementsList.Width.Set(-25f, 1f);
            this._achievementsList.Height.Set(-50f, 1f);
            this._achievementsList.Top.Set(50f, 0f);
            this._achievementsList.ListPadding = 5f;
            uipanel.Append(this._achievementsList);
            UITextPanel<LocalizedText> uitextPanel = new UITextPanel<LocalizedText>(Language.GetText("UI.Achievements"), 1f, true);
            uitextPanel.HAlign = 0.5f;
            uitextPanel.Top.Set(-33f, 0f);
            uitextPanel.SetPadding(13f);
            uitextPanel.BackgroundColor = new Color(73, 94, 171);
            uielement.Append(uitextPanel);
            UITextPanel<LocalizedText> uitextPanel2 = new UITextPanel<LocalizedText>(Language.GetText("UI.Back"), 0.7f, true);
            uitextPanel2.Width.Set(-10f, 0.5f);
            uitextPanel2.Height.Set(50f, 0f);
            uitextPanel2.VAlign = 1f;
            uitextPanel2.HAlign = 0.5f;
            uitextPanel2.Top.Set(-45f, 0f);
            uitextPanel2.OnMouseOver += this.FadedMouseOver;
            uitextPanel2.OnMouseOut += this.FadedMouseOut;
            uitextPanel2.OnLeftClick += this.GoBackClick;
            uielement.Append(uitextPanel2);
            this._backpanel = uitextPanel2;
            List<Achievement> list = Main.Achievements.CreateAchievementsList();
            for (int i = 0; i < list.Count; i++)
            {
                UIAchievementListItem uiachievementListItem = new UIAchievementListItem(list[i], flag);
                this._achievementsList.Add(uiachievementListItem);
                this._achievementElements.Add(uiachievementListItem);
            }
            UIScrollbar uiscrollbar = new UIScrollbar(UIScrollbar.ColorTheme.Blue);
            uiscrollbar.SetView(100f, 1000f);
            uiscrollbar.Height.Set(-50f, 1f);
            uiscrollbar.Top.Set(50f, 0f);
            uiscrollbar.HAlign = 1f;
            uipanel.Append(uiscrollbar);
            this._achievementsList.SetScrollbar(uiscrollbar);
            UIElement uielement2 = new UIElement();
            uielement2.Width.Set(0f, 1f);
            uielement2.Height.Set(32f, 0f);
            uielement2.Top.Set(10f, 0f);
            Asset<Texture2D> asset = Main.Assets.Request<Texture2D>("Images/UI/Achievement_Categories", 1);
            for (int j = 0; j < 4; j++)
            {
                UIToggleImage uitoggleImage = new UIToggleImage(asset, 32, 32, new Point(34 * j, 0), new Point(34 * j, 34));
                uitoggleImage.Left.Set((float)(j * 36 + 8), 0f);
                uitoggleImage.SetState(true);
                uitoggleImage.OnLeftClick += this.FilterList;
                this._categoryButtons.Add(uitoggleImage);
                uielement2.Append(uitoggleImage);
            }
            uipanel.Append(uielement2);
        }
References Terraria.GameContent.UI.States.UIAchievementsMenu._achievementElements, Terraria.GameContent.UI.States.UIAchievementsMenu._achievementsList, Terraria.GameContent.UI.States.UIAchievementsMenu._categoryButtons, Terraria.Main.Achievements, System.Collections.Generic.List< T >.Add(), Terraria.GameContent.UI.Elements.UIList.Add(), Terraria.UI.UIElement.Append(), Terraria.Main.Assets, System.Collections.Generic.List< T >.Clear(), Microsoft.Xna.Framework.Graphics.Color, Terraria.Achievements.AchievementManager.CreateAchievementsList(), Terraria.GameContent.UI.States.UIAchievementsMenu.FadedMouseOut(), Terraria.GameContent.UI.States.UIAchievementsMenu.FadedMouseOver(), Terraria.GameContent.UI.States.UIAchievementsMenu.FilterList(), Terraria.Localization.Language.GetText(), Terraria.GameContent.UI.States.UIAchievementsMenu.GoBackClick(), Terraria.UI.UIElement.Height, Terraria.UI.UIElement.Left, System.list, Terraria.UI.UIElement.MaxWidth, Terraria.UI.UIElement.MinWidth, Microsoft.Xna.Framework.Graphics.Point, Terraria.UI.StyleDimension.Set(), Terraria.UI.UIElement.SetPadding(), Terraria.GameContent.UI.Elements.UIList.SetScrollbar(), Terraria.GameContent.UI.Elements.UIToggleImage.SetState(), Terraria.GameContent.UI.Elements.UIScrollbar.SetView(), Terraria.UI.UIElement.Top, Terraria.UI.UIElement.UIElement(), and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.UIAchievementsMenu.OnActivate().