Terraria Decompiled: Terraria.Utilities.CrashDump.CreateDumpName
CreateDumpName()
static string Terraria.Utilities.CrashDump.CreateDumpName () inline static private
Definition at line 27 of file CrashDump.cs.
        {
            DateTime dateTime = DateTime.Now.ToLocalTime();
            return string.Format("{0}_{1}_{2}_{3}.dmp", new object[]
            {
                Main.dedServ ? "TerrariaServer" : "Terraria",
                Main.versionNumber,
                dateTime.ToString("MM-dd-yy_HH-mm-ss-ffff", CultureInfo.InvariantCulture),
                Thread.CurrentThread.ManagedThreadId
            });
        }
References System.Threading.Thread.CurrentThread, System.Globalization.CultureInfo.InvariantCulture, System.Threading.Thread.ManagedThreadId, System.DateTime.Now, System.DateTime.ToLocalTime(), System.DateTime.ToString(), and Terraria.Main.versionNumber.
Referenced by Terraria.Utilities.CrashDump.Write().