Terraria Decompiled: Terraria.Utilities.CrashDump.Write
Write() [3/3]
static bool Terraria.Utilities.CrashDump.Write (SafeHandle fileHandle, CrashDump::Options options, CrashDump::ExceptionInfo exceptionInfo) inline static private
Definition at line 60 of file CrashDump.cs.
        {
            if (!Platform.IsWindows)
            {
                return false;
            }
            Process currentProcess = Process.GetCurrentProcess();
            IntPtr handle = currentProcess.Handle;
            uint id = (uint)currentProcess.Id;
            CrashDump.MiniDumpExceptionInformation miniDumpExceptionInformation;
            miniDumpExceptionInformation.ThreadId = CrashDump.GetCurrentThreadId();
            miniDumpExceptionInformation.ClientPointers = false;
            miniDumpExceptionInformation.ExceptionPointers = IntPtr.Zero;
            if (exceptionInfo == CrashDump.ExceptionInfo.Present)
            {
                miniDumpExceptionInformation.ExceptionPointers = Marshal.GetExceptionPointers();
            }
            bool flag;
            if (miniDumpExceptionInformation.ExceptionPointers == IntPtr.Zero)
            {
                flag = CrashDump.MiniDumpWriteDump(handle, id, fileHandle, (uint)options, IntPtr.Zero, IntPtr.Zero, IntPtr.Zero);
            }
            else
            {
                flag = CrashDump.MiniDumpWriteDump(handle, id, fileHandle, (uint)options, ref miniDumpExceptionInformation, IntPtr.Zero, IntPtr.Zero);
            }
            return flag;
        }
References Terraria.Utilities.CrashDump.MiniDumpExceptionInformation.ExceptionPointers, Terraria.Utilities.CrashDump.GetCurrentThreadId(), System.Runtime.InteropServices.Marshal.GetExceptionPointers(), ReLogic.OS.Platform.IsWindows, Terraria.Utilities.CrashDump.MiniDumpWriteDump(), System.options, System.Process, and System.IntPtr.Zero.