Terraria Decompiled: System.Buffers.Binary.BinaryPrimitives.ReverseEndianness
ReverseEndianness() [4/8]
static sbyte System.Buffers.Binary.BinaryPrimitives.ReverseEndianness (sbyte value) inline static
Definition at line 13 of file BinaryPrimitives.cs.
        {
            return value;
        }
References System.value.
Referenced by System.Globalization.CharUnicodeInfo.InternalGetCategoryValue(), System.Globalization.CharUnicodeInfo.InternalGetNumericValue(), System.IO.BinaryReader.ReadDecimal(), System.Buffers.Binary.BinaryPrimitives.ReadInt16BigEndian(), System.Buffers.Binary.BinaryPrimitives.ReadInt16LittleEndian(), System.Buffers.Binary.BinaryPrimitives.ReadInt32BigEndian(), System.Buffers.Binary.BinaryPrimitives.ReadInt32LittleEndian(), System.Buffers.Binary.BinaryPrimitives.ReadInt64BigEndian(), System.Buffers.Binary.BinaryPrimitives.ReadInt64LittleEndian(), System.Buffers.Binary.BinaryPrimitives.ReadUInt16BigEndian(), System.Buffers.Binary.BinaryPrimitives.ReadUInt16LittleEndian(), System.Buffers.Binary.BinaryPrimitives.ReadUInt32BigEndian(), System.Buffers.Binary.BinaryPrimitives.ReadUInt32LittleEndian(), System.Buffers.Binary.BinaryPrimitives.ReadUInt64BigEndian(), System.Buffers.Binary.BinaryPrimitives.ReadUInt64LittleEndian(), System.Buffers.Binary.BinaryPrimitives.ReverseEndianness(), System.Buffers.Binary.BinaryPrimitives.ReverseEndianness(), System.Buffers.Binary.BinaryPrimitives.ReverseEndianness(), System.Buffers.Binary.BinaryPrimitives.TryReadInt16BigEndian(), System.Buffers.Binary.BinaryPrimitives.TryReadInt16LittleEndian(), System.Buffers.Binary.BinaryPrimitives.TryReadInt32BigEndian(), System.Buffers.Binary.BinaryPrimitives.TryReadInt32LittleEndian(), System.Buffers.Binary.BinaryPrimitives.TryReadInt64BigEndian(), System.Buffers.Binary.BinaryPrimitives.TryReadInt64LittleEndian(), System.Buffers.SequenceReaderExtensions.TryReadReverseEndianness(), System.Buffers.SequenceReaderExtensions.TryReadReverseEndianness(), System.Buffers.SequenceReaderExtensions.TryReadReverseEndianness(), System.Buffers.Binary.BinaryPrimitives.TryReadUInt16BigEndian(), System.Buffers.Binary.BinaryPrimitives.TryReadUInt16LittleEndian(), System.Buffers.Binary.BinaryPrimitives.TryReadUInt32BigEndian(), System.Buffers.Binary.BinaryPrimitives.TryReadUInt32LittleEndian(), System.Buffers.Binary.BinaryPrimitives.TryReadUInt64BigEndian(), System.Buffers.Binary.BinaryPrimitives.TryReadUInt64LittleEndian(), System.Buffers.Binary.BinaryPrimitives.TryWriteInt16BigEndian(), System.Buffers.Binary.BinaryPrimitives.TryWriteInt16LittleEndian(), System.Buffers.Binary.BinaryPrimitives.TryWriteInt32BigEndian(), System.Buffers.Binary.BinaryPrimitives.TryWriteInt32LittleEndian(), System.Buffers.Binary.BinaryPrimitives.TryWriteInt64BigEndian(), System.Buffers.Binary.BinaryPrimitives.TryWriteInt64LittleEndian(), System.Buffers.Binary.BinaryPrimitives.TryWriteUInt16BigEndian(), System.Buffers.Binary.BinaryPrimitives.TryWriteUInt16LittleEndian(), System.Buffers.Binary.BinaryPrimitives.TryWriteUInt32BigEndian(), System.Buffers.Binary.BinaryPrimitives.TryWriteUInt32LittleEndian(), System.Buffers.Binary.BinaryPrimitives.TryWriteUInt64BigEndian(), System.Buffers.Binary.BinaryPrimitives.TryWriteUInt64LittleEndian(), System.Buffers.Binary.BinaryPrimitives.WriteInt16BigEndian(), System.Buffers.Binary.BinaryPrimitives.WriteInt16LittleEndian(), System.Buffers.Binary.BinaryPrimitives.WriteInt32BigEndian(), System.Buffers.Binary.BinaryPrimitives.WriteInt32LittleEndian(), System.Buffers.Binary.BinaryPrimitives.WriteInt64BigEndian(), System.Buffers.Binary.BinaryPrimitives.WriteInt64LittleEndian(), System.Buffers.Binary.BinaryPrimitives.WriteUInt16BigEndian(), System.Buffers.Binary.BinaryPrimitives.WriteUInt16LittleEndian(), System.Buffers.Binary.BinaryPrimitives.WriteUInt32BigEndian(), System.Buffers.Binary.BinaryPrimitives.WriteUInt32LittleEndian(), System.Buffers.Binary.BinaryPrimitives.WriteUInt64BigEndian(), and System.Buffers.Binary.BinaryPrimitives.WriteUInt64LittleEndian().