Terraria Decompiled: System.Reflection.Emit.GenericTypeParameterBuilder.InternalResolve
InternalResolve()
override Type System.Reflection.Emit.GenericTypeParameterBuilder.InternalResolve () inline package virtual
Reimplemented from System.Type.
Definition at line 41 of file GenericTypeParameterBuilder.cs.
        {
            if (this.mbuilder != null)
            {
                return MethodBase.GetMethodFromHandle(this.mbuilder.MethodHandleInternal, this.mbuilder.TypeBuilder.InternalResolve().TypeHandle).GetGenericArguments()[this.index];
            }
            return this.tbuilder.InternalResolve().GetGenericArguments()[this.index];
        }
References System.Reflection.MethodBase.GetGenericArguments(), System.Type.GetGenericArguments(), System.Reflection.MethodBase.GetMethodFromHandle(), System.Reflection.Emit.GenericTypeParameterBuilder.index, System.Reflection.Emit.TypeBuilder.InternalResolve(), System.Reflection.Emit.GenericTypeParameterBuilder.mbuilder, System.Reflection.Emit.MethodBuilder.MethodHandleInternal, and System.Reflection.Emit.GenericTypeParameterBuilder.tbuilder.