Terraria Decompiled: Newtonsoft.Json.JsonSerializer.DeserializeInternal
DeserializeInternal()
virtual object Newtonsoft.Json.JsonSerializer.DeserializeInternal (JsonReader reader, Type objectType) inline package virtual
Reimplemented in Newtonsoft.Json.Serialization.JsonSerializerProxy.
Definition at line 851 of file JsonSerializer.cs.
        {
            ValidationUtils.ArgumentNotNull(reader, "reader");
            CultureInfo cultureInfo;
            DateTimeZoneHandling? dateTimeZoneHandling;
            DateParseHandling? dateParseHandling;
            FloatParseHandling? floatParseHandling;
            int? num;
            string text;
            this.SetupReader(reader, out cultureInfo, out dateTimeZoneHandling, out dateParseHandling, out floatParseHandling, out num, out text);
            TraceJsonReader traceJsonReader = ((this.TraceWriter != null && this.TraceWriter.LevelFilter >= 4) ? new TraceJsonReader(reader) : null);
            object obj = new JsonSerializerInternalReader(this).Deserialize(traceJsonReader ?? reader, objectType, this.CheckAdditionalContent);
            if (traceJsonReader != null)
            {
                this.TraceWriter.Trace(4, traceJsonReader.GetDeserializedJsonMessage(), null);
            }
            this.ResetReader(reader, cultureInfo, dateTimeZoneHandling, dateParseHandling, floatParseHandling, num, text);
            return obj;
        }
References Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(), Newtonsoft.Json.JsonSerializer.CheckAdditionalContent, Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(), Newtonsoft.Json.Serialization.TraceJsonReader.GetDeserializedJsonMessage(), System.obj, Newtonsoft.Json.JsonSerializer.ResetReader(), Newtonsoft.Json.JsonSerializer.SetupReader(), System.text, Newtonsoft.Json.Serialization.ITraceWriter.Trace(), and Newtonsoft.Json.JsonSerializer.TraceWriter.
Referenced by Newtonsoft.Json.JsonSerializer.Deserialize().