Terraria Decompiled: Newtonsoft.Json.JsonSerializer.Deserialize
Deserialize() [1/3]
object Newtonsoft.Json.JsonSerializer.Deserialize (JsonReader reader) inline
Definition at line 827 of file JsonSerializer.cs.
        {
            return this.Deserialize(reader, null);
        }
References Newtonsoft.Json.JsonSerializer.Deserialize().
Referenced by Newtonsoft.Json.Converters.DataTableConverter.CreateRow(), Newtonsoft.Json.JsonSerializer.Deserialize(), Newtonsoft.Json.JsonSerializer.Deserialize(), Newtonsoft.Json.JsonSerializer.Deserialize< T >(), Newtonsoft.Json.Serialization.JsonSerializerProxy.DeserializeInternal(), Newtonsoft.Json.JsonConvert.DeserializeObject(), Terraria.IO.Preferences.Load(), Terraria.Achievements.AchievementManager.Load(), Newtonsoft.Json.Converters.EntityKeyMemberConverter.ReadJson(), Newtonsoft.Json.Converters.KeyValuePairConverter.ReadJson(), Terraria.WorldBuilding.WorldGenSnapshot.SnapshotGenVars.ReadJson(), Newtonsoft.Json.Converters.RegexConverter.ReadRegexObject(), and Newtonsoft.Json.Linq.JToken.ToObject().