Terraria Decompiled: Newtonsoft.Json.JsonSerializer.SerializeInternal
SerializeInternal()
virtual void Newtonsoft.Json.JsonSerializer.SerializeInternal (JsonWriter jsonWriter, object value, Type objectType) inline package virtual
Reimplemented in Newtonsoft.Json.Serialization.JsonSerializerProxy.
Definition at line 998 of file JsonSerializer.cs.
        {
            ValidationUtils.ArgumentNotNull(jsonWriter, "jsonWriter");
            Formatting? formatting = default(Formatting?);
            if (this._formatting != null && jsonWriter.Formatting != this._formatting)
            {
                formatting = new Formatting?(jsonWriter.Formatting);
                jsonWriter.Formatting = this._formatting.GetValueOrDefault();
            }
            DateFormatHandling? dateFormatHandling = default(DateFormatHandling?);
            if (this._dateFormatHandling != null && jsonWriter.DateFormatHandling != this._dateFormatHandling)
            {
                dateFormatHandling = new DateFormatHandling?(jsonWriter.DateFormatHandling);
                jsonWriter.DateFormatHandling = this._dateFormatHandling.GetValueOrDefault();
            }
            DateTimeZoneHandling? dateTimeZoneHandling = default(DateTimeZoneHandling?);
            if (this._dateTimeZoneHandling != null && jsonWriter.DateTimeZoneHandling != this._dateTimeZoneHandling)
            {
                dateTimeZoneHandling = new DateTimeZoneHandling?(jsonWriter.DateTimeZoneHandling);
                jsonWriter.DateTimeZoneHandling = this._dateTimeZoneHandling.GetValueOrDefault();
            }
            FloatFormatHandling? floatFormatHandling = default(FloatFormatHandling?);
            if (this._floatFormatHandling != null && jsonWriter.FloatFormatHandling != this._floatFormatHandling)
            {
                floatFormatHandling = new FloatFormatHandling?(jsonWriter.FloatFormatHandling);
                jsonWriter.FloatFormatHandling = this._floatFormatHandling.GetValueOrDefault();
            }
            StringEscapeHandling? stringEscapeHandling = default(StringEscapeHandling?);
            if (this._stringEscapeHandling != null && jsonWriter.StringEscapeHandling != this._stringEscapeHandling)
            {
                stringEscapeHandling = new StringEscapeHandling?(jsonWriter.StringEscapeHandling);
                jsonWriter.StringEscapeHandling = this._stringEscapeHandling.GetValueOrDefault();
            }
            CultureInfo cultureInfo = null;
            if (this._culture != null && !this._culture.Equals(jsonWriter.Culture))
            {
                cultureInfo = jsonWriter.Culture;
                jsonWriter.Culture = this._culture;
            }
            string text = null;
            if (this._dateFormatStringSet && jsonWriter.DateFormatString != this._dateFormatString)
            {
                text = jsonWriter.DateFormatString;
                jsonWriter.DateFormatString = this._dateFormatString;
            }
            TraceJsonWriter traceJsonWriter = ((this.TraceWriter != null && this.TraceWriter.LevelFilter >= 4) ? new TraceJsonWriter(jsonWriter) : null);
            new JsonSerializerInternalWriter(this).Serialize(traceJsonWriter ?? jsonWriter, value, objectType);
            if (traceJsonWriter != null)
            {
                this.TraceWriter.Trace(4, traceJsonWriter.GetSerializedJsonMessage(), null);
            }
            if (formatting != null)
            {
                jsonWriter.Formatting = formatting.GetValueOrDefault();
            }
            if (dateFormatHandling != null)
            {
                jsonWriter.DateFormatHandling = dateFormatHandling.GetValueOrDefault();
            }
            if (dateTimeZoneHandling != null)
            {
                jsonWriter.DateTimeZoneHandling = dateTimeZoneHandling.GetValueOrDefault();
            }
            if (floatFormatHandling != null)
            {
                jsonWriter.FloatFormatHandling = floatFormatHandling.GetValueOrDefault();
            }
            if (stringEscapeHandling != null)
            {
                jsonWriter.StringEscapeHandling = stringEscapeHandling.GetValueOrDefault();
            }
            if (this._dateFormatStringSet)
            {
                jsonWriter.DateFormatString = text;
            }
            if (cultureInfo != null)
            {
                jsonWriter.Culture = cultureInfo;
            }
        }
References Newtonsoft.Json.JsonSerializer._culture, Newtonsoft.Json.JsonSerializer._dateFormatHandling, Newtonsoft.Json.JsonSerializer._dateFormatString, Newtonsoft.Json.JsonSerializer._dateFormatStringSet, Newtonsoft.Json.JsonSerializer._dateTimeZoneHandling, Newtonsoft.Json.JsonSerializer._floatFormatHandling, Newtonsoft.Json.JsonSerializer._formatting, Newtonsoft.Json.JsonSerializer._stringEscapeHandling, Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(), Newtonsoft.Json.JsonWriter.Culture, Newtonsoft.Json.JsonWriter.DateFormatHandling, Newtonsoft.Json.JsonWriter.DateFormatString, Newtonsoft.Json.JsonWriter.DateTimeZoneHandling, System.Globalization.CultureInfo.Equals(), Newtonsoft.Json.JsonWriter.FloatFormatHandling, Newtonsoft.Json.JsonWriter.Formatting, Newtonsoft.Json.Serialization.TraceJsonWriter.GetSerializedJsonMessage(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(), Newtonsoft.Json.JsonWriter.StringEscapeHandling, System.text, Newtonsoft.Json.Serialization.ITraceWriter.Trace(), Newtonsoft.Json.JsonSerializer.TraceWriter, and System.value.
Referenced by Newtonsoft.Json.JsonSerializer.Serialize(), and Newtonsoft.Json.JsonSerializer.Serialize().