Terraria Decompiled: Newtonsoft.Json.JsonSerializer.SetupReader
SetupReader()
void Newtonsoft.Json.JsonSerializer.SetupReader (JsonReader reader, out CultureInfo previousCulture, out DateTimeZoneHandling? previousDateTimeZoneHandling, out DateParseHandling? previousDateParseHandling, out FloatParseHandling? previousFloatParseHandling, out int? previousMaxDepth, out string previousDateFormatString) inline private
Definition at line 872 of file JsonSerializer.cs.
        {
            if (this._culture != null && !this._culture.Equals(reader.Culture))
            {
                previousCulture = reader.Culture;
                reader.Culture = this._culture;
            }
            else
            {
                previousCulture = null;
            }
            if (this._dateTimeZoneHandling != null && reader.DateTimeZoneHandling != this._dateTimeZoneHandling)
            {
                previousDateTimeZoneHandling = new DateTimeZoneHandling?(reader.DateTimeZoneHandling);
                reader.DateTimeZoneHandling = this._dateTimeZoneHandling.GetValueOrDefault();
            }
            else
            {
                previousDateTimeZoneHandling = default(DateTimeZoneHandling?);
            }
            if (this._dateParseHandling != null && reader.DateParseHandling != this._dateParseHandling)
            {
                previousDateParseHandling = new DateParseHandling?(reader.DateParseHandling);
                reader.DateParseHandling = this._dateParseHandling.GetValueOrDefault();
            }
            else
            {
                previousDateParseHandling = default(DateParseHandling?);
            }
            if (this._floatParseHandling != null && reader.FloatParseHandling != this._floatParseHandling)
            {
                previousFloatParseHandling = new FloatParseHandling?(reader.FloatParseHandling);
                reader.FloatParseHandling = this._floatParseHandling.GetValueOrDefault();
            }
            else
            {
                previousFloatParseHandling = default(FloatParseHandling?);
            }
            if (this._maxDepthSet && reader.MaxDepth != this._maxDepth)
            {
                previousMaxDepth = reader.MaxDepth;
                reader.MaxDepth = this._maxDepth;
            }
            else
            {
                previousMaxDepth = default(int?);
            }
            if (this._dateFormatStringSet && reader.DateFormatString != this._dateFormatString)
            {
                previousDateFormatString = reader.DateFormatString;
                reader.DateFormatString = this._dateFormatString;
            }
            else
            {
                previousDateFormatString = null;
            }
            JsonTextReader jsonTextReader = reader as JsonTextReader;
            if (jsonTextReader != null)
            {
                DefaultContractResolver defaultContractResolver = this._contractResolver as DefaultContractResolver;
                if (defaultContractResolver != null)
                {
                    jsonTextReader.NameTable = defaultContractResolver.GetNameTable();
                }
            }
        }
References Newtonsoft.Json.JsonSerializer._culture, Newtonsoft.Json.JsonSerializer._dateFormatString, Newtonsoft.Json.JsonSerializer._dateFormatStringSet, Newtonsoft.Json.JsonSerializer._dateParseHandling, Newtonsoft.Json.JsonSerializer._dateTimeZoneHandling, Newtonsoft.Json.JsonSerializer._floatParseHandling, Newtonsoft.Json.JsonSerializer._maxDepth, Newtonsoft.Json.JsonSerializer._maxDepthSet, Newtonsoft.Json.JsonReader.Culture, Newtonsoft.Json.JsonReader.DateFormatString, Newtonsoft.Json.JsonReader.DateParseHandling, Newtonsoft.Json.JsonReader.DateTimeZoneHandling, System.Globalization.CultureInfo.Equals(), Newtonsoft.Json.JsonReader.FloatParseHandling, Newtonsoft.Json.Serialization.DefaultContractResolver.GetNameTable(), and Newtonsoft.Json.JsonReader.MaxDepth.
Referenced by Newtonsoft.Json.JsonSerializer.DeserializeInternal(), and Newtonsoft.Json.JsonSerializer.PopulateInternal().