Terraria Decompiled: Newtonsoft.Json.JsonSerializer.ApplySerializerSettings
ApplySerializerSettings()
static void Newtonsoft.Json.JsonSerializer.ApplySerializerSettings (JsonSerializer serializer, JsonSerializerSettings settings) inline static private
Definition at line 668 of file JsonSerializer.cs.
        {
            if (!CollectionUtils.IsNullOrEmpty<JsonConverter>(settings.Converters))
            {
                for (int i = 0; i < settings.Converters.Count; i++)
                {
                    serializer.Converters.Insert(i, settings.Converters[i]);
                }
            }
            if (settings._typeNameHandling != null)
            {
                serializer.TypeNameHandling = settings.TypeNameHandling;
            }
            if (settings._metadataPropertyHandling != null)
            {
                serializer.MetadataPropertyHandling = settings.MetadataPropertyHandling;
            }
            if (settings._typeNameAssemblyFormatHandling != null)
            {
                serializer.TypeNameAssemblyFormatHandling = settings.TypeNameAssemblyFormatHandling;
            }
            if (settings._preserveReferencesHandling != null)
            {
                serializer.PreserveReferencesHandling = settings.PreserveReferencesHandling;
            }
            if (settings._referenceLoopHandling != null)
            {
                serializer.ReferenceLoopHandling = settings.ReferenceLoopHandling;
            }
            if (settings._missingMemberHandling != null)
            {
                serializer.MissingMemberHandling = settings.MissingMemberHandling;
            }
            if (settings._objectCreationHandling != null)
            {
                serializer.ObjectCreationHandling = settings.ObjectCreationHandling;
            }
            if (settings._nullValueHandling != null)
            {
                serializer.NullValueHandling = settings.NullValueHandling;
            }
            if (settings._defaultValueHandling != null)
            {
                serializer.DefaultValueHandling = settings.DefaultValueHandling;
            }
            if (settings._constructorHandling != null)
            {
                serializer.ConstructorHandling = settings.ConstructorHandling;
            }
            if (settings._context != null)
            {
                serializer.Context = settings.Context;
            }
            if (settings._checkAdditionalContent != null)
            {
                serializer._checkAdditionalContent = settings._checkAdditionalContent;
            }
            if (settings.Error != null)
            {
                serializer.Error += settings.Error;
            }
            if (settings.ContractResolver != null)
            {
                serializer.ContractResolver = settings.ContractResolver;
            }
            if (settings.ReferenceResolverProvider != null)
            {
                serializer.ReferenceResolver = settings.ReferenceResolverProvider.Invoke();
            }
            if (settings.TraceWriter != null)
            {
                serializer.TraceWriter = settings.TraceWriter;
            }
            if (settings.EqualityComparer != null)
            {
                serializer.EqualityComparer = settings.EqualityComparer;
            }
            if (settings.SerializationBinder != null)
            {
                serializer.SerializationBinder = settings.SerializationBinder;
            }
            if (settings._formatting != null)
            {
                serializer._formatting = settings._formatting;
            }
            if (settings._dateFormatHandling != null)
            {
                serializer._dateFormatHandling = settings._dateFormatHandling;
            }
            if (settings._dateTimeZoneHandling != null)
            {
                serializer._dateTimeZoneHandling = settings._dateTimeZoneHandling;
            }
            if (settings._dateParseHandling != null)
            {
                serializer._dateParseHandling = settings._dateParseHandling;
            }
            if (settings._dateFormatStringSet)
            {
                serializer._dateFormatString = settings._dateFormatString;
                serializer._dateFormatStringSet = settings._dateFormatStringSet;
            }
            if (settings._floatFormatHandling != null)
            {
                serializer._floatFormatHandling = settings._floatFormatHandling;
            }
            if (settings._floatParseHandling != null)
            {
                serializer._floatParseHandling = settings._floatParseHandling;
            }
            if (settings._stringEscapeHandling != null)
            {
                serializer._stringEscapeHandling = settings._stringEscapeHandling;
            }
            if (settings._culture != null)
            {
                serializer._culture = settings._culture;
            }
            if (settings._maxDepthSet)
            {
                serializer._maxDepth = settings._maxDepth;
                serializer._maxDepthSet = settings._maxDepthSet;
            }
        }
References Newtonsoft.Json.JsonSerializerSettings._checkAdditionalContent, Newtonsoft.Json.JsonSerializerSettings._constructorHandling, Newtonsoft.Json.JsonSerializerSettings._context, Newtonsoft.Json.JsonSerializerSettings._culture, Newtonsoft.Json.JsonSerializerSettings._dateFormatHandling, Newtonsoft.Json.JsonSerializerSettings._dateFormatString, Newtonsoft.Json.JsonSerializerSettings._dateFormatStringSet, Newtonsoft.Json.JsonSerializerSettings._dateParseHandling, Newtonsoft.Json.JsonSerializerSettings._dateTimeZoneHandling, Newtonsoft.Json.JsonSerializerSettings._defaultValueHandling, Newtonsoft.Json.JsonSerializerSettings._floatFormatHandling, Newtonsoft.Json.JsonSerializerSettings._floatParseHandling, Newtonsoft.Json.JsonSerializerSettings._formatting, Newtonsoft.Json.JsonSerializerSettings._maxDepth, Newtonsoft.Json.JsonSerializerSettings._maxDepthSet, Newtonsoft.Json.JsonSerializerSettings._metadataPropertyHandling, Newtonsoft.Json.JsonSerializerSettings._missingMemberHandling, Newtonsoft.Json.JsonSerializerSettings._nullValueHandling, Newtonsoft.Json.JsonSerializerSettings._objectCreationHandling, Newtonsoft.Json.JsonSerializerSettings._preserveReferencesHandling, Newtonsoft.Json.JsonSerializerSettings._referenceLoopHandling, Newtonsoft.Json.JsonSerializerSettings._stringEscapeHandling, Newtonsoft.Json.JsonSerializerSettings._typeNameAssemblyFormatHandling, Newtonsoft.Json.JsonSerializerSettings._typeNameHandling, Newtonsoft.Json.JsonSerializerSettings.ConstructorHandling, Newtonsoft.Json.JsonSerializerSettings.Context, Newtonsoft.Json.JsonSerializerSettings.ContractResolver, Newtonsoft.Json.JsonSerializer.Converters, Newtonsoft.Json.JsonSerializerSettings.Converters, Newtonsoft.Json.JsonSerializerSettings.DefaultValueHandling, Newtonsoft.Json.JsonSerializerSettings.EqualityComparer, Newtonsoft.Json.JsonSerializerSettings.Error, System.Collections.ObjectModel.Collection< T >.Insert(), Newtonsoft.Json.JsonSerializerSettings.MetadataPropertyHandling, Newtonsoft.Json.JsonSerializerSettings.MissingMemberHandling, Newtonsoft.Json.JsonSerializerSettings.NullValueHandling, Newtonsoft.Json.JsonSerializerSettings.ObjectCreationHandling, Newtonsoft.Json.JsonSerializerSettings.PreserveReferencesHandling, Newtonsoft.Json.JsonSerializerSettings.ReferenceLoopHandling, Newtonsoft.Json.JsonSerializerSettings.ReferenceResolverProvider, Newtonsoft.Json.JsonSerializerSettings.SerializationBinder, Newtonsoft.Json.JsonSerializerSettings.TraceWriter, Newtonsoft.Json.JsonSerializerSettings.TypeNameAssemblyFormatHandling, and Newtonsoft.Json.JsonSerializerSettings.TypeNameHandling.
Referenced by Newtonsoft.Json.JsonSerializer.Create(), and Newtonsoft.Json.JsonSerializer.CreateDefault().