Terraria Decompiled: Newtonsoft.Json.JsonSerializer.PopulateInternal
PopulateInternal()
virtual void Newtonsoft.Json.JsonSerializer.PopulateInternal (JsonReader reader, object target) inline package virtual
Reimplemented in Newtonsoft.Json.Serialization.JsonSerializerProxy.
Definition at line 806 of file JsonSerializer.cs.
        {
            ValidationUtils.ArgumentNotNull(reader, "reader");
            ValidationUtils.ArgumentNotNull(target, "target");
            CultureInfo cultureInfo;
            DateTimeZoneHandling? dateTimeZoneHandling;
            DateParseHandling? dateParseHandling;
            FloatParseHandling? floatParseHandling;
            int? num;
            string text;
            this.SetupReader(reader, out cultureInfo, out dateTimeZoneHandling, out dateParseHandling, out floatParseHandling, out num, out text);
            TraceJsonReader traceJsonReader = ((this.TraceWriter != null && this.TraceWriter.LevelFilter >= 4) ? new TraceJsonReader(reader) : null);
            new JsonSerializerInternalReader(this).Populate(traceJsonReader ?? reader, target);
            if (traceJsonReader != null)
            {
                this.TraceWriter.Trace(4, traceJsonReader.GetDeserializedJsonMessage(), null);
            }
            this.ResetReader(reader, cultureInfo, dateTimeZoneHandling, dateParseHandling, floatParseHandling, num, text);
        }
References Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(), Newtonsoft.Json.Serialization.TraceJsonReader.GetDeserializedJsonMessage(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(), Newtonsoft.Json.JsonSerializer.ResetReader(), Newtonsoft.Json.JsonSerializer.SetupReader(), System.text, Newtonsoft.Json.Serialization.ITraceWriter.Trace(), and Newtonsoft.Json.JsonSerializer.TraceWriter.
Referenced by Newtonsoft.Json.JsonSerializer.Populate().