Terraria Decompiled: System.Buffers.TlsOverPerCoreLockedStacksArrayPool.PerCoreLockedStacks.TryPush
TryPush()
void System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >.PerCoreLockedStacks.TryPush (T[] array) inline
Definition at line 289 of file TlsOverPerCoreLockedStacksArrayPool.cs.
            {
                TlsOverPerCoreLockedStacksArrayPool<T>.LockedStack[] perCoreStacks = this._perCoreStacks;
                int num = RuntimeThread.GetCurrentProcessorId() % perCoreStacks.Length;
                for (int i = 0; i < perCoreStacks.Length; i++)
                {
                    if (perCoreStacks[num].TryPush(array))
                    {
                        return;
                    }
                    if (++num == perCoreStacks.Length)
                    {
                        num = 0;
                    }
                }
            }
References System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >.PerCoreLockedStacks._perCoreStacks, System.array, Internal.Runtime.Augments.RuntimeThread.GetCurrentProcessorId(), and System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >.PerCoreLockedStacks.TryPush().
Referenced by System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >.PerCoreLockedStacks.TryPush().