Terraria Decompiled: Terraria.GameContent.UI.Elements.UIBestiarySortingOptionsGrid.ClickOption
ClickOption()
void Terraria.GameContent.UI.Elements.UIBestiarySortingOptionsGrid.ClickOption (UIMouseEvent evt, UIElement listeningElement) inline private
Definition at line 118 of file UIBestiarySortingOptionsGrid.cs.
        {
            int num = ((GroupOptionButton<int>)listeningElement).OptionValue;
            if (num == this._currentSelected)
            {
                num = this._defaultStepIndex;
            }
            foreach (GroupOptionButton<int> groupOptionButton in this._buttonsBySorting)
            {
                bool flag = num == groupOptionButton.OptionValue;
                groupOptionButton.SetCurrentOption(flag ? num : (-1));
                if (flag)
                {
                    groupOptionButton.SetColor(new Color(152, 175, 235), 1f);
                }
                else
                {
                    groupOptionButton.SetColor(Colors.InventoryDefaultColor, 0.7f);
                }
            }
            this._currentSelected = num;
            this._sorter.SetPrioritizedStepIndex(num);
            if (this.OnClickingOption != null)
            {
                this.OnClickingOption();
            }
        }
References Terraria.GameContent.UI.Elements.UIBestiarySortingOptionsGrid._buttonsBySorting, Terraria.GameContent.UI.Elements.UIBestiarySortingOptionsGrid._currentSelected, Terraria.GameContent.UI.Elements.UIBestiarySortingOptionsGrid._defaultStepIndex, Terraria.GameContent.UI.Elements.UIBestiarySortingOptionsGrid._sorter, Terraria.ID.Colors.InventoryDefaultColor, Terraria.GameContent.UI.Elements.UIBestiarySortingOptionsGrid.OnClickingOption, Terraria.GameContent.UI.Elements.GroupOptionButton< T >.OptionValue, Terraria.GameContent.UI.Elements.GroupOptionButton< T >.SetColor(), Terraria.GameContent.UI.Elements.GroupOptionButton< T >.SetCurrentOption(), and Terraria.DataStructures.EntrySorter< TEntryType, TStepType >.SetPrioritizedStepIndex().
Referenced by Terraria.GameContent.UI.Elements.UIBestiarySortingOptionsGrid.BuildGrid().