Terraria Decompiled: Terraria.Graphics.Renderers.ItemTransferParticle.Draw
Draw()
void Terraria.Graphics.Renderers.ItemTransferParticle.Draw (ref ParticleRendererSettings settings, SpriteBatch spritebatch) inline
Implements Terraria.Graphics.Renderers.IParticle.
Definition at line 73 of file ItemTransferParticle.cs.
        {
            float num = (float)this._lifeTimeCounted / (float)this._lifeTimeTotal;
            float num2 = Utils.Remap(num, 0.1f, 0.5f, 0f, 0.85f, true);
            num2 = Utils.Remap(num, 0.5f, 0.9f, num2, 1f, true);
            Vector2 vector;
            Vector2.Hermite(ref this.StartPosition, ref this.BezierHelper1, ref this.EndPosition, ref this.BezierHelper2, num2, out vector);
            Vector2 vector2 = Vector2.Zero;
            if (num <= 0.15f)
            {
                vector2 = Vector2.Lerp(Vector2.Zero, this.StartOffset, num / 0.15f);
            }
            else if (num <= 0.5f)
            {
                vector2 = Vector2.Lerp(this.StartOffset, this.EndOffset, (num - 0.15f) / 0.35f);
            }
            else if (num <= 0.85f)
            {
                vector2 = this.EndOffset;
            }
            else
            {
                vector2 = Vector2.Lerp(this.EndOffset, Vector2.Zero, Utils.Remap(num, 0.85f, 0.95f, 0f, 1f, true));
            }
            vector += vector2;
            float num3 = Utils.Remap(num, 0f, 0.15f, (float)(this.TransitionIn ? 0 : 1), 1f, true) * Utils.Remap(num, 0.85f, 0.95f, 1f, 0f, true);
            Color color = (this.Fullbright ? Color.White : Lighting.GetColor(vector.ToTileCoordinates()));
            int num4 = 31;
            int num5 = 32;
            if (this.InInventory)
            {
                num5 = 32;
                num3 = 1f;
                float num6 = num;
                num6 *= num6;
                vector = Vector2.Lerp(this.StartPosition - new Vector2(26f, 26f) * Main.inventoryScale, this.EndPosition - new Vector2(26f, 26f) * Main.inventoryScale, num6);
                num4 = 14;
            }
            if (this.InInventory)
            {
                ItemSlot.Draw(spritebatch, ref this._itemInstance, num4, settings.AnchorPosition + vector, color);
                return;
            }
            ItemSlot.DrawItemIcon(this._itemInstance, num4, Main.spriteBatch, settings.AnchorPosition + vector, this._itemInstance.scale * num3, (float)num5, color, 1f, false);
        }
References Terraria.Graphics.Renderers.ItemTransferParticle._itemInstance, Terraria.Graphics.Renderers.ItemTransferParticle._lifeTimeCounted, Terraria.Graphics.Renderers.ItemTransferParticle._lifeTimeTotal, Terraria.Graphics.Renderers.ItemTransferParticle.BezierHelper1, Terraria.Graphics.Renderers.ItemTransferParticle.BezierHelper2, Terraria.UI.ItemSlot.Draw(), Terraria.UI.ItemSlot.DrawItemIcon(), Terraria.Graphics.Renderers.ItemTransferParticle.EndOffset, Terraria.Graphics.Renderers.ItemTransferParticle.EndPosition, Terraria.Lighting.GetColor(), Microsoft.Xna.Framework.Vector2.Hermite(), Terraria.Graphics.Renderers.ItemTransferParticle.InInventory, Terraria.Main.inventoryScale, Microsoft.Xna.Framework.Vector2.Lerp(), Terraria.Utils.Remap(), Terraria.Main.spriteBatch, Terraria.Graphics.Renderers.ItemTransferParticle.StartOffset, Terraria.Graphics.Renderers.ItemTransferParticle.StartPosition, Microsoft.Xna.Framework.Graphics.Vector2, and Microsoft.Xna.Framework.Vector2.Zero.