Terraria Decompiled: System.Runtime.Remoting.Lifetime.Lease.ProcessSponsorResponse
ProcessSponsorResponse()
void System.Runtime.Remoting.Lifetime.Lease.ProcessSponsorResponse (object state, bool timedOut) inline private
Definition at line 201 of file Lease.cs.
        {
            if (!timedOut)
            {
                try
                {
                    IAsyncResult asyncResult = (IAsyncResult)state;
                    TimeSpan timeSpan = this._renewalDelegate.EndInvoke(asyncResult);
                    if (timeSpan != TimeSpan.Zero)
                    {
                        this.Renew(timeSpan);
                        this._currentState = LeaseState.Active;
                        this._renewingSponsors = null;
                        return;
                    }
                }
                catch
                {
                }
            }
            this.Unregister((ISponsor)this._renewingSponsors.Dequeue());
            this.CheckNextSponsor();
        }
References System.Runtime.Remoting.Lifetime.Lease._renewalDelegate, System.Runtime.Remoting.Lifetime.Lease._renewingSponsors, System.Runtime.Remoting.Lifetime.Lease.CheckNextSponsor(), System.Collections.Queue.Dequeue(), System.Runtime.Remoting.Lifetime.Lease.Renew(), System.state, System.Runtime.Remoting.Lifetime.Lease.Unregister(), and System.TimeSpan.Zero.
Referenced by System.Runtime.Remoting.Lifetime.Lease.CheckNextSponsor().