Terraria Decompiled: System.Runtime.Remoting.Lifetime.Lease.CheckNextSponsor
CheckNextSponsor()
void System.Runtime.Remoting.Lifetime.Lease.CheckNextSponsor () inline private
Definition at line 186 of file Lease.cs.
        {
            if (this._renewingSponsors.Count == 0)
            {
                this._currentState = LeaseState.Expired;
                this._renewingSponsors = null;
                return;
            }
            ISponsor sponsor = (ISponsor)this._renewingSponsors.Peek();
            this._renewalDelegate = new Lease.RenewalDelegate(sponsor.Renewal);
            IAsyncResult asyncResult = this._renewalDelegate.BeginInvoke(this, null, null);
            ThreadPool.RegisterWaitForSingleObject(asyncResult.AsyncWaitHandle, new WaitOrTimerCallback(this.ProcessSponsorResponse), asyncResult, this._sponsorshipTimeout, true);
        }
References System.Runtime.Remoting.Lifetime.Lease._renewalDelegate, System.Runtime.Remoting.Lifetime.Lease._renewingSponsors, System.Runtime.Remoting.Lifetime.Lease._sponsorshipTimeout, System.IAsyncResult.AsyncWaitHandle, System.Collections.Queue.Count, System.Collections.Queue.Peek(), System.Runtime.Remoting.Lifetime.Lease.ProcessSponsorResponse(), System.Threading.ThreadPool.RegisterWaitForSingleObject(), System.Runtime.Remoting.Lifetime.ISponsor.Renewal(), and System.Runtime.Remoting.Lifetime.Lease.RenewalDelegate().
Referenced by System.Runtime.Remoting.Lifetime.Lease.ProcessSponsorResponse(), and System.Runtime.Remoting.Lifetime.Lease.UpdateState().