Terraria Decompiled: Terraria.Testing.WindowsPerformanceDiagnostics.MonitorPerformanceCounters
MonitorPerformanceCounters()
static void Terraria.Testing.WindowsPerformanceDiagnostics.MonitorPerformanceCounters () inline static private
Definition at line 185 of file WindowsPerformanceDiagnostics.cs.
        {
            if (WindowsPerformanceDiagnostics.PdhOpenQuery(IntPtr.Zero, IntPtr.Zero, out WindowsPerformanceDiagnostics.queryHandle) != 0)
            {
                return;
            }
            WindowsPerformanceDiagnostics.AddCounter("\\System\\Processor Queue Length", ref WindowsPerformanceDiagnostics.processorQueueLengthHandle);
            WindowsPerformanceDiagnostics.RecreateCoreCounters();
            WindowsPerformanceDiagnostics.RecreateThreadCounters();
            for (;;)
            {
                int num = (WindowsPerformanceDiagnostics._data.PinnedToProcessor ? WindowsPerformanceDiagnostics._data.CurrentProcessor : (-1));
                if (num != WindowsPerformanceDiagnostics.MonitoringCoreNumber)
                {
                    WindowsPerformanceDiagnostics.MonitoringCoreNumber = num;
                    WindowsPerformanceDiagnostics.RecreateCoreCounters();
                }
                Thread.Sleep(250);
                WindowsPerformanceDiagnostics.PdhCollectQueryData(WindowsPerformanceDiagnostics.queryHandle);
                double? num2;
                WindowsPerformanceDiagnostics.ReadCounter(WindowsPerformanceDiagnostics.processorPerformanceHandle, out num2);
                double? num3;
                WindowsPerformanceDiagnostics.ReadCounter(WindowsPerformanceDiagnostics.processorQueueLengthHandle, out num3);
                double num4;
                if (!WindowsPerformanceDiagnostics.ReadCounter(WindowsPerformanceDiagnostics.threadProcessIdHandle, out num4))
                {
                    WindowsPerformanceDiagnostics.ProcessCopyNumber = 0;
                    WindowsPerformanceDiagnostics.RecreateThreadCounters();
                }
                else if (num4 != (double)WindowsPerformanceDiagnostics.PID)
                {
                    WindowsPerformanceDiagnostics.ProcessCopyNumber++;
                    WindowsPerformanceDiagnostics.RecreateThreadCounters();
                }
                else
                {
                    double? num5;
                    WindowsPerformanceDiagnostics.ReadCounter(WindowsPerformanceDiagnostics.threadProcessorTimeHandle, out num5);
                    object @lock = WindowsPerformanceDiagnostics._lock;
                    lock (@lock)
                    {
                        WindowsPerformanceDiagnostics._data.ProcessorThrottlePercent = num2;
                        WindowsPerformanceDiagnostics._data.ContentionQueueLength = ((num3 != null) ? new long?((long)num3.Value) : null);
                        WindowsPerformanceDiagnostics.LowPassUpdate(ref WindowsPerformanceDiagnostics._data.MainThreadCPUPercent, num5, 0.25f);
                        WindowsPerformanceDiagnostics._data.RecommendUnpinning = WindowsPerformanceDiagnostics.ShouldRecommendUnpinning();
                    }
                }
            }
        }
References Terraria.Testing.WindowsPerformanceDiagnostics._data, Terraria.Testing.WindowsPerformanceDiagnostics._lock, Terraria.Testing.WindowsPerformanceDiagnostics.AddCounter(), Terraria.Testing.WindowsPerformanceDiagnostics.LowPassUpdate(), Terraria.Testing.WindowsPerformanceDiagnostics.MonitoringCoreNumber, Terraria.Testing.WindowsPerformanceDiagnostics.PdhCollectQueryData(), Terraria.Testing.WindowsPerformanceDiagnostics.PdhOpenQuery(), Terraria.Testing.WindowsPerformanceDiagnostics.PID, Terraria.Testing.WindowsPerformanceDiagnostics.ProcessCopyNumber, Terraria.Testing.WindowsPerformanceDiagnostics.processorPerformanceHandle, Terraria.Testing.WindowsPerformanceDiagnostics.processorQueueLengthHandle, Terraria.Testing.WindowsPerformanceDiagnostics.queryHandle, Terraria.Testing.WindowsPerformanceDiagnostics.ReadCounter(), Terraria.Testing.WindowsPerformanceDiagnostics.RecreateCoreCounters(), Terraria.Testing.WindowsPerformanceDiagnostics.RecreateThreadCounters(), Terraria.Testing.WindowsPerformanceDiagnostics.ShouldRecommendUnpinning(), System.Threading.Thread.Sleep(), Terraria.Testing.WindowsPerformanceDiagnostics.threadProcessIdHandle, Terraria.Testing.WindowsPerformanceDiagnostics.threadProcessorTimeHandle, and System.IntPtr.Zero.
Referenced by Terraria.Testing.WindowsPerformanceDiagnostics.GetData().