Terraria Decompiled: Microsoft.Xna.Framework.Media.BaseYUVPlayer.GL_pushState
GL_pushState()
unsafe void Microsoft.Xna.Framework.Media.BaseYUVPlayer.GL_pushState () inline protected
Definition at line 65 of file BaseYUVPlayer.cs.
        {
            FNA3D.FNA3D_BeginPassRestore(this.currentDevice.GLDevice, this.shaderProgram.glEffect, this.stateChangesPtr);
            for (int i = 0; i < 3; i++)
            {
                this.oldTextures[i] = this.currentDevice.Textures[i];
                this.oldSamplers[i] = this.currentDevice.SamplerStates[i];
                this.currentDevice.Textures[i] = this.yuvTextures[i];
                this.currentDevice.SamplerStates[i] = SamplerState.LinearClamp;
            }
            this.oldBuffers = this.currentDevice.GetVertexBuffers();
            this.currentDevice.SetVertexBuffers(new VertexBufferBinding[] { this.vertBuffer });
            int renderTargetsNoAllocEXT = this.currentDevice.GetRenderTargetsNoAllocEXT(null);
            Array.Resize<RenderTargetBinding>(ref this.oldTargets, renderTargetsNoAllocEXT);
            this.currentDevice.GetRenderTargetsNoAllocEXT(this.oldTargets);
            fixed (FNA3D.FNA3D_RenderTargetBinding* ptr = &this.nativeVideoTexture[0])
            {
                FNA3D.FNA3D_RenderTargetBinding* ptr2 = ptr;
                GraphicsDevice.PrepareRenderTargetBindings(ptr2, this.videoTexture);
                FNA3D.FNA3D_SetRenderTargets(this.currentDevice.GLDevice, ptr2, this.videoTexture.Length, IntPtr.Zero, DepthFormat.None, 0);
            }
            this.prevBlend = this.currentDevice.BlendState;
            this.prevDepthStencil = this.currentDevice.DepthStencilState;
            this.prevRasterizer = this.currentDevice.RasterizerState;
            this.currentDevice.BlendState = BlendState.Opaque;
            this.currentDevice.DepthStencilState = DepthStencilState.None;
            this.currentDevice.RasterizerState = RasterizerState.CullNone;
            this.prevViewport = this.currentDevice.Viewport;
            FNA3D.FNA3D_SetViewport(this.currentDevice.GLDevice, ref this.viewport.viewport);
        }
References Microsoft.Xna.Framework.Graphics.GraphicsDevice.BlendState, Microsoft.Xna.Framework.Graphics.RasterizerState.CullNone, Microsoft.Xna.Framework.Media.BaseYUVPlayer.currentDevice, Microsoft.Xna.Framework.Graphics.GraphicsDevice.DepthStencilState, Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_BeginPassRestore(), Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_SetRenderTargets(), Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_SetViewport(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.GetRenderTargetsNoAllocEXT(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.GetVertexBuffers(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.GLDevice, Microsoft.Xna.Framework.Graphics.SamplerState.LinearClamp, Microsoft.Xna.Framework.Graphics.DepthStencilState.None, Microsoft.Xna.Framework.Media.BaseYUVPlayer.oldSamplers, Microsoft.Xna.Framework.Media.BaseYUVPlayer.oldTargets, Microsoft.Xna.Framework.Media.BaseYUVPlayer.oldTextures, Microsoft.Xna.Framework.Graphics.BlendState.Opaque, Microsoft.Xna.Framework.Graphics.GraphicsDevice.PrepareRenderTargetBindings(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.RasterizerState, Microsoft.Xna.Framework.Graphics.GraphicsDevice.SamplerStates, Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetVertexBuffers(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.Textures, Microsoft.Xna.Framework.Media.BaseYUVPlayer.videoTexture, Microsoft.Xna.Framework.Graphics.GraphicsDevice.Viewport, Microsoft.Xna.Framework.Media.BaseYUVPlayer.yuvTextures, and System.IntPtr.Zero.