Terraria Decompiled: Microsoft.Xna.Framework.Media.BaseYUVPlayer.GL_dispose
GL_dispose()
void Microsoft.Xna.Framework.Media.BaseYUVPlayer.GL_dispose () inline protected
Definition at line 20 of file BaseYUVPlayer.cs.
        {
            if (this.currentDevice == null)
            {
                return;
            }
            this.currentDevice = null;
            if (this.shaderProgram != null)
            {
                this.shaderProgram.Dispose();
            }
            if (this.stateChangesPtr != IntPtr.Zero)
            {
                FNAPlatform.Free(this.stateChangesPtr);
            }
            if (this.vertBuffer.VertexBuffer != null)
            {
                this.vertBuffer.VertexBuffer.Dispose();
            }
            for (int i = 0; i < 3; i++)
            {
                if (this.yuvTextures[i] != null)
                {
                    this.yuvTextures[i].Dispose();
                }
            }
        }
References Microsoft.Xna.Framework.Media.BaseYUVPlayer.currentDevice, Microsoft.Xna.Framework.Graphics.Effect.Dispose(), Microsoft.Xna.Framework.Graphics.Texture.Dispose(), Microsoft.Xna.Framework.Graphics.VertexBuffer.Dispose(), Microsoft.Xna.Framework.FNAPlatform.Free, Microsoft.Xna.Framework.Media.BaseYUVPlayer.shaderProgram, Microsoft.Xna.Framework.Media.BaseYUVPlayer.stateChangesPtr, Microsoft.Xna.Framework.Media.BaseYUVPlayer.vertBuffer, Microsoft.Xna.Framework.Graphics.VertexBufferBinding.VertexBuffer, Microsoft.Xna.Framework.Media.BaseYUVPlayer.yuvTextures, and System.IntPtr.Zero.
Referenced by Microsoft.Xna.Framework.Media.BaseYUVPlayer.Dispose().