Terraria Decompiled: Microsoft.Xna.Framework.Media.BaseYUVPlayer.GL_popState
GL_popState()
unsafe void Microsoft.Xna.Framework.Media.BaseYUVPlayer.GL_popState () inline protected
Definition at line 97 of file BaseYUVPlayer.cs.
        {
            FNA3D.FNA3D_EndPassRestore(this.currentDevice.GLDevice, this.shaderProgram.glEffect);
            this.currentDevice.BlendState = this.prevBlend;
            this.currentDevice.DepthStencilState = this.prevDepthStencil;
            this.currentDevice.RasterizerState = this.prevRasterizer;
            this.prevBlend = null;
            this.prevDepthStencil = null;
            this.prevRasterizer = null;
            if (this.oldTargets == null || this.oldTargets.Length == 0)
            {
                FNA3D.FNA3D_SetRenderTargets(this.currentDevice.GLDevice, IntPtr.Zero, 0, IntPtr.Zero, DepthFormat.None, 0);
            }
            else
            {
                IRenderTarget renderTarget = this.oldTargets[0].RenderTarget as IRenderTarget;
                fixed (FNA3D.FNA3D_RenderTargetBinding* ptr = &this.nativeOldTargets[0])
                {
                    FNA3D.FNA3D_RenderTargetBinding* ptr2 = ptr;
                    GraphicsDevice.PrepareRenderTargetBindings(ptr2, this.oldTargets);
                    FNA3D.FNA3D_SetRenderTargets(this.currentDevice.GLDevice, ptr2, this.oldTargets.Length, renderTarget.DepthStencilBuffer, renderTarget.DepthStencilFormat, (renderTarget.RenderTargetUsage > RenderTargetUsage.DiscardContents) ? 1 : 0);
                }
            }
            this.oldTargets = null;
            FNA3D.FNA3D_SetViewport(this.currentDevice.GLDevice, ref this.prevViewport.viewport);
            this.currentDevice.SetVertexBuffers(this.oldBuffers);
            this.oldBuffers = null;
            this.currentDevice.Textures.ignoreTargets = true;
            for (int i = 0; i < 3; i++)
            {
                if (this.oldTextures[i] == null || !this.oldTextures[i].IsDisposed)
                {
                    this.currentDevice.Textures[i] = this.oldTextures[i];
                }
                this.currentDevice.SamplerStates[i] = this.oldSamplers[i];
                this.oldTextures[i] = null;
                this.oldSamplers[i] = null;
            }
            this.currentDevice.Textures.ignoreTargets = false;
        }
References Microsoft.Xna.Framework.Media.BaseYUVPlayer.currentDevice, Microsoft.Xna.Framework.Graphics.IRenderTarget.DepthStencilBuffer, Microsoft.Xna.Framework.Graphics.IRenderTarget.DepthStencilFormat, Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_EndPassRestore(), Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_SetRenderTargets(), Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_SetViewport(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.GLDevice, Microsoft.Xna.Framework.Media.BaseYUVPlayer.IsDisposed, Microsoft.Xna.Framework.Media.BaseYUVPlayer.oldBuffers, Microsoft.Xna.Framework.Media.BaseYUVPlayer.oldSamplers, Microsoft.Xna.Framework.Media.BaseYUVPlayer.oldTargets, Microsoft.Xna.Framework.Media.BaseYUVPlayer.oldTextures, Microsoft.Xna.Framework.Graphics.GraphicsDevice.PrepareRenderTargetBindings(), Microsoft.Xna.Framework.Media.BaseYUVPlayer.prevBlend, Microsoft.Xna.Framework.Media.BaseYUVPlayer.prevDepthStencil, Microsoft.Xna.Framework.Media.BaseYUVPlayer.prevRasterizer, Microsoft.Xna.Framework.Graphics.RenderTargetBinding.RenderTarget, Microsoft.Xna.Framework.Graphics.IRenderTarget.RenderTargetUsage, Microsoft.Xna.Framework.Graphics.GraphicsDevice.SamplerStates, Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetVertexBuffers(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.Textures, and System.IntPtr.Zero.