Terraria Decompiled: Terraria.GameContent.Biomes.DitherSnake.GetPositionAlongSnake
GetPositionAlongSnake()
double Terraria.GameContent.Biomes.DitherSnake.GetPositionAlongSnake (Vector2D pos) inline
Definition at line 67 of file DitherSnake.cs.
        {
            DungeonControlLine lineContaining = this.GetLineContaining(pos, null, 0);
            double num;
            double num2;
            if (!lineContaining.CanPaint((int)pos.X, (int)pos.Y, out num, out num2))
            {
                num2 = 0.5;
            }
            return (double)lineContaining.Index + num2;
        }
References Terraria.GameContent.Biomes.DungeonControlLine.CanPaint(), Terraria.GameContent.Biomes.DitherSnake.GetLineContaining(), ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.HallwayCalculator().