Terraria Decompiled: Terraria.GameContent.Biomes.DitherSnake.IsLineInsideBorder
IsLineInsideBorder() [1/2]
bool Terraria.GameContent.Biomes.DitherSnake.IsLineInsideBorder (Vector2D from, Vector2D to) inline
Definition at line 190 of file DitherSnake.cs.
        {
            DungeonControlLine line = this.GetClosestLineTo(from);
            return Utils.PlotLine(from.ToPoint(), to.ToPoint(), delegate(int x, int y)
            {
                line = this.GetLineContaining(new Vector2D((double)x, (double)y), line, 0);
                return line != null && line.IsInsideBorder(new Point(x, y));
            }, true);
        }
References Terraria.GameContent.Biomes.DitherSnake.GetClosestLineTo(), Terraria.GameContent.Biomes.DitherSnake.GetLineContaining(), Terraria.GameContent.Biomes.DungeonControlLine.IsInsideBorder(), and Terraria.Utils.PlotLine().