Terraria Decompiled: Terraria.GameContent.Biomes.DitherSnake.IsCircleInsideBorderWithMatchingStyle
IsCircleInsideBorderWithMatchingStyle()
bool Terraria.GameContent.Biomes.DitherSnake.IsCircleInsideBorderWithMatchingStyle (DungeonControlLine nearbyLine, Vector2D center, int radius) inline
Definition at line 87 of file DitherSnake.cs.
        {
            double num = (double)radius * DitherSnake.ExtraBuffer;
            foreach (Vector2D vector2D in DitherSnake.CircleTestPoints)
            {
                Vector2D vector2D2 = center + vector2D * num;
                DungeonControlLine lineContaining = this.GetLineContaining(vector2D2, nearbyLine, 0);
                if (lineContaining == null || lineContaining.Style != nearbyLine.Style)
                {
                    return false;
                }
                if (!lineContaining.IsInsideBorder(vector2D2.ToPoint()))
                {
                    return false;
                }
            }
            return true;
        }
References Terraria.GameContent.Biomes.DitherSnake.CircleTestPoints, Terraria.GameContent.Biomes.DitherSnake.ExtraBuffer, Terraria.GameContent.Biomes.DitherSnake.GetLineContaining(), Terraria.GameContent.Biomes.DungeonControlLine.IsInsideBorder(), Terraria.GameContent.Biomes.DungeonControlLine.Style, and Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.Style.
Referenced by Terraria.GameContent.Biomes.DitherSnake.GetRoomPositionInsideBorder(), and Terraria.GameContent.Biomes.DitherSnake.IsCircleInsideBorderWithStyle().