Terraria Decompiled: Terraria.DataStructures.ActiveSections.IsSectionActive
IsSectionActive()
static bool Terraria.DataStructures.ActiveSections.IsSectionActive (Point sectionCoords) inline static
Definition at line 67 of file ActiveSections.cs.
        {
            sectionCoords = sectionCoords.ClampSectionCoords();
            return ActiveSections.LastActiveTime[sectionCoords.X, sectionCoords.Y] + ActiveSections.SectionInactiveTime >= Main.GameUpdateCount;
        }
References Terraria.Main.GameUpdateCount, Terraria.DataStructures.ActiveSections.LastActiveTime, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.DataStructures.ActiveSections.CheckSection(), Terraria.GameContent.LeashedEntity.Clear(), Terraria.Main.DrawDebugSectionsOnMap(), and Terraria.GameContent.LeashedEntity.RecheckActiveSections().