Terraria Decompiled: Terraria.GameContent.Biomes.DitherSnake.GetLineContaining
GetLineContaining()
DungeonControlLine Terraria.GameContent.Biomes.DitherSnake.GetLineContaining (Vector2D pos, DungeonControlLine initialGuess = null, int depth = 0) inline
Definition at line 45 of file DitherSnake.cs.
        {
            if (initialGuess == null)
            {
                initialGuess = this.GetClosestLineTo(pos);
            }
            if (depth == 3)
            {
                return null;
            }
            if (Vector2D.Dot(pos - initialGuess.Start, initialGuess.StartTangent) < 0.0 && initialGuess.Prev != null)
            {
                return this.GetLineContaining(pos, initialGuess.Prev, depth + 1);
            }
            if (Vector2D.Dot(pos - initialGuess.End, initialGuess.EndTangent) < 0.0 && initialGuess.Next != null)
            {
                return this.GetLineContaining(pos, initialGuess.Next, depth + 1);
            }
            return initialGuess;
        }
References ReLogic.Utilities.Vector2D.Dot(), Terraria.GameContent.Biomes.DitherSnake.GetClosestLineTo(), and Terraria.GameContent.Biomes.DitherSnake.GetLineContaining().
Referenced by Terraria.GameContent.Biomes.DitherSnake.GetLineContaining(), Terraria.GameContent.Biomes.DitherSnake.GetPositionAlongSnake(), Terraria.GameContent.Biomes.DitherSnake.IsCircleInsideBorderWithMatchingStyle(), Terraria.GameContent.Biomes.DitherSnake.IsLineInsideBorder(), and Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.MakeHall().