Terraria Decompiled: Terraria.GameContent.Biomes.DitherSnake.GetRoomPositionInsideBorder
GetRoomPositionInsideBorder()
Vector2D Terraria.GameContent.Biomes.DitherSnake.GetRoomPositionInsideBorder (DungeonControlLine line, double normalizedDistanceAlong, double normalizedDistanceFrom, int roomRadius, out SnakeOrientation orientation) inline
Definition at line 107 of file DitherSnake.cs.
        {
            orientation = SnakeOrientation.Unknown;
            Vector2D vector2D = Vector2D.Lerp(line.Start, line.End, normalizedDistanceAlong);
            Vector2D potentialRoomPosition = line.GetPotentialRoomPosition(normalizedDistanceAlong, 0.0, roomRadius);
            Vector2D potentialRoomPosition2 = line.GetPotentialRoomPosition(normalizedDistanceAlong, 1.0, roomRadius);
            Vector2D vector2D2 = ((potentialRoomPosition.Y < potentialRoomPosition2.Y) ? potentialRoomPosition : potentialRoomPosition2);
            Vector2D vector2D3 = ((potentialRoomPosition.Y > potentialRoomPosition2.Y) ? potentialRoomPosition : potentialRoomPosition2);
            for (int i = 0; i < 4; i++)
            {
                Vector2D potentialRoomPosition3 = line.GetPotentialRoomPosition(normalizedDistanceAlong, normalizedDistanceFrom, roomRadius);
                if (this.IsCircleInsideBorderWithMatchingStyle(line, potentialRoomPosition3, roomRadius))
                {
                    double num = potentialRoomPosition3.Distance(vector2D);
                    double num2 = potentialRoomPosition3.Distance(vector2D2);
                    double num3 = potentialRoomPosition3.Distance(vector2D3);
                    if (num < num2 && num < num3)
                    {
                        orientation = SnakeOrientation.Center;
                    }
                    else if (num2 < num3)
                    {
                        orientation = SnakeOrientation.Top;
                    }
                    else
                    {
                        orientation = SnakeOrientation.Bottom;
                    }
                    return potentialRoomPosition3;
                }
                normalizedDistanceFrom *= 0.8;
            }
            orientation = SnakeOrientation.Center;
            return line.Center;
        }
References Terraria.GameContent.Biomes.DungeonControlLine.Center, ReLogic.Utilities.Vector2D.Distance(), Terraria.GameContent.Biomes.DungeonControlLine.End, Terraria.GameContent.Biomes.DungeonControlLine.GetPotentialRoomPosition(), Terraria.GameContent.Biomes.DitherSnake.IsCircleInsideBorderWithMatchingStyle(), ReLogic.Utilities.Vector2D.Lerp(), Terraria.GameContent.Biomes.DungeonControlLine.Start, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.TryMakeRegularRoomOnLine().