Terraria Decompiled: System.Security.Cryptography.Rfc2898DeriveBytes.Dispose
Dispose()
override void System.Security.Cryptography.Rfc2898DeriveBytes.Dispose (bool disposing) inline protected virtual
Reimplemented from System.Security.Cryptography.DeriveBytes.
Definition at line 156 of file Rfc2898DeriveBytes.cs.
        {
            if (disposing)
            {
                if (this._hmac != null)
                {
                    this._hmac.Dispose();
                    this._hmac = null;
                }
                if (this._buffer != null)
                {
                    Array.Clear(this._buffer, 0, this._buffer.Length);
                }
                if (this._password != null)
                {
                    Array.Clear(this._password, 0, this._password.Length);
                }
                if (this._salt != null)
                {
                    Array.Clear(this._salt, 0, this._salt.Length);
                }
            }
            base.Dispose(disposing);
        }
References System.Security.Cryptography.Rfc2898DeriveBytes._buffer, System.Security.Cryptography.Rfc2898DeriveBytes._hmac, System.Security.Cryptography.Rfc2898DeriveBytes._password, System.Security.Cryptography.Rfc2898DeriveBytes._salt, System.Array.Clear(), System.Security.Cryptography.HMAC.Dispose(), and System.Security.Cryptography.Rfc2898DeriveBytes.Func().