Terraria Decompiled: System.Security.Cryptography.Rfc2898DeriveBytes.Func
Func()
byte[] System.Security.Cryptography.Rfc2898DeriveBytes.Func () inline private
Definition at line 273 of file Rfc2898DeriveBytes.cs.
        {
            byte[] array = new byte[this._salt.Length + 4];
            Buffer.BlockCopy(this._salt, 0, array, 0, this._salt.Length);
            Helpers.WriteInt(this._block, array, this._salt.Length);
            byte[] array2 = ArrayPool<byte>.Shared.Rent(this._blockSize);
            byte[] array5;
            try
            {
                Span<byte> span = new Span<byte>(array2, 0, this._blockSize);
                int num;
                if (!this._hmac.TryComputeHash(array, span, out num) || num != this._blockSize)
                {
                    throw new CryptographicException();
                }
                byte[] array3 = new byte[this._blockSize];
                span.CopyTo(array3);
                int num2 = 2;
                while ((long)num2 <= (long)((ulong)this._iterations))
                {
                    if (!this._hmac.TryComputeHash(span, span, out num) || num != this._blockSize)
                    {
                        throw new CryptographicException();
                    }
                    for (int i = 0; i < this._blockSize; i++)
                    {
                        byte[] array4 = array3;
                        int num3 = i;
                        array4[num3] ^= array2[i];
                    }
                    num2++;
                }
                this._block += 1U;
                array5 = array3;
            }
            finally
            {
                Array.Clear(array2, 0, this._blockSize);
                ArrayPool<byte>.Shared.Return(array2, false);
            }
            return array5;
        }
References System.Security.Cryptography.Rfc2898DeriveBytes._block, System.Security.Cryptography.Rfc2898DeriveBytes._blockSize, System.Security.Cryptography.Rfc2898DeriveBytes._hmac, System.Security.Cryptography.Rfc2898DeriveBytes._iterations, System.Security.Cryptography.Rfc2898DeriveBytes._salt, System.array, System.Buffer.BlockCopy(), System.Array.Clear(), System.Span< T >.CopyTo(), System.Security.Cryptography.Rfc2898DeriveBytes.Func(), System.Buffers.ArrayPool< T >.Shared, System.Security.Cryptography.HashAlgorithm.TryComputeHash(), System.U, and Internal.Cryptography.Helpers.WriteInt().
Referenced by System.Security.Cryptography.Rfc2898DeriveBytes.Dispose(), System.Security.Cryptography.Rfc2898DeriveBytes.Func(), System.Security.Cryptography.Rfc2898DeriveBytes.GetBytes(), System.Security.Cryptography.Rfc2898DeriveBytes.Initialize(), System.Security.Cryptography.Rfc2898DeriveBytes.OpenHmac(), System.Security.Cryptography.Rfc2898DeriveBytes.Rfc2898DeriveBytes(), and System.Security.Cryptography.Rfc2898DeriveBytes.Rfc2898DeriveBytes().