Terraria Decompiled: Microsoft.Xna.Framework.Audio.Cue.Stop
Stop()
void Microsoft.Xna.Framework.Audio.Cue.Stop (AudioStopOptions options) inline
Definition at line 262 of file Cue.cs.
        {
            FAudio.FACTCue_Stop(this.handle, (options == AudioStopOptions.Immediate) ? 1U : 0U);
        }
References FAudio.FACTCue_Stop(), Microsoft.Xna.Framework.Audio.Cue.handle, and System.U.
Referenced by Terraria.Audio.MusicCueHolder.PurgeCue(), Terraria.Audio.MusicCueHolder.Stop(), and Terraria.Audio.CueAudioTrack.Stop().