Terraria Decompiled: Microsoft.Xna.Framework.Audio.Cue.SetVariable
SetVariable()
void Microsoft.Xna.Framework.Audio.Cue.SetVariable (string name, float value) inline
Definition at line 247 of file Cue.cs.
        {
            if (string.IsNullOrEmpty(name))
            {
                throw new ArgumentNullException("name");
            }
            ushort num = FAudio.FACTCue_GetVariableIndex(this.handle, name);
            if (num == 65535)
            {
                throw new InvalidOperationException("Invalid variable name!");
            }
            FAudio.FACTCue_SetVariable(this.handle, num, value);
        }
References FAudio.FACTCue_GetVariableIndex(), FAudio.FACTCue_SetVariable(), Microsoft.Xna.Framework.Audio.Cue.handle, System.name, and System.value.
Referenced by Terraria.Audio.CueAudioTrack.SetVariable(), and Terraria.Audio.MusicCueHolder.SetVolume().