Terraria Decompiled: rail.RailCallBackHelper.RegisterCallback
RegisterCallback()
void rail.RailCallBackHelper.RegisterCallback (RAILEventID event_id, RailEventCallBackHandler handler) inline
Definition at line 20 of file RailCallBackHelper.cs.
        {
            object obj = RailCallBackHelper.locker_;
            lock (obj)
            {
                if (RailCallBackHelper.eventHandlers_.ContainsKey(event_id))
                {
                    Dictionary<RAILEventID, RailEventCallBackHandler> dictionary = RailCallBackHelper.eventHandlers_;
                    dictionary[event_id] = (RailEventCallBackHandler)Delegate.Combine(dictionary[event_id], handler);
                }
                else
                {
                    RailCallBackHelper.eventHandlers_.Add(event_id, handler);
                    RAIL_API_PINVOKE.CSharpRailRegisterEvent((int)event_id, RailCallBackHelper.delegate_);
                }
            }
        }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Delegate.Combine(), System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), rail.RAIL_API_PINVOKE.CSharpRailRegisterEvent(), rail.RailCallBackHelper.delegate_, System.dictionary, rail.RailCallBackHelper.eventHandlers_, rail.RailCallBackHelper.locker_, System.obj, and RailEventCallBackHandler().
Referenced by Terraria.Social.WeGame.AchievementsSocialModule.Initialize(), Terraria.Social.WeGame.CoreSocialModule.Initialize(), Terraria.Social.WeGame.Lobby.RegisterGameServerEvent(), Terraria.Social.WeGame.NetClientSocialModule.RegisterRailEvent(), and Terraria.Social.WeGame.NetServerSocialModule.RegisterRailEvent().