Terraria Decompiled: Newtonsoft.Json.Bson.BsonBinaryWriter.CalculateSize
CalculateSize() [1/2]
int Newtonsoft.Json.Bson.BsonBinaryWriter.CalculateSize (BsonToken t) inline private
Definition at line 214 of file BsonBinaryWriter.cs.
        {
            switch (t.Type)
            {
            case BsonType.Number:
                return 8;
            case BsonType.String:
            {
                BsonString bsonString = (BsonString)t;
                string text = (string)bsonString.Value;
                bsonString.ByteCount = ((text != null) ? BsonBinaryWriter.Encoding.GetByteCount(text) : 0);
                bsonString.CalculatedSize = this.CalculateSizeWithLength(bsonString.ByteCount, bsonString.IncludeLength);
                return bsonString.CalculatedSize;
            }
            case BsonType.Object:
            {
                BsonObject bsonObject = (BsonObject)t;
                int num = 4;
                foreach (BsonProperty bsonProperty in bsonObject)
                {
                    int num2 = 1;
                    num2 += this.CalculateSize(bsonProperty.Name);
                    num2 += this.CalculateSize(bsonProperty.Value);
                    num += num2;
                }
                num++;
                bsonObject.CalculatedSize = num;
                return num;
            }
            case BsonType.Array:
            {
                BsonArray bsonArray = (BsonArray)t;
                int num3 = 4;
                ulong num4 = 0UL;
                foreach (BsonToken bsonToken in bsonArray)
                {
                    num3++;
                    num3 += this.CalculateSize(MathUtils.IntLength(num4));
                    num3 += this.CalculateSize(bsonToken);
                    num4 += 1UL;
                }
                num3++;
                bsonArray.CalculatedSize = num3;
                return bsonArray.CalculatedSize;
            }
            case BsonType.Binary:
            {
                BsonBinary bsonBinary = (BsonBinary)t;
                byte[] array = (byte[])bsonBinary.Value;
                bsonBinary.CalculatedSize = 5 + array.Length;
                return bsonBinary.CalculatedSize;
            }
            case BsonType.Undefined:
            case BsonType.Null:
                return 0;
            case BsonType.Oid:
                return 12;
            case BsonType.Boolean:
                return 1;
            case BsonType.Date:
                return 8;
            case BsonType.Regex:
            {
                BsonRegex bsonRegex = (BsonRegex)t;
                int num5 = 0;
                num5 += this.CalculateSize(bsonRegex.Pattern);
                num5 += this.CalculateSize(bsonRegex.Options);
                bsonRegex.CalculatedSize = num5;
                return bsonRegex.CalculatedSize;
            }
            case BsonType.Integer:
                return 4;
            case BsonType.Long:
                return 8;
            }
            throw new ArgumentOutOfRangeException("t", "Unexpected token when writing BSON: {0}".FormatWith(CultureInfo.InvariantCulture, t.Type));
        }
References System.array, Newtonsoft.Json.Bson.BsonString.ByteCount, Newtonsoft.Json.Bson.BsonToken.CalculatedSize, Newtonsoft.Json.Bson.BsonBinaryWriter.CalculateSize(), Newtonsoft.Json.Bson.BsonBinaryWriter.CalculateSizeWithLength(), Newtonsoft.Json.Bson.BsonBinaryWriter.Encoding, System.Text.Encoding.GetByteCount(), Newtonsoft.Json.Bson.BsonString.IncludeLength, Newtonsoft.Json.Utilities.MathUtils.IntLength(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.Bson.BsonProperty.Name, Newtonsoft.Json.Bson.BsonRegex.Options, Newtonsoft.Json.Bson.BsonRegex.Pattern, System.text, Newtonsoft.Json.Bson.BsonToken.Type, Newtonsoft.Json.Bson.BsonProperty.Value, and Newtonsoft.Json.Bson.BsonValue.Value.