Terraria Decompiled: Newtonsoft.Json.Bson.BsonBinaryWriter.WriteTokenInternal
WriteTokenInternal()
void Newtonsoft.Json.Bson.BsonBinaryWriter.WriteTokenInternal (BsonToken t) inline private
Definition at line 57 of file BsonBinaryWriter.cs.
        {
            switch (t.Type)
            {
            case BsonType.Number:
            {
                BsonValue bsonValue = (BsonValue)t;
                this._writer.Write(Convert.ToDouble(bsonValue.Value, CultureInfo.InvariantCulture));
                return;
            }
            case BsonType.String:
            {
                BsonString bsonString = (BsonString)t;
                this.WriteString((string)bsonString.Value, bsonString.ByteCount, new int?(bsonString.CalculatedSize - 4));
                return;
            }
            case BsonType.Object:
            {
                BsonObject bsonObject = (BsonObject)t;
                this._writer.Write(bsonObject.CalculatedSize);
                foreach (BsonProperty bsonProperty in bsonObject)
                {
                    this._writer.Write((sbyte)bsonProperty.Value.Type);
                    this.WriteString((string)bsonProperty.Name.Value, bsonProperty.Name.ByteCount, default(int?));
                    this.WriteTokenInternal(bsonProperty.Value);
                }
                this._writer.Write(0);
                return;
            }
            case BsonType.Array:
            {
                BsonArray bsonArray = (BsonArray)t;
                this._writer.Write(bsonArray.CalculatedSize);
                ulong num = 0UL;
                foreach (BsonToken bsonToken in bsonArray)
                {
                    this._writer.Write((sbyte)bsonToken.Type);
                    this.WriteString(num.ToString(CultureInfo.InvariantCulture), MathUtils.IntLength(num), default(int?));
                    this.WriteTokenInternal(bsonToken);
                    num += 1UL;
                }
                this._writer.Write(0);
                return;
            }
            case BsonType.Binary:
            {
                BsonBinary bsonBinary = (BsonBinary)t;
                byte[] array = (byte[])bsonBinary.Value;
                this._writer.Write(array.Length);
                this._writer.Write((byte)bsonBinary.BinaryType);
                this._writer.Write(array);
                return;
            }
            case BsonType.Undefined:
            case BsonType.Null:
                return;
            case BsonType.Oid:
            {
                byte[] array2 = (byte[])((BsonValue)t).Value;
                this._writer.Write(array2);
                return;
            }
            case BsonType.Boolean:
                this._writer.Write(t == BsonBoolean.True);
                return;
            case BsonType.Date:
            {
                BsonValue bsonValue2 = (BsonValue)t;
                long num2;
                if (bsonValue2.Value is DateTime)
                {
                    DateTime dateTime = (DateTime)bsonValue2.Value;
                    if (this.DateTimeKindHandling == 1)
                    {
                        dateTime = dateTime.ToUniversalTime();
                    }
                    else if (this.DateTimeKindHandling == 2)
                    {
                        dateTime = dateTime.ToLocalTime();
                    }
                    num2 = DateTimeUtils.ConvertDateTimeToJavaScriptTicks(dateTime, false);
                }
                else
                {
                    DateTimeOffset dateTimeOffset = (DateTimeOffset)bsonValue2.Value;
                    num2 = DateTimeUtils.ConvertDateTimeToJavaScriptTicks(dateTimeOffset.UtcDateTime, dateTimeOffset.Offset);
                }
                this._writer.Write(num2);
                return;
            }
            case BsonType.Regex:
            {
                BsonRegex bsonRegex = (BsonRegex)t;
                this.WriteString((string)bsonRegex.Pattern.Value, bsonRegex.Pattern.ByteCount, default(int?));
                this.WriteString((string)bsonRegex.Options.Value, bsonRegex.Options.ByteCount, default(int?));
                return;
            }
            case BsonType.Integer:
            {
                BsonValue bsonValue3 = (BsonValue)t;
                this._writer.Write(Convert.ToInt32(bsonValue3.Value, CultureInfo.InvariantCulture));
                return;
            }
            case BsonType.Long:
            {
                BsonValue bsonValue4 = (BsonValue)t;
                this._writer.Write(Convert.ToInt64(bsonValue4.Value, CultureInfo.InvariantCulture));
                return;
            }
            }
            throw new ArgumentOutOfRangeException("t", "Unexpected token when writing BSON: {0}".FormatWith(CultureInfo.InvariantCulture, t.Type));
        }
References Newtonsoft.Json.Bson.BsonBinaryWriter._writer, System.array, Newtonsoft.Json.Bson.BsonBinary.BinaryType, Newtonsoft.Json.Bson.BsonString.ByteCount, Newtonsoft.Json.Bson.BsonToken.CalculatedSize, Newtonsoft.Json.Utilities.DateTimeUtils.ConvertDateTimeToJavaScriptTicks(), Newtonsoft.Json.DateTime, Newtonsoft.Json.Bson.BsonBinaryWriter.DateTimeKindHandling, Newtonsoft.Json.DateTimeOffset, Newtonsoft.Json.Utilities.MathUtils.IntLength(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.Bson.BsonProperty.Name, System.DateTimeOffset.Offset, Newtonsoft.Json.Bson.BsonRegex.Options, Newtonsoft.Json.Bson.BsonRegex.Pattern, System.Convert.ToDouble(), System.Convert.ToInt32(), System.Convert.ToInt64(), System.DateTime.ToLocalTime(), System.DateTime.ToUniversalTime(), Newtonsoft.Json.Bson.BsonBoolean.True, Newtonsoft.Json.Bson.BsonToken.Type, System.DateTimeOffset.UtcDateTime, Newtonsoft.Json.Bson.BsonProperty.Value, Newtonsoft.Json.Bson.BsonValue.Value, System.IO.BinaryWriter.Write(), Newtonsoft.Json.Bson.BsonBinaryWriter.WriteString(), and Newtonsoft.Json.Bson.BsonBinaryWriter.WriteTokenInternal().
Referenced by Newtonsoft.Json.Bson.BsonBinaryWriter.WriteToken(), and Newtonsoft.Json.Bson.BsonBinaryWriter.WriteTokenInternal().