Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.Converter.GetNameSpaceEnum
GetNameSpaceEnum()
static InternalNameSpaceE System.Runtime.Serialization.Formatters.Binary.Converter.GetNameSpaceEnum (InternalPrimitiveTypeE code, Type type, WriteObjectInfo objectInfo, out string typeName) inline static package
Definition at line 116 of file Converter.cs.
        {
            InternalNameSpaceE internalNameSpaceE = InternalNameSpaceE.None;
            typeName = null;
            if (code != InternalPrimitiveTypeE.Invalid)
            {
                switch (code)
                {
                case InternalPrimitiveTypeE.Boolean:
                case InternalPrimitiveTypeE.Byte:
                case InternalPrimitiveTypeE.Char:
                case InternalPrimitiveTypeE.Double:
                case InternalPrimitiveTypeE.Int16:
                case InternalPrimitiveTypeE.Int32:
                case InternalPrimitiveTypeE.Int64:
                case InternalPrimitiveTypeE.SByte:
                case InternalPrimitiveTypeE.Single:
                case InternalPrimitiveTypeE.TimeSpan:
                case InternalPrimitiveTypeE.DateTime:
                case InternalPrimitiveTypeE.UInt16:
                case InternalPrimitiveTypeE.UInt32:
                case InternalPrimitiveTypeE.UInt64:
                    internalNameSpaceE = InternalNameSpaceE.XdrPrimitive;
                    typeName = "System." + Converter.ToComType(code);
                    break;
                case InternalPrimitiveTypeE.Decimal:
                    internalNameSpaceE = InternalNameSpaceE.UrtSystem;
                    typeName = "System." + Converter.ToComType(code);
                    break;
                }
            }
            if (internalNameSpaceE == InternalNameSpaceE.None && type != null)
            {
                if (type == Converter.typeofString)
                {
                    internalNameSpaceE = InternalNameSpaceE.XdrString;
                }
                else if (objectInfo == null)
                {
                    typeName = type.FullName;
                    if (type.Assembly == Converter.urtAssembly)
                    {
                        internalNameSpaceE = InternalNameSpaceE.UrtSystem;
                    }
                    else
                    {
                        internalNameSpaceE = InternalNameSpaceE.UrtUser;
                    }
                }
                else
                {
                    typeName = objectInfo.GetTypeFullName();
                    if (objectInfo.GetAssemblyString().Equals(Converter.urtAssemblyString))
                    {
                        internalNameSpaceE = InternalNameSpaceE.UrtSystem;
                    }
                    else
                    {
                        internalNameSpaceE = InternalNameSpaceE.UrtUser;
                    }
                }
            }
            return internalNameSpaceE;
        }
References System.Type.Assembly, System.Type.FullName, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.GetAssemblyString(), System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.GetTypeFullName(), System.Runtime.Serialization.Formatters.Binary.Converter.ToComType(), System.Runtime.Serialization.Formatters.Binary.Converter.typeofString, System.Runtime.Serialization.Formatters.Binary.Converter.urtAssembly, and System.Runtime.Serialization.Formatters.Binary.Converter.urtAssemblyString.