Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.Converter.ToCode
ToCode()
static InternalPrimitiveTypeE System.Runtime.Serialization.Formatters.Binary.Converter.ToCode (Type type) inline static package
Definition at line 16 of file Converter.cs.
        {
            InternalPrimitiveTypeE internalPrimitiveTypeE;
            if (type != null && !type.IsPrimitive)
            {
                if (type == Converter.typeofDateTime)
                {
                    internalPrimitiveTypeE = InternalPrimitiveTypeE.DateTime;
                }
                else if (type == Converter.typeofTimeSpan)
                {
                    internalPrimitiveTypeE = InternalPrimitiveTypeE.TimeSpan;
                }
                else if (type == Converter.typeofDecimal)
                {
                    internalPrimitiveTypeE = InternalPrimitiveTypeE.Decimal;
                }
                else
                {
                    internalPrimitiveTypeE = InternalPrimitiveTypeE.Invalid;
                }
            }
            else
            {
                internalPrimitiveTypeE = Converter.ToPrimitiveTypeEnum(Type.GetTypeCode(type));
            }
            return internalPrimitiveTypeE;
        }
References System.Type.GetTypeCode(), System.Type.IsPrimitive, System.Runtime.Serialization.Formatters.Binary.Converter.ToPrimitiveTypeEnum(), System.Runtime.Serialization.Formatters.Binary.Converter.typeofDateTime, System.Runtime.Serialization.Formatters.Binary.Converter.typeofDecimal, and System.Runtime.Serialization.Formatters.Binary.Converter.typeofTimeSpan.
Referenced by System.Runtime.Serialization.Formatters.Binary.BinaryConverter.GetParserBinaryTypeInfo(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseMember(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.ToCode(), System.Runtime.Serialization.Formatters.Binary.BinaryMethodReturn.WriteArray(), System.Runtime.Serialization.Formatters.Binary.BinaryMethodCall.WriteArray(), and System.Runtime.Serialization.Formatters.Binary.IOUtil.WriteWithCode().