Terraria Decompiled: System.Globalization.TimeSpanFormat.FormatLiterals.Init
Init()
unsafe void System.Globalization.TimeSpanFormat.FormatLiterals.Init (ReadOnlySpan< char > format, bool useInvariantFieldLengths) inline package
Definition at line 429 of file TimeSpanFormat.cs.
            {
                this.dd = (this.hh = (this.mm = (this.ss = (this.ff = 0))));
                this._literals = new string[6];
                for (int i = 0; i < this._literals.Length; i++)
                {
                    this._literals[i] = string.Empty;
                }
                StringBuilder stringBuilder = StringBuilderCache.Acquire(16);
                bool flag = false;
                char c = '\'';
                int num = 0;
                int j = 0;
                while (j < format.Length)
                {
                    char c2 = (char)(*format[j]);
                    if (c2 <= 'F')
                    {
                        if (c2 <= '%')
{
                            if (c2 != '"')
{
                                if (c2 != '%')
{
                                    goto IL_01C5;
                                }
                                goto IL_01C5;
                            }
                        }
                        else if (c2 != '\'')
{
                            if (c2 != 'F')
{
                                goto IL_01C5;
                            }
                            goto IL_01B0;
                        }
                        if (flag && c == (char)(*format[j]))
{
                            if (num < 0 || num > 5)
{
                                return;
                            }
                            this._literals[num] = stringBuilder.ToString();
                            stringBuilder.Length = 0;
                            flag = false;
                        }
                        else if (!flag)
{
                            c = (char)(*format[j]);
                            flag = true;
                        }
                    }
                    else if (c2 <= 'h')
                    {
                        if (c2 != '\\')
{
                            switch (c2)
{
                            case 'd':
                                if (!flag)
{
                                    num = 1;
                                    this.dd++;
                                }
                                break;
                            case 'e':
                            case 'g':
                                goto IL_01C5;
                            case 'f':
                                goto IL_01B0;
                            case 'h':
                                if (!flag)
{
                                    num = 2;
                                    this.hh++;
                                }
                                break;
                            default:
                                goto IL_01C5;
                            }
                        }
                        else
{
                            if (flag)
{
                                goto IL_01C5;
                            }
                            j++;
                        }
                    }
                    else if (c2 != 'm')
                    {
                        if (c2 != 's')
{
                            goto IL_01C5;
                        }
                        if (!flag)
{
                            num = 4;
                            this.ss++;
                        }
                    }
                    else if (!flag)
                    {
                        num = 3;
                        this.mm++;
                    }
                    IL_01D6:
                    j++;
                    continue;
                    IL_01B0:
                    if (!flag)
                    {
                        num = 5;
                        this.ff++;
                        goto IL_01D6;
                    }
                    goto IL_01D6;
                    IL_01C5:
                    stringBuilder.Append((char)(*format[j]));
                    goto IL_01D6;
                }
                this.AppCompatLiteral = this.MinuteSecondSep + this.SecondFractionSep;
                if (useInvariantFieldLengths)
                {
                    this.dd = 2;
                    this.hh = 2;
                    this.mm = 2;
                    this.ss = 2;
                    this.ff = 7;
                }
                else
                {
                    if (this.dd < 1 || this.dd > 2)
                    {
                        this.dd = 2;
                    }
                    if (this.hh < 1 || this.hh > 2)
                    {
                        this.hh = 2;
                    }
                    if (this.mm < 1 || this.mm > 2)
                    {
                        this.mm = 2;
                    }
                    if (this.ss < 1 || this.ss > 2)
                    {
                        this.ss = 2;
                    }
                    if (this.ff < 1 || this.ff > 7)
                    {
                        this.ff = 7;
                    }
                }
                StringBuilderCache.Release(stringBuilder);
            }
References System.Globalization.TimeSpanFormat.FormatLiterals._literals, System.Text.StringBuilderCache.Acquire(), System.Text.StringBuilder.Append(), System.Globalization.TimeSpanFormat.FormatLiterals.dd, System.Globalization.TimeSpanFormat.FormatLiterals.ff, System.format, System.Globalization.TimeSpanFormat.FormatLiterals.hh, System.Globalization.TimeSpanFormat.FormatLiterals.mm, System.Text.StringBuilderCache.Release(), System.Globalization.TimeSpanFormat.FormatLiterals.SecondFractionSep, System.Globalization.TimeSpanFormat.FormatLiterals.ss, and System.Text.StringBuilder.ToString().
Referenced by System.Globalization.TimeSpanFormat.FormatStandard().