Terraria Decompiled: Terraria.GameContent.UI.States.UIVirtualKeyboard.BuildSpaceBarArea
BuildSpaceBarArea()
void Terraria.GameContent.UI.States.UIVirtualKeyboard.BuildSpaceBarArea (UIPanel mainPanel) inline private
Definition at line 316 of file UIVirtualKeyboard.cs.
        {
            UIElement.MouseEvent <>9__1;
            UIElement.MouseEvent <>9__2;
            Action createTheseTwo = delegate
            {
                bool flag = this.CanRestore();
                int num = (flag ? 4 : 5);
                bool editingSign = this._editingSign;
                int num2 = ((flag && editingSign) ? 2 : 3);
                UITextPanel<object> uitextPanel = this.CreateKeyboardButton(Language.GetText("UI.SpaceButton"), 2, 4, (this._editingSign || (this._editingChest && flag)) ? num2 : 6, true);
                UIElement uielement = uitextPanel;
                UIElement.MouseEvent mouseEvent;
                if ((mouseEvent = <>9__1) == null)
                {
                    mouseEvent = (<>9__1 = delegate(UIMouseEvent evt, UIElement listeningElement)
                    {
                        this.PressSpace();
                    });
                }
                uielement.OnLeftClick += mouseEvent;
                mainPanel.Append(uitextPanel);
                this._spacebarButton = uitextPanel;
                if (editingSign)
                {
                    UITextPanel<object> uitextPanel2 = this.CreateKeyboardButton(Language.GetText("UI.EnterButton"), num, 4, num2, true);
                    UIElement uielement2 = uitextPanel2;
                    UIElement.MouseEvent mouseEvent2;
                    if ((mouseEvent2 = <>9__2) == null)
                    {
                        mouseEvent2 = (<>9__2 = delegate(UIMouseEvent evt, UIElement listeningElement)
{
                            SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                            this._textBox.Write("\n");
                            this.ValidateText();
                        });
                    }
                    uielement2.OnLeftClick += mouseEvent2;
                    mainPanel.Append(uitextPanel2);
                    this._enterButton = uitextPanel2;
                }
            };
            createTheseTwo();
            if (this.CanRestore())
            {
                UITextPanel<object> restoreBar = this.CreateKeyboardButton(Language.GetText("UI.RestoreButton"), 6, 4, 2, true);
                restoreBar.OnLeftClick += delegate(UIMouseEvent evt, UIElement listeningElement)
                {
                    SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                    this.RestoreCanceledInput(this._keyboardContext);
                    this.ValidateText();
                    restoreBar.Remove();
                    this._enterButton.Remove();
                    this._spacebarButton.Remove();
                    createTheseTwo();
                };
                mainPanel.Append(restoreBar);
                this._restoreButton = restoreBar;
            }
        }
References Terraria.GameContent.UI.States.UIVirtualKeyboard._editingSign, Terraria.GameContent.UI.States.UIVirtualKeyboard._enterButton, Terraria.GameContent.UI.States.UIVirtualKeyboard._keyboardContext, Terraria.GameContent.UI.States.UIVirtualKeyboard._spacebarButton, Terraria.GameContent.UI.States.UIVirtualKeyboard._textBox, Terraria.UI.UIElement.Append(), Terraria.GameContent.UI.States.UIVirtualKeyboard.CanRestore(), Terraria.GameContent.UI.States.UIVirtualKeyboard.CreateKeyboardButton(), Terraria.Localization.Language.GetText(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.GameContent.UI.States.UIVirtualKeyboard.PressSpace(), Terraria.UI.UIElement.Remove(), Terraria.GameContent.UI.States.UIVirtualKeyboard.RestoreCanceledInput(), Terraria.GameContent.UI.States.UIVirtualKeyboard.ValidateText(), and Terraria.GameContent.UI.Elements.UITextBox.Write().
Referenced by Terraria.GameContent.UI.States.UIVirtualKeyboard.UIVirtualKeyboard().