Terraria Decompiled: Terraria.GameContent.UI.States.UIVirtualKeyboard.UIVirtualKeyboard
UIVirtualKeyboard() [1/2]
Terraria.GameContent.UI.States.UIVirtualKeyboard.UIVirtualKeyboard (string labelText, string startingText, UIVirtualKeyboard::KeyboardSubmitEvent submitAction, Action cancelAction, int inputMode = 0, bool allowEmpty = false, int maxLength = 20) inline
Definition at line 51 of file UIVirtualKeyboard.cs.
        {
            this._keyboardContext = inputMode;
            this._allowEmpty = allowEmpty;
            UIVirtualKeyboard.OffsetDown = 0;
            UIVirtualKeyboard.ShouldHideText = false;
            this._lastOffsetDown = 0;
            this._editingSign = this._keyboardContext == 1;
            this._editingChest = this._keyboardContext == 2;
            UIVirtualKeyboard._currentInstance = this;
            this._submitAction = submitAction;
            this._cancelAction = cancelAction;
            this._textureShift = Main.Assets.Request<Texture2D>("Images/UI/VK_Shift", 1);
            this._textureBackspace = Main.Assets.Request<Texture2D>("Images/UI/VK_Backspace", 1);
            this.Top.Pixels = (float)this._lastOffsetDown;
            float num = (float)(-5000 * this._editingSign.ToInt());
            float num2 = 270f;
            float num3 = 0f;
            float num4 = 516f;
            UIElement uielement = new UIElement();
            uielement.Width.Pixels = num4 + 8f + 16f;
            uielement.Top.Precent = num3;
            uielement.Top.Pixels = num2;
            uielement.Height.Pixels = 266f;
            uielement.HAlign = 0.5f;
            uielement.SetPadding(0f);
            this.outerLayer1 = uielement;
            UIElement uielement2 = new UIElement();
            uielement2.Width.Pixels = num4 + 8f + 16f;
            uielement2.Top.Precent = num3;
            uielement2.Top.Pixels = num2;
            uielement2.Height.Pixels = 266f;
            uielement2.HAlign = 0.5f;
            uielement2.SetPadding(0f);
            this.outerLayer2 = uielement2;
            UIPanel uipanel = new UIPanel();
            uipanel.Width.Precent = 1f;
            uipanel.Height.Pixels = 225f;
            uipanel.BackgroundColor = new Color(23, 33, 69) * 0.7f;
            uielement.Append(uipanel);
            float num5 = -50f;
            this._textBox = new UITextBox("", 0.78f, true);
            this._textBox.BackgroundColor = Color.Transparent;
            this._textBox.BorderColor = Color.Transparent;
            this._textBox.HAlign = 0.5f;
            this._textBox.Width.Pixels = num4;
            this._textBox.Top.Pixels = num5 + num2 - 10f + num;
            this._textBox.Top.Precent = num3;
            this._textBox.Height.Pixels = 37f;
            base.Append(this._textBox);
            for (int i = 0; i < 10; i++)
            {
                for (int j = 0; j < 4; j++)
                {
                    int num6 = j * 10 + i;
                    UITextPanel<object> uitextPanel = this.CreateKeyboardButton("1234567890qwertyuiopasdfghjkl'zxcvbnm,.?"[num6].ToString(), i, j, 1, true);
                    uitextPanel.OnLeftClick += this.TypeText;
                    uipanel.Append(uitextPanel);
                }
            }
            this._shiftButton = this.CreateKeyboardButton("", 0, 4, 1, false);
            this._shiftButton.PaddingLeft = 0f;
            this._shiftButton.PaddingRight = 0f;
            this._shiftButton.PaddingBottom = (this._shiftButton.PaddingTop = 0f);
            this._shiftButton.BackgroundColor = new Color(63, 82, 151) * 0.7f;
            this._shiftButton.BorderColor = this._internalBorderColor * 0.7f;
            this._shiftButton.OnMouseOver += delegate(UIMouseEvent evt, UIElement listeningElement)
            {
                this._shiftButton.BorderColor = this._internalBorderColorSelected;
                if (this._keyState != UIVirtualKeyboard.KeyState.Shift)
                {
                    this._shiftButton.BackgroundColor = new Color(73, 94, 171);
                }
            };
            this._shiftButton.OnMouseOut += delegate(UIMouseEvent evt, UIElement listeningElement)
            {
                this._shiftButton.BorderColor = this._internalBorderColor * 0.7f;
                if (this._keyState != UIVirtualKeyboard.KeyState.Shift)
                {
                    this._shiftButton.BackgroundColor = new Color(63, 82, 151) * 0.7f;
                }
            };
            this._shiftButton.OnLeftClick += delegate(UIMouseEvent evt, UIElement listeningElement)
            {
                SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                this.SetKeyState((this._keyState == UIVirtualKeyboard.KeyState.Shift) ? UIVirtualKeyboard.KeyState.Default : UIVirtualKeyboard.KeyState.Shift);
            };
            UIImage uiimage = new UIImage(this._textureShift);
            uiimage.HAlign = 0.5f;
            uiimage.VAlign = 0.5f;
            uiimage.ImageScale = 0.85f;
            this._shiftButton.Append(uiimage);
            uipanel.Append(this._shiftButton);
            this._symbolButton = this.CreateKeyboardButton("@%", 1, 4, 1, false);
            this._symbolButton.PaddingLeft = 0f;
            this._symbolButton.PaddingRight = 0f;
            this._symbolButton.BackgroundColor = new Color(63, 82, 151) * 0.7f;
            this._symbolButton.BorderColor = this._internalBorderColor * 0.7f;
            this._symbolButton.OnMouseOver += delegate(UIMouseEvent evt, UIElement listeningElement)
            {
                this._symbolButton.BorderColor = this._internalBorderColorSelected;
                if (this._keyState != UIVirtualKeyboard.KeyState.Symbol)
                {
                    this._symbolButton.BackgroundColor = new Color(73, 94, 171);
                }
            };
            this._symbolButton.OnMouseOut += delegate(UIMouseEvent evt, UIElement listeningElement)
            {
                this._symbolButton.BorderColor = this._internalBorderColor * 0.7f;
                if (this._keyState != UIVirtualKeyboard.KeyState.Symbol)
                {
                    this._symbolButton.BackgroundColor = new Color(63, 82, 151) * 0.7f;
                }
            };
            this._symbolButton.OnLeftClick += delegate(UIMouseEvent evt, UIElement listeningElement)
            {
                SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                this.SetKeyState((this._keyState == UIVirtualKeyboard.KeyState.Symbol) ? UIVirtualKeyboard.KeyState.Default : UIVirtualKeyboard.KeyState.Symbol);
            };
            uipanel.Append(this._symbolButton);
            this.BuildSpaceBarArea(uipanel);
            this._submitButton = new UITextPanel<LocalizedText>((this._editingSign || this._editingChest) ? Language.GetText("UI.Save") : Language.GetText("UI.Submit"), 0.4f, true);
            this._submitButton.Height.Pixels = 37f;
            this._submitButton.Width.Precent = 0.4f;
            this._submitButton.HAlign = 1f;
            this._submitButton.VAlign = 1f;
            this._submitButton.PaddingLeft = 0f;
            this._submitButton.PaddingRight = 0f;
            this.ValidateText();
            this._submitButton.OnMouseOver += this.FadedMouseOver;
            this._submitButton.OnMouseOut += this.FadedMouseOut;
            this._submitButton.OnMouseOver += delegate(UIMouseEvent evt, UIElement listeningElement)
            {
                this.ValidateText();
            };
            this._submitButton.OnMouseOut += delegate(UIMouseEvent evt, UIElement listeningElement)
            {
                this.ValidateText();
            };
            this._submitButton.OnLeftClick += delegate(UIMouseEvent evt, UIElement listeningElement)
            {
                UIVirtualKeyboard.Submit();
            };
            uielement.Append(this._submitButton);
            this._cancelButton = new UITextPanel<LocalizedText>(Language.GetText("UI.Cancel"), 0.4f, true);
            this.StyleKey<LocalizedText>(this._cancelButton, true);
            this._cancelButton.Height.Pixels = 37f;
            this._cancelButton.Width.Precent = 0.4f;
            this._cancelButton.VAlign = 1f;
            this._cancelButton.OnLeftClick += delegate(UIMouseEvent evt, UIElement listeningElement)
            {
                SoundEngine.PlaySound(11, -1, -1, 1, 1f, 0f);
                this._cancelAction();
            };
            this._cancelButton.OnMouseOver += this.FadedMouseOver;
            this._cancelButton.OnMouseOut += this.FadedMouseOut;
            uielement.Append(this._cancelButton);
            this._submitButton2 = new UITextPanel<LocalizedText>((this._editingSign || this._editingChest) ? Language.GetText("UI.Save") : Language.GetText("UI.Submit"), 0.72f, true);
            this._submitButton2.TextColor = Color.Silver;
            this._submitButton2.DrawPanel = false;
            this._submitButton2.Height.Pixels = 60f;
            this._submitButton2.Width.Precent = 0.4f;
            this._submitButton2.HAlign = 0.5f;
            this._submitButton2.VAlign = 0f;
            this._submitButton2.OnMouseOver += delegate(UIMouseEvent a, UIElement b)
            {
                ((UITextPanel<LocalizedText>)b).TextScale = 0.85f;
                ((UITextPanel<LocalizedText>)b).TextColor = Color.White;
            };
            this._submitButton2.OnMouseOut += delegate(UIMouseEvent a, UIElement b)
            {
                ((UITextPanel<LocalizedText>)b).TextScale = 0.72f;
                ((UITextPanel<LocalizedText>)b).TextColor = Color.Silver;
            };
            this._submitButton2.Top.Pixels = 50f;
            this._submitButton2.PaddingLeft = 0f;
            this._submitButton2.PaddingRight = 0f;
            this.ValidateText();
            this._submitButton2.OnMouseOver += delegate(UIMouseEvent evt, UIElement listeningElement)
            {
                this.ValidateText();
            };
            this._submitButton2.OnMouseOut += delegate(UIMouseEvent evt, UIElement listeningElement)
            {
                this.ValidateText();
            };
            this._submitButton2.OnMouseOver += this.FadedMouseOver;
            this._submitButton2.OnMouseOut += this.FadedMouseOut;
            this._submitButton2.OnLeftClick += delegate(UIMouseEvent evt, UIElement listeningElement)
            {
                if (this.TextIsValidForSubmit())
                {
                    SoundEngine.PlaySound(10, -1, -1, 1, 1f, 0f);
                    this._submitAction(this.Text.Trim());
                }
            };
            this.outerLayer2.Append(this._submitButton2);
            this._cancelButton2 = new UITextPanel<LocalizedText>(Language.GetText("UI.Cancel"), 0.72f, true);
            this._cancelButton2.TextColor = Color.Silver;
            this._cancelButton2.DrawPanel = false;
            this._cancelButton2.OnMouseOver += delegate(UIMouseEvent a, UIElement b)
            {
                ((UITextPanel<LocalizedText>)b).TextScale = 0.85f;
                ((UITextPanel<LocalizedText>)b).TextColor = Color.White;
            };
            this._cancelButton2.OnMouseOut += delegate(UIMouseEvent a, UIElement b)
            {
                ((UITextPanel<LocalizedText>)b).TextScale = 0.72f;
                ((UITextPanel<LocalizedText>)b).TextColor = Color.Silver;
            };
            this._cancelButton2.Height.Pixels = 60f;
            this._cancelButton2.Width.Precent = 0.4f;
            this._cancelButton2.Top.Pixels = 114f;
            this._cancelButton2.VAlign = 0f;
            this._cancelButton2.HAlign = 0.5f;
            this._cancelButton2.OnLeftClick += delegate(UIMouseEvent evt, UIElement listeningElement)
            {
                SoundEngine.PlaySound(11, -1, -1, 1, 1f, 0f);
                this._cancelAction();
            };
            this.outerLayer2.Append(this._cancelButton2);
            UITextPanel<object> uitextPanel2 = this.CreateKeyboardButton("", 8, 4, 2, true);
            uitextPanel2.OnLeftClick += delegate(UIMouseEvent evt, UIElement listeningElement)
            {
                SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                this._textBox.Backspace();
                this.ValidateText();
            };
            uitextPanel2.PaddingLeft = 0f;
            uitextPanel2.PaddingRight = 0f;
            uitextPanel2.PaddingBottom = (uitextPanel2.PaddingTop = 0f);
            uitextPanel2.Append(new UIImage(this._textureBackspace)
            {
                HAlign = 0.5f,
                VAlign = 0.5f,
                ImageScale = 0.92f
            });
            uipanel.Append(uitextPanel2);
            UIText uitext = new UIText(labelText, 0.75f, true);
            uitext.HAlign = 0.5f;
            uitext.Width.Pixels = num4;
            uitext.Top.Pixels = num5 - 37f - 4f + num2 + num;
            uitext.Top.Precent = num3;
            uitext.Height.Pixels = 37f;
            base.Append(uitext);
            this._label = uitext;
            base.Append(uielement);
            this._textBox.SetTextMaxLength(maxLength);
            this.Text = startingText;
            if (this.Text.Length == 0)
            {
                this.SetKeyState(UIVirtualKeyboard.KeyState.Shift);
            }
            UIVirtualKeyboard.ShouldHideText = true;
            UIVirtualKeyboard.OffsetDown = 9999;
            this.UpdateOffsetDown();
        }
References Terraria.GameContent.UI.States.UIVirtualKeyboard._cancelAction, Terraria.GameContent.UI.States.UIVirtualKeyboard._cancelButton, Terraria.GameContent.UI.States.UIVirtualKeyboard._cancelButton2, Terraria.GameContent.UI.States.UIVirtualKeyboard._editingChest, Terraria.GameContent.UI.States.UIVirtualKeyboard._editingSign, Terraria.GameContent.UI.States.UIVirtualKeyboard._internalBorderColorSelected, Terraria.GameContent.UI.States.UIVirtualKeyboard._keyState, Terraria.GameContent.UI.States.UIVirtualKeyboard._lastOffsetDown, Terraria.GameContent.UI.States.UIVirtualKeyboard._shiftButton, Terraria.GameContent.UI.States.UIVirtualKeyboard._submitAction, Terraria.GameContent.UI.States.UIVirtualKeyboard._submitButton, Terraria.GameContent.UI.States.UIVirtualKeyboard._submitButton2, Terraria.GameContent.UI.States.UIVirtualKeyboard._symbolButton, Terraria.GameContent.UI.States.UIVirtualKeyboard._textBox, Terraria.GameContent.UI.States.UIVirtualKeyboard._textureBackspace, Terraria.GameContent.UI.States.UIVirtualKeyboard._textureShift, Terraria.UI.UIElement.Append(), Terraria.Main.Assets, Terraria.GameContent.UI.Elements.UITextBox.Backspace(), Terraria.GameContent.UI.States.UIVirtualKeyboard.BuildSpaceBarArea(), Microsoft.Xna.Framework.Graphics.Color, Terraria.GameContent.UI.States.UIVirtualKeyboard.CreateKeyboardButton(), Terraria.GameContent.UI.States.UIVirtualKeyboard.FadedMouseOut(), Terraria.GameContent.UI.States.UIVirtualKeyboard.FadedMouseOver(), Terraria.Localization.Language.GetText(), Terraria.UI.UIElement.HAlign, Terraria.GameContent.UI.States.UIVirtualKeyboard.outerLayer2, Terraria.Audio.SoundEngine.PlaySound(), Terraria.GameContent.UI.States.UIVirtualKeyboard.SetKeyState(), Terraria.UI.UIElement.SetPadding(), Terraria.GameContent.UI.Elements.UITextBox.SetTextMaxLength(), Microsoft.Xna.Framework.Color.Silver, Terraria.GameContent.UI.States.UIVirtualKeyboard.Submit(), Terraria.GameContent.UI.States.UIVirtualKeyboard.TextIsValidForSubmit(), System.ToString, Microsoft.Xna.Framework.Color.Transparent, Terraria.GameContent.UI.States.UIVirtualKeyboard.TypeText(), Terraria.UI.UIElement.UIElement(), Terraria.GameContent.UI.States.UIVirtualKeyboard.UpdateOffsetDown(), Terraria.GameContent.UI.States.UIVirtualKeyboard.ValidateText(), Terraria.UI.UIElement.VAlign, and Microsoft.Xna.Framework.Color.White.