Terraria Decompiled: Terraria.GameContent.UI.States.UIVirtualKeyboard.SetupGamepadPoints
SetupGamepadPoints()
void Terraria.GameContent.UI.States.UIVirtualKeyboard.SetupGamepadPoints (SpriteBatch spriteBatch) inline private
Definition at line 757 of file UIVirtualKeyboard.cs.
        {
            UILinkPointNavigator.Shortcuts.BackButtonCommand = 6;
            UILinkPointNavigator.Shortcuts.FANCYUI_SPECIAL_INSTRUCTIONS = 1;
            int num = 3002;
            int num2 = 5;
            int num3 = 10;
            int num4 = num3 * num2 - 1;
            int num5 = num3 * (num2 - 1);
            UILinkPointNavigator.SetPosition(3000, this._cancelButton.GetDimensions().Center());
            UILinkPoint uilinkPoint = UILinkPointNavigator.Points[3000];
            uilinkPoint.Unlink();
            uilinkPoint.Right = 3001;
            uilinkPoint.Up = num + num5;
            UILinkPointNavigator.SetPosition(3001, this._submitButton.GetDimensions().Center());
            uilinkPoint = UILinkPointNavigator.Points[3001];
            uilinkPoint.Unlink();
            uilinkPoint.Left = 3000;
            uilinkPoint.Up = num + num4;
            for (int i = 0; i < num2; i++)
            {
                for (int j = 0; j < num3; j++)
                {
                    int num6 = i * num3 + j;
                    int num7 = num + num6;
                    if (this._keyList[num6] != null)
                    {
                        UILinkPointNavigator.SetPosition(num7, this._keyList[num6].GetDimensions().Center());
                        uilinkPoint = UILinkPointNavigator.Points[num7];
                        uilinkPoint.Unlink();
                        int num8 = j - 1;
                        while (num8 >= 0 && this._keyList[i * num3 + num8] == this._keyList[num6])
{
                            num8--;
                        }
                        if (num8 != -1)
{
                            uilinkPoint.Left = i * num3 + num8 + num;
                        }
                        else
{
                            uilinkPoint.Left = i * num3 + (num3 - 1) + num;
                        }
                        int num9 = j + 1;
                        while (num9 <= num3 - 1 && this._keyList[i * num3 + num9] == this._keyList[num6])
{
                            num9++;
                        }
                        if (num9 != num3 && this._keyList[num6] != this._keyList[num9])
{
                            uilinkPoint.Right = i * num3 + num9 + num;
                        }
                        else
{
                            uilinkPoint.Right = i * num3 + num;
                        }
                        if (i != 0)
{
                            uilinkPoint.Up = num7 - num3;
                        }
                        if (i != num2 - 1)
{
                            uilinkPoint.Down = num7 + num3;
                        }
                        else
{
                            uilinkPoint.Down = ((j < num2) ? 3000 : 3001);
                        }
                    }
                }
            }
        }
References Terraria.GameContent.UI.States.UIVirtualKeyboard._cancelButton, Terraria.GameContent.UI.States.UIVirtualKeyboard._keyList, Terraria.GameContent.UI.States.UIVirtualKeyboard._submitButton, Terraria.UI.CalculatedStyle.Center(), Terraria.UI.UIElement.GetDimensions(), Terraria.UI.Gamepad.UILinkPointNavigator.Points, Terraria.UI.Gamepad.UILinkPointNavigator.SetPosition(), and Terraria.UI.Gamepad.UILinkPoint.Unlink().
Referenced by Terraria.GameContent.UI.States.UIVirtualKeyboard.DrawSelf(), and Terraria.GameContent.UI.States.UIVirtualKeyboard.OnActivate().