Terraria Decompiled: Terraria.GameContent.UI.States.UIVirtualKeyboard.SetKeyState
SetKeyState()
void Terraria.GameContent.UI.States.UIVirtualKeyboard.SetKeyState (UIVirtualKeyboard::KeyState keyState) inline
Definition at line 421 of file UIVirtualKeyboard.cs.
        {
            UITextPanel<object> uitextPanel = null;
            UIVirtualKeyboard.KeyState keyState2 = this._keyState;
            if (keyState2 != UIVirtualKeyboard.KeyState.Symbol)
            {
                if (keyState2 == UIVirtualKeyboard.KeyState.Shift)
                {
                    uitextPanel = this._shiftButton;
                }
            }
            else
            {
                uitextPanel = this._symbolButton;
            }
            if (uitextPanel != null)
            {
                if (uitextPanel.IsMouseHovering)
                {
                    uitextPanel.BackgroundColor = new Color(73, 94, 171);
                }
                else
                {
                    uitextPanel.BackgroundColor = new Color(63, 82, 151) * 0.7f;
                }
            }
            string text = null;
            UITextPanel<object> uitextPanel2 = null;
            switch (keyState)
            {
            case UIVirtualKeyboard.KeyState.Default:
                text = "1234567890qwertyuiopasdfghjkl'zxcvbnm,.?";
                break;
            case UIVirtualKeyboard.KeyState.Symbol:
                text = "1234567890!@#$%^&*()-_+=/\\{}[]<>;:\"`|~£¥";
                uitextPanel2 = this._symbolButton;
                break;
            case UIVirtualKeyboard.KeyState.Shift:
                text = "1234567890QWERTYUIOPASDFGHJKL'ZXCVBNM,.?";
                uitextPanel2 = this._shiftButton;
                break;
            }
            for (int i = 0; i < text.Length; i++)
            {
                this._keyList[i].SetText(text[i].ToString());
            }
            this._keyState = keyState;
            if (uitextPanel2 != null)
            {
                uitextPanel2.BackgroundColor = new Color(93, 114, 191);
            }
        }
References Terraria.GameContent.UI.States.UIVirtualKeyboard._keyList, Terraria.GameContent.UI.States.UIVirtualKeyboard._keyState, Terraria.GameContent.UI.States.UIVirtualKeyboard._shiftButton, Terraria.GameContent.UI.States.UIVirtualKeyboard._symbolButton, Microsoft.Xna.Framework.Graphics.Color, Terraria.UI.UIElement.IsMouseHovering, Terraria.GameContent.UI.Elements.UITextPanel< T >.SetText(), System.text, and System.ToString.
Referenced by Terraria.GameContent.UI.States.UIVirtualKeyboard.b__49_2(), Terraria.GameContent.UI.States.UIVirtualKeyboard.b__49_5(), Terraria.GameContent.UI.States.UIVirtualKeyboard.CycleSymbols(), Terraria.GameContent.UI.States.UIVirtualKeyboard.TypeText(), Terraria.GameContent.UI.States.UIVirtualKeyboard.UIVirtualKeyboard(), and Terraria.GameContent.UI.States.UIVirtualKeyboard.Write().