Terraria Decompiled: Terraria.GameContent.UI.States.UIVirtualKeyboard.ValidateText
ValidateText()
void Terraria.GameContent.UI.States.UIVirtualKeyboard.ValidateText () inline private
Definition at line 475 of file UIVirtualKeyboard.cs.
        {
            if (this.TextIsValidForSubmit())
            {
                this._canSubmit = true;
                this._submitButton.TextColor = Color.White;
                if (this._submitButton.IsMouseHovering)
                {
                    this._submitButton.BackgroundColor = new Color(73, 94, 171);
                    return;
                }
                this._submitButton.BackgroundColor = new Color(63, 82, 151) * 0.7f;
                return;
            }
            else
            {
                this._canSubmit = false;
                this._submitButton.TextColor = Color.Gray;
                if (this._submitButton.IsMouseHovering)
                {
                    this._submitButton.BackgroundColor = new Color(180, 60, 60) * 0.85f;
                    return;
                }
                this._submitButton.BackgroundColor = new Color(150, 40, 40) * 0.85f;
                return;
            }
        }
References Terraria.GameContent.UI.States.UIVirtualKeyboard._submitButton, Microsoft.Xna.Framework.Graphics.Color, Microsoft.Xna.Framework.Color.Gray, Terraria.GameContent.UI.States.UIVirtualKeyboard.TextIsValidForSubmit(), and Microsoft.Xna.Framework.Color.White.
Referenced by Terraria.GameContent.UI.States.UIVirtualKeyboard.b__49_12(), Terraria.GameContent.UI.States.UIVirtualKeyboard.b__49_13(), Terraria.GameContent.UI.States.UIVirtualKeyboard.b__49_18(), Terraria.GameContent.UI.States.UIVirtualKeyboard.b__49_6(), Terraria.GameContent.UI.States.UIVirtualKeyboard.b__49_7(), Terraria.GameContent.UI.States.UIVirtualKeyboard.BackSpace(), Terraria.GameContent.UI.States.UIVirtualKeyboard.BuildSpaceBarArea(), Terraria.GameContent.UI.States.UIVirtualKeyboard.PressSpace(), Terraria.GameContent.UI.States.UIVirtualKeyboard.TypeText(), Terraria.GameContent.UI.States.UIVirtualKeyboard.UIVirtualKeyboard(), and Terraria.GameContent.UI.States.UIVirtualKeyboard.Write().