Terraria Decompiled: System.IFormattable.ToString
ToString()
string System.IFormattable.ToString (string format, IFormatProvider formatProvider)
Implemented in System.DateTimeOffset, System.Numerics.Vector< T >, System.TimeSpan, Newtonsoft.Json.Linq.JValue, System.Byte, System.DateTime, System.Decimal, System.Double, System.Enum, System.Guid, System.Int16, System.Int32, System.Int64, System.SByte, System.Single, System.UInt16, System.UInt32, System.UInt64, and System.FormattableString.
Referenced by System.Text.StringBuilder.AppendFormatHelper(), CsvHelper.TypeConversion.DefaultTypeConverter.ConvertToString(), Newtonsoft.Json.JsonReader.ReadAsString(), System.Convert.ToString(), Newtonsoft.Json.Linq.JValue.ToString(), System.IO.TextWriter.Write(), and System.IO.TextWriter.WriteLine().