Terraria Decompiled: Terraria.GameContent.Achievements.AchievementsHelper.HandleSpecialEvent
HandleSpecialEvent()
static void Terraria.GameContent.Achievements.AchievementsHelper.HandleSpecialEvent (Player player, int eventID) inline static
Definition at line 442 of file AchievementsHelper.cs.
        {
            if (player.whoAmI != Main.myPlayer)
            {
                return;
            }
            switch (eventID)
            {
            case 1:
                Main.Achievements.GetCondition("STAR_POWER", "Use").Complete();
                if (player.statLifeMax == 500 && player.statManaMax == 200)
                {
                    Main.Achievements.GetCondition("TOPPED_OFF", "Use").Complete();
                    return;
                }
                break;
            case 2:
                Main.Achievements.GetCondition("GET_A_LIFE", "Use").Complete();
                if (player.statLifeMax == 500 && player.statManaMax == 200)
                {
                    Main.Achievements.GetCondition("TOPPED_OFF", "Use").Complete();
                    return;
                }
                break;
            case 3:
                Main.Achievements.GetCondition("NOT_THE_BEES", "Use").Complete();
                return;
            case 4:
                Main.Achievements.GetCondition("WATCH_YOUR_STEP", "Hit").Complete();
                return;
            case 5:
                Main.Achievements.GetCondition("RAINBOWS_AND_UNICORNS", "Use").Complete();
                return;
            case 6:
                Main.Achievements.GetCondition("YOU_AND_WHAT_ARMY", "Spawn").Complete();
                return;
            case 7:
                Main.Achievements.GetCondition("THROWING_LINES", "Use").Complete();
                return;
            case 8:
                Main.Achievements.GetCondition("LUCKY_BREAK", "Hit").Complete();
                return;
            case 9:
                Main.Achievements.GetCondition("VEHICULAR_MANSLAUGHTER", "Hit").Complete();
                return;
            case 10:
                Main.Achievements.GetCondition("ROCK_BOTTOM", "Reach").Complete();
                return;
            case 11:
                Main.Achievements.GetCondition("INTO_ORBIT", "Reach").Complete();
                return;
            case 12:
                Main.Achievements.GetCondition("WHERES_MY_HONEY", "Reach").Complete();
                return;
            case 13:
                Main.Achievements.GetCondition("JEEPERS_CREEPERS", "Reach").Complete();
                return;
            case 14:
                Main.Achievements.GetCondition("ITS_GETTING_HOT_IN_HERE", "Reach").Complete();
                return;
            case 15:
                Main.Achievements.GetCondition("FUNKYTOWN", "Reach").Complete();
                return;
            case 16:
                Main.Achievements.GetCondition("I_AM_LOOT", "Peek").Complete();
                return;
            case 17:
                Main.Achievements.GetCondition("FLY_A_KITE_ON_A_WINDY_DAY", "Use").Complete();
                return;
            case 18:
                Main.Achievements.GetCondition("FOUND_GRAVEYARD", "Reach").Complete();
                return;
            case 19:
                Main.Achievements.GetCondition("GO_LAVA_FISHING", "Do").Complete();
                return;
            case 20:
                Main.Achievements.GetCondition("TALK_TO_NPC_AT_MAX_HAPPINESS", "Do").Complete();
                return;
            case 21:
                Main.Achievements.GetCondition("PET_THE_PET", "Do").Complete();
                return;
            case 22:
                Main.Achievements.GetCondition("FIND_A_FAIRY", "Do").Complete();
                return;
            case 23:
                Main.Achievements.GetCondition("DIE_TO_DEAD_MANS_CHEST", "Do").Complete();
                return;
            case 24:
                Main.Achievements.GetCondition("GAIN_TORCH_GODS_FAVOR", "Use").Complete();
                return;
            case 25:
                Main.Achievements.GetCondition("DRINK_BOTTLED_WATER_WHILE_DROWNING", "Use").Complete();
                return;
            case 26:
                Main.Achievements.GetCondition("PLAY_ON_A_SPECIAL_SEED", "Do").Complete();
                return;
            case 27:
                Main.Achievements.GetCondition("PURIFY_ENTIRE_WORLD", "Do").Complete();
                break;
            default:
                return;
            }
        }
References Terraria.Main.Achievements, Terraria.Main.myPlayer, Terraria.Player.statLifeMax, Terraria.Player.statManaMax, and Terraria.Entity.whoAmI.
Referenced by Terraria.NPC.AI_112_FairyCritter(), Terraria.DataStructures.ArmorSetBonuses.Benefits.Bee(), Terraria.Projectile.BombsHurtPlayers(), Terraria.Player.BordersMovement(), Terraria.Projectile.Damage_EVP(), Terraria.Main.DryadText_WorldPurityOrStardewValleyBit(), Terraria.Player.FreeUpPetsAndMinions(), Terraria.GameContent.NPCInteractions.Actions.DryadPurification.Interact(), Terraria.Player.ItemCheck(), Terraria.Player.ItemCheck_Shoot(), Terraria.Player.ItemCheck_UseLifeCrystal(), Terraria.Player.ItemCheck_UseLifeFruit(), Terraria.Player.ItemCheck_UseManaCrystal(), Terraria.Player.ItemCheck_UseTorchGodsFavor(), Terraria.Player.KillMe(), Terraria.Player.PetAnimal(), Terraria.Player.PetMount(), Terraria.Player.QuickHeal(), Terraria.Projectile.SetFishingCheckResults(), Terraria.Player.SetTalkNPC(), Terraria.Player.TileInteractionsUse(), Terraria.Player.Update(), Terraria.Player.UpdateArmorSetsOld(), Terraria.Player.UpdateBiomes(), and Terraria.Mount.UpdateEffects().