Terraria Decompiled: Terraria.GameContent.Achievements.AchievementsHelper.OnPlayerEnteredWorld
OnPlayerEnteredWorld()
static void Terraria.GameContent.Achievements.AchievementsHelper.OnPlayerEnteredWorld (Player player) inline static package
Definition at line 246 of file AchievementsHelper.cs.
        {
            if (AchievementsHelper.OnItemPickup != null)
            {
                for (int i = 0; i < 58; i++)
                {
                    AchievementsHelper.OnItemPickup(player, (short)player.inventory[i].type, player.inventory[i].stack);
                }
                for (int j = 0; j < player.armor.Length; j++)
                {
                    AchievementsHelper.OnItemPickup(player, (short)player.armor[j].type, player.armor[j].stack);
                }
                for (int k = 0; k < player.dye.Length; k++)
                {
                    AchievementsHelper.OnItemPickup(player, (short)player.dye[k].type, player.dye[k].stack);
                }
                for (int l = 0; l < player.miscEquips.Length; l++)
                {
                    AchievementsHelper.OnItemPickup(player, (short)player.miscEquips[l].type, player.miscEquips[l].stack);
                }
                for (int m = 0; m < player.miscDyes.Length; m++)
                {
                    AchievementsHelper.OnItemPickup(player, (short)player.miscDyes[m].type, player.miscDyes[m].stack);
                }
                for (int n = 0; n < player.bank.item.Length; n++)
                {
                    AchievementsHelper.OnItemPickup(player, (short)player.bank.item[n].type, player.bank.item[n].stack);
                }
                for (int num = 0; num < player.bank2.item.Length; num++)
                {
                    AchievementsHelper.OnItemPickup(player, (short)player.bank2.item[num].type, player.bank2.item[num].stack);
                }
                for (int num2 = 0; num2 < player.bank3.item.Length; num2++)
                {
                    AchievementsHelper.OnItemPickup(player, (short)player.bank3.item[num2].type, player.bank3.item[num2].stack);
                }
                for (int num3 = 0; num3 < player.bank4.item.Length; num3++)
                {
                    AchievementsHelper.OnItemPickup(player, (short)player.bank4.item[num3].type, player.bank4.item[num3].stack);
                }
                for (int num4 = 0; num4 < player.Loadouts.Length; num4++)
                {
                    Item[] array = player.Loadouts[num4].Armor;
                    for (int num5 = 0; num5 < array.Length; num5++)
                    {
                        AchievementsHelper.OnItemPickup(player, (short)array[num5].type, array[num5].stack);
                    }
                    array = player.Loadouts[num4].Dye;
                    for (int num6 = 0; num6 < array.Length; num6++)
                    {
                        AchievementsHelper.OnItemPickup(player, (short)array[num6].type, array[num6].stack);
                    }
                }
            }
            if (player.statManaMax > 20)
            {
                Main.Achievements.GetCondition("STAR_POWER", "Use").Complete();
            }
            if (player.statLifeMax == 500 && player.statManaMax == 200)
            {
                Main.Achievements.GetCondition("TOPPED_OFF", "Use").Complete();
            }
            if (player.miscEquips[4].type > 0)
            {
                Main.Achievements.GetCondition("HOLD_ON_TIGHT", "Equip").Complete();
            }
            if (player.miscEquips[3].type > 0)
            {
                Main.Achievements.GetCondition("THE_CAVALRY", "Equip").Complete();
            }
            for (int num7 = 0; num7 < player.armor.Length; num7++)
            {
                if (player.armor[num7].wingSlot > 0)
                {
                    Main.Achievements.GetCondition("HEAD_IN_THE_CLOUDS", "Equip").Complete();
                    break;
                }
            }
            if (player.armor[0].stack > 0 && player.armor[1].stack > 0 && player.armor[2].stack > 0)
            {
                Main.Achievements.GetCondition("MATCHING_ATTIRE", "Equip").Complete();
            }
            if (player.armor[10].stack > 0 && player.armor[11].stack > 0 && player.armor[12].stack > 0)
            {
                Main.Achievements.GetCondition("FASHION_STATEMENT", "Equip").Complete();
            }
            bool flag = true;
            for (int num8 = 0; num8 < 10; num8++)
            {
                if (player.IsItemSlotUnlockedAndUsable(num8) && (player.dye[num8].type < 1 || player.dye[num8].stack < 1))
                {
                    flag = false;
                }
            }
            if (flag)
            {
                Main.Achievements.GetCondition("DYE_HARD", "Equip").Complete();
            }
            if (player.unlockedBiomeTorches)
            {
                Main.Achievements.GetCondition("GAIN_TORCH_GODS_FAVOR", "Use").Complete();
            }
            WorldGen.CheckAchievement_RealEstateAndTownSlimes();
            AchievementsHelper.TryGrantingBestiary100PercentAchievement();
        }
References Terraria.Main.Achievements, Terraria.EquipmentLoadout.Armor, Terraria.Player.armor, System.array, Terraria.Player.bank, Terraria.Player.bank2, Terraria.Player.bank3, Terraria.Player.bank4, Terraria.WorldGen.CheckAchievement_RealEstateAndTownSlimes(), Terraria.EquipmentLoadout.Dye, Terraria.Player.dye, Terraria.Player.inventory, Terraria.Player.IsItemSlotUnlockedAndUsable(), Terraria.Chest.item, Terraria.Player.Loadouts, Terraria.Player.miscDyes, Terraria.Player.miscEquips, Terraria.GameContent.Achievements.AchievementsHelper.OnItemPickup, System.stack, Terraria.Item.stack, Terraria.Player.statLifeMax, Terraria.Player.statManaMax, Terraria.GameContent.Achievements.AchievementsHelper.TryGrantingBestiary100PercentAchievement(), Terraria.Item.type, Terraria.Player.unlockedBiomeTorches, and Terraria.Item.wingSlot.
Referenced by Terraria.GameContent.Achievements.AchievementsHelper.Initialize().