Terraria Decompiled: Terraria.GameContent.Achievements.AchievementsHelper.MechaMayhem_Kill
MechaMayhem_Kill()
static void Terraria.GameContent.Achievements.AchievementsHelper.MechaMayhem_Kill (int justKilled) inline static
Definition at line 641 of file AchievementsHelper.cs.
        {
            if (!AchievementsHelper.mayhemOK)
            {
                return;
            }
            if (justKilled == 125 || justKilled == 126)
            {
                AchievementsHelper.mayhem1down = true;
            }
            else if (!NPC.AnyNPCs(125) && !NPC.AnyNPCs(126) && !AchievementsHelper.mayhem1down)
            {
                AchievementsHelper.mayhemOK = false;
                return;
            }
            if (justKilled == 134)
            {
                AchievementsHelper.mayhem2down = true;
            }
            else if (!NPC.AnyNPCs(134) && !AchievementsHelper.mayhem2down)
            {
                AchievementsHelper.mayhemOK = false;
                return;
            }
            if (justKilled == 127)
            {
                AchievementsHelper.mayhem3down = true;
            }
            else if (!NPC.AnyNPCs(127) && !AchievementsHelper.mayhem3down)
            {
                AchievementsHelper.mayhemOK = false;
                return;
            }
            if (AchievementsHelper.mayhem1down && AchievementsHelper.mayhem2down && AchievementsHelper.mayhem3down)
            {
                AchievementsHelper.NotifyProgressionEvent(21);
            }
        }
References Terraria.NPC.AnyNPCs(), Terraria.GameContent.Achievements.AchievementsHelper.mayhem1down, Terraria.GameContent.Achievements.AchievementsHelper.mayhem2down, Terraria.GameContent.Achievements.AchievementsHelper.mayhem3down, Terraria.GameContent.Achievements.AchievementsHelper.mayhemOK, and Terraria.GameContent.Achievements.AchievementsHelper.NotifyProgressionEvent().
Referenced by Terraria.NPC.CountKillForAchievements().