Terraria Decompiled: Newtonsoft.Json.Serialization.JsonProperty.GetResolvedDefaultValue
GetResolvedDefaultValue()
object Newtonsoft.Json.Serialization.JsonProperty.GetResolvedDefaultValue () inline package
Definition at line 270 of file JsonProperty.cs.
        {
            if (this._propertyType == null)
            {
                return null;
            }
            if (!this._hasExplicitDefaultValue && !this._hasGeneratedDefaultValue)
            {
                this._defaultValue = ReflectionUtils.GetDefaultValue(this.PropertyType);
                this._hasGeneratedDefaultValue = true;
            }
            return this._defaultValue;
        }
References Newtonsoft.Json.Serialization.JsonProperty._defaultValue, Newtonsoft.Json.Serialization.JsonProperty._hasExplicitDefaultValue, Newtonsoft.Json.Serialization.JsonProperty._hasGeneratedDefaultValue, Newtonsoft.Json.Serialization.JsonProperty._propertyType, Newtonsoft.Json.Utilities.ReflectionUtils.GetDefaultValue(), and Newtonsoft.Json.Serialization.JsonProperty.PropertyType.
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CalculatePropertyDetails(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EndProcessProperty(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ShouldSetPropertyValue(), and Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.ShouldWriteProperty().