Terraria Decompiled: Newtonsoft.Json.Serialization.JsonProperty.WritePropertyName
WritePropertyName()
void Newtonsoft.Json.Serialization.JsonProperty.WritePropertyName (JsonWriter writer) inline package
Definition at line 549 of file JsonProperty.cs.
        {
            if (this._skipPropertyNameEscape)
            {
                writer.WritePropertyName(this.PropertyName, false);
                return;
            }
            writer.WritePropertyName(this.PropertyName);
        }
References Newtonsoft.Json.Serialization.JsonProperty._skipPropertyNameEscape, Newtonsoft.Json.Serialization.JsonProperty.PropertyName, and Newtonsoft.Json.JsonWriter.WritePropertyName().
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDynamic(), and Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject().