Terraria Decompiled: Terraria.Graphics.Effects.SkyManager.Instance
Instance
SkyManager Terraria.Graphics.Effects.SkyManager.Instance = new SkyManager() static
Definition at line 130 of file SkyManager.cs.
Referenced by Terraria.GameContent.Skies.AmbientSky.AnActiveSkyConflictsWithAmbience(), Terraria.Main.ApplyColorOfTheSkiesToTiles(), Terraria.SceneState.ApplyVisuals(), Terraria.Main.ClearVisualPostProcessEffects(), Terraria.GameContent.NetModules.NetAmbienceModule.Deserialize(), Terraria.Main.DoUpdate(), Terraria.GameContent.Skies.AmbientSky.Draw(), Terraria.Main.DrawMenu(), Terraria.Main.DrawSurfaceBG(), Terraria.Main.DrawSurfaceBG_BackMountainsStep1(), Terraria.Main.DrawSurfaceBG_BackMountainsStep2(), Terraria.Main.DrawSurfaceBG_Corrupt(), Terraria.Main.DrawSurfaceBG_Crimson(), Terraria.Main.DrawSurfaceBG_Desert(), Terraria.Main.DrawSurfaceBG_Forest(), Terraria.Main.DrawSurfaceBG_GoodEvilDesert(), Terraria.Main.DrawSurfaceBG_Hallow(), Terraria.Main.DrawSurfaceBG_Jungle(), Terraria.Main.DrawSurfaceBG_Mushroom(), Terraria.Main.DrawSurfaceBG_Snow(), Terraria.Main.DrawUnderworldBackground(), Terraria.Main.DrawUnderworldBackgroundLayer(), Terraria.Initializers.ScreenEffectInitializer.LoadSkies(), Terraria.SceneState.ManageSpecialBiomeVisuals(), Terraria.GameContent.Skies.AuroraSky.ModifyTileColor(), Terraria.GameContent.Skies.AmbientSky.Spawn(), Terraria.Main.StartSlimeRain(), Terraria.Main.StopSlimeRain(), Terraria.Main.TryPlayingCreditsRoll(), Terraria.GameContent.Events.CreditsRollEvent.TryStartingCreditsRoll(), Terraria.GameContent.Skies.AmbientSky.Update(), Terraria.GameContent.Skies.CreditsRollSky.Update(), Terraria.GameContent.Events.BirthdayParty.UpdateTime(), and Terraria.GameContent.Events.LanternNight.UpdateTime().