Terraria Decompiled: Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_06_NormalHats
DrawPlayer_06_NormalHats()
static void Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_06_NormalHats (ref PlayerDrawHeadSet drawinfo) inline static
Definition at line 363 of file PlayerDrawHeadLayers.cs.
        {
            if (drawinfo.drawPlayer.head == 270)
            {
                PlayerDrawHeadLayers.DrawPlayer_04_CapricornMask(ref drawinfo);
                return;
            }
            if (drawinfo.drawPlayer.head == 265)
            {
                PlayerDrawHeadLayers.DrawPlayer_04_BadgersHat(ref drawinfo);
                return;
            }
            if (drawinfo.drawPlayer.head == 282)
            {
                PlayerDrawHeadLayers.DrawPlayer_04_DeadCellsBeheadedHead(ref drawinfo);
                return;
            }
            if (drawinfo.helmetIsNormal)
            {
                Rectangle hairFrame = drawinfo.HairFrame;
                Color color = drawinfo.colorArmorHead;
                int num = drawinfo.cHead;
                if (ArmorIDs.Head.Sets.UseSkinColor[drawinfo.drawPlayer.head])
                {
                    if (drawinfo.drawPlayer.isDisplayDollOrInanimate)
                    {
                        color = drawinfo.colorDisplayDollSkin;
                    }
                    else
                    {
                        color = drawinfo.colorHead;
                    }
                    num = drawinfo.skinDyePacked;
                }
                PlayerDrawHeadLayers.QuickCDD(drawinfo.DrawData, num, TextureAssets.ArmorHead[drawinfo.drawPlayer.head].Value, drawinfo.helmetOffset + new Vector2(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.bodyFrameMemory.Width / 2) + (float)(drawinfo.drawPlayer.width / 2), drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.bodyFrameMemory.Height + 4f) + drawinfo.drawPlayer.headPosition + drawinfo.headVect, new Rectangle?(hairFrame), color, drawinfo.drawPlayer.headRotation, drawinfo.headVect, drawinfo.scale, drawinfo.playerEffect, 0f);
                if (drawinfo.drawPlayer.head == 109)
                {
                    Texture2D value = TextureAssets.Extra[276].Value;
                    PlayerDrawHeadLayers.QuickCDD(drawinfo.DrawData, 0, value, drawinfo.helmetOffset + new Vector2(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.bodyFrameMemory.Width / 2) + (float)(drawinfo.drawPlayer.width / 2), drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.bodyFrameMemory.Height + 4f) + drawinfo.drawPlayer.headPosition + drawinfo.headVect, new Rectangle?(hairFrame), color, drawinfo.drawPlayer.headRotation, drawinfo.headVect, drawinfo.scale, drawinfo.playerEffect, 0f);
                }
                if (drawinfo.drawPlayer.head == 271)
                {
                    int num2 = PlayerDrawLayers.DrawPlayer_Head_GetTVScreen(drawinfo.drawPlayer);
                    if (num2 != 0)
                    {
                        Texture2D value2 = TextureAssets.GlowMask[309].Value;
                        int num3 = drawinfo.drawPlayer.miscCounter % 20 / 5;
                        if (num2 == 5)
{
                            num3 = 0;
                            if (drawinfo.drawPlayer.eyeHelper.EyeFrameToShow > 0)
{
                                num3 = 2;
                            }
                        }
                        Rectangle rectangle = value2.Frame(6, 4, num2, num3, -2, 0);
                        PlayerDrawHeadLayers.QuickCDD(drawinfo.DrawData, drawinfo.cHead, value2, drawinfo.helmetOffset + new Vector2(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.bodyFrameMemory.Width / 2) + (float)(drawinfo.drawPlayer.width / 2), drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.bodyFrameMemory.Height + 4f) + drawinfo.drawPlayer.headPosition + drawinfo.headVect, new Rectangle?(rectangle), drawinfo.colorArmorHead, drawinfo.drawPlayer.headRotation, drawinfo.headVect, drawinfo.scale, drawinfo.playerEffect, 0f);
                    }
                }
            }
        }
References Terraria.GameContent.TextureAssets.ArmorHead, Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_04_BadgersHat(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_04_CapricornMask(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_04_DeadCellsBeheadedHead(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_Head_GetTVScreen(), Terraria.GameContent.TextureAssets.Extra, Terraria.GameContent.TextureAssets.GlowMask, Terraria.DataStructures.PlayerDrawHeadLayers.QuickCDD(), Terraria.Main.screenPosition, Terraria.ID.ArmorIDs.Head.Sets.UseSkinColor, System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayerHead(), and Terraria.GameContent.PlayerHeadDrawRenderTargetContent.DrawTheContent().