Terraria Decompiled: Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_RenderAllLayers
DrawPlayer_RenderAllLayers()
static void Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_RenderAllLayers (ref PlayerDrawHeadSet drawinfo) inline static
Definition at line 492 of file PlayerDrawHeadLayers.cs.
        {
            List<DrawData> drawData = drawinfo.DrawData;
            Effect pixelShader = Main.pixelShader;
            Projectile[] projectile = Main.projectile;
            SpriteBatch spriteBatch = Main.spriteBatch;
            for (int i = 0; i < drawData.Count; i++)
            {
                DrawData drawData2 = drawData[i];
                if (drawData2.sourceRect == null)
                {
                    drawData2.sourceRect = new Rectangle?(drawData2.texture.Frame(1, 1, 0, 0, 0, 0));
                }
                PlayerDrawHelper.SetShaderForData(drawinfo.drawPlayer, drawinfo.cHead, ref drawData2);
                if (drawData2.texture != null)
                {
                    drawData2.Draw(spriteBatch);
                }
            }
            pixelShader.CurrentTechnique.Passes[0].Apply();
        }
References System.Collections.Generic.List< T >.Count, Microsoft.Xna.Framework.Graphics.Effect.CurrentTechnique, Terraria.DataStructures.DrawData.Draw(), Microsoft.Xna.Framework.Graphics.EffectTechnique.Passes, Terraria.Main.pixelShader, Terraria.Main.projectile, Terraria.DataStructures.PlayerDrawHelper.SetShaderForData(), Terraria.DataStructures.DrawData.sourceRect, Terraria.Main.spriteBatch, and Terraria.DataStructures.DrawData.texture.
Referenced by Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayerHead(), and Terraria.GameContent.PlayerHeadDrawRenderTargetContent.DrawTheContent().