Terraria Decompiled: Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_00_BackHelmet
DrawPlayer_00_BackHelmet()
static void Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_00_BackHelmet (ref PlayerDrawHeadSet drawinfo) inline static
Definition at line 20 of file PlayerDrawHeadLayers.cs.
        {
            if (drawinfo.drawPlayer.head < 0 || drawinfo.drawPlayer.head >= ArmorIDs.Head.Count)
            {
                return;
            }
            int num = ArmorIDs.Head.Sets.FrontToBackID[drawinfo.drawPlayer.head];
            if (num < 0)
            {
                return;
            }
            Rectangle hairFrame = drawinfo.HairFrame;
            PlayerDrawHeadLayers.QuickCDD(drawinfo.DrawData, drawinfo.cHead, TextureAssets.ArmorHead[num].Value, drawinfo.helmetOffset + new Vector2(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.bodyFrameMemory.Width / 2) + (float)(drawinfo.drawPlayer.width / 2), drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.bodyFrameMemory.Height + 4f) + drawinfo.drawPlayer.headPosition + drawinfo.headVect, new Rectangle?(hairFrame), drawinfo.colorArmorHead, drawinfo.drawPlayer.headRotation, drawinfo.headVect, drawinfo.scale, drawinfo.playerEffect, 0f);
        }
References Terraria.GameContent.TextureAssets.ArmorHead, Terraria.ID.ArmorIDs.Head.Count, Terraria.ID.ArmorIDs.Head.Sets.FrontToBackID, Terraria.DataStructures.PlayerDrawHeadLayers.QuickCDD(), Terraria.Main.screenPosition, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayerHead(), and Terraria.GameContent.PlayerHeadDrawRenderTargetContent.DrawTheContent().