Terraria Decompiled: Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_08_FaceAcc
DrawPlayer_08_FaceAcc()
static void Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_08_FaceAcc (ref PlayerDrawHeadSet drawinfo) inline static
Definition at line 441 of file PlayerDrawHeadLayers.cs.
        {
            bool flag = drawinfo.drawPlayer.head < 0 || !ArmorIDs.Head.Sets.PreventBeardDraw[drawinfo.drawPlayer.head];
            if (drawinfo.drawPlayer.beard > 0 && flag)
            {
                Vector2 beardDrawOffset = drawinfo.drawPlayer.GetBeardDrawOffset(true);
                Color color = drawinfo.colorArmorHead;
                if (ArmorIDs.Beard.Sets.UseHairColor[(int)drawinfo.drawPlayer.beard])
                {
                    color = drawinfo.colorHair;
                }
                PlayerDrawHeadLayers.QuickCDD(drawinfo.DrawData, drawinfo.cBeard, TextureAssets.AccBeard[(int)drawinfo.drawPlayer.beard].Value, beardDrawOffset + new Vector2(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.bodyFrameMemory.Width / 2) + (float)(drawinfo.drawPlayer.width / 2), drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.bodyFrameMemory.Height + 4f) + drawinfo.drawPlayer.headPosition + drawinfo.headVect, new Rectangle?(drawinfo.bodyFrameMemory), color, drawinfo.drawPlayer.headRotation, drawinfo.headVect, drawinfo.scale, drawinfo.playerEffect, 0f);
            }
            bool flag2 = drawinfo.drawPlayer.head == 287;
            if (drawinfo.drawPlayer.face > 0 && drawinfo.drawPlayer.face < ArmorIDs.Face.Count && !ArmorIDs.Face.Sets.DrawInFaceUnderHairLayer[(int)drawinfo.drawPlayer.face] && (drawinfo.drawPlayer.face != 23 || !flag2))
            {
                Vector2 vector = drawinfo.drawPlayer.GetFaceDrawOffset((int)drawinfo.drawPlayer.face) * drawinfo.drawPlayer.Directions;
                PlayerDrawHeadLayers.QuickCDD(drawinfo.DrawData, drawinfo.cFace, TextureAssets.AccFace[(int)drawinfo.drawPlayer.face].Value, vector + new Vector2((float)((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.bodyFrameMemory.Width / 2) + (float)(drawinfo.drawPlayer.width / 2))), drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.bodyFrameMemory.Height + 4f) + drawinfo.drawPlayer.headPosition + drawinfo.headVect, new Rectangle?(drawinfo.bodyFrameMemory), drawinfo.colorArmorHead, drawinfo.drawPlayer.headRotation, drawinfo.headVect, drawinfo.scale, drawinfo.playerEffect, 0f);
            }
            bool flag3 = drawinfo.drawPlayer.faceMask > 0 && drawinfo.drawPlayer.faceMask < ArmorIDs.Face.Count;
            if (flag3 && drawinfo.drawPlayer.head > 0 && drawinfo.drawPlayer.head < ArmorIDs.Head.Count && (ArmorIDs.Head.Sets.PreventFaceMaskDraw[drawinfo.drawPlayer.head] || ArmorIDs.Head.Sets.DrawFaceMaskUnderHeadLayer[drawinfo.drawPlayer.head]))
            {
                flag3 = false;
            }
            if (flag3)
            {
                Vector2 vector2 = drawinfo.drawPlayer.GetFaceDrawOffset((int)drawinfo.drawPlayer.faceMask) * drawinfo.drawPlayer.Directions;
                PlayerDrawHeadLayers.QuickCDD(drawinfo.DrawData, drawinfo.cFaceMask, TextureAssets.AccFace[(int)drawinfo.drawPlayer.faceMask].Value, vector2 + new Vector2((float)((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.bodyFrameMemory.Width / 2) + (float)(drawinfo.drawPlayer.width / 2))), drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.bodyFrameMemory.Height + 4f) + drawinfo.drawPlayer.headPosition + drawinfo.headVect, new Rectangle?(drawinfo.bodyFrameMemory), drawinfo.colorArmorHead, drawinfo.drawPlayer.headRotation, drawinfo.headVect, drawinfo.scale, drawinfo.playerEffect, 0f);
            }
            bool flag4 = drawinfo.drawPlayer.faceFlower > 0 && drawinfo.drawPlayer.faceFlower < ArmorIDs.Face.Count;
            if (flag4 && drawinfo.drawPlayer.head > 0 && drawinfo.drawPlayer.head < ArmorIDs.Head.Count && ArmorIDs.Head.Sets.PreventFaceFlowerDraw[drawinfo.drawPlayer.head])
            {
                flag4 = false;
            }
            if (flag4)
            {
                Vector2 vector3 = drawinfo.drawPlayer.GetFaceDrawOffset((int)drawinfo.drawPlayer.faceFlower) * drawinfo.drawPlayer.Directions;
                PlayerDrawHeadLayers.QuickCDD(drawinfo.DrawData, drawinfo.cFaceFlower, TextureAssets.AccFace[(int)drawinfo.drawPlayer.faceFlower].Value, vector3 + new Vector2((float)((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.bodyFrameMemory.Width / 2) + (float)(drawinfo.drawPlayer.width / 2))), drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.bodyFrameMemory.Height + 4f) + drawinfo.drawPlayer.headPosition + drawinfo.headVect, new Rectangle?(drawinfo.bodyFrameMemory), drawinfo.colorArmorHead, drawinfo.drawPlayer.headRotation, drawinfo.headVect, drawinfo.scale, drawinfo.playerEffect, 0f);
            }
            if (drawinfo.drawUnicornHorn)
            {
                PlayerDrawHeadLayers.QuickCDD(drawinfo.DrawData, drawinfo.cUnicornHorn, TextureAssets.Extra[143].Value, new Vector2(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.bodyFrameMemory.Width / 2) + (float)(drawinfo.drawPlayer.width / 2), drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.bodyFrameMemory.Height + 4f) + drawinfo.drawPlayer.headPosition + drawinfo.headVect, new Rectangle?(drawinfo.bodyFrameMemory), drawinfo.colorArmorHead, drawinfo.drawPlayer.headRotation, drawinfo.headVect, drawinfo.scale, drawinfo.playerEffect, 0f);
            }
            if (drawinfo.drawAngelHalo)
            {
                Main.instance.LoadAccFace(7);
                PlayerDrawHeadLayers.QuickCDD(drawinfo.DrawData, drawinfo.cAngelHalo, TextureAssets.AccFace[7].Value, new Vector2((float)((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.bodyFrameMemory.Width / 2) + (float)(drawinfo.drawPlayer.width / 2))), drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.bodyFrameMemory.Height + 4f) + drawinfo.drawPlayer.headPosition + drawinfo.headVect, new Rectangle?(drawinfo.bodyFrameMemory), new Color(200, 200, 200, 200), drawinfo.drawPlayer.headRotation, drawinfo.headVect, drawinfo.scale, drawinfo.playerEffect, 0f);
            }
        }
References Terraria.GameContent.TextureAssets.AccBeard, Terraria.GameContent.TextureAssets.AccFace, Terraria.ID.ArmorIDs.Head.Count, Terraria.ID.ArmorIDs.Face.Count, Terraria.ID.ArmorIDs.Head.Sets.DrawFaceMaskUnderHeadLayer, Terraria.ID.ArmorIDs.Face.Sets.DrawInFaceUnderHairLayer, Terraria.GameContent.TextureAssets.Extra, Terraria.Main.instance, Terraria.Main.LoadAccFace(), Terraria.ID.ArmorIDs.Head.Sets.PreventBeardDraw, Terraria.ID.ArmorIDs.Head.Sets.PreventFaceFlowerDraw, Terraria.ID.ArmorIDs.Head.Sets.PreventFaceMaskDraw, Terraria.DataStructures.PlayerDrawHeadLayers.QuickCDD(), Terraria.Main.screenPosition, Terraria.ID.ArmorIDs.Beard.Sets.UseHairColor, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayerHead(), and Terraria.GameContent.PlayerHeadDrawRenderTargetContent.DrawTheContent().