Terraria Decompiled: Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_04_RabbitOrder
DrawPlayer_04_RabbitOrder()
static void Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_04_RabbitOrder (ref PlayerDrawHeadSet drawinfo) inline static
Definition at line 148 of file PlayerDrawHeadLayers.cs.
        {
            int num = 27;
            Texture2D value = TextureAssets.ArmorHead[drawinfo.drawPlayer.head].Value;
            Rectangle rectangle = value.Frame(1, num, 0, drawinfo.drawPlayer.rabbitOrderFrame.DisplayFrame, 0, 0);
            Vector2 vector = rectangle.Size() / 2f;
            int num2 = 1;
            Vector2 vector2 = PlayerDrawHeadLayers.DrawPlayer_04_GetHatDrawPosition(ref drawinfo, new Vector2(1f, -26f), num2);
            int hatStacks = PlayerDrawHeadLayers.GetHatStacks(ref drawinfo, 4955);
            float num3 = 0.05235988f;
            float num4 = num3 * drawinfo.drawPlayer.position.X % 6.2831855f;
            for (int i = hatStacks - 1; i >= 0; i--)
            {
                float num5 = Vector2.UnitY.RotatedBy((double)(num4 + num3 * (float)i), default(Vector2)).X * ((float)i / 30f) * 2f - (float)(i * 2 * drawinfo.drawPlayer.direction);
                PlayerDrawHeadLayers.QuickCDD(drawinfo.DrawData, drawinfo.cHead, value, vector2 + new Vector2(num5, (float)(i * -14) * drawinfo.scale), new Rectangle?(rectangle), drawinfo.colorArmorHead, drawinfo.drawPlayer.headRotation, vector, drawinfo.scale, drawinfo.playerEffect, 0f);
            }
            if (!drawinfo.hideHair)
            {
                Rectangle hairFrame = drawinfo.HairFrame;
                hairFrame.Y -= 336;
                if (hairFrame.Y < 0)
                {
                    hairFrame.Y = 0;
                }
                PlayerDrawHeadLayers.QuickCDD(drawinfo.DrawData, drawinfo.hairShaderPacked, TextureAssets.PlayerHair[drawinfo.drawPlayer.hair].Value, new Vector2(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.bodyFrameMemory.Width / 2) + (float)(drawinfo.drawPlayer.width / 2), drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.bodyFrameMemory.Height + 4f) + drawinfo.drawPlayer.headPosition + drawinfo.headVect + drawinfo.hairOffset, new Rectangle?(hairFrame), drawinfo.colorHair, drawinfo.drawPlayer.headRotation, drawinfo.headVect, drawinfo.scale, drawinfo.playerEffect, 0f);
            }
        }
References Terraria.GameContent.TextureAssets.ArmorHead, Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_04_GetHatDrawPosition(), Terraria.DataStructures.PlayerDrawHeadLayers.GetHatStacks(), Terraria.GameContent.TextureAssets.PlayerHair, Terraria.DataStructures.PlayerDrawHeadLayers.QuickCDD(), Terraria.Main.screenPosition, Microsoft.Xna.Framework.Vector2.UnitY, System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Rectangle.Y, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_04_HatsWithFullHair().