Terraria Decompiled: Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_05_TallHats
DrawPlayer_05_TallHats()
static void Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_05_TallHats (ref PlayerDrawHeadSet drawinfo) inline static
Definition at line 297 of file PlayerDrawHeadLayers.cs.
        {
            if (drawinfo.helmetIsTall)
            {
                Rectangle hairFrame = drawinfo.HairFrame;
                if (drawinfo.drawPlayer.head == 158)
                {
                    hairFrame.Height -= 2;
                }
                int num = 0;
                if (hairFrame.Y == hairFrame.Height * 6)
                {
                    hairFrame.Height -= 2;
                }
                else if (hairFrame.Y == hairFrame.Height * 7)
                {
                    num = -2;
                }
                else if (hairFrame.Y == hairFrame.Height * 8)
                {
                    num = -2;
                }
                else if (hairFrame.Y == hairFrame.Height * 9)
                {
                    num = -2;
                }
                else if (hairFrame.Y == hairFrame.Height * 10)
                {
                    num = -2;
                }
                else if (hairFrame.Y == hairFrame.Height * 13)
                {
                    hairFrame.Height -= 2;
                }
                else if (hairFrame.Y == hairFrame.Height * 14)
                {
                    num = -2;
                }
                else if (hairFrame.Y == hairFrame.Height * 15)
                {
                    num = -2;
                }
                else if (hairFrame.Y == hairFrame.Height * 16)
                {
                    num = -2;
                }
                hairFrame.Y += num;
                Color color = drawinfo.colorArmorHead;
                int num2 = drawinfo.cHead;
                if (ArmorIDs.Head.Sets.UseSkinColor[drawinfo.drawPlayer.head])
                {
                    if (drawinfo.drawPlayer.isDisplayDollOrInanimate)
                    {
                        color = drawinfo.colorDisplayDollSkin;
                    }
                    else
                    {
                        color = drawinfo.colorHead;
                    }
                    num2 = drawinfo.skinDyePacked;
                }
                PlayerDrawHeadLayers.QuickCDD(drawinfo.DrawData, num2, TextureAssets.ArmorHead[drawinfo.drawPlayer.head].Value, drawinfo.helmetOffset + new Vector2(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.bodyFrameMemory.Width / 2) + (float)(drawinfo.drawPlayer.width / 2), drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.bodyFrameMemory.Height + 4f + (float)num) + drawinfo.drawPlayer.headPosition + drawinfo.headVect, new Rectangle?(hairFrame), color, drawinfo.drawPlayer.headRotation, drawinfo.headVect, drawinfo.scale, drawinfo.playerEffect, 0f);
            }
        }
References Terraria.GameContent.TextureAssets.ArmorHead, Microsoft.Xna.Framework.Rectangle.Height, Terraria.DataStructures.PlayerDrawHeadLayers.QuickCDD(), Terraria.Main.screenPosition, Terraria.ID.ArmorIDs.Head.Sets.UseSkinColor, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Rectangle.Y, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayerHead(), and Terraria.GameContent.PlayerHeadDrawRenderTargetContent.DrawTheContent().