Terraria Decompiled: Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_04_BadgersHat
DrawPlayer_04_BadgersHat()
static void Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_04_BadgersHat (ref PlayerDrawHeadSet drawinfo) inline static
Definition at line 189 of file PlayerDrawHeadLayers.cs.
        {
            int num = 6;
            Texture2D value = TextureAssets.ArmorHead[drawinfo.drawPlayer.head].Value;
            Rectangle rectangle = value.Frame(1, num, 0, drawinfo.drawPlayer.rabbitOrderFrame.DisplayFrame, 0, 0);
            Vector2 vector = rectangle.Size() / 2f;
            int num2 = 1;
            Vector2 vector2 = PlayerDrawHeadLayers.DrawPlayer_04_GetHatDrawPosition(ref drawinfo, new Vector2(0f, -9f), num2);
            int hatStacks = PlayerDrawHeadLayers.GetHatStacks(ref drawinfo, 5004);
            float num3 = 0.05235988f;
            float num4 = num3 * drawinfo.drawPlayer.position.X % 6.2831855f;
            int num5 = hatStacks * 4 + 2;
            int num6 = 0;
            bool flag = (Main.GlobalTimeWrappedHourly + 180f) % 600f < 60f;
            for (int i = num5 - 1; i >= 0; i--)
            {
                int num7 = 0;
                if (i == num5 - 1)
                {
                    rectangle.Y = 0;
                    num7 = 2;
                }
                else if (i == 0)
                {
                    rectangle.Y = rectangle.Height * 5;
                }
                else
                {
                    rectangle.Y = rectangle.Height * (num6++ % 4 + 1);
                }
                if (rectangle.Y != rectangle.Height * 3 || !flag)
                {
                    float num8 = Vector2.UnitY.RotatedBy((double)(num4 + num3 * (float)i), default(Vector2)).X * ((float)i / 10f) * 4f - (float)i * 0.1f * (float)drawinfo.drawPlayer.direction;
                    PlayerDrawHeadLayers.QuickCDD(drawinfo.DrawData, drawinfo.cHead, value, vector2 + new Vector2(num8, (float)((i * -4 + num7) * num2)) * drawinfo.scale, new Rectangle?(rectangle), drawinfo.colorArmorHead, drawinfo.drawPlayer.headRotation, vector, drawinfo.scale, drawinfo.playerEffect, 0f);
                }
            }
        }
References Terraria.GameContent.TextureAssets.ArmorHead, Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_04_GetHatDrawPosition(), Terraria.DataStructures.PlayerDrawHeadLayers.GetHatStacks(), Microsoft.Xna.Framework.Rectangle.Height, Terraria.DataStructures.PlayerDrawHeadLayers.QuickCDD(), Microsoft.Xna.Framework.Vector2.UnitY, System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, System.X, and Microsoft.Xna.Framework.Rectangle.Y.
Referenced by Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_06_NormalHats().