Terraria Decompiled: Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_04_HatsWithFullHair
DrawPlayer_04_HatsWithFullHair()
static void Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_04_HatsWithFullHair (ref PlayerDrawHeadSet drawinfo) inline static
Definition at line 256 of file PlayerDrawHeadLayers.cs.
        {
            if (drawinfo.drawPlayer.head == 259)
            {
                PlayerDrawHeadLayers.DrawPlayer_04_RabbitOrder(ref drawinfo);
                return;
            }
            if (drawinfo.helmetIsOverFullHair)
            {
                if (!drawinfo.hideHair)
                {
                    Rectangle hairFrame = drawinfo.HairFrame;
                    hairFrame.Y -= 336;
                    if (hairFrame.Y < 0)
                    {
                        hairFrame.Y = 0;
                    }
                    PlayerDrawHeadLayers.QuickCDD(drawinfo.DrawData, drawinfo.hairShaderPacked, TextureAssets.PlayerHair[drawinfo.drawPlayer.hair].Value, new Vector2(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.bodyFrameMemory.Width / 2) + (float)(drawinfo.drawPlayer.width / 2), drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.bodyFrameMemory.Height + 4f) + drawinfo.drawPlayer.headPosition + drawinfo.headVect + drawinfo.hairOffset, new Rectangle?(hairFrame), drawinfo.colorHair, drawinfo.drawPlayer.headRotation, drawinfo.headVect, drawinfo.scale, drawinfo.playerEffect, 0f);
                }
                if (drawinfo.drawPlayer.head != 0)
                {
                    Color color = drawinfo.colorArmorHead;
                    int num = drawinfo.cHead;
                    if (ArmorIDs.Head.Sets.UseSkinColor[drawinfo.drawPlayer.head])
                    {
                        if (drawinfo.drawPlayer.isDisplayDollOrInanimate)
{
                            color = drawinfo.colorDisplayDollSkin;
                        }
                        else
{
                            color = drawinfo.colorHead;
                        }
                        num = drawinfo.skinDyePacked;
                    }
                    PlayerDrawHeadLayers.QuickCDD(drawinfo.DrawData, num, TextureAssets.ArmorHead[drawinfo.drawPlayer.head].Value, drawinfo.helmetOffset + new Vector2(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.bodyFrameMemory.Width / 2) + (float)(drawinfo.drawPlayer.width / 2), drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.bodyFrameMemory.Height + 4f) + drawinfo.drawPlayer.headPosition + drawinfo.headVect, new Rectangle?(drawinfo.bodyFrameMemory), color, drawinfo.drawPlayer.headRotation, drawinfo.headVect, drawinfo.scale, drawinfo.playerEffect, 0f);
                }
            }
        }
References Terraria.GameContent.TextureAssets.ArmorHead, Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_04_RabbitOrder(), Terraria.GameContent.TextureAssets.PlayerHair, Terraria.DataStructures.PlayerDrawHeadLayers.QuickCDD(), Terraria.Main.screenPosition, Terraria.ID.ArmorIDs.Head.Sets.UseSkinColor, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Rectangle.Y, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayerHead(), and Terraria.GameContent.PlayerHeadDrawRenderTargetContent.DrawTheContent().