Terraria Decompiled: Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_02_DrawArmorWithFullHair
DrawPlayer_02_DrawArmorWithFullHair()
static void Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_02_DrawArmorWithFullHair (ref PlayerDrawHeadSet drawinfo) inline static
Definition at line 75 of file PlayerDrawHeadLayers.cs.
        {
            bool flag = drawinfo.drawPlayer.faceMask > 0 && drawinfo.drawPlayer.faceMask < ArmorIDs.Face.Count;
            if (flag && drawinfo.drawPlayer.head > 0 && drawinfo.drawPlayer.head < ArmorIDs.Head.Count && !ArmorIDs.Head.Sets.DrawFaceMaskUnderHeadLayer[drawinfo.drawPlayer.head])
            {
                flag = false;
            }
            if (flag)
            {
                Vector2 vector = drawinfo.drawPlayer.GetFaceDrawOffset((int)drawinfo.drawPlayer.faceMask) * drawinfo.drawPlayer.Directions;
                PlayerDrawHeadLayers.QuickCDD(drawinfo.DrawData, drawinfo.cFaceMask, TextureAssets.AccFace[(int)drawinfo.drawPlayer.faceMask].Value, vector + new Vector2((float)((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.bodyFrameMemory.Width / 2) + (float)(drawinfo.drawPlayer.width / 2))), drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.bodyFrameMemory.Height + 4f) + drawinfo.drawPlayer.headPosition + drawinfo.headVect, new Rectangle?(drawinfo.bodyFrameMemory), drawinfo.colorArmorHead, drawinfo.drawPlayer.headRotation, drawinfo.headVect, drawinfo.scale, drawinfo.playerEffect, 0f);
            }
            if (drawinfo.fullHair)
            {
                Color color = drawinfo.colorArmorHead;
                int num = drawinfo.cHead;
                if (ArmorIDs.Head.Sets.UseSkinColor[drawinfo.drawPlayer.head])
                {
                    if (drawinfo.drawPlayer.isDisplayDollOrInanimate)
                    {
                        color = drawinfo.colorDisplayDollSkin;
                    }
                    else
                    {
                        color = drawinfo.colorHead;
                    }
                    num = drawinfo.skinDyePacked;
                }
                PlayerDrawHeadLayers.QuickCDD(drawinfo.DrawData, num, TextureAssets.ArmorHead[drawinfo.drawPlayer.head].Value, drawinfo.helmetOffset + new Vector2(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.bodyFrameMemory.Width / 2) + (float)(drawinfo.drawPlayer.width / 2), drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.bodyFrameMemory.Height + 4f) + drawinfo.drawPlayer.headPosition + drawinfo.headVect, new Rectangle?(drawinfo.HairFrame), color, drawinfo.drawPlayer.headRotation, drawinfo.headVect, drawinfo.scale, drawinfo.playerEffect, 0f);
                if (!drawinfo.hideHair)
                {
                    Rectangle hairFrame = drawinfo.HairFrame;
                    hairFrame.Y -= 336;
                    if (hairFrame.Y < 0)
                    {
                        hairFrame.Y = 0;
                    }
                    PlayerDrawHeadLayers.QuickCDD(drawinfo.DrawData, drawinfo.hairShaderPacked, TextureAssets.PlayerHair[drawinfo.drawPlayer.hair].Value, new Vector2(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.bodyFrameMemory.Width / 2) + (float)(drawinfo.drawPlayer.width / 2), drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.bodyFrameMemory.Height + 4f) + drawinfo.drawPlayer.headPosition + drawinfo.headVect + drawinfo.hairOffset, new Rectangle?(hairFrame), drawinfo.colorHair, drawinfo.drawPlayer.headRotation, drawinfo.headVect, drawinfo.scale, drawinfo.playerEffect, 0f);
                }
            }
        }
References Terraria.GameContent.TextureAssets.AccFace, Terraria.GameContent.TextureAssets.ArmorHead, Terraria.ID.ArmorIDs.Head.Count, Terraria.ID.ArmorIDs.Face.Count, Terraria.ID.ArmorIDs.Head.Sets.DrawFaceMaskUnderHeadLayer, Terraria.GameContent.TextureAssets.PlayerHair, Terraria.DataStructures.PlayerDrawHeadLayers.QuickCDD(), Terraria.Main.screenPosition, Terraria.ID.ArmorIDs.Head.Sets.UseSkinColor, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Rectangle.Y, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayerHead(), and Terraria.GameContent.PlayerHeadDrawRenderTargetContent.DrawTheContent().