Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldGenDebug.TestResetFromPassesAndRegen
TestResetFromPassesAndRegen()
static IEnumerable< object > Terraria.GameContent.UI.States.UIWorldGenDebug.TestResetFromPassesAndRegen () inline static
Definition at line 915 of file UIWorldGenDebug.cs.
        {
            using (IEnumerator<bool> enumerator = UIWorldGenDebug.TestSetupResetAndCreateSnapshots().GetEnumerator())
            {
                while (enumerator.MoveNext())
                {
                    if (!enumerator.Current)
                    {
                        yield break;
                    }
                    yield return null;
                }
            }
            IEnumerator<bool> enumerator = null;
            GenPass lastPass = UIWorldGenDebug.Controller.Passes.Last<GenPass>();
            List<GenPass> passes = UIWorldGenDebug.Controller.Passes.Where((GenPass p) => p.Enabled).ToList<GenPass>();
            int num;
            for (int i = 0; i < passes.Count; i = num + 1)
            {
                GenPass pass = passes[i];
                UIWorldGenDebug.Controller.TryReset();
                Main.NewText(string.Format("[{0}/{1}] Running to {2}", i + 1, passes.Count, pass.Name), byte.MaxValue, 100, 0);
                UIWorldGenDebug.Controller.TryRunToEndOfPass(pass, false, true);
                yield return null;
                if (UIWorldGenDebug.Controller.LastCompletedPass != pass || UIWorldGenDebug.Controller.PausedDueToHashMismatch)
                {
                    Main.NewText("Test aborted", byte.MaxValue, 0, 0);
                    yield break;
                }
                UIWorldGenDebug.Controller.TryReset();
                UIWorldGenDebug.Controller.TryRunToEndOfPass(lastPass, false, true);
                yield return null;
                if (UIWorldGenDebug.Controller.LastCompletedPass != lastPass || UIWorldGenDebug.Controller.PausedDueToHashMismatch)
                {
                    Main.NewText("Test aborted", byte.MaxValue, 0, 0);
                    yield break;
                }
                pass = null;
                num = i;
            }
            Main.NewText("Test Completed Successfully", 0, byte.MaxValue, 0);
            yield break;
            yield break;
        }
References Terraria.GameContent.UI.States.UIWorldGenDebug.Controller, System.Collections.Generic.IEnumerator< out T >.Current, Terraria.WorldBuilding.GenPass.Enabled, System.Format, System.Collections.IEnumerator.MoveNext(), Terraria.WorldBuilding.GenPass.Name, Terraria.Main.NewText(), and Terraria.GameContent.UI.States.UIWorldGenDebug.TestSetupResetAndCreateSnapshots().