Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldGenDebug.DrawSelf
DrawSelf()
override void Terraria.GameContent.UI.States.UIWorldGenDebug.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 750 of file UIWorldGenDebug.cs.
        {
            Main.starGame = false;
            Main.onlyDrawFancyUI = this.showMap;
            if (this.showMap)
            {
                Main.alreadyGrabbingSunOrMoon = false;
                this.UpdateAndDrawMap();
                Main.instance.DrawFPS();
            }
            if (!this.hideChat || Main.drawingPlayerChat)
            {
                spriteBatch.End();
                spriteBatch.Begin(SpriteSortMode.Deferred, null, null, null, null, null, Matrix.CreateTranslation(250f, 0f, 0f) * Main.UIScaleMatrix);
                Main.instance.DrawPlayerChat();
                spriteBatch.End();
                spriteBatch.Begin(SpriteSortMode.Deferred, null, null, null, null, null, Main.UIScaleMatrix);
            }
        }
References Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(), Microsoft.Xna.Framework.Matrix.CreateTranslation(), Terraria.Main.DrawFPS(), Terraria.Main.drawingPlayerChat, Terraria.Main.DrawPlayerChat(), Microsoft.Xna.Framework.Graphics.SpriteBatch.End(), Terraria.GameContent.UI.States.UIWorldGenDebug.hideChat, Terraria.Main.instance, Terraria.GameContent.UI.States.UIWorldGenDebug.showMap, Terraria.Main.UIScaleMatrix, and Terraria.GameContent.UI.States.UIWorldGenDebug.UpdateAndDrawMap().