Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldGenDebug.ToggleMap
ToggleMap()
void Terraria.GameContent.UI.States.UIWorldGenDebug.ToggleMap () inline private
Definition at line 789 of file UIWorldGenDebug.cs.
        {
            this.showMap = !this.showMap;
            Main.onlyDrawFancyUI = this.showMap;
            if (this.showMap)
            {
                this.nextMapSection = Point.Zero;
                this.fullMapScanTimer = Stopwatch.StartNew();
            }
        }
References Terraria.GameContent.UI.States.UIWorldGenDebug.showMap, and Microsoft.Xna.Framework.Point.Zero.
Referenced by Terraria.GameContent.UI.States.UIWorldGenDebug.b__38_15(), Terraria.GameContent.UI.States.UIWorldGenDebug.OnActivate(), Terraria.GameContent.UI.States.UIWorldGenDebug.UIWorldGenDebug(), and Terraria.GameContent.UI.States.UIWorldGenDebug.Update().