Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldGenDebug.AddImage
AddImage()
UIImage Terraria.GameContent.UI.States.UIWorldGenDebug.AddImage (UIPanel controlPanel, string assetPath, Action onClick, Func< string > getTitle, Func< string > getDescription = null) inline private
Definition at line 427 of file UIWorldGenDebug.cs.
        {
            UIImage uiimage = new UIImage(Main.Assets.Request<Texture2D>(assetPath, 1))
            {
                Width = new StyleDimension(34f, 0f),
                Height = new StyleDimension(34f, 0f),
                Left = StyleDimension.FromPixelsAndPercent((float)(36 * controlPanel.Children.Count<UIElement>()), 0f)
            };
            uiimage.OnLeftClick += delegate(UIMouseEvent evt, UIElement e)
            {
                onClick();
            };
            uiimage.Append(new UIWorldGenDebug.TooltipElement(getTitle, getDescription));
            controlPanel.Append(uiimage);
            controlPanel.Width = StyleDimension.FromPixelsAndPercent((float)(36 * controlPanel.Children.Count<UIElement>() - 2) + controlPanel.PaddingLeft + controlPanel.PaddingRight, 0f);
            return uiimage;
        }
References Terraria.UI.UIElement.Append(), Terraria.Main.Assets, Terraria.UI.UIElement.Children, Terraria.GameContent.UI.States.UIWorldGenDebug.controlPanel, Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.UI.UIElement.Height, Terraria.UI.UIElement.Left, Terraria.UI.UIElement.PaddingLeft, Terraria.UI.UIElement.PaddingRight, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.UIWorldGenDebug.UIWorldGenDebug().