Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldGenDebug.Update
Update()
override void Terraria.GameContent.UI.States.UIWorldGenDebug.Update (GameTime gameTime) inline virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 523 of file UIWorldGenDebug.cs.
        {
            Main.starGame = false;
            Main.LocalPlayer.dead = true;
            if (UIWorldGenDebug.Controller.Paused && this.TestEnumerator != null)
            {
                for (;;)
                {
                    if (UIWorldGenDebug.Controller.TryOperateInControlLock(delegate
                    {
                    }))
                    {
                        break;
                    }
                    Thread.Yield();
                }
                if (!this.TestEnumerator.MoveNext())
                {
                    this.TestEnumerator = null;
                }
            }
            base.Update(gameTime);
            if (Main.drawingPlayerChat || this.searchBar.IsWritingText)
            {
                this.ignoreEscapeAttempt = 3;
                return;
            }
            int num = this.ignoreEscapeAttempt;
            this.ignoreEscapeAttempt = num - 1;
            if (num <= 0 && PlayerInput.Triggers.JustPressed.Inventory)
            {
                UIWorldGenDebug.Controller.QueuedAbort = true;
            }
            if (UIWorldGenDebug.KeyPressed(Keys.Space))
            {
                WorldGenerator.Controller controller = UIWorldGenDebug.Controller;
                controller.Paused = !controller.Paused;
            }
            if (UIWorldGenDebug.KeyPressed(Keys.R) && UIWorldGenDebug.CanSubmitActions && UIWorldGenDebug.Controller.LastCompletedPass != null)
            {
                UIWorldGenDebug.Controller.TryRunToEndOfPass(UIWorldGenDebug.Controller.LastCompletedPass, !Main.keyState.PressingShift(), true);
            }
            if (UIWorldGenDebug.KeyPressed(Keys.Up) || UIWorldGenDebug.KeyPressed(Keys.Left))
            {
                this.StepBack();
            }
            if (UIWorldGenDebug.KeyPressed(Keys.Down) || UIWorldGenDebug.KeyPressed(Keys.Right))
            {
                this.StepForward();
            }
            if (UIWorldGenDebug.KeyPressed(Keys.C))
            {
                this.hideChat = !this.hideChat;
            }
            if (UIWorldGenDebug.KeyPressed(Keys.H))
            {
                this.ToggleUI();
            }
            if (UIWorldGenDebug.KeyPressed(Keys.M))
            {
                this.ToggleMap();
            }
            PlayerInput.SetZoom_World();
            if (this.showMap)
            {
                if (PlayerInput.Triggers.Current.Up && !Main.oldKeyState.IsKeyDown(Keys.Up))
                {
                    Main.mapFullscreenPos.Y = Main.mapFullscreenPos.Y - 1f * (16f / Main.mapFullscreenScale);
                }
                if (PlayerInput.Triggers.Current.Down && !Main.oldKeyState.IsKeyDown(Keys.Down))
                {
                    Main.mapFullscreenPos.Y = Main.mapFullscreenPos.Y + 1f * (16f / Main.mapFullscreenScale);
                }
                if (PlayerInput.Triggers.Current.Left && !Main.oldKeyState.IsKeyDown(Keys.Left))
                {
                    Main.mapFullscreenPos.X = Main.mapFullscreenPos.X - 1f * (16f / Main.mapFullscreenScale);
                }
                if (PlayerInput.Triggers.Current.Right && !Main.oldKeyState.IsKeyDown(Keys.Right))
                {
                    Main.mapFullscreenPos.X = Main.mapFullscreenPos.X + 1f * (16f / Main.mapFullscreenScale);
                }
                if (!UserInterface.ActiveInstance.IsElementUnderMouse())
                {
                    Main.mapFullscreenScale *= 1f + (float)(PlayerInput.ScrollWheelDelta / 120) * 0.3f;
                }
                Main.screenPosition = Main.mapFullscreenPos * 16f - Main.Camera.UnscaledSize / 2f;
            }
            else if (!Main.gameMenu)
            {
                Main.DebugCameraPan(PlayerInput.Triggers.Current.Left, PlayerInput.Triggers.Current.Right, PlayerInput.Triggers.Current.Up, PlayerInput.Triggers.Current.Down);
            }
            if (!Main.gameMenu)
            {
                Main.ClampScreenPositionToWorld();
                Main.LocalPlayer.position += Main.screenPosition - Main.PlayerFocusedScreenPosition();
                Main.mapFullscreenPos = Main.Camera.Center / 16f;
            }
            PlayerInput.SetZoom_UI();
            UIWorldGenDebug.spaceWasPressed = Main.keyState.IsKeyDown(Keys.Space) || Main.oldKeyState.IsKeyDown(Keys.Space);
        }
References Terraria.UI.UserInterface.ActiveInstance, Terraria.GameContent.UI.States.UIWorldGenDebug.CanSubmitActions, Terraria.Main.ClampScreenPositionToWorld(), Terraria.GameContent.UI.States.UIWorldGenDebug.Controller, Terraria.GameInput.TriggersPack.Current, Terraria.Main.DebugCameraPan(), Terraria.GameInput.TriggersSet.Down, Terraria.Main.drawingPlayerChat, Terraria.Main.gameMenu, Terraria.GameContent.UI.States.UIWorldGenDebug.hideChat, Terraria.GameContent.UI.States.UIWorldGenDebug.ignoreEscapeAttempt, Terraria.GameInput.TriggersSet.Inventory, Terraria.UI.UserInterface.IsElementUnderMouse(), Microsoft.Xna.Framework.Input.KeyboardState.IsKeyDown(), Terraria.GameInput.TriggersPack.JustPressed, Terraria.GameContent.UI.States.UIWorldGenDebug.KeyPressed(), Terraria.Main.keyState, Terraria.GameInput.TriggersSet.Left, Terraria.Main.mapFullscreenScale, Terraria.Main.oldKeyState, Terraria.WorldBuilding.WorldGenerator.Controller.Paused, Terraria.Main.PlayerFocusedScreenPosition(), Terraria.GameInput.TriggersSet.Right, Terraria.GameInput.PlayerInput.ScrollWheelDelta, Terraria.GameInput.PlayerInput.SetZoom_UI(), Terraria.GameInput.PlayerInput.SetZoom_World(), Terraria.GameContent.UI.States.UIWorldGenDebug.showMap, Terraria.GameContent.UI.States.UIWorldGenDebug.StepBack(), Terraria.GameContent.UI.States.UIWorldGenDebug.StepForward(), Terraria.GameContent.UI.States.UIWorldGenDebug.TestEnumerator, Terraria.GameContent.UI.States.UIWorldGenDebug.ToggleMap(), Terraria.GameContent.UI.States.UIWorldGenDebug.ToggleUI(), Terraria.GameInput.PlayerInput.Triggers, Terraria.GameInput.TriggersSet.Up, and System.Threading.Thread.Yield().