Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldGenDebug.UIWorldGenDebug
UIWorldGenDebug() [1/2]
Terraria.GameContent.UI.States.UIWorldGenDebug.UIWorldGenDebug () inline
Definition at line 147 of file UIWorldGenDebug.cs.
        {
            this.NoGamepadSupport = true;
            this.IgnoresMouseInteraction = true;
            UIGenProgressBar progressBar = new UIGenProgressBar
            {
                VAlign = 0f,
                HAlign = 0.5f,
                Top = StyleDimension.FromPixels(20f),
                IgnoresMouseInteraction = true
            };
            base.Append(progressBar);
            UIHeader progressMessage = new UIHeader
            {
                VAlign = 0f,
                HAlign = 0.5f,
                IgnoresMouseInteraction = true
            };
            base.Append(progressMessage);
            base.OnUpdate += delegate(UIElement e)
            {
                progressBar.SetProgress((float)WorldGenerator.CurrentGenerationProgress.TotalProgress, (float)WorldGenerator.CurrentGenerationProgress.Value);
                progressMessage.Text = WorldGenerator.CurrentGenerationProgress.Message;
                if (WorldGenerator.CurrentController.QueuedAbort)
                {
                    progressMessage.Text = Language.GetTextValue("UI.Canceling");
                }
                if (WorldGen.Manifest.GenPassResults.Count != this.LassPassIndex)
                {
                    this.LassPassIndex = WorldGen.Manifest.GenPassResults.Count;
                    this.EnsurePassVisible(this.LassPassIndex);
                }
            };
            this.controlListArea = new UIElement
            {
                Width = StyleDimension.FromPixels(450f),
                Height = StyleDimension.FromPixelsAndPercent(-60f, 1f),
                Top = StyleDimension.FromPixels(30f),
                Left = StyleDimension.FromPixels(10f)
            };
            base.Append(this.controlListArea);
            this.controlPanel = new UIPanel
            {
                Height = StyleDimension.FromPixels(50f)
            };
            this.controlPanel.SetPadding(8f);
            this.controlPanel.BackgroundColor = new Color(73, 94, 171) * 0.9f;
            UIElement uielement = this.AddButton(this.controlPanel, "Images/UI/Camera_0", delegate
            {
                UIWorldGenDebug.Controller.DeleteAllSnapshots();
            }, () => "Delete all snapshots", () => string.Concat(new object[]
            {
                "Click to clear all snapshots\nEstimated Disk Usage: ",
                WorldGenSnapshot.EstimatedDiskUsage / 1024L / 1024L,
                "MB",
                UIWorldGenDebug.CanSubmitActions ? "" : "\n[c/FFA500:Must be paused to manipulate snapshots]"
            }));
            UIImage uiimage = new UIImage(Main.Assets.Request<Texture2D>("Images/CoolDown", 1))
            {
                ScaleToFit = true,
                Width = new StyleDimension(28f, 0f),
                Height = new StyleDimension(28f, 0f),
                Left = new StyleDimension(3f, 0f),
                Top = new StyleDimension(3f, 0f)
            };
            uielement.Append(uiimage);
            GroupOptionButton<bool> groupOptionButton = this.AddButton(this.controlPanel, "Images/UI/IconReset", delegate
            {
                UIWorldGenDebug.Controller.TryReset();
            }, () => "Reset", delegate
            {
                if (!UIWorldGenDebug.CanSubmitActions)
                {
                    return "[c/FFA500:Must be paused to reset]";
                }
                return null;
            });
            groupOptionButton.IconScale = 28f / (float)groupOptionButton.Icon.Width;
            groupOptionButton.IconOffset = new Vector2(2f, 3f);
            GroupOptionButton<bool> groupOptionButton2 = this.AddButton(this.controlPanel, "Images/UI/IconPrev", new Action(this.StepBack), () => "Step Back", () => "Hotkey: Up/Left");
            groupOptionButton2.IconScale = 28f / (float)groupOptionButton2.Icon.Width;
            groupOptionButton2.IconOffset = new Vector2(2f, 3f);
            GroupOptionButton<bool> playPauseButton = this.AddButton(this.controlPanel, "Images/UI/IconPlayPause", delegate
            {
                WorldGenerator.Controller controller = UIWorldGenDebug.Controller;
                controller.Paused = !controller.Paused;
            }, delegate
            {
                if (!WorldGenerator.CurrentController.Paused)
                {
                    return "Pause";
                }
                return "Play";
            }, () => "Hotkey: Space");
            playPauseButton.IconScale = 28f / (float)playPauseButton.Icon.Width;
            playPauseButton.IconOffset = new Vector2(3f, 3f);
            playPauseButton.OnUpdate += delegate(UIElement e)
            {
                playPauseButton.SetIconFrame(playPauseButton.Icon.Frame(1, 2, 0, UIWorldGenDebug.Controller.Paused ? 0 : 1, 0, 0));
            };
            GroupOptionButton<bool> groupOptionButton3 = this.AddButton(this.controlPanel, "Images/UI/IconNext", new Action(this.StepForward), () => "Step Forward", () => "Hotkey: Down/Right");
            groupOptionButton3.IconScale = 28f / (float)groupOptionButton3.Icon.Width;
            groupOptionButton3.IconOffset = new Vector2(2f, 3f);
            this.AddButton(this.controlPanel, "Images/Map_0", delegate
            {
                this.ToggleMap();
            }, () => "Toggle Map", () => "Left click to toggle the map display").IconOffset = new Vector2(4f, 5f);
            GroupOptionButton<bool> groupOptionButton4 = this.AddButton(this.controlPanel, "Images/Extra_" + 48, delegate
            {
                this.hideChat = !this.hideChat;
            }, () => "Toggle Chat", () => "Left click to toggle the chat log");
            Asset<Texture2D> asset = Main.Assets.Request<Texture2D>("Images/Extra_" + 48, 1);
            Rectangle rectangle = asset.Frame(8, EmoteBubble.EMOTE_SHEET_VERTICAL_FRAMES, 1, 0, 0, 0);
            groupOptionButton4.IconScale = 28f / (float)rectangle.Width;
            groupOptionButton4.IconOffset = new Vector2(3f, 5f);
            groupOptionButton4.SetIconFrame(rectangle);
            rectangle = asset.Frame(8, EmoteBubble.EMOTE_SHEET_VERTICAL_FRAMES, 4, 3, 0, 0);
            UIImage uiimage2 = new UIImage(asset)
            {
                Frame = new Rectangle?(rectangle),
                ScaleToFit = true,
                Width = new StyleDimension(28f, 0f),
                Height = new StyleDimension(28f, 0f),
                Left = new StyleDimension(2f, 0f),
                Top = new StyleDimension(6f, 0f)
            };
            groupOptionButton4.Append(uiimage2);
            GroupOptionButton<bool> snapshotFrequencyButton = this.AddButton(this.controlPanel, "Images/UI/IconSnapshotFrequency", new Action(this.CycleSnapshotMode), new Func<string>(this.GetSnapshotModeButtonTitle), null);
            snapshotFrequencyButton.OnUpdate += delegate(UIElement e)
            {
                snapshotFrequencyButton.SetIconFrame(snapshotFrequencyButton.Icon.Frame(1, 3, 0, (int)WorldGenerator.CurrentController.SnapshotFrequency, 0, 0));
            };
            GroupOptionButton<bool> mismatchPauseButton = this.AddButton(this.controlPanel, "Images/UI/IconMismatchPause", delegate
            {
                WorldGenerator.Controller controller2 = UIWorldGenDebug.Controller;
                controller2.PauseOnHashMismatch = !controller2.PauseOnHashMismatch;
            }, () => "Pause on gen pass change: " + (WorldGenerator.CurrentController.PauseOnHashMismatch ? "On" : "Off"), () => "Stop the generator when the output of a pass is different\nto the last time it was run in the save, or current session");
            mismatchPauseButton.SetColorsBasedOnSelectionState(new Color(152, 175, 235), Colors.InventoryDefaultColor, 1f, 0.7f);
            mismatchPauseButton.OnUpdate += delegate(UIElement e)
            {
                mismatchPauseButton.SetCurrentOption(WorldGenerator.CurrentController.PauseOnHashMismatch);
            };
            string quickLoadCommand = (Main.gameMenu ? "/quickload-regen" : "/quickload");
            this.AddButton(this.controlPanel, "Images/UI/IconQuickload", delegate
            {
                DebugUtils.QuickSPMessage(quickLoadCommand);
            }, () => "Save current settings to " + quickLoadCommand, () => "Future launches of the game will automatically load the world\nfrom the most recent snapshot, and run to the current pass");
            UIImage uiimage3 = this.AddImage(this.controlPanel, "Images/UI/Bestiary/Icon_Locked", delegate
            {
            }, () => "Controls", () => this.GetControls());
            uiimage3.ImageScale = 24f / (float)uiimage3.Texture.Value.Height;
            uiimage3.NormalizedOrigin.X = 0.75f;
            this.AddButton(this.controlPanel, "Images/UI/Camera_5", delegate
            {
                UIWorldGenDebug.Controller.QueuedAbort = true;
            }, () => "Cancel", null).IconOffset = new Vector2(4f, 4f);
            this.controlListArea.Append(this.controlPanel);
            float num = this.controlPanel.Height.Pixels + 2f;
            this.scrollPanel = new UIPanel
            {
                Width = StyleDimension.FromPixelsAndPercent(300f, 0f),
                Height = StyleDimension.FromPixelsAndPercent(-num, 1f),
                Top = StyleDimension.FromPixels(num),
                Left = this.controlPanel.Left,
                HAlign = 0f,
                VAlign = 0f
            };
            this.scrollPanel.PaddingTop = 8f;
            this.scrollPanel.PaddingBottom = 8f;
            this.scrollPanel.PaddingLeft = 4f;
            this.scrollPanel.PaddingRight = 4f;
            this.controlListArea.Append(this.scrollPanel);
            this.searchBar = new UIWrappedSearchBar(delegate
            {
                UserInterface.ActiveInstance.SetState(this);
            }, null, UIWrappedSearchBar.ColorTheme.Blue)
            {
                Left = StyleDimension.FromPixels(-2f),
                Top = StyleDimension.FromPixels(-2f),
                Height = StyleDimension.FromPixels(28f),
                Width = StyleDimension.FromPixelsAndPercent(0f, 1f),
                HAlign = 0f
            };
            this.searchBar.OnSearchContentsChanged += delegate(string s)
            {
                this.searchText = s;
            };
            this.searchBar.HideSearchButton();
            this.scrollPanel.Append(this.searchBar);
            num = 30f;
            UIList uilist = new UIList();
            uilist.Top = StyleDimension.FromPixels(num);
            uilist.Width = StyleDimension.FromPixelsAndPercent(-20f, 1f);
            uilist.Height = StyleDimension.FromPixelsAndPercent(-num, 1f);
            uilist.ListPadding = 0f;
            uilist.ManualSortMethod = delegate(List<UIElement> _)
            {
            };
            this.GenPassList = uilist;
            this.scrollPanel.Append(this.GenPassList);
            foreach (GenPass genPass in UIWorldGenDebug.Controller.Passes)
            {
                UIWorldGenDebug.GenPassElement genPassElement = new UIWorldGenDebug.GenPassElement(this, genPass)
                {
                    Width = new StyleDimension(-4f, 1f),
                    Height = StyleDimension.FromPixels(32f),
                    PaddingLeft = 7f
                };
                this.allPasses.Add(genPassElement);
                this.GenPassList.Add(genPassElement);
            }
            this.scrollbar = new UIScrollbar(UIScrollbar.ColorTheme.Blue)
            {
                Top = StyleDimension.FromPixels(34f),
                Height = StyleDimension.FromPixelsAndPercent(-38f, 1f),
                Left = StyleDimension.FromPixels(-1f),
                HAlign = 1f
            };
            this.scrollbar.SetView(100f, 1000f);
            this.GenPassList.SetScrollbar(this.scrollbar);
            this.scrollPanel.Append(this.scrollbar);
            this.RefreshControlsPosition();
        }
References System.Action(), Terraria.UI.UserInterface.ActiveInstance, Terraria.GameContent.UI.Elements.UIList.Add(), Terraria.GameContent.UI.States.UIWorldGenDebug.AddButton(), Terraria.GameContent.UI.States.UIWorldGenDebug.AddImage(), Terraria.GameContent.UI.States.UIWorldGenDebug.allPasses, Terraria.UI.UIElement.Append(), Terraria.Main.Assets, Terraria.GameContent.UI.States.UIWorldGenDebug.CanSubmitActions, Microsoft.Xna.Framework.Graphics.Color, Terraria.GameContent.UI.States.UIWorldGenDebug.Controller, Terraria.GameContent.UI.States.UIWorldGenDebug.controlListArea, Terraria.GameContent.UI.States.UIWorldGenDebug.controlPanel, Terraria.WorldBuilding.WorldGenerator.CurrentController, Terraria.WorldBuilding.WorldGenerator.CurrentGenerationProgress, Terraria.GameContent.UI.States.UIWorldGenDebug.CycleSnapshotMode(), Terraria.GameContent.UI.EmoteBubble.EMOTE_SHEET_VERTICAL_FRAMES, Terraria.GameContent.UI.States.UIWorldGenDebug.EnsurePassVisible(), Terraria.UI.StyleDimension.FromPixels(), Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.GameContent.UI.States.UIWorldGenDebug.GenPassList, Terraria.WorldBuilding.WorldManifest.GenPassResults, Terraria.GameContent.UI.States.UIWorldGenDebug.GetControls(), Terraria.GameContent.UI.States.UIWorldGenDebug.GetSnapshotModeButtonTitle(), Terraria.Localization.Language.GetTextValue(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.GameContent.UI.States.UIWorldGenDebug.hideChat, Terraria.GameContent.UI.Elements.UIWrappedSearchBar.HideSearchButton(), Terraria.GameContent.UI.Elements.GroupOptionButton< T >.Icon, Terraria.GameContent.UI.Elements.GroupOptionButton< T >.IconOffset, Terraria.UI.UIElement.IgnoresMouseInteraction, Terraria.ID.Colors.InventoryDefaultColor, Microsoft.Xna.Framework.Input.L, Terraria.GameContent.UI.States.UIWorldGenDebug.LassPassIndex, Terraria.UI.UIElement.Left, Terraria.WorldGen.Manifest, Terraria.WorldBuilding.GenerationProgress.Message, Terraria.UI.UIElement.PaddingLeft, Terraria.WorldBuilding.WorldGenerator.Controller.Paused, Terraria.WorldBuilding.WorldGenerator.Controller.PauseOnHashMismatch, Terraria.Testing.DebugUtils.QuickSPMessage(), Terraria.GameContent.UI.States.UIWorldGenDebug.RefreshControlsPosition(), System.s, Terraria.GameContent.UI.States.UIWorldGenDebug.scrollbar, Terraria.GameContent.UI.States.UIWorldGenDebug.scrollPanel, Terraria.GameContent.UI.States.UIWorldGenDebug.searchBar, Terraria.GameContent.UI.Elements.GroupOptionButton< T >.SetColorsBasedOnSelectionState(), Terraria.GameContent.UI.Elements.GroupOptionButton< T >.SetCurrentOption(), Terraria.GameContent.UI.Elements.GroupOptionButton< T >.SetIconFrame(), Terraria.UI.UIElement.SetPadding(), Terraria.GameContent.UI.Elements.UIGenProgressBar.SetProgress(), Terraria.GameContent.UI.Elements.UIList.SetScrollbar(), Terraria.UI.UserInterface.SetState(), Terraria.GameContent.UI.Elements.UIScrollbar.SetView(), Terraria.GameContent.UI.States.UIWorldGenDebug.StepBack(), Terraria.GameContent.UI.States.UIWorldGenDebug.StepForward(), Terraria.GameContent.UI.Elements.UIImage.Texture, Terraria.GameContent.UI.States.UIWorldGenDebug.ToggleMap(), Terraria.UI.UIElement.Top, Terraria.WorldBuilding.GenerationProgress.TotalProgress, Terraria.UI.UIElement.VAlign, ReLogic.Content.Asset< T >.Value, Terraria.WorldBuilding.GenerationProgress.Value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Graphics.Texture2D.Width, Microsoft.Xna.Framework.Rectangle.Width, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.UIWorldGenDebug.Open().