Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldGenDebug.UpdateAndDrawMap
UpdateAndDrawMap()
void Terraria.GameContent.UI.States.UIWorldGenDebug.UpdateAndDrawMap () inline private
Definition at line 801 of file UIWorldGenDebug.cs.
        {
            Main.spriteBatch.End();
            if (Main.clearMap)
            {
                Main.Map.Clear();
                MapRenderer.DrawToMap(default(Rectangle));
            }
            PlayerInput.SetZoom_Unscaled();
            Rectangle rectangle = Utils.CenteredRectangle(Main.mapFullscreenPos.ToPoint(), (Main.ScreenSize.ToVector2() / Main.mapFullscreenScale).ToPoint());
            rectangle.Inflate(2, 2);
            rectangle = WorldUtils.ClampToWorld(rectangle, 40);
            Stopwatch stopwatch = Stopwatch.StartNew();
            Point point = this.nextMapSection;
            while (stopwatch.ElapsedMilliseconds < 10L)
            {
                Rectangle sectionStripRect = new Rectangle(this.nextMapSection.X * 200, 0, 200, Main.maxTilesY);
                sectionStripRect = Rectangle.Intersect(sectionStripRect, rectangle);
                bool mapUpdate = false;
                FastParallel.For(sectionStripRect.Left, sectionStripRect.Right, delegate(int x1, int x2, object _)
                {
                    bool flag4 = false;
                    int top = sectionStripRect.Top;
                    int bottom = sectionStripRect.Bottom;
                    for (int i = x1; i < x2; i++)
                    {
                        for (int j = top; j < bottom; j++)
{
                            flag4 |= Main.Map.UpdateLighting(i, j, byte.MaxValue);
                        }
                    }
                    if (flag4)
                    {
                        mapUpdate = true;
                    }
                }, null);
                this.nextMapSection.Y = 0;
                while ((this.nextMapSection.Y < Main.maxSectionsY) & mapUpdate)
                {
                    Rectangle rectangle2 = new Rectangle(this.nextMapSection.X * 200, this.nextMapSection.Y * 150, 200, 150);
                    if (rectangle2.Intersects(rectangle))
                    {
                        MapRenderer.DrawToMap_Section(this.nextMapSection.X, this.nextMapSection.Y);
                    }
                    this.nextMapSection.Y = this.nextMapSection.Y + 1;
                }
                this.nextMapSection.X = this.nextMapSection.X + 1;
                if (this.nextMapSection.X >= Main.maxSectionsX)
                {
                    if (this.lastScanRateUpdate.Elapsed > TimeSpan.FromMilliseconds(200.0))
                    {
                        this.lastScanRateUpdate.Restart();
                        this.fullMapScanPeriod = this.fullMapScanTimer.Elapsed;
                    }
                    this.fullMapScanTimer.Restart();
                    this.nextMapSection.X = 0;
                }
                if (this.nextMapSection.X == point.X)
                {
                    break;
                }
            }
            Main.instance.GraphicsDevice.Clear(new Color(100, 100, 255));
            Main.spriteBatch.Begin();
            Main.mapReady = true;
            Main.MapPylonTile = new Point16(-1, -1);
            Main.mapFullscreen = true;
            bool flag = UserInterface.ActiveInstance.MouseCaptured() || UserInterface.ActiveInstance.IsElementUnderMouse();
            bool flag2 = Main.mouseLeft && !flag;
            bool flag3 = Main.mouseRight && !flag;
            Utils.Swap<bool>(ref Main.mouseLeft, ref flag2);
            Utils.Swap<bool>(ref Main.mouseRight, ref flag3);
            Main.instance.DrawMap(new GameTime());
            Utils.Swap<bool>(ref Main.mouseLeft, ref flag2);
            Utils.Swap<bool>(ref Main.mouseRight, ref flag3);
            Main.mapFullscreen = false;
            PlayerInput.SetZoom_UI();
            Main.spriteBatch.End();
            Main.spriteBatch.Begin(SpriteSortMode.Deferred, null, null, null, null, null, Main.UIScaleMatrix);
            if (Main.showFrameRate)
            {
                double num = Math.Min(1.0 / this.fullMapScanPeriod.TotalSeconds, 60.0);
                string text = string.Format((num >= 10.0) ? "{0:0}" : "{0:0.0}", num);
                text += " map scans/s";
                DynamicSpriteFontExtensionMethods.DrawString(Main.spriteBatch, FontAssets.MouseText.Value, text, new Vector2((float)(Main.screenWidth - (int)FontAssets.MouseText.Value.MeasureString(text).X), 4f), new Color((int)Main.mouseTextColor, (int)Main.mouseTextColor, (int)Main.mouseTextColor, (int)Main.mouseTextColor));
            }
        }
References Terraria.UI.UserInterface.ActiveInstance, Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(), Microsoft.Xna.Framework.Rectangle.Bottom, Terraria.Utils.CenteredRectangle(), Terraria.WorldBuilding.WorldUtils.ClampToWorld(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.Clear(), Terraria.Main.clearMap, Microsoft.Xna.Framework.Graphics.Color, Terraria.Main.DrawMap(), ReLogic.Graphics.DynamicSpriteFontExtensionMethods.DrawString(), Terraria.MapRenderer.DrawToMap(), Terraria.MapRenderer.DrawToMap_Section(), Microsoft.Xna.Framework.Graphics.SpriteBatch.End(), ReLogic.Threading.FastParallel.For(), System.TimeSpan.FromMilliseconds(), Terraria.GameContent.UI.States.UIWorldGenDebug.fullMapScanPeriod, Terraria.GameContent.UI.States.UIWorldGenDebug.fullMapScanTimer, Microsoft.Xna.Framework.Game.GraphicsDevice, Microsoft.Xna.Framework.Rectangle.Inflate(), Terraria.Main.instance, int, Microsoft.Xna.Framework.Rectangle.Intersect(), Microsoft.Xna.Framework.Rectangle.Intersects(), Terraria.UI.UserInterface.IsElementUnderMouse(), Microsoft.Xna.Framework.Input.L, Terraria.GameContent.UI.States.UIWorldGenDebug.lastScanRateUpdate, Microsoft.Xna.Framework.Rectangle.Left, Terraria.Main.Map, Terraria.Main.mapFullscreenPos, Terraria.Main.mapFullscreenScale, Terraria.Main.maxSectionsX, Terraria.Main.maxSectionsY, Terraria.Main.maxTilesY, System.Math.Min(), Terraria.UI.UserInterface.MouseCaptured(), Terraria.Main.mouseLeft, Terraria.Main.mouseRight, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.mouseTextColor, Terraria.GameContent.UI.States.UIWorldGenDebug.nextMapSection, Microsoft.Xna.Framework.Rectangle.Right, Terraria.Main.ScreenSize, Terraria.GameInput.PlayerInput.SetZoom_UI(), Terraria.GameInput.PlayerInput.SetZoom_Unscaled(), Terraria.Main.showFrameRate, Terraria.Main.spriteBatch, System.text, Microsoft.Xna.Framework.Rectangle.Top, System.TimeSpan.TotalSeconds, Terraria.Main.UIScaleMatrix, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.UI.States.UIWorldGenDebug.DrawSelf().