Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldGenDebug.Draw
Draw()
override void Terraria.GameContent.UI.States.UIWorldGenDebug.Draw (SpriteBatch spriteBatch) inline virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 771 of file UIWorldGenDebug.cs.
        {
            this.UpdateFilter();
            if (Main.gameMenu)
            {
                Main.UIScale = Main.UIScaleWanted;
                PlayerInput.SetZoom_UI();
                Main.spriteBatch.End();
                Main.spriteBatch.Begin(SpriteSortMode.Deferred, null, null, null, null, null, Main.UIScaleMatrix);
            }
            base.Draw(spriteBatch);
            if (!this.showMap)
            {
                Main.DrawInterface_37_DebugStuff();
            }
        }
References Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(), Terraria.Main.DrawInterface_37_DebugStuff(), Microsoft.Xna.Framework.Graphics.SpriteBatch.End(), Terraria.Main.gameMenu, Terraria.GameInput.PlayerInput.SetZoom_UI(), Terraria.GameContent.UI.States.UIWorldGenDebug.showMap, Terraria.Main.spriteBatch, Terraria.Main.UIScaleMatrix, Terraria.Main.UIScaleWanted, and Terraria.GameContent.UI.States.UIWorldGenDebug.UpdateFilter().