Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldGenDebug.OnActivate
OnActivate()
override void Terraria.GameContent.UI.States.UIWorldGenDebug.OnActivate () inline virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 489 of file UIWorldGenDebug.cs.
        {
            UIWorldGenDebug.Config.Load();
            if (UIWorldGenDebug.Controller.SnapshotFrequency == WorldGenerator.SnapshotFrequency.None)
            {
                UIWorldGenDebug.Controller.SnapshotFrequency = WorldGenerator.SnapshotFrequency.Automatic;
            }
            Main.menuChat = true;
            if (Main.gameMenu)
            {
                PlayerInput.SetZoom_World();
                Main.mapFullscreenPos = new Vector2((float)(Main.maxTilesX / 2), (float)(Main.maxTilesY / 2));
                Main.mapFullscreenScale = (float)Main.screenWidth / (float)Main.maxTilesX;
            }
            else
            {
                Main.mapFullscreenScale = 2.5f;
                Main.mapFullscreenPos = Main.Camera.Center / 16f;
            }
            this.ToggleMap();
            if (!Main.gameMenu && !DebugOptions.devLightTilesCheat)
            {
                DebugOptions.devLightTilesCheat = true;
                this.disableLightOnClose = true;
            }
        }
References Terraria.GameContent.UI.States.UIWorldGenDebug.Controller, Terraria.Testing.DebugOptions.devLightTilesCheat, Terraria.Main.gameMenu, Terraria.GameContent.UI.States.UIWorldGenDebug.Config.Load(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.screenWidth, Terraria.GameInput.PlayerInput.SetZoom_World(), Terraria.GameContent.UI.States.UIWorldGenDebug.ToggleMap(), and Microsoft.Xna.Framework.Graphics.Vector2.