Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldGenDebug.TestHiddenTileData
TestHiddenTileData()
static IEnumerable< object > Terraria.GameContent.UI.States.UIWorldGenDebug.TestHiddenTileData () inline static
Definition at line 961 of file UIWorldGenDebug.cs.
        {
            using (IEnumerator<bool> enumerator = UIWorldGenDebug.TestSetupResetAndCreateSnapshots().GetEnumerator())
            {
                while (enumerator.MoveNext())
                {
                    if (!enumerator.Current)
                    {
                        yield break;
                    }
                    yield return null;
                }
            }
            IEnumerator<bool> enumerator = null;
            UIWorldGenDebug.Controller.TryReset();
            foreach (GenPass pass in UIWorldGenDebug.Controller.Passes.Where((GenPass p) => p.Enabled))
            {
                TileSnapshot.Create(null);
                TileSnapshot.Restore();
                UIWorldGenDebug.Controller.TryRunToEndOfPass(pass, false, true);
                yield return null;
                if (UIWorldGenDebug.Controller.LastCompletedPass != pass || UIWorldGenDebug.Controller.PausedDueToHashMismatch)
                {
                    Main.NewText("Test aborted", byte.MaxValue, 0, 0);
                    yield break;
                }
                pass = null;
            }
            IEnumerator<GenPass> enumerator2 = null;
            Main.NewText("Test Completed Successfully", 0, byte.MaxValue, 0);
            yield break;
            yield break;
        }
References Terraria.GameContent.UI.States.UIWorldGenDebug.Controller, Terraria.Utilities.TileSnapshot.Create(), System.Collections.Generic.IEnumerator< out T >.Current, Terraria.WorldBuilding.GenPass.Enabled, System.Collections.IEnumerator.MoveNext(), Terraria.Main.NewText(), Terraria.Utilities.TileSnapshot.Restore(), and Terraria.GameContent.UI.States.UIWorldGenDebug.TestSetupResetAndCreateSnapshots().