Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldGenDebug.EnsurePassVisible
EnsurePassVisible()
void Terraria.GameContent.UI.States.UIWorldGenDebug.EnsurePassVisible (int passIndex) inline private
Definition at line 372 of file UIWorldGenDebug.cs.
        {
            if (passIndex < this.allPasses.Count)
            {
                UIWorldGenDebug.GenPassElement genPassElement = this.allPasses[passIndex];
                if (!this.searchVisible || string.IsNullOrEmpty(this.searchText) || this.MatchesSearch(genPassElement.Pass))
                {
                    float height = this.scrollPanel.GetDimensions().Height;
                    if (genPassElement.Height.Pixels + genPassElement.Top.Pixels > this.scrollbar.ViewPosition + height - 8f)
                    {
                        this.scrollbar.ViewPosition = genPassElement.Top.Pixels - (height - 8f) + genPassElement.Height.Pixels;
                        return;
                    }
                    if (genPassElement.Top.Pixels < this.scrollbar.ViewPosition)
                    {
                        this.scrollbar.ViewPosition = genPassElement.Top.Pixels;
                    }
                }
            }
        }
References Terraria.GameContent.UI.States.UIWorldGenDebug.allPasses, Terraria.UI.UIElement.GetDimensions(), Terraria.UI.CalculatedStyle.Height, Terraria.UI.UIElement.Height, Terraria.GameContent.UI.States.UIWorldGenDebug.MatchesSearch(), Terraria.GameContent.UI.States.UIWorldGenDebug.GenPassElement.Pass, Terraria.UI.StyleDimension.Pixels, Terraria.GameContent.UI.States.UIWorldGenDebug.scrollPanel, Terraria.GameContent.UI.States.UIWorldGenDebug.searchText, Terraria.GameContent.UI.States.UIWorldGenDebug.searchVisible, and Terraria.UI.UIElement.Top.
Referenced by Terraria.GameContent.UI.States.UIWorldGenDebug.UIWorldGenDebug().