Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldGenDebug.UpdateFilter
UpdateFilter()
void Terraria.GameContent.UI.States.UIWorldGenDebug.UpdateFilter () inline private
Definition at line 695 of file UIWorldGenDebug.cs.
        {
            if (this.searchVisible && !string.IsNullOrEmpty(this.searchText))
            {
                if (!(this.lastSearchText != this.searchText))
                {
                    return;
                }
                this.GenPassList.Clear();
                this.lastSearchText = this.searchText;
                using (List<UIWorldGenDebug.GenPassElement>.Enumerator enumerator = this.allPasses.GetEnumerator())
                {
                    while (enumerator.MoveNext())
                    {
                        UIWorldGenDebug.GenPassElement genPassElement = enumerator.Current;
                        if (this.MatchesSearch(genPassElement.Pass))
{
                            this.GenPassList.Add(genPassElement);
                        }
                    }
                    return;
                }
            }
            if (this.allPasses.Count != this.GenPassList.Count)
            {
                this.lastSearchText = null;
                this.GenPassList.Clear();
                foreach (UIWorldGenDebug.GenPassElement genPassElement2 in this.allPasses)
                {
                    this.GenPassList.Add(genPassElement2);
                }
            }
        }
References Terraria.GameContent.UI.Elements.UIList.Add(), Terraria.GameContent.UI.States.UIWorldGenDebug.allPasses, Terraria.GameContent.UI.Elements.UIList.Clear(), Terraria.GameContent.UI.States.UIWorldGenDebug.GenPassList, Terraria.GameContent.UI.States.UIWorldGenDebug.lastSearchText, Terraria.GameContent.UI.States.UIWorldGenDebug.MatchesSearch(), Terraria.GameContent.UI.States.UIWorldGenDebug.GenPassElement.Pass, Terraria.GameContent.UI.States.UIWorldGenDebug.searchText, and Terraria.GameContent.UI.States.UIWorldGenDebug.searchVisible.
Referenced by Terraria.GameContent.UI.States.UIWorldGenDebug.Draw().