Terraria Decompiled: Terraria.WorldBuilding.AWorldGenerationOption.Load
Load()
void Terraria.WorldBuilding.AWorldGenerationOption.Load () inline
Definition at line 168 of file AWorldGenerationOption.cs.
        {
            if (this.Texture != null)
            {
                return;
            }
            this.Description = Language.GetText("UI." + this.KeyName);
            this.Title = Language.GetText("UI." + this.KeyName + "_Title");
            if (Main.dedServ)
            {
                return;
            }
            this.Texture = Main.Assets.Request<Texture2D>("Images/UI/WorldCreation/" + this.KeyName, 1);
        }
References Terraria.Main.Assets, Terraria.Main.dedServ, Terraria.Localization.Language.GetText(), and Terraria.WorldBuilding.AWorldGenerationOption.KeyName.
Referenced by Terraria.Main.DedServ_SeedFlagsMenu(), and Terraria.GameContent.UI.States.UIWorldCreationAdvanced.PrepareSeedButtons().