Terraria Decompiled: System.Collections.Generic.KeyValuePair.PairToString
PairToString()
static string System.Collections.Generic.KeyValuePair< TKey, TValue >.PairToString (object key, object value) inline static package
Definition at line 16 of file KeyValuePair.cs.
        {
            StringBuilder stringBuilder = StringBuilderCache.Acquire(16);
            stringBuilder.Append('[');
            if (key != null)
            {
                stringBuilder.Append(key);
            }
            stringBuilder.Append(", ");
            if (value != null)
            {
                stringBuilder.Append(value);
            }
            stringBuilder.Append(']');
            return StringBuilderCache.GetStringAndRelease(stringBuilder);
        }
References System.Text.StringBuilderCache.Acquire(), System.Text.StringBuilder.Append(), System.Text.StringBuilderCache.GetStringAndRelease(), System.Collections.Generic.KeyValuePair< TKey, TValue >.key, and System.Collections.Generic.KeyValuePair< TKey, TValue >.value.
Referenced by System.Collections.Generic.KeyValuePair< TKey, TValue >.ToString().