Terraria Decompiled: System.BCLDebug.CheckEnabled
CheckEnabled()
static bool System.BCLDebug.CheckEnabled (string switchName) inline static package
Definition at line 52 of file BCLDebug.cs.
        {
            return false;
        }
Referenced by System.Runtime.Serialization.Formatters.Binary.BinaryAssembly.DumpInternal(), System.Runtime.Serialization.Formatters.Binary.BinaryCrossAppDomainAssembly.DumpInternal(), System.Runtime.Serialization.Formatters.Binary.BinaryCrossAppDomainMap.DumpInternal(), System.Runtime.Serialization.Formatters.Binary.BinaryCrossAppDomainString.DumpInternal(), System.Runtime.Serialization.Formatters.Binary.BinaryMethodCall.DumpInternal(), System.Runtime.Serialization.Formatters.Binary.BinaryMethodReturn.DumpInternal(), System.Runtime.Serialization.Formatters.Binary.BinaryObject.DumpInternal(), System.Runtime.Serialization.Formatters.Binary.BinaryObjectString.DumpInternal(), System.Runtime.Serialization.Formatters.Binary.BinaryObjectWithMap.DumpInternal(), System.Runtime.Serialization.Formatters.Binary.MemberPrimitiveTyped.DumpInternal(), System.Runtime.Serialization.Formatters.Binary.MemberPrimitiveUnTyped.DumpInternal(), System.Runtime.Serialization.Formatters.Binary.MemberReference.DumpInternal(), System.Runtime.Serialization.Formatters.Binary.ObjectNull.DumpInternal(), System.Runtime.Serialization.Formatters.Binary.SerializationHeaderRecord.DumpInternal(), System.Runtime.Serialization.Formatters.Binary.MessageEnd.DumpInternal(), System.Runtime.Serialization.Formatters.Binary.BinaryUtil.NVTraceI(), System.Runtime.Serialization.Formatters.Binary.BinaryUtil.NVTraceI(), System.Runtime.Serialization.Formatters.InternalRM.SoapCheckEnabled(), and System.Runtime.Serialization.Formatters.InternalST.SoapCheckEnabled().