Terraria Decompiled: Terraria.GameContent.LeashedEntities.LeashedCritter.VisualEffects
VisualEffects()
virtual void Terraria.GameContent.LeashedEntities.LeashedCritter.VisualEffects () inline protected virtual
Reimplemented in Terraria.GameContent.LeashedEntities.EmpressButterflyLeashedCritter, Terraria.GameContent.LeashedEntities.FairyLeashedCritter, Terraria.GameContent.LeashedEntities.FireflyLeashedCritter, Terraria.GameContent.LeashedEntities.HellButterflyLeashedCritter, Terraria.GameContent.LeashedEntities.ShimmerFlyLeashedCritter, and Terraria.GameContent.LeashedEntities.SnailLeashedCritter.
Definition at line 111 of file LeashedCritter.cs.
        {
            if (this.npcType >= 0 && NPCID.Sets.IsGoldCritter[this.npcType])
            {
                this.position += this.netOffset;
                Color color = Lighting.GetColor((int)base.Center.X / 16, (int)base.Center.Y / 16);
                if (color.R > 20 || color.B > 20 || color.G > 20)
                {
                    int num = (int)color.R;
                    if ((int)color.G > num)
                    {
                        num = (int)color.G;
                    }
                    if ((int)color.B > num)
                    {
                        num = (int)color.B;
                    }
                    num /= 30;
                    if (Main.rand.Next(300) < num)
                    {
                        int num2 = Dust.NewDust(this.position, this.width, this.height, 43, 0f, 0f, 254, new Color(255, 255, 0), 0.5f);
                        Main.dust[num2].velocity *= 0f;
                    }
                }
                this.position -= this.netOffset;
            }
        }
References Microsoft.Xna.Framework.Color.B, Microsoft.Xna.Framework.Graphics.Color, Terraria.Main.dust, Microsoft.Xna.Framework.Color.G, Terraria.Lighting.GetColor(), Terraria.GameContent.LeashedEntity.height, int, Terraria.ID.NPCID.Sets.IsGoldCritter, Terraria.GameContent.LeashedEntities.LeashedCritter.netOffset, Terraria.Dust.NewDust(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.GameContent.LeashedEntities.LeashedCritter.npcType, Terraria.GameContent.LeashedEntity.position, Microsoft.Xna.Framework.Color.R, Terraria.Main.rand, Terraria.Dust.velocity, and Terraria.GameContent.LeashedEntity.width.
Referenced by Terraria.GameContent.LeashedEntities.FlyerLeashedCritter.Update(), Terraria.GameContent.LeashedEntities.JumperLeashedCritter.Update(), and Terraria.GameContent.LeashedEntities.WalkerLeashedCritter.Update().