Terraria Decompiled: Terraria.GameContent.LeashedEntities.LeashedCritter.DrawBubble
DrawBubble()
void Terraria.GameContent.LeashedEntities.LeashedCritter.DrawBubble () inline protected
Definition at line 192 of file LeashedCritter.cs.
        {
            Main.instance.LoadGore(413);
            Texture2D value = TextureAssets.Gore[413].Value;
            Rectangle rectangle = value.Frame(1, 1, 0, 0, 0, 0);
            Vector2 vector = rectangle.Size() / 2f;
            Vector2 vector2 = this.position;
            vector2 += this.netOffset + this.GetDrawOffset() + LeashedCritter._dummy.Size * new Vector2(0.5f, 0.5f);
            Point point = vector2.ToTileCoordinates();
            Main.spriteBatch.Draw(value, vector2 - Main.screenPosition, new Rectangle?(rectangle), Lighting.GetColor(point), 0f, vector, 1f, SpriteEffects.None, 0f);
        }
References Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Lighting.GetColor(), Terraria.GameContent.LeashedEntities.LeashedCritter.GetDrawOffset(), Terraria.GameContent.TextureAssets.Gore, Terraria.Main.instance, Terraria.Main.LoadGore(), Terraria.GameContent.LeashedEntity.position, Terraria.Main.screenPosition, Terraria.Main.spriteBatch, System.value, ReLogic.Content.Asset< T >.Value, and Microsoft.Xna.Framework.Graphics.Vector2.
Referenced by Terraria.GameContent.LeashedEntities.LeashedCritter.Draw().