Terraria Decompiled: Terraria.GameContent.LeashedEntities.LeashedCritter.Draw
Draw()
override void Terraria.GameContent.LeashedEntities.LeashedCritter.Draw () inline virtual
Reimplemented from Terraria.GameContent.LeashedEntity.
Reimplemented in Terraria.GameContent.LeashedEntities.ShimmerFlyLeashedCritter.
Definition at line 167 of file LeashedCritter.cs.
        {
            Main.instance.LoadNPC(this.npcType);
            if (this.frame.Width == 0 || this.frame.Height == 0)
            {
                this.frame = new Rectangle(0, 0, TextureAssets.Npc[this.npcType].Width(), TextureAssets.Npc[this.npcType].Height() / Main.npcFrameCount[this.npcType]);
            }
            this.CopyToDummy();
            LeashedCritter._dummy.position += this.netOffset + this.GetDrawOffset();
            Main.instance.DrawNPCDirect(Main.spriteBatch, LeashedCritter._dummy, true, Main.screenPosition);
            Point point = LeashedCritter._dummy.Center.ToTileCoordinates();
            byte liquid = Framing.GetTileSafely(point.X, point.Y).liquid;
            if ((this.isAquatic && liquid < 255) || (!this.isAquatic && liquid > 0))
            {
                this.DrawBubble();
            }
        }
References Terraria.GameContent.LeashedEntities.LeashedCritter._dummy, Terraria.Entity.Center, Terraria.GameContent.LeashedEntities.LeashedCritter.CopyToDummy(), Terraria.GameContent.LeashedEntities.LeashedCritter.DrawBubble(), Terraria.Main.DrawNPCDirect(), Terraria.GameContent.LeashedEntities.LeashedCritter.frame, Terraria.GameContent.LeashedEntities.LeashedCritter.GetDrawOffset(), Terraria.Framing.GetTileSafely(), Terraria.Main.instance, Terraria.GameContent.LeashedEntities.LeashedCritter.isAquatic, Terraria.Tile.liquid, Terraria.Main.LoadNPC(), Terraria.GameContent.TextureAssets.Npc, Terraria.Main.npcFrameCount, Terraria.GameContent.LeashedEntities.LeashedCritter.npcType, Terraria.Main.screenPosition, Terraria.Main.spriteBatch, Microsoft.Xna.Framework.Rectangle.Width, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.