Terraria Decompiled: Terraria.GameContent.LeashedEntities.LeashedCritter.NetReceive
NetReceive()
override void Terraria.GameContent.LeashedEntities.LeashedCritter.NetReceive (BinaryReader reader, bool full) inline virtual
Reimplemented from Terraria.GameContent.LeashedEntity.
Reimplemented in Terraria.GameContent.LeashedEntities.NormalButterflyLeashedCritter, and Terraria.GameContent.LeashedEntities.ShimmerFlyLeashedCritter.
Definition at line 46 of file LeashedCritter.cs.
        {
            if (full)
            {
                this.npcType = reader.Read7BitEncodedInt();
                base.Size = reader.ReadVector2();
            }
            Vector2 position = this.position;
            this.position = reader.ReadPackedVector2() + base.AnchorPosition.ToWorldCoordinates(8f, 8f);
            this.direction = (reader.ReadBoolean() ? 1 : (-1));
            this.rand.state = reader.ReadUInt32();
            this.WaitTime = reader.ReadInt16();
            this.State = reader.ReadByte();
            this.TargetPosition = new Point16((int)(base.AnchorPosition.X + (short)reader.ReadSByte()), (int)(base.AnchorPosition.Y + (short)reader.ReadSByte()));
            if (full)
            {
                this.netOffset = Vector2.Zero;
            }
            else
            {
                this.netOffset += position - this.position;
            }
            if (full)
            {
                this.Update();
            }
        }
References Terraria.GameContent.LeashedEntity.position, System.IO.BinaryReader.Read7BitEncodedInt(), System.IO.BinaryReader.ReadBoolean(), System.IO.BinaryReader.ReadByte(), System.IO.BinaryReader.ReadInt16(), System.IO.BinaryReader.ReadSByte(), System.IO.BinaryReader.ReadUInt32(), Terraria.GameContent.LeashedEntities.LeashedCritter.Update(), and Microsoft.Xna.Framework.Vector2.Zero.