Terraria Decompiled: System.Globalization.ISOWeek.GetWeeksInYear
GetWeeksInYear()
static int System.Globalization.ISOWeek.GetWeeksInYear (int year) inline static
Definition at line 52 of file ISOWeek.cs.
        {
            if (year < 1 || year > 9999)
            {
                throw new ArgumentOutOfRangeException("year", "Year must be between 1 and 9999.");
            }
            if (ISOWeek.<GetWeeksInYear>g__P|8_0(year) == 4 || ISOWeek.<GetWeeksInYear>g__P|8_0(year - 1) == 3)
            {
                return 53;
            }
            return 52;
        }
References System.Globalization.ISOWeek.g__P(), and System.Globalization.ISOWeek.GetWeeksInYear().
Referenced by System.Globalization.ISOWeek.GetWeekOfYear(), System.Globalization.ISOWeek.GetWeeksInYear(), System.Globalization.ISOWeek.GetYear(), and System.Globalization.ISOWeek.GetYearEnd().