Terraria Decompiled: Microsoft.Xna.Framework.SDL3_FNAPlatform.ReadToPointer
ReadToPointer()
static IntPtr Microsoft.Xna.Framework.SDL3_FNAPlatform.ReadToPointer (string path, out IntPtr size) inline static
Definition at line 990 of file SDL3_FNAPlatform.cs.
        {
            UIntPtr uintPtr;
            IntPtr intPtr = SDL.SDL_LoadFile(path, out uintPtr);
            size = (IntPtr)uintPtr.ToPointer();
            return intPtr;
        }
References SDL3.SDL.SDL_LoadFile(), and System.UIntPtr.ToPointer().
Referenced by Microsoft.Xna.Framework.FNAPlatform.FNAPlatform().