Terraria Decompiled: Microsoft.Xna.Framework.SDL3_FNAPlatform.GetGamePadAccelerometer
GetGamePadAccelerometer()
static unsafe bool Microsoft.Xna.Framework.SDL3_FNAPlatform.GetGamePadAccelerometer (int index, out Vector3 accel) inline static
Definition at line 1259 of file SDL3_FNAPlatform.cs.
        {
            IntPtr intPtr = SDL3_FNAPlatform.INTERNAL_devices[index];
            if (intPtr == IntPtr.Zero)
            {
                accel = Vector3.Zero;
                return false;
            }
            if (!SDL.SDL_GamepadSensorEnabled(intPtr, SDL.SDL_SensorType.SDL_SENSOR_ACCEL))
            {
                SDL.SDL_SetGamepadSensorEnabled(intPtr, SDL.SDL_SensorType.SDL_SENSOR_ACCEL, true);
            }
            float* ptr = stackalloc float[(UIntPtr)12];
            if (!SDL.SDL_GetGamepadSensorData(intPtr, SDL.SDL_SensorType.SDL_SENSOR_ACCEL, ptr, 3))
            {
                accel = Vector3.Zero;
                return false;
            }
            accel.X = *ptr;
            accel.Y = ptr[1];
            accel.Z = ptr[2];
            return true;
        }
References System.index, Microsoft.Xna.Framework.SDL3_FNAPlatform.INTERNAL_devices, SDL3.SDL.SDL_GamepadSensorEnabled(), SDL3.SDL.SDL_GetGamepadSensorData(), SDL3.SDL.SDL_SetGamepadSensorEnabled(), Microsoft.Xna.Framework.Vector3.Zero, and System.IntPtr.Zero.
Referenced by Microsoft.Xna.Framework.FNAPlatform.FNAPlatform().