Terraria Decompiled: Microsoft.Xna.Framework.SDL3_FNAPlatform.GetGraphicsAdapters
GetGraphicsAdapters()
static unsafe GraphicsAdapter[] Microsoft.Xna.Framework.SDL3_FNAPlatform.GetGraphicsAdapters () inline static
Definition at line 759 of file SDL3_FNAPlatform.cs.
        {
            int num;
            uint* ptr = (uint*)(void*)SDL.SDL_GetDisplays(out num);
            GraphicsAdapter[] array = new GraphicsAdapter[num];
            SDL3_FNAPlatform.displayIds = new uint[num];
            for (int i = 0; i < array.Length; i++)
            {
                List<DisplayMode> list = new List<DisplayMode>();
                int num2;
                SDL.SDL_DisplayMode** ptr2 = (SDL.SDL_DisplayMode**)(void*)SDL.SDL_GetFullscreenDisplayModes(ptr[i], out num2);
                for (int j = num2 - 1; j >= 0; j--)
                {
                    bool flag = false;
                    foreach (DisplayMode displayMode in list)
                    {
                        if (((IntPtr*)(ptr2 + (IntPtr)j * (IntPtr)sizeof(SDL.SDL_DisplayMode*) / (IntPtr)sizeof(SDL.SDL_DisplayMode*)))->w == displayMode.Width && ((IntPtr*)(ptr2 + (IntPtr)j * (IntPtr)sizeof(SDL.SDL_DisplayMode*) / (IntPtr)sizeof(SDL.SDL_DisplayMode*)))->h == displayMode.Height)
{
                            flag = true;
                        }
                    }
                    if (!flag)
                    {
                        list.Add(new DisplayMode(((IntPtr*)(ptr2 + (IntPtr)j * (IntPtr)sizeof(SDL.SDL_DisplayMode*) / (IntPtr)sizeof(SDL.SDL_DisplayMode*)))->w, ((IntPtr*)(ptr2 + (IntPtr)j * (IntPtr)sizeof(SDL.SDL_DisplayMode*) / (IntPtr)sizeof(SDL.SDL_DisplayMode*)))->h, SurfaceFormat.Color));
                    }
                }
                SDL.SDL_free((IntPtr)((void*)ptr2));
                array[i] = new GraphicsAdapter(new DisplayModeCollection(list), "\\\\.\\DISPLAY" + (i + 1).ToString(), SDL.SDL_GetDisplayName(ptr[i]));
                SDL3_FNAPlatform.displayIds[i] = ptr[i];
            }
            SDL.SDL_free((IntPtr)((void*)ptr));
            return array;
        }
References System.IntPtr.Add(), System.array, Microsoft.Xna.Framework.SDL3_FNAPlatform.displayIds, Microsoft.Xna.Framework.Graphics.DisplayMode.Height, System.list, SDL3.SDL.SDL_free(), SDL3.SDL.SDL_GetDisplayName(), SDL3.SDL.SDL_GetDisplays(), SDL3.SDL.SDL_GetFullscreenDisplayModes(), and System.ToString.
Referenced by Microsoft.Xna.Framework.FNAPlatform.FNAPlatform().