Terraria Decompiled: Microsoft.Xna.Framework.SDL3_FNAPlatform.GetKeyFromScancode
GetKeyFromScancode()
static Keys Microsoft.Xna.Framework.SDL3_FNAPlatform.GetKeyFromScancode (Keys scancode) inline static
Definition at line 1520 of file SDL3_FNAPlatform.cs.
        {
            if (SDL3_FNAPlatform.UseScancodes)
            {
                return scancode;
            }
            SDL.SDL_Scancode sdl_Scancode;
            if (SDL3_FNAPlatform.INTERNAL_xnaMap.TryGetValue((int)scancode, out sdl_Scancode))
            {
                uint num = SDL.SDL_GetKeyFromScancode(sdl_Scancode, SDL.SDL_Keymod.SDL_KMOD_NONE, true);
                Keys keys;
                if (SDL3_FNAPlatform.INTERNAL_keyMap.TryGetValue((int)num, out keys))
                {
                    return keys;
                }
                FNALoggerEXT.LogWarn("KEYCODE MISSING FROM SDL3->XNA DICTIONARY: " + num.ToString());
            }
            else
            {
                FNALoggerEXT.LogWarn("SCANCODE MISSING FROM XNA->SDL3 DICTIONARY: " + scancode.ToString());
            }
            return Keys.None;
        }
References Microsoft.Xna.Framework.SDL3_FNAPlatform.INTERNAL_keyMap, Microsoft.Xna.Framework.SDL3_FNAPlatform.INTERNAL_xnaMap, Microsoft.Xna.Framework.FNALoggerEXT.LogWarn, SDL3.SDL.SDL_GetKeyFromScancode(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and Microsoft.Xna.Framework.SDL3_FNAPlatform.UseScancodes.
Referenced by Microsoft.Xna.Framework.FNAPlatform.FNAPlatform().