Terraria Decompiled: Microsoft.Xna.Framework.SDL3_FNAPlatform.ProgramInit
ProgramInit()
static string Microsoft.Xna.Framework.SDL3_FNAPlatform.ProgramInit (LaunchParameters args) inline static
Definition at line 20 of file SDL3_FNAPlatform.cs.
        {
            try
            {
                SDL3_FNAPlatform.OSVersion = SDL.SDL_GetPlatform();
            }
            catch (DllNotFoundException)
            {
                FNALoggerEXT.LogError("SDL3 was not found! Do you have fnalibs?");
                throw;
            }
            catch (BadImageFormatException ex)
            {
                string text = string.Format("This process is {0}-bit, the DLL is {1}-bit!", (IntPtr.Size == 4) ? "32" : "64", (IntPtr.Size == 4) ? "64" : "32");
                FNALoggerEXT.LogError(text);
                throw new BadImageFormatException(text, ex);
            }
            SDL.SDL_SetMainReady();
            string baseDirectory = SDL3_FNAPlatform.GetBaseDirectory();
            string text2 = Path.Combine(baseDirectory, "gamecontrollerdb.txt");
            if (File.Exists(text2))
            {
                SDL.SDL_SetHint("SDL_GAMECONTROLLERCONFIG_FILE", text2);
            }
            if (Environment.GetEnvironmentVariable("FNA_NUKE_STEAM_INPUT") == "1")
            {
                SDL.SDL_SetHintWithPriority("SDL_GAMECONTROLLER_IGNORE_DEVICES", "0x28DE/0x11FF", SDL.SDL_HintPriority.SDL_HINT_OVERRIDE);
                SDL.SDL_SetHintWithPriority("SDL_GAMECONTROLLER_IGNORE_DEVICES_EXCEPT", "", SDL.SDL_HintPriority.SDL_HINT_OVERRIDE);
                SDL.SDL_SetHintWithPriority("SDL_GAMECONTROLLER_ALLOW_STEAM_VIRTUAL_GAMEPAD", "0", SDL.SDL_HintPriority.SDL_HINT_OVERRIDE);
            }
            string text3;
            if (args.TryGetValue("glprofile", out text3))
            {
                if (text3 == "es3")
                {
                    SDL.SDL_SetHintWithPriority("FNA3D_OPENGL_FORCE_ES3", "1", SDL.SDL_HintPriority.SDL_HINT_OVERRIDE);
                }
                else if (text3 == "core")
                {
                    SDL.SDL_SetHintWithPriority("FNA3D_OPENGL_FORCE_CORE_PROFILE", "1", SDL.SDL_HintPriority.SDL_HINT_OVERRIDE);
                }
                else if (text3 == "compatibility")
                {
                    SDL.SDL_SetHintWithPriority("FNA3D_OPENGL_FORCE_COMPATIBILITY_PROFILE", "1", SDL.SDL_HintPriority.SDL_HINT_OVERRIDE);
                }
            }
            if (args.TryGetValue("angle", out text3) && text3 == "1")
            {
                SDL.SDL_SetHintWithPriority("FNA3D_OPENGL_FORCE_ES3", "1", SDL.SDL_HintPriority.SDL_HINT_OVERRIDE);
                SDL.SDL_SetHintWithPriority("SDL_OPENGL_ES_DRIVER", "1", SDL.SDL_HintPriority.SDL_HINT_OVERRIDE);
            }
            if (args.TryGetValue("forcemailboxvsync", out text3) && text3 == "1")
            {
                SDL.SDL_SetHintWithPriority("FNA3D_VULKAN_FORCE_MAILBOX_VSYNC", "1", SDL.SDL_HintPriority.SDL_HINT_OVERRIDE);
            }
            if (args.TryGetValue("audiodriver", out text3))
            {
                SDL.SDL_SetHintWithPriority("SDL_AUDIO_DRIVER", text3, SDL.SDL_HintPriority.SDL_HINT_OVERRIDE);
            }
            if (!SDL.SDL_Init(SDL.SDL_InitFlags.SDL_INIT_VIDEO | SDL.SDL_InitFlags.SDL_INIT_GAMEPAD))
            {
                throw new Exception("SDL_Init failed: " + SDL.SDL_GetError());
            }
            string text4 = SDL.SDL_GetCurrentVideoDriver();
            SDL3_FNAPlatform.SupportsGlobalMouse = SDL3_FNAPlatform.OSVersion.Equals("Windows") || SDL3_FNAPlatform.OSVersion.Equals("macOS") || text4.Equals("x11");
            if (Environment.GetEnvironmentVariable("FNA_MOUSE_DISABLE_GLOBAL_ACCESS") == "1")
            {
                SDL3_FNAPlatform.SupportsGlobalMouse = false;
            }
            if (SDL3_FNAPlatform.SupportsGlobalMouse)
            {
                SDL.SDL_SetHint("SDL_MOUSE_EMULATE_WARP_WITH_RELATIVE", "0");
            }
            SDL3_FNAPlatform.SupportsOrientations = SDL3_FNAPlatform.OSVersion.Equals("iOS") || SDL3_FNAPlatform.OSVersion.Equals("Android");
            if (SDL3_FNAPlatform.OSVersion.Equals("Windows"))
            {
                SDL.SDL_SetHint("SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS", "1");
            }
            if (string.IsNullOrEmpty(SDL.SDL_GetHint("SDL_JOYSTICK_ALLOW_BACKGROUND_EVENTS")))
            {
                SDL.SDL_SetHint("SDL_JOYSTICK_ALLOW_BACKGROUND_EVENTS", "1");
            }
            SDL.SDL_SetHint("SDL_ORIENTATIONS", "LandscapeLeft LandscapeRight Portrait");
            SDL.SDL_Event[] array = new SDL.SDL_Event[1];
            SDL.SDL_PumpEvents();
            while (SDL.SDL_PeepEvents(array, 1, SDL.SDL_EventAction.SDL_GETEVENT, 1619U, 1619U) == 1)
            {
                SDL3_FNAPlatform.INTERNAL_AddInstance(array[0].gdevice.which);
            }
            if (SDL3_FNAPlatform.OSVersion.Equals("Windows") && SDL.SDL_GetHint("FNA_WIN32_IGNORE_WM_PAINT") != "1")
            {
                IntPtr intPtr;
                SDL.SDL_GetEventFilter(out SDL3_FNAPlatform.prevEventFilter, out intPtr);
                SDL.SDL_SetEventFilter(SDL3_FNAPlatform.win32OnPaint, intPtr);
            }
            return baseDirectory;
        }
References System.array, System.IO.Path.Combine(), System.IO.File.Exists(), Microsoft.Xna.Framework.SDL3_FNAPlatform.GetBaseDirectory(), Microsoft.Xna.Framework.SDL3_FNAPlatform.INTERNAL_AddInstance(), Microsoft.Xna.Framework.FNALoggerEXT.LogError, Microsoft.Xna.Framework.SDL3_FNAPlatform.OSVersion, Microsoft.Xna.Framework.SDL3_FNAPlatform.prevEventFilter, SDL3.SDL.SDL_GetCurrentVideoDriver(), SDL3.SDL.SDL_GetError(), SDL3.SDL.SDL_GetEventFilter(), SDL3.SDL.SDL_GetHint(), SDL3.SDL.SDL_GetPlatform(), SDL3.SDL.SDL_Init(), SDL3.SDL.SDL_PeepEvents(), SDL3.SDL.SDL_PumpEvents(), SDL3.SDL.SDL_SetEventFilter(), SDL3.SDL.SDL_SetHint(), SDL3.SDL.SDL_SetHintWithPriority(), SDL3.SDL.SDL_SetMainReady(), System.IntPtr.Size, Microsoft.Xna.Framework.SDL3_FNAPlatform.SupportsGlobalMouse, System.text, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), Microsoft.Xna.Framework.Input.U, and Microsoft.Xna.Framework.SDL3_FNAPlatform.win32OnPaint.
Referenced by Microsoft.Xna.Framework.FNAPlatform.FNAPlatform().