Terraria Decompiled: Microsoft.Xna.Framework.SDL3_FNAPlatform.GetMouseState
GetMouseState()
static void Microsoft.Xna.Framework.SDL3_FNAPlatform.GetMouseState (IntPtr window, out int x, out int y, out ButtonState left, out ButtonState middle, out ButtonState right, out ButtonState x1, out ButtonState x2) inline static
Definition at line 807 of file SDL3_FNAPlatform.cs.
        {
            float num;
            float num2;
            SDL.SDL_MouseButtonFlags sdl_MouseButtonFlags;
            if (SDL3_FNAPlatform.GetRelativeMouseMode(window))
            {
                sdl_MouseButtonFlags = SDL.SDL_GetRelativeMouseState(out num, out num2);
            }
            else if (SDL3_FNAPlatform.SupportsGlobalMouse)
            {
                sdl_MouseButtonFlags = SDL.SDL_GetGlobalMouseState(out num, out num2);
                int num3 = 0;
                int num4 = 0;
                SDL.SDL_GetWindowPosition(window, out num3, out num4);
                num -= (float)num3;
                num2 -= (float)num4;
            }
            else
            {
                sdl_MouseButtonFlags = SDL.SDL_GetMouseState(out num, out num2);
            }
            x = (int)num;
            y = (int)num2;
            left = (ButtonState)(sdl_MouseButtonFlags & SDL.SDL_MouseButtonFlags.SDL_BUTTON_LMASK);
            middle = (ButtonState)((sdl_MouseButtonFlags & SDL.SDL_MouseButtonFlags.SDL_BUTTON_MMASK) >> 1);
            right = (ButtonState)((sdl_MouseButtonFlags & SDL.SDL_MouseButtonFlags.SDL_BUTTON_RMASK) >> 2);
            x1 = (ButtonState)((sdl_MouseButtonFlags & SDL.SDL_MouseButtonFlags.SDL_BUTTON_X1MASK) >> 3);
            x2 = (ButtonState)((sdl_MouseButtonFlags & SDL.SDL_MouseButtonFlags.SDL_BUTTON_X2MASK) >> 4);
        }
References Microsoft.Xna.Framework.SDL3_FNAPlatform.GetRelativeMouseMode(), int, SDL3.SDL.SDL_GetGlobalMouseState(), SDL3.SDL.SDL_GetMouseState(), SDL3.SDL.SDL_GetRelativeMouseState(), SDL3.SDL.SDL_GetWindowPosition(), and Microsoft.Xna.Framework.SDL3_FNAPlatform.SupportsGlobalMouse.
Referenced by Microsoft.Xna.Framework.FNAPlatform.FNAPlatform().