Terraria Decompiled: Microsoft.Xna.Framework.SDL3_FNAPlatform.GetStorageRoot
GetStorageRoot()
static string Microsoft.Xna.Framework.SDL3_FNAPlatform.GetStorageRoot () inline static
Definition at line 892 of file SDL3_FNAPlatform.cs.
        {
            string text = Path.GetFileNameWithoutExtension(AppDomain.CurrentDomain.FriendlyName).Replace(".vshost", "");
            if (SDL3_FNAPlatform.OSVersion.Equals("Windows"))
            {
                return Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments), "SavedGames", text);
            }
            if (SDL3_FNAPlatform.OSVersion.Equals("macOS"))
            {
                string environmentVariable = Environment.GetEnvironmentVariable("HOME");
                if (string.IsNullOrEmpty(environmentVariable))
                {
                    return ".";
                }
                return Path.Combine(environmentVariable, "Library/Application Support", text);
            }
            else
            {
                if (SDL3_FNAPlatform.OSVersion.Equals("Linux") || SDL3_FNAPlatform.OSVersion.Equals("FreeBSD") || SDL3_FNAPlatform.OSVersion.Equals("OpenBSD") || SDL3_FNAPlatform.OSVersion.Equals("NetBSD"))
                {
                    string text2 = Environment.GetEnvironmentVariable("XDG_DATA_HOME");
                    if (string.IsNullOrEmpty(text2))
                    {
                        text2 = Environment.GetEnvironmentVariable("HOME");
                        if (string.IsNullOrEmpty(text2))
{
                            return ".";
                        }
                        text2 += "/.local/share";
                    }
                    return Path.Combine(text2, text);
                }
                return SDL.SDL_GetPrefPath(null, text);
            }
        }
References System.IO.Path.Combine(), System.AppDomain.CurrentDomain, System.AppDomain.FriendlyName, System.IO.Path.GetFileNameWithoutExtension(), Microsoft.Xna.Framework.SDL3_FNAPlatform.OSVersion, SDL3.SDL.SDL_GetPrefPath(), and System.text.
Referenced by Microsoft.Xna.Framework.FNAPlatform.FNAPlatform().