Terraria Decompiled: Microsoft.Xna.Framework.SDL3_FNAPlatform.ApplyWindowChanges
ApplyWindowChanges()
static unsafe void Microsoft.Xna.Framework.SDL3_FNAPlatform.ApplyWindowChanges (IntPtr window, int clientWidth, int clientHeight, bool wantsFullscreen, string screenDeviceName, ref string resultDeviceName) inline static
Definition at line 195 of file SDL3_FNAPlatform.cs.
        {
            bool flag = false;
            SDL3_FNAPlatform.ScaleForWindow(window, false, ref clientWidth, ref clientHeight);
            if (!wantsFullscreen)
            {
                bool flag2;
                if ((SDL.SDL_GetWindowFlags(window) & SDL.SDL_WindowFlags.SDL_WINDOW_FULLSCREEN) != (SDL.SDL_WindowFlags)0UL)
                {
                    SDL.SDL_SetWindowFullscreen(window, false);
                    flag2 = true;
                }
                else
                {
                    int num;
                    int num2;
                    SDL.SDL_GetWindowSize(window, out num, out num2);
                    flag2 = clientWidth != num || clientHeight != num2;
                }
                if (flag2)
                {
                    SDL.SDL_RestoreWindow(window);
                    SDL.SDL_SetWindowSize(window, clientWidth, clientHeight);
                    flag = true;
                }
            }
            int num3 = 0;
            for (int i = 0; i < GraphicsAdapter.Adapters.Count; i++)
            {
                if (screenDeviceName == GraphicsAdapter.Adapters[i].DeviceName)
                {
                    num3 = i;
                    break;
                }
            }
            if (resultDeviceName != screenDeviceName)
            {
                SDL.SDL_SetWindowFullscreen(window, false);
                resultDeviceName = screenDeviceName;
                flag = true;
            }
            if (flag)
            {
                int num4 = (int)(805240832U | SDL3_FNAPlatform.displayIds[num3]);
                SDL.SDL_SetWindowPosition(window, num4, num4);
            }
            if (wantsFullscreen)
            {
                if ((SDL.SDL_GetWindowFlags(window) & SDL.SDL_WindowFlags.SDL_WINDOW_HIDDEN) != (SDL.SDL_WindowFlags)0UL)
                {
                    SDL.SDL_DisplayMode* ptr = (SDL.SDL_DisplayMode*)(void*)SDL.SDL_GetCurrentDisplayMode(SDL.SDL_GetDisplayForWindow(window));
                    SDL.SDL_SetWindowSize(window, ptr->w, ptr->h);
                }
                SDL.SDL_SetWindowFullscreen(window, true);
            }
            if (Mouse.WindowHandle == window)
            {
                Rectangle windowBounds = SDL3_FNAPlatform.GetWindowBounds(window);
                Mouse.INTERNAL_WindowWidth = windowBounds.Width;
                Mouse.INTERNAL_WindowHeight = windowBounds.Height;
            }
        }
References Microsoft.Xna.Framework.Graphics.GraphicsAdapter.Adapters, Microsoft.Xna.Framework.SDL3_FNAPlatform.displayIds, Microsoft.Xna.Framework.SDL3_FNAPlatform.GetWindowBounds(), Microsoft.Xna.Framework.Rectangle.Height, int, Microsoft.Xna.Framework.SDL3_FNAPlatform.ScaleForWindow(), SDL3.SDL.SDL_GetCurrentDisplayMode(), SDL3.SDL.SDL_GetDisplayForWindow(), SDL3.SDL.SDL_GetWindowFlags(), SDL3.SDL.SDL_GetWindowSize(), SDL3.SDL.SDL_RestoreWindow(), SDL3.SDL.SDL_SetWindowFullscreen(), SDL3.SDL.SDL_SetWindowPosition(), SDL3.SDL.SDL_SetWindowSize(), Microsoft.Xna.Framework.Input.U, Microsoft.Xna.Framework.Rectangle.Width, and Microsoft.Xna.Framework.Input.Mouse.WindowHandle.
Referenced by Microsoft.Xna.Framework.FNAPlatform.FNAPlatform().