Terraria Decompiled: Microsoft.Xna.Framework.SDL3_FNAPlatform.INTERNAL_AddInstance
INTERNAL_AddInstance()
static void Microsoft.Xna.Framework.SDL3_FNAPlatform.INTERNAL_AddInstance (uint dev) inline static private
Definition at line 1284 of file SDL3_FNAPlatform.cs.
        {
            int num = -1;
            for (int i = 0; i < SDL3_FNAPlatform.INTERNAL_devices.Length; i++)
            {
                if (SDL3_FNAPlatform.INTERNAL_devices[i] == IntPtr.Zero)
                {
                    num = i;
                    break;
                }
            }
            if (num == -1)
            {
                return;
            }
            SDL.SDL_ClearError();
            SDL3_FNAPlatform.INTERNAL_devices[num] = SDL.SDL_OpenGamepad(dev);
            IntPtr intPtr = SDL.SDL_GetGamepadJoystick(SDL3_FNAPlatform.INTERNAL_devices[num]);
            uint num2 = SDL.SDL_GetJoystickID(intPtr);
            if (SDL3_FNAPlatform.INTERNAL_instanceList.ContainsKey(num2))
            {
                SDL3_FNAPlatform.INTERNAL_devices[num] = IntPtr.Zero;
                return;
            }
            SDL3_FNAPlatform.INTERNAL_instanceList.Add(num2, num);
            SDL3_FNAPlatform.INTERNAL_states[num] = default(GamePadState);
            SDL3_FNAPlatform.INTERNAL_states[num].IsConnected = true;
            bool flag = SDL.SDL_RumbleGamepad(SDL3_FNAPlatform.INTERNAL_devices[num], 0, 0, 0U);
            bool flag2 = SDL.SDL_RumbleGamepadTriggers(SDL3_FNAPlatform.INTERNAL_devices[num], 0, 0, 0U);
            uint num3 = SDL.SDL_GetGamepadProperties(SDL3_FNAPlatform.INTERNAL_devices[num]);
            GamePadCapabilities gamePadCapabilities = default(GamePadCapabilities);
            gamePadCapabilities.IsConnected = true;
            gamePadCapabilities.GamePadType = SDL3_FNAPlatform.INTERNAL_gamepadType[(int)SDL.SDL_GetJoystickType(intPtr)];
            gamePadCapabilities.HasAButton = SDL.SDL_GamepadHasButton(SDL3_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GamepadButton.SDL_GAMEPAD_BUTTON_SOUTH);
            gamePadCapabilities.HasBButton = SDL.SDL_GamepadHasButton(SDL3_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GamepadButton.SDL_GAMEPAD_BUTTON_EAST);
            gamePadCapabilities.HasXButton = SDL.SDL_GamepadHasButton(SDL3_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GamepadButton.SDL_GAMEPAD_BUTTON_WEST);
            gamePadCapabilities.HasYButton = SDL.SDL_GamepadHasButton(SDL3_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GamepadButton.SDL_GAMEPAD_BUTTON_NORTH);
            gamePadCapabilities.HasBackButton = SDL.SDL_GamepadHasButton(SDL3_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GamepadButton.SDL_GAMEPAD_BUTTON_BACK);
            gamePadCapabilities.HasBigButton = SDL.SDL_GamepadHasButton(SDL3_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GamepadButton.SDL_GAMEPAD_BUTTON_GUIDE);
            gamePadCapabilities.HasStartButton = SDL.SDL_GamepadHasButton(SDL3_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GamepadButton.SDL_GAMEPAD_BUTTON_START);
            gamePadCapabilities.HasLeftStickButton = SDL.SDL_GamepadHasButton(SDL3_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GamepadButton.SDL_GAMEPAD_BUTTON_LEFT_STICK);
            gamePadCapabilities.HasRightStickButton = SDL.SDL_GamepadHasButton(SDL3_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GamepadButton.SDL_GAMEPAD_BUTTON_RIGHT_STICK);
            gamePadCapabilities.HasLeftShoulderButton = SDL.SDL_GamepadHasButton(SDL3_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GamepadButton.SDL_GAMEPAD_BUTTON_LEFT_SHOULDER);
            gamePadCapabilities.HasRightShoulderButton = SDL.SDL_GamepadHasButton(SDL3_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GamepadButton.SDL_GAMEPAD_BUTTON_RIGHT_SHOULDER);
            gamePadCapabilities.HasDPadUpButton = SDL.SDL_GamepadHasButton(SDL3_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GamepadButton.SDL_GAMEPAD_BUTTON_DPAD_UP);
            gamePadCapabilities.HasDPadDownButton = SDL.SDL_GamepadHasButton(SDL3_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GamepadButton.SDL_GAMEPAD_BUTTON_DPAD_DOWN);
            gamePadCapabilities.HasDPadLeftButton = SDL.SDL_GamepadHasButton(SDL3_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GamepadButton.SDL_GAMEPAD_BUTTON_DPAD_LEFT);
            gamePadCapabilities.HasDPadRightButton = SDL.SDL_GamepadHasButton(SDL3_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GamepadButton.SDL_GAMEPAD_BUTTON_DPAD_RIGHT);
            gamePadCapabilities.HasLeftXThumbStick = SDL.SDL_GamepadHasAxis(SDL3_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GamepadAxis.SDL_GAMEPAD_AXIS_LEFTX);
            gamePadCapabilities.HasLeftYThumbStick = SDL.SDL_GamepadHasAxis(SDL3_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GamepadAxis.SDL_GAMEPAD_AXIS_LEFTY);
            gamePadCapabilities.HasRightXThumbStick = SDL.SDL_GamepadHasAxis(SDL3_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GamepadAxis.SDL_GAMEPAD_AXIS_RIGHTX);
            gamePadCapabilities.HasRightYThumbStick = SDL.SDL_GamepadHasAxis(SDL3_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GamepadAxis.SDL_GAMEPAD_AXIS_RIGHTY);
            gamePadCapabilities.HasLeftTrigger = SDL.SDL_GamepadHasAxis(SDL3_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GamepadAxis.SDL_GAMEPAD_AXIS_LEFT_TRIGGER);
            gamePadCapabilities.HasRightTrigger = SDL.SDL_GamepadHasAxis(SDL3_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GamepadAxis.SDL_GAMEPAD_AXIS_RIGHT_TRIGGER);
            gamePadCapabilities.HasLeftVibrationMotor = flag;
            gamePadCapabilities.HasRightVibrationMotor = flag;
            gamePadCapabilities.HasVoiceSupport = false;
            gamePadCapabilities.HasLightBarEXT = SDL.SDL_GetBooleanProperty(num3, "SDL.joystick.cap.rgb_led", false);
            gamePadCapabilities.HasTriggerVibrationMotorsEXT = flag2;
            gamePadCapabilities.HasMisc1EXT = SDL.SDL_GamepadHasButton(SDL3_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GamepadButton.SDL_GAMEPAD_BUTTON_MISC1);
            gamePadCapabilities.HasPaddle1EXT = SDL.SDL_GamepadHasButton(SDL3_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GamepadButton.SDL_GAMEPAD_BUTTON_RIGHT_PADDLE1);
            gamePadCapabilities.HasPaddle2EXT = SDL.SDL_GamepadHasButton(SDL3_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GamepadButton.SDL_GAMEPAD_BUTTON_LEFT_PADDLE1);
            gamePadCapabilities.HasPaddle3EXT = SDL.SDL_GamepadHasButton(SDL3_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GamepadButton.SDL_GAMEPAD_BUTTON_RIGHT_PADDLE2);
            gamePadCapabilities.HasPaddle4EXT = SDL.SDL_GamepadHasButton(SDL3_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GamepadButton.SDL_GAMEPAD_BUTTON_LEFT_PADDLE2);
            gamePadCapabilities.HasTouchPadEXT = SDL.SDL_GetNumGamepadTouchpads(SDL3_FNAPlatform.INTERNAL_devices[num]) > 0;
            gamePadCapabilities.HasGyroEXT = SDL.SDL_GamepadHasSensor(SDL3_FNAPlatform.INTERNAL_devices[num], SDL.SDL_SensorType.SDL_SENSOR_GYRO);
            gamePadCapabilities.HasAccelerometerEXT = SDL.SDL_GamepadHasSensor(SDL3_FNAPlatform.INTERNAL_devices[num], SDL.SDL_SensorType.SDL_SENSOR_ACCEL);
            SDL3_FNAPlatform.INTERNAL_capabilities[num] = gamePadCapabilities;
            ushort num4 = SDL.SDL_GetJoystickVendor(intPtr);
            ushort num5 = SDL.SDL_GetJoystickProduct(intPtr);
            if (num4 == 0 && num5 == 0)
            {
                SDL3_FNAPlatform.INTERNAL_guids[num] = "xinput";
            }
            else
            {
                SDL3_FNAPlatform.INTERNAL_guids[num] = string.Format("{0:x2}{1:x2}{2:x2}{3:x2}", new object[]
                {
                    (int)(num4 & 255),
                    num4 >> 8,
                    (int)(num5 & 255),
                    num5 >> 8
                });
            }
            if (num4 == 10462)
            {
                SDL.SDL_GamepadType sdl_GamepadType = SDL.SDL_GetGamepadType(SDL3_FNAPlatform.INTERNAL_devices[num]);
                if (sdl_GamepadType == SDL.SDL_GamepadType.SDL_GAMEPAD_TYPE_XBOX360 || sdl_GamepadType == SDL.SDL_GamepadType.SDL_GAMEPAD_TYPE_XBOXONE)
                {
                    SDL3_FNAPlatform.INTERNAL_guids[num] = "xinput";
                }
                else if (sdl_GamepadType == SDL.SDL_GamepadType.SDL_GAMEPAD_TYPE_PS4)
                {
                    SDL3_FNAPlatform.INTERNAL_guids[num] = "4c05c405";
                }
                else if (sdl_GamepadType == SDL.SDL_GamepadType.SDL_GAMEPAD_TYPE_PS5)
                {
                    SDL3_FNAPlatform.INTERNAL_guids[num] = "4c05e60c";
                }
            }
            string text = SDL.SDL_GetGamepadMapping(SDL3_FNAPlatform.INTERNAL_devices[num]);
            string text2;
            if (string.IsNullOrEmpty(text))
            {
                text2 = "Mapping not found";
            }
            else
            {
                text2 = "Mapping: " + text;
            }
            FNALoggerEXT.LogInfo(string.Concat(new string[]
            {
                "Controller ",
                num.ToString(),
                ": ",
                SDL.SDL_GetGamepadName(SDL3_FNAPlatform.INTERNAL_devices[num]),
                ", GUID: ",
                SDL3_FNAPlatform.INTERNAL_guids[num],
                ", ",
                text2
            }));
        }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), int, Microsoft.Xna.Framework.SDL3_FNAPlatform.INTERNAL_capabilities, Microsoft.Xna.Framework.SDL3_FNAPlatform.INTERNAL_devices, Microsoft.Xna.Framework.SDL3_FNAPlatform.INTERNAL_gamepadType, Microsoft.Xna.Framework.SDL3_FNAPlatform.INTERNAL_guids, Microsoft.Xna.Framework.SDL3_FNAPlatform.INTERNAL_instanceList, Microsoft.Xna.Framework.SDL3_FNAPlatform.INTERNAL_states, Microsoft.Xna.Framework.Input.GamePadState.IsConnected, Microsoft.Xna.Framework.FNALoggerEXT.LogInfo, SDL3.SDL.SDL_ClearError(), SDL3.SDL.SDL_GamepadHasAxis(), SDL3.SDL.SDL_GamepadHasButton(), SDL3.SDL.SDL_GamepadHasSensor(), SDL3.SDL.SDL_GetBooleanProperty(), SDL3.SDL.SDL_GetGamepadJoystick(), SDL3.SDL.SDL_GetGamepadMapping(), SDL3.SDL.SDL_GetGamepadName(), SDL3.SDL.SDL_GetGamepadProperties(), SDL3.SDL.SDL_GetGamepadType(), SDL3.SDL.SDL_GetJoystickID(), SDL3.SDL.SDL_GetJoystickProduct(), SDL3.SDL.SDL_GetJoystickType(), SDL3.SDL.SDL_GetJoystickVendor(), SDL3.SDL.SDL_GetNumGamepadTouchpads(), SDL3.SDL.SDL_OpenGamepad(), SDL3.SDL.SDL_RumbleGamepad(), SDL3.SDL.SDL_RumbleGamepadTriggers(), System.text, Microsoft.Xna.Framework.Input.U, and System.IntPtr.Zero.
Referenced by Microsoft.Xna.Framework.SDL3_FNAPlatform.PollEvents(), and Microsoft.Xna.Framework.SDL3_FNAPlatform.ProgramInit().