Terraria Decompiled: Microsoft.Xna.Framework.SDL3_FNAPlatform.INTERNAL_SetIcon
INTERNAL_SetIcon()
static void Microsoft.Xna.Framework.SDL3_FNAPlatform.INTERNAL_SetIcon (IntPtr window, string title) inline static private
Definition at line 337 of file SDL3_FNAPlatform.cs.
        {
            string text = string.Empty;
            try
            {
                text = SDL3_FNAPlatform.INTERNAL_GetIconName(title + ".png");
                if (!string.IsNullOrEmpty(text))
                {
                    IntPtr intPtr;
                    IntPtr intPtr2;
                    using (Stream stream = TitleContainer.OpenStream(text))
                    {
                        int num;
                        int num2;
                        int num3;
                        intPtr = FNA3D.ReadImageStream(stream, out num, out num2, out num3, -1, -1, false);
                        intPtr2 = SDL.SDL_CreateSurfaceFrom(num, num2, SDL.SDL_PixelFormat.SDL_PIXELFORMAT_ABGR8888, intPtr, num * 4);
                    }
                    SDL.SDL_SetWindowIcon(window, intPtr2);
                    SDL.SDL_DestroySurface(intPtr2);
                    FNA3D.FNA3D_Image_Free(intPtr);
                    return;
                }
            }
            catch (DllNotFoundException)
            {
            }
            text = SDL3_FNAPlatform.INTERNAL_GetIconName(title + ".bmp");
            if (!string.IsNullOrEmpty(text))
            {
                IntPtr intPtr3 = SDL.SDL_LoadBMP(text);
                SDL.SDL_SetWindowIcon(window, intPtr3);
                SDL.SDL_DestroySurface(intPtr3);
            }
        }
References Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_Image_Free(), Microsoft.Xna.Framework.SDL3_FNAPlatform.INTERNAL_GetIconName(), Microsoft.Xna.Framework.TitleContainer.OpenStream(), Microsoft.Xna.Framework.Graphics.FNA3D.ReadImageStream(), SDL3.SDL.SDL_CreateSurfaceFrom(), SDL3.SDL.SDL_DestroySurface(), SDL3.SDL.SDL_LoadBMP(), SDL3.SDL.SDL_SetWindowIcon(), and System.text.
Referenced by Microsoft.Xna.Framework.SDL3_FNAPlatform.CreateWindow().