Terraria Decompiled: Microsoft.Xna.Framework.SDL3_FNAPlatform.GetWindowBounds
GetWindowBounds()
static unsafe Rectangle Microsoft.Xna.Framework.SDL3_FNAPlatform.GetWindowBounds (IntPtr window) inline static
Definition at line 281 of file SDL3_FNAPlatform.cs.
        {
            Rectangle rectangle;
            if ((SDL.SDL_GetWindowFlags(window) & SDL.SDL_WindowFlags.SDL_WINDOW_FULLSCREEN) != (SDL.SDL_WindowFlags)0UL)
            {
                SDL.SDL_DisplayMode* ptr = (SDL.SDL_DisplayMode*)(void*)SDL.SDL_GetCurrentDisplayMode(SDL.SDL_GetDisplayForWindow(window));
                rectangle.X = 0;
                rectangle.Y = 0;
                rectangle.Width = ptr->w;
                rectangle.Height = ptr->h;
            }
            else
            {
                SDL.SDL_GetWindowPosition(window, out rectangle.X, out rectangle.Y);
                SDL.SDL_GetWindowSize(window, out rectangle.Width, out rectangle.Height);
            }
            return rectangle;
        }
References Microsoft.Xna.Framework.Rectangle.Height, SDL3.SDL.SDL_GetCurrentDisplayMode(), SDL3.SDL.SDL_GetDisplayForWindow(), SDL3.SDL.SDL_GetWindowFlags(), SDL3.SDL.SDL_GetWindowPosition(), SDL3.SDL.SDL_GetWindowSize(), Microsoft.Xna.Framework.Rectangle.Width, Microsoft.Xna.Framework.Rectangle.X, and Microsoft.Xna.Framework.Rectangle.Y.
Referenced by Microsoft.Xna.Framework.SDL3_FNAPlatform.ApplyWindowChanges(), Microsoft.Xna.Framework.FNAPlatform.FNAPlatform(), and Microsoft.Xna.Framework.SDL3_FNAPlatform.PollEvents().