Terraria Decompiled: Microsoft.Xna.Framework.SDL3_FNAPlatform.GetGamePadState
GetGamePadState()
static GamePadState Microsoft.Xna.Framework.SDL3_FNAPlatform.GetGamePadState (int index, GamePadDeadZone deadZoneMode) inline static
Definition at line 1085 of file SDL3_FNAPlatform.cs.
        {
            IntPtr intPtr = SDL3_FNAPlatform.INTERNAL_devices[index];
            if (intPtr == IntPtr.Zero)
            {
                return default(GamePadState);
            }
            Vector2 vector = new Vector2((float)SDL.SDL_GetGamepadAxis(intPtr, SDL.SDL_GamepadAxis.SDL_GAMEPAD_AXIS_LEFTX) / 32767f, (float)SDL.SDL_GetGamepadAxis(intPtr, SDL.SDL_GamepadAxis.SDL_GAMEPAD_AXIS_LEFTY) / -32767f);
            Vector2 vector2 = new Vector2((float)SDL.SDL_GetGamepadAxis(intPtr, SDL.SDL_GamepadAxis.SDL_GAMEPAD_AXIS_RIGHTX) / 32767f, (float)SDL.SDL_GetGamepadAxis(intPtr, SDL.SDL_GamepadAxis.SDL_GAMEPAD_AXIS_RIGHTY) / -32767f);
            float num = (float)SDL.SDL_GetGamepadAxis(intPtr, SDL.SDL_GamepadAxis.SDL_GAMEPAD_AXIS_LEFT_TRIGGER) / 32767f;
            float num2 = (float)SDL.SDL_GetGamepadAxis(intPtr, SDL.SDL_GamepadAxis.SDL_GAMEPAD_AXIS_RIGHT_TRIGGER) / 32767f;
            Buttons buttons = (Buttons)0;
            if (SDL.SDL_GetGamepadButton(intPtr, SDL.SDL_GamepadButton.SDL_GAMEPAD_BUTTON_SOUTH))
            {
                buttons |= Buttons.A;
            }
            if (SDL.SDL_GetGamepadButton(intPtr, SDL.SDL_GamepadButton.SDL_GAMEPAD_BUTTON_EAST))
            {
                buttons |= Buttons.B;
            }
            if (SDL.SDL_GetGamepadButton(intPtr, SDL.SDL_GamepadButton.SDL_GAMEPAD_BUTTON_WEST))
            {
                buttons |= Buttons.X;
            }
            if (SDL.SDL_GetGamepadButton(intPtr, SDL.SDL_GamepadButton.SDL_GAMEPAD_BUTTON_NORTH))
            {
                buttons |= Buttons.Y;
            }
            if (SDL.SDL_GetGamepadButton(intPtr, SDL.SDL_GamepadButton.SDL_GAMEPAD_BUTTON_BACK))
            {
                buttons |= Buttons.Back;
            }
            if (SDL.SDL_GetGamepadButton(intPtr, SDL.SDL_GamepadButton.SDL_GAMEPAD_BUTTON_GUIDE))
            {
                buttons |= Buttons.BigButton;
            }
            if (SDL.SDL_GetGamepadButton(intPtr, SDL.SDL_GamepadButton.SDL_GAMEPAD_BUTTON_START))
            {
                buttons |= Buttons.Start;
            }
            if (SDL.SDL_GetGamepadButton(intPtr, SDL.SDL_GamepadButton.SDL_GAMEPAD_BUTTON_LEFT_STICK))
            {
                buttons |= Buttons.LeftStick;
            }
            if (SDL.SDL_GetGamepadButton(intPtr, SDL.SDL_GamepadButton.SDL_GAMEPAD_BUTTON_RIGHT_STICK))
            {
                buttons |= Buttons.RightStick;
            }
            if (SDL.SDL_GetGamepadButton(intPtr, SDL.SDL_GamepadButton.SDL_GAMEPAD_BUTTON_LEFT_SHOULDER))
            {
                buttons |= Buttons.LeftShoulder;
            }
            if (SDL.SDL_GetGamepadButton(intPtr, SDL.SDL_GamepadButton.SDL_GAMEPAD_BUTTON_RIGHT_SHOULDER))
            {
                buttons |= Buttons.RightShoulder;
            }
            ButtonState buttonState = ButtonState.Released;
            ButtonState buttonState2 = ButtonState.Released;
            ButtonState buttonState3 = ButtonState.Released;
            ButtonState buttonState4 = ButtonState.Released;
            if (SDL.SDL_GetGamepadButton(intPtr, SDL.SDL_GamepadButton.SDL_GAMEPAD_BUTTON_DPAD_UP))
            {
                buttons |= Buttons.DPadUp;
                buttonState = ButtonState.Pressed;
            }
            if (SDL.SDL_GetGamepadButton(intPtr, SDL.SDL_GamepadButton.SDL_GAMEPAD_BUTTON_DPAD_DOWN))
            {
                buttons |= Buttons.DPadDown;
                buttonState2 = ButtonState.Pressed;
            }
            if (SDL.SDL_GetGamepadButton(intPtr, SDL.SDL_GamepadButton.SDL_GAMEPAD_BUTTON_DPAD_LEFT))
            {
                buttons |= Buttons.DPadLeft;
                buttonState3 = ButtonState.Pressed;
            }
            if (SDL.SDL_GetGamepadButton(intPtr, SDL.SDL_GamepadButton.SDL_GAMEPAD_BUTTON_DPAD_RIGHT))
            {
                buttons |= Buttons.DPadRight;
                buttonState4 = ButtonState.Pressed;
            }
            if (SDL.SDL_GetGamepadButton(intPtr, SDL.SDL_GamepadButton.SDL_GAMEPAD_BUTTON_MISC1))
            {
                buttons |= Buttons.Misc1EXT;
            }
            if (SDL.SDL_GetGamepadButton(intPtr, SDL.SDL_GamepadButton.SDL_GAMEPAD_BUTTON_RIGHT_PADDLE1))
            {
                buttons |= Buttons.Paddle1EXT;
            }
            if (SDL.SDL_GetGamepadButton(intPtr, SDL.SDL_GamepadButton.SDL_GAMEPAD_BUTTON_LEFT_PADDLE1))
            {
                buttons |= Buttons.Paddle2EXT;
            }
            if (SDL.SDL_GetGamepadButton(intPtr, SDL.SDL_GamepadButton.SDL_GAMEPAD_BUTTON_RIGHT_PADDLE2))
            {
                buttons |= Buttons.Paddle3EXT;
            }
            if (SDL.SDL_GetGamepadButton(intPtr, SDL.SDL_GamepadButton.SDL_GAMEPAD_BUTTON_LEFT_PADDLE2))
            {
                buttons |= Buttons.Paddle4EXT;
            }
            if (SDL.SDL_GetGamepadButton(intPtr, SDL.SDL_GamepadButton.SDL_GAMEPAD_BUTTON_TOUCHPAD))
            {
                buttons |= Buttons.TouchPadEXT;
            }
            GamePadState gamePadState = new GamePadState(new GamePadThumbSticks(vector, vector2, deadZoneMode), new GamePadTriggers(num, num2, deadZoneMode), new GamePadButtons(buttons), new GamePadDPad(buttonState, buttonState2, buttonState3, buttonState4))
            {
                IsConnected = true,
                PacketNumber = SDL3_FNAPlatform.INTERNAL_states[index].PacketNumber
            };
            if (gamePadState != SDL3_FNAPlatform.INTERNAL_states[index])
            {
                gamePadState.PacketNumber++;
                SDL3_FNAPlatform.INTERNAL_states[index] = gamePadState;
            }
            return gamePadState;
        }
References System.index, Microsoft.Xna.Framework.SDL3_FNAPlatform.INTERNAL_devices, Microsoft.Xna.Framework.SDL3_FNAPlatform.INTERNAL_states, Microsoft.Xna.Framework.Input.GamePadState.PacketNumber, SDL3.SDL.SDL_GetGamepadAxis(), SDL3.SDL.SDL_GetGamepadButton(), Microsoft.Xna.Framework.Graphics.Vector2, and System.IntPtr.Zero.
Referenced by Microsoft.Xna.Framework.FNAPlatform.FNAPlatform().