Terraria Decompiled: Microsoft.Xna.Framework.SDL3_FNAPlatform.CreateWindow
CreateWindow()
static GameWindow Microsoft.Xna.Framework.SDL3_FNAPlatform.CreateWindow () inline static
Definition at line 137 of file SDL3_FNAPlatform.cs.
        {
            SDL.SDL_WindowFlags sdl_WindowFlags = SDL.SDL_WindowFlags.SDL_WINDOW_HIDDEN | SDL.SDL_WindowFlags.SDL_WINDOW_INPUT_FOCUS | SDL.SDL_WindowFlags.SDL_WINDOW_MOUSE_FOCUS | (SDL.SDL_WindowFlags)FNA3D.FNA3D_PrepareWindowAttributes();
            if ((sdl_WindowFlags & SDL.SDL_WindowFlags.SDL_WINDOW_VULKAN) == SDL.SDL_WindowFlags.SDL_WINDOW_VULKAN && SDL.SDL_GetHint("FNA3D_VULKAN_PIPELINE_CACHE_FILE_NAME") == null)
            {
                string text2;
                if (SDL3_FNAPlatform.OSVersion.Equals("Windows") || SDL3_FNAPlatform.OSVersion.Equals("macOS") || SDL3_FNAPlatform.OSVersion.Equals("Linux") || SDL3_FNAPlatform.OSVersion.Equals("FreeBSD") || SDL3_FNAPlatform.OSVersion.Equals("OpenBSD") || SDL3_FNAPlatform.OSVersion.Equals("NetBSD"))
                {
                    string text = Path.GetFileNameWithoutExtension(AppDomain.CurrentDomain.FriendlyName).Replace(".vshost", "");
                    text2 = Path.Combine(SDL.SDL_GetPrefPath(null, "FNA3D"), text + "_Vulkan_PipelineCache.blob");
                }
                else
                {
                    text2 = string.Empty;
                }
                SDL.SDL_SetHint("FNA3D_VULKAN_PIPELINE_CACHE_FILE_NAME", text2);
            }
            if (Environment.GetEnvironmentVariable("FNA_GRAPHICS_ENABLE_HIGHDPI") == "1")
            {
                sdl_WindowFlags |= SDL.SDL_WindowFlags.SDL_WINDOW_HIGH_PIXEL_DENSITY;
            }
            string defaultWindowTitle = AssemblyHelper.GetDefaultWindowTitle();
            IntPtr intPtr = SDL.SDL_CreateWindow(defaultWindowTitle, GraphicsDeviceManager.DefaultBackBufferWidth, GraphicsDeviceManager.DefaultBackBufferHeight, sdl_WindowFlags);
            if (intPtr == IntPtr.Zero)
            {
                throw new NoSuitableGraphicsDeviceException(SDL.SDL_GetError());
            }
            SDL3_FNAPlatform.INTERNAL_SetIcon(intPtr, defaultWindowTitle);
            SDL.SDL_DisableScreenSaver();
            SDL3_FNAPlatform.OnIsMouseVisibleChanged(false);
            sdl_WindowFlags = SDL.SDL_GetWindowFlags(intPtr);
            if ((sdl_WindowFlags & SDL.SDL_WindowFlags.SDL_WINDOW_HIGH_PIXEL_DENSITY) == (SDL.SDL_WindowFlags)0UL)
            {
                Environment.SetEnvironmentVariable("FNA_GRAPHICS_ENABLE_HIGHDPI", "0");
            }
            return new FNAWindow(intPtr, "\\\\.\\DISPLAY" + SDL.SDL_GetDisplayForWindow(intPtr).ToString());
        }
References System.IO.Path.Combine(), System.AppDomain.CurrentDomain, Microsoft.Xna.Framework.GraphicsDeviceManager.DefaultBackBufferHeight, Microsoft.Xna.Framework.GraphicsDeviceManager.DefaultBackBufferWidth, Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_PrepareWindowAttributes(), System.AppDomain.FriendlyName, MonoGame.Utilities.AssemblyHelper.GetDefaultWindowTitle(), System.IO.Path.GetFileNameWithoutExtension(), Microsoft.Xna.Framework.SDL3_FNAPlatform.INTERNAL_SetIcon(), Microsoft.Xna.Framework.SDL3_FNAPlatform.OnIsMouseVisibleChanged(), Microsoft.Xna.Framework.SDL3_FNAPlatform.OSVersion, SDL3.SDL.SDL_CreateWindow(), SDL3.SDL.SDL_DisableScreenSaver(), SDL3.SDL.SDL_GetDisplayForWindow(), SDL3.SDL.SDL_GetError(), SDL3.SDL.SDL_GetHint(), SDL3.SDL.SDL_GetPrefPath(), SDL3.SDL.SDL_GetWindowFlags(), SDL3.SDL.SDL_SetHint(), System.text, and System.IntPtr.Zero.
Referenced by Microsoft.Xna.Framework.FNAPlatform.FNAPlatform().