Terraria Decompiled: Microsoft.Xna.Framework.SDL3_FNAPlatform.PollEvents
PollEvents()
static unsafe void Microsoft.Xna.Framework.SDL3_FNAPlatform.PollEvents (Game game, ref GraphicsAdapter currentAdapter, bool[] textInputControlDown, ref bool textInputSuppress) inline static
Definition at line 476 of file SDL3_FNAPlatform.cs.
        {
            char* ptr = stackalloc char[(UIntPtr)64];
            SDL.SDL_Event sdl_Event;
            while (SDL.SDL_PollEvent(out sdl_Event))
            {
                if (sdl_Event.type == 768U)
                {
                    Keys keys = SDL3_FNAPlatform.ToXNAKey(ref sdl_Event.key.key, ref sdl_Event.key.scancode);
                    if (!Keyboard.keys.Contains(keys))
                    {
                        Keyboard.keys.Add(keys);
                        int num;
                        if (FNAPlatform.TextInputBindings.TryGetValue(keys, out num))
{
                            textInputControlDown[num] = true;
                            TextInputEXT.OnTextInput(FNAPlatform.TextInputCharacters[num]);
                        }
                        else if ((Keyboard.keys.Contains(Keys.LeftControl) || Keyboard.keys.Contains(Keys.RightControl)) && keys == Keys.V)
{
                            textInputControlDown[6] = true;
                            TextInputEXT.OnTextInput(FNAPlatform.TextInputCharacters[6]);
                            textInputSuppress = true;
                        }
                    }
                    else if (sdl_Event.key.repeat)
                    {
                        int num2;
                        if (FNAPlatform.TextInputBindings.TryGetValue(keys, out num2))
{
                            TextInputEXT.OnTextInput(FNAPlatform.TextInputCharacters[num2]);
                        }
                        else if ((Keyboard.keys.Contains(Keys.LeftControl) || Keyboard.keys.Contains(Keys.RightControl)) && keys == Keys.V)
{
                            TextInputEXT.OnTextInput(FNAPlatform.TextInputCharacters[6]);
                        }
                    }
                }
                else if (sdl_Event.type == 769U)
                {
                    Keys keys2 = SDL3_FNAPlatform.ToXNAKey(ref sdl_Event.key.key, ref sdl_Event.key.scancode);
                    if (Keyboard.keys.Remove(keys2))
                    {
                        int num3;
                        if (FNAPlatform.TextInputBindings.TryGetValue(keys2, out num3))
{
                            textInputControlDown[num3] = false;
                        }
                        else if ((!Keyboard.keys.Contains(Keys.LeftControl) && !Keyboard.keys.Contains(Keys.RightControl) && textInputControlDown[6]) || keys2 == Keys.V)
{
                            textInputControlDown[6] = false;
                            textInputSuppress = false;
                        }
                    }
                }
                else if (sdl_Event.type == 1025U)
                {
                    Mouse.INTERNAL_onClicked((int)(sdl_Event.button.button - 1));
                }
                else if (sdl_Event.type == 1027U)
                {
                    Mouse.INTERNAL_MouseWheel += (int)sdl_Event.wheel.y * 120;
                }
                else if (sdl_Event.type == 1792U)
                {
                    TouchPanel.TouchDeviceExists = true;
                    TouchPanel.INTERNAL_onTouchEvent((int)sdl_Event.tfinger.fingerID, TouchLocationState.Pressed, sdl_Event.tfinger.x, sdl_Event.tfinger.y, 0f, 0f);
                }
                else if (sdl_Event.type == 1794U)
                {
                    TouchPanel.INTERNAL_onTouchEvent((int)sdl_Event.tfinger.fingerID, TouchLocationState.Moved, sdl_Event.tfinger.x, sdl_Event.tfinger.y, sdl_Event.tfinger.dx, sdl_Event.tfinger.dy);
                }
                else if (sdl_Event.type == 1793U || sdl_Event.type == 1795U)
                {
                    TouchPanel.INTERNAL_onTouchEvent((int)sdl_Event.tfinger.fingerID, TouchLocationState.Released, sdl_Event.tfinger.x, sdl_Event.tfinger.y, 0f, 0f);
                }
                else if (sdl_Event.type >= 514U && sdl_Event.type <= 538U)
                {
                    if (sdl_Event.type == 526U)
                    {
                        game.IsActive = true;
                        if (SDL.SDL_GetCurrentVideoDriver() == "x11")
{
                            SDL.SDL_SetWindowFullscreen(game.Window.Handle, game.GraphicsDevice.PresentationParameters.IsFullScreen);
                        }
                        SDL.SDL_DisableScreenSaver();
                    }
                    else if (sdl_Event.type == 527U)
                    {
                        game.IsActive = false;
                        if (SDL.SDL_GetCurrentVideoDriver() == "x11")
{
                            SDL.SDL_SetWindowFullscreen(game.Window.Handle, false);
                        }
                        SDL.SDL_EnableScreenSaver();
                    }
                    else if (sdl_Event.type == 519U)
                    {
                        Rectangle windowBounds = SDL3_FNAPlatform.GetWindowBounds(Mouse.WindowHandle);
                        Mouse.INTERNAL_WindowWidth = windowBounds.Width;
                        Mouse.INTERNAL_WindowHeight = windowBounds.Height;
                    }
                    else if (sdl_Event.type == 518U)
                    {
                        SDL.SDL_WindowFlags sdl_WindowFlags = SDL.SDL_GetWindowFlags(game.Window.Handle);
                        if ((sdl_WindowFlags & SDL.SDL_WindowFlags.SDL_WINDOW_RESIZABLE) != (SDL.SDL_WindowFlags)0UL && (sdl_WindowFlags & (SDL.SDL_WindowFlags.SDL_WINDOW_INPUT_FOCUS | SDL.SDL_WindowFlags.SDL_WINDOW_MOUSE_FOCUS)) != (SDL.SDL_WindowFlags)0UL)
{
                            ((FNAWindow)game.Window).INTERNAL_ClientSizeChanged();
                        }
                    }
                    else if (sdl_Event.type == 516U)
                    {
                        game.RedrawWindow();
                    }
                    else if (sdl_Event.type == 517U)
                    {
                        GraphicsAdapter graphicsAdapter = SDL3_FNAPlatform.FetchDisplayAdapter(game.Window.Handle, true);
                        if (graphicsAdapter != currentAdapter)
{
                            currentAdapter = graphicsAdapter;
                            game.GraphicsDevice.Reset(game.GraphicsDevice.PresentationParameters, currentAdapter);
                        }
                    }
                    else if (sdl_Event.type == 524U)
                    {
                        SDL.SDL_DisableScreenSaver();
                    }
                    else if (sdl_Event.type == 525U)
                    {
                        SDL.SDL_EnableScreenSaver();
                    }
                    else if (sdl_Event.type == 535U)
                    {
                        object service = game.Services.GetService(typeof(IGraphicsDeviceManager));
                        if (service != null && service is GraphicsDeviceManager)
{
                            ((GraphicsDeviceManager)service).IsFullScreen = true;
                        }
                    }
                    else if (sdl_Event.type == 536U)
                    {
                        object service2 = game.Services.GetService(typeof(IGraphicsDeviceManager));
                        if (service2 != null && service2 is GraphicsDeviceManager)
{
                            ((GraphicsDeviceManager)service2).IsFullScreen = false;
                        }
                    }
                }
                else if (sdl_Event.type >= 337U && sdl_Event.type <= 344U)
                {
                    GraphicsAdapter.AdaptersChanged();
                    currentAdapter = SDL3_FNAPlatform.FetchDisplayAdapter(game.Window.Handle, true);
                    if (sdl_Event.type == 337U)
                    {
                        if (SDL3_FNAPlatform.SupportsOrientationChanges())
{
                            SDL3_FNAPlatform.INTERNAL_HandleOrientationChange(SDL3_FNAPlatform.INTERNAL_ConvertOrientation((SDL.SDL_DisplayOrientation)sdl_Event.display.data1), game.GraphicsDevice, currentAdapter, (FNAWindow)game.Window);
                        }
                    }
                    else
                    {
                        game.GraphicsDevice.QuietlyUpdateAdapter(currentAdapter);
                    }
                }
                else if (sdl_Event.type == 1619U)
                {
                    SDL3_FNAPlatform.INTERNAL_AddInstance(sdl_Event.gdevice.which);
                }
                else if (sdl_Event.type == 1620U)
                {
                    SDL3_FNAPlatform.INTERNAL_RemoveInstance(sdl_Event.gdevice.which);
                }
                else if (sdl_Event.type == 771U && !textInputSuppress)
                {
                    int num4 = SDL3_FNAPlatform.MeasureStringLength(sdl_Event.text.text);
                    if (num4 > 0)
                    {
                        int chars = Encoding.UTF8.GetChars(sdl_Event.text.text, num4, ptr, num4);
                        for (int i = 0; i < chars; i++)
{
                            TextInputEXT.OnTextInput(ptr[i]);
                        }
                    }
                }
                else if (sdl_Event.type == 770U)
                {
                    int num5 = SDL3_FNAPlatform.MeasureStringLength(sdl_Event.edit.text);
                    if (num5 > 0)
                    {
                        int chars2 = Encoding.UTF8.GetChars(sdl_Event.edit.text, num5, ptr, num5);
                        TextInputEXT.OnTextEditing(new string(ptr, 0, chars2), sdl_Event.edit.start, sdl_Event.edit.length);
                    }
                    else
                    {
                        TextInputEXT.OnTextEditing(null, 0, 0);
                    }
                }
                else if (sdl_Event.type == 256U)
                {
                    game.RunApplication = false;
                    return;
                }
            }
        }
References Microsoft.Xna.Framework.Graphics.GraphicsAdapter.AdaptersChanged(), System.Collections.Generic.List< T >.Add(), System.Collections.Generic.List< T >.Contains(), Microsoft.Xna.Framework.SDL3_FNAPlatform.FetchDisplayAdapter(), System.Text.Encoding.GetChars(), Microsoft.Xna.Framework.GameServiceContainer.GetService(), Microsoft.Xna.Framework.SDL3_FNAPlatform.GetWindowBounds(), Microsoft.Xna.Framework.Game.GraphicsDevice, Microsoft.Xna.Framework.GameWindow.Handle, Microsoft.Xna.Framework.Rectangle.Height, int, Microsoft.Xna.Framework.SDL3_FNAPlatform.INTERNAL_AddInstance(), Microsoft.Xna.Framework.SDL3_FNAPlatform.INTERNAL_ConvertOrientation(), Microsoft.Xna.Framework.SDL3_FNAPlatform.INTERNAL_HandleOrientationChange(), Microsoft.Xna.Framework.Input.Mouse.INTERNAL_onClicked(), Microsoft.Xna.Framework.Input.Touch.TouchPanel.INTERNAL_onTouchEvent(), Microsoft.Xna.Framework.SDL3_FNAPlatform.INTERNAL_RemoveInstance(), Microsoft.Xna.Framework.Graphics.PresentationParameters.IsFullScreen, Microsoft.Xna.Framework.Input.Keyboard.keys, Microsoft.Xna.Framework.SDL3_FNAPlatform.MeasureStringLength(), Microsoft.Xna.Framework.Input.TextInputEXT.OnTextEditing(), Microsoft.Xna.Framework.Input.TextInputEXT.OnTextInput(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.PresentationParameters, Microsoft.Xna.Framework.Graphics.GraphicsDevice.QuietlyUpdateAdapter(), Microsoft.Xna.Framework.Game.RedrawWindow(), System.Collections.Generic.List< T >.Remove(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.Reset(), SDL3.SDL.SDL_DisableScreenSaver(), SDL3.SDL.SDL_EnableScreenSaver(), SDL3.SDL.SDL_GetCurrentVideoDriver(), SDL3.SDL.SDL_GetWindowFlags(), SDL3.SDL.SDL_PollEvent(), SDL3.SDL.SDL_SetWindowFullscreen(), Microsoft.Xna.Framework.Game.Services, Microsoft.Xna.Framework.SDL3_FNAPlatform.SupportsOrientationChanges(), Microsoft.Xna.Framework.FNAPlatform.TextInputBindings, Microsoft.Xna.Framework.FNAPlatform.TextInputCharacters, Microsoft.Xna.Framework.SDL3_FNAPlatform.ToXNAKey(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), Microsoft.Xna.Framework.Input.U, System.Text.Encoding.UTF8, Microsoft.Xna.Framework.Rectangle.Width, Microsoft.Xna.Framework.Game.Window, and Microsoft.Xna.Framework.Input.Mouse.WindowHandle.
Referenced by Microsoft.Xna.Framework.FNAPlatform.FNAPlatform().