Terraria Decompiled: Microsoft.Xna.Framework.SDL3_FNAPlatform.UpdateTouchPanelState
UpdateTouchPanelState()
static unsafe void Microsoft.Xna.Framework.SDL3_FNAPlatform.UpdateTouchPanelState () inline static
Definition at line 1445 of file SDL3_FNAPlatform.cs.
        {
            int num;
            IntPtr intPtr = SDL.SDL_GetTouchFingers(SDL3_FNAPlatform.GetTouchDeviceId(0), out num);
            for (int i = 0; i < 8; i++)
            {
                if (i >= num)
                {
                    TouchPanel.SetFinger(i, -1, Vector2.Zero);
                }
                else
                {
                    SDL.SDL_Finger* ptr = *(IntPtr*)((byte*)(void*)intPtr + (IntPtr)i * (IntPtr)sizeof(SDL.SDL_Finger*));
                    TouchPanel.SetFinger(i, (int)ptr->id, new Vector2((float)Math.Round((double)(ptr->x * (float)TouchPanel.DisplayWidth)), (float)Math.Round((double)(ptr->y * (float)TouchPanel.DisplayHeight))));
                }
            }
            SDL.SDL_free(intPtr);
        }
References Microsoft.Xna.Framework.Input.Touch.TouchPanel.DisplayHeight, Microsoft.Xna.Framework.Input.Touch.TouchPanel.DisplayWidth, Microsoft.Xna.Framework.SDL3_FNAPlatform.GetTouchDeviceId(), System.Math.Round(), SDL3.SDL.SDL_free(), SDL3.SDL.SDL_GetTouchFingers(), Microsoft.Xna.Framework.Input.Touch.TouchPanel.SetFinger(), Microsoft.Xna.Framework.Graphics.Vector2, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Microsoft.Xna.Framework.FNAPlatform.FNAPlatform().