Terraria Decompiled: Microsoft.Xna.Framework.SDL3_FNAPlatform.GetTouchDeviceId
GetTouchDeviceId()
static unsafe ulong Microsoft.Xna.Framework.SDL3_FNAPlatform.GetTouchDeviceId (int index) inline static private
Definition at line 1473 of file SDL3_FNAPlatform.cs.
        {
            int num;
            IntPtr intPtr = SDL.SDL_GetTouchDevices(out num);
            ulong num2 = (ulong)((index >= 0 && index < num) ? (*(long*)((byte*)(void*)intPtr + (IntPtr)index * 8)) : 0L);
            SDL.SDL_free(intPtr);
            return num2;
        }
References System.index, Microsoft.Xna.Framework.Input.L, SDL3.SDL.SDL_free(), and SDL3.SDL.SDL_GetTouchDevices().
Referenced by Microsoft.Xna.Framework.SDL3_FNAPlatform.GetNumTouchFingers(), and Microsoft.Xna.Framework.SDL3_FNAPlatform.UpdateTouchPanelState().