Terraria Decompiled: Terraria.Graphics.Light.LightMap.Blur
Blur()
void Terraria.Graphics.Light.LightMap.Blur () inline
Definition at line 206 of file LightMap.cs.
        {
            this.BlurPass();
            this.BlurPass();
            this._random.NextSeed();
        }
References Terraria.Graphics.Light.LightMap._random, Terraria.Graphics.Light.LightMap.BlurPass(), and Terraria.Utilities.FastRandom.NextSeed().
Referenced by Terraria.Graphics.Light.LightingEngine.ProcessBlur().