Terraria Decompiled: Terraria.Graphics.Light.LightMap.BlurLine
BlurLine()
void Terraria.Graphics.Light.LightMap.BlurLine (int startIndex, int endIndex, int stride) inline private
Definition at line 235 of file LightMap.cs.
        {
            Vector3 zero = Vector3.Zero;
            bool flag = false;
            bool flag2 = false;
            bool flag3 = false;
            for (int num = startIndex; num != endIndex + stride; num += stride)
            {
                if (zero.X < this._colors[num].X)
                {
                    zero.X = this._colors[num].X;
                    flag = false;
                }
                else if (!flag)
                {
                    if (zero.X < 0.0185f)
                    {
                        flag = true;
                    }
                    else
                    {
                        this._colors[num].X = zero.X;
                    }
                }
                if (zero.Y < this._colors[num].Y)
                {
                    zero.Y = this._colors[num].Y;
                    flag2 = false;
                }
                else if (!flag2)
                {
                    if (zero.Y < 0.0185f)
                    {
                        flag2 = true;
                    }
                    else
                    {
                        this._colors[num].Y = zero.Y;
                    }
                }
                if (zero.Z < this._colors[num].Z)
                {
                    zero.Z = this._colors[num].Z;
                    flag3 = false;
                }
                else if (!flag3)
                {
                    if (zero.Z < 0.0185f)
                    {
                        flag3 = true;
                    }
                    else
                    {
                        this._colors[num].Z = zero.Z;
                    }
                }
                if (!flag || !flag3 || !flag2)
                {
                    switch (this._mask[num])
                    {
                    case LightMaskMode.None:
                        if (!flag)
{
                            zero.X *= this.LightDecayThroughAir;
                        }
                        if (!flag2)
{
                            zero.Y *= this.LightDecayThroughAir;
                        }
                        if (!flag3)
{
                            zero.Z *= this.LightDecayThroughAir;
                        }
                        break;
                    case LightMaskMode.Solid:
                        if (!flag)
{
                            zero.X *= this.LightDecayThroughSolid;
                        }
                        if (!flag2)
{
                            zero.Y *= this.LightDecayThroughSolid;
                        }
                        if (!flag3)
{
                            zero.Z *= this.LightDecayThroughSolid;
                        }
                        break;
                    case LightMaskMode.Water:
                    {
                        float num2 = (float)this._random.WithModifier((ulong)((long)num)).Next(98, 100) / 100f;
                        if (!flag)
{
                            zero.X *= this.LightDecayThroughWater.X * num2;
                        }
                        if (!flag2)
{
                            zero.Y *= this.LightDecayThroughWater.Y * num2;
                        }
                        if (!flag3)
{
                            zero.Z *= this.LightDecayThroughWater.Z * num2;
                        }
                        break;
                    }
                    case LightMaskMode.Honey:
                        if (!flag)
{
                            zero.X *= this.LightDecayThroughHoney.X;
                        }
                        if (!flag2)
{
                            zero.Y *= this.LightDecayThroughHoney.Y;
                        }
                        if (!flag3)
{
                            zero.Z *= this.LightDecayThroughHoney.Z;
                        }
                        break;
                    case LightMaskMode.CrackedBricks:
                        if (!flag)
{
                            zero.X *= this.LightDecayThroughCrackedBrick;
                        }
                        if (!flag2)
{
                            zero.Y *= this.LightDecayThroughCrackedBrick;
                        }
                        if (!flag3)
{
                            zero.Z *= this.LightDecayThroughCrackedBrick;
                        }
                        break;
                    }
                }
            }
        }
References Terraria.Graphics.Light.LightMap._colors, Terraria.Graphics.Light.LightMap._mask, Terraria.Graphics.Light.LightMap._random, System.endIndex, Terraria.Graphics.Light.LightMap.LightDecayThroughAir, Terraria.Graphics.Light.LightMap.LightDecayThroughCrackedBrick, Terraria.Graphics.Light.LightMap.LightDecayThroughHoney, Terraria.Graphics.Light.LightMap.LightDecayThroughSolid, long, System.startIndex, Terraria.Utilities.FastRandom.WithModifier(), Microsoft.Xna.Framework.Vector3.X, Microsoft.Xna.Framework.Vector3.Y, Microsoft.Xna.Framework.Vector3.Z, and Microsoft.Xna.Framework.Vector3.Zero.
Referenced by Terraria.Graphics.Light.LightMap.b__46_0(), Terraria.Graphics.Light.LightMap.b__46_1(), and Terraria.Graphics.Light.LightMap.BlurPass().