Terraria Decompiled: Terraria.DataStructures.TileEntity.Place
Place()
static int Terraria.DataStructures.TileEntity.Place (int x, int y, int type) inline static protected
Definition at line 152 of file TileEntity.cs.
        {
            TileEntity tileEntity = TileEntity.manager.GenerateInstance(type);
            tileEntity.Position = new Point16(x, y);
            tileEntity.ID = TileEntity.AssignNewID();
            tileEntity.type = (byte)type;
            TileEntity.Add(tileEntity);
            tileEntity.OnPlaced();
            return tileEntity.ID;
        }
References Terraria.DataStructures.TileEntity.Add(), Terraria.DataStructures.TileEntity.AssignNewID(), Terraria.DataStructures.TileEntitiesManager.GenerateInstance(), Terraria.DataStructures.TileEntity.ID, Terraria.DataStructures.TileEntity.manager, Terraria.DataStructures.TileEntity.OnPlaced(), and Terraria.DataStructures.TileEntity.type.
Referenced by Terraria.GameContent.Tile_Entities.TEKiteAnchor.DebugPlace(), Terraria.GameContent.Tile_Entities.TELeashedEntityAnchor.NetPlaceEntityAttempt(), Terraria.DataStructures.TileEntityType< T >.Place(), and Terraria.GameContent.Tile_Entities.TELeashedEntityAnchor.PlaceFromPlayerPlacementHook().