Terraria Decompiled: Terraria.DataStructures.TileEntity.Add
Add()
static void Terraria.DataStructures.TileEntity.Add (TileEntity ent) inline static
Definition at line 127 of file TileEntity.cs.
        {
            object entityCreationLock = TileEntity.EntityCreationLock;
            lock (entityCreationLock)
            {
                TileEntity.ByID[ent.ID] = ent;
                TileEntity.ByPosition[ent.Position] = ent;
                if (ent.RequiresUpdates)
                {
                    TileEntity.UpdateEntities.Add(ent);
                }
            }
        }
References System.Collections.Generic.List< T >.Add(), Terraria.DataStructures.TileEntity.ByID, Terraria.DataStructures.TileEntity.ByPosition, Terraria.DataStructures.TileEntity.EntityCreationLock, Terraria.DataStructures.TileEntity.ID, Terraria.DataStructures.TileEntity.Position, Terraria.DataStructures.TileEntity.RequiresUpdates, and Terraria.DataStructures.TileEntity.UpdateEntities.
Referenced by Terraria.NetMessage.DecompressTileBlock_Inner(), Terraria.IO.WorldFile.LoadTileEntities(), Terraria.DataStructures.TileEntity.Place(), and Terraria.Utilities.TileSnapshot.Restore().