Terraria Decompiled: Terraria.DataStructures.TileEntity.Read
Read()
static TileEntity Terraria.DataStructures.TileEntity.Read (BinaryReader reader, int gameVersion, bool networkSend = false) inline static
Definition at line 250 of file TileEntity.cs.
        {
            byte b = reader.ReadByte();
            TileEntity tileEntity = TileEntity.manager.GenerateInstance((int)b);
            tileEntity.type = b;
            tileEntity.ReadInner(reader, gameVersion, networkSend);
            return tileEntity;
        }
References Terraria.DataStructures.TileEntitiesManager.GenerateInstance(), Terraria.DataStructures.TileEntity.manager, System.IO.BinaryReader.ReadByte(), and Terraria.DataStructures.TileEntity.ReadInner().
Referenced by Terraria.Utilities.TileSnapshot.Clone(), Terraria.NetMessage.DecompressTileBlock_Inner(), Terraria.Utilities.TileSnapshot.Load(), Terraria.IO.WorldFile.LoadTileEntities(), and Terraria.IO.WorldFile.ValidateWorld().