Terraria Decompiled: Terraria.DataStructures.TileEntity.BasicOpenCloseInteraction
BasicOpenCloseInteraction()
static void Terraria.DataStructures.TileEntity.BasicOpenCloseInteraction (Player player, int x, int y, int id) inline static
Definition at line 331 of file TileEntity.cs.
        {
            player.CloseSign(false);
            if (Main.netMode != 1)
            {
                Main.stackSplit = 600;
                player.GamepadEnableGrappleCooldown();
                int num;
                if (!TileEntity.IsOccupied(id, out num))
                {
                    TileEntity.SetInteractionAnchor(player, x, y, id);
                    return;
                }
                if (num == player.whoAmI)
                {
                    SoundEngine.PlaySound(11, -1, -1, 1, 1f, 0f);
                    player.tileEntityAnchor.Clear();
                    return;
                }
            }
            else
            {
                Main.stackSplit = 600;
                player.GamepadEnableGrappleCooldown();
                int num;
                if (TileEntity.IsOccupied(id, out num))
                {
                    if (num == player.whoAmI)
                    {
                        SoundEngine.PlaySound(11, -1, -1, 1, 1f, 0f);
                        player.tileEntityAnchor.Clear();
                        NetMessage.SendData(122, -1, -1, null, -1, (float)Main.myPlayer, 0f, 0f, 0, 0, 0);
                        return;
                    }
                }
                else
                {
                    NetMessage.SendData(122, -1, -1, null, id, (float)Main.myPlayer, 0f, 0f, 0, 0, 0);
                }
            }
        }
References Terraria.Player.CloseSign(), Terraria.Player.GamepadEnableGrappleCooldown(), Terraria.DataStructures.TileEntity.IsOccupied(), Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Audio.SoundEngine.PlaySound(), Terraria.NetMessage.SendData(), Terraria.DataStructures.TileEntity.SetInteractionAnchor(), Terraria.Player.tileEntityAnchor, and Terraria.Entity.whoAmI.
Referenced by Terraria.GameContent.Tile_Entities.TEDisplayDoll.OnPlayerInteraction(), and Terraria.GameContent.Tile_Entities.TEHatRack.OnPlayerInteraction().