Terraria Decompiled: System.Collections.Stack.Clone
Clone()
virtual object System.Collections.Stack.Clone () inline virtual
Implements System.ICloneable.
Reimplemented in System.Collections.Stack.SyncStack.
Definition at line 94 of file Stack.cs.
        {
            Stack stack = new Stack(this._size);
            stack._size = this._size;
            Array.Copy(this._array, 0, stack._array, 0, this._size);
            stack._version = this._version;
            return stack;
        }
References System.Collections.Stack._array, System.Collections.Stack._size, System.Collections.Stack._version, System.Array.Copy(), System.Collections.Stack.Stack(), and System.stack.
Referenced by System.Collections.Stack.SyncStack.Clone().