Terraria Decompiled: System.Globalization.TimeSpanParse.TimeSpanRawInfo.ProcessToken
ProcessToken()
bool System.Globalization.TimeSpanParse.TimeSpanRawInfo.ProcessToken (ref TimeSpanParse::TimeSpanToken tok, ref TimeSpanParse::TimeSpanResult result) inline package
Definition at line 1245 of file TimeSpanParse.cs.
            {
                switch (tok._ttt)
                {
                case TimeSpanParse.TTT.Num:
                    if ((this._tokenCount == 0 && !this.AddSep(default(ReadOnlySpan<char>), ref result)) || !this.AddNum(tok, ref result))
                    {
                        return false;
                    }
                    break;
                case TimeSpanParse.TTT.Sep:
                    if (!this.AddSep(tok._sep, ref result))
                    {
                        return false;
                    }
                    break;
                case TimeSpanParse.TTT.NumOverflow:
                    return result.SetFailure(TimeSpanParse.ParseFailureKind.Overflow, "The TimeSpan could not be parsed because at least one of the numeric components is out of range or contains too many digits.", null, null);
                default:
                    return result.SetFailure(TimeSpanParse.ParseFailureKind.Format, "String was not recognized as a valid TimeSpan.", null, null);
                }
                this._lastSeenTTT = tok._ttt;
                return true;
            }
References System.Globalization.TimeSpanParse.TimeSpanRawInfo._tokenCount, System.Globalization.TimeSpanParse.TimeSpanRawInfo.AddNum(), and System.Globalization.TimeSpanParse.TimeSpanRawInfo.AddSep().
Referenced by System.Globalization.TimeSpanParse.TryParseTimeSpan().