Terraria Decompiled: Terraria.Net.Sockets.DebugNetworkStream.Run
Run()
void Terraria.Net.Sockets.DebugNetworkStream.Run () inline private
Definition at line 181 of file DebugNetworkStream.cs.
        {
            byte[] array = null;
            while (!this._closed)
            {
                Queue<DebugNetworkStream.Packet> queue = this._outgoingQueue;
                lock (queue)
                {
                    while (this._writeException == null && this._outgoingQueue.Count > 0 && this._outgoingQueue.Peek().IsReady())
                    {
                        this.BeginBufferedWrite(this._outgoingQueue.Dequeue());
                    }
                }
                queue = this._incomingQueue;
                lock (queue)
                {
                    if (this._readMode == DebugNetworkStream.ReadMode.None && DebugNetworkStream.Latency > 0U)
                    {
                        this._readMode = DebugNetworkStream.ReadMode.Buffered;
                        if (array == null)
{
                            array = new byte[65536];
                        }
                        this.BeginBufferedRead(array);
                    }
                }
                Thread.Sleep(1);
            }
        }
References Terraria.Net.Sockets.DebugNetworkStream._closed, Terraria.Net.Sockets.DebugNetworkStream._incomingQueue, Terraria.Net.Sockets.DebugNetworkStream._outgoingQueue, Terraria.Net.Sockets.DebugNetworkStream._readMode, Terraria.Net.Sockets.DebugNetworkStream._writeException, System.array, Terraria.Net.Sockets.DebugNetworkStream.BeginBufferedRead(), Terraria.Net.Sockets.DebugNetworkStream.BeginBufferedWrite(), Terraria.Net.Sockets.DebugNetworkStream.Latency, System.queue, System.Threading.Thread.Sleep(), and System.U.