Terraria Decompiled: Terraria.Net.Sockets.DebugNetworkStream.BeginRead
BeginRead()
void Terraria.Net.Sockets.DebugNetworkStream.BeginRead (byte[] buffer, int offset, int count, AsyncCallback callback, object state) inline
Definition at line 87 of file DebugNetworkStream.cs.
        {
            if (this._closed)
            {
                throw new ObjectDisposedException("NetworkStream");
            }
            if (this._readException != null)
            {
                throw this._readException;
            }
            this._beginReadBuf = new ArraySegment<byte>(buffer, offset, count);
            Queue<DebugNetworkStream.Packet> incomingQueue = this._incomingQueue;
            lock (incomingQueue)
            {
                while (this._readMode == DebugNetworkStream.ReadMode.Buffered && this._incomingQueue.Count == 0)
                {
                    Monitor.Exit(this._incomingQueue);
                    Thread.Sleep(1);
                    Monitor.Enter(this._incomingQueue);
                    if (this._readException != null)
                    {
                        throw this._readException;
                    }
                }
                if (this._readMode == DebugNetworkStream.ReadMode.None && this._incomingQueue.Count == 0)
                {
                    this._readMode = DebugNetworkStream.ReadMode.Direct;
                    this._stream.BeginRead(buffer, offset, count, callback, state);
                }
                else
                {
                    int num = 0;
                    while (count > 0 && this._incomingQueue.Count > 0 && this._incomingQueue.Peek().IsReady())
                    {
                        DebugNetworkStream.Packet packet = this._incomingQueue.Peek();
                        if (packet.Data.Count == 0)
{
                            break;
                        }
                        int num2 = Math.Min(packet.Data.Count, count);
                        Array.Copy(packet.Data.Array, packet.Data.Offset, buffer, offset, num2);
                        offset += num2;
                        count -= num2;
                        num += num2;
                        if (num2 == packet.Data.Count)
{
                            this._incomingQueue.Dequeue();
                        }
                        else
{
                            packet.Data = new ArraySegment<byte>(packet.Data.Array, packet.Data.Offset + num2, packet.Data.Count - num2);
                        }
                    }
                    callback(new DebugNetworkStream.CompletedAsyncResult
                    {
                        AsyncState = state,
                        Read = num
                    });
                }
            }
        }
References Terraria.Net.Sockets.DebugNetworkStream._closed, Terraria.Net.Sockets.DebugNetworkStream._incomingQueue, Terraria.Net.Sockets.DebugNetworkStream._readException, Terraria.Net.Sockets.DebugNetworkStream._readMode, Terraria.Net.Sockets.DebugNetworkStream._stream, System.ArraySegment< T >.Array, System.Array.Copy(), System.ArraySegment< T >.Count, System.count, Terraria.Net.Sockets.DebugNetworkStream.Packet.Data, System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), System.Math.Min(), System.ArraySegment< T >.Offset, System.offset, System.Threading.Thread.Sleep(), and System.state.
Referenced by Terraria.Net.Sockets.TcpSocket.AsyncReceive().