Terraria Decompiled: Terraria.Net.Sockets.DebugNetworkStream.BeginBufferedRead
BeginBufferedRead()
void Terraria.Net.Sockets.DebugNetworkStream.BeginBufferedRead (byte[] buffer) inline private
Definition at line 238 of file DebugNetworkStream.cs.
        {
            try
            {
                this._stream.BeginRead(buffer, 0, buffer.Length, new AsyncCallback(this.BufferedReadCallback), buffer);
            }
            catch (Exception ex)
            {
                this._readException = ex;
            }
        }
References Terraria.Net.Sockets.DebugNetworkStream._stream, and Terraria.Net.Sockets.DebugNetworkStream.BufferedReadCallback().
Referenced by Terraria.Net.Sockets.DebugNetworkStream.BufferedReadCallback(), and Terraria.Net.Sockets.DebugNetworkStream.Run().