Terraria Decompiled: Terraria.GameContent.UI.States.UICharacterSelect.Draw
Draw()
override void Terraria.GameContent.UI.States.UICharacterSelect.Draw (SpriteBatch spriteBatch) inline virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 154 of file UICharacterSelect.cs.
        {
            if (this.skipDraw)
            {
                this.skipDraw = false;
                return;
            }
            if (this.UpdateFavoritesCache())
            {
                this.skipDraw = true;
                Main.MenuUI.Draw(spriteBatch, new GameTime());
            }
            base.Draw(spriteBatch);
            this.SetupGamepadPoints(spriteBatch);
        }
References Terraria.UI.UserInterface.Draw(), Terraria.Main.MenuUI, Terraria.GameContent.UI.States.UICharacterSelect.SetupGamepadPoints(), Terraria.GameContent.UI.States.UICharacterSelect.skipDraw, and Terraria.GameContent.UI.States.UICharacterSelect.UpdateFavoritesCache().