Terraria Decompiled: System.Number.TryParseInt64IntegerStyle
TryParseInt64IntegerStyle()
static unsafe bool System.Number.TryParseInt64IntegerStyle (ReadOnlySpan< char > value, NumberStyles styles, NumberFormatInfo info, out long result, ref bool failureIsOverflow) inline static private
Definition at line 2719 of file Number.cs.
        {
            if (value.Length >= 1)
            {
                bool flag = false;
                int num = 1;
                int num2 = 0;
                int num3 = (int)(*value[0]);
                if ((styles & NumberStyles.AllowLeadingWhite) != NumberStyles.None && global::System.Number.IsWhite(num3))
                {
                    do
                    {
                        num2++;
                        if (num2 >= value.Length)
{
                            goto IL_0278;
                        }
                        num3 = (int)(*value[num2]);
                    }
                    while (global::System.Number.IsWhite(num3));
                }
                if ((styles & NumberStyles.AllowLeadingSign) != NumberStyles.None)
                {
                    string positiveSign = info.PositiveSign;
                    string negativeSign = info.NegativeSign;
                    if (positiveSign == "+" && negativeSign == "-")
                    {
                        if (num3 == 45)
{
                            num = -1;
                            num2++;
                            if (num2 >= value.Length)
{
                                goto IL_0278;
                            }
                            num3 = (int)(*value[num2]);
                        }
                        else if (num3 == 43)
{
                            num2++;
                            if (num2 >= value.Length)
{
                                goto IL_0278;
                            }
                            num3 = (int)(*value[num2]);
                        }
                    }
                    else
                    {
                        value = value.Slice(num2);
                        num2 = 0;
                        if (!string.IsNullOrEmpty(positiveSign) && value.StartsWith(positiveSign))
{
                            num2 += positiveSign.Length;
                            if (num2 >= value.Length)
{
                                goto IL_0278;
                            }
                            num3 = (int)(*value[num2]);
                        }
                        else if (!string.IsNullOrEmpty(negativeSign) && value.StartsWith(negativeSign))
{
                            num = -1;
                            num2 += negativeSign.Length;
                            if (num2 >= value.Length)
{
                                goto IL_0278;
                            }
                            num3 = (int)(*value[num2]);
                        }
                    }
                }
                long num4 = 0L;
                if (global::System.Number.IsDigit(num3))
                {
                    if (num3 == 48)
                    {
                        do
{
                            num2++;
                            if (num2 >= value.Length)
{
                                goto IL_027E;
                            }
                            num3 = (int)(*value[num2]);
                        }
                        while (num3 == 48);
                        if (!global::System.Number.IsDigit(num3))
{
                            goto IL_0290;
                        }
                    }
                    num4 = (long)(num3 - 48);
                    num2++;
                    for (int i = 0; i < 17; i++)
                    {
                        if (num2 >= value.Length)
{
                            goto IL_027E;
                        }
                        num3 = (int)(*value[num2]);
                        if (!global::System.Number.IsDigit(num3))
{
                            goto IL_0290;
                        }
                        num2++;
                        num4 = 10L * num4 + (long)num3 - 48L;
                    }
                    if (num2 < value.Length)
                    {
                        num3 = (int)(*value[num2]);
                        if (!global::System.Number.IsDigit(num3))
{
                            goto IL_0290;
                        }
                        num2++;
                        if (num4 > 922337203685477580L)
{
                            flag = true;
                        }
                        num4 = num4 * 10L + (long)num3 - 48L;
                        if (num4 > 9223372036854775807L + (long)((-1 * num + 1) / 2))
{
                            flag = true;
                        }
                        if (num2 < value.Length)
{
                            num3 = (int)(*value[num2]);
                            while (global::System.Number.IsDigit(num3))
{
                                flag = true;
                                num2++;
                                if (num2 >= value.Length)
{
                                    goto IL_027E;
                                }
                                num3 = (int)(*value[num2]);
                            }
                            goto IL_0290;
                        }
                    }
                    IL_027E:
                    if (flag)
                    {
                        failureIsOverflow = true;
                        goto IL_0278;
                    }
                    result = num4 * (long)num;
                    return true;
                    IL_0290:
                    if (global::System.Number.IsWhite(num3))
                    {
                        if ((styles & NumberStyles.AllowTrailingWhite) == NumberStyles.None)
{
                            goto IL_0278;
                        }
                        num2++;
                        while (num2 < value.Length && global::System.Number.IsWhite((int)(*value[num2])))
{
                            num2++;
                        }
                        if (num2 >= value.Length)
{
                            goto IL_027E;
                        }
                    }
                    if (global::System.Number.TrailingZeros(value, num2))
                    {
                        goto IL_027E;
                    }
                }
            }
            IL_0278:
            result = 0L;
            return false;
        }
References System.info, int, System.Number.IsDigit(), System.Number.IsWhite(), System.L, long, System.Number.TrailingZeros(), and System.value.
Referenced by System.Number.ParseInt64().