Terraria Decompiled: System.Number.TryParseUInt32IntegerStyle
TryParseUInt32IntegerStyle()
static unsafe bool System.Number.TryParseUInt32IntegerStyle (ReadOnlySpan< char > value, NumberStyles styles, NumberFormatInfo info, out uint result, ref bool failureIsOverflow) inline static private
Definition at line 2933 of file Number.cs.
        {
            if (value.Length >= 1)
            {
                bool flag = false;
                bool flag2 = false;
                int num = 0;
                int num2 = (int)(*value[0]);
                if ((styles & NumberStyles.AllowLeadingWhite) != NumberStyles.None && global::System.Number.IsWhite(num2))
                {
                    do
                    {
                        num++;
                        if (num >= value.Length)
{
                            goto IL_025B;
                        }
                        num2 = (int)(*value[num]);
                    }
                    while (global::System.Number.IsWhite(num2));
                }
                if ((styles & NumberStyles.AllowLeadingSign) != NumberStyles.None)
                {
                    string positiveSign = info.PositiveSign;
                    string negativeSign = info.NegativeSign;
                    if (positiveSign == "+" && negativeSign == "-")
                    {
                        if (num2 == 43)
{
                            num++;
                            if (num >= value.Length)
{
                                goto IL_025B;
                            }
                            num2 = (int)(*value[num]);
                        }
                        else if (num2 == 45)
{
                            flag2 = true;
                            num++;
                            if (num >= value.Length)
{
                                goto IL_025B;
                            }
                            num2 = (int)(*value[num]);
                        }
                    }
                    else
                    {
                        value = value.Slice(num);
                        num = 0;
                        if (!string.IsNullOrEmpty(positiveSign) && value.StartsWith(positiveSign))
{
                            num += positiveSign.Length;
                            if (num >= value.Length)
{
                                goto IL_025B;
                            }
                            num2 = (int)(*value[num]);
                        }
                        else if (!string.IsNullOrEmpty(negativeSign) && value.StartsWith(negativeSign))
{
                            flag2 = true;
                            num += negativeSign.Length;
                            if (num >= value.Length)
{
                                goto IL_025B;
                            }
                            num2 = (int)(*value[num]);
                        }
                    }
                }
                int num3 = 0;
                if (global::System.Number.IsDigit(num2))
                {
                    if (num2 == 48)
                    {
                        do
{
                            num++;
                            if (num >= value.Length)
{
                                goto IL_0260;
                            }
                            num2 = (int)(*value[num]);
                        }
                        while (num2 == 48);
                        if (!global::System.Number.IsDigit(num2))
{
                            goto IL_0276;
                        }
                    }
                    num3 = num2 - 48;
                    num++;
                    for (int i = 0; i < 8; i++)
                    {
                        if (num >= value.Length)
{
                            goto IL_0260;
                        }
                        num2 = (int)(*value[num]);
                        if (!global::System.Number.IsDigit(num2))
{
                            goto IL_0276;
                        }
                        num++;
                        num3 = 10 * num3 + num2 - 48;
                    }
                    if (num < value.Length)
                    {
                        num2 = (int)(*value[num]);
                        if (!global::System.Number.IsDigit(num2))
{
                            goto IL_0276;
                        }
                        num++;
                        if (num3 > 429496729 || (num3 == 429496729 && num2 > 53))
{
                            flag = true;
                        }
                        num3 = num3 * 10 + num2 - 48;
                        if (num < value.Length)
{
                            num2 = (int)(*value[num]);
                            while (global::System.Number.IsDigit(num2))
{
                                flag = true;
                                num++;
                                if (num >= value.Length)
{
                                    goto IL_0260;
                                }
                                num2 = (int)(*value[num]);
                            }
                            goto IL_0276;
                        }
                    }
                    IL_0260:
                    if (flag || (flag2 && num3 != 0))
                    {
                        failureIsOverflow = true;
                        goto IL_025B;
                    }
                    result = (uint)num3;
                    return true;
                    IL_0276:
                    if (global::System.Number.IsWhite(num2))
                    {
                        if ((styles & NumberStyles.AllowTrailingWhite) == NumberStyles.None)
{
                            goto IL_025B;
                        }
                        num++;
                        while (num < value.Length && global::System.Number.IsWhite((int)(*value[num])))
{
                            num++;
                        }
                        if (num >= value.Length)
{
                            goto IL_0260;
                        }
                    }
                    if (global::System.Number.TrailingZeros(value, num))
                    {
                        goto IL_0260;
                    }
                }
            }
            IL_025B:
            result = 0U;
            return false;
        }
References System.info, int, System.Number.IsDigit(), System.Number.IsWhite(), System.Number.TrailingZeros(), System.U, and System.value.
Referenced by System.Number.ParseUInt32().