Terraria Decompiled: System.Number.TryFormatUInt32
TryFormatUInt32()
static unsafe bool System.Number.TryFormatUInt32 (uint value, ReadOnlySpan< char > format, IFormatProvider provider, Span< char > destination, out int charsWritten) inline static
Definition at line 441 of file Number.cs.
        {
            if (format.Length == 0)
            {
                return global::System.Number.TryUInt32ToDecStr(value, -1, destination, out charsWritten);
            }
            int num;
            char c = global::System.Number.ParseFormatSpecifier(format, out num);
            NumberFormatInfo instance = NumberFormatInfo.GetInstance(provider);
            char c2 = c & '\uffdf';
            if ((c2 == 'G' && num < 1) || c2 == 'D')
            {
                return global::System.Number.TryUInt32ToDecStr(value, num, destination, out charsWritten);
            }
            if (c2 == 'X')
            {
                return global::System.Number.TryInt32ToHexStr((int)value, c - '!', num, destination, out charsWritten);
            }
            global::System.Number.NumberBuffer numberBuffer = default(global::System.Number.NumberBuffer);
            global::System.Number.UInt32ToNumber(value, ref numberBuffer);
            char* ptr = stackalloc char[(UIntPtr)64];
            ValueStringBuilder valueStringBuilder = new ValueStringBuilder(new Span<char>((void*)ptr, 32));
            if (c != '\0')
            {
                global::System.Number.NumberToString(ref valueStringBuilder, ref numberBuffer, c, num, instance, false);
            }
            else
            {
                global::System.Number.NumberToStringFormat(ref valueStringBuilder, ref numberBuffer, format, instance);
            }
            return valueStringBuilder.TryCopyTo(destination, out charsWritten);
        }
References System.destination, System.format, System.Globalization.NumberFormatInfo.GetInstance(), and System.value.
Referenced by System.Int16.TryFormat(), System.SByte.TryFormat(), System.UInt16.TryFormat(), and System.UInt32.TryFormat().