Terraria Decompiled: System.Number.TryParseDecimal
TryParseDecimal()
static bool System.Number.TryParseDecimal (ReadOnlySpan< char > value, NumberStyles styles, NumberFormatInfo info, out decimal result) inline static package
Definition at line 3720 of file Number.cs.
        {
            global::System.Number.NumberBuffer numberBuffer = default(global::System.Number.NumberBuffer);
            result = 0m;
            return global::System.Number.TryStringToNumber(value, styles, ref numberBuffer, info, true) && global::System.Number.NumberBufferToDecimal(ref numberBuffer, ref result);
        }
References System.info, and System.value.
Referenced by System.Decimal.TryParse(), System.Decimal.TryParse(), System.Decimal.TryParse(), and System.Decimal.TryParse().