Terraria Decompiled: System.Number.ParseInt32
ParseInt32()
static int System.Number.ParseInt32 (ReadOnlySpan< char > value, NumberStyles styles, NumberFormatInfo info) inline static package
Definition at line 2204 of file Number.cs.
        {
            if ((styles & ~(NumberStyles.AllowLeadingWhite | NumberStyles.AllowTrailingWhite | NumberStyles.AllowLeadingSign)) == NumberStyles.None)
            {
                bool flag = false;
                int num;
                if (!global::System.Number.TryParseInt32IntegerStyle(value, styles, info, out num, ref flag))
                {
                    global::System.Number.ThrowOverflowOrFormatException(flag, "Value was either too large or too small for an Int32.");
                }
                return num;
            }
            if ((styles & NumberStyles.AllowHexSpecifier) != NumberStyles.None)
            {
                bool flag2 = false;
                uint num2;
                if (!global::System.Number.TryParseUInt32HexNumberStyle(value, styles, info, out num2, ref flag2))
                {
                    global::System.Number.ThrowOverflowOrFormatException(flag2, "Value was either too large or too small for an Int32.");
                }
                return (int)num2;
            }
            global::System.Number.NumberBuffer numberBuffer = default(global::System.Number.NumberBuffer);
            int num3 = 0;
            global::System.Number.StringToNumber(value, styles, ref numberBuffer, info, false);
            if (!global::System.Number.NumberToInt32(ref numberBuffer, ref num3))
            {
                global::System.Number.ThrowOverflowOrFormatException(true, "Value was either too large or too small for an Int32.");
            }
            return num3;
        }
References System.info, System.Number.NumberToInt32(), System.Number.TryParseInt32IntegerStyle(), System.Number.TryParseUInt32HexNumberStyle(), and System.value.
Referenced by System.Byte.Parse(), System.Int16.Parse(), System.SByte.Parse(), System.Int32.Parse(), System.Int32.Parse(), System.Int32.Parse(), System.Int32.Parse(), and System.Int32.Parse().