Terraria Decompiled: System.Number.NegativeInt64ToDecStr
NegativeInt64ToDecStr()
static unsafe string System.Number.NegativeInt64ToDecStr (long input, int digits, string sNegative) inline static private
Definition at line 886 of file Number.cs.
        {
            if (digits < 1)
            {
                digits = 1;
            }
            ulong num = (ulong)(-(ulong)input);
            int num2 = Math.Max(digits, FormattingHelpers.CountDigits(num)) + sNegative.Length;
            string text = string.FastAllocateString(num2);
            fixed (string text2 = text)
            {
                char* ptr = text2;
                if (ptr != null)
                {
                    ptr += RuntimeHelpers.OffsetToStringData / 2;
                }
                char* ptr2 = ptr + num2;
                while (global::System.Number.High32(num) != 0U)
                {
                    ptr2 = global::System.Number.UInt32ToDecChars(ptr2, global::System.Number.Int64DivMod1E9(ref num), 9);
                    digits -= 9;
                }
                ptr2 = global::System.Number.UInt32ToDecChars(ptr2, global::System.Number.Low32(num), digits);
                for (int i = sNegative.Length - 1; i >= 0; i--)
                {
                    *(--ptr2) = sNegative[i];
                }
            }
            return text;
        }
References System.Buffers.Text.FormattingHelpers.CountDigits(), System.Number.High32(), System.input, System.Number.Int64DivMod1E9(), System.Number.Low32(), System.Math.Max(), System.text, and System.U.