Terraria Decompiled: System.Number.FormatUInt64
FormatUInt64()
static unsafe string System.Number.FormatUInt64 (ulong value, ReadOnlySpan< char > format, IFormatProvider provider) inline static
Definition at line 557 of file Number.cs.
        {
            if (format.Length == 0)
            {
                return global::System.Number.UInt64ToDecStr(value, -1);
            }
            int num;
            char c = global::System.Number.ParseFormatSpecifier(format, out num);
            NumberFormatInfo instance = NumberFormatInfo.GetInstance(provider);
            char c2 = c & '\uffdf';
            if ((c2 == 'G' && num < 1) || c2 == 'D')
            {
                return global::System.Number.UInt64ToDecStr(value, num);
            }
            if (c2 == 'X')
            {
                return global::System.Number.Int64ToHexStr((long)value, c - '!', num);
            }
            global::System.Number.NumberBuffer numberBuffer = default(global::System.Number.NumberBuffer);
            global::System.Number.UInt64ToNumber(value, ref numberBuffer);
            char* ptr = stackalloc char[(UIntPtr)64];
            ValueStringBuilder valueStringBuilder = new ValueStringBuilder(new Span<char>((void*)ptr, 32));
            if (c != '\0')
            {
                global::System.Number.NumberToString(ref valueStringBuilder, ref numberBuffer, c, num, instance, false);
            }
            else
            {
                global::System.Number.NumberToStringFormat(ref valueStringBuilder, ref numberBuffer, format, instance);
            }
            return valueStringBuilder.ToString();
        }
References System.format, System.Globalization.NumberFormatInfo.GetInstance(), and System.value.
Referenced by System.UInt64.ToString(), System.UInt64.ToString(), System.UInt64.ToString(), and System.UInt64.ToString().