Terraria Decompiled: System.Number.FormatInt32
FormatInt32()
static unsafe string System.Number.FormatInt32 (int value, ReadOnlySpan< char > format, IFormatProvider provider) inline static
Definition at line 325 of file Number.cs.
        {
            if (value >= 0 && format.Length == 0)
            {
                return global::System.Number.UInt32ToDecStr((uint)value, -1);
            }
            int num;
            char c = global::System.Number.ParseFormatSpecifier(format, out num);
            NumberFormatInfo instance = NumberFormatInfo.GetInstance(provider);
            char c2 = c & '\uffdf';
            if ((c2 == 'G' && num < 1) || c2 == 'D')
            {
                if (value < 0)
                {
                    return global::System.Number.NegativeInt32ToDecStr(value, num, instance.NegativeSign);
                }
                return global::System.Number.UInt32ToDecStr((uint)value, num);
            }
            else
            {
                if (c2 == 'X')
                {
                    return global::System.Number.Int32ToHexStr(value, c - '!', num);
                }
                global::System.Number.NumberBuffer numberBuffer = default(global::System.Number.NumberBuffer);
                global::System.Number.Int32ToNumber(value, ref numberBuffer);
                char* ptr = stackalloc char[(UIntPtr)64];
                ValueStringBuilder valueStringBuilder = new ValueStringBuilder(new Span<char>((void*)ptr, 32));
                if (c != '\0')
                {
                    global::System.Number.NumberToString(ref valueStringBuilder, ref numberBuffer, c, num, instance, false);
                }
                else
                {
                    global::System.Number.NumberToStringFormat(ref valueStringBuilder, ref numberBuffer, format, instance);
                }
                return valueStringBuilder.ToString();
            }
        }
References System.format, System.Globalization.NumberFormatInfo.GetInstance(), System.Globalization.NumberFormatInfo.NegativeSign, and System.value.
Referenced by System.Byte.ToString(), System.Int16.ToString(), System.Int32.ToString(), System.SByte.ToString(), System.Byte.ToString(), System.Int16.ToString(), System.Int32.ToString(), System.SByte.ToString(), System.Byte.ToString(), System.Int32.ToString(), System.Byte.ToString(), System.Int16.ToString(), System.Int32.ToString(), and System.SByte.ToString().