Terraria Decompiled: System.Number.ParseNumber
ParseNumber()
static unsafe bool System.Number.ParseNumber (ref char * str, char * strEnd, NumberStyles styles, ref global::System::Number::NumberBuffer number, NumberFormatInfo info, bool parseDecimal) inline static private
Definition at line 2332 of file Number.cs.
        {
            number.scale = 0;
            number.sign = false;
            string text = null;
            bool flag = false;
            string text2;
            string text3;
            if ((styles & NumberStyles.AllowCurrencySymbol) != NumberStyles.None)
            {
                text = info.CurrencySymbol;
                text2 = info.CurrencyDecimalSeparator;
                text3 = info.CurrencyGroupSeparator;
                flag = true;
            }
            else
            {
                text2 = info.NumberDecimalSeparator;
                text3 = info.NumberGroupSeparator;
            }
            int num = 0;
            char* ptr = str;
            char c = ((ptr < strEnd) ? (*ptr) : '\0');
            for (;;)
            {
                if (!global::System.Number.IsWhite((int)c) || (styles & NumberStyles.AllowLeadingWhite) == NumberStyles.None || ((num & 1) != 0 && (num & 32) == 0 && info.NumberNegativePattern != 2))
                {
                    char* ptr2;
                    if ((styles & NumberStyles.AllowLeadingSign) != NumberStyles.None && (num & 1) == 0 && ((ptr2 = global::System.Number.MatchChars(ptr, strEnd, info.PositiveSign)) != null || ((ptr2 = global::System.Number.MatchChars(ptr, strEnd, info.NegativeSign)) != null && (number.sign = true))))
                    {
                        num |= 1;
                        ptr = ptr2 - 1;
                    }
                    else if (c == '(' && (styles & NumberStyles.AllowParentheses) != NumberStyles.None && (num & 1) == 0)
                    {
                        num |= 3;
                        number.sign = true;
                    }
                    else
                    {
                        if (text == null || (ptr2 = global::System.Number.MatchChars(ptr, strEnd, text)) == null)
{
                            break;
                        }
                        num |= 32;
                        text = null;
                        ptr = ptr2 - 1;
                    }
                }
                c = ((++ptr < strEnd) ? (*ptr) : '\0');
            }
            int num2 = 0;
            int num3 = 0;
            for (;;)
            {
                char* ptr2;
                if (global::System.Number.IsDigit((int)c))
                {
                    num |= 4;
                    if (c != '0' || (num & 8) != 0)
                    {
                        if (num2 < 50)
{
                            number.digits[(IntPtr)(num2++) * 2] = c;
                            if (c != '0' || parseDecimal)
{
                                num3 = num2;
                            }
                        }
                        if ((num & 16) == 0)
{
                            number.scale++;
                        }
                        num |= 8;
                    }
                    else if ((num & 16) != 0)
                    {
                        number.scale--;
                    }
                }
                else if ((styles & NumberStyles.AllowDecimalPoint) != NumberStyles.None && (num & 16) == 0 && ((ptr2 = global::System.Number.MatchChars(ptr, strEnd, text2)) != null || (flag && (num & 32) == 0 && (ptr2 = global::System.Number.MatchChars(ptr, strEnd, info.NumberDecimalSeparator)) != null)))
                {
                    num |= 16;
                    ptr = ptr2 - 1;
                }
                else
                {
                    if ((styles & NumberStyles.AllowThousands) == NumberStyles.None || (num & 4) == 0 || (num & 16) != 0 || ((ptr2 = global::System.Number.MatchChars(ptr, strEnd, text3)) == null && (!flag || (num & 32) != 0 || (ptr2 = global::System.Number.MatchChars(ptr, strEnd, info.NumberGroupSeparator)) == null)))
                    {
                        break;
                    }
                    ptr = ptr2 - 1;
                }
                c = ((++ptr < strEnd) ? (*ptr) : '\0');
            }
            bool flag2 = false;
            number.precision = num3;
            number.digits[num3] = '\0';
            if ((num & 4) != 0)
            {
                if ((c == 'E' || c == 'e') && (styles & NumberStyles.AllowExponent) != NumberStyles.None)
                {
                    char* ptr3 = ptr;
                    c = ((++ptr < strEnd) ? (*ptr) : '\0');
                    char* ptr2;
                    if ((ptr2 = global::System.Number.MatchChars(ptr, strEnd, info.positiveSign)) != null)
                    {
                        c = (((ptr = ptr2) < strEnd) ? (*ptr) : '\0');
                    }
                    else if ((ptr2 = global::System.Number.MatchChars(ptr, strEnd, info.negativeSign)) != null)
                    {
                        c = (((ptr = ptr2) < strEnd) ? (*ptr) : '\0');
                        flag2 = true;
                    }
                    if (global::System.Number.IsDigit((int)c))
                    {
                        int num4 = 0;
                        do
{
                            num4 = num4 * 10 + (int)(c - '0');
                            c = ((++ptr < strEnd) ? (*ptr) : '\0');
                            if (num4 > 1000)
{
                                num4 = 9999;
                                while (global::System.Number.IsDigit((int)c))
{
                                    c = ((++ptr < strEnd) ? (*ptr) : '\0');
                                }
                            }
                        }
                        while (global::System.Number.IsDigit((int)c));
                        if (flag2)
{
                            num4 = -num4;
                        }
                        number.scale += num4;
                    }
                    else
                    {
                        ptr = ptr3;
                        c = ((ptr < strEnd) ? (*ptr) : '\0');
                    }
                }
                for (;;)
                {
                    if (!global::System.Number.IsWhite((int)c) || (styles & NumberStyles.AllowTrailingWhite) == NumberStyles.None)
                    {
                        char* ptr2;
                        if ((styles & NumberStyles.AllowTrailingSign) != NumberStyles.None && (num & 1) == 0 && ((ptr2 = global::System.Number.MatchChars(ptr, strEnd, info.PositiveSign)) != null || ((ptr2 = global::System.Number.MatchChars(ptr, strEnd, info.NegativeSign)) != null && (number.sign = true))))
{
                            num |= 1;
                            ptr = ptr2 - 1;
                        }
                        else if (c == ')' && (num & 2) != 0)
{
                            num &= -3;
                        }
                        else
{
                            if (text == null || (ptr2 = global::System.Number.MatchChars(ptr, strEnd, text)) == null)
{
                                break;
                            }
                            text = null;
                            ptr = ptr2 - 1;
                        }
                    }
                    c = ((++ptr < strEnd) ? (*ptr) : '\0');
                }
                if ((num & 2) == 0)
                {
                    if ((num & 8) == 0)
                    {
                        if (!parseDecimal)
{
                            number.scale = 0;
                        }
                        if ((num & 16) == 0)
{
                            number.sign = false;
                        }
                    }
                    str = ptr;
                    return true;
                }
            }
            str = ptr;
            return false;
        }
References System.info, int, System.Number.IsDigit(), System.Number.IsWhite(), System.Number.MatchChars(), and System.text.
Referenced by System.Number.StringToNumber(), and System.Number.TryStringToNumber().