Terraria Decompiled: System.Number.NumberBufferToDouble
NumberBufferToDouble()
static bool System.Number.NumberBufferToDouble (ref global::System::Number::NumberBuffer number, ref double value) inline static private
Definition at line 3850 of file Number.cs.
        {
            double num = global::System.Number.NumberToDouble(ref number);
            if (!double.IsFinite(num))
            {
                value = 0.0;
                return false;
            }
            if (num == 0.0)
            {
                num = 0.0;
            }
            value = num;
            return true;
        }
References System.value.
Referenced by System.Number.ParseDouble(), System.Number.ParseSingle(), and System.Number.TryParseSingle().