Terraria Decompiled: System.Number.ParseDouble
ParseDouble()
static double System.Number.ParseDouble (ReadOnlySpan< char > value, NumberStyles styles, NumberFormatInfo info) inline static package
Definition at line 3657 of file Number.cs.
        {
            global::System.Number.NumberBuffer numberBuffer = default(global::System.Number.NumberBuffer);
            double num = 0.0;
            if (!global::System.Number.TryStringToNumber(value, styles, ref numberBuffer, info, false))
            {
                ReadOnlySpan<char> readOnlySpan = value.Trim();
                if (readOnlySpan.EqualsOrdinal(info.PositiveInfinitySymbol))
                {
                    return double.PositiveInfinity;
                }
                if (readOnlySpan.EqualsOrdinal(info.NegativeInfinitySymbol))
                {
                    return double.NegativeInfinity;
                }
                if (readOnlySpan.EqualsOrdinal(info.NaNSymbol))
                {
                    return double.NaN;
                }
                global::System.Number.ThrowOverflowOrFormatException(false, null);
            }
            if (!global::System.Number.NumberBufferToDouble(ref numberBuffer, ref num))
            {
                global::System.Number.ThrowOverflowOrFormatException(true, "Value was either too large or too small for a Double.");
            }
            return num;
        }
References System.info, System.Number.NumberBufferToDouble(), System.Number.TryStringToNumber(), and System.value.
Referenced by System.Double.Parse(), System.Double.Parse(), System.Double.Parse(), System.Double.Parse(), and System.Double.Parse().