Terraria Decompiled: System.Number.TryParseUInt64HexNumberStyle
TryParseUInt64HexNumberStyle()
static unsafe bool System.Number.TryParseUInt64HexNumberStyle (ReadOnlySpan< char > value, NumberStyles styles, NumberFormatInfo info, out ulong result, ref bool failureIsOverflow) inline static private
Definition at line 3422 of file Number.cs.
        {
            if (value.Length >= 1)
            {
                bool flag = false;
                int num = 0;
                int i = (int)(*value[0]);
                if ((styles & NumberStyles.AllowLeadingWhite) != NumberStyles.None && global::System.Number.IsWhite(i))
                {
                    do
                    {
                        num++;
                        if (num >= value.Length)
{
                            goto IL_0179;
                        }
                        i = (int)(*value[num]);
                    }
                    while (global::System.Number.IsWhite(i));
                }
                long num2 = 0L;
                int[] array = global::System.Number.s_charToHexLookup;
                if (i < array.Length && array[i] != 255)
                {
                    if (i == 48)
                    {
                        do
{
                            num++;
                            if (num >= value.Length)
{
                                goto IL_0188;
                            }
                            i = (int)(*value[num]);
                        }
                        while (i == 48);
                        if (i >= array.Length || array[i] == 255)
{
                            goto IL_018E;
                        }
                    }
                    num2 = (long)array[i];
                    num++;
                    for (int j = 0; j < 15; j++)
                    {
                        if (num >= value.Length)
{
                            goto IL_0188;
                        }
                        i = (int)(*value[num]);
                        int num3;
                        if (i >= array.Length || (num3 = array[i]) == 255)
{
                            goto IL_018E;
                        }
                        num++;
                        num2 = 16L * num2 + (long)num3;
                    }
                    if (num >= value.Length)
                    {
                        goto IL_0188;
                    }
                    i = (int)(*value[num]);
                    if (i >= array.Length || array[i] == 255)
                    {
                        goto IL_018E;
                    }
                    num++;
                    flag = true;
                    if (num < value.Length)
                    {
                        for (i = (int)(*value[num]); i < array.Length; i = (int)(*value[num]))
{
                            if (array[i] == 255)
{
                                break;
                            }
                            num++;
                            if (num >= value.Length)
{
                                goto IL_017F;
                            }
                        }
                        goto IL_018E;
                    }
                    IL_017F:
                    if (flag)
                    {
                        failureIsOverflow = true;
                        goto IL_0179;
                    }
                    IL_0188:
                    result = (ulong)num2;
                    return true;
                    IL_018E:
                    if (global::System.Number.IsWhite(i))
                    {
                        if ((styles & NumberStyles.AllowTrailingWhite) == NumberStyles.None)
{
                            goto IL_0179;
                        }
                        num++;
                        while (num < value.Length && global::System.Number.IsWhite((int)(*value[num])))
{
                            num++;
                        }
                        if (num >= value.Length)
{
                            goto IL_017F;
                        }
                    }
                    if (global::System.Number.TrailingZeros(value, num))
                    {
                        goto IL_017F;
                    }
                }
            }
            IL_0179:
            result = 0UL;
            return false;
        }
References System.array, int, System.Number.IsWhite(), System.L, long, System.Number.TrailingZeros(), and System.value.
Referenced by System.Number.ParseInt64(), and System.Number.ParseUInt64().