Terraria Decompiled: System.Number.TryParseSingle
TryParseSingle()
static bool System.Number.TryParseSingle (ReadOnlySpan< char > value, NumberStyles styles, NumberFormatInfo info, out float result) inline static package
Definition at line 3736 of file Number.cs.
        {
            global::System.Number.NumberBuffer numberBuffer = default(global::System.Number.NumberBuffer);
            result = 0f;
            double num = 0.0;
            if (!global::System.Number.TryStringToNumber(value, styles, ref numberBuffer, info, false))
            {
                return false;
            }
            if (!global::System.Number.NumberBufferToDouble(ref numberBuffer, ref num))
            {
                return false;
            }
            float num2 = (float)num;
            if (float.IsInfinity(num2))
            {
                return false;
            }
            result = num2;
            return true;
        }
References System.info, System.Number.NumberBufferToDouble(), System.Number.TryStringToNumber(), and System.value.
Referenced by System.Single.TryParse().