Terraria Decompiled: System.Number.TryFormatInt32
TryFormatInt32()
static unsafe bool System.Number.TryFormatInt32 (int value, ReadOnlySpan< char > format, IFormatProvider provider, Span< char > destination, out int charsWritten) inline static
Definition at line 366 of file Number.cs.
        {
            if (value >= 0 && format.Length == 0)
            {
                return global::System.Number.TryUInt32ToDecStr((uint)value, -1, destination, out charsWritten);
            }
            int num;
            char c = global::System.Number.ParseFormatSpecifier(format, out num);
            NumberFormatInfo instance = NumberFormatInfo.GetInstance(provider);
            char c2 = c & '\uffdf';
            if ((c2 == 'G' && num < 1) || c2 == 'D')
            {
                if (value < 0)
                {
                    return global::System.Number.TryNegativeInt32ToDecStr(value, num, instance.NegativeSign, destination, out charsWritten);
                }
                return global::System.Number.TryUInt32ToDecStr((uint)value, num, destination, out charsWritten);
            }
            else
            {
                if (c2 == 'X')
                {
                    return global::System.Number.TryInt32ToHexStr(value, c - '!', num, destination, out charsWritten);
                }
                global::System.Number.NumberBuffer numberBuffer = default(global::System.Number.NumberBuffer);
                global::System.Number.Int32ToNumber(value, ref numberBuffer);
                char* ptr = stackalloc char[(UIntPtr)64];
                ValueStringBuilder valueStringBuilder = new ValueStringBuilder(new Span<char>((void*)ptr, 32));
                if (c != '\0')
                {
                    global::System.Number.NumberToString(ref valueStringBuilder, ref numberBuffer, c, num, instance, false);
                }
                else
                {
                    global::System.Number.NumberToStringFormat(ref valueStringBuilder, ref numberBuffer, format, instance);
                }
                return valueStringBuilder.TryCopyTo(destination, out charsWritten);
            }
        }
References System.destination, System.format, System.Globalization.NumberFormatInfo.GetInstance(), System.Globalization.NumberFormatInfo.NegativeSign, and System.value.
Referenced by System.Byte.TryFormat(), System.Int16.TryFormat(), System.Int32.TryFormat(), and System.SByte.TryFormat().