Terraria Decompiled: System.Number.TryParseUInt64IntegerStyle
TryParseUInt64IntegerStyle()
static unsafe bool System.Number.TryParseUInt64IntegerStyle (ReadOnlySpan< char > value, NumberStyles styles, NumberFormatInfo info, out ulong result, ref bool failureIsOverflow) inline static private
Definition at line 3248 of file Number.cs.
        {
            if (value.Length >= 1)
            {
                bool flag = false;
                bool flag2 = false;
                int num = 0;
                int num2 = (int)(*value[0]);
                if ((styles & NumberStyles.AllowLeadingWhite) != NumberStyles.None && global::System.Number.IsWhite(num2))
                {
                    do
                    {
                        num++;
                        if (num >= value.Length)
{
                            goto IL_0272;
                        }
                        num2 = (int)(*value[num]);
                    }
                    while (global::System.Number.IsWhite(num2));
                }
                if ((styles & NumberStyles.AllowLeadingSign) != NumberStyles.None)
                {
                    string positiveSign = info.PositiveSign;
                    string negativeSign = info.NegativeSign;
                    if (positiveSign == "+" && negativeSign == "-")
                    {
                        if (num2 == 43)
{
                            num++;
                            if (num >= value.Length)
{
                                goto IL_0272;
                            }
                            num2 = (int)(*value[num]);
                        }
                        else if (num2 == 45)
{
                            flag2 = true;
                            num++;
                            if (num >= value.Length)
{
                                goto IL_0272;
                            }
                            num2 = (int)(*value[num]);
                        }
                    }
                    else
                    {
                        value = value.Slice(num);
                        num = 0;
                        if (!string.IsNullOrEmpty(positiveSign) && value.StartsWith(positiveSign))
{
                            num += positiveSign.Length;
                            if (num >= value.Length)
{
                                goto IL_0272;
                            }
                            num2 = (int)(*value[num]);
                        }
                        else if (!string.IsNullOrEmpty(negativeSign) && value.StartsWith(negativeSign))
{
                            flag2 = true;
                            num += negativeSign.Length;
                            if (num >= value.Length)
{
                                goto IL_0272;
                            }
                            num2 = (int)(*value[num]);
                        }
                    }
                }
                long num3 = 0L;
                if (global::System.Number.IsDigit(num2))
                {
                    if (num2 == 48)
                    {
                        do
{
                            num++;
                            if (num >= value.Length)
{
                                goto IL_0278;
                            }
                            num2 = (int)(*value[num]);
                        }
                        while (num2 == 48);
                        if (!global::System.Number.IsDigit(num2))
{
                            goto IL_028E;
                        }
                    }
                    num3 = (long)(num2 - 48);
                    num++;
                    for (int i = 0; i < 18; i++)
                    {
                        if (num >= value.Length)
{
                            goto IL_0278;
                        }
                        num2 = (int)(*value[num]);
                        if (!global::System.Number.IsDigit(num2))
{
                            goto IL_028E;
                        }
                        num++;
                        num3 = 10L * num3 + (long)num2 - 48L;
                    }
                    if (num < value.Length)
                    {
                        num2 = (int)(*value[num]);
                        if (!global::System.Number.IsDigit(num2))
{
                            goto IL_028E;
                        }
                        num++;
                        if (num3 > 1844674407370955161L || (num3 == 1844674407370955161L && num2 > 53))
{
                            flag = true;
                        }
                        num3 = num3 * 10L + (long)num2 - 48L;
                        if (num < value.Length)
{
                            num2 = (int)(*value[num]);
                            while (global::System.Number.IsDigit(num2))
{
                                flag = true;
                                num++;
                                if (num >= value.Length)
{
                                    goto IL_0278;
                                }
                                num2 = (int)(*value[num]);
                            }
                            goto IL_028E;
                        }
                    }
                    IL_0278:
                    if (flag || (flag2 && num3 != 0L))
                    {
                        failureIsOverflow = true;
                        goto IL_0272;
                    }
                    result = (ulong)num3;
                    return true;
                    IL_028E:
                    if (global::System.Number.IsWhite(num2))
                    {
                        if ((styles & NumberStyles.AllowTrailingWhite) == NumberStyles.None)
{
                            goto IL_0272;
                        }
                        num++;
                        while (num < value.Length && global::System.Number.IsWhite((int)(*value[num])))
{
                            num++;
                        }
                        if (num >= value.Length)
{
                            goto IL_0278;
                        }
                    }
                    if (global::System.Number.TrailingZeros(value, num))
                    {
                        goto IL_0278;
                    }
                }
            }
            IL_0272:
            result = 0UL;
            return false;
        }
References System.info, int, System.Number.IsDigit(), System.Number.IsWhite(), System.L, long, System.Number.TrailingZeros(), and System.value.
Referenced by System.Number.ParseUInt64().