Terraria Decompiled: System.Number.ParseInt64
ParseInt64()
static long System.Number.ParseInt64 (ReadOnlySpan< char > value, NumberStyles styles, NumberFormatInfo info) inline static package
Definition at line 2237 of file Number.cs.
        {
            if ((styles & ~(NumberStyles.AllowLeadingWhite | NumberStyles.AllowTrailingWhite | NumberStyles.AllowLeadingSign)) == NumberStyles.None)
            {
                bool flag = false;
                long num;
                if (!global::System.Number.TryParseInt64IntegerStyle(value, styles, info, out num, ref flag))
                {
                    global::System.Number.ThrowOverflowOrFormatException(flag, "Value was either too large or too small for an Int64.");
                }
                return num;
            }
            if ((styles & NumberStyles.AllowHexSpecifier) != NumberStyles.None)
            {
                bool flag2 = false;
                ulong num2;
                if (!global::System.Number.TryParseUInt64HexNumberStyle(value, styles, info, out num2, ref flag2))
                {
                    global::System.Number.ThrowOverflowOrFormatException(flag2, "Value was either too large or too small for an Int64.");
                }
                return (long)num2;
            }
            global::System.Number.NumberBuffer numberBuffer = default(global::System.Number.NumberBuffer);
            long num3 = 0L;
            global::System.Number.StringToNumber(value, styles, ref numberBuffer, info, false);
            if (!global::System.Number.NumberToInt64(ref numberBuffer, ref num3))
            {
                global::System.Number.ThrowOverflowOrFormatException(true, "Value was either too large or too small for an Int64.");
            }
            return num3;
        }
References System.info, System.L, System.Number.NumberToInt64(), System.Number.TryParseInt64IntegerStyle(), System.Number.TryParseUInt64HexNumberStyle(), and System.value.
Referenced by System.Int64.Parse(), System.Int64.Parse(), System.Int64.Parse(), System.Int64.Parse(), and System.Int64.Parse().