Terraria Decompiled: System.Security.Cryptography.Utils.HasAlgorithm
HasAlgorithm()
static bool System.Security.Cryptography.Utils.HasAlgorithm (int dwCalg, int dwKeySize) inline static package
Definition at line 39 of file Utils.cs.
        {
            return true;
        }
Referenced by System.Security.Cryptography.DESCryptoServiceProvider.DESCryptoServiceProvider(), System.Security.Cryptography.RC2CryptoServiceProvider.RC2CryptoServiceProvider(), and System.Security.Cryptography.TripleDESCryptoServiceProvider.TripleDESCryptoServiceProvider().