Terraria Decompiled: Terraria.Projectile.AI_203_StormLightning
AI_203_StormLightning()
void Terraria.Projectile.AI_203_StormLightning () inline private
Definition at line 40042 of file Projectile.cs.
        {
            int num = 240;
            int num2;
            int num3;
            this.UnpackTargetIndex(this.ai[0], out num2, out num3);
            bool flag = num2 != -1 || num3 != -1;
            if (num2 != -1)
            {
                NPC npc = Main.npc[num2];
                if (!npc.active || npc.dontTakeDamage || this.AI_203_TooFar(npc))
                {
                    num2 = -1;
                }
            }
            if (num3 != -1)
            {
                Player player = Main.player[num3];
                if (!player.active || player.dead || this.AI_203_TooFar(player) || player.dashDelay < 0)
                {
                    num3 = -1;
                }
            }
            if (flag && num2 == -1 && num3 == -1)
            {
                this.Kill();
                return;
            }
            float num4 = this.ai[1];
            if (num2 == -1 && num3 == -1)
            {
                Entity entity = null;
                float num5 = 32f;
                float num6 = (float)((Main.Difficulty < GameDifficultyLevel.Legendary) ? 14 : 32);
                int num7 = ((Main.Difficulty < GameDifficultyLevel.Legendary) ? 5 : 0);
                int num8 = 0;
                while (num8 < Main.maxNPCs && entity == null)
                {
                    NPC npc2 = Main.npc[num8];
                    if (npc2.active && !npc2.dontTakeDamage && base.Distance(npc2.Hitbox.ClosestPointInRect(base.Center)) <= num5)
                    {
                        entity = npc2;
                        num2 = npc2.whoAmI;
                    }
                    num8++;
                }
                bool flag2 = this.localAI[2] >= (float)num7;
                int num9 = 0;
                while (num9 < 255 && entity == null)
                {
                    Player player2 = Main.player[num9];
                    if (player2.active && !player2.dead && base.Distance(player2.Hitbox.ClosestPointInRect(base.Center)) <= num6)
                    {
                        if (!flag2)
{
                            this.localAI[2] += 1f;
                            break;
                        }
                        entity = player2;
                        num3 = player2.whoAmI;
                    }
                    num9++;
                }
                if (entity != null)
                {
                    this.ai[0] = (float)this.PackTargetIndex(num2, num3);
                    this.netUpdate = true;
                }
            }
            Vector2 vector = base.Center;
            Vector2 vector2 = Vector2.Zero;
            if (num2 != -1)
            {
                vector = Main.npc[num2].Center;
                vector2 = Main.npc[num2].velocity;
            }
            if (num3 != -1)
            {
                vector = Main.player[num3].Center;
                vector2 = Main.player[num3].velocity;
            }
            base.Center = base.Center.MoveTowards(vector, 32f);
            this.ai[1] += 1f;
            if (this.ai[1] >= (float)num)
            {
                this.Kill();
            }
            float num10 = this.ai[1] / (float)num;
            float num11 = Utils.Remap(num10, 0f, 0.5f, 0f, 1f, true);
            float num12 = (float)Math.Sqrt(1.0 - Math.Pow((double)(num11 - 1f), 2.0)) * 0.3f;
            Color color = this.AI_203_GetLightningColor();
            Vector3 vector3 = color.ToVector3() * num12;
            Lighting.AddLight(base.Center, vector3);
            if (this.ai[1] == (float)((int)((float)num * 0.15f)))
            {
                SoundEngine.PlaySound(SoundID.NPCHit34, base.Center, 0f, 1f);
                for (int i = 0; i < 5; i++)
                {
                    ParticleOrchestrator.RequestParticleSpawn(true, ParticleOrchestraType.StormlightningWindup, new ParticleOrchestraSettings
                    {
                        PositionInWorld = base.Center,
                        MovementVector = vector2,
                        UniqueInfoPiece = (int)color.PackedValue
                    }, null);
                }
            }
            if (Main.rand.NextFloat() <= num10 * 0.2f)
            {
                ParticleOrchestrator.RequestParticleSpawn(true, ParticleOrchestraType.StormlightningWindup, new ParticleOrchestraSettings
                {
                    PositionInWorld = base.Center,
                    MovementVector = vector2,
                    UniqueInfoPiece = (int)color.PackedValue
                }, null);
            }
            for (int j = 0; j < 3; j++)
            {
                if (Main.rand.Next(4) == 0 && Main.rand.NextFloat() <= num11 * num11 * 0.13f)
                {
                    Dust dust = Dust.NewDustDirect(this.position, this.width, this.height, 306, 0f, 0f, 0, new Color((int)color.R, (int)color.G, (int)color.B, 0), 1f);
                    dust.velocity = new Vector2(0f, -4f).RotatedByRandom(1.5707963705062866) * (0.5f + 0.2f * Main.rand.NextFloatDirection());
                    dust.scale = 1.8f;
                    dust.fadeIn = 0f;
                    dust.noGravity = Main.rand.Next(3) != 0;
                    dust.noLight = (dust.noLightEmittance = true);
                    Dust dust2 = Dust.CloneDust(dust);
                    dust2.color = new Color(255, 255, 255, 0);
                    dust2.scale = 1.3f;
                }
            }
            float num13 = Utils.Remap(num10, 0.7f, 1f, 0f, 1f, true);
            for (int k = -1; k <= 1; k += 2)
            {
                if (Main.rand.Next(4) == 0 && Main.rand.NextFloat() <= num13 * 0.2f)
                {
                    Dust dust3 = Dust.NewDustPerfect(base.Center, 306, new Vector2?(new Vector2(0f, -4f).RotatedBy((double)(0.7853982f * (float)k * (1f - num13)), default(Vector2))), 0, default(Color), 1f);
                    dust3.color = new Color((int)color.R, (int)color.G, (int)color.B, 0);
                    dust3.scale = 1.8f;
                    dust3.fadeIn = 0f;
                    dust3.noGravity = Main.rand.Next(3) != 0;
                    dust3.noLight = (dust3.noLightEmittance = true);
                    Dust dust4 = Dust.CloneDust(dust3);
                    dust4.color = new Color(255, 255, 255, 0);
                    dust4.scale = 1.3f;
                }
            }
            for (int l = 0; l < 2; l++)
            {
                if (Main.rand.Next(4) == 0 && Main.rand.NextFloat() <= 0.2f)
                {
                    Dust dust5 = Dust.NewDustPerfect(base.Center, 226, null, 0, default(Color), 1f);
                    dust5.HackFrame(278);
                    dust5.color = color;
                    dust5.customData = dust5.color;
                    dust5.velocity *= 1f + Main.rand.NextFloat() * 2.5f;
                    dust5.velocity += new Vector2(0f, -2f);
                    dust5.fadeIn = 0f;
                    dust5.scale = 0.4f + Main.rand.NextFloat() * 0.5f;
                    Dust dust6 = dust5;
                    dust6.velocity.X = dust6.velocity.X * 2f;
                    dust5.velocity = Main.rand.NextVector2Circular(3f, 2f) + new Vector2(0f, -2f);
                    dust5.noLight = (dust5.noLightEmittance = true);
                    dust5.position -= dust5.velocity * 3f;
                }
            }
        }
References Terraria.NPC.active, Terraria.Player.active, Terraria.Lighting.AddLight(), Microsoft.Xna.Framework.Color.B, Terraria.Entity.Center, Terraria.Dust.CloneDust(), Terraria.Dust.color, Terraria.Player.dashDelay, Terraria.Player.dead, Terraria.Main.Difficulty, Terraria.NPC.dontTakeDamage, Microsoft.Xna.Framework.Color.G, Terraria.Dust.HackFrame(), Terraria.Entity.Hitbox, Terraria.DataStructures.GameDifficultyLevel.Legendary, Terraria.Main.maxNPCs, Terraria.Dust.NewDustDirect(), Terraria.Dust.NewDustPerfect(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.npc, Terraria.ID.SoundID.NPCHit34, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), System.Math.Pow(), Microsoft.Xna.Framework.Color.R, Terraria.Main.rand, Terraria.Utils.Remap(), Terraria.GameContent.Drawing.ParticleOrchestrator.RequestParticleSpawn(), System.Math.Sqrt(), Microsoft.Xna.Framework.Color.ToVector3(), Terraria.Entity.velocity, Terraria.Entity.whoAmI, and Microsoft.Xna.Framework.Vector2.Zero.