Terraria Decompiled: Terraria.Projectile.AI_167_SparkleGuitar
AI_167_SparkleGuitar()
void Terraria.Projectile.AI_167_SparkleGuitar () inline private
Definition at line 46949 of file Projectile.cs.
        {
            float num = 90f;
            float[] array = this.localAI;
            int num2 = 0;
            float num3 = array[num2] + 1f;
            array[num2] = num3;
            if (num3 >= num - 1f)
            {
                this.Kill();
                return;
            }
            float num4 = this.localAI[0] / num;
            Vector2 center = Main.player[this.owner].Center;
            Vector2 vector = new Vector2(this.ai[0], this.ai[1]);
            Vector2 vector2 = -this.velocity;
            Vector2 vector3 = center + vector2 * 2f;
            Vector2 vector4 = vector + vector2 * (1f - num4 * 3f);
            base.Center = Vector2.CatmullRom(vector3, center, vector, vector4, num4);
            int num5 = this.type;
            if (num5 == 856)
            {
                Lighting.AddLight(base.Center, Color.HotPink.ToVector3() * 0.3f);
                this.rotation = 6.2831855f * num4 * 1f;
            }
        }
References Terraria.Lighting.AddLight(), System.array, Microsoft.Xna.Framework.Vector2.CatmullRom(), Terraria.Entity.Center, Microsoft.Xna.Framework.Color.HotPink, Terraria.Main.player, and Microsoft.Xna.Framework.Color.ToVector3().