Terraria Decompiled: Terraria.Projectile.BombsHurtPlayers
BombsHurtPlayers()
void Terraria.Projectile.BombsHurtPlayers (Rectangle projRectangle) inline private
Definition at line 13958 of file Projectile.cs.
        {
            Player localPlayer = Main.LocalPlayer;
            if (!localPlayer.active || localPlayer.dead || localPlayer.immune)
            {
                return;
            }
            if (this.ownerHitCheck && !this.CanHitWithMeleeWeapon(localPlayer))
            {
                return;
            }
            if (!projRectangle.Intersects(localPlayer.Hitbox))
            {
                return;
            }
            this.direction = ((localPlayer.Center.X < base.Center.X) ? (-1) : 1);
            int num = Main.DamageVar((float)this.damage, -localPlayer.luck);
            if (localPlayer.deadMansSweater && this.trap)
            {
                num = (int)((float)num * 0.5f);
                num = Math.Min(num, 300);
            }
            int num2 = this.owner;
            bool flag = true;
            if (this.type == 108 || this.type == 1002)
            {
                num2 = -1;
                flag = false;
            }
            if (ProjectileID.Sets.IsAGravestone[this.type])
            {
                num2 = (int)this.ai[0];
            }
            bool flag2 = this.IsDamageDodgeable();
            PlayerDeathReason playerDeathReason = PlayerDeathReason.ByProjectile(num2, this.whoAmI);
            if (localPlayer.Hurt(playerDeathReason, num, this.direction, flag, false, false, -1, flag2) > 0.0 && !localPlayer.dead)
            {
                this.StatusPlayer(localPlayer);
            }
            if (this.trap)
            {
                localPlayer.trapDebuffSource = true;
                if (localPlayer.dead)
                {
                    AchievementsHelper.HandleSpecialEvent(localPlayer, 4);
                }
            }
        }
References Terraria.Player.active, Terraria.DataStructures.PlayerDeathReason.ByProjectile(), Terraria.Main.DamageVar(), Terraria.Player.dead, Terraria.Player.deadMansSweater, Terraria.GameContent.Achievements.AchievementsHelper.HandleSpecialEvent(), Terraria.Entity.Hitbox, Terraria.Player.Hurt(), Terraria.Player.immune, int, Microsoft.Xna.Framework.Rectangle.Intersects(), Terraria.ID.ProjectileID.Sets.IsAGravestone, Terraria.Main.LocalPlayer, Terraria.Player.luck, and System.Math.Min().