Terraria Decompiled: Terraria.Projectile.SpawnMoonLordWhipProc
SpawnMoonLordWhipProc()
static void Terraria.Projectile.SpawnMoonLordWhipProc (Projectile parent, NPC targetNPC, int procDamage, int aiCounter) inline static
Definition at line 13843 of file Projectile.cs.
        {
            int num = Main.rand.Next(1, 4);
            num = 1;
            for (int i = 0; i < num; i++)
            {
                Rectangle hitbox = targetNPC.Hitbox;
                hitbox.Inflate(30, 16);
                hitbox.Y -= 8;
                Vector2 vector = Main.rand.NextVector2FromRectangle(hitbox);
                Vector2 vector2 = hitbox.Center.ToVector2();
                float num2 = 7f + Main.rand.NextFloat() * 8f;
                Vector2 vector3 = (vector2 - vector).SafeNormalize(parent.velocity.SafeNormalize(-Vector2.UnitY)) * num2;
                float num3 = (float)(Main.rand.Next(2) * 2 - 1) * (0.62831855f + 2.5132742f * Main.rand.NextFloat());
                num3 *= 0.5f;
                vector3 = vector3.RotatedBy(0.7853981852531433, default(Vector2));
                int num4 = 1;
                int num5 = 24 * num4;
                int num6 = 16;
                int num7 = num6 * num4;
                vector = vector2;
                for (int j = 0; j < num7; j++)
                {
                    vector -= vector3;
                    vector3 = vector3.RotatedBy((double)(-(double)num3 / (float)num5), default(Vector2));
                }
                vector += targetNPC.velocity * (float)num6;
                ParticleOrchestrator.RequestParticleSpawn(false, ParticleOrchestraType.MoonLordWhipEye, new ParticleOrchestraSettings
                {
                    PositionInWorld = vector,
                    MovementVector = -vector3
                }, new int?(parent.owner));
                Projectile.NewProjectile(parent.GetProjectileSource_FromThis(), vector, vector3, 1045, procDamage, 0f, parent.owner, num3, (float)aiCounter, 0f, null);
            }
        }
References Microsoft.Xna.Framework.Rectangle.Center, Terraria.Projectile.GetProjectileSource_FromThis(), Terraria.Entity.Hitbox, Microsoft.Xna.Framework.Rectangle.Inflate(), Terraria.Projectile.NewProjectile(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Projectile.owner, Terraria.Main.rand, Terraria.GameContent.Drawing.ParticleOrchestrator.RequestParticleSpawn(), Microsoft.Xna.Framework.Vector2.UnitY, and Terraria.Entity.velocity.
Referenced by Terraria.Projectile.Damage_PVE_Inner(), and Terraria.GameContent.Items.WhipTagEffect_Possession.OnProcHit().