Terraria Decompiled: Terraria.Projectile.AI_156_Think
AI_156_Think()
void Terraria.Projectile.AI_156_Think (List< int > blacklist) inline private
Definition at line 51899 of file Projectile.cs.
        {
            bool flag = this.type == 755;
            bool flag2 = this.type == 946;
            int num = 60;
            int num2 = num - 1;
            int num3 = num + 60;
            int num4 = num3 - 1;
            int num5 = num + 1;
            if (flag)
            {
                num = 66;
            }
            if (flag2)
            {
                num = 40;
                num2 = num - 1;
                num3 = num + 40;
                num4 = num3 - 1;
                num5 = num + 1;
            }
            Player player = Main.player[this.owner];
            if (player.active && Vector2.Distance(player.Center, base.Center) > 2000f)
            {
                this.ai[0] = 0f;
                this.ai[1] = 0f;
                this.netUpdate = true;
            }
            if (this.ai[0] == -1f)
            {
                int num6;
                int num7;
                this.AI_GetMyGroupIndexAndFillBlackList(blacklist, out num6, out num7);
                Vector2 vector;
                float num8;
                this.AI_156_GetIdlePosition(num6, num7, out vector, out num8);
                this.velocity = Vector2.Zero;
                base.Center = base.Center.MoveTowards(vector, 32f);
                this.rotation = this.rotation.AngleLerp(num8, 0.2f);
                if (base.Distance(vector) < 2f)
                {
                    this.ai[0] = 0f;
                    this.netUpdate = true;
                    return;
                }
            }
            else if (this.ai[0] == 0f)
            {
                if (flag)
                {
                    int num9;
                    int num10;
                    this.AI_GetMyGroupIndexAndFillBlackList(blacklist, out num9, out num10);
                    Vector2 vector2;
                    float num11;
                    this.AI_156_GetIdlePosition(num9, num10, out vector2, out num11);
                    this.velocity = Vector2.Zero;
                    base.Center = Vector2.SmoothStep(base.Center, vector2, 0.45f);
                    if (Main.rand.Next(20) == 0)
                    {
                        int num12 = this.AI_156_TryAttackingNPCs(blacklist, false);
                        if (num12 != -1)
{
                            this.AI_156_StartAttack();
                            this.ai[0] = (float)num;
                            this.ai[1] = (float)num12;
                            this.netUpdate = true;
                            return;
                        }
                    }
                }
                if (flag2)
                {
                    int num13;
                    int num14;
                    this.AI_GetMyGroupIndexAndFillBlackList(blacklist, out num13, out num14);
                    Vector2 vector3;
                    float num15;
                    this.AI_156_GetIdlePosition(num13, num14, out vector3, out num15);
                    this.velocity = Vector2.Zero;
                    base.Center = Vector2.SmoothStep(base.Center, vector3, 0.45f);
                    this.rotation = this.rotation.AngleLerp(num15, 0.45f);
                    if (Main.rand.Next(20) == 0)
                    {
                        int num16 = this.AI_156_TryAttackingNPCs(blacklist, false);
                        if (num16 != -1)
{
                            this.AI_156_StartAttack();
                            this.ai[0] = (float)Main.rand.NextFromList(new int[] { num, num3 });
                            this.ai[0] = (float)num3;
                            this.ai[1] = (float)num16;
                            this.netUpdate = true;
                            return;
                        }
                    }
                }
            }
            else
            {
                if (flag)
                {
                    int num17 = (int)this.ai[1];
                    if (!Main.npc.IndexInRange(num17))
                    {
                        this.ai[0] = 0f;
                        this.netUpdate = true;
                        return;
                    }
                    NPC npc = Main.npc[num17];
                    if (!npc.CanBeChasedBy(this, false))
                    {
                        this.ai[0] = 0f;
                        this.netUpdate = true;
                        return;
                    }
                    this.ai[0] -= 1f;
                    if (this.ai[0] >= (float)num2)
                    {
                        this.velocity *= 0.8f;
                        if (this.ai[0] == (float)num2)
{
                            this.localAI[0] = base.Center.X;
                            this.localAI[1] = base.Center.Y;
                        }
                        return;
                    }
                    float lerpValue = Utils.GetLerpValue((float)num2, 0f, this.ai[0], true);
                    Vector2 center = new Vector2(this.localAI[0], this.localAI[1]);
                    if (lerpValue >= 0.5f)
                    {
                        center = Main.player[this.owner].Center;
                    }
                    Vector2 center2 = npc.Center;
                    float num18 = (center2 - center).ToRotation();
                    float num19 = ((center2.X > center.X) ? (-3.1415927f) : 3.1415927f);
                    float num20 = num19 + -num19 * lerpValue * 2f;
                    Vector2 vector4 = num20.ToRotationVector2();
                    vector4.Y *= (float)Math.Sin((double)((float)this.identity * 2.3f)) * 0.5f;
                    vector4 = vector4.RotatedBy((double)num18, default(Vector2));
                    float num21 = (center2 - center).Length() / 2f;
                    Vector2 vector5 = Vector2.Lerp(center, center2, 0.5f) + vector4 * num21;
                    base.Center = vector5;
                    Vector2 vector6 = MathHelper.WrapAngle(num18 + num20 + 0f).ToRotationVector2() * 10f;
                    this.velocity = vector6;
                    this.position -= this.velocity;
                    if (this.ai[0] == 0f)
                    {
                        int num22 = this.AI_156_TryAttackingNPCs(blacklist, false);
                        if (num22 != -1)
{
                            this.ai[0] = (float)num;
                            this.ai[1] = (float)num22;
                            this.AI_156_StartAttack();
                            this.netUpdate = true;
                            return;
                        }
                        this.ai[1] = 0f;
                        this.netUpdate = true;
                    }
                }
                if (flag2)
                {
                    bool flag3 = true;
                    int num23 = 0;
                    int num24 = num2;
                    int num25 = 0;
                    if (this.ai[0] >= (float)num5)
                    {
                        num23 = 1;
                        num24 = num4;
                        num25 = num5;
                    }
                    int num26 = (int)this.ai[1];
                    if (!Main.npc.IndexInRange(num26))
                    {
                        int num27 = this.AI_156_TryAttackingNPCs(blacklist, flag3);
                        if (num27 != -1)
{
                            this.ai[0] = (float)Main.rand.NextFromList(new int[] { num, num3 });
                            this.ai[1] = (float)num27;
                            this.AI_156_StartAttack();
                            this.netUpdate = true;
                            return;
                        }
                        this.ai[0] = -1f;
                        this.ai[1] = 0f;
                        this.netUpdate = true;
                        return;
                    }
                    else
                    {
                        NPC npc2 = Main.npc[num26];
                        if (!npc2.CanBeChasedBy(this, false))
{
                            int num28 = this.AI_156_TryAttackingNPCs(blacklist, flag3);
                            if (num28 != -1)
{
                                this.ai[0] = (float)Main.rand.NextFromList(new int[] { num, num3 });
                                this.AI_156_StartAttack();
                                this.ai[1] = (float)num28;
                                this.netUpdate = true;
                                return;
                            }
                            this.ai[0] = -1f;
                            this.ai[1] = 0f;
                            this.netUpdate = true;
                            return;
                        }
                        else
{
                            this.ai[0] -= 1f;
                            if (this.ai[0] >= (float)num24)
{
                                this.direction = ((base.Center.X < npc2.Center.X) ? 1 : (-1));
                                if (this.ai[0] == (float)num24)
{
                                    this.localAI[0] = base.Center.X;
                                    this.localAI[1] = base.Center.Y;
                                }
                            }
                            float lerpValue2 = Utils.GetLerpValue((float)num24, (float)num25, this.ai[0], true);
                            if (num23 == 0)
{
                                Vector2 vector7 = new Vector2(this.localAI[0], this.localAI[1]);
                                if (lerpValue2 >= 0.5f)
{
                                    vector7 = Vector2.Lerp(npc2.Center, Main.player[this.owner].Center, 0.5f);
                                }
                                Vector2 center3 = npc2.Center;
                                float num29 = (center3 - vector7).ToRotation();
                                float num30 = ((this.direction == 1) ? (-3.1415927f) : 3.1415927f);
                                float num31 = num30 + -num30 * lerpValue2 * 2f;
                                Vector2 vector8 = num31.ToRotationVector2();
                                vector8.Y *= 0.5f;
                                vector8.Y *= 0.8f + (float)Math.Sin((double)((float)this.identity * 2.3f)) * 0.2f;
                                vector8 = vector8.RotatedBy((double)num29, default(Vector2));
                                float num32 = (center3 - vector7).Length() / 2f;
                                Vector2 vector9 = Vector2.Lerp(vector7, center3, 0.5f) + vector8 * num32;
                                base.Center = vector9;
                                float num33 = MathHelper.WrapAngle(num29 + num31 + 0f);
                                this.rotation = num33 + 1.5707964f;
                                Vector2 vector10 = num33.ToRotationVector2() * 10f;
                                this.velocity = vector10;
                                this.position -= this.velocity;
                            }
                            if (num23 == 1)
{
                                Vector2 vector11 = new Vector2(this.localAI[0], this.localAI[1]);
                                vector11 += new Vector2(0f, Utils.GetLerpValue(0f, 0.4f, lerpValue2, true) * -100f);
                                Vector2 vector12 = npc2.Center - vector11;
                                Vector2 vector13 = vector12.SafeNormalize(Vector2.Zero) * MathHelper.Clamp(vector12.Length(), 60f, 150f);
                                Vector2 vector14 = npc2.Center + vector13;
                                float lerpValue3 = Utils.GetLerpValue(0.4f, 0.6f, lerpValue2, true);
                                float lerpValue4 = Utils.GetLerpValue(0.6f, 1f, lerpValue2, true);
                                float num34 = vector12.SafeNormalize(Vector2.Zero).ToRotation() + 1.5707964f;
                                this.rotation = this.rotation.AngleTowards(num34, 0.62831855f);
                                base.Center = Vector2.Lerp(vector11, npc2.Center, lerpValue3);
                                if (lerpValue4 > 0f)
{
                                    base.Center = Vector2.Lerp(npc2.Center, vector14, lerpValue4);
                                }
                            }
                            if (this.ai[0] == (float)num25)
{
                                int num35 = this.AI_156_TryAttackingNPCs(blacklist, flag3);
                                if (num35 != -1)
{
                                    this.ai[0] = (float)Main.rand.NextFromList(new int[] { num, num3 });
                                    this.ai[1] = (float)num35;
                                    this.AI_156_StartAttack();
                                    this.netUpdate = true;
                                    return;
                                }
                                this.ai[0] = -1f;
                                this.ai[1] = 0f;
                                this.netUpdate = true;
                            }
                        }
                    }
                }
            }
        }
References Terraria.Player.active, Terraria.Entity.Center, Microsoft.Xna.Framework.Vector2.Distance(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.player, Terraria.Main.rand, Microsoft.Xna.Framework.Vector2.SmoothStep(), and Microsoft.Xna.Framework.Vector2.Zero.