Terraria Decompiled: Terraria.Projectile.KillOldestJavelin
KillOldestJavelin()
static void Terraria.Projectile.KillOldestJavelin (int protectedProjectileIndex, int projectileType, int targetNPCIndex, Point[] bufferForScan) inline static
Definition at line 14015 of file Projectile.cs.
        {
            int num = 0;
            for (int i = 0; i < 1000; i++)
            {
                if (i != protectedProjectileIndex && Main.projectile[i].active && Main.projectile[i].owner == Main.myPlayer && Main.projectile[i].type == projectileType && Main.projectile[i].ai[0] == 1f && Main.projectile[i].ai[1] == (float)targetNPCIndex)
                {
                    bufferForScan[num++] = new Point(i, Main.projectile[i].timeLeft);
                    if (num >= bufferForScan.Length)
                    {
                        break;
                    }
                }
            }
            if (num >= bufferForScan.Length)
            {
                int num2 = 0;
                for (int j = 1; j < bufferForScan.Length; j++)
                {
                    if (bufferForScan[j].Y < bufferForScan[num2].Y)
                    {
                        num2 = j;
                    }
                }
                Main.projectile[bufferForScan[num2].X].Kill();
            }
        }
References Terraria.Projectile.active, Terraria.Projectile.ai, Terraria.Projectile.Kill(), Terraria.Main.myPlayer, Terraria.Projectile.owner, Terraria.Main.projectile, Terraria.Projectile.timeLeft, Terraria.Projectile.type, Microsoft.Xna.Framework.Point.X, and System.Y.
Referenced by Terraria.Player.BloodButcherer_TryButchering(), Terraria.Projectile.Damage_PVE_Inner(), and Terraria.Player.TentacleSpike_TrySpiking().