Terraria Decompiled: Terraria.Projectile.RainbowBoulder_JumpToPosition
RainbowBoulder_JumpToPosition()
void Terraria.Projectile.RainbowBoulder_JumpToPosition (Vector2 targetPosition, Vector2 targetVelocity) inline private
Definition at line 18909 of file Projectile.cs.
        {
            Vector2 vector = targetPosition - base.Center;
            int num = 32;
            float num2 = Utils.Remap(vector.Length(), 0f, 200f, 4f, (float)num, true);
            float num3 = vector.Length() / num2;
            float num4 = 0.6f;
            this.velocity = vector.SafeNormalize(Vector2.UnitY * -1f) * num2;
            if (this.owner == Main.myPlayer)
            {
                ParticleOrchestrator.RequestParticleSpawn(false, ParticleOrchestraType.RainbowBoulder4, new ParticleOrchestraSettings
                {
                    PositionInWorld = base.Center,
                    MovementVector = this.velocity
                }, null);
            }
            bool flag = false;
            for (float num5 = 8f; num5 <= (float)num; num5 += 2f)
            {
                Utils.ChaseResults chaseResults = Utils.GetChaseResults(base.Center, num5, targetPosition, targetVelocity);
                if (chaseResults.InterceptionHappens)
                {
                    this.velocity = chaseResults.ChaserVelocity;
                    this.velocity = Utils.FactorAcceleration(this.velocity, chaseResults.InterceptionTime, new Vector2(0f, num4), 0);
                    num3 = (float)((int)(chaseResults.InterceptionTime - 2f));
                    flag = true;
                }
            }
            if (!flag)
            {
                this.velocity = Utils.FactorAcceleration(this.velocity, Math.Min(120f, num3), new Vector2(0f, num4), 0);
            }
            this.ai[1] = num3;
            this.netUpdate = true;
        }
References Terraria.Utils.ChaseResults.ChaserVelocity, Terraria.Utils.FactorAcceleration(), Terraria.Utils.GetChaseResults(), Terraria.Utils.ChaseResults.InterceptionHappens, Terraria.Utils.ChaseResults.InterceptionTime, Microsoft.Xna.Framework.Vector2.Length(), System.Math.Min(), Terraria.Main.myPlayer, Terraria.Utils.Remap(), Terraria.GameContent.Drawing.ParticleOrchestrator.RequestParticleSpawn(), and Microsoft.Xna.Framework.Vector2.UnitY.