Terraria Decompiled: Terraria.Projectile.FindBannerToAssociateTo
FindBannerToAssociateTo()
void Terraria.Projectile.FindBannerToAssociateTo (IEntitySource spawnSource) inline private
Definition at line 10227 of file Projectile.cs.
        {
            EntitySource_Parent entitySource_Parent = spawnSource as EntitySource_Parent;
            if (entitySource_Parent == null)
            {
                return;
            }
            Projectile projectile = entitySource_Parent.Entity as Projectile;
            if (projectile != null)
            {
                this.bannerIdToRespondTo = projectile.bannerIdToRespondTo;
                return;
            }
            NPC npc = entitySource_Parent.Entity as NPC;
            if (npc != null)
            {
                this.bannerIdToRespondTo = BannerSystem.NPCtoBanner(npc.BannerID());
            }
        }
References Terraria.NPC.BannerID(), Terraria.Projectile.bannerIdToRespondTo, Terraria.Enums.NPC, Terraria.GameContent.BannerSystem.NPCtoBanner(), and Terraria.Projectile.Projectile().
Referenced by Terraria.Projectile.NewProjectile().