Terraria Decompiled: Terraria.Projectile.SpawnConstellationStarsTowards
SpawnConstellationStarsTowards()
void Terraria.Projectile.SpawnConstellationStarsTowards (NPC targetNPC, int calcDamage) inline private
Definition at line 13880 of file Projectile.cs.
        {
            int num = (int)((float)calcDamage * 0.33f);
            this.WhipPointsForCollision.Clear();
            Projectile.FillWhipControlPoints(this, this.WhipPointsForCollision, null, false);
            for (int i = 2; i < this.WhipPointsForCollision.Count - 1; i += 3)
            {
                Vector2 vector = this.WhipPointsForCollision[i + 1];
                Vector2 vector2 = this.WhipPointsForCollision[i];
                Vector2 vector3 = (vector - vector2).RotatedBy((double)(-1.5707964f * (float)Main.player[this.owner].direction * Main.player[this.owner].gravDir), default(Vector2));
                Projectile.NewProjectile(this.GetProjectileSource_FromThis(), vector2, vector3.SafeNormalize(Vector2.Zero) * (1f + Main.rand.NextFloatDirection() * 3f), 1039, num, this.knockBack, this.owner, (float)targetNPC.whoAmI, 0.02f + 0.09f * Main.rand.NextFloat(), 0f, null);
            }
        }
References Terraria.Entity.direction, Terraria.Projectile.FillWhipControlPoints(), Terraria.Player.gravDir, int, Terraria.Projectile.NewProjectile(), Terraria.Main.player, Terraria.Main.rand, Terraria.Entity.whoAmI, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.Projectile.Damage_PVE_Inner().