Terraria Decompiled: Terraria.Projectile.AI_131_FlameBurstShot
AI_131_FlameBurstShot()
void Terraria.Projectile.AI_131_FlameBurstShot () inline private
Definition at line 69238 of file Projectile.cs.
        {
            if (this.type == 664 || this.type == 666 || this.type == 668)
            {
                if (this.localAI[0] == 0f)
                {
                    this.localAI[0] = 1f;
                    this.localAI[1] = SoundEngine.PlayTrackedSound(SoundID.DD2_FlameburstTowerShot, base.Center, default(SoundPlayOverrides)).ToFloat();
                }
                ActiveSound activeSound = SoundEngine.GetActiveSound(SlotId.FromFloat(this.localAI[1]));
                if (activeSound == null)
                {
                    float[] array = this.localAI;
                    int num = 1;
                    SlotId invalid = SlotId.Invalid;
                    array[num] = invalid.ToFloat();
                }
                else
                {
                    activeSound.Position = base.Center;
                }
                if (this.alpha > 0)
                {
                    this.alpha -= 25;
                    if (this.alpha < 0)
                    {
                        this.alpha = 0;
                    }
                }
                int num2 = 1;
                if (this.type == 666)
                {
                    num2 = 2;
                }
                if (this.type == 668)
                {
                    num2 = 3;
                }
                for (int i = 0; i < num2; i++)
                {
                    if (Main.rand.Next(2) != 0)
                    {
                        Dust dust = Dust.NewDustDirect(this.position, this.width, this.height, 6, this.velocity.X * 0.2f, this.velocity.Y * 0.2f, 100, default(Color), 2f);
                        dust.noGravity = true;
                        dust.velocity *= 0.3f;
                        if (Main.rand.Next(1) == 0)
{
                            Dust dust2 = dust;
                            dust2.velocity.Y = dust2.velocity.Y + (float)Math.Sign(dust.velocity.Y) * 1.2f;
                            dust.fadeIn += 0.5f;
                        }
                    }
                }
                this.rotation = this.velocity.ToRotation() + 1.5707964f;
            }
        }
References System.array, Terraria.ID.SoundID.DD2_FlameburstTowerShot, ReLogic.Utilities.SlotId.FromFloat(), Terraria.Audio.SoundEngine.GetActiveSound(), ReLogic.Utilities.SlotId.Invalid, Terraria.Dust.NewDustDirect(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Audio.SoundEngine.PlayTrackedSound(), Terraria.Main.rand, System.Math.Sign(), ReLogic.Utilities.SlotId.ToFloat(), Terraria.Dust.velocity, and Microsoft.Xna.Framework.Vector2.Y.