Terraria Decompiled: Terraria.Projectile.AI_156_TryAttackingNPCs
AI_156_TryAttackingNPCs()
int Terraria.Projectile.AI_156_TryAttackingNPCs (List< int > blackListedTargets, bool skipBodyCheck = false) inline private
Definition at line 52189 of file Projectile.cs.
        {
            Vector2 center = Main.player[this.owner].Center;
            int num = -1;
            float num2 = -1f;
            NPC ownerMinionAttackTargetNPC = this.OwnerMinionAttackTargetNPC;
            if (ownerMinionAttackTargetNPC != null && ownerMinionAttackTargetNPC.CanBeChasedBy(this, false))
            {
                bool flag = true;
                if (!ownerMinionAttackTargetNPC.boss && blackListedTargets.Contains(ownerMinionAttackTargetNPC.whoAmI))
                {
                    flag = false;
                }
                if (ownerMinionAttackTargetNPC.Distance(center) > 1000f)
                {
                    flag = false;
                }
                if (!skipBodyCheck && !this.CanHitWithOwnBody(ownerMinionAttackTargetNPC))
                {
                    flag = false;
                }
                if (flag)
                {
                    return ownerMinionAttackTargetNPC.whoAmI;
                }
            }
            for (int i = 0; i < Main.maxNPCs; i++)
            {
                NPC npc = Main.npc[i];
                if (npc.CanBeChasedBy(this, false) && (npc.boss || !blackListedTargets.Contains(i)))
                {
                    float num3 = npc.Distance(center);
                    if (num3 <= 1000f && (num3 <= num2 || num2 == -1f) && (skipBodyCheck || this.CanHitWithOwnBody(npc)))
                    {
                        num2 = num3;
                        num = i;
                    }
                }
            }
            return num;
        }
References Terraria.NPC.boss, Terraria.NPC.CanBeChasedBy(), Terraria.Entity.Center, System.Collections.Generic.List< T >.Contains(), Terraria.Entity.Distance(), Terraria.Main.maxNPCs, Terraria.Main.npc, Terraria.Main.player, and Terraria.Entity.whoAmI.