Terraria Decompiled: Terraria.Projectile.Damage_GetProjectileSpecificDamageMultiplier
Damage_GetProjectileSpecificDamageMultiplier()
float Terraria.Projectile.Damage_GetProjectileSpecificDamageMultiplier () inline private
Definition at line 13354 of file Projectile.cs.
        {
            float num = 1f;
            if (ProjectileID.Sets.IsARocketThatDealsDoubleDamageToPrimaryEnemy[this.type] && this.timeLeft > 3)
            {
                num *= 2f;
            }
            if (ProjectileID.Sets.IsAMineThatDealsTripleDamageWhenStationary[this.type] && this.velocity.Length() < 0.5f)
            {
                num *= 3f;
            }
            if (this.type == 34 && this.penetrate == 1)
            {
                num *= 1f;
            }
            if (this.aiStyle == 15 && this.ai[0] == 0f)
            {
                num *= 1.2f;
                if (this.type == 26 || this.type == 35)
                {
                    for (int i = 0; i < 1000; i++)
                    {
                        if (Main.projectile[i].active && Main.projectile[i].type != this.type && Main.projectile[i].owner == this.owner && (Main.projectile[i].type == 35 || Main.projectile[i].type == 26))
{
                            num *= 0.8f;
                            break;
                        }
                    }
                }
            }
            if (this.aiStyle == 15 && (this.ai[0] == 1f || this.ai[0] == 2f))
            {
                num *= 2f;
            }
            if (this.type == 877 || this.type == 879 || this.type == 878)
            {
                num = 0.1f + Main.player[this.owner].velocity.Length() / 7f * 0.9f;
            }
            if (this.type == 968)
            {
                num = 1f;
                switch ((int)this.ai[1])
                {
                case 0:
                    num = 1.5f;
                    break;
                case 1:
                    num = 1f;
                    break;
                case 2:
                    num = 1.5f;
                    break;
                case 3:
                    num = 0.1f;
                    break;
                case 4:
                    num = 1f;
                    break;
                case 5:
                    num = 1f;
                    break;
                case 6:
                    num = 1f;
                    break;
                case 7:
                    num = 0.25f;
                    break;
                case 8:
                    num = 1f;
                    break;
                case 9:
                    num = 0.75f;
                    break;
                case 10:
                    num = 0.5f;
                    break;
                case 11:
                    num = 0.5f;
                    break;
                case 12:
                    num = 0.5f;
                    break;
                case 13:
                    num = 0.5f;
                    break;
                case 14:
                    num = 0.5f;
                    break;
                case 15:
                    num = 0.5f;
                    break;
                case 16:
                    num = 0.5f;
                    break;
                case 17:
                    num = 1.5f;
                    break;
                case 18:
                    num = 1.6f;
                    break;
                case 19:
                    num = 1.8f;
                    break;
                case 20:
                    num = 1.9f;
                    break;
                case 21:
                    num = 1.7f;
                    break;
                case 22:
                    num = 2f;
                    break;
                case 23:
                    num = 1.9f;
                    break;
                }
            }
            if (this.type == 533 && this.localAI[2] >= 40f)
            {
                num *= 0.5f;
            }
            if (this.type == 1024 && this.ai[0] == 2f)
            {
                num *= 1.5f;
            }
            if (this.type == 1023 && this.localAI[1] > 0f)
            {
                num *= 1.33f;
            }
            if (this.type == 1091)
            {
                num *= Utils.Remap(Main.Difficulty, GameDifficultyLevel.Classic, GameDifficultyLevel.Master, 1f, 3f, true);
            }
            return num;
        }
References Terraria.Projectile.active, Terraria.DataStructures.GameDifficultyLevel.Classic, Terraria.Main.Difficulty, Terraria.ID.ProjectileID.Sets.IsAMineThatDealsTripleDamageWhenStationary, Terraria.ID.ProjectileID.Sets.IsARocketThatDealsDoubleDamageToPrimaryEnemy, Microsoft.Xna.Framework.Vector2.Length(), Terraria.DataStructures.GameDifficultyLevel.Master, Terraria.Projectile.owner, Terraria.Main.player, Terraria.Main.projectile, Terraria.Utils.Remap(), Terraria.Projectile.type, and Terraria.Entity.velocity.
Referenced by Terraria.Projectile.Damage().