Terraria Decompiled: Terraria.Projectile.AI_172_HallowBossRainbowPelletStorm
AI_172_HallowBossRainbowPelletStorm()
void Terraria.Projectile.AI_172_HallowBossRainbowPelletStorm () inline private
Definition at line 45818 of file Projectile.cs.
        {
            if (this.localAI[1] <= 90f)
            {
                this.localAI[1] += 1f;
                this.scale = 0.5f;
                this.Opacity = 0.5f;
                float lerpValue = Utils.GetLerpValue(0f, 90f, this.localAI[1], false);
                this.scale = MathHelper.Lerp(5f, 1f, lerpValue);
                this.Opacity = 1f - (1f - lerpValue * lerpValue);
                return;
            }
            this.scale = 1f;
            this.Opacity = 1f;
            float num = 150f + 10f * (float)this.AI_172_GetPelletStormsCount();
            this.localAI[0] += 1f;
            if (this.localAI[0] >= num)
            {
                this.Kill();
                return;
            }
            this.velocity = Vector2.Zero;
            this.rotation = 0f;
            int num2 = this.AI_172_GetPelletStormsCount();
            for (int i = 0; i < num2; i++)
            {
                Projectile.HallowBossPelletStormInfo hallowBossPelletStormInfo = this.AI_172_GetPelletStormInfo(i);
                for (int j = 0; j < hallowBossPelletStormInfo.BulletsInStorm; j++)
                {
                    if (hallowBossPelletStormInfo.IsValid(j))
                    {
                        hallowBossPelletStormInfo.GetBulletPosition(j, base.Center);
                    }
                }
            }
        }
References Terraria.Projectile.HallowBossPelletStormInfo.BulletsInStorm, Terraria.Projectile.HallowBossPelletStormInfo.GetBulletPosition(), Terraria.Utils.GetLerpValue(), Terraria.Projectile.HallowBossPelletStormInfo.IsValid(), Microsoft.Xna.Framework.MathHelper.Lerp(), and Microsoft.Xna.Framework.Vector2.Zero.