Terraria Decompiled: Terraria.Projectile.AI_148_StarSpawner
AI_148_StarSpawner()
void Terraria.Projectile.AI_148_StarSpawner () inline private
Definition at line 53463 of file Projectile.cs.
        {
            if (Main.dayTime && !Main.remixWorld)
            {
                this.Kill();
                return;
            }
            this.ai[0] += (float)Main.dayRate;
            if (this.localAI[0] == 0f && Main.netMode != 2)
            {
                this.localAI[0] = 1f;
                if ((double)Main.LocalPlayer.position.Y < Main.worldSurface * 16.0)
                {
                    Star.StarFall(this.position.X);
                }
            }
            if (this.owner == Main.myPlayer && this.ai[0] >= 180f)
            {
                if (this.ai[1] > -1f)
                {
                    this.velocity.X = this.velocity.X * 0.35f;
                    if (base.Center.X < Main.player[(int)this.ai[1]].Center.X)
                    {
                        this.velocity.X = Math.Abs(this.velocity.X);
                    }
                    else
                    {
                        this.velocity.X = -Math.Abs(this.velocity.X);
                    }
                }
                Projectile.NewProjectile(this.GetProjectileSource_FromThis(), this.position.X, this.position.Y, this.velocity.X, this.velocity.Y, 12, 1000, 10f, Main.myPlayer, 0f, 0f, 0f, null);
                this.Kill();
            }
        }
References System.Math.Abs(), Terraria.Entity.Center, Terraria.Main.dayRate, Terraria.Main.dayTime, Terraria.Main.LocalPlayer, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Projectile.NewProjectile(), Terraria.Main.player, Terraria.Entity.position, Terraria.Main.remixWorld, Terraria.Star.StarFall(), Terraria.Main.worldSurface, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.