Terraria Decompiled: Terraria.Projectile.AI_174_MultisegmentPet
AI_174_MultisegmentPet()
void Terraria.Projectile.AI_174_MultisegmentPet () inline private
Definition at line 45589 of file Projectile.cs.
        {
            Player player = Main.player[this.owner];
            if (!player.active)
            {
                this.active = false;
                return;
            }
            if (this.type == 883)
            {
                if (player.dead)
                {
                    player.petFlagEaterOfWorldsPet = false;
                }
                if (player.petFlagEaterOfWorldsPet)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 887)
            {
                if (player.dead)
                {
                    player.petFlagDestroyerPet = false;
                }
                if (player.petFlagDestroyerPet)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 893)
            {
                if (player.dead)
                {
                    player.petFlagLunaticCultistPet = false;
                }
                if (player.petFlagLunaticCultistPet)
                {
                    this.timeLeft = 2;
                }
            }
            Vector2 center = player.Center;
            if (base.Distance(center) > 2000f)
            {
                base.Center = center;
                this.velocity = Vector2.Zero;
                this.netUpdate = true;
            }
            float num = (center - base.Center).Length();
            float num2 = Math.Min(12f, Math.Max(4f, player.velocity.Length()));
            this.velocity.Length();
            if (this.velocity == Vector2.Zero)
            {
                this.velocity.X = 2f * (float)player.direction;
                Vector2 vector = this.position;
                for (int i = 0; i < this.oldPos.Length; i++)
                {
                    vector -= this.velocity;
                    this.oldPos[i] = vector;
                }
            }
            if (num >= 120f)
            {
                float num3 = base.AngleTo(center);
                float num4 = this.velocity.ToRotation().AngleTowards(num3, MathHelper.ToRadians(5f));
                this.velocity = num4.ToRotationVector2() * num2;
            }
            if (this.velocity.Length() > num2)
            {
                this.velocity = this.velocity.SafeNormalize(Vector2.Zero) * num2;
            }
            if (Math.Abs(this.velocity.Y) < 1f)
            {
                this.velocity.Y = this.velocity.Y - 0.1f;
            }
            this.rotation = this.velocity.ToRotation() + 1.5707964f;
            int direction = this.direction;
            this.direction = (this.spriteDirection = ((this.velocity.X > 0f) ? 1 : (-1)));
            if (direction != this.direction)
            {
                this.netUpdate = true;
            }
            this.position.X = MathHelper.Clamp(this.position.X, 160f, (float)(Main.maxTilesX * 16 - 160));
            this.position.Y = MathHelper.Clamp(this.position.Y, 160f, (float)(Main.maxTilesY * 16 - 160));
        }
References System.Math.Abs(), Terraria.Player.active, Terraria.Entity.Center, Microsoft.Xna.Framework.MathHelper.Clamp(), Terraria.Player.dead, Terraria.Entity.direction, Microsoft.Xna.Framework.Vector2.Length(), System.Math.Max(), System.Math.Min(), Terraria.Player.petFlagDestroyerPet, Terraria.Player.petFlagEaterOfWorldsPet, Terraria.Player.petFlagLunaticCultistPet, Terraria.Main.player, Microsoft.Xna.Framework.MathHelper.ToRadians(), Terraria.Entity.velocity, and Microsoft.Xna.Framework.Vector2.Zero.