Terraria Decompiled: Terraria.Projectile.FillWhipControlPoints
FillWhipControlPoints()
static void Terraria.Projectile.FillWhipControlPoints (Projectile proj, List< Vector2 > controlPoints, Player owner = null, bool getActualCollisionPoints = false) inline static
Definition at line 48733 of file Projectile.cs.
        {
            if (owner == null)
            {
                owner = Main.player[proj.owner];
            }
            float num;
            int num2;
            float num3;
            Projectile.GetWhipSettings(proj, out num, out num2, out num3);
            float num4 = proj.ai[0] / num;
            if (proj.type == 1028)
            {
                num4 = Utils.Remap(num4, 0f, 1f, 0.3f, 0.95f, true);
            }
            float num5 = 0.5f;
            float num6 = 1f + num5;
            float num7 = 31.415928f * (1f - num4 * num6) * (float)(-(float)proj.spriteDirection) / (float)num2;
            float num8 = num4 * num6;
            float num9 = 0f;
            if (num8 > 1f)
            {
                num9 = (num8 - 1f) / num5;
                num8 = MathHelper.Lerp(1f, 0f, num9);
            }
            float num10 = proj.ai[0] - 1f;
            Item heldItem = owner.HeldItem;
            num10 = (float)(ContentSamples.ItemsByType[heldItem.type].useAnimation * 2) * num4 * owner.whipRangeMultiplier;
            float num11 = proj.velocity.Length() * num10 * num8 * num3 / (float)num2;
            float num12 = 1f;
            Vector2 playerArmPosition = Main.GetPlayerArmPosition(proj, owner);
            Vector2 vector = playerArmPosition;
            float num13 = 0f;
            float num14 = num13 - 1.5707964f;
            Vector2 vector2 = vector;
            float num15 = num13 + 1.5707964f + 1.5707964f * (float)proj.spriteDirection;
            Vector2 vector3 = vector;
            float num16 = num13 + 1.5707964f;
            controlPoints.Add(playerArmPosition);
            float num17 = proj.ai[1];
            if (getActualCollisionPoints)
            {
                num17 = 1f;
            }
            for (int i = 0; i < num2; i++)
            {
                float num18 = (float)i / (float)num2;
                float num19 = num7 * num18 * num12 * num17;
                Vector2 vector4 = vector + num14.ToRotationVector2() * num11;
                Vector2 vector5 = vector3 + num16.ToRotationVector2() * (num11 * 2f);
                Vector2 vector6 = vector2 + num15.ToRotationVector2() * (num11 * 2f);
                float num20 = 1f - num8;
                float num21 = 1f - num20 * num20;
                Vector2 vector7 = Vector2.Lerp(vector5, vector4, num21 * 0.9f + 0.1f);
                Vector2 vector8 = Vector2.Lerp(vector6, vector7, num21 * 0.7f + 0.3f);
                Vector2 vector9 = playerArmPosition + (vector8 - playerArmPosition) * new Vector2(1f, num6);
                float num22 = num9;
                num22 *= num22;
                Vector2 vector10 = vector9.RotatedBy((double)(proj.rotation + 4.712389f * num22 * (float)proj.spriteDirection), playerArmPosition);
                controlPoints.Add(vector10);
                num14 += num19;
                num16 += num19;
                num15 += num19;
                vector = vector4;
                vector3 = vector5;
                vector2 = vector6;
            }
        }
References System.Collections.Generic.List< T >.Add(), Terraria.Projectile.ai, Terraria.Main.GetPlayerArmPosition(), Terraria.Projectile.GetWhipSettings(), Terraria.ID.ContentSamples.ItemsByType, Microsoft.Xna.Framework.Vector2.Length(), Microsoft.Xna.Framework.MathHelper.Lerp(), Microsoft.Xna.Framework.Vector2.Lerp(), Terraria.Projectile.owner, Terraria.Main.player, Terraria.Utils.Remap(), Terraria.Projectile.rotation, Terraria.Projectile.spriteDirection, Terraria.Item.type, Terraria.Projectile.type, and Terraria.Entity.velocity.
Referenced by Terraria.Projectile.AI_165_Whip(), Terraria.Projectile.Colliding(), Terraria.Projectile.CutTiles(), Terraria.Main.DrawWhip(), Terraria.Projectile.SpawnConstellationStarsTowards(), Terraria.Projectile.StatusNPC(), and Terraria.Projectile.UpdateEnchantmentVisuals().