Terraria Decompiled: Terraria.Projectile.AI_003_Boomerang
AI_003_Boomerang()
void Terraria.Projectile.AI_003_Boomerang () inline private
Definition at line 39294 of file Projectile.cs.
        {
            if (this.type != 383 && !ProjectileID.Sets.IsAPhaseblade[this.type] && this.soundDelay == 0)
            {
                if (this.type == 301)
                {
                    if (this.ai[0] != 0f)
                    {
                        this.soundDelay = 10;
                        if (this.extraUpdates > 0)
{
                            this.soundDelay *= this.extraUpdates + 1;
                        }
                        SoundEngine.PlaySound(SoundID.Item7, this.position, -0.33f, 1f);
                    }
                }
                else
                {
                    this.soundDelay = 8;
                    if (this.extraUpdates > 0)
                    {
                        this.soundDelay *= this.extraUpdates + 1;
                    }
                    SoundEngine.PlaySound(SoundID.Item7, this.position, 0f, 1f);
                }
            }
            if (this.type == 19)
            {
                for (int i = 0; i < 2; i++)
                {
                    int num = Dust.NewDust(new Vector2(this.position.X, this.position.Y), this.width, this.height, 6, this.velocity.X * 0.2f, this.velocity.Y * 0.2f, 100, default(Color), 2f);
                    Main.dust[num].noGravity = true;
                    Dust dust = Main.dust[num];
                    dust.velocity.X = dust.velocity.X * 0.3f;
                    Dust dust2 = Main.dust[num];
                    dust2.velocity.Y = dust2.velocity.Y * 0.3f;
                }
            }
            else if (this.type == 1000)
            {
                if (Main.rand.Next(3) == 0)
                {
                    switch (Main.rand.Next(3))
                    {
                    default:
                    {
                        int num2;
                        switch (Main.rand.Next(3))
{
                        default:
                            num2 = 15;
                            break;
                        case 1:
                            num2 = 57;
                            break;
                        case 2:
                            num2 = 58;
                            break;
                        }
                        Main.dust[Dust.NewDust(this.position, this.width, this.height, num2, this.velocity.X * 0.25f, this.velocity.Y * 0.25f, 150, default(Color), 0.7f)].velocity *= 0.5f;
                        break;
                    }
                    case 1:
                    {
                        Dust dust3 = Main.dust[Dust.NewDust(this.position, this.width, this.height, 267, this.velocity.X, this.velocity.Y, 50, new Color(50, 50, 200), 1.1f)];
                        dust3.fadeIn = 0.1f;
                        dust3.velocity = this.velocity * 0.5f;
                        dust3.noGravity = true;
                        break;
                    }
                    case 2:
                        Main.dust[Dust.NewDust(this.position, this.width, this.height, 76, this.velocity.X * 0.15f, this.velocity.Y * 0.15f, 0, default(Color), 1.1f)].noGravity = true;
                        Dust.NewDust(this.position, this.width, this.height, 15, this.velocity.X * 0.05f, this.velocity.Y * 0.05f, 150, default(Color), 0.6f);
                        break;
                    }
                }
            }
            else if (this.type == 867)
            {
                if (Main.rand.Next(3) == 0)
                {
                    int num3 = Dust.NewDust(this.position, this.width, this.height, 165, this.velocity.X, this.velocity.Y, 50, default(Color), 1f);
                    Main.dust[num3].velocity *= 0.5f;
                    Main.dust[num3].noGravity = true;
                }
            }
            else if (this.type == 33)
            {
                if (Main.rand.Next(1) == 0)
                {
                    int num4 = Dust.NewDust(this.position, this.width, this.height, 40, this.velocity.X * 0.25f, this.velocity.Y * 0.25f, 0, default(Color), 1.4f);
                    Main.dust[num4].noGravity = true;
                }
            }
            else if (this.type == 320)
            {
                if (Main.rand.Next(3) == 0)
                {
                    int num5 = Dust.NewDust(this.position, this.width, this.height, 5, this.velocity.X * 0.25f, this.velocity.Y * 0.25f, 0, default(Color), 1.1f);
                    if (Main.rand.Next(2) == 0)
                    {
                        Main.dust[num5].scale = 0.9f;
                        Main.dust[num5].velocity *= 0.2f;
                    }
                    else
                    {
                        Main.dust[num5].noGravity = true;
                    }
                }
            }
            else if (this.type == 6)
            {
                if (Main.rand.Next(5) == 0)
                {
                    int num6 = Main.rand.Next(3);
                    if (num6 == 0)
                    {
                        num6 = 15;
                    }
                    else if (num6 == 1)
                    {
                        num6 = 57;
                    }
                    else
                    {
                        num6 = 58;
                    }
                    Dust.NewDust(this.position, this.width, this.height, num6, this.velocity.X * 0.25f, this.velocity.Y * 0.25f, 150, default(Color), 0.7f);
                }
            }
            else if (this.type == 113 && Main.rand.Next(1) == 0)
            {
                int num7 = Dust.NewDust(this.position, this.width, this.height, 76, this.velocity.X * 0.15f, this.velocity.Y * 0.15f, 0, default(Color), 1.1f);
                Main.dust[num7].noGravity = true;
                Dust.NewDust(this.position, this.width, this.height, 15, this.velocity.X * 0.05f, this.velocity.Y * 0.05f, 150, default(Color), 0.6f);
            }
            if (ProjectileID.Sets.IsAPhaseblade[this.type])
            {
                if (Main.myPlayer == this.owner && this.ai[0] != 1f && !WorldGen.InWorld(base.Center.ToTileCoordinates(), 10))
                {
                    this.ai[0] = 1f;
                    this.netUpdate = true;
                }
                if (this.timeLeft < 5 && Main.player[this.owner].active && !Main.player[this.owner].dead)
                {
                    this.timeLeft = 5;
                    if (Main.myPlayer == this.owner && this.ai[0] != 1f)
                    {
                        this.ai[0] = 1f;
                        this.netUpdate = true;
                    }
                }
                if ((double)this.rotation < -6.283185307179586)
                {
                    this.rotation += 6.2831855f;
                }
                if ((double)this.rotation > 6.283185307179586)
                {
                    this.rotation -= 6.2831855f;
                }
                if (ProjectileID.Sets.IsAPhaseblade[Main.player[this.owner].HeldItem.shoot] && this.owner == Main.myPlayer && this.ai[0] != 1f && Main.player[this.owner].active && !Main.player[this.owner].dead && Main.player[this.owner].controlUseItem)
                {
                    this.ai[0] = 1f;
                    this.netUpdate = true;
                }
                Color color = Item.GetPhaseColor(this.type, false) * 0.5f;
                float num8 = (float)color.R / 255f;
                float num9 = (float)color.G / 255f;
                float num10 = (float)color.B / 255f;
                if (this.type != 1074)
                {
                    Lighting.AddLight((int)(base.Center.X / 16f), (int)(base.Center.Y / 16f), num8, num9, num10);
                    Lighting.AddLight((int)(base.Center.X / 16f), (int)(base.Center.Y / 16f) - 1, num8, num9, num10);
                }
            }
            if (this.ai[0] == 0f)
            {
                bool flag = true;
                int num11 = this.type;
                if (num11 == 866)
                {
                    flag = false;
                }
                if (flag)
                {
                    this.ai[1] += 1f;
                }
                if (this.type == 106 && this.ai[1] >= 45f)
                {
                    this.ai[0] = 1f;
                    this.ai[1] = 0f;
                    this.netUpdate = true;
                }
                if (ProjectileID.Sets.IsAPhaseblade[this.type])
                {
                    if (this.ai[1] >= 30f)
                    {
                        this.velocity.Y = this.velocity.Y + 1f;
                        this.velocity.X = this.velocity.X * 0.96f;
                        if (this.velocity.Y > 16f)
{
                            this.velocity.Y = 16f;
                        }
                        if (this.velocity.Y > 0f)
{
                            if (this.direction > 0)
{
                                if (this.rotation <= 2.335f)
{
                                    this.rotation = (this.rotation * 4f + 2.335f) / 5f;
                                }
                                else
{
                                    this.rotation = (this.rotation * 9f + 2.335f + 6.2831855f) / 10f;
                                }
                            }
                            else if (this.rotation >= -3.948f)
{
                                this.rotation = (this.rotation * 4f - 3.948f) / 5f;
                            }
                            else
{
                                this.rotation = (this.rotation * 9f - 3.948f - 6.2831855f) / 10f;
                            }
                        }
                        else
{
                            this.rotation += 0.4f * (float)this.direction;
                            if (this.type == 1074)
{
                                if (this.soundDelay == 0)
{
                                    SoundEngine.PlaySound(SoundID.Item7, this.position, 0f, 1f);
                                    this.soundDelay = 9;
                                }
                            }
                            else if (this.soundDelay == 0)
{
                                SoundEngine.PlaySound(SoundID.Item15, this.position, 0f, 1f);
                                this.soundDelay = 14;
                            }
                        }
                    }
                    else
                    {
                        this.rotation += 0.4f * (float)this.direction;
                        if (this.type == 1074)
{
                            if (this.soundDelay == 0)
{
                                SoundEngine.PlaySound(SoundID.Item7, this.position, -0.3f, 1f);
                                this.soundDelay = 11;
                            }
                        }
                        else if (this.soundDelay == 0)
{
                            SoundEngine.PlaySound(SoundID.Item15, this.position, 0f, 1f);
                            this.soundDelay = 14;
                        }
                    }
                }
                else if (this.type == 320 || this.type == 383)
                {
                    if (this.ai[1] >= 10f)
                    {
                        this.velocity.Y = this.velocity.Y + 0.5f;
                        if (this.type == 383 && this.velocity.Y < 0f)
{
                            this.velocity.Y = this.velocity.Y + 0.35f;
                        }
                        this.velocity.X = this.velocity.X * 0.95f;
                        if (this.velocity.Y > 16f)
{
                            this.velocity.Y = 16f;
                        }
                        if (this.type == 383 && Vector2.Distance(base.Center, Main.player[this.owner].Center) > 800f)
{
                            this.ai[0] = 1f;
                            this.netUpdate = true;
                        }
                    }
                }
                else if (this.type == 182)
                {
                    if (Main.rand.Next(2) == 0)
                    {
                        int num12 = Dust.NewDust(this.position, this.width, this.height, 57, 0f, 0f, 255, default(Color), 0.75f);
                        Main.dust[num12].velocity *= 0.1f;
                        Main.dust[num12].noGravity = true;
                    }
                    if (this.velocity.X > 0f)
                    {
                        this.spriteDirection = 1;
                    }
                    else if (this.velocity.X < 0f)
                    {
                        this.spriteDirection = -1;
                    }
                    float num13 = this.position.X;
                    float num14 = this.position.Y;
                    float num15 = 800f;
                    bool flag2 = false;
                    if (this.ai[1] > 10f && this.ai[1] < 360f)
                    {
                        for (int j = 0; j < Main.maxNPCs; j++)
{
                            if (Main.npc[j].CanBeChasedBy(this, false))
{
                                float num16 = Main.npc[j].position.X + (float)(Main.npc[j].width / 2);
                                float num17 = Main.npc[j].position.Y + (float)(Main.npc[j].height / 2);
                                float num18 = base.Distance(Main.npc[j].Center);
                                if (num18 < num15 && Collision.CanHit(new Vector2(this.position.X + (float)(this.width / 2), this.position.Y + (float)(this.height / 2)), 1, 1, Main.npc[j].position, Main.npc[j].width, Main.npc[j].height))
{
                                    num15 = num18;
                                    num13 = num16;
                                    num14 = num17;
                                    flag2 = true;
                                }
                            }
                        }
                    }
                    if (!flag2)
                    {
                        num13 = this.position.X + (float)(this.width / 2) + this.velocity.X * 100f;
                        num14 = this.position.Y + (float)(this.height / 2) + this.velocity.Y * 100f;
                        if (this.ai[1] >= 30f)
{
                            this.ai[0] = 1f;
                            this.ai[1] = 0f;
                            this.netUpdate = true;
                        }
                    }
                    float num19 = 12f;
                    float num20 = 0.25f;
                    Vector2 vector = new Vector2(this.position.X + (float)this.width * 0.5f, this.position.Y + (float)this.height * 0.5f);
                    float num21 = num13 - vector.X;
                    float num22 = num14 - vector.Y;
                    float num23 = (float)Math.Sqrt((double)(num21 * num21 + num22 * num22));
                    num23 = num19 / num23;
                    num21 *= num23;
                    num22 *= num23;
                    if (this.velocity.X < num21)
                    {
                        this.velocity.X = this.velocity.X + num20;
                        if (this.velocity.X < 0f && num21 > 0f)
{
                            this.velocity.X = this.velocity.X + num20 * 2f;
                        }
                    }
                    else if (this.velocity.X > num21)
                    {
                        this.velocity.X = this.velocity.X - num20;
                        if (this.velocity.X > 0f && num21 < 0f)
{
                            this.velocity.X = this.velocity.X - num20 * 2f;
                        }
                    }
                    if (this.velocity.Y < num22)
                    {
                        this.velocity.Y = this.velocity.Y + num20;
                        if (this.velocity.Y < 0f && num22 > 0f)
{
                            this.velocity.Y = this.velocity.Y + num20 * 2f;
                        }
                    }
                    else if (this.velocity.Y > num22)
                    {
                        this.velocity.Y = this.velocity.Y - num20;
                        if (this.velocity.Y > 0f && num22 < 0f)
{
                            this.velocity.Y = this.velocity.Y - num20 * 2f;
                        }
                    }
                }
                else if (this.type == 866)
                {
                    if (this.owner == Main.myPlayer && this.damage > 0)
                    {
                        float num24 = this.ai[1];
                        if (this.localAI[0] >= 10f && this.localAI[0] <= 360f)
{
                            int num25 = this.FindTargetWithLineOfSight(800f);
                            this.ai[1] = (float)num25;
                        }
                        else
{
                            this.ai[1] = -1f;
                        }
                        if (this.ai[1] != num24)
{
                            this.netUpdate = true;
                        }
                    }
                    this.localAI[0] += 1f;
                    int num26 = (int)this.ai[1];
                    Vector2 vector2;
                    if (Main.npc.IndexInRange(num26) && Main.npc[num26].CanBeChasedBy(this, false))
                    {
                        vector2 = Main.npc[num26].Center;
                    }
                    else
                    {
                        vector2 = base.Center + this.velocity * 100f;
                        int num27 = 30;
                        if (this.owner != Main.myPlayer)
{
                            num27 = 60;
                        }
                        if (this.localAI[0] >= (float)num27)
{
                            this.ai[0] = 1f;
                            this.ai[1] = 0f;
                            this.netUpdate = true;
                        }
                    }
                    float num28 = 12f;
                    float num29 = 0.25f;
                    Vector2 vector3 = new Vector2(this.position.X + (float)this.width * 0.5f, this.position.Y + (float)this.height * 0.5f);
                    float num30 = vector2.X - vector3.X;
                    float num31 = vector2.Y - vector3.Y;
                    float num32 = (float)Math.Sqrt((double)(num30 * num30 + num31 * num31));
                    num32 = num28 / num32;
                    num30 *= num32;
                    num31 *= num32;
                    if (this.velocity.X < num30)
                    {
                        this.velocity.X = this.velocity.X + num29;
                        if (this.velocity.X < 0f && num30 > 0f)
{
                            this.velocity.X = this.velocity.X + num29 * 2f;
                        }
                    }
                    else if (this.velocity.X > num30)
                    {
                        this.velocity.X = this.velocity.X - num29;
                        if (this.velocity.X > 0f && num30 < 0f)
{
                            this.velocity.X = this.velocity.X - num29 * 2f;
                        }
                    }
                    if (this.velocity.Y < num31)
                    {
                        this.velocity.Y = this.velocity.Y + num29;
                        if (this.velocity.Y < 0f && num31 > 0f)
{
                            this.velocity.Y = this.velocity.Y + num29 * 2f;
                        }
                    }
                    else if (this.velocity.Y > num31)
                    {
                        this.velocity.Y = this.velocity.Y - num29;
                        if (this.velocity.Y > 0f && num31 < 0f)
{
                            this.velocity.Y = this.velocity.Y - num29 * 2f;
                        }
                    }
                }
                else if (this.type == 301)
                {
                    if (Main.player[this.owner].active && !Main.player[this.owner].dead && Main.player[this.owner].controlUseItem)
                    {
                        if (this.ai[1] >= 20f)
{
                            this.ai[0] = 1f;
                            this.ai[1] = 0f;
                            this.velocity = Vector2.Zero;
                            this.netUpdate = true;
                        }
                    }
                    else if (this.ai[1] >= 100f)
                    {
                        this.ai[0] = 1f;
                        this.ai[1] = 0f;
                        this.velocity = Vector2.Zero;
                        this.netUpdate = true;
                    }
                }
                else if (this.ai[1] >= 30f)
                {
                    this.ai[0] = 1f;
                    this.ai[1] = 0f;
                    this.netUpdate = true;
                }
            }
            else if (ProjectileID.Sets.IsAPhaseblade[this.type] && this.ai[0] == 2f)
            {
                if (this.velocity.Y < 0f)
                {
                    this.velocity.Y = this.velocity.Y * 0.5f;
                }
                this.rotation = 2.335f;
                this.velocity.X = 0f;
                this.velocity.Y = this.velocity.Y + 1f;
                if (this.localAI[1] == 0f)
                {
                    if (this.type == 1074)
                    {
                        this.localAI[0] = -1f;
                        SoundEngine.PlaySound(SoundID.Item182, this.position, 0f, 1f);
                    }
                    else
                    {
                        SoundEngine.PlaySound(SoundID.Item15, this.position, 0f, 1f);
                    }
                    this.localAI[1] = 1f;
                }
            }
            else
            {
                if (ProjectileID.Sets.IsAPhaseblade[this.type])
                {
                    if (base.Center.X < Main.player[this.owner].Center.X)
                    {
                        this.direction = -1;
                    }
                    else
                    {
                        this.direction = 1;
                    }
                    this.rotation = this.velocity.ToRotation() - 2.335f;
                    if (this.localAI[0] <= 0f)
                    {
                        if (this.type == 1074)
{
                            if (this.localAI[0] < 0f)
{
                                SoundEngine.PlaySound(SoundID.Item182, this.position, -0.2f, 1f);
                            }
                            else
{
                                SoundEngine.PlaySound(SoundID.Item7, this.position, -0.5f, 1f);
                            }
                        }
                        else
{
                            SoundEngine.PlaySound(SoundID.Item15, this.position, 0f, 1f);
                        }
                        this.localAI[0] = 1f;
                    }
                }
                this.tileCollide = false;
                float num33 = 9f;
                float num34 = 0.4f;
                if (ProjectileID.Sets.IsAPhaseblade[this.type])
                {
                    num33 = 40f;
                    num34 = 3f;
                }
                else if (this.type == 1000)
                {
                    num33 = 9.5f;
                }
                else if (this.type == 19)
                {
                    num33 = 20f;
                    num34 = 1.5f;
                }
                else if (this.type == 33)
                {
                    num33 = 18f;
                    num34 = 1.2f;
                }
                else if (this.type == 182)
                {
                    num33 = 16f;
                    num34 = 1.2f;
                }
                else if (this.type == 866)
                {
                    num33 = 16f;
                    num34 = 1.2f;
                }
                else if (this.type == 106)
                {
                    num33 = 16f;
                    num34 = 1.2f;
                }
                else if (this.type == 272)
                {
                    num33 = 20f;
                    num34 = 1.5f;
                }
                else if (this.type == 333)
                {
                    num33 = 12f;
                    num34 = 0.6f;
                }
                else if (this.type == 301)
                {
                    num33 = 15f;
                    num34 = 3f;
                }
                else if (this.type == 320)
                {
                    num33 = 15f;
                    num34 = 3f;
                }
                else if (this.type == 383)
                {
                    num33 = 16f;
                    num34 = 4f;
                }
                Vector2 vector4 = new Vector2(this.position.X + (float)this.width * 0.5f, this.position.Y + (float)this.height * 0.5f);
                float num35 = Main.player[this.owner].position.X + (float)(Main.player[this.owner].width / 2) - vector4.X;
                float num36 = Main.player[this.owner].position.Y + (float)(Main.player[this.owner].height / 2) - vector4.Y;
                float num37 = (float)Math.Sqrt((double)(num35 * num35 + num36 * num36));
                if (ProjectileID.Sets.IsAPhaseblade[this.type])
                {
                    this.extraUpdates = (int)(num37 / 3000f);
                    if (this.type == 1074)
                    {
                        this.extraUpdates++;
                    }
                    if (this.extraUpdates > 20)
                    {
                        this.extraUpdates = 20;
                    }
                }
                else if (this.type == 301)
                {
                    if (num37 > 6000f)
                    {
                        this.Kill();
                    }
                }
                else if (num37 > 3000f)
                {
                    this.Kill();
                }
                num37 = num33 / num37;
                num35 *= num37;
                num36 *= num37;
                if (this.type == 383)
                {
                    Vector2 vector5 = new Vector2(num35, num36) - this.velocity;
                    if (vector5 != Vector2.Zero)
                    {
                        Vector2 vector6 = vector5;
                        vector6.Normalize();
                        this.velocity += vector6 * Math.Min(num34, vector5.Length());
                    }
                }
                else
                {
                    if (this.velocity.X < num35)
                    {
                        this.velocity.X = this.velocity.X + num34;
                        if (this.velocity.X < 0f && num35 > 0f)
{
                            this.velocity.X = this.velocity.X + num34;
                        }
                    }
                    else if (this.velocity.X > num35)
                    {
                        this.velocity.X = this.velocity.X - num34;
                        if (this.velocity.X > 0f && num35 < 0f)
{
                            this.velocity.X = this.velocity.X - num34;
                        }
                    }
                    if (this.velocity.Y < num36)
                    {
                        this.velocity.Y = this.velocity.Y + num34;
                        if (this.velocity.Y < 0f && num36 > 0f)
{
                            this.velocity.Y = this.velocity.Y + num34;
                        }
                    }
                    else if (this.velocity.Y > num36)
                    {
                        this.velocity.Y = this.velocity.Y - num34;
                        if (this.velocity.Y > 0f && num36 < 0f)
{
                            this.velocity.Y = this.velocity.Y - num34;
                        }
                    }
                }
                if (Main.myPlayer == this.owner)
                {
                    Rectangle rectangle = new Rectangle((int)this.position.X, (int)this.position.Y, this.width, this.height);
                    Rectangle rectangle2 = new Rectangle((int)Main.player[this.owner].position.X, (int)Main.player[this.owner].position.Y, Main.player[this.owner].width, Main.player[this.owner].height);
                    if (rectangle.Intersects(rectangle2))
                    {
                        this.Kill();
                    }
                }
            }
            if (this.type == 106)
            {
                this.rotation += 0.3f * (float)this.direction;
                return;
            }
            if (this.type == 866)
            {
                this.rotation = this.velocity.ToRotation();
                if (Main.rand.Next(2) == 0)
                {
                    int num38 = Dust.NewDust(this.position, this.width, this.height, 212, 0f, 0f, 0, default(Color), 1f);
                    Main.dust[num38].velocity *= 0.1f;
                    Main.dust[num38].noGravity = true;
                    return;
                }
            }
            else if (this.type == 383)
            {
                if (this.ai[0] == 0f)
                {
                    Vector2 vector7 = this.velocity;
                    vector7 = vector7.SafeNormalize(Vector2.Zero);
                    this.rotation = (float)Math.Atan2((double)vector7.Y, (double)vector7.X) + 1.57f;
                    return;
                }
                Vector2 vector8 = base.Center - Main.player[this.owner].Center;
                vector8 = vector8.SafeNormalize(Vector2.Zero);
                this.rotation = (float)Math.Atan2((double)vector8.Y, (double)vector8.X) + 1.57f;
                return;
            }
            else if (this.type == 301)
            {
                if (this.ai[0] != 0f)
                {
                    this.rotation += 0.4f * (float)this.direction;
                    return;
                }
                this.rotation = this.velocity.ToRotation() + 0.7853982f;
                if (Main.rand.Next(2) == 0)
                {
                    int num39 = Dust.NewDust(this.position, this.width, this.height, 57, this.velocity.X * 0.2f, this.velocity.Y * 0.2f, 200, default(Color), 1.2f);
                    Main.dust[num39].velocity += this.velocity * 0.3f;
                    Main.dust[num39].velocity *= 0.2f;
                    Main.dust[num39].noGravity = true;
                }
                if (Main.rand.Next(3) == 0)
                {
                    int num40 = Dust.NewDust(this.position, this.width, this.height, 43, 0f, 0f, 254, default(Color), 0.3f);
                    Main.dust[num40].velocity += this.velocity * 0.5f;
                    Main.dust[num40].velocity *= 0.5f;
                    Main.dust[num40].noGravity = true;
                    return;
                }
            }
            else if (!ProjectileID.Sets.IsAPhaseblade[this.type])
            {
                this.rotation += 0.4f * (float)this.direction;
            }
        }
References Terraria.Player.active, Terraria.Lighting.AddLight(), System.Math.Atan2(), Microsoft.Xna.Framework.Color.B, Terraria.NPC.CanBeChasedBy(), Terraria.Collision.CanHit(), Terraria.Entity.Center, Terraria.Player.controlUseItem, Terraria.Player.dead, Microsoft.Xna.Framework.Vector2.Distance(), Terraria.Main.dust, Microsoft.Xna.Framework.Color.G, Terraria.Item.GetPhaseColor(), Terraria.Entity.height, Terraria.Player.HeldItem, int, Microsoft.Xna.Framework.Rectangle.Intersects(), Terraria.WorldGen.InWorld(), Terraria.ID.ProjectileID.Sets.IsAPhaseblade, Terraria.ID.SoundID.Item15, Terraria.ID.SoundID.Item182, Terraria.ID.SoundID.Item7, Microsoft.Xna.Framework.Vector2.Length(), Terraria.Main.maxNPCs, System.Math.Min(), Terraria.Main.myPlayer, Terraria.Dust.NewDust(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Microsoft.Xna.Framework.Vector2.Normalize(), Terraria.Main.npc, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Microsoft.Xna.Framework.Color.R, Terraria.Main.rand, Terraria.Dust.scale, Terraria.Item.shoot, System.Math.Sqrt(), Terraria.Dust.velocity, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.