Terraria Decompiled: Terraria.Projectile.AI_166_Dove
AI_166_Dove()
void Terraria.Projectile.AI_166_Dove () inline private
Definition at line 47992 of file Projectile.cs.
        {
            bool flag = this.type == 855;
            if (this.localAI[0] == 0f)
            {
                this.localAI[0] = 1f;
                this.frame = Main.rand.Next(4);
            }
            int num = 4;
            if (flag)
            {
                num = 6;
            }
            int num2 = this.frameCounter + 1;
            this.frameCounter = num2;
            if (num2 > num)
            {
                this.frameCounter = 0;
                num2 = this.frame + 1;
                this.frame = num2;
                if (num2 > 3)
                {
                    this.frame = 0;
                }
            }
            this.spriteDirection = -1;
            if (this.velocity.X > 0f)
            {
                this.spriteDirection = 1;
            }
            if (flag)
            {
                float num3 = 1f - (float)this.alpha / 255f;
                Vector3 vector = new Vector3(1f, 0.6f, 0.1f) * num3;
                Lighting.AddLight(base.Center, vector);
                this.rotation = this.velocity.X * 0.2f;
                if (this.velocity.Y < -1f)
                {
                    this.velocity.Y = this.velocity.Y * 0.99f;
                }
                else
                {
                    this.velocity.Y = this.velocity.Y + (float)Math.Sin((double)((float)(this.timeLeft % 200) / 200f * 6.2831855f)) * 0.25f;
                    if (this.velocity.Y > 0.5f)
                    {
                        this.velocity.Y = this.velocity.Y * 0.8f;
                    }
                    this.velocity.Y = MathHelper.Clamp(this.velocity.Y, -1.5f, 1.5f);
                }
                float num4 = Main.WindForVisuals;
                if (num4 == 0f)
                {
                    num4 = 0.1f;
                }
                this.velocity.X = this.velocity.X + 0.0525f * num4;
                this.velocity.X = MathHelper.Clamp(this.velocity.X, -2f, 2f);
            }
            else
            {
                this.rotation = this.velocity.X * 0.15f;
                this.velocity.Y = this.velocity.Y - 0.025f;
                if (this.velocity.Y < -3f)
                {
                    this.velocity.Y = -3f;
                }
                this.velocity.X = MathHelper.Clamp(this.velocity.X, -5f, 5f);
            }
            if (this.timeLeft < 90)
            {
                this.alpha += 3;
            }
            if (this.alpha >= 255)
            {
                this.Kill();
            }
        }
References Terraria.Lighting.AddLight(), Microsoft.Xna.Framework.MathHelper.Clamp(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, System.Math.Sin(), and Terraria.Main.WindForVisuals.