Terraria Decompiled: Terraria.Projectile.AI_105_SporeSac
AI_105_SporeSac()
void Terraria.Projectile.AI_105_SporeSac () inline private
Definition at line 40389 of file Projectile.cs.
        {
            float num = 1f - (float)this.alpha / 255f;
            num *= this.scale;
            Lighting.AddLight(base.Center, 0.2f * num, 0.275f * num, 0.075f * num);
            bool flag = this.type == 567 || this.type == 568;
            this.localAI[0] += 1f;
            if (this.localAI[0] >= 90f)
            {
                this.localAI[0] *= -1f;
            }
            if (this.localAI[0] >= 0f)
            {
                this.scale += 0.003f;
            }
            else
            {
                this.scale -= 0.003f;
            }
            this.rotation += 0.0025f * this.scale;
            float num2 = 1f;
            float num3 = 1f;
            if (this.identity % 6 == 0)
            {
                num3 *= -1f;
            }
            if (this.identity % 6 == 1)
            {
                num2 *= -1f;
            }
            if (this.identity % 6 == 2)
            {
                num3 *= -1f;
                num2 *= -1f;
            }
            if (this.identity % 6 == 3)
            {
                num3 = 0f;
            }
            if (this.identity % 6 == 4)
            {
                num2 = 0f;
            }
            this.localAI[1] += 1f;
            if (this.localAI[1] > 60f)
            {
                this.localAI[1] = -180f;
            }
            if (this.localAI[1] >= -60f)
            {
                this.velocity.X = this.velocity.X + 0.002f * num3;
                this.velocity.Y = this.velocity.Y + 0.002f * num2;
            }
            else
            {
                this.velocity.X = this.velocity.X - 0.002f * num3;
                this.velocity.Y = this.velocity.Y - 0.002f * num2;
            }
            this.ai[0] += 1f;
            if (this.ai[0] > 5400f)
            {
                this.damage = 0;
                this.ai[1] = 1f;
                if (this.alpha < 255)
                {
                    this.alpha += 5;
                    if (this.alpha > 255)
                    {
                        this.alpha = 255;
                    }
                }
                else if (this.owner == Main.myPlayer)
                {
                    this.Kill();
                }
            }
            else
            {
                float num4 = (base.Center - Main.player[this.owner].Center).Length() / 100f;
                if (num4 > 4f)
                {
                    num4 *= 1.1f;
                }
                if (num4 > 5f)
                {
                    num4 *= 1.2f;
                }
                if (num4 > 6f)
                {
                    num4 *= 1.3f;
                }
                if (num4 > 7f)
                {
                    num4 *= 1.4f;
                }
                if (num4 > 8f)
                {
                    num4 *= 1.5f;
                }
                if (num4 > 9f)
                {
                    num4 *= 1.6f;
                }
                if (num4 > 10f)
                {
                    num4 *= 1.7f;
                }
                if (flag && !Main.player[this.owner].sporeSac)
                {
                    num4 += 100f;
                }
                this.ai[0] += num4;
                if (this.alpha > 50)
                {
                    this.alpha -= 10;
                    if (this.alpha < 50)
                    {
                        this.alpha = 50;
                    }
                }
            }
            bool flag2 = false;
            Vector2 center = new Vector2(0f, 0f);
            float num5 = 340f;
            for (int i = 0; i < Main.maxNPCs; i++)
            {
                if (Main.npc[i].CanBeChasedBy(this, false))
                {
                    float num6 = Main.npc[i].position.X + (float)(Main.npc[i].width / 2);
                    float num7 = Main.npc[i].position.Y + (float)(Main.npc[i].height / 2);
                    float num8 = Math.Abs(this.position.X + (float)(this.width / 2) - num6) + Math.Abs(this.position.Y + (float)(this.height / 2) - num7);
                    if (num8 < num5)
                    {
                        num5 = num8;
                        center = Main.npc[i].Center;
                        flag2 = true;
                    }
                }
            }
            if (flag2)
            {
                Vector2 vector = center - base.Center;
                vector.Normalize();
                vector *= 4f;
                this.velocity = (this.velocity * 40f + vector) / 41f;
                return;
            }
            if ((double)this.velocity.Length() > 0.2)
            {
                this.velocity *= 0.98f;
            }
        }
References System.Math.Abs(), Terraria.Lighting.AddLight(), Terraria.NPC.CanBeChasedBy(), Terraria.Entity.Center, Terraria.Entity.height, Terraria.Main.maxNPCs, Terraria.Main.myPlayer, Microsoft.Xna.Framework.Vector2.Normalize(), Terraria.Main.npc, Terraria.Main.player, Terraria.Entity.position, Terraria.Player.sporeSac, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.