Terraria Decompiled: Terraria.Projectile.Damage_GetHitbox
Damage_GetHitbox()
Rectangle Terraria.Projectile.Damage_GetHitbox () inline private
Definition at line 13895 of file Projectile.cs.
        {
            Rectangle rectangle = new Rectangle((int)this.position.X, (int)this.position.Y, this.width, this.height);
            if (ProjectileID.Sets.IsAPhaseblade[this.type] && this.ai[0] == 2f)
            {
                rectangle.Inflate(-14, 0);
            }
            if (this.type == 301 && this.localAI[0] > 0f)
            {
                rectangle.Inflate(-this.width / 2, -this.height / 2);
                rectangle.Inflate((int)(this.localAI[0] / 2f), (int)this.localAI[0] / 2);
                this.localAI[0] = -1f;
            }
            if (this.type == 383 && this.localAI[0] > 0f)
            {
                rectangle.Inflate(-this.width / 2, -this.height / 2);
                rectangle.Inflate((int)(this.localAI[0] / 2f), (int)this.localAI[0] / 2);
                this.localAI[0] = -1f;
            }
            if (this.type == 262 && this.localAI[0] > 0f)
            {
                rectangle.Inflate(-this.width / 2, -this.height / 2);
                rectangle.Inflate((int)(this.localAI[0] / 2f), (int)this.localAI[0] / 2);
                this.localAI[0] = -1f;
            }
            if (this.type == 101)
            {
                rectangle.Inflate(30, 30);
            }
            if (this.type == 1024)
            {
                rectangle.Inflate(6, 6);
            }
            if (this.type == 1023)
            {
                rectangle.Inflate(8, 8);
            }
            if (this.type == 85)
            {
                int num = (int)Utils.Remap(this.localAI[0], 0f, 72f, 10f, 40f, true);
                rectangle.Inflate(num, num);
            }
            if (this.type == 1106)
            {
                int num2 = (int)Utils.Remap(this.localAI[0], 0f, 72f, 0f, 20f, true);
                rectangle.Inflate(num2, num2);
            }
            if (this.type == 188)
            {
                rectangle.Inflate(20, 20);
            }
            if (this.aiStyle == 29)
            {
                rectangle.Inflate(4, 4);
            }
            if (this.type == 967)
            {
                rectangle.Inflate(10, 10);
            }
            return rectangle;
        }
References Microsoft.Xna.Framework.Rectangle.Inflate(), int, Terraria.ID.ProjectileID.Sets.IsAPhaseblade, and Terraria.Utils.Remap().
Referenced by Terraria.Projectile.Damage().