Terraria Decompiled: Terraria.Projectile.AI_066_TryInterceptingTarget
AI_066_TryInterceptingTarget()
void Terraria.Projectile.AI_066_TryInterceptingTarget (Vector2 targetDir, Vector2 targetVelocity, float speed) inline private
Definition at line 42418 of file Projectile.cs.
        {
            float num = 5f;
            float num2 = 30f;
            float num3 = num2 + num;
            int num4 = 1;
            int num5 = 4;
            int num6 = 2;
            bool flag = false;
            if (this.type == 533)
            {
                num4 = 2;
            }
            if (this.type == 388)
            {
                num4 = 2;
                num2 = 40f;
            }
            targetVelocity /= (float)num4;
            float num7 = 1f;
            while (num7 <= 1.5f)
            {
                Utils.ChaseResults chaseResults = Utils.GetChaseResults(base.Center, speed, targetDir, targetVelocity);
                if (chaseResults.InterceptionHappens && chaseResults.InterceptionTime <= num3)
                {
                    this.velocity = chaseResults.ChaserVelocity;
                    if (flag)
                    {
                        int num8 = (int)Utils.Clamp<float>((float)Math.Ceiling((double)chaseResults.InterceptionTime) + (float)num6, (float)num5, num2 - 1f) / num4;
                        float num9 = num2 / (float)num4 - (float)num8;
                        this.ai[1] += num9 * (float)num4;
                        return;
                    }
                    break;
                }
                else
                {
                    num7 += 0.1f;
                }
            }
        }
References System.Math.Ceiling(), Terraria.Utils.ChaseResults.ChaserVelocity, Terraria.Utils.Clamp(), Terraria.Utils.GetChaseResults(), int, Terraria.Utils.ChaseResults.InterceptionHappens, and Terraria.Utils.ChaseResults.InterceptionTime.