Terraria Decompiled: Terraria.Projectile.AI_139_ExplosiveTrapExplosion
AI_139_ExplosiveTrapExplosion()
void Terraria.Projectile.AI_139_ExplosiveTrapExplosion () inline private
Definition at line 69865 of file Projectile.cs.
        {
            int num = Main.projFrames[this.type];
            int num2 = 3;
            this.alpha -= 25;
            if (this.alpha < 0)
            {
                this.alpha = 0;
            }
            if (this.localAI[0] == 0f)
            {
                this.localAI[0] = 1f;
            }
            int num3 = this.frameCounter + 1;
            this.frameCounter = num3;
            if (num3 >= num2)
            {
                this.frameCounter = 0;
                num3 = this.frame + 1;
                this.frame = num3;
                if (num3 >= num)
                {
                    this.Kill();
                    return;
                }
            }
            DelegateMethods.v3_1 = new Vector3(1.3f, 0.9f, 0.2f);
            Utils.PlotTileLine(base.Top, base.Bottom, 2f, new Utils.TileActionAttempt(DelegateMethods.CastLightOpen));
        }
References Terraria.DelegateMethods.CastLightOpen(), Terraria.Utils.PlotTileLine(), Terraria.Main.projFrames, and Terraria.Utils.TileActionAttempt().