Terraria Decompiled: Terraria.Projectile.GetLastPrismHue
GetLastPrismHue()
float Terraria.Projectile.GetLastPrismHue (float laserIndex, ref float laserLuminance, ref float laserAlphaMultiplier) inline
Definition at line 20970 of file Projectile.cs.
        {
            if (Main.player[this.owner].active)
            {
                double timeForVisualEffects = Main.timeForVisualEffects;
                string name = Main.player[this.owner].name;
                uint num = <PrivateImplementationDetails>.ComputeStringHash(name);
                if (num <= 2447758250U)
                {
                    if (num <= 1566394895U)
                    {
                        if (num <= 708199672U)
{
                            if (num <= 214021753U)
{
                                if (num != 62183149U)
{
                                    if (num != 208328621U)
{
                                        if (num != 214021753U)
{
                                            goto IL_1121;
                                        }
                                        if (!(name == "Yoraiz0r"))
{
                                            goto IL_1121;
                                        }
                                    }
                                    else
{
                                        if (!(name == "Jopojelly"))
{
                                            goto IL_1121;
                                        }
                                        goto IL_0D68;
                                    }
                                }
                                else
{
                                    if (!(name == "ManaUser"))
{
                                        goto IL_1121;
                                    }
                                    return 0.49f + (float)Math.Cos(timeForVisualEffects / 140.0 * 6.2831854820251465) * 0.08f;
                                }
                            }
                            else if (num != 541614085U)
{
                                if (num != 680803461U)
{
                                    if (num != 708199672U)
{
                                        goto IL_1121;
                                    }
                                    if (!(name == "Kazzymodus"))
{
                                        goto IL_1121;
                                    }
                                    laserLuminance = MathHelper.Lerp(0.6f, 0.8f, Utils.GetLerpValue(-1f, 1f, (float)Math.Cos(timeForVisualEffects / 90.0 * 6.2831854820251465), false));
                                    laserAlphaMultiplier = 0.3f;
                                    return 0.33f;
                                }
                                else
{
                                    if (!(name == "Mid"))
{
                                        goto IL_1121;
                                    }
                                    laserLuminance = 0.25f;
                                    laserAlphaMultiplier = 0.4f;
                                    return 0.86f + (float)Math.Cos(timeForVisualEffects / 270.0 * 6.2831854820251465) * 0.13f;
                                }
                            }
                            else
{
                                if (!(name == "Aeroblop"))
{
                                    goto IL_1121;
                                }
                                return 0.25f + (float)Math.Cos(timeForVisualEffects / 180.0 * 6.2831854820251465) * 0.1f;
                            }
                        }
                        else if (num <= 1139021827U)
{
                            if (num != 869206474U)
{
                                if (num != 1091948930U)
{
                                    if (num != 1139021827U)
{
                                        goto IL_1121;
                                    }
                                    if (!(name == "Jaxrud"))
{
                                        goto IL_1121;
                                    }
                                    return MathHelper.Lerp(0.18055555f, 0.43611112f, Utils.Turn01ToCyclic010(laserIndex / 6f));
                                }
                                else
{
                                    if (!(name == "Random"))
{
                                        goto IL_1121;
                                    }
                                    return Main.rand.NextFloat();
                                }
                            }
                            else
{
                                if (!(name == "CheesyPaninie"))
{
                                    goto IL_1121;
                                }
                                return 0.98f + (float)Math.Cos(timeForVisualEffects / 90.0 * 6.2831854820251465) * 0.105f;
                            }
                        }
                        else if (num != 1284017581U)
{
                            if (num != 1335914532U)
{
                                if (num != 1566394895U)
{
                                    goto IL_1121;
                                }
                                if (!(name == "Tsuki"))
{
                                    goto IL_1121;
                                }
                            }
                            else
{
                                if (!(name == "Loki"))
{
                                    goto IL_1121;
                                }
                                laserLuminance = MathHelper.Lerp(0f, 0.3f, Utils.GetLerpValue(-1f, 1f, (float)Math.Cos(timeForVisualEffects / 5.0 * 6.2831854820251465), false));
                                laserAlphaMultiplier = 0.4f;
                                return 0f;
                            }
                        }
                        else
{
                            if (!(name == "ppowersteef"))
{
                                goto IL_1121;
                            }
                            laserLuminance = MathHelper.Lerp(0.1f, 0.5f, Utils.GetLerpValue(-1f, 1f, (float)Math.Cos(timeForVisualEffects / 105.0 * 6.2831854820251465), false));
                            laserAlphaMultiplier = 0.25f;
                            return 0.6f;
                        }
                        return 0.92f;
                    }
                    if (num <= 1923781348U)
                    {
                        if (num <= 1752923523U)
{
                            if (num != 1650374817U)
{
                                if (num != 1747396969U)
{
                                    if (num != 1752923523U)
{
                                        goto IL_1121;
                                    }
                                    if (!(name == "Darthkitten"))
{
                                        goto IL_1121;
                                    }
                                    laserLuminance = MathHelper.Lerp(0.4f, 0.9f, Utils.GetLerpValue(-1f, 1f, (float)Math.Cos(timeForVisualEffects / 120.0 * 6.2831854820251465), false));
                                    laserAlphaMultiplier = 0.3f;
                                    return 1f;
                                }
                                else
{
                                    if (!(name == "Leinfors"))
{
                                        goto IL_1121;
                                    }
                                    return 0.73f + (float)Math.Cos(timeForVisualEffects / 3.0 * 6.2831854820251465) * 0.03f;
                                }
                            }
                            else
{
                                if (!(name == "Aurora3500"))
{
                                    goto IL_1121;
                                }
                                laserLuminance = MathHelper.Lerp(0f, 0.5f, Utils.GetLerpValue(-1f, 1f, (float)Math.Cos(timeForVisualEffects / 105.0 * 6.2831854820251465), false));
                                laserAlphaMultiplier = 0.25f;
                                return 0.35f;
                            }
                        }
                        else if (num != 1773024879U)
{
                            if (num != 1863568037U)
{
                                if (num != 1923781348U)
{
                                    goto IL_1121;
                                }
                                if (!(name == "Alchemystics"))
{
                                    goto IL_1121;
                                }
                                return 0.73f + (float)Math.Cos(timeForVisualEffects / 180.0 * 6.2831854820251465) * 0.18f;
                            }
                            else
{
                                if (!(name == "Antithesis"))
{
                                    goto IL_1121;
                                }
                                laserLuminance = 0.25f;
                                laserAlphaMultiplier = 0.4f;
                                return 0.7f + (float)Math.Cos(timeForVisualEffects / 180.0 * 6.2831854820251465) * 0.05f;
                            }
                        }
                        else
{
                            if (!(name == "Artyrian"))
{
                                goto IL_1121;
                            }
                            float num2 = Utils.PingPongFrom01To010(laserIndex / 6f);
                            num2 = MathHelper.SmoothStep(0f, 1f, num2);
                            num2 = MathHelper.SmoothStep(0f, 1f, num2);
                            return Main.rgbToHsl(Color.Lerp(new Color(1f, 0.31f, 0f), new Color(0.7f, 0f, 1f), num2)).X;
                        }
                    }
                    else
                    {
                        if (num <= 2148467107U)
{
                            if (num != 2016962940U)
{
                                if (num != 2118543838U)
{
                                    if (num != 2148467107U)
{
                                        goto IL_1121;
                                    }
                                    if (!(name == "Ghostar"))
{
                                        goto IL_1121;
                                    }
                                    laserLuminance = MathHelper.Lerp(0.4f, 0.7f, Utils.GetLerpValue(-1f, 1f, (float)Math.Cos(timeForVisualEffects / 120.0 * 6.2831854820251465), false));
                                    laserAlphaMultiplier = 0.3f;
                                    return 0.66f;
                                }
                                else if (!(name == "Darkhalis"))
{
                                    goto IL_1121;
                                }
                            }
                            else if (!(name == "Arkhalis"))
{
                                goto IL_1121;
                            }
                            return 0.75f + (float)Math.Cos(timeForVisualEffects / 180.0 * 6.2831854820251465) * 0.07f;
                        }
                        if (num <= 2386938644U)
{
                            if (num != 2351718047U)
{
                                if (num != 2386938644U)
{
                                    goto IL_1121;
                                }
                                if (!(name == "Sigma"))
{
                                    goto IL_1121;
                                }
                                return 0.06f + (float)Math.Cos(timeForVisualEffects / 180.0 * 6.2831854820251465) * 0.06f;
                            }
                            else
{
                                if (!(name == "Nimbus"))
{
                                    goto IL_1121;
                                }
                                laserLuminance = MathHelper.Lerp(0f, 0.3f, Utils.GetLerpValue(-1f, 1f, (float)Math.Cos(timeForVisualEffects / 20.0 * 6.2831854820251465), false));
                                laserAlphaMultiplier = 0.2f;
                                return 0.75f;
                            }
                        }
                        else if (num != 2412408538U)
{
                            if (num != 2447758250U)
{
                                goto IL_1121;
                            }
                            if (!(name == "W1K"))
{
                                goto IL_1121;
                            }
                            return 0.75f + (float)Math.Cos(timeForVisualEffects / 120.0 * 6.2831854820251465) * 0.05f;
                        }
                        else
{
                            if (!(name == "Vulpes Inculta"))
{
                                goto IL_1121;
                            }
                            return 0.7f + (float)Math.Cos(timeForVisualEffects / 180.0 * 6.2831854820251465) * 0.05f;
                        }
                    }
                }
                else if (num <= 3428214922U)
                {
                    if (num <= 3035519103U)
                    {
                        if (num <= 2716996079U)
{
                            if (num != 2568166278U)
{
                                if (num != 2639310093U)
{
                                    if (num != 2716996079U)
{
                                        goto IL_1121;
                                    }
                                    if (!(name == "GreyL1me"))
{
                                        goto IL_1121;
                                    }
                                    laserLuminance = MathHelper.Lerp(0.4f, 0.6f, Utils.GetLerpValue(-1f, 1f, (float)Math.Cos(timeForVisualEffects / 105.0 * 6.2831854820251465), false));
                                    laserAlphaMultiplier = 0.3f;
                                    return 0.24f;
                                }
                                else if (!(name == "jopojelly"))
{
                                    goto IL_1121;
                                }
                            }
                            else
{
                                if (!(name == "Khaios"))
{
                                    goto IL_1121;
                                }
                                laserLuminance = MathHelper.Lerp(0f, 0.1f, Utils.GetLerpValue(-1f, 1f, (float)Math.Cos(timeForVisualEffects / 105.0 * 6.2831854820251465), false));
                                laserAlphaMultiplier = 0.25f;
                                return 0.35f;
                            }
                        }
                        else if (num != 2734667832U)
{
                            if (num != 2905540048U)
{
                                if (num != 3035519103U)
{
                                    goto IL_1121;
                                }
                                if (!(name == "RBrandon"))
{
                                    goto IL_1121;
                                }
                                laserLuminance = MathHelper.Lerp(0f, 0.5f, Utils.GetLerpValue(-1f, 1f, (float)Math.Cos(timeForVisualEffects / 105.0 * 6.2831854820251465), false));
                                laserAlphaMultiplier = 0.4f;
                                return 1f;
                            }
                            else
{
                                if (!(name == "Criddle"))
{
                                    goto IL_1121;
                                }
                                laserLuminance = 0.75f + (float)Math.Cos(timeForVisualEffects / 150.0 * 6.2831854820251465) * -0.25f;
                                return 0.89f + (float)Math.Cos(timeForVisualEffects / 300.0 * 6.2831854820251465) * 0.17f;
                            }
                        }
                        else
{
                            if (!(name == "darthmorf"))
{
                                goto IL_1121;
                            }
                            laserLuminance = MathHelper.Lerp(0f, 0.2f, Utils.GetLerpValue(-1f, 1f, (float)Math.Cos(timeForVisualEffects / 105.0 * 6.2831854820251465), false));
                            laserAlphaMultiplier = 0.4f;
                            return 0f;
                        }
                    }
                    else if (num <= 3198660749U)
                    {
                        if (num != 3055308131U)
{
                            if (num != 3094522306U)
{
                                if (num != 3198660749U)
{
                                    goto IL_1121;
                                }
                                if (!(name == "Crowno"))
{
                                    goto IL_1121;
                                }
                                laserLuminance = MathHelper.Lerp(0.25f, 0.4f, Utils.GetLerpValue(-1f, 1f, (float)Math.Cos(timeForVisualEffects / 105.0 * 6.2831854820251465), false));
                                laserAlphaMultiplier = 0.5f;
                                return MathHelper.Lerp(0.70555556f, 0.78333336f, Utils.Turn01ToCyclic010(laserIndex / 6f));
                            }
                            else
{
                                if (!(name == "Bame"))
{
                                    goto IL_1121;
                                }
                                float num3 = Utils.PingPongFrom01To010(laserIndex / 6f);
                                num3 = MathHelper.SmoothStep(0f, 1f, num3);
                                num3 = MathHelper.SmoothStep(0f, 1f, num3);
                                return Main.rgbToHsl(Color.Lerp(Color.Yellow, new Color(0.2f, 0f, 0.7f), num3)).X;
                            }
                        }
                        else
{
                            if (!(name == "Waze3174"))
{
                                goto IL_1121;
                            }
                            return 0.38f + (float)Math.Cos(timeForVisualEffects / 90.0 * 6.2831854820251465) * 0.24f;
                        }
                    }
                    else if (num != 3229605002U)
                    {
                        if (num != 3276909722U)
{
                            if (num != 3428214922U)
{
                                goto IL_1121;
                            }
                            if (!(name == "Nike Leon"))
{
                                goto IL_1121;
                            }
                            return 0.07f + (float)Math.Cos(timeForVisualEffects / 180.0 * 6.2831854820251465) * 0.04f;
                        }
                        else
{
                            if (!(name == "Serenity"))
{
                                goto IL_1121;
                            }
                            laserLuminance = MathHelper.Lerp(0.9f, 0.65f, Utils.GetLerpValue(-1f, 1f, (float)Math.Cos(timeForVisualEffects / 120.0 * 6.2831854820251465), false));
                            laserAlphaMultiplier = 0.3f;
                            return 0.85f;
                        }
                    }
                    else
                    {
                        if (!(name == "Lazure"))
{
                            goto IL_1121;
                        }
                        return MathHelper.Lerp(0.53333336f, 0.9222222f, Utils.Turn01ToCyclic010(laserIndex / 6f));
                    }
                }
                else if (num <= 3966071759U)
                {
                    if (num <= 3718845703U)
                    {
                        if (num != 3507409723U)
{
                            if (num != 3645672011U)
{
                                if (num != 3718845703U)
{
                                    goto IL_1121;
                                }
                                if (!(name == "Zoomo"))
{
                                    goto IL_1121;
                                }
                                return 0.77f;
                            }
                            else
{
                                if (!(name == "Xman101"))
{
                                    goto IL_1121;
                                }
                                laserLuminance = MathHelper.Lerp(0.9f, 0.55f, Utils.GetLerpValue(-1f, 1f, (float)Math.Cos(timeForVisualEffects / 120.0 * 6.2831854820251465), false));
                                laserAlphaMultiplier = 0.2f;
                                return 0.33f;
                            }
                        }
                        else
{
                            if (!(name == "Cenx"))
{
                                goto IL_1121;
                            }
                            float num4 = Utils.PingPongFrom01To010(laserIndex / 6f);
                            num4 = MathHelper.SmoothStep(0f, 1f, num4);
                            num4 = MathHelper.SmoothStep(0f, 1f, num4);
                            return Main.rgbToHsl(Color.Lerp(new Color(0.3f, 1f, 0.2f), Color.HotPink, num4)).X;
                        }
                    }
                    else if (num != 3731670101U)
                    {
                        if (num != 3898742756U)
{
                            if (num != 3966071759U)
{
                                goto IL_1121;
                            }
                            if (!(name == "Unit One"))
{
                                goto IL_1121;
                            }
                            return 0.38f + (float)Math.Cos(timeForVisualEffects / 90.0 * 6.2831854820251465) * 0.24f;
                        }
                        else
{
                            if (!(name == "Suweeka"))
{
                                goto IL_1121;
                            }
                            return 0.5f + (float)Math.Cos(timeForVisualEffects / 180.0 * 6.2831854820251465) * 0.18f;
                        }
                    }
                    else
                    {
                        if (!(name == "Redigit"))
{
                            goto IL_1121;
                        }
                        return 0.7f;
                    }
                }
                else if (num <= 4005152619U)
                {
                    if (num != 3972042669U)
                    {
                        if (num != 3977692559U)
{
                            if (num != 4005152619U)
{
                                goto IL_1121;
                            }
                            if (!(name == "Doylee"))
{
                                goto IL_1121;
                            }
                            return 0.84f + (float)Math.Cos(timeForVisualEffects / 90.0 * 6.2831854820251465) * 0.16f;
                        }
                        else
{
                            if (!(name == "Discipile"))
{
                                goto IL_1121;
                            }
                            laserLuminance = MathHelper.Lerp(0f, 0.4f, Utils.GetLerpValue(-1f, 1f, (float)Math.Cos(timeForVisualEffects / 105.0 * 6.2831854820251465), false));
                            laserAlphaMultiplier = 0.35f;
                            return 0.55f;
                        }
                    }
                    else
                    {
                        if (!(name == "Grox The Great"))
{
                            goto IL_1121;
                        }
                        return 0.41f + (float)Math.Cos(timeForVisualEffects / 120.0 * 6.2831854820251465) * 0.1f;
                    }
                }
                else if (num <= 4203845300U)
                {
                    if (num != 4123588084U)
                    {
                        if (num != 4203845300U)
{
                            goto IL_1121;
                        }
                        if (!(name == "teiull"))
{
                            goto IL_1121;
                        }
                        return 0.5f + (float)Math.Cos(timeForVisualEffects / 45.0 * 6.2831854820251465) * 0.3f;
                    }
                    else
                    {
                        if (!(name == "Jenosis"))
{
                            goto IL_1121;
                        }
                        return 0.66f + (float)Math.Cos(timeForVisualEffects / 180.0 * 6.2831854820251465) * 0.08f;
                    }
                }
                else if (num != 4263357569U)
                {
                    if (num != 4272415882U)
                    {
                        goto IL_1121;
                    }
                    if (!(name == "Acamaeda"))
                    {
                        goto IL_1121;
                    }
                    return 0.18f + (float)Math.Cos(timeForVisualEffects / 90.0 * 6.2831854820251465) * 0.1f;
                }
                else
                {
                    if (!(name == "Devalaous"))
                    {
                        goto IL_1121;
                    }
                    return 0.66f + (float)Math.Cos(timeForVisualEffects / 180.0 * 6.2831854820251465) * 0.1f;
                }
                IL_0D68:
                if ((int)laserIndex % 2 != 0)
                {
                    return MathHelper.Lerp(0.072f, 0.086f, laserIndex / 3f);
                }
                return MathHelper.Lerp(0.47f, 0.55f, laserIndex / 3f);
            }
            IL_1121:
            return (float)((int)laserIndex) / 6f;
        }
References Terraria.Player.active, System.Math.Cos(), Terraria.Utils.GetLerpValue(), Microsoft.Xna.Framework.Color.HotPink, int, Microsoft.Xna.Framework.Color.Lerp(), Microsoft.Xna.Framework.MathHelper.Lerp(), System.name, Terraria.Player.name, Terraria.Utils.PingPongFrom01To010(), Terraria.Main.player, Terraria.Main.rand, Terraria.Main.rgbToHsl(), Microsoft.Xna.Framework.MathHelper.SmoothStep(), Terraria.Main.timeForVisualEffects, Terraria.Utils.Turn01ToCyclic010(), System.U, Microsoft.Xna.Framework.Vector3.X, and Microsoft.Xna.Framework.Color.Yellow.
Referenced by Terraria.Main.DrawProjDirect().