Terraria Decompiled: Terraria.Projectile.StatusNPC
StatusNPC()
void Terraria.Projectile.StatusNPC (int i) inline
Definition at line 10333 of file Projectile.cs.
        {
            NPC npc = Main.npc[i];
            if ((this.melee || ProjectileID.Sets.IsAWhip[this.type]) && Main.player[this.owner].meleeEnchant > 0 && !this.noEnchantments)
            {
                byte meleeEnchant = Main.player[this.owner].meleeEnchant;
                if (meleeEnchant == 1)
                {
                    npc.AddBuff(70, 60 * Main.rand.Next(5, 10), false);
                }
                if (meleeEnchant == 2)
                {
                    npc.AddBuff(39, 60 * Main.rand.Next(3, 7), false);
                }
                if (meleeEnchant == 3)
                {
                    npc.AddBuff(24, 60 * Main.rand.Next(3, 7), false);
                }
                if (meleeEnchant == 5)
                {
                    npc.AddBuff(69, 60 * Main.rand.Next(10, 20), false);
                }
                if (meleeEnchant == 6)
                {
                    npc.AddBuff(31, 60 * Main.rand.Next(1, 4), false);
                }
                if (meleeEnchant == 8)
                {
                    npc.AddBuff(20, 60 * Main.rand.Next(5, 10), false);
                }
                if (meleeEnchant == 4)
                {
                    npc.AddBuff(72, 120, false);
                }
            }
            if (this.type == 1083)
            {
                npc.AddBuff(30, 60 * Main.rand.Next(4, 7), false);
            }
            if (this.type == 1078)
            {
                npc.AddBuff(24, Main.rand.Next(300, 600), false);
            }
            if (this.type == 1026)
            {
                npc.AddBuff(20, Main.rand.Next(300, 600), false);
            }
            if (this.type == 1104)
            {
                npc.AddBuff(137, 180, false);
                float num;
                int num2;
                float num3;
                Projectile.GetWhipSettings(this, out num, out num2, out num3);
                int num4 = (int)(num / 3f) * 2;
                int num5 = 1;
                if (this.ai[0] >= (float)(num4 - num5) && this.ai[0] <= (float)(num4 + num5))
                {
                    this.WhipPointsForCollision.Clear();
                    Projectile.FillWhipControlPoints(this, this.WhipPointsForCollision, null, true);
                    if (Utils.CenteredRectangle(this.WhipPointsForCollision[this.WhipPointsForCollision.Count - 1], new Vector2(50f, 50f)).Intersects(npc.Hitbox))
                    {
                        npc.AddBuff(24, 60 * Main.rand.Next(3, 6), false);
                    }
                }
            }
            if (this.type == 182)
            {
                npc.AddBuff(375, 60 * Main.rand.Next(8, 13), false);
            }
            if (this.type == 190)
            {
                npc.AddBuff(375, 60 * Main.rand.Next(4, 7), false);
            }
            if (this.type == 301)
            {
                npc.AddBuff(36, 60 * Main.rand.Next(10, 21), false);
            }
            if (this.type == 383 && Main.rand.Next(3) == 0)
            {
                npc.AddBuff(31, 60 * (int)((double)Main.rand.Next(10, 21) * 0.1), false);
            }
            if (this.type == 262 && Main.rand.Next(3) == 0)
            {
                npc.AddBuff(31, 60 * (int)((double)Main.rand.Next(10, 21) * 0.1), false);
            }
            if (this.type == 23)
            {
                npc.AddBuff(30, 60 * Main.rand.Next(8, 13), false);
            }
            if (this.type == 320)
            {
                npc.AddBuff(30, 60 * Main.rand.Next(3, 6), false);
            }
            if (this.type == 195)
            {
                npc.AddBuff(70, 60 * Main.rand.Next(5, 11), false);
            }
            if (this.type == 119)
            {
                npc.AddBuff(324, 240, false);
            }
            if (this.type == 309)
            {
                npc.AddBuff(324, 300, false);
            }
            if (this.type == 359)
            {
                npc.AddBuff(324, 420, false);
            }
            if (this.type == 1097)
            {
                npc.AddBuff(24, Main.rand.Next(300, 600), false);
            }
            if (this.type == 669 && Main.rand.Next(20) == 0)
            {
                npc.AddBuff(31, 60 * Main.rand.Next(2, 6), false);
            }
            this.ApplyWhipDebuffs(npc);
            if (this.type == 664 && Main.rand.Next(3) == 0)
            {
                npc.AddBuff(24, 60 * Main.rand.Next(3, 6), false);
            }
            if (this.type == 666 && Main.rand.Next(2) == 0)
            {
                npc.AddBuff(323, 60 * Main.rand.Next(3, 9), false);
            }
            if (this.type == 668 && Main.rand.Next(3) != 0)
            {
                npc.AddBuff(323, 60 * Main.rand.Next(6, 9), false);
            }
            if (this.type == 567 || this.type == 568)
            {
                npc.AddBuff(20, 60 * Main.rand.Next(5, 11), false);
            }
            if (this.type == 598 && this.ai[1] == (float)i)
            {
                npc.AddBuff(169, 900, false);
            }
            if (this.type == 636 && this.ai[1] == (float)i)
            {
                npc.AddBuff(189, 300, false);
            }
            if (this.type == 971 && this.ai[1] == (float)i)
            {
                npc.AddBuff(337, 540, false);
            }
            if (this.type == 975 && this.ai[1] == (float)i)
            {
                npc.AddBuff(344, 540, false);
            }
            if (this.type == 611)
            {
                npc.AddBuff(189, 300, false);
            }
            if (this.type == 612)
            {
                npc.AddBuff(189, 300, false);
            }
            if (this.type == 978)
            {
                npc.AddBuff(24, 180, false);
            }
            if (this.type == 953)
            {
                npc.AddBuff(189, 300, false);
            }
            if (this.type == 711)
            {
                npc.AddBuff(203, 600, false);
            }
            if (this.type == 706)
            {
                npc.AddBuff(323, 480, false);
            }
            if (this.type == 614 && this.ai[1] == (float)i)
            {
                npc.AddBuff(183, 900, false);
            }
            if (this.type == 585)
            {
                npc.AddBuff(153, 60 * Main.rand.Next(5, 11), false);
            }
            if (this.type == 583)
            {
                npc.AddBuff(20, 60 * Main.rand.Next(3, 6), false);
            }
            if (this.type == 524)
            {
                npc.AddBuff(69, 60 * Main.rand.Next(3, 8), false);
            }
            if (this.type == 954 && Main.rand.Next(2) == 0)
            {
                int num6 = 24;
                if (Main.remixWorld)
                {
                    num6 = 323;
                }
                if (Main.rand.Next(3) == 0)
                {
                    npc.AddBuff(num6, Main.rand.Next(60, 240), false);
                }
                else
                {
                    npc.AddBuff(num6, Main.rand.Next(60, 120), false);
                }
            }
            if (this.type == 504 && Main.rand.Next(2) == 0)
            {
                if (Main.rand.Next(3) == 0)
                {
                    npc.AddBuff(323, Main.rand.Next(60, 240), false);
                }
                else
                {
                    npc.AddBuff(323, Main.rand.Next(60, 120), false);
                }
            }
            if (this.type == 979 && Main.rand.Next(2) == 0)
            {
                int num7 = 44;
                if (Main.remixWorld)
                {
                    num7 = 324;
                }
                if (Main.rand.Next(3) == 0)
                {
                    npc.AddBuff(num7, Main.rand.Next(60, 240), false);
                }
                else
                {
                    npc.AddBuff(num7, Main.rand.Next(60, 120), false);
                }
            }
            if ((this.type == 694 || this.type == 695 || this.type == 696) && Main.player[this.owner].setHuntressT2)
            {
                npc.AddBuff(204, Main.rand.Next(8, 18) * 30, false);
            }
            if (this.type == 545 && Main.rand.Next(3) == 0)
            {
                npc.AddBuff(24, Main.rand.Next(60, 240), false);
            }
            if (this.type == 553)
            {
                npc.AddBuff(323, Main.rand.Next(180, 480), false);
            }
            if (this.type == 552 && Main.rand.Next(3) != 0)
            {
                npc.AddBuff(324, Main.rand.Next(120, 320), false);
            }
            if (this.type == 495)
            {
                npc.AddBuff(153, Main.rand.Next(120, 300), false);
            }
            if (this.type == 497)
            {
                npc.AddBuff(153, Main.rand.Next(60, 180), false);
            }
            if (this.type == 496)
            {
                npc.AddBuff(153, Main.rand.Next(240, 480), false);
            }
            if (this.type == 46)
            {
                npc.AddBuff(153, Main.rand.Next(240, 300), false);
            }
            if (this.type == 476)
            {
                npc.AddBuff(151, 30, false);
            }
            if (this.type == 523)
            {
                npc.AddBuff(20, 60 * Main.rand.Next(10, 30), false);
            }
            if (this.type == 478 || this.type == 480)
            {
                npc.AddBuff(39, 60 * Main.rand.Next(3, 7), false);
            }
            if (this.type == 479)
            {
                npc.AddBuff(69, 60 * Main.rand.Next(7, 15), false);
            }
            if (this.type == 379)
            {
                npc.AddBuff(70, 60 * Main.rand.Next(2, 5), false);
            }
            if (this.type >= 390 && this.type <= 392)
            {
                npc.AddBuff(70, 60 * Main.rand.Next(2, 5), false);
            }
            if (this.type == 374)
            {
                npc.AddBuff(20, 60 * Main.rand.Next(4, 7), false);
            }
            if (this.type == 376)
            {
                npc.AddBuff(24, 60 * Main.rand.Next(3, 7), false);
            }
            if (this.type == 399 || (this.type >= 400 && this.type <= 402))
            {
                npc.AddBuff(24, 60 * Main.rand.Next(3, 7), false);
            }
            if (this.type >= 1107 && this.type <= 1109)
            {
                npc.AddBuff(323, 60 * Main.rand.Next(3, 7), false);
            }
            if (this.type == 295 || this.type == 296)
            {
                npc.AddBuff(323, 60 * Main.rand.Next(8, 16), false);
            }
            if ((this.melee || this.ranged) && !this.npcProj && Main.player[this.owner].frostBurn && !this.noEnchantments)
            {
                npc.AddBuff(324, 60 * Main.rand.Next(5, 15), false);
            }
            if (this.melee && Main.player[this.owner].magmaStone && !this.noEnchantments)
            {
                if (Main.rand.Next(7) == 0)
                {
                    npc.AddBuff(323, 360, false);
                }
                else if (Main.rand.Next(3) == 0)
                {
                    npc.AddBuff(323, 120, false);
                }
                else
                {
                    npc.AddBuff(323, 60, false);
                }
            }
            if (this.type == 287)
            {
                npc.AddBuff(72, 120, false);
            }
            if (this.type == 285)
            {
                if (Main.rand.Next(3) == 0)
                {
                    npc.AddBuff(31, 180, false);
                }
                else
                {
                    npc.AddBuff(31, 60, false);
                }
            }
            if (this.type == 2 && Main.rand.Next(3) == 0)
            {
                npc.AddBuff(24, 180, false);
            }
            if (this.type == 172)
            {
                if (Main.rand.Next(3) == 0)
                {
                    npc.AddBuff(44, 180, false);
                }
            }
            else if (this.type == 15)
            {
                int num8 = 24;
                if (Main.remixWorld)
                {
                    num8 = 323;
                }
                if (Main.rand.Next(2) == 0)
                {
                    npc.AddBuff(num8, 300, false);
                }
            }
            else if (this.type == 253)
            {
                npc.AddBuff(324, 480, false);
            }
            else if (this.type == 19)
            {
                if (Main.rand.Next(2) == 0)
                {
                    npc.AddBuff(24, 360, false);
                }
            }
            else if (this.type == 113)
            {
                if (Main.rand.Next(2) == 0)
                {
                    npc.AddBuff(44, 180, false);
                }
            }
            else if (this.type == 33)
            {
                if (Main.rand.Next(2) == 0)
                {
                    npc.AddBuff(20, 420, false);
                }
            }
            else if (this.type == 976)
            {
                if (Main.rand.Next(4) == 0)
                {
                    npc.AddBuff(20, 420, false);
                }
            }
            else if (this.type == 34)
            {
                if (Main.rand.Next(2) == 0)
                {
                    npc.AddBuff(24, Main.rand.Next(240, 480), false);
                }
            }
            else if (this.type == 948)
            {
                if (Main.rand.Next(6) == 0)
                {
                    npc.AddBuff(24, 60 * Main.rand.Next(2, 4), false);
                }
            }
            else if (this.type == 35)
            {
                if (Main.rand.Next(2) == 0)
                {
                    npc.AddBuff(24, 300, false);
                }
            }
            else if (this.type == 54)
            {
                if (Main.rand.Next(2) == 0)
                {
                    npc.AddBuff(20, 600, false);
                }
            }
            else if (this.type == 267)
            {
                if (Main.rand.Next(3) == 0)
                {
                    npc.AddBuff(20, 3600, false);
                }
                else
                {
                    npc.AddBuff(20, 1800, false);
                }
            }
            else if (this.type == 63)
            {
                if (Main.rand.Next(5) != 0)
                {
                    npc.AddBuff(31, 60 * Main.rand.Next(2, 5), false);
                }
            }
            else if (this.type == 85)
            {
                int num9 = ((this.ai[0] == 1f) ? 324 : 323);
                npc.AddBuff(num9, 1200, false);
            }
            else if (this.type == 1106)
            {
                npc.AddBuff(24, 300, false);
            }
            else if (this.type == 188)
            {
                npc.AddBuff(323, 1200, false);
            }
            else if (this.type == 95 || this.type == 103 || this.type == 104 || this.type == 482)
            {
                npc.AddBuff(39, 420, false);
            }
            else if (this.type == 278 || this.type == 279 || this.type == 280)
            {
                npc.AddBuff(69, 600, false);
            }
            else if (this.type == 282 || this.type == 283)
            {
                npc.AddBuff(70, 600, false);
            }
            if (this.type == 163 || this.type == 310 || this.type == 1008 || this.type == 1010 || this.type == 1011)
            {
                if (Main.rand.Next(3) == 0)
                {
                    npc.AddBuff(24, 600, false);
                }
                else
                {
                    npc.AddBuff(24, 300, false);
                }
            }
            if (this.type == 1053)
            {
                npc.AddBuff(24, 300, false);
            }
            if (this.type == 1009)
            {
                npc.AddBuff(39, 600, false);
                return;
            }
            if (this.type == 98)
            {
                npc.AddBuff(20, 600, false);
                return;
            }
            if (this.type == 184)
            {
                npc.AddBuff(20, 900, false);
                return;
            }
            if (this.type == 980)
            {
                npc.AddBuff(70, 300, false);
                return;
            }
            if (this.type == 265)
            {
                npc.AddBuff(20, 1800, false);
                return;
            }
            if (this.type == 355)
            {
                npc.AddBuff(70, 1800, false);
                return;
            }
            if (this.type == 1103)
            {
                npc.AddBuff(137, 180, false);
            }
        }
References Terraria.NPC.AddBuff(), Terraria.Projectile.ai, Terraria.Projectile.ApplyWhipDebuffs(), Terraria.Utils.CenteredRectangle(), System.Collections.Generic.List< T >.Clear(), Terraria.Projectile.FillWhipControlPoints(), Terraria.Player.frostBurn, Terraria.Projectile.GetWhipSettings(), Terraria.Entity.Hitbox, int, Microsoft.Xna.Framework.Intersects, Terraria.ID.ProjectileID.Sets.IsAWhip, Terraria.Player.magmaStone, Terraria.Projectile.melee, Terraria.Player.meleeEnchant, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.npc, Terraria.Projectile.npcProj, Terraria.Projectile.owner, Terraria.Main.player, Terraria.Main.rand, Terraria.Projectile.ranged, Terraria.Main.remixWorld, Terraria.Player.setHuntressT2, Terraria.Projectile.type, and Terraria.Projectile.WhipPointsForCollision.
Referenced by Terraria.Player.BloodButcherer_TryButchering(), Terraria.Projectile.Damage_PVE_Inner(), and Terraria.Player.TentacleSpike_TrySpiking().