Terraria Decompiled: Terraria.Projectile.AI_016_Bombs
AI_016_Bombs()
void Terraria.Projectile.AI_016_Bombs () inline private
Definition at line 47340 of file Projectile.cs.
        {
            if (this.owner == Main.myPlayer)
            {
                if (this.wet && (this.type == 799 || this.type == 800 || this.type == 801 || this.type == 810 || this.type == 906 || this.type == 784 || this.type == 785 || this.type == 786 || this.type == 805 || this.type == 903 || this.type == 787 || this.type == 788 || this.type == 789 || this.type == 806 || this.type == 904 || this.type == 790 || this.type == 791 || this.type == 792 || this.type == 807 || this.type == 905 || (this.type == 1077 && this.localAI[0] == 1f)))
                {
                    this.timeLeft = 1;
                }
                if (this.type == 1077)
                {
                    this.localAI[0] = (float)(this.wet ? 0 : 1);
                }
            }
            if (SoundEngine.GetActiveSound(SlotId.FromFloat(this.localAI[2])) == null && this.timeLeft > 1 && ProjectileID.Sets.IsABombWithFuse[this.type])
            {
                this.localAI[2] = SoundEngine.PlayTrackedLoopedSound(SoundID.BombFuse, base.Center, new ActiveSound.LoopedPlayCondition(new ProjectileAudioTracker(this).IsActiveAndInGame), default(SoundPlayOverrides)).ToFloat();
                SoundEngine.GetActiveSound(SlotId.FromFloat(this.localAI[2]));
            }
            if (this.type == 108 || this.type == 164 || this.type == 1002)
            {
                this.ai[0] += 1f;
                if (this.ai[0] > 3f)
                {
                    this.Kill();
                }
            }
            if (this.type == 102)
            {
                int num = (int)(base.Center.X / 16f);
                int num2 = (int)(base.Center.Y / 16f);
                if (WorldGen.InWorld(num, num2, 0))
                {
                    Tile tile = Main.tile[num, num2];
                    if (tile != null && tile.active() && (TileID.Sets.Platforms[(int)tile.type] || tile.type == 380))
                    {
                        this.Kill();
                        return;
                    }
                }
            }
            if (this.type == 75)
            {
                if (this.localAI[0] == 0f)
                {
                    this.localAI[0] = 1f;
                    SoundEngine.PlaySound(66, (int)this.position.X, (int)this.position.Y, 1, 1f, 0f);
                }
                if (!Main.tenthAnniversaryWorld)
                {
                    for (int i = 0; i < 255; i++)
                    {
                        if (Main.player[i].active && !Main.player[i].dead && !Main.player[i].ghost && (base.Center - Main.player[i].Center).Length() < 40f)
{
                            this.Kill();
                            return;
                        }
                    }
                }
            }
            bool flag = false;
            if (this.type == 37 || this.type == 397 || this.type == 470 || this.type == 519 || this.type == 773 || this.type == 911 || this.type == 1087)
            {
                try
                {
                    int num3 = (int)(this.position.X / 16f) - 1;
                    int num4 = (int)((this.position.X + (float)this.width) / 16f) + 2;
                    int num5 = (int)(this.position.Y / 16f) - 1;
                    int num6 = (int)((this.position.Y + (float)this.height) / 16f) + 2;
                    if (num3 < 0)
                    {
                        num3 = 0;
                    }
                    if (num4 > Main.maxTilesX)
                    {
                        num4 = Main.maxTilesX;
                    }
                    if (num5 < 0)
                    {
                        num5 = 0;
                    }
                    if (num6 > Main.maxTilesY)
                    {
                        num6 = Main.maxTilesY;
                    }
                    for (int j = num3; j < num4; j++)
                    {
                        for (int k = num5; k < num6; k++)
{
                            if (Main.tile[j, k] != null && Main.tile[j, k].nactive() && Main.tileSolid[(int)Main.tile[j, k].type] && !Main.tileSolidTop[(int)Main.tile[j, k].type])
{
                                Vector2 vector;
                                vector.X = (float)(j * 16);
                                vector.Y = (float)(k * 16);
                                if (this.position.X + (float)this.width - 4f > vector.X && this.position.X + 4f < vector.X + 16f && this.position.Y + (float)this.height - 4f > vector.Y && this.position.Y + 4f < vector.Y + 16f)
{
                                    if (this.type == 911 && this.owner == Main.myPlayer && this.localAI[0] == 0f)
{
                                        float num7 = 12f;
                                        Vector2 vector2 = vector + new Vector2(8f, 8f);
                                        if (Vector2.Distance(base.Center, vector2) < num7)
{
                                            base.Center += this.velocity.SafeNormalize(Vector2.Zero) * -4f;
                                        }
                                        this.localAI[0] = 1f;
                                        this.netUpdate = true;
                                    }
                                    this.velocity.X = 0f;
                                    this.velocity.Y = -0.2f;
                                    flag = true;
                                }
                            }
                        }
                    }
                }
                catch
                {
                }
            }
            if (flag && this.type == 911)
            {
                Point point = base.Center.ToTileCoordinates();
                if (WorldGen.SolidOrSlopedTile(Framing.GetTileSafely(point.X, point.Y)))
                {
                    Vector2 vector3 = point.ToWorldCoordinates(8f, 8f) - base.Center;
                    base.Center += vector3.SafeNormalize(Vector2.Zero) * -4f;
                }
            }
            if (flag && this.type == 773)
            {
                Player player = Main.player[this.owner];
                Vector2 vector4 = base.DirectionTo(player.Center).SafeNormalize(Vector2.UnitX * (float)player.direction);
                float num8 = this.rotation;
                float num9 = vector4.ToRotation() + 1.5707964f;
                this.rotation = this.rotation.AngleLerp(num9, 0.2f);
                this.rotation = this.rotation.AngleTowards(num9, 0.05f);
                Vector2 vector5 = (this.rotation - 1.5707964f).ToRotationVector2();
                if (Main.rand.Next(3) == 0)
                {
                    Dust dust = Dust.NewDustPerfect(base.Center + vector5 * 10f, 59, new Vector2?(vector5 * 2f + Main.rand.NextVector2Circular(0.25f, 0.25f)), 0, default(Color), 2f);
                    dust.noGravity = true;
                    if (Main.rand.Next(3) == 0)
                    {
                        dust.velocity *= 1.5f;
                        dust.noGravity = false;
                        dust.scale /= 2f;
                    }
                }
                if (Main.rand.Next(3) == 0)
                {
                    Point scarabBombDigDirectionSnap = this.GetScarabBombDigDirectionSnap8();
                    Dust.NewDustPerfect(base.Center + vector5 * -10f, 59, new Vector2?(scarabBombDigDirectionSnap.ToVector2() * 1.5f), 0, default(Color), 2f).noGravity = true;
                }
                if (Main.rand.Next(15) == 0)
                {
                    Dust dust2 = Dust.NewDustPerfect(base.Center + vector5 * 10f, 88, new Vector2?(vector5 * 3f + Main.rand.NextVector2Circular(0.25f, 0.25f)), 0, default(Color), 2f);
                    dust2.noGravity = true;
                    if (Main.rand.Next(3) == 0)
                    {
                        dust2.velocity *= 1.5f;
                    }
                }
                bool flag2 = Main.rand.Next(30) == 0;
                if (num8 != this.rotation && Main.rand.Next(40) == 0)
                {
                    flag2 = true;
                }
                if (flag2)
                {
                    float num10 = 6.2831855f * Main.rand.NextFloat();
                    for (float num11 = 0f; num11 < 1f; num11 += 0.14285715f)
                    {
                        Vector2 vector6 = (num11 * 6.2831855f + num10).ToRotationVector2();
                        vector6 *= new Vector2(1f, 0.3f);
                        vector6 = vector6.RotatedBy((double)num9, default(Vector2));
                        Dust dust3 = Dust.NewDustPerfect(base.Center + vector6 + vector5 * 8f, 59, new Vector2?(vector5 * 3f + vector6), 0, default(Color), 1f);
                        dust3.noGravity = true;
                        dust3.fadeIn = 1.6f;
                    }
                }
                int num12 = this.frameCounter + 1;
                this.frameCounter = num12;
                if (num12 >= 3)
                {
                    this.frameCounter = 0;
                    num12 = this.frame + 1;
                    this.frame = num12;
                    if (num12 >= 4)
                    {
                        this.frame = 0;
                    }
                }
            }
            if (this.type == 519)
            {
                this.localAI[1] += 1f;
                float num13 = 180f - this.localAI[1];
                if (num13 < 0f)
                {
                    num13 = 0f;
                }
                this.frameCounter++;
                if (num13 < 15f)
                {
                    this.frameCounter++;
                }
                if ((float)this.frameCounter >= (num13 / 10f + 6f) / 2f)
                {
                    this.frame++;
                    this.frameCounter = 0;
                    if (this.frame >= Main.projFrames[this.type])
                    {
                        this.frame = 0;
                    }
                }
            }
            if (this.type == 681 && this.localAI[1] == 0f)
            {
                this.localAI[1] = 1f;
            }
            int num14 = 6;
            if (this.type == 776 || this.type == 780 || this.type == 803 || this.type == 804)
            {
                num14 = 228;
            }
            else if (this.type == 784 || this.type == 805)
            {
                num14 = ((Main.rand.Next(3) == 0) ? 6 : Dust.dustWater());
            }
            else if (this.type == 787 || this.type == 806)
            {
                num14 = ((Main.rand.Next(3) == 0) ? 6 : 35);
            }
            else if (this.type == 790 || this.type == 807)
            {
                num14 = ((Main.rand.Next(3) == 0) ? 6 : 152);
            }
            if (this.type == 102)
            {
                if (this.velocity.Y > 10f)
                {
                    this.velocity.Y = 10f;
                }
                if (this.localAI[0] == 0f)
                {
                    this.localAI[0] = 1f;
                    SoundEngine.PlaySound(SoundID.Item10, this.position, 0f, 1f);
                }
                this.frameCounter++;
                if (this.frameCounter > 3)
                {
                    this.frame++;
                    this.frameCounter = 0;
                }
                if (this.frame > 1)
                {
                    this.frame = 0;
                }
                if (this.velocity.Y == 0f && this.timeLeft > 3)
                {
                    this.timeLeft = 3;
                }
            }
            if (this.type == 303 && this.timeLeft <= 3 && this.hostile)
            {
                this.position.X = this.position.X + (float)(this.width / 2);
                this.position.Y = this.position.Y + (float)(this.height / 2);
                this.width = 128;
                this.height = 128;
                this.position.X = this.position.X - (float)(this.width / 2);
                this.position.Y = this.position.Y - (float)(this.height / 2);
            }
            if (this.owner == Main.myPlayer && this.type == 1088 && (this.timeLeft <= 3 || this.velocity.Length() <= 0.01f))
            {
                this.Kill();
            }
            else if (this.owner == Main.myPlayer && this.timeLeft <= 3)
            {
                this.PrepareBombToBlow();
            }
            else
            {
                if (Main.getGoodWorld && Main.noTrapsWorld && !Main.tenthAnniversaryWorld)
                {
                    this.timeLeft--;
                }
                if (this.type != 30 && this.type != 75 && this.type != 517 && this.type != 681 && this.type != 588 && this.type != 397 && this.type != 108 && this.type != 1002 && this.type != 133 && this.type != 134 && this.type != 135 && this.type != 136 && this.type != 137 && this.type != 138 && this.type != 139 && this.type != 140 && this.type != 141 && this.type != 142 && this.type != 143 && this.type != 144 && this.type != 164 && this.type != 303 && this.type != 338 && this.type != 339 && this.type != 340 && this.type != 341 && (this.type < 776 || this.type > 801) && (this.type < 803 || this.type > 810) && this.type != 862 && this.type != 863 && this.type != 930 && this.type != 1088)
                {
                    this.damage = 0;
                }
                if (this.type == 1086 || this.type == 1087)
                {
                    short num15 = 307;
                    Vector2 vector7 = base.Center + new Vector2(0f, (float)(-(float)this.height / 2)).RotatedBy((double)this.rotation, default(Vector2)) * 1.1f;
                    Vector2 vector8 = (vector7 - base.Center).SafeNormalize(Vector2.Zero) * 5f;
                    Dust dust4 = Main.dust[Dust.NewDust(base.Center, 6, 6, (int)num15, this.velocity.X, this.velocity.Y, 100, default(Color), 1.6f)];
                    dust4.position = vector7;
                    dust4.noGravity = true;
                    dust4.velocity = this.velocity + vector8;
                }
                else if (this.type == 1088)
                {
                    if (this.frameCounter == 0)
                    {
                        this.frameCounter = 1;
                        this.frame = Main.rand.Next(2);
                    }
                }
                else if (this.type == 338 || this.type == 339 || this.type == 340 || this.type == 341 || this.type == 803 || this.type == 804 || this.type == 808 || this.type == 809 || this.type == 810 || this.type == 805 || this.type == 806 || this.type == 807 || this.type == 930)
                {
                    this.localAI[1] += 1f;
                    if (this.localAI[1] > 6f)
                    {
                        this.alpha = 0;
                    }
                    else
                    {
                        this.alpha = (int)(255f - 42f * this.localAI[1]) + 100;
                        if (this.alpha > 255)
{
                            this.alpha = 255;
                        }
                    }
                    for (int l = 0; l < 2; l++)
                    {
                        float num16 = 0f;
                        float num17 = 0f;
                        if (l == 1)
{
                            num16 = this.velocity.X * 0.5f;
                            num17 = this.velocity.Y * 0.5f;
                        }
                        if (this.localAI[1] > 9f)
{
                            if (Main.rand.Next(2) == 0)
{
                                int num18 = Dust.NewDust(new Vector2(this.position.X + 3f + num16, this.position.Y + 3f + num17) - this.velocity * 0.5f, this.width - 8, this.height - 8, num14, 0f, 0f, 100, default(Color), 1f);
                                Main.dust[num18].scale *= 1.4f + (float)Main.rand.Next(10) * 0.1f;
                                Main.dust[num18].velocity *= 0.2f;
                                Main.dust[num18].noGravity = true;
                                if (Main.dust[num18].type == 152)
{
                                    Main.dust[num18].scale *= 0.5f;
                                    Main.dust[num18].velocity += this.velocity * 0.1f;
                                }
                                else if (Main.dust[num18].type == 35)
{
                                    Main.dust[num18].scale *= 0.5f;
                                    Main.dust[num18].velocity += this.velocity * 0.1f;
                                }
                                else if (Main.dust[num18].type == Dust.dustWater())
{
                                    Main.dust[num18].scale *= 0.65f;
                                    Main.dust[num18].velocity += this.velocity * 0.1f;
                                }
                                if (this.type == 808 || this.type == 809)
{
                                    Dust dust5 = Main.dust[num18];
                                    if (dust5.dustIndex != 6000)
{
                                        dust5 = Dust.NewDustPerfect(dust5.position, dust5.type, new Vector2?(dust5.velocity), dust5.alpha, dust5.color, dust5.scale + 0.5f);
                                        dust5.velocity = Main.rand.NextVector2Circular(3f, 3f);
                                        dust5.noGravity = true;
                                    }
                                    if (dust5.dustIndex != 6000)
{
                                        dust5 = Dust.NewDustPerfect(dust5.position, dust5.type, new Vector2?(dust5.velocity), dust5.alpha, dust5.color, dust5.scale + 0.5f);
                                        dust5.velocity = (6.2831855f * ((float)this.timeLeft / 20f)).ToRotationVector2() * 3f;
                                        dust5.noGravity = true;
                                    }
                                }
                            }
                            if (Main.rand.Next(2) == 0)
{
                                int num19 = Dust.NewDust(new Vector2(this.position.X + 3f + num16, this.position.Y + 3f + num17) - this.velocity * 0.5f, this.width - 8, this.height - 8, 31, 0f, 0f, 100, default(Color), 0.5f);
                                Main.dust[num19].fadeIn = 0.5f + (float)Main.rand.Next(5) * 0.1f;
                                Main.dust[num19].velocity *= 0.05f;
                            }
                        }
                    }
                    float num20 = this.position.X;
                    float num21 = this.position.Y;
                    float num22 = 600f;
                    if (this.type == 930)
                    {
                        num22 = 650f;
                    }
                    bool flag3 = false;
                    this.ai[0] += 1f;
                    if (this.ai[0] > 30f)
                    {
                        this.ai[0] = 30f;
                        for (int m = 0; m < Main.maxNPCs; m++)
{
                            if (Main.npc[m].CanBeChasedBy(this, false))
{
                                float num23 = Main.npc[m].position.X + (float)(Main.npc[m].width / 2);
                                float num24 = Main.npc[m].position.Y + (float)(Main.npc[m].height / 2);
                                float num25 = Math.Abs(this.position.X + (float)(this.width / 2) - num23) + Math.Abs(this.position.Y + (float)(this.height / 2) - num24);
                                if (num25 < num22 && Collision.CanHit(this.position, this.width, this.height, Main.npc[m].position, Main.npc[m].width, Main.npc[m].height))
{
                                    num22 = num25;
                                    num20 = num23;
                                    num21 = num24;
                                    flag3 = true;
                                }
                            }
                        }
                    }
                    if (!flag3)
                    {
                        num20 = this.position.X + (float)(this.width / 2) + this.velocity.X * 100f;
                        num21 = this.position.Y + (float)(this.height / 2) + this.velocity.Y * 100f;
                    }
                    float num26 = 16f;
                    if (this.type == 930)
                    {
                        num26 = 12f;
                    }
                    Vector2 vector9 = (new Vector2(num20, num21) - base.Center).SafeNormalize(-Vector2.UnitY) * num26;
                    this.velocity = Vector2.Lerp(this.velocity, vector9, 0.083333336f);
                }
                else if (this.type == 134 || this.type == 137 || this.type == 140 || this.type == 143 || this.type == 303 || this.type == 776 || this.type == 780 || this.type == 793 || this.type == 796 || this.type == 799 || this.type == 784 || this.type == 787 || this.type == 790)
                {
                    if (Math.Abs(this.velocity.X) >= 8f || Math.Abs(this.velocity.Y) >= 8f)
                    {
                        for (int n = 0; n < 2; n++)
{
                            float num27 = 0f;
                            float num28 = 0f;
                            if (n == 1)
{
                                num27 = this.velocity.X * 0.5f;
                                num28 = this.velocity.Y * 0.5f;
                            }
                            int num29 = Dust.NewDust(new Vector2(this.position.X + 3f + num27, this.position.Y + 3f + num28) - this.velocity * 0.5f, this.width - 8, this.height - 8, num14, 0f, 0f, 100, default(Color), 1f);
                            Main.dust[num29].scale *= 2f + (float)Main.rand.Next(10) * 0.1f;
                            Main.dust[num29].velocity *= 0.2f;
                            Main.dust[num29].noGravity = true;
                            if (Main.dust[num29].type == 152)
{
                                Main.dust[num29].scale *= 0.5f;
                                Main.dust[num29].velocity += this.velocity * 0.1f;
                            }
                            else if (Main.dust[num29].type == 35)
{
                                Main.dust[num29].scale *= 0.5f;
                                Main.dust[num29].velocity += this.velocity * 0.1f;
                            }
                            else if (Main.dust[num29].type == Dust.dustWater())
{
                                Main.dust[num29].scale *= 0.65f;
                                Main.dust[num29].velocity += this.velocity * 0.1f;
                            }
                            if (this.type == 793 || this.type == 796)
{
                                Dust dust6 = Main.dust[num29];
                                if (dust6.dustIndex != 6000)
{
                                    dust6 = Dust.NewDustPerfect(dust6.position, dust6.type, new Vector2?(dust6.velocity), dust6.alpha, dust6.color, dust6.scale);
                                    dust6.velocity = Main.rand.NextVector2Circular(3f, 3f);
                                    dust6.noGravity = true;
                                }
                                if (dust6.dustIndex != 6000)
{
                                    dust6 = Dust.NewDustPerfect(dust6.position, dust6.type, new Vector2?(dust6.velocity), dust6.alpha, dust6.color, dust6.scale);
                                    dust6.velocity = (6.2831855f * ((float)this.timeLeft / 20f)).ToRotationVector2() * 3f;
                                    dust6.noGravity = true;
                                }
                            }
                            num29 = Dust.NewDust(new Vector2(this.position.X + 3f + num27, this.position.Y + 3f + num28) - this.velocity * 0.5f, this.width - 8, this.height - 8, 31, 0f, 0f, 100, default(Color), 0.5f);
                            Main.dust[num29].fadeIn = 1f + (float)Main.rand.Next(5) * 0.1f;
                            Main.dust[num29].velocity *= 0.05f;
                        }
                    }
                    if (Math.Abs(this.velocity.X) < 15f && Math.Abs(this.velocity.Y) < 15f)
                    {
                        this.velocity *= 1.1f;
                    }
                }
                else if (this.type == 133 || this.type == 136 || this.type == 139 || this.type == 142 || this.type == 777 || this.type == 781 || this.type == 794 || this.type == 797 || this.type == 800 || this.type == 785 || this.type == 788 || this.type == 791)
                {
                    int num30 = Dust.NewDust(new Vector2(this.position.X, this.position.Y), this.width, this.height, 31, 0f, 0f, 100, default(Color), 1f);
                    Main.dust[num30].scale *= 1f + (float)Main.rand.Next(10) * 0.1f;
                    Main.dust[num30].velocity *= 0.2f;
                    Main.dust[num30].noGravity = true;
                }
                else if (this.type == 135 || this.type == 138 || this.type == 141 || this.type == 144 || this.type == 778 || this.type == 782 || this.type == 795 || this.type == 798 || this.type == 801 || this.type == 786 || this.type == 789 || this.type == 792)
                {
                    if ((double)this.velocity.X > -0.2 && (double)this.velocity.X < 0.2 && (double)this.velocity.Y > -0.2 && (double)this.velocity.Y < 0.2)
                    {
                        this.alpha += 2;
                        if (this.alpha > 200)
{
                            this.alpha = 200;
                        }
                    }
                    else
                    {
                        this.alpha = 0;
                        int num31 = Dust.NewDust(new Vector2(this.position.X + 3f, this.position.Y + 3f) - this.velocity * 0.5f, this.width - 8, this.height - 8, 31, 0f, 0f, 100, default(Color), 1f);
                        Main.dust[num31].scale *= 1.6f + (float)Main.rand.Next(5) * 0.1f;
                        Main.dust[num31].velocity *= 0.05f;
                        Main.dust[num31].noGravity = true;
                    }
                }
                else if (this.type == 779 || this.type == 783 || this.type == 862 || this.type == 863)
                {
                    if (Main.rand.Next(25) == 0)
                    {
                        Dust dust7 = Dust.NewDustDirect(this.position, this.width, this.height, 228, -this.velocity.X / 10f, -this.velocity.Y / 10f, 100, default(Color), 1f);
                        dust7.noGravity = true;
                        dust7.velocity *= 0f;
                        dust7.scale = 1.3f;
                    }
                    if (Main.rand.Next(5) == 0)
                    {
                        Dust dust8 = Dust.NewDustDirect(this.position, this.width, this.height, 31, -this.velocity.X / 10f, -this.velocity.Y / 10f, 100, default(Color), 1f);
                        dust8.noGravity = true;
                        dust8.velocity *= 0f;
                        dust8.scale = 1.3f;
                    }
                    if (this.frameCounter == 0)
                    {
                        this.frameCounter = 1;
                        this.frame = Main.rand.Next(4);
                    }
                }
                else if (this.type != 30 && this.type != 517 && this.type != 681 && this.type != 397 && this.type != 519 && this.type != 588 && this.type != 779 && this.type != 783 && this.type != 862 && this.type != 863 && Main.rand.Next(2) == 0)
                {
                    int num32 = Dust.NewDust(new Vector2(this.position.X, this.position.Y), this.width, this.height, 31, 0f, 0f, 100, default(Color), 1f);
                    Main.dust[num32].scale = 0.1f + (float)Main.rand.Next(5) * 0.1f;
                    Main.dust[num32].fadeIn = 1.5f + (float)Main.rand.Next(5) * 0.1f;
                    Main.dust[num32].noGravity = true;
                    Main.dust[num32].position = base.Center + new Vector2(0f, (float)(-(float)this.height / 2)).RotatedBy((double)this.rotation, default(Vector2)) * 1.1f;
                    int num33 = 6;
                    if (this.type == 773)
                    {
                        num33 = 59;
                    }
                    if (this.type == 903)
                    {
                        num33 = Dust.dustWater();
                    }
                    if (this.type == 904)
                    {
                        num33 = 35;
                    }
                    if (this.type == 905)
                    {
                        num33 = 152;
                    }
                    if (this.type == 1077)
                    {
                        num33 = 135;
                    }
                    if (this.type == 910 || this.type == 911)
                    {
                        num33 = 0;
                    }
                    Dust dust9 = Dust.NewDustDirect(this.position, this.width, this.height, num33, 0f, 0f, 100, default(Color), 1f);
                    dust9.scale = 1f + (float)Main.rand.Next(5) * 0.1f;
                    dust9.noGravity = true;
                    dust9.position = base.Center + new Vector2(0f, (float)(-(float)this.height / 2 - 6)).RotatedBy((double)this.rotation, default(Vector2)) * 1.1f;
                }
                else if (this.type == 681)
                {
                    Dust dust10 = Dust.NewDustDirect(this.position, this.width, this.height, 6, 0f, 0f, 100, default(Color), 1f);
                    dust10.scale = 1f + (float)Main.rand.Next(5) * 0.1f;
                    dust10.noGravity = true;
                    dust10.position = base.Center + new Vector2((float)(6 * Math.Sign(this.velocity.X)), (float)(-(float)this.height / 2 - 6)).RotatedBy((double)this.rotation, default(Vector2)) * 1.1f;
                }
            }
            this.ai[0] += 1f;
            if (this.type == 338 || this.type == 339 || this.type == 340 || this.type == 341 || this.type == 803 || this.type == 804 || this.type == 808 || this.type == 809 || this.type == 810 || this.type == 805 || this.type == 806 || this.type == 807 || this.type == 930)
            {
                if (this.velocity.X < 0f)
                {
                    this.spriteDirection = -1;
                    this.rotation = (float)Math.Atan2((double)(-(double)this.velocity.Y), (double)(-(double)this.velocity.X)) - 1.57f;
                }
                else
                {
                    this.spriteDirection = 1;
                    this.rotation = (float)Math.Atan2((double)this.velocity.Y, (double)this.velocity.X) + 1.57f;
                }
            }
            else if (this.type == 134 || this.type == 137 || this.type == 140 || this.type == 143 || this.type == 303 || this.type == 776 || this.type == 780 || this.type == 793 || this.type == 796 || this.type == 799 || this.type == 784 || this.type == 787 || this.type == 790)
            {
                if (this.velocity != Vector2.Zero)
                {
                    this.rotation = (float)Math.Atan2((double)this.velocity.Y, (double)this.velocity.X) + 1.57f;
                }
            }
            else if (this.type == 135 || this.type == 138 || this.type == 141 || this.type == 144 || this.type == 778 || this.type == 782 || this.type == 795 || this.type == 798 || this.type == 801 || this.type == 786 || this.type == 789 || this.type == 792)
            {
                this.velocity.Y = this.velocity.Y + 0.2f;
                this.velocity *= 0.97f;
                if ((double)this.velocity.X > -0.1 && (double)this.velocity.X < 0.1)
                {
                    this.velocity.X = 0f;
                }
                if ((double)this.velocity.Y > -0.1 && (double)this.velocity.Y < 0.1)
                {
                    this.velocity.Y = 0f;
                }
            }
            else if (this.type == 133 || this.type == 136 || this.type == 139 || this.type == 142 || this.type == 777 || this.type == 781 || this.type == 794 || this.type == 797 || this.type == 800 || this.type == 785 || this.type == 788 || this.type == 791)
            {
                if (this.ai[0] > 15f)
                {
                    if (this.velocity.Y == 0f)
                    {
                        this.velocity.X = this.velocity.X * 0.95f;
                    }
                    this.velocity.Y = this.velocity.Y + 0.2f;
                }
            }
            else if (((this.type == 30 || this.type == 397 || this.type == 517 || this.type == 681 || this.type == 588 || this.type == 779 || this.type == 783 || this.type == 862 || this.type == 863 || this.type == 1088) && this.ai[0] > 10f) || (this.type != 30 && this.type != 397 && this.type != 517 && this.type != 588 && this.type != 779 && this.type != 783 && this.type != 862 && this.type != 863 && this.type != 1088 && this.ai[0] > 5f))
            {
                this.ai[0] = 10f;
                if (this.velocity.Y == 0f && this.velocity.X != 0f)
                {
                    this.velocity.X = this.velocity.X * 0.97f;
                    if (this.type == 29 || this.type == 470 || this.type == 637)
                    {
                        this.velocity.X = this.velocity.X * 0.99f;
                    }
                    if (this.velocity.X > -0.01f && this.velocity.X < 0.01f)
                    {
                        this.velocity.X = 0f;
                        this.netUpdate = true;
                    }
                }
                this.velocity.Y = this.velocity.Y + 0.2f;
                if (this.type == 911)
                {
                    this.velocity.X = MathHelper.Clamp(this.velocity.X, -8f, 8f);
                    this.velocity.Y = MathHelper.Clamp(this.velocity.Y, -8f, 8f);
                }
            }
            if (this.type == 519)
            {
                this.rotation += this.velocity.X * 0.06f;
                return;
            }
            if (this.type != 134 && this.type != 137 && this.type != 140 && this.type != 143 && this.type != 303 && (this.type < 338 || this.type > 341) && this.type != 776 && this.type != 780 && this.type != 793 && this.type != 796 && this.type != 799 && this.type != 784 && this.type != 787 && this.type != 790 && this.type != 803 && this.type != 804 && this.type != 808 && this.type != 809 && this.type != 810 && this.type != 805 && this.type != 806 && this.type != 807 && this.type != 930)
            {
                this.rotation += this.velocity.X * 0.1f;
            }
        }
References System.Math.Abs(), Terraria.Player.active, Terraria.Tile.active(), Terraria.Dust.alpha, System.Math.Atan2(), Terraria.ID.SoundID.BombFuse, Terraria.NPC.CanBeChasedBy(), Terraria.Collision.CanHit(), Terraria.Entity.Center, Microsoft.Xna.Framework.MathHelper.Clamp(), Terraria.Dust.color, Terraria.Player.dead, Terraria.Entity.direction, Microsoft.Xna.Framework.Vector2.Distance(), Terraria.Main.dust, Terraria.Dust.dustIndex, Terraria.Dust.dustWater(), Terraria.Dust.fadeIn, ReLogic.Utilities.SlotId.FromFloat(), Terraria.Audio.SoundEngine.GetActiveSound(), Terraria.Main.getGoodWorld, Terraria.Framing.GetTileSafely(), Terraria.Player.ghost, Terraria.Entity.height, int, Terraria.WorldGen.InWorld(), Terraria.ID.ProjectileID.Sets.IsABombWithFuse, Terraria.ID.SoundID.Item10, Microsoft.Xna.Framework.Vector2.Lerp(), Terraria.Audio.ActiveSound.LoopedPlayCondition(), Terraria.Main.maxNPCs, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.myPlayer, Terraria.Tile.nactive(), Terraria.Dust.NewDust(), Terraria.Dust.NewDustDirect(), Terraria.Dust.NewDustPerfect(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Terraria.Main.noTrapsWorld, Terraria.Main.npc, Terraria.ID.TileID.Sets.Platforms, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Audio.SoundEngine.PlayTrackedLoopedSound(), Terraria.Dust.position, Terraria.Entity.position, Terraria.Main.projFrames, Terraria.Main.rand, Terraria.Dust.scale, System.Math.Sign(), Terraria.WorldGen.SolidOrSlopedTile(), Terraria.Main.tenthAnniversaryWorld, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Dust.type, Terraria.Tile.type, Microsoft.Xna.Framework.Vector2.UnitX, Microsoft.Xna.Framework.Vector2.UnitY, Terraria.Dust.velocity, Terraria.Entity.width, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Point.Y, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.