Terraria Decompiled: Terraria.Projectile.AI_015_Flails_Old
AI_015_Flails_Old()
void Terraria.Projectile.AI_015_Flails_Old () inline private
Definition at line 44369 of file Projectile.cs.
        {
            this.AI_015_Flails_Dust(false);
            bool flag = Main.player[this.owner].dead;
            if (!flag)
            {
                flag = (Main.player[this.owner].Center - base.Center).Length() > 2000f;
            }
            if (flag)
            {
                this.Kill();
                return;
            }
            Main.player[this.owner].SetDummyItemTime(10);
            if (this.position.X + (float)(this.width / 2) > Main.player[this.owner].position.X + (float)(Main.player[this.owner].width / 2))
            {
                Main.player[this.owner].ChangeDir(1);
                this.direction = 1;
            }
            else
            {
                Main.player[this.owner].ChangeDir(-1);
                this.direction = -1;
            }
            Vector2 mountedCenter = Main.player[this.owner].MountedCenter;
            Vector2 vector = new Vector2(this.position.X + (float)this.width * 0.5f, this.position.Y + (float)this.height * 0.5f);
            float num = mountedCenter.X - vector.X;
            float num2 = mountedCenter.Y - vector.Y;
            float num3 = (float)Math.Sqrt((double)(num * num + num2 * num2));
            if (this.ai[0] == 0f)
            {
                float num4 = 160f;
                if (this.type == 63)
                {
                    num4 *= 1.5f;
                }
                if (this.type == 247)
                {
                    num4 *= 1.5f;
                }
                if (this.type == 757)
                {
                    num4 *= 1.5f;
                }
                this.tileCollide = true;
                if (num3 > num4)
                {
                    this.ai[0] = 1f;
                    this.netUpdate = true;
                }
                else if (!Main.player[this.owner].channel)
                {
                    if (this.velocity.Y < 0f)
                    {
                        this.velocity.Y = this.velocity.Y * 0.9f;
                    }
                    this.velocity.Y = this.velocity.Y + 1f;
                    this.velocity.X = this.velocity.X * 0.9f;
                }
            }
            else if (this.ai[0] == 1f)
            {
                float meleeSpeed = Main.player[this.owner].meleeSpeed;
                float num5 = 14f / meleeSpeed;
                float num6 = 0.9f / meleeSpeed;
                float num7 = 300f / meleeSpeed;
                int num8 = 60;
                if (this.type == 63)
                {
                    num7 *= 1.5f;
                    num5 *= 1.5f;
                    num6 *= 1.5f;
                }
                if (this.type == 247)
                {
                    num7 *= 1.5f;
                    num5 = 15.9f;
                    num6 *= 2f;
                    num8 = 100;
                }
                if (this.type == 757)
                {
                    num7 *= 1.5f;
                    num5 = 15.9f;
                    num6 *= 2f;
                    num8 = 100;
                }
                Math.Abs(num);
                Math.Abs(num2);
                if (this.ai[1] == 1f)
                {
                    this.tileCollide = false;
                }
                if (!Main.player[this.owner].channel || num3 > num7 || !this.tileCollide)
                {
                    this.ai[1] = 1f;
                    if (this.tileCollide)
                    {
                        this.netUpdate = true;
                    }
                    this.tileCollide = false;
                    if (num3 < 20f)
                    {
                        this.Kill();
                    }
                }
                if (!this.tileCollide)
                {
                    num6 *= 2f;
                }
                if (num3 > (float)num8 || !this.tileCollide)
                {
                    num3 = num5 / num3;
                    num *= num3;
                    num2 *= num3;
                    new Vector2(this.velocity.X, this.velocity.Y);
                    float num9 = num - this.velocity.X;
                    float num10 = num2 - this.velocity.Y;
                    float num11 = (float)Math.Sqrt((double)(num9 * num9 + num10 * num10));
                    num11 = num6 / num11;
                    num9 *= num11;
                    num10 *= num11;
                    this.velocity.X = this.velocity.X * 0.98f;
                    this.velocity.Y = this.velocity.Y * 0.98f;
                    this.velocity.X = this.velocity.X + num9;
                    this.velocity.Y = this.velocity.Y + num10;
                }
                else
                {
                    if (Math.Abs(this.velocity.X) + Math.Abs(this.velocity.Y) < 6f)
                    {
                        this.velocity.X = this.velocity.X * 0.96f;
                        this.velocity.Y = this.velocity.Y + 0.2f;
                    }
                    if (Main.player[this.owner].velocity.X == 0f)
                    {
                        this.velocity.X = this.velocity.X * 0.96f;
                    }
                }
            }
            if (this.type == 247)
            {
                if (this.velocity.X < 0f)
                {
                    this.rotation -= (Math.Abs(this.velocity.X) + Math.Abs(this.velocity.Y)) * 0.01f;
                }
                else
                {
                    this.rotation += (Math.Abs(this.velocity.X) + Math.Abs(this.velocity.Y)) * 0.01f;
                }
                float num12 = this.position.X;
                float num13 = this.position.Y;
                float num14 = 600f;
                bool flag2 = false;
                if (this.owner == Main.myPlayer)
                {
                    this.localAI[1] += 1f;
                    if (this.localAI[1] > 20f)
                    {
                        this.localAI[1] = 20f;
                        for (int i = 0; i < Main.maxNPCs; i++)
{
                            if (Main.npc[i].CanBeChasedBy(this, false))
{
                                float num15 = Main.npc[i].position.X + (float)(Main.npc[i].width / 2);
                                float num16 = Main.npc[i].position.Y + (float)(Main.npc[i].height / 2);
                                float num17 = Math.Abs(this.position.X + (float)(this.width / 2) - num15) + Math.Abs(this.position.Y + (float)(this.height / 2) - num16);
                                if (num17 < num14 && Collision.CanHit(this.position, this.width, this.height, Main.npc[i].position, Main.npc[i].width, Main.npc[i].height))
{
                                    num14 = num17;
                                    num12 = num15;
                                    num13 = num16;
                                    flag2 = true;
                                }
                            }
                        }
                    }
                }
                if (flag2)
                {
                    this.localAI[1] = 0f;
                    float num18 = 14f;
                    vector = new Vector2(this.position.X + (float)this.width * 0.5f, this.position.Y + (float)this.height * 0.5f);
                    num = num12 - vector.X;
                    num2 = num13 - vector.Y;
                    num3 = (float)Math.Sqrt((double)(num * num + num2 * num2));
                    num3 = num18 / num3;
                    num *= num3;
                    num2 *= num3;
                    Projectile.NewProjectile(this.GetProjectileSource_FromThis(), vector.X, vector.Y, num, num2, 248, (int)((double)this.damage / 1.5), this.knockBack / 2f, Main.myPlayer, 0f, 0f, 0f, null);
                }
            }
            else
            {
                this.rotation = (float)Math.Atan2((double)num2, (double)num) - this.velocity.X * 0.1f;
            }
            this.AI_AdjustPlayerItemRotationToFaceProjectile(-1, 0f);
        }
References System.Math.Abs(), System.Math.Atan2(), Terraria.NPC.CanBeChasedBy(), Terraria.Collision.CanHit(), Terraria.Entity.Center, Terraria.Player.ChangeDir(), Terraria.Player.channel, Terraria.Player.dead, Terraria.Entity.height, int, Terraria.Main.maxNPCs, Terraria.Player.meleeSpeed, Terraria.Player.MountedCenter, Terraria.Main.myPlayer, Terraria.Projectile.NewProjectile(), Terraria.Main.npc, Terraria.Main.player, Terraria.Entity.position, Terraria.Player.SetDummyItemTime(), System.Math.Sqrt(), Terraria.Entity.velocity, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.