Terraria Decompiled: Terraria.Projectile.AI_067_FreakingPirates_HitIntention
AI_067_FreakingPirates_HitIntention()
void Terraria.Projectile.AI_067_FreakingPirates_HitIntention (Vector2 idealPosition) inline private
Definition at line 51555 of file Projectile.cs.
        {
            if (this.type == 1093)
            {
                Point point = idealPosition.ToTileCoordinates();
                Tile tileSafely = Framing.GetTileSafely(point);
                if (tileSafely != null)
                {
                    int num = 0;
                    if (tileSafely.active())
                    {
                        Player player = Main.player[this.owner];
                        int num2 = 41;
                        int num3;
                        int num4;
                        player.PickTile_DetermineDamage(point.X, point.Y, num2, tileSafely, out num3, out num4);
                        if (num4 > 0)
{
                            num++;
                            player.PickTile(point.X, point.Y, num2);
                        }
                    }
                    if (num > 0)
                    {
                        ParticleOrchestrator.BroadcastOrRequestParticleSpawn(ParticleOrchestraType.CattivaHit, new ParticleOrchestraSettings
{
                            PositionInWorld = idealPosition + Main.rand.NextVector2Circular(4f, 4f),
                            MovementVector = Main.rand.NextVector2CircularEdge(4f, 4f)
                        });
                        return;
                    }
                    this.ai[0] = 0f;
                    this.ai[1] = 0f;
                    this.ai[2] = 0f;
                    this.netUpdate = true;
                }
            }
        }
References Terraria.Tile.active(), Terraria.GameContent.Drawing.ParticleOrchestrator.BroadcastOrRequestParticleSpawn(), Terraria.Framing.GetTileSafely(), Terraria.Player.PickTile(), Terraria.Player.PickTile_DetermineDamage(), Terraria.Main.player, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.