Terraria Decompiled: Terraria.Projectile.AI_164_StormTigerGem
AI_164_StormTigerGem()
void Terraria.Projectile.AI_164_StormTigerGem () inline private
Definition at line 46977 of file Projectile.cs.
        {
            Player player = Main.player[this.owner];
            this.localAI[1] += 1f;
            if (this.type == 831)
            {
                if (player.dead)
                {
                    player.stormTiger = false;
                }
                if (player.stormTiger)
                {
                    this.timeLeft = 2;
                }
                int num = this.frameCounter + 1;
                this.frameCounter = num;
                if (num >= 4)
                {
                    this.frameCounter = 0;
                    num = this.frame + 1;
                    this.frame = num;
                    if (num >= 6)
                    {
                        this.frame = 0;
                    }
                }
            }
            if (this.type == 970)
            {
                if (player.ownedProjectileCounts[this.type] > 1 && this.localAI[0] == 0f)
                {
                    this.localAI[0] = 1f;
                    SoundEngine.PlaySound(SoundID.AbigailUpgrade, base.Center, 0f, 1f);
                }
                if (player.dead)
                {
                    player.abigailMinion = false;
                }
                if (player.abigailMinion)
                {
                    this.timeLeft = 2;
                }
                int num = this.frameCounter + 1;
                this.frameCounter = num;
                if (num >= 4)
                {
                    this.frameCounter = 0;
                    num = this.frame + 1;
                    this.frame = num;
                    if (num >= 6)
                    {
                        this.frame = 0;
                    }
                }
            }
            List<int> ai164_blacklistedTargets = Projectile._ai164_blacklistedTargets;
            ai164_blacklistedTargets.Clear();
            int num2;
            int num3;
            this.AI_GetMyGroupIndexAndFillBlackList(ai164_blacklistedTargets, out num2, out num3);
            Vector2 vector = Projectile.AI_164_GetHomeLocation(player, num2, num3);
            base.Center = vector;
        }
References Terraria.Projectile._ai164_blacklistedTargets, Terraria.Player.abigailMinion, Terraria.ID.SoundID.AbigailUpgrade, Terraria.Projectile.AI_164_GetHomeLocation(), System.Collections.Generic.List< T >.Clear(), Terraria.Player.dead, Terraria.Player.ownedProjectileCounts, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), and Terraria.Player.stormTiger.