Terraria Decompiled: Terraria.Projectile.AI_202_TorchGodHelper
AI_202_TorchGodHelper()
void Terraria.Projectile.AI_202_TorchGodHelper () inline private
Definition at line 40251 of file Projectile.cs.
        {
            int num = (int)this.ai[1];
            int num2 = (int)this.ai[2];
            Vector2 vector = new Point(num, num2).ToWorldCoordinates(8f, 8f);
            if (vector.Distance(base.Center) < 16f)
            {
                base.Center = vector;
                this.velocity = Vector2.Zero;
                if (this.owner == Main.myPlayer && WorldGen.InWorld(num, num2, 0) && Main.tile[num, num2].active() && Main.tile[num, num2].type == 4)
                {
                    Main.tile[num, num2].frameY = (short)(this.ai[0] * 22f);
                    NetMessage.SendTileSquare(this.owner, num, num2, 1, TileChangeType.None);
                }
                this.Kill();
            }
            if (this.localAI[0] == 0f)
            {
                this.localAI[0] = 1f;
                SoundEngine.PlaySound(SoundID.Item8, base.Center, 0f, 1f);
            }
            int num3 = TorchID.Dust[(int)this.ai[0]];
            float num4 = 4f;
            for (float num5 = 0f; num5 < num4; num5 += 1f)
            {
                int num6 = Dust.NewDust(this.position + this.velocity / num4 * num5, 4, 4, num3, 0f, 0f, 100, default(Color), 1f);
                if (Main.rand.Next(3) != 0)
                {
                    Main.dust[num6].noGravity = true;
                }
                Main.dust[num6].velocity *= 0.3f;
                Main.dust[num6].scale *= 1.1f;
                Main.dust[num6].noLightEmittance = true;
                Main.dust[num6].fullBright = true;
                if (num3 == 66)
                {
                    Main.dust[num6].color = new Color(Main.DiscoR, Main.DiscoG, Main.DiscoB);
                    Main.dust[num6].noGravity = true;
                }
            }
        }
References Terraria.Tile.active(), Terraria.Dust.color, Terraria.Main.DiscoB, Terraria.Main.DiscoG, Terraria.Main.DiscoR, Microsoft.Xna.Framework.Vector2.Distance(), Terraria.ID.TorchID.Dust, Terraria.Main.dust, Terraria.Tile.frameY, Terraria.Dust.fullBright, int, Terraria.WorldGen.InWorld(), Terraria.ID.SoundID.Item8, Terraria.Main.myPlayer, Terraria.Dust.NewDust(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Terraria.Dust.noLightEmittance, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.rand, Terraria.Dust.scale, Terraria.NetMessage.SendTileSquare(), Terraria.Main.tile, Terraria.Tile.type, Terraria.Dust.velocity, and Microsoft.Xna.Framework.Vector2.Zero.