Terraria Decompiled: Terraria.Projectile.NewProjectile
NewProjectile() [1/2]
static int Terraria.Projectile.NewProjectile (IEntitySource spawnSource, float X, float Y, float SpeedX, float SpeedY, int Type, int Damage, float KnockBack, int Owner = -1, float ai0 = 0f, float ai1 = 0f, float ai2 = 0f, NewProjectileModifier modifer = null) inline static
Definition at line 9946 of file Projectile.cs.
        {
            if (Owner == -1)
            {
                Owner = 255;
            }
            int num = 1000;
            for (int i = 0; i < 1000; i++)
            {
                if (!Main.projectile[i].active)
                {
                    num = i;
                    break;
                }
            }
            if (num == 1000)
            {
                num = Projectile.FindOldestProjectile();
            }
            Projectile projectile = Main.projectile[num];
            if (Main.NoPooling)
            {
                projectile = (Main.projectile[num] = new Projectile());
            }
            projectile.SetDefaults(Type);
            projectile.whoAmI = num;
            projectile.position.X = X - (float)projectile.width * 0.5f;
            projectile.position.Y = Y - (float)projectile.height * 0.5f;
            projectile.owner = Owner;
            projectile.velocity.X = SpeedX;
            projectile.velocity.Y = SpeedY;
            projectile.damage = Damage;
            projectile.knockBack = KnockBack;
            projectile.identity = num;
            projectile.gfxOffY = 0f;
            projectile.stepSpeed = 1f;
            projectile.wet = Collision.WetCollision(projectile.position, projectile.width, projectile.height);
            if (projectile.ignoreWater)
            {
                projectile.wet = false;
            }
            projectile.honeyWet = Collision.honey;
            projectile.shimmerWet = Collision.shimmer;
            Main.projectileIdentity[Owner, num] = num;
            projectile.ApplyStatsFromSource(spawnSource);
            projectile.FindBannerToAssociateTo(spawnSource);
            projectile.TrackMinionSpawnSource(spawnSource);
            if (projectile.aiStyle == 1)
            {
                while (projectile.velocity.X >= 16f || projectile.velocity.X <= -16f || projectile.velocity.Y >= 16f || projectile.velocity.Y < -16f)
                {
                    Projectile projectile2 = projectile;
                    projectile2.velocity.X = projectile2.velocity.X * 0.97f;
                    Projectile projectile3 = projectile;
                    projectile3.velocity.Y = projectile3.velocity.Y * 0.97f;
                }
            }
            if (Owner == Main.myPlayer)
            {
                if (Type == 206)
                {
                    projectile.ai[0] = (float)Main.rand.Next(-100, 101) * 0.0005f;
                    projectile.ai[1] = (float)Main.rand.Next(-100, 101) * 0.0005f;
                }
                else if (Type == 335)
                {
                    projectile.ai[1] = (float)Main.rand.Next(4);
                }
                else if (Type == 358)
                {
                    projectile.ai[1] = (float)Main.rand.Next(10, 31) * 0.1f;
                }
                else if (Type == 406)
                {
                    projectile.ai[1] = (float)Main.rand.Next(10, 21) * 0.1f;
                }
                else
                {
                    projectile.ai[0] = ai0;
                    projectile.ai[1] = ai1;
                    projectile.ai[2] = ai2;
                }
            }
            if (Type == 434)
            {
                projectile.ai[0] = projectile.position.X;
                projectile.ai[1] = projectile.position.Y;
            }
            if (Type > 0 && Type < (int)ProjectileID.Count)
            {
                if (ProjectileID.Sets.NeedsUUID[Type])
                {
                    projectile.projUUID = projectile.identity;
                }
                if (ProjectileID.Sets.StardustDragon[Type])
                {
                    int num2 = Main.projectile[(int)projectile.ai[0]].projUUID;
                    if (num2 >= 0)
                    {
                        projectile.ai[0] = (float)num2;
                    }
                }
            }
            if (Owner == Main.myPlayer)
            {
                if (ProjectileID.Sets.IsAGolfBall[Type] && Damage <= 0)
                {
                    int num3 = 0;
                    int num4 = 0;
                    int num5 = 99999999;
                    for (int j = 0; j < 1000; j++)
                    {
                        if (Main.projectile[j].active && ProjectileID.Sets.IsAGolfBall[Main.projectile[j].type] && Main.projectile[j].owner == Owner && Main.projectile[j].damage <= 0)
{
                            num3++;
                            if (num5 > Main.projectile[j].timeLeft)
{
                                num4 = j;
                                num5 = Main.projectile[j].timeLeft;
                            }
                        }
                    }
                    if (num3 > 10)
                    {
                        Main.projectile[num4].Kill();
                    }
                }
                if (ProjectileID.Sets.CopiesOwnerAttackCDToLocalImmunityOnSpawn[Type])
                {
                    int[] meleeNPCHitCooldown = Main.player[Owner].meleeNPCHitCooldown;
                    int[] array = projectile.localNPCImmunity;
                    for (int k = 0; k < Main.maxNPCs; k++)
                    {
                        int num6 = meleeNPCHitCooldown[k];
                        if (num6 > 0)
{
                            array[k] = num6;
                        }
                    }
                }
                if (Type == 28)
                {
                    projectile.timeLeft = 180;
                }
                if (Type == 1077)
                {
                    projectile.timeLeft = 180;
                }
                if (Type == 516)
                {
                    projectile.timeLeft = 180;
                }
                if (Type == 519)
                {
                    projectile.timeLeft = 180;
                }
                if (Type == 1086 || Type == 1087)
                {
                    projectile.timeLeft = 300;
                }
                if (Type == 29 || Type == 470 || Type == 637)
                {
                    projectile.timeLeft = 300;
                }
                if (Type == 30)
                {
                    projectile.timeLeft = 180;
                }
                if (Type == 517)
                {
                    projectile.timeLeft = 180;
                }
                if (Type == 37)
                {
                    projectile.timeLeft = 180;
                }
                if (Type == 773)
                {
                    projectile.timeLeft = 180;
                }
                if (Type == 75)
                {
                    projectile.timeLeft = 180;
                }
                if (Type == 133)
                {
                    projectile.timeLeft = 180;
                }
                if (Type == 136)
                {
                    projectile.timeLeft = 180;
                }
                if (Type == 139)
                {
                    projectile.timeLeft = 180;
                }
                if (Type == 142)
                {
                    projectile.timeLeft = 180;
                }
                if (Type == 397)
                {
                    projectile.timeLeft = 180;
                }
                if (Type == 419)
                {
                    projectile.timeLeft = 600;
                }
                if (Type == 420)
                {
                    projectile.timeLeft = 600;
                }
                if (Type == 421)
                {
                    projectile.timeLeft = 600;
                }
                if (Type == 422)
                {
                    projectile.timeLeft = 600;
                }
                if (Type == 588)
                {
                    projectile.timeLeft = 180;
                }
                if (Type == 779)
                {
                    projectile.timeLeft = 60;
                }
                if (Type == 783)
                {
                    projectile.timeLeft = 60;
                }
                if (Type == 862 || Type == 863)
                {
                    projectile.timeLeft = 60;
                }
                if (Type == 443 || Type == 1110)
                {
                    projectile.timeLeft = 300;
                }
                if (Type == 681)
                {
                    projectile.timeLeft = 600;
                }
                if (Type == 684)
                {
                    projectile.timeLeft = 60;
                }
                if (Type == 706)
                {
                    projectile.timeLeft = 120;
                }
                if (Type == 680 && Main.player[projectile.owner].setSquireT2)
                {
                    projectile.penetrate = 7;
                }
                if (Type == 777 || Type == 781 || Type == 794 || Type == 797 || Type == 800 || Type == 785 || Type == 788 || Type == 791 || Type == 903 || Type == 904 || Type == 905 || Type == 906 || Type == 910 || Type == 911)
                {
                    projectile.timeLeft = 180;
                }
            }
            if (Type == 249)
            {
                projectile.frame = Main.rand.Next(5);
            }
            if (modifer != null)
            {
                modifer(projectile);
            }
            if (Main.netMode != 0 && Owner == Main.myPlayer)
            {
                NetMessage.SendData(27, -1, -1, null, num, 0f, 0f, 0f, 0, 0, 0);
            }
            if (Owner == Main.myPlayer)
            {
                Main.player[Owner].TryUpdateChannel(projectile);
            }
            return num;
        }
References Terraria.Projectile.active, Terraria.Projectile.ai, Terraria.Projectile.aiStyle, Terraria.Projectile.ApplyStatsFromSource(), System.array, Terraria.ID.ProjectileID.Sets.CopiesOwnerAttackCDToLocalImmunityOnSpawn, Terraria.ID.ProjectileID.Count, Terraria.Projectile.Damage(), Terraria.Projectile.damage, Terraria.Projectile.FindBannerToAssociateTo(), Terraria.Projectile.FindOldestProjectile(), Terraria.Entity.height, Terraria.Collision.honey, Terraria.Projectile.identity, Terraria.Projectile.ignoreWater, int, Terraria.ID.ProjectileID.Sets.IsAGolfBall, Terraria.Projectile.Kill(), Terraria.Projectile.localNPCImmunity, Terraria.Main.maxNPCs, Terraria.Player.meleeNPCHitCooldown, Terraria.Main.myPlayer, Terraria.ID.ProjectileID.Sets.NeedsUUID, Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.NoPooling, Terraria.Projectile.owner, Terraria.Main.player, Terraria.Entity.position, Terraria.Main.projectile, Terraria.Projectile.Projectile(), Terraria.Main.projectileIdentity, Terraria.Projectile.projUUID, Terraria.Main.rand, Terraria.NetMessage.SendData(), Terraria.Projectile.SetDefaults(), Terraria.Player.setSquireT2, Terraria.Collision.shimmer, Terraria.ID.ProjectileID.Sets.StardustDragon, Terraria.Projectile.timeLeft, Terraria.Projectile.TrackMinionSpawnSource(), Terraria.Player.TryUpdateChannel(), Terraria.Projectile.type, Terraria.Entity.velocity, Terraria.Collision.WetCollision(), Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, System.X, Microsoft.Xna.Framework.Vector2.Y, and System.Y.