Terraria Decompiled: Terraria.Projectile.SpawnHitVisuals
SpawnHitVisuals()
void Terraria.Projectile.SpawnHitVisuals (Entity target) inline private
Definition at line 13319 of file Projectile.cs.
        {
            if (this.type == 916)
            {
                Projectile.EmitBlackLightningParticles(target.Center);
            }
            if (this.type == 1091)
            {
                if (!this.GetStormLightningExplosionRect().Intersects(target.Hitbox))
                {
                    ParticleOrchestrator.SpawnLightningExplosionDust(target.Center, this.AI_203_GetLightningColor());
                }
                if (this.StormLightningLiquidCollisionCheck(target.Center))
                {
                    Vector2 vector = this._lightningLastHitChainPos ?? base.Center;
                    Vector2 vector2 = Main.rand.NextVector2FromRectangle(target.Hitbox);
                    this._lightningLastHitChainPos = new Vector2?(vector2);
                    ParticleOrchestrator.BroadcastOrRequestParticleSpawn(ParticleOrchestraType.BlueLightningSmallLong, new ParticleOrchestraSettings
                    {
                        PositionInWorld = vector,
                        MovementVector = vector2 - vector
                    });
                }
            }
            if (this.type == 1093)
            {
                ParticleOrchestrator.BroadcastOrRequestParticleSpawn(ParticleOrchestraType.CattivaHit, new ParticleOrchestraSettings
                {
                    PositionInWorld = base.Center + new Vector2((float)(this.direction * 8), 0f) + Main.rand.NextVector2Circular(4f, 4f),
                    MovementVector = Main.rand.NextVector2CircularEdge(4f, 4f)
                });
            }
        }
References Terraria.GameContent.Drawing.ParticleOrchestrator.BroadcastOrRequestParticleSpawn(), Terraria.Entity.Center, Terraria.Projectile.EmitBlackLightningParticles(), Terraria.Entity.Hitbox, Microsoft.Xna.Framework.Intersects, Terraria.Main.rand, and Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnLightningExplosionDust().
Referenced by Terraria.Projectile.Damage_PVE_Inner().