Terraria Decompiled: Terraria.Projectile.ProjLight
ProjLight()
void Terraria.Projectile.ProjLight () inline
Definition at line 14753 of file Projectile.cs.
        {
            if (this.light > 0f)
            {
                float num = this.light;
                float num2 = this.light;
                float num3 = this.light;
                switch (this.type)
                {
                case 987:
                    num *= 0.6f;
                    num2 *= 0.5f;
                    num3 *= 0.1f;
                    break;
                case 988:
                    num *= 0.8f;
                    num2 *= 0.35f;
                    num3 *= 0f;
                    break;
                case 989:
                    num *= 0f;
                    num2 *= 0.65f;
                    num3 *= 0f;
                    break;
                case 990:
                    num *= 0f;
                    num2 *= 0.35f;
                    num3 *= 0.7f;
                    break;
                case 991:
                    num *= 0.9f;
                    num2 *= 0f;
                    num3 *= 0.5f;
                    break;
                case 992:
                    num *= 0.75f;
                    num2 *= 0f;
                    num3 *= 0.75f;
                    break;
                case 993:
                    num *= (float)Main.DiscoR / 255f;
                    num2 *= (float)Main.DiscoG / 255f;
                    num3 *= (float)Main.DiscoB / 255f;
                    break;
                }
                if (this.type == 446)
                {
                    num *= 0f;
                    num3 *= 0.8f;
                }
                else if (this.type == 493 || this.type == 494)
                {
                    num2 *= 0.3f;
                }
                else if (this.type == 876)
                {
                    num *= 0.1f;
                    num2 *= 0.7f;
                    num3 *= 1f;
                }
                else if (this.type == 867)
                {
                    float num4 = (float)Main.rand.Next(28, 42) * 0.005f;
                    num4 += (float)(270 - (int)Main.mouseTextColor) / 500f;
                    num = 0.1f;
                    num2 = 0.3f + num4 / 2f;
                    num3 = 0.6f + num4;
                }
                else if (this.type == 1000)
                {
                    float num5 = (float)Main.rand.Next(28, 42) * 0.005f;
                    num5 += (float)(270 - (int)Main.mouseTextColor) / 500f;
                    num = 0.3f + num5 * 0.25f;
                    num2 = 0.35f + num5 * 0.75f;
                    num3 = 0.5f + num5;
                }
                else if (this.type == 332)
                {
                    num3 *= 0.1f;
                    num2 *= 0.6f;
                }
                else if (this.type == 259)
                {
                    num3 *= 0.1f;
                    if (Main.getGoodWorld)
                    {
                        num = 0f;
                        num2 = 0f;
                        num3 = 0f;
                    }
                }
                else if (this.type == 329)
                {
                    num3 *= 0.1f;
                    num2 *= 0.9f;
                }
                else if (this.type == 2 || this.type == 82)
                {
                    num2 *= 0.75f;
                    num3 *= 0.55f;
                }
                else if (this.type == 172)
                {
                    num2 *= 0.55f;
                    num *= 0.35f;
                }
                else if (this.type == 308)
                {
                    num2 *= 0.7f;
                    num *= 0.1f;
                }
                else if (this.type == 304)
                {
                    num2 *= 0.2f;
                    num3 *= 0.1f;
                }
                else if (this.type == 263)
                {
                    num2 *= 0.7f;
                    num *= 0.1f;
                }
                else if (this.type == 274)
                {
                    num2 *= 0.1f;
                    num *= 0.7f;
                }
                else if (this.type == 254)
                {
                    num *= 0.1f;
                }
                else if (this.type == 94)
                {
                    num *= 0.5f;
                    num2 *= 0f;
                }
                else if (this.type == 95 || this.type == 96 || this.type == 103 || this.type == 104)
                {
                    num *= 0.35f;
                    num2 *= 1f;
                    num3 *= 0f;
                }
                else if (this.type == 4)
                {
                    num2 *= 0.1f;
                    num *= 0.5f;
                }
                else if (this.type == 257)
                {
                    num2 *= 0.9f;
                    num *= 0.1f;
                }
                else if (this.type == 9)
                {
                    num2 *= 0.1f;
                    num3 *= 0.6f;
                }
                else if (this.type == 488)
                {
                    num = 0.3f;
                    num3 = 0.25f;
                    num2 = 0f;
                }
                else if (this.type == 92)
                {
                    num2 *= 0.6f;
                    num *= 0.8f;
                }
                else if (this.type == 93)
                {
                    num2 *= 1f;
                    num *= 1f;
                    num3 *= 0.01f;
                }
                else if (this.type == 12 || this.type == 955)
                {
                    num *= 0.9f;
                    num2 *= 0.8f;
                    num3 *= 0.1f;
                }
                else if (this.type == 14 || this.type == 110 || this.type == 180 || this.type == 242 || this.type == 302)
                {
                    num2 *= 0.7f;
                    num3 *= 0.1f;
                }
                else if (this.type == 981)
                {
                    num2 *= 0.7f;
                    num3 *= 0.7f;
                }
                else if (this.type == 15)
                {
                    num2 *= 0.4f;
                    num3 *= 0.1f;
                    num = 1f;
                }
                else if (this.type == 16)
                {
                    num *= 0.1f;
                    num2 *= 0.4f;
                    num3 = 1f;
                }
                else if (this.type == 18)
                {
                    num2 *= 0.1f;
                    num *= 0.6f;
                }
                else if (this.type == 19)
                {
                    num2 *= 0.5f;
                    num3 *= 0.1f;
                }
                else if (this.type == 20)
                {
                    num *= 0.1f;
                    num3 *= 0.3f;
                }
                else if (this.type == 22)
                {
                    num = 0f;
                    num2 = 0f;
                }
                else if (this.type == 27)
                {
                    num *= 0f;
                    num2 *= 0.3f;
                    num3 = 1f;
                }
                else if (this.type == 34)
                {
                    num2 *= 0.1f;
                    num3 *= 0.1f;
                }
                else if (this.type == 36)
                {
                    num = 0.8f;
                    num2 *= 0.2f;
                    num3 *= 0.6f;
                }
                else if (this.type == 41)
                {
                    num2 *= 0.8f;
                    num3 *= 0.6f;
                }
                else if (this.type == 44 || this.type == 45)
                {
                    num3 = 1f;
                    num *= 0.6f;
                    num2 *= 0.1f;
                }
                else if (this.type == 50)
                {
                    num *= 0.7f;
                    num3 *= 0.8f;
                }
                else if (this.type == 515)
                {
                    num2 *= 0.6f;
                    num3 *= 0.85f;
                }
                else if (this.type == 870)
                {
                    num *= 0.9f;
                    num2 = 0.35f;
                }
                else if (this.type == 53)
                {
                    num *= 0.7f;
                    num2 *= 0.8f;
                }
                else if (this.type == 473)
                {
                    num *= 1.05f;
                    num2 *= 0.95f;
                    num3 *= 0.55f;
                }
                else if (this.type == 1089)
                {
                    num = (float)Main.DiscoR / 255f;
                    num2 = (float)Main.DiscoG / 255f;
                    num3 = (float)Main.DiscoB / 255f;
                }
                else if (this.type == 72)
                {
                    num *= 0.45f;
                    num2 *= 0.75f;
                    num3 = 1f;
                }
                else if (this.type == 86)
                {
                    num *= 1f;
                    num2 *= 0.45f;
                    num3 = 0.75f;
                }
                else if (this.type == 87)
                {
                    num *= 0.45f;
                    num2 = 1f;
                    num3 *= 0.75f;
                }
                else if (this.type == 73)
                {
                    num *= 0.4f;
                    num2 *= 0.6f;
                    num3 *= 1f;
                }
                else if (this.type == 74)
                {
                    num *= 1f;
                    num2 *= 0.4f;
                    num3 *= 0.6f;
                }
                else if (this.type == 284)
                {
                    num *= 1f;
                    num2 *= 0.1f;
                    num3 *= 0.8f;
                }
                else if (this.type == 285)
                {
                    num *= 0.1f;
                    num2 *= 0.5f;
                    num3 *= 1f;
                }
                else if (this.type == 286)
                {
                    num *= 1f;
                    num2 *= 0.5f;
                    num3 *= 0.1f;
                }
                else if (this.type == 287)
                {
                    num *= 0.9f;
                    num2 *= 1f;
                    num3 *= 0.4f;
                }
                else if (this.type == 283)
                {
                    num *= 0.8f;
                    num2 *= 0.1f;
                }
                else if (this.type == 76 || this.type == 77 || this.type == 78)
                {
                    num *= 1f;
                    num2 *= 0.3f;
                    num3 *= 0.6f;
                }
                else if (this.type == 79)
                {
                    num = (float)Main.DiscoR / 255f;
                    num2 = (float)Main.DiscoG / 255f;
                    num3 = (float)Main.DiscoB / 255f;
                }
                else if (this.type == 80)
                {
                    num *= 0f;
                    num2 *= 0.8f;
                    num3 *= 1f;
                }
                else if (this.type == 83 || this.type == 88)
                {
                    num *= 0.7f;
                    num2 *= 0f;
                    num3 *= 1f;
                }
                else if (this.type == 100)
                {
                    num *= 1f;
                    num2 *= 0.5f;
                    num3 *= 0f;
                }
                else if (this.type == 84 || this.type == 389)
                {
                    num *= 0.8f;
                    num2 *= 0f;
                    num3 *= 0.5f;
                }
                else if (this.type == 89 || this.type == 90)
                {
                    num2 *= 0.2f;
                    num3 *= 1f;
                    num *= 0.05f;
                }
                else if (this.type == 106)
                {
                    num *= 0f;
                    num2 *= 0.5f;
                    num3 *= 1f;
                }
                else if (this.type == 113)
                {
                    num *= 0.25f;
                    num2 *= 0.75f;
                    num3 *= 1f;
                }
                else if (this.type == 114 || this.type == 115)
                {
                    num *= 0.5f;
                    num2 *= 0.05f;
                    num3 *= 1f;
                }
                else if (this.type == 116)
                {
                    num3 *= 0.25f;
                }
                else if (this.type == 131)
                {
                    num *= 0.1f;
                    num2 *= 0.4f;
                }
                else if (this.type == 132 || this.type == 157)
                {
                    num *= 0.2f;
                    num3 *= 0.6f;
                }
                else if (this.type == 156)
                {
                    num *= 1f;
                    num3 *= 0.6f;
                    num2 = 0f;
                }
                else if (this.type == 173)
                {
                    num *= 0.3f;
                    num3 *= 1f;
                    num2 = 0.4f;
                }
                else if (this.type == 207)
                {
                    num *= 0.4f;
                    num3 *= 0.4f;
                }
                else if (this.type == 253)
                {
                    num = 0f;
                    num2 *= 0.4f;
                }
                else if (this.type == 211)
                {
                    num *= 0.5f;
                    num2 *= 0.9f;
                    num3 *= 1f;
                    if (this.localAI[0] == 0f)
                    {
                        this.light = 1.5f;
                    }
                    else
                    {
                        this.light = 1f;
                    }
                }
                else if (this.type == 209)
                {
                    float num6 = (255f - (float)this.alpha) / 255f;
                    num *= 0.3f;
                    num2 *= 0.4f;
                    num3 *= 1.75f;
                    num3 *= num6;
                    num *= num6;
                    num2 *= num6;
                }
                else if (this.type == 226 || ((this.type == 221) | (this.type == 229)))
                {
                    num *= 0.25f;
                    num2 *= 1f;
                    num3 *= 0.5f;
                }
                else if (this.type == 251)
                {
                    num = (float)Main.DiscoR / 255f;
                    num2 = (float)Main.DiscoG / 255f;
                    num3 = (float)Main.DiscoB / 255f;
                    num = (num + 1f) / 2f;
                    num2 = (num2 + 1f) / 2f;
                    num3 = (num3 + 1f) / 2f;
                    num *= this.light;
                    num2 *= this.light;
                    num3 *= this.light;
                }
                else if (this.type == 278 || this.type == 279)
                {
                    num *= 1f;
                    num2 *= 1f;
                    num3 *= 0f;
                }
                if (this.type == 870)
                {
                    Vector3 vector = new Vector3(num, num2, num3);
                    DelegateMethods.v3_1 = vector;
                    Point point = base.Center.ToTileCoordinates();
                    DelegateMethods.v2_1 = point.ToVector2();
                    DelegateMethods.f_1 = 4.5f;
                    Utils.FloodFillTile(point, 4.5f, new Utils.TileActionAttempt(DelegateMethods.SpreadLightOpen_StopForSolids));
                    Lighting.AddLight(base.Center, vector);
                    return;
                }
                Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), num, num2, num3);
            }
        }
References Terraria.Lighting.AddLight(), Terraria.Main.DiscoB, Terraria.Main.DiscoG, Terraria.Main.DiscoR, Terraria.Utils.FloodFillTile(), Terraria.Main.getGoodWorld, Terraria.Main.mouseTextColor, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, Terraria.DelegateMethods.SpreadLightOpen_StopForSolids(), and Terraria.Utils.TileActionAttempt().