Terraria Decompiled: Terraria.Projectile.Kill_SpiderBoulder_SpawnSpider
Kill_SpiderBoulder_SpawnSpider()
void Terraria.Projectile.Kill_SpiderBoulder_SpawnSpider () inline
Definition at line 71108 of file Projectile.cs.
        {
            if (Main.netMode == 1)
            {
                return;
            }
            int num = (int)(base.Center.X - this.velocity.X * 2f);
            int num2 = (int)(base.Bottom.Y - this.velocity.Y * 2f);
            bool flag = Main.tile[(int)(base.Center.X / 16f), (int)(base.Bottom.Y / 16f)].wall > 0;
            int num3 = (flag ? 36 : 50);
            int num4 = (flag ? 36 : 20);
            Rectangle rectangle;
            if (Collision.TryChangingSizeFromBottomCenter(base.Hitbox, num3, num4, out rectangle))
            {
                num = rectangle.Left + num3 / 2;
                num2 = rectangle.Top + num4;
            }
            int num5;
            if (flag)
            {
                num5 = NPC.NewNPC(this.GetNPCSource_FromThis(), num, num2, 165, 0, 0f, 0f, 0f, 0f, 255);
            }
            else
            {
                num5 = NPC.NewNPC(this.GetNPCSource_FromThis(), num, num2, 164, 0, 0f, 0f, 0f, 0f, 255);
            }
            if (num5 >= 0)
            {
                Main.npc[num5].netUpdate = true;
                NetMessage.SendData(23, -1, -1, null, num5, 0f, 0f, 0f, 0, 0, 0);
            }
        }
References int, Terraria.Main.netMode, Terraria.NPC.netUpdate, Terraria.NPC.NewNPC(), Terraria.Main.npc, Terraria.NetMessage.SendData(), Terraria.Main.tile, Terraria.Collision.TryChangingSizeFromBottomCenter(), and Terraria.Tile.wall.