Terraria Decompiled: Terraria.Projectile.GetAlpha
GetAlpha()
Color Terraria.Projectile.GetAlpha (Color newColor) inline
Definition at line 81026 of file Projectile.cs.
        {
            if (ProjectileID.Sets.IsAPhaseblade[this.type])
            {
                return Color.White;
            }
            if (this.type == 920 || this.type == 921 || this.type == 926)
            {
                return Color.Lerp(newColor, Color.White, 0.4f) * this.Opacity;
            }
            if (this.type == 47 && Main.player[this.owner].wet)
            {
                return Color.White;
            }
            if (this.type == 1099)
            {
                if (this.alpha > 0)
                {
                    return new Color(0, 0, 0, 0);
                }
                int num = Main.rand.Next(255);
                int num2 = Main.rand.Next(255);
                int num3 = Main.rand.Next(255);
                return new Color(num, num2, num3, 200);
            }
            else
            {
                if (this.type == 1055)
                {
                    return new Color((int)newColor.R, (int)newColor.G, (int)newColor.B, (int)(byte.MaxValue - (byte)this.localAI[0]));
                }
                if (this.type == 1090)
                {
                    float num4 = this.localAI[2];
                    Color color = new Color(255, 255, 255, 255);
                    if (num4 == 0f)
                    {
                        return newColor;
                    }
                    if (num4 == 1f)
                    {
                        return color;
                    }
                    return Color.Lerp(newColor, color, num4);
                }
                else
                {
                    if (this.type == 937)
                    {
                        newColor.A = (byte)((float)newColor.A * 0.75f);
                    }
                    if (this.type == 880 || this.type == 929)
                    {
                        newColor.A /= 2;
                    }
                    if (this.type == 963)
                    {
                        float num5 = 0.85f;
                        newColor *= num5;
                        newColor.A = (byte)((float)newColor.A * num5);
                        if (this.ai[0] >= 2f)
{
                            newColor.G = (byte)((float)newColor.G * 0.7f);
                            newColor.B = (byte)((float)newColor.B * 0.7f);
                        }
                    }
                    if (this.type == 1021)
                    {
                        return Color.White;
                    }
                    if (this.type == 1006)
                    {
                        return Color.White;
                    }
                    if (this.type == 981)
                    {
                        return Color.White;
                    }
                    if (this.type == 75)
                    {
                        return Color.Lerp(newColor, Color.White, 0.66f) * this.Opacity;
                    }
                    if (this.type == 969)
                    {
                        int num6 = 210;
                        int num;
                        int num3;
                        int num2 = (num = (num3 = num6));
                        if ((int)newColor.R < num6)
{
                            num = (int)newColor.R;
                        }
                        if ((int)newColor.G < num6)
{
                            num2 = (int)newColor.G;
                        }
                        if ((int)newColor.B < num6)
{
                            num3 = (int)newColor.B;
                        }
                        return new Color(num, num2, num3, 185) * this.Opacity;
                    }
                    if (this.type == 967)
                    {
                        return Color.White * this.Opacity;
                    }
                    if (this.type == 855)
                    {
                        newColor = Color.Lerp(newColor, new Color(255, 200, 60), 0.5f);
                    }
                    if (this.type == 933 || this.type == 1001 || this.type == 1100)
                    {
                        newColor = Color.White * this.Opacity;
                    }
                    if (this.type == 270)
                    {
                        return new Color(255, 255, 255, (int)Utils.WrappedLerp(0f, 255f, (float)(this.timeLeft % 40) / 40f));
                    }
                    if (this.type == 837)
                    {
                        if (this.alpha > 0)
{
                            return Color.Transparent;
                        }
                        return new Color(255, 255, 255, 200);
                    }
                    else
                    {
                        if (this.type == 180 || this.type == 345)
{
                            return Color.Lerp(newColor, Color.White, 0.75f);
                        }
                        if (this.type == 586)
{
                            if (this.ai[2] == 1f)
{
                                Color color2 = new Color((int)(newColor.R / 2), 0, (int)newColor.G);
                                float num7 = (float)Math.Sin((double)(this.ai[0] % 120f * 6.2831855f / 120f)) * 0.5f + 0.5f;
                                newColor = Color.Lerp(newColor, color2, num7);
                                return Color.Lerp(newColor, Color.Lerp(Color.White, color2, num7), 0.75f);
                            }
                            return Color.Lerp(newColor, Color.White, 0.75f);
                        }
                        else
{
                            if (this.type == 764 || this.type == 856 || this.type == 857 || this.type == 864)
{
                                return Color.White;
                            }
                            if (this.type == 873 || this.type == 872 || this.type == 931 || this.type == 913 || this.type == 34 || this.type == 1039)
{
                                return Color.White * this.Opacity;
                            }
                            if (this.type == 756 || this.type == 961)
{
                                return Color.Lerp(newColor, Color.Black, 0.25f);
                            }
                            if (this.type == 1041)
{
                                if (this.alpha == 255)
{
                                    return Color.Transparent;
                                }
                                return Color.White;
                            }
                            else
{
                                if (this.type == 895)
{
                                    return Color.White * this.Opacity;
                                }
                                if (this.type == 893 || this.type == 907)
{
                                    return new Color(255, 255, 255, 150);
                                }
                                if (this.type == 833 || this.type == 834 || this.type == 835 || this.type == 912)
{
                                    return Color.Lerp(newColor, Color.White, 0.25f);
                                }
                                if (this.type == 351 || this.type == 350)
{
                                    Point point = base.Center.ToTileCoordinates();
                                    if (WorldGen.InWorld(point.X, point.Y, 0) && !WorldGen.SolidTile(point.X, point.Y, false))
{
                                        return Color.Lerp(newColor, Color.White, 0.15f);
                                    }
                                    return Color.Lerp(newColor, Color.White, 0.05f);
                                }
                                else
{
                                    if (this.type == 346 || this.type == 347 || this.type == 325 || this.type == 755)
{
                                        return Color.Lerp(newColor, Color.White, 0.75f);
                                    }
                                    int num;
                                    int num2;
                                    int num3;
                                    if (this.type == 650)
{
                                        num = (int)((double)newColor.R * 1.5);
                                        num2 = (int)((double)newColor.G * 1.5);
                                        num3 = (int)((double)newColor.B * 1.5);
                                        if (num > 255)
{
                                        }
                                        if (num2 > 255)
{
                                        }
                                        if (num3 > 255)
{
                                        }
                                    }
                                    else
{
                                        if (this.type == 948)
{
                                            return Color.White;
                                        }
                                        if (this.type == 604 || this.type == 631)
{
                                            return new Color(255 - this.alpha, 255 - this.alpha, 255 - this.alpha, 0);
                                        }
                                        if (this.type == 342)
{
                                            return Color.Lerp(newColor, Color.White, 0.75f) * this.Opacity;
                                        }
                                        if (this.type == 636)
{
                                            return new Color(255 - this.alpha, 255 - this.alpha, 255 - this.alpha, 64 - this.alpha / 4);
                                        }
                                        if (this.type == 673 || this.type == 706)
{
                                            return new Color(255 - this.alpha, 255 - this.alpha, 255 - this.alpha, 180 - this.alpha / 2 - this.alpha / 4);
                                        }
                                        if (this.type == 603 || this.type == 633)
{
                                            return new Color(255, 255, 255, 200);
                                        }
                                        if (this.type == 623 || (this.type >= 625 && this.type <= 628) || this.type == 710)
{
                                            return new Color(255 - this.alpha, 255 - this.alpha, 255 - this.alpha, 255 - this.alpha);
                                        }
                                        if (this.type == 645 || this.type == 643)
{
                                            return new Color(255 - this.alpha, 255 - this.alpha, 255 - this.alpha, 127 - this.alpha / 2);
                                        }
                                        if (this.type == 611)
{
                                            return new Color(255, 255, 255, 200);
                                        }
                                        if (this.type == 640 || this.type == 644 || this.type == 658)
{
                                            return new Color(255 - this.alpha, 255 - this.alpha, 255 - this.alpha, 0);
                                        }
                                        if (this.type == 612 || this.type == 953)
{
                                            return new Color(255, 255, 255, 127);
                                        }
                                        if (this.type == 978)
{
                                            return new Color(255, 255, 255, 127) * this.Opacity;
                                        }
                                        if (this.type == 567 || this.type == 568)
{
                                            return new Color(255 - this.alpha, 255 - this.alpha, 255 - this.alpha, 255 - this.alpha);
                                        }
                                        if (this.type == 554)
{
                                            return new Color(200, 200, 200, 200);
                                        }
                                        if (this.type == 601)
{
                                            return PortalHelper.GetPortalColor(this.owner, (int)this.ai[0]);
                                        }
                                        if (this.type == 602)
{
                                            Color portalColor = PortalHelper.GetPortalColor(this.owner, (int)this.ai[1]);
                                            portalColor.A = 227;
                                            return portalColor;
                                        }
                                        if (this.type == 585)
{
                                            byte a = newColor.A;
                                            newColor = Color.Lerp(newColor, Color.White, 0.5f);
                                            newColor.A = a;
                                            return newColor;
                                        }
                                        if (this.type == 714)
{
                                            byte a2 = newColor.A;
                                            newColor = Color.Lerp(newColor, Color.White, 0.8f);
                                            newColor.A = a2;
                                            newColor *= (float)a2 / 255f;
                                            return newColor;
                                        }
                                        if (this.type == 573 || this.type == 578 || this.type == 579 || this.type == 617 || this.type == 641 || this.type == 707 || this.type == 813)
{
                                            return new Color(255 - this.alpha, 255 - this.alpha, 255 - this.alpha, 255 - this.alpha);
                                        }
                                        if (this.type == 490)
{
                                            return Color.White;
                                        }
                                        if (this.type == 575 || this.type == 596 || this.type == 659)
{
                                            if (this.timeLeft < 30)
{
                                                float num8 = (float)this.timeLeft / 30f;
                                                this.alpha = (int)(255f - 255f * num8);
                                            }
                                            return new Color(255 - this.alpha, 255 - this.alpha, 255 - this.alpha, 128 - this.alpha / 2);
                                        }
                                        if (this.type == 546)
{
                                            return new Color(255, 200, 255, 200);
                                        }
                                        if (this.type == 553)
{
                                            return new Color(255, 255, 200, 200);
                                        }
                                        if (this.type == 540)
{
                                            return new Color(255 - this.alpha, 255 - this.alpha, 255 - this.alpha, 0);
                                        }
                                        if (this.type == 498)
{
                                            return new Color(255, 100, 20, 200);
                                        }
                                        if (this.type == 538)
{
                                            return new Color(255 - this.alpha, 255 - this.alpha, 255 - this.alpha, 255 - this.alpha);
                                        }
                                        if (this.type == 518)
{
                                            float num9 = 1f - (float)this.alpha / 255f;
                                            return new Color((int)(200f * num9), (int)(200f * num9), (int)(200f * num9), (int)(100f * num9));
                                        }
                                        if (this.type == 518 || this.type == 595 || this.type == 735)
{
                                            Color color3 = Color.Lerp(newColor, Color.White, 0.85f);
                                            color3.A = 128;
                                            return color3 * (1f - (float)this.alpha / 255f);
                                        }
                                        if (this.type == 536 || this.type == 607)
{
                                            return new Color(255 - this.alpha, 255 - this.alpha, 255 - this.alpha, 63 - this.alpha / 4);
                                        }
                                        if (this.type == 591)
{
                                            return new Color(255 - this.alpha, 255 - this.alpha, 255 - this.alpha, 63 - this.alpha / 4);
                                        }
                                        if (this.type == 493 || this.type == 494)
{
                                            return new Color(255 - this.alpha, 255 - this.alpha, 255 - this.alpha, 255 - this.alpha);
                                        }
                                        if (this.type == 492)
{
                                            return new Color(255, 255, 255, 255);
                                        }
                                        if (this.type == 491)
{
                                            return new Color(255, 255, 255, 255);
                                        }
                                        if (this.type == 485 || this.type == 502)
{
                                            return new Color(255, 255, 255, 200);
                                        }
                                        if (this.type == 488 || this.type == 1047)
{
                                            return new Color(255, 255, 255, 255);
                                        }
                                        if (this.type == 477 || this.type == 478 || this.type == 479)
{
                                            if (this.alpha == 0)
{
                                                return new Color(255, 255, 255, 200);
                                            }
                                            return new Color(0, 0, 0, 0);
                                        }
                                        else
{
                                            if (this.type == 473)
{
                                                return new Color(255, 255, 255, 255);
                                            }
                                            if (this.type == 50 || this.type == 53 || this.type == 515 || this.type == 870)
{
                                                return new Color(255, 255, 255, 0);
                                            }
                                            if (this.type == 1089)
{
                                                return new Color(Main.DiscoR, Main.DiscoG, Main.DiscoB, 70);
                                            }
                                            if (this.type == 1024)
{
                                                return new Color(255, 255, 255) * this.Opacity;
                                            }
                                            if (this.type == 723 || this.type == 724 || this.type == 725 || this.type == 726 || this.type == 728 || this.type == 9)
{
                                                return new Color(255, 255, 255, 0) * this.Opacity;
                                            }
                                            if (this.type == 92)
{
                                                return new Color(255, 255, 255, 0);
                                            }
                                            if (this.type == 91)
{
                                                return new Color(200, 200, 200, 0);
                                            }
                                            if (this.type == 34 || this.type == 15 || this.type == 93 || this.type == 94 || this.type == 95 || this.type == 96 || this.type == 253 || this.type == 258 || (this.type == 102 && this.alpha < 255))
{
                                                return new Color(200, 200, 200, 25);
                                            }
                                            if (this.type == 465)
{
                                                return new Color(255, 255, 255, 0) * (1f - (float)this.alpha / 255f);
                                            }
                                            if (this.type == 503)
{
                                                Color color4 = Color.Lerp(newColor, Color.White, 0.5f) * (1f - (float)this.alpha / 255f);
                                                Color color5 = Color.Lerp(Color.Purple, Color.White, 0.33f);
                                                float num10 = 0.25f + (float)Math.Cos((double)this.localAI[0]) * 0.25f;
                                                return Color.Lerp(color4, color5, num10);
                                            }
                                            if (this.type == 467)
{
                                                return new Color(255, 255, 255, 255) * (1f - (float)this.alpha / 255f);
                                            }
                                            if (this.type == 694 || this.type == 695 || this.type == 696)
{
                                                return new Color(255, 255, 255, 127) * (1f - (float)this.alpha / 255f);
                                            }
                                            if (this.type == 634 || this.type == 635)
{
                                                return new Color(255, 255, 255, 127) * this.Opacity;
                                            }
                                            if (this.type == 671)
{
                                                return new Color(255, 255, 255, 255) * this.Opacity;
                                            }
                                            if (this.type == 664 || this.type == 666 || this.type == 668)
{
                                                newColor = Color.Lerp(newColor, Color.White, 0.5f);
                                                return new Color((int)newColor.R, (int)newColor.G, (int)newColor.B, 200) * this.Opacity;
                                            }
                                            if (this.type == 451)
{
                                                return new Color(255, 255, 255, 200) * ((255f - (float)this.alpha) / 255f);
                                            }
                                            if (this.type == 684)
{
                                                return new Color(255, 255, 255, 200) * ((255f - (float)this.alpha) / 255f);
                                            }
                                            if (this.type == 454 || this.type == 452)
{
                                                return new Color(255, 255, 255, 255) * (1f - (float)this.alpha / 255f);
                                            }
                                            if (this.type == 464)
{
                                                return new Color(255, 255, 255, 255) * ((255f - (float)this.alpha) / 255f);
                                            }
                                            if (this.type == 450)
{
                                                return new Color(200, 200, 200, 255 - this.alpha);
                                            }
                                            if (this.type == 459 || this.type == 709)
{
                                                return new Color(255, 255, 255, 200);
                                            }
                                            if (this.type == 447)
{
                                                return new Color(255, 255, 255, 200);
                                            }
                                            if (this.type == 446)
{
                                                return Color.Lerp(newColor, Color.White, 0.8f) * (1f - (float)this.alpha / 255f);
                                            }
                                            if (this.type == 691 || this.type == 692 || this.type == 693)
{
                                                return Color.Lerp(newColor, Color.White, 0.4f) * (1f - (float)this.alpha / 255f);
                                            }
                                            if (this.type >= 646 && this.type <= 649)
{
                                                return Color.Lerp(newColor, Color.White, 0.8f) * (1f - (float)this.alpha / 255f);
                                            }
                                            if (this.type == 445)
{
                                                return new Color(255, 255, 255, 128) * (1f - (float)this.alpha / 255f);
                                            }
                                            if (this.type == 440 || this.type == 449 || this.type == 606)
{
                                                num = 255 - this.alpha;
                                                num2 = 255 - this.alpha;
                                                num3 = 255 - this.alpha;
                                            }
                                            else
{
                                                if (this.type == 444)
{
                                                    return newColor * (1f - (float)this.alpha / 255f);
                                                }
                                                if (this.type == 443 || this.type == 675 || this.type == 686 || this.type == 711 || this.type == 1097 || this.type == 1110)
{
                                                    return new Color(255, 255, 255, 128) * (1f - (float)this.alpha / 255f);
                                                }
                                                if (this.type == 676)
{
                                                    return newColor * this.Opacity;
                                                }
                                                if (this.type == 438)
{
                                                    return new Color(255, 255, 255, 128) * (1f - (float)this.alpha / 255f);
                                                }
                                                if (this.type == 592)
{
                                                    return new Color(255, 255, 255, 128) * (1f - (float)this.alpha / 255f);
                                                }
                                                if (this.type == 437 || this.type == 700)
{
                                                    return new Color(255, 255, 255, 0) * (1f - (float)this.alpha / 255f);
                                                }
                                                if (this.type == 964 || this.type == 965)
{
                                                    return new Color(255, 255, 255, 255) * this.Opacity;
                                                }
                                                if (this.type == 462)
{
                                                    return new Color(255, 255, 255, 128) * (1f - (float)this.alpha / 255f);
                                                }
                                                if (this.type == 352)
{
                                                    Color color6 = Color.Lerp(newColor, Color.White, 0.5f);
                                                    color6.A = (byte)((float)color6.A * ((float)this.alpha / 255f));
                                                    return new Color((int)color6.R, (int)color6.G, (int)color6.B, (int)color6.A);
                                                }
                                                if (this.type == 435 || this.type == 732 || this.type == 731)
{
                                                    newColor = Color.Lerp(newColor, Color.White, 0.8f);
                                                    return new Color((int)newColor.R, (int)newColor.G, (int)newColor.B, 25);
                                                }
                                                if (this.type == 682)
{
                                                    newColor = Color.Lerp(newColor, Color.White, 0.8f);
                                                    return new Color((int)newColor.R, (int)newColor.G, (int)newColor.B, 127);
                                                }
                                                if (this.type == 436)
{
                                                    newColor = Color.Lerp(newColor, Color.White, 0.8f);
                                                    return new Color((int)newColor.R, (int)newColor.G, (int)newColor.B, 25);
                                                }
                                                if (this.type == 409)
{
                                                    return new Color(250, 250, 250, 200);
                                                }
                                                if (this.type == 348 || this.type == 349)
{
                                                    return new Color(200, 200, 200, this.alpha);
                                                }
                                                if (this.type == 337)
{
                                                    return new Color(250, 250, 250, 150);
                                                }
                                                if (this.type >= 424 && this.type <= 426)
{
                                                    byte b = 150;
                                                    if (newColor.R < b)
{
                                                        newColor.R = b;
                                                    }
                                                    if (newColor.G < b)
{
                                                        newColor.G = b;
                                                    }
                                                    if (newColor.B < b)
{
                                                        newColor.B = b;
                                                    }
                                                    return new Color((int)newColor.R, (int)newColor.G, (int)newColor.B, 255);
                                                }
                                                if (this.type == 431 || this.type == 432)
{
                                                    return new Color(250, 250, 250, 255 - this.alpha);
                                                }
                                                if (this.type == 343 || this.type == 344)
{
                                                    float num11 = 1f - (float)this.alpha / 255f;
                                                    return new Color((int)(250f * num11), (int)(250f * num11), (int)(250f * num11), (int)(100f * num11));
                                                }
                                                if (this.type == 332)
{
                                                    return new Color(255, 255, 255, 255);
                                                }
                                                if (this.type == 329)
{
                                                    return new Color(200, 200, 200, 50);
                                                }
                                                if (this.type >= 326 && this.type <= 328)
{
                                                    return Color.Transparent;
                                                }
                                                if ((this.type >= 400 && this.type <= 402) || (this.type >= 1107 && this.type <= 1109))
{
                                                    return Color.Transparent;
                                                }
                                                if (this.type == 324 && this.frame >= 6 && this.frame <= 9)
{
                                                    return new Color(255, 255, 255, 255);
                                                }
                                                if (this.type == 16)
{
                                                    return new Color(255, 255, 255, 0);
                                                }
                                                if (this.type == 321)
{
                                                    return new Color(200, 200, 200, 0);
                                                }
                                                if (this.type == 76 || this.type == 77 || this.type == 78)
{
                                                    return new Color(255, 255, 255, 0);
                                                }
                                                if (this.type == 308)
{
                                                    return new Color(200, 200, 255, 125);
                                                }
                                                if (this.type == 263)
{
                                                    if (this.timeLeft < 255)
{
                                                        return new Color(255, 255, 255, (int)((byte)this.timeLeft));
                                                    }
                                                    return new Color(255, 255, 255, 255);
                                                }
                                                else if (this.type == 274)
{
                                                    if (this.timeLeft < 85)
{
                                                        byte b2 = (byte)(this.timeLeft * 3);
                                                        byte b3 = (byte)(100f * ((float)b2 / 255f));
                                                        return new Color((int)b2, (int)b2, (int)b2, (int)b3);
                                                    }
                                                    return new Color(255, 255, 255, 100);
                                                }
                                                else
{
                                                    if (this.type == 5)
{
                                                        return new Color(255, 255, 255, 0);
                                                    }
                                                    if (this.type == 300)
{
                                                        return new Color(250, 250, 250, 50);
                                                    }
                                                    if (this.type == 301)
{
                                                        if (this.ai[0] == 1f)
{
                                                            return newColor;
                                                        }
                                                        return new Color(250, 250, 250, 50);
                                                    }
                                                    else
{
                                                        if (this.type == 712)
{
                                                            return Color.Lerp(newColor, Color.White, 0.4f) * this.Opacity;
                                                        }
                                                        if (this.type == 304)
{
                                                            return new Color(255 - this.alpha, 255 - this.alpha, 255 - this.alpha, (int)((byte)((float)(255 - this.alpha) / 3f)));
                                                        }
                                                        if (this.type == 116 || this.type == 132 || this.type == 156 || this.type == 157 || this.type == 157 || this.type == 173)
{
                                                            if (this.localAI[1] >= 15f)
{
                                                                return new Color(255, 255, 255, this.alpha);
                                                            }
                                                            if (this.localAI[1] < 5f)
{
                                                                return Color.Transparent;
                                                            }
                                                            int num12 = (int)((this.localAI[1] - 5f) / 10f * 255f);
                                                            return new Color(num12, num12, num12, num12);
                                                        }
                                                        else
{
                                                            if (this.type == 254)
{
                                                                if (this.timeLeft < 30)
{
                                                                    float num13 = (float)this.timeLeft / 30f;
                                                                    this.alpha = (int)(255f - 255f * num13);
                                                                }
                                                                return new Color(255 - this.alpha, 255 - this.alpha, 255 - this.alpha, 0);
                                                            }
                                                            if (this.type == 265 || this.type == 355)
{
                                                                if (this.alpha > 0)
{
                                                                    return Color.Transparent;
                                                                }
                                                                return new Color(255, 255, 255, 0);
                                                            }
                                                            else if (this.type == 257)
{
                                                                if (this.alpha > 200)
{
                                                                    return Color.Transparent;
                                                                }
                                                                return new Color(255 - this.alpha, 255 - this.alpha, 255 - this.alpha, 0);
                                                            }
                                                            else if (this.type == 259)
{
                                                                if (this.alpha > 200)
{
                                                                    return Color.Transparent;
                                                                }
                                                                return new Color(255 - this.alpha, 255 - this.alpha, 255 - this.alpha, 0);
                                                            }
                                                            else
{
                                                                if (this.type >= 150 && this.type <= 152)
{
                                                                    return new Color(255 - this.alpha, 255 - this.alpha, 255 - this.alpha, 255 - this.alpha);
                                                                }
                                                                if (this.type == 250)
{
                                                                    return Color.Transparent;
                                                                }
                                                                if (this.type == 251)
{
                                                                    num = 255 - this.alpha;
                                                                    num2 = 255 - this.alpha;
                                                                    num3 = 255 - this.alpha;
                                                                    return new Color(num, num2, num3, 0);
                                                                }
                                                                if (this.type == 131)
{
                                                                    return new Color(255 - this.alpha, 255 - this.alpha, 255 - this.alpha, 0);
                                                                }
                                                                if (this.type == 211)
{
                                                                    return new Color(255, 255, 255, 0);
                                                                }
                                                                if (this.type == 229)
{
                                                                    return new Color(255, 255, 255, 50);
                                                                }
                                                                if (this.type == 221 || this.type == 729 || this.type == 977)
{
                                                                    return new Color(255, 255, 255, 200);
                                                                }
                                                                if (this.type == 1045)
{
                                                                    return new Color(255, 255, 255, 200) * this.Opacity;
                                                                }
                                                                if (this.type == 20)
{
                                                                    if (this.alpha <= 150)
{
                                                                        return new Color(255, 255, 255, 0);
                                                                    }
                                                                    return new Color(0, 0, 0, 0);
                                                                }
                                                                else if (this.type == 207)
{
                                                                    num = 255 - this.alpha;
                                                                    num2 = 255 - this.alpha;
                                                                    num3 = 255 - this.alpha;
                                                                }
                                                                else if (this.type == 242)
{
                                                                    if (this.alpha < 140)
{
                                                                        return new Color(255, 255, 255, 100);
                                                                    }
                                                                    return Color.Transparent;
                                                                }
                                                                else
{
                                                                    if (this.type == 638)
{
                                                                        return new Color(255, 255, 255, 100) * this.Opacity;
                                                                    }
                                                                    if (this.type == 660)
{
                                                                        return new Color(150, 255, 255, 0) * this.Opacity;
                                                                    }
                                                                    if (this.type == 209)
{
                                                                        num = (int)newColor.R - this.alpha;
                                                                        num2 = (int)newColor.G - this.alpha;
                                                                        num3 = (int)newColor.B - this.alpha / 2;
                                                                    }
                                                                    else
{
                                                                        if (this.type == 130)
{
                                                                            return new Color(255, 255, 255, 175);
                                                                        }
                                                                        if (this.type == 182)
{
                                                                            return new Color(255, 255, 255, 200);
                                                                        }
                                                                        if (this.type == 226)
{
                                                                            num = 255;
                                                                            num2 = 255;
                                                                            num3 = 255;
                                                                            float num14 = (float)Main.mouseTextColor / 200f - 0.3f;
                                                                            num = (int)((float)num * num14);
                                                                            num2 = (int)((float)num2 * num14);
                                                                            num3 = (int)((float)num3 * num14);
                                                                            num += 50;
                                                                            if (num > 255)
{
                                                                                num = 255;
                                                                            }
                                                                            num2 += 50;
                                                                            if (num2 > 255)
{
                                                                                num2 = 255;
                                                                            }
                                                                            num3 += 50;
                                                                            if (num3 > 255)
{
                                                                                num3 = 255;
                                                                            }
                                                                            return new Color(num, num2, num3, 200);
                                                                        }
                                                                        if (this.type == 227)
{
                                                                            num2 = (num = (num3 = 255));
                                                                            float num15 = (float)Main.mouseTextColor / 100f - 1.6f;
                                                                            num = (int)((float)num * num15);
                                                                            num2 = (int)((float)num2 * num15);
                                                                            num3 = (int)((float)num3 * num15);
                                                                            int num16 = (int)(100f * num15);
                                                                            num += 50;
                                                                            if (num > 255)
{
                                                                                num = 255;
                                                                            }
                                                                            num2 += 50;
                                                                            if (num2 > 255)
{
                                                                                num2 = 255;
                                                                            }
                                                                            num3 += 50;
                                                                            if (num3 > 255)
{
                                                                                num3 = 255;
                                                                            }
                                                                            return new Color(num, num2, num3, num16);
                                                                        }
                                                                        if (this.type == 114 || this.type == 115)
{
                                                                            if (this.localAI[1] >= 15f)
{
                                                                                return new Color(255, 255, 255, this.alpha);
                                                                            }
                                                                            if (this.localAI[1] < 5f)
{
                                                                                return Color.Transparent;
                                                                            }
                                                                            int num17 = (int)((this.localAI[1] - 5f) / 10f * 255f);
                                                                            return new Color(num17, num17, num17, num17);
                                                                        }
                                                                        else if (this.type == 83 || this.type == 88 || this.type == 89 || this.type == 90 || this.type == 100 || this.type == 104 || this.type == 279 || (this.type >= 283 && this.type <= 287) || this.type == 876)
{
                                                                            if (this.alpha < 200)
{
                                                                                return new Color(255 - this.alpha, 255 - this.alpha, 255 - this.alpha, 0);
                                                                            }
                                                                            return Color.Transparent;
                                                                        }
                                                                        else
{
                                                                            if (this.type == 34 || this.type == 35 || this.type == 15 || this.type == 19 || this.type == 44 || this.type == 45)
{
                                                                                return Color.White;
                                                                            }
                                                                            if (this.type == 79)
{
                                                                                num = Main.DiscoR;
                                                                                num2 = Main.DiscoG;
                                                                                num3 = Main.DiscoB;
                                                                                return default(Color);
                                                                            }
                                                                            if (this.type == 9 || this.type == 15 || this.type == 34 || this.type == 50 || this.type == 53 || this.type == 76 || this.type == 77 || this.type == 78 || this.type == 92 || this.type == 91)
{
                                                                                num = (int)newColor.R - this.alpha / 3;
                                                                                num2 = (int)newColor.G - this.alpha / 3;
                                                                                num3 = (int)newColor.B - this.alpha / 3;
                                                                            }
                                                                            else
{
                                                                                if (this.type == 18)
{
                                                                                    return new Color(255, 255, 255, 130);
                                                                                }
                                                                                if (this.type == 16 || this.type == 44 || this.type == 45)
{
                                                                                    num = (int)newColor.R;
                                                                                    num2 = (int)newColor.G;
                                                                                    num3 = (int)newColor.B;
                                                                                }
                                                                                else if (this.type == 12 || this.type == 72 || this.type == 86 || this.type == 87 || this.type == 955)
{
                                                                                    return new Color(255, 255, 255, (int)newColor.A - this.alpha);
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                    if (this.aiStyle == 99 && Main.player[this.owner].stringColor == 29 && this.alpha == 0)
{
                                        return Color.White;
                                    }
                                    float num18 = (float)(255 - this.alpha) / 255f;
                                    num = (int)((float)newColor.R * num18);
                                    num2 = (int)((float)newColor.G * num18);
                                    num3 = (int)((float)newColor.B * num18);
                                    int num19 = (int)newColor.A - this.alpha;
                                    if (num19 < 0)
{
                                        num19 = 0;
                                    }
                                    if (num19 > 255)
{
                                        num19 = 255;
                                    }
                                    return new Color(num, num2, num3, num19);
                                }
                            }
                        }
                    }
                }
            }
        }
References Microsoft.Xna.Framework.Color.A, Microsoft.Xna.Framework.Color.B, Microsoft.Xna.Framework.Color.Black, System.Math.Cos(), Terraria.Main.DiscoB, Terraria.Main.DiscoG, Terraria.Main.DiscoR, Microsoft.Xna.Framework.Color.G, Terraria.GameContent.PortalHelper.GetPortalColor(), int, Terraria.WorldGen.InWorld(), Terraria.ID.ProjectileID.Sets.IsAPhaseblade, Microsoft.Xna.Framework.Color.Lerp(), Terraria.Main.mouseTextColor, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.player, Microsoft.Xna.Framework.Color.Purple, Microsoft.Xna.Framework.Color.R, Terraria.Main.rand, System.Math.Sin(), Terraria.WorldGen.SolidTile(), Terraria.Player.stringColor, Microsoft.Xna.Framework.Color.Transparent, Terraria.Entity.wet, Microsoft.Xna.Framework.Color.White, Terraria.Utils.WrappedLerp(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.Main.DrawKite(), Terraria.Main.DrawMultisegmentPet(), Terraria.Main.DrawProj_PiercingStarlight(), Terraria.Main.DrawProj_Spear(), Terraria.Main.DrawProjDirect(), Terraria.Main.DrawTwinsPet(), Terraria.Main.DrawWhip_CoolWhip(), and Terraria.Main.DrawWhip_FireWhip().