Terraria Decompiled: Terraria.Projectile.GetWhipSettings
GetWhipSettings()
static void Terraria.Projectile.GetWhipSettings (Projectile proj, out float timeToFlyOut, out int segments, out float rangeMultiplier) inline static
Definition at line 48803 of file Projectile.cs.
        {
            timeToFlyOut = (float)(Main.player[proj.owner].itemAnimationMax * proj.MaxUpdates);
            if (proj.isAPreviewDisplayDoll)
            {
                timeToFlyOut = 60f;
            }
            segments = 20;
            rangeMultiplier = 1f;
            int num = proj.type;
            if (num <= 915)
            {
                if (num == 841)
                {
                    rangeMultiplier *= 0.75f;
                    return;
                }
                switch (num)
                {
                case 847:
                    segments = 20;
                    rangeMultiplier *= 1.75f;
                    return;
                case 848:
                    segments = 40;
                    rangeMultiplier = 1.6f;
                    return;
                case 849:
                    segments = 30;
                    rangeMultiplier = 2.15f;
                    return;
                default:
                    switch (num)
                    {
                    case 912:
                        rangeMultiplier *= 1.5f;
                        return;
                    case 913:
                        rangeMultiplier *= 1.4f;
                        return;
                    case 914:
                        rangeMultiplier *= 1f;
                        return;
                    case 915:
                        segments = 40;
                        rangeMultiplier = 2.2f;
                        return;
                    default:
                        return;
                    }
                    break;
                }
            }
            else
            {
                if (num != 952)
                {
                    switch (num)
                    {
                    case 1028:
                        segments = 12;
                        rangeMultiplier *= 0.75f;
                        return;
                    case 1029:
                        rangeMultiplier *= 0.95f;
                        return;
                    case 1030:
                        rangeMultiplier *= 0.85f;
                        return;
                    case 1031:
                        rangeMultiplier *= 1.1f;
                        return;
                    case 1032:
                        rangeMultiplier *= 1.8f;
                        return;
                    case 1033:
                        segments = 45;
                        rangeMultiplier = 2f;
                        return;
                    case 1034:
                        rangeMultiplier *= 2.2f;
                        return;
                    case 1035:
                        segments = 30;
                        rangeMultiplier *= 2.2f;
                        if (proj.ai[2] >= 10f)
{
                            timeToFlyOut = (float)(30 * proj.MaxUpdates);
                        }
                        break;
                    default:
                        if (num == 1104)
{
                            segments = 36;
                            rangeMultiplier *= 0.75f;
                            return;
                        }
                        break;
                    }
                    return;
                }
                rangeMultiplier *= 0.95f;
                return;
            }
        }
References Terraria.Projectile.ai, Terraria.Projectile.isAPreviewDisplayDoll, Terraria.Player.itemAnimationMax, Terraria.Projectile.MaxUpdates, Terraria.Projectile.owner, Terraria.Main.player, and Terraria.Projectile.type.
Referenced by Terraria.Projectile.AI_165_Whip(), Terraria.Main.DrawWhip_Constellation(), Terraria.Main.DrawWhip_WhipBland(), Terraria.Main.DrawWhip_WhipMace(), Terraria.Main.DrawWhip_WhipScythe(), Terraria.Projectile.FillWhipControlPoints(), Terraria.Projectile.GetWhipAnimationPercent(), and Terraria.Projectile.StatusNPC().