Terraria Decompiled: Terraria.Projectile.AI_197_CeilingAndHoverTurret
AI_197_CeilingAndHoverTurret()
void Terraria.Projectile.AI_197_CeilingAndHoverTurret () inline private
Definition at line 40672 of file Projectile.cs.
        {
            bool flag = this.type == 1025;
            if (this.localAI[1] == 0f)
            {
                this.localAI[1] = 1f;
                if (flag)
                {
                    this.frame = 3;
                    int num = 10;
                    for (int i = 0; i < 40; i++)
                    {
                        int num2 = Dust.NewDust(base.Center - new Vector2((float)num, (float)num), num * 2, num * 2, 2, 0f, 0f, 0, default(Color), 1f);
                        Main.dust[num2].alpha = 100;
                        Main.dust[num2].velocity *= 2f;
                        Main.dust[num2].noGravity = true;
                    }
                }
            }
            int num3 = 15;
            int num4 = 50;
            short num5 = 1026;
            int num6 = this.damage;
            float num7 = 12f;
            bool flag2 = false;
            Vector2 vector = this.velocity + new Vector2(0f, -2f);
            bool flag3 = Collision.SolidCollision(this.position + vector, this.width, this.height);
            Point point = base.Top.ToTileCoordinates();
            for (int j = 0; j < num3; j++)
            {
                Point point2 = new Point(point.X, point.Y + j);
                if (!WorldGen.InWorld(point2.X, point2.Y, 2))
                {
                    break;
                }
                Tile tile = Main.tile[point2.X, point2.Y];
                if (tile == null || WorldGen.SolidOrSlopedTile(tile))
                {
                    flag2 = true;
                    break;
                }
            }
            if (Main.myPlayer == this.owner && this.ai[0] == 1f && !flag3)
            {
                this.ai[0] = 0f;
                this.netUpdate = true;
            }
            if (flag)
            {
                if (this.ai[0] == 1f)
                {
                    if (this.frame < 0 || this.frame >= 3)
                    {
                        this.frame = Main.rand.Next(3);
                    }
                }
                else
                {
                    this.frame = 3;
                }
            }
            if (flag2)
            {
                if (this.ai[0] == 1f)
                {
                    this.velocity = Vector2.Zero;
                }
                else
                {
                    this.velocity.Y = this.velocity.Y - 0.1f;
                    if (this.velocity.Y < -12f)
                    {
                        this.velocity.Y = -12f;
                    }
                }
            }
            else
            {
                this.velocity *= 0.9f;
                if (this.velocity.Length() < 0.01f)
                {
                    this.velocity = Vector2.Zero;
                }
            }
            if (Main.myPlayer == this.owner)
            {
                int num8 = -1;
                float num9 = -1f;
                float num10 = -1f;
                Vector2 vector2 = new Vector2(0f, 10f);
                bool flag4 = false;
                int num11 = 1000;
                if (flag)
                {
                    num11 += num3 * 16;
                }
                bool flag5 = this.AI_053_HandleSentryNPCTargeting(vector2, flag4, out num8, out num9, out num10, (float)num11);
                this.localAI[0] += 1f;
                if (this.localAI[0] >= (float)num4)
                {
                    if (!flag5)
                    {
                        this.localAI[0] = (float)num4;
                        return;
                    }
                    this.localAI[0] = 0f;
                    Entity entity = Main.npc[num8];
                    Vector2 vector3 = base.Center + vector2;
                    Vector2 vector4 = (entity.Center - vector3).SafeNormalize(Vector2.Zero) * num7;
                    Projectile.NewProjectile(this.GetProjectileSource_FromThis(), vector3.X, vector3.Y, vector4.X, vector4.Y, (int)num5, num6, this.knockBack, this.owner, 0f, 0f, 0f, null);
                }
            }
        }
References Terraria.Dust.alpha, Terraria.Main.dust, int, Terraria.WorldGen.InWorld(), Terraria.Main.myPlayer, Terraria.Dust.NewDust(), Terraria.Projectile.NewProjectile(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Terraria.Main.npc, Terraria.Main.rand, Terraria.Collision.SolidCollision(), Terraria.WorldGen.SolidOrSlopedTile(), Terraria.Main.tile, Terraria.Dust.velocity, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Point.Y, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.