Terraria Decompiled: Terraria.Projectile.AI_200_BirdDroppings
AI_200_BirdDroppings()
void Terraria.Projectile.AI_200_BirdDroppings () inline private
Definition at line 40324 of file Projectile.cs.
        {
            this.velocity.Y = this.velocity.Y + 0.3f;
            if (this.velocity.Y > 16f)
            {
                this.velocity.Y = 16f;
            }
            for (int i = 0; i < 2; i++)
            {
                int num = Dust.NewDust(base.Center, 1, 1, 329, 0f, 0f, 0, default(Color), 1f);
                Main.dust[num].velocity *= 0.1f;
                if (Main.rand.Next(2) == 0)
                {
                    Main.dust[num].scale = Main.rand.NextFloat() * 0.5f + 0.5f;
                    Main.dust[num].velocity += this.velocity;
                    Main.dust[num].noGravity = true;
                }
                else
                {
                    Main.dust[num].scale = Main.rand.NextFloat() * 0.4f + 0.4f;
                    Main.dust[num].velocity *= 0.5f;
                    Main.dust[num].velocity += this.velocity / 2f;
                }
            }
            Rectangle rectangle = new Rectangle((int)this.position.X, (int)this.position.Y, this.width, this.height);
            for (int j = 0; j < 255; j++)
            {
                if (Main.player[j].active && !Main.player[j].dead)
                {
                    Rectangle rectangle2 = new Rectangle((int)Main.player[j].position.X, (int)Main.player[j].position.Y, Main.player[j].width, Main.player[j].height);
                    if (rectangle.Intersects(rectangle2))
                    {
                        this.Kill();
                    }
                }
            }
        }
References Terraria.Player.active, Terraria.Player.dead, Terraria.Main.dust, Terraria.Entity.height, Microsoft.Xna.Framework.Rectangle.Intersects(), Terraria.Dust.NewDust(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Terraria.Main.player, Terraria.Entity.position, Terraria.Main.rand, Terraria.Dust.scale, Terraria.Dust.velocity, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.