Terraria Decompiled: Terraria.Projectile.AI_015_HandleMovementCollision_Old
AI_015_HandleMovementCollision_Old()
void Terraria.Projectile.AI_015_HandleMovementCollision_Old (ref Vector2 wetVelocity, ref Vector2 lastVelocity) inline private
Definition at line 44334 of file Projectile.cs.
        {
            bool flag = false;
            if (lastVelocity.X != this.velocity.X)
            {
                if (Math.Abs(lastVelocity.X) > 4f)
                {
                    flag = true;
                }
                this.position.X = this.position.X + this.velocity.X;
                this.velocity.X = -lastVelocity.X * 0.2f;
            }
            if (lastVelocity.Y != this.velocity.Y)
            {
                if (Math.Abs(lastVelocity.Y) > 4f)
                {
                    flag = true;
                }
                this.position.Y = this.position.Y + this.velocity.Y;
                this.velocity.Y = -lastVelocity.Y * 0.2f;
            }
            this.ai[0] = 1f;
            if (flag)
            {
                this.netUpdate = true;
                Collision.HitTiles(this.position, this.velocity, this.width, this.height);
                SoundEngine.PlaySound(0, (int)this.position.X, (int)this.position.Y, 1, 1f, 0f);
            }
            if (this.wet)
            {
                wetVelocity = this.velocity;
            }
        }
References System.Math.Abs(), Terraria.Collision.HitTiles(), and Terraria.Audio.SoundEngine.PlaySound().