Terraria Decompiled: Terraria.Projectile.SpawnFakeFishInWater
SpawnFakeFishInWater()
void Terraria.Projectile.SpawnFakeFishInWater (int x, int y) inline private
Definition at line 19170 of file Projectile.cs.
        {
            int num;
            int num2;
            Projectile.GetFishingPondWidth(x, y, out num, out num2);
            int num3 = 10;
            num = Math.Max(x - num3, num);
            num2 = Math.Min(x + num3, num2);
            int num4 = 1;
            int num5 = 1;
            int num6 = 10;
            int num7 = 3;
            num += num4;
            num2 -= num4;
            Projectile._availableFishTypesToShow.Clear();
            Main.FishDropsDB.GetDisplayableDrops(Projectile._context, Projectile._availableFishTypesToShow);
            if (Projectile._availableFishTypesToShow.Count == 0)
            {
                return;
            }
            float num8 = 0f;
            foreach (FishPossibilityEntry fishPossibilityEntry in Projectile._availableFishTypesToShow)
            {
                num8 += fishPossibilityEntry.Frequency;
            }
            for (int i = num; i <= num2; i++)
            {
                int num9 = y;
                int num10 = 0;
                while (Main.tile[i, num9] != null && Main.tile[i, num9].liquid > 0 && !WorldGen.SolidTile(i, num9, false) && num9 < Main.maxTilesY - 10 && num10 < num6)
                {
                    num10++;
                    num9++;
                }
                if (num10 >= num7)
                {
                    if (Main.rand.Next(5) == 0)
                    {
                        Vector2 vector = new Vector2((float)(i * 16 + Main.rand.Next(4, 13)), (float)(y * 16 + Main.rand.Next(num5 * 16 + 4, num10 * 16 + 16 - num5 * 16 - 4 + 1)));
                        float num11 = (float)(y * 16) - vector.Y;
                        num11 *= Main.rand.NextFloat();
                        ParticleOrchestrator.RequestParticleSpawn(true, ParticleOrchestraType.LakeSparkle, new ParticleOrchestraSettings
{
                            PositionInWorld = vector,
                            MovementVector = new Vector2(0f, num11)
                        }, null);
                    }
                    if (Main.rand.Next(10) == 0)
                    {
                        Vector2 vector2 = new Vector2((float)(i * 16 + Main.rand.Next(4, 13)), (float)(y * 16 + Main.rand.Next(num5 * 16 + 4, num10 * 16 + 16 - num5 * 16 - 4 + 1)));
                        Vector2 vector3 = new Point(x, y).ToWorldCoordinates(8f, 8f);
                        float num12 = num8 * Main.rand.NextFloat();
                        int num13 = Projectile._availableFishTypesToShow[0].ItemType;
                        foreach (FishPossibilityEntry fishPossibilityEntry2 in Projectile._availableFishTypesToShow)
{
                            num13 = fishPossibilityEntry2.ItemType;
                            num12 -= fishPossibilityEntry2.Frequency;
                            if (num12 <= 0f)
{
                                break;
                            }
                        }
                        bool flag = Main.rand.Next(4) == 0;
                        ParticleOrchestraType particleOrchestraType = ParticleOrchestraType.FakeFish;
                        Vector2 vector4 = vector3;
                        if (flag)
{
                            int num14 = Main.rand.Next(num, num2 + 1);
                            int num15 = Main.rand.Next(num, num2 + 1);
                            int num16 = (num14 + num15) / 2;
                            int num17 = Math.Min(num14, num15);
                            int num18 = Math.Abs(num14 - num15);
                            int num19 = 6;
                            int num20 = 0;
                            Rectangle rectangle = new Rectangle(num17 * 16 + 2, y * 16 - 2, num18 * 16 - 4, 12);
                            int num21 = 0;
                            while (num21 < num19 && !Collision.SolidTiles(rectangle.TopLeft(), rectangle.Width, rectangle.Height))
{
                                num21++;
                                rectangle.Y -= 16;
                                num20++;
                            }
                            int num22 = 3;
                            if (num20 >= num22)
{
                                particleOrchestraType = ParticleOrchestraType.FakeFishJump;
                                int num23 = Main.rand.Next(1, 4);
                                int num24 = num22 + num23;
                                int num25 = Main.rand.Next(16 * num24, (num23 + num20) * 16);
                                float num26 = 0.2f;
                                float jumpForce = Utils.GetJumpForce((float)num25, num26);
                                float num27 = Utils.GetJumpTimeToApex((float)num25, num26) * 2f;
                                vector4 = new Vector2((float)((num15 - num14) * 16) / num27, -jumpForce);
                                vector2 = new Vector2((float)(num14 * 16 + 4 + Main.rand.Next(9)), (float)((y + num23) * 16 + 4 + Main.rand.Next(9)));
                            }
                        }
                        ParticleOrchestrator.RequestParticleSpawn(true, particleOrchestraType, new ParticleOrchestraSettings
{
                            PositionInWorld = vector2,
                            UniqueInfoPiece = num13,
                            MovementVector = vector4
                        }, null);
                    }
                }
            }
        }
References Terraria.Projectile._availableFishTypesToShow, Terraria.Projectile._context, System.Math.Abs(), System.Collections.Generic.List< T >.Clear(), System.Collections.Generic.List< T >.Count, Terraria.Main.FishDropsDB, Terraria.GameContent.FishDropRules.FishPossibilityEntry.Frequency, Terraria.GameContent.FishDropRules.FishDropRuleList.GetDisplayableDrops(), Terraria.Projectile.GetFishingPondWidth(), Terraria.Utils.GetJumpForce(), Terraria.Utils.GetJumpTimeToApex(), Microsoft.Xna.Framework.Rectangle.Height, Terraria.GameContent.FishDropRules.FishPossibilityEntry.ItemType, Terraria.Tile.liquid, System.Math.Max(), Terraria.Main.maxTilesY, System.Math.Min(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, Terraria.GameContent.Drawing.ParticleOrchestrator.RequestParticleSpawn(), Terraria.WorldGen.SolidTile(), Terraria.Collision.SolidTiles(), Terraria.Main.tile, Microsoft.Xna.Framework.Rectangle.Width, and Microsoft.Xna.Framework.Vector2.Y.