Terraria Decompiled: Terraria.Projectile.AI_170_FairyGlowstick
AI_170_FairyGlowstick()
void Terraria.Projectile.AI_170_FairyGlowstick () inline private
Definition at line 45905 of file Projectile.cs.
        {
            Point point = base.Center.ToTileCoordinates();
            Vector2 vector = point.ToVector2();
            int num = 10;
            Vector2 vector2 = Vector2.Zero;
            int num2 = 0;
            float num3 = 3f;
            if (this.ai[1] == 1f)
            {
                SoundEngine.PlaySound(SoundID.Item28, this.position, 0f, 1f);
                this.rotation = 0f;
                this.velocity.X = 0f;
                this.ai[1] = 2f;
            }
            this.frameCounter++;
            if (this.frameCounter > 4)
            {
                this.frameCounter = 0;
                this.frame++;
                if (this.frame >= Main.projFrames[this.type])
                {
                    this.frame = 0;
                }
            }
            if (this.velocity.Length() > 1f && this.timeLeft % 10 == 0)
            {
                for (int i = point.X - num; i < point.X + num + 1; i++)
                {
                    for (int j = point.Y - num; j < point.Y + num + 1; j++)
                    {
                        if (WorldGen.SolidTile(i, j, false))
{
                            Vector2 vector3 = vector - new Vector2((float)i, (float)j);
                            Vector2 vector4 = vector3.SafeNormalize(Vector2.Zero) * Math.Max((float)num - vector3.Length(), 0f);
                            vector4 *= num3;
                            vector2 += vector4;
                            num2++;
                        }
                    }
                }
                if (num2 > 0)
                {
                    vector2 /= (float)num2;
                }
                if (vector2.Length() > 1f)
                {
                    this.velocity = vector2;
                }
            }
            this.velocity *= 0.95f;
            if (this.velocity != Vector2.Zero && this.velocity.Length() < 1f)
            {
                this.velocity = Vector2.Zero;
                this.netUpdate = true;
            }
        }
References Terraria.ID.SoundID.Item28, Microsoft.Xna.Framework.Vector2.Length(), System.Math.Max(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.projFrames, Terraria.WorldGen.SolidTile(), Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Point.Y, and Microsoft.Xna.Framework.Vector2.Zero.