Terraria Decompiled: Terraria.Projectile.SpawnWebs
SpawnWebs()
void Terraria.Projectile.SpawnWebs () inline private
Definition at line 71066 of file Projectile.cs.
        {
            int num = 6;
            int num2 = (int)(base.Center.X / 16f);
            int num3 = (int)(base.Center.Y / 16f);
            int num4 = num2 - num;
            int num5 = num2 + num;
            int num6 = num3 - num;
            int num7 = num3 + num;
            if (num4 < 1)
            {
                num4 = 1;
            }
            if (num5 > Main.maxTilesX - 1)
            {
                num5 = Main.maxTilesX - 1;
            }
            if (num6 < 1)
            {
                num6 = 1;
            }
            if (num7 > Main.maxTilesY - 1)
            {
                num7 = Main.maxTilesY - 1;
            }
            for (int i = num4; i < num5; i++)
            {
                for (int j = num6; j < num7; j++)
                {
                    if (!Main.tile[i, j].active() && Main.rand.Next(5) != 0 && Math.Abs(i - num2) * Math.Abs(i - num2) + Math.Abs(j - num3) * Math.Abs(j - num3) < num * num)
                    {
                        WorldGen.PlaceTile(i, j, 51, false, false, -1, 0);
                        if (Main.tile[i, j].active() && Main.netMode == 2)
{
                            NetMessage.SendTileSquare(-1, i, j, TileChangeType.None);
                        }
                    }
                }
            }
        }
References System.Math.Abs(), Terraria.Tile.active(), int, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.PlaceTile(), Terraria.Main.rand, Terraria.NetMessage.SendTileSquare(), and Terraria.Main.tile.