Terraria Decompiled: Terraria.Projectile.GetConstellationColor
GetConstellationColor()
Color Terraria.Projectile.GetConstellationColor (float alphaChannelMultiplier = 1f, float lerpToWhite = 0f, float? rawHueOverride = null) inline
Definition at line 20397 of file Projectile.cs.
        {
            float num = this.ai[1];
            if (rawHueOverride != null)
            {
                num = rawHueOverride.Value;
            }
            float num2 = (num + 0.5f) % 1f;
            float num3 = 1f;
            float num4 = 0.5f;
            Color color = Main.hslToRgb(num2, num3, num4, byte.MaxValue);
            color *= this.Opacity;
            if (lerpToWhite != 0f)
            {
                color = Color.Lerp(color, Color.White, lerpToWhite);
            }
            color.A = (byte)((float)color.A * alphaChannelMultiplier);
            return color;
        }
References Terraria.Main.hslToRgb(), Microsoft.Xna.Framework.Color.Lerp(), and Microsoft.Xna.Framework.Color.White.
Referenced by Terraria.Main.DrawProjDirect().