Terraria Decompiled: Terraria.Projectile.RainbowBoulder_PerformSmartBounce
RainbowBoulder_PerformSmartBounce()
void Terraria.Projectile.RainbowBoulder_PerformSmartBounce () inline private
Definition at line 18787 of file Projectile.cs.
        {
            this.RainbowBoulder_PreventSpam();
            if (!this.active)
            {
                return;
            }
            this.RainbowBoulder_HighlightNearbyTreasure();
            Player player;
            Rectangle rectangle;
            Rectangle rectangle2;
            this.RainbowBoulder_GetAreas(out player, out rectangle, out rectangle2);
            float num = float.PositiveInfinity;
            float num2 = float.PositiveInfinity;
            NPC npc = null;
            NPC npc2 = null;
            for (int i = 0; i < Main.maxNPCs; i++)
            {
                NPC npc3 = Main.npc[i];
                if (npc3.CanBeChasedBy(this, false) && npc3.Hitbox.Intersects(rectangle))
                {
                    float num3 = player.Distance(npc3.Center);
                    if (num > num3)
                    {
                        num = num3;
                        npc = npc3;
                        if (!npc3.Hitbox.Intersects(rectangle2) && num2 > num3)
{
                            num2 = num3;
                            npc2 = npc3;
                        }
                    }
                }
            }
            if (npc != null || npc2 != null)
            {
                NPC npc4 = npc;
                this.RainbowBoulder_JumpToEnemy(npc4);
                return;
            }
            Rectangle rectangle3 = rectangle;
            rectangle3.X /= 16;
            rectangle3.Y /= 16;
            rectangle3.Width /= 16;
            rectangle3.Height /= 16;
            Point point;
            if (this.RainbowBoulder_GetTreasureCoords(rectangle3, out point))
            {
                this.RainbowBoulder_JumpToTreasure(point);
                return;
            }
            if (base.Distance(player.Center) < 3000f)
            {
                this.RainbowBoulder_JumpToPlayer(player);
                return;
            }
        }
References Terraria.NPC.CanBeChasedBy(), Terraria.Entity.Center, Terraria.Entity.Distance(), Terraria.Entity.Hitbox, Microsoft.Xna.Framework.Rectangle.Intersects(), Terraria.Main.maxNPCs, and Terraria.Main.npc.