Terraria Decompiled: Terraria.Projectile.AI_061_FishingBobber_DoASplash
AI_061_FishingBobber_DoASplash()
void Terraria.Projectile.AI_061_FishingBobber_DoASplash () inline private
Definition at line 54303 of file Projectile.cs.
        {
            for (int i = 0; i < 100; i++)
            {
                int num = Dust.NewDust(new Vector2(this.position.X - 6f, this.position.Y - 10f), this.width + 12, 24, Dust.dustWater(), 0f, 0f, 0, default(Color), 1f);
                Dust dust = Main.dust[num];
                dust.velocity.Y = dust.velocity.Y - 4f;
                Dust dust2 = Main.dust[num];
                dust2.velocity.X = dust2.velocity.X * 2.5f;
                Main.dust[num].scale = 0.8f;
                Main.dust[num].alpha = 100;
                Main.dust[num].noGravity = true;
            }
            SoundEngine.PlaySound(19, (int)this.position.X, (int)this.position.Y, 0, 1f, 0f);
        }
References Terraria.Dust.alpha, Terraria.Main.dust, Terraria.Dust.dustWater(), Terraria.Dust.NewDust(), Terraria.Dust.noGravity, Terraria.Audio.SoundEngine.PlaySound(), and Terraria.Dust.scale.