Terraria Decompiled: Terraria.Projectile.AI_158_GetHomeLocation
AI_158_GetHomeLocation()
static Vector2 Terraria.Projectile.AI_158_GetHomeLocation (Player master, int stackedIndex) inline static
Definition at line 49444 of file Projectile.cs.
        {
            int num = master.bodyFrame.Height;
            if (num == 0)
            {
                num = 1;
            }
            Vector2 vector = Main.OffsetsPlayerHeadgear[master.bodyFrame.Y / num];
            vector.Y -= 2f;
            if (master.mount.Active)
            {
                int num2 = master.mount.Type;
                switch (num2)
                {
                case 52:
                    vector.Y += 6f;
                    vector.X -= (float)(master.direction * 10);
                    break;
                case 53:
                    break;
                case 54:
                    master.ApplyHeadOffsetFromMount(ref vector);
                    vector.X -= (float)(master.direction * 14);
                    break;
                case 55:
                case 56:
                    master.ApplyHeadOffsetFromMount(ref vector);
                    vector += new Vector2(0f, -4f) * master.Directions;
                    break;
                default:
                    if (num2 == 61)
                    {
                        master.ApplyHeadOffsetFromMount(ref vector);
                        vector += new Vector2(2f, -4f) * master.Directions;
                    }
                    break;
                }
            }
            switch (stackedIndex % 6)
            {
            case 1:
                vector += new Vector2((float)(master.direction * 8), master.gravDir * -2f);
                break;
            case 2:
                vector += new Vector2((float)(master.direction * -10), master.gravDir * -2f);
                break;
            case 3:
            {
                Vector2 vector2 = vector;
                int direction = master.direction;
                vector = vector2 + new Vector2((float)0, master.gravDir * -10f);
                break;
            }
            case 4:
                vector += new Vector2((float)(master.direction * 10), master.gravDir * -10f);
                break;
            case 5:
                vector += new Vector2((float)(master.direction * -12), master.gravDir * -10f);
                break;
            }
            vector += new Vector2(0f, master.gravDir * -16f) * (float)(stackedIndex / 6);
            Vector2 vector3 = master.RotatedRelativePoint(master.MountedCenter, false, true);
            int direction2 = master.direction;
            return (vector3 + new Vector2((float)0, master.gravDir * -21f) + vector).Floor();
        }
References Terraria.Mount.Active, Terraria.Player.ApplyHeadOffsetFromMount(), Terraria.Player.bodyFrame, Terraria.Entity.direction, Terraria.Player.Directions, Terraria.Player.gravDir, Microsoft.Xna.Framework.Rectangle.Height, Terraria.Player.mount, Terraria.Player.MountedCenter, Terraria.Main.OffsetsPlayerHeadgear, Terraria.Player.RotatedRelativePoint(), and Terraria.Mount.Type.
Referenced by Terraria.Projectile.AI_158_BabyBird(), and Terraria.Main.SortBabyBirdProjectiles().