Terraria Decompiled: Terraria.Projectile.TryBuildFishingContext
TryBuildFishingContext()
bool Terraria.Projectile.TryBuildFishingContext (FishingContext context) inline private
Definition at line 19295 of file Projectile.cs.
        {
            if (Main.player[this.owner].wet && base.Center.Y < Main.player[this.owner].RotatedRelativePoint(Main.player[this.owner].MountedCenter, false, true).Y)
            {
                return false;
            }
            FishingAttempt fishingAttempt = default(FishingAttempt);
            fishingAttempt.X = (int)(base.Center.X / 16f);
            fishingAttempt.Y = (int)(base.Center.Y / 16f);
            fishingAttempt.bobberType = this.type;
            Projectile.GetFishingPondState(fishingAttempt.X, fishingAttempt.Y, out fishingAttempt.inLava, out fishingAttempt.inHoney, out fishingAttempt.waterTilesCount, out fishingAttempt.chumsInWater);
            if (Main.notTheBeesWorld && Main.rand.Next(2) == 0)
            {
                fishingAttempt.inHoney = false;
            }
            if (fishingAttempt.waterTilesCount < 75)
            {
                Main.player[this.owner].displayedFishingInfo = Language.GetTextValue("GameUI.NotEnoughWater");
                return false;
            }
            fishingAttempt.playerFishingConditions = Main.player[this.owner].GetFishingConditions();
            int baitItemType = fishingAttempt.playerFishingConditions.BaitItemType;
            if (baitItemType == 2673)
            {
                Main.player[this.owner].displayedFishingInfo = Language.GetTextValue("GameUI.FishingWarning");
                if ((fishingAttempt.X < 380 || fishingAttempt.X > Main.maxTilesX - 380) && fishingAttempt.waterTilesCount > 1000 && !NPC.AnyNPCs(370))
                {
                    this.ai[1] = (float)(Main.rand.Next(-180, -60) - 100);
                    this.localAI[1] = 1f;
                    this.localAI[2] = 2673f;
                    this.netUpdate = true;
                }
                return false;
            }
            fishingAttempt.fishingLevel = fishingAttempt.playerFishingConditions.FinalFishingLevel;
            if (fishingAttempt.fishingLevel == 0)
            {
                return false;
            }
            fishingAttempt.CanFishInLava = ItemID.Sets.CanFishInLava[fishingAttempt.playerFishingConditions.PoleItemType] || ItemID.Sets.IsLavaBait[fishingAttempt.playerFishingConditions.BaitItemType] || Main.player[this.owner].accLavaFishing;
            if (fishingAttempt.chumsInWater > 0)
            {
                fishingAttempt.fishingLevel += 11;
            }
            if (fishingAttempt.chumsInWater > 1)
            {
                fishingAttempt.fishingLevel += 6;
            }
            if (fishingAttempt.chumsInWater > 2)
            {
                fishingAttempt.fishingLevel += 3;
            }
            Main.player[this.owner].displayedFishingInfo = Language.GetTextValue("GameUI.FishingPower", fishingAttempt.fishingLevel);
            fishingAttempt.waterNeededToFish = 300;
            float num = (float)Main.maxTilesX / 4200f;
            num *= num;
            fishingAttempt.atmo = (float)((double)(this.position.Y / 16f - (60f + 10f * num)) / (Main.worldSurface / 6.0));
            if ((double)fishingAttempt.atmo < 0.25)
            {
                fishingAttempt.atmo = 0.25f;
            }
            if (fishingAttempt.atmo > 1f)
            {
                fishingAttempt.atmo = 1f;
            }
            fishingAttempt.waterNeededToFish = (int)((float)fishingAttempt.waterNeededToFish * fishingAttempt.atmo);
            fishingAttempt.waterQuality = (float)fishingAttempt.waterTilesCount / (float)fishingAttempt.waterNeededToFish;
            if (fishingAttempt.waterQuality < 1f)
            {
                fishingAttempt.fishingLevel = (int)((float)fishingAttempt.fishingLevel * fishingAttempt.waterQuality);
            }
            fishingAttempt.waterQuality = 1f - fishingAttempt.waterQuality;
            if (fishingAttempt.waterTilesCount < fishingAttempt.waterNeededToFish)
            {
                Main.player[this.owner].displayedFishingInfo = Language.GetTextValue("GameUI.FullFishingPower", fishingAttempt.fishingLevel, -Math.Round((double)(fishingAttempt.waterQuality * 100f)));
            }
            if (Main.player[this.owner].luck < 0f)
            {
                if (Main.rand.NextFloat() < -Main.player[this.owner].luck)
                {
                    fishingAttempt.fishingLevel = (int)((double)fishingAttempt.fishingLevel * (0.9 - (double)Main.rand.NextFloat() * 0.3));
                }
            }
            else if (Main.rand.NextFloat() < Main.player[this.owner].luck)
            {
                fishingAttempt.fishingLevel = (int)((double)fishingAttempt.fishingLevel * (1.1 + (double)Main.rand.NextFloat() * 0.3));
            }
            fishingAttempt.heightLevel = 0;
            if (Main.remixWorld)
            {
                if ((double)fishingAttempt.Y < Main.worldSurface * 0.5)
                {
                    fishingAttempt.heightLevel = 0;
                }
                else if ((double)fishingAttempt.Y < Main.worldSurface)
                {
                    fishingAttempt.heightLevel = 1;
                }
                else if ((double)fishingAttempt.Y < Main.rockLayer)
                {
                    fishingAttempt.heightLevel = 3;
                }
                else if (fishingAttempt.Y < Main.maxTilesY - 300)
                {
                    fishingAttempt.heightLevel = 2;
                }
                else
                {
                    fishingAttempt.heightLevel = 4;
                }
                if (fishingAttempt.heightLevel == 2 && Main.rand.Next(2) == 0)
                {
                    fishingAttempt.heightLevel = 1;
                }
            }
            else if ((double)fishingAttempt.Y < Main.worldSurface * 0.5)
            {
                fishingAttempt.heightLevel = 0;
            }
            else if ((double)fishingAttempt.Y < Main.worldSurface)
            {
                fishingAttempt.heightLevel = 1;
            }
            else if ((double)fishingAttempt.Y < Main.rockLayer)
            {
                fishingAttempt.heightLevel = 2;
            }
            else if (fishingAttempt.Y < Main.maxTilesY - 300)
            {
                fishingAttempt.heightLevel = 3;
            }
            else
            {
                fishingAttempt.heightLevel = 4;
            }
            fishingAttempt.junk = Main.rand.Next(50) > fishingAttempt.fishingLevel && Main.rand.Next(50) > fishingAttempt.fishingLevel && fishingAttempt.waterTilesCount < fishingAttempt.waterNeededToFish;
            this.FishingCheck_RollDropLevels(fishingAttempt.fishingLevel, out fishingAttempt.common, out fishingAttempt.uncommon, out fishingAttempt.rare, out fishingAttempt.veryrare, out fishingAttempt.legendary, out fishingAttempt.crate);
            this.FishingCheck_ProbeForQuestFish(ref fishingAttempt);
            this.PrepareFishingContext(context, fishingAttempt);
            return true;
        }
References Terraria.Player.accLavaFishing, Terraria.NPC.AnyNPCs(), Terraria.DataStructures.FishingAttempt.atmo, Terraria.DataStructures.PlayerFishingConditions.BaitItemType, Terraria.ID.ItemID.Sets.CanFishInLava, Terraria.DataStructures.FishingAttempt.chumsInWater, Terraria.DataStructures.FishingAttempt.common, Terraria.DataStructures.FishingAttempt.crate, Terraria.Player.displayedFishingInfo, Terraria.DataStructures.PlayerFishingConditions.FinalFishingLevel, Terraria.DataStructures.FishingAttempt.fishingLevel, Terraria.Player.GetFishingConditions(), Terraria.Projectile.GetFishingPondState(), Terraria.Localization.Language.GetTextValue(), Terraria.DataStructures.FishingAttempt.heightLevel, Terraria.DataStructures.FishingAttempt.inHoney, Terraria.DataStructures.FishingAttempt.inLava, int, Terraria.ID.ItemID.Sets.IsLavaBait, Terraria.DataStructures.FishingAttempt.legendary, Terraria.Player.luck, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Player.MountedCenter, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.notTheBeesWorld, Terraria.Main.player, Terraria.DataStructures.FishingAttempt.playerFishingConditions, Terraria.DataStructures.PlayerFishingConditions.PoleItemType, Terraria.Main.rand, Terraria.DataStructures.FishingAttempt.rare, Terraria.Main.remixWorld, Terraria.Main.rockLayer, Terraria.Player.RotatedRelativePoint(), System.Math.Round(), Terraria.DataStructures.FishingAttempt.uncommon, Terraria.DataStructures.FishingAttempt.veryrare, Terraria.DataStructures.FishingAttempt.waterNeededToFish, Terraria.DataStructures.FishingAttempt.waterQuality, Terraria.DataStructures.FishingAttempt.waterTilesCount, Terraria.Entity.wet, Terraria.Main.worldSurface, Terraria.DataStructures.FishingAttempt.X, Microsoft.Xna.Framework.Vector2.Y, and Terraria.DataStructures.FishingAttempt.Y.