Terraria Decompiled: Terraria.Projectile.GetFairyQueenWeaponsColorFull
GetFairyQueenWeaponsColorFull()
static Color Terraria.Projectile.GetFairyQueenWeaponsColorFull (int playerIndex, Vector2 center, float hueRaw, float alphaChannelMultiplier = 1f, float lerpToWhite = 0f, float Opacity = 1f, float luminance = 0::5f) inline static
Definition at line 20429 of file Projectile.cs.
        {
            float num = 1f;
            float num2 = (hueRaw + 0.5f) % 1f;
            if (playerIndex != -1)
            {
                Player player = Main.player[playerIndex];
                if (player.active)
                {
                    string name = player.name;
                    uint num3 = <PrivateImplementationDetails>.ComputeStringHash(name);
                    if (num3 <= 2639310093U)
                    {
                        if (num3 <= 1650374817U)
{
                            if (num3 <= 708199672U)
{
                                if (num3 <= 208328621U)
{
                                    if (num3 != 62183149U)
{
                                        if (num3 != 208328621U)
{
                                            goto IL_0FA2;
                                        }
                                        if (!(name == "Jopojelly"))
{
                                            goto IL_0FA2;
                                        }
                                    }
                                    else
{
                                        if (!(name == "ManaUser"))
{
                                            goto IL_0FA2;
                                        }
                                        num2 = MathHelper.Lerp(0.41f, 0.57f, Utils.Turn01ToCyclic010(num2));
                                        goto IL_0FA2;
                                    }
                                }
                                else if (num3 != 214021753U)
{
                                    if (num3 != 680803461U)
{
                                        if (num3 != 708199672U)
{
                                            goto IL_0FA2;
                                        }
                                        if (!(name == "Kazzymodus"))
{
                                            goto IL_0FA2;
                                        }
                                        num2 = 0.33f;
                                        float num4 = (float)Math.Cos((double)(hueRaw * 6.2831855f)) * 0.5f + 0.5f;
                                        luminance = MathHelper.Lerp(0.15f, 0.4f, num4);
                                        goto IL_0FA2;
                                    }
                                    else
{
                                        if (!(name == "Mid"))
{
                                            goto IL_0FA2;
                                        }
                                        num2 = 0f;
                                        float num5 = (float)Math.Cos((double)(hueRaw * 6.2831855f)) * 0.5f + 0.5f;
                                        luminance = MathHelper.Lerp(0f, 0.9f, num5);
                                        goto IL_0FA2;
                                    }
                                }
                                else
{
                                    if (!(name == "Yoraiz0r"))
{
                                        goto IL_0FA2;
                                    }
                                    num2 = MathHelper.Lerp(0.9f, 0.95f, Utils.Turn01ToCyclic010(num2));
                                    goto IL_0FA2;
                                }
                            }
                            else if (num3 <= 1139021827U)
{
                                if (num3 != 869206474U)
{
                                    if (num3 != 1139021827U)
{
                                        goto IL_0FA2;
                                    }
                                    if (!(name == "Jaxrud"))
{
                                        goto IL_0FA2;
                                    }
                                    num2 = MathHelper.Lerp(0.18055555f, 0.43611112f, Utils.Turn01ToCyclic010(num2));
                                    goto IL_0FA2;
                                }
                                else
{
                                    if (!(name == "CheesyPaninie"))
{
                                        goto IL_0FA2;
                                    }
                                    num2 = MathHelper.Lerp(0.88f, 1.09f, Utils.Turn01ToCyclic010(num2));
                                    alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 0.5f, 0.5f);
                                    goto IL_0FA2;
                                }
                            }
                            else if (num3 != 1284017581U)
{
                                if (num3 != 1335914532U)
{
                                    if (num3 != 1650374817U)
{
                                        goto IL_0FA2;
                                    }
                                    if (!(name == "Aurora3500"))
{
                                        goto IL_0FA2;
                                    }
                                    num2 = MathHelper.Lerp(0.33f, 0.8f, Utils.Turn01ToCyclic010(num2));
                                    alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 0.5f, 0.5f);
                                    goto IL_0FA2;
                                }
                                else
{
                                    if (!(name == "Loki"))
{
                                        goto IL_0FA2;
                                    }
                                    num2 = 0f;
                                    float num6 = (float)Math.Cos((double)(hueRaw * 6.2831855f)) * 0.5f + 0.5f;
                                    luminance = MathHelper.Lerp(0f, 0.25f, num6);
                                    goto IL_0FA2;
                                }
                            }
                            else
{
                                if (!(name == "ppowersteef"))
{
                                    goto IL_0FA2;
                                }
                                num2 = MathHelper.Lerp(0f, 0.15f, Utils.Turn01ToCyclic010(num2));
                                alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 0.6f, 0.5f);
                                goto IL_0FA2;
                            }
                        }
                        else if (num3 <= 1923781348U)
{
                            if (num3 <= 1752923523U)
{
                                if (num3 != 1747396969U)
{
                                    if (num3 != 1752923523U)
{
                                        goto IL_0FA2;
                                    }
                                    if (!(name == "Darthkitten"))
{
                                        goto IL_0FA2;
                                    }
                                    num2 = 1f;
                                    float num7 = (float)Math.Cos((double)(hueRaw * 6.2831855f)) * 0.5f + 0.5f;
                                    luminance = MathHelper.Lerp(1f, 0.4f, num7);
                                    goto IL_0FA2;
                                }
                                else
{
                                    if (!(name == "Leinfors"))
{
                                        goto IL_0FA2;
                                    }
                                    num2 = MathHelper.Lerp(0.7f, 0.77f, Utils.Turn01ToCyclic010(num2));
                                    goto IL_0FA2;
                                }
                            }
                            else if (num3 != 1773024879U)
{
                                if (num3 != 1863568037U)
{
                                    if (num3 != 1923781348U)
{
                                        goto IL_0FA2;
                                    }
                                    if (!(name == "Alchemystics"))
{
                                        goto IL_0FA2;
                                    }
                                    num2 = MathHelper.Lerp(0.74f, 0.96f, Utils.Turn01ToCyclic010(num2));
                                    luminance = 0.6f;
                                    alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 0.6f, 0.5f);
                                    goto IL_0FA2;
                                }
                                else
{
                                    if (!(name == "Antithesis"))
{
                                        goto IL_0FA2;
                                    }
                                    num2 = 0.51f;
                                    float num8 = (float)Math.Cos((double)(hueRaw * 6.2831855f)) * 0.5f + 0.5f;
                                    luminance = MathHelper.Lerp(0f, 0.5f, num8);
                                    goto IL_0FA2;
                                }
                            }
                            else
{
                                if (!(name == "Artyrian"))
{
                                    goto IL_0FA2;
                                }
                                float num9 = Utils.PingPongFrom01To010(num2);
                                num9 = MathHelper.SmoothStep(0f, 1f, num9);
                                num9 = MathHelper.SmoothStep(0f, 1f, num9);
                                Color color = Color.Lerp(new Color(1f, 0.31f, 0f), new Color(0.7f, 0f, 1f), num9);
                                if (lerpToWhite != 0f)
{
                                    color = Color.Lerp(color, Color.White, lerpToWhite);
                                }
                                color.A = (byte)((float)color.A * alphaChannelMultiplier);
                                return color;
                            }
                        }
                        else if (num3 <= 2386938644U)
{
                            if (num3 != 2148467107U)
{
                                if (num3 != 2351718047U)
{
                                    if (num3 != 2386938644U)
{
                                        goto IL_0FA2;
                                    }
                                    if (!(name == "Sigma"))
{
                                        goto IL_0FA2;
                                    }
                                    num2 = MathHelper.Lerp(0f, 0.12f, Utils.Turn01ToCyclic010(num2));
                                    luminance = 0.5f;
                                    alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 0.6f, 0.5f);
                                    goto IL_0FA2;
                                }
                                else
{
                                    if (!(name == "Nimbus"))
{
                                        goto IL_0FA2;
                                    }
                                    num2 = MathHelper.Lerp(0.75f, 1f, Utils.Turn01ToCyclic010(num2));
                                    luminance = 1f;
                                    alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 0.5f, 0.8f);
                                    goto IL_0FA2;
                                }
                            }
                            else
{
                                if (!(name == "Ghostar"))
{
                                    goto IL_0FA2;
                                }
                                num2 = 0.66f;
                                float num10 = (float)Math.Cos((double)(hueRaw * 6.2831855f)) * 0.5f + 0.5f;
                                luminance = MathHelper.Lerp(0.15f, 0.85f, num10);
                                goto IL_0FA2;
                            }
                        }
                        else if (num3 != 2412408538U)
{
                            if (num3 != 2568166278U)
{
                                if (num3 != 2639310093U)
{
                                    goto IL_0FA2;
                                }
                                if (!(name == "jopojelly"))
{
                                    goto IL_0FA2;
                                }
                            }
                            else
{
                                if (!(name == "Khaios"))
{
                                    goto IL_0FA2;
                                }
                                num2 = 0.33f;
                                float num11 = (float)Math.Cos((double)(hueRaw * 6.2831855f)) * 0.5f + 0.5f;
                                luminance = MathHelper.Lerp(0f, 0.2f, num11);
                                goto IL_0FA2;
                            }
                        }
                        else
{
                            if (!(name == "Vulpes Inculta"))
{
                                goto IL_0FA2;
                            }
                            num2 = MathHelper.Lerp(0.65f, 0.75f, Utils.Turn01ToCyclic010(num2));
                            luminance = 0.5f;
                            alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 0.5f, 0.5f);
                            goto IL_0FA2;
                        }
                        Vector2 vector = player.Center - center;
                        float num12 = 10f;
                        float num13 = Utils.Turn01ToCyclic010(num2);
                        float num14 = MathHelper.Lerp(0.072f, 0.086f, num13);
                        float num15 = MathHelper.Lerp(0.47f, 0.55f, num13);
                        float num16 = MathHelper.Clamp(vector.X / num12, -1f, 1f) * 0.5f + 0.5f;
                        num2 = MathHelper.Lerp(num14, num15, num16);
                    }
                    else if (num3 <= 3428214922U)
                    {
                        if (num3 <= 3055308131U)
{
                            if (num3 <= 2734667832U)
{
                                if (num3 != 2716996079U)
{
                                    if (num3 == 2734667832U)
{
                                        if (name == "darthmorf")
{
                                            num2 = 0f;
                                            float num17 = (float)Math.Cos((double)(hueRaw * 6.2831855f)) * 0.5f + 0.5f;
                                            luminance = MathHelper.Lerp(0f, 0.2f, num17);
                                        }
                                    }
                                }
                                else if (name == "GreyL1me")
{
                                    num2 = 0.24f;
                                    float num18 = (float)Math.Cos((double)(hueRaw * 6.2831855f)) * 0.5f + 0.5f;
                                    luminance = MathHelper.Lerp(0.4f, 0.6f, num18);
                                    alphaChannelMultiplier = 0.3f;
                                }
                            }
                            else if (num3 != 2905540048U)
{
                                if (num3 != 3035519103U)
{
                                    if (num3 == 3055308131U)
{
                                        if (name == "Waze3174")
{
                                            num2 = MathHelper.Lerp(0.33f, 0f, Utils.Turn01ToCyclic010(num2));
                                            luminance = 0.3f;
                                            alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 0.6f, 0.5f);
                                        }
                                    }
                                }
                                else if (name == "RBrandon")
{
                                    num2 = 0.03f;
                                    luminance = 0.3f;
                                    alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 0.6f, 0.5f);
                                }
                            }
                            else if (name == "Criddle")
{
                                num2 = MathHelper.Lerp(0.05f, 0.15f, Utils.Turn01ToCyclic010(num2));
                                alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 0.5f, 0.5f);
                            }
                        }
                        else if (num3 <= 3198660749U)
{
                            if (num3 != 3094522306U)
{
                                if (num3 == 3198660749U)
{
                                    if (name == "Crowno")
{
                                        luminance = MathHelper.Lerp(0.25f, 0.4f, Utils.Turn01ToCyclic010(num2));
                                        num2 = MathHelper.Lerp(0.70555556f, 0.78333336f, Utils.Turn01ToCyclic010(num2));
                                        alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 0.5f, 0.5f);
                                    }
                                }
                            }
                            else if (name == "Bame")
{
                                float num19 = Utils.PingPongFrom01To010(num2);
                                num19 = MathHelper.SmoothStep(0f, 1f, num19);
                                num19 = MathHelper.SmoothStep(0f, 1f, num19);
                                Color color2 = Color.Lerp(Color.Yellow, new Color(0.4f, 0f, 0.75f), num19);
                                if (lerpToWhite != 0f)
{
                                    color2 = Color.Lerp(color2, Color.White, lerpToWhite);
                                }
                                color2.A = (byte)((float)color2.A * alphaChannelMultiplier);
                                return color2;
                            }
                        }
                        else if (num3 != 3229605002U)
{
                            if (num3 != 3276909722U)
{
                                if (num3 == 3428214922U)
{
                                    if (name == "Nike Leon")
{
                                        num2 = MathHelper.Lerp(0.04f, 0.1f, Utils.Turn01ToCyclic010(num2));
                                        alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 0.5f, 0.5f);
                                    }
                                }
                            }
                            else if (name == "Serenity")
{
                                num2 = 0.85f;
                                float num20 = (float)Math.Cos((double)(hueRaw * 6.2831855f)) * 0.5f + 0.5f;
                                luminance = MathHelper.Lerp(1f, 0.5f, num20);
                            }
                        }
                        else if (name == "Lazure")
{
                            num2 = MathHelper.Lerp(0.53333336f, 0.9222222f, Utils.Turn01ToCyclic010(num2));
                        }
                    }
                    else if (num3 <= 3966071759U)
                    {
                        if (num3 <= 3645672011U)
{
                            if (num3 != 3507409723U)
{
                                if (num3 == 3645672011U)
{
                                    if (name == "Xman101")
{
                                        num2 = 0.06f;
                                        float num21 = (float)Math.Cos((double)(hueRaw * 6.2831855f)) * 0.5f + 0.5f;
                                        luminance = MathHelper.Lerp(0f, 0.5f, num21);
                                    }
                                }
                            }
                            else if (name == "Cenx")
{
                                float num22 = Utils.PingPongFrom01To010(num2);
                                num22 = MathHelper.SmoothStep(0f, 1f, num22);
                                num22 = MathHelper.SmoothStep(0f, 1f, num22);
                                Color color3 = Color.Lerp(new Color(0.3f, 1f, 0.2f), Color.HotPink, num22);
                                if (lerpToWhite != 0f)
{
                                    color3 = Color.Lerp(color3, Color.White, lerpToWhite);
                                }
                                color3.A = (byte)((float)color3.A * alphaChannelMultiplier);
                                return color3;
                            }
                        }
                        else if (num3 != 3718845703U)
{
                            if (num3 != 3731670101U)
{
                                if (num3 == 3966071759U)
{
                                    if (name == "Unit One")
{
                                        float num23 = Utils.PingPongFrom01To010(num2);
                                        num23 = MathHelper.SmoothStep(0f, 1f, num23);
                                        Color color4 = Color.Lerp(Color.Yellow, Color.Blue, num23);
                                        if (lerpToWhite != 0f)
{
                                            color4 = Color.Lerp(color4, Color.White, lerpToWhite);
                                        }
                                        color4.A = (byte)((float)color4.A * alphaChannelMultiplier);
                                        return color4;
                                    }
                                }
                            }
                            else if (name == "Redigit")
{
                                num2 = 0.7f;
                            }
                        }
                        else if (name == "Zoomo")
{
                            num2 = 0.77f;
                            luminance = 0.5f;
                            alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 0.6f, 0.5f);
                        }
                    }
                    else if (num3 <= 4005152619U)
                    {
                        if (num3 != 3972042669U)
{
                            if (num3 != 3977692559U)
{
                                if (num3 == 4005152619U)
{
                                    if (name == "Doylee")
{
                                        num2 = MathHelper.Lerp(0.68f, 1f, Utils.Turn01ToCyclic010(num2));
                                        alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 0.6f, 0.5f);
                                    }
                                }
                            }
                            else if (name == "Discipile")
{
                                num2 = 0.53f;
                                float num24 = (float)Math.Cos((double)(hueRaw * 6.2831855f)) * 0.5f + 0.5f;
                                luminance = MathHelper.Lerp(0.05f, 0.5f, num24);
                            }
                        }
                        else if (name == "Grox The Great")
{
                            num2 = MathHelper.Lerp(0.31f, 0.5f, Utils.Turn01ToCyclic010(num2));
                            alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 1f, 0.8f);
                        }
                    }
                    else if (num3 != 4123588084U)
                    {
                        if (num3 != 4203845300U)
{
                            if (num3 == 4272415882U)
{
                                if (name == "Acamaeda")
{
                                    num2 = MathHelper.Lerp(0.06f, 0.28f, Utils.Turn01ToCyclic010(num2));
                                    alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 0.6f, 0.5f);
                                }
                            }
                        }
                        else if (name == "teiull")
{
                            num2 = MathHelper.Lerp(0.66f, 1f, Utils.Turn01ToCyclic010(num2));
                            luminance = 0.5f;
                        }
                    }
                    else if (name == "Jenosis")
                    {
                        num2 = MathHelper.Lerp(0.9f, 1.13f, Utils.Turn01ToCyclic010(num2)) % 1f;
                        alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 0.5f, 0.5f);
                    }
                }
            }
            IL_0FA2:
            Color color5 = Main.hslToRgb(num2, num, luminance, byte.MaxValue);
            color5 *= Opacity;
            if (lerpToWhite != 0f)
            {
                color5 = Color.Lerp(color5, Color.White, lerpToWhite);
            }
            color5.A = (byte)((float)color5.A * alphaChannelMultiplier);
            return color5;
        }
References Terraria.Player.active, Microsoft.Xna.Framework.Color.Blue, Microsoft.Xna.Framework.MathHelper.Clamp(), System.Math.Cos(), Microsoft.Xna.Framework.Color.HotPink, Terraria.Main.hslToRgb(), Microsoft.Xna.Framework.Color.Lerp(), Microsoft.Xna.Framework.MathHelper.Lerp(), System.name, Terraria.Player.name, Terraria.Utils.PingPongFrom01To010(), Terraria.Main.player, Microsoft.Xna.Framework.MathHelper.SmoothStep(), Terraria.Utils.Turn01ToCyclic010(), System.U, Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Color.Yellow.
Referenced by Terraria.Mount.DoFailedDismountDust(), Terraria.Mount.DoSpawnDust(), Terraria.Mount.Draw(), Terraria.Projectile.GetFairyQueenWeaponsColor(), Terraria.Mount.UpdateEffects(), and Terraria.Mount.UpdateFrame().