Terraria Decompiled: Terraria.Projectile.ApplyWhipDebuffs
ApplyWhipDebuffs()
void Terraria.Projectile.ApplyWhipDebuffs (NPC targetNPC) inline private
Definition at line 10855 of file Projectile.cs.
        {
            int num = this.type;
            if (num != 849)
            {
                switch (num)
                {
                case 912:
                    targetNPC.AddBuff(324, 240, false);
                    return;
                case 913:
                    targetNPC.AddBuff(323, 240, false);
                    return;
                case 914:
                    if (Main.rand.Next(5) == 0)
                    {
                        targetNPC.AddBuff(20, 180, false);
                        return;
                    }
                    break;
                default:
                    if (num != 1033)
                    {
                        return;
                    }
                    targetNPC.AddBuff(362, 240, false);
                    return;
                }
            }
            else
            {
                targetNPC.AddBuff(310, 240, false);
            }
        }
References Terraria.NPC.AddBuff(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, and Terraria.Projectile.type.
Referenced by Terraria.Projectile.StatusNPC().