Terraria Decompiled: Terraria.Projectile.SetFishingCheckResults
SetFishingCheckResults()
void Terraria.Projectile.SetFishingCheckResults (ref FishingAttempt fisher) inline private
Definition at line 19438 of file Projectile.cs.
        {
            this.FishingCheck_RollEnemySpawns(ref fisher);
            this.FishingCheck_RollItemDrop(ref fisher);
            bool flag = false;
            if (fisher.rolledItemDrop > 0)
            {
                if (Main.player[this.owner].sonarPotion)
                {
                    Item item = new Item();
                    item.SetDefaults(fisher.rolledItemDrop, null);
                    PopupText.AssignAsSonarText(PopupText.NewText(PopupTextContext.SonarAlert, item, base.Center, 1, true, false));
                    SoundEngine.PlaySound(SoundID.SonarPotion, this.position, 0f, 1f);
                }
                float num = (float)fisher.fishingLevel;
                this.ai[1] = (float)Main.rand.Next(-240, -90) - num;
                this.localAI[1] = (float)fisher.rolledItemDrop;
                this.localAI[2] = (float)fisher.playerFishingConditions.BaitItemType;
                this.netUpdate = true;
                flag = true;
            }
            if (fisher.rolledEnemySpawn > 0)
            {
                if (Main.player[this.owner].sonarPotion)
                {
                    PopupText.AssignAsSonarText(PopupText.NewText(PopupTextContext.SonarAlert, fisher.rolledEnemySpawn, base.Center, false));
                    SoundEngine.PlaySound(SoundID.SonarPotion, this.position, 0f, 1f);
                }
                float num2 = (float)fisher.fishingLevel;
                this.ai[1] = (float)Main.rand.Next(-240, -90) - num2;
                this.localAI[1] = (float)(-(float)fisher.rolledEnemySpawn);
                this.localAI[2] = (float)fisher.playerFishingConditions.BaitItemType;
                this.netUpdate = true;
                flag = true;
            }
            if (!flag && fisher.inLava)
            {
                int num3 = 0;
                if (ItemID.Sets.IsLavaBait[fisher.playerFishingConditions.BaitItemType])
                {
                    num3++;
                }
                if (ItemID.Sets.CanFishInLava[fisher.playerFishingConditions.PoleItemType])
                {
                    num3++;
                }
                if (Main.player[this.owner].accLavaFishing)
                {
                    num3++;
                }
                if (num3 >= 3)
                {
                    this.localAI[1] += 480f;
                }
                else if (num3 >= 2)
                {
                    this.localAI[1] += 240f;
                }
            }
            if (fisher.CanFishInLava && fisher.inLava)
            {
                AchievementsHelper.HandleSpecialEvent(Main.player[this.owner], 19);
            }
        }
References Terraria.Player.accLavaFishing, Terraria.PopupText.AssignAsSonarText(), Terraria.ID.ItemID.Sets.CanFishInLava, Terraria.GameContent.Achievements.AchievementsHelper.HandleSpecialEvent(), Terraria.ID.ItemID.Sets.IsLavaBait, System.item, Terraria.PopupText.NewText(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.rand, Terraria.ID.SoundID.SonarPotion, and Terraria.Player.sonarPotion.