Terraria Decompiled: Terraria.Projectile.NewProjectile
NewProjectile() [2/2]
static int Terraria.Projectile.NewProjectile (IEntitySource spawnSource, Vector2 position, Vector2 velocity, int Type, int Damage, float KnockBack, int Owner = -1, float ai0 = 0f, float ai1 = 0f, float ai2 = 0f, NewProjectileModifier modifer = null) inline static
Definition at line 9924 of file Projectile.cs.
        {
            return Projectile.NewProjectile(spawnSource, position.X, position.Y, velocity.X, velocity.Y, Type, Damage, KnockBack, Owner, ai0, ai1, ai2, modifer);
        }
References Terraria.Projectile.Damage(), Terraria.Projectile.NewProjectile(), Terraria.Entity.position, Terraria.Entity.velocity, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.GameContent.PortalHelper.AddPortal(), Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.Projectile.AI_001(), Terraria.NPC.AI_001_Slimes(), Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_005_EaterOfSouls(), Terraria.NPC.AI_007_TownEntities(), Terraria.Projectile.AI_015_Flails(), Terraria.Projectile.AI_015_Flails_Old(), Terraria.Projectile.AI_019_Spears(), Terraria.Projectile.AI_019_Spears_Old(), Terraria.Projectile.AI_026(), Terraria.NPC.AI_026_Unicorns(), Terraria.NPC.AI_037_Destroyer(), Terraria.Projectile.AI_047_MagnetSphere_TryAttacking(), Terraria.Projectile.AI_062(), Terraria.Projectile.AI_067_FreakingPirates(), Terraria.Projectile.AI_067_TigerSpecialAttack(), Terraria.NPC.AI_069_DukeFishron(), Terraria.Projectile.AI_075(), Terraria.NPC.AI_084_LunaticCultist(), Terraria.Projectile.AI_099_1_Counterweights(), Terraria.Projectile.AI_099_2_Yoyos(), Terraria.Projectile.AI_100_Medusa(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_109_DarkMage(), Terraria.NPC.AI_110_Betsy(), Terraria.NPC.AI_111_DD2LightningBug(), Terraria.NPC.AI_117_BloodNautilus(), Terraria.NPC.AI_119_Dandelion(), Terraria.NPC.AI_120_HallowBoss(), Terraria.NPC.AI_121_QueenSlime(), Terraria.NPC.AI_123_Deerclops(), Terraria.NPC.AI_123_Deerclops_ShootRubbleUp(), Terraria.NPC.AI_123_Deerclops_TryMakingSpike(), Terraria.Projectile.AI_130_FlameBurstTower(), Terraria.Projectile.AI_134_Ballista(), Terraria.Projectile.AI_138_ExplosiveTrap(), Terraria.Projectile.AI_140_MonkStaffT1(), Terraria.Projectile.AI_142_MonkStaffT2And3(), Terraria.Projectile.AI_148_StarSpawner(), Terraria.Projectile.AI_165_Whip(), Terraria.Projectile.AI_197_CeilingAndHoverTurret(), Terraria.Projectile.AI_198_Flint(), Terraria.Projectile.AI_198_Flint_EmitSpikes(), Terraria.Player.ApplyNPCOnHitEffects(), Terraria.Player.ApplySetBonus_Stardust(), Terraria.Projectile.BetsySharpnel(), Terraria.Player.BloodButcherer_TryButchering(), Terraria.NPC.BloodNautilus_CallForHelp(), Terraria.Projectile.BoulderExplosion(), Terraria.Player.BuffHandle_SpawnPetIfNeeded(), Terraria.Mount.CastSuperCartLaser(), Terraria.WorldGen.Check2x2(), Terraria.NPC.checkDead(), Terraria.WorldGen.CheckSuper(), Terraria.Player.CommandForbiddenStorm(), Terraria.Player.Counterweight(), Terraria.Cinematics.DSTFilm.CreateChester(), Terraria.GameContent.Items.WhipTagEffect_Firecracker.CreateExplosion(), Terraria.Projectile.Damage_PVE_Inner(), Terraria.Projectile.Damage_PVP(), Terraria.Player.DashMovement(), Terraria.NPC.DoDeathEvents(), Terraria.Main.DrawWallOfStars(), Terraria.Player.DropTombstone(), Terraria.NPC.DropTombstoneTownNPC(), Terraria.Wiring.ExplodeMine(), Terraria.Projectile.GasTrapCheck(), Terraria.Wiring.GeyserTrap(), Terraria.Projectile.ghostHeal(), Terraria.Projectile.ghostHurt(), Terraria.Projectile.HandleMovement(), Terraria.NPC.HaveDryadDoStardewAnimation(), Terraria.NPC.HitEffect(), Terraria.Wiring.HitWireSingle(), Terraria.Player.HorsemansBlade_SpawnPumpkin(), Terraria.Player.Hurt(), Terraria.Player.ItemCheck_EmitHammushProjectiles(), Terraria.Player.ItemCheck_MeleeHitPVP(), Terraria.Player.ItemCheck_OwnerOnlyCode(), Terraria.Player.ItemCheck_Shoot(), Terraria.WorldGen.KillTile(), Terraria.Player.LaunchMinecartHook(), Terraria.WorldGen.LaunchRocket(), Terraria.WorldGen.LaunchRocketSmall(), Terraria.Projectile.NewProjectile(), Terraria.Player.OnHit(), Terraria.Player.ProcessHitAgainstNPC(), Terraria.Player.QuickGrapple(), Terraria.WorldGen.ShakeTree(), Terraria.WorldGen.ShootFromCannon(), Terraria.GameContent.Items.WhipTagEffect_DarkHarvest.SpawnBlackLightning(), Terraria.Projectile.SpawnConstellationStarsTowards(), Terraria.WorldGen.SpawnFallingBlockProjectile(), Terraria.WorldGen.SpawnFallingObjects(), Terraria.GameContent.Items.WhipTagEffect_ViolentDisplayOfFlower.SpawnFlowerExplosionOn(), Terraria.Player.SpawnHallucination(), Terraria.GameContent.Items.WhipTagEffect_Starcrash.SpawnMeteorWhipMeteorOn(), Terraria.Player.SpawnMinionOnCursor(), Terraria.Projectile.SpawnMoonLordWhipProc(), Terraria.NPC.SpawnPassiveShadowHands(), Terraria.NPC.SpawnStardustMark_StardustTower(), Terraria.NPC.SpawnStardustMark_StardustWorm(), Terraria.WorldGen.SpawnThingsFromPot(), Terraria.Player.SporeSac(), Terraria.Mount.StartAbilityCharge(), Terraria.NPC.StingerExplosion(), Terraria.Projectile.SummonMonkGhast(), Terraria.Projectile.SummonSuperStarSlash(), Terraria.Player.TentacleSpike_TrySpiking(), Terraria.Player.TileInteractionsUse(), Terraria.Player.TorchAttack(), Terraria.Player.TorchGodsFlavor(), Terraria.Player.TryPlacingAGolfBallNearANearbyTee(), Terraria.Player.TrySpawnDigtoiseAt(), Terraria.WorldGen.TrySpawnLightningBolt(), Terraria.Player.UpdateAbigailStatus(), Terraria.Player.UpdateBuffs(), Terraria.Player.UpdateStormTigerStatus(), Terraria.Mount.UseAbility(), Terraria.Projectile.vampireHeal(), Terraria.Player.VolatileGelatin(), and Terraria.Player.Volcano_TrySpawningVolcano().