Terraria Decompiled: Terraria.Projectile.ghostHurt
ghostHurt()
void Terraria.Projectile.ghostHurt (int dmg, Vector2 Position, Entity victim) inline
Definition at line 11150 of file Projectile.cs.
        {
            if (!this.magic || this.damage <= 0)
            {
                return;
            }
            int num = this.damage;
            if (dmg <= 1)
            {
                return;
            }
            int num2 = 1500;
            if (Main.player[Main.myPlayer].ghostDmg > (float)num2)
            {
                return;
            }
            Main.player[Main.myPlayer].ghostDmg += (float)num;
            int[] array = new int[Main.maxNPCs];
            int num3 = 0;
            new int[Main.maxNPCs];
            int num4 = 0;
            for (int i = 0; i < Main.maxNPCs; i++)
            {
                if (Main.npc[i].CanBeChasedBy(this, false))
                {
                    float num5 = Math.Abs(Main.npc[i].position.X + (float)(Main.npc[i].width / 2) - this.position.X + (float)(this.width / 2)) + Math.Abs(Main.npc[i].position.Y + (float)(Main.npc[i].height / 2) - this.position.Y + (float)(this.height / 2));
                    if (num5 < 800f)
                    {
                        if (Collision.CanHit(this.position, 1, 1, Main.npc[i].position, Main.npc[i].width, Main.npc[i].height) && num5 > 50f)
{
                            array[num4] = i;
                            num4++;
                        }
                        else if (num4 == 0)
{
                            array[num3] = i;
                            num3++;
                        }
                    }
                }
            }
            if (num3 == 0 && num4 == 0)
            {
                return;
            }
            int num6;
            if (num4 > 0)
            {
                num6 = array[Main.rand.Next(num4)];
            }
            else
            {
                num6 = array[Main.rand.Next(num3)];
            }
            float num7 = 4f;
            float num8 = (float)Main.rand.Next(-100, 101);
            float num9 = (float)Main.rand.Next(-100, 101);
            float num10 = (float)Math.Sqrt((double)(num8 * num8 + num9 * num9));
            num10 = num7 / num10;
            num8 *= num10;
            num9 *= num10;
            Projectile.NewProjectile(this.GetProjectileSource_OnHit(victim, 16), Position.X, Position.Y, num8, num9, 356, num, 0f, this.owner, (float)num6, 0f, 0f, null);
        }
References System.Math.Abs(), System.array, Terraria.NPC.CanBeChasedBy(), Terraria.Collision.CanHit(), Terraria.Projectile.damage, Terraria.Projectile.GetProjectileSource_OnHit(), Terraria.Player.ghostDmg, Terraria.Entity.height, Terraria.Projectile.magic, Terraria.Main.maxNPCs, Terraria.Main.myPlayer, Terraria.Projectile.NewProjectile(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.npc, Terraria.Projectile.owner, Terraria.Main.player, Terraria.Entity.position, Terraria.Main.rand, System.Math.Sqrt(), Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Projectile.Damage_PVE_Inner().