Terraria Decompiled: Terraria.Projectile.AI_156_BatOfLight
AI_156_BatOfLight()
void Terraria.Projectile.AI_156_BatOfLight () inline private
Definition at line 51826 of file Projectile.cs.
        {
            List<int> ai156_blacklistedTargets = Projectile._ai156_blacklistedTargets;
            Player player = Main.player[this.owner];
            bool flag = this.type == 755;
            bool flag2 = this.type == 946;
            if (flag)
            {
                if (player.dead)
                {
                    player.batsOfLight = false;
                }
                if (player.batsOfLight)
                {
                    this.timeLeft = 2;
                }
                DelegateMethods.v3_1 = this.AI_156_GetColor().ToVector3();
                Point point = base.Center.ToTileCoordinates();
                DelegateMethods.CastLightOpen(point.X, point.Y);
                int num = this.frameCounter + 1;
                this.frameCounter = num;
                if (num >= 6)
                {
                    this.frameCounter = 0;
                    num = this.frame + 1;
                    this.frame = num;
                    if (num >= Main.projFrames[this.type] - 1)
                    {
                        this.frame = 0;
                    }
                }
                int num2 = player.direction;
                if (this.velocity.X != 0f)
                {
                    num2 = Math.Sign(this.velocity.X);
                }
                this.spriteDirection = num2;
            }
            if (flag2)
            {
                if (player.dead)
                {
                    player.empressBlade = false;
                }
                if (player.empressBlade)
                {
                    this.timeLeft = 2;
                }
                DelegateMethods.v3_1 = this.AI_156_GetColor().ToVector3();
                Point point2 = base.Center.ToTileCoordinates();
                DelegateMethods.CastLightOpen(point2.X, point2.Y);
            }
            ai156_blacklistedTargets.Clear();
            this.AI_156_Think(ai156_blacklistedTargets);
        }
References Terraria.Projectile._ai156_blacklistedTargets, Terraria.Player.batsOfLight, Terraria.DelegateMethods.CastLightOpen(), System.Collections.Generic.List< T >.Clear(), Terraria.Player.dead, Terraria.Entity.direction, Terraria.Player.empressBlade, Terraria.Main.player, Terraria.Main.projFrames, System.Math.Sign(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.