Terraria Decompiled: Terraria.Projectile.KiteLogic
KiteLogic()
void Terraria.Projectile.KiteLogic (Vector2 anchorPoint, KiteFlyingInfo info) inline
Definition at line 48957 of file Projectile.cs.
        {
            Player player = Main.player[this.owner];
            bool flag = this.owner == 255;
            float num = 4f;
            float num2 = 500f;
            float num3 = num2 / 2f;
            if (this.owner == Main.myPlayer && this.extraUpdates == 0)
            {
                float num4 = this.ai[0];
                if (this.ai[0] == 0f)
                {
                    this.ai[0] = num3;
                }
                float num5 = this.ai[0];
                if (player.channel)
                {
                    num5 -= 5f;
                }
                if (player.controlUseItem && player.itemAnimation == 0)
                {
                    num5 += 5f;
                }
                this.ai[0] = MathHelper.Clamp(num5, num, num2);
                if (num4 != this.ai[0])
                {
                    this.netUpdate = true;
                }
            }
            if (this.localAI[2] == 0f)
            {
                this.localAI[2] = this.ai[0];
            }
            else if (this.localAI[2] != this.ai[0])
            {
                this.localAI[2] = this.ai[0];
                if (this.soundDelay == 0)
                {
                    this.soundDelay = 30;
                    Projectile.kiteSoundPitch = (this.localAI[2] - num) / (num2 - num) * -0.12f + 0.06f;
                    if (!flag)
                    {
                        SoundEngine.PlaySound(SoundID.Item192, player.position, 0f, 1f);
                    }
                }
            }
            if (this.soundDelay > 0)
            {
                this.soundDelay--;
            }
            if (this.numUpdates == 1)
            {
                this.extraUpdates = 0;
            }
            float cloudAlpha = info.CloudAlpha;
            float num6 = 0f;
            if (WorldGen.InAPlaceWithWind(this.position, this.width, this.height))
            {
                num6 = info.WindInWorld;
            }
            float num7 = this.localAI[0];
            bool flag2 = Math.Abs(num6) >= 0.2f;
            this.localAI[0] = Utils.Clamp<float>(this.localAI[0] - (float)flag2.ToDirectionInt(), 0f, 300f);
            float num8 = Utils.GetLerpValue(0.2f, 0.5f, Math.Abs(num6), true) * 0.5f;
            Vector2 vector = base.Center;
            Vector2 vector2 = new Vector2(num6, (float)Math.Sin((double)(info.GlobalTime + info.BobOffset)) + cloudAlpha * 5f) * 25f;
            if (cloudAlpha > 0f && Math.Abs(num6) >= cloudAlpha / 2f && vector2.Y > 0f)
            {
                vector2.Y *= 1f - Math.Abs(num6) * 2f;
            }
            vector += vector2;
            Vector2 vector3 = vector - base.Center;
            vector3 = vector3.SafeNormalize(Vector2.Zero) * (3f + cloudAlpha * 7f);
            if (num8 == 0f)
            {
                vector3 = Vector2.Zero;
            }
            if (this.extraUpdates > 0)
            {
                this.position -= this.velocity;
                return;
            }
            float num9 = base.Distance(vector);
            float lerpValue = Utils.GetLerpValue(5f, 10f, num9, true);
            float y = this.velocity.Y;
            if (num9 > 10f)
            {
                this.velocity = Vector2.Lerp(this.velocity, vector3, 0.075f * lerpValue);
            }
            this.velocity.Y = y;
            this.velocity.Y = this.velocity.Y - num8;
            this.velocity.Y = this.velocity.Y + (0.02f + num8 * 0.25f);
            this.velocity.Y = MathHelper.Clamp(this.velocity.Y, -2f, 2f);
            if (base.Center.Y + this.velocity.Y < vector.Y)
            {
                this.velocity.Y = MathHelper.Lerp(this.velocity.Y, this.velocity.Y + num8 + 0.01f, 0.75f);
            }
            if (Math.Abs(this.velocity.X) > 0.02f)
            {
                this.velocity.X = this.velocity.X * 0.98f;
            }
            float num10 = base.Distance(anchorPoint);
            float num11 = this.ai[0];
            bool flag3 = num10 > num11;
            bool flag4 = num10 > num11 - 2f;
            if (flag3)
            {
                Vector2 vector4 = base.DirectionTo(anchorPoint);
                float num12 = num10 - num11;
                Vector2 vector5 = vector4 * num12;
                if (info.CanReelThroughBlocks)
                {
                    base.Center += vector5;
                }
                else
                {
                    this.velocity += vector5;
                }
                bool flag5 = Vector2.Dot(vector4, Vector2.UnitY) < 0.8f || num8 > 0f;
                if (num8 == 0f && Math.Abs(this.velocity.X) < 0.05f)
                {
                    flag5 = false;
                }
                this.velocity.Y = this.velocity.Y + vector4.Y * 0.05f;
                if (flag5)
                {
                    this.velocity.Y = this.velocity.Y - 0.15f;
                }
                this.velocity.X = this.velocity.X + vector4.X * 0.2f;
                if (num11 == num && this.owner == Main.myPlayer)
                {
                    player.afkCounter = 0;
                    player.afkCounterForKiting = 0;
                    this.Kill();
                    return;
                }
            }
            this.timeLeft = 2;
            Vector2 vector6 = base.Center - anchorPoint;
            int num13 = ((vector6.X > 0f) ? 1 : (-1));
            if (Math.Abs(vector6.X) > Math.Abs(vector6.Y) / 2f)
            {
                player.ChangeDir(num13);
            }
            Vector2 vector7 = base.DirectionTo(anchorPoint).SafeNormalize(Vector2.Zero);
            bool flag6 = num8 == 0f && this.velocity.Y >= 0.02f && !flag4;
            if (flag6)
            {
                this.rotation *= 0.95f;
            }
            else
            {
                float num14 = (-vector7).ToRotation() + 0.7853982f;
                if (this.spriteDirection == -1)
                {
                    num14 -= 1.5707964f * (float)player.direction;
                }
                this.rotation = num14 + this.velocity.X * 0.05f;
            }
            this.localAI[1] = Utils.Clamp<float>(this.localAI[1] + (float)flag6.ToDirectionInt() * 0.005f, 0f, 1f);
            float num15 = this.velocity.Length();
            int num16 = this.type;
            if (num16 != 771)
            {
                switch (num16)
                {
                case 822:
                case 823:
                case 827:
                case 830:
                case 838:
                case 843:
                case 844:
                case 845:
                case 846:
                case 850:
                case 852:
                    goto IL_0726;
                case 824:
                case 839:
                case 840:
                case 853:
                    if (num8 < 0.15f)
                    {
                        this.frame = 0;
                        goto IL_07F5;
                    }
                    this.frameCounter++;
                    if ((float)this.frameCounter > (1f - num8) * 10f)
                    {
                        this.frameCounter = 0;
                        this.frame = Main.rand.Next(4);
                        goto IL_07F5;
                    }
                    goto IL_07F5;
                case 826:
                    this.frame = (int)this.ai[1];
                    goto IL_07F5;
                case 828:
                case 829:
                    if (num15 < 6f)
                    {
                        this.frame = 1;
                        goto IL_07F5;
                    }
                    this.frame = 0;
                    goto IL_07F5;
                }
                if (num15 < 3f)
                {
                    this.frame = 0;
                    goto IL_07F5;
                }
                if (num15 < 5f)
                {
                    this.frame = 1;
                    goto IL_07F5;
                }
                if (num15 < 7f)
                {
                    this.frame = 2;
                    goto IL_07F5;
                }
                this.frame = 3;
                goto IL_07F5;
            }
            IL_0726:
            this.frame = 0;
            IL_07F5:
            this.spriteDirection = player.direction;
        }
References System.Math.Abs(), Terraria.Player.ChangeDir(), Terraria.Player.channel, Microsoft.Xna.Framework.MathHelper.Clamp(), Terraria.Utils.Clamp(), Terraria.Player.controlUseItem, Terraria.Entity.direction, Microsoft.Xna.Framework.Vector2.Distance(), Microsoft.Xna.Framework.Vector2.Dot(), Terraria.Utils.GetLerpValue(), Terraria.WorldGen.InAPlaceWithWind(), System.info, int, Terraria.ID.SoundID.Item192, Terraria.Player.itemAnimation, Microsoft.Xna.Framework.MathHelper.Lerp(), Microsoft.Xna.Framework.Vector2.Lerp(), Terraria.Main.myPlayer, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Main.rand, System.Math.Sin(), Microsoft.Xna.Framework.Vector2.UnitY, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.LeashedEntities.LeashedKite.MoveKite().