Terraria Decompiled: Terraria.Projectile.Damage_EVP
Damage_EVP()
void Terraria.Projectile.Damage_EVP (Rectangle projRectangle) inline private
Definition at line 13696 of file Projectile.cs.
        {
            if (this.hostile && Main.myPlayer < 255 && this.damage > 0)
            {
                int num = ImmunityCooldownID.General;
                int num2 = this.type;
                if (num2 <= 462)
                {
                    if (num2 == 452 || num2 - 454 <= 1 || num2 == 462)
                    {
                        num = ImmunityCooldownID.BossNoCheese;
                    }
                }
                else if (num2 - 871 <= 3 || num2 == 919 || num2 - 923 <= 1)
                {
                    num = ImmunityCooldownID.BossNoCheese;
                }
                int myPlayer = Main.myPlayer;
                bool flag = Main.player[myPlayer].active && !Main.player[myPlayer].dead && (!Main.player[myPlayer].immune || num != ImmunityCooldownID.General);
                if (flag && this.type == 281)
                {
                    flag = this.ai[1] - 1f == (float)myPlayer;
                }
                if (Main.getGoodWorld && this.type == 281)
                {
                    flag = true;
                }
                if (this.type == 1073 && Main.player[myPlayer].npcTypeNoAggro[1])
                {
                    flag = false;
                }
                if (this.type == 1078 && Main.player[myPlayer].spaceGun)
                {
                    flag = false;
                }
                if (flag && this.Colliding(projRectangle, Main.player[myPlayer].getRect()))
                {
                    int num3 = this.direction;
                    if (Main.player[myPlayer].position.X + (float)(Main.player[myPlayer].width / 2) < this.position.X + (float)(this.width / 2))
                    {
                        num3 = -1;
                    }
                    else
                    {
                        num3 = 1;
                    }
                    if (!Main.player[myPlayer].CanParryAgainst(Main.player[myPlayer].Hitbox, base.Hitbox, this.velocity))
                    {
                        this.SpawnHitVisuals(Main.player[myPlayer]);
                        this.TryDoingOnHitEffects(Main.player[myPlayer]);
                        int num4 = Main.DamageVar((float)this.damage, -Main.player[this.owner].luck);
                        ItemID.BannerEffect bannerEffect;
                        if (Main.player[myPlayer].GetBannerBuffEffect(this.bannerIdToRespondTo, out bannerEffect))
{
                            num4 = (int)((float)num4 * bannerEffect.DamageReceived.Sample(Main.Difficulty));
                        }
                        if (Main.player[myPlayer].resistCold && this.coldDamage)
{
                            num4 = (int)((float)num4 * 0.7f);
                        }
                        if (!this.reflected)
{
                            num4 = (int)((float)num4 * this.hostileDamageScaling.Sample(Main.Difficulty));
                        }
                        int num5 = 2;
                        num4 *= num5;
                        if (Main.player[myPlayer].deadMansSweater && this.trap)
{
                            num4 = (int)((float)num4 * 0.5f);
                            num4 = Math.Min(num4, 300);
                        }
                        int num6 = num4;
                        if (this.type == 961)
{
                            if (this.penetrate == 1)
{
                                this.damage = 0;
                                this.penetrate = -1;
                            }
                            else
{
                                this.damage = (int)((double)this.damage * 0.7);
                            }
                        }
                        bool flag2 = this.IsDamageDodgeable();
                        int num7 = -1;
                        if (ProjectileID.Sets.IsAGravestone[this.type])
{
                            num7 = (int)this.ai[0];
                        }
                        if (Main.player[myPlayer].Hurt(PlayerDeathReason.ByProjectile(num7, this.whoAmI), num6, num3, false, false, false, num, flag2) > 0.0 && !Main.player[myPlayer].dead)
{
                            this.StatusPlayer(Main.player[myPlayer]);
                        }
                        if (this.trap)
{
                            Main.player[myPlayer].trapDebuffSource = true;
                            if (Main.player[myPlayer].dead)
{
                                AchievementsHelper.HandleSpecialEvent(Main.player[myPlayer], 4);
                            }
                        }
                    }
                    if (true)
                    {
                        if (this.type == 435 || this.type == 682)
{
                            this.penetrate--;
                        }
                        if (this.type == 436)
{
                            this.penetrate--;
                        }
                        if (this.type == 681)
{
                            this.timeLeft = 0;
                        }
                        if (this.type == 437)
{
                            this.penetrate--;
                        }
                    }
                }
            }
        }
References Terraria.Player.active, Terraria.ID.ImmunityCooldownID.BossNoCheese, Terraria.DataStructures.PlayerDeathReason.ByProjectile(), Terraria.Player.CanParryAgainst(), Terraria.ID.ItemID.BannerEffect.DamageReceived, Terraria.Main.DamageVar(), Terraria.Player.dead, Terraria.Player.deadMansSweater, Terraria.Main.Difficulty, Terraria.ID.ImmunityCooldownID.General, Terraria.Player.GetBannerBuffEffect(), Terraria.Main.getGoodWorld, Terraria.Player.getRect(), Terraria.GameContent.Achievements.AchievementsHelper.HandleSpecialEvent(), Terraria.Entity.Hitbox, Terraria.Player.Hurt(), Terraria.Player.immune, int, Terraria.ID.ProjectileID.Sets.IsAGravestone, Terraria.Player.luck, System.Math.Min(), Terraria.Main.myPlayer, Terraria.Player.npcTypeNoAggro, Terraria.Main.player, Terraria.Entity.position, Terraria.Player.resistCold, Terraria.Player.spaceGun, Terraria.Player.trapDebuffSource, Terraria.Entity.width, and Microsoft.Xna.Framework.Vector2.X.
Referenced by Terraria.Projectile.Damage().