Terraria Decompiled: Terraria.Projectile.ReduceRemainingChumsInPool
ReduceRemainingChumsInPool()
void Terraria.Projectile.ReduceRemainingChumsInPool () inline private
Definition at line 54000 of file Projectile.cs.
        {
            int num = (int)base.Center.X / 16;
            int num2 = (int)base.Center.Y / 16;
            List<Tuple<int, Point>> list = new List<Tuple<int, Point>>();
            List<int> list2 = new List<int>();
            for (int i = 0; i < 1000; i++)
            {
                Projectile projectile = Main.projectile[i];
                if (projectile.active && projectile.owner == Main.myPlayer && projectile.timeLeft > 60 && projectile.type == 820)
                {
                    list.Add(new Tuple<int, Point>(i, (projectile.Center + Vector2.UnitY * 16f).ToTileCoordinates()));
                }
            }
            if (list.Count == 0)
            {
                return;
            }
            int num3;
            int num4;
            Projectile.GetFishingPondWidth(num, num2, out num3, out num4);
            Point point = default(Point);
            for (int j = num3; j <= num4; j++)
            {
                point.X = j;
                int num5 = num2;
                while (Main.tile[j, num5].liquid > 0 && !WorldGen.SolidTile(j, num5, false) && num5 < Main.maxTilesY - 10)
                {
                    num5++;
                    point.Y = num5;
                    for (int k = list.Count - 1; k >= 0; k--)
                    {
                        if (list[k].Item2 == point)
{
                            list2.Add(list[k].Item1);
                            list.RemoveAt(k);
                        }
                    }
                    if (list.Count == 0)
                    {
                        break;
                    }
                }
                if (list.Count == 0)
                {
                    break;
                }
            }
            for (int l = 0; l < list2.Count; l++)
            {
                Projectile projectile2 = Main.projectile[list2[l]];
                projectile2.ai[0] += 1f;
                projectile2.netUpdate = true;
            }
        }
References Terraria.Projectile.active, System.Collections.Generic.List< T >.Add(), Terraria.Projectile.ai, Terraria.Entity.Center, System.Collections.Generic.List< T >.Count, Terraria.Projectile.GetFishingPondWidth(), int, Terraria.Tile.liquid, System.list, Terraria.Main.maxTilesY, Terraria.Main.myPlayer, Terraria.Projectile.owner, Terraria.Main.projectile, Terraria.WorldGen.SolidTile(), Terraria.Main.tile, Terraria.Projectile.timeLeft, Terraria.Projectile.type, and Microsoft.Xna.Framework.Vector2.UnitY.