Terraria Decompiled: Terraria.Projectile.AI_099_2_Yoyos
AI_099_2_Yoyos()
void Terraria.Projectile.AI_099_2_Yoyos () inline private
Definition at line 68532 of file Projectile.cs.
        {
            bool flag = false;
            for (int i = 0; i < this.whoAmI; i++)
            {
                if (Main.projectile[i].active && Main.projectile[i].owner == this.owner && Main.projectile[i].type == this.type && Main.projectile[i].ai[0] >= -1f)
                {
                    flag = true;
                }
            }
            if (this.owner == Main.myPlayer)
            {
                this.localAI[0] += 1f;
                if (flag)
                {
                    this.localAI[0] += (float)Main.rand.Next(10, 31) * 0.1f;
                }
                float num = this.localAI[0] / 60f;
                num /= (1f + Main.player[this.owner].meleeSpeed) / 2f;
                float num2 = ProjectileID.Sets.YoyosLifeTimeMultiplier[this.type];
                if (Main.player[Main.myPlayer].yoyoString && num2 > 0f)
                {
                    num2 *= 1.5f;
                }
                if (this.ai[0] <= -2f)
                {
                    num2 = -1f;
                }
                if (num2 != -1f && num > num2)
                {
                    if (this.owner == Main.myPlayer)
                    {
                        for (int j = 0; j < 1000; j++)
{
                            if (Main.projectile[j].active && Main.projectile[j].aiStyle == this.aiStyle && Main.projectile[j].ai[0] >= 0f && Main.projectile[j].owner == this.owner)
{
                                Main.projectile[j].ai[0] = -1f;
                                Main.projectile[j].netUpdate = true;
                            }
                        }
                    }
                    this.ai[0] = -1f;
                }
            }
            if (this.type == 603 && this.owner == Main.myPlayer && this.ai[0] != 3f)
            {
                this.localAI[1] += 1f;
                if (this.localAI[1] >= 6f)
                {
                    float num3 = 400f;
                    Vector2 vector = this.velocity;
                    Vector2 vector2;
                    do
                    {
                        vector2 = new Vector2((float)Main.rand.Next(-100, 101), (float)Main.rand.Next(-100, 101));
                    }
                    while (vector2 == Vector2.Zero);
                    vector2.Normalize();
                    vector2 *= (float)Main.rand.Next(10, 41) * 0.1f;
                    if (Main.rand.Next(3) == 0)
                    {
                        vector2 *= 2f;
                    }
                    vector *= 0.25f;
                    vector += vector2;
                    for (int k = 0; k < Main.maxNPCs; k++)
                    {
                        if (Main.npc[k].CanBeChasedBy(this, false))
{
                            float num4 = Main.npc[k].position.X + (float)(Main.npc[k].width / 2);
                            float num5 = Main.npc[k].position.Y + (float)(Main.npc[k].height / 2);
                            float num6 = Math.Abs(this.position.X + (float)(this.width / 2) - num4) + Math.Abs(this.position.Y + (float)(this.height / 2) - num5);
                            if (num6 < num3 && Collision.CanHit(this.position, this.width, this.height, Main.npc[k].position, Main.npc[k].width, Main.npc[k].height))
{
                                num3 = num6;
                                vector.X = num4;
                                vector.Y = num5;
                                vector -= base.Center;
                                vector = vector.SafeNormalize(Vector2.Zero);
                                vector *= 8f;
                            }
                        }
                    }
                    vector *= 0.8f;
                    Projectile.NewProjectile(this.GetProjectileSource_FromThis(), base.Center.X - vector.X, base.Center.Y - vector.Y, vector.X, vector.Y, 604, this.damage, this.knockBack, this.owner, 0f, 0f, 0f, null);
                    this.localAI[1] = 0f;
                }
            }
            bool flag2 = false;
            if ((this.type >= 556 && this.type <= 561) || this.type == 1079)
            {
                flag2 = true;
            }
            if (Main.player[this.owner].dead)
            {
                this.Kill();
                return;
            }
            if (!flag2 && !flag && this.ai[0] != -2f)
            {
                Main.player[this.owner].heldProj = this.whoAmI;
                Main.player[this.owner].SetDummyItemTime(2);
                if (base.Center.X > Main.player[this.owner].Center.X + 2f)
                {
                    Main.player[this.owner].ChangeDir(1);
                    this.direction = 1;
                }
                else if (base.Center.X < Main.player[this.owner].Center.X - 2f)
                {
                    Main.player[this.owner].ChangeDir(-1);
                    this.direction = -1;
                }
            }
            else
            {
                this.drawLayer = 0;
            }
            if (this.velocity.HasNaNs())
            {
                this.Kill();
            }
            this.timeLeft = 6;
            float num7 = ProjectileID.Sets.YoyosMaximumRange[this.type];
            float num8 = ProjectileID.Sets.YoyosTopSpeed[this.type];
            if (this.type == 545)
            {
                if (Main.rand.Next(6) == 0)
                {
                    int num9 = Dust.NewDust(this.position, this.width, this.height, 6, 0f, 0f, 0, default(Color), 1f);
                    Main.dust[num9].noGravity = true;
                }
            }
            else if (this.type == 553 && Main.rand.Next(2) == 0)
            {
                int num10 = Dust.NewDust(this.position, this.width, this.height, 6, 0f, 0f, 0, default(Color), 1f);
                Main.dust[num10].noGravity = true;
                Main.dust[num10].scale = 1.6f;
            }
            if (Main.player[this.owner].yoyoString)
            {
                num7 = num7 * 1.25f + 30f;
            }
            num7 /= (1f + Main.player[this.owner].meleeSpeed * 3f) / 4f;
            num8 /= (1f + Main.player[this.owner].meleeSpeed * 3f) / 4f;
            float num11 = 14f - num8 / 2f;
            if (num11 < 1f)
            {
                num11 = 1f;
            }
            float num12 = 5f + num8 / 2f;
            if (flag)
            {
                num12 += 20f;
            }
            if (this.ai[0] >= 0f)
            {
                if (this.velocity.Length() > num8)
                {
                    this.velocity *= 0.98f;
                }
                bool flag3 = false;
                bool flag4 = false;
                if (this.ai[0] != -2f)
                {
                    Vector2 vector3 = Main.player[this.owner].Center - base.Center;
                    if (vector3.Length() > num7)
                    {
                        flag3 = true;
                        if ((double)vector3.Length() > (double)num7 * 1.3)
{
                            flag4 = true;
                        }
                    }
                }
                if (this.owner == Main.myPlayer)
                {
                    if (!Main.player[this.owner].channel || Main.player[this.owner].stoned || Main.player[this.owner].frozen)
                    {
                        this.ai[0] = -1f;
                        this.ai[1] = 0f;
                        this.netUpdate = true;
                    }
                    else
                    {
                        Vector2 vector4 = Main.ReverseGravitySupport(Main.MouseScreen, 0f) + Main.screenPosition;
                        float num13 = vector4.X;
                        float num14 = vector4.Y;
                        Vector2 vector5 = new Vector2(num13, num14) - Main.player[this.owner].Center;
                        if (vector5.Length() > num7)
{
                            vector5.Normalize();
                            vector5 *= num7;
                            vector5 = Main.player[this.owner].Center + vector5;
                            num13 = vector5.X;
                            num14 = vector5.Y;
                        }
                        if (this.ai[0] != num13 || this.ai[1] != num14)
{
                            Vector2 vector6 = new Vector2(num13, num14) - Main.player[this.owner].Center;
                            if (vector6.Length() > num7 - 1f)
{
                                vector6.Normalize();
                                vector6 *= num7 - 1f;
                                Vector2 vector7 = Main.player[this.owner].Center + vector6;
                                num13 = vector7.X;
                                num14 = vector7.Y;
                            }
                            this.ai[0] = num13;
                            this.ai[1] = num14;
                            this.netUpdate = true;
                        }
                    }
                }
                if (flag4 && this.owner == Main.myPlayer)
                {
                    this.ai[0] = -1f;
                    this.netUpdate = true;
                }
                if (this.ai[0] >= 0f)
                {
                    if (flag3)
                    {
                        num11 /= 2f;
                        num8 *= 2f;
                        if (base.Center.X > Main.player[this.owner].Center.X && this.velocity.X > 0f)
{
                            this.velocity.X = this.velocity.X * 0.5f;
                        }
                        if (base.Center.Y > Main.player[this.owner].Center.Y && this.velocity.Y > 0f)
{
                            this.velocity.Y = this.velocity.Y * 0.5f;
                        }
                        if (base.Center.X < Main.player[this.owner].Center.X && this.velocity.X < 0f)
{
                            this.velocity.X = this.velocity.X * 0.5f;
                        }
                        if (base.Center.Y < Main.player[this.owner].Center.Y && this.velocity.Y < 0f)
{
                            this.velocity.Y = this.velocity.Y * 0.5f;
                        }
                    }
                    Vector2 vector8 = new Vector2(this.ai[0], this.ai[1]) - base.Center;
                    if (flag3)
                    {
                        num11 = 1f;
                    }
                    this.velocity.Length();
                    float num15 = vector8.Length();
                    if (num15 > num12)
                    {
                        vector8.Normalize();
                        float num16 = Math.Min(num15 / 2f, num8);
                        if (flag3)
{
                            num16 = Math.Min(num16, num8 / 2f);
                        }
                        vector8 *= num16;
                        this.velocity = (this.velocity * (num11 - 1f) + vector8) / num11;
                    }
                    else if (flag)
                    {
                        if ((double)this.velocity.Length() < (double)num8 * 0.6)
{
                            vector8 = this.velocity;
                            vector8 = vector8.SafeNormalize(Vector2.Zero);
                            vector8 *= num8 * 0.6f;
                            this.velocity = (this.velocity * (num11 - 1f) + vector8) / num11;
                        }
                    }
                    else
                    {
                        this.velocity *= 0.8f;
                    }
                    if (flag && !flag3 && (double)this.velocity.Length() < (double)num8 * 0.6)
                    {
                        this.velocity = this.velocity.SafeNormalize(Vector2.Zero);
                        this.velocity *= num8 * 0.6f;
                    }
                }
            }
            if (this.ai[0] == -1f && Main.player[this.owner].magicString)
            {
                this.ai[0] = -3f;
                if (Main.myPlayer == this.owner)
                {
                    this.netUpdate = true;
                    Projectile.NewProjectile(this.GetProjectileSource_FromThis(), base.Center, this.velocity, this.type, (int)((double)this.damage * 0.75), (float)((int)((double)this.knockBack * 0.75)), this.owner, -2f, 0f, 0f, null);
                }
            }
            if (this.ai[0] == -3f)
            {
                this.alpha = 255;
                this.damage = 0;
            }
            if (this.ai[0] == -2f)
            {
                if (this.penetrate < 0)
                {
                    this.penetrate = Main.rand.Next(3, 7);
                }
                this.velocity.Y = this.velocity.Y + 0.3f;
                if (this.velocity.Length() > 16f)
                {
                    this.velocity.Normalize();
                    this.velocity *= 16f;
                }
                else if (this.velocity.Y <= 3f)
                {
                    if (num8 > 16f)
                    {
                        num8 = 16f;
                    }
                    if ((double)Math.Abs(this.velocity.X) < 0.1)
                    {
                        if (base.Center.X < Main.player[this.owner].Center.X)
{
                            this.velocity.X = this.velocity.X - 0.1f;
                            this.direction = -1;
                        }
                        else
{
                            this.velocity.X = this.velocity.X + 0.1f;
                            this.direction = 1;
                        }
                    }
                    else if (this.velocity.X > 0f && this.velocity.X < num8)
                    {
                        this.velocity.X = this.velocity.X + 0.1f;
                    }
                    else if (this.velocity.X < 0f && this.velocity.X > -num8)
                    {
                        this.velocity.X = this.velocity.X - 0.1f;
                    }
                }
            }
            else if (this.ai[0] < 0f)
            {
                num11 = (float)((int)((double)num11 * 0.8));
                num8 *= 1.5f;
                this.tileCollide = false;
                Vector2 vector9 = Main.player[this.owner].Center - base.Center;
                float num17 = vector9.Length();
                if (num17 < num8 + 10f || num17 == 0f || num17 > 2000f)
                {
                    this.Kill();
                }
                else
                {
                    vector9.Normalize();
                    vector9 *= num8;
                    this.velocity = (this.velocity * (num11 - 1f) + vector9) / num11;
                }
            }
            if (this.ai[0] == -2f)
            {
                this.rotation += 0.45f * (float)this.direction;
            }
            else
            {
                this.rotation += 0.45f;
            }
            this.AI_AdjustPlayerItemRotationToFaceProjectile(-1, 0f);
        }
References System.Math.Abs(), Terraria.Projectile.active, Terraria.Projectile.ai, Terraria.Projectile.aiStyle, Terraria.NPC.CanBeChasedBy(), Terraria.Collision.CanHit(), Terraria.Entity.Center, Terraria.Player.ChangeDir(), Terraria.Player.channel, Terraria.Player.dead, Terraria.Main.dust, Terraria.Player.frozen, Terraria.Entity.height, Terraria.Player.heldProj, int, Microsoft.Xna.Framework.Vector2.Length(), Terraria.Player.magicString, Terraria.Main.maxNPCs, Terraria.Player.meleeSpeed, System.Math.Min(), Terraria.Main.MouseScreen, Terraria.Main.myPlayer, Terraria.Projectile.netUpdate, Terraria.Dust.NewDust(), Terraria.Projectile.NewProjectile(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Microsoft.Xna.Framework.Vector2.Normalize(), Terraria.Main.npc, Terraria.Projectile.owner, Terraria.Main.player, Terraria.Entity.position, Terraria.Main.projectile, Terraria.Main.rand, Terraria.Main.ReverseGravitySupport(), Terraria.Dust.scale, Terraria.Main.screenPosition, Terraria.Player.SetDummyItemTime(), Terraria.Player.stoned, Terraria.Projectile.type, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, Terraria.ID.ProjectileID.Sets.YoyosLifeTimeMultiplier, Terraria.ID.ProjectileID.Sets.YoyosMaximumRange, Terraria.ID.ProjectileID.Sets.YoyosTopSpeed, Terraria.Player.yoyoString, and Microsoft.Xna.Framework.Vector2.Zero.