Terraria Decompiled: Terraria.Projectile.AI_099_1_Counterweights
AI_099_1_Counterweights()
void Terraria.Projectile.AI_099_1_Counterweights () inline private
Definition at line 68180 of file Projectile.cs.
        {
            this.timeLeft = 6;
            bool flag = true;
            float num = 250f;
            float num2 = 0.1f;
            float num3 = 15f;
            float num4 = 12f;
            num *= 0.5f;
            num3 *= 0.8f;
            num4 *= 1.5f;
            float num5 = num3;
            if (this.owner == Main.myPlayer && this.ai[0] >= 0f)
            {
                bool flag2 = false;
                for (int i = 0; i < 1000; i++)
                {
                    if (Main.projectile[i].active && Main.projectile[i].owner == this.owner && Main.projectile[i].aiStyle == 99 && Main.projectile[i].ai[0] >= -1f && (Main.projectile[i].type < 556 || Main.projectile[i].type > 561) && Main.projectile[i].type != 1079)
                    {
                        flag2 = true;
                    }
                }
                if (!flag2)
                {
                    this.ai[0] = -1f;
                    this.netUpdate = true;
                }
            }
            if (Main.player[this.owner].yoyoString)
            {
                num += num * 0.25f + 10f;
            }
            this.rotation += 0.5f;
            if (Main.player[this.owner].dead)
            {
                this.Kill();
                return;
            }
            if (!flag)
            {
                Main.player[this.owner].heldProj = this.whoAmI;
                Main.player[this.owner].SetDummyItemTime(2);
                if (this.position.X + (float)(this.width / 2) > Main.player[this.owner].position.X + (float)(Main.player[this.owner].width / 2))
                {
                    Main.player[this.owner].ChangeDir(1);
                    this.direction = 1;
                }
                else
                {
                    Main.player[this.owner].ChangeDir(-1);
                    this.direction = -1;
                }
            }
            if (this.ai[0] == 0f || this.ai[0] == 1f)
            {
                if (this.ai[0] == 1f)
                {
                    num *= 0.75f;
                }
                num4 *= 0.5f;
                bool flag3 = false;
                Vector2 vector = Main.player[this.owner].Center - base.Center;
                if ((double)vector.Length() > (double)num * 0.9 && this.ai[0] != -2f)
                {
                    flag3 = true;
                }
                if (vector.Length() > num)
                {
                    float num6 = vector.Length() - num;
                    Vector2 vector2;
                    vector2.X = vector.Y;
                    vector2.Y = vector.X;
                    vector.Normalize();
                    vector *= num;
                    this.position = Main.player[this.owner].Center - vector;
                    this.position.X = this.position.X - (float)(this.width / 2);
                    this.position.Y = this.position.Y - (float)(this.height / 2);
                    float num7 = this.velocity.Length();
                    this.velocity = this.velocity.SafeNormalize(Vector2.Zero);
                    if (num6 > num7 - 1f)
                    {
                        num6 = num7 - 1f;
                    }
                    this.velocity *= num7 - num6;
                    num7 = this.velocity.Length();
                    Vector2 vector3 = new Vector2(base.Center.X, base.Center.Y);
                    Vector2 vector4 = new Vector2(Main.player[this.owner].Center.X, Main.player[this.owner].Center.Y);
                    if (vector3.Y < vector4.Y)
                    {
                        vector2.Y = Math.Abs(vector2.Y);
                    }
                    else if (vector3.Y > vector4.Y)
                    {
                        vector2.Y = -Math.Abs(vector2.Y);
                    }
                    if (vector3.X < vector4.X)
                    {
                        vector2.X = Math.Abs(vector2.X);
                    }
                    else if (vector3.X > vector4.X)
                    {
                        vector2.X = -Math.Abs(vector2.X);
                    }
                    vector2.Normalize();
                    vector2 *= this.velocity.Length();
                    new Vector2(vector2.X, vector2.Y);
                    if (Math.Abs(this.velocity.X) > Math.Abs(this.velocity.Y))
                    {
                        Vector2 vector5 = this.velocity;
                        vector5.Y += vector2.Y;
                        vector5 = vector5.SafeNormalize(Vector2.Zero);
                        vector5 *= this.velocity.Length();
                        if ((double)Math.Abs(vector2.X) < 0.1 || (double)Math.Abs(vector2.Y) < 0.1)
{
                            this.velocity = vector5;
                        }
                        else
{
                            this.velocity = (vector5 + this.velocity * 2f) / 3f;
                        }
                    }
                    else
                    {
                        Vector2 vector6 = this.velocity;
                        vector6.X += vector2.X;
                        vector6 = vector6.SafeNormalize(Vector2.Zero);
                        vector6 *= this.velocity.Length();
                        if ((double)Math.Abs(vector2.X) < 0.2 || (double)Math.Abs(vector2.Y) < 0.2)
{
                            this.velocity = vector6;
                        }
                        else
{
                            this.velocity = (vector6 + this.velocity * 2f) / 3f;
                        }
                    }
                }
                if (Main.myPlayer == this.owner)
                {
                    if (Main.player[this.owner].channel)
                    {
                        Vector2 vector7 = new Vector2((float)(Main.mouseX - Main.lastMouseX), (float)(Main.mouseY - Main.lastMouseY));
                        if (this.velocity.X != 0f || this.velocity.Y != 0f)
{
                            if (flag)
{
                                vector7 *= -1f;
                            }
                            if (flag3)
{
                                if (base.Center.X < Main.player[this.owner].Center.X && vector7.X < 0f)
{
                                    vector7.X = 0f;
                                }
                                if (base.Center.X > Main.player[this.owner].Center.X && vector7.X > 0f)
{
                                    vector7.X = 0f;
                                }
                                if (base.Center.Y < Main.player[this.owner].Center.Y && vector7.Y < 0f)
{
                                    vector7.Y = 0f;
                                }
                                if (base.Center.Y > Main.player[this.owner].Center.Y && vector7.Y > 0f)
{
                                    vector7.Y = 0f;
                                }
                            }
                            this.velocity += vector7 * num2;
                            this.netUpdate = true;
                        }
                    }
                    else
                    {
                        this.ai[0] = -1f;
                        this.netUpdate = true;
                    }
                }
                if (flag || this.type == 562 || this.type == 547 || this.type == 555 || this.type == 564 || this.type == 552 || this.type == 563 || this.type == 549 || this.type == 550 || this.type == 554 || this.type == 553 || this.type == 603 || this.type == 999)
                {
                    float num8 = 800f;
                    Vector2 vector8 = default(Vector2);
                    bool flag4 = false;
                    if (this.type == 549)
                    {
                        num8 = 200f;
                    }
                    if (this.type == 554)
                    {
                        num8 = 400f;
                    }
                    if (this.type == 553)
                    {
                        num8 = 250f;
                    }
                    if (this.type == 603)
                    {
                        num8 = 320f;
                    }
                    for (int j = 0; j < Main.maxNPCs; j++)
                    {
                        if (Main.npc[j].CanBeChasedBy(this, false))
{
                            float num9 = Main.npc[j].position.X + (float)(Main.npc[j].width / 2);
                            float num10 = Main.npc[j].position.Y + (float)(Main.npc[j].height / 2);
                            float num11 = Math.Abs(this.position.X + (float)(this.width / 2) - num9) + Math.Abs(this.position.Y + (float)(this.height / 2) - num10);
                            if (num11 < num8 && (this.type != 563 || num11 >= 200f) && Collision.CanHit(this.position, this.width, this.height, Main.npc[j].position, Main.npc[j].width, Main.npc[j].height) && (double)(Main.npc[j].Center - Main.player[this.owner].Center).Length() < (double)num * 0.9)
{
                                num8 = num11;
                                vector8.X = num9;
                                vector8.Y = num10;
                                flag4 = true;
                            }
                        }
                    }
                    if (flag4)
                    {
                        vector8 -= base.Center;
                        vector8 = vector8.SafeNormalize(Vector2.Zero);
                        if (this.type == 563)
{
                            vector8 *= 4f;
                            this.velocity = (this.velocity * 14f + vector8) / 15f;
                        }
                        else if (this.type == 553)
{
                            vector8 *= 5f;
                            this.velocity = (this.velocity * 12f + vector8) / 13f;
                        }
                        else if (this.type == 603)
{
                            vector8 *= 16f;
                            this.velocity = (this.velocity * 9f + vector8) / 10f;
                        }
                        else if (this.type == 554)
{
                            vector8 *= 8f;
                            this.velocity = (this.velocity * 6f + vector8) / 7f;
                        }
                        else
{
                            vector8 *= 6f;
                            this.velocity = (this.velocity * 7f + vector8) / 8f;
                        }
                    }
                }
                if (this.velocity.Length() > num3)
                {
                    this.velocity.Normalize();
                    this.velocity *= num3;
                }
                if (this.velocity.Length() < num4)
                {
                    this.velocity = this.velocity.SafeNormalize(Vector2.Zero);
                    this.velocity *= num4;
                }
            }
            if (this.ai[0] == -1f && Main.player[this.owner].magicString)
            {
                this.ai[0] = -3f;
                if (Main.myPlayer == this.owner)
                {
                    this.netUpdate = true;
                    Projectile.NewProjectile(this.GetProjectileSource_FromThis(), base.Center, this.velocity, this.type, (int)((double)this.damage * 0.75), (float)((int)((double)this.knockBack * 0.75)), this.owner, -2f, 0f, 0f, null);
                }
            }
            if (this.ai[0] == -3f)
            {
                this.alpha = 255;
                this.damage = 0;
            }
            if (this.ai[0] == -2f)
            {
                this.extraUpdates = 0;
                if (this.penetrate < 0)
                {
                    this.penetrate = 1;
                }
                this.velocity.Y = this.velocity.Y + 0.3f;
                if (this.velocity.Length() > 16f)
                {
                    this.velocity.Normalize();
                    this.velocity *= 16f;
                    return;
                }
                if (this.velocity.Y <= 3f)
                {
                    if (num5 > 16f)
                    {
                        num5 = 16f;
                    }
                    if ((double)Math.Abs(this.velocity.X) < 0.1)
                    {
                        if (base.Center.X < Main.player[this.owner].Center.X)
{
                            this.velocity.X = this.velocity.X - 0.1f;
                            this.direction = -1;
                            return;
                        }
                        this.velocity.X = this.velocity.X + 0.1f;
                        this.direction = 1;
                        return;
                    }
                    else
                    {
                        if (this.velocity.X > 0f && this.velocity.X < num5)
{
                            this.velocity.X = this.velocity.X + 0.1f;
                            return;
                        }
                        if (this.velocity.X < 0f && this.velocity.X > -num5)
{
                            this.velocity.X = this.velocity.X - 0.1f;
                            return;
                        }
                    }
                }
            }
            else if (this.ai[0] < 0f)
            {
                this.tileCollide = false;
                Vector2 vector9 = Main.player[this.owner].Center - base.Center;
                float num12 = vector9.Length();
                if (num12 < 40f || vector9.HasNaNs() || num12 > 2000f)
                {
                    this.Kill();
                    return;
                }
                float num13 = num3 * 1.5f;
                if (this.type == 546)
                {
                    num13 *= 1.5f;
                }
                if (this.type == 554)
                {
                    num13 *= 1.25f;
                }
                if (this.type == 555)
                {
                    num13 *= 1.35f;
                }
                if (this.type == 562)
                {
                    num13 *= 1.25f;
                }
                float num14 = 12f;
                vector9.Normalize();
                vector9 *= num13;
                this.velocity = (this.velocity * (num14 - 1f) + vector9) / num14;
            }
        }
References System.Math.Abs(), Terraria.Projectile.active, Terraria.Projectile.ai, Terraria.Projectile.aiStyle, Terraria.NPC.CanBeChasedBy(), Terraria.Collision.CanHit(), Terraria.Entity.Center, Terraria.Player.ChangeDir(), Terraria.Player.channel, Terraria.Player.dead, Terraria.Entity.height, Terraria.Player.heldProj, int, Terraria.Main.lastMouseX, Terraria.Main.lastMouseY, Microsoft.Xna.Framework.Vector2.Length(), Terraria.Player.magicString, Terraria.Main.maxNPCs, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Projectile.NewProjectile(), Microsoft.Xna.Framework.Vector2.Normalize(), Terraria.Main.npc, Terraria.Projectile.owner, Terraria.Main.player, Terraria.Entity.position, Terraria.Main.projectile, Terraria.Player.SetDummyItemTime(), Terraria.Projectile.type, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, Terraria.Player.yoyoString, and Microsoft.Xna.Framework.Vector2.Zero.