Terraria Decompiled: Terraria.Projectile.AI_015_Flails_Dust
AI_015_Flails_Dust()
void Terraria.Projectile.AI_015_Flails_Dust (bool doFastThrowDust) inline private
Definition at line 44569 of file Projectile.cs.
        {
            if (this.type == 25)
            {
                int num = 15;
                if (doFastThrowDust)
                {
                    num = 1;
                }
                if (Main.rand.Next(num) == 0)
                {
                    Dust.NewDust(this.position, this.width, this.height, 14, 0f, 0f, 150, default(Color), 1.3f);
                    return;
                }
            }
            else
            {
                if (this.type == 757)
                {
                    int num2 = 4;
                    if (this.velocity.Length() < 8f)
                    {
                        num2 = 10;
                    }
                    if (doFastThrowDust)
                    {
                        num2 /= 2;
                    }
                    for (int i = 0; i < 2; i++)
                    {
                        if (Main.rand.Next(num2) == 0)
{
                            Dust dust = Dust.NewDustDirect(this.position, this.width, this.height, 5, 0f, 0f, 0, default(Color), 0.8f);
                            dust.velocity += this.velocity / 4f;
                            dust.fadeIn = 1.3f;
                        }
                    }
                    num2 = 40;
                    if (doFastThrowDust)
                    {
                        num2 /= 2;
                    }
                    for (float num3 = 0f; num3 < 1f; num3 += 0.1f)
                    {
                        if (Main.rand.Next(num2) == 0)
{
                            Dust.NewDustDirect(Vector2.Lerp(Main.player[this.owner].Center, base.Center, Main.rand.NextFloat()) + new Vector2(-8f), 16, 16, 5, 0f, 0f, 0, default(Color), 1.3f).velocity += this.velocity / 4f;
                        }
                    }
                    return;
                }
                if (this.type == 26)
                {
                    int num4 = Dust.NewDust(this.position, this.width, this.height, 172, this.velocity.X * 0.4f, this.velocity.Y * 0.4f, 100, default(Color), 1.5f);
                    Main.dust[num4].noGravity = true;
                    Dust dust2 = Main.dust[num4];
                    dust2.velocity.X = dust2.velocity.X / 2f;
                    Dust dust3 = Main.dust[num4];
                    dust3.velocity.Y = dust3.velocity.Y / 2f;
                    return;
                }
                if (this.type == 948 && !this.wet)
                {
                    int num5 = Dust.NewDust(this.position, this.width, this.height, 6, this.velocity.X * 0.4f, this.velocity.Y * 0.4f, 100, default(Color), 1.2f);
                    Main.dust[num5].noGravity = true;
                    Dust dust4 = Main.dust[num5];
                    dust4.velocity.X = dust4.velocity.X * 4f;
                    Dust dust5 = Main.dust[num5];
                    dust5.velocity.Y = dust5.velocity.Y * 4f;
                    Main.dust[num5].velocity = (Main.dust[num5].velocity + this.velocity) / 2f;
                    return;
                }
                if (this.type == 35)
                {
                    int num6 = Dust.NewDust(this.position, this.width, this.height, 6, this.velocity.X * 0.4f, this.velocity.Y * 0.4f, 100, default(Color), 3f);
                    Main.dust[num6].noGravity = true;
                    Dust dust6 = Main.dust[num6];
                    dust6.velocity.X = dust6.velocity.X * 2f;
                    Dust dust7 = Main.dust[num6];
                    dust7.velocity.Y = dust7.velocity.Y * 2f;
                    return;
                }
                if (this.type == 154)
                {
                    int num7 = Dust.NewDust(this.position, this.width, this.height, 115, this.velocity.X * 0.4f, this.velocity.Y * 0.4f, 140, default(Color), 1.5f);
                    Main.dust[num7].noGravity = true;
                    Main.dust[num7].velocity *= 0.25f;
                }
            }
        }
References Terraria.Entity.Center, Terraria.Main.dust, Microsoft.Xna.Framework.Vector2.Lerp(), Terraria.Dust.NewDust(), Terraria.Dust.NewDustDirect(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Terraria.Main.player, Terraria.Main.rand, and Terraria.Dust.velocity.