Terraria Decompiled: Terraria.Projectile.AI_198_Flint_EmitSpikes
AI_198_Flint_EmitSpikes()
void Terraria.Projectile.AI_198_Flint_EmitSpikes (Vector2 startPosition, int direction) inline private
Definition at line 52679 of file Projectile.cs.
        {
            Player player = Main.player[this.owner];
            startPosition += new Vector2((float)(direction * 30), 0f);
            Point point = startPosition.ToTileCoordinates();
            ParticleOrchestrator.RequestParticleSpawn(false, ParticleOrchestraType.DeadCellsFlint, new ParticleOrchestraSettings
            {
                PositionInWorld = startPosition + new Vector2(16f, 16f) * Main.player[this.owner].Directions,
                UniqueInfoPiece = 0,
                MovementVector = new Vector2(32f, Main.player[this.owner].gravDir)
            }, null);
            bool flag = player.gravDir == -1f;
            int num = 12;
            int num2 = 2;
            int i = 0;
            while (i <= num)
            {
                if (flag)
                {
                    this.FindBlockCeiling(point.X, ref point.Y, 10, 10);
                }
                else
                {
                    this.FindBlockSurface(point.X, ref point.Y, 10, 10);
                }
                if (!WorldGen.ActiveAndWalkableTile(point.X, point.Y))
                {
                    break;
                }
                Vector2 vector = point.ToWorldCoordinates(8f, 0f);
                Vector2 vector2 = new Vector2((float)direction, -10f);
                float num3 = 1f + (float)i * 0.04f + Main.rand.NextFloat() * 0.2f;
                if (flag)
                {
                    vector += new Vector2(0f, 16f);
                    vector2.Y *= -1f;
                }
                Projectile.NewProjectile(this.GetProjectileSource_FromThis(), vector, vector2.RotatedBy((double)(Main.rand.NextFloatDirection() * 6.2831855f * 0.025f), default(Vector2)), 1041, this.damage, this.knockBack, this.owner, (float)(0 - i * 2), num3, 0f, null);
                i++;
                point.X += direction * num2;
            }
        }
References Terraria.WorldGen.ActiveAndWalkableTile(), Terraria.Projectile.NewProjectile(), Terraria.Main.player, Terraria.Main.rand, Terraria.GameContent.Drawing.ParticleOrchestrator.RequestParticleSpawn(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.