Terraria Decompiled: Terraria.Projectile.CreateImpactExplosion
CreateImpactExplosion()
void Terraria.Projectile.CreateImpactExplosion (int dustAmountMultiplier, Vector2 explosionOrigin, ref Point scanAreaStart, ref Point scanAreaEnd, int explosionRange, out bool causedShockwaves) inline private
Definition at line 70117 of file Projectile.cs.
        {
            causedShockwaves = false;
            int num = 4;
            for (int i = scanAreaStart.X; i <= scanAreaEnd.X; i++)
            {
                for (int j = scanAreaStart.Y; j <= scanAreaEnd.Y; j++)
                {
                    if (Vector2.Distance(explosionOrigin, new Vector2((float)(i * 16), (float)(j * 16))) <= (float)explosionRange)
                    {
                        Tile tileSafely = Framing.GetTileSafely(i, j);
                        if (tileSafely.active() && Main.tileSolid[(int)tileSafely.type] && !Main.tileSolidTop[(int)tileSafely.type] && !Main.tileFrameImportant[(int)tileSafely.type])
{
                            Tile tileSafely2 = Framing.GetTileSafely(i, j - 1);
                            if (!tileSafely2.active() || !Main.tileSolid[(int)tileSafely2.type] || Main.tileSolidTop[(int)tileSafely2.type])
{
                                int num2 = WorldGen.KillTile_GetTileDustAmount(true, tileSafely) * dustAmountMultiplier;
                                for (int k = 0; k < num2; k++)
{
                                    Dust dust = Main.dust[WorldGen.KillTile_MakeTileDust(i, j, tileSafely)];
                                    dust.velocity.Y = dust.velocity.Y - (3f + (float)num * 1.5f);
                                    dust.velocity.Y = dust.velocity.Y * Main.rand.NextFloat();
                                    dust.scale += (float)num * 0.03f;
                                }
                                if (num >= 2)
{
                                    for (int l = 0; l < num2 - 1; l++)
{
                                        Dust dust2 = Main.dust[WorldGen.KillTile_MakeTileDust(i, j, tileSafely)];
                                        dust2.velocity.Y = dust2.velocity.Y - (1f + (float)num);
                                        dust2.velocity.Y = dust2.velocity.Y * Main.rand.NextFloat();
                                    }
                                }
                                if (num2 > 0)
{
                                    causedShockwaves = true;
                                }
                            }
                        }
                    }
                }
            }
        }
References Terraria.Tile.active(), Microsoft.Xna.Framework.Vector2.Distance(), Terraria.Main.dust, Terraria.Framing.GetTileSafely(), int, Terraria.WorldGen.KillTile_GetTileDustAmount(), Terraria.WorldGen.KillTile_MakeTileDust(), Terraria.Main.rand, Terraria.Main.tileFrameImportant, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, and Terraria.Tile.type.