Terraria Decompiled: Terraria.Projectile.AI_196_Petal
AI_196_Petal()
void Terraria.Projectile.AI_196_Petal () inline private
Definition at line 40787 of file Projectile.cs.
        {
            int num = 20;
            bool flag = this.ai[0] < (float)num;
            if (this.localAI[0] == 0f)
            {
                this.localAI[0] = 1f;
                if (Main.netMode != 2)
                {
                    SoundEngine.PlaySound(SoundID.Item17, base.Center, 0f, 1f);
                }
                this.frame = Main.rand.Next(8);
                this.spriteDirection = ((this.velocity.X < 0f) ? (-1) : 1);
                this.rotation = Main.rand.NextFloat() * 6.2831855f;
                this.scale = 0.6f + 0.3f * Main.rand.NextFloat();
            }
            int num2 = this.frameCounter + 1;
            this.frameCounter = num2;
            if (num2 >= 4)
            {
                this.frameCounter = 0;
                num2 = this.frame + 1;
                this.frame = num2;
                if (num2 >= 8)
                {
                    this.frame = 0;
                }
            }
            this.rotation += this.velocity.X * 0.1f + this.velocity.Y * 0.1f;
            if (flag)
            {
                this.ai[0] += 1f;
                this.velocity *= 0.95f;
                if (this.ai[0] >= 10f)
                {
                    Lighting.AddLight(base.Center, new Vector3(0.5f, 0f, 0.2f));
                    return;
                }
            }
            else
            {
                bool flag2 = false;
                Vector2 center = new Vector2(0f, 0f);
                float num3 = 340f;
                for (int i = 0; i < Main.maxNPCs; i++)
                {
                    NPC npc = Main.npc[i];
                    if (npc.CanBeChasedBy(this, false))
                    {
                        float num4 = base.Distance(npc.Center);
                        if (num4 < num3)
{
                            num3 = num4;
                            center = npc.Center;
                            flag2 = true;
                        }
                    }
                }
                if (flag2)
                {
                    Vector2 vector = (center - base.Center).SafeNormalize(Vector2.Zero) * 8f;
                    float num5 = 15f;
                    this.velocity = (this.velocity * num5 + vector) / (num5 + 1f);
                    return;
                }
                this.velocity.X = MathHelper.Lerp(this.velocity.X, (float)Math.Sin((double)this.ai[0]) * 2.5f, 0.1f);
                this.velocity.Y = MathHelper.Lerp(this.velocity.Y, 0.3f, 0.1f);
            }
        }
References Terraria.Lighting.AddLight(), Terraria.NPC.CanBeChasedBy(), Terraria.Entity.Center, Terraria.Entity.Distance(), Terraria.ID.SoundID.Item17, Microsoft.Xna.Framework.MathHelper.Lerp(), Terraria.Main.maxNPCs, Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.npc, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.rand, System.Math.Sin(), and Microsoft.Xna.Framework.Vector2.Zero.