Terraria Decompiled: Terraria.Projectile.RainbowBoulder_GetTreasureCoords
RainbowBoulder_GetTreasureCoords()
bool Terraria.Projectile.RainbowBoulder_GetTreasureCoords (Rectangle playArea, out Point treasureCoords) inline private
Definition at line 18946 of file Projectile.cs.
        {
            treasureCoords = default(Point);
            Point point = base.Center.ToTileCoordinates();
            Rectangle rectangle = new Rectangle(point.X, point.Y, 1, 1);
            rectangle = playArea;
            int num = 40;
            Rectangle rectangle2 = new Rectangle(0, 0, Main.maxTilesX, Main.maxTilesY);
            rectangle2.Inflate(-num, -num);
            rectangle = Rectangle.Intersect(rectangle, rectangle2);
            int num2 = -1;
            float num3 = -1f;
            for (int i = rectangle.Left; i <= rectangle.Right; i++)
            {
                for (int j = rectangle.Top; j <= rectangle.Bottom; j++)
                {
                    Tile tile = Main.tile[i, j];
                    if (tile != null && tile.active() && TileID.Sets.FriendlyFairyCanLureTo[(int)tile.type] && SceneMetrics.IsValidForOreFinder(tile))
                    {
                        short num4 = Main.tileOreFinderPriority[(int)tile.type];
                        if (TileID.Sets.Ore[(int)tile.type])
{
                            int num5 = 3;
                            int num6 = 3;
                            int num7 = 40;
                            int num8 = 0;
                            for (int k = i - num5; k <= i + num5; k++)
{
                                for (int l = j - num6; l <= j + num6; l++)
{
                                    if (Main.tile[k, l].active() && Main.tile[k, l].type == tile.type)
{
                                        num8++;
                                    }
                                }
                            }
                            if (num8 < num7)
{
                                num4 = -1;
                            }
                        }
                        if (num2 <= (int)num4)
{
                            float num9 = base.Distance(new Vector2((float)(i * 16 + 8), (float)(j * 16 + 8)));
                            if (num2 != (int)num4 || num9 < num3)
{
                                num2 = (int)num4;
                                num3 = num9;
                                treasureCoords.X = i;
                                treasureCoords.Y = j;
                            }
                        }
                    }
                }
            }
            return num2 != -1;
        }
References Terraria.Tile.active(), Microsoft.Xna.Framework.Rectangle.Bottom, Terraria.ID.TileID.Sets.FriendlyFairyCanLureTo, Microsoft.Xna.Framework.Rectangle.Inflate(), int, Microsoft.Xna.Framework.Rectangle.Intersect(), Terraria.SceneMetrics.IsValidForOreFinder(), Microsoft.Xna.Framework.Rectangle.Left, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.ID.TileID.Sets.Ore, Microsoft.Xna.Framework.Rectangle.Right, Terraria.Main.tile, Terraria.Main.tileOreFinderPriority, Microsoft.Xna.Framework.Rectangle.Top, Terraria.Tile.type, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.