Terraria Decompiled: Terraria.Projectile.AI_188_LightsBane
AI_188_LightsBane()
void Terraria.Projectile.AI_188_LightsBane () inline private
Definition at line 42299 of file Projectile.cs.
        {
            if (this.soundDelay == 0)
            {
                this.soundDelay = -1;
                SoundEffectInstance soundEffectInstance = SoundEngine.PlaySound(SoundID.Item60, base.Center, 0f, 1f);
                if (soundEffectInstance != null)
                {
                    soundEffectInstance.Volume *= 0.15f * this.ai[0];
                }
            }
            this.scale = this.ai[0];
            this.localAI[0] += 1f;
            int num = this.frameCounter + 1;
            this.frameCounter = num;
            if (num >= 3)
            {
                this.frameCounter = 0;
                num = this.frame + 1;
                this.frame = num;
                if (num >= 12)
                {
                    this.Kill();
                    return;
                }
            }
            this.rotation = this.velocity.ToRotation();
            float num2 = this.rotation;
            float num3 = 46f * this.scale;
            Vector2 vector = num2.ToRotationVector2();
            float num4 = this.localAI[0] / 36f * 4f;
            if (num4 >= 0f && num4 <= 1f)
            {
                Dust dust = Dust.NewDustPerfect(Vector2.Lerp(base.Center - vector * num3, base.Center + vector * num3, this.localAI[0] / 36f), 278, new Vector2?(vector.RotatedBy((double)(6.2831855f * Main.rand.NextFloatDirection() * 0.02f), default(Vector2)) * 8f * Main.rand.NextFloat()), 0, new Color(60, 0, 150), 0.7f * num4);
                dust.noGravity = true;
                dust.noLight = (dust.noLightEmittance = true);
            }
        }
References Terraria.ID.SoundID.Item60, Microsoft.Xna.Framework.Vector2.Lerp(), Terraria.Dust.NewDustPerfect(), Terraria.Audio.SoundEngine.PlaySound(), and Terraria.Main.rand.