Terraria Decompiled: Terraria.Projectile.AI_204_Digtoise
AI_204_Digtoise()
void Terraria.Projectile.AI_204_Digtoise () inline private
Definition at line 38921 of file Projectile.cs.
        {
            if (!WorldGen.InWorld(base.Center.ToTileCoordinates(), 20))
            {
                this.Kill();
                return;
            }
            bool flag = this.ai[0] == 0f;
            bool flag2 = this.ai[0] == 1f;
            bool flag3 = this.ai[0] == 2f;
            bool flag4 = this.ai[0] == 3f;
            bool flag5 = this.ai[0] == 4f;
            bool flag6 = this.ai[0] == 5f;
            Player player = Main.player[this.owner];
            this.velocity.Y = this.velocity.Y + 0.13333334f;
            if (this.velocity.Y > 16f)
            {
                this.velocity.Y = 16f;
            }
            this.timeLeft = 2;
            if (player.dead || player.noBuilding)
            {
                this.Kill();
                return;
            }
            if (player.petting.isPetting && player.petting.proj == this.whoAmI)
            {
                if (!flag6)
                {
                    this.spriteDirection = (this.direction = ((base.Center.X > player.Center.X) ? (-1) : 1));
                    flag = false;
                    flag6 = true;
                    this.ai[0] = 5f;
                    this.ai[1] = 0f;
                    SoundEngine.PlaySound(SoundID.PalDigtoiseJoy, base.Center, 0f, 1f);
                }
            }
            else if (flag6)
            {
                flag = true;
                flag6 = false;
                this.ai[0] = 0f;
                this.ai[1] = 0f;
            }
            if (flag)
            {
                int num = this.soundDelay - 1;
                this.soundDelay = num;
                if (num == -20)
                {
                    SoundEngine.PlaySound(SoundID.PalDigtoise, base.Center, 0f, 1f);
                }
                if (this.soundDelay == -1)
                {
                    SoundEngine.PlaySound(SoundID.PalSummon, base.Center, 0f, 1f);
                }
            }
            if (flag || flag5 || flag6)
            {
                this.DoPalAppearEffect(player, true);
                if ((!player.active || player.HeldItem.type != 5667) && this.owner == Main.myPlayer)
                {
                    this.Kill();
                }
                this.velocity.X = this.velocity.X * 0.7f;
                if (this.ai[1] == 0f && flag)
                {
                    this.spriteDirection = (this.direction = ((base.Center.X > player.Center.X) ? 1 : (-1)));
                }
                this.ai[1] += 1f;
                if (flag && this.ai[1] >= 180f)
                {
                    this.ai[1] = 0f;
                    this.ai[0] = 1f;
                    this.netUpdate = true;
                }
                if (flag5 && this.ai[1] >= 600f && this.owner == Main.myPlayer)
                {
                    this.Kill();
                }
                if (this.frame > 2)
                {
                    this.frame = 2;
                }
                int num2 = ((this.frame == 1) ? 60 : 4);
                int num = this.frameCounter + 1;
                this.frameCounter = num;
                if (num >= num2)
                {
                    this.frameCounter = 0;
                    this.frame--;
                    if (this.frame < 0)
                    {
                        this.frame = 0;
                    }
                }
            }
            bool flag7 = flag2 || flag4 || flag3;
            if (flag7)
            {
                this.alpha = 0;
                int num3 = 0;
                int num4 = 0;
                if (flag2)
                {
                    num4 = 1;
                }
                if (flag4)
                {
                    num3 = -1;
                }
                if (flag3)
                {
                    num3 = 1;
                }
                if (num3 != 0)
                {
                    this.spriteDirection = (this.direction = num3);
                }
                int num5 = 40;
                if (this.ai[1] > (float)num5)
                {
                    this.velocity.X = this.velocity.X + (float)(num3 * 8) / 60f;
                    int num6 = 8;
                    if (Math.Abs(this.velocity.X) >= (float)num6)
                    {
                        this.velocity.X = (float)((this.velocity.X >= 0f) ? num6 : (-(float)num6));
                    }
                }
                if (num3 != 0 && this.ai[1] > (float)num5)
                {
                    Point point = (base.Bottom + new Vector2((float)(this.width * num3) / 2f + (float)(num3 * 2), 2f)).ToTileCoordinates();
                    Point point2 = new Point(point.X + num3, point.Y);
                    Point point3 = new Point(point.X + num3, point.Y);
                    if (!WorldGen.SolidTile3(point.X, point.Y) && !WorldGen.SolidTile3(point2.X, point2.Y) && !WorldGen.SolidTile3(point3.X, point3.Y))
                    {
                        flag7 = false;
                        this.ai[1] = 0f;
                        this.ai[0] = 4f;
                        this.velocity.X = this.velocity.X * 0.5f;
                        this.netUpdate = true;
                    }
                }
                Point point4 = (base.Bottom + new Vector2(0f, -15f)).ToTileCoordinates();
                if (flag7 && num3 != 0)
                {
                    int num7 = point4.X + num3 * 2;
                    bool flag8 = false;
                    for (int i = point4.Y - 2; i <= point4.Y; i++)
                    {
                        if (WorldGen.SolidTile3(num7, i))
{
                            flag8 = true;
                        }
                    }
                    if (flag8)
                    {
                        if (num3 > 0)
{
                            this.velocity.X = Math.Min(this.velocity.X, (float)(num7 * 16) - base.Right.X);
                        }
                        else
{
                            this.velocity.X = Math.Max(this.velocity.X, (float)(num7 * 16 + 16) - base.Left.X);
                        }
                    }
                }
                if (flag7 && this.ai[1] > (float)num5)
                {
                    if (this.frame < 2)
                    {
                        this.frame = 2;
                        this.localAI[1] = 0f;
                        this.frameCounter = 0;
                    }
                    int num8 = 4 - (int)(this.localAI[1] / 4f);
                    if (num8 < 1)
                    {
                        num8 = 1;
                    }
                    int num9 = ((this.frame == 2) ? 5 : num8);
                    int num = this.frameCounter + 1;
                    this.frameCounter = num;
                    if (num >= num9)
                    {
                        this.localAI[1] += 1f;
                        this.frameCounter = 0;
                        num = this.frame + 1;
                        this.frame = num;
                        if (num >= 10)
{
                            this.frame = 3;
                        }
                    }
                    if (this.soundDelay <= 0)
                    {
                        this.soundDelay = 10;
                        SoundEngine.PlaySound(SoundID.Item199, base.Center, 0f, 1f);
                    }
                    bool flag9 = false;
                    if (num4 != 0)
                    {
                        int num10 = point4.Y + 1;
                        for (int j = point4.X - 1; j <= point4.X + 1; j++)
{
                            if (WorldGen.SolidTile3(j, num10))
{
                                flag9 = true;
                            }
                        }
                    }
                    if (num3 != 0)
                    {
                        int num11 = point4.X + num3 * 2;
                        for (int k = point4.Y - 2; k <= point4.Y; k++)
{
                            if (WorldGen.SolidTile3(num11, k))
{
                                flag9 = true;
                            }
                        }
                    }
                    Lighting.AddLight(base.Center, 0.3f, 0.3f, 0.1f);
                    if (flag9)
                    {
                        for (int l = 0; l < 3; l++)
{
                            Dust dust = Dust.NewDustDirect(this.position + new Vector2((float)(num3 * 20), (float)(this.height / 2)), this.width, this.height / 2, 213, (float)(-(float)num3 * 3), -2f, 0, default(Color), 1f);
                            if (Main.rand.Next(3) == 0)
{
                                dust.scale = 2f;
                                dust.fadeIn = 3f;
                            }
                            else
{
                                dust.scale = 3f;
                            }
                        }
                    }
                }
                if (flag7 && this.ai[1] <= (float)num5)
                {
                    this.ai[1] += 1f;
                    this.frame = 0;
                }
                if (flag7 && this.ai[1] > (float)num5)
                {
                    this.ai[1] += 1f;
                    if (this.ai[1] >= (float)(num5 + 30))
                    {
                        this.ai[1] = (float)(num5 + 10);
                        if (this.owner == Main.myPlayer)
{
                            int num12 = 26;
                            int num13 = 0;
                            int num14 = 0;
                            if (num4 != 0)
{
                                int num15 = point4.Y + 1;
                                for (int m = point4.X - 1; m <= point4.X + 1; m++)
{
                                    if (WorldGen.SolidTile3(m, num15))
{
                                        num14++;
                                        int num16;
                                        int num17;
                                        player.PickTile_DetermineDamage(m, num15, num12, Main.tile[m, num15], out num16, out num17);
                                        if (num17 > 0)
{
                                            num13++;
                                            player.PickTile(m, num15, num12);
                                        }
                                    }
                                }
                            }
                            if (num3 != 0)
{
                                int num18 = point4.X + num3 * 2;
                                for (int n = point4.Y - 2; n <= point4.Y; n++)
{
                                    if (WorldGen.SolidTile3(num18, n))
{
                                        num14++;
                                        int num19;
                                        int num20;
                                        player.PickTile_DetermineDamage(num18, n, num12, Main.tile[num18, n], out num19, out num20);
                                        if (num20 > 0)
{
                                            num13++;
                                            player.PickTile(num18, n, num12);
                                        }
                                    }
                                }
                            }
                            if (num14 > 0 && num13 < num14)
{
                                this.ai[1] = 0f;
                                this.ai[0] = 4f;
                                this.netUpdate = true;
                            }
                        }
                    }
                }
            }
        }
References System.Math.Abs(), Terraria.Player.active, Terraria.Lighting.AddLight(), Terraria.Entity.Center, Terraria.Player.dead, Terraria.Player.HeldItem, int, Terraria.WorldGen.InWorld(), Terraria.GameContent.PlayerPettingInfo.isPetting, Terraria.ID.SoundID.Item199, System.Math.Max(), System.Math.Min(), Terraria.Main.myPlayer, Terraria.Dust.NewDustDirect(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Player.noBuilding, Terraria.ID.SoundID.PalDigtoise, Terraria.ID.SoundID.PalDigtoiseJoy, Terraria.ID.SoundID.PalSummon, Terraria.Player.petting, Terraria.Player.PickTile(), Terraria.Player.PickTile_DetermineDamage(), Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.GameContent.PlayerPettingInfo.proj, Terraria.Main.rand, Terraria.WorldGen.SolidTile3(), Terraria.Main.tile, Terraria.Item.type, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Point.Y.