Terraria Decompiled: Terraria.Projectile.AI_001
AI_001()
void Terraria.Projectile.AI_001 () inline private
Definition at line 54433 of file Projectile.cs.
        {
            if (this.type == 469 && this.wet && !this.honeyWet && !this.shimmerWet)
            {
                this.Kill();
            }
            if (this.type == 88)
            {
                if (this.ai[0] != 0f)
                {
                    this.extraUpdates = (int)this.ai[0];
                }
                if (this.scale < 4f)
                {
                    this.scale += 0.053f;
                    if (this.scale > 4f)
                    {
                        this.scale = 4f;
                    }
                    if (Main.myPlayer == this.owner)
                    {
                        this.knockBack *= 1.0045f;
                        this.localAI[0] += 1f;
                        if (this.localAI[0] >= 8f)
{
                            this.localAI[0] = 0f;
                            this.damage += Main.rand.Next(1, 4);
                            this.penetrate += Main.rand.Next(0, 2);
                        }
                    }
                }
            }
            if (this.type == 20 && this.scale < 3f)
            {
                this.scale += 0.0189f;
                if (this.scale > 3f)
                {
                    this.scale = 3f;
                }
                if (Main.myPlayer == this.owner)
                {
                    this.knockBack *= 1.0025f;
                    this.localAI[0] += 1f;
                    if (this.localAI[0] >= 25f)
                    {
                        this.localAI[0] = 0f;
                        this.damage += Main.rand.Next(1, 3);
                        this.penetrate++;
                    }
                }
            }
            int num;
            if (this.type == 601)
            {
                Color portalColor = PortalHelper.GetPortalColor(this.owner, (int)this.ai[0]);
                Vector3 vector = portalColor.ToVector3();
                vector *= 0.5f;
                Lighting.AddLight(base.Center + this.velocity * 3f, vector);
                if (this.alpha > 0 && this.alpha <= 15)
                {
                    Color color = portalColor;
                    color.A = byte.MaxValue;
                    for (int i = 0; i < 4; i++)
                    {
                        Dust dust = Main.dust[Dust.NewDust(base.Center, 0, 0, 264, 0f, 0f, 0, default(Color), 1f)];
                        dust.position = base.Center;
                        dust.velocity = this.velocity * 2f + Utils.RandomVector2(Main.rand, -1f, 1f);
                        dust.color = color;
                        dust.scale = 1.2f;
                        dust.noLight = true;
                        dust.noGravity = true;
                        dust.customData = Main.player[this.owner];
                    }
                    if (this.ai[0] != 0f)
                    {
                        SoundEngine.PlaySound(SoundID.Item114, this.position, 0f, 1f);
                    }
                    else
                    {
                        SoundEngine.PlaySound(SoundID.Item115, this.position, 0f, 1f);
                    }
                }
                this.alpha -= 15;
                if (this.alpha < 0)
                {
                    this.alpha = 0;
                }
                num = this.frameCounter + 1;
                this.frameCounter = num;
                if (num >= 4)
                {
                    this.frameCounter = 0;
                    num = this.frame + 1;
                    this.frame = num;
                    if (num >= Main.projFrames[this.type])
                    {
                        this.frame = 0;
                    }
                }
                if (this.alpha == 0)
                {
                    Color color2 = portalColor;
                    color2.A = byte.MaxValue;
                    Dust dust2 = Main.dust[Dust.NewDust(base.Center, 0, 0, 263, 0f, 0f, 0, default(Color), 1f)];
                    dust2.position = base.Center;
                    dust2.velocity = this.velocity / 4f;
                    dust2.color = color2;
                    dust2.noGravity = true;
                    dust2.scale = 0.6f;
                }
            }
            if (this.type == 472)
            {
                int num2 = Dust.NewDust(this.position, this.width, this.height, 30, 0f, 0f, 0, default(Color), 1f);
                Main.dust[num2].noGravity = true;
                Main.dust[num2].velocity *= 0.25f;
                Main.dust[num2].velocity += this.velocity * 0.75f;
                if (this.localAI[0] == 0f)
                {
                    this.localAI[0] = 1f;
                    SoundEngine.PlaySound(SoundID.Item17, this.position, 0f, 1f);
                    for (int j = 0; j < 20; j++)
                    {
                        num2 = Dust.NewDust(this.position, this.width, this.height, 30, 0f, 0f, 0, default(Color), 1f);
                        Main.dust[num2].noGravity = true;
                        Main.dust[num2].velocity *= 0.25f;
                        Main.dust[num2].velocity += this.velocity;
                        Dust dust3 = Main.dust[num2];
                        dust3.velocity.X = dust3.velocity.X * (1f + (float)Main.rand.Next(-50, 51) * 0.01f);
                        Dust dust4 = Main.dust[num2];
                        dust4.velocity.Y = dust4.velocity.Y * (1f + (float)Main.rand.Next(-50, 51) * 0.01f);
                    }
                }
            }
            if (this.type == 323)
            {
                this.alpha -= 50;
                if (this.alpha < 0)
                {
                    this.alpha = 0;
                }
            }
            if (this.type == 436)
            {
                if (this.ai[1] == 0f)
                {
                    this.ai[1] = 1f;
                    SoundEngine.PlaySound(SoundID.Item12, this.position, 0f, 1f);
                }
                this.alpha -= 40;
                if (this.alpha < 0)
                {
                    this.alpha = 0;
                }
                this.spriteDirection = this.direction;
                this.frameCounter++;
                if (this.frameCounter >= 3)
                {
                    this.frame++;
                    this.frameCounter = 0;
                    if (this.frame >= 4)
                    {
                        this.frame = 0;
                    }
                }
                Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 0.3f, 1.1f, 0.5f);
            }
            if (this.type == 467)
            {
                if (this.ai[1] == 0f)
                {
                    this.ai[1] = 1f;
                    SoundEngine.PlaySound(SoundID.Item34, this.position, 0f, 1f);
                }
                else if (this.ai[1] == 1f && Main.netMode != 1)
                {
                    int num3 = -1;
                    float num4 = 2000f;
                    for (int k = 0; k < 255; k++)
                    {
                        if (Main.player[k].active && !Main.player[k].dead)
{
                            Vector2 center = Main.player[k].Center;
                            float num5 = Vector2.Distance(center, base.Center);
                            if ((num5 < num4 || num3 == -1) && Collision.CanHit(base.Center, 1, 1, center, 1, 1))
{
                                num4 = num5;
                                num3 = k;
                            }
                        }
                    }
                    if (num4 < 20f)
                    {
                        this.Kill();
                        return;
                    }
                    if (num3 != -1)
                    {
                        this.ai[1] = 21f;
                        this.ai[0] = (float)num3;
                        this.netUpdate = true;
                    }
                }
                else if (this.ai[1] > 20f && this.ai[1] < 200f)
                {
                    this.ai[1] += 1f;
                    int num6 = (int)this.ai[0];
                    if (!Main.player[num6].active || Main.player[num6].dead)
                    {
                        this.ai[1] = 1f;
                        this.ai[0] = 0f;
                        this.netUpdate = true;
                    }
                    else
                    {
                        float num7 = this.velocity.ToRotation();
                        Vector2 vector2 = Main.player[num6].Center - base.Center;
                        if (vector2.Length() < 20f)
{
                            this.Kill();
                            return;
                        }
                        float num8 = vector2.ToRotation();
                        if (vector2 == Vector2.Zero)
{
                            num8 = num7;
                        }
                        float num9 = num7.AngleLerp(num8, 0.008f);
                        this.velocity = new Vector2(this.velocity.Length(), 0f).RotatedBy((double)num9, default(Vector2));
                    }
                }
                if (this.ai[1] >= 1f && this.ai[1] < 20f)
                {
                    this.ai[1] += 1f;
                    if (this.ai[1] == 20f)
                    {
                        this.ai[1] = 1f;
                    }
                }
                this.alpha -= 40;
                if (this.alpha < 0)
                {
                    this.alpha = 0;
                }
                this.spriteDirection = this.direction;
                this.frameCounter++;
                if (this.frameCounter >= 3)
                {
                    this.frame++;
                    this.frameCounter = 0;
                    if (this.frame >= 4)
                    {
                        this.frame = 0;
                    }
                }
                Lighting.AddLight(base.Center, 1.1f, 0.9f, 0.4f);
                this.localAI[0] += 1f;
                if (this.localAI[0] == 12f)
                {
                    this.localAI[0] = 0f;
                    for (int l = 0; l < 12; l++)
                    {
                        Vector2 vector3 = Vector2.UnitX * (float)(-(float)this.width) / 2f;
                        vector3 += -Vector2.UnitY.RotatedBy((double)((float)l * 3.1415927f / 6f), default(Vector2)) * new Vector2(8f, 16f);
                        vector3 = vector3.RotatedBy((double)(this.rotation - 1.5707964f), default(Vector2));
                        int num10 = Dust.NewDust(base.Center, 0, 0, 6, 0f, 0f, 160, default(Color), 1f);
                        Main.dust[num10].scale = 1.1f;
                        Main.dust[num10].noGravity = true;
                        Main.dust[num10].position = base.Center + vector3;
                        Main.dust[num10].velocity = this.velocity * 0.1f;
                        Main.dust[num10].velocity = Vector2.Normalize(base.Center - this.velocity * 3f - Main.dust[num10].position) * 1.25f;
                    }
                }
                if (Main.rand.Next(4) == 0)
                {
                    for (int m = 0; m < 1; m++)
                    {
                        Vector2 vector4 = -Vector2.UnitX.RotatedByRandom(0.19634954631328583).RotatedBy((double)this.velocity.ToRotation(), default(Vector2));
                        int num11 = Dust.NewDust(this.position, this.width, this.height, 31, 0f, 0f, 100, default(Color), 1f);
                        Main.dust[num11].velocity *= 0.1f;
                        Main.dust[num11].position = base.Center + vector4 * (float)this.width / 2f;
                        Main.dust[num11].fadeIn = 0.9f;
                    }
                }
                if (Main.rand.Next(32) == 0)
                {
                    for (int n = 0; n < 1; n++)
                    {
                        Vector2 vector5 = -Vector2.UnitX.RotatedByRandom(0.39269909262657166).RotatedBy((double)this.velocity.ToRotation(), default(Vector2));
                        int num12 = Dust.NewDust(this.position, this.width, this.height, 31, 0f, 0f, 155, default(Color), 0.8f);
                        Main.dust[num12].velocity *= 0.3f;
                        Main.dust[num12].position = base.Center + vector5 * (float)this.width / 2f;
                        if (Main.rand.Next(2) == 0)
{
                            Main.dust[num12].fadeIn = 1.4f;
                        }
                    }
                }
                if (Main.rand.Next(2) == 0)
                {
                    for (int num13 = 0; num13 < 2; num13++)
                    {
                        Vector2 vector6 = -Vector2.UnitX.RotatedByRandom(0.7853981852531433).RotatedBy((double)this.velocity.ToRotation(), default(Vector2));
                        int num14 = Dust.NewDust(this.position, this.width, this.height, 6, 0f, 0f, 0, default(Color), 1.2f);
                        Main.dust[num14].velocity *= 0.3f;
                        Main.dust[num14].noGravity = true;
                        Main.dust[num14].position = base.Center + vector6 * (float)this.width / 2f;
                        if (Main.rand.Next(2) == 0)
{
                            Main.dust[num14].fadeIn = 1.4f;
                        }
                    }
                }
            }
            if (this.type == 468)
            {
                if (this.ai[1] == 0f)
                {
                    this.ai[1] = 1f;
                    SoundEngine.PlaySound(SoundID.Item34, this.position, 0f, 1f);
                }
                else if (this.ai[1] == 1f && Main.netMode != 1)
                {
                    int num15 = -1;
                    float num16 = 2000f;
                    for (int num17 = 0; num17 < 255; num17++)
                    {
                        if (Main.player[num17].active && !Main.player[num17].dead)
{
                            Vector2 center2 = Main.player[num17].Center;
                            float num18 = Vector2.Distance(center2, base.Center);
                            if ((num18 < num16 || num15 == -1) && Collision.CanHit(base.Center, 1, 1, center2, 1, 1))
{
                                num16 = num18;
                                num15 = num17;
                            }
                        }
                    }
                    if (num16 < 20f)
                    {
                        this.Kill();
                        return;
                    }
                    if (num15 != -1)
                    {
                        this.ai[1] = 21f;
                        this.ai[0] = (float)num15;
                        this.netUpdate = true;
                    }
                }
                else if (this.ai[1] > 20f && this.ai[1] < 200f)
                {
                    this.ai[1] += 1f;
                    int num19 = (int)this.ai[0];
                    if (!Main.player[num19].active || Main.player[num19].dead)
                    {
                        this.ai[1] = 1f;
                        this.ai[0] = 0f;
                        this.netUpdate = true;
                    }
                    else
                    {
                        float num20 = this.velocity.ToRotation();
                        Vector2 vector7 = Main.player[num19].Center - base.Center;
                        if (vector7.Length() < 20f)
{
                            this.Kill();
                            return;
                        }
                        float num21 = vector7.ToRotation();
                        if (vector7 == Vector2.Zero)
{
                            num21 = num20;
                        }
                        float num22 = num20.AngleLerp(num21, 0.01f);
                        this.velocity = new Vector2(this.velocity.Length(), 0f).RotatedBy((double)num22, default(Vector2));
                    }
                }
                if (this.ai[1] >= 1f && this.ai[1] < 20f)
                {
                    this.ai[1] += 1f;
                    if (this.ai[1] == 20f)
                    {
                        this.ai[1] = 1f;
                    }
                }
                this.alpha -= 40;
                if (this.alpha < 0)
                {
                    this.alpha = 0;
                }
                this.spriteDirection = this.direction;
                this.frameCounter++;
                if (this.frameCounter >= 3)
                {
                    this.frame++;
                    this.frameCounter = 0;
                    if (this.frame >= 4)
                    {
                        this.frame = 0;
                    }
                }
                Lighting.AddLight(base.Center, 0.2f, 0.1f, 0.6f);
                this.localAI[0] += 1f;
                if (this.localAI[0] == 12f)
                {
                    this.localAI[0] = 0f;
                    for (int num23 = 0; num23 < 12; num23++)
                    {
                        Vector2 vector8 = Vector2.UnitX * (float)(-(float)this.width) / 2f;
                        vector8 += -Vector2.UnitY.RotatedBy((double)((float)num23 * 3.1415927f / 6f), default(Vector2)) * new Vector2(8f, 16f);
                        vector8 = vector8.RotatedBy((double)(this.rotation - 1.5707964f), default(Vector2));
                        int num24 = Dust.NewDust(base.Center, 0, 0, 27, 0f, 0f, 160, default(Color), 1f);
                        Main.dust[num24].scale = 1.1f;
                        Main.dust[num24].noGravity = true;
                        Main.dust[num24].position = base.Center + vector8;
                        Main.dust[num24].velocity = this.velocity * 0.1f;
                        Main.dust[num24].velocity = Vector2.Normalize(base.Center - this.velocity * 3f - Main.dust[num24].position) * 1.25f;
                    }
                }
                if (Main.rand.Next(4) == 0)
                {
                    for (int num25 = 0; num25 < 1; num25++)
                    {
                        Vector2 vector9 = -Vector2.UnitX.RotatedByRandom(0.19634954631328583).RotatedBy((double)this.velocity.ToRotation(), default(Vector2));
                        int num26 = Dust.NewDust(this.position, this.width, this.height, 31, 0f, 0f, 100, default(Color), 1f);
                        Main.dust[num26].velocity *= 0.1f;
                        Main.dust[num26].position = base.Center + vector9 * (float)this.width / 2f;
                        Main.dust[num26].fadeIn = 0.9f;
                    }
                }
                if (Main.rand.Next(32) == 0)
                {
                    for (int num27 = 0; num27 < 1; num27++)
                    {
                        Vector2 vector10 = -Vector2.UnitX.RotatedByRandom(0.39269909262657166).RotatedBy((double)this.velocity.ToRotation(), default(Vector2));
                        int num28 = Dust.NewDust(this.position, this.width, this.height, 31, 0f, 0f, 155, default(Color), 0.8f);
                        Main.dust[num28].velocity *= 0.3f;
                        Main.dust[num28].position = base.Center + vector10 * (float)this.width / 2f;
                        if (Main.rand.Next(2) == 0)
{
                            Main.dust[num28].fadeIn = 1.4f;
                        }
                    }
                }
                if (Main.rand.Next(2) == 0)
                {
                    for (int num29 = 0; num29 < 2; num29++)
                    {
                        Vector2 vector11 = -Vector2.UnitX.RotatedByRandom(0.7853981852531433).RotatedBy((double)this.velocity.ToRotation(), default(Vector2));
                        int num30 = Dust.NewDust(this.position, this.width, this.height, 27, 0f, 0f, 0, default(Color), 1.2f);
                        Main.dust[num30].velocity *= 0.3f;
                        Main.dust[num30].noGravity = true;
                        Main.dust[num30].position = base.Center + vector11 * (float)this.width / 2f;
                        if (Main.rand.Next(2) == 0)
{
                            Main.dust[num30].fadeIn = 1.4f;
                        }
                    }
                }
            }
            if (this.type == 634 || this.type == 635)
            {
                float num31 = 5f;
                float num32 = 250f;
                float num33 = 6f;
                Vector2 vector12 = new Vector2(8f, 10f);
                float num34 = 1.2f;
                Vector3 vector13 = new Vector3(0.7f, 0.1f, 0.5f);
                int num35 = 4 * this.MaxUpdates;
                int num36 = Utils.SelectRandom<int>(Main.rand, new int[] { 242, 73, 72, 71, 255 });
                int num37 = 255;
                if (this.type == 635)
                {
                    vector12 = new Vector2(10f, 20f);
                    num34 = 1f;
                    num32 = 500f;
                    num37 = 88;
                    num35 = 3 * this.MaxUpdates;
                    vector13 = new Vector3(0.4f, 0.6f, 0.9f);
                    num36 = Utils.SelectRandom<int>(Main.rand, new int[] { 242, 59, 88 });
                }
                if (this.ai[1] == 0f)
                {
                    this.ai[1] = 1f;
                    this.localAI[0] = (float)(-(float)Main.rand.Next(48));
                    SoundEngine.PlaySound(SoundID.Item34, this.position, 0f, 1f);
                }
                else if (this.ai[1] == 1f && this.owner == Main.myPlayer)
                {
                    int num38 = -1;
                    float num39 = num32;
                    for (int num40 = 0; num40 < Main.maxNPCs; num40++)
                    {
                        if (Main.npc[num40].active && Main.npc[num40].CanBeChasedBy(this, false))
{
                            Vector2 center3 = Main.npc[num40].Center;
                            float num41 = Vector2.Distance(center3, base.Center);
                            if (num41 < num39 && num38 == -1 && Collision.CanHitLine(base.Center, 1, 1, center3, 1, 1))
{
                                num39 = num41;
                                num38 = num40;
                            }
                        }
                    }
                    if (num39 < 20f)
                    {
                        this.Kill();
                        return;
                    }
                    if (num38 != -1)
                    {
                        this.ai[1] = num31 + 1f;
                        this.ai[0] = (float)num38;
                        this.netUpdate = true;
                    }
                }
                else if (this.ai[1] > num31)
                {
                    this.ai[1] += 1f;
                    int num42 = (int)this.ai[0];
                    if (!Main.npc[num42].active || !Main.npc[num42].CanBeChasedBy(this, false))
                    {
                        this.ai[1] = 1f;
                        this.ai[0] = 0f;
                        this.netUpdate = true;
                    }
                    else
                    {
                        this.velocity.ToRotation();
                        Vector2 vector14 = Main.npc[num42].Center - base.Center;
                        if (vector14.Length() < 20f)
{
                            this.Kill();
                            return;
                        }
                        if (vector14 != Vector2.Zero)
{
                            vector14.Normalize();
                            vector14 *= num33;
                        }
                        float num43 = 30f;
                        this.velocity = (this.velocity * (num43 - 1f) + vector14) / num43;
                    }
                }
                if (this.ai[1] >= 1f && this.ai[1] < num31)
                {
                    this.ai[1] += 1f;
                    if (this.ai[1] == num31)
                    {
                        this.ai[1] = 1f;
                    }
                }
                this.alpha -= 40;
                if (this.alpha < 0)
                {
                    this.alpha = 0;
                }
                this.spriteDirection = this.direction;
                this.frameCounter++;
                if (this.frameCounter >= num35)
                {
                    this.frame++;
                    this.frameCounter = 0;
                    if (this.frame >= 4)
                    {
                        this.frame = 0;
                    }
                }
                Lighting.AddLight(base.Center, vector13);
                this.rotation = this.velocity.ToRotation();
                this.localAI[0] += 1f;
                if (this.localAI[0] == 48f)
                {
                    this.localAI[0] = 0f;
                }
                else if (this.alpha == 0)
                {
                    for (int num44 = 0; num44 < 2; num44++)
                    {
                        Vector2 vector15 = Vector2.UnitX * -30f;
                        vector15 = -Vector2.UnitY.RotatedBy((double)(this.localAI[0] * 0.1308997f + (float)num44 * 3.1415927f), default(Vector2)) * vector12 - this.rotation.ToRotationVector2() * 10f;
                        int num45 = Dust.NewDust(base.Center, 0, 0, num37, 0f, 0f, 160, default(Color), 1f);
                        Main.dust[num45].scale = num34;
                        Main.dust[num45].noGravity = true;
                        Main.dust[num45].position = base.Center + vector15 + this.velocity * 2f;
                        Main.dust[num45].velocity = Vector2.Normalize(base.Center + this.velocity * 2f * 8f - Main.dust[num45].position) * 2f + this.velocity * 2f;
                    }
                }
                if (Main.rand.Next(12) == 0)
                {
                    for (int num46 = 0; num46 < 1; num46++)
                    {
                        Vector2 vector16 = -Vector2.UnitX.RotatedByRandom(0.19634954631328583).RotatedBy((double)this.velocity.ToRotation(), default(Vector2));
                        int num47 = Dust.NewDust(this.position, this.width, this.height, 31, 0f, 0f, 100, default(Color), 1f);
                        Main.dust[num47].velocity *= 0.1f;
                        Main.dust[num47].position = base.Center + vector16 * (float)this.width / 2f + this.velocity * 2f;
                        Main.dust[num47].fadeIn = 0.9f;
                    }
                }
                if (Main.rand.Next(64) == 0)
                {
                    for (int num48 = 0; num48 < 1; num48++)
                    {
                        Vector2 vector17 = -Vector2.UnitX.RotatedByRandom(0.39269909262657166).RotatedBy((double)this.velocity.ToRotation(), default(Vector2));
                        int num49 = Dust.NewDust(this.position, this.width, this.height, 31, 0f, 0f, 155, default(Color), 0.8f);
                        Main.dust[num49].velocity *= 0.3f;
                        Main.dust[num49].position = base.Center + vector17 * (float)this.width / 2f;
                        if (Main.rand.Next(2) == 0)
{
                            Main.dust[num49].fadeIn = 1.4f;
                        }
                    }
                }
                if (Main.rand.Next(4) == 0)
                {
                    for (int num50 = 0; num50 < 2; num50++)
                    {
                        Vector2 vector18 = -Vector2.UnitX.RotatedByRandom(0.7853981852531433).RotatedBy((double)this.velocity.ToRotation(), default(Vector2));
                        int num51 = Dust.NewDust(this.position, this.width, this.height, num36, 0f, 0f, 0, default(Color), 1.2f);
                        Main.dust[num51].velocity *= 0.3f;
                        Main.dust[num51].noGravity = true;
                        Main.dust[num51].position = base.Center + vector18 * (float)this.width / 2f;
                        if (Main.rand.Next(2) == 0)
{
                            Main.dust[num51].fadeIn = 1.4f;
                        }
                    }
                }
                if (Main.rand.Next(12) == 0 && this.type == 634)
                {
                    Vector2 vector19 = -Vector2.UnitX.RotatedByRandom(0.19634954631328583).RotatedBy((double)this.velocity.ToRotation(), default(Vector2));
                    int num52 = Dust.NewDust(this.position, this.width, this.height, num37, 0f, 0f, 100, default(Color), 1f);
                    Main.dust[num52].velocity *= 0.3f;
                    Main.dust[num52].position = base.Center + vector19 * (float)this.width / 2f;
                    Main.dust[num52].fadeIn = 0.9f;
                    Main.dust[num52].noGravity = true;
                }
                if (Main.rand.Next(3) == 0 && this.type == 635)
                {
                    Vector2 vector20 = -Vector2.UnitX.RotatedByRandom(0.19634954631328583).RotatedBy((double)this.velocity.ToRotation(), default(Vector2));
                    int num53 = Dust.NewDust(this.position, this.width, this.height, num37, 0f, 0f, 100, default(Color), 1f);
                    Main.dust[num53].velocity *= 0.3f;
                    Main.dust[num53].position = base.Center + vector20 * (float)this.width / 2f;
                    Main.dust[num53].fadeIn = 1.2f;
                    Main.dust[num53].scale = 1.5f;
                    Main.dust[num53].noGravity = true;
                }
            }
            if (this.type == 459)
            {
                this.alpha -= 30;
                if (this.alpha < 0)
                {
                    this.alpha = 0;
                }
                this.spriteDirection = this.direction;
                this.frameCounter++;
                if (this.frameCounter >= 3)
                {
                    this.frame++;
                    this.frameCounter = 0;
                    if (this.frame >= 3)
                    {
                        this.frame = 0;
                    }
                }
                this.ai[1] = MathHelper.Clamp(this.ai[1], 0.7f, 1.6f);
                this.position = base.Center;
                this.scale = this.ai[1];
                this.width = (this.height = (int)(22f * this.scale));
                base.Center = this.position;
                Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 0.4f, 0.85f, 0.9f);
                int num54;
                if ((double)this.scale < 0.85)
                {
                    num54 = ((Main.rand.Next(3) == 0) ? 1 : 0);
                }
                else
                {
                    num54 = 1;
                    this.penetrate = -1;
                    this.maxPenetrate = -1;
                }
                for (int num55 = 0; num55 < num54; num55++)
                {
                    int num56 = Dust.NewDust(this.position, this.width, this.height, 226, this.velocity.X, 0f, 0, default(Color), 1f);
                    Main.dust[num56].position -= Vector2.One * 3f;
                    Main.dust[num56].scale = 0.5f;
                    Main.dust[num56].noGravity = true;
                    Main.dust[num56].velocity = this.velocity / 3f;
                    Main.dust[num56].alpha = 255 - (int)(255f * this.scale);
                }
            }
            if (this.type == 709)
            {
                this.alpha -= 30;
                if (this.alpha < 0)
                {
                    this.alpha = 0;
                }
                this.spriteDirection = this.direction;
                this.frameCounter++;
                if (this.frameCounter >= 3)
                {
                    this.frame++;
                    this.frameCounter = 0;
                    if (this.frame >= 3)
                    {
                        this.frame = 0;
                    }
                }
                Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 0.4f, 0.85f, 0.9f);
                if (this.ai[1] == 0f)
                {
                    SoundEngine.PlayTrackedSound(SoundID.DD2_SkyDragonsFuryShot, base.Center, default(SoundPlayOverrides));
                }
                this.ai[1] += 1f;
                if (this.ai[1] >= 30f)
                {
                    this.Kill();
                    return;
                }
            }
            if (this.type == 442)
            {
                this.frame = 0;
                if (this.alpha != 0)
                {
                    this.localAI[0] += 1f;
                    if (this.localAI[0] >= 4f)
                    {
                        this.alpha -= 90;
                        if (this.alpha < 0)
{
                            this.alpha = 0;
                            this.localAI[0] = 2f;
                        }
                    }
                }
                if (Vector2.Distance(base.Center, new Vector2(this.ai[0], this.ai[1]) * 16f + Vector2.One * 8f) <= 16f)
                {
                    this.Kill();
                    return;
                }
                if (this.alpha == 0)
                {
                    this.localAI[1] += 1f;
                    if (this.localAI[1] >= 120f)
                    {
                        this.Kill();
                        return;
                    }
                    Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 0.3f, 0.45f, 0.8f);
                    this.localAI[0] += 1f;
                    if (this.localAI[0] == 3f)
                    {
                        this.localAI[0] = 0f;
                        for (int num57 = 0; num57 < 8; num57++)
{
                            Vector2 vector21 = Vector2.UnitX * -8f;
                            vector21 += -Vector2.UnitY.RotatedBy((double)((float)num57 * 3.1415927f / 4f), default(Vector2)) * new Vector2(2f, 4f);
                            vector21 = vector21.RotatedBy((double)(this.rotation - 1.5707964f), default(Vector2));
                            int num58 = Dust.NewDust(base.Center, 0, 0, 135, 0f, 0f, 0, default(Color), 1f);
                            Main.dust[num58].scale = 1.5f;
                            Main.dust[num58].noGravity = true;
                            Main.dust[num58].position = base.Center + vector21;
                            Main.dust[num58].velocity = this.velocity * 0.66f;
                        }
                    }
                }
            }
            if (this.type == 440 || this.type == 449 || this.type == 606)
            {
                if (this.alpha > 0)
                {
                    this.alpha -= 25;
                }
                if (this.alpha < 0)
                {
                    this.alpha = 0;
                }
                if (this.type == 440)
                {
                    Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 0.25f, 0.4f, 0.7f);
                }
                if (this.type == 449)
                {
                    Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 0.7f, 0.65f, 0.3f);
                }
                if (this.type == 606)
                {
                    Lighting.AddLight(base.Center, 0.7f, 0.3f, 0.3f);
                }
                float num59 = 100f;
                float num60 = 3f;
                if (this.type == 606)
                {
                    num59 = 150f;
                    num60 = 5f;
                }
                if (this.ai[1] == 0f)
                {
                    this.localAI[0] += num60;
                    if (this.localAI[0] == num60 * 1f && this.type == 606)
                    {
                        for (int num61 = 0; num61 < 4; num61++)
{
                            int num62 = Dust.NewDust(base.Center - this.velocity / 2f, 0, 0, 182, 0f, 0f, 100, default(Color), 1.4f);
                            Main.dust[num62].velocity *= 0.2f;
                            Main.dust[num62].velocity += this.velocity / 10f;
                            Main.dust[num62].noGravity = true;
                        }
                    }
                    if (this.localAI[0] > num59)
                    {
                        this.localAI[0] = num59;
                    }
                }
                else
                {
                    this.localAI[0] -= num60;
                    if (this.localAI[0] <= 0f)
                    {
                        this.Kill();
                        return;
                    }
                }
            }
            if (this.type == 438)
            {
                Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 0.4f, 0.1f, 0.2f);
            }
            if (this.type == 593)
            {
                Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 0.4f, 0.1f, 0.3f);
                num = this.frameCounter + 1;
                this.frameCounter = num;
                if (num >= 12)
                {
                    num = this.frame + 1;
                    this.frame = num;
                    if (num >= Main.projFrames[this.type])
                    {
                        this.frame = 0;
                    }
                    this.frameCounter = 0;
                }
                if (Main.rand.Next(2) == 0)
                {
                    Vector2 vector22 = Vector2.UnitY.RotatedByRandom(6.2831854820251465);
                    Dust dust5 = Main.dust[Dust.NewDust(base.Center - vector22 * 8f, 0, 0, 240, 0f, 0f, 0, default(Color), 1f)];
                    dust5.noGravity = true;
                    dust5.position = base.Center - vector22 * 8f * this.scale;
                    dust5.velocity = vector22.RotatedBy(-1.5707963705062866, default(Vector2)) * 2f;
                    dust5.velocity = Vector2.Zero;
                    dust5.scale = 0.5f + Main.rand.NextFloat();
                    dust5.fadeIn = 0.5f;
                }
            }
            if (this.type == 592)
            {
                Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 0.15f, 0.15f, 0.4f);
            }
            if (this.type == 462)
            {
                int num63 = Dust.NewDust(base.Center, 0, 0, 229, 0f, 0f, 100, default(Color), 1f);
                Main.dust[num63].noLight = true;
                Main.dust[num63].noGravity = true;
                Main.dust[num63].velocity = this.velocity;
                Main.dust[num63].position -= Vector2.One * 4f;
                Main.dust[num63].scale = 0.8f;
                num = this.frameCounter + 1;
                this.frameCounter = num;
                if (num >= 9)
                {
                    this.frameCounter = 0;
                    num = this.frame + 1;
                    this.frame = num;
                    if (num >= 5)
                    {
                        this.frame = 0;
                    }
                }
            }
            if (this.type == 437)
            {
                if (this.ai[1] == 0f)
                {
                    this.ai[1] = 1f;
                    SoundEngine.PlaySound(SoundID.Item12, this.position, 0f, 1f);
                }
                if (this.localAI[0] == 0f)
                {
                    this.localAI[0] = 1f;
                    for (int num64 = 0; num64 < 4; num64++)
                    {
                        int num65 = Dust.NewDust(this.position, this.width, this.height, 226, this.velocity.X, 0f, 0, default(Color), 1f);
                        Main.dust[num65].position = Vector2.Lerp(Main.dust[num65].position, base.Center, 0.25f);
                        Main.dust[num65].scale = 0.5f;
                        Main.dust[num65].noGravity = true;
                        Main.dust[num65].velocity /= 2f;
                        Main.dust[num65].velocity += this.velocity * 0.66f;
                    }
                }
                if (this.ai[0] < 16f)
                {
                    for (int num66 = 0; num66 < 2; num66++)
                    {
                        int num67 = Dust.NewDust(this.position, this.width, this.height, 226, this.velocity.X, 0f, 0, default(Color), 1f);
                        Main.dust[num67].position = this.position + new Vector2((float)(((this.direction == 1) ? 1 : 0) * this.width), (float)(2 + (this.height - 4) * num66));
                        Main.dust[num67].scale = 0.3f;
                        Main.dust[num67].noGravity = true;
                        Main.dust[num67].velocity = Vector2.Zero;
                    }
                }
            }
            if (this.type == 435)
            {
                if (this.ai[1] == 0f)
                {
                    this.ai[1] = 1f;
                    SoundEngine.PlaySound(SoundID.Item12, this.position, 0f, 1f);
                }
                this.alpha -= 40;
                if (this.alpha < 0)
                {
                    this.alpha = 0;
                }
                this.spriteDirection = this.direction;
                this.frameCounter++;
                if (this.frameCounter >= 3)
                {
                    this.frame++;
                    this.frameCounter = 0;
                    if (this.frame >= 4)
                    {
                        this.frame = 0;
                    }
                }
                Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 0.3f, 0.8f, 1.1f);
            }
            if (this.type == 682)
            {
                if (this.ai[1] == 0f)
                {
                    this.ai[1] = 1f;
                    SoundEngine.PlaySound(SoundID.DD2_LightningBugZap, this.position, 0f, 1f);
                    for (int num68 = 0; num68 < 8; num68++)
                    {
                        Dust dust6 = Dust.NewDustDirect(this.position, this.width, this.height, 272, 0f, 0f, 0, default(Color), 1f);
                        dust6.velocity *= 1f;
                        dust6.velocity += this.velocity * 0.65f;
                        dust6.scale = 0.6f;
                        dust6.fadeIn = 0.8f;
                        dust6.noGravity = true;
                        dust6.noLight = true;
                        dust6.position += dust6.velocity * 3f;
                    }
                }
                this.alpha -= 40;
                if (this.alpha < 0)
                {
                    this.alpha = 0;
                }
                this.spriteDirection = this.direction;
                this.frameCounter++;
                if (this.frameCounter >= 3)
                {
                    this.frame++;
                    this.frameCounter = 0;
                    if (this.frame >= 4)
                    {
                        this.frame = 0;
                    }
                }
                Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 0.5f, 0.2f, 1.1f);
            }
            if (this.type == 684)
            {
                this.alpha -= 40;
                if (this.alpha < 0)
                {
                    this.alpha = 0;
                }
                this.spriteDirection = this.direction;
                this.localAI[0] += 1f;
                for (int num69 = 0; num69 < 1; num69++)
                {
                    Vector2 vector23 = Utils.RandomVector2(Main.rand, -0.5f, 0.5f) * new Vector2(20f, 80f);
                    vector23 = vector23.RotatedBy((double)this.velocity.ToRotation(), default(Vector2));
                    Dust dust7 = Dust.NewDustDirect(base.Center, 0, 0, 60, 0f, 0f, 0, default(Color), 1f);
                    dust7.alpha = 127;
                    dust7.fadeIn = 1.5f;
                    dust7.scale = 1.3f;
                    dust7.velocity *= 0.3f;
                    dust7.position = base.Center + vector23;
                    dust7.noGravity = true;
                    dust7.noLight = true;
                    dust7.color = new Color(255, 255, 255, 0);
                }
                Lighting.AddLight(base.Center, 1.1f, 0.3f, 0.4f);
            }
            if (this.type == 408)
            {
                this.alpha -= 40;
                if (this.alpha < 0)
                {
                    this.alpha = 0;
                }
                this.spriteDirection = this.direction;
            }
            if (this.type == 282)
            {
                int num70 = Dust.NewDust(this.position, this.width, this.height, 171, 0f, 0f, 100, default(Color), 1f);
                Main.dust[num70].scale = (float)Main.rand.Next(1, 10) * 0.1f;
                Main.dust[num70].noGravity = true;
                Main.dust[num70].fadeIn = 1.5f;
                Main.dust[num70].velocity *= 0.25f;
                Main.dust[num70].velocity += this.velocity * 0.25f;
            }
            if (this.type == 275 || this.type == 276)
            {
                this.frameCounter++;
                if (this.frameCounter > 1)
                {
                    this.frameCounter = 0;
                    this.frame++;
                    if (this.frame > 1)
                    {
                        this.frame = 0;
                    }
                }
            }
            if (this.type == 225 && Main.rand.Next(2) == 0)
            {
                int num71 = Dust.NewDust(new Vector2(this.position.X, this.position.Y), this.width, this.height, 40, 0f, 0f, 0, default(Color), 1f);
                Main.dust[num71].noGravity = true;
                Main.dust[num71].scale = 1.3f;
                Main.dust[num71].velocity *= 0.5f;
            }
            if (this.type == 174)
            {
                if (this.alpha == 0)
                {
                    int num72 = Dust.NewDust(this.oldPosition - this.velocity * 3f, this.width, this.height, 76, 0f, 0f, 50, default(Color), 1f);
                    Main.dust[num72].noGravity = true;
                    Main.dust[num72].noLight = true;
                    Main.dust[num72].velocity *= 0.5f;
                }
                this.alpha -= 50;
                if (this.alpha < 0)
                {
                    this.alpha = 0;
                }
                if (this.ai[1] == 0f)
                {
                    this.ai[1] = 1f;
                    SoundEngine.PlaySound(SoundID.Item17, this.position, 0f, 1f);
                }
            }
            else if (this.type == 605 || this.type == 920 || this.type == 921 || this.type == 926 || this.type == 937)
            {
                if (this.type == 920 && this.frameCounter == 0)
                {
                    this.frameCounter = 1;
                    this.frame = Main.rand.Next(3);
                }
                if (this.type != 920 && this.type != 921 && this.alpha == 0 && Main.rand.Next(3) == 0)
                {
                    int num73 = 4;
                    Color color3 = new Color(78, 136, 255, 150);
                    float num74 = 1.2f;
                    bool flag = true;
                    int num75 = 0;
                    if (this.type == 921)
                    {
                        num73 = 243;
                        color3 = default(Color);
                    }
                    if (this.type == 926)
                    {
                        num73 = 4;
                        color3 = NPC.AI_121_QueenSlime_GetDustColor();
                        color3.A = 150;
                        num74 = 1.2f;
                        num75 = 8;
                        flag = Main.rand.Next(2) == 0;
                    }
                    if (this.type == 937)
                    {
                        num73 = 4;
                        color3 = NPC.AI_121_QueenSlime_GetDustColor();
                        color3.A = 150;
                    }
                    int num76 = Dust.NewDust(this.position - new Vector2((float)num75, (float)num75) + this.velocity, this.width + num75 * 2, this.height + num75 * 2, num73, 0f, 0f, 50, color3, num74);
                    Main.dust[num76].velocity *= 0.3f;
                    Main.dust[num76].velocity += this.velocity * 0.3f;
                    Main.dust[num76].noGravity = flag;
                }
                this.alpha -= 50;
                if (this.alpha < 0)
                {
                    this.alpha = 0;
                }
                if (this.type != 937 && this.ai[1] == 0f)
                {
                    this.ai[1] = 1f;
                    if (this.type == 926)
                    {
                        SoundEngine.PlaySound(SoundID.Item155, this.position, 0f, 1f);
                    }
                    else
                    {
                        SoundEngine.PlaySound(SoundID.Item154, this.position, 0f, 1f);
                    }
                }
            }
            else if (this.type == 176)
            {
                if (this.alpha == 0)
                {
                    int num77 = Dust.NewDust(this.oldPosition, this.width, this.height, 22, 0f, 0f, 100, default(Color), 0.5f);
                    Main.dust[num77].noGravity = true;
                    Main.dust[num77].noLight = true;
                    Main.dust[num77].velocity *= 0.15f;
                    Main.dust[num77].fadeIn = 0.8f;
                }
                this.alpha -= 50;
                if (this.alpha < 0)
                {
                    this.alpha = 0;
                }
                if (this.ai[1] == 0f)
                {
                    this.ai[1] = 1f;
                    SoundEngine.PlaySound(SoundID.Item17, this.position, 0f, 1f);
                }
            }
            if (this.type == 350)
            {
                this.alpha -= 100;
                if (this.alpha < 0)
                {
                    this.alpha = 0;
                }
                Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 0.9f, 0.6f, 0.2f);
                if (this.alpha == 0)
                {
                    int num78 = 2;
                    if (Main.rand.Next(3) != 0)
                    {
                        int num79 = Dust.NewDust(new Vector2(base.Center.X - (float)num78, base.Center.Y - (float)num78 - 2f) - this.velocity * 0.5f, num78 * 2, num78 * 2, 6, 0f, 0f, 100, default(Color), 1f);
                        Main.dust[num79].scale *= 1.3f + (float)Main.rand.Next(10) * 0.05f;
                        Main.dust[num79].velocity *= 0.2f;
                        Main.dust[num79].noGravity = true;
                        Main.dust[num79].noLight = true;
                        Main.dust[num79].velocity += this.velocity * 0.25f;
                    }
                    if (Main.rand.Next(4) == 0)
                    {
                        int num80 = Dust.NewDust(new Vector2(base.Center.X - (float)num78, base.Center.Y - (float)num78 - 2f) - this.velocity * 0.5f, num78 * 2, num78 * 2, 31, 0f, 0f, 100, default(Color), 0.5f);
                        Main.dust[num80].fadeIn = 0.6f + (float)Main.rand.Next(5) * 0.1f;
                        Main.dust[num80].velocity *= 0.05f;
                        Main.dust[num80].velocity += this.velocity * 0.25f;
                    }
                }
                if (this.ai[1] == 0f)
                {
                    this.ai[1] = 1f;
                    SoundEngine.PlaySound(SoundID.Item42, this.position, 0f, 1f);
                }
            }
            if (this.type == 325)
            {
                this.alpha -= 100;
                if (this.alpha < 0)
                {
                    this.alpha = 0;
                }
                Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 0.9f, 0.6f, 0.2f);
                if (this.alpha == 0)
                {
                    int num81 = 2;
                    if (Main.rand.Next(3) != 0)
                    {
                        int num82 = Dust.NewDust(new Vector2(base.Center.X - (float)num81, base.Center.Y - (float)num81 - 2f) - this.velocity * 0.5f, num81 * 2, num81 * 2, 6, 0f, 0f, 100, default(Color), 1f);
                        Main.dust[num82].scale *= 1.2f + (float)Main.rand.Next(10) * 0.05f;
                        Main.dust[num82].velocity *= 0.2f;
                        Main.dust[num82].noGravity = true;
                        Main.dust[num82].noLight = true;
                        Main.dust[num82].velocity += this.velocity * 0.25f;
                    }
                    if (Main.rand.Next(4) == 0)
                    {
                        int num83 = Dust.NewDust(new Vector2(base.Center.X - (float)num81, base.Center.Y - (float)num81 - 2f) - this.velocity * 0.5f, num81 * 2, num81 * 2, 31, 0f, 0f, 100, default(Color), 0.5f);
                        Main.dust[num83].fadeIn = 0.5f + (float)Main.rand.Next(5) * 0.05f;
                        Main.dust[num83].velocity *= 0.05f;
                    }
                }
                if (this.ai[1] == 0f)
                {
                    this.ai[1] = 1f;
                    SoundEngine.PlaySound(SoundID.Item42, this.position, 0f, 1f);
                }
            }
            if (this.type == 469)
            {
                this.localAI[1] += 1f;
                if (this.localAI[1] > 2f)
                {
                    this.alpha -= 50;
                    if (this.alpha < 0)
                    {
                        this.alpha = 0;
                    }
                }
            }
            else if (this.type == 1023 && this.ai[1] == 0f)
            {
                this.ai[1] = 1f;
                Vector2 velocity = Main.player[this.owner].velocity;
                float num84 = Utils.Remap(velocity.Length(), 0f, 3f, 0f, 0.5f, true);
                Vector2 vector24 = base.Center + this.velocity.SafeNormalize(Vector2.Zero) * 54f;
                vector24 += new Vector2(0f, -4f) * Main.player[this.owner].Directions;
                for (int num85 = 0; num85 < 25; num85++)
                {
                    Dust dust8 = Dust.NewDustDirect(vector24, 16, 8, 31, this.velocity.X, this.velocity.Y, 50, default(Color), 1f + Main.rand.NextFloat() * 0.3f);
                    dust8.position = vector24;
                    dust8.position += new Vector2(0f, Main.rand.NextFloatDirection() * 10f).RotatedBy((double)this.velocity.ToRotation(), default(Vector2));
                    dust8.velocity = (this.velocity * (0.2f + num84)).RotatedByRandom(0.19634954631328583) + velocity * 0.25f;
                    dust8.velocity *= 3f;
                    dust8.velocity *= Main.rand.NextFloat();
                    dust8.fadeIn = 0.1f;
                    dust8.position -= dust8.velocity;
                    dust8.noGravity = true;
                }
            }
            else if (this.type == 83 && this.ai[1] == 0f)
            {
                this.ai[1] = 1f;
                SoundEngine.PlaySound(SoundID.Item33, this.position, 0f, 1f);
            }
            else if (this.type == 408 && this.ai[1] == 0f)
            {
                this.ai[1] = 1f;
                SoundEngine.PlaySound(4, (int)this.position.X, (int)this.position.Y, 19, 1f, 0f);
            }
            else if (this.type == 259 && this.ai[1] == 0f)
            {
                this.ai[1] = 1f;
                SoundEngine.PlaySound(SoundID.Item33, this.position, 0f, 1f);
            }
            else if (this.type == 110 && this.ai[1] == 0f)
            {
                this.ai[1] = 1f;
                SoundEngine.PlaySound(SoundID.Item11, this.position, 0f, 1f);
            }
            else if (this.type == 302 && this.ai[1] == 0f)
            {
                this.ai[1] = 1f;
                SoundEngine.PlaySound(SoundID.Item11, this.position, 0f, 1f);
            }
            else if (this.type == 438 && this.ai[1] == 0f)
            {
                this.ai[1] = 1f;
                SoundEngine.PlaySound(SoundID.Item12, this.position, 0f, 1f);
            }
            else if (this.type == 593 && this.ai[1] == 0f)
            {
                this.ai[1] = 1f;
                SoundEngine.PlaySound(SoundID.Item11, this.position, 0f, 1f);
            }
            else if (this.type == 592 && this.ai[1] == 0f)
            {
                this.ai[1] = 1f;
                SoundEngine.PlaySound(SoundID.Item12, this.position, 0f, 1f);
            }
            else if (this.type == 462 && this.ai[1] == 0f)
            {
                this.ai[1] = 1f;
                if (Main.rand.Next(2) == 0)
                {
                    SoundEngine.PlaySound(SoundID.Item124, this.position, 0f, 1f);
                }
                else
                {
                    SoundEngine.PlaySound(SoundID.Item125, this.position, 0f, 1f);
                }
                Vector2 vector25 = Vector2.Normalize(this.velocity);
                int num86 = Main.rand.Next(5, 10);
                for (int num87 = 0; num87 < num86; num87++)
                {
                    int num88 = Dust.NewDust(base.Center, 0, 0, 229, 0f, 0f, 100, default(Color), 1f);
                    Dust dust9 = Main.dust[num88];
                    dust9.velocity.Y = dust9.velocity.Y - 1f;
                    Main.dust[num88].velocity += vector25 * 2f;
                    Main.dust[num88].position -= Vector2.One * 4f;
                    Main.dust[num88].noGravity = true;
                }
            }
            else if (this.type == 84 && this.ai[1] == 0f)
            {
                this.ai[1] = 1f;
                SoundEngine.PlaySound(SoundID.Item12, this.position, 0f, 1f);
            }
            else if (this.type == 389 && this.ai[1] == 0f)
            {
                this.ai[1] = 1f;
                SoundEngine.PlaySound(SoundID.Item12, this.position, 0f, 1f);
            }
            else if (this.type == 257 && this.ai[1] == 0f)
            {
                this.ai[1] = 1f;
                SoundEngine.PlaySound(SoundID.Item12, this.position, 0f, 1f);
            }
            else if (this.type == 100 && this.ai[1] == 0f)
            {
                this.ai[1] = 1f;
                SoundEngine.PlaySound(SoundID.Item33, this.position, 0f, 1f);
            }
            else if (this.type == 98 && this.ai[1] == 0f)
            {
                this.ai[1] = 1f;
                SoundEngine.PlaySound(SoundID.Item17, this.position, 0f, 1f);
            }
            else if (this.type == 1073 && this.ai[1] == 0f)
            {
                this.ai[1] = 1f;
                SoundEngine.PlaySound(SoundID.Item17, this.position, 0f, 1f);
            }
            else if (this.type == 184 && this.ai[1] == 0f)
            {
                this.ai[1] = 1f;
                SoundEngine.PlaySound(SoundID.Item17, this.position, 0f, 1f);
            }
            else if (this.type == 980 && this.ai[1] == 0f)
            {
                this.ai[1] = 1f;
                SoundEngine.PlaySound(SoundID.Item17, this.position, 0f, 1f);
            }
            else if (this.type == 195 && this.ai[1] == 0f)
            {
                this.ai[1] = 1f;
                SoundEngine.PlaySound(SoundID.Item17, this.position, 0f, 1f);
            }
            else if (this.type == 1097 && this.ai[1] == 0f)
            {
                this.ai[1] = 1f;
                SoundEngine.PlaySound(SoundID.Item20, this.position, 0f, 1f);
            }
            else if (this.type == 275 && this.ai[1] == 0f)
            {
                this.ai[1] = 1f;
                SoundEngine.PlaySound(SoundID.Item17, this.position, 0f, 1f);
            }
            else if (this.type == 276 && this.ai[1] == 0f)
            {
                this.ai[1] = 1f;
                SoundEngine.PlaySound(SoundID.Item17, this.position, 0f, 1f);
            }
            else if ((this.type == 81 || this.type == 82) && this.ai[1] == 0f)
            {
                SoundEngine.PlaySound(SoundID.Item5, this.position, 0f, 1f);
                this.ai[1] = 1f;
            }
            else if (this.type == 180 && this.ai[1] == 0f)
            {
                SoundEngine.PlaySound(SoundID.Item11, this.position, 0f, 1f);
                this.ai[1] = 1f;
            }
            else if (this.type == 248 && this.ai[1] == 0f)
            {
                SoundEngine.PlaySound(SoundID.Item17, this.position, 0f, 1f);
                this.ai[1] = 1f;
            }
            else if (this.type == 576 && this.ai[1] == 0f)
            {
                this.ai[1] = 1f;
                SoundEngine.PlaySound(SoundID.Item12, this.position, 0f, 1f);
            }
            else if (this.type == 577 && this.soundDelay == 0)
            {
                this.soundDelay = -1;
                SoundEngine.PlaySound(SoundID.Item36, this.position, 0f, 1f);
                for (int num89 = 0; num89 < 5; num89++)
                {
                    Vector2 center4 = base.Center;
                    int num90 = ((num89 == 0) ? 0 : 3);
                    float num91 = ((num89 == 0) ? (12f + 8f * Main.rand.NextFloat()) : (12f * Main.rand.NextFloat()));
                    Vector2 vector26 = this.velocity.SafeNormalize(Vector2.Zero) * num91 + Main.rand.NextVector2Circular(1f, 1f) * (float)num90;
                    Dust dust10 = Main.dust[Dust.NewDust(center4, 8, 8, 229, 0f, 0f, 100, Color.Transparent, 1f + Main.rand.NextFloat() * 0.5f)];
                    dust10.noGravity = true;
                    dust10.velocity = vector26;
                    dust10.position = center4;
                }
            }
            else if (this.type == 710)
            {
                this.alpha -= 25;
                if (this.alpha < 0)
                {
                    this.alpha = 0;
                }
                if (Main.rand.Next(4) == 0)
                {
                    int num92;
                    if (Main.rand.Next(2) == 0)
                    {
                        num92 = Dust.NewDust(this.position, this.width, this.height, 31, 0f, 0f, 100, default(Color), 1.6f);
                        Main.dust[num92].noGravity = true;
                    }
                    num92 = Dust.NewDust(this.position, this.width, this.height, 6, 0f, 0f, 100, default(Color), 1.2f);
                    Main.dust[num92].noGravity = true;
                    Main.dust[num92].velocity *= 2f;
                    Main.dust[num92].velocity += this.velocity;
                    if (this.ai[1] == -1f)
                    {
                        Main.dust[num92].fadeIn = 1.5f;
                    }
                    else
                    {
                        Main.dust[num92].fadeIn = 1.22f;
                    }
                    if (this.wet)
                    {
                        this.Kill();
                    }
                }
            }
            else if (this.type == 639)
            {
                if (this.localAI[0] == 0f && this.localAI[1] == 0f)
                {
                    this.localAI[0] = base.Center.X;
                    this.localAI[1] = base.Center.Y;
                    this.ai[0] = this.velocity.X;
                    this.ai[1] = this.velocity.Y;
                }
                this.alpha -= 25;
                if (this.alpha < 0)
                {
                    this.alpha = 0;
                }
            }
            else if (this.type == 640)
            {
                this.alpha -= 25;
                if (this.alpha < 0)
                {
                    this.alpha = 0;
                }
                if (this.velocity == Vector2.Zero)
                {
                    this.ai[0] = 0f;
                    bool flag2 = true;
                    for (int num93 = 1; num93 < this.oldPos.Length; num93++)
                    {
                        if (this.oldPos[num93] != this.oldPos[0])
{
                            flag2 = false;
                        }
                    }
                    if (flag2)
                    {
                        this.Kill();
                        return;
                    }
                    if (Main.rand.Next(this.extraUpdates) == 0 && (this.velocity != Vector2.Zero || Main.rand.Next((this.localAI[1] == 2f) ? 2 : 6) == 0))
                    {
                        for (int num94 = 0; num94 < 2; num94++)
{
                            float num95 = this.rotation + ((Main.rand.Next(2) == 1) ? (-1f) : 1f) * 1.5707964f;
                            float num96 = (float)Main.rand.NextDouble() * 0.8f + 1f;
                            Vector2 vector27 = new Vector2((float)Math.Cos((double)num95) * num96, (float)Math.Sin((double)num95) * num96);
                            int num97 = Dust.NewDust(base.Center, 0, 0, 229, vector27.X, vector27.Y, 0, default(Color), 1f);
                            Main.dust[num97].noGravity = true;
                            Main.dust[num97].scale = 1.2f;
                        }
                        if (Main.rand.Next(10) == 0)
{
                            Vector2 vector28 = this.velocity.RotatedBy(1.5707963705062866, default(Vector2)) * ((float)Main.rand.NextDouble() - 0.5f) * (float)this.width;
                            int num98 = Dust.NewDust(base.Center + vector28 - Vector2.One * 4f, 8, 8, 31, 0f, 0f, 100, default(Color), 1.5f);
                            Main.dust[num98].velocity *= 0.5f;
                            Main.dust[num98].velocity.Y = -Math.Abs(Main.dust[num98].velocity.Y);
                        }
                    }
                }
                else if (this.numUpdates == 1)
                {
                    float num99 = this.rotation + 1.5707964f + ((Main.rand.Next(2) == 1) ? (-1f) : 1f) * 1.5707964f;
                    float num100 = (float)Main.rand.NextDouble() * 0.25f + 0.25f;
                    Vector2 vector29 = new Vector2((float)Math.Cos((double)num99) * num100, (float)Math.Sin((double)num99) * num100);
                    int num101 = Dust.NewDust(this.position, 0, 0, 229, vector29.X, vector29.Y, 0, default(Color), 1f);
                    Main.dust[num101].noGravity = true;
                    Main.dust[num101].scale = 1.2f;
                }
            }
            if (this.type == 41)
            {
                int num102 = Dust.NewDust(new Vector2(this.position.X, this.position.Y), this.width, this.height, 31, 0f, 0f, 100, default(Color), 1.6f);
                Main.dust[num102].noGravity = true;
                num102 = Dust.NewDust(new Vector2(this.position.X, this.position.Y), this.width, this.height, 6, 0f, 0f, 100, default(Color), 2f);
                Main.dust[num102].noGravity = true;
            }
            else if (this.type == 55)
            {
                int num103 = Dust.NewDust(new Vector2(this.position.X, this.position.Y), this.width, this.height, 18, 0f, 0f, 0, default(Color), 0.9f);
                Main.dust[num103].noGravity = true;
            }
            else if (this.type == 719)
            {
                if (Main.rand.Next(2) == 0)
                {
                    Dust.NewDustDirect(this.position - this.velocity, this.width, this.height, 147, 0f, 0f, 0, default(Color), 0.9f).noGravity = true;
                }
                if (this.localAI[0] == 0f)
                {
                    this.localAI[0] = 1f;
                    for (int num104 = 0; num104 < 20; num104++)
                    {
                        Dust dust11 = Dust.NewDustDirect(this.position - this.velocity, this.width, this.height, 147, 0f, 0f, 0, default(Color), 1.3f);
                        dust11.noGravity = true;
                        dust11.velocity += this.velocity * 0.75f;
                    }
                    for (int num105 = 0; num105 < 10; num105++)
                    {
                        Dust dust12 = Dust.NewDustDirect(this.position - this.velocity, this.width, this.height, 147, 0f, 0f, 0, default(Color), 1.3f);
                        dust12.noGravity = true;
                        dust12.velocity *= 2f;
                    }
                }
            }
            else if (this.type == 763)
            {
                if (this.localAI[0] == 0f)
                {
                    this.localAI[0] = 1f;
                    for (int num106 = 0; num106 < 5; num106++)
                    {
                        Dust dust13 = Dust.NewDustDirect(this.position - this.velocity, this.width, this.height, 40, 0f, 0f, 0, default(Color), 1.1f);
                        dust13.noGravity = true;
                        dust13.velocity *= 1.5f;
                    }
                }
            }
            else if (this.type == 772)
            {
                if (Main.rand.Next(7) == 0)
                {
                    for (int num107 = 0; num107 < 1; num107++)
                    {
                        Dust dust14 = Dust.NewDustDirect(this.position - this.velocity, this.width, this.height, Main.rand.NextFromList(new int[] { 86, 87, 88, 89, 90, 91, 138 }), 0f, 0f, 0, default(Color), 0.7f);
                        dust14.noGravity = true;
                        dust14.velocity = this.velocity * 0.6f;
                        dust14.fadeIn = 0.8f;
                    }
                }
            }
            else if (this.type == 374)
            {
                if (this.localAI[0] == 0f)
                {
                    SoundEngine.PlaySound(SoundID.Item17, this.position, 0f, 1f);
                    this.localAI[0] = 1f;
                }
                if (Main.rand.Next(2) == 0)
                {
                    int num108 = Dust.NewDust(new Vector2(this.position.X, this.position.Y), this.width, this.height, 18, 0f, 0f, 0, default(Color), 0.9f);
                    Main.dust[num108].noGravity = true;
                    Main.dust[num108].velocity *= 0.5f;
                }
            }
            else if (this.type == 376)
            {
                if (this.localAI[0] == 0f)
                {
                    SoundEngine.PlaySound(SoundID.Item20, this.position, 0f, 1f);
                }
                this.localAI[0] += 1f;
                if (this.localAI[0] > 3f)
                {
                    int num109 = 1;
                    if (this.localAI[0] > 5f)
                    {
                        num109 = 2;
                    }
                    for (int num110 = 0; num110 < num109; num110++)
                    {
                        int num111 = Dust.NewDust(new Vector2(this.position.X, this.position.Y + 2f), this.width, this.height, 6, this.velocity.X * 0.2f, this.velocity.Y * 0.2f, 100, default(Color), 2f);
                        Main.dust[num111].noGravity = true;
                        Dust dust15 = Main.dust[num111];
                        dust15.velocity.X = dust15.velocity.X * 0.3f;
                        Dust dust16 = Main.dust[num111];
                        dust16.velocity.Y = dust16.velocity.Y * 0.3f;
                        Main.dust[num111].noLight = true;
                    }
                    if (this.wet && !this.lavaWet)
                    {
                        this.Kill();
                        return;
                    }
                }
            }
            else if (this.type == 91 && Main.rand.Next(2) == 0)
            {
                int num112;
                if (Main.rand.Next(2) == 0)
                {
                    num112 = 15;
                }
                else
                {
                    num112 = 58;
                }
                int num113 = Dust.NewDust(this.position, this.width, this.height, num112, this.velocity.X * 0.25f, this.velocity.Y * 0.25f, 150, default(Color), 0.9f);
                Main.dust[num113].velocity *= 0.25f;
            }
            if (this.type == 163 || this.type == 310 || this.type == 1008 || this.type == 1010 || this.type == 1009 || this.type == 1011)
            {
                if (this.alpha > 0)
                {
                    this.alpha -= 25;
                }
                if (this.alpha < 0)
                {
                    this.alpha = 0;
                }
            }
            num = this.type;
            if (num <= 104)
            {
                if (num <= 36)
                {
                    if (num != 14 && num != 20 && num != 36)
                    {
                        goto IL_56DB;
                    }
                }
                else if (num <= 89)
                {
                    if (num - 83 > 1 && num != 89)
                    {
                        goto IL_56DB;
                    }
                }
                else if (num != 100 && num != 104)
                {
                    goto IL_56DB;
                }
            }
            else if (num <= 180)
            {
                if (num != 110 && num - 158 > 3 && num != 180)
                {
                    goto IL_56DB;
                }
            }
            else if (num <= 287)
            {
                if (num != 279 && num - 283 > 4)
                {
                    goto IL_56DB;
                }
            }
            else if (num != 389)
            {
                if (num - 576 > 1)
                {
                    goto IL_56DB;
                }
                this.localAI[1] += 1f;
                if (this.localAI[1] <= 2f)
                {
                    goto IL_56DB;
                }
                if (this.alpha > 0)
                {
                    this.alpha -= 15;
                }
                if (this.alpha < 0)
                {
                    this.alpha = 0;
                    goto IL_56DB;
                }
                goto IL_56DB;
            }
            if (this.alpha > 0)
            {
                this.alpha -= 15;
            }
            if (this.alpha < 0)
            {
                this.alpha = 0;
            }
            IL_56DB:
            if (this.type == 484)
            {
                int num114 = Dust.NewDust(this.position, this.width, this.height, 78, 0f, 0f, 0, default(Color), 1f);
                Main.dust[num114].noGravity = true;
                Main.dust[num114].velocity *= 0.1f;
                Main.dust[num114].scale = 0.75f;
                Main.dust[num114].position = (Main.dust[num114].position + base.Center) / 2f;
                Main.dust[num114].position += this.velocity * (float)Main.rand.Next(0, 101) * 0.01f;
            }
            if (this.type == 242 || this.type == 302 || this.type == 438 || this.type == 462 || this.type == 592)
            {
                float num115 = (float)Math.Sqrt((double)(this.velocity.X * this.velocity.X + this.velocity.Y * this.velocity.Y));
                if (this.alpha > 0)
                {
                    this.alpha -= (int)((byte)((double)num115 * 0.9));
                }
                if (this.alpha < 0)
                {
                    this.alpha = 0;
                }
            }
            if (this.type == 660)
            {
                DelegateMethods.v3_1 = new Vector3(0.6f, 1f, 1f) * 0.2f;
                Utils.PlotTileLine(base.Center, base.Center + this.velocity * 10f, 8f, new Utils.TileActionAttempt(DelegateMethods.CastLightOpen));
                if (this.alpha > 0)
                {
                    SoundEngine.PlaySound(SoundID.Item9, base.Center, 0f, 1f);
                    this.alpha = 0;
                    this.scale = 1.1f;
                    this.frame = Main.rand.Next(14);
                    float num116 = 16f;
                    int num117 = 0;
                    while ((float)num117 < num116)
                    {
                        Vector2 vector30 = Vector2.UnitX * 0f;
                        vector30 += -Vector2.UnitY.RotatedBy((double)((float)num117 * (6.2831855f / num116)), default(Vector2)) * new Vector2(1f, 4f);
                        vector30 = vector30.RotatedBy((double)this.velocity.ToRotation(), default(Vector2));
                        int num118 = Dust.NewDust(base.Center, 0, 0, 180, 0f, 0f, 0, default(Color), 1f);
                        Main.dust[num118].scale = 1.5f;
                        Main.dust[num118].noGravity = true;
                        Main.dust[num118].position = base.Center + vector30;
                        Main.dust[num118].velocity = this.velocity * 0f + vector30.SafeNormalize(Vector2.UnitY) * 1f;
                        num117++;
                    }
                }
            }
            if (this.type == 712)
            {
                DelegateMethods.v3_1 = new Vector3(0.4f, 0.4f, 0.4f) * 0.7f;
                Utils.PlotTileLine(base.Center, base.Center + this.velocity * 10f, 8f, new Utils.TileActionAttempt(DelegateMethods.CastLightOpen));
                if (this.alpha == 255)
                {
                    this.frame = Main.rand.Next(2) * 4;
                }
                num = this.frameCounter + 1;
                this.frameCounter = num;
                if (num >= 4)
                {
                    this.frameCounter = 0;
                    this.frame++;
                    if (this.frame == 4)
                    {
                        this.frame = 0;
                    }
                    if (this.frame >= 8)
                    {
                        this.frame = 4;
                    }
                }
                if (this.alpha > 0)
                {
                    this.alpha = 0;
                    this.scale = 1.1f;
                    this.frame = Main.rand.Next(14);
                    float num119 = 4f;
                    int num120 = 0;
                    while ((float)num120 < num119)
                    {
                        Vector2 vector31 = Vector2.UnitX * 0f;
                        vector31 += -Vector2.UnitY.RotatedBy((double)((float)num120 * (6.2831855f / num119)), default(Vector2)) * new Vector2(1f, 4f);
                        vector31 = vector31.RotatedBy((double)this.velocity.ToRotation(), default(Vector2));
                        int num121 = Dust.NewDust(base.Center, 0, 0, 15, 0f, 0f, 0, default(Color), 1f);
                        Main.dust[num121].scale = 1.7f;
                        Main.dust[num121].noGravity = true;
                        Main.dust[num121].position = base.Center + vector31 + this.velocity.SafeNormalize(Vector2.Zero) * 50f;
                        Main.dust[num121].velocity = Main.dust[num121].velocity * 2f + vector31.SafeNormalize(Vector2.UnitY) * 0.3f + this.velocity.SafeNormalize(Vector2.Zero) * 3f;
                        Main.dust[num121].velocity *= 0.7f;
                        Main.dust[num121].position += Main.dust[num121].velocity * 5f;
                        num120++;
                    }
                }
            }
            if (this.type == 661)
            {
                if (this.alpha <= 0)
                {
                    for (int num122 = 0; num122 < 3; num122++)
                    {
                        int num123 = Dust.NewDust(this.position, this.width, this.height, 240, 0f, 0f, 0, default(Color), 1f);
                        Main.dust[num123].noGravity = true;
                        Main.dust[num123].velocity *= 0.3f;
                        Main.dust[num123].noLight = true;
                    }
                }
                if (this.alpha > 0)
                {
                    this.alpha -= 55;
                    this.scale = 1.3f;
                    if (this.alpha < 0)
                    {
                        this.alpha = 0;
                        float num124 = 16f;
                        int num125 = 0;
                        while ((float)num125 < num124)
{
                            Vector2 vector32 = Vector2.UnitX * 0f;
                            vector32 += -Vector2.UnitY.RotatedBy((double)((float)num125 * (6.2831855f / num124)), default(Vector2)) * new Vector2(1f, 4f);
                            vector32 = vector32.RotatedBy((double)this.velocity.ToRotation(), default(Vector2));
                            int num126 = Dust.NewDust(base.Center, 0, 0, 62, 0f, 0f, 0, default(Color), 1f);
                            Main.dust[num126].scale = 1.5f;
                            Main.dust[num126].noLight = true;
                            Main.dust[num126].noGravity = true;
                            Main.dust[num126].position = base.Center + vector32;
                            Main.dust[num126].velocity = Main.dust[num126].velocity * 4f + this.velocity * 0.3f;
                            num125++;
                        }
                    }
                }
            }
            if (this.type == 706)
            {
                if (this.wet)
                {
                    this.Kill();
                    return;
                }
                if (this.localAI[1] == 0f)
                {
                    this.localAI[0] = SoundEngine.PlayTrackedSound(SoundID.DD2_PhantomPhoenixShot, base.Center, default(SoundPlayOverrides)).ToFloat();
                    this.localAI[1] += 1f;
                    for (int num127 = 0; num127 < 15; num127++)
                    {
                        if (Main.rand.Next(4) != 0)
{
                            Dust dust17 = Dust.NewDustDirect(base.Center - base.Size / 4f, this.width / 2, this.height / 2, Utils.SelectRandom<int>(Main.rand, new int[] { 6, 31, 31 }), 0f, 0f, 0, default(Color), 1f);
                            dust17.noGravity = true;
                            dust17.velocity *= 2.3f;
                            dust17.fadeIn = 1.5f;
                            dust17.noLight = true;
                        }
                    }
                }
                ActiveSound activeSound = SoundEngine.GetActiveSound(SlotId.FromFloat(this.localAI[0]));
                if (activeSound != null)
                {
                    activeSound.Position = base.Center;
                }
                else
                {
                    float[] array = this.localAI;
                    int num128 = 0;
                    SlotId invalid = SlotId.Invalid;
                    array[num128] = invalid.ToFloat();
                }
                if (this.alpha <= 0)
                {
                    for (int num129 = 0; num129 < 2; num129++)
                    {
                        if (Main.rand.Next(4) != 0)
{
                            Dust dust18 = Dust.NewDustDirect(base.Center - base.Size / 4f, this.width / 2, this.height / 2, Utils.SelectRandom<int>(Main.rand, new int[] { 6, 31, 31 }), 0f, 0f, 0, default(Color), 1f);
                            dust18.noGravity = true;
                            dust18.velocity *= 2.3f;
                            dust18.fadeIn = 1.5f;
                            dust18.noLight = true;
                        }
                    }
                    Vector2 vector33 = new Vector2(0f, (float)Math.Cos((double)((float)this.frameCounter * 6.2831855f / 40f - 1.5707964f))) * 16f;
                    vector33 = vector33.RotatedBy((double)this.rotation, default(Vector2));
                    Vector2 vector34 = this.velocity.SafeNormalize(Vector2.Zero);
                    for (int num130 = 0; num130 < 1; num130++)
                    {
                        Dust dust19 = Dust.NewDustDirect(base.Center - base.Size / 4f, this.width / 2, this.height / 2, 6, 0f, 0f, 0, default(Color), 1f);
                        dust19.noGravity = true;
                        dust19.position = base.Center + vector33;
                        dust19.velocity *= 0f;
                        dust19.fadeIn = 1.4f;
                        dust19.scale = 1.15f;
                        dust19.noLight = true;
                        dust19.position += this.velocity * 1.2f;
                        dust19.velocity += vector34 * 2f;
                        Dust dust20 = Dust.NewDustDirect(base.Center - base.Size / 4f, this.width / 2, this.height / 2, 6, 0f, 0f, 0, default(Color), 1f);
                        dust20.noGravity = true;
                        dust20.position = base.Center + vector33;
                        dust20.velocity *= 0f;
                        dust20.fadeIn = 1.4f;
                        dust20.scale = 1.15f;
                        dust20.noLight = true;
                        dust20.position += this.velocity * 0.5f;
                        dust20.position += this.velocity * 1.2f;
                        dust20.velocity += vector34 * 2f;
                    }
                }
                num = this.frameCounter + 1;
                this.frameCounter = num;
                if (num >= 40)
                {
                    this.frameCounter = 0;
                }
                this.frame = this.frameCounter / 5;
                if (this.alpha > 0)
                {
                    this.alpha -= 55;
                    if (this.alpha < 0)
                    {
                        this.alpha = 0;
                        float num131 = 16f;
                        int num132 = 0;
                        while ((float)num132 < num131)
{
                            Vector2 vector35 = Vector2.UnitX * 0f;
                            vector35 += -Vector2.UnitY.RotatedBy((double)((float)num132 * (6.2831855f / num131)), default(Vector2)) * new Vector2(1f, 4f);
                            vector35 = vector35.RotatedBy((double)this.velocity.ToRotation(), default(Vector2));
                            int num133 = Dust.NewDust(base.Center, 0, 0, 6, 0f, 0f, 0, default(Color), 1f);
                            Main.dust[num133].scale = 1.5f;
                            Main.dust[num133].noLight = true;
                            Main.dust[num133].noGravity = true;
                            Main.dust[num133].position = base.Center + vector35;
                            Main.dust[num133].velocity = Main.dust[num133].velocity * 4f + this.velocity * 0.3f;
                            num132++;
                        }
                    }
                }
                DelegateMethods.v3_1 = new Vector3(1f, 0.6f, 0.2f);
                Utils.PlotTileLine(base.Center, base.Center + this.velocity * 4f, 40f, new Utils.TileActionAttempt(DelegateMethods.CastLightOpen));
            }
            if (this.type == 638)
            {
                float num134 = this.velocity.Length();
                if (this.alpha > 0)
                {
                    this.alpha -= (int)((byte)((double)num134 * 0.3));
                }
                if (this.alpha < 0)
                {
                    this.alpha = 0;
                }
                Rectangle hitbox = base.Hitbox;
                hitbox.Offset((int)this.velocity.X, (int)this.velocity.Y);
                bool flag3 = false;
                for (int num135 = 0; num135 < Main.maxNPCs; num135++)
                {
                    NPC npc = Main.npc[num135];
                    if (npc.active && !npc.dontTakeDamage && npc.immune[this.owner] == 0 && this.localNPCImmunity[num135] == 0 && npc.Hitbox.Intersects(hitbox) && !npc.friendly)
                    {
                        flag3 = true;
                        break;
                    }
                }
                if (flag3)
                {
                    int num136 = Main.rand.Next(15, 31);
                    for (int num137 = 0; num137 < num136; num137++)
                    {
                        int num138 = Dust.NewDust(base.Center, 0, 0, 229, 0f, 0f, 100, default(Color), 0.8f);
                        Main.dust[num138].velocity *= 1.6f;
                        Dust dust21 = Main.dust[num138];
                        dust21.velocity.Y = dust21.velocity.Y - 1f;
                        Main.dust[num138].velocity += this.velocity;
                        Main.dust[num138].noGravity = true;
                    }
                }
            }
            if (this.type == 257 || this.type == 593)
            {
                if (this.alpha > 0)
                {
                    this.alpha -= 10;
                }
                if (this.alpha < 0)
                {
                    this.alpha = 0;
                }
            }
            if (this.type == 876)
            {
                if (this.ai[1] == 0f)
                {
                    this.tileCollide = true;
                }
                else
                {
                    this.tileCollide = false;
                }
                if (this.alpha > 0)
                {
                    this.alpha -= 10;
                }
                if (this.alpha < 0)
                {
                    this.alpha = 0;
                }
            }
            if (this.type == 88)
            {
                if (this.alpha > 0)
                {
                    this.alpha -= 10;
                }
                if (this.alpha < 0)
                {
                    this.alpha = 0;
                }
            }
            if (this.type == 532)
            {
                this.ai[0] += 1f;
            }
            bool flag4 = true;
            bool flag5 = false;
            num = this.type;
            if (num <= 350)
            {
                if (num <= 180)
                {
                    if (num <= 84)
                    {
                        if (num <= 20)
{
                            if (num != 5 && num != 14 && num != 20)
{
                                goto IL_6C29;
                            }
                        }
                        else if (num <= 38)
{
                            if (num != 36 && num != 38)
{
                                goto IL_6C29;
                            }
                        }
                        else if (num != 55 && num - 83 > 1)
{
                            goto IL_6C29;
                        }
                    }
                    else if (num <= 100)
                    {
                        if (num - 88 > 1 && num != 98 && num != 100)
{
                            goto IL_6C29;
                        }
                    }
                    else if (num <= 110)
                    {
                        if (num != 104 && num != 110)
{
                            goto IL_6C29;
                        }
                    }
                    else if (num - 158 > 3 && num != 180)
                    {
                        goto IL_6C29;
                    }
                }
                else if (num <= 270)
                {
                    if (num <= 248)
                    {
                        if (num != 184 && num != 242 && num != 248)
{
                            goto IL_6C29;
                        }
                    }
                    else if (num <= 259)
                    {
                        if (num != 257 && num != 259)
{
                            goto IL_6C29;
                        }
                    }
                    else if (num != 265 && num != 270)
                    {
                        goto IL_6C29;
                    }
                }
                else if (num <= 299)
                {
                    if (num != 279 && num - 283 > 4 && num != 299)
                    {
                        goto IL_6C29;
                    }
                }
                else if (num <= 323)
                {
                    if (num != 302 && num != 323)
                    {
                        goto IL_6C29;
                    }
                }
                else if (num != 325 && num - 348 > 2)
                {
                    goto IL_6C29;
                }
            }
            else if (num <= 585)
            {
                if (num <= 459)
                {
                    if (num <= 376)
                    {
                        if (num != 355 && num != 374 && num != 376)
{
                            goto IL_6C29;
                        }
                    }
                    else if (num <= 442)
                    {
                        if (num != 389)
{
                            switch (num)
{
                            case 435:
                            case 436:
                            case 438:
                            case 440:
                            case 442:
                                break;
                            case 437:
                            case 439:
                            case 441:
                                goto IL_6C29;
                            default:
                                goto IL_6C29;
                            }
                        }
                    }
                    else if (num != 449 && num != 459)
                    {
                        goto IL_6C29;
                    }
                }
                else if (num <= 472)
                {
                    if (num != 462 && num - 467 > 2 && num != 472)
                    {
                        goto IL_6C29;
                    }
                }
                else if (num <= 498)
                {
                    if (num - 483 > 2 && num != 498)
                    {
                        goto IL_6C29;
                    }
                }
                else if (num - 576 > 1 && num != 585)
                {
                    goto IL_6C29;
                }
            }
            else if (num <= 661)
            {
                if (num <= 606)
                {
                    if (num - 592 > 1 && num != 601 && num != 606)
                    {
                        goto IL_6C29;
                    }
                }
                else if (num <= 635)
                {
                    if (num != 616 && num - 634 > 1)
                    {
                        goto IL_6C29;
                    }
                }
                else if (num - 638 > 1 && num - 660 > 1)
                {
                    goto IL_6C29;
                }
            }
            else if (num <= 712)
            {
                if (num != 682 && num != 684)
                {
                    switch (num)
                    {
                    case 706:
                    case 709:
                    case 710:
                    case 712:
                        break;
                    case 707:
                    case 708:
                    case 711:
                        goto IL_6C29;
                    default:
                        goto IL_6C29;
                    }
                }
            }
            else if (num <= 981)
            {
                if (num != 876 && num - 980 > 1)
                {
                    goto IL_6C29;
                }
            }
            else
            {
                if (num == 1006)
                {
                    flag5 = true;
                    goto IL_6C29;
                }
                if (num != 1073)
                {
                    goto IL_6C29;
                }
            }
            flag4 = false;
            IL_6C29:
            if (flag4)
            {
                this.ai[0] += 1f;
            }
            if (this.type == 1006 && Main.rand.Next(8) == 0)
            {
                Vector2 vector36 = this.velocity * 1.25f;
                if (this.wet)
                {
                    vector36 *= 0.5f;
                }
                Dust dust22 = Dust.NewDustPerfect(base.Center + Main.rand.NextVector2Circular(4f, 4f), 306, new Vector2?(vector36), 0, Main.hslToRgb(Main.rand.NextFloat(), 1f, 0.5f, byte.MaxValue), 1f + Main.rand.NextFloat() * 0.4f);
                dust22.noGravity = true;
                dust22.scale += 0.05f;
                Dust dust23 = Dust.CloneDust(dust22);
                dust23.color = Color.White;
                dust23.scale -= 0.3f;
            }
            if (this.type == 270)
            {
                int num139 = (int)Player.FindClosest(base.Center, 1, 1);
                this.ai[1] += 1f;
                if (this.ai[1] < 110f && this.ai[1] > 30f)
                {
                    float num140 = this.velocity.Length();
                    Vector2 vector37 = Main.player[num139].Center - base.Center;
                    vector37.Normalize();
                    vector37 *= num140;
                    this.velocity = (this.velocity * 24f + vector37) / 25f;
                    this.velocity.Normalize();
                    this.velocity *= num140;
                }
                if (this.velocity.Length() < 18f)
                {
                    this.velocity *= 1.02f;
                }
                if (this.localAI[0] == 0f)
                {
                    this.localAI[0] = 1f;
                    SoundEngine.PlaySound(SoundID.Item8, this.position, 0f, 1f);
                    for (int num141 = 0; num141 < 10; num141++)
                    {
                        int num142 = Dust.NewDust(new Vector2(this.position.X, this.position.Y), this.width, this.height, 5, this.velocity.X, this.velocity.Y, 0, default(Color), 2f);
                        Main.dust[num142].noGravity = true;
                        Main.dust[num142].velocity = base.Center - Main.dust[num142].position;
                        Main.dust[num142].velocity.Normalize();
                        Main.dust[num142].velocity *= -5f;
                        Main.dust[num142].velocity += this.velocity / 2f;
                    }
                }
            }
            if (this.type == 585)
            {
                if (this.localAI[0] == 0f)
                {
                    this.localAI[0] = 1f;
                    SoundEngine.PlaySound(SoundID.Item8, this.position, 0f, 1f);
                    for (int num143 = 0; num143 < 3; num143++)
                    {
                        int num144 = Dust.NewDust(this.position, this.width, this.height, 27, this.velocity.X, this.velocity.Y, 0, default(Color), 2f);
                        Main.dust[num144].noGravity = true;
                        Main.dust[num144].velocity = base.Center - Main.dust[num144].position;
                        Main.dust[num144].velocity.Normalize();
                        Main.dust[num144].velocity *= -5f;
                        Main.dust[num144].velocity += this.velocity / 2f;
                        Main.dust[num144].noLight = true;
                    }
                }
                if (this.alpha > 0)
                {
                    this.alpha -= 50;
                }
                if (this.alpha < 0)
                {
                    this.alpha = 0;
                }
                this.frameCounter++;
                if (this.frameCounter >= 12)
                {
                    this.frameCounter = 0;
                }
                this.frame = this.frameCounter / 2;
                if (this.frame > 3)
                {
                    this.frame = 6 - this.frame;
                }
                Vector3 vector38 = NPCID.Sets.MagicAuraColor[54].ToVector3();
                Lighting.AddLight(base.Center, vector38.X, vector38.Y, vector38.Z);
                if (Main.rand.Next(3) == 0)
                {
                    int num145 = Dust.NewDust(new Vector2(this.position.X + 4f, this.position.Y + 4f), this.width - 8, this.height - 8, 27, this.velocity.X * 0.2f, this.velocity.Y * 0.2f, 100, default(Color), 2f);
                    Main.dust[num145].position -= this.velocity * 2f;
                    Main.dust[num145].noLight = true;
                    Main.dust[num145].noGravity = true;
                    Dust dust24 = Main.dust[num145];
                    dust24.velocity.X = dust24.velocity.X * 0.3f;
                    Dust dust25 = Main.dust[num145];
                    dust25.velocity.Y = dust25.velocity.Y * 0.3f;
                }
            }
            if (this.type == 594)
            {
                int num146 = (int)(43f - this.ai[1]) / 13;
                if (num146 < 1)
                {
                    num146 = 1;
                }
                int num147 = ((this.ai[1] < 20f) ? 6 : 31);
                for (int num148 = 0; num148 < num146; num148++)
                {
                    int num149 = Dust.NewDust(new Vector2(this.position.X + 4f, this.position.Y + 4f), this.width - 8, this.height - 8, num147, this.velocity.X * 0.2f, this.velocity.Y * 0.2f, 0, default(Color), 2f);
                    Main.dust[num149].position -= this.velocity * 2f;
                    Main.dust[num149].noLight = true;
                    Main.dust[num149].noGravity = true;
                    Dust dust26 = Main.dust[num149];
                    dust26.velocity.X = dust26.velocity.X * 0.3f;
                    Dust dust27 = Main.dust[num149];
                    dust27.velocity.Y = dust27.velocity.Y * 0.3f;
                    if (num147 == 6)
                    {
                        Main.dust[num149].fadeIn = Main.rand.NextFloat() * 2f;
                    }
                }
                this.ai[1] += 1f;
                if (this.ai[1] > (float)(43 * this.MaxUpdates))
                {
                    this.Kill();
                    return;
                }
            }
            if (this.type == 622)
            {
                int num150 = 229;
                if (Main.rand.Next(3) != 0)
                {
                    int num151 = Dust.NewDust(new Vector2(this.position.X + 4f, this.position.Y + 4f), this.width - 8, this.height - 8, num150, this.velocity.X * 0.2f, this.velocity.Y * 0.2f, 0, default(Color), 1.2f);
                    Main.dust[num151].position -= this.velocity * 2f;
                    Main.dust[num151].noLight = true;
                    Main.dust[num151].noGravity = true;
                    Dust dust28 = Main.dust[num151];
                    dust28.velocity.X = dust28.velocity.X * 0.3f;
                    Dust dust29 = Main.dust[num151];
                    dust29.velocity.Y = dust29.velocity.Y * 0.3f;
                }
                this.ai[1] += 1f;
                if (this.ai[1] > (float)(23 * this.MaxUpdates))
                {
                    this.Kill();
                    return;
                }
            }
            if (this.type == 587)
            {
                Color color4 = Main.hslToRgb(this.ai[1], 1f, 0.5f, byte.MaxValue);
                color4.A = 200;
                this.localAI[0] += 1f;
                if (this.localAI[0] >= 2f)
                {
                    if (this.localAI[0] == 2f)
                    {
                        SoundEngine.PlaySound(SoundID.Item5, this.position, 0f, 1f);
                        for (int num152 = 0; num152 < 4; num152++)
{
                            int num153 = Dust.NewDust(this.position, this.width, this.height, 76, this.velocity.X, this.velocity.Y, 0, color4, 1.1f);
                            Main.dust[num153].noGravity = true;
                            Main.dust[num153].velocity = base.Center - Main.dust[num153].position;
                            Main.dust[num153].velocity.Normalize();
                            Main.dust[num153].velocity *= -3f;
                            Main.dust[num153].velocity += this.velocity / 2f;
                        }
                    }
                    else
                    {
                        this.frame++;
                        if (this.frame > 2)
{
                            this.frame = 0;
                        }
                        for (int num154 = 0; num154 < 1; num154++)
{
                            int num155 = Dust.NewDust(new Vector2(this.position.X + 4f, this.position.Y + 4f), this.width - 8, this.height - 8, 76, this.velocity.X * 0.2f, this.velocity.Y * 0.2f, 0, color4, 0.9f);
                            Main.dust[num155].position = base.Center;
                            Main.dust[num155].noGravity = true;
                            Main.dust[num155].velocity = this.velocity * 0.5f;
                        }
                    }
                }
            }
            if (this.type == 349)
            {
                this.frame = (int)this.ai[0];
                this.velocity.Y = this.velocity.Y + 0.2f;
                if (this.localAI[0] == 0f || this.localAI[0] == 2f)
                {
                    this.scale += 0.01f;
                    this.alpha -= 50;
                    if (this.alpha <= 0)
                    {
                        this.localAI[0] = 1f;
                        this.alpha = 0;
                    }
                }
                else if (this.localAI[0] == 1f)
                {
                    this.scale -= 0.01f;
                    this.alpha += 50;
                    if (this.alpha >= 255)
                    {
                        this.localAI[0] = 2f;
                        this.alpha = 255;
                    }
                }
            }
            if (this.type == 348)
            {
                if (this.localAI[1] == 0f)
                {
                    this.localAI[1] = 1f;
                    SoundEngine.PlaySound(SoundID.Item8, this.position, 0f, 1f);
                }
                if (this.ai[0] == 0f || this.ai[0] == 2f)
                {
                    this.scale += 0.01f;
                    this.alpha -= 50;
                    if (this.alpha <= 0)
                    {
                        this.ai[0] = 1f;
                        this.alpha = 0;
                    }
                }
                else if (this.ai[0] == 1f)
                {
                    this.scale -= 0.01f;
                    this.alpha += 50;
                    if (this.alpha >= 255)
                    {
                        this.ai[0] = 2f;
                        this.alpha = 255;
                    }
                }
            }
            if (this.type == 572)
            {
                if (this.localAI[0] == 0f)
                {
                    this.localAI[0] = 1f;
                    SoundEngine.PlaySound(SoundID.Item17, this.position, 0f, 1f);
                }
                for (int num156 = 0; num156 < 2; num156++)
                {
                    int num157 = Dust.NewDust(new Vector2(this.position.X, this.position.Y), this.width, this.height, 40, this.velocity.X, this.velocity.Y, 100, default(Color), 1f);
                    Main.dust[num157].velocity *= 0.5f;
                    Main.dust[num157].velocity += this.velocity;
                    Main.dust[num157].velocity *= 0.5f;
                    Main.dust[num157].noGravity = true;
                    Main.dust[num157].scale = 1.2f;
                    Main.dust[num157].position = (base.Center + this.position) / 2f;
                }
            }
            if (this.type == 577)
            {
                Lighting.AddLight(base.Center, 0.1f, 0.3f, 0.4f);
            }
            else if (this.type == 576)
            {
                Lighting.AddLight(base.Center, 0.4f, 0.2f, 0.4f);
                for (int num158 = 0; num158 < 5; num158++)
                {
                    Dust dust30 = Main.dust[Dust.NewDust(this.position, this.width, this.height, 242, this.velocity.X, this.velocity.Y, 100, default(Color), 1f)];
                    dust30.velocity = Vector2.Zero;
                    dust30.position -= this.velocity / 5f * (float)num158;
                    dust30.noGravity = true;
                    dust30.scale = 0.8f;
                    dust30.noLight = true;
                }
            }
            else if (this.type == 581)
            {
                if (this.localAI[0] == 0f)
                {
                    this.localAI[0] = 1f;
                    SoundEngine.PlaySound(SoundID.Item17, base.Center, 0f, 1f);
                }
                for (int num159 = 0; num159 < 2; num159++)
                {
                    int num160 = Utils.SelectRandom<int>(Main.rand, new int[] { 229, 161, 161 });
                    Dust dust31 = Main.dust[Dust.NewDust(this.position, this.width, this.height, num160, this.velocity.X, this.velocity.Y, 100, default(Color), 1f)];
                    dust31.velocity = dust31.velocity / 4f + this.velocity / 2f;
                    dust31.noGravity = true;
                    dust31.scale = 1.2f;
                    dust31.position = base.Center;
                    dust31.noLight = true;
                }
            }
            else if (this.type == 671)
            {
                if (this.localAI[0] == 0f)
                {
                    this.localAI[0] = 1f;
                    for (int num161 = 0; num161 < 8; num161++)
                    {
                        int num162 = Utils.SelectRandom<int>(Main.rand, new int[] { 27, 62 });
                        Dust dust32 = Main.dust[Dust.NewDust(this.position, this.width, this.height, num162, this.velocity.X, this.velocity.Y, 100, default(Color), 1f)];
                        dust32.velocity = (Main.rand.NextFloatDirection() * 3.1415927f).ToRotationVector2() * 2f + this.velocity.SafeNormalize(Vector2.Zero) * 3f;
                        dust32.noGravity = true;
                        dust32.scale = 1.5f;
                        dust32.fadeIn = 1.2f;
                        dust32.position = base.Center;
                        dust32.noLight = true;
                    }
                }
                this.alpha -= 20;
                if (this.alpha < 0)
                {
                    this.alpha = 0;
                }
                for (int num163 = 0; num163 < 2; num163++)
                {
                    int num164 = Utils.SelectRandom<int>(Main.rand, new int[] { 27, 27, 62 });
                    Dust dust33 = Main.dust[Dust.NewDust(this.position, this.width, this.height, num164, this.velocity.X, this.velocity.Y, 100, default(Color), 1f)];
                    dust33.velocity = dust33.velocity / 4f + this.velocity / 2f;
                    dust33.noGravity = true;
                    dust33.scale = 1.2f;
                    dust33.position = base.Center;
                    dust33.noLight = true;
                }
            }
            else if (this.type == 811)
            {
                if (this.localAI[0] == 0f)
                {
                    SoundEngine.PlaySound(SoundID.Item17, base.Center, 0f, 1f);
                    this.localAI[0] = 1f;
                    for (int num165 = 0; num165 < 8; num165++)
                    {
                        Dust dust34 = Main.dust[Dust.NewDust(this.position, this.width, this.height, 5, this.velocity.X, this.velocity.Y, 100, default(Color), 1f)];
                        dust34.velocity = (Main.rand.NextFloatDirection() * 3.1415927f).ToRotationVector2() * 2f + this.velocity.SafeNormalize(Vector2.Zero) * 3f;
                        dust34.scale = 1.5f;
                        dust34.fadeIn = 1.7f;
                        dust34.position = base.Center;
                    }
                }
                this.alpha -= 20;
                if (this.alpha < 0)
                {
                    this.alpha = 0;
                }
                for (int num166 = 0; num166 < 2; num166++)
                {
                    Dust dust35 = Main.dust[Dust.NewDust(this.position, this.width, this.height, 5, this.velocity.X, this.velocity.Y, 100, default(Color), 1f)];
                    dust35.velocity = dust35.velocity / 4f + this.velocity / 2f;
                    dust35.scale = 1.2f;
                    dust35.position = base.Center + Main.rand.NextFloat() * this.velocity * 2f;
                }
            }
            else if (this.type == 819)
            {
                if (this.localAI[0] == 0f)
                {
                    this.localAI[0] = 1f;
                    for (int num167 = 0; num167 < 8; num167++)
                    {
                        Dust dust36 = Main.dust[Dust.NewDust(this.position, this.width, this.height, 5, this.velocity.X, this.velocity.Y, 100, default(Color), 1f)];
                        dust36.velocity = (Main.rand.NextFloatDirection() * 3.1415927f).ToRotationVector2() * 2f + this.velocity.SafeNormalize(Vector2.Zero) * 2f;
                        dust36.scale = 0.9f;
                        dust36.fadeIn = 1.3f;
                        dust36.position = base.Center;
                    }
                }
                this.alpha -= 20;
                if (this.alpha < 0)
                {
                    this.alpha = 0;
                }
                for (int num168 = 1; num168 < 6; num168++)
                {
                    Dust dust37 = Main.dust[Dust.NewDust(this.position, this.width, this.height, 5, 0f, 0f, 100, default(Color), 1f)];
                    dust37.velocity = dust37.velocity * 0.5f + this.velocity * 0.5f;
                    dust37.velocity *= 0.25f;
                    dust37.scale = 0.9f;
                    dust37.position = base.Center - this.velocity * (float)num168 / 5f;
                }
                if (Main.rand.Next(2) == 0)
                {
                    Dust dust38 = Dust.NewDustPerfect(base.Center - this.velocity * 3f, 267, new Vector2?(this.velocity * 0.5f), 0, Color.Red * (Main.rand.NextFloat() * 0.3f + 0.1f), 1f);
                    dust38.noGravity = true;
                    dust38.scale = 0.7f;
                }
                Lighting.AddLight(base.Center, 0.3f, 0.05f, 0.05f);
            }
            else if (this.type == 814)
            {
                if (this.localAI[0] == 0f)
                {
                    SoundEngine.PlaySound(SoundID.Item171, base.Center, 0f, 1f);
                    this.localAI[0] = 1f;
                    for (int num169 = 0; num169 < 8; num169++)
                    {
                        Dust dust39 = Main.dust[Dust.NewDust(this.position, this.width, this.height, 5, this.velocity.X, this.velocity.Y, 100, default(Color), 1f)];
                        dust39.velocity = (Main.rand.NextFloatDirection() * 3.1415927f).ToRotationVector2() * 2f + this.velocity.SafeNormalize(Vector2.Zero) * 2f;
                        dust39.scale = 0.9f;
                        dust39.fadeIn = 1.1f;
                        dust39.position = base.Center;
                    }
                }
                this.alpha -= 20;
                if (this.alpha < 0)
                {
                    this.alpha = 0;
                }
                for (int num170 = 0; num170 < 2; num170++)
                {
                    Dust dust40 = Main.dust[Dust.NewDust(this.position, this.width, this.height, 5, this.velocity.X, this.velocity.Y, 100, default(Color), 1f)];
                    dust40.velocity = dust40.velocity / 4f + this.velocity / 2f;
                    dust40.scale = 1.2f;
                    dust40.position = base.Center + Main.rand.NextFloat() * this.velocity * 2f;
                }
                for (int num171 = 1; num171 < this.oldPos.Length; num171++)
                {
                    if (this.oldPos[num171] == Vector2.Zero)
                    {
                        break;
                    }
                    if (Main.rand.Next(3) == 0)
                    {
                        Dust dust41 = Main.dust[Dust.NewDust(this.oldPos[num171], this.width, this.height, 5, this.velocity.X, this.velocity.Y, 100, default(Color), 1f)];
                        dust41.velocity = dust41.velocity / 4f + this.velocity / 2f;
                        dust41.scale = 1.2f;
                        dust41.position = this.oldPos[num171] + base.Size / 2f + Main.rand.NextFloat() * this.velocity * 2f;
                    }
                }
            }
            else if (this.type == 675)
            {
                if (this.localAI[0] == 0f)
                {
                    this.localAI[0] = 1f;
                    SoundEngine.PlayTrackedSound(SoundID.DD2_DarkMageAttack, base.Center, default(SoundPlayOverrides));
                }
                this.alpha -= 20;
                if (this.alpha < 0)
                {
                    this.alpha = 0;
                }
            }
            else if (this.type == 676)
            {
                if (this.localAI[0] == 0f)
                {
                    this.localAI[0] = 1f;
                    SoundEngine.PlaySound(SoundID.Item17, base.Center, 0f, 1f);
                }
                this.alpha -= 20;
                if (this.alpha < 0)
                {
                    this.alpha = 0;
                }
                for (int num172 = 0; num172 < 2; num172++)
                {
                    if (Main.rand.Next(5) != 0)
                    {
                        int num173 = Utils.SelectRandom<int>(Main.rand, new int[] { 4, 256 });
                        Dust dust42 = Main.dust[Dust.NewDust(this.position, this.width, this.height, num173, this.velocity.X, this.velocity.Y, 100, default(Color), 1f)];
                        dust42.velocity = dust42.velocity / 4f + this.velocity / 2f;
                        dust42.scale = 0.8f + Main.rand.NextFloat() * 0.4f;
                        dust42.position = base.Center;
                        dust42.position += new Vector2((float)(this.width * 2), 0f).RotatedBy((double)(6.2831855f * Main.rand.NextFloat()), default(Vector2)) * Main.rand.NextFloat();
                        dust42.noLight = true;
                        if (dust42.type == 4)
{
                            dust42.color = new Color(80, 170, 40, 120);
                        }
                    }
                }
            }
            else if (this.type == 686)
            {
                if (this.localAI[0] == 0f)
                {
                    this.localAI[0] = 1f;
                    SoundEngine.PlayTrackedSound(SoundID.DD2_BetsyFireballShot, base.Center, default(SoundPlayOverrides));
                }
                if (this.ai[0] >= 2f)
                {
                    this.alpha -= 25;
                    if (this.alpha < 0)
                    {
                        this.alpha = 0;
                    }
                }
                if (Main.rand.Next(4) == 0)
                {
                    Dust dust43 = Dust.NewDustDirect(this.position, this.width, this.height, 55, 0f, 0f, 200, default(Color), 1f);
                    dust43.scale *= 0.7f;
                    dust43.velocity += this.velocity * 1f;
                }
                if (Main.rand.Next(3) == 0 && this.oldPos[9] != Vector2.Zero)
                {
                    Dust dust44 = Dust.NewDustDirect(this.oldPos[9], this.width, this.height, 55, 0f, 0f, 50, default(Color), 1f);
                    dust44.scale *= 0.85f;
                    dust44.velocity += this.velocity * 0.85f;
                    dust44.color = Color.Purple;
                }
            }
            else if (this.type == 1097)
            {
                if (this.localAI[0] == 0f)
                {
                    this.localAI[0] = 1f;
                    SoundEngine.PlayTrackedSound(SoundID.DD2_BetsyFireballShot, base.Center, default(SoundPlayOverrides));
                    for (int num174 = 0; num174 < 10; num174++)
                    {
                        Dust dust45 = Dust.NewDustDirect(this.position, this.width, this.height, 6, 0f, 0f, 200, default(Color), 1f);
                        dust45.scale *= 0.7f;
                        dust45.velocity *= 0.5f;
                        dust45.velocity += this.velocity * Main.rand.NextFloat() * 0.6f;
                        dust45.noLightEmittance = true;
                        Dust dust46 = Dust.NewDustDirect(this.position, this.width, this.height, 6, 0f, 0f, 50, default(Color), 1f);
                        dust46.scale *= 1.25f;
                        dust46.velocity += this.velocity * 0.45f * Main.rand.NextFloat();
                        dust46.noLightEmittance = true;
                    }
                }
                if (this.ai[0] >= 2f)
                {
                    this.alpha -= 25;
                    if (this.alpha < 0)
                    {
                        this.alpha = 0;
                    }
                }
                if (Main.rand.Next(4) == 0)
                {
                    Dust dust47 = Dust.NewDustDirect(this.position, this.width, this.height, 6, 0f, 0f, 200, default(Color), 1f);
                    dust47.scale *= 1.3f;
                    dust47.velocity += this.velocity * 0.4f;
                    dust47.noLightEmittance = true;
                }
                if (Main.rand.Next(2) == 0)
                {
                    Dust dust48 = Dust.NewDustDirect(this.position, this.width, this.height, 30, 0f, 0f, 100, default(Color), 1f);
                    dust48.scale *= 0.7f;
                    dust48.velocity += this.velocity * 1f;
                }
                if (Main.rand.Next(3) == 0 && this.oldPos[9] != Vector2.Zero)
                {
                    Dust dust49 = Dust.NewDustDirect(this.oldPos[9], this.width, this.height, 55, 0f, 0f, 50, default(Color), 1f);
                    dust49.scale *= 0.85f;
                    dust49.velocity += this.velocity * 0.85f;
                    dust49.color = new Color(255, 60, 20);
                }
                this.scale -= 0.01f;
                if (this.scale < 0.3f)
                {
                    this.Kill();
                    return;
                }
            }
            else if (this.type == 711)
            {
                if (this.localAI[0] == 0f)
                {
                    this.localAI[0] = 1f;
                    for (int num175 = 0; num175 < 10; num175++)
                    {
                        Dust dust50 = Dust.NewDustDirect(this.position, this.width, this.height, 55, 0f, 0f, 200, default(Color), 1f);
                        dust50.scale *= 0.65f;
                        dust50.velocity *= 1.5f;
                        dust50.velocity += this.velocity * 0.3f;
                        dust50.fadeIn = 0.7f;
                    }
                }
                if (this.ai[0] >= 2f)
                {
                    this.alpha -= 25;
                    if (this.alpha < 0)
                    {
                        this.alpha = 0;
                    }
                }
                if (Main.rand.Next(4) == 0)
                {
                    Dust dust51 = Dust.NewDustDirect(this.position, this.width, this.height, 55, 0f, 0f, 200, default(Color), 1f);
                    dust51.scale *= 0.7f;
                    dust51.velocity += this.velocity * 1f;
                }
                if (Main.rand.Next(3) == 0 && this.oldPos[9] != Vector2.Zero)
                {
                    Dust dust52 = Dust.NewDustDirect(this.oldPos[9], this.width, this.height, 55, 0f, 0f, 50, default(Color), 1f);
                    dust52.scale *= 0.85f;
                    dust52.velocity += this.velocity * 0.85f;
                    dust52.color = Color.Purple;
                }
            }
            if (this.type == 299)
            {
                if (this.localAI[0] == 6f)
                {
                    SoundEngine.PlaySound(SoundID.Item8, this.position, 0f, 1f);
                    for (int num176 = 0; num176 < 40; num176++)
                    {
                        int num177 = Dust.NewDust(new Vector2(this.position.X, this.position.Y), this.width, this.height, 181, 0f, 0f, 100, default(Color), 1f);
                        Main.dust[num177].velocity *= 3f;
                        Main.dust[num177].velocity += this.velocity * 0.75f;
                        Main.dust[num177].scale *= 1.2f;
                        Main.dust[num177].noGravity = true;
                    }
                }
                this.localAI[0] += 1f;
                if (this.localAI[0] > 6f)
                {
                    for (int num178 = 0; num178 < 3; num178++)
                    {
                        int num179 = Dust.NewDust(new Vector2(this.position.X, this.position.Y), this.width, this.height, 181, this.velocity.X * 0.2f, this.velocity.Y * 0.2f, 100, default(Color), 1f);
                        Main.dust[num179].velocity *= 0.6f;
                        Main.dust[num179].scale *= 1.4f;
                        Main.dust[num179].noGravity = true;
                    }
                }
            }
            else if (this.type == 270 || this.type == 837)
            {
                if (this.type == 270)
                {
                    this.alpha = 0;
                }
                if (this.alpha > 0)
                {
                    this.alpha -= 50;
                }
                if (this.alpha < 0)
                {
                    this.alpha = 0;
                }
                this.frame++;
                if (this.frame > 2)
                {
                    this.frame = 0;
                }
                if (this.type == 270)
                {
                    for (int num180 = 0; num180 < 2; num180++)
                    {
                        int num181 = Dust.NewDust(new Vector2(this.position.X + 4f, this.position.Y + 4f), this.width - 8, this.height - 8, 5, this.velocity.X * 0.2f, this.velocity.Y * 0.2f, 100, default(Color), 1.5f);
                        Main.dust[num181].position -= this.velocity;
                        Main.dust[num181].noGravity = true;
                        Dust dust53 = Main.dust[num181];
                        dust53.velocity.X = dust53.velocity.X * 0.3f;
                        Dust dust54 = Main.dust[num181];
                        dust54.velocity.Y = dust54.velocity.Y * 0.3f;
                    }
                }
                else
                {
                    for (int num182 = 0; num182 < 2; num182++)
                    {
                        int num183 = Dust.NewDust(new Vector2(this.position.X + 4f, this.position.Y + 4f), this.width - 8, this.height - 8, 6, this.velocity.X * 0.2f, this.velocity.Y * 0.2f, 100, default(Color), 2f);
                        Main.dust[num183].position -= this.velocity * 2f;
                        Main.dust[num183].noGravity = true;
                        Dust dust55 = Main.dust[num183];
                        dust55.velocity.X = dust55.velocity.X * 0.3f;
                        Dust dust56 = Main.dust[num183];
                        dust56.velocity.Y = dust56.velocity.Y * 0.3f;
                    }
                }
            }
            if (this.type == 259)
            {
                if (this.alpha > 0)
                {
                    this.alpha -= 10;
                }
                if (this.alpha < 0)
                {
                    this.alpha = 0;
                }
            }
            if (this.type == 265)
            {
                if (this.alpha > 0)
                {
                    this.alpha -= 50;
                }
                if (this.alpha < 0)
                {
                    this.alpha = 0;
                }
                if (this.alpha == 0)
                {
                    int num184 = Dust.NewDust(new Vector2(this.position.X, this.position.Y), this.width, this.height, 163, this.velocity.X, this.velocity.Y, 100, default(Color), 1.2f);
                    Main.dust[num184].noGravity = true;
                    Main.dust[num184].velocity *= 0.3f;
                    Main.dust[num184].velocity -= this.velocity * 0.4f;
                }
            }
            if (this.type == 355)
            {
                if (this.alpha > 0)
                {
                    this.alpha -= 50;
                }
                if (this.alpha < 0)
                {
                    this.alpha = 0;
                }
                if (this.alpha == 0)
                {
                    int num185 = Dust.NewDust(new Vector2(this.position.X, this.position.Y), this.width, this.height, 205, this.velocity.X, this.velocity.Y, 100, default(Color), 1.2f);
                    Main.dust[num185].noGravity = true;
                    Main.dust[num185].velocity *= 0.3f;
                    Main.dust[num185].velocity -= this.velocity * 0.4f;
                }
            }
            if (this.type == 981 && Main.rand.Next(6) == 0)
            {
                int num186 = Dust.NewDust(new Vector2(this.position.X, this.position.Y), this.width, this.height, 279, this.velocity.X, this.velocity.Y, 100, default(Color), 1.2f);
                Main.dust[num186].noLightEmittance = true;
                Main.dust[num186].noGravity = true;
                Main.dust[num186].velocity *= 0.2f;
            }
            if (this.type == 357)
            {
                if (this.alpha < 170)
                {
                    for (int num187 = 0; num187 < 10; num187++)
                    {
                        float num188 = this.position.X - this.velocity.X / 10f * (float)num187;
                        float num189 = this.position.Y - this.velocity.Y / 10f * (float)num187;
                        int num190 = Dust.NewDust(new Vector2(num188, num189), 1, 1, 206, 0f, 0f, 0, default(Color), 1f);
                        Main.dust[num190].alpha = this.alpha;
                        Main.dust[num190].position.X = num188;
                        Main.dust[num190].position.Y = num189;
                        Main.dust[num190].velocity *= 0f;
                        Main.dust[num190].noGravity = true;
                    }
                }
                if (this.alpha > 0)
                {
                    this.alpha -= 25;
                }
                if (this.alpha < 0)
                {
                    this.alpha = 0;
                }
            }
            else if (this.type == 207 || this.type == 837)
            {
                if (this.type == 207 && this.alpha < 170)
                {
                    for (int num191 = 0; num191 < 10; num191++)
                    {
                        float num192 = this.position.X - this.velocity.X / 10f * (float)num191;
                        float num193 = this.position.Y - this.velocity.Y / 10f * (float)num191;
                        int num194 = Dust.NewDust(new Vector2(num192, num193), 1, 1, 75, 0f, 0f, 0, default(Color), 1f);
                        Main.dust[num194].alpha = this.alpha;
                        Main.dust[num194].position.X = num192;
                        Main.dust[num194].position.Y = num193;
                        Main.dust[num194].velocity *= 0f;
                        Main.dust[num194].noGravity = true;
                    }
                }
                float num195 = (float)Math.Sqrt((double)(this.velocity.X * this.velocity.X + this.velocity.Y * this.velocity.Y));
                float num196 = this.localAI[0];
                if (num196 == 0f)
                {
                    this.localAI[0] = num195;
                    num196 = num195;
                }
                if (this.alpha > 0)
                {
                    this.alpha -= 25;
                }
                if (this.alpha < 0)
                {
                    this.alpha = 0;
                }
                float num197 = this.position.X;
                float num198 = this.position.Y;
                float num199 = 300f;
                bool flag6 = false;
                int num200 = 0;
                if (this.ai[1] == 0f)
                {
                    for (int num201 = 0; num201 < Main.maxNPCs; num201++)
                    {
                        if (Main.npc[num201].CanBeChasedBy(this, false) && (this.ai[1] == 0f || this.ai[1] == (float)(num201 + 1)))
{
                            float num202 = Main.npc[num201].position.X + (float)(Main.npc[num201].width / 2);
                            float num203 = Main.npc[num201].position.Y + (float)(Main.npc[num201].height / 2);
                            float num204 = Math.Abs(this.position.X + (float)(this.width / 2) - num202) + Math.Abs(this.position.Y + (float)(this.height / 2) - num203);
                            if (num204 < num199 && Collision.CanHit(new Vector2(this.position.X + (float)(this.width / 2), this.position.Y + (float)(this.height / 2)), 1, 1, Main.npc[num201].position, Main.npc[num201].width, Main.npc[num201].height))
{
                                num199 = num204;
                                num197 = num202;
                                num198 = num203;
                                flag6 = true;
                                num200 = num201;
                            }
                        }
                    }
                    if (flag6)
                    {
                        this.ai[1] = (float)(num200 + 1);
                    }
                    flag6 = false;
                }
                if (this.ai[1] > 0f)
                {
                    int num205 = (int)(this.ai[1] - 1f);
                    if (Main.npc[num205].active && Main.npc[num205].CanBeChasedBy(this, true) && !Main.npc[num205].dontTakeDamage)
                    {
                        float num206 = Main.npc[num205].position.X + (float)(Main.npc[num205].width / 2);
                        float num207 = Main.npc[num205].position.Y + (float)(Main.npc[num205].height / 2);
                        if (Math.Abs(this.position.X + (float)(this.width / 2) - num206) + Math.Abs(this.position.Y + (float)(this.height / 2) - num207) < 1000f)
{
                            flag6 = true;
                            num197 = Main.npc[num205].position.X + (float)(Main.npc[num205].width / 2);
                            num198 = Main.npc[num205].position.Y + (float)(Main.npc[num205].height / 2);
                        }
                    }
                    else
                    {
                        this.ai[1] = 0f;
                    }
                }
                if (!this.friendly)
                {
                    flag6 = false;
                }
                if (flag6)
                {
                    float num208 = num196;
                    Vector2 vector39 = new Vector2(this.position.X + (float)this.width * 0.5f, this.position.Y + (float)this.height * 0.5f);
                    float num209 = num197 - vector39.X;
                    float num210 = num198 - vector39.Y;
                    float num211 = (float)Math.Sqrt((double)(num209 * num209 + num210 * num210));
                    num211 = num208 / num211;
                    num209 *= num211;
                    num210 *= num211;
                    int num212 = 8;
                    if (this.type == 837)
                    {
                        num212 = 32;
                    }
                    this.velocity.X = (this.velocity.X * (float)(num212 - 1) + num209) / (float)num212;
                    this.velocity.Y = (this.velocity.Y * (float)(num212 - 1) + num210) / (float)num212;
                }
            }
            else if (this.type == 81 || this.type == 91)
            {
                if (this.ai[0] >= 20f)
                {
                    this.ai[0] = 20f;
                    this.velocity.Y = this.velocity.Y + 0.07f;
                }
            }
            else if (this.type == 174 || this.type == 605 || this.type == 920 || this.type == 921 || this.type == 926)
            {
                if (this.ai[0] >= 5f)
                {
                    this.ai[0] = 5f;
                    this.velocity.Y = this.velocity.Y + 0.15f;
                }
            }
            else if (this.type == 937)
            {
                if (this.ai[0] >= 5f)
                {
                    this.ai[0] = 5f;
                    this.velocity.Y = this.velocity.Y + 0.07f;
                }
            }
            else if (this.type == 962)
            {
                this.frame = (int)this.ai[1];
                if (this.localAI[0] == 0f)
                {
                    this.localAI[0] = 1f;
                    this.rotation = this.velocity.ToRotation();
                    for (int num213 = 0; num213 < 5; num213++)
                    {
                        Dust dust57 = Dust.NewDustPerfect(base.Center + Main.rand.NextVector2Circular(24f, 24f), 16, new Vector2?(this.velocity * MathHelper.Lerp(0.2f, 0.7f, Main.rand.NextFloat())), 0, default(Color), 1f);
                        dust57.velocity += Main.rand.NextVector2Circular(0.5f, 0.5f);
                        dust57.scale = 0.8f + Main.rand.NextFloat() * 0.5f;
                    }
                    for (int num214 = 0; num214 < 5; num214++)
                    {
                        Dust dust58 = Dust.NewDustPerfect(base.Center + Main.rand.NextVector2Circular(24f, 24f), 16, new Vector2?(Main.rand.NextVector2Circular(2f, 2f) + this.velocity * MathHelper.Lerp(0.2f, 0.5f, Main.rand.NextFloat())), 0, default(Color), 1f);
                        dust58.velocity += Main.rand.NextVector2Circular(0.5f, 0.5f);
                        dust58.scale = 0.8f + Main.rand.NextFloat() * 0.5f;
                        dust58.fadeIn = 1f;
                    }
                }
                if (this.ai[0] >= 5f)
                {
                    this.velocity.Y = this.velocity.Y + 0.15f;
                }
            }
            else if (this.type == 337)
            {
                if (this.position.Y > Main.player[this.owner].position.Y - 300f)
                {
                    this.tileCollide = true;
                }
                if ((double)this.position.Y < Main.worldSurface * 16.0)
                {
                    this.tileCollide = true;
                }
                this.frame = (int)this.ai[1];
                if (Main.rand.Next(2) == 0)
                {
                    int num215 = Dust.NewDust(new Vector2(this.position.X, this.position.Y), this.width, this.height, 197, 0f, 0f, 0, default(Color), 1f);
                    Main.dust[num215].velocity *= 0.5f;
                    Main.dust[num215].noGravity = true;
                }
            }
            else if (this.type == 645)
            {
                if (this.ai[1] != -1f && this.position.Y > this.ai[1])
                {
                    this.tileCollide = true;
                }
                if (this.position.HasNaNs())
                {
                    this.Kill();
                    return;
                }
                bool flag7 = WorldGen.SolidTile(Framing.GetTileSafely((int)this.position.X / 16, (int)this.position.Y / 16));
                Dust dust59 = Main.dust[Dust.NewDust(new Vector2(this.position.X, this.position.Y), this.width, this.height, 229, 0f, 0f, 0, default(Color), 1f)];
                dust59.position = base.Center;
                dust59.velocity = Vector2.Zero;
                dust59.noGravity = true;
                if (flag7)
                {
                    dust59.noLight = true;
                }
                if (this.ai[1] == -1f)
                {
                    this.ai[0] += 1f;
                    this.velocity = Vector2.Zero;
                    this.tileCollide = false;
                    this.penetrate = -1;
                    this.position = base.Center;
                    this.width = (this.height = 140);
                    base.Center = this.position;
                    this.alpha -= 10;
                    if (this.alpha < 0)
                    {
                        this.alpha = 0;
                    }
                    num = this.frameCounter + 1;
                    this.frameCounter = num;
                    if (num >= this.MaxUpdates * 3)
                    {
                        this.frameCounter = 0;
                        this.frame++;
                    }
                    if (this.ai[0] >= (float)(Main.projFrames[this.type] * this.MaxUpdates * 3))
                    {
                        this.Kill();
                    }
                    return;
                }
                this.alpha = 255;
                if (this.numUpdates == 0)
                {
                    int num216 = -1;
                    float num217 = 60f;
                    for (int num218 = 0; num218 < Main.maxNPCs; num218++)
                    {
                        NPC npc2 = Main.npc[num218];
                        if (npc2.CanBeChasedBy(this, false))
{
                            float num219 = base.Distance(npc2.Center);
                            if (num219 < num217 && Collision.CanHitLine(base.Center, 0, 0, npc2.Center, 0, 0))
{
                                num217 = num219;
                                num216 = num218;
                            }
                        }
                    }
                    if (num216 != -1)
                    {
                        this.ai[0] = 0f;
                        this.ai[1] = -1f;
                        this.netUpdate = true;
                        return;
                    }
                }
            }
            else if (this.type >= 424 && this.type <= 426)
            {
                if (this.position.Y > Main.player[this.owner].position.Y - 300f)
                {
                    this.tileCollide = true;
                }
                if ((double)this.position.Y < Main.worldSurface * 16.0)
                {
                    this.tileCollide = true;
                }
                this.scale = this.ai[1];
                this.rotation += this.velocity.X * 2f;
                Vector2 vector40 = base.Center + Vector2.Normalize(this.velocity) * 10f;
                Dust dust60 = Main.dust[Dust.NewDust(this.position, this.width, this.height, 6, 0f, 0f, 0, default(Color), 1f)];
                dust60.position = vector40;
                dust60.velocity = this.velocity.RotatedBy(1.5707963705062866, default(Vector2)) * 0.33f + this.velocity / 4f;
                dust60.position += this.velocity.RotatedBy(1.5707963705062866, default(Vector2));
                dust60.fadeIn = 0.5f;
                dust60.noGravity = true;
                Dust dust61 = Main.dust[Dust.NewDust(this.position, this.width, this.height, 6, 0f, 0f, 0, default(Color), 1f)];
                dust61.position = vector40;
                dust61.velocity = this.velocity.RotatedBy(-1.5707963705062866, default(Vector2)) * 0.33f + this.velocity / 4f;
                dust61.position += this.velocity.RotatedBy(-1.5707963705062866, default(Vector2));
                dust61.fadeIn = 0.5f;
                dust61.noGravity = true;
                for (int num220 = 0; num220 < 1; num220++)
                {
                    int num221 = Dust.NewDust(new Vector2(this.position.X, this.position.Y), this.width, this.height, 6, 0f, 0f, 0, default(Color), 1f);
                    Main.dust[num221].velocity *= 0.5f;
                    Main.dust[num221].scale *= 1.3f;
                    Main.dust[num221].fadeIn = 1f;
                    Main.dust[num221].noGravity = true;
                }
            }
            else if (this.type == 344)
            {
                if (WorldGen.SolidTile((int)this.position.X / 16, (int)(this.position.Y + this.velocity.Y) / 16 + 1, false) || WorldGen.SolidTile((int)(this.position.X + (float)this.width) / 16, (int)(this.position.Y + this.velocity.Y) / 16 + 1, false))
                {
                    this.Kill();
                    return;
                }
                this.localAI[1] += 1f;
                if (this.localAI[1] > 5f)
                {
                    this.alpha -= 50;
                    if (this.alpha < 0)
                    {
                        this.alpha = 0;
                    }
                }
                this.frame = (int)this.ai[1];
                if (this.localAI[1] >= 20f)
                {
                    this.velocity.Y = this.velocity.Y + 0.15f;
                    this.velocity.X = this.velocity.X * 0.96f;
                }
                if (this.localAI[1] >= 25f)
                {
                    this.localAI[1] = 20f;
                    Vector2 zero = Vector2.Zero;
                    float num222 = 0f;
                    int num223 = 60;
                    for (int num224 = 0; num224 < 1000; num224++)
                    {
                        Projectile projectile = Main.projectile[num224];
                        if (projectile.whoAmI != this.whoAmI && projectile.active && projectile.type == this.type)
{
                            Vector2 vector41 = projectile.position - this.position;
                            if (vector41.Length() <= (float)num223)
{
                                num222 += 1f;
                                float num225 = Utils.Remap(vector41.Length(), 0f, (float)num223, 1f, 0f, true);
                                zero.X += (float)(-(float)Math.Sign(vector41.X)) * num225;
                            }
                        }
                    }
                    if (num222 > 0f)
                    {
                        Vector2 vector42 = zero;
                        vector42.Y = 0f;
                        if (vector42.X == 0f)
{
                            vector42.X = 1f;
                        }
                        this.velocity += vector42 * 0.25f;
                    }
                }
            }
            else if (this.type == 336 || this.type == 345)
            {
                if (this.type == 345 && this.localAI[0] == 0f)
                {
                    this.localAI[0] = 1f;
                    SoundEngine.PlaySound(SoundID.Item1, this.position, 0f, 1f);
                }
                if (this.ai[0] >= 50f)
                {
                    this.ai[0] = 50f;
                    this.velocity.Y = this.velocity.Y + 0.5f;
                }
            }
            else if (this.type == 246)
            {
                this.alpha -= 20;
                if (this.alpha < 0)
                {
                    this.alpha = 0;
                }
                if (this.ai[0] >= 60f)
                {
                    this.ai[0] = 60f;
                    this.velocity.Y = this.velocity.Y + 0.15f;
                }
            }
            else if (this.type == 311)
            {
                if (this.alpha > 0)
                {
                    this.alpha -= 50;
                }
                if (this.alpha < 0)
                {
                    this.alpha = 0;
                }
                if (this.ai[0] >= 30f)
                {
                    this.ai[0] = 30f;
                    if (this.ai[1] == 0f)
                    {
                        this.ai[1] = 1f;
                    }
                    this.velocity.Y = this.velocity.Y + 0.5f;
                }
            }
            else if (this.type == 1023)
            {
                if (this.ai[0] >= 6f)
                {
                    this.alpha = 0;
                }
                if (this.ai[0] >= 20f)
                {
                    this.ai[0] = 30f;
                    this.velocity.Y = this.velocity.Y + 0.25f;
                }
            }
            else if (this.type == 312)
            {
                if (this.ai[0] >= 5f)
                {
                    this.alpha = 0;
                }
                if (this.ai[0] >= 20f)
                {
                    this.ai[0] = 30f;
                    this.velocity.Y = this.velocity.Y + 0.5f;
                }
                Lighting.AddLight(base.Center, 0.6f, 0.4f, 0.3f);
            }
            else if (this.type != 239 && this.type != 264)
            {
                if (this.type == 176)
                {
                    if (this.ai[0] >= 15f)
                    {
                        this.ai[0] = 15f;
                        this.velocity.Y = this.velocity.Y + 0.05f;
                    }
                }
                else if (this.type == 275 || this.type == 276)
                {
                    if (this.alpha > 0)
                    {
                        this.alpha -= 30;
                    }
                    if (this.alpha < 0)
                    {
                        this.alpha = 0;
                    }
                    if (this.ai[0] >= 35f)
                    {
                        this.ai[0] = 35f;
                        this.velocity.Y = this.velocity.Y + 0.025f;
                    }
                    if (Main.expertMode)
                    {
                        float num226 = 18f;
                        int num227 = (int)Player.FindClosest(base.Center, 1, 1);
                        Vector2 vector43 = Main.player[num227].Center - base.Center;
                        vector43.Normalize();
                        vector43 *= num226;
                        int num228 = 70;
                        this.velocity = (this.velocity * (float)(num228 - 1) + vector43) / (float)num228;
                        if (this.velocity.Length() < 14f)
{
                            this.velocity.Normalize();
                            this.velocity *= 14f;
                        }
                        this.tileCollide = false;
                        if (this.timeLeft > 180)
{
                            this.timeLeft = 180;
                        }
                    }
                }
                else if (this.type == 172)
                {
                    if (this.ai[0] >= 17f)
                    {
                        this.ai[0] = 17f;
                        this.velocity.Y = this.velocity.Y + 0.085f;
                    }
                }
                else if (this.type == 117)
                {
                    if (this.ai[0] >= 35f)
                    {
                        this.ai[0] = 35f;
                        this.velocity.Y = this.velocity.Y + 0.06f;
                    }
                }
                else if (this.type == 120)
                {
                    int num229 = Dust.NewDust(new Vector2(this.position.X - this.velocity.X, this.position.Y - this.velocity.Y), this.width, this.height, 67, this.velocity.X, this.velocity.Y, 100, default(Color), 1.2f);
                    Main.dust[num229].noGravity = true;
                    Main.dust[num229].velocity *= 0.3f;
                    if (this.ai[0] >= 30f)
                    {
                        this.ai[0] = 30f;
                        this.velocity.Y = this.velocity.Y + 0.05f;
                    }
                }
                else if (this.type == 195)
                {
                    int num230 = 40;
                    if (this.ai[0] >= (float)num230)
                    {
                        this.ai[0] = (float)num230;
                        this.velocity.Y = this.velocity.Y + 0.15f;
                        this.tileCollide = true;
                    }
                    else
                    {
                        this.tileCollide = this.velocity.Y > 0f;
                    }
                }
                else if (this.type == 1097)
                {
                    int num231 = 40;
                    if (this.ai[0] >= (float)num231)
                    {
                        this.ai[0] = (float)num231;
                        this.velocity.Y = this.velocity.Y + 0.15f;
                        this.tileCollide = true;
                    }
                    else
                    {
                        this.tileCollide = this.velocity.Y > 0f;
                    }
                }
                else if (this.type == 267 || this.type == 477 || this.type == 478 || this.type == 479)
                {
                    this.localAI[0] += 1f;
                    if (this.localAI[0] > 3f)
                    {
                        this.alpha = 0;
                    }
                    if (this.ai[0] >= 20f)
                    {
                        this.ai[0] = 20f;
                        if (this.type != 477)
{
                            this.velocity.Y = this.velocity.Y + 0.075f;
                        }
                    }
                    if (this.type == 479 && Main.myPlayer == this.owner)
                    {
                        if (this.ai[1] >= 0f)
{
                            this.maxPenetrate = (this.penetrate = -1);
                        }
                        else if (this.penetrate < 0)
{
                            this.maxPenetrate = (this.penetrate = 1);
                        }
                        if (this.ai[1] >= 0f)
{
                            this.ai[1] += 1f;
                        }
                        if (this.ai[1] > (float)Main.rand.Next(5, 30))
{
                            this.ai[1] = -1000f;
                            float num232 = this.velocity.Length();
                            Vector2 velocity2 = this.velocity;
                            velocity2.Normalize();
                            int num233 = Main.rand.Next(2, 4);
                            if (Main.rand.Next(4) == 0)
{
                                num233++;
                            }
                            for (int num234 = 0; num234 < num233; num234++)
{
                                Vector2 vector44 = new Vector2((float)Main.rand.Next(-100, 101), (float)Main.rand.Next(-100, 101));
                                vector44.Normalize();
                                vector44 += velocity2 * 2f;
                                vector44.Normalize();
                                vector44 *= num232;
                                Projectile.NewProjectile(this.GetProjectileSource_FromThis(), base.Center.X, base.Center.Y, vector44.X, vector44.Y, this.type, (int)((float)this.damage * 0.9f), this.knockBack, this.owner, 0f, -1000f, 0f, new NewProjectileModifier(NewProjectileModifiers.IchorDartUpdatePenetrate));
                                Vector2 vector45 = Vector2.Zero;
                                for (int num235 = 0; num235 < 4; num235++)
{
                                    vector45 = vector44 * (0.4f + (float)num235 * 0.075f);
                                    Main.dust[Dust.NewDust(base.Center + vector45 * 1.5f, 2, 2, 170, vector45.X, vector45.Y, 0, default(Color), 1f)].noGravity = true;
                                }
                                vector45 = vector44 * 0.2f;
                                Main.dust[Dust.NewDust(base.Center, 2, 2, 170, -vector45.X, -vector45.Y, 0, default(Color), 1f)].noGravity = true;
                            }
                        }
                    }
                    if (this.type == 478 && Main.myPlayer == this.owner)
                    {
                        this.ai[1] += 1f;
                        if (this.ai[1] > (float)Main.rand.Next(5, 20))
{
                            if (this.timeLeft > 40)
{
                                this.timeLeft -= 20;
                            }
                            this.ai[1] = 0f;
                            Projectile.NewProjectile(this.GetProjectileSource_FromThis(), base.Center.X, base.Center.Y, 0f, 0f, 480, (int)((double)this.damage * 0.8), this.knockBack * 0.5f, this.owner, 0f, 0f, 0f, null);
                        }
                    }
                }
                else if (this.type == 408)
                {
                    if (this.ai[0] >= 45f)
                    {
                        this.ai[0] = 45f;
                        this.velocity.Y = this.velocity.Y + 0.05f;
                    }
                }
                else if (this.type == 616)
                {
                    if (this.alpha < 170)
                    {
                        float num236 = 3f;
                        int num237 = 0;
                        while ((float)num237 < num236)
{
                            int num238 = Dust.NewDust(this.position, 1, 1, 229, 0f, 0f, 0, default(Color), 1f);
                            Main.dust[num238].position = base.Center - this.velocity / num236 * (float)num237;
                            Main.dust[num238].velocity *= 0f;
                            Main.dust[num238].noGravity = true;
                            Main.dust[num238].alpha = 200;
                            Main.dust[num238].scale = 0.5f;
                            num237++;
                        }
                    }
                    float num239 = (float)Math.Sqrt((double)(this.velocity.X * this.velocity.X + this.velocity.Y * this.velocity.Y));
                    float num240 = this.localAI[0];
                    if (num240 == 0f)
                    {
                        this.localAI[0] = num239;
                        num240 = num239;
                    }
                    if (this.alpha > 0)
                    {
                        this.alpha -= 25;
                    }
                    if (this.alpha < 0)
                    {
                        this.alpha = 0;
                    }
                    float num241 = this.position.X;
                    float num242 = this.position.Y;
                    float num243 = 800f;
                    bool flag8 = false;
                    int num244 = 0;
                    this.ai[0] += 1f;
                    if (this.ai[0] > 20f)
                    {
                        this.ai[0] -= 1f;
                        if (this.ai[1] == 0f)
{
                            for (int num245 = 0; num245 < Main.maxNPCs; num245++)
{
                                if (Main.npc[num245].CanBeChasedBy(this, false) && (this.ai[1] == 0f || this.ai[1] == (float)(num245 + 1)))
{
                                    float num246 = Main.npc[num245].position.X + (float)(Main.npc[num245].width / 2);
                                    float num247 = Main.npc[num245].position.Y + (float)(Main.npc[num245].height / 2);
                                    float num248 = Math.Abs(this.position.X + (float)(this.width / 2) - num246) + Math.Abs(this.position.Y + (float)(this.height / 2) - num247);
                                    if (num248 < num243 && Collision.CanHit(new Vector2(this.position.X + (float)(this.width / 2), this.position.Y + (float)(this.height / 2)), 1, 1, Main.npc[num245].position, Main.npc[num245].width, Main.npc[num245].height))
{
                                        num243 = num248;
                                        num241 = num246;
                                        num242 = num247;
                                        flag8 = true;
                                        num244 = num245;
                                    }
                                }
                            }
                            if (flag8)
{
                                this.ai[1] = (float)(num244 + 1);
                            }
                            flag8 = false;
                        }
                        if (this.ai[1] != 0f)
{
                            int num249 = (int)(this.ai[1] - 1f);
                            if (Main.npc[num249].active && Main.npc[num249].CanBeChasedBy(this, true))
{
                                float num250 = Main.npc[num249].position.X + (float)(Main.npc[num249].width / 2);
                                float num251 = Main.npc[num249].position.Y + (float)(Main.npc[num249].height / 2);
                                if (Math.Abs(this.position.X + (float)(this.width / 2) - num250) + Math.Abs(this.position.Y + (float)(this.height / 2) - num251) < 1000f)
{
                                    flag8 = true;
                                    num241 = Main.npc[num249].position.X + (float)(Main.npc[num249].width / 2);
                                    num242 = Main.npc[num249].position.Y + (float)(Main.npc[num249].height / 2);
                                }
                            }
                        }
                        if (!this.friendly)
{
                            flag8 = false;
                        }
                        if (flag8)
{
                            float num252 = num240;
                            Vector2 vector46 = new Vector2(this.position.X + (float)this.width * 0.5f, this.position.Y + (float)this.height * 0.5f);
                            float num253 = num241 - vector46.X;
                            float num254 = num242 - vector46.Y;
                            float num255 = (float)Math.Sqrt((double)(num253 * num253 + num254 * num254));
                            num255 = num252 / num255;
                            num253 *= num255;
                            num254 *= num255;
                            int num256 = 8;
                            this.velocity.X = (this.velocity.X * (float)(num256 - 1) + num253) / (float)num256;
                            this.velocity.Y = (this.velocity.Y * (float)(num256 - 1) + num254) / (float)num256;
                        }
                    }
                }
                else if (this.type == 507 || this.type == 508 || this.type == 662 || this.type == 680 || this.type == 685)
                {
                    if (this.ai[0] > 60f)
                    {
                        this.velocity.X = this.velocity.X * 0.98f;
                        this.velocity.Y = this.velocity.Y + 0.3f;
                    }
                }
                else if (this.type == 495)
                {
                    int num257 = Dust.NewDust(new Vector2(this.position.X - this.velocity.X, this.position.Y - this.velocity.Y), this.width, this.height, 27, this.velocity.X, this.velocity.Y, 100, default(Color), 1.2f);
                    Main.dust[num257].noGravity = true;
                    Main.dust[num257].velocity *= 0.3f;
                    if (this.ai[0] >= 30f)
                    {
                        this.ai[0] = 30f;
                        this.velocity.Y = this.velocity.Y + 0.04f;
                    }
                }
                else if (this.type == 498)
                {
                    if (this.localAI[0] == 0f)
                    {
                        this.localAI[0] += 1f;
                        SoundEngine.PlaySound(SoundID.Item17, this.position, 0f, 1f);
                    }
                    this.ai[0] += 1f;
                    if (this.ai[0] >= 50f)
                    {
                        this.velocity.X = this.velocity.X * 0.98f;
                        this.velocity.Y = this.velocity.Y + 0.15f;
                        this.rotation += (float)this.direction * 0.5f;
                    }
                    else
                    {
                        this.rotation = (float)Math.Atan2((double)this.velocity.Y, (double)this.velocity.X) + 1.57f;
                    }
                }
                else if (this.type == 437)
                {
                    if (this.ai[0] >= 12f)
                    {
                        if (this.ai[0] >= 20f)
{
                            this.Kill();
                        }
                        this.alpha += 30;
                    }
                }
                else if (this.type != 442 && this.type != 634 && this.type != 635 && this.type != 675)
                {
                    if (this.type == 686 || this.type == 711)
                    {
                        if (this.ai[0] >= 10f)
{
                            this.velocity.Y = this.velocity.Y + 0.1f;
                        }
                        if (this.ai[0] >= 20f)
{
                            this.velocity.Y = this.velocity.Y + 0.1f;
                        }
                        if (this.ai[0] > 20f)
{
                            this.ai[0] = 20f;
                        }
                        this.velocity.X = this.velocity.X * 0.99f;
                        if (this.velocity.Y > 32f)
{
                            this.velocity.Y = 32f;
                        }
                    }
                    else if (this.type == 639)
                    {
                        if (this.timeLeft <= this.MaxUpdates * 45 - 14)
{
                            this.velocity.Y = this.velocity.Y + 0.1f;
                        }
                    }
                    else if (this.type == 710)
                    {
                        if (this.ai[0] >= 0f)
{
                            this.ai[0] += 1f;
                            if (this.ai[0] >= 20f)
{
                                this.velocity.Y = this.velocity.Y + 0.2f;
                                if (this.velocity.Y > 0f)
{
                                    this.velocity.X = this.velocity.X * 0.98f;
                                }
                                if (this.velocity.Y > 12f)
{
                                    this.velocity.Y = 12f;
                                }
                            }
                        }
                    }
                    else if (this.ai[0] >= 15f)
                    {
                        this.ai[0] = 15f;
                        if (flag5)
{
                            this.velocity.Y = this.velocity.Y - 0.1f;
                        }
                        else
{
                            this.velocity.Y = this.velocity.Y + 0.1f;
                        }
                    }
                }
            }
            if (this.type == 921 || this.type == 926 || this.type == 937)
            {
                this.rotation += (Math.Abs(this.velocity.X) + Math.Abs(this.velocity.Y)) * 0.05f;
            }
            else if (this.type == 248)
            {
                if (this.velocity.X < 0f)
                {
                    this.rotation -= (Math.Abs(this.velocity.X) + Math.Abs(this.velocity.Y)) * 0.05f;
                }
                else
                {
                    this.rotation += (Math.Abs(this.velocity.X) + Math.Abs(this.velocity.Y)) * 0.05f;
                }
            }
            else if (this.type == 270 || this.type == 585 || this.type == 601 || this.type == 706 || this.type == 837)
            {
                this.spriteDirection = this.direction;
                if (this.direction < 0)
                {
                    this.rotation = (float)Math.Atan2((double)(-(double)this.velocity.Y), (double)(-(double)this.velocity.X));
                }
                else
                {
                    this.rotation = (float)Math.Atan2((double)this.velocity.Y, (double)this.velocity.X);
                }
            }
            else if (this.type == 311)
            {
                if (this.ai[1] != 0f)
                {
                    this.rotation += this.velocity.X * 0.1f + (float)Main.rand.Next(-10, 11) * 0.025f;
                }
                else
                {
                    this.rotation = (float)Math.Atan2((double)this.velocity.Y, (double)this.velocity.X) + 1.57f;
                }
            }
            else if (this.type == 1023)
            {
                this.rotation += MathHelper.Clamp(this.velocity.X * 0.025f, 0.19634955f, 0.5235988f);
            }
            else if (this.type == 312)
            {
                this.rotation += this.velocity.X * 0.02f;
            }
            else if (this.type == 675)
            {
                this.rotation += this.velocity.X * 0.03f;
            }
            else if (this.type != 676)
            {
                if (this.type == 408)
                {
                    this.rotation = this.velocity.ToRotation();
                    if (this.direction == -1)
                    {
                        this.rotation += 3.1415927f;
                    }
                }
                else if (this.type == 435 || this.type == 459 || this.type == 682 || this.type == 709)
                {
                    this.rotation = this.velocity.ToRotation();
                    if (this.direction == -1)
                    {
                        this.rotation += 3.1415927f;
                    }
                }
                else if (this.type == 660)
                {
                    this.rotation = this.velocity.ToRotation() + 0.7853982f;
                }
                else if (this.type == 662 || this.type == 685)
                {
                    this.rotation = this.velocity.ToRotation() - 3.1415927f - 0.7853982f;
                }
                else if (this.type == 680 || this.type == 684 || this.type == 686 || this.type == 711 || this.type == 712 || this.type == 1097)
                {
                    this.rotation = this.velocity.ToRotation() + 1.5707964f;
                }
                else if (this.type == 436)
                {
                    this.rotation = this.velocity.ToRotation();
                    this.rotation += 3.1415927f;
                    if (this.direction == -1)
                    {
                        this.rotation += 3.1415927f;
                    }
                }
                else if (this.type == 469)
                {
                    if (this.velocity.X > 0f)
                    {
                        this.spriteDirection = -1;
                        this.rotation = (float)Math.Atan2((double)this.velocity.Y, (double)this.velocity.X) + 1.57f;
                    }
                    else
                    {
                        this.spriteDirection = 1;
                        this.rotation = (float)Math.Atan2((double)this.velocity.Y, (double)this.velocity.X) + 1.57f;
                    }
                }
                else if (this.type == 477)
                {
                    if (this.localAI[1] < 5f)
                    {
                        this.rotation = (float)Math.Atan2((double)this.velocity.Y, (double)this.velocity.X) + 1.57f;
                        this.localAI[1] += 1f;
                    }
                    else
                    {
                        this.rotation = (this.rotation * 2f + (float)Math.Atan2((double)this.velocity.Y, (double)this.velocity.X) + 1.57f) / 3f;
                    }
                }
                else if (this.type == 532)
                {
                    this.rotation += 0.2f + Math.Abs(this.velocity.X) * 0.1f;
                }
                else if (this.type == 483)
                {
                    this.rotation += this.velocity.X * 0.05f;
                }
                else if (this.type == 772)
                {
                    this.rotation += (float)Math.Sign(this.velocity.X) * (Math.Abs(this.velocity.X) + Math.Abs(this.velocity.Y)) * 0.05f;
                }
                else if (this.type == 485)
                {
                    Vector2 vector47 = new Vector2(this.ai[0], this.ai[1]);
                    this.velocity = (this.velocity * 39f + vector47) / 40f;
                    int num258 = Dust.NewDust(this.position, this.width, this.height, 6, 0f, 0f, 0, default(Color), 1f);
                    Main.dust[num258].noGravity = true;
                    Main.dust[num258].velocity *= 0.2f;
                    Main.dust[num258].position = (Main.dust[num258].position + base.Center) / 2f;
                    this.frameCounter++;
                    if (this.frameCounter >= 2)
                    {
                        this.frameCounter = 0;
                        this.frame++;
                        if (this.frame >= 5)
{
                            this.frame = 0;
                        }
                    }
                    if (this.velocity.X < 0f)
                    {
                        this.spriteDirection = -1;
                        this.rotation = (float)Math.Atan2((double)(-(double)this.velocity.Y), (double)(-(double)this.velocity.X));
                    }
                    else
                    {
                        this.spriteDirection = 1;
                        this.rotation = (float)Math.Atan2((double)this.velocity.Y, (double)this.velocity.X);
                    }
                }
                else if (this.type == 640)
                {
                    if (this.velocity != Vector2.Zero)
                    {
                        this.rotation = this.velocity.ToRotation() + 1.5707964f;
                    }
                }
                else if (this.type == 325)
                {
                    this.rotation = this.velocity.ToRotation() - 1.5707964f;
                }
                else if (this.type != 344 && this.type != 498)
                {
                    this.rotation = (float)Math.Atan2((double)this.velocity.Y, (double)this.velocity.X) + 1.57f;
                }
            }
            bool flag9 = true;
            num = this.type;
            if (num == 577)
            {
                flag9 = false;
            }
            if (flag9)
            {
                if (flag5 && this.velocity.Y < -16f)
                {
                    this.velocity.Y = -16f;
                }
                if (this.velocity.Y > 16f)
                {
                    this.velocity.Y = 16f;
                }
            }
        }
References System.Math.Abs(), Terraria.NPC.active, Terraria.Player.active, Terraria.Projectile.active, Terraria.Lighting.AddLight(), Terraria.NPC.AI_121_QueenSlime_GetDustColor(), Terraria.Dust.alpha, System.array, System.Math.Atan2(), Terraria.NPC.CanBeChasedBy(), Terraria.Collision.CanHit(), Terraria.Collision.CanHitLine(), Terraria.DelegateMethods.CastLightOpen(), Terraria.Entity.Center, Microsoft.Xna.Framework.MathHelper.Clamp(), Terraria.Dust.CloneDust(), System.Math.Cos(), Terraria.ID.SoundID.DD2_BetsyFireballShot, Terraria.ID.SoundID.DD2_DarkMageAttack, Terraria.ID.SoundID.DD2_LightningBugZap, Terraria.ID.SoundID.DD2_PhantomPhoenixShot, Terraria.ID.SoundID.DD2_SkyDragonsFuryShot, Terraria.Player.dead, Terraria.Player.Directions, Terraria.Entity.Distance(), Microsoft.Xna.Framework.Vector2.Distance(), Terraria.NPC.dontTakeDamage, Terraria.Main.dust, Terraria.Main.expertMode, Terraria.Dust.fadeIn, Terraria.Player.FindClosest(), Terraria.NPC.friendly, ReLogic.Utilities.SlotId.FromFloat(), Terraria.Audio.SoundEngine.GetActiveSound(), Terraria.GameContent.PortalHelper.GetPortalColor(), Terraria.Framing.GetTileSafely(), Terraria.Entity.height, Terraria.Entity.Hitbox, Terraria.Main.hslToRgb(), Terraria.NewProjectileModifiers.IchorDartUpdatePenetrate(), Terraria.NPC.immune, int, Microsoft.Xna.Framework.Rectangle.Intersects(), ReLogic.Utilities.SlotId.Invalid, Terraria.ID.SoundID.Item1, Terraria.ID.SoundID.Item11, Terraria.ID.SoundID.Item114, Terraria.ID.SoundID.Item115, Terraria.ID.SoundID.Item12, Terraria.ID.SoundID.Item124, Terraria.ID.SoundID.Item125, Terraria.ID.SoundID.Item154, Terraria.ID.SoundID.Item155, Terraria.ID.SoundID.Item17, Terraria.ID.SoundID.Item171, Terraria.ID.SoundID.Item20, Terraria.ID.SoundID.Item33, Terraria.ID.SoundID.Item34, Terraria.ID.SoundID.Item36, Terraria.ID.SoundID.Item42, Terraria.ID.SoundID.Item5, Terraria.ID.SoundID.Item8, Terraria.ID.SoundID.Item9, Microsoft.Xna.Framework.Vector2.Length(), Microsoft.Xna.Framework.MathHelper.Lerp(), Microsoft.Xna.Framework.Vector2.Lerp(), Terraria.ID.NPCID.Sets.MagicAuraColor, Terraria.Main.maxNPCs, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Dust.NewDust(), Terraria.Dust.NewDustDirect(), Terraria.Dust.NewDustPerfect(), Terraria.Projectile.NewProjectile(), Terraria.NewProjectileModifier(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Utilities.UnifiedRandom.NextDouble(), Terraria.Dust.noGravity, Terraria.Dust.noLight, Terraria.Dust.noLightEmittance, Microsoft.Xna.Framework.Vector2.Normalize(), Terraria.Main.npc, Microsoft.Xna.Framework.Rectangle.Offset(), Microsoft.Xna.Framework.Vector2.One, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Audio.SoundEngine.PlayTrackedSound(), Terraria.Utils.PlotTileLine(), Terraria.Dust.position, Terraria.Entity.position, Terraria.Main.projectile, Terraria.Main.projFrames, Microsoft.Xna.Framework.Color.Purple, Terraria.Main.rand, Terraria.Utils.RandomVector2(), Terraria.Utils.Remap(), Terraria.Dust.scale, System.Math.Sign(), System.Math.Sin(), Terraria.WorldGen.SolidTile(), System.Math.Sqrt(), Terraria.Utils.TileActionAttempt(), ReLogic.Utilities.SlotId.ToFloat(), Microsoft.Xna.Framework.Color.ToVector3(), Microsoft.Xna.Framework.Color.Transparent, Terraria.Projectile.type, Microsoft.Xna.Framework.Vector2.UnitX, Microsoft.Xna.Framework.Vector2.UnitY, Terraria.Dust.velocity, Terraria.Entity.velocity, Microsoft.Xna.Framework.Color.White, Terraria.Entity.whoAmI, Terraria.Entity.width, Terraria.Main.worldSurface, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector3.X, Microsoft.Xna.Framework.Vector2.Y, Microsoft.Xna.Framework.Vector3.Y, Microsoft.Xna.Framework.Vector3.Z, and Microsoft.Xna.Framework.Vector2.Zero.