Terraria Decompiled: Terraria.Projectile.AI_047_MagnetSphere_TryAttacking
AI_047_MagnetSphere_TryAttacking()
void Terraria.Projectile.AI_047_MagnetSphere_TryAttacking () inline private
Definition at line 41764 of file Projectile.cs.
        {
            if (this.owner != Main.myPlayer)
            {
                return;
            }
            int[] array = new int[20];
            int num = 0;
            float num2 = 300f;
            bool flag = false;
            for (int i = 0; i < Main.maxNPCs; i++)
            {
                if (Main.npc[i].CanBeChasedBy(this, false))
                {
                    float num3 = Main.npc[i].position.X + (float)(Main.npc[i].width / 2);
                    float num4 = Main.npc[i].position.Y + (float)(Main.npc[i].height / 2);
                    if (Math.Abs(this.position.X + (float)(this.width / 2) - num3) + Math.Abs(this.position.Y + (float)(this.height / 2) - num4) < num2 && Collision.CanHit(base.Center, 1, 1, Main.npc[i].Center, 1, 1))
                    {
                        if (num < 20)
{
                            array[num] = i;
                            num++;
                        }
                        flag = true;
                    }
                }
            }
            if (this.timeLeft < 30)
            {
                flag = false;
            }
            if (flag)
            {
                int num5 = Main.rand.Next(num);
                num5 = array[num5];
                float num6 = Main.npc[num5].position.X + (float)(Main.npc[num5].width / 2);
                float num7 = Main.npc[num5].position.Y + (float)(Main.npc[num5].height / 2);
                this.localAI[0] += 1f;
                if (this.localAI[0] > 8f)
                {
                    this.localAI[0] = 0f;
                    float num8 = 6f;
                    Vector2 vector = new Vector2(this.position.X + (float)this.width * 0.5f, this.position.Y + (float)this.height * 0.5f);
                    vector += this.velocity * 4f;
                    float num9 = num6 - vector.X;
                    float num10 = num7 - vector.Y;
                    float num11 = (float)Math.Sqrt((double)(num9 * num9 + num10 * num10));
                    num11 = num8 / num11;
                    num9 *= num11;
                    num10 *= num11;
                    Projectile.NewProjectile(this.GetProjectileSource_FromThis(), vector.X, vector.Y, num9, num10, 255, this.damage, this.knockBack, this.owner, 0f, 0f, 0f, null);
                }
            }
        }
References System.Math.Abs(), System.array, Terraria.NPC.CanBeChasedBy(), Terraria.Collision.CanHit(), Terraria.Entity.Center, Terraria.Entity.height, Terraria.Main.maxNPCs, Terraria.Main.myPlayer, Terraria.Projectile.NewProjectile(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.npc, Terraria.Entity.position, Terraria.Main.rand, System.Math.Sqrt(), Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.