Terraria Decompiled: Terraria.Projectile.AI_171_GetColor
AI_171_GetColor()
Color Terraria.Projectile.AI_171_GetColor () inline
Definition at line 45807 of file Projectile.cs.
        {
            if (NPC.ShouldEmpressBeEnraged())
            {
                float lerpValue = Utils.GetLerpValue(0f, 60f, (float)((int)Main.time), true);
                return Color.Lerp(Color.White, Main.OurFavoriteColor, lerpValue) * this.Opacity;
            }
            return Main.hslToRgb((this.ai[1] + 0.5f) % 1f, 1f, 0.5f, byte.MaxValue) * this.Opacity;
        }
References Terraria.Utils.GetLerpValue(), Terraria.Main.hslToRgb(), Microsoft.Xna.Framework.Color.Lerp(), Terraria.Main.OurFavoriteColor, Terraria.NPC.ShouldEmpressBeEnraged(), Terraria.Main.time, and Microsoft.Xna.Framework.Color.White.
Referenced by Terraria.Main.DrawProj_FairyQueenLance(), and Terraria.Main.DrawProjDirect().