Terraria Decompiled: Terraria.Projectile.AI_067_FreakingPirates_TryJumpingToTarget
AI_067_FreakingPirates_TryJumpingToTarget()
void Terraria.Projectile.AI_067_FreakingPirates_TryJumpingToTarget (Vector2 targetVelocity, Vector2 toTarget, Vector2 targetCenter) inline private
Definition at line 51494 of file Projectile.cs.
        {
            bool flag = this.type == 1022;
            this.shouldFallThrough = targetCenter.Y > base.Bottom.Y;
            bool flag2 = this.velocity.Y == 0f;
            if (this.wet && this.velocity.Y > 0f && !this.shouldFallThrough)
            {
                flag2 = true;
            }
            bool flag3 = false;
            if (flag && (toTarget.Y < base.Center.Y - 160f || this.ai[0] == 1f) && !flag3 && this.ai[2] == 0f)
            {
                int num = 15;
                if (this.localAI[2] == 0f)
                {
                    ParticleOrchestrator.RequestParticleSpawn(true, ParticleOrchestraType.DeadCellsMushroomBoiTargetFound, new ParticleOrchestraSettings
                    {
                        PositionInWorld = base.Top,
                        UniqueInfoPiece = this.whoAmI
                    }, new int?(this.owner));
                }
                this.localAI[2] += 1f;
                if (this.localAI[2] >= (float)num)
                {
                    int num2 = 32;
                    Utils.ChaseResults chaseResults = Utils.GetChaseResults(base.Center, (float)num2, targetCenter, targetVelocity);
                    Vector2 vector = -Vector2.UnitY * (float)num2;
                    if (chaseResults.InterceptionHappens && chaseResults.InterceptionTime < 120f)
                    {
                        vector = chaseResults.ChaserVelocity;
                    }
                    else
                    {
                        vector = targetCenter.SafeNormalize(-Vector2.UnitY) * (float)num2;
                    }
                    this.velocity = vector;
                    this.ai[2] = 30f;
                    this.localAI[2] = 0f;
                    this.netUpdate = true;
                }
                flag3 = true;
            }
            int num3 = 30;
            if (this.type == 1093 && this.ai[0] == 3f)
            {
                num3 = 16;
            }
            if (toTarget.Y < base.Center.Y - (float)num3 && flag2 && !flag3)
            {
                double num4 = (double)((toTarget.Y - base.Center.Y) * -1f);
                float num5 = 0.4f;
                float num6 = (float)Math.Sqrt(num4 * (double)2f * (double)num5);
                if (num6 > 26f)
                {
                    num6 = 26f;
                }
                this.velocity.Y = -num6;
            }
        }
References Terraria.Utils.ChaseResults.ChaserVelocity, Terraria.Utils.GetChaseResults(), Terraria.Utils.ChaseResults.InterceptionHappens, Terraria.Utils.ChaseResults.InterceptionTime, Terraria.GameContent.Drawing.ParticleOrchestrator.RequestParticleSpawn(), System.Math.Sqrt(), Microsoft.Xna.Framework.Vector2.UnitY, and Microsoft.Xna.Framework.Vector2.Y.