Terraria Decompiled: Terraria.Projectile.AI_067_FreakingPirates
AI_067_FreakingPirates()
void Terraria.Projectile.AI_067_FreakingPirates () inline private
Definition at line 49649 of file Projectile.cs.
        {
            Player player = Main.player[this.owner];
            bool flag = this.type == 393 || this.type == 394 || this.type == 395;
            bool flag2 = this.type == 758;
            bool flag3 = this.type == 833 || this.type == 834 || this.type == 835;
            bool flag4 = this.type == 834 || this.type == 835;
            bool flag5 = this.type == 951;
            bool flag6 = this.type == 1022;
            bool flag7 = this.type == 1036;
            bool flag8 = this.type == 1093;
            float num = 0.4f;
            if (flag7)
            {
                if (!player.active || player.dead)
                {
                    player.cobWhipBuff = false;
                    this.Kill();
                    return;
                }
                if (player.cobWhipBuff)
                {
                    this.timeLeft = 2;
                }
            }
            if (!player.active)
            {
                if (flag7)
                {
                    player.coolWhipBuff = false;
                }
                this.active = false;
                return;
            }
            int num2 = 450;
            float num3 = 500f;
            float num4 = 300f;
            int num5 = 15;
            bool flag9 = player.petting.isPetting && player.petting.proj == this.whoAmI;
            if (flag8)
            {
                if (player.dead)
                {
                    player.palworldCattivaMinion = false;
                }
                if (player.palworldCattivaMinion)
                {
                    this.timeLeft = 2;
                }
                num2 = 800;
                int num6 = this.soundDelay - 1;
                this.soundDelay = num6;
                if (num6 == -20)
                {
                    SoundEngine.PlaySound(SoundID.PalCattiva, base.Center, 0f, 1f);
                }
                if (this.soundDelay == -1)
                {
                    SoundEngine.PlaySound(SoundID.PalSummon, base.Center, 0f, 1f);
                }
                if (flag9 && this.localAI[0] == 0f)
                {
                    this.localAI[0] = 60f;
                    SoundEngine.PlaySound(SoundID.PalCattivaJoy, base.Center, 0f, 1f);
                }
                if (this.localAI[0] > (float)(flag9 ? 1 : 0))
                {
                    this.localAI[0] -= 1f;
                }
            }
            if (flag6)
            {
                if (player.dead)
                {
                    player.deadCellsMushroomBoiMinion = false;
                }
                if (player.deadCellsMushroomBoiMinion)
                {
                    this.timeLeft = 2;
                }
                num2 = 800;
            }
            if (flag5)
            {
                if (player.dead)
                {
                    player.flinxMinion = false;
                }
                if (player.flinxMinion)
                {
                    this.timeLeft = 2;
                }
                num2 = 800;
            }
            if (flag)
            {
                if (player.dead)
                {
                    player.pirateMinion = false;
                }
                if (player.pirateMinion)
                {
                    this.timeLeft = 2;
                }
                num2 = 800;
            }
            if (flag3)
            {
                if (player.dead)
                {
                    player.stormTiger = false;
                }
                if (player.stormTiger)
                {
                    this.timeLeft = 2;
                }
                num2 = 800;
                if (this.ai[0] != 4f)
                {
                    if (this.velocity != Vector2.Zero && Main.rand.Next(18) == 0)
                    {
                        Dust dust = Main.dust[Dust.NewDust(this.position, this.width, this.height, 269, 0f, 0f, 0, default(Color), 1f)];
                        dust.fadeIn = 0.5f;
                        dust.scale = 0.3f;
                        dust.noLight = true;
                        dust.velocity += this.velocity * 0.005f;
                    }
                    if (this.type == 833)
                    {
                        Lighting.AddLight(base.Center, Vector3.One * 0.5f);
                    }
                    if (this.type == 834)
                    {
                        Lighting.AddLight(base.Center, Vector3.One * 0.8f);
                    }
                    if (this.type == 835)
                    {
                        Lighting.AddLight(base.Center, Color.Lerp(Main.OurFavoriteColor, Color.White, 0.8f).ToVector3() * 1f);
                    }
                }
                if (this.owner == Main.myPlayer)
                {
                    if (this.localAI[0] <= 0f)
                    {
                        int num7;
                        switch (this.type)
{
                        default:
                            num7 = 360;
                            break;
                        case 834:
                            num7 = 300;
                            break;
                        case 835:
                            num7 = 240;
                            break;
                        }
                        if (this.damage != 0)
{
                            bool flag10 = this.AI_067_TigerSpecialAttack();
                            this.localAI[0] = (float)(flag10 ? num7 : 10);
                        }
                    }
                    else
                    {
                        this.localAI[0] -= 1f;
                    }
                }
            }
            if (flag2)
            {
                if (player.dead)
                {
                    player.vampireFrog = false;
                }
                if (player.vampireFrog)
                {
                    this.timeLeft = 2;
                }
                num2 = 800;
            }
            if (this.type == 500)
            {
                num3 = 200f;
                if (player.dead)
                {
                    player.crimsonHeart = false;
                }
                if (player.crimsonHeart)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 653)
            {
                num3 = 300f;
                if (player.dead)
                {
                    player.companionCube = false;
                }
                if (player.companionCube)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 1018)
            {
                num3 = 200f;
                if (player.dead)
                {
                    player.petFlagDirtiestBlock = false;
                }
                if (player.petFlagDirtiestBlock)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 1056)
            {
                num3 = 200f;
                if (player.dead)
                {
                    player.petFlagBoulderPet = false;
                }
                if (player.petFlagBoulderPet)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 1090)
            {
                num3 = 200f;
                if (player.dead)
                {
                    player.petFlagRainbowBoulderPet = false;
                }
                if (player.petFlagRainbowBoulderPet)
                {
                    this.timeLeft = 2;
                }
            }
            if (flag3 && this.ai[0] == 4f)
            {
                this.velocity = Vector2.Zero;
                this.frame = 9;
                if (flag4)
                {
                    this.frame = 11;
                }
                this.ai[1] -= 1f;
                if (this.ai[1] > 0f)
                {
                    return;
                }
                this.ai[0] = 0f;
                this.ai[1] = 0f;
                this.netUpdate = true;
            }
            Vector2 vector = player.Center;
            if (flag6)
            {
                vector.X -= (float)((45 + player.width / 2) * player.direction);
                vector.X -= (float)(this.minionPos * 30 * player.direction);
            }
            else if (flag5)
            {
                vector.X -= (float)((45 + player.width / 2) * player.direction);
                vector.X -= (float)(this.minionPos * 30 * player.direction);
            }
            else if (flag)
            {
                vector.X -= (float)((15 + player.width / 2) * player.direction);
                vector.X -= (float)(this.minionPos * 20 * player.direction);
            }
            else if (flag8)
            {
                vector.X -= (float)((30 + player.width / 2) * player.direction);
                vector.X -= (float)(this.minionPos * 20 * player.direction);
            }
            else if (flag3)
            {
                vector.X -= (float)((15 + player.width / 2) * player.direction);
                vector.X -= (float)(this.minionPos * 40 * player.direction);
            }
            else if (flag2)
            {
                vector.X -= (float)((35 + player.width / 2) * player.direction);
                vector.X -= (float)(this.minionPos * 40 * player.direction);
            }
            else if (this.type == 500)
            {
                vector.X -= (float)((15 + player.width / 2) * player.direction);
                vector.X -= (float)(40 * player.direction);
            }
            else if (this.type == 1018)
            {
                vector.X = player.Center.X;
            }
            else if (this.type == 1056)
            {
                vector.X -= (float)((15 + player.width / 2) * player.direction);
            }
            else if (this.type == 1090)
            {
                vector.X -= (float)((15 + player.width / 2) * player.direction);
            }
            else if (this.type == 653)
            {
                vector.X = player.Center.X;
            }
            if (this.type == 500)
            {
                Lighting.AddLight(base.Center, 0.9f, 0.1f, 0.3f);
                int num8 = 6;
                if (this.frame == 0 || this.frame == 2)
                {
                    num8 = 12;
                }
                int num6 = this.frameCounter + 1;
                this.frameCounter = num6;
                if (num6 >= num8)
                {
                    this.frameCounter = 0;
                    num6 = this.frame + 1;
                    this.frame = num6;
                    if (num6 >= Main.projFrames[this.type])
                    {
                        this.frame = 0;
                    }
                }
                this.rotation += this.velocity.X / 20f;
                Vector2 vector2 = (-Vector2.UnitY).RotatedBy((double)this.rotation, default(Vector2)).RotatedBy((double)((float)this.direction * 0.2f), default(Vector2));
                int num9 = Dust.NewDust(base.Center + vector2 * 10f - new Vector2(4f), 0, 0, 5, vector2.X, vector2.Y, 0, Color.Transparent, 1f);
                Main.dust[num9].scale = 1f;
                Main.dust[num9].velocity = vector2.RotatedByRandom(0.7853981852531433) * 3.5f;
                Main.dust[num9].noGravity = true;
                Main.dust[num9].shader = GameShaders.Armor.GetSecondaryShader(Main.player[this.owner].cLight, Main.player[this.owner]);
            }
            if (this.type == 1018)
            {
                this.rotation += this.velocity.X / 20f;
            }
            if (this.type == 1056 || this.type == 1090)
            {
                this.rotation += this.velocity.X / 16f;
            }
            if (this.type == 653)
            {
                this.rotation += this.velocity.X / 20f;
                bool flag11 = this.owner >= 0 && this.owner < 255;
                if (flag11)
                {
                    Projectile._CompanionCubeScreamCooldown[this.owner] -= 1f;
                    if (Projectile._CompanionCubeScreamCooldown[this.owner] < 0f)
                    {
                        Projectile._CompanionCubeScreamCooldown[this.owner] = 0f;
                    }
                }
                Tile tileSafely = Framing.GetTileSafely(base.Center);
                if (tileSafely.liquid > 0 && tileSafely.lava())
                {
                    this.localAI[0] += 1f;
                }
                else
                {
                    this.localAI[0] -= 1f;
                }
                this.localAI[0] = MathHelper.Clamp(this.localAI[0], 0f, 20f);
                if (this.localAI[0] >= 20f)
                {
                    if (flag11 && Projectile._CompanionCubeScreamCooldown[this.owner] == 0f)
                    {
                        Projectile._CompanionCubeScreamCooldown[this.owner] = 3600f;
                        SoundEngine.PlaySound((Main.rand.Next(10) == 0) ? SoundID.NPCDeath61 : SoundID.NPCDeath59, this.position, 0f, 1f);
                    }
                    this.Kill();
                }
                if (flag11 && this.owner == Main.myPlayer && Main.netMode != 2)
                {
                    Vector3 vector3 = Lighting.GetColor((int)base.Center.X / 16, (int)base.Center.Y / 16).ToVector3();
                    Vector3 vector4 = Lighting.GetColor((int)player.Center.X / 16, (int)player.Center.Y / 16).ToVector3();
                    if (vector3.Length() < 0.15f && vector4.Length() < 0.15f)
                    {
                        this.localAI[1] += 1f;
                    }
                    else if (this.localAI[1] > 0f)
                    {
                        this.localAI[1] -= 1f;
                    }
                    this.localAI[1] = MathHelper.Clamp(this.localAI[1], -3600f, 120f);
                    if (this.localAI[1] > (float)Main.rand.Next(30, 120) && !player.immune && player.velocity == Vector2.Zero)
                    {
                        if (Main.rand.Next(5) == 0)
{
                            SoundEngine.PlaySound(SoundID.Item16, base.Center, 0f, 1f);
                            this.localAI[1] = -600f;
                        }
                        else
{
                            SoundEngine.PlaySound(SoundID.Item1, base.Center, 0f, 1f);
                            player.Hurt(PlayerDeathReason.ByOther(6), 3, 0, false, false, false, -1, true);
                            player.immune = false;
                            player.immuneTime = 0;
                            this.localAI[1] = (float)(-300 + Main.rand.Next(30) * -10);
                        }
                    }
                }
            }
            bool flag12 = true;
            if (this.type == 500 || this.type == 653 || this.type == 1018 || this.type == 1056 || this.type == 1090)
            {
                flag12 = false;
            }
            this.shouldFallThrough = player.position.Y + (float)player.height - 12f > this.position.Y + (float)this.height;
            this.friendly = false;
            int num10 = 0;
            int num11 = 15;
            int num12 = -1;
            bool flag13 = true;
            bool flag14 = this.ai[0] == 5f;
            if (flag7)
            {
                num11 = 5;
                num10 = 0;
                flag13 = false;
                this.friendly = true;
            }
            if (flag6)
            {
                flag13 = false;
                this.friendly = true;
            }
            if (flag5)
            {
                flag13 = false;
                this.friendly = true;
            }
            if (flag2)
            {
                this.friendly = true;
                num11 = 20;
                num10 = 60;
            }
            if (flag3)
            {
                flag13 = false;
                this.friendly = true;
                this.originalDamage = player.highestStormTigerGemOriginalDamage;
            }
            if (flag8)
            {
                num11 = 16;
                this.DoPalAppearEffect(player, this.ai[0] != 1f);
                this.AI_067_FreakingPirates_TryAssigningHelp();
            }
            bool flag15 = this.ai[0] == 0f;
            if (flag3 && flag14)
            {
                flag15 = true;
            }
            if (flag6)
            {
                flag15 = this.ai[0] == 0f || this.ai[0] == 1f;
            }
            if (flag15 && flag12)
            {
                bool flag16 = true;
                if (flag7)
                {
                    flag16 = false;
                }
                this.Minion_FindTargetInRange(num2, ref num12, true, new Func<Entity, int, bool>(this.AI_067_CustomEliminationCheck_Pirates), flag16);
            }
            if (flag8 && num12 >= 0 && this.ai[0] == 3f && this.owner == Main.myPlayer)
            {
                this.ai[0] = 0f;
                this.ai[1] = 0f;
                this.localAI[0] = 0f;
                this.localAI[1] = 0f;
                this.netUpdate = true;
            }
            if (!flag3 || !flag14)
            {
                if (flag6)
                {
                    if (this.ai[2] > 0f && num12 >= 0)
                    {
                        float num13 = 60f;
                        NPC npc = Main.npc[num12];
                        vector = npc.Center;
                        float num14;
                        float num15;
                        bool flag17;
                        if (this.IsInRangeOfMeOrMyOwner(npc, num13, out num14, out num15, out flag17))
{
                            this.ai[2] = -120f;
                            if (this.owner == Main.myPlayer)
{
                                Projectile.NewProjectile(this.GetProjectileSource_FromThis(), base.Center, Vector2.Zero, 1044, (int)((float)this.damage * 1.33f), this.knockBack * 3f, this.owner, 0f, 2f, 0f, null);
                            }
                            Vector2 center = base.Center;
                            base.Center = player.Center;
                            this.velocity = new Vector2(-2f + Main.rand.NextFloat() * 4f, 1f + Main.rand.NextFloat());
                            this.netUpdate = true;
                        }
                    }
                    if (this.ai[2] < 0f)
                    {
                        this.ai[2] += 1f;
                    }
                    else if (this.velocity.Y == 0f)
                    {
                        this.ai[2] = 0f;
                    }
                    else
                    {
                        float[] array = this.ai;
                        int num16 = 2;
                        float num17 = array[num16] - 1f;
                        array[num16] = num17;
                        if (num17 < 0f)
{
                            this.ai[2] = 0f;
                        }
                    }
                }
                if (this.ai[0] == 1f)
                {
                    if (Main.netMode != 2 && this.type == 1090 && Main.LocalPlayer.miscCounter % 2 == 0)
                    {
                        ParticleOrchestrator.RequestParticleSpawn(true, ParticleOrchestraType.ShimmerBlock, new ParticleOrchestraSettings
{
                            PositionInWorld = base.Center + Main.rand.NextVector2CircularEdge((float)(this.width / 2), (float)(this.height / 2)),
                            MovementVector = this.velocity * 0.05f,
                            UniqueInfoPiece = 500
                        }, null);
                    }
                    this.tileCollide = false;
                    float num18 = 0.2f;
                    float num19 = 10f;
                    int num20 = 200;
                    if (this.type == 1090)
                    {
                        num19 = 18f;
                    }
                    if (num19 < Math.Abs(player.velocity.X) + Math.Abs(player.velocity.Y))
                    {
                        num19 = Math.Abs(player.velocity.X) + Math.Abs(player.velocity.Y);
                    }
                    Vector2 vector5 = player.Center - base.Center;
                    float num21 = vector5.Length();
                    if (num21 > 2000f)
                    {
                        this.position = player.Center - new Vector2((float)this.width, (float)this.height) / 2f;
                    }
                    if (num21 < (float)num20 && player.velocity.Y == 0f && this.position.Y + (float)this.height <= player.position.Y + (float)player.height && !Collision.SolidCollision(this.position, this.width, this.height))
                    {
                        this.ai[0] = 0f;
                        this.netUpdate = true;
                        if (this.velocity.Y < -6f)
{
                            this.velocity.Y = -6f;
                        }
                    }
                    if (flag8 && num21 < (float)num20 && player.velocity.Y == 0f)
                    {
                        this.ai[0] = 0f;
                        this.netUpdate = true;
                        base.Center = player.MountedCenter;
                    }
                    int num22 = 60;
                    if (this.type == 1090)
                    {
                        num22 = 350;
                    }
                    if (num21 < (float)num22)
                    {
                        this.localAI[0] = 0f;
                        if (this.type == 1090 && this.velocity.Length() < num19)
{
                            if (this.velocity == Vector2.Zero)
{
                                this.velocity = new Vector2(0f, -1f);
                            }
                            this.velocity = this.velocity.SafeNormalize(Vector2.Zero) * num19;
                        }
                    }
                    else
                    {
                        vector5.Normalize();
                        vector5 *= num19;
                        if (this.type == 1090)
{
                            this.velocity = vector5.RotatedByRandom(0.5235987901687622);
                            if (this.localAI[0] == 0f)
{
                                this.localAI[0] = 1f;
                                ParticleOrchestrator.RequestParticleSpawn(true, ParticleOrchestraType.RainbowBoulderPetBounce, new ParticleOrchestraSettings
{
                                    PositionInWorld = base.Center,
                                    MovementVector = this.velocity
                                }, null);
                            }
                        }
                        else
{
                            if (this.velocity.X < vector5.X)
{
                                this.velocity.X = this.velocity.X + num18;
                                if (this.velocity.X < 0f)
{
                                    this.velocity.X = this.velocity.X + num18 * 1.5f;
                                }
                            }
                            if (this.velocity.X > vector5.X)
{
                                this.velocity.X = this.velocity.X - num18;
                                if (this.velocity.X > 0f)
{
                                    this.velocity.X = this.velocity.X - num18 * 1.5f;
                                }
                            }
                            if (this.velocity.Y < vector5.Y)
{
                                this.velocity.Y = this.velocity.Y + num18;
                                if (this.velocity.Y < 0f)
{
                                    this.velocity.Y = this.velocity.Y + num18 * 1.5f;
                                }
                            }
                            if (this.velocity.Y > vector5.Y)
{
                                this.velocity.Y = this.velocity.Y - num18;
                                if (this.velocity.Y > 0f)
{
                                    this.velocity.Y = this.velocity.Y - num18 * 1.5f;
                                }
                            }
                        }
                    }
                    if (this.velocity.X != 0f)
                    {
                        this.spriteDirection = Math.Sign(this.velocity.X);
                    }
                    if (flag6)
                    {
                        this.frame = 1;
                        this.rotation = this.velocity.X * 0.1f;
                    }
                    if (flag5)
                    {
                        this.frameCounter++;
                        if (this.frameCounter > 3)
{
                            this.frame++;
                            this.frameCounter = 0;
                        }
                        if (this.frame < 2 || this.frame >= Main.projFrames[this.type])
{
                            this.frame = 2;
                        }
                        this.rotation = this.rotation.AngleTowards(this.rotation + 0.25f * (float)this.spriteDirection, 0.25f);
                    }
                    if (flag)
                    {
                        this.frameCounter++;
                        if (this.frameCounter > 3)
{
                            this.frame++;
                            this.frameCounter = 0;
                        }
                        if (this.frame < 10 || this.frame > 13)
{
                            this.frame = 10;
                        }
                        this.rotation = this.velocity.X * 0.1f;
                    }
                    if (flag8)
                    {
                        this.frame = 1;
                        if (player.velocity.Y >= -6f)
{
                            this.frame = 0;
                        }
                        if (player.velocity.Y >= 6f)
{
                            this.frame = 2;
                        }
                        base.Center = player.MountedCenter + new Vector2((float)(player.direction * -8), -24f);
                        this.position = this.position.Floor();
                        this.direction = (this.spriteDirection = player.direction);
                        this.velocity = Vector2.Zero;
                        if (player.mount.Active && MountID.Sets.PlayerIsHidden[player.mount.Type])
{
                            this.alpha = 255;
                        }
                    }
                    if (flag2)
                    {
                        int num23 = 3;
                        int num6 = this.frameCounter + 1;
                        this.frameCounter = num6;
                        if (num6 >= num23 * 4)
{
                            this.frameCounter = 0;
                        }
                        this.frame = 14 + this.frameCounter / num23;
                        this.rotation = this.velocity.X * 0.15f;
                    }
                    if (flag3)
                    {
                        this.frame = 8;
                        if (flag4)
{
                            this.frame = 10;
                        }
                        this.rotation += 0.6f * (float)this.spriteDirection;
                    }
                    if (this.type == 1056 || this.type == 1090)
                    {
                        this.rotation += 0.5f * (float)this.spriteDirection;
                    }
                    if (this.type == 1018 && Main.LocalPlayer.miscCounter % 3 == 0)
                    {
                        int num24 = 2;
                        Dust dust2 = Main.dust[Dust.NewDust(this.position + new Vector2((float)(-(float)num24), (float)(-(float)num24)), 16 + num24 * 2, 16 + num24 * 2, 0, 0f, 0f, 0, default(Color), 0.8f)];
                        dust2.velocity = -this.velocity * 0.25f;
                        dust2.velocity = dust2.velocity.RotatedByRandom(0.2617993950843811);
                    }
                }
                if (this.ai[0] == 2f && this.ai[1] < 0f)
                {
                    this.friendly = false;
                    this.ai[1] += 1f;
                    if (num11 >= 0)
                    {
                        this.ai[1] = 0f;
                        this.ai[0] = 0f;
                        this.netUpdate = true;
                        return;
                    }
                }
                else if (this.ai[0] == 2f)
                {
                    this.spriteDirection = this.direction;
                    this.rotation = 0f;
                    if (flag)
                    {
                        this.friendly = true;
                        this.frame = 4 + (int)((float)num11 - this.ai[1]) / (num11 / 3);
                        if (this.velocity.Y != 0f)
{
                            this.frame += 3;
                        }
                    }
                    if (flag8)
                    {
                        this.friendly = true;
                        if (this.ai[1] == (float)(num11 - 1) && this.velocity.Y == 0f)
{
                            this.velocity.X = this.velocity.X * 0.3f;
                        }
                        this.frame = 3 + (int)((float)num11 - this.ai[1]) / (num11 / 4);
                        if ((int)this.ai[1] % 4 == 0)
{
                            for (int i = 0; i < 3; i++)
{
                                Dust dust3 = Dust.NewDustDirect(base.Center + new Vector2((float)(this.direction * 8), -4f), 8, 8, 16, (float)(-(float)this.direction * 2), 0f, 127, default(Color), 1f);
                                dust3.velocity *= 0.5f;
                                dust3.scale *= 0.8f;
                                dust3.velocity.Y = dust3.velocity.Y - 0.2f;
                            }
                        }
                    }
                    if (flag2)
                    {
                        float num25 = ((float)num11 - this.ai[1]) / (float)num11;
                        if ((double)num25 > 0.25 && (double)num25 < 0.75)
{
                            this.friendly = true;
                        }
                        int num26 = (int)(num25 * 5f);
                        if (num26 > 2)
{
                            num26 = 4 - num26;
                        }
                        if (this.velocity.Y != 0f)
{
                            this.frame = 21 + num26;
                        }
                        else
{
                            this.frame = 18 + num26;
                        }
                        if (this.velocity.Y == 0f)
{
                            this.velocity.X = this.velocity.X * 0.8f;
                        }
                    }
                    this.velocity.Y = this.velocity.Y + 0.4f;
                    if (this.velocity.Y > 10f)
                    {
                        this.velocity.Y = 10f;
                    }
                    this.ai[1] -= 1f;
                    if (this.ai[1] <= 0f)
                    {
                        if (num10 <= 0)
{
                            this.ai[1] = 0f;
                            this.ai[0] = 0f;
                            this.netUpdate = true;
                            return;
                        }
                        this.ai[1] = (float)(-(float)num10);
                    }
                }
                if (flag6 && num12 < 0)
                {
                    this.localAI[2] = 0f;
                }
                if (num12 >= 0)
                {
                    flag9 = false;
                    float num27 = (float)num2;
                    float num28 = 20f;
                    if (flag2)
                    {
                        num28 = 50f;
                    }
                    NPC npc2 = Main.npc[num12];
                    Vector2 vector6 = npc2.Center;
                    Vector2 vector7 = vector6;
                    if (flag6)
                    {
                        vector6 += new Vector2(num28 + 7f, 0f) * (float)this.direction;
                    }
                    vector = vector6;
                    float num29;
                    float num30;
                    bool flag18;
                    if (this.IsInRangeOfMeOrMyOwner(npc2, num27, out num29, out num30, out flag18))
                    {
                        this.AI_067_FreakingPirates_TryJumpingToTarget(npc2.velocity, vector6, vector7);
                        if (flag13 && Vector2.Distance(base.Center, vector) < num28)
{
                            if (this.velocity.Length() > 10f)
{
                                this.velocity /= this.velocity.Length() / 10f;
                            }
                            this.ai[0] = 2f;
                            this.ai[1] = (float)num11;
                            this.netUpdate = true;
                            this.direction = ((vector6.X - base.Center.X > 0f) ? 1 : (-1));
                        }
                        if (flag3)
{
                            Point point = npc2.Top.ToTileCoordinates();
                            int j = 0;
                            int num31 = point.Y;
                            while (j < num5)
{
                                Tile tile = Main.tile[point.X, num31];
                                if (tile == null || tile.active())
{
                                    break;
                                }
                                j++;
                                num31++;
                            }
                            if (j >= num5)
{
                                this.ai[0] = 5f;
                                this.ai[1] = 0f;
                                this.netUpdate = true;
                                return;
                            }
                            if (base.Hitbox.Intersects(npc2.Hitbox) && this.velocity.Y >= 0f)
{
                                this.velocity.Y = -4f;
                                this.velocity.X = (float)(this.direction * 10);
                            }
                        }
                    }
                    if (flag2)
                    {
                        int num32 = 1;
                        if (vector6.X - base.Center.X < 0f)
{
                            num32 = -1;
                        }
                        vector.X += (float)(20 * -(float)num32);
                    }
                }
                if (this.ai[0] == 0f && num12 < 0 && !flag7)
                {
                    bool flag19 = false;
                    Vector2 vector8 = player.Center - base.Center;
                    if (vector8.Length() > 2000f)
                    {
                        this.position = player.Center - new Vector2((float)this.width, (float)this.height) / 2f;
                    }
                    else if (vector8.Length() > num3 || Math.Abs(vector8.Y) > num4)
                    {
                        flag19 = true;
                        if (this.velocity.Y > 0f && vector8.Y < 0f)
{
                            this.velocity.Y = 0f;
                        }
                        if (this.velocity.Y < 0f && vector8.Y > 0f)
{
                            this.velocity.Y = 0f;
                        }
                    }
                    if (flag19)
                    {
                        this.ai[0] = 1f;
                        this.netUpdate = true;
                        if (this.type == 1093)
{
                            this.alpha = 255;
                        }
                    }
                }
                if (this.ai[0] == 0f || this.ai[0] == 3f)
                {
                    if (num12 < 0)
                    {
                        if (base.Distance(player.Center) > 60f && base.Distance(vector) > 60f && Math.Sign(vector.X - player.Center.X) != Math.Sign(base.Center.X - player.Center.X))
{
                            vector = player.Center;
                        }
                        if (this.ai[0] == 3f)
{
                            vector = new Vector2(this.ai[1] * 16f + 8f, this.ai[2] * 16f + 8f);
                            this.AI_067_FreakingPirates_TryJumpingToTarget(Vector2.Zero, vector, vector);
                            float num33 = Vector2.Distance(base.Hitbox.ClosestPointInRect(vector), vector);
                            if (flag13 && num33 < 20f)
{
                                if (this.velocity.Length() > 10f)
{
                                    this.velocity /= this.velocity.Length() / 10f;
                                }
                                this.ai[0] = 2f;
                                this.ai[1] = (float)num11;
                                this.netUpdate = true;
                                this.direction = ((vector.X - base.Center.X > 0f) ? 1 : (-1));
                                this.AI_067_FreakingPirates_HitIntention(vector);
                            }
                        }
                        Rectangle rectangle = Utils.CenteredRectangle(vector, base.Size);
                        int num34 = 0;
                        while (num34 < 20 && !Collision.SolidCollision(rectangle.TopLeft(), rectangle.Width, rectangle.Height))
{
                            rectangle.Y += 16;
                            vector.Y += 16f;
                            num34++;
                        }
                        Vector2 vector9 = vector - player.Center;
                        Vector2 vector10 = Collision.TileCollision(player.Center - base.Size / 2f, vector9, this.width, this.height, false, false, 1, false, false, true);
                        vector = player.Center - base.Size / 2f + vector10 + base.Size / 2f;
                        if (base.Distance(vector) < 32f && this.ai[0] != 3f)
{
                            float num35 = player.Center.Distance(vector);
                            if (player.Center.Distance(base.Center) < num35)
{
                                vector = base.Center;
                            }
                        }
                        Vector2 vector11 = player.Center - vector;
                        if (vector11.Length() > num3 || Math.Abs(vector11.Y) > num4)
{
                            Rectangle rectangle2 = Utils.CenteredRectangle(player.Center, base.Size);
                            Vector2 vector12 = vector - player.Center;
                            Vector2 vector13 = rectangle2.TopLeft();
                            for (float num36 = 0f; num36 < 1f; num36 += 0.05f)
{
                                Vector2 vector14 = rectangle2.TopLeft() + vector12 * num36;
                                if (Collision.SolidCollision(rectangle2.TopLeft() + vector12 * num36, rectangle.Width, rectangle.Height))
{
                                    break;
                                }
                                vector13 = vector14;
                            }
                            vector = vector13 + base.Size / 2f;
                        }
                    }
                    this.tileCollide = true;
                    float num37 = 0.5f;
                    float num38 = 4f;
                    float num39 = 4f;
                    float num40 = 0.1f;
                    if (flag6 && num12 != -1)
                    {
                        num37 = 0.8f;
                        num38 = 6f;
                        num39 = 6f;
                    }
                    if (flag5 && num12 != -1)
                    {
                        num37 = 0.65f;
                        num38 = 5.5f;
                        num39 = 5.5f;
                    }
                    if (flag && num12 != -1)
                    {
                        num37 = 1f;
                        num38 = 8f;
                        num39 = 8f;
                    }
                    if (flag8 && num12 != -1)
                    {
                        num37 = 0.3f;
                        num38 = 6f;
                        num39 = 6f;
                    }
                    if (flag2 && num12 != -1)
                    {
                        num37 = 0.7f;
                        num38 = 6f;
                        num39 = 6f;
                    }
                    if (flag3 && num12 != -1)
                    {
                        num37 = 1f;
                        num38 = 8f;
                        num39 = 8f;
                    }
                    if (num39 < Math.Abs(player.velocity.X) + Math.Abs(player.velocity.Y))
                    {
                        num39 = Math.Abs(player.velocity.X) + Math.Abs(player.velocity.Y);
                        num37 = 0.7f;
                    }
                    if (this.type == 653 || this.type == 1018)
                    {
                        float num41 = player.velocity.Length();
                        if (num41 < 0.1f)
{
                            num41 = 0f;
                        }
                        if (num41 != 0f && num41 < num39)
{
                            num39 = num41;
                        }
                    }
                    int num42 = 0;
                    bool flag20 = false;
                    bool flag21 = flag9;
                    float num43 = vector.X - base.Center.X;
                    Vector2 vector15 = vector - base.Center;
                    if (flag21)
                    {
                        num43 = 0f;
                    }
                    if ((this.type == 1056 || this.type == 1090) && Math.Abs(num43) < 50f)
                    {
                        float num44 = player.velocity.Length();
                        if (num44 < 0.1f)
{
                            num44 = 0f;
                        }
                        if (num44 != 0f && num44 < num39)
{
                            num39 = num44;
                        }
                        if (this.velocity.Length() <= 0.3f)
{
                            this.rotation = MathHelper.WrapAngle(this.rotation).AngleLerp(0f, 0.1f);
                        }
                        this.velocity.X = this.velocity.X * 0.9f;
                        if (Math.Abs(this.velocity.X) < 0.1f)
{
                            this.velocity.X = 0f;
                        }
                    }
                    else if (this.type == 1018 && Math.Abs(num43) < 50f)
                    {
                        this.rotation = this.rotation.AngleTowards(0f, 0.2f);
                        this.velocity.X = this.velocity.X * 0.9f;
                        if ((double)Math.Abs(this.velocity.X) < 0.1)
{
                            this.velocity.X = 0f;
                        }
                    }
                    else if (this.type == 653 && Math.Abs(num43) < 150f)
                    {
                        this.rotation = this.rotation.AngleTowards(0f, 0.2f);
                        this.velocity.X = this.velocity.X * 0.9f;
                        if ((double)Math.Abs(this.velocity.X) < 0.1)
{
                            this.velocity.X = 0f;
                        }
                    }
                    else if (Math.Abs(num43) > 5f)
                    {
                        if (num43 < 0f)
{
                            num42 = -1;
                            if (this.velocity.X > -num38)
{
                                this.velocity.X = this.velocity.X - num37;
                            }
                            else
{
                                this.velocity.X = this.velocity.X - num40;
                            }
                        }
                        else
{
                            num42 = 1;
                            if (this.velocity.X < num38)
{
                                this.velocity.X = this.velocity.X + num37;
                            }
                            else
{
                                this.velocity.X = this.velocity.X + num40;
                            }
                        }
                        bool flag22 = true;
                        if (flag6)
{
                            flag22 = false;
                        }
                        if (flag)
{
                            flag22 = false;
                        }
                        if (flag8)
{
                            flag22 = false;
                        }
                        if (this.type == 653)
{
                            flag22 = false;
                        }
                        if (this.type == 1018)
{
                            flag22 = false;
                        }
                        if ((this.type == 1056 || this.type == 1090) && this.velocity.Length() <= 5f)
{
                            flag22 = false;
                        }
                        if (this.type == 1036)
{
                            flag22 = false;
                        }
                        if (flag2 && num12 == -1)
{
                            flag22 = false;
                        }
                        if (flag3)
{
                            flag22 = vector15.Y < -80f;
                        }
                        if (flag5)
{
                            flag22 = num12 > -1 && Main.npc[num12].Hitbox.Intersects(base.Hitbox);
                        }
                        if (flag22)
{
                            flag20 = true;
                        }
                    }
                    else
                    {
                        this.velocity.X = this.velocity.X * 0.9f;
                        if (Math.Abs(this.velocity.X) < num37 * 2f)
{
                            this.velocity.X = 0f;
                        }
                    }
                    bool flag23 = Math.Abs(vector15.X) >= 64f || (vector15.Y <= -48f && Math.Abs(vector15.X) >= 8f);
                    if (flag21)
                    {
                        flag23 = false;
                    }
                    if (num42 != 0 && flag23)
                    {
                        int num45 = (int)(this.position.X + (float)(this.width / 2)) / 16;
                        int num46 = (int)this.position.Y / 16;
                        num45 += num42;
                        num45 += (int)this.velocity.X;
                        for (int k = num46; k < num46 + this.height / 16 + 1; k++)
{
                            if (WorldGen.SolidTile(num45, k, false))
{
                                flag20 = true;
                            }
                        }
                    }
                    if (this.type == 500 && this.velocity.X != 0f)
                    {
                        flag20 = true;
                    }
                    if (this.type == 653 && Math.Abs(this.velocity.X) > 3f)
                    {
                        flag20 = true;
                    }
                    if (this.type == 1018 && Math.Abs(this.velocity.X) > 3f)
                    {
                        flag20 = true;
                    }
                    if ((this.type == 1056 || this.type == 1090) && this.velocity.Length() > 5f)
                    {
                        flag20 = true;
                    }
                    if (this.type == 1036 && this.velocity.X != 0f)
                    {
                        flag20 = true;
                    }
                    Collision.StepUp(ref this.position, ref this.velocity, this.width, this.height, ref this.stepSpeed, ref this.gfxOffY, 1, false, 0);
                    bool flag24 = flag6 && this.ai[2] != 0f;
                    float num47 = Utils.GetLerpValue(0f, 100f, vector15.Y, true) * Utils.GetLerpValue(-2f, -6f, this.velocity.Y, true);
                    float num48 = 1f;
                    if (flag24)
                    {
                        num48 = 0f;
                    }
                    if (this.velocity.Y == 0f)
                    {
                        if (flag20)
{
                            for (int l = 0; l < 3; l++)
{
                                int num49 = (int)(this.position.X + (float)(this.width / 2)) / 16;
                                if (l == 0)
{
                                    num49 = (int)this.position.X / 16;
                                }
                                if (l == 2)
{
                                    num49 = (int)(this.position.X + (float)this.width) / 16;
                                }
                                int num50 = (int)(this.position.Y + (float)this.height) / 16;
                                if (WorldGen.SolidTile(num49, num50, false) || Main.tile[num49, num50].halfBrick() || Main.tile[num49, num50].slope() > 0 || (TileID.Sets.Platforms[(int)Main.tile[num49, num50].type] && Main.tile[num49, num50].active() && !Main.tile[num49, num50].inActive()))
{
                                    try
{
                                        num49 = (int)(this.position.X + (float)(this.width / 2)) / 16;
                                        num50 = (int)(this.position.Y + (float)(this.height / 2)) / 16;
                                        num49 += num42;
                                        num49 += (int)this.velocity.X;
                                        if (!WorldGen.SolidTile(num49, num50 - 1, false) && !WorldGen.SolidTile(num49, num50 - 2, false))
{
                                            this.velocity.Y = -5.1f;
                                        }
                                        else if (!WorldGen.SolidTile(num49, num50 - 2, false))
{
                                            this.velocity.Y = -7.1f;
                                        }
                                        else if (WorldGen.SolidTile(num49, num50 - 5, false))
{
                                            this.velocity.Y = -11.1f;
                                        }
                                        else if (WorldGen.SolidTile(num49, num50 - 4, false))
{
                                            this.velocity.Y = -10.1f;
                                        }
                                        else
{
                                            this.velocity.Y = -9.1f;
                                        }
                                    }
                                    catch
{
                                        this.velocity.Y = -9.1f;
                                    }
                                }
                            }
                            if (vector.Y - base.Center.Y < -48f)
{
                                float num51 = vector.Y - base.Center.Y;
                                num51 *= -1f;
                                if (num51 < 60f)
{
                                    this.velocity.Y = -6f;
                                }
                                else if (num51 < 80f)
{
                                    this.velocity.Y = -7f;
                                }
                                else if (num51 < 100f)
{
                                    this.velocity.Y = -8f;
                                }
                                else if (num51 < 120f)
{
                                    this.velocity.Y = -9f;
                                }
                                else if (num51 < 140f)
{
                                    this.velocity.Y = -10f;
                                }
                                else if (num51 < 160f)
{
                                    this.velocity.Y = -11f;
                                }
                                else if (num51 < 190f)
{
                                    this.velocity.Y = -12f;
                                }
                                else if (num51 < 210f)
{
                                    this.velocity.Y = -13f;
                                }
                                else if (num51 < 270f)
{
                                    this.velocity.Y = -14f;
                                }
                                else if (num51 < 310f)
{
                                    this.velocity.Y = -15f;
                                }
                                else
{
                                    this.velocity.Y = -16f;
                                }
                            }
                            if (this.wet && num47 == 0f)
{
                                this.velocity.Y = this.velocity.Y * 2f;
                            }
                        }
                        if (this.type == 1018 && this.localAI[2] == 0f)
{
                            this.localAI[2] = 1f;
                            for (int m = 0; m < 6; m++)
{
                                Dust dust4 = Main.dust[Dust.NewDust(this.position + this.velocity, 16, 16, 0, 0f, 0f, 0, default(Color), 0.8f)];
                                dust4.velocity.X = this.velocity.X * 0.25f;
                                dust4.velocity.Y = -2f + Math.Abs(this.velocity.Y) * 0.25f;
                                dust4.velocity = dust4.velocity.RotatedByRandom(0.2617993950843811);
                            }
                        }
                    }
                    else if (this.type == 1018)
                    {
                        this.localAI[2] = 0f;
                    }
                    if (!flag24)
                    {
                        if (this.velocity.X > num39)
{
                            this.velocity.X = num39;
                        }
                        if (this.velocity.X < -num39)
{
                            this.velocity.X = -num39;
                        }
                    }
                    if (this.ai[0] != 2f)
                    {
                        if (this.velocity.X < 0f)
{
                            this.direction = -1;
                        }
                        if (this.velocity.X > 0f)
{
                            this.direction = 1;
                        }
                        if (this.velocity.X == 0f)
{
                            this.direction = ((player.Center.X > base.Center.X) ? 1 : (-1));
                        }
                        if (this.velocity.X > num37 && num42 == 1)
{
                            this.direction = 1;
                        }
                        if (this.velocity.X < -num37 && num42 == -1)
{
                            this.direction = -1;
                        }
                    }
                    this.spriteDirection = this.direction;
                    if (flag7)
                    {
                        this.spriteDirection = -this.direction;
                        this.rotation = 0f;
                        if (this.velocity.Y == 0f)
{
                            if (this.velocity.X == 0f)
{
                                this.frameCounter = 0;
                                this.frame = 0;
                            }
                            else
{
                                this.frameCounter++;
                                if (this.frameCounter > 4)
{
                                    this.frameCounter = 0;
                                    this.frame++;
                                }
                                if (this.frame >= Main.projFrames[this.type])
{
                                    this.frame = 0;
                                }
                            }
                        }
                        else
{
                            this.frameCounter = 0;
                            this.frame = 1;
                        }
                    }
                    if (flag6)
                    {
                        this.rotation = 0f;
                        if (num12 != -1)
{
                            if (this.velocity.Y != 0f)
{
                                this.frame = 13;
                                this.frameCounter = 0;
                            }
                            else
{
                                this.frameCounter++;
                                if (this.frameCounter > 3)
{
                                    this.frame++;
                                    this.frameCounter = 0;
                                }
                                if (this.frame < 10 || this.frame > 15)
{
                                    this.frame = 10;
                                }
                            }
                        }
                        else if (this.velocity.Y == 0f)
{
                            if (this.velocity.X == 0f)
{
                                this.frame = 0;
                                this.frameCounter = 0;
                            }
                            else if (Math.Abs(this.velocity.X) >= 0.5f)
{
                                this.frameCounter += (int)Math.Abs(this.velocity.X);
                                this.frameCounter++;
                                if (this.frameCounter > 10)
{
                                    this.frame++;
                                    this.frameCounter = 0;
                                }
                                if (this.frame < 2 || this.frame > 9)
{
                                    this.frame = 2;
                                }
                            }
                            else
{
                                this.frame = 0;
                                this.frameCounter = 0;
                            }
                        }
                        else if (this.velocity.Y != 0f)
{
                            this.frame = 1;
                            this.frameCounter = 0;
                        }
                    }
                    if (flag5)
                    {
                        if (this.velocity.Y == 0f)
{
                            this.rotation = this.rotation.AngleTowards(0f, 0.3f);
                            if (this.velocity.X == 0f)
{
                                this.frame = 0;
                                this.frameCounter = 0;
                            }
                            else if (Math.Abs(this.velocity.X) >= 0.5f)
{
                                this.frameCounter += (int)Math.Abs(this.velocity.X);
                                this.frameCounter++;
                                if (this.frameCounter > 10)
{
                                    this.frame++;
                                    this.frameCounter = 0;
                                }
                                if (this.frame < 2 || this.frame >= Main.projFrames[this.type])
{
                                    this.frame = 2;
                                }
                            }
                            else
{
                                this.frame = 0;
                                this.frameCounter = 0;
                            }
                        }
                        else if (this.velocity.Y != 0f)
{
                            this.rotation = Math.Min(4f, this.velocity.Y) * -0.1f;
                            if (this.spriteDirection == -1)
{
                                this.rotation -= 6.2831855f;
                            }
                            this.frameCounter = 0;
                            this.frame = 1;
                        }
                    }
                    if (flag)
                    {
                        this.rotation = 0f;
                        if (this.velocity.Y == 0f)
{
                            if (this.velocity.X == 0f)
{
                                this.frame = 0;
                                this.frameCounter = 0;
                            }
                            else if (Math.Abs(this.velocity.X) >= 0.5f)
{
                                this.frameCounter += (int)Math.Abs(this.velocity.X);
                                this.frameCounter++;
                                if (this.frameCounter > 10)
{
                                    this.frame++;
                                    this.frameCounter = 0;
                                }
                                if (this.frame >= 4)
{
                                    this.frame = 0;
                                }
                            }
                            else
{
                                this.frame = 0;
                                this.frameCounter = 0;
                            }
                        }
                        else if (this.velocity.Y != 0f)
{
                            this.frameCounter = 0;
                            this.frame = 14;
                        }
                    }
                    if (flag8)
                    {
                        this.rotation = 0f;
                        if (this.velocity.Y == 0f)
{
                            if (this.velocity.X == 0f)
{
                                this.frame = 0;
                                this.frameCounter = 0;
                                if (flag9)
{
                                    this.frame = 13;
                                }
                            }
                            else if (Math.Abs(this.velocity.X) >= 0.5f)
{
                                this.frameCounter += (int)Math.Abs(this.velocity.X);
                                this.frameCounter++;
                                if (this.frame < 7)
{
                                    this.frame = 7;
                                }
                                if (this.frameCounter > 10)
{
                                    this.frame++;
                                    this.frameCounter = 0;
                                }
                                if (this.frame >= 13)
{
                                    this.frame = 7;
                                }
                            }
                            else
{
                                this.frame = 0;
                                this.frameCounter = 0;
                            }
                        }
                        else if (this.velocity.Y != 0f)
{
                            this.frameCounter = 0;
                            this.frame = 1;
                            if (this.velocity.Y > 0f)
{
                                this.frame = 2;
                            }
                        }
                    }
                    if (flag2)
                    {
                        this.rotation = 0f;
                        if (this.velocity.Y == 0f)
{
                            if (this.velocity.X == 0f)
{
                                int num52 = 4;
                                int num6 = this.frameCounter + 1;
                                this.frameCounter = num6;
                                if (num6 >= 7 * num52 && Main.rand.Next(50) == 0)
{
                                    this.frameCounter = 0;
                                }
                                int num53 = this.frameCounter / num52;
                                if (num53 >= 4)
{
                                    num53 = 6 - num53;
                                }
                                if (num53 < 0)
{
                                    num53 = 0;
                                }
                                this.frame = 1 + num53;
                            }
                            else if (Math.Abs(this.velocity.X) >= 0.5f)
{
                                this.frameCounter += (int)Math.Abs(this.velocity.X);
                                this.frameCounter++;
                                int num54 = 15;
                                int num55 = 8;
                                if (this.frameCounter >= num55 * num54)
{
                                    this.frameCounter = 0;
                                }
                                int num56 = this.frameCounter / num54;
                                this.frame = num56 + 5;
                            }
                            else
{
                                this.frame = 0;
                                this.frameCounter = 0;
                            }
                        }
                        else if (this.velocity.Y != 0f)
{
                            if (this.velocity.Y < 0f)
{
                                if (this.frame > 9 || this.frame < 5)
{
                                    this.frame = 5;
                                    this.frameCounter = 0;
                                }
                                int num6 = this.frameCounter + 1;
                                this.frameCounter = num6;
                                if (num6 >= 1 && this.frame < 9)
{
                                    this.frame++;
                                    this.frameCounter = 0;
                                }
                            }
                            else
{
                                if (this.frame > 13 || this.frame < 9)
{
                                    this.frame = 9;
                                    this.frameCounter = 0;
                                }
                                int num6 = this.frameCounter + 1;
                                this.frameCounter = num6;
                                if (num6 >= 2 && this.frame < 11)
{
                                    this.frame++;
                                    this.frameCounter = 0;
                                }
                            }
                        }
                    }
                    if (flag3)
                    {
                        int num57 = 8;
                        if (flag4)
{
                            num57 = 10;
                        }
                        this.rotation = 0f;
                        if (this.velocity.Y == 0f)
{
                            if (this.velocity.X == 0f)
{
                                this.frame = 0;
                                this.frameCounter = 0;
                            }
                            else if (Math.Abs(this.velocity.X) >= 0.5f)
{
                                this.frameCounter += (int)Math.Abs(this.velocity.X);
                                this.frameCounter++;
                                if (this.frameCounter > 10)
{
                                    this.frame++;
                                    this.frameCounter = 0;
                                }
                                if (this.frame >= num57 || this.frame < 2)
{
                                    this.frame = 2;
                                }
                            }
                            else
{
                                this.frame = 0;
                                this.frameCounter = 0;
                            }
                        }
                        else if (this.velocity.Y != 0f)
{
                            this.frameCounter = 0;
                            this.frame = 1;
                            if (flag4)
{
                                this.frame = 9;
                            }
                        }
                    }
                    this.velocity.Y = this.velocity.Y + (num + num47 * num48);
                    if (this.velocity.Y > 10f)
                    {
                        this.velocity.Y = 10f;
                    }
                }
                if (flag)
                {
                    this.localAI[0] += 1f;
                    if (this.velocity.X == 0f)
                    {
                        this.localAI[0] += 1f;
                    }
                    if (this.localAI[0] >= (float)Main.rand.Next(900, 1200))
                    {
                        this.localAI[0] = 0f;
                        for (int n = 0; n < 6; n++)
{
                            int num58 = Dust.NewDust(base.Center + Vector2.UnitX * (float)(-(float)this.direction) * 8f - Vector2.One * 5f + Vector2.UnitY * 8f, 3, 6, 216, (float)(-(float)this.direction), 1f, 0, default(Color), 1f);
                            Main.dust[num58].velocity /= 2f;
                            Main.dust[num58].scale = 0.8f;
                        }
                        int num59 = Gore.NewGore(base.Center + Vector2.UnitX * (float)(-(float)this.direction) * 8f, Vector2.Zero, Main.rand.Next(580, 583), 1f);
                        Main.gore[num59].velocity /= 2f;
                        Main.gore[num59].velocity.Y = Math.Abs(Main.gore[num59].velocity.Y);
                        Main.gore[num59].velocity.X = -Math.Abs(Main.gore[num59].velocity.X) * (float)this.direction;
                    }
                }
                if (this.type == 1090)
                {
                    int num6 = this.frameCounter + 1;
                    this.frameCounter = num6;
                    if (num6 >= 2)
                    {
                        this.frameCounter = 0;
                        num6 = this.frame + 1;
                        this.frame = num6;
                        if (num6 >= 100)
{
                            this.frame = 0;
                        }
                    }
                    float num60 = 0.025f;
                    if (this.ai[0] == 1f)
                    {
                        this.localAI[2] += num60;
                        if (this.localAI[2] >= 1f)
{
                            this.localAI[2] = 1f;
                            return;
                        }
                    }
                    else
                    {
                        this.localAI[2] -= num60;
                        if (this.localAI[2] <= 0f)
{
                            this.localAI[2] = 0f;
                        }
                    }
                }
                return;
            }
            if (num12 < 0)
            {
                this.ai[0] = 0f;
                this.ai[1] = 0f;
                return;
            }
            float num61 = (float)num2;
            NPC npc3 = Main.npc[num12];
            vector = npc3.Center;
            float num62;
            float num63;
            bool flag25;
            if (!this.IsInRangeOfMeOrMyOwner(npc3, num61, out num62, out num63, out flag25))
            {
                this.ai[0] = 0f;
                this.ai[1] = 0f;
                return;
            }
            Point point2 = npc3.Top.ToTileCoordinates();
            int num64 = 0;
            int num65 = point2.Y;
            while (num64 < num5)
            {
                Tile tile2 = Main.tile[point2.X, num65];
                if (tile2 == null || tile2.active())
                {
                    break;
                }
                num64++;
                num65++;
            }
            int num66 = num5 / 2;
            if (num64 < num66)
            {
                this.ai[0] = 0f;
                this.ai[1] = 0f;
                return;
            }
            if (base.Hitbox.Intersects(npc3.Hitbox) && this.velocity.Y >= 0f)
            {
                this.velocity.Y = -8f;
                this.velocity.X = (float)(this.direction * 10);
            }
            float num67 = 20f;
            float num68 = 4f;
            float num69 = 40f;
            float num70 = 40f;
            Vector2 top = npc3.Top;
            float num71 = (float)Math.Cos(Main.timeForVisualEffects / (double)num69 * 6.2831854820251465);
            if (num71 > 0f)
            {
                num71 *= -1f;
            }
            num71 *= num70;
            top.Y += num71;
            Vector2 vector16 = top - base.Center;
            if (vector16.Length() > num67)
            {
                vector16 = vector16.SafeNormalize(Vector2.Zero) * num67;
            }
            this.velocity = this.velocity.MoveTowards(vector16, num68);
            this.frame = 8;
            if (flag4)
            {
                this.frame = 10;
            }
            this.rotation += 0.6f * (float)this.spriteDirection;
        }
References Terraria.Projectile._CompanionCubeScreamCooldown, System.Math.Abs(), Terraria.Mount.Active, Terraria.Player.active, Terraria.Tile.active(), Terraria.Lighting.AddLight(), Terraria.Graphics.Shaders.GameShaders.Armor, System.array, Terraria.DataStructures.PlayerDeathReason.ByOther(), Terraria.Entity.Center, Terraria.Utils.CenteredRectangle(), Microsoft.Xna.Framework.MathHelper.Clamp(), Terraria.Player.cLight, Terraria.Player.cobWhipBuff, Terraria.Player.companionCube, System.Math.Cos(), Terraria.Player.crimsonHeart, Terraria.Player.dead, Terraria.Player.deadCellsMushroomBoiMinion, Terraria.Entity.direction, Microsoft.Xna.Framework.Vector2.Distance(), Terraria.Main.dust, Terraria.Player.flinxMinion, Terraria.Lighting.GetColor(), Terraria.Utils.GetLerpValue(), Terraria.Graphics.Shaders.ArmorShaderDataSet.GetSecondaryShader(), Terraria.Framing.GetTileSafely(), Terraria.Main.gore, Terraria.Tile.halfBrick(), Microsoft.Xna.Framework.Rectangle.Height, Terraria.Entity.height, Terraria.Player.highestStormTigerGemOriginalDamage, Terraria.Entity.Hitbox, Terraria.Player.Hurt(), Terraria.Player.immune, Terraria.Tile.inActive(), int, Microsoft.Xna.Framework.Rectangle.Intersects(), Terraria.ID.SoundID.Item1, Terraria.ID.SoundID.Item16, Terraria.Tile.lava(), Microsoft.Xna.Framework.Vector2.Length(), Microsoft.Xna.Framework.Vector3.Length(), Microsoft.Xna.Framework.Color.Lerp(), Terraria.Tile.liquid, Terraria.Main.LocalPlayer, System.Math.Min(), Terraria.Player.miscCounter, Terraria.Player.mount, Terraria.Player.MountedCenter, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Dust.NewDust(), Terraria.Dust.NewDustDirect(), Terraria.Gore.NewGore(), Terraria.Projectile.NewProjectile(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Microsoft.Xna.Framework.Vector2.Normalize(), Terraria.Main.npc, Terraria.ID.SoundID.NPCDeath59, Terraria.ID.SoundID.NPCDeath61, Microsoft.Xna.Framework.Vector3.One, Terraria.Main.OurFavoriteColor, Terraria.ID.SoundID.PalCattiva, Terraria.ID.SoundID.PalCattivaJoy, Terraria.ID.SoundID.PalSummon, Terraria.Player.palworldCattivaMinion, Terraria.Player.petFlagBoulderPet, Terraria.Player.petFlagDirtiestBlock, Terraria.Player.petFlagRainbowBoulderPet, Terraria.Player.pirateMinion, Terraria.ID.TileID.Sets.Platforms, Terraria.Main.player, Terraria.ID.MountID.Sets.PlayerIsHidden, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Main.projFrames, Terraria.Main.rand, Terraria.GameContent.Drawing.ParticleOrchestrator.RequestParticleSpawn(), Terraria.Dust.scale, Terraria.Dust.shader, System.Math.Sign(), Terraria.Tile.slope(), Terraria.Collision.SolidCollision(), Terraria.WorldGen.SolidTile(), Terraria.Collision.StepUp(), Terraria.Player.stormTiger, Terraria.Main.tile, Terraria.Collision.TileCollision(), Terraria.Main.timeForVisualEffects, Terraria.Entity.Top, Microsoft.Xna.Framework.Color.ToVector3(), Microsoft.Xna.Framework.Color.Transparent, Terraria.Mount.Type, Terraria.Tile.type, Microsoft.Xna.Framework.Vector2.UnitX, Microsoft.Xna.Framework.Vector2.UnitY, Terraria.Player.vampireFrog, Terraria.Dust.velocity, Terraria.Entity.velocity, Terraria.Gore.velocity, Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Rectangle.Width, Terraria.Entity.width, Microsoft.Xna.Framework.MathHelper.WrapAngle(), Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Point.Y, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.