Terraria Decompiled: Terraria.Projectile.Damage_PVE_Inner
Damage_PVE_Inner()
void Terraria.Projectile.Damage_PVE_Inner (int victimIndex, NPC targetNPC, Rectangle projRectangle, float projectileSpecificDamageMultiplier, int[] immuneArray, ref bool keepIterating) inline private
Definition at line 11692 of file Projectile.cs.
        {
            bool ownedBySomeone = this.OwnedBySomeone;
            bool flag = !targetNPC.friendly;
            flag |= this.type == 318;
            flag |= targetNPC.type == 22 && this.owner < 255 && Main.player[this.owner].killGuide;
            flag |= targetNPC.type == 54 && this.owner < 255 && Main.player[this.owner].killClothier;
            if (this.owner < 255 && !Main.player[this.owner].CanNPCBeHitByPlayerOrPlayerProjectile(targetNPC, this))
            {
                flag = false;
            }
            bool flag2 = targetNPC.friendly && !targetNPC.dontTakeDamageFromHostiles;
            if ((!this.friendly || (!flag && !NPCID.Sets.ZappingJellyfish[targetNPC.type])) && (!this.hostile || !flag2))
            {
                return;
            }
            bool flag3 = this.maxPenetrate == 1 && !this.usesLocalNPCImmunity && !this.usesIDStaticNPCImmunity;
            if (this.owner >= 0 && targetNPC.immune[this.owner] != 0 && !flag3)
            {
                return;
            }
            bool flag4 = false;
            if (this.type == 11 && (targetNPC.type == 47 || targetNPC.type == 57))
            {
                flag4 = true;
            }
            else if (this.type == 31 && targetNPC.type == 69)
            {
                flag4 = true;
            }
            else if (targetNPC.trapImmune && this.trap)
            {
                flag4 = true;
            }
            else if (targetNPC.immortal && this.npcProj)
            {
                flag4 = true;
            }
            if (flag4)
            {
                return;
            }
            if (!targetNPC.noTileCollide && this.ownerHitCheck && !this.CanHitWithMeleeWeapon(targetNPC))
            {
                return;
            }
            bool flag5;
            if (targetNPC.type == 414)
            {
                Rectangle rect = targetNPC.getRect();
                int num = 8;
                rect.X -= num;
                rect.Y -= num;
                rect.Width += num * 2;
                rect.Height += num * 2;
                flag5 = this.Colliding(projRectangle, rect);
            }
            else
            {
                flag5 = this.Colliding(projRectangle, targetNPC.getRect());
            }
            if (!flag5)
            {
                return;
            }
            if (NPCID.Sets.ZappingJellyfish[targetNPC.type])
            {
                if ((targetNPC.dontTakeDamage || !Main.player[this.owner].CanNPCBeHitByPlayerOrPlayerProjectile(targetNPC, this)) && (this.aiStyle == 19 || this.aiStyle == 161 || this.aiStyle == 75 || this.aiStyle == 140 || ProjectileID.Sets.IsAWhip[this.type] || ProjectileID.Sets.AllowsContactDamageFromJellyfish[this.type]))
                {
                    Main.player[this.owner].TakeDamageFromJellyfish(victimIndex);
                }
                if (targetNPC.dontTakeDamage || !flag)
                {
                    return;
                }
            }
            if (this.type == 876)
            {
                Vector2 vector = this.position;
                if (Main.rand.Next(20) == 0)
                {
                    this.tileCollide = false;
                    this.position.X = this.position.X + (float)Main.rand.Next(-256, 257);
                }
                if (Main.rand.Next(20) == 0)
                {
                    this.tileCollide = false;
                    this.position.Y = this.position.Y + (float)Main.rand.Next(-256, 257);
                }
                if (Main.rand.Next(2) == 0)
                {
                    this.tileCollide = false;
                }
                if (Main.rand.Next(3) != 0)
                {
                    vector = this.position;
                    this.position -= this.velocity * (float)Main.rand.Next(0, 40);
                    if (this.tileCollide && Collision.SolidTiles(this.position, this.width, this.height))
                    {
                        this.position = vector;
                        this.position -= this.velocity * (float)Main.rand.Next(0, 40);
                        if (this.tileCollide && Collision.SolidTiles(this.position, this.width, this.height))
{
                            this.position = vector;
                        }
                    }
                }
                this.velocity *= 0.6f;
                if (Main.rand.Next(7) == 0)
                {
                    this.velocity.X = this.velocity.X + (float)Main.rand.Next(30, 31) * 0.01f;
                }
                if (Main.rand.Next(7) == 0)
                {
                    this.velocity.Y = this.velocity.Y + (float)Main.rand.Next(30, 31) * 0.01f;
                }
                this.damage = (int)((double)this.damage * 0.9);
                this.knockBack *= 0.9f;
                if (Main.rand.Next(20) == 0)
                {
                    this.knockBack *= 10f;
                }
                if (Main.rand.Next(50) == 0)
                {
                    this.damage *= 10;
                }
                if (Main.rand.Next(7) == 0)
                {
                    vector = this.position;
                    this.position.X = this.position.X + (float)Main.rand.Next(-64, 65);
                    if (this.tileCollide && Collision.SolidTiles(this.position, this.width, this.height))
                    {
                        this.position = vector;
                    }
                }
                if (Main.rand.Next(7) == 0)
                {
                    vector = this.position;
                    this.position.Y = this.position.Y + (float)Main.rand.Next(-64, 65);
                    if (this.tileCollide && Collision.SolidTiles(this.position, this.width, this.height))
                    {
                        this.position = vector;
                    }
                }
                if (Main.rand.Next(14) == 0)
                {
                    this.velocity.X = this.velocity.X * -1f;
                }
                if (Main.rand.Next(14) == 0)
                {
                    this.velocity.Y = this.velocity.Y * -1f;
                }
                if (Main.rand.Next(10) == 0)
                {
                    this.velocity *= (float)Main.rand.Next(1, 201) * 0.0005f;
                }
                if (this.tileCollide)
                {
                    this.ai[1] = 0f;
                }
                else
                {
                    this.ai[1] = 1f;
                }
                this.netUpdate = true;
            }
            bool flag6 = targetNPC.reflectsProjectiles;
            if (Main.getGoodWorld && NPCID.Sets.ReflectStarShotsInForTheWorthy[targetNPC.type] && (this.type == 955 || this.type == 728))
            {
                flag6 = true;
            }
            if (flag6 && this.CanBeReflected() && targetNPC.CanReflectProjectile(this))
            {
                targetNPC.ReflectProjectile(this);
                keepIterating = false;
                return;
            }
            if (this.type == 604)
            {
                Main.player[this.owner].Counterweight(targetNPC.Center, this.damage, this.knockBack);
            }
            float num2 = this.knockBack;
            bool flag7 = false;
            float num3 = 0f;
            int num4 = Main.player[this.owner].GetArmorPenetration(this.melee) + this.armorPenetration;
            bool flag8 = false;
            int num5 = this.type;
            if (num5 <= 442)
            {
                if (num5 != 189)
                {
                    if (num5 == 442)
                    {
                        flag8 = true;
                    }
                }
                else if (ownedBySomeone && Main.player[this.owner].strongBees)
                {
                    num4 += 5;
                }
            }
            else if (num5 - 877 > 2)
            {
                if (num5 == 963)
                {
                    if (this.ai[0] >= 2f)
                    {
                        num2 = 2f;
                    }
                    else
                    {
                        num2 = 0f;
                    }
                }
            }
            else
            {
                num2 *= Main.player[this.owner].velocity.Length() / 7f;
            }
            if (flag8)
            {
                this.Kill();
                keepIterating = false;
                return;
            }
            int num6 = (int)((float)this.damage * projectileSpecificDamageMultiplier);
            if (this.type > 0 && this.type < (int)ProjectileID.Count && ProjectileID.Sets.StardustDragon[this.type])
            {
                float num7 = (this.scale - 1f) * 100f;
                num7 = Utils.Clamp<float>(num7, 0f, 50f);
                num6 = (int)((float)num6 * (1f + num7 * 0.23f));
            }
            if (this.type > 0 && this.type < (int)ProjectileID.Count && ProjectileID.Sets.StormTiger[this.type])
            {
                int num8 = Math.Max(0, Main.player[this.owner].ownedProjectileCounts[831] - 1);
                num6 = (int)((float)num6 * (1f + (float)num8 * 0.4f));
            }
            if (this.type == 818)
            {
                int num9 = Math.Max(0, Main.player[this.owner].ownedProjectileCounts[831] - 1);
                num6 = (int)((float)num6 * (1.5f + (float)num9 * 0.4f));
            }
            if (this.type == 963)
            {
                int num10 = Math.Max(0, Main.player[this.owner].ownedProjectileCounts[970] - 1);
                int num11 = 3 + num10 / 2;
                if (this.CountEnemiesWhoAreImmuneToMeRightNow(num11) >= num11)
                {
                    return;
                }
                float num12 = 0.55f;
                if (Main.hardMode)
                {
                    num12 = 1.3f;
                }
                num6 = (int)((float)num6 * (1f + (float)num10 * num12));
            }
            if (ownedBySomeone && this.type == 189 && Main.player[this.owner].strongBees)
            {
                num6 += 5;
            }
            if (ownedBySomeone)
            {
                int num13 = 0;
                if (this.bonusCritChance > 0)
                {
                    num13 += this.bonusCritChance;
                }
                if (this.melee && Main.rand.Next(1, 101) <= Main.player[this.owner].meleeCrit + num13)
                {
                    flag7 = true;
                }
                if (this.ranged && Main.rand.Next(1, 101) <= Main.player[this.owner].rangedCrit + num13)
                {
                    flag7 = true;
                }
                if (this.magic && Main.rand.Next(1, 101) <= Main.player[this.owner].magicCrit + num13)
                {
                    flag7 = true;
                }
                num5 = this.type;
                if (num5 - 688 <= 2)
                {
                    if (Main.player[this.owner].setMonkT3)
                    {
                        if (Main.rand.Next(4) == 0)
{
                            flag7 = true;
                        }
                    }
                    else if (Main.player[this.owner].setMonkT2 && Main.rand.Next(6) == 0)
                    {
                        flag7 = true;
                    }
                }
            }
            int num14 = num6;
            Main.player[this.owner].TagEffectState.ModifyHit(this, targetNPC, ref num14, ref flag7);
            int num15;
            if (ownedBySomeone)
            {
                num15 = Main.DamageVar((float)num14, Main.player[this.owner].luck);
            }
            else
            {
                num15 = Main.DamageVar((float)num14, 0f);
            }
            if (this.type == 1002)
            {
                num15 /= 2;
            }
            if (this.type == 1074)
            {
                num15 = targetNPC.KeyBrandStrike(this.owner, num15, base.Center);
            }
            if (this.trap && NPCID.Sets.BelongsToInvasionOldOnesArmy[targetNPC.type])
            {
                num15 /= 2;
            }
            if (this.type == 482 && (targetNPC.aiStyle == 6 || targetNPC.aiStyle == 37))
            {
                num15 /= 2;
            }
            if (ownedBySomeone)
            {
                Vector2 vector2 = Main.rand.NextVector2FromRectangle(targetNPC.Hitbox);
                ParticleOrchestraSettings particleOrchestraSettings = new ParticleOrchestraSettings
                {
                    PositionInWorld = vector2
                };
                num5 = this.type;
                if (num5 <= 973)
                {
                    if (num5 != 972)
                    {
                        if (num5 == 973)
{
                            ParticleOrchestrator.RequestParticleSpawn(false, ParticleOrchestraType.TrueNightsEdge, particleOrchestraSettings, new int?(this.owner));
                        }
                    }
                    else
                    {
                        ParticleOrchestrator.RequestParticleSpawn(false, ParticleOrchestraType.NightsEdge, particleOrchestraSettings, new int?(this.owner));
                    }
                }
                else
                {
                    switch (num5)
                    {
                    case 982:
                        ParticleOrchestrator.RequestParticleSpawn(false, ParticleOrchestraType.Excalibur, particleOrchestraSettings, new int?(this.owner));
                        break;
                    case 983:
                        ParticleOrchestrator.RequestParticleSpawn(false, ParticleOrchestraType.TrueExcalibur, particleOrchestraSettings, new int?(this.owner));
                        break;
                    case 984:
                    case 985:
                        particleOrchestraSettings.MovementVector = this.velocity;
                        ParticleOrchestrator.RequestParticleSpawn(false, ParticleOrchestraType.TerraBlade, particleOrchestraSettings, new int?(this.owner));
                        break;
                    default:
                        if (num5 != 1035)
{
                            if (num5 == 1045)
{
                                particleOrchestraSettings.PositionInWorld = Vector2.Lerp(particleOrchestraSettings.PositionInWorld, targetNPC.Center, 0.5f);
                                particleOrchestraSettings.MovementVector = this.velocity;
                                ParticleOrchestrator.RequestParticleSpawn(false, ParticleOrchestraType.MoonLordWhipHit, particleOrchestraSettings, new int?(this.owner));
                            }
                        }
                        else
{
                            particleOrchestraSettings.MovementVector = this.velocity.RotatedBy((double)(Main.rand.NextFloatDirection() * 6.2831855f * 0.1f), default(Vector2));
                            ParticleOrchestrator.RequestParticleSpawn(false, ParticleOrchestraType.MoonLordWhipHit, particleOrchestraSettings, new int?(this.owner));
                        }
                        break;
                    }
                }
            }
            if (this.type == 604)
            {
                this.friendly = false;
                this.ai[1] = 1000f;
            }
            if ((this.type == 400 || this.type == 401 || this.type == 402 || this.type == 1107 || this.type == 1108 || this.type == 1109) && targetNPC.type >= 13 && targetNPC.type <= 15)
            {
                num15 = (int)((double)num15 * 0.65);
                if (this.penetrate > 1)
                {
                    this.penetrate--;
                }
            }
            Point point;
            if (this.type == 710 && !WorldUtils.Find(base.Center.ToTileCoordinates(), Searches.Chain(new Searches.Down(12), new GenCondition[]
            {
                Projectile._cachedConditions_notNull,
                Projectile._cachedConditions_solid
            }), out point))
            {
                num15 = (int)((float)num15 * 1.5f);
            }
            if (this.type == 504 || this.type == 954 || this.type == 979)
            {
                float num16 = (60f - this.ai[0]) / 2f;
                this.ai[0] += num16;
            }
            if (this.type == 301)
            {
                if (projRectangle.Width > this.width)
                {
                    num2 *= 1.75f;
                }
                float x = Main.player[this.owner].Center.X;
                if (targetNPC.Center.X < x)
                {
                    this.direction = -1;
                }
                else
                {
                    this.direction = 1;
                }
            }
            if (this.type == 383)
            {
                if (projRectangle.Width > this.width)
                {
                    num2 *= 1.5f;
                    num15 = (int)((float)num15 * 0.6f);
                }
                float x2 = Main.player[this.owner].Center.X;
                if (targetNPC.Center.X < x2)
                {
                    this.direction = -1;
                }
                else
                {
                    this.direction = 1;
                }
            }
            else if (this.aiStyle == 3 && this.type != 301 && this.type != 866 && this.type != 902 && !ProjectileID.Sets.IsAPhaseblade[this.type])
            {
                if (this.ai[0] == 0f)
                {
                    if (this.type == 106)
                    {
                        this.LightDisc_Bounce(base.Center + this.velocity.SafeNormalize(Vector2.UnitX) * 8f, (-this.velocity).SafeNormalize(Vector2.UnitX));
                    }
                    this.velocity.X = -this.velocity.X;
                    this.velocity.Y = -this.velocity.Y;
                    this.netUpdate = true;
                }
                this.ai[0] = 1f;
            }
            else if (this.type == 951)
            {
                Vector2 vector3 = (targetNPC.Center - base.Center).SafeNormalize(Vector2.Zero);
                vector3.X += (-0.5f + Main.rand.NextFloat()) * 13f;
                vector3.Y = -5f;
                this.velocity.X = vector3.X;
                this.velocity.Y = vector3.Y;
                this.netUpdate = true;
            }
            else if (this.type == 582 || this.type == 902)
            {
                if (this.ai[0] != 0f)
                {
                    this.direction *= -1;
                }
            }
            else if (this.type == 612 || this.type == 953 || this.type == 978)
            {
                this.direction = Main.player[this.owner].direction;
            }
            else if (this.type == 624)
            {
                float num17 = 1f;
                if (targetNPC.knockBackResist > 0f)
                {
                    num17 = 1f / targetNPC.knockBackResist;
                }
                this.knockBack = 4f * num17;
                num2 = this.knockBack;
                if (targetNPC.Center.X < base.Center.X)
                {
                    this.direction = 1;
                }
                else
                {
                    this.direction = -1;
                }
            }
            else if (this.aiStyle == 16)
            {
                if (this.timeLeft > 3)
                {
                    this.timeLeft = 3;
                }
                if (targetNPC.position.X + (float)(targetNPC.width / 2) < this.position.X + (float)(this.width / 2))
                {
                    this.direction = -1;
                }
                else
                {
                    this.direction = 1;
                }
            }
            else if (this.type == 669)
            {
                this.damage = (int)((double)this.damage * 0.8);
                this.timeLeft = 1;
                float x3 = Main.player[this.owner].Center.X;
                if (targetNPC.Center.X < x3)
                {
                    this.direction = -1;
                }
                else
                {
                    this.direction = 1;
                }
            }
            else if (this.aiStyle == 68)
            {
                if (this.timeLeft > 3)
                {
                    this.timeLeft = 3;
                }
                if (targetNPC.position.X + (float)(targetNPC.width / 2) < this.position.X + (float)(this.width / 2))
                {
                    this.direction = -1;
                }
                else
                {
                    this.direction = 1;
                }
            }
            else if (this.aiStyle == 50)
            {
                if (targetNPC.position.X + (float)(targetNPC.width / 2) < this.position.X + (float)(this.width / 2))
                {
                    this.direction = -1;
                }
                else
                {
                    this.direction = 1;
                }
            }
            else if (this.type == 908)
            {
                if (targetNPC.position.X + (float)(targetNPC.width / 2) < this.position.X + (float)(this.width / 2))
                {
                    this.direction = -1;
                }
                else
                {
                    this.direction = 1;
                }
            }
            if (this.type == 509)
            {
                int num18 = Main.rand.Next(2, 6);
                for (int i = 0; i < num18; i++)
                {
                    Vector2 vector4 = new Vector2((float)Main.rand.Next(-100, 101), (float)Main.rand.Next(-100, 101));
                    vector4 += this.velocity * 3f;
                    vector4.Normalize();
                    vector4 *= (float)Main.rand.Next(35, 81) * 0.1f;
                    int num19 = (int)((double)this.damage * 0.5);
                    Projectile.NewProjectile(this.GetProjectileSource_FromThis(), base.Center.X, base.Center.Y, vector4.X, vector4.Y, 504, num19, this.knockBack * 0.2f, this.owner, 0f, 0f, 0f, null);
                }
            }
            if ((this.type == 476 || this.type == 950) && !this.npcProj)
            {
                float x4 = Main.player[this.owner].Center.X;
                if (targetNPC.Center.X < x4)
                {
                    this.direction = -1;
                }
                else
                {
                    this.direction = 1;
                }
            }
            if (this.aiStyle == 113 && this.ai[0] < 2f)
            {
                this.ai[0] = 1f;
                this.ai[1] = (float)victimIndex;
                this.velocity = (targetNPC.Center - base.Center) * 0.75f;
                this.netUpdate = true;
                this.AI_113_UpdateDrawLayer();
            }
            if (this.type >= 511 && this.type <= 513)
            {
                this.ai[1] += 1f;
                this.netUpdate = true;
            }
            if (this.type == 659)
            {
                this.timeLeft = 0;
            }
            if (this.type == 524)
            {
                this.netUpdate = true;
                this.ai[0] += 50f;
            }
            if ((this.type == 688 || this.type == 689 || this.type == 690) && targetNPC.type != 68 && targetNPC.defense < 999)
            {
                num3 = 1f;
            }
            if (this.aiStyle == 39)
            {
                if (this.ai[1] == 0f)
                {
                    this.ai[1] = (float)(victimIndex + 1);
                    this.netUpdate = true;
                }
                if (Main.player[this.owner].position.X + (float)(Main.player[this.owner].width / 2) < this.position.X + (float)(this.width / 2))
                {
                    this.direction = 1;
                }
                else
                {
                    this.direction = -1;
                }
            }
            if (this.type == 41 && this.timeLeft > 1)
            {
                this.timeLeft = 1;
            }
            if (this.aiStyle == 99)
            {
                if (this.ai[0] == -2f)
                {
                    float num20 = this.velocity.Length();
                    this.velocity.Normalize();
                    this.velocity *= num20 / 5f;
                    this.velocity.Y = this.velocity.Y - (float)Main.rand.Next(50, 81) * 0.1f;
                    if (this.velocity.Y < -16f)
                    {
                        this.velocity.Y = -16f;
                    }
                    this.netUpdate = true;
                }
                else
                {
                    Main.player[this.owner].Counterweight(targetNPC.Center, this.damage, this.knockBack);
                    if (targetNPC.Center.X < Main.player[this.owner].Center.X)
                    {
                        this.direction = -1;
                    }
                    else
                    {
                        this.direction = 1;
                    }
                    if (this.ai[0] >= 0f)
                    {
                        Vector2 vector5 = base.Center - targetNPC.Center;
                        vector5.Normalize();
                        float num21 = 16f;
                        this.velocity *= -0.5f;
                        this.velocity += vector5 * num21;
                        this.netUpdate = true;
                        this.localAI[0] += 20f;
                        if (!Collision.CanHit(this.position, this.width, this.height, Main.player[this.owner].position, Main.player[this.owner].width, Main.player[this.owner].height))
{
                            this.localAI[0] += 40f;
                            num15 = (int)((double)num15 * 0.75);
                        }
                    }
                }
            }
            if (this.type == 856)
            {
                this.ModifyStellarTuneDamage(ref num15);
            }
            if (ProjectileID.Sets.IsAPhaseblade[this.type] && this.ai[0] == 2f)
            {
                switch (this.type)
                {
                case 1065:
                case 1066:
                case 1067:
                case 1068:
                case 1069:
                case 1070:
                case 1072:
                case 1076:
                    num15 = (int)((double)num15 * 0.5);
                    break;
                default:
                    num15 = (int)((double)num15 * 0.6);
                    break;
                }
                num2 *= 0.6f;
                if (targetNPC.Center.X < Main.player[this.owner].Center.X)
                {
                    this.direction = -1;
                }
                else
                {
                    this.direction = 1;
                }
            }
            if (this.aiStyle == 93)
            {
                if (this.ai[0] == 0f)
                {
                    this.ai[1] = 0f;
                    int num22 = -victimIndex - 1;
                    this.ai[0] = (float)num22;
                    this.velocity = targetNPC.Center - base.Center;
                    this.netUpdate = true;
                }
                if (this.ai[0] == 2f)
                {
                    num15 = (int)((double)num15 * 1.35);
                }
                else
                {
                    num15 = (int)((double)num15 * 0.15);
                }
            }
            if (ownedBySomeone)
            {
                int num23 = BannerSystem.NPCtoBanner(targetNPC.BannerID());
                if (num23 >= 0)
                {
                    Main.player[Main.myPlayer].lastCreatureHit = num23;
                }
            }
            ItemID.BannerEffect bannerEffect;
            if (Main.netMode != 2 && ownedBySomeone && Main.player[this.owner].GetBannerBuffEffect(targetNPC, out bannerEffect))
            {
                num15 = (int)((float)num15 * bannerEffect.DamageDealt.Sample(Main.Difficulty));
            }
            if (Main.expertMode)
            {
                if ((this.type == 30 || this.type == 397 || this.type == 517 || this.type == 28 || this.type == 37 || this.type == 516 || this.type == 29 || this.type == 470 || this.type == 637 || this.type == 1086 || this.type == 1087 || this.type == 108 || this.type == 281 || this.type == 588 || this.type == 519 || this.type == 773 || this.type == 183 || this.type == 181 || this.type == 566 || this.type == 1002) && targetNPC.type >= 13 && targetNPC.type <= 15)
                {
                    num15 /= 5;
                }
                if (this.type == 280 && ((targetNPC.type >= 134 && targetNPC.type <= 136) || targetNPC.type == 139))
                {
                    num15 = (int)((double)num15 * 0.75);
                }
            }
            if (Main.netMode != 2 && targetNPC.type == 439 && this.type >= 0 && this.type <= (int)ProjectileID.Count && ProjectileID.Sets.CultistIsResistantTo[this.type])
            {
                num15 = (int)((float)num15 * 0.75f);
            }
            if (this.type == 497 && this.penetrate != 1)
            {
                this.ai[0] = 25f;
                float num24 = this.velocity.Length();
                Vector2 vector6 = targetNPC.Center - base.Center;
                vector6.Normalize();
                vector6 *= num24;
                this.velocity = -vector6 * 0.9f;
                this.netUpdate = true;
            }
            if (this.type == 323 && (targetNPC.type == 159 || targetNPC.type == 158))
            {
                num15 *= 10;
            }
            if (this.type == 981 && targetNPC.type == 104)
            {
                num15 *= 3;
            }
            num5 = this.type;
            if (num5 <= 355)
            {
                if (num5 <= 132)
                {
                    if (num5 <= 78)
                    {
                        if (num5 != 4)
{
                            if (num5 != 5)
{
                                if (num5 - 76 <= 2)
{
                                    this.damage = (int)((double)this.damage * 0.95);
                                }
                            }
                            else
{
                                this.damage = (int)((double)this.damage * 0.9);
                            }
                        }
                        else
{
                            this.damage = (int)((double)this.damage * 0.95);
                        }
                    }
                    else if (num5 != 85)
                    {
                        if (num5 != 114)
{
                            if (num5 == 132)
{
                                this.damage = (int)((double)this.damage * 0.85);
                            }
                        }
                        else
{
                            this.damage = (int)((double)this.damage * 0.9);
                        }
                    }
                    else
                    {
                        this.damage = (int)((double)this.damage * 0.85);
                    }
                }
                else if (num5 <= 294)
                {
                    if (num5 != 242)
                    {
                        if (num5 != 265)
{
                            if (num5 == 294)
{
                                this.damage = (int)((double)this.damage * 0.9);
                            }
                        }
                        else
{
                            this.damage = (int)((double)this.damage * 0.75);
                        }
                    }
                    else
                    {
                        this.damage = (int)((double)this.damage * 0.85);
                    }
                }
                else if (num5 != 309)
                {
                    if (num5 != 323)
                    {
                        if (num5 == 355)
{
                            this.damage = (int)((double)this.damage * 0.75);
                        }
                    }
                    else
                    {
                        this.damage = (int)((double)this.damage * 0.9);
                    }
                }
                else
                {
                    this.damage = (int)((double)this.damage * 0.85);
                }
            }
            else if (num5 <= 950)
            {
                if (num5 <= 866)
                {
                    if (num5 != 841)
                    {
                        switch (num5)
{
                        case 847:
                            this.damage = (int)((double)this.damage * 0.8);
                            break;
                        case 848:
                            this.damage = (int)((double)this.damage * 0.95);
                            break;
                        case 849:
                            this.damage = (int)((double)this.damage * 0.9);
                            break;
                        default:
                            if (num5 == 866)
{
                                this.damage = (int)((double)this.damage * 0.8);
                            }
                            break;
                        }
                    }
                    else
                    {
                        this.damage = (int)((double)this.damage * 0.5);
                    }
                }
                else
                {
                    switch (num5)
                    {
                    case 912:
                        this.damage = (int)((double)this.damage * 0.7);
                        break;
                    case 913:
                        this.damage = (int)((double)this.damage * 0.66);
                        break;
                    case 914:
                        this.damage = (int)((double)this.damage * 0.6);
                        break;
                    case 915:
                        this.damage = (int)((double)this.damage * 0.8);
                        break;
                    default:
                        if (num5 != 931)
{
                            if (num5 == 950)
{
                                this.damage = (int)((double)this.damage * 0.98);
                            }
                        }
                        else
{
                            this.damage = (int)((double)this.damage * 0.8);
                        }
                        break;
                    }
                }
            }
            else if (num5 <= 985)
            {
                if (num5 != 952)
                {
                    if (num5 != 964)
                    {
                        if (num5 == 985)
{
                            this.damage = (int)((double)this.damage * 0.75);
                        }
                    }
                    else
                    {
                        this.damage = (int)((double)this.damage * 0.85);
                    }
                }
                else
                {
                    this.damage = (int)((double)this.damage * 0.9);
                }
            }
            else
            {
                switch (num5)
                {
                case 1028:
                    this.damage = (int)((double)this.damage * 0.4);
                    break;
                case 1029:
                    this.damage = (int)((double)this.damage * 0.6);
                    break;
                case 1030:
                    this.damage = (int)((double)this.damage * 0.6);
                    break;
                case 1031:
                    this.damage = (int)((double)this.damage * 0.7);
                    break;
                case 1032:
                    this.damage = (int)((double)this.damage * 0.85);
                    break;
                case 1033:
                    this.damage = (int)((double)this.damage * 0.95);
                    break;
                case 1034:
                    this.damage = (int)((double)this.damage * 0.9);
                    break;
                case 1035:
                    this.damage = (int)((double)this.damage * 0.95);
                    break;
                default:
                    if (num5 != 1104)
                    {
                        if (num5 == 1106)
{
                            this.damage = (int)((double)this.damage * 0.85);
                        }
                    }
                    else
                    {
                        this.damage = (int)((double)this.damage * 0.4);
                    }
                    break;
                }
            }
            if (this.type == 477 && this.penetrate > 1)
            {
                int[] array = new int[10];
                int num25 = 0;
                int num26 = 700;
                int num27 = 20;
                for (int j = 0; j < Main.maxNPCs; j++)
                {
                    if (j != victimIndex && Main.npc[j].CanBeChasedBy(this, false))
                    {
                        float num28 = (base.Center - Main.npc[j].Center).Length();
                        if (num28 > (float)num27 && num28 < (float)num26 && Collision.CanHitLine(base.Center, 1, 1, Main.npc[j].Center, 1, 1))
{
                            array[num25] = j;
                            num25++;
                            if (num25 >= 9)
{
                                break;
                            }
                        }
                    }
                }
                if (num25 > 0)
                {
                    num25 = Main.rand.Next(num25);
                    Vector2 vector7 = Main.npc[array[num25]].Center - base.Center;
                    float num29 = this.velocity.Length();
                    vector7.Normalize();
                    this.velocity = vector7 * num29;
                    this.rotation = this.velocity.ToRotation() + 1.5707964f;
                    this.netUpdate = true;
                }
            }
            if (this.type == 261 && this.velocity.Length() < 3.5f)
            {
                num15 /= 2;
                num2 /= 2f;
            }
            if (ownedBySomeone && this.melee && Main.player[this.owner].parryDamageBuff && !ProjectileID.Sets.DontApplyParryDamageBuff[this.type])
            {
                num15 *= 5;
                Main.player[this.owner].parryDamageBuff = false;
                Main.player[this.owner].ClearBuff(198);
            }
            this.SpawnHitVisuals(targetNPC);
            this.StatusNPC(victimIndex);
            if (ownedBySomeone && this.tagEffectType > 0)
            {
                Main.player[this.owner].TagEffectState.TryApplyTagToNPC(this.tagEffectType, targetNPC);
            }
            if (ownedBySomeone && targetNPC.life > 5)
            {
                this.TryDoingOnHitEffects(targetNPC);
            }
            if (ProjectileID.Sets.ImmediatelyUpdatesNPCBuffFlags[this.type])
            {
                targetNPC.UpdateNPC_BuffSetFlags(false);
            }
            if (this.type == 317)
            {
                this.ai[1] = -1f;
                this.netUpdate = true;
            }
            int num30 = this.direction;
            num5 = this.type;
            if (num5 <= 699)
            {
                if (num5 != 697 && num5 != 699)
                {
                    goto IL_24A8;
                }
            }
            else if (num5 - 707 > 1 && num5 != 759)
            {
                goto IL_24A8;
            }
            num30 = ((Main.player[this.owner].Center.X < targetNPC.Center.X) ? 1 : (-1));
            IL_24A8:
            if (this.aiStyle == 188 || this.aiStyle == 189 || this.aiStyle == 190 || this.aiStyle == 191)
            {
                num30 = ((Main.player[this.owner].Center.X < targetNPC.Center.X) ? 1 : (-1));
            }
            if (this.aiStyle == 15)
            {
                num30 = ((Main.player[this.owner].Center.X < targetNPC.Center.X) ? 1 : (-1));
                if (this.ai[0] == 0f)
                {
                    num2 *= 0.35f;
                }
                if (this.ai[0] == 6f)
                {
                    num2 *= 0.5f;
                }
            }
            if (this.type == 22)
            {
                num30 = ((Main.player[this.owner].Center.X < targetNPC.Center.X) ? 1 : (-1));
            }
            if (ownedBySomeone && !this.hostile)
            {
                num15 += targetNPC.checkArmorPenetration(num4, num3);
            }
            NPCKillAttempt npckillAttempt = new NPCKillAttempt(targetNPC);
            int num31;
            if (ownedBySomeone)
            {
                num31 = (int)targetNPC.StrikeNPC(num15, num2, num30, flag7, false, false, this.owner);
            }
            else
            {
                num31 = (int)targetNPC.StrikeNPCNoInteraction(num15, num2, num30, flag7, false, false);
            }
            if (ownedBySomeone && npckillAttempt.DidNPCDie())
            {
                Main.player[this.owner].OnKillNPC(ref npckillAttempt, this);
            }
            if (ownedBySomeone && Main.player[this.owner].accDreamCatcher)
            {
                Main.player[this.owner].addDPS(num31);
            }
            Main.player[this.owner].TagEffectState.OnHit(this, targetNPC, num6);
            bool flag9 = !targetNPC.immortal;
            bool flag10 = num31 > 0 && targetNPC.lifeMax > 5 && this.friendly && !this.hostile && this.aiStyle != 59;
            bool flag11 = false;
            if (DebugOptions.LetProjectilesAimAtTargetDummies && targetNPC.type == 488)
            {
                flag9 = true;
                flag11 = true;
                flag10 |= this.friendly && this.aiStyle != 59;
            }
            if (flag9 && this.active && this.timeLeft > 10 && targetNPC.active && targetNPC.type == 676 && this.CanBeReflected())
            {
                targetNPC.ReflectProjectile(this);
                this.penetrate++;
            }
            if (ownedBySomeone && flag9)
            {
                if (this.type == 997 && (!targetNPC.immortal || flag11) && !targetNPC.SpawnedFromStatue && !NPCID.Sets.CountsAsCritter[targetNPC.type])
                {
                    Main.player[this.owner].HorsemansBlade_SpawnPumpkin(victimIndex, (int)((float)this.damage * 1f), this.knockBack);
                }
                if (this.type == 756 && this.penetrate == 1)
                {
                    this.damage = 0;
                    this.penetrate = -1;
                    keepIterating = false;
                }
                if ((flag11 || targetNPC.value > 0f) && Main.player[this.owner].hasLuckyCoin && Main.rand.Next(5) == 0)
                {
                    int num32 = 71;
                    if (Main.rand.Next(10) == 0)
                    {
                        num32 = 72;
                    }
                    if (Main.rand.Next(100) == 0)
                    {
                        num32 = 73;
                    }
                    int num33 = Item.NewItem(this.GetItemSource_OnHit(targetNPC, ItemSourceID.LuckyCoin), (int)targetNPC.position.X, (int)targetNPC.position.Y, targetNPC.width, targetNPC.height, num32, 1, false, 0, false);
                    Main.item[num33].stack = Main.rand.Next(1, 11);
                    Main.item[num33].velocity.Y = (float)Main.rand.Next(-20, 1) * 0.2f;
                    Main.item[num33].velocity.X = (float)Main.rand.Next(10, 31) * 0.2f * (float)num30;
                    Main.item[num33].timeLeftInWhichTheItemCannotBeTakenByEnemies = 60;
                    if (Main.netMode == 1)
                    {
                        NetMessage.SendData(148, -1, -1, null, num33, 0f, 0f, 0f, 0, 0, 0);
                    }
                }
                if (this.type == 999 && this.owner == Main.myPlayer && Main.rand.Next(3) == 0)
                {
                    Player player = Main.player[this.owner];
                    Vector2 vector8 = (base.Center - targetNPC.Center).SafeNormalize(Vector2.Zero) * 0.25f;
                    int num34 = this.damage / 2;
                    float num35 = this.knockBack;
                    int num36 = Projectile.NewProjectile(this.GetProjectileSource_FromThis(), base.Center.X, base.Center.Y, vector8.X, vector8.Y, player.beeType(), player.beeDamage(num34), player.beeKB(num35), this.owner, 0f, 0f, 0f, null);
                    Main.projectile[num36].melee = true;
                }
                if (flag10)
                {
                    if (this.type == 304 && !Main.player[this.owner].moonLeech)
                    {
                        this.vampireHeal(num31, new Vector2(targetNPC.Center.X, targetNPC.Center.Y), targetNPC);
                    }
                    if (targetNPC.canGhostHeal || flag11)
                    {
                        if (Main.player[this.owner].ghostHeal && !Main.player[this.owner].moonLeech)
{
                            this.ghostHeal(num31, new Vector2(targetNPC.Center.X, targetNPC.Center.Y), targetNPC);
                        }
                        if (Main.player[this.owner].ghostHurt)
{
                            this.ghostHurt(num31, new Vector2(targetNPC.Center.X, targetNPC.Center.Y), targetNPC);
                        }
                        if (this.magic && Main.player[this.owner].setNebula && Main.player[this.owner].nebulaCD == 0 && Main.rand.Next(3) == 0)
{
                            Main.player[this.owner].nebulaCD = 30;
                            int num37 = Utils.SelectRandom<int>(Main.rand, new int[] { 3453, 3454, 3455 });
                            int num38 = Item.NewItem(this.GetItemSource_OnHit(targetNPC, ItemSourceID.SetBonus_Nebula), (int)targetNPC.position.X, (int)targetNPC.position.Y, targetNPC.width, targetNPC.height, num37, 1, false, 0, false);
                            Main.item[num38].velocity.Y = (float)Main.rand.Next(-20, 1) * 0.2f;
                            Main.item[num38].velocity.X = (float)Main.rand.Next(10, 31) * 0.2f * (float)num30;
                            if (Main.netMode == 1)
{
                                NetMessage.SendData(21, -1, -1, null, num38, 0f, 0f, 0f, 0, 0, 0);
                            }
                        }
                    }
                    if (this.melee && Main.player[this.owner].beetleOffense && (!targetNPC.immortal || flag11))
                    {
                        if (Main.player[this.owner].beetleOrbs == 0)
{
                            Main.player[this.owner].beetleCounter += (float)(num31 * 3);
                        }
                        else if (Main.player[this.owner].beetleOrbs == 1)
{
                            Main.player[this.owner].beetleCounter += (float)(num31 * 2);
                        }
                        else
{
                            Main.player[this.owner].beetleCounter += (float)num31;
                        }
                        Main.player[this.owner].beetleCountdown = 0;
                    }
                    if (this.arrow && this.type != 631 && Main.player[this.owner].phantasmTime > 0)
                    {
                        Vector2 vector9 = Main.player[this.owner].position + Main.player[this.owner].Size * Utils.RandomVector2(Main.rand, 0f, 1f);
                        Vector2 vector10 = targetNPC.DirectionFrom(vector9) * 6f;
                        int num39 = (int)((float)this.damage * 0.3f);
                        Projectile.NewProjectile(this.GetProjectileSource_FromThis(), vector9.X, vector9.Y, vector10.X, vector10.Y, 631, num39, 0f, this.owner, (float)victimIndex, 0f, 0f, null);
                        Projectile.NewProjectile(this.GetProjectileSource_FromThis(), vector9.X, vector9.Y, vector10.X, vector10.Y, 631, num39, 0f, this.owner, (float)victimIndex, 15f, 0f, null);
                        Projectile.NewProjectile(this.GetProjectileSource_FromThis(), vector9.X, vector9.Y, vector10.X, vector10.Y, 631, num39, 0f, this.owner, (float)victimIndex, 30f, 0f, null);
                    }
                    Player player2 = Main.player[this.owner];
                    num5 = this.type;
                    if (num5 <= 913)
                    {
                        if (num5 == 912)
{
                            int num40 = 15;
                            if (!player2.coolWhipBuff)
{
                                Projectile.NewProjectile(this.GetProjectileSource_FromThis(), targetNPC.Center, Vector2.Zero, 917, num40, 0f, this.owner, 0f, 0f, 0f, null);
                                player2.coolWhipBuff = true;
                            }
                            player2.AddBuff(312, 180, false);
                            goto IL_2FE4;
                        }
                        if (num5 != 913)
{
                            goto IL_2FE4;
                        }
                    }
                    else
                    {
                        switch (num5)
{
                        case 1028:
{
                            int num41 = 2;
                            if (!player2.cobWhipBuff)
{
                                Projectile.NewProjectile(this.GetProjectileSource_FromThis(), targetNPC.Center, Vector2.Zero, 1036, num41, 0f, this.owner, 0f, 0f, 0f, null);
                                player2.cobWhipBuff = true;
                            }
                            player2.AddBuff(365, 180, false);
                            goto IL_2FE4;
                        }
                        case 1029:
                        case 1030:
                        case 1033:
                            goto IL_2FE4;
                        case 1031:
                        case 1032:
                            break;
                        case 1034:
                            if (this.localAI[0] == 0f)
{
                                this.localAI[0] = 1f;
                                this.SpawnConstellationStarsTowards(targetNPC, this.damage);
                                goto IL_2FE4;
                            }
                            goto IL_2FE4;
                        case 1035:
                            Main.player[this.owner].TagEffectState.TryEnableProcOnNPC(this.tagEffectType, targetNPC);
                            goto IL_2FE4;
                        default:
                            if (num5 != 1045)
{
                                goto IL_2FE4;
                            }
                            if (this.ai[1] < 2f)
{
                                Projectile.SpawnMoonLordWhipProc(this, targetNPC, this.damage, (int)this.ai[1] + 1);
                                goto IL_2FE4;
                            }
                            goto IL_2FE4;
                        }
                    }
                    if (this.localAI[0] == 0f)
                    {
                        this.localAI[0] = 1f;
                        Main.player[this.owner].TagEffectState.TryEnableProcOnNPC(this.tagEffectType, targetNPC);
                    }
                }
            }
            IL_2FE4:
            if (ownedBySomeone && (this.melee || ProjectileID.Sets.IsAWhip[this.type]) && Main.player[this.owner].meleeEnchant == 7)
            {
                Projectile.NewProjectile(this.GetProjectileSource_FromThis(), targetNPC.Center.X, targetNPC.Center.Y, targetNPC.velocity.X, targetNPC.velocity.Y, 289, 0, 0f, this.owner, 0f, 0f, 0f, null);
            }
            if (Main.netMode != 0)
            {
                if (flag7)
                {
                    NetMessage.SendData(28, -1, -1, null, victimIndex, (float)num15, num2, (float)num30, 1, 0, 0);
                }
                else
                {
                    NetMessage.SendData(28, -1, -1, null, victimIndex, (float)num15, num2, (float)num30, 0, 0, 0);
                }
            }
            if (this.type == 1088)
            {
                this.Kill();
            }
            if (this.type >= 390 && this.type <= 392)
            {
                this.localAI[1] = 20f;
            }
            if (this.usesIDStaticNPCImmunity)
            {
                if (this.penetrate != 1 || this.appliesImmunityTimeOnSingleHits)
                {
                    targetNPC.immune[this.owner] = 0;
                    Projectile.perIDStaticNPCImmunity[this.type][victimIndex] = Main.GameUpdateCount + (uint)this.idStaticNPCHitCooldown;
                }
            }
            else if (this.type == 434)
            {
                this.numUpdates = 0;
            }
            else if (this.type == 598 || this.type == 636 || this.type == 614)
            {
                Point[] array2 = Projectile._javelinsMax6;
                if (this.type == 636)
                {
                    array2 = Projectile._javelinsMax8;
                }
                if (this.type == 614)
                {
                    array2 = Projectile._javelinsMax10;
                }
                Projectile.KillOldestJavelin(this.whoAmI, this.type, victimIndex, array2);
            }
            else if (this.type == 632)
            {
                targetNPC.immune[this.owner] = 5;
            }
            else if (this.type == 514)
            {
                targetNPC.immune[this.owner] = 1;
            }
            else if (this.type == 595 || this.type == 735)
            {
                targetNPC.immune[this.owner] = 5;
            }
            else if (this.type == 927)
            {
                targetNPC.immune[this.owner] = 4;
            }
            else if (this.type == 286)
            {
                targetNPC.immune[this.owner] = 5;
            }
            else if (this.type == 443 || this.type == 1110)
            {
                targetNPC.immune[this.owner] = 8;
            }
            else if (this.type >= 424 && this.type <= 426)
            {
                targetNPC.immune[this.owner] = 5;
            }
            else if (this.type == 634 || this.type == 635)
            {
                targetNPC.immune[this.owner] = 5;
            }
            else if (this.type == 659)
            {
                targetNPC.immune[this.owner] = 5;
            }
            else if (this.type == 246)
            {
                targetNPC.immune[this.owner] = 7;
            }
            else if (this.type == 249)
            {
                targetNPC.immune[this.owner] = 7;
            }
            else if (this.type == 16)
            {
                targetNPC.immune[this.owner] = 8;
            }
            else if (this.type == 409)
            {
                targetNPC.immune[this.owner] = 6;
            }
            else if (this.type == 582 || this.type == 902)
            {
                targetNPC.immune[this.owner] = 7;
                if (this.ai[0] != 1f)
                {
                    this.ai[0] = 1f;
                    this.netUpdate = true;
                }
            }
            else
            {
                if (this.type == 451)
                {
                    if (this.ai[0] == 0f)
                    {
                        this.ai[0] += (float)this.penetrate;
                    }
                    else
                    {
                        this.ai[0] -= (float)(this.penetrate + 1);
                    }
                    this.ai[1] = 0f;
                    this.netUpdate = true;
                    keepIterating = false;
                    return;
                }
                if (this.type == 864)
                {
                    immuneArray[victimIndex] = this.localNPCHitCooldown;
                    targetNPC.immune[this.owner] = 0;
                    if (this.ai[0] > 0f)
                    {
                        this.ai[0] = -1f;
                        this.ai[1] = 0f;
                        this.netUpdate = true;
                    }
                }
                else if (this.type == 866)
                {
                    immuneArray[victimIndex] = this.localNPCHitCooldown;
                    targetNPC.immune[this.owner] = 0;
                    this.penetrate--;
                    if (this.penetrate == 0)
                    {
                        this.penetrate = 1;
                        this.damage = 0;
                        this.ai[1] = -1f;
                        this.netUpdate = true;
                        keepIterating = false;
                        return;
                    }
                    if (this.owner == Main.myPlayer)
                    {
                        int num42 = this.FindTargetWithLineOfSight(800f);
                        float num43 = this.ai[1];
                        this.ai[1] = (float)num42;
                        if (this.ai[1] != num43)
{
                            this.netUpdate = true;
                        }
                        if (num42 != -1)
{
                            this.velocity = this.velocity.Length() * base.DirectionTo(Main.npc[num42].Center);
                        }
                    }
                }
                else if (this.type == 611 || this.type == 612)
                {
                    targetNPC.immune[this.owner] = 4;
                    immuneArray[victimIndex] = this.localNPCHitCooldown;
                }
                else if (this.usesLocalNPCImmunity && this.localNPCHitCooldown != -2)
                {
                    targetNPC.immune[this.owner] = 0;
                    immuneArray[victimIndex] = this.localNPCHitCooldown;
                }
                else if (this.penetrate != 1 || this.appliesImmunityTimeOnSingleHits)
                {
                    targetNPC.immune[this.owner] = 10;
                }
            }
            if (this.type == 710)
            {
                this.BetsySharpnel(victimIndex);
            }
            if (this.penetrate > 0 && this.type != 317 && this.type != 866)
            {
                if (this.type == 357)
                {
                    this.damage = (int)((double)this.damage * 0.8);
                }
                this.penetrate--;
                if (this.penetrate == 0)
                {
                    if (this.stopsDealingDamageAfterPenetrateHits)
                    {
                        this.penetrate = -1;
                        this.damage = 0;
                    }
                    keepIterating = false;
                }
            }
            if (this.aiStyle == 7)
            {
                this.ai[0] = 1f;
                this.damage = 0;
                this.netUpdate = true;
            }
            else if (this.type == 23)
            {
                if (this.penetrate <= 0)
                {
                    if (this.ai[0] == 0f)
                    {
                        this.velocity *= 0f;
                    }
                    this.penetrate = -1;
                    this.ai[0] = 1f;
                    this.netUpdate = true;
                }
            }
            else if (this.aiStyle == 13)
            {
                this.ai[0] = 1f;
                this.netUpdate = true;
            }
            else if (this.aiStyle == 69)
            {
                this.ai[0] = 1f;
                this.netUpdate = true;
            }
            else if (this.type == 607)
            {
                this.ai[0] = 1f;
                this.netUpdate = true;
                this.friendly = false;
            }
            else if (this.type == 638 || this.type == 639 || this.type == 640)
            {
                this.damage = (int)((double)this.damage * 0.96);
            }
            else if (this.type == 656)
            {
                this.localAI[0] += 1f;
            }
            else if (this.type == 611)
            {
                if (this.localAI[1] <= 0f)
                {
                    Projectile.NewProjectile(this.GetProjectileSource_FromThis(), targetNPC.Center.X, targetNPC.Center.Y, 0f, 0f, 612, this.damage, 10f, this.owner, 0f, 0.85f + Main.rand.NextFloat() * 1.15f, 0f, null);
                }
                this.localAI[1] = 4f;
            }
            else if (this.type == 645 && this.ai[1] != -1f)
            {
                this.ai[0] = 0f;
                this.ai[1] = -1f;
                this.netUpdate = true;
            }
            this.numHits++;
            if (this.type == 697)
            {
                if (this.ai[0] >= 42f)
                {
                    this.localAI[1] = 1f;
                }
            }
            else if (this.type == 699)
            {
                this.SummonMonkGhast();
            }
            else if (this.type == 706)
            {
                this.damage = (int)((float)this.damage * 0.95f);
            }
            else if (this.type == 728)
            {
                this.SummonSuperStarSlash(targetNPC.Center);
            }
            else if (this.type == 34)
            {
                if (this.ai[0] == -1f)
                {
                    this.ai[1] = -1f;
                    this.netUpdate = true;
                }
            }
            else if (this.type == 79)
            {
                if (this.ai[0] == -1f)
                {
                    this.ai[1] = -1f;
                    this.netUpdate = true;
                }
                ParticleOrchestrator.RequestParticleSpawn(false, ParticleOrchestraType.RainbowRodHit, new ParticleOrchestraSettings
                {
                    PositionInWorld = targetNPC.Center,
                    MovementVector = this.velocity
                }, null);
            }
            else if (this.type == 931 || this.type == 1039)
            {
                int num44 = this.FindTargetWithLineOfSight(800f);
                if (num44 != -1)
                {
                    this.ai[0] = (float)num44;
                    this.netUpdate = true;
                }
                if (this.type == 1039)
                {
                    ParticleOrchestrator.RequestParticleSpawn(false, ParticleOrchestraType.StardustPunch, new ParticleOrchestraSettings
                    {
                        PositionInWorld = Vector2.Lerp(base.Center, targetNPC.Hitbox.ClosestPointInRect(base.Center), 0.5f) + new Vector2(0f, Main.rand.NextFloatDirection() * 10f),
                        MovementVector = new Vector2((float)this.direction, Main.rand.NextFloatDirection() * 0.5f) * (2f + 2f * Main.rand.NextFloat())
                    }, null);
                }
            }
            else if (this.aiStyle == 165)
            {
                if (targetNPC.active)
                {
                    Main.player[this.owner].MinionAttackTargetNPC = victimIndex;
                }
            }
            else if (this.type == 623)
            {
                ParticleOrchestrator.RequestParticleSpawn(false, ParticleOrchestraType.StardustPunch, new ParticleOrchestraSettings
                {
                    PositionInWorld = Vector2.Lerp(base.Center, targetNPC.Hitbox.ClosestPointInRect(base.Center), 0.5f) + new Vector2(0f, Main.rand.NextFloatDirection() * 10f),
                    MovementVector = new Vector2((float)this.direction, Main.rand.NextFloatDirection() * 0.5f) * (3f + 3f * Main.rand.NextFloat())
                }, null);
            }
            else if (this.type == 1047 && targetNPC.TreatedAsABossForRainbowBoulders)
            {
                this.Kill();
                keepIterating = false;
            }
            if (this.CareForAttackCD)
            {
                Main.player[this.owner].SetMeleeHitCooldown(victimIndex, Main.player[this.owner].itemAnimation);
            }
        }
References Terraria.Projectile._cachedConditions_notNull, Terraria.Projectile._javelinsMax10, Terraria.Projectile._javelinsMax6, Terraria.Projectile._javelinsMax8, Terraria.Player.accDreamCatcher, Terraria.NPC.active, Terraria.Projectile.active, Terraria.Player.AddBuff(), Terraria.Player.addDPS(), Terraria.Projectile.ai, Terraria.Projectile.AI_113_UpdateDrawLayer(), Terraria.NPC.aiStyle, Terraria.Projectile.aiStyle, Terraria.ID.ProjectileID.Sets.AllowsContactDamageFromJellyfish, Terraria.Projectile.appliesImmunityTimeOnSingleHits, Terraria.Projectile.armorPenetration, System.array, Terraria.Projectile.arrow, Terraria.NPC.BannerID(), Terraria.Player.beeDamage(), Terraria.Player.beeKB(), Terraria.Player.beetleCountdown, Terraria.Player.beetleCounter, Terraria.Player.beetleOffense, Terraria.Player.beetleOrbs, Terraria.Player.beeType(), Terraria.ID.NPCID.Sets.BelongsToInvasionOldOnesArmy, Terraria.Projectile.BetsySharpnel(), Terraria.Projectile.bonusCritChance, Terraria.NPC.CanBeChasedBy(), Terraria.Projectile.CanBeReflected(), Terraria.NPC.canGhostHeal, Terraria.Collision.CanHit(), Terraria.Collision.CanHitLine(), Terraria.Player.CanNPCBeHitByPlayerOrPlayerProjectile(), Terraria.NPC.CanReflectProjectile(), Terraria.Entity.Center, Terraria.WorldBuilding.Searches.Chain(), Terraria.NPC.checkArmorPenetration(), Terraria.Utils.Clamp(), Terraria.Player.ClearBuff(), Terraria.Player.cobWhipBuff, Terraria.Projectile.Colliding(), Terraria.Player.coolWhipBuff, Terraria.Projectile.CountEnemiesWhoAreImmuneToMeRightNow(), Terraria.Player.Counterweight(), Terraria.ID.NPCID.Sets.CountsAsCritter, Terraria.ID.ProjectileID.Sets.CultistIsResistantTo, Terraria.Projectile.damage, Terraria.ID.ItemID.BannerEffect.DamageDealt, Terraria.Main.DamageVar(), Terraria.NPC.defense, Terraria.DataStructures.NPCKillAttempt.DidNPCDie(), Terraria.Main.Difficulty, Terraria.Entity.direction, Terraria.Entity.DirectionFrom(), Terraria.ID.ProjectileID.Sets.DontApplyParryDamageBuff, Terraria.NPC.dontTakeDamage, Terraria.NPC.dontTakeDamageFromHostiles, Terraria.Main.expertMode, Terraria.WorldBuilding.WorldUtils.Find(), Terraria.Projectile.FindTargetWithLineOfSight(), Terraria.NPC.friendly, Terraria.Projectile.friendly, Terraria.Player.GetArmorPenetration(), Terraria.Player.GetBannerBuffEffect(), Terraria.Main.getGoodWorld, Terraria.Projectile.GetItemSource_OnHit(), Terraria.Projectile.GetProjectileSource_FromThis(), Terraria.NPC.getRect(), Terraria.Player.ghostHeal, Terraria.Projectile.ghostHeal(), Terraria.Player.ghostHurt, Terraria.Projectile.ghostHurt(), Terraria.Main.hardMode, Terraria.Player.hasLuckyCoin, Terraria.Entity.height, Terraria.Entity.Hitbox, Terraria.Player.HorsemansBlade_SpawnPumpkin(), Terraria.Projectile.hostile, Terraria.Projectile.idStaticNPCHitCooldown, Terraria.ID.ProjectileID.Sets.ImmediatelyUpdatesNPCBuffFlags, Terraria.NPC.immortal, Terraria.NPC.immune, int, Terraria.ID.ProjectileID.Sets.IsAPhaseblade, Terraria.ID.ProjectileID.Sets.IsAWhip, Terraria.Main.item, Terraria.NPC.KeyBrandStrike(), Terraria.Projectile.Kill(), Terraria.Player.killClothier, Terraria.Player.killGuide, Terraria.Projectile.KillOldestJavelin(), Terraria.Projectile.knockBack, Terraria.NPC.knockBackResist, Terraria.Player.lastCreatureHit, Microsoft.Xna.Framework.Vector2.Length(), Microsoft.Xna.Framework.Vector2.Lerp(), Terraria.Testing.DebugOptions.LetProjectilesAimAtTargetDummies, Terraria.NPC.life, Terraria.Projectile.LightDisc_Bounce(), Terraria.Projectile.localAI, Terraria.Projectile.localNPCHitCooldown, Terraria.Player.luck, Terraria.ID.ItemSourceID.LuckyCoin, Terraria.Projectile.magic, Terraria.Player.magicCrit, System.Math.Max(), Terraria.Main.maxNPCs, Terraria.Projectile.melee, Terraria.Player.meleeCrit, Terraria.Player.meleeEnchant, Terraria.Projectile.ModifyStellarTuneDamage(), Terraria.Player.moonLeech, Terraria.Main.myPlayer, Terraria.Player.nebulaCD, Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.Projectile.NewProjectile(), Terraria.Utilities.UnifiedRandom.Next(), Microsoft.Xna.Framework.Vector2.Normalize(), Terraria.NPC.noTileCollide, Terraria.Main.npc, Terraria.Projectile.npcProj, Terraria.GameContent.BannerSystem.NPCtoBanner(), Terraria.Projectile.numHits, Terraria.Player.OnKillNPC(), Terraria.Projectile.OwnedBySomeone, Terraria.Player.ownedProjectileCounts, Terraria.Projectile.owner, Terraria.Player.parryDamageBuff, Terraria.Projectile.penetrate, Terraria.Projectile.perIDStaticNPCImmunity, Terraria.Player.phantasmTime, Terraria.Main.player, Terraria.Entity.position, Terraria.GameContent.Drawing.ParticleOrchestraSettings.PositionInWorld, Terraria.Main.projectile, Terraria.Main.rand, Terraria.Utils.RandomVector2(), Terraria.Projectile.ranged, Terraria.Player.rangedCrit, Terraria.NPC.ReflectProjectile(), Terraria.NPC.reflectsProjectiles, Terraria.ID.NPCID.Sets.ReflectStarShotsInForTheWorthy, Terraria.GameContent.Drawing.ParticleOrchestrator.RequestParticleSpawn(), Terraria.NetMessage.SendData(), Terraria.ID.ItemSourceID.SetBonus_Nebula, Terraria.Player.setMonkT2, Terraria.Player.setMonkT3, Terraria.Player.setNebula, Terraria.Entity.Size, Terraria.Collision.SolidTiles(), Terraria.Projectile.SpawnConstellationStarsTowards(), Terraria.Projectile.SpawnHitVisuals(), Terraria.Projectile.SpawnMoonLordWhipProc(), Terraria.WorldItem.stack, Terraria.ID.ProjectileID.Sets.StardustDragon, Terraria.Projectile.StatusNPC(), Terraria.Projectile.stopsDealingDamageAfterPenetrateHits, Terraria.ID.ProjectileID.Sets.StormTiger, Terraria.NPC.StrikeNPC(), Terraria.NPC.StrikeNPCNoInteraction(), Terraria.Player.strongBees, Terraria.Projectile.SummonMonkGhast(), Terraria.Projectile.SummonSuperStarSlash(), Terraria.Player.TagEffectState, Terraria.Projectile.tagEffectType, Terraria.Player.TakeDamageFromJellyfish(), Terraria.Projectile.tileCollide, Terraria.Projectile.timeLeft, Terraria.WorldItem.timeLeftInWhichTheItemCannotBeTakenByEnemies, Terraria.Projectile.trap, Terraria.NPC.trapImmune, Terraria.Projectile.TryDoingOnHitEffects(), Terraria.NPC.type, Terraria.Projectile.type, Microsoft.Xna.Framework.Vector2.UnitX, Terraria.NPC.UpdateNPC_BuffSetFlags(), Terraria.Projectile.usesIDStaticNPCImmunity, Terraria.Projectile.usesLocalNPCImmunity, Terraria.NPC.value, Terraria.Projectile.vampireHeal(), Terraria.Entity.velocity, Terraria.Entity.whoAmI, Microsoft.Xna.Framework.Rectangle.Width, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, Terraria.ID.NPCID.Sets.ZappingJellyfish, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.Projectile.Damage_PVE().