Terraria Decompiled: Terraria.Projectile.CutTilesAt
CutTilesAt()
void Terraria.Projectile.CutTilesAt (Vector2 boxPosition, int boxWidth, int boxHeight) inline private
Definition at line 14224 of file Projectile.cs.
        {
            int num = (int)(boxPosition.X / 16f);
            int num2 = (int)((boxPosition.X + (float)boxWidth) / 16f) + 1;
            int num3 = (int)(boxPosition.Y / 16f);
            int num4 = (int)((boxPosition.Y + (float)boxHeight) / 16f) + 1;
            if (num < 0)
            {
                num = 0;
            }
            if (num2 > Main.maxTilesX)
            {
                num2 = Main.maxTilesX;
            }
            if (num3 < 0)
            {
                num3 = 0;
            }
            if (num4 > Main.maxTilesY)
            {
                num4 = Main.maxTilesY;
            }
            bool[] tileCutIgnorance = Main.player[this.owner].GetTileCutIgnorance(false, this.trap);
            for (int i = num; i < num2; i++)
            {
                for (int j = num3; j < num4; j++)
                {
                    Tile tile = Main.tile[i, j];
                    if (tile != null && tile.active() && tile.type >= 0 && !tileCutIgnorance[(int)tile.type])
                    {
                        bool flag = Main.tileCut[(int)tile.type];
                        if (this.type == 1052 && this.ai[0] == 0f)
{
                            flag = flag || TileID.Sets.IsATreeTrunk[(int)tile.type] || tile.type == 323;
                        }
                        if (this.type == 1047 && tile.type == 231)
{
                            flag = false;
                        }
                        if (flag && WorldGen.CanCutTile(i, j, TileCuttingContext.AttackProjectile))
{
                            WorldGen.KillTile(i, j, false, false, false);
                            if (Main.netMode != 0)
{
                                NetMessage.SendData(17, -1, -1, null, 0, (float)i, (float)j, 0f, 0, 0, 0);
                            }
                        }
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.CanCutTile(), Terraria.Player.GetTileCutIgnorance(), int, Terraria.ID.TileID.Sets.IsATreeTrunk, Terraria.WorldGen.KillTile(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.netMode, Terraria.Main.player, Terraria.NetMessage.SendData(), Terraria.Main.tile, Terraria.Main.tileCut, Terraria.Tile.type, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.