Terraria Decompiled: Terraria.Projectile.AI_026
AI_026()
void Terraria.Projectile.AI_026 () inline private
Definition at line 58671 of file Projectile.cs.
        {
            if (!Main.player[this.owner].active)
            {
                this.active = false;
                return;
            }
            bool flag = false;
            bool flag2 = false;
            bool flag3 = false;
            bool flag4 = false;
            bool flag5 = false;
            int num = 85;
            bool flag6 = this.type >= 191 && this.type <= 194;
            bool flag7 = this.type >= 390 && this.type <= 392;
            bool flag8 = this.type == 1094;
            bool flag9 = Main.player[this.owner].petting.isPetting && Main.player[this.owner].petting.proj == this.whoAmI;
            bool flag10 = flag6 || flag8;
            if (this.type == 324)
            {
                num = 120;
            }
            if (this.type == 112)
            {
                num = 100;
            }
            if (this.type == 127)
            {
                num = 50;
            }
            int num2 = this.type;
            if (num2 <= 860)
            {
                if (num2 <= 821)
                {
                    if (num2 != 816 && num2 != 821)
                    {
                        goto IL_02B1;
                    }
                }
                else if (num2 != 825 && num2 != 854 && num2 - 858 > 2)
                {
                    goto IL_02B1;
                }
            }
            else if (num2 <= 897)
            {
                switch (num2)
                {
                case 881:
                    num = 95;
                    if (Main.player[this.owner].ownedProjectileCounts[881] > 0)
                    {
                        num = 120;
                        goto IL_02B1;
                    }
                    goto IL_02B1;
                case 882:
                case 883:
                case 886:
                case 887:
                case 888:
                    goto IL_02B1;
                case 884:
                case 890:
                    num = 80;
                    goto IL_02B1;
                case 885:
                case 889:
                case 891:
                    break;
                default:
                    if (num2 != 897)
                    {
                        goto IL_02B1;
                    }
                    break;
                }
            }
            else if (num2 - 899 > 1 && num2 != 934)
            {
                if (num2 != 1094)
                {
                    goto IL_02B1;
                }
                num2 = this.soundDelay - 1;
                this.soundDelay = num2;
                if (num2 == -20)
                {
                    SoundEngine.PlaySound(SoundID.PalFoxparks, base.Center, 0f, 1f);
                }
                if (this.soundDelay == -1)
                {
                    SoundEngine.PlaySound(SoundID.PalSummon, base.Center, 0f, 1f);
                }
                if (flag9 && this.localAI[2] == 0f)
                {
                    this.localAI[2] = 60f;
                    SoundEngine.PlaySound(SoundID.PalFoxparksJoy, base.Center, 0f, 1f);
                }
                if (this.localAI[2] > (float)(flag9 ? 1 : 0))
                {
                    this.localAI[2] -= 1f;
                    goto IL_02B1;
                }
                goto IL_02B1;
            }
            num = 95;
            IL_02B1:
            if (this.type == 960)
            {
                Main.CurrentFrameFlags.HadAnActiveInteractableProjectile = true;
                flag = true;
            }
            if (flag10)
            {
                if (this.lavaWet)
                {
                    this.ai[0] = 1f;
                    this.ai[1] = 0f;
                }
                num = 60 + 30 * this.minionPos;
            }
            else if (this.type == 266)
            {
                num = 60 + 30 * this.minionPos;
            }
            bool flag11 = this.ai[0] == -1f || this.ai[0] == -2f;
            bool flag12 = this.ai[0] == -1f;
            bool flag13 = this.ai[0] == -2f;
            if (this.type == 1094)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].palworldFoxsparksMinion = false;
                }
                if (Main.player[this.owner].palworldFoxsparksMinion)
                {
                    this.timeLeft = 2;
                }
                Lighting.AddLight(base.Center, 0.5f, 0.3f, 0.1f);
                this.DoPalAppearEffect(Main.player[this.owner], this.ai[0] != 1f);
            }
            if (this.type == 111)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].bunny = false;
                }
                if (Main.player[this.owner].bunny)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 112)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].penguin = false;
                }
                if (Main.player[this.owner].penguin)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 334)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].puppy = false;
                }
                if (Main.player[this.owner].puppy)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 353)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].grinch = false;
                }
                if (Main.player[this.owner].grinch)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 127)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].turtle = false;
                }
                if (Main.player[this.owner].turtle)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 175)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].eater = false;
                }
                if (Main.player[this.owner].eater)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 197)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].skeletron = false;
                }
                if (Main.player[this.owner].skeletron)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 198)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].hornet = false;
                }
                if (Main.player[this.owner].hornet)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 199)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].tiki = false;
                }
                if (Main.player[this.owner].tiki)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 200)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].lizard = false;
                }
                if (Main.player[this.owner].lizard)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 208)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].parrot = false;
                }
                if (Main.player[this.owner].parrot)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 209)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].truffle = false;
                }
                if (Main.player[this.owner].truffle)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 210)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].sapling = false;
                }
                if (Main.player[this.owner].sapling)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 324)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].cSapling = false;
                }
                if (Main.player[this.owner].cSapling)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 313)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].spider = false;
                }
                if (Main.player[this.owner].spider)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 314)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].squashling = false;
                }
                if (Main.player[this.owner].squashling)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 211)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].wisp = false;
                }
                if (Main.player[this.owner].wisp)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 236)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].dino = false;
                }
                if (Main.player[this.owner].dino)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 499)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].babyFaceMonster = false;
                }
                if (Main.player[this.owner].babyFaceMonster)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 765)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].petFlagSugarGlider = false;
                }
                if (Main.player[this.owner].petFlagSugarGlider)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 266)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].slime = false;
                }
                if (Main.player[this.owner].slime)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 268)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].eyeSpring = false;
                }
                if (Main.player[this.owner].eyeSpring)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 269)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].snowman = false;
                }
                if (Main.player[this.owner].snowman)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 319)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].blackCat = false;
                }
                if (Main.player[this.owner].blackCat)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 380)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].zephyrfish = false;
                }
                if (Main.player[this.owner].zephyrfish)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 1095)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].petFlagChillet = false;
                }
                if (Main.player[this.owner].petFlagChillet)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 1096)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].petFlagChilletIgnis = false;
                }
                if (Main.player[this.owner].petFlagChilletIgnis)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 774)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].petFlagBabyShark = false;
                }
                if (Main.player[this.owner].petFlagBabyShark)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 815)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].petFlagLilHarpy = false;
                }
                if (Main.player[this.owner].petFlagLilHarpy)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 816)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].petFlagFennecFox = false;
                }
                if (Main.player[this.owner].petFlagFennecFox)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 817)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].petFlagGlitteryButterfly = false;
                }
                if (Main.player[this.owner].petFlagGlitteryButterfly)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 821)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].petFlagBabyImp = false;
                }
                if (Main.player[this.owner].petFlagBabyImp)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 825)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].petFlagBabyRedPanda = false;
                }
                if (Main.player[this.owner].petFlagBabyRedPanda)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 854)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].petFlagPlantero = false;
                }
                if (Main.player[this.owner].petFlagPlantero)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 858)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].petFlagDynamiteKitten = false;
                }
                if (Main.player[this.owner].petFlagDynamiteKitten)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 859)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].petFlagBabyWerewolf = false;
                }
                if (Main.player[this.owner].petFlagBabyWerewolf)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 860)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].petFlagShadowMimic = false;
                }
                if (Main.player[this.owner].petFlagShadowMimic)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 875)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].petFlagVoltBunny = false;
                }
                if (Main.player[this.owner].petFlagVoltBunny)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 881)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].petFlagKingSlimePet = false;
                }
                if (Main.player[this.owner].petFlagKingSlimePet)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 884)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].petFlagBrainOfCthulhuPet = false;
                }
                if (Main.player[this.owner].petFlagBrainOfCthulhuPet)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 885)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].petFlagSkeletronPet = false;
                }
                if (Main.player[this.owner].petFlagSkeletronPet)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 886)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].petFlagQueenBeePet = false;
                }
                if (Main.player[this.owner].petFlagQueenBeePet)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 889)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].petFlagSkeletronPrimePet = false;
                }
                if (Main.player[this.owner].petFlagSkeletronPrimePet)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 890)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].petFlagPlanteraPet = false;
                }
                if (Main.player[this.owner].petFlagPlanteraPet)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 891)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].petFlagGolemPet = false;
                }
                if (Main.player[this.owner].petFlagGolemPet)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 892)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].petFlagDukeFishronPet = false;
                }
                if (Main.player[this.owner].petFlagDukeFishronPet)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 894)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].petFlagMoonLordPet = false;
                }
                if (Main.player[this.owner].petFlagMoonLordPet)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 897)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].petFlagEverscreamPet = false;
                }
                if (Main.player[this.owner].petFlagEverscreamPet)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 899)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].petFlagMartianPet = false;
                }
                if (Main.player[this.owner].petFlagMartianPet)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 900)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].petFlagDD2OgrePet = false;
                }
                if (Main.player[this.owner].petFlagDD2OgrePet)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 901)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].petFlagDD2BetsyPet = false;
                }
                if (Main.player[this.owner].petFlagDD2BetsyPet)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 934)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].petFlagQueenSlimePet = false;
                }
                if (Main.player[this.owner].petFlagQueenSlimePet)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 956)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].petFlagBerniePet = false;
                }
                if (Main.player[this.owner].petFlagBerniePet)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 958)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].petFlagDeerclopsPet = false;
                }
                if (Main.player[this.owner].petFlagDeerclopsPet)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 959)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].petFlagPigPet = false;
                }
                if (Main.player[this.owner].petFlagPigPet)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 960)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].petFlagChesterPet = false;
                }
                if (Main.player[this.owner].petFlagChesterPet)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 994)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].petFlagJunimoPet = false;
                }
                if (Main.player[this.owner].petFlagJunimoPet)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 998)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].petFlagBlueChickenPet = false;
                }
                if (Main.player[this.owner].petFlagBlueChickenPet)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 1003)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].petFlagSpiffo = false;
                }
                if (Main.player[this.owner].petFlagSpiffo)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 1004)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].petFlagCaveling = false;
                }
                if (Main.player[this.owner].petFlagCaveling)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 1027)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].petFlagDeadCellsSwarmBiter = false;
                }
                if (Main.player[this.owner].petFlagDeadCellsSwarmBiter)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 1046)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].petFlagPufferfish = false;
                }
                if (Main.player[this.owner].petFlagPufferfish)
                {
                    this.timeLeft = 2;
                }
            }
            if (flag6)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].pygmy = false;
                }
                if (Main.player[this.owner].pygmy)
                {
                    this.timeLeft = Main.rand.Next(2, 10);
                }
            }
            if (flag7)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].spiderMinion = false;
                }
                if (Main.player[this.owner].spiderMinion)
                {
                    this.timeLeft = 2;
                }
            }
            if (this.type == 398)
            {
                if (Main.player[this.owner].dead)
                {
                    Main.player[this.owner].miniMinotaur = false;
                }
                if (Main.player[this.owner].miniMinotaur)
                {
                    this.timeLeft = 2;
                }
            }
            if (flag11)
            {
                this.timeLeft = 2;
            }
            if (flag10 || this.type == 266 || flag7)
            {
                num = 10;
                int num3 = 40 * (this.minionPos + 1) * Main.player[this.owner].direction;
                if (Main.player[this.owner].Center.X < base.Center.X - (float)num + (float)num3)
                {
                    flag2 = true;
                }
                else if (Main.player[this.owner].Center.X > base.Center.X + (float)num + (float)num3)
                {
                    flag3 = true;
                }
            }
            else if (this.type == 1027)
            {
                num = 10;
                float num4 = (float)(28 * -(float)Main.player[this.owner].direction);
                float num5 = Main.player[this.owner].Center.X + num4;
                if (num5 < base.Center.X - (float)num)
                {
                    flag2 = true;
                }
                else if (num5 > base.Center.X + (float)num)
                {
                    flag3 = true;
                }
            }
            else if (this.type == 891)
            {
                num = 30;
                float num6 = (float)(-50 * -(float)Main.player[this.owner].direction);
                float num7 = Main.player[this.owner].Center.X + num6;
                if (num7 < this.position.X + (float)(this.width / 2) - (float)num)
                {
                    flag2 = true;
                }
                else if (num7 > this.position.X + (float)(this.width / 2) + (float)num)
                {
                    flag3 = true;
                }
            }
            else if (this.type == 960 && !flag11)
            {
                num = 10;
                Player player = Main.player[this.owner];
                int num8 = ((player.Center.X - base.Center.X > 0f) ? 1 : (-1));
                if (player.velocity.X != 0f)
                {
                    num8 = player.direction;
                }
                float num9 = (float)(-70 * num8);
                float num10 = player.Center.X + num9;
                if (num10 < base.Center.X - (float)num)
                {
                    flag2 = true;
                }
                else if (num10 > base.Center.X + (float)num)
                {
                    flag3 = true;
                }
            }
            else if (Main.player[this.owner].position.X + (float)(Main.player[this.owner].width / 2) < this.position.X + (float)(this.width / 2) - (float)num)
            {
                flag2 = true;
            }
            else if (Main.player[this.owner].position.X + (float)(Main.player[this.owner].width / 2) > this.position.X + (float)(this.width / 2) + (float)num)
            {
                flag3 = true;
            }
            if (flag12)
            {
                flag2 = false;
                flag3 = true;
            }
            if (flag13)
            {
                flag2 = false;
                flag3 = false;
            }
            if (flag8)
            {
                Player player2 = Main.player[this.owner];
                if (this.ai[0] >= 1000f)
                {
                    this.localAI[0] = 0f;
                    float num11 = 0f;
                    if (this.spriteDirection == -1)
                    {
                        num11 = 3.1415927f;
                    }
                    int num12 = 4;
                    if (this.ai[0] == 1000f && Main.myPlayer == this.owner && (player2.channel && !player2.noItems && !player2.CCed))
                    {
                        float num13 = player2.inventory[player2.selectedItem].shootSpeed * this.scale;
                        Vector2 vector = player2.RotatedRelativePoint(player2.MountedCenter, false, true);
                        Vector2 vector2 = Main.screenPosition + new Vector2((float)Main.mouseX, (float)Main.mouseY) - vector;
                        if (player2.gravDir == -1f)
{
                            vector2.Y = (float)(Main.screenHeight - Main.mouseY) + Main.screenPosition.Y - vector.Y;
                        }
                        Vector2 vector3 = Vector2.Normalize(vector2);
                        if (float.IsNaN(vector3.X) || float.IsNaN(vector3.Y))
{
                            vector3 = -Vector2.UnitY;
                        }
                        vector3 *= num13;
                        if (vector3.X != this.velocity.X || vector3.Y != this.velocity.Y)
{
                            this.netUpdate = true;
                        }
                        this.velocity = vector3;
                    }
                    this.direction = (this.spriteDirection = ((this.velocity.X > 0f) ? 1 : (-1)));
                    if (this.velocity.X == 0f)
                    {
                        this.direction = (this.spriteDirection = player2.direction);
                    }
                    player2.heldProj = this.type;
                    this.drawLayer = 7;
                    this.position = player2.RotatedRelativePoint(player2.MountedCenter, false, true) - base.Size / 2f;
                    this.rotation = this.velocity.ToRotation() + num11 + 3.1415927f;
                    this.spriteDirection = -this.direction;
                    this.timeLeft = 2;
                    float num14 = 0f;
                    player2.ChangeDir(this.direction);
                    player2.heldProj = this.whoAmI;
                    if (player2.channel)
                    {
                        player2.SetDummyItemTime(2);
                    }
                    player2.itemRotation = MathHelper.WrapAngle((float)Math.Atan2((double)(this.velocity.Y * (float)this.direction), (double)(this.velocity.X * (float)this.direction)) + num14);
                    if (this.ai[0] == 1000f && Main.myPlayer == this.owner && (player2.channel && !player2.noItems && !player2.CCed))
                    {
                        int num15 = 1106;
                        int num16 = (int)((float)this.damage * 0.75f);
                        float num17 = 5f;
                        int num18 = 0;
                        for (int i = 0; i < 1; i++)
{
                            Vector2 vector4 = base.Center + new Vector2((float)Main.rand.Next(-num18, num18 + 1), (float)Main.rand.Next(-num18, num18 + 1));
                            Vector2 vector5 = Vector2.Normalize(this.velocity) * num17;
                            if (float.IsNaN(vector5.X) || float.IsNaN(vector5.Y))
{
                                vector5 = -Vector2.UnitY;
                            }
                            int num19 = Projectile.NewProjectile(this.GetProjectileSource_FromThis(), vector4.X, vector4.Y, vector5.X, vector5.Y, num15, num16, this.knockBack, this.owner, 0f, 0f, 0f, null);
                            Projectile projectile = Main.projectile[num19];
                        }
                    }
                    float[] array = this.ai;
                    int num20 = 0;
                    float num21 = array[num20] + 1f;
                    array[num20] = num21;
                    if (num21 >= (float)(1000 + num12))
                    {
                        bool flag14 = (player2.HeldItem.type == 5664 && player2.channel) || Main.myPlayer != this.owner;
                        this.ai[0] = (float)(flag14 ? 1000 : 0);
                        this.localAI[0] = 30f;
                        if (this.ai[0] == 0f)
{
                            this.drawLayer = 0;
                        }
                        this.netUpdate = true;
                    }
                    return;
                }
                this.drawLayer = 0;
            }
            if (this.type == 175)
            {
                float num22 = 0.1f;
                this.tileCollide = false;
                int num23 = 300;
                Vector2 vector6 = new Vector2(this.position.X + (float)this.width * 0.5f, this.position.Y + (float)this.height * 0.5f);
                float num24 = Main.player[this.owner].position.X + (float)(Main.player[this.owner].width / 2) - vector6.X;
                float num25 = Main.player[this.owner].position.Y + (float)(Main.player[this.owner].height / 2) - vector6.Y;
                if (this.type == 127)
                {
                    num25 = Main.player[this.owner].position.Y - vector6.Y;
                }
                float num26 = (float)Math.Sqrt((double)(num24 * num24 + num25 * num25));
                float num27 = 7f;
                float num28 = 2000f;
                bool flag15 = num26 > num28;
                if (num26 < (float)num23 && Main.player[this.owner].velocity.Y == 0f && this.position.Y + (float)this.height <= Main.player[this.owner].position.Y + (float)Main.player[this.owner].height && !Collision.SolidCollision(this.position, this.width, this.height))
                {
                    this.ai[0] = 0f;
                    if (this.velocity.Y < -6f)
                    {
                        this.velocity.Y = -6f;
                    }
                }
                if (num26 < 150f)
                {
                    if (Math.Abs(this.velocity.X) > 2f || Math.Abs(this.velocity.Y) > 2f)
                    {
                        this.velocity *= 0.99f;
                    }
                    num22 = 0.01f;
                    if (num24 < -2f)
                    {
                        num24 = -2f;
                    }
                    if (num24 > 2f)
                    {
                        num24 = 2f;
                    }
                    if (num25 < -2f)
                    {
                        num25 = -2f;
                    }
                    if (num25 > 2f)
                    {
                        num25 = 2f;
                    }
                }
                else
                {
                    if (num26 > 300f)
                    {
                        num22 = 0.2f;
                    }
                    num26 = num27 / num26;
                    num24 *= num26;
                    num25 *= num26;
                }
                if (flag15)
                {
                    int num29 = 17;
                    for (int j = 0; j < 12; j++)
                    {
                        float num30 = 1f - Main.rand.NextFloat() * 2f;
                        float num31 = 1f - Main.rand.NextFloat() * 2f;
                        int num32 = Dust.NewDust(this.position, this.width, this.height, num29, num30, num31, 0, default(Color), 1f);
                        Main.dust[num32].noLightEmittance = true;
                        Main.dust[num32].noGravity = true;
                    }
                    base.Center = Main.player[this.owner].Center;
                    this.velocity = Vector2.Zero;
                    if (Main.myPlayer == this.owner)
                    {
                        this.netUpdate = true;
                    }
                }
                if (Math.Abs(num24) > Math.Abs(num25) || num22 == 0.05f)
                {
                    if (this.velocity.X < num24)
                    {
                        this.velocity.X = this.velocity.X + num22;
                        if (num22 > 0.05f && this.velocity.X < 0f)
{
                            this.velocity.X = this.velocity.X + num22;
                        }
                    }
                    if (this.velocity.X > num24)
                    {
                        this.velocity.X = this.velocity.X - num22;
                        if (num22 > 0.05f && this.velocity.X > 0f)
{
                            this.velocity.X = this.velocity.X - num22;
                        }
                    }
                }
                if (Math.Abs(num24) <= Math.Abs(num25) || num22 == 0.05f)
                {
                    if (this.velocity.Y < num25)
                    {
                        this.velocity.Y = this.velocity.Y + num22;
                        if (num22 > 0.05f && this.velocity.Y < 0f)
{
                            this.velocity.Y = this.velocity.Y + num22;
                        }
                    }
                    if (this.velocity.Y > num25)
                    {
                        this.velocity.Y = this.velocity.Y - num22;
                        if (num22 > 0.05f && this.velocity.Y > 0f)
{
                            this.velocity.Y = this.velocity.Y - num22;
                        }
                    }
                }
                this.rotation = (float)Math.Atan2((double)this.velocity.Y, (double)this.velocity.X) - 1.57f;
                this.frameCounter++;
                if (this.frameCounter > 6)
                {
                    this.frame++;
                    this.frameCounter = 0;
                }
                if (this.frame > 1)
                {
                    this.frame = 0;
                    return;
                }
            }
            else if (this.type == 197)
            {
                float num33 = 0.1f;
                this.tileCollide = false;
                int num34 = 300;
                Vector2 vector7 = new Vector2(this.position.X + (float)this.width * 0.5f, this.position.Y + (float)this.height * 0.5f);
                float num35 = Main.player[this.owner].position.X + (float)(Main.player[this.owner].width / 2) - vector7.X;
                float num36 = Main.player[this.owner].position.Y + (float)(Main.player[this.owner].height / 2) - vector7.Y;
                if (this.type == 127)
                {
                    num36 = Main.player[this.owner].position.Y - vector7.Y;
                }
                float num37 = (float)Math.Sqrt((double)(num35 * num35 + num36 * num36));
                float num38 = 3f;
                if (num37 > 500f)
                {
                    this.localAI[0] = 10000f;
                }
                if (this.localAI[0] >= 10000f)
                {
                    num38 = 14f;
                }
                float num39 = 2000f;
                bool flag16 = num37 > num39;
                if (num37 < (float)num34 && Main.player[this.owner].velocity.Y == 0f && this.position.Y + (float)this.height <= Main.player[this.owner].position.Y + (float)Main.player[this.owner].height && !Collision.SolidCollision(this.position, this.width, this.height))
                {
                    this.ai[0] = 0f;
                    if (this.velocity.Y < -6f)
                    {
                        this.velocity.Y = -6f;
                    }
                }
                if (num37 < 150f)
                {
                    if (Math.Abs(this.velocity.X) > 2f || Math.Abs(this.velocity.Y) > 2f)
                    {
                        this.velocity *= 0.99f;
                    }
                    num33 = 0.01f;
                    if (num35 < -2f)
                    {
                        num35 = -2f;
                    }
                    if (num35 > 2f)
                    {
                        num35 = 2f;
                    }
                    if (num36 < -2f)
                    {
                        num36 = -2f;
                    }
                    if (num36 > 2f)
                    {
                        num36 = 2f;
                    }
                }
                else
                {
                    if (num37 > 300f)
                    {
                        num33 = 0.2f;
                    }
                    num37 = num38 / num37;
                    num35 *= num37;
                    num36 *= num37;
                }
                if (flag16)
                {
                    int num40 = 26;
                    for (int k = 0; k < 12; k++)
                    {
                        float num41 = 1f - Main.rand.NextFloat() * 2f;
                        float num42 = 1f - Main.rand.NextFloat() * 2f;
                        int num43 = Dust.NewDust(this.position, this.width, this.height, num40, num41, num42, 0, default(Color), 1f);
                        Main.dust[num43].noLightEmittance = true;
                        Main.dust[num43].noGravity = true;
                    }
                    base.Center = Main.player[this.owner].Center;
                    this.velocity = Vector2.Zero;
                    if (Main.myPlayer == this.owner)
                    {
                        this.netUpdate = true;
                    }
                }
                if (this.velocity.X < num35)
                {
                    this.velocity.X = this.velocity.X + num33;
                    if (num33 > 0.05f && this.velocity.X < 0f)
                    {
                        this.velocity.X = this.velocity.X + num33;
                    }
                }
                if (this.velocity.X > num35)
                {
                    this.velocity.X = this.velocity.X - num33;
                    if (num33 > 0.05f && this.velocity.X > 0f)
                    {
                        this.velocity.X = this.velocity.X - num33;
                    }
                }
                if (this.velocity.Y < num36)
                {
                    this.velocity.Y = this.velocity.Y + num33;
                    if (num33 > 0.05f && this.velocity.Y < 0f)
                    {
                        this.velocity.Y = this.velocity.Y + num33;
                    }
                }
                if (this.velocity.Y > num36)
                {
                    this.velocity.Y = this.velocity.Y - num33;
                    if (num33 > 0.05f && this.velocity.Y > 0f)
                    {
                        this.velocity.Y = this.velocity.Y - num33;
                    }
                }
                this.localAI[0] += (float)Main.rand.Next(10);
                if (this.localAI[0] > 10000f)
                {
                    if (this.localAI[1] == 0f)
                    {
                        if (this.velocity.X < 0f)
{
                            this.localAI[1] = -1f;
                        }
                        else
{
                            this.localAI[1] = 1f;
                        }
                    }
                    this.rotation += 0.25f * this.localAI[1];
                    if (this.localAI[0] > 12000f)
                    {
                        this.localAI[0] = 0f;
                    }
                }
                else
                {
                    this.localAI[1] = 0f;
                    float num44 = this.velocity.X * 0.1f;
                    if (this.rotation > num44)
                    {
                        this.rotation -= (Math.Abs(this.velocity.X) + Math.Abs(this.velocity.Y)) * 0.01f;
                        if (this.rotation < num44)
{
                            this.rotation = num44;
                        }
                    }
                    if (this.rotation < num44)
                    {
                        this.rotation += (Math.Abs(this.velocity.X) + Math.Abs(this.velocity.Y)) * 0.01f;
                        if (this.rotation > num44)
{
                            this.rotation = num44;
                        }
                    }
                }
                if ((double)this.rotation > 6.28)
                {
                    this.rotation -= 6.28f;
                }
                if ((double)this.rotation < -6.28)
                {
                    this.rotation += 6.28f;
                    return;
                }
            }
            else if (this.type == 198 || this.type == 380 || this.type == 774 || this.type == 815 || this.type == 817 || this.type == 886 || this.type == 892 || this.type == 894 || this.type == 901 || this.type == 1046)
            {
                float num45 = 0.4f;
                if (this.type == 380)
                {
                    num45 = 0.3f;
                }
                if (this.type == 774 || this.type == 1046)
                {
                    num45 = 0.3f;
                }
                this.tileCollide = false;
                int num46 = 100;
                float num47 = 50f;
                float num48 = 400f;
                float num49 = num48 / 2f;
                float num50 = 2000f;
                bool flag17 = false;
                Vector2 vector8 = new Vector2(this.position.X + (float)this.width * 0.5f, this.position.Y + (float)this.height * 0.5f);
                float num51 = Main.player[this.owner].position.X + (float)(Main.player[this.owner].width / 2) - vector8.X;
                float num52 = Main.player[this.owner].position.Y + (float)(Main.player[this.owner].height / 2) - vector8.Y;
                if (this.type == 774 || this.type == 1046)
                {
                    num47 = 2f;
                    float num53 = (float)Math.Sin((double)(6.2831855f * ((float)Main.player[this.owner].miscCounter / 60f)));
                    float num54 = Utils.GetLerpValue(0.5f, 1f, num53, true);
                    if (new Vector2(num51 - (float)(70 * Main.player[this.owner].direction), num52 - 60f).Length() > 50f)
                    {
                        num53 = 0f;
                        num54 = 0f;
                    }
                    num52 += -60f + num54 * -8f + num53 * 8f;
                    num51 += (float)(70 * -(float)Main.player[this.owner].direction);
                }
                else
                {
                    if (this.type != 892 && this.type != 894)
                    {
                        num52 += (float)Main.rand.Next(-10, 21);
                        num51 += (float)Main.rand.Next(-10, 21);
                    }
                    num51 += (float)(60 * -(float)Main.player[this.owner].direction);
                    num52 -= 60f;
                }
                Vector2 vector9 = new Vector2(num51, num52);
                if (this.type == 127)
                {
                    num52 = Main.player[this.owner].position.Y - vector8.Y;
                }
                float num55 = (float)Math.Sqrt((double)(num51 * num51 + num52 * num52));
                float num56 = num55;
                float num57 = 14f;
                if (this.type == 380)
                {
                    num57 = 6f;
                }
                if (this.type == 815 || this.type == 817)
                {
                    if (num55 < num48)
                    {
                        num57 = 6f;
                    }
                    else
                    {
                        num57 = 10f;
                    }
                }
                if (this.type == 892 || this.type == 894 || this.type == 901)
                {
                    if (num55 < num49)
                    {
                    }
                    if (num55 < num48)
                    {
                        num57 = 9f;
                    }
                    else
                    {
                        num57 = 12f;
                    }
                }
                if (this.type == 774)
                {
                    num57 = 5f;
                }
                if (this.type == 1046)
                {
                    num57 = 5f;
                    if (num55 >= num48)
                    {
                        num57 = 8f;
                    }
                }
                if (num55 < (float)num46 && Main.player[this.owner].velocity.Y == 0f && this.position.Y + (float)this.height <= Main.player[this.owner].position.Y + (float)Main.player[this.owner].height && !Collision.SolidCollision(this.position, this.width, this.height))
                {
                    this.ai[0] = 0f;
                    if (this.velocity.Y < -6f)
                    {
                        this.velocity.Y = -6f;
                    }
                }
                if (num55 < num47)
                {
                    if (Math.Abs(this.velocity.X) > 2f || Math.Abs(this.velocity.Y) > 2f)
                    {
                        if (this.type == 892 || this.type == 892)
{
                            this.velocity *= 0.95f;
                        }
                        else
{
                            this.velocity *= 0.99f;
                        }
                    }
                    num45 = 0.01f;
                }
                else
                {
                    if (this.type == 892 || this.type == 894 || this.type == 901)
                    {
                        if (num55 < 100f)
{
                            num45 = 0.1f;
                        }
                        if (num55 > num50)
{
                            flag17 = true;
                        }
                        else if (num55 > num48)
{
                            num45 = 0.7f;
                        }
                        else if (num55 > num49)
{
                            num45 = 0.5f;
                        }
                    }
                    else if (this.type == 815 || this.type == 817)
                    {
                        if (num55 < 100f)
{
                            num45 = 0.1f;
                        }
                        if (num55 > num50)
{
                            flag17 = true;
                        }
                        else if (this.type != 815 && num55 > num48)
{
                            num45 = 0.5f;
                        }
                    }
                    else if (this.type == 380)
                    {
                        if (num55 < 100f)
{
                            num45 = 0.1f;
                        }
                        if (num55 > 300f)
{
                            num45 = 0.4f;
                        }
                        if (num55 > num50)
{
                            flag17 = true;
                        }
                    }
                    else if (this.type == 198 || this.type == 886)
                    {
                        if (num55 < 100f)
{
                            num45 = 0.1f;
                        }
                        if (num55 > 300f)
{
                            num45 = 0.6f;
                        }
                        if (num55 > num50)
{
                            flag17 = true;
                        }
                    }
                    else if (this.type == 774 || this.type == 1046)
                    {
                        if (num55 < 40f)
{
                            num45 = 0.1f;
                        }
                        if (num55 > 300f)
{
                            num45 = 0.6f;
                        }
                        if (num55 > num50)
{
                            flag17 = true;
                        }
                    }
                    num55 = num57 / num55;
                    num51 *= num55;
                    num52 *= num55;
                }
                if (this.velocity.X < num51)
                {
                    this.velocity.X = this.velocity.X + num45;
                    if (num45 > 0.05f && this.velocity.X < 0f)
                    {
                        this.velocity.X = this.velocity.X + num45;
                    }
                }
                if (this.velocity.X > num51)
                {
                    this.velocity.X = this.velocity.X - num45;
                    if (num45 > 0.05f && this.velocity.X > 0f)
                    {
                        this.velocity.X = this.velocity.X - num45;
                    }
                }
                if (this.velocity.Y < num52)
                {
                    this.velocity.Y = this.velocity.Y + num45;
                    if (num45 > 0.05f && this.velocity.Y < 0f)
                    {
                        this.velocity.Y = this.velocity.Y + num45 * 2f;
                    }
                }
                if (this.velocity.Y > num52)
                {
                    this.velocity.Y = this.velocity.Y - num45;
                    if (num45 > 0.05f && this.velocity.Y > 0f)
                    {
                        this.velocity.Y = this.velocity.Y - num45 * 2f;
                    }
                }
                if ((double)this.velocity.X > 0.25)
                {
                    this.direction = -1;
                }
                else if ((double)this.velocity.X < -0.25)
                {
                    this.direction = 1;
                }
                this.spriteDirection = this.direction;
                this.rotation = this.velocity.X * 0.05f;
                if (flag17)
                {
                    int num58 = 33;
                    if (this.type == 198 || this.type == 886)
                    {
                        num58 = 147;
                    }
                    if (this.type == 815)
                    {
                        num58 = 31;
                    }
                    if (this.type == 817)
                    {
                        num58 = 21;
                    }
                    for (int l = 0; l < 12; l++)
                    {
                        float num59 = 1f - Main.rand.NextFloat() * 2f;
                        float num60 = 1f - Main.rand.NextFloat() * 2f;
                        int num61 = Dust.NewDust(this.position, this.width, this.height, num58, num59, num60, 0, default(Color), 1f);
                        Main.dust[num61].noLightEmittance = true;
                        Main.dust[num61].noGravity = true;
                    }
                    base.Center = Main.player[this.owner].Center;
                    this.velocity = Vector2.Zero;
                    if (Main.myPlayer == this.owner)
                    {
                        this.netUpdate = true;
                    }
                }
                bool flag18 = false;
                int num62 = 3;
                int num63 = 0;
                int num64 = 3;
                if (this.type == 380)
                {
                    num62 = 6;
                }
                if (this.type == 815)
                {
                    num62 = 5;
                    num63 = 0;
                    num64 = 5;
                    if (num56 > num48)
                    {
                        num63 = 6;
                        num64 = 9;
                    }
                }
                if (this.type == 817)
                {
                    num62 = 5;
                    num63 = 0;
                    num64 = 2;
                    flag18 = true;
                }
                if (this.type == 901)
                {
                    num62 = 4;
                    num63 = 0;
                    num64 = 5;
                    if (num56 > num48 / 2f)
                    {
                        num62 = 3;
                        num63 = 6;
                        num64 = 11;
                    }
                }
                if (this.type == 892)
                {
                    num62 = 6;
                    num63 = 0;
                    num64 = Main.projFrames[this.type] - 1;
                }
                if (this.type == 886 || this.type == 894)
                {
                    num62 = 4;
                    num63 = 0;
                    num64 = Main.projFrames[this.type] - 1;
                }
                if (this.type == 774)
                {
                    if (Main.player[this.owner].velocity.Length() < 2f && vector9.Length() < 10f)
                    {
                        this.direction = -Main.player[this.owner].direction;
                        this.spriteDirection = this.direction;
                    }
                    num62 = 6;
                    if (!this.wet)
                    {
                        num63 += 4;
                        num64 += 4;
                    }
                    this.rotation = this.velocity.X * 0.05f + Math.Abs(this.velocity.Y * -0.05f);
                }
                if (this.type == 1046)
                {
                    num63 = 0;
                    num64 = 3;
                    if (Main.player[this.owner].velocity.Length() < 2f && vector9.Length() < 10f)
                    {
                        this.direction = -Main.player[this.owner].direction;
                        this.spriteDirection = this.direction;
                    }
                    num62 = 7;
                    bool flag19 = num56 >= num48;
                    bool flag20 = !this.wet;
                    if (flag19)
                    {
                        num63 = 4;
                        num64 = 5;
                        num62 = 6;
                    }
                    if (flag20)
                    {
                        num63 += 6;
                        num64 += 6;
                    }
                    this.rotation = this.velocity.X * 0.05f + Math.Abs(this.velocity.Y * -0.05f);
                }
                if (flag18)
                {
                    int num65 = num62 * (num64 - num63) * 2;
                    this.frameCounter++;
                    if (this.frameCounter >= num65)
                    {
                        this.frameCounter = 0;
                    }
                    this.frame = this.frameCounter / num62;
                    if (this.frame > num64)
                    {
                        this.frame = num64 + (num64 - this.frame);
                    }
                    this.frame = (int)MathHelper.Clamp((float)this.frame, (float)num63, (float)num64);
                    return;
                }
                if (num62 > 0)
                {
                    num2 = this.frameCounter + 1;
                    this.frameCounter = num2;
                    if (num2 >= num62)
                    {
                        this.frameCounter = 0;
                        this.frame++;
                        if (this.frame < num63 || this.frame > num64)
{
                            this.frame = num63;
                            return;
                        }
                    }
                }
            }
            else if (this.type == 211)
            {
                float num66 = 0.2f;
                float num67 = 5f;
                this.tileCollide = false;
                Vector2 vector10 = new Vector2(this.position.X + (float)this.width * 0.5f, this.position.Y + (float)this.height * 0.5f);
                float num68 = Main.player[this.owner].position.X + (float)(Main.player[this.owner].width / 2) - vector10.X;
                float num69 = Main.player[this.owner].position.Y + Main.player[this.owner].gfxOffY + (float)(Main.player[this.owner].height / 2) - vector10.Y;
                if (Main.player[this.owner].controlLeft)
                {
                    num68 -= 120f;
                }
                else if (Main.player[this.owner].controlRight)
                {
                    num68 += 120f;
                }
                if (Main.player[this.owner].controlDown)
                {
                    num69 += 120f;
                }
                else
                {
                    if (Main.player[this.owner].controlUp)
                    {
                        num69 -= 120f;
                    }
                    num69 -= 60f;
                }
                float num70 = (float)Math.Sqrt((double)(num68 * num68 + num69 * num69));
                if (num70 > 1000f)
                {
                    this.position.X = this.position.X + num68;
                    this.position.Y = this.position.Y + num69;
                }
                if (this.localAI[0] == 1f)
                {
                    if (num70 < 10f)
                    {
                        Player player3 = Main.player[this.owner];
                        if (Math.Abs(player3.velocity.X) + Math.Abs(player3.velocity.Y) < num67 && (player3.velocity.Y == 0f || (player3.mount.Active && player3.mount.CanFly(player3))))
{
                            this.localAI[0] = 0f;
                        }
                    }
                    num67 = 12f;
                    if (num70 < num67)
                    {
                        this.velocity.X = num68;
                        this.velocity.Y = num69;
                    }
                    else
                    {
                        num70 = num67 / num70;
                        this.velocity.X = num68 * num70;
                        this.velocity.Y = num69 * num70;
                    }
                    if ((double)this.velocity.X > 0.5)
                    {
                        this.direction = -1;
                    }
                    else if ((double)this.velocity.X < -0.5)
                    {
                        this.direction = 1;
                    }
                    this.spriteDirection = this.direction;
                    this.rotation -= (0.2f + Math.Abs(this.velocity.X) * 0.025f) * (float)this.direction;
                    this.frameCounter++;
                    if (this.frameCounter > 3)
                    {
                        this.frame++;
                        this.frameCounter = 0;
                    }
                    if (this.frame < 5)
                    {
                        this.frame = 5;
                    }
                    if (this.frame > 9)
                    {
                        this.frame = 5;
                    }
                    for (int m = 0; m < 2; m++)
                    {
                        int num71 = Dust.NewDust(new Vector2(this.position.X + 3f, this.position.Y + 4f), 14, 14, 156, 0f, 0f, 0, default(Color), 1f);
                        Main.dust[num71].velocity *= 0.2f;
                        Main.dust[num71].noGravity = true;
                        Main.dust[num71].scale = 1.25f;
                        Main.dust[num71].shader = GameShaders.Armor.GetSecondaryShader(Main.player[this.owner].cLight, Main.player[this.owner]);
                    }
                    return;
                }
                if (num70 > 200f)
                {
                    this.localAI[0] = 1f;
                }
                if ((double)this.velocity.X > 0.5)
                {
                    this.direction = -1;
                }
                else if ((double)this.velocity.X < -0.5)
                {
                    this.direction = 1;
                }
                this.spriteDirection = this.direction;
                if (num70 < 10f)
                {
                    this.velocity.X = num68;
                    this.velocity.Y = num69;
                    this.rotation = this.velocity.X * 0.05f;
                    if (num70 < num67)
                    {
                        this.position += this.velocity;
                        this.velocity *= 0f;
                        num66 = 0f;
                    }
                    this.direction = -Main.player[this.owner].direction;
                }
                num70 = num67 / num70;
                num68 *= num70;
                num69 *= num70;
                if (this.velocity.X < num68)
                {
                    this.velocity.X = this.velocity.X + num66;
                    if (this.velocity.X < 0f)
                    {
                        this.velocity.X = this.velocity.X * 0.99f;
                    }
                }
                if (this.velocity.X > num68)
                {
                    this.velocity.X = this.velocity.X - num66;
                    if (this.velocity.X > 0f)
                    {
                        this.velocity.X = this.velocity.X * 0.99f;
                    }
                }
                if (this.velocity.Y < num69)
                {
                    this.velocity.Y = this.velocity.Y + num66;
                    if (this.velocity.Y < 0f)
                    {
                        this.velocity.Y = this.velocity.Y * 0.99f;
                    }
                }
                if (this.velocity.Y > num69)
                {
                    this.velocity.Y = this.velocity.Y - num66;
                    if (this.velocity.Y > 0f)
                    {
                        this.velocity.Y = this.velocity.Y * 0.99f;
                    }
                }
                if (this.velocity.X != 0f || this.velocity.Y != 0f)
                {
                    this.rotation = this.velocity.X * 0.05f;
                }
                this.frameCounter++;
                if (this.frameCounter > 3)
                {
                    this.frame++;
                    this.frameCounter = 0;
                }
                if (this.frame > 4)
                {
                    this.frame = 0;
                    return;
                }
            }
            else if (this.type == 199)
            {
                float num72 = 0.1f;
                this.tileCollide = false;
                int num73 = 200;
                Vector2 vector11 = new Vector2(this.position.X + (float)this.width * 0.5f, this.position.Y + (float)this.height * 0.5f);
                float num74 = Main.player[this.owner].position.X + (float)(Main.player[this.owner].width / 2) - vector11.X;
                float num75 = Main.player[this.owner].position.Y + (float)(Main.player[this.owner].height / 2) - vector11.Y;
                num75 -= 60f;
                num74 -= 2f;
                if (this.type == 127)
                {
                    num75 = Main.player[this.owner].position.Y - vector11.Y;
                }
                float num76 = (float)Math.Sqrt((double)(num74 * num74 + num75 * num75));
                float num77 = 4f;
                float num78 = num76;
                float num79 = 2000f;
                bool flag21 = num76 > num79;
                if (num76 < (float)num73 && Main.player[this.owner].velocity.Y == 0f && this.position.Y + (float)this.height <= Main.player[this.owner].position.Y + (float)Main.player[this.owner].height && !Collision.SolidCollision(this.position, this.width, this.height))
                {
                    this.ai[0] = 0f;
                    if (this.velocity.Y < -6f)
                    {
                        this.velocity.Y = -6f;
                    }
                }
                if (num76 < 4f)
                {
                    this.velocity.X = num74;
                    this.velocity.Y = num75;
                    num72 = 0f;
                }
                else
                {
                    if (num76 > 350f)
                    {
                        num72 = 0.2f;
                        num77 = 10f;
                    }
                    num76 = num77 / num76;
                    num74 *= num76;
                    num75 *= num76;
                }
                if (flag21)
                {
                    int num80 = 2;
                    for (int n = 0; n < 12; n++)
                    {
                        float num81 = 1f - Main.rand.NextFloat() * 2f;
                        float num82 = 1f - Main.rand.NextFloat() * 2f;
                        int num83 = Dust.NewDust(this.position, this.width, this.height, num80, num81, num82, 0, default(Color), 1f);
                        Main.dust[num83].noLightEmittance = true;
                        Main.dust[num83].noGravity = true;
                    }
                    base.Center = Main.player[this.owner].Center;
                    this.velocity = Vector2.Zero;
                    if (Main.myPlayer == this.owner)
                    {
                        this.netUpdate = true;
                    }
                }
                if (this.velocity.X < num74)
                {
                    this.velocity.X = this.velocity.X + num72;
                    if (this.velocity.X < 0f)
                    {
                        this.velocity.X = this.velocity.X + num72;
                    }
                }
                if (this.velocity.X > num74)
                {
                    this.velocity.X = this.velocity.X - num72;
                    if (this.velocity.X > 0f)
                    {
                        this.velocity.X = this.velocity.X - num72;
                    }
                }
                if (this.velocity.Y < num75)
                {
                    this.velocity.Y = this.velocity.Y + num72;
                    if (this.velocity.Y < 0f)
                    {
                        this.velocity.Y = this.velocity.Y + num72;
                    }
                }
                if (this.velocity.Y > num75)
                {
                    this.velocity.Y = this.velocity.Y - num72;
                    if (this.velocity.Y > 0f)
                    {
                        this.velocity.Y = this.velocity.Y - num72;
                    }
                }
                this.direction = -Main.player[this.owner].direction;
                this.spriteDirection = 1;
                this.rotation = this.velocity.Y * 0.05f * (float)(-(float)this.direction);
                if (num78 >= 50f)
                {
                    this.frameCounter++;
                    if (this.frameCounter > 6)
                    {
                        this.frameCounter = 0;
                        if (this.velocity.X < 0f)
{
                            if (this.frame < 2)
{
                                this.frame++;
                            }
                            if (this.frame > 2)
{
                                this.frame--;
                                return;
                            }
                        }
                        else
{
                            if (this.frame < 6)
{
                                this.frame++;
                            }
                            if (this.frame > 6)
{
                                this.frame--;
                                return;
                            }
                        }
                    }
                }
                else
                {
                    this.frameCounter++;
                    if (this.frameCounter > 6)
                    {
                        this.frame += this.direction;
                        this.frameCounter = 0;
                    }
                    if (this.frame > 7)
                    {
                        this.frame = 0;
                    }
                    if (this.frame < 0)
                    {
                        this.frame = 7;
                        return;
                    }
                }
            }
            else if (this.type == 885 || this.type == 889)
            {
                Player player4 = Main.player[this.owner];
                float num84 = 0.15f;
                this.tileCollide = false;
                int num85 = 150;
                Vector2 center = base.Center;
                float num86 = player4.Center.X - center.X;
                float num87 = player4.Center.Y - center.Y;
                num87 -= 65f;
                num86 -= (float)(30 * player4.direction);
                float num88 = (float)Math.Sqrt((double)(num86 * num86 + num87 * num87));
                float num89 = 8f;
                float num90 = num88;
                float num91 = 2000f;
                bool flag22 = num88 > num91;
                if (num88 < (float)num85 && player4.velocity.Y == 0f && this.position.Y + (float)this.height <= player4.position.Y + (float)player4.height && !Collision.SolidCollision(this.position, this.width, this.height) && this.velocity.Y < -6f)
                {
                    this.velocity.Y = -6f;
                }
                if (num88 < 10f)
                {
                    this.velocity *= 0.9f;
                    if (this.velocity.Length() < 0.5f)
                    {
                        this.velocity = Vector2.Zero;
                    }
                    num84 = 0f;
                }
                else
                {
                    if (num88 > (float)num85)
                    {
                        num84 = 0.2f;
                        num89 = 12f;
                    }
                    num88 = num89 / num88;
                    num86 *= num88;
                    num87 *= num88;
                }
                if (flag22)
                {
                    int num92 = 234;
                    if (this.type == 889)
                    {
                        num92 = 60;
                    }
                    for (int num93 = 0; num93 < 12; num93++)
                    {
                        float num94 = 1f - Main.rand.NextFloat() * 2f;
                        float num95 = 1f - Main.rand.NextFloat() * 2f;
                        int num96 = Dust.NewDust(this.position, this.width, this.height, num92, num94, num95, 0, default(Color), 1f);
                        Main.dust[num96].noLightEmittance = true;
                        Main.dust[num96].noGravity = true;
                    }
                    base.Center = player4.Center;
                    this.velocity = Vector2.Zero;
                    if (Main.myPlayer == this.owner)
                    {
                        this.netUpdate = true;
                    }
                }
                if (this.velocity.X < num86)
                {
                    this.velocity.X = this.velocity.X + num84;
                    if (this.velocity.X < 0f)
                    {
                        this.velocity.X = this.velocity.X + num84;
                    }
                }
                if (this.velocity.X > num86)
                {
                    this.velocity.X = this.velocity.X - num84;
                    if (this.velocity.X > 0f)
                    {
                        this.velocity.X = this.velocity.X - num84;
                    }
                }
                if (this.velocity.Y < num87)
                {
                    this.velocity.Y = this.velocity.Y + num84;
                    if (this.velocity.Y < 0f)
                    {
                        this.velocity.Y = this.velocity.Y + num84;
                    }
                }
                if (this.velocity.Y > num87)
                {
                    this.velocity.Y = this.velocity.Y - num84;
                    if (this.velocity.Y > 0f)
                    {
                        this.velocity.Y = this.velocity.Y - num84;
                    }
                }
                this.direction = -player4.direction;
                this.spriteDirection = -this.direction;
                int num97 = 100;
                if (num90 >= (float)num85)
                {
                    this.rotation += 0.5f;
                    if (this.rotation > 6.2831855f)
                    {
                        this.rotation -= 6.2831855f;
                    }
                    this.frame = 6;
                    this.frameCounter = 0;
                    if (this.type == 885)
                    {
                        this.localAI[0] = 0f;
                    }
                    if (this.type == 889)
                    {
                        this.localAI[0] += 3f;
                        if (this.localAI[0] > (float)num97)
{
                            this.localAI[0] = (float)num97;
                            return;
                        }
                    }
                }
                else
                {
                    this.rotation *= 0.95f;
                    if (this.rotation < 0.05f)
                    {
                        this.rotation = 0f;
                    }
                    this.frameCounter++;
                    if (this.type == 885)
                    {
                        num2 = this.frameCounter;
                        if (num2 <= 20)
{
                            if (num2 != 10)
{
                                if (num2 == 20)
{
                                    this.localAI[0] = 1f;
                                }
                            }
                            else
{
                                this.localAI[0] = 0f;
                            }
                        }
                        else if (num2 != 30)
{
                            if (num2 == 40)
{
                                this.localAI[0] = 1f;
                            }
                        }
                        else
{
                            this.localAI[0] = 2f;
                        }
                    }
                    if (this.type == 889)
                    {
                        this.localAI[0] -= 3f;
                        if (this.localAI[0] < 0f)
{
                            this.localAI[0] = 0f;
                        }
                    }
                    if (this.frameCounter % 5 == 0)
                    {
                        this.frame++;
                        if (this.frame > 5)
{
                            this.frame = 0;
                        }
                    }
                    if (this.frameCounter >= 40)
                    {
                        this.frameCounter = 0;
                        return;
                    }
                }
            }
            else
            {
                bool flag23 = this.ai[1] == 0f;
                if (flag)
                {
                    flag23 = true;
                }
                if (flag23)
                {
                    int num98 = 500;
                    if (this.type == 127)
                    {
                        num98 = 200;
                    }
                    if (this.type == 208)
                    {
                        num98 = 300;
                    }
                    num2 = this.type;
                    if (num2 <= 860)
                    {
                        if (num2 <= 821)
{
                            if (num2 != 816)
{
                                if (num2 != 821)
{
                                    goto IL_495F;
                                }
                                goto IL_4958;
                            }
                        }
                        else if (num2 != 825 && num2 != 854 && num2 - 858 > 2)
{
                            goto IL_495F;
                        }
                    }
                    else if (num2 <= 884)
                    {
                        if (num2 != 881 && num2 != 884)
{
                            goto IL_495F;
                        }
                    }
                    else if (num2 - 890 > 1)
                    {
                        switch (num2)
{
                        case 897:
                        case 900:
                            break;
                        case 898:
                            goto IL_495F;
                        case 899:
                            goto IL_4958;
                        default:
                            if (num2 != 934)
{
                                goto IL_495F;
                            }
                            break;
                        }
                    }
                    num98 = 400;
                    goto IL_495F;
                    IL_4958:
                    num98 = 500;
                    IL_495F:
                    if (flag10 || this.type == 266 || flag7)
                    {
                        num98 += 40 * this.minionPos;
                        if (this.localAI[0] > 0f)
{
                            num98 += 500;
                        }
                        if (this.type == 266 && this.localAI[0] > 0f)
{
                            num98 += 100;
                        }
                        if (flag7 && this.localAI[0] > 0f)
{
                            num98 += 400;
                        }
                    }
                    bool flag24 = false;
                    Vector2 vector12 = new Vector2(this.position.X + (float)this.width * 0.5f, this.position.Y + (float)this.height * 0.5f);
                    float num99 = Main.player[this.owner].position.X + (float)(Main.player[this.owner].width / 2) - vector12.X;
                    float num100 = Main.player[this.owner].position.Y + (float)(Main.player[this.owner].height / 2) - vector12.Y;
                    float num101 = (float)Math.Sqrt((double)(num99 * num99 + num100 * num100));
                    if (!flag11)
                    {
                        if (num101 > 2000f)
{
                            this.position.X = Main.player[this.owner].position.X + (float)(Main.player[this.owner].width / 2) - (float)(this.width / 2);
                            this.position.Y = Main.player[this.owner].position.Y + (float)(Main.player[this.owner].height / 2) - (float)(this.height / 2);
                        }
                        else if (num101 > (float)num98 || (Math.Abs(num100) > 300f && ((!flag10 && this.type != 266 && !flag7) || this.localAI[0] <= 0f)))
{
                            if (this.type != 324)
{
                                if (num100 > 0f && this.velocity.Y < 0f)
{
                                    this.velocity.Y = 0f;
                                }
                                if (num100 < 0f && this.velocity.Y > 0f)
{
                                    this.velocity.Y = 0f;
                                }
                            }
                            flag24 = true;
                        }
                    }
                    if (flag24)
                    {
                        if (flag8 && this.ai[0] != 1f)
{
                            this.alpha = 255;
                        }
                        this.ai[0] = 1f;
                    }
                }
                if ((this.type == 209 || this.type == 956 || this.type == 1027) && this.ai[0] != 0f)
                {
                    if (Main.player[this.owner].velocity.Y == 0f && this.alpha >= 100)
                    {
                        this.position.X = Main.player[this.owner].position.X + (float)(Main.player[this.owner].width / 2) - (float)(this.width / 2);
                        this.position.Y = Main.player[this.owner].position.Y + (float)Main.player[this.owner].height - (float)this.height;
                        this.ai[0] = 0f;
                    }
                    else
                    {
                        this.velocity.X = 0f;
                        this.velocity.Y = 0f;
                        if (this.type == 1027 && this.alpha < 255)
{
                            this.alpha = 255;
                            int num102 = 25;
                            float num103 = Main.rand.NextFloat() * 6.2831855f;
                            for (int num104 = 0; num104 < num102; num104++)
{
                                bool flag25 = num104 % 2 == 0;
                                float num105 = num103 + (float)num104 / (float)num102 * 6.2831855f;
                                Vector2 vector13 = new Vector2(0f, flag25 ? 2f : 4f).RotatedBy((double)num105, default(Vector2));
                                Dust dust = Dust.NewDustPerfect(base.Center, 282, new Vector2?(vector13), 0, default(Color), 1f);
                                dust.scale = (flag25 ? 1.3f : 1.2f);
                                dust.noGravity = true;
                            }
                        }
                        if (this.type == 956 && this.alpha < 100)
{
                            int num106 = Dust.NewDust(this.position, this.width, this.height, 6, this.velocity.X, this.velocity.Y, 0, default(Color), 1.2f);
                            Dust dust2 = Main.dust[num106];
                            dust2.velocity.X = dust2.velocity.X + (Main.rand.NextFloat() - 0.5f);
                            Dust dust3 = Main.dust[num106];
                            dust3.velocity.Y = dust3.velocity.Y + (Main.rand.NextFloat() + 0.5f) * -1f;
                            if (Main.rand.Next(3) != 0)
{
                                Main.dust[num106].noGravity = true;
                            }
                        }
                        this.alpha += 5;
                        if (this.alpha > 255)
{
                            this.alpha = 255;
                        }
                    }
                }
                else if (this.ai[0] != 0f && !flag11)
                {
                    float num107 = 0.2f;
                    int num108 = 200;
                    if (this.type == 127)
                    {
                        num108 = 100;
                    }
                    if (flag10 || this.type == 816 || this.type == 821 || this.type == 825 || this.type == 854 || this.type == 858 || this.type == 859 || this.type == 860)
                    {
                        num107 = 0.5f;
                        num108 = 100;
                    }
                    if (this.type == 875)
                    {
                        num107 = 2f;
                        num108 = 100;
                    }
                    this.tileCollide = false;
                    Vector2 vector14 = new Vector2(this.position.X + (float)this.width * 0.5f, this.position.Y + (float)this.height * 0.5f);
                    float num109 = Main.player[this.owner].position.X + (float)(Main.player[this.owner].width / 2) - vector14.X;
                    if (flag10 || this.type == 266 || flag7)
                    {
                        num109 -= (float)(40 * Main.player[this.owner].direction);
                        float num110 = 700f;
                        if (flag10)
{
                            num110 += 100f;
                        }
                        bool flag26 = false;
                        int num111 = -1;
                        for (int num112 = 0; num112 < Main.maxNPCs; num112++)
{
                            if (Main.npc[num112].CanBeChasedBy(this, false))
{
                                float num113 = Main.npc[num112].position.X + (float)(Main.npc[num112].width / 2);
                                float num114 = Main.npc[num112].position.Y + (float)(Main.npc[num112].height / 2);
                                if (Math.Abs(Main.player[this.owner].position.X + (float)(Main.player[this.owner].width / 2) - num113) + Math.Abs(Main.player[this.owner].position.Y + (float)(Main.player[this.owner].height / 2) - num114) < num110)
{
                                    if (Collision.CanHit(this.position, this.width, this.height, Main.npc[num112].position, Main.npc[num112].width, Main.npc[num112].height))
{
                                        num111 = num112;
                                    }
                                    flag26 = true;
                                    break;
                                }
                            }
                        }
                        if (!flag26)
{
                            num109 -= (float)(40 * this.minionPos * Main.player[this.owner].direction);
                        }
                        if (flag26 && num111 >= 0)
{
                            this.ai[0] = 0f;
                        }
                    }
                    float num115 = Main.player[this.owner].position.Y + (float)(Main.player[this.owner].height / 2) - vector14.Y;
                    if (this.type == 127)
                    {
                        num115 = Main.player[this.owner].position.Y - vector14.Y;
                    }
                    float num116 = (float)Math.Sqrt((double)(num109 * num109 + num115 * num115));
                    float num117 = num116;
                    float num118 = 10f;
                    float num119 = num116;
                    if (this.type == 111)
                    {
                        num118 = 11f;
                    }
                    if (this.type == 127)
                    {
                        num118 = 9f;
                    }
                    if (this.type == 875)
                    {
                        num107 = 1.8f;
                        num118 = 16f;
                    }
                    if (this.type == 324)
                    {
                        num118 = 20f;
                    }
                    if (flag10 || this.type == 816 || this.type == 821 || this.type == 825 || this.type == 854 || this.type == 858 || this.type == 859 || this.type == 860 || this.type == 956 || this.type == 958 || this.type == 959 || this.type == 960 || this.type == 994 || this.type == 998 || this.type == 1003 || this.type == 1004 || this.type == 1027 || this.type == 1095 || this.type == 1096)
                    {
                        num107 = 0.4f;
                        num118 = 12f;
                        if (flag10)
{
                            num107 = 0.8f;
                        }
                        if (num118 < Math.Abs(Main.player[this.owner].velocity.X) + Math.Abs(Main.player[this.owner].velocity.Y))
{
                            num118 = Math.Abs(Main.player[this.owner].velocity.X) + Math.Abs(Main.player[this.owner].velocity.Y);
                        }
                    }
                    if (this.type == 208 && Math.Abs(Main.player[this.owner].velocity.X) + Math.Abs(Main.player[this.owner].velocity.Y) > 4f)
                    {
                        num108 = -1;
                    }
                    if (num116 < (float)num108 && Main.player[this.owner].velocity.Y == 0f && this.position.Y + (float)this.height <= Main.player[this.owner].position.Y + (float)Main.player[this.owner].height && !Collision.SolidCollision(this.position, this.width, this.height))
                    {
                        this.ai[0] = 0f;
                        if (this.velocity.Y < -6f)
{
                            this.velocity.Y = -6f;
                        }
                    }
                    if (num116 < 60f)
                    {
                        num109 = this.velocity.X;
                        num115 = this.velocity.Y;
                    }
                    else
                    {
                        num116 = num118 / num116;
                        num109 *= num116;
                        num115 *= num116;
                    }
                    if (this.type == 324)
                    {
                        if (num119 > 1000f)
{
                            if ((double)(Math.Abs(this.velocity.X) + Math.Abs(this.velocity.Y)) < (double)num118 - 1.25)
{
                                this.velocity *= 1.025f;
                            }
                            if ((double)(Math.Abs(this.velocity.X) + Math.Abs(this.velocity.Y)) > (double)num118 + 1.25)
{
                                this.velocity *= 0.975f;
                            }
                        }
                        else if (num119 > 600f)
{
                            if (Math.Abs(this.velocity.X) + Math.Abs(this.velocity.Y) < num118 - 1f)
{
                                this.velocity *= 1.05f;
                            }
                            if (Math.Abs(this.velocity.X) + Math.Abs(this.velocity.Y) > num118 + 1f)
{
                                this.velocity *= 0.95f;
                            }
                        }
                        else if (num119 > 400f)
{
                            if ((double)(Math.Abs(this.velocity.X) + Math.Abs(this.velocity.Y)) < (double)num118 - 0.5)
{
                                this.velocity *= 1.075f;
                            }
                            if ((double)(Math.Abs(this.velocity.X) + Math.Abs(this.velocity.Y)) > (double)num118 + 0.5)
{
                                this.velocity *= 0.925f;
                            }
                        }
                        else
{
                            if ((double)(Math.Abs(this.velocity.X) + Math.Abs(this.velocity.Y)) < (double)num118 - 0.25)
{
                                this.velocity *= 1.1f;
                            }
                            if ((double)(Math.Abs(this.velocity.X) + Math.Abs(this.velocity.Y)) > (double)num118 + 0.25)
{
                                this.velocity *= 0.9f;
                            }
                        }
                        this.velocity.X = (this.velocity.X * 34f + num109) / 35f;
                        this.velocity.Y = (this.velocity.Y * 34f + num115) / 35f;
                    }
                    else if (this.type == 875)
                    {
                        if (num117 < (float)num108)
{
                            if (this.velocity.X < num109)
{
                                this.velocity.X = this.velocity.X + num107;
                            }
                            else if (this.velocity.X > num109)
{
                                this.velocity.X = this.velocity.X - num107;
                            }
                            if (this.velocity.Y < num115)
{
                                this.velocity.Y = this.velocity.Y + num107;
                            }
                            else if (this.velocity.Y > num115)
{
                                this.velocity.Y = this.velocity.Y - num107;
                            }
                        }
                        else
{
                            this.velocity = Vector2.Lerp(this.velocity, new Vector2(num109, num115), 0.75f);
                        }
                    }
                    else
                    {
                        if (this.velocity.X < num109)
{
                            this.velocity.X = this.velocity.X + num107;
                            if (this.velocity.X < 0f)
{
                                this.velocity.X = this.velocity.X + num107 * 1.5f;
                            }
                        }
                        if (this.velocity.X > num109)
{
                            this.velocity.X = this.velocity.X - num107;
                            if (this.velocity.X > 0f)
{
                                this.velocity.X = this.velocity.X - num107 * 1.5f;
                            }
                        }
                        if (this.velocity.Y < num115)
{
                            this.velocity.Y = this.velocity.Y + num107;
                            if (this.velocity.Y < 0f)
{
                                this.velocity.Y = this.velocity.Y + num107 * 1.5f;
                            }
                        }
                        if (this.velocity.Y > num115)
{
                            this.velocity.Y = this.velocity.Y - num107;
                            if (this.velocity.Y > 0f)
{
                                this.velocity.Y = this.velocity.Y - num107 * 1.5f;
                            }
                        }
                    }
                    if (this.type == 111)
                    {
                        this.frame = 7;
                    }
                    if (flag6 && this.frame < 12)
                    {
                        this.frame = Main.rand.Next(12, 18);
                        this.frameCounter = 0;
                    }
                    if (this.type != 313)
                    {
                        if ((double)this.velocity.X > 0.5)
{
                            this.spriteDirection = -1;
                        }
                        else if ((double)this.velocity.X < -0.5)
{
                            this.spriteDirection = 1;
                        }
                    }
                    if (flag8)
                    {
                        this.frame = 0;
                        this.frameCounter = 0;
                        base.Center = Main.player[this.owner].MountedCenter + new Vector2(0f, -10f);
                        this.position = this.position.Floor();
                        this.rotation = 0f;
                        this.direction = (this.spriteDirection = Main.player[this.owner].direction);
                        this.velocity = new Vector2((float)this.direction, 0f);
                        Player player5 = Main.player[this.owner];
                        if (player5.mount.Active && MountID.Sets.PlayerIsHidden[player5.mount.Type])
{
                            this.alpha = 255;
                        }
                    }
                    else if (this.type == 112)
                    {
                        this.frameCounter++;
                        if (this.frame < 3)
{
                            this.frame = 3;
                            this.frameCounter = 0;
                        }
                        if (this.frameCounter > 3)
{
                            this.frameCounter = 0;
                            this.frame++;
                            if (this.frame >= Main.projFrames[this.type])
{
                                this.frame = 3;
                            }
                        }
                        this.rotation = this.velocity.X * 0.125f;
                    }
                    else if (this.type == 900)
                    {
                        if (this.velocity.X != 0f)
{
                            this.spriteDirection = Math.Sign(this.velocity.X);
                        }
                        this.frameCounter++;
                        if (this.frame < 10)
{
                            this.frame = 10;
                            this.frameCounter = 0;
                        }
                        if (this.frameCounter > 3)
{
                            this.frameCounter = 0;
                            this.frame++;
                            if (this.frame >= Main.projFrames[this.type])
{
                                this.frame = 10;
                            }
                        }
                        this.rotation = this.velocity.X * 0.125f;
                    }
                    else if (this.type == 899)
                    {
                        if (this.velocity.X != 0f)
{
                            this.spriteDirection = Math.Sign(this.velocity.X);
                        }
                        this.frameCounter++;
                        if (this.frame < 10)
{
                            this.frame = 10;
                            this.frameCounter = 0;
                        }
                        if (this.frameCounter > 3)
{
                            this.frameCounter = 0;
                            this.frame++;
                            if (this.frame >= Main.projFrames[this.type])
{
                                this.frame = 10;
                            }
                        }
                        Vector2 vector15 = this.velocity.SafeNormalize(Vector2.UnitX);
                        this.rotation = vector15.ToRotation();
                        if (this.velocity.X < 0f)
{
                            this.rotation += 3.1415927f;
                        }
                    }
                    else if (this.type == 897)
                    {
                        this.spriteDirection = 1;
                        this.frameCounter++;
                        if (this.frame < 8)
{
                            this.frame = 8;
                            this.frameCounter = 0;
                        }
                        if (this.frameCounter > 3)
{
                            this.frameCounter = 0;
                            this.frame++;
                            if (this.frame >= Main.projFrames[this.type])
{
                                this.frame = 8;
                            }
                        }
                        Vector2 vector16 = this.velocity.SafeNormalize(-Vector2.UnitY);
                        this.rotation = vector16.ToRotation() + 1.5707964f;
                    }
                    else if (this.type == 891)
                    {
                        this.spriteDirection = 1;
                        this.frameCounter++;
                        if (this.frame < 9)
{
                            this.frame = 9;
                            this.frameCounter = 0;
                        }
                        if (this.frameCounter > 3)
{
                            this.frameCounter = 0;
                            this.frame++;
                            if (this.frame >= Main.projFrames[this.type])
{
                                this.frame = 9;
                            }
                        }
                        Vector2 vector17 = this.velocity.SafeNormalize(-Vector2.UnitY);
                        this.rotation = vector17.ToRotation() + 1.5707964f;
                    }
                    else if (this.type == 890)
                    {
                        if (this.velocity.X != 0f)
{
                            this.spriteDirection = Math.Sign(this.velocity.X);
                        }
                        this.frameCounter++;
                        if (this.frame < 9)
{
                            this.frame = 9;
                            this.frameCounter = 0;
                        }
                        if (this.frameCounter > 3)
{
                            this.frameCounter = 0;
                            this.frame++;
                            if (this.frame >= Main.projFrames[this.type])
{
                                this.frame = 9;
                            }
                        }
                        this.rotation = this.velocity.X * 0.025f;
                    }
                    else if (this.type == 884)
                    {
                        if (this.velocity.X != 0f)
{
                            this.spriteDirection = Math.Sign(this.velocity.X);
                        }
                        this.frameCounter++;
                        if (this.frame < 9)
{
                            this.frame = 9;
                            this.frameCounter = 0;
                        }
                        if (this.frameCounter > 3)
{
                            this.frameCounter = 0;
                            this.frame++;
                            if (this.frame >= Main.projFrames[this.type])
{
                                this.frame = 9;
                            }
                        }
                        Vector2 vector18 = this.velocity.SafeNormalize(-Vector2.UnitY);
                        this.rotation = vector18.ToRotation() + 1.5707964f;
                    }
                    else if (this.type == 881 || this.type == 934)
                    {
                        int num120 = 1226;
                        if (this.type == 934)
{
                            num120 = 1261;
                        }
                        if (this.frame < 6 || this.frame > 11)
{
                            Gore.NewGore(new Vector2(base.Center.X, this.position.Y), this.velocity * 0.5f, num120, 1f);
                        }
                        this.frameCounter++;
                        if (this.frameCounter > 4)
{
                            this.frame++;
                            this.frameCounter = 0;
                        }
                        if (this.frame < 6 || this.frame > 11)
{
                            this.frame = 6;
                        }
                        Vector2 vector19 = this.velocity.SafeNormalize(-Vector2.UnitY);
                        this.rotation = vector19.ToRotation() + 1.5707964f;
                    }
                    else if (this.type == 875)
                    {
                        num2 = this.frameCounter + 1;
                        this.frameCounter = num2;
                        if (num2 > 4)
{
                            this.frame++;
                            this.frameCounter = 0;
                        }
                        if (this.frame < 7 || this.frame > 10)
{
                            this.frame = 7;
                        }
                        Vector2 vector20 = this.velocity.SafeNormalize(-Vector2.UnitX * (float)this.spriteDirection);
                        this.rotation = vector20.ToRotation() + ((this.spriteDirection == -1) ? 0f : 3.1415927f);
                    }
                    else if (this.type == 825)
                    {
                        num2 = this.frameCounter + 1;
                        this.frameCounter = num2;
                        if (num2 > 4)
{
                            this.frame++;
                            this.frameCounter = 0;
                        }
                        if (this.frame < 21 || this.frame > 25)
{
                            this.frame = 21;
                        }
                        this.rotation = this.velocity.X * 0.025f;
                    }
                    else if (this.type == 854)
                    {
                        if (this.frame < 13)
{
                            Gore.NewGore(new Vector2(base.Center.X, this.position.Y), this.velocity * 0.5f, 1269, 1f);
                        }
                        num2 = this.frameCounter + 1;
                        this.frameCounter = num2;
                        if (num2 > 4)
{
                            this.frame++;
                            this.frameCounter = 0;
                        }
                        if (this.frame < 13 || this.frame > 18)
{
                            this.frame = 13;
                        }
                        Vector2 vector21 = this.velocity.SafeNormalize(-Vector2.UnitY);
                        this.rotation = vector21.ToRotation() + 1.5707964f;
                    }
                    else if (this.type == 858)
                    {
                        num2 = this.frameCounter + 1;
                        this.frameCounter = num2;
                        if (num2 > 4)
{
                            this.frame++;
                            this.frameCounter = 0;
                        }
                        if (this.frame < 10 || this.frame > 13)
{
                            this.frame = 10;
                        }
                        Vector2 vector22 = this.velocity.SafeNormalize(-Vector2.UnitX * (float)this.spriteDirection);
                        this.rotation = vector22.ToRotation() + ((this.spriteDirection == -1) ? 0f : 3.1415927f);
                    }
                    else if (this.type == 859)
                    {
                        num2 = this.frameCounter + 1;
                        this.frameCounter = num2;
                        if (num2 > 4)
{
                            this.frame++;
                            this.frameCounter = 0;
                        }
                        if (this.frame < 18 || this.frame > 23)
{
                            this.frame = 18;
                        }
                        this.rotation = this.velocity.X * 0.025f;
                    }
                    else if (this.type == 860)
                    {
                        if (this.frame < 6)
{
                            this.frame = 8;
                            this.frameCounter = 0;
                        }
                        num2 = this.frameCounter + 1;
                        this.frameCounter = num2;
                        if (num2 > 4)
{
                            this.frame++;
                            this.frameCounter = 0;
                        }
                        if (this.frame > 13)
{
                            this.frame = 6;
                        }
                        Vector2 vector23 = this.velocity.SafeNormalize(-Vector2.UnitY);
                        this.rotation = vector23.ToRotation() + 1.5707964f;
                    }
                    else if (this.type == 816)
                    {
                        num2 = this.frameCounter + 1;
                        this.frameCounter = num2;
                        if (num2 > 4)
{
                            this.frame++;
                            this.frameCounter = 0;
                        }
                        if (this.frame < 11 || this.frame > 16)
{
                            this.frame = 11;
                        }
                        this.rotation = this.velocity.X * 0.025f;
                    }
                    else if (this.type == 821)
                    {
                        num2 = this.frameCounter + 1;
                        this.frameCounter = num2;
                        if (num2 > 4)
{
                            this.frame++;
                            this.frameCounter = 0;
                        }
                        if (this.frame < 19 || this.frame > 22)
{
                            this.frame = 19;
                        }
                        this.rotation = this.velocity.X * 0.025f;
                    }
                    else if (this.type == 958)
                    {
                        if (this.velocity.X != 0f)
{
                            this.spriteDirection = Math.Sign(this.velocity.X);
                        }
                        if (this.frame < 13)
{
                            this.frame = 13;
                            this.frameCounter = 0;
                        }
                        num2 = this.frameCounter + 1;
                        this.frameCounter = num2;
                        if (num2 > 4)
{
                            this.frame++;
                            this.frameCounter = 0;
                        }
                        if (this.frame > 16)
{
                            this.frame = 13;
                        }
                        this.rotation = MathHelper.Clamp(this.velocity.X * 0.025f, -0.4f, 0.4f);
                    }
                    else if (this.type == 960)
                    {
                        if (this.velocity.X != 0f)
{
                            this.spriteDirection = Math.Sign(this.velocity.X);
                        }
                        this.frame = 4;
                        this.frameCounter = 0;
                        Vector2 vector24 = this.velocity.SafeNormalize(-Vector2.UnitY);
                        this.rotation = vector24.ToRotation() + 1.5707964f;
                    }
                    else if (this.type == 959)
                    {
                        if (this.velocity.X != 0f)
{
                            this.spriteDirection = Math.Sign(this.velocity.X);
                        }
                        this.frame = 11;
                        this.frameCounter = 0;
                        this.rotation = MathHelper.Clamp(this.velocity.X * 0.025f, -0.4f, 0.4f);
                        float num121 = Vector2.Dot(this.velocity.SafeNormalize(Vector2.UnitX), new Vector2(0f, -1f));
                        if (num121 > 0f && Main.rand.NextFloat() < 0.3f + num121 * 0.3f)
{
                            Dust dust4 = Dust.NewDustDirect(this.position, this.width, this.height, 16, this.velocity.X * 0.7f, this.velocity.Y * 1.2f, 150, default(Color), 0.6f);
                            dust4.noGravity = true;
                            dust4.fadeIn = 1f;
                            dust4.velocity.X = this.velocity.X * 0.3f;
                            dust4.position = base.Top + new Vector2(0f, -10f) + new Vector2(Main.rand.NextFloatDirection() * 30f, Main.rand.NextFloatDirection() * 10f);
                            dust4.velocity *= 0.7f;
                            dust4.position += dust4.velocity * 2f;
                        }
                    }
                    else if (this.type == 1095 || this.type == 1096)
                    {
                        if (this.velocity.X != 0f)
{
                            this.spriteDirection = Math.Sign(this.velocity.X);
                        }
                        this.frame = 11;
                        this.frameCounter = 0;
                        this.rotation = MathHelper.Clamp(this.velocity.X * 0.025f, -0.4f, 0.4f);
                        float num122 = Vector2.Dot(this.velocity.SafeNormalize(Vector2.UnitX), new Vector2(0f, -1f));
                        if (num122 > 0f && Main.rand.NextFloat() < 0.3f + num122 * 0.3f)
{
                            Dust dust5 = Dust.NewDustDirect(this.position, this.width, this.height, 16, this.velocity.X * 0.7f, this.velocity.Y * 1.2f, 150, default(Color), 0.6f);
                            dust5.noGravity = true;
                            dust5.fadeIn = 1f;
                            dust5.velocity.X = this.velocity.X * 0.3f;
                            dust5.position = base.Top + new Vector2(0f, -10f) + new Vector2(Main.rand.NextFloatDirection() * 30f, Main.rand.NextFloatDirection() * 10f);
                            dust5.velocity *= 0.7f;
                            dust5.position += dust5.velocity * 2f;
                        }
                    }
                    else if (this.type == 994)
                    {
                        if (this.velocity.X != 0f)
{
                            this.spriteDirection = Math.Sign(this.velocity.X);
                        }
                        this.frameCounter++;
                        if (this.frameCounter > 5)
{
                            this.frame++;
                            this.frameCounter = 0;
                        }
                        if (this.frame < 13 || this.frame > 15)
{
                            this.frame = 13;
                        }
                        this.rotation = MathHelper.Clamp(this.velocity.X * 0.025f, -0.4f, 0.4f);
                    }
                    else if (this.type == 998)
                    {
                        if (this.velocity.X != 0f)
{
                            this.spriteDirection = -Math.Sign(this.velocity.X);
                        }
                        this.frameCounter++;
                        if (this.frameCounter > 4)
{
                            this.frame++;
                            this.frameCounter = 0;
                        }
                        if (this.frame < 6 || this.frame > 9)
{
                            this.frame = 6;
                        }
                        this.rotation = MathHelper.Clamp(this.velocity.X * 0.025f, -0.4f, 0.4f);
                    }
                    else if (this.type == 1003)
                    {
                        if (this.velocity.X != 0f)
{
                            this.spriteDirection = -Math.Sign(this.velocity.X);
                        }
                        this.frameCounter++;
                        if (this.frameCounter > 3)
{
                            this.frame++;
                            this.frameCounter = 0;
                        }
                        if (this.frame < 12 || this.frame > 15)
{
                            this.frame = 12;
                        }
                        this.rotation = MathHelper.Clamp(this.velocity.X * 0.025f, -0.35f, 0.35f);
                    }
                    else if (this.type == 1004)
                    {
                        if (this.velocity.X != 0f)
{
                            this.spriteDirection = -Math.Sign(this.velocity.X);
                        }
                        this.frameCounter++;
                        if (this.frameCounter > 3)
{
                            this.frame++;
                            this.frameCounter = 0;
                        }
                        if (this.frame < 10 || this.frame > 14)
{
                            this.frame = 10;
                        }
                        this.rotation = MathHelper.Clamp(this.velocity.X * 0.025f, -0.35f, 0.35f);
                    }
                    else if (this.type == 112)
                    {
                        if (this.spriteDirection == -1)
{
                            this.rotation = (float)Math.Atan2((double)this.velocity.Y, (double)this.velocity.X) + 1.57f;
                        }
                        else
{
                            this.rotation = (float)Math.Atan2((double)this.velocity.Y, (double)this.velocity.X) + 1.57f;
                        }
                    }
                    else if (flag7)
                    {
                        int num123 = (int)(base.Center.X / 16f);
                        int num124 = (int)(base.Center.Y / 16f);
                        if (Main.tile[num123, num124] != null && Main.tile[num123, num124].wall > 0)
{
                            this.rotation = this.velocity.ToRotation() + 1.5707964f;
                            this.frameCounter += (int)(Math.Abs(this.velocity.X) + Math.Abs(this.velocity.Y));
                            if (this.frameCounter > 5)
{
                                this.frame++;
                                this.frameCounter = 0;
                            }
                            if (this.frame > 7)
{
                                this.frame = 4;
                            }
                            if (this.frame < 4)
{
                                this.frame = 7;
                            }
                        }
                        else
{
                            this.frameCounter++;
                            if (this.frameCounter > 2)
{
                                this.frame++;
                                this.frameCounter = 0;
                            }
                            if (this.frame < 8 || this.frame > 10)
{
                                this.frame = 8;
                            }
                            this.rotation = this.velocity.X * 0.1f;
                        }
                    }
                    else if (this.type == 334)
                    {
                        this.frameCounter++;
                        if (this.frameCounter > 1)
{
                            this.frame++;
                            this.frameCounter = 0;
                        }
                        if (this.frame < 7 || this.frame > 10)
{
                            this.frame = 7;
                        }
                        this.rotation = this.velocity.X * 0.1f;
                    }
                    else if (this.type == 353)
                    {
                        this.frameCounter++;
                        if (this.frameCounter > 6)
{
                            this.frame++;
                            this.frameCounter = 0;
                        }
                        if (this.frame < 10 || this.frame > 13)
{
                            this.frame = 10;
                        }
                        this.rotation = this.velocity.X * 0.05f;
                    }
                    else if (this.type == 127)
                    {
                        this.frameCounter += 3;
                        if (this.frameCounter > 6)
{
                            this.frame++;
                            this.frameCounter = 0;
                        }
                        if (this.frame <= 5 || this.frame > 15)
{
                            this.frame = 6;
                        }
                        this.rotation = this.velocity.X * 0.1f;
                    }
                    else if (this.type == 269)
                    {
                        if (this.frame == 6)
{
                            this.frameCounter = 0;
                        }
                        else if (this.frame < 4 || this.frame > 6)
{
                            this.frameCounter = 0;
                            this.frame = 4;
                        }
                        else
{
                            this.frameCounter++;
                            if (this.frameCounter > 6)
{
                                this.frame++;
                                this.frameCounter = 0;
                            }
                        }
                        this.rotation = this.velocity.X * 0.05f;
                    }
                    else if (this.type == 266)
                    {
                        this.frameCounter++;
                        if (this.frameCounter > 5)
{
                            this.frame++;
                            this.frameCounter = 0;
                        }
                        if (this.frame < 8 || this.frame >= Main.projFrames[266])
{
                            this.frame = 8;
                        }
                        this.rotation = this.velocity.X * 0.1f;
                    }
                    else if (this.type == 324)
                    {
                        this.frameCounter++;
                        if (this.frameCounter > 1)
{
                            this.frame++;
                            this.frameCounter = 0;
                        }
                        if (this.frame < 6 || this.frame > 9)
{
                            this.frame = 6;
                        }
                        this.rotation = (float)Math.Atan2((double)this.velocity.Y, (double)this.velocity.X) + 1.58f;
                        Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 0.9f, 0.6f, 0.2f);
                        for (int num125 = 0; num125 < 2; num125++)
{
                            int num126 = 4;
                            int num127 = Dust.NewDust(new Vector2(base.Center.X - (float)num126, base.Center.Y - (float)num126) - this.velocity * 0f, num126 * 2, num126 * 2, 6, 0f, 0f, 100, default(Color), 1f);
                            Main.dust[num127].scale *= 1.8f + (float)Main.rand.Next(10) * 0.1f;
                            Main.dust[num127].velocity *= 0.2f;
                            if (num125 == 1)
{
                                Main.dust[num127].position -= this.velocity * 0.5f;
                            }
                            Main.dust[num127].noGravity = true;
                            num127 = Dust.NewDust(new Vector2(base.Center.X - (float)num126, base.Center.Y - (float)num126) - this.velocity * 0f, num126 * 2, num126 * 2, 31, 0f, 0f, 100, default(Color), 0.5f);
                            Main.dust[num127].fadeIn = 1f + (float)Main.rand.Next(5) * 0.1f;
                            Main.dust[num127].velocity *= 0.05f;
                            if (num125 == 1)
{
                                Main.dust[num127].position -= this.velocity * 0.5f;
                            }
                        }
                    }
                    else if (this.type == 268)
                    {
                        this.frameCounter++;
                        if (this.frameCounter > 4)
{
                            this.frame++;
                            this.frameCounter = 0;
                        }
                        if (this.frame < 6 || this.frame > 7)
{
                            this.frame = 6;
                        }
                        this.rotation = (float)Math.Atan2((double)this.velocity.Y, (double)this.velocity.X) + 1.58f;
                    }
                    else if (this.type == 200)
                    {
                        this.frameCounter += 3;
                        if (this.frameCounter > 6)
{
                            this.frame++;
                            this.frameCounter = 0;
                        }
                        if (this.frame <= 5 || this.frame > 9)
{
                            this.frame = 6;
                        }
                        this.rotation = this.velocity.X * 0.1f;
                    }
                    else if (this.type == 208)
                    {
                        this.rotation = this.velocity.X * 0.075f;
                        this.frameCounter++;
                        if (this.frameCounter > 6)
{
                            this.frame++;
                            this.frameCounter = 0;
                        }
                        if (this.frame > 4)
{
                            this.frame = 1;
                        }
                        if (this.frame < 1)
{
                            this.frame = 1;
                        }
                    }
                    else if (this.type == 236)
                    {
                        this.rotation = this.velocity.Y * 0.05f * (float)this.direction;
                        if (this.velocity.Y < 0f)
{
                            this.frameCounter += 2;
                        }
                        else
{
                            this.frameCounter++;
                        }
                        if (this.frameCounter >= 6)
{
                            this.frame++;
                            this.frameCounter = 0;
                        }
                        if (this.frame > 12)
{
                            this.frame = 9;
                        }
                        if (this.frame < 9)
{
                            this.frame = 9;
                        }
                    }
                    else if (this.type == 499)
                    {
                        this.rotation = this.velocity.Y * 0.05f * (float)this.direction;
                        if (this.velocity.Y < 0f)
{
                            this.frameCounter += 2;
                        }
                        else
{
                            this.frameCounter++;
                        }
                        if (this.frameCounter >= 6)
{
                            this.frame++;
                            this.frameCounter = 0;
                        }
                        if (this.frame >= 12)
{
                            this.frame = 8;
                        }
                        if (this.frame < 8)
{
                            this.frame = 8;
                        }
                    }
                    else if (this.type == 765)
                    {
                        this.rotation = this.velocity.Y * 0.05f * (float)this.direction;
                        this.frameCounter++;
                        if (this.frameCounter >= 8)
{
                            this.frame++;
                            this.frameCounter = 0;
                        }
                        if (this.frame >= 10)
{
                            this.frame = 8;
                        }
                        if (this.frame < 6)
{
                            this.frame = 6;
                        }
                    }
                    else if (this.type == 314)
                    {
                        this.rotation = (float)Math.Atan2((double)this.velocity.Y, (double)this.velocity.X) + 1.58f;
                        this.frameCounter++;
                        if (this.frameCounter >= 3)
{
                            this.frame++;
                            this.frameCounter = 0;
                        }
                        if (this.frame > 12)
{
                            this.frame = 7;
                        }
                        if (this.frame < 7)
{
                            this.frame = 7;
                        }
                    }
                    else if (this.type == 319)
                    {
                        this.rotation = this.velocity.X * 0.05f;
                        this.frameCounter++;
                        if (this.frameCounter >= 6)
{
                            this.frame++;
                            this.frameCounter = 0;
                        }
                        if (this.frame > 10)
{
                            this.frame = 6;
                        }
                        if (this.frame < 6)
{
                            this.frame = 6;
                        }
                    }
                    else if (this.type == 210)
                    {
                        this.rotation = (float)Math.Atan2((double)this.velocity.Y, (double)this.velocity.X) + 1.58f;
                        this.frameCounter += 3;
                        if (this.frameCounter > 6)
{
                            this.frame++;
                            this.frameCounter = 0;
                        }
                        if (this.frame > 11)
{
                            this.frame = 7;
                        }
                        if (this.frame < 7)
{
                            this.frame = 7;
                        }
                    }
                    else if (this.type == 313)
                    {
                        this.position.Y = this.position.Y + (float)this.height;
                        this.height = 54;
                        this.position.Y = this.position.Y - (float)this.height;
                        this.position.X = this.position.X + (float)(this.width / 2);
                        this.width = 54;
                        this.position.X = this.position.X - (float)(this.width / 2);
                        this.rotation += this.velocity.X * 0.01f;
                        this.frameCounter = 0;
                        this.frame = 11;
                    }
                    else if (this.type == 398)
                    {
                        if ((double)this.velocity.X > 0.5)
{
                            this.spriteDirection = 1;
                        }
                        else if ((double)this.velocity.X < -0.5)
{
                            this.spriteDirection = -1;
                        }
                        this.frameCounter++;
                        if (this.frameCounter > 4)
{
                            this.frame++;
                            this.frameCounter = 0;
                        }
                        if (this.frame < 7 || this.frame > 10)
{
                            this.frame = 7;
                        }
                    }
                    else if (this.spriteDirection == -1)
                    {
                        this.rotation = (float)Math.Atan2((double)this.velocity.Y, (double)this.velocity.X);
                    }
                    else
                    {
                        this.rotation = (float)Math.Atan2((double)this.velocity.Y, (double)this.velocity.X) + 3.14f;
                    }
                    if (!flag10 && this.type != 499 && this.type != 765 && this.type != 816 && this.type != 821 && this.type != 825 && this.type != 859 && this.type != 881 && this.type != 884 && this.type != 890 && this.type != 891 && this.type != 900 && this.type != 934 && this.type != 958 && this.type != 959 && this.type != 960 && this.type != 994 && this.type != 998 && this.type != 1003 && this.type != 1004 && this.type != 1027 && this.type != 1095 && this.type != 1096)
                    {
                        if (this.type == 899)
{
                            int num128 = 6;
                            if (Main.rand.Next(4) == 0)
{
                                num128 = 31;
                            }
                            int num129 = Dust.NewDust(base.Center + new Vector2(-8f, 0f) - this.velocity * 0.25f, 15, 15, num128, -this.velocity.X * 0.5f, this.velocity.Y * 0.5f, 0, default(Color), 1.3f);
                            Main.dust[num129].velocity.X = Main.dust[num129].velocity.X * 0.2f;
                            Main.dust[num129].velocity.Y = Main.dust[num129].velocity.Y * 0.2f - 0.2f;
                            Main.dust[num129].noGravity = true;
                        }
                        else if (this.type == 897)
{
                            int num130 = 6;
                            if (Main.rand.Next(4) == 0)
{
                                num130 = 31;
                            }
                            int num131 = Dust.NewDust(base.Center + new Vector2(-8f, -8f) - this.velocity * 0.25f, 15, 15, num130, -this.velocity.X * 0.5f, this.velocity.Y * 0.5f, 0, default(Color), 1.3f);
                            Main.dust[num131].velocity.X = Main.dust[num131].velocity.X * 0.2f;
                            Main.dust[num131].velocity.Y = Main.dust[num131].velocity.Y * 0.2f - 0.2f;
                            Main.dust[num131].noGravity = true;
                        }
                        else if (this.type == 875)
{
                            if (Main.rand.Next(3) == 0)
{
                                Gore.NewGorePerfect(base.Center + new Vector2(-10f + (float)Main.rand.Next(-20, 20) * 0.5f, -10f + (float)Main.rand.Next(-20, 20) * 0.5f), this.velocity * 0.1f, 1225, 0.5f + Main.rand.NextFloat() * 1f);
                                Vector2 vector25 = Main.rand.NextVector2CircularEdge(2f, 2f) + this.velocity * -0.5f;
                                vector25 *= 0.5f;
                                int num132 = Dust.NewDust(base.Center - this.velocity * 1.5f - new Vector2(7f, 7f), 15, 15, 226, vector25.X, vector25.Y, 0, default(Color), 0.65f);
                                Main.dust[num132].noGravity = true;
                            }
                        }
                        else if (this.type == 860)
{
                            int num133 = Dust.NewDust(new Vector2(this.position.X + (float)(this.width / 2) - 4f, this.position.Y + (float)(this.height / 2) - 4f) + this.velocity, 8, 8, 27, -this.velocity.X * 0.5f, this.velocity.Y * 0.5f, 0, default(Color), 1f);
                            Main.dust[num133].velocity.X = Main.dust[num133].velocity.X * 0.2f;
                            Main.dust[num133].velocity.Y = Main.dust[num133].velocity.Y * 0.2f - 0.2f;
                            Main.dust[num133].velocity += new Vector2((float)Main.rand.Next(-10, 10) * 0.4f, (float)Main.rand.Next(-10, 10) * 0.4f) * 0.5f;
                            Main.dust[num133].noGravity = true;
                        }
                        else if (this.type == 858)
{
                            int num134 = 6;
                            if (Main.rand.Next(4) == 0)
{
                                num134 = 31;
                            }
                            int num135 = Dust.NewDust(new Vector2(this.position.X + (float)(this.width / 2) - 4f, this.position.Y + (float)(this.height / 2) - 4f) - this.velocity, 10, 10, num134, -this.velocity.X * 0.5f, this.velocity.Y * 0.5f, 0, default(Color), 1.3f);
                            Main.dust[num135].velocity.X = Main.dust[num135].velocity.X * 0.2f;
                            Main.dust[num135].velocity.Y = Main.dust[num135].velocity.Y * 0.2f - 0.2f;
                            Main.dust[num135].noGravity = true;
                        }
                        else if (this.type == 112)
{
                            int num136 = 6;
                            if (Main.rand.Next(4) == 0)
{
                                num136 = 31;
                            }
                            int num137 = Dust.NewDust(base.Center + new Vector2((float)(12 * this.spriteDirection), 4f).RotatedBy((double)this.rotation, default(Vector2)) + new Vector2(-5f, -5f), 10, 10, num136, -this.velocity.X * 0.5f, this.velocity.Y * 0.5f, 0, default(Color), 1.3f);
                            Main.dust[num137].velocity.X = Main.dust[num137].velocity.X * 0.2f;
                            Main.dust[num137].velocity.Y = Main.dust[num137].velocity.Y * 0.2f - 0.2f;
                            Main.dust[num137].noGravity = true;
                        }
                        else if (this.type == 854)
{
                            if (Main.rand.Next(6) == 0)
{
                                Vector2 vector26 = base.Center / 16f;
                                int num138 = (int)vector26.X;
                                int num139 = (int)vector26.Y;
                                Tile tileSafely = Framing.GetTileSafely(num138, num139 + 1);
                                if (!WorldGen.SolidTile(tileSafely) && tileSafely.liquid == 0)
{
                                    Gore gore = Gore.NewGorePerfect(base.Center + new Vector2((float)Main.rand.Next(-30, 30) * 0.5f, (float)Main.rand.Next(-30, 30) * 0.5f), this.velocity * -0.2f, 910, 1f);
                                    gore.Frame.CurrentColumn = 0;
                                    gore.timeLeft = 1;
                                }
                            }
                        }
                        else if (this.type != 398 && this.type != 390 && this.type != 391 && this.type != 392 && this.type != 127 && this.type != 200 && this.type != 208 && this.type != 210 && this.type != 236 && this.type != 266 && this.type != 268 && this.type != 269 && this.type != 313 && this.type != 314 && this.type != 319 && this.type != 324 && this.type != 334 && this.type != 353)
{
                            int num140 = Dust.NewDust(new Vector2(this.position.X + (float)(this.width / 2) - 4f, this.position.Y + (float)(this.height / 2) - 4f) - this.velocity, 8, 8, 16, -this.velocity.X * 0.5f, this.velocity.Y * 0.5f, 50, default(Color), 1.7f);
                            Main.dust[num140].velocity.X = Main.dust[num140].velocity.X * 0.2f;
                            Main.dust[num140].velocity.Y = Main.dust[num140].velocity.Y * 0.2f;
                            Main.dust[num140].noGravity = true;
                        }
                    }
                }
                else
                {
                    if (flag10)
                    {
                        float num141 = (float)(40 * this.minionPos);
                        int num142 = 30;
                        int num143 = 60;
                        if (flag8)
{
                            num142 = 42;
                        }
                        this.localAI[0] -= 1f;
                        if (this.localAI[0] < 0f)
{
                            this.localAI[0] = 0f;
                        }
                        bool flag27 = false;
                        if (flag8)
{
                            flag27 = true;
                        }
                        if (flag27 && this.ai[1] > 0f)
{
                            this.ai[1] -= 1f;
                        }
                        bool flag28 = this.ai[1] <= 0f;
                        if (flag8 && (this.alpha > 0 || this.localAI[0] > 0f))
{
                            flag28 = false;
                        }
                        if (!flag27 && this.ai[1] > 0f)
{
                            this.ai[1] -= 1f;
                        }
                        if (flag28)
{
                            float num144 = this.position.X;
                            float num145 = this.position.Y;
                            float num146 = 100000f;
                            float num147 = num146;
                            int num148 = -1;
                            float num149 = 20f;
                            NPC ownerMinionAttackTargetNPC = this.OwnerMinionAttackTargetNPC;
                            if (ownerMinionAttackTargetNPC != null && ownerMinionAttackTargetNPC.CanBeChasedBy(this, false))
{
                                float num150 = ownerMinionAttackTargetNPC.position.X + (float)(ownerMinionAttackTargetNPC.width / 2);
                                float num151 = ownerMinionAttackTargetNPC.position.Y + (float)(ownerMinionAttackTargetNPC.height / 2);
                                float num152 = Math.Abs(this.position.X + (float)(this.width / 2) - num150) + Math.Abs(this.position.Y + (float)(this.height / 2) - num151);
                                if (num152 < num146)
{
                                    if (num148 == -1 && num152 <= num147)
{
                                        num147 = num152;
                                        num144 = num150;
                                        num145 = num151;
                                    }
                                    if (Collision.CanHit(this.position, this.width, this.height, ownerMinionAttackTargetNPC.position, ownerMinionAttackTargetNPC.width, ownerMinionAttackTargetNPC.height))
{
                                        num146 = num152;
                                        num144 = num150;
                                        num145 = num151;
                                        num148 = ownerMinionAttackTargetNPC.whoAmI;
                                    }
                                }
                            }
                            if (num148 == -1)
{
                                for (int num153 = 0; num153 < Main.maxNPCs; num153++)
{
                                    if (Main.npc[num153].CanBeChasedBy(this, false))
{
                                        float num154 = Main.npc[num153].position.X + (float)(Main.npc[num153].width / 2);
                                        float num155 = Main.npc[num153].position.Y + (float)(Main.npc[num153].height / 2);
                                        float num156 = Math.Abs(this.position.X + (float)(this.width / 2) - num154) + Math.Abs(this.position.Y + (float)(this.height / 2) - num155);
                                        if (num156 < num146)
{
                                            if (num148 == -1 && num156 <= num147)
{
                                                num147 = num156;
                                                num144 = num154 + Main.npc[num153].velocity.X * num149;
                                                num145 = num155 + Main.npc[num153].velocity.Y * num149;
                                            }
                                            if (Collision.CanHit(this.position, this.width, this.height, Main.npc[num153].position, Main.npc[num153].width, Main.npc[num153].height))
{
                                                num146 = num156;
                                                num144 = num154 + Main.npc[num153].velocity.X * num149;
                                                num145 = num155 + Main.npc[num153].velocity.Y * num149;
                                                num148 = num153;
                                            }
                                        }
                                    }
                                }
                            }
                            if (num148 == -1 && num147 < num146)
{
                                num146 = num147;
                            }
                            if (num148 != -1)
{
                                flag9 = false;
                            }
                            float num157 = 400f;
                            if ((double)this.position.Y > Main.worldSurface * 16.0)
{
                                num157 = 200f;
                            }
                            if (num146 < num157 + num141 && num148 == -1)
{
                                float num158 = num144 - (this.position.X + (float)(this.width / 2));
                                if (num158 < -5f)
{
                                    flag2 = true;
                                    flag3 = false;
                                }
                                else if (num158 > 5f)
{
                                    flag3 = true;
                                    flag2 = false;
                                }
                            }
                            else if (num148 >= 0 && num146 < 800f + num141)
{
                                this.localAI[0] = (float)num143;
                                float num159 = num144 - (this.position.X + (float)(this.width / 2));
                                if (num159 > 450f || num159 < -450f)
{
                                    if (num159 < -50f)
{
                                        flag2 = true;
                                        flag3 = false;
                                    }
                                    else if (num159 > 50f)
{
                                        flag3 = true;
                                        flag2 = false;
                                    }
                                }
                                else if (this.owner == Main.myPlayer)
{
                                    this.ai[1] = (float)num142;
                                    float num160 = 11f;
                                    Vector2 vector27 = new Vector2(this.position.X + (float)this.width * 0.5f, this.position.Y + (float)(this.height / 2) - 8f);
                                    float num161 = num144 - vector27.X + (float)Main.rand.Next(-20, 21);
                                    float num162 = Math.Abs(num161) * 0.1f;
                                    num162 = num162 * (float)Main.rand.Next(0, 100) * 0.001f;
                                    int num163 = 20;
                                    if (flag8)
{
                                        num163 = 0;
                                    }
                                    float num164 = num145 - vector27.Y + (float)Main.rand.Next(-num163, num163 + 1) - num162;
                                    float num165 = (float)Math.Sqrt((double)(num161 * num161 + num164 * num164));
                                    num165 = num160 / num165;
                                    num161 *= num165;
                                    num164 *= num165;
                                    int num166 = this.damage;
                                    short num167 = 195;
                                    if (flag8)
{
                                        if (num161 < 0f)
{
                                            this.direction = -1;
                                        }
                                        if (num161 > 0f)
{
                                            this.direction = 1;
                                        }
                                        vector27.Y -= 2f;
                                        num167 = 1097;
                                        vector27 += new Vector2(num161, num164) * 1f;
                                        this.localAI[0] = (float)num142;
                                    }
                                    int num168 = Projectile.NewProjectile(this.GetProjectileSource_FromThis(), vector27.X, vector27.Y, num161, num164, (int)num167, num166, this.knockBack, Main.myPlayer, 0f, 0f, 0f, null);
                                    Main.projectile[num168].timeLeft = 300;
                                    if (num161 < 0f)
{
                                        this.direction = -1;
                                    }
                                    if (num161 > 0f)
{
                                        this.direction = 1;
                                    }
                                    this.netUpdate = true;
                                }
                            }
                        }
                    }
                    bool flag29 = false;
                    Vector2 vector28 = Vector2.Zero;
                    bool flag30 = false;
                    if (this.type == 266 || flag7)
                    {
                        float num169 = (float)(40 * this.minionPos);
                        int num170 = 60;
                        this.localAI[0] -= 1f;
                        if (this.localAI[0] < 0f)
{
                            this.localAI[0] = 0f;
                        }
                        if (this.ai[1] > 0f)
{
                            this.ai[1] -= 1f;
                        }
                        else
{
                            float num171 = this.position.X;
                            float num172 = this.position.Y;
                            float num173 = 100000f;
                            float num174 = num173;
                            int num175 = -1;
                            NPC ownerMinionAttackTargetNPC2 = this.OwnerMinionAttackTargetNPC;
                            if (ownerMinionAttackTargetNPC2 != null && ownerMinionAttackTargetNPC2.CanBeChasedBy(this, false))
{
                                float x = ownerMinionAttackTargetNPC2.Center.X;
                                float y = ownerMinionAttackTargetNPC2.Center.Y;
                                float num176 = Math.Abs(this.position.X + (float)(this.width / 2) - x) + Math.Abs(this.position.Y + (float)(this.height / 2) - y);
                                if (num176 < num173)
{
                                    if (num175 == -1 && num176 <= num174)
{
                                        num174 = num176;
                                        num171 = x;
                                        num172 = y;
                                    }
                                    if (Collision.CanHit(this.position, this.width, this.height, ownerMinionAttackTargetNPC2.position, ownerMinionAttackTargetNPC2.width, ownerMinionAttackTargetNPC2.height))
{
                                        num173 = num176;
                                        num171 = x;
                                        num172 = y;
                                        num175 = ownerMinionAttackTargetNPC2.whoAmI;
                                    }
                                }
                            }
                            if (num175 == -1)
{
                                for (int num177 = 0; num177 < Main.maxNPCs; num177++)
{
                                    if (Main.npc[num177].CanBeChasedBy(this, false))
{
                                        float num178 = Main.npc[num177].position.X + (float)(Main.npc[num177].width / 2);
                                        float num179 = Main.npc[num177].position.Y + (float)(Main.npc[num177].height / 2);
                                        float num180 = Math.Abs(this.position.X + (float)(this.width / 2) - num178) + Math.Abs(this.position.Y + (float)(this.height / 2) - num179);
                                        if (num180 < num173)
{
                                            if (num175 == -1 && num180 <= num174)
{
                                                num174 = num180;
                                                num171 = num178;
                                                num172 = num179;
                                            }
                                            if (Collision.CanHit(this.position, this.width, this.height, Main.npc[num177].position, Main.npc[num177].width, Main.npc[num177].height))
{
                                                num173 = num180;
                                                num171 = num178;
                                                num172 = num179;
                                                num175 = num177;
                                            }
                                        }
                                    }
                                }
                            }
                            if (flag7 && !Collision.SolidCollision(this.position, this.width, this.height))
{
                                this.tileCollide = true;
                            }
                            if (num175 == -1 && num174 < num173)
{
                                num173 = num174;
                            }
                            else if (num175 >= 0)
{
                                flag29 = true;
                                vector28 = new Vector2(num171, num172) - base.Center;
                                if (flag7)
{
                                    if (Main.npc[num175].position.Y > this.position.Y + (float)this.height)
{
                                        int num181 = (int)(base.Center.X / 16f);
                                        int num182 = (int)((this.position.Y + (float)this.height + 1f) / 16f);
                                        if (Main.tile[num181, num182] != null && Main.tile[num181, num182].active() && TileID.Sets.Platforms[(int)Main.tile[num181, num182].type])
{
                                            this.tileCollide = false;
                                        }
                                    }
                                    Rectangle rectangle = new Rectangle((int)this.position.X, (int)this.position.Y, this.width, this.height);
                                    Rectangle rectangle2 = new Rectangle((int)Main.npc[num175].position.X, (int)Main.npc[num175].position.Y, Main.npc[num175].width, Main.npc[num175].height);
                                    int num183 = 10;
                                    rectangle2.X -= num183;
                                    rectangle2.Y -= num183;
                                    rectangle2.Width += num183 * 2;
                                    rectangle2.Height += num183 * 2;
                                    if (rectangle.Intersects(rectangle2))
{
                                        flag30 = true;
                                        Vector2 vector29 = Main.npc[num175].Center - base.Center;
                                        if (this.velocity.Y > 0f && vector29.Y < 0f)
{
                                            this.velocity.Y = this.velocity.Y * 0.5f;
                                        }
                                        if (this.velocity.Y < 0f && vector29.Y > 0f)
{
                                            this.velocity.Y = this.velocity.Y * 0.5f;
                                        }
                                        if (this.velocity.X > 0f && vector29.X < 0f)
{
                                            this.velocity.X = this.velocity.X * 0.5f;
                                        }
                                        if (this.velocity.X < 0f && vector29.X > 0f)
{
                                            this.velocity.X = this.velocity.X * 0.5f;
                                        }
                                        if (vector29.Length() > 14f)
{
                                            vector29.Normalize();
                                            vector29 *= 14f;
                                        }
                                        this.rotation = (this.rotation * 5f + vector29.ToRotation() + 1.5707964f) / 6f;
                                        this.velocity = (this.velocity * 9f + vector29) / 10f;
                                        for (int num184 = 0; num184 < 1000; num184++)
{
                                            if (this.whoAmI != num184 && this.owner == Main.projectile[num184].owner && Main.projectile[num184].type >= 390 && Main.projectile[num184].type <= 392 && (Main.projectile[num184].Center - base.Center).Length() < 15f)
{
                                                float num185 = 0.5f;
                                                if (base.Center.Y > Main.projectile[num184].Center.Y)
{
                                                    Projectile projectile2 = Main.projectile[num184];
                                                    projectile2.velocity.Y = projectile2.velocity.Y - num185;
                                                    this.velocity.Y = this.velocity.Y + num185;
                                                }
                                                else
{
                                                    Projectile projectile3 = Main.projectile[num184];
                                                    projectile3.velocity.Y = projectile3.velocity.Y + num185;
                                                    this.velocity.Y = this.velocity.Y - num185;
                                                }
                                                if (base.Center.X > Main.projectile[num184].Center.X)
{
                                                    this.velocity.X = this.velocity.X + num185;
                                                    Projectile projectile4 = Main.projectile[num184];
                                                    projectile4.velocity.X = projectile4.velocity.X - num185;
                                                }
                                                else
{
                                                    this.velocity.X = this.velocity.X - num185;
                                                    Projectile projectile5 = Main.projectile[num184];
                                                    projectile5.velocity.Y = projectile5.velocity.Y + num185;
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                            float num186 = 300f;
                            if ((double)this.position.Y > Main.worldSurface * 16.0)
{
                                num186 = 150f;
                            }
                            if (flag7)
{
                                num186 = 500f;
                                if ((double)this.position.Y > Main.worldSurface * 16.0)
{
                                    num186 = 250f;
                                }
                            }
                            if (num173 < num186 + num169 && num175 == -1)
{
                                float num187 = num171 - (this.position.X + (float)(this.width / 2));
                                if (num187 < -5f)
{
                                    flag2 = true;
                                    flag3 = false;
                                }
                                else if (num187 > 5f)
{
                                    flag3 = true;
                                    flag2 = false;
                                }
                            }
                            bool flag31 = false;
                            if (flag7 && this.localAI[1] > 0f)
{
                                flag31 = true;
                                this.localAI[1] -= 1f;
                            }
                            if (num175 >= 0 && num173 < 800f + num169)
{
                                this.friendly = true;
                                this.localAI[0] = (float)num170;
                                float num188 = num171 - (this.position.X + (float)(this.width / 2));
                                if (num188 < -10f)
{
                                    flag2 = true;
                                    flag3 = false;
                                }
                                else if (num188 > 10f)
{
                                    flag3 = true;
                                    flag2 = false;
                                }
                                if (num172 < base.Center.Y - 100f && num188 > -50f && num188 < 50f && this.velocity.Y == 0f)
{
                                    float num189 = Math.Abs(num172 - base.Center.Y);
                                    if (num189 < 120f)
{
                                        this.velocity.Y = -10f;
                                    }
                                    else if (num189 < 210f)
{
                                        this.velocity.Y = -13f;
                                    }
                                    else if (num189 < 270f)
{
                                        this.velocity.Y = -15f;
                                    }
                                    else if (num189 < 310f)
{
                                        this.velocity.Y = -17f;
                                    }
                                    else if (num189 < 380f)
{
                                        this.velocity.Y = -18f;
                                    }
                                }
                                if (flag31)
{
                                    this.friendly = false;
                                    if (this.velocity.X < 0f)
{
                                        flag2 = true;
                                    }
                                    else if (this.velocity.X > 0f)
{
                                        flag3 = true;
                                    }
                                }
                            }
                            else
{
                                this.friendly = false;
                            }
                        }
                    }
                    if (this.ai[1] != 0f || flag9)
                    {
                        flag2 = false;
                        flag3 = false;
                    }
                    else if (flag10 && this.localAI[0] == 0f)
                    {
                        this.direction = Main.player[this.owner].direction;
                    }
                    bool flag32 = true;
                    if (this.ai[1] != 0f && flag8)
                    {
                        flag32 = false;
                        if (this.velocity.Y == 0f)
{
                            this.velocity.X = this.velocity.X * 0.7f;
                        }
                    }
                    if (this.type == 127)
                    {
                        if ((double)this.rotation > -0.1 && (double)this.rotation < 0.1)
{
                            this.rotation = 0f;
                        }
                        else if (this.rotation < 0f)
{
                            this.rotation += 0.1f;
                        }
                        else
{
                            this.rotation -= 0.1f;
                        }
                    }
                    else if (this.type != 313 && !flag30)
                    {
                        this.rotation = 0f;
                    }
                    if (!flag7)
                    {
                        this.tileCollide = true;
                    }
                    float num190 = 0.08f;
                    float num191 = 6.5f;
                    if (this.type == 127)
                    {
                        num191 = 2f;
                        num190 = 0.04f;
                    }
                    if (this.type == 112)
                    {
                        num191 = 6f;
                        num190 = 0.06f;
                    }
                    if (this.type == 1094)
                    {
                        num191 = 6f;
                        num190 = 0.03f;
                    }
                    if (this.type == 334)
                    {
                        num191 = 8f;
                        num190 = 0.08f;
                    }
                    if (this.type == 268)
                    {
                        num191 = 8f;
                        num190 = 0.4f;
                    }
                    if (this.type == 324)
                    {
                        num190 = 0.1f;
                        num191 = 3f;
                    }
                    if (this.type == 858)
                    {
                        num190 = 0.3f;
                        num191 = 7f;
                    }
                    if (flag10 || this.type == 266 || flag7 || this.type == 816 || this.type == 821 || this.type == 825 || this.type == 859 || this.type == 860 || this.type == 881 || this.type == 884 || this.type == 890 || this.type == 891 || this.type == 897 || this.type == 899 || this.type == 900 || this.type == 934 || this.type == 956 || this.type == 958 || this.type == 959 || this.type == 960 || this.type == 994 || this.type == 998 || this.type == 1003 || this.type == 1004 || this.type == 1027 || this.type == 1095 || this.type == 1096)
                    {
                        num191 = 6f;
                        num190 = 0.2f;
                        if (num191 < Math.Abs(Main.player[this.owner].velocity.X) + Math.Abs(Main.player[this.owner].velocity.Y))
{
                            num191 = Math.Abs(Main.player[this.owner].velocity.X) + Math.Abs(Main.player[this.owner].velocity.Y);
                            num190 = 0.3f;
                        }
                        if (flag10)
{
                            num190 *= 2f;
                        }
                        if (this.type == 1027)
{
                            num190 *= 1.5f;
                        }
                    }
                    if (this.type == 875)
                    {
                        num191 = 7f;
                        num190 = 0.25f;
                        if (num191 < Math.Abs(Main.player[this.owner].velocity.X) + Math.Abs(Main.player[this.owner].velocity.Y))
{
                            num191 = Math.Abs(Main.player[this.owner].velocity.X) + Math.Abs(Main.player[this.owner].velocity.Y);
                            num190 = 0.35f;
                        }
                    }
                    if (flag7)
                    {
                        num190 *= 2f;
                    }
                    if (flag11)
                    {
                        num191 = 6f;
                    }
                    if (flag2)
                    {
                        if ((double)this.velocity.X > -3.5)
{
                            this.velocity.X = this.velocity.X - num190;
                        }
                        else
{
                            this.velocity.X = this.velocity.X - num190 * 0.25f;
                        }
                    }
                    else if (flag3)
                    {
                        if ((double)this.velocity.X < 3.5)
{
                            this.velocity.X = this.velocity.X + num190;
                        }
                        else
{
                            this.velocity.X = this.velocity.X + num190 * 0.25f;
                        }
                    }
                    else
                    {
                        this.velocity.X = this.velocity.X * 0.9f;
                        if (this.velocity.X >= -num190 && this.velocity.X <= num190)
{
                            this.velocity.X = 0f;
                        }
                    }
                    if (this.type == 208)
                    {
                        this.velocity.X = this.velocity.X * 0.95f;
                        if ((double)this.velocity.X > -0.1 && (double)this.velocity.X < 0.1)
{
                            this.velocity.X = 0f;
                        }
                        flag2 = false;
                        flag3 = false;
                    }
                    if (flag2 || flag3)
                    {
                        int num192 = (int)(this.position.X + (float)(this.width / 2)) / 16;
                        int num193 = (int)(this.position.Y + (float)(this.height / 2)) / 16;
                        if (this.type == 236)
{
                            num192 += this.direction;
                        }
                        if (flag2)
{
                            num192--;
                        }
                        if (flag3)
{
                            num192++;
                        }
                        num192 += (int)this.velocity.X;
                        if (WorldGen.InWorld(num192, num193, 0) && WorldGen.SolidTile(num192, num193, false) && Main.tile[num192, num193] != null && !TileID.Sets.ForAdvancedCollision.ClosedDoors[(int)Main.tile[num192, num193].type])
{
                            flag5 = true;
                        }
                    }
                    if (Main.player[this.owner].position.Y + (float)Main.player[this.owner].height - 8f > this.position.Y + (float)this.height)
                    {
                        flag4 = true;
                    }
                    if (this.type == 268 && this.frameCounter < 10)
                    {
                        flag5 = false;
                    }
                    if (this.type == 860 && this.velocity.X != 0f)
                    {
                        flag5 = true;
                    }
                    if ((this.type == 881 || this.type == 934) && this.velocity.X != 0f)
                    {
                        flag5 = true;
                    }
                    Collision.StepUp(ref this.position, ref this.velocity, this.width, this.height, ref this.stepSpeed, ref this.gfxOffY, 1, false, 0);
                    if (this.velocity.Y == 0f || this.type == 200)
                    {
                        if (!flag4 && (this.velocity.X < 0f || this.velocity.X > 0f))
{
                            int num194 = (int)(this.position.X + (float)(this.width / 2)) / 16;
                            int num195 = (int)(this.position.Y + (float)(this.height / 2)) / 16 + 1;
                            if (flag2)
{
                                num194--;
                            }
                            if (flag3)
{
                                num194++;
                            }
                            WorldGen.SolidTile(num194, num195, false);
                        }
                        if (flag5)
{
                            int num196 = (int)(this.position.X + (float)(this.width / 2)) / 16;
                            int num197 = (int)(this.position.Y + (float)this.height) / 16;
                            if (WorldGen.SolidTileAllowBottomSlope(num196, num197) || Main.tile[num196, num197].halfBrick() || Main.tile[num196, num197].slope() > 0 || this.type == 200)
{
                                if (this.type == 200)
{
                                    this.velocity.Y = -3.1f;
                                }
                                else
{
                                    try
{
                                        num196 = (int)(this.position.X + (float)(this.width / 2)) / 16;
                                        num197 = (int)(this.position.Y + (float)(this.height / 2)) / 16;
                                        if (flag2)
{
                                            num196--;
                                        }
                                        if (flag3)
{
                                            num196++;
                                        }
                                        num196 += (int)this.velocity.X;
                                        if (!WorldGen.SolidTile(num196, num197 - 1, false) && !WorldGen.SolidTile(num196, num197 - 2, false))
{
                                            this.velocity.Y = -5.1f;
                                        }
                                        else if (!WorldGen.SolidTile(num196, num197 - 2, false))
{
                                            this.velocity.Y = -7.1f;
                                        }
                                        else if (WorldGen.SolidTile(num196, num197 - 5, false))
{
                                            this.velocity.Y = -11.1f;
                                        }
                                        else if (WorldGen.SolidTile(num196, num197 - 4, false))
{
                                            this.velocity.Y = -10.1f;
                                        }
                                        else
{
                                            this.velocity.Y = -9.1f;
                                        }
                                    }
                                    catch
{
                                        this.velocity.Y = -9.1f;
                                    }
                                }
                                if (this.type == 127)
{
                                    this.ai[0] = 1f;
                                }
                            }
                        }
                        else if (this.type == 266 && (flag2 || flag3))
{
                            this.velocity.Y = this.velocity.Y - 6f;
                        }
                    }
                    if (this.velocity.X > num191)
                    {
                        this.velocity.X = num191;
                    }
                    if (this.velocity.X < -num191)
                    {
                        this.velocity.X = -num191;
                    }
                    if (flag32)
                    {
                        if (this.velocity.X < 0f)
{
                            this.direction = -1;
                        }
                        if (this.velocity.X > 0f)
{
                            this.direction = 1;
                        }
                        if (this.velocity.X > num190 && flag3)
{
                            this.direction = 1;
                        }
                        if (this.velocity.X < -num190 && flag2)
{
                            this.direction = -1;
                        }
                    }
                    if (this.type != 313)
                    {
                        if (this.direction == -1)
{
                            this.spriteDirection = 1;
                        }
                        if (this.direction == 1)
{
                            this.spriteDirection = -1;
                        }
                    }
                    if (this.type == 398 || this.type == 958 || this.type == 960 || this.type == 956 || this.type == 959 || this.type == 994 || this.type == 1095 || this.type == 1096 || this.type == 1094)
                    {
                        this.spriteDirection = this.direction;
                    }
                    bool flag33 = this.position.X - this.oldPosition.X == 0f;
                    if (this.type == 956)
                    {
                        if (this.alpha > 0)
{
                            int num198 = Dust.NewDust(this.position, this.width, this.height, 6, this.velocity.X, this.velocity.Y, 0, default(Color), 1.2f);
                            Dust dust6 = Main.dust[num198];
                            dust6.velocity.X = dust6.velocity.X + (Main.rand.NextFloat() - 0.5f);
                            Dust dust7 = Main.dust[num198];
                            dust7.velocity.Y = dust7.velocity.Y + (Main.rand.NextFloat() + 0.5f) * -1f;
                            if (Main.rand.Next(3) != 0)
{
                                Main.dust[num198].noGravity = true;
                            }
                            this.alpha -= 5;
                            if (this.alpha < 0)
{
                                this.alpha = 0;
                            }
                        }
                        if (this.velocity.Y != 0f)
{
                            this.frame = 10;
                        }
                        else if (flag33)
{
                            this.spriteDirection = 1;
                            if (Main.player[this.owner].Center.X < base.Center.X)
{
                                this.spriteDirection = -1;
                            }
                            this.frame = 0;
                        }
                        else
{
                            float num199 = this.velocity.Length();
                            this.frameCounter += (int)num199;
                            if (this.frameCounter > 7)
{
                                this.frame++;
                                this.frameCounter = 0;
                            }
                            if (this.frame < 1 || this.frame > 9)
{
                                this.frame = 1;
                            }
                        }
                        this.velocity.Y = this.velocity.Y + 0.4f;
                        if (this.velocity.Y > 10f)
{
                            this.velocity.Y = 10f;
                        }
                    }
                    else if (this.type == 958)
                    {
                        if (this.velocity.Y != 0f)
{
                            this.localAI[0] = 0f;
                            this.frame = 4;
                        }
                        else if (flag33)
{
                            this.spriteDirection = 1;
                            if (Main.player[this.owner].Center.X < base.Center.X)
{
                                this.spriteDirection = -1;
                            }
                            this.localAI[0] += 1f;
                            if (this.localAI[0] > 200f)
{
                                this.frame = 1 + (int)(this.localAI[0] - 200f) / 6;
                                if (this.localAI[0] >= 218f)
{
                                    this.frame = 0;
                                    this.localAI[0] = (float)Main.rand.Next(100);
                                }
                            }
                            else
{
                                this.frame = 0;
                            }
                        }
                        else
{
                            this.localAI[0] = 0f;
                            float num200 = this.velocity.Length();
                            this.frameCounter += (int)num200;
                            if (this.frameCounter > 6)
{
                                this.frame++;
                                this.frameCounter = 0;
                            }
                            if (this.frame < 5 || this.frame > 12)
{
                                this.frame = 5;
                            }
                        }
                        this.velocity.Y = this.velocity.Y + 0.4f;
                        if (this.velocity.Y > 10f)
{
                            this.velocity.Y = 10f;
                        }
                    }
                    else if (this.type == 959)
                    {
                        if (this.velocity.Y != 0f)
{
                            this.frame = ((this.velocity.Y > 0f) ? 10 : 9);
                        }
                        else if (flag33)
{
                            this.spriteDirection = 1;
                            if (Main.player[this.owner].Center.X < base.Center.X)
{
                                this.spriteDirection = -1;
                            }
                            this.frame = 0;
                        }
                        else
{
                            float num201 = this.velocity.Length();
                            this.frameCounter += (int)num201;
                            if (this.frameCounter > 6)
{
                                this.frame++;
                                this.frameCounter = 0;
                            }
                            if (this.frame < 1 || this.frame > 8)
{
                                this.frame = 1;
                            }
                        }
                        this.velocity.Y = this.velocity.Y + 0.4f;
                        if (this.velocity.Y > 10f)
{
                            this.velocity.Y = 10f;
                        }
                    }
                    else if (this.type == 998)
                    {
                        if (this.velocity.Y != 0f)
{
                            this.frame = 1;
                        }
                        else if (flag33)
{
                            this.spriteDirection = -1;
                            if (Main.player[this.owner].Center.X < base.Center.X)
{
                                this.spriteDirection = 1;
                            }
                            this.frame = 0;
                        }
                        else
{
                            float num202 = this.velocity.Length();
                            this.frameCounter += (int)num202;
                            if (this.frameCounter > 6)
{
                                this.frame++;
                                this.frameCounter = 0;
                            }
                            if (this.frame < 0 || this.frame > 5)
{
                                this.frame = 0;
                            }
                        }
                        this.velocity.Y = this.velocity.Y + 0.4f;
                        if (this.velocity.Y > 10f)
{
                            this.velocity.Y = 10f;
                        }
                    }
                    else if (this.type == 1003)
                    {
                        if (this.velocity.Y != 0f)
{
                            this.frame = 1;
                        }
                        else if (flag33)
{
                            this.spriteDirection = -1;
                            if (Main.player[this.owner].Center.X < base.Center.X)
{
                                this.spriteDirection = 1;
                            }
                            this.frame = 0;
                        }
                        else
{
                            float num203 = this.velocity.Length();
                            this.frameCounter += (int)num203;
                            if (this.frameCounter > 6)
{
                                this.frame++;
                                this.frameCounter = 0;
                            }
                            if (this.frame < 2 || this.frame > 11)
{
                                this.frame = 2;
                            }
                        }
                        this.velocity.Y = this.velocity.Y + 0.4f;
                        if (this.velocity.Y > 10f)
{
                            this.velocity.Y = 10f;
                        }
                    }
                    else if (this.type == 1004)
                    {
                        if (this.velocity.Y != 0f)
{
                            this.frame = 1;
                        }
                        else if (flag33)
{
                            this.spriteDirection = -1;
                            if (Main.player[this.owner].Center.X < base.Center.X)
{
                                this.spriteDirection = 1;
                            }
                            this.frame = 0;
                        }
                        else
{
                            float num204 = this.velocity.Length();
                            this.frameCounter += (int)num204;
                            if (this.frameCounter > 6)
{
                                this.frame++;
                                this.frameCounter = 0;
                            }
                            if (this.frame < 2 || this.frame > 9)
{
                                this.frame = 2;
                            }
                        }
                        this.velocity.Y = this.velocity.Y + 0.4f;
                        if (this.velocity.Y > 10f)
{
                            this.velocity.Y = 10f;
                        }
                    }
                    else if (this.type == 1027)
                    {
                        if (this.alpha > 0)
{
                            this.alpha = 0;
                            int num205 = 25;
                            float num206 = Main.rand.NextFloat() * 6.2831855f;
                            for (int num207 = 0; num207 < num205; num207++)
{
                                bool flag34 = num207 % 2 == 0;
                                float num208 = num206 + (float)num207 / (float)num205 * 6.2831855f;
                                Vector2 vector30 = new Vector2(0f, flag34 ? 2f : 4f).RotatedBy((double)num208, default(Vector2));
                                Dust dust8 = Dust.NewDustPerfect(base.Center, 282, new Vector2?(vector30), 0, default(Color), 1f);
                                dust8.scale = (flag34 ? 1.3f : 1.2f);
                                dust8.noGravity = true;
                            }
                        }
                        if (this.velocity.Y < 0f)
{
                            this.frame = 2;
                        }
                        else if (this.velocity.Y > 0f)
{
                            this.frame = 4;
                        }
                        else if (flag33)
{
                            this.spriteDirection = -1;
                            if (Main.player[this.owner].Center.X < base.Center.X)
{
                                this.spriteDirection = 1;
                            }
                            this.frame = 0;
                        }
                        else
{
                            float num209 = this.velocity.Length() / 2f;
                            this.frameCounter += Math.Max(1, (int)num209);
                            if (this.frameCounter > 5)
{
                                this.frame++;
                                this.frameCounter = 0;
                            }
                            if (this.frame < 0 || this.frame > 3)
{
                                this.frame = 0;
                            }
                        }
                        this.rotation = 0f;
                        if (this.velocity.Y != 0f)
{
                            this.rotation = this.velocity.Y / 10f * 0.7853982f * (float)(-(float)this.spriteDirection);
                        }
                        this.velocity.Y = this.velocity.Y + 0.4f;
                        if (this.velocity.Y > 10f)
{
                            this.velocity.Y = 10f;
                        }
                    }
                    else if (this.type == 1095 || this.type == 1096)
                    {
                        if (this.velocity.Y != 0f)
{
                            this.frame = ((this.velocity.Y > 0f) ? 10 : 9);
                        }
                        else if (flag33)
{
                            this.spriteDirection = 1;
                            if (Main.player[this.owner].Center.X < base.Center.X)
{
                                this.spriteDirection = -1;
                            }
                            this.frame = 0;
                        }
                        else
{
                            float num210 = this.velocity.Length();
                            this.frameCounter += (int)num210;
                            if (this.frameCounter > 6)
{
                                this.frame++;
                                this.frameCounter = 0;
                            }
                            if (this.frame < 1 || this.frame > 8)
{
                                this.frame = 1;
                            }
                        }
                        this.velocity.Y = this.velocity.Y + 0.4f;
                        if (this.velocity.Y > 10f)
{
                            this.velocity.Y = 10f;
                        }
                    }
                    else if (this.type == 994)
                    {
                        if (this.velocity.Y != 0f)
{
                            this.frame = 4;
                        }
                        else if (flag33)
{
                            this.spriteDirection = 1;
                            if (Main.player[this.owner].Center.X < base.Center.X)
{
                                this.spriteDirection = -1;
                            }
                            this.frameCounter++;
                            if (this.frameCounter > 5)
{
                                this.frame++;
                                this.frameCounter = 0;
                            }
                            if (this.frame > 3)
{
                                this.frame = 0;
                            }
                        }
                        else
{
                            float num211 = this.velocity.Length();
                            this.frameCounter += (int)num211;
                            if (this.frameCounter > 6)
{
                                this.frame++;
                                this.frameCounter = 0;
                            }
                            if (this.frame < 5 || this.frame > 12)
{
                                this.frame = 5;
                            }
                        }
                        this.velocity.Y = this.velocity.Y + 0.4f;
                        if (this.velocity.Y > 10f)
{
                            this.velocity.Y = 10f;
                        }
                    }
                    else if (this.type == 960)
                    {
                        Player player6 = Main.player[this.owner];
                        if (this.velocity.Y != 0f)
{
                            this.localAI[0] = 0f;
                            this.localAI[1] = 0f;
                            this.frameCounter = 0;
                            this.frame = 4;
                        }
                        else if (flag33)
{
                            if (!flag11)
{
                                this.spriteDirection = 1;
                                if (Main.player[this.owner].Center.X < base.Center.X)
{
                                    this.spriteDirection = -1;
                                }
                            }
                            if (this.frame >= 5 && this.frame < 12)
{
                                this.frameCounter++;
                                if (this.frameCounter > 3)
{
                                    this.frame++;
                                    this.frameCounter = 0;
                                }
                                if (this.frame >= 12)
{
                                    this.frame = 0;
                                }
                            }
                            else if (this.Chester_IsAnyPlayerTrackingThisProjectile())
{
                                if (this.localAI[0] == 0f)
{
                                    if (this.localAI[1] == 0f)
{
                                        this.localAI[1] = 1f;
                                        this.frameCounter = 0;
                                    }
                                    this.frame = 13;
                                    this.frameCounter++;
                                    if (this.frameCounter > 6)
{
                                        this.localAI[0] = 1f;
                                        this.frame = 14;
                                        this.frameCounter = 0;
                                    }
                                }
                                else
{
                                    this.frameCounter++;
                                    if (this.frameCounter > 6)
{
                                        this.frame++;
                                        if (this.frame > 18)
{
                                            this.frame = 14;
                                        }
                                        this.frameCounter = 0;
                                    }
                                }
                            }
                            else
{
                                this.localAI[0] = 0f;
                                if (this.localAI[1] == 1f)
{
                                    this.localAI[1] = 0f;
                                    this.frameCounter = 0;
                                }
                                if (this.frame >= 12 && this.frame <= 19)
{
                                    this.frame = 19;
                                    this.frameCounter++;
                                    if (this.frameCounter > 6)
{
                                        this.frame = 0;
                                        this.frameCounter = 0;
                                    }
                                }
                                else
{
                                    this.frameCounter++;
                                    if (this.frameCounter >= 24)
{
                                        this.frameCounter = 0;
                                    }
                                    this.frame = this.frameCounter / 6;
                                }
                            }
                        }
                        else
{
                            this.localAI[0] = 0f;
                            this.localAI[1] = 0f;
                            float num212 = this.velocity.Length();
                            this.frameCounter += (int)Math.Max(2f, num212);
                            if (this.frameCounter > 6)
{
                                this.frame++;
                                this.frameCounter = 0;
                            }
                            if (this.frame < 5 || this.frame > 12)
{
                                this.frame = 5;
                            }
                        }
                        this.velocity.Y = this.velocity.Y + 0.4f;
                        if (this.velocity.Y > 10f)
{
                            this.velocity.Y = 10f;
                        }
                    }
                    else if (this.type == 816)
                    {
                        if (this.velocity.Y != 0f)
{
                            this.frame = 4;
                        }
                        else if (flag33)
{
                            this.spriteDirection = -1;
                            if (Main.player[this.owner].Center.X < base.Center.X)
{
                                this.spriteDirection = 1;
                            }
                            num2 = this.frameCounter + 1;
                            this.frameCounter = num2;
                            if (num2 > 5)
{
                                this.frame++;
                                this.frameCounter = 0;
                            }
                            if (this.frame < 0 || this.frame > 3)
{
                                this.frame = 0;
                            }
                        }
                        else
{
                            int num213 = 5;
                            float num214 = this.velocity.Length();
                            if (num214 > 4f)
{
                                num213 = 3;
                            }
                            else if (num214 > 2f)
{
                                num213 = 4;
                            }
                            num2 = this.frameCounter + 1;
                            this.frameCounter = num2;
                            if (num2 > num213)
{
                                this.frame++;
                                this.frameCounter = 0;
                            }
                            if (this.frame < 4 || this.frame > 10)
{
                                this.frame = 4;
                            }
                        }
                        this.velocity.Y = this.velocity.Y + 0.4f;
                        if (this.velocity.Y > 10f)
{
                            this.velocity.Y = 10f;
                        }
                    }
                    if (this.type == 860)
                    {
                        if (this.velocity.Y != 0f)
{
                            this.localAI[0] = 0f;
                            if (this.frame >= 5)
{
                                this.frame = 5;
                                this.frameCounter = 0;
                            }
                            else
{
                                num2 = this.frameCounter + 1;
                                this.frameCounter = num2;
                                if (num2 > 5)
{
                                    this.frame++;
                                    this.frameCounter = 0;
                                }
                            }
                        }
                        else if (Math.Abs(this.velocity.X) < 1f)
{
                            if (this.localAI[0] > 800f)
{
                                this.frameCounter++;
                                if (this.frameCounter > 3)
{
                                    this.frameCounter = 0;
                                    this.frame++;
                                    if (this.frame > 3)
{
                                        this.frame = 3;
                                    }
                                }
                                this.localAI[0] += 1f;
                                if (this.localAI[0] > 850f)
{
                                    this.localAI[0] = 0f;
                                }
                                if (this.frame == 3 && this.localAI[0] == 820f)
{
                                    for (int num215 = 0; num215 < 3 + Main.rand.Next(3); num215++)
{
                                        int num216 = Gore.NewGore(new Vector2(this.position.X, base.Center.Y - 10f), Vector2.Zero, 1218, 1f);
                                        Main.gore[num216].velocity = new Vector2((float)Main.rand.Next(1, 10) * 0.3f * (float)(-(float)this.spriteDirection), -(2f + (float)Main.rand.Next(4) * 0.3f));
                                    }
                                }
                            }
                            else if (this.frame == 0)
{
                                this.localAI[0] += 1f;
                                this.frame = 0;
                                this.frameCounter = 0;
                            }
                            else
{
                                this.localAI[0] = 0f;
                                if (this.frame > 5)
{
                                    this.frame = 5;
                                    this.frameCounter = 0;
                                }
                                num2 = this.frameCounter + 1;
                                this.frameCounter = num2;
                                if (num2 > 4)
{
                                    this.frame--;
                                    this.frameCounter = 0;
                                }
                            }
                        }
                        this.velocity.Y = this.velocity.Y + 0.4f;
                        if (this.velocity.Y > 10f)
{
                            this.velocity.Y = 10f;
                        }
                    }
                    if (this.type == 859)
                    {
                        if (this.velocity.Y != 0f)
{
                            this.frame = 4;
                        }
                        else if (flag33)
{
                            this.spriteDirection = -1;
                            if (Main.player[this.owner].Center.X < base.Center.X)
{
                                this.spriteDirection = 1;
                            }
                            if (this.frame == 6)
{
                                num2 = this.frameCounter + 1;
                                this.frameCounter = num2;
                                if (num2 > 5)
{
                                    this.frame = 0;
                                    this.frameCounter = 0;
                                }
                            }
                            else if (this.frame > 3)
{
                                this.frame = 6;
                                this.frameCounter = 0;
                            }
                            else
{
                                num2 = this.frameCounter + 1;
                                this.frameCounter = num2;
                                if (num2 > 5)
{
                                    this.frame++;
                                    this.frameCounter = 0;
                                }
                                if (this.frame < 0 || this.frame > 3)
{
                                    this.frame = 0;
                                }
                            }
                        }
                        else
{
                            float num217 = this.velocity.Length();
                            int num218 = 8;
                            if (num217 < 3f)
{
                                num218 = 4;
                            }
                            if (num217 < 1f)
{
                                num218 = 2;
                            }
                            this.frameCounter += (int)num217;
                            if (this.frameCounter > num218)
{
                                this.frame++;
                                this.frameCounter = 0;
                            }
                            if (this.frame < 5 || this.frame > 17)
{
                                this.frame = 5;
                            }
                        }
                        this.velocity.Y = this.velocity.Y + 0.4f;
                        if (this.velocity.Y > 10f)
{
                            this.velocity.Y = 10f;
                        }
                    }
                    else if (this.type == 858)
                    {
                        if (this.velocity.Y != 0f)
{
                            this.frame = 1;
                        }
                        else if (flag33)
{
                            this.spriteDirection = -1;
                            if (Main.player[this.owner].Center.X < base.Center.X)
{
                                this.spriteDirection = 1;
                            }
                            this.frame = 0;
                        }
                        else
{
                            float num219 = this.velocity.Length();
                            this.frameCounter += (int)num219;
                            if (this.frameCounter > 3)
{
                                this.frame++;
                                this.frameCounter = 0;
                            }
                            if (this.frame < 2 || this.frame > 9)
{
                                this.frame = 2;
                            }
                        }
                        this.velocity.Y = this.velocity.Y + 0.4f;
                        if (this.velocity.Y > 10f)
{
                            this.velocity.Y = 10f;
                        }
                    }
                    else if (this.type == 900)
                    {
                        this.spriteDirection = this.direction;
                        if (this.velocity.Y != 0f)
{
                            this.frame = 1;
                            this.frameCounter = 0;
                        }
                        else if (flag33)
{
                            this.spriteDirection = 1;
                            if (Main.player[this.owner].Center.X < base.Center.X)
{
                                this.spriteDirection = -1;
                            }
                            this.frame = 0;
                            this.frameCounter = 0;
                        }
                        else
{
                            this.frameCounter += 1 + (int)Math.Abs(this.velocity.X * 0.3f);
                            if (this.frame < 2)
{
                                this.frame = 2;
                                this.frameCounter = 0;
                            }
                            if (this.frameCounter > 4)
{
                                this.frame++;
                                this.frameCounter = 0;
                            }
                            if (this.frame > 9)
{
                                this.frame = 2;
                            }
                        }
                        this.velocity.Y = this.velocity.Y + 0.4f;
                        if (this.velocity.Y > 10f)
{
                            this.velocity.Y = 10f;
                        }
                    }
                    else if (this.type == 899)
                    {
                        this.spriteDirection = this.direction;
                        if (this.velocity.Y != 0f)
{
                            this.frame = 1;
                            this.frameCounter = 0;
                        }
                        else if (flag33)
{
                            this.spriteDirection = 1;
                            if (Main.player[this.owner].Center.X < base.Center.X)
{
                                this.spriteDirection = -1;
                            }
                            this.frame = 0;
                            this.frameCounter = 0;
                        }
                        else
{
                            this.frameCounter += 1 + (int)Math.Abs(this.velocity.X * 0.3f);
                            if (this.frame < 2)
{
                                this.frame = 2;
                                this.frameCounter = 0;
                            }
                            if (this.frameCounter > 4)
{
                                this.frame++;
                                this.frameCounter = 0;
                            }
                            if (this.frame > 9)
{
                                this.frame = 2;
                            }
                        }
                        this.velocity.Y = this.velocity.Y + 0.4f;
                        if (this.velocity.Y > 10f)
{
                            this.velocity.Y = 10f;
                        }
                    }
                    else if (this.type == 897)
                    {
                        this.spriteDirection = this.direction;
                        if (this.velocity.Y != 0f)
{
                            this.frame = 1;
                            this.frameCounter = 0;
                        }
                        else if (flag33)
{
                            this.spriteDirection = 1;
                            if (Main.player[this.owner].Center.X < base.Center.X)
{
                                this.spriteDirection = -1;
                            }
                            this.frame = 0;
                            this.frameCounter = 0;
                        }
                        else
{
                            this.frameCounter += 1 + (int)Math.Abs(this.velocity.X * 0.3f);
                            if (this.frame < 2)
{
                                this.frame = 2;
                                this.frameCounter = 0;
                            }
                            if (this.frameCounter > 4)
{
                                this.frame++;
                                this.frameCounter = 0;
                            }
                            if (this.frame > 7)
{
                                this.frame = 2;
                            }
                        }
                        this.velocity.Y = this.velocity.Y + 0.4f;
                        if (this.velocity.Y > 10f)
{
                            this.velocity.Y = 10f;
                        }
                    }
                    else if (this.type == 891)
                    {
                        this.spriteDirection = this.direction;
                        if (this.velocity.Y != 0f)
{
                            this.frame = 1;
                            this.frameCounter = 0;
                        }
                        else if (flag33)
{
                            this.spriteDirection = Main.player[this.owner].direction;
                            this.frame = 0;
                            this.frameCounter = 0;
                        }
                        else
{
                            this.frameCounter += 1 + (int)Math.Abs(this.velocity.X * 0.3f);
                            if (this.frame < 2)
{
                                this.frame = 2;
                                this.frameCounter = 0;
                            }
                            if (this.frameCounter > 4)
{
                                this.frame++;
                                this.frameCounter = 0;
                            }
                            if (this.frame > 8)
{
                                this.frame = 2;
                            }
                        }
                        this.velocity.Y = this.velocity.Y + 0.4f;
                        if (this.velocity.Y > 10f)
{
                            this.velocity.Y = 10f;
                        }
                    }
                    else if (this.type == 890)
                    {
                        this.spriteDirection = this.direction;
                        if (this.velocity.Y != 0f)
{
                            this.frame = 1;
                            this.frameCounter = 0;
                        }
                        else if (flag33)
{
                            this.spriteDirection = 1;
                            if (Main.player[this.owner].Center.X < base.Center.X)
{
                                this.spriteDirection = -1;
                            }
                            this.frame = 0;
                            this.frameCounter = 0;
                        }
                        else
{
                            this.frameCounter += 1 + (int)Math.Abs(this.velocity.X * 0.3f);
                            if (this.frame < 2)
{
                                this.frame = 2;
                                this.frameCounter = 0;
                            }
                            if (this.frameCounter > 4)
{
                                this.frame++;
                                this.frameCounter = 0;
                            }
                            if (this.frame > 7)
{
                                this.frame = 2;
                            }
                        }
                        this.velocity.Y = this.velocity.Y + 0.4f;
                        if (this.velocity.Y > 10f)
{
                            this.velocity.Y = 10f;
                        }
                    }
                    else if (this.type == 884)
                    {
                        this.spriteDirection = this.direction;
                        if (this.velocity.Y != 0f)
{
                            if (this.velocity.Y < 0f)
{
                                this.frame = 9;
                            }
                            else
{
                                this.frame = 1;
                            }
                            this.frameCounter = 0;
                        }
                        else if (flag33)
{
                            this.spriteDirection = 1;
                            if (Main.player[this.owner].Center.X < base.Center.X)
{
                                this.spriteDirection = -1;
                            }
                            this.frame = 0;
                            this.frameCounter = 0;
                        }
                        else
{
                            this.frameCounter += 1 + (int)Math.Abs(this.velocity.X * 0.5f);
                            if (this.frameCounter > 6)
{
                                this.frame++;
                                this.frameCounter = 0;
                            }
                            if (this.frame > 8)
{
                                this.frame = 2;
                            }
                        }
                        this.velocity.Y = this.velocity.Y + 0.4f;
                        if (this.velocity.Y > 10f)
{
                            this.velocity.Y = 10f;
                        }
                    }
                    else if (this.type == 881 || this.type == 934)
                    {
                        this.spriteDirection = 1;
                        if (Main.player[this.owner].Center.X < base.Center.X)
{
                            this.spriteDirection = -1;
                        }
                        if (this.velocity.Y > 0f)
{
                            this.frameCounter++;
                            if (this.frameCounter > 2)
{
                                this.frame++;
                                if (this.frame >= 2)
{
                                    this.frame = 2;
                                }
                                this.frameCounter = 0;
                            }
                        }
                        else if (this.velocity.Y < 0f)
{
                            this.frameCounter++;
                            if (this.frameCounter > 2)
{
                                this.frame++;
                                if (this.frame >= 5)
{
                                    this.frame = 0;
                                }
                                this.frameCounter = 0;
                            }
                        }
                        else if (this.frame == 0)
{
                            this.frame = 0;
                        }
                        else
{
                            num2 = this.frameCounter + 1;
                            this.frameCounter = num2;
                            if (num2 > 3)
{
                                this.frame++;
                                if (this.frame >= 6)
{
                                    this.frame = 0;
                                }
                                this.frameCounter = 0;
                            }
                        }
                        if (this.wet && Main.player[this.owner].position.Y + (float)Main.player[this.owner].height < this.position.Y + (float)this.height && this.localAI[0] == 0f)
{
                            if (this.velocity.Y > -4f)
{
                                this.velocity.Y = this.velocity.Y - 0.2f;
                            }
                            if (this.velocity.Y > 0f)
{
                                this.velocity.Y = this.velocity.Y * 0.95f;
                            }
                        }
                        else
{
                            this.velocity.Y = this.velocity.Y + 0.4f;
                        }
                        if (this.velocity.Y > 10f)
{
                            this.velocity.Y = 10f;
                        }
                    }
                    else if (this.type == 875)
                    {
                        if (this.velocity.Y != 0f)
{
                            if (this.velocity.Y < 0f)
{
                                this.frame = 3;
                            }
                            else
{
                                this.frame = 6;
                            }
                            this.frameCounter = 0;
                        }
                        else if (flag33)
{
                            this.spriteDirection = -1;
                            if (Main.player[this.owner].Center.X < base.Center.X)
{
                                this.spriteDirection = 1;
                            }
                            this.frame = 0;
                            this.frameCounter = 0;
                        }
                        else
{
                            this.frameCounter += 1 + (int)Math.Abs(this.velocity.X * 0.75f);
                            if (this.frameCounter > 6)
{
                                this.frame++;
                                this.frameCounter = 0;
                            }
                            if (this.frame > 6)
{
                                this.frame = 0;
                            }
                        }
                        this.velocity.Y = this.velocity.Y + 0.4f;
                        if (this.velocity.Y > 10f)
{
                            this.velocity.Y = 10f;
                        }
                    }
                    else if (this.type == 854)
                    {
                        if (this.velocity.Y != 0f)
{
                            this.frame = 7;
                        }
                        else if (flag33)
{
                            this.spriteDirection = -1;
                            if (Main.player[this.owner].Center.X < base.Center.X)
{
                                this.spriteDirection = 1;
                            }
                            num2 = this.frameCounter + 1;
                            this.frameCounter = num2;
                            if (num2 > 5)
{
                                this.frame++;
                                this.frameCounter = 0;
                            }
                            if (this.frame < 0 || this.frame > 3)
{
                                this.frame = 0;
                            }
                        }
                        else
{
                            int num220 = 3;
                            float num221 = this.velocity.Length();
                            if (num221 > 4f)
{
                                num220 = 1;
                            }
                            else if (num221 > 2f)
{
                                num220 = 2;
                            }
                            num2 = this.frameCounter + 1;
                            this.frameCounter = num2;
                            if (num2 > num220)
{
                                this.frame++;
                                this.frameCounter = 0;
                            }
                            if (this.frame < 4 || this.frame > 12)
{
                                this.frame = 4;
                            }
                        }
                        this.velocity.Y = this.velocity.Y + 0.4f;
                        if (this.velocity.Y > 10f)
{
                            this.velocity.Y = 10f;
                        }
                    }
                    else if (this.type == 825)
                    {
                        if (this.velocity.Y != 0f)
{
                            this.localAI[0] = 0f;
                            this.frame = 12;
                        }
                        else if (flag33)
{
                            this.spriteDirection = -1;
                            if (Main.player[this.owner].Center.X < base.Center.X)
{
                                this.spriteDirection = 1;
                            }
                            if (this.frame >= 1 && this.frame <= 2)
{
                                this.localAI[0] = 0f;
                                num2 = this.frameCounter + 1;
                                this.frameCounter = num2;
                                if (num2 > 5)
{
                                    this.frame++;
                                    this.frameCounter = 0;
                                }
                                if (this.frame > 2)
{
                                    this.frame = 0;
                                }
                            }
                            else if (this.frame >= 3 && this.frame <= 11)
{
                                this.localAI[0] = 0f;
                                num2 = this.frameCounter + 1;
                                this.frameCounter = num2;
                                if (num2 > 5)
{
                                    this.frame++;
                                    this.frameCounter = 0;
                                }
                                if (this.frame > 11)
{
                                    this.frame = 0;
                                }
                            }
                            else
{
                                if (this.frame == 13)
{
                                    num2 = this.frameCounter + 1;
                                    this.frameCounter = num2;
                                    if (num2 > 8)
{
                                        this.frame++;
                                        this.frameCounter = 0;
                                    }
                                    if (this.frame == 14)
{
                                        this.frame = 0;
                                    }
                                }
                                if (this.frame != 0)
{
                                    this.frame = 13;
                                }
                                else
{
                                    this.frame = 0;
                                }
                                if (this.frame == 0)
{
                                    this.localAI[0] += 1f;
                                    if (this.localAI[0] > 300f && Main.rand.Next(50) == 0)
{
                                        int num222 = Main.rand.Next(2);
                                        if (num222 != 0)
{
                                            if (num222 == 1)
{
                                                this.frame = 3;
                                            }
                                        }
                                        else
{
                                            this.frame = 1;
                                        }
                                    }
                                }
                            }
                        }
                        else
{
                            this.localAI[0] = 0f;
                            int num223 = 3;
                            float num224 = this.velocity.Length();
                            if (num224 > 4f)
{
                                num223 = 2;
                            }
                            else if (num224 > 2f)
{
                                num223 = 1;
                            }
                            num2 = this.frameCounter + 1;
                            this.frameCounter = num2;
                            if (num2 > num223)
{
                                this.frame++;
                                this.frameCounter = 0;
                            }
                            if (this.frame < 13)
{
                                this.frame = 13;
                            }
                            if (this.frame > 19)
{
                                this.frame = 14;
                            }
                        }
                        this.velocity.Y = this.velocity.Y + 0.4f;
                        if (this.velocity.Y > 10f)
{
                            this.velocity.Y = 10f;
                        }
                    }
                    else if (this.type == 821)
                    {
                        if (this.velocity.Y != 0f)
{
                            this.localAI[0] = 0f;
                            this.frame = 12;
                        }
                        else if (flag33)
{
                            this.spriteDirection = -1;
                            if (Main.player[this.owner].Center.X < base.Center.X)
{
                                this.spriteDirection = 1;
                            }
                            this.localAI[0] += 1f;
                            if (this.localAI[0] > 400f)
{
                                int num225 = 7;
                                if (this.frame == 9)
{
                                    num225 = 25;
                                }
                                num2 = this.frameCounter + 1;
                                this.frameCounter = num2;
                                if (num2 > num225)
{
                                    this.frame++;
                                    this.frameCounter = 0;
                                }
                                if (this.frame < 5)
{
                                    this.frame = 5;
                                }
                                if (this.frame > 11)
{
                                    this.localAI[0] = 0f;
                                    this.frame = 0;
                                }
                            }
                            else
{
                                num2 = this.frameCounter + 1;
                                this.frameCounter = num2;
                                if (num2 > 6)
{
                                    this.frame++;
                                    this.frameCounter = 0;
                                }
                                if (this.frame < 0 || this.frame > 4)
{
                                    this.frame = 0;
                                }
                            }
                        }
                        else
{
                            this.localAI[0] = 0f;
                            int num226 = 4;
                            float num227 = this.velocity.Length();
                            if (num227 > 3f)
{
                                num226 = 3;
                            }
                            if (num227 > 5f)
{
                                num226 = 2;
                            }
                            num2 = this.frameCounter + 1;
                            this.frameCounter = num2;
                            if (num2 > num226)
{
                                this.frame++;
                                if (num226 == 0)
{
                                    this.frame++;
                                }
                                this.frameCounter = 0;
                            }
                            if (this.frame < 13 || this.frame > 18)
{
                                this.frame = 13;
                            }
                        }
                        this.velocity.Y = this.velocity.Y + 0.4f;
                        if (this.velocity.Y > 10f)
{
                            this.velocity.Y = 10f;
                        }
                    }
                    else if (flag6)
                    {
                        if (this.ai[1] > 0f)
{
                            if (this.localAI[1] == 0f)
{
                                this.localAI[1] = 1f;
                                this.frame = 1;
                            }
                            if (this.frame != 0)
{
                                this.frameCounter++;
                                if (this.frameCounter > 4)
{
                                    this.frame++;
                                    this.frameCounter = 0;
                                }
                                if (this.frame >= 4)
{
                                    this.frame = 0;
                                }
                            }
                        }
                        else if (this.velocity.Y == 0f)
{
                            this.localAI[1] = 0f;
                            if (flag33)
{
                                this.frame = 0;
                                this.frameCounter = 0;
                            }
                            else if ((double)this.velocity.X < -0.8 || (double)this.velocity.X > 0.8)
{
                                this.frameCounter += (int)Math.Abs(this.velocity.X);
                                this.frameCounter++;
                                if (this.frameCounter > 6)
{
                                    this.frame++;
                                    this.frameCounter = 0;
                                }
                                if (this.frame < 5 || this.frame >= 11)
{
                                    this.frame = 5;
                                }
                            }
                            else
{
                                this.frame = 0;
                                this.frameCounter = 0;
                            }
                        }
                        else if (this.velocity.Y < 0f)
{
                            this.frameCounter = 0;
                            this.frame = 4;
                        }
                        else if (this.velocity.Y > 0f)
{
                            this.frameCounter = 0;
                            this.frame = 4;
                        }
                        this.velocity.Y = this.velocity.Y + 0.4f;
                        if (this.velocity.Y > 10f)
{
                            this.velocity.Y = 10f;
                        }
                        Vector2 velocity = this.velocity;
                    }
                    else if (this.type == 1094)
                    {
                        if (this.ai[1] > 0f)
{
                            if (this.frame < 36 || this.frame >= 42)
{
                                this.frameCounter = 0;
                                this.frame = 36;
                            }
                            if (this.ai[1] == 40f)
{
                                this.frameCounter = 0;
                            }
                            this.frameCounter++;
                            int num228 = this.frameCounter / 3;
                            if (num228 >= 6)
{
                                num228 = 11 - num228;
                            }
                            if (num228 < 0)
{
                                num228 = 0;
                            }
                            this.frame = 36 + num228;
                            if (this.frame != 36 && this.frameCounter < 10)
{
                                Dust dust9 = Dust.NewDustDirect(base.Bottom + new Vector2((float)(-2 - this.spriteDirection * 16), -8f), 4, 4, 6, (float)(this.spriteDirection * 2), -0.25f, 0, default(Color), 1f);
                                dust9.noGravity = true;
                                dust9.scale = 1.4f;
                                dust9.velocity *= 4f;
                            }
                        }
                        else if (this.velocity.Y == 0f)
{
                            this.localAI[1] = 0f;
                            if (flag33 && flag9)
{
                                if (this.frame < 45 || this.frame >= 53)
{
                                    this.frame = 45;
                                }
                                num2 = this.frameCounter + 1;
                                this.frameCounter = num2;
                                if (num2 >= 4)
{
                                    this.frameCounter = 0;
                                    num2 = this.frame + 1;
                                    this.frame = num2;
                                    if (num2 >= 53)
{
                                        this.frame = 45;
                                    }
                                }
                            }
                            else if (flag33)
{
                                if (this.frame < 18 || this.frame >= 26)
{
                                    this.frame = 18;
                                }
                                num2 = this.frameCounter + 1;
                                this.frameCounter = num2;
                                if (num2 >= 4)
{
                                    this.frameCounter = 0;
                                    num2 = this.frame + 1;
                                    this.frame = num2;
                                    if (num2 >= 26)
{
                                        this.frame = 18;
                                    }
                                }
                            }
                            else if ((double)this.velocity.X < -0.8 || (double)this.velocity.X > 0.8)
{
                                this.frameCounter += (int)Math.Abs(this.velocity.X);
                                this.frameCounter++;
                                if (this.frame < 28 || this.frame >= 36)
{
                                    this.frame = 28;
                                }
                                if (this.frameCounter >= 10)
{
                                    this.frameCounter = 0;
                                    num2 = this.frame + 1;
                                    this.frame = num2;
                                    if (num2 >= 36)
{
                                        this.frame = 28;
                                    }
                                }
                            }
                            else
{
                                this.frame = 18;
                                this.frameCounter = 0;
                            }
                        }
                        else if (this.velocity.Y < 0f)
{
                            this.frameCounter = 0;
                            this.frame = 27;
                        }
                        else if (this.velocity.Y > 0f)
{
                            this.frameCounter = 0;
                            this.frame = 27;
                        }
                        this.velocity.Y = this.velocity.Y + 0.4f;
                        if (this.velocity.Y > 10f)
{
                            this.velocity.Y = 10f;
                        }
                        Vector2 velocity2 = this.velocity;
                    }
                    else if (this.type == 268)
                    {
                        if (this.velocity.Y == 0f)
{
                            if (this.frame > 5)
{
                                this.frameCounter = 0;
                            }
                            if (flag33)
{
                                int num229 = 3;
                                this.frameCounter++;
                                if (this.frameCounter < num229)
{
                                    this.frame = 0;
                                }
                                else if (this.frameCounter < num229 * 2)
{
                                    this.frame = 1;
                                }
                                else if (this.frameCounter < num229 * 3)
{
                                    this.frame = 2;
                                }
                                else if (this.frameCounter < num229 * 4)
{
                                    this.frame = 3;
                                }
                                else
{
                                    this.frameCounter = num229 * 4;
                                }
                            }
                            else
{
                                this.velocity.X = this.velocity.X * 0.8f;
                                this.frameCounter++;
                                int num230 = 3;
                                if (this.frameCounter < num230)
{
                                    this.frame = 0;
                                }
                                else if (this.frameCounter < num230 * 2)
{
                                    this.frame = 1;
                                }
                                else if (this.frameCounter < num230 * 3)
{
                                    this.frame = 2;
                                }
                                else if (this.frameCounter < num230 * 4)
{
                                    this.frame = 3;
                                }
                                else if (flag2 || flag3)
{
                                    this.velocity.X = this.velocity.X * 2f;
                                    this.frame = 4;
                                    this.velocity.Y = -6.1f;
                                    this.frameCounter = 0;
                                    for (int num231 = 0; num231 < 4; num231++)
{
                                        int num232 = Dust.NewDust(new Vector2(this.position.X, this.position.Y + (float)this.height - 2f), this.width, 4, 5, 0f, 0f, 0, default(Color), 1f);
                                        Main.dust[num232].velocity += this.velocity;
                                        Main.dust[num232].velocity *= 0.4f;
                                    }
                                }
                                else
{
                                    this.frameCounter = num230 * 4;
                                }
                            }
                        }
                        else if (this.velocity.Y < 0f)
{
                            this.frameCounter = 0;
                            this.frame = 5;
                        }
                        else
{
                            this.frame = 4;
                            this.frameCounter = 3;
                        }
                        this.velocity.Y = this.velocity.Y + 0.4f;
                        if (this.velocity.Y > 10f)
{
                            this.velocity.Y = 10f;
                        }
                    }
                    else if (this.type == 269)
                    {
                        if (this.velocity.Y >= 0f && (double)this.velocity.Y <= 0.8)
{
                            if (flag33)
{
                                this.frame = 0;
                                this.frameCounter = 0;
                            }
                            else if ((double)this.velocity.X < -0.8 || (double)this.velocity.X > 0.8)
{
                                int num233 = Dust.NewDust(new Vector2(this.position.X, this.position.Y + (float)this.height - 2f), this.width, 6, 76, 0f, 0f, 0, default(Color), 1f);
                                Main.dust[num233].noGravity = true;
                                Main.dust[num233].velocity *= 0.3f;
                                Main.dust[num233].noLight = true;
                                this.frameCounter += (int)Math.Abs(this.velocity.X);
                                this.frameCounter++;
                                if (this.frameCounter > 6)
{
                                    this.frame++;
                                    this.frameCounter = 0;
                                }
                                if (this.frame > 3)
{
                                    this.frame = 0;
                                }
                            }
                            else
{
                                this.frame = 0;
                                this.frameCounter = 0;
                            }
                        }
                        else
{
                            this.frameCounter = 0;
                            this.frame = 2;
                        }
                        this.velocity.Y = this.velocity.Y + 0.4f;
                        if (this.velocity.Y > 10f)
{
                            this.velocity.Y = 10f;
                        }
                    }
                    else if (this.type == 313)
                    {
                        int num234 = (int)(base.Center.X / 16f);
                        int num235 = (int)(base.Center.Y / 16f);
                        int num236 = 0;
                        Tile tileSafely2 = Framing.GetTileSafely(num234, num235);
                        Tile tileSafely3 = Framing.GetTileSafely(num234, num235 - 1);
                        Tile tileSafely4 = Framing.GetTileSafely(num234, num235 + 1);
                        if (tileSafely2.wall > 0)
{
                            num236++;
                        }
                        if (tileSafely3.wall > 0)
{
                            num236++;
                        }
                        if (tileSafely4.wall > 0)
{
                            num236++;
                        }
                        if (num236 > 1)
{
                            this.position.Y = this.position.Y + (float)this.height;
                            this.height = 34;
                            this.position.Y = this.position.Y - (float)this.height;
                            this.position.X = this.position.X + (float)(this.width / 2);
                            this.width = 34;
                            this.position.X = this.position.X - (float)(this.width / 2);
                            float num237 = 4f;
                            Vector2 vector31 = new Vector2(this.position.X + (float)this.width * 0.5f, this.position.Y + (float)this.height * 0.5f);
                            float num238 = Main.player[this.owner].Center.X - vector31.X;
                            float num239 = Main.player[this.owner].Center.Y - vector31.Y;
                            float num240 = (float)Math.Sqrt((double)(num238 * num238 + num239 * num239));
                            float num241 = num237 / num240;
                            num238 *= num241;
                            num239 *= num241;
                            if (num240 < 120f)
{
                                this.velocity.X = this.velocity.X * 0.9f;
                                this.velocity.Y = this.velocity.Y * 0.9f;
                                if ((double)(Math.Abs(this.velocity.X) + Math.Abs(this.velocity.Y)) < 0.1)
{
                                    this.velocity *= 0f;
                                }
                            }
                            else
{
                                this.velocity.X = (this.velocity.X * 9f + num238) / 10f;
                                this.velocity.Y = (this.velocity.Y * 9f + num239) / 10f;
                            }
                            if (num240 >= 120f)
{
                                this.spriteDirection = this.direction;
                                this.rotation = (float)Math.Atan2((double)(this.velocity.Y * (float)(-(float)this.direction)), (double)(this.velocity.X * (float)(-(float)this.direction)));
                            }
                            this.frameCounter += (int)(Math.Abs(this.velocity.X) + Math.Abs(this.velocity.Y));
                            if (this.frameCounter > 6)
{
                                this.frame++;
                                this.frameCounter = 0;
                            }
                            if (this.frame > 10)
{
                                this.frame = 5;
                            }
                            if (this.frame < 5)
{
                                this.frame = 10;
                            }
                        }
                        else
{
                            this.rotation = 0f;
                            if (this.direction == -1)
{
                                this.spriteDirection = 1;
                            }
                            if (this.direction == 1)
{
                                this.spriteDirection = -1;
                            }
                            this.position.Y = this.position.Y + (float)this.height;
                            this.height = 30;
                            this.position.Y = this.position.Y - (float)this.height;
                            this.position.X = this.position.X + (float)(this.width / 2);
                            this.width = 30;
                            this.position.X = this.position.X - (float)(this.width / 2);
                            if (this.velocity.Y >= 0f && (double)this.velocity.Y <= 0.8)
{
                                if (flag33)
{
                                    this.frame = 0;
                                    this.frameCounter = 0;
                                }
                                else if ((double)this.velocity.X < -0.8 || (double)this.velocity.X > 0.8)
{
                                    this.frameCounter += (int)Math.Abs(this.velocity.X);
                                    this.frameCounter++;
                                    if (this.frameCounter > 6)
{
                                        this.frame++;
                                        this.frameCounter = 0;
                                    }
                                    if (this.frame > 3)
{
                                        this.frame = 0;
                                    }
                                }
                                else
{
                                    this.frame = 0;
                                    this.frameCounter = 0;
                                }
                            }
                            else
{
                                this.frameCounter = 0;
                                this.frame = 4;
                            }
                            this.velocity.Y = this.velocity.Y + 0.4f;
                            if (this.velocity.Y > 10f)
{
                                this.velocity.Y = 10f;
                            }
                        }
                    }
                    else if (flag7)
                    {
                        int num242 = (int)(base.Center.X / 16f);
                        int num243 = (int)(base.Center.Y / 16f);
                        int num244 = 0;
                        Tile tileSafely5 = Framing.GetTileSafely(num242, num243);
                        Tile tileSafely6 = Framing.GetTileSafely(num242, num243 - 1);
                        Tile tileSafely7 = Framing.GetTileSafely(num242, num243 + 1);
                        if (tileSafely5.wall > 0)
{
                            num244++;
                        }
                        if (tileSafely6.wall > 0)
{
                            num244++;
                        }
                        if (tileSafely7.wall > 0)
{
                            num244++;
                        }
                        if (num244 > 1)
{
                            float num245 = 9f;
                            float num246 = (float)(40 * (this.minionPos + 1));
                            Vector2 vector32 = Main.player[this.owner].Center - base.Center;
                            if (flag29)
{
                                vector32 = vector28;
                                num246 = 10f;
                            }
                            if (vector32.Length() < num246)
{
                                this.velocity *= 0.9f;
                                if ((double)(Math.Abs(this.velocity.X) + Math.Abs(this.velocity.Y)) < 0.1)
{
                                    this.velocity *= 0f;
                                }
                            }
                            else if (vector32.Length() < 800f || !flag29)
{
                                this.velocity = (this.velocity * 9f + vector32.SafeNormalize(Vector2.Zero) * num245) / 10f;
                            }
                            if (vector32.Length() >= num246)
{
                                this.spriteDirection = this.direction;
                                this.rotation = this.velocity.ToRotation() + 1.5707964f;
                            }
                            else
{
                                this.rotation = vector32.ToRotation() + 1.5707964f;
                            }
                            this.frameCounter += (int)(Math.Abs(this.velocity.X) + Math.Abs(this.velocity.Y));
                            if (this.frameCounter > 8)
{
                                this.frame++;
                                this.frameCounter = 0;
                            }
                            if (this.frame > 7)
{
                                this.frame = 4;
                            }
                            if (this.frame < 4)
{
                                this.frame = 7;
                            }
                        }
                        else
{
                            if (!flag30)
{
                                this.rotation = 0f;
                            }
                            this.spriteDirection = -this.direction;
                            if (!flag30 && this.frame >= 4 && this.frame <= 7)
{
                                Vector2 vector33 = Main.player[this.owner].Center - base.Center;
                                if (flag29)
{
                                    vector33 = vector28;
                                }
                                float num247 = -vector33.Y;
                                if (vector33.Y <= 0f)
{
                                    if (num247 < 120f)
{
                                        this.velocity.Y = -10f;
                                    }
                                    else if (num247 < 210f)
{
                                        this.velocity.Y = -13f;
                                    }
                                    else if (num247 < 270f)
{
                                        this.velocity.Y = -15f;
                                    }
                                    else if (num247 < 310f)
{
                                        this.velocity.Y = -17f;
                                    }
                                    else if (num247 < 380f)
{
                                        this.velocity.Y = -18f;
                                    }
                                }
                            }
                            if (flag30)
{
                                this.frameCounter++;
                                if (this.frameCounter > 4)
{
                                    this.frame++;
                                    this.frameCounter = 0;
                                }
                                if (this.frame >= 8)
{
                                    this.frame = 4;
                                }
                                if (this.frame <= 3)
{
                                    this.frame = 7;
                                }
                            }
                            else if (this.velocity.Y >= 0f && this.velocity.Y <= 0.8f)
{
                                if (flag33)
{
                                    this.frame = 0;
                                    this.frameCounter = 0;
                                }
                                else if (this.velocity.X < -0.8f || this.velocity.X > 0.8f)
{
                                    this.frameCounter += (int)Math.Abs(this.velocity.X);
                                    this.frameCounter++;
                                    if (this.frameCounter > 8)
{
                                        this.frame++;
                                        this.frameCounter = 0;
                                    }
                                    if (this.frame > 2)
{
                                        this.frame = 0;
                                    }
                                }
                                else
{
                                    this.frame = 0;
                                    this.frameCounter = 0;
                                }
                            }
                            else
{
                                this.frameCounter = 0;
                                this.frame = 3;
                            }
                            this.velocity.Y = this.velocity.Y + 0.4f;
                            if (this.velocity.Y > 10f)
{
                                this.velocity.Y = 10f;
                            }
                        }
                    }
                    else if (this.type == 314)
                    {
                        if (this.velocity.Y >= 0f && (double)this.velocity.Y <= 0.8)
{
                            if (flag33)
{
                                this.frame = 0;
                                this.frameCounter = 0;
                            }
                            else if ((double)this.velocity.X < -0.8 || (double)this.velocity.X > 0.8)
{
                                this.frameCounter += (int)Math.Abs(this.velocity.X);
                                this.frameCounter++;
                                if (this.frameCounter > 6)
{
                                    this.frame++;
                                    this.frameCounter = 0;
                                }
                                if (this.frame > 6)
{
                                    this.frame = 1;
                                }
                            }
                            else
{
                                this.frame = 0;
                                this.frameCounter = 0;
                            }
                        }
                        else
{
                            this.frameCounter = 0;
                            this.frame = 7;
                        }
                        this.velocity.Y = this.velocity.Y + 0.4f;
                        if (this.velocity.Y > 10f)
{
                            this.velocity.Y = 10f;
                        }
                    }
                    else if (this.type == 319)
                    {
                        if (this.velocity.Y >= 0f && (double)this.velocity.Y <= 0.8)
{
                            if (flag33)
{
                                this.frame = 0;
                                this.frameCounter = 0;
                            }
                            else if ((double)this.velocity.X < -0.8 || (double)this.velocity.X > 0.8)
{
                                this.frameCounter += (int)Math.Abs(this.velocity.X);
                                this.frameCounter++;
                                if (this.frameCounter > 8)
{
                                    this.frame++;
                                    this.frameCounter = 0;
                                }
                                if (this.frame > 5)
{
                                    this.frame = 2;
                                }
                            }
                            else
{
                                this.frame = 0;
                                this.frameCounter = 0;
                            }
                        }
                        else
{
                            this.frameCounter = 0;
                            this.frame = 1;
                        }
                        this.velocity.Y = this.velocity.Y + 0.4f;
                        if (this.velocity.Y > 10f)
{
                            this.velocity.Y = 10f;
                        }
                    }
                    else if (this.type == 236)
                    {
                        if (this.velocity.Y >= 0f && (double)this.velocity.Y <= 0.8)
{
                            if (flag33)
{
                                this.frame = 0;
                                this.frameCounter = 0;
                            }
                            else if ((double)this.velocity.X < -0.8 || (double)this.velocity.X > 0.8)
{
                                if (this.frame < 2)
{
                                    this.frame = 2;
                                }
                                this.frameCounter += (int)Math.Abs(this.velocity.X);
                                this.frameCounter++;
                                if (this.frameCounter > 6)
{
                                    this.frame++;
                                    this.frameCounter = 0;
                                }
                                if (this.frame > 8)
{
                                    this.frame = 2;
                                }
                            }
                            else
{
                                this.frame = 0;
                                this.frameCounter = 0;
                            }
                        }
                        else
{
                            this.frameCounter = 0;
                            this.frame = 1;
                        }
                        this.velocity.Y = this.velocity.Y + 0.4f;
                        if (this.velocity.Y > 10f)
{
                            this.velocity.Y = 10f;
                        }
                    }
                    else if (this.type == 499)
                    {
                        if (this.velocity.Y >= 0f && (double)this.velocity.Y <= 0.8)
{
                            if (flag33)
{
                                this.frame = 0;
                                this.frameCounter = 0;
                            }
                            else if ((double)this.velocity.X < -0.8 || (double)this.velocity.X > 0.8)
{
                                if (this.frame < 2)
{
                                    this.frame = 2;
                                }
                                this.frameCounter += (int)Math.Abs(this.velocity.X);
                                this.frameCounter++;
                                if (this.frameCounter > 6)
{
                                    this.frame++;
                                    this.frameCounter = 0;
                                }
                                if (this.frame >= 8)
{
                                    this.frame = 2;
                                }
                            }
                            else
{
                                this.frame = 0;
                                this.frameCounter = 0;
                            }
                        }
                        else
{
                            this.frameCounter = 0;
                            this.frame = 1;
                        }
                        this.velocity.Y = this.velocity.Y + 0.4f;
                        if (this.velocity.Y > 10f)
{
                            this.velocity.Y = 10f;
                        }
                    }
                    else if (this.type == 765)
                    {
                        if (this.velocity.Y >= 0f && (double)this.velocity.Y <= 0.8)
{
                            if (flag33)
{
                                this.frame = 0;
                                this.frameCounter = 0;
                            }
                            else if ((double)this.velocity.X < -0.8 || (double)this.velocity.X > 0.8)
{
                                if (this.frame < 1)
{
                                    this.frame = 1;
                                }
                                this.frameCounter += (int)Math.Abs(this.velocity.X);
                                this.frameCounter++;
                                if (this.frameCounter > 6)
{
                                    this.frame++;
                                    this.frameCounter = 0;
                                }
                                if (this.frame >= 6)
{
                                    this.frame = 1;
                                }
                            }
                            else
{
                                this.frame = 0;
                                this.frameCounter = 0;
                            }
                        }
                        else
{
                            this.frame = 0;
                            this.frameCounter = 0;
                        }
                        this.velocity.Y = this.velocity.Y + 0.4f;
                        if (this.velocity.Y > 10f)
{
                            this.velocity.Y = 10f;
                        }
                    }
                    else if (this.type == 266)
                    {
                        if (this.velocity.Y != 0f)
{
                            this.frameCounter++;
                            if (this.frameCounter > 4)
{
                                this.frameCounter = 0;
                                this.frame++;
                            }
                            if (this.frame == 0 || this.frame >= 8)
{
                                this.frame = 1;
                            }
                        }
                        else
{
                            if (flag33)
{
                                this.spriteDirection = -1;
                                if (Main.player[this.owner].Center.X < base.Center.X)
{
                                    this.spriteDirection = 1;
                                }
                            }
                            this.frameCounter++;
                            if (this.frameCounter > 7)
{
                                this.frameCounter = 0;
                                this.frame++;
                                if (this.frame == 1)
{
                                    this.frame = 5;
                                }
                            }
                            if ((this.frame >= 1 && this.frame <= 4) || this.frame >= 8)
{
                                this.frame = 0;
                            }
                        }
                        if (this.wet && Main.player[this.owner].position.Y + (float)Main.player[this.owner].height < this.position.Y + (float)this.height && this.localAI[0] == 0f)
{
                            if (this.velocity.Y > -4f)
{
                                this.velocity.Y = this.velocity.Y - 0.2f;
                            }
                            if (this.velocity.Y > 0f)
{
                                this.velocity.Y = this.velocity.Y * 0.95f;
                            }
                        }
                        else
{
                            this.velocity.Y = this.velocity.Y + 0.4f;
                        }
                        if (this.velocity.Y > 10f)
{
                            this.velocity.Y = 10f;
                        }
                    }
                    else if (this.type == 334)
                    {
                        if (this.velocity.Y == 0f)
{
                            if (flag33)
{
                                if (this.frame > 0)
{
                                    this.frameCounter += 2;
                                    if (this.frameCounter > 6)
{
                                        this.frame++;
                                        this.frameCounter = 0;
                                    }
                                    if (this.frame >= 7)
{
                                        this.frame = 0;
                                    }
                                }
                                else
{
                                    this.frame = 0;
                                    this.frameCounter = 0;
                                }
                            }
                            else if ((double)this.velocity.X < -0.8 || (double)this.velocity.X > 0.8)
{
                                this.frameCounter += (int)Math.Abs((double)this.velocity.X * 0.75);
                                this.frameCounter++;
                                if (this.frameCounter > 6)
{
                                    this.frame++;
                                    this.frameCounter = 0;
                                }
                                if (this.frame >= 7 || this.frame < 1)
{
                                    this.frame = 1;
                                }
                            }
                            else if (this.frame > 0)
{
                                this.frameCounter += 2;
                                if (this.frameCounter > 6)
{
                                    this.frame++;
                                    this.frameCounter = 0;
                                }
                                if (this.frame >= 7)
{
                                    this.frame = 0;
                                }
                            }
                            else
{
                                this.frame = 0;
                                this.frameCounter = 0;
                            }
                        }
                        else if (this.velocity.Y < 0f)
{
                            this.frameCounter = 0;
                            this.frame = 2;
                        }
                        else if (this.velocity.Y > 0f)
{
                            this.frameCounter = 0;
                            this.frame = 4;
                        }
                        this.velocity.Y = this.velocity.Y + 0.4f;
                        if (this.velocity.Y > 10f)
{
                            this.velocity.Y = 10f;
                        }
                    }
                    else if (this.type == 353)
                    {
                        if (this.velocity.Y == 0f)
{
                            if (flag33)
{
                                this.frame = 0;
                                this.frameCounter = 0;
                            }
                            else if ((double)this.velocity.X < -0.8 || (double)this.velocity.X > 0.8)
{
                                this.frameCounter += (int)Math.Abs(this.velocity.X);
                                this.frameCounter++;
                                if (this.frameCounter > 6)
{
                                    this.frame++;
                                    this.frameCounter = 0;
                                }
                                if (this.frame > 9)
{
                                    this.frame = 2;
                                }
                            }
                            else
{
                                this.frame = 0;
                                this.frameCounter = 0;
                            }
                        }
                        else if (this.velocity.Y < 0f)
{
                            this.frameCounter = 0;
                            this.frame = 1;
                        }
                        else if (this.velocity.Y > 0f)
{
                            this.frameCounter = 0;
                            this.frame = 1;
                        }
                        this.velocity.Y = this.velocity.Y + 0.4f;
                        if (this.velocity.Y > 10f)
{
                            this.velocity.Y = 10f;
                        }
                    }
                    else if (this.type == 111)
                    {
                        if (this.velocity.Y == 0f)
{
                            if (flag33)
{
                                this.frame = 0;
                                this.frameCounter = 0;
                            }
                            else if ((double)this.velocity.X < -0.8 || (double)this.velocity.X > 0.8)
{
                                this.frameCounter += (int)Math.Abs(this.velocity.X);
                                this.frameCounter++;
                                if (this.frameCounter > 6)
{
                                    this.frame++;
                                    this.frameCounter = 0;
                                }
                                if (this.frame >= 7)
{
                                    this.frame = 0;
                                }
                            }
                            else
{
                                this.frame = 0;
                                this.frameCounter = 0;
                            }
                        }
                        else if (this.velocity.Y < 0f)
{
                            this.frameCounter = 0;
                            this.frame = 4;
                        }
                        else if (this.velocity.Y > 0f)
{
                            this.frameCounter = 0;
                            this.frame = 6;
                        }
                        this.velocity.Y = this.velocity.Y + 0.4f;
                        if (this.velocity.Y > 10f)
{
                            this.velocity.Y = 10f;
                        }
                    }
                    else if (this.type == 112)
                    {
                        if (this.velocity.Y == 0f)
{
                            if (flag33)
{
                                this.frame = 0;
                                this.frameCounter = 0;
                            }
                            else if ((double)this.velocity.X < -0.8 || (double)this.velocity.X > 0.8)
{
                                this.frameCounter += (int)Math.Abs(this.velocity.X);
                                this.frameCounter++;
                                if (this.frameCounter > 6)
{
                                    this.frame++;
                                    this.frameCounter = 0;
                                }
                                if (this.frame >= 3)
{
                                    this.frame = 0;
                                }
                            }
                            else
{
                                this.frame = 0;
                                this.frameCounter = 0;
                            }
                        }
                        else if (this.velocity.Y != 0f)
{
                            this.frameCounter = 0;
                            this.frame = 1;
                        }
                        this.velocity.Y = this.velocity.Y + 0.4f;
                        if (this.velocity.Y > 10f)
{
                            this.velocity.Y = 10f;
                        }
                    }
                    else if (this.type == 127)
                    {
                        if (this.velocity.Y == 0f)
{
                            if (flag33)
{
                                this.frame = 0;
                                this.frameCounter = 0;
                            }
                            else if ((double)this.velocity.X < -0.1 || (double)this.velocity.X > 0.1)
{
                                this.frameCounter += (int)Math.Abs(this.velocity.X);
                                this.frameCounter++;
                                if (this.frameCounter > 6)
{
                                    this.frame++;
                                    this.frameCounter = 0;
                                }
                                if (this.frame > 5)
{
                                    this.frame = 0;
                                }
                            }
                            else
{
                                this.frame = 0;
                                this.frameCounter = 0;
                            }
                        }
                        else
{
                            this.frame = 0;
                            this.frameCounter = 0;
                        }
                        this.velocity.Y = this.velocity.Y + 0.4f;
                        if (this.velocity.Y > 10f)
{
                            this.velocity.Y = 10f;
                        }
                    }
                    else if (this.type == 200)
                    {
                        if (this.velocity.Y == 0f)
{
                            if (flag33)
{
                                this.frame = 0;
                                this.frameCounter = 0;
                            }
                            else if ((double)this.velocity.X < -0.1 || (double)this.velocity.X > 0.1)
{
                                this.frameCounter += (int)Math.Abs(this.velocity.X);
                                this.frameCounter++;
                                if (this.frameCounter > 6)
{
                                    this.frame++;
                                    this.frameCounter = 0;
                                }
                                if (this.frame > 5)
{
                                    this.frame = 0;
                                }
                            }
                            else
{
                                this.frame = 0;
                                this.frameCounter = 0;
                            }
                        }
                        else
{
                            this.rotation = this.velocity.X * 0.1f;
                            this.frameCounter++;
                            if (this.velocity.Y < 0f)
{
                                this.frameCounter += 2;
                            }
                            if (this.frameCounter > 6)
{
                                this.frame++;
                                this.frameCounter = 0;
                            }
                            if (this.frame > 9)
{
                                this.frame = 6;
                            }
                            if (this.frame < 6)
{
                                this.frame = 6;
                            }
                        }
                        this.velocity.Y = this.velocity.Y + 0.1f;
                        if (this.velocity.Y > 4f)
{
                            this.velocity.Y = 4f;
                        }
                    }
                    else if (this.type == 208)
                    {
                        if (this.velocity.Y == 0f && flag33)
{
                            if (Main.player[this.owner].position.X + (float)(Main.player[this.owner].width / 2) < this.position.X + (float)(this.width / 2))
{
                                this.direction = -1;
                            }
                            else if (Main.player[this.owner].position.X + (float)(Main.player[this.owner].width / 2) > this.position.X + (float)(this.width / 2))
{
                                this.direction = 1;
                            }
                            this.rotation = 0f;
                            this.frame = 0;
                        }
                        else
{
                            this.rotation = this.velocity.X * 0.075f;
                            this.frameCounter++;
                            if (this.frameCounter > 6)
{
                                this.frame++;
                                this.frameCounter = 0;
                            }
                            if (this.frame > 4)
{
                                this.frame = 1;
                            }
                            if (this.frame < 1)
{
                                this.frame = 1;
                            }
                        }
                        this.velocity.Y = this.velocity.Y + 0.1f;
                        if (this.velocity.Y > 4f)
{
                            this.velocity.Y = 4f;
                        }
                    }
                    else if (this.type == 209)
                    {
                        if (this.alpha > 0)
{
                            this.alpha -= 5;
                            if (this.alpha < 0)
{
                                this.alpha = 0;
                            }
                        }
                        if (this.velocity.Y == 0f)
{
                            if (flag33)
{
                                this.frame = 0;
                                this.frameCounter = 0;
                            }
                            else if ((double)this.velocity.X < -0.1 || (double)this.velocity.X > 0.1)
{
                                this.frameCounter += (int)Math.Abs(this.velocity.X);
                                this.frameCounter++;
                                if (this.frameCounter > 6)
{
                                    this.frame++;
                                    this.frameCounter = 0;
                                }
                                if (this.frame > 11)
{
                                    this.frame = 2;
                                }
                                if (this.frame < 2)
{
                                    this.frame = 2;
                                }
                            }
                            else
{
                                this.frame = 0;
                                this.frameCounter = 0;
                            }
                        }
                        else
{
                            this.frame = 1;
                            this.frameCounter = 0;
                            this.rotation = 0f;
                        }
                        this.velocity.Y = this.velocity.Y + 0.4f;
                        if (this.velocity.Y > 10f)
{
                            this.velocity.Y = 10f;
                        }
                    }
                    else if (this.type == 324)
                    {
                        if (this.velocity.Y == 0f)
{
                            if ((double)this.velocity.X < -0.1 || (double)this.velocity.X > 0.1)
{
                                this.frameCounter += (int)Math.Abs(this.velocity.X);
                                this.frameCounter++;
                                if (this.frameCounter > 6)
{
                                    this.frame++;
                                    this.frameCounter = 0;
                                }
                                if (this.frame > 5)
{
                                    this.frame = 2;
                                }
                                if (this.frame < 2)
{
                                    this.frame = 2;
                                }
                            }
                            else
{
                                this.frame = 0;
                                this.frameCounter = 0;
                            }
                        }
                        else
{
                            this.frameCounter = 0;
                            this.frame = 1;
                        }
                        this.velocity.Y = this.velocity.Y + 0.4f;
                        if (this.velocity.Y > 14f)
{
                            this.velocity.Y = 14f;
                        }
                    }
                    else if (this.type == 210)
                    {
                        if (this.velocity.Y == 0f)
{
                            if ((double)this.velocity.X < -0.1 || (double)this.velocity.X > 0.1)
{
                                this.frameCounter += (int)Math.Abs(this.velocity.X);
                                this.frameCounter++;
                                if (this.frameCounter > 6)
{
                                    this.frame++;
                                    this.frameCounter = 0;
                                }
                                if (this.frame > 6)
{
                                    this.frame = 0;
                                }
                            }
                            else
{
                                this.frame = 0;
                                this.frameCounter = 0;
                            }
                        }
                        else
{
                            this.rotation = this.velocity.X * 0.05f;
                            this.frameCounter++;
                            if (this.frameCounter > 6)
{
                                this.frame++;
                                this.frameCounter = 0;
                            }
                            if (this.frame > 11)
{
                                this.frame = 7;
                            }
                            if (this.frame < 7)
{
                                this.frame = 7;
                            }
                        }
                        this.velocity.Y = this.velocity.Y + 0.4f;
                        if (this.velocity.Y > 10f)
{
                            this.velocity.Y = 10f;
                        }
                    }
                    else if (this.type == 398)
                    {
                        if (this.velocity.Y == 0f)
{
                            if (flag33)
{
                                this.frame = 0;
                                this.frameCounter = 0;
                            }
                            else if ((double)this.velocity.X < -0.8 || (double)this.velocity.X > 0.8)
{
                                this.frameCounter += (int)Math.Abs(this.velocity.X);
                                this.frameCounter++;
                                if (this.frameCounter > 10)
{
                                    this.frame++;
                                    this.frameCounter = 0;
                                }
                                if (this.frame > 6)
{
                                    this.frame = 0;
                                }
                            }
                            else
{
                                this.frame = 0;
                                this.frameCounter = 0;
                            }
                        }
                        else if (this.velocity.Y != 0f)
{
                            this.frameCounter = 0;
                            this.frame = 5;
                        }
                        this.velocity.Y = this.velocity.Y + 0.4f;
                        if (this.velocity.Y > 10f)
{
                            this.velocity.Y = 10f;
                        }
                    }
                }
                if (this.type == 891)
                {
                    Player player7 = Main.player[this.owner];
                    DelegateMethods.v3_1 = new Vector3(1f, 0.61f, 0.16f) * 1.5f;
                    Utils.PlotTileLine(base.Center, base.Center + this.velocity * 6f, 20f, new Utils.TileActionAttempt(DelegateMethods.CastLightOpen));
                    Utils.PlotTileLine(base.Left, base.Right, 20f, new Utils.TileActionAttempt(DelegateMethods.CastLightOpen));
                }
            }
        }
References System.Math.Abs(), Terraria.Mount.Active, Terraria.Player.active, Terraria.Tile.active(), Terraria.Lighting.AddLight(), Terraria.Graphics.Shaders.GameShaders.Armor, System.array, System.Math.Atan2(), Terraria.Player.babyFaceMonster, Terraria.Player.blackCat, Terraria.Player.bunny, Terraria.NPC.CanBeChasedBy(), Terraria.Mount.CanFly(), Terraria.Collision.CanHit(), Terraria.DelegateMethods.CastLightOpen(), Terraria.Player.CCed, Terraria.Entity.Center, Terraria.Player.ChangeDir(), Terraria.Player.channel, Microsoft.Xna.Framework.MathHelper.Clamp(), Terraria.Player.cLight, Terraria.ID.TileID.Sets.ForAdvancedCollision.ClosedDoors, Terraria.Player.controlDown, Terraria.Player.controlLeft, Terraria.Player.controlRight, Terraria.Player.controlUp, Terraria.Player.cSapling, Terraria.Player.dead, Terraria.Player.dino, Terraria.Entity.direction, Microsoft.Xna.Framework.Vector2.Dot(), Terraria.Main.dust, Terraria.Player.eater, Terraria.Player.eyeSpring, Terraria.Dust.fadeIn, Terraria.Utils.GetLerpValue(), Terraria.Graphics.Shaders.ArmorShaderDataSet.GetSecondaryShader(), Terraria.Framing.GetTileSafely(), Terraria.Player.gfxOffY, Terraria.Main.gore, Terraria.Player.gravDir, Terraria.Player.grinch, Terraria.Tile.halfBrick(), Terraria.Entity.height, Terraria.Player.hornet, int, Microsoft.Xna.Framework.Rectangle.Intersects(), Terraria.Player.inventory, Terraria.WorldGen.InWorld(), Terraria.GameContent.PlayerPettingInfo.isPetting, Microsoft.Xna.Framework.Vector2.Length(), Microsoft.Xna.Framework.Vector2.Lerp(), Terraria.Tile.liquid, Terraria.Player.lizard, System.Math.Max(), Terraria.Main.maxNPCs, Terraria.Player.miniMinotaur, Terraria.Player.miscCounter, Terraria.Player.mount, Terraria.Player.MountedCenter, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Dust.NewDust(), Terraria.Dust.NewDustDirect(), Terraria.Dust.NewDustPerfect(), Terraria.Gore.NewGore(), Terraria.Gore.NewGorePerfect(), Terraria.Projectile.NewProjectile(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Terraria.Player.noItems, Terraria.Dust.noLight, Terraria.Dust.noLightEmittance, Microsoft.Xna.Framework.Vector2.Normalize(), Terraria.Main.npc, Terraria.Player.ownedProjectileCounts, Terraria.Projectile.owner, Terraria.ID.SoundID.PalFoxparks, Terraria.ID.SoundID.PalFoxparksJoy, Terraria.ID.SoundID.PalSummon, Terraria.Player.palworldFoxsparksMinion, Terraria.Player.parrot, Terraria.Player.penguin, Terraria.Player.petFlagBabyImp, Terraria.Player.petFlagBabyRedPanda, Terraria.Player.petFlagBabyShark, Terraria.Player.petFlagBabyWerewolf, Terraria.Player.petFlagBerniePet, Terraria.Player.petFlagBlueChickenPet, Terraria.Player.petFlagBrainOfCthulhuPet, Terraria.Player.petFlagCaveling, Terraria.Player.petFlagChesterPet, Terraria.Player.petFlagChillet, Terraria.Player.petFlagChilletIgnis, Terraria.Player.petFlagDD2BetsyPet, Terraria.Player.petFlagDD2OgrePet, Terraria.Player.petFlagDeadCellsSwarmBiter, Terraria.Player.petFlagDeerclopsPet, Terraria.Player.petFlagDukeFishronPet, Terraria.Player.petFlagDynamiteKitten, Terraria.Player.petFlagEverscreamPet, Terraria.Player.petFlagFennecFox, Terraria.Player.petFlagGlitteryButterfly, Terraria.Player.petFlagGolemPet, Terraria.Player.petFlagJunimoPet, Terraria.Player.petFlagKingSlimePet, Terraria.Player.petFlagLilHarpy, Terraria.Player.petFlagMartianPet, Terraria.Player.petFlagMoonLordPet, Terraria.Player.petFlagPigPet, Terraria.Player.petFlagPlanteraPet, Terraria.Player.petFlagPlantero, Terraria.Player.petFlagPufferfish, Terraria.Player.petFlagQueenBeePet, Terraria.Player.petFlagQueenSlimePet, Terraria.Player.petFlagShadowMimic, Terraria.Player.petFlagSkeletronPet, Terraria.Player.petFlagSkeletronPrimePet, Terraria.Player.petFlagSpiffo, Terraria.Player.petFlagSugarGlider, Terraria.Player.petFlagVoltBunny, Terraria.Player.petting, Terraria.ID.TileID.Sets.Platforms, Terraria.Main.player, Terraria.ID.MountID.Sets.PlayerIsHidden, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Utils.PlotTileLine(), Terraria.Dust.position, Terraria.Entity.position, Terraria.GameContent.PlayerPettingInfo.proj, Terraria.Main.projectile, Terraria.Main.projFrames, Terraria.Player.puppy, Terraria.Player.pygmy, Terraria.Main.rand, Terraria.Player.RotatedRelativePoint(), Terraria.Player.sapling, Terraria.Dust.scale, Terraria.Main.screenHeight, Terraria.Player.selectedItem, Terraria.Player.SetDummyItemTime(), Terraria.Dust.shader, Terraria.Item.shootSpeed, System.Math.Sign(), System.Math.Sin(), Terraria.Player.skeletron, Terraria.Player.slime, Terraria.Tile.slope(), Terraria.Player.snowman, Terraria.Collision.SolidCollision(), Terraria.WorldGen.SolidTile(), Terraria.WorldGen.SolidTileAllowBottomSlope(), Terraria.Player.spider, Terraria.Player.spiderMinion, System.Math.Sqrt(), Terraria.Player.squashling, Terraria.Collision.StepUp(), Terraria.Player.tiki, Terraria.Main.tile, Terraria.Utils.TileActionAttempt(), Terraria.Projectile.timeLeft, Terraria.Player.truffle, Terraria.Player.turtle, Terraria.Mount.Type, Terraria.Projectile.type, Terraria.Tile.type, Microsoft.Xna.Framework.Vector2.UnitX, Microsoft.Xna.Framework.Vector2.UnitY, Terraria.Dust.velocity, Terraria.Entity.velocity, Terraria.Gore.velocity, Terraria.Tile.wall, Terraria.Entity.whoAmI, Terraria.Entity.width, Terraria.Player.wisp, Microsoft.Xna.Framework.MathHelper.WrapAngle(), Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, Terraria.Player.zephyrfish, and Microsoft.Xna.Framework.Vector2.Zero.