Terraria Decompiled: Terraria.Projectile.AI_113_TargetSticker
AI_113_TargetSticker()
void Terraria.Projectile.AI_113_TargetSticker () inline private
Definition at line 40858 of file Projectile.cs.
        {
            int num = 25;
            if (this.type == 614)
            {
                num = 63;
            }
            if (this.alpha > 0)
            {
                this.alpha -= num;
            }
            if (this.alpha < 0)
            {
                this.alpha = 0;
            }
            if (this.ai[0] == 0f)
            {
                if (this.type == 1024)
                {
                    this.frameCounter++;
                    if (this.frameCounter > 3)
                    {
                        this.frameCounter = 0;
                        this.frame++;
                        if (this.frame >= Main.projFrames[this.type])
{
                            this.frame = 0;
                        }
                    }
                }
                if (this.type == 614)
                {
                    int num2 = (int)this.ai[1];
                    if (!Main.npc[num2].CanBeChasedBy(this, false))
                    {
                        this.Kill();
                        return;
                    }
                    this.velocity.ToRotation();
                    Vector2 vector = Main.npc[num2].Center - base.Center;
                    if (vector != Vector2.Zero)
                    {
                        vector.Normalize();
                        vector *= 14f;
                    }
                    float num3 = 5f;
                    this.velocity = (this.velocity * (num3 - 1f) + vector) / num3;
                }
                else
                {
                    this.ai[1] += 1f;
                    int num4 = 45;
                    if (this.type == 1024)
                    {
                        num4 = 60;
                    }
                    if (this.ai[1] >= (float)num4)
                    {
                        float num5 = 0.98f;
                        float num6 = 0.35f;
                        if (this.type == 636)
{
                            num5 = 0.995f;
                            num6 = 0.15f;
                        }
                        this.velocity.X = this.velocity.X * num5;
                        this.velocity.Y = this.velocity.Y + num6;
                    }
                    if (this.type == 1024)
                    {
                        if (this.velocity.Y > 12f)
{
                            this.velocity.Y = 12f;
                        }
                        if (this.ai[1] == 1f)
{
                            this.frame = Main.rand.Next(Main.projFrames[this.type]);
                            for (int i = 0; i < 6; i++)
{
                                Dust dust = Dust.NewDustDirect(this.position, this.width, this.height, 306, 0f, 0f, 0, Color.Transparent, 0.8f + Main.rand.NextFloat() * 1.7f);
                                dust.velocity = this.velocity.SafeNormalize(Vector2.Zero).RotatedBy((double)this.ai[2] * 3.141592653589793 * 0.10000000149011612, default(Vector2)) * 8f * (0.1f + Main.rand.NextFloat() * 1.2f);
                                dust.color = Color.Lerp(Color.White, new Color(140, 234, 180), (float)i / 10f);
                                dust.noGravity = true;
                            }
                        }
                    }
                    this.rotation = this.velocity.ToRotation() + 1.5707964f;
                    if (this.type == 1024)
                    {
                        this.rotation -= 1.5707964f;
                    }
                    if (this.type == 1024)
                    {
                        float num7 = 0.10471976f;
                        float num8 = 40f * this.ai[2];
                        double num9 = (double)(num8 * num7 * num7) * -Math.Sin((double)(this.ai[1] * num7));
                        if (this.ai[1] == 1f)
{
                            num9 += (double)(num8 * num7);
                        }
                        this.velocity += Vector2.UnitY.RotatedBy((double)this.rotation, default(Vector2)) * (float)num9;
                    }
                }
            }
            if (this.ai[0] == 1f)
            {
                this.frame = 0;
                int num10 = -1;
                Vector2 center = base.Center;
                this.ignoreWater = true;
                this.tileCollide = false;
                int num11 = 15;
                if (this.type == 636)
                {
                    num11 = 5 * this.MaxUpdates;
                }
                if (this.type == 971)
                {
                    num11 = 9 * this.MaxUpdates;
                }
                if (this.type == 975)
                {
                    num11 = 9 * this.MaxUpdates;
                }
                if (this.type == 1024)
                {
                    num11 = 5 * this.MaxUpdates;
                }
                if (this.type == 1024 && this.localAI[0] == 0f)
                {
                    for (int j = 0; j < 12; j++)
                    {
                        Dust dust2 = Dust.NewDustDirect(this.position, this.width, this.height, 306, 0f, 0f, 0, Color.Transparent, 0.8f + Main.rand.NextFloat() * 1.7f);
                        dust2.velocity = this.velocity.SafeNormalize(Vector2.Zero).RotatedBy((double)(6.2831855f * (float)j / 12f), default(Vector2)) * 8f * (0.1f + Main.rand.NextFloat() * 1.2f);
                        dust2.color = Color.Lerp(Color.White, new Color(140, 234, 180), (float)j / 10f);
                        dust2.noGravity = true;
                    }
                }
                bool flag = false;
                bool flag2 = false;
                this.localAI[0] += 1f;
                if (this.localAI[0] % 30f == 0f)
                {
                    flag2 = true;
                }
                if (this.type == 1024)
                {
                    flag2 = false;
                }
                int num12 = (int)this.ai[1];
                bool flag3 = this.type == 1024;
                bool flag4 = this.type == 1024;
                if (flag3 && num12 == num10)
                {
                    bool flag5 = false;
                    try
                    {
                        int num13 = (int)MathHelper.Clamp((float)((int)(this.position.X / 16f) - 1), 0f, (float)Main.maxTilesX);
                        int num14 = (int)MathHelper.Clamp((float)((int)((this.position.X + (float)this.width) / 16f) + 2), 0f, (float)Main.maxTilesX);
                        int num15 = (int)MathHelper.Clamp((float)((int)(this.position.Y / 16f) - 1), 0f, (float)Main.maxTilesY);
                        int num16 = (int)MathHelper.Clamp((float)((int)((this.position.Y + (float)this.height) / 16f) + 2), 0f, (float)Main.maxTilesY);
                        for (int k = num13; k < num14; k++)
{
                            for (int l = num15; l < num16; l++)
{
                                if (Main.tile[k, l] != null && Main.tile[k, l].nactive() && Main.tileSolid[(int)Main.tile[k, l].type] && !Main.tileSolidTop[(int)Main.tile[k, l].type])
{
                                    Vector2 vector2;
                                    vector2.X = (float)(k * 16);
                                    vector2.Y = (float)(l * 16);
                                    if (this.position.X + (float)this.width + 7f > vector2.X && this.position.X - 7f < vector2.X + 16f && this.position.Y + (float)this.height + 7f > vector2.Y && this.position.Y - 7f < vector2.Y + 16f)
{
                                        this.velocity = Vector2.Zero;
                                        flag5 = true;
                                    }
                                }
                            }
                        }
                    }
                    catch
                    {
                    }
                    if (!flag5)
                    {
                        flag = true;
                    }
                    if (this.localAI[0] >= (float)(60 * num11))
                    {
                        flag = true;
                    }
                }
                else if (this.localAI[0] >= (float)(60 * num11))
                {
                    flag = true;
                }
                else if (num12 < 0 || num12 >= Main.maxNPCs)
                {
                    flag = true;
                }
                else if (Main.npc[num12].active && !Main.npc[num12].dontTakeDamage)
                {
                    base.Center = Main.npc[num12].Center - this.velocity * 2f;
                    this.gfxOffY = Main.npc[num12].gfxOffY;
                    if (flag2)
                    {
                        Main.npc[num12].HitEffect(0, 1.0);
                    }
                }
                else
                {
                    flag = true;
                }
                if (flag)
                {
                    if (flag4)
                    {
                        this.velocity = Vector2.Zero;
                        this.ai[0] = 2f;
                        this.netUpdate = true;
                        if (this.type == 1024)
{
                            this.ResetLocalNPCHitImmunity();
                            this.Damage();
                        }
                    }
                    else
                    {
                        this.Kill();
                    }
                }
                if (!flag && this.type == 971)
                {
                    if (num12 > 0 && num12 < Main.maxNPCs && this.timeLeft % 2 == 0)
                    {
                        Vector2 vector3 = center - this.velocity.SafeNormalize(Vector2.Zero) * 8f;
                        Vector2 vector4 = Main.npc[num12].velocity + new Vector2(Main.rand.NextFloatDirection() * 0.35f, 2.5f);
                        Dust dust3 = Dust.NewDustPerfect(vector3, 4, new Vector2?(vector4), 0, new Color(120, 50, 120), 0.65f);
                        dust3.fadeIn = 0.25f;
                        dust3.noGravity = true;
                    }
                    if (this.localAI[1] == 0f)
                    {
                        this.localAI[1] = 1f;
                        this.rotation = this.velocity.ToRotation() + 1.5707964f;
                        if (this.type == 1024)
{
                            this.rotation -= 1.5707964f;
                        }
                    }
                }
                if (!flag && this.type == 975)
                {
                    if (num12 > 0 && num12 < Main.maxNPCs && this.timeLeft % 2 == 0)
                    {
                        Vector2 vector5 = center;
                        Vector2 vector6 = this.velocity.SafeNormalize(Vector2.Zero) * -7f + this.velocity.SafeNormalize(Vector2.Zero).RotatedByRandom(0.19634954631328583);
                        Dust dust4 = Dust.NewDustPerfect(vector5, 5, new Vector2?(Vector2.Zero), 0, default(Color), 1.5f);
                        dust4.scale = 1.1f;
                        dust4.velocity = vector6 * 0.85f + new Vector2(0f, 0.85f);
                        Vector2 velocity = dust4.velocity;
                        dust4.velocity = velocity.RotatedBy((double)(6.2831855f * Main.rand.NextFloatDirection() * 0.025f), default(Vector2));
                        dust4 = Dust.CloneDust(dust4.dustIndex);
                        dust4.velocity = velocity.RotatedBy((double)(6.2831855f * Main.rand.NextFloatDirection() * 0.025f), default(Vector2));
                        dust4.position += dust4.velocity;
                        if (Main.rand.Next(3) == 0)
{
                            dust4 = Dust.CloneDust(dust4.dustIndex);
                            dust4.velocity = dust4.velocity.RotatedByRandom(0.39269909262657166) * 0.9f;
                        }
                    }
                    if (this.localAI[1] == 0f)
                    {
                        this.localAI[1] = 1f;
                        this.rotation = this.velocity.ToRotation() + 1.5707964f;
                        if (this.type == 1024)
{
                            this.rotation -= 1.5707964f;
                        }
                        Vector2 vector7 = center;
                        for (int m = 0; m < 10; m++)
{
                            Vector2 vector8 = Main.rand.NextVector2CircularEdge(4f, 4f);
                            Dust dust5 = Dust.NewDustPerfect(vector7, 5, new Vector2?(Vector2.Zero), 0, default(Color), 1.5f);
                            dust5.scale = 1.5f;
                            dust5.velocity = vector8;
                            dust5.noGravity = true;
                        }
                    }
                }
            }
            if (this.ai[0] == 2f)
            {
                if (this.type == 1024)
                {
                    this.frameCounter++;
                    if (this.frameCounter > 3)
                    {
                        this.frameCounter = 0;
                        this.frame++;
                        if (this.frame >= Main.projFrames[this.type])
{
                            this.frame = 0;
                        }
                    }
                }
                this.tileCollide = false;
                Player player = Main.player[this.owner];
                if (!player.active || player.dead || player.Hitbox.Intersects(base.Hitbox))
                {
                    this.Kill();
                    return;
                }
                this.velocity = (player.Center - base.Center).SafeNormalize(Vector2.Zero) * 16f;
                this.rotation = this.velocity.ToRotation() + 1.5707964f;
                if (this.type == 1024)
                {
                    this.rotation -= 1.5707964f;
                }
                if (this.type == 1024 && this.localAI[1] == 0f)
                {
                    this.localAI[1] += 1f;
                    for (int n = 0; n < 6; n++)
                    {
                        Dust dust6 = Dust.NewDustDirect(this.position, this.width, this.height, 306, 0f, 0f, 0, Color.Transparent, 0.8f + Main.rand.NextFloat() * 1.7f);
                        dust6.velocity = this.velocity.SafeNormalize(Vector2.Zero) * 3f * (-1f + Main.rand.NextFloat() * 2f) + Main.rand.NextVector2Circular(1f, 1f);
                        dust6.color = Color.Lerp(Color.White, new Color(140, 234, 180), (float)n / 10f);
                        dust6.noGravity = true;
                        dust6.position = base.Center;
                    }
                }
            }
            if (this.type == 614)
            {
                Lighting.AddLight(base.Center, 0.2f, 0.6f, 0.7f);
            }
            if (this.type == 636)
            {
                Lighting.AddLight(base.Center, 0.8f, 0.7f, 0.4f);
            }
            this.AI_113_UpdateDrawLayer();
        }
References Terraria.NPC.active, Terraria.Player.active, Terraria.Lighting.AddLight(), Terraria.NPC.CanBeChasedBy(), Terraria.Entity.Center, Microsoft.Xna.Framework.MathHelper.Clamp(), Terraria.Dust.CloneDust(), Terraria.GameContent.Damage, Terraria.Player.dead, Terraria.NPC.dontTakeDamage, Terraria.Dust.dustIndex, Terraria.NPC.gfxOffY, Terraria.Entity.Hitbox, Terraria.NPC.HitEffect(), int, Microsoft.Xna.Framework.Rectangle.Intersects(), Microsoft.Xna.Framework.Color.Lerp(), Terraria.Main.maxNPCs, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Tile.nactive(), Terraria.Dust.NewDustDirect(), Terraria.Dust.NewDustPerfect(), Terraria.Utilities.UnifiedRandom.Next(), Microsoft.Xna.Framework.Vector2.Normalize(), Terraria.Main.npc, Terraria.Main.player, Terraria.Main.projFrames, Terraria.Main.rand, System.Math.Sin(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Microsoft.Xna.Framework.Color.Transparent, Terraria.Tile.type, Microsoft.Xna.Framework.Vector2.UnitY, Terraria.Dust.velocity, Terraria.Entity.velocity, Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.