Terraria Decompiled: Terraria.Projectile.AI_205_RemoteControlCar
AI_205_RemoteControlCar()
void Terraria.Projectile.AI_205_RemoteControlCar () inline private
Definition at line 38520 of file Projectile.cs.
        {
            Player player = Main.player[this.owner];
            bool flag = false;
            if (player.dead)
            {
                flag = true;
            }
            if (this.owner == Main.myPlayer)
            {
                if (this.position.Y - (float)this.height <= 640f)
                {
                    this.Kill();
                    return;
                }
                if (player.HeldItem.type != 5738)
                {
                    flag = true;
                }
                BitsByte bitsByte = (byte)this.ai[0];
                bool flag2 = bitsByte[4];
                bool flag3 = bitsByte[5];
                bool flag4 = player.gravDir == -1f;
                BitsByte bitsByte2 = 0;
                Player.PlayerInputSyncCache localInputCache = player.LocalInputCache;
                bitsByte2[0] = localInputCache.controlLeft ^ flag4;
                bitsByte2[1] = localInputCache.controlRight ^ flag4;
                bitsByte2[2] = localInputCache.controlUp;
                bitsByte2[3] = localInputCache.controlDown;
                bitsByte2[4] = localInputCache.controlJump;
                if (!flag2 && localInputCache.controlJump && this.velocity.Y != 0f)
                {
                    SoundEngine.PlaySound(22, -1, -1, 1, 1f, 0f);
                    flag3 = !flag3;
                    for (int i = 0; i < 2; i++)
                    {
                        Dust dust = Dust.NewDustDirect(this.position, this.width, this.height, 226, 0f, 0f, 0, default(Color), 1f);
                        dust.noLightEmittance = true;
                        dust.scale = 0.6f;
                        dust.noGravity = true;
                    }
                }
                bitsByte2[5] = flag3;
                float num = (float)bitsByte2;
                if (this.ai[0] != num)
                {
                    this.ai[0] = num;
                    this.netUpdate = true;
                }
                Main.DroneCameraTracker.Track(this);
            }
            if (flag)
            {
                this.Kill();
                return;
            }
            BitsByte bitsByte3 = (byte)this.ai[0];
            this.rotation = this.ai[1];
            bool flag5 = bitsByte3[0];
            bool flag6 = bitsByte3[1];
            bool flag7 = bitsByte3[2];
            bool flag8 = bitsByte3[3];
            bool flag9 = bitsByte3[4];
            bool flag10 = bitsByte3[5];
            bool flag11 = flag5 || flag6 || flag7 || flag8;
            this.localAI[0] += 1f;
            if (!flag7 && !flag8)
            {
                this.localAI[0] = 0f;
            }
            bool flag12 = Framing.GetTileSafely((this.oldPosition + base.Size / 2f).ToTileCoordinates()).wall > 0 && flag10;
            bool flag13 = Framing.GetTileSafely(base.Center.ToTileCoordinates()).wall > 0 && flag10;
            bool flag14 = !flag13;
            if (flag13)
            {
                bool flag15 = flag7;
                bool flag16 = flag8;
                bool flag17 = flag6;
                bool flag18 = flag5;
                float num2 = ((flag15 || flag16) ? 0.037699115f : 0.07539823f);
                float num3 = (float)(flag15.ToInt() - flag16.ToInt()) * 0.275f;
                this.rotation += (float)(flag17.ToInt() - flag18.ToInt()) * num2;
                this.velocity += this.rotation.ToRotationVector2() * num3;
                this.velocity *= 0.96f;
                if (this.frame < 4)
                {
                    this.velocity *= 0.5f;
                    this.frame = 4;
                    if (this.direction == -1)
                    {
                        this.rotation += 3.1415927f;
                    }
                    this.direction = (this.spriteDirection = 1);
                }
                int num4 = 999999;
                float num5 = this.velocity.Length();
                if (num5 >= 0.02f)
                {
                    num4 = 16;
                }
                if (num5 >= 0.2f)
                {
                    num4 = 12;
                }
                if (num5 >= 0.5f)
                {
                    num4 = 10;
                }
                if (num5 >= 0.8f)
                {
                    num4 = 8;
                }
                if (num5 >= 1.5f)
                {
                    num4 = 6;
                }
                if (num5 >= 3f)
                {
                    num4 = 3;
                }
                if (num5 >= 6f)
                {
                    num4 = 2;
                }
                if (num5 >= 9f)
                {
                    num4 = 1;
                }
                if (flag11)
                {
                    num4 = 1;
                }
                int num6 = this.frameCounter + 1;
                this.frameCounter = num6;
                if (num6 >= num4)
                {
                    this.frameCounter = 0;
                    num6 = this.frame + 1;
                    this.frame = num6;
                    if (num6 >= 7)
                    {
                        this.frame = 4;
                    }
                }
                this.spriteDirection = (this.direction = 1);
                int num7 = 0;
                if (num3 != 0f)
                {
                    num7 = 3;
                }
                else if (num5 > 0.2f)
                {
                    num7 = 6;
                }
                else if (flag11)
                {
                    num7 = 2;
                }
                if (num7 != 0)
                {
                    float num8 = 0.3f;
                    float num9 = 10f;
                    Vector2 vector = this.velocity;
                    if (num5 < 0.2f)
                    {
                        vector = this.rotation.ToRotationVector2() * -4f;
                    }
                    if (Main.rand.Next(num7) == 0)
                    {
                        Dust.NewDustPerfect(base.Center + new Vector2(-15f, -num9).RotatedBy((double)this.rotation, default(Vector2)) * this.scale, 31, new Vector2?(vector * 0.2f + Main.rand.NextVector2Circular(num8, num8)), 127, default(Color), 1f);
                    }
                    if (Main.rand.Next(num7) == 0)
                    {
                        Dust.NewDustPerfect(base.Center + new Vector2(-15f, num9).RotatedBy((double)this.rotation, default(Vector2)) * this.scale, 31, new Vector2?(vector * 0.2f + Main.rand.NextVector2Circular(num8, num8)), 127, default(Color), 1f);
                    }
                }
                int num10 = 0;
                if (flag11)
                {
                    num10 = 100;
                }
                this.localAI[1] = MathHelper.Lerp(this.localAI[1], (float)num10, 0.2f);
                float num11 = Utils.Remap(this.localAI[0], 0f, 5f, 0f, 1f, true) * Utils.Remap(this.localAI[0], 5f, 15f, 1f, 0f, true);
                float num12 = Utils.Clamp<float>(MathHelper.Max(Utils.Remap(this.localAI[1], 0f, 100f, 0f, 25f, true), num11 * 12f), 0f, 100f);
                ActiveSound activeSound = SoundEngine.GetActiveSound(SlotId.FromFloat(this.localAI[2]));
                if (activeSound == null && num12 != 0f)
                {
                    this.localAI[2] = SoundEngine.PlayTrackedLoopedSound(SoundID.RCCar, base.Center, new ActiveSound.LoopedPlayCondition(new ProjectileAudioTracker(this).IsActiveAndInGame), default(SoundPlayOverrides)).ToFloat();
                    activeSound = SoundEngine.GetActiveSound(SlotId.FromFloat(this.localAI[2]));
                }
                if (activeSound != null)
                {
                    activeSound.Volume = num12;
                    activeSound.Position = base.Center;
                    activeSound.Pitch = Utils.Clamp<float>(Utils.Remap(this.localAI[1], 0f, 100f, -1f, 1f, true) + num11, -1f, 1f);
                }
                if (this.velocity.Y == 0f)
                {
                    this.velocity.Y = 0.0001f;
                }
            }
            if (flag14)
            {
                bool flag19 = this.velocity.Y == 0f;
                int num13 = 0;
                if (flag11)
                {
                    num13 = 100;
                    if (!flag19)
                    {
                        num13 = 10;
                    }
                }
                this.localAI[1] = MathHelper.Lerp(this.localAI[1], (float)num13, 0.2f);
                float num14 = Utils.Remap(this.localAI[0], 0f, 5f, 0f, 1f, true) * Utils.Remap(this.localAI[0], 5f, 15f, 1f, 0f, true);
                float num15 = Utils.Clamp<float>(MathHelper.Max(Utils.Remap(this.localAI[1], 0f, 100f, 0f, 25f, true), num14 * 12f), 0f, 100f);
                ActiveSound activeSound2 = SoundEngine.GetActiveSound(SlotId.FromFloat(this.localAI[2]));
                if (activeSound2 == null && num15 != 0f)
                {
                    this.localAI[2] = SoundEngine.PlayTrackedLoopedSound(SoundID.RCCar, base.Center, new ActiveSound.LoopedPlayCondition(new ProjectileAudioTracker(this).IsActiveAndInGame), default(SoundPlayOverrides)).ToFloat();
                    activeSound2 = SoundEngine.GetActiveSound(SlotId.FromFloat(this.localAI[2]));
                }
                if (activeSound2 != null)
                {
                    activeSound2.Volume = num15;
                    activeSound2.Position = base.Center;
                    activeSound2.Pitch = Utils.Clamp<float>(Utils.Remap(this.localAI[1], 0f, 100f, -1f, 1f, true) + num14, -1f, 1f);
                }
                float num16 = 0.3f;
                if (flag19)
                {
                    float num17 = 0f;
                    Tile tileSafely = Framing.GetTileSafely((this.position + new Vector2(0f, (float)this.height + 0.02f)).ToTileCoordinates());
                    Tile tileSafely2 = Framing.GetTileSafely((this.position + new Vector2((float)this.width, (float)this.height + 0.02f)).ToTileCoordinates());
                    if (tileSafely.blockType() == 2)
                    {
                        num17 = 0.7853982f;
                    }
                    if (tileSafely2.blockType() == 3)
                    {
                        num17 = -0.7853982f;
                    }
                    this.rotation = MathHelper.Lerp(MathHelper.WrapAngle(this.rotation), num17, 0.3f);
                    this.velocity.X = this.velocity.X * 0.97f;
                    int num18 = 0;
                    if (flag5)
                    {
                        num18 = -1;
                    }
                    if (flag6)
                    {
                        num18 = 1;
                    }
                    if (num18 != 0)
                    {
                        if (this.spriteDirection != num18)
{
                            this.localAI[1] = 0f;
                        }
                        this.spriteDirection = (this.direction = num18);
                    }
                    if (flag9)
                    {
                        Vector2 vector2 = (this.rotation - 1.5707964f).ToRotationVector2();
                        this.velocity += vector2 * 6f;
                        num16 = 0f;
                    }
                }
                else if (!flag10)
                {
                    float num19 = 0.20943952f;
                    num19 = Utils.Remap(this.localAI[0], 0f, 10f, num19 * 0.1f, num19, true);
                    int num20 = flag7.ToInt() - flag8.ToInt();
                    this.rotation += (float)num20 * num19 * (float)this.spriteDirection;
                }
                if (flag12 && !flag13)
                {
                    this.velocity *= 1.5f;
                    this.rotation = MathHelper.WrapAngle(this.rotation);
                }
                bool flag20 = !flag19 && this.frame >= 4 && flag10;
                if ((flag19 || !flag10) && this.frame >= 4)
                {
                    if (!flag19 && this.velocity.X < 0f)
                    {
                        this.direction = (this.spriteDirection = -1);
                        this.rotation += 3.1415927f;
                    }
                    this.frame = 0;
                }
                float num21 = Math.Abs(this.velocity.X);
                int num22 = 99999999;
                if (num21 >= 0.02f)
                {
                    num22 = 16;
                }
                if (num21 >= 0.2f)
                {
                    num22 = 12;
                }
                if (num21 >= 0.5f)
                {
                    num22 = 10;
                }
                if (num21 >= 0.8f)
                {
                    num22 = 8;
                }
                if (num21 >= 1.5f)
                {
                    num22 = 6;
                }
                if (num21 >= 3f)
                {
                    num22 = 3;
                }
                if (num21 >= 6f)
                {
                    num22 = 2;
                }
                if (num21 >= 9f)
                {
                    num22 = 1;
                }
                if (flag11)
                {
                    num22 = 1;
                }
                if (!flag20)
                {
                    int num6 = this.frameCounter + 1;
                    this.frameCounter = num6;
                    if (num6 >= num22)
                    {
                        this.frameCounter = 0;
                        num6 = this.frame + 1;
                        this.frame = num6;
                        if (num6 >= 4)
{
                            this.frame = 0;
                        }
                    }
                }
                this.velocity.Y = this.velocity.Y + num16;
                float num23 = (flag19 ? 0.3f : 0.1f);
                if (flag5)
                {
                    this.velocity.X = this.velocity.X - num23;
                }
                if (flag6)
                {
                    this.velocity.X = this.velocity.X + num23;
                }
                Vector4 vector3 = Collision.WalkDownSlope(this.position, this.velocity, this.width, this.height, num16);
                this.position = new Vector2(vector3.X, vector3.Y);
                this.velocity = new Vector2(vector3.Z, vector3.W);
                if (flag19 && flag11)
                {
                    Vector2 position = this.position;
                    float num24 = 0f;
                    int num25 = 3;
                    int num26 = 16 * num25;
                    for (int j = 0; j < num25; j++)
                    {
                        Vector2 vector4 = new Vector2(0f, 16f);
                        Vector2 vector5 = Collision.TileCollision(position + vector4 * (float)j, vector4, this.width, this.height, false, false, 1, false, false, true);
                        num24 += vector5.Y;
                        if (vector5 != vector4)
{
                            break;
                        }
                    }
                    if (num24 != (float)num26)
                    {
                        for (int k = 0; k < 2; k++)
{
                            if (Main.rand.NextFloat() >= 0.66f)
{
                                Vector2 vector6 = position + new Vector2(0f, num24) + new Vector2((float)this.width / 2f, (float)this.height) + new Vector2((float)(-11 * this.spriteDirection) * this.scale, 0f);
                                Vector2 vector7 = Main.rand.NextVector2CircularEdge(2.5f, 1f) * 0.5f;
                                if (vector7.Y > 0f)
{
                                    vector7.Y *= -1f;
                                }
                                Dust.NewDustPerfect(vector6, 31, new Vector2?(vector7), 127, default(Color), 1f);
                            }
                        }
                    }
                }
            }
            this.ai[1] = this.rotation;
            if (this.velocity.Length() > 16f)
            {
                this.velocity *= 16f / this.velocity.Length();
            }
            Lighting.AddLight(base.Center, Vector3.One * 0.3f);
            this.timeLeft = 2;
            this.CheckSectionsInCaseOwnerIsWatching();
        }
References System.Math.Abs(), Terraria.Lighting.AddLight(), Terraria.Tile.blockType(), Terraria.Utils.Clamp(), Terraria.Player.PlayerInputSyncCache.controlDown, Terraria.Player.PlayerInputSyncCache.controlJump, Terraria.Player.PlayerInputSyncCache.controlUp, Terraria.Player.dead, Terraria.Main.DroneCameraTracker, ReLogic.Utilities.SlotId.FromFloat(), Terraria.Audio.SoundEngine.GetActiveSound(), Terraria.Framing.GetTileSafely(), Terraria.Player.HeldItem, Microsoft.Xna.Framework.MathHelper.Lerp(), Terraria.Player.LocalInputCache, Terraria.Audio.ActiveSound.LoopedPlayCondition(), Microsoft.Xna.Framework.MathHelper.Max(), Terraria.Main.myPlayer, Terraria.Dust.NewDustDirect(), Terraria.Dust.NewDustPerfect(), Terraria.Utilities.UnifiedRandom.Next(), Microsoft.Xna.Framework.Vector3.One, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Audio.SoundEngine.PlayTrackedLoopedSound(), Terraria.Main.rand, Terraria.ID.SoundID.RCCar, Terraria.Utils.Remap(), Terraria.Collision.TileCollision(), ReLogic.Utilities.SlotId.ToFloat(), Terraria.DataStructures.DroneCameraTracker.Track(), Terraria.Item.type, Microsoft.Xna.Framework.Vector4.W, Terraria.Collision.WalkDownSlope(), Microsoft.Xna.Framework.MathHelper.WrapAngle(), Microsoft.Xna.Framework.Vector4.X, Microsoft.Xna.Framework.Vector2.Y, Microsoft.Xna.Framework.Vector4.Y, and Microsoft.Xna.Framework.Vector4.Z.