Terraria Decompiled: Terraria.Projectile.AI_184_BadTorchLuck
AI_184_BadTorchLuck()
void Terraria.Projectile.AI_184_BadTorchLuck () inline private
Definition at line 42861 of file Projectile.cs.
        {
            this.owner = 255;
            if (Main.player[Main.myPlayer].unlockedBiomeTorches)
            {
                this.damage = 0;
            }
            if (this.localAI[0] == 0f)
            {
                this.localAI[0] = 1f;
                SoundEngine.PlaySound(SoundID.Item8, base.Center, 0f, 1f);
            }
            if (this.ai[1] > 0f)
            {
                this.ai[1] -= this.velocity.Length();
            }
            else
            {
                this.tileCollide = true;
            }
            int num = (int)this.ai[0];
            float num2 = 4f;
            for (float num3 = 0f; num3 < num2; num3 += 1f)
            {
                int num4 = Dust.NewDust(this.position + this.velocity / num2 * num3, 4, 4, num, 0f, 0f, 100, default(Color), 1f);
                if (Main.rand.Next(3) != 0)
                {
                    Main.dust[num4].noGravity = true;
                }
                Main.dust[num4].velocity *= 0.3f;
                if (num == 66)
                {
                    Main.dust[num4].color = new Color(Main.DiscoR, Main.DiscoG, Main.DiscoB);
                    Main.dust[num4].noGravity = true;
                }
            }
        }
References Terraria.Dust.color, Terraria.Main.DiscoB, Terraria.Main.DiscoG, Terraria.Main.DiscoR, Terraria.Main.dust, int, Terraria.ID.SoundID.Item8, Terraria.Main.myPlayer, Terraria.Dust.NewDust(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.rand, Terraria.Player.unlockedBiomeTorches, and Terraria.Dust.velocity.