Terraria Decompiled: Terraria.Projectile.UseGasTrapInChest
UseGasTrapInChest()
static void Terraria.Projectile.UseGasTrapInChest (int chestIndex, Chest theChest, int gasTrapIndex, int gasOffsetX, int gasOffsetY) inline static
Definition at line 41372 of file Projectile.cs.
        {
            if (Main.netMode == 1)
            {
                return;
            }
            bool flag = false;
            int num = -1;
            for (int i = 0; i < theChest.maxItems; i++)
            {
                Item item = theChest.item[i];
                if (item != null)
                {
                    if (item.IsAir)
                    {
                        if (num == -1)
{
                            num = i;
                        }
                    }
                    else if (item.type == 5356 && item.stack < item.maxStack)
                    {
                        flag = true;
                        item.stack++;
                        if (Main.netMode != 0)
{
                            NetMessage.SendData(32, -1, -1, null, chestIndex, (float)i, 0f, 0f, 0, 0, 0);
                            break;
                        }
                        break;
                    }
                }
            }
            theChest.item[gasTrapIndex].stack--;
            if (theChest.item[gasTrapIndex].stack <= 0)
            {
                if (flag)
                {
                    theChest.item[gasTrapIndex].TurnToAir(false);
                }
                else
                {
                    flag = true;
                    theChest.item[gasTrapIndex].SetDefaults(5356, null);
                }
            }
            if (Main.netMode != 0)
            {
                NetMessage.SendData(32, -1, -1, null, chestIndex, (float)gasTrapIndex, 0f, 0f, 0, 0, 0);
            }
            if (!flag && num > -1)
            {
                flag = true;
                theChest.item[num].SetDefaults(5356, null);
                if (Main.netMode != 0)
                {
                    NetMessage.SendData(32, -1, -1, null, chestIndex, (float)num, 0f, 0f, 0, 0, 0);
                }
            }
            if (!flag)
            {
                Vector2 vector = new Vector2((float)(theChest.x * 16 + gasOffsetX), (float)(theChest.y * 16 + gasOffsetY));
                Item.NewItem(new EntitySource_OverfullChest(theChest.x, theChest.y, theChest), vector, Vector2.One, 5356, 1, false, 0, false);
            }
        }
References System.item, Terraria.Chest.item, Terraria.Chest.maxItems, Terraria.Main.netMode, Terraria.Item.NewItem(), Microsoft.Xna.Framework.Vector2.One, Terraria.NetMessage.SendData(), Terraria.Item.SetDefaults(), Terraria.Item.stack, Terraria.Item.TurnToAir(), Terraria.Chest.x, and Terraria.Chest.y.
Referenced by Terraria.Projectile.GasTrapCheck().