Terraria Decompiled: Terraria.Projectile.AI_DisplayDoll
AI_DisplayDoll()
void Terraria.Projectile.AI_DisplayDoll (Player doll, TEDisplayDoll::DisplayDollPose pose, out bool botherDrawing) inline
Definition at line 22175 of file Projectile.cs.
        {
            this.AI_DisplayDoll_Reset(doll);
            botherDrawing = true;
            bool flag = false;
            DisplayDollPoseID pose2 = pose.Pose;
            if (pose2 - DisplayDollPoseID.Use1 <= 4)
            {
                flag = true;
            }
            int num = this.aiStyle;
            int num4;
            if (num <= 99)
            {
                if (num <= 19)
                {
                    if (num != 15)
                    {
                        if (num == 19)
{
                            this.direction = doll.direction;
                            this.spriteDirection = -this.direction;
                            Vector2 vector = Vector2.UnitX;
                            float num2 = 0f;
                            if (pose.ItemAimRadians != null)
{
                                num2 = pose.ItemAimRadians.Value;
                            }
                            vector = vector.RotatedBy((double)num2, default(Vector2));
                            if (this.direction == -1)
{
                                vector.X *= -1f;
                            }
                            this.velocity = vector;
                            int num3 = 25;
                            num4 = this.type;
                            if (num4 != 130)
{
                                if (num4 - 367 > 1)
{
                                    if (num4 - 877 <= 2)
{
                                        this.position += this.velocity * 74f;
                                        num3 = 50;
                                        this.alpha = 0;
                                    }
                                }
                                else
{
                                    num3 = 20;
                                }
                            }
                            else
{
                                this.position += this.velocity * 44f;
                                num3 = 50;
                            }
                            this.position += this.velocity * this.AI_019_Spears_GetSpearOffsetRelativeToPlayer(doll, num3, 100);
                            this.rotation = (float)Math.Atan2((double)vector.Y, (double)vector.X) + 1.5707964f + 0.7853982f;
                            if (this.spriteDirection == -1)
{
                                this.rotation -= 1.5707964f;
                            }
                            if (!flag)
{
                                botherDrawing = false;
                                return;
                            }
                            return;
                        }
                    }
                    else
                    {
                        this.spriteDirection = this.direction;
                        this.position = new Vector2(doll.Center.X + (float)(9 * doll.direction), doll.Bottom.Y - 12f);
                        if (!flag)
{
                            botherDrawing = false;
                            return;
                        }
                        return;
                    }
                }
                else if (num != 20)
                {
                    if (num == 75)
                    {
                        goto IL_02BB;
                    }
                    if (num == 99)
                    {
                        this.spriteDirection = this.direction;
                        this.position = new Vector2(doll.Center.X + (float)(9 * doll.direction), doll.Bottom.Y - 8f);
                        if (!flag)
{
                            botherDrawing = false;
                            return;
                        }
                        return;
                    }
                }
                else
                {
                    this.spriteDirection = this.direction;
                    Vector2 vector2 = Vector2.UnitX * 20f;
                    float num5 = 0f;
                    if (pose.ItemAimRadians != null)
                    {
                        num5 = pose.ItemAimRadians.Value;
                    }
                    vector2 = vector2.RotatedBy((double)num5, default(Vector2));
                    if (this.direction == -1)
                    {
                        vector2.X *= -1f;
                    }
                    this.velocity = vector2;
                    this.position += vector2;
                    this.rotation = (float)Math.Atan2((double)vector2.Y, (double)vector2.X) + 1.5707964f;
                    if (!flag)
                    {
                        botherDrawing = false;
                        return;
                    }
                    return;
                }
            }
            else
            {
                if (num <= 140)
                {
                    if (num != 100)
                    {
                        if (num != 140)
{
                            goto IL_0093;
                        }
                    }
                    else
                    {
                        Vector2 zero = Vector2.Zero;
                        zero.X = (float)doll.direction * 6f;
                        zero.Y = doll.gravDir * -14f;
                        this.rotation = ((doll.gravDir == 1f) ? 0f : 3.1415927f);
                        this.spriteDirection = this.direction;
                        Vector2 vector3 = Main.OffsetsPlayerOnhand[doll.bodyFrame.Y / 56] * 2f;
                        if (doll.direction != 1)
{
                            vector3.X = (float)doll.bodyFrame.Width - vector3.X;
                        }
                        if (doll.gravDir != 1f)
{
                            vector3.Y = (float)doll.bodyFrame.Height - vector3.Y;
                        }
                        vector3 -= new Vector2((float)(doll.bodyFrame.Width - doll.width), (float)(doll.bodyFrame.Height - 42)) / 2f;
                        base.Center = (doll.RotatedRelativePoint(doll.MountedCenter - new Vector2(20f, 42f) / 2f + vector3 + zero, false, true) - this.velocity).Floor();
                        if (!flag)
{
                            botherDrawing = false;
                            return;
                        }
                        return;
                    }
                }
                else if (num != 142)
                {
                    if (num == 161)
                    {
                        goto IL_02BB;
                    }
                    if (num != 165)
                    {
                        goto IL_0093;
                    }
                    this.ai[0] = 12f;
                    this.ai[1] = 0.4f;
                    Vector2 vector4 = Vector2.UnitX * 1f;
                    float num6 = 0f;
                    if (pose.ItemAimRadians != null)
                    {
                        num6 = pose.ItemAimRadians.Value;
                    }
                    vector4 = vector4.RotatedBy((double)num6, default(Vector2));
                    if (this.direction == -1)
                    {
                        vector4.X *= -1f;
                    }
                    this.velocity = vector4;
                    base.Center = Main.GetPlayerArmPosition(this, doll) + this.velocity * (this.ai[0] - 1f);
                    this.spriteDirection = ((Vector2.Dot(this.velocity, Vector2.UnitX) < 0f) ? (-1) : 1);
                    if (!flag)
                    {
                        botherDrawing = false;
                        return;
                    }
                    return;
                }
                this.spriteDirection = this.direction;
                Vector2 vector5 = Vector2.UnitX * 12f;
                float num7 = 0f;
                if (pose.ItemAimRadians != null)
                {
                    num7 = pose.ItemAimRadians.Value;
                }
                vector5 = vector5.RotatedBy((double)num7, default(Vector2));
                if (this.direction == -1)
                {
                    vector5.X *= -1f;
                }
                this.velocity = vector5;
                this.position += vector5;
                num4 = this.type;
                float num8;
                if (num4 != 699)
                {
                    num8 = 0f;
                    if (this.spriteDirection == -1)
                    {
                        num8 = 3.1415927f;
                    }
                }
                else
                {
                    num8 = 0.7853982f * (float)this.direction;
                    if (this.spriteDirection == -1)
                    {
                        num8 = 0.7853982f * (float)this.direction + 3.1415927f;
                    }
                    this.position += new Vector2(1f, -1f).RotatedBy((double)num7, default(Vector2)) * 75f * new Vector2((float)doll.direction, 1f);
                    if (pose.Pose == DisplayDollPoseID.Use2)
                    {
                        this.position.X = this.position.X - (float)(doll.direction * 4);
                    }
                    if (pose.Pose == DisplayDollPoseID.Use5)
                    {
                        this.position.Y = this.position.Y - 8f;
                    }
                }
                this.alpha = 0;
                this.rotation = (float)Math.Atan2((double)vector5.Y, (double)vector5.X) + num8;
                if (this.type == 699)
                {
                    this.position += new Vector2((float)(110 * this.direction), -6f).RotatedBy((double)this.rotation, default(Vector2));
                    this.position += vector5.SafeNormalize(Vector2.Zero) * -20f;
                }
                if (!flag)
                {
                    botherDrawing = false;
                    return;
                }
                return;
            }
            IL_0093:
            botherDrawing = false;
            return;
            IL_02BB:
            this.spriteDirection = this.direction;
            Vector2 vector6 = Vector2.UnitX * 12f;
            float num9 = 0f;
            if (pose.ItemAimRadians != null)
            {
                num9 = pose.ItemAimRadians.Value;
            }
            vector6 = vector6.RotatedBy((double)num9, default(Vector2));
            if (this.direction == -1)
            {
                vector6.X *= -1f;
            }
            this.velocity = vector6;
            this.position += vector6;
            float num10 = 1.5707964f;
            if (this.aiStyle == 161)
            {
                this.position += vector6 * 1.5f;
            }
            num4 = this.type;
            if (num4 <= 705)
            {
                if (num4 <= 615)
                {
                    if (num4 != 595 && num4 != 615)
                    {
                        goto IL_042B;
                    }
                }
                else if (num4 != 630 && num4 != 705)
                {
                    goto IL_042B;
                }
            }
            else if (num4 <= 735)
            {
                if (num4 != 714 && num4 != 735)
                {
                    goto IL_042B;
                }
            }
            else
            {
                if (num4 == 842)
                {
                    this.position -= vector6 * 0.7f;
                    goto IL_042B;
                }
                if (num4 != 927)
                {
                    goto IL_042B;
                }
                num10 = 0f;
                goto IL_042B;
            }
            num10 = 0f;
            if (this.spriteDirection == -1)
            {
                num10 = 3.1415927f;
            }
            IL_042B:
            this.rotation = (float)Math.Atan2((double)vector6.Y, (double)vector6.X) + num10;
            if (!flag)
            {
                botherDrawing = false;
                return;
            }
        }
References System.Math.Atan2(), Terraria.Player.bodyFrame, Terraria.Entity.Bottom, Terraria.Entity.Center, Terraria.Entity.direction, Microsoft.Xna.Framework.Vector2.Dot(), Terraria.Main.GetPlayerArmPosition(), Terraria.Player.gravDir, Microsoft.Xna.Framework.Rectangle.Height, Terraria.Player.MountedCenter, Terraria.Main.OffsetsPlayerOnhand, Terraria.Player.RotatedRelativePoint(), Microsoft.Xna.Framework.Vector2.UnitX, Microsoft.Xna.Framework.Rectangle.Width, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.Tile_Entities.TEDisplayDoll.Draw().