Terraria Decompiled: Terraria.Projectile.AI_130_FlameBurstTower_FindTarget
AI_130_FlameBurstTower_FindTarget()
int Terraria.Projectile.AI_130_FlameBurstTower_FindTarget (float shot_range, float angleRatioMax, Vector2 shootingSpot, bool canChangeDirection = true) inline private
Definition at line 69146 of file Projectile.cs.
        {
            int num = -1;
            NPC ownerMinionAttackTargetNPC = this.OwnerMinionAttackTargetNPC;
            if (ownerMinionAttackTargetNPC != null && ownerMinionAttackTargetNPC.CanBeChasedBy(this, false))
            {
                for (int i = 0; i < 1; i++)
                {
                    if (ownerMinionAttackTargetNPC.CanBeChasedBy(this, false))
                    {
                        float num2 = Vector2.Distance(shootingSpot, ownerMinionAttackTargetNPC.Center);
                        if (num2 <= shot_range)
{
                            Vector2 vector = (ownerMinionAttackTargetNPC.Center - shootingSpot).SafeNormalize(Vector2.UnitY);
                            if (Math.Abs(vector.X) >= Math.Abs(vector.Y) * angleRatioMax && (canChangeDirection || (float)this.direction * vector.X >= 0f) && (num == -1 || num2 < Vector2.Distance(shootingSpot, Main.npc[num].Center)) && Collision.CanHitLine(shootingSpot, 0, 0, ownerMinionAttackTargetNPC.Center, 0, 0))
{
                                num = ownerMinionAttackTargetNPC.whoAmI;
                            }
                        }
                    }
                }
                if (num != -1)
                {
                    return num;
                }
            }
            for (int j = 0; j < Main.maxNPCs; j++)
            {
                NPC npc = Main.npc[j];
                if (npc.CanBeChasedBy(this, false))
                {
                    float num3 = Vector2.Distance(shootingSpot, npc.Center);
                    if (num3 <= shot_range)
                    {
                        Vector2 vector2 = (npc.Center - shootingSpot).SafeNormalize(Vector2.UnitY);
                        if (Math.Abs(vector2.X) >= Math.Abs(vector2.Y) * angleRatioMax && (canChangeDirection || (float)this.direction * vector2.X >= 0f) && (num == -1 || num3 < Vector2.Distance(shootingSpot, Main.npc[num].Center)) && Collision.CanHitLine(shootingSpot, 0, 0, npc.Center, 0, 0))
{
                            num = j;
                        }
                    }
                }
            }
            return num;
        }
References System.Math.Abs(), Terraria.NPC.CanBeChasedBy(), Terraria.Collision.CanHitLine(), Terraria.Entity.Center, Microsoft.Xna.Framework.Vector2.Distance(), Terraria.Main.maxNPCs, Terraria.Main.npc, Microsoft.Xna.Framework.Vector2.UnitY, Terraria.Entity.whoAmI, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.