Terraria Decompiled: Terraria.Projectile.GetByUUID
GetByUUID() [1/2]
static int Terraria.Projectile.GetByUUID (int owner, float uuid) inline static
Definition at line 21589 of file Projectile.cs.
        {
            return Projectile.GetByUUID(owner, (int)uuid);
        }
References Terraria.Projectile.GetByUUID().
Referenced by Terraria.Projectile.AI_121_StardustDragon(), Terraria.Player.FreeUpPetsAndMinions(), Terraria.Projectile.GetByUUID(), Terraria.Main.SortStardustDragonProjectiles(), and Terraria.Projectile.Update().