Terraria Decompiled: Terraria.Projectile.AI_159_PaperAirplanes
AI_159_PaperAirplanes()
void Terraria.Projectile.AI_159_PaperAirplanes () inline private
Definition at line 49190 of file Projectile.cs.
        {
            if (this.ai[1] == 0f)
            {
                this.direction = ((this.velocity.X > 0f) ? 1 : (-1));
                this.rotation = this.velocity.ToRotation();
                this.ai[1] = 1f;
                this.ai[0] = (float)(-(float)Main.rand.Next(30, 80));
                this.netUpdate = true;
            }
            if (this.wet && this.owner == Main.myPlayer)
            {
                this.Kill();
            }
            this.ai[0] += 1f;
            Vector2 vector = this.rotation.ToRotationVector2() * 8f;
            float num = (float)Math.Sin((double)(6.2831855f * (float)(Main.timeForVisualEffects % 90.0 / 90.0))) * (float)this.direction * Main.WindForVisuals;
            Vector2 vector2 = vector + new Vector2(Main.WindForVisuals, num);
            Vector2.UnitX * (float)this.direction;
            bool flag = this.direction == Math.Sign(Main.WindForVisuals) && this.velocity.Length() > 3f;
            bool flag2 = this.ai[0] >= 20f && this.ai[0] <= 69f;
            if (this.ai[0] == 70f)
            {
                this.ai[0] = (float)(-(float)Main.rand.Next(120, 600));
            }
            bool flag3 = flag2 && flag;
            if (flag3)
            {
                float lerpValue = Utils.GetLerpValue(0f, 30f, this.ai[0], true);
                vector2 = vector.RotatedBy((double)((float)(-(float)this.direction) * 6.2831855f * 0.02f * lerpValue), default(Vector2));
            }
            this.velocity = vector2.SafeNormalize(Vector2.UnitY) * this.velocity.Length();
            if (!flag3)
            {
                float num2 = MathHelper.Lerp(0.15f, 0.05f, Math.Abs(Main.WindForVisuals));
                if (this.timeLeft % 40 < 20)
                {
                    this.velocity.Y = this.velocity.Y - num2;
                }
                else
                {
                    this.velocity.Y = this.velocity.Y + num2;
                }
                if (this.velocity.Y < -2f)
                {
                    this.velocity.Y = -2f;
                }
                if (this.velocity.Y > 2f)
                {
                    this.velocity.Y = 2f;
                }
                this.velocity.X = MathHelper.Clamp(this.velocity.X + Main.WindForVisuals * 0.006f, -6f, 6f);
                if (this.velocity.X * this.oldVelocity.X < 0f)
                {
                    this.direction *= -1;
                    this.ai[0] = (float)(-(float)Main.rand.Next(120, 300));
                    this.netUpdate = true;
                }
            }
            this.rotation = this.velocity.ToRotation();
            this.spriteDirection = this.direction;
        }
References System.Math.Abs(), Microsoft.Xna.Framework.MathHelper.Clamp(), Terraria.Utils.GetLerpValue(), Microsoft.Xna.Framework.Vector2.Length(), Microsoft.Xna.Framework.MathHelper.Lerp(), Terraria.Main.myPlayer, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, System.Math.Sign(), System.Math.Sin(), Terraria.Main.timeForVisualEffects, Microsoft.Xna.Framework.Vector2.UnitY, and Terraria.Main.WindForVisuals.