Terraria Decompiled: Terraria.Projectile.AI_067_FreakingPirates_TryAssigningHelp
AI_067_FreakingPirates_TryAssigningHelp()
void Terraria.Projectile.AI_067_FreakingPirates_TryAssigningHelp () inline private
Definition at line 51595 of file Projectile.cs.
        {
            if (this.owner != Main.myPlayer)
            {
                return;
            }
            if (this.ai[0] == 1f || this.ai[0] == 2f)
            {
                return;
            }
            Player player = Main.player[this.owner];
            PlayerIntentionGuesser intentionGuesser = player.IntentionGuesser;
            if (this.ai[0] == 3f && intentionGuesser.Intention == GuessedPlayerIntention.None)
            {
                this.ai[0] = 0f;
                this.ai[1] = 0f;
                this.ai[2] = 0f;
                this.localAI[0] = 0f;
                this.localAI[1] = 0f;
                this.netUpdate = true;
                return;
            }
            SmartCursorHelper.SmartCursorUsageInfo usageProxy = intentionGuesser.UsageProxy;
            int num = -1;
            int num2 = -1;
            float num3 = this.ai[0];
            float num4 = this.ai[1];
            float num5 = this.ai[2];
            GuessedPlayerIntention intention = intentionGuesser.Intention;
            if (intention != GuessedPlayerIntention.HarvestTreasure)
            {
                if (intention == GuessedPlayerIntention.HarvestTrees)
                {
                    intentionGuesser.PrepareUsageProxy(player, 10, 15, 5);
                    SmartCursorHelper.Step_Axe(usageProxy, ref num, ref num2);
                    if (num != -1 && num2 != -1)
                    {
                        this.ai[0] = 3f;
                        this.ai[1] = (float)num;
                        this.ai[2] = (float)num2;
                    }
                }
            }
            else
            {
                intentionGuesser.PrepareUsageProxy(player, 1, 15, 15);
                intentionGuesser.UsageProxy.mouse - intentionGuesser.UsageProxy.Center;
                SmartCursorHelper.Step_Pickaxe_MineSolids(player, intentionGuesser.LastPosition, intentionGuesser.LastCenter, intentionGuesser.LastWidth, intentionGuesser.LastDirection, intentionGuesser.UsageProxy, Projectile._miningHelperPointsToSkip, ref num, ref num2);
                if (num != -1 && num2 != -1)
                {
                    this.ai[0] = 3f;
                    this.ai[1] = (float)num;
                    this.ai[2] = (float)num2;
                }
            }
            if (num3 != this.ai[0] && intentionGuesser.PlayerActiveActionTimeLeft > 0)
            {
                this.localAI[0] = 60f;
                this.localAI[1] = 0f;
            }
            if (num4 != (float)num || num5 != (float)num2 || num3 != this.ai[0])
            {
                this.netUpdate = true;
            }
        }
References Terraria.Projectile._miningHelperPointsToSkip, Terraria.DataStructures.PlayerIntentionGuesser.Intention, Terraria.Player.IntentionGuesser, Terraria.DataStructures.PlayerIntentionGuesser.LastCenter, Terraria.DataStructures.PlayerIntentionGuesser.LastDirection, Terraria.DataStructures.PlayerIntentionGuesser.LastPosition, Terraria.DataStructures.PlayerIntentionGuesser.LastWidth, Terraria.Main.myPlayer, Terraria.Main.player, Terraria.DataStructures.PlayerIntentionGuesser.PlayerActiveActionTimeLeft, Terraria.DataStructures.PlayerIntentionGuesser.PrepareUsageProxy(), Terraria.GameContent.SmartCursorHelper.Step_Axe(), Terraria.GameContent.SmartCursorHelper.Step_Pickaxe_MineSolids(), and Terraria.DataStructures.PlayerIntentionGuesser.UsageProxy.