Terraria Decompiled: Terraria.Projectile.AI_168_FirstFractal
AI_168_FirstFractal()
void Terraria.Projectile.AI_168_FirstFractal () inline private
Definition at line 46907 of file Projectile.cs.
        {
            float num = 60f;
            float[] array = this.localAI;
            int num2 = 0;
            float num3 = array[num2] + 1f;
            array[num2] = num3;
            if (num3 >= num - 1f)
            {
                this.Kill();
                return;
            }
            if (this.frameCounter == 0)
            {
                this.frameCounter = 1;
                this.frame = Main.rand.Next(15);
            }
            this.velocity = this.velocity.RotatedBy((double)this.ai[0], default(Vector2));
            this.Opacity = Utils.GetLerpValue(0f, 12f, this.localAI[0], true) * Utils.GetLerpValue(num, num - 12f, this.localAI[0], true);
            this.direction = ((this.velocity.X > 0f) ? 1 : (-1));
            this.spriteDirection = this.direction;
            this.rotation = 0.7853982f * (float)this.spriteDirection + this.velocity.ToRotation();
            if (this.spriteDirection == -1)
            {
                this.rotation += 3.1415927f;
            }
            if (this.localAI[0] > 7f)
            {
                int num4 = 5;
                base.Center - new Vector2((float)num4);
                if (Main.rand.Next(15) == 0)
                {
                    Dust dust = Dust.NewDustPerfect(base.Center, 278, null, 100, Color.Lerp(this.GetFirstFractalColor(), Color.White, Main.rand.NextFloat() * 0.3f), 1f);
                    dust.scale = 0.7f;
                    dust.noGravity = true;
                    dust.velocity *= 0.5f;
                    dust.velocity += this.velocity * 2f;
                }
            }
        }
References System.array, Terraria.Utils.GetLerpValue(), Microsoft.Xna.Framework.Color.Lerp(), Terraria.Dust.NewDustPerfect(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, and Microsoft.Xna.Framework.Color.White.