Terraria Decompiled: Terraria.Projectile.AI_199_MeteorOre
AI_199_MeteorOre()
void Terraria.Projectile.AI_199_MeteorOre () inline private
Definition at line 40363 of file Projectile.cs.
        {
            if (this.localAI[0] == 0f)
            {
                this.localAI[0] = 1f;
                this.frame = Main.rand.Next(3);
            }
            int num = Dust.NewDust(new Vector2(this.position.X, this.position.Y), this.width, this.height, 31, 0f, 0f, 100, default(Color), 1f);
            Main.dust[num].scale = 0.1f + (float)Main.rand.Next(5) * 0.1f;
            Main.dust[num].fadeIn = 1.5f + (float)Main.rand.Next(5) * 0.1f;
            Main.dust[num].noGravity = true;
            if (!this.wet)
            {
                int num2 = 6;
                Dust dust = Dust.NewDustDirect(this.position, this.width, this.height, num2, 0f, 0f, 100, default(Color), 1f);
                dust.scale = 1f + (float)Main.rand.Next(5) * 0.1f;
                dust.position.X = dust.position.X + (float)Main.rand.Next(-40, 41) * 0.1f;
                dust.position.Y = dust.position.Y + (float)Main.rand.Next(-40, 41) * 0.1f;
                dust.noGravity = true;
            }
            Lighting.AddLight(base.Center, 1f, 0f, 0f);
            this.rotation += this.velocity.X * 0.06f;
            this.rotation += (float)this.direction * 0.06f;
        }
References Terraria.Lighting.AddLight(), Terraria.Main.dust, Terraria.Dust.fadeIn, Terraria.Dust.NewDust(), Terraria.Dust.NewDustDirect(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Terraria.Main.rand, and Terraria.Dust.scale.