Terraria Decompiled: Terraria.Projectile.AI_019_Spears_GetSpearOffsetRelativeToPlayer
AI_019_Spears_GetSpearOffsetRelativeToPlayer()
float Terraria.Projectile.AI_019_Spears_GetSpearOffsetRelativeToPlayer (Player master, int itemAnimation = -1, int itemAnimationMax = -1) inline private
Definition at line 46345 of file Projectile.cs.
        {
            if (itemAnimation == -1)
            {
                itemAnimation = Math.Max(0, master.itemAnimation);
            }
            if (itemAnimationMax == -1)
            {
                itemAnimationMax = Math.Max(1, master.itemAnimation);
            }
            Vector2 vector = master.RotatedRelativePoint(master.MountedCenter, false, true);
            this.direction = master.direction;
            base.Center = vector;
            int num = itemAnimationMax / 3;
            int num2 = itemAnimationMax;
            int num3 = itemAnimation;
            int num4 = itemAnimationMax / 3;
            float num5 = MathHelper.Min((float)num3, (float)num4);
            float num6 = (float)num3 - num5;
            float num7 = 0f;
            float num8 = 0f;
            float num9 = 0f;
            this.spriteDirection = -this.direction;
            int num10 = this.type;
            if (num10 <= 212)
            {
                if (num10 <= 97)
                {
                    if (num10 <= 64)
                    {
                        switch (num10)
{
                        case 46:
                            num7 = 3f;
                            num9 = 1.6f;
                            num8 = 1.4f;
                            goto IL_0337;
                        case 47:
                            num7 = 4f;
                            num9 = 1.2f;
                            num8 = 0.9f;
                            goto IL_0337;
                        case 48:
                            goto IL_0337;
                        case 49:
                            num7 = 4f;
                            num9 = 1.1f;
                            num8 = 0.85f;
                            goto IL_0337;
                        default:
                            if (num10 != 64)
{
                                goto IL_0337;
                            }
                            break;
                        }
                    }
                    else
                    {
                        if (num10 != 66 && num10 != 97)
{
                            goto IL_0337;
                        }
                        goto IL_02F4;
                    }
                }
                else if (num10 <= 130)
                {
                    if (num10 == 105)
                    {
                        num7 = 3f;
                        num9 = 2.4f;
                        num8 = 2.1f;
                        goto IL_0337;
                    }
                    if (num10 != 130)
                    {
                        goto IL_0337;
                    }
                    num7 = 3f;
                    num9 = 1.3f;
                    num8 = 1f;
                    goto IL_0337;
                }
                else
                {
                    if (num10 == 153)
                    {
                        num7 = 4f;
                        num9 = 1.5f;
                        num8 = 1.3f;
                        goto IL_0337;
                    }
                    if (num10 != 212)
                    {
                        goto IL_0337;
                    }
                    goto IL_02F4;
                }
            }
            else if (num10 <= 342)
            {
                if (num10 <= 218)
                {
                    if (num10 != 215)
                    {
                        if (num10 != 218)
{
                            goto IL_0337;
                        }
                        goto IL_02F4;
                    }
                }
                else
                {
                    if (num10 == 222)
                    {
                        num7 = 3f;
                        num9 = 2.4f;
                        num8 = 2.1f;
                        goto IL_0337;
                    }
                    if (num10 != 342)
                    {
                        goto IL_0337;
                    }
                    num7 = 3f;
                    num9 = 2.4f;
                    num8 = 2.1f;
                    goto IL_0337;
                }
            }
            else if (num10 <= 368)
            {
                if (num10 == 367)
                {
                    num7 = 3f;
                    num9 = 1.6f;
                    num8 = 1.5f;
                    goto IL_0337;
                }
                if (num10 != 368)
                {
                    goto IL_0337;
                }
                num7 = 3f;
                num9 = 1.5f;
                num8 = 1.4f;
                goto IL_0337;
            }
            else
            {
                if (num10 == 730)
                {
                    num7 = 8f;
                    num9 = 1.5f;
                    num8 = 1.2f;
                    goto IL_0337;
                }
                if (num10 - 877 <= 2)
                {
                    num7 = 28f;
                    num9 = 0.4f;
                    num8 = 0.4f;
                    goto IL_0337;
                }
                if (num10 != 1103)
                {
                    goto IL_0337;
                }
                num7 = 4f;
                num9 = 1.1f;
                num8 = 0.85f;
                goto IL_0337;
            }
            this.spriteDirection = -this.direction;
            num7 = 3f;
            num9 = 1.9f;
            num8 = 1.7f;
            goto IL_0337;
            IL_02F4:
            num7 = 3f;
            num9 = 2.1f;
            num8 = 1.9f;
            IL_0337:
            float num11 = (float)(num2 - num4) - num6;
            float num12 = (float)num4 - num5;
            return num7 + num8 * num11 - num9 * num12;
        }
References Terraria.Entity.direction, Terraria.Player.itemAnimation, System.Math.Max(), Microsoft.Xna.Framework.MathHelper.Min(), Terraria.Player.MountedCenter, and Terraria.Player.RotatedRelativePoint().