Terraria Decompiled: Terraria.Projectile.Damage_PVE
Damage_PVE()
void Terraria.Projectile.Damage_PVE (Rectangle projRectangle, float projectileSpecificDamageMultiplier) inline private
Definition at line 11651 of file Projectile.cs.
        {
            bool ownedBySomeone = this.OwnedBySomeone;
            bool flag = this.usesOwnerMeleeHitCD && ownedBySomeone && this.owner < 255;
            if (this.damage <= 0)
            {
                return;
            }
            int[] array = this.localNPCImmunity;
            if (this.type == 626 || this.type == 627 || this.type == 628)
            {
                Projectile projectile = this.FindStardustDragonHeadOfOwner();
                if (projectile != null)
                {
                    array = projectile.localNPCImmunity;
                }
            }
            bool flag2 = true;
            int num = 0;
            while (num < Main.maxNPCs && flag2)
            {
                NPC npc = Main.npc[num];
                if (npc.active)
                {
                    bool flag3 = (!this.usesLocalNPCImmunity && !this.usesIDStaticNPCImmunity) || (this.usesLocalNPCImmunity && array[num] == 0) || (this.usesIDStaticNPCImmunity && Projectile.IsNPCIndexImmuneToProjectileType(this.type, num));
                    if (flag && !Main.player[this.owner].CanHitNPCWithMeleeHit(num))
                    {
                        flag3 = false;
                    }
                    if (flag3 && (!npc.dontTakeDamage || NPCID.Sets.ZappingJellyfish[npc.type]) && (npc.aiStyle != 112 || npc.ai[2] <= 1f))
                    {
                        this.Damage_StartIteratingNPC(npc);
                        this.Damage_PVE_Inner(num, npc, projRectangle, projectileSpecificDamageMultiplier, array, ref flag2);
                        this.Damage_StopIteratingNPC(npc);
                    }
                }
                num++;
            }
        }
References Terraria.NPC.active, Terraria.NPC.ai, System.array, Terraria.Player.CanHitNPCWithMeleeHit(), Terraria.Projectile.damage, Terraria.Projectile.Damage_PVE_Inner(), Terraria.Projectile.Damage_StartIteratingNPC(), Terraria.Projectile.Damage_StopIteratingNPC(), Terraria.NPC.dontTakeDamage, Terraria.Projectile.FindStardustDragonHeadOfOwner(), Terraria.Projectile.IsNPCIndexImmuneToProjectileType(), Terraria.Projectile.localNPCImmunity, Terraria.Main.maxNPCs, Terraria.Main.npc, Terraria.Projectile.OwnedBySomeone, Terraria.Main.player, Terraria.NPC.type, Terraria.Projectile.type, Terraria.Projectile.usesIDStaticNPCImmunity, Terraria.Projectile.usesLocalNPCImmunity, and Terraria.ID.NPCID.Sets.ZappingJellyfish.
Referenced by Terraria.Projectile.Damage().