Terraria Decompiled: Terraria.Projectile.AI_134_Ballista
AI_134_Ballista()
void Terraria.Projectile.AI_134_Ballista () inline private
Definition at line 69296 of file Projectile.cs.
        {
            float num = 900f;
            float num2 = 0.75f;
            Vector2 center = base.Center;
            int num3 = 680;
            float num4 = 16f;
            int num5 = 1;
            int num6 = 5;
            int num7 = 5;
            if (Main.player[this.owner].setSquireT2)
            {
                num4 = 21f;
            }
            int ballistraShotDelay = Projectile.GetBallistraShotDelay(Main.player[this.owner]);
            int num8 = num7;
            int num9 = this.type;
            if (num9 == 677)
            {
                center.Y -= 4f;
            }
            if (this.ai[0] == 0f)
            {
                this.direction = (this.spriteDirection = Main.player[this.owner].direction);
                this.ai[0] = 1f;
                this.ai[1] = 0f;
                this.netUpdate = true;
                if (this.direction == -1)
                {
                    this.rotation = 3.1415927f;
                }
            }
            if (this.ai[0] == 1f)
            {
                this.frame = 0;
                bool flag = false;
                if (Main.player[this.owner].ballistaPanic && this.ai[1] > 60f)
                {
                    this.ai[1] = 60f;
                }
                if (Main.player[this.owner].ballistaPanic && Main.player[this.owner].setSquireT3 && this.ai[1] > 30f)
                {
                    this.ai[1] = 30f;
                }
                if (this.ai[1] > 0f)
                {
                    this.ai[1] -= 1f;
                }
                else
                {
                    flag = true;
                }
                int num10 = this.AI_134_Ballista_FindTarget(num, num2, center);
                if (num10 != -1)
                {
                    Vector2 vector = (Main.npc[num10].Center - center).SafeNormalize(Vector2.UnitY);
                    this.rotation = this.rotation.AngleLerp(vector.ToRotation(), 0.08f);
                    if (this.rotation > 1.5707964f || this.rotation < -1.5707964f)
                    {
                        this.direction = -1;
                    }
                    else
                    {
                        this.direction = 1;
                    }
                    if (flag && this.owner == Main.myPlayer)
                    {
                        this.direction = Math.Sign(vector.X);
                        this.ai[0] = 2f;
                        this.ai[1] = 0f;
                        this.netUpdate = true;
                    }
                }
                else
                {
                    float num11 = 0f;
                    if (this.direction == -1)
                    {
                        num11 = 3.1415927f;
                    }
                    this.rotation = this.rotation.AngleLerp(num11, 0.05f);
                }
            }
            else if (this.ai[0] == 2f)
            {
                this.frame = num5 + (int)(this.ai[1] / (float)num7);
                if (this.ai[1] == (float)num8)
                {
                    SoundEngine.PlayTrackedSound(SoundID.DD2_BallistaTowerShot, base.Center, default(SoundPlayOverrides));
                    Vector2 vector2 = new Vector2((float)this.direction, 0f);
                    int num12 = this.AI_134_Ballista_FindTarget(num, num2, center);
                    if (num12 != -1)
                    {
                        vector2 = (Main.npc[num12].Center - center).SafeNormalize(Vector2.UnitX * (float)this.direction);
                    }
                    this.rotation = vector2.ToRotation();
                    if (this.rotation > 1.5707964f || this.rotation < -1.5707964f)
                    {
                        this.direction = -1;
                    }
                    else
                    {
                        this.direction = 1;
                    }
                    Vector2 vector3 = vector2 * num4;
                    if (this.owner == Main.myPlayer)
                    {
                        Projectile.NewProjectile(this.GetProjectileSource_FromThis(), center, vector3, num3, this.damage, this.knockBack, this.owner, 0f, 0f, 0f, null);
                    }
                }
                float[] array = this.ai;
                int num13 = 1;
                float num14 = array[num13] + 1f;
                array[num13] = num14;
                if (num14 >= (float)(num6 * num7))
                {
                    this.ai[0] = 1f;
                    this.ai[1] = (float)ballistraShotDelay;
                }
            }
            this.spriteDirection = this.direction;
            this.tileCollide = true;
            this.velocity.Y = this.velocity.Y + 0.2f;
        }
References System.array, Terraria.Player.ballistaPanic, Terraria.Entity.Center, Terraria.ID.SoundID.DD2_BallistaTowerShot, Terraria.Entity.direction, Terraria.Projectile.GetBallistraShotDelay(), int, Terraria.Main.myPlayer, Terraria.Projectile.NewProjectile(), Terraria.Main.npc, Terraria.Main.player, Terraria.Audio.SoundEngine.PlayTrackedSound(), Terraria.Player.setSquireT2, Terraria.Player.setSquireT3, System.Math.Sign(), Microsoft.Xna.Framework.Vector2.UnitX, Microsoft.Xna.Framework.Vector2.UnitY, and Microsoft.Xna.Framework.Vector2.X.