Terraria Decompiled: Terraria.Projectile.HandleMovement
HandleMovement()
void Terraria.Projectile.HandleMovement (Vector2 wetVelocity) inline
Definition at line 16137 of file Projectile.cs.
        {
            bool flag = false;
            bool flag2 = false;
            bool? flag3 = ProjectileID.Sets.ForcePlateDetection[this.type];
            bool flag4 = flag3 != null && !flag3.Value;
            bool flag5 = flag3 != null && flag3.Value;
            if (this.tileCollide)
            {
                bool flag6 = true;
                bool flag7 = Main.projPet[this.type];
                if (Main.projPet[this.type])
                {
                    flag6 = false;
                    if (Main.player[this.owner].position.Y + (float)Main.player[this.owner].height - 12f > this.position.Y + (float)this.height)
                    {
                        flag6 = true;
                    }
                }
                if (this.type == 500)
                {
                    flag6 = false;
                    if (Main.player[this.owner].Bottom.Y > base.Bottom.Y + 4f)
                    {
                        flag6 = true;
                    }
                }
                if (this.type == 653 || this.type == 1018)
                {
                    flag6 = false;
                    if (Main.player[this.owner].Bottom.Y > base.Bottom.Y + 4f)
                    {
                        flag6 = true;
                    }
                }
                if (this.type == 378)
                {
                    flag6 = false;
                }
                if (this.aiStyle == 62)
                {
                    flag6 = true;
                }
                if (this.aiStyle == 66)
                {
                    flag6 = true;
                }
                if (this.type == 317)
                {
                    flag6 = true;
                }
                if (this.type == 373)
                {
                    flag6 = true;
                }
                if (this.type == 281)
                {
                    flag6 = false;
                }
                if (this.type == 253)
                {
                    flag6 = false;
                }
                if (this.aiStyle == 53)
                {
                    flag6 = false;
                }
                if (this.aiStyle == 197)
                {
                    flag6 = true;
                }
                if (this.type == 9 || this.type == 1037 || this.type == 1049 || this.type == 12 || this.type == 15 || this.type == 13)
                {
                    flag6 = false;
                }
                if (this.aiStyle == 10 && ProjectileID.Sets.FallingBlockDoesNotFallThroughPlatforms[this.type])
                {
                    flag6 = false;
                }
                if (this.type == 24)
                {
                    flag6 = false;
                }
                if (this.aiStyle == 99 && this.ai[0] == -2f)
                {
                    flag6 = false;
                }
                int num = this.type;
                if (num <= 693)
                {
                    switch (num)
                    {
                    case 663:
                    case 665:
                    case 667:
                        break;
                    case 664:
                    case 666:
                        goto IL_02DD;
                    default:
                        if (num - 677 > 2 && num - 688 > 5)
{
                            goto IL_02DD;
                        }
                        break;
                    }
                }
                else
                {
                    if (num == 759)
                    {
                        flag6 = true;
                        goto IL_02DD;
                    }
                    if (num == 1020)
                    {
                        float num2 = MathHelper.WrapAngle(this.rotation);
                        flag6 = num2 >= 1.5707964f || num2 < -1.5707964f;
                        goto IL_02DD;
                    }
                    if (num != 1105)
                    {
                        goto IL_02DD;
                    }
                }
                flag6 = false;
                IL_02DD:
                if (this.decidesManualFallThrough)
                {
                    flag6 = this.shouldFallThrough;
                }
                Vector2 velocity = this.velocity;
                Vector2 vector;
                int num3;
                int num4;
                this.GetCollisionParams(out vector, out num3, out num4);
                Vector2 vector2 = base.Center - new Vector2((float)num3, (float)num4) * vector;
                if (((this.type != 440 && this.type != 449 && this.type != 606) || this.ai[1] != 1f) && (this.type != 466 || this.localAI[1] != 1f) && (this.type != 580 || this.localAI[1] <= 0f) && (this.type != 640 || this.localAI[1] <= 0f))
                {
                    if (this.aiStyle == 10)
                    {
                        if (this.type >= 736 && this.type <= 738)
{
                            this.velocity = Collision.TileCollision(this.position, this.velocity, this.width, this.height, flag6, flag6, 1, false, false, true);
                        }
                        else if (this.type == 411 || this.type == 412 || this.type == 413 || this.type == 414)
{
                            this.velocity = Collision.TileCollision(this.position, this.velocity, this.width, this.height, flag6, flag6, 1, false, false, true);
                            this.velocity = Collision.AnyCollisionWithSpecificTiles(this.position, this.velocity, this.width, this.height, TileID.Sets.Falling, true);
                        }
                        else if (this.type == 42 || this.type == 65 || this.type == 68 || this.type == 354 || (this.type == 31 && this.ai[0] == 2f))
{
                            this.velocity = Collision.TileCollision(this.position, this.velocity, this.width, this.height, flag6, flag6, 1, false, false, true);
                        }
                        else
{
                            this.velocity = Collision.TileCollision(this.position, this.velocity, this.width, this.height, flag6, flag6, 1, false, false, true);
                        }
                    }
                    else if (this.wet)
                    {
                        if (this.shimmerWet)
{
                            Vector2 velocity2 = this.velocity;
                            this.velocity = Collision.TileCollision(vector2, this.velocity, num3, num4, flag6, flag6, 1, flag7, false, true);
                            wetVelocity = this.velocity * 0.375f;
                            if (this.velocity.X != velocity2.X)
{
                                wetVelocity.X = this.velocity.X;
                            }
                            if (this.velocity.Y != velocity2.Y)
{
                                wetVelocity.Y = this.velocity.Y;
                            }
                        }
                        else if (this.honeyWet)
{
                            Vector2 velocity3 = this.velocity;
                            this.velocity = Collision.TileCollision(vector2, this.velocity, num3, num4, flag6, flag6, 1, flag7, false, true);
                            wetVelocity = this.velocity * 0.25f;
                            if (this.velocity.X != velocity3.X)
{
                                wetVelocity.X = this.velocity.X;
                            }
                            if (this.velocity.Y != velocity3.Y)
{
                                wetVelocity.Y = this.velocity.Y;
                            }
                        }
                        else
{
                            Vector2 velocity4 = this.velocity;
                            this.velocity = Collision.TileCollision(vector2, this.velocity, num3, num4, flag6, flag6, 1, flag7, false, true);
                            wetVelocity = this.velocity * 0.5f;
                            if (this.velocity.X != velocity4.X)
{
                                wetVelocity.X = this.velocity.X;
                            }
                            if (this.velocity.Y != velocity4.Y)
{
                                wetVelocity.Y = this.velocity.Y;
                            }
                        }
                        if (!this.correctSlopeCollision)
{
                            Vector4 vector3 = Collision.SlopeCollision(vector2, this.velocity, num3, num4, 0f, true, false);
                            Vector2 vector4 = this.position - vector2;
                            if (this.aiStyle == 137)
{
                                if (vector2.Y != vector3.Y)
{
                                    flag = true;
                                }
                                if (this.velocity.Y != vector3.W)
{
                                    flag = true;
                                }
                                vector2.Y = vector3.Y;
                                this.position.Y = vector2.Y + vector4.Y;
                                this.velocity.Y = vector3.W;
                            }
                            else
{
                                if (vector2.X != vector3.X)
{
                                    flag = true;
                                }
                                if (vector2.Y != vector3.Y)
{
                                    flag = true;
                                }
                                if (this.velocity.X != vector3.Z)
{
                                    flag = true;
                                }
                                if (this.velocity.Y != vector3.W)
{
                                    flag = true;
                                }
                                vector2.X = vector3.X;
                                vector2.Y = vector3.Y;
                                this.position = vector2 + vector4;
                                this.velocity.X = vector3.Z;
                                this.velocity.Y = vector3.W;
                            }
                        }
                    }
                    else
                    {
                        int num5 = Math.Min(num3, num4);
                        if (num5 < 3)
{
                            num5 = 3;
                        }
                        if (num5 > 16)
{
                            num5 = 16;
                        }
                        if (this.velocity.Length() > (float)num5)
{
                            bool flag8 = true;
                            ref Vector2 ptr = Collision.TileCollision(vector2, this.velocity, num3, num4, flag6, flag6, 1, flag7, false, true);
                            float num6 = this.velocity.Length();
                            float num7 = (float)num5;
                            Vector2 vector5 = this.velocity.SafeNormalize(Vector2.Zero);
                            if (ptr.Y == 0f)
{
                                vector5.Y = 0f;
                            }
                            Vector2 vector6 = Vector2.Zero;
                            Vector2 zero = Vector2.Zero;
                            Vector2 zero2 = Vector2.Zero;
                            int num8 = 0;
                            while (num6 > 0f)
{
                                num8++;
                                if (num8 > 300)
{
                                    break;
                                }
                                Vector2 vector7 = vector2;
                                float num9 = num6;
                                if (num9 > num7)
{
                                    num9 = num7;
                                }
                                num6 -= num9;
                                Vector2 vector8 = vector5 * num9;
                                Vector2 vector9 = Collision.TileCollision(vector2, vector8, num3, num4, flag6, flag6, 1, flag7, false, flag8);
                                vector2 += vector9;
                                this.velocity = vector9;
                                if (!this.correctSlopeCollision)
{
                                    Vector4 vector10 = Collision.SlopeCollision(vector2, this.velocity, num3, num4, 0f, true, false);
                                    Vector2 vector11 = this.position - vector2;
                                    if (this.aiStyle == 137)
{
                                        if (vector2.Y != vector10.Y)
{
                                            flag = true;
                                        }
                                        if (this.velocity.Y != vector10.W)
{
                                            flag = true;
                                        }
                                        vector2.Y = vector10.Y;
                                        this.position.Y = vector2.Y + vector11.Y;
                                        this.velocity.Y = vector10.W;
                                    }
                                    else
{
                                        if (vector2.X != vector10.X)
{
                                            flag = true;
                                        }
                                        if (vector2.Y != vector10.Y)
{
                                            flag = true;
                                        }
                                        if (this.velocity.X != vector10.Z)
{
                                            flag = true;
                                        }
                                        if (this.velocity.Y != vector10.W)
{
                                            flag = true;
                                        }
                                        vector2.X = vector10.X;
                                        vector2.Y = vector10.Y;
                                        this.position = vector2 + vector11;
                                        this.velocity.X = vector10.Z;
                                        this.velocity.Y = vector10.W;
                                    }
                                }
                                flag2 = true;
                                if (this.owner == Main.myPlayer && vector2 != vector7 && !flag4)
{
                                    Collision.SwitchTiles(this, vector2, num3, num4, vector7, 4);
                                }
                                vector9 = this.velocity;
                                vector6 += vector9;
                            }
                            this.velocity = vector6;
                            if (Math.Abs(this.velocity.X - velocity.X) < 0.0001f)
{
                                this.velocity.X = velocity.X;
                            }
                            if (Math.Abs(this.velocity.Y - velocity.Y) < 0.0001f)
{
                                this.velocity.Y = velocity.Y;
                            }
                            if (!this.correctSlopeCollision)
{
                                Vector4 vector12 = Collision.SlopeCollision(vector2, this.velocity, num3, num4, 0f, true, false);
                                Vector2 vector13 = this.position - vector2;
                                if (this.aiStyle == 137)
{
                                    if (vector2.Y != vector12.Y)
{
                                        flag = true;
                                    }
                                    if (this.velocity.Y != vector12.W)
{
                                        flag = true;
                                    }
                                    vector2.Y = vector12.Y;
                                    this.position.Y = vector2.Y + vector13.Y;
                                    this.velocity.Y = vector12.W;
                                }
                                else
{
                                    if (vector2.X != vector12.X)
{
                                        flag = true;
                                    }
                                    if (vector2.Y != vector12.Y)
{
                                        flag = true;
                                    }
                                    if (this.velocity.X != vector12.Z)
{
                                        flag = true;
                                    }
                                    if (this.velocity.Y != vector12.W)
{
                                        flag = true;
                                    }
                                    vector2.X = vector12.X;
                                    vector2.Y = vector12.Y;
                                    this.position = vector2 + vector13;
                                    this.velocity.X = vector12.Z;
                                    this.velocity.Y = vector12.W;
                                }
                            }
                        }
                        else
{
                            this.velocity = Collision.TileCollision(vector2, this.velocity, num3, num4, flag6, flag6, 1, flag7, false, true);
                            if (!this.correctSlopeCollision)
{
                                Vector4 vector14 = Collision.SlopeCollision(vector2, this.velocity, num3, num4, 0f, true, false);
                                Vector2 vector15 = this.position - vector2;
                                if (this.aiStyle == 137)
{
                                    if (vector2.Y != vector14.Y)
{
                                        flag = true;
                                    }
                                    if (this.velocity.Y != vector14.W)
{
                                        flag = true;
                                    }
                                    vector2.Y = vector14.Y;
                                    this.position.Y = vector2.Y + vector15.Y;
                                    this.velocity.Y = vector14.W;
                                }
                                else
{
                                    if (vector2.X != vector14.X)
{
                                        flag = true;
                                    }
                                    if (vector2.Y != vector14.Y)
{
                                        flag = true;
                                    }
                                    if (this.velocity.X != vector14.Z)
{
                                        flag = true;
                                    }
                                    if (this.velocity.Y != vector14.W)
{
                                        flag = true;
                                    }
                                    vector2.X = vector14.X;
                                    vector2.Y = vector14.Y;
                                    this.position = vector2 + vector15;
                                    this.velocity.X = vector14.Z;
                                    this.velocity.Y = vector14.W;
                                }
                            }
                        }
                    }
                }
                if (velocity != this.velocity)
                {
                    flag = true;
                }
                if (this.aiStyle == 3 && (this.position.X <= Main.leftWorld || this.position.X + (float)this.width >= Main.rightWorld || this.position.Y <= Main.topWorld || this.position.Y + (float)this.height >= Main.bottomWorld))
                {
                    flag = true;
                }
                if (flag)
                {
                    if (ProjectileID.Sets.BreaksFromToyBreaker[this.type] && Collision.AnyCollisionWithSpecificTiles(vector2, velocity, num3, num4, TileID.Sets.BreaksToys, false) != velocity)
                    {
                        this.Kill();
                    }
                    if (this.owner == Main.myPlayer && this.CanCutTiles() && (this.friendly || this.hostile) && this.damage > 0)
                    {
                        int num10 = (int)(this.position.X + this.velocity.X - 1f) / 16;
                        int num11 = (int)((this.position.X + (float)this.width + this.velocity.X + 1f) / 16f) + 1;
                        int num12 = (int)(this.position.Y + this.velocity.Y - 1f) / 16;
                        int num13 = (int)((this.position.Y + (float)this.height + this.velocity.Y + 1f) / 16f) + 1;
                        if (num10 < 0)
{
                            num10 = 0;
                        }
                        if (num11 > Main.maxTilesX)
{
                            num11 = Main.maxTilesX;
                        }
                        if (num12 < 0)
{
                            num12 = 0;
                        }
                        if (num13 > Main.maxTilesY)
{
                            num13 = Main.maxTilesY;
                        }
                        bool[] tileCutIgnorance = Main.player[this.owner].GetTileCutIgnorance(false, this.trap);
                        for (int i = num10; i < num11; i++)
{
                            for (int j = num12; j < num13; j++)
{
                                if (Main.tile[i, j] != null && !tileCutIgnorance[(int)Main.tile[i, j].type] && Main.tile[i, j].type == 484 && WorldGen.CanCutTile(i, j, TileCuttingContext.AttackProjectile))
{
                                    WorldGen.KillTile(i, j, false, false, false);
                                    if (Main.netMode != 0)
{
                                        NetMessage.SendData(17, -1, -1, null, 0, (float)i, (float)j, 0f, 0, 0, 0);
                                    }
                                }
                            }
                        }
                    }
                    if (Main.rand.Next(3) == 0 && this.owner == Main.myPlayer && this.CanCutTiles() && (this.friendly || this.hostile) && this.damage > 0)
                    {
                        int num14 = (int)(this.position.X + this.velocity.X - 1f) / 16;
                        int num15 = (int)((this.position.X + (float)this.width + this.velocity.X + 1f) / 16f) + 1;
                        int num16 = (int)(this.position.Y + this.velocity.Y - 1f) / 16;
                        int num17 = (int)((this.position.Y + (float)this.height + this.velocity.Y + 1f) / 16f) + 1;
                        if (num14 < 0)
{
                            num14 = 0;
                        }
                        if (num15 > Main.maxTilesX)
{
                            num15 = Main.maxTilesX;
                        }
                        if (num16 < 0)
{
                            num16 = 0;
                        }
                        if (num17 > Main.maxTilesY)
{
                            num17 = Main.maxTilesY;
                        }
                        bool[] tileCutIgnorance2 = Main.player[this.owner].GetTileCutIgnorance(false, this.trap);
                        for (int k = num14; k < num15; k++)
{
                            for (int l = num16; l < num17; l++)
{
                                if (Main.tile[k, l] != null && !tileCutIgnorance2[(int)Main.tile[k, l].type] && TileID.Sets.CrackedBricks[(int)Main.tile[k, l].type] && WorldGen.CanCutTile(k, l, TileCuttingContext.AttackProjectile))
{
                                    WorldGen.KillTile(k, l, false, false, false);
                                    if (Main.netMode != 0)
{
                                        NetMessage.SendData(17, -1, -1, null, 0, (float)k, (float)l, 0f, 0, 0, 0);
                                    }
                                }
                            }
                        }
                    }
                    if (this.type == 663 || this.type == 665 || this.type == 667 || this.type == 677 || this.type == 678 || this.type == 679 || this.type == 691 || this.type == 692 || this.type == 693 || this.type == 688 || this.type == 689 || this.type == 690)
                    {
                        this.position += this.velocity;
                        this.velocity = Vector2.Zero;
                    }
                    else if (this.type == 434)
                    {
                        this.position += this.velocity;
                        this.numUpdates = 0;
                    }
                    else if (this.type == 1020)
                    {
                        if (this.velocity.X != velocity.X && Math.Abs(velocity.X) > 1f)
{
                            this.velocity.X = -velocity.X * 0.25f;
                        }
                        if (this.velocity.Y != velocity.Y && Math.Abs(velocity.Y) > 1f)
{
                            this.velocity.Y = -velocity.Y * 0.25f;
                        }
                    }
                    else if (this.type == 601)
                    {
                        if (Main.netMode != 2 && this.alpha > 0)
{
                            if (this.ai[1] != 0f)
{
                                SoundEngine.PlaySound(SoundID.Item114, this.position, 0f, 1f);
                            }
                            else
{
                                SoundEngine.PlaySound(SoundID.Item115, this.position, 0f, 1f);
                            }
                        }
                        if (this.owner == Main.myPlayer)
{
                            PortalHelper.TryPlacingPortal(this, velocity, this.velocity);
                        }
                        this.position += this.velocity;
                        this.Kill();
                    }
                    else if (this.type == 985)
                    {
                        this.position += this.velocity;
                        this.velocity = velocity;
                        this.velocity *= 0.01f;
                        this.localAI[1] = 1f;
                    }
                    else if (this.type == 451)
                    {
                        this.ai[0] = 1f;
                        this.ai[1] = 0f;
                        this.netUpdate = true;
                        this.velocity = velocity / 2f;
                    }
                    else if (this.type == 645)
                    {
                        this.ai[0] = 0f;
                        this.ai[1] = -1f;
                        this.netUpdate = true;
                    }
                    else if (this.type == 584)
                    {
                        bool flag9 = false;
                        if (this.velocity.X != velocity.X)
{
                            this.velocity.X = velocity.X * -0.75f;
                            flag9 = true;
                        }
                        if ((this.velocity.Y != velocity.Y && velocity.Y > 2f) || this.velocity.Y == 0f)
{
                            this.velocity.Y = velocity.Y * -0.75f;
                            flag9 = true;
                        }
                        if (flag9)
{
                            float num18 = velocity.Length() / this.velocity.Length();
                            if (num18 == 0f)
{
                                num18 = 1f;
                            }
                            this.velocity /= num18;
                            this.penetrate--;
                        }
                    }
                    else if (this.type == 532)
                    {
                        bool flag10 = false;
                        if (this.velocity.X != velocity.X)
{
                            this.velocity.X = velocity.X * -0.75f;
                            flag10 = true;
                        }
                        if ((this.velocity.Y != velocity.Y && velocity.Y > 2f) || this.velocity.Y == 0f)
{
                            this.velocity.Y = velocity.Y * -0.75f;
                            flag10 = true;
                        }
                        if (flag10)
{
                            float num19 = velocity.Length() / this.velocity.Length();
                            if (num19 == 0f)
{
                                num19 = 1f;
                            }
                            this.velocity /= num19;
                            this.penetrate--;
                            Collision.HitTiles(this.position, velocity, this.width, this.height);
                        }
                    }
                    else if (this.type == 533)
                    {
                        float num20 = 1f;
                        bool flag11 = false;
                        if (this.velocity.X != velocity.X)
{
                            this.velocity.X = velocity.X * -num20;
                            flag11 = true;
                        }
                        if (this.velocity.Y != velocity.Y || this.velocity.Y == 0f)
{
                            this.velocity.Y = velocity.Y * -num20 * 0.5f;
                            flag11 = true;
                        }
                        if (flag11)
{
                            float num21 = velocity.Length() / this.velocity.Length();
                            if (num21 == 0f)
{
                                num21 = 1f;
                            }
                            this.velocity /= num21;
                            if (this.ai[0] == 7f && (double)this.velocity.Y < -0.1)
{
                                this.velocity.Y = this.velocity.Y + 0.1f;
                            }
                            if (this.ai[0] >= 6f && this.ai[0] < 9f)
{
                                Collision.HitTiles(this.position, velocity, this.width, this.height);
                            }
                            this.localAI[2] += 30f;
                        }
                    }
                    else if (this.type == 502)
                    {
                        float[] array = this.ai;
                        int num22 = 0;
                        float[] array2 = this.ai;
                        int num23 = 0;
                        float num24 = array2[num23] + 1f;
                        array2[num23] = num24;
                        array[num22] = MathHelper.Clamp(num24, 1f, 5f);
                        SoundEngine.PlaySound(37, (int)this.position.X, (int)this.position.Y, 5 + (int)this.ai[0], 1f, 0f);
                        if (this.ai[0] >= 5f)
{
                            this.position += this.velocity;
                            this.Kill();
                        }
                        else
{
                            if (this.velocity.Y != velocity.Y)
{
                                this.velocity.Y = -velocity.Y;
                            }
                            if (this.velocity.X != velocity.X)
{
                                this.velocity.X = -velocity.X;
                            }
                        }
                        Vector2 vector16 = new Vector2(0f, -3f - this.ai[0]).RotatedByRandom(3.1415927410125732);
                        float num25 = 10f + this.ai[0] * 4f;
                        Vector2 vector17 = new Vector2(1.05f, 1f);
                        for (float num26 = 0f; num26 < num25; num26 += 1f)
{
                            int num27 = Dust.NewDust(base.Center, 0, 0, 66, 0f, 0f, 0, Color.Transparent, 1f);
                            Main.dust[num27].position = base.Center;
                            Main.dust[num27].velocity = vector16.RotatedBy((double)(6.2831855f * num26 / num25), default(Vector2)) * vector17 * (0.8f + Main.rand.NextFloat() * 0.4f);
                            Main.dust[num27].color = Main.hslToRgb(num26 / num25, 1f, 0.5f, byte.MaxValue);
                            Main.dust[num27].noGravity = true;
                            Main.dust[num27].scale = 1f + this.ai[0] / 3f;
                        }
                        if (Main.myPlayer == this.owner)
{
                            int width = this.width;
                            int height = this.height;
                            int num28 = this.penetrate;
                            this.position = base.Center;
                            this.width = (this.height = 40 + 8 * (int)this.ai[0]);
                            base.Center = this.position;
                            this.penetrate = -1;
                            this.Damage();
                            this.penetrate = num28;
                            this.position = base.Center;
                            this.width = width;
                            this.height = height;
                            base.Center = this.position;
                        }
                    }
                    else if (this.type == 444)
                    {
                        if (this.velocity.X != velocity.X)
{
                            this.velocity.X = -velocity.X;
                        }
                        if (this.velocity.Y != velocity.Y)
{
                            this.velocity.Y = -velocity.Y;
                        }
                        this.ai[0] = this.velocity.ToRotation();
                    }
                    else if (this.type == 617)
                    {
                        if (this.velocity.X != velocity.X)
{
                            this.velocity.X = -velocity.X * 0.35f;
                        }
                        if (this.velocity.Y != velocity.Y)
{
                            this.velocity.Y = -velocity.Y * 0.35f;
                        }
                    }
                    else if (this.type == 440 || this.type == 449 || this.type == 606)
                    {
                        if (this.ai[1] != 1f)
{
                            this.ai[1] = 1f;
                            this.position += this.velocity;
                            this.velocity = velocity;
                        }
                    }
                    else if (this.type == 1024)
                    {
                        if (this.ai[0] == 0f)
{
                            Collision.HitTiles(this.position, velocity, this.width, this.height);
                            SoundEngine.PlaySound(SoundID.Item10, this.position, 0f, 1f);
                            this.position += this.velocity;
                        }
                        if (this.ai[0] < 2f)
{
                            this.ai[0] = 1f;
                            this.ai[1] = -1f;
                            this.velocity = velocity.SafeNormalize(Vector2.Zero);
                            this.netUpdate = true;
                        }
                    }
                    else if (this.type == 85 || this.type == 1106)
                    {
                        this.velocity = velocity * 0.95f;
                        this.position -= this.velocity;
                    }
                    else if (this.type == 466 || this.type == 580 || this.type == 640)
                    {
                        if (this.localAI[1] < 1f)
{
                            this.localAI[1] += 2f;
                            this.position += this.velocity;
                            this.velocity = Vector2.Zero;
                        }
                    }
                    else if (this.type == 405)
                    {
                        this.localAI[0] += 1f;
                        if (this.localAI[0] < 2f)
{
                            if (this.velocity.X != velocity.X)
{
                                this.velocity.X = -velocity.X;
                            }
                            if (this.velocity.Y != velocity.Y)
{
                                this.velocity.Y = -velocity.Y;
                            }
                        }
                        else
{
                            this.Kill();
                        }
                    }
                    else if (this.type == 851)
                    {
                        if (this.velocity.X != velocity.X)
{
                            this.velocity.X = -velocity.X * 0.8f;
                        }
                        if (this.velocity.Y != velocity.Y)
{
                            this.velocity.Y = -velocity.Y * 0.5f;
                        }
                    }
                    else if (this.type == 855)
                    {
                        if (this.velocity.X != velocity.X)
{
                            this.velocity.X = -velocity.X;
                        }
                        if (this.velocity.Y != velocity.Y)
{
                            this.velocity.Y = -velocity.Y;
                            if (velocity.Y < 0f)
{
                                this.velocity.Y = this.velocity.Y * 0.25f;
                            }
                        }
                    }
                    else if (this.aiStyle == 54)
                    {
                        if (this.velocity.X != velocity.X)
{
                            this.velocity.X = velocity.X * -0.6f;
                        }
                        if (this.velocity.Y != velocity.Y)
{
                            this.velocity.Y = velocity.Y * -0.6f;
                        }
                    }
                    else if (this.type == 861)
                    {
                        float num29 = -1f;
                        if (this.ai[1] == 1f)
{
                            num29 = -0.6f;
                        }
                        if (this.velocity.X != velocity.X)
{
                            this.velocity.X = velocity.X * num29;
                        }
                        if (this.velocity.Y != velocity.Y && (double)velocity.Y > 0.7)
{
                            this.velocity.Y = velocity.Y * num29;
                        }
                        if (Math.Abs(this.velocity.Y) < 0.5f)
{
                            this.velocity.Y = 0f;
                        }
                        if (this.ai[1] != 1f)
{
                            this.netUpdate = true;
                        }
                        this.ai[1] = 1f;
                    }
                    else if (!this.correctSlopeCollision && this.type != 1036 && this.type != 500 && this.type != 820 && this.aiStyle != 160 && this.type != 650 && this.type != 882 && this.type != 888 && this.type != 894 && this.type != 895 && this.type != 898 && this.type != 901 && this.type != 957)
                    {
                        if (this.aiStyle == 99)
{
                            if (this.ai[0] == -2f)
{
                                if (this.velocity.Y != velocity.Y && velocity.Y > 4f)
{
                                    this.velocity.Y = -velocity.Y * 0.6f;
                                }
                                if (this.velocity.X != velocity.X)
{
                                    Collision.HitTiles(this.position, this.velocity, this.width, this.height);
                                    SoundEngine.PlaySound(0, (int)this.position.X, (int)this.position.Y, 1, 1f, 0f);
                                    this.Kill();
                                }
                            }
                            else if ((this.type >= 556 && this.type <= 561) || this.type == 1079)
{
                                bool flag12 = false;
                                if (this.velocity.X != velocity.X)
{
                                    flag12 = true;
                                    this.velocity.X = velocity.X * -1f;
                                }
                                if (this.velocity.Y != velocity.Y)
{
                                    flag12 = true;
                                    this.velocity.Y = velocity.Y * -1f;
                                }
                                if (flag12)
{
                                    Vector2 vector18 = Main.player[this.owner].Center - base.Center;
                                    vector18 = vector18.SafeNormalize(Vector2.UnitY);
                                    vector18 *= this.velocity.Length();
                                    vector18 *= 0.25f;
                                    this.velocity *= 0.75f;
                                    this.velocity += vector18;
                                    if (this.velocity.Length() > 6f)
{
                                        this.velocity *= 0.5f;
                                    }
                                }
                            }
                        }
                        else if (this.type == 604)
{
                            if (this.velocity.X != velocity.X)
{
                                this.velocity.X = -velocity.X;
                            }
                            if (this.velocity.Y != velocity.Y)
{
                                this.velocity.Y = -velocity.Y;
                            }
                        }
                        else if (this.type == 379)
{
                            if (this.velocity.X != velocity.X)
{
                                this.velocity.X = velocity.X * -0.6f;
                            }
                            if (this.velocity.Y != velocity.Y && velocity.Y > 2f)
{
                                this.velocity.Y = velocity.Y * -0.6f;
                            }
                        }
                        else if (this.type == 491)
{
                            if (this.ai[0] <= 0f)
{
                                this.ai[0] = -10f;
                            }
                            if (this.velocity.X != velocity.X && Math.Abs(velocity.X) > 0f)
{
                                this.velocity.X = velocity.X * -1f;
                            }
                            if (this.velocity.Y != velocity.Y && Math.Abs(velocity.Y) > 0f)
{
                                this.velocity.Y = velocity.Y * -1f;
                            }
                        }
                        else if ((this.type >= 515 && this.type <= 517) || this.type == 637)
{
                            if (this.velocity.X != velocity.X && Math.Abs(velocity.X) > 1f)
{
                                this.velocity.X = velocity.X * -0.9f;
                            }
                            if (this.velocity.Y != velocity.Y && Math.Abs(velocity.Y) > 1f)
{
                                this.velocity.Y = velocity.Y * -0.9f;
                            }
                        }
                        else if (this.type == 921 || this.type == 926 || this.type == 937)
{
                            if (this.velocity.X != velocity.X && Math.Abs(velocity.X) > 1f)
{
                                this.velocity.X = velocity.X * -0.4f;
                            }
                            if (this.velocity.Y != velocity.Y && Math.Abs(velocity.Y) > 1f)
{
                                this.velocity.Y = velocity.Y * -0.95f;
                            }
                            this.penetrate--;
                        }
                        else if (this.type == 969)
{
                            if (this.velocity.X != velocity.X && Math.Abs(velocity.X) > 1f)
{
                                this.velocity.X = velocity.X * -0.75f;
                            }
                            if (this.velocity.Y != velocity.Y && Math.Abs(velocity.Y) > 1f)
{
                                this.velocity.Y = velocity.Y * -0.75f;
                            }
                        }
                        else if (this.type == 681)
{
                            this.timeLeft = 4;
                        }
                        else if (this.type == 409)
{
                            if (this.velocity.X != velocity.X)
{
                                this.velocity.X = velocity.X * -1f;
                            }
                            if (this.velocity.Y != velocity.Y)
{
                                this.velocity.Y = velocity.Y * -1f;
                            }
                        }
                        else if (this.type == 254)
{
                            if (this.velocity.X != velocity.X)
{
                                this.velocity.X = velocity.X * -1f;
                            }
                            if (this.velocity.Y != velocity.Y)
{
                                this.velocity.Y = velocity.Y * -1f;
                            }
                        }
                        else if (this.type == 225)
{
                            this.ai[1] += 1f;
                            if (this.ai[1] == 1f)
{
                                this.damage = (int)((float)this.damage * 0.66f);
                            }
                            if (this.ai[1] >= 4f)
{
                                this.Kill();
                                return;
                            }
                            this.velocity.X = -velocity.X;
                            this.velocity.Y = -velocity.Y;
                            int num30 = this.FindTargetWithLineOfSight(800f);
                            if (num30 != -1)
{
                                NPC npc = Main.npc[num30];
                                float num31 = base.Distance(npc.Center);
                                Vector2 vector19 = -Vector2.UnitY * MathHelper.Lerp((float)npc.height * 0.1f, (float)npc.height * 0.5f, Utils.GetLerpValue(0f, 300f, num31, false));
                                this.velocity = base.DirectionTo(npc.Center + vector19).SafeNormalize(-Vector2.UnitY) * this.velocity.Length();
                                this.netUpdate = true;
                            }
                        }
                        else if (this.type == 285)
{
                            this.ai[1] += 1f;
                            if (this.ai[1] == 1f)
{
                                this.damage = (int)((float)this.damage * 0.66f);
                            }
                            if (this.ai[1] >= 2f)
{
                                this.Kill();
                                return;
                            }
                            if (this.velocity.X != velocity.X)
{
                                this.velocity.X = velocity.X * -1f;
                            }
                            if (this.velocity.Y != velocity.Y)
{
                                this.velocity.Y = velocity.Y * -1f;
                            }
                            int num32 = this.FindTargetWithLineOfSight(800f);
                            if (num32 != -1)
{
                                NPC npc2 = Main.npc[num32];
                                base.Distance(npc2.Center);
                                this.velocity = base.DirectionTo(npc2.Center).SafeNormalize(-Vector2.UnitY) * this.velocity.Length();
                                this.netUpdate = true;
                            }
                        }
                        else if (this.type == 931 || this.type == 1039)
{
                            if (this.velocity.X != velocity.X)
{
                                this.velocity.X = velocity.X * -1f;
                            }
                            if (this.velocity.Y != velocity.Y)
{
                                this.velocity.Y = velocity.Y * -1f;
                            }
                        }
                        else if (this.type == 155)
{
                            if (this.ai[1] > 10f)
{
                                ChatHelper.BroadcastChatMessage(NetworkText.FromKey("Game.BallBounceResult", new object[]
{
                                    NetworkText.FromKey(Lang.GetProjectileName(this.type).Key, new object[0]),
                                    this.ai[1]
                                }), ChatColors.ServerMessage, -1);
                            }
                            this.ai[1] = 0f;
                            if (this.velocity.X != velocity.X)
{
                                this.velocity.X = velocity.X * -0.6f;
                            }
                            if (this.velocity.Y != velocity.Y && velocity.Y > 2f)
{
                                this.velocity.Y = velocity.Y * -0.6f;
                            }
                        }
                        else if (this.aiStyle == 33)
{
                            if (this.localAI[0] == 0f)
{
                                if (this.wet)
{
                                    this.position += velocity / 2f;
                                }
                                else
{
                                    this.position += velocity;
                                }
                                this.velocity *= 0f;
                                this.localAI[0] = 1f;
                            }
                        }
                        else if (this.type != 308 && this.type != 377 && this.type != 966)
{
                            if (this.aiStyle == 197)
{
                                if (this.ai[0] == 0f)
{
                                    this.AI_197_HandleTileCollision();
                                }
                            }
                            else if (this.type == 477)
{
                                if (this.velocity.Y != velocity.Y || this.velocity.X != velocity.X)
{
                                    this.penetrate--;
                                    if (this.penetrate <= 0)
{
                                        this.Kill();
                                    }
                                    if (this.velocity.X != velocity.X)
{
                                        this.velocity.X = -velocity.X;
                                    }
                                    if (this.velocity.Y != velocity.Y)
{
                                        this.velocity.Y = -velocity.Y;
                                    }
                                    this.rotation = this.velocity.ToRotation() + 1.5707964f;
                                    this.damage = (int)((float)this.damage * 0.85f);
                                }
                                if (this.penetrate > 0 && this.owner == Main.myPlayer)
{
                                    int[] array3 = new int[10];
                                    int num33 = 0;
                                    int num34 = 700;
                                    int num35 = 20;
                                    for (int m = 0; m < Main.maxNPCs; m++)
{
                                        if (Main.npc[m].CanBeChasedBy(this, false))
{
                                            float num36 = (base.Center - Main.npc[m].Center).Length();
                                            if (num36 > (float)num35 && num36 < (float)num34 && Collision.CanHitLine(base.Center, 1, 1, Main.npc[m].Center, 1, 1))
{
                                                array3[num33] = m;
                                                num33++;
                                                if (num33 >= 9)
{
                                                    break;
                                                }
                                            }
                                        }
                                    }
                                    if (num33 > 0)
{
                                        num33 = Main.rand.Next(num33);
                                        Vector2 vector20 = Main.npc[array3[num33]].Center - base.Center;
                                        float num37 = this.velocity.Length();
                                        vector20.Normalize();
                                        this.velocity = vector20 * num37;
                                        this.rotation = this.velocity.ToRotation() + 1.5707964f;
                                        this.netUpdate = true;
                                    }
                                }
                            }
                            else if (this.type == 94)
{
                                if (this.velocity.X != velocity.X)
{
                                    this.velocity.X = -velocity.X;
                                }
                                if (this.velocity.Y != velocity.Y)
{
                                    this.velocity.Y = -velocity.Y;
                                }
                            }
                            else if (this.type == 496)
{
                                if (this.velocity.X != velocity.X)
{
                                    if (Math.Abs(this.velocity.X) < 1f)
{
                                        this.velocity.X = -velocity.X;
                                    }
                                    else
{
                                        this.Kill();
                                    }
                                }
                                if (this.velocity.Y != velocity.Y)
{
                                    if (Math.Abs(this.velocity.Y) < 1f)
{
                                        this.velocity.Y = -velocity.Y;
                                    }
                                    else
{
                                        this.Kill();
                                    }
                                }
                            }
                            else if (this.type == 311)
{
                                if (this.velocity.X != velocity.X)
{
                                    this.velocity.X = -velocity.X;
                                    this.ai[1] += 1f;
                                }
                                if (this.velocity.Y != velocity.Y)
{
                                    this.velocity.Y = -velocity.Y;
                                    this.ai[1] += 1f;
                                }
                                if (this.ai[1] > 4f)
{
                                    this.Kill();
                                }
                            }
                            else if (this.type == 1023)
{
                                bool flag13 = false;
                                if (this.velocity.X != velocity.X)
{
                                    bool flag14 = Math.Abs(this.velocity.X - velocity.X) < 5f;
                                    this.velocity.X = -velocity.X;
                                    if (flag14)
{
                                        this.velocity.X = ((this.velocity.X < 0f) ? (-5f) : 5f);
                                    }
                                    this.localAI[1] = 1f;
                                    flag13 = true;
                                }
                                if (this.velocity.Y != velocity.Y)
{
                                    bool flag15 = velocity.Y > 0f && velocity.Y < 5f;
                                    this.velocity.Y = -velocity.Y;
                                    if (flag15)
{
                                        this.velocity.Y = -5f;
                                    }
                                    this.localAI[1] = 1f;
                                    flag13 = true;
                                }
                                if (flag13)
{
                                    Collision.HitTiles(this.position, velocity, this.width, this.height);
                                    SoundEngine.PlaySound(0, (int)this.position.X, (int)this.position.Y, 1, 1f, 0f);
                                }
                            }
                            else if (this.type == 312)
{
                                if (this.velocity.X != velocity.X)
{
                                    this.velocity.X = -velocity.X;
                                    this.ai[1] += 1f;
                                }
                                if (this.velocity.Y != velocity.Y)
{
                                    this.velocity.Y = -velocity.Y;
                                    this.ai[1] += 1f;
                                }
                            }
                            else if (this.type == 522 || this.type == 620)
{
                                if (this.velocity.X != velocity.X)
{
                                    this.velocity.X = -velocity.X;
                                }
                                if (this.velocity.Y != velocity.Y)
{
                                    this.velocity.Y = -velocity.Y;
                                }
                            }
                            else if (this.type == 524)
{
                                this.ai[0] += 100f;
                                if (this.velocity.X != velocity.X)
{
                                    this.velocity.X = -velocity.X;
                                }
                                if (this.velocity.Y != velocity.Y)
{
                                    this.velocity.Y = -velocity.Y;
                                }
                            }
                            else if (this.aiStyle == 93)
{
                                if (this.velocity != velocity)
{
                                    this.ai[1] = 0f;
                                    this.ai[0] = 1f;
                                    this.netUpdate = true;
                                    this.tileCollide = false;
                                    this.position += this.velocity;
                                    this.velocity = velocity;
                                    this.velocity.Normalize();
                                    this.velocity *= 3f;
                                }
                            }
                            else if (this.type == 281)
{
                                bool flag16 = Math.Abs(this.velocity.X) + Math.Abs(this.velocity.Y) < 2f || this.ai[0] == -1f;
                                if (this.ai[0] == -2f || this.ai[0] == -3f)
{
                                    flag16 = false;
                                }
                                if (flag16)
{
                                    if (Main.myPlayer == this.owner)
{
                                        int num38 = ((this.velocity.X > 0f) ? 1 : 2);
                                        num38 += 2;
                                        NPC.ReleaseNPC((int)base.Center.X, (int)base.Bottom.Y - 4, 614, num38, this.owner);
                                        this.ai[0] = -3f;
                                        this.netUpdate = true;
                                    }
                                }
                                else
{
                                    if (this.velocity.X != velocity.X)
{
                                        this.velocity.X = -velocity.X * 0.5f;
                                    }
                                    if (this.velocity.Y != velocity.Y)
{
                                        this.velocity.Y = -velocity.Y * 0.5f;
                                    }
                                }
                            }
                            else if (this.type == 290 || this.type == 294)
{
                                if (this.velocity.X != velocity.X)
{
                                    this.position.X = this.position.X + this.velocity.X;
                                    this.velocity.X = -velocity.X;
                                }
                                if (this.velocity.Y != velocity.Y)
{
                                    this.position.Y = this.position.Y + this.velocity.Y;
                                    this.velocity.Y = -velocity.Y;
                                }
                                bool flag17 = this.type == 290;
                                bool flag18 = this.owner == Main.myPlayer;
                                if (flag17)
{
                                    flag18 = Main.netMode != 1 || Main.dedServ;
                                }
                                if (flag18)
{
                                    int num39 = this.AI_048_GetStartPositionSettingDelay();
                                    if (this.localAI[0] >= (float)num39)
{
                                        float num40 = this.localAI[1];
                                        float num41 = this.localAI[2];
                                        ParticleOrchestraType particleOrchestraType = ParticleOrchestraType.ShadowbeamHostile;
                                        if (this.type == 294)
{
                                            particleOrchestraType = ParticleOrchestraType.ShadowbeamFriendly;
                                        }
                                        if (num40 > 0f && num41 > 0f)
{
                                            ParticleOrchestrator.BroadcastOrRequestParticleSpawn(particleOrchestraType, new ParticleOrchestraSettings
{
                                                PositionInWorld = base.Center,
                                                MovementVector = new Vector2(num40, num41),
                                                UniqueInfoPiece = (int)(this.velocity.Length() * 1000f)
                                            });
                                        }
                                    }
                                    this.localAI[1] = base.Center.X;
                                    this.localAI[2] = base.Center.Y;
                                }
                            }
                            else if ((this.type == 181 || this.type == 189 || this.type == 357 || this.type == 566) && this.penetrate > 0)
{
                                if (this.type == 357)
{
                                    this.damage = (int)((double)this.damage * 0.9);
                                }
                                this.penetrate--;
                                if (this.velocity.X != velocity.X)
{
                                    this.velocity.X = -velocity.X;
                                }
                                if (this.velocity.Y != velocity.Y)
{
                                    this.velocity.Y = -velocity.Y;
                                }
                            }
                            else if (this.type == 1080)
{
                                if (this.velocity != velocity)
{
                                    this.position += this.velocity;
                                    this.Kill();
                                }
                            }
                            else if (this.type == 307 && this.ai[1] < 5f)
{
                                this.ai[1] += 1f;
                                if (this.velocity.X != velocity.X)
{
                                    this.velocity.X = -velocity.X;
                                }
                                if (this.velocity.Y != velocity.Y)
{
                                    this.velocity.Y = -velocity.Y;
                                }
                            }
                            else if (this.type == 1055 || this.type == 99 || this.type == 1005 || this.type == 1014 || this.type == 1053 || this.type == 1057)
{
                                if (this.velocity.Y != velocity.Y && velocity.Y > 5f)
{
                                    if (this.type == 1053)
{
                                        for (int n = 0; n < 10; n++)
{
                                            int num42 = Dust.NewDust(new Vector2(this.position.X, this.position.Y + 8f), this.width, this.height - 8, 6, 0f, 0f, 100, default(Color), 2f);
                                            Main.dust[num42].velocity *= 8f;
                                            Main.dust[num42].noGravity = true;
                                            num42 = Dust.NewDust(new Vector2(this.position.X, this.position.Y + 8f), this.width, this.height - 8, 6, 0f, 0f, 100, default(Color), 1.25f);
                                            Main.dust[num42].velocity *= 2f;
                                            Dust dust = Main.dust[num42];
                                            dust.velocity.X = dust.velocity.X * 1.5f;
                                            Dust dust2 = Main.dust[num42];
                                            dust2.velocity.Y = dust2.velocity.Y - 2f;
                                        }
                                    }
                                    Collision.HitTiles(this.position, this.velocity, this.width, this.height);
                                    SoundEngine.PlaySound(0, (int)this.position.X, (int)this.position.Y, 1, 1f, 0f);
                                    this.velocity.Y = -velocity.Y * 0.2f;
                                    if (this.type == 1055)
{
                                        this.ai[1] = 1f;
                                    }
                                    else if (this.type == 1057)
{
                                        this.Kill();
                                    }
                                }
                                if (this.velocity.X != velocity.X)
{
                                    if (this.type == 1055)
{
                                        if (this.ai[1] != 1f)
{
                                            this.ai[1] = 1f;
                                            Collision.HitTiles(this.position, this.velocity, this.width, this.height);
                                            SoundEngine.PlaySound(0, (int)this.position.X, (int)this.position.Y, 1, 1f, 0f);
                                        }
                                    }
                                    else
{
                                        this.Kill();
                                    }
                                }
                            }
                            else if (this.type == 1021)
{
                                if (this.velocity.Y != velocity.Y)
{
                                    if (velocity.Y > 4f)
{
                                        Collision.HitTiles(this.position, this.velocity, this.width, this.height);
                                        SoundEngine.PlaySound(0, (int)this.position.X, (int)this.position.Y, 1, 1f, 0f);
                                        this.velocity.Y = -velocity.Y * 0.9f;
                                    }
                                    else if (velocity.Y > 0f)
{
                                        this.localAI[1] = 999f;
                                    }
                                }
                                if (this.velocity.X != velocity.X)
{
                                    if (this.localAI[1] <= 3f)
{
                                        this.velocity.X = velocity.X * -0.75f;
                                        this.localAI[1] += 1f;
                                    }
                                    else
{
                                        this.Kill();
                                    }
                                }
                            }
                            else if (this.type == 1013)
{
                                float num43 = Math.Abs(velocity.X);
                                float num44 = Math.Abs(velocity.Y);
                                float num45 = 0.95f;
                                float num46 = 0.95f;
                                if (num43 < 0.5f)
{
                                    num45 = 0.1f;
                                }
                                else if (num43 < 0.75f)
{
                                    num45 = 0.25f;
                                }
                                else if (num43 < 1f)
{
                                    num45 = 0.5f;
                                }
                                if (num44 < 0.5f)
{
                                    num46 = 0.1f;
                                }
                                else if (num44 < 0.75f)
{
                                    num46 = 0.25f;
                                }
                                else if (num44 < 1f)
{
                                    num46 = 0.5f;
                                }
                                bool flag19 = this.localAI[0] >= 500f;
                                bool flag20 = false;
                                if (this.velocity.Y != velocity.Y)
{
                                    if (flag19 || Math.Abs(velocity.Y) > 5f)
{
                                        flag20 = true;
                                    }
                                    this.velocity.Y = -velocity.Y * num46;
                                }
                                if (this.velocity.X != velocity.X)
{
                                    if (flag19 || Math.Abs(velocity.X) > 5f)
{
                                        flag20 = true;
                                    }
                                    this.velocity.X = -velocity.X * num45;
                                }
                                if (flag20)
{
                                    this.localAI[1] += 1f;
                                    Collision.HitTiles(this.position, this.velocity, this.width, this.height);
                                    SoundEngine.PlaySound(0, (int)this.position.X, (int)this.position.Y, 1, 1f, 0f);
                                }
                                if (this.velocity.Length() < 0.1f && this.localAI[0] > 50f)
{
                                    this.Kill();
                                }
                                if (this.localAI[1] > 20f)
{
                                    this.Kill();
                                }
                            }
                            else if (this.type == 1047)
{
                                this.RainbowBoulder_CheckBounce(ref velocity);
                            }
                            else if (this.type == 727)
{
                                int num47 = 30;
                                float num48 = 2f;
                                float num49 = 2f;
                                if (this.velocity.Y != velocity.Y && velocity.Y > 5f)
{
                                    Collision.HitTiles(this.position, this.velocity, this.width, this.height);
                                    SoundEngine.PlaySound(0, (int)this.position.X, (int)this.position.Y, 1, 1f, 0f);
                                    this.velocity.Y = -velocity.Y * 0.65f;
                                    if (this.owner == Main.myPlayer)
{
                                        int num50 = Main.rand.Next(3, 6);
                                        float num51 = Main.rand.NextFloat();
                                        for (float num52 = 0f; num52 < 1f; num52 += 1f / (float)num50)
{
                                            Vector2 vector21 = ((num51 + num52) * 6.2831855f).ToRotationVector2() * num49;
                                            if (vector21.Y > 0f)
{
                                                vector21 *= -0.7f;
                                            }
                                            Projectile.NewProjectile(this.GetProjectileSource_FromThis(), base.Center, vector21, 763, num47, num48, Main.myPlayer, 0f, 0f, 0f, null);
                                        }
                                    }
                                }
                                if (this.velocity.X != velocity.X)
{
                                    this.Kill();
                                    if (this.owner == Main.myPlayer)
{
                                        int num53 = Main.rand.Next(3, 6);
                                        float num54 = Main.rand.NextFloat();
                                        for (float num55 = 0f; num55 < 1f; num55 += 1f / (float)num53)
{
                                            Vector2 vector22 = ((num54 + num55) * 6.2831855f).ToRotationVector2() * num49;
                                            if (vector22.Y > 0f)
{
                                                vector22 *= -0.7f;
                                            }
                                            Projectile.NewProjectile(this.GetProjectileSource_FromThis(), base.Center, vector22, 763, num47, num48, Main.myPlayer, 0f, 0f, 0f, null);
                                        }
                                    }
                                }
                            }
                            else if (this.type == 1054)
{
                                float num56 = Math.Abs(velocity.X);
                                float num57 = Math.Abs(velocity.Y);
                                float num58 = 0.8f;
                                float num59 = 0.6f;
                                if (num56 < 0.5f)
{
                                    num58 = 0.1f;
                                }
                                else if (num56 < 0.75f)
{
                                    num58 = 0.25f;
                                }
                                else if (num56 < 1f)
{
                                    num58 = 0.5f;
                                }
                                if (num57 < 0.5f)
{
                                    num59 = 0.1f;
                                }
                                else if (num57 < 0.75f)
{
                                    num59 = 0.25f;
                                }
                                else if (num57 < 1f)
{
                                    num59 = 0.5f;
                                }
                                bool flag21 = this.localAI[0] >= 500f;
                                bool flag22 = false;
                                if (this.velocity.Y != velocity.Y)
{
                                    if (flag21 || Math.Abs(velocity.Y) > 5f)
{
                                        flag22 = true;
                                    }
                                    this.velocity.Y = -velocity.Y * num59;
                                }
                                if (this.velocity.X != velocity.X)
{
                                    if (flag21 || Math.Abs(velocity.X) > 2f)
{
                                        flag22 = true;
                                        this.localAI[1] += 1f;
                                    }
                                    this.velocity.X = -velocity.X * num58;
                                }
                                if (flag22)
{
                                    Collision.HitTiles(this.position, this.velocity, this.width, this.height);
                                    SoundEngine.PlaySound(0, (int)this.position.X, (int)this.position.Y, 1, 1f, 0f);
                                }
                                if (this.velocity.Length() < 0.1f && this.localAI[0] > 50f)
{
                                    this.Kill();
                                }
                                if (this.localAI[1] > 1f)
{
                                    this.Kill();
                                }
                            }
                            else if (this.type == 1048)
{
                                float num60 = Math.Abs(velocity.X);
                                float num61 = Math.Abs(velocity.Y);
                                float num62 = 0.75f;
                                float num63 = 0.75f;
                                if (num60 < 0.5f)
{
                                    num62 = 0.1f;
                                }
                                else if (num60 < 0.75f)
{
                                    num62 = 0.2f;
                                }
                                else if (num60 < 1f)
{
                                    num62 = 0.45f;
                                }
                                if (num61 < 0.5f)
{
                                    num63 = 0.1f;
                                }
                                else if (num61 < 0.75f)
{
                                    num63 = 0.2f;
                                }
                                else if (num61 < 1f)
{
                                    num63 = 0.45f;
                                }
                                bool flag23 = this.localAI[0] >= 500f;
                                bool flag24 = false;
                                if (this.velocity.Y != velocity.Y)
{
                                    if (flag23 || Math.Abs(velocity.Y) > 4f)
{
                                        flag24 = true;
                                    }
                                    this.velocity.Y = -velocity.Y * num63;
                                }
                                if (this.velocity.X != velocity.X)
{
                                    if (flag23 || Math.Abs(velocity.X) > 4f)
{
                                        flag24 = true;
                                    }
                                    this.velocity.X = -velocity.X * num62;
                                }
                                if (flag24)
{
                                    this.localAI[1] += 3f;
                                    Collision.HitTiles(this.position, this.velocity, this.width, this.height);
                                    SoundEngine.PlaySound(SoundID.Item177, (int)this.position.X, (int)this.position.Y, 0f, 1f);
                                    for (int num64 = 0; num64 < 10; num64++)
{
                                        Vector2 vector23 = Main.rand.NextVector2FromRectangle(base.Hitbox);
                                        Dust dust3 = Main.dust[Dust.NewDust(vector23 - Vector2.One, 2, 2, 322, -this.velocity.X * 0.5f, -this.velocity.Y * 0.5f, 0, default(Color), 1f)];
                                    }
                                    for (int num65 = 0; num65 < 2 + Main.rand.Next(2); num65++)
{
                                        Vector2 vector24 = Main.rand.NextVector2FromRectangle(base.Hitbox);
                                        ParticleOrchestrator.RequestParticleSpawn(true, ParticleOrchestraType.PooFly, new ParticleOrchestraSettings
{
                                            PositionInWorld = vector24 + this.velocity * -1f
                                        }, null);
                                    }
                                }
                                if (this.velocity.Length() < 0.1f && this.localAI[0] > 50f)
{
                                    this.Kill();
                                }
                                if (this.localAI[1] > 20f)
{
                                    this.Kill();
                                }
                            }
                            else if (this.type == 655)
{
                                if (this.velocity.Y != velocity.Y && velocity.Y > 5f)
{
                                    Collision.HitTiles(this.position, this.velocity, this.width, this.height);
                                    SoundEngine.PlaySound(0, (int)this.position.X, (int)this.position.Y, 1, 1f, 0f);
                                    this.velocity.Y = -velocity.Y * 0.2f;
                                }
                                if (this.velocity.X != velocity.X)
{
                                    this.Kill();
                                }
                            }
                            else if (this.type == 36)
{
                                if (this.penetrate > 1)
{
                                    Collision.HitTiles(this.position, this.velocity, this.width, this.height);
                                    SoundEngine.PlaySound(SoundID.Item10, this.position, 0f, 1f);
                                    this.penetrate--;
                                    if (this.velocity.X != velocity.X)
{
                                        this.velocity.X = -velocity.X;
                                    }
                                    if (this.velocity.Y != velocity.Y)
{
                                        this.velocity.Y = -velocity.Y;
                                    }
                                }
                                else
{
                                    this.Kill();
                                }
                            }
                            else if (this.aiStyle == 21)
{
                                if (this.velocity.X != velocity.X)
{
                                    this.velocity.X = -velocity.X;
                                }
                                if (this.velocity.Y != velocity.Y)
{
                                    this.velocity.Y = -velocity.Y;
                                }
                            }
                            else if (this.aiStyle == 17)
{
                                if (this.velocity.X != velocity.X)
{
                                    this.velocity.X = velocity.X * -0.75f;
                                }
                                if (this.velocity.Y != velocity.Y && (double)velocity.Y > 1.5)
{
                                    this.velocity.Y = velocity.Y * -0.7f;
                                }
                            }
                            else if (this.aiStyle == 15)
{
                                this.AI_015_HandleMovementCollision(ref wetVelocity, ref velocity);
                            }
                            else if (this.aiStyle == 9)
{
                                bool flag25 = this.owner == Main.myPlayer;
                                if (this.type == 79)
{
                                    bool flag26 = this.ai[0] >= 0f;
                                    flag25 &= !flag26;
                                    if (flag26)
{
                                        if (this.velocity.X != velocity.X)
{
                                            this.velocity.X = this.velocity.X * 0.1f;
                                        }
                                        if (this.velocity.Y != velocity.Y)
{
                                            this.velocity.Y = this.velocity.Y * 0.1f;
                                        }
                                    }
                                }
                                if (flag25)
{
                                    this.Kill();
                                }
                            }
                            else if (this.aiStyle == 39)
{
                                Collision.HitTiles(this.position, this.velocity, this.width, this.height);
                                if (this.type == 33 || this.type == 106)
{
                                    if (this.velocity.X != velocity.X)
{
                                        this.velocity.X = -velocity.X;
                                    }
                                    if (this.velocity.Y != velocity.Y)
{
                                        this.velocity.Y = -velocity.Y;
                                    }
                                }
                                else
{
                                    this.ai[0] = 1f;
                                    if (this.aiStyle == 3)
{
                                        this.velocity.X = -velocity.X;
                                        this.velocity.Y = -velocity.Y;
                                    }
                                }
                                this.netUpdate = true;
                                SoundEngine.PlaySound(0, (int)this.position.X, (int)this.position.Y, 1, 1f, 0f);
                            }
                            else if (ProjectileID.Sets.IsAPhaseblade[this.type])
{
                                this.ai[0] = 2f;
                                if (velocity.X == this.velocity.X && velocity.Y > 0f)
{
                                    if (this.type == 1074)
{
                                        for (int num66 = 0; num66 < 15; num66++)
{
                                            int num67 = 57;
                                            if (Main.rand.Next(2) == 0)
{
                                                num67 = 43;
                                            }
                                            Dust dust4 = new Dust();
                                            if (Main.rand.Next(10) == 0)
{
                                                dust4 = Dust.NewDustPerfect(base.Center, num67, null, 255, default(Color), 1f);
                                                dust4.color = new Color(255, 255, 255, 0);
                                                dust4.scale *= 0.5f;
                                                dust4.velocity *= 0.7f;
                                                Dust dust5 = dust4;
                                                dust5.velocity.Y = dust5.velocity.Y - 3f;
                                                Dust dust6 = dust4;
                                                dust6.position.X = dust6.position.X + (float)Main.rand.Next(-4, 6);
                                            }
                                            else
{
                                                dust4 = Dust.NewDustPerfect(base.Center, num67, null, 255, default(Color), 1f);
                                                dust4.color = new Color(200, 200, 200, 0);
                                                if (Main.rand.Next(4) == 0)
{
                                                    dust4.noGravity = true;
                                                }
                                                dust4.scale *= 0.5f;
                                                Dust dust7 = dust4;
                                                dust7.velocity.Y = dust7.velocity.Y * 0.15f;
                                                Dust dust8 = dust4;
                                                dust8.velocity.Y = dust8.velocity.Y - 0.6f;
                                                Dust dust9 = dust4;
                                                dust9.velocity.X = dust9.velocity.X * 0.6f;
                                                Dust dust10 = dust4;
                                                dust10.position.X = dust10.position.X + (float)Main.rand.Next(-4, 6);
                                                if (dust4.position.X < base.Center.X)
{
                                                    dust4.velocity.X = -Math.Abs(dust4.velocity.X);
                                                }
                                                else
{
                                                    dust4.velocity.X = Math.Abs(dust4.velocity.X);
                                                }
                                            }
                                            Dust dust11 = dust4;
                                            dust11.position.Y = dust11.position.Y + 6f;
                                            Dust dust12 = dust4;
                                            dust12.position.Y = dust12.position.Y + (float)Main.rand.Next(300) * 0.1f;
                                        }
                                    }
                                    else
{
                                        int num68 = 0;
                                        Color color = Color.Black;
                                        if (this.type == 1059 || this.type == 1065)
{
                                            num68 = 88;
                                        }
                                        else if (this.type == 1060 || this.type == 1066)
{
                                            num68 = 90;
                                        }
                                        else if (this.type == 1061 || this.type == 1067)
{
                                            num68 = 89;
                                        }
                                        else if (this.type == 1062 || this.type == 1068)
{
                                            num68 = 86;
                                        }
                                        else if (this.type == 1064 || this.type == 1070)
{
                                            num68 = 87;
                                        }
                                        else if (this.type == 1063 || this.type == 1069)
{
                                            num68 = 91;
                                        }
                                        else if (this.type == 1071 || this.type == 1072)
{
                                            num68 = 138;
                                        }
                                        else if (this.type == 1075 || this.type == 1076)
{
                                            num68 = 325;
                                        }
                                        else if (this.type == 1101 || this.type == 1102)
{
                                            num68 = 267;
                                            color = Item.GetPhaseColor(this.type, false);
                                        }
                                        for (int num69 = 0; num69 < 5; num69++)
{
                                            Dust dust13 = Dust.NewDustPerfect(base.Center, num68, null, 0, default(Color), 1f);
                                            dust13.color = new Color(255, 255, 255, 255);
                                            if (color != Color.Black)
{
                                                dust13.color = color;
                                            }
                                            if (Main.rand.Next(10) == 0)
{
                                                dust13.scale *= 0.45f;
                                                dust13.velocity *= 0.7f;
                                                Dust dust14 = dust13;
                                                dust14.velocity.X = dust14.velocity.X * 1.2f;
                                                Dust dust15 = dust13;
                                                dust15.velocity.Y = dust15.velocity.Y - 3.5f;
                                                if (num68 == 267)
{
                                                    dust13.velocity *= 2f;
                                                    dust13.noGravity = true;
                                                }
                                            }
                                            else
{
                                                dust13.velocity *= 0.3f;
                                                dust13.scale *= 0.7f;
                                                dust13.noGravity = true;
                                                Dust dust16 = dust13;
                                                dust16.velocity.Y = dust16.velocity.Y - 0.5f;
                                            }
                                            Dust dust17 = dust13;
                                            dust17.position.X = dust17.position.X + (float)Main.rand.Next(-2, 4);
                                            if (num68 != 138)
{
                                                Dust dust18 = dust13;
                                                dust18.position.X = dust18.position.X + 1f;
                                            }
                                            if (this.height < 42)
{
                                                Dust dust19 = dust13;
                                                dust19.position.Y = dust19.position.Y + 6f;
                                                Dust dust20 = dust13;
                                                dust20.position.Y = dust20.position.Y + (float)Main.rand.Next(240) * 0.1f;
                                            }
                                            else
{
                                                Dust dust21 = dust13;
                                                dust21.position.Y = dust21.position.Y + 6f;
                                                Dust dust22 = dust13;
                                                dust22.position.Y = dust22.position.Y + (float)Main.rand.Next(320) * 0.1f;
                                            }
                                        }
                                    }
                                }
                            }
                            else if (this.aiStyle == 3 || this.aiStyle == 13 || this.aiStyle == 69 || this.aiStyle == 109)
{
                                if (this.type == 106)
{
                                    Vector2 vector25 = base.Center + this.velocity.SafeNormalize(Vector2.UnitX) * 8f * this.scale;
                                    Vector2 vector26 = new Vector2((float)((this.velocity.X != velocity.X) ? (-(float)Math.Sign(velocity.X)) : 0), (float)((this.velocity.Y != velocity.Y) ? (-(float)Math.Sign(velocity.Y)) : 0));
                                    this.LightDisc_Bounce(vector25, vector26);
                                }
                                if (this.type == 23)
{
                                    this.velocity *= 0f;
                                }
                                else if (this.type == 383)
{
                                    if (this.ai[1] >= 10f)
{
                                        int num70 = 300;
                                        this.localAI[0] = (float)num70;
                                        Collision.HitTilesInACircle(new Vector2(this.position.X - (float)(num70 / 2), this.position.Y - (float)(num70 / 2)), this.velocity, num70, num70);
                                        SoundEngine.PlaySound(SoundID.Item14, this.position, 0f, 1f);
                                    }
                                }
                                else if (this.type == 301)
{
                                    int num71 = 200;
                                    this.localAI[0] = (float)num71;
                                    if (this.owner == Main.myPlayer)
{
                                        ParticleOrchestrator.RequestParticleSpawn(false, ParticleOrchestraType.PaladinsHammerShockwave, new ParticleOrchestraSettings
{
                                            PositionInWorld = this.position,
                                            MovementVector = base.Size
                                        }, new int?(this.owner));
                                    }
                                }
                                else
{
                                    Collision.HitTiles(this.position, this.velocity, this.width, this.height);
                                }
                                if (this.type == 33 || this.type == 106 || this.type == 866)
{
                                    if (this.velocity.X != velocity.X)
{
                                        this.velocity.X = -velocity.X;
                                    }
                                    if (this.velocity.Y != velocity.Y)
{
                                        this.velocity.Y = -velocity.Y;
                                    }
                                }
                                else
{
                                    this.ai[0] = 1f;
                                    if ((this.aiStyle == 3 || this.aiStyle == 109) && this.type != 383)
{
                                        this.velocity.X = -velocity.X;
                                        this.velocity.Y = -velocity.Y;
                                    }
                                }
                                this.netUpdate = true;
                                SoundEngine.PlaySound(0, (int)this.position.X, (int)this.position.Y, 1, 1f, 0f);
                            }
                            else if (this.aiStyle == 8 && this.type != 96)
{
                                SoundEngine.PlaySound(SoundID.Item10, this.position, 0f, 1f);
                                this.ai[0] += 1f;
                                int num72 = 5;
                                if (this.type == 27 && this.ai[1] == 1f)
{
                                    num72 = 7;
                                }
                                num = this.type;
                                if (num != 15)
{
                                    if (num == 253)
{
                                        num72 = 8;
                                    }
                                }
                                else
{
                                    num72 = 6;
                                }
                                if (this.ai[0] >= (float)num72)
{
                                    this.position += this.velocity;
                                    this.Kill();
                                }
                                else
{
                                    if (this.type == 15 && this.velocity.Y > 4f)
{
                                        if (this.velocity.Y != velocity.Y)
{
                                            this.velocity.Y = -velocity.Y * 0.8f;
                                        }
                                    }
                                    else if (this.velocity.Y != velocity.Y)
{
                                        this.velocity.Y = -velocity.Y;
                                    }
                                    if (this.velocity.X != velocity.X)
{
                                        this.velocity.X = -velocity.X;
                                    }
                                }
                            }
                            else if (this.aiStyle == 61)
{
                                if (this.velocity.X != velocity.X)
{
                                    this.velocity.X = velocity.X * -0.3f;
                                }
                                if (this.velocity.Y != velocity.Y && velocity.Y > 1f)
{
                                    this.velocity.Y = velocity.Y * -0.3f;
                                }
                            }
                            else if (this.aiStyle == 14)
{
                                if (this.type == 928)
{
                                    int num73 = 0;
                                    for (int num74 = 1000; num74 >= 0; num74--)
{
                                        if (num74 != this.whoAmI && Main.projectile[num74].active && Main.projectile[num74].owner == this.owner && Main.projectile[num74].type == this.type)
{
                                            num73++;
                                            if (num73 >= 2 && this.timeLeft > Main.projectile[num74].timeLeft && Main.projectile[num74].timeLeft > 30)
{
                                                Main.projectile[num74].timeLeft = 2;
                                            }
                                        }
                                    }
                                }
                                if (this.type == 261 && ((this.velocity.X != velocity.X && (velocity.X < -3f || velocity.X > 3f)) || (this.velocity.Y != velocity.Y && (velocity.Y < -3f || velocity.Y > 3f))))
{
                                    for (int num75 = 0; num75 < 10; num75++)
{
                                        Collision.HitTiles(this.position, this.velocity, this.width, this.height);
                                    }
                                    SoundEngine.PlaySound(0, (int)base.Center.X, (int)base.Center.Y, 1, 1f, 0f);
                                    this.MakeBoulderOfEarthExplosion();
                                }
                                if (this.type >= 326 && this.type <= 328 && this.velocity.X != velocity.X)
{
                                    this.velocity.X = velocity.X * -0.1f;
                                }
                                if ((this.type >= 400 && this.type <= 402) || (this.type >= 1107 && this.type <= 1109))
{
                                    if (this.velocity.X != velocity.X)
{
                                        this.velocity.X = velocity.X * -0.1f;
                                    }
                                }
                                else if (this.type == 870 && this.ai[1] == 0f)
{
                                    if (this.velocity.X != velocity.X || this.velocity.Y != velocity.Y)
{
                                        this.velocity = -velocity;
                                        this.ai[1] = 1f;
                                    }
                                }
                                else if (this.type == 50)
{
                                    if (this.velocity.X != velocity.X)
{
                                        this.velocity.X = velocity.X * -0.2f;
                                    }
                                    if (this.velocity.Y != velocity.Y && (double)velocity.Y > 1.5)
{
                                        this.velocity.Y = velocity.Y * -0.2f;
                                    }
                                }
                                else if (this.type >= 1089)
{
                                    if (this.velocity.X != velocity.X)
{
                                        bool flag27 = Math.Abs(this.velocity.X - velocity.X) < 1f;
                                        this.velocity.X = -velocity.X * 0.99f;
                                        if (flag27)
{
                                            this.velocity.X = ((this.velocity.X < 0f) ? (-1f) : 1f);
                                        }
                                    }
                                    if (this.velocity.Y != velocity.Y)
{
                                        bool flag28 = velocity.Y > 0f && velocity.Y < 1f;
                                        this.velocity.Y = -velocity.Y * 0.99f;
                                        if (flag28)
{
                                            this.velocity.Y = -1f;
                                        }
                                    }
                                }
                                else if (this.type == 185)
{
                                    if (this.velocity.X != velocity.X)
{
                                        this.velocity.X = velocity.X * -0.9f;
                                    }
                                    if (this.velocity.Y != velocity.Y && velocity.Y > 1f)
{
                                        this.velocity.Y = velocity.Y * -0.9f;
                                    }
                                }
                                else if (this.type == 277)
{
                                    if (this.velocity.X != velocity.X)
{
                                        this.velocity.X = velocity.X * -0.9f;
                                    }
                                    if (this.velocity.Y != velocity.Y && velocity.Y > 3f)
{
                                        this.velocity.Y = velocity.Y * -0.9f;
                                    }
                                }
                                else if (this.type != 480)
{
                                    if (this.type == 450)
{
                                        if (this.velocity.X != velocity.X)
{
                                            this.velocity.X = velocity.X * -0.1f;
                                        }
                                    }
                                    else
{
                                        if (this.velocity.X != velocity.X)
{
                                            this.velocity.X = velocity.X * -0.5f;
                                        }
                                        if (this.velocity.Y != velocity.Y && velocity.Y > 1f)
{
                                            this.velocity.Y = velocity.Y * -0.5f;
                                        }
                                    }
                                }
                            }
                            else if (this.aiStyle == 16)
{
                                if (this.type == 1088)
{
                                    Point zero3 = Point.Zero;
                                    if (this.AI_016_CanAcornPlant(out zero3))
{
                                        this.Kill();
                                    }
                                }
                                if (this.velocity.X != velocity.X)
{
                                    this.velocity.X = velocity.X * -0.4f;
                                    if (this.type == 29)
{
                                        this.velocity.X = this.velocity.X * 0.8f;
                                    }
                                }
                                if (this.velocity.Y != velocity.Y && (double)velocity.Y > 0.7 && this.type != 102)
{
                                    this.velocity.Y = velocity.Y * -0.4f;
                                    if (this.type == 29)
{
                                        this.velocity.Y = this.velocity.Y * 0.8f;
                                    }
                                }
                                if (this.type == 134 || this.type == 137 || this.type == 140 || this.type == 143 || this.type == 303 || (this.type >= 338 && this.type <= 341) || this.type == 776 || this.type == 780 || this.type == 793 || this.type == 796 || this.type == 799 || this.type == 784 || this.type == 787 || this.type == 790 || this.type == 803 || this.type == 804 || this.type == 808 || this.type == 809 || this.type == 810 || this.type == 805 || this.type == 806 || this.type == 807 || this.type == 930)
{
                                    this.velocity *= 0f;
                                    this.alpha = 255;
                                    this.timeLeft = 3;
                                }
                            }
                            else if (this.aiStyle == 68)
{
                                this.velocity *= 0f;
                                this.alpha = 255;
                                this.timeLeft = 3;
                                this.netUpdate = true;
                            }
                            else if (this.type == 870)
{
                                if (this.velocity.X != velocity.X)
{
                                    this.velocity.X = velocity.X * -0.2f;
                                }
                                if (this.velocity.Y != velocity.Y && velocity.Y > 0f)
{
                                    this.velocity.Y = velocity.Y * -0.2f;
                                }
                            }
                            else if (this.aiStyle == 201)
{
                                this.ai[1] = 1f;
                                this.velocity = velocity;
                            }
                            else if (this.type == 116)
{
                                this.ai[2] += 1f;
                                if (this.ai[2] < 4f)
{
                                    SoundEngine.PlaySound(SoundID.Item10, this.position, 0f, 1f);
                                    for (int num76 = 0; num76 < 30; num76++)
{
                                        int num77 = Dust.NewDust(new Vector2(this.position.X, this.position.Y), this.width, this.height, 64, 0f, 0f, 100, Color.White, 1.8f);
                                        Main.dust[num77].noGravity = true;
                                        Main.dust[num77].velocity *= (float)Main.rand.Next(1, 7);
                                    }
                                    if (this.velocity.X != velocity.X)
{
                                        this.velocity.X = velocity.X * -1f;
                                    }
                                    if (this.velocity.Y != velocity.Y)
{
                                        this.velocity.Y = velocity.Y * -1f;
                                    }
                                }
                                else
{
                                    this.Kill();
                                }
                            }
                            else if (this.type == 1081)
{
                                if (velocity.Y != this.velocity.Y && velocity.Y > 0f)
{
                                    this.position += this.velocity;
                                    this.Kill();
                                }
                                else if (this.velocity != velocity)
{
                                    if (this.velocity.Y < 0f)
{
                                        this.velocity.Y = 0f;
                                    }
                                    if (this.localAI[0] == 0f)
{
                                        this.localAI[0] = 1f;
                                        SoundEngine.PlaySound(0, (int)this.position.X, (int)this.position.Y, 1, 1f, 0f);
                                    }
                                }
                            }
                            else
{
                                this.position += this.velocity;
                                this.Kill();
                            }
                        }
                    }
                }
            }
            this.UpdatePosition(wetVelocity);
            if (!flag2 && !flag4 && this.owner == Main.myPlayer && (this.tileCollide || flag5) && this.position != this.oldPosition)
            {
                Vector2 vector27;
                int num78;
                int num79;
                this.GetCollisionParams(out vector27, out num78, out num79);
                Vector2 vector28 = base.Size / 2f - new Vector2((float)num78, (float)num79) * vector27;
                Collision.SwitchTiles(this, this.position + vector28, num78, num79, this.oldPosition + vector28, 4);
            }
        }
References System.Math.Abs(), Terraria.Projectile.active, Terraria.Collision.AnyCollisionWithSpecificTiles(), System.array, Microsoft.Xna.Framework.Color.Black, Terraria.Entity.Bottom, Terraria.Main.bottomWorld, Terraria.ID.ProjectileID.Sets.BreaksFromToyBreaker, Terraria.ID.TileID.Sets.BreaksToys, Terraria.Chat.ChatHelper.BroadcastChatMessage(), Terraria.GameContent.Drawing.ParticleOrchestrator.BroadcastOrRequestParticleSpawn(), Terraria.NPC.CanBeChasedBy(), Terraria.WorldGen.CanCutTile(), Terraria.Collision.CanHitLine(), Terraria.Entity.Center, Microsoft.Xna.Framework.MathHelper.Clamp(), Terraria.Dust.color, Terraria.ID.TileID.Sets.CrackedBricks, Terraria.GameContent.Damage, Terraria.Main.dedServ, Terraria.Entity.Distance(), Terraria.Main.dust, Terraria.ID.TileID.Sets.Falling, Terraria.ID.ProjectileID.Sets.FallingBlockDoesNotFallThroughPlatforms, Terraria.ID.ProjectileID.Sets.ForcePlateDetection, Terraria.Localization.NetworkText.FromKey(), Terraria.Utils.GetLerpValue(), Terraria.Item.GetPhaseColor(), Terraria.Player.GetTileCutIgnorance(), Terraria.Entity.height, Terraria.Collision.HitTiles(), Terraria.Collision.HitTilesInACircle(), Terraria.Main.hslToRgb(), int, Terraria.ID.ProjectileID.Sets.IsAPhaseblade, Terraria.ID.SoundID.Item10, Terraria.ID.SoundID.Item114, Terraria.ID.SoundID.Item115, Terraria.ID.SoundID.Item14, Terraria.ID.SoundID.Item177, Terraria.WorldGen.KillTile(), Terraria.Main.leftWorld, Microsoft.Xna.Framework.Vector2.Length(), Microsoft.Xna.Framework.MathHelper.Lerp(), Terraria.Main.maxNPCs, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, System.Math.Min(), Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Dust.NewDust(), Terraria.Dust.NewDustPerfect(), Terraria.Projectile.NewProjectile(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Microsoft.Xna.Framework.Vector2.Normalize(), Terraria.Main.npc, Microsoft.Xna.Framework.Vector2.One, Terraria.Projectile.owner, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Dust.position, Terraria.Entity.position, Terraria.Main.projectile, Terraria.Main.projPet, Terraria.Main.rand, Terraria.NPC.ReleaseNPC(), Terraria.GameContent.Drawing.ParticleOrchestrator.RequestParticleSpawn(), Terraria.Main.rightWorld, Terraria.Dust.scale, Terraria.NetMessage.SendData(), Terraria.Chat.ChatColors.ServerMessage, System.Math.Sign(), Terraria.Collision.SlopeCollision(), Terraria.Collision.SwitchTiles(), Terraria.Main.tile, Terraria.Collision.TileCollision(), Terraria.Projectile.timeLeft, Terraria.Main.topWorld, Microsoft.Xna.Framework.Color.Transparent, Terraria.GameContent.PortalHelper.TryPlacingPortal(), Terraria.Projectile.type, Terraria.Tile.type, Microsoft.Xna.Framework.Vector2.UnitX, Microsoft.Xna.Framework.Vector2.UnitY, Terraria.Dust.velocity, Microsoft.Xna.Framework.Vector4.W, Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.MathHelper.WrapAngle(), Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector4.X, Microsoft.Xna.Framework.Vector2.Y, Microsoft.Xna.Framework.Vector4.Y, Microsoft.Xna.Framework.Vector4.Z, Microsoft.Xna.Framework.Point.Zero, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.LeashedEntities.LeashedKite.MoveKite().