Terraria Decompiled: Terraria.Projectile.AI_165_Whip
AI_165_Whip()
void Terraria.Projectile.AI_165_Whip () inline private
Definition at line 48088 of file Projectile.cs.
        {
            if (this.type == 1035 && this.localAI[1] == 0f)
            {
                this.localAI[1] = (float)(1 + Main.rand.Next(3));
            }
            Player player = Main.player[this.owner];
            this.rotation = this.velocity.ToRotation() + 1.5707964f;
            this.ai[0] += 1f;
            float num = this.ai[1];
            float num2;
            int num3;
            float num4;
            Projectile.GetWhipSettings(this, out num2, out num3, out num4);
            base.Center = Main.GetPlayerArmPosition(this, player) + this.velocity * (this.ai[0] - 1f);
            this.spriteDirection = ((Vector2.Dot(this.velocity, Vector2.UnitX) < 0f) ? (-1) : 1);
            if (this.ai[0] >= num2)
            {
                this.Kill();
                return;
            }
            bool flag = true;
            if (this.type == 1035 && this.ai[2] >= 10f)
            {
                flag = false;
            }
            if (flag)
            {
                player.heldProj = this.whoAmI;
                player.MatchItemTimeToItemAnimation();
            }
            else
            {
                this.drawLayer = 0;
            }
            if (this.type == 1035 && this.owner == Main.myPlayer && this.ai[2] < 10f)
            {
                int num5 = 3;
                float num6 = this.ai[0] / num2 * (float)num5;
                if (this.ai[2] < num6)
                {
                    this.ai[2] += 1f;
                    Vector2 vector = Main.ReverseGravitySupport(Main.MouseScreen, 0f) + Main.screenPosition;
                    Vector2 vector2 = player.DirectionTo(vector).SafeNormalize(this.velocity) * this.velocity.Length();
                    Projectile.NewProjectile(this.GetProjectileSource_FromThis(), player.Center.X, player.Center.Y, vector2.X, vector2.Y, this.type, this.damage, this.knockBack, this.owner, 0f, Main.rand.NextFloatDirection(), 10f + this.ai[2], null);
                }
            }
            if (this.ai[0] == (float)((int)(num2 / 2f)))
            {
                this.WhipPointsForCollision.Clear();
                Projectile.FillWhipControlPoints(this, this.WhipPointsForCollision, null, false);
                Vector2 vector3 = this.WhipPointsForCollision[this.WhipPointsForCollision.Count - 1];
                if (this.type == 1029)
                {
                    SoundEngine.PlaySound(SoundID.NPCDeath1, vector3, 0f, 0.6f);
                }
                else if (this.type == 1030)
                {
                    SoundEngine.PlaySound(SoundID.NPCHit9, vector3, 0f, 1f);
                }
                else if (this.type == 1033)
                {
                    SoundEngine.PlaySound(SoundID.Item193, vector3, 0f, 1f);
                }
                else
                {
                    SoundEngine.PlaySound(SoundID.Item153, vector3, 0f, 1f);
                }
            }
            if (this.type == 1104 && this.ai[0] == (float)((int)(num2 / 3f) * 2))
            {
                this.WhipPointsForCollision.Clear();
                Projectile.FillWhipControlPoints(this, this.WhipPointsForCollision, null, false);
                Vector2 vector4 = this.WhipPointsForCollision[this.WhipPointsForCollision.Count - 1];
                if (this.type == 1104)
                {
                    for (int i = 0; i < 15; i++)
                    {
                        Dust dust = Dust.NewDustPerfect(vector4, 6, new Vector2?(Main.rand.NextVector2Circular(4f, 4f)), 0, default(Color), 1f);
                        dust.scale = 1f + Main.rand.NextFloat();
                        if (Main.rand.Next(15) != 0)
{
                            dust.noLightEmittance = true;
                        }
                        else
{
                            dust.scale *= 0.4f;
                        }
                        if (Main.rand.Next(2) == 0)
{
                            dust.noGravity = true;
                        }
                        else
{
                            dust.velocity *= 0.3f;
                            dust.scale -= 0.5f;
                        }
                        dust.velocity += this.velocity * 0.7f;
                        dust.position -= dust.velocity * 2f;
                    }
                    for (int j = 0; j < 6; j++)
                    {
                        Dust dust2 = Dust.NewDustPerfect(vector4, 31, new Vector2?(Main.rand.NextVector2Circular(4f, 4f)), 0, default(Color), 1f);
                        dust2.scale = 0.3f + 0.3f * Main.rand.NextFloat();
                        if (Main.rand.Next(2) == 0)
{
                            dust2.noGravity = true;
                        }
                        else
{
                            dust2.velocity = dust2.velocity * 0.3f + this.velocity * 0.6f;
                        }
                    }
                }
            }
            int num7 = this.type;
            if (num7 <= 915)
            {
                switch (num7)
                {
                case 847:
                {
                    float num8 = this.ai[0] / num2;
                    if (Utils.GetLerpValue(0.1f, 0.7f, num8, true) * Utils.GetLerpValue(0.9f, 0.7f, num8, true) > 0.5f && Main.rand.Next(3) != 0)
                    {
                        this.WhipPointsForCollision.Clear();
                        Projectile.FillWhipControlPoints(this, this.WhipPointsForCollision, null, false);
                        int num9 = Main.rand.Next(this.WhipPointsForCollision.Count - 10, this.WhipPointsForCollision.Count);
                        Rectangle rectangle = Utils.CenteredRectangle(this.WhipPointsForCollision[num9], new Vector2(30f, 30f));
                        int num10 = 57;
                        if (Main.rand.Next(3) == 0)
{
                            num10 = 43;
                        }
                        Dust dust3 = Dust.NewDustDirect(rectangle.TopLeft(), rectangle.Width, rectangle.Height, num10, 0f, 0f, 100, Color.White, 1f);
                        dust3.position = this.WhipPointsForCollision[num9];
                        dust3.fadeIn = 0.3f;
                        Vector2 vector5 = this.WhipPointsForCollision[num9] - this.WhipPointsForCollision[num9 - 1];
                        dust3.noGravity = true;
                        dust3.velocity *= 0.5f;
                        dust3.velocity += vector5.RotatedBy((double)((float)player.direction * 1.5707964f), default(Vector2));
                        dust3.velocity *= 0.5f;
                        return;
                    }
                    break;
                }
                case 848:
                {
                    float num11 = this.ai[0] / num2;
                    float num12 = Utils.GetLerpValue(0.1f, 0.7f, num11, true) * Utils.GetLerpValue(0.9f, 0.7f, num11, true);
                    if (num12 > 0.1f && Main.rand.NextFloat() < num12 / 2f)
                    {
                        this.WhipPointsForCollision.Clear();
                        Projectile.FillWhipControlPoints(this, this.WhipPointsForCollision, null, false);
                        Rectangle rectangle2 = Utils.CenteredRectangle(this.WhipPointsForCollision[this.WhipPointsForCollision.Count - 1], new Vector2(30f, 30f));
                        int num13 = Dust.NewDust(rectangle2.TopLeft(), rectangle2.Width, rectangle2.Height, 172, 0f, 0f, 100, default(Color), 1.5f);
                        Main.dust[num13].noGravity = true;
                        Dust dust4 = Main.dust[num13];
                        dust4.velocity.X = dust4.velocity.X / 2f;
                        Dust dust5 = Main.dust[num13];
                        dust5.velocity.Y = dust5.velocity.Y / 2f;
                        return;
                    }
                    break;
                }
                case 849:
                {
                    float num14 = this.ai[0] / num2;
                    Utils.GetLerpValue(0.1f, 0.7f, num14, true);
                    Utils.GetLerpValue(0.9f, 0.7f, num14, true);
                    if (num14 > 0.4f && Main.rand.Next(9) != 0)
                    {
                        this.WhipPointsForCollision.Clear();
                        Projectile.FillWhipControlPoints(this, this.WhipPointsForCollision, null, false);
                        Rectangle rectangle3 = Utils.CenteredRectangle(this.WhipPointsForCollision[this.WhipPointsForCollision.Count - 1], new Vector2(30f, 30f));
                        Vector2 vector6 = this.WhipPointsForCollision[this.WhipPointsForCollision.Count - 2].DirectionTo(this.WhipPointsForCollision[this.WhipPointsForCollision.Count - 1]).SafeNormalize(Vector2.Zero);
                        Dust dust6 = Dust.NewDustDirect(rectangle3.TopLeft(), rectangle3.Width, rectangle3.Height, 191, 0f, 0f, 0, default(Color), 1.3f);
                        dust6.noGravity = true;
                        dust6.velocity += vector6 * 2f;
                        if (Main.rand.Next(2) == 0)
{
                            ParticleOrchestrator.RequestParticleSpawn(true, ParticleOrchestraType.BlackLightningSmall, new ParticleOrchestraSettings
{
                                MovementVector = vector6,
                                PositionInWorld = rectangle3.Center.ToVector2()
                            }, new int?(this.owner));
                        }
                        Lighting.AddLight(rectangle3.Center.ToVector2(), new Vector3(0.2f, 0f, 0.4f));
                        return;
                    }
                    break;
                }
                default:
                    switch (num7)
                    {
                    case 912:
                    {
                        float num15 = this.ai[0] / num2;
                        float num16 = Utils.GetLerpValue(0.1f, 0.7f, num15, true) * Utils.GetLerpValue(0.9f, 0.7f, num15, true);
                        if (num16 > 0.1f && Main.rand.NextFloat() < num16 / 2f)
{
                            this.WhipPointsForCollision.Clear();
                            Projectile.FillWhipControlPoints(this, this.WhipPointsForCollision, null, false);
                            Rectangle rectangle4 = Utils.CenteredRectangle(this.WhipPointsForCollision[this.WhipPointsForCollision.Count - 1], new Vector2(30f, 30f));
                            Vector2 vector7 = this.WhipPointsForCollision[this.WhipPointsForCollision.Count - 2].DirectionTo(this.WhipPointsForCollision[this.WhipPointsForCollision.Count - 1]).SafeNormalize(Vector2.Zero);
                            for (int k = 0; k < 3; k++)
{
                                Dust dust7 = Dust.NewDustDirect(rectangle4.TopLeft(), rectangle4.Width, rectangle4.Height, 16, 0f, 0f, 0, default(Color), 1.2f);
                                dust7.noGravity = true;
                                dust7.velocity += vector7 * 2f;
                            }
                            for (int l = 0; l < 1; l++)
{
                                Dust.NewDustDirect(rectangle4.TopLeft(), rectangle4.Width, rectangle4.Height, 13, 0f, 0f, 0, default(Color), 0.8f).velocity += vector7 * 2f;
                            }
                            for (int m = 0; m < 3; m++)
{
                                if (Main.rand.Next(2) != 0)
{
                                    Dust dust8 = Dust.NewDustDirect(rectangle4.TopLeft(), rectangle4.Width, rectangle4.Height, 261, 0f, 0f, 0, Color.Transparent, 0.8f);
                                    dust8.velocity += vector7 * 2f;
                                    dust8.velocity *= 0.3f;
                                    dust8.noGravity = true;
                                }
                            }
                            Lighting.AddLight(rectangle4.Center.ToVector2(), new Vector3(0.1f, 0.1f, 0.2f));
                            return;
                        }
                        break;
                    }
                    case 913:
                    {
                        float num17 = this.ai[0] / num2;
                        float num18 = Utils.GetLerpValue(0.1f, 0.7f, num17, true) * Utils.GetLerpValue(0.9f, 0.7f, num17, true);
                        if (num18 > 0.1f && Main.rand.NextFloat() < num18)
{
                            this.WhipPointsForCollision.Clear();
                            Projectile.FillWhipControlPoints(this, this.WhipPointsForCollision, null, false);
                            Rectangle rectangle5 = Utils.CenteredRectangle(this.WhipPointsForCollision[this.WhipPointsForCollision.Count - 1], new Vector2(20f, 20f));
                            Vector2 vector8 = this.WhipPointsForCollision[this.WhipPointsForCollision.Count - 2].DirectionTo(this.WhipPointsForCollision[this.WhipPointsForCollision.Count - 1]).SafeNormalize(Vector2.Zero);
                            for (int n = 0; n < 3; n++)
{
                                if (Main.rand.Next(3) == 0)
{
                                    if (Main.rand.Next(7) == 0)
{
                                        Dust dust9 = Dust.NewDustDirect(rectangle5.TopLeft(), rectangle5.Width, rectangle5.Height, 31, 0f, 0f, 0, default(Color), 1f);
                                        dust9.velocity.X = dust9.velocity.X / 2f;
                                        dust9.velocity.Y = dust9.velocity.Y / 2f;
                                        dust9.velocity += vector8 * 2f;
                                        dust9.fadeIn = 1f + Main.rand.NextFloat() * 0.6f;
                                        dust9.noGravity = true;
                                    }
                                    else
{
                                        Dust dust10 = Dust.NewDustDirect(rectangle5.TopLeft(), rectangle5.Width, rectangle5.Height, 6, 0f, 0f, 0, default(Color), 1.2f);
                                        dust10.velocity += vector8 * 2f;
                                        if (Main.rand.Next(3) != 0)
{
                                            dust10.fadeIn = 0.7f + Main.rand.NextFloat() * 0.9f;
                                            dust10.scale = 0.6f;
                                            dust10.noGravity = true;
                                        }
                                    }
                                }
                            }
                            return;
                        }
                        break;
                    }
                    case 914:
                    {
                        float num19 = this.ai[0] / num2;
                        float num20 = Utils.GetLerpValue(0.1f, 0.7f, num19, true) * Utils.GetLerpValue(0.9f, 0.7f, num19, true);
                        if (num20 > 0.1f && Main.rand.NextFloat() < num20 / 2f)
{
                            this.WhipPointsForCollision.Clear();
                            Projectile.FillWhipControlPoints(this, this.WhipPointsForCollision, null, false);
                            Rectangle rectangle6 = Utils.CenteredRectangle(this.WhipPointsForCollision[this.WhipPointsForCollision.Count - 1], new Vector2(30f, 30f));
                            Vector2 vector9 = this.WhipPointsForCollision[this.WhipPointsForCollision.Count - 2].DirectionTo(this.WhipPointsForCollision[this.WhipPointsForCollision.Count - 1]).SafeNormalize(Vector2.Zero);
                            Dust dust11 = Dust.NewDustDirect(rectangle6.TopLeft(), rectangle6.Width, rectangle6.Height, 39, 0f, 0f, 0, default(Color), 1.2f);
                            dust11.noGravity = Main.rand.Next(3) == 0;
                            dust11.velocity += vector9 * 2f;
                            return;
                        }
                        break;
                    }
                    case 915:
                    {
                        float num21 = this.ai[0] / num2;
                        if (Utils.GetLerpValue(0.1f, 0.7f, num21, true) * Utils.GetLerpValue(0.9f, 0.7f, num21, true) > 0.1f)
{
                            this.WhipPointsForCollision.Clear();
                            Projectile.FillWhipControlPoints(this, this.WhipPointsForCollision, null, false);
                            Rectangle rectangle7 = Utils.CenteredRectangle(this.WhipPointsForCollision[this.WhipPointsForCollision.Count - 1], new Vector2(30f, 30f));
                            Vector2 vector10 = this.WhipPointsForCollision[this.WhipPointsForCollision.Count - 2].DirectionTo(this.WhipPointsForCollision[this.WhipPointsForCollision.Count - 1]).SafeNormalize(Vector2.Zero);
                            Dust dust12 = Dust.NewDustDirect(rectangle7.TopLeft(), rectangle7.Width, rectangle7.Height, 267, 0f, 0f, 0, Main.hslToRgb(player.miscCounterNormalized * 9f % 1f, 1f, 0.5f, byte.MaxValue), 1.3f);
                            dust12.velocity *= Main.rand.NextFloat() * 0.8f;
                            dust12.noGravity = true;
                            dust12.scale = 0.9f + Main.rand.NextFloat() * 0.9f;
                            dust12.fadeIn = Main.rand.NextFloat() * 0.9f;
                            dust12.velocity += vector10 * 2f;
                            if (dust12.dustIndex != 6000)
{
                                Dust dust13 = Dust.CloneDust(dust12);
                                dust13.scale /= 2f;
                                dust13.fadeIn *= 0.85f;
                                dust13.color = new Color(255, 255, 255, 255);
                                return;
                            }
                        }
                        break;
                    }
                    default:
                        return;
                    }
                    break;
                }
            }
            else if (num7 != 952)
            {
                switch (num7)
                {
                case 1028:
                {
                    float num22 = this.ai[0] / num2;
                    float num23 = Utils.GetLerpValue(0.1f, 0.7f, num22, true) * Utils.GetLerpValue(0.9f, 0.7f, num22, true);
                    if (num23 > 0.15f && Main.rand.NextFloat() < num23 && Main.rand.Next(2) == 0)
                    {
                        this.WhipPointsForCollision.Clear();
                        Projectile.FillWhipControlPoints(this, this.WhipPointsForCollision, null, false);
                        Rectangle rectangle8 = Utils.CenteredRectangle(this.WhipPointsForCollision[this.WhipPointsForCollision.Count - 1], new Vector2(30f, 30f));
                        Vector2 vector11 = this.WhipPointsForCollision[this.WhipPointsForCollision.Count - 2].DirectionTo(this.WhipPointsForCollision[this.WhipPointsForCollision.Count - 1]).SafeNormalize(Vector2.Zero);
                        Dust dust14 = Dust.NewDustDirect(rectangle8.TopLeft(), rectangle8.Width, rectangle8.Height, 30, 0f, 0f, 0, default(Color), 0.7f);
                        dust14.noGravity = Main.rand.Next(3) == 0;
                        if (dust14.noGravity)
{
                            dust14.scale += 0.3f;
                        }
                        dust14.velocity += vector11 * 2f;
                        return;
                    }
                    break;
                }
                case 1029:
                {
                    float num24 = this.ai[0] / num2;
                    if (Utils.GetLerpValue(0.1f, 0.7f, num24, true) * Utils.GetLerpValue(0.9f, 0.7f, num24, true) > 0.6f && Main.rand.Next(2) == 0)
                    {
                        this.WhipPointsForCollision.Clear();
                        Projectile.FillWhipControlPoints(this, this.WhipPointsForCollision, null, false);
                        Rectangle rectangle9 = Utils.CenteredRectangle(this.WhipPointsForCollision[this.WhipPointsForCollision.Count - 1], new Vector2(30f, 30f));
                        for (int num25 = 0; num25 < 2; num25++)
{
                            short num26 = ((Main.rand.Next(2) == 0) ? 18 : 184);
                            Vector2 vector12 = this.WhipPointsForCollision[this.WhipPointsForCollision.Count - 2].DirectionTo(this.WhipPointsForCollision[this.WhipPointsForCollision.Count - 1]).SafeNormalize(Vector2.Zero);
                            Dust dust15 = Dust.NewDustDirect(rectangle9.TopLeft(), rectangle9.Width, rectangle9.Height, (int)num26, 0f, 0f, 0, default(Color), 0.7f);
                            dust15.noGravity = num26 == 184 || Main.rand.Next(3) == 0;
                            if (dust15.noGravity)
{
                                dust15.scale += 0.3f;
                            }
                            dust15.velocity += vector12 * 2f;
                        }
                        return;
                    }
                    break;
                }
                case 1030:
                {
                    float num27 = this.ai[0] / num2;
                    if (Utils.GetLerpValue(0.1f, 0.7f, num27, true) * Utils.GetLerpValue(0.9f, 0.7f, num27, true) > 0.6f && Main.rand.Next(4) != 0)
                    {
                        this.WhipPointsForCollision.Clear();
                        Projectile.FillWhipControlPoints(this, this.WhipPointsForCollision, null, false);
                        for (int num28 = this.WhipPointsForCollision.Count / 2; num28 < this.WhipPointsForCollision.Count; num28++)
{
                            if (Main.rand.Next(6) == 0 || num28 == this.WhipPointsForCollision.Count - 1)
{
                                Rectangle rectangle10 = Utils.CenteredRectangle(this.WhipPointsForCollision[num28], new Vector2(30f, 30f));
                                int num29 = ((num28 == this.WhipPointsForCollision.Count - 1) ? 4 : 1);
                                for (int num30 = 0; num30 < num29; num30++)
{
                                    short num31 = ((Main.rand.Next(2) == 0) ? 115 : 5);
                                    Vector2 vector13 = this.WhipPointsForCollision[num28 - 1].DirectionTo(this.WhipPointsForCollision[num28]).SafeNormalize(Vector2.Zero);
                                    Dust dust16 = Dust.NewDustDirect(rectangle10.TopLeft(), rectangle10.Width, rectangle10.Height, (int)num31, 0f, 0f, 0, default(Color), 0.3f + 0.3f * Main.rand.NextFloat());
                                    dust16.velocity += vector13 * 3f * Main.rand.NextFloat();
                                    dust16.velocity *= 0.5f;
                                    Dust dust17 = dust16;
                                    dust17.velocity.X = dust17.velocity.X + (float)player.direction * 2f;
                                    dust16.velocity += player.velocity * Main.rand.NextFloat();
                                    dust16.fadeIn = dust16.scale * 1.1f;
                                    if (num30 > 0)
{
                                        dust16.alpha = Main.rand.Next(0, 200);
                                    }
                                }
                            }
                        }
                        return;
                    }
                    break;
                }
                case 1031:
                {
                    float num32 = this.ai[0] / num2;
                    float num33 = Utils.GetLerpValue(0.1f, 0.7f, num32, true) * Utils.GetLerpValue(0.9f, 0.7f, num32, true);
                    if (num33 > 0.1f && Main.rand.NextFloat() < num33)
                    {
                        this.WhipPointsForCollision.Clear();
                        Projectile.FillWhipControlPoints(this, this.WhipPointsForCollision, null, false);
                        Rectangle rectangle11 = Utils.CenteredRectangle(this.WhipPointsForCollision[this.WhipPointsForCollision.Count - 1], new Vector2(20f, 20f));
                        Vector2 vector14 = this.WhipPointsForCollision[this.WhipPointsForCollision.Count - 2].DirectionTo(this.WhipPointsForCollision[this.WhipPointsForCollision.Count - 1]).SafeNormalize(Vector2.Zero);
                        for (int num34 = 0; num34 < 4; num34++)
{
                            if (Main.rand.Next(3) == 0)
{
                                Dust dust18 = Dust.NewDustDirect(rectangle11.TopLeft(), rectangle11.Width, rectangle11.Height, 6, 0f, 0f, 0, default(Color), 1f);
                                dust18.velocity += vector14 * 1.5f;
                                if (Main.rand.Next(3) != 0)
{
                                    dust18.velocity += vector14;
                                    dust18.fadeIn = 0.7f + Main.rand.NextFloat() * 0.9f;
                                    dust18.scale = 0.7f;
                                    dust18.noGravity = true;
                                }
                            }
                        }
                        return;
                    }
                    break;
                }
                case 1032:
                {
                    float num35 = this.ai[0] / num2;
                    float num36 = Utils.GetLerpValue(0.1f, 0.7f, num35, true) * Utils.GetLerpValue(0.9f, 0.7f, num35, true);
                    if (num36 > 0.6f && Main.rand.NextFloat() < num36 && Main.rand.Next(3) != 0)
                    {
                        this.WhipPointsForCollision.Clear();
                        Projectile.FillWhipControlPoints(this, this.WhipPointsForCollision, null, false);
                        for (int num37 = 0; num37 < this.WhipPointsForCollision.Count - 1; num37 += 2)
{
                            float num38 = (float)num37 / (float)this.WhipPointsForCollision.Count;
                            if (Main.rand.NextFloat() < num38 * num38)
{
                                Vector2 vector15 = this.WhipPointsForCollision[num37].DirectionTo(this.WhipPointsForCollision[num37 + 1]).SafeNormalize(Vector2.Zero);
                                Rectangle rectangle12 = Utils.CenteredRectangle(this.WhipPointsForCollision[num37 + 1], new Vector2(30f, 30f));
                                Dust dust19;
                                for (int num39 = 0; num39 < 2; num39++)
{
                                    short num40 = ((Main.rand.Next(2) == 0) ? 167 : 166);
                                    dust19 = Dust.NewDustDirect(rectangle12.TopLeft(), rectangle12.Width, rectangle12.Height, (int)num40, 0f, 0f, 0, default(Color), 1f);
                                    dust19.noGravity = Main.rand.Next(3) != 0;
                                    if (dust19.noGravity)
{
                                        dust19.scale += 0.2f;
                                    }
                                    dust19.velocity += vector15 * 2f;
                                }
                                dust19 = Dust.NewDustDirect(rectangle12.TopLeft(), rectangle12.Width, rectangle12.Height, 166, 0f, 0f, 0, default(Color), 1f);
                                dust19.noGravity = Main.rand.Next(3) != 0;
                                if (dust19.noGravity)
{
                                    dust19.scale += 0.2f;
                                }
                                dust19.velocity += vector15 * 2f;
                                dust19 = Dust.NewDustDirect(rectangle12.TopLeft(), rectangle12.Width, rectangle12.Height, 167, 0f, 0f, 0, default(Color), 1f);
                                dust19.noGravity = Main.rand.Next(3) != 0;
                                if (dust19.noGravity)
{
                                    dust19.scale += 0.2f;
                                }
                                dust19.velocity += vector15 * 2f;
                            }
                        }
                        return;
                    }
                    break;
                }
                case 1033:
                {
                    float num41 = this.ai[0] / num2;
                    Utils.GetLerpValue(0.1f, 0.7f, num41, true);
                    Utils.GetLerpValue(0.9f, 0.7f, num41, true);
                    this.WhipPointsForCollision.Clear();
                    Projectile.FillWhipControlPoints(this, this.WhipPointsForCollision, null, false);
                    for (int num42 = 10; num42 < this.WhipPointsForCollision.Count - 1; num42++)
                    {
                        Vector2 vector16 = this.WhipPointsForCollision[num42].DirectionTo(this.WhipPointsForCollision[num42 + 1]).SafeNormalize(Vector2.Zero);
                        Rectangle rectangle13 = Utils.CenteredRectangle(this.WhipPointsForCollision[num42 + 1], new Vector2(30f, 30f));
                        if (Main.rand.Next(5) == 0 && Main.rand.NextFloat() <= num41)
{
                            if (Main.rand.Next(3) == 0)
{
                                int num43 = 1;
                                for (int num44 = 0; num44 < num43; num44++)
{
                                    Vector2 vector17 = ((float)(Main.rand.NextDouble() * 3.1415927410125732) - 1.5707964f).ToRotationVector2() * (float)Main.rand.Next(3, 8);
                                    int num45 = Dust.NewDust(rectangle13.TopLeft(), rectangle13.Width, rectangle13.Height, 217, vector17.X * 2f, vector17.Y * 2f, 100, default(Color), 1.4f);
                                    Main.dust[num45].noGravity = true;
                                    Main.dust[num45].noLight = true;
                                    Main.dust[num45].velocity /= 4f;
                                    Main.dust[num45].velocity += vector16 * 3f;
                                }
                            }
                            else if (Main.rand.Next(4) == 0)
{
                                for (int num46 = 0; num46 < 1; num46++)
{
                                    Dust dust20 = Dust.NewDustDirect(rectangle13.TopLeft(), rectangle13.Width, rectangle13.Height, 226, 0f, 0f, 0, default(Color), 0.7f);
                                    dust20.noGravity = Main.rand.Next(3) == 0;
                                    if (dust20.noGravity)
{
                                        dust20.scale += 0.3f;
                                    }
                                    dust20.velocity += vector16.RotatedByRandom(0.19634954631328583) * 2f;
                                }
                            }
                        }
                    }
                    return;
                }
                case 1034:
                {
                    float num47 = this.ai[0] / num2;
                    if (Utils.GetLerpValue(0.1f, 0.7f, num47, true) * Utils.GetLerpValue(0.9f, 0.7f, num47, true) > 0.5f && Main.rand.Next(3) != 0)
                    {
                        this.WhipPointsForCollision.Clear();
                        Projectile.FillWhipControlPoints(this, this.WhipPointsForCollision, null, false);
                        int num48 = Main.rand.Next(this.WhipPointsForCollision.Count - 10, this.WhipPointsForCollision.Count);
                        Rectangle rectangle14 = Utils.CenteredRectangle(this.WhipPointsForCollision[num48], new Vector2(30f, 30f));
                        int num49 = 135;
                        Dust dust21 = Dust.NewDustDirect(rectangle14.TopLeft(), rectangle14.Width, rectangle14.Height, num49, 0f, 0f, 100, Color.White, 1.5f);
                        dust21.position = this.WhipPointsForCollision[num48];
                        dust21.fadeIn = 0.3f;
                        Vector2 vector18 = this.WhipPointsForCollision[num48] - this.WhipPointsForCollision[num48 - 1];
                        dust21.noGravity = true;
                        dust21.velocity *= 0.5f;
                        dust21.velocity += vector18.RotatedBy((double)((float)player.direction * 1.5707964f * (float)Math.Sign(num)), default(Vector2));
                        dust21.velocity *= 0.5f;
                        return;
                    }
                    break;
                }
                case 1035:
                {
                    float num50 = this.ai[0] / num2;
                    if (Utils.GetLerpValue(0.1f, 0.7f, num50, true) * Utils.GetLerpValue(0.9f, 0.7f, num50, true) > 0.5f && Main.rand.Next(3) != 0)
                    {
                        this.WhipPointsForCollision.Clear();
                        Projectile.FillWhipControlPoints(this, this.WhipPointsForCollision, null, false);
                        int num51 = Main.rand.Next(this.WhipPointsForCollision.Count - 8, this.WhipPointsForCollision.Count);
                        Rectangle rectangle15 = Utils.CenteredRectangle(this.WhipPointsForCollision[num51], new Vector2(20f, 20f));
                        int num52 = 306;
                        Dust dust22 = Dust.NewDustDirect(rectangle15.TopLeft(), rectangle15.Width, rectangle15.Height, num52, 0f, 0f, 100, new Color(147, 255, 220), 1.6f);
                        dust22.position = this.WhipPointsForCollision[num51];
                        Vector2 vector19 = this.WhipPointsForCollision[num51] - this.WhipPointsForCollision[num51 - 1];
                        dust22.noGravity = Main.rand.Next(2) == 0;
                        if (!dust22.noGravity)
{
                            dust22.scale *= 0.5f;
                        }
                        dust22.velocity = this.velocity.SafeNormalize(this.velocity) * vector19.Length();
                        dust22.velocity *= 0.5f;
                        dust22.velocity = dust22.velocity.RotatedBy((double)(Main.rand.NextFloatDirection() * 6.2831855f * 0.1f), default(Vector2));
                        Dust dust23 = Dust.NewDustPerfect(this.WhipPointsForCollision[num51], 229, new Vector2?(dust22.velocity), 0, default(Color), 1f);
                        dust23.noGravity = true;
                        dust23.scale = 0.3f + 1.1f * Main.rand.NextFloat();
                        dust23.velocity *= dust23.scale;
                        dust23.velocity *= Main.rand.NextFloat();
                        return;
                    }
                    break;
                }
                default:
                {
                    if (num7 != 1104)
                    {
                        return;
                    }
                    float num53 = this.ai[0] / num2;
                    float num54 = Utils.GetLerpValue(0.1f, 0.7f, num53, true) * Utils.GetLerpValue(0.9f, 0.7f, num53, true);
                    if (num54 > 0.15f && Main.rand.NextFloat() < num54 && Main.rand.Next(2) == 0)
                    {
                        this.WhipPointsForCollision.Clear();
                        Projectile.FillWhipControlPoints(this, this.WhipPointsForCollision, null, false);
                        for (int num55 = this.WhipPointsForCollision.Count - 1; num55 >= 1; num55 -= 3)
{
                            if (num55 == this.WhipPointsForCollision.Count - 1 || Main.rand.Next(20) == 0)
{
                                Rectangle rectangle16 = Utils.CenteredRectangle(this.WhipPointsForCollision[num55], new Vector2(30f, 30f));
                                Vector2 vector20 = this.WhipPointsForCollision[num55 - 1].DirectionTo(this.WhipPointsForCollision[num55]).SafeNormalize(Vector2.Zero);
                                Dust dust24 = Dust.NewDustDirect(rectangle16.TopLeft(), rectangle16.Width, rectangle16.Height, 4, 0f, 0f, 84, new Color(78, 136, 255, 127), 1f);
                                dust24.scale = 1f + Main.rand.NextFloat() * 0.3f;
                                dust24.velocity += vector20 * Main.rand.NextFloat() * 5f;
                                if (Main.rand.Next(4) == 0)
{
                                    dust24.noGravity = true;
                                }
                                else
{
                                    dust24.velocity *= 0.3f;
                                    dust24.scale -= 0.4f;
                                    dust24.velocity += this.velocity * 0.5f;
                                }
                            }
                        }
                    }
                    break;
                }
                }
            }
            else
            {
                float num56 = this.ai[0] / num2;
                float num57 = Utils.GetLerpValue(0.1f, 0.7f, num56, true) * Utils.GetLerpValue(0.9f, 0.7f, num56, true);
                if (num57 > 0.15f && Main.rand.NextFloat() < num57)
                {
                    this.WhipPointsForCollision.Clear();
                    Projectile.FillWhipControlPoints(this, this.WhipPointsForCollision, null, false);
                    Rectangle rectangle17 = Utils.CenteredRectangle(this.WhipPointsForCollision[this.WhipPointsForCollision.Count - 1], new Vector2(30f, 30f));
                    Vector2 vector21 = this.WhipPointsForCollision[this.WhipPointsForCollision.Count - 2].DirectionTo(this.WhipPointsForCollision[this.WhipPointsForCollision.Count - 1]).SafeNormalize(Vector2.Zero);
                    Dust dust25 = Dust.NewDustDirect(rectangle17.TopLeft(), rectangle17.Width, rectangle17.Height, 26, 0f, 0f, 0, default(Color), 0.7f);
                    dust25.noGravity = Main.rand.Next(3) == 0;
                    if (dust25.noGravity)
                    {
                        dust25.scale += 0.4f;
                    }
                    dust25.velocity += vector21 * 2f;
                    return;
                }
            }
        }
References Terraria.Lighting.AddLight(), Microsoft.Xna.Framework.Rectangle.Center, Terraria.Entity.Center, Terraria.Utils.CenteredRectangle(), Terraria.Dust.CloneDust(), Terraria.Entity.direction, Terraria.Entity.DirectionTo(), Microsoft.Xna.Framework.Vector2.Dot(), Terraria.Main.dust, Terraria.Dust.dustIndex, Terraria.Projectile.FillWhipControlPoints(), Terraria.Utils.GetLerpValue(), Terraria.Main.GetPlayerArmPosition(), Terraria.Projectile.GetWhipSettings(), Microsoft.Xna.Framework.Rectangle.Height, Terraria.Main.hslToRgb(), int, Terraria.ID.SoundID.Item153, Terraria.ID.SoundID.Item193, Microsoft.Xna.Framework.Vector2.Length(), Terraria.Player.MatchItemTimeToItemAnimation(), Terraria.Player.miscCounterNormalized, Terraria.Main.MouseScreen, Terraria.Main.myPlayer, Terraria.Dust.NewDust(), Terraria.Dust.NewDustDirect(), Terraria.Dust.NewDustPerfect(), Terraria.Projectile.NewProjectile(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Terraria.ID.SoundID.NPCDeath1, Terraria.ID.SoundID.NPCHit9, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.rand, Terraria.GameContent.Drawing.ParticleOrchestrator.RequestParticleSpawn(), Terraria.Main.ReverseGravitySupport(), Terraria.Main.screenPosition, Microsoft.Xna.Framework.Color.Transparent, Microsoft.Xna.Framework.Vector2.UnitX, Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Rectangle.Width, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.