Terraria Decompiled: Terraria.Projectile.ExplodeCrackedTiles
ExplodeCrackedTiles()
void Terraria.Projectile.ExplodeCrackedTiles (Vector2 compareSpot, int radius, int minI, int maxI, int minJ, int maxJ) inline
Definition at line 80968 of file Projectile.cs.
        {
            AchievementsHelper.CurrentlyMining = true;
            for (int i = minI; i <= maxI; i++)
            {
                for (int j = minJ; j <= maxJ; j++)
                {
                    float num = Math.Abs((float)i - compareSpot.X / 16f);
                    float num2 = Math.Abs((float)j - compareSpot.Y / 16f);
                    if (Math.Sqrt((double)(num * num + num2 * num2)) < (double)radius && Main.tile[i, j] != null && Main.tile[i, j].active() && TileID.Sets.CrackedBricks[(int)Main.tile[i, j].type])
                    {
                        WorldGen.KillTile(i, j, false, false, false);
                        if (!Main.tile[i, j].active() && Main.netMode != 0)
{
                            NetMessage.SendData(17, -1, -1, null, 20, (float)i, (float)j, 0f, 0, 0, 0);
                        }
                    }
                }
            }
            AchievementsHelper.CurrentlyMining = false;
        }
References System.Math.Abs(), Terraria.Tile.active(), Terraria.ID.TileID.Sets.CrackedBricks, Terraria.WorldGen.KillTile(), Terraria.Main.netMode, Terraria.NetMessage.SendData(), System.Math.Sqrt(), Terraria.Main.tile, Terraria.Tile.type, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.