Terraria Decompiled: Terraria.Projectile.AI_061_FishingBobber
AI_061_FishingBobber()
void Terraria.Projectile.AI_061_FishingBobber () inline private
Definition at line 54057 of file Projectile.cs.
        {
            Player player = Main.player[this.owner];
            bool flag = this.type >= 986 && this.type <= 993;
            this.timeLeft = 60;
            bool flag2 = false;
            if (player.inventory[player.selectedItem].fishingPole == 0 || player.CCed || player.noItems)
            {
                flag2 = true;
            }
            else if (player.inventory[player.selectedItem].shoot != this.type && !flag)
            {
                flag2 = true;
            }
            else if (player.pulley)
            {
                flag2 = true;
            }
            else if (player.dead)
            {
                flag2 = true;
            }
            if (flag2)
            {
                this.Kill();
                return;
            }
            player.afkCounterForKiting = 0;
            if (this.ai[1] > 0f && this.localAI[1] != 0f)
            {
                this.localAI[1] = 0f;
                if (!this.lavaWet && !this.honeyWet)
                {
                    this.AI_061_FishingBobber_DoASplash();
                }
            }
            if (this.ai[0] >= 1f)
            {
                if (this.ai[0] == 2f)
                {
                    this.ai[0] += 1f;
                    SoundEngine.PlaySound(SoundID.Item17, this.position, 0f, 1f);
                    if (!this.lavaWet && !this.honeyWet)
                    {
                        this.AI_061_FishingBobber_DoASplash();
                    }
                }
                if (this.localAI[0] < 100f)
                {
                    this.localAI[0] += 1f;
                }
                if (this.frameCounter == 0)
                {
                    this.frameCounter = 1;
                    this.ReduceRemainingChumsInPool();
                }
                this.tileCollide = false;
                float num = 15.9f;
                int num2 = 10;
                Vector2 vector = new Vector2(this.position.X + (float)this.width * 0.5f, this.position.Y + (float)this.height * 0.5f);
                float num3 = player.position.X + (float)(player.width / 2) - vector.X;
                float num4 = player.position.Y + (float)(player.height / 2) - vector.Y;
                float num5 = (float)Math.Sqrt((double)(num3 * num3 + num4 * num4));
                if (num5 > 3000f)
                {
                    this.Kill();
                }
                num5 = num / num5;
                num3 *= num5;
                num4 *= num5;
                this.velocity.X = (this.velocity.X * (float)(num2 - 1) + num3) / (float)num2;
                this.velocity.Y = (this.velocity.Y * (float)(num2 - 1) + num4) / (float)num2;
                this.rotation = (float)Math.Atan2((double)this.velocity.Y, (double)this.velocity.X) + 1.57f;
                if (Main.myPlayer == this.owner && base.Hitbox.Intersects(player.Hitbox))
                {
                    this.Kill();
                    return;
                }
            }
            else
            {
                bool flag3 = false;
                Vector2 vector2 = new Vector2(this.position.X + (float)this.width * 0.5f, this.position.Y + (float)this.height * 0.5f);
                float num6 = player.position.X + (float)(player.width / 2) - vector2.X;
                float num7 = player.position.Y + (float)(player.height / 2) - vector2.Y;
                this.rotation = (float)Math.Atan2((double)num7, (double)num6) + 1.57f;
                if ((float)Math.Sqrt((double)(num6 * num6 + num7 * num7)) > 900f)
                {
                    this.ai[0] = 1f;
                }
                if (this.wet)
                {
                    if (this.shimmerWet)
                    {
                        if (Main.myPlayer == this.owner)
{
                            Main.player[this.owner].AddBuff(353, 60, false);
                        }
                        if (this.localAI[2] == 0f)
{
                            this.localAI[2] = 1f;
                            SoundEngine.PlaySound(19, (int)Main.player[this.owner].position.X, (int)Main.player[this.owner].position.Y, 2, 1f, 0f);
                        }
                    }
                    this.rotation = 0f;
                    this.velocity.X = this.velocity.X * 0.9f;
                    int num8 = (int)(base.Center.X + (float)((this.width / 2 + 8) * this.direction)) / 16;
                    int num9 = (int)(base.Center.Y / 16f);
                    float num10 = this.position.Y / 16f;
                    int num11 = (int)((this.position.Y + (float)this.height) / 16f);
                    if (Main.tile[num8, num9] == null)
                    {
                        Main.tile[num8, num9] = new Tile();
                    }
                    if (Main.tile[num8, num11] == null)
                    {
                        Main.tile[num8, num11] = new Tile();
                    }
                    if (this.velocity.Y > 0f)
                    {
                        this.velocity.Y = this.velocity.Y * 0.5f;
                    }
                    num8 = (int)(base.Center.X / 16f);
                    num9 = (int)(base.Center.Y / 16f);
                    float num12 = this.AI_061_FishingBobber_GetWaterLine(num8, num9);
                    if (base.Center.Y > num12)
                    {
                        this.velocity.Y = this.velocity.Y - 0.1f;
                        if (this.velocity.Y < -8f)
{
                            this.velocity.Y = -8f;
                        }
                        if (base.Center.Y + this.velocity.Y < num12)
{
                            this.velocity.Y = num12 - base.Center.Y;
                        }
                    }
                    else
                    {
                        this.velocity.Y = num12 - base.Center.Y;
                    }
                    if ((double)this.velocity.Y >= -0.01 && (double)this.velocity.Y <= 0.01)
                    {
                        flag3 = true;
                    }
                }
                else
                {
                    if (this.velocity.Y == 0f)
                    {
                        this.velocity.X = this.velocity.X * 0.95f;
                    }
                    this.velocity.X = this.velocity.X * 0.98f;
                    this.velocity.Y = this.velocity.Y + 0.2f;
                    if (this.velocity.Y > 15.9f)
                    {
                        this.velocity.Y = 15.9f;
                    }
                }
                if (Main.myPlayer == this.owner && player.GetFishingConditions().BaitItemType == 2673)
                {
                    player.displayedFishingInfo = Language.GetTextValue("GameUI.FishingWarning");
                }
                if (this.ai[1] != 0f)
                {
                    flag3 = true;
                }
                if (flag3)
                {
                    if (this.ai[1] == 0f && Main.myPlayer == this.owner)
                    {
                        int finalFishingLevel = player.GetFishingConditions().FinalFishingLevel;
                        if (Main.rand.Next(300) < finalFishingLevel)
{
                            this.localAI[1] += (float)Main.rand.Next(1, 3);
                        }
                        this.localAI[1] += (float)(finalFishingLevel / 30);
                        this.localAI[1] += (float)Main.rand.Next(1, 3);
                        if (Main.rand.Next(60) == 0)
{
                            this.localAI[1] += 60f;
                        }
                        if (this.localAI[1] > 660f)
{
                            this.localAI[1] = 0f;
                            this.FishingCheck();
                            return;
                        }
                    }
                    else if (this.ai[1] < 0f)
                    {
                        if (this.velocity.Y == 0f || (this.honeyWet && Math.Abs(this.velocity.Y) <= 0.01f))
{
                            this.velocity.Y = (float)Main.rand.Next(100, 500) * 0.015f;
                            this.velocity.X = (float)Main.rand.Next(-100, 101) * 0.015f;
                            this.wet = false;
                            this.lavaWet = false;
                            this.honeyWet = false;
                        }
                        this.ai[1] += (float)Main.rand.Next(1, 5);
                        if (this.ai[1] >= 0f)
{
                            this.ai[1] = 0f;
                            this.localAI[1] = 0f;
                            this.netUpdate = true;
                        }
                    }
                }
            }
        }
References System.Math.Abs(), Terraria.Player.AddBuff(), System.Math.Atan2(), Terraria.DataStructures.PlayerFishingConditions.BaitItemType, Terraria.Player.CCed, Terraria.Player.dead, Terraria.DataStructures.PlayerFishingConditions.FinalFishingLevel, Terraria.Item.fishingPole, Terraria.Player.GetFishingConditions(), Terraria.Localization.Language.GetTextValue(), Terraria.Entity.height, Terraria.Entity.Hitbox, int, Terraria.Player.inventory, Terraria.ID.SoundID.Item17, Terraria.Main.myPlayer, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Player.noItems, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Player.pulley, Terraria.Main.rand, Terraria.Player.selectedItem, Terraria.Item.shoot, System.Math.Sqrt(), Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.