Terraria Decompiled: Terraria.GameContent.Creative.CreativePowers.ModifyRainPower.UpdateSliderAndShowMultiplierMouseOver
UpdateSliderAndShowMultiplierMouseOver()
void Terraria.GameContent.Creative.CreativePowers.ModifyRainPower.UpdateSliderAndShowMultiplierMouseOver (UIElement affectedElement) inline private
Definition at line 2161 of file CreativePowers.cs.
            {
                if (affectedElement.IsMouseHovering)
                {
                    string text = Main.maxRaining.ToString("P0");
                    CreativePowersHelper.AddPermissionTextIfNeeded(this, ref text);
                    Main.instance.MouseTextNoOverride(text, 0, 0, -1, -1, -1, -1, 0);
                }
            }
References Terraria.GameContent.Creative.CreativePowersHelper.AddPermissionTextIfNeeded(), Terraria.Main.instance, Terraria.UI.UIElement.IsMouseHovering, Terraria.Main.maxRaining, Terraria.Main.MouseTextNoOverride(), and System.text.
Referenced by Terraria.GameContent.Creative.CreativePowers.ModifyRainPower.ProvideSlider().