Terraria Decompiled: Terraria.Projectile.AI_163_Chum
AI_163_Chum()
void Terraria.Projectile.AI_163_Chum () inline private
Definition at line 53864 of file Projectile.cs.
        {
            float num = 0.05f;
            float num2 = (float)(this.width / 2);
            for (int i = 0; i < 1000; i++)
            {
                if (i != this.whoAmI && Main.projectile[i].active && Main.projectile[i].type == this.type && Math.Abs(this.position.X - Main.projectile[i].position.X) + Math.Abs(this.position.Y - Main.projectile[i].position.Y) < num2)
                {
                    if (this.position.X < Main.projectile[i].position.X)
                    {
                        this.velocity.X = this.velocity.X - num;
                    }
                    else
                    {
                        this.velocity.X = this.velocity.X + num;
                    }
                    if (this.position.Y < Main.projectile[i].position.Y)
                    {
                        this.velocity.Y = this.velocity.Y - num;
                    }
                    else
                    {
                        this.velocity.Y = this.velocity.Y + num;
                    }
                }
            }
            if (this.wet)
            {
                this.velocity.X = this.velocity.X * 0.9f;
                int num3 = (int)(base.Center.X + (float)((this.width / 2 + 8) * this.direction)) / 16;
                int num4 = (int)(base.Center.Y / 16f);
                float num5 = this.position.Y / 16f;
                int num6 = (int)((this.position.Y + (float)this.height) / 16f);
                if (Main.tile[num3, num4] == null)
                {
                    Main.tile[num3, num4] = new Tile();
                }
                if (Main.tile[num3, num6] == null)
                {
                    Main.tile[num3, num6] = new Tile();
                }
                if (this.velocity.Y > 0f)
                {
                    this.velocity.Y = this.velocity.Y * 0.5f;
                }
                num3 = (int)(base.Center.X / 16f);
                num4 = (int)(base.Center.Y / 16f);
                float num7 = this.AI_061_FishingBobber_GetWaterLine(num3, num4);
                if (base.Center.Y > num7)
                {
                    this.velocity.Y = this.velocity.Y - 0.1f;
                    if (this.velocity.Y < -8f)
                    {
                        this.velocity.Y = -8f;
                    }
                    if (base.Center.Y + this.velocity.Y < num7)
                    {
                        this.velocity.Y = num7 - base.Center.Y;
                    }
                }
                else
                {
                    this.velocity.Y = num7 - base.Center.Y;
                }
            }
            else
            {
                if (this.velocity.Y == 0f)
                {
                    this.velocity.X = this.velocity.X * 0.95f;
                }
                this.velocity.X = this.velocity.X * 0.98f;
                this.velocity.Y = this.velocity.Y + 0.3f;
                if (this.velocity.Y > 15.9f)
                {
                    this.velocity.Y = 15.9f;
                }
            }
            if (this.frameCounter == 0)
            {
                this.frameCounter = 1;
                this.frame = Main.rand.Next(4);
            }
            if (this.frameCounter < 10 && this.wet)
            {
                this.frameCounter++;
                for (float num8 = 0f; num8 < 1f; num8 += 0.5f)
                {
                    Gore gore = Gore.NewGoreDirect(this.position + Vector2.UnitY * 6f, Vector2.Zero, 1201, this.scale * 0.7f);
                    gore.velocity = Main.rand.NextVector2CircularEdge(10f, 10f);
                    if (gore.velocity.Y > 0f)
                    {
                        Gore gore2 = gore;
                        gore2.velocity.Y = gore2.velocity.Y * -1f;
                    }
                }
                for (float num9 = 0f; num9 < 2f; num9 += 1f)
                {
                    Gore gore3 = Gore.NewGoreDirect(this.position + Vector2.UnitY * 6f, Vector2.Zero, 1208, this.scale * 0.7f + Main.rand.NextFloat() * 0.15f);
                    gore3.velocity = Main.rand.NextVector2CircularEdge(4f, 4f);
                    if (gore3.velocity.Y > 0f)
                    {
                        Gore gore4 = gore3;
                        gore4.velocity.Y = gore4.velocity.Y * -1f;
                    }
                }
            }
            this.scale = Utils.GetLerpValue(0f, 60f, (float)this.timeLeft, true);
            this.rotation += this.velocity.X * 0.14f;
            bool flag = !this.wet && this.velocity.Length() < 0.8f;
            int num10 = (this.wet ? 90 : 5);
            if (Main.rand.Next(num10) == 0 && !flag)
            {
                Gore gore5 = Gore.NewGoreDirect(this.position + Vector2.UnitY * 6f, Vector2.Zero, 1201, this.scale * 0.7f);
                if (this.wet)
                {
                    gore5.velocity = Vector2.UnitX * Main.rand.NextFloatDirection() * 0.75f + Vector2.UnitY * Main.rand.NextFloat();
                }
                else if (gore5.velocity.Y < 0f)
                {
                    gore5.velocity.Y = -gore5.velocity.Y;
                }
            }
            Vector2 vector = base.Center + Vector2.UnitY * 16f;
            if (this.ai[0] >= 10f && this.timeLeft > 60)
            {
                this.timeLeft = 60;
                this.netUpdate = true;
            }
            if (this.ai[0] < 10f && this.timeLeft > 60)
            {
                Main.instance.ChumBucketProjectileHelper.AddChumLocation(vector);
            }
        }
References System.Math.Abs(), Terraria.Projectile.active, Terraria.GameContent.ChumBucketProjectileHelper.AddChumLocation(), Terraria.Main.ChumBucketProjectileHelper, Terraria.Utils.GetLerpValue(), Terraria.Main.instance, int, Terraria.Gore.NewGoreDirect(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Entity.position, Terraria.Main.projectile, Terraria.Main.rand, Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.Projectile.type, Microsoft.Xna.Framework.Vector2.UnitY, Terraria.Gore.velocity, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.