Terraria Decompiled: Terraria.Projectile.GasTrapCheck
GasTrapCheck()
static bool Terraria.Projectile.GasTrapCheck (int x, int y, Player user) inline static
Definition at line 41548 of file Projectile.cs.
        {
            if (Main.netMode == 1)
            {
                return false;
            }
            int num = Chest.FindChest(x, y);
            if (num < 0)
            {
                return false;
            }
            Chest chest = Main.chest[num];
            int num2 = 16;
            int num3 = 16;
            bool flag = false;
            for (int i = 0; i < chest.maxItems; i++)
            {
                ushort num4 = Main.tile[chest.x, chest.y].type;
                if (TileObjectData.CustomPlace((int)num4, 0))
                {
                    TileObjectData tileData = TileObjectData.GetTileData((int)num4, 0, 0);
                    if (tileData != null)
                    {
                        int num5 = (int)Math.Ceiling((double)((float)tileData.Width / 2f));
                        int num6 = (int)Math.Ceiling((double)((float)tileData.Width / 2f));
                        num2 = num5 * 16;
                        num3 = num6 * 16;
                        if (num5 % 2 != 0)
{
                            num2 += 8;
                        }
                        if (num6 % 2 != 0)
{
                            num3 += 8;
                        }
                    }
                }
                if (chest.item[i] != null && chest.item[i].type == 5346)
                {
                    Projectile.UseGasTrapInChest(num, chest, i, num2, num3);
                    flag = true;
                    break;
                }
            }
            if (flag)
            {
                num3 -= 8;
                Vector2 vector = new Vector2((float)(x * 16 + num2), (float)(y * 16 + num3));
                Projectile.NewProjectile(user.GetProjectileSource_TileInteraction(x, y), vector, Vector2.Zero, 1007, 10, 0f, Main.myPlayer, 0f, 0f, 0f, null);
            }
            return flag;
        }
References System.Math.Ceiling(), Terraria.Main.chest, Terraria.ObjectData.TileObjectData.CustomPlace(), Terraria.Chest.FindChest(), Terraria.Player.GetProjectileSource_TileInteraction(), Terraria.ObjectData.TileObjectData.GetTileData(), int, Terraria.Chest.item, Terraria.Chest.maxItems, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Projectile.NewProjectile(), Terraria.Main.tile, Terraria.Item.type, Terraria.Tile.type, Terraria.Projectile.UseGasTrapInChest(), Terraria.ObjectData.TileObjectData.Width, Terraria.Chest.x, Terraria.Chest.y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.Player.ChestChangeEvents().