Terraria Decompiled: Terraria.Projectile.AI_147_Explosion
AI_147_Explosion()
void Terraria.Projectile.AI_147_Explosion () inline private
Definition at line 53499 of file Projectile.cs.
        {
            switch ((int)this.ai[0])
            {
            case 0:
            {
                for (int i = 0; i < 4; i++)
                {
                    Dust.NewDust(new Vector2(this.position.X, this.position.Y), this.width, this.height, 31, 0f, 0f, 100, default(Color), 1.5f);
                }
                for (int j = 0; j < 20; j++)
                {
                    int num = Dust.NewDust(new Vector2(this.position.X, this.position.Y), this.width, this.height, 130, 0f, 0f, 200, default(Color), 1.2f);
                    Main.dust[num].noGravity = true;
                    Main.dust[num].velocity *= 3f;
                    num = Dust.NewDust(new Vector2(this.position.X, this.position.Y), this.width, this.height, 130, 0f, 0f, 200, default(Color), 0.5f);
                    Main.dust[num].velocity *= 1.2f;
                    Main.dust[num].noGravity = true;
                }
                for (int k = 0; k < 1; k++)
                {
                    int num2 = Gore.NewGore(this.position + new Vector2((float)(this.width * Main.rand.Next(100)) / 100f, (float)(this.height * Main.rand.Next(100)) / 100f) - Vector2.One * 10f, default(Vector2), Main.rand.Next(61, 64), 1f);
                    Main.gore[num2].velocity *= 0.3f;
                    Gore gore = Main.gore[num2];
                    gore.velocity.X = gore.velocity.X + (float)Main.rand.Next(-10, 11) * 0.05f;
                    Gore gore2 = Main.gore[num2];
                    gore2.velocity.Y = gore2.velocity.Y + (float)Main.rand.Next(-10, 11) * 0.05f;
                }
                return;
            }
            case 1:
            {
                Color celeb2Color = this.GetCeleb2Color();
                Vector2 center = base.Center;
                Main.rand.NextFloat();
                for (float num3 = 0f; num3 < 1f; num3 += 0.0125f)
                {
                    Dust dust = Dust.NewDustPerfect(center, 278, null, 200, Color.Lerp(celeb2Color, Color.White, Main.rand.NextFloat() * 0.6f), 1f);
                    dust.scale = 1.1f;
                    dust.fadeIn = 1.3f;
                    dust.velocity *= Main.rand.NextFloat() * 2f + 2f;
                    if (dust.velocity.Y > 0f)
                    {
                        dust.velocity *= 0.3f;
                    }
                    dust.velocity *= 2f;
                }
                for (int l = 0; l < 3; l++)
                {
                    int num4 = Gore.NewGore(this.position + new Vector2((float)(this.width * Main.rand.Next(100)) / 100f, (float)(this.height * Main.rand.Next(100)) / 100f) - Vector2.One * 10f, default(Vector2), Main.rand.Next(61, 64), 1f);
                    Main.gore[num4].velocity *= 0.3f;
                    Gore gore3 = Main.gore[num4];
                    gore3.velocity.X = gore3.velocity.X + (float)Main.rand.Next(-10, 11) * 0.05f;
                    Gore gore4 = Main.gore[num4];
                    gore4.velocity.Y = gore4.velocity.Y + (float)Main.rand.Next(-10, 11) * 0.05f;
                }
                int num5 = 20;
                int num6 = 100;
                int num7 = 2;
                int num8 = 10;
                int num9 = 2;
                this.CreateGroundExplosion(40f, num5, num6, num7, num8, num9);
                return;
            }
            case 2:
            {
                Vector2 center2 = base.Center;
                Color celeb2Color2 = this.GetCeleb2Color();
                float num10 = 0.05f;
                float num11 = 0.13f;
                bool flag = Main.rand.Next(4) == 0;
                if (flag)
                {
                    num10 = 0.1f;
                    num11 = 0.1f;
                }
                float num12 = Main.rand.NextFloatDirection();
                for (float num13 = 0f; num13 < 5f; num13 += 1f)
                {
                    Vector2 vector = new Vector2(0f, -100f);
                    Vector2 vector2 = center2 + vector.RotatedBy((double)(num12 + num13 * 1.2566371f), default(Vector2));
                    Vector2 vector3 = center2 + vector.RotatedBy((double)(num12 + (num13 + 1f) * 1.2566371f), default(Vector2));
                    Vector2 vector4 = center2 + vector.RotatedBy((double)(num12 + (num13 + 0.5f) * 1.2566371f), default(Vector2)) * 0.4f;
                    for (int m = 0; m < 2; m++)
                    {
                        Vector2 vector5 = vector2;
                        Vector2 vector6 = vector4;
                        if (m == 1)
{
                            vector5 = vector4;
                            vector6 = vector3;
                        }
                        for (float num14 = 0f; num14 < 1f; num14 += num11)
{
                            Vector2 vector7 = Vector2.Lerp(vector5, vector6, num14);
                            Vector2 vector8 = Vector2.Lerp(vector7, center2, 0.9f);
                            Vector2 vector9 = (vector7 - vector8).SafeNormalize(Vector2.Zero);
                            Dust dust2 = Dust.NewDustPerfect(vector8, 267, new Vector2?(Vector2.Zero), 0, celeb2Color2, 0.5f);
                            dust2.fadeIn = 1.2f;
                            dust2.noGravity = true;
                            dust2.velocity = vector9 * Vector2.Distance(vector7, vector8) * num10;
                        }
                    }
                }
                if (flag)
                {
                    for (int n = 0; n < 4; n++)
                    {
                        Dust.NewDust(new Vector2(this.position.X, this.position.Y), this.width, this.height, 31, 0f, 0f, 100, default(Color), 1.5f);
                    }
                    for (int num15 = 0; num15 < 60; num15++)
                    {
                        int num16 = Dust.NewDust(new Vector2(this.position.X, this.position.Y), this.width, this.height, 228, 0f, 0f, 200, default(Color), 2.5f);
                        Main.dust[num16].noGravity = true;
                        Main.dust[num16].velocity *= 8f;
                        num16 = Dust.NewDust(new Vector2(this.position.X, this.position.Y), this.width, this.height, 228, 0f, 0f, 200, default(Color), 1.5f);
                        Main.dust[num16].velocity *= 4.2f;
                        Main.dust[num16].noGravity = true;
                    }
                    for (int num17 = 0; num17 < 1; num17++)
                    {
                        int num18 = Gore.NewGore(this.position + new Vector2((float)(this.width * Main.rand.Next(100)) / 100f, (float)(this.height * Main.rand.Next(100)) / 100f) - Vector2.One * 10f, default(Vector2), Main.rand.Next(61, 64), 1f);
                        Main.gore[num18].velocity *= 0.3f;
                        Gore gore5 = Main.gore[num18];
                        gore5.velocity.X = gore5.velocity.X + (float)Main.rand.Next(-10, 11) * 0.05f;
                        Gore gore6 = Main.gore[num18];
                        gore6.velocity.Y = gore6.velocity.Y + (float)Main.rand.Next(-10, 11) * 0.05f;
                    }
                    return;
                }
                for (int num19 = 0; num19 < 4; num19++)
                {
                    Dust.NewDust(new Vector2(this.position.X, this.position.Y), this.width, this.height, 31, 0f, 0f, 100, default(Color), 1.5f);
                }
                for (int num20 = 0; num20 < 40; num20++)
                {
                    int num21 = Dust.NewDust(new Vector2(this.position.X, this.position.Y), this.width, this.height, 228, 0f, 0f, 200, default(Color), 2.5f);
                    Main.dust[num21].noGravity = true;
                    Main.dust[num21].velocity *= 4f;
                    num21 = Dust.NewDust(new Vector2(this.position.X, this.position.Y), this.width, this.height, 228, 0f, 0f, 200, default(Color), 1.5f);
                    Main.dust[num21].velocity *= 2.2f;
                    Main.dust[num21].noGravity = true;
                }
                for (int num22 = 0; num22 < 1; num22++)
                {
                    int num23 = Gore.NewGore(this.position + new Vector2((float)(this.width * Main.rand.Next(100)) / 100f, (float)(this.height * Main.rand.Next(100)) / 100f) - Vector2.One * 10f, default(Vector2), Main.rand.Next(61, 64), 1f);
                    Main.gore[num23].velocity *= 0.3f;
                    Gore gore7 = Main.gore[num23];
                    gore7.velocity.X = gore7.velocity.X + (float)Main.rand.Next(-10, 11) * 0.05f;
                    Gore gore8 = Main.gore[num23];
                    gore8.velocity.Y = gore8.velocity.Y + (float)Main.rand.Next(-10, 11) * 0.05f;
                }
                return;
            }
            case 3:
            {
                Color celeb2Color3 = this.GetCeleb2Color();
                Vector2 center3 = base.Center;
                for (int num24 = 0; num24 < 4; num24++)
                {
                    Dust.NewDust(new Vector2(this.position.X, this.position.Y), this.width, this.height, 31, 0f, 0f, 100, default(Color), 1.5f);
                }
                float num25 = Main.rand.NextFloat() * 6.2831855f;
                for (int num26 = 0; num26 < 40; num26++)
                {
                    Dust dust3 = Dust.NewDustPerfect(center3, 278, null, 100, Color.Lerp(celeb2Color3, Color.White, Main.rand.NextFloat() * 0.3f), 1f);
                    dust3.scale = 1.3f * (dust3.velocity.Length() / 2f);
                    dust3.fadeIn = 1.5f * (dust3.velocity.Length() / 2f);
                    dust3.noGravity = true;
                    dust3.velocity *= 6f;
                    if (Math.Abs(dust3.velocity.X) > Math.Abs(dust3.velocity.Y))
                    {
                        Dust dust4 = dust3;
                        dust4.velocity.Y = dust4.velocity.Y * 0.1f;
                    }
                    else
                    {
                        Dust dust5 = dust3;
                        dust5.velocity.X = dust5.velocity.X * 0.1f;
                    }
                    dust3.velocity = dust3.velocity.RotatedBy((double)num25, default(Vector2));
                }
                for (int num27 = 0; num27 < 1; num27++)
                {
                    int num28 = Gore.NewGore(this.position + new Vector2((float)(this.width * Main.rand.Next(100)) / 100f, (float)(this.height * Main.rand.Next(100)) / 100f) - Vector2.One * 10f, default(Vector2), Main.rand.Next(61, 64), 1f);
                    Main.gore[num28].velocity *= 0.3f;
                    Gore gore9 = Main.gore[num28];
                    gore9.velocity.X = gore9.velocity.X + (float)Main.rand.Next(-10, 11) * 0.05f;
                    Gore gore10 = Main.gore[num28];
                    gore10.velocity.Y = gore10.velocity.Y + (float)Main.rand.Next(-10, 11) * 0.05f;
                }
                return;
            }
            case 4:
            {
                this.GetCeleb2Color();
                Vector2 center4 = base.Center;
                Main.rand.NextFloat();
                for (float num29 = 0f; num29 < 1f; num29 += 0.025f)
                {
                    Dust dust6 = Dust.NewDustPerfect(center4, 132, null, 200, default(Color), 1f);
                    dust6.scale = 1.1f;
                    dust6.fadeIn = 1.5f;
                    dust6.velocity *= Main.rand.NextFloat() * 2f + 2f;
                    if (dust6.velocity.Y > 0f)
                    {
                        dust6.velocity *= 0.3f;
                    }
                    dust6.velocity *= 2f;
                }
                for (int num30 = 0; num30 < 3; num30++)
                {
                    int num31 = Gore.NewGore(this.position + new Vector2((float)(this.width * Main.rand.Next(100)) / 100f, (float)(this.height * Main.rand.Next(100)) / 100f) - Vector2.One * 10f, default(Vector2), Main.rand.Next(61, 64), 1f);
                    Main.gore[num31].velocity *= 0.3f;
                    Gore gore11 = Main.gore[num31];
                    gore11.velocity.X = gore11.velocity.X + (float)Main.rand.Next(-10, 11) * 0.05f;
                    Gore gore12 = Main.gore[num31];
                    gore12.velocity.Y = gore12.velocity.Y + (float)Main.rand.Next(-10, 11) * 0.05f;
                }
                return;
            }
            case 5:
            {
                Color celeb2Color4 = this.GetCeleb2Color();
                Vector2 center5 = base.Center;
                for (int num32 = 0; num32 < 20; num32++)
                {
                    int num33 = Dust.NewDust(new Vector2(this.position.X, this.position.Y), this.width, this.height, 278, 0f, 0f, 200, Color.Lerp(celeb2Color4, Color.White, Main.rand.NextFloat() * 0.4f), 2.5f);
                    Main.dust[num33].fadeIn = 1.3f;
                    Main.dust[num33].scale = 1.1f;
                    Main.dust[num33].velocity *= 2f;
                    num33 = Dust.NewDust(new Vector2(this.position.X, this.position.Y), this.width, this.height, 27, 0f, 0f, 200, celeb2Color4, 2.5f);
                    Main.dust[num33].velocity *= 1.2f;
                    Main.dust[num33].noGravity = true;
                }
                return;
            }
            case 6:
            {
                Color celeb2Color5 = this.GetCeleb2Color();
                Vector2 center6 = base.Center;
                for (int num34 = 0; num34 < 4; num34++)
                {
                    Dust.NewDust(new Vector2(this.position.X, this.position.Y), this.width, this.height, 31, 0f, 0f, 100, default(Color), 1.5f);
                }
                for (float num35 = 0f; num35 < 1f; num35 += 0.015f)
                {
                    Vector2 vector10 = Vector2.UnitY.RotatedBy((double)(num35 * 6.2831855f), default(Vector2)) * (1f + Main.rand.NextFloatDirection() * 0.1f);
                    Dust dust7 = Dust.NewDustPerfect(center6 + vector10, 134, new Vector2?(Vector2.Zero), 0, celeb2Color5, 1f);
                    dust7.scale = 1.4f;
                    dust7.velocity = vector10 * 5f;
                    dust7.velocity.Y = dust7.velocity.Y + -3f;
                    dust7.velocity *= 2f;
                }
                for (float num36 = 0f; num36 < 1f; num36 += 0.025f)
                {
                    Vector2 vector11 = Vector2.UnitY.RotatedBy((double)(num36 * 6.2831855f), default(Vector2)) * (1f + Main.rand.NextFloatDirection() * 0.2f);
                    Dust dust8 = Dust.NewDustPerfect(center6 + vector11, 267, new Vector2?(Vector2.Zero), 0, celeb2Color5, 1f);
                    dust8.noGravity = true;
                    dust8.scale = 0.4f;
                    dust8.fadeIn = 1.2f;
                    dust8.velocity = vector11 * 4f;
                    dust8.velocity.Y = dust8.velocity.Y + -3f;
                    dust8.velocity *= 2f;
                }
                for (float num37 = 0f; num37 < 1f; num37 += 0.07f)
                {
                    Vector2 vector12 = Vector2.UnitY.RotatedBy((double)(num37 * 6.2831855f), default(Vector2)) * (1f + Main.rand.NextFloatDirection() * 0.3f);
                    Dust dust9 = Dust.NewDustPerfect(center6 + vector12, 267, new Vector2?(Vector2.Zero), 0, celeb2Color5, 1f);
                    dust9.noGravity = true;
                    dust9.scale = 0.4f;
                    dust9.fadeIn = 1.3f;
                    dust9.velocity = vector12 * 7f;
                    dust9.velocity.Y = dust9.velocity.Y + -3f;
                    dust9.velocity *= 2f;
                }
                for (int num38 = 0; num38 < 1; num38++)
                {
                    int num39 = Gore.NewGore(this.position + new Vector2((float)(this.width * Main.rand.Next(100)) / 100f, (float)(this.height * Main.rand.Next(100)) / 100f) - Vector2.One * 10f, default(Vector2), Main.rand.Next(61, 64), 1f);
                    Main.gore[num39].velocity *= 0.3f;
                    Gore gore13 = Main.gore[num39];
                    gore13.velocity.X = gore13.velocity.X + (float)Main.rand.Next(-10, 11) * 0.05f;
                    Gore gore14 = Main.gore[num39];
                    gore14.velocity.Y = gore14.velocity.Y + (float)Main.rand.Next(-10, 11) * 0.05f;
                }
                return;
            }
            default:
                return;
            }
        }
References System.Math.Abs(), Microsoft.Xna.Framework.Vector2.Distance(), Terraria.Main.dust, Terraria.Dust.fadeIn, Terraria.Main.gore, Microsoft.Xna.Framework.Vector2.Length(), Microsoft.Xna.Framework.Color.Lerp(), Microsoft.Xna.Framework.Vector2.Lerp(), Terraria.Dust.NewDust(), Terraria.Dust.NewDustPerfect(), Terraria.Gore.NewGore(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Microsoft.Xna.Framework.Vector2.One, Terraria.Main.rand, Terraria.Dust.scale, Microsoft.Xna.Framework.Vector2.UnitY, Terraria.Dust.velocity, Terraria.Gore.velocity, Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.