Terraria Decompiled: Terraria.Projectile.ExplodeTiles
ExplodeTiles()
void Terraria.Projectile.ExplodeTiles (Vector2 compareSpot, int radius, int minI, int maxI, int minJ, int maxJ, bool wallSplode, bool explodeHardmodeOres = false) inline
Definition at line 80918 of file Projectile.cs.
        {
            AchievementsHelper.CurrentlyMining = true;
            for (int i = minI; i <= maxI; i++)
            {
                for (int j = minJ; j <= maxJ; j++)
                {
                    float num = Math.Abs((float)i - compareSpot.X / 16f);
                    float num2 = Math.Abs((float)j - compareSpot.Y / 16f);
                    if (Math.Sqrt((double)(num * num + num2 * num2)) < (double)radius)
                    {
                        Tile tile = Main.tile[i, j];
                        bool flag = true;
                        if (tile != null && tile.active())
{
                            flag = this.CanExplodeTile(i, j, explodeHardmodeOres);
                            if (flag)
{
                                WorldGen.KillTile(i, j, false, false, false);
                                if (!Main.tile[i, j].active() && Main.netMode != 0)
{
                                    NetMessage.SendData(17, -1, -1, null, 0, (float)i, (float)j, 0f, 0, 0, 0);
                                }
                            }
                        }
                        if (wallSplode && flag)
{
                            for (int k = i - 1; k <= i + 1; k++)
{
                                for (int l = j - 1; l <= j + 1; l++)
{
                                    Tile tile2 = Main.tile[k, l];
                                    if (tile2 != null && tile2.wall != 0 && tile2.wall != 350)
{
                                        WorldGen.KillWall(k, l, false);
                                        if (tile2.wall == 0 && Main.netMode != 0)
{
                                            NetMessage.SendData(17, -1, -1, null, 2, (float)k, (float)l, 0f, 0, 0, 0);
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            AchievementsHelper.CurrentlyMining = false;
        }
References System.Math.Abs(), Terraria.Tile.active(), Terraria.WorldGen.KillTile(), Terraria.WorldGen.KillWall(), Terraria.Main.netMode, Terraria.NetMessage.SendData(), System.Math.Sqrt(), Terraria.Main.tile, Terraria.Tile.wall, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.