Terraria Decompiled: Terraria.Projectile.AI_198_Flint
AI_198_Flint()
void Terraria.Projectile.AI_198_Flint () inline private
Definition at line 52596 of file Projectile.cs.
        {
            Player player = Main.player[this.owner];
            if (!player.active)
            {
                this.Kill();
                return;
            }
            if (!player.channel && this.ai[0] == 0f)
            {
                bool flag = this.ai[1] >= 30f;
                this.ai[0] = 1f;
                this.ai[1] = 0f;
                this.netUpdate = true;
                if (this.owner == Main.myPlayer)
                {
                    int num = (int)((float)this.damage * 1.78f);
                    Projectile.NewProjectile(this.GetProjectileSource_FromThis(), player.MountedCenter, new Vector2((float)this.direction, 0f), 1043, num, this.knockBack, this.owner, (float)this.direction * player.gravDir, 6f, 1f, null);
                    if (flag)
                    {
                        this.AI_198_Flint_EmitSpikes(player.MountedCenter, this.direction);
                    }
                }
            }
            if (this.ai[0] == 1f)
            {
                this.ai[1] += 1f;
                float num2 = (float)player.HeldItem.useAnimation;
                if (this.ai[1] >= num2)
                {
                    this.Kill();
                    return;
                }
                this.velocity = Vector2.Zero;
                player.ChangeDir(this.direction);
                player.heldProj = this.whoAmI;
                int num3 = (int)Utils.Remap(this.ai[1], 0f, 5f, (float)player.HeldItem.useAnimation, 0f, true);
                if (num3 < 2)
                {
                    num3 = 2;
                }
                player.SetDummyItemTime(num3);
            }
            if (this.ai[0] == 0f)
            {
                this.velocity = Vector2.Zero;
                if (this.owner == Main.myPlayer)
                {
                    Vector2 vector = Main.ReverseGravitySupport(Main.MouseScreen, 0f) + Main.screenPosition - player.MountedCenter;
                    this.direction = ((vector.X >= 0f) ? 1 : (-1));
                    player.ChangeDir(this.direction);
                }
                this.direction = player.direction;
                player.heldProj = this.whoAmI;
                int useAnimation = player.HeldItem.useAnimation;
                int num4 = 3;
                this.ai[1] += 1f;
                float num5 = this.ai[1];
                if (num5 > (float)num4)
                {
                    num5 = (float)num4;
                }
                int num6 = useAnimation + (int)num5;
                if (num6 < 2)
                {
                    num6 = 2;
                }
                if (this.ai[1] == 30f)
                {
                    SoundEngine.PlaySound(SoundID.DeadCellsFlintCharge, player.Center, 0f, 1f);
                }
                player.itemAnimationMax = useAnimation;
                player.SetDummyItemTime(num6);
                Player player2 = player;
                player2.itemLocation.Y = player2.itemLocation.Y + (float)Main.rand.Next(2);
                if (Main.rand.Next(10) == 0)
                {
                    Dust.NewDustPerfect(player.itemLocation + new Vector2((float)(41 * player.direction), -41f * player.gravDir).RotatedBy((double)player.itemRotation, default(Vector2)) + Main.rand.NextVector2Circular(12f, 12f), 228, new Vector2?(new Vector2(0f, Main.rand.NextFloat() * -8f - 2f)), 127, new Color(255, 180, 0, 0), 1.3f + Main.rand.NextFloat()).noGravity = true;
                }
            }
        }
References Terraria.Player.active, Terraria.Entity.Center, Terraria.Player.ChangeDir(), Terraria.Player.channel, Terraria.ID.SoundID.DeadCellsFlintCharge, Terraria.Entity.direction, Terraria.Player.gravDir, Terraria.Player.HeldItem, int, Terraria.Player.itemLocation, Terraria.Player.itemRotation, Terraria.Player.MountedCenter, Terraria.Main.MouseScreen, Terraria.Main.myPlayer, Terraria.Dust.NewDustPerfect(), Terraria.Projectile.NewProjectile(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.rand, Terraria.Utils.Remap(), Terraria.Main.ReverseGravitySupport(), Terraria.Player.SetDummyItemTime(), Terraria.Item.useAnimation, and Microsoft.Xna.Framework.Vector2.Zero.