Terraria Decompiled: Terraria.Projectile.AI_019_Spears_GetExtensionHitbox
AI_019_Spears_GetExtensionHitbox()
bool Terraria.Projectile.AI_019_Spears_GetExtensionHitbox (Player master, out Rectangle extensionBox) inline
Definition at line 46536 of file Projectile.cs.
        {
            extensionBox = default(Rectangle);
            if (master.itemAnimation < master.itemAnimationMax / 3)
            {
                return false;
            }
            int itemAnimationMax = master.itemAnimationMax;
            float itemAnimation = (float)master.itemAnimation;
            int num = master.itemAnimationMax / 3;
            float num2 = Utils.Remap(itemAnimation, (float)itemAnimationMax, (float)num, 0f, 1f, true);
            float num3 = 10f;
            float num4 = 10f;
            int num5 = this.type;
            float num6;
            float num7;
            if (num5 != 46)
            {
                if (num5 != 105)
                {
                    if (num5 != 153)
                    {
                        return false;
                    }
                    num6 = 40f;
                    num7 = 10f;
                }
                else
                {
                    num6 = 50f;
                    num7 = 20f;
                }
            }
            else
            {
                num6 = 50f;
                num7 = 15f;
            }
            num6 *= 1f / master.meleeSpeed;
            float num8 = num3 + num6 * num2;
            float num9 = num4 + num7 * num2;
            float num10 = this.velocity.ToRotation();
            Vector2 vector = base.Center + num10.ToRotationVector2() * num8;
            extensionBox = Utils.CenteredRectangle(vector, new Vector2(num9, num9));
            return true;
        }
References Terraria.Utils.CenteredRectangle(), Terraria.Player.itemAnimation, Terraria.Player.itemAnimationMax, Terraria.Player.meleeSpeed, and Terraria.Utils.Remap().
Referenced by Terraria.Main.DrawProj_Spear().