Terraria Decompiled: Terraria.Projectile.AI_197_HandleTileCollision
AI_197_HandleTileCollision()
void Terraria.Projectile.AI_197_HandleTileCollision () inline private
Definition at line 40611 of file Projectile.cs.
        {
            Collision.HitTiles(this.position, this.velocity + this.velocity.SafeNormalize(Vector2.Zero) * 8f, this.width, this.height);
            SoundEngine.PlaySound(0, (int)this.position.X, (int)this.position.Y, 1, 1f, 0f);
            this.ai[0] = 1f;
            this.netUpdate = true;
            if (this.type == 1025)
            {
                SoundEngine.PlaySound(SoundID.Item167, this.position, 0f, 1f);
                Vector2 vector = this.position + new Vector2(0f, -22f);
                for (int i = 0; i < 30; i++)
                {
                    int num = Dust.NewDust(vector, this.width, 28, 2, this.velocity.X, this.velocity.Y, 0, default(Color), 1.4f + (float)Main.rand.Next(-20, 40) * 0.01f);
                    Main.dust[num].alpha = 50;
                    Main.dust[num].fadeIn = 0.5f;
                    if (i % 3 != 0)
                    {
                        Main.dust[num].noGravity = true;
                    }
                    else
                    {
                        Main.dust[num].scale *= 0.75f;
                    }
                    Main.dust[num].velocity = Main.rand.NextVector2Circular(5f, 5f) + new Vector2(0f, -2f);
                }
                int num2 = 20;
                Vector2 vector2 = base.Top - Vector2.UnitY * 62f;
                Vector2 vector3 = new Vector2((float)(-(float)num2), 6f);
                Vector2 vector4 = new Vector2((float)num2, 6f);
                for (int j = 0; j < 3; j++)
                {
                    int num3 = 1128;
                    Vector2 vector5 = vector2;
                    switch (j)
                    {
                    case 0:
                        num3 = 1143;
                        vector5 += vector3;
                        break;
                    case 1:
                        num3 = 1137;
                        break;
                    case 2:
                        num3 = 1128;
                        vector5 += vector4;
                        break;
                    }
                    Gore gore = Gore.NewGorePerfect(vector5, Main.rand.NextVector2Circular(2f, 2f), num3 + Main.rand.Next(3), 1f);
                    gore.velocity.Y = gore.velocity.Y - Main.rand.NextFloat();
                    gore.velocity *= 2f;
                    Gore gore2 = Gore.NewGorePerfect(vector5 + new Vector2((float)(-4 + Main.rand.Next(5)), (float)(-4 + Main.rand.Next(5))), Main.rand.NextVector2Circular(2f, 2f), num3 + Main.rand.Next(3), 1f);
                    gore2.velocity.Y = gore2.velocity.Y - Main.rand.NextFloat();
                    gore2.velocity *= 2f;
                    Gore gore3 = Gore.NewGorePerfect(vector5 + new Vector2((float)(-4 + Main.rand.Next(5)), (float)(-4 + Main.rand.Next(5) + 10)), Main.rand.NextVector2Circular(2f, 2f), 1146, 1f);
                    gore3.velocity.Y = gore3.velocity.Y - Main.rand.NextFloat();
                    gore3.velocity *= 0.5f;
                }
            }
        }
References Terraria.Dust.alpha, Terraria.Main.dust, Terraria.Dust.fadeIn, Terraria.Collision.HitTiles(), Terraria.ID.SoundID.Item167, Terraria.Dust.NewDust(), Terraria.Gore.NewGorePerfect(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.rand, Terraria.Dust.scale, Terraria.Dust.velocity, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Zero.