Terraria Decompiled: Terraria.Projectile.AI_194_HorsemanPumpkin
AI_194_HorsemanPumpkin()
void Terraria.Projectile.AI_194_HorsemanPumpkin () inline private
Definition at line 41602 of file Projectile.cs.
        {
            int num = (int)this.ai[0];
            Vector2 vector = base.Center;
            if (Main.player.IndexInRange(num))
            {
                Player player = Main.player[num];
                if (player.active && !player.dead)
                {
                    vector = player.Center;
                }
            }
            Vector2 vector2 = vector - base.Center;
            int num2 = 30;
            float num3 = 4f;
            float num4 = 5f;
            float num5 = 0.4f;
            float num6 = 0.4f;
            if (vector2.Y >= (float)num2 || vector2.Y <= (float)(-(float)num2))
            {
                float num7 = (float)Math.Sign(vector2.Y) * num6;
                this.velocity.Y = Utils.Clamp<float>(this.velocity.Y + num7, -num4, num4);
            }
            this.velocity.X = Utils.Clamp<float>(this.velocity.X + (float)Math.Sign(vector2.X) * num5, -num3, num3);
            this.rotation = this.velocity.ToRotation();
            this.spriteDirection = ((this.velocity.X < 0f) ? (-1) : 1);
            if (this.timeLeft < 6)
            {
                this.Opacity -= 0.1f;
            }
            else
            {
                this.Opacity += 0.033333335f;
            }
            if (Main.rand.Next(3) != 0)
            {
                Dust dust = Dust.NewDustDirect(this.position, this.width, this.height, 6, this.velocity.X, this.velocity.Y, 0, default(Color), 1f);
                dust.scale = 0.6f;
                dust.fadeIn = 1.1f;
                dust.noGravity = true;
                dust.noLight = true;
            }
        }
References Terraria.Player.active, Terraria.Entity.Center, Terraria.Utils.Clamp(), Terraria.Player.dead, int, Terraria.Dust.NewDustDirect(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.player, Terraria.Main.rand, System.Math.Sign(), Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.