Terraria Decompiled: Terraria.Projectile.RainbowBoulder_HighlightNearbyTreasure
RainbowBoulder_HighlightNearbyTreasure()
void Terraria.Projectile.RainbowBoulder_HighlightNearbyTreasure () inline private
Definition at line 18846 of file Projectile.cs.
        {
            Rectangle rectangle = Utils.CenteredRectangle(base.Center.ToTileCoordinates().ToVector2(), new Vector2(5f, 5f));
            for (int i = rectangle.Left; i <= rectangle.Right; i++)
            {
                for (int j = rectangle.Top; j <= rectangle.Bottom; j++)
                {
                    if (WorldGen.InWorld(i, j, 2))
                    {
                        Tile tile = Main.tile[i, j];
                        if (tile != null && tile.active() && TileID.Sets.FriendlyFairyCanLureTo[(int)tile.type] && SceneMetrics.IsValidForOreFinder(tile))
{
                            Vector2 vector = new Vector2((float)(i * 16 + 8), (float)(j * 16 + 8)) + Main.rand.NextVector2Circular(16f, 16f);
                            for (float num = 0f; num < 0.5f; num += 1f)
{
                                ParticleOrchestrator.RequestParticleSpawn(true, ParticleOrchestraType.RainbowBoulder1, new ParticleOrchestraSettings
{
                                    PositionInWorld = vector,
                                    MovementVector = Vector2.UnitX.RotatedBy((double)(num * 6.2831855f), default(Vector2)) * 16f
                                }, new int?(this.owner));
                            }
                            j++;
                        }
                    }
                }
            }
        }
References Terraria.Tile.active(), Microsoft.Xna.Framework.Rectangle.Bottom, Terraria.Utils.CenteredRectangle(), Terraria.ID.TileID.Sets.FriendlyFairyCanLureTo, int, Terraria.WorldGen.InWorld(), Terraria.SceneMetrics.IsValidForOreFinder(), Microsoft.Xna.Framework.Rectangle.Left, Terraria.Main.rand, Terraria.GameContent.Drawing.ParticleOrchestrator.RequestParticleSpawn(), Microsoft.Xna.Framework.Rectangle.Right, Terraria.Main.tile, Microsoft.Xna.Framework.Rectangle.Top, and Terraria.Tile.type.