Terraria Decompiled: Terraria.Projectile.DropGeodeGems
DropGeodeGems()
void Terraria.Projectile.DropGeodeGems () inline private
Definition at line 80692 of file Projectile.cs.
        {
            List<int> list = new List<int> { 181, 182, 180, 178, 179, 177, 999 };
            int num = list[Main.rand.Next(list.Count)];
            list.Remove(num);
            int num2 = Main.rand.Next(3, 7);
            int num3 = list[Main.rand.Next(list.Count)];
            list.Remove(num3);
            int num4 = Main.rand.Next(3, 7);
            int num5 = Item.NewItem(new EntitySource_Loot(this), this.position, base.Size, num, num2, false, 0, false);
            Main.item[num5].noGrabDelay = 0;
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, num5, 1f, 0f, 0f, 0, 0, 0);
            }
            num5 = Item.NewItem(new EntitySource_Loot(this), this.position, base.Size, num3, num4, false, 0, false);
            Main.item[num5].noGrabDelay = 0;
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, num5, 1f, 0f, 0f, 0, 0, 0);
            }
        }
References Terraria.Main.item, System.list, Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldItem.noGrabDelay, Terraria.Main.rand, System.Collections.Generic.List< T >.Remove(), and Terraria.NetMessage.SendData().