Terraria Decompiled: Terraria.Projectile.Damage_PVP
Damage_PVP()
void Terraria.Projectile.Damage_PVP (Rectangle projRectangle, float projectileSpecificDamageMultiplier) inline private
Definition at line 13491 of file Projectile.cs.
        {
            if (this.damage <= 0)
            {
                return;
            }
            if (Main.player[Main.myPlayer].hostile)
            {
                for (int i = 0; i < 255; i++)
                {
                    if (i != this.owner)
                    {
                        Player player = Main.player[i];
                        if (player.active && !player.dead && !player.immune && player.hostile && this.playerImmune[i] <= 0 && (Main.player[Main.myPlayer].team == 0 || Main.player[Main.myPlayer].team != player.team))
{
                            bool flag = !this.ownerHitCheck;
                            if (this.ownerHitCheck)
{
                                flag |= this.CanHitWithMeleeWeapon(player);
                            }
                            if (flag && this.Colliding(projRectangle, player.getRect()))
{
                                if (this.aiStyle == 3 && !ProjectileID.Sets.IsAPhaseblade[this.type])
{
                                    if (this.ai[0] == 0f)
{
                                        this.velocity.X = -this.velocity.X;
                                        this.velocity.Y = -this.velocity.Y;
                                        this.netUpdate = true;
                                    }
                                    this.ai[0] = 1f;
                                }
                                else if (this.aiStyle == 16)
{
                                    if (this.timeLeft > 3)
{
                                        this.timeLeft = 3;
                                    }
                                    if (player.position.X + (float)(player.width / 2) < this.position.X + (float)(this.width / 2))
{
                                        this.direction = -1;
                                    }
                                    else
{
                                        this.direction = 1;
                                    }
                                }
                                else if (this.aiStyle == 68)
{
                                    if (this.timeLeft > 3)
{
                                        this.timeLeft = 3;
                                    }
                                    if (player.position.X + (float)(player.width / 2) < this.position.X + (float)(this.width / 2))
{
                                        this.direction = -1;
                                    }
                                    else
{
                                        this.direction = 1;
                                    }
                                }
                                int num = this.owner;
                                if (ProjectileID.Sets.IsAGravestone[this.type])
{
                                    num = (int)this.ai[0];
                                }
                                PlayerDeathReason playerDeathReason = PlayerDeathReason.ByProjectile(num, this.whoAmI);
                                if (this.type == 41 && this.timeLeft > 1)
{
                                    this.timeLeft = 1;
                                }
                                bool flag2 = false;
                                if (this.melee && Main.rand.Next(1, 101) <= Main.player[this.owner].meleeCrit)
{
                                    flag2 = true;
                                }
                                int num2 = Main.DamageVar((float)((int)((float)this.damage * projectileSpecificDamageMultiplier)), Main.player[this.owner].luck);
                                bool flag3 = this.IsDamageDodgeable();
                                if (this.type == 856)
{
                                    this.ModifyStellarTuneDamage(ref num2);
                                }
                                if ((this.type == 476 || this.type == 950) && !this.npcProj)
{
                                    float x = Main.player[this.owner].Center.X;
                                    if (player.Center.X < x)
{
                                        this.direction = -1;
                                    }
                                    else
{
                                        this.direction = 1;
                                    }
                                }
                                if (!player.immune)
{
                                    this.StatusPvP(i);
                                }
                                this.TryDoingOnHitEffects(player);
                                int num3 = (int)player.Hurt(playerDeathReason, num2, this.direction, true, false, flag2, -1, flag3);
                                if (num3 > 0 && Main.player[this.owner].ghostHeal && this.friendly && !this.hostile)
{
                                    this.ghostHeal(num3, new Vector2(player.Center.X, player.Center.Y), player);
                                }
                                if (this.type == 304 && num3 > 0)
{
                                    this.vampireHeal(num3, new Vector2(player.Center.X, player.Center.Y), player);
                                }
                                if ((this.melee || ProjectileID.Sets.IsAWhip[this.type]) && Main.player[this.owner].meleeEnchant == 7)
{
                                    Projectile.NewProjectile(this.GetProjectileSource_FromThis(), player.Center.X, player.Center.Y, player.velocity.X, player.velocity.Y, 289, 0, 0f, this.owner, 0f, 0f, 0f, null);
                                }
                                if (Main.netMode != 0)
{
                                    NetMessage.SendPlayerHurt(i, playerDeathReason, num2, this.direction, flag2, true, ImmunityCooldownID.General, -1, -1);
                                }
                                this.playerImmune[i] = 40;
                                if (this.penetrate > 0)
{
                                    this.penetrate--;
                                    if (this.penetrate == 0)
{
                                        break;
                                    }
                                }
                                if (this.aiStyle == 7)
{
                                    this.ai[0] = 1f;
                                    this.damage = 0;
                                    this.netUpdate = true;
                                }
                                else if (this.aiStyle == 13)
{
                                    this.ai[0] = 1f;
                                    this.netUpdate = true;
                                }
                                else if (this.aiStyle == 69)
{
                                    this.ai[0] = 1f;
                                    this.netUpdate = true;
                                }
                            }
                        }
                    }
                }
            }
        }
References Terraria.Player.active, Terraria.DataStructures.PlayerDeathReason.ByProjectile(), Terraria.Entity.Center, Terraria.Main.DamageVar(), Terraria.Player.dead, Terraria.ID.ImmunityCooldownID.General, Terraria.Player.getRect(), Terraria.Player.ghostHeal, Terraria.Player.hostile, Terraria.Player.Hurt(), Terraria.Player.immune, int, Terraria.ID.ProjectileID.Sets.IsAGravestone, Terraria.ID.ProjectileID.Sets.IsAPhaseblade, Terraria.ID.ProjectileID.Sets.IsAWhip, Terraria.Player.luck, Terraria.Player.meleeCrit, Terraria.Player.meleeEnchant, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Projectile.NewProjectile(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.player, Terraria.Entity.position, Terraria.Main.rand, Terraria.NetMessage.SendPlayerHurt(), Terraria.Player.team, Terraria.Entity.velocity, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Projectile.Damage().