Terraria Decompiled: Terraria.Projectile.AI_067_TigerSpecialAttack
AI_067_TigerSpecialAttack()
bool Terraria.Projectile.AI_067_TigerSpecialAttack () inline private
Definition at line 49561 of file Projectile.cs.
        {
            List<NPC> list = new List<NPC>();
            Vector2 center = Main.player[this.owner].Center;
            Rectangle rectangle = Utils.CenteredRectangle(center, new Vector2(1600f, 800f));
            int num = Main.player[this.owner].ownedProjectileCounts[831] + 1;
            for (int i = 0; i < Main.maxNPCs; i++)
            {
                NPC npc = Main.npc[i];
                if (npc.CanBeChasedBy(this, false) && npc.Hitbox.Intersects(rectangle))
                {
                    list.Add(npc);
                }
            }
            if (list.Count == 0)
            {
                return false;
            }
            NPC npc2 = list[0];
            for (int j = 1; j < list.Count; j++)
            {
                if (Vector2.Distance(npc2.Center, center) > Vector2.Distance(list[j].Center, center))
                {
                    npc2 = list[j];
                }
            }
            list.Remove(npc2);
            NPC npc3 = null;
            if (list.Count > 0)
            {
                npc3 = list[0];
                for (int k = 1; k < list.Count; k++)
                {
                    if (base.Distance(npc3.Center) > base.Distance(list[k].Center))
                    {
                        npc3 = list[k];
                    }
                }
                list.Remove(npc3);
            }
            List<Vector2> list2 = new List<Vector2>();
            if (npc3 != null)
            {
                list2.Add(npc3.Center);
            }
            int num2 = 0;
            while (list.Count > 0 && list2.Count < num - 1)
            {
                int num3 = Main.rand.Next(list.Count);
                Vector2 vector = list[num3].velocity * 4f * (float)(num2 + 1);
                list2.Add(list[num3].Center + vector);
                list.RemoveAt(num3);
                num2++;
            }
            if (npc2 != null)
            {
                list2.Add(npc2.Center);
            }
            if (list2.Count > 0 && Collision.SolidCollision(list2[list2.Count - 1] - base.Size / 2f, this.width, this.height))
            {
                list2.Add(center);
            }
            Vector2 vector2 = base.Center;
            float num4 = (float)Math.Min(20, 30 / list2.Count);
            float num5 = 0f;
            for (int l = 0; l < list2.Count; l++)
            {
                float num6 = 20f;
                Vector2 vector3 = list2[l];
                vector3.X += ((vector2.X < vector3.X) ? num6 : (-num6));
                Vector2 vector4 = vector3 - vector2;
                int num7 = (int)Math.Min((double)num4, 4.0 + Math.Ceiling((double)(vector4.Length() / 50f)));
                if (num7 < 5)
                {
                    num7 = 5;
                }
                Projectile.NewProjectile(this.GetProjectileSource_FromThis(), vector2, vector4, 818, this.damage, 0f, this.owner, -num5 * 4f, (float)(num7 * 4), 0f, null);
                vector2 = vector3;
                num5 += (float)num7;
            }
            base.Center = vector2;
            this.ai[0] = 4f;
            this.ai[1] = num5;
            this.netUpdate = true;
            return true;
        }
References System.Collections.Generic.List< T >.Add(), Terraria.NPC.CanBeChasedBy(), System.Math.Ceiling(), Terraria.Entity.Center, Terraria.Utils.CenteredRectangle(), System.Collections.Generic.List< T >.Count, Microsoft.Xna.Framework.Vector2.Distance(), Terraria.Entity.Hitbox, int, Microsoft.Xna.Framework.Rectangle.Intersects(), Microsoft.Xna.Framework.Vector2.Length(), System.list, Terraria.Main.maxNPCs, System.Math.Min(), Terraria.Projectile.NewProjectile(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.npc, Terraria.Player.ownedProjectileCounts, Terraria.Main.player, Terraria.Main.rand, Terraria.Collision.SolidCollision(), and Microsoft.Xna.Framework.Vector2.X.