Terraria Decompiled: Terraria.Projectile.Shimmer
Shimmer()
void Terraria.Projectile.Shimmer () inline private
Definition at line 21946 of file Projectile.cs.
        {
            if (this.hostile && this.aiStyle != 25 && this.aiStyle != 17)
            {
                return;
            }
            if (this.aiStyle == 99 && this.ai[0] == -1f)
            {
                return;
            }
            if (this.aiStyle == 15 && (this.ai[0] == 2f || this.ai[0] == 4f))
            {
                return;
            }
            if (this.type == 502)
            {
                this.velocity.Y = this.velocity.Y - 0.4f;
                this.timeLeft -= 5;
                return;
            }
            if (this.type == 469 || this.type == 181 || this.type == 566)
            {
                this.velocity.Y = this.velocity.Y - 0.2f;
                if (this.type == 469 && this.velocity.Y < 0f)
                {
                    this.Kill();
                    return;
                }
            }
            else
            {
                if (this.type == 819 || this.type == 117 || this.type == 474 || this.type == 225 || this.type == 103 || this.type == 2 || this.type == 82 || this.type == 120 || this.type == 172 || this.type == 41 || this.type == 91 || this.type == 278 || this.type == 5 || this.type == 639 || this.type == 631 || this.type == 495 || this.type == 4 || this.type == 282 || this.type == 1 || this.type == 81)
                {
                    this.velocity.Y = this.velocity.Y - 0.4f;
                    return;
                }
                if (ProjectileID.Sets.IsAPhaseblade[this.type])
                {
                    if (this.ai[0] != 1f)
                    {
                        this.ai[1] = 0f;
                        this.ai[0] = 0f;
                        if (this.velocity.Y > -11f)
{
                            if (this.velocity.Y > 16f)
{
                                this.velocity.Y = this.velocity.Y * 0.9f;
                            }
                            this.velocity.Y = this.velocity.Y - 0.5f;
                        }
                        this.velocity.X = this.velocity.X * 1.1f;
                        this.velocity.X = Utils.Clamp<float>(this.velocity.X, -14f, 14f);
                        return;
                    }
                }
                else if (this.aiStyle == 1 || this.aiStyle == 16 || this.aiStyle == 40 || this.type == 229)
                {
                    int num = (int)(base.Center.X / 16f);
                    int num2 = (int)(this.position.Y / 16f);
                    if (WorldGen.InWorld(num, num2, 0) && Main.tile[num, num2] != null && Main.tile[num, num2].liquid == 255 && Main.tile[num, num2].shimmer() && WorldGen.InWorld(num, num2 - 1, 0) && Main.tile[num, num2 - 1] != null && Main.tile[num, num2 - 1].liquid > 0 && Main.tile[num, num2 - 1].shimmer())
                    {
                        this.Kill();
                        return;
                    }
                    if (this.velocity.Y > 0f)
                    {
                        this.velocity.Y = this.velocity.Y * -1f;
                        this.netUpdate = true;
                        if (this.timeLeft > 600)
{
                            this.timeLeft = 600;
                        }
                        this.timeLeft -= 60;
                        this.shimmerWet = false;
                        this.wet = false;
                        return;
                    }
                }
                else if (this.aiStyle == 5 || this.aiStyle == 8 || this.aiStyle == 21 || this.aiStyle == 28 || this.aiStyle == 29 || this.aiStyle == 33 || this.aiStyle == 36 || this.aiStyle == 47 || this.aiStyle == 93 || this.aiStyle == 115 || this.aiStyle == 151 || this.aiStyle == 152 || this.type == 1024 || this.type == 669)
                {
                    int num3 = (int)(base.Center.X / 16f);
                    int num4 = (int)(this.position.Y / 16f);
                    if (WorldGen.InWorld(num3, num4, 0) && Main.tile[num3, num4] != null && Main.tile[num3, num4].liquid == 255 && Main.tile[num3, num4].shimmer() && WorldGen.InWorld(num3, num4 - 1, 0) && Main.tile[num3, num4 - 1] != null && Main.tile[num3, num4 - 1].liquid > 0 && Main.tile[num3, num4 - 1].shimmer())
                    {
                        this.Kill();
                        return;
                    }
                    if (this.velocity.Y > 0f)
                    {
                        this.velocity.Y = this.velocity.Y * -1f;
                        this.netUpdate = true;
                        this.shimmerWet = false;
                        this.wet = false;
                        return;
                    }
                }
                else if (this.aiStyle == 15)
                {
                    if (this.velocity.Y > 0f)
                    {
                        this.velocity.Y = this.velocity.Y * -1f;
                        this.netUpdate = true;
                    }
                    this.velocity.Y = this.velocity.Y - 0.4f;
                    if (this.velocity.Y < -8f)
                    {
                        this.velocity.Y = -8f;
                        return;
                    }
                }
                else if (this.aiStyle == 99)
                {
                    if (this.velocity.Y > 0f)
                    {
                        this.velocity.Y = this.velocity.Y * -1f;
                        this.netUpdate = true;
                        this.shimmerWet = false;
                        this.wet = false;
                    }
                    if (this.velocity.Y > -8f)
                    {
                        this.velocity.Y = -8f;
                        return;
                    }
                }
                else
                {
                    if (this.aiStyle == 7 || this.aiStyle == 9 || this.aiStyle == 13 || this.aiStyle == 35 || this.aiStyle == 53 || this.aiStyle == 197 || this.aiStyle == 130 || this.aiStyle == 134 || this.aiStyle == 137 || this.aiStyle == 138 || this.aiStyle == 149 || this.aiStyle == 160)
                    {
                        this.Kill();
                        return;
                    }
                    if (this.aiStyle == 2)
                    {
                        this.velocity.Y = this.velocity.Y - 0.7f;
                        if (this.type != 936 || NPC.unlockedSlimeRainbowSpawn || this.velocity.Y >= 0f)
{
                            this.timeLeft -= 20;
                            return;
                        }
                        if (this.timeLeft > 5)
{
                            this.timeLeft = 5;
                        }
                        if (Main.netMode != 1)
{
                            NPC.unlockedSlimeRainbowSpawn = true;
                            NetMessage.SendData(7, -1, -1, null, 0, 0f, 0f, 0f, 0, 0, 0);
                            int num5 = NPC.NewNPC(this.GetNPCSource_FromThis(), (int)base.Center.X + 4, (int)base.Center.Y, 681, 0, 0f, 0f, 0f, 0f, 255);
                            NPC npc = Main.npc[num5];
                            npc.velocity = this.velocity;
                            npc.netUpdate = true;
                            WorldGen.CheckAchievement_RealEstateAndTownSlimes();
                            return;
                        }
                    }
                    else
                    {
                        if (this.aiStyle == 14 || this.aiStyle == 16)
{
                            if (this.timeLeft > 3000)
{
                                this.timeLeft -= 60;
                            }
                            this.velocity.Y = this.velocity.Y - 0.5f;
                            return;
                        }
                        if (this.aiStyle == 25 || this.aiStyle == 17)
{
                            if (this.velocity.Y > 10f)
{
                                this.velocity.Y = this.velocity.Y * 0.97f;
                            }
                            this.velocity.Y = this.velocity.Y - 0.7f;
                            if (this.velocity.Y < -10f)
{
                                this.velocity.Y = -10f;
                            }
                        }
                    }
                }
            }
        }
References Terraria.WorldGen.CheckAchievement_RealEstateAndTownSlimes(), Terraria.Utils.Clamp(), int, Terraria.WorldGen.InWorld(), Terraria.ID.ProjectileID.Sets.IsAPhaseblade, Terraria.Tile.liquid, Terraria.Main.netMode, Terraria.NPC.NewNPC(), Terraria.Main.npc, Terraria.NetMessage.SendData(), Terraria.Tile.shimmer(), Terraria.Main.tile, and Terraria.NPC.unlockedSlimeRainbowSpawn.