Terraria Decompiled: Terraria.Projectile.AI_016_CanAcornPlant
AI_016_CanAcornPlant()
bool Terraria.Projectile.AI_016_CanAcornPlant (out Point plantPoint) inline private
Definition at line 47265 of file Projectile.cs.
        {
            plantPoint = Point.Zero;
            Point point = base.Center.ToTileCoordinates();
            if (!WorldGen.InWorld(point.X, point.Y, 5))
            {
                return false;
            }
            for (int i = 0; i < 2; i++)
            {
                Point point2 = new Point(point.X, point.Y + i);
                if (!WorldGen.InWorld(point.X, point.Y, 5))
                {
                    break;
                }
                Tile tile = Main.tile[point2.X, point2.Y];
                if (tile != null && tile.active() && tile.nactive() && !tile.topSlope() && !tile.halfBrick())
                {
                    Tile tile2 = Main.tile[point2.X, point2.Y - 1];
                    if (tile2 != null && (!tile2.active() || tile2.type < 0 || Main.tileCut[(int)tile2.type]) && WorldGen.CanCutTile(point2.X, point2.Y - 1, TileCuttingContext.TilePlacement))
                    {
                        Tile tile3 = Main.tile[point2.X, point2.Y - 2];
                        if (tile3 != null && (!tile3.active() || tile3.type < 0 || Main.tileCut[(int)tile3.type]) && WorldGen.CanCutTile(point2.X, point2.Y - 2, TileCuttingContext.TilePlacement))
{
                            ushort num = tile.type;
                            if (num <= 116)
{
                                if (num <= 53)
{
                                    if (num != 2 && num != 23 && num != 53)
{
                                        goto IL_0231;
                                    }
                                }
                                else if (num <= 109)
{
                                    if (num != 60 && num != 109)
{
                                        goto IL_0231;
                                    }
                                }
                                else if (num != 112 && num != 116)
{
                                    goto IL_0231;
                                }
                            }
                            else if (num <= 234)
{
                                if (num != 147 && num != 199 && num != 234)
{
                                    goto IL_0231;
                                }
                            }
                            else if (num <= 492)
{
                                if (num != 477 && num != 492)
{
                                    goto IL_0231;
                                }
                            }
                            else if (num != 633 && num - 661 > 1)
{
                                goto IL_0231;
                            }
                            plantPoint = new Point(point2.X, point2.Y - 1);
                            return true;
                        }
                    }
                }
                IL_0231:;
            }
            return false;
        }
References Terraria.Tile.active(), Terraria.WorldGen.CanCutTile(), Terraria.Tile.halfBrick(), Terraria.WorldGen.InWorld(), Terraria.Tile.nactive(), Terraria.Main.tile, Terraria.Main.tileCut, Terraria.Tile.topSlope(), Terraria.Tile.type, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Point.Y, and Microsoft.Xna.Framework.Point.Zero.