Terraria Decompiled: Terraria.Projectile.FishingCheck_RollItemDrop
FishingCheck_RollItemDrop()
void Terraria.Projectile.FishingCheck_RollItemDrop (ref FishingAttempt fisher) inline private
Definition at line 19538 of file Projectile.cs.
        {
            fisher.rolledItemDrop = Main.FishDropsDB.TryGetItemDropType(Projectile._context);
            if (fisher.rolledItemDrop == 0)
            {
                return;
            }
            if (Main.player[this.owner].sonarPotion)
            {
                ParticleOrchestrator.RequestParticleSpawn(true, ParticleOrchestraType.FakeFish, new ParticleOrchestraSettings
                {
                    PositionInWorld = base.Center + new Vector2(0f, 24f) + Main.rand.NextVector2Circular(16f, 0f),
                    MovementVector = base.Center + new Vector2(0f, 24f),
                    UniqueInfoPiece = fisher.rolledItemDrop
                }, new int?(this.owner));
                ParticleOrchestrator.PingFakeFish(this, fisher.rolledItemDrop);
                ParticleOrchestrator.PushAwayFakeFish(this, fisher.rolledItemDrop);
            }
            ParticleOrchestrator.MagnetFakeFish(this, fisher.rolledItemDrop);
        }
References Terraria.Projectile._context, Terraria.Main.FishDropsDB, Terraria.GameContent.Drawing.ParticleOrchestrator.MagnetFakeFish(), Terraria.GameContent.Drawing.ParticleOrchestrator.PingFakeFish(), Terraria.Main.player, Terraria.GameContent.Drawing.ParticleOrchestrator.PushAwayFakeFish(), Terraria.GameContent.Drawing.ParticleOrchestrator.RequestParticleSpawn(), Terraria.Player.sonarPotion, and Terraria.GameContent.FishDropRules.FishDropRuleList.TryGetItemDropType().