Terraria Decompiled: Terraria.Initializers.UILinksInitializer.FancyUISpecialInstructions
FancyUISpecialInstructions()
static string Terraria.Initializers.UILinksInitializer.FancyUISpecialInstructions () inline static
Definition at line 2214 of file UILinksInitializer.cs.
        {
            string text = "";
            int fancyui_SPECIAL_INSTRUCTIONS = UILinkPointNavigator.Shortcuts.FANCYUI_SPECIAL_INSTRUCTIONS;
            if (fancyui_SPECIAL_INSTRUCTIONS == 1)
            {
                if (UILinksInitializer.CanExecuteInputCommand() && PlayerInput.Triggers.JustPressed.HotbarMinus)
                {
                    UIVirtualKeyboard.CycleSymbols();
                    PlayerInput.LockGamepadButtons("HotbarMinus");
                    PlayerInput.SettingsForUI.TryRevertingToMouseMode();
                }
                text += PlayerInput.BuildCommand(Lang.menu[235].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["HotbarMinus"] });
                if (UILinksInitializer.CanExecuteInputCommand() && PlayerInput.Triggers.JustPressed.MouseRight)
                {
                    UIVirtualKeyboard.BackSpace();
                    PlayerInput.LockGamepadButtons("MouseRight");
                    PlayerInput.SettingsForUI.TryRevertingToMouseMode();
                }
                text += PlayerInput.BuildCommand(Lang.menu[236].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["MouseRight"] });
                if (UILinksInitializer.CanExecuteInputCommand() && PlayerInput.Triggers.JustPressed.SmartCursor)
                {
                    UIVirtualKeyboard.Write(" ");
                    PlayerInput.LockGamepadButtons("SmartCursor");
                    PlayerInput.SettingsForUI.TryRevertingToMouseMode();
                }
                text += PlayerInput.BuildCommand(Lang.menu[238].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["SmartCursor"] });
                if (UIVirtualKeyboard.CanSubmit)
                {
                    if (UILinksInitializer.CanExecuteInputCommand() && PlayerInput.Triggers.JustPressed.HotbarPlus)
                    {
                        UIVirtualKeyboard.Submit();
                        PlayerInput.LockGamepadButtons("HotbarPlus");
                        PlayerInput.SettingsForUI.TryRevertingToMouseMode();
                    }
                    text += PlayerInput.BuildCommand(Lang.menu[237].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["HotbarPlus"] });
                }
            }
            return text;
        }
References Terraria.GameContent.UI.States.UIVirtualKeyboard.BackSpace(), Terraria.GameInput.PlayerInput.BuildCommand(), Terraria.Initializers.UILinksInitializer.CanExecuteInputCommand(), Terraria.GameContent.UI.States.UIVirtualKeyboard.CanSubmit, Terraria.GameContent.UI.States.UIVirtualKeyboard.CycleSymbols(), Terraria.UI.Gamepad.UILinkPointNavigator.Shortcuts.FANCYUI_SPECIAL_INSTRUCTIONS, Terraria.GameInput.TriggersSet.HotbarMinus, Terraria.GameInput.TriggersSet.HotbarPlus, Terraria.GameInput.TriggersPack.JustPressed, Terraria.GameInput.PlayerInput.LockGamepadButtons(), Terraria.Lang.menu, Terraria.GameInput.TriggersSet.MouseRight, Terraria.GameInput.TriggersSet.SmartCursor, Terraria.GameContent.UI.States.UIVirtualKeyboard.Submit(), System.text, Terraria.GameInput.PlayerInput.Triggers, Terraria.GameInput.PlayerInput.SettingsForUI.TryRevertingToMouseMode(), Terraria.Localization.LocalizedText.Value, and Terraria.GameContent.UI.States.UIVirtualKeyboard.Write().