Terraria Decompiled: Terraria.Initializers.UILinksInitializer.HandleSliderVerticalInput
HandleSliderVerticalInput()
static float Terraria.Initializers.UILinksInitializer.HandleSliderVerticalInput (float currentValue, float min, float max, float deadZone = 0::2f, float sensitivity = 0::5f) inline static
Definition at line 44 of file UILinksInitializer.cs.
        {
            float num = -PlayerInput.GamepadThumbstickLeft.Y;
            if (num < -deadZone || num > deadZone)
            {
                num = MathHelper.Lerp(0f, sensitivity / 60f, (Math.Abs(num) - deadZone) / (1f - deadZone)) * (float)Math.Sign(num);
            }
            else
            {
                num = 0f;
            }
            return MathHelper.Clamp((currentValue - min) / (max - min) + num, 0f, 1f) * (max - min) + min;
        }
References System.Math.Abs(), Microsoft.Xna.Framework.MathHelper.Clamp(), Terraria.GameInput.PlayerInput.GamepadThumbstickLeft, Microsoft.Xna.Framework.MathHelper.Lerp(), System.Math.Sign(), and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.GameContent.Creative.CreativePowers.APerPlayerSliderPower.SetValueGamepad(), and Terraria.GameContent.Creative.CreativePowers.ASharedSliderPower.SetValueGamepad().