Terraria Decompiled: Terraria.Initializers.UILinksInitializer.FancyExit
FancyExit()
static void Terraria.Initializers.UILinksInitializer.FancyExit () inline static
Definition at line 2171 of file UILinksInitializer.cs.
        {
            switch (UILinkPointNavigator.Shortcuts.BackButtonCommand)
            {
            case 1:
                SoundEngine.PlaySound(11, -1, -1, 1, 1f, 0f);
                Main.menuMode = 0;
                return;
            case 2:
                SoundEngine.PlaySound(11, -1, -1, 1, 1f, 0f);
                Main.menuMode = (Main.menuMultiplayer ? 12 : 1);
                return;
            case 3:
                Main.menuMode = 0;
                IngameFancyUI.Close(false);
                return;
            case 4:
                SoundEngine.PlaySound(11, -1, -1, 1, 1f, 0f);
                Main.menuMode = 11;
                return;
            case 5:
                SoundEngine.PlaySound(11, -1, -1, 1, 1f, 0f);
                Main.menuMode = 11;
                return;
            case 6:
                Main.LocalPlayer.releaseInventory = false;
                UIVirtualKeyboard.Cancel();
                return;
            case 7:
            {
                IHaveBackButtonCommand haveBackButtonCommand = Main.MenuUI.CurrentState as IHaveBackButtonCommand;
                if (haveBackButtonCommand != null)
                {
                    haveBackButtonCommand.HandleBackButtonUsage();
                }
                return;
            }
            default:
                return;
            }
        }
References Terraria.UI.Gamepad.UILinkPointNavigator.Shortcuts.BackButtonCommand, Terraria.GameContent.UI.States.UIVirtualKeyboard.Cancel(), Terraria.UI.IngameFancyUI.Close(), Terraria.UI.IHaveBackButtonCommand.HandleBackButtonUsage(), and Terraria.Audio.SoundEngine.PlaySound().