Terraria Decompiled: Terraria.GameContent.Tile_Entities.TEDisplayDoll.OnPlayerUpdate
OnPlayerUpdate()
override void Terraria.GameContent.Tile_Entities.TEDisplayDoll.OnPlayerUpdate (Player player) inline
Definition at line 491 of file TEDisplayDoll.cs.
        {
            if (!player.InTileEntityInteractionRange(player.tileEntityAnchor.X, player.tileEntityAnchor.Y, 2, 3, TileReachCheckSettings.Simple) || player.chest != -1 || player.talkNPC != -1)
            {
                if (player.chest == -1 && player.talkNPC == -1)
                {
                    SoundEngine.PlaySound(11, -1, -1, 1, 1f, 0f);
                }
                player.tileEntityAnchor.Clear();
            }
        }
References Terraria.Player.chest, Terraria.DataStructures.PlayerInteractionAnchor.Clear(), Terraria.Player.InTileEntityInteractionRange(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.DataStructures.TileReachCheckSettings.Simple, Terraria.Player.talkNPC, Terraria.Player.tileEntityAnchor, Terraria.DataStructures.PlayerInteractionAnchor.X, and Terraria.DataStructures.PlayerInteractionAnchor.Y.