Terraria Decompiled: Terraria.GameContent.Tile_Entities.TEDisplayDoll.Draw
Draw()
void Terraria.GameContent.Tile_Entities.TEDisplayDoll.Draw (int tileLeftX, int tileTopY) inline
Definition at line 331 of file TEDisplayDoll.cs.
        {
            Player dollPlayer = this._dollPlayer;
            for (int i = 0; i < 8; i++)
            {
                dollPlayer.armor[i] = this._equip[i];
                dollPlayer.dye[i] = this._dyes[i];
            }
            Item item = this._misc[0];
            dollPlayer.inventory[0] = item;
            dollPlayer.direction = -1;
            dollPlayer.Male = true;
            Tile tileSafely = Framing.GetTileSafely(tileLeftX, tileTopY);
            if (tileSafely.frameX % 72 == 36)
            {
                dollPlayer.direction = 1;
            }
            if (tileSafely.frameX / 72 == 1)
            {
                dollPlayer.Male = false;
            }
            dollPlayer.isDisplayDollOrInanimate = true;
            dollPlayer.ResetEffects();
            dollPlayer.ResetVisibleAccessories();
            dollPlayer.UpdateDyes();
            dollPlayer.DisplayDollUpdate();
            dollPlayer.UpdateSocialShadow();
            dollPlayer.bodyFrameCounter = 0.0;
            dollPlayer.headFrameCounter = 0.0;
            dollPlayer.legFrameCounter = 0.0;
            dollPlayer.wingFrameCounter = 0;
            dollPlayer.sitting.isSitting = false;
            dollPlayer.itemAnimationMax = 0;
            dollPlayer.itemAnimation = 0;
            Item item2 = this._equip[8];
            int num = -1;
            if (!item2.IsAir)
            {
                num = item2.mountType;
            }
            if (dollPlayer.mount.Type != num)
            {
                if (num == -1)
                {
                    dollPlayer.mount.Dismount(dollPlayer, false);
                }
                else
                {
                    dollPlayer.mount.SetMount(num, dollPlayer);
                }
            }
            dollPlayer.miscDyes[3] = this._dyes[8];
            dollPlayer.miscDyes[2] = this._dyes[8];
            int num2 = 0;
            DisplayDollPoseID displayDollPoseID = (DisplayDollPoseID)this._pose;
            if (!this.IsValidPose((int)this._pose))
            {
                displayDollPoseID = DisplayDollPoseID.Standing;
            }
            if (num != -1)
            {
                dollPlayer.mount.ApplyDummyFrameCounters();
                if (displayDollPoseID == DisplayDollPoseID.Sitting || displayDollPoseID == DisplayDollPoseID.Jumping)
                {
                    displayDollPoseID = DisplayDollPoseID.Standing;
                }
            }
            switch (displayDollPoseID)
            {
            case DisplayDollPoseID.Standing:
                dollPlayer.velocity = Vector2.Zero;
                break;
            case DisplayDollPoseID.Sitting:
                dollPlayer.velocity = Vector2.Zero;
                dollPlayer.sitting.isSitting = true;
                num2 = 14;
                break;
            case DisplayDollPoseID.Jumping:
                dollPlayer.velocity = Vector2.UnitY;
                break;
            case DisplayDollPoseID.Walking:
                dollPlayer.velocity = Vector2.UnitX * (float)dollPlayer.direction;
                dollPlayer.legFrame.Y = dollPlayer.legFrame.Height * 9;
                dollPlayer.bodyFrame.Y = dollPlayer.legFrame.Y;
                break;
            default:
            {
                dollPlayer.velocity = Vector2.Zero;
                List<TEDisplayDoll.DisplayDollPose> list;
                if (TEDisplayDoll.SupportedUseStylePoses.TryGetValue(item.useStyle, out list))
                {
                    foreach (TEDisplayDoll.DisplayDollPose displayDollPose in list)
                    {
                        if ((DisplayDollPoseID)this._pose == displayDollPose.Pose)
{
                            dollPlayer.itemAnimationMax = 1000;
                            dollPlayer.itemAnimation = (int)(1000f * displayDollPose.ItemAnimationPercent);
                            dollPlayer.itemRotation = 0f;
                            float? num3 = displayDollPose.ItemAimRadians;
                            if (num3 == null)
{
                                break;
                            }
                            Player player = dollPlayer;
                            num3 = displayDollPose.ItemAimRadians;
                            player.itemRotation = num3.Value;
                            if (dollPlayer.direction == -1)
{
                                dollPlayer.itemRotation *= -1f;
                                break;
                            }
                            break;
                        }
                    }
                }
                break;
            }
            }
            dollPlayer.PlayerFrame();
            Vector2 vector = new Vector2((float)(tileLeftX + 1), (float)(tileTopY + 3)) * 16f + new Vector2((float)(-(float)dollPlayer.width / 2), (float)(-(float)dollPlayer.height - 6 + num2));
            dollPlayer.position = vector;
            dollPlayer.lastVisualizedSelectedItem = item;
            dollPlayer.ItemCheck_EmitHeldItemLight(item);
            dollPlayer.AnimatePlayerAndGetItemFrame(0f, item);
            TEDisplayDoll._playerRenderer.OverrideHeldProjectile = null;
            if (item != null && !item.IsAir && item.shoot > 0)
            {
                Projectile projectileDummy = TEDisplayDoll._projectileDummy;
                projectileDummy.SetDefaults(item.shoot);
                projectileDummy.isAPreviewDisplayDoll = true;
                bool flag = false;
                List<TEDisplayDoll.DisplayDollPose> list2;
                if (TEDisplayDoll.SupportedUseStylePoses.TryGetValue(item.useStyle, out list2))
                {
                    foreach (TEDisplayDoll.DisplayDollPose displayDollPose2 in list2)
                    {
                        if ((DisplayDollPoseID)this._pose == displayDollPose2.Pose)
{
                            projectileDummy.AI_DisplayDoll(dollPlayer, displayDollPose2, out flag);
                            break;
                        }
                    }
                }
                if (flag)
                {
                    TEDisplayDoll._playerRenderer.OverrideHeldProjectile = projectileDummy;
                    int drawLayer = projectileDummy.drawLayer;
                    if (drawLayer <= 3)
                    {
                        Main.instance.DrawProjDirect(projectileDummy, null);
                    }
                }
            }
            dollPlayer.isFullbright = tileSafely.fullbrightBlock();
            dollPlayer.skinDyePacked = PlayerDrawHelper.PackShader((int)tileSafely.color(), PlayerDrawHelper.ShaderConfiguration.TilePaintID);
            TEDisplayDoll._playerRenderer.PrepareDrawForFrame(dollPlayer);
            TEDisplayDoll._playerRenderer.DrawPlayer(Main.Camera, dollPlayer, dollPlayer.position, 0f, dollPlayer.fullRotationOrigin, 0f, 1f);
        }
References Terraria.GameContent.Tile_Entities.TEDisplayDoll._playerRenderer, Terraria.GameContent.Tile_Entities.TEDisplayDoll._projectileDummy, Terraria.Projectile.AI_DisplayDoll(), Terraria.Player.AnimatePlayerAndGetItemFrame(), Terraria.Mount.ApplyDummyFrameCounters(), Terraria.Player.armor, Terraria.Main.Camera, Terraria.Tile.color(), Terraria.Entity.direction, Terraria.Mount.Dismount(), Terraria.Player.DisplayDollUpdate(), Terraria.Projectile.drawLayer, Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayer(), Terraria.Main.DrawProjDirect(), Terraria.Player.dye, Terraria.Tile.frameX, Terraria.Tile.fullbrightBlock(), Terraria.Player.fullRotationOrigin, Terraria.Framing.GetTileSafely(), Terraria.Entity.height, Terraria.Main.instance, int, Terraria.Player.inventory, Terraria.Item.IsAir, System.item, Terraria.GameContent.Tile_Entities.TEDisplayDoll.DisplayDollPose.ItemAimRadians, Terraria.Player.ItemCheck_EmitHeldItemLight(), Terraria.Player.legFrame, System.list, Terraria.Player.miscDyes, Terraria.Player.mount, Terraria.Item.mountType, Terraria.DataStructures.PlayerDrawHelper.PackShader(), Terraria.Player.PlayerFrame(), Terraria.Entity.position, Terraria.Graphics.Renderers.LegacyPlayerRenderer.PrepareDrawForFrame(), Terraria.Player.ResetEffects(), Terraria.Player.ResetVisibleAccessories(), Terraria.Projectile.SetDefaults(), Terraria.Mount.SetMount(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.SupportedUseStylePoses, Terraria.Mount.Type, Microsoft.Xna.Framework.Vector2.UnitY, Terraria.Player.UpdateDyes(), Terraria.Player.UpdateSocialShadow(), Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Entity.width, Microsoft.Xna.Framework.Rectangle.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.Drawing.TileDrawing.DrawEntities_DisplayDolls().