Terraria Decompiled: Terraria.GameContent.Tile_Entities.TEDisplayDoll.TryFitting
TryFitting()
bool Terraria.GameContent.Tile_Entities.TEDisplayDoll.TryFitting (Item[] inv, int slot) inline private
Definition at line 682 of file TEDisplayDoll.cs.
        {
            Item item = inv[slot];
            Item[] array = this._equip;
            int num = -1;
            if (item.headSlot > 0)
            {
                num = 0;
            }
            else if (item.bodySlot > 0)
            {
                num = 1;
            }
            else if (item.legSlot > 0)
            {
                num = 2;
            }
            else if (item.accessory)
            {
                num = this.GetAccessoryTargetSlot(item);
            }
            else if (item.mountType >= 0)
            {
                num = 8;
            }
            else if (TEDisplayDoll.AcceptedInWeaponSlot(item))
            {
                array = this._misc;
                num = 0;
            }
            if (num == -1)
            {
                return false;
            }
            if (item.stack > 1 && !array[num].IsAir)
            {
                return true;
            }
            SoundEngine.PlaySound(7, -1, -1, 1, 1f, 0f);
            if (item.stack > 1)
            {
                item.favorited = false;
                array[num] = item.Clone();
                array[num].stack = 1;
                item.stack--;
            }
            else
            {
                inv[slot].favorited = false;
                Utils.Swap<Item>(ref array[num], ref inv[slot]);
            }
            if (Main.netMode == 1)
            {
                NetMessage.SendData(121, -1, -1, null, Main.myPlayer, (float)this.ID, (float)num, (float)((array == this._misc) ? 3 : 0), 0, 0, 0);
            }
            return true;
        }
References Terraria.GameContent.Tile_Entities.TEDisplayDoll.AcceptedInWeaponSlot(), System.array, Terraria.Item.favorited, System.item, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Audio.SoundEngine.PlaySound(), and Terraria.NetMessage.SendData().