Terraria Decompiled: Terraria.GameContent.Tile_Entities.TEDisplayDoll.ReadExtraData
ReadExtraData()
override void Terraria.GameContent.Tile_Entities.TEDisplayDoll.ReadExtraData (BinaryReader reader, int gameVersion, bool networkSend) inline
Definition at line 198 of file TEDisplayDoll.cs.
        {
            BitsByte bitsByte = reader.ReadByte();
            BitsByte bitsByte2 = reader.ReadByte();
            if (gameVersion >= 307)
            {
                this._pose = reader.ReadByte();
            }
            BitsByte bitsByte3 = 0;
            if (gameVersion >= 308)
            {
                bitsByte3 = reader.ReadByte();
            }
            bool flag = false;
            if (gameVersion == 311)
            {
                flag = bitsByte3[1];
                bitsByte3[1] = false;
            }
            int num = (int)bitsByte | (bitsByte3[1] ? 256 : 0);
            for (int i = 0; i < this._equip.Length; i++)
            {
                this._equip[i] = new Item();
                Item item = this._equip[i];
                if ((num & (1 << i)) != 0)
                {
                    item.netDefaults((int)reader.ReadInt16());
                    item.Prefix((int)reader.ReadByte());
                    item.stack = (int)reader.ReadInt16();
                }
            }
            long num2 = (long)((int)bitsByte2 | (bitsByte3[2] ? 256 : 0));
            for (int j = 0; j < this._dyes.Length; j++)
            {
                this._dyes[j] = new Item();
                Item item2 = this._dyes[j];
                if ((num2 & (1L << (j & 31))) != 0L)
                {
                    item2.netDefaults((int)reader.ReadInt16());
                    item2.Prefix((int)reader.ReadByte());
                    item2.stack = (int)reader.ReadInt16();
                }
            }
            for (int k = 0; k < this._misc.Length; k++)
            {
                this._misc[k] = new Item();
                Item item3 = this._misc[k];
                if (bitsByte3[k])
                {
                    item3.netDefaults((int)reader.ReadInt16());
                    item3.Prefix((int)reader.ReadByte());
                    item3.stack = (int)reader.ReadInt16();
                }
            }
            if (flag)
            {
                Item item4 = this._equip[8];
                item4.netDefaults((int)reader.ReadInt16());
                item4.Prefix((int)reader.ReadByte());
                item4.stack = (int)reader.ReadInt16();
            }
        }
References int, System.item, System.L, long, Terraria.Item.netDefaults(), Terraria.Item.Prefix(), System.IO.BinaryReader.ReadByte(), and System.IO.BinaryReader.ReadInt16().