Terraria Decompiled: Terraria.GameContent.Tile_Entities.TEDisplayDoll.Framing_CheckTile
Framing_CheckTile()
static void Terraria.GameContent.Tile_Entities.TEDisplayDoll.Framing_CheckTile (int callX, int callY) inline static
Definition at line 279 of file TEDisplayDoll.cs.
        {
            if (WorldGen.destroyObject)
            {
                return;
            }
            Tile tileSafely = Framing.GetTileSafely(callX, callY);
            int num = callX - (int)(tileSafely.frameX / 18 % 2);
            int num2 = callY - (int)(tileSafely.frameY / 18 % 3);
            bool flag = false;
            for (int i = num; i < num + 2; i++)
            {
                for (int j = num2; j < num2 + 3; j++)
                {
                    Tile tile = Main.tile[i, j];
                    if (!tile.active() || tile.type != 470)
                    {
                        flag = true;
                    }
                }
            }
            if (!WorldGen.SolidTileAllowBottomSlope(num, num2 + 3) || !WorldGen.SolidTileAllowBottomSlope(num + 1, num2 + 3))
            {
                flag = true;
            }
            if (flag)
            {
                TileEntityType<TEDisplayDoll>.Kill(num, num2);
                if (Main.tile[callX, callY].frameX / 72 != 1)
                {
                    Item.NewItem(new EntitySource_TileBreak(num, num2), num * 16, num2 * 16, 32, 48, 498, 1, false, 0, false);
                }
                else
                {
                    Item.NewItem(new EntitySource_TileBreak(num, num2), num * 16, num2 * 16, 32, 48, 1989, 1, false, 0, false);
                }
                WorldGen.destroyObject = true;
                for (int k = num; k < num + 2; k++)
                {
                    for (int l = num2; l < num2 + 3; l++)
                    {
                        if (Main.tile[k, l].active() && Main.tile[k, l].type == 470)
{
                            WorldGen.KillTile(k, l, false, false, false);
                        }
                    }
                }
                WorldGen.destroyObject = false;
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.destroyObject, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Framing.GetTileSafely(), int, Terraria.DataStructures.TileEntityType< T >.Kill(), Terraria.WorldGen.KillTile(), Terraria.Item.NewItem(), Terraria.WorldGen.SolidTileAllowBottomSlope(), Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.TileFrameImportant().