Terraria Decompiled: System.Threading.Thread.Start
Start() [3/3]
void System.Threading.Thread.Start (ref StackCrawlMark stackMark) inline private
Definition at line 108 of file Thread.cs.
        {
            if (this.m_Delegate != null)
            {
                ThreadHelper threadHelper = (ThreadHelper)this.m_Delegate.Target;
                ExecutionContext executionContext = ExecutionContext.Capture(ref stackMark, ExecutionContext.CaptureOptions.IgnoreSyncCtx);
                threadHelper.SetExecutionContextHelper(executionContext);
            }
            object obj = null;
            this.StartInternal(obj, ref stackMark);
        }
References System.Threading.ExecutionContext.Capture(), System.Threading.Thread.m_Delegate, System.obj, System.Threading.ThreadHelper.SetExecutionContextHelper(), System.Threading.Thread.StartInternal(), and System.Delegate.Target.