Terraria Decompiled: Terraria.Social.Steam.NetServerSocialModule.Close
Close() [1/2]
void Terraria.Social.Steam.NetServerSocialModule.Close (CSteamID user) inline private
Definition at line 137 of file NetServerSocialModule.cs.
        {
            if (!this._connectionStateMap.ContainsKey(user))
            {
                return;
            }
            Task.Factory.StartNew(delegate
            {
                Thread.Sleep(2000);
                SteamUser.EndAuthSession(user);
                SteamNetworking.CloseP2PSessionWithUser(user);
            });
            this._connectionStateMap[user] = NetSocialModule.ConnectionState.Inactive;
            this._reader.ClearUser(user);
        }
References Terraria.Social.Steam.NetSocialModule._connectionStateMap, Terraria.Social.Steam.NetSocialModule._reader, Terraria.Social.Steam.SteamP2PReader.ClearUser(), Steamworks.SteamNetworking.CloseP2PSessionWithUser(), Steamworks.SteamUser.EndAuthSession(), System.Threading.Tasks.Task< TResult >.Factory, System.Threading.Thread.Sleep(), and System.Threading.Tasks.TaskFactory< TResult >.StartNew().