Terraria Decompiled: System.Threading.Thread.DeserializePrincipal
DeserializePrincipal()
static void System.Threading.Thread.DeserializePrincipal (Thread th) inline static private
Definition at line 601 of file Thread.cs.
        {
            MemoryStream memoryStream = new MemoryStream(Thread.ByteArrayToCurrentDomain(th.Internal._serialized_principal));
            int num = memoryStream.ReadByte();
            if (num == 0)
            {
                BinaryFormatter binaryFormatter = new BinaryFormatter();
                th.principal = (IPrincipal)binaryFormatter.Deserialize(memoryStream);
                th.principal_version = th.Internal._serialized_principal_version;
                return;
            }
            if (num == 1)
            {
                BinaryReader binaryReader = new BinaryReader(memoryStream);
                string text = binaryReader.ReadString();
                string text2 = binaryReader.ReadString();
                int num2 = binaryReader.ReadInt32();
                string[] array = null;
                if (num2 >= 0)
                {
                    array = new string[num2];
                    for (int i = 0; i < num2; i++)
                    {
                        array[i] = binaryReader.ReadString();
                    }
                }
                th.principal = new GenericPrincipal(new GenericIdentity(text, text2), array);
                return;
            }
            if (num == 2 || num == 3)
            {
                string[] array2 = ((num == 2) ? null : new string[0]);
                th.principal = new GenericPrincipal(new GenericIdentity("", ""), array2);
            }
        }
References System.Threading.InternalThread._serialized_principal, System.Threading.InternalThread._serialized_principal_version, System.array, System.Threading.Thread.ByteArrayToCurrentDomain(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(), System.Threading.Thread.Internal, System.IO.MemoryStream.ReadByte(), System.IO.BinaryReader.ReadInt32(), System.IO.BinaryReader.ReadString(), and System.text.