Terraria Decompiled: Terraria.Social.Steam.NetServerSocialModule.BroadcastConnectedUsers
BroadcastConnectedUsers()
void Terraria.Social.Steam.NetServerSocialModule.BroadcastConnectedUsers () inline private
Definition at line 25 of file NetServerSocialModule.cs.
        {
            List<ulong> list = new List<ulong>();
            foreach (KeyValuePair<CSteamID, NetSocialModule.ConnectionState> keyValuePair in this._connectionStateMap)
            {
                if (keyValuePair.Value == NetSocialModule.ConnectionState.Connected)
                {
                    list.Add(keyValuePair.Key.m_SteamID);
                }
            }
            byte[] array = new byte[list.Count * 8 + 1];
            using (MemoryStream memoryStream = new MemoryStream(array))
            {
                using (BinaryWriter binaryWriter = new BinaryWriter(memoryStream))
                {
                    binaryWriter.Write(1);
                    foreach (ulong num in list)
                    {
                        binaryWriter.Write(num);
                    }
                }
            }
            this._lobby.SendMessage(array);
        }
References Terraria.Social.Steam.NetSocialModule._connectionStateMap, Terraria.Social.Steam.NetSocialModule._lobby, System.array, System.Collections.Generic.KeyValuePair< TKey, TValue >.Key, System.list, Terraria.Social.Steam.Lobby.SendMessage(), System.Collections.Generic.KeyValuePair< TKey, TValue >.Value, and System.IO.BinaryWriter.Write().
Referenced by Terraria.Social.Steam.NetServerSocialModule.OnPacketRead().