Terraria Decompiled: System.Threading.Thread.Start
Start() [2/3]
void System.Threading.Thread.Start (object parameter) inline
Definition at line 95 of file Thread.cs.
        {
            if (this.m_Delegate is ThreadStart)
            {
                throw new InvalidOperationException(Environment.GetResourceString("The thread was created with a ThreadStart delegate that does not accept a parameter."));
            }
            this.m_ThreadStartArg = parameter;
            StackCrawlMark stackCrawlMark = StackCrawlMark.LookForMyCaller;
            this.Start(ref stackCrawlMark);
        }
References System.Environment.GetResourceString(), System.Threading.Thread.m_Delegate, System.Threading.Thread.Start(), and System.Threading.ThreadStart().