Terraria Decompiled: System.Threading.Thread.SerializePrincipal
SerializePrincipal()
static void System.Threading.Thread.SerializePrincipal (Thread th, IPrincipal value) inline static private
Definition at line 638 of file Thread.cs.
        {
            MemoryStream memoryStream = new MemoryStream();
            bool flag = false;
            if (value.GetType() == typeof(GenericPrincipal))
            {
                GenericPrincipal genericPrincipal = (GenericPrincipal)value;
                if (genericPrincipal.Identity != null && genericPrincipal.Identity.GetType() == typeof(GenericIdentity))
                {
                    GenericIdentity genericIdentity = (GenericIdentity)genericPrincipal.Identity;
                    if (genericIdentity.Name == "" && genericIdentity.AuthenticationType == "")
                    {
                        if (genericPrincipal.Roles == null)
{
                            memoryStream.WriteByte(2);
                            flag = true;
                        }
                        else if (genericPrincipal.Roles.Length == 0)
{
                            memoryStream.WriteByte(3);
                            flag = true;
                        }
                    }
                    else
                    {
                        memoryStream.WriteByte(1);
                        BinaryWriter binaryWriter = new BinaryWriter(memoryStream);
                        binaryWriter.Write(genericPrincipal.Identity.Name);
                        binaryWriter.Write(genericPrincipal.Identity.AuthenticationType);
                        string[] roles = genericPrincipal.Roles;
                        if (roles == null)
{
                            binaryWriter.Write(-1);
                        }
                        else
{
                            binaryWriter.Write(roles.Length);
                            foreach (string text in roles)
{
                                binaryWriter.Write(text);
                            }
                        }
                        binaryWriter.Flush();
                        flag = true;
                    }
                }
            }
            if (!flag)
            {
                memoryStream.WriteByte(0);
                BinaryFormatter binaryFormatter = new BinaryFormatter();
                try
                {
                    binaryFormatter.Serialize(memoryStream, value);
                }
                catch
                {
                }
            }
            th.Internal._serialized_principal = Thread.ByteArrayToRootDomain(memoryStream.ToArray());
        }
References System.Security.Principal.GenericIdentity.AuthenticationType, System.Security.Principal.IIdentity.AuthenticationType, System.Threading.Thread.ByteArrayToRootDomain(), System.IO.BinaryWriter.Flush(), System.Security.Principal.GenericPrincipal.Identity, System.Security.Principal.GenericIdentity.Name, System.Security.Principal.IIdentity.Name, System.Security.Principal.GenericPrincipal.Roles, System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(), System.text, System.IO.MemoryStream.ToArray(), System.value, System.IO.BinaryWriter.Write(), and System.IO.MemoryStream.WriteByte().