Terraria Decompiled: Terraria.GameContent.Events.ScreenObstruction.Draw
Draw()
static void Terraria.GameContent.Events.ScreenObstruction.Draw (SpriteBatch spriteBatch) inline static
Definition at line 43 of file ScreenObstruction.cs.
        {
            if (ScreenObstruction.screenObstruction == 0f)
            {
                return;
            }
            Color color = Color.Black * ScreenObstruction.screenObstruction;
            int num = TextureAssets.Extra[49].Width();
            int num2 = 10;
            Rectangle rect = Main.SceneMetrics.PerspectivePlayer.getRect();
            rect.Inflate((num - rect.Width) / 2, (num - rect.Height) / 2 + num2 / 2);
            rect.Offset(-(int)Main.screenPosition.X, -(int)Main.screenPosition.Y + (int)Main.player[Main.myPlayer].gfxOffY - num2);
            Rectangle rectangle = Rectangle.Union(new Rectangle(0, 0, 1, 1), new Rectangle(rect.Right - 1, rect.Top - 1, 1, 1));
            Rectangle rectangle2 = Rectangle.Union(new Rectangle(Main.screenWidth - 1, 0, 1, 1), new Rectangle(rect.Right, rect.Bottom - 1, 1, 1));
            Rectangle rectangle3 = Rectangle.Union(new Rectangle(Main.screenWidth - 1, Main.screenHeight - 1, 1, 1), new Rectangle(rect.Left, rect.Bottom, 1, 1));
            Rectangle rectangle4 = Rectangle.Union(new Rectangle(0, Main.screenHeight - 1, 1, 1), new Rectangle(rect.Left - 1, rect.Top, 1, 1));
            spriteBatch.Draw(TextureAssets.MagicPixel.Value, rectangle, new Rectangle?(new Rectangle(0, 0, 1, 1)), color);
            spriteBatch.Draw(TextureAssets.MagicPixel.Value, rectangle2, new Rectangle?(new Rectangle(0, 0, 1, 1)), color);
            spriteBatch.Draw(TextureAssets.MagicPixel.Value, rectangle3, new Rectangle?(new Rectangle(0, 0, 1, 1)), color);
            spriteBatch.Draw(TextureAssets.MagicPixel.Value, rectangle4, new Rectangle?(new Rectangle(0, 0, 1, 1)), color);
            spriteBatch.Draw(TextureAssets.Extra[49].Value, rect, color);
        }
References Microsoft.Xna.Framework.Rectangle.Bottom, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.GameContent.TextureAssets.Extra, Terraria.Player.getRect(), Terraria.Player.gfxOffY, Microsoft.Xna.Framework.Rectangle.Height, Microsoft.Xna.Framework.Rectangle.Inflate(), Microsoft.Xna.Framework.Rectangle.Left, Terraria.GameContent.TextureAssets.MagicPixel, Terraria.Main.myPlayer, Microsoft.Xna.Framework.Rectangle.Offset(), Terraria.SceneMetrics.PerspectivePlayer, Terraria.Main.player, Microsoft.Xna.Framework.Rectangle.Right, Terraria.Main.SceneMetrics, Terraria.Main.screenHeight, Terraria.GameContent.Events.ScreenObstruction.screenObstruction, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Microsoft.Xna.Framework.Rectangle.Top, Microsoft.Xna.Framework.Rectangle.Union(), ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Rectangle.Width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.