Terraria Decompiled: Terraria.GameContent.Creative.CreativePowers.ASharedSliderPower.DeserializeNetMessage
DeserializeNetMessage()
void Terraria.GameContent.Creative.CreativePowers.ASharedSliderPower.DeserializeNetMessage (BinaryReader reader, int userId) inline
Implements Terraria.GameContent.Creative.ICreativePower.
Definition at line 1049 of file CreativePowers.cs.
            {
                float num = reader.ReadSingle();
                if (Main.netMode == 2 && !CreativePowersHelper.IsAvailableForPlayer(this, userId))
                {
                    return;
                }
                this._sliderCurrentValueCache = num;
                this.UpdateInfoFromSliderValueCache();
                if (Main.netMode == 2)
                {
                    NetPacket netPacket = NetCreativePowersModule.PreparePacket(this.PowerId, 4);
                    netPacket.Writer.Write(num);
                    NetManager.Instance.Broadcast(netPacket, -1);
                }
            }
References Terraria.Net.NetManager.Broadcast(), Terraria.Net.NetManager.Instance, Terraria.GameContent.Creative.CreativePowersHelper.IsAvailableForPlayer(), Terraria.Main.netMode, Terraria.GameContent.Creative.CreativePowers.ASharedSliderPower.PowerId, Terraria.GameContent.NetModules.NetCreativePowersModule.PreparePacket(), System.IO.BinaryReader.ReadSingle(), Terraria.GameContent.Creative.CreativePowers.ASharedSliderPower.UpdateInfoFromSliderValueCache(), System.IO.BinaryWriter.Write(), and Terraria.Net.NetPacket.Writer.