Terraria Decompiled: Terraria.GameContent.SpelunkerProjectileHelper.CheckSpot
CheckSpot()
void Terraria.GameContent.SpelunkerProjectileHelper.CheckSpot (Vector2 Center) inline private
Definition at line 34 of file SpelunkerProjectileHelper.cs.
        {
            int num = (int)Center.X / 16;
            int num2 = (int)Center.Y / 16;
            int num3 = Utils.Clamp<int>(num - 30, this._clampBox.Left, this._clampBox.Right);
            int num4 = Utils.Clamp<int>(num + 30, this._clampBox.Left, this._clampBox.Right);
            int num5 = Utils.Clamp<int>(num2 - 30, this._clampBox.Top, this._clampBox.Bottom);
            int num6 = Utils.Clamp<int>(num2 + 30, this._clampBox.Top, this._clampBox.Bottom);
            Point point = default(Point);
            Vector2 vector = default(Vector2);
            for (int i = num3; i <= num4; i++)
            {
                for (int j = num5; j <= num6; j++)
                {
                    Tile tile = Main.tile[i, j];
                    if (tile != null && tile.active() && Main.IsTileSpelunkable(tile))
                    {
                        Vector2 vector2 = new Vector2((float)(num - i), (float)(num2 - j));
                        if (vector2.Length() <= 30f)
{
                            point.X = i;
                            point.Y = j;
                            if (this._tilesChecked.Add(point) && Main.rand.Next(4) == 0)
{
                                vector.X = (float)(i * 16);
                                vector.Y = (float)(j * 16);
                                Dust dust = Dust.NewDustDirect(vector, 16, 16, 204, 0f, 0f, 150, default(Color), 0.3f);
                                dust.fadeIn = 0.75f;
                                dust.velocity *= 0.1f;
                                dust.noLight = true;
                            }
                        }
                    }
                }
            }
        }
References Terraria.GameContent.SpelunkerProjectileHelper._clampBox, Terraria.GameContent.SpelunkerProjectileHelper._tilesChecked, Terraria.Tile.active(), Microsoft.Xna.Framework.Rectangle.Bottom, Terraria.Utils.Clamp(), int, Terraria.Main.IsTileSpelunkable(), Microsoft.Xna.Framework.Rectangle.Left, Microsoft.Xna.Framework.Vector2.Length(), Terraria.Dust.NewDustDirect(), Terraria.Main.rand, Microsoft.Xna.Framework.Rectangle.Right, Terraria.Main.tile, and Microsoft.Xna.Framework.Rectangle.Top.
Referenced by Terraria.GameContent.SpelunkerProjectileHelper.AddSpotToCheck().