Terraria Decompiled: System.Security.Policy.Hash.ToString
ToString()
override string System.Security.Policy.Hash.ToString () inline
Definition at line 99 of file Hash.cs.
        {
            SecurityElement securityElement = new SecurityElement(base.GetType().FullName);
            securityElement.AddAttribute("version", "1");
            StringBuilder stringBuilder = new StringBuilder();
            byte[] array = this.GetData();
            for (int i = 0; i < array.Length; i++)
            {
                stringBuilder.Append(array[i].ToString("X2"));
            }
            securityElement.AddChild(new SecurityElement("RawData", stringBuilder.ToString()));
            return securityElement.ToString();
        }
References System.Security.SecurityElement.AddAttribute(), System.Security.SecurityElement.AddChild(), System.Text.StringBuilder.Append(), System.array, System.Security.Policy.Hash.GetData(), System.Security.Policy.Hash.ToString(), System.Security.SecurityElement.ToString(), and System.Text.StringBuilder.ToString().
Referenced by System.Security.Policy.Hash.ToString().