Terraria Decompiled: System.Security.Policy.Hash.GenerateHash
GenerateHash()
byte[] System.Security.Policy.Hash.GenerateHash (HashAlgorithm hashAlg) inline
Definition at line 79 of file Hash.cs.
        {
            if (hashAlg == null)
            {
                throw new ArgumentNullException("hashAlg");
            }
            return hashAlg.ComputeHash(this.GetData());
        }
References System.Security.Cryptography.HashAlgorithm.ComputeHash(), and System.Security.Policy.Hash.GetData().
Referenced by System.Security.Policy.HashMembershipCondition.Check().