Terraria Decompiled: System.Security.Policy.Hash.GetData
GetData()
byte[] System.Security.Policy.Hash.GetData () inline private
Definition at line 115 of file Hash.cs.
        {
            if (this.assembly == null && this.data == null)
            {
                throw new SecurityException(Locale.GetText("No assembly data."));
            }
            if (this.data == null)
            {
                FileStream fileStream = new FileStream(this.assembly.Location, FileMode.Open, FileAccess.Read);
                this.data = new byte[fileStream.Length];
                fileStream.Read(this.data, 0, (int)fileStream.Length);
            }
            return this.data;
        }
References System.Security.Policy.Hash.assembly, System.Security.Policy.Hash.data, Locale.GetText(), System.IO.FileStream.Length, System.Reflection.Assembly.Location, and System.IO.FileStream.Read().
Referenced by System.Security.Policy.Hash.GenerateHash(), System.Security.Policy.Hash.GetObjectData(), and System.Security.Policy.Hash.ToString().