Terraria Decompiled: ReLogic.Content.RejectedAssetCollection.TryGetRejections
TryGetRejections()
bool ReLogic.Content.RejectedAssetCollection.TryGetRejections (List< string > rejectionReasons) inline
Definition at line 28 of file RejectedAssetCollection.cs.
        {
            foreach (KeyValuePair<string, IRejectionReason> keyValuePair in this._rejectedAssetsAndReasons)
            {
                rejectionReasons.Add(keyValuePair.Value.GetReason());
            }
            return this._rejectedAssetsAndReasons.Count > 0;
        }
References ReLogic.Content.RejectedAssetCollection._rejectedAssetsAndReasons, and System.Collections.Generic.KeyValuePair< TKey, TValue >.Value.
Referenced by ReLogic.Content.Sources.FileSystemContentSource.TryGetRejections(), ReLogic.Content.Sources.XnaContentSource.TryGetRejections(), ReLogic.Content.Sources.XnaDirectContentSource.TryGetRejections(), and ReLogic.Content.Sources.ZipContentSource.TryGetRejections().