Terraria Decompiled: Mono.Security.ASN1Convert.ToDateTime
ToDateTime()
static DateTime Mono.Security.ASN1Convert.ToDateTime (ASN1 time) inline static
Definition at line 134 of file ASN1Convert.cs.
        {
            if (time == null)
            {
                throw new ArgumentNullException("time");
            }
            string text = Encoding.ASCII.GetString(time.Value);
            string text2 = null;
            switch (text.Length)
            {
            case 11:
                text2 = "yyMMddHHmmZ";
                break;
            case 13:
                if (Convert.ToInt16(text.Substring(0, 2), CultureInfo.InvariantCulture) >= 50)
                {
                    text = "19" + text;
                }
                else
                {
                    text = "20" + text;
                }
                text2 = "yyyyMMddHHmmssZ";
                break;
            case 15:
                text2 = "yyyyMMddHHmmssZ";
                break;
            case 17:
            {
                string text3 = ((Convert.ToInt16(text.Substring(0, 2), CultureInfo.InvariantCulture) >= 50) ? "19" : "20");
                char c = ((text[12] == '+') ? '-' : '+');
                text = string.Format("{0}{1}{2}{3}{4}:{5}{6}", new object[]
                {
                    text3,
                    text.Substring(0, 12),
                    c,
                    text[13],
                    text[14],
                    text[15],
                    text[16]
                });
                text2 = "yyyyMMddHHmmsszzz";
                break;
            }
            }
            return DateTime.ParseExact(text, text2, CultureInfo.InvariantCulture, DateTimeStyles.AdjustToUniversal);
        }
References System.Text.Encoding.ASCII, System.Text.Encoding.GetString(), System.Globalization.CultureInfo.InvariantCulture, System.DateTime.ParseExact(), System.text, System.Convert.ToInt16(), and Mono.Security.ASN1.Value.