Terraria Decompiled: Newtonsoft.Json.Serialization.DefaultContractResolver.CreateDynamicContract
CreateDynamicContract()
virtual JsonDynamicContract Newtonsoft.Json.Serialization.DefaultContractResolver.CreateDynamicContract (Type objectType) inline protected virtual
Definition at line 788 of file DefaultContractResolver.cs.
        {
            JsonDynamicContract jsonDynamicContract = new JsonDynamicContract(objectType);
            this.InitializeContract(jsonDynamicContract);
            JsonContainerAttribute attribute = JsonTypeReflector.GetAttribute<JsonContainerAttribute>(objectType);
            if (((attribute != null) ? attribute.NamingStrategyType : null) != null)
            {
                NamingStrategy namingStrategy = JsonTypeReflector.GetContainerNamingStrategy(attribute);
                jsonDynamicContract.PropertyNameResolver = (string s) => namingStrategy.GetDictionaryKey(s);
            }
            else
            {
                jsonDynamicContract.PropertyNameResolver = new Func<string, string>(this.ResolveDictionaryKey);
            }
            jsonDynamicContract.Properties.AddRange(this.CreateProperties(objectType, MemberSerialization.OptOut));
            return jsonDynamicContract;
        }
References Newtonsoft.Json.Serialization.DefaultContractResolver.CreateProperties(), Newtonsoft.Json.Serialization.JsonTypeReflector.GetContainerNamingStrategy(), Newtonsoft.Json.Serialization.NamingStrategy.GetDictionaryKey(), Newtonsoft.Json.Serialization.DefaultContractResolver.InitializeContract(), Newtonsoft.Json.JsonContainerAttribute.NamingStrategyType, Newtonsoft.Json.Serialization.JsonDynamicContract.Properties, Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveDictionaryKey(), and System.s.
Referenced by Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract().