Terraria Decompiled: Newtonsoft.Json.Serialization.DefaultContractResolver.IsValidCallback
IsValidCallback()
static bool Newtonsoft.Json.Serialization.DefaultContractResolver.IsValidCallback (MethodInfo method, ParameterInfo[] parameters, Type attributeType, MethodInfo currentCallback, ref Type prevAttributeType) inline static private
Definition at line 887 of file DefaultContractResolver.cs.
        {
            if (!method.IsDefined(attributeType, false))
            {
                return false;
            }
            if (currentCallback != null)
            {
                throw new JsonException("Invalid attribute. Both '{0}' and '{1}' in type '{2}' have '{3}'.".FormatWith(CultureInfo.InvariantCulture, method, currentCallback, DefaultContractResolver.GetClrTypeFullName(method.DeclaringType), attributeType));
            }
            if (prevAttributeType != null)
            {
                throw new JsonException("Invalid Callback. Method '{3}' in type '{2}' has both '{0}' and '{1}'.".FormatWith(CultureInfo.InvariantCulture, prevAttributeType, attributeType, DefaultContractResolver.GetClrTypeFullName(method.DeclaringType), method));
            }
            if (method.IsVirtual)
            {
                throw new JsonException("Virtual Method '{0}' of type '{1}' cannot be marked with '{2}' attribute.".FormatWith(CultureInfo.InvariantCulture, method, DefaultContractResolver.GetClrTypeFullName(method.DeclaringType), attributeType));
            }
            if (method.ReturnType != typeof(void))
            {
                throw new JsonException("Serialization Callback '{1}' in type '{0}' must return void.".FormatWith(CultureInfo.InvariantCulture, DefaultContractResolver.GetClrTypeFullName(method.DeclaringType), method));
            }
            if (attributeType == typeof(OnErrorAttribute))
            {
                if (parameters == null || parameters.Length != 2 || parameters[0].ParameterType != typeof(StreamingContext) || parameters[1].ParameterType != typeof(ErrorContext))
                {
                    throw new JsonException("Serialization Error Callback '{1}' in type '{0}' must have two parameters of type '{2}' and '{3}'.".FormatWith(CultureInfo.InvariantCulture, DefaultContractResolver.GetClrTypeFullName(method.DeclaringType), method, typeof(StreamingContext), typeof(ErrorContext)));
                }
            }
            else if (parameters == null || parameters.Length != 1 || parameters[0].ParameterType != typeof(StreamingContext))
            {
                throw new JsonException("Serialization Callback '{1}' in type '{0}' must have a single parameter of type '{2}'.".FormatWith(CultureInfo.InvariantCulture, DefaultContractResolver.GetClrTypeFullName(method.DeclaringType), method, typeof(StreamingContext)));
            }
            prevAttributeType = attributeType;
            return true;
        }
References System.Runtime.InteropServices._MethodInfo.DeclaringType, Newtonsoft.Json.Serialization.DefaultContractResolver.GetClrTypeFullName(), System.Globalization.CultureInfo.InvariantCulture, System.Runtime.InteropServices._MethodInfo.IsDefined(), System.Reflection.MethodBase.IsVirtual, System.Reflection.ParameterInfo.ParameterType, and System.Reflection.MethodInfo.ReturnType.
Referenced by Newtonsoft.Json.Serialization.DefaultContractResolver.GetCallbackMethodsForType().