Terraria Decompiled: Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveDictionaryKey
ResolveDictionaryKey()
virtual string Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveDictionaryKey (string dictionaryKey) inline protected virtual
Definition at line 1197 of file DefaultContractResolver.cs.
        {
            if (this.NamingStrategy != null)
            {
                return this.NamingStrategy.GetDictionaryKey(dictionaryKey);
            }
            return this.ResolvePropertyName(dictionaryKey);
        }
References Newtonsoft.Json.Serialization.NamingStrategy.GetDictionaryKey(), and Newtonsoft.Json.Serialization.DefaultContractResolver.ResolvePropertyName().
Referenced by Newtonsoft.Json.Serialization.DefaultContractResolver.CreateDictionaryContract(), and Newtonsoft.Json.Serialization.DefaultContractResolver.CreateDynamicContract().