Terraria Decompiled: Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract
CreateObjectContract()
virtual JsonObjectContract Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract (Type objectType) inline protected virtual
Definition at line 224 of file DefaultContractResolver.cs.
        {
            JsonObjectContract jsonObjectContract = new JsonObjectContract(objectType);
            this.InitializeContract(jsonObjectContract);
            bool ignoreSerializableAttribute = this.IgnoreSerializableAttribute;
            jsonObjectContract.MemberSerialization = JsonTypeReflector.GetObjectMemberSerialization(jsonObjectContract.NonNullableUnderlyingType, ignoreSerializableAttribute);
            jsonObjectContract.Properties.AddRange(this.CreateProperties(jsonObjectContract.NonNullableUnderlyingType, jsonObjectContract.MemberSerialization));
            Func<string, string> func = null;
            JsonObjectAttribute cachedAttribute = JsonTypeReflector.GetCachedAttribute<JsonObjectAttribute>(jsonObjectContract.NonNullableUnderlyingType);
            if (cachedAttribute != null)
            {
                jsonObjectContract.ItemRequired = cachedAttribute._itemRequired;
                if (cachedAttribute.NamingStrategyType != null)
                {
                    NamingStrategy namingStrategy = JsonTypeReflector.GetContainerNamingStrategy(cachedAttribute);
                    func = (string s) => namingStrategy.GetDictionaryKey(s);
                }
            }
            if (func == null)
            {
                func = new Func<string, string>(this.ResolveExtensionDataName);
            }
            jsonObjectContract.ExtensionDataNameResolver = func;
            if (jsonObjectContract.IsInstantiable)
            {
                ConstructorInfo attributeConstructor = this.GetAttributeConstructor(jsonObjectContract.NonNullableUnderlyingType);
                if (attributeConstructor != null)
                {
                    jsonObjectContract.OverrideCreator = JsonTypeReflector.ReflectionDelegateFactory.CreateParameterizedConstructor(attributeConstructor);
                    jsonObjectContract.CreatorParameters.AddRange(this.CreateConstructorParameters(attributeConstructor, jsonObjectContract.Properties));
                }
                else if (jsonObjectContract.MemberSerialization == MemberSerialization.Fields)
                {
                    if (JsonTypeReflector.FullyTrusted)
                    {
                        jsonObjectContract.DefaultCreator = new Func<object>(jsonObjectContract.GetUninitializedObject);
                    }
                }
                else if (jsonObjectContract.DefaultCreator == null || jsonObjectContract.DefaultCreatorNonPublic)
                {
                    ConstructorInfo parameterizedConstructor = this.GetParameterizedConstructor(jsonObjectContract.NonNullableUnderlyingType);
                    if (parameterizedConstructor != null)
                    {
                        jsonObjectContract.ParameterizedCreator = JsonTypeReflector.ReflectionDelegateFactory.CreateParameterizedConstructor(parameterizedConstructor);
                        jsonObjectContract.CreatorParameters.AddRange(this.CreateConstructorParameters(parameterizedConstructor, jsonObjectContract.Properties));
                    }
                }
                else if (jsonObjectContract.NonNullableUnderlyingType.IsValueType())
                {
                    ConstructorInfo immutableConstructor = this.GetImmutableConstructor(jsonObjectContract.NonNullableUnderlyingType, jsonObjectContract.Properties);
                    if (immutableConstructor != null)
                    {
                        jsonObjectContract.OverrideCreator = JsonTypeReflector.ReflectionDelegateFactory.CreateParameterizedConstructor(immutableConstructor);
                        jsonObjectContract.CreatorParameters.AddRange(this.CreateConstructorParameters(immutableConstructor, jsonObjectContract.Properties));
                    }
                }
            }
            MemberInfo extensionDataMemberForType = this.GetExtensionDataMemberForType(jsonObjectContract.NonNullableUnderlyingType);
            if (extensionDataMemberForType != null)
            {
                DefaultContractResolver.SetExtensionDataDelegates(jsonObjectContract, extensionDataMemberForType);
            }
            return jsonObjectContract;
        }
References Newtonsoft.Json.JsonObjectAttribute._itemRequired, Newtonsoft.Json.Serialization.DefaultContractResolver.CreateConstructorParameters(), Newtonsoft.Json.Utilities.ReflectionDelegateFactory.CreateParameterizedConstructor(), Newtonsoft.Json.Serialization.DefaultContractResolver.CreateProperties(), Newtonsoft.Json.Serialization.JsonObjectContract.CreatorParameters, Newtonsoft.Json.Serialization.JsonContract.DefaultCreator, Newtonsoft.Json.Serialization.JsonContract.DefaultCreatorNonPublic, Newtonsoft.Json.Serialization.JsonTypeReflector.FullyTrusted, Newtonsoft.Json.Serialization.DefaultContractResolver.GetAttributeConstructor(), Newtonsoft.Json.Serialization.JsonTypeReflector.GetContainerNamingStrategy(), Newtonsoft.Json.Serialization.NamingStrategy.GetDictionaryKey(), Newtonsoft.Json.Serialization.DefaultContractResolver.GetExtensionDataMemberForType(), Newtonsoft.Json.Serialization.DefaultContractResolver.GetImmutableConstructor(), Newtonsoft.Json.Serialization.JsonTypeReflector.GetObjectMemberSerialization(), Newtonsoft.Json.Serialization.DefaultContractResolver.GetParameterizedConstructor(), Newtonsoft.Json.Serialization.JsonObjectContract.GetUninitializedObject(), Newtonsoft.Json.Serialization.DefaultContractResolver.IgnoreSerializableAttribute, Newtonsoft.Json.Serialization.DefaultContractResolver.InitializeContract(), Newtonsoft.Json.Serialization.JsonContract.IsInstantiable, System.Type.IsValueType, Newtonsoft.Json.Serialization.JsonObjectContract.MemberSerialization, Newtonsoft.Json.JsonContainerAttribute.NamingStrategyType, Newtonsoft.Json.Serialization.JsonContract.NonNullableUnderlyingType, Newtonsoft.Json.Serialization.JsonObjectContract.Properties, Newtonsoft.Json.Serialization.JsonTypeReflector.ReflectionDelegateFactory, Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveExtensionDataName(), System.s, and Newtonsoft.Json.Serialization.DefaultContractResolver.SetExtensionDataDelegates().
Referenced by Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract().