Terraria Decompiled: Newtonsoft.Json.Serialization.DefaultContractResolver.CreateISerializableContract
CreateISerializableContract()
virtual JsonISerializableContract Newtonsoft.Json.Serialization.DefaultContractResolver.CreateISerializableContract (Type objectType) inline protected virtual
Definition at line 770 of file DefaultContractResolver.cs.
        {
            JsonISerializableContract jsonISerializableContract = new JsonISerializableContract(objectType);
            this.InitializeContract(jsonISerializableContract);
            ConstructorInfo constructor = jsonISerializableContract.NonNullableUnderlyingType.GetConstructor(52, null, new Type[]
            {
                typeof(SerializationInfo),
                typeof(StreamingContext)
            }, null);
            if (constructor != null)
            {
                ObjectConstructor<object> objectConstructor = JsonTypeReflector.ReflectionDelegateFactory.CreateParameterizedConstructor(constructor);
                jsonISerializableContract.ISerializableCreator = objectConstructor;
            }
            return jsonISerializableContract;
        }
References Newtonsoft.Json.Utilities.ReflectionDelegateFactory.CreateParameterizedConstructor(), System.Type.GetConstructor(), Newtonsoft.Json.Serialization.DefaultContractResolver.InitializeContract(), Newtonsoft.Json.Serialization.JsonContract.NonNullableUnderlyingType, and Newtonsoft.Json.Serialization.JsonTypeReflector.ReflectionDelegateFactory.
Referenced by Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract().