Terraria Decompiled: Newtonsoft.Json.Serialization.DefaultContractResolver.CreateArrayContract
CreateArrayContract()
virtual JsonArrayContract Newtonsoft.Json.Serialization.DefaultContractResolver.CreateArrayContract (Type objectType) inline protected virtual
Definition at line 727 of file DefaultContractResolver.cs.
        {
            JsonArrayContract jsonArrayContract = new JsonArrayContract(objectType);
            this.InitializeContract(jsonArrayContract);
            ConstructorInfo attributeConstructor = this.GetAttributeConstructor(jsonArrayContract.NonNullableUnderlyingType);
            if (attributeConstructor != null)
            {
                ParameterInfo[] parameters = attributeConstructor.GetParameters();
                Type type = ((jsonArrayContract.CollectionItemType != null) ? typeof(IEnumerable).MakeGenericType(new Type[] { jsonArrayContract.CollectionItemType }) : typeof(IEnumerable));
                if (parameters.Length == 0)
                {
                    jsonArrayContract.HasParameterizedCreator = false;
                }
                else
                {
                    if (parameters.Length != 1 || !type.IsAssignableFrom(parameters[0].ParameterType))
                    {
                        throw new JsonException("Constructor for '{0}' must have no parameters or a single parameter that implements '{1}'.".FormatWith(CultureInfo.InvariantCulture, jsonArrayContract.UnderlyingType, type));
                    }
                    jsonArrayContract.HasParameterizedCreator = true;
                }
                jsonArrayContract.OverrideCreator = JsonTypeReflector.ReflectionDelegateFactory.CreateParameterizedConstructor(attributeConstructor);
            }
            return jsonArrayContract;
        }
References Newtonsoft.Json.Utilities.ReflectionDelegateFactory.CreateParameterizedConstructor(), Newtonsoft.Json.Serialization.DefaultContractResolver.GetAttributeConstructor(), System.Reflection.MethodBase.GetParameters(), Newtonsoft.Json.Serialization.DefaultContractResolver.InitializeContract(), System.Globalization.CultureInfo.InvariantCulture, System.Type.IsAssignableFrom(), Newtonsoft.Json.Serialization.JsonContract.NonNullableUnderlyingType, System.Reflection.ParameterInfo.ParameterType, Newtonsoft.Json.Serialization.JsonTypeReflector.ReflectionDelegateFactory, and Newtonsoft.Json.Serialization.JsonContract.UnderlyingType.
Referenced by Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract().