Terraria Decompiled: Newtonsoft.Json.Serialization.DefaultContractResolver.GetAttributeConstructor
GetAttributeConstructor()
ConstructorInfo Newtonsoft.Json.Serialization.DefaultContractResolver.GetAttributeConstructor (Type objectType) inline private
Definition at line 391 of file DefaultContractResolver.cs.
        {
            IEnumerator<ConstructorInfo> enumerator = Enumerable.Where<ConstructorInfo>(objectType.GetConstructors(52), (ConstructorInfo c) => c.IsDefined(typeof(JsonConstructorAttribute), true)).GetEnumerator();
            if (enumerator.MoveNext())
            {
                ConstructorInfo constructorInfo = enumerator.Current;
                if (enumerator.MoveNext())
                {
                    throw new JsonException("Multiple constructors with the JsonConstructorAttribute.");
                }
                return constructorInfo;
            }
            else
            {
                if (objectType == typeof(Version))
                {
                    return objectType.GetConstructor(new Type[]
                    {
                        typeof(int),
                        typeof(int),
                        typeof(int),
                        typeof(int)
                    });
                }
                return null;
            }
        }
References System.Collections.Generic.IEnumerator< out T >.Current, System.Type.GetConstructor(), System.Type.GetConstructors(), System.Reflection.MemberInfo.IsDefined(), and System.Collections.IEnumerator.MoveNext().
Referenced by Newtonsoft.Json.Serialization.DefaultContractResolver.CreateArrayContract(), Newtonsoft.Json.Serialization.DefaultContractResolver.CreateDictionaryContract(), and Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract().