Terraria Decompiled: Newtonsoft.Json.Serialization.DefaultContractResolver.CreateProperty
CreateProperty()
virtual JsonProperty Newtonsoft.Json.Serialization.DefaultContractResolver.CreateProperty (MemberInfo member, MemberSerialization memberSerialization) inline protected virtual
Reimplemented in Terraria.Utilities.EasyDeserializationJsonContractResolver.
Definition at line 990 of file DefaultContractResolver.cs.
        {
            JsonProperty jsonProperty = new JsonProperty();
            jsonProperty.PropertyType = ReflectionUtils.GetMemberUnderlyingType(member);
            jsonProperty.DeclaringType = member.DeclaringType;
            jsonProperty.ValueProvider = this.CreateMemberValueProvider(member);
            jsonProperty.AttributeProvider = new ReflectionAttributeProvider(member);
            bool flag;
            this.SetPropertySettingsFromAttributes(jsonProperty, member, member.Name, member.DeclaringType, memberSerialization, out flag);
            if (memberSerialization != MemberSerialization.Fields)
            {
                jsonProperty.Readable = ReflectionUtils.CanReadMemberValue(member, flag);
                jsonProperty.Writable = ReflectionUtils.CanSetMemberValue(member, flag, jsonProperty.HasMemberAttribute);
            }
            else
            {
                jsonProperty.Readable = true;
                jsonProperty.Writable = true;
            }
            jsonProperty.ShouldSerialize = this.CreateShouldSerializeTest(member);
            this.SetIsSpecifiedActions(jsonProperty, member, flag);
            return jsonProperty;
        }
References Newtonsoft.Json.Utilities.ReflectionUtils.CanReadMemberValue(), Newtonsoft.Json.Utilities.ReflectionUtils.CanSetMemberValue(), Newtonsoft.Json.Serialization.DefaultContractResolver.CreateMemberValueProvider(), Newtonsoft.Json.Serialization.DefaultContractResolver.CreateShouldSerializeTest(), System.Reflection.MemberInfo.DeclaringType, Newtonsoft.Json.Utilities.ReflectionUtils.GetMemberUnderlyingType(), Newtonsoft.Json.Serialization.JsonProperty.HasMemberAttribute, System.Reflection.MemberInfo.Name, Newtonsoft.Json.Serialization.DefaultContractResolver.SetIsSpecifiedActions(), and Newtonsoft.Json.Serialization.DefaultContractResolver.SetPropertySettingsFromAttributes().
Referenced by Newtonsoft.Json.Serialization.DefaultContractResolver.CreateProperties().