Terraria Decompiled: Newtonsoft.Json.Serialization.DefaultContractResolver.GetCallbackMethodsForType
GetCallbackMethodsForType()
void Newtonsoft.Json.Serialization.DefaultContractResolver.GetCallbackMethodsForType (Type type, out List< SerializationCallback > onSerializing, out List< SerializationCallback > onSerialized, out List< SerializationCallback > onDeserializing, out List< SerializationCallback > onDeserialized, out List< SerializationErrorCallback > onError) inline private
Definition at line 606 of file DefaultContractResolver.cs.
        {
            onSerializing = null;
            onSerialized = null;
            onDeserializing = null;
            onDeserialized = null;
            onError = null;
            foreach (Type type2 in this.GetClassHierarchyForType(type))
            {
                MethodInfo methodInfo = null;
                MethodInfo methodInfo2 = null;
                MethodInfo methodInfo3 = null;
                MethodInfo methodInfo4 = null;
                MethodInfo methodInfo5 = null;
                bool flag = DefaultContractResolver.ShouldSkipSerializing(type2);
                bool flag2 = DefaultContractResolver.ShouldSkipDeserialized(type2);
                foreach (MethodInfo methodInfo6 in type2.GetMethods(54))
                {
                    if (!methodInfo6.ContainsGenericParameters)
                    {
                        Type type3 = null;
                        ParameterInfo[] parameters = methodInfo6.GetParameters();
                        if (!flag && DefaultContractResolver.IsValidCallback(methodInfo6, parameters, typeof(OnSerializingAttribute), methodInfo, ref type3))
{
                            onSerializing = onSerializing ?? new List<SerializationCallback>();
                            onSerializing.Add(JsonContract.CreateSerializationCallback(methodInfo6));
                            methodInfo = methodInfo6;
                        }
                        if (DefaultContractResolver.IsValidCallback(methodInfo6, parameters, typeof(OnSerializedAttribute), methodInfo2, ref type3))
{
                            onSerialized = onSerialized ?? new List<SerializationCallback>();
                            onSerialized.Add(JsonContract.CreateSerializationCallback(methodInfo6));
                            methodInfo2 = methodInfo6;
                        }
                        if (DefaultContractResolver.IsValidCallback(methodInfo6, parameters, typeof(OnDeserializingAttribute), methodInfo3, ref type3))
{
                            onDeserializing = onDeserializing ?? new List<SerializationCallback>();
                            onDeserializing.Add(JsonContract.CreateSerializationCallback(methodInfo6));
                            methodInfo3 = methodInfo6;
                        }
                        if (!flag2 && DefaultContractResolver.IsValidCallback(methodInfo6, parameters, typeof(OnDeserializedAttribute), methodInfo4, ref type3))
{
                            onDeserialized = onDeserialized ?? new List<SerializationCallback>();
                            onDeserialized.Add(JsonContract.CreateSerializationCallback(methodInfo6));
                            methodInfo4 = methodInfo6;
                        }
                        if (DefaultContractResolver.IsValidCallback(methodInfo6, parameters, typeof(OnErrorAttribute), methodInfo5, ref type3))
{
                            onError = onError ?? new List<SerializationErrorCallback>();
                            onError.Add(JsonContract.CreateSerializationErrorCallback(methodInfo6));
                            methodInfo5 = methodInfo6;
                        }
                    }
                }
            }
        }
References System.Reflection.MethodBase.ContainsGenericParameters, Newtonsoft.Json.Serialization.JsonContract.CreateSerializationCallback(), Newtonsoft.Json.Serialization.JsonContract.CreateSerializationErrorCallback(), Newtonsoft.Json.Serialization.DefaultContractResolver.GetClassHierarchyForType(), System.Type.GetMethods(), System.Reflection.MethodBase.GetParameters(), Newtonsoft.Json.Serialization.DefaultContractResolver.IsValidCallback(), Newtonsoft.Json.Serialization.DefaultContractResolver.ShouldSkipDeserialized(), and Newtonsoft.Json.Serialization.DefaultContractResolver.ShouldSkipSerializing().
Referenced by Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveCallbackMethods().