Terraria Decompiled: Newtonsoft.Json.Serialization.DefaultContractResolver.CreateDictionaryContract
CreateDictionaryContract()
virtual JsonDictionaryContract Newtonsoft.Json.Serialization.DefaultContractResolver.CreateDictionaryContract (Type objectType) inline protected virtual
Definition at line 690 of file DefaultContractResolver.cs.
        {
            JsonDictionaryContract jsonDictionaryContract = new JsonDictionaryContract(objectType);
            this.InitializeContract(jsonDictionaryContract);
            JsonContainerAttribute attribute = JsonTypeReflector.GetAttribute<JsonContainerAttribute>(objectType);
            if (((attribute != null) ? attribute.NamingStrategyType : null) != null)
            {
                NamingStrategy namingStrategy = JsonTypeReflector.GetContainerNamingStrategy(attribute);
                jsonDictionaryContract.DictionaryKeyResolver = (string s) => namingStrategy.GetDictionaryKey(s);
            }
            else
            {
                jsonDictionaryContract.DictionaryKeyResolver = new Func<string, string>(this.ResolveDictionaryKey);
            }
            ConstructorInfo attributeConstructor = this.GetAttributeConstructor(jsonDictionaryContract.NonNullableUnderlyingType);
            if (attributeConstructor != null)
            {
                ParameterInfo[] parameters = attributeConstructor.GetParameters();
                Type type = ((jsonDictionaryContract.DictionaryKeyType != null && jsonDictionaryContract.DictionaryValueType != null) ? typeof(IEnumerable).MakeGenericType(new Type[] { typeof(KeyValuePair).MakeGenericType(new Type[] { jsonDictionaryContract.DictionaryKeyType, jsonDictionaryContract.DictionaryValueType }) }) : typeof(IDictionary));
                if (parameters.Length == 0)
                {
                    jsonDictionaryContract.HasParameterizedCreator = false;
                }
                else
                {
                    if (parameters.Length != 1 || !type.IsAssignableFrom(parameters[0].ParameterType))
                    {
                        throw new JsonException("Constructor for '{0}' must have no parameters or a single parameter that implements '{1}'.".FormatWith(CultureInfo.InvariantCulture, jsonDictionaryContract.UnderlyingType, type));
                    }
                    jsonDictionaryContract.HasParameterizedCreator = true;
                }
                jsonDictionaryContract.OverrideCreator = JsonTypeReflector.ReflectionDelegateFactory.CreateParameterizedConstructor(attributeConstructor);
            }
            return jsonDictionaryContract;
        }
References Newtonsoft.Json.Utilities.ReflectionDelegateFactory.CreateParameterizedConstructor(), Newtonsoft.Json.Serialization.JsonDictionaryContract.DictionaryKeyType, Newtonsoft.Json.Serialization.DefaultContractResolver.GetAttributeConstructor(), Newtonsoft.Json.Serialization.JsonTypeReflector.GetContainerNamingStrategy(), Newtonsoft.Json.Serialization.NamingStrategy.GetDictionaryKey(), System.Reflection.MethodBase.GetParameters(), Newtonsoft.Json.Serialization.DefaultContractResolver.InitializeContract(), System.Globalization.CultureInfo.InvariantCulture, System.Type.IsAssignableFrom(), System.Type.MakeGenericType(), Newtonsoft.Json.JsonContainerAttribute.NamingStrategyType, Newtonsoft.Json.Serialization.JsonContract.NonNullableUnderlyingType, System.Reflection.ParameterInfo.ParameterType, Newtonsoft.Json.Serialization.JsonTypeReflector.ReflectionDelegateFactory, Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveDictionaryKey(), System.s, and Newtonsoft.Json.Serialization.JsonContract.UnderlyingType.
Referenced by Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract().