Terraria Decompiled: Newtonsoft.Json.Serialization.DefaultContractResolver.InitializeContract
InitializeContract()
void Newtonsoft.Json.Serialization.DefaultContractResolver.InitializeContract (JsonContract contract) inline private
Definition at line 549 of file DefaultContractResolver.cs.
        {
            JsonContainerAttribute cachedAttribute = JsonTypeReflector.GetCachedAttribute<JsonContainerAttribute>(contract.NonNullableUnderlyingType);
            if (cachedAttribute != null)
            {
                contract.IsReference = cachedAttribute._isReference;
            }
            else
            {
                DataContractAttribute dataContractAttribute = JsonTypeReflector.GetDataContractAttribute(contract.NonNullableUnderlyingType);
                if (dataContractAttribute != null && dataContractAttribute.IsReference)
                {
                    contract.IsReference = new bool?(true);
                }
            }
            contract.Converter = this.ResolveContractConverter(contract.NonNullableUnderlyingType);
            contract.InternalConverter = JsonSerializer.GetMatchingConverter(DefaultContractResolver.BuiltInConverters, contract.NonNullableUnderlyingType);
            if (contract.IsInstantiable && (ReflectionUtils.HasDefaultConstructor(contract.CreatedType, true) || contract.CreatedType.IsValueType()))
            {
                contract.DefaultCreator = this.GetDefaultCreator(contract.CreatedType);
                contract.DefaultCreatorNonPublic = !contract.CreatedType.IsValueType() && ReflectionUtils.GetDefaultConstructor(contract.CreatedType) == null;
            }
            this.ResolveCallbackMethods(contract, contract.NonNullableUnderlyingType);
        }
References Newtonsoft.Json.JsonContainerAttribute._isReference, Newtonsoft.Json.Serialization.DefaultContractResolver.BuiltInConverters, Newtonsoft.Json.Serialization.JsonContract.CreatedType, Newtonsoft.Json.Serialization.JsonTypeReflector.GetDataContractAttribute(), Newtonsoft.Json.Utilities.ReflectionUtils.GetDefaultConstructor(), Newtonsoft.Json.Serialization.DefaultContractResolver.GetDefaultCreator(), Newtonsoft.Json.JsonSerializer.GetMatchingConverter(), Newtonsoft.Json.Utilities.ReflectionUtils.HasDefaultConstructor(), Newtonsoft.Json.Serialization.JsonContract.IsInstantiable, System.Type.IsValueType, Newtonsoft.Json.Serialization.JsonContract.NonNullableUnderlyingType, Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveCallbackMethods(), and Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContractConverter().
Referenced by Newtonsoft.Json.Serialization.DefaultContractResolver.CreateArrayContract(), Newtonsoft.Json.Serialization.DefaultContractResolver.CreateDictionaryContract(), Newtonsoft.Json.Serialization.DefaultContractResolver.CreateDynamicContract(), Newtonsoft.Json.Serialization.DefaultContractResolver.CreateISerializableContract(), Newtonsoft.Json.Serialization.DefaultContractResolver.CreateLinqContract(), Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(), Newtonsoft.Json.Serialization.DefaultContractResolver.CreatePrimitiveContract(), and Newtonsoft.Json.Serialization.DefaultContractResolver.CreateStringContract().