Terraria Decompiled: Newtonsoft.Json.Serialization.DefaultContractResolver.SetExtensionDataDelegates
SetExtensionDataDelegates()
static void Newtonsoft.Json.Serialization.DefaultContractResolver.SetExtensionDataDelegates (JsonObjectContract contract, MemberInfo member) inline static private
Definition at line 328 of file DefaultContractResolver.cs.
        {
            JsonExtensionDataAttribute attribute = ReflectionUtils.GetAttribute<JsonExtensionDataAttribute>(member);
            if (attribute == null)
            {
                return;
            }
            Type memberUnderlyingType = ReflectionUtils.GetMemberUnderlyingType(member);
            Type type;
            ReflectionUtils.ImplementsGenericDefinition(memberUnderlyingType, typeof(IDictionary), out type);
            Type type2 = type.GetGenericArguments()[0];
            Type type3 = type.GetGenericArguments()[1];
            Type type4;
            if (ReflectionUtils.IsGenericDefinition(memberUnderlyingType, typeof(IDictionary)))
            {
                type4 = typeof(Dictionary).MakeGenericType(new Type[] { type2, type3 });
            }
            else
            {
                type4 = memberUnderlyingType;
            }
            Func<object, object> getExtensionDataDictionary = JsonTypeReflector.ReflectionDelegateFactory.CreateGet<object>(member);
            if (attribute.ReadData)
            {
                Action<object, object> setExtensionDataDictionary = (ReflectionUtils.CanSetMemberValue(member, true, false) ? JsonTypeReflector.ReflectionDelegateFactory.CreateSet<object>(member) : null);
                Func<object> createExtensionDataDictionary = JsonTypeReflector.ReflectionDelegateFactory.CreateDefaultConstructor<object>(type4);
                MethodInfo method = memberUnderlyingType.GetMethod("Add", new Type[] { type2, type3 });
                MethodCall<object, object> setExtensionDataDictionaryValue = JsonTypeReflector.ReflectionDelegateFactory.CreateMethodCall<object>(method);
                ExtensionDataSetter extensionDataSetter = delegate(object o, string key, object value)
                {
                    object obj = getExtensionDataDictionary.Invoke(o);
                    if (obj == null)
                    {
                        if (setExtensionDataDictionary == null)
{
                            throw new JsonSerializationException("Cannot set value onto extension data member '{0}'. The extension data collection is null and it cannot be set.".FormatWith(CultureInfo.InvariantCulture, member.Name));
                        }
                        obj = createExtensionDataDictionary.Invoke();
                        setExtensionDataDictionary.Invoke(o, obj);
                    }
                    setExtensionDataDictionaryValue(obj, new object[] { key, value });
                };
                contract.ExtensionDataSetter = extensionDataSetter;
            }
            if (attribute.WriteData)
            {
                ConstructorInfo constructorInfo = Enumerable.First<ConstructorInfo>(typeof(DefaultContractResolver.EnumerableDictionaryWrapper<, >).MakeGenericType(new Type[] { type2, type3 }).GetConstructors());
                ObjectConstructor<object> createEnumerableWrapper = JsonTypeReflector.ReflectionDelegateFactory.CreateParameterizedConstructor(constructorInfo);
                ExtensionDataGetter extensionDataGetter = delegate(object o)
                {
                    object obj2 = getExtensionDataDictionary.Invoke(o);
                    if (obj2 == null)
                    {
                        return null;
                    }
                    return (IEnumerable<KeyValuePair<object, object>>)createEnumerableWrapper(new object[] { obj2 });
                };
                contract.ExtensionDataGetter = extensionDataGetter;
            }
            contract.ExtensionDataValueType = type3;
        }
References Newtonsoft.Json.Utilities.ReflectionUtils.CanSetMemberValue(), Newtonsoft.Json.Utilities.ReflectionDelegateFactory.CreateParameterizedConstructor(), Newtonsoft.Json.Serialization.ExtensionDataGetter(), Newtonsoft.Json.Serialization.ExtensionDataSetter(), System.Type.GetGenericArguments(), Newtonsoft.Json.Utilities.ReflectionUtils.GetMemberUnderlyingType(), System.Type.GetMethod(), Newtonsoft.Json.Utilities.ReflectionUtils.ImplementsGenericDefinition(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.Utilities.ReflectionUtils.IsGenericDefinition(), System.key, System.Type.MakeGenericType(), System.Reflection.MemberInfo.Name, System.obj, Newtonsoft.Json.JsonExtensionDataAttribute.ReadData, Newtonsoft.Json.Serialization.JsonTypeReflector.ReflectionDelegateFactory, System.value, and Newtonsoft.Json.JsonExtensionDataAttribute.WriteData.
Referenced by Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract().