Terraria Decompiled: Newtonsoft.Json.Serialization.DefaultContractResolver.SetPropertySettingsFromAttributes
SetPropertySettingsFromAttributes()
void Newtonsoft.Json.Serialization.DefaultContractResolver.SetPropertySettingsFromAttributes (JsonProperty property, object attributeProvider, string name, Type declaringType, MemberSerialization memberSerialization, out bool allowNonPublicAccess) inline private
Definition at line 1015 of file DefaultContractResolver.cs.
        {
            bool dataContractAttribute = JsonTypeReflector.GetDataContractAttribute(declaringType) != null;
            MemberInfo memberInfo = attributeProvider as MemberInfo;
            DataMemberAttribute dataMemberAttribute;
            if (dataContractAttribute && memberInfo != null)
            {
                dataMemberAttribute = JsonTypeReflector.GetDataMemberAttribute(memberInfo);
            }
            else
            {
                dataMemberAttribute = null;
            }
            JsonPropertyAttribute attribute = JsonTypeReflector.GetAttribute<JsonPropertyAttribute>(attributeProvider);
            bool attribute2 = JsonTypeReflector.GetAttribute<JsonRequiredAttribute>(attributeProvider) != null;
            string text;
            bool flag;
            if (attribute != null && attribute.PropertyName != null)
            {
                text = attribute.PropertyName;
                flag = true;
            }
            else if (dataMemberAttribute != null && dataMemberAttribute.Name != null)
            {
                text = dataMemberAttribute.Name;
                flag = true;
            }
            else
            {
                text = name;
                flag = false;
            }
            JsonContainerAttribute attribute3 = JsonTypeReflector.GetAttribute<JsonContainerAttribute>(declaringType);
            NamingStrategy namingStrategy;
            if (((attribute != null) ? attribute.NamingStrategyType : null) != null)
            {
                namingStrategy = JsonTypeReflector.CreateNamingStrategyInstance(attribute.NamingStrategyType, attribute.NamingStrategyParameters);
            }
            else if (((attribute3 != null) ? attribute3.NamingStrategyType : null) != null)
            {
                namingStrategy = JsonTypeReflector.GetContainerNamingStrategy(attribute3);
            }
            else
            {
                namingStrategy = this.NamingStrategy;
            }
            if (namingStrategy != null)
            {
                property.PropertyName = namingStrategy.GetPropertyName(text, flag);
            }
            else
            {
                property.PropertyName = this.ResolvePropertyName(text);
            }
            property.UnderlyingName = name;
            bool flag2 = false;
            if (attribute != null)
            {
                property._required = attribute._required;
                property.Order = attribute._order;
                property.DefaultValueHandling = attribute._defaultValueHandling;
                flag2 = true;
                property.NullValueHandling = attribute._nullValueHandling;
                property.ReferenceLoopHandling = attribute._referenceLoopHandling;
                property.ObjectCreationHandling = attribute._objectCreationHandling;
                property.TypeNameHandling = attribute._typeNameHandling;
                property.IsReference = attribute._isReference;
                property.ItemIsReference = attribute._itemIsReference;
                property.ItemConverter = ((attribute.ItemConverterType != null) ? JsonTypeReflector.CreateJsonConverterInstance(attribute.ItemConverterType, attribute.ItemConverterParameters) : null);
                property.ItemReferenceLoopHandling = attribute._itemReferenceLoopHandling;
                property.ItemTypeNameHandling = attribute._itemTypeNameHandling;
            }
            else
            {
                property.NullValueHandling = default(NullValueHandling?);
                property.ReferenceLoopHandling = default(ReferenceLoopHandling?);
                property.ObjectCreationHandling = default(ObjectCreationHandling?);
                property.TypeNameHandling = default(TypeNameHandling?);
                property.IsReference = default(bool?);
                property.ItemIsReference = default(bool?);
                property.ItemConverter = null;
                property.ItemReferenceLoopHandling = default(ReferenceLoopHandling?);
                property.ItemTypeNameHandling = default(TypeNameHandling?);
                if (dataMemberAttribute != null)
                {
                    property._required = new Required?(dataMemberAttribute.IsRequired ? Required.AllowNull : Required.Default);
                    property.Order = ((dataMemberAttribute.Order != -1) ? new int?(dataMemberAttribute.Order) : default(int?));
                    property.DefaultValueHandling = ((!dataMemberAttribute.EmitDefaultValue) ? new DefaultValueHandling?(DefaultValueHandling.Ignore) : default(DefaultValueHandling?));
                    flag2 = true;
                }
            }
            if (attribute2)
            {
                property._required = new Required?(Required.Always);
                flag2 = true;
            }
            property.HasMemberAttribute = flag2;
            bool flag3 = JsonTypeReflector.GetAttribute<JsonIgnoreAttribute>(attributeProvider) != null || JsonTypeReflector.GetAttribute<JsonExtensionDataAttribute>(attributeProvider) != null || JsonTypeReflector.IsNonSerializable(attributeProvider);
            if (memberSerialization != MemberSerialization.OptIn)
            {
                bool flag4 = JsonTypeReflector.GetAttribute<IgnoreDataMemberAttribute>(attributeProvider) != null;
                property.Ignored = flag3 || flag4;
            }
            else
            {
                property.Ignored = flag3 || !flag2;
            }
            property.Converter = JsonTypeReflector.GetJsonConverter(attributeProvider);
            property.MemberConverter = JsonTypeReflector.GetJsonConverter(attributeProvider);
            DefaultValueAttribute attribute4 = JsonTypeReflector.GetAttribute<DefaultValueAttribute>(attributeProvider);
            if (attribute4 != null)
            {
                property.DefaultValue = attribute4.Value;
            }
            allowNonPublicAccess = false;
            if ((this.DefaultMembersSearchFlags & 32) == 32)
            {
                allowNonPublicAccess = true;
            }
            if (flag2)
            {
                allowNonPublicAccess = true;
            }
            if (memberSerialization == MemberSerialization.Fields)
            {
                allowNonPublicAccess = true;
            }
        }
References Newtonsoft.Json.JsonPropertyAttribute._defaultValueHandling, Newtonsoft.Json.JsonPropertyAttribute._isReference, Newtonsoft.Json.JsonPropertyAttribute._itemIsReference, Newtonsoft.Json.JsonPropertyAttribute._itemReferenceLoopHandling, Newtonsoft.Json.JsonPropertyAttribute._itemTypeNameHandling, Newtonsoft.Json.JsonPropertyAttribute._nullValueHandling, Newtonsoft.Json.JsonPropertyAttribute._objectCreationHandling, Newtonsoft.Json.JsonPropertyAttribute._order, Newtonsoft.Json.JsonPropertyAttribute._referenceLoopHandling, Newtonsoft.Json.JsonPropertyAttribute._required, Newtonsoft.Json.JsonPropertyAttribute._typeNameHandling, Newtonsoft.Json.Serialization.JsonTypeReflector.CreateJsonConverterInstance(), Newtonsoft.Json.Serialization.JsonTypeReflector.CreateNamingStrategyInstance(), Newtonsoft.Json.Serialization.DefaultContractResolver.DefaultMembersSearchFlags, Newtonsoft.Json.Serialization.JsonTypeReflector.GetContainerNamingStrategy(), Newtonsoft.Json.Serialization.JsonTypeReflector.GetDataContractAttribute(), Newtonsoft.Json.Serialization.JsonTypeReflector.GetDataMemberAttribute(), Newtonsoft.Json.Serialization.JsonTypeReflector.GetJsonConverter(), Newtonsoft.Json.Serialization.NamingStrategy.GetPropertyName(), Newtonsoft.Json.Serialization.JsonTypeReflector.IsNonSerializable(), Newtonsoft.Json.JsonPropertyAttribute.ItemConverterParameters, Newtonsoft.Json.JsonPropertyAttribute.ItemConverterType, System.name, Newtonsoft.Json.Serialization.DefaultContractResolver.NamingStrategy, Newtonsoft.Json.JsonPropertyAttribute.NamingStrategyParameters, Newtonsoft.Json.JsonPropertyAttribute.NamingStrategyType, Newtonsoft.Json.JsonPropertyAttribute.PropertyName, Newtonsoft.Json.Serialization.DefaultContractResolver.ResolvePropertyName(), and System.text.
Referenced by Newtonsoft.Json.Serialization.DefaultContractResolver.CreateProperty(), and Newtonsoft.Json.Serialization.DefaultContractResolver.CreatePropertyFromConstructorParameter().