Terraria Decompiled: Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract
CreateContract()
virtual JsonContract Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract (Type objectType) inline protected virtual
Reimplemented in Terraria.Utilities.EasyDeserializationJsonContractResolver.
Definition at line 815 of file DefaultContractResolver.cs.
        {
            if (DefaultContractResolver.IsJsonPrimitiveType(objectType))
            {
                return this.CreatePrimitiveContract(objectType);
            }
            Type type = ReflectionUtils.EnsureNotNullableType(objectType);
            JsonContainerAttribute cachedAttribute = JsonTypeReflector.GetCachedAttribute<JsonContainerAttribute>(type);
            if (cachedAttribute is JsonObjectAttribute)
            {
                return this.CreateObjectContract(objectType);
            }
            if (cachedAttribute is JsonArrayAttribute)
            {
                return this.CreateArrayContract(objectType);
            }
            if (cachedAttribute is JsonDictionaryAttribute)
            {
                return this.CreateDictionaryContract(objectType);
            }
            if (type == typeof(JToken) || type.IsSubclassOf(typeof(JToken)))
            {
                return this.CreateLinqContract(objectType);
            }
            if (CollectionUtils.IsDictionaryType(type))
            {
                return this.CreateDictionaryContract(objectType);
            }
            if (typeof(IEnumerable).IsAssignableFrom(type))
            {
                return this.CreateArrayContract(objectType);
            }
            if (DefaultContractResolver.CanConvertToString(type))
            {
                return this.CreateStringContract(objectType);
            }
            if (!this.IgnoreSerializableInterface && typeof(ISerializable).IsAssignableFrom(type))
            {
                return this.CreateISerializableContract(objectType);
            }
            if (typeof(IDynamicMetaObjectProvider).IsAssignableFrom(type))
            {
                return this.CreateDynamicContract(objectType);
            }
            if (DefaultContractResolver.IsIConvertible(type))
            {
                return this.CreatePrimitiveContract(type);
            }
            return this.CreateObjectContract(objectType);
        }
References Newtonsoft.Json.Serialization.DefaultContractResolver.CanConvertToString(), Newtonsoft.Json.Serialization.DefaultContractResolver.CreateArrayContract(), Newtonsoft.Json.Serialization.DefaultContractResolver.CreateDictionaryContract(), Newtonsoft.Json.Serialization.DefaultContractResolver.CreateDynamicContract(), Newtonsoft.Json.Serialization.DefaultContractResolver.CreateISerializableContract(), Newtonsoft.Json.Serialization.DefaultContractResolver.CreateLinqContract(), Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(), Newtonsoft.Json.Serialization.DefaultContractResolver.CreatePrimitiveContract(), Newtonsoft.Json.Serialization.DefaultContractResolver.CreateStringContract(), Newtonsoft.Json.Utilities.ReflectionUtils.EnsureNotNullableType(), Newtonsoft.Json.Serialization.DefaultContractResolver.IgnoreSerializableInterface, Newtonsoft.Json.Utilities.CollectionUtils.IsDictionaryType(), Newtonsoft.Json.Serialization.DefaultContractResolver.IsIConvertible(), Newtonsoft.Json.Serialization.DefaultContractResolver.IsJsonPrimitiveType(), and System.Type.IsSubclassOf().
Referenced by Newtonsoft.Json.Serialization.CamelCasePropertyNamesContractResolver.ResolveContract(), and Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract().