Terraria Decompiled: Newtonsoft.Json.Serialization.DefaultContractResolver.SetIsSpecifiedActions
SetIsSpecifiedActions()
void Newtonsoft.Json.Serialization.DefaultContractResolver.SetIsSpecifiedActions (JsonProperty property, MemberInfo member, bool allowNonPublicAccess) inline private
Definition at line 1157 of file DefaultContractResolver.cs.
        {
            MemberInfo memberInfo = member.DeclaringType.GetProperty(member.Name + "Specified");
            if (memberInfo == null)
            {
                memberInfo = member.DeclaringType.GetField(member.Name + "Specified");
            }
            if (memberInfo == null || ReflectionUtils.GetMemberUnderlyingType(memberInfo) != typeof(bool))
            {
                return;
            }
            Func<object, object> specifiedPropertyGet = JsonTypeReflector.ReflectionDelegateFactory.CreateGet<object>(memberInfo);
            property.GetIsSpecified = (object o) => (bool)specifiedPropertyGet.Invoke(o);
            if (ReflectionUtils.CanSetMemberValue(memberInfo, allowNonPublicAccess, false))
            {
                property.SetIsSpecified = JsonTypeReflector.ReflectionDelegateFactory.CreateSet<object>(memberInfo);
            }
        }
References Newtonsoft.Json.Utilities.ReflectionUtils.CanSetMemberValue(), System.Reflection.MemberInfo.DeclaringType, System.Type.GetField(), Newtonsoft.Json.Utilities.ReflectionUtils.GetMemberUnderlyingType(), System.Type.GetProperty(), System.Reflection.MemberInfo.Name, and Newtonsoft.Json.Serialization.JsonTypeReflector.ReflectionDelegateFactory.
Referenced by Newtonsoft.Json.Serialization.DefaultContractResolver.CreateProperty().