Terraria Decompiled: Newtonsoft.Json.Serialization.DefaultContractResolver.GetImmutableConstructor
GetImmutableConstructor()
ConstructorInfo Newtonsoft.Json.Serialization.DefaultContractResolver.GetImmutableConstructor (Type objectType, JsonPropertyCollection memberProperties) inline private
Definition at line 420 of file DefaultContractResolver.cs.
        {
            IEnumerator<ConstructorInfo> enumerator = objectType.GetConstructors().GetEnumerator();
            if (enumerator.MoveNext())
            {
                ConstructorInfo constructorInfo = enumerator.Current;
                if (!enumerator.MoveNext())
                {
                    ParameterInfo[] parameters = constructorInfo.GetParameters();
                    if (parameters.Length != 0)
                    {
                        foreach (ParameterInfo parameterInfo in parameters)
{
                            JsonProperty jsonProperty = this.MatchProperty(memberProperties, parameterInfo.Name, parameterInfo.ParameterType);
                            if (jsonProperty == null || jsonProperty.Writable)
{
                                return null;
                            }
                        }
                        return constructorInfo;
                    }
                }
            }
            return null;
        }
References System.Collections.Generic.IEnumerator< out T >.Current, System.Type.GetConstructors(), System.Reflection.MethodBase.GetParameters(), Newtonsoft.Json.Serialization.DefaultContractResolver.MatchProperty(), System.Collections.IEnumerator.MoveNext(), System.Reflection.ParameterInfo.Name, System.Reflection.ParameterInfo.ParameterType, and Newtonsoft.Json.Serialization.JsonProperty.Writable.
Referenced by Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract().