Terraria Decompiled: Newtonsoft.Json.Serialization.DefaultContractResolver.GetSerializableMembers
GetSerializableMembers()
virtual List< MemberInfo > Newtonsoft.Json.Serialization.DefaultContractResolver.GetSerializableMembers (Type objectType) inline protected virtual
Definition at line 160 of file DefaultContractResolver.cs.
        {
            bool ignoreSerializableAttribute = this.IgnoreSerializableAttribute;
            MemberSerialization objectMemberSerialization = JsonTypeReflector.GetObjectMemberSerialization(objectType, ignoreSerializableAttribute);
            IEnumerable<MemberInfo> enumerable = Enumerable.Where<MemberInfo>(ReflectionUtils.GetFieldsAndProperties(objectType, 60), (MemberInfo m) => !ReflectionUtils.IsIndexedProperty(m));
            List<MemberInfo> list = new List<MemberInfo>();
            if (objectMemberSerialization != MemberSerialization.Fields)
            {
                DataContractAttribute dataContractAttribute = JsonTypeReflector.GetDataContractAttribute(objectType);
                List<MemberInfo> list2 = Enumerable.ToList<MemberInfo>(Enumerable.Where<MemberInfo>(ReflectionUtils.GetFieldsAndProperties(objectType, this.DefaultMembersSearchFlags), (MemberInfo m) => !ReflectionUtils.IsIndexedProperty(m)));
                foreach (MemberInfo memberInfo in enumerable)
                {
                    if (this.SerializeCompilerGeneratedMembers || !memberInfo.IsDefined(typeof(CompilerGeneratedAttribute), true))
                    {
                        if (list2.Contains(memberInfo))
{
                            list.Add(memberInfo);
                        }
                        else if (JsonTypeReflector.GetAttribute<JsonPropertyAttribute>(memberInfo) != null)
{
                            list.Add(memberInfo);
                        }
                        else if (JsonTypeReflector.GetAttribute<JsonRequiredAttribute>(memberInfo) != null)
{
                            list.Add(memberInfo);
                        }
                        else if (dataContractAttribute != null && JsonTypeReflector.GetAttribute<DataMemberAttribute>(memberInfo) != null)
{
                            list.Add(memberInfo);
                        }
                        else if (objectMemberSerialization == MemberSerialization.Fields && memberInfo.MemberType() == 4)
{
                            list.Add(memberInfo);
                        }
                    }
                }
                Type type;
                if (objectType.AssignableToTypeName("System.Data.Objects.DataClasses.EntityObject", false, out type))
                {
                    list = Enumerable.ToList<MemberInfo>(Enumerable.Where<MemberInfo>(list, new Func<MemberInfo, bool>(this.ShouldSerializeEntityMember)));
                }
            }
            else
            {
                foreach (MemberInfo memberInfo2 in enumerable)
                {
                    FieldInfo fieldInfo = memberInfo2 as FieldInfo;
                    if (fieldInfo != null && !fieldInfo.IsStatic)
                    {
                        list.Add(memberInfo2);
                    }
                }
            }
            return list;
        }
References Newtonsoft.Json.Serialization.DefaultContractResolver.DefaultMembersSearchFlags, Newtonsoft.Json.Serialization.JsonTypeReflector.GetDataContractAttribute(), Newtonsoft.Json.Utilities.ReflectionUtils.GetFieldsAndProperties(), Newtonsoft.Json.Serialization.JsonTypeReflector.GetObjectMemberSerialization(), Newtonsoft.Json.Serialization.DefaultContractResolver.IgnoreSerializableAttribute, System.Reflection.MemberInfo.IsDefined(), Newtonsoft.Json.Utilities.ReflectionUtils.IsIndexedProperty(), System.Reflection.FieldInfo.IsStatic, System.list, System.Reflection.MemberInfo.MemberType, Newtonsoft.Json.Serialization.DefaultContractResolver.SerializeCompilerGeneratedMembers, and Newtonsoft.Json.Serialization.DefaultContractResolver.ShouldSerializeEntityMember().
Referenced by Newtonsoft.Json.Serialization.DefaultContractResolver.CreateProperties().