Terraria Decompiled: Newtonsoft.Json.Utilities.ReflectionObject.Create
Create() [1/2]
static ReflectionObject Newtonsoft.Json.Utilities.ReflectionObject.Create (Type t, MethodBase creator, params string[] memberNames) inline static
Definition at line 68 of file ReflectionObject.cs.
        {
            ReflectionDelegateFactory reflectionDelegateFactory = JsonTypeReflector.ReflectionDelegateFactory;
            ObjectConstructor<object> objectConstructor = null;
            if (creator != null)
            {
                objectConstructor = reflectionDelegateFactory.CreateParameterizedConstructor(creator);
            }
            else if (ReflectionUtils.HasDefaultConstructor(t, false))
            {
                Func<object> ctor = reflectionDelegateFactory.CreateDefaultConstructor<object>(t);
                objectConstructor = (object[] args) => ctor.Invoke();
            }
            ReflectionObject reflectionObject = new ReflectionObject(objectConstructor);
            int i = 0;
            while (i < memberNames.Length)
            {
                string text = memberNames[i];
                MemberInfo[] member = t.GetMember(text, 20);
                if (member.Length != 1)
                {
                    throw new ArgumentException("Expected a single member with the name '{0}'.".FormatWith(CultureInfo.InvariantCulture, text));
                }
                MemberInfo memberInfo = Enumerable.Single<MemberInfo>(member);
                ReflectionMember reflectionMember = new ReflectionMember();
                MemberTypes memberTypes = memberInfo.MemberType();
                if (memberTypes == 4)
                {
                    goto IL_00AA;
                }
                if (memberTypes != 8)
                {
                    if (memberTypes == 16)
                    {
                        goto IL_00AA;
                    }
                    throw new ArgumentException("Unexpected member type '{0}' for member '{1}'.".FormatWith(CultureInfo.InvariantCulture, memberInfo.MemberType(), memberInfo.Name));
                }
                else
                {
                    MethodInfo methodInfo = (MethodInfo)memberInfo;
                    if (methodInfo.IsPublic)
                    {
                        ParameterInfo[] parameters = methodInfo.GetParameters();
                        if (parameters.Length == 0 && methodInfo.ReturnType != typeof(void))
{
                            MethodCall<object, object> call2 = reflectionDelegateFactory.CreateMethodCall<object>(methodInfo);
                            reflectionMember.Getter = (object target) => call2(target, new object[0]);
                        }
                        else if (parameters.Length == 1 && methodInfo.ReturnType == typeof(void))
{
                            MethodCall<object, object> call = reflectionDelegateFactory.CreateMethodCall<object>(methodInfo);
                            reflectionMember.Setter = delegate(object target, object arg)
{
                                call(target, new object[] { arg });
                            };
                        }
                    }
                }
                IL_01BF:
                if (ReflectionUtils.CanReadMemberValue(memberInfo, false))
                {
                    reflectionMember.Getter = reflectionDelegateFactory.CreateGet<object>(memberInfo);
                }
                if (ReflectionUtils.CanSetMemberValue(memberInfo, false, false))
                {
                    reflectionMember.Setter = reflectionDelegateFactory.CreateSet<object>(memberInfo);
                }
                reflectionMember.MemberType = ReflectionUtils.GetMemberUnderlyingType(memberInfo);
                reflectionObject.Members[text] = reflectionMember;
                i++;
                continue;
                IL_00AA:
                if (ReflectionUtils.CanReadMemberValue(memberInfo, false))
                {
                    reflectionMember.Getter = reflectionDelegateFactory.CreateGet<object>(memberInfo);
                }
                if (ReflectionUtils.CanSetMemberValue(memberInfo, false, false))
                {
                    reflectionMember.Setter = reflectionDelegateFactory.CreateSet<object>(memberInfo);
                    goto IL_01BF;
                }
                goto IL_01BF;
            }
            return reflectionObject;
        }
References Newtonsoft.Json.Utilities.ReflectionUtils.CanReadMemberValue(), Newtonsoft.Json.Utilities.ReflectionUtils.CanSetMemberValue(), Newtonsoft.Json.Utilities.ReflectionDelegateFactory.CreateParameterizedConstructor(), System.Type.GetMember(), Newtonsoft.Json.Utilities.ReflectionUtils.GetMemberUnderlyingType(), System.Reflection.MethodBase.GetParameters(), Newtonsoft.Json.Utilities.ReflectionUtils.HasDefaultConstructor(), System.Globalization.CultureInfo.InvariantCulture, System.Reflection.MethodBase.IsPublic, Newtonsoft.Json.Utilities.ReflectionObject.Members, System.Reflection.MemberInfo.MemberType, System.Reflection.MemberInfo.Name, Newtonsoft.Json.Serialization.JsonTypeReflector.ReflectionDelegateFactory, Newtonsoft.Json.Utilities.ReflectionObject.ReflectionObject(), System.Reflection.MethodInfo.ReturnType, and System.text.