Terraria Decompiled: System.Security.Permissions.EnvironmentPermission.ThrowInvalidFlag
ThrowInvalidFlag()
void System.Security.Permissions.EnvironmentPermission.ThrowInvalidFlag (EnvironmentPermissionAccess flag, bool context) inline package
Definition at line 346 of file EnvironmentPermission.cs.
        {
            string text;
            if (context)
            {
                text = Locale.GetText("Unknown flag '{0}'.");
            }
            else
            {
                text = Locale.GetText("Invalid flag '{0}' in this context.");
            }
            throw new ArgumentException(string.Format(text, flag), "flag");
        }
References System.Security.Format, Locale.GetText(), and System.text.
Referenced by System.Security.Permissions.EnvironmentPermission.AddPathList(), System.Security.Permissions.EnvironmentPermission.GetPathList(), and System.Security.Permissions.EnvironmentPermission.SetPathList().