Terraria Decompiled: System.Security.Permissions.EnvironmentPermission.FromXml
FromXml()
override void System.Security.Permissions.EnvironmentPermission.FromXml (SecurityElement esd) inline
Implements System.Security.ISecurityEncodable.
Definition at line 95 of file EnvironmentPermission.cs.
        {
            CodeAccessPermission.CheckSecurityElement(esd, "esd", 1, 1);
            if (CodeAccessPermission.IsUnrestricted(esd))
            {
                this._state = PermissionState.Unrestricted;
            }
            string text = esd.Attribute("Read");
            if (text != null && text.Length > 0)
            {
                this.SetPathList(EnvironmentPermissionAccess.Read, text);
            }
            string text2 = esd.Attribute("Write");
            if (text2 != null && text2.Length > 0)
            {
                this.SetPathList(EnvironmentPermissionAccess.Write, text2);
            }
        }
References System.Security.SecurityElement.Attribute(), System.Security.CodeAccessPermission.CheckSecurityElement(), System.Security.CodeAccessPermission.IsUnrestricted(), System.Security.Permissions.EnvironmentPermission.SetPathList(), and System.text.