Terraria Decompiled: System.Security.Permissions.EnvironmentPermission.GetPathList
GetPathList() [2/2]
string System.Security.Permissions.EnvironmentPermission.GetPathList (EnvironmentPermissionAccess flag) inline
Definition at line 115 of file EnvironmentPermission.cs.
        {
            switch (flag)
            {
            case EnvironmentPermissionAccess.NoAccess:
            case EnvironmentPermissionAccess.AllAccess:
                this.ThrowInvalidFlag(flag, true);
                break;
            case EnvironmentPermissionAccess.Read:
                return this.GetPathList(this.readList);
            case EnvironmentPermissionAccess.Write:
                return this.GetPathList(this.writeList);
            default:
                this.ThrowInvalidFlag(flag, false);
                break;
            }
            return null;
        }
References System.Security.Permissions.EnvironmentPermission.GetPathList(), System.Security.Permissions.EnvironmentPermission.readList, System.Security.Permissions.EnvironmentPermission.ThrowInvalidFlag(), and System.Security.Permissions.EnvironmentPermission.writeList.
Referenced by System.Security.Permissions.EnvironmentPermission.Copy(), System.Security.Permissions.EnvironmentPermission.GetPathList(), System.Security.Permissions.EnvironmentPermission.Intersect(), System.Security.Permissions.EnvironmentPermission.ToXml(), and System.Security.Permissions.EnvironmentPermission.Union().