Terraria Decompiled: System.Security.Permissions.EnvironmentPermission.Union
Union()
override IPermission System.Security.Permissions.EnvironmentPermission.Union (IPermission other) inline virtual
Reimplemented from System.Security.CodeAccessPermission.
Definition at line 289 of file EnvironmentPermission.cs.
        {
            EnvironmentPermission environmentPermission = this.Cast(other);
            if (environmentPermission == null)
            {
                return this.Copy();
            }
            if (this.IsUnrestricted() || environmentPermission.IsUnrestricted())
            {
                return new EnvironmentPermission(PermissionState.Unrestricted);
            }
            if (this.IsEmpty() && environmentPermission.IsEmpty())
            {
                return null;
            }
            EnvironmentPermission environmentPermission2 = (EnvironmentPermission)this.Copy();
            string text = environmentPermission.GetPathList(EnvironmentPermissionAccess.Read);
            if (text != null)
            {
                environmentPermission2.AddPathList(EnvironmentPermissionAccess.Read, text);
            }
            text = environmentPermission.GetPathList(EnvironmentPermissionAccess.Write);
            if (text != null)
            {
                environmentPermission2.AddPathList(EnvironmentPermissionAccess.Write, text);
            }
            return environmentPermission2;
        }
References System.Security.Permissions.EnvironmentPermission.AddPathList(), System.Security.Permissions.EnvironmentPermission.Cast(), System.Security.Permissions.EnvironmentPermission.Copy(), System.Security.Permissions.EnvironmentPermission.EnvironmentPermission(), System.Security.Permissions.EnvironmentPermission.GetPathList(), System.Security.Permissions.EnvironmentPermission.IsEmpty(), System.Security.Permissions.EnvironmentPermission.IsUnrestricted(), and System.text.