Terraria Decompiled: System.Security.Permissions.EnvironmentPermission.Intersect
Intersect()
override IPermission System.Security.Permissions.EnvironmentPermission.Intersect (IPermission target) inline
Implements System.Security.IPermission.
Definition at line 135 of file EnvironmentPermission.cs.
        {
            EnvironmentPermission environmentPermission = this.Cast(target);
            if (environmentPermission == null)
            {
                return null;
            }
            if (this.IsUnrestricted())
            {
                return environmentPermission.Copy();
            }
            if (environmentPermission.IsUnrestricted())
            {
                return this.Copy();
            }
            int num = 0;
            EnvironmentPermission environmentPermission2 = new EnvironmentPermission(PermissionState.None);
            string pathList = environmentPermission.GetPathList(EnvironmentPermissionAccess.Read);
            if (pathList != null)
            {
                foreach (string text in pathList.Split(';', StringSplitOptions.None))
                {
                    if (this.readList.Contains(text))
                    {
                        environmentPermission2.AddPathList(EnvironmentPermissionAccess.Read, text);
                        num++;
                    }
                }
            }
            string pathList2 = environmentPermission.GetPathList(EnvironmentPermissionAccess.Write);
            if (pathList2 != null)
            {
                foreach (string text2 in pathList2.Split(';', StringSplitOptions.None))
                {
                    if (this.writeList.Contains(text2))
                    {
                        environmentPermission2.AddPathList(EnvironmentPermissionAccess.Write, text2);
                        num++;
                    }
                }
            }
            if (num <= 0)
            {
                return null;
            }
            return environmentPermission2;
        }
References System.Security.Permissions.EnvironmentPermission.AddPathList(), System.Security.Permissions.EnvironmentPermission.Cast(), System.Collections.ArrayList.Contains(), System.Security.Permissions.EnvironmentPermission.Copy(), System.Security.Permissions.EnvironmentPermission.EnvironmentPermission(), System.Security.Permissions.EnvironmentPermission.GetPathList(), System.Security.Permissions.EnvironmentPermission.IsUnrestricted(), System.Security.Permissions.EnvironmentPermission.readList, System.text, and System.Security.Permissions.EnvironmentPermission.writeList.