Terraria Decompiled: System.Security.Permissions.EnvironmentPermission.SetPathList
SetPathList()
void System.Security.Permissions.EnvironmentPermission.SetPathList (EnvironmentPermissionAccess flag, string pathList) inline
Definition at line 225 of file EnvironmentPermission.cs.
        {
            if (pathList == null)
            {
                throw new ArgumentNullException("pathList");
            }
            switch (flag)
            {
            case EnvironmentPermissionAccess.NoAccess:
                break;
            case EnvironmentPermissionAccess.Read:
                this.readList.Clear();
                foreach (string text in pathList.Split(';', StringSplitOptions.None))
                {
                    this.readList.Add(text);
                }
                return;
            case EnvironmentPermissionAccess.Write:
                this.writeList.Clear();
                foreach (string text2 in pathList.Split(';', StringSplitOptions.None))
                {
                    this.writeList.Add(text2);
                }
                return;
            case EnvironmentPermissionAccess.AllAccess:
                this.readList.Clear();
                this.writeList.Clear();
                foreach (string text3 in pathList.Split(';', StringSplitOptions.None))
                {
                    this.readList.Add(text3);
                    this.writeList.Add(text3);
                }
                return;
            default:
                this.ThrowInvalidFlag(flag, false);
                break;
            }
        }
References System.Collections.ArrayList.Add(), System.Collections.ArrayList.Clear(), System.Security.Permissions.EnvironmentPermission.readList, System.text, System.Security.Permissions.EnvironmentPermission.ThrowInvalidFlag(), and System.Security.Permissions.EnvironmentPermission.writeList.
Referenced by System.Security.Permissions.EnvironmentPermission.Copy(), System.Security.Permissions.EnvironmentPermission.EnvironmentPermission(), and System.Security.Permissions.EnvironmentPermission.FromXml().