Terraria Decompiled: Microsoft.Xna.Framework.Audio.SoundBank.SoundBank
SoundBank()
Microsoft.Xna.Framework.Audio.SoundBank.SoundBank (AudioEngine audioEngine, string filename) inline
Definition at line 73 of file SoundBank.cs.
        {
            if (audioEngine == null)
            {
                throw new ArgumentNullException("audioEngine");
            }
            if (string.IsNullOrEmpty(filename))
            {
                throw new ArgumentNullException("filename");
            }
            IntPtr intPtr2;
            IntPtr intPtr = TitleContainer.ReadToPointer(filename, out intPtr2);
            FAudio.FACTAudioEngine_CreateSoundBank(audioEngine.handle, intPtr, (uint)(int)intPtr2, 0U, 0U, out this.handle);
            FNAPlatform.FreeFilePointer(intPtr);
            this.engine = audioEngine;
            this.selfReference = new WeakReference(this, true);
            this.dspSettings = default(FAudio.F3DAUDIO_DSP_SETTINGS);
            this.dspSettings.SrcChannelCount = 1U;
            this.dspSettings.DstChannelCount = (uint)this.engine.channels;
            this.dspSettings.pMatrixCoefficients = FNAPlatform.Malloc((int)(4U * this.dspSettings.SrcChannelCount * this.dspSettings.DstChannelCount));
            this.engine.RegisterPointer(this.handle, this.selfReference);
            this.IsDisposed = false;
        }
References Microsoft.Xna.Framework.Audio.AudioEngine.channels, Microsoft.Xna.Framework.Audio.SoundBank.dspSettings, Microsoft.Xna.Framework.Audio.SoundBank.engine, FAudio.FACTAudioEngine_CreateSoundBank(), Microsoft.Xna.Framework.FNAPlatform.FreeFilePointer, Microsoft.Xna.Framework.Audio.AudioEngine.handle, Microsoft.Xna.Framework.Audio.SoundBank.handle, Microsoft.Xna.Framework.FNAPlatform.Malloc, Microsoft.Xna.Framework.TitleContainer.ReadToPointer(), Microsoft.Xna.Framework.Audio.AudioEngine.RegisterPointer(), Microsoft.Xna.Framework.Audio.SoundBank.selfReference, and System.U.