Terraria Decompiled: Microsoft.Xna.Framework.Audio.SoundBank.PlayCue
PlayCue() [2/2]
void Microsoft.Xna.Framework.Audio.SoundBank.PlayCue (string name, AudioListener listener, AudioEmitter emitter) inline
Definition at line 174 of file SoundBank.cs.
        {
            if (string.IsNullOrEmpty(name))
            {
                throw new ArgumentNullException("name");
            }
            if (listener == null)
            {
                throw new ArgumentNullException("listener");
            }
            if (emitter == null)
            {
                throw new ArgumentNullException("emitter");
            }
            ushort num = FAudio.FACTSoundBank_GetCueIndex(this.handle, name);
            if (num == 65535)
            {
                throw new InvalidOperationException("Invalid cue name!");
            }
            emitter.emitterData.ChannelCount = this.dspSettings.SrcChannelCount;
            emitter.emitterData.CurveDistanceScaler = float.MaxValue;
            FAudio.FACT3DCalculate(this.engine.handle3D, ref listener.listenerData, ref emitter.emitterData, ref this.dspSettings);
            FAudio.FACTSoundBank_Play3D(this.handle, num, 0U, 0, ref this.dspSettings, IntPtr.Zero);
        }
References Microsoft.Xna.Framework.Audio.SoundBank.dspSettings, Microsoft.Xna.Framework.Audio.AudioEmitter.emitterData, Microsoft.Xna.Framework.Audio.SoundBank.engine, FAudio.FACT3DCalculate(), FAudio.FACTSoundBank_GetCueIndex(), FAudio.FACTSoundBank_Play3D(), Microsoft.Xna.Framework.Audio.SoundBank.handle, Microsoft.Xna.Framework.Audio.AudioEngine.handle3D, Microsoft.Xna.Framework.Audio.AudioListener.listenerData, System.name, System.U, and System.IntPtr.Zero.