Terraria Decompiled: System.Security.Permissions.RegistryPermission.GetPathList
GetPathList() [2/2]
string System.Security.Permissions.RegistryPermission.GetPathList (RegistryPermissionAccess access) inline
Definition at line 81 of file RegistryPermission.cs.
        {
            switch (access)
            {
            case RegistryPermissionAccess.NoAccess:
            case RegistryPermissionAccess.AllAccess:
                this.ThrowInvalidFlag(access, true);
                goto IL_0061;
            case RegistryPermissionAccess.Read:
                return this.GetPathList(this.readList);
            case RegistryPermissionAccess.Write:
                return this.GetPathList(this.writeList);
            case RegistryPermissionAccess.Create:
                return this.GetPathList(this.createList);
            }
            this.ThrowInvalidFlag(access, false);
            IL_0061:
            return null;
        }
References System.Security.Permissions.RegistryPermission.createList, System.Security.Permissions.RegistryPermission.GetPathList(), System.Security.Permissions.RegistryPermission.readList, System.Security.Permissions.RegistryPermission.ThrowInvalidFlag(), and System.Security.Permissions.RegistryPermission.writeList.
Referenced by System.Security.Permissions.RegistryPermission.Copy(), System.Security.Permissions.RegistryPermission.GetPathList(), System.Security.Permissions.RegistryPermission.ToXml(), and System.Security.Permissions.RegistryPermission.Union().