Terraria Decompiled: System.Security.Permissions.RegistryPermission.Intersect
Intersect()
override IPermission System.Security.Permissions.RegistryPermission.Intersect (IPermission target) inline
Implements System.Security.IPermission.
Definition at line 197 of file RegistryPermission.cs.
        {
            RegistryPermission registryPermission = this.Cast(target);
            if (registryPermission == null)
            {
                return null;
            }
            if (this.IsUnrestricted())
            {
                return registryPermission.Copy();
            }
            if (registryPermission.IsUnrestricted())
            {
                return this.Copy();
            }
            RegistryPermission registryPermission2 = new RegistryPermission(PermissionState.None);
            this.IntersectKeys(this.createList, registryPermission.createList, registryPermission2.createList);
            this.IntersectKeys(this.readList, registryPermission.readList, registryPermission2.readList);
            this.IntersectKeys(this.writeList, registryPermission.writeList, registryPermission2.writeList);
            if (!registryPermission2.IsEmpty())
            {
                return registryPermission2;
            }
            return null;
        }
References System.Security.Permissions.RegistryPermission.Cast(), System.Security.Permissions.RegistryPermission.Copy(), System.Security.Permissions.RegistryPermission.createList, System.Security.Permissions.RegistryPermission.IntersectKeys(), System.Security.Permissions.RegistryPermission.IsEmpty(), System.Security.Permissions.RegistryPermission.IsUnrestricted(), System.Security.Permissions.RegistryPermission.readList, System.Security.Permissions.RegistryPermission.RegistryPermission(), and System.Security.Permissions.RegistryPermission.writeList.