Terraria Decompiled: System.Security.Permissions.RegistryPermission.Copy
Copy()
override IPermission System.Security.Permissions.RegistryPermission.Copy () inline
Implements System.Security.IPermission.
Definition at line 149 of file RegistryPermission.cs.
        {
            RegistryPermission registryPermission = new RegistryPermission(this._state);
            string text = this.GetPathList(RegistryPermissionAccess.Create);
            if (text != null)
            {
                registryPermission.SetPathList(RegistryPermissionAccess.Create, text);
            }
            text = this.GetPathList(RegistryPermissionAccess.Read);
            if (text != null)
            {
                registryPermission.SetPathList(RegistryPermissionAccess.Read, text);
            }
            text = this.GetPathList(RegistryPermissionAccess.Write);
            if (text != null)
            {
                registryPermission.SetPathList(RegistryPermissionAccess.Write, text);
            }
            return registryPermission;
        }
References System.Security.Permissions.RegistryPermission._state, System.Security.Permissions.RegistryPermission.GetPathList(), System.Security.Permissions.RegistryPermission.RegistryPermission(), System.Security.Permissions.RegistryPermission.SetPathList(), and System.text.
Referenced by System.Security.Permissions.RegistryPermission.Intersect(), and System.Security.Permissions.RegistryPermission.Union().