Terraria Decompiled: System.Security.Permissions.RegistryPermission.SetPathList
SetPathList()
void System.Security.Permissions.RegistryPermission.SetPathList (RegistryPermissionAccess access, string pathList) inline
Definition at line 102 of file RegistryPermission.cs.
        {
            if (pathList == null)
            {
                throw new ArgumentNullException("pathList");
            }
            switch (access)
            {
            case RegistryPermissionAccess.NoAccess:
                return;
            case RegistryPermissionAccess.Read:
                this.readList.Clear();
                foreach (string text in pathList.Split(';', StringSplitOptions.None))
                {
                    this.readList.Add(text);
                }
                return;
            case RegistryPermissionAccess.Write:
                this.writeList.Clear();
                foreach (string text2 in pathList.Split(';', StringSplitOptions.None))
                {
                    this.writeList.Add(text2);
                }
                return;
            case RegistryPermissionAccess.Create:
                this.createList.Clear();
                foreach (string text3 in pathList.Split(';', StringSplitOptions.None))
                {
                    this.createList.Add(text3);
                }
                return;
            case RegistryPermissionAccess.AllAccess:
                this.createList.Clear();
                this.readList.Clear();
                this.writeList.Clear();
                foreach (string text4 in pathList.Split(';', StringSplitOptions.None))
                {
                    this.createList.Add(text4);
                    this.readList.Add(text4);
                    this.writeList.Add(text4);
                }
                return;
            }
            this.ThrowInvalidFlag(access, false);
        }
References System.Collections.ArrayList.Add(), System.Collections.ArrayList.Clear(), System.Security.Permissions.RegistryPermission.createList, System.Security.Permissions.RegistryPermission.readList, System.text, System.Security.Permissions.RegistryPermission.ThrowInvalidFlag(), and System.Security.Permissions.RegistryPermission.writeList.
Referenced by System.Security.Permissions.RegistryPermission.Copy(), and System.Security.Permissions.RegistryPermission.FromXml().