Terraria Decompiled: System.Security.Permissions.RegistryPermission.Union
Union()
override IPermission System.Security.Permissions.RegistryPermission.Union (IPermission other) inline virtual
Reimplemented from System.Security.CodeAccessPermission.
Definition at line 278 of file RegistryPermission.cs.
        {
            RegistryPermission registryPermission = this.Cast(other);
            if (registryPermission == null)
            {
                return this.Copy();
            }
            if (this.IsUnrestricted() || registryPermission.IsUnrestricted())
            {
                return new RegistryPermission(PermissionState.Unrestricted);
            }
            if (this.IsEmpty() && registryPermission.IsEmpty())
            {
                return null;
            }
            RegistryPermission registryPermission2 = (RegistryPermission)this.Copy();
            string text = registryPermission.GetPathList(RegistryPermissionAccess.Create);
            if (text != null)
            {
                registryPermission2.AddPathList(RegistryPermissionAccess.Create, text);
            }
            text = registryPermission.GetPathList(RegistryPermissionAccess.Read);
            if (text != null)
            {
                registryPermission2.AddPathList(RegistryPermissionAccess.Read, text);
            }
            text = registryPermission.GetPathList(RegistryPermissionAccess.Write);
            if (text != null)
            {
                registryPermission2.AddPathList(RegistryPermissionAccess.Write, text);
            }
            return registryPermission2;
        }
References System.Security.Permissions.RegistryPermission.AddPathList(), System.Security.Permissions.RegistryPermission.Cast(), System.Security.Permissions.RegistryPermission.Copy(), System.Security.Permissions.RegistryPermission.GetPathList(), System.Security.Permissions.RegistryPermission.IsEmpty(), System.Security.Permissions.RegistryPermission.IsUnrestricted(), System.Security.Permissions.RegistryPermission.RegistryPermission(), and System.text.