Terraria Decompiled: System.Security.Permissions.RegistryPermission.IsSubsetOf
IsSubsetOf()
override bool System.Security.Permissions.RegistryPermission.IsSubsetOf (IPermission target) inline
Implements System.Security.IPermission.
Definition at line 224 of file RegistryPermission.cs.
        {
            RegistryPermission registryPermission = this.Cast(target);
            if (registryPermission == null)
            {
                return false;
            }
            if (registryPermission.IsEmpty())
            {
                return this.IsEmpty();
            }
            if (this.IsUnrestricted())
            {
                return registryPermission.IsUnrestricted();
            }
            return registryPermission.IsUnrestricted() || (this.KeyIsSubsetOf(this.createList, registryPermission.createList) && this.KeyIsSubsetOf(this.readList, registryPermission.readList) && this.KeyIsSubsetOf(this.writeList, registryPermission.writeList));
        }
References System.Security.Permissions.RegistryPermission.Cast(), System.Security.Permissions.RegistryPermission.createList, System.Security.Permissions.RegistryPermission.IsEmpty(), System.Security.Permissions.RegistryPermission.IsUnrestricted(), System.Security.Permissions.RegistryPermission.KeyIsSubsetOf(), System.Security.Permissions.RegistryPermission.readList, and System.Security.Permissions.RegistryPermission.writeList.