Terraria Decompiled: Terraria.GameContent.EmergencyStacking.GetPlayerViewRects
GetPlayerViewRects()
static List< Rectangle > Terraria.GameContent.EmergencyStacking.GetPlayerViewRects () inline static private
Definition at line 146 of file EmergencyStacking.cs.
        {
            List<Rectangle> list = EmergencyStacking.playerViewRectsScratch;
            list.Clear();
            for (int i = 0; i < 255; i++)
            {
                Player player = Main.player[i];
                if (player.active)
                {
                    list.Add(Utils.CenteredRectangle(player.Center.ToPoint(), EmergencyStacking.PlayerViewRectSize));
                }
            }
            return list;
        }
References Terraria.Player.active, Terraria.Entity.Center, Terraria.Utils.CenteredRectangle(), System.Collections.Generic.List< T >.Clear(), System.list, Terraria.Main.player, Terraria.GameContent.EmergencyStacking.PlayerViewRectSize, and Terraria.GameContent.EmergencyStacking.playerViewRectsScratch.
Referenced by Terraria.GameContent.EmergencyStacking.MemoStackableItems().