Terraria Decompiled: Terraria.GameContent.EmergencyStacking.MemoStackableItems
MemoStackableItems()
static EmergencyStacking.StackableItem[] Terraria.GameContent.EmergencyStacking.MemoStackableItems () inline static private
Definition at line 123 of file EmergencyStacking.cs.
        {
            List<Rectangle> playerViewRects = EmergencyStacking.GetPlayerViewRects();
            EmergencyStacking.StackableItem[] array = EmergencyStacking.stackableItemsScratch;
            Array.Clear(array, 0, array.Length);
            for (int i = 0; i < 400; i++)
            {
                WorldItem worldItem = Main.item[i];
                if (!worldItem.IsAir && worldItem.stack < worldItem.maxStack && !worldItem.instanced && worldItem.shimmerTime == 0f && Main.timeItemSlotCannotBeReusedFor[i] == 0)
                {
                    array[i] = new EmergencyStacking.StackableItem
                    {
                        type = worldItem.type,
                        age = worldItem.timeSinceItemSpawned,
                        isOnScreen = EmergencyStacking.AnyContains(playerViewRects, worldItem.Center.ToPoint()),
                        item = worldItem
                    };
                }
            }
            return array;
        }
References Terraria.GameContent.EmergencyStacking.AnyContains(), System.array, Terraria.Entity.Center, System.Array.Clear(), Terraria.GameContent.EmergencyStacking.GetPlayerViewRects(), Terraria.WorldItem.instanced, Terraria.WorldItem.IsAir, System.item, Terraria.Main.item, Terraria.WorldItem.maxStack, Terraria.WorldItem.shimmerTime, Terraria.WorldItem.stack, Terraria.GameContent.EmergencyStacking.stackableItemsScratch, Terraria.Main.timeItemSlotCannotBeReusedFor, Terraria.WorldItem.timeSinceItemSpawned, and Terraria.WorldItem.type.
Referenced by Terraria.GameContent.EmergencyStacking.EmergencyStackItemsToMakeSpace().