Terraria Decompiled: Terraria.GameContent.EmergencyStacking.ProcessPendingTransfers
ProcessPendingTransfers() [2/2]
static void Terraria.GameContent.EmergencyStacking.ProcessPendingTransfers (out int freeSlot) inline static private
Definition at line 74 of file EmergencyStacking.cs.
        {
            freeSlot = 400;
            for (int i = 0; i < EmergencyStacking.PendingTransfers.Count; i++)
            {
                EmergencyStacking.UpdateDestinationFromPreviousTransfers(EmergencyStacking.PendingTransfers, i);
                EmergencyStacking.Transfer transfer = EmergencyStacking.PendingTransfers[i];
                EmergencyStacking.DoTransfer(transfer);
                if (transfer.src.IsAir)
                {
                    freeSlot = Math.Min(freeSlot, transfer.src.whoAmI);
                }
            }
            if (Main.netMode != 2)
            {
                EmergencyStacking.PendingTransfers.Clear();
                return;
            }
            Array.Clear(EmergencyStacking.HasPendingTransfer, 0, EmergencyStacking.HasPendingTransfer.Length);
            EmergencyStacking.PendingTransfers.RemoveAll((EmergencyStacking.Transfer t) => t.NumToTransfer == 0);
            foreach (EmergencyStacking.Transfer transfer2 in EmergencyStacking.PendingTransfers)
            {
                EmergencyStacking.HasPendingTransfer[transfer2.src.whoAmI] = true;
                EmergencyStacking.HasPendingTransfer[transfer2.dst.whoAmI] = true;
            }
        }
References System.Array.Clear(), Terraria.GameContent.EmergencyStacking.DoTransfer(), Terraria.GameContent.EmergencyStacking.HasPendingTransfer, Terraria.WorldItem.IsAir, System.Math.Min(), Terraria.Main.netMode, Terraria.GameContent.EmergencyStacking.PendingTransfers, Terraria.GameContent.EmergencyStacking.Transfer.src, Terraria.GameContent.EmergencyStacking.UpdateDestinationFromPreviousTransfers(), and Terraria.Entity.whoAmI.