Terraria Decompiled: Terraria.ObjectData.TileObjectData.LiquidPlace
LiquidPlace() [2/2]
bool Terraria.ObjectData.TileObjectData.LiquidPlace (Tile checkTile) inline
Definition at line 1894 of file TileObjectData.cs.
        {
            if (checkTile == null)
            {
                return false;
            }
            if (checkTile.liquid > 0)
            {
                switch (checkTile.liquidType())
                {
                case 0:
                case 2:
                case 3:
                    if (this.WaterPlacement == LiquidPlacement.NotAllowed)
                    {
                        return false;
                    }
                    if (this.WaterPlacement == LiquidPlacement.OnlyInFullLiquid && checkTile.liquid != 255)
                    {
                        return false;
                    }
                    break;
                case 1:
                    if (this.LavaPlacement == LiquidPlacement.NotAllowed)
                    {
                        return false;
                    }
                    if (this.LavaPlacement == LiquidPlacement.OnlyInFullLiquid && checkTile.liquid != 255)
                    {
                        return false;
                    }
                    break;
                }
            }
            else
            {
                switch (checkTile.liquidType())
                {
                case 0:
                case 2:
                case 3:
                    if (this.WaterPlacement == LiquidPlacement.OnlyInFullLiquid || this.WaterPlacement == LiquidPlacement.OnlyInLiquid)
                    {
                        return false;
                    }
                    break;
                case 1:
                    if (this.LavaPlacement == LiquidPlacement.OnlyInFullLiquid || this.LavaPlacement == LiquidPlacement.OnlyInLiquid)
                    {
                        return false;
                    }
                    break;
                }
            }
            return true;
        }
References Terraria.ObjectData.TileObjectData.LavaPlacement, Terraria.Tile.liquid, Terraria.Tile.liquidType(), and Terraria.ObjectData.TileObjectData.WaterPlacement.
Referenced by Terraria.TileObject.CanPlace(), and Terraria.ObjectData.TileObjectData.CheckLiquidPlacement().