Terraria Decompiled: Terraria.ObjectData.TileObjectData.Calculate
Calculate()
void Terraria.ObjectData.TileObjectData.Calculate () inline private
Definition at line 153 of file TileObjectData.cs.
        {
            if (this._tileObjectCoords.calculated)
            {
                return;
            }
            this._tileObjectCoords.calculated = true;
            this._tileObjectCoords.styleWidth = (this._tileObjectCoords.width + this._tileObjectCoords.padding) * this.Width + (int)this._tileObjectCoords.paddingFix.X;
            int num = 0;
            this._tileObjectCoords.styleHeight = 0;
            for (int i = 0; i < this._tileObjectCoords.heights.Length; i++)
            {
                num += this._tileObjectCoords.heights[i] + this._tileObjectCoords.padding;
            }
            num += (int)this._tileObjectCoords.paddingFix.Y;
            this._tileObjectCoords.styleHeight = num;
            if (this._hasOwnLiquidDeath)
            {
                if (this._liquidDeath.lava)
                {
                    this.LavaPlacement = LiquidPlacement.NotAllowed;
                }
                if (this._liquidDeath.water)
                {
                    this.WaterPlacement = LiquidPlacement.NotAllowed;
                }
            }
        }
References Terraria.ObjectData.TileObjectData._hasOwnLiquidDeath, Terraria.ObjectData.TileObjectData._liquidDeath, Terraria.ObjectData.TileObjectData._tileObjectCoords, Terraria.Modules.TileObjectCoordinatesModule.calculated, Terraria.Modules.TileObjectCoordinatesModule.heights, int, Terraria.Modules.LiquidDeathModule.lava, Terraria.Modules.TileObjectCoordinatesModule.padding, Terraria.Modules.TileObjectCoordinatesModule.paddingFix, Terraria.Modules.LiquidDeathModule.water, Terraria.ObjectData.TileObjectData.Width, Terraria.DataStructures.Point16.X, and Terraria.DataStructures.Point16.Y.
Referenced by Terraria.ObjectData.TileObjectData.addAlternate(), Terraria.ObjectData.TileObjectData.addBaseTile(), Terraria.ObjectData.TileObjectData.addSubTile(), Terraria.ObjectData.TileObjectData.addSubTile(), Terraria.ObjectData.TileObjectData.addSubTileRange(), Terraria.ObjectData.TileObjectData.addTile(), and Terraria.ObjectData.TileObjectData.Initialize().