Terraria Decompiled: Terraria.ObjectData.TileObjectData.CustomPlace
CustomPlace()
static bool Terraria.ObjectData.TileObjectData.CustomPlace (int type, int style) inline static
Definition at line 5056 of file TileObjectData.cs.
        {
            if (type < 0 || type >= TileObjectData._data.Count || style < 0)
            {
                return false;
            }
            TileObjectData tileObjectData = TileObjectData._data[type];
            if (tileObjectData == null)
            {
                return false;
            }
            List<TileObjectData> subTiles = tileObjectData.SubTiles;
            if (subTiles != null && style < subTiles.Count)
            {
                TileObjectData tileObjectData2 = subTiles[style];
                if (tileObjectData2 != null)
                {
                    return tileObjectData2._usesCustomCanPlace;
                }
            }
            return tileObjectData._usesCustomCanPlace;
        }
References Terraria.ObjectData.TileObjectData._data, Terraria.ObjectData.TileObjectData._usesCustomCanPlace, System.Collections.Generic.List< T >.Count, and Terraria.ObjectData.TileObjectData.SubTiles.
Referenced by Terraria.Projectile.GasTrapCheck(), Terraria.Player.PlaceThing_Tiles_TryPlacing(), and Terraria.Player.UpdatePlacementPreview().