Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDictionary
SerializeDictionary()
void Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDictionary (JsonWriter writer, IDictionary values, JsonDictionaryContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty) inline private
Definition at line 821 of file JsonSerializerInternalWriter.cs.
        {
            IWrappedDictionary wrappedDictionary = values as IWrappedDictionary;
            object obj = ((wrappedDictionary != null) ? wrappedDictionary.UnderlyingDictionary : values);
            this.OnSerializing(writer, contract, obj);
            this._serializeStack.Add(obj);
            this.WriteObjectStart(writer, obj, contract, member, collectionContract, containerProperty);
            if (contract.ItemContract == null)
            {
                contract.ItemContract = this.Serializer._contractResolver.ResolveContract(contract.DictionaryValueType ?? typeof(object));
            }
            if (contract.KeyContract == null)
            {
                contract.KeyContract = this.Serializer._contractResolver.ResolveContract(contract.DictionaryKeyType ?? typeof(object));
            }
            int top = writer.Top;
            using (IDictionaryEnumerator enumerator = values.GetEnumerator())
            {
                while (enumerator.MoveNext())
                {
                    DictionaryEntry entry = enumerator.Entry;
                    bool flag;
                    string text = this.GetPropertyName(writer, entry.Key, contract.KeyContract, out flag);
                    text = ((contract.DictionaryKeyResolver != null) ? contract.DictionaryKeyResolver.Invoke(text) : text);
                    try
                    {
                        object value = entry.Value;
                        JsonContract jsonContract = contract.FinalItemContract ?? this.GetContractSafe(value);
                        if (this.ShouldWriteReference(value, null, jsonContract, contract, member))
{
                            writer.WritePropertyName(text, flag);
                            this.WriteReference(writer, value);
                        }
                        else if (this.CheckForCircularReference(writer, value, null, jsonContract, contract, member))
{
                            writer.WritePropertyName(text, flag);
                            this.SerializeValue(writer, value, jsonContract, null, contract, member);
                        }
                    }
                    catch (Exception ex)
                    {
                        if (!base.IsErrorHandled(obj, contract, text, null, writer.ContainerPath, ex))
{
                            throw;
                        }
                        this.HandleError(writer, top);
                    }
                }
            }
            writer.WriteEndObject();
            this._serializeStack.RemoveAt(this._serializeStack.Count - 1);
            this.OnSerialized(writer, contract, obj);
        }
References Newtonsoft.Json.JsonSerializer._contractResolver, Newtonsoft.Json.Serialization.JsonSerializerInternalWriter._serializeStack, System.Collections.Generic.List< T >.Add(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(), Newtonsoft.Json.JsonWriter.ContainerPath, System.Collections.Generic.List< T >.Count, Newtonsoft.Json.Serialization.JsonDictionaryContract.DictionaryKeyResolver, Newtonsoft.Json.Serialization.JsonDictionaryContract.DictionaryKeyType, Newtonsoft.Json.Serialization.JsonDictionaryContract.DictionaryValueType, System.Collections.IDictionaryEnumerator.Entry, Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.GetContractSafe(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.GetPropertyName(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.HandleError(), Newtonsoft.Json.Serialization.JsonContainerContract.ItemContract, System.Collections.DictionaryEntry.Key, Newtonsoft.Json.Serialization.JsonDictionaryContract.KeyContract, System.Collections.IEnumerator.MoveNext(), System.obj, Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.OnSerialized(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.OnSerializing(), System.Collections.Generic.List< T >.RemoveAt(), Newtonsoft.Json.Serialization.JsonSerializerInternalBase.Serializer, Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.ShouldWriteReference(), System.text, Newtonsoft.Json.JsonWriter.Top, Newtonsoft.Json.Utilities.IWrappedDictionary.UnderlyingDictionary, System.Collections.DictionaryEntry.Value, System.value, System.values, Newtonsoft.Json.JsonWriter.WriteEndObject(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.WriteObjectStart(), Newtonsoft.Json.JsonWriter.WritePropertyName(), and Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.WriteReference().
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue().