Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.GetPropertyName
GetPropertyName()
string Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.GetPropertyName (JsonWriter writer, object name, JsonContract contract, out bool escape) inline private
Definition at line 876 of file JsonSerializerInternalWriter.cs.
        {
            if (contract.ContractType == JsonContractType.Primitive)
            {
                switch (((JsonPrimitiveContract)contract).TypeCode)
                {
                case PrimitiveTypeCode.Single:
                case PrimitiveTypeCode.SingleNullable:
                {
                    float num = (float)name;
                    escape = false;
                    return num.ToString("R", CultureInfo.InvariantCulture);
                }
                case PrimitiveTypeCode.Double:
                case PrimitiveTypeCode.DoubleNullable:
                {
                    double num2 = (double)name;
                    escape = false;
                    return num2.ToString("R", CultureInfo.InvariantCulture);
                }
                case PrimitiveTypeCode.DateTime:
                case PrimitiveTypeCode.DateTimeNullable:
                {
                    DateTime dateTime = DateTimeUtils.EnsureDateTime((DateTime)name, writer.DateTimeZoneHandling);
                    escape = false;
                    StringWriter stringWriter = new StringWriter(CultureInfo.InvariantCulture);
                    DateTimeUtils.WriteDateTimeString(stringWriter, dateTime, writer.DateFormatHandling, writer.DateFormatString, writer.Culture);
                    return stringWriter.ToString();
                }
                case PrimitiveTypeCode.DateTimeOffset:
                case PrimitiveTypeCode.DateTimeOffsetNullable:
                {
                    escape = false;
                    StringWriter stringWriter2 = new StringWriter(CultureInfo.InvariantCulture);
                    DateTimeUtils.WriteDateTimeOffsetString(stringWriter2, (DateTimeOffset)name, writer.DateFormatHandling, writer.DateFormatString, writer.Culture);
                    return stringWriter2.ToString();
                }
                default:
                    escape = true;
                    return Convert.ToString(name, CultureInfo.InvariantCulture);
                }
            }
            else
            {
                string text;
                if (JsonSerializerInternalWriter.TryConvertToString(name, name.GetType(), out text))
                {
                    escape = true;
                    return text;
                }
                escape = true;
                return name.ToString();
            }
        }
References Newtonsoft.Json.Serialization.JsonContract.ContractType, Newtonsoft.Json.JsonWriter.Culture, Newtonsoft.Json.JsonWriter.DateFormatHandling, Newtonsoft.Json.JsonWriter.DateFormatString, Newtonsoft.Json.JsonWriter.DateTimeZoneHandling, Newtonsoft.Json.Utilities.DateTimeUtils.EnsureDateTime(), System.Globalization.CultureInfo.InvariantCulture, System.name, System.text, System.IO.StringWriter.ToString(), System.Convert.ToString(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.TryConvertToString(), Newtonsoft.Json.Utilities.DateTimeUtils.WriteDateTimeOffsetString(), and Newtonsoft.Json.Utilities.DateTimeUtils.WriteDateTimeString().
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDictionary(), and Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject().