Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeISerializable
SerializeISerializable()
void Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeISerializable (JsonWriter writer, ISerializable value, JsonISerializableContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty) inline private
Definition at line 681 of file JsonSerializerInternalWriter.cs.
        {
            if (!JsonTypeReflector.FullyTrusted)
            {
                string text = "Type '{0}' implements ISerializable but cannot be serialized using the ISerializable interface because the current application is not fully trusted and ISerializable can expose secure data." + Environment.NewLine + "To fix this error either change the environment to be fully trusted, change the application to not deserialize the type, add JsonObjectAttribute to the type or change the JsonSerializer setting ContractResolver to use a new DefaultContractResolver with IgnoreSerializableInterface set to true." + Environment.NewLine;
                text = text.FormatWith(CultureInfo.InvariantCulture, value.GetType());
                throw JsonSerializationException.Create(null, writer.ContainerPath, text, null);
            }
            this.OnSerializing(writer, contract, value);
            this._serializeStack.Add(value);
            this.WriteObjectStart(writer, value, contract, member, collectionContract, containerProperty);
            SerializationInfo serializationInfo = new SerializationInfo(contract.UnderlyingType, new FormatterConverter());
            value.GetObjectData(serializationInfo, this.Serializer._context);
            foreach (SerializationEntry serializationEntry in serializationInfo)
            {
                JsonContract contractSafe = this.GetContractSafe(serializationEntry.Value);
                if (this.ShouldWriteReference(serializationEntry.Value, null, contractSafe, contract, member))
                {
                    writer.WritePropertyName(serializationEntry.Name);
                    this.WriteReference(writer, serializationEntry.Value);
                }
                else if (this.CheckForCircularReference(writer, serializationEntry.Value, null, contractSafe, contract, member))
                {
                    writer.WritePropertyName(serializationEntry.Name);
                    this.SerializeValue(writer, serializationEntry.Value, contractSafe, null, contract, member);
                }
            }
            writer.WriteEndObject();
            this._serializeStack.RemoveAt(this._serializeStack.Count - 1);
            this.OnSerialized(writer, contract, value);
        }
References Newtonsoft.Json.JsonSerializer._context, Newtonsoft.Json.Serialization.JsonSerializerInternalWriter._serializeStack, System.Collections.Generic.List< T >.Add(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(), Newtonsoft.Json.JsonWriter.ContainerPath, System.Collections.Generic.List< T >.Count, Newtonsoft.Json.JsonSerializationException.Create(), Newtonsoft.Json.Serialization.JsonTypeReflector.FullyTrusted, Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.GetContractSafe(), System.Globalization.CultureInfo.InvariantCulture, System.Runtime.Serialization.SerializationEntry.Name, Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.OnSerialized(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.OnSerializing(), System.Collections.Generic.List< T >.RemoveAt(), Newtonsoft.Json.Serialization.JsonSerializerInternalBase.Serializer, Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.ShouldWriteReference(), System.text, Newtonsoft.Json.Serialization.JsonContract.UnderlyingType, System.value, System.Runtime.Serialization.SerializationEntry.Value, Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.WriteObjectStart(), and Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.WriteReference().
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue().