Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.WriteTypeProperty
WriteTypeProperty()
void Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.WriteTypeProperty (JsonWriter writer, Type type) inline private
Definition at line 484 of file JsonSerializerInternalWriter.cs.
        {
            string typeName = ReflectionUtils.GetTypeName(type, this.Serializer._typeNameAssemblyFormatHandling, this.Serializer._serializationBinder);
            if (this.TraceWriter != null && this.TraceWriter.LevelFilter >= 4)
            {
                this.TraceWriter.Trace(4, JsonPosition.FormatMessage(null, writer.Path, "Writing type name '{0}' for {1}.".FormatWith(CultureInfo.InvariantCulture, typeName, type)), null);
            }
            writer.WritePropertyName("$type", false);
            writer.WriteValue(typeName);
        }
References Newtonsoft.Json.JsonSerializer._typeNameAssemblyFormatHandling, Newtonsoft.Json.JsonPosition.FormatMessage(), Newtonsoft.Json.Utilities.ReflectionUtils.GetTypeName(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.Serialization.ITraceWriter.LevelFilter, Newtonsoft.Json.JsonWriter.Path, Newtonsoft.Json.Serialization.JsonSerializerInternalBase.Serializer, Newtonsoft.Json.Serialization.ITraceWriter.Trace(), Newtonsoft.Json.Serialization.JsonSerializerInternalBase.TraceWriter, Newtonsoft.Json.JsonWriter.WritePropertyName(), and Newtonsoft.Json.JsonWriter.WriteValue().
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializePrimitive(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.WriteObjectStart(), and Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.WriteStartArray().