Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.ShouldWriteDynamicProperty
ShouldWriteDynamicProperty()
bool Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.ShouldWriteDynamicProperty (object memberValue) inline private
Definition at line 779 of file JsonSerializerInternalWriter.cs.
        {
            return (this.Serializer._nullValueHandling != NullValueHandling.Ignore || memberValue != null) && (!this.HasFlag(this.Serializer._defaultValueHandling, DefaultValueHandling.Ignore) || (memberValue != null && !MiscellaneousUtils.ValueEquals(memberValue, ReflectionUtils.GetDefaultValue(memberValue.GetType()))));
        }
References Newtonsoft.Json.JsonSerializer._defaultValueHandling, Newtonsoft.Json.JsonSerializer._nullValueHandling, Newtonsoft.Json.Utilities.ReflectionUtils.GetDefaultValue(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.HasFlag(), Newtonsoft.Json.Serialization.JsonSerializerInternalBase.Serializer, and Newtonsoft.Json.Utilities.MiscellaneousUtils.ValueEquals().
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDynamic().