Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.WriteObjectStart
WriteObjectStart()
void Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.WriteObjectStart (JsonWriter writer, object value, JsonContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty) inline private
Definition at line 451 of file JsonSerializerInternalWriter.cs.
        {
            writer.WriteStartObject();
            if ((this.ResolveIsReference(contract, member, collectionContract, containerProperty) ?? this.HasFlag(this.Serializer._preserveReferencesHandling, PreserveReferencesHandling.Objects)) && (member == null || member.Writable || this.HasCreatorParameter(collectionContract, member)))
            {
                this.WriteReferenceIdProperty(writer, contract.UnderlyingType, value);
            }
            if (this.ShouldWriteType(TypeNameHandling.Objects, contract, member, collectionContract, containerProperty))
            {
                this.WriteTypeProperty(writer, contract.UnderlyingType);
            }
        }
References Newtonsoft.Json.JsonSerializer._preserveReferencesHandling, Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.HasFlag(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.ResolveIsReference(), Newtonsoft.Json.Serialization.JsonSerializerInternalBase.Serializer, Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.ShouldWriteType(), Newtonsoft.Json.Serialization.JsonContract.UnderlyingType, System.value, Newtonsoft.Json.Serialization.JsonProperty.Writable, Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.WriteReferenceIdProperty(), Newtonsoft.Json.JsonWriter.WriteStartObject(), and Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.WriteTypeProperty().
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDictionary(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDynamic(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeISerializable(), and Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject().