Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeMultidimensionalArray
SerializeMultidimensionalArray() [2/2]
void Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeMultidimensionalArray (JsonWriter writer, Array values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty) inline private
Definition at line 586 of file JsonSerializerInternalWriter.cs.
        {
            this.OnSerializing(writer, contract, values);
            this._serializeStack.Add(values);
            bool flag = this.WriteStartArray(writer, values, contract, member, collectionContract, containerProperty);
            this.SerializeMultidimensionalArray(writer, values, contract, member, writer.Top, CollectionUtils.ArrayEmpty<int>());
            if (flag)
            {
                writer.WriteEndObject();
            }
            this._serializeStack.RemoveAt(this._serializeStack.Count - 1);
            this.OnSerialized(writer, contract, values);
        }
References Newtonsoft.Json.Serialization.JsonSerializerInternalWriter._serializeStack, System.Collections.Generic.List< T >.Add(), System.Collections.Generic.List< T >.Count, Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.OnSerialized(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.OnSerializing(), System.Collections.Generic.List< T >.RemoveAt(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeMultidimensionalArray(), Newtonsoft.Json.JsonWriter.Top, System.values, Newtonsoft.Json.JsonWriter.WriteEndObject(), and Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.WriteStartArray().
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeMultidimensionalArray(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeMultidimensionalArray(), and Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue().