Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize
Serialize()
void Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize (JsonWriter jsonWriter, object value, Type objectType) inline
Definition at line 26 of file JsonSerializerInternalWriter.cs.
        {
            if (jsonWriter == null)
            {
                throw new ArgumentNullException("jsonWriter");
            }
            this._rootType = objectType;
            this._rootLevel = this._serializeStack.Count + 1;
            JsonContract contractSafe = this.GetContractSafe(value);
            try
            {
                if (this.ShouldWriteReference(value, null, contractSafe, null, null))
                {
                    this.WriteReference(jsonWriter, value);
                }
                else
                {
                    this.SerializeValue(jsonWriter, value, contractSafe, null, null, null);
                }
            }
            catch (Exception ex)
            {
                if (!base.IsErrorHandled(null, contractSafe, null, null, jsonWriter.Path, ex))
                {
                    base.ClearErrorContext();
                    throw;
                }
                this.HandleError(jsonWriter, 0);
            }
            finally
            {
                this._rootType = null;
            }
        }
References Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.GetContractSafe(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.HandleError(), Newtonsoft.Json.JsonWriter.Path, Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.ShouldWriteReference(), System.value, and Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.WriteReference().
Referenced by Newtonsoft.Json.JsonSerializer.SerializeInternal(), and Newtonsoft.Json.Serialization.JsonSerializerProxy.SerializeInternal().