Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.WriteStartArray
WriteStartArray()
bool Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.WriteStartArray (JsonWriter writer, object values, JsonArrayContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty) inline private
Definition at line 653 of file JsonSerializerInternalWriter.cs.
        {
            bool flag = this.ResolveIsReference(contract, member, containerContract, containerProperty) ?? this.HasFlag(this.Serializer._preserveReferencesHandling, PreserveReferencesHandling.Arrays);
            flag = flag && (member == null || member.Writable || this.HasCreatorParameter(containerContract, member));
            bool flag2 = this.ShouldWriteType(TypeNameHandling.Arrays, contract, member, containerContract, containerProperty);
            bool flag3 = flag || flag2;
            if (flag3)
            {
                writer.WriteStartObject();
                if (flag)
                {
                    this.WriteReferenceIdProperty(writer, contract.UnderlyingType, values);
                }
                if (flag2)
                {
                    this.WriteTypeProperty(writer, values.GetType());
                }
                writer.WritePropertyName("$values", false);
            }
            if (contract.ItemContract == null)
            {
                contract.ItemContract = this.Serializer._contractResolver.ResolveContract(contract.CollectionItemType ?? typeof(object));
            }
            return flag3;
        }
References Newtonsoft.Json.JsonSerializer._contractResolver, Newtonsoft.Json.JsonSerializer._preserveReferencesHandling, Newtonsoft.Json.Serialization.JsonArrayContract.CollectionItemType, Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.HasCreatorParameter(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.HasFlag(), Newtonsoft.Json.Serialization.JsonContainerContract.ItemContract, Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.ResolveIsReference(), Newtonsoft.Json.Serialization.JsonSerializerInternalBase.Serializer, Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.ShouldWriteType(), Newtonsoft.Json.Serialization.JsonContract.UnderlyingType, System.values, Newtonsoft.Json.JsonWriter.WritePropertyName(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.WriteReferenceIdProperty(), Newtonsoft.Json.JsonWriter.WriteStartObject(), and Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.WriteTypeProperty().
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(), and Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeMultidimensionalArray().