Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.ShouldWriteType
ShouldWriteType()
bool Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.ShouldWriteType (TypeNameHandling typeNameHandlingFlag, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty) inline private
Definition at line 785 of file JsonSerializerInternalWriter.cs.
        {
            TypeNameHandling typeNameHandling = ((member != null) ? member.TypeNameHandling : default(TypeNameHandling?)) ?? ((containerProperty != null) ? containerProperty.ItemTypeNameHandling : default(TypeNameHandling?)) ?? ((containerContract != null) ? containerContract.ItemTypeNameHandling : default(TypeNameHandling?)) ?? this.Serializer._typeNameHandling;
            if (this.HasFlag(typeNameHandling, typeNameHandlingFlag))
            {
                return true;
            }
            if (this.HasFlag(typeNameHandling, TypeNameHandling.Auto))
            {
                if (member != null)
                {
                    if (contract.NonNullableUnderlyingType != member.PropertyContract.CreatedType)
                    {
                        return true;
                    }
                }
                else if (containerContract != null)
                {
                    if (containerContract.ItemContract == null || contract.NonNullableUnderlyingType != containerContract.ItemContract.CreatedType)
                    {
                        return true;
                    }
                }
                else if (this._rootType != null && this._serializeStack.Count == this._rootLevel)
                {
                    JsonContract jsonContract = this.Serializer._contractResolver.ResolveContract(this._rootType);
                    if (contract.NonNullableUnderlyingType != jsonContract.CreatedType)
                    {
                        return true;
                    }
                }
            }
            return false;
        }
References Newtonsoft.Json.JsonSerializer._contractResolver, Newtonsoft.Json.Serialization.JsonSerializerInternalWriter._rootType, Newtonsoft.Json.Serialization.JsonSerializerInternalWriter._serializeStack, Newtonsoft.Json.JsonSerializer._typeNameHandling, System.Collections.Generic.List< T >.Count, Newtonsoft.Json.Serialization.JsonContract.CreatedType, Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.HasFlag(), Newtonsoft.Json.Serialization.JsonContainerContract.ItemContract, Newtonsoft.Json.Serialization.JsonContract.NonNullableUnderlyingType, Newtonsoft.Json.Serialization.JsonProperty.PropertyContract, Newtonsoft.Json.Serialization.JsonSerializerInternalBase.Serializer, and Newtonsoft.Json.Serialization.JsonProperty.TypeNameHandling.
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.WriteObjectStart(), and Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.WriteStartArray().