Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.WriteReference
WriteReference()
void Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.WriteReference (JsonWriter writer, object value) inline private
Definition at line 272 of file JsonSerializerInternalWriter.cs.
        {
            string reference = this.GetReference(writer, value);
            if (this.TraceWriter != null && this.TraceWriter.LevelFilter >= 3)
            {
                this.TraceWriter.Trace(3, JsonPosition.FormatMessage(null, writer.Path, "Writing object reference to Id '{0}' for {1}.".FormatWith(CultureInfo.InvariantCulture, reference, value.GetType())), null);
            }
            writer.WriteStartObject();
            writer.WritePropertyName("$ref", false);
            writer.WriteValue(reference);
            writer.WriteEndObject();
        }
References Newtonsoft.Json.JsonPosition.FormatMessage(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.GetReference(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.Serialization.ITraceWriter.LevelFilter, Newtonsoft.Json.JsonWriter.Path, Newtonsoft.Json.Serialization.ITraceWriter.Trace(), Newtonsoft.Json.Serialization.JsonSerializerInternalBase.TraceWriter, System.value, Newtonsoft.Json.JsonWriter.WriteEndObject(), Newtonsoft.Json.JsonWriter.WritePropertyName(), Newtonsoft.Json.JsonWriter.WriteStartObject(), and Newtonsoft.Json.JsonWriter.WriteValue().
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDictionary(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeISerializable(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeMultidimensionalArray(), and Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject().