Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject
SerializeObject()
void Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject (JsonWriter writer, object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty) inline private
Definition at line 350 of file JsonSerializerInternalWriter.cs.
        {
            this.OnSerializing(writer, contract, value);
            this._serializeStack.Add(value);
            this.WriteObjectStart(writer, value, contract, member, collectionContract, containerProperty);
            int top = writer.Top;
            for (int i = 0; i < contract.Properties.Count; i++)
            {
                JsonProperty jsonProperty = contract.Properties[i];
                try
                {
                    JsonContract jsonContract;
                    object obj;
                    if (this.CalculatePropertyValues(writer, value, contract, member, jsonProperty, out jsonContract, out obj))
                    {
                        jsonProperty.WritePropertyName(writer);
                        this.SerializeValue(writer, obj, jsonContract, jsonProperty, contract, member);
                    }
                }
                catch (Exception ex)
                {
                    if (!base.IsErrorHandled(value, contract, jsonProperty.PropertyName, null, writer.ContainerPath, ex))
                    {
                        throw;
                    }
                    this.HandleError(writer, top);
                }
            }
            ExtensionDataGetter extensionDataGetter = contract.ExtensionDataGetter;
            IEnumerable<KeyValuePair<object, object>> enumerable = ((extensionDataGetter != null) ? extensionDataGetter(value) : null);
            if (enumerable != null)
            {
                foreach (KeyValuePair<object, object> keyValuePair in enumerable)
                {
                    JsonContract contractSafe = this.GetContractSafe(keyValuePair.Key);
                    JsonContract contractSafe2 = this.GetContractSafe(keyValuePair.Value);
                    bool flag;
                    string text = this.GetPropertyName(writer, keyValuePair.Key, contractSafe, out flag);
                    text = ((contract.ExtensionDataNameResolver != null) ? contract.ExtensionDataNameResolver.Invoke(text) : text);
                    if (this.ShouldWriteReference(keyValuePair.Value, null, contractSafe2, contract, member))
                    {
                        writer.WritePropertyName(text);
                        this.WriteReference(writer, keyValuePair.Value);
                    }
                    else if (this.CheckForCircularReference(writer, keyValuePair.Value, null, contractSafe2, contract, member))
                    {
                        writer.WritePropertyName(text);
                        this.SerializeValue(writer, keyValuePair.Value, contractSafe2, null, contract, member);
                    }
                }
            }
            writer.WriteEndObject();
            this._serializeStack.RemoveAt(this._serializeStack.Count - 1);
            this.OnSerialized(writer, contract, value);
        }
References Newtonsoft.Json.Serialization.JsonSerializerInternalWriter._serializeStack, System.Collections.Generic.List< T >.Add(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(), Newtonsoft.Json.JsonWriter.ContainerPath, System.Collections.Generic.List< T >.Count, Newtonsoft.Json.Serialization.ExtensionDataGetter(), Newtonsoft.Json.Serialization.JsonObjectContract.ExtensionDataGetter, Newtonsoft.Json.Serialization.JsonObjectContract.ExtensionDataNameResolver, Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.GetContractSafe(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.GetPropertyName(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.HandleError(), System.Collections.Generic.KeyValuePair< TKey, TValue >.Key, System.obj, Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.OnSerialized(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.OnSerializing(), Newtonsoft.Json.Serialization.JsonObjectContract.Properties, Newtonsoft.Json.Serialization.JsonProperty.PropertyName, System.Collections.Generic.List< T >.RemoveAt(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.ShouldWriteReference(), System.text, Newtonsoft.Json.JsonWriter.Top, System.Collections.Generic.KeyValuePair< TKey, TValue >.Value, System.value, Newtonsoft.Json.JsonWriter.WriteEndObject(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.WriteObjectStart(), Newtonsoft.Json.Serialization.JsonProperty.WritePropertyName(), Newtonsoft.Json.JsonWriter.WritePropertyName(), and Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.WriteReference().
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue().