Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.ShouldWriteReference
ShouldWriteReference()
bool Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.ShouldWriteReference (object value, JsonProperty property, JsonContract valueContract, JsonContainerContract collectionContract, JsonProperty containerProperty) inline private
Definition at line 191 of file JsonSerializerInternalWriter.cs.
        {
            if (value == null)
            {
                return false;
            }
            if (valueContract.ContractType == JsonContractType.Primitive || valueContract.ContractType == JsonContractType.String)
            {
                return false;
            }
            bool? flag = this.ResolveIsReference(valueContract, property, collectionContract, containerProperty);
            if (flag == null)
            {
                if (valueContract.ContractType == JsonContractType.Array)
                {
                    flag = new bool?(this.HasFlag(this.Serializer._preserveReferencesHandling, PreserveReferencesHandling.Arrays));
                }
                else
                {
                    flag = new bool?(this.HasFlag(this.Serializer._preserveReferencesHandling, PreserveReferencesHandling.Objects));
                }
            }
            return flag.GetValueOrDefault() && this.Serializer.GetReferenceResolver().IsReferenced(this, value);
        }
References Newtonsoft.Json.JsonSerializer._preserveReferencesHandling, Newtonsoft.Json.Serialization.JsonContract.ContractType, Newtonsoft.Json.JsonSerializer.GetReferenceResolver(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.HasFlag(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.ResolveIsReference(), Newtonsoft.Json.Serialization.JsonSerializerInternalBase.Serializer, and System.value.
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDictionary(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeISerializable(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeMultidimensionalArray(), and Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject().