Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.GetReference
GetReference()
string Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.GetReference (JsonWriter writer, object value) inline private
Definition at line 286 of file JsonSerializerInternalWriter.cs.
        {
            string reference;
            try
            {
                reference = this.Serializer.GetReferenceResolver().GetReference(this, value);
            }
            catch (Exception ex)
            {
                throw JsonSerializationException.Create(null, writer.ContainerPath, "Error writing object reference for '{0}'.".FormatWith(CultureInfo.InvariantCulture, value.GetType()), ex);
            }
            return reference;
        }
References Newtonsoft.Json.JsonWriter.ContainerPath, Newtonsoft.Json.JsonSerializationException.Create(), Newtonsoft.Json.JsonSerializer.GetReferenceResolver(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.Serialization.JsonSerializerInternalBase.Serializer, and System.value.
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.WriteReference(), and Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.WriteReferenceIdProperty().