Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.TryConvertToString
TryConvertToString()
static bool Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.TryConvertToString (object value, Type type, out string s) inline static package
Definition at line 301 of file JsonSerializerInternalWriter.cs.
        {
            TypeConverter typeConverter;
            if (JsonTypeReflector.CanTypeDescriptorConvertString(type, out typeConverter))
            {
                s = typeConverter.ConvertToInvariantString(value);
                return true;
            }
            type = value as Type;
            if (type != null)
            {
                s = type.AssemblyQualifiedName;
                return true;
            }
            s = null;
            return false;
        }
References System.Type.AssemblyQualifiedName, Newtonsoft.Json.Serialization.JsonTypeReflector.CanTypeDescriptorConvertString(), System.s, and System.value.
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.GetPropertyName(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeString(), and Newtonsoft.Json.Converters.EntityKeyMemberConverter.WriteJson().