Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDynamic
SerializeDynamic()
void Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDynamic (JsonWriter writer, IDynamicMetaObjectProvider value, JsonDynamicContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty) inline private
Definition at line 714 of file JsonSerializerInternalWriter.cs.
        {
            this.OnSerializing(writer, contract, value);
            this._serializeStack.Add(value);
            this.WriteObjectStart(writer, value, contract, member, collectionContract, containerProperty);
            int top = writer.Top;
            for (int i = 0; i < contract.Properties.Count; i++)
            {
                JsonProperty jsonProperty = contract.Properties[i];
                if (jsonProperty.HasMemberAttribute)
                {
                    try
                    {
                        JsonContract jsonContract;
                        object obj;
                        if (this.CalculatePropertyValues(writer, value, contract, member, jsonProperty, out jsonContract, out obj))
{
                            jsonProperty.WritePropertyName(writer);
                            this.SerializeValue(writer, obj, jsonContract, jsonProperty, contract, member);
                        }
                    }
                    catch (Exception ex)
                    {
                        if (!base.IsErrorHandled(value, contract, jsonProperty.PropertyName, null, writer.ContainerPath, ex))
{
                            throw;
                        }
                        this.HandleError(writer, top);
                    }
                }
            }
            foreach (string text in value.GetDynamicMemberNames())
            {
                object obj2;
                if (contract.TryGetMember(value, text, out obj2))
                {
                    try
                    {
                        JsonContract contractSafe = this.GetContractSafe(obj2);
                        if (this.ShouldWriteDynamicProperty(obj2))
{
                            if (this.CheckForCircularReference(writer, obj2, null, contractSafe, contract, member))
{
                                string text2 = ((contract.PropertyNameResolver != null) ? contract.PropertyNameResolver.Invoke(text) : text);
                                writer.WritePropertyName(text2);
                                this.SerializeValue(writer, obj2, contractSafe, null, contract, member);
                            }
                        }
                    }
                    catch (Exception ex2)
                    {
                        if (!base.IsErrorHandled(value, contract, text, null, writer.ContainerPath, ex2))
{
                            throw;
                        }
                        this.HandleError(writer, top);
                    }
                }
            }
            writer.WriteEndObject();
            this._serializeStack.RemoveAt(this._serializeStack.Count - 1);
            this.OnSerialized(writer, contract, value);
        }
References Newtonsoft.Json.Serialization.JsonSerializerInternalWriter._serializeStack, System.Collections.Generic.List< T >.Add(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(), Newtonsoft.Json.JsonWriter.ContainerPath, System.Collections.Generic.List< T >.Count, Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.GetContractSafe(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.HandleError(), Newtonsoft.Json.Serialization.JsonProperty.HasMemberAttribute, System.obj, Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.OnSerialized(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.OnSerializing(), Newtonsoft.Json.Serialization.JsonDynamicContract.Properties, Newtonsoft.Json.Serialization.JsonProperty.PropertyName, System.Collections.Generic.List< T >.RemoveAt(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.ShouldWriteDynamicProperty(), System.text, Newtonsoft.Json.JsonWriter.Top, System.value, Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.WriteObjectStart(), and Newtonsoft.Json.Serialization.JsonProperty.WritePropertyName().
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue().