Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue
SerializeValue()
void Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue (JsonWriter writer, object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty) inline private
Definition at line 97 of file JsonSerializerInternalWriter.cs.
        {
            if (value == null)
            {
                writer.WriteNull();
                return;
            }
            JsonConverter jsonConverter;
            if ((jsonConverter = ((member != null) ? member.Converter : null)) == null && (jsonConverter = ((containerProperty != null) ? containerProperty.ItemConverter : null)) == null && (jsonConverter = ((containerContract != null) ? containerContract.ItemConverter : null)) == null && (jsonConverter = valueContract.Converter) == null)
            {
                jsonConverter = this.Serializer.GetMatchingConverter(valueContract.UnderlyingType) ?? valueContract.InternalConverter;
            }
            JsonConverter jsonConverter2 = jsonConverter;
            if (jsonConverter2 != null && jsonConverter2.CanWrite)
            {
                this.SerializeConvertable(writer, jsonConverter2, value, valueContract, containerContract, containerProperty);
                return;
            }
            switch (valueContract.ContractType)
            {
            case JsonContractType.Object:
                this.SerializeObject(writer, value, (JsonObjectContract)valueContract, member, containerContract, containerProperty);
                return;
            case JsonContractType.Array:
            {
                JsonArrayContract jsonArrayContract = (JsonArrayContract)valueContract;
                if (!jsonArrayContract.IsMultidimensionalArray)
                {
                    this.SerializeList(writer, (IEnumerable)value, jsonArrayContract, member, containerContract, containerProperty);
                    return;
                }
                this.SerializeMultidimensionalArray(writer, (Array)value, jsonArrayContract, member, containerContract, containerProperty);
                return;
            }
            case JsonContractType.Primitive:
                this.SerializePrimitive(writer, value, (JsonPrimitiveContract)valueContract, member, containerContract, containerProperty);
                return;
            case JsonContractType.String:
                this.SerializeString(writer, value, (JsonStringContract)valueContract);
                return;
            case JsonContractType.Dictionary:
            {
                JsonDictionaryContract jsonDictionaryContract = (JsonDictionaryContract)valueContract;
                IDictionary dictionary2;
                if (!(value is IDictionary))
                {
                    IDictionary dictionary = jsonDictionaryContract.CreateWrapper(value);
                    dictionary2 = dictionary;
                }
                else
                {
                    dictionary2 = (IDictionary)value;
                }
                this.SerializeDictionary(writer, dictionary2, jsonDictionaryContract, member, containerContract, containerProperty);
                return;
            }
            case JsonContractType.Dynamic:
                this.SerializeDynamic(writer, (IDynamicMetaObjectProvider)value, (JsonDynamicContract)valueContract, member, containerContract, containerProperty);
                return;
            case JsonContractType.Serializable:
                this.SerializeISerializable(writer, (ISerializable)value, (JsonISerializableContract)valueContract, member, containerContract, containerProperty);
                return;
            case JsonContractType.Linq:
                ((JToken)value).WriteTo(writer, Enumerable.ToArray<JsonConverter>(this.Serializer.Converters));
                return;
            default:
                return;
            }
        }
References Newtonsoft.Json.JsonConverter.CanWrite, Newtonsoft.Json.Serialization.JsonContract.ContractType, Newtonsoft.Json.Serialization.JsonContract.Converter, Newtonsoft.Json.Serialization.JsonProperty.Converter, Newtonsoft.Json.Serialization.JsonDictionaryContract.CreateWrapper(), System.dictionary, Newtonsoft.Json.JsonSerializer.GetMatchingConverter(), Newtonsoft.Json.Serialization.JsonContract.InternalConverter, Newtonsoft.Json.Serialization.JsonArrayContract.IsMultidimensionalArray, Newtonsoft.Json.Serialization.JsonContainerContract.ItemConverter, Newtonsoft.Json.Serialization.JsonProperty.ItemConverter, Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDictionary(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDynamic(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeISerializable(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeMultidimensionalArray(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializePrimitive(), Newtonsoft.Json.Serialization.JsonSerializerInternalBase.Serializer, Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeString(), Newtonsoft.Json.Serialization.JsonContract.UnderlyingType, System.value, and Newtonsoft.Json.JsonWriter.WriteNull().
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDictionary(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDynamic(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeISerializable(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeMultidimensionalArray(), and Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject().