Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues
CalculatePropertyValues()
bool Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues (JsonWriter writer, object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, out JsonContract memberContract, out object memberValue) inline private
Definition at line 407 of file JsonSerializerInternalWriter.cs.
        {
            if (!property.Ignored && property.Readable && this.ShouldSerialize(writer, property, value) && this.IsSpecified(writer, property, value))
            {
                if (property.PropertyContract == null)
                {
                    property.PropertyContract = this.Serializer._contractResolver.ResolveContract(property.PropertyType);
                }
                memberValue = property.ValueProvider.GetValue(value);
                memberContract = (property.PropertyContract.IsSealed ? property.PropertyContract : this.GetContractSafe(memberValue));
                if (this.ShouldWriteProperty(memberValue, property))
                {
                    if (this.ShouldWriteReference(memberValue, property, memberContract, contract, member))
                    {
                        property.WritePropertyName(writer);
                        this.WriteReference(writer, memberValue);
                        return false;
                    }
                    if (!this.CheckForCircularReference(writer, memberValue, property, memberContract, contract, member))
                    {
                        return false;
                    }
                    if (memberValue == null)
                    {
                        JsonObjectContract jsonObjectContract = contract as JsonObjectContract;
                        Required required = property._required ?? ((jsonObjectContract != null) ? jsonObjectContract.ItemRequired : default(Required?)) ?? Required.Default;
                        if (required == Required.Always)
{
                            throw JsonSerializationException.Create(null, writer.ContainerPath, "Cannot write a null value for property '{0}'. Property requires a value.".FormatWith(CultureInfo.InvariantCulture, property.PropertyName), null);
                        }
                        if (required == Required.DisallowNull)
{
                            throw JsonSerializationException.Create(null, writer.ContainerPath, "Cannot write a null value for property '{0}'. Property requires a non-null value.".FormatWith(CultureInfo.InvariantCulture, property.PropertyName), null);
                        }
                    }
                    return true;
                }
            }
            memberContract = null;
            memberValue = null;
            return false;
        }
References Newtonsoft.Json.JsonSerializer._contractResolver, Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(), Newtonsoft.Json.JsonWriter.ContainerPath, Newtonsoft.Json.JsonSerializationException.Create(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.GetContractSafe(), Newtonsoft.Json.Serialization.JsonProperty.Ignored, System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.Serialization.JsonObjectContract.ItemRequired, Newtonsoft.Json.Serialization.JsonProperty.PropertyContract, Newtonsoft.Json.Serialization.JsonProperty.PropertyName, Newtonsoft.Json.Serialization.JsonProperty.PropertyType, Newtonsoft.Json.Serialization.JsonProperty.Readable, Newtonsoft.Json.Serialization.JsonSerializerInternalBase.Serializer, Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.ShouldWriteProperty(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.ShouldWriteReference(), System.value, and Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.WriteReference().
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDynamic(), and Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject().