Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeMultidimensionalArray
SerializeMultidimensionalArray() [1/2]
void Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeMultidimensionalArray (JsonWriter writer, Array values, JsonArrayContract contract, JsonProperty member, int initialDepth, int[] indices) inline private
Definition at line 601 of file JsonSerializerInternalWriter.cs.
        {
            int num = indices.Length;
            int[] array = new int[num + 1];
            for (int i = 0; i < num; i++)
            {
                array[i] = indices[i];
            }
            writer.WriteStartArray();
            int j = values.GetLowerBound(num);
            while (j <= values.GetUpperBound(num))
            {
                array[num] = j;
                if (array.Length == values.Rank)
                {
                    object value = values.GetValue(array);
                    try
                    {
                        JsonContract jsonContract = contract.FinalItemContract ?? this.GetContractSafe(value);
                        if (this.ShouldWriteReference(value, null, jsonContract, contract, member))
{
                            this.WriteReference(writer, value);
                        }
                        else if (this.CheckForCircularReference(writer, value, null, jsonContract, contract, member))
{
                            this.SerializeValue(writer, value, jsonContract, null, contract, member);
                        }
                        goto IL_00DE;
                    }
                    catch (Exception ex)
                    {
                        if (base.IsErrorHandled(values, contract, j, null, writer.ContainerPath, ex))
{
                            this.HandleError(writer, initialDepth + 1);
                            goto IL_00DE;
                        }
                        throw;
                    }
                    goto IL_00CE;
                }
                goto IL_00CE;
                IL_00DE:
                j++;
                continue;
                IL_00CE:
                this.SerializeMultidimensionalArray(writer, values, contract, member, initialDepth + 1, array);
                goto IL_00DE;
            }
            writer.WriteEndArray();
        }
References System.array, Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(), Newtonsoft.Json.JsonWriter.ContainerPath, Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.GetContractSafe(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.HandleError(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeMultidimensionalArray(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.ShouldWriteReference(), System.value, System.values, Newtonsoft.Json.JsonWriter.WriteEndArray(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.WriteReference(), and Newtonsoft.Json.JsonWriter.WriteStartArray().