Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList
SerializeList()
void Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList (JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty) inline private
Definition at line 539 of file JsonSerializerInternalWriter.cs.
        {
            IWrappedCollection wrappedCollection = values as IWrappedCollection;
            object obj = ((wrappedCollection != null) ? wrappedCollection.UnderlyingCollection : values);
            this.OnSerializing(writer, contract, obj);
            this._serializeStack.Add(obj);
            bool flag = this.WriteStartArray(writer, obj, contract, member, collectionContract, containerProperty);
            writer.WriteStartArray();
            int top = writer.Top;
            int num = 0;
            foreach (object obj2 in values)
            {
                try
                {
                    JsonContract jsonContract = contract.FinalItemContract ?? this.GetContractSafe(obj2);
                    if (this.ShouldWriteReference(obj2, null, jsonContract, contract, member))
                    {
                        this.WriteReference(writer, obj2);
                    }
                    else if (this.CheckForCircularReference(writer, obj2, null, jsonContract, contract, member))
                    {
                        this.SerializeValue(writer, obj2, jsonContract, null, contract, member);
                    }
                }
                catch (Exception ex)
                {
                    if (!base.IsErrorHandled(obj, contract, num, null, writer.ContainerPath, ex))
                    {
                        throw;
                    }
                    this.HandleError(writer, top);
                }
                finally
                {
                    num++;
                }
            }
            writer.WriteEndArray();
            if (flag)
            {
                writer.WriteEndObject();
            }
            this._serializeStack.RemoveAt(this._serializeStack.Count - 1);
            this.OnSerialized(writer, contract, obj);
        }
References Newtonsoft.Json.Serialization.JsonSerializerInternalWriter._serializeStack, System.Collections.Generic.List< T >.Add(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(), System.Collections.Generic.List< T >.Count, Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.GetContractSafe(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.HandleError(), System.obj, Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.OnSerialized(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.OnSerializing(), System.Collections.Generic.List< T >.RemoveAt(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.ShouldWriteReference(), Newtonsoft.Json.JsonWriter.Top, Newtonsoft.Json.Utilities.IWrappedCollection.UnderlyingCollection, System.values, Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.WriteReference(), Newtonsoft.Json.JsonWriter.WriteStartArray(), and Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.WriteStartArray().
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue().