Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeString
SerializeString()
void Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeString (JsonWriter writer, object value, JsonStringContract contract) inline private
Definition at line 320 of file JsonSerializerInternalWriter.cs.
        {
            this.OnSerializing(writer, contract, value);
            string text;
            JsonSerializerInternalWriter.TryConvertToString(value, contract.UnderlyingType, out text);
            writer.WriteValue(text);
            this.OnSerialized(writer, contract, value);
        }
References Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.OnSerialized(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.OnSerializing(), System.text, Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.TryConvertToString(), Newtonsoft.Json.Serialization.JsonContract.UnderlyingType, System.value, and Newtonsoft.Json.JsonWriter.WriteValue().
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue().