Terraria Decompiled: System.Security.Claims.ClaimsPrincipal.SerializeIdentities
SerializeIdentities()
string System.Security.Claims.ClaimsPrincipal.SerializeIdentities () inline private
Definition at line 286 of file ClaimsPrincipal.cs.
        {
            List<string> list = new List<string>();
            BinaryFormatter binaryFormatter = new BinaryFormatter();
            foreach (ClaimsIdentity claimsIdentity in this.m_identities)
            {
                if (claimsIdentity.GetType() == typeof(WindowsIdentity))
                {
                    WindowsIdentity windowsIdentity = claimsIdentity as WindowsIdentity;
                    list.Add(windowsIdentity.GetTokenInternal().ToInt64().ToString(NumberFormatInfo.InvariantInfo));
                    using (MemoryStream memoryStream = new MemoryStream())
                    {
                        binaryFormatter.Serialize(memoryStream, windowsIdentity.CloneAsBase(), null, false);
                        list.Add(Convert.ToBase64String(memoryStream.GetBuffer(), 0, (int)memoryStream.Length));
                        continue;
                    }
                }
                using (MemoryStream memoryStream2 = new MemoryStream())
                {
                    list.Add("");
                    binaryFormatter.Serialize(memoryStream2, claimsIdentity, null, false);
                    list.Add(Convert.ToBase64String(memoryStream2.GetBuffer(), 0, (int)memoryStream2.Length));
                }
            }
            string text;
            using (MemoryStream memoryStream3 = new MemoryStream())
            {
                binaryFormatter.Serialize(memoryStream3, list, null, false);
                text = Convert.ToBase64String(memoryStream3.GetBuffer(), 0, (int)memoryStream3.Length);
            }
            return text;
        }
References System.Security.Principal.WindowsIdentity.CloneAsBase(), System.IO.MemoryStream.GetBuffer(), System.Security.Principal.WindowsIdentity.GetTokenInternal(), int, System.Globalization.NumberFormatInfo.InvariantInfo, System.IO.MemoryStream.Length, System.list, System.Security.Claims.ClaimsPrincipal.m_identities, System.text, System.Convert.ToBase64String(), and System.IntPtr.ToInt64().
Referenced by System.Security.Claims.ClaimsPrincipal.GetObjectData(), and System.Security.Claims.ClaimsPrincipal.OnSerializingMethod().