Terraria Decompiled: System.Security.Claims.ClaimsPrincipal.Deserialize
Deserialize()
void System.Security.Claims.ClaimsPrincipal.Deserialize (SerializationInfo info, StreamingContext context) inline private
Definition at line 226 of file ClaimsPrincipal.cs.
        {
            if (info == null)
            {
                throw new ArgumentNullException("info");
            }
            SerializationInfoEnumerator enumerator = info.GetEnumerator();
            while (enumerator.MoveNext())
            {
                string name = enumerator.Name;
                if (!(name == "System.Security.ClaimsPrincipal.Identities"))
                {
                    if (name == "System.Security.ClaimsPrincipal.Version")
                    {
                        this.m_version = info.GetString("System.Security.ClaimsPrincipal.Version");
                    }
                }
                else
                {
                    this.DeserializeIdentities(info.GetString("System.Security.ClaimsPrincipal.Identities"));
                }
            }
        }
References System.Security.Claims.ClaimsPrincipal.DeserializeIdentities(), System.Runtime.Serialization.SerializationInfo.GetString(), System.info, System.Runtime.Serialization.SerializationInfoEnumerator.MoveNext(), System.name, and System.Runtime.Serialization.SerializationInfoEnumerator.Name.
Referenced by System.Security.Claims.ClaimsPrincipal.ClaimsPrincipal().