Terraria Decompiled: System.Security.Claims.ClaimsPrincipal.DeserializeIdentities
DeserializeIdentities()
void System.Security.Claims.ClaimsPrincipal.DeserializeIdentities (string identities) inline private
Definition at line 252 of file ClaimsPrincipal.cs.
        {
            this.m_identities = new List<ClaimsIdentity>();
            if (!string.IsNullOrEmpty(identities))
            {
                List<string> list = null;
                BinaryFormatter binaryFormatter = new BinaryFormatter();
                using (MemoryStream memoryStream = new MemoryStream(Convert.FromBase64String(identities)))
                {
                    list = (List<string>)binaryFormatter.Deserialize(memoryStream, null, false);
                    for (int i = 0; i < list.Count; i += 2)
                    {
                        ClaimsIdentity claimsIdentity = null;
                        using (MemoryStream memoryStream2 = new MemoryStream(Convert.FromBase64String(list[i + 1])))
{
                            claimsIdentity = (ClaimsIdentity)binaryFormatter.Deserialize(memoryStream2, null, false);
                        }
                        if (!string.IsNullOrEmpty(list[i]))
{
                            long num;
                            if (!long.TryParse(list[i], NumberStyles.Integer, NumberFormatInfo.InvariantInfo, out num))
{
                                throw new SerializationException(Environment.GetResourceString("Invalid BinaryFormatter stream."));
                            }
                            claimsIdentity = new WindowsIdentity(claimsIdentity, new IntPtr(num));
                        }
                        this.m_identities.Add(claimsIdentity);
                    }
                }
            }
        }
References System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(), System.Convert.FromBase64String(), System.Environment.GetResourceString(), System.Globalization.NumberFormatInfo.InvariantInfo, System.list, and System.Security.Claims.ClaimsPrincipal.m_identities.
Referenced by System.Security.Claims.ClaimsPrincipal.Deserialize(), and System.Security.Claims.ClaimsPrincipal.OnDeserializedMethod().