Terraria Decompiled: System.Security.Claims.ClaimsPrincipal.WriteTo
WriteTo() [2/2]
virtual void System.Security.Claims.ClaimsPrincipal.WriteTo (BinaryWriter writer, byte[] userData) inline protected virtual
Definition at line 574 of file ClaimsPrincipal.cs.
        {
            if (writer == null)
            {
                throw new ArgumentNullException("writer");
            }
            int num = 0;
            ClaimsPrincipal.SerializationMask serializationMask = ClaimsPrincipal.SerializationMask.None;
            if (this.m_identities.Count > 0)
            {
                serializationMask |= ClaimsPrincipal.SerializationMask.HasIdentities;
                num++;
            }
            if (userData != null && userData.Length != 0)
            {
                num++;
                serializationMask |= ClaimsPrincipal.SerializationMask.UserData;
            }
            writer.Write((int)serializationMask);
            writer.Write(num);
            if ((serializationMask & ClaimsPrincipal.SerializationMask.HasIdentities) == ClaimsPrincipal.SerializationMask.HasIdentities)
            {
                writer.Write(this.m_identities.Count);
                foreach (ClaimsIdentity claimsIdentity in this.m_identities)
                {
                    claimsIdentity.WriteTo(writer);
                }
            }
            if ((serializationMask & ClaimsPrincipal.SerializationMask.UserData) == ClaimsPrincipal.SerializationMask.UserData)
            {
                writer.Write(userData.Length);
                writer.Write(userData);
            }
            writer.Flush();
        }
References System.IO.BinaryWriter.Flush(), System.Security.Claims.ClaimsPrincipal.m_identities, System.IO.BinaryWriter.Write(), and System.Security.Claims.ClaimsIdentity.WriteTo().