Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldLoad.DrawSelf
DrawSelf()
override void Terraria.GameContent.UI.States.UIWorldLoad.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 78 of file UIWorldLoad.cs.
        {
            float num = 0f;
            float num2 = 0f;
            string text = string.Empty;
            if (this._progress != null)
            {
                num = (float)this._progress.TotalProgress;
                num2 = (float)this._progress.Value;
                text = this._progress.Message;
                if (WorldGenerator.CurrentController.QueuedAbort)
                {
                    text = Language.GetTextValue("UI.Canceling");
                }
            }
            this._progressBar.SetProgress(num, num2);
            this._progressMessage.Text = text;
            if (WorldGen.drunkWorldGenText && !WorldGen.placingTraps && !WorldGen.getGoodWorldGen)
            {
                this._progressMessage.Text = string.Concat(Main.rand.Next(999999999));
                for (int i = 0; i < 3; i++)
                {
                    if (Main.rand.Next(2) == 0)
                    {
                        this._progressMessage.Text = this._progressMessage.Text + Main.rand.Next(999999999);
                    }
                }
            }
            if (WorldGen.notTheBees && !Main.zenithWorld)
            {
                this._progressMessage.Text = Language.GetTextValue("UI.WorldGenEasterEgg_GeneratingBees");
            }
            if (WorldGen.getGoodWorldGen && (!WorldGen.noTrapsWorldGen || !WorldGen.placingTraps))
            {
                string text2 = "";
                for (int j = this._progressMessage.Text.Length - 1; j >= 0; j--)
                {
                    text2 += this._progressMessage.Text.Substring(j, 1);
                }
                this._progressMessage.Text = text2;
            }
            Main.gameTips.Update();
            Main.gameTips.Draw();
            this.UpdateGamepadSquiggle();
        }
References Terraria.GameContent.UI.States.UIWorldLoad._progress, Terraria.GameContent.UI.States.UIWorldLoad._progressBar, Terraria.GameContent.UI.States.UIWorldLoad._progressMessage, Terraria.WorldBuilding.WorldGenerator.CurrentController, Terraria.WorldGen.drunkWorldGenText, Terraria.Main.gameTips, Terraria.WorldGen.getGoodWorldGen, Terraria.Localization.Language.GetTextValue(), Terraria.WorldBuilding.GenerationProgress.Message, Terraria.WorldGen.noTrapsWorldGen, Terraria.WorldGen.notTheBees, Terraria.WorldGen.placingTraps, Terraria.Main.rand, Terraria.GameContent.UI.Elements.UIGenProgressBar.SetProgress(), System.text, Terraria.GameContent.UI.Elements.UIHeader.Text, Terraria.WorldBuilding.GenerationProgress.TotalProgress, Terraria.GameContent.UI.States.UIWorldLoad.UpdateGamepadSquiggle(), Terraria.WorldBuilding.GenerationProgress.Value, and Terraria.Main.zenithWorld.