Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldLoad.UpdateGamepadSquiggle
UpdateGamepadSquiggle()
void Terraria.GameContent.UI.States.UIWorldLoad.UpdateGamepadSquiggle () inline private
Definition at line 125 of file UIWorldLoad.cs.
        {
            Vector2 vector = new Vector2((float)Math.Cos((double)(Main.GlobalTimeWrappedHourly * 6.2831855f)), (float)Math.Sin((double)(Main.GlobalTimeWrappedHourly * 6.2831855f * 2f))) * new Vector2(30f, 15f) + Vector2.UnitY * 20f;
            UILinkPointNavigator.Points[3000].Unlink();
            UILinkPointNavigator.SetPosition(3000, new Vector2((float)Main.screenWidth, (float)Main.screenHeight) / 2f + vector);
        }
References System.Math.Cos(), Terraria.Main.GlobalTimeWrappedHourly, Terraria.UI.Gamepad.UILinkPointNavigator.Points, Terraria.Main.screenHeight, Terraria.Main.screenWidth, Terraria.UI.Gamepad.UILinkPointNavigator.SetPosition(), System.Math.Sin(), and Microsoft.Xna.Framework.Graphics.Vector2.
Referenced by Terraria.GameContent.UI.States.UIWorldLoad.DrawSelf().