Terraria Decompiled: System.Runtime.Remoting.ChannelData.CopyFrom
CopyFrom()
void System.Runtime.Remoting.ChannelData.CopyFrom (ChannelData other) inline
Definition at line 52 of file ChannelData.cs.
        {
            if (this.Ref == null)
            {
                this.Ref = other.Ref;
            }
            if (this.Id == null)
            {
                this.Id = other.Id;
            }
            if (this.Type == null)
            {
                this.Type = other.Type;
            }
            if (this.DelayLoadAsClientChannel == null)
            {
                this.DelayLoadAsClientChannel = other.DelayLoadAsClientChannel;
            }
            if (other._customProperties != null)
            {
                foreach (object obj in other._customProperties)
                {
                    DictionaryEntry dictionaryEntry = (DictionaryEntry)obj;
                    if (!this.CustomProperties.ContainsKey(dictionaryEntry.Key))
                    {
                        this.CustomProperties[dictionaryEntry.Key] = dictionaryEntry.Value;
                    }
                }
            }
            if (this._serverProviders == null && other._serverProviders != null)
            {
                foreach (object obj2 in other._serverProviders)
                {
                    ProviderData providerData = (ProviderData)obj2;
                    ProviderData providerData2 = new ProviderData();
                    providerData2.CopyFrom(providerData);
                    this.ServerProviders.Add(providerData2);
                }
            }
            if (this._clientProviders == null && other._clientProviders != null)
            {
                foreach (object obj3 in other._clientProviders)
                {
                    ProviderData providerData3 = (ProviderData)obj3;
                    ProviderData providerData4 = new ProviderData();
                    providerData4.CopyFrom(providerData3);
                    this.ClientProviders.Add(providerData4);
                }
            }
        }
References System.Runtime.Remoting.ChannelData._clientProviders, System.Runtime.Remoting.ChannelData._customProperties, System.Runtime.Remoting.ChannelData._serverProviders, System.Collections.ArrayList.Add(), System.Runtime.Remoting.ChannelData.ClientProviders, System.Collections.Hashtable.ContainsKey(), System.Runtime.Remoting.ProviderData.CopyFrom(), System.Runtime.Remoting.ChannelData.CustomProperties, System.Runtime.Remoting.ChannelData.DelayLoadAsClientChannel, System.Runtime.Remoting.ChannelData.Id, System.Collections.DictionaryEntry.Key, System.obj, System.Runtime.Remoting.ChannelData.Ref, System.Runtime.Remoting.ChannelData.ServerProviders, System.Runtime.Remoting.ChannelData.Type, and System.Collections.DictionaryEntry.Value.
Referenced by System.Runtime.Remoting.RemotingConfiguration.RegisterChannels().