Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldLoad.Update
Update()
override void Terraria.GameContent.UI.States.UIWorldLoad.Update (GameTime gameTime) inline virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 45 of file UIWorldLoad.cs.
        {
            if (WorldGenerator.CurrentController != null)
            {
                if (DebugOptions.enableDebugCommands && Main.keyState.IsKeyDown(Keys.F5))
                {
                    UIWorldGenDebug.Open();
                }
                if (PlayerInput.Triggers.Current.Inventory && !WorldGenerator.CurrentController.QueuedAbort)
                {
                    WorldGenerator.CurrentController.QueuedAbort = true;
                    SoundEngine.PlaySound(11, -1, -1, 1, 1f, 0f);
                }
            }
            this._progressBar.Top.Pixels = MathHelper.Lerp(270f, 370f, Utils.GetLerpValue(600f, 700f, (float)Main.screenHeight, true));
            this._progressMessage.Top.Pixels = this._progressBar.Top.Pixels - 70f;
            this._progressBar.Recalculate();
            this._progressMessage.Recalculate();
            base.Update(gameTime);
        }
References Terraria.GameContent.UI.States.UIWorldLoad._progressBar, Terraria.GameContent.UI.States.UIWorldLoad._progressMessage, Terraria.GameInput.TriggersPack.Current, Terraria.WorldBuilding.WorldGenerator.CurrentController, Terraria.Testing.DebugOptions.enableDebugCommands, Terraria.Utils.GetLerpValue(), Terraria.GameInput.TriggersSet.Inventory, Microsoft.Xna.Framework.Input.KeyboardState.IsKeyDown(), Terraria.Main.keyState, Microsoft.Xna.Framework.MathHelper.Lerp(), Terraria.GameContent.UI.States.UIWorldGenDebug.Open(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.GameContent.UI.Elements.UIGenProgressBar.Recalculate(), Terraria.UI.UIElement.Recalculate(), Terraria.Main.screenHeight, and Terraria.GameInput.PlayerInput.Triggers.