Terraria Decompiled: Newtonsoft.Json.Schema.JsonSchemaWriter.ReferenceOrWriteSchema
ReferenceOrWriteSchema()
void Newtonsoft.Json.Schema.JsonSchemaWriter.ReferenceOrWriteSchema (JsonSchema schema) inline private
Definition at line 23 of file JsonSchemaWriter.cs.
        {
            if (schema.Id != null && this._resolver.GetSchema(schema.Id) != null)
            {
                this._writer.WriteStartObject();
                this._writer.WritePropertyName("$ref");
                this._writer.WriteValue(schema.Id);
                this._writer.WriteEndObject();
                return;
            }
            this.WriteSchema(schema);
        }
References Newtonsoft.Json.Schema.JsonSchemaWriter._writer, Newtonsoft.Json.Schema.JsonSchema.Id, Newtonsoft.Json.JsonWriter.WriteEndObject(), Newtonsoft.Json.JsonWriter.WritePropertyName(), Newtonsoft.Json.Schema.JsonSchemaWriter.WriteSchema(), Newtonsoft.Json.JsonWriter.WriteStartObject(), and Newtonsoft.Json.JsonWriter.WriteValue().
Referenced by Newtonsoft.Json.Schema.JsonSchemaWriter.WriteItems(), Newtonsoft.Json.Schema.JsonSchemaWriter.WriteSchema(), and Newtonsoft.Json.Schema.JsonSchemaWriter.WriteSchemaDictionaryIfNotNull().