Terraria Decompiled: Newtonsoft.Json.Schema.JsonSchemaWriter.WriteSchemaDictionaryIfNotNull
WriteSchemaDictionaryIfNotNull()
void Newtonsoft.Json.Schema.JsonSchemaWriter.WriteSchemaDictionaryIfNotNull (JsonWriter writer, string propertyName, IDictionary< string, JsonSchema > properties) inline private
Definition at line 130 of file JsonSchemaWriter.cs.
        {
            if (properties != null)
            {
                writer.WritePropertyName(propertyName);
                writer.WriteStartObject();
                foreach (KeyValuePair<string, JsonSchema> keyValuePair in properties)
                {
                    writer.WritePropertyName(keyValuePair.Key);
                    this.ReferenceOrWriteSchema(keyValuePair.Value);
                }
                writer.WriteEndObject();
            }
        }
References System.Collections.Generic.KeyValuePair< TKey, TValue >.Key, Newtonsoft.Json.Schema.JsonSchemaWriter.ReferenceOrWriteSchema(), System.Collections.Generic.KeyValuePair< TKey, TValue >.Value, Newtonsoft.Json.JsonWriter.WriteEndObject(), Newtonsoft.Json.JsonWriter.WritePropertyName(), and Newtonsoft.Json.JsonWriter.WriteStartObject().
Referenced by Newtonsoft.Json.Schema.JsonSchemaWriter.WriteSchema().