Terraria Decompiled: Newtonsoft.Json.Schema.JsonSchemaWriter.WriteType
WriteType()
void Newtonsoft.Json.Schema.JsonSchemaWriter.WriteType (string propertyName, JsonWriter writer, JsonSchemaType type) inline private
Definition at line 176 of file JsonSchemaWriter.cs.
        {
            if (Enum.IsDefined(typeof(JsonSchemaType), type))
            {
                writer.WritePropertyName(propertyName);
                writer.WriteValue(JsonSchemaBuilder.MapType(type));
                return;
            }
            IEnumerator<JsonSchemaType> enumerator = Enumerable.Where<JsonSchemaType>(EnumUtils.GetFlagsValues<JsonSchemaType>(type), (JsonSchemaType v) => v > JsonSchemaType.None).GetEnumerator();
            if (enumerator.MoveNext())
            {
                writer.WritePropertyName(propertyName);
                JsonSchemaType jsonSchemaType = enumerator.Current;
                if (enumerator.MoveNext())
                {
                    writer.WriteStartArray();
                    writer.WriteValue(JsonSchemaBuilder.MapType(jsonSchemaType));
                    do
                    {
                        writer.WriteValue(JsonSchemaBuilder.MapType(enumerator.Current));
                    }
                    while (enumerator.MoveNext());
                    writer.WriteEndArray();
                    return;
                }
                writer.WriteValue(JsonSchemaBuilder.MapType(jsonSchemaType));
            }
        }
References System.Collections.Generic.IEnumerator< out T >.Current, System.Enum.IsDefined(), Newtonsoft.Json.Schema.JsonSchemaBuilder.MapType(), System.Collections.IEnumerator.MoveNext(), Newtonsoft.Json.JsonWriter.WriteEndArray(), Newtonsoft.Json.JsonWriter.WritePropertyName(), Newtonsoft.Json.JsonWriter.WriteStartArray(), and Newtonsoft.Json.JsonWriter.WriteValue().
Referenced by Newtonsoft.Json.Schema.JsonSchemaWriter.WriteSchema().