Terraria Decompiled: Newtonsoft.Json.Schema.JsonSchemaWriter.WriteSchema
WriteSchema()
void Newtonsoft.Json.Schema.JsonSchemaWriter.WriteSchema (JsonSchema schema) inline
Definition at line 37 of file JsonSchemaWriter.cs.
        {
            ValidationUtils.ArgumentNotNull(schema, "schema");
            if (!this._resolver.LoadedSchemas.Contains(schema))
            {
                this._resolver.LoadedSchemas.Add(schema);
            }
            this._writer.WriteStartObject();
            this.WritePropertyIfNotNull(this._writer, "id", schema.Id);
            this.WritePropertyIfNotNull(this._writer, "title", schema.Title);
            this.WritePropertyIfNotNull(this._writer, "description", schema.Description);
            this.WritePropertyIfNotNull(this._writer, "required", schema.Required);
            this.WritePropertyIfNotNull(this._writer, "readonly", schema.ReadOnly);
            this.WritePropertyIfNotNull(this._writer, "hidden", schema.Hidden);
            this.WritePropertyIfNotNull(this._writer, "transient", schema.Transient);
            if (schema.Type != null)
            {
                this.WriteType("type", this._writer, schema.Type.GetValueOrDefault());
            }
            if (!schema.AllowAdditionalProperties)
            {
                this._writer.WritePropertyName("additionalProperties");
                this._writer.WriteValue(schema.AllowAdditionalProperties);
            }
            else if (schema.AdditionalProperties != null)
            {
                this._writer.WritePropertyName("additionalProperties");
                this.ReferenceOrWriteSchema(schema.AdditionalProperties);
            }
            if (!schema.AllowAdditionalItems)
            {
                this._writer.WritePropertyName("additionalItems");
                this._writer.WriteValue(schema.AllowAdditionalItems);
            }
            else if (schema.AdditionalItems != null)
            {
                this._writer.WritePropertyName("additionalItems");
                this.ReferenceOrWriteSchema(schema.AdditionalItems);
            }
            this.WriteSchemaDictionaryIfNotNull(this._writer, "properties", schema.Properties);
            this.WriteSchemaDictionaryIfNotNull(this._writer, "patternProperties", schema.PatternProperties);
            this.WriteItems(schema);
            this.WritePropertyIfNotNull(this._writer, "minimum", schema.Minimum);
            this.WritePropertyIfNotNull(this._writer, "maximum", schema.Maximum);
            this.WritePropertyIfNotNull(this._writer, "exclusiveMinimum", schema.ExclusiveMinimum);
            this.WritePropertyIfNotNull(this._writer, "exclusiveMaximum", schema.ExclusiveMaximum);
            this.WritePropertyIfNotNull(this._writer, "minLength", schema.MinimumLength);
            this.WritePropertyIfNotNull(this._writer, "maxLength", schema.MaximumLength);
            this.WritePropertyIfNotNull(this._writer, "minItems", schema.MinimumItems);
            this.WritePropertyIfNotNull(this._writer, "maxItems", schema.MaximumItems);
            this.WritePropertyIfNotNull(this._writer, "divisibleBy", schema.DivisibleBy);
            this.WritePropertyIfNotNull(this._writer, "format", schema.Format);
            this.WritePropertyIfNotNull(this._writer, "pattern", schema.Pattern);
            if (schema.Enum != null)
            {
                this._writer.WritePropertyName("enum");
                this._writer.WriteStartArray();
                foreach (JToken jtoken in schema.Enum)
                {
                    jtoken.WriteTo(this._writer, new JsonConverter[0]);
                }
                this._writer.WriteEndArray();
            }
            if (schema.Default != null)
            {
                this._writer.WritePropertyName("default");
                schema.Default.WriteTo(this._writer, new JsonConverter[0]);
            }
            if (schema.Disallow != null)
            {
                this.WriteType("disallow", this._writer, schema.Disallow.GetValueOrDefault());
            }
            if (schema.Extends != null && schema.Extends.Count > 0)
            {
                this._writer.WritePropertyName("extends");
                if (schema.Extends.Count == 1)
                {
                    this.ReferenceOrWriteSchema(schema.Extends[0]);
                }
                else
                {
                    this._writer.WriteStartArray();
                    foreach (JsonSchema jsonSchema in schema.Extends)
                    {
                        this.ReferenceOrWriteSchema(jsonSchema);
                    }
                    this._writer.WriteEndArray();
                }
            }
            this._writer.WriteEndObject();
        }
References Newtonsoft.Json.Schema.JsonSchemaWriter._resolver, Newtonsoft.Json.Schema.JsonSchemaWriter._writer, Newtonsoft.Json.Schema.JsonSchema.AdditionalItems, Newtonsoft.Json.Schema.JsonSchema.AdditionalProperties, Newtonsoft.Json.Schema.JsonSchema.AllowAdditionalItems, Newtonsoft.Json.Schema.JsonSchema.AllowAdditionalProperties, Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(), Newtonsoft.Json.Schema.JsonSchema.Default, Newtonsoft.Json.Schema.JsonSchema.Description, Newtonsoft.Json.Schema.JsonSchema.Disallow, Newtonsoft.Json.Schema.JsonSchema.DivisibleBy, Newtonsoft.Json.Schema.JsonSchema.Enum, Newtonsoft.Json.Schema.JsonSchema.ExclusiveMaximum, Newtonsoft.Json.Schema.JsonSchema.ExclusiveMinimum, Newtonsoft.Json.Schema.JsonSchema.Extends, Newtonsoft.Json.Schema.JsonSchema.Format, Newtonsoft.Json.Schema.JsonSchema.Hidden, Newtonsoft.Json.Schema.JsonSchema.Id, Newtonsoft.Json.Schema.JsonSchemaResolver.LoadedSchemas, Newtonsoft.Json.Schema.JsonSchema.Maximum, Newtonsoft.Json.Schema.JsonSchema.MaximumItems, Newtonsoft.Json.Schema.JsonSchema.MaximumLength, Newtonsoft.Json.Schema.JsonSchema.Minimum, Newtonsoft.Json.Schema.JsonSchema.MinimumItems, Newtonsoft.Json.Schema.JsonSchema.MinimumLength, Newtonsoft.Json.Schema.JsonSchema.Pattern, Newtonsoft.Json.Schema.JsonSchema.PatternProperties, Newtonsoft.Json.Schema.JsonSchema.Properties, Newtonsoft.Json.Schema.JsonSchema.ReadOnly, Newtonsoft.Json.Schema.JsonSchemaWriter.ReferenceOrWriteSchema(), Newtonsoft.Json.Schema.JsonSchema.Required, Newtonsoft.Json.Schema.JsonSchema.Title, Newtonsoft.Json.Schema.JsonSchema.Transient, Newtonsoft.Json.Schema.JsonSchema.Type, Newtonsoft.Json.JsonWriter.WriteEndArray(), Newtonsoft.Json.JsonWriter.WriteEndObject(), Newtonsoft.Json.Schema.JsonSchemaWriter.WriteItems(), Newtonsoft.Json.Schema.JsonSchemaWriter.WritePropertyIfNotNull(), Newtonsoft.Json.JsonWriter.WritePropertyName(), Newtonsoft.Json.Schema.JsonSchemaWriter.WriteSchemaDictionaryIfNotNull(), Newtonsoft.Json.JsonWriter.WriteStartArray(), Newtonsoft.Json.JsonWriter.WriteStartObject(), Newtonsoft.Json.Linq.JToken.WriteTo(), Newtonsoft.Json.Schema.JsonSchemaWriter.WriteType(), and Newtonsoft.Json.JsonWriter.WriteValue().
Referenced by Newtonsoft.Json.Schema.JsonSchemaWriter.ReferenceOrWriteSchema(), and Newtonsoft.Json.Schema.JsonSchema.WriteTo().