Terraria Decompiled: Newtonsoft.Json.Schema.JsonSchemaWriter.WriteItems
WriteItems()
void Newtonsoft.Json.Schema.JsonSchemaWriter.WriteItems (JsonSchema schema) inline private
Definition at line 146 of file JsonSchemaWriter.cs.
        {
            if (schema.Items == null && !schema.PositionalItemsValidation)
            {
                return;
            }
            this._writer.WritePropertyName("items");
            if (schema.PositionalItemsValidation)
            {
                this._writer.WriteStartArray();
                if (schema.Items != null)
                {
                    foreach (JsonSchema jsonSchema in schema.Items)
                    {
                        this.ReferenceOrWriteSchema(jsonSchema);
                    }
                }
                this._writer.WriteEndArray();
                return;
            }
            if (schema.Items != null && schema.Items.Count > 0)
            {
                this.ReferenceOrWriteSchema(schema.Items[0]);
                return;
            }
            this._writer.WriteStartObject();
            this._writer.WriteEndObject();
        }
References Newtonsoft.Json.Schema.JsonSchemaWriter._writer, Newtonsoft.Json.Schema.JsonSchema.Items, Newtonsoft.Json.Schema.JsonSchema.PositionalItemsValidation, Newtonsoft.Json.Schema.JsonSchemaWriter.ReferenceOrWriteSchema(), Newtonsoft.Json.JsonWriter.WriteEndArray(), Newtonsoft.Json.JsonWriter.WriteEndObject(), Newtonsoft.Json.JsonWriter.WritePropertyName(), Newtonsoft.Json.JsonWriter.WriteStartArray(), and Newtonsoft.Json.JsonWriter.WriteStartObject().
Referenced by Newtonsoft.Json.Schema.JsonSchemaWriter.WriteSchema().