Terraria Decompiled: Terraria.Star.StarFall
StarFall()
static void Terraria.Star.StarFall (float positionX) inline static
Definition at line 33 of file Star.cs.
        {
            Star.starFallCount++;
            int num = -1;
            float num2 = -1f;
            float num3 = positionX / Main.rightWorld * (float)Main.MaxWorldViewSize.X;
            for (int i = 0; i < Main.numStars; i++)
            {
                if (!Main.star[i].hidden && !Main.star[i].falling)
                {
                    float num4 = Math.Abs(Main.star[i].position.X - num3);
                    if (num2 == -1f || num4 < num2)
                    {
                        num = i;
                        num2 = num4;
                    }
                }
            }
            if (num >= 0)
            {
                Main.star[num].Fall();
            }
        }
References System.Math.Abs(), Terraria.Star.Fall(), Terraria.Star.falling, Terraria.Star.hidden, Terraria.Main.MaxWorldViewSize, Terraria.Main.numStars, Terraria.Star.position, Terraria.Main.star, Terraria.Star.starFallCount, and Microsoft.Xna.Framework.Vector2.X.
Referenced by Terraria.Projectile.AI_148_StarSpawner().