Terraria Decompiled: Terraria.Star.UpdateStars
UpdateStars()
static void Terraria.Star.UpdateStars () inline static
Definition at line 218 of file Star.cs.
        {
            if (Main.onlyDrawFancyUI)
            {
                return;
            }
            if (!Main.dayTime)
            {
                Star.dayCheck = false;
            }
            else if (!Star.dayCheck && Main.time >= 27000.0)
            {
                for (int i = 0; i < Main.numStars; i++)
                {
                    if (Main.star[i].hidden)
                    {
                        Star.SpawnStars(i);
                    }
                }
            }
            for (int j = 0; j < Main.numStars; j++)
            {
                Main.star[j].Update();
            }
            if (Main.gameMenu && WorldGen.generatingWorld && WorldGen.SecretSeed.anySecretSeedIsActive)
            {
                for (int k = 0; k < Main.numStars; k++)
                {
                    if (!Main.star[k].falling && !Main.star[k].hidden && Main.star[k].scale > 0f)
                    {
                        for (int l = 0; l < Main.numStars; l++)
{
                            if (k != l && !Main.star[l].falling && !Main.star[l].hidden && Main.star[l].position != Main.star[k].position)
{
                                Vector2 vector = Main.star[l].position - Main.star[k].position;
                                float num = vector.X * vector.X + vector.Y * vector.Y;
                                vector *= 0.005f * Main.star[l].scale;
                                if (num != 0f)
{
                                    if (vector.X != 0f)
{
                                        Star star = Main.star[k];
                                        star.velocity.X = star.velocity.X + vector.X / num / Main.star[k].scale;
                                    }
                                    if (vector.Y != 0f)
{
                                        Star star2 = Main.star[k];
                                        star2.velocity.Y = star2.velocity.Y + vector.Y / num / Main.star[k].scale;
                                    }
                                }
                                if (float.IsNaN(Main.star[k].velocity.X) || float.IsInfinity(Main.star[k].velocity.X) || float.IsNaN(Main.star[k].velocity.Y) || float.IsInfinity(Main.star[k].velocity.Y))
{
                                    Main.star[k].velocity = default(Vector2);
                                    Main.star[k].position = default(Vector2);
                                    Main.star[k].hidden = true;
                                }
                            }
                        }
                        Main.star[k].position += Main.star[k].velocity;
                        Main.star[k].rotation += Main.star[k].velocity.X * 0.02f;
                        if (Main.star[k].position.X < 0f)
{
                            Main.star[k].velocity.X = Math.Abs(Main.star[k].velocity.X);
                        }
                        if (Main.star[k].position.X > (float)Main.MaxWorldViewSize.X)
{
                            Main.star[k].velocity.X = -Math.Abs(Main.star[k].velocity.X);
                        }
                        if (Main.star[k].position.Y < 0f)
{
                            Main.star[k].velocity.Y = Math.Abs(Main.star[k].velocity.Y);
                        }
                        if (Main.star[k].position.Y > (float)Main.MaxWorldViewSize.Y)
{
                            Main.star[k].velocity.Y = -Math.Abs(Main.star[k].velocity.Y);
                        }
                    }
                }
            }
        }
References System.Math.Abs(), Terraria.WorldGen.SecretSeed.anySecretSeedIsActive, Terraria.Star.dayCheck, Terraria.Main.dayTime, Terraria.Star.falling, Terraria.Main.gameMenu, Terraria.WorldGen.generatingWorld, Terraria.Star.hidden, Terraria.Main.MaxWorldViewSize, Terraria.Main.numStars, Terraria.Main.onlyDrawFancyUI, Terraria.Star.position, Terraria.Star.rotation, Terraria.Star.scale, Terraria.Star.SpawnStars(), Terraria.Main.star, Terraria.Main.time, Terraria.Star.Update(), Terraria.Star.velocity, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Main.DoUpdate(), and Terraria.Main.DrawMenu().