Terraria Decompiled: Terraria.Star.SpawnStars
SpawnStars()
static void Terraria.Star.SpawnStars (int s = -1) inline static
Definition at line 58 of file Star.cs.
        {
            FastRandom fastRandom = FastRandom.CreateWithRandomSeed();
            int num = fastRandom.Next(200, 400);
            int num2 = 0;
            int num3 = num;
            if (s >= 0)
            {
                num2 = s;
                num3 = s + 1;
            }
            for (int i = num2; i < num3; i++)
            {
                Main.star[i] = new Star();
                if (s >= 0)
                {
                    Main.star[i].fadeIn = 1f;
                    int num4 = 10;
                    int num5 = -2000;
                    for (int j = 0; j < num4; j++)
                    {
                        float num6 = (float)fastRandom.Next(1921);
                        int num7 = 2000;
                        for (int k = 0; k < Main.numStars; k++)
{
                            if (k != s && !Main.star[k].hidden && !Main.star[k].falling)
{
                                int num8 = (int)Math.Abs(num6 - Main.star[k].position.X);
                                if (num8 < num7)
{
                                    num7 = num8;
                                }
                            }
                        }
                        if (s == 0 || num7 > num5)
{
                            num5 = num7;
                            Main.star[i].position.X = num6;
                        }
                    }
                }
                else
                {
                    Main.star[i].position.X = (float)fastRandom.Next(1921);
                }
                Main.star[i].position.Y = (float)fastRandom.Next(1201);
                Main.star[i].rotation = (float)fastRandom.Next(628) * 0.01f;
                Main.star[i].scale = (float)fastRandom.Next(70, 130) * 0.006f;
                Main.star[i].type = fastRandom.Next(0, 4);
                Main.star[i].twinkle = (float)fastRandom.Next(60, 101) * 0.01f;
                Main.star[i].twinkleSpeed = (float)fastRandom.Next(30, 110) * 0.0001f;
                Main.star[i].velocity *= 0f;
                if (fastRandom.Next(2) == 0)
                {
                    Main.star[i].twinkleSpeed *= -1f;
                }
                Main.star[i].rotationSpeed = (float)fastRandom.Next(5, 50) * 0.0001f;
                if (fastRandom.Next(2) == 0)
                {
                    Main.star[i].rotationSpeed *= -1f;
                }
                if (fastRandom.Next(40) == 0)
                {
                    Main.star[i].scale *= 2f;
                    Main.star[i].twinkleSpeed /= 2f;
                    Main.star[i].rotationSpeed /= 2f;
                }
            }
            if (s == -1)
            {
                Main.numStars = num;
            }
        }
References System.Math.Abs(), Terraria.Utilities.FastRandom.CreateWithRandomSeed(), Terraria.Star.fadeIn, Terraria.Star.falling, Terraria.Star.hidden, int, Terraria.Utilities.FastRandom.Next(), Terraria.Main.numStars, Terraria.Star.position, Terraria.Star.rotation, Terraria.Star.rotationSpeed, System.s, Terraria.Star.scale, Terraria.Main.star, Terraria.Star.Star(), Terraria.Star.twinkle, Terraria.Star.twinkleSpeed, Terraria.Star.type, Terraria.Star.velocity, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.WorldGen.clearWorld(), Terraria.Main.DoUpdate(), Terraria.Main.DrawSunAndMoon(), Terraria.Main.Initialize_AlmostEverything(), and Terraria.Star.UpdateStars().