Terraria Decompiled: System.Threading.Tasks.Task.ContinueWith< TNewResult >
ContinueWith< TNewResult >() [7/12]
Task< TNewResult > System.Threading.Tasks.Task< TResult >.ContinueWith< TNewResult > (Func< Task< TResult >, TNewResult > continuationFunction) inline
Definition at line 381 of file Task.cs.
        {
            return this.ContinueWith<TNewResult>(continuationFunction, TaskScheduler.Current, default(CancellationToken), TaskContinuationOptions.None);
        }
References System.Threading.Tasks.Task< TResult >.ContinueWith< TNewResult >(), and System.Threading.Tasks.TaskScheduler.Current.
Referenced by System.Threading.Tasks.Task< TResult >.ContinueWith< TNewResult >(), System.Threading.Tasks.Task< TResult >.ContinueWith< TNewResult >(), System.Threading.Tasks.Task< TResult >.ContinueWith< TNewResult >(), System.Threading.Tasks.Task< TResult >.ContinueWith< TNewResult >(), System.Threading.Tasks.Task< TResult >.ContinueWith< TNewResult >(), System.Threading.Tasks.Task< TResult >.ContinueWith< TNewResult >(), System.Threading.Tasks.Task< TResult >.ContinueWith< TNewResult >(), System.Threading.Tasks.Task< TResult >.ContinueWith< TNewResult >(), System.Threading.Tasks.Task< TResult >.ContinueWith< TNewResult >(), and System.Threading.Tasks.Task< TResult >.ContinueWith< TNewResult >().