Terraria Decompiled: System.Threading.Tasks.Task.ThrowIfExceptional
ThrowIfExceptional()
void System.Threading.Tasks.Task< TResult >.ThrowIfExceptional (bool includeTaskCanceledExceptions) inline package
Definition at line 1057 of file Task.2.cs.
        {
            Exception exceptions = this.GetExceptions(includeTaskCanceledExceptions);
            if (exceptions != null)
            {
                this.UpdateExceptionObservedStatus();
                throw exceptions;
            }
        }
References System.exceptions, System.Threading.Tasks.Task< TResult >.GetExceptions(), and System.Threading.Tasks.Task< TResult >.UpdateExceptionObservedStatus().
Referenced by System.Threading.Tasks.Task< TResult >.Wait().