Terraria Decompiled: System.Threading.Tasks.Task.GetDelegatesFromContinuationObject
GetDelegatesFromContinuationObject()
static Delegate[] System.Threading.Tasks.Task< TResult >.GetDelegatesFromContinuationObject (object continuationObject) inline static private
Definition at line 2736 of file Task.2.cs.
        {
            if (continuationObject != null)
            {
                Action action = continuationObject as Action;
                if (action != null)
                {
                    return new Delegate[] { AsyncMethodBuilderCore.TryGetStateMachineForDebugger(action) };
                }
                TaskContinuation taskContinuation = continuationObject as TaskContinuation;
                if (taskContinuation != null)
                {
                    return taskContinuation.GetDelegateContinuationsForDebugger();
                }
                Task task = continuationObject as Task;
                if (task != null)
                {
                    return task.GetDelegateContinuationsForDebugger();
                }
                ITaskCompletionAction taskCompletionAction = continuationObject as ITaskCompletionAction;
                if (taskCompletionAction != null)
                {
                    return new Delegate[]
                    {
                        new Action<Task>(taskCompletionAction.Invoke)
                    };
                }
                LowLevelListWithIList<object> lowLevelListWithIList = continuationObject as LowLevelListWithIList<object>;
                if (lowLevelListWithIList != null)
                {
                    LowLevelListWithIList<Delegate> lowLevelListWithIList2 = new LowLevelListWithIList<Delegate>();
                    foreach (object obj in ((IEnumerable<object>)lowLevelListWithIList))
                    {
                        Delegate[] delegatesFromContinuationObject = Task.GetDelegatesFromContinuationObject(obj);
                        if (delegatesFromContinuationObject != null)
{
                            foreach (Delegate @delegate in delegatesFromContinuationObject)
{
                                if (@delegate != null)
{
                                    lowLevelListWithIList2.Add(@delegate);
                                }
                            }
                        }
                    }
                    return lowLevelListWithIList2.ToArray();
                }
            }
            return null;
        }
References System.Action(), System.action, System.Threading.Tasks.TaskContinuation.GetDelegateContinuationsForDebugger(), System.Threading.Tasks.Task< TResult >.GetDelegatesFromContinuationObject(), System.Threading.Tasks.ITaskCompletionAction.Invoke(), System.obj, System.task, System.Threading.Tasks.Task< TResult >.Task(), and System.Runtime.CompilerServices.AsyncMethodBuilderCore.TryGetStateMachineForDebugger().
Referenced by System.Threading.Tasks.Task< TResult >.GetDelegateContinuationsForDebugger(), and System.Threading.Tasks.Task< TResult >.GetDelegatesFromContinuationObject().