Terraria Decompiled: System.Threading.Tasks.Task.WaitAll
WaitAll() [4/5]
static bool System.Threading.Tasks.Task< TResult >.WaitAll (Task< TResult >[] tasks, int millisecondsTimeout, CancellationToken cancellationToken) inline static
Definition at line 2094 of file Task.2.cs.
        {
            if (tasks == null)
            {
                throw new ArgumentNullException("tasks");
            }
            if (millisecondsTimeout < -1)
            {
                throw new ArgumentOutOfRangeException("millisecondsTimeout");
            }
            cancellationToken.ThrowIfCancellationRequested();
            LowLevelListWithIList<Exception> lowLevelListWithIList = null;
            LowLevelListWithIList<Task> lowLevelListWithIList2 = null;
            LowLevelListWithIList<Task> lowLevelListWithIList3 = null;
            bool flag = false;
            bool flag2 = false;
            bool flag3 = true;
            for (int i = tasks.Length - 1; i >= 0; i--)
            {
                Task task = tasks[i];
                if (task == null)
                {
                    throw new ArgumentException("The tasks array included at least one null element.", "tasks");
                }
                bool flag4 = task.IsCompleted;
                if (!flag4)
                {
                    if (millisecondsTimeout != -1 || cancellationToken.CanBeCanceled)
                    {
                        Task.AddToList<Task>(task, ref lowLevelListWithIList2, tasks.Length);
                    }
                    else
                    {
                        flag4 = task.WrappedTryRunInline() && task.IsCompleted;
                        if (!flag4)
{
                            Task.AddToList<Task>(task, ref lowLevelListWithIList2, tasks.Length);
                        }
                    }
                }
                if (flag4)
                {
                    if (task.IsFaulted)
                    {
                        flag = true;
                    }
                    else if (task.IsCanceled)
                    {
                        flag2 = true;
                    }
                    if (task.IsWaitNotificationEnabled)
                    {
                        Task.AddToList<Task>(task, ref lowLevelListWithIList3, 1);
                    }
                }
            }
            if (lowLevelListWithIList2 != null)
            {
                flag3 = Task.WaitAllBlockingCore(lowLevelListWithIList2, millisecondsTimeout, cancellationToken);
                if (flag3)
                {
                    foreach (Task task2 in ((IEnumerable<Task>)lowLevelListWithIList2))
                    {
                        if (task2.IsFaulted)
{
                            flag = true;
                        }
                        else if (task2.IsCanceled)
{
                            flag2 = true;
                        }
                        if (task2.IsWaitNotificationEnabled)
{
                            Task.AddToList<Task>(task2, ref lowLevelListWithIList3, 1);
                        }
                    }
                }
                GC.KeepAlive(tasks);
            }
            if (flag3 && lowLevelListWithIList3 != null)
            {
                using (IEnumerator<Task> enumerator = ((IEnumerable<Task>)lowLevelListWithIList3).GetEnumerator())
                {
                    while (enumerator.MoveNext())
                    {
                        if (enumerator.Current.NotifyDebuggerOfWaitCompletionIfNecessary())
{
                            break;
                        }
                    }
                }
            }
            if (flag3 && (flag || flag2))
            {
                if (!flag)
                {
                    cancellationToken.ThrowIfCancellationRequested();
                }
                foreach (Task task3 in tasks)
                {
                    Task.AddExceptionsForCompletedTask(ref lowLevelListWithIList, task3);
                }
                throw new AggregateException(lowLevelListWithIList);
            }
            return flag3;
        }
References System.Threading.Tasks.Task< TResult >.AddExceptionsForCompletedTask(), System.Threading.CancellationToken.CanBeCanceled, System.Collections.Generic.IEnumerator< out T >.Current, System.Threading.Tasks.Task< TResult >.IsCanceled, System.Threading.Tasks.Task< TResult >.IsFaulted, System.Threading.Tasks.Task< TResult >.IsWaitNotificationEnabled, System.GC.KeepAlive(), System.Collections.IEnumerator.MoveNext(), System.task, System.Threading.CancellationToken.ThrowIfCancellationRequested(), and System.Threading.Tasks.Task< TResult >.WaitAllBlockingCore().