Terraria Decompiled: Terraria.GameContent.Biomes.CaveHouse.HouseUtils.CreateRooms
CreateRooms()
static List< Rectangle > Terraria.GameContent.Biomes.CaveHouse.HouseUtils.CreateRooms (Point origin) inline static private
Definition at line 99 of file HouseUtils.cs.
        {
            if (WorldGen.SecretSeed.GenerateBiggerAbandonedHouses)
            {
                return HouseUtils.CreateRooms_BigAbandonedHouses(origin);
            }
            Point point;
            if (!WorldUtils.Find(origin, Searches.Chain(new Searches.Down(200), new GenCondition[]
            {
                new Conditions.IsSolid()
            }), out point) || point == origin)
            {
                return new List<Rectangle>();
            }
            Rectangle rectangle = HouseUtils.FindRoom(point);
            Rectangle rectangle2 = HouseUtils.FindRoom(new Point(rectangle.Center.X, rectangle.Y + 1));
            Rectangle rectangle3 = HouseUtils.FindRoom(new Point(rectangle.Center.X, rectangle.Y + rectangle.Height + 10));
            rectangle3.Y = rectangle.Y + rectangle.Height - 1;
            double roomSolidPrecentage = HouseUtils.GetRoomSolidPrecentage(rectangle2);
            double roomSolidPrecentage2 = HouseUtils.GetRoomSolidPrecentage(rectangle3);
            rectangle.Y += 3;
            rectangle2.Y += 3;
            rectangle3.Y += 3;
            List<Rectangle> list = new List<Rectangle>();
            if (WorldGen.genRand.NextDouble() > roomSolidPrecentage + 0.2)
            {
                list.Add(rectangle2);
            }
            list.Add(rectangle);
            if (WorldGen.genRand.NextDouble() > roomSolidPrecentage2 + 0.2)
            {
                list.Add(rectangle3);
            }
            return list;
        }
References Microsoft.Xna.Framework.Rectangle.Center, Terraria.WorldBuilding.Searches.Chain(), Terraria.GameContent.Biomes.CaveHouse.HouseUtils.CreateRooms_BigAbandonedHouses(), Terraria.WorldBuilding.WorldUtils.Find(), Terraria.GameContent.Biomes.CaveHouse.HouseUtils.FindRoom(), Terraria.WorldGen.SecretSeed.GenerateBiggerAbandonedHouses, Terraria.WorldGen.genRand, Terraria.GameContent.Biomes.CaveHouse.HouseUtils.GetRoomSolidPrecentage(), Microsoft.Xna.Framework.Rectangle.Height, System.list, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Rectangle.Y.
Referenced by Terraria.GameContent.Biomes.CaveHouse.HouseUtils.CreateBuilder().