Terraria Decompiled: System.Threading.Tasks.Task.InternalStartNew
InternalStartNew()
static Task System.Threading.Tasks.Task< TResult >.InternalStartNew (Task< TResult > creatingTask, Delegate action, object state, CancellationToken cancellationToken, TaskScheduler scheduler, TaskCreationOptions options, InternalTaskOptions internalOptions) inline static package
Definition at line 532 of file Task.2.cs.
        {
            if (scheduler == null)
            {
                throw new ArgumentNullException("scheduler");
            }
            Task task = new Task(action, state, creatingTask, cancellationToken, options, internalOptions | InternalTaskOptions.QueuedByRuntime, scheduler);
            task.ScheduleAndStart(false);
            return task;
        }
References System.action, System.options, System.state, System.task, and System.Threading.Tasks.Task< TResult >.Task().
Referenced by System.Threading.Tasks.Task< TResult >.Run(), System.Threading.Tasks.Task< TResult >.Run(), System.Threading.Tasks.TaskFactory< TResult >.StartNew(), System.Threading.Tasks.TaskFactory< TResult >.StartNew(), System.Threading.Tasks.TaskFactory< TResult >.StartNew(), System.Threading.Tasks.TaskFactory< TResult >.StartNew(), System.Threading.Tasks.TaskFactory< TResult >.StartNew(), System.Threading.Tasks.TaskFactory< TResult >.StartNew(), System.Threading.Tasks.TaskFactory< TResult >.StartNew(), System.Threading.Tasks.TaskFactory< TResult >.StartNew(), and System.Threading.Tasks.TaskFactory< TResult >.StartNew().