Terraria Decompiled: System.Threading.Tasks.Task.CompletedTask
CompletedTask
Task System.Threading.Tasks.Task< TResult >.CompletedTask = new Task(false, (TaskCreationOptions)16384, default(CancellationToken)) static get
Definition at line 832 of file Task.2.cs.
        {
            [CompilerGenerated]
            get
            {
                return Task.<CompletedTask>k__BackingField;
            }
        } = new Task(false, (TaskCreationOptions)16384, default(CancellationToken));
Referenced by System.IO.File.AppendAllTextAsync(), System.IO.MemoryStream.CopyToAsync(), System.IO.Stream.NullStream.CopyToAsync(), System.Threading.Tasks.Task< TResult >.Delay(), System.IO.StringWriter.FlushAsync(), System.IO.TextWriter.SyncTextWriter.FlushAsync(), System.IO.MemoryStream.FlushAsync(), System.IO.Stream.NullStream.FlushAsync(), System.IO.UnmanagedMemoryStream.FlushAsync(), System.Security.Cryptography.CryptoStream.FlushAsync(), System.IO.StreamWriter.FlushAsyncInternal(), System.Threading.Tasks.Task< TResult >.InternalWhenAll(), System.IO.File.WriteAllTextAsync(), System.IO.MemoryStream.WriteAsync(), System.IO.Stream.NullStream.WriteAsync(), System.IO.UnmanagedMemoryStream.WriteAsync(), System.IO.StringWriter.WriteAsync(), System.IO.TextWriter.SyncTextWriter.WriteAsync(), System.IO.TextWriter.WriteAsync(), System.IO.StringWriter.WriteAsync(), System.IO.TextWriter.SyncTextWriter.WriteAsync(), System.IO.StreamWriter.WriteAsync(), System.IO.StringWriter.WriteAsync(), System.IO.TextWriter.SyncTextWriter.WriteAsync(), System.IO.StringWriter.WriteLineAsync(), System.IO.TextWriter.SyncTextWriter.WriteLineAsync(), System.IO.StringWriter.WriteLineAsync(), System.IO.TextWriter.SyncTextWriter.WriteLineAsync(), System.IO.StringWriter.WriteLineAsync(), and System.IO.TextWriter.SyncTextWriter.WriteLineAsync().