Terraria Decompiled: System.Threading.Tasks.Task.FinishContinuations
FinishContinuations()
void System.Threading.Tasks.Task< TResult >.FinishContinuations () inline package
Definition at line 1620 of file Task.2.cs.
        {
            object obj = Interlocked.Exchange(ref this.m_continuationObject, Task.s_taskCompletionSentinel);
            if (obj != null)
            {
                if (DebuggerSupport.LoggingOn)
                {
                    DebuggerSupport.TraceSynchronousWorkStart(CausalityTraceLevel.Required, this, CausalitySynchronousWork.CompletionNotification);
                }
                bool flag = (this.m_stateFlags & 134217728) == 0 && (this.m_stateFlags & 64) == 0;
                Action action = obj as Action;
                if (action != null)
                {
                    AwaitTaskContinuation.RunOrScheduleAction(action, flag, ref Task.t_currentTask);
                    this.LogFinishCompletionNotification();
                    return;
                }
                ITaskCompletionAction taskCompletionAction = obj as ITaskCompletionAction;
                if (taskCompletionAction != null)
                {
                    if (flag || !taskCompletionAction.InvokeMayRunArbitraryCode)
                    {
                        taskCompletionAction.Invoke(this);
                    }
                    else
                    {
                        ThreadPool.UnsafeQueueCustomWorkItem(new CompletionActionInvoker(taskCompletionAction, this), false);
                    }
                    this.LogFinishCompletionNotification();
                    return;
                }
                TaskContinuation taskContinuation = obj as TaskContinuation;
                if (taskContinuation != null)
                {
                    taskContinuation.Run(this, flag);
                    this.LogFinishCompletionNotification();
                    return;
                }
                LowLevelListWithIList<object> lowLevelListWithIList = obj as LowLevelListWithIList<object>;
                if (lowLevelListWithIList == null)
                {
                    this.LogFinishCompletionNotification();
                    return;
                }
                LowLevelListWithIList<object> lowLevelListWithIList2 = lowLevelListWithIList;
                lock (lowLevelListWithIList2)
                {
                }
                int count = lowLevelListWithIList.Count;
                for (int i = 0; i < count; i++)
                {
                    StandardTaskContinuation standardTaskContinuation = lowLevelListWithIList[i] as StandardTaskContinuation;
                    if (standardTaskContinuation != null && (standardTaskContinuation.m_options & TaskContinuationOptions.ExecuteSynchronously) == TaskContinuationOptions.None)
                    {
                        lowLevelListWithIList[i] = null;
                        standardTaskContinuation.Run(this, flag);
                    }
                }
                for (int j = 0; j < count; j++)
                {
                    object obj2 = lowLevelListWithIList[j];
                    if (obj2 != null)
                    {
                        lowLevelListWithIList[j] = null;
                        Action action2 = obj2 as Action;
                        if (action2 != null)
{
                            AwaitTaskContinuation.RunOrScheduleAction(action2, flag, ref Task.t_currentTask);
                        }
                        else
{
                            TaskContinuation taskContinuation2 = obj2 as TaskContinuation;
                            if (taskContinuation2 != null)
{
                                taskContinuation2.Run(this, flag);
                            }
                            else
{
                                ITaskCompletionAction taskCompletionAction2 = (ITaskCompletionAction)obj2;
                                if (flag || !taskCompletionAction2.InvokeMayRunArbitraryCode)
{
                                    taskCompletionAction2.Invoke(this);
                                }
                                else
{
                                    ThreadPool.UnsafeQueueCustomWorkItem(new CompletionActionInvoker(taskCompletionAction2, this), false);
                                }
                            }
                        }
                    }
                }
                this.LogFinishCompletionNotification();
            }
        }
References System.Action(), System.action, System.Collections.Generic.LowLevelList< T >.Count, System.count, System.Threading.Interlocked.Exchange(), System.Threading.Tasks.ITaskCompletionAction.Invoke(), System.Threading.Tasks.ITaskCompletionAction.InvokeMayRunArbitraryCode, System.Threading.Tasks.Task< TResult >.LogFinishCompletionNotification(), System.Threading.Tasks.DebuggerSupport.LoggingOn, System.Threading.Tasks.Task< TResult >.m_continuationObject, System.Threading.Tasks.StandardTaskContinuation.m_options, System.Threading.Tasks.Task< TResult >.m_stateFlags, System.obj, System.Threading.Tasks.StandardTaskContinuation.Run(), System.Threading.Tasks.TaskContinuation.Run(), System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(), System.Threading.Tasks.Task< TResult >.s_taskCompletionSentinel, System.Threading.Tasks.Task< TResult >.t_currentTask, System.Threading.Tasks.DebuggerSupport.TraceSynchronousWorkStart(), and System.Threading.ThreadPool.UnsafeQueueCustomWorkItem().
Referenced by System.Threading.Tasks.Task< TResult >.FinishStageThree().