Terraria Decompiled: System.Threading.Tasks.Task.AddTaskContinuationComplex
AddTaskContinuationComplex()
bool System.Threading.Tasks.Task< TResult >.AddTaskContinuationComplex (object tc, bool addBeforeOthers) inline private
Definition at line 1984 of file Task.2.cs.
        {
            object continuationObject = this.m_continuationObject;
            if (continuationObject != Task.s_taskCompletionSentinel && !(continuationObject is LowLevelListWithIList<object>))
            {
                Interlocked.CompareExchange(ref this.m_continuationObject, new LowLevelListWithIList<object> { continuationObject }, continuationObject);
            }
            LowLevelListWithIList<object> lowLevelListWithIList = this.m_continuationObject as LowLevelListWithIList<object>;
            if (lowLevelListWithIList != null)
            {
                LowLevelListWithIList<object> lowLevelListWithIList2 = lowLevelListWithIList;
                lock (lowLevelListWithIList2)
                {
                    if (this.m_continuationObject != Task.s_taskCompletionSentinel)
                    {
                        if (lowLevelListWithIList.Count == lowLevelListWithIList.Capacity)
{
                            lowLevelListWithIList.RemoveAll(Task.s_IsTaskContinuationNullPredicate);
                        }
                        if (addBeforeOthers)
{
                            lowLevelListWithIList.Insert(0, tc);
                        }
                        else
{
                            lowLevelListWithIList.Add(tc);
                        }
                        return true;
                    }
                }
                return false;
            }
            return false;
        }
References System.Collections.Generic.LowLevelList< T >.Add(), System.Collections.Generic.LowLevelList< T >.Capacity, System.Threading.Interlocked.CompareExchange(), System.Collections.Generic.LowLevelList< T >.Count, System.Collections.Generic.LowLevelList< T >.Insert(), System.Threading.Tasks.Task< TResult >.m_continuationObject, System.Collections.Generic.LowLevelList< T >.RemoveAll(), System.Threading.Tasks.Task< TResult >.s_IsTaskContinuationNullPredicate, and System.Threading.Tasks.Task< TResult >.s_taskCompletionSentinel.
Referenced by System.Threading.Tasks.Task< TResult >.AddTaskContinuation().