Terraria Decompiled: System.Threading.Tasks.Task.InternalRunSynchronously
InternalRunSynchronously()
void System.Threading.Tasks.Task< TResult >.InternalRunSynchronously (TaskScheduler scheduler, bool waitForCompletion) inline package
Definition at line 479 of file Task.2.cs.
        {
            int stateFlags = this.m_stateFlags;
            TaskCreationOptions taskCreationOptions = Task.OptionsMethod(stateFlags);
            if ((taskCreationOptions & (TaskCreationOptions)512) != TaskCreationOptions.None)
            {
                throw new InvalidOperationException("RunSynchronously may not be called on a continuation task.");
            }
            if ((taskCreationOptions & (TaskCreationOptions)1024) != TaskCreationOptions.None)
            {
                throw new InvalidOperationException("RunSynchronously may not be called on a task not bound to a delegate, such as the task returned from an asynchronous method.");
            }
            if (Task.IsCompletedMethod(stateFlags))
            {
                throw new InvalidOperationException("RunSynchronously may not be called on a task that has already completed.");
            }
            if (Interlocked.CompareExchange<TaskScheduler>(ref this.m_taskScheduler, scheduler, null) != null)
            {
                throw new InvalidOperationException("RunSynchronously may not be called on a task that was already started.");
            }
            if (this.MarkStarted())
            {
                bool flag = false;
                try
                {
                    if (!scheduler.TryRunInline(this, false))
                    {
                        scheduler.QueueTask(this);
                        flag = true;
                    }
                    if (waitForCompletion && !this.IsCompleted)
                    {
                        this.SpinThenBlockingWait(-1, default(CancellationToken));
                    }
                    return;
                }
                catch (Exception ex)
                {
                    if (!flag)
                    {
                        TaskSchedulerException ex2 = new TaskSchedulerException(ex);
                        this.AddException(ex2);
                        this.Finish(false);
                        this.m_contingentProperties.m_exceptionsHolder.MarkAsHandled(false);
                        throw ex2;
                    }
                    throw;
                }
            }
            throw new InvalidOperationException("RunSynchronously may not be called on a task that has already completed.");
        }
References System.Threading.Tasks.Task< TResult >.AddException(), System.Threading.Interlocked.CompareExchange(), System.Threading.Tasks.Task< TResult >.Finish(), System.Threading.Tasks.Task< TResult >.IsCompleted, System.Threading.Tasks.Task< TResult >.IsCompletedMethod(), System.Threading.Tasks.Task< TResult >.m_contingentProperties, System.Threading.Tasks.Task< TResult >.m_stateFlags, System.Threading.Tasks.Task< TResult >.MarkStarted(), System.Threading.Tasks.Task< TResult >.OptionsMethod(), System.Threading.Tasks.TaskScheduler.QueueTask(), System.Threading.Tasks.Task< TResult >.SpinThenBlockingWait(), and System.Threading.Tasks.TaskScheduler.TryRunInline().
Referenced by System.Threading.Tasks.TaskFactory< TResult >.FromAsyncImpl(), System.Threading.Tasks.Task< TResult >.RunSynchronously(), and System.Threading.Tasks.Task< TResult >.RunSynchronously().