Terraria Decompiled: System.Threading.Tasks.Task.AssignCancellationToken
AssignCancellationToken()
void System.Threading.Tasks.Task< TResult >.AssignCancellationToken (CancellationToken cancellationToken, Task< TResult > antecedent, TaskContinuation continuation) inline private
Definition at line 162 of file Task.2.cs.
        {
            Task.ContingentProperties contingentProperties = this.EnsureContingentPropertiesInitialized(false);
            contingentProperties.m_cancellationToken = cancellationToken;
            try
            {
                if ((this.Options & (TaskCreationOptions)13312) == TaskCreationOptions.None)
                {
                    if (cancellationToken.IsCancellationRequested)
                    {
                        this.InternalCancel(false);
                    }
                    else
                    {
                        CancellationTokenRegistration cancellationTokenRegistration;
                        if (antecedent == null)
{
                            cancellationTokenRegistration = cancellationToken.InternalRegisterWithoutEC(Task.s_taskCancelCallback, this);
                        }
                        else
{
                            cancellationTokenRegistration = cancellationToken.InternalRegisterWithoutEC(Task.s_taskCancelCallback, new Tuple<Task, Task, TaskContinuation>(this, antecedent, continuation));
                        }
                        contingentProperties.m_cancellationRegistration = cancellationTokenRegistration;
                    }
                }
            }
            catch
            {
                if (this.m_parent != null && (this.Options & TaskCreationOptions.AttachedToParent) != TaskCreationOptions.None && (this.m_parent.Options & TaskCreationOptions.DenyChildAttach) == TaskCreationOptions.None)
                {
                    this.m_parent.DisregardChild();
                }
                throw;
            }
        }
References System.Threading.Tasks.Task< TResult >.DisregardChild(), System.Threading.Tasks.Task< TResult >.EnsureContingentPropertiesInitialized(), System.Threading.Tasks.Task< TResult >.InternalCancel(), System.Threading.CancellationToken.InternalRegisterWithoutEC(), System.Threading.CancellationToken.IsCancellationRequested, System.Threading.Tasks.Task< TResult >.m_parent, System.Threading.Tasks.Task< TResult >.Options, and System.Threading.Tasks.Task< TResult >.s_taskCancelCallback.
Referenced by System.Threading.Tasks.Task< TResult >.ContinueWithCore(), and System.Threading.Tasks.Task< TResult >.TaskConstructorCore().