Terraria Decompiled: System.Threading.Tasks.Task.TaskConstructorCore
TaskConstructorCore()
void System.Threading.Tasks.Task< TResult >.TaskConstructorCore (Delegate action, object state, CancellationToken cancellationToken, TaskCreationOptions creationOptions, InternalTaskOptions internalOptions, TaskScheduler scheduler) inline package
Definition at line 135 of file Task.2.cs.
        {
            this.m_action = action;
            this.m_stateObject = state;
            this.m_taskScheduler = scheduler;
            if ((creationOptions & ~(TaskCreationOptions.PreferFairness | TaskCreationOptions.LongRunning | TaskCreationOptions.AttachedToParent | TaskCreationOptions.DenyChildAttach | TaskCreationOptions.HideScheduler | TaskCreationOptions.RunContinuationsAsynchronously)) != TaskCreationOptions.None)
            {
                throw new ArgumentOutOfRangeException("creationOptions");
            }
            int num = (int)(creationOptions | (TaskCreationOptions)internalOptions);
            if (this.m_action == null || (internalOptions & InternalTaskOptions.ContinuationTask) != InternalTaskOptions.None)
            {
                num |= 33554432;
            }
            this.m_stateFlags = num;
            if (this.m_parent != null && (creationOptions & TaskCreationOptions.AttachedToParent) != TaskCreationOptions.None && (this.m_parent.CreationOptions & TaskCreationOptions.DenyChildAttach) == TaskCreationOptions.None)
            {
                this.m_parent.AddNewChild();
            }
            if (cancellationToken.CanBeCanceled)
            {
                this.AssignCancellationToken(cancellationToken, null, null);
            }
            this.CapturedContext = ExecutionContext.Capture();
        }
References System.action, System.Threading.Tasks.Task< TResult >.AddNewChild(), System.Threading.Tasks.Task< TResult >.AssignCancellationToken(), System.Threading.CancellationToken.CanBeCanceled, System.Threading.ExecutionContext.Capture(), int, System.Threading.Tasks.Task< TResult >.m_action, System.Threading.Tasks.Task< TResult >.m_parent, and System.state.
Referenced by System.Threading.Tasks.Task< TResult >.Task(), and System.Threading.Tasks.Task< TResult >.Task().