Terraria Decompiled: System.Threading.Tasks.Task.CreationOptionsFromContinuationOptions
CreationOptionsFromContinuationOptions()
static void System.Threading.Tasks.Task< TResult >.CreationOptionsFromContinuationOptions (TaskContinuationOptions continuationOptions, out TaskCreationOptions creationOptions, out InternalTaskOptions internalOptions) inline static package
Definition at line 1922 of file Task.2.cs.
        {
            TaskContinuationOptions taskContinuationOptions = TaskContinuationOptions.NotOnRanToCompletion | TaskContinuationOptions.NotOnFaulted | TaskContinuationOptions.NotOnCanceled;
            TaskContinuationOptions taskContinuationOptions2 = TaskContinuationOptions.PreferFairness | TaskContinuationOptions.LongRunning | TaskContinuationOptions.AttachedToParent | TaskContinuationOptions.DenyChildAttach | TaskContinuationOptions.HideScheduler | TaskContinuationOptions.RunContinuationsAsynchronously;
            TaskContinuationOptions taskContinuationOptions3 = TaskContinuationOptions.LongRunning | TaskContinuationOptions.ExecuteSynchronously;
            if ((continuationOptions & taskContinuationOptions3) == taskContinuationOptions3)
            {
                throw new ArgumentOutOfRangeException("continuationOptions", "The specified TaskContinuationOptions combined LongRunning and ExecuteSynchronously.  Synchronous continuations should not be long running.");
            }
            if ((continuationOptions & ~((taskContinuationOptions2 | taskContinuationOptions | TaskContinuationOptions.LazyCancellation | TaskContinuationOptions.ExecuteSynchronously) != TaskContinuationOptions.None)) != TaskContinuationOptions.None)
            {
                throw new ArgumentOutOfRangeException("continuationOptions");
            }
            if ((continuationOptions & taskContinuationOptions) == taskContinuationOptions)
            {
                throw new ArgumentOutOfRangeException("continuationOptions", "The specified TaskContinuationOptions excluded all continuation kinds.");
            }
            creationOptions = (TaskCreationOptions)(continuationOptions & taskContinuationOptions2);
            internalOptions = InternalTaskOptions.ContinuationTask;
            if ((continuationOptions & TaskContinuationOptions.LazyCancellation) != TaskContinuationOptions.None)
            {
                internalOptions |= InternalTaskOptions.LazyCancellation;
            }
        }
Referenced by System.Threading.Tasks.Task< TResult >.ContinueWith(), System.Threading.Tasks.Task< TResult >.ContinueWith(), System.Threading.Tasks.Task< TResult >.ContinueWith(), System.Threading.Tasks.Task< TResult >.ContinueWith(), System.Threading.Tasks.Task< TResult >.ContinueWith< TNewResult >(), System.Threading.Tasks.Task< TResult >.ContinueWith< TNewResult >(), System.Threading.Tasks.Task< TResult >.ContinueWith< TResult >(), System.Threading.Tasks.Task< TResult >.ContinueWith< TResult >(), and System.Threading.Tasks.TaskFactory< TResult >.CreateCanceledTask().