Terraria Decompiled: System.Threading.Tasks.Task.Factory
Factory [1/2]
TaskFactory System.Threading.Tasks.Task< TResult >.Factory = new TaskFactory() static get
Definition at line 821 of file Task.2.cs.
        {
            [CompilerGenerated]
            get
            {
                return Task.<Factory>k__BackingField;
            }
        } = new TaskFactory();
Referenced by Terraria.Social.Steam.NetServerSocialModule.Close(), Terraria.Social.WeGame.IPCClient.ConnectTo(), Terraria.WorldGen.CreateNewWorld(), System.IO.TextWriter.FlushAsync(), System.IO.Stream.FlushAsync(), System.Threading.Tasks.Parallel.Invoke(), System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.InvokeContinuation(), Terraria.WorldBuilding.WorldGenSnapshot.LoadSnapshots(), System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.OnCompleted(), System.Runtime.CompilerServices.YieldAwaitable.YieldAwaiter.QueueContinuation(), System.IO.TextReader.ReadAsync(), System.IO.TextReader.ReadBlockAsync(), System.IO.TextReader.ReadLineAsync(), System.Threading.Tasks.Task< TResult >.Run(), System.Threading.Tasks.Task< TResult >.Run< TResult >(), Terraria.Social.WeGame.AsyncTaskHelper.RunAsyncTask(), Terraria.Social.WeGame.AsyncTaskHelper.RunAsyncTaskAndReply(), Terraria.WorldGen.serverLoadWorld(), Terraria.WorldGen.TransformWorldOnBackgroundThread(), Terraria.Testing.WindowsPerformanceDiagnostics.UnpinFromCore0(), System.IO.TextWriter.WriteAsync(), System.IO.TextWriter.WriteAsync(), System.IO.TextWriter.WriteAsync(), System.IO.TextWriter.WriteAsync(), System.IO.TextWriter.WriteLineAsync(), System.IO.TextWriter.WriteLineAsync(), System.IO.TextWriter.WriteLineAsync(), and System.IO.TextWriter.WriteLineAsync().