Terraria Decompiled: Terraria.GameContent.Biomes.CaveHouse.HouseUtils.FindRoom
FindRoom()
static Rectangle Terraria.GameContent.Biomes.CaveHouse.HouseUtils.FindRoom (Point origin) inline static private
Definition at line 136 of file HouseUtils.cs.
        {
            Point point;
            bool flag = WorldUtils.Find(origin, Searches.Chain(new Searches.Left(25), new GenCondition[]
            {
                new Conditions.IsSolid()
            }), out point);
            Point point2;
            bool flag2 = WorldUtils.Find(origin, Searches.Chain(new Searches.Right(25), new GenCondition[]
            {
                new Conditions.IsSolid()
            }), out point2);
            if (!flag)
            {
                point = new Point(origin.X - 25, origin.Y);
            }
            if (!flag2)
            {
                point2 = new Point(origin.X + 25, origin.Y);
            }
            Rectangle rectangle = new Rectangle(origin.X, origin.Y, 0, 0);
            if (origin.X - point.X > point2.X - origin.X)
            {
                rectangle.X = point.X;
                rectangle.Width = Utils.Clamp<int>(point2.X - point.X, 15, 30);
            }
            else
            {
                rectangle.Width = Utils.Clamp<int>(point2.X - point.X, 15, 30);
                rectangle.X = point2.X - rectangle.Width;
            }
            Point point3;
            bool flag3 = WorldUtils.Find(point, Searches.Chain(new Searches.Up(10), new GenCondition[]
            {
                new Conditions.IsSolid()
            }), out point3);
            Point point4;
            bool flag4 = WorldUtils.Find(point2, Searches.Chain(new Searches.Up(10), new GenCondition[]
            {
                new Conditions.IsSolid()
            }), out point4);
            if (!flag3)
            {
                point3 = new Point(origin.X, origin.Y - 10);
            }
            if (!flag4)
            {
                point4 = new Point(origin.X, origin.Y - 10);
            }
            rectangle.Height = Utils.Clamp<int>(Math.Max(origin.Y - point3.Y, origin.Y - point4.Y), 8, 12);
            rectangle.Y -= rectangle.Height;
            return rectangle;
        }
References Terraria.WorldBuilding.Searches.Chain(), Terraria.Utils.Clamp(), Terraria.WorldBuilding.WorldUtils.Find(), Microsoft.Xna.Framework.Rectangle.Height, System.Math.Max(), Microsoft.Xna.Framework.Rectangle.Width, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.Biomes.CaveHouse.HouseUtils.CreateRooms(), and Terraria.GameContent.Biomes.CaveHouse.HouseUtils.CreateRooms_BigAbandonedHouses().