Terraria Decompiled: System.Threading.Tasks.Task.ScheduleAndStart
ScheduleAndStart()
void System.Threading.Tasks.Task< TResult >.ScheduleAndStart (bool needsProtection) inline package
Definition at line 948 of file Task.2.cs.
        {
            if (needsProtection)
            {
                if (!this.MarkStarted())
                {
                    return;
                }
            }
            else
            {
                this.m_stateFlags |= 65536;
            }
            DebuggerSupport.AddToActiveTasks(this);
            if (DebuggerSupport.LoggingOn && (this.Options & (TaskCreationOptions)512) == TaskCreationOptions.None)
            {
                CausalityTraceLevel causalityTraceLevel = CausalityTraceLevel.Required;
                string text = "Task: ";
                Delegate action = this.m_action;
                DebuggerSupport.TraceOperationCreation(causalityTraceLevel, this, text + ((action != null) ? action.ToString() : null), 0UL);
            }
            try
            {
                this.m_taskScheduler.QueueTask(this);
            }
            catch (Exception ex)
            {
                TaskSchedulerException ex2 = new TaskSchedulerException(ex);
                this.AddException(ex2);
                this.Finish(false);
                if ((this.Options & (TaskCreationOptions)512) == TaskCreationOptions.None)
                {
                    this.m_contingentProperties.m_exceptionsHolder.MarkAsHandled(false);
                }
                throw ex2;
            }
        }
References System.action, System.Threading.Tasks.Task< TResult >.AddException(), System.Threading.Tasks.DebuggerSupport.AddToActiveTasks(), System.Threading.Tasks.Task< TResult >.Finish(), System.Threading.Tasks.DebuggerSupport.LoggingOn, System.Threading.Tasks.Task< TResult >.m_action, System.Threading.Tasks.Task< TResult >.m_contingentProperties, System.Threading.Tasks.Task< TResult >.m_taskScheduler, System.Threading.Tasks.Task< TResult >.MarkStarted(), System.Threading.Tasks.Task< TResult >.Options, System.Threading.Tasks.TaskScheduler.QueueTask(), System.text, and System.Threading.Tasks.DebuggerSupport.TraceOperationCreation().
Referenced by System.Threading.Tasks.Task< TResult >.Start().