Terraria Decompiled: System.Threading.Tasks.Task.Finish
Finish()
void System.Threading.Tasks.Task< TResult >.Finish (bool bUserDelegateExecuted) inline package
Definition at line 1097 of file Task.2.cs.
        {
            if (!bUserDelegateExecuted)
            {
                this.FinishStageTwo();
                return;
            }
            Task.ContingentProperties contingentProperties = this.m_contingentProperties;
            if (contingentProperties == null || contingentProperties.m_completionCountdown == 1 || Interlocked.Decrement(ref contingentProperties.m_completionCountdown) == 0)
            {
                this.FinishStageTwo();
            }
            else
            {
                this.AtomicStateUpdate(8388608, 23068672);
            }
            LowLevelListWithIList<Task> lowLevelListWithIList = ((contingentProperties != null) ? contingentProperties.m_exceptionalChildren : null);
            if (lowLevelListWithIList != null)
            {
                LowLevelListWithIList<Task> lowLevelListWithIList2 = lowLevelListWithIList;
                lock (lowLevelListWithIList2)
                {
                    lowLevelListWithIList.RemoveAll(Task.s_IsExceptionObservedByParentPredicate);
                }
            }
        }
References System.Threading.Tasks.Task< TResult >.AtomicStateUpdate(), System.Threading.Interlocked.Decrement(), System.Threading.Tasks.Task< TResult >.FinishStageTwo(), System.Threading.Tasks.Task< TResult >.ContingentProperties.m_completionCountdown, System.Threading.Tasks.Task< TResult >.m_contingentProperties, System.Threading.Tasks.Task< TResult >.ContingentProperties.m_exceptionalChildren, System.Collections.Generic.LowLevelList< T >.RemoveAll(), and System.Threading.Tasks.Task< TResult >.s_IsExceptionObservedByParentPredicate.
Referenced by System.Threading.Tasks.Task< TResult >.ExecuteWithThreadLocal(), System.Threading.Tasks.Task< TResult >.InternalRunSynchronously(), System.Threading.Tasks.Task< TResult >.ScheduleAndStart(), and System.Threading.Tasks.Task< TResult >.TrySetException().