Terraria Decompiled: System.Threading.Tasks.Task.AtomicStateUpdate
AtomicStateUpdate() [1/2]
bool System.Threading.Tasks.Task< TResult >.AtomicStateUpdate (int newBits, int illegalBits) inline package
Definition at line 282 of file Task.2.cs.
        {
            SpinWait spinWait = default(SpinWait);
            for (;;)
            {
                int stateFlags = this.m_stateFlags;
                if ((stateFlags & illegalBits) != 0)
                {
                    break;
                }
                if (Interlocked.CompareExchange(ref this.m_stateFlags, stateFlags | newBits, stateFlags) == stateFlags)
                {
                    return true;
                }
                spinWait.SpinOnce();
            }
            return false;
        }
References System.Threading.Interlocked.CompareExchange(), System.Threading.Tasks.Task< TResult >.m_stateFlags, and System.Threading.SpinWait.SpinOnce().
Referenced by System.Threading.Tasks.Task< TResult >.ExecuteEntry(), System.Threading.Tasks.Task< TResult >.Finish(), System.Threading.Tasks.Task< TResult >.InternalCancel(), System.Threading.Tasks.Task< TResult >.MarkStarted(), System.Threading.Tasks.Task< TResult >.SetNotificationForWaitCompletion(), System.Threading.Tasks.Task< TResult >.TrySetCanceled(), and System.Threading.Tasks.Task< TResult >.TrySetException().