Terraria Decompiled: System.Threading.Tasks.Task.ConfigureAwait
ConfigureAwait() [1/2]
ConfiguredTaskAwaitable System.Threading.Tasks.Task< TResult >.ConfigureAwait (bool continueOnCapturedContext) inline
Definition at line 1314 of file Task.2.cs.
        {
            return new ConfiguredTaskAwaitable(this, continueOnCapturedContext);
        }
Referenced by System.IO.BufferedStream.CopyToAsyncCore(), System.IO.Stream.CopyToAsyncInternal(), System.IO.StreamWriter.DisposeAsyncCore(), System.IO.Stream.FinishWriteAsync(), System.IO.BufferedStream.FlushAsyncInternal(), System.IO.StreamWriter.FlushAsyncInternal(), System.IO.BufferedStream.FlushWriteAsync(), System.IO.Stream.g__FinishReadAsync(), System.IO.File.InternalReadAllBytesAsync(), System.IO.File.InternalReadAllTextAsync(), System.IO.File.InternalWriteAllBytesAsync(), System.IO.File.InternalWriteAllLinesAsync(), System.IO.File.InternalWriteAllTextAsync(), System.Threading.Tasks.TaskToApm.InvokeCallbackWhenTaskCompletes(), System.IO.BufferedStream.d__34.MoveNext(), System.IO.BufferedStream.d__38.MoveNext(), System.IO.BufferedStream.d__42.MoveNext(), System.IO.BufferedStream.d__51.MoveNext(), System.IO.BufferedStream.d__63.MoveNext(), System.IO.BufferedStream.d__71.MoveNext(), System.IO.StreamReader.d__61.MoveNext(), System.IO.StreamReader.d__63.MoveNext(), System.IO.StreamReader.d__66.MoveNext(), System.IO.StreamWriter.d__33.MoveNext(), System.Threading.SemaphoreSlim.d__32.MoveNext(), System.Threading.Tasks.ForceAsyncAwaiter.OnCompleted(), System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable< TResult >.ConfiguredValueTaskAwaiter.OnCompleted(), System.IO.StreamReader.ReadAsyncInternal(), System.IO.StreamReader.ReadBufferAsync(), System.IO.BufferedStream.ReadFromUnderlyingStreamAsync(), System.IO.StreamReader.ReadLineAsyncInternal(), System.IO.StreamReader.ReadToEndAsyncInternal(), System.Threading.Tasks.ForceAsyncAwaiter.UnsafeOnCompleted(), System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable< TResult >.ConfiguredValueTaskAwaiter.UnsafeOnCompleted(), System.Threading.SemaphoreSlim.WaitUntilCountOrTimeoutAsync(), System.IO.StreamWriter.WriteAsyncInternal(), System.IO.StreamWriter.WriteAsyncInternal(), System.IO.StreamWriter.WriteAsyncInternal(), and System.IO.BufferedStream.WriteToUnderlyingStreamAsync().