Terraria Decompiled: System.Threading.Tasks.Task.WaitAny
WaitAny() [4/5]
static int System.Threading.Tasks.Task< TResult >.WaitAny (Task< TResult >[] tasks, int millisecondsTimeout, CancellationToken cancellationToken) inline static
Definition at line 2290 of file Task.2.cs.
        {
            if (tasks == null)
            {
                throw new ArgumentNullException("tasks");
            }
            if (millisecondsTimeout < -1)
            {
                throw new ArgumentOutOfRangeException("millisecondsTimeout");
            }
            cancellationToken.ThrowIfCancellationRequested();
            int num = -1;
            for (int i = 0; i < tasks.Length; i++)
            {
                Task task = tasks[i];
                if (task == null)
                {
                    throw new ArgumentException("The tasks array included at least one null element.", "tasks");
                }
                if (num == -1 && task.IsCompleted)
                {
                    num = i;
                }
            }
            if (num == -1 && tasks.Length != 0)
            {
                Task<Task> task2 = TaskFactory.CommonCWAnyLogic(tasks);
                if (task2.Wait(millisecondsTimeout, cancellationToken))
                {
                    num = Array.IndexOf<Task>(tasks, task2.Result);
                }
            }
            GC.KeepAlive(tasks);
            return num;
        }
References System.Threading.Tasks.TaskFactory< TResult >.CommonCWAnyLogic(), System.Array.IndexOf(), System.GC.KeepAlive(), System.Threading.Tasks.Task< TResult >.Result, System.task, System.Threading.CancellationToken.ThrowIfCancellationRequested(), and System.Threading.Tasks.Task< TResult >.Wait().