Terraria Decompiled: System.Threading.Tasks.Task.HandleException
HandleException()
void System.Threading.Tasks.Task< TResult >.HandleException (Exception unhandledException) inline private
Definition at line 1295 of file Task.2.cs.
        {
            OperationCanceledException ex = unhandledException as OperationCanceledException;
            if (ex != null && this.IsCancellationRequested && this.m_contingentProperties.m_cancellationToken == ex.CancellationToken)
            {
                this.SetCancellationAcknowledged();
                this.AddException(ex, true);
                return;
            }
            this.AddException(unhandledException);
        }
References System.Threading.Tasks.Task< TResult >.AddException(), System.OperationCanceledException.CancellationToken, System.Threading.Tasks.Task< TResult >.IsCancellationRequested, System.Threading.Tasks.Task< TResult >.m_contingentProperties, and System.Threading.Tasks.Task< TResult >.SetCancellationAcknowledged().
Referenced by System.Threading.Tasks.Task< TResult >.Execute().