Terraria Decompiled: System.Threading.Tasks.Task.WhenAny
WhenAny() [2/2]
static Task< Task > System.Threading.Tasks.Task< TResult >.WhenAny (params Task< TResult >[] tasks) inline static
Definition at line 2664 of file Task.2.cs.
        {
            if (tasks == null)
            {
                throw new ArgumentNullException("tasks");
            }
            if (tasks.Length == 0)
            {
                throw new ArgumentException("The tasks argument contains no tasks.", "tasks");
            }
            int num = tasks.Length;
            Task[] array = new Task[num];
            for (int i = 0; i < num; i++)
            {
                Task task = tasks[i];
                if (task == null)
                {
                    throw new ArgumentException("The tasks argument included a null value.", "tasks");
                }
                array[i] = task;
            }
            return TaskFactory.CommonCWAnyLogic(array);
        }
References System.array, System.Threading.Tasks.TaskFactory< TResult >.CommonCWAnyLogic(), and System.task.
Referenced by System.Threading.SemaphoreSlim.d__32.MoveNext(), System.Threading.SemaphoreSlim.WaitUntilCountOrTimeoutAsync(), System.Threading.Tasks.Task< TResult >.WhenAny< TResult >(), and System.Threading.Tasks.Task< TResult >.WhenAny< TResult >().