Terraria Decompiled: System.Threading.Tasks.Task.RemoveContinuation
RemoveContinuation()
void System.Threading.Tasks.Task< TResult >.RemoveContinuation (object continuationObject) inline package
Definition at line 2026 of file Task.2.cs.
        {
            object continuationObject2 = this.m_continuationObject;
            if (continuationObject2 == Task.s_taskCompletionSentinel)
            {
                return;
            }
            LowLevelListWithIList<object> lowLevelListWithIList = continuationObject2 as LowLevelListWithIList<object>;
            if (lowLevelListWithIList == null)
            {
                if (Interlocked.CompareExchange(ref this.m_continuationObject, new LowLevelListWithIList<object>(), continuationObject) == continuationObject)
                {
                    return;
                }
                lowLevelListWithIList = this.m_continuationObject as LowLevelListWithIList<object>;
            }
            if (lowLevelListWithIList != null)
            {
                LowLevelListWithIList<object> lowLevelListWithIList2 = lowLevelListWithIList;
                lock (lowLevelListWithIList2)
                {
                    if (this.m_continuationObject != Task.s_taskCompletionSentinel)
                    {
                        int num = lowLevelListWithIList.IndexOf(continuationObject);
                        if (num != -1)
{
                            lowLevelListWithIList[num] = null;
                        }
                    }
                }
            }
        }
References System.Threading.Interlocked.CompareExchange(), System.Collections.Generic.LowLevelList< T >.IndexOf(), System.Threading.Tasks.Task< TResult >.m_continuationObject, and System.Threading.Tasks.Task< TResult >.s_taskCompletionSentinel.
Referenced by System.Threading.Tasks.Task< TResult >.SpinThenBlockingWait(), and System.Threading.Tasks.Task< TResult >.WaitAllBlockingCore().