Terraria Decompiled: Terraria.GameContent.Biomes.CaveHouse.HouseUtils.CreateRooms_BigAbandonedHouses
CreateRooms_BigAbandonedHouses()
static List< Rectangle > Terraria.GameContent.Biomes.CaveHouse.HouseUtils.CreateRooms_BigAbandonedHouses (Point origin) inline static private
Definition at line 68 of file HouseUtils.cs.
        {
            List<Rectangle> list = new List<Rectangle>();
            Point point;
            if (!WorldUtils.Find(origin, Searches.Chain(new Searches.Down(200), new GenCondition[]
            {
                new Conditions.IsSolid()
            }), out point) || point == origin)
            {
                return new List<Rectangle>();
            }
            Rectangle rectangle = HouseUtils.FindRoom(point);
            int randomizedRoomCountInABigAbandonedHouse = HouseUtils.GetRandomizedRoomCountInABigAbandonedHouse();
            if (randomizedRoomCountInABigAbandonedHouse == 0)
            {
                return list;
            }
            for (int i = 0; i < randomizedRoomCountInABigAbandonedHouse; i++)
            {
                Rectangle rectangle2 = HouseUtils.FindRoom_BigAbandonedHouses(new Point(rectangle.Center.X, rectangle.Y + 1), rectangle);
                list.Add(rectangle2);
                rectangle = rectangle2;
            }
            for (int j = 0; j < list.Count; j++)
            {
                list[j].Y += 3;
            }
            return list;
        }
References Microsoft.Xna.Framework.Rectangle.Center, Terraria.WorldBuilding.Searches.Chain(), Terraria.WorldBuilding.WorldUtils.Find(), Terraria.GameContent.Biomes.CaveHouse.HouseUtils.FindRoom(), Terraria.GameContent.Biomes.CaveHouse.HouseUtils.FindRoom_BigAbandonedHouses(), Terraria.GameContent.Biomes.CaveHouse.HouseUtils.GetRandomizedRoomCountInABigAbandonedHouse(), System.list, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Rectangle.Y.
Referenced by Terraria.GameContent.Biomes.CaveHouse.HouseUtils.CreateRooms().