Terraria Decompiled: System.Threading.Tasks.Task.WhenAll
WhenAll() [1/2]
static Task System.Threading.Tasks.Task< TResult >.WhenAll (IEnumerable< Task< TResult > > tasks) inline static
Definition at line 2516 of file Task.2.cs.
        {
            Task[] array = tasks as Task[];
            if (array != null)
            {
                return Task.WhenAll(array);
            }
            ICollection<Task> collection = tasks as ICollection<Task>;
            if (collection != null)
            {
                int num = 0;
                array = new Task[collection.Count];
                foreach (Task task in tasks)
                {
                    if (task == null)
                    {
                        throw new ArgumentException("The tasks argument included a null value.", "tasks");
                    }
                    array[num++] = task;
                }
                return Task.InternalWhenAll(array);
            }
            if (tasks == null)
            {
                throw new ArgumentNullException("tasks");
            }
            LowLevelListWithIList<Task> lowLevelListWithIList = new LowLevelListWithIList<Task>();
            foreach (Task task2 in tasks)
            {
                if (task2 == null)
                {
                    throw new ArgumentException("The tasks argument included a null value.", "tasks");
                }
                lowLevelListWithIList.Add(task2);
            }
            return Task.InternalWhenAll(lowLevelListWithIList.ToArray());
        }
References System.array, System.collection, System.Threading.Tasks.Task< TResult >.InternalWhenAll(), System.task, and System.Threading.Tasks.Task< TResult >.WhenAll().
Referenced by System.Threading.Tasks.Task< TResult >.WhenAll(), and System.Threading.Tasks.Task< TResult >.WhenAll< TResult >().