Terraria Decompiled: System.Threading.Tasks.Task.AddExceptionsForCompletedTask
AddExceptionsForCompletedTask()
static void System.Threading.Tasks.Task< TResult >.AddExceptionsForCompletedTask (ref LowLevelListWithIList< Exception > exceptions, Task< TResult > t) inline static package
Definition at line 2241 of file Task.2.cs.
        {
            AggregateException exceptions2 = t.GetExceptions(true);
            if (exceptions2 != null)
            {
                t.UpdateExceptionObservedStatus();
                if (exceptions == null)
                {
                    exceptions = new LowLevelListWithIList<Exception>(exceptions2.InnerExceptions.Count);
                }
                exceptions.AddRange(exceptions2.InnerExceptions);
            }
        }
References System.exceptions, System.Threading.Tasks.Task< TResult >.GetExceptions(), System.AggregateException.InnerExceptions, and System.Threading.Tasks.Task< TResult >.UpdateExceptionObservedStatus().
Referenced by System.Threading.Tasks.Task< TResult >.WaitAll().