Terraria Decompiled: System.Threading.Tasks.Task.FinishStageThree
FinishStageThree()
void System.Threading.Tasks.Task< TResult >.FinishStageThree () inline package
Definition at line 1167 of file Task.2.cs.
        {
            this.m_action = null;
            if (this.m_parent != null && (this.m_parent.CreationOptions & TaskCreationOptions.DenyChildAttach) == TaskCreationOptions.None && (this.m_stateFlags & 65535 & 4) != 0)
            {
                this.m_parent.ProcessChildCompletion(this);
            }
            this.FinishContinuations();
        }
References System.Threading.Tasks.Task< TResult >.CreationOptions, System.Threading.Tasks.Task< TResult >.FinishContinuations(), System.Threading.Tasks.Task< TResult >.m_parent, and System.Threading.Tasks.Task< TResult >.ProcessChildCompletion().
Referenced by System.Threading.Tasks.Task< TResult >.CancellationCleanupLogic(), and System.Threading.Tasks.Task< TResult >.FinishStageTwo().