Terraria Decompiled: Terraria.GameContent.Biomes.CaveHouse.HouseUtils.CreateBuilder
CreateBuilder()
static HouseBuilder Terraria.GameContent.Biomes.CaveHouse.HouseUtils.CreateBuilder (Point origin, StructureMap structures) inline static
Definition at line 13 of file HouseUtils.cs.
        {
            List<Rectangle> list = HouseUtils.CreateRooms(origin);
            if (list.Count == 0 || !HouseUtils.AreRoomLocationsValid(list))
            {
                return HouseBuilder.Invalid;
            }
            HouseType houseType = HouseUtils.GetHouseType(list);
            if (!HouseUtils.AreRoomsValid(list, structures, houseType))
            {
                return HouseBuilder.Invalid;
            }
            switch (houseType)
            {
            case HouseType.Wood:
                return new WoodHouseBuilder(list);
            case HouseType.Ice:
                return new IceHouseBuilder(list);
            case HouseType.Desert:
                return new DesertHouseBuilder(list);
            case HouseType.Jungle:
                return new JungleHouseBuilder(list);
            case HouseType.Mushroom:
                return new MushroomHouseBuilder(list);
            case HouseType.Granite:
                return new GraniteHouseBuilder(list);
            case HouseType.Marble:
                return new MarbleHouseBuilder(list);
            default:
                return new WoodHouseBuilder(list);
            }
        }
References Terraria.GameContent.Biomes.CaveHouse.HouseUtils.AreRoomLocationsValid(), Terraria.GameContent.Biomes.CaveHouse.HouseUtils.AreRoomsValid(), Terraria.GameContent.Biomes.CaveHouse.HouseUtils.CreateRooms(), Terraria.GameContent.Biomes.CaveHouse.HouseUtils.GetHouseType(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.Invalid, and System.list.
Referenced by Terraria.GameContent.Biomes.CaveHouseBiome.Place().