Terraria Decompiled: Terraria.Social.Steam.WorkshopHelper.UGCBased.PublishedItemsFinder.LoadHooks
LoadHooks()
void Terraria.Social.Steam.WorkshopHelper.UGCBased.PublishedItemsFinder.LoadHooks () inline private
Definition at line 194 of file WorkshopHelper.cs.
                {
                    this.OnSteamUGCQueryCompletedCallResult = CallResult<SteamUGCQueryCompleted_t>.Create(new CallResult<SteamUGCQueryCompleted_t>.APIDispatchDelegate(this.OnSteamUGCQueryCompleted));
                    this.OnSteamUGCRequestUGCDetailsResultCallResult = CallResult<SteamUGCRequestUGCDetailsResult_t>.Create(new CallResult<SteamUGCRequestUGCDetailsResult_t>.APIDispatchDelegate(this.OnSteamUGCRequestUGCDetailsResult));
                }
References Steamworks.CallResult< T >.Create(), Terraria.Social.Steam.WorkshopHelper.UGCBased.PublishedItemsFinder.OnSteamUGCQueryCompleted(), and Terraria.Social.Steam.WorkshopHelper.UGCBased.PublishedItemsFinder.OnSteamUGCRequestUGCDetailsResult().
Referenced by Terraria.Social.Steam.WorkshopHelper.UGCBased.PublishedItemsFinder.Create().