Terraria Decompiled: System.Globalization.GregorianCalendarHelper.GetDatePart
GetDatePart()
virtual int System.Globalization.GregorianCalendarHelper.GetDatePart (long ticks, int part) inline package virtual
Definition at line 103 of file GregorianCalendarHelper.cs.
        {
            this.CheckTicksRange(ticks);
            int i = (int)(ticks / 864000000000L);
            int num = i / 146097;
            i -= num * 146097;
            int num2 = i / 36524;
            if (num2 == 4)
            {
                num2 = 3;
            }
            i -= num2 * 36524;
            int num3 = i / 1461;
            i -= num3 * 1461;
            int num4 = i / 365;
            if (num4 == 4)
            {
                num4 = 3;
            }
            if (part == 0)
            {
                return num * 400 + num2 * 100 + num3 * 4 + num4 + 1;
            }
            i -= num4 * 365;
            if (part == 1)
            {
                return i + 1;
            }
            int[] array = ((num4 == 3 && (num3 != 24 || num2 == 3)) ? GregorianCalendarHelper.DaysToMonth366 : GregorianCalendarHelper.DaysToMonth365);
            int num5 = i >> 6;
            while (i >= array[num5])
            {
                num5++;
            }
            if (part == 2)
            {
                return num5;
            }
            return i - array[num5 - 1] + 1;
        }
References System.array, System.Globalization.GregorianCalendarHelper.CheckTicksRange(), System.Globalization.GregorianCalendarHelper.DaysToMonth365, int, and System.L.
Referenced by System.Globalization.GregorianCalendarHelper.AddMonths(), System.Globalization.GregorianCalendarHelper.GetDayOfMonth(), System.Globalization.GregorianCalendarHelper.GetDayOfYear(), System.Globalization.GregorianCalendarHelper.GetMonth(), and System.Globalization.GregorianCalendarHelper.GetYear().