Terraria Decompiled: System.Globalization.GregorianCalendarHelper.AddMonths
AddMonths()
DateTime System.Globalization.GregorianCalendarHelper.AddMonths (DateTime time, int months) inline
Definition at line 189 of file GregorianCalendarHelper.cs.
        {
            if (months < -120000 || months > 120000)
            {
                throw new ArgumentOutOfRangeException("months", string.Format(CultureInfo.CurrentCulture, Environment.GetResourceString("Valid values are between {0} and {1}, inclusive."), -120000, 120000));
            }
            this.CheckTicksRange(time.Ticks);
            int num = this.GetDatePart(time.Ticks, 0);
            int num2 = this.GetDatePart(time.Ticks, 2);
            int num3 = this.GetDatePart(time.Ticks, 3);
            int num4 = num2 - 1 + months;
            if (num4 >= 0)
            {
                num2 = num4 % 12 + 1;
                num += num4 / 12;
            }
            else
            {
                num2 = 12 + (num4 + 1) % 12;
                num += (num4 - 11) / 12;
            }
            int[] array = ((num % 4 == 0 && (num % 100 != 0 || num % 400 == 0)) ? GregorianCalendarHelper.DaysToMonth366 : GregorianCalendarHelper.DaysToMonth365);
            int num5 = array[num2] - array[num2 - 1];
            if (num3 > num5)
            {
                num3 = num5;
            }
            long num6 = GregorianCalendarHelper.DateToTicks(num, num2, num3) + time.Ticks % 864000000000L;
            Calendar.CheckAddResult(num6, this.m_Cal.MinSupportedDateTime, this.m_Cal.MaxSupportedDateTime);
            return new DateTime(num6);
        }
References System.array, System.Globalization.Calendar.CheckAddResult(), System.Globalization.GregorianCalendarHelper.CheckTicksRange(), System.Globalization.CultureInfo.CurrentCulture, System.DateTime, System.Globalization.GregorianCalendarHelper.DateToTicks(), System.Globalization.GregorianCalendarHelper.DaysToMonth365, System.Globalization.Format, System.Globalization.GregorianCalendarHelper.GetDatePart(), System.Environment.GetResourceString(), System.L, System.Globalization.GregorianCalendarHelper.m_Cal, System.Globalization.Calendar.MinSupportedDateTime, and System.DateTime.Ticks.
Referenced by System.Globalization.JapaneseCalendar.AddMonths(), System.Globalization.KoreanCalendar.AddMonths(), System.Globalization.TaiwanCalendar.AddMonths(), System.Globalization.ThaiBuddhistCalendar.AddMonths(), and System.Globalization.GregorianCalendarHelper.AddYears().