Terraria Decompiled: System.Globalization.GregorianCalendarHelper.ToDateTime
ToDateTime()
DateTime System.Globalization.GregorianCalendarHelper.ToDateTime (int year, int month, int day, int hour, int minute, int second, int millisecond, int era) inline
Definition at line 379 of file GregorianCalendarHelper.cs.
        {
            year = this.GetGregorianYear(year, era);
            long num = GregorianCalendarHelper.DateToTicks(year, month, day) + GregorianCalendarHelper.TimeToTicks(hour, minute, second, millisecond);
            this.CheckTicksRange(num);
            return new DateTime(num);
        }
References System.Globalization.GregorianCalendarHelper.CheckTicksRange(), System.DateTime, System.Globalization.GregorianCalendarHelper.DateToTicks(), System.Globalization.GregorianCalendarHelper.GetGregorianYear(), and System.Globalization.GregorianCalendarHelper.TimeToTicks().
Referenced by System.Globalization.JapaneseCalendar.ToDateTime(), System.Globalization.KoreanCalendar.ToDateTime(), System.Globalization.TaiwanCalendar.ToDateTime(), and System.Globalization.ThaiBuddhistCalendar.ToDateTime().