Terraria Decompiled: ReLogic.Localization.IME.WindowsIme.PreFilterMessage
PreFilterMessage()
bool ReLogic.Localization.IME.WindowsIme.PreFilterMessage (ref Message message) inline
Definition at line 90 of file WindowsIme.cs.
        {
            if (message.Msg == 8)
            {
                ReLogic.Localization.IME.Windows.NativeMethods.ImeUi_Enable(false);
                this._isFocused = false;
                this._visibleUnfocusedCandidateWindow = false;
                return true;
            }
            if (message.Msg == 7)
            {
                if (base.IsEnabled)
                {
                    ReLogic.Localization.IME.Windows.NativeMethods.ImeUi_Enable(true);
                }
                this._isFocused = true;
                return true;
            }
            if (!base.IsEnabled)
            {
                return false;
            }
            bool flag = false;
            IntPtr lparam = message.LParam;
            ReLogic.Localization.IME.Windows.NativeMethods.ImeUi_ProcessMessage(message.HWnd, message.Msg, message.WParam, ref lparam, ref flag);
            message.LParam = lparam;
            if (flag)
            {
                return true;
            }
            int msg = message.Msg;
            if (msg <= 258)
            {
                if (msg == 81)
                {
                    return true;
                }
                if (msg != 256)
                {
                    if (msg == 258)
                    {
                        base.OnKeyPress((char)message.WParam.ToInt32());
                    }
                }
                else
                {
                    bool flag2 = false;
                    uint? num = default(uint?);
                    if ((int)message.WParam == 229 && ReLogic.Localization.IME.Windows.NativeMethods.ImeUi_GetPrimaryLanguage() == 17)
                    {
                        if (string.IsNullOrEmpty(this.CompositionString))
{
                            this._visibleUnfocusedCandidateWindow = false;
                        }
                        else if (!this._visibleUnfocusedCandidateWindow)
{
                            uint num2 = ReLogic.Localization.IME.Windows.NativeMethods.ImmGetVirtualKey(message.HWnd);
                            if (num2 == 8U || num2 == 27U)
{
                                this._visibleUnfocusedCandidateWindow = true;
                            }
                            if (num2 == 9U)
{
                                num = this.SelectedCandidate;
                            }
                        }
                        else
{
                            uint num3 = ReLogic.Localization.IME.Windows.NativeMethods.ImmGetVirtualKey(message.HWnd);
                            if (num3 == 40U || num3 == 9U)
{
                                this._visibleUnfocusedCandidateWindow = false;
                                uint? num4 = this.SelectedCandidate;
                                uint num5 = 0U;
                                flag2 = (num4.GetValueOrDefault() == num5) & (num4 != null);
                            }
                        }
                    }
                    if (!ReLogic.Localization.IME.Windows.NativeMethods.ImeUi_ShouldIgnoreHotKey(ref message))
                    {
                        ReLogic.OS.Windows.NativeMethods.TranslateMessage(ref message);
                    }
                    if (flag2)
                    {
                        uint? num4 = this.SelectedCandidate;
                        uint num5 = 1U;
                        if ((num4.GetValueOrDefault() == num5) & (num4 != null))
{
                            ReLogic.Localization.IME.Windows.NativeMethods.ImeUi_SetCandidateSelection(0U);
                        }
                    }
                    if (num != null)
                    {
                        uint? num4 = this.SelectedCandidate;
                        uint? num6 = num;
                        if ((num4.GetValueOrDefault() == num6.GetValueOrDefault()) & (num4 != null == (num6 != null)))
{
                            ReLogic.Localization.IME.Windows.NativeMethods.ImeUi_SetCandidateSelection(0U);
                        }
                    }
                }
            }
            else
            {
                if (msg == 269)
                {
                    return true;
                }
                if (msg != 641)
                {
                    if (msg == 642)
                    {
                        int num7 = message.WParam.ToInt32();
                        if (num7 == 5 && ReLogic.Localization.IME.Windows.NativeMethods.ImeUi_GetPrimaryLanguage() == 17)
{
                            this._visibleUnfocusedCandidateWindow = true;
                        }
                        else if (num7 == 4)
{
                            this._visibleUnfocusedCandidateWindow = false;
                        }
                        return true;
                    }
                }
                else
                {
                    message.LParam = IntPtr.Zero;
                }
            }
            return false;
        }
References ReLogic.Localization.IME.WindowsIme._visibleUnfocusedCandidateWindow, ReLogic.Localization.IME.WindowsIme.CompositionString, ReLogic.Localization.IME.Windows.NativeMethods.ImeUi_Enable(), ReLogic.Localization.IME.Windows.NativeMethods.ImeUi_GetPrimaryLanguage(), ReLogic.Localization.IME.Windows.NativeMethods.ImeUi_ProcessMessage(), ReLogic.Localization.IME.Windows.NativeMethods.ImeUi_SetCandidateSelection(), ReLogic.Localization.IME.Windows.NativeMethods.ImeUi_ShouldIgnoreHotKey(), ReLogic.Localization.IME.Windows.NativeMethods.ImmGetVirtualKey(), ReLogic.Localization.IME.WindowsIme.SelectedCandidate, ReLogic.OS.Windows.NativeMethods.TranslateMessage(), System.U, and System.IntPtr.Zero.