Terraria Decompiled: System.Globalization.GregorianCalendarHelper.GetLeapMonth
GetLeapMonth()
int System.Globalization.GregorianCalendarHelper.GetLeapMonth (int year, int era) inline
Definition at line 354 of file GregorianCalendarHelper.cs.
        {
            year = this.GetGregorianYear(year, era);
            return 0;
        }
References System.Globalization.GregorianCalendarHelper.GetGregorianYear().
Referenced by System.Globalization.JapaneseCalendar.GetLeapMonth(), System.Globalization.KoreanCalendar.GetLeapMonth(), System.Globalization.TaiwanCalendar.GetLeapMonth(), and System.Globalization.ThaiBuddhistCalendar.GetLeapMonth().