Terraria Decompiled: System.Globalization.GregorianCalendarHelper.IsLeapMonth
IsLeapMonth()
bool System.Globalization.GregorianCalendarHelper.IsLeapMonth (int year, int month, int era) inline
Definition at line 361 of file GregorianCalendarHelper.cs.
        {
            year = this.GetGregorianYear(year, era);
            if (month < 1 || month > 12)
            {
                throw new ArgumentOutOfRangeException("month", string.Format(CultureInfo.CurrentCulture, Environment.GetResourceString("Valid values are between {0} and {1}, inclusive."), 1, 12));
            }
            return false;
        }
References System.Globalization.CultureInfo.CurrentCulture, System.Globalization.Format, System.Globalization.GregorianCalendarHelper.GetGregorianYear(), and System.Environment.GetResourceString().
Referenced by System.Globalization.JapaneseCalendar.IsLeapMonth(), System.Globalization.KoreanCalendar.IsLeapMonth(), System.Globalization.TaiwanCalendar.IsLeapMonth(), and System.Globalization.ThaiBuddhistCalendar.IsLeapMonth().