Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldGenDebug.GenPassElement.GetPassIcon
GetPassIcon()
UIWorldGenDebug.GenPassElement.PassIconEntry Terraria.GameContent.UI.States.UIWorldGenDebug.GenPassElement.GetPassIcon (GenPass pass) inline private
Definition at line 1491 of file UIWorldGenDebug.cs.
            {
                if (UIWorldGenDebug.GenPassElement.passIcons.Count == 0)
                {
                    UIWorldGenDebug.GenPassElement.InitPassIcons();
                }
                UIWorldGenDebug.GenPassElement.PassIconEntry passIconEntry;
                if (!UIWorldGenDebug.GenPassElement.passIcons.TryGetValue(pass.Name, out passIconEntry))
                {
                    passIconEntry = UIWorldGenDebug.GenPassElement.PassIconEntry.FromBestiaryIcon(64);
                }
                return passIconEntry;
            }
References Terraria.GameContent.UI.States.UIWorldGenDebug.GenPassElement.PassIconEntry.FromBestiaryIcon(), Terraria.GameContent.UI.States.UIWorldGenDebug.GenPassElement.InitPassIcons(), Terraria.WorldBuilding.GenPass.Name, and Terraria.GameContent.UI.States.UIWorldGenDebug.GenPassElement.passIcons.
Referenced by Terraria.GameContent.UI.States.UIWorldGenDebug.GenPassElement.AddIcon().