Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldGenDebug.GenPassElement.SetColorsToHovered
SetColorsToHovered()
void Terraria.GameContent.UI.States.UIWorldGenDebug.GenPassElement.SetColorsToHovered () inline private
Definition at line 1654 of file UIWorldGenDebug.cs.
            {
                this.BackgroundColor = new Color(73, 94, 171);
                this.BorderColor = new Color(89, 116, 213);
                if (this.IsHighlighted)
                {
                    this.BackgroundColor = new Color(110, 30, 150);
                    this.BorderColor = new Color(171, 53, 255);
                }
                if (UIWorldGenDebug.CurrentTargetPass == this.Pass)
                {
                    this.BorderColor = new Color(255, 231, 69);
                }
                if (!this.Pass.Enabled)
                {
                    this.BorderColor = new Color(150, 150, 150) * 1f;
                    this.BackgroundColor = Color.Lerp(this.BackgroundColor, new Color(120, 120, 120), 0.5f) * 1f;
                }
            }
References Terraria.GameContent.UI.Elements.UIPanel.BackgroundColor, Microsoft.Xna.Framework.Graphics.Color, Terraria.GameContent.UI.States.UIWorldGenDebug.CurrentTargetPass, Terraria.WorldBuilding.GenPass.Enabled, Terraria.GameContent.UI.States.UIWorldGenDebug.GenPassElement.IsHighlighted, Microsoft.Xna.Framework.Color.Lerp(), and Terraria.GameContent.UI.States.UIWorldGenDebug.GenPassElement.Pass.
Referenced by Terraria.GameContent.UI.States.UIWorldGenDebug.GenPassElement.MouseOver(), and Terraria.GameContent.UI.States.UIWorldGenDebug.GenPassElement.RefreshColors().