Terraria Decompiled: Newtonsoft.Json.Utilities.CollectionUtils.ResolveEnumerableCollectionConstructor
ResolveEnumerableCollectionConstructor() [1/2]
static ConstructorInfo Newtonsoft.Json.Utilities.CollectionUtils.ResolveEnumerableCollectionConstructor (Type collectionType, Type collectionItemType) inline static
Definition at line 43 of file CollectionUtils.cs.
        {
            Type type = typeof(IList).MakeGenericType(new Type[] { collectionItemType });
            return CollectionUtils.ResolveEnumerableCollectionConstructor(collectionType, collectionItemType, type);
        }
References System.Type.MakeGenericType(), and Newtonsoft.Json.Utilities.CollectionUtils.ResolveEnumerableCollectionConstructor().
Referenced by Newtonsoft.Json.Serialization.JsonArrayContract.JsonArrayContract(), Newtonsoft.Json.Serialization.JsonDictionaryContract.JsonDictionaryContract(), and Newtonsoft.Json.Utilities.CollectionUtils.ResolveEnumerableCollectionConstructor().