Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldGenDebug.GenPassElement.GenPassElement
GenPassElement() [1/2]
Terraria.GameContent.UI.States.UIWorldGenDebug.GenPassElement.GenPassElement (UIWorldGenDebug parent, GenPass pass) inline
Definition at line 1521 of file UIWorldGenDebug.cs.
            {
                UIWorldGenDebug.GenPassElement.<>c__DisplayClass9_0 CS$<>8__locals1 = new UIWorldGenDebug.GenPassElement.<>c__DisplayClass9_0();
                CS$<>8__locals1.pass = pass;
                CS$<>8__locals1.parent = parent;
                base..ctor();
                CS$<>8__locals1.<>4__this = this;
                this.Pass = CS$<>8__locals1.pass;
                base.SetPadding(2f);
                this.Height.Set(96f, 0f);
                base.Append(new UIWorldGenDebug.TooltipElement(new Func<string>(this.GetTitle), new Func<string>(this.GetDescription)));
                UIImage uiimage = this.AddIcon();
                uiimage.IgnoresMouseInteraction = true;
                base.Append(uiimage);
                UIText indexText = new UIText(this.Index.ToString(), 0.5f, false)
                {
                    Left = StyleDimension.FromPixels(2f),
                    Top = StyleDimension.FromPixels(2f),
                    IgnoresMouseInteraction = true
                };
                base.Append(indexText);
                UIText text = new UIText(CS$<>8__locals1.pass.Name, 1f, false)
                {
                    Left = StyleDimension.FromPixels(32f),
                    Top = StyleDimension.FromPixels(4f),
                    IgnoresMouseInteraction = true
                };
                text.OnUpdate += delegate(UIElement e)
                {
                    text.TextColor = (CS$<>8__locals1.<>4__this.IsRunning ? Color.Yellow : (CS$<>8__locals1.<>4__this.Skipped ? Color.DarkGreen : (CS$<>8__locals1.<>4__this.HasCompleted ? new Color(0, 230, 0) : ((!CS$<>8__locals1.pass.Enabled) ? Color.DarkGray : Color.White))));
                    text.TextColor *= (CS$<>8__locals1.parent.MatchesSearch(CS$<>8__locals1.pass) ? 1f : 0.6f);
                    indexText.TextColor = text.TextColor;
                };
                base.Append(text);
                this.SetColorsToNotHovered();
                UIWorldGenDebug.UIImageButtonWithExtraIcon snapshotIcon = this.AddButton("Images/UI/ButtonBacking", "Images/UI/Camera_4", 72f, 3f, delegate
                {
                    if (Main.keyState.PressingAlt())
                    {
                        return;
                    }
                    if (CS$<>8__locals1.<>4__this.Snapshot == null)
                    {
                        UIWorldGenDebug.Controller.TryCreateSnapshot();
                        return;
                    }
                    if (!CS$<>8__locals1.<>4__this.Snapshot.Outdated)
                    {
                        UIWorldGenDebug.Controller.TryResetToSnapshot(CS$<>8__locals1.pass);
                    }
                }, new Func<string>(this.GetSnapshotButtonTitle), new Func<string>(this.GetSnapshotButtonDescription));
                snapshotIcon.OnUpdate += delegate(UIElement e)
                {
                    if (CS$<>8__locals1.<>4__this.Snapshot != null)
                    {
                        snapshotIcon.SetIcon("Images/UI/Camera_4");
                    }
                    else if (UIWorldGenDebug.Controller.LastCompletedPass == CS$<>8__locals1.<>4__this.Pass)
                    {
                        snapshotIcon.SetIcon("Images/UI/Camera_7");
                    }
                    UIWorldGenDebug.SetButtonState(snapshotIcon, (CS$<>8__locals1.<>4__this.Pass.Enabled && (CS$<>8__locals1.<>4__this.Snapshot != null || UIWorldGenDebug.Controller.LastCompletedPass == CS$<>8__locals1.<>4__this.Pass)) ? UIWorldGenDebug.ButtonState.Enabled : UIWorldGenDebug.ButtonState.NotVisible);
                    if (CS$<>8__locals1.<>4__this.Snapshot != null && CS$<>8__locals1.<>4__this.Snapshot.Outdated)
                    {
                        snapshotIcon.IconColor = Color.PaleVioletRed;
                        return;
                    }
                    snapshotIcon.IconColor = Color.White;
                };
                snapshotIcon.OnRightClick += delegate(UIMouseEvent evt, UIElement e)
                {
                    if (CS$<>8__locals1.<>4__this.Snapshot != null)
                    {
                        UIWorldGenDebug.Controller.DeleteSnapshot(CS$<>8__locals1.pass);
                        UserInterface.ActiveInstance.ClearPointers();
                    }
                };
                snapshotIcon.Left = new StyleDimension(-28f, 1f);
                base.OnLeftClick += delegate(UIMouseEvent evt, UIElement e)
                {
                    if (CS$<>8__locals1.<>4__this != evt.Target)
                    {
                        return;
                    }
                    if (UIWorldGenDebug.spaceWasPressed)
                    {
                        return;
                    }
                    if (Main.keyState.PressingAlt())
                    {
                        CS$<>8__locals1.<>4__this.ToggleHighlight();
                        CS$<>8__locals1.<>4__this.SetColorsToHovered();
                        return;
                    }
                    if (!CS$<>8__locals1.pass.Enabled)
                    {
                        CS$<>8__locals1.parent.RangePassClickEvent(CS$<>8__locals1.<>4__this, delegate(UIWorldGenDebug.GenPassElement x)
{
                            x.Enable();
                            x.RefreshColors();
                        });
                        return;
                    }
                    if (CS$<>8__locals1.pass.Enabled)
                    {
                        UIWorldGenDebug.Controller.TryRunToEndOfPass(CS$<>8__locals1.pass, !Main.keyState.PressingShift(), true);
                    }
                };
                base.OnRightClick += delegate(UIMouseEvent evt, UIElement e)
                {
                    if (CS$<>8__locals1.pass.Enabled)
                    {
                        CS$<>8__locals1.parent.RangePassClickEvent(CS$<>8__locals1.<>4__this, delegate(UIWorldGenDebug.GenPassElement x)
{
                            x.Disable();
                            x.RefreshColors();
                        });
                    }
                };
            }
References Terraria.UI.UserInterface.ActiveInstance, Terraria.GameContent.UI.States.UIWorldGenDebug.GenPassElement.AddButton(), Terraria.GameContent.UI.States.UIWorldGenDebug.GenPassElement.AddIcon(), Terraria.UI.UserInterface.ClearPointers(), Microsoft.Xna.Framework.Graphics.Color, Terraria.GameContent.UI.States.UIWorldGenDebug.Controller, Microsoft.Xna.Framework.Color.DarkGray, Terraria.UI.StyleDimension.FromPixels(), Terraria.GameContent.UI.States.UIWorldGenDebug.GenPassElement.GetSnapshotButtonDescription(), Terraria.GameContent.UI.States.UIWorldGenDebug.GenPassElement.GetSnapshotButtonTitle(), Terraria.UI.UIElement.Height, Terraria.UI.UIElement.IgnoresMouseInteraction, Terraria.Main.keyState, Terraria.UI.UIElement.Left, Microsoft.Xna.Framework.Color.PaleVioletRed, Terraria.UI.StyleDimension.Set(), Terraria.GameContent.UI.States.UIWorldGenDebug.SetButtonState(), Terraria.GameContent.UI.States.UIWorldGenDebug.GenPassElement.SetColorsToNotHovered(), Terraria.GameContent.UI.States.UIWorldGenDebug.UIImageButtonWithExtraIcon.SetIcon(), Terraria.GameContent.UI.States.UIWorldGenDebug.spaceWasPressed, Terraria.UI.UIEvent.Target, System.text, Terraria.UI.UIElement.Top, System.Index.ToString(), and Microsoft.Xna.Framework.Color.White.