Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldGenDebug.GenPassElement.InitPassIcons
InitPassIcons()
static void Terraria.GameContent.UI.States.UIWorldGenDebug.GenPassElement.InitPassIcons () inline static private
Definition at line 1378 of file UIWorldGenDebug.cs.
            {
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.Terrain, UIWorldGenDebug.GenPassElement.PassIconEntry.FromBestiaryIcon(1));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.Skyblock, UIWorldGenDebug.GenPassElement.PassIconEntry.FromBestiaryIcon(26));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.DunesAndPyramidLocations, UIWorldGenDebug.GenPassElement.PassIconEntry.FromBestiaryIcon(4));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.OceanSand, UIWorldGenDebug.GenPassElement.PassIconEntry.FromBestiaryIcon(28));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.SandPatches, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(169));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.Tunnels, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(4501));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.MountainCaves, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(4510));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.DirtWallBackgrounds, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(30));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.RocksInDirt, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(3));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.DirtInRocks, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(2));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.Clay, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(133));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.SmallHoles, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(4538));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.DirtLayerCaves, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(4510));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.RockLayerCaves, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(4512));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.SurfaceCaves, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(4501));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.WavyCaves, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(4537));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.IceBiome, UIWorldGenDebug.GenPassElement.PassIconEntry.FromBestiaryIcon(6));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.Grass, UIWorldGenDebug.GenPassElement.PassIconEntry.FromImageFrame("Images/Tiles_3", 5, 45, 1));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.Jungle, UIWorldGenDebug.GenPassElement.PassIconEntry.FromBestiaryIcon(22));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.MudCavesToJungleGrass, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(745));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.DesertBiome, UIWorldGenDebug.GenPassElement.PassIconEntry.FromBestiaryIcon(3));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.GlowingMushroomPatches, UIWorldGenDebug.GenPassElement.PassIconEntry.FromBestiaryIcon(24));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.Marble, UIWorldGenDebug.GenPassElement.PassIconEntry.FromBestiaryIcon(29));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.Granite, UIWorldGenDebug.GenPassElement.PassIconEntry.FromBestiaryIcon(30));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.FloatingIslands, UIWorldGenDebug.GenPassElement.PassIconEntry.FromBestiaryIcon(26));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.DirtToMud, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(176));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.Silt, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(424));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.OresAndShinies, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(19));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.Webs, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(150));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.Underworld, UIWorldGenDebug.GenPassElement.PassIconEntry.FromBestiaryIcon(33));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.CorruptionAndCrimson, UIWorldGenDebug.GenPassElement.PassIconEntry.FromBestiaryIcon(7));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.Lakes, UIWorldGenDebug.GenPassElement.PassIconEntry.FromBestiaryIcon(28));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.StoneToIceAndSiltPlusMudIntoSlush, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(1103));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.DualDungeonsDitherSnake, UIWorldGenDebug.GenPassElement.PassIconEntry.FromBestiaryIcon(32));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.Dungeon, UIWorldGenDebug.GenPassElement.PassIconEntry.FromBestiaryIcon(32));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.MountainCaveOpenings, UIWorldGenDebug.GenPassElement.PassIconEntry.FromBestiaryIcon(2));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.BeachesAndOceanCleanup, UIWorldGenDebug.GenPassElement.PassIconEntry.FromBestiaryIcon(27));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.Gems, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(178));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.GravitatingSandCleanup, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(169));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.OceanCaves, UIWorldGenDebug.GenPassElement.PassIconEntry.FromBestiaryIcon(28));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.Shimmer, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(5340));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.DirtWallCleanup, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(2));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.Pyramids, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(607));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.DirtRockWallRunner, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(4501));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.LivingTrees, UIWorldGenDebug.GenPassElement.PassIconEntry.FromBestiaryIcon(0));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.LivingTreeWalls, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(1723));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.DemonAndCrimsonAltars, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(5467));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.SurfaceWaterInJungle, UIWorldGenDebug.GenPassElement.PassIconEntry.FromBestiaryIcon(22));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.LihzahrdTemple, UIWorldGenDebug.GenPassElement.PassIconEntry.FromBestiaryIcon(31));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.Beehives, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(1126));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.JungleShrines, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(680));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.SettleLiquids, UIWorldGenDebug.GenPassElement.PassIconEntry.FromBestiaryIcon(28));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.RemoveSurfaceWaterAboveSand, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(169));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.Oasis, UIWorldGenDebug.GenPassElement.PassIconEntry.FromBestiaryIcon(27));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.ShellPilesMarblePilesAndSpikePits, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(4090));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.SmoothWorld, UIWorldGenDebug.GenPassElement.PassIconEntry.FromBestiaryIcon(1));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.Waterfalls, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(2169));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.FragileIceOverIceBiomeWater, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(664));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.CaveWallVariety, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(4540));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.LifeCrystals, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(29));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.Statues, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(52));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.UndergroundHousesAndBuriedChests, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(306));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.SurfaceChests, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(48));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.ChestsInJungleShrines, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(680));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.UnderwaterChests, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(1298));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.SpiderCaves, UIWorldGenDebug.GenPassElement.PassIconEntry.FromBestiaryIcon(34));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.GemCaves, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(4644));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.MossAndMossCaves, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(4496));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.LihzahrdTemplePart2, UIWorldGenDebug.GenPassElement.PassIconEntry.FromBestiaryIcon(31));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.CaveWallsInEnclosedSpaces, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(4510));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.UndergroundJungleTrees, UIWorldGenDebug.GenPassElement.PassIconEntry.FromBestiaryIcon(23));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.FloatingIslandHouses, UIWorldGenDebug.GenPassElement.PassIconEntry.FromBestiaryIcon(26));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.QuickCleanup, UIWorldGenDebug.GenPassElement.PassIconEntry.FromBestiaryIcon(41));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.PotsGraveyardsAndBoulderPiles, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(222));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.Hellforges, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(221));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.SpreadingGrassOnSurfaceSunflowersEvilsOnSurfaceAndLavaCleanup, UIWorldGenDebug.GenPassElement.PassIconEntry.FromImageFrame("Images/Tiles_3", 5, 45, 1));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.SurfaceOreAndStone, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(19));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.FallenLogsAndWaterFeatures, UIWorldGenDebug.GenPassElement.PassIconEntry.FromBestiaryIcon(0));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.Traps, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(580));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.Piles, UIWorldGenDebug.GenPassElement.PassIconEntry.FromBestiaryIcon(1));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.SpawnPoint, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(224));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.SurfaceDirtWallsToGrassWalls, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(745));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.SpawnStarterNPCs, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(867));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.SunflowersPart2, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(63));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.Trees, UIWorldGenDebug.GenPassElement.PassIconEntry.FromBestiaryIcon(0));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.AlchemyHerbs, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(3093));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.DyePlants, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(1109));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.WebsInSpiderCavesAndHoneyPlusSpeleothemsInBeehives, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(150));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.GrassPlantsEvilPlantsAndPumpkinsOnSurface, UIWorldGenDebug.GenPassElement.PassIconEntry.FromImageFrame("Images/Tiles_3", 5, 45, 1));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.GlowingMushroomPlantsUndergroundAndJunglePlants, UIWorldGenDebug.GenPassElement.PassIconEntry.FromBestiaryIcon(25));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.JunglePlantsPart2, UIWorldGenDebug.GenPassElement.PassIconEntry.FromBestiaryIcon(23));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.Vines, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(3005));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.Flowers, UIWorldGenDebug.GenPassElement.PassIconEntry.FromImageFrame("Images/Tiles_3", 33, 45, 1));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.Mushrooms, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(5));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.ExposedGemsInIceBiome, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(182));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.ExposedGemsUnderground, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(4400));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.LongMoss, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(4496));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.DirtWallsIntoMudWallsInJungleAndJungleMinMax, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(4487));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.BeeLarvaInBeehives, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(2108));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.SettleLiquidsPart2AndNotTheBees, UIWorldGenDebug.GenPassElement.PassIconEntry.FromBestiaryIcon(28));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.CactusPalmTreesAndCoral, UIWorldGenDebug.GenPassElement.PassIconEntry.FromBestiaryIcon(3));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.TileCleanup, UIWorldGenDebug.GenPassElement.PassIconEntry.FromBestiaryIcon(41));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.LihzahrdAltar, UIWorldGenDebug.GenPassElement.PassIconEntry.FromBestiaryIcon(31));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.MicroBiomes, UIWorldGenDebug.GenPassElement.PassIconEntry.FromBestiaryIcon(0));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.LilypadsCattailsBambooAndSeaweed, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(4564));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.SpeleothemsAndGemTrees, UIWorldGenDebug.GenPassElement.PassIconEntry.FromBestiaryIcon(6));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.BrokenTrapCleanup, UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(580));
                UIWorldGenDebug.GenPassElement.passIcons.Add(GenPassNameID.FinalCleanup, UIWorldGenDebug.GenPassElement.PassIconEntry.FromBestiaryIcon(41));
            }
References Terraria.ID.GenPassNameID.AlchemyHerbs, Terraria.ID.GenPassNameID.BeachesAndOceanCleanup, Terraria.ID.GenPassNameID.Beehives, Terraria.ID.GenPassNameID.BeeLarvaInBeehives, Terraria.ID.GenPassNameID.BrokenTrapCleanup, Terraria.ID.GenPassNameID.CactusPalmTreesAndCoral, Terraria.ID.GenPassNameID.CaveWallsInEnclosedSpaces, Terraria.ID.GenPassNameID.CaveWallVariety, Terraria.ID.GenPassNameID.ChestsInJungleShrines, Terraria.ID.GenPassNameID.Clay, Terraria.ID.GenPassNameID.CorruptionAndCrimson, Terraria.ID.GenPassNameID.DemonAndCrimsonAltars, Terraria.ID.GenPassNameID.DesertBiome, Terraria.ID.GenPassNameID.DirtInRocks, Terraria.ID.GenPassNameID.DirtLayerCaves, Terraria.ID.GenPassNameID.DirtRockWallRunner, Terraria.ID.GenPassNameID.DirtToMud, Terraria.ID.GenPassNameID.DirtWallBackgrounds, Terraria.ID.GenPassNameID.DirtWallCleanup, Terraria.ID.GenPassNameID.DirtWallsIntoMudWallsInJungleAndJungleMinMax, Terraria.ID.GenPassNameID.DualDungeonsDitherSnake, Terraria.ID.GenPassNameID.DunesAndPyramidLocations, Terraria.ID.GenPassNameID.Dungeon, Terraria.ID.GenPassNameID.DyePlants, Terraria.ID.GenPassNameID.ExposedGemsInIceBiome, Terraria.ID.GenPassNameID.ExposedGemsUnderground, Terraria.ID.GenPassNameID.FallenLogsAndWaterFeatures, Terraria.ID.GenPassNameID.FinalCleanup, Terraria.ID.GenPassNameID.FloatingIslandHouses, Terraria.ID.GenPassNameID.FloatingIslands, Terraria.ID.GenPassNameID.Flowers, Terraria.ID.GenPassNameID.FragileIceOverIceBiomeWater, Terraria.GameContent.UI.States.UIWorldGenDebug.GenPassElement.PassIconEntry.FromBestiaryIcon(), Terraria.GameContent.UI.States.UIWorldGenDebug.GenPassElement.PassIconEntry.FromImageFrame(), Terraria.GameContent.UI.States.UIWorldGenDebug.GenPassElement.PassIconEntry.FromItem(), Terraria.ID.GenPassNameID.GemCaves, Terraria.ID.GenPassNameID.Gems, Terraria.ID.GenPassNameID.GlowingMushroomPatches, Terraria.ID.GenPassNameID.GlowingMushroomPlantsUndergroundAndJunglePlants, Terraria.ID.GenPassNameID.Granite, Terraria.ID.GenPassNameID.Grass, Terraria.ID.GenPassNameID.GrassPlantsEvilPlantsAndPumpkinsOnSurface, Terraria.ID.GenPassNameID.GravitatingSandCleanup, Terraria.ID.GenPassNameID.Hellforges, Terraria.ID.GenPassNameID.IceBiome, Terraria.ID.GenPassNameID.Jungle, Terraria.ID.GenPassNameID.JunglePlantsPart2, Terraria.ID.GenPassNameID.JungleShrines, Terraria.ID.GenPassNameID.Lakes, Terraria.ID.GenPassNameID.LifeCrystals, Terraria.ID.GenPassNameID.LihzahrdAltar, Terraria.ID.GenPassNameID.LihzahrdTemple, Terraria.ID.GenPassNameID.LihzahrdTemplePart2, Terraria.ID.GenPassNameID.LilypadsCattailsBambooAndSeaweed, Terraria.ID.GenPassNameID.LivingTrees, Terraria.ID.GenPassNameID.LivingTreeWalls, Terraria.ID.GenPassNameID.LongMoss, Terraria.ID.GenPassNameID.Marble, Terraria.ID.GenPassNameID.MicroBiomes, Terraria.ID.GenPassNameID.MossAndMossCaves, Terraria.ID.GenPassNameID.MountainCaveOpenings, Terraria.ID.GenPassNameID.MountainCaves, Terraria.ID.GenPassNameID.MudCavesToJungleGrass, Terraria.ID.GenPassNameID.Mushrooms, Terraria.ID.GenPassNameID.Oasis, Terraria.ID.GenPassNameID.OceanCaves, Terraria.ID.GenPassNameID.OceanSand, Terraria.ID.GenPassNameID.OresAndShinies, Terraria.GameContent.UI.States.UIWorldGenDebug.GenPassElement.passIcons, Terraria.ID.GenPassNameID.Piles, Terraria.ID.GenPassNameID.PotsGraveyardsAndBoulderPiles, Terraria.ID.GenPassNameID.Pyramids, Terraria.ID.GenPassNameID.QuickCleanup, Terraria.ID.GenPassNameID.RemoveSurfaceWaterAboveSand, Terraria.ID.GenPassNameID.RockLayerCaves, Terraria.ID.GenPassNameID.RocksInDirt, Terraria.ID.GenPassNameID.SandPatches, Terraria.ID.GenPassNameID.SettleLiquids, Terraria.ID.GenPassNameID.SettleLiquidsPart2AndNotTheBees, Terraria.ID.GenPassNameID.ShellPilesMarblePilesAndSpikePits, Terraria.ID.GenPassNameID.Shimmer, Terraria.ID.GenPassNameID.Silt, Terraria.ID.GenPassNameID.Skyblock, Terraria.ID.GenPassNameID.SmallHoles, Terraria.ID.GenPassNameID.SmoothWorld, Terraria.ID.GenPassNameID.SpawnPoint, Terraria.ID.GenPassNameID.SpawnStarterNPCs, Terraria.ID.GenPassNameID.SpeleothemsAndGemTrees, Terraria.ID.GenPassNameID.SpiderCaves, Terraria.ID.GenPassNameID.SpreadingGrassOnSurfaceSunflowersEvilsOnSurfaceAndLavaCleanup, Terraria.ID.GenPassNameID.Statues, Terraria.ID.GenPassNameID.StoneToIceAndSiltPlusMudIntoSlush, Terraria.ID.GenPassNameID.SunflowersPart2, Terraria.ID.GenPassNameID.SurfaceCaves, Terraria.ID.GenPassNameID.SurfaceChests, Terraria.ID.GenPassNameID.SurfaceDirtWallsToGrassWalls, Terraria.ID.GenPassNameID.SurfaceOreAndStone, Terraria.ID.GenPassNameID.SurfaceWaterInJungle, Terraria.ID.GenPassNameID.Terrain, Terraria.ID.GenPassNameID.TileCleanup, Terraria.ID.GenPassNameID.Traps, Terraria.ID.GenPassNameID.Trees, Terraria.ID.GenPassNameID.Tunnels, Terraria.ID.GenPassNameID.UndergroundHousesAndBuriedChests, Terraria.ID.GenPassNameID.UndergroundJungleTrees, Terraria.ID.GenPassNameID.UnderwaterChests, Terraria.ID.GenPassNameID.Underworld, Terraria.ID.GenPassNameID.Vines, Terraria.ID.GenPassNameID.Waterfalls, Terraria.ID.GenPassNameID.WavyCaves, Terraria.ID.GenPassNameID.Webs, and Terraria.ID.GenPassNameID.WebsInSpiderCavesAndHoneyPlusSpeleothemsInBeehives.
Referenced by Terraria.GameContent.UI.States.UIWorldGenDebug.GenPassElement.GetPassIcon().