Terraria Decompiled: Newtonsoft.Json.Utilities.CollectionUtils.ResolveEnumerableCollectionConstructor
ResolveEnumerableCollectionConstructor() [2/2]
static ConstructorInfo Newtonsoft.Json.Utilities.CollectionUtils.ResolveEnumerableCollectionConstructor (Type collectionType, Type collectionItemType, Type constructorArgumentType) inline static
Definition at line 50 of file CollectionUtils.cs.
        {
            Type type = typeof(IEnumerable).MakeGenericType(new Type[] { collectionItemType });
            ConstructorInfo constructorInfo = null;
            foreach (ConstructorInfo constructorInfo2 in collectionType.GetConstructors(20))
            {
                IList<ParameterInfo> parameters = constructorInfo2.GetParameters();
                if (parameters.Count == 1)
                {
                    Type parameterType = parameters[0].ParameterType;
                    if (type == parameterType)
                    {
                        constructorInfo = constructorInfo2;
                        break;
                    }
                    if (constructorInfo == null && parameterType.IsAssignableFrom(constructorArgumentType))
                    {
                        constructorInfo = constructorInfo2;
                    }
                }
            }
            return constructorInfo;
        }
References System.Collections.Generic.ICollection< T >.Count, System.Reflection.MethodBase.GetParameters(), System.Type.IsAssignableFrom(), and System.Type.MakeGenericType().