Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldGenDebug.GenPassElement.AddButton
AddButton()
UIWorldGenDebug.UIImageButtonWithExtraIcon Terraria.GameContent.UI.States.UIWorldGenDebug.GenPassElement.AddButton (string assetPath, string iconAsset, float x, float y, Action onClick, Func< string > getTitle, Func< string > getDescription = null) inline private
Definition at line 1347 of file UIWorldGenDebug.cs.
            {
                UIWorldGenDebug.UIImageButtonWithExtraIcon uiimageButtonWithExtraIcon = new UIWorldGenDebug.UIImageButtonWithExtraIcon(Main.Assets.Request<Texture2D>(assetPath, 1), null)
                {
                    Left = StyleDimension.FromPixelsAndPercent(x, 0f),
                    Top = StyleDimension.FromPixelsAndPercent(y, 0f)
                };
                if (!string.IsNullOrEmpty(iconAsset))
                {
                    uiimageButtonWithExtraIcon.SetIcon(iconAsset);
                }
                uiimageButtonWithExtraIcon.OnLeftClick += delegate(UIMouseEvent evt, UIElement e)
                {
                    onClick();
                };
                if (getTitle != null)
                {
                    uiimageButtonWithExtraIcon.Append(new UIWorldGenDebug.TooltipElement(getTitle, getDescription));
                }
                base.Append(uiimageButtonWithExtraIcon);
                return uiimageButtonWithExtraIcon;
            }
References Terraria.UI.UIElement.Append(), Terraria.Main.Assets, Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.UI.UIElement.Left, Terraria.GameContent.UI.States.UIWorldGenDebug.UIImageButtonWithExtraIcon.SetIcon(), and Terraria.UI.UIElement.Top.
Referenced by Terraria.GameContent.UI.States.UIWorldGenDebug.GenPassElement.GenPassElement().