Terraria Decompiled: Terraria.Chat.ChatCommandProcessor.ProcessIncomingMessage
ProcessIncomingMessage()
void Terraria.Chat.ChatCommandProcessor.ProcessIncomingMessage (ChatMessage message, int clientId) inline
Implements Terraria.Chat.IChatProcessor.
Definition at line 100 of file ChatCommandProcessor.cs.
        {
            IChatCommand chatCommand;
            if (this._commands.TryGetValue(message.CommandId, out chatCommand))
            {
                chatCommand.ProcessIncomingMessage(message.Text, (byte)clientId);
                message.Consume();
                return;
            }
            if (this._defaultCommand != null)
            {
                this._defaultCommand.ProcessIncomingMessage(message.Text, (byte)clientId);
                message.Consume();
            }
        }
References Terraria.Chat.ChatCommandProcessor._commands, Terraria.Chat.ChatCommandProcessor._defaultCommand, Terraria.Chat.ChatMessage.CommandId, Terraria.Chat.ChatMessage.Consume(), Terraria.Chat.Commands.IChatCommand.ProcessIncomingMessage(), and Terraria.Chat.ChatMessage.Text.
Referenced by Terraria.GameContent.NetModules.NetTextModule.DeserializeAsServer(), and Terraria.Main.DoUpdate_HandleChat().