Terraria Decompiled: System.Runtime.Remoting.Messaging.MonoMethodMessage.InitMessage
InitMessage()
void System.Runtime.Remoting.Messaging.MonoMethodMessage.InitMessage (RuntimeMethodInfo method, object[] out_args) inline package
Definition at line 14 of file MonoMethodMessage.cs.
        {
            this.method = method;
            ParameterInfo[] parametersInternal = method.GetParametersInternal();
            int num = parametersInternal.Length;
            this.args = new object[num];
            this.arg_types = new byte[num];
            this.asyncResult = null;
            this.call_type = CallType.Sync;
            this.names = new string[num];
            for (int i = 0; i < num; i++)
            {
                this.names[i] = parametersInternal[i].Name;
            }
            bool flag = out_args != null;
            int num2 = 0;
            for (int j = 0; j < num; j++)
            {
                bool isOut = parametersInternal[j].IsOut;
                byte b;
                if (parametersInternal[j].ParameterType.IsByRef)
                {
                    if (flag)
                    {
                        this.args[j] = out_args[num2++];
                    }
                    b = 2;
                    if (!isOut)
                    {
                        b |= 1;
                    }
                }
                else
                {
                    b = 1;
                    if (isOut)
                    {
                        b |= 4;
                    }
                }
                this.arg_types[j] = b;
            }
        }
References System.Runtime.Remoting.Messaging.MonoMethodMessage.arg_types, System.Runtime.Remoting.Messaging.MonoMethodMessage.args, System.Reflection.RuntimeMethodInfo.GetParametersInternal(), System.Reflection.ParameterInfo.IsOut, System.Runtime.Remoting.Messaging.MonoMethodMessage.method, System.Reflection.ParameterInfo.Name, and System.Runtime.Remoting.Messaging.MonoMethodMessage.names.
Referenced by System.Runtime.Remoting.Messaging.MonoMethodMessage.MonoMethodMessage(), and System.Runtime.Remoting.Messaging.MonoMethodMessage.MonoMethodMessage().