Terraria Decompiled: Terraria.Graphics.Renderers.LittleFlyingCritterParticle.Prepare
Prepare()
void Terraria.Graphics.Renderers.LittleFlyingCritterParticle.Prepare (LittleFlyingCritterParticle::FlyType type, Vector2 position, int duration, Color overrideColor = default(Color), int repelLifetimeDecay = 0) inline
Definition at line 52 of file LittleFlyingCritterParticle.cs.
        {
            this._type = type;
            this._variantRow = Main.rand.Next(8);
            this._variantColumn = ((Main.rand.Next(5) == 0) ? 1 : 0);
            this._spawnPosition = position;
            this._localPosition = position + Main.rand.NextVector2Circular(4f, 8f);
            this._neverGoBelowThis = position.Y + 8f;
            this.RandomizeVelocity();
            this._lifeTimeCounted = 0;
            this._lifeTimeTotal = 300 + Main.rand.Next(6) * 60;
            this._overrideColor = overrideColor;
            this._repelLifetimeDecay = repelLifetimeDecay;
        }
References Terraria.Main.rand, and Terraria.Graphics.Renderers.LittleFlyingCritterParticle.RandomizeVelocity().
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_NatureFly(), and Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_PooFly().