Terraria Decompiled: Terraria.Graphics.Renderers.LittleFlyingCritterParticle.Update
Update()
void Terraria.Graphics.Renderers.LittleFlyingCritterParticle.Update (ref ParticleRendererSettings settings) inline
Implements Terraria.Graphics.Renderers.IParticle.
Definition at line 88 of file LittleFlyingCritterParticle.cs.
        {
            int num = this._lifeTimeCounted + 1;
            this._lifeTimeCounted = num;
            if (num >= this._lifeTimeTotal)
            {
                this.ShouldBeRemovedFromRenderer = true;
            }
            float num2 = 0.02f;
            int num3 = 30;
            if (this._type == LittleFlyingCritterParticle.FlyType.ButterFly)
            {
                num2 = 0.01f;
                num3 = 600;
            }
            this._velocity += new Vector2((float)Math.Sign(this._spawnPosition.X - this._localPosition.X) * num2, (float)Math.Sign(this._spawnPosition.Y - this._localPosition.Y) * num2);
            if (this._lifeTimeCounted % num3 == 0 && Main.rand.Next(2) == 0)
            {
                this.RandomizeVelocity();
                if (Main.rand.Next(2) == 0)
                {
                    this._velocity /= 2f;
                }
            }
            this._addedVelocity *= 0.98f;
            if (this._addedVelocity.Length() < 0.01f)
            {
                this._addedVelocity = new Vector2(0f, 0f);
            }
            this._localPosition += this._velocity + this._addedVelocity;
            if (this._localPosition.Y > this._neverGoBelowThis)
            {
                this._localPosition.Y = this._neverGoBelowThis;
                if (this._velocity.Y > 0f)
                {
                    this._velocity.Y = this._velocity.Y * -1f;
                }
                if (this._addedVelocity.Y > 0f)
                {
                    this._addedVelocity.Y = this._addedVelocity.Y * -1f;
                }
            }
        }
References Terraria.Graphics.Renderers.LittleFlyingCritterParticle._addedVelocity, Terraria.Graphics.Renderers.LittleFlyingCritterParticle._lifeTimeCounted, Terraria.Graphics.Renderers.LittleFlyingCritterParticle._lifeTimeTotal, Terraria.Graphics.Renderers.LittleFlyingCritterParticle._localPosition, Terraria.Graphics.Renderers.LittleFlyingCritterParticle._neverGoBelowThis, Terraria.Graphics.Renderers.LittleFlyingCritterParticle._type, Terraria.Graphics.Renderers.LittleFlyingCritterParticle._velocity, Microsoft.Xna.Framework.Vector2.Length(), Terraria.Main.rand, Terraria.Graphics.Renderers.LittleFlyingCritterParticle.RandomizeVelocity(), System.Math.Sign(), Microsoft.Xna.Framework.Graphics.Vector2, and Microsoft.Xna.Framework.Vector2.Y.