Terraria Decompiled: Terraria.Graphics.Renderers.LittleFlyingCritterParticle.Draw_Fly
Draw_Fly()
void Terraria.Graphics.Renderers.LittleFlyingCritterParticle.Draw_Fly (ref ParticleRendererSettings settings, SpriteBatch spritebatch) inline private
Definition at line 174 of file LittleFlyingCritterParticle.cs.
        {
            Vector2 vector = this._velocity + this._addedVelocity;
            Texture2D value = TextureAssets.Extra[262].Value;
            int num = this._lifeTimeCounted % 6 / 3;
            Rectangle rectangle = value.Frame(1, 6, 0, num, 0, 0);
            Vector2 vector2 = new Vector2((float)((vector.X > 0f) ? 3 : 1), 3f);
            float num2 = Utils.Remap((float)this._lifeTimeCounted, 0f, 90f, 0f, 1f, true) * Utils.Remap((float)this._lifeTimeCounted, (float)(this._lifeTimeTotal - 90), (float)this._lifeTimeTotal, 1f, 0f, true);
            Color color = Lighting.GetColor(this._localPosition.ToTileCoordinates());
            if (this._overrideColor == default(Color))
            {
                spritebatch.Draw(value, settings.AnchorPosition + this._localPosition, new Rectangle?(rectangle), color * num2, 0f, vector2, 1f, (vector.X > 0f) ? SpriteEffects.FlipHorizontally : SpriteEffects.None, 0f);
                return;
            }
            Vector4 vector3 = this._overrideColor.ToVector4() * color.ToVector4();
            Color color2 = new Color(vector3);
            rectangle.Offset(0, 12);
            spritebatch.Draw(value, settings.AnchorPosition + this._localPosition, new Rectangle?(rectangle), color2 * num2, 0f, vector2, 1f, (vector.X > 0f) ? SpriteEffects.FlipHorizontally : SpriteEffects.None, 0f);
            rectangle.Offset(0, 12);
            spritebatch.Draw(value, settings.AnchorPosition + this._localPosition, new Rectangle?(rectangle), color * num2, 0f, vector2, 1f, (vector.X > 0f) ? SpriteEffects.FlipHorizontally : SpriteEffects.None, 0f);
        }
References Terraria.Graphics.Renderers.LittleFlyingCritterParticle._addedVelocity, Terraria.Graphics.Renderers.LittleFlyingCritterParticle._lifeTimeCounted, Terraria.Graphics.Renderers.LittleFlyingCritterParticle._lifeTimeTotal, Terraria.Graphics.Renderers.LittleFlyingCritterParticle._localPosition, Terraria.Graphics.Renderers.LittleFlyingCritterParticle._overrideColor, Microsoft.Xna.Framework.Graphics.Color, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.GameContent.TextureAssets.Extra, Terraria.Lighting.GetColor(), Microsoft.Xna.Framework.Rectangle.Offset(), Terraria.Utils.Remap(), Microsoft.Xna.Framework.Color.ToVector4(), System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, and Microsoft.Xna.Framework.Vector2.X.
Referenced by Terraria.Graphics.Renderers.LittleFlyingCritterParticle.Draw().