Terraria Decompiled: System.Security.AccessControl.NativeObjectSecurity.Win32SetHelper
Win32SetHelper()
int System.Security.AccessControl.NativeObjectSecurity.Win32SetHelper (NativeObjectSecurity::SetSecurityInfoNativeCall nativeCall, AccessControlSections includeSections) inline private
Definition at line 291 of file NativeObjectSecurity.cs.
        {
            if (includeSections == AccessControlSections.None)
            {
                return 0;
            }
            SecurityInfos securityInfos = (SecurityInfos)0;
            byte[] array = null;
            byte[] array2 = null;
            byte[] array3 = null;
            byte[] array4 = null;
            if ((includeSections & AccessControlSections.Owner) != AccessControlSections.None)
            {
                securityInfos |= SecurityInfos.Owner;
                SecurityIdentifier securityIdentifier = (SecurityIdentifier)base.GetOwner(typeof(SecurityIdentifier));
                if (null != securityIdentifier)
                {
                    array = new byte[securityIdentifier.BinaryLength];
                    securityIdentifier.GetBinaryForm(array, 0);
                }
            }
            if ((includeSections & AccessControlSections.Group) != AccessControlSections.None)
            {
                securityInfos |= SecurityInfos.Group;
                SecurityIdentifier securityIdentifier2 = (SecurityIdentifier)base.GetGroup(typeof(SecurityIdentifier));
                if (null != securityIdentifier2)
                {
                    array2 = new byte[securityIdentifier2.BinaryLength];
                    securityIdentifier2.GetBinaryForm(array2, 0);
                }
            }
            if ((includeSections & AccessControlSections.Access) != AccessControlSections.None)
            {
                securityInfos |= SecurityInfos.DiscretionaryAcl;
                if (base.AreAccessRulesProtected)
                {
                    securityInfos |= (SecurityInfos)(-2147483648);
                }
                else
                {
                    securityInfos |= (SecurityInfos)536870912;
                }
                array3 = new byte[this.descriptor.DiscretionaryAcl.BinaryLength];
                this.descriptor.DiscretionaryAcl.GetBinaryForm(array3, 0);
            }
            if ((includeSections & AccessControlSections.Audit) != AccessControlSections.None && this.descriptor.SystemAcl != null)
            {
                securityInfos |= SecurityInfos.SystemAcl;
                if (base.AreAuditRulesProtected)
                {
                    securityInfos |= (SecurityInfos)1073741824;
                }
                else
                {
                    securityInfos |= (SecurityInfos)268435456;
                }
                array4 = new byte[this.descriptor.SystemAcl.BinaryLength];
                this.descriptor.SystemAcl.GetBinaryForm(array4, 0);
            }
            return nativeCall(securityInfos, array, array2, array3, array4);
        }
References System.array, System.Security.AccessControl.CommonAcl.BinaryLength, System.Security.Principal.SecurityIdentifier.BinaryLength, System.Security.AccessControl.ObjectSecurity< T >.descriptor, System.Security.AccessControl.CommonSecurityDescriptor.DiscretionaryAcl, System.Security.AccessControl.CommonAcl.GetBinaryForm(), System.Security.Principal.SecurityIdentifier.GetBinaryForm(), and System.Security.AccessControl.CommonSecurityDescriptor.SystemAcl.
Referenced by System.Security.AccessControl.NativeObjectSecurity.InternalSet(), and System.Security.AccessControl.NativeObjectSecurity.InternalSet().