Terraria Decompiled: System.Security.AccessControl.NativeObjectSecurity.Win32GetHelper
Win32GetHelper()
int System.Security.AccessControl.NativeObjectSecurity.Win32GetHelper (NativeObjectSecurity::GetSecurityInfoNativeCall nativeCall, AccessControlSections includeSections) inline private
Definition at line 239 of file NativeObjectSecurity.cs.
        {
            bool flag = (includeSections & AccessControlSections.Owner) > AccessControlSections.None;
            bool flag2 = (includeSections & AccessControlSections.Group) > AccessControlSections.None;
            bool flag3 = (includeSections & AccessControlSections.Access) > AccessControlSections.None;
            bool flag4 = (includeSections & AccessControlSections.Audit) > AccessControlSections.None;
            SecurityInfos securityInfos = (SecurityInfos)0;
            if (flag)
            {
                securityInfos |= SecurityInfos.Owner;
            }
            if (flag2)
            {
                securityInfos |= SecurityInfos.Group;
            }
            if (flag3)
            {
                securityInfos |= SecurityInfos.DiscretionaryAcl;
            }
            if (flag4)
            {
                securityInfos |= SecurityInfos.SystemAcl;
            }
            IntPtr intPtr;
            IntPtr intPtr2;
            IntPtr intPtr3;
            IntPtr intPtr4;
            IntPtr intPtr5;
            int num = nativeCall(securityInfos, out intPtr, out intPtr2, out intPtr3, out intPtr4, out intPtr5);
            if (num != 0)
            {
                return num;
            }
            try
            {
                int num2 = 0;
                if (NativeObjectSecurity.IsValidSecurityDescriptor(intPtr5))
                {
                    num2 = NativeObjectSecurity.GetSecurityDescriptorLength(intPtr5);
                }
                byte[] array = new byte[num2];
                Marshal.Copy(intPtr5, array, 0, num2);
                base.SetSecurityDescriptorBinaryForm(array, includeSections);
            }
            finally
            {
                NativeObjectSecurity.LocalFree(intPtr5);
            }
            return 0;
        }
References System.array, System.Runtime.InteropServices.Marshal.Copy(), System.Security.AccessControl.NativeObjectSecurity.GetSecurityDescriptorLength(), System.Security.AccessControl.NativeObjectSecurity.IsValidSecurityDescriptor(), and System.Security.AccessControl.NativeObjectSecurity.LocalFree().
Referenced by System.Security.AccessControl.NativeObjectSecurity.InternalGet(), and System.Security.AccessControl.NativeObjectSecurity.InternalGet().