Terraria Decompiled: System.Reflection.RuntimeConstructorInfo.DoInvoke
DoInvoke()
object System.Reflection.RuntimeConstructorInfo.DoInvoke (object obj, BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture) inline private
Definition at line 127 of file RuntimeConstructorInfo.cs.
        {
            if (binder == null)
            {
                binder = Type.DefaultBinder;
            }
            ParameterInfo[] parametersInfo = MonoMethodInfo.GetParametersInfo(this.mhandle, this);
            RuntimeMethodInfo.ConvertValues(binder, parameters, parametersInfo, culture, invokeAttr);
            if (obj == null && this.DeclaringType.ContainsGenericParameters)
            {
                string text = "Cannot create an instance of ";
                Type declaringType = this.DeclaringType;
                throw new MemberAccessException(text + ((declaringType != null) ? declaringType.ToString() : null) + " because Type.ContainsGenericParameters is true.");
            }
            if ((invokeAttr & BindingFlags.CreateInstance) != BindingFlags.Default && this.DeclaringType.IsAbstract)
            {
                throw new MemberAccessException(string.Format("Cannot create an instance of {0} because it is an abstract class", this.DeclaringType));
            }
            return this.InternalInvoke(obj, parameters, (invokeAttr & BindingFlags.DoNotWrapExceptions) == BindingFlags.Default);
        }
References System.Type.ContainsGenericParameters, System.Reflection.RuntimeMethodInfo.ConvertValues(), System.culture, System.Reflection.RuntimeConstructorInfo.DeclaringType, System.Type.DefaultBinder, System.Format, System.Reflection.MonoMethodInfo.GetParametersInfo(), System.Reflection.RuntimeConstructorInfo.InternalInvoke(), System.Reflection.RuntimeConstructorInfo.mhandle, System.obj, System.text, and System.Type.ToString().
Referenced by System.Reflection.RuntimeConstructorInfo.Invoke(), and System.Reflection.RuntimeConstructorInfo.Invoke().