Terraria Decompiled: Microsoft.Xna.Framework.Content.LzxDecoder.Decompress
Decompress()
int Microsoft.Xna.Framework.Content.LzxDecoder.Decompress (Stream inData, int inLen, Stream outData, int outLen) inline
Definition at line 96 of file LzxDecoder.cs.
        {
            LzxDecoder.BitBuffer bitBuffer = new LzxDecoder.BitBuffer(inData);
            long position = inData.Position;
            long num = inData.Position + (long)inLen;
            byte[] window = this.m_state.window;
            uint num2 = this.m_state.window_posn;
            uint window_size = this.m_state.window_size;
            uint num3 = this.m_state.R0;
            uint num4 = this.m_state.R1;
            uint num5 = this.m_state.R2;
            int i = outLen;
            bitBuffer.InitBitStream();
            if (this.m_state.header_read == 0)
            {
                if (bitBuffer.ReadBits(1) != 0U)
                {
                    uint num6 = bitBuffer.ReadBits(16);
                    uint num7 = bitBuffer.ReadBits(16);
                    this.m_state.intel_filesize = (int)((num6 << 16) | num7);
                }
                this.m_state.header_read = 1;
            }
            while (i > 0)
            {
                if (this.m_state.block_remaining == 0U)
                {
                    if (this.m_state.block_type == LzxConstants.BLOCKTYPE.UNCOMPRESSED)
                    {
                        if ((this.m_state.block_length & 1U) == 1U)
{
                            inData.ReadByte();
                        }
                        bitBuffer.InitBitStream();
                    }
                    this.m_state.block_type = (LzxConstants.BLOCKTYPE)bitBuffer.ReadBits(3);
                    uint num6 = bitBuffer.ReadBits(16);
                    uint num7 = bitBuffer.ReadBits(8);
                    this.m_state.block_remaining = (this.m_state.block_length = (num6 << 8) | num7);
                    switch (this.m_state.block_type)
                    {
                    case LzxConstants.BLOCKTYPE.VERBATIM:
                        break;
                    case LzxConstants.BLOCKTYPE.ALIGNED:
                        for (num6 = 0U; num6 < 8U; num6 += 1U)
{
                            num7 = bitBuffer.ReadBits(3);
                            this.m_state.ALIGNED_len[(int)num6] = (byte)num7;
                        }
                        this.MakeDecodeTable(8U, 7U, this.m_state.ALIGNED_len, this.m_state.ALIGNED_table);
                        break;
                    case LzxConstants.BLOCKTYPE.UNCOMPRESSED:
                    {
                        this.m_state.intel_started = 1;
                        bitBuffer.EnsureBits(16);
                        if (bitBuffer.GetBitsLeft() > 16)
{
                            inData.Seek(-2L, SeekOrigin.Current);
                        }
                        uint num8 = (uint)((byte)inData.ReadByte());
                        byte b = (byte)inData.ReadByte();
                        byte b2 = (byte)inData.ReadByte();
                        byte b3 = (byte)inData.ReadByte();
                        num3 = num8 | (uint)((uint)b << 8) | (uint)((uint)b2 << 16) | (uint)((uint)b3 << 24);
                        uint num9 = (uint)((byte)inData.ReadByte());
                        b = (byte)inData.ReadByte();
                        b2 = (byte)inData.ReadByte();
                        b3 = (byte)inData.ReadByte();
                        num4 = num9 | (uint)((uint)b << 8) | (uint)((uint)b2 << 16) | (uint)((uint)b3 << 24);
                        uint num10 = (uint)((byte)inData.ReadByte());
                        b = (byte)inData.ReadByte();
                        b2 = (byte)inData.ReadByte();
                        b3 = (byte)inData.ReadByte();
                        num5 = num10 | (uint)((uint)b << 8) | (uint)((uint)b2 << 16) | (uint)((uint)b3 << 24);
                        goto IL_033F;
                    }
                    default:
                        return -1;
                    }
                    this.ReadLengths(this.m_state.MAINTREE_len, 0U, 256U, bitBuffer);
                    this.ReadLengths(this.m_state.MAINTREE_len, 256U, (uint)this.m_state.main_elements, bitBuffer);
                    this.MakeDecodeTable(656U, 12U, this.m_state.MAINTREE_len, this.m_state.MAINTREE_table);
                    if (this.m_state.MAINTREE_len[232] != 0)
                    {
                        this.m_state.intel_started = 1;
                    }
                    this.ReadLengths(this.m_state.LENGTH_len, 0U, 249U, bitBuffer);
                    this.MakeDecodeTable(250U, 12U, this.m_state.LENGTH_len, this.m_state.LENGTH_table);
                }
                IL_033F:
                if (inData.Position > position + (long)inLen && (inData.Position > position + (long)inLen + 2L || bitBuffer.GetBitsLeft() < 16))
                {
                    return -1;
                }
                int j;
                while ((j = (int)this.m_state.block_remaining) > 0 && i > 0)
                {
                    if (j > i)
                    {
                        j = i;
                    }
                    i -= j;
                    this.m_state.block_remaining = this.m_state.block_remaining - (uint)j;
                    num2 &= window_size - 1U;
                    if ((ulong)num2 + (ulong)((long)j) > (ulong)window_size)
                    {
                        return -1;
                    }
                    switch (this.m_state.block_type)
                    {
                    case LzxConstants.BLOCKTYPE.VERBATIM:
                        while (j > 0)
{
                            int num11 = (int)this.ReadHuffSym(this.m_state.MAINTREE_table, this.m_state.MAINTREE_len, 656U, 12U, bitBuffer);
                            if (num11 < 256)
{
                                window[(int)num2++] = (byte)num11;
                                j--;
                            }
                            else
{
                                num11 -= 256;
                                int num12 = num11 & 7;
                                if (num12 == 7)
{
                                    int num13 = (int)this.ReadHuffSym(this.m_state.LENGTH_table, this.m_state.LENGTH_len, 250U, 12U, bitBuffer);
                                    num12 += num13;
                                }
                                num12 += 2;
                                int num14 = num11 >> 3;
                                if (num14 > 2)
{
                                    if (num14 != 3)
{
                                        int num15 = (int)LzxDecoder.extra_bits[num14];
                                        int num16 = (int)bitBuffer.ReadBits((byte)num15);
                                        num14 = (int)(LzxDecoder.position_base[num14] - 2U + (uint)num16);
                                    }
                                    else
{
                                        num14 = 1;
                                    }
                                    num5 = num4;
                                    num4 = num3;
                                    num3 = (uint)num14;
                                }
                                else if (num14 == 0)
{
                                    num14 = (int)num3;
                                }
                                else if (num14 == 1)
{
                                    num14 = (int)num4;
                                    num4 = num3;
                                    num3 = (uint)num14;
                                }
                                else
{
                                    num14 = (int)num5;
                                    num5 = num3;
                                    num3 = (uint)num14;
                                }
                                int num17 = (int)num2;
                                j -= num12;
                                int num18;
                                if ((ulong)num2 >= (ulong)((long)num14))
{
                                    num18 = num17 - num14;
                                }
                                else
{
                                    num18 = num17 + (int)(window_size - (uint)num14);
                                    int num19 = num14 - (int)num2;
                                    if (num19 < num12)
{
                                        num12 -= num19;
                                        num2 += (uint)num19;
                                        while (num19-- > 0)
{
                                            window[num17++] = window[num18++];
                                        }
                                        num18 = 0;
                                    }
                                }
                                num2 += (uint)num12;
                                while (num12-- > 0)
{
                                    window[num17++] = window[num18++];
                                }
                            }
                        }
                        break;
                    case LzxConstants.BLOCKTYPE.ALIGNED:
                        while (j > 0)
{
                            int num11 = (int)this.ReadHuffSym(this.m_state.MAINTREE_table, this.m_state.MAINTREE_len, 656U, 12U, bitBuffer);
                            if (num11 < 256)
{
                                window[(int)num2++] = (byte)num11;
                                j--;
                            }
                            else
{
                                num11 -= 256;
                                int num12 = num11 & 7;
                                if (num12 == 7)
{
                                    int num13 = (int)this.ReadHuffSym(this.m_state.LENGTH_table, this.m_state.LENGTH_len, 250U, 12U, bitBuffer);
                                    num12 += num13;
                                }
                                num12 += 2;
                                int num14 = num11 >> 3;
                                if (num14 > 2)
{
                                    int num15 = (int)LzxDecoder.extra_bits[num14];
                                    num14 = (int)(LzxDecoder.position_base[num14] - 2U);
                                    if (num15 > 3)
{
                                        num15 -= 3;
                                        int num16 = (int)bitBuffer.ReadBits((byte)num15);
                                        num14 += num16 << 3;
                                        int num20 = (int)this.ReadHuffSym(this.m_state.ALIGNED_table, this.m_state.ALIGNED_len, 8U, 7U, bitBuffer);
                                        num14 += num20;
                                    }
                                    else if (num15 == 3)
{
                                        int num20 = (int)this.ReadHuffSym(this.m_state.ALIGNED_table, this.m_state.ALIGNED_len, 8U, 7U, bitBuffer);
                                        num14 += num20;
                                    }
                                    else if (num15 > 0)
{
                                        int num16 = (int)bitBuffer.ReadBits((byte)num15);
                                        num14 += num16;
                                    }
                                    else
{
                                        num14 = 1;
                                    }
                                    num5 = num4;
                                    num4 = num3;
                                    num3 = (uint)num14;
                                }
                                else if (num14 == 0)
{
                                    num14 = (int)num3;
                                }
                                else if (num14 == 1)
{
                                    num14 = (int)num4;
                                    num4 = num3;
                                    num3 = (uint)num14;
                                }
                                else
{
                                    num14 = (int)num5;
                                    num5 = num3;
                                    num3 = (uint)num14;
                                }
                                int num17 = (int)num2;
                                j -= num12;
                                int num18;
                                if ((ulong)num2 >= (ulong)((long)num14))
{
                                    num18 = num17 - num14;
                                }
                                else
{
                                    num18 = num17 + (int)(window_size - (uint)num14);
                                    int num19 = num14 - (int)num2;
                                    if (num19 < num12)
{
                                        num12 -= num19;
                                        num2 += (uint)num19;
                                        while (num19-- > 0)
{
                                            window[num17++] = window[num18++];
                                        }
                                        num18 = 0;
                                    }
                                }
                                num2 += (uint)num12;
                                while (num12-- > 0)
{
                                    window[num17++] = window[num18++];
                                }
                            }
                        }
                        break;
                    case LzxConstants.BLOCKTYPE.UNCOMPRESSED:
                    {
                        if (inData.Position + (long)j > num)
{
                            return -1;
                        }
                        byte[] array = new byte[j];
                        inData.Read(array, 0, j);
                        array.CopyTo(window, (int)num2);
                        num2 += (uint)j;
                        break;
                    }
                    default:
                        return -1;
                    }
                }
            }
            if (i != 0)
            {
                return -1;
            }
            int num21 = (int)num2;
            if (num21 == 0)
            {
                num21 = (int)window_size;
            }
            num21 -= outLen;
            outData.Write(window, num21, outLen);
            this.m_state.window_posn = num2;
            this.m_state.R0 = num3;
            this.m_state.R1 = num4;
            this.m_state.R2 = num5;
            uint frames_read = this.m_state.frames_read;
            this.m_state.frames_read = frames_read + 1U;
            if (frames_read < 32768U && this.m_state.intel_filesize != 0)
            {
                if (outLen <= 6 || this.m_state.intel_started == 0)
                {
                    this.m_state.intel_curpos = this.m_state.intel_curpos + outLen;
                }
                else
                {
                    int num22 = outLen - 10;
                    uint num23 = (uint)this.m_state.intel_curpos;
                    this.m_state.intel_curpos = (int)(num23 + (uint)outLen);
                    while (outData.Position < (long)num22)
                    {
                        if (outData.ReadByte() != 232)
{
                            num23 += 1U;
                        }
                    }
                }
                return -1;
            }
            return 0;
        }
References System.array, Microsoft.Xna.Framework.Content.LzxDecoder.BitBuffer.EnsureBits(), Microsoft.Xna.Framework.Content.LzxDecoder.extra_bits, Microsoft.Xna.Framework.Content.LzxDecoder.BitBuffer.GetBitsLeft(), Microsoft.Xna.Framework.Content.LzxDecoder.BitBuffer.InitBitStream(), int, System.L, long, Microsoft.Xna.Framework.Content.LzxDecoder.m_state, Microsoft.Xna.Framework.Content.LzxDecoder.MakeDecodeTable(), System.IO.Stream.Position, Microsoft.Xna.Framework.Content.LzxDecoder.position_base, System.IO.Stream.Read(), Microsoft.Xna.Framework.Content.LzxDecoder.BitBuffer.ReadBits(), System.IO.Stream.ReadByte(), Microsoft.Xna.Framework.Content.LzxDecoder.ReadHuffSym(), Microsoft.Xna.Framework.Content.LzxDecoder.ReadLengths(), System.IO.Stream.Seek(), System.U, and System.IO.Stream.Write().
Referenced by Microsoft.Xna.Framework.Content.ContentManager.GetContentReaderFromXnb().