Terraria Decompiled: Microsoft.Xna.Framework.Content.LzxDecoder.ReadLengths
ReadLengths()
void Microsoft.Xna.Framework.Content.LzxDecoder.ReadLengths (byte[] lens, uint first, uint last, LzxDecoder::BitBuffer bitbuf) inline private
Definition at line 536 of file LzxDecoder.cs.
        {
            uint num;
            for (num = 0U; num < 20U; num += 1U)
            {
                uint num2 = bitbuf.ReadBits(4);
                this.m_state.PRETREE_len[(int)num] = (byte)num2;
            }
            this.MakeDecodeTable(20U, 6U, this.m_state.PRETREE_len, this.m_state.PRETREE_table);
            num = first;
            while (num < last)
            {
                int num3 = (int)this.ReadHuffSym(this.m_state.PRETREE_table, this.m_state.PRETREE_len, 20U, 6U, bitbuf);
                if (num3 == 17)
                {
                    uint num2 = bitbuf.ReadBits(4);
                    num2 += 4U;
                    while (num2-- != 0U)
                    {
                        lens[(int)num++] = 0;
                    }
                }
                else if (num3 == 18)
                {
                    uint num2 = bitbuf.ReadBits(5);
                    num2 += 20U;
                    while (num2-- != 0U)
                    {
                        lens[(int)num++] = 0;
                    }
                }
                else if (num3 == 19)
                {
                    uint num2 = bitbuf.ReadBits(1);
                    num2 += 4U;
                    num3 = (int)this.ReadHuffSym(this.m_state.PRETREE_table, this.m_state.PRETREE_len, 20U, 6U, bitbuf);
                    num3 = (int)lens[(int)num] - num3;
                    if (num3 < 0)
                    {
                        num3 += 17;
                    }
                    while (num2-- != 0U)
                    {
                        lens[(int)num++] = (byte)num3;
                    }
                }
                else
                {
                    num3 = (int)lens[(int)num] - num3;
                    if (num3 < 0)
                    {
                        num3 += 17;
                    }
                    lens[(int)num++] = (byte)num3;
                }
            }
        }
References int, Microsoft.Xna.Framework.Content.LzxDecoder.m_state, Microsoft.Xna.Framework.Content.LzxDecoder.MakeDecodeTable(), Microsoft.Xna.Framework.Content.LzxDecoder.ReadHuffSym(), and System.U.
Referenced by Microsoft.Xna.Framework.Content.LzxDecoder.Decompress().