Terraria Decompiled: System.Security.Policy.HashMembershipCondition.FromXml
FromXml() [2/2]
void System.Security.Policy.HashMembershipCondition.FromXml (SecurityElement e, PolicyLevel level) inline
Implements System.Security.ISecurityPolicyEncodable.
Definition at line 140 of file HashMembershipCondition.cs.
        {
            MembershipConditionHelper.CheckSecurityElement(e, "e", this.version, this.version);
            this.hash_value = CryptoConvert.FromHex(e.Attribute("HashValue"));
            string text = e.Attribute("HashAlgorithm");
            this.hash_algorithm = ((text == null) ? null : HashAlgorithm.Create(text));
        }
References System.Security.SecurityElement.Attribute(), System.Security.Policy.MembershipConditionHelper.CheckSecurityElement(), System.Security.Cryptography.HashAlgorithm.Create(), Mono.Security.Cryptography.CryptoConvert.FromHex(), System.text, and System.Security.Policy.HashMembershipCondition.version.