Terraria Decompiled: Terraria.GameContent.NPCInteractions.Actions.RequestHome.Interact
Interact()
override void Terraria.GameContent.NPCInteractions.Actions.RequestHome.Interact () inline
Definition at line 525 of file NPCInteractions.cs.
                {
                    Main.npcChatCornerItem = -1;
                    SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                    Main.DoNPCPortraitHop();
                    NPC talkNPC = base.TalkNPC;
                    string text = "TownNPCMood_" + NPCID.Search.GetName(talkNPC.netID);
                    if (talkNPC.type == 633 && talkNPC.altTexture == 2)
                    {
                        text += "Transformed";
                    }
                    if (talkNPC.type == 638)
                    {
                        text = "DogChatter";
                    }
                    else if (talkNPC.type == 637)
                    {
                        text = "CatChatter";
                    }
                    else if (talkNPC.type == 656)
                    {
                        text = "BunnyChatter";
                    }
                    else if (NPCID.Sets.IsTownSlime[talkNPC.type])
                    {
                        string slimeType = Lang.GetSlimeType(talkNPC);
                        text = "Slime" + slimeType + "Chatter";
                    }
                    Main.npcChatText = Language.GetTextValue(text + ".NoHome");
                    Main.npcChatText += "\n\n";
                    if (talkNPC.type == 160)
                    {
                        Main.npcChatText += Language.GetTextValueWith("HousingText.HousingRequirements_Truffle", new
{
                            NPCName = talkNPC.FullName
                        });
                        return;
                    }
                    Main.npcChatText += Language.GetTextValue("HousingText.HousingRequirements");
                }
References Terraria.NPC.altTexture, Terraria.Main.DoNPCPortraitHop(), Terraria.Lang.GetSlimeType(), Terraria.Localization.Language.GetTextValue(), Terraria.Localization.Language.GetTextValueWith(), Terraria.ID.NPCID.Sets.IsTownSlime, Terraria.NPC.netID, Terraria.Audio.SoundEngine.PlaySound(), Terraria.ID.NPCID.Search, System.text, and Terraria.NPC.type.