Terraria Decompiled: Microsoft.Xna.Framework.Graphics.PackedVector.Byte4.Pack
Pack()
static uint Microsoft.Xna.Framework.Graphics.PackedVector.Byte4.Pack (float x, float y, float z, float w) inline static private
Definition at line 85 of file Byte4.cs.
        {
            return (uint)Math.Round((double)MathHelper.Clamp(x, 0f, 255f)) | ((uint)Math.Round((double)MathHelper.Clamp(y, 0f, 255f)) << 8) | ((uint)Math.Round((double)MathHelper.Clamp(z, 0f, 255f)) << 16) | ((uint)Math.Round((double)MathHelper.Clamp(w, 0f, 255f)) << 24);
        }
References Microsoft.Xna.Framework.MathHelper.Clamp(), and System.Math.Round().
Referenced by Microsoft.Xna.Framework.Graphics.PackedVector.Byte4.Byte4(), Microsoft.Xna.Framework.Graphics.PackedVector.Byte4.Byte4(), and Microsoft.Xna.Framework.Graphics.PackedVector.Byte4.PackFromVector4().