Terraria Decompiled: Terraria.Testing.DebugUtils.PracticeModeReset
PracticeModeReset()
static bool Terraria.Testing.DebugUtils.PracticeModeReset (Player player, PlayerDeathReason damageSource) inline static package
Definition at line 99 of file DebugUtils.cs.
        {
            if (!DebugOptions.PracticeMode)
            {
                return false;
            }
            if (!NPC.AnyDanger(false, true))
            {
                return false;
            }
            player.statLife = player.statLifeMax2;
            for (int i = 0; i < Player.maxBuffs; i++)
            {
                if (player.buffTime[i] > 0)
                {
                    int num = player.buffType[i];
                    if (Main.debuff[num] && (num == 21 || !BuffID.Sets.NurseCannotRemoveDebuff[num]))
                    {
                        player.DelBuff(i);
                        i = -1;
                    }
                }
            }
            for (int j = 0; j < BuffID.Count; j++)
            {
                if (Main.debuff[j])
                {
                    player.buffImmune[j] = true;
                }
            }
            string text = "unknown source";
            Entity entity;
            damageSource.TryGetCausingEntity(out entity);
            if (entity is NPC)
            {
                text = ((NPC)entity).TypeName;
            }
            else if (entity is Projectile)
            {
                text = ((Projectile)entity).Name;
            }
            else if (entity is Player)
            {
                text = ((Player)entity).name;
            }
            Main.NewText("Lethal damage dealt by " + text, byte.MaxValue, byte.MaxValue, 0);
            if (Main.netMode != 0)
            {
                return true;
            }
            for (int k = 0; k < 1000; k++)
            {
                Projectile projectile = Main.projectile[k];
                if (projectile.active && projectile.hostile)
                {
                    projectile.active = false;
                }
            }
            for (int l = 0; l < Main.maxNPCs; l++)
            {
                NPC npc = Main.npc[l];
                if (npc.active && !npc.friendly && !npc.isLikeATownNPC)
                {
                    npc.active = false;
                }
            }
            return true;
        }
References Terraria.NPC.active, Terraria.Projectile.active, Terraria.NPC.AnyDanger(), Terraria.Player.buffImmune, Terraria.Player.buffTime, Terraria.Player.buffType, Terraria.ID.BuffID.Count, Terraria.Main.debuff, Terraria.Player.DelBuff(), Terraria.NPC.friendly, Terraria.Projectile.hostile, Terraria.NPC.isLikeATownNPC, Terraria.Player.maxBuffs, Terraria.Main.maxNPCs, Terraria.Main.netMode, Terraria.Main.NewText(), Terraria.Main.npc, Terraria.ID.BuffID.Sets.NurseCannotRemoveDebuff, Terraria.Testing.DebugOptions.PracticeMode, Terraria.Main.projectile, Terraria.Player.statLifeMax2, System.text, and Terraria.DataStructures.PlayerDeathReason.TryGetCausingEntity().
Referenced by Terraria.Player.KillMe().