Terraria Decompiled: Terraria.Testing.DebugUtils.GetTileDescription
GetTileDescription()
static string Terraria.Testing.DebugUtils.GetTileDescription (int x, int y) inline static package
Definition at line 14 of file DebugUtils.cs.
        {
            Tile tile = Main.tile[x, y];
            if (tile == null)
            {
                return "";
            }
            Point point = (Main.LocalPlayer.Bottom + new Vector2(-8f, 8f)).ToTileCoordinates();
            string text;
            if (!TileID.Search.TryGetName((int)tile.type, ref text))
            {
                text = "Unknown";
            }
            string text2;
            if (!WallID.Search.TryGetName((int)tile.wall, ref text2))
            {
                text2 = "Unknown";
            }
            string text3 = "   ";
            return string.Concat(new object[]
            {
                text3,
                "Pos: ",
                x,
                ", ",
                y,
                "\n",
                text3,
                "Type: ",
                tile.type,
                (tile.blockType() == 0) ? "" : (" " + DebugUtils._slopeIcons[tile.blockType() - 1].ToString()),
                " (",
                text,
                ")\n",
                text3,
                "Frame: ",
                tile.frameX,
                ", ",
                tile.frameY,
                "\n",
                text3,
                "FrameImportant: ",
                Main.tileFrameImportant[(int)tile.type].ToString(),
                "\n",
                text3,
                "Liquid: ",
                tile.liquid,
                " (",
                tile.liquidType(),
                ")\n",
                text3,
                "Wall: ",
                tile.wall,
                " (",
                text2,
                ")\n",
                text3,
                "Compare Spot: ",
                point.X,
                ", ",
                point.Y,
                "\n",
                text3,
                "Chunk: ",
                x / 200,
                ", ",
                y / 150,
                "\n",
                text3,
                "Paints: ",
                tile.color(),
                tile.fullbrightBlock() ? " fullbright" : "",
                tile.invisibleBlock() ? " echo" : "",
                ", ",
                tile.wallColor(),
                tile.fullbrightWall() ? " fullbright" : "",
                tile.invisibleWall() ? " echo" : "",
                "\n",
                text3,
                "Light: ",
                Lighting.GetColor(x, y)
            });
        }
References Terraria.Testing.DebugUtils._slopeIcons, Terraria.Tile.blockType(), Terraria.Tile.color(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Tile.fullbrightBlock(), Terraria.Tile.fullbrightWall(), Terraria.Lighting.GetColor(), Terraria.Tile.invisibleBlock(), Terraria.Tile.invisibleWall(), Terraria.Tile.liquid, Terraria.Tile.liquidType(), Terraria.ID.TileID.Search, Terraria.ID.WallID.Search, System.text, Terraria.Main.tile, Terraria.Main.tileFrameImportant, Terraria.Tile.type, Terraria.Tile.wall, Terraria.Tile.wallColor(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.Main.DrawMap().