Terraria Decompiled: Mono.Security.Cryptography.SymmetricTransform.FinalEncrypt
FinalEncrypt()
virtual byte[] Mono.Security.Cryptography.SymmetricTransform.FinalEncrypt (byte[] inputBuffer, int inputOffset, int inputCount) inline protected virtual
Definition at line 340 of file SymmetricTransform.cs.
        {
            int num = inputCount / this.BlockSizeByte * this.BlockSizeByte;
            int num2 = inputCount - num;
            int i = num;
            PaddingMode paddingMode = this.padmode;
            if (paddingMode == PaddingMode.PKCS7 || paddingMode - PaddingMode.ANSIX923 <= 1)
            {
                i += this.BlockSizeByte;
            }
            else
            {
                if (inputCount == 0)
                {
                    return new byte[0];
                }
                if (num2 != 0)
                {
                    if (this.padmode == PaddingMode.None)
                    {
                        throw new CryptographicException("invalid block length");
                    }
                    byte[] array = new byte[num + this.BlockSizeByte];
                    Buffer.BlockCopy(inputBuffer, inputOffset, array, 0, inputCount);
                    inputBuffer = array;
                    inputOffset = 0;
                    inputCount = array.Length;
                    i = inputCount;
                }
            }
            byte[] array2 = new byte[i];
            int num3 = 0;
            while (i > this.BlockSizeByte)
            {
                this.InternalTransformBlock(inputBuffer, inputOffset, this.BlockSizeByte, array2, num3);
                inputOffset += this.BlockSizeByte;
                num3 += this.BlockSizeByte;
                i -= this.BlockSizeByte;
            }
            byte b = (byte)(this.BlockSizeByte - num2);
            switch (this.padmode)
            {
            case PaddingMode.PKCS7:
            {
                int num4 = array2.Length;
                while (--num4 >= array2.Length - (int)b)
                {
                    array2[num4] = b;
                }
                Buffer.BlockCopy(inputBuffer, inputOffset, array2, num, num2);
                this.InternalTransformBlock(array2, num, this.BlockSizeByte, array2, num);
                return array2;
            }
            case PaddingMode.ANSIX923:
                array2[array2.Length - 1] = b;
                Buffer.BlockCopy(inputBuffer, inputOffset, array2, num, num2);
                this.InternalTransformBlock(array2, num, this.BlockSizeByte, array2, num);
                return array2;
            case PaddingMode.ISO10126:
                this.Random(array2, array2.Length - (int)b, (int)(b - 1));
                array2[array2.Length - 1] = b;
                Buffer.BlockCopy(inputBuffer, inputOffset, array2, num, num2);
                this.InternalTransformBlock(array2, num, this.BlockSizeByte, array2, num);
                return array2;
            }
            this.InternalTransformBlock(inputBuffer, inputOffset, this.BlockSizeByte, array2, num3);
            return array2;
        }
References System.array, System.Buffer.BlockCopy(), Mono.Security.Cryptography.SymmetricTransform.BlockSizeByte, Mono.Security.Cryptography.SymmetricTransform.InternalTransformBlock(), Mono.Security.Cryptography.SymmetricTransform.padmode, and Mono.Security.Cryptography.SymmetricTransform.Random().
Referenced by Mono.Security.Cryptography.SymmetricTransform.TransformFinalBlock().