Terraria Decompiled: Mono.Security.Cryptography.SymmetricTransform.TransformFinalBlock
TransformFinalBlock()
virtual byte[] Mono.Security.Cryptography.SymmetricTransform.TransformFinalBlock (byte[] inputBuffer, int inputOffset, int inputCount) inline virtual
Implements System.Security.Cryptography.ICryptoTransform.
Definition at line 488 of file SymmetricTransform.cs.
        {
            if (this.m_disposed)
            {
                throw new ObjectDisposedException("Object is disposed");
            }
            this.CheckInput(inputBuffer, inputOffset, inputCount);
            if (this.encrypt)
            {
                return this.FinalEncrypt(inputBuffer, inputOffset, inputCount);
            }
            return this.FinalDecrypt(inputBuffer, inputOffset, inputCount);
        }
References Mono.Security.Cryptography.SymmetricTransform.CheckInput(), Mono.Security.Cryptography.SymmetricTransform.encrypt, Mono.Security.Cryptography.SymmetricTransform.FinalDecrypt(), Mono.Security.Cryptography.SymmetricTransform.FinalEncrypt(), and Mono.Security.Cryptography.SymmetricTransform.m_disposed.