Terraria Decompiled: Mono.Security.Cryptography.SymmetricTransform.CheckInput
CheckInput()
void Mono.Security.Cryptography.SymmetricTransform.CheckInput (byte[] inputBuffer, int inputOffset, int inputCount) inline private
Definition at line 196 of file SymmetricTransform.cs.
        {
            if (inputBuffer == null)
            {
                throw new ArgumentNullException("inputBuffer");
            }
            if (inputOffset < 0)
            {
                throw new ArgumentOutOfRangeException("inputOffset", "< 0");
            }
            if (inputCount < 0)
            {
                throw new ArgumentOutOfRangeException("inputCount", "< 0");
            }
            if (inputOffset > inputBuffer.Length - inputCount)
            {
                throw new ArgumentException("inputBuffer", Locale.GetText("Overflow"));
            }
        }
References Locale.GetText().
Referenced by Mono.Security.Cryptography.SymmetricTransform.TransformBlock(), and Mono.Security.Cryptography.SymmetricTransform.TransformFinalBlock().