Terraria Decompiled: Mono.Security.Cryptography.SymmetricTransform.FinalDecrypt
FinalDecrypt()
virtual byte[] Mono.Security.Cryptography.SymmetricTransform.FinalDecrypt (byte[] inputBuffer, int inputOffset, int inputCount) inline protected virtual
Definition at line 410 of file SymmetricTransform.cs.
        {
            int i = inputCount;
            int num = inputCount;
            if (this.lastBlock)
            {
                num += this.BlockSizeByte;
            }
            byte[] array = new byte[num];
            int num2 = 0;
            while (i > 0)
            {
                int num3 = this.InternalTransformBlock(inputBuffer, inputOffset, this.BlockSizeByte, array, num2);
                inputOffset += this.BlockSizeByte;
                num2 += num3;
                i -= this.BlockSizeByte;
            }
            if (this.lastBlock)
            {
                this.Transform(this.workBuff, this.workout);
                Buffer.BlockCopy(this.workout, 0, array, num2, this.BlockSizeByte);
                num2 += this.BlockSizeByte;
                this.lastBlock = false;
            }
            byte b = ((num > 0) ? array[num - 1] : 0);
            switch (this.padmode)
            {
            case PaddingMode.PKCS7:
            {
                if (b == 0 || (int)b > this.BlockSizeByte)
                {
                    this.ThrowBadPaddingException(this.padmode, (int)b, -1);
                }
                for (int j = (int)(b - 1); j > 0; j--)
                {
                    if (array[num - 1 - j] != b)
                    {
                        this.ThrowBadPaddingException(this.padmode, -1, j);
                    }
                }
                num -= (int)b;
                break;
            }
            case PaddingMode.ANSIX923:
            {
                if (b == 0 || (int)b > this.BlockSizeByte)
                {
                    this.ThrowBadPaddingException(this.padmode, (int)b, -1);
                }
                for (int k = (int)(b - 1); k > 0; k--)
                {
                    if (array[num - 1 - k] != 0)
                    {
                        this.ThrowBadPaddingException(this.padmode, -1, k);
                    }
                }
                num -= (int)b;
                break;
            }
            case PaddingMode.ISO10126:
                if (b == 0 || (int)b > this.BlockSizeByte)
                {
                    this.ThrowBadPaddingException(this.padmode, (int)b, -1);
                }
                num -= (int)b;
                break;
            }
            if (num > 0)
            {
                byte[] array2 = new byte[num];
                Buffer.BlockCopy(array, 0, array2, 0, num);
                Array.Clear(array, 0, array.Length);
                return array2;
            }
            return new byte[0];
        }
References System.array, System.Buffer.BlockCopy(), Mono.Security.Cryptography.SymmetricTransform.BlockSizeByte, System.Array.Clear(), int, Mono.Security.Cryptography.SymmetricTransform.InternalTransformBlock(), Mono.Security.Cryptography.SymmetricTransform.lastBlock, Mono.Security.Cryptography.SymmetricTransform.padmode, Mono.Security.Cryptography.SymmetricTransform.ThrowBadPaddingException(), Mono.Security.Cryptography.SymmetricTransform.Transform(), Mono.Security.Cryptography.SymmetricTransform.workBuff, and Mono.Security.Cryptography.SymmetricTransform.workout.
Referenced by Mono.Security.Cryptography.SymmetricTransform.TransformFinalBlock().