Terraria Decompiled: Mono.Security.Cryptography.SymmetricTransform.InternalTransformBlock
InternalTransformBlock()
int Mono.Security.Cryptography.SymmetricTransform.InternalTransformBlock (byte[] inputBuffer, int inputOffset, int inputCount, byte[] outputBuffer, int outputOffset) inline private
Definition at line 266 of file SymmetricTransform.cs.
        {
            int num = inputOffset;
            int num2;
            if (inputCount != this.BlockSizeByte)
            {
                if (inputCount % this.BlockSizeByte != 0)
                {
                    throw new CryptographicException("Invalid input block size.");
                }
                num2 = inputCount / this.BlockSizeByte;
            }
            else
            {
                num2 = 1;
            }
            if (this.KeepLastBlock)
            {
                num2--;
            }
            int num3 = 0;
            if (this.lastBlock)
            {
                this.Transform(this.workBuff, this.workout);
                Buffer.BlockCopy(this.workout, 0, outputBuffer, outputOffset, this.BlockSizeByte);
                outputOffset += this.BlockSizeByte;
                num3 += this.BlockSizeByte;
                this.lastBlock = false;
            }
            for (int i = 0; i < num2; i++)
            {
                Buffer.BlockCopy(inputBuffer, num, this.workBuff, 0, this.BlockSizeByte);
                this.Transform(this.workBuff, this.workout);
                Buffer.BlockCopy(this.workout, 0, outputBuffer, outputOffset, this.BlockSizeByte);
                num += this.BlockSizeByte;
                outputOffset += this.BlockSizeByte;
                num3 += this.BlockSizeByte;
            }
            if (this.KeepLastBlock)
            {
                Buffer.BlockCopy(inputBuffer, num, this.workBuff, 0, this.BlockSizeByte);
                this.lastBlock = true;
            }
            return num3;
        }
References System.Buffer.BlockCopy(), Mono.Security.Cryptography.SymmetricTransform.BlockSizeByte, Mono.Security.Cryptography.SymmetricTransform.KeepLastBlock, Mono.Security.Cryptography.SymmetricTransform.lastBlock, Mono.Security.Cryptography.SymmetricTransform.Transform(), Mono.Security.Cryptography.SymmetricTransform.workBuff, and Mono.Security.Cryptography.SymmetricTransform.workout.
Referenced by Mono.Security.Cryptography.SymmetricTransform.FinalDecrypt(), Mono.Security.Cryptography.SymmetricTransform.FinalEncrypt(), and Mono.Security.Cryptography.SymmetricTransform.TransformBlock().