Terraria Decompiled: System.ModuleHandle.ResolveMethodHandle
ResolveMethodHandle() [2/2]
RuntimeMethodHandle System.ModuleHandle.ResolveMethodHandle (int methodToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext) inline
Definition at line 102 of file ModuleHandle.cs.
        {
            if (this.value == IntPtr.Zero)
            {
                throw new ArgumentNullException(string.Empty, "Invalid handle");
            }
            ResolveTokenError resolveTokenError;
            IntPtr intPtr = RuntimeModule.ResolveMethodToken(this.value, methodToken, this.ptrs_from_handles(typeInstantiationContext), this.ptrs_from_handles(methodInstantiationContext), out resolveTokenError);
            if (intPtr == IntPtr.Zero)
            {
                throw new Exception(string.Format("Could not load method '0x{0:x}' from assembly '0x{1:x}'", methodToken, this.value.ToInt64()));
            }
            return new RuntimeMethodHandle(intPtr);
        }
References System.Format, System.ModuleHandle.ptrs_from_handles(), System.Reflection.RuntimeModule.ResolveMethodToken(), System.IntPtr.ToInt64(), System.ModuleHandle.value, and System.IntPtr.Zero.