Terraria Decompiled: System.ModuleHandle.ResolveTypeHandle
ResolveTypeHandle() [2/2]
RuntimeTypeHandle System.ModuleHandle.ResolveTypeHandle (int typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext) inline
Definition at line 86 of file ModuleHandle.cs.
        {
            if (this.value == IntPtr.Zero)
            {
                throw new ArgumentNullException(string.Empty, "Invalid handle");
            }
            ResolveTokenError resolveTokenError;
            IntPtr intPtr = RuntimeModule.ResolveTypeToken(this.value, typeToken, this.ptrs_from_handles(typeInstantiationContext), this.ptrs_from_handles(methodInstantiationContext), out resolveTokenError);
            if (intPtr == IntPtr.Zero)
            {
                throw new TypeLoadException(string.Format("Could not load type '0x{0:x}' from assembly '0x{1:x}'", typeToken, this.value.ToInt64()));
            }
            return new RuntimeTypeHandle(intPtr);
        }
References System.Format, System.ModuleHandle.ptrs_from_handles(), System.Reflection.RuntimeModule.ResolveTypeToken(), System.IntPtr.ToInt64(), System.ModuleHandle.value, and System.IntPtr.Zero.