Terraria Decompiled: System.Threading.SemaphoreSlim.WaitAsync
WaitAsync() [4/6]
Task< bool > System.Threading.SemaphoreSlim.WaitAsync (int millisecondsTimeout, CancellationToken cancellationToken) inline
Definition at line 263 of file SemaphoreSlim.cs.
        {
            this.CheckDispose();
            if (millisecondsTimeout < -1)
            {
                throw new ArgumentOutOfRangeException("totalMilliSeconds", millisecondsTimeout, SemaphoreSlim.GetResourceString("The timeout must represent a value between -1 and Int32.MaxValue, inclusive."));
            }
            if (cancellationToken.IsCancellationRequested)
            {
                return Task.FromCancellation<bool>(cancellationToken);
            }
            object lockObj = this.m_lockObj;
            Task<bool> task;
            lock (lockObj)
            {
                if (this.m_currentCount > 0)
                {
                    this.m_currentCount--;
                    if (this.m_waitHandle != null && this.m_currentCount == 0)
                    {
                        this.m_waitHandle.Reset();
                    }
                    task = SemaphoreSlim.s_trueTask;
                }
                else if (millisecondsTimeout == 0)
                {
                    task = SemaphoreSlim.s_falseTask;
                }
                else
                {
                    SemaphoreSlim.TaskNode taskNode = this.CreateAndAddAsyncWaiter();
                    task = ((millisecondsTimeout == -1 && !cancellationToken.CanBeCanceled) ? taskNode : this.WaitUntilCountOrTimeoutAsync(taskNode, millisecondsTimeout, cancellationToken));
                }
            }
            return task;
        }
References System.Threading.CancellationToken.CanBeCanceled, System.Threading.SemaphoreSlim.CheckDispose(), System.Threading.SemaphoreSlim.CreateAndAddAsyncWaiter(), System.Threading.Tasks.Task< TResult >.FromCancellation(), System.Threading.SemaphoreSlim.GetResourceString(), System.Threading.CancellationToken.IsCancellationRequested, System.Threading.SemaphoreSlim.m_currentCount, System.Threading.SemaphoreSlim.m_lockObj, System.Threading.SemaphoreSlim.m_waitHandle, System.Threading.EventWaitHandle.Reset(), System.Threading.SemaphoreSlim.s_falseTask, System.Threading.SemaphoreSlim.s_trueTask, System.task, and System.Threading.SemaphoreSlim.WaitUntilCountOrTimeoutAsync().