Terraria Decompiled: System.Threading.SemaphoreSlim.WaitUntilCountOrTimeoutAsync
WaitUntilCountOrTimeoutAsync()
async Task< bool > System.Threading.SemaphoreSlim.WaitUntilCountOrTimeoutAsync (SemaphoreSlim::TaskNode asyncWaiter, int millisecondsTimeout, CancellationToken cancellationToken) inline private
Definition at line 343 of file SemaphoreSlim.cs.
        {
            using (CancellationTokenSource cts = (cancellationToken.CanBeCanceled ? CancellationTokenSource.CreateLinkedTokenSource(cancellationToken, default(CancellationToken)) : new CancellationTokenSource()))
            {
                Task<Task> task = Task.WhenAny(new Task[]
                {
                    asyncWaiter,
                    Task.Delay(millisecondsTimeout, cts.Token)
                });
                object obj = asyncWaiter;
                Task task2 = await task.ConfigureAwait(false);
                if (obj == task2)
                {
                    obj = null;
                    cts.Cancel();
                    return true;
                }
            }
            CancellationTokenSource cts = null;
            object lockObj = this.m_lockObj;
            lock (lockObj)
            {
                if (this.RemoveAsyncWaiter(asyncWaiter))
                {
                    cancellationToken.ThrowIfCancellationRequested();
                    return false;
                }
            }
            return await asyncWaiter.ConfigureAwait(false);
        }
References System.Threading.CancellationTokenSource.Cancel(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Threading.CancellationTokenSource.CreateLinkedTokenSource(), System.Threading.Tasks.Task< TResult >.Delay(), System.Threading.SemaphoreSlim.m_lockObj, System.obj, System.Threading.SemaphoreSlim.RemoveAsyncWaiter(), System.task, System.Threading.CancellationToken.ThrowIfCancellationRequested(), System.Threading.CancellationTokenSource.Token, and System.Threading.Tasks.Task< TResult >.WhenAny().
Referenced by System.Threading.SemaphoreSlim.d__32.MoveNext(), and System.Threading.SemaphoreSlim.WaitAsync().