Terraria Decompiled: System.Threading.SemaphoreSlim.Release
Release() [2/2]
int System.Threading.SemaphoreSlim.Release (int releaseCount) inline
Definition at line 381 of file SemaphoreSlim.cs.
        {
            this.CheckDispose();
            if (releaseCount < 1)
            {
                throw new ArgumentOutOfRangeException("releaseCount", releaseCount, SemaphoreSlim.GetResourceString("The releaseCount argument must be greater than zero."));
            }
            object lockObj = this.m_lockObj;
            int num2;
            lock (lockObj)
            {
                int num = this.m_currentCount;
                num2 = num;
                if (this.m_maxCount - num < releaseCount)
                {
                    throw new SemaphoreFullException();
                }
                num += releaseCount;
                int waitCount = this.m_waitCount;
                if (num == 1 || waitCount == 1)
                {
                    Monitor.Pulse(this.m_lockObj);
                }
                else if (waitCount > 1)
                {
                    Monitor.PulseAll(this.m_lockObj);
                }
                if (this.m_asyncHead != null)
                {
                    int num3 = num - waitCount;
                    while (num3 > 0 && this.m_asyncHead != null)
                    {
                        num--;
                        num3--;
                        SemaphoreSlim.TaskNode asyncHead = this.m_asyncHead;
                        this.RemoveAsyncWaiter(asyncHead);
                        SemaphoreSlim.QueueWaiterTask(asyncHead);
                    }
                }
                this.m_currentCount = num;
                if (this.m_waitHandle != null && num2 == 0 && num > 0)
                {
                    this.m_waitHandle.Set();
                }
            }
            return num2;
        }
References System.Threading.SemaphoreSlim.CheckDispose(), System.Threading.SemaphoreSlim.GetResourceString(), System.Threading.SemaphoreSlim.m_asyncHead, System.Threading.SemaphoreSlim.m_currentCount, System.Threading.SemaphoreSlim.m_lockObj, System.Threading.SemaphoreSlim.m_maxCount, System.Threading.SemaphoreSlim.m_waitCount, System.Threading.SemaphoreSlim.m_waitHandle, System.Threading.Monitor.Pulse(), System.Threading.Monitor.PulseAll(), System.Threading.SemaphoreSlim.QueueWaiterTask(), System.Threading.SemaphoreSlim.RemoveAsyncWaiter(), and System.Threading.EventWaitHandle.Set().