Terraria Decompiled: System.Threading.SemaphoreSlim.Wait
Wait() [4/6]
bool System.Threading.SemaphoreSlim.Wait (int millisecondsTimeout, CancellationToken cancellationToken) inline
Definition at line 113 of file SemaphoreSlim.cs.
        {
            this.CheckDispose();
            if (millisecondsTimeout < -1)
            {
                throw new ArgumentOutOfRangeException("totalMilliSeconds", millisecondsTimeout, SemaphoreSlim.GetResourceString("The timeout must represent a value between -1 and Int32.MaxValue, inclusive."));
            }
            cancellationToken.ThrowIfCancellationRequested();
            if (millisecondsTimeout == 0 && this.m_currentCount == 0)
            {
                return false;
            }
            uint num = 0U;
            if (millisecondsTimeout != -1 && millisecondsTimeout > 0)
            {
                num = TimeoutHelper.GetTime();
            }
            bool flag = false;
            Task<bool> task = null;
            bool flag2 = false;
            CancellationTokenRegistration cancellationTokenRegistration = cancellationToken.InternalRegisterWithoutEC(SemaphoreSlim.s_cancellationTokenCanceledEventHandler, this);
            try
            {
                SpinWait spinWait = default(SpinWait);
                while (this.m_currentCount == 0 && !spinWait.NextSpinWillYield)
                {
                    spinWait.SpinOnce();
                }
                try
                {
                }
                finally
                {
                    Monitor.Enter(this.m_lockObj, ref flag2);
                    if (flag2)
                    {
                        this.m_waitCount++;
                    }
                }
                if (this.m_asyncHead != null)
                {
                    task = this.WaitAsync(millisecondsTimeout, cancellationToken);
                }
                else
                {
                    OperationCanceledException ex = null;
                    if (this.m_currentCount == 0)
                    {
                        if (millisecondsTimeout == 0)
{
                            return false;
                        }
                        try
{
                            flag = this.WaitUntilCountOrTimeout(millisecondsTimeout, num, cancellationToken);
                        }
                        catch (OperationCanceledException ex)
{
                        }
                    }
                    if (this.m_currentCount > 0)
                    {
                        flag = true;
                        this.m_currentCount--;
                    }
                    else if (ex != null)
                    {
                        throw ex;
                    }
                    if (this.m_waitHandle != null && this.m_currentCount == 0)
                    {
                        this.m_waitHandle.Reset();
                    }
                }
            }
            finally
            {
                if (flag2)
                {
                    this.m_waitCount--;
                    Monitor.Exit(this.m_lockObj);
                }
                cancellationTokenRegistration.Dispose();
            }
            if (task == null)
            {
                return flag;
            }
            return task.GetAwaiter().GetResult();
        }
References System.Threading.SemaphoreSlim.CheckDispose(), System.Threading.CancellationTokenRegistration.Dispose(), System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), System.Threading.SemaphoreSlim.GetResourceString(), System.Threading.TimeoutHelper.GetTime(), System.Threading.CancellationToken.InternalRegisterWithoutEC(), System.Threading.SemaphoreSlim.m_asyncHead, System.Threading.SemaphoreSlim.m_currentCount, System.Threading.SemaphoreSlim.m_lockObj, System.Threading.SemaphoreSlim.m_waitCount, System.Threading.SemaphoreSlim.m_waitHandle, System.Threading.SpinWait.NextSpinWillYield, System.Threading.EventWaitHandle.Reset(), System.Threading.SemaphoreSlim.s_cancellationTokenCanceledEventHandler, System.Threading.SpinWait.SpinOnce(), System.task, System.Threading.CancellationToken.ThrowIfCancellationRequested(), System.U, System.Threading.SemaphoreSlim.WaitAsync(), and System.Threading.SemaphoreSlim.WaitUntilCountOrTimeout().