Terraria Decompiled: System.Threading.SemaphoreSlim.RemoveAsyncWaiter
RemoveAsyncWaiter()
bool System.Threading.SemaphoreSlim.RemoveAsyncWaiter (SemaphoreSlim::TaskNode task) inline private
Definition at line 319 of file SemaphoreSlim.cs.
        {
            bool flag = this.m_asyncHead == task || task.Prev != null;
            if (task.Next != null)
            {
                task.Next.Prev = task.Prev;
            }
            if (task.Prev != null)
            {
                task.Prev.Next = task.Next;
            }
            if (this.m_asyncHead == task)
            {
                this.m_asyncHead = task.Next;
            }
            if (this.m_asyncTail == task)
            {
                this.m_asyncTail = task.Prev;
            }
            task.Next = (task.Prev = null);
            return flag;
        }
References System.Threading.SemaphoreSlim.m_asyncHead, System.Threading.SemaphoreSlim.m_asyncTail, and System.task.
Referenced by System.Threading.SemaphoreSlim.d__32.MoveNext(), System.Threading.SemaphoreSlim.Release(), and System.Threading.SemaphoreSlim.WaitUntilCountOrTimeoutAsync().