Terraria Decompiled: System.SharedStatics.GetSharedStringMaker
GetSharedStringMaker()
static Tokenizer.StringMaker System.SharedStatics.GetSharedStringMaker () inline static
Definition at line 51 of file SharedStatics.cs.
        {
            Tokenizer.StringMaker stringMaker = null;
            bool flag = false;
            RuntimeHelpers.PrepareConstrainedRegions();
            try
            {
                Monitor.Enter(SharedStatics._sharedStatics, ref flag);
                if (SharedStatics._sharedStatics._maker != null)
                {
                    stringMaker = SharedStatics._sharedStatics._maker;
                    SharedStatics._sharedStatics._maker = null;
                }
            }
            finally
            {
                if (flag)
                {
                    Monitor.Exit(SharedStatics._sharedStatics);
                }
            }
            if (stringMaker == null)
            {
                stringMaker = new Tokenizer.StringMaker();
            }
            return stringMaker;
        }
References System.SharedStatics._maker, System.SharedStatics._sharedStatics, System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), and System.Runtime.CompilerServices.RuntimeHelpers.PrepareConstrainedRegions().
Referenced by System.Security.Util.Tokenizer.BasicInitialization(), and System.Security.SecurityDocument.GetString().