Terraria Decompiled: Terraria.Testing.PacketHistory.Record
Record()
void Terraria.Testing.PacketHistory.Record (byte[] buffer, int offset, int length) inline
Definition at line 20 of file PacketHistory.cs.
        {
            length = Math.Max(0, length);
            PacketHistory.PacketView packetView = this.AppendPacket(length);
            Buffer.BlockCopy(buffer, offset, this._buffer, packetView.Offset, length);
        }
References Terraria.Testing.PacketHistory._buffer, Terraria.Testing.PacketHistory.AppendPacket(), System.Buffer.BlockCopy(), System.length, System.Math.Max(), System.offset, and Terraria.Testing.PacketHistory.PacketView.Offset.