Terraria Decompiled: Terraria.Testing.PacketHistory.Dump
Dump()
void Terraria.Testing.PacketHistory.Dump (string reason) inline
Definition at line 44 of file PacketHistory.cs.
        {
            byte[] array = new byte[this._buffer.Length];
            Buffer.BlockCopy(this._buffer, this._bufferPosition, array, 0, this._buffer.Length - this._bufferPosition);
            Buffer.BlockCopy(this._buffer, 0, array, this._buffer.Length - this._bufferPosition, this._bufferPosition);
            StringBuilder stringBuilder = new StringBuilder();
            int num = 1;
            for (int i = 0; i < this._packets.Length; i++)
            {
                PacketHistory.PacketView packetView = this._packets[(i + this._historyPosition) % this._packets.Length];
                if (packetView.Offset != 0 || packetView.Length != 0)
                {
                    stringBuilder.Append(string.Format("Packet {0} [Assumed MessageID: {4}, Size: {2}, Buffer Position: {1}, Timestamp: {3:G}]\r\n", new object[]
                    {
                        num++,
                        packetView.Offset,
                        packetView.Length,
                        packetView.Time,
                        this._buffer[packetView.Offset]
                    }));
                    for (int j = 0; j < packetView.Length; j++)
                    {
                        stringBuilder.Append(this._buffer[packetView.Offset + j].ToString("X2") + " ");
                        if (j % 16 == 15 && j != this._packets.Length - 1)
{
                            stringBuilder.Append("\r\n");
                        }
                    }
                    stringBuilder.Append("\r\n\r\n");
                }
            }
            stringBuilder.Append(reason);
            Directory.CreateDirectory(Path.Combine(Main.SavePath, "NetDump"));
            File.WriteAllText(Path.Combine(Main.SavePath, "NetDump", this.CreateDumpFileName()), stringBuilder.ToString());
        }
References Terraria.Testing.PacketHistory._buffer, Terraria.Testing.PacketHistory._bufferPosition, Terraria.Testing.PacketHistory._historyPosition, Terraria.Testing.PacketHistory._packets, System.Text.StringBuilder.Append(), System.array, System.Buffer.BlockCopy(), System.IO.Path.Combine(), System.IO.Directory.CreateDirectory(), System.Globalization.Format, Terraria.Testing.PacketHistory.PacketView.Length, Terraria.Testing.PacketHistory.PacketView.Offset, Terraria.Main.SavePath, Terraria.Testing.PacketHistory.PacketView.Time, System.Text.StringBuilder.ToString(), and System.IO.File.WriteAllText().