Terraria Decompiled: System.Security.Cryptography.HMAC.GetHashAlgorithmWithFipsFallback
GetHashAlgorithmWithFipsFallback()
static HashAlgorithm System.Security.Cryptography.HMAC.GetHashAlgorithmWithFipsFallback (Func< HashAlgorithm > createStandardHashAlgorithmCallback, Func< HashAlgorithm > createFipsHashAlgorithmCallback) inline static package
Definition at line 182 of file HMAC.cs.
        {
            if (CryptoConfig.AllowOnlyFipsAlgorithms)
            {
                try
                {
                    return createFipsHashAlgorithmCallback();
                }
                catch (PlatformNotSupportedException ex)
                {
                    throw new InvalidOperationException(ex.Message, ex);
                }
            }
            return createStandardHashAlgorithmCallback();
        }
References System.Security.Cryptography.CryptoConfig.AllowOnlyFipsAlgorithms, and System.Exception.Message.
Referenced by System.Security.Cryptography.HMACSHA256.HMACSHA256(), System.Security.Cryptography.HMACSHA384.HMACSHA384(), and System.Security.Cryptography.HMACSHA512.HMACSHA512().