Terraria Decompiled: Terraria.Social.WeGame.WeGameP2PWriter.ClearUser
ClearUser()
void Terraria.Social.WeGame.WeGameP2PWriter.ClearUser (RailID user) inline
Definition at line 61 of file WeGameP2PWriter.cs.
        {
            object @lock = this._lock;
            lock (@lock)
            {
                if (this._pendingSendData.ContainsKey(user))
                {
                    Queue<WeGameP2PWriter.WriteInformation> queue = this._pendingSendData[user];
                    while (queue.Count > 0)
                    {
                        this._bufferPool.Enqueue(queue.Dequeue().Data);
                    }
                }
                if (this._pendingSendDataSwap.ContainsKey(user))
                {
                    Queue<WeGameP2PWriter.WriteInformation> queue2 = this._pendingSendDataSwap[user];
                    while (queue2.Count > 0)
                    {
                        this._bufferPool.Enqueue(queue2.Dequeue().Data);
                    }
                }
            }
        }
References Terraria.Social.WeGame.WeGameP2PWriter._bufferPool, Terraria.Social.WeGame.WeGameP2PWriter._lock, Terraria.Social.WeGame.WeGameP2PWriter._pendingSendData, Terraria.Social.WeGame.WeGameP2PWriter._pendingSendDataSwap, System.Collections.Generic.Queue< T >.Enqueue(), and System.queue.
Referenced by Terraria.Social.WeGame.NetClientSocialModule.Close(), and Terraria.Social.WeGame.NetServerSocialModule.CloseAndUpdateUserState().