Terraria Decompiled: Terraria.Social.WeGame.WeGameP2PWriter.SendAll
SendAll()
void Terraria.Social.WeGame.WeGameP2PWriter.SendAll () inline
Definition at line 108 of file WeGameP2PWriter.cs.
        {
            if (!this.IsValid())
            {
                return;
            }
            object @lock = this._lock;
            lock (@lock)
            {
                Utils.Swap<Dictionary<RailID, Queue<WeGameP2PWriter.WriteInformation>>>(ref this._pendingSendData, ref this._pendingSendDataSwap);
            }
            foreach (KeyValuePair<RailID, Queue<WeGameP2PWriter.WriteInformation>> keyValuePair in this._pendingSendDataSwap)
            {
                Queue<WeGameP2PWriter.WriteInformation> value = keyValuePair.Value;
                while (value.Count > 0)
                {
                    WeGameP2PWriter.WriteInformation writeInformation = value.Dequeue();
                    bool flag2 = rail_api.RailFactory().RailNetworkHelper().SendData(this.GetLocalPeer(), keyValuePair.Key, writeInformation.Data, (uint)writeInformation.Size) == 0;
                    this._bufferPool.Enqueue(writeInformation.Data);
                }
            }
        }
References Terraria.Social.WeGame.WeGameP2PWriter._bufferPool, Terraria.Social.WeGame.WeGameP2PWriter._lock, Terraria.Social.WeGame.WeGameP2PWriter._pendingSendData, Terraria.Social.WeGame.WeGameP2PWriter._pendingSendDataSwap, Terraria.Social.WeGame.WeGameP2PWriter.WriteInformation.Data, System.Collections.Generic.Queue< T >.Enqueue(), Terraria.Social.WeGame.WeGameP2PWriter.GetLocalPeer(), Terraria.Social.WeGame.WeGameP2PWriter.IsValid(), rail.rail_api.RailFactory(), rail.IRailFactory.RailNetworkHelper(), rail.IRailNetwork.SendData(), Terraria.Social.WeGame.WeGameP2PWriter.WriteInformation.Size, and System.value.
Referenced by Terraria.Social.WeGame.NetSocialModule.Initialize().