Terraria Decompiled: System.Reflection.Emit.DynamicMethod.CreateDelegate
CreateDelegate() [1/2]
override Delegate System.Reflection.Emit.DynamicMethod.CreateDelegate (Type delegateType) inline sealed virtual
Reimplemented from System.Reflection.MethodInfo.
Definition at line 155 of file DynamicMethod.cs.
        {
            if (delegateType == null)
            {
                throw new ArgumentNullException("delegateType");
            }
            if (this.deleg != null)
            {
                return this.deleg;
            }
            this.CreateDynMethod();
            this.deleg = Delegate.CreateDelegate(delegateType, null, this);
            return this.deleg;
        }
References System.Delegate.CreateDelegate(), System.Reflection.Emit.DynamicMethod.CreateDynMethod(), and System.Reflection.Emit.DynamicMethod.deleg.
Referenced by Newtonsoft.Json.Utilities.DynamicReflectionDelegateFactory.CreateDefaultConstructor< T >(), Newtonsoft.Json.Utilities.DynamicReflectionDelegateFactory.CreateGet< T >(), Newtonsoft.Json.Utilities.DynamicReflectionDelegateFactory.CreateGet< T >(), Newtonsoft.Json.Utilities.DynamicReflectionDelegateFactory.CreateMethodCall< T >(), Newtonsoft.Json.Utilities.DynamicReflectionDelegateFactory.CreateParameterizedConstructor(), Newtonsoft.Json.Utilities.DynamicReflectionDelegateFactory.CreateSet< T >(), and Newtonsoft.Json.Utilities.DynamicReflectionDelegateFactory.CreateSet< T >().