Terraria Decompiled: System.Reflection.Emit.DynamicMethod.CreateDynMethod
CreateDynMethod()
void System.Reflection.Emit.DynamicMethod.CreateDynMethod () inline private
Definition at line 114 of file DynamicMethod.cs.
        {
            lock (this)
            {
                if (this.mhandle.Value == IntPtr.Zero)
                {
                    if (this.ilgen == null || this.ilgen.ILOffset == 0)
                    {
                        throw new InvalidOperationException("Method '" + this.name + "' does not have a method body.");
                    }
                    this.ilgen.label_fixup(this);
                    try
                    {
                        this.creating = true;
                        if (this.refs != null)
{
                            for (int i = 0; i < this.refs.Length; i++)
{
                                if (this.refs[i] is DynamicMethod)
{
                                    DynamicMethod dynamicMethod = (DynamicMethod)this.refs[i];
                                    if (!dynamicMethod.creating)
{
                                        dynamicMethod.CreateDynMethod();
                                    }
                                }
                            }
                        }
                    }
                    finally
                    {
                        this.creating = false;
                    }
                    DynamicMethod.create_dynamic_method(this);
                    this.ilgen = null;
                }
            }
        }
References System.Reflection.Emit.DynamicMethod.create_dynamic_method(), System.Reflection.Emit.DynamicMethod.CreateDynMethod(), System.Reflection.Emit.DynamicMethod.creating, System.Reflection.Emit.DynamicMethod.DynamicMethod(), System.Reflection.Emit.DynamicMethod.ilgen, System.Reflection.Emit.ILGenerator.ILOffset, System.Reflection.Emit.ILGenerator.label_fixup(), System.Reflection.Emit.DynamicMethod.mhandle, System.Reflection.Emit.DynamicMethod.name, System.Reflection.Emit.DynamicMethod.refs, System.RuntimeMethodHandle.Value, and System.IntPtr.Zero.
Referenced by System.Reflection.Emit.DynamicMethod.CreateDelegate(), System.Reflection.Emit.DynamicMethod.CreateDelegate(), System.Reflection.Emit.DynamicMethod.CreateDynMethod(), and System.Reflection.Emit.DynamicMethod.Invoke().