Terraria Decompiled: Terraria.Social.WeGame.WeGameP2PWriter.QueueSend
QueueSend()
void Terraria.Social.WeGame.WeGameP2PWriter.QueueSend (RailID user, byte[] data, int length) inline
Definition at line 16 of file WeGameP2PWriter.cs.
        {
            object @lock = this._lock;
            lock (@lock)
            {
                Queue<WeGameP2PWriter.WriteInformation> queue;
                if (this._pendingSendData.ContainsKey(user))
                {
                    queue = this._pendingSendData[user];
                }
                else
                {
                    queue = (this._pendingSendData[user] = new Queue<WeGameP2PWriter.WriteInformation>());
                }
                int i = length;
                int num = 0;
                while (i > 0)
                {
                    WeGameP2PWriter.WriteInformation writeInformation;
                    if (queue.Count == 0 || 1024 - queue.Peek().Size == 0)
                    {
                        if (this._bufferPool.Count > 0)
{
                            writeInformation = new WeGameP2PWriter.WriteInformation(this._bufferPool.Dequeue());
                        }
                        else
{
                            writeInformation = new WeGameP2PWriter.WriteInformation();
                        }
                        queue.Enqueue(writeInformation);
                    }
                    else
                    {
                        writeInformation = queue.Peek();
                    }
                    int num2 = Math.Min(i, 1024 - writeInformation.Size);
                    Array.Copy(data, num, writeInformation.Data, writeInformation.Size, num2);
                    writeInformation.Size += num2;
                    i -= num2;
                    num += num2;
                }
            }
        }
References Terraria.Social.WeGame.WeGameP2PWriter._bufferPool, Terraria.Social.WeGame.WeGameP2PWriter._lock, Terraria.Social.WeGame.WeGameP2PWriter._pendingSendData, System.Array.Copy(), System.Collections.Generic.Queue< T >.Count, Terraria.Social.WeGame.WeGameP2PWriter.WriteInformation.Data, System.Collections.Generic.Queue< T >.Dequeue(), System.length, System.Math.Min(), System.queue, and Terraria.Social.WeGame.WeGameP2PWriter.WriteInformation.Size.
Referenced by Terraria.Social.WeGame.NetSocialModule.Send().