Terraria Decompiled: System.Reflection.Emit.DynamicMethod.GetParametersInternal
GetParametersInternal()
override ParameterInfo[] System.Reflection.Emit.DynamicMethod.GetParametersInternal () inline package virtual
Reimplemented from System.Reflection.MethodBase.
Definition at line 275 of file DynamicMethod.cs.
        {
            if (this.parameters == null)
            {
                return EmptyArray<ParameterInfo>.Value;
            }
            ParameterInfo[] array = new ParameterInfo[this.parameters.Length];
            for (int i = 0; i < this.parameters.Length; i++)
            {
                ParameterInfo[] array2 = array;
                int num = i;
                ParameterBuilder[] array3 = this.pinfo;
                array2[num] = RuntimeParameterInfo.New((array3 != null) ? array3[i + 1] : null, this.parameters[i], this, i + 1);
            }
            return array;
        }
References System.array, System.Reflection.RuntimeParameterInfo.New(), System.Reflection.Emit.DynamicMethod.parameters, System.Reflection.Emit.DynamicMethod.pinfo, and System.EmptyArray< T >.Value.
Referenced by System.Reflection.Emit.DynamicMethod.GetParameters(), and System.Reflection.Emit.DynamicMethod.ToString().