Terraria Decompiled: Terraria.GameContent.TilePaintSystemV2.TryGetTileAndRequestIfNotReady
TryGetTileAndRequestIfNotReady()
Texture2D Terraria.GameContent.TilePaintSystemV2.TryGetTileAndRequestIfNotReady (int tileType, int tileStyle, int paintColor) inline
Definition at line 158 of file TilePaintSystemV2.cs.
        {
            TilePaintSystemV2.TileVariationkey tileVariationkey = new TilePaintSystemV2.TileVariationkey
            {
                TileType = tileType,
                TileStyle = tileStyle,
                PaintColor = paintColor
            };
            TilePaintSystemV2.TileRenderTargetHolder tileRenderTargetHolder;
            if (this._tilesRenders.TryGetValue(tileVariationkey, out tileRenderTargetHolder) && tileRenderTargetHolder.IsReady)
            {
                return tileRenderTargetHolder.Target;
            }
            this.RequestTile(ref tileVariationkey);
            return null;
        }
References Terraria.GameContent.TilePaintSystemV2._tilesRenders, Terraria.GameContent.TilePaintSystemV2.ARenderTargetHolder.IsReady, Terraria.GameContent.TilePaintSystemV2.RequestTile(), and Terraria.GameContent.TilePaintSystemV2.ARenderTargetHolder.Target.
Referenced by Terraria.HitTile.DrawFreshAnimations(), and Terraria.GameContent.Drawing.TileDrawing.LookupTileDrawTexture().