Terraria Decompiled: ReLogic.Utilities.AttributeUtilities.GetAttribute< T >
GetAttribute< T >() [1/3]
static T ReLogic.Utilities.AttributeUtilities.GetAttribute< T > (this Enum value) inline static
Type Constraints
T : Attribute
Definition at line 17 of file AttributeUtilities.cs.
                                                                 : Attribute
        {
            Type type = value.GetType();
            string name = Enum.GetName(type, value);
            return Enumerable.SingleOrDefault<T>(Enumerable.OfType<T>(type.GetField(name).GetCustomAttributes(false)));
        }
References System.Reflection.MemberInfo.GetCustomAttributes(), System.Type.GetField(), System.Enum.GetName(), System.Type.GetType(), System.name, and System.value.