Terraria Decompiled: System.Runtime.Remoting.Activation.AppDomainLevelActivator.Activate
Activate()
IConstructionReturnMessage System.Runtime.Remoting.Activation.AppDomainLevelActivator.Activate (IConstructionCallMessage ctorCall) inline
Implements System.Runtime.Remoting.Activation.IActivator.
Definition at line 42 of file AppDomainLevelActivator.cs.
        {
            IActivator activator = (IActivator)RemotingServices.Connect(typeof(IActivator), this._activationUrl);
            ctorCall.Activator = ctorCall.Activator.NextActivator;
            IConstructionReturnMessage constructionReturnMessage;
            try
            {
                constructionReturnMessage = activator.Activate(ctorCall);
            }
            catch (Exception ex)
            {
                return new ConstructionResponse(ex, ctorCall);
            }
            ObjRef objRef = (ObjRef)constructionReturnMessage.ReturnValue;
            if (RemotingServices.GetIdentityForUri(objRef.URI) != null)
            {
                throw new RemotingException("Inconsistent state during activation; there may be two proxies for the same object");
            }
            object obj;
            Identity orCreateClientIdentity = RemotingServices.GetOrCreateClientIdentity(objRef, null, out obj);
            RemotingServices.SetMessageTargetIdentity(ctorCall, orCreateClientIdentity);
            return constructionReturnMessage;
        }
References System.Runtime.Remoting.Activation.AppDomainLevelActivator._activationUrl, System.Runtime.Remoting.Activation.IActivator.Activate(), System.Runtime.Remoting.Activation.IConstructionCallMessage.Activator, System.Runtime.Remoting.RemotingServices.Connect(), System.Runtime.Remoting.RemotingServices.GetIdentityForUri(), System.Runtime.Remoting.RemotingServices.GetOrCreateClientIdentity(), System.Runtime.Remoting.Activation.IActivator.NextActivator, System.obj, System.Runtime.Remoting.Messaging.IMethodReturnMessage.ReturnValue, System.Runtime.Remoting.RemotingServices.SetMessageTargetIdentity(), and System.Runtime.Remoting.ObjRef.URI.