Terraria Decompiled: System.Security.Cryptography.RSAOAEPKeyExchangeFormatter.CreateKeyExchange
CreateKeyExchange() [1/2]
override byte[] System.Security.Cryptography.RSAOAEPKeyExchangeFormatter.CreateKeyExchange (byte[] rgbData) inline
Definition at line 87 of file RSAOAEPKeyExchangeFormatter.cs.
        {
            if (this._rsaKey == null)
            {
                throw new CryptographicUnexpectedOperationException(Environment.GetResourceString("No asymmetric key object has been associated with this formatter object."));
            }
            if (this.OverridesEncrypt)
            {
                return this._rsaKey.Encrypt(rgbData, RSAEncryptionPadding.OaepSHA1);
            }
            return Utils.RsaOaepEncrypt(this._rsaKey, SHA1.Create(), new PKCS1MaskGenerationMethod(), RandomNumberGenerator.Create(), rgbData);
        }
References System.Security.Cryptography.RSAOAEPKeyExchangeFormatter._rsaKey, System.Security.Cryptography.RandomNumberGenerator.Create(), System.Security.Cryptography.SHA1.Create(), System.Security.Cryptography.RSA.Encrypt(), System.Environment.GetResourceString(), System.Security.Cryptography.RSAEncryptionPadding.OaepSHA1, System.Security.Cryptography.RSAOAEPKeyExchangeFormatter.OverridesEncrypt, and System.Security.Cryptography.Utils.RsaOaepEncrypt().
Referenced by System.Security.Cryptography.RSAOAEPKeyExchangeFormatter.CreateKeyExchange().