Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.BinaryObjectWithMap.Write
Write()
void System.Runtime.Serialization.Formatters.Binary.BinaryObjectWithMap.Write (__BinaryWriter sout) inline
Implements System.Runtime.Serialization.Formatters.Binary.IStreamable.
Definition at line 38 of file BinaryObjectWithMap.cs.
        {
            sout.WriteByte((byte)this.binaryHeaderEnum);
            sout.WriteInt32(this.objectId);
            sout.WriteString(this.name);
            sout.WriteInt32(this.numMembers);
            for (int i = 0; i < this.numMembers; i++)
            {
                sout.WriteString(this.memberNames[i]);
            }
            if (this.assemId > 0)
            {
                sout.WriteInt32(this.assemId);
            }
        }
References System.Runtime.Serialization.Formatters.Binary.BinaryObjectWithMap.assemId, System.Runtime.Serialization.Formatters.Binary.BinaryObjectWithMap.binaryHeaderEnum, System.Runtime.Serialization.Formatters.Binary.BinaryObjectWithMap.memberNames, System.Runtime.Serialization.Formatters.Binary.BinaryObjectWithMap.name, System.Runtime.Serialization.Formatters.Binary.BinaryObjectWithMap.numMembers, System.Runtime.Serialization.Formatters.Binary.BinaryObjectWithMap.objectId, System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteByte(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteInt32(), and System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteString().
Referenced by System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteObject().