Terraria Decompiled: Terraria.Rain.NewRain
NewRain()
static int Terraria.Rain.NewRain (Vector2 Position, Vector2 Velocity) inline static private
Definition at line 185 of file Rain.cs.
        {
            int num = -1;
            int num2 = (int)((float)Main.maxRain * Main.cloudAlpha);
            if (num2 > Main.maxRain)
            {
                num2 = Main.maxRain;
            }
            float num3 = (float)Main.maxTilesX / 6400f;
            Math.Max(0f, Math.Min(1f, (Main.player[Main.myPlayer].position.Y / 16f - 85f * num3) / (60f * num3)));
            float num4 = (1f + Main.gfxQuality) / 2f;
            if ((double)num4 < 0.9)
            {
                num2 = (int)((float)num2 * num4);
            }
            float num5 = Utils.Clamp<float>((float)Main.SceneMetrics.SnowTileCount / (float)SceneMetrics.SnowTileThreshold, 0f, 1f);
            num5 *= num5;
            num2 = (int)((float)num2 * (1f - num5));
            num2 = (int)((double)num2 * Math.Pow((double)Main.atmo, 9.0));
            if ((double)Main.atmo < 0.4)
            {
                num2 = 0;
            }
            for (int i = 0; i < num2; i++)
            {
                if (!Main.rain[i].active)
                {
                    num = i;
                    break;
                }
            }
            if (num == -1)
            {
                return Main.maxRain;
            }
            Rain rain = Main.rain[num];
            rain.active = true;
            rain.position = Position;
            rain.scale = 1f + (float)Main.rand.Next(-20, 21) * 0.01f;
            rain.velocity = Velocity * rain.scale;
            rain.rotation = (float)Math.Atan2((double)rain.velocity.X, (double)(-(double)rain.velocity.Y));
            rain.type = (byte)(Main.waterStyle * 3 + Main.rand.Next(3));
            return num;
        }
References Terraria.Rain.active, System.Math.Atan2(), Terraria.Main.atmo, Terraria.Utils.Clamp(), Terraria.Main.cloudAlpha, Terraria.Main.gfxQuality, int, System.Math.Max(), Terraria.Main.maxRain, Terraria.Main.maxTilesX, System.Math.Min(), Terraria.Main.myPlayer, Terraria.Main.player, Terraria.Entity.position, System.Math.Pow(), Terraria.Main.rain, Terraria.Main.rand, Terraria.Rain.scale, Terraria.Main.SceneMetrics, Terraria.SceneMetrics.SnowTileCount, Terraria.SceneMetrics.SnowTileThreshold, Terraria.Rain.velocity, Terraria.Main.waterStyle, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Rain.MakeRain().