Terraria Decompiled: Terraria.Rain.Update
Update()
void Terraria.Rain.Update () inline
Definition at line 108 of file Rain.cs.
        {
            if (Main.gamePaused)
            {
                return;
            }
            this.position += this.velocity;
            if (Main.gameMenu)
            {
                if (this.position.Y > Main.screenPosition.Y + (float)Main.screenHeight + 2000f)
                {
                    this.active = false;
                    return;
                }
            }
            else if (Main.remixWorld)
            {
                if (this.position.Y > Main.screenPosition.Y + (float)Main.screenHeight + 100f)
                {
                    this.active = false;
                    return;
                }
            }
            else if (Collision.SolidCollision(this.position, 2, 2) || this.position.Y > Main.screenPosition.Y + (float)Main.screenHeight + 100f || Collision.WetCollision(this.position, 2, 2))
            {
                this.active = false;
                if ((float)Main.rand.Next(100) < Main.gfxQuality * 100f)
                {
                    int num = Dust.NewDust(this.position - this.velocity, 2, 2, Dust.dustWater(), 0f, 0f, 0, default(Color), 1f);
                    Dust dust = Main.dust[num];
                    dust.position.X = dust.position.X - 2f;
                    Dust dust2 = Main.dust[num];
                    dust2.position.Y = dust2.position.Y + 2f;
                    Main.dust[num].alpha = 38;
                    Main.dust[num].velocity *= 0.1f;
                    Main.dust[num].velocity += -this.velocity * 0.025f;
                    Dust dust3 = Main.dust[num];
                    dust3.velocity.Y = dust3.velocity.Y - 2f;
                    Main.dust[num].scale = 0.6f;
                    Main.dust[num].noGravity = true;
                }
            }
        }
References Terraria.Dust.alpha, Terraria.Main.dust, Terraria.Dust.dustWater(), Terraria.Main.gameMenu, Terraria.Main.gamePaused, Terraria.Main.gfxQuality, Terraria.Dust.NewDust(), Terraria.Dust.noGravity, Terraria.Rain.position, Terraria.Main.rand, Terraria.Main.remixWorld, Terraria.Dust.scale, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Collision.SolidCollision(), Terraria.Dust.velocity, Terraria.Rain.velocity, Terraria.Collision.WetCollision(), and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Main.DrawRain().