Terraria Decompiled: System.IO.File.d__72.MoveNext
MoveNext()
void IAsyncStateMachine. System.IO.File.d__72.MoveNext () inline
Implements System.Runtime.CompilerServices.IAsyncStateMachine.
Definition at line 1464 of file File.cs.
            {
                int num2;
                int num = num2;
                byte[] array2;
                try
                {
                    if (num != 0)
                    {
                        rentedArray = ArrayPool<byte>.Shared.Rent(512);
                    }
                    try
                    {
                        ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter;
                        if (num == 0)
{
                            ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter2;
                            configuredValueTaskAwaiter = configuredValueTaskAwaiter2;
                            configuredValueTaskAwaiter2 = default(ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter);
                            num = (num2 = -1);
                            goto IL_0121;
                        }
                        bytesRead = 0;
                        IL_002D:
                        if (bytesRead == rentedArray.Length)
{
                            uint num3 = (uint)(rentedArray.Length * 2);
                            if (num3 > 2147483591U)
{
                                num3 = (uint)Math.Max(2147483591, rentedArray.Length + 1);
                            }
                            byte[] array = ArrayPool<byte>.Shared.Rent((int)num3);
                            Buffer.BlockCopy(rentedArray, 0, array, 0, bytesRead);
                            ArrayPool<byte>.Shared.Return(rentedArray, false);
                            rentedArray = array;
                        }
                        configuredValueTaskAwaiter = fs.ReadAsync(rentedArray.AsMemory(bytesRead), cancellationToken).ConfigureAwait(false).GetAwaiter();
                        if (!configuredValueTaskAwaiter.IsCompleted)
{
                            num = (num2 = 0);
                            ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter2 = configuredValueTaskAwaiter;
                            this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter, File.<InternalReadAllBytesUnknownLengthAsync>d__72>(ref configuredValueTaskAwaiter, ref this);
                            return;
                        }
                        IL_0121:
                        int result = configuredValueTaskAwaiter.GetResult();
                        if (result != 0)
{
                            bytesRead += result;
                            goto IL_002D;
                        }
                        array2 = rentedArray.AsSpan(0, bytesRead).ToArray();
                    }
                    finally
                    {
                        if (num < 0)
{
                            fs.Dispose();
                            ArrayPool<byte>.Shared.Return(rentedArray, false);
                        }
                    }
                }
                catch (Exception ex)
                {
                    num2 = -2;
                    rentedArray = null;
                    this.<>t__builder.SetException(ex);
                    return;
                }
                num2 = -2;
                rentedArray = null;
                this.<>t__builder.SetResult(array2);
            }
References System.array, System.Buffer.BlockCopy(), System.IO.File.InternalReadAllBytesUnknownLengthAsync(), System.Math.Max(), System.Buffers.ArrayPool< T >.Shared, and System.U.