Terraria Decompiled: System.TermInfoDriver.Init
Init()
void System.TermInfoDriver.Init () inline
Implements System.IConsoleDriver.
Definition at line 116 of file TermInfoDriver.cs.
        {
            if (this.inited)
            {
                return;
            }
            object obj = this.initLock;
            lock (obj)
            {
                if (!this.inited)
                {
                    try
                    {
                        if (!ConsoleDriver.IsConsole)
{
                            throw new IOException("Not a tty.");
                        }
                        ConsoleDriver.SetEcho(false);
                        string text = null;
                        this.keypadXmit = this.reader.Get(TermInfoStrings.KeypadXmit);
                        this.keypadLocal = this.reader.Get(TermInfoStrings.KeypadLocal);
                        if (this.keypadXmit != null)
{
                            this.WriteConsole(this.keypadXmit);
                            if (this.keypadLocal != null)
{
                                text += this.keypadLocal;
                            }
                        }
                        this.origPair = this.reader.Get(TermInfoStrings.OrigPair);
                        this.origColors = this.reader.Get(TermInfoStrings.OrigColors);
                        this.setfgcolor = this.reader.Get(TermInfoStrings.SetAForeground);
                        this.setbgcolor = this.reader.Get(TermInfoStrings.SetABackground);
                        this.maxColors = this.reader.Get(TermInfoNumbers.MaxColors);
                        this.maxColors = Math.Max(Math.Min(this.maxColors, 16), 1);
                        string text2 = ((this.origColors == null) ? this.origPair : this.origColors);
                        if (text2 != null)
{
                            text += text2;
                        }
                        if (!ConsoleDriver.TtySetup(this.keypadXmit, text, out this.control_characters, out TermInfoDriver.native_terminal_size))
{
                            this.control_characters = new byte[17];
                            TermInfoDriver.native_terminal_size = null;
                        }
                        this.stdin = new StreamReader(Console.OpenStandardInput(0), Console.InputEncoding);
                        this.clear = this.reader.Get(TermInfoStrings.ClearScreen);
                        this.bell = this.reader.Get(TermInfoStrings.Bell);
                        if (this.clear == null)
{
                            this.clear = this.reader.Get(TermInfoStrings.CursorHome);
                            this.clear += this.reader.Get(TermInfoStrings.ClrEos);
                        }
                        this.csrVisible = this.reader.Get(TermInfoStrings.CursorNormal);
                        if (this.csrVisible == null)
{
                            this.csrVisible = this.reader.Get(TermInfoStrings.CursorVisible);
                        }
                        this.csrInvisible = this.reader.Get(TermInfoStrings.CursorInvisible);
                        if (this.term == "cygwin" || this.term == "linux" || (this.term != null && this.term.StartsWith("xterm")) || this.term == "rxvt" || this.term == "dtterm")
{
                            this.titleFormat = "\u001b]0;{0}\a";
                        }
                        else if (this.term == "iris-ansi")
{
                            this.titleFormat = "\u001bP1.y{0}\u001b\\";
                        }
                        else if (this.term == "sun-cmd")
{
                            this.titleFormat = "\u001b]l{0}\u001b\\";
                        }
                        this.cursorAddress = this.reader.Get(TermInfoStrings.CursorAddress);
                        this.GetCursorPosition();
                        if (this.noGetPosition)
{
                            this.WriteConsole(this.clear);
                            this.cursorLeft = 0;
                            this.cursorTop = 0;
                        }
                    }
                    finally
                    {
                        this.inited = true;
                    }
                }
            }
        }
References System.TermInfoDriver.clear, System.TermInfoDriver.csrVisible, System.TermInfoReader.Get(), System.TermInfoDriver.GetCursorPosition(), System.TermInfoDriver.inited, System.TermInfoDriver.initLock, System.Console.InputEncoding, System.ConsoleDriver.IsConsole, System.TermInfoDriver.keypadLocal, System.TermInfoDriver.keypadXmit, System.Math.Max(), System.Math.Min(), System.TermInfoDriver.native_terminal_size, System.TermInfoDriver.noGetPosition, System.obj, System.Console.OpenStandardInput(), System.TermInfoDriver.origColors, System.TermInfoDriver.origPair, System.TermInfoDriver.reader, System.ConsoleDriver.SetEcho(), System.TermInfoDriver.term, System.text, System.ConsoleDriver.TtySetup(), and System.TermInfoDriver.WriteConsole().
Referenced by System.TermInfoDriver.Beep(), System.TermInfoDriver.Clear(), System.TermInfoDriver.MoveBufferArea(), System.TermInfoDriver.ReadKeyInternal(), System.TermInfoDriver.ReadUntilConditionInternal(), System.TermInfoDriver.ResetColor(), System.TermInfoDriver.SetBufferSize(), System.TermInfoDriver.SetCursorPosition(), System.TermInfoDriver.SetWindowPosition(), and System.TermInfoDriver.SetWindowSize().