Terraria Decompiled: System.TermInfoDriver.TrySetWindowDimensions
TrySetWindowDimensions()
void System.TermInfoDriver.TrySetWindowDimensions (int width, int height) inline private
Definition at line 712 of file TermInfoDriver.cs.
        {
            if (width <= 0)
            {
                throw new ArgumentOutOfRangeException("width", "Value must be higher than 0");
            }
            if (height <= 0)
            {
                throw new ArgumentOutOfRangeException("height", "Value must be highet than 0");
            }
            if (height == this.WindowHeight && width == this.WindowWidth)
            {
                return;
            }
            if (this.term.StartsWith("xterm"))
            {
                this.WriteConsole(string.Concat(new string[]
                {
                    "\u001b[8;",
                    height.ToString(),
                    ";",
                    width.ToString(),
                    "t"
                }));
                Thread.Sleep(50);
                return;
            }
            throw new PlatformNotSupportedException("Resizing can only work in xterm-based terminals");
        }
References System.Threading.Thread.Sleep(), System.TermInfoDriver.term, System.TermInfoDriver.WindowHeight, System.TermInfoDriver.WindowWidth, and System.TermInfoDriver.WriteConsole().
Referenced by System.TermInfoDriver.SetBufferSize(), and System.TermInfoDriver.SetWindowSize().