Terraria Decompiled: System.TermInfoDriver.SetCursorPosition
SetCursorPosition()
void System.TermInfoDriver.SetCursorPosition (int left, int top) inline
Implements System.IConsoleDriver.
Definition at line 1313 of file TermInfoDriver.cs.
        {
            if (!this.inited)
            {
                this.Init();
            }
            this.CheckWindowDimensions();
            if (left < 0 || left >= this.bufferWidth)
            {
                throw new ArgumentOutOfRangeException("left", left.ToString(), "Value must be positive and below the buffer width.");
            }
            if (top < 0 || top >= this.bufferHeight)
            {
                throw new ArgumentOutOfRangeException("top", top.ToString(), "Value must be positive and below the buffer height.");
            }
            if (this.cursorAddress == null)
            {
                throw new IOException("This terminal does not suport setting the cursor position.");
            }
            this.WriteConsole(ParameterizedStrings.Evaluate(this.cursorAddress, new ParameterizedStrings.FormatParam[] { top, left }));
            this.cursorLeft = left;
            this.cursorTop = top;
        }
References System.TermInfoDriver.bufferHeight, System.TermInfoDriver.bufferWidth, System.TermInfoDriver.CheckWindowDimensions(), System.TermInfoDriver.cursorAddress, System.ParameterizedStrings.Evaluate(), System.TermInfoDriver.Init(), System.TermInfoDriver.inited, and System.TermInfoDriver.WriteConsole().
Referenced by System.TermInfoDriver.WriteSpecialKey().