Terraria Decompiled: System.TermInfoDriver.Read
Read()
int System.TermInfoDriver.Read ([Out] char[] dest, int index, int count) inline
Definition at line 1124 of file TermInfoDriver.cs.
        {
            bool flag = false;
            int num = 0;
            StringBuilder stringBuilder = new StringBuilder();
            object keyFromBuffer;
            while ((keyFromBuffer = this.GetKeyFromBuffer(true)) != null)
            {
                ConsoleKeyInfo consoleKeyInfo = (ConsoleKeyInfo)keyFromBuffer;
                char c = consoleKeyInfo.KeyChar;
                if (consoleKeyInfo.Key != ConsoleKey.Backspace)
                {
                    if (consoleKeyInfo.Key == ConsoleKey.Enter)
                    {
                        num = stringBuilder.Length;
                    }
                    stringBuilder.Append(c);
                }
                else if (stringBuilder.Length > num)
                {
                    StringBuilder stringBuilder2 = stringBuilder;
                    int num2 = stringBuilder2.Length;
                    stringBuilder2.Length = num2 - 1;
                }
            }
            this.rl_startx = this.cursorLeft;
            this.rl_starty = this.cursorTop;
            for (;;)
            {
                bool flag2;
                ConsoleKeyInfo consoleKeyInfo = this.ReadKeyInternal(out flag2);
                flag = flag || flag2;
                char c = consoleKeyInfo.KeyChar;
                if (consoleKeyInfo.Key != ConsoleKey.Backspace)
                {
                    if (consoleKeyInfo.Key == ConsoleKey.Enter)
                    {
                        num = stringBuilder.Length;
                    }
                    stringBuilder.Append(c);
                    goto IL_00E0;
                }
                if (stringBuilder.Length > num)
                {
                    StringBuilder stringBuilder3 = stringBuilder;
                    int num2 = stringBuilder3.Length;
                    stringBuilder3.Length = num2 - 1;
                    goto IL_00E0;
                }
                IL_00EA:
                if (consoleKeyInfo.Key == ConsoleKey.Enter)
                {
                    break;
                }
                continue;
                IL_00E0:
                if (flag)
                {
                    this.Echo(consoleKeyInfo);
                    goto IL_00EA;
                }
                goto IL_00EA;
            }
            this.EchoFlush();
            this.rl_startx = -1;
            this.rl_starty = -1;
            int num3 = 0;
            while (count > 0 && num3 < stringBuilder.Length)
            {
                dest[index + num3] = stringBuilder[num3];
                num3++;
                count--;
            }
            for (int i = num3; i < stringBuilder.Length; i++)
            {
                this.AddToBuffer((int)stringBuilder[i]);
            }
            return num3;
        }
References System.TermInfoDriver.AddToBuffer(), System.Text.StringBuilder.Append(), System.count, System.TermInfoDriver.cursorLeft, System.TermInfoDriver.cursorTop, System.TermInfoDriver.Echo(), System.TermInfoDriver.EchoFlush(), System.TermInfoDriver.GetKeyFromBuffer(), System.index, System.ConsoleKeyInfo.Key, System.ConsoleKeyInfo.KeyChar, System.Text.StringBuilder.Length, and System.TermInfoDriver.ReadKeyInternal().
Referenced by System.IO.CStreamReader.Read().