Terraria Decompiled: System.TermInfoDriver.CreateKeyInfoFromInt
CreateKeyInfoFromInt()
ConsoleKeyInfo System.TermInfoDriver.CreateKeyInfoFromInt (int n, bool alt) inline private
Definition at line 905 of file TermInfoDriver.cs.
        {
            char c = (char)n;
            ConsoleKey consoleKey = (ConsoleKey)n;
            bool flag = false;
            bool flag2 = false;
            if (n <= 19)
            {
                switch (n)
                {
                case 8:
                case 9:
                case 12:
                case 13:
                    goto IL_00C7;
                case 10:
                    consoleKey = ConsoleKey.Enter;
                    goto IL_00C7;
                case 11:
                    break;
                default:
                    if (n == 19)
                    {
                        goto IL_00C7;
                    }
                    break;
                }
            }
            else
            {
                if (n == 27)
                {
                    consoleKey = ConsoleKey.Escape;
                    goto IL_00C7;
                }
                if (n == 32)
                {
                    consoleKey = ConsoleKey.Spacebar;
                    goto IL_00C7;
                }
                switch (n)
                {
                case 42:
                    consoleKey = ConsoleKey.Multiply;
                    goto IL_00C7;
                case 43:
                    consoleKey = ConsoleKey.Add;
                    goto IL_00C7;
                case 45:
                    consoleKey = ConsoleKey.Subtract;
                    goto IL_00C7;
                case 47:
                    consoleKey = ConsoleKey.Divide;
                    goto IL_00C7;
                }
            }
            if (n >= 1 && n <= 26)
            {
                flag2 = true;
                consoleKey = ConsoleKey.A + n - 1;
            }
            else if (n >= 97 && n <= 122)
            {
                consoleKey = (ConsoleKey)(-32) + n;
            }
            else if (n >= 65 && n <= 90)
            {
                flag = true;
            }
            else if (n < 48 || n > 57)
            {
                consoleKey = (ConsoleKey)0;
            }
            IL_00C7:
            return new ConsoleKeyInfo(c, consoleKey, flag, alt, flag2);
        }
Referenced by System.TermInfoDriver.GetKeyFromBuffer(), System.TermInfoDriver.IsSpecialKey(), and System.TermInfoDriver.WriteSpecialKey().