Terraria Decompiled: System.TermInfoDriver.IsSpecialKey
IsSpecialKey() [2/2]
bool System.TermInfoDriver.IsSpecialKey (ConsoleKeyInfo key) inline
Definition at line 269 of file TermInfoDriver.cs.
        {
            if (!this.inited)
            {
                return false;
            }
            switch (key.Key)
            {
            case ConsoleKey.Backspace:
                return true;
            case ConsoleKey.Tab:
                return true;
            case ConsoleKey.Clear:
                return true;
            case ConsoleKey.Enter:
                this.cursorLeft = 0;
                this.cursorTop++;
                if (this.cursorTop >= this.WindowHeight)
                {
                    this.cursorTop--;
                }
                return false;
            }
            this.IncrementX();
            return false;
        }
References System.TermInfoDriver.cursorTop, System.TermInfoDriver.IncrementX(), System.TermInfoDriver.inited, System.ConsoleKeyInfo.Key, and System.TermInfoDriver.WindowHeight.
Referenced by System.TermInfoDriver.Echo(), System.TermInfoDriver.IsSpecialKey(), System.IO.CStreamWriter.Write(), and System.IO.CStreamWriter.Write().