Terraria Decompiled: System.TermInfoDriver.ReadKey
ReadKey()
ConsoleKeyInfo System.TermInfoDriver.ReadKey (bool intercept) inline
Implements System.IConsoleDriver.
Definition at line 1205 of file TermInfoDriver.cs.
        {
            bool flag;
            ConsoleKeyInfo consoleKeyInfo = this.ReadKeyInternal(out flag);
            if (!intercept && flag)
            {
                this.Echo(consoleKeyInfo);
                this.EchoFlush();
            }
            return consoleKeyInfo;
        }
References System.TermInfoDriver.Echo(), System.TermInfoDriver.EchoFlush(), and System.TermInfoDriver.ReadKeyInternal().