Terraria Decompiled: System.TermInfoDriver.WriteSpecialKey
WriteSpecialKey() [2/2]
void System.TermInfoDriver.WriteSpecialKey (ConsoleKeyInfo key) inline
Definition at line 224 of file TermInfoDriver.cs.
        {
            switch (key.Key)
            {
            case ConsoleKey.Backspace:
                if (this.cursorLeft > 0 && (this.cursorLeft > this.rl_startx || this.cursorTop != this.rl_starty))
                {
                    this.cursorLeft--;
                    this.SetCursorPosition(this.cursorLeft, this.cursorTop);
                    this.WriteConsole(" ");
                    this.SetCursorPosition(this.cursorLeft, this.cursorTop);
                    return;
                }
                break;
            case ConsoleKey.Tab:
            {
                int num = 8 - this.cursorLeft % 8;
                for (int i = 0; i < num; i++)
                {
                    this.IncrementX();
                }
                this.WriteConsole("\t");
                return;
            }
            case (ConsoleKey)10:
            case (ConsoleKey)11:
            case ConsoleKey.Enter:
                break;
            case ConsoleKey.Clear:
                this.WriteConsole(this.clear);
                this.cursorLeft = 0;
                this.cursorTop = 0;
                break;
            default:
                return;
            }
        }
References System.TermInfoDriver.clear, System.TermInfoDriver.cursorLeft, System.TermInfoDriver.cursorTop, System.TermInfoDriver.IncrementX(), System.key, System.TermInfoDriver.rl_startx, System.TermInfoDriver.rl_starty, System.TermInfoDriver.SetCursorPosition(), and System.TermInfoDriver.WriteConsole().
Referenced by System.TermInfoDriver.Echo(), System.IO.CStreamWriter.Write(), System.IO.CStreamWriter.Write(), and System.TermInfoDriver.WriteSpecialKey().