Terraria Decompiled: System.TermInfoDriver.Echo
Echo()
void System.TermInfoDriver.Echo (ConsoleKeyInfo key) inline private
Definition at line 1101 of file TermInfoDriver.cs.
        {
            if (!this.IsSpecialKey(key))
            {
                this.QueueEcho(key.KeyChar);
                return;
            }
            this.EchoFlush();
            this.WriteSpecialKey(key);
        }
References System.TermInfoDriver.EchoFlush(), System.TermInfoDriver.IsSpecialKey(), System.ConsoleKeyInfo.KeyChar, System.TermInfoDriver.QueueEcho(), and System.TermInfoDriver.WriteSpecialKey().
Referenced by System.TermInfoDriver.Read(), System.TermInfoDriver.ReadKey(), and System.TermInfoDriver.ReadUntilConditionInternal().