Terraria Decompiled: System.TermInfoDriver.ReadKeyInternal
ReadKeyInternal()
ConsoleKeyInfo System.TermInfoDriver.ReadKeyInternal (out bool fresh) inline private
Definition at line 1028 of file TermInfoDriver.cs.
        {
            if (!this.inited)
            {
                this.Init();
            }
            this.InitKeys();
            object obj;
            if ((obj = this.GetKeyFromBuffer(true)) == null)
            {
                do
                {
                    if (ConsoleDriver.InternalKeyAvailable(150) > 0)
                    {
                        do
{
                            this.AddToBuffer(this.stdin.Read());
                        }
                        while (ConsoleDriver.InternalKeyAvailable(0) > 0);
                    }
                    else if (this.stdin.DataAvailable())
                    {
                        do
{
                            this.AddToBuffer(this.stdin.Read());
                        }
                        while (this.stdin.DataAvailable());
                    }
                    else
                    {
                        if ((obj = this.GetKeyFromBuffer(false)) != null)
{
                            break;
                        }
                        this.AddToBuffer(this.stdin.Read());
                    }
                    obj = this.GetKeyFromBuffer(true);
                }
                while (obj == null);
                fresh = true;
            }
            else
            {
                fresh = false;
            }
            return (ConsoleKeyInfo)obj;
        }
References System.TermInfoDriver.AddToBuffer(), System.IO.StreamReader.DataAvailable(), System.TermInfoDriver.GetKeyFromBuffer(), System.TermInfoDriver.Init(), System.TermInfoDriver.inited, System.TermInfoDriver.InitKeys(), System.ConsoleDriver.InternalKeyAvailable(), System.obj, System.IO.StreamReader.Read(), and System.TermInfoDriver.stdin.
Referenced by System.TermInfoDriver.Read(), System.TermInfoDriver.ReadKey(), and System.TermInfoDriver.ReadUntilConditionInternal().