Terraria Decompiled: System.TermInfoDriver.GetCursorPosition
GetCursorPosition()
void System.TermInfoDriver.GetCursorPosition () inline private
Definition at line 366 of file TermInfoDriver.cs.
        {
            int num = 0;
            int num2 = 0;
            int num3 = ConsoleDriver.InternalKeyAvailable(0);
            int num4;
            while (num3-- > 0)
            {
                num4 = this.stdin.Read();
                this.AddToBuffer(num4);
            }
            this.WriteConsole("\u001b[6n");
            if (ConsoleDriver.InternalKeyAvailable(1000) <= 0)
            {
                this.noGetPosition = true;
                return;
            }
            for (num4 = this.stdin.Read(); num4 != 27; num4 = this.stdin.Read())
            {
                this.AddToBuffer(num4);
                if (ConsoleDriver.InternalKeyAvailable(100) <= 0)
                {
                    return;
                }
            }
            num4 = this.stdin.Read();
            if (num4 != 91)
            {
                this.AddToBuffer(27);
                this.AddToBuffer(num4);
                return;
            }
            num4 = this.stdin.Read();
            if (num4 != 59)
            {
                num = num4 - 48;
                num4 = this.stdin.Read();
                while (num4 >= 48 && num4 <= 57)
                {
                    num = num * 10 + num4 - 48;
                    num4 = this.stdin.Read();
                }
                num--;
            }
            num4 = this.stdin.Read();
            if (num4 != 82)
            {
                num2 = num4 - 48;
                num4 = this.stdin.Read();
                while (num4 >= 48 && num4 <= 57)
                {
                    num2 = num2 * 10 + num4 - 48;
                    num4 = this.stdin.Read();
                }
                num2--;
            }
            this.cursorLeft = num2;
            this.cursorTop = num;
        }
References System.TermInfoDriver.AddToBuffer(), System.ConsoleDriver.InternalKeyAvailable(), System.IO.StreamReader.Read(), System.TermInfoDriver.stdin, and System.TermInfoDriver.WriteConsole().
Referenced by System.TermInfoDriver.Init(), and System.TermInfoDriver.ReadUntilConditionInternal().