Terraria Decompiled: System.TermInfoDriver.GetKeyFromBuffer
GetKeyFromBuffer()
object System.TermInfoDriver.GetKeyFromBuffer (bool cooked) inline private
Definition at line 983 of file TermInfoDriver.cs.
        {
            if (this.readpos >= this.writepos)
            {
                return null;
            }
            int num = (int)this.buffer[this.readpos];
            if (!cooked || !this.rootmap.StartsWith(num))
            {
                this.readpos++;
                this.AdjustBuffer();
                return this.CreateKeyInfoFromInt(num, false);
            }
            int num2;
            TermInfoStrings termInfoStrings = this.rootmap.Match(this.buffer, this.readpos, this.writepos - this.readpos, out num2);
            if (termInfoStrings == (TermInfoStrings)(-1))
            {
                if (this.buffer[this.readpos] != '\u001b' || this.writepos - this.readpos < 2)
                {
                    return null;
                }
                this.readpos += 2;
                this.AdjustBuffer();
                if (this.buffer[this.readpos + 1] == '\u007f')
                {
                    return new ConsoleKeyInfo('\b', ConsoleKey.Backspace, false, true, false);
                }
                return this.CreateKeyInfoFromInt((int)this.buffer[this.readpos + 1], true);
            }
            else
            {
                if (this.keymap[termInfoStrings] != null)
                {
                    ConsoleKeyInfo consoleKeyInfo = (ConsoleKeyInfo)this.keymap[termInfoStrings];
                    this.readpos += num2;
                    this.AdjustBuffer();
                    return consoleKeyInfo;
                }
                this.readpos++;
                this.AdjustBuffer();
                return this.CreateKeyInfoFromInt(num, false);
            }
        }
References System.TermInfoDriver.AdjustBuffer(), System.TermInfoDriver.buffer, System.TermInfoDriver.CreateKeyInfoFromInt(), int, System.TermInfoDriver.keymap, System.ByteMatcher.Match(), System.TermInfoDriver.readpos, System.TermInfoDriver.rootmap, System.ByteMatcher.StartsWith(), and System.TermInfoDriver.writepos.
Referenced by System.TermInfoDriver.Read(), and System.TermInfoDriver.ReadKeyInternal().