Terraria Decompiled: System.TermInfoDriver.ReadUntilConditionInternal
ReadUntilConditionInternal()
string System.TermInfoDriver.ReadUntilConditionInternal (bool haltOnNewLine) inline private
Definition at line 1230 of file TermInfoDriver.cs.
        {
            if (!this.inited)
            {
                this.Init();
            }
            this.GetCursorPosition();
            StringBuilder stringBuilder = new StringBuilder();
            bool flag = false;
            this.rl_startx = this.cursorLeft;
            this.rl_starty = this.cursorTop;
            char c = (char)this.control_characters[4];
            for (;;)
            {
                bool flag2;
                ConsoleKeyInfo consoleKeyInfo = this.ReadKeyInternal(out flag2);
                flag = flag || flag2;
                char keyChar = consoleKeyInfo.KeyChar;
                if (keyChar == c && keyChar != '\0' && stringBuilder.Length == 0)
                {
                    break;
                }
                bool flag3 = haltOnNewLine && consoleKeyInfo.Key == ConsoleKey.Enter;
                if (flag3)
                {
                    goto IL_00AC;
                }
                if (consoleKeyInfo.Key != ConsoleKey.Backspace)
                {
                    stringBuilder.Append(keyChar);
                    goto IL_00AC;
                }
                if (stringBuilder.Length > 0)
                {
                    StringBuilder stringBuilder2 = stringBuilder;
                    int length = stringBuilder2.Length;
                    stringBuilder2.Length = length - 1;
                    goto IL_00AC;
                }
                IL_00B6:
                if (flag3)
                {
                    goto Block_10;
                }
                continue;
                IL_00AC:
                if (flag)
                {
                    this.Echo(consoleKeyInfo);
                    goto IL_00B6;
                }
                goto IL_00B6;
            }
            return null;
            Block_10:
            this.EchoFlush();
            this.rl_startx = -1;
            this.rl_starty = -1;
            return stringBuilder.ToString();
        }
References System.Text.StringBuilder.Append(), System.TermInfoDriver.control_characters, System.TermInfoDriver.cursorLeft, System.TermInfoDriver.cursorTop, System.TermInfoDriver.Echo(), System.TermInfoDriver.EchoFlush(), System.TermInfoDriver.GetCursorPosition(), System.TermInfoDriver.Init(), System.TermInfoDriver.inited, System.ConsoleKeyInfo.Key, System.ConsoleKeyInfo.KeyChar, System.length, System.Text.StringBuilder.Length, System.TermInfoDriver.ReadKeyInternal(), and System.Text.StringBuilder.ToString().
Referenced by System.TermInfoDriver.ReadLine(), and System.TermInfoDriver.ReadToEnd().