Terraria Decompiled: System.Runtime.Remoting.Messaging.StackBuilderSink.ExecuteAsyncMessage
ExecuteAsyncMessage()
void System.Runtime.Remoting.Messaging.StackBuilderSink.ExecuteAsyncMessage (object ob) inline private
Definition at line 51 of file StackBuilderSink.cs.
        {
            object[] array = (object[])ob;
            IMethodCallMessage methodCallMessage = (IMethodCallMessage)array[0];
            IMessageSink messageSink = (IMessageSink)array[1];
            this.CheckParameters(methodCallMessage);
            IMessage message;
            if (this._rp != null)
            {
                message = this._rp.Invoke(methodCallMessage);
            }
            else
            {
                message = RemotingServices.InternalExecuteMessage(this._target, methodCallMessage);
            }
            messageSink.SyncProcessMessage(message);
        }
References System.Runtime.Remoting.Messaging.StackBuilderSink._rp, System.Runtime.Remoting.Messaging.StackBuilderSink._target, System.array, System.Runtime.Remoting.Messaging.StackBuilderSink.CheckParameters(), System.Runtime.Remoting.RemotingServices.InternalExecuteMessage(), System.Runtime.Remoting.Proxies.RealProxy.Invoke(), and System.Runtime.Remoting.Messaging.IMessageSink.SyncProcessMessage().
Referenced by System.Runtime.Remoting.Messaging.StackBuilderSink.AsyncProcessMessage(), and System.Runtime.Remoting.Messaging.StackBuilderSink.b__4_0().