Terraria Decompiled: System.Runtime.Remoting.Messaging.StackBuilderSink.CheckParameters
CheckParameters()
void System.Runtime.Remoting.Messaging.StackBuilderSink.CheckParameters (IMessage msg) inline private
Definition at line 80 of file StackBuilderSink.cs.
        {
            IMethodCallMessage methodCallMessage = (IMethodCallMessage)msg;
            ParameterInfo[] parameters = methodCallMessage.MethodBase.GetParameters();
            int num = 0;
            foreach (ParameterInfo parameterInfo in parameters)
            {
                object arg = methodCallMessage.GetArg(num++);
                Type type = parameterInfo.ParameterType;
                if (type.IsByRef)
                {
                    type = type.GetElementType();
                }
                if (arg != null && !type.IsInstanceOfType(arg))
                {
                    throw new RemotingException(string.Concat(new string[]
                    {
                        "Cannot cast argument ",
                        parameterInfo.Position.ToString(),
                        " of type '",
                        arg.GetType().AssemblyQualifiedName,
                        "' to type '",
                        type.AssemblyQualifiedName,
                        "'"
                    }));
                }
            }
        }
References System.Type.AssemblyQualifiedName, System.Type.GetElementType(), System.Reflection.MethodBase.GetParameters(), System.Type.IsByRef, System.Type.IsInstanceOfType(), System.Runtime.Remoting.Messaging.IMethodMessage.MethodBase, System.Reflection.ParameterInfo.ParameterType, and System.Reflection.ParameterInfo.Position.
Referenced by System.Runtime.Remoting.Messaging.StackBuilderSink.ExecuteAsyncMessage(), and System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage().