Terraria Decompiled: System.Text.ValueStringBuilder.Grow
Grow()
void System.Text.ValueStringBuilder.Grow (int requiredAdditionalCapacity) inline private
Definition at line 251 of file ValueStringBuilder.cs.
        {
            char[] array = ArrayPool<char>.Shared.Rent(Math.Max(this._pos + requiredAdditionalCapacity, this._chars.Length * 2));
            this._chars.CopyTo(array);
            char[] arrayToReturnToPool = this._arrayToReturnToPool;
            this._chars = (this._arrayToReturnToPool = array);
            if (arrayToReturnToPool != null)
            {
                ArrayPool<char>.Shared.Return(arrayToReturnToPool, false);
            }
        }
References System.Text.ValueStringBuilder._arrayToReturnToPool, System.Text.ValueStringBuilder._chars, System.array, System.Span< T >.CopyTo(), System.Math.Max(), and System.Buffers.ArrayPool< T >.Shared.
Referenced by System.Text.ValueStringBuilder.Append(), System.Text.ValueStringBuilder.Append(), System.Text.ValueStringBuilder.Append(), System.Text.ValueStringBuilder.AppendSlow(), System.Text.ValueStringBuilder.AppendSpan(), System.Text.ValueStringBuilder.EnsureCapacity(), System.Text.ValueStringBuilder.GrowAndAppend(), and System.Text.ValueStringBuilder.Insert().