Terraria Decompiled: System.Text.ValueStringBuilder.ToString
ToString()
override string System.Text.ValueStringBuilder.ToString () inline
Definition at line 74 of file ValueStringBuilder.cs.
        {
            string text = new string(this._chars.Slice(0, this._pos));
            this.Dispose();
            return text;
        }
References System.Text.ValueStringBuilder._chars, System.Text.ValueStringBuilder.Dispose(), System.Span< T >.Slice(), and System.text.
Referenced by System.Number.FormatDouble(), System.Number.FormatSingle(), System.IO.PathInternal.RemoveRelativeSegments(), and System.IO.Enumeration.FileSystemName.TranslateWin32Expression().