Terraria Decompiled: Terraria.GameContent.ExtraSpawnPointManager.GenerateExtraSpawns_TryFindSpawnAt
GenerateExtraSpawns_TryFindSpawnAt()
static bool Terraria.GameContent.ExtraSpawnPointManager.GenerateExtraSpawns_TryFindSpawnAt (List< Point > spawnPoints, ref int spawnX, ref int spawnY, int maxY) inline static private
Definition at line 210 of file ExtraSpawnPointManager.cs.
        {
            spawnY = ExtraSpawnPointManager.GenerateExtraSpawns_IterateDownToFloor(spawnX, spawnY, maxY);
            if (ExtraSpawnPointManager.settings.remix && ExtraSpawnPointManager.settings.skyblock)
            {
                spawnY -= 2;
                spawnX -= 10;
                spawnX += WorldGen.genRand.Next(21);
                return true;
            }
            int num = 50;
            if (ExtraSpawnPointManager.settings.skyblock)
            {
                num = 15;
            }
            if (ExtraSpawnPointManager.settings.extraLiquid)
            {
                num = 30;
            }
            bool flag = false;
            int num2 = Math.Max(0, spawnX - num);
            int num3 = num;
            int num4 = Math.Max(0, spawnY - num);
            int num5 = num;
            int[] tilesToAvoidForSpawn_TeamBasedSpawns = WorldGen.GetTilesToAvoidForSpawn_TeamBasedSpawns();
            int num6 = 50;
            int num7 = 100;
            Func<Tile, int, int, bool> func = delegate(Tile tile, int x, int y)
            {
                Point point = new Point(x, y);
                int num8 = 250;
                if (ExtraSpawnPointManager.settings.extraLiquid && tile.type == 379)
                {
                    return false;
                }
                if (ExtraSpawnPointManager.settings.skyblock && tile.type != 0)
                {
                    return false;
                }
                if (ExtraSpawnPointManager.settings.remix)
                {
                    if (WorldGen.GetWorldSize() == 0)
                    {
                        num8 = 150;
                    }
                    if (!ExtraSpawnPointManager.settings.skyblock && (y < GenVars.remixSurfaceLayerLow || y > GenVars.remixMushroomLayerHigh))
                    {
                        return false;
                    }
                    if (ExtraSpawnPointManager.settings.skyblock && y < Main.UnderworldLayer)
                    {
                        return false;
                    }
                }
                if (ExtraSpawnPointManager.settings.roundLandmass && WorldGen.GetWorldSize() == 0)
                {
                    num8 = 150;
                }
                for (int i = 0; i < spawnPoints.Count; i++)
                {
                    Point point2 = spawnPoints[i];
                    int num9 = Math.Abs(point2.X - point.X);
                    int num10 = Math.Abs(point2.Y - point.Y);
                    if (num9 < num8 && num10 < num8)
                    {
                        return false;
                    }
                }
                return true;
            };
            Vector2 vector = Utils.CheckForGoodTeleportationSpot(ref flag, num2, num3, num4, num5, new Utils.RandomTeleportationAttemptSettings
            {
                teleporteeSize = new Vector2(20f, 42f),
                teleporteeVelocity = Vector2.Zero,
                teleporteeGravityDirection = 1f,
                avoidLava = true,
                avoidAnyLiquid = true,
                avoidHurtTiles = true,
                avoidWalls = true,
                mostlySolidFloor = true,
                strictRange = true,
                maximumFallDistanceFromOrignalPoint = num7,
                attemptsBeforeGivingUp = 250,
                tilesToAvoid = tilesToAvoidForSpawn_TeamBasedSpawns,
                tilesToAvoidRange = num6,
                specializedConditions = func
            });
            if (flag)
            {
                spawnX = (int)(vector.X / 16f);
                spawnY = (int)(vector.Y / 16f);
                return true;
            }
            return false;
        }
References System.Math.Abs(), Terraria.Utils.CheckForGoodTeleportationSpot(), System.Collections.Generic.List< T >.Count, Terraria.GameContent.ExtraSpawnSettings.extraLiquid, Terraria.GameContent.ExtraSpawnPointManager.GenerateExtraSpawns_IterateDownToFloor(), Terraria.WorldGen.genRand, Terraria.WorldGen.GetTilesToAvoidForSpawn_TeamBasedSpawns(), Terraria.WorldGen.GetWorldSize(), int, System.Math.Max(), Terraria.GameContent.ExtraSpawnSettings.remix, Terraria.WorldBuilding.GenVars.remixMushroomLayerHigh, Terraria.GameContent.ExtraSpawnSettings.roundLandmass, Terraria.GameContent.ExtraSpawnPointManager.settings, Terraria.GameContent.ExtraSpawnSettings.skyblock, Terraria.Tile.type, Terraria.Main.UnderworldLayer, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Point.Y, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.GameContent.ExtraSpawnPointManager.GenerateExtraSpawns_TryFindSpawnRandomly().