Terraria Decompiled: Terraria.GameContent.ExtraSpawnPointManager.GenerateExtraSpawns_Setup
GenerateExtraSpawns_Setup()
static void Terraria.GameContent.ExtraSpawnPointManager.GenerateExtraSpawns_Setup () inline static
Definition at line 38 of file ExtraSpawnPointManager.cs.
        {
            if (ExtraSpawnPointManager.settings.skyblock)
            {
                ExtraSpawnPointManager._listOfLandmasses.Clear();
                for (int i = 0; i < GenVars.landmassData.Count; i++)
                {
                    LandmassData landmassData = GenVars.landmassData[i];
                    if (landmassData.DataType == LandmassDataType.SkyblockIsland || landmassData.Style == 13)
                    {
                        ExtraSpawnPointManager._listOfLandmasses.Add(landmassData);
                    }
                }
                return;
            }
            if (ExtraSpawnPointManager.settings.roundLandmass)
            {
                ExtraSpawnPointManager._listOfLandmasses.Clear();
                for (int j = 0; j < GenVars.landmassData.Count; j++)
                {
                    LandmassData landmassData2 = GenVars.landmassData[j];
                    if (landmassData2.DataType == LandmassDataType.RoundLandmass && landmassData2.Position.Distance(new Vector2((float)Main.spawnTileX, (float)Main.spawnTileY)) >= 300f)
                    {
                        ExtraSpawnPointManager._listOfLandmasses.Add(landmassData2);
                    }
                }
                return;
            }
            if (ExtraSpawnPointManager.settings.extraLiquid)
            {
                ExtraSpawnPointManager._listOfLandmasses.Clear();
                for (int k = 0; k < GenVars.landmassData.Count; k++)
                {
                    LandmassData landmassData3 = GenVars.landmassData[k];
                    if (landmassData3.DataType == LandmassDataType.ExtraLiquidBubbleSquare && landmassData3.Position.Distance(new Vector2((float)Main.spawnTileX, (float)Main.spawnTileY)) >= 300f)
                    {
                        ExtraSpawnPointManager._listOfLandmasses.Add(landmassData3);
                    }
                }
            }
        }
References Terraria.GameContent.ExtraSpawnPointManager._listOfLandmasses, System.Collections.Generic.List< T >.Add(), System.Collections.Generic.List< T >.Clear(), System.Collections.Generic.List< T >.Count, Terraria.WorldBuilding.LandmassData.DataType, Microsoft.Xna.Framework.Vector2.Distance(), Terraria.GameContent.ExtraSpawnSettings.extraLiquid, Terraria.WorldBuilding.GenVars.landmassData, Terraria.WorldBuilding.LandmassData.Position, Terraria.GameContent.ExtraSpawnSettings.roundLandmass, Terraria.GameContent.ExtraSpawnPointManager.settings, Terraria.GameContent.ExtraSpawnSettings.skyblock, Terraria.Main.spawnTileX, Terraria.Main.spawnTileY, and Terraria.WorldBuilding.LandmassData.Style.
Referenced by Terraria.GameContent.ExtraSpawnPointManager.GenerateExtraSpawns(), and Terraria.GameContent.ExtraSpawnPointManager.PrepareExtraSpawns().