Terraria Decompiled: Terraria.GameContent.ExtraSpawnPointManager.GenerateExtraSpawns
GenerateExtraSpawns()
static void Terraria.GameContent.ExtraSpawnPointManager.GenerateExtraSpawns () inline static
Definition at line 89 of file ExtraSpawnPointManager.cs.
        {
            ExtraSpawnPointManager.GenerateExtraSpawns_Setup();
            ExtraSpawnType spawnType = ExtraSpawnPointManager.settings.spawnType;
            if (spawnType == ExtraSpawnType.None || spawnType != ExtraSpawnType.TeamBased)
            {
                ExtraSpawnPointManager.extraSpawnPoints = new Point[0];
                return;
            }
            ExtraSpawnPointManager.extraSpawnPoints = new Point[(int)PlayerTeamID.Count];
            ExtraSpawnPointManager.extraSpawnPoints[0] = new Point(Main.spawnTileX, Main.spawnTileY);
            List<Point> list = new List<Point>();
            for (int i = 1; i < (int)PlayerTeamID.Count; i++)
            {
                ExtraSpawnPointManager.GenerateExtraSpawns_TryFindSpawnRandomly(list, ExtraSpawnPointManager.GenerateExtraSpawns_GetFallbackSpawn(i, (int)PlayerTeamID.Count));
            }
            for (int j = 1; j < (int)PlayerTeamID.Count; j++)
            {
                Point point = list[WorldGen.genRand.Next(list.Count)];
                ExtraSpawnPointManager.extraSpawnPoints[j] = point;
                list.Remove(point);
            }
        }
References Terraria.ID.PlayerTeamID.Count, Terraria.GameContent.ExtraSpawnPointManager.extraSpawnPoints, Terraria.GameContent.ExtraSpawnPointManager.GenerateExtraSpawns_GetFallbackSpawn(), Terraria.GameContent.ExtraSpawnPointManager.GenerateExtraSpawns_Setup(), Terraria.GameContent.ExtraSpawnPointManager.GenerateExtraSpawns_TryFindSpawnRandomly(), Terraria.WorldGen.genRand, int, System.list, Terraria.GameContent.ExtraSpawnPointManager.settings, Terraria.Main.spawnTileX, Terraria.Main.spawnTileY, and Terraria.GameContent.ExtraSpawnSettings.spawnType.
Referenced by Terraria.WorldGen.SecretSeed.FinalizeSecretSeeds().