Terraria Decompiled: Terraria.GameContent.ExtraSpawnPointManager.GenerateExtraSpawns_TryFindSpawnRandomly
GenerateExtraSpawns_TryFindSpawnRandomly()
static bool Terraria.GameContent.ExtraSpawnPointManager.GenerateExtraSpawns_TryFindSpawnRandomly (List< Point > spawnPoints, Point fallbackSpawn) inline static private
Definition at line 114 of file ExtraSpawnPointManager.cs.
        {
            int num = 500;
            int num2 = 60;
            int num3 = 60;
            bool flag = true;
            LandmassData landmassData = default(LandmassData);
            for (int i = 0; i < num; i++)
            {
                int num4 = 0;
                int num5 = 0;
                int num6 = (int)Main.worldSurface;
                if (flag)
                {
                    num4 = WorldGen.genRand.Next(num2, Main.maxTilesX / 2);
                }
                else
                {
                    num4 = WorldGen.genRand.Next(Main.maxTilesX / 2, Main.maxTilesX - num2);
                }
                if (!ExtraSpawnPointManager.settings.surface)
                {
                    num6 = Main.UnderworldLayer - 50 - num3;
                    num5 = WorldGen.genRand.Next((int)Main.worldSurface + 200 + num3, num6);
                }
                if (ExtraSpawnPointManager.settings.remix)
                {
                    num6 = GenVars.remixMushroomLayerHigh - num3;
                    num5 = GenVars.remixSurfaceLayerLow + 50 + num3;
                }
                if (ExtraSpawnPointManager.settings.skyblock)
                {
                    LandmassData landmassData2 = default(LandmassData);
                    int j = 500;
                    while (j > 0)
                    {
                        j--;
                        if (ExtraSpawnPointManager._listOfLandmasses.Count <= 0)
{
                            break;
                        }
                        landmassData2 = ExtraSpawnPointManager._listOfLandmasses[WorldGen.genRand.Next(ExtraSpawnPointManager._listOfLandmasses.Count)];
                        if ((!ExtraSpawnPointManager.settings.surface || (double)landmassData2.Position.Y <= Main.worldSurface) && (!ExtraSpawnPointManager.settings.remix || (landmassData2.DataType == LandmassDataType.SkyblockIsland && landmassData2.Style == 13)))
{
                            break;
                        }
                    }
                    num4 = (int)MathHelper.Clamp(landmassData2.Top.X, (float)num2, (float)(Main.maxTilesX - num2));
                    num5 = (int)MathHelper.Clamp(landmassData2.Top.Y, (float)num3, (float)(Main.maxTilesY - num3));
                    num6 = (int)MathHelper.Clamp((float)(num5 + landmassData2.RadiusOrHalfSize), (float)num3, (float)(Main.maxTilesY - num3));
                    landmassData = landmassData2;
                }
                else if (ExtraSpawnPointManager.settings.roundLandmass || ExtraSpawnPointManager.settings.extraLiquid)
                {
                    LandmassData landmassData3 = default(LandmassData);
                    Vector2 vector = Vector2.Zero;
                    int k = 500;
                    while (k > 0)
                    {
                        k--;
                        if (ExtraSpawnPointManager._listOfLandmasses.Count <= 0)
{
                            break;
                        }
                        landmassData3 = ExtraSpawnPointManager._listOfLandmasses[WorldGen.genRand.Next(ExtraSpawnPointManager._listOfLandmasses.Count)];
                        vector = landmassData3.Position;
                        if (ExtraSpawnPointManager.settings.roundLandmass)
{
                            vector = landmassData3.Top;
                        }
                        if ((!ExtraSpawnPointManager.settings.surface || (double)vector.Y <= Main.worldSurface) && (!ExtraSpawnPointManager.settings.remix || (vector.Y >= (float)GenVars.remixSurfaceLayerLow && vector.Y <= (float)GenVars.remixMushroomLayerHigh)) && (!ExtraSpawnPointManager.settings.roundLandmass || k <= 250 || landmassData3.RadiusOrHalfSize >= 40) && (!ExtraSpawnPointManager.settings.extraLiquid || k <= 250 || landmassData3.RadiusOrHalfSize >= 10))
{
                            break;
                        }
                    }
                    num4 = (int)MathHelper.Clamp(vector.X, (float)num2, (float)(Main.maxTilesX - num2));
                    num5 = (int)MathHelper.Clamp(vector.Y, (float)num3, (float)(Main.maxTilesY - num3));
                    num6 = Main.maxTilesY - 50;
                    landmassData = landmassData3;
                }
                flag = !flag;
                if (ExtraSpawnPointManager.GenerateExtraSpawns_TryFindSpawnAt(spawnPoints, ref num4, ref num5, num6))
                {
                    spawnPoints.Add(new Point(num4, num5));
                    if (!landmassData.Equals(default(LandmassData)))
                    {
                        ExtraSpawnPointManager._listOfLandmasses.Remove(landmassData);
                    }
                    return true;
                }
            }
            spawnPoints.Add(fallbackSpawn);
            return false;
        }
References Terraria.GameContent.ExtraSpawnPointManager._listOfLandmasses, System.Collections.Generic.List< T >.Add(), Microsoft.Xna.Framework.MathHelper.Clamp(), System.Collections.Generic.List< T >.Count, Terraria.WorldBuilding.LandmassData.DataType, Terraria.GameContent.ExtraSpawnSettings.extraLiquid, Terraria.GameContent.ExtraSpawnPointManager.GenerateExtraSpawns_TryFindSpawnAt(), Terraria.WorldGen.genRand, int, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.WorldBuilding.LandmassData.Position, Terraria.WorldBuilding.LandmassData.RadiusOrHalfSize, Terraria.GameContent.ExtraSpawnSettings.remix, Terraria.WorldBuilding.GenVars.remixMushroomLayerHigh, System.Collections.Generic.List< T >.Remove(), Terraria.GameContent.ExtraSpawnSettings.roundLandmass, Terraria.GameContent.ExtraSpawnPointManager.settings, Terraria.GameContent.ExtraSpawnSettings.skyblock, Terraria.WorldBuilding.LandmassData.Style, Terraria.GameContent.ExtraSpawnSettings.surface, Terraria.WorldBuilding.LandmassData.Top, Terraria.Main.worldSurface, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.ExtraSpawnPointManager.GenerateExtraSpawns().