Terraria Decompiled: Terraria.GameContent.ExtraSpawnPointManager.GenerateExtraSpawns_IterateDownToFloor
GenerateExtraSpawns_IterateDownToFloor()
static int Terraria.GameContent.ExtraSpawnPointManager.GenerateExtraSpawns_IterateDownToFloor (int spawnX, int spawnY, int maxY) inline static private
Definition at line 356 of file ExtraSpawnPointManager.cs.
        {
            if (spawnY > Main.maxTilesY - 5)
            {
                spawnY = Main.maxTilesY - 5;
            }
            else if (spawnY < 5)
            {
                spawnY = 5;
            }
            if (maxY <= spawnY)
            {
                return spawnY;
            }
            bool extraLiquid = ExtraSpawnPointManager.settings.extraLiquid;
            int num = spawnY;
            while (num < maxY && num < Main.maxTilesY)
            {
                Tile tile = Main.tile[spawnX, num];
                if (tile.active() && (extraLiquid || tile.liquid <= 0) && (tile.type < 0 || Main.tileSolid[(int)tile.type]) && (!ExtraSpawnPointManager.settings.remix || (tile.type != 195 && tile.type != 474)))
                {
                    return num;
                }
                num++;
            }
            return spawnY;
        }
References Terraria.Tile.active(), Terraria.GameContent.ExtraSpawnSettings.extraLiquid, Terraria.Tile.liquid, Terraria.Main.maxTilesY, Terraria.GameContent.ExtraSpawnSettings.remix, Terraria.GameContent.ExtraSpawnPointManager.settings, Terraria.Main.tile, Terraria.Main.tileSolid, and Terraria.Tile.type.
Referenced by Terraria.GameContent.ExtraSpawnPointManager.GenerateExtraSpawns_GetFallbackSpawn(), and Terraria.GameContent.ExtraSpawnPointManager.GenerateExtraSpawns_TryFindSpawnAt().