Terraria Decompiled: Terraria.GameContent.ExtraSpawnPointManager.GenerateExtraSpawns_GetFallbackSpawn
GenerateExtraSpawns_GetFallbackSpawn()
static Point Terraria.GameContent.ExtraSpawnPointManager.GenerateExtraSpawns_GetFallbackSpawn (int iteration, int iterationMax) inline static private
Definition at line 307 of file ExtraSpawnPointManager.cs.
        {
            float num = ExtraSpawnPointManager.GenerateExtraSpawns_WorldPercentileAvoidWorldSpawnIfNeeded((float)iteration / (float)iterationMax);
            int num2 = (int)((float)Main.maxTilesX * num);
            int num3 = 0;
            double worldSurface = Main.worldSurface;
            if (!ExtraSpawnPointManager.settings.surface)
            {
                num3 = (int)((float)Main.maxTilesY * 0.5f);
                int underworldLayer = Main.UnderworldLayer;
            }
            if (ExtraSpawnPointManager.settings.roundLandmass)
            {
                if (ExtraSpawnPointManager.settings.surface)
                {
                    num3 = 0;
                    double worldSurface2 = Main.worldSurface;
                }
                else
                {
                    num3 = (int)Main.worldSurface + 100;
                    int underworldLayer2 = Main.UnderworldLayer;
                }
            }
            if (ExtraSpawnPointManager.settings.remix)
            {
                num3 = (int)MathHelper.Lerp((float)GenVars.remixSurfaceLayerLow, (float)GenVars.remixMushroomLayerHigh, 0.5f);
                int remixMushroomLayerHigh = GenVars.remixMushroomLayerHigh;
            }
            num3 = ExtraSpawnPointManager.GenerateExtraSpawns_IterateDownToFloor(num2, num3, (int)Main.worldSurface);
            return new Point(num2, num3);
        }
References Terraria.GameContent.ExtraSpawnPointManager.GenerateExtraSpawns_IterateDownToFloor(), Terraria.GameContent.ExtraSpawnPointManager.GenerateExtraSpawns_WorldPercentileAvoidWorldSpawnIfNeeded(), int, Microsoft.Xna.Framework.MathHelper.Lerp(), Terraria.GameContent.ExtraSpawnSettings.remix, Terraria.WorldBuilding.GenVars.remixMushroomLayerHigh, Terraria.WorldBuilding.GenVars.remixSurfaceLayerLow, Terraria.GameContent.ExtraSpawnSettings.roundLandmass, Terraria.GameContent.ExtraSpawnPointManager.settings, Terraria.GameContent.ExtraSpawnSettings.surface, Terraria.Main.UnderworldLayer, and Terraria.Main.worldSurface.
Referenced by Terraria.GameContent.ExtraSpawnPointManager.GenerateExtraSpawns().