Terraria Decompiled: Terraria.Gore.Update
Update()
void Terraria.Gore.Update () inline
Definition at line 306 of file Gore.cs.
        {
            if (Main.netMode == 2)
            {
                return;
            }
            if (this.active)
            {
                if (this.sticky)
                {
                    if (this.DeactivateIfOutsideOfWorld())
                    {
                        return;
                    }
                    float num = this.velocity.Length();
                    if (num > 32f)
                    {
                        this.velocity *= 32f / num;
                    }
                }
                int num2 = GoreID.Sets.SpecialAI[this.type];
                if (num2 == 4)
                {
                    this.UpdateAmbientFloorCloud();
                    return;
                }
                if (num2 == 5)
                {
                    this.UpdateAmbientAirborneCloud();
                    return;
                }
                if (num2 == 6)
                {
                    this.UpdateFogMachineCloud();
                    return;
                }
                if (num2 == 7)
                {
                    this.UpdateLightningBunnySparks();
                    return;
                }
                if ((this.type == 1217 || this.type == 1218) && this.frameCounter == 0)
                {
                    this.frameCounter = 1;
                    this.Frame.CurrentRow = (byte)Main.rand.Next(3);
                }
                bool flag = this.type >= 1024 && this.type <= 1026;
                if (this.type >= 276 && this.type <= 282)
                {
                    this.velocity.X = this.velocity.X * 0.98f;
                    this.velocity.Y = this.velocity.Y * 0.98f;
                    if (this.velocity.Y < this.scale)
                    {
                        this.velocity.Y = this.velocity.Y + 0.05f;
                    }
                    if ((double)this.velocity.Y > 0.1)
                    {
                        if (this.velocity.X > 0f)
{
                            this.rotation += 0.01f;
                        }
                        else
{
                            this.rotation -= 0.01f;
                        }
                    }
                }
                if (this.type >= 570 && this.type <= 572)
                {
                    this.scale -= 0.001f;
                    if ((double)this.scale <= 0.01)
                    {
                        this.scale = 0.01f;
                        this.timeLeft = 0;
                    }
                    this.sticky = false;
                    this.rotation = this.velocity.X * 0.1f;
                }
                else if (this.type >= 0 && this.type < GoreID.Count && GoreID.Sets.IsDrip[this.type])
                {
                    if (this.type == 943 || (this.type >= 1160 && this.type <= 1162))
                    {
                        this.alpha = 0;
                    }
                    else if ((double)this.position.Y < Main.worldSurface * 16.0 + 8.0)
                    {
                        this.alpha = 0;
                    }
                    else
                    {
                        this.alpha = 100;
                    }
                    int num3 = 4;
                    this.frameCounter += 1;
                    if (this.frame <= 4)
                    {
                        int num4 = (int)(this.position.X / 16f);
                        int num5 = (int)(this.position.Y / 16f) - 1;
                        if (WorldGen.InWorld(num4, num5, 0) && !Main.tile[num4, num5].active())
{
                            this.active = false;
                        }
                        if (this.frame == 0)
{
                            num3 = 24 + Main.rand.Next(256);
                        }
                        if (this.frame == 1)
{
                            num3 = 24 + Main.rand.Next(256);
                        }
                        if (this.frame == 2)
{
                            num3 = 24 + Main.rand.Next(256);
                        }
                        if (this.frame == 3)
{
                            num3 = 24 + Main.rand.Next(96);
                        }
                        if (this.frame == 5)
{
                            num3 = 16 + Main.rand.Next(64);
                        }
                        if (this.type == 716)
{
                            num3 *= 2;
                        }
                        if (this.type == 717)
{
                            num3 *= 4;
                        }
                        if ((this.type == 943 || (this.type >= 1160 && this.type <= 1162)) && this.frame < 6)
{
                            num3 = 4;
                        }
                        if ((int)this.frameCounter >= num3)
{
                            this.frameCounter = 0;
                            this.frame += 1;
                            if (this.frame == 5)
{
                                int num6 = Gore.NewGore(this.position, this.velocity, this.type, 1f);
                                Main.gore[num6].frame = 9;
                                Main.gore[num6].velocity *= 0f;
                            }
                        }
                    }
                    else if (this.frame <= 6)
                    {
                        num3 = 8;
                        if (this.type == 716)
{
                            num3 *= 2;
                        }
                        if (this.type == 717)
{
                            num3 *= 3;
                        }
                        if ((int)this.frameCounter >= num3)
{
                            this.frameCounter = 0;
                            this.frame += 1;
                            if (this.frame == 7)
{
                                this.active = false;
                            }
                        }
                    }
                    else if (this.frame <= 9)
                    {
                        num3 = 6;
                        if (this.type == 716)
{
                            num3 = (int)((double)num3 * 1.5);
                            this.velocity.Y = this.velocity.Y + 0.175f;
                        }
                        else if (this.type == 717)
{
                            num3 *= 2;
                            this.velocity.Y = this.velocity.Y + 0.15f;
                        }
                        else if (this.type == 943)
{
                            num3 = (int)((double)num3 * 1.5);
                            this.velocity.Y = this.velocity.Y + 0.2f;
                        }
                        else
{
                            this.velocity.Y = this.velocity.Y + 0.2f;
                        }
                        if ((double)this.velocity.Y < 0.5)
{
                            this.velocity.Y = 0.5f;
                        }
                        if (this.velocity.Y > 12f)
{
                            this.velocity.Y = 12f;
                        }
                        if ((int)this.frameCounter >= num3)
{
                            this.frameCounter = 0;
                            this.frame += 1;
                        }
                        if (this.frame > 9)
{
                            this.frame = 7;
                        }
                    }
                    else
                    {
                        if (this.type == 716)
{
                            num3 *= 2;
                        }
                        else if (this.type == 717)
{
                            num3 *= 6;
                        }
                        this.velocity.Y = this.velocity.Y + 0.1f;
                        if ((int)this.frameCounter >= num3)
{
                            this.frameCounter = 0;
                            this.frame += 1;
                        }
                        this.velocity *= 0f;
                        if (this.frame > 14)
{
                            this.active = false;
                        }
                    }
                }
                else if (this.type == 11 || this.type == 12 || this.type == 13 || this.type == 61 || this.type == 62 || this.type == 63 || this.type == 99 || this.type == 220 || this.type == 221 || this.type == 222 || (this.type >= 375 && this.type <= 377) || (this.type >= 435 && this.type <= 437) || (this.type >= 861 && this.type <= 862))
                {
                    this.velocity.Y = this.velocity.Y * 0.98f;
                    this.velocity.X = this.velocity.X * 0.98f;
                    this.scale -= 0.007f;
                    if ((double)this.scale < 0.1)
                    {
                        this.scale = 0.1f;
                        this.alpha = 255;
                    }
                }
                else if (this.type == 16 || this.type == 17)
                {
                    this.velocity.Y = this.velocity.Y * 0.98f;
                    this.velocity.X = this.velocity.X * 0.98f;
                    this.scale -= 0.01f;
                    if ((double)this.scale < 0.1)
                    {
                        this.scale = 0.1f;
                        this.alpha = 255;
                    }
                }
                else if (this.type == 1201)
                {
                    if (this.frameCounter == 0)
                    {
                        this.frameCounter = 1;
                        this.Frame.CurrentRow = (byte)Main.rand.Next(4);
                    }
                    this.scale -= 0.002f;
                    if ((double)this.scale < 0.1)
                    {
                        this.scale = 0.1f;
                        this.alpha = 255;
                    }
                    this.rotation += this.velocity.X * 0.1f;
                    int num7 = (int)(this.position.X + 6f) / 16;
                    int num8 = (int)(this.position.Y - 6f) / 16;
                    if (Main.tile[num7, num8] == null || Main.tile[num7, num8].liquid <= 0)
                    {
                        this.velocity.Y = this.velocity.Y + 0.2f;
                        if (this.velocity.Y < 0f)
{
                            this.velocity *= 0.92f;
                        }
                    }
                    else
                    {
                        this.velocity.Y = this.velocity.Y + 0.005f;
                        float num9 = this.velocity.Length();
                        if (num9 > 1f)
{
                            this.velocity *= 0.1f;
                        }
                        else if (num9 > 0.1f)
{
                            this.velocity *= 0.98f;
                        }
                    }
                }
                else if (this.type == 1208)
                {
                    if (this.frameCounter == 0)
                    {
                        this.frameCounter = 1;
                        this.Frame.CurrentRow = (byte)Main.rand.Next(4);
                    }
                    Vector2 vector = this.position + new Vector2(this.Width, this.Height) / 2f;
                    int num10 = (int)vector.X / 16;
                    int num11 = (int)vector.Y / 16;
                    bool flag2 = Main.tile[num10, num11] != null && Main.tile[num10, num11].liquid > 0;
                    this.scale -= 0.0005f;
                    if ((double)this.scale < 0.1)
                    {
                        this.scale = 0.1f;
                        this.alpha = 255;
                    }
                    this.rotation += this.velocity.X * 0.1f;
                    if (flag2)
                    {
                        this.velocity.X = this.velocity.X * 0.9f;
                        int num12 = (int)vector.X / 16;
                        int num13 = (int)(vector.Y / 16f);
                        float num14 = this.position.Y / 16f;
                        int num15 = (int)((this.position.Y + this.Height) / 16f);
                        if (Main.tile[num12, num13] == null)
{
                            Main.tile[num12, num13] = new Tile();
                        }
                        if (Main.tile[num12, num15] == null)
{
                            Main.tile[num12, num15] = new Tile();
                        }
                        if (this.velocity.Y > 0f)
{
                            this.velocity.Y = this.velocity.Y * 0.5f;
                        }
                        num12 = (int)(vector.X / 16f);
                        num13 = (int)(vector.Y / 16f);
                        float num16 = this.ChumFloatingChunk_GetWaterLine(num12, num13);
                        if (vector.Y > num16)
{
                            this.velocity.Y = this.velocity.Y - 0.1f;
                            if (this.velocity.Y < -8f)
{
                                this.velocity.Y = -8f;
                            }
                            if (vector.Y + this.velocity.Y < num16)
{
                                this.velocity.Y = num16 - vector.Y;
                            }
                        }
                        else
{
                            this.velocity.Y = num16 - vector.Y;
                        }
                        bool flag3 = !flag2 && this.velocity.Length() < 0.8f;
                        int num17 = (flag2 ? 270 : 15);
                        if (Main.rand.Next(num17) == 0 && !flag3)
{
                            Gore gore = Gore.NewGoreDirect(this.position + Vector2.UnitY * 6f, Vector2.Zero, 1201, this.scale * 0.7f);
                            if (flag2)
{
                                gore.velocity = Vector2.UnitX * Main.rand.NextFloatDirection() * 0.5f + Vector2.UnitY * Main.rand.NextFloat();
                            }
                            else if (gore.velocity.Y < 0f)
{
                                gore.velocity.Y = -gore.velocity.Y;
                            }
                        }
                    }
                    else
                    {
                        if (this.velocity.Y == 0f)
{
                            this.velocity.X = this.velocity.X * 0.95f;
                        }
                        this.velocity.X = this.velocity.X * 0.98f;
                        this.velocity.Y = this.velocity.Y + 0.3f;
                        if (this.velocity.Y > 15.9f)
{
                            this.velocity.Y = 15.9f;
                        }
                    }
                }
                else if (this.type == 331)
                {
                    this.alpha += 5;
                    this.velocity.Y = this.velocity.Y * 0.95f;
                    this.velocity.X = this.velocity.X * 0.95f;
                    this.rotation = this.velocity.X * 0.1f;
                }
                else if (GoreID.Sets.SpecialAI[this.type] == 3)
                {
                    byte b = this.frameCounter + 1;
                    this.frameCounter = b;
                    if (b >= 8 && this.velocity.Y > 0.2f)
                    {
                        this.frameCounter = 0;
                        int num18 = (int)(this.Frame.CurrentRow / 4);
                        b = this.Frame.CurrentRow + 1;
                        this.Frame.CurrentRow = b;
                        if ((int)b >= 4 + num18 * 4)
{
                            this.Frame.CurrentRow = (byte)(num18 * 4);
                        }
                    }
                }
                else if (GoreID.Sets.SpecialAI[this.type] != 1 && GoreID.Sets.SpecialAI[this.type] != 2)
                {
                    if (this.type >= 907 && this.type <= 909)
                    {
                        this.rotation = 0f;
                        this.velocity.X = this.velocity.X * 0.98f;
                        if (this.velocity.Y > 0f && this.velocity.Y < 0.001f)
{
                            this.velocity.Y = -0.5f + Main.rand.NextFloat() * -3f;
                        }
                        if (this.velocity.Y > -1f)
{
                            this.velocity.Y = this.velocity.Y - 0.1f;
                        }
                        if (this.scale < 1f)
{
                            this.scale += 0.1f;
                        }
                        byte b = this.frameCounter + 1;
                        this.frameCounter = b;
                        if (b >= 8)
{
                            this.frameCounter = 0;
                            b = this.frame + 1;
                            this.frame = b;
                            if (b >= 3)
{
                                this.frame = 0;
                            }
                        }
                    }
                    else if (this.type == 1218)
                    {
                        if (this.timeLeft > 8)
{
                            this.timeLeft = 8;
                        }
                        this.velocity.X = this.velocity.X * 0.95f;
                        if (Math.Abs(this.velocity.X) <= 0.1f)
{
                            this.velocity.X = 0f;
                        }
                        if (this.alpha < 100 && this.velocity.Length() > 0f && Main.rand.Next(5) == 0)
{
                            int num19 = 246;
                            switch (this.Frame.CurrentRow)
{
                            case 0:
                                num19 = 246;
                                break;
                            case 1:
                                num19 = 245;
                                break;
                            case 2:
                                num19 = 244;
                                break;
                            }
                            int num20 = Dust.NewDust(this.position + new Vector2(6f, 4f), 4, 4, num19, 0f, 0f, 0, default(Color), 1f);
                            Main.dust[num20].alpha = 255;
                            Main.dust[num20].scale = 0.8f;
                            Main.dust[num20].velocity = Vector2.Zero;
                        }
                        this.velocity.Y = this.velocity.Y + 0.2f;
                        this.rotation = 0f;
                    }
                    else if (this.type < 411 || this.type > 430)
                    {
                        this.velocity.Y = this.velocity.Y + 0.2f;
                        this.rotation += this.velocity.X * 0.05f;
                    }
                    else if (GoreID.Sets.SpecialAI[this.type] != 3)
                    {
                        this.rotation += this.velocity.X * 0.1f;
                    }
                }
                if (this.type >= 580 && this.type <= 582)
                {
                    this.rotation = 0f;
                    this.velocity.X = this.velocity.X * 0.95f;
                }
                if (GoreID.Sets.SpecialAI[this.type] == 2)
                {
                    if (this.timeLeft < 60)
                    {
                        this.alpha += Main.rand.Next(1, 7);
                    }
                    else if (this.alpha > 100)
                    {
                        this.alpha -= Main.rand.Next(1, 4);
                    }
                    if (this.alpha < 0)
                    {
                        this.alpha = 0;
                    }
                    if (this.alpha > 255)
                    {
                        this.timeLeft = 0;
                    }
                    this.velocity.X = (this.velocity.X * 50f + Main.WindForVisuals * 2f + (float)Main.rand.Next(-10, 11) * 0.1f) / 51f;
                    float num21 = 0f;
                    if (this.velocity.X < 0f)
                    {
                        num21 = this.velocity.X * 0.2f;
                    }
                    this.velocity.Y = (this.velocity.Y * 50f + -0.35f + num21 + (float)Main.rand.Next(-10, 11) * 0.2f) / 51f;
                    this.rotation = this.velocity.X * 0.6f;
                    float num22 = -1f;
                    if (TextureAssets.Gore[this.type].IsLoaded)
                    {
                        Rectangle rectangle = new Rectangle((int)this.position.X, (int)this.position.Y, (int)((float)TextureAssets.Gore[this.type].Width() * this.scale), (int)((float)TextureAssets.Gore[this.type].Height() * this.scale));
                        for (int i = 0; i < 255; i++)
{
                            if (Main.player[i].active && !Main.player[i].dead)
{
                                Rectangle rectangle2 = new Rectangle((int)Main.player[i].position.X, (int)Main.player[i].position.Y, Main.player[i].width, Main.player[i].height);
                                if (rectangle.Intersects(rectangle2))
{
                                    this.timeLeft = 0;
                                    num22 = Main.player[i].velocity.Length();
                                    break;
                                }
                            }
                        }
                    }
                    if (this.timeLeft > 0)
                    {
                        if (Main.rand.Next(2) == 0)
{
                            this.timeLeft--;
                        }
                        if (Main.rand.Next(50) == 0)
{
                            this.timeLeft -= 5;
                        }
                        if (Main.rand.Next(100) == 0)
{
                            this.timeLeft -= 10;
                        }
                    }
                    else
                    {
                        this.alpha = 255;
                        if (TextureAssets.Gore[this.type].IsLoaded && num22 != -1f)
{
                            float num23 = (float)TextureAssets.Gore[this.type].Width() * this.scale * 0.8f;
                            float x = this.position.X;
                            float y = this.position.Y;
                            float num24 = (float)TextureAssets.Gore[this.type].Width() * this.scale;
                            float num25 = (float)TextureAssets.Gore[this.type].Height() * this.scale;
                            int num26 = 31;
                            int num27 = 0;
                            while ((float)num27 < num23)
{
                                int num28 = Dust.NewDust(new Vector2(x, y), (int)num24, (int)num25, num26, 0f, 0f, 0, default(Color), 1f);
                                Main.dust[num28].velocity *= (1f + num22) / 3f;
                                Main.dust[num28].noGravity = true;
                                Main.dust[num28].alpha = 100;
                                Main.dust[num28].scale = this.scale;
                                num27++;
                            }
                        }
                    }
                }
                if (this.type >= 411 && this.type <= 430)
                {
                    this.alpha = 50;
                    this.velocity.X = (this.velocity.X * 50f + Main.WindForVisuals * 2f + (float)Main.rand.Next(-10, 11) * 0.1f) / 51f;
                    this.velocity.Y = (this.velocity.Y * 50f + -0.25f + (float)Main.rand.Next(-10, 11) * 0.2f) / 51f;
                    this.rotation = this.velocity.X * 0.3f;
                    if (TextureAssets.Gore[this.type].IsLoaded)
                    {
                        Rectangle rectangle3 = new Rectangle((int)this.position.X, (int)this.position.Y, (int)((float)TextureAssets.Gore[this.type].Width() * this.scale), (int)((float)TextureAssets.Gore[this.type].Height() * this.scale));
                        for (int j = 0; j < 255; j++)
{
                            if (Main.player[j].active && !Main.player[j].dead)
{
                                Rectangle rectangle4 = new Rectangle((int)Main.player[j].position.X, (int)Main.player[j].position.Y, Main.player[j].width, Main.player[j].height);
                                if (rectangle3.Intersects(rectangle4))
{
                                    this.timeLeft = 0;
                                }
                            }
                        }
                        if (Collision.SolidCollision(this.position, (int)((float)TextureAssets.Gore[this.type].Width() * this.scale), (int)((float)TextureAssets.Gore[this.type].Height() * this.scale)))
{
                            this.timeLeft = 0;
                        }
                    }
                    if (this.timeLeft > 0)
                    {
                        if (Main.rand.Next(2) == 0)
{
                            this.timeLeft--;
                        }
                        if (Main.rand.Next(50) == 0)
{
                            this.timeLeft -= 5;
                        }
                        if (Main.rand.Next(100) == 0)
{
                            this.timeLeft -= 10;
                        }
                    }
                    else
                    {
                        this.alpha = 255;
                        if (TextureAssets.Gore[this.type].IsLoaded)
{
                            float num29 = (float)TextureAssets.Gore[this.type].Width() * this.scale * 0.8f;
                            float x2 = this.position.X;
                            float y2 = this.position.Y;
                            float num30 = (float)TextureAssets.Gore[this.type].Width() * this.scale;
                            float num31 = (float)TextureAssets.Gore[this.type].Height() * this.scale;
                            int num32 = 176;
                            if (this.type >= 416 && this.type <= 420)
{
                                num32 = 177;
                            }
                            if (this.type >= 421 && this.type <= 425)
{
                                num32 = 178;
                            }
                            if (this.type >= 426 && this.type <= 430)
{
                                num32 = 179;
                            }
                            int num33 = 0;
                            while ((float)num33 < num29)
{
                                int num34 = Dust.NewDust(new Vector2(x2, y2), (int)num30, (int)num31, num32, 0f, 0f, 0, default(Color), 1f);
                                Main.dust[num34].noGravity = true;
                                Main.dust[num34].alpha = 100;
                                Main.dust[num34].scale = this.scale;
                                num33++;
                            }
                        }
                    }
                }
                else if (GoreID.Sets.SpecialAI[this.type] != 3 && GoreID.Sets.SpecialAI[this.type] != 1)
                {
                    if (this.type >= 0 && this.type < GoreID.Count && GoreID.Sets.IsDrip[this.type])
                    {
                        if (this.type == 716 || this.type == 1383)
{
                            float num35 = 1f;
                            float num36 = 1f;
                            float num37 = 1f;
                            float num38 = 1f;
                            if (this.type == 716)
{
                                num35 = 1f;
                                num36 = 0.5f;
                                num37 = 0.1f;
                                num38 = 0.6f;
                            }
                            else if (this.type == 1383)
{
                                Point point = this.position.ToTileCoordinates();
                                Vector4 shimmerBaseColor = LiquidRenderer.GetShimmerBaseColor((float)point.X, (float)point.Y);
                                num35 = shimmerBaseColor.X;
                                num36 = shimmerBaseColor.Y;
                                num37 = shimmerBaseColor.Z;
                                num38 = 0.7f;
                            }
                            if (this.frame == 0)
{
                                num38 *= 0.1f;
                            }
                            else if (this.frame == 1)
{
                                num38 *= 0.2f;
                            }
                            else if (this.frame == 2)
{
                                num38 *= 0.3f;
                            }
                            else if (this.frame == 3)
{
                                num38 *= 0.4f;
                            }
                            else if (this.frame == 4)
{
                                num38 *= 0.5f;
                            }
                            else if (this.frame == 5)
{
                                num38 *= 0.4f;
                            }
                            else if (this.frame == 6)
{
                                num38 *= 0.2f;
                            }
                            else if (this.frame <= 9)
{
                                num38 *= 0.5f;
                            }
                            else if (this.frame == 10)
{
                                num38 *= 0.5f;
                            }
                            else if (this.frame == 11)
{
                                num38 *= 0.4f;
                            }
                            else if (this.frame == 12)
{
                                num38 *= 0.3f;
                            }
                            else if (this.frame == 13)
{
                                num38 *= 0.2f;
                            }
                            else if (this.frame == 14)
{
                                num38 *= 0.1f;
                            }
                            else
{
                                num38 = 0f;
                            }
                            num35 *= num38;
                            num36 *= num38;
                            num37 *= num38;
                            Lighting.AddLight(this.position + new Vector2(8f, 8f), num35, num36, num37);
                        }
                        bool flag4 = this.type == 716 || this.type == 717 || this.type == 943 || (this.type >= 1160 && this.type <= 1162);
                        Vector2 vector2 = this.velocity;
                        this.velocity = Collision.TileCollision(this.position, this.velocity, 16, 14, false, false, 1, false, false, true);
                        if (this.velocity != vector2)
{
                            if (this.frame < 10)
{
                                this.frame = 10;
                                this.frameCounter = 0;
                                if (!flag4)
{
                                    SoundEngine.PlaySound(39, (int)this.position.X + 8, (int)this.position.Y + 8, Main.rand.Next(2), 1f, 0f);
                                }
                            }
                        }
                        else if (Collision.WetCollision(this.position + this.velocity, 16, 14))
{
                            if (this.frame < 10)
{
                                this.frame = 10;
                                this.frameCounter = 0;
                                if (!flag4)
{
                                    SoundEngine.PlaySound(39, (int)this.position.X + 8, (int)this.position.Y + 8, 2, 1f, 0f);
                                }
                                ((WaterShaderData)Filters.Scene["WaterDistortion"].GetShader()).QueueRipple(this.position + new Vector2(8f, 8f), 1f, RippleShape.Square, 0f);
                            }
                            int num39 = (int)(this.position.X + 8f) / 16;
                            int num40 = (int)(this.position.Y + 14f) / 16;
                            if (Main.tile[num39, num40] != null && Main.tile[num39, num40].liquid > 0)
{
                                this.velocity *= 0f;
                                this.position.Y = (float)(num40 * 16 - (int)(Main.tile[num39, num40].liquid / 16));
                            }
                        }
                    }
                    else if (this.sticky)
                    {
                        int num41 = 32;
                        if (TextureAssets.Gore[this.type].IsLoaded)
{
                            num41 = TextureAssets.Gore[this.type].Width();
                            if (TextureAssets.Gore[this.type].Height() < num41)
{
                                num41 = TextureAssets.Gore[this.type].Height();
                            }
                        }
                        if (flag)
{
                            num41 = 4;
                        }
                        num41 = (int)((float)num41 * 0.9f);
                        Vector2 vector3 = this.velocity;
                        this.velocity = Collision.TileCollision(this.position, this.velocity, (int)((float)num41 * this.scale), (int)((float)num41 * this.scale), false, false, 1, false, false, true);
                        if (this.velocity.Y == 0f)
{
                            if (flag)
{
                                this.velocity.X = this.velocity.X * 0.94f;
                            }
                            else
{
                                this.velocity.X = this.velocity.X * 0.97f;
                            }
                            if ((double)this.velocity.X > -0.01 && (double)this.velocity.X < 0.01)
{
                                this.velocity.X = 0f;
                            }
                        }
                        if (this.timeLeft > 0)
{
                            this.timeLeft -= GoreID.Sets.DisappearSpeed[this.type];
                        }
                        else
{
                            this.alpha += GoreID.Sets.DisappearSpeedAlpha[this.type];
                        }
                    }
                    else
                    {
                        this.alpha += 2 * GoreID.Sets.DisappearSpeedAlpha[this.type];
                    }
                }
                if (this.type >= 907 && this.type <= 909)
                {
                    int num42 = 32;
                    if (TextureAssets.Gore[this.type].IsLoaded)
                    {
                        num42 = TextureAssets.Gore[this.type].Width();
                        if (TextureAssets.Gore[this.type].Height() < num42)
{
                            num42 = TextureAssets.Gore[this.type].Height();
                        }
                    }
                    num42 = (int)((float)num42 * 0.9f);
                    Vector4 vector4 = Collision.SlopeCollision(this.position, this.velocity, num42, num42, 0f, true, false);
                    this.position.X = vector4.X;
                    this.position.Y = vector4.Y;
                    this.velocity.X = vector4.Z;
                    this.velocity.Y = vector4.W;
                }
                if (GoreID.Sets.SpecialAI[this.type] == 1)
                {
                    this.Gore_UpdateSail();
                }
                else if (GoreID.Sets.SpecialAI[this.type] == 3)
                {
                    this.Gore_UpdateLeaf();
                }
                else
                {
                    this.position += this.velocity;
                }
                if (this.alpha >= 255)
                {
                    this.active = false;
                }
                if (this.light > 0f)
                {
                    float num43 = this.light * this.scale;
                    float num44 = this.light * this.scale;
                    float num45 = this.light * this.scale;
                    if (this.type == 16)
                    {
                        num45 *= 0.3f;
                        num44 *= 0.8f;
                    }
                    else if (this.type == 17)
                    {
                        num44 *= 0.6f;
                        num43 *= 0.3f;
                    }
                    if (TextureAssets.Gore[this.type].IsLoaded)
                    {
                        Lighting.AddLight((int)((this.position.X + (float)TextureAssets.Gore[this.type].Width() * this.scale / 2f) / 16f), (int)((this.position.Y + (float)TextureAssets.Gore[this.type].Height() * this.scale / 2f) / 16f), num43, num44, num45);
                        return;
                    }
                    Lighting.AddLight((int)((this.position.X + 32f * this.scale / 2f) / 16f), (int)((this.position.Y + 32f * this.scale / 2f) / 16f), num43, num44, num45);
                }
            }
        }
References System.Math.Abs(), Terraria.Gore.active, Terraria.Player.active, Terraria.Tile.active(), Terraria.Lighting.AddLight(), Terraria.Dust.alpha, Terraria.Gore.alpha, Terraria.Gore.ChumFloatingChunk_GetWaterLine(), Terraria.ID.GoreID.Count, Terraria.DataStructures.SpriteFrame.CurrentRow, Terraria.Gore.DeactivateIfOutsideOfWorld(), Terraria.Player.dead, Terraria.ID.GoreID.Sets.DisappearSpeed, Terraria.ID.GoreID.Sets.DisappearSpeedAlpha, Terraria.Main.dust, Terraria.Gore.frame, Terraria.Gore.Frame, Terraria.Gore.frameCounter, Terraria.GameContent.Liquid.LiquidRenderer.GetShimmerBaseColor(), Terraria.GameContent.TextureAssets.Gore, Terraria.Main.gore, Terraria.Gore.Gore_UpdateLeaf(), Terraria.Gore.Gore_UpdateSail(), Terraria.Entity.height, Terraria.Gore.Height, int, Microsoft.Xna.Framework.Rectangle.Intersects(), Terraria.WorldGen.InWorld(), Terraria.ID.GoreID.Sets.IsDrip, ReLogic.Content.Asset< T >.IsLoaded, Microsoft.Xna.Framework.Vector2.Length(), Terraria.Gore.light, Terraria.Tile.liquid, Terraria.Main.netMode, Terraria.Dust.NewDust(), Terraria.Gore.NewGore(), Terraria.Gore.NewGoreDirect(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Gore.position, Terraria.Main.rand, Terraria.Dust.scale, Terraria.Gore.scale, Terraria.Graphics.Effects.Filters.Scene, Terraria.Collision.SlopeCollision(), Terraria.Collision.SolidCollision(), Terraria.ID.GoreID.Sets.SpecialAI, Terraria.Gore.sticky, Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.Collision.TileCollision(), Terraria.Gore.timeLeft, Terraria.Gore.type, Microsoft.Xna.Framework.Vector2.UnitY, Terraria.Gore.UpdateAmbientAirborneCloud(), Terraria.Gore.UpdateAmbientFloorCloud(), Terraria.Gore.UpdateFogMachineCloud(), Terraria.Gore.UpdateLightningBunnySparks(), Terraria.Dust.velocity, Terraria.Entity.velocity, Terraria.Gore.velocity, Microsoft.Xna.Framework.Vector4.W, Terraria.Collision.WetCollision(), Terraria.Entity.width, Terraria.Gore.Width, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector4.X, Microsoft.Xna.Framework.Point.Y, Microsoft.Xna.Framework.Vector2.Y, Microsoft.Xna.Framework.Vector4.Y, Microsoft.Xna.Framework.Vector4.Z, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.Main.DoUpdateInWorld().