Terraria Decompiled: Terraria.Gore.UpdateLightningBunnySparks
UpdateLightningBunnySparks()
void Terraria.Gore.UpdateLightningBunnySparks () inline private
Definition at line 234 of file Gore.cs.
        {
            if (this.frameCounter == 0)
            {
                this.frameCounter = 1;
                this.Frame.CurrentRow = (byte)Main.rand.Next(3);
            }
            this.timeLeft -= GoreID.Sets.DisappearSpeed[this.type];
            if (this.timeLeft <= 0)
            {
                this.active = false;
                return;
            }
            this.alpha = (int)MathHelper.Lerp(255f, 0f, (float)this.timeLeft / 15f);
            float num = (255f - (float)this.alpha) / 255f;
            num *= this.scale;
            Lighting.AddLight(this.position + new Vector2(this.Width / 2f, this.Height / 2f), num * 0.4f, num, num);
            this.position += this.velocity;
        }
References Terraria.Lighting.AddLight(), Terraria.Gore.alpha, Terraria.ID.GoreID.Sets.DisappearSpeed, Terraria.Gore.frameCounter, Terraria.Gore.Height, int, Microsoft.Xna.Framework.MathHelper.Lerp(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Gore.position, Terraria.Main.rand, Terraria.Gore.scale, Terraria.Gore.timeLeft, Terraria.Gore.type, Terraria.Gore.velocity, and Terraria.Gore.Width.
Referenced by Terraria.Gore.Update().