Terraria Decompiled: Terraria.Gore.UpdateAmbientAirborneCloud
UpdateAmbientAirborneCloud()
void Terraria.Gore.UpdateAmbientAirborneCloud () inline private
Definition at line 145 of file Gore.cs.
        {
            this.timeLeft -= GoreID.Sets.DisappearSpeed[this.type];
            if (this.timeLeft <= 0)
            {
                this.active = false;
                return;
            }
            bool flag = false;
            Point point = (this.position + new Vector2(15f, 0f)).ToTileCoordinates();
            this.rotation = this.velocity.ToRotation();
            Tile tile = Main.tile[point.X, point.Y];
            if (tile == null)
            {
                this.active = false;
                return;
            }
            if (WorldGen.SolidTile(tile))
            {
                flag = true;
            }
            if (this.timeLeft <= 60)
            {
                flag = true;
            }
            if (!flag)
            {
                if (this.alpha > 240 && Main.rand.Next(5) == 0)
                {
                    this.alpha--;
                }
            }
            else
            {
                if (Main.rand.Next(5) == 0)
                {
                    this.alpha++;
                }
                if (this.alpha >= 255)
                {
                    this.active = false;
                    return;
                }
            }
            this.position += this.velocity;
        }
References Terraria.Gore.alpha, Terraria.ID.GoreID.Sets.DisappearSpeed, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, Terraria.WorldGen.SolidTile(), Terraria.Main.tile, Terraria.Gore.timeLeft, Terraria.Gore.type, Terraria.Gore.velocity, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.Gore.Update().