Terraria Decompiled: Terraria.Gore.Gore_UpdateSail
Gore_UpdateSail()
void Terraria.Gore.Gore_UpdateSail () inline private
Definition at line 1302 of file Gore.cs.
        {
            if (this.velocity.Y < 0f)
            {
                Vector2 vector = new Vector2(this.velocity.X, 0.6f);
                int num = 32;
                if (TextureAssets.Gore[this.type].IsLoaded)
                {
                    num = TextureAssets.Gore[this.type].Width();
                    if (TextureAssets.Gore[this.type].Height() < num)
                    {
                        num = TextureAssets.Gore[this.type].Height();
                    }
                }
                num = (int)((float)num * 0.9f);
                vector = Collision.TileCollision(this.position, vector, (int)((float)num * this.scale), (int)((float)num * this.scale), false, false, 1, false, false, true);
                vector.X *= 0.97f;
                if ((double)vector.X > -0.01 && (double)vector.X < 0.01)
                {
                    vector.X = 0f;
                }
                if (this.timeLeft > 0)
                {
                    this.timeLeft--;
                }
                else
                {
                    this.alpha++;
                }
                this.velocity.X = vector.X;
                return;
            }
            this.velocity.Y = this.velocity.Y + 0.05235988f;
            Vector2 vector2 = new Vector2(Vector2.UnitY.RotatedBy((double)this.velocity.Y, default(Vector2)).X * 2f, Math.Abs(Vector2.UnitY.RotatedBy((double)this.velocity.Y, default(Vector2)).Y) * 3f);
            vector2 *= 2f;
            int num2 = 32;
            if (TextureAssets.Gore[this.type].IsLoaded)
            {
                num2 = TextureAssets.Gore[this.type].Width();
                if (TextureAssets.Gore[this.type].Height() < num2)
                {
                    num2 = TextureAssets.Gore[this.type].Height();
                }
            }
            Vector2 vector3 = vector2;
            vector2 = Collision.TileCollision(this.position, vector2, (int)((float)num2 * this.scale), (int)((float)num2 * this.scale), false, false, 1, false, false, true);
            if (vector2 != vector3)
            {
                this.velocity.Y = -1f;
            }
            this.position += vector2;
            this.rotation = vector2.ToRotation() + 3.1415927f;
            if (this.timeLeft > 0)
            {
                this.timeLeft--;
                return;
            }
            this.alpha++;
        }
References System.Math.Abs(), Terraria.Gore.alpha, Terraria.GameContent.TextureAssets.Gore, int, ReLogic.Content.Asset< T >.IsLoaded, Terraria.Gore.position, Terraria.Gore.scale, Terraria.Collision.TileCollision(), Terraria.Gore.timeLeft, Terraria.Gore.type, Microsoft.Xna.Framework.Vector2.UnitY, Terraria.Gore.velocity, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Gore.Update().