Terraria Decompiled: Terraria.Gore.NewGore
NewGore()
static int Terraria.Gore.NewGore (Vector2 Position, Vector2 Velocity, int Type, float Scale = 1f) inline static
Definition at line 1378 of file Gore.cs.
        {
            if (Main.netMode == 2)
            {
                return 600;
            }
            if (Main.gamePaused)
            {
                return 600;
            }
            if (WorldGen.isGeneratingOrLoadingWorld)
            {
                return 600;
            }
            if (Main.rand == null)
            {
                Main.rand = new UnifiedRandom();
            }
            if (Type == -1)
            {
                return 600;
            }
            int num = 600;
            for (int i = 0; i < 600; i++)
            {
                if (!Main.gore[i].active)
                {
                    num = i;
                    break;
                }
            }
            if (num == 600)
            {
                return num;
            }
            Main.gore[num].Frame = new SpriteFrame(1, 1);
            Main.gore[num].frameCounter = 0;
            Main.gore[num].behindTiles = false;
            Main.gore[num].light = 0f;
            Main.gore[num].position = Position;
            Main.gore[num].velocity = Velocity;
            Gore gore = Main.gore[num];
            gore.velocity.Y = gore.velocity.Y - (float)Main.rand.Next(10, 31) * 0.1f;
            Gore gore2 = Main.gore[num];
            gore2.velocity.X = gore2.velocity.X + (float)Main.rand.Next(-20, 21) * 0.1f;
            Main.gore[num].type = Type;
            Main.gore[num].active = true;
            Main.gore[num].alpha = 0;
            Main.gore[num].rotation = 0f;
            Main.gore[num].scale = Scale;
            if (!ChildSafety.Disabled && ChildSafety.DangerousGore(Type))
            {
                Type = Main.rand.Next(11, 14);
                Main.gore[num].type = Type;
                Main.gore[num].scale = Main.rand.NextFloat() * 0.5f + 0.5f;
                Main.gore[num].velocity /= 2f;
            }
            if (Gore.goreTime == 0 || Type == 11 || Type == 12 || Type == 13 || Type == 16 || Type == 17 || Type == 61 || Type == 62 || Type == 63 || Type == 99 || Type == 220 || Type == 221 || Type == 222 || Type == 435 || Type == 436 || Type == 437 || (Type >= 861 && Type <= 862))
            {
                Main.gore[num].sticky = false;
            }
            else if (Type >= 375 && Type <= 377)
            {
                Main.gore[num].sticky = false;
                Main.gore[num].alpha = 100;
            }
            else
            {
                Main.gore[num].sticky = true;
                Main.gore[num].timeLeft = Gore.goreTime;
            }
            if (Type >= 0 && Type < GoreID.Count && GoreID.Sets.IsDrip[Type])
            {
                Main.gore[num].numFrames = 15;
                Main.gore[num].behindTiles = true;
                Main.gore[num].timeLeft = Gore.goreTime * 3;
            }
            if (Type == 16 || Type == 17)
            {
                Main.gore[num].alpha = 100;
                Main.gore[num].scale = 0.7f;
                Main.gore[num].light = 1f;
            }
            if (Type >= 570 && Type <= 572)
            {
                Main.gore[num].velocity = Velocity;
            }
            if (Type == 1201 || Type == 1208)
            {
                Main.gore[num].Frame = new SpriteFrame(1, 4);
            }
            if (Type == 1217 || Type == 1218)
            {
                Main.gore[num].Frame = new SpriteFrame(1, 3);
            }
            if (Type == 1225)
            {
                Main.gore[num].Frame = new SpriteFrame(1, 3);
                Main.gore[num].timeLeft = 10 + Main.rand.Next(6);
                Main.gore[num].sticky = false;
                if (TextureAssets.Gore[Type].IsLoaded)
                {
                    Main.gore[num].position.X = Position.X - (float)(TextureAssets.Gore[Type].Width() / 2) * Scale;
                    Main.gore[num].position.Y = Position.Y - (float)TextureAssets.Gore[Type].Height() * Scale / 2f;
                }
            }
            int num2 = GoreID.Sets.SpecialAI[Type];
            if (num2 == 3)
            {
                Main.gore[num].velocity = new Vector2((Main.rand.NextFloat() - 0.5f) * 1f, Main.rand.NextFloat() * 6.2831855f);
                bool flag = (Type >= 910 && Type <= 925) || (Type >= 1113 && Type <= 1121) || (Type >= 1248 && Type <= 1255) || Type == 1257 || Type == 1278;
                Main.gore[num].Frame = new SpriteFrame(flag ? 32 : 1, 8)
                {
                    CurrentRow = (byte)Main.rand.Next(8)
                };
                Main.gore[num].frameCounter = (byte)Main.rand.Next(8);
            }
            if (num2 == 1)
            {
                Main.gore[num].velocity = new Vector2((Main.rand.NextFloat() - 0.5f) * 3f, Main.rand.NextFloat() * 6.2831855f);
            }
            if (Type >= 411 && Type <= 430 && TextureAssets.Gore[Type].IsLoaded)
            {
                Main.gore[num].position.X = Position.X - (float)(TextureAssets.Gore[Type].Width() / 2) * Scale;
                Main.gore[num].position.Y = Position.Y - (float)TextureAssets.Gore[Type].Height() * Scale;
                Gore gore3 = Main.gore[num];
                gore3.velocity.Y = gore3.velocity.Y * ((float)Main.rand.Next(90, 150) * 0.01f);
                Gore gore4 = Main.gore[num];
                gore4.velocity.X = gore4.velocity.X * ((float)Main.rand.Next(40, 90) * 0.01f);
                int num3 = Main.rand.Next(4) * 5;
                Main.gore[num].type += num3;
                Main.gore[num].timeLeft = Main.rand.Next(Gore.goreTime / 2, Gore.goreTime * 2);
                Main.gore[num].sticky = true;
                if (Gore.goreTime == 0)
                {
                    Main.gore[num].timeLeft = Main.rand.Next(150, 600);
                }
            }
            if (Type >= 907 && Type <= 909)
            {
                Main.gore[num].sticky = true;
                Main.gore[num].numFrames = 3;
                Main.gore[num].frame = (byte)Main.rand.Next(3);
                Main.gore[num].frameCounter = (byte)Main.rand.Next(5);
                Main.gore[num].rotation = 0f;
            }
            if (num2 == 2)
            {
                Main.gore[num].sticky = false;
                if (TextureAssets.Gore[Type].IsLoaded)
                {
                    Main.gore[num].alpha = 150;
                    Main.gore[num].velocity = Velocity;
                    Main.gore[num].position.X = Position.X - (float)(TextureAssets.Gore[Type].Width() / 2) * Scale;
                    Main.gore[num].position.Y = Position.Y - (float)TextureAssets.Gore[Type].Height() * Scale / 2f;
                    Main.gore[num].timeLeft = Main.rand.Next(Gore.goreTime / 2, Gore.goreTime + 1);
                }
            }
            if (num2 == 4)
            {
                Main.gore[num].alpha = 254;
                Main.gore[num].timeLeft = 300;
            }
            if (num2 == 5)
            {
                Main.gore[num].alpha = 254;
                Main.gore[num].timeLeft = 240;
            }
            if (num2 == 6)
            {
                Main.gore[num].alpha = 254;
                Main.gore[num].timeLeft = 480;
            }
            if (Main.gore[num].DeactivateIfOutsideOfWorld())
            {
                return 600;
            }
            return num;
        }
References Terraria.Gore.active, Terraria.Gore.alpha, Terraria.Gore.behindTiles, Terraria.ID.GoreID.Count, Terraria.GameContent.ChildSafety.DangerousGore(), Terraria.Gore.DeactivateIfOutsideOfWorld(), Terraria.GameContent.ChildSafety.Disabled, Terraria.Gore.frame, Terraria.Gore.Frame, Terraria.Gore.frameCounter, Terraria.Main.gamePaused, Terraria.GameContent.TextureAssets.Gore, Terraria.Main.gore, Terraria.Gore.goreTime, Terraria.ID.GoreID.Sets.IsDrip, Terraria.WorldGen.isGeneratingOrLoadingWorld, ReLogic.Content.Asset< T >.IsLoaded, Terraria.Gore.light, Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Gore.numFrames, Terraria.Gore.position, Terraria.Main.rand, Terraria.Gore.rotation, Terraria.Gore.scale, Terraria.ID.GoreID.Sets.SpecialAI, Terraria.Gore.sticky, Terraria.Gore.timeLeft, Terraria.Gore.type, Terraria.Gore.velocity, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.NPC.AI_001_Slimes(), Terraria.NPC.AI_015_KingSlime(), Terraria.Projectile.AI_026(), Terraria.NPC.AI_045_Golem(), Terraria.Projectile.AI_067_FreakingPirates(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_108_DivingFlyer(), Terraria.NPC.AI_121_QueenSlime(), Terraria.Projectile.AI_147_Explosion(), Terraria.Projectile.AI_151_SuperStar(), Terraria.Projectile.AI_178_FireExplosion(), Terraria.NPC.BigMimicSpawnSmoke(), Terraria.DataStructures.PlayerDrawSet.BoringSetup(), Terraria.WorldGen.Check3x3(), Terraria.WorldGen.CheckPot(), Terraria.WorldItem.DespawnIfMeetingConditions(), Terraria.Mount.DoSpawnDust(), Terraria.Player.DoubleJumpVisuals(), Terraria.GameContent.Drawing.TileDrawing.DrawTiles_EmitParticles(), Terraria.Projectile.EmitEnchantmentVisualsAt(), Terraria.GameContent.Drawing.TileDrawing.EmitLiquidDrops(), Terraria.NPC.FindFrame(), Terraria.NPC.HitEffect(), Terraria.Player.ItemCheck_ApplyUseStyle(), Terraria.Player.ItemCheck_EmitUseVisuals(), Terraria.Player.ItemCheck_GetMeleeHitboxParticles(), Terraria.Player.JumpMovement(), Terraria.Player.KillMe(), Terraria.Gore.NewGoreDirect(), Terraria.Player.NinjaDodge(), Terraria.Utils.PoofOfSmoke(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ClassyCane(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_Digestion(), Terraria.DelegateMethods.Minecart.SpawnFartCloud(), Terraria.NPC.StrikeNPC(), Terraria.NPC.TransformVisuals(), Terraria.WorldGen.TreeGrowFX(), Terraria.Gore.Update(), Terraria.Player.UpdateHairDyeDust(), and Terraria.NPC.UpdateNPC_BuffApplyVFX().