Terraria Decompiled: XPT.Core.Audio.MP3Sharp.Support.SupportClass.WriteStackTrace
WriteStackTrace()
static void XPT.Core.Audio.MP3Sharp.Support.SupportClass.WriteStackTrace (Exception throwable, TextWriter stream) inline static package
Definition at line 42 of file SupportClass.cs.
        {
            stream.Write(throwable.StackTrace);
            stream.Flush();
        }
References System.IO.TextWriter.Flush(), System.Exception.StackTrace, and System.IO.TextWriter.Write().
Referenced by XPT.Core.Audio.MP3Sharp.MP3SharpException.PrintStackTrace(), and XPT.Core.Audio.MP3Sharp.MP3SharpException.PrintStackTrace().