Terraria Decompiled: Ionic.Zlib.ZlibBaseStream._ReadAndValidateGzipHeader
_ReadAndValidateGzipHeader()
int Ionic.Zlib.ZlibBaseStream._ReadAndValidateGzipHeader () inline private
Definition at line 320 of file ZlibBaseStream.cs.
        {
            int num = 0;
            byte[] array = new byte[10];
            int num2 = this._stream.Read(array, 0, array.Length);
            if (num2 == 0)
            {
                return 0;
            }
            if (num2 != 10)
            {
                throw new ZlibException("Not a valid GZIP stream.");
            }
            if (array[0] != 31 || array[1] != 139 || array[2] != 8)
            {
                throw new ZlibException("Bad GZIP header.");
            }
            int num3 = BitConverter.ToInt32(array, 4);
            this._GzipMtime = GZipStream._unixEpoch.AddSeconds((double)num3);
            num += num2;
            if ((array[3] & 4) == 4)
            {
                num2 = this._stream.Read(array, 0, 2);
                num += num2;
                short num4 = (short)((int)array[0] + (int)array[1] * 256);
                byte[] array2 = new byte[(int)num4];
                num2 = this._stream.Read(array2, 0, array2.Length);
                if (num2 != (int)num4)
                {
                    throw new ZlibException("Unexpected end-of-file reading GZIP header.");
                }
                num += num2;
            }
            if ((array[3] & 8) == 8)
            {
                this._GzipFileName = this.ReadZeroTerminatedString();
            }
            if ((array[3] & 16) == 16)
            {
                this._GzipComment = this.ReadZeroTerminatedString();
            }
            if ((array[3] & 2) == 2)
            {
                this.Read(this._buf1, 0, 1);
            }
            return num;
        }
References Ionic.Zlib.ZlibBaseStream._buf1, Ionic.Zlib.ZlibBaseStream._stream, Ionic.Zlib.GZipStream._unixEpoch, System.DateTime.AddSeconds(), System.array, int, System.IO.Read, System.IO.Stream.Read(), Ionic.Zlib.ZlibBaseStream.ReadZeroTerminatedString(), and System.BitConverter.ToInt32().
Referenced by Ionic.Zlib.ZlibBaseStream.Read().