Terraria Decompiled: Ionic.Zlib.ZlibBaseStream.UncompressString
UncompressString()
static string Ionic.Zlib.ZlibBaseStream.UncompressString (byte[] compressed, Stream decompressor) inline static
Definition at line 562 of file ZlibBaseStream.cs.
        {
            byte[] array = new byte[1024];
            Encoding utf = Encoding.UTF8;
            string text;
            using (MemoryStream memoryStream = new MemoryStream())
            {
                try
                {
                    int num;
                    while ((num = decompressor.Read(array, 0, array.Length)) != 0)
                    {
                        memoryStream.Write(array, 0, num);
                    }
                }
                finally
                {
                    if (decompressor != null)
                    {
                        decompressor.Dispose();
                    }
                }
                memoryStream.Seek(0L, 0);
                StreamReader streamReader = new StreamReader(memoryStream, utf);
                text = streamReader.ReadToEnd();
            }
            return text;
        }
References System.array, System.IO.Stream.Dispose(), System.L, System.IO.Stream.Read(), System.IO.StreamReader.ReadToEnd(), System.IO.MemoryStream.Seek(), System.text, System.Text.Encoding.UTF8, and System.IO.MemoryStream.Write().
Referenced by Ionic.Zlib.DeflateStream.UncompressString(), Ionic.Zlib.GZipStream.UncompressString(), and Ionic.Zlib.ZlibStream.UncompressString().