Terraria Decompiled: Ionic.Zlib.ZlibBaseStream.finish
finish()
void Ionic.Zlib.ZlibBaseStream.finish () inline private
Definition at line 136 of file ZlibBaseStream.cs.
        {
            if (this._z == null)
            {
                return;
            }
            if (this._streamMode == ZlibBaseStream.StreamMode.Writer)
            {
                int num;
                for (;;)
                {
                    this._z.OutputBuffer = this.workingBuffer;
                    this._z.NextOut = 0;
                    this._z.AvailableBytesOut = this._workingBuffer.Length;
                    num = (this._wantCompress ? this._z.Deflate(FlushType.Finish) : this._z.Inflate(FlushType.Finish));
                    if (num != 1 && num != 0)
                    {
                        break;
                    }
                    if (this._workingBuffer.Length - this._z.AvailableBytesOut > 0)
                    {
                        this._stream.Write(this._workingBuffer, 0, this._workingBuffer.Length - this._z.AvailableBytesOut);
                    }
                    bool flag = this._z.AvailableBytesIn == 0 && this._z.AvailableBytesOut != 0;
                    if (this._flavor == ZlibStreamFlavor.GZIP && !this._wantCompress)
                    {
                        flag = this._z.AvailableBytesIn == 8 && this._z.AvailableBytesOut != 0;
                    }
                    if (flag)
                    {
                        goto Block_12;
                    }
                }
                string text = (this._wantCompress ? "de" : "in") + "flating";
                if (this._z.Message == null)
                {
                    throw new ZlibException(string.Format("{0}: (rc = {1})", text, num));
                }
                throw new ZlibException(text + ": " + this._z.Message);
                Block_12:
                this.Flush();
                if (this._flavor == ZlibStreamFlavor.GZIP)
                {
                    if (this._wantCompress)
                    {
                        int crc32Result = this.crc.Crc32Result;
                        this._stream.Write(BitConverter.GetBytes(crc32Result), 0, 4);
                        int num2 = (int)(this.crc.TotalBytesRead & (long)((ulong)(-1)));
                        this._stream.Write(BitConverter.GetBytes(num2), 0, 4);
                        return;
                    }
                    throw new ZlibException("Writing with decompression is not supported.");
                }
            }
            else if (this._streamMode == ZlibBaseStream.StreamMode.Reader && this._flavor == ZlibStreamFlavor.GZIP)
            {
                if (this._wantCompress)
                {
                    throw new ZlibException("Reading with compression is not supported.");
                }
                if (this._z.TotalBytesOut == 0L)
                {
                    return;
                }
                byte[] array = new byte[8];
                if (this._z.AvailableBytesIn < 8)
                {
                    Array.Copy(this._z.InputBuffer, this._z.NextIn, array, 0, this._z.AvailableBytesIn);
                    int num3 = 8 - this._z.AvailableBytesIn;
                    int num4 = this._stream.Read(array, this._z.AvailableBytesIn, num3);
                    if (num3 != num4)
                    {
                        throw new ZlibException(string.Format("Missing or incomplete GZIP trailer. Expected 8 bytes, got {0}.", this._z.AvailableBytesIn + num4));
                    }
                }
                else
                {
                    Array.Copy(this._z.InputBuffer, this._z.NextIn, array, 0, array.Length);
                }
                int num5 = BitConverter.ToInt32(array, 0);
                int crc32Result2 = this.crc.Crc32Result;
                int num6 = BitConverter.ToInt32(array, 4);
                int num7 = (int)(this._z.TotalBytesOut & (long)((ulong)(-1)));
                if (crc32Result2 != num5)
                {
                    throw new ZlibException(string.Format("Bad CRC32 in GZIP trailer. (actual({0:X8})!=expected({1:X8}))", crc32Result2, num5));
                }
                if (num7 != num6)
                {
                    throw new ZlibException(string.Format("Bad size in GZIP trailer. (actual({0})!=expected({1}))", num7, num6));
                }
            }
        }
References Ionic.Zlib.ZlibBaseStream._flavor, Ionic.Zlib.ZlibBaseStream._stream, Ionic.Zlib.ZlibBaseStream._streamMode, Ionic.Zlib.ZlibBaseStream._wantCompress, Ionic.Zlib.ZlibBaseStream._workingBuffer, Ionic.Zlib.ZlibBaseStream._z, System.array, Ionic.Zlib.ZlibCodec.AvailableBytesIn, System.Array.Copy(), Ionic.Zlib.ZlibBaseStream.crc, Ionic.Crc.CRC32.Crc32Result, Ionic.Zlib.ZlibCodec.Deflate(), Ionic.Zlib.ZlibBaseStream.Flush(), System.Format, System.BitConverter.GetBytes(), Ionic.Zlib.ZlibCodec.Inflate(), Ionic.Zlib.ZlibCodec.InputBuffer, int, System.L, Ionic.Zlib.ZlibCodec.Message, System.IO.Stream.Read(), System.text, System.BitConverter.ToInt32(), Ionic.Zlib.ZlibCodec.TotalBytesOut, Ionic.Crc.CRC32.TotalBytesRead, Ionic.Zlib.ZlibBaseStream.workingBuffer, and System.IO.Stream.Write().
Referenced by Ionic.Zlib.ZlibBaseStream.Close().