Terraria Decompiled: Ionic.Zlib.ZlibBaseStream.Read
Read()
override int Ionic.Zlib.ZlibBaseStream.Read (byte[] buffer, int offset, int count) inline
Definition at line 369 of file ZlibBaseStream.cs.
        {
            if (this._streamMode == ZlibBaseStream.StreamMode.Undefined)
            {
                if (!this._stream.CanRead)
                {
                    throw new ZlibException("The stream is not readable.");
                }
                this._streamMode = ZlibBaseStream.StreamMode.Reader;
                this.z.AvailableBytesIn = 0;
                if (this._flavor == ZlibStreamFlavor.GZIP)
                {
                    this._gzipHeaderByteCount = this._ReadAndValidateGzipHeader();
                    if (this._gzipHeaderByteCount == 0)
                    {
                        return 0;
                    }
                }
            }
            if (this._streamMode != ZlibBaseStream.StreamMode.Reader)
            {
                throw new ZlibException("Cannot Read after Writing.");
            }
            if (count == 0)
            {
                return 0;
            }
            if (this.nomoreinput && this._wantCompress)
            {
                return 0;
            }
            if (buffer == null)
            {
                throw new ArgumentNullException("buffer");
            }
            if (count < 0)
            {
                throw new ArgumentOutOfRangeException("count");
            }
            if (offset < buffer.GetLowerBound(0))
            {
                throw new ArgumentOutOfRangeException("offset");
            }
            if (offset + count > buffer.GetLength(0))
            {
                throw new ArgumentOutOfRangeException("count");
            }
            this._z.OutputBuffer = buffer;
            this._z.NextOut = offset;
            this._z.AvailableBytesOut = count;
            this._z.InputBuffer = this.workingBuffer;
            int num;
            for (;;)
            {
                if (this._z.AvailableBytesIn == 0 && !this.nomoreinput)
                {
                    this._z.NextIn = 0;
                    this._z.AvailableBytesIn = this._stream.Read(this._workingBuffer, 0, this._workingBuffer.Length);
                    if (this._z.AvailableBytesIn == 0)
                    {
                        this.nomoreinput = true;
                    }
                }
                num = (this._wantCompress ? this._z.Deflate(this._flushMode) : this._z.Inflate(this._flushMode));
                if (this.nomoreinput && num == -5)
                {
                    break;
                }
                if (num != 0 && num != 1)
                {
                    goto Block_20;
                }
                if (((this.nomoreinput || num == 1) && this._z.AvailableBytesOut == count) || this._z.AvailableBytesOut <= 0 || this.nomoreinput || num != 0)
                {
                    goto IL_020A;
                }
            }
            return 0;
            Block_20:
            throw new ZlibException(string.Format("{0}flating:  rc={1}  msg={2}", this._wantCompress ? "de" : "in", num, this._z.Message));
            IL_020A:
            if (this._z.AvailableBytesOut > 0)
            {
                if (num == 0)
                {
                    int availableBytesIn = this._z.AvailableBytesIn;
                }
                if (this.nomoreinput && this._wantCompress)
                {
                    num = this._z.Deflate(FlushType.Finish);
                    if (num != 0 && num != 1)
                    {
                        throw new ZlibException(string.Format("Deflating:  rc={0}  msg={1}", num, this._z.Message));
                    }
                }
            }
            num = count - this._z.AvailableBytesOut;
            if (this.crc != null)
            {
                this.crc.SlurpBlock(buffer, offset, num);
            }
            return num;
        }
References Ionic.Zlib.ZlibBaseStream._flavor, Ionic.Zlib.ZlibBaseStream._flushMode, Ionic.Zlib.ZlibBaseStream._gzipHeaderByteCount, Ionic.Zlib.ZlibBaseStream._ReadAndValidateGzipHeader(), Ionic.Zlib.ZlibBaseStream._stream, Ionic.Zlib.ZlibBaseStream._streamMode, Ionic.Zlib.ZlibBaseStream._wantCompress, Ionic.Zlib.ZlibBaseStream._workingBuffer, Ionic.Zlib.ZlibBaseStream._z, Ionic.Zlib.ZlibCodec.AvailableBytesIn, Ionic.Zlib.ZlibCodec.AvailableBytesOut, System.IO.Stream.CanRead, System.count, Ionic.Zlib.ZlibBaseStream.crc, Ionic.Zlib.ZlibCodec.Deflate(), System.Format, Ionic.Zlib.ZlibCodec.Inflate(), Ionic.Zlib.ZlibCodec.Message, Ionic.Zlib.ZlibBaseStream.nomoreinput, System.offset, System.IO.Stream.Read(), Ionic.Crc.CRC32.SlurpBlock(), and Ionic.Zlib.ZlibBaseStream.workingBuffer.
Referenced by Ionic.Zlib.DeflateStream.Read(), Ionic.Zlib.GZipStream.Read(), and Ionic.Zlib.ZlibStream.Read().