Terraria Decompiled: Ionic.Zlib.ZlibBaseStream.Write
Write()
override void Ionic.Zlib.ZlibBaseStream.Write (byte[] buffer, int offset, int count) inline
Definition at line 90 of file ZlibBaseStream.cs.
        {
            if (this.crc != null)
            {
                this.crc.SlurpBlock(buffer, offset, count);
            }
            if (this._streamMode == ZlibBaseStream.StreamMode.Undefined)
            {
                this._streamMode = ZlibBaseStream.StreamMode.Writer;
            }
            else if (this._streamMode != ZlibBaseStream.StreamMode.Writer)
            {
                throw new ZlibException("Cannot Write after Reading.");
            }
            if (count == 0)
            {
                return;
            }
            this.z.InputBuffer = buffer;
            this._z.NextIn = offset;
            this._z.AvailableBytesIn = count;
            for (;;)
            {
                this._z.OutputBuffer = this.workingBuffer;
                this._z.NextOut = 0;
                this._z.AvailableBytesOut = this._workingBuffer.Length;
                int num = (this._wantCompress ? this._z.Deflate(this._flushMode) : this._z.Inflate(this._flushMode));
                if (num != 0 && num != 1)
                {
                    break;
                }
                this._stream.Write(this._workingBuffer, 0, this._workingBuffer.Length - this._z.AvailableBytesOut);
                bool flag = this._z.AvailableBytesIn == 0 && this._z.AvailableBytesOut != 0;
                if (this._flavor == ZlibStreamFlavor.GZIP && !this._wantCompress)
                {
                    flag = this._z.AvailableBytesIn == 8 && this._z.AvailableBytesOut != 0;
                }
                if (flag)
                {
                    return;
                }
            }
            throw new ZlibException((this._wantCompress ? "de" : "in") + "flating: " + this._z.Message);
        }
References Ionic.Zlib.ZlibBaseStream._flavor, Ionic.Zlib.ZlibBaseStream._flushMode, Ionic.Zlib.ZlibBaseStream._stream, Ionic.Zlib.ZlibBaseStream._streamMode, Ionic.Zlib.ZlibBaseStream._wantCompress, Ionic.Zlib.ZlibBaseStream._workingBuffer, Ionic.Zlib.ZlibBaseStream._z, System.count, Ionic.Zlib.ZlibBaseStream.crc, Ionic.Zlib.ZlibCodec.Deflate(), Ionic.Zlib.ZlibCodec.Inflate(), Ionic.Zlib.ZlibCodec.Message, System.offset, Ionic.Crc.CRC32.SlurpBlock(), Ionic.Zlib.ZlibBaseStream.workingBuffer, and System.IO.Stream.Write().
Referenced by Ionic.Zlib.DeflateStream.Write(), Ionic.Zlib.GZipStream.Write(), and Ionic.Zlib.ZlibStream.Write().