Terraria Decompiled: Ionic.Zlib.ZlibBaseStream.ReadZeroTerminatedString
ReadZeroTerminatedString()
string Ionic.Zlib.ZlibBaseStream.ReadZeroTerminatedString () inline private
Definition at line 289 of file ZlibBaseStream.cs.
        {
            List<byte> list = new List<byte>();
            bool flag = false;
            for (;;)
            {
                int num = this._stream.Read(this._buf1, 0, 1);
                if (num != 1)
                {
                    break;
                }
                if (this._buf1[0] == 0)
                {
                    flag = true;
                }
                else
                {
                    list.Add(this._buf1[0]);
                }
                if (flag)
                {
                    goto Block_3;
                }
            }
            throw new ZlibException("Unexpected EOF reading GZIP header.");
            Block_3:
            byte[] array = list.ToArray();
            return GZipStream.iso8859dash1.GetString(array, 0, array.Length);
        }
References Ionic.Zlib.ZlibBaseStream._buf1, Ionic.Zlib.ZlibBaseStream._stream, System.array, System.Text.Encoding.GetString(), Ionic.Zlib.GZipStream.iso8859dash1, System.list, and System.IO.Stream.Read().
Referenced by Ionic.Zlib.ZlibBaseStream._ReadAndValidateGzipHeader().