Terraria Decompiled: System.Runtime.Remoting.Messaging.CADMethodCallMessage.CADMethodCallMessage
CADMethodCallMessage()
System.Runtime.Remoting.Messaging.CADMethodCallMessage.CADMethodCallMessage (IMethodCallMessage callMsg) inline package
Definition at line 33 of file CADMethodCallMessage.cs.
            : base(callMsg)
        {
            this._uri = callMsg.Uri;
            ArrayList arrayList = null;
            this._propertyCount = CADMessageBase.MarshalProperties(callMsg.Properties, ref arrayList);
            this._args = base.MarshalArguments(callMsg.Args, ref arrayList);
            base.SaveLogicalCallContext(callMsg, ref arrayList);
            if (arrayList != null)
            {
                MemoryStream memoryStream = CADSerializer.SerializeObject(arrayList.ToArray());
                this._serializedArgs = memoryStream.GetBuffer();
            }
        }
References System.Runtime.Remoting.Messaging.IMethodMessage.Args, System.IO.MemoryStream.GetBuffer(), System.Runtime.Remoting.Messaging.CADMessageBase.MarshalProperties(), System.Runtime.Remoting.Messaging.IMessage.Properties, System.Runtime.Remoting.Channels.CADSerializer.SerializeObject(), System.Collections.ArrayList.ToArray(), and System.Runtime.Remoting.Messaging.IMethodMessage.Uri.
Referenced by System.Runtime.Remoting.Messaging.CADMethodCallMessage.Create().