Terraria Decompiled: Steamworks.CSteamID.CreateBlankAnonLogon
CreateBlankAnonLogon()
void Steamworks.CSteamID.CreateBlankAnonLogon (EUniverse eUniverse) inline
Definition at line 61 of file CSteamID.cs.
        {
            this.SetAccountID(new AccountID_t(0U));
            this.SetEUniverse(eUniverse);
            this.SetEAccountType(EAccountType.k_EAccountTypeAnonGameServer);
            this.SetAccountInstance(0U);
        }
References Steamworks.CSteamID.SetAccountID(), Steamworks.CSteamID.SetAccountInstance(), Steamworks.CSteamID.SetEAccountType(), Steamworks.CSteamID.SetEUniverse(), and System.U.