Terraria Decompiled: System.Threading.SemaphoreSlim.d__32.MoveNext
MoveNext()
void IAsyncStateMachine. System.Threading.SemaphoreSlim.d__32.MoveNext () inline
Implements System.Runtime.CompilerServices.IAsyncStateMachine.
Definition at line 558 of file SemaphoreSlim.cs.
            {
                int num2;
                int num = num2;
                SemaphoreSlim semaphoreSlim = this;
                bool flag;
                try
                {
                    ConfiguredTaskAwaitable<bool>.ConfiguredTaskAwaiter configuredTaskAwaiter;
                    if (num != 0)
                    {
                        if (num == 1)
{
                            ConfiguredTaskAwaitable<bool>.ConfiguredTaskAwaiter configuredTaskAwaiter2;
                            configuredTaskAwaiter = configuredTaskAwaiter2;
                            configuredTaskAwaiter2 = default(ConfiguredTaskAwaitable<bool>.ConfiguredTaskAwaiter);
                            num = (num2 = -1);
                            goto IL_01CF;
                        }
                        cts = (cancellationToken.CanBeCanceled ? CancellationTokenSource.CreateLinkedTokenSource(cancellationToken, default(CancellationToken)) : new CancellationTokenSource());
                    }
                    try
                    {
                        ConfiguredTaskAwaitable<Task>.ConfiguredTaskAwaiter configuredTaskAwaiter3;
                        if (num != 0)
{
                            Task<Task> task = Task.WhenAny(new Task[]
{
                                asyncWaiter,
                                Task.Delay(millisecondsTimeout, cts.Token)
                            });
                            obj = asyncWaiter;
                            configuredTaskAwaiter3 = task.ConfigureAwait(false).GetAwaiter();
                            if (!configuredTaskAwaiter3.IsCompleted)
{
                                num = (num2 = 0);
                                ConfiguredTaskAwaitable<Task>.ConfiguredTaskAwaiter configuredTaskAwaiter4 = configuredTaskAwaiter3;
                                this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredTaskAwaitable<Task>.ConfiguredTaskAwaiter, SemaphoreSlim.<WaitUntilCountOrTimeoutAsync>d__32>(ref configuredTaskAwaiter3, ref this);
                                return;
                            }
                        }
                        else
{
                            ConfiguredTaskAwaitable<Task>.ConfiguredTaskAwaiter configuredTaskAwaiter4;
                            configuredTaskAwaiter3 = configuredTaskAwaiter4;
                            configuredTaskAwaiter4 = default(ConfiguredTaskAwaitable<Task>.ConfiguredTaskAwaiter);
                            num = (num2 = -1);
                        }
                        Task result = configuredTaskAwaiter3.GetResult();
                        if (obj == result)
{
                            obj = null;
                            cts.Cancel();
                            flag = true;
                            goto IL_01F2;
                        }
                    }
                    finally
                    {
                        if (num < 0 && cts != null)
{
                            ((IDisposable)cts).Dispose();
                        }
                    }
                    cts = null;
                    object lockObj = semaphoreSlim.m_lockObj;
                    bool flag2 = false;
                    try
                    {
                        Monitor.Enter(lockObj, ref flag2);
                        if (semaphoreSlim.RemoveAsyncWaiter(asyncWaiter))
{
                            cancellationToken.ThrowIfCancellationRequested();
                            flag = false;
                            goto IL_01F2;
                        }
                    }
                    finally
                    {
                        if (num < 0 && flag2)
{
                            Monitor.Exit(lockObj);
                        }
                    }
                    configuredTaskAwaiter = asyncWaiter.ConfigureAwait(false).GetAwaiter();
                    if (!configuredTaskAwaiter.IsCompleted)
                    {
                        num = (num2 = 1);
                        ConfiguredTaskAwaitable<bool>.ConfiguredTaskAwaiter configuredTaskAwaiter2 = configuredTaskAwaiter;
                        this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredTaskAwaitable<bool>.ConfiguredTaskAwaiter, SemaphoreSlim.<WaitUntilCountOrTimeoutAsync>d__32>(ref configuredTaskAwaiter, ref this);
                        return;
                    }
                    IL_01CF:
                    flag = configuredTaskAwaiter.GetResult();
                }
                catch (Exception ex)
                {
                    num2 = -2;
                    this.<>t__builder.SetException(ex);
                    return;
                }
                IL_01F2:
                num2 = -2;
                this.<>t__builder.SetResult(flag);
            }
References System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Threading.CancellationTokenSource.CreateLinkedTokenSource(), System.Threading.Tasks.Task< TResult >.Delay(), System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), System.Runtime.CompilerServices.ConfiguredTaskAwaitable< TResult >.GetAwaiter(), System.Threading.SemaphoreSlim.m_lockObj, System.obj, System.Threading.SemaphoreSlim.RemoveAsyncWaiter(), System.task, System.Threading.SemaphoreSlim.WaitUntilCountOrTimeoutAsync(), and System.Threading.Tasks.Task< TResult >.WhenAny().