Terraria Decompiled: Steamworks.CSteamID.BBlankAnonAccount
BBlankAnonAccount()
bool Steamworks.CSteamID.BBlankAnonAccount () inline
Definition at line 79 of file CSteamID.cs.
        {
            return this.GetAccountID() == new AccountID_t(0U) && this.BAnonAccount() && this.GetUnAccountInstance() == 0U;
        }
References Steamworks.CSteamID.BAnonAccount(), Steamworks.CSteamID.GetAccountID(), Steamworks.CSteamID.GetUnAccountInstance(), and System.U.