Terraria Decompiled: Newtonsoft.Json.Utilities.ConvertUtils.GetTypeCode
GetTypeCode() [1/2]
static PrimitiveTypeCode Newtonsoft.Json.Utilities.ConvertUtils.GetTypeCode (Type t) inline static
Definition at line 17 of file ConvertUtils.cs.
        {
            bool flag;
            return ConvertUtils.GetTypeCode(t, out flag);
        }
References Newtonsoft.Json.Utilities.ConvertUtils.GetTypeCode().
Referenced by Newtonsoft.Json.Utilities.ReflectionUtils.GetDefaultValue(), Newtonsoft.Json.Schema.JsonSchemaGenerator.GetJsonSchemaType(), Newtonsoft.Json.Utilities.ConvertUtils.GetTypeCode(), Newtonsoft.Json.Utilities.ConvertUtils.GetTypeCode(), Newtonsoft.Json.Utilities.ConvertUtils.IsInteger(), Newtonsoft.Json.Serialization.DefaultContractResolver.IsJsonPrimitiveType(), Newtonsoft.Json.Serialization.JsonPrimitiveContract.JsonPrimitiveContract(), Newtonsoft.Json.Linq.JToken.ToObject(), Newtonsoft.Json.JsonConvert.ToString(), and Newtonsoft.Json.JsonWriter.WriteValue().