Terraria Decompiled: Terraria.GameContent.Bestiary.CommonEnemyUICollectionInfoProvider.GetKillCountNeeded
GetKillCountNeeded()
static int Terraria.GameContent.Bestiary.CommonEnemyUICollectionInfoProvider.GetKillCountNeeded (string persistentId) inline static
Definition at line 19 of file CommonEnemyUICollectionInfoProvider.cs.
        {
            int defaultKillsForBannerNeeded = ItemID.Sets.DefaultKillsForBannerNeeded;
            int num;
            if (!ContentSamples.NpcNetIdsByPersistentIds.TryGetValue(persistentId, out num))
            {
                return defaultKillsForBannerNeeded;
            }
            NPC npc;
            if (!ContentSamples.NpcsByNetId.TryGetValue(num, out npc))
            {
                return defaultKillsForBannerNeeded;
            }
            int num2 = BannerSystem.BannerToItem(BannerSystem.NPCtoBanner(npc.BannerID()));
            return ItemID.Sets.KillsToBanner[num2];
        }
References Terraria.NPC.BannerID(), Terraria.GameContent.BannerSystem.BannerToItem(), Terraria.ID.ItemID.Sets.DefaultKillsForBannerNeeded, Terraria.ID.ItemID.Sets.KillsToBanner, Terraria.ID.ContentSamples.NpcNetIdsByPersistentIds, Terraria.ID.ContentSamples.NpcsByNetId, Terraria.GameContent.BannerSystem.NPCtoBanner(), and System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue().
Referenced by Terraria.GameContent.Bestiary.CommonEnemyUICollectionInfoProvider.CommonEnemyUICollectionInfoProvider(), and Terraria.GameContent.Bestiary.SalamanderShellyDadUICollectionInfoProvider.SalamanderShellyDadUICollectionInfoProvider().