Terraria Decompiled: Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable
EnsureTypeAssignable()
static object Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable (object value, Type initialType, Type targetType) inline static private
Definition at line 372 of file ConvertUtils.cs.
        {
            Type type = ((value != null) ? value.GetType() : null);
            if (value != null)
            {
                if (targetType.IsAssignableFrom(type))
                {
                    return value;
                }
                Func<object, object> func = ConvertUtils.CastConverters.Get(new ConvertUtils.TypeConvertKey(type, targetType));
                if (func != null)
                {
                    return func.Invoke(value);
                }
            }
            else if (ReflectionUtils.IsNullable(targetType))
            {
                return null;
            }
            throw new ArgumentException("Could not cast or convert from {0} to {1}.".FormatWith(CultureInfo.InvariantCulture, ((initialType != null) ? initialType.ToString() : null) ?? "{null}", targetType));
        }
References Newtonsoft.Json.Utilities.ConvertUtils.CastConverters, System.Globalization.CultureInfo.InvariantCulture, System.Type.IsAssignableFrom(), Newtonsoft.Json.Utilities.ReflectionUtils.IsNullable(), System.Type.ToString(), and System.value.
Referenced by Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(), and Newtonsoft.Json.Utilities.ConvertUtils.TryConvertInternal().