Terraria Decompiled: Newtonsoft.Json.Utilities.ConvertUtils.GetTypeCode
GetTypeCode() [2/2]
static PrimitiveTypeCode Newtonsoft.Json.Utilities.ConvertUtils.GetTypeCode (Type t, out bool isEnum) inline static
Definition at line 24 of file ConvertUtils.cs.
        {
            PrimitiveTypeCode primitiveTypeCode;
            if (ConvertUtils.TypeCodeMap.TryGetValue(t, ref primitiveTypeCode))
            {
                isEnum = false;
                return primitiveTypeCode;
            }
            if (t.IsEnum())
            {
                isEnum = true;
                return ConvertUtils.GetTypeCode(Enum.GetUnderlyingType(t));
            }
            if (ReflectionUtils.IsNullableType(t))
            {
                Type underlyingType = Nullable.GetUnderlyingType(t);
                if (underlyingType.IsEnum())
                {
                    Type type = typeof(Nullable).MakeGenericType(new Type[] { Enum.GetUnderlyingType(underlyingType) });
                    isEnum = true;
                    return ConvertUtils.GetTypeCode(type);
                }
            }
            isEnum = false;
            return PrimitiveTypeCode.Object;
        }
References Newtonsoft.Json.Utilities.ConvertUtils.GetTypeCode(), System.Enum.GetUnderlyingType(), System.Nullable< T >.GetUnderlyingType(), System.Type.IsEnum, Newtonsoft.Json.Utilities.ReflectionUtils.IsNullableType(), System.Type.MakeGenericType(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and Newtonsoft.Json.Utilities.ConvertUtils.TypeCodeMap.