Terraria Decompiled: Newtonsoft.Json.Utilities.ConvertUtils.IsInteger
IsInteger()
static bool Newtonsoft.Json.Utilities.ConvertUtils.IsInteger (object value) inline static
Definition at line 431 of file ConvertUtils.cs.
        {
            switch (ConvertUtils.GetTypeCode(value.GetType()))
            {
            case PrimitiveTypeCode.SByte:
            case PrimitiveTypeCode.Int16:
            case PrimitiveTypeCode.UInt16:
            case PrimitiveTypeCode.Int32:
            case PrimitiveTypeCode.Byte:
            case PrimitiveTypeCode.UInt32:
            case PrimitiveTypeCode.Int64:
            case PrimitiveTypeCode.UInt64:
                return true;
            }
            return false;
        }
References Newtonsoft.Json.Utilities.ConvertUtils.GetTypeCode(), and System.value.
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(), Newtonsoft.Json.Utilities.ConvertUtils.TryConvertInternal(), and Newtonsoft.Json.Utilities.MiscellaneousUtils.ValueEquals().