Terraria Decompiled: Newtonsoft.Json.Utilities.ConvertUtils.TryConvertInternal
TryConvertInternal()
static ConvertUtils.ConvertResult Newtonsoft.Json.Utilities.ConvertUtils.TryConvertInternal (object initialValue, CultureInfo culture, Type targetType, out object value) inline static private
Definition at line 212 of file ConvertUtils.cs.
        {
            if (initialValue == null)
            {
                throw new ArgumentNullException("initialValue");
            }
            if (ReflectionUtils.IsNullableType(targetType))
            {
                targetType = Nullable.GetUnderlyingType(targetType);
            }
            Type type = initialValue.GetType();
            if (targetType == type)
            {
                value = initialValue;
                return ConvertUtils.ConvertResult.Success;
            }
            if (ConvertUtils.IsConvertible(initialValue.GetType()) && ConvertUtils.IsConvertible(targetType))
            {
                if (targetType.IsEnum())
                {
                    if (initialValue is string)
                    {
                        value = Enum.Parse(targetType, initialValue.ToString(), true);
                        return ConvertUtils.ConvertResult.Success;
                    }
                    if (ConvertUtils.IsInteger(initialValue))
                    {
                        value = Enum.ToObject(targetType, initialValue);
                        return ConvertUtils.ConvertResult.Success;
                    }
                }
                value = global::System.Convert.ChangeType(initialValue, targetType, culture);
                return ConvertUtils.ConvertResult.Success;
            }
            if (initialValue is DateTime && targetType == typeof(DateTimeOffset))
            {
                value = new DateTimeOffset((DateTime)initialValue);
                return ConvertUtils.ConvertResult.Success;
            }
            byte[] array = initialValue as byte[];
            if (array != null && targetType == typeof(Guid))
            {
                value = new Guid(array);
                return ConvertUtils.ConvertResult.Success;
            }
            if (initialValue is Guid && targetType == typeof(byte[]))
            {
                value = ((Guid)initialValue).ToByteArray();
                return ConvertUtils.ConvertResult.Success;
            }
            string text = initialValue as string;
            if (text != null)
            {
                if (targetType == typeof(Guid))
                {
                    value = new Guid(text);
                    return ConvertUtils.ConvertResult.Success;
                }
                if (targetType == typeof(Uri))
                {
                    value = new Uri(text, 0);
                    return ConvertUtils.ConvertResult.Success;
                }
                if (targetType == typeof(TimeSpan))
                {
                    value = ConvertUtils.ParseTimeSpan(text);
                    return ConvertUtils.ConvertResult.Success;
                }
                if (targetType == typeof(byte[]))
                {
                    value = global::System.Convert.FromBase64String(text);
                    return ConvertUtils.ConvertResult.Success;
                }
                if (targetType == typeof(Version))
                {
                    Version version;
                    if (ConvertUtils.VersionTryParse(text, out version))
                    {
                        value = version;
                        return ConvertUtils.ConvertResult.Success;
                    }
                    value = null;
                    return ConvertUtils.ConvertResult.NoValidConversion;
                }
                else if (typeof(Type).IsAssignableFrom(targetType))
                {
                    value = Type.GetType(text, true);
                    return ConvertUtils.ConvertResult.Success;
                }
            }
            if (targetType == typeof(BigInteger))
            {
                value = ConvertUtils.ToBigInteger(initialValue);
                return ConvertUtils.ConvertResult.Success;
            }
            if (initialValue is BigInteger)
            {
                value = ConvertUtils.FromBigInteger((BigInteger)initialValue, targetType);
                return ConvertUtils.ConvertResult.Success;
            }
            TypeConverter converter = TypeDescriptor.GetConverter(type);
            if (converter != null && converter.CanConvertTo(targetType))
            {
                value = converter.ConvertTo(null, culture, initialValue, targetType);
                return ConvertUtils.ConvertResult.Success;
            }
            TypeConverter converter2 = TypeDescriptor.GetConverter(targetType);
            if (converter2 != null && converter2.CanConvertFrom(type))
            {
                value = converter2.ConvertFrom(null, culture, initialValue);
                return ConvertUtils.ConvertResult.Success;
            }
            if (initialValue == DBNull.Value)
            {
                if (ReflectionUtils.IsNullable(targetType))
                {
                    value = ConvertUtils.EnsureTypeAssignable(null, type, targetType);
                    return ConvertUtils.ConvertResult.Success;
                }
                value = null;
                return ConvertUtils.ConvertResult.CannotConvertNull;
            }
            else
            {
                INullable nullable = initialValue as INullable;
                if (nullable != null)
                {
                    value = ConvertUtils.EnsureTypeAssignable(ConvertUtils.ToValue(nullable), type, targetType);
                    return ConvertUtils.ConvertResult.Success;
                }
                if (targetType.IsInterface() || targetType.IsGenericTypeDefinition() || targetType.IsAbstract())
                {
                    value = null;
                    return ConvertUtils.ConvertResult.NotInstantiableType;
                }
                value = null;
                return ConvertUtils.ConvertResult.NoValidConversion;
            }
        }
References System.array, Newtonsoft.Json.Utilities.BigInteger, System.converter, System.culture, Newtonsoft.Json.Utilities.DateTimeOffset, Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(), Newtonsoft.Json.Utilities.ConvertUtils.FromBigInteger(), System.Type.GetType(), System.Nullable< T >.GetUnderlyingType(), Newtonsoft.Json.Utilities.Guid, System.Type.IsAbstract, Newtonsoft.Json.Utilities.ConvertUtils.IsConvertible(), System.Type.IsEnum, System.Type.IsGenericTypeDefinition, Newtonsoft.Json.Utilities.ConvertUtils.IsInteger(), System.Type.IsInterface, Newtonsoft.Json.Utilities.ReflectionUtils.IsNullable(), Newtonsoft.Json.Utilities.ReflectionUtils.IsNullableType(), System.Enum.Parse(), Newtonsoft.Json.Utilities.ConvertUtils.ParseTimeSpan(), System.text, Newtonsoft.Json.Utilities.ConvertUtils.ToBigInteger(), System.Enum.ToObject(), Newtonsoft.Json.Utilities.ConvertUtils.ToValue(), Newtonsoft.Json.Utilities.Uri, System.DBNull.Value, System.value, and Newtonsoft.Json.Utilities.ConvertUtils.VersionTryParse().
Referenced by Newtonsoft.Json.Utilities.ConvertUtils.Convert(), and Newtonsoft.Json.Utilities.ConvertUtils.TryConvert().