Terraria Decompiled: Newtonsoft.Json.Utilities.ConvertUtils.ToValue
ToValue()
static object Newtonsoft.Json.Utilities.ConvertUtils.ToValue (INullable nullableValue) inline static
Definition at line 395 of file ConvertUtils.cs.
        {
            if (nullableValue == null)
            {
                return null;
            }
            if (nullableValue is SqlInt32)
            {
                return ConvertUtils.ToValue((SqlInt32)nullableValue);
            }
            if (nullableValue is SqlInt64)
            {
                return ConvertUtils.ToValue((SqlInt64)nullableValue);
            }
            if (nullableValue is SqlBoolean)
            {
                return ConvertUtils.ToValue((SqlBoolean)nullableValue);
            }
            if (nullableValue is SqlString)
            {
                return ConvertUtils.ToValue((SqlString)nullableValue);
            }
            if (nullableValue is SqlDateTime)
            {
                return ConvertUtils.ToValue((SqlDateTime)nullableValue);
            }
            throw new ArgumentException("Unsupported INullable type: {0}".FormatWith(CultureInfo.InvariantCulture, nullableValue.GetType()));
        }
References System.Globalization.CultureInfo.InvariantCulture, and Newtonsoft.Json.Utilities.ConvertUtils.ToValue().
Referenced by Newtonsoft.Json.Utilities.ConvertUtils.ToValue(), and Newtonsoft.Json.Utilities.ConvertUtils.TryConvertInternal().