Terraria Decompiled: System.Runtime.Remoting.Messaging.LogicalCallContext.Clone
Clone()
object System.Runtime.Remoting.Messaging.LogicalCallContext.Clone () inline
Implements System.ICloneable.
Definition at line 91 of file LogicalCallContext.cs.
        {
            LogicalCallContext logicalCallContext = new LogicalCallContext();
            if (this.m_RemotingData != null)
            {
                logicalCallContext.m_RemotingData = (CallContextRemotingData)this.m_RemotingData.Clone();
            }
            if (this.m_SecurityData != null)
            {
                logicalCallContext.m_SecurityData = (CallContextSecurityData)this.m_SecurityData.Clone();
            }
            if (this.m_HostContext != null)
            {
                logicalCallContext.m_HostContext = this.m_HostContext;
            }
            logicalCallContext.m_IsCorrelationMgr = this.m_IsCorrelationMgr;
            if (this.HasUserData)
            {
                IDictionaryEnumerator enumerator = this.m_Datastore.GetEnumerator();
                if (!this.m_IsCorrelationMgr)
                {
                    while (enumerator.MoveNext())
                    {
                        logicalCallContext.Datastore[(string)enumerator.Key] = enumerator.Value;
                    }
                }
                else
                {
                    while (enumerator.MoveNext())
                    {
                        string text = (string)enumerator.Key;
                        if (text.Equals("System.Diagnostics.Trace.CorrelationManagerSlot"))
{
                            logicalCallContext.Datastore[text] = ((ICloneable)enumerator.Value).Clone();
                        }
                        else
{
                            logicalCallContext.Datastore[text] = enumerator.Value;
                        }
                    }
                }
            }
            return logicalCallContext;
        }
References System.Collections.Hashtable.Clone(), System.Runtime.Remoting.Messaging.CallContextRemotingData.Clone(), System.Runtime.Remoting.Messaging.CallContextSecurityData.Clone(), System.Runtime.Remoting.Messaging.LogicalCallContext.Datastore, System.Collections.Hashtable.GetEnumerator(), System.Runtime.Remoting.Messaging.LogicalCallContext.HasUserData, System.Collections.IDictionaryEnumerator.Key, System.Runtime.Remoting.Messaging.LogicalCallContext.LogicalCallContext(), System.Runtime.Remoting.Messaging.LogicalCallContext.m_Datastore, System.Runtime.Remoting.Messaging.LogicalCallContext.m_HostContext, System.Runtime.Remoting.Messaging.LogicalCallContext.m_IsCorrelationMgr, System.Runtime.Remoting.Messaging.LogicalCallContext.m_RemotingData, System.Runtime.Remoting.Messaging.LogicalCallContext.m_SecurityData, System.Collections.IEnumerator.MoveNext(), System.text, and System.Collections.IDictionaryEnumerator.Value.
Referenced by System.Threading.ExecutionContext.Capture(), System.Runtime.Remoting.Messaging.LogicalCallContext.Reader.Clone(), System.Threading.ExecutionContext.CreateCopy(), and System.Threading.ExecutionContext.CreateMutableCopy().