Terraria Decompiled: System.Runtime.Remoting.Messaging.LogicalCallContext.GetObjectData
GetObjectData()
void System.Runtime.Remoting.Messaging.LogicalCallContext.GetObjectData (SerializationInfo info, StreamingContext context) inline
Implements System.Runtime.Serialization.ISerializable.
Definition at line 56 of file LogicalCallContext.cs.
        {
            if (info == null)
            {
                throw new ArgumentNullException("info");
            }
            info.SetType(LogicalCallContext.s_callContextType);
            if (this.m_RemotingData != null)
            {
                info.AddValue("__RemotingData", this.m_RemotingData);
            }
            if (this.m_SecurityData != null && context.State == StreamingContextStates.CrossAppDomain)
            {
                info.AddValue("__SecurityData", this.m_SecurityData);
            }
            if (this.m_HostContext != null)
            {
                info.AddValue("__HostContext", this.m_HostContext);
            }
            if (this.m_IsCorrelationMgr)
            {
                info.AddValue("__CorrelationMgrSlotPresent", this.m_IsCorrelationMgr);
            }
            if (this.HasUserData)
            {
                IDictionaryEnumerator enumerator = this.m_Datastore.GetEnumerator();
                while (enumerator.MoveNext())
                {
                    info.AddValue((string)enumerator.Key, enumerator.Value);
                }
            }
        }
References System.Runtime.Serialization.SerializationInfo.AddValue(), System.Collections.Hashtable.GetEnumerator(), System.Runtime.Remoting.Messaging.LogicalCallContext.HasUserData, System.info, System.Collections.IDictionaryEnumerator.Key, System.Runtime.Remoting.Messaging.LogicalCallContext.m_Datastore, System.Runtime.Remoting.Messaging.LogicalCallContext.m_HostContext, System.Runtime.Remoting.Messaging.LogicalCallContext.m_IsCorrelationMgr, System.Runtime.Remoting.Messaging.LogicalCallContext.m_RemotingData, System.Runtime.Remoting.Messaging.LogicalCallContext.m_SecurityData, System.Collections.IEnumerator.MoveNext(), System.Runtime.Remoting.Messaging.LogicalCallContext.s_callContextType, System.Runtime.Serialization.StreamingContext.State, and System.Collections.IDictionaryEnumerator.Value.