Terraria Decompiled: System.Runtime.Remoting.Messaging.LogicalCallContext.PropagateIncomingHeadersToCallContext
PropagateIncomingHeadersToCallContext()
void System.Runtime.Remoting.Messaging.LogicalCallContext.PropagateIncomingHeadersToCallContext (IMessage msg) inline package
Definition at line 351 of file LogicalCallContext.cs.
        {
            IInternalMessage internalMessage = msg as IInternalMessage;
            if (internalMessage != null && !internalMessage.HasProperties())
            {
                return;
            }
            IDictionaryEnumerator enumerator = msg.Properties.GetEnumerator();
            int num = 0;
            while (enumerator.MoveNext())
            {
                if (!((string)enumerator.Key).StartsWith("__", StringComparison.Ordinal) && enumerator.Value is Header)
                {
                    num++;
                }
            }
            Header[] array = null;
            if (num > 0)
            {
                array = new Header[num];
                num = 0;
                enumerator.Reset();
                while (enumerator.MoveNext())
                {
                    if (!((string)enumerator.Key).StartsWith("__", StringComparison.Ordinal))
                    {
                        Header header = enumerator.Value as Header;
                        if (header != null)
{
                            array[num++] = header;
                        }
                    }
                }
            }
            this._recvHeaders = array;
            this._sendHeaders = null;
        }
References System.array, System.Collections.IDictionary.GetEnumerator(), System.Runtime.Remoting.Messaging.IInternalMessage.HasProperties(), System.Collections.IDictionaryEnumerator.Key, System.Collections.IEnumerator.MoveNext(), System.Runtime.Remoting.Messaging.IMessage.Properties, System.Collections.IEnumerator.Reset(), and System.Collections.IDictionaryEnumerator.Value.