Terraria Decompiled: Newtonsoft.Json.Linq.JTokenWriter.WriteToken
WriteToken()
override void Newtonsoft.Json.Linq.JTokenWriter.WriteToken (JsonReader reader, bool writeChildren, bool writeDateConstructorAsDate, bool writeComments) inline package virtual
Reimplemented from Newtonsoft.Json.JsonWriter.
Definition at line 337 of file JTokenWriter.cs.
        {
            JTokenReader jtokenReader = reader as JTokenReader;
            if (jtokenReader == null || !writeChildren || !writeDateConstructorAsDate || !writeComments)
            {
                base.WriteToken(reader, writeChildren, writeDateConstructorAsDate, writeComments);
                return;
            }
            if (jtokenReader.TokenType == JsonToken.None && !jtokenReader.Read())
            {
                return;
            }
            JToken jtoken = jtokenReader.CurrentToken.CloneToken();
            if (this._parent != null)
            {
                this._parent.Add(jtoken);
                this._current = this._parent.Last;
                if (this._parent.Type == JTokenType.Property)
                {
                    this._parent = this._parent.Parent;
                    base.InternalWriteValue(JsonToken.Null);
                }
            }
            else
            {
                this._current = jtoken;
                if (this._token == null && this._value == null)
                {
                    this._token = jtoken as JContainer;
                    this._value = jtoken as JValue;
                }
            }
            jtokenReader.Skip();
        }
References Newtonsoft.Json.Linq.JTokenWriter._parent, Newtonsoft.Json.Linq.JTokenWriter._token, Newtonsoft.Json.Linq.JTokenWriter._value, Newtonsoft.Json.Linq.JContainer.Add(), Newtonsoft.Json.Linq.JToken.CloneToken(), Newtonsoft.Json.Linq.JTokenReader.CurrentToken, Newtonsoft.Json.Linq.JContainer.Last, Newtonsoft.Json.Linq.JToken.Parent, Newtonsoft.Json.Linq.JTokenReader.Read(), Newtonsoft.Json.JsonReader.Skip(), Newtonsoft.Json.JsonReader.TokenType, and Newtonsoft.Json.Linq.JToken.Type.
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateJObject(), and Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateJToken().