Terraria Decompiled: System.Buffers.ArrayPool.Shared
Shared
ArrayPool<T> System.Buffers.ArrayPool< T >.Shared = new TlsOverPerCoreLockedStacksArrayPool<T>() static get
Definition at line 11 of file ArrayPool.cs.
        {
            [CompilerGenerated]
            get
            {
                return ArrayPool<T>.<Shared>k__BackingField;
            }
        } = new TlsOverPerCoreLockedStacksArrayPool<T>();
Referenced by System.Buffers.ArrayMemoryPool< T >.ArrayMemoryPoolBuffer.ArrayMemoryPoolBuffer(), System.Security.Cryptography.HashAlgorithm.ComputeHash(), System.Text.ValueUtf8Converter.ConvertAndTerminateString(), System.IO.Stream.CopyTo(), System.IO.Stream.CopyToAsyncInternal(), System.Buffers.ArrayMemoryPool< T >.ArrayMemoryPoolBuffer.Dispose(), System.Collections.Generic.ValueListBuilder< T >.Dispose(), System.Text.ValueStringBuilder.Dispose(), System.Text.ValueUtf8Converter.Dispose(), System.TimeZoneInfo.EnumerateFilesRecursively(), System.IO.Enumeration.FileSystemEnumerator< TResult >.FileSystemEnumerator(), System.IO.Stream.FinishWriteAsync(), System.Security.Cryptography.Rfc2898DeriveBytes.Func(), System.IO.Stream.g__FinishReadAsync(), System.Security.Cryptography.RandomNumberGenerator.GetBytes(), System.Globalization.CompareInfo.GetIgnoreCaseHash(), System.Security.Cryptography.RandomNumberGenerator.GetNonZeroBytes(), System.Collections.Generic.ValueListBuilder< T >.Grow(), System.Text.ValueStringBuilder.Grow(), System.Security.Cryptography.HashAlgorithm.HashCore(), System.IO.Enumeration.FileSystemEnumerator< TResult >.InternalDispose(), System.IO.File.InternalReadAllBytesUnknownLengthAsync(), System.IO.File.InternalReadAllTextAsync(), System.IO.File.InternalWriteAllTextAsync(), System.IO.File.d__67.MoveNext(), System.IO.File.d__72.MoveNext(), System.IO.File.d__81.MoveNext(), System.IO.Stream.d__28.MoveNext(), System.IO.Stream.d__57.MoveNext(), System.IO.Stream.d.MoveNext(), System.IO.TextReader.d__14.MoveNext(), System.Security.Cryptography.CryptoStream.d__42.MoveNext(), System.Security.Cryptography.CryptoStream.d__49.MoveNext(), System.IO.Stream.Read(), System.IO.BinaryReader.Read(), System.IO.TextReader.Read(), System.IO.File.ReadAllBytesUnknownLength(), System.IO.Stream.ReadAsync(), System.Security.Cryptography.CryptoStream.ReadAsyncCore(), System.IO.TextReader.ReadBlock(), Interop.Sys.ReadLink(), System.IO.TextReader.ReadToEndAsync(), System.Security.Cryptography.DSA.TryHashData(), System.Security.Cryptography.RSA.TryHashData(), System.Security.Cryptography.DSA.VerifyData(), System.Security.Cryptography.RSA.VerifyData(), System.IO.Stream.Write(), System.IO.TextWriter.Write(), System.IO.Stream.WriteAsync(), System.Security.Cryptography.CryptoStream.WriteAsyncCore(), and System.IO.TextWriter.WriteLine().