Terraria Decompiled: NVorbis.Residue0.Decode
Decode()
virtual void NVorbis.Residue0.Decode (IPacket packet, bool[] doNotDecodeChannel, int blockSize, float buffer[][]) inline virtual
Implements NVorbis.Contracts.IResidue.
Reimplemented in NVorbis.Residue2.
Definition at line 104 of file Residue0.cs.
        {
            int num = ((this._end < blockSize / 2) ? this._end : (blockSize / 2)) - this._begin;
            if (num > 0 && Array.IndexOf<bool>(doNotDecodeChannel, false) != -1)
            {
                int num2 = num / this._partitionSize;
                int num3 = (num2 + this._classBook.Dimensions - 1) / this._classBook.Dimensions;
                int[,][] array = new int[this._channels, num3][];
                for (int i = 0; i < this._maxStages; i++)
                {
                    int j = 0;
                    int num4 = 0;
                    while (j < num2)
                    {
                        if (i == 0)
{
                            for (int k = 0; k < this._channels; k++)
{
                                int num5 = this._classBook.DecodeScalar(packet);
                                if (num5 < 0 || num5 >= this._decodeMap.Length)
{
                                    j = num2;
                                    i = this._maxStages;
                                    break;
                                }
                                array[k, num4] = this._decodeMap[num5];
                            }
                        }
                        int num6 = 0;
                        while (j < num2 && num6 < this._classBook.Dimensions)
{
                            int num7 = this._begin + j * this._partitionSize;
                            for (int l = 0; l < this._channels; l++)
{
                                int num8 = array[l, num4][num6];
                                if ((this._cascade[num8] & (1 << i)) != 0)
{
                                    ICodebook codebook = this._books[num8][i];
                                    if (codebook != null && this.WriteVectors(codebook, packet, buffer, l, num7, this._partitionSize))
{
                                        j = num2;
                                        i = this._maxStages;
                                        break;
                                    }
                                }
                            }
                            num6++;
                            j++;
                        }
                        num4++;
                    }
                }
            }
        }
References NVorbis.Residue0._begin, NVorbis.Residue0._books, NVorbis.Residue0._cascade, NVorbis.Residue0._channels, NVorbis.Residue0._classBook, NVorbis.Residue0._decodeMap, NVorbis.Residue0._end, NVorbis.Residue0._maxStages, NVorbis.Residue0._partitionSize, System.array, NVorbis.Contracts.ICodebook.DecodeScalar(), NVorbis.Contracts.ICodebook.Dimensions, System.Array.IndexOf(), and NVorbis.Residue0.WriteVectors().