Terraria Decompiled: NVorbis.Residue0.Init
Init()
virtual void NVorbis.Residue0.Init (IPacket packet, int channels, ICodebook[] codebooks) inline virtual
Implements NVorbis.Contracts.IResidue.
Reimplemented in NVorbis.Residue2.
Definition at line 23 of file Residue0.cs.
        {
            this._begin = (int)packet.ReadBits(24);
            this._end = (int)packet.ReadBits(24);
            this._partitionSize = (int)packet.ReadBits(24) + 1;
            this._classifications = (int)packet.ReadBits(6) + 1;
            this._classBook = codebooks[(int)packet.ReadBits(8)];
            this._cascade = new int[this._classifications];
            int num = 0;
            for (int i = 0; i < this._classifications; i++)
            {
                int num2 = (int)packet.ReadBits(3);
                if (packet.ReadBit())
                {
                    this._cascade[i] = ((int)packet.ReadBits(5) << 3) | num2;
                }
                else
                {
                    this._cascade[i] = num2;
                }
                num += Residue0.icount(this._cascade[i]);
            }
            int[] array = new int[num];
            for (int j = 0; j < num; j++)
            {
                array[j] = (int)packet.ReadBits(8);
                if (codebooks[array[j]].MapType == 0)
                {
                    throw new InvalidDataException();
                }
            }
            int entries = this._classBook.Entries;
            int k = this._classBook.Dimensions;
            int num3 = 1;
            while (k > 0)
            {
                num3 *= this._classifications;
                if (num3 > entries)
                {
                    throw new InvalidDataException();
                }
                k--;
            }
            this._books = new ICodebook[this._classifications][];
            num = 0;
            int num4 = 0;
            for (int l = 0; l < this._classifications; l++)
            {
                int num5 = Utils.ilog(this._cascade[l]);
                this._books[l] = new ICodebook[num5];
                if (num5 > 0)
                {
                    num4 = Math.Max(num4, num5);
                    for (int m = 0; m < num5; m++)
                    {
                        if ((this._cascade[l] & (1 << m)) > 0)
{
                            this._books[l][m] = codebooks[array[num++]];
                        }
                    }
                }
            }
            this._maxStages = num4;
            this._decodeMap = new int[num3][];
            for (int n = 0; n < num3; n++)
            {
                int num6 = n;
                int num7 = num3 / this._classifications;
                this._decodeMap[n] = new int[this._classBook.Dimensions];
                for (int num8 = 0; num8 < this._classBook.Dimensions; num8++)
                {
                    int num9 = num6 / num7;
                    num6 -= num9 * num7;
                    num7 /= this._classifications;
                    this._decodeMap[n][num8] = num9;
                }
            }
            this._channels = channels;
        }
References NVorbis.Residue0._books, NVorbis.Residue0._cascade, NVorbis.Residue0._classBook, NVorbis.Residue0._classifications, NVorbis.Residue0._decodeMap, System.array, NVorbis.Contracts.ICodebook.Dimensions, NVorbis.Contracts.ICodebook.Entries, NVorbis.Residue0.icount(), NVorbis.Utils.ilog(), int, System.Math.Max(), and NVorbis.Contracts.IPacket.ReadBits().