Terraria Decompiled: ReLogic.Content.Sources.FileSystemContentSource.Refresh
Refresh()
void ReLogic.Content.Sources.FileSystemContentSource.Refresh () inline
Implements ReLogic.Content.Sources.IContentSource.
Definition at line 107 of file FileSystemContentSource.cs.
        {
            this._nameToAbsolutePath.Clear();
            if (!Directory.Exists(this._basePath))
            {
                return;
            }
            string[] files = Directory.GetFiles(this._basePath, "*", 1);
            for (int i = 0; i < files.Length; i++)
            {
                string fullPath = Path.GetFullPath(files[i]);
                string text = Path.GetExtension(fullPath) ?? "";
                string text2 = fullPath.Substring(this._basePath.Length, fullPath.Length - text.Length - this._basePath.Length);
                text2 = AssetPathHelper.CleanPath(text2);
                this._nameToAbsolutePath[text2] = fullPath;
            }
        }
References ReLogic.Content.Sources.FileSystemContentSource._basePath, ReLogic.Content.Sources.FileSystemContentSource._nameToAbsolutePath, ReLogic.Content.AssetPathHelper.CleanPath(), System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.IO.Directory.Exists(), System.IO.Path.GetExtension(), System.IO.Directory.GetFiles(), System.IO.Path.GetFullPath(), and System.text.
Referenced by ReLogic.Content.Sources.FileSystemContentSource.FileSystemContentSource().