Terraria Decompiled: ReLogic.Content.Sources.FileSystemContentSource.OpenStream
OpenStream()
Stream ReLogic.Content.Sources.FileSystemContentSource.OpenStream (string assetName) inline
Implements ReLogic.Content.Sources.IContentSource.
Definition at line 83 of file FileSystemContentSource.cs.
        {
            string text;
            if (!this._nameToAbsolutePath.TryGetValue(assetName, ref text))
            {
                throw AssetLoadException.FromMissingAsset(assetName, null);
            }
            if (!File.Exists(text))
            {
                throw AssetLoadException.FromMissingAsset(assetName, null);
            }
            Stream stream;
            try
            {
                stream = File.OpenRead(text);
            }
            catch (Exception ex)
            {
                throw AssetLoadException.FromMissingAsset(assetName, ex);
            }
            return stream;
        }
References ReLogic.Content.Sources.FileSystemContentSource._nameToAbsolutePath, System.IO.File.Exists(), ReLogic.Content.AssetLoadException.FromMissingAsset(), System.IO.File.OpenRead(), System.text, and System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue().