Terraria Decompiled: Mono.Security.Cryptography.PKCS1.MGF1
MGF1()
static byte[] Mono.Security.Cryptography.PKCS1.MGF1 (HashAlgorithm hash, byte[] mgfSeed, int maskLen) inline static
Definition at line 340 of file PKCS1.cs.
        {
            if (maskLen < 0)
            {
                throw new OverflowException();
            }
            int num = mgfSeed.Length;
            int num2 = hash.HashSize >> 3;
            int num3 = maskLen / num2;
            if (maskLen % num2 != 0)
            {
                num3++;
            }
            byte[] array = new byte[num3 * num2];
            byte[] array2 = new byte[num + 4];
            int num4 = 0;
            for (int i = 0; i < num3; i++)
            {
                Array array3 = PKCS1.I2OSP(i, 4);
                Buffer.BlockCopy(mgfSeed, 0, array2, 0, num);
                Buffer.BlockCopy(array3, 0, array2, num, 4);
                Buffer.BlockCopy(hash.ComputeHash(array2), 0, array, num4, num2);
                num4 += num2;
            }
            byte[] array4 = new byte[maskLen];
            Buffer.BlockCopy(array, 0, array4, 0, maskLen);
            return array4;
        }
References System.array, System.Buffer.BlockCopy(), System.Security.Cryptography.HashAlgorithm.ComputeHash(), and Mono.Security.Cryptography.PKCS1.I2OSP().
Referenced by Mono.Security.Cryptography.PKCS1.Decrypt_OAEP(), Mono.Security.Cryptography.PKCS1.Encrypt_OAEP(), and System.Security.Cryptography.PKCS1MaskGenerationMethod.GenerateMask().