Terraria Decompiled: Mono.Security.Cryptography.PKCS1.Encode_v15
Encode_v15()
static byte[] Mono.Security.Cryptography.PKCS1.Encode_v15 (HashAlgorithm hash, byte[] hashValue, int emLength) inline static
Definition at line 304 of file PKCS1.cs.
        {
            if (hashValue.Length != hash.HashSize >> 3)
            {
                throw new CryptographicException("bad hash length for " + hash.ToString());
            }
            string text = CryptoConfig.MapNameToOID(hash.ToString());
            byte[] array;
            if (text != null)
            {
                ASN1 asn = new ASN1(48);
                asn.Add(new ASN1(CryptoConfig.EncodeOID(text)));
                asn.Add(new ASN1(5));
                ASN1 asn2 = new ASN1(4, hashValue);
                ASN1 asn3 = new ASN1(48);
                asn3.Add(asn);
                asn3.Add(asn2);
                array = asn3.GetBytes();
            }
            else
            {
                array = hashValue;
            }
            Buffer.BlockCopy(hashValue, 0, array, array.Length - hashValue.Length, hashValue.Length);
            int num = Math.Max(8, emLength - array.Length - 3);
            byte[] array2 = new byte[num + array.Length + 3];
            array2[1] = 1;
            for (int i = 2; i < num + 2; i++)
            {
                array2[i] = byte.MaxValue;
            }
            Buffer.BlockCopy(array, 0, array2, num + 3, array.Length);
            return array2;
        }
References Mono.Security.ASN1.Add(), System.array, System.Buffer.BlockCopy(), System.Security.Cryptography.CryptoConfig.EncodeOID(), Mono.Security.ASN1.GetBytes(), System.Security.Cryptography.HashAlgorithm.HashSize, System.Security.Cryptography.CryptoConfig.MapNameToOID(), System.Math.Max(), and System.text.
Referenced by Mono.Security.Cryptography.PKCS1.Sign_v15(), and Mono.Security.Cryptography.PKCS1.Verify_v15().