Terraria Decompiled: Mono.Security.Cryptography.PKCS1.Encrypt_OAEP
Encrypt_OAEP()
static byte[] Mono.Security.Cryptography.PKCS1.Encrypt_OAEP (RSA rsa, HashAlgorithm hash, RandomNumberGenerator rng, byte[] M) inline static
Definition at line 122 of file PKCS1.cs.
        {
            int num = rsa.KeySize / 8;
            int num2 = hash.HashSize / 8;
            if (M.Length > num - 2 * num2 - 2)
            {
                throw new CryptographicException("message too long");
            }
            byte[] emptyHash = PKCS1.GetEmptyHash(hash);
            int num3 = num - M.Length - 2 * num2 - 2;
            byte[] array = new byte[emptyHash.Length + num3 + 1 + M.Length];
            Buffer.BlockCopy(emptyHash, 0, array, 0, emptyHash.Length);
            array[emptyHash.Length + num3] = 1;
            Buffer.BlockCopy(M, 0, array, array.Length - M.Length, M.Length);
            byte[] array2 = new byte[num2];
            rng.GetBytes(array2);
            byte[] array3 = PKCS1.MGF1(hash, array2, num - num2 - 1);
            byte[] array4 = PKCS1.xor(array, array3);
            byte[] array5 = PKCS1.MGF1(hash, array4, num2);
            byte[] array6 = PKCS1.xor(array2, array5);
            byte[] array7 = new byte[array6.Length + array4.Length + 1];
            Buffer.BlockCopy(array6, 0, array7, 1, array6.Length);
            Buffer.BlockCopy(array4, 0, array7, array6.Length + 1, array4.Length);
            byte[] array8 = PKCS1.OS2IP(array7);
            return PKCS1.I2OSP(PKCS1.RSAEP(rsa, array8), num);
        }
References System.array, System.Buffer.BlockCopy(), System.Security.Cryptography.RandomNumberGenerator.GetBytes(), Mono.Security.Cryptography.PKCS1.GetEmptyHash(), Mono.Security.Cryptography.PKCS1.I2OSP(), System.M, Mono.Security.Cryptography.PKCS1.MGF1(), Mono.Security.Cryptography.PKCS1.OS2IP(), Mono.Security.Cryptography.PKCS1.RSAEP(), and Mono.Security.Cryptography.PKCS1.xor().
Referenced by System.Security.Cryptography.Utils.RsaOaepEncrypt().