Terraria Decompiled: Mono.Security.Cryptography.PKCS1.Decrypt_OAEP
Decrypt_OAEP()
static byte[] Mono.Security.Cryptography.PKCS1.Decrypt_OAEP (RSA rsa, HashAlgorithm hash, byte[] C) inline static
Definition at line 150 of file PKCS1.cs.
        {
            int num = rsa.KeySize / 8;
            int num2 = hash.HashSize / 8;
            if (num < 2 * num2 + 2 || C.Length != num)
            {
                throw new CryptographicException("decryption error");
            }
            byte[] array = PKCS1.OS2IP(C);
            byte[] array2 = PKCS1.I2OSP(PKCS1.RSADP(rsa, array), num);
            byte[] array3 = new byte[num2];
            Buffer.BlockCopy(array2, 1, array3, 0, array3.Length);
            byte[] array4 = new byte[num - num2 - 1];
            Buffer.BlockCopy(array2, array2.Length - array4.Length, array4, 0, array4.Length);
            byte[] array5 = PKCS1.MGF1(hash, array4, num2);
            byte[] array6 = PKCS1.xor(array3, array5);
            byte[] array7 = PKCS1.MGF1(hash, array6, num - num2 - 1);
            byte[] array8 = PKCS1.xor(array4, array7);
            byte[] emptyHash = PKCS1.GetEmptyHash(hash);
            byte[] array9 = new byte[emptyHash.Length];
            Buffer.BlockCopy(array8, 0, array9, 0, array9.Length);
            bool flag = PKCS1.Compare(emptyHash, array9);
            int num3 = emptyHash.Length;
            while (array8[num3] == 0)
            {
                num3++;
            }
            int num4 = array8.Length - num3 - 1;
            byte[] array10 = new byte[num4];
            Buffer.BlockCopy(array8, num3 + 1, array10, 0, num4);
            if (array2[0] != 0 || !flag || array8[num3] != 1)
            {
                return null;
            }
            return array10;
        }
References System.array, System.Buffer.BlockCopy(), System.C, Mono.Security.Cryptography.PKCS1.Compare(), Mono.Security.Cryptography.PKCS1.GetEmptyHash(), Mono.Security.Cryptography.PKCS1.I2OSP(), Mono.Security.Cryptography.PKCS1.MGF1(), Mono.Security.Cryptography.PKCS1.OS2IP(), Mono.Security.Cryptography.PKCS1.RSADP(), and Mono.Security.Cryptography.PKCS1.xor().
Referenced by System.Security.Cryptography.Utils.RsaOaepDecrypt().