Terraria Decompiled: Mono.Security.Cryptography.PKCS1.Sign_v15
Sign_v15() [1/2]
static byte[] Mono.Security.Cryptography.PKCS1.Sign_v15 (RSA rsa, HashAlgorithm hash, byte[] hashValue) inline static
Definition at line 236 of file PKCS1.cs.
        {
            int num = rsa.KeySize >> 3;
            byte[] array = PKCS1.OS2IP(PKCS1.Encode_v15(hash, hashValue, num));
            return PKCS1.I2OSP(PKCS1.RSASP1(rsa, array), num);
        }
References System.array, Mono.Security.Cryptography.PKCS1.Encode_v15(), Mono.Security.Cryptography.PKCS1.I2OSP(), Mono.Security.Cryptography.PKCS1.OS2IP(), and Mono.Security.Cryptography.PKCS1.RSASP1().
Referenced by System.Security.Cryptography.RSAPKCS1SignatureFormatter.CreateSignature(), Mono.Security.Cryptography.PKCS1.Sign_v15(), System.Security.Cryptography.RSACryptoServiceProvider.SignData(), System.Security.Cryptography.RSACryptoServiceProvider.SignData(), System.Security.Cryptography.RSACryptoServiceProvider.SignHash(), and System.Security.Cryptography.RSACryptoServiceProvider.SignHash().