Terraria Decompiled: Mono.Security.Cryptography.PKCS1.I2OSP
I2OSP() [2/2]
static byte[] Mono.Security.Cryptography.PKCS1.I2OSP (int x, int size) inline static
Definition at line 65 of file PKCS1.cs.
        {
            byte[] bytes = BitConverterLE.GetBytes(x);
            Array.Reverse<byte>(bytes, 0, bytes.Length);
            return PKCS1.I2OSP(bytes, size);
        }
References Mono.Security.BitConverterLE.GetBytes(), Mono.Security.Cryptography.PKCS1.I2OSP(), and System.Array.Reverse().
Referenced by Mono.Security.Cryptography.PKCS1.Decrypt_OAEP(), Mono.Security.Cryptography.PKCS1.Decrypt_v15(), Mono.Security.Cryptography.PKCS1.Encrypt_OAEP(), Mono.Security.Cryptography.PKCS1.Encrypt_v15(), Mono.Security.Cryptography.PKCS1.I2OSP(), Mono.Security.Cryptography.PKCS1.MGF1(), Mono.Security.Cryptography.PKCS1.Sign_v15(), and Mono.Security.Cryptography.PKCS1.Verify_v15().