Terraria Decompiled: Newtonsoft.Json.Utilities.StringBuffer.StringBuffer
StringBuffer() [1/2]
Newtonsoft.Json.Utilities.StringBuffer.StringBuffer (IArrayPool< char > bufferPool, int initalSize) inline
Definition at line 34 of file StringBuffer.cs.
        {
            this = new StringBuffer(BufferUtils.RentBuffer(bufferPool, initalSize));
        }
References Newtonsoft.Json.Utilities.BufferUtils.RentBuffer(), and Newtonsoft.Json.Utilities.StringBuffer.StringBuffer().
Referenced by Newtonsoft.Json.Utilities.StringBuffer.StringBuffer().