var dir_b8b3b00dc3ec564510d15ead4fe89e47 =
[
    [ "Concurrent", "dir_7923412276ff43d122bdfbd032e4e90d.html", "dir_7923412276ff43d122bdfbd032e4e90d" ],
    [ "Generic", "dir_b1ede291d207aac6de4139064eaf14e3.html", "dir_b1ede291d207aac6de4139064eaf14e3" ],
    [ "ObjectModel", "dir_d528b4b4f8823628be6642fdad2d0a9f.html", "dir_d528b4b4f8823628be6642fdad2d0a9f" ],
    [ "ArrayList.cs", "df/d27/ArrayList_8cs.html", "df/d27/ArrayList_8cs" ],
    [ "BitArray.cs", "d1/d9e/BitArray_8cs.html", "d1/d9e/BitArray_8cs" ],
    [ "CaseInsensitiveComparer.cs", "d6/dd4/CaseInsensitiveComparer_8cs.html", "d6/dd4/CaseInsensitiveComparer_8cs" ],
    [ "CaseInsensitiveHashCodeProvider.cs", "d3/d36/CaseInsensitiveHashCodeProvider_8cs.html", "d3/d36/CaseInsensitiveHashCodeProvider_8cs" ],
    [ "CollectionBase.cs", "de/df9/CollectionBase_8cs.html", "de/df9/CollectionBase_8cs" ],
    [ "Comparer.cs", "db/de3/Comparer_8cs.html", "db/de3/Comparer_8cs" ],
    [ "CompatibleComparer.cs", "d1/dac/CompatibleComparer_8cs.html", "d1/dac/CompatibleComparer_8cs" ],
    [ "DictionaryBase.cs", "db/d70/DictionaryBase_8cs.html", "db/d70/DictionaryBase_8cs" ],
    [ "DictionaryEntry.cs", "db/d7b/DictionaryEntry_8cs.html", "db/d7b/DictionaryEntry_8cs" ],
    [ "EmptyReadOnlyDictionaryInternal.cs", "d0/dc5/EmptyReadOnlyDictionaryInternal_8cs.html", "d0/dc5/EmptyReadOnlyDictionaryInternal_8cs" ],
    [ "HashHelpers.cs", "dd/d0b/Collections_2HashHelpers_8cs.html", "dd/d0b/Collections_2HashHelpers_8cs" ],
    [ "Hashtable.cs", "d8/d2f/Hashtable_8cs.html", "d8/d2f/Hashtable_8cs" ],
    [ "ICollection.cs", "d4/db8/ICollection_8cs.html", "d4/db8/ICollection_8cs" ],
    [ "IComparer.cs", "d0/dce/IComparer_8cs.html", "d0/dce/IComparer_8cs" ],
    [ "IDictionary.cs", "d1/d5a/IDictionary_8cs.html", "d1/d5a/IDictionary_8cs" ],
    [ "IDictionaryEnumerator.cs", "dd/d8d/IDictionaryEnumerator_8cs.html", "dd/d8d/IDictionaryEnumerator_8cs" ],
    [ "IEnumerable.cs", "df/d8e/Collections_2IEnumerable_8cs.html", "df/d8e/Collections_2IEnumerable_8cs" ],
    [ "IEnumerator.cs", "d6/dfc/Collections_2IEnumerator_8cs.html", "d6/dfc/Collections_2IEnumerator_8cs" ],
    [ "IEqualityComparer.cs", "d1/de3/IEqualityComparer_8cs.html", "d1/de3/IEqualityComparer_8cs" ],
    [ "IHashCodeProvider.cs", "da/d0c/IHashCodeProvider_8cs.html", "da/d0c/IHashCodeProvider_8cs" ],
    [ "IList.cs", "dd/d71/IList_8cs.html", "dd/d71/IList_8cs" ],
    [ "IStructuralComparable.cs", "d4/d4c/IStructuralComparable_8cs.html", "d4/d4c/IStructuralComparable_8cs" ],
    [ "IStructuralEquatable.cs", "d4/d29/IStructuralEquatable_8cs.html", "d4/d29/IStructuralEquatable_8cs" ],
    [ "KeyValuePairs.cs", "d7/d29/KeyValuePairs_8cs.html", "d7/d29/KeyValuePairs_8cs" ],
    [ "ListDictionaryInternal.cs", "d1/d66/ListDictionaryInternal_8cs.html", "d1/d66/ListDictionaryInternal_8cs" ],
    [ "Queue.cs", "d9/d9f/Queue_8cs.html", "d9/d9f/Queue_8cs" ],
    [ "ReadOnlyCollectionBase.cs", "d4/d72/ReadOnlyCollectionBase_8cs.html", "d4/d72/ReadOnlyCollectionBase_8cs" ],
    [ "SortedList.cs", "d3/d81/SortedList_8cs.html", "d3/d81/SortedList_8cs" ],
    [ "Stack.cs", "d1/d88/Stack_8cs.html", "d1/d88/Stack_8cs" ],
    [ "StructuralComparer.cs", "da/d9e/StructuralComparer_8cs.html", "da/d9e/StructuralComparer_8cs" ],
    [ "StructuralComparisons.cs", "d7/da9/StructuralComparisons_8cs.html", "d7/da9/StructuralComparisons_8cs" ],
    [ "StructuralEqualityComparer.cs", "d3/daf/StructuralEqualityComparer_8cs.html", "d3/daf/StructuralEqualityComparer_8cs" ]
];