var dir_3c13e971f2aa187d09ad22076d7f2c97 =
[
    [ "Album.cs", "da/d25/Album_8cs.html", "da/d25/Album_8cs" ],
    [ "AlbumCollection.cs", "df/d29/AlbumCollection_8cs.html", "df/d29/AlbumCollection_8cs" ],
    [ "Artist.cs", "d2/dcb/Artist_8cs.html", "d2/dcb/Artist_8cs" ],
    [ "ArtistCollection.cs", "de/de6/ArtistCollection_8cs.html", "de/de6/ArtistCollection_8cs" ],
    [ "BaseYUVPlayer.cs", "d3/d4c/BaseYUVPlayer_8cs.html", "d3/d4c/BaseYUVPlayer_8cs" ],
    [ "Genre.cs", "d4/d0b/Genre_8cs.html", "d4/d0b/Genre_8cs" ],
    [ "GenreCollection.cs", "df/da8/GenreCollection_8cs.html", "df/da8/GenreCollection_8cs" ],
    [ "IVideoPlayerCodec.cs", "d6/dba/IVideoPlayerCodec_8cs.html", "d6/dba/IVideoPlayerCodec_8cs" ],
    [ "MediaLibrary.cs", "dd/d7c/MediaLibrary_8cs.html", "dd/d7c/MediaLibrary_8cs" ],
    [ "MediaPlayer.cs", "d0/da0/MediaPlayer_8cs.html", "d0/da0/MediaPlayer_8cs" ],
    [ "MediaQueue.cs", "d3/d57/MediaQueue_8cs.html", "d3/d57/MediaQueue_8cs" ],
    [ "MediaSource.cs", "d2/de9/MediaSource_8cs.html", "d2/de9/MediaSource_8cs" ],
    [ "MediaSourceType.cs", "d6/d7c/MediaSourceType_8cs.html", "d6/d7c/MediaSourceType_8cs" ],
    [ "MediaState.cs", "d2/d53/MediaState_8cs.html", "d2/d53/MediaState_8cs" ],
    [ "Picture.cs", "db/d22/Picture_8cs.html", "db/d22/Picture_8cs" ],
    [ "PictureAlbum.cs", "d8/d4d/PictureAlbum_8cs.html", "d8/d4d/PictureAlbum_8cs" ],
    [ "PictureAlbumCollection.cs", "d1/d7b/PictureAlbumCollection_8cs.html", "d1/d7b/PictureAlbumCollection_8cs" ],
    [ "PictureCollection.cs", "d5/db8/PictureCollection_8cs.html", "d5/db8/PictureCollection_8cs" ],
    [ "Playlist.cs", "d2/dff/Playlist_8cs.html", "d2/dff/Playlist_8cs" ],
    [ "PlaylistCollection.cs", "d1/d04/PlaylistCollection_8cs.html", "d1/d04/PlaylistCollection_8cs" ],
    [ "Song.cs", "d8/d80/Song_8cs.html", "d8/d80/Song_8cs" ],
    [ "SongCollection.cs", "db/df6/SongCollection_8cs.html", "db/df6/SongCollection_8cs" ],
    [ "Video.cs", "d7/dda/Video_8cs.html", "d7/dda/Video_8cs" ],
    [ "VideoPlayer.cs", "de/dbe/VideoPlayer_8cs.html", "de/dbe/VideoPlayer_8cs" ],
    [ "VideoPlayerAV1.cs", "d4/d5a/VideoPlayerAV1_8cs.html", "d4/d5a/VideoPlayerAV1_8cs" ],
    [ "VideoPlayerTheora.cs", "dc/d0e/VideoPlayerTheora_8cs.html", "dc/d0e/VideoPlayerTheora_8cs" ],
    [ "VideoSoundtrackType.cs", "dd/daa/VideoSoundtrackType_8cs.html", "dd/daa/VideoSoundtrackType_8cs" ],
    [ "VisualizationData.cs", "db/dae/VisualizationData_8cs.html", "db/dae/VisualizationData_8cs" ]
];