var dir_077d6cc828b711695495854d76d93485 =
[
    [ "Binary", "dir_4a54e7d5ce6fda93453208df481efcfb.html", "dir_4a54e7d5ce6fda93453208df481efcfb" ],
    [ "Text", "dir_7905a873e190014d8f3378bcb373945d.html", "dir_7905a873e190014d8f3378bcb373945d" ],
    [ "ArrayBufferWriter.cs", "d3/db5/ArrayBufferWriter_8cs.html", "d3/db5/ArrayBufferWriter_8cs" ],
    [ "ArrayMemoryPool.cs", "dd/dd6/ArrayMemoryPool_8cs.html", "dd/dd6/ArrayMemoryPool_8cs" ],
    [ "ArrayPool.cs", "d9/d24/ArrayPool_8cs.html", "d9/d24/ArrayPool_8cs" ],
    [ "ArrayPoolEventSource.cs", "d4/dcd/ArrayPoolEventSource_8cs.html", "d4/dcd/ArrayPoolEventSource_8cs" ],
    [ "BuffersExtensions.cs", "d0/d21/BuffersExtensions_8cs.html", "d0/d21/BuffersExtensions_8cs" ],
    [ "ConfigurableArrayPool.cs", "dd/d97/ConfigurableArrayPool_8cs.html", "dd/d97/ConfigurableArrayPool_8cs" ],
    [ "IBufferWriter.cs", "d8/d67/IBufferWriter_8cs.html", "d8/d67/IBufferWriter_8cs" ],
    [ "IMemoryOwner.cs", "d1/df6/IMemoryOwner_8cs.html", "d1/df6/IMemoryOwner_8cs" ],
    [ "IPinnable.cs", "d3/da6/IPinnable_8cs.html", "d3/da6/IPinnable_8cs" ],
    [ "MemoryHandle.cs", "d6/ddf/MemoryHandle_8cs.html", "d6/ddf/MemoryHandle_8cs" ],
    [ "MemoryManager.cs", "d4/d6a/MemoryManager_8cs.html", "d4/d6a/MemoryManager_8cs" ],
    [ "MemoryPool.cs", "de/d51/MemoryPool_8cs.html", "de/d51/MemoryPool_8cs" ],
    [ "OperationStatus.cs", "d7/d51/OperationStatus_8cs.html", "d7/d51/OperationStatus_8cs" ],
    [ "ReadOnlySequence.2.cs", "de/d97/ReadOnlySequence_82_8cs.html", "de/d97/ReadOnlySequence_82_8cs" ],
    [ "ReadOnlySequence.cs", "d3/d09/ReadOnlySequence_8cs.html", "d3/d09/ReadOnlySequence_8cs" ],
    [ "ReadOnlySequenceDebugView.cs", "da/dc7/ReadOnlySequenceDebugView_8cs.html", "da/dc7/ReadOnlySequenceDebugView_8cs" ],
    [ "ReadOnlySequenceSegment.cs", "d6/d6c/ReadOnlySequenceSegment_8cs.html", "d6/d6c/ReadOnlySequenceSegment_8cs" ],
    [ "ReadOnlySpanAction.cs", "d7/dfa/ReadOnlySpanAction_8cs.html", "d7/dfa/ReadOnlySpanAction_8cs" ],
    [ "SequenceReader.cs", "d8/d31/SequenceReader_8cs.html", "d8/d31/SequenceReader_8cs" ],
    [ "SequenceReaderExtensions.cs", "d9/d5e/SequenceReaderExtensions_8cs.html", "d9/d5e/SequenceReaderExtensions_8cs" ],
    [ "SpanAction.cs", "d5/d8a/SpanAction_8cs.html", "d5/d8a/SpanAction_8cs" ],
    [ "StandardFormat.cs", "dd/d99/StandardFormat_8cs.html", "dd/d99/StandardFormat_8cs" ],
    [ "TlsOverPerCoreLockedStacksArrayPool.cs", "d8/d01/TlsOverPerCoreLockedStacksArrayPool_8cs.html", "d8/d01/TlsOverPerCoreLockedStacksArrayPool_8cs" ],
    [ "Utilities.cs", "d3/d9a/Utilities_8cs.html", "d3/d9a/Utilities_8cs" ]
];