Terraria Decompiled: System.Reflection.Emit.MethodBuilder.RejectIfCreated
RejectIfCreated()
void System.Reflection.Emit.MethodBuilder.RejectIfCreated () inline private
Definition at line 733 of file MethodBuilder.cs.
        {
            if (this.type.is_created)
            {
                throw new InvalidOperationException("Type definition of the method is complete.");
            }
        }
References System.Reflection.Emit.TypeBuilder.is_created, and System.Reflection.Emit.MethodBuilder.type.
Referenced by System.Reflection.Emit.MethodBuilder.AddDeclarativeSecurity(), System.Reflection.Emit.MethodBuilder.DefineParameter(), System.Reflection.Emit.MethodBuilder.SetImplementationFlags(), System.Reflection.Emit.MethodBuilder.SetMarshal(), and System.Reflection.Emit.MethodBuilder.SetSymCustomAttribute().