Terraria Decompiled: System.Reflection.Emit.MethodBuilder.MethodBuilder
MethodBuilder() [1/2]
System.Reflection.Emit.MethodBuilder.MethodBuilder (TypeBuilder tb, string name, MethodAttributes attributes, CallingConventions callingConvention, Type returnType, Type[] returnModReq, Type[] returnModOpt, Type[] parameterTypes, Type paramModReq[][], Type paramModOpt[][]) inline package
Definition at line 44 of file MethodBuilder.cs.
        {
            this.name = name;
            this.attrs = attributes;
            this.call_conv = callingConvention;
            this.rtype = returnType;
            this.returnModReq = returnModReq;
            this.returnModOpt = returnModOpt;
            this.paramModReq = paramModReq;
            this.paramModOpt = paramModOpt;
            if ((attributes & MethodAttributes.Static) == MethodAttributes.PrivateScope)
            {
                this.call_conv |= CallingConventions.HasThis;
            }
            if (parameterTypes != null)
            {
                for (int i = 0; i < parameterTypes.Length; i++)
                {
                    if (parameterTypes[i] == null)
                    {
                        throw new ArgumentException("Elements of the parameterTypes array cannot be null", "parameterTypes");
                    }
                }
                this.parameters = new Type[parameterTypes.Length];
                Array.Copy(parameterTypes, this.parameters, parameterTypes.Length);
            }
            this.type = tb;
            this.table_idx = this.get_next_table_index(this, 6, 1);
            ((ModuleBuilder)tb.Module).RegisterToken(this, this.GetToken().Token);
        }
References System.Array.Copy(), System.Reflection.Emit.MethodBuilder.get_next_table_index(), System.Reflection.Emit.MethodBuilder.GetToken(), System.Reflection.Emit.TypeBuilder.Module, System.Reflection.Emit.MethodBuilder.name, System.Reflection.Emit.MethodBuilder.parameters, System.Reflection.Emit.MethodBuilder.paramModOpt, System.Reflection.Emit.MethodBuilder.paramModReq, System.Reflection.Emit.MethodBuilder.returnModOpt, System.Reflection.Emit.MethodBuilder.returnModReq, and System.Reflection.Emit.MethodToken.Token.