Terraria Decompiled: Terraria.GameContent.UI.GameTipsDisplay.AddNewTip
AddNewTip()
void Terraria.GameContent.UI.GameTipsDisplay.AddNewTip (double currentTime) inline private
Definition at line 117 of file GameTipsDisplay.cs.
        {
            string text = "UI.Back";
            string key = this._tipProvider.RollAvailableTip().Key;
            if (Language.Exists(key))
            {
                text = key;
            }
            this._currentTips.Add(new GameTipsDisplay.GameTip(text, currentTime));
        }
References Terraria.GameContent.UI.GameTipsDisplay._currentTips, Terraria.GameContent.UI.GameTipsDisplay._tipProvider, Terraria.Localization.Language.Exists(), System.key, Terraria.Localization.LocalizedText.Key, Terraria.GameContent.UI.ITipProvider.RollAvailableTip(), and System.text.
Referenced by Terraria.GameContent.UI.GameTipsDisplay.Update().