Terraria Decompiled: Terraria.GameContent.UI.GameTipsDisplay.Draw
Draw()
void Terraria.GameContent.UI.GameTipsDisplay.Draw () inline
Definition at line 55 of file GameTipsDisplay.cs.
        {
            SpriteBatch spriteBatch = Main.spriteBatch;
            float num = (float)Main.screenWidth;
            float num2 = (float)Main.screenHeight + this.TipOffsetY;
            float num3 = (float)Main.screenWidth * 0.5f;
            foreach (GameTipsDisplay.GameTip gameTip in this._currentTips)
            {
                if (gameTip.ScreenAnchorX >= -0.5f && gameTip.ScreenAnchorX <= 1.5f)
                {
                    DynamicSpriteFont value = FontAssets.MouseText.Value;
                    string text = value.CreateWrappedText(gameTip.Text, num3, Language.ActiveCulture.CultureInfo);
                    if (text.Split(new char[] { '\n' }).Length > 2)
                    {
                        text = value.CreateWrappedText(gameTip.Text, num3 * 1.5f - 50f, Language.ActiveCulture.CultureInfo);
                    }
                    if (Main.vampireSeed)
                    {
                        text = Language.GetTextValue("Misc.Vampirism");
                    }
                    else if (WorldGen.getGoodWorldGen)
                    {
                        string text2 = "";
                        for (int i = text.Length - 1; i >= 0; i--)
{
                            text2 += text.Substring(i, 1);
                        }
                        text = text2;
                    }
                    else if (WorldGen.drunkWorldGenText)
                    {
                        text = string.Concat(Main.rand.Next(999999999));
                        for (int j = 0; j < 14; j++)
{
                            if (Main.rand.Next(2) == 0)
{
                                text += Main.rand.Next(999999999);
                            }
                        }
                    }
                    Vector2 vector = value.MeasureString(text);
                    float num4 = 1.1f;
                    float num5 = 110f;
                    if (vector.Y > num5)
                    {
                        num4 = num5 / vector.Y;
                    }
                    Vector2 vector2 = new Vector2(num * gameTip.ScreenAnchorX, num2);
                    vector2 -= vector * num4 * 0.5f;
                    if (WorldGen.tenthAnniversaryWorldGen && !Main.zenithWorld)
                    {
                        ChatManager.DrawColorCodedStringWithShadow(spriteBatch, value, text, vector2, Color.HotPink, 0f, Vector2.Zero, new Vector2(num4, num4), -1f, 2f);
                    }
                    else
                    {
                        ChatManager.DrawColorCodedStringWithShadow(spriteBatch, value, text, vector2, Color.White, 0f, Vector2.Zero, new Vector2(num4, num4), -1f, 2f);
                    }
                }
            }
        }
References Terraria.Localization.Language.ActiveCulture, Terraria.Localization.GameCulture.CultureInfo, Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.WorldGen.drunkWorldGenText, Terraria.WorldGen.getGoodWorldGen, Terraria.Localization.Language.GetTextValue(), Microsoft.Xna.Framework.Color.HotPink, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.rand, Terraria.Main.screenHeight, Terraria.Main.screenWidth, Terraria.Main.spriteBatch, Terraria.WorldGen.tenthAnniversaryWorldGen, System.text, System.value, ReLogic.Content.Asset< T >.Value, Terraria.Main.vampireSeed, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Vector2.Y, Terraria.Main.zenithWorld, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.Draw(), and Terraria.Main.DrawMenu().