Terraria Decompiled: Terraria.GameContent.UI.GameTipsDisplay.Update
Update()
void Terraria.GameContent.UI.GameTipsDisplay.Update () inline
Definition at line 22 of file GameTipsDisplay.cs.
        {
            double time = Main.gameTimeCache.TotalGameTime.TotalSeconds;
            this._currentTips.RemoveAll((GameTipsDisplay.GameTip x) => x.IsExpired(time));
            bool flag = true;
            using (List<GameTipsDisplay.GameTip>.Enumerator enumerator = this._currentTips.GetEnumerator())
            {
                while (enumerator.MoveNext())
                {
                    if (!enumerator.Current.IsExpiring(time))
                    {
                        flag = false;
                        break;
                    }
                }
            }
            if (flag)
            {
                this.AddNewTip(time);
            }
            foreach (GameTipsDisplay.GameTip gameTip in this._currentTips)
            {
                gameTip.Update(time);
            }
        }
References Terraria.GameContent.UI.GameTipsDisplay._currentTips, Terraria.GameContent.UI.GameTipsDisplay.AddNewTip(), Terraria.Main.gameTimeCache, Microsoft.Xna.Framework.GameTime.TotalGameTime, and System.TimeSpan.TotalSeconds.
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.Draw(), and Terraria.Main.DrawMenu().