Terraria Decompiled: Microsoft.Xna.Framework.Graphics.Effect.INTERNAL_updateSamplers
INTERNAL_updateSamplers()
unsafe void Microsoft.Xna.Framework.Graphics.Effect.INTERNAL_updateSamplers (uint changeCount, Effect::MOJOSHADER_samplerStateRegister * registers, TextureCollection textures, SamplerStateCollection samplers) inline private
Definition at line 418 of file Effect.cs.
        {
            int num = 0;
            while ((long)num < (long)((ulong)changeCount))
            {
                if (registers[num].sampler_state_count != 0U)
                {
                    int sampler_register = (int)registers[num].sampler_register;
                    PipelineCache pipelineCache = base.GraphicsDevice.PipelineCache;
                    pipelineCache.BeginApplySampler(samplers, sampler_register);
                    bool flag = false;
                    bool flag2 = false;
                    TextureFilter filter = pipelineCache.Filter;
                    Effect.MOJOSHADER_textureFilterType mojoshader_textureFilterType = Effect.XNAMag[(int)filter];
                    Effect.MOJOSHADER_textureFilterType mojoshader_textureFilterType2 = Effect.XNAMin[(int)filter];
                    Effect.MOJOSHADER_textureFilterType mojoshader_textureFilterType3 = Effect.XNAMip[(int)filter];
                    Effect.MOJOSHADER_effectSamplerState* ptr = (Effect.MOJOSHADER_effectSamplerState*)(void*)registers[num].sampler_states;
                    int num2 = 0;
                    while ((long)num2 < (long)((ulong)registers[num].sampler_state_count))
                    {
                        Effect.MOJOSHADER_samplerStateType type = ptr[num2].type;
                        if (type == Effect.MOJOSHADER_samplerStateType.MOJOSHADER_SAMP_TEXTURE)
{
                            EffectParameter effectParameter;
                            if (this.samplerMap.TryGetValue(registers[num].sampler_name, out effectParameter))
{
                                Texture texture = effectParameter.texture;
                                if (texture != null)
{
                                    textures[sampler_register] = texture;
                                }
                            }
                        }
                        else if (type == Effect.MOJOSHADER_samplerStateType.MOJOSHADER_SAMP_ADDRESSU)
{
                            Effect.MOJOSHADER_textureAddress* ptr2 = (Effect.MOJOSHADER_textureAddress*)(void*)ptr[num2].value.values;
                            pipelineCache.AddressU = Effect.XNAAddress[(int)(*ptr2)];
                            flag = true;
                        }
                        else if (type == Effect.MOJOSHADER_samplerStateType.MOJOSHADER_SAMP_ADDRESSV)
{
                            Effect.MOJOSHADER_textureAddress* ptr3 = (Effect.MOJOSHADER_textureAddress*)(void*)ptr[num2].value.values;
                            pipelineCache.AddressV = Effect.XNAAddress[(int)(*ptr3)];
                            flag = true;
                        }
                        else if (type == Effect.MOJOSHADER_samplerStateType.MOJOSHADER_SAMP_ADDRESSW)
{
                            Effect.MOJOSHADER_textureAddress* ptr4 = (Effect.MOJOSHADER_textureAddress*)(void*)ptr[num2].value.values;
                            pipelineCache.AddressW = Effect.XNAAddress[(int)(*ptr4)];
                            flag = true;
                        }
                        else if (type == Effect.MOJOSHADER_samplerStateType.MOJOSHADER_SAMP_MAGFILTER)
{
                            Effect.MOJOSHADER_textureFilterType* ptr5 = (Effect.MOJOSHADER_textureFilterType*)(void*)ptr[num2].value.values;
                            mojoshader_textureFilterType = *ptr5;
                            flag2 = true;
                        }
                        else if (type == Effect.MOJOSHADER_samplerStateType.MOJOSHADER_SAMP_MINFILTER)
{
                            Effect.MOJOSHADER_textureFilterType* ptr6 = (Effect.MOJOSHADER_textureFilterType*)(void*)ptr[num2].value.values;
                            mojoshader_textureFilterType2 = *ptr6;
                            flag2 = true;
                        }
                        else if (type == Effect.MOJOSHADER_samplerStateType.MOJOSHADER_SAMP_MIPFILTER)
{
                            Effect.MOJOSHADER_textureFilterType* ptr7 = (Effect.MOJOSHADER_textureFilterType*)(void*)ptr[num2].value.values;
                            mojoshader_textureFilterType3 = *ptr7;
                            flag2 = true;
                        }
                        else if (type == Effect.MOJOSHADER_samplerStateType.MOJOSHADER_SAMP_MIPMAPLODBIAS)
{
                            float* ptr8 = (float*)(void*)ptr[num2].value.values;
                            pipelineCache.MipMapLODBias = *ptr8;
                            flag = true;
                        }
                        else if (type == Effect.MOJOSHADER_samplerStateType.MOJOSHADER_SAMP_MAXMIPLEVEL)
{
                            int* ptr9 = (int*)(void*)ptr[num2].value.values;
                            pipelineCache.MaxMipLevel = *ptr9;
                            flag = true;
                        }
                        else
{
                            if (type != Effect.MOJOSHADER_samplerStateType.MOJOSHADER_SAMP_MAXANISOTROPY)
{
                                throw new NotImplementedException("Unhandled sampler state! " + type.ToString());
                            }
                            int* ptr10 = (int*)(void*)ptr[num2].value.values;
                            pipelineCache.MaxAnisotropy = *ptr10;
                            flag = true;
                        }
                        num2++;
                    }
                    if (flag2)
                    {
                        if (mojoshader_textureFilterType == Effect.MOJOSHADER_textureFilterType.MOJOSHADER_TEXTUREFILTER_POINT)
{
                            if (mojoshader_textureFilterType2 == Effect.MOJOSHADER_textureFilterType.MOJOSHADER_TEXTUREFILTER_POINT)
{
                                if (mojoshader_textureFilterType3 == Effect.MOJOSHADER_textureFilterType.MOJOSHADER_TEXTUREFILTER_NONE || mojoshader_textureFilterType3 == Effect.MOJOSHADER_textureFilterType.MOJOSHADER_TEXTUREFILTER_POINT)
{
                                    pipelineCache.Filter = TextureFilter.Point;
                                }
                                else
{
                                    if (mojoshader_textureFilterType3 != Effect.MOJOSHADER_textureFilterType.MOJOSHADER_TEXTUREFILTER_LINEAR && mojoshader_textureFilterType3 != Effect.MOJOSHADER_textureFilterType.MOJOSHADER_TEXTUREFILTER_ANISOTROPIC)
{
                                        throw new NotImplementedException("Unhandled mipfilter type! " + mojoshader_textureFilterType3.ToString());
                                    }
                                    pipelineCache.Filter = TextureFilter.PointMipLinear;
                                }
                            }
                            else
{
                                if (mojoshader_textureFilterType2 != Effect.MOJOSHADER_textureFilterType.MOJOSHADER_TEXTUREFILTER_LINEAR && mojoshader_textureFilterType2 != Effect.MOJOSHADER_textureFilterType.MOJOSHADER_TEXTUREFILTER_ANISOTROPIC)
{
                                    throw new NotImplementedException("Unhandled minfilter type! " + mojoshader_textureFilterType2.ToString());
                                }
                                if (mojoshader_textureFilterType3 == Effect.MOJOSHADER_textureFilterType.MOJOSHADER_TEXTUREFILTER_NONE || mojoshader_textureFilterType3 == Effect.MOJOSHADER_textureFilterType.MOJOSHADER_TEXTUREFILTER_POINT)
{
                                    pipelineCache.Filter = TextureFilter.MinLinearMagPointMipPoint;
                                }
                                else
{
                                    if (mojoshader_textureFilterType3 != Effect.MOJOSHADER_textureFilterType.MOJOSHADER_TEXTUREFILTER_LINEAR && mojoshader_textureFilterType3 != Effect.MOJOSHADER_textureFilterType.MOJOSHADER_TEXTUREFILTER_ANISOTROPIC)
{
                                        throw new NotImplementedException("Unhandled mipfilter type! " + mojoshader_textureFilterType3.ToString());
                                    }
                                    pipelineCache.Filter = TextureFilter.MinLinearMagPointMipLinear;
                                }
                            }
                        }
                        else
{
                            if (mojoshader_textureFilterType != Effect.MOJOSHADER_textureFilterType.MOJOSHADER_TEXTUREFILTER_LINEAR && mojoshader_textureFilterType != Effect.MOJOSHADER_textureFilterType.MOJOSHADER_TEXTUREFILTER_ANISOTROPIC)
{
                                throw new NotImplementedException("Unhandled magfilter type! " + mojoshader_textureFilterType.ToString());
                            }
                            if (mojoshader_textureFilterType2 == Effect.MOJOSHADER_textureFilterType.MOJOSHADER_TEXTUREFILTER_POINT)
{
                                if (mojoshader_textureFilterType3 == Effect.MOJOSHADER_textureFilterType.MOJOSHADER_TEXTUREFILTER_NONE || mojoshader_textureFilterType3 == Effect.MOJOSHADER_textureFilterType.MOJOSHADER_TEXTUREFILTER_POINT)
{
                                    pipelineCache.Filter = TextureFilter.MinPointMagLinearMipPoint;
                                }
                                else
{
                                    if (mojoshader_textureFilterType3 != Effect.MOJOSHADER_textureFilterType.MOJOSHADER_TEXTUREFILTER_LINEAR && mojoshader_textureFilterType3 != Effect.MOJOSHADER_textureFilterType.MOJOSHADER_TEXTUREFILTER_ANISOTROPIC)
{
                                        throw new NotImplementedException("Unhandled mipfilter type! " + mojoshader_textureFilterType3.ToString());
                                    }
                                    pipelineCache.Filter = TextureFilter.MinPointMagLinearMipLinear;
                                }
                            }
                            else
{
                                if (mojoshader_textureFilterType2 != Effect.MOJOSHADER_textureFilterType.MOJOSHADER_TEXTUREFILTER_LINEAR && mojoshader_textureFilterType2 != Effect.MOJOSHADER_textureFilterType.MOJOSHADER_TEXTUREFILTER_ANISOTROPIC)
{
                                    throw new NotImplementedException("Unhandled minfilter type! " + mojoshader_textureFilterType2.ToString());
                                }
                                if (mojoshader_textureFilterType3 == Effect.MOJOSHADER_textureFilterType.MOJOSHADER_TEXTUREFILTER_NONE || mojoshader_textureFilterType3 == Effect.MOJOSHADER_textureFilterType.MOJOSHADER_TEXTUREFILTER_POINT)
{
                                    pipelineCache.Filter = TextureFilter.LinearMipPoint;
                                }
                                else
{
                                    if (mojoshader_textureFilterType3 != Effect.MOJOSHADER_textureFilterType.MOJOSHADER_TEXTUREFILTER_LINEAR && mojoshader_textureFilterType3 != Effect.MOJOSHADER_textureFilterType.MOJOSHADER_TEXTUREFILTER_ANISOTROPIC)
{
                                        throw new NotImplementedException("Unhandled mipfilter type! " + mojoshader_textureFilterType3.ToString());
                                    }
                                    pipelineCache.Filter = TextureFilter.Linear;
                                }
                            }
                        }
                        flag = true;
                    }
                    if (flag)
                    {
                        pipelineCache.EndApplySampler(samplers, sampler_register);
                    }
                }
                num++;
            }
        }
References Microsoft.Xna.Framework.Graphics.PipelineCache.BeginApplySampler(), Microsoft.Xna.Framework.Graphics.PipelineCache.EndApplySampler(), Microsoft.Xna.Framework.Graphics.PipelineCache.Filter, int, long, Microsoft.Xna.Framework.Graphics.PipelineCache.PipelineCache(), Microsoft.Xna.Framework.Graphics.Effect.samplerMap, Microsoft.Xna.Framework.Graphics.EffectParameter.texture, Microsoft.Xna.Framework.Graphics.Effect.MOJOSHADER_effectSamplerState.type, System.U, Microsoft.Xna.Framework.Graphics.Effect.XNAAddress, Microsoft.Xna.Framework.Graphics.Effect.XNAMag, Microsoft.Xna.Framework.Graphics.Effect.XNAMin, and Microsoft.Xna.Framework.Graphics.Effect.XNAMip.
Referenced by Microsoft.Xna.Framework.Graphics.Effect.INTERNAL_applyEffect().