Terraria Decompiled: Microsoft.Xna.Framework.Graphics.Effect.INTERNAL_applyEffect
INTERNAL_applyEffect()
unsafe void Microsoft.Xna.Framework.Graphics.Effect.INTERNAL_applyEffect (uint pass) inline package
Definition at line 120 of file Effect.cs.
        {
            FNA3D.FNA3D_ApplyEffect(base.GraphicsDevice.GLDevice, this.glEffect, pass, base.GraphicsDevice.effectStateChangesPtr);
            Effect.MOJOSHADER_effectStateChanges* ptr = (Effect.MOJOSHADER_effectStateChanges*)(void*)base.GraphicsDevice.effectStateChangesPtr;
            if (ptr->render_state_change_count > 0U)
            {
                PipelineCache pipelineCache = base.GraphicsDevice.PipelineCache;
                pipelineCache.BeginApplyBlend();
                pipelineCache.BeginApplyDepthStencil();
                pipelineCache.BeginApplyRasterizer();
                bool flag = false;
                bool flag2 = false;
                bool flag3 = false;
                Effect.MOJOSHADER_effectState* ptr2 = (Effect.MOJOSHADER_effectState*)(void*)ptr->render_state_changes;
                int num = 0;
                while ((long)num < (long)((ulong)ptr->render_state_change_count))
                {
                    Effect.MOJOSHADER_renderStateType type = ptr2[num].type;
                    if (type != Effect.MOJOSHADER_renderStateType.MOJOSHADER_RS_VERTEXSHADER && type != Effect.MOJOSHADER_renderStateType.MOJOSHADER_RS_PIXELSHADER)
                    {
                        if (type == Effect.MOJOSHADER_renderStateType.MOJOSHADER_RS_ZENABLE)
{
                            Effect.MOJOSHADER_zBufferType* ptr3 = (Effect.MOJOSHADER_zBufferType*)(void*)ptr2[num].value.values;
                            pipelineCache.DepthBufferEnable = *ptr3 == Effect.MOJOSHADER_zBufferType.MOJOSHADER_ZB_TRUE;
                            flag2 = true;
                        }
                        else if (type == Effect.MOJOSHADER_renderStateType.MOJOSHADER_RS_FILLMODE)
{
                            Effect.MOJOSHADER_fillMode* ptr4 = (Effect.MOJOSHADER_fillMode*)(void*)ptr2[num].value.values;
                            if (*ptr4 == Effect.MOJOSHADER_fillMode.MOJOSHADER_FILL_SOLID)
{
                                pipelineCache.FillMode = FillMode.Solid;
                            }
                            else if (*ptr4 == Effect.MOJOSHADER_fillMode.MOJOSHADER_FILL_WIREFRAME)
{
                                pipelineCache.FillMode = FillMode.WireFrame;
                            }
                            flag3 = true;
                        }
                        else if (type == Effect.MOJOSHADER_renderStateType.MOJOSHADER_RS_ZWRITEENABLE)
{
                            int* ptr5 = (int*)(void*)ptr2[num].value.values;
                            pipelineCache.DepthBufferWriteEnable = *ptr5 == 1;
                            flag2 = true;
                        }
                        else if (type == Effect.MOJOSHADER_renderStateType.MOJOSHADER_RS_SRCBLEND)
{
                            Effect.MOJOSHADER_blendMode* ptr6 = (Effect.MOJOSHADER_blendMode*)(void*)ptr2[num].value.values;
                            pipelineCache.ColorSourceBlend = Effect.XNABlend[(int)(*ptr6)];
                            if (!pipelineCache.SeparateAlphaBlend)
{
                                pipelineCache.AlphaSourceBlend = Effect.XNABlend[(int)(*ptr6)];
                            }
                            flag = true;
                        }
                        else if (type == Effect.MOJOSHADER_renderStateType.MOJOSHADER_RS_DESTBLEND)
{
                            Effect.MOJOSHADER_blendMode* ptr7 = (Effect.MOJOSHADER_blendMode*)(void*)ptr2[num].value.values;
                            pipelineCache.ColorDestinationBlend = Effect.XNABlend[(int)(*ptr7)];
                            if (!pipelineCache.SeparateAlphaBlend)
{
                                pipelineCache.AlphaDestinationBlend = Effect.XNABlend[(int)(*ptr7)];
                            }
                            flag = true;
                        }
                        else if (type == Effect.MOJOSHADER_renderStateType.MOJOSHADER_RS_CULLMODE)
{
                            Effect.MOJOSHADER_cullMode* ptr8 = (Effect.MOJOSHADER_cullMode*)(void*)ptr2[num].value.values;
                            if (*ptr8 == Effect.MOJOSHADER_cullMode.MOJOSHADER_CULL_NONE)
{
                                pipelineCache.CullMode = CullMode.None;
                            }
                            else if (*ptr8 == Effect.MOJOSHADER_cullMode.MOJOSHADER_CULL_CW)
{
                                pipelineCache.CullMode = CullMode.CullClockwiseFace;
                            }
                            else if (*ptr8 == Effect.MOJOSHADER_cullMode.MOJOSHADER_CULL_CCW)
{
                                pipelineCache.CullMode = CullMode.CullCounterClockwiseFace;
                            }
                            flag3 = true;
                        }
                        else if (type == Effect.MOJOSHADER_renderStateType.MOJOSHADER_RS_ZFUNC)
{
                            Effect.MOJOSHADER_compareFunc* ptr9 = (Effect.MOJOSHADER_compareFunc*)(void*)ptr2[num].value.values;
                            pipelineCache.DepthBufferFunction = Effect.XNACompare[(int)(*ptr9)];
                            flag2 = true;
                        }
                        else if (type == Effect.MOJOSHADER_renderStateType.MOJOSHADER_RS_ALPHABLENDENABLE)
{
                            int* ptr10 = (int*)(void*)ptr2[num].value.values;
                            if (*ptr10 == 0)
{
                                pipelineCache.ColorSourceBlend = Blend.One;
                                pipelineCache.ColorDestinationBlend = Blend.Zero;
                                pipelineCache.AlphaSourceBlend = Blend.One;
                                pipelineCache.AlphaDestinationBlend = Blend.Zero;
                                flag = true;
                            }
                        }
                        else if (type == Effect.MOJOSHADER_renderStateType.MOJOSHADER_RS_STENCILENABLE)
{
                            int* ptr11 = (int*)(void*)ptr2[num].value.values;
                            pipelineCache.StencilEnable = *ptr11 == 1;
                            flag2 = true;
                        }
                        else if (type == Effect.MOJOSHADER_renderStateType.MOJOSHADER_RS_STENCILFAIL)
{
                            Effect.MOJOSHADER_stencilOp* ptr12 = (Effect.MOJOSHADER_stencilOp*)(void*)ptr2[num].value.values;
                            pipelineCache.StencilFail = Effect.XNAStencilOp[(int)(*ptr12)];
                            flag2 = true;
                        }
                        else if (type == Effect.MOJOSHADER_renderStateType.MOJOSHADER_RS_STENCILZFAIL)
{
                            Effect.MOJOSHADER_stencilOp* ptr13 = (Effect.MOJOSHADER_stencilOp*)(void*)ptr2[num].value.values;
                            pipelineCache.StencilDepthBufferFail = Effect.XNAStencilOp[(int)(*ptr13)];
                            flag2 = true;
                        }
                        else if (type == Effect.MOJOSHADER_renderStateType.MOJOSHADER_RS_STENCILPASS)
{
                            Effect.MOJOSHADER_stencilOp* ptr14 = (Effect.MOJOSHADER_stencilOp*)(void*)ptr2[num].value.values;
                            pipelineCache.StencilPass = Effect.XNAStencilOp[(int)(*ptr14)];
                            flag2 = true;
                        }
                        else if (type == Effect.MOJOSHADER_renderStateType.MOJOSHADER_RS_STENCILFUNC)
{
                            Effect.MOJOSHADER_compareFunc* ptr15 = (Effect.MOJOSHADER_compareFunc*)(void*)ptr2[num].value.values;
                            pipelineCache.StencilFunction = Effect.XNACompare[(int)(*ptr15)];
                            flag2 = true;
                        }
                        else if (type == Effect.MOJOSHADER_renderStateType.MOJOSHADER_RS_STENCILREF)
{
                            int* ptr16 = (int*)(void*)ptr2[num].value.values;
                            pipelineCache.ReferenceStencil = *ptr16;
                            flag2 = true;
                        }
                        else if (type == Effect.MOJOSHADER_renderStateType.MOJOSHADER_RS_STENCILMASK)
{
                            int* ptr17 = (int*)(void*)ptr2[num].value.values;
                            pipelineCache.StencilMask = *ptr17;
                            flag2 = true;
                        }
                        else if (type == Effect.MOJOSHADER_renderStateType.MOJOSHADER_RS_STENCILWRITEMASK)
{
                            int* ptr18 = (int*)(void*)ptr2[num].value.values;
                            pipelineCache.StencilWriteMask = *ptr18;
                            flag2 = true;
                        }
                        else if (type == Effect.MOJOSHADER_renderStateType.MOJOSHADER_RS_MULTISAMPLEANTIALIAS)
{
                            int* ptr19 = (int*)(void*)ptr2[num].value.values;
                            pipelineCache.MultiSampleAntiAlias = *ptr19 == 1;
                            flag3 = true;
                        }
                        else if (type == Effect.MOJOSHADER_renderStateType.MOJOSHADER_RS_MULTISAMPLEMASK)
{
                            int* ptr20 = (int*)(void*)ptr2[num].value.values;
                            pipelineCache.MultiSampleMask = *ptr20;
                            flag = true;
                        }
                        else if (type == Effect.MOJOSHADER_renderStateType.MOJOSHADER_RS_COLORWRITEENABLE)
{
                            int* ptr21 = (int*)(void*)ptr2[num].value.values;
                            pipelineCache.ColorWriteChannels = (ColorWriteChannels)(*ptr21);
                            flag = true;
                        }
                        else if (type == Effect.MOJOSHADER_renderStateType.MOJOSHADER_RS_BLENDOP)
{
                            Effect.MOJOSHADER_blendOp* ptr22 = (Effect.MOJOSHADER_blendOp*)(void*)ptr2[num].value.values;
                            pipelineCache.ColorBlendFunction = Effect.XNABlendOp[(int)(*ptr22)];
                            flag = true;
                        }
                        else if (type == Effect.MOJOSHADER_renderStateType.MOJOSHADER_RS_SCISSORTESTENABLE)
{
                            int* ptr23 = (int*)(void*)ptr2[num].value.values;
                            pipelineCache.ScissorTestEnable = *ptr23 == 1;
                            flag3 = true;
                        }
                        else if (type == Effect.MOJOSHADER_renderStateType.MOJOSHADER_RS_SLOPESCALEDEPTHBIAS)
{
                            float* ptr24 = (float*)(void*)ptr2[num].value.values;
                            pipelineCache.SlopeScaleDepthBias = *ptr24;
                            flag3 = true;
                        }
                        else if (type == Effect.MOJOSHADER_renderStateType.MOJOSHADER_RS_TWOSIDEDSTENCILMODE)
{
                            int* ptr25 = (int*)(void*)ptr2[num].value.values;
                            pipelineCache.TwoSidedStencilMode = *ptr25 == 1;
                            flag2 = true;
                        }
                        else if (type == Effect.MOJOSHADER_renderStateType.MOJOSHADER_RS_CCW_STENCILFAIL)
{
                            Effect.MOJOSHADER_stencilOp* ptr26 = (Effect.MOJOSHADER_stencilOp*)(void*)ptr2[num].value.values;
                            pipelineCache.CCWStencilFail = Effect.XNAStencilOp[(int)(*ptr26)];
                            flag2 = true;
                        }
                        else if (type == Effect.MOJOSHADER_renderStateType.MOJOSHADER_RS_CCW_STENCILZFAIL)
{
                            Effect.MOJOSHADER_stencilOp* ptr27 = (Effect.MOJOSHADER_stencilOp*)(void*)ptr2[num].value.values;
                            pipelineCache.CCWStencilDepthBufferFail = Effect.XNAStencilOp[(int)(*ptr27)];
                            flag2 = true;
                        }
                        else if (type == Effect.MOJOSHADER_renderStateType.MOJOSHADER_RS_CCW_STENCILPASS)
{
                            Effect.MOJOSHADER_stencilOp* ptr28 = (Effect.MOJOSHADER_stencilOp*)(void*)ptr2[num].value.values;
                            pipelineCache.CCWStencilPass = Effect.XNAStencilOp[(int)(*ptr28)];
                            flag2 = true;
                        }
                        else if (type == Effect.MOJOSHADER_renderStateType.MOJOSHADER_RS_CCW_STENCILFUNC)
{
                            Effect.MOJOSHADER_compareFunc* ptr29 = (Effect.MOJOSHADER_compareFunc*)(void*)ptr2[num].value.values;
                            pipelineCache.CCWStencilFunction = Effect.XNACompare[(int)(*ptr29)];
                            flag2 = true;
                        }
                        else if (type == Effect.MOJOSHADER_renderStateType.MOJOSHADER_RS_COLORWRITEENABLE1)
{
                            int* ptr30 = (int*)(void*)ptr2[num].value.values;
                            pipelineCache.ColorWriteChannels1 = (ColorWriteChannels)(*ptr30);
                            flag = true;
                        }
                        else if (type == Effect.MOJOSHADER_renderStateType.MOJOSHADER_RS_COLORWRITEENABLE2)
{
                            int* ptr31 = (int*)(void*)ptr2[num].value.values;
                            pipelineCache.ColorWriteChannels2 = (ColorWriteChannels)(*ptr31);
                            flag = true;
                        }
                        else if (type == Effect.MOJOSHADER_renderStateType.MOJOSHADER_RS_COLORWRITEENABLE3)
{
                            int* ptr32 = (int*)(void*)ptr2[num].value.values;
                            pipelineCache.ColorWriteChannels3 = (ColorWriteChannels)(*ptr32);
                            flag = true;
                        }
                        else if (type == Effect.MOJOSHADER_renderStateType.MOJOSHADER_RS_BLENDFACTOR)
{
                            int* ptr33 = (int*)(void*)ptr2[num].value.values;
                            pipelineCache.BlendFactor = new Color((*ptr33 >> 24) & 255, (*ptr33 >> 16) & 255, (*ptr33 >> 8) & 255, *ptr33 & 255);
                            flag = true;
                        }
                        else if (type == Effect.MOJOSHADER_renderStateType.MOJOSHADER_RS_DEPTHBIAS)
{
                            float* ptr34 = (float*)(void*)ptr2[num].value.values;
                            pipelineCache.DepthBias = *ptr34;
                            flag3 = true;
                        }
                        else if (type == Effect.MOJOSHADER_renderStateType.MOJOSHADER_RS_SEPARATEALPHABLENDENABLE)
{
                            int* ptr35 = (int*)(void*)ptr2[num].value.values;
                            pipelineCache.SeparateAlphaBlend = *ptr35 == 1;
                        }
                        else if (type == Effect.MOJOSHADER_renderStateType.MOJOSHADER_RS_SRCBLENDALPHA)
{
                            Effect.MOJOSHADER_blendMode* ptr36 = (Effect.MOJOSHADER_blendMode*)(void*)ptr2[num].value.values;
                            pipelineCache.AlphaSourceBlend = Effect.XNABlend[(int)(*ptr36)];
                            flag = true;
                        }
                        else if (type == Effect.MOJOSHADER_renderStateType.MOJOSHADER_RS_DESTBLENDALPHA)
{
                            Effect.MOJOSHADER_blendMode* ptr37 = (Effect.MOJOSHADER_blendMode*)(void*)ptr2[num].value.values;
                            pipelineCache.AlphaDestinationBlend = Effect.XNABlend[(int)(*ptr37)];
                            flag = true;
                        }
                        else if (type == Effect.MOJOSHADER_renderStateType.MOJOSHADER_RS_BLENDOPALPHA)
{
                            Effect.MOJOSHADER_blendOp* ptr38 = (Effect.MOJOSHADER_blendOp*)(void*)ptr2[num].value.values;
                            pipelineCache.AlphaBlendFunction = Effect.XNABlendOp[(int)(*ptr38)];
                            flag = true;
                        }
                        else if (type != (Effect.MOJOSHADER_renderStateType)178)
{
                            throw new NotImplementedException("Unhandled render state! " + type.ToString());
                        }
                    }
                    num++;
                }
                if (flag)
                {
                    pipelineCache.EndApplyBlend();
                }
                if (flag2)
                {
                    pipelineCache.EndApplyDepthStencil();
                }
                if (flag3)
                {
                    pipelineCache.EndApplyRasterizer();
                }
            }
            if (ptr->sampler_state_change_count > 0U)
            {
                this.INTERNAL_updateSamplers(ptr->sampler_state_change_count, (Effect.MOJOSHADER_samplerStateRegister*)(void*)ptr->sampler_state_changes, base.GraphicsDevice.Textures, base.GraphicsDevice.SamplerStates);
            }
            if (ptr->vertex_sampler_state_change_count > 0U)
            {
                this.INTERNAL_updateSamplers(ptr->vertex_sampler_state_change_count, (Effect.MOJOSHADER_samplerStateRegister*)(void*)ptr->vertex_sampler_state_changes, base.GraphicsDevice.VertexTextures, base.GraphicsDevice.VertexSamplerStates);
            }
        }
References Microsoft.Xna.Framework.Graphics.PipelineCache.BeginApplyBlend(), Microsoft.Xna.Framework.Graphics.PipelineCache.BeginApplyDepthStencil(), Microsoft.Xna.Framework.Graphics.PipelineCache.BeginApplyRasterizer(), Microsoft.Xna.Framework.Graphics.Color, Microsoft.Xna.Framework.Graphics.PipelineCache.EndApplyBlend(), Microsoft.Xna.Framework.Graphics.PipelineCache.EndApplyDepthStencil(), Microsoft.Xna.Framework.Graphics.PipelineCache.EndApplyRasterizer(), Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_ApplyEffect(), int, Microsoft.Xna.Framework.Graphics.Effect.INTERNAL_updateSamplers(), long, Microsoft.Xna.Framework.Graphics.PipelineCache.PipelineCache(), Microsoft.Xna.Framework.Graphics.PipelineCache.SeparateAlphaBlend, Microsoft.Xna.Framework.Graphics.Effect.MOJOSHADER_effectState.type, System.U, Microsoft.Xna.Framework.Graphics.Effect.XNABlend, Microsoft.Xna.Framework.Graphics.Effect.XNABlendOp, Microsoft.Xna.Framework.Graphics.Effect.XNACompare, and Microsoft.Xna.Framework.Graphics.Effect.XNAStencilOp.
Referenced by Microsoft.Xna.Framework.Graphics.EffectPass.Apply().