Terraria Decompiled: Microsoft.Xna.Framework.Graphics.Effect.INTERNAL_parseEffectStruct
INTERNAL_parseEffectStruct()
unsafe void Microsoft.Xna.Framework.Graphics.Effect.INTERNAL_parseEffectStruct (IntPtr effectData) inline private
Definition at line 603 of file Effect.cs.
        {
            Effect.MOJOSHADER_effect* ptr = (Effect.MOJOSHADER_effect*)(void*)effectData;
            Effect.MOJOSHADER_effectParam* ptr2 = (Effect.MOJOSHADER_effectParam*)(void*)ptr->parameters;
            List<EffectParameter> list = new List<EffectParameter>();
            for (int i = 0; i < ptr->param_count; i++)
            {
                Effect.MOJOSHADER_effectParam mojoshader_effectParam = ptr2[i];
                if (mojoshader_effectParam.value.type.parameter_type != Effect.MOJOSHADER_symbolType.MOJOSHADER_SYMTYPE_VERTEXSHADER && mojoshader_effectParam.value.type.parameter_type != Effect.MOJOSHADER_symbolType.MOJOSHADER_SYMTYPE_PIXELSHADER)
                {
                    if (mojoshader_effectParam.value.type.parameter_type >= Effect.MOJOSHADER_symbolType.MOJOSHADER_SYMTYPE_SAMPLER && mojoshader_effectParam.value.type.parameter_type <= Effect.MOJOSHADER_symbolType.MOJOSHADER_SYMTYPE_SAMPLERCUBE)
                    {
                        string text = string.Empty;
                        Effect.MOJOSHADER_effectSamplerState* ptr3 = (Effect.MOJOSHADER_effectSamplerState*)(void*)mojoshader_effectParam.value.values;
                        int num = 0;
                        while ((long)num < (long)((ulong)mojoshader_effectParam.value.value_count))
{
                            if (ptr3[num].value.type.parameter_type >= Effect.MOJOSHADER_symbolType.MOJOSHADER_SYMTYPE_TEXTURE && ptr3[num].value.type.parameter_type <= Effect.MOJOSHADER_symbolType.MOJOSHADER_SYMTYPE_TEXTURECUBE)
{
                                Effect.MOJOSHADER_effectObject* ptr4 = (Effect.MOJOSHADER_effectObject*)(void*)ptr->objects;
                                int* ptr5 = (int*)(void*)ptr3[num].value.values;
                                text = Marshal.PtrToStringAnsi(ptr4[*ptr5].mapping.name);
                                break;
                            }
                            num++;
                        }
                        for (int j = 0; j < list.Count; j++)
{
                            if (text.Equals(list[j].Name))
{
                                this.samplerMap[mojoshader_effectParam.value.name] = list[j];
                                break;
                            }
                        }
                    }
                    else
                    {
                        EffectParameter effectParameter = new EffectParameter(MarshalHelper.PtrToInternedStringAnsi(mojoshader_effectParam.value.name), MarshalHelper.PtrToInternedStringAnsi(mojoshader_effectParam.value.semantic), (int)mojoshader_effectParam.value.type.rows, (int)mojoshader_effectParam.value.type.columns, (int)mojoshader_effectParam.value.type.elements, Effect.XNAClass[(int)mojoshader_effectParam.value.type.parameter_class], Effect.XNAType[(int)mojoshader_effectParam.value.type.parameter_type], new IntPtr((void*)(&ptr2[i].value.type)), this.INTERNAL_readAnnotations(mojoshader_effectParam.annotations, mojoshader_effectParam.annotation_count), mojoshader_effectParam.value.values, mojoshader_effectParam.value.value_count * 4U, this);
                        if (mojoshader_effectParam.value.type.parameter_type == Effect.MOJOSHADER_symbolType.MOJOSHADER_SYMTYPE_STRING)
{
                            int* ptr6 = (int*)(void*)mojoshader_effectParam.value.values;
                            effectParameter.cachedString = this.INTERNAL_GetStringFromObjectTable(*ptr6);
                        }
                        list.Add(effectParameter);
                    }
                }
            }
            this.Parameters = new EffectParameterCollection(list);
            Effect.MOJOSHADER_effectTechnique* ptr7 = (Effect.MOJOSHADER_effectTechnique*)(void*)ptr->techniques;
            List<EffectTechnique> list2 = new List<EffectTechnique>(ptr->technique_count);
            int k = 0;
            while (k < list2.Capacity)
            {
                Effect.MOJOSHADER_effectPass* ptr8 = (Effect.MOJOSHADER_effectPass*)(void*)ptr7->passes;
                EffectPassCollection effectPassCollection;
                if (ptr7->pass_count == 1U)
                {
                    effectPassCollection = new EffectPassCollection(this.INTERNAL_readPass(ref *ptr8, (IntPtr)((void*)ptr7), 0U));
                }
                else
                {
                    List<EffectPass> list3 = new List<EffectPass>((int)ptr7->pass_count);
                    for (int l = 0; l < list3.Capacity; l++)
                    {
                        list3.Add(this.INTERNAL_readPass(ref ptr8[l], (IntPtr)((void*)ptr7), (uint)l));
                    }
                    effectPassCollection = new EffectPassCollection(list3);
                }
                list2.Add(new EffectTechnique(MarshalHelper.PtrToInternedStringAnsi(ptr7->name), (IntPtr)((void*)ptr7), effectPassCollection, this.INTERNAL_readAnnotations(ptr7->annotations, ptr7->annotation_count)));
                k++;
                ptr7++;
            }
            this.Techniques = new EffectTechniqueCollection(list2);
        }
References System.Collections.Generic.List< T >.Add(), Microsoft.Xna.Framework.Graphics.Effect.MOJOSHADER_effectParam.annotation_count, Microsoft.Xna.Framework.Graphics.Effect.MOJOSHADER_effectParam.annotations, System.Collections.Generic.List< T >.Capacity, Microsoft.Xna.Framework.Graphics.Effect.effectData, Microsoft.Xna.Framework.Graphics.Effect.INTERNAL_GetStringFromObjectTable(), Microsoft.Xna.Framework.Graphics.Effect.INTERNAL_readPass(), System.list, long, Microsoft.Xna.Framework.MarshalHelper.PtrToInternedStringAnsi(), System.Runtime.InteropServices.Marshal.PtrToStringAnsi(), Microsoft.Xna.Framework.Graphics.Effect.samplerMap, System.text, System.U, Microsoft.Xna.Framework.Graphics.Effect.MOJOSHADER_effectParam.value, System.value, Microsoft.Xna.Framework.Graphics.Effect.XNAClass, and Microsoft.Xna.Framework.Graphics.Effect.XNAType.
Referenced by Microsoft.Xna.Framework.Graphics.Effect.Effect(), and Microsoft.Xna.Framework.Graphics.Effect.Effect().