Terraria Decompiled: Microsoft.Xna.Framework.Graphics.Effect.INTERNAL_readEffectParameterStructureMembers
INTERNAL_readEffectParameterStructureMembers()
static unsafe EffectParameterCollection Microsoft.Xna.Framework.Graphics.Effect.INTERNAL_readEffectParameterStructureMembers (EffectParameter parameter, IntPtr _type, Effect outer) inline static package
Definition at line 679 of file Effect.cs.
        {
            if (_type == IntPtr.Zero)
            {
                return new EffectParameterCollection(new List<EffectParameter>(0));
            }
            Effect.MOJOSHADER_symbolTypeInfo mojoshader_symbolTypeInfo = *(Effect.MOJOSHADER_symbolTypeInfo*)(void*)_type;
            List<EffectParameter> list = new List<EffectParameter>();
            Effect.MOJOSHADER_symbolStructMember* ptr = (Effect.MOJOSHADER_symbolStructMember*)(void*)mojoshader_symbolTypeInfo.members;
            IntPtr intPtr = IntPtr.Zero;
            int num = 0;
            while ((long)num < (long)((ulong)mojoshader_symbolTypeInfo.member_count))
            {
                uint num2 = ptr[num].info.rows * ptr[num].info.columns;
                if (ptr[num].info.elements > 0U)
                {
                    num2 *= ptr[num].info.elements;
                }
                EffectParameter effectParameter = new EffectParameter(MarshalHelper.PtrToInternedStringAnsi(ptr[num].name), null, (int)ptr[num].info.rows, (int)ptr[num].info.columns, (int)ptr[num].info.elements, Effect.XNAClass[(int)ptr[num].info.parameter_class], Effect.XNAType[(int)ptr[num].info.parameter_type], null, null, parameter.values + intPtr.ToInt32(), num2 * 4U, outer);
                if (ptr[num].info.parameter_type == Effect.MOJOSHADER_symbolType.MOJOSHADER_SYMTYPE_STRING)
                {
                    int* ptr2 = (int*)(void*)(parameter.values + intPtr.ToInt32());
                    effectParameter.cachedString = outer.INTERNAL_GetStringFromObjectTable(*ptr2);
                }
                list.Add(effectParameter);
                intPtr += (int)(num2 * 4U);
                num++;
            }
            return new EffectParameterCollection(list);
        }
References System.info, int, Microsoft.Xna.Framework.Graphics.Effect.INTERNAL_GetStringFromObjectTable(), System.list, long, Microsoft.Xna.Framework.Graphics.Effect.MOJOSHADER_symbolTypeInfo.member_count, Microsoft.Xna.Framework.Graphics.Effect.MOJOSHADER_symbolTypeInfo.members, Microsoft.Xna.Framework.MarshalHelper.PtrToInternedStringAnsi(), System.IntPtr.ToInt32(), System.U, Microsoft.Xna.Framework.Graphics.EffectParameter.values, Microsoft.Xna.Framework.Graphics.Effect.XNAClass, Microsoft.Xna.Framework.Graphics.Effect.XNAType, and System.IntPtr.Zero.
Referenced by Microsoft.Xna.Framework.Graphics.EffectParameter.BuildMemberList().