Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.SerStack.PeekPeek
PeekPeek()
object System.Runtime.Serialization.Formatters.Binary.SerStack.PeekPeek () inline package
Definition at line 68 of file SerStack.cs.
        {
            if (this.top < 1)
            {
                return null;
            }
            return this.objects[this.top - 1];
        }
References System.Runtime.Serialization.Formatters.Binary.SerStack.objects, and System.Runtime.Serialization.Formatters.Binary.SerStack.top.
Referenced by System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadArray(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObject(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMap(), and System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMapTyped().