Terraria Decompiled: System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run
Run()
void System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run () inline package
Definition at line 207 of file AsyncMethodBuilderCore.cs.
            {
                if (this.m_context != null)
                {
                    try
                    {
                        ContextCallback contextCallback = AsyncMethodBuilderCore.MoveNextRunner.s_invokeMoveNext;
                        if (contextCallback == null)
{
                            contextCallback = (AsyncMethodBuilderCore.MoveNextRunner.s_invokeMoveNext = new ContextCallback(AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext));
                        }
                        ExecutionContext.Run(this.m_context, contextCallback, this.m_stateMachine, true);
                        return;
                    }
                    finally
                    {
                        this.m_context.Dispose();
                    }
                }
                this.m_stateMachine.MoveNext();
            }
References System.Threading.ContextCallback(), System.Threading.ExecutionContext.Dispose(), System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(), System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.m_context, System.Runtime.CompilerServices.IAsyncStateMachine.MoveNext(), System.Threading.ExecutionContext.Run(), and System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.s_invokeMoveNext.
Referenced by System.Runtime.CompilerServices.AsyncMethodBuilderCore.GetCompletionAction().