Terraria Decompiled: System.Security.Policy.PolicyStatement.FromXml
FromXml() [2/2]
void System.Security.Policy.PolicyStatement.FromXml (SecurityElement et, PolicyLevel level) inline
Implements System.Security.ISecurityPolicyEncodable.
Definition at line 102 of file PolicyStatement.cs.
        {
            if (et == null)
            {
                throw new ArgumentNullException("et");
            }
            if (et.Tag != "PolicyStatement")
            {
                throw new ArgumentException(Locale.GetText("Invalid tag."));
            }
            string text = et.Attribute("Attributes");
            if (text != null)
            {
                this.attrs = (PolicyStatementAttribute)Enum.Parse(typeof(PolicyStatementAttribute), text);
            }
            SecurityElement securityElement = et.SearchForChildByTag("PermissionSet");
            this.PermissionSet.FromXml(securityElement);
        }
References System.Security.SecurityElement.Attribute(), System.Security.PermissionSet.FromXml(), Locale.GetText(), System.Enum.Parse(), System.Security.SecurityElement.SearchForChildByTag(), System.Security.SecurityElement.Tag, and System.text.