Terraria Decompiled: System.Security.Policy.PolicyStatement.ToXml
ToXml() [2/2]
SecurityElement System.Security.Policy.PolicyStatement.ToXml (PolicyLevel level) inline
Implements System.Security.ISecurityPolicyEncodable.
Definition at line 128 of file PolicyStatement.cs.
        {
            SecurityElement securityElement = new SecurityElement("PolicyStatement");
            securityElement.AddAttribute("version", "1");
            if (this.attrs != PolicyStatementAttribute.Nothing)
            {
                securityElement.AddAttribute("Attributes", this.attrs.ToString());
            }
            securityElement.AddChild(this.PermissionSet.ToXml());
            return securityElement;
        }
References System.Security.SecurityElement.AddAttribute(), System.Security.SecurityElement.AddChild(), System.Security.Policy.PolicyStatement.attrs, and System.Security.PermissionSet.ToXml().