Terraria Decompiled: Terraria.GameContent.Biomes.MarbleBiome.SmoothSlope
SmoothSlope()
void Terraria.GameContent.Biomes.MarbleBiome.SmoothSlope (int x, int y) inline private
Definition at line 12 of file MarbleBiome.cs.
        {
            MarbleBiome.Slab slab = this._slabs[x, y];
            if (!slab.IsSolid)
            {
                return;
            }
            bool isSolid = this._slabs[x, y - 1].IsSolid;
            bool isSolid2 = this._slabs[x, y + 1].IsSolid;
            bool isSolid3 = this._slabs[x - 1, y].IsSolid;
            bool isSolid4 = this._slabs[x + 1, y].IsSolid;
            switch (((isSolid ? 1 : 0) << 3) | ((isSolid2 ? 1 : 0) << 2) | ((isSolid3 ? 1 : 0) << 1) | (isSolid4 ? 1 : 0))
            {
            case 4:
                this._slabs[x, y] = slab.WithState(new MarbleBiome.SlabState(MarbleBiome.SlabStates.HalfBrick));
                return;
            case 5:
                this._slabs[x, y] = slab.WithState(new MarbleBiome.SlabState(MarbleBiome.SlabStates.BottomRightFilled));
                return;
            case 6:
                this._slabs[x, y] = slab.WithState(new MarbleBiome.SlabState(MarbleBiome.SlabStates.BottomLeftFilled));
                return;
            case 9:
                this._slabs[x, y] = slab.WithState(new MarbleBiome.SlabState(MarbleBiome.SlabStates.TopRightFilled));
                return;
            case 10:
                this._slabs[x, y] = slab.WithState(new MarbleBiome.SlabState(MarbleBiome.SlabStates.TopLeftFilled));
                return;
            }
            this._slabs[x, y] = slab.WithState(new MarbleBiome.SlabState(MarbleBiome.SlabStates.Solid));
        }
References Terraria.GameContent.Biomes.MarbleBiome._slabs, Terraria.GameContent.Biomes.MarbleBiome.SlabStates.BottomLeftFilled(), Terraria.GameContent.Biomes.MarbleBiome.SlabStates.BottomRightFilled(), Terraria.GameContent.Biomes.MarbleBiome.SlabStates.HalfBrick(), Terraria.GameContent.Biomes.MarbleBiome.Slab.IsSolid, Terraria.GameContent.Biomes.MarbleBiome.SlabState(), Terraria.GameContent.Biomes.MarbleBiome.SlabStates.Solid(), Terraria.GameContent.Biomes.MarbleBiome.SlabStates.TopLeftFilled(), Terraria.GameContent.Biomes.MarbleBiome.SlabStates.TopRightFilled(), and Terraria.GameContent.Biomes.MarbleBiome.Slab.WithState().
Referenced by Terraria.GameContent.Biomes.MarbleBiome.Place().