Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.Halls.DungeonHall.GenerateDungeonSquareHall
GenerateDungeonSquareHall()
void Terraria.GameContent.Generation.Dungeon.Halls.DungeonHall.GenerateDungeonSquareHall (DungeonData data, List< DungeonRoom > roomsInArea, Vector2D currentPoint, ushort tileType, ushort tileCrackedType, ushort wallType, int innerBoundsSize, int outerBoundsSize, bool placeOverProtectedBricks = false, bool crackedBricks = false, bool clearPaintFirst = false) inline
Definition at line 53 of file DungeonHall.cs.
        {
            int num = innerBoundsSize + outerBoundsSize;
            for (int i = -num; i <= num; i++)
            {
                int num2 = (int)currentPoint.X + i;
                for (int j = -num; j <= num; j++)
                {
                    int num3 = (int)currentPoint.Y + j;
                    bool flag = true;
                    bool flag2 = true;
                    ProtectionType highestProtectionTypeFromPoint = DungeonUtils.GetHighestProtectionTypeFromPoint(num2, num3, roomsInArea);
                    if (highestProtectionTypeFromPoint != ProtectionType.TilesAndWalls)
                    {
                        if (highestProtectionTypeFromPoint == ProtectionType.Tiles)
{
                            flag = false;
                        }
                        if (highestProtectionTypeFromPoint == ProtectionType.Walls && DungeonUtils.IsConsideredDungeonWall((int)Main.tile[num2, num3].wall, false))
{
                            flag2 = false;
                        }
                        Tile tile = Main.tile[num2, num3];
                        if (Math.Abs(i) <= innerBoundsSize && Math.Abs(j) <= innerBoundsSize)
{
                            if (!this.CanRemoveTileAt(data, tile, (int)tileCrackedType))
{
                                goto IL_023B;
                            }
                            if (crackedBricks)
{
                                if ((tile.active() || !DungeonUtils.IsConsideredDungeonWall((int)tile.wall, false)) && num3 < Main.UnderworldLayer)
{
                                    if (this.settings.CarveOnly)
{
                                        tile.ClearTile();
                                    }
                                    else
{
                                        if (flag)
{
                                            tile.ClearTile();
                                        }
                                        if (flag2)
{
                                            tile.wall = 0;
                                        }
                                        if (flag2)
{
                                            if (clearPaintFirst)
{
                                                WorldGen.paintWall(num2, num3, 0, false, false);
                                            }
                                            DungeonUtils.ChangeWallType(tile, wallType, false, this.settings.OverridePaintWall);
                                        }
                                        if (flag)
{
                                            if (clearPaintFirst)
{
                                                WorldGen.paintTile(num2, num3, 0, false, false);
                                            }
                                            DungeonUtils.ChangeTileType(tile, tileCrackedType, false, this.settings.OverridePaintTile);
                                        }
                                    }
                                }
                            }
                            else
{
                                tile.ClearTile();
                                if (!this.settings.CarveOnly && flag2)
{
                                    if (clearPaintFirst)
{
                                        WorldGen.paintWall(num2, num3, 0, false, false);
                                    }
                                    DungeonUtils.ChangeWallType(tile, wallType, false, this.settings.OverridePaintWall);
                                }
                            }
                        }
                        else if (this.CanPlaceTileAt(data, tile, (int)tileType, (int)tileCrackedType))
{
                            if (flag)
{
                                tile.ClearTile();
                            }
                            if (flag2)
{
                                tile.wall = 0;
                            }
                            if (flag)
{
                                if (clearPaintFirst)
{
                                    WorldGen.paintTile(num2, num3, 0, false, false);
                                }
                                DungeonUtils.ChangeTileType(tile, tileType, false, this.settings.OverridePaintTile);
                            }
                            if (flag2 && i > -num && i < num && j > -num && j < num)
{
                                if (clearPaintFirst)
{
                                    WorldGen.paintWall(num2, num3, 0, false, false);
                                }
                                DungeonUtils.ChangeWallType(tile, wallType, false, this.settings.OverridePaintWall);
                            }
                        }
                        tile.liquid = 0;
                    }
                    IL_023B:;
                }
            }
        }
References System.Math.Abs(), Terraria.Tile.active(), Terraria.GameContent.Generation.Dungeon.Halls.DungeonHall.CanPlaceTileAt(), Terraria.GameContent.Generation.Dungeon.Halls.DungeonHall.CanRemoveTileAt(), Terraria.GameContent.Generation.Dungeon.Halls.DungeonHallSettings.CarveOnly, Terraria.GameContent.Generation.Dungeon.DungeonUtils.ChangeTileType(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.ChangeWallType(), Terraria.Tile.ClearTile(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GetHighestProtectionTypeFromPoint(), int, Terraria.GameContent.Generation.Dungeon.DungeonUtils.IsConsideredDungeonWall(), Terraria.GameContent.Generation.Dungeon.Halls.DungeonHallSettings.OverridePaintTile, Terraria.GameContent.Generation.Dungeon.Halls.DungeonHallSettings.OverridePaintWall, Terraria.WorldGen.paintTile(), Terraria.WorldGen.paintWall(), Terraria.GameContent.Generation.Dungeon.Halls.DungeonHall.settings, Terraria.Main.tile, Terraria.Main.UnderworldLayer, Terraria.Tile.wall, ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.