Terraria Decompiled: NVorbis.Floor1.Apply
Apply()
void NVorbis.Floor1.Apply (IFloorData floorData, int blockSize, float[] residue) inline
Implements NVorbis.Contracts.IFloor.
Definition at line 156 of file Floor1.cs.
        {
            Floor1.Data data = floorData as Floor1.Data;
            if (data == null)
            {
                throw new ArgumentException("Incorrect packet data!", "packetData");
            }
            int num = blockSize / 2;
            if (data.PostCount > 0)
            {
                bool[] array = this.UnwrapPosts(data);
                int num2 = 0;
                int num3 = data.Posts[0] * this._multiplier;
                for (int i = 1; i < data.PostCount; i++)
                {
                    int num4 = this._sortIdx[i];
                    if (array[num4])
                    {
                        int num5 = this._xList[num4];
                        int num6 = data.Posts[num4] * this._multiplier;
                        if (num2 < num)
{
                            this.RenderLineMulti(num2, num3, Math.Min(num5, num), num6, residue);
                        }
                        num2 = num5;
                        num3 = num6;
                    }
                    if (num2 >= num)
                    {
                        break;
                    }
                }
                if (num2 < num)
                {
                    this.RenderLineMulti(num2, num3, num, num3, residue);
                    return;
                }
            }
            else
            {
                Array.Clear(residue, 0, num);
            }
        }
References NVorbis.Floor1._multiplier, NVorbis.Floor1._sortIdx, NVorbis.Floor1._xList, System.array, System.Array.Clear(), System.Math.Min(), NVorbis.Floor1.Data.PostCount, NVorbis.Floor1.Data.Posts, NVorbis.Floor1.RenderLineMulti(), and NVorbis.Floor1.UnwrapPosts().