Terraria Decompiled: Terraria.WorldSections.GetNextMapDraw
GetNextMapDraw()
bool Terraria.WorldSections.GetNextMapDraw (Vector2 playerPos, out int x, out int y) inline
Definition at line 189 of file WorldSections.cs.
        {
            if (this.mapSectionsLeft <= 0)
            {
                x = -1;
                y = -1;
                return false;
            }
            int num = 0;
            int num2 = 0;
            Vector2 vector = this.prevMap.centerPos;
            playerPos *= 0.0625f;
            int sectionX = Netplay.GetSectionX((int)playerPos.X);
            int sectionY = Netplay.GetSectionY((int)playerPos.Y);
            int num3 = Netplay.GetSectionX((int)vector.X);
            int num4 = Netplay.GetSectionY((int)vector.Y);
            int num5;
            if (num3 != sectionX || num4 != sectionY)
            {
                vector = playerPos;
                num3 = sectionX;
                num4 = sectionY;
                num5 = 4;
                x = sectionX;
                y = sectionY;
            }
            else
            {
                num5 = this.prevMap.leg;
                x = this.prevMap.X;
                y = this.prevMap.Y;
                num = this.prevMap.xDir;
                num2 = this.prevMap.yDir;
            }
            int num6 = (int)(playerPos.X - ((float)num3 + 0.5f) * 200f);
            int num7 = (int)(playerPos.Y - ((float)num4 + 0.5f) * 150f);
            if (num == 0)
            {
                if (num6 > 0)
                {
                    num = -1;
                }
                else
                {
                    num = 1;
                }
                if (num7 > 0)
                {
                    num2 = -1;
                }
                else
                {
                    num2 = 1;
                }
            }
            int num8 = 0;
            bool flag = false;
            bool flag2 = false;
            for (;;)
            {
                if (num8 == 4)
                {
                    if (flag2)
                    {
                        break;
                    }
                    flag2 = true;
                    x = num3;
                    y = num4;
                    num6 = (int)(vector.X - ((float)num3 + 0.5f) * 200f);
                    num7 = (int)(vector.Y - ((float)num4 + 0.5f) * 150f);
                    if (num6 > 0)
                    {
                        num = -1;
                    }
                    else
                    {
                        num = 1;
                    }
                    if (num7 > 0)
                    {
                        num2 = -1;
                    }
                    else
                    {
                        num2 = 1;
                    }
                    num5 = 4;
                    num8 = 0;
                }
                if (y >= 0 && y < this.height && x >= 0 && x < this.width)
                {
                    flag = false;
                    if (!this.data[y * this.width + x][2])
                    {
                        goto Block_14;
                    }
                }
                int num9 = x - num3;
                int num10 = y - num4;
                if (num9 == 0 || num10 == 0)
                {
                    if (num5 == 4)
                    {
                        if (num9 == 0 && num10 == 0)
{
                            if (Math.Abs(num6) > Math.Abs(num7))
{
                                y -= num2;
                            }
                            else
{
                                x -= num;
                            }
                        }
                        else
{
                            if (num9 != 0)
{
                                x += num9 / Math.Abs(num9);
                            }
                            if (num10 != 0)
{
                                y += num10 / Math.Abs(num10);
                            }
                        }
                        num5 = 0;
                        num8 = -2;
                        flag = true;
                    }
                    else
                    {
                        if (num9 == 0)
{
                            if (num10 > 0)
{
                                num2 = -1;
                            }
                            else
{
                                num2 = 1;
                            }
                        }
                        else if (num9 > 0)
{
                            num = -1;
                        }
                        else
{
                            num = 1;
                        }
                        x += num;
                        y += num2;
                        num5++;
                    }
                    if (flag)
                    {
                        num8++;
                    }
                    else
                    {
                        flag = true;
                    }
                }
                else
                {
                    x += num;
                    y += num2;
                }
            }
            throw new Exception("Infinite loop in WorldSections.GetNextMapDraw");
            Block_14:
            this.data[y * this.width + x][2] = true;
            this.mapSectionsLeft--;
            this.prevMap.centerPos = playerPos;
            this.prevMap.X = x;
            this.prevMap.Y = y;
            this.prevMap.leg = num5;
            this.prevMap.xDir = num;
            this.prevMap.yDir = num2;
            return true;
        }
References System.Math.Abs(), Terraria.WorldSections.data, Terraria.Netplay.GetSectionX(), Terraria.Netplay.GetSectionY(), int, Terraria.WorldSections.mapSectionsLeft, Terraria.WorldSections.prevMap, Terraria.WorldSections.width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Main.DoDraw().