Terraria Decompiled: Terraria.DataStructures.PlayerDeathReason.ByProjectile
ByProjectile()
static PlayerDeathReason Terraria.DataStructures.PlayerDeathReason.ByProjectile (int playerIndex, int projectileIndex) inline static
Definition at line 94 of file PlayerDeathReason.cs.
        {
            PlayerDeathReason playerDeathReason = new PlayerDeathReason
            {
                _sourcePlayerIndex = playerIndex,
                _sourceProjectileLocalIndex = projectileIndex,
                _sourceProjectileType = Main.projectile[projectileIndex].type
            };
            if (playerIndex >= 0 && playerIndex <= 255)
            {
                playerDeathReason._sourceItemType = Main.player[playerIndex].inventory[Main.player[playerIndex].selectedItem].type;
                playerDeathReason._sourceItemPrefix = (int)Main.player[playerIndex].inventory[Main.player[playerIndex].selectedItem].prefix;
            }
            return playerDeathReason;
        }
References Terraria.DataStructures.PlayerDeathReason._sourcePlayerIndex, Terraria.DataStructures.PlayerDeathReason._sourceProjectileLocalIndex, Terraria.DataStructures.PlayerDeathReason._sourceProjectileType, int, Terraria.Player.inventory, Terraria.Main.player, Terraria.Item.prefix, Terraria.Main.projectile, Terraria.Player.selectedItem, Terraria.Item.type, and Terraria.Projectile.type.
Referenced by Terraria.Projectile.BombsHurtPlayers(), Terraria.Projectile.Damage_EVP(), and Terraria.Projectile.Damage_PVP().