Terraria Decompiled: Terraria.DataStructures.PlayerDeathReason.GetDeathText
GetDeathText()
NetworkText Terraria.DataStructures.PlayerDeathReason.GetDeathText (string deadPlayerName) inline
Definition at line 111 of file PlayerDeathReason.cs.
        {
            if (this._sourceCustomReason != null)
            {
                return NetworkText.FromLiteral(this._sourceCustomReason);
            }
            return Lang.CreateDeathMessage(deadPlayerName, this._sourcePlayerIndex, this._sourceNPCIndex, this._sourceProjectileLocalIndex, this._sourceOtherIndex, this._sourceProjectileType, this._sourceItemType);
        }
References Terraria.DataStructures.PlayerDeathReason._sourceCustomReason, Terraria.DataStructures.PlayerDeathReason._sourceItemType, Terraria.DataStructures.PlayerDeathReason._sourceNPCIndex, Terraria.DataStructures.PlayerDeathReason._sourceOtherIndex, Terraria.DataStructures.PlayerDeathReason._sourcePlayerIndex, Terraria.DataStructures.PlayerDeathReason._sourceProjectileLocalIndex, Terraria.DataStructures.PlayerDeathReason._sourceProjectileType, Terraria.Lang.CreateDeathMessage(), and Terraria.Localization.NetworkText.FromLiteral().
Referenced by Terraria.Player.KillMe().