Terraria Decompiled: Terraria.GameContent.BannerSystem.AddNPCKillBy
AddNPCKillBy()
static void Terraria.GameContent.BannerSystem.AddNPCKillBy (int npcType, int plr) inline static
Definition at line 96 of file BannerSystem.cs.
        {
            if (Main.netMode == 1)
            {
                return;
            }
            int num = BannerSystem.NPCtoBanner(npcType);
            if (num <= 0)
            {
                return;
            }
            BannerSystem.AddKill(num);
            int num2 = ItemID.Sets.KillsToBanner[BannerSystem.BannerToItem(num)];
            if (BannerSystem.killCount[num] % num2 == 0)
            {
                BannerSystem.AddClaimableBanner(num);
                int num3 = BannerSystem.BannerToNPC(num);
                NetworkText networkText = NetworkText.FromKey("Game.EnemiesDefeatedAnnouncement", new object[]
                {
                    BannerSystem.killCount[num],
                    NetworkText.FromKey(Lang.GetNPCName(num3).Key, new object[0])
                });
                if (plr >= 0 && plr < 255)
                {
                    networkText = NetworkText.FromKey("Game.EnemiesDefeatedByAnnouncement", new object[]
                    {
                        Main.player[plr].name,
                        BannerSystem.killCount[num],
                        NetworkText.FromKey(Lang.GetNPCName(num3).Key, new object[0])
                    });
                }
                ChatHelper.BroadcastChatMessage(networkText, new Color(250, 250, 0), -1);
            }
        }
References Terraria.GameContent.BannerSystem.AddClaimableBanner(), Terraria.GameContent.BannerSystem.AddKill(), Terraria.GameContent.BannerSystem.BannerToItem(), Terraria.GameContent.BannerSystem.BannerToNPC(), Terraria.Chat.ChatHelper.BroadcastChatMessage(), Terraria.Localization.NetworkText.FromKey(), Terraria.Lang.GetNPCName(), Terraria.Localization.LocalizedText.Key, Terraria.GameContent.BannerSystem.killCount, Terraria.ID.ItemID.Sets.KillsToBanner, Terraria.Player.name, Terraria.Main.netMode, Terraria.GameContent.BannerSystem.NPCtoBanner(), and Terraria.Main.player.
Referenced by Terraria.NPC.CountKillForBannersAndDropThem().