Terraria Decompiled: Terraria.GameContent.BannerSystem.Load
Load()
static void Terraria.GameContent.BannerSystem.Load (BinaryReader reader, int version) inline static
Definition at line 50 of file BannerSystem.cs.
        {
            int num = (int)reader.ReadInt16();
            for (int i = 0; i < num; i++)
            {
                int num2 = reader.ReadInt32();
                if (i < BannerSystem.killCount.Length)
                {
                    BannerSystem.killCount[i] = num2;
                }
            }
            if (version < 289)
            {
                return;
            }
            num = (int)reader.ReadInt16();
            for (int j = 0; j < num; j++)
            {
                ushort num3 = reader.ReadUInt16();
                if (j < BannerSystem.claimableBanners.Length)
                {
                    BannerSystem.claimableBanners[j] = num3;
                }
            }
        }
References Terraria.GameContent.BannerSystem.claimableBanners, int, Terraria.GameContent.BannerSystem.killCount, System.IO.BinaryReader.ReadInt16(), System.IO.BinaryReader.ReadInt32(), and System.IO.BinaryReader.ReadUInt16().
Referenced by Terraria.GameContent.BannerSystem.NetBannersModule.Deserialize(), and Terraria.IO.WorldFile.LoadHeader().