Terraria Decompiled: Terraria.GameContent.BannerSystem.BannerToItem
BannerToItem()
static int Terraria.GameContent.BannerSystem.BannerToItem (int banner) inline static
Definition at line 207 of file BannerSystem.cs.
        {
            int num;
            if (banner == 292)
            {
                num = 5673;
            }
            else if (banner == 291)
            {
                num = 5672;
            }
            else if (banner == 290)
            {
                num = 5651;
            }
            else if (banner == 289)
            {
                num = 5352;
            }
            else if (banner >= 276)
            {
                num = 4965 + banner - 276;
            }
            else if (banner >= 274)
            {
                num = 4687 + banner - 274;
            }
            else if (banner == 273)
            {
                num = 4602;
            }
            else if (banner >= 267)
            {
                num = 4541 + banner - 267;
            }
            else if (banner >= 257)
            {
                num = 3837 + banner - 257;
            }
            else if (banner >= 252)
            {
                num = 3789 + banner - 252;
            }
            else if (banner == 251)
            {
                num = 3780;
            }
            else if (banner >= 249)
            {
                num = 3593 + banner - 249;
            }
            else if (banner >= 186)
            {
                num = 3390 + banner - 186;
            }
            else if (banner >= 88)
            {
                num = 2897 + banner - 88;
            }
            else
            {
                num = 1615 + banner - 1;
            }
            return num;
        }
Referenced by Terraria.GameContent.BannerSystem.AddNPCKillBy(), Terraria.Player.GetBannerBuffEffect(), Terraria.GameContent.Bestiary.CommonEnemyUICollectionInfoProvider.GetKillCountNeeded(), Terraria.GameContent.BannerSystem.HandleBannerClaimResponse(), Terraria.GameContent.BannerSystem.RequestBannerClaim(), Terraria.SceneMetrics.ScanTiles(), and Terraria.UI.BannerClaimingUI.UpdateAndGetClaimableItemsCount().