Terraria Decompiled: Terraria.GameContent.BannerSystem.AddKill
AddKill()
static void Terraria.GameContent.BannerSystem.AddKill (int banner) inline static private
Definition at line 144 of file BannerSystem.cs.
        {
            BannerSystem.killCount[banner]++;
            if (Main.netMode == 2)
            {
                NetManager.Instance.Broadcast(BannerSystem.NetBannersModule.WriteKillCountUpdate(banner), -1);
            }
        }
References Terraria.Net.NetManager.Broadcast(), Terraria.Net.NetManager.Instance, Terraria.GameContent.BannerSystem.killCount, Terraria.Main.netMode, and Terraria.GameContent.BannerSystem.NetBannersModule.WriteKillCountUpdate().
Referenced by Terraria.GameContent.BannerSystem.AddNPCKillBy().