Terraria Decompiled: System.Text.ValueUtf8Converter.ConvertAndTerminateString
ConvertAndTerminateString()
unsafe Span< byte > System.Text.ValueUtf8Converter.ConvertAndTerminateString (ReadOnlySpan< char > value) inline
Definition at line 17 of file ValueUtf8Converter.cs.
        {
            int num = Encoding.UTF8.GetMaxByteCount(value.Length) + 1;
            if (this._bytes.Length < num)
            {
                this.Dispose();
                this._arrayToReturnToPool = ArrayPool<byte>.Shared.Rent(num);
                this._bytes = new Span<byte>(this._arrayToReturnToPool);
            }
            int bytes = Encoding.UTF8.GetBytes(value, this._bytes);
            *this._bytes[bytes] = 0;
            return this._bytes.Slice(0, bytes + 1);
        }
References System.Text.ValueUtf8Converter._arrayToReturnToPool, System.Text.ValueUtf8Converter._bytes, System.Text.ValueUtf8Converter.Dispose(), System.Text.Encoding.GetBytes(), System.Text.Encoding.GetMaxByteCount(), System.Span< T >.Length, System.Buffers.ArrayPool< T >.Shared, System.Span< T >.Slice(), System.Text.Encoding.UTF8, and System.value.