Terraria Decompiled: Terraria.Social.WeGame.CloudSocialModule.Read
Read()
override void Terraria.Social.WeGame.CloudSocialModule.Read (string path, byte[] buffer, int size) inline
Definition at line 96 of file CloudSocialModule.cs.
        {
            object obj = this.ioLock;
            lock (obj)
            {
                IRailFile railFile = rail_api.RailFactory().RailStorageHelper().OpenFile(path);
                if (railFile != null)
                {
                    railFile.Read(buffer, (uint)size);
                    railFile.Close();
                }
            }
        }
References rail.IRailFile.Close(), Terraria.Social.WeGame.CloudSocialModule.ioLock, System.obj, rail.IRailStorageHelper.OpenFile(), rail.rail_api.RailFactory(), rail.IRailFactory.RailStorageHelper(), and rail.IRailFile.Read().