Terraria Decompiled: Terraria.Social.WeGame.CloudSocialModule.GetFiles
GetFiles()
override IEnumerable< string > Terraria.Social.WeGame.CloudSocialModule.GetFiles () inline
Definition at line 22 of file CloudSocialModule.cs.
        {
            object obj = this.ioLock;
            IEnumerable<string> enumerable;
            lock (obj)
            {
                uint fileCount = rail_api.RailFactory().RailStorageHelper().GetFileCount();
                List<string> list = new List<string>((int)fileCount);
                ulong num = 0UL;
                for (uint num2 = 0U; num2 < fileCount; num2 += 1U)
                {
                    string text;
                    rail_api.RailFactory().RailStorageHelper().GetFileNameAndSize(num2, ref text, ref num);
                    list.Add(text);
                }
                enumerable = list;
            }
            return enumerable;
        }
References rail.IRailStorageHelper.GetFileCount(), rail.IRailStorageHelper.GetFileNameAndSize(), Terraria.Social.WeGame.CloudSocialModule.ioLock, System.list, System.obj, rail.rail_api.RailFactory(), rail.IRailFactory.RailStorageHelper(), System.text, and System.U.