Terraria Decompiled: Terraria.Social.WeGame.CloudSocialModule.Delete
Delete()
override bool Terraria.Social.WeGame.CloudSocialModule.Delete (string path) inline
Definition at line 123 of file CloudSocialModule.cs.
        {
            object obj = this.ioLock;
            bool flag2;
            lock (obj)
            {
                RailResult railResult = rail_api.RailFactory().RailStorageHelper().RemoveFile(path);
                flag2 = railResult == 0;
            }
            return flag2;
        }
References Terraria.Social.WeGame.CloudSocialModule.ioLock, System.obj, rail.rail_api.RailFactory(), rail.IRailFactory.RailStorageHelper(), and rail.IRailStorageHelper.RemoveFile().