Terraria Decompiled: FullSerializer.fsData.CreateDictionary
CreateDictionary()
static fsData FullSerializer.fsData.CreateDictionary () inline static
Definition at line 53 of file fsData.cs.
        {
            return new fsData(new Dictionary<string, fsData>(fsGlobalConfig.IsCaseSensitive ? StringComparer.Ordinal : StringComparer.OrdinalIgnoreCase));
        }
References FullSerializer.fsData.fsData(), FullSerializer.fsGlobalConfig.IsCaseSensitive, System.StringComparer.Ordinal, and System.StringComparer.OrdinalIgnoreCase.
Referenced by FullSerializer.fsSerializer.ConvertLegacyData(), FullSerializer.fsSerializer.InternalSerialize_1_ProcessCycles(), FullSerializer.Internal.fsKeyValuePairConverter.TrySerialize(), FullSerializer.Internal.fsReflectedConverter.TrySerialize(), FullSerializer.Internal.fsWeakReferenceConverter.TrySerialize(), and FullSerializer.Internal.fsDictionaryConverter.TrySerialize().