Terraria Decompiled: Terraria.GameContent.UI.Elements.UIBestiaryInfoItemLine.UIBestiaryInfoItemLine
UIBestiaryInfoItemLine()
Terraria.GameContent.UI.Elements.UIBestiaryInfoItemLine.UIBestiaryInfoItemLine (DropRateInfo info, BestiaryUICollectionInfo uiinfo, float textScale = 1f) inline
Definition at line 36 of file UIBestiaryInfoItemLine.cs.
        {
            this._infoDisplayItem = new Item();
            this._infoDisplayItem.SetDefaults(info.itemId, null);
            this.SetBestiaryNotesOnItemCache(info);
            base.SetPadding(0f);
            this.PaddingLeft = 10f;
            this.PaddingRight = 10f;
            this.Width.Set(-14f, 1f);
            this.Height.Set(32f, 0f);
            this.Left.Set(5f, 0f);
            base.OnMouseOver += this.MouseOver;
            base.OnMouseOut += this.MouseOut;
            this.BorderColor = new Color(89, 116, 213, 255);
            string text;
            string text2;
            this.GetDropInfo(info, uiinfo, out text, out text2);
            if (uiinfo.UnlockState < BestiaryEntryUnlockState.CanShowDropsWithoutDropRates_3)
            {
                this._hideMouseOver = true;
                Asset<Texture2D> asset = Main.Assets.Request<Texture2D>("Images/UI/Bestiary/Icon_Locked", 1);
                UIElement uielement = new UIElement
                {
                    Height = new StyleDimension(0f, 1f),
                    Width = new StyleDimension(0f, 1f),
                    HAlign = 0.5f,
                    VAlign = 0.5f
                };
                uielement.SetPadding(0f);
                UIImage uiimage = new UIImage(asset)
                {
                    ImageScale = 0.55f,
                    HAlign = 0.5f,
                    VAlign = 0.5f
                };
                uielement.Append(uiimage);
                base.Append(uielement);
                return;
            }
            UIItemIcon uiitemIcon = new UIItemIcon(this._infoDisplayItem, uiinfo.UnlockState < BestiaryEntryUnlockState.CanShowDropsWithoutDropRates_3)
            {
                IgnoresMouseInteraction = true,
                HAlign = 0f,
                Left = new StyleDimension(4f, 0f)
            };
            base.Append(uiitemIcon);
            if (!string.IsNullOrEmpty(text))
            {
                text2 = text + " " + text2;
            }
            UITextPanel<string> uitextPanel = new UITextPanel<string>(text2, textScale, false)
            {
                IgnoresMouseInteraction = true,
                DrawPanel = false,
                HAlign = 1f,
                Top = new StyleDimension(-4f, 0f)
            };
            base.Append(uitextPanel);
        }
References Terraria.GameContent.UI.Elements.UIBestiaryInfoItemLine._infoDisplayItem, Terraria.Main.Assets, Microsoft.Xna.Framework.Graphics.Color, Terraria.GameContent.UI.Elements.UIPanel.DrawPanel(), Terraria.GameContent.UI.Elements.UIBestiaryInfoItemLine.GetDropInfo(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.IgnoresMouseInteraction, Terraria.GameContent.ItemDropRules.DropRateInfo.itemId, Terraria.UI.UIElement.Left, Terraria.GameContent.UI.Elements.UIBestiaryInfoItemLine.MouseOut(), Terraria.GameContent.UI.Elements.UIBestiaryInfoItemLine.MouseOver(), Terraria.UI.StyleDimension.Set(), Terraria.GameContent.UI.Elements.UIBestiaryInfoItemLine.SetBestiaryNotesOnItemCache(), Terraria.Item.SetDefaults(), System.text, Terraria.UI.UIElement.Top, Terraria.GameContent.Bestiary.BestiaryUICollectionInfo.UnlockState, Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.