Terraria Decompiled: Terraria.ID.ContentSamples.BestiaryHelper.GetSortedBestiaryEntriesList
GetSortedBestiaryEntriesList()
static List< KeyValuePair< int, NPC > > Terraria.ID.ContentSamples.BestiaryHelper.GetSortedBestiaryEntriesList (BestiaryDatabase database) inline static
Definition at line 1413 of file ContentSamples.cs.
            {
                List<IBestiaryInfoElement> commonFilters = BestiaryDatabaseNPCsPopulator.CommonTags.GetCommonInfoElementsForFilters();
                List<KeyValuePair<int, NPC>> list = (from x in ContentSamples.NpcsByNetId.ToList<KeyValuePair<int, NPC>>()
                    orderby ContentSamples.BestiaryHelper.GetBestiaryTownPriority(x.Value), !x.Value.isLikeATownNPC, ContentSamples.BestiaryHelper.GetBestiaryNormalGoldCritterPriority(x.Value), !x.Value.CountsAsACritter, ContentSamples.BestiaryHelper.GetBestiaryBossPriority(x.Value), ContentSamples.BestiaryHelper.GetLowestBiomeGroupIndex(x.Value, database, commonFilters), x.Value.aiStyle, ContentSamples.BestiaryHelper.GetBestiaryPowerLevel(x.Value), ContentSamples.BestiaryHelper.GetBestiaryStarsPriority(x.Value)
                    select x).ToList<KeyValuePair<int, NPC>>();
                list.RemoveAll((KeyValuePair<int, NPC> x) => ContentSamples.BestiaryHelper.ShouldHideBestiaryEntry(x.Value));
                return list;
            }
References Terraria.ID.ContentSamples.BestiaryHelper.GetBestiaryBossPriority(), Terraria.ID.ContentSamples.BestiaryHelper.GetBestiaryNormalGoldCritterPriority(), Terraria.ID.ContentSamples.BestiaryHelper.GetBestiaryPowerLevel(), Terraria.ID.ContentSamples.BestiaryHelper.GetBestiaryStarsPriority(), Terraria.ID.ContentSamples.BestiaryHelper.GetBestiaryTownPriority(), Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.CommonTags.GetCommonInfoElementsForFilters(), Terraria.ID.ContentSamples.BestiaryHelper.GetLowestBiomeGroupIndex(), System.list, Terraria.ID.ContentSamples.NpcsByNetId, Terraria.ID.ContentSamples.BestiaryHelper.ShouldHideBestiaryEntry(), and System.Collections.Generic.KeyValuePair< TKey, TValue >.Value.
Referenced by Terraria.ID.ContentSamples.CreateBestiarySortingIds().