Terraria Decompiled: Steamworks.CGameID.IsValid
IsValid()
bool Steamworks.CGameID.IsValid () inline
Definition at line 74 of file CGameID.cs.
        {
            switch (this.Type())
            {
            case CGameID.EGameIDType.k_EGameIDTypeApp:
                return this.AppID() != AppId_t.Invalid;
            case CGameID.EGameIDType.k_EGameIDTypeGameMod:
                return this.AppID() != AppId_t.Invalid && (this.ModID() & 2147483648U) > 0U;
            case CGameID.EGameIDType.k_EGameIDTypeShortcut:
                return (this.ModID() & 2147483648U) > 0U;
            case CGameID.EGameIDType.k_EGameIDTypeP2P:
                return this.AppID() == AppId_t.Invalid && (this.ModID() & 2147483648U) > 0U;
            default:
                return false;
            }
        }
References Steamworks.CGameID.AppID(), Steamworks.AppId_t.Invalid, Steamworks.CGameID.ModID(), Steamworks.CGameID.Type(), and System.U.