Terraria Decompiled: Steamworks.CGameID.CGameID
CGameID() [3/3]
Steamworks.CGameID.CGameID (AppId_t nAppID, uint nModID) inline
Definition at line 23 of file CGameID.cs.
        {
            this.m_GameID = 0UL;
            this.SetAppID(nAppID);
            this.SetType(CGameID.EGameIDType.k_EGameIDTypeGameMod);
            this.SetModID(nModID);
        }
References Steamworks.CGameID.SetAppID(), Steamworks.CGameID.SetModID(), and Steamworks.CGameID.SetType().