Terraria Decompiled: Terraria.GameContent.UI.States.UICharacterCreation.Click_PasteHex
Click_PasteHex()
void Terraria.GameContent.UI.States.UICharacterCreation.Click_PasteHex (UIMouseEvent evt, UIElement listeningElement) inline private
Definition at line 1310 of file UICharacterCreation.cs.
        {
            SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
            string value = Platform.Get<IClipboard>().Value;
            Vector3 vector;
            if (this.GetHexColor(value, out vector))
            {
                this.ApplyPendingColor(UICharacterCreation.ScaledHslToRgb(vector.X, vector.Y, vector.Z));
                this._currentColorHSL = vector;
                this.UpdateHexText(UICharacterCreation.ScaledHslToRgb(vector.X, vector.Y, vector.Z));
                this.UpdateColorPickers();
            }
        }
References Terraria.GameContent.UI.States.UICharacterCreation.ApplyPendingColor(), Terraria.GameContent.UI.States.UICharacterCreation.GetHexColor(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.GameContent.UI.States.UICharacterCreation.ScaledHslToRgb(), Terraria.GameContent.UI.States.UICharacterCreation.UpdateColorPickers(), Terraria.GameContent.UI.States.UICharacterCreation.UpdateHexText(), and System.value.
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.MakeHSLMenu().