Terraria Decompiled: Terraria.GameContent.UI.States.UICharacterCreation.SetupGamepadPoints
SetupGamepadPoints()
void Terraria.GameContent.UI.States.UICharacterCreation.SetupGamepadPoints (SpriteBatch spriteBatch) inline private
Definition at line 2102 of file UICharacterCreation.cs.
        {
            UILinkPointNavigator.Shortcuts.BackButtonCommand = 7;
            int num = 3000;
            int num2 = num + 20;
            int num3 = num;
            List<SnapPoint> snapPoints = this.GetSnapPoints();
            SnapPoint snapPoint = snapPoints.First((SnapPoint a) => a.Name == "Back");
            SnapPoint snapPoint2 = snapPoints.First((SnapPoint a) => a.Name == "Create");
            UILinkPoint uilinkPoint = UILinkPointNavigator.Points[num3];
            uilinkPoint.Unlink();
            UILinkPointNavigator.SetPosition(num3, snapPoint.Position);
            num3++;
            UILinkPoint uilinkPoint2 = UILinkPointNavigator.Points[num3];
            uilinkPoint2.Unlink();
            UILinkPointNavigator.SetPosition(num3, snapPoint2.Position);
            num3++;
            uilinkPoint.Right = uilinkPoint2.ID;
            uilinkPoint2.Left = uilinkPoint.ID;
            this._foundPoints.Clear();
            this._foundPoints.Add(uilinkPoint.ID);
            this._foundPoints.Add(uilinkPoint2.ID);
            List<SnapPoint> list = snapPoints.Where((SnapPoint a) => a.Name == "Top").ToList<SnapPoint>();
            list.Sort(new Comparison<SnapPoint>(this.SortPoints));
            for (int i = 0; i < list.Count; i++)
            {
                UILinkPoint uilinkPoint3 = UILinkPointNavigator.Points[num3];
                uilinkPoint3.Unlink();
                UILinkPointNavigator.SetPosition(num3, list[i].Position);
                uilinkPoint3.Left = num3 - 1;
                uilinkPoint3.Right = num3 + 1;
                uilinkPoint3.Down = num2;
                if (i == 0)
                {
                    uilinkPoint3.Left = -3;
                }
                if (i == list.Count - 1)
                {
                    uilinkPoint3.Right = -4;
                }
                if (this._selectedPicker == UICharacterCreation.CategoryId.HairStyle || this._selectedPicker == UICharacterCreation.CategoryId.Clothing)
                {
                    uilinkPoint3.Down = num2 + i;
                }
                this._foundPoints.Add(num3);
                num3++;
            }
            List<SnapPoint> list2 = snapPoints.Where((SnapPoint a) => a.Name == "Middle").ToList<SnapPoint>();
            list2.Sort(new Comparison<SnapPoint>(this.SortPoints));
            num3 = num2;
            switch (this._selectedPicker)
            {
            case UICharacterCreation.CategoryId.CharInfo:
            {
                for (int j = 0; j < list2.Count; j++)
                {
                    UILinkPoint andSet = this.GetAndSet(num3, list2[j]);
                    andSet.Up = andSet.ID - 1;
                    andSet.Down = andSet.ID + 1;
                    if (j == 0)
                    {
                        andSet.Up = num + 2;
                    }
                    if (j == list2.Count - 1)
                    {
                        andSet.Down = uilinkPoint.ID;
                        uilinkPoint.Up = andSet.ID;
                        uilinkPoint2.Up = andSet.ID;
                    }
                    this._foundPoints.Add(num3);
                    num3++;
                }
                break;
            }
            case UICharacterCreation.CategoryId.Clothing:
            {
                List<SnapPoint> list3 = snapPoints.Where((SnapPoint a) => a.Name == "Preview").ToList<SnapPoint>();
                list3.Sort(new Comparison<SnapPoint>(this.SortPoints));
                List<SnapPoint> list4 = snapPoints.Where((SnapPoint a) => a.Name == "Low").ToList<SnapPoint>();
                list4.Sort(new Comparison<SnapPoint>(this.SortPoints));
                int num4 = -2;
                SnapPoint snapPoint3 = null;
                UILinkPoint uilinkPoint4 = null;
                if (this._pitchSlider.GetSnapPoint(out snapPoint3))
                {
                    uilinkPoint4 = this.GetAndSet(num2 + 40, snapPoint3);
                    this._foundPoints.Add(uilinkPoint4.ID);
                }
                uilinkPoint4.Down = uilinkPoint.ID;
                int num5 = num2 + 20;
                num3 = num2 + 20;
                int num6 = num3 + list4.Count;
                UILinkPoint uilinkPoint5 = null;
                for (int k = 0; k < list4.Count; k++)
                {
                    UILinkPoint andSet2 = this.GetAndSet(num3, list4[k]);
                    andSet2.Up = num2 + k + 2;
                    andSet2.Down = uilinkPoint4.ID;
                    if (k >= 3)
                    {
                        andSet2.Up = num6 + (k - 3) + 1;
                        andSet2.Down = uilinkPoint2.ID;
                    }
                    andSet2.Left = andSet2.ID - 1;
                    andSet2.Right = andSet2.ID + 1;
                    if (k == 0)
                    {
                        num4 = andSet2.ID;
                        andSet2.Left = andSet2.ID + 5;
                        uilinkPoint.Up = andSet2.ID;
                    }
                    if (k == list4.Count - 1)
                    {
                        int id = andSet2.ID;
                        andSet2.Right = andSet2.ID - 5;
                        uilinkPoint2.Up = andSet2.ID;
                    }
                    if (k == 1)
                    {
                        uilinkPoint5 = andSet2;
                    }
                    this._foundPoints.Add(num3);
                    num3++;
                }
                for (int l = 0; l < list3.Count; l++)
                {
                    UILinkPoint andSet3 = this.GetAndSet(num3, list3[l]);
                    andSet3.Up = num2 + l + 5;
                    andSet3.Down = num5 + ((int)MathHelper.Clamp((float)l, 1f, 4f) - 1) + 3;
                    andSet3.Left = andSet3.ID - 1;
                    andSet3.Right = andSet3.ID + 1;
                    if (l == 0)
                    {
                        andSet3.Left = num5 + 2;
                    }
                    if (l == list3.Count - 1)
                    {
                        andSet3.Right = num5;
                    }
                    this._foundPoints.Add(num3);
                    num3++;
                }
                if (list4.Count > 1)
                {
                    uilinkPoint4.Up = uilinkPoint5.ID;
                }
                uilinkPoint.Up = uilinkPoint4.ID;
                num3 = num2;
                for (int m = 0; m < list2.Count; m++)
                {
                    UILinkPoint andSet4 = this.GetAndSet(num3, list2[m]);
                    andSet4.Up = num + 2 + m;
                    andSet4.Left = andSet4.ID - 1;
                    andSet4.Right = andSet4.ID + 1;
                    if (m == 0)
                    {
                        andSet4.Left = andSet4.ID + 9;
                    }
                    if (m == list2.Count - 1)
                    {
                        andSet4.Right = andSet4.ID - 9;
                    }
                    andSet4.Down = num4;
                    if (m >= 5)
                    {
                        andSet4.Down = num6 + m - 5;
                    }
                    this._foundPoints.Add(num3);
                    num3++;
                }
                break;
            }
            case UICharacterCreation.CategoryId.HairStyle:
                if (list2.Count != 0)
                {
                    this._helper.CullPointsOutOfElementArea(spriteBatch, list2, this._hairstylesContainer);
                    SnapPoint snapPoint4 = list2[list2.Count - 1];
                    int num7 = snapPoint4.Id / 10;
                    int num8 = snapPoint4.Id % 10;
                    int count = Main.Hairstyles.AvailableHairstyles.Count;
                    for (int n = 0; n < list2.Count; n++)
                    {
                        SnapPoint snapPoint5 = list2[n];
                        UILinkPoint andSet5 = this.GetAndSet(num3, snapPoint5);
                        andSet5.Left = andSet5.ID - 1;
                        if (snapPoint5.Id == 0)
{
                            andSet5.Left = -3;
                        }
                        andSet5.Right = andSet5.ID + 1;
                        if (snapPoint5.Id == count - 1)
{
                            andSet5.Right = -4;
                        }
                        andSet5.Up = andSet5.ID - 10;
                        if (n < 10)
{
                            andSet5.Up = num + 2 + n;
                        }
                        andSet5.Down = andSet5.ID + 10;
                        if (snapPoint5.Id + 10 > snapPoint4.Id)
{
                            if (snapPoint5.Id % 10 < 5)
{
                                andSet5.Down = uilinkPoint.ID;
                            }
                            else
{
                                andSet5.Down = uilinkPoint2.ID;
                            }
                        }
                        if (n == list2.Count - 1)
{
                            uilinkPoint.Up = andSet5.ID;
                            uilinkPoint2.Up = andSet5.ID;
                        }
                        this._foundPoints.Add(num3);
                        num3++;
                    }
                }
                break;
            default:
            {
                List<SnapPoint> list5 = snapPoints.Where((SnapPoint a) => a.Name == "Low").ToList<SnapPoint>();
                list5.Sort(new Comparison<SnapPoint>(this.SortPoints));
                num3 = num2 + 20;
                for (int num9 = 0; num9 < list5.Count; num9++)
                {
                    UILinkPoint andSet6 = this.GetAndSet(num3, list5[num9]);
                    andSet6.Up = num2 + 2;
                    andSet6.Down = uilinkPoint.ID;
                    andSet6.Left = andSet6.ID - 1;
                    andSet6.Right = andSet6.ID + 1;
                    if (num9 == 0)
                    {
                        andSet6.Left = andSet6.ID + 2;
                        uilinkPoint.Up = andSet6.ID;
                    }
                    if (num9 == list5.Count - 1)
                    {
                        andSet6.Right = andSet6.ID - 2;
                        uilinkPoint2.Up = andSet6.ID;
                    }
                    this._foundPoints.Add(num3);
                    num3++;
                }
                num3 = num2;
                for (int num10 = 0; num10 < list2.Count; num10++)
                {
                    UILinkPoint andSet7 = this.GetAndSet(num3, list2[num10]);
                    andSet7.Up = andSet7.ID - 1;
                    andSet7.Down = andSet7.ID + 1;
                    if (num10 == 0)
                    {
                        andSet7.Up = num + 2 + 5;
                    }
                    if (num10 == list2.Count - 1)
                    {
                        andSet7.Down = num2 + 20 + 2;
                    }
                    this._foundPoints.Add(num3);
                    num3++;
                }
                break;
            }
            }
            if (PlayerInput.UsingGamepadUI && !this._foundPoints.Contains(UILinkPointNavigator.CurrentPoint))
            {
                this.MoveToVisuallyClosestPoint();
            }
        }
References Terraria.GameContent.UI.States.UICharacterCreation._foundPoints, Terraria.GameContent.UI.States.UICharacterCreation._hairstylesContainer, Terraria.GameContent.UI.States.UICharacterCreation._helper, Terraria.GameContent.UI.States.UICharacterCreation._pitchSlider, Terraria.GameContent.UI.States.UICharacterCreation._selectedPicker, System.Collections.Generic.List< T >.Add(), Microsoft.Xna.Framework.MathHelper.Clamp(), System.Collections.Generic.List< T >.Clear(), System.Collections.Generic.List< T >.Count, System.count, Terraria.GameContent.UI.States.UIGamepadHelper.CullPointsOutOfElementArea(), Terraria.UI.Gamepad.UILinkPointNavigator.CurrentPoint, Terraria.GameContent.UI.States.UICharacterCreation.GetAndSet(), Terraria.UI.UIElement.GetSnapPoint(), Terraria.UI.UIElement.GetSnapPoints(), Terraria.Main.Hairstyles, Terraria.UI.Gamepad.UILinkPoint.ID, Terraria.UI.SnapPoint.Id, int, System.list, Terraria.GameContent.UI.States.UICharacterCreation.MoveToVisuallyClosestPoint(), Terraria.UI.SnapPoint.Name, Terraria.UI.Gamepad.UILinkPointNavigator.Points, Microsoft.Xna.Framework.Graphics.Position, Terraria.UI.SnapPoint.Position, Terraria.UI.Gamepad.UILinkPointNavigator.SetPosition(), System.Collections.Generic.List< T >.Sort(), Terraria.GameContent.UI.States.UICharacterCreation.SortPoints(), Terraria.UI.Gamepad.UILinkPoint.Unlink(), and Terraria.GameInput.PlayerInput.UsingGamepadUI.
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.Draw().