Terraria Decompiled: Terraria.GameContent.UI.States.UICharacterCreation.TryAutoAssigningHair
TryAutoAssigningHair()
void Terraria.GameContent.UI.States.UICharacterCreation.TryAutoAssigningHair () inline private
Definition at line 515 of file UICharacterCreation.cs.
        {
            if (this._lastSelectedHairstyle != null)
            {
                return;
            }
            int num;
            if (this._defaultHairstylesForClothStyle.TryGetValue(this._player.skinVariant, out num))
            {
                this._player.hair = num;
            }
        }
References Terraria.GameContent.UI.States.UICharacterCreation._defaultHairstylesForClothStyle, Terraria.GameContent.UI.States.UICharacterCreation._lastSelectedHairstyle, and System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue().
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.FinishCreatingCharacter(), Terraria.GameContent.UI.States.UICharacterCreation.PreparePreview_ClothStyle(), and Terraria.GameContent.UI.States.UICharacterCreation.PreparePreview_Main().