Terraria Decompiled: Terraria.GameContent.UI.States.UICharacterCreation.SetupPlayerStatsAndInventoryBasedOnDifficulty
SetupPlayerStatsAndInventoryBasedOnDifficulty()
void Terraria.GameContent.UI.States.UICharacterCreation.SetupPlayerStatsAndInventoryBasedOnDifficulty () inline private
Definition at line 1773 of file UICharacterCreation.cs.
        {
            this._femaleArmor = (this._maleArmor = default(UICharacterCreation.ArmorAssignments));
            this.UpdatePreviewItems();
            int num = 0;
            byte difficulty = this._player.difficulty;
            if (difficulty == 3)
            {
                this._player.statLife = (this._player.statLifeMax = 100);
                this._player.statMana = (this._player.statManaMax = 20);
                this._player.inventory[num].SetDefaults(6, null);
                this._player.inventory[num++].Prefix(-1);
                this._player.inventory[num].SetDefaults(1, null);
                this._player.inventory[num++].Prefix(-1);
                this._player.inventory[num].SetDefaults(10, null);
                this._player.inventory[num++].Prefix(-1);
                this._player.inventory[num].SetDefaults(7, null);
                this._player.inventory[num++].Prefix(-1);
                this._player.inventory[num].SetDefaults(4281, null);
                this._player.inventory[num++].Prefix(-1);
                this._player.inventory[num].SetDefaults(8, null);
                this._player.inventory[num++].stack = 100;
                this._player.inventory[num].SetDefaults(965, null);
                this._player.inventory[num++].stack = 100;
                this._player.inventory[num++].SetDefaults(50, null);
                this._player.inventory[num++].SetDefaults(84, null);
                this._player.armor[3].SetDefaults(4978, null);
                this._player.armor[3].Prefix(-1);
                string text = this._player.name.ToLower();
                if (text == "wolf pet" || text == "wolfpet")
                {
                    this._player.miscEquips[3].SetDefaults(5130, null);
                }
                this._player.AddBuff(216, 3600, false);
            }
            else
            {
                this._player.inventory[num].SetDefaults(3507, null);
                this._player.inventory[num++].Prefix(-1);
                this._player.inventory[num].SetDefaults(3509, null);
                this._player.inventory[num++].Prefix(-1);
                this._player.inventory[num].SetDefaults(3506, null);
                this._player.inventory[num++].Prefix(-1);
            }
            if (Main.runningCollectorsEdition)
            {
                this._player.inventory[num++].SetDefaults(603, null);
            }
            this._player.savedPerPlayerFieldsThatArentInThePlayerClass = new Player.SavedPlayerDataWithAnnoyingRules();
            CreativePowerManager.Instance.ResetDataForNewPlayer(this._player);
        }
References Terraria.GameContent.UI.States.UICharacterCreation._player, Terraria.Player.AddBuff(), Terraria.Player.armor, Terraria.Player.difficulty, Terraria.GameContent.Creative.CreativePowerManager.Instance, Terraria.Player.inventory, Terraria.Player.miscEquips, Terraria.Player.name, Terraria.Item.Prefix(), Terraria.GameContent.Creative.CreativePowerManager.ResetDataForNewPlayer(), Terraria.Main.runningCollectorsEdition, Terraria.Item.SetDefaults(), Terraria.Item.stack, System.text, and Terraria.GameContent.UI.States.UICharacterCreation.UpdatePreviewItems().
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.FinishCreatingCharacter().