Terraria Decompiled: Terraria.GameContent.UI.States.UICharacterCreation.Click_PastePlayerTemplate
Click_PastePlayerTemplate()
void Terraria.GameContent.UI.States.UICharacterCreation.Click_PastePlayerTemplate (UIMouseEvent evt, UIElement listeningElement) inline private
Definition at line 1392 of file UICharacterCreation.cs.
        {
            SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
            try
            {
                string text = Platform.Get<IClipboard>().Value;
                int num = text.IndexOf("{");
                if (num != -1)
                {
                    text = text.Substring(num);
                    int num2 = text.LastIndexOf("}");
                    if (num2 != -1)
                    {
                        text = text.Substring(0, num2 + 1);
                        Dictionary<string, object> dictionary = JsonConvert.DeserializeObject<Dictionary<string, object>>(text);
                        if (dictionary != null)
{
                            Dictionary<string, object> dictionary2 = new Dictionary<string, object>();
                            foreach (KeyValuePair<string, object> keyValuePair in dictionary)
{
                                dictionary2[keyValuePair.Key.ToLower()] = keyValuePair.Value;
                            }
                            object obj;
                            if (dictionary2.TryGetValue("version", out obj))
{
                                long num3 = (long)obj;
                            }
                            if (dictionary2.TryGetValue("hairstyle", out obj))
{
                                int num4 = (int)((long)obj);
                                if (Main.Hairstyles.AvailableHairstyles.Contains(num4))
{
                                    this._player.hair = num4;
                                    this._lastSelectedHairstyle = new int?(num4);
                                }
                            }
                            if (dictionary2.TryGetValue("clothingstyle", out obj))
{
                                int num5 = (int)((long)obj);
                                if (this._validClothStyles.Contains(num5))
{
                                    this._player.skinVariant = num5;
                                }
                            }
                            if (dictionary2.TryGetValue("voicestyle", out obj))
{
                                int num6 = (int)((long)obj);
                                if (this._validVoiceStyles.Contains(num6))
{
                                    this._player.voiceVariant = num6;
                                }
                            }
                            if (dictionary2.TryGetValue("voicepitch", out obj))
{
                                float num7 = (float)((double)obj);
                                this._player.voicePitchOffset = num7;
                                this._pitchAmount = num7;
                            }
                            Vector3 vector;
                            if (dictionary2.TryGetValue("haircolor", out obj) && this.GetHexColor((string)obj, out vector))
{
                                this._player.hairColor = UICharacterCreation.ScaledHslToRgb(vector);
                            }
                            if (dictionary2.TryGetValue("eyecolor", out obj) && this.GetHexColor((string)obj, out vector))
{
                                this._player.eyeColor = UICharacterCreation.ScaledHslToRgb(vector);
                            }
                            if (dictionary2.TryGetValue("skincolor", out obj) && this.GetHexColor((string)obj, out vector))
{
                                this._player.skinColor = UICharacterCreation.ScaledHslToRgb(vector);
                            }
                            if (dictionary2.TryGetValue("shirtcolor", out obj) && this.GetHexColor((string)obj, out vector))
{
                                this._player.shirtColor = UICharacterCreation.ScaledHslToRgb(vector);
                            }
                            if (dictionary2.TryGetValue("undershirtcolor", out obj) && this.GetHexColor((string)obj, out vector))
{
                                this._player.underShirtColor = UICharacterCreation.ScaledHslToRgb(vector);
                            }
                            if (dictionary2.TryGetValue("pantscolor", out obj) && this.GetHexColor((string)obj, out vector))
{
                                this._player.pantsColor = UICharacterCreation.ScaledHslToRgb(vector);
                            }
                            if (dictionary2.TryGetValue("shoecolor", out obj) && this.GetHexColor((string)obj, out vector))
{
                                this._player.shoeColor = UICharacterCreation.ScaledHslToRgb(vector);
                            }
                            this.Click_CharClothStyle(null, null);
                            this.UpdateColorPickers();
                        }
                    }
                }
            }
            catch
            {
            }
        }
References Terraria.GameContent.UI.States.UICharacterCreation._validClothStyles, Terraria.GameContent.UI.States.UICharacterCreation._validVoiceStyles, Terraria.GameContent.UI.States.UICharacterCreation.Click_CharClothStyle(), Newtonsoft.Json.JsonConvert.DeserializeObject(), System.dictionary, Terraria.GameContent.UI.States.UICharacterCreation.GetHexColor(), Terraria.Main.Hairstyles, int, System.Collections.Generic.KeyValuePair< TKey, TValue >.Key, long, System.obj, Terraria.Audio.SoundEngine.PlaySound(), Terraria.GameContent.UI.States.UICharacterCreation.ScaledHslToRgb(), System.text, Terraria.GameContent.UI.States.UICharacterCreation.UpdateColorPickers(), and System.Collections.Generic.KeyValuePair< TKey, TValue >.Value.
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.MakeClothStylesMenu().