Terraria Decompiled: Terraria.GameContent.UI.States.UICharacterCreation.CreateHSLSlider
CreateHSLSlider()
UIColoredSlider Terraria.GameContent.UI.States.UICharacterCreation.CreateHSLSlider (UICharacterCreation::HSLSliderId id) inline private
Definition at line 966 of file UICharacterCreation.cs.
        {
            UIColoredSlider uicoloredSlider = this.CreateHSLSliderButtonBase(id);
            uicoloredSlider.VAlign = 0f;
            uicoloredSlider.HAlign = 0f;
            uicoloredSlider.Width = StyleDimension.FromPixelsAndPercent(-10f, 1f);
            uicoloredSlider.Top.Set((float)((UICharacterCreation.HSLSliderId)30 * id), 0f);
            uicoloredSlider.OnLeftMouseDown += this.Click_ColorPicker;
            uicoloredSlider.SetSnapPoint("Middle", (int)id, null, new Vector2?(new Vector2(0f, 20f)));
            return uicoloredSlider;
        }
References Terraria.GameContent.UI.States.UICharacterCreation.Click_ColorPicker(), Terraria.GameContent.UI.States.UICharacterCreation.CreateHSLSliderButtonBase(), Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.UI.StyleDimension.Set(), Terraria.UI.UIElement.SetSnapPoint(), Terraria.UI.UIElement.Top, and Microsoft.Xna.Framework.Graphics.Vector2.
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.MakeHSLMenu().