Terraria Decompiled: Terraria.GameContent.UI.States.UICharacterCreation.Draw
Draw()
override void Terraria.GameContent.UI.States.UICharacterCreation.Draw (SpriteBatch spriteBatch) inline virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 1953 of file UICharacterCreation.cs.
        {
            base.Draw(spriteBatch);
            string text = null;
            if (this._copyHexButton.IsMouseHovering)
            {
                text = Language.GetTextValue("UI.CopyColorToClipboard");
            }
            if (this._pasteHexButton.IsMouseHovering)
            {
                text = Language.GetTextValue("UI.PasteColorFromClipboard");
            }
            if (this._randomColorButton.IsMouseHovering)
            {
                text = Language.GetTextValue("UI.RandomizeColor");
            }
            if (this._copyTemplateButton.IsMouseHovering)
            {
                text = Language.GetTextValue("UI.CopyPlayerToClipboard");
            }
            if (this._pasteTemplateButton.IsMouseHovering)
            {
                text = Language.GetTextValue("UI.PastePlayerFromClipboard");
            }
            if (this._randomizePlayerButton.IsMouseHovering)
            {
                text = Language.GetTextValue("UI.RandomizePlayer");
            }
            if (this._previewArmorButton[0].IsMouseHovering)
            {
                text = Language.GetTextValue("UI.PreviewArmorNone");
            }
            if (this._previewArmorButton[1].IsMouseHovering)
            {
                text = Language.GetTextValue("UI.PreviewArmorHallowed");
            }
            if (this._previewArmorButton[2].IsMouseHovering)
            {
                text = Language.GetTextValue("UI.PreviewArmorSilver");
            }
            if (this._previewArmorButton[3].IsMouseHovering)
            {
                text = Language.GetTextValue("UI.PreviewArmorFormal");
            }
            if (this._previewArmorButton[4].IsMouseHovering)
            {
                text = Language.GetTextValue("UI.PreviewArmorSwimming");
            }
            if (UISliderBase.CurrentAimedSlider == this._pitchSlider)
            {
                text = Language.GetTextValue("UI.PlayerCreateVoicePitch");
            }
            if (this._voicePrevious.IsMouseHovering)
            {
                text = Language.GetTextValue("UI.PlayerCreateVoicePrev");
            }
            if (this._voiceNext.IsMouseHovering)
            {
                text = Language.GetTextValue("UI.PlayerCreateVoiceNext");
            }
            if (this._voicePlay.IsMouseHovering)
            {
                text = Language.GetTextValue("UI.PlayerCreateVoicePlay");
            }
            if (this._charInfoCategoryButton.IsMouseHovering)
            {
                text = Language.GetTextValue("UI.PlayerCreateCategoryInfo");
            }
            if (this._clothingStylesCategoryButton.IsMouseHovering)
            {
                text = Language.GetTextValue("UI.PlayerCreateCategoryBodyStyle");
            }
            if (this._hairStylesCategoryButton.IsMouseHovering)
            {
                text = Language.GetTextValue("UI.PlayerCreateCategoryHairStyle");
            }
            if (this._colorPickers[3].IsMouseHovering)
            {
                text = Language.GetTextValue("UI.PlayerCreateCategoryHairColor");
            }
            if (this._colorPickers[4].IsMouseHovering)
            {
                text = Language.GetTextValue("UI.PlayerCreateCategoryEyeColor");
            }
            if (this._colorPickers[5].IsMouseHovering)
            {
                text = Language.GetTextValue("UI.PlayerCreateCategorySkinColor");
            }
            if (this._colorPickers[6].IsMouseHovering)
            {
                text = Language.GetTextValue("UI.PlayerCreateCategoryShirtColor");
            }
            if (this._colorPickers[7].IsMouseHovering)
            {
                text = Language.GetTextValue("UI.PlayerCreateCategoryUndershirtColor");
            }
            if (this._colorPickers[8].IsMouseHovering)
            {
                text = Language.GetTextValue("UI.PlayerCreateCategoryPantsColor");
            }
            if (this._colorPickers[9].IsMouseHovering)
            {
                text = Language.GetTextValue("UI.PlayerCreateCategoryShoesColor");
            }
            if (text != null)
            {
                float x = FontAssets.MouseText.Value.MeasureString(text).X;
                Vector2 vector = new Vector2((float)Main.mouseX, (float)Main.mouseY) + new Vector2(16f);
                if (vector.Y > (float)(Main.screenHeight - 30))
                {
                    vector.Y = (float)(Main.screenHeight - 30);
                }
                if (vector.X > (float)Main.screenWidth - x)
                {
                    vector.X = (float)(Main.screenWidth - 460);
                }
                Utils.DrawBorderStringFourWay(spriteBatch, FontAssets.MouseText.Value, text, vector.X, vector.Y, new Color((int)Main.mouseTextColor, (int)Main.mouseTextColor, (int)Main.mouseTextColor, (int)Main.mouseTextColor), Color.Black, Vector2.Zero, 1f);
            }
            this.SetupGamepadPoints(spriteBatch);
            this._tips.Update();
            int num = Main.screenHeight - 560;
            if (num < 0)
            {
                num = 0;
            }
            int num2 = 150;
            if (num < 300)
            {
                num2 = num / 2;
            }
            if (num > 30)
            {
                this._tips.TipOffsetY = (float)(-(float)num2);
                this._tips.Draw();
            }
            if (!UICharacterCreation.dirty)
            {
                if (!string.IsNullOrEmpty(this._player.name))
                {
                    UICharacterCreation.dirty = true;
                }
                if (this.GetPlayerTemplateValues() != this.initialState)
                {
                    UICharacterCreation.dirty = true;
                }
            }
        }
References Terraria.GameContent.UI.States.UICharacterCreation._charInfoCategoryButton, Terraria.GameContent.UI.States.UICharacterCreation._clothingStylesCategoryButton, Terraria.GameContent.UI.States.UICharacterCreation._colorPickers, Terraria.GameContent.UI.States.UICharacterCreation._copyHexButton, Terraria.GameContent.UI.States.UICharacterCreation._copyTemplateButton, Terraria.GameContent.UI.States.UICharacterCreation._hairStylesCategoryButton, Terraria.GameContent.UI.States.UICharacterCreation._pasteHexButton, Terraria.GameContent.UI.States.UICharacterCreation._pasteTemplateButton, Terraria.GameContent.UI.States.UICharacterCreation._player, Terraria.GameContent.UI.States.UICharacterCreation._previewArmorButton, Terraria.GameContent.UI.States.UICharacterCreation._randomColorButton, Terraria.GameContent.UI.States.UICharacterCreation._randomizePlayerButton, Terraria.GameContent.UI.States.UICharacterCreation._tips, Terraria.GameContent.UI.States.UICharacterCreation._voiceNext, Terraria.GameContent.UI.States.UICharacterCreation._voicePlay, Terraria.GameContent.UI.States.UICharacterCreation._voicePrevious, Microsoft.Xna.Framework.Color.Black, Terraria.GameContent.UI.Elements.UISliderBase.CurrentAimedSlider, Terraria.GameContent.UI.States.UICharacterCreation.dirty, Terraria.GameContent.UI.GameTipsDisplay.Draw(), Terraria.Utils.DrawBorderStringFourWay(), Terraria.GameContent.UI.States.UICharacterCreation.GetPlayerTemplateValues(), Terraria.Localization.Language.GetTextValue(), Terraria.GameContent.UI.States.UICharacterCreation.initialState, int, Terraria.UI.UIElement.IsMouseHovering, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.mouseTextColor, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Player.name, Terraria.Main.screenHeight, Terraria.Main.screenWidth, Terraria.GameContent.UI.States.UICharacterCreation.SetupGamepadPoints(), System.text, Terraria.GameContent.UI.GameTipsDisplay.Update(), ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.