Terraria Decompiled: Terraria.GameContent.UI.States.UICharacterCreation.ApplyPendingColor
ApplyPendingColor()
void Terraria.GameContent.UI.States.UICharacterCreation.ApplyPendingColor (Color pendingColor) inline private
Definition at line 1092 of file UICharacterCreation.cs.
        {
            switch (this._selectedPicker)
            {
            case UICharacterCreation.CategoryId.HairColor:
                this._player.hairColor = pendingColor;
                return;
            case UICharacterCreation.CategoryId.Eye:
                this._player.eyeColor = pendingColor;
                return;
            case UICharacterCreation.CategoryId.Skin:
                this._player.skinColor = pendingColor;
                return;
            case UICharacterCreation.CategoryId.Shirt:
                this._player.shirtColor = pendingColor;
                return;
            case UICharacterCreation.CategoryId.Undershirt:
                this._player.underShirtColor = pendingColor;
                return;
            case UICharacterCreation.CategoryId.Pants:
                this._player.pantsColor = pendingColor;
                return;
            case UICharacterCreation.CategoryId.Shoes:
                this._player.shoeColor = pendingColor;
                return;
            default:
                return;
            }
        }
References Terraria.GameContent.UI.States.UICharacterCreation._selectedPicker.
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.Click_PasteHex(), Terraria.GameContent.UI.States.UICharacterCreation.Click_RandomizeSingleColor(), and Terraria.GameContent.UI.States.UICharacterCreation.UpdateHSLValue().