Terraria Decompiled: Terraria.GameContent.UI.States.UICharacterCreation.FinishCreatingCharacter
FinishCreatingCharacter()
void Terraria.GameContent.UI.States.UICharacterCreation.FinishCreatingCharacter () inline private
Definition at line 1763 of file UICharacterCreation.cs.
        {
            this.TryAutoAssigningHair();
            this.SetupPlayerStatsAndInventoryBasedOnDifficulty();
            PlayerFileData.CreateAndSave(this._player);
            Main.LoadPlayers();
            Main.menuMode = 1;
        }
References Terraria.GameContent.UI.States.UICharacterCreation._player, Terraria.IO.PlayerFileData.CreateAndSave(), Terraria.Main.LoadPlayers(), Terraria.GameContent.UI.States.UICharacterCreation.SetupPlayerStatsAndInventoryBasedOnDifficulty(), and Terraria.GameContent.UI.States.UICharacterCreation.TryAutoAssigningHair().
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.Click_NamingAndCreating(), and Terraria.GameContent.UI.States.UICharacterCreation.OnFinishedNamingAndCreating().