Terraria Decompiled: Terraria.GameContent.UI.States.UICharacterCreation.HandleBackButtonUsage
HandleBackButtonUsage()
void Terraria.GameContent.UI.States.UICharacterCreation.HandleBackButtonUsage () inline
Implements Terraria.UI.IHaveBackButtonCommand.
Definition at line 2452 of file UICharacterCreation.cs.
        {
            if (this._selectedPicker != UICharacterCreation.CategoryId.CharInfo)
            {
                SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                this.UnselectAllCategories();
                this._selectedPicker = UICharacterCreation.CategoryId.CharInfo;
                this._middleContainer.Append(this._infoContainer);
                this._charInfoCategoryButton.SetSelected(true);
                return;
            }
            UICharacterCreation.GoBack();
        }
References Terraria.GameContent.UI.States.UICharacterCreation._charInfoCategoryButton, Terraria.GameContent.UI.States.UICharacterCreation._infoContainer, Terraria.GameContent.UI.States.UICharacterCreation._middleContainer, Terraria.GameContent.UI.States.UICharacterCreation._selectedPicker, Terraria.UI.UIElement.Append(), Terraria.GameContent.UI.States.UICharacterCreation.GoBack(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.GameContent.UI.Elements.UIColoredImageButton.SetSelected(), and Terraria.GameContent.UI.States.UICharacterCreation.UnselectAllCategories().