Terraria Decompiled: Terraria.GameContent.UI.States.UICharacterCreation.MakeClothStylesMenu
MakeClothStylesMenu()
void Terraria.GameContent.UI.States.UICharacterCreation.MakeClothStylesMenu (UIElement middleInnerPanel) inline private
Definition at line 179 of file UICharacterCreation.cs.
        {
            UIElement uielement = new UIElement
            {
                Width = StyleDimension.FromPixelsAndPercent(0f, 1f),
                Height = StyleDimension.FromPixelsAndPercent(0f, 1f),
                HAlign = 0.5f,
                VAlign = 0.5f
            };
            middleInnerPanel.Append(uielement);
            uielement.SetPadding(0f);
            int num = 0;
            for (int i = 0; i < this._validClothStyles.Length; i++)
            {
                int num2 = 19;
                if (i >= this._validClothStyles.Length / 2)
                {
                    num2 += 10;
                }
                else
                {
                    num2 -= 8;
                }
                UIClothStyleButton uiclothStyleButton = new UIClothStyleButton(this._player, this._validClothStyles[i], new Action(this.PreparePreview_ClothStyle))
                {
                    Left = StyleDimension.FromPixels((float)i * 46f + (float)num2),
                    Top = StyleDimension.FromPixels((float)num)
                };
                uiclothStyleButton.OnLeftMouseDown += this.Click_CharClothStyle;
                uiclothStyleButton.SetSnapPoint("Middle", i, null, null);
                uielement.Append(uiclothStyleButton);
            }
            int num3 = 15;
            int num4 = 60;
            UIElement uielement2 = new UIElement
            {
                Width = StyleDimension.FromPixels(170f),
                Height = StyleDimension.FromPixels(50f),
                HAlign = 0f,
                Left = new StyleDimension((float)num4 - 34f, 0.5f),
                VAlign = 1f,
                Top = StyleDimension.FromPixels((float)(-(float)num3 - 7))
            };
            uielement.Append(uielement2);
            UIColoredImageButton uicoloredImageButton = new UIColoredImageButton(Main.Assets.Request<Texture2D>("Images/Item_" + 271, 1), true)
            {
                VAlign = 0.5f,
                HAlign = 0f,
                Left = StyleDimension.FromPixelsAndPercent(0f, 0f)
            };
            uicoloredImageButton.SetColor(this._player.hairColor);
            uicoloredImageButton.OnLeftMouseDown += this.EquipArmorNone;
            uielement2.Append(uicoloredImageButton);
            UIColoredImageButton uicoloredImageButton2 = new UIColoredImageButton(Main.Assets.Request<Texture2D>("Images/Item_" + 5660, 1), true)
            {
                VAlign = 0.5f,
                HAlign = 0.5f
            };
            uicoloredImageButton2.OnLeftMouseDown += this.EquipArmorHallowed;
            uielement2.Append(uicoloredImageButton2);
            UIColoredImageButton uicoloredImageButton3 = new UIColoredImageButton(Main.Assets.Request<Texture2D>("Images/Item_" + 91, 1), true)
            {
                VAlign = 0.5f,
                HAlign = 0.25f
            };
            uicoloredImageButton3.OnLeftMouseDown += this.EquipArmorSilver;
            uielement2.Append(uicoloredImageButton3);
            UIColoredImageButton uicoloredImageButton4 = new UIColoredImageButton(Main.Assets.Request<Texture2D>("Images/Item_" + 239, 1), true)
            {
                VAlign = 0.5f,
                HAlign = 0.75f
            };
            uicoloredImageButton4.OnLeftMouseDown += this.EquipArmorFormal;
            uielement2.Append(uicoloredImageButton4);
            UIColoredImageButton uicoloredImageButton5 = new UIColoredImageButton(Main.Assets.Request<Texture2D>("Images/Item_" + 237, 1), true)
            {
                VAlign = 0.5f,
                HAlign = 1f
            };
            uicoloredImageButton5.OnLeftMouseDown += this.EquipArmorSwimming;
            uielement2.Append(uicoloredImageButton5);
            this._previewArmorButton = new UIElement[5];
            this._previewArmorButton[0] = uicoloredImageButton;
            this._previewArmorButton[1] = uicoloredImageButton2;
            this._previewArmorButton[2] = uicoloredImageButton3;
            this._previewArmorButton[3] = uicoloredImageButton4;
            this._previewArmorButton[4] = uicoloredImageButton5;
            this._previewArmorButton[0].SetSnapPoint("Preview", 0, null, null);
            this._previewArmorButton[2].SetSnapPoint("Preview", 1, null, null);
            this._previewArmorButton[1].SetSnapPoint("Preview", 2, null, null);
            this._previewArmorButton[3].SetSnapPoint("Preview", 3, null, null);
            this._previewArmorButton[4].SetSnapPoint("Preview", 4, null, null);
            UIElement uielement3 = new UIElement
            {
                Width = StyleDimension.FromPixels(100f),
                Height = StyleDimension.FromPixels(50f),
                HAlign = 0f,
                Left = new StyleDimension((float)num4, 0.5f),
                VAlign = 1f,
                Top = StyleDimension.FromPixels((float)(-(float)num3 + 38 - 9))
            };
            uielement.Append(uielement3);
            UIColoredImageButton uicoloredImageButton6 = new UIColoredImageButton(Main.Assets.Request<Texture2D>("Images/UI/CharCreation/Copy", 1), true)
            {
                VAlign = 0.5f,
                HAlign = 0f,
                Left = StyleDimension.FromPixelsAndPercent(0f, 0f)
            };
            uicoloredImageButton6.OnLeftMouseDown += this.Click_CopyPlayerTemplate;
            uielement3.Append(uicoloredImageButton6);
            this._copyTemplateButton = uicoloredImageButton6;
            UIColoredImageButton uicoloredImageButton7 = new UIColoredImageButton(Main.Assets.Request<Texture2D>("Images/UI/CharCreation/Paste", 1), true)
            {
                VAlign = 0.5f,
                HAlign = 0.5f
            };
            uicoloredImageButton7.OnLeftMouseDown += this.Click_PastePlayerTemplate;
            uielement3.Append(uicoloredImageButton7);
            this._pasteTemplateButton = uicoloredImageButton7;
            UIColoredImageButton uicoloredImageButton8 = new UIColoredImageButton(Main.Assets.Request<Texture2D>("Images/UI/CharCreation/Randomize", 1), true)
            {
                VAlign = 0.5f,
                HAlign = 1f
            };
            uicoloredImageButton8.OnLeftMouseDown += this.Click_RandomizePlayer;
            uielement3.Append(uicoloredImageButton8);
            this._randomizePlayerButton = uicoloredImageButton8;
            UIElement uielement4 = new UIElement
            {
                Width = StyleDimension.FromPixels(90f),
                Height = StyleDimension.FromPixels(50f),
                HAlign = 1f,
                Left = new StyleDimension((float)(-(float)num4), -0.5f),
                VAlign = 1f,
                Top = StyleDimension.FromPixels((float)(-(float)num3))
            };
            uielement.Append(uielement4);
            UIHorizontalSeparator uihorizontalSeparator = new UIHorizontalSeparator(2, true)
            {
                Width = StyleDimension.FromPixelsAndPercent(-38f, 1f),
                HAlign = 0.5f,
                VAlign = 1f,
                Top = StyleDimension.FromPixelsAndPercent((float)(-52 - num3), 0f),
                Left = new StyleDimension(-3f, 0f),
                Color = Color.Lerp(Color.White, new Color(63, 65, 151, 255), 0.85f) * 0.9f
            };
            uielement.Append(uihorizontalSeparator);
            Asset<Texture2D> asset = Main.Assets.Request<Texture2D>("Images/UI/TexturePackButtons", 1);
            Asset<Texture2D> asset2 = Main.Assets.Request<Texture2D>("Images/UI/TexturePackButtonsOutline", 1);
            UIImageButton uiimageButton = new UIImageButton(asset, new Rectangle?(asset.Frame(2, 2, 0, 1, 0, 0)))
            {
                VAlign = 0.5f,
                HAlign = 0f,
                Left = StyleDimension.FromPixelsAndPercent(0f, 0f),
                BorderColor = Main.OurFavoriteColor
            };
            uiimageButton.SetVisibility(1f, 1f);
            uiimageButton.SetHoverImage(asset2, new Rectangle?(asset2.Frame(2, 2, 0, 1, 0, 0)));
            uiimageButton.OnLeftMouseDown += this.Click_VoiceCycleBack;
            uielement4.Append(uiimageButton);
            UIImageButton uiimageButton2 = new UIImageButton(asset, new Rectangle?(asset.Frame(2, 2, 1, 1, 0, 0)))
            {
                VAlign = 0.5f,
                HAlign = 1f,
                Left = StyleDimension.FromPixelsAndPercent(0f, 0f),
                BorderColor = Main.OurFavoriteColor
            };
            uiimageButton2.SetVisibility(1f, 1f);
            uiimageButton2.SetHoverImage(asset2, new Rectangle?(asset2.Frame(2, 2, 1, 1, 0, 0)));
            uiimageButton2.OnLeftMouseDown += this.Click_VoiceCycleForward;
            uielement4.Append(uiimageButton2);
            UIColoredImageButton uicoloredImageButton9 = new UIColoredImageButton(null, false)
            {
                VAlign = 0.5f,
                HAlign = 0.5f,
                Left = StyleDimension.FromPixelsAndPercent(0f, 0f),
                Width = StyleDimension.FromPixels(52f),
                Height = StyleDimension.FromPixels(52f)
            };
            UIImage uiimage = new UIImage(Main.Assets.Request<Texture2D>("Images/UI/CharCreation/Voice", 1))
            {
                VAlign = 0.5f,
                HAlign = 0.5f,
                IgnoresMouseInteraction = true,
                Color = Main.OurFavoriteColor
            };
            uiimage.OnUpdate += this.voiceIcon_OnUpdate;
            uicoloredImageButton9.Append(uiimage);
            UIText uitext = new UIText("", 0.85f, false)
            {
                VAlign = 1f,
                HAlign = 1f,
                TextOriginX = 0.5f,
                TextOriginY = 1f,
                Top = StyleDimension.FromPixels(-6f),
                Left = StyleDimension.FromPixels(-12f),
                ShadowColor = Color.Black * 0.3f
            };
            uitext.OnUpdate += this.voiceNumber_OnUpdate;
            uicoloredImageButton9.Append(uitext);
            uicoloredImageButton9.OnLeftMouseDown += this.Click_VoicePlay;
            uielement4.Append(uicoloredImageButton9);
            UIColoredSlider uicoloredSlider = new UIColoredSlider(LocalizedText.Empty, new Func<float>(this.GetPitchSlider), new Action<float>(this.SetPitchSlider_Keyboard), new Action(this.SetPitchSlider_GamePad), new Func<float, Color>(this.GetVoicePitchColorAt), Color.Transparent)
            {
                VAlign = 1f,
                HAlign = 0.5f,
                Width = StyleDimension.FromPixelsAndPercent(187f, 0f),
                Top = StyleDimension.FromPixels(-10f),
                Left = StyleDimension.FromPixels(55f)
            };
            uicoloredSlider.OnLeftMouseDown += this.Click_VoicePitch;
            uicoloredSlider.OnUpdate += this.PitchSliderUpdate;
            uicoloredSlider.SetSnapPoint("pitch", 0, null, new Vector2?(new Vector2(-93f, 16f)));
            uielement4.Append(uicoloredSlider);
            this._pitchSlider = uicoloredSlider;
            uiimageButton.SetSnapPoint("Low", 1, null, null);
            uicoloredImageButton9.SetSnapPoint("Low", 2, null, null);
            uiimageButton2.SetSnapPoint("Low", 3, null, null);
            this._voicePrevious = uiimageButton;
            this._voiceNext = uiimageButton2;
            this._voicePlay = uicoloredImageButton9;
            uicoloredImageButton6.SetSnapPoint("Low", 4, null, null);
            uicoloredImageButton7.SetSnapPoint("Low", 5, null, null);
            uicoloredImageButton8.SetSnapPoint("Low", 6, null, null);
            this._clothStylesContainer = uielement;
        }
References Terraria.GameContent.UI.States.UICharacterCreation._player, Terraria.GameContent.UI.States.UICharacterCreation._previewArmorButton, Terraria.GameContent.UI.States.UICharacterCreation._validClothStyles, System.Action(), Terraria.UI.UIElement.Append(), Terraria.Main.Assets, Terraria.GameContent.UI.States.UICharacterCreation.Click_CharClothStyle(), Terraria.GameContent.UI.States.UICharacterCreation.Click_CopyPlayerTemplate(), Terraria.GameContent.UI.States.UICharacterCreation.Click_PastePlayerTemplate(), Terraria.GameContent.UI.States.UICharacterCreation.Click_RandomizePlayer(), Terraria.GameContent.UI.States.UICharacterCreation.Click_VoiceCycleBack(), Terraria.GameContent.UI.States.UICharacterCreation.Click_VoiceCycleForward(), Terraria.GameContent.UI.States.UICharacterCreation.Click_VoicePitch(), Terraria.GameContent.UI.States.UICharacterCreation.Click_VoicePlay(), Terraria.Localization.LocalizedText.Empty, Terraria.GameContent.UI.States.UICharacterCreation.EquipArmorFormal(), Terraria.GameContent.UI.States.UICharacterCreation.EquipArmorHallowed(), Terraria.GameContent.UI.States.UICharacterCreation.EquipArmorNone(), Terraria.GameContent.UI.States.UICharacterCreation.EquipArmorSilver(), Terraria.GameContent.UI.States.UICharacterCreation.EquipArmorSwimming(), Terraria.UI.StyleDimension.FromPixels(), Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.GameContent.UI.States.UICharacterCreation.GetVoicePitchColorAt(), Terraria.Player.hairColor, Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.IgnoresMouseInteraction, Terraria.UI.UIElement.Left, Microsoft.Xna.Framework.Color.Lerp(), Terraria.GameContent.UI.States.UICharacterCreation.PitchSliderUpdate(), Terraria.GameContent.UI.States.UICharacterCreation.PreparePreview_ClothStyle(), Terraria.GameContent.UI.Elements.UIColoredImageButton.SetColor(), Terraria.GameContent.UI.Elements.UIImageButton.SetHoverImage(), Terraria.UI.UIElement.SetPadding(), Terraria.GameContent.UI.States.UICharacterCreation.SetPitchSlider_GamePad(), Terraria.UI.UIElement.SetSnapPoint(), Terraria.GameContent.UI.Elements.UIImageButton.SetVisibility(), Terraria.UI.UIElement.Top, Microsoft.Xna.Framework.Color.Transparent, Terraria.UI.UIElement.VAlign, Microsoft.Xna.Framework.Graphics.Vector2, Terraria.GameContent.UI.States.UICharacterCreation.voiceIcon_OnUpdate(), Terraria.GameContent.UI.States.UICharacterCreation.voiceNumber_OnUpdate(), Microsoft.Xna.Framework.Color.White, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.BuildPage().