Terraria Decompiled: Terraria.GameContent.UI.States.UICharacterCreation.MakeInfoMenu
MakeInfoMenu()
void Terraria.GameContent.UI.States.UICharacterCreation.MakeInfoMenu (UIElement parentContainer) inline private
Definition at line 762 of file UICharacterCreation.cs.
        {
            UIElement uielement = new UIElement
            {
                Width = StyleDimension.FromPixelsAndPercent(0f, 1f),
                Height = StyleDimension.FromPixelsAndPercent(0f, 1f),
                HAlign = 0.5f,
                VAlign = 0f
            };
            uielement.SetPadding(10f);
            uielement.PaddingBottom = 0f;
            uielement.PaddingTop = 0f;
            parentContainer.Append(uielement);
            UICharacterNameButton uicharacterNameButton = new UICharacterNameButton(Language.GetText("UI.WorldCreationName"), Language.GetText("UI.PlayerEmptyName"), null);
            uicharacterNameButton.Width = StyleDimension.FromPixelsAndPercent(0f, 1f);
            uicharacterNameButton.HAlign = 0.5f;
            uielement.Append(uicharacterNameButton);
            this._charName = uicharacterNameButton;
            uicharacterNameButton.OnLeftMouseDown += this.Click_Naming;
            uicharacterNameButton.SetSnapPoint("Middle", 0, null, null);
            float num = 4f;
            float num2 = 0f;
            float num3 = 0.4f;
            UIElement uielement2 = new UIElement
            {
                HAlign = 0f,
                VAlign = 1f,
                Width = StyleDimension.FromPixelsAndPercent(-num, num3),
                Height = StyleDimension.FromPixelsAndPercent(-50f, 1f)
            };
            uielement2.SetPadding(0f);
            uielement.Append(uielement2);
            UISlicedImage uislicedImage = new UISlicedImage(Main.Assets.Request<Texture2D>("Images/UI/CharCreation/CategoryPanelHighlight", 1))
            {
                HAlign = 1f,
                VAlign = 1f,
                Width = StyleDimension.FromPixelsAndPercent(-num * 2f, 1f - num3),
                Left = StyleDimension.FromPixels(-num),
                Height = StyleDimension.FromPixelsAndPercent(uielement2.Height.Pixels, uielement2.Height.Precent)
            };
            uislicedImage.SetSliceDepths(10);
            uislicedImage.Color = Color.LightGray * 0.7f;
            uielement.Append(uislicedImage);
            float num4 = 4f;
            UIDifficultyButton uidifficultyButton = new UIDifficultyButton(this._player, Lang.menu[26], Lang.menu[31], 0, Color.Cyan)
            {
                HAlign = 0f,
                VAlign = 1f / (num4 - 1f),
                Width = StyleDimension.FromPixelsAndPercent(0f, 1f),
                Height = StyleDimension.FromPixelsAndPercent(-num2, 1f / num4)
            };
            UIDifficultyButton uidifficultyButton2 = new UIDifficultyButton(this._player, Lang.menu[25], Lang.menu[30], 1, Main.mcColor)
            {
                HAlign = 0f,
                VAlign = 2f / (num4 - 1f),
                Width = StyleDimension.FromPixelsAndPercent(0f, 1f),
                Height = StyleDimension.FromPixelsAndPercent(-num2, 1f / num4)
            };
            UIDifficultyButton uidifficultyButton3 = new UIDifficultyButton(this._player, Lang.menu[24], Lang.menu[29], 2, Main.hcColor)
            {
                HAlign = 0f,
                VAlign = 1f,
                Width = StyleDimension.FromPixelsAndPercent(0f, 1f),
                Height = StyleDimension.FromPixelsAndPercent(-num2, 1f / num4)
            };
            UIDifficultyButton uidifficultyButton4 = new UIDifficultyButton(this._player, Language.GetText("UI.Creative"), Language.GetText("UI.CreativeDescriptionPlayer"), 3, Main.creativeModeColor)
            {
                HAlign = 0f,
                VAlign = 0f,
                Width = StyleDimension.FromPixelsAndPercent(0f, 1f),
                Height = StyleDimension.FromPixelsAndPercent(-num2, 1f / num4)
            };
            UIText uitext = new UIText(Lang.menu[26], 1f, false)
            {
                HAlign = 0f,
                VAlign = 0.5f,
                Width = StyleDimension.FromPixelsAndPercent(0f, 1f),
                Height = StyleDimension.FromPixelsAndPercent(0f, 1f),
                Top = StyleDimension.FromPixelsAndPercent(15f, 0f),
                IsWrapped = true
            };
            uitext.PaddingLeft = 20f;
            uitext.PaddingRight = 20f;
            uislicedImage.Append(uitext);
            uielement2.Append(uidifficultyButton4);
            uielement2.Append(uidifficultyButton);
            uielement2.Append(uidifficultyButton2);
            uielement2.Append(uidifficultyButton3);
            this._infoContainer = uielement;
            this._difficultyDescriptionText = uitext;
            uidifficultyButton4.OnLeftMouseDown += this.UpdateDifficultyDescription;
            uidifficultyButton.OnLeftMouseDown += this.UpdateDifficultyDescription;
            uidifficultyButton2.OnLeftMouseDown += this.UpdateDifficultyDescription;
            uidifficultyButton3.OnLeftMouseDown += this.UpdateDifficultyDescription;
            this.UpdateDifficultyDescription(null, null);
            uidifficultyButton4.SetSnapPoint("Middle", 1, null, null);
            uidifficultyButton.SetSnapPoint("Middle", 2, null, null);
            uidifficultyButton2.SetSnapPoint("Middle", 3, null, null);
            uidifficultyButton3.SetSnapPoint("Middle", 4, null, null);
        }
References Terraria.GameContent.UI.States.UICharacterCreation._player, Terraria.UI.UIElement.Append(), Terraria.Main.Assets, Terraria.GameContent.UI.States.UICharacterCreation.Click_Naming(), Terraria.Main.creativeModeColor, Microsoft.Xna.Framework.Color.Cyan, Terraria.UI.StyleDimension.FromPixels(), Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.Localization.Language.GetText(), Terraria.UI.UIElement.HAlign, Terraria.Main.hcColor, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.Left, Terraria.Main.mcColor, Terraria.Lang.menu, Terraria.UI.StyleDimension.Pixels, Terraria.UI.StyleDimension.Precent, Terraria.UI.UIElement.SetPadding(), Terraria.GameContent.UI.Elements.UISlicedImage.SetSliceDepths(), Terraria.UI.UIElement.SetSnapPoint(), Terraria.UI.UIElement.Top, Terraria.GameContent.UI.States.UICharacterCreation.UpdateDifficultyDescription(), Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.BuildPage().