Terraria Decompiled: Terraria.GameContent.UI.States.UICharacterCreation.MakeCategoriesBar
MakeCategoriesBar()
void Terraria.GameContent.UI.States.UICharacterCreation.MakeCategoriesBar (UIElement categoryContainer) inline private
Definition at line 641 of file UICharacterCreation.cs.
        {
            float num = -240f;
            float num2 = 48f;
            this._colorPickers = new UIColoredImageButton[10];
            categoryContainer.Append(this.CreateColorPicker(UICharacterCreation.CategoryId.HairColor, "Images/UI/CharCreation/ColorHair", num, num2));
            categoryContainer.Append(this.CreateColorPicker(UICharacterCreation.CategoryId.Eye, "Images/UI/CharCreation/ColorEye", num, num2));
            categoryContainer.Append(this.CreateColorPicker(UICharacterCreation.CategoryId.Skin, "Images/UI/CharCreation/ColorSkin", num, num2));
            categoryContainer.Append(this.CreateColorPicker(UICharacterCreation.CategoryId.Shirt, "Images/UI/CharCreation/ColorShirt", num, num2));
            categoryContainer.Append(this.CreateColorPicker(UICharacterCreation.CategoryId.Undershirt, "Images/UI/CharCreation/ColorUndershirt", num, num2));
            categoryContainer.Append(this.CreateColorPicker(UICharacterCreation.CategoryId.Pants, "Images/UI/CharCreation/ColorPants", num, num2));
            categoryContainer.Append(this.CreateColorPicker(UICharacterCreation.CategoryId.Shoes, "Images/UI/CharCreation/ColorShoes", num, num2));
            this._colorPickers[4].SetMiddleTexture(Main.Assets.Request<Texture2D>("Images/UI/CharCreation/ColorEyeBack", 1));
            this._clothingStylesCategoryButton = this.CreatePickerWithoutClick(UICharacterCreation.CategoryId.Clothing, "Images/UI/CharCreation/ClothStyleMale", num, num2);
            this._clothingStylesCategoryButton.OnLeftMouseDown += this.Click_ClothStyles;
            this._clothingStylesCategoryButton.SetSnapPoint("Top", 1, null, null);
            categoryContainer.Append(this._clothingStylesCategoryButton);
            Asset<Texture2D> asset = Main.Assets.Request<Texture2D>("Images/UI/CharCreation/ColorCharacter", 1);
            this._clothingStylesCategoryButton.SetColor(Color.Transparent);
            for (int i = 0; i < this._characterPreviewLayers.Length; i++)
            {
                UIImageFramed uiimageFramed = new UIImageFramed(asset, asset.Frame(1, 7, 0, i, 0, 0))
                {
                    HAlign = 0.5f,
                    VAlign = 0.5f
                };
                this._characterPreviewLayers[i] = uiimageFramed;
                this._clothingStylesCategoryButton.Append(uiimageFramed);
                this._clothingStylesCategoryButton.OnUpdate += this._clothingStylesCategoryButton_OnUpdate;
            }
            this._hairStylesCategoryButton = this.CreatePickerWithoutClick(UICharacterCreation.CategoryId.HairStyle, "Images/UI/CharCreation/HairStyle_Hair", num, num2);
            this._hairStylesCategoryButton.OnLeftMouseDown += this.Click_HairStyles;
            this._hairStylesCategoryButton.SetMiddleTexture(Main.Assets.Request<Texture2D>("Images/UI/CharCreation/HairStyle_Arrow", 1));
            this._hairStylesCategoryButton.SetSnapPoint("Top", 2, null, null);
            categoryContainer.Append(this._hairStylesCategoryButton);
            this._charInfoCategoryButton = this.CreatePickerWithoutClick(UICharacterCreation.CategoryId.CharInfo, "Images/UI/CharCreation/CharInfo", num, num2);
            this._charInfoCategoryButton.OnLeftMouseDown += this.Click_CharInfo;
            this._charInfoCategoryButton.SetSnapPoint("Top", 0, null, null);
            categoryContainer.Append(this._charInfoCategoryButton);
            this.UpdateColorPickers();
            UIHorizontalSeparator uihorizontalSeparator = new UIHorizontalSeparator(2, true)
            {
                Width = StyleDimension.FromPixelsAndPercent(-25f, 1f),
                Top = StyleDimension.FromPixels(6f),
                Left = new StyleDimension(-2.5f, 0f),
                VAlign = 1f,
                HAlign = 0.5f,
                Color = Color.Lerp(Color.White, new Color(63, 65, 151, 255), 0.85f) * 0.9f
            };
            categoryContainer.Append(uihorizontalSeparator);
            int num3 = 21;
            UIText uitext = new UIText(PlayerInput.GenerateInputTag_ForCurrentGamemode(false, "HotbarMinus"), 1f, false)
            {
                Left = new StyleDimension((float)(-(float)num3), 0f),
                VAlign = 0.5f,
                Top = new StyleDimension(-4f, 0f)
            };
            categoryContainer.Append(uitext);
            UIText uitext2 = new UIText(PlayerInput.GenerateInputTag_ForCurrentGamemode(false, "HotbarMinus"), 1f, false)
            {
                HAlign = 1f,
                Left = new StyleDimension((float)(12 + num3), 0f),
                VAlign = 0.5f,
                Top = new StyleDimension(-4f, 0f)
            };
            categoryContainer.Append(uitext2);
            this._helpGlyphLeft = uitext;
            this._helpGlyphRight = uitext2;
            categoryContainer.OnUpdate += this.UpdateHelpGlyphs;
        }
References Terraria.GameContent.UI.States.UICharacterCreation._characterPreviewLayers, Terraria.GameContent.UI.States.UICharacterCreation._charInfoCategoryButton, Terraria.GameContent.UI.States.UICharacterCreation._clothingStylesCategoryButton, Terraria.GameContent.UI.States.UICharacterCreation._clothingStylesCategoryButton_OnUpdate(), Terraria.GameContent.UI.States.UICharacterCreation._colorPickers, Terraria.GameContent.UI.States.UICharacterCreation._hairStylesCategoryButton, Terraria.UI.UIElement.Append(), Terraria.Main.Assets, Terraria.GameContent.UI.States.UICharacterCreation.Click_CharInfo(), Terraria.GameContent.UI.States.UICharacterCreation.Click_ClothStyles(), Terraria.GameContent.UI.States.UICharacterCreation.Click_HairStyles(), Terraria.GameContent.UI.States.UICharacterCreation.CreateColorPicker(), Terraria.GameContent.UI.States.UICharacterCreation.CreatePickerWithoutClick(), Terraria.UI.StyleDimension.FromPixels(), Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.GameInput.PlayerInput.GenerateInputTag_ForCurrentGamemode(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Left, Microsoft.Xna.Framework.Color.Lerp(), Terraria.GameContent.UI.Elements.UIColoredImageButton.SetColor(), Terraria.GameContent.UI.Elements.UIColoredImageButton.SetMiddleTexture(), Terraria.UI.UIElement.SetSnapPoint(), Terraria.UI.UIElement.Top, Microsoft.Xna.Framework.Color.Transparent, Terraria.GameContent.UI.States.UICharacterCreation.UpdateColorPickers(), Terraria.GameContent.UI.States.UICharacterCreation.UpdateHelpGlyphs(), Terraria.UI.UIElement.VAlign, Microsoft.Xna.Framework.Color.White, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.BuildPage().