Terraria Decompiled: Terraria.GameContent.UI.States.UICharacterCreation.SelectColorPicker
SelectColorPicker()
void Terraria.GameContent.UI.States.UICharacterCreation.SelectColorPicker (UICharacterCreation::CategoryId selection) inline private
Definition at line 1882 of file UICharacterCreation.cs.
        {
            this._selectedPicker = selection;
            if (selection == UICharacterCreation.CategoryId.CharInfo)
            {
                this.Click_CharInfo(null, null);
                return;
            }
            if (selection == UICharacterCreation.CategoryId.Clothing)
            {
                this.Click_ClothStyles(null, null);
                return;
            }
            if (selection == UICharacterCreation.CategoryId.HairStyle)
            {
                this.Click_HairStyles(null, null);
                return;
            }
            this.UnselectAllCategories();
            this._middleContainer.Append(this._hslContainer);
            for (int i = 0; i < this._colorPickers.Length; i++)
            {
                if (this._colorPickers[i] != null)
                {
                    this._colorPickers[i].SetSelected(i == (int)selection);
                }
            }
            Vector3 vector = Vector3.One;
            switch (this._selectedPicker)
            {
            case UICharacterCreation.CategoryId.HairColor:
                vector = UICharacterCreation.RgbToScaledHsl(this._player.hairColor);
                break;
            case UICharacterCreation.CategoryId.Eye:
                vector = UICharacterCreation.RgbToScaledHsl(this._player.eyeColor);
                break;
            case UICharacterCreation.CategoryId.Skin:
                vector = UICharacterCreation.RgbToScaledHsl(this._player.skinColor);
                break;
            case UICharacterCreation.CategoryId.Shirt:
                vector = UICharacterCreation.RgbToScaledHsl(this._player.shirtColor);
                break;
            case UICharacterCreation.CategoryId.Undershirt:
                vector = UICharacterCreation.RgbToScaledHsl(this._player.underShirtColor);
                break;
            case UICharacterCreation.CategoryId.Pants:
                vector = UICharacterCreation.RgbToScaledHsl(this._player.pantsColor);
                break;
            case UICharacterCreation.CategoryId.Shoes:
                vector = UICharacterCreation.RgbToScaledHsl(this._player.shoeColor);
                break;
            }
            this._currentColorHSL = vector;
            this.UpdateHexText(UICharacterCreation.ScaledHslToRgb(vector.X, vector.Y, vector.Z));
        }
References Terraria.GameContent.UI.States.UICharacterCreation._colorPickers, Terraria.GameContent.UI.States.UICharacterCreation._hslContainer, Terraria.GameContent.UI.States.UICharacterCreation._middleContainer, Terraria.GameContent.UI.States.UICharacterCreation._player, Terraria.GameContent.UI.States.UICharacterCreation._selectedPicker, Terraria.UI.UIElement.Append(), Terraria.GameContent.UI.States.UICharacterCreation.Click_CharInfo(), Terraria.GameContent.UI.States.UICharacterCreation.Click_ClothStyles(), Terraria.GameContent.UI.States.UICharacterCreation.Click_HairStyles(), Terraria.Player.eyeColor, Terraria.Player.hairColor, Microsoft.Xna.Framework.Vector3.One, Terraria.Player.pantsColor, Terraria.GameContent.UI.States.UICharacterCreation.RgbToScaledHsl(), Terraria.GameContent.UI.States.UICharacterCreation.ScaledHslToRgb(), Terraria.GameContent.UI.Elements.UIColoredImageButton.SetSelected(), Terraria.Player.shirtColor, Terraria.Player.shoeColor, Terraria.Player.skinColor, Terraria.Player.underShirtColor, Terraria.GameContent.UI.States.UICharacterCreation.UnselectAllCategories(), Terraria.GameContent.UI.States.UICharacterCreation.UpdateHexText(), Microsoft.Xna.Framework.Vector3.X, Microsoft.Xna.Framework.Vector3.Y, and Microsoft.Xna.Framework.Vector3.Z.
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.Click_ColorPicker(), and Terraria.GameContent.UI.States.UICharacterCreation.TryMovingCategory().