Terraria Decompiled: Terraria.GameContent.UI.States.UICharacterCreation.MakeHSLMenu
MakeHSLMenu()
void Terraria.GameContent.UI.States.UICharacterCreation.MakeHSLMenu (UIElement parentContainer) inline private
Definition at line 886 of file UICharacterCreation.cs.
        {
            UIElement uielement = new UIElement
            {
                Width = StyleDimension.FromPixelsAndPercent(220f, 0f),
                Height = StyleDimension.FromPixelsAndPercent(158f, 0f),
                HAlign = 0.5f,
                VAlign = 0f
            };
            uielement.SetPadding(0f);
            parentContainer.Append(uielement);
            UIElement uielement2 = new UIPanel
            {
                Width = StyleDimension.FromPixelsAndPercent(220f, 0f),
                Height = StyleDimension.FromPixelsAndPercent(104f, 0f),
                HAlign = 0.5f,
                VAlign = 0f,
                Top = StyleDimension.FromPixelsAndPercent(10f, 0f)
            };
            uielement2.SetPadding(0f);
            uielement2.PaddingTop = 3f;
            uielement.Append(uielement2);
            uielement2.Append(this.CreateHSLSlider(UICharacterCreation.HSLSliderId.Hue));
            uielement2.Append(this.CreateHSLSlider(UICharacterCreation.HSLSliderId.Saturation));
            uielement2.Append(this.CreateHSLSlider(UICharacterCreation.HSLSliderId.Luminance));
            UIPanel uipanel = new UIPanel
            {
                VAlign = 1f,
                HAlign = 1f,
                Width = StyleDimension.FromPixelsAndPercent(100f, 0f),
                Height = StyleDimension.FromPixelsAndPercent(32f, 0f)
            };
            UIText uitext = new UIText("FFFFFF", 1f, false)
            {
                VAlign = 0.5f,
                HAlign = 0.5f
            };
            uipanel.Append(uitext);
            uielement.Append(uipanel);
            UIColoredImageButton uicoloredImageButton = new UIColoredImageButton(Main.Assets.Request<Texture2D>("Images/UI/CharCreation/Copy", 1), true)
            {
                VAlign = 1f,
                HAlign = 0f,
                Left = StyleDimension.FromPixelsAndPercent(0f, 0f)
            };
            uicoloredImageButton.OnLeftMouseDown += this.Click_CopyHex;
            uielement.Append(uicoloredImageButton);
            this._copyHexButton = uicoloredImageButton;
            UIColoredImageButton uicoloredImageButton2 = new UIColoredImageButton(Main.Assets.Request<Texture2D>("Images/UI/CharCreation/Paste", 1), true)
            {
                VAlign = 1f,
                HAlign = 0f,
                Left = StyleDimension.FromPixelsAndPercent(40f, 0f)
            };
            uicoloredImageButton2.OnLeftMouseDown += this.Click_PasteHex;
            uielement.Append(uicoloredImageButton2);
            this._pasteHexButton = uicoloredImageButton2;
            UIColoredImageButton uicoloredImageButton3 = new UIColoredImageButton(Main.Assets.Request<Texture2D>("Images/UI/CharCreation/Randomize", 1), true)
            {
                VAlign = 1f,
                HAlign = 0f,
                Left = StyleDimension.FromPixelsAndPercent(80f, 0f)
            };
            uicoloredImageButton3.OnLeftMouseDown += this.Click_RandomizeSingleColor;
            uielement.Append(uicoloredImageButton3);
            this._randomColorButton = uicoloredImageButton3;
            this._hslContainer = uielement;
            this._hslHexText = uitext;
            uicoloredImageButton.SetSnapPoint("Low", 0, null, null);
            uicoloredImageButton2.SetSnapPoint("Low", 1, null, null);
            uicoloredImageButton3.SetSnapPoint("Low", 2, null, null);
        }
References Terraria.UI.UIElement.Append(), Terraria.Main.Assets, Terraria.GameContent.UI.States.UICharacterCreation.Click_CopyHex(), Terraria.GameContent.UI.States.UICharacterCreation.Click_PasteHex(), Terraria.GameContent.UI.States.UICharacterCreation.Click_RandomizeSingleColor(), Terraria.GameContent.UI.States.UICharacterCreation.CreateHSLSlider(), Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.Left, Terraria.UI.UIElement.SetPadding(), Terraria.UI.UIElement.SetSnapPoint(), Terraria.UI.UIElement.Top, Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.BuildPage().