Terraria Decompiled: Terraria.GameContent.UI.States.UICharacterCreation.UpdateSelectedGender
UpdateSelectedGender()
void Terraria.GameContent.UI.States.UICharacterCreation.UpdateSelectedGender () inline private
Definition at line 1276 of file UICharacterCreation.cs.
        {
            if (this._oldMaleForVoiceAutoSwitch == this._player.Male)
            {
                this.PlayVoicePreview();
                return;
            }
            int voiceVariant = this._player.voiceVariant;
            if (voiceVariant != 1)
            {
                if (voiceVariant == 2)
                {
                    if (!this._oldMaleForVoiceAutoSwitch)
                    {
                        this._player.voiceVariant = 1;
                    }
                }
            }
            else if (this._oldMaleForVoiceAutoSwitch)
            {
                this._player.voiceVariant = 2;
            }
            this._oldMaleForVoiceAutoSwitch = this._player.Male;
            this.PlayVoicePreview();
        }
References Terraria.GameContent.UI.States.UICharacterCreation._oldMaleForVoiceAutoSwitch, Terraria.GameContent.UI.States.UICharacterCreation._player, Terraria.Player.Male, Terraria.GameContent.UI.States.UICharacterCreation.PlayVoicePreview(), and Terraria.Player.voiceVariant.
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.Click_CharClothStyle(), and Terraria.GameContent.UI.States.UICharacterCreation.Click_RandomizePlayer().