Terraria Decompiled: Terraria.GameContent.UI.States.UICharacterCreation.UpdateColorPickers
UpdateColorPickers()
void Terraria.GameContent.UI.States.UICharacterCreation.UpdateColorPickers () inline private
Definition at line 1939 of file UICharacterCreation.cs.
        {
            UICharacterCreation.CategoryId selectedPicker = this._selectedPicker;
            this._colorPickers[3].SetColor(this._player.hairColor);
            this._hairStylesCategoryButton.SetColor(this._player.hairColor);
            this._colorPickers[4].SetColor(this._player.eyeColor);
            this._colorPickers[5].SetColor(this._player.skinColor);
            this._colorPickers[6].SetColor(this._player.shirtColor);
            this._colorPickers[7].SetColor(this._player.underShirtColor);
            this._colorPickers[8].SetColor(this._player.pantsColor);
            this._colorPickers[9].SetColor(this._player.shoeColor);
        }
References Terraria.GameContent.UI.States.UICharacterCreation._colorPickers, Terraria.GameContent.UI.States.UICharacterCreation._hairStylesCategoryButton, Terraria.GameContent.UI.States.UICharacterCreation._player, Terraria.GameContent.UI.States.UICharacterCreation._selectedPicker, Terraria.Player.eyeColor, Terraria.Player.hairColor, Terraria.Player.pantsColor, Terraria.GameContent.UI.Elements.UIColoredImageButton.SetColor(), Terraria.Player.shirtColor, Terraria.Player.shoeColor, Terraria.Player.skinColor, and Terraria.Player.underShirtColor.
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.Click_PasteHex(), Terraria.GameContent.UI.States.UICharacterCreation.Click_PastePlayerTemplate(), Terraria.GameContent.UI.States.UICharacterCreation.Click_RandomizePlayer(), Terraria.GameContent.UI.States.UICharacterCreation.Click_RandomizeSingleColor(), and Terraria.GameContent.UI.States.UICharacterCreation.MakeCategoriesBar().