Terraria Decompiled: Terraria.GameContent.UI.States.UICharacterCreation.CreateColorPicker
CreateColorPicker()
UIColoredImageButton Terraria.GameContent.UI.States.UICharacterCreation.CreateColorPicker (UICharacterCreation::CategoryId id, string texturePath, float xPositionStart, float xPositionPerId) inline private
Definition at line 739 of file UICharacterCreation.cs.
        {
            UIColoredImageButton uicoloredImageButton = new UIColoredImageButton(Main.Assets.Request<Texture2D>(texturePath, 1), false);
            this._colorPickers[(int)id] = uicoloredImageButton;
            uicoloredImageButton.VAlign = 0f;
            uicoloredImageButton.HAlign = 0f;
            uicoloredImageButton.Left.Set(xPositionStart + (float)id * xPositionPerId, 0.5f);
            uicoloredImageButton.OnLeftMouseDown += this.Click_ColorPicker;
            uicoloredImageButton.SetSnapPoint("Top", (int)id, null, null);
            return uicoloredImageButton;
        }
References Terraria.GameContent.UI.States.UICharacterCreation._colorPickers, Terraria.Main.Assets, Terraria.GameContent.UI.States.UICharacterCreation.Click_ColorPicker(), int, Terraria.UI.UIElement.Left, Terraria.UI.StyleDimension.Set(), and Terraria.UI.UIElement.SetSnapPoint().
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.MakeCategoriesBar().