Terraria Decompiled: Terraria.GameContent.UI.States.UICharacterCreation.GetPlayerTemplateValues
GetPlayerTemplateValues()
string Terraria.GameContent.UI.States.UICharacterCreation.GetPlayerTemplateValues () inline private
Definition at line 1325 of file UICharacterCreation.cs.
        {
            string text = JsonConvert.SerializeObject(new Dictionary<string, object>
            {
                { "version", 1 },
                {
                    "hairStyle",
                    this._player.hair
                },
                {
                    "clothingStyle",
                    this._player.skinVariant
                },
                {
                    "voiceStyle",
                    this._player.voiceVariant
                },
                {
                    "voicePitch",
                    this._player.voicePitchOffset
                },
                {
                    "hairColor",
                    UICharacterCreation.GetHexText(this._player.hairColor)
                },
                {
                    "eyeColor",
                    UICharacterCreation.GetHexText(this._player.eyeColor)
                },
                {
                    "skinColor",
                    UICharacterCreation.GetHexText(this._player.skinColor)
                },
                {
                    "shirtColor",
                    UICharacterCreation.GetHexText(this._player.shirtColor)
                },
                {
                    "underShirtColor",
                    UICharacterCreation.GetHexText(this._player.underShirtColor)
                },
                {
                    "pantsColor",
                    UICharacterCreation.GetHexText(this._player.pantsColor)
                },
                {
                    "shoeColor",
                    UICharacterCreation.GetHexText(this._player.shoeColor)
                }
            }, new JsonSerializerSettings
            {
                TypeNameHandling = 4,
                MetadataPropertyHandling = 1,
                Formatting = 1
            });
            PlayerInput.PrettyPrintProfiles(ref text);
            return text;
        }
References Terraria.GameContent.UI.States.UICharacterCreation._player, Terraria.Player.eyeColor, Terraria.GameContent.UI.States.UICharacterCreation.GetHexText(), Terraria.Player.hairColor, Terraria.Player.pantsColor, Terraria.GameInput.PlayerInput.PrettyPrintProfiles(), Newtonsoft.Json.JsonConvert.SerializeObject(), Terraria.Player.shirtColor, Terraria.Player.shoeColor, Terraria.Player.skinColor, System.text, and Terraria.Player.underShirtColor.
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.Click_CopyPlayerTemplate(), Terraria.GameContent.UI.States.UICharacterCreation.Draw(), and Terraria.GameContent.UI.States.UICharacterCreation.UICharacterCreation().