Terraria Decompiled: Terraria.GameContent.UI.States.UICharacterCreation.CreateHSLSliderButtonBase
CreateHSLSliderButtonBase()
UIColoredSlider Terraria.GameContent.UI.States.UICharacterCreation.CreateHSLSliderButtonBase (UICharacterCreation::HSLSliderId id) inline private
Definition at line 979 of file UICharacterCreation.cs.
        {
            UIColoredSlider uicoloredSlider;
            if (id != UICharacterCreation.HSLSliderId.Saturation)
            {
                if (id != UICharacterCreation.HSLSliderId.Luminance)
                {
                    uicoloredSlider = new UIColoredSlider(LocalizedText.Empty, () => this.GetHSLSliderPosition(UICharacterCreation.HSLSliderId.Hue), delegate(float x)
                    {
                        this.UpdateHSLValue(UICharacterCreation.HSLSliderId.Hue, x);
                    }, new Action(this.UpdateHSL_H), (float x) => this.GetHSLSliderColorAt(UICharacterCreation.HSLSliderId.Hue, x), Color.Transparent);
                }
                else
                {
                    uicoloredSlider = new UIColoredSlider(LocalizedText.Empty, () => this.GetHSLSliderPosition(UICharacterCreation.HSLSliderId.Luminance), delegate(float x)
                    {
                        this.UpdateHSLValue(UICharacterCreation.HSLSliderId.Luminance, x);
                    }, new Action(this.UpdateHSL_L), (float x) => this.GetHSLSliderColorAt(UICharacterCreation.HSLSliderId.Luminance, x), Color.Transparent);
                }
            }
            else
            {
                uicoloredSlider = new UIColoredSlider(LocalizedText.Empty, () => this.GetHSLSliderPosition(UICharacterCreation.HSLSliderId.Saturation), delegate(float x)
                {
                    this.UpdateHSLValue(UICharacterCreation.HSLSliderId.Saturation, x);
                }, new Action(this.UpdateHSL_S), (float x) => this.GetHSLSliderColorAt(UICharacterCreation.HSLSliderId.Saturation, x), Color.Transparent);
            }
            return uicoloredSlider;
        }
References System.Action(), Terraria.Localization.LocalizedText.Empty, Terraria.GameContent.UI.States.UICharacterCreation.GetHSLSliderColorAt(), Microsoft.Xna.Framework.Color.Transparent, Terraria.GameContent.UI.States.UICharacterCreation.UpdateHSL_H(), Terraria.GameContent.UI.States.UICharacterCreation.UpdateHSL_L(), Terraria.GameContent.UI.States.UICharacterCreation.UpdateHSL_S(), and Terraria.GameContent.UI.States.UICharacterCreation.UpdateHSLValue().
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.CreateHSLSlider().