Terraria Decompiled: Terraria.GameContent.UI.States.UICharacterCreation.GetHexColor
GetHexColor()
bool Terraria.GameContent.UI.States.UICharacterCreation.GetHexColor (string hexString, out Vector3 hsl) inline private
Definition at line 1826 of file UICharacterCreation.cs.
        {
            if (hexString.StartsWith("#"))
            {
                hexString = hexString.Substring(1);
            }
            uint num;
            if (hexString.Length <= 6 && uint.TryParse(hexString, NumberStyles.HexNumber, CultureInfo.CurrentCulture, out num))
            {
                uint num2 = num & 255U;
                uint num3 = (num >> 8) & 255U;
                uint num4 = (num >> 16) & 255U;
                hsl = UICharacterCreation.RgbToScaledHsl(new Color((int)num4, (int)num3, (int)num2));
                return true;
            }
            hsl = Vector3.Zero;
            return false;
        }
References Microsoft.Xna.Framework.Graphics.Color, System.Globalization.CultureInfo.CurrentCulture, int, Terraria.GameContent.UI.States.UICharacterCreation.RgbToScaledHsl(), System.U, and Microsoft.Xna.Framework.Vector3.Zero.
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.Click_PasteHex(), and Terraria.GameContent.UI.States.UICharacterCreation.Click_PastePlayerTemplate().