Terraria Decompiled: Terraria.GameContent.UI.States.UICharacterCreation.Click_RandomizePlayer
Click_RandomizePlayer()
void Terraria.GameContent.UI.States.UICharacterCreation.Click_RandomizePlayer (UIMouseEvent evt, UIElement listeningElement) inline private
Definition at line 1530 of file UICharacterCreation.cs.
        {
            SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
            Player player = this._player;
            int num = Main.rand.Next(Main.Hairstyles.AvailableHairstyles.Count);
            player.hair = Main.Hairstyles.AvailableHairstyles[num];
            this._lastSelectedHairstyle = new int?(player.hair);
            player.eyeColor = UICharacterCreation.ScaledHslToRgb(UICharacterCreation.GetRandomColorVector());
            while ((int)(player.eyeColor.R + player.eyeColor.G + player.eyeColor.B) > 300)
            {
                player.eyeColor = UICharacterCreation.ScaledHslToRgb(UICharacterCreation.GetRandomColorVector());
            }
            float num2 = (float)Main.rand.Next(60, 120) * 0.01f;
            if (num2 > 1f)
            {
                num2 = 1f;
            }
            player.skinColor.R = (byte)((float)Main.rand.Next(240, 255) * num2);
            player.skinColor.G = (byte)((float)Main.rand.Next(110, 140) * num2);
            player.skinColor.B = (byte)((float)Main.rand.Next(75, 110) * num2);
            player.hairColor = UICharacterCreation.ScaledHslToRgb(UICharacterCreation.GetRandomColorVector());
            player.shirtColor = UICharacterCreation.ScaledHslToRgb(UICharacterCreation.GetRandomColorVector());
            player.underShirtColor = UICharacterCreation.ScaledHslToRgb(UICharacterCreation.GetRandomColorVector());
            player.pantsColor = UICharacterCreation.ScaledHslToRgb(UICharacterCreation.GetRandomColorVector());
            player.shoeColor = UICharacterCreation.ScaledHslToRgb(UICharacterCreation.GetRandomColorVector());
            player.skinVariant = this._validClothStyles[Main.rand.Next(this._validClothStyles.Length)];
            player.voiceVariant = (player.Male ? 1 : 2);
            if (Main.rand.Next(2) == 0)
            {
                player.voiceVariant = 3;
            }
            int num3 = player.hair + 1;
            if (num3 <= 135)
            {
                if (num3 <= 124)
                {
                    switch (num3)
                    {
                    case 5:
                    case 6:
                    case 7:
                    case 10:
                    case 12:
                    case 19:
                    case 22:
                    case 23:
                    case 26:
                    case 27:
                    case 30:
                    case 33:
                    case 34:
                    case 35:
                    case 37:
                    case 38:
                    case 39:
                    case 40:
                    case 41:
                    case 44:
                    case 45:
                    case 46:
                    case 47:
                    case 48:
                    case 49:
                    case 51:
                    case 56:
                    case 65:
                    case 66:
                    case 67:
                    case 68:
                    case 69:
                    case 70:
                    case 71:
                    case 72:
                    case 73:
                    case 74:
                    case 79:
                    case 80:
                    case 81:
                    case 82:
                    case 84:
                    case 85:
                    case 86:
                    case 87:
                    case 88:
                    case 90:
                    case 91:
                    case 92:
                    case 93:
                    case 95:
                    case 96:
                    case 98:
                    case 100:
                    case 102:
                    case 104:
                    case 107:
                    case 108:
                    case 113:
                        break;
                    case 8:
                    case 9:
                    case 11:
                    case 13:
                    case 14:
                    case 15:
                    case 16:
                    case 17:
                    case 18:
                    case 20:
                    case 21:
                    case 24:
                    case 25:
                    case 28:
                    case 29:
                    case 31:
                    case 32:
                    case 36:
                    case 42:
                    case 43:
                    case 50:
                    case 52:
                    case 53:
                    case 54:
                    case 55:
                    case 57:
                    case 58:
                    case 59:
                    case 60:
                    case 61:
                    case 62:
                    case 63:
                    case 64:
                    case 75:
                    case 76:
                    case 77:
                    case 78:
                    case 83:
                    case 89:
                    case 94:
                    case 97:
                    case 99:
                    case 101:
                    case 103:
                    case 105:
                    case 106:
                    case 109:
                    case 110:
                    case 111:
                    case 112:
                        goto IL_03E7;
                    default:
                        if (num3 != 124)
{
                            goto IL_03E7;
                        }
                        break;
                    }
                }
                else if (num3 != 126 && num3 - 133 > 2)
                {
                    goto IL_03E7;
                }
            }
            else if (num3 <= 147)
            {
                if (num3 != 144 && num3 - 146 > 1)
                {
                    goto IL_03E7;
                }
            }
            else if (num3 != 163 && num3 != 165)
            {
                goto IL_03E7;
            }
            player.Male = false;
            goto IL_03EE;
            IL_03E7:
            player.Male = true;
            IL_03EE:
            this._femaleArmor = (this._maleArmor = default(UICharacterCreation.ArmorAssignments));
            this.Click_CharClothStyle(null, null);
            this.UpdateSelectedGender();
            this.UpdateColorPickers();
        }
References Terraria.GameContent.UI.States.UICharacterCreation._player, Terraria.GameContent.UI.States.UICharacterCreation._validClothStyles, Microsoft.Xna.Framework.Color.B, Terraria.GameContent.UI.States.UICharacterCreation.Click_CharClothStyle(), Terraria.Player.eyeColor, Terraria.GameContent.UI.States.UICharacterCreation.GetRandomColorVector(), Terraria.Player.hair, Terraria.Main.Hairstyles, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.rand, Terraria.GameContent.UI.States.UICharacterCreation.ScaledHslToRgb(), Terraria.GameContent.UI.States.UICharacterCreation.UpdateColorPickers(), and Terraria.GameContent.UI.States.UICharacterCreation.UpdateSelectedGender().
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.MakeClothStylesMenu().