Terraria Decompiled: Terraria.GameContent.UI.States.UICharacterCreation.MakeHairstylesMenu
MakeHairstylesMenu()
void Terraria.GameContent.UI.States.UICharacterCreation.MakeHairstylesMenu (UIElement middleInnerPanel) inline private
Definition at line 120 of file UICharacterCreation.cs.
        {
            Main.Hairstyles.UpdateUnlocks();
            UIElement uielement = new UIElement
            {
                Width = StyleDimension.FromPixelsAndPercent(-10f, 1f),
                Height = StyleDimension.FromPixelsAndPercent(0f, 1f),
                HAlign = 0.5f,
                VAlign = 0.5f,
                Top = StyleDimension.FromPixels(6f)
            };
            middleInnerPanel.Append(uielement);
            uielement.SetPadding(0f);
            UIList uilist = new UIList
            {
                Width = StyleDimension.FromPixelsAndPercent(-18f, 1f),
                Height = StyleDimension.FromPixelsAndPercent(-6f, 1f)
            };
            uilist.SetPadding(4f);
            uielement.Append(uilist);
            UIScrollbar uiscrollbar = new UIScrollbar(UIScrollbar.ColorTheme.Blue)
            {
                HAlign = 1f,
                Height = StyleDimension.FromPixelsAndPercent(-30f, 1f),
                Top = StyleDimension.FromPixels(10f)
            };
            uiscrollbar.SetView(100f, 1000f);
            uilist.SetScrollbar(uiscrollbar);
            uielement.Append(uiscrollbar);
            int count = Main.Hairstyles.AvailableHairstyles.Count;
            UIElement uielement2 = new UIElement
            {
                Width = StyleDimension.FromPixelsAndPercent(0f, 1f),
                Height = StyleDimension.FromPixelsAndPercent((float)(48 * (count / 10 + ((count % 10 == 0) ? 0 : 1))), 0f)
            };
            uilist.Add(uielement2);
            uielement2.SetPadding(0f);
            for (int i = 0; i < count; i++)
            {
                UIHairStyleButton uihairStyleButton = new UIHairStyleButton(this._player, Main.Hairstyles.AvailableHairstyles[i])
                {
                    Left = StyleDimension.FromPixels((float)(i % 10) * 46f + 6f),
                    Top = StyleDimension.FromPixels((float)(i / 10) * 48f + 1f)
                };
                uihairStyleButton.SetSnapPoint("Middle", i, null, null);
                uihairStyleButton.SkipRenderingContent(i);
                uihairStyleButton.OnLeftMouseDown += this.RecordThatHairWasSelected;
                uielement2.Append(uihairStyleButton);
            }
            this._hairstylesContainer = uielement;
        }
References Terraria.GameContent.UI.States.UICharacterCreation._player, Terraria.GameContent.UI.Elements.UIList.Add(), Terraria.UI.UIElement.Append(), System.count, Terraria.UI.StyleDimension.FromPixels(), Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.Main.Hairstyles, Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.Left, Terraria.GameContent.UI.States.UICharacterCreation.RecordThatHairWasSelected(), Terraria.UI.UIElement.SetPadding(), Terraria.GameContent.UI.Elements.UIList.SetScrollbar(), Terraria.UI.UIElement.SetSnapPoint(), Terraria.GameContent.UI.Elements.UIScrollbar.SetView(), Terraria.GameContent.UI.Elements.UIHairStyleButton.SkipRenderingContent(), Terraria.UI.UIElement.Top, Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.BuildPage().