Terraria Decompiled: Terraria.GameContent.UI.States.UICharacterCreation.UpdatePreviewItems
UpdatePreviewItems()
void Terraria.GameContent.UI.States.UICharacterCreation.UpdatePreviewItems () inline private
Definition at line 529 of file UICharacterCreation.cs.
        {
            UICharacterCreation.ArmorAssignments armorAssignments = this._femaleArmor;
            if (this._player.Male)
            {
                armorAssignments = this._maleArmor;
            }
            this._player.armor[0].SetDefaults(armorAssignments.HeadItem, null);
            this._player.armor[1].SetDefaults(armorAssignments.BodyItem, null);
            this._player.armor[2].SetDefaults(armorAssignments.LegItem, null);
        }
References Terraria.GameContent.UI.States.UICharacterCreation._femaleArmor, Terraria.GameContent.UI.States.UICharacterCreation._maleArmor, Terraria.GameContent.UI.States.UICharacterCreation._player, Terraria.Player.armor, Terraria.GameContent.UI.States.UICharacterCreation.ArmorAssignments.BodyItem, Terraria.GameContent.UI.States.UICharacterCreation.ArmorAssignments.HeadItem, Terraria.GameContent.UI.States.UICharacterCreation.ArmorAssignments.LegItem, Terraria.Player.Male, and Terraria.Item.SetDefaults().
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.PreparePreview_ClothStyle(), Terraria.GameContent.UI.States.UICharacterCreation.PreparePreview_Main(), and Terraria.GameContent.UI.States.UICharacterCreation.SetupPlayerStatsAndInventoryBasedOnDifficulty().