Terraria Decompiled: Terraria.GameContent.UI.States.UICharacterCreation.GetHSLSliderPosition
GetHSLSliderPosition()
float Terraria.GameContent.UI.States.UICharacterCreation.GetHSLSliderPosition (UICharacterCreation::HSLSliderId id) inline private
Definition at line 1031 of file UICharacterCreation.cs.
        {
            switch (id)
            {
            case UICharacterCreation.HSLSliderId.Hue:
                return this._currentColorHSL.X;
            case UICharacterCreation.HSLSliderId.Saturation:
                return this._currentColorHSL.Y;
            case UICharacterCreation.HSLSliderId.Luminance:
                return this._currentColorHSL.Z;
            default:
                return 1f;
            }
        }
References Terraria.GameContent.UI.States.UICharacterCreation._currentColorHSL, Microsoft.Xna.Framework.Vector3.X, Microsoft.Xna.Framework.Vector3.Y, and Microsoft.Xna.Framework.Vector3.Z.
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.b__86_0(), Terraria.GameContent.UI.States.UICharacterCreation.b__86_3(), and Terraria.GameContent.UI.States.UICharacterCreation.b__86_6().