Terraria Decompiled: Terraria.GameContent.UI.States.UICharacterCreation.PlayVoicePreview
PlayVoicePreview()
void Terraria.GameContent.UI.States.UICharacterCreation.PlayVoicePreview () inline private
Definition at line 1497 of file UICharacterCreation.cs.
        {
            if (this._playedVoicePreviewThisFrame)
            {
                return;
            }
            this._playedVoicePreviewThisFrame = true;
            Vector2 position = this._player.position;
            this._player.position = new Vector2(-1f, -1f);
            this._player.PlayHurtSound();
            this._player.position = position;
        }
References Terraria.GameContent.UI.States.UICharacterCreation._playedVoicePreviewThisFrame, Terraria.GameContent.UI.States.UICharacterCreation._player, Terraria.Player.PlayHurtSound(), Terraria.Entity.position, and Microsoft.Xna.Framework.Graphics.Vector2.
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.Click_VoiceCycleBack(), Terraria.GameContent.UI.States.UICharacterCreation.Click_VoiceCycleForward(), Terraria.GameContent.UI.States.UICharacterCreation.Click_VoicePlay(), Terraria.GameContent.UI.States.UICharacterCreation.PitchSliderUpdate(), and Terraria.GameContent.UI.States.UICharacterCreation.UpdateSelectedGender().