Terraria Decompiled: Terraria.GameContent.UI.States.UICharacterCreation.Click_ColorPicker
Click_ColorPicker()
void Terraria.GameContent.UI.States.UICharacterCreation.Click_ColorPicker (UIMouseEvent evt, UIElement listeningElement) inline private
Definition at line 1200 of file UICharacterCreation.cs.
        {
            SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
            for (int i = 0; i < this._colorPickers.Length; i++)
            {
                if (this._colorPickers[i] == evt.Target)
                {
                    this.SelectColorPicker((UICharacterCreation.CategoryId)i);
                    return;
                }
            }
        }
References Terraria.GameContent.UI.States.UICharacterCreation._colorPickers, Terraria.Audio.SoundEngine.PlaySound(), Terraria.GameContent.UI.States.UICharacterCreation.SelectColorPicker(), and Terraria.UI.UIEvent.Target.
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.CreateColorPicker(), and Terraria.GameContent.UI.States.UICharacterCreation.CreateHSLSlider().