Terraria Decompiled: System.IO.Stream.RunReadWriteTaskWhenReady
RunReadWriteTaskWhenReady()
void System.IO.Stream.RunReadWriteTaskWhenReady (Task asyncWaiter, Stream::ReadWriteTask readWriteTask) inline private
Definition at line 406 of file Stream.cs.
        {
            if (asyncWaiter.IsCompleted)
            {
                this.RunReadWriteTask(readWriteTask);
                return;
            }
            asyncWaiter.ContinueWith(delegate(Task t, object state)
            {
                Stream.ReadWriteTask readWriteTask2 = (Stream.ReadWriteTask)state;
                readWriteTask2._stream.RunReadWriteTask(readWriteTask2);
            }, readWriteTask, default(CancellationToken), TaskContinuationOptions.ExecuteSynchronously, TaskScheduler.Default);
        }
References System.IO.Stream.ReadWriteTask._stream, System.Threading.Tasks.Task< TResult >.ContinueWith(), System.Threading.Tasks.TaskScheduler.Default, System.Threading.Tasks.Task< TResult >.IsCompleted, System.IO.Stream.RunReadWriteTask(), and System.state.
Referenced by System.IO.Stream.BeginReadInternal(), and System.IO.Stream.BeginWriteInternal().