Terraria Decompiled: System.IO.Stream.BeginRead
BeginRead()
virtual IAsyncResult System.IO.Stream.BeginRead (byte[] buffer, int offset, int count, AsyncCallback callback, object state) inline virtual
Reimplemented in System.IO.FileStream, System.IO.BufferedStream, System.IO.Stream.NullStream, System.IO.Stream.SyncStream, System.Security.Cryptography.CryptoStream, and System.IO.IsolatedStorage.IsolatedStorageFileStream.
Definition at line 226 of file Stream.cs.
        {
            return this.BeginReadInternal(buffer, offset, count, callback, state, false, true);
        }
References System.IO.Stream.BeginReadInternal(), System.count, System.offset, and System.state.
Referenced by System.IO.Stream.BeginEndReadAsync(), and System.IO.Stream.SyncStream.BeginRead().