Terraria Decompiled: System.IO.Stream.BeginReadInternal
BeginReadInternal()
IAsyncResult System.IO.Stream.BeginReadInternal (byte[] buffer, int offset, int count, AsyncCallback callback, object state, bool serializeAsynchronously, bool apm) inline package
Definition at line 232 of file Stream.cs.
        {
            if (!this.CanRead)
            {
                throw Error.GetReadNotSupported();
            }
            SemaphoreSlim semaphoreSlim = this.EnsureAsyncActiveSemaphoreInitialized();
            Task task = null;
            if (serializeAsynchronously)
            {
                task = semaphoreSlim.WaitAsync();
            }
            else
            {
                semaphoreSlim.Wait();
            }
            Stream.ReadWriteTask readWriteTask = new Stream.ReadWriteTask(true, apm, delegate
            {
                Stream.ReadWriteTask readWriteTask2 = Task.InternalCurrent as Stream.ReadWriteTask;
                int num;
                try
                {
                    num = readWriteTask2._stream.Read(readWriteTask2._buffer, readWriteTask2._offset, readWriteTask2._count);
                }
                finally
                {
                    if (!readWriteTask2._apm)
                    {
                        readWriteTask2._stream.FinishTrackingAsyncOperation();
                    }
                    readWriteTask2.ClearBeginState();
                }
                return num;
            }, state, this, buffer, offset, count, callback);
            if (task != null)
            {
                this.RunReadWriteTaskWhenReady(task, readWriteTask);
            }
            else
            {
                this.RunReadWriteTask(readWriteTask);
            }
            return readWriteTask;
        }
References System.IO.Stream.ReadWriteTask._apm, System.IO.Stream.ReadWriteTask._buffer, System.IO.Stream.ReadWriteTask._count, System.IO.Stream.ReadWriteTask._offset, System.IO.Stream.ReadWriteTask._stream, System.IO.Stream.CanRead, System.IO.Stream.ReadWriteTask.ClearBeginState(), System.count, System.IO.Stream.EnsureAsyncActiveSemaphoreInitialized(), System.IO.Stream.FinishTrackingAsyncOperation(), System.IO.Error.GetReadNotSupported(), System.offset, System.IO.Stream.Read(), System.IO.Stream.RunReadWriteTask(), System.IO.Stream.RunReadWriteTaskWhenReady(), System.state, System.task, System.Threading.SemaphoreSlim.Wait(), and System.Threading.SemaphoreSlim.WaitAsync().
Referenced by System.IO.Stream.BeginEndReadAsync(), System.IO.Stream.BeginRead(), and System.IO.Stream.SyncStream.BeginRead().