Terraria Decompiled: System.IO.Stream.Seek
Seek()
long System.IO.Stream.Seek (long offset, SeekOrigin origin) abstract
Referenced by System.Resources.ResourceReader._LoadObjectV1(), System.Resources.ResourceReader._LoadObjectV2(), System.Resources.ResourceReader._ReadResources(), System.Resources.ResourceReader.AllocateStringForNameIndex(), XPT.Core.Audio.MP3Sharp.IO.RiffFile.Backpatch(), XPT.Core.Audio.MP3Sharp.IO.RiffFile.Backpatch(), XPT.Core.Audio.MP3Sharp.IO.RiffFile.Close(), System.Resources.ManifestBasedResourceGroveler.CreateResourceSet(), Microsoft.Xna.Framework.Content.LzxDecoder.Decompress(), Ionic.Zip.ZipEntry.ExtractOne(), System.Resources.ResourceReader.FindPosForResource(), Ionic.Zip.SharedUtilities.FindSignature(), System.IO.BufferedStream.FlushRead(), Microsoft.Xna.Framework.Graphics.Texture2D.FromStream(), Microsoft.Xna.Framework.Graphics.Texture2D.FromStream(), Ionic.Zip.ZipInputStream.GetNextEntry(), System.Resources.ResourceReader.GetValueForNameIndex(), Ionic.Zip.ZipEntry.HandleUnexpectedDataDescriptor(), Microsoft.Xna.Framework.Graphics.FNA3D.INTERNAL_Skip(), Ionic.Zip.ZipEntry.InternalOpenReader(), System.IO.BinaryReader.InternalReadOneChar(), Terraria.WorldBuilding.WorldGenSnapshot.Load(), System.Resources.ResourceReader.LoadString(), Ionic.Zip.ZipEntry.PostProcessOutput(), Ionic.Zip.ZipInputStream.Read(), Microsoft.Xna.Framework.Content.Texture2DReader.Read(), Microsoft.Xna.Framework.Content.ContentManager.ReadAsset< T >(), Ionic.Zip.ZipFile.ReadCentralDirectory(), Ionic.Zip.ZipFile.ReadCentralDirectoryFooter(), Ionic.Zip.ZipEntry.ReadDirEntry(), Ionic.Zip.ZipEntry.ReadEntry(), Ionic.Zip.ZipEntry.ReadExtraField(), Ionic.Zip.ZipEntry.ReadHeader(), Ionic.Zip.ZipFile.ReadIntoInstance(), Ionic.Zip.ZipFile.ReadIntoInstance_Orig(), Ionic.BZip2.BitWriter.Reset(), System.Reflection.Emit.ModuleBuilder.Save(), System.IO.BinaryWriter.Seek(), XPT.Core.Audio.MP3Sharp.IO.RiffFile.Seek(), Ionic.Zip.CountingStream.Seek(), Ionic.Zip.OffsetStream.Seek(), Ionic.Zip.ZipInputStream.Seek(), Ionic.Zip.ZipSegmentedStream.Seek(), XPT.Core.Audio.MP3Sharp.MP3Stream.Seek(), System.IO.BufferedStream.Seek(), System.IO.Stream.SyncStream.Seek(), NVorbis.Ogg.PageReaderBase.SeekStream(), Ionic.Zip.ZipEntry.SetFdpLoh(), Ionic.Zip.ZipEntry.SetupCryptoForExtract(), System.Resources.ResourceReader.SkipInt32(), System.Resources.ResourceReader.SkipString(), Microsoft.Xna.Framework.Graphics.Texture2D.TextureDataFromStreamEXT(), Ionic.Zip.ZipSegmentedStream.TruncateBackward(), Ionic.Zip.ZipEntry.Write(), and Ionic.Zip.ZipFile.Zip64SeekToCentralDirectory().