Terraria Decompiled: System.IO.Stream.g__FinishReadAsync
g__FinishReadAsync()
static async ValueTask< int >< ReadAsync > System.IO.Stream.g__FinishReadAsync (Task< int > readTask, byte[] localBuffer, Memory< byte > localDestination) inline static package
Definition at line 705 of file Stream.cs.
        {
            int num2;
            try
            {
                int num = await readTask.ConfigureAwait(false);
                new Span<byte>(localBuffer, 0, num).CopyTo(localDestination.Span);
                num2 = num;
            }
            finally
            {
                ArrayPool<byte>.Shared.Return(localBuffer, false);
            }
            return num2;
        }
References System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Span< T >.CopyTo(), System.Buffers.ArrayPool< T >.Shared, and System.Memory< T >.Span.
Referenced by System.IO.Stream.d.MoveNext(), and System.IO.Stream.ReadAsync().