Terraria Decompiled: System.IO.Stream.BeginWrite
BeginWrite()
virtual IAsyncResult System.IO.Stream.BeginWrite (byte[] buffer, int offset, int count, AsyncCallback callback, object state) inline virtual
Reimplemented in System.IO.FileStream, System.IO.BufferedStream, System.IO.Stream.NullStream, System.IO.Stream.SyncStream, System.Security.Cryptography.CryptoStream, and System.IO.IsolatedStorage.IsolatedStorageFileStream.
Definition at line 353 of file Stream.cs.
        {
            return this.BeginWriteInternal(buffer, offset, count, callback, state, false, true);
        }
References System.IO.Stream.BeginWriteInternal(), System.count, System.offset, and System.state.
Referenced by System.IO.Stream.BeginEndWriteAsync(), and System.IO.Stream.SyncStream.BeginWrite().