Terraria Decompiled: System.IO.Stream.CopyToAsyncInternal
CopyToAsyncInternal()
async Task System.IO.Stream.CopyToAsyncInternal (Stream destination, int bufferSize, CancellationToken cancellationToken) inline private
Definition at line 111 of file Stream.cs.
        {
            byte[] buffer = ArrayPool<byte>.Shared.Rent(bufferSize);
            try
            {
                for (;;)
                {
                    int num = await this.ReadAsync(new Memory<byte>(buffer), cancellationToken).ConfigureAwait(false);
                    if (num == 0)
                    {
                        break;
                    }
                    await destination.WriteAsync(new ReadOnlyMemory<byte>(buffer, 0, num), cancellationToken).ConfigureAwait(false);
                }
            }
            finally
            {
                ArrayPool<byte>.Shared.Return(buffer, false);
            }
        }
References System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.destination, System.IO.Stream.ReadAsync(), and System.Buffers.ArrayPool< T >.Shared.
Referenced by System.IO.Stream.CopyToAsync(), and System.IO.Stream.d__28.MoveNext().