Terraria Decompiled: System.Threading.Timer.Change
Change() [3/5]
bool System.Threading.Timer.Change (long dueTime, long period, bool first) inline private
Definition at line 110 of file Timer.cs.
        {
            if (dueTime > (long)((ulong)(-2)))
            {
                throw new ArgumentOutOfRangeException("dueTime", "Due time too large");
            }
            if (period > (long)((ulong)(-2)))
            {
                throw new ArgumentOutOfRangeException("period", "Period too large");
            }
            if (dueTime < -1L)
            {
                throw new ArgumentOutOfRangeException("dueTime");
            }
            if (period < -1L)
            {
                throw new ArgumentOutOfRangeException("period");
            }
            if (this.disposed)
            {
                throw new ObjectDisposedException(null, Environment.GetResourceString("Cannot access a disposed object."));
            }
            this.due_time_ms = dueTime;
            this.period_ms = period;
            long num;
            if (dueTime == 0L)
            {
                num = 0L;
            }
            else if (dueTime < 0L)
            {
                num = long.MaxValue;
                if (first)
                {
                    this.next_run = num;
                    return true;
                }
            }
            else
            {
                num = dueTime * 10000L + Timer.GetTimeMonotonic();
            }
            Timer.scheduler.Change(this, num);
            return true;
        }
References System.Threading.Timer.Change(), System.Threading.Timer.disposed, System.Environment.GetResourceString(), System.Threading.Timer.GetTimeMonotonic(), System.L, and System.Threading.Timer.scheduler.