Terraria Decompiled: System.Threading.Timer.Init
Init()
void System.Threading.Timer.Init (TimerCallback callback, object state, long dueTime, long period) inline private
Definition at line 58 of file Timer.cs.
        {
            if (callback == null)
            {
                throw new ArgumentNullException("callback");
            }
            this.callback = callback;
            this.state = state;
            this.is_dead = false;
            this.is_added = false;
            this.Change(dueTime, period, true);
        }
References System.Threading.Timer.callback, System.Threading.Timer.Change(), and System.Threading.Timer.state.
Referenced by System.Threading.Timer.Timer(), System.Threading.Timer.Timer(), System.Threading.Timer.Timer(), System.Threading.Timer.Timer(), and System.Threading.Timer.Timer().