Terraria Decompiled: System.IO.__Error.GetDisplayablePath
GetDisplayablePath()
static string System.IO.__Error.GetDisplayablePath (string path, bool isInvalidPath) inline static package
Definition at line 72 of file __Error.cs.
        {
            if (string.IsNullOrEmpty(path))
            {
                return string.Empty;
            }
            if (path.Length < 2)
            {
                return path;
            }
            if (PathInternal.IsPartiallyQualified(path) && !isInvalidPath)
            {
                return path;
            }
            bool flag = false;
            try
            {
                if (!isInvalidPath)
                {
                    flag = true;
                }
            }
            catch (SecurityException)
            {
            }
            catch (ArgumentException)
            {
            }
            catch (NotSupportedException)
            {
            }
            if (!flag)
            {
                if (Path.IsDirectorySeparator(path[path.Length - 1]))
                {
                    path = Environment.GetResourceString("<Path discovery permission to the specified directory was denied.>");
                }
                else
                {
                    path = Path.GetFileName(path);
                }
            }
            return path;
        }
References System.IO.Path.GetFileName(), System.Environment.GetResourceString(), System.IO.Path.IsDirectorySeparator(), and System.IO.PathInternal.IsPartiallyQualified().
Referenced by System.IO.__Error.WinIOError().