Terraria Decompiled: System.IO.__Error.WinIOError
WinIOError()
static void System.IO.__Error.WinIOError (int errorCode, string maybeFullPath) inline static package
Definition at line 119 of file __Error.cs.
        {
            bool flag = errorCode == 123 || errorCode == 161;
            string displayablePath = __Error.GetDisplayablePath(maybeFullPath, flag);
            if (errorCode <= 80)
            {
                if (errorCode <= 15)
                {
                    switch (errorCode)
                    {
                    case 2:
                        if (displayablePath.Length == 0)
{
                            throw new FileNotFoundException(Environment.GetResourceString("Unable to find the specified file."));
                        }
                        throw new FileNotFoundException(Environment.GetResourceString("Could not find file '{0}'.", new object[] { displayablePath }), displayablePath);
                    case 3:
                        if (displayablePath.Length == 0)
{
                            throw new DirectoryNotFoundException(Environment.GetResourceString("Could not find a part of the path."));
                        }
                        throw new DirectoryNotFoundException(Environment.GetResourceString("Could not find a part of the path '{0}'.", new object[] { displayablePath }));
                    case 4:
                        break;
                    case 5:
                        if (displayablePath.Length == 0)
{
                            throw new UnauthorizedAccessException(Environment.GetResourceString("Access to the path is denied."));
                        }
                        throw new UnauthorizedAccessException(Environment.GetResourceString("Access to the path '{0}' is denied.", new object[] { displayablePath }));
                    default:
                        if (errorCode == 15)
{
                            throw new DriveNotFoundException(Environment.GetResourceString("Could not find the drive '{0}'. The drive might not be ready or might not be mapped.", new object[] { displayablePath }));
                        }
                        break;
                    }
                }
                else if (errorCode != 32)
                {
                    if (errorCode == 80)
                    {
                        if (displayablePath.Length != 0)
{
                            throw new IOException(Environment.GetResourceString("The file '{0}' already exists.", new object[] { displayablePath }), Win32Native.MakeHRFromErrorCode(errorCode));
                        }
                    }
                }
                else
                {
                    if (displayablePath.Length == 0)
                    {
                        throw new IOException(Environment.GetResourceString("The process cannot access the file because it is being used by another process."), Win32Native.MakeHRFromErrorCode(errorCode));
                    }
                    throw new IOException(Environment.GetResourceString("The process cannot access the file '{0}' because it is being used by another process.", new object[] { displayablePath }), Win32Native.MakeHRFromErrorCode(errorCode));
                }
            }
            else if (errorCode <= 183)
            {
                if (errorCode == 87)
                {
                    throw new IOException(Win32Native.GetMessage(errorCode), Win32Native.MakeHRFromErrorCode(errorCode));
                }
                if (errorCode == 183)
                {
                    if (displayablePath.Length != 0)
                    {
                        throw new IOException(Environment.GetResourceString("Cannot create \"{0}\" because a file or directory with the same name already exists.", new object[] { displayablePath }), Win32Native.MakeHRFromErrorCode(errorCode));
                    }
                }
            }
            else
            {
                if (errorCode == 206)
                {
                    throw new PathTooLongException(Environment.GetResourceString("The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters."));
                }
                if (errorCode == 995)
                {
                    throw new OperationCanceledException();
                }
            }
            throw new IOException(Win32Native.GetMessage(errorCode), Win32Native.MakeHRFromErrorCode(errorCode));
        }
References System.IO.__Error.GetDisplayablePath(), Microsoft.Win32.Win32Native.GetMessage(), System.Environment.GetResourceString(), and Microsoft.Win32.Win32Native.MakeHRFromErrorCode().
Referenced by System.Threading.EventWaitHandle.EventWaitHandle(), System.Threading.EventWaitHandle.EventWaitHandle(), System.Threading.EventWaitHandle.OpenExisting(), and System.Threading.EventWaitHandle.OpenExistingWorker().