Terraria Decompiled: System.Buffers.ReadOnlySequence.Slice
Slice() [4/9]
ReadOnlySequence< T > System.Buffers.ReadOnlySequence< T >.Slice (long start, long length) inline
Definition at line 182 of file ReadOnlySequence.cs.
        {
            if (start < 0L || length < 0L)
            {
                ThrowHelper.ThrowStartOrEndArgumentValidationException(start);
            }
            int num = ReadOnlySequence<T>.GetIndex(this._startInteger);
            int index = ReadOnlySequence<T>.GetIndex(this._endInteger);
            object startObject = this._startObject;
            object endObject = this._endObject;
            SequencePosition sequencePosition;
            SequencePosition sequencePosition2;
            if (startObject != endObject)
            {
                ReadOnlySequenceSegment<T> readOnlySequenceSegment = (ReadOnlySequenceSegment<T>)startObject;
                int num2 = readOnlySequenceSegment.Memory.Length - num;
                if ((long)num2 > start)
                {
                    num += (int)start;
                    sequencePosition = new SequencePosition(startObject, num);
                    sequencePosition2 = ReadOnlySequence<T>.GetEndPosition(readOnlySequenceSegment, startObject, num, endObject, index, length);
                }
                else
                {
                    if (num2 < 0)
                    {
                        ThrowHelper.ThrowArgumentOutOfRangeException_PositionOutOfRange();
                    }
                    sequencePosition = ReadOnlySequence<T>.SeekMultiSegment(readOnlySequenceSegment.Next, endObject, index, start - (long)num2, ExceptionArgument.start);
                    int index2 = ReadOnlySequence<T>.GetIndex(in sequencePosition);
                    object @object = sequencePosition.GetObject();
                    if (@object != endObject)
                    {
                        sequencePosition2 = ReadOnlySequence<T>.GetEndPosition((ReadOnlySequenceSegment<T>)@object, @object, index2, endObject, index, length);
                    }
                    else
                    {
                        if ((long)(index - index2) < length)
{
                            ThrowHelper.ThrowStartOrEndArgumentValidationException(0L);
                        }
                        sequencePosition2 = new SequencePosition(@object, index2 + (int)length);
                    }
                }
            }
            else
            {
                if ((long)(index - num) < start)
                {
                    ThrowHelper.ThrowStartOrEndArgumentValidationException(-1L);
                }
                num += (int)start;
                sequencePosition = new SequencePosition(startObject, num);
                if ((long)(index - num) < length)
                {
                    ThrowHelper.ThrowStartOrEndArgumentValidationException(0L);
                }
                sequencePosition2 = new SequencePosition(startObject, num + (int)length);
            }
            return this.SliceImpl(in sequencePosition, in sequencePosition2);
        }
References System.Buffers.ReadOnlySequence< T >._endInteger, System.Buffers.ReadOnlySequence< T >._endObject, System.Buffers.ReadOnlySequence< T >._startInteger, System.Buffers.ReadOnlySequence< T >._startObject, System.Buffers.ReadOnlySequence< T >.GetEndPosition(), System.Buffers.ReadOnlySequence< T >.GetIndex(), System.index, int, System.L, System.length, System.Buffers.ReadOnlySequenceSegment< T >.Next, System.Buffers.ReadOnlySequence< T >.SeekMultiSegment(), System.Buffers.ReadOnlySequence< T >.SliceImpl(), System.start, System.ThrowHelper.ThrowArgumentOutOfRangeException_PositionOutOfRange(), and System.ThrowHelper.ThrowStartOrEndArgumentValidationException().
Referenced by System.Buffers.ReadOnlySequence< T >.Slice(), System.Buffers.ReadOnlySequence< T >.Slice(), and System.Buffers.ReadOnlySequence< T >.Slice().