Terraria Decompiled: System.Buffers.ReadOnlySequence.ReadOnlySequence
ReadOnlySequence() [5/6]
System.Buffers.ReadOnlySequence< T >.ReadOnlySequence (ReadOnlyMemory< T > memory) inline
Definition at line 136 of file ReadOnlySequence.cs.
        {
            MemoryManager<T> memoryManager;
            int num;
            int num2;
            if (MemoryMarshal.TryGetMemoryManager<T, MemoryManager<T>>(memory, out memoryManager, out num, out num2))
            {
                this._startObject = memoryManager;
                this._endObject = memoryManager;
                this._startInteger = ReadOnlySequence.MemoryManagerToSequenceStart(num);
                this._endInteger = ReadOnlySequence.MemoryManagerToSequenceEnd(num2);
                return;
            }
            ArraySegment<T> arraySegment;
            if (MemoryMarshal.TryGetArray<T>(memory, out arraySegment))
            {
                T[] array = arraySegment.Array;
                int offset = arraySegment.Offset;
                this._startObject = array;
                this._endObject = array;
                this._startInteger = ReadOnlySequence.ArrayToSequenceStart(offset);
                this._endInteger = ReadOnlySequence.ArrayToSequenceEnd(offset + arraySegment.Count);
                return;
            }
            if (typeof(T) == typeof(char))
            {
                string text;
                int num3;
                if (!MemoryMarshal.TryGetString((ReadOnlyMemory<char>)memory, out text, out num3, out num2))
                {
                    ThrowHelper.ThrowInvalidOperationException();
                }
                this._startObject = text;
                this._endObject = text;
                this._startInteger = ReadOnlySequence.StringToSequenceStart(num3);
                this._endInteger = ReadOnlySequence.StringToSequenceEnd(num3 + num2);
                return;
            }
            ThrowHelper.ThrowInvalidOperationException();
            this._startObject = null;
            this._endObject = null;
            this._startInteger = 0;
            this._endInteger = 0;
        }
References System.ArraySegment< T >.Array, System.array, System.Buffers.ReadOnlySequence< T >.ArrayToSequenceEnd(), System.Buffers.ReadOnlySequence< T >.ArrayToSequenceStart(), System.ArraySegment< T >.Count, System.Buffers.ReadOnlySequence< T >.MemoryManagerToSequenceEnd(), System.Buffers.ReadOnlySequence< T >.MemoryManagerToSequenceStart(), System.ArraySegment< T >.Offset, System.offset, System.Buffers.ReadOnlySequence< T >.StringToSequenceEnd(), System.Buffers.ReadOnlySequence< T >.StringToSequenceStart(), System.text, System.ThrowHelper.ThrowInvalidOperationException(), and System.Runtime.InteropServices.MemoryMarshal.TryGetString().