Terraria Decompiled: System.Buffers.ReadOnlySequence.GetFirstBufferSlow
GetFirstBufferSlow()
ReadOnlyMemory< T > System.Buffers.ReadOnlySequence< T >.GetFirstBufferSlow (object startObject, bool isMultiSegment) inline private
Definition at line 560 of file ReadOnlySequence.cs.
        {
            if (isMultiSegment)
            {
                ThrowHelper.ThrowInvalidOperationException_EndPositionNotReached();
            }
            int num = this._startInteger;
            int endInteger = this._endInteger;
            if (num >= 0)
            {
                return new ReadOnlyMemory<T>((T[])startObject, num, (endInteger & int.MaxValue) - num);
            }
            if (typeof(T) == typeof(char) && endInteger < 0)
            {
                return (ReadOnlyMemory<T>)((string)startObject).AsMemory(num & int.MaxValue, endInteger - num);
            }
            num &= int.MaxValue;
            return ((MemoryManager<T>)startObject).Memory.Slice(num, endInteger - num);
        }
References System.Buffers.ReadOnlySequence< T >._endInteger, System.Buffers.ReadOnlySequence< T >._startInteger, System.Memory< T >.Slice(), and System.ThrowHelper.ThrowInvalidOperationException_EndPositionNotReached().
Referenced by System.Buffers.ReadOnlySequence< T >.GetFirstBuffer().