Terraria Decompiled: System.Buffers.ReadOnlySequence.Slice
Slice() [8/9]
ReadOnlySequence< T > System.Buffers.ReadOnlySequence< T >.Slice (SequencePosition start, long length) inline
Definition at line 303 of file ReadOnlySequence.cs.
        {
            uint index = (uint)ReadOnlySequence<T>.GetIndex(this._startInteger);
            object startObject = this._startObject;
            uint index2 = (uint)ReadOnlySequence<T>.GetIndex(this._endInteger);
            object endObject = this._endObject;
            uint num = (uint)ReadOnlySequence<T>.GetIndex(in start);
            object obj = start.GetObject();
            if (obj == null)
            {
                num = index;
                obj = this._startObject;
            }
            if (startObject == endObject)
            {
                if (!ReadOnlySequence<T>.InRange(num, index, index2))
                {
                    ThrowHelper.ThrowArgumentOutOfRangeException_PositionOutOfRange();
                }
                if (length < 0L)
                {
                    ThrowHelper.ThrowStartOrEndArgumentValidationException(0L);
                }
                if ((ulong)(index2 - num) < (ulong)length)
                {
                    ThrowHelper.ThrowStartOrEndArgumentValidationException(0L);
                }
            }
            else
            {
                ReadOnlySequenceSegment<T> readOnlySequenceSegment = (ReadOnlySequenceSegment<T>)obj;
                long num2 = readOnlySequenceSegment.RunningIndex + (long)((ulong)num);
                ulong num3 = (ulong)(((ReadOnlySequenceSegment<T>)startObject).RunningIndex + (long)((ulong)index));
                ulong num4 = (ulong)(((ReadOnlySequenceSegment<T>)endObject).RunningIndex + (long)((ulong)index2));
                if (!ReadOnlySequence<T>.InRange((ulong)num2, num3, num4))
                {
                    ThrowHelper.ThrowArgumentOutOfRangeException_PositionOutOfRange();
                }
                if (length < 0L)
                {
                    ThrowHelper.ThrowStartOrEndArgumentValidationException(0L);
                }
                if (num2 + length > (long)num4)
                {
                    ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.length);
                }
                int num5 = readOnlySequenceSegment.Memory.Length - (int)num;
                if ((long)num5 < length)
                {
                    if (num5 < 0)
                    {
                        ThrowHelper.ThrowArgumentOutOfRangeException_PositionOutOfRange();
                    }
                    SequencePosition sequencePosition = ReadOnlySequence<T>.SeekMultiSegment(readOnlySequenceSegment.Next, endObject, (int)index2, length - (long)num5, ExceptionArgument.length);
                    return this.SliceImpl(in start, in sequencePosition);
                }
            }
            SequencePosition sequencePosition2 = new SequencePosition(obj, (int)num);
            SequencePosition sequencePosition3 = new SequencePosition(obj, (int)(num + (uint)((int)length)));
            return this.SliceImpl(in sequencePosition2, in sequencePosition3);
        }
References System.Buffers.ReadOnlySequence< T >._endInteger, System.Buffers.ReadOnlySequence< T >._endObject, System.Buffers.ReadOnlySequence< T >._startInteger, System.Buffers.ReadOnlySequence< T >._startObject, System.Buffers.ReadOnlySequence< T >.GetIndex(), System.index, System.Buffers.ReadOnlySequence< T >.InRange(), int, System.L, System.length, long, System.Buffers.ReadOnlySequenceSegment< T >.Next, System.obj, System.Buffers.ReadOnlySequence< T >.SeekMultiSegment(), System.Buffers.ReadOnlySequence< T >.SliceImpl(), System.start, System.ThrowHelper.ThrowArgumentOutOfRangeException(), System.ThrowHelper.ThrowArgumentOutOfRangeException_PositionOutOfRange(), and System.ThrowHelper.ThrowStartOrEndArgumentValidationException().