Terraria Decompiled: System.Buffers.ReadOnlySequence.TryGetBuffer
TryGetBuffer()
bool System.Buffers.ReadOnlySequence< T >.TryGetBuffer (in SequencePosition position, out ReadOnlyMemory< T > memory, out SequencePosition next) inline package
Definition at line 481 of file ReadOnlySequence.cs.
        {
            object @object = position.GetObject();
            next = default(SequencePosition);
            if (@object == null)
            {
                memory = default(ReadOnlyMemory<T>);
                return false;
            }
            ReadOnlySequence<T>.SequenceType sequenceType = this.GetSequenceType();
            object endObject = this._endObject;
            int index = ReadOnlySequence<T>.GetIndex(in position);
            int index2 = ReadOnlySequence<T>.GetIndex(this._endInteger);
            if (sequenceType == ReadOnlySequence<T>.SequenceType.MultiSegment)
            {
                ReadOnlySequenceSegment<T> readOnlySequenceSegment = (ReadOnlySequenceSegment<T>)@object;
                if (readOnlySequenceSegment != endObject)
                {
                    ReadOnlySequenceSegment<T> next2 = readOnlySequenceSegment.Next;
                    if (next2 == null)
                    {
                        ThrowHelper.ThrowInvalidOperationException_EndPositionNotReached();
                    }
                    next = new SequencePosition(next2, 0);
                    memory = readOnlySequenceSegment.Memory.Slice(index);
                }
                else
                {
                    memory = readOnlySequenceSegment.Memory.Slice(index, index2 - index);
                }
            }
            else
            {
                if (@object != endObject)
                {
                    ThrowHelper.ThrowInvalidOperationException_EndPositionNotReached();
                }
                if (sequenceType == ReadOnlySequence<T>.SequenceType.Array)
                {
                    memory = new ReadOnlyMemory<T>((T[])@object, index, index2 - index);
                }
                else if (typeof(T) == typeof(char) && sequenceType == ReadOnlySequence<T>.SequenceType.String)
                {
                    memory = (ReadOnlyMemory<T>)((string)@object).AsMemory(index, index2 - index);
                }
                else
                {
                    memory = ((MemoryManager<T>)@object).Memory.Slice(index, index2 - index);
                }
            }
            return true;
        }
References System.Buffers.ReadOnlySequence< T >._endInteger, System.Buffers.ReadOnlySequence< T >._endObject, System.Buffers.ReadOnlySequence< T >.GetIndex(), System.Buffers.ReadOnlySequence< T >.GetSequenceType(), System.index, System.Buffers.ReadOnlySequenceSegment< T >.Memory, System.Buffers.ReadOnlySequenceSegment< T >.Next, and System.ThrowHelper.ThrowInvalidOperationException_EndPositionNotReached().
Referenced by System.Buffers.ReadOnlySequence< T >.TryGet().