Terraria Decompiled: System.Buffers.ReadOnlySequence.Slice
Slice() [5/9]
ReadOnlySequence< T > System.Buffers.ReadOnlySequence< T >.Slice (long start, SequencePosition end) inline
Definition at line 245 of file ReadOnlySequence.cs.
        {
            if (start < 0L)
            {
                ThrowHelper.ThrowStartOrEndArgumentValidationException(start);
            }
            uint index = (uint)ReadOnlySequence<T>.GetIndex(this._startInteger);
            object startObject = this._startObject;
            uint index2 = (uint)ReadOnlySequence<T>.GetIndex(this._endInteger);
            object endObject = this._endObject;
            uint num = (uint)ReadOnlySequence<T>.GetIndex(in end);
            object obj = end.GetObject();
            if (obj == null)
            {
                obj = this._startObject;
                num = index;
            }
            if (startObject == endObject)
            {
                if (!ReadOnlySequence<T>.InRange(num, index, index2))
                {
                    ThrowHelper.ThrowArgumentOutOfRangeException_PositionOutOfRange();
                }
                if ((ulong)(num - index) < (ulong)start)
                {
                    ThrowHelper.ThrowStartOrEndArgumentValidationException(-1L);
                }
            }
            else
            {
                ReadOnlySequenceSegment<T> readOnlySequenceSegment = (ReadOnlySequenceSegment<T>)startObject;
                ulong num2 = (ulong)(readOnlySequenceSegment.RunningIndex + (long)((ulong)index));
                ulong num3 = (ulong)(((ReadOnlySequenceSegment<T>)obj).RunningIndex + (long)((ulong)num));
                if (!ReadOnlySequence<T>.InRange(num3, num2, (ulong)(((ReadOnlySequenceSegment<T>)endObject).RunningIndex + (long)((ulong)index2))))
                {
                    ThrowHelper.ThrowArgumentOutOfRangeException_PositionOutOfRange();
                }
                if (num2 + (ulong)start > num3)
                {
                    ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.start);
                }
                int num4 = readOnlySequenceSegment.Memory.Length - (int)index;
                if ((long)num4 <= start)
                {
                    if (num4 < 0)
                    {
                        ThrowHelper.ThrowArgumentOutOfRangeException_PositionOutOfRange();
                    }
                    SequencePosition sequencePosition = ReadOnlySequence<T>.SeekMultiSegment(readOnlySequenceSegment.Next, obj, (int)num, start - (long)num4, ExceptionArgument.start);
                    return this.SliceImpl(in sequencePosition, in end);
                }
            }
            SequencePosition sequencePosition2 = new SequencePosition(startObject, (int)(index + (uint)((int)start)));
            SequencePosition sequencePosition3 = new SequencePosition(obj, (int)num);
            return this.SliceImpl(in sequencePosition2, in sequencePosition3);
        }
References System.Buffers.ReadOnlySequence< T >._endInteger, System.Buffers.ReadOnlySequence< T >._endObject, System.Buffers.ReadOnlySequence< T >._startInteger, System.Buffers.ReadOnlySequence< T >._startObject, System.Buffers.ReadOnlySequence< T >.GetIndex(), System.SequencePosition.GetObject(), System.index, System.Buffers.ReadOnlySequence< T >.InRange(), int, System.L, long, System.Buffers.ReadOnlySequenceSegment< T >.Next, System.obj, System.Buffers.ReadOnlySequenceSegment< T >.RunningIndex, System.Buffers.ReadOnlySequence< T >.SeekMultiSegment(), System.Buffers.ReadOnlySequence< T >.SliceImpl(), System.start, System.ThrowHelper.ThrowArgumentOutOfRangeException(), System.ThrowHelper.ThrowArgumentOutOfRangeException_PositionOutOfRange(), and System.ThrowHelper.ThrowStartOrEndArgumentValidationException().