Terraria Decompiled: System.Buffers.ReadOnlySequence.ReadOnlySequence
ReadOnlySequence() [4/6]
System.Buffers.ReadOnlySequence< T >.ReadOnlySequence (T[] array, int start, int length) inline
Definition at line 123 of file ReadOnlySequence.cs.
        {
            if (array == null || start > array.Length || length > array.Length - start)
            {
                ThrowHelper.ThrowArgumentValidationException(array, start);
            }
            this._startObject = array;
            this._endObject = array;
            this._startInteger = ReadOnlySequence.ArrayToSequenceStart(start);
            this._endInteger = ReadOnlySequence.ArrayToSequenceEnd(start + length);
        }
References System.array, System.Buffers.ReadOnlySequence< T >.ArrayToSequenceEnd(), System.Buffers.ReadOnlySequence< T >.ArrayToSequenceStart(), System.length, System.start, and System.ThrowHelper.ThrowArgumentValidationException().