Terraria Decompiled: System.Buffers.ReadOnlySequence.BoundsCheck
BoundsCheck() [1/2]
void System.Buffers.ReadOnlySequence< T >.BoundsCheck (in SequencePosition position, bool positionIsNotNull) inline private
Definition at line 706 of file ReadOnlySequence.cs.
        {
            uint index = (uint)ReadOnlySequence<T>.GetIndex(in position);
            object startObject = this._startObject;
            object endObject = this._endObject;
            uint index2 = (uint)ReadOnlySequence<T>.GetIndex(this._startInteger);
            uint index3 = (uint)ReadOnlySequence<T>.GetIndex(this._endInteger);
            if (startObject == endObject)
            {
                if (!ReadOnlySequence<T>.InRange(index, index2, index3))
                {
                    ThrowHelper.ThrowArgumentOutOfRangeException_PositionOutOfRange();
                    return;
                }
            }
            else
            {
                ulong num = (ulong)(((ReadOnlySequenceSegment<T>)startObject).RunningIndex + (long)((ulong)index2));
                long num2 = 0L;
                if (positionIsNotNull)
                {
                    num2 = ((ReadOnlySequenceSegment<T>)position.GetObject()).RunningIndex;
                }
                if (!ReadOnlySequence<T>.InRange((ulong)(num2 + (long)((ulong)index)), num, (ulong)(((ReadOnlySequenceSegment<T>)endObject).RunningIndex + (long)((ulong)index3))))
                {
                    ThrowHelper.ThrowArgumentOutOfRangeException_PositionOutOfRange();
                }
            }
        }
References System.Buffers.ReadOnlySequence< T >._endInteger, System.Buffers.ReadOnlySequence< T >._endObject, System.Buffers.ReadOnlySequence< T >._startInteger, System.Buffers.ReadOnlySequence< T >._startObject, System.Buffers.ReadOnlySequence< T >.GetIndex(), System.index, System.Buffers.ReadOnlySequence< T >.InRange(), System.L, long, and System.ThrowHelper.ThrowArgumentOutOfRangeException_PositionOutOfRange().
Referenced by System.Buffers.ReadOnlySequence< T >.Slice(), and System.Buffers.ReadOnlySequence< T >.Slice().