Terraria Decompiled: NVorbis.Memory.Empty
Empty
Memory<T> NVorbis.Memory< T >.Empty = new Memory<T>(new T[0]) static get
Definition at line 31 of file Memory.cs.
        {
            [CompilerGenerated]
            get
            {
                return Memory<T>.<Empty>k__BackingField;
            }
        } = new Memory<T>(new T[0]);
Referenced by NVorbis.Ogg.ForwardOnlyPacketProvider.Done(), NVorbis.Ogg.PacketProvider.GetPacketData(), and NVorbis.Ogg.Packet.ReadNextByte().