Terraria Decompiled: rail.IRailGameImpl.GetCurrentBranchInfo
GetCurrentBranchInfo()
virtual RailResult rail.IRailGameImpl.GetCurrentBranchInfo (RailBranchInfo branch_info) inline virtual
Implements rail.IRailGame.
Definition at line 157 of file IRailGameImpl.cs.
        {
            IntPtr intPtr = ((branch_info == null) ? IntPtr.Zero : RAIL_API_PINVOKE.new_RailBranchInfo__SWIG_0());
            RailResult railResult;
            try
            {
                railResult = (RailResult)RAIL_API_PINVOKE.IRailGame_GetCurrentBranchInfo(this.swigCPtr_, intPtr);
            }
            finally
            {
                if (branch_info != null)
                {
                    RailConverter.Cpp2Csharp(intPtr, branch_info);
                }
                RAIL_API_PINVOKE.delete_RailBranchInfo(intPtr);
            }
            return railResult;
        }
References rail.RailConverter.Cpp2Csharp(), rail.RAIL_API_PINVOKE.delete_RailBranchInfo(), rail.RAIL_API_PINVOKE.IRailGame_GetCurrentBranchInfo(), rail.RAIL_API_PINVOKE.new_RailBranchInfo__SWIG_0(), and System.IntPtr.Zero.