Terraria Decompiled: System.Security.AccessControl.ObjectAce.ObjectAce
ObjectAce() [3/3]
System.Security.AccessControl.ObjectAce.ObjectAce (byte[] binaryForm, int offset) inline package
Definition at line 33 of file ObjectAce.cs.
            : base(binaryForm, offset)
        {
            int num = (int)GenericAce.ReadUShort(binaryForm, offset + 2);
            int num2 = 12 + SecurityIdentifier.MinBinaryLength;
            if (offset > binaryForm.Length - num)
            {
                throw new ArgumentException("Invalid ACE - truncated", "binaryForm");
            }
            if (num < num2)
            {
                throw new ArgumentException("Invalid ACE", "binaryForm");
            }
            base.AccessMask = GenericAce.ReadInt(binaryForm, offset + 4);
            this.ObjectAceFlags = (ObjectAceFlags)GenericAce.ReadInt(binaryForm, offset + 8);
            if (this.ObjectAceTypePresent)
            {
                num2 += 16;
            }
            if (this.InheritedObjectAceTypePresent)
            {
                num2 += 16;
            }
            if (num < num2)
            {
                throw new ArgumentException("Invalid ACE", "binaryForm");
            }
            int num3 = 12;
            if (this.ObjectAceTypePresent)
            {
                this.ObjectAceType = this.ReadGuid(binaryForm, offset + num3);
                num3 += 16;
            }
            if (this.InheritedObjectAceTypePresent)
            {
                this.InheritedObjectAceType = this.ReadGuid(binaryForm, offset + num3);
                num3 += 16;
            }
            base.SecurityIdentifier = new SecurityIdentifier(binaryForm, offset + num3);
            num3 += base.SecurityIdentifier.BinaryLength;
            int num4 = num - num3;
            if (num4 > 0)
            {
                byte[] array = new byte[num4];
                Array.Copy(binaryForm, offset + num3, array, 0, num4);
                base.SetOpaque(array);
            }
        }
References System.array, System.Array.Copy(), System.Security.AccessControl.ObjectAce.InheritedObjectAceTypePresent, int, System.Security.Principal.SecurityIdentifier.MinBinaryLength, System.Security.AccessControl.ObjectAce.ObjectAceFlags, System.Security.AccessControl.ObjectAce.ObjectAceTypePresent, System.offset, System.Security.AccessControl.ObjectAce.ReadGuid(), System.Security.AccessControl.GenericAce.ReadInt(), System.Security.AccessControl.GenericAce.ReadUShort(), and System.Security.AccessControl.KnownAce.SecurityIdentifier.