Terraria Decompiled: System.Diagnostics.Contracts.Contract.AssertMustUseRewriter
AssertMustUseRewriter()
static void System.Diagnostics.Contracts.Contract.AssertMustUseRewriter (ContractFailureKind kind, string contractKind) inline static private
Definition at line 275 of file Contract.cs.
        {
            if (Contract._assertingMustUseRewriter)
            {
                global::System.Diagnostics.Assert.Fail("Asserting that we must use the rewriter went reentrant.", "Didn't rewrite this mscorlib?");
            }
            Contract._assertingMustUseRewriter = true;
            Assembly assembly = typeof(Contract).Assembly;
            StackTrace stackTrace = new StackTrace();
            Assembly assembly2 = null;
            for (int i = 0; i < stackTrace.FrameCount; i++)
            {
                Assembly assembly3 = stackTrace.GetFrame(i).GetMethod().DeclaringType.Assembly;
                if (assembly3 != assembly)
                {
                    assembly2 = assembly3;
                    break;
                }
            }
            if (assembly2 == null)
            {
                assembly2 = assembly;
            }
            string name = assembly2.GetName().Name;
            ContractHelper.TriggerFailure(kind, Environment.GetResourceString("An assembly (probably \"{1}\") must be rewritten using the code contracts binary rewriter (CCRewrite) because it is calling Contract.{0} and the CONTRACTS_FULL symbol is defined.  Remove any explicit definitions of the CONTRACTS_FULL symbol from your project and rebuild.  CCRewrite can be downloaded from http://go.microsoft.com/fwlink/?LinkID=169180. \\r\\nAfter the rewriter is installed, it can be enabled in Visual Studio from the project's Properties page on the Code Contracts pane.  Ensure that \"Perform Runtime Contract Checking\" is enabled, which will define CONTRACTS_FULL.", new object[] { contractKind, name }), null, null, null);
            Contract._assertingMustUseRewriter = false;
        }
References System.Diagnostics.Contracts.Contract._assertingMustUseRewriter, System.Reflection.Assembly.Assembly(), System.Type.Assembly, System.Reflection.MemberInfo.DeclaringType, System.Diagnostics.StackTrace.FrameCount, System.Diagnostics.StackTrace.GetFrame(), System.Diagnostics.StackFrame.GetMethod(), System.Reflection.Assembly.GetName(), System.Environment.GetResourceString(), System.name, System.Reflection.AssemblyName.Name, and System.Runtime.CompilerServices.ContractHelper.TriggerFailure().
Referenced by System.Diagnostics.Contracts.Contract.Ensures(), System.Diagnostics.Contracts.Contract.Ensures(), System.Diagnostics.Contracts.Contract.EnsuresOnThrow< TException >(), System.Diagnostics.Contracts.Contract.EnsuresOnThrow< TException >(), System.Diagnostics.Contracts.Contract.Invariant(), System.Diagnostics.Contracts.Contract.Invariant(), System.Diagnostics.Contracts.Contract.Requires(), System.Diagnostics.Contracts.Contract.Requires(), System.Diagnostics.Contracts.Contract.Requires< TException >(), and System.Diagnostics.Contracts.Contract.Requires< TException >().