Terraria Decompiled: Terraria.GameContent.FlexibleTileWand.TryGetPlacementOption
TryGetPlacementOption()
bool Terraria.GameContent.FlexibleTileWand.TryGetPlacementOption (Player player, int randomSeed, int selectCycleOffset, out FlexibleTileWand::PlacementOption option, out Item itemToConsume) inline
Definition at line 90 of file FlexibleTileWand.cs.
        {
            option = null;
            itemToConsume = null;
            Item[] inventory = player.inventory;
            int num = 1;
            for (int i = 0; i < 58 + num; i++)
            {
                if (i < 50 || i >= 54)
                {
                    Item item = inventory[i];
                    FlexibleTileWand.OptionBucket optionBucket;
                    if (!item.IsAir && (this.CanConsumeFavorites || !item.favorited) && this._options.TryGetValue(item.type, out optionBucket))
                    {
                        this._random.SetSeed(randomSeed);
                        option = optionBucket.GetOptionWithCycling(selectCycleOffset);
                        itemToConsume = item;
                        return true;
                    }
                }
            }
            return false;
        }
References Terraria.GameContent.FlexibleTileWand.OptionBucket.GetOptionWithCycling(), Terraria.Player.inventory, and System.item.
Referenced by Terraria.Player.ModifyFlexibleWandPlacementInfo(), Terraria.Player.PlaceThing_Tiles_CheckFlexibleWand(), Terraria.Player.PlaceThing_Tiles_PlaceIt_ConsumeFlexibleWandMaterial(), Terraria.Main.TryGetAmmo(), and Terraria.Player.TryGetFlexibleWandAvailableUsageCount().