Terraria Decompiled: Terraria.UI.NetDiagnosticsUI.DrawCounter
DrawCounter()
void Terraria.UI.NetDiagnosticsUI.DrawCounter (SpriteBatch spriteBatch, ref NetDiagnosticsUI::CounterForMessage counter, string title, Vector2 position) inline private
Definition at line 109 of file NetDiagnosticsUI.cs.
        {
            if (!counter.exemptFromBadScoreTest)
            {
                if (this._highestFoundReadCount < counter.timesReceived)
                {
                    this._highestFoundReadCount = counter.timesReceived;
                }
                if (this._highestFoundReadBytes < counter.bytesReceived)
                {
                    this._highestFoundReadBytes = counter.bytesReceived;
                }
            }
            Vector2 vector = position;
            string text = title + ": ";
            float num = Utils.Remap((float)counter.bytesReceived, 0f, (float)this._highestFoundReadBytes, 0f, 1f, true);
            Color color = Main.hslToRgb(0.3f * (1f - num), 1f, 0.5f, byte.MaxValue);
            if (counter.exemptFromBadScoreTest)
            {
                color = Color.White;
            }
            string text2 = text;
            this.DrawText(spriteBatch, text2, vector, color);
            vector.X += 30f;
            text2 = "rx:" + string.Format("{0,0}", counter.timesReceived);
            this.DrawText(spriteBatch, text2, vector, color);
            vector.X += 70f;
            text2 = string.Format("{0,0}", counter.bytesReceived);
            this.DrawText(spriteBatch, text2, vector, color);
            vector.X += 70f;
            text2 = text;
            this.DrawText(spriteBatch, text2, vector, color);
            vector.X += 30f;
            text2 = "tx:" + string.Format("{0,0}", counter.timesSent);
            this.DrawText(spriteBatch, text2, vector, color);
            vector.X += 70f;
            text2 = string.Format("{0,0}", counter.bytesSent);
            this.DrawText(spriteBatch, text2, vector, color);
        }
References Terraria.UI.NetDiagnosticsUI._highestFoundReadBytes, Terraria.UI.NetDiagnosticsUI._highestFoundReadCount, Terraria.UI.NetDiagnosticsUI.DrawText(), Terraria.Main.hslToRgb(), Terraria.Utils.Remap(), System.text, and Microsoft.Xna.Framework.Color.White.
Referenced by Terraria.UI.NetDiagnosticsUI.Draw().