Terraria Decompiled: Terraria.UI.NetDiagnosticsUI.CountSentMessage
CountSentMessage()
void Terraria.UI.NetDiagnosticsUI.CountSentMessage (int messageId, int messageLength) inline
Implements Terraria.UI.INetDiagnosticsUI.
Definition at line 39 of file NetDiagnosticsUI.cs.
        {
            Interlocked.Add(ref this.bytesSent, messageLength);
            this._counterByMessageId[messageId].CountSentMessage(messageLength);
        }
References Terraria.UI.NetDiagnosticsUI._counterByMessageId, System.Threading.Interlocked.Add(), Terraria.UI.NetDiagnosticsUI.bytesSent, and Terraria.UI.NetDiagnosticsUI.CountSentMessage().
Referenced by Terraria.UI.NetDiagnosticsUI.CountSentMessage().