Terraria Decompiled: Terraria.GameContent.Skies.LanternSky.Update
Update()
override void Terraria.GameContent.Skies.LanternSky.Update (GameTime gameTime) inline
Definition at line 54 of file LanternSky.cs.
        {
            if (FocusHelper.PauseSkies)
            {
                return;
            }
            this._opacity = Utils.Clamp<float>(this._opacity + (float)LanternNight.LanternsUp.ToDirectionInt() * 0.01f, 0f, 1f);
            for (int i = 0; i < this._lanterns.Length; i++)
            {
                if (this._lanterns[i].Active)
                {
                    float num = Main.windSpeedCurrent;
                    if (num == 0f)
                    {
                        num = 0.1f;
                    }
                    float num2 = (float)Math.Sin((double)(this._lanterns[i].Position.X / 120f)) * 0.5f;
                    LanternSky.Lantern[] lanterns = this._lanterns;
                    int num3 = i;
                    lanterns[num3].Position.Y = lanterns[num3].Position.Y + num2 * 0.5f;
                    LanternSky.Lantern[] lanterns2 = this._lanterns;
                    int num4 = i;
                    lanterns2[num4].Position.Y = lanterns2[num4].Position.Y + this._lanterns[i].FloatAdjustedSpeed * 0.5f;
                    LanternSky.Lantern[] lanterns3 = this._lanterns;
                    int num5 = i;
                    lanterns3[num5].Position.X = lanterns3[num5].Position.X + (0.1f + num) * (3f - this._lanterns[i].Speed) * 0.5f * ((float)i / (float)this._lanterns.Length + 1.5f) / 2.5f;
                    this._lanterns[i].Rotation = num2 * (float)((num < 0f) ? (-1) : 1) * 0.5f;
                    this._lanterns[i].TimeUntilFloat = Math.Max(0, this._lanterns[i].TimeUntilFloat - 1);
                    if (this._lanterns[i].Position.Y < 300f)
                    {
                        if (!this._leaving)
{
                            this.ResetLantern(i);
                            this._lanterns[i].Position = new Vector2((float)(this._random.Next(0, Main.maxTilesX) * 16), (float)Main.worldSurface * 16f + 1600f);
                        }
                        else
{
                            this._lanterns[i].Active = false;
                            this._lanternsDrawing--;
                        }
                    }
                }
            }
            this._active = true;
        }
References Terraria.GameContent.Skies.LanternSky._lanterns, Terraria.GameContent.Skies.LanternSky._lanternsDrawing, Terraria.GameContent.Skies.LanternSky._leaving, Terraria.GameContent.Skies.LanternSky._random, Terraria.Graphics.Effects.Active, Terraria.Utils.Clamp(), Terraria.GameContent.Events.LanternNight.LanternsUp, System.Math.Max(), Terraria.Main.maxTilesX, Terraria.Utilities.UnifiedRandom.Next(), Terraria.FocusHelper.PauseSkies, Microsoft.Xna.Framework.Graphics.Position, Terraria.GameContent.Skies.LanternSky.ResetLantern(), System.Math.Sin(), Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Main.windSpeedCurrent, and Terraria.Main.worldSurface.