Terraria Decompiled: ReLogic.Utilities.SlotId.ToFloat
ToFloat()
float ReLogic.Utilities.SlotId.ToFloat () inline
Definition at line 92 of file SlotId.cs.
        {
            return ReinterpretCast.UIntAsFloat(this.Value);
        }
References ReLogic.Utilities.ReinterpretCast.UIntAsFloat(), and ReLogic.Utilities.SlotId.Value.
Referenced by Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.Projectile.AI_001(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_108_DivingFlyer(), Terraria.NPC.AI_110_Betsy(), Terraria.Projectile.AI_131_FlameBurstShot(), Terraria.Projectile.AI_143_MonkStaffT2Ghast(), Terraria.Projectile.AI_145_BookStaffStorm(), Terraria.Projectile.AI_177_IceWhipSlicer(), Terraria.Projectile.AI_187_ShadowHand(), Terraria.Projectile.AI_195_JimsDrone(), and Terraria.Projectile.AI_205_RemoteControlCar().