Terraria Decompiled: Terraria.Graphics.WorldSceneLayerTarget.UpdateContent
UpdateContent()
void Terraria.Graphics.WorldSceneLayerTarget.UpdateContent (Action render) inline
Definition at line 64 of file WorldSceneLayerTarget.cs.
        {
            Vector2 screenPosition = Main.screenPosition;
            Point screenSize = Main.ScreenSize;
            Vector2 zoom = Main.GameViewMatrix.Zoom;
            Vector2 center = Main.Camera.Center;
            Main.screenWidth = this._target.Width - Main.offScreenRange * 2;
            Main.screenHeight = this._target.Height - Main.offScreenRange * 2;
            Main.screenPosition = Utils.Round(center - Main.ScreenSize.ToVector2() / 2f);
            Main.GameViewMatrix.Zoom = Vector2.One;
            GraphicsDevice graphicsDevice = Main.instance.GraphicsDevice;
            RenderTargetBinding[] renderTargets = graphicsDevice.GetRenderTargets();
            graphicsDevice.SetRenderTarget(this._target);
            graphicsDevice.Clear(Color.Transparent);
            this._position = Main.screenPosition - new Vector2((float)Main.offScreenRange, (float)Main.offScreenRange);
            render();
            graphicsDevice.SetRenderTargets(renderTargets);
            Main.screenPosition = screenPosition;
            Main.screenWidth = screenSize.X;
            Main.screenHeight = screenSize.Y;
            Main.GameViewMatrix.Zoom = zoom;
        }
References Terraria.Graphics.WorldSceneLayerTarget._target, Terraria.Main.Camera, Microsoft.Xna.Framework.Graphics.GraphicsDevice.Clear(), Terraria.Main.GameViewMatrix, Microsoft.Xna.Framework.Graphics.GraphicsDevice.GetRenderTargets(), Microsoft.Xna.Framework.Game.GraphicsDevice, Terraria.Main.instance, Terraria.Main.offScreenRange, Microsoft.Xna.Framework.Vector2.One, Terraria.Utils.Round(), Terraria.Main.screenPosition, Terraria.Main.ScreenSize, Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetRenderTarget(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetRenderTargets(), Microsoft.Xna.Framework.Color.Transparent, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.Main.DoDraw(), and Terraria.Main.RenderToTargets().