Terraria Decompiled: rail.IRailFriendsImpl.AsyncQueryPlayedWithFriendsTime
AsyncQueryPlayedWithFriendsTime()
virtual RailResult rail.IRailFriendsImpl.AsyncQueryPlayedWithFriendsTime (List< RailID > rail_ids, string user_data) inline virtual
Implements rail.IRailFriends.
Definition at line 185 of file IRailFriendsImpl.cs.
        {
            IntPtr intPtr = ((rail_ids == null) ? IntPtr.Zero : RAIL_API_PINVOKE.new_RailArrayRailID__SWIG_0());
            if (rail_ids != null)
            {
                RailConverter.Csharp2Cpp(rail_ids, intPtr);
            }
            RailResult railResult;
            try
            {
                railResult = (RailResult)RAIL_API_PINVOKE.IRailFriends_AsyncQueryPlayedWithFriendsTime(this.swigCPtr_, intPtr, user_data);
            }
            finally
            {
                RAIL_API_PINVOKE.delete_RailArrayRailID(intPtr);
            }
            return railResult;
        }
References rail.RailConverter.Csharp2Cpp(), rail.RAIL_API_PINVOKE.delete_RailArrayRailID(), rail.RAIL_API_PINVOKE.IRailFriends_AsyncQueryPlayedWithFriendsTime(), rail.RAIL_API_PINVOKE.new_RailArrayRailID__SWIG_0(), and System.IntPtr.Zero.