Terraria Decompiled: FullSerializer.Internal.fsDateConverter.TryDeserialize
TryDeserialize()
override fsResult FullSerializer.Internal.fsDateConverter.TryDeserialize (fsData data, ref object instance, Type storageType) inline
Definition at line 46 of file fsDateConverter.cs.
        {
            if (!data.IsString)
            {
                return fsResult.Fail("Date deserialization requires a string, not " + data.Type);
            }
            if (storageType == typeof(DateTime))
            {
                DateTime dateTime;
                if (DateTime.TryParse(data.AsString, null, 128, ref dateTime))
                {
                    instance = dateTime;
                    return fsResult.Success;
                }
                if (fsGlobalConfig.AllowInternalExceptions)
                {
                    try
                    {
                        instance = Convert.ToDateTime(data.AsString);
                        return fsResult.Success;
                    }
                    catch (Exception ex)
                    {
                        return fsResult.Fail(string.Concat(new object[] { "Unable to parse ", data.AsString, " into a DateTime; got exception ", ex }));
                    }
                }
                return fsResult.Fail("Unable to parse " + data.AsString + " into a DateTime");
            }
            else if (storageType == typeof(DateTimeOffset))
            {
                DateTimeOffset dateTimeOffset;
                if (DateTimeOffset.TryParse(data.AsString, null, 128, ref dateTimeOffset))
                {
                    instance = dateTimeOffset;
                    return fsResult.Success;
                }
                return fsResult.Fail("Unable to parse " + data.AsString + " into a DateTimeOffset");
            }
            else
            {
                if (!(storageType == typeof(TimeSpan)))
                {
                    throw new InvalidOperationException("FullSerializer Internal Error -- Unexpected deserialization type");
                }
                TimeSpan timeSpan;
                if (TimeSpan.TryParse(data.AsString, ref timeSpan))
                {
                    instance = timeSpan;
                    return fsResult.Success;
                }
                return fsResult.Fail("Unable to parse " + data.AsString + " into a TimeSpan");
            }
        }
References FullSerializer.fsGlobalConfig.AllowInternalExceptions, FullSerializer.fsData.AsString, FullSerializer.fsResult.Fail(), FullSerializer.fsData.IsString, FullSerializer.fsResult.Success, System.Convert.ToDateTime(), System.DateTimeOffset.TryParse(), System.DateTime.TryParse(), System.TimeSpan.TryParse(), and FullSerializer.fsData.Type.