Terraria Decompiled: Ionic.Zip.ZipOutput.WriteCentralDirectoryStructure
WriteCentralDirectoryStructure()
static bool Ionic.Zip.ZipOutput.WriteCentralDirectoryStructure (Stream s, ICollection< ZipEntry > entries, uint numSegments, Zip64Option zip64, string comment, ZipContainer container) inline static
Definition at line 12 of file ZipOutput.cs.
        {
            ZipSegmentedStream zipSegmentedStream = s as ZipSegmentedStream;
            if (zipSegmentedStream != null)
            {
                zipSegmentedStream.ContiguousWrite = true;
            }
            long num = 0L;
            using (MemoryStream memoryStream = new MemoryStream())
            {
                foreach (ZipEntry zipEntry in entries)
                {
                    if (zipEntry.IncludedInMostRecentSave)
                    {
                        zipEntry.WriteCentralDirectoryEntry(memoryStream);
                    }
                }
                byte[] array = memoryStream.ToArray();
                s.Write(array, 0, array.Length);
                num = (long)array.Length;
            }
            CountingStream countingStream = s as CountingStream;
            long num2 = ((countingStream != null) ? countingStream.ComputedPosition : s.Position);
            long num3 = num2 - num;
            uint num4 = ((zipSegmentedStream != null) ? zipSegmentedStream.CurrentSegment : 0U);
            long num5 = num2 - num3;
            int num6 = ZipOutput.CountEntries(entries);
            bool flag = zip64 == Zip64Option.Always || num6 >= 65535 || num5 > (long)((ulong)(-1)) || num3 > (long)((ulong)(-1));
            byte[] array3;
            if (flag)
            {
                if (zip64 == Zip64Option.Default)
                {
                    throw new ZipException("The archive requires a ZIP64 Central Directory. Consider enabling ZIP64 extensions.");
                }
                byte[] array2 = ZipOutput.GenZip64EndOfCentralDirectory(num3, num2, num6, numSegments);
                array3 = ZipOutput.GenCentralDirectoryFooter(num3, num2, zip64, num6, comment, container);
                if (num4 != 0U)
                {
                    uint num7 = zipSegmentedStream.ComputeSegment(array2.Length + array3.Length);
                    int num8 = 16;
                    Array.Copy(BitConverter.GetBytes(num7), 0, array2, num8, 4);
                    num8 += 4;
                    Array.Copy(BitConverter.GetBytes(num7), 0, array2, num8, 4);
                    num8 = 60;
                    Array.Copy(BitConverter.GetBytes(num7), 0, array2, num8, 4);
                    num8 += 4;
                    num8 += 8;
                    Array.Copy(BitConverter.GetBytes(num7), 0, array2, num8, 4);
                }
                s.Write(array2, 0, array2.Length);
            }
            else
            {
                array3 = ZipOutput.GenCentralDirectoryFooter(num3, num2, zip64, num6, comment, container);
            }
            if (num4 != 0U)
            {
                ushort num9 = (ushort)zipSegmentedStream.ComputeSegment(array3.Length);
                int num10 = 4;
                Array.Copy(BitConverter.GetBytes(num9), 0, array3, num10, 2);
                num10 += 2;
                Array.Copy(BitConverter.GetBytes(num9), 0, array3, num10, 2);
                num10 += 2;
            }
            s.Write(array3, 0, array3.Length);
            if (zipSegmentedStream != null)
            {
                zipSegmentedStream.ContiguousWrite = false;
            }
            return flag;
        }
References System.array, Ionic.Zip.CountingStream.ComputedPosition, Ionic.Zip.ZipSegmentedStream.ComputeSegment(), System.Array.Copy(), Ionic.Zip.ZipOutput.CountEntries(), Ionic.Zip.ZipSegmentedStream.CurrentSegment, Ionic.Zip.ZipOutput.GenCentralDirectoryFooter(), Ionic.Zip.ZipOutput.GenZip64EndOfCentralDirectory(), System.BitConverter.GetBytes(), Ionic.Zip.ZipEntry.IncludedInMostRecentSave, System.L, long, System.s, System.IO.MemoryStream.ToArray(), System.U, and Ionic.Zip.ZipEntry.WriteCentralDirectoryEntry().
Referenced by Ionic.Zip.ZipOutputStream.Dispose(), and Ionic.Zip.ZipFile.Save().