Terraria Decompiled: Ionic.Zip.ZipOutput.GenCentralDirectoryFooter
GenCentralDirectoryFooter()
static byte[] Ionic.Zip.ZipOutput.GenCentralDirectoryFooter (long StartOfCentralDirectory, long EndOfCentralDirectory, Zip64Option zip64, int entryCount, string comment, ZipContainer container) inline static private
Definition at line 110 of file ZipOutput.cs.
        {
            Encoding encoding = ZipOutput.GetEncoding(container, comment);
            int num = 22;
            byte[] array = null;
            short num2 = 0;
            if (comment != null && comment.Length != 0)
            {
                array = encoding.GetBytes(comment);
                num2 = (short)array.Length;
            }
            num += (int)num2;
            byte[] array2 = new byte[num];
            int num3 = 0;
            byte[] bytes = BitConverter.GetBytes(101010256U);
            Array.Copy(bytes, 0, array2, num3, 4);
            num3 += 4;
            array2[num3++] = 0;
            array2[num3++] = 0;
            array2[num3++] = 0;
            array2[num3++] = 0;
            if (entryCount >= 65535 || zip64 == Zip64Option.Always)
            {
                for (int i = 0; i < 4; i++)
                {
                    array2[num3++] = byte.MaxValue;
                }
            }
            else
            {
                array2[num3++] = (byte)(entryCount & 255);
                array2[num3++] = (byte)((entryCount & 65280) >> 8);
                array2[num3++] = (byte)(entryCount & 255);
                array2[num3++] = (byte)((entryCount & 65280) >> 8);
            }
            long num4 = EndOfCentralDirectory - StartOfCentralDirectory;
            if (num4 >= (long)((ulong)(-1)) || StartOfCentralDirectory >= (long)((ulong)(-1)))
            {
                for (int i = 0; i < 8; i++)
                {
                    array2[num3++] = byte.MaxValue;
                }
            }
            else
            {
                array2[num3++] = (byte)(num4 & 255L);
                array2[num3++] = (byte)((num4 & 65280L) >> 8);
                array2[num3++] = (byte)((num4 & 16711680L) >> 16);
                array2[num3++] = (byte)((num4 & (long)((ulong)(-16777216))) >> 24);
                array2[num3++] = (byte)(StartOfCentralDirectory & 255L);
                array2[num3++] = (byte)((StartOfCentralDirectory & 65280L) >> 8);
                array2[num3++] = (byte)((StartOfCentralDirectory & 16711680L) >> 16);
                array2[num3++] = (byte)((StartOfCentralDirectory & (long)((ulong)(-16777216))) >> 24);
            }
            if (comment == null || comment.Length == 0)
            {
                array2[num3++] = 0;
                array2[num3++] = 0;
            }
            else
            {
                if ((int)num2 + num3 + 2 > array2.Length)
                {
                    num2 = (short)(array2.Length - num3 - 2);
                }
                array2[num3++] = (byte)(num2 & 255);
                array2[num3++] = (byte)(((int)num2 & 65280) >> 8);
                if (num2 != 0)
                {
                    int i = 0;
                    while (i < (int)num2 && num3 + i < array2.Length)
                    {
                        array2[num3 + i] = array[i];
                        i++;
                    }
                    num3 += i;
                }
            }
            return array2;
        }
References System.array, System.Array.Copy(), System.BitConverter.GetBytes(), System.Text.Encoding.GetBytes(), Ionic.Zip.ZipOutput.GetEncoding(), int, System.L, and System.U.
Referenced by Ionic.Zip.ZipOutput.WriteCentralDirectoryStructure().