Terraria Decompiled: Ionic.Zip.ZipOutput.GenZip64EndOfCentralDirectory
GenZip64EndOfCentralDirectory()
static byte[] Ionic.Zip.ZipOutput.GenZip64EndOfCentralDirectory (long StartOfCentralDirectory, long EndOfCentralDirectory, int entryCount, uint numSegments) inline static private
Definition at line 192 of file ZipOutput.cs.
        {
            byte[] array = new byte[76];
            int num = 0;
            byte[] array2 = BitConverter.GetBytes(101075792U);
            Array.Copy(array2, 0, array, num, 4);
            num += 4;
            long num2 = 44L;
            Array.Copy(BitConverter.GetBytes(num2), 0, array, num, 8);
            num += 8;
            array[num++] = 45;
            array[num++] = 0;
            array[num++] = 45;
            array[num++] = 0;
            for (int i = 0; i < 8; i++)
            {
                array[num++] = 0;
            }
            long num3 = (long)entryCount;
            Array.Copy(BitConverter.GetBytes(num3), 0, array, num, 8);
            num += 8;
            Array.Copy(BitConverter.GetBytes(num3), 0, array, num, 8);
            num += 8;
            long num4 = EndOfCentralDirectory - StartOfCentralDirectory;
            Array.Copy(BitConverter.GetBytes(num4), 0, array, num, 8);
            num += 8;
            Array.Copy(BitConverter.GetBytes(StartOfCentralDirectory), 0, array, num, 8);
            num += 8;
            array2 = BitConverter.GetBytes(117853008U);
            Array.Copy(array2, 0, array, num, 4);
            num += 4;
            uint num5 = ((numSegments == 0U) ? 0U : (numSegments - 1U));
            Array.Copy(BitConverter.GetBytes(num5), 0, array, num, 4);
            num += 4;
            Array.Copy(BitConverter.GetBytes(EndOfCentralDirectory), 0, array, num, 8);
            num += 8;
            Array.Copy(BitConverter.GetBytes(numSegments), 0, array, num, 4);
            num += 4;
            return array;
        }
References System.array, System.Array.Copy(), System.BitConverter.GetBytes(), System.L, long, and System.U.
Referenced by Ionic.Zip.ZipOutput.WriteCentralDirectoryStructure().