Terraria Decompiled: System.Security.Permissions.FileIOPermission.Intersect
Intersect()
override IPermission System.Security.Permissions.FileIOPermission.Intersect (IPermission target) inline
Implements System.Security.IPermission.
Definition at line 253 of file FileIOPermission.cs.
        {
            FileIOPermission fileIOPermission = FileIOPermission.Cast(target);
            if (fileIOPermission == null)
            {
                return null;
            }
            if (this.IsUnrestricted())
            {
                return fileIOPermission.Copy();
            }
            if (fileIOPermission.IsUnrestricted())
            {
                return this.Copy();
            }
            FileIOPermission fileIOPermission2 = new FileIOPermission(PermissionState.None);
            fileIOPermission2.AllFiles = this.m_AllFilesAccess & fileIOPermission.AllFiles;
            fileIOPermission2.AllLocalFiles = this.m_AllLocalFilesAccess & fileIOPermission.AllLocalFiles;
            FileIOPermission.IntersectKeys(this.readList, fileIOPermission.readList, fileIOPermission2.readList);
            FileIOPermission.IntersectKeys(this.writeList, fileIOPermission.writeList, fileIOPermission2.writeList);
            FileIOPermission.IntersectKeys(this.appendList, fileIOPermission.appendList, fileIOPermission2.appendList);
            FileIOPermission.IntersectKeys(this.pathList, fileIOPermission.pathList, fileIOPermission2.pathList);
            if (!fileIOPermission2.IsEmpty())
            {
                return fileIOPermission2;
            }
            return null;
        }
References System.Security.Permissions.FileIOPermission.AllFiles, System.Security.Permissions.FileIOPermission.AllLocalFiles, System.Security.Permissions.FileIOPermission.appendList, System.Security.Permissions.FileIOPermission.Cast(), System.Security.Permissions.FileIOPermission.Copy(), System.Security.Permissions.FileIOPermission.FileIOPermission(), System.Security.Permissions.FileIOPermission.IntersectKeys(), System.Security.Permissions.FileIOPermission.IsEmpty(), System.Security.Permissions.FileIOPermission.IsUnrestricted(), System.Security.Permissions.FileIOPermission.pathList, System.Security.Permissions.FileIOPermission.readList, and System.Security.Permissions.FileIOPermission.writeList.