Terraria Decompiled: System.Security.Permissions.FileIOPermission.Copy
Copy()
override IPermission System.Security.Permissions.FileIOPermission.Copy () inline
Implements System.Security.IPermission.
Definition at line 165 of file FileIOPermission.cs.
        {
            if (this.m_Unrestricted)
            {
                return new FileIOPermission(PermissionState.Unrestricted);
            }
            return new FileIOPermission(PermissionState.None)
            {
                readList = (ArrayList)this.readList.Clone(),
                writeList = (ArrayList)this.writeList.Clone(),
                appendList = (ArrayList)this.appendList.Clone(),
                pathList = (ArrayList)this.pathList.Clone(),
                m_AllFilesAccess = this.m_AllFilesAccess,
                m_AllLocalFilesAccess = this.m_AllLocalFilesAccess
            };
        }
References System.Security.Permissions.FileIOPermission.appendList, System.Collections.ArrayList.Clone(), System.Security.Permissions.FileIOPermission.FileIOPermission(), System.Security.Permissions.FileIOPermission.m_AllFilesAccess, System.Security.Permissions.FileIOPermission.m_AllLocalFilesAccess, System.Security.Permissions.FileIOPermission.m_Unrestricted, System.Security.Permissions.FileIOPermission.pathList, System.Security.Permissions.FileIOPermission.readList, and System.Security.Permissions.FileIOPermission.writeList.
Referenced by System.Security.Permissions.FileIOPermission.Intersect(), and System.Security.Permissions.FileIOPermission.Union().