Terraria Decompiled: System.Security.Permissions.FileIOPermission.IsSubsetOf
IsSubsetOf()
override bool System.Security.Permissions.FileIOPermission.IsSubsetOf (IPermission target) inline
Implements System.Security.IPermission.
Definition at line 283 of file FileIOPermission.cs.
        {
            FileIOPermission fileIOPermission = FileIOPermission.Cast(target);
            if (fileIOPermission == null)
            {
                return false;
            }
            if (fileIOPermission.IsEmpty())
            {
                return this.IsEmpty();
            }
            if (this.IsUnrestricted())
            {
                return fileIOPermission.IsUnrestricted();
            }
            return fileIOPermission.IsUnrestricted() || ((this.m_AllFilesAccess & fileIOPermission.AllFiles) == this.m_AllFilesAccess && (this.m_AllLocalFilesAccess & fileIOPermission.AllLocalFiles) == this.m_AllLocalFilesAccess && FileIOPermission.KeyIsSubsetOf(this.appendList, fileIOPermission.appendList) && FileIOPermission.KeyIsSubsetOf(this.readList, fileIOPermission.readList) && FileIOPermission.KeyIsSubsetOf(this.writeList, fileIOPermission.writeList) && FileIOPermission.KeyIsSubsetOf(this.pathList, fileIOPermission.pathList));
        }
References System.Security.Permissions.FileIOPermission.AllFiles, System.Security.Permissions.FileIOPermission.AllLocalFiles, System.Security.Permissions.FileIOPermission.appendList, System.Security.Permissions.FileIOPermission.Cast(), System.Security.Permissions.FileIOPermission.IsEmpty(), System.Security.Permissions.FileIOPermission.IsUnrestricted(), System.Security.Permissions.FileIOPermission.KeyIsSubsetOf(), System.Security.Permissions.FileIOPermission.m_AllFilesAccess, System.Security.Permissions.FileIOPermission.m_AllLocalFilesAccess, System.Security.Permissions.FileIOPermission.pathList, System.Security.Permissions.FileIOPermission.readList, and System.Security.Permissions.FileIOPermission.writeList.