Terraria Decompiled: System.Security.Permissions.FileIOPermission.KeyIsSubsetOf
KeyIsSubsetOf()
static bool System.Security.Permissions.FileIOPermission.KeyIsSubsetOf (IList local, IList target) inline static package
Definition at line 518 of file FileIOPermission.cs.
        {
            bool flag = false;
            foreach (object obj in local)
            {
                string text = (string)obj;
                using (IEnumerator enumerator2 = target.GetEnumerator())
                {
                    while (enumerator2.MoveNext())
                    {
                        if (Path.IsPathSubsetOf((string)enumerator2.Current, text))
{
                            flag = true;
                            break;
                        }
                    }
                }
                if (!flag)
                {
                    return false;
                }
            }
            return true;
        }
References System.Collections.IEnumerator.Current, System.IO.Path.IsPathSubsetOf(), System.Collections.IEnumerator.MoveNext(), System.obj, and System.text.
Referenced by System.Security.Permissions.FileIOPermission.IsSubsetOf().