Terraria Decompiled: System.Security.AccessControl.CommonSecurityDescriptor.Init
Init() [2/2]
void System.Security.AccessControl.CommonSecurityDescriptor.Init (bool isContainer, bool isDS, RawSecurityDescriptor rawSecurityDescriptor) inline private
Definition at line 34 of file CommonSecurityDescriptor.cs.
        {
            if (rawSecurityDescriptor == null)
            {
                throw new ArgumentNullException("rawSecurityDescriptor");
            }
            SystemAcl systemAcl = null;
            if (rawSecurityDescriptor.SystemAcl != null)
            {
                systemAcl = new SystemAcl(isContainer, isDS, rawSecurityDescriptor.SystemAcl);
            }
            DiscretionaryAcl discretionaryAcl = null;
            if (rawSecurityDescriptor.DiscretionaryAcl != null)
            {
                discretionaryAcl = new DiscretionaryAcl(isContainer, isDS, rawSecurityDescriptor.DiscretionaryAcl);
            }
            this.Init(isContainer, isDS, rawSecurityDescriptor.ControlFlags, rawSecurityDescriptor.Owner, rawSecurityDescriptor.Group, systemAcl, discretionaryAcl);
        }
References System.Security.AccessControl.RawSecurityDescriptor.ControlFlags, System.Security.AccessControl.CommonSecurityDescriptor.DiscretionaryAcl, System.Security.AccessControl.RawSecurityDescriptor.DiscretionaryAcl, System.Security.AccessControl.RawSecurityDescriptor.Group, System.Security.AccessControl.CommonSecurityDescriptor.Init(), System.Security.AccessControl.RawSecurityDescriptor.Owner, System.Security.AccessControl.CommonSecurityDescriptor.SystemAcl, and System.Security.AccessControl.RawSecurityDescriptor.SystemAcl.
Referenced by System.Security.AccessControl.CommonSecurityDescriptor.CommonSecurityDescriptor(), System.Security.AccessControl.CommonSecurityDescriptor.CommonSecurityDescriptor(), System.Security.AccessControl.CommonSecurityDescriptor.CommonSecurityDescriptor(), System.Security.AccessControl.CommonSecurityDescriptor.CommonSecurityDescriptor(), and System.Security.AccessControl.CommonSecurityDescriptor.Init().