Terraria Decompiled: System.Security.Permissions.FileIOPermission.Union
Union()
override IPermission System.Security.Permissions.FileIOPermission.Union (IPermission other) inline virtual
Reimplemented from System.Security.CodeAccessPermission.
Definition at line 369 of file FileIOPermission.cs.
        {
            FileIOPermission fileIOPermission = FileIOPermission.Cast(other);
            if (fileIOPermission == null)
            {
                return this.Copy();
            }
            if (this.IsUnrestricted() || fileIOPermission.IsUnrestricted())
            {
                return new FileIOPermission(PermissionState.Unrestricted);
            }
            if (this.IsEmpty() && fileIOPermission.IsEmpty())
            {
                return null;
            }
            FileIOPermission fileIOPermission2 = (FileIOPermission)this.Copy();
            fileIOPermission2.AllFiles |= fileIOPermission.AllFiles;
            fileIOPermission2.AllLocalFiles |= fileIOPermission.AllLocalFiles;
            string[] array = fileIOPermission.GetPathList(FileIOPermissionAccess.Read);
            if (array != null)
            {
                FileIOPermission.UnionKeys(fileIOPermission2.readList, array);
            }
            array = fileIOPermission.GetPathList(FileIOPermissionAccess.Write);
            if (array != null)
            {
                FileIOPermission.UnionKeys(fileIOPermission2.writeList, array);
            }
            array = fileIOPermission.GetPathList(FileIOPermissionAccess.Append);
            if (array != null)
            {
                FileIOPermission.UnionKeys(fileIOPermission2.appendList, array);
            }
            array = fileIOPermission.GetPathList(FileIOPermissionAccess.PathDiscovery);
            if (array != null)
            {
                FileIOPermission.UnionKeys(fileIOPermission2.pathList, array);
            }
            return fileIOPermission2;
        }
References System.Security.Permissions.FileIOPermission.AllFiles, System.Security.Permissions.FileIOPermission.AllLocalFiles, System.Security.Permissions.FileIOPermission.appendList, System.array, System.Security.Permissions.FileIOPermission.Cast(), System.Security.Permissions.FileIOPermission.Copy(), System.Security.Permissions.FileIOPermission.FileIOPermission(), System.Security.Permissions.FileIOPermission.GetPathList(), System.Security.Permissions.FileIOPermission.IsEmpty(), System.Security.Permissions.FileIOPermission.IsUnrestricted(), System.Security.Permissions.FileIOPermission.pathList, System.Security.Permissions.FileIOPermission.readList, System.Security.Permissions.FileIOPermission.UnionKeys(), and System.Security.Permissions.FileIOPermission.writeList.