Terraria Decompiled: System.Security.Permissions.FileIOPermission.SetPathList
SetPathList() [1/2]
void System.Security.Permissions.FileIOPermission.SetPathList (FileIOPermissionAccess access, string path) inline
Definition at line 308 of file FileIOPermission.cs.
        {
            if ((FileIOPermissionAccess.AllAccess & access) != access)
            {
                FileIOPermission.ThrowInvalidFlag(access, true);
            }
            FileIOPermission.ThrowIfInvalidPath(path);
            this.Clear(access);
            this.AddPathInternal(access, path);
        }
References System.Security.Permissions.FileIOPermission.AddPathInternal(), System.Clear, System.Security.Permissions.FileIOPermission.ThrowIfInvalidPath(), and System.Security.Permissions.FileIOPermission.ThrowInvalidFlag().