Terraria Decompiled: Ionic.Zip.ZipInputStream.Read
Read()
override int Ionic.Zip.ZipInputStream.Read (byte[] buffer, int offset, int count) inline
Definition at line 115 of file ZipInputStream.cs.
        {
            if (this._closed)
            {
                this._exceptionPending = true;
                throw new InvalidOperationException("The stream has been closed.");
            }
            if (this._needSetup)
            {
                this.SetupStream();
            }
            if (this._LeftToRead == 0L)
            {
                return 0;
            }
            int num = ((this._LeftToRead > (long)count) ? count : ((int)this._LeftToRead));
            int num2 = this._crcStream.Read(buffer, offset, num);
            this._LeftToRead -= (long)num2;
            if (this._LeftToRead == 0L)
            {
                int crc = this._crcStream.Crc;
                this._currentEntry.VerifyCrcAfterExtract(crc);
                this._inputStream.Seek(this._endOfEntry, 0);
                SharedUtilities.Workaround_Ladybug318918(this._inputStream);
            }
            return num2;
        }
References Ionic.Zip.ZipInputStream._closed, Ionic.Zip.ZipInputStream._crcStream, Ionic.Zip.ZipInputStream._currentEntry, Ionic.Zip.ZipInputStream._endOfEntry, Ionic.Zip.ZipInputStream._inputStream, Ionic.Zip.ZipInputStream._LeftToRead, Ionic.Zip.ZipInputStream._needSetup, System.count, Ionic.Crc.CrcCalculatorStream.Crc, int, System.L, long, System.offset, Ionic.Crc.CrcCalculatorStream.Read(), System.IO.Stream.Seek(), Ionic.Zip.ZipInputStream.SetupStream(), Ionic.Zip.ZipEntry.VerifyCrcAfterExtract(), and Ionic.Zip.SharedUtilities.Workaround_Ladybug318918().