Terraria Decompiled: Terraria.UI.CalculatedStyle.ToRectangle
ToRectangle()
Rectangle Terraria.UI.CalculatedStyle.ToRectangle () inline
Definition at line 19 of file CalculatedStyle.cs.
        {
            return new Rectangle((int)this.X, (int)this.Y, (int)this.Width, (int)this.Height);
        }
References Terraria.UI.CalculatedStyle.Height, Terraria.UI.CalculatedStyle.Width, Terraria.UI.CalculatedStyle.X, and Terraria.UI.CalculatedStyle.Y.
Referenced by Terraria.GameContent.UI.States.UICreativePowersMenu.Draw(), Terraria.GameContent.UI.Elements.UIBestiaryEntryIcon.DrawSelf(), Terraria.GameContent.UI.Elements.UIImage.DrawSelf(), Terraria.GameContent.UI.Elements.UIImageWithBorder.DrawSelf(), Terraria.GameContent.UI.Elements.UIScrollbar.DrawSelf(), Terraria.GameContent.UI.Elements.UIVerticalSeparator.DrawSelf(), Terraria.GameContent.UI.States.UIBestiaryTest.GetEntriesToShow(), Terraria.UI.UIElement.GetViewCullingArea(), Terraria.GameContent.UI.States.UIAchievementsMenu.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIEmotesMenu.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIManageControls.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIEmotesMenu.SetupGamepadPoints2(), Terraria.GameContent.UI.Elements.UIBestiaryEntryIcon.Update(), and Terraria.GameContent.UI.States.UIWorldCreation.UpdateSpecialSeedRing().