Terraria Decompiled: rail.rail_api.RailFactory
RailFactory()
static IRailFactory rail.rail_api.RailFactory () inline static
Definition at line 67 of file rail_api.cs.
        {
            IntPtr intPtr = RAIL_API_PINVOKE.RailFactory();
            if (!(intPtr == IntPtr.Zero))
            {
                return new IRailFactoryImpl(intPtr);
            }
            return null;
        }
References rail.RAIL_API_PINVOKE.RailFactory(), and System.IntPtr.Zero.
Referenced by Terraria.Social.WeGame.NetServerSocialModule.AcceptAnUserSession(), Terraria.Social.WeGame.NetClientSocialModule.AsyncGetFriendsInfo(), Terraria.Social.WeGame.NetClientSocialModule.AsyncGetServerIDByOwener(), Terraria.Social.WeGame.NetClientSocialModule.AsyncSetInviteCommandLine(), Terraria.Social.WeGame.NetClientSocialModule.AsyncSetMyMetaData(), Terraria.Social.WeGame.NetClientSocialModule.AsyncSetPlayWith(), Terraria.Social.WeGame.NetClientSocialModule.CleanMyMetaData(), Terraria.Social.WeGame.NetClientSocialModule.Close(), Terraria.Social.WeGame.NetServerSocialModule.CloseNetWorkSession(), Terraria.Social.WeGame.Lobby.Create(), Terraria.Social.WeGame.CloudSocialModule.Delete(), Terraria.Social.WeGame.AchievementsSocialModule.GetEncryptionKey(), Terraria.Social.WeGame.CloudSocialModule.GetFiles(), Terraria.Social.WeGame.CloudSocialModule.GetFileSize(), Terraria.Social.WeGame.NetSocialModule.GetLocalPeer(), Terraria.Social.WeGame.AchievementsSocialModule.GetMyPlayerAchievement(), Terraria.Social.WeGame.AchievementsSocialModule.GetMyPlayerStats(), Terraria.Social.WeGame.NetClientSocialModule.GetRailFriendList(), Terraria.Social.WeGame.NetServerSocialModule.GetRailFriendList(), Terraria.Social.WeGame.Lobby.GetRailServerHelper(), Terraria.Social.WeGame.NetSocialModule.GetSessionState(), Terraria.Social.WeGame.FriendsSocialModule.GetUsername(), Terraria.Social.WeGame.CloudSocialModule.HasFile(), Terraria.Social.WeGame.WeGameP2PReader.IsPacketAvailable(), Terraria.Social.WeGame.NetClientSocialModule.JoinServer(), Terraria.Social.WeGame.NetClientSocialModule.LaunchLocalServer(), Terraria.Social.WeGame.NetServerSocialModule.OnAuthSuccess(), Terraria.Social.WeGame.NetClientSocialModule.OnRailCreateSessionRequest(), Terraria.Social.WeGame.Lobby.OpenInviteOverlay(), Terraria.Social.WeGame.FriendsSocialModule.OpenJoinInterface(), Terraria.Social.WeGame.CloudSocialModule.Read(), Terraria.Social.WeGame.WeGameP2PReader.ReadTick(), Terraria.Social.WeGame.WeGameP2PWriter.SendAll(), Terraria.Social.WeGame.NetServerSocialModule.TerminateRemotePlayerSession(), and Terraria.Social.WeGame.CloudSocialModule.Write().