Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.BinaryObjectWithMapTyped.Write
Write()
void System.Runtime.Serialization.Formatters.Binary.BinaryObjectWithMapTyped.Write (__BinaryWriter sout) inline
Implements System.Runtime.Serialization.Formatters.Binary.IStreamable.
Definition at line 41 of file BinaryObjectWithMapTyped.cs.
        {
            sout.WriteByte((byte)this.binaryHeaderEnum);
            sout.WriteInt32(this.objectId);
            sout.WriteString(this.name);
            sout.WriteInt32(this.numMembers);
            for (int i = 0; i < this.numMembers; i++)
            {
                sout.WriteString(this.memberNames[i]);
            }
            for (int j = 0; j < this.numMembers; j++)
            {
                sout.WriteByte((byte)this.binaryTypeEnumA[j]);
            }
            for (int k = 0; k < this.numMembers; k++)
            {
                BinaryConverter.WriteTypeInfo(this.binaryTypeEnumA[k], this.typeInformationA[k], this.memberAssemIds[k], sout);
            }
            if (this.assemId > 0)
            {
                sout.WriteInt32(this.assemId);
            }
        }
References System.Runtime.Serialization.Formatters.Binary.BinaryObjectWithMapTyped.assemId, System.Runtime.Serialization.Formatters.Binary.BinaryObjectWithMapTyped.binaryHeaderEnum, System.Runtime.Serialization.Formatters.Binary.BinaryObjectWithMapTyped.binaryTypeEnumA, System.Runtime.Serialization.Formatters.Binary.BinaryObjectWithMapTyped.memberAssemIds, System.Runtime.Serialization.Formatters.Binary.BinaryObjectWithMapTyped.memberNames, System.Runtime.Serialization.Formatters.Binary.BinaryObjectWithMapTyped.name, System.Runtime.Serialization.Formatters.Binary.BinaryObjectWithMapTyped.numMembers, System.Runtime.Serialization.Formatters.Binary.BinaryObjectWithMapTyped.objectId, System.Runtime.Serialization.Formatters.Binary.BinaryObjectWithMapTyped.typeInformationA, System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteByte(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteInt32(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteString(), and System.Runtime.Serialization.Formatters.Binary.BinaryConverter.WriteTypeInfo().
Referenced by System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteObject().