Terraria Decompiled: Steamworks.SteamUGC.GetQueryUGCMetadata
GetQueryUGCMetadata()
static bool Steamworks.SteamUGC.GetQueryUGCMetadata (UGCQueryHandle_t handle, uint index, out string pchMetadata, uint cchMetadatasize) inline static
Definition at line 98 of file SteamUGC.cs.
        {
            InteropHelp.TestIfAvailableClient();
            IntPtr intPtr = Marshal.AllocHGlobal((int)cchMetadatasize);
            bool flag = NativeMethods.ISteamUGC_GetQueryUGCMetadata(CSteamAPIContext.GetSteamUGC(), handle, index, intPtr, cchMetadatasize);
            pchMetadata = (flag ? InteropHelp.PtrToStringUTF8(intPtr) : null);
            Marshal.FreeHGlobal(intPtr);
            return flag;
        }
References System.Runtime.InteropServices.Marshal.AllocHGlobal(), System.Runtime.InteropServices.Marshal.FreeHGlobal(), Steamworks.CSteamAPIContext.GetSteamUGC(), System.index, Steamworks.NativeMethods.ISteamUGC_GetQueryUGCMetadata(), Steamworks.InteropHelp.PtrToStringUTF8(), and Steamworks.InteropHelp.TestIfAvailableClient().