Terraria Decompiled: System.Security.Principal.WindowsIdentity.OnDeserialization
OnDeserialization()
void IDeserializationCallback. System.Security.Principal.WindowsIdentity.OnDeserialization (object sender) inline private
Implements System.Runtime.Serialization.IDeserializationCallback.
Definition at line 293 of file WindowsIdentity.cs.
        {
            this._token = (IntPtr)this._info.GetValue("m_userToken", typeof(IntPtr));
            this._name = this._info.GetString("m_name");
            if (this._name != null)
            {
                if (WindowsIdentity.GetTokenName(this._token) != this._name)
                {
                    throw new SerializationException("Token-Name mismatch.");
                }
            }
            else
            {
                this._name = WindowsIdentity.GetTokenName(this._token);
                if (this._name == null)
                {
                    throw new SerializationException("Token doesn't match a user.");
                }
            }
            this._type = this._info.GetString("m_type");
            this._account = (WindowsAccountType)this._info.GetValue("m_acctType", typeof(WindowsAccountType));
            this._authenticated = this._info.GetBoolean("m_isAuthenticated");
        }
References System.Security.Principal.WindowsIdentity._info, System.Security.Principal.WindowsIdentity._name, System.Security.Principal.WindowsIdentity._token, System.Runtime.Serialization.SerializationInfo.GetBoolean(), System.Runtime.Serialization.SerializationInfo.GetString(), System.Security.Principal.WindowsIdentity.GetTokenName(), and System.Runtime.Serialization.SerializationInfo.GetValue().