Terraria Decompiled: System.Security.Principal.WindowsIdentity.SetToken
SetToken()
void System.Security.Principal.WindowsIdentity.SetToken (IntPtr token) inline private
Definition at line 340 of file WindowsIdentity.cs.
        {
            if (Environment.IsUnix)
            {
                this._token = token;
                if (this._type == null)
                {
                    this._type = "POSIX";
                }
                if (this._token == IntPtr.Zero)
                {
                    this._account = WindowsAccountType.System;
                    return;
                }
            }
            else
            {
                if (token == WindowsIdentity.invalidWindows && this._account != WindowsAccountType.Anonymous)
                {
                    throw new ArgumentException("Invalid token");
                }
                this._token = token;
                if (this._type == null)
                {
                    this._type = "NTLM";
                }
            }
        }
References System.Security.Principal.WindowsIdentity._token, System.Security.Principal.WindowsIdentity._type, System.Security.Principal.WindowsIdentity.invalidWindows, and System.IntPtr.Zero.
Referenced by System.Security.Principal.WindowsIdentity.WindowsIdentity(), System.Security.Principal.WindowsIdentity.WindowsIdentity(), and System.Security.Principal.WindowsIdentity.WindowsIdentity().