Terraria Decompiled: Terraria.Audio.ActiveSound.DetermineIntendedVolume
DetermineIntendedVolume()
float Terraria.Audio.ActiveSound.DetermineIntendedVolume () inline private
Definition at line 171 of file ActiveSound.cs.
        {
            float num = 1f;
            if (!this.IsGlobal)
            {
                Vector2 vector = this.Position - Main.Camera.Center;
                this.Sound.Pan = MathHelper.Clamp(vector.X / ((float)Main.MaxWorldViewSize.X * 0.5f), -1f, 1f);
                num = MathHelper.Clamp(1f - vector.Length() / LegacySoundPlayer.SoundAttenuationDistance, 0f, 1f);
            }
            num *= this.Style.Volume * this.Volume;
            switch (this.Style.Type)
            {
            case SoundType.Sound:
                num *= Main.soundVolume;
                break;
            case SoundType.Ambient:
                num *= Main.ambientVolume;
                break;
            case SoundType.Music:
                num *= Main.musicVolume;
                break;
            }
            return MathHelper.Clamp(num, 0f, 1f);
        }
References Terraria.Main.ambientVolume, Terraria.Main.Camera, Microsoft.Xna.Framework.MathHelper.Clamp(), Terraria.Audio.ActiveSound.IsGlobal, Microsoft.Xna.Framework.Vector2.Length(), Terraria.Main.MaxWorldViewSize, Terraria.Main.musicVolume, Terraria.Audio.LegacySoundPlayer.SoundAttenuationDistance, Terraria.Main.soundVolume, Terraria.Audio.ActiveSound.Style, Terraria.Audio.SoundStyle.Type, Terraria.Audio.ActiveSound.Volume, and Microsoft.Xna.Framework.Vector2.X.
Referenced by Terraria.Audio.ActiveSound.Play(), and Terraria.Audio.ActiveSound.Update().