Terraria Decompiled: System.Reflection.RuntimeParameterInfo.New
New() [1/4]
static ParameterInfo System.Reflection.RuntimeParameterInfo.New (ParameterBuilder pb, Type type, MemberInfo member, int position) inline static package
Definition at line 78 of file RuntimeParameterInfo.cs.
        {
            return new RuntimeParameterInfo(pb, type, member, position);
        }
References System.Reflection.RuntimeParameterInfo.RuntimeParameterInfo().
Referenced by System.Reflection.RuntimePropertyInfo.GetIndexParameters(), System.Reflection.Emit.ConstructorBuilder.GetParametersInternal(), System.Reflection.Emit.ConstructorOnTypeBuilderInst.GetParametersInternal(), System.Reflection.Emit.DynamicMethod.GetParametersInternal(), System.Reflection.Emit.MethodBuilder.GetParametersInternal(), and System.Reflection.MonoMethodInfo.GetReturnParameterInfo().