Terraria Decompiled: System.Runtime.Serialization.ObjectHolder.UpdateData
UpdateData()
void System.Runtime.Serialization.ObjectHolder.UpdateData (object obj, SerializationInfo info, ISerializationSurrogate surrogate, long idOfContainer, FieldInfo field, int[] arrayIndex, ObjectManager manager) inline package
Definition at line 128 of file ObjectHolder.cs.
        {
            this.SetObjectValue(obj, manager);
            this.m_serInfo = info;
            this.m_surrogate = surrogate;
            if (idOfContainer != 0L && ((field != null && field.FieldType.IsValueType) || arrayIndex != null))
            {
                if (idOfContainer == this.m_id)
                {
                    throw new SerializationException(Environment.GetResourceString("The ID of the containing object cannot be the same as the object ID."));
                }
                this.m_valueFixup = new ValueTypeFixupInfo(idOfContainer, field, arrayIndex);
            }
            this.SetFlags();
            if (this.RequiresValueTypeFixup)
            {
                this.UpdateDescendentDependencyChain(this.m_missingElementsRemaining, manager);
            }
        }
References System.arrayIndex, System.Reflection.FieldInfo.FieldType, System.Environment.GetResourceString(), System.info, System.Type.IsValueType, System.L, System.Runtime.Serialization.ObjectHolder.m_id, System.Runtime.Serialization.ObjectHolder.m_missingElementsRemaining, System.Runtime.Serialization.ObjectHolder.RequiresValueTypeFixup, System.Runtime.Serialization.ObjectHolder.SetFlags(), System.Runtime.Serialization.ObjectHolder.SetObjectValue(), and System.Runtime.Serialization.ObjectHolder.UpdateDescendentDependencyChain().
Referenced by System.Runtime.Serialization.ObjectManager.RegisterObject().