Terraria Decompiled: System.Runtime.Serialization.ObjectHolder.SetObjectValue
SetObjectValue()
void System.Runtime.Serialization.ObjectHolder.SetObjectValue (object obj, ObjectManager manager) inline package
Definition at line 346 of file ObjectHolder.cs.
        {
            this.m_object = obj;
            if (obj == manager.TopObject)
            {
                this.m_reachable = true;
            }
            if (obj is TypeLoadExceptionHolder)
            {
                this.m_typeLoad = (TypeLoadExceptionHolder)obj;
            }
            if (this.m_markForFixupWhenAvailable)
            {
                manager.CompleteObject(this, true);
            }
        }
References System.Runtime.Serialization.ObjectManager.CompleteObject(), System.Runtime.Serialization.ObjectHolder.m_markForFixupWhenAvailable, System.obj, and System.Runtime.Serialization.ObjectManager.TopObject.
Referenced by System.Runtime.Serialization.ObjectManager.FixupSpecialObject(), System.Runtime.Serialization.ObjectManager.ResolveObjectReference(), and System.Runtime.Serialization.ObjectHolder.UpdateData().