Terraria Decompiled: Microsoft.Xna.Framework.Audio.DynamicSoundEffectInstance.Update
Update()
void Microsoft.Xna.Framework.Audio.DynamicSoundEffectInstance.Update () inline package
Definition at line 230 of file DynamicSoundEffectInstance.cs.
        {
            if (base.State != SoundState.Playing)
            {
                return;
            }
            if (this.handle != IntPtr.Zero)
            {
                FAudio.FAudioVoiceState faudioVoiceState;
                FAudio.FAudioSourceVoice_GetState(this.handle, out faudioVoiceState, 256U);
                while ((long)this.PendingBufferCount > (long)((ulong)faudioVoiceState.BuffersQueued))
                {
                    List<IntPtr> list = this.queuedBuffers;
                    lock (list)
                    {
                        FNAPlatform.Free(this.queuedBuffers[0]);
                        this.queuedBuffers.RemoveAt(0);
                    }
                }
            }
            int num = 3 - this.PendingBufferCount;
            while (num > 0 && this.BufferNeeded != null)
            {
                this.BufferNeeded(this, null);
                num--;
            }
        }
References Microsoft.Xna.Framework.Audio.DynamicSoundEffectInstance.BufferNeeded, FAudio.FAudioVoiceState.BuffersQueued, FAudio.FAudioSourceVoice_GetState(), Microsoft.Xna.Framework.FNAPlatform.Free, Microsoft.Xna.Framework.Audio.SoundEffectInstance.handle, System.list, Microsoft.Xna.Framework.Audio.DynamicSoundEffectInstance.PendingBufferCount, Microsoft.Xna.Framework.Audio.DynamicSoundEffectInstance.queuedBuffers, System.Collections.Generic.List< T >.RemoveAt(), System.U, and System.IntPtr.Zero.
Referenced by Microsoft.Xna.Framework.Audio.DynamicSoundEffectInstance.Play(), and Microsoft.Xna.Framework.FrameworkDispatcher.Update().