Terraria Decompiled: System.Runtime.Serialization.ObjectHolder.AddFixup
AddFixup()
void System.Runtime.Serialization.ObjectHolder.AddFixup (FixupHolder fixup, ObjectManager manager) inline package
Definition at line 90 of file ObjectHolder.cs.
        {
            if (this.m_missingElements == null)
            {
                this.m_missingElements = new FixupHolderList();
            }
            this.m_missingElements.Add(fixup);
            this.m_missingElementsRemaining++;
            if (this.RequiresValueTypeFixup)
            {
                this.UpdateDescendentDependencyChain(1, manager);
            }
        }
References System.Runtime.Serialization.FixupHolderList.Add(), System.Runtime.Serialization.ObjectHolder.m_missingElements, System.Runtime.Serialization.ObjectHolder.m_missingElementsRemaining, System.Runtime.Serialization.ObjectHolder.RequiresValueTypeFixup, and System.Runtime.Serialization.ObjectHolder.UpdateDescendentDependencyChain().
Referenced by System.Runtime.Serialization.ObjectManager.RegisterFixup().