Terraria Decompiled: Microsoft.Xna.Framework.Audio.DynamicSoundEffectInstance.SubmitBuffer
SubmitBuffer() [2/2]
void Microsoft.Xna.Framework.Audio.DynamicSoundEffectInstance.SubmitBuffer (byte[] buffer, int offset, int count) inline
Definition at line 129 of file DynamicSoundEffectInstance.cs.
        {
            IntPtr intPtr = FNAPlatform.Malloc(count);
            Marshal.Copy(buffer, offset, intPtr, count);
            List<IntPtr> list = this.queuedBuffers;
            lock (list)
            {
                this.queuedBuffers.Add(intPtr);
                if (base.State != SoundState.Stopped)
                {
                    FAudio.FAudioBuffer faudioBuffer = default(FAudio.FAudioBuffer);
                    faudioBuffer.AudioBytes = (uint)count;
                    faudioBuffer.pAudioData = intPtr;
                    faudioBuffer.PlayLength = faudioBuffer.AudioBytes / (uint)this.channels / (uint)(this.format.wBitsPerSample / 8);
                    FAudio.FAudioSourceVoice_SubmitSourceBuffer(this.handle, ref faudioBuffer, IntPtr.Zero);
                }
                else
                {
                    this.queuedSizes.Add((uint)count);
                }
            }
        }
References System.Collections.Generic.List< T >.Add(), Microsoft.Xna.Framework.Audio.DynamicSoundEffectInstance.channels, System.Runtime.InteropServices.Marshal.Copy(), System.count, FAudio.FAudioSourceVoice_SubmitSourceBuffer(), Microsoft.Xna.Framework.Audio.SoundEffectInstance.handle, System.list, Microsoft.Xna.Framework.FNAPlatform.Malloc, System.offset, Microsoft.Xna.Framework.Audio.DynamicSoundEffectInstance.queuedBuffers, Microsoft.Xna.Framework.Audio.DynamicSoundEffectInstance.queuedSizes, and System.IntPtr.Zero.