Terraria Decompiled: System.IO.File.d__74.MoveNext
MoveNext()
void IAsyncStateMachine. System.IO.File.d__74.MoveNext () inline
Implements System.Runtime.CompilerServices.IAsyncStateMachine.
Definition at line 1573 of file File.cs.
            {
                int num2;
                int num = num2;
                try
                {
                    if (num > 1)
                    {
                        fs = new FileStream(path, FileMode.Create, FileAccess.Write, FileShare.Read, 4096, FileOptions.Asynchronous | FileOptions.SequentialScan);
                    }
                    try
                    {
                        ConfiguredTaskAwaitable.ConfiguredTaskAwaiter configuredTaskAwaiter;
                        ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter;
                        if (num != 0)
{
                            if (num == 1)
{
                                ConfiguredTaskAwaitable.ConfiguredTaskAwaiter configuredTaskAwaiter2;
                                configuredTaskAwaiter = configuredTaskAwaiter2;
                                configuredTaskAwaiter2 = default(ConfiguredTaskAwaitable.ConfiguredTaskAwaiter);
                                num = (num2 = -1);
                                goto IL_011A;
                            }
                            configuredValueTaskAwaiter = fs.WriteAsync(new ReadOnlyMemory<byte>(bytes), cancellationToken).ConfigureAwait(false).GetAwaiter();
                            if (!configuredValueTaskAwaiter.IsCompleted)
{
                                num = (num2 = 0);
                                ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter2 = configuredValueTaskAwaiter;
                                this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter, File.<InternalWriteAllBytesAsync>d__74>(ref configuredValueTaskAwaiter, ref this);
                                return;
                            }
                        }
                        else
{
                            ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter2;
                            configuredValueTaskAwaiter = configuredValueTaskAwaiter2;
                            configuredValueTaskAwaiter2 = default(ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter);
                            num = (num2 = -1);
                        }
                        configuredValueTaskAwaiter.GetResult();
                        configuredTaskAwaiter = fs.FlushAsync(cancellationToken).ConfigureAwait(false).GetAwaiter();
                        if (!configuredTaskAwaiter.IsCompleted)
{
                            num = (num2 = 1);
                            ConfiguredTaskAwaitable.ConfiguredTaskAwaiter configuredTaskAwaiter2 = configuredTaskAwaiter;
                            this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredTaskAwaitable.ConfiguredTaskAwaiter, File.<InternalWriteAllBytesAsync>d__74>(ref configuredTaskAwaiter, ref this);
                            return;
                        }
                        IL_011A:
                        configuredTaskAwaiter.GetResult();
                    }
                    finally
                    {
                        if (num < 0 && fs != null)
{
                            ((IDisposable)fs).Dispose();
                        }
                    }
                    fs = null;
                }
                catch (Exception ex)
                {
                    num2 = -2;
                    this.<>t__builder.SetException(ex);
                    return;
                }
                num2 = -2;
                this.<>t__builder.SetResult();
            }
References System.Runtime.CompilerServices.ConfiguredTaskAwaitable< TResult >.ConfiguredTaskAwaiter.GetResult(), System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable< TResult >.ConfiguredValueTaskAwaiter.GetResult(), System.IO.File.InternalWriteAllBytesAsync(), System.Runtime.CompilerServices.ConfiguredTaskAwaitable< TResult >.ConfiguredTaskAwaiter.IsCompleted, and System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable< TResult >.ConfiguredValueTaskAwaiter.IsCompleted.