Terraria Decompiled: UTF8Marshaler.MarshalNativeToManaged
MarshalNativeToManaged()
object UTF8Marshaler.MarshalNativeToManaged (IntPtr data) inline
Implements System.Runtime.InteropServices.ICustomMarshaler.
Definition at line 27 of file UTF8Marshaler.cs.
    {
        int num = 0;
        while (Marshal.ReadByte(data, num) != 0)
        {
            num++;
        }
        if (num == 0)
        {
            return string.Empty;
        }
        byte[] array = new byte[num];
        Marshal.Copy(data, array, 0, num);
        return Encoding.UTF8.GetString(array);
    }
References System.array, System.Runtime.InteropServices.Marshal.Copy(), System.Text.Encoding.GetString(), System.Runtime.InteropServices.Marshal.ReadByte(), and System.Text.Encoding.UTF8.