Terraria Decompiled: UTF8Marshaler.MarshalManagedToNative
MarshalManagedToNative()
IntPtr UTF8Marshaler.MarshalManagedToNative (object obj) inline
Implements System.Runtime.InteropServices.ICustomMarshaler.
Definition at line 9 of file UTF8Marshaler.cs.
    {
        if (obj == null)
        {
            return IntPtr.Zero;
        }
        if (!(obj is string))
        {
            throw new MarshalDirectiveException("Invalid obj in UTF8Marshaler.");
        }
        byte[] bytes = Encoding.UTF8.GetBytes((string)obj);
        IntPtr intPtr = Marshal.AllocHGlobal(bytes.Length + 1);
        Marshal.Copy(bytes, 0, intPtr, bytes.Length);
        Marshal.WriteByte(intPtr + bytes.Length, 0);
        return intPtr;
    }
References System.Runtime.InteropServices.Marshal.AllocHGlobal(), System.Runtime.InteropServices.Marshal.Copy(), System.Text.Encoding.GetBytes(), System.obj, System.Text.Encoding.UTF8, System.Runtime.InteropServices.Marshal.WriteByte(), and System.IntPtr.Zero.