Terraria Decompiled: Microsoft.Xna.Framework.Graphics.RenderTarget2D.RenderTarget2D
RenderTarget2D() [3/3]
Microsoft.Xna.Framework.Graphics.RenderTarget2D.RenderTarget2D (GraphicsDevice graphicsDevice, int width, int height, bool mipMap, SurfaceFormat preferredFormat, DepthFormat preferredDepthFormat, int preferredMultiSampleCount, RenderTargetUsage usage) inline
Definition at line 137 of file RenderTarget2D.cs.
            : base(graphicsDevice, width, height, mipMap, preferredFormat)
        {
            this.DepthStencilFormat = preferredDepthFormat;
            this.MultiSampleCount = FNA3D.FNA3D_GetMaxMultiSampleCount(graphicsDevice.GLDevice, base.Format, MathHelper.ClosestMSAAPower(preferredMultiSampleCount));
            this.RenderTargetUsage = usage;
            if (this.MultiSampleCount > 0)
            {
                this.glColorBuffer = FNA3D.FNA3D_GenColorRenderbuffer(graphicsDevice.GLDevice, base.Width, base.Height, base.Format, this.MultiSampleCount, this.texture);
            }
            if (this.DepthStencilFormat == DepthFormat.None)
            {
                return;
            }
            this.glDepthStencilBuffer = FNA3D.FNA3D_GenDepthStencilRenderbuffer(graphicsDevice.GLDevice, base.Width, base.Height, this.DepthStencilFormat, this.MultiSampleCount);
        }
References Microsoft.Xna.Framework.MathHelper.ClosestMSAAPower(), Microsoft.Xna.Framework.Graphics.RenderTarget2D.DepthStencilFormat, Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_GenColorRenderbuffer(), Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_GenDepthStencilRenderbuffer(), Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_GetMaxMultiSampleCount(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.GLDevice, Microsoft.Xna.Framework.Graphics.GraphicsResource.graphicsDevice, and Microsoft.Xna.Framework.Graphics.RenderTarget2D.MultiSampleCount.