Terraria Decompiled: Microsoft.Xna.Framework.Graphics.RenderTarget2D.Dispose
Dispose()
override void Microsoft.Xna.Framework.Graphics.RenderTarget2D.Dispose (bool disposing) inline protected virtual
Reimplemented from Microsoft.Xna.Framework.Graphics.GraphicsResource.
Definition at line 155 of file RenderTarget2D.cs.
        {
            if (!base.IsDisposed)
            {
                for (int i = 0; i < base.GraphicsDevice.renderTargetCount; i++)
                {
                    if (base.GraphicsDevice.renderTargetBindings[i].RenderTarget == this)
                    {
                        throw new InvalidOperationException("Disposing target that is still bound");
                    }
                }
                IntPtr intPtr = Interlocked.Exchange(ref this.glColorBuffer, IntPtr.Zero);
                if (intPtr != IntPtr.Zero)
                {
                    FNA3D.FNA3D_AddDisposeRenderbuffer(base.GraphicsDevice.GLDevice, intPtr);
                }
                intPtr = Interlocked.Exchange(ref this.glDepthStencilBuffer, IntPtr.Zero);
                if (intPtr != IntPtr.Zero)
                {
                    FNA3D.FNA3D_AddDisposeRenderbuffer(base.GraphicsDevice.GLDevice, intPtr);
                }
            }
            base.Dispose(disposing);
        }
References System.Threading.Interlocked.Exchange(), Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_AddDisposeRenderbuffer(), Microsoft.Xna.Framework.Graphics.RenderTarget2D.glColorBuffer, Microsoft.Xna.Framework.Graphics.RenderTarget2D.glDepthStencilBuffer, and System.IntPtr.Zero.
Referenced by Terraria.MapRenderer.checkMap(), Terraria.GameContent.TilePaintSystemV2.ARenderTargetHolder.Clear(), Terraria.Graphics.Capture.CaptureCamera.Dispose(), Terraria.Graphics.WorldSceneLayerTarget.Dispose(), Terraria.Graphics.Capture.CaptureCamera.FinishCapture(), Terraria.GameContent.Shaders.WaterShaderData.ReleaseRenderTargets(), and Terraria.Main.ReleaseTargets().