Terraria Decompiled: MonoGame.Utilities.AssemblyHelper.GetDefaultWindowTitle
GetDefaultWindowTitle()
static string MonoGame.Utilities.AssemblyHelper.GetDefaultWindowTitle () inline static
Definition at line 10 of file AssemblyHelper.cs.
        {
            string text = string.Empty;
            Assembly entryAssembly = Assembly.GetEntryAssembly();
            if (entryAssembly != null)
            {
                try
                {
                    AssemblyTitleAttribute assemblyTitleAttribute = (AssemblyTitleAttribute)Attribute.GetCustomAttribute(entryAssembly, typeof(AssemblyTitleAttribute));
                    if (assemblyTitleAttribute != null)
                    {
                        text = assemblyTitleAttribute.Title;
                    }
                }
                catch
                {
                }
                if (string.IsNullOrEmpty(text))
                {
                    text = entryAssembly.GetName().Name;
                }
            }
            return text;
        }
References System.Attribute.GetCustomAttribute(), System.Reflection.Assembly.GetEntryAssembly(), System.Reflection.Assembly.GetName(), System.Reflection.AssemblyName.Name, System.text, and System.Reflection.AssemblyTitleAttribute.Title.
Referenced by Microsoft.Xna.Framework.SDL2_FNAPlatform.CreateWindow(), and Microsoft.Xna.Framework.SDL3_FNAPlatform.CreateWindow().