Terraria Decompiled: System.Threading.Tasks.TaskFactory.CompleteOnInvokePromise.Invoke
Invoke()
void System.Threading.Tasks.TaskFactory< TResult >.CompleteOnInvokePromise.Invoke (Task completingTask) inline
Implements System.Threading.Tasks.ITaskCompletionAction.
Definition at line 1004 of file TaskFactory.2.cs.
            {
                if (base.TrySetResult(completingTask))
                {
                    if (DebuggerSupport.LoggingOn)
                    {
                        DebuggerSupport.TraceOperationRelation(CausalityTraceLevel.Important, this, CausalityRelation.Choice);
                        DebuggerSupport.TraceOperationCompletion(CausalityTraceLevel.Required, this, AsyncStatus.Completed);
                    }
                    DebuggerSupport.RemoveFromActiveTasks(this);
                    IList<Task> tasks = this._tasks;
                    int count = tasks.Count;
                    for (int i = 0; i < count; i++)
                    {
                        Task task = tasks[i];
                        if (task != null && !task.IsCompleted)
{
                            task.RemoveContinuation(this);
                        }
                    }
                    this._tasks = null;
                }
            }
References System.Threading.Tasks.TaskFactory< TResult >.CompleteOnInvokePromise._tasks, System.Collections.Generic.ICollection< T >.Count, System.count, System.Threading.Tasks.DebuggerSupport.LoggingOn, System.Threading.Tasks.DebuggerSupport.RemoveFromActiveTasks(), System.task, System.Threading.Tasks.DebuggerSupport.TraceOperationCompletion(), and System.Threading.Tasks.DebuggerSupport.TraceOperationRelation().
Referenced by System.Threading.Tasks.TaskFactory< TResult >.CommonCWAnyLogic().