Terraria Decompiled: Terraria.Graphics.Renderers.StormLightningParticle.Prepare
Prepare()
void Terraria.Graphics.Renderers.StormLightningParticle.Prepare (uint seed, Vector2 targetPosition, int lifeTimeTotal, Color color) inline
Definition at line 66 of file StormLightningParticle.cs.
        {
            this.Color = color;
            this._lifeTimeTotal = lifeTimeTotal;
            LightningGenerator.Bolt bolt = LightningGenerator.StormLightning.Generate(this.bolts, seed, targetPosition, true, true);
            this.StartPosition = bolt.positions[0];
            this.EndPosition = bolt.positions[bolt.positions.Length - 1];
            LCG32Random lcg32Random = new LCG32Random(seed);
            int num = (int)Math.Ceiling((double)((float)bolt.positions.Length / 10f));
            for (int i = 0; i < bolt.positions.Length; i++)
            {
                if (lcg32Random.Next(num) == 0)
                {
                    Vector2 vector = bolt.positions[i];
                    Vector2 vector2 = Vector2.UnitY;
                    if (bolt.rotations != null)
                    {
                        vector2 = -bolt.rotations[i].ToRotationVector2();
                    }
                    Dust dust = Dust.NewDustPerfect(vector, 226, null, 0, default(Color), 1f);
                    dust.HackFrame(278);
                    dust.color = color;
                    dust.customData = dust.color;
                    dust.velocity = vector2;
                    dust.velocity *= 3f + lcg32Random.NextFloat() * 6.5f;
                    dust.fadeIn = 0f;
                    dust.scale = 0.4f + lcg32Random.NextFloat() * 0.5f;
                    dust.noGravity = true;
                    dust.position -= dust.velocity * 6f;
                    Dust.CloneDust(dust).velocity *= 0.5f;
                    dust.scale -= 0.3f;
                }
            }
        }
References Terraria.Graphics.Renderers.StormLightningParticle.bolts, System.Math.Ceiling(), Terraria.Dust.CloneDust(), Terraria.Dust.color, Terraria.GameContent.LightningGenerator.StormLightning.Generate(), Terraria.Dust.HackFrame(), int, Microsoft.Xna.Framework.Vector2.Length(), Terraria.Dust.NewDustPerfect(), Terraria.Utilities.LCG32Random.Next(), Terraria.Utilities.LCG32Random.NextFloat(), Terraria.GameContent.LightningGenerator.Bolt.positions, Terraria.GameContent.LightningGenerator.Bolt.rotations, Microsoft.Xna.Framework.Vector2.UnitY, and Terraria.Dust.velocity.
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_StormLightning().