Terraria Decompiled: System.Collections.Generic.LowLevelDictionary.Add
Add()
void System.Collections.Generic.LowLevelDictionary< TKey, TValue >.Add (TKey key, TValue value) inline
Definition at line 94 of file LowLevelDictionary.cs.
        {
            if (key == null)
            {
                throw new ArgumentNullException("key");
            }
            if (this.Find(key) != null)
            {
                throw new ArgumentException(SR.Format("An item with the same key has already been added. Key: {0}", key));
            }
            this._version++;
            this.UncheckedAdd(key, value);
        }
References System.Collections.Generic.LowLevelDictionary< TKey, TValue >._version, System.Collections.Generic.LowLevelDictionary< TKey, TValue >.Find(), SR.Format(), System.key, System.Collections.Generic.LowLevelDictionary< TKey, TValue >.UncheckedAdd(), and System.value.