Terraria Decompiled: Microsoft.Xna.Framework.Graphics.SpriteEffect.OnApply
OnApply()
override void Microsoft.Xna.Framework.Graphics.SpriteEffect.OnApply () inline package virtual
Reimplemented from Microsoft.Xna.Framework.Graphics.Effect.
Definition at line 35 of file SpriteEffect.cs.
        {
            Viewport viewport = base.GraphicsDevice.Viewport;
            Matrix matrix = Matrix.CreateOrthographicOffCenter(0f, (float)viewport.Width, (float)viewport.Height, 0f, 0f, 1f);
            Matrix matrix2 = Matrix.CreateTranslation(-0.5f, -0.5f, 0f);
            this.matrixParam.SetValue(matrix2 * matrix);
        }
References Microsoft.Xna.Framework.Matrix.CreateOrthographicOffCenter(), Microsoft.Xna.Framework.Matrix.CreateTranslation(), Microsoft.Xna.Framework.Graphics.Viewport.Height, Microsoft.Xna.Framework.Graphics.SpriteEffect.matrixParam, Microsoft.Xna.Framework.Graphics.EffectParameter.SetValue(), Microsoft.Xna.Framework.Graphics.Viewport.Viewport(), and Microsoft.Xna.Framework.Graphics.Viewport.Width.