Terraria Decompiled: System.Collections.Generic.LowLevelDictionary.Find
Find()
LowLevelDictionary< TKey, TValue >.Entry System.Collections.Generic.LowLevelDictionary< TKey, TValue >.Find (TKey key) inline private
Definition at line 147 of file LowLevelDictionary.cs.
        {
            int bucket = this.GetBucket(key, 0);
            for (LowLevelDictionary<TKey, TValue>.Entry entry = this._buckets[bucket]; entry != null; entry = entry._next)
            {
                if (this._comparer.Equals(key, entry._key))
                {
                    return entry;
                }
            }
            return null;
        }
References System.Collections.Generic.LowLevelDictionary< TKey, TValue >._buckets, System.Collections.Generic.LowLevelDictionary< TKey, TValue >._comparer, System.Collections.Generic.LowLevelDictionary< TKey, TValue >.Entry._next, System.Collections.IEqualityComparer.Equals(), and System.Collections.Generic.LowLevelDictionary< TKey, TValue >.GetBucket().
Referenced by System.Collections.Generic.LowLevelDictionary< TKey, TValue >.Add(), and System.Collections.Generic.LowLevelDictionary< TKey, TValue >.TryGetValue().