Terraria Decompiled: System.Collections.Generic.LowLevelDictionary.UncheckedAdd
UncheckedAdd()
LowLevelDictionary< TKey, TValue >.Entry System.Collections.Generic.LowLevelDictionary< TKey, TValue >.UncheckedAdd (TKey key, TValue value) inline private
Definition at line 161 of file LowLevelDictionary.cs.
        {
            LowLevelDictionary<TKey, TValue>.Entry entry = new LowLevelDictionary<TKey, TValue>.Entry();
            entry._key = key;
            entry._value = value;
            int bucket = this.GetBucket(key, 0);
            entry._next = this._buckets[bucket];
            this._buckets[bucket] = entry;
            this._numEntries++;
            if (this._numEntries > this._buckets.Length * 2)
            {
                this.ExpandBuckets();
            }
            return entry;
        }
References System.Collections.Generic.LowLevelDictionary< TKey, TValue >._buckets, System.Collections.Generic.LowLevelDictionary< TKey, TValue >._numEntries, System.Collections.Generic.LowLevelDictionary< TKey, TValue >.ExpandBuckets(), System.Collections.Generic.LowLevelDictionary< TKey, TValue >.GetBucket(), System.key, and System.value.
Referenced by System.Collections.Generic.LowLevelDictionary< TKey, TValue >.Add().