Terraria Decompiled: Terraria.Achievements.AchievementCondition.Complete
Complete()
virtual void Terraria.Achievements.AchievementCondition.Complete () inline virtual
Reimplemented in Terraria.GameContent.Achievements.CustomFloatCondition, and Terraria.GameContent.Achievements.CustomIntCondition.
Definition at line 75 of file AchievementCondition.cs.
        {
            if (this._isCompleted)
            {
                return;
            }
            this._isCompleted = true;
            if (this.OnComplete != null)
            {
                this.OnComplete(this);
            }
        }
References Terraria.Achievements.AchievementCondition._isCompleted, and Terraria.Achievements.AchievementCondition.OnComplete.
Referenced by Terraria.GameContent.Achievements.ItemCraftCondition.ItemCraftListener(), Terraria.GameContent.Achievements.ItemPickupCondition.ItemPickupListener(), Terraria.GameContent.Achievements.NPCKilledCondition.NPCKilledListener(), Terraria.GameContent.Achievements.ProgressionEventCondition.ProgressionEventListener(), and Terraria.GameContent.Achievements.TileDestroyedCondition.TileDestroyedListener().