Terraria Decompiled: Newtonsoft.Json.Utilities.FSharpUtils.GetMethodWithNonPublicFallback
GetMethodWithNonPublicFallback()
static MethodInfo Newtonsoft.Json.Utilities.FSharpUtils.GetMethodWithNonPublicFallback (Type type, string methodName, BindingFlags bindingFlags) inline static private
Definition at line 219 of file FSharpUtils.cs.
        {
            MethodInfo methodInfo = type.GetMethod(methodName, bindingFlags);
            if (methodInfo == null && (bindingFlags & 32) != 32)
            {
                methodInfo = type.GetMethod(methodName, bindingFlags | 32);
            }
            return methodInfo;
        }
References System.Type.GetMethod().
Referenced by Newtonsoft.Json.Utilities.FSharpUtils.CreateFSharpFuncCall(), and Newtonsoft.Json.Utilities.FSharpUtils.EnsureInitialized().