Terraria Decompiled: Newtonsoft.Json.Utilities.FSharpUtils.EnsureInitialized
EnsureInitialized()
static void Newtonsoft.Json.Utilities.FSharpUtils.EnsureInitialized (Assembly fsharpCoreAssembly) inline static
Definition at line 185 of file FSharpUtils.cs.
        {
            if (!FSharpUtils._initialized)
            {
                object @lock = FSharpUtils.Lock;
                lock (@lock)
                {
                    if (!FSharpUtils._initialized)
                    {
                        FSharpUtils.FSharpCoreAssembly = fsharpCoreAssembly;
                        Type type = fsharpCoreAssembly.GetType("Microsoft.FSharp.Reflection.FSharpType");
                        MethodInfo methodWithNonPublicFallback = FSharpUtils.GetMethodWithNonPublicFallback(type, "IsUnion", 24);
                        FSharpUtils.IsUnion = JsonTypeReflector.ReflectionDelegateFactory.CreateMethodCall<object>(methodWithNonPublicFallback);
                        MethodInfo methodWithNonPublicFallback2 = FSharpUtils.GetMethodWithNonPublicFallback(type, "GetUnionCases", 24);
                        FSharpUtils.GetUnionCases = JsonTypeReflector.ReflectionDelegateFactory.CreateMethodCall<object>(methodWithNonPublicFallback2);
                        Type type2 = fsharpCoreAssembly.GetType("Microsoft.FSharp.Reflection.FSharpValue");
                        FSharpUtils.PreComputeUnionTagReader = FSharpUtils.CreateFSharpFuncCall(type2, "PreComputeUnionTagReader");
                        FSharpUtils.PreComputeUnionReader = FSharpUtils.CreateFSharpFuncCall(type2, "PreComputeUnionReader");
                        FSharpUtils.PreComputeUnionConstructor = FSharpUtils.CreateFSharpFuncCall(type2, "PreComputeUnionConstructor");
                        Type type3 = fsharpCoreAssembly.GetType("Microsoft.FSharp.Reflection.UnionCaseInfo");
                        FSharpUtils.GetUnionCaseInfoName = JsonTypeReflector.ReflectionDelegateFactory.CreateGet<object>(type3.GetProperty("Name"));
                        FSharpUtils.GetUnionCaseInfoTag = JsonTypeReflector.ReflectionDelegateFactory.CreateGet<object>(type3.GetProperty("Tag"));
                        FSharpUtils.GetUnionCaseInfoDeclaringType = JsonTypeReflector.ReflectionDelegateFactory.CreateGet<object>(type3.GetProperty("DeclaringType"));
                        FSharpUtils.GetUnionCaseInfoFields = JsonTypeReflector.ReflectionDelegateFactory.CreateMethodCall<object>(type3.GetMethod("GetFields"));
                        FSharpUtils._ofSeq = fsharpCoreAssembly.GetType("Microsoft.FSharp.Collections.ListModule").GetMethod("OfSeq");
                        FSharpUtils._mapType = fsharpCoreAssembly.GetType("Microsoft.FSharp.Collections.FSharpMap`2");
                        Thread.MemoryBarrier();
                        FSharpUtils._initialized = true;
                    }
                }
            }
        }
References Newtonsoft.Json.Utilities.FSharpUtils._initialized, Newtonsoft.Json.Utilities.FSharpUtils.CreateFSharpFuncCall(), System.Type.GetMethod(), Newtonsoft.Json.Utilities.FSharpUtils.GetMethodWithNonPublicFallback(), System.Type.GetProperty(), System.Reflection.Assembly.GetType(), Newtonsoft.Json.Utilities.FSharpUtils.Lock, System.Threading.Thread.MemoryBarrier(), and Newtonsoft.Json.Serialization.JsonTypeReflector.ReflectionDelegateFactory.
Referenced by Newtonsoft.Json.Converters.DiscriminatedUnionConverter.CanConvert(), Newtonsoft.Json.Serialization.JsonDictionaryContract.JsonDictionaryContract(), and Newtonsoft.Json.Serialization.JsonArrayContract.StoreFSharpListCreatorIfNecessary().