Terraria Decompiled: Terraria.Net.Sockets.TcpSocket.GetStream
GetStream()
DebugNetworkStream Terraria.Net.Sockets.TcpSocket.GetStream () inline private
Definition at line 14 of file TcpSocket.cs.
        {
            if (this._debugStream == null)
            {
                return this._debugStream = new DebugNetworkStream(this._connection.GetStream());
            }
            return this._debugStream;
        }
References Terraria.Net.Sockets.TcpSocket._connection, and Terraria.Net.Sockets.TcpSocket._debugStream.
Referenced by Terraria.Net.Sockets.TcpSocket.AsyncReceive(), Terraria.Net.Sockets.TcpSocket.AsyncSend(), Terraria.Net.Sockets.TcpSocket.IsDataAvailable(), and Terraria.Net.Sockets.TcpSocket.SendCallback().