Terraria Decompiled: Newtonsoft.Json.Utilities.Base64Encoder.Encode
Encode()
void Newtonsoft.Json.Utilities.Base64Encoder.Encode (byte[] buffer, int index, int count) inline
Definition at line 38 of file Base64Encoder.cs.
        {
            this.ValidateEncode(buffer, index, count);
            if (this._leftOverBytesCount > 0)
            {
                if (this.FulfillFromLeftover(buffer, index, ref count))
                {
                    return;
                }
                int num = Convert.ToBase64CharArray(this._leftOverBytes, 0, 3, this._charsLine, 0);
                this.WriteChars(this._charsLine, 0, num);
            }
            this.StoreLeftOverBytes(buffer, index, ref count);
            int num2 = index + count;
            int num3 = 57;
            while (index < num2)
            {
                if (index + num3 > num2)
                {
                    num3 = num2 - index;
                }
                int num4 = Convert.ToBase64CharArray(buffer, index, num3, this._charsLine, 0);
                this.WriteChars(this._charsLine, 0, num4);
                index += num3;
            }
        }
References Newtonsoft.Json.Utilities.Base64Encoder._charsLine, Newtonsoft.Json.Utilities.Base64Encoder._leftOverBytes, Newtonsoft.Json.Utilities.Base64Encoder._leftOverBytesCount, System.count, Newtonsoft.Json.Utilities.Base64Encoder.FulfillFromLeftover(), System.index, Newtonsoft.Json.Utilities.Base64Encoder.StoreLeftOverBytes(), System.Convert.ToBase64CharArray(), Newtonsoft.Json.Utilities.Base64Encoder.ValidateEncode(), and Newtonsoft.Json.Utilities.Base64Encoder.WriteChars().
Referenced by Newtonsoft.Json.JsonTextWriter.WriteValue().