Terraria Decompiled: Steamworks.CallResult.OnRunCallResult
OnRunCallResult() [2/2]
override void Steamworks.CallResult< T >.OnRunCallResult (IntPtr pvParam, bool bFailed, ulong hSteamAPICall_) inline package
Definition at line 128 of file CallResult.2.cs.
        {
            if ((SteamAPICall_t)hSteamAPICall_ == this.m_hAPICall)
            {
                try
                {
                    this.m_Func((T)((object)Marshal.PtrToStructure(pvParam, typeof(T))), bFailed);
                }
                catch (Exception ex)
                {
                    CallbackDispatcher.ExceptionHandler(ex);
                }
            }
        }
References Steamworks.CallbackDispatcher.ExceptionHandler(), Steamworks.CallResult< T >.m_Func, Steamworks.CallResult< T >.m_hAPICall, and System.Runtime.InteropServices.Marshal.PtrToStructure().
Referenced by Steamworks.CallbackDispatcher.RunFrame().