Terraria Decompiled: Terraria.GameContent.NetModules.NetLiquidModule.Deserialize
Deserialize()
override bool Terraria.GameContent.NetModules.NetLiquidModule.Deserialize (BinaryReader reader, int userId) inline
Definition at line 53 of file NetLiquidModule.cs.
        {
            int num = (int)reader.ReadUInt16();
            for (int i = 0; i < num; i++)
            {
                int num2 = reader.ReadInt32();
                byte b = reader.ReadByte();
                byte b2 = reader.ReadByte();
                int num3 = (num2 >> 16) & 65535;
                int num4 = num2 & 65535;
                Tile tile = Main.tile[num3, num4];
                if (tile != null)
                {
                    tile.liquid = b;
                    tile.liquidType((int)b2);
                }
            }
            return true;
        }
References int, Terraria.Tile.liquidType(), System.IO.BinaryReader.ReadByte(), System.IO.BinaryReader.ReadInt32(), System.IO.BinaryReader.ReadUInt16(), and Terraria.Main.tile.