Terraria Decompiled: Terraria.GameContent.NetModules.NetLiquidModule.SerializeForPlayer
SerializeForPlayer()
static NetPacket Terraria.GameContent.NetModules.NetLiquidModule.SerializeForPlayer (int playerIndex) inline static
Definition at line 29 of file NetLiquidModule.cs.
        {
            NetLiquidModule._changesForPlayerCache.Clear();
            foreach (KeyValuePair<Point, NetLiquidModule.ChunkChanges> keyValuePair in NetLiquidModule._changesByChunkCoords)
            {
                if (keyValuePair.Value.BroadcastingCondition(playerIndex))
                {
                    NetLiquidModule._changesForPlayerCache.AddRange(keyValuePair.Value.DirtiedPackedTileCoords);
                }
            }
            NetPacket netPacket = NetModule.CreatePacket<NetLiquidModule>(65530);
            netPacket.Writer.Write((ushort)NetLiquidModule._changesForPlayerCache.Count);
            foreach (int num in NetLiquidModule._changesForPlayerCache)
            {
                int num2 = (num >> 16) & 65535;
                int num3 = num & 65535;
                netPacket.Writer.Write(num);
                netPacket.Writer.Write(Main.tile[num2, num3].liquid);
                netPacket.Writer.Write(Main.tile[num2, num3].liquidType());
            }
            return netPacket;
        }
References Terraria.GameContent.NetModules.NetLiquidModule._changesByChunkCoords, Terraria.GameContent.NetModules.NetLiquidModule._changesForPlayerCache, System.Collections.Generic.List< T >.AddRange(), System.Collections.Generic.List< T >.Clear(), System.Collections.Generic.List< T >.Count, Terraria.Tile.liquid, Terraria.Tile.liquidType(), Terraria.Main.tile, System.Collections.Generic.KeyValuePair< TKey, TValue >.Value, System.IO.BinaryWriter.Write(), and Terraria.Net.NetPacket.Writer.
Referenced by Terraria.GameContent.NetModules.NetLiquidModule.PrepareAndSendToEachPlayerSeparately().