Terraria Decompiled: Terraria.UI.ItemSorting.ClearAmmoSlotSpaces
ClearAmmoSlotSpaces()
static void Terraria.UI.ItemSorting.ClearAmmoSlotSpaces () inline static
Definition at line 461 of file ItemSorting.cs.
        {
            Item[] inventory = Main.player[Main.myPlayer].inventory;
            for (int i = 54; i < 58; i++)
            {
                Item item = inventory[i];
                if (!item.IsAir && item.ammo != AmmoID.None && item.stack < item.maxStack)
                {
                    int num = (item.favorited ? 54 : (i + 1));
                    ItemSorting.RefillItemStack(inventory, item, num, 58);
                }
            }
            for (int j = 54; j < 58; j++)
            {
                if (inventory[j].type > 0 && !inventory[j].favorited)
                {
                    ItemSorting.TrySlidingUp(inventory, j, 54);
                }
            }
        }
References Terraria.Player.inventory, System.item, Terraria.Main.myPlayer, Terraria.ID.AmmoID.None, Terraria.Main.player, Terraria.UI.ItemSorting.RefillItemStack(), and Terraria.UI.ItemSorting.TrySlidingUp().
Referenced by Terraria.UI.ItemSorting.SortAmmo().