Terraria Decompiled: Terraria.UI.ItemSorting.SetupWhiteLists
SetupWhiteLists()
static void Terraria.UI.ItemSorting.SetupWhiteLists () inline static
Definition at line 23 of file ItemSorting.cs.
        {
            ItemSorting._layerWhiteLists.Clear();
            List<ItemSorting.ItemSortingLayer> list = new List<ItemSorting.ItemSortingLayer>();
            List<Item> list2 = new List<Item>();
            List<int> list3 = new List<int>();
            list.Add(ItemSorting.ItemSortingLayers.WeaponsMelee);
            list.Add(ItemSorting.ItemSortingLayers.WeaponsRanged);
            list.Add(ItemSorting.ItemSortingLayers.WeaponsMagic);
            list.Add(ItemSorting.ItemSortingLayers.WeaponsMinions);
            list.Add(ItemSorting.ItemSortingLayers.WeaponsAssorted);
            list.Add(ItemSorting.ItemSortingLayers.WeaponsAmmo);
            list.Add(ItemSorting.ItemSortingLayers.ToolsPicksaws);
            list.Add(ItemSorting.ItemSortingLayers.ToolsHamaxes);
            list.Add(ItemSorting.ItemSortingLayers.ToolsPickaxes);
            list.Add(ItemSorting.ItemSortingLayers.ToolsAxes);
            list.Add(ItemSorting.ItemSortingLayers.ToolsHammers);
            list.Add(ItemSorting.ItemSortingLayers.ToolsTerraforming);
            list.Add(ItemSorting.ItemSortingLayers.ToolsFishing);
            list.Add(ItemSorting.ItemSortingLayers.ToolsGolf);
            list.Add(ItemSorting.ItemSortingLayers.ToolsInstruments);
            list.Add(ItemSorting.ItemSortingLayers.ToolsKeys);
            list.Add(ItemSorting.ItemSortingLayers.ToolsKites);
            list.Add(ItemSorting.ItemSortingLayers.ToolsAmmoLeftovers);
            list.Add(ItemSorting.ItemSortingLayers.ToolsMisc);
            list.Add(ItemSorting.ItemSortingLayers.ArmorCombat);
            list.Add(ItemSorting.ItemSortingLayers.ArmorVanity);
            list.Add(ItemSorting.ItemSortingLayers.ArmorAccessories);
            list.Add(ItemSorting.ItemSortingLayers.EquipGrapple);
            list.Add(ItemSorting.ItemSortingLayers.EquipMount);
            list.Add(ItemSorting.ItemSortingLayers.EquipCart);
            list.Add(ItemSorting.ItemSortingLayers.EquipLightPet);
            list.Add(ItemSorting.ItemSortingLayers.EquipVanityPet);
            list.Add(ItemSorting.ItemSortingLayers.PotionsDyes);
            list.Add(ItemSorting.ItemSortingLayers.PotionsHairDyes);
            list.Add(ItemSorting.ItemSortingLayers.PotionsLife);
            list.Add(ItemSorting.ItemSortingLayers.PotionsJustTheMushroom);
            list.Add(ItemSorting.ItemSortingLayers.PotionsMana);
            list.Add(ItemSorting.ItemSortingLayers.PotionsElixirs);
            list.Add(ItemSorting.ItemSortingLayers.PotionsBuffs);
            list.Add(ItemSorting.ItemSortingLayers.PotionsFood);
            list.Add(ItemSorting.ItemSortingLayers.MiscValuables);
            list.Add(ItemSorting.ItemSortingLayers.MiscPainting);
            list.Add(ItemSorting.ItemSortingLayers.MiscWiring);
            list.Add(ItemSorting.ItemSortingLayers.MiscMaterials);
            list.Add(ItemSorting.ItemSortingLayers.MiscJustTheGlowingMushroom);
            list.Add(ItemSorting.ItemSortingLayers.MiscRopes);
            list.Add(ItemSorting.ItemSortingLayers.MiscHerbsAndSeeds);
            list.Add(ItemSorting.ItemSortingLayers.MiscAcorns);
            list.Add(ItemSorting.ItemSortingLayers.MiscGems);
            list.Add(ItemSorting.ItemSortingLayers.MiscBossBags);
            list.Add(ItemSorting.ItemSortingLayers.MiscCritters);
            list.Add(ItemSorting.ItemSortingLayers.MiscExtractinator);
            list.Add(ItemSorting.ItemSortingLayers.LastMaterials);
            list.Add(ItemSorting.ItemSortingLayers.LastTilesImportant);
            list.Add(ItemSorting.ItemSortingLayers.LastTilesCommon);
            list.Add(ItemSorting.ItemSortingLayers.LastNotTrash);
            list.Add(ItemSorting.ItemSortingLayers.LastTrash);
            for (int i = -48; i < (int)ItemID.Count; i++)
            {
                Item item = new Item();
                item.netDefaults(i);
                list2.Add(item);
                list3.Add(i + 48);
            }
            Item[] array = list2.ToArray();
            ItemSorting._layerCount = list.Count;
            ItemSorting._layerIndexForItemType = new int[(int)ItemID.Count];
            for (int j = 0; j < list.Count; j++)
            {
                ItemSorting.ItemSortingLayer itemSortingLayer = list[j];
                List<int> list4 = itemSortingLayer.SortingMethod(itemSortingLayer, array, list3);
                List<int> list5 = new List<int>();
                for (int k = 0; k < list4.Count; k++)
                {
                    Item item2 = array[list4[k]];
                    list5.Add(item2.type);
                    ItemSorting._layerIndexForItemType[item2.type] = j;
                }
                ItemSorting._layerWhiteLists.Add(itemSortingLayer.Name, list5);
            }
        }
References Terraria.UI.ItemSorting._layerIndexForItemType, Terraria.UI.ItemSorting._layerWhiteLists, System.Collections.Generic.List< T >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), Terraria.UI.ItemSorting.ItemSortingLayers.ArmorAccessories, Terraria.UI.ItemSorting.ItemSortingLayers.ArmorCombat, Terraria.UI.ItemSorting.ItemSortingLayers.ArmorVanity, System.array, System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.Collections.Generic.List< T >.Count, Terraria.ID.ItemID.Count, Terraria.UI.ItemSorting.ItemSortingLayers.EquipCart, Terraria.UI.ItemSorting.ItemSortingLayers.EquipGrapple, Terraria.UI.ItemSorting.ItemSortingLayers.EquipLightPet, Terraria.UI.ItemSorting.ItemSortingLayers.EquipMount, Terraria.UI.ItemSorting.ItemSortingLayers.EquipVanityPet, int, System.item, Terraria.UI.ItemSorting.ItemSortingLayers.LastMaterials, Terraria.UI.ItemSorting.ItemSortingLayers.LastNotTrash, Terraria.UI.ItemSorting.ItemSortingLayers.LastTilesCommon, Terraria.UI.ItemSorting.ItemSortingLayers.LastTilesImportant, Terraria.UI.ItemSorting.ItemSortingLayers.LastTrash, System.list, Terraria.UI.ItemSorting.ItemSortingLayers.MiscAcorns, Terraria.UI.ItemSorting.ItemSortingLayers.MiscBossBags, Terraria.UI.ItemSorting.ItemSortingLayers.MiscCritters, Terraria.UI.ItemSorting.ItemSortingLayers.MiscExtractinator, Terraria.UI.ItemSorting.ItemSortingLayers.MiscGems, Terraria.UI.ItemSorting.ItemSortingLayers.MiscHerbsAndSeeds, Terraria.UI.ItemSorting.ItemSortingLayers.MiscJustTheGlowingMushroom, Terraria.UI.ItemSorting.ItemSortingLayers.MiscMaterials, Terraria.UI.ItemSorting.ItemSortingLayers.MiscPainting, Terraria.UI.ItemSorting.ItemSortingLayers.MiscRopes, Terraria.UI.ItemSorting.ItemSortingLayers.MiscValuables, Terraria.UI.ItemSorting.ItemSortingLayers.MiscWiring, Terraria.UI.ItemSorting.ItemSortingLayer.Name, Terraria.UI.ItemSorting.ItemSortingLayers.PotionsBuffs, Terraria.UI.ItemSorting.ItemSortingLayers.PotionsDyes, Terraria.UI.ItemSorting.ItemSortingLayers.PotionsElixirs, Terraria.UI.ItemSorting.ItemSortingLayers.PotionsFood, Terraria.UI.ItemSorting.ItemSortingLayers.PotionsHairDyes, Terraria.UI.ItemSorting.ItemSortingLayers.PotionsJustTheMushroom, Terraria.UI.ItemSorting.ItemSortingLayers.PotionsLife, Terraria.UI.ItemSorting.ItemSortingLayers.PotionsMana, Terraria.UI.ItemSorting.ItemSortingLayer.SortingMethod, System.Collections.Generic.List< T >.ToArray(), Terraria.UI.ItemSorting.ItemSortingLayers.ToolsAmmoLeftovers, Terraria.UI.ItemSorting.ItemSortingLayers.ToolsAxes, Terraria.UI.ItemSorting.ItemSortingLayers.ToolsFishing, Terraria.UI.ItemSorting.ItemSortingLayers.ToolsGolf, Terraria.UI.ItemSorting.ItemSortingLayers.ToolsHamaxes, Terraria.UI.ItemSorting.ItemSortingLayers.ToolsHammers, Terraria.UI.ItemSorting.ItemSortingLayers.ToolsInstruments, Terraria.UI.ItemSorting.ItemSortingLayers.ToolsKeys, Terraria.UI.ItemSorting.ItemSortingLayers.ToolsKites, Terraria.UI.ItemSorting.ItemSortingLayers.ToolsMisc, Terraria.UI.ItemSorting.ItemSortingLayers.ToolsPickaxes, Terraria.UI.ItemSorting.ItemSortingLayers.ToolsPicksaws, Terraria.UI.ItemSorting.ItemSortingLayers.ToolsTerraforming, Terraria.Item.type, Terraria.UI.ItemSorting.ItemSortingLayers.WeaponsAmmo, Terraria.UI.ItemSorting.ItemSortingLayers.WeaponsAssorted, Terraria.UI.ItemSorting.ItemSortingLayers.WeaponsMagic, Terraria.UI.ItemSorting.ItemSortingLayers.WeaponsMelee, Terraria.UI.ItemSorting.ItemSortingLayers.WeaponsMinions, and Terraria.UI.ItemSorting.ItemSortingLayers.WeaponsRanged.
Referenced by Terraria.Main.Initialize_AlmostEverything().