Terraria Decompiled: Terraria.UI.ItemSorting.Sort
Sort()
static void Terraria.UI.ItemSorting.Sort (bool withFeedback, Item[] inv, params int[] ignoreSlots) inline static private
Definition at line 190 of file ItemSorting.cs.
        {
            ItemSorting.SetupSortingPriorities();
            ItemSorting._sort_itemsToSort.Clear();
            ItemSorting._sort_sortedItemIndexes.Clear();
            ItemSorting._sort_counts.Clear();
            ItemSorting._sort_itemsCache.Clear();
            ItemSorting._sort_availableSortingSlots.Clear();
            for (int i = 0; i < inv.Length; i++)
            {
                if (!ignoreSlots.Contains(i))
                {
                    Item item = inv[i];
                    if (item != null && item.stack != 0 && item.type != 0 && !item.favorited)
                    {
                        ItemSorting._sort_itemsToSort.Add(i);
                    }
                }
            }
            for (int j = 0; j < ItemSorting._sort_itemsToSort.Count; j++)
            {
                Item item2 = inv[ItemSorting._sort_itemsToSort[j]];
                if (item2.stack < item2.maxStack)
                {
                    int num = item2.maxStack - item2.stack;
                    for (int k = j; k < ItemSorting._sort_itemsToSort.Count; k++)
                    {
                        if (j != k)
{
                            Item item3 = inv[ItemSorting._sort_itemsToSort[k]];
                            if (Item.CanStack(item2, item3) && item3.stack != item3.maxStack)
{
                                int num2 = item3.stack;
                                if (num < num2)
{
                                    num2 = num;
                                }
                                item2.stack += num2;
                                item3.stack -= num2;
                                num -= num2;
                                if (item3.stack == 0)
{
                                    inv[ItemSorting._sort_itemsToSort[k]] = new Item();
                                    ItemSorting._sort_itemsToSort.Remove(ItemSorting._sort_itemsToSort[k]);
                                    j--;
                                    k--;
                                    break;
                                }
                                if (num == 0)
{
                                    break;
                                }
                            }
                        }
                    }
                }
            }
            ItemSorting._sort_availableSortingSlots.AddRange(ItemSorting._sort_itemsToSort);
            for (int l = 0; l < inv.Length; l++)
            {
                if (!ignoreSlots.Contains(l) && !ItemSorting._sort_availableSortingSlots.Contains(l))
                {
                    Item item4 = inv[l];
                    if (item4 == null || item4.stack == 0 || item4.type == 0)
                    {
                        ItemSorting._sort_availableSortingSlots.Add(l);
                    }
                }
            }
            ItemSorting._sort_availableSortingSlots.Sort();
            foreach (ItemSorting.ItemSortingLayer itemSortingLayer in ItemSorting._layerList)
            {
                List<int> list = itemSortingLayer.SortingMethod(itemSortingLayer, inv, ItemSorting._sort_itemsToSort);
                if (list.Count > 0)
                {
                    ItemSorting._sort_counts.Add(list.Count);
                }
                ItemSorting._sort_sortedItemIndexes.AddRange(list);
            }
            ItemSorting._sort_sortedItemIndexes.AddRange(ItemSorting._sort_itemsToSort);
            foreach (int num3 in ItemSorting._sort_sortedItemIndexes)
            {
                ItemSorting._sort_itemsCache.Add(inv[num3]);
                inv[num3] = new Item();
            }
            float num4 = 1f / (float)ItemSorting._sort_counts.Count;
            float num5 = num4 / 2f;
            for (int m = 0; m < ItemSorting._sort_itemsCache.Count; m++)
            {
                int num6 = ItemSorting._sort_availableSortingSlots[0];
                if (withFeedback)
                {
                    ItemSlot.SetGlow(num6, num5, Main.player[Main.myPlayer].chest != -1);
                }
                List<int> sort_counts = ItemSorting._sort_counts;
                int num7 = sort_counts[0];
                sort_counts[0] = num7 - 1;
                if (ItemSorting._sort_counts[0] == 0)
                {
                    ItemSorting._sort_counts.RemoveAt(0);
                    num5 += num4;
                }
                inv[num6] = ItemSorting._sort_itemsCache[m];
                ItemSorting._sort_availableSortingSlots.Remove(num6);
            }
        }
References Terraria.UI.ItemSorting._layerList, Terraria.UI.ItemSorting._sort_availableSortingSlots, Terraria.UI.ItemSorting._sort_counts, Terraria.UI.ItemSorting._sort_itemsCache, Terraria.UI.ItemSorting._sort_itemsToSort, Terraria.UI.ItemSorting._sort_sortedItemIndexes, System.Collections.Generic.List< T >.Add(), System.Collections.Generic.List< T >.AddRange(), Terraria.Item.CanStack(), Terraria.Player.chest, System.Collections.Generic.List< T >.Clear(), System.Collections.Generic.List< T >.Contains(), System.Collections.Generic.List< T >.Count, System.item, System.list, Terraria.Item.maxStack, Terraria.Main.myPlayer, Terraria.Main.player, System.Collections.Generic.List< T >.Remove(), System.Collections.Generic.List< T >.RemoveAt(), Terraria.UI.ItemSlot.SetGlow(), Terraria.UI.ItemSorting.SetupSortingPriorities(), System.Collections.Generic.List< T >.Sort(), Terraria.Item.stack, and Terraria.Item.type.
Referenced by Terraria.UI.ItemSorting.SortInventory(), and Terraria.UI.ItemSorting.SortInventory().