Terraria Decompiled: Terraria.UI.ItemSorting.FillAmmoFromInventory
FillAmmoFromInventory()
static void Terraria.UI.ItemSorting.FillAmmoFromInventory () inline static
Definition at line 398 of file ItemSorting.cs.
        {
            ItemSorting._fillAmmoFromInventory_acceptedAmmoTypes.Clear();
            ItemSorting._fillAmmoFromInventory_emptyAmmoSlots.Clear();
            Item[] inventory = Main.player[Main.myPlayer].inventory;
            for (int i = 54; i < 58; i++)
            {
                ItemSlot.SetGlow(i, 0.31f, false);
                Item item = inventory[i];
                if (item.IsAir)
                {
                    ItemSorting._fillAmmoFromInventory_emptyAmmoSlots.Add(i);
                }
                else if (item.ammo != AmmoID.None)
                {
                    if (!ItemSorting._fillAmmoFromInventory_acceptedAmmoTypes.Contains(item.type))
                    {
                        ItemSorting._fillAmmoFromInventory_acceptedAmmoTypes.Add(item.type);
                    }
                    ItemSorting.RefillItemStack(inventory, inventory[i], 0, 50);
                }
            }
            if (ItemSorting._fillAmmoFromInventory_emptyAmmoSlots.Count < 1)
            {
                return;
            }
            for (int j = 0; j < 50; j++)
            {
                Item item2 = inventory[j];
                if (item2.stack >= 1 && item2.CanFillEmptyAmmoSlot() && ItemSorting._fillAmmoFromInventory_acceptedAmmoTypes.Contains(item2.type) && !item2.favorited)
                {
                    int num = ItemSorting._fillAmmoFromInventory_emptyAmmoSlots[0];
                    ItemSorting._fillAmmoFromInventory_emptyAmmoSlots.Remove(num);
                    Utils.Swap<Item>(ref inventory[j], ref inventory[num]);
                    ItemSorting.RefillItemStack(inventory, inventory[num], 0, 50);
                    if (ItemSorting._fillAmmoFromInventory_emptyAmmoSlots.Count == 0)
                    {
                        break;
                    }
                }
            }
            if (ItemSorting._fillAmmoFromInventory_emptyAmmoSlots.Count < 1)
            {
                return;
            }
            for (int k = 0; k < 50; k++)
            {
                Item item3 = inventory[k];
                if (item3.stack >= 1 && item3.CanFillEmptyAmmoSlot() && item3.FitsAmmoSlot() && !item3.favorited)
                {
                    int num2 = ItemSorting._fillAmmoFromInventory_emptyAmmoSlots[0];
                    ItemSorting._fillAmmoFromInventory_emptyAmmoSlots.Remove(num2);
                    Utils.Swap<Item>(ref inventory[k], ref inventory[num2]);
                    ItemSorting.RefillItemStack(inventory, inventory[num2], 0, 50);
                    if (ItemSorting._fillAmmoFromInventory_emptyAmmoSlots.Count == 0)
                    {
                        break;
                    }
                }
            }
        }
References Terraria.UI.ItemSorting._fillAmmoFromInventory_acceptedAmmoTypes, Terraria.UI.ItemSorting._fillAmmoFromInventory_emptyAmmoSlots, System.Collections.Generic.List< T >.Add(), Terraria.Item.CanFillEmptyAmmoSlot(), System.Collections.Generic.List< T >.Clear(), System.Collections.Generic.List< T >.Contains(), System.Collections.Generic.List< T >.Count, Terraria.Item.favorited, Terraria.Item.FitsAmmoSlot(), Terraria.Player.inventory, System.item, Terraria.Main.myPlayer, Terraria.ID.AmmoID.None, Terraria.Main.player, Terraria.UI.ItemSorting.RefillItemStack(), System.Collections.Generic.List< T >.Remove(), Terraria.UI.ItemSlot.SetGlow(), Terraria.Item.stack, and Terraria.Item.type.
Referenced by Terraria.UI.ItemSorting.SortAmmo().