Terraria Decompiled: Terraria.UI.ItemSorting.SortCoins
SortCoins()
static void Terraria.UI.ItemSorting.SortCoins () inline static private
Definition at line 483 of file ItemSorting.cs.
        {
            Item[] inventory = Main.LocalPlayer.inventory;
            bool flag;
            long num = Utils.CoinsCount(out flag, inventory, new int[] { 58 });
            int commonMaxStack = Item.CommonMaxStack;
            if (flag)
            {
                return;
            }
            int[] array = Utils.CoinsSplit(num);
            int num2 = 0;
            for (int i = 0; i < 3; i++)
            {
                int j = array[i];
                while (j > 0)
                {
                    j -= 99;
                    num2++;
                }
            }
            int k = array[3];
            while (k > commonMaxStack)
            {
                k -= commonMaxStack;
                num2++;
            }
            int num3 = 0;
            for (int l = 0; l < 58; l++)
            {
                if (inventory[l].type >= 71 && inventory[l].type <= 74 && inventory[l].stack > 0)
                {
                    num3++;
                }
            }
            if (num3 < num2)
            {
                return;
            }
            for (int m = 0; m < 58; m++)
            {
                if (inventory[m].type >= 71 && inventory[m].type <= 74 && inventory[m].stack > 0)
                {
                    inventory[m].TurnToAir(false);
                }
            }
            int num4 = 100;
            do
            {
                int num5 = -1;
                for (int n = 3; n >= 0; n--)
                {
                    if (array[n] > 0)
                    {
                        num5 = n;
                        break;
                    }
                }
                if (num5 == -1)
                {
                    return;
                }
                int num6 = array[num5];
                if (num5 == 3 && num6 > commonMaxStack)
                {
                    num6 = commonMaxStack;
                }
                bool flag2 = false;
                if (!flag2)
                {
                    for (int num7 = 50; num7 < 54; num7++)
                    {
                        if (inventory[num7].IsAir)
{
                            inventory[num7].SetDefaults(71 + num5, null);
                            inventory[num7].stack = num6;
                            array[num5] -= num6;
                            flag2 = true;
                            break;
                        }
                    }
                }
                if (!flag2)
                {
                    for (int num8 = 0; num8 < 50; num8++)
                    {
                        if (inventory[num8].IsAir)
{
                            inventory[num8].SetDefaults(71 + num5, null);
                            inventory[num8].stack = num6;
                            array[num5] -= num6;
                            break;
                        }
                    }
                }
                num4--;
            }
            while (num4 > 0);
            for (int num9 = 3; num9 >= 0; num9--)
            {
                if (array[num9] > 0)
                {
                    Main.LocalPlayer.QuickSpawnItem(Main.LocalPlayer.GetItemSource_InventoryOverflow(), 71 + num9, array[num9]);
                }
            }
        }
References System.array, Terraria.Utils.CoinsCount(), Terraria.Utils.CoinsSplit(), Terraria.Item.CommonMaxStack, Terraria.Player.GetItemSource_InventoryOverflow(), Terraria.Player.inventory, Terraria.Main.LocalPlayer, Terraria.Player.QuickSpawnItem(), Terraria.Item.SetDefaults(), System.stack, Terraria.Item.stack, and Terraria.Item.TurnToAir().
Referenced by Terraria.UI.ItemSorting.SortInventory().