Terraria Decompiled: System.Security.Permissions.SecurityPermission.Intersect
Intersect()
override IPermission System.Security.Permissions.SecurityPermission.Intersect (IPermission target) inline
Implements System.Security.IPermission.
Definition at line 60 of file SecurityPermission.cs.
        {
            SecurityPermission securityPermission = this.Cast(target);
            if (securityPermission == null)
            {
                return null;
            }
            if (this.IsEmpty() || securityPermission.IsEmpty())
            {
                return null;
            }
            if (this.IsUnrestricted() && securityPermission.IsUnrestricted())
            {
                return new SecurityPermission(PermissionState.Unrestricted);
            }
            if (this.IsUnrestricted())
            {
                return securityPermission.Copy();
            }
            if (securityPermission.IsUnrestricted())
            {
                return this.Copy();
            }
            SecurityPermissionFlag securityPermissionFlag = this.flags & securityPermission.flags;
            if (securityPermissionFlag == SecurityPermissionFlag.NoFlags)
            {
                return null;
            }
            return new SecurityPermission(securityPermissionFlag);
        }
References System.Security.Permissions.SecurityPermission.Cast(), System.Security.Permissions.SecurityPermission.Copy(), System.Security.Permissions.SecurityPermission.flags, System.Security.Permissions.SecurityPermission.IsEmpty(), System.Security.Permissions.SecurityPermission.IsUnrestricted(), and System.Security.Permissions.SecurityPermission.SecurityPermission().