Terraria Decompiled: Terraria.IO.ResourcePack.OpenStream
OpenStream()
Stream Terraria.IO.ResourcePack.OpenStream (string fileName) inline private
Definition at line 210 of file ResourcePack.cs.
        {
            if (!this.IsCompressed)
            {
                return File.OpenRead(Path.Combine(this.FullPath, fileName));
            }
            ZipEntry zipEntry = this._zipFile[fileName];
            MemoryStream memoryStream = new MemoryStream((int)zipEntry.UncompressedSize);
            zipEntry.Extract(memoryStream);
            memoryStream.Position = 0L;
            return memoryStream;
        }
References Terraria.IO.ResourcePack._zipFile, System.IO.Path.Combine(), Ionic.Zip.ZipEntry.Extract(), Terraria.IO.ResourcePack.IsCompressed, System.L, System.IO.File.OpenRead(), and Ionic.Zip.ZipEntry.UncompressedSize.
Referenced by Terraria.IO.ResourcePack.CreateIcon(), and Terraria.IO.ResourcePack.LoadManifest().