Terraria Decompiled: Terraria.IO.ResourcePack.ResourcePack
ResourcePack()
Terraria.IO.ResourcePack.ResourcePack (IServiceProvider services, string path, ResourcePack::BrandingType branding = ResourcePack::BrandingType::None) inline
Definition at line 134 of file ResourcePack.cs.
        {
            if (File.Exists(path))
            {
                this.IsCompressed = true;
            }
            else if (!Directory.Exists(path))
            {
                throw new FileNotFoundException("Unable to find file or folder for resource pack at: " + path);
            }
            this.FileName = Path.GetFileName(path);
            this._services = services;
            this.FullPath = path;
            this.Branding = branding;
            if (this.IsCompressed)
            {
                this._zipFile = ZipFile.Read(path);
            }
            this.LoadManifest();
        }
References System.IO.Directory.Exists(), System.IO.File.Exists(), System.IO.Path.GetFileName(), Terraria.IO.ResourcePack.IsCompressed, Terraria.IO.ResourcePack.LoadManifest(), and Ionic.Zip.ZipFile.Read().