Terraria Decompiled: Terraria.IO.ResourcePack.LoadManifest
LoadManifest()
void Terraria.IO.ResourcePack.LoadManifest () inline private
Definition at line 189 of file ResourcePack.cs.
        {
            if (!this.HasFile("pack.json"))
            {
                throw new FileNotFoundException(string.Format("Resource Pack at \"{0}\" must contain a {1} file.", this.FullPath, "pack.json"));
            }
            JObject jobject;
            using (Stream stream = this.OpenStream("pack.json"))
            {
                using (StreamReader streamReader = new StreamReader(stream))
                {
                    jobject = JObject.Parse(streamReader.ReadToEnd());
                }
            }
            this.Name = Extensions.Value<string>(jobject["Name"]);
            this.Description = Extensions.Value<string>(jobject["Description"]);
            this.Author = Extensions.Value<string>(jobject["Author"]);
            this.Version = jobject["Version"].ToObject<ResourcePackVersion>();
        }
References System.Format, Terraria.IO.ResourcePack.FullPath, Terraria.IO.ResourcePack.HasFile(), Terraria.IO.ResourcePack.OpenStream(), Newtonsoft.Json.Linq.JObject.Parse(), System.IO.StreamReader.ReadToEnd(), and Newtonsoft.Json.Linq.JToken.ToObject().
Referenced by Terraria.IO.ResourcePack.ResourcePack().