Terraria Decompiled: Mono.Interop.ComInteropProxy.CacheProxy
CacheProxy()
void Mono.Interop.ComInteropProxy.CacheProxy () inline private
Definition at line 32 of file ComInteropProxy.cs.
        {
            ComInteropProxy comInteropProxy = null;
            ComInteropProxy.FindProxy(this.com_object.IUnknown, ref comInteropProxy);
            if (comInteropProxy == null)
            {
                ComInteropProxy comInteropProxy2 = this;
                ComInteropProxy.AddProxy(this.com_object.IUnknown, ref comInteropProxy2);
                return;
            }
            Interlocked.Increment(ref this.ref_count);
        }
References Mono.Interop.ComInteropProxy.AddProxy(), Mono.Interop.ComInteropProxy.com_object, Mono.Interop.ComInteropProxy.FindProxy(), System.Threading.Interlocked.Increment(), System.__ComObject.IUnknown, and Mono.Interop.ComInteropProxy.ref_count.
Referenced by Mono.Interop.ComInteropProxy.ComInteropProxy().