Terraria Decompiled: Mono.Interop.ComInteropProxy.CreateProxy
CreateProxy()
static ComInteropProxy Mono.Interop.ComInteropProxy.CreateProxy (Type t) inline static package
Definition at line 78 of file ComInteropProxy.cs.
        {
            IntPtr intPtr = __ComObject.CreateIUnknown(t);
            ComInteropProxy comInteropProxy = null;
            ComInteropProxy.FindProxy(intPtr, ref comInteropProxy);
            ComInteropProxy comInteropProxy2;
            if (comInteropProxy != null)
            {
                Type type = comInteropProxy.com_object.GetType();
                if (type != t)
                {
                    throw new InvalidCastException(string.Format("Unable to cast object of type '{0}' to type '{1}'.", type, t));
                }
                comInteropProxy2 = comInteropProxy;
                Marshal.Release(intPtr);
            }
            else
            {
                comInteropProxy2 = new ComInteropProxy(t);
                comInteropProxy2.com_object.Initialize(intPtr, comInteropProxy2);
            }
            return comInteropProxy2;
        }
References Mono.Interop.ComInteropProxy.com_object, Mono.Interop.ComInteropProxy.ComInteropProxy(), System.__ComObject.CreateIUnknown(), Mono.Interop.ComInteropProxy.FindProxy(), System.Format, System.__ComObject.Initialize(), and System.Runtime.InteropServices.Marshal.Release().
Referenced by System.Runtime.Remoting.RemotingServices.CreateClientProxyForComInterop().