Terraria Decompiled: Mono.Interop.ComInteropProxy.GetProxy
GetProxy()
static ComInteropProxy Mono.Interop.ComInteropProxy.GetProxy (IntPtr pItf, Type t) inline static package
Definition at line 60 of file ComInteropProxy.cs.
        {
            Guid iid_IUnknown = __ComObject.IID_IUnknown;
            IntPtr intPtr;
            Marshal.ThrowExceptionForHR(Marshal.QueryInterface(pItf, ref iid_IUnknown, out intPtr));
            ComInteropProxy comInteropProxy = null;
            ComInteropProxy.FindProxy(intPtr, ref comInteropProxy);
            if (comInteropProxy == null)
            {
                Marshal.Release(intPtr);
                return new ComInteropProxy(intPtr);
            }
            Marshal.Release(intPtr);
            Interlocked.Increment(ref comInteropProxy.ref_count);
            return comInteropProxy;
        }
References Mono.Interop.ComInteropProxy.ComInteropProxy(), Mono.Interop.ComInteropProxy.FindProxy(), System.__ComObject.IID_IUnknown, System.Threading.Interlocked.Increment(), System.Runtime.InteropServices.Marshal.QueryInterface(), Mono.Interop.ComInteropProxy.ref_count, System.Runtime.InteropServices.Marshal.Release(), and System.Runtime.InteropServices.Marshal.ThrowExceptionForHR().
Referenced by System.Runtime.InteropServices.Marshal.CreateWrapperOfType(), and System.Runtime.InteropServices.Marshal.GetObjectForIUnknown().