Terraria Decompiled: System.Security.Permissions.IsolatedStorageFilePermission.Intersect
Intersect()
override IPermission System.Security.Permissions.IsolatedStorageFilePermission.Intersect (IPermission target) inline
Implements System.Security.IPermission.
Definition at line 31 of file IsolatedStorageFilePermission.cs.
        {
            IsolatedStorageFilePermission isolatedStorageFilePermission = this.Cast(target);
            if (isolatedStorageFilePermission == null)
            {
                return null;
            }
            if (base.IsEmpty() && isolatedStorageFilePermission.IsEmpty())
            {
                return null;
            }
            return new IsolatedStorageFilePermission(PermissionState.None)
            {
                m_userQuota = ((this.m_userQuota < isolatedStorageFilePermission.m_userQuota) ? this.m_userQuota : isolatedStorageFilePermission.m_userQuota),
                m_machineQuota = ((this.m_machineQuota < isolatedStorageFilePermission.m_machineQuota) ? this.m_machineQuota : isolatedStorageFilePermission.m_machineQuota),
                m_expirationDays = ((this.m_expirationDays < isolatedStorageFilePermission.m_expirationDays) ? this.m_expirationDays : isolatedStorageFilePermission.m_expirationDays),
                m_permanentData = (this.m_permanentData && isolatedStorageFilePermission.m_permanentData),
                UsageAllowed = ((this.m_allowed < isolatedStorageFilePermission.m_allowed) ? this.m_allowed : isolatedStorageFilePermission.m_allowed)
            };
        }
References System.Security.Permissions.IsolatedStorageFilePermission.Cast(), System.Security.Permissions.IsolatedStoragePermission.IsEmpty(), System.Security.Permissions.IsolatedStorageFilePermission.IsolatedStorageFilePermission(), System.Security.Permissions.IsolatedStoragePermission.m_allowed, System.Security.Permissions.IsolatedStoragePermission.m_expirationDays, System.Security.Permissions.IsolatedStoragePermission.m_machineQuota, System.Security.Permissions.IsolatedStoragePermission.m_permanentData, System.Security.Permissions.IsolatedStoragePermission.m_userQuota, and System.Security.Permissions.IsolatedStoragePermission.UsageAllowed.