Terraria Decompiled: Terraria.GameContent.Creative.CreativePowerManager.TryListingPermissionsFrom
TryListingPermissionsFrom()
static void Terraria.GameContent.Creative.CreativePowerManager.TryListingPermissionsFrom (string line) inline static
Definition at line 52 of file CreativePowerManager.cs.
        {
            int length = "journeypermission_".Length;
            if (line.Length < length)
            {
                return;
            }
            if (!line.ToLower().StartsWith("journeypermission_"))
            {
                return;
            }
            string[] array = line.Substring(length).Split(new char[] { '=' });
            if (array.Length != 2)
            {
                return;
            }
            int num;
            if (!int.TryParse(array[1].Trim(), out num))
            {
                return;
            }
            PowerPermissionLevel powerPermissionLevel = (PowerPermissionLevel)Utils.Clamp<int>(num, 0, 2);
            string text = array[0].Trim().ToLower();
            CreativePowerManager.Initialize();
            ICreativePower creativePower;
            if (!CreativePowerManager.Instance._powersByName.TryGetValue(text, out creativePower))
            {
                return;
            }
            creativePower.DefaultPermissionLevel = powerPermissionLevel;
            creativePower.CurrentPermissionLevel = powerPermissionLevel;
        }
References Terraria.GameContent.Creative.CreativePowerManager._powersByName, System.array, Terraria.Utils.Clamp(), Terraria.GameContent.Creative.CreativePowerManager.Initialize(), Terraria.GameContent.Creative.CreativePowerManager.Instance, System.length, and System.text.
Referenced by Terraria.Main.LoadDedConfig().