Terraria Decompiled: Terraria.GameContent.Creative.CreativePowerManager.SyncThingsToJoiningPlayer
SyncThingsToJoiningPlayer()
void Terraria.GameContent.Creative.CreativePowerManager.SyncThingsToJoiningPlayer (int playerIndex) inline
Definition at line 186 of file CreativePowerManager.cs.
        {
            foreach (KeyValuePair<ushort, ICreativePower> keyValuePair in this._powersById)
            {
                NetPacket netPacket = NetCreativePowerPermissionsModule.SerializeCurrentPowerPermissionLevel(keyValuePair.Key, (int)keyValuePair.Value.CurrentPermissionLevel);
                NetManager.Instance.SendToClient(netPacket, playerIndex);
            }
            foreach (KeyValuePair<ushort, ICreativePower> keyValuePair2 in this._powersById)
            {
                IOnPlayerJoining onPlayerJoining = keyValuePair2.Value as IOnPlayerJoining;
                if (onPlayerJoining != null)
                {
                    onPlayerJoining.OnPlayerJoining(playerIndex);
                }
            }
        }
References Terraria.GameContent.Creative.CreativePowerManager._powersById, Terraria.Net.NetManager.Instance, System.Collections.Generic.KeyValuePair< TKey, TValue >.Key, Terraria.GameContent.IOnPlayerJoining.OnPlayerJoining(), Terraria.Net.NetManager.SendToClient(), Terraria.GameContent.NetModules.NetCreativePowerPermissionsModule.SerializeCurrentPowerPermissionLevel(), and System.Collections.Generic.KeyValuePair< TKey, TValue >.Value.
Referenced by Terraria.MessageBuffer.GetData().