Terraria Decompiled: Terraria.GameContent.Creative.CreativePowerManager.ResetDataForNewPlayer
ResetDataForNewPlayer()
void Terraria.GameContent.Creative.CreativePowerManager.ResetDataForNewPlayer (Player player) inline
Definition at line 269 of file CreativePowerManager.cs.
        {
            foreach (KeyValuePair<ushort, ICreativePower> keyValuePair in this._powersById)
            {
                IPersistentPerPlayerContent persistentPerPlayerContent = keyValuePair.Value as IPersistentPerPlayerContent;
                if (persistentPerPlayerContent != null)
                {
                    persistentPerPlayerContent.Reset();
                    persistentPerPlayerContent.ResetDataForNewPlayer(player);
                }
            }
        }
References Terraria.GameContent.Creative.CreativePowerManager._powersById, Terraria.GameContent.IPersistentPerPlayerContent.Reset(), and Terraria.GameContent.IPersistentPerPlayerContent.ResetDataForNewPlayer().
Referenced by Terraria.Player.Deserialize(), and Terraria.GameContent.UI.States.UICharacterCreation.SetupPlayerStatsAndInventoryBasedOnDifficulty().