Terraria Decompiled: Terraria.GameContent.Drawing.WindGrid.GetWindTime
GetWindTime()
void Terraria.GameContent.Drawing.WindGrid.GetWindTime (int tileX, int tileY, int timeThreshold, out int windTimeLeft, out int directionX, out int directionY) inline
Definition at line 28 of file WindGrid.cs.
        {
            WindGrid.WindCoord windCoord = this._grid[tileX % this._width, tileY % this._height];
            directionX = windCoord.DirectionX;
            directionY = windCoord.DirectionY;
            if (windCoord.Time + timeThreshold < this._gameTime)
            {
                windTimeLeft = 0;
                return;
            }
            windTimeLeft = this._gameTime - windCoord.Time;
        }
References Terraria.GameContent.Drawing.WindGrid._grid, Terraria.GameContent.Drawing.WindGrid._height, Terraria.GameContent.Drawing.WindGrid._width, Terraria.GameContent.Drawing.WindGrid.WindCoord.DirectionX, Terraria.GameContent.Drawing.WindGrid.WindCoord.DirectionY, and Terraria.GameContent.Drawing.WindGrid.WindCoord.Time.
Referenced by Terraria.GameContent.Drawing.TileDrawing.DrawTiles_EmitParticles(), Terraria.GameContent.Drawing.TileDrawing.GetHighestWindGridPushComplex(), Terraria.GameContent.Drawing.TileDrawing.GetWindGridPush(), Terraria.GameContent.Drawing.TileDrawing.GetWindGridPush2Axis(), and Terraria.GameContent.Drawing.TileDrawing.GetWindGridPushComplex().