Terraria Decompiled: Terraria.GameContent.Drawing.WindGrid.ScanPlayer
ScanPlayer()
void Terraria.GameContent.Drawing.WindGrid.ScanPlayer (int i) inline private
Definition at line 79 of file WindGrid.cs.
        {
            Player player = Main.player[i];
            if (!player.active || player.dead || (player.velocity.X == 0f && player.velocity.Y == 0f))
            {
                return;
            }
            if (!Utils.CenteredRectangle(Main.Camera.Center, Main.Camera.UnscaledSize).Intersects(player.Hitbox))
            {
                return;
            }
            if (player.velocity.HasNaNs())
            {
                return;
            }
            int num = Math.Sign(player.velocity.X);
            int num2 = Math.Sign(player.velocity.Y);
            foreach (Point point in Collision.GetTilesIn(player.TopLeft, player.BottomRight))
            {
                this.SetWindTime(point.X, point.Y, num, num2);
            }
        }
References Terraria.Player.active, Terraria.Main.Camera, Terraria.Utils.CenteredRectangle(), Terraria.Player.dead, Terraria.Collision.GetTilesIn(), Terraria.Entity.Hitbox, Microsoft.Xna.Framework.Rectangle.Intersects(), Terraria.Main.player, Terraria.GameContent.Drawing.WindGrid.SetWindTime(), System.Math.Sign(), Terraria.Entity.velocity, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Point.Y, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.GameContent.Drawing.WindGrid.ScanPlayers().