Terraria Decompiled: Terraria.GameContent.Drawing.WindGrid.SetSize
SetSize()
void Terraria.GameContent.Drawing.WindGrid.SetSize (int targetWidth, int targetHeight) inline
Definition at line 10 of file WindGrid.cs.
        {
            this._width = Math.Max(this._width, targetWidth);
            this._height = Math.Max(this._height, targetHeight);
            this.ResizeGrid();
        }
References Terraria.GameContent.Drawing.WindGrid._height, Terraria.GameContent.Drawing.WindGrid._width, System.Math.Max(), and Terraria.GameContent.Drawing.WindGrid.ResizeGrid().
Referenced by Terraria.GameContent.Drawing.TileDrawing.EnsureWindGridSize().