Terraria Decompiled: Ionic.Zip.ZipEntry.PostProcessOutput
PostProcessOutput()
void Ionic.Zip.ZipEntry.PostProcessOutput (Stream s) inline package
Definition at line 2916 of file ZipEntry.cs.
        {
            CountingStream countingStream = s as CountingStream;
            if (this._UncompressedSize == 0L && this._CompressedSize == 0L)
            {
                if (this._Source == ZipEntrySource.ZipOutputStream)
                {
                    return;
                }
                if (this._Password != null)
                {
                    int num = 0;
                    if (this.Encryption == EncryptionAlgorithm.PkzipWeak)
                    {
                        num = 12;
                    }
                    if (this._Source == ZipEntrySource.ZipOutputStream && !s.CanSeek)
                    {
                        throw new ZipException("Zero bytes written, encryption in use, and non-seekable output.");
                    }
                    if (this.Encryption != EncryptionAlgorithm.None)
                    {
                        s.Seek((long)(-1 * num), 1);
                        s.SetLength(s.Position);
                        SharedUtilities.Workaround_Ladybug318918(s);
                        if (countingStream != null)
{
                            countingStream.Adjust((long)num);
                        }
                        this._LengthOfHeader -= num;
                        this.__FileDataPosition -= (long)num;
                    }
                    this._Password = null;
                    this._BitField &= -2;
                    int num2 = 6;
                    this._EntryHeader[num2++] = (byte)(this._BitField & 255);
                    this._EntryHeader[num2++] = (byte)(((int)this._BitField & 65280) >> 8);
                }
                this.CompressionMethod = CompressionMethod.None;
                this.Encryption = EncryptionAlgorithm.None;
            }
            else if (this._zipCrypto_forWrite != null && this.Encryption == EncryptionAlgorithm.PkzipWeak)
            {
                this._CompressedSize += 12L;
            }
            int num3 = 8;
            this._EntryHeader[num3++] = (byte)(this._CompressionMethod & 255);
            this._EntryHeader[num3++] = (byte)(((int)this._CompressionMethod & 65280) >> 8);
            num3 = 14;
            this._EntryHeader[num3++] = (byte)(this._Crc32 & 255);
            this._EntryHeader[num3++] = (byte)((this._Crc32 & 65280) >> 8);
            this._EntryHeader[num3++] = (byte)((this._Crc32 & 16711680) >> 16);
            this._EntryHeader[num3++] = (byte)(((long)this._Crc32 & (long)((ulong)(-16777216))) >> 24);
            this.SetZip64Flags();
            short num4 = (short)((int)this._EntryHeader[26] + (int)this._EntryHeader[27] * 256);
            short num5 = (short)((int)this._EntryHeader[28] + (int)this._EntryHeader[29] * 256);
            if (this._OutputUsesZip64.Value)
            {
                this._EntryHeader[4] = 45;
                this._EntryHeader[5] = 0;
                for (int i = 0; i < 8; i++)
                {
                    this._EntryHeader[num3++] = byte.MaxValue;
                }
                num3 = (int)(30 + num4);
                this._EntryHeader[num3++] = 1;
                this._EntryHeader[num3++] = 0;
                num3 += 2;
                Array.Copy(BitConverter.GetBytes(this._UncompressedSize), 0, this._EntryHeader, num3, 8);
                num3 += 8;
                Array.Copy(BitConverter.GetBytes(this._CompressedSize), 0, this._EntryHeader, num3, 8);
            }
            else
            {
                this._EntryHeader[4] = 20;
                this._EntryHeader[5] = 0;
                num3 = 18;
                this._EntryHeader[num3++] = (byte)(this._CompressedSize & 255L);
                this._EntryHeader[num3++] = (byte)((this._CompressedSize & 65280L) >> 8);
                this._EntryHeader[num3++] = (byte)((this._CompressedSize & 16711680L) >> 16);
                this._EntryHeader[num3++] = (byte)((this._CompressedSize & (long)((ulong)(-16777216))) >> 24);
                this._EntryHeader[num3++] = (byte)(this._UncompressedSize & 255L);
                this._EntryHeader[num3++] = (byte)((this._UncompressedSize & 65280L) >> 8);
                this._EntryHeader[num3++] = (byte)((this._UncompressedSize & 16711680L) >> 16);
                this._EntryHeader[num3++] = (byte)((this._UncompressedSize & (long)((ulong)(-16777216))) >> 24);
                if (num5 != 0)
                {
                    num3 = (int)(30 + num4);
                    short num6 = (short)((int)this._EntryHeader[num3 + 2] + (int)this._EntryHeader[num3 + 3] * 256);
                    if (num6 == 16)
                    {
                        this._EntryHeader[num3++] = 153;
                        this._EntryHeader[num3++] = 153;
                    }
                }
            }
            if ((this._BitField & 8) != 8 || (this._Source == ZipEntrySource.ZipOutputStream && s.CanSeek))
            {
                ZipSegmentedStream zipSegmentedStream = s as ZipSegmentedStream;
                if (zipSegmentedStream != null && this._diskNumber != zipSegmentedStream.CurrentSegment)
                {
                    using (Stream stream = ZipSegmentedStream.ForUpdate(this._container.ZipFile.Name, this._diskNumber))
                    {
                        stream.Seek(this._RelativeOffsetOfLocalHeader, 0);
                        stream.Write(this._EntryHeader, 0, this._EntryHeader.Length);
                        goto IL_04CA;
                    }
                }
                s.Seek(this._RelativeOffsetOfLocalHeader, 0);
                s.Write(this._EntryHeader, 0, this._EntryHeader.Length);
                if (countingStream != null)
                {
                    countingStream.Adjust((long)this._EntryHeader.Length);
                }
                s.Seek(this._CompressedSize, 1);
            }
            IL_04CA:
            if ((this._BitField & 8) == 8 && !this.IsDirectory)
            {
                byte[] array = new byte[16 + (this._OutputUsesZip64.Value ? 8 : 0)];
                num3 = 0;
                Array.Copy(BitConverter.GetBytes(134695760), 0, array, num3, 4);
                num3 += 4;
                Array.Copy(BitConverter.GetBytes(this._Crc32), 0, array, num3, 4);
                num3 += 4;
                if (this._OutputUsesZip64.Value)
                {
                    Array.Copy(BitConverter.GetBytes(this._CompressedSize), 0, array, num3, 8);
                    num3 += 8;
                    Array.Copy(BitConverter.GetBytes(this._UncompressedSize), 0, array, num3, 8);
                    num3 += 8;
                }
                else
                {
                    array[num3++] = (byte)(this._CompressedSize & 255L);
                    array[num3++] = (byte)((this._CompressedSize & 65280L) >> 8);
                    array[num3++] = (byte)((this._CompressedSize & 16711680L) >> 16);
                    array[num3++] = (byte)((this._CompressedSize & (long)((ulong)(-16777216))) >> 24);
                    array[num3++] = (byte)(this._UncompressedSize & 255L);
                    array[num3++] = (byte)((this._UncompressedSize & 65280L) >> 8);
                    array[num3++] = (byte)((this._UncompressedSize & 16711680L) >> 16);
                    array[num3++] = (byte)((this._UncompressedSize & (long)((ulong)(-16777216))) >> 24);
                }
                s.Write(array, 0, array.Length);
                this._LengthOfTrailer += array.Length;
            }
        }
References Ionic.Zip.ZipEntry._BitField, Ionic.Zip.ZipEntry._CompressedSize, Ionic.Zip.ZipEntry._CompressionMethod, Ionic.Zip.ZipEntry._container, Ionic.Zip.ZipEntry._Crc32, Ionic.Zip.ZipEntry._diskNumber, Ionic.Zip.ZipEntry._EntryHeader, Ionic.Zip.ZipEntry._OutputUsesZip64, Ionic.Zip.ZipEntry._Password, Ionic.Zip.ZipEntry._RelativeOffsetOfLocalHeader, Ionic.Zip.ZipEntry._Source, Ionic.Zip.ZipEntry._UncompressedSize, Ionic.Zip.ZipEntry._zipCrypto_forWrite, Ionic.Zip.CountingStream.Adjust(), System.array, System.Array.Copy(), Ionic.Zip.ZipSegmentedStream.CurrentSegment, Ionic.Zip.ZipEntry.Encryption, Ionic.Zip.ZipSegmentedStream.ForUpdate(), System.BitConverter.GetBytes(), int, Ionic.Zip.ZipEntry.IsDirectory, System.L, long, Ionic.Zip.ZipFile.Name, System.s, System.IO.Stream.Seek(), Ionic.Zip.ZipEntry.SetZip64Flags(), Ionic.Zip.SharedUtilities.Workaround_Ladybug318918(), System.IO.Stream.Write(), and Ionic.Zip.ZipContainer.ZipFile.
Referenced by Ionic.Zip.ZipOutputStream._FinishCurrentEntry(), and Ionic.Zip.ZipEntry._WriteEntryData().