Terraria Decompiled: Ionic.Zip.ZipEntry.Write
Write()
void Ionic.Zip.ZipEntry.Write (Stream s) inline package
Definition at line 3133 of file ZipEntry.cs.
        {
            CountingStream countingStream = s as CountingStream;
            ZipSegmentedStream zipSegmentedStream = s as ZipSegmentedStream;
            bool flag = false;
            do
            {
                try
                {
                    if (this._Source == ZipEntrySource.ZipFile && !this._restreamRequiredOnSave)
                    {
                        this.CopyThroughOneEntry(s);
                        break;
                    }
                    if (this.IsDirectory)
                    {
                        this.WriteHeader(s, 1);
                        this.StoreRelativeOffset();
                        this._entryRequiresZip64 = new bool?(this._RelativeOffsetOfLocalHeader >= (long)((ulong)(-1)));
                        this._OutputUsesZip64 = new bool?(this._container.Zip64 == Zip64Option.Always || this._entryRequiresZip64.Value);
                        if (zipSegmentedStream != null)
{
                            this._diskNumber = zipSegmentedStream.CurrentSegment;
                        }
                        break;
                    }
                    int num = 0;
                    bool flag2;
                    do
                    {
                        num++;
                        this.WriteHeader(s, num);
                        this.WriteSecurityMetadata(s);
                        this._WriteEntryData(s);
                        this._TotalEntrySize = (long)this._LengthOfHeader + this._CompressedFileDataSize + (long)this._LengthOfTrailer;
                        flag2 = num <= 1 && s.CanSeek && this.WantReadAgain();
                        if (flag2)
{
                            if (zipSegmentedStream != null)
{
                                zipSegmentedStream.TruncateBackward(this._diskNumber, this._RelativeOffsetOfLocalHeader);
                            }
                            else
{
                                s.Seek(this._RelativeOffsetOfLocalHeader, 0);
                            }
                            s.SetLength(s.Position);
                            if (countingStream != null)
{
                                countingStream.Adjust(this._TotalEntrySize);
                            }
                        }
                    }
                    while (flag2);
                    this._skippedDuringSave = false;
                    flag = true;
                }
                catch (Exception ex)
                {
                    ZipErrorAction zipErrorAction = this.ZipErrorAction;
                    int num2 = 0;
                    while (this.ZipErrorAction != ZipErrorAction.Throw)
                    {
                        if (this.ZipErrorAction == ZipErrorAction.Skip || this.ZipErrorAction == ZipErrorAction.Retry)
{
                            long num3 = ((countingStream != null) ? countingStream.ComputedPosition : s.Position);
                            long num4 = num3 - this._future_ROLH;
                            if (num4 > 0L)
{
                                s.Seek(num4, 1);
                                long position = s.Position;
                                s.SetLength(s.Position);
                                if (countingStream != null)
{
                                    countingStream.Adjust(num3 - position);
                                }
                            }
                            if (this.ZipErrorAction == ZipErrorAction.Skip)
{
                                this.WriteStatus("Skipping file {0} (exception: {1})", new object[]
{
                                    this.LocalFileName,
                                    ex.ToString()
                                });
                                this._skippedDuringSave = true;
                                flag = true;
                            }
                            else
{
                                this.ZipErrorAction = zipErrorAction;
                            }
                        }
                        else
{
                            if (num2 > 0)
{
                                throw;
                            }
                            if (this.ZipErrorAction == ZipErrorAction.InvokeErrorEvent)
{
                                this.OnZipErrorWhileSaving(ex);
                                if (this._ioOperationCanceled)
{
                                    flag = true;
                                    goto IL_023B;
                                }
                            }
                            num2++;
                            continue;
                        }
                        IL_023B:
                        goto IL_023D;
                    }
                    throw;
                }
                IL_023D:;
            }
            while (!flag);
        }
References Ionic.Zip.ZipEntry._CompressedFileDataSize, Ionic.Zip.ZipEntry._diskNumber, Ionic.Zip.ZipEntry._entryRequiresZip64, Ionic.Zip.ZipEntry._future_ROLH, Ionic.Zip.ZipEntry._ioOperationCanceled, Ionic.Zip.ZipEntry._LengthOfHeader, Ionic.Zip.ZipEntry._LengthOfTrailer, Ionic.Zip.ZipEntry._RelativeOffsetOfLocalHeader, Ionic.Zip.ZipEntry._Source, Ionic.Zip.ZipEntry._TotalEntrySize, Ionic.Zip.ZipEntry._WriteEntryData(), Ionic.Zip.CountingStream.Adjust(), Ionic.Zip.CountingStream.ComputedPosition, Ionic.Zip.ZipEntry.CopyThroughOneEntry(), Ionic.Zip.ZipSegmentedStream.CurrentSegment, Ionic.Zip.ZipEntry.IsDirectory, System.L, Ionic.Zip.ZipEntry.LocalFileName, long, Ionic.Zip.ZipEntry.OnZipErrorWhileSaving(), System.s, System.IO.Stream.Seek(), System.IO.Stream.SetLength(), Ionic.Zip.ZipEntry.StoreRelativeOffset(), System.Exception.ToString(), Ionic.Zip.ZipSegmentedStream.TruncateBackward(), Ionic.Zip.ZipEntry.WantReadAgain(), Ionic.Zip.ZipEntry.WriteHeader(), Ionic.Zip.ZipEntry.WriteSecurityMetadata(), Ionic.Zip.ZipEntry.WriteStatus(), and Ionic.Zip.ZipEntry.ZipErrorAction.
Referenced by Ionic.Zip.ZipFile.Save().