Terraria Decompiled: Ionic.Zip.ZipEntry.HandleUnexpectedDataDescriptor
HandleUnexpectedDataDescriptor()
static void Ionic.Zip.ZipEntry.HandleUnexpectedDataDescriptor (ZipEntry entry) inline static private
Definition at line 1967 of file ZipEntry.cs.
        {
            Stream archiveStream = entry.ArchiveStream;
            uint num = (uint)SharedUtilities.ReadInt(archiveStream);
            if ((ulong)num != (ulong)((long)entry._Crc32))
            {
                archiveStream.Seek(-4L, 1);
                SharedUtilities.Workaround_Ladybug318918(archiveStream);
                return;
            }
            int num2 = SharedUtilities.ReadInt(archiveStream);
            if ((long)num2 != entry._CompressedSize)
            {
                archiveStream.Seek(-8L, 1);
                SharedUtilities.Workaround_Ladybug318918(archiveStream);
                return;
            }
            num2 = SharedUtilities.ReadInt(archiveStream);
            if ((long)num2 == entry._UncompressedSize)
            {
                return;
            }
            archiveStream.Seek(-12L, 1);
            SharedUtilities.Workaround_Ladybug318918(archiveStream);
        }
References Ionic.Zip.ZipEntry._CompressedSize, Ionic.Zip.ZipEntry._Crc32, Ionic.Zip.ZipEntry._UncompressedSize, Ionic.Zip.ZipEntry.ArchiveStream, System.L, Ionic.Zip.SharedUtilities.ReadInt(), System.IO.Stream.Seek(), and Ionic.Zip.SharedUtilities.Workaround_Ladybug318918().
Referenced by Ionic.Zip.ZipEntry.ReadEntry().