Terraria Decompiled: Ionic.Zip.ZipEntry.ConstructExtraField
ConstructExtraField()
byte[] Ionic.Zip.ZipEntry.ConstructExtraField (bool forCentralDirectory) inline private
Definition at line 2308 of file ZipEntry.cs.
        {
            List<byte[]> list = new List<byte[]>();
            if (this._container.Zip64 == Zip64Option.Always || (this._container.Zip64 == Zip64Option.AsNecessary && (!forCentralDirectory || this._entryRequiresZip64.Value)))
            {
                int num = 4 + (forCentralDirectory ? 28 : 16);
                byte[] array = new byte[num];
                int num2 = 0;
                if (this._presumeZip64 || forCentralDirectory)
                {
                    array[num2++] = 1;
                    array[num2++] = 0;
                }
                else
                {
                    array[num2++] = 153;
                    array[num2++] = 153;
                }
                array[num2++] = (byte)(num - 4);
                array[num2++] = 0;
                Array.Copy(BitConverter.GetBytes(this._UncompressedSize), 0, array, num2, 8);
                num2 += 8;
                Array.Copy(BitConverter.GetBytes(this._CompressedSize), 0, array, num2, 8);
                num2 += 8;
                if (forCentralDirectory)
                {
                    Array.Copy(BitConverter.GetBytes(this._RelativeOffsetOfLocalHeader), 0, array, num2, 8);
                    num2 += 8;
                    Array.Copy(BitConverter.GetBytes(0), 0, array, num2, 4);
                }
                list.Add(array);
            }
            if (this._ntfsTimesAreSet && this._emitNtfsTimes)
            {
                byte[] array = new byte[36];
                int num3 = 0;
                array[num3++] = 10;
                array[num3++] = 0;
                array[num3++] = 32;
                array[num3++] = 0;
                num3 += 4;
                array[num3++] = 1;
                array[num3++] = 0;
                array[num3++] = 24;
                array[num3++] = 0;
                long num4 = this._Mtime.ToFileTime();
                Array.Copy(BitConverter.GetBytes(num4), 0, array, num3, 8);
                num3 += 8;
                num4 = this._Atime.ToFileTime();
                Array.Copy(BitConverter.GetBytes(num4), 0, array, num3, 8);
                num3 += 8;
                num4 = this._Ctime.ToFileTime();
                Array.Copy(BitConverter.GetBytes(num4), 0, array, num3, 8);
                num3 += 8;
                list.Add(array);
            }
            if (this._ntfsTimesAreSet && this._emitUnixTimes)
            {
                int num5 = 9;
                if (!forCentralDirectory)
                {
                    num5 += 8;
                }
                byte[] array = new byte[num5];
                int num6 = 0;
                array[num6++] = 85;
                array[num6++] = 84;
                array[num6++] = (byte)(num5 - 4);
                array[num6++] = 0;
                array[num6++] = 7;
                int num7 = (int)(this._Mtime - ZipEntry._unixEpoch).TotalSeconds;
                Array.Copy(BitConverter.GetBytes(num7), 0, array, num6, 4);
                num6 += 4;
                if (!forCentralDirectory)
                {
                    num7 = (int)(this._Atime - ZipEntry._unixEpoch).TotalSeconds;
                    Array.Copy(BitConverter.GetBytes(num7), 0, array, num6, 4);
                    num6 += 4;
                    num7 = (int)(this._Ctime - ZipEntry._unixEpoch).TotalSeconds;
                    Array.Copy(BitConverter.GetBytes(num7), 0, array, num6, 4);
                    num6 += 4;
                }
                list.Add(array);
            }
            byte[] array2 = null;
            if (list.Count > 0)
            {
                int num8 = 0;
                int num9 = 0;
                for (int i = 0; i < list.Count; i++)
                {
                    num8 += list[i].Length;
                }
                array2 = new byte[num8];
                for (int i = 0; i < list.Count; i++)
                {
                    Array.Copy(list[i], 0, array2, num9, list[i].Length);
                    num9 += list[i].Length;
                }
            }
            return array2;
        }
References Ionic.Zip.ZipEntry._Atime, Ionic.Zip.ZipEntry._container, Ionic.Zip.ZipEntry._Ctime, Ionic.Zip.ZipEntry._emitNtfsTimes, Ionic.Zip.ZipEntry._emitUnixTimes, Ionic.Zip.ZipEntry._Mtime, Ionic.Zip.ZipEntry._ntfsTimesAreSet, Ionic.Zip.ZipEntry._presumeZip64, Ionic.Zip.ZipEntry._unixEpoch, System.array, System.Array.Copy(), System.BitConverter.GetBytes(), int, System.list, System.DateTime.ToFileTime(), and Ionic.Zip.ZipContainer.Zip64.
Referenced by Ionic.Zip.ZipEntry.WriteCentralDirectoryEntry(), and Ionic.Zip.ZipEntry.WriteHeader().