Terraria Decompiled: Ionic.Zip.ZipEntry.SetEntryTimes
SetEntryTimes()
void Ionic.Zip.ZipEntry.SetEntryTimes (DateTime created, DateTime accessed, DateTime modified) inline
Definition at line 286 of file ZipEntry.cs.
        {
            this._ntfsTimesAreSet = true;
            if (created == ZipEntry._zeroHour && created.Kind == ZipEntry._zeroHour.Kind)
            {
                created = ZipEntry._win32Epoch;
            }
            if (accessed == ZipEntry._zeroHour && accessed.Kind == ZipEntry._zeroHour.Kind)
            {
                accessed = ZipEntry._win32Epoch;
            }
            if (modified == ZipEntry._zeroHour && modified.Kind == ZipEntry._zeroHour.Kind)
            {
                modified = ZipEntry._win32Epoch;
            }
            this._Ctime = created.ToUniversalTime();
            this._Atime = accessed.ToUniversalTime();
            this._Mtime = modified.ToUniversalTime();
            this._LastModified = this._Mtime;
            if (!this._emitUnixTimes && !this._emitNtfsTimes)
            {
                this._emitNtfsTimes = true;
            }
            this._metadataChanged = true;
        }
References Ionic.Zip.ZipEntry._emitNtfsTimes, Ionic.Zip.ZipEntry._emitUnixTimes, Ionic.Zip.ZipEntry._Mtime, Ionic.Zip.ZipEntry._win32Epoch, Ionic.Zip.ZipEntry._zeroHour, System.DateTime.Kind, and System.DateTime.ToUniversalTime().
Referenced by Ionic.Zip.ZipFile.AddDirectoryByName(), Ionic.Zip.ZipFile.AddEntry(), Ionic.Zip.ZipFile.AddEntry(), and Ionic.Zip.ZipOutputStream.PutNextEntry().