Terraria Decompiled: Ionic.Zip.ZipEntry.ValidateOutput
ValidateOutput()
bool Ionic.Zip.ZipEntry.ValidateOutput (string basedir, Stream outstream, out string outFileName) inline private
Definition at line 1701 of file ZipEntry.cs.
        {
            if (basedir != null)
            {
                string text = this.FileName.Replace("\\", "/");
                if (text.IndexOf(':') == 1)
                {
                    text = text.Substring(2);
                }
                if (text.StartsWith("/"))
                {
                    text = text.Substring(1);
                }
                if (this._container.ZipFile.FlattenFoldersOnExtract)
                {
                    outFileName = Path.Combine(basedir, (text.IndexOf('/') != -1) ? Path.GetFileName(text) : text);
                }
                else
                {
                    outFileName = Path.Combine(basedir, text);
                }
                outFileName = outFileName.Replace("/", "\\");
                if (this.IsDirectory || this.FileName.EndsWith("/"))
                {
                    if (!Directory.Exists(outFileName))
                    {
                        Directory.CreateDirectory(outFileName);
                        this._SetTimes(outFileName, false);
                    }
                    else if (this.ExtractExistingFile == ExtractExistingFileAction.OverwriteSilently)
                    {
                        this._SetTimes(outFileName, false);
                    }
                    return true;
                }
                return false;
            }
            else
            {
                if (outstream != null)
                {
                    outFileName = null;
                    return this.IsDirectory || this.FileName.EndsWith("/");
                }
                throw new ArgumentNullException("outstream");
            }
        }
References Ionic.Zip.ZipEntry._container, Ionic.Zip.ZipEntry._SetTimes(), System.IO.Path.Combine(), System.IO.Directory.CreateDirectory(), System.IO.Directory.Exists(), Ionic.Zip.ZipEntry.ExtractExistingFile, Ionic.Zip.ZipEntry.FileName, Ionic.Zip.ZipFile.FlattenFoldersOnExtract, System.IO.Path.GetFileName(), Ionic.Zip.ZipEntry.IsDirectory, System.text, and Ionic.Zip.ZipContainer.ZipFile.
Referenced by Ionic.Zip.ZipEntry.InternalExtract().