Terraria Decompiled: Ionic.Zip.ZipEntry.CopyThroughWithRecompute
CopyThroughWithRecompute()
void Ionic.Zip.ZipEntry.CopyThroughWithRecompute (Stream outstream) inline private
Definition at line 3329 of file ZipEntry.cs.
        {
            byte[] array = new byte[this.BufferSize];
            CountingStream countingStream = new CountingStream(this.ArchiveStream);
            long relativeOffsetOfLocalHeader = this._RelativeOffsetOfLocalHeader;
            int lengthOfHeader = this.LengthOfHeader;
            this.WriteHeader(outstream, 0);
            this.StoreRelativeOffset();
            if (!this.FileName.EndsWith("/"))
            {
                long num = relativeOffsetOfLocalHeader + (long)lengthOfHeader;
                int num2 = ZipEntry.GetLengthOfCryptoHeaderBytes(this._Encryption_FromZipFile);
                num -= (long)num2;
                this._LengthOfHeader += num2;
                countingStream.Seek(num, 0);
                long num3 = this._CompressedSize;
                while (num3 > 0L)
                {
                    num2 = ((num3 > (long)array.Length) ? array.Length : ((int)num3));
                    int num4 = countingStream.Read(array, 0, num2);
                    outstream.Write(array, 0, num4);
                    num3 -= (long)num4;
                    this.OnWriteBlock(countingStream.BytesRead, this._CompressedSize);
                    if (this._ioOperationCanceled)
                    {
                        break;
                    }
                }
                if ((this._BitField & 8) == 8)
                {
                    int num5 = 16;
                    if (this._InputUsesZip64)
                    {
                        num5 += 8;
                    }
                    byte[] array2 = new byte[num5];
                    countingStream.Read(array2, 0, num5);
                    if (this._InputUsesZip64 && this._container.UseZip64WhenSaving == Zip64Option.Default)
                    {
                        outstream.Write(array2, 0, 8);
                        if (this._CompressedSize > (long)((ulong)(-1)))
{
                            throw new InvalidOperationException("ZIP64 is required");
                        }
                        outstream.Write(array2, 8, 4);
                        if (this._UncompressedSize > (long)((ulong)(-1)))
{
                            throw new InvalidOperationException("ZIP64 is required");
                        }
                        outstream.Write(array2, 16, 4);
                        this._LengthOfTrailer -= 8;
                    }
                    else if (!this._InputUsesZip64 && this._container.UseZip64WhenSaving == Zip64Option.Always)
                    {
                        byte[] array3 = new byte[4];
                        outstream.Write(array2, 0, 8);
                        outstream.Write(array2, 8, 4);
                        outstream.Write(array3, 0, 4);
                        outstream.Write(array2, 12, 4);
                        outstream.Write(array3, 0, 4);
                        this._LengthOfTrailer += 8;
                    }
                    else
                    {
                        outstream.Write(array2, 0, num5);
                    }
                }
            }
            this._TotalEntrySize = (long)this._LengthOfHeader + this._CompressedFileDataSize + (long)this._LengthOfTrailer;
        }
References Ionic.Zip.ZipEntry._BitField, Ionic.Zip.ZipEntry._CompressedFileDataSize, Ionic.Zip.ZipEntry._CompressedSize, Ionic.Zip.ZipEntry._container, Ionic.Zip.ZipEntry._Encryption_FromZipFile, Ionic.Zip.ZipEntry._InputUsesZip64, Ionic.Zip.ZipEntry._ioOperationCanceled, Ionic.Zip.ZipEntry._LengthOfHeader, Ionic.Zip.ZipEntry._LengthOfTrailer, Ionic.Zip.ZipEntry._RelativeOffsetOfLocalHeader, Ionic.Zip.ZipEntry._UncompressedSize, Ionic.Zip.ZipEntry.ArchiveStream, System.array, Ionic.Zip.ZipEntry.BufferSize, Ionic.Zip.CountingStream.BytesRead, Ionic.Zip.ZipEntry.FileName, Ionic.Zip.ZipEntry.GetLengthOfCryptoHeaderBytes(), int, System.L, Ionic.Zip.ZipEntry.LengthOfHeader, long, Ionic.Zip.ZipEntry.OnWriteBlock(), Ionic.Zip.CountingStream.Read(), Ionic.Zip.CountingStream.Seek(), Ionic.Zip.ZipEntry.StoreRelativeOffset(), Ionic.Zip.ZipContainer.UseZip64WhenSaving, System.IO.Stream.Write(), and Ionic.Zip.ZipEntry.WriteHeader().
Referenced by Ionic.Zip.ZipEntry.CopyThroughOneEntry().