Terraria Decompiled: Ionic.Zip.ZipEntry.MarkAsDirectory
MarkAsDirectory()
void Ionic.Zip.ZipEntry.MarkAsDirectory () inline package
Definition at line 956 of file ZipEntry.cs.
        {
            this._IsDirectory = true;
            if (!this._FileNameInArchive.EndsWith("/"))
            {
                this._FileNameInArchive += "/";
            }
        }
References Ionic.Zip.ZipEntry._FileNameInArchive.
Referenced by Ionic.Zip.ZipFile.AddDirectoryByName(), Ionic.Zip.ZipFile.AddOrUpdateDirectoryImpl(), Ionic.Zip.ZipOutputStream.PutNextEntry(), Ionic.Zip.ZipEntry.ReadDirEntry(), Ionic.Zip.ZipEntry.ReadHeader(), and Ionic.Zip.ZipFile.ReadIntoInstance_Orig().