Terraria Decompiled: Ionic.Zip.ZipEntry.ProcessExtraFieldZip64
ProcessExtraFieldZip64()
int Ionic.Zip.ZipEntry.ProcessExtraFieldZip64 (byte[] buffer, int j, short dataSize, long posn) inline private
Definition at line 2080 of file ZipEntry.cs.
        {
            ZipEntry.<>c__DisplayClass1 <>c__DisplayClass = new ZipEntry.<>c__DisplayClass1();
            <>c__DisplayClass.buffer = buffer;
            <>c__DisplayClass.j = j;
            <>c__DisplayClass.posn = posn;
            this._InputUsesZip64 = true;
            if (dataSize > 28)
            {
                throw new BadReadException(string.Format("  Inconsistent size (0x{0:X4}) for ZIP64 extra field at position 0x{1:X16}", dataSize, <>c__DisplayClass.posn));
            }
            <>c__DisplayClass.remainingData = (int)dataSize;
            ZipEntry.Func<long> func = new ZipEntry.Func<long>(<>c__DisplayClass.<ProcessExtraFieldZip64>b__0);
            if (this._UncompressedSize == (long)((ulong)(-1)))
            {
                this._UncompressedSize = func();
            }
            if (this._CompressedSize == (long)((ulong)(-1)))
            {
                this._CompressedSize = func();
            }
            if (this._RelativeOffsetOfLocalHeader == (long)((ulong)(-1)))
            {
                this._RelativeOffsetOfLocalHeader = func();
            }
            return <>c__DisplayClass.j;
        }
References Ionic.Zip.ZipEntry._CompressedSize, Ionic.Zip.ZipEntry._RelativeOffsetOfLocalHeader, Ionic.Zip.ZipEntry._UncompressedSize, System.Format, int, and Ionic.Zip.ZipEntry.ProcessExtraFieldZip64().
Referenced by Ionic.Zip.ZipEntry.ProcessExtraField(), and Ionic.Zip.ZipEntry.ProcessExtraFieldZip64().