Terraria Decompiled: Ionic.Zip.ZipEntry.WriteHeader
WriteHeader()
void Ionic.Zip.ZipEntry.WriteHeader (Stream s, int cycle) inline package
Definition at line 2543 of file ZipEntry.cs.
        {
            CountingStream countingStream = s as CountingStream;
            this._future_ROLH = ((countingStream != null) ? countingStream.ComputedPosition : s.Position);
            int num = 0;
            byte[] array = new byte[30];
            array[num++] = 80;
            array[num++] = 75;
            array[num++] = 3;
            array[num++] = 4;
            this._presumeZip64 = this._container.Zip64 == Zip64Option.Always || (this._container.Zip64 == Zip64Option.AsNecessary && !s.CanSeek);
            short num2 = (this._presumeZip64 ? 45 : 20);
            if (this.CompressionMethod == CompressionMethod.BZip2)
            {
                num2 = 46;
            }
            array[num++] = (byte)(num2 & 255);
            array[num++] = (byte)(((int)num2 & 65280) >> 8);
            byte[] encodedFileNameBytes = this.GetEncodedFileNameBytes();
            short num3 = (short)encodedFileNameBytes.Length;
            if (this._Encryption == EncryptionAlgorithm.None)
            {
                this._BitField &= -2;
            }
            else
            {
                this._BitField |= 1;
            }
            if (this._actualEncoding.CodePage == Encoding.UTF8.CodePage)
            {
                this._BitField |= 2048;
            }
            if (this.IsDirectory || cycle == 99)
            {
                this._BitField &= -9;
                this._BitField &= -2;
                this.Encryption = EncryptionAlgorithm.None;
                this.Password = null;
            }
            else if (!s.CanSeek)
            {
                this._BitField |= 8;
            }
            array[num++] = (byte)(this._BitField & 255);
            array[num++] = (byte)(((int)this._BitField & 65280) >> 8);
            if (this.__FileDataPosition == -1L)
            {
                this._CompressedSize = 0L;
                this._crcCalculated = false;
            }
            this.MaybeUnsetCompressionMethodForWriting(cycle);
            array[num++] = (byte)(this._CompressionMethod & 255);
            array[num++] = (byte)(((int)this._CompressionMethod & 65280) >> 8);
            if (cycle == 99)
            {
                this.SetZip64Flags();
            }
            this._TimeBlob = SharedUtilities.DateTimeToPacked(this.LastModified);
            array[num++] = (byte)(this._TimeBlob & 255);
            array[num++] = (byte)((this._TimeBlob & 65280) >> 8);
            array[num++] = (byte)((this._TimeBlob & 16711680) >> 16);
            array[num++] = (byte)(((long)this._TimeBlob & (long)((ulong)(-16777216))) >> 24);
            array[num++] = (byte)(this._Crc32 & 255);
            array[num++] = (byte)((this._Crc32 & 65280) >> 8);
            array[num++] = (byte)((this._Crc32 & 16711680) >> 16);
            array[num++] = (byte)(((long)this._Crc32 & (long)((ulong)(-16777216))) >> 24);
            if (this._presumeZip64)
            {
                for (int i = 0; i < 8; i++)
                {
                    array[num++] = byte.MaxValue;
                }
            }
            else
            {
                array[num++] = (byte)(this._CompressedSize & 255L);
                array[num++] = (byte)((this._CompressedSize & 65280L) >> 8);
                array[num++] = (byte)((this._CompressedSize & 16711680L) >> 16);
                array[num++] = (byte)((this._CompressedSize & (long)((ulong)(-16777216))) >> 24);
                array[num++] = (byte)(this._UncompressedSize & 255L);
                array[num++] = (byte)((this._UncompressedSize & 65280L) >> 8);
                array[num++] = (byte)((this._UncompressedSize & 16711680L) >> 16);
                array[num++] = (byte)((this._UncompressedSize & (long)((ulong)(-16777216))) >> 24);
            }
            array[num++] = (byte)(num3 & 255);
            array[num++] = (byte)(((int)num3 & 65280) >> 8);
            this._Extra = this.ConstructExtraField(false);
            short num4 = (short)((this._Extra == null) ? 0 : this._Extra.Length);
            array[num++] = (byte)(num4 & 255);
            array[num++] = (byte)(((int)num4 & 65280) >> 8);
            byte[] array2 = new byte[num + (int)num3 + (int)num4];
            Buffer.BlockCopy(array, 0, array2, 0, num);
            Buffer.BlockCopy(encodedFileNameBytes, 0, array2, num, encodedFileNameBytes.Length);
            num += encodedFileNameBytes.Length;
            if (this._Extra != null)
            {
                Buffer.BlockCopy(this._Extra, 0, array2, num, this._Extra.Length);
                num += this._Extra.Length;
            }
            this._LengthOfHeader = num;
            ZipSegmentedStream zipSegmentedStream = s as ZipSegmentedStream;
            if (zipSegmentedStream != null)
            {
                zipSegmentedStream.ContiguousWrite = true;
                uint num5 = zipSegmentedStream.ComputeSegment(num);
                if (num5 != zipSegmentedStream.CurrentSegment)
                {
                    this._future_ROLH = 0L;
                }
                else
                {
                    this._future_ROLH = zipSegmentedStream.Position;
                }
                this._diskNumber = num5;
            }
            if (this._container.Zip64 == Zip64Option.Default && (uint)this._RelativeOffsetOfLocalHeader >= 4294967295U)
            {
                throw new ZipException("Offset within the zip archive exceeds 0xFFFFFFFF. Consider setting the UseZip64WhenSaving property on the ZipFile instance.");
            }
            s.Write(array2, 0, num);
            if (zipSegmentedStream != null)
            {
                zipSegmentedStream.ContiguousWrite = false;
            }
            this._EntryHeader = array2;
        }
References Ionic.Zip.ZipEntry.__FileDataPosition, Ionic.Zip.ZipEntry._actualEncoding, Ionic.Zip.ZipEntry._BitField, Ionic.Zip.ZipEntry._CompressedSize, Ionic.Zip.ZipEntry._CompressionMethod, Ionic.Zip.ZipEntry._container, Ionic.Zip.ZipEntry._Crc32, Ionic.Zip.ZipEntry._Encryption, Ionic.Zip.ZipEntry._Extra, Ionic.Zip.ZipEntry._presumeZip64, Ionic.Zip.ZipEntry._TimeBlob, Ionic.Zip.ZipEntry._UncompressedSize, System.array, System.Buffer.BlockCopy(), System.Text.Encoding.CodePage, Ionic.Zip.CountingStream.ComputedPosition, Ionic.Zip.ZipSegmentedStream.ComputeSegment(), Ionic.Zip.ZipEntry.ConstructExtraField(), Ionic.Zip.ZipSegmentedStream.CurrentSegment, Ionic.Zip.SharedUtilities.DateTimeToPacked(), Ionic.Zip.ZipEntry.GetEncodedFileNameBytes(), int, Ionic.Zip.ZipEntry.IsDirectory, System.L, Ionic.Zip.ZipEntry.LastModified, long, Ionic.Zip.ZipEntry.MaybeUnsetCompressionMethodForWriting(), Ionic.Zip.ZipSegmentedStream.Position, System.s, Ionic.Zip.ZipEntry.SetZip64Flags(), System.U, System.Text.Encoding.UTF8, and Ionic.Zip.ZipContainer.Zip64.
Referenced by Ionic.Zip.ZipOutputStream._InitiateCurrentEntry(), Ionic.Zip.ZipEntry.CopyThroughWithRecompute(), and Ionic.Zip.ZipEntry.Write().