Terraria Decompiled: Ionic.Zip.ZipEntry.CheckExtractExistingFile
CheckExtractExistingFile()
int Ionic.Zip.ZipEntry.CheckExtractExistingFile (string baseDir, string targetFileName) inline private
Definition at line 1384 of file ZipEntry.cs.
        {
            int num = 0;
            for (;;)
            {
                switch (this.ExtractExistingFile)
                {
                case ExtractExistingFileAction.OverwriteSilently:
                    goto IL_0021;
                case ExtractExistingFileAction.DoNotOverwrite:
                    goto IL_003A;
                case ExtractExistingFileAction.InvokeExtractProgressEvent:
                    if (num > 0)
                    {
                        goto Block_2;
                    }
                    this.OnExtractExisting(baseDir);
                    if (this._ioOperationCanceled)
                    {
                        return 2;
                    }
                    num++;
                    continue;
                }
                break;
            }
            goto IL_0085;
            IL_0021:
            this.WriteStatus("the file {0} exists; will overwrite it...", new object[] { targetFileName });
            return 0;
            IL_003A:
            this.WriteStatus("the file {0} exists; not extracting entry...", new object[] { this.FileName });
            this.OnAfterExtract(baseDir);
            return 1;
            Block_2:
            throw new ZipException(string.Format("The file {0} already exists.", targetFileName));
            IL_0085:
            throw new ZipException(string.Format("The file {0} already exists.", targetFileName));
        }
References Ionic.Zip.ZipEntry._ioOperationCanceled, Ionic.Zip.ZipEntry.ExtractExistingFile, System.Format, Ionic.Zip.ZipEntry.OnAfterExtract(), Ionic.Zip.ZipEntry.OnExtractExisting(), and Ionic.Zip.ZipEntry.WriteStatus().
Referenced by Ionic.Zip.ZipEntry.InternalExtract().