Terraria Decompiled: Ionic.Zip.ZipEntry.InternalOpenReader
InternalOpenReader()
CrcCalculatorStream Ionic.Zip.ZipEntry.InternalOpenReader (string password) inline package
Definition at line 1162 of file ZipEntry.cs.
        {
            this.ValidateCompression();
            this.ValidateEncryption();
            this.SetupCryptoForExtract(password);
            if (this._Source != ZipEntrySource.ZipFile)
            {
                throw new BadStateException("You must call ZipFile.Save before calling OpenReader");
            }
            long num = ((this._CompressionMethod_FromZipFile == 0) ? this._CompressedFileDataSize : this.UncompressedSize);
            Stream archiveStream = this.ArchiveStream;
            this.ArchiveStream.Seek(this.FileDataPosition, 0);
            SharedUtilities.Workaround_Ladybug318918(this.ArchiveStream);
            this._inputDecryptorStream = this.GetExtractDecryptor(archiveStream);
            Stream extractDecompressor = this.GetExtractDecompressor(this._inputDecryptorStream);
            return new CrcCalculatorStream(extractDecompressor, num);
        }
References Ionic.Zip.ZipEntry._CompressedFileDataSize, Ionic.Zip.ZipEntry._inputDecryptorStream, Ionic.Zip.ZipEntry._Source, Ionic.Zip.ZipEntry.ArchiveStream, Ionic.Zip.ZipEntry.FileDataPosition, Ionic.Zip.ZipEntry.GetExtractDecompressor(), Ionic.Zip.ZipEntry.GetExtractDecryptor(), System.IO.Stream.Seek(), Ionic.Zip.ZipEntry.SetupCryptoForExtract(), Ionic.Zip.ZipEntry.UncompressedSize, Ionic.Zip.ZipEntry.ValidateCompression(), Ionic.Zip.ZipEntry.ValidateEncryption(), and Ionic.Zip.SharedUtilities.Workaround_Ladybug318918().
Referenced by Ionic.Zip.ZipEntry.OpenReader(), Ionic.Zip.ZipEntry.OpenReader(), Ionic.Zip.ZipEntry.SetInputAndFigureFileLength(), and Ionic.Zip.ZipInputStream.SetupStream().