Terraria Decompiled: Ionic.Zip.ZipEntry.ReadExtraField
ReadExtraField()
void Ionic.Zip.ZipEntry.ReadExtraField () inline private
Definition at line 1750 of file ZipEntry.cs.
        {
            this._readExtraDepth++;
            long position = this.ArchiveStream.Position;
            this.ArchiveStream.Seek(this._RelativeOffsetOfLocalHeader, 0);
            SharedUtilities.Workaround_Ladybug318918(this.ArchiveStream);
            byte[] array = new byte[30];
            this.ArchiveStream.Read(array, 0, array.Length);
            int num = 26;
            short num2 = (short)((int)array[num++] + (int)array[num++] * 256);
            short num3 = (short)((int)array[num++] + (int)array[num++] * 256);
            this.ArchiveStream.Seek((long)num2, 1);
            SharedUtilities.Workaround_Ladybug318918(this.ArchiveStream);
            this.ProcessExtraField(this.ArchiveStream, num3);
            this.ArchiveStream.Seek(position, 0);
            SharedUtilities.Workaround_Ladybug318918(this.ArchiveStream);
            this._readExtraDepth--;
        }
References Ionic.Zip.ZipEntry._readExtraDepth, Ionic.Zip.ZipEntry._RelativeOffsetOfLocalHeader, Ionic.Zip.ZipEntry.ArchiveStream, System.array, int, System.IO.Stream.Position, Ionic.Zip.ZipEntry.ProcessExtraField(), System.IO.Stream.Read(), System.IO.Stream.Seek(), and Ionic.Zip.SharedUtilities.Workaround_Ladybug318918().
Referenced by Ionic.Zip.ZipEntry.ProcessExtraFieldUnixTimes().