Terraria Decompiled: Ionic.Zip.ZipEntry.SetupCryptoForExtract
SetupCryptoForExtract()
void Ionic.Zip.ZipEntry.SetupCryptoForExtract (string password) inline private
Definition at line 1682 of file ZipEntry.cs.
        {
            if (this._Encryption_FromZipFile == EncryptionAlgorithm.None)
            {
                return;
            }
            if (this._Encryption_FromZipFile == EncryptionAlgorithm.PkzipWeak)
            {
                if (password == null)
                {
                    throw new ZipException("Missing password.");
                }
                this.ArchiveStream.Seek(this.FileDataPosition - 12L, 0);
                SharedUtilities.Workaround_Ladybug318918(this.ArchiveStream);
                this._zipCrypto_forExtract = ZipCrypto.ForRead(password, this);
            }
        }
References Ionic.Zip.ZipEntry._Encryption_FromZipFile, Ionic.Zip.ZipEntry.ArchiveStream, Ionic.Zip.ZipEntry.FileDataPosition, Ionic.Zip.ZipCrypto.ForRead(), System.L, System.IO.Stream.Seek(), and Ionic.Zip.SharedUtilities.Workaround_Ladybug318918().
Referenced by Ionic.Zip.ZipEntry.InternalExtract(), and Ionic.Zip.ZipEntry.InternalOpenReader().