Terraria Decompiled: Ionic.Zip.ZipEntry.ProcessExtraField
ProcessExtraField()
int Ionic.Zip.ZipEntry.ProcessExtraField (Stream s, short extraFieldLength) inline package
Definition at line 2011 of file ZipEntry.cs.
        {
            int num = 0;
            if (extraFieldLength > 0)
            {
                byte[] array = (this._Extra = new byte[(int)extraFieldLength]);
                num = s.Read(array, 0, array.Length);
                long num2 = s.Position - (long)num;
                int num3 = 0;
                while (num3 + 3 < array.Length)
                {
                    int num4 = num3;
                    ushort num5 = (ushort)((int)array[num3++] + (int)array[num3++] * 256);
                    short num6 = (short)((int)array[num3++] + (int)array[num3++] * 256);
                    ushort num7 = num5;
                    if (num7 <= 23)
                    {
                        if (num7 != 1)
{
                            if (num7 != 10)
{
                                if (num7 == 23)
{
                                    num3 = this.ProcessExtraFieldPkwareStrongEncryption(array, num3);
                                }
                            }
                            else
{
                                num3 = this.ProcessExtraFieldWindowsTimes(array, num3, num6, num2);
                            }
                        }
                        else
{
                            num3 = this.ProcessExtraFieldZip64(array, num3, num6, num2);
                        }
                    }
                    else if (num7 <= 22613)
                    {
                        if (num7 != 21589)
{
                            if (num7 == 22613)
{
                                num3 = this.ProcessExtraFieldInfoZipTimes(array, num3, num6, num2);
                            }
                        }
                        else
{
                            num3 = this.ProcessExtraFieldUnixTimes(array, num3, num6, num2);
                        }
                    }
                    else if (num7 != 30805 && num7 != 30837)
                    {
                    }
                    num3 = num4 + (int)num6 + 4;
                }
            }
            return num;
        }
References System.array, int, long, Ionic.Zip.ZipEntry.ProcessExtraFieldInfoZipTimes(), Ionic.Zip.ZipEntry.ProcessExtraFieldPkwareStrongEncryption(), Ionic.Zip.ZipEntry.ProcessExtraFieldUnixTimes(), Ionic.Zip.ZipEntry.ProcessExtraFieldWindowsTimes(), Ionic.Zip.ZipEntry.ProcessExtraFieldZip64(), and System.s.
Referenced by Ionic.Zip.ZipEntry.ReadDirEntry(), Ionic.Zip.ZipEntry.ReadExtraField(), and Ionic.Zip.ZipEntry.ReadHeader().