Terraria Decompiled: Ionic.Zip.ZipEntry.Create
Create()
static ZipEntry Ionic.Zip.ZipEntry.Create (string nameInArchive, ZipEntrySource source, object arg1, object arg2) inline static private
Definition at line 895 of file ZipEntry.cs.
        {
            if (string.IsNullOrEmpty(nameInArchive))
            {
                throw new ZipException("The entry name must be non-null and non-empty.");
            }
            ZipEntry zipEntry = new ZipEntry();
            zipEntry._VersionMadeBy = 45;
            zipEntry._Source = source;
            zipEntry._Mtime = (zipEntry._Atime = (zipEntry._Ctime = DateTime.UtcNow));
            if (source == ZipEntrySource.Stream)
            {
                zipEntry._sourceStream = arg1 as Stream;
            }
            else if (source == ZipEntrySource.WriteDelegate)
            {
                zipEntry._WriteDelegate = arg1 as WriteDelegate;
            }
            else if (source == ZipEntrySource.JitStream)
            {
                zipEntry._OpenDelegate = arg1 as OpenDelegate;
                zipEntry._CloseDelegate = arg2 as CloseDelegate;
            }
            else if (source != ZipEntrySource.ZipOutputStream)
            {
                if (source == ZipEntrySource.None)
                {
                    zipEntry._Source = ZipEntrySource.FileSystem;
                }
                else
                {
                    string text = arg1 as string;
                    if (string.IsNullOrEmpty(text))
                    {
                        throw new ZipException("The filename must be non-null and non-empty.");
                    }
                    try
                    {
                        zipEntry._Mtime = File.GetLastWriteTime(text).ToUniversalTime();
                        zipEntry._Ctime = File.GetCreationTime(text).ToUniversalTime();
                        zipEntry._Atime = File.GetLastAccessTime(text).ToUniversalTime();
                        if (File.Exists(text) || Directory.Exists(text))
{
                            zipEntry._ExternalFileAttrs = (int)NetCfFile.GetAttributes(text);
                        }
                        zipEntry._ntfsTimesAreSet = true;
                        zipEntry._LocalFileName = Path.GetFullPath(text);
                    }
                    catch (PathTooLongException ex)
                    {
                        string text2 = string.Format("The path is too long, filename={0}", text);
                        throw new ZipException(text2, ex);
                    }
                }
            }
            zipEntry._LastModified = zipEntry._Mtime;
            zipEntry._FileNameInArchive = SharedUtilities.NormalizePathForUseInZipFile(nameInArchive);
            return zipEntry;
        }
References Ionic.Zip.ZipEntry._Mtime, Ionic.Zip.CloseDelegate(), System.IO.Directory.Exists(), System.IO.File.Exists(), Ionic.Zip.NetCfFile.GetAttributes(), System.IO.File.GetCreationTime(), System.IO.Path.GetFullPath(), System.IO.File.GetLastAccessTime(), System.IO.File.GetLastWriteTime(), int, Ionic.Zip.SharedUtilities.NormalizePathForUseInZipFile(), Ionic.Zip.OpenDelegate(), System.source, Ionic.Zip.Stream, System.text, System.DateTime.ToUniversalTime(), System.DateTime.UtcNow, Ionic.Zip.WriteDelegate, and Ionic.Zip.ZipEntry.ZipEntry().
Referenced by Ionic.Zip.ZipEntry.CreateForJitStreamProvider(), Ionic.Zip.ZipEntry.CreateForStream(), Ionic.Zip.ZipEntry.CreateForWriter(), Ionic.Zip.ZipEntry.CreateForZipOutputStream(), Ionic.Zip.ZipEntry.CreateFromFile(), and Ionic.Zip.ZipEntry.CreateFromNothing().