Terraria Decompiled: Ionic.Zip.ZipEntry.ProcessExtraFieldInfoZipTimes
ProcessExtraFieldInfoZipTimes()
int Ionic.Zip.ZipEntry.ProcessExtraFieldInfoZipTimes (byte[] buffer, int j, short dataSize, long posn) inline private
Definition at line 2109 of file ZipEntry.cs.
        {
            if (dataSize != 12 && dataSize != 8)
            {
                throw new BadReadException(string.Format("  Unexpected size (0x{0:X4}) for InfoZip v1 extra field at position 0x{1:X16}", dataSize, posn));
            }
            int num = BitConverter.ToInt32(buffer, j);
            this._Mtime = ZipEntry._unixEpoch.AddSeconds((double)num);
            j += 4;
            num = BitConverter.ToInt32(buffer, j);
            this._Atime = ZipEntry._unixEpoch.AddSeconds((double)num);
            j += 4;
            this._Ctime = DateTime.UtcNow;
            this._ntfsTimesAreSet = true;
            this._timestamp |= ZipEntryTimestamp.InfoZip1;
            return j;
        }
References Ionic.Zip.ZipEntry._unixEpoch, System.DateTime.AddSeconds(), System.Format, System.BitConverter.ToInt32(), and System.DateTime.UtcNow.
Referenced by Ionic.Zip.ZipEntry.ProcessExtraField().