Terraria Decompiled: Ionic.Zip.ZipEntry.FinishOutputStream
FinishOutputStream()
void Ionic.Zip.ZipEntry.FinishOutputStream (Stream s, CountingStream entryCounter, Stream encryptor, Stream compressor, CrcCalculatorStream output) inline package
Definition at line 2890 of file ZipEntry.cs.
        {
            if (output == null)
            {
                return;
            }
            output.Close();
            if (compressor is DeflateStream)
            {
                compressor.Close();
            }
            else if (compressor is BZip2OutputStream)
            {
                compressor.Close();
            }
            encryptor.Flush();
            encryptor.Close();
            this._LengthOfTrailer = 0;
            this._UncompressedSize = output.TotalBytesSlurped;
            this._CompressedFileDataSize = entryCounter.BytesWritten;
            this._CompressedSize = this._CompressedFileDataSize;
            this._Crc32 = output.Crc;
            this.StoreRelativeOffset();
        }
References Ionic.Zip.ZipEntry._CompressedFileDataSize, Ionic.Zip.CountingStream.BytesWritten, Ionic.Crc.CrcCalculatorStream.Close(), System.IO.Stream.Close(), Ionic.Crc.CrcCalculatorStream.Crc, System.IO.Stream.Flush(), Ionic.Zip.ZipEntry.StoreRelativeOffset(), and Ionic.Crc.CrcCalculatorStream.TotalBytesSlurped.
Referenced by Ionic.Zip.ZipOutputStream._FinishCurrentEntry(), and Ionic.Zip.ZipEntry._WriteEntryData().