Terraria Decompiled: Ionic.Zip.ZipEntry.SetFdpLoh
SetFdpLoh()
void Ionic.Zip.ZipEntry.SetFdpLoh () inline private
Definition at line 1010 of file ZipEntry.cs.
        {
            long position = this.ArchiveStream.Position;
            try
            {
                this.ArchiveStream.Seek(this._RelativeOffsetOfLocalHeader, 0);
                SharedUtilities.Workaround_Ladybug318918(this.ArchiveStream);
            }
            catch (IOException ex)
            {
                string text = string.Format("Exception seeking  entry({0}) offset(0x{1:X8}) len(0x{2:X8})", this.FileName, this._RelativeOffsetOfLocalHeader, this.ArchiveStream.Length);
                throw new BadStateException(text, ex);
            }
            byte[] array = new byte[30];
            this.ArchiveStream.Read(array, 0, array.Length);
            short num = (short)((int)array[26] + (int)array[27] * 256);
            short num2 = (short)((int)array[28] + (int)array[29] * 256);
            this.ArchiveStream.Seek((long)(num + num2), 1);
            SharedUtilities.Workaround_Ladybug318918(this.ArchiveStream);
            this._LengthOfHeader = (int)(30 + num2 + num) + ZipEntry.GetLengthOfCryptoHeaderBytes(this._Encryption_FromZipFile);
            this.__FileDataPosition = this._RelativeOffsetOfLocalHeader + (long)this._LengthOfHeader;
            this.ArchiveStream.Seek(position, 0);
            SharedUtilities.Workaround_Ladybug318918(this.ArchiveStream);
        }
References Ionic.Zip.ZipEntry._Encryption_FromZipFile, Ionic.Zip.ZipEntry._LengthOfHeader, Ionic.Zip.ZipEntry._RelativeOffsetOfLocalHeader, Ionic.Zip.ZipEntry.ArchiveStream, System.array, Ionic.Zip.ZipEntry.FileName, Ionic.Zip.ZipEntry.GetLengthOfCryptoHeaderBytes(), int, System.IO.Stream.Length, long, System.IO.Stream.Position, System.IO.Stream.Read(), System.IO.Stream.Seek(), System.text, and Ionic.Zip.SharedUtilities.Workaround_Ladybug318918().