Terraria Decompiled: Ionic.Zip.ZipEntry.WriteCentralDirectoryEntry
WriteCentralDirectoryEntry()
void Ionic.Zip.ZipEntry.WriteCentralDirectoryEntry (Stream s) inline package
Definition at line 2191 of file ZipEntry.cs.
        {
            byte[] array = new byte[4096];
            int num = 0;
            array[num++] = 80;
            array[num++] = 75;
            array[num++] = 1;
            array[num++] = 2;
            array[num++] = (byte)(this._VersionMadeBy & 255);
            array[num++] = (byte)(((int)this._VersionMadeBy & 65280) >> 8);
            short num2 = ((this.VersionNeeded != 0) ? this.VersionNeeded : 20);
            if (this._OutputUsesZip64 == null)
            {
                this._OutputUsesZip64 = new bool?(this._container.Zip64 == Zip64Option.Always);
            }
            short num3 = (this._OutputUsesZip64.Value ? 45 : num2);
            if (this.CompressionMethod == CompressionMethod.BZip2)
            {
                num3 = 46;
            }
            array[num++] = (byte)(num3 & 255);
            array[num++] = (byte)(((int)num3 & 65280) >> 8);
            array[num++] = (byte)(this._BitField & 255);
            array[num++] = (byte)(((int)this._BitField & 65280) >> 8);
            array[num++] = (byte)(this._CompressionMethod & 255);
            array[num++] = (byte)(((int)this._CompressionMethod & 65280) >> 8);
            array[num++] = (byte)(this._TimeBlob & 255);
            array[num++] = (byte)((this._TimeBlob & 65280) >> 8);
            array[num++] = (byte)((this._TimeBlob & 16711680) >> 16);
            array[num++] = (byte)(((long)this._TimeBlob & (long)((ulong)(-16777216))) >> 24);
            array[num++] = (byte)(this._Crc32 & 255);
            array[num++] = (byte)((this._Crc32 & 65280) >> 8);
            array[num++] = (byte)((this._Crc32 & 16711680) >> 16);
            array[num++] = (byte)(((long)this._Crc32 & (long)((ulong)(-16777216))) >> 24);
            if (this._OutputUsesZip64.Value)
            {
                for (int i = 0; i < 8; i++)
                {
                    array[num++] = byte.MaxValue;
                }
            }
            else
            {
                array[num++] = (byte)(this._CompressedSize & 255L);
                array[num++] = (byte)((this._CompressedSize & 65280L) >> 8);
                array[num++] = (byte)((this._CompressedSize & 16711680L) >> 16);
                array[num++] = (byte)((this._CompressedSize & (long)((ulong)(-16777216))) >> 24);
                array[num++] = (byte)(this._UncompressedSize & 255L);
                array[num++] = (byte)((this._UncompressedSize & 65280L) >> 8);
                array[num++] = (byte)((this._UncompressedSize & 16711680L) >> 16);
                array[num++] = (byte)((this._UncompressedSize & (long)((ulong)(-16777216))) >> 24);
            }
            byte[] encodedFileNameBytes = this.GetEncodedFileNameBytes();
            short num4 = (short)encodedFileNameBytes.Length;
            array[num++] = (byte)(num4 & 255);
            array[num++] = (byte)(((int)num4 & 65280) >> 8);
            this._presumeZip64 = this._OutputUsesZip64.Value;
            this._Extra = this.ConstructExtraField(true);
            short num5 = (short)((this._Extra == null) ? 0 : this._Extra.Length);
            array[num++] = (byte)(num5 & 255);
            array[num++] = (byte)(((int)num5 & 65280) >> 8);
            int num6 = ((this._CommentBytes == null) ? 0 : this._CommentBytes.Length);
            if (num6 + num > array.Length)
            {
                num6 = array.Length - num;
            }
            array[num++] = (byte)(num6 & 255);
            array[num++] = (byte)((num6 & 65280) >> 8);
            bool flag = this._container.ZipFile != null && this._container.ZipFile.MaxOutputSegmentSize != 0;
            if (flag)
            {
                array[num++] = (byte)(this._diskNumber & 255U);
                array[num++] = (byte)((this._diskNumber & 65280U) >> 8);
            }
            else
            {
                array[num++] = 0;
                array[num++] = 0;
            }
            array[num++] = (this._IsText ? 1 : 0);
            array[num++] = 0;
            array[num++] = (byte)(this._ExternalFileAttrs & 255);
            array[num++] = (byte)((this._ExternalFileAttrs & 65280) >> 8);
            array[num++] = (byte)((this._ExternalFileAttrs & 16711680) >> 16);
            array[num++] = (byte)(((long)this._ExternalFileAttrs & (long)((ulong)(-16777216))) >> 24);
            if (this._RelativeOffsetOfLocalHeader > (long)((ulong)(-1)))
            {
                array[num++] = byte.MaxValue;
                array[num++] = byte.MaxValue;
                array[num++] = byte.MaxValue;
                array[num++] = byte.MaxValue;
            }
            else
            {
                array[num++] = (byte)(this._RelativeOffsetOfLocalHeader & 255L);
                array[num++] = (byte)((this._RelativeOffsetOfLocalHeader & 65280L) >> 8);
                array[num++] = (byte)((this._RelativeOffsetOfLocalHeader & 16711680L) >> 16);
                array[num++] = (byte)((this._RelativeOffsetOfLocalHeader & (long)((ulong)(-16777216))) >> 24);
            }
            Buffer.BlockCopy(encodedFileNameBytes, 0, array, num, (int)num4);
            num += (int)num4;
            if (this._Extra != null)
            {
                byte[] extra = this._Extra;
                int num7 = 0;
                Buffer.BlockCopy(extra, num7, array, num, (int)num5);
                num += (int)num5;
            }
            if (num6 != 0)
            {
                Buffer.BlockCopy(this._CommentBytes, 0, array, num, num6);
                num += num6;
            }
            s.Write(array, 0, num);
        }
References Ionic.Zip.ZipEntry._BitField, Ionic.Zip.ZipEntry._CommentBytes, Ionic.Zip.ZipEntry._CompressedSize, Ionic.Zip.ZipEntry._CompressionMethod, Ionic.Zip.ZipEntry._Crc32, Ionic.Zip.ZipEntry._diskNumber, Ionic.Zip.ZipEntry._ExternalFileAttrs, Ionic.Zip.ZipEntry._Extra, Ionic.Zip.ZipEntry._OutputUsesZip64, Ionic.Zip.ZipEntry._RelativeOffsetOfLocalHeader, Ionic.Zip.ZipEntry._TimeBlob, Ionic.Zip.ZipEntry._UncompressedSize, Ionic.Zip.ZipEntry._VersionMadeBy, System.array, System.Buffer.BlockCopy(), Ionic.Zip.ZipEntry.ConstructExtraField(), Ionic.Zip.ZipEntry.GetEncodedFileNameBytes(), int, System.L, long, System.s, System.U, and Ionic.Zip.ZipEntry.VersionNeeded.
Referenced by Ionic.Zip.ZipOutput.WriteCentralDirectoryStructure().