Terraria Decompiled: Ionic.Zip.ZipEntry.FigureCrc32
FigureCrc32()
int Ionic.Zip.ZipEntry.FigureCrc32 () inline private
Definition at line 2671 of file ZipEntry.cs.
        {
            if (!this._crcCalculated)
            {
                Stream stream = null;
                if (this._Source == ZipEntrySource.WriteDelegate)
                {
                    CrcCalculatorStream crcCalculatorStream = new CrcCalculatorStream(Stream.Null);
                    this._WriteDelegate(this.FileName, crcCalculatorStream);
                    this._Crc32 = crcCalculatorStream.Crc;
                }
                else if (this._Source != ZipEntrySource.ZipFile)
                {
                    if (this._Source == ZipEntrySource.Stream)
                    {
                        this.PrepSourceStream();
                        stream = this._sourceStream;
                    }
                    else if (this._Source == ZipEntrySource.JitStream)
                    {
                        if (this._sourceStream == null)
{
                            this._sourceStream = this._OpenDelegate(this.FileName);
                        }
                        this.PrepSourceStream();
                        stream = this._sourceStream;
                    }
                    else if (this._Source != ZipEntrySource.ZipOutputStream)
                    {
                        stream = File.Open(this.LocalFileName, 3, 1, 3);
                    }
                    CRC32 crc = new CRC32();
                    this._Crc32 = crc.GetCrc32(stream);
                    if (this._sourceStream == null)
                    {
                        stream.Close();
                    }
                }
                this._crcCalculated = true;
            }
            return this._Crc32;
        }
References Ionic.Zip.ZipEntry._Crc32, Ionic.Zip.ZipEntry._crcCalculated, Ionic.Zip.ZipEntry._OpenDelegate, Ionic.Zip.ZipEntry._Source, Ionic.Zip.ZipEntry._sourceStream, Ionic.Zip.ZipEntry._WriteDelegate, System.IO.Stream.Close(), Ionic.Crc.CrcCalculatorStream.Crc, Ionic.Zip.ZipEntry.FileName, Ionic.Crc.CRC32.GetCrc32(), Ionic.Zip.ZipEntry.LocalFileName, System.IO.Stream.Null, System.IO.File.Open(), and Ionic.Zip.ZipEntry.PrepSourceStream().
Referenced by Ionic.Zip.ZipEntry.WriteSecurityMetadata().