Terraria Decompiled: Ionic.Zip.ZipEntry._WriteEntryData
_WriteEntryData()
void Ionic.Zip.ZipEntry._WriteEntryData (Stream s) inline private
Definition at line 2766 of file ZipEntry.cs.
        {
            Stream stream = null;
            long num = -1L;
            try
            {
                num = s.Position;
            }
            catch (Exception)
            {
            }
            try
            {
                long num2 = this.SetInputAndFigureFileLength(ref stream);
                CountingStream countingStream = new CountingStream(s);
                Stream stream2;
                Stream stream3;
                if (num2 != 0L)
                {
                    stream2 = this.MaybeApplyEncryption(countingStream);
                    stream3 = this.MaybeApplyCompression(stream2, num2);
                }
                else
                {
                    stream3 = (stream2 = countingStream);
                }
                CrcCalculatorStream crcCalculatorStream = new CrcCalculatorStream(stream3, true);
                if (this._Source == ZipEntrySource.WriteDelegate)
                {
                    this._WriteDelegate(this.FileName, crcCalculatorStream);
                }
                else
                {
                    byte[] array = new byte[this.BufferSize];
                    int num3;
                    while ((num3 = SharedUtilities.ReadWithRetry(stream, array, 0, array.Length, this.FileName)) != 0)
                    {
                        crcCalculatorStream.Write(array, 0, num3);
                        this.OnWriteBlock(crcCalculatorStream.TotalBytesSlurped, num2);
                        if (this._ioOperationCanceled)
{
                            break;
                        }
                    }
                }
                this.FinishOutputStream(s, countingStream, stream2, stream3, crcCalculatorStream);
            }
            finally
            {
                if (this._Source == ZipEntrySource.JitStream)
                {
                    if (this._CloseDelegate != null)
                    {
                        this._CloseDelegate(this.FileName, stream);
                    }
                }
                else if (stream is FileStream)
                {
                    stream.Close();
                }
            }
            if (this._ioOperationCanceled)
            {
                return;
            }
            this.__FileDataPosition = num;
            this.PostProcessOutput(s);
        }
References Ionic.Zip.ZipEntry._CloseDelegate, Ionic.Zip.ZipEntry._ioOperationCanceled, Ionic.Zip.ZipEntry._Source, Ionic.Zip.ZipEntry._WriteDelegate, System.array, Ionic.Zip.ZipEntry.BufferSize, System.IO.Stream.Close(), Ionic.Zip.ZipEntry.FileName, Ionic.Zip.ZipEntry.FinishOutputStream(), System.L, Ionic.Zip.ZipEntry.MaybeApplyCompression(), Ionic.Zip.ZipEntry.MaybeApplyEncryption(), Ionic.Zip.ZipEntry.OnWriteBlock(), Ionic.Zip.ZipEntry.PostProcessOutput(), Ionic.Zip.SharedUtilities.ReadWithRetry(), System.s, Ionic.Zip.ZipEntry.SetInputAndFigureFileLength(), Ionic.Crc.CrcCalculatorStream.TotalBytesSlurped, and Ionic.Crc.CrcCalculatorStream.Write().
Referenced by Ionic.Zip.ZipEntry.Write().