Terraria Decompiled: Ionic.Zip.ZipEntry.ReadHeader
ReadHeader()
static bool Ionic.Zip.ZipEntry.ReadHeader (ZipEntry ze, Encoding defaultEncoding) inline static private
Definition at line 1770 of file ZipEntry.cs.
        {
            int num = 0;
            ze._RelativeOffsetOfLocalHeader = ze.ArchiveStream.Position;
            int num2 = SharedUtilities.ReadEntrySignature(ze.ArchiveStream);
            num += 4;
            if (ZipEntry.IsNotValidSig(num2))
            {
                ze.ArchiveStream.Seek(-4L, 1);
                SharedUtilities.Workaround_Ladybug318918(ze.ArchiveStream);
                if (ZipEntry.IsNotValidZipDirEntrySig(num2) && (long)num2 != 101010256L)
                {
                    throw new BadReadException(string.Format("  Bad signature (0x{0:X8}) at position  0x{1:X8}", num2, ze.ArchiveStream.Position));
                }
                return false;
            }
            else
            {
                byte[] array = new byte[26];
                int num3 = ze.ArchiveStream.Read(array, 0, array.Length);
                if (num3 != array.Length)
                {
                    return false;
                }
                num += num3;
                int num4 = 0;
                ze._VersionNeeded = (short)((int)array[num4++] + (int)array[num4++] * 256);
                ze._BitField = (short)((int)array[num4++] + (int)array[num4++] * 256);
                ze._CompressionMethod_FromZipFile = (ze._CompressionMethod = (short)((int)array[num4++] + (int)array[num4++] * 256));
                ze._TimeBlob = (int)array[num4++] + (int)array[num4++] * 256 + (int)array[num4++] * 256 * 256 + (int)array[num4++] * 256 * 256 * 256;
                ze._LastModified = SharedUtilities.PackedToDateTime(ze._TimeBlob);
                ze._timestamp |= ZipEntryTimestamp.DOS;
                if ((ze._BitField & 1) == 1)
                {
                    ze._Encryption_FromZipFile = (ze._Encryption = EncryptionAlgorithm.PkzipWeak);
                    ze._sourceIsEncrypted = true;
                }
                ze._Crc32 = (int)array[num4++] + (int)array[num4++] * 256 + (int)array[num4++] * 256 * 256 + (int)array[num4++] * 256 * 256 * 256;
                ze._CompressedSize = (long)((ulong)((int)array[num4++] + (int)array[num4++] * 256 + (int)array[num4++] * 256 * 256 + (int)array[num4++] * 256 * 256 * 256));
                ze._UncompressedSize = (long)((ulong)((int)array[num4++] + (int)array[num4++] * 256 + (int)array[num4++] * 256 * 256 + (int)array[num4++] * 256 * 256 * 256));
                if ((uint)ze._CompressedSize == 4294967295U || (uint)ze._UncompressedSize == 4294967295U)
                {
                    ze._InputUsesZip64 = true;
                }
                short num5 = (short)((int)array[num4++] + (int)array[num4++] * 256);
                short num6 = (short)((int)array[num4++] + (int)array[num4++] * 256);
                array = new byte[(int)num5];
                num3 = ze.ArchiveStream.Read(array, 0, array.Length);
                num += num3;
                if ((ze._BitField & 2048) == 2048)
                {
                    ze.AlternateEncoding = Encoding.UTF8;
                    ze.AlternateEncodingUsage = ZipOption.Always;
                }
                ze._FileNameInArchive = ze.AlternateEncoding.GetString(array, 0, array.Length);
                if (ze._FileNameInArchive.EndsWith("/"))
                {
                    ze.MarkAsDirectory();
                }
                num += ze.ProcessExtraField(ze.ArchiveStream, num6);
                ze._LengthOfTrailer = 0;
                if (!ze._FileNameInArchive.EndsWith("/") && (ze._BitField & 8) == 8)
                {
                    long position = ze.ArchiveStream.Position;
                    bool flag = true;
                    long num7 = 0L;
                    int num8 = 0;
                    while (flag)
                    {
                        num8++;
                        if (ze._container.ZipFile != null)
{
                            ze._container.ZipFile.OnReadBytes(ze);
                        }
                        long num9 = SharedUtilities.FindSignature(ze.ArchiveStream, 134695760);
                        if (num9 == -1L)
{
                            return false;
                        }
                        num7 += num9;
                        if (ze._InputUsesZip64)
{
                            array = new byte[20];
                            num3 = ze.ArchiveStream.Read(array, 0, array.Length);
                            if (num3 != 20)
{
                                return false;
                            }
                            num4 = 0;
                            ze._Crc32 = (int)array[num4++] + (int)array[num4++] * 256 + (int)array[num4++] * 256 * 256 + (int)array[num4++] * 256 * 256 * 256;
                            ze._CompressedSize = BitConverter.ToInt64(array, num4);
                            num4 += 8;
                            ze._UncompressedSize = BitConverter.ToInt64(array, num4);
                            num4 += 8;
                            ze._LengthOfTrailer += 24;
                        }
                        else
{
                            array = new byte[12];
                            num3 = ze.ArchiveStream.Read(array, 0, array.Length);
                            if (num3 != 12)
{
                                return false;
                            }
                            num4 = 0;
                            ze._Crc32 = (int)array[num4++] + (int)array[num4++] * 256 + (int)array[num4++] * 256 * 256 + (int)array[num4++] * 256 * 256 * 256;
                            ze._CompressedSize = (long)((ulong)((int)array[num4++] + (int)array[num4++] * 256 + (int)array[num4++] * 256 * 256 + (int)array[num4++] * 256 * 256 * 256));
                            ze._UncompressedSize = (long)((ulong)((int)array[num4++] + (int)array[num4++] * 256 + (int)array[num4++] * 256 * 256 + (int)array[num4++] * 256 * 256 * 256));
                            ze._LengthOfTrailer += 16;
                        }
                        flag = num7 != ze._CompressedSize;
                        if (flag)
{
                            ze.ArchiveStream.Seek(-12L, 1);
                            SharedUtilities.Workaround_Ladybug318918(ze.ArchiveStream);
                            num7 += 4L;
                        }
                    }
                    ze.ArchiveStream.Seek(position, 0);
                    SharedUtilities.Workaround_Ladybug318918(ze.ArchiveStream);
                }
                ze._CompressedFileDataSize = ze._CompressedSize;
                if ((ze._BitField & 1) == 1)
                {
                    ze._WeakEncryptionHeader = new byte[12];
                    num += ZipEntry.ReadWeakEncryptionHeader(ze._archiveStream, ze._WeakEncryptionHeader);
                    ze._CompressedFileDataSize -= 12L;
                }
                ze._LengthOfHeader = num;
                ze._TotalEntrySize = (long)ze._LengthOfHeader + ze._CompressedFileDataSize + (long)ze._LengthOfTrailer;
                return true;
            }
        }
References Ionic.Zip.ZipEntry._archiveStream, Ionic.Zip.ZipEntry._BitField, Ionic.Zip.ZipEntry._CompressedFileDataSize, Ionic.Zip.ZipEntry._CompressedSize, Ionic.Zip.ZipEntry._container, Ionic.Zip.ZipEntry._FileNameInArchive, Ionic.Zip.ZipEntry._InputUsesZip64, Ionic.Zip.ZipEntry._LengthOfHeader, Ionic.Zip.ZipEntry._LengthOfTrailer, Ionic.Zip.ZipEntry._TimeBlob, Ionic.Zip.ZipEntry._UncompressedSize, Ionic.Zip.ZipEntry._WeakEncryptionHeader, Ionic.Zip.ZipEntry.AlternateEncoding, Ionic.Zip.ZipEntry.ArchiveStream, System.array, Ionic.Zip.SharedUtilities.FindSignature(), System.Format, System.Text.Encoding.GetString(), int, Ionic.Zip.ZipEntry.IsNotValidSig(), Ionic.Zip.ZipEntry.IsNotValidZipDirEntrySig(), System.L, long, Ionic.Zip.ZipEntry.MarkAsDirectory(), Ionic.Zip.ZipFile.OnReadBytes(), Ionic.Zip.SharedUtilities.PackedToDateTime(), System.IO.Stream.Position, Ionic.Zip.ZipEntry.ProcessExtraField(), System.IO.Stream.Read(), Ionic.Zip.SharedUtilities.ReadEntrySignature(), Ionic.Zip.ZipEntry.ReadWeakEncryptionHeader(), System.IO.Stream.Seek(), System.BitConverter.ToInt64(), System.U, System.Text.Encoding.UTF8, Ionic.Zip.SharedUtilities.Workaround_Ladybug318918(), and Ionic.Zip.ZipContainer.ZipFile.
Referenced by Ionic.Zip.ZipEntry.ReadEntry().