Terraria Decompiled: Ionic.Zip.ZipEntry.ExtractOne
ExtractOne()
int Ionic.Zip.ZipEntry.ExtractOne (Stream output) inline private
Definition at line 1434 of file ZipEntry.cs.
        {
            int num = 0;
            Stream archiveStream = this.ArchiveStream;
            try
            {
                archiveStream.Seek(this.FileDataPosition, 0);
                SharedUtilities.Workaround_Ladybug318918(archiveStream);
                byte[] array = new byte[this.BufferSize];
                long num2 = ((this._CompressionMethod_FromZipFile != 0) ? this.UncompressedSize : this._CompressedFileDataSize);
                this._inputDecryptorStream = this.GetExtractDecryptor(archiveStream);
                Stream extractDecompressor = this.GetExtractDecompressor(this._inputDecryptorStream);
                long num3 = 0L;
                using (CrcCalculatorStream crcCalculatorStream = new CrcCalculatorStream(extractDecompressor))
                {
                    while (num2 > 0L)
                    {
                        int num4 = ((num2 > (long)array.Length) ? array.Length : ((int)num2));
                        int num5 = crcCalculatorStream.Read(array, 0, num4);
                        this._CheckRead(num5);
                        output.Write(array, 0, num5);
                        num2 -= (long)num5;
                        num3 += (long)num5;
                        this.OnExtractProgress(num3, this.UncompressedSize);
                        if (this._ioOperationCanceled)
{
                            break;
                        }
                    }
                    num = crcCalculatorStream.Crc;
                }
            }
            finally
            {
                ZipSegmentedStream zipSegmentedStream = archiveStream as ZipSegmentedStream;
                if (zipSegmentedStream != null)
                {
                    zipSegmentedStream.Close();
                    this._archiveStream = null;
                }
            }
            return num;
        }
References Ionic.Zip.ZipEntry._CheckRead(), Ionic.Zip.ZipEntry._CompressedFileDataSize, Ionic.Zip.ZipEntry._inputDecryptorStream, Ionic.Zip.ZipEntry._ioOperationCanceled, Ionic.Zip.ZipEntry.ArchiveStream, System.array, Ionic.Zip.ZipEntry.BufferSize, System.IO.Stream.Close(), Ionic.Crc.CrcCalculatorStream.Crc, Ionic.Zip.ZipEntry.FileDataPosition, Ionic.Zip.ZipEntry.GetExtractDecompressor(), Ionic.Zip.ZipEntry.GetExtractDecryptor(), int, System.L, long, Ionic.Zip.ZipEntry.OnExtractProgress(), Ionic.Crc.CrcCalculatorStream.Read(), System.IO.Stream.Seek(), Ionic.Zip.ZipEntry.UncompressedSize, Ionic.Zip.SharedUtilities.Workaround_Ladybug318918(), and System.IO.Stream.Write().
Referenced by Ionic.Zip.ZipEntry.InternalExtract().