Terraria Decompiled: Ionic.Zip.ZipEntry.WriteSecurityMetadata
WriteSecurityMetadata()
void Ionic.Zip.ZipEntry.WriteSecurityMetadata (Stream outstream) inline package
Definition at line 3270 of file ZipEntry.cs.
        {
            if (this.Encryption == EncryptionAlgorithm.None)
            {
                return;
            }
            string text = this._Password;
            if (this._Source == ZipEntrySource.ZipFile && text == null)
            {
                text = this._container.Password;
            }
            if (text == null)
            {
                this._zipCrypto_forWrite = null;
                return;
            }
            if (this.Encryption == EncryptionAlgorithm.PkzipWeak)
            {
                this._zipCrypto_forWrite = ZipCrypto.ForWrite(text);
                Random random = new Random();
                byte[] array = new byte[12];
                random.NextBytes(array);
                if ((this._BitField & 8) == 8)
                {
                    this._TimeBlob = SharedUtilities.DateTimeToPacked(this.LastModified);
                    array[11] = (byte)((this._TimeBlob >> 8) & 255);
                }
                else
                {
                    this.FigureCrc32();
                    array[11] = (byte)((this._Crc32 >> 24) & 255);
                }
                byte[] array2 = this._zipCrypto_forWrite.EncryptMessage(array, array.Length);
                outstream.Write(array2, 0, array2.Length);
                this._LengthOfHeader += array2.Length;
            }
        }
References Ionic.Zip.ZipEntry._BitField, Ionic.Zip.ZipEntry._container, Ionic.Zip.ZipEntry._Crc32, Ionic.Zip.ZipEntry._Password, Ionic.Zip.ZipEntry._Source, Ionic.Zip.ZipEntry._TimeBlob, Ionic.Zip.ZipEntry._zipCrypto_forWrite, System.array, Ionic.Zip.SharedUtilities.DateTimeToPacked(), Ionic.Zip.ZipEntry.Encryption, Ionic.Zip.ZipCrypto.EncryptMessage(), Ionic.Zip.ZipEntry.FigureCrc32(), Ionic.Zip.ZipCrypto.ForWrite(), Ionic.Zip.ZipEntry.LastModified, System.Random.NextBytes(), Ionic.Zip.ZipContainer.Password, System.text, and System.IO.Stream.Write().
Referenced by Ionic.Zip.ZipOutputStream._InitiateCurrentEntry(), and Ionic.Zip.ZipEntry.Write().