Terraria Decompiled: Ionic.Zip.ZipEntry.CopyThroughWithNoChange
CopyThroughWithNoChange()
void Ionic.Zip.ZipEntry.CopyThroughWithNoChange (Stream outstream) inline private
Definition at line 3401 of file ZipEntry.cs.
        {
            byte[] array = new byte[this.BufferSize];
            CountingStream countingStream = new CountingStream(this.ArchiveStream);
            countingStream.Seek(this._RelativeOffsetOfLocalHeader, 0);
            if (this._TotalEntrySize == 0L)
            {
                this._TotalEntrySize = (long)this._LengthOfHeader + this._CompressedFileDataSize + (long)this._LengthOfTrailer;
            }
            CountingStream countingStream2 = outstream as CountingStream;
            this._RelativeOffsetOfLocalHeader = ((countingStream2 != null) ? countingStream2.ComputedPosition : outstream.Position);
            long num = this._TotalEntrySize;
            while (num > 0L)
            {
                int num2 = ((num > (long)array.Length) ? array.Length : ((int)num));
                int num3 = countingStream.Read(array, 0, num2);
                outstream.Write(array, 0, num3);
                num -= (long)num3;
                this.OnWriteBlock(countingStream.BytesRead, this._TotalEntrySize);
                if (this._ioOperationCanceled)
                {
                    return;
                }
            }
        }
References Ionic.Zip.ZipEntry._CompressedFileDataSize, Ionic.Zip.ZipEntry._ioOperationCanceled, Ionic.Zip.ZipEntry._LengthOfHeader, Ionic.Zip.ZipEntry._LengthOfTrailer, Ionic.Zip.ZipEntry._RelativeOffsetOfLocalHeader, Ionic.Zip.ZipEntry._TotalEntrySize, Ionic.Zip.ZipEntry.ArchiveStream, System.array, Ionic.Zip.ZipEntry.BufferSize, Ionic.Zip.CountingStream.BytesRead, Ionic.Zip.CountingStream.ComputedPosition, int, System.L, long, Ionic.Zip.ZipEntry.OnWriteBlock(), System.IO.Stream.Position, Ionic.Zip.CountingStream.Read(), Ionic.Zip.CountingStream.Seek(), and System.IO.Stream.Write().
Referenced by Ionic.Zip.ZipEntry.CopyThroughOneEntry().