Terraria Decompiled: Ionic.Zip.ZipEntry.GetEncodedFileNameBytes
GetEncodedFileNameBytes()
byte[] Ionic.Zip.ZipEntry.GetEncodedFileNameBytes () inline private
Definition at line 2441 of file ZipEntry.cs.
        {
            string text = this.NormalizeFileName();
            switch (this.AlternateEncodingUsage)
            {
            case ZipOption.Default:
                if (this._Comment != null && this._Comment.Length != 0)
                {
                    this._CommentBytes = ZipEntry.ibm437.GetBytes(this._Comment);
                }
                this._actualEncoding = ZipEntry.ibm437;
                return ZipEntry.ibm437.GetBytes(text);
            case ZipOption.Always:
                if (this._Comment != null && this._Comment.Length != 0)
                {
                    this._CommentBytes = this.AlternateEncoding.GetBytes(this._Comment);
                }
                this._actualEncoding = this.AlternateEncoding;
                return this.AlternateEncoding.GetBytes(text);
            }
            byte[] array = ZipEntry.ibm437.GetBytes(text);
            string @string = ZipEntry.ibm437.GetString(array, 0, array.Length);
            this._CommentBytes = null;
            if (@string != text)
            {
                array = this.AlternateEncoding.GetBytes(text);
                if (this._Comment != null && this._Comment.Length != 0)
                {
                    this._CommentBytes = this.AlternateEncoding.GetBytes(this._Comment);
                }
                this._actualEncoding = this.AlternateEncoding;
                return array;
            }
            this._actualEncoding = ZipEntry.ibm437;
            if (this._Comment == null || this._Comment.Length == 0)
            {
                return array;
            }
            byte[] bytes = ZipEntry.ibm437.GetBytes(this._Comment);
            string string2 = ZipEntry.ibm437.GetString(bytes, 0, bytes.Length);
            if (string2 != this.Comment)
            {
                array = this.AlternateEncoding.GetBytes(text);
                this._CommentBytes = this.AlternateEncoding.GetBytes(this._Comment);
                this._actualEncoding = this.AlternateEncoding;
                return array;
            }
            this._CommentBytes = bytes;
            return array;
        }
References Ionic.Zip.ZipEntry._Comment, Ionic.Zip.ZipEntry.AlternateEncoding, Ionic.Zip.ZipEntry.AlternateEncodingUsage, System.array, Ionic.Zip.ZipEntry.Comment, System.Text.Encoding.GetBytes(), System.Text.Encoding.GetString(), Ionic.Zip.ZipEntry.ibm437, Ionic.Zip.ZipEntry.NormalizeFileName(), and System.text.
Referenced by Ionic.Zip.ZipEntry.WriteCentralDirectoryEntry(), and Ionic.Zip.ZipEntry.WriteHeader().