Terraria Decompiled: Ionic.Zip.ZipEntry.ReallyDelete
ReallyDelete()
static void Ionic.Zip.ZipEntry.ReallyDelete (string fileName) inline static private
Definition at line 1217 of file ZipEntry.cs.
        {
            if ((NetCfFile.GetAttributes(fileName) & 1U) == 1U)
            {
                NetCfFile.SetAttributes(fileName, 128U);
            }
            File.Delete(fileName);
        }
References System.IO.File.Delete(), Ionic.Zip.NetCfFile.GetAttributes(), Ionic.Zip.NetCfFile.SetAttributes(), and System.U.
Referenced by Ionic.Zip.ZipEntry.InternalExtract().