Terraria Decompiled: Ionic.Zip.ZipEntry.SetInputAndFigureFileLength
SetInputAndFigureFileLength()
long Ionic.Zip.ZipEntry.SetInputAndFigureFileLength (ref Stream input) inline private
Definition at line 2836 of file ZipEntry.cs.
        {
            long num = -1L;
            if (this._Source == ZipEntrySource.Stream)
            {
                this.PrepSourceStream();
                input = this._sourceStream;
                try
                {
                    return this._sourceStream.Length;
                }
                catch (NotSupportedException)
                {
                    return num;
                }
            }
            if (this._Source == ZipEntrySource.ZipFile)
            {
                string text = ((this._Encryption_FromZipFile == EncryptionAlgorithm.None) ? null : (this._Password ?? this._container.Password));
                this._sourceStream = this.InternalOpenReader(text);
                this.PrepSourceStream();
                input = this._sourceStream;
                num = this._sourceStream.Length;
            }
            else
            {
                if (this._Source == ZipEntrySource.JitStream)
                {
                    if (this._sourceStream == null)
                    {
                        this._sourceStream = this._OpenDelegate(this.FileName);
                    }
                    this.PrepSourceStream();
                    input = this._sourceStream;
                    try
                    {
                        return this._sourceStream.Length;
                    }
                    catch (NotSupportedException)
                    {
                        return num;
                    }
                }
                if (this._Source == ZipEntrySource.FileSystem)
                {
                    FileShare fileShare = 3;
                    input = File.Open(this.LocalFileName, 3, 1, fileShare);
                    num = input.Length;
                }
            }
            return num;
        }
References Ionic.Zip.ZipEntry._container, Ionic.Zip.ZipEntry._OpenDelegate, Ionic.Zip.ZipEntry._Source, Ionic.Zip.ZipEntry._sourceStream, Ionic.Zip.ZipEntry.FileName, System.input, Ionic.Zip.ZipEntry.InternalOpenReader(), System.L, System.IO.Stream.Length, Ionic.Zip.ZipEntry.LocalFileName, System.IO.File.Open(), Ionic.Zip.ZipContainer.Password, Ionic.Zip.ZipEntry.PrepSourceStream(), and System.text.
Referenced by Ionic.Zip.ZipEntry._WriteEntryData().