Terraria Decompiled: Ionic.Zip.ZipEntry.ProcessExtraFieldWindowsTimes
ProcessExtraFieldWindowsTimes()
int Ionic.Zip.ZipEntry.ProcessExtraFieldWindowsTimes (byte[] buffer, int j, short dataSize, long posn) inline private
Definition at line 2162 of file ZipEntry.cs.
        {
            if (dataSize != 32)
            {
                throw new BadReadException(string.Format("  Unexpected size (0x{0:X4}) for NTFS times extra field at position 0x{1:X16}", dataSize, posn));
            }
            j += 4;
            short num = (short)((int)buffer[j] + (int)buffer[j + 1] * 256);
            short num2 = (short)((int)buffer[j + 2] + (int)buffer[j + 3] * 256);
            j += 4;
            if (num == 1 && num2 == 24)
            {
                long num3 = BitConverter.ToInt64(buffer, j);
                this._Mtime = DateTime.FromFileTimeUtc(num3);
                j += 8;
                num3 = BitConverter.ToInt64(buffer, j);
                this._Atime = DateTime.FromFileTimeUtc(num3);
                j += 8;
                num3 = BitConverter.ToInt64(buffer, j);
                this._Ctime = DateTime.FromFileTimeUtc(num3);
                j += 8;
                this._ntfsTimesAreSet = true;
                this._timestamp |= ZipEntryTimestamp.Windows;
                this._emitNtfsTimes = true;
            }
            return j;
        }
References System.Format, System.DateTime.FromFileTimeUtc(), int, and System.BitConverter.ToInt64().
Referenced by Ionic.Zip.ZipEntry.ProcessExtraField().