Terraria Decompiled: Ionic.Zip.ZipEntry.ReadDirEntry
ReadDirEntry()
static ZipEntry Ionic.Zip.ZipEntry.ReadDirEntry (ZipFile zf, Dictionary< string, object > previouslySeen) inline static package
Definition at line 77 of file ZipEntry.cs.
        {
            Stream readStream = zf.ReadStream;
            Encoding encoding = ((zf.AlternateEncodingUsage == ZipOption.Always) ? zf.AlternateEncoding : ZipFile.DefaultEncoding);
            int num = SharedUtilities.ReadSignature(readStream);
            if (ZipEntry.IsNotValidZipDirEntrySig(num))
            {
                readStream.Seek(-4L, 1);
                SharedUtilities.Workaround_Ladybug318918(readStream);
                if ((long)num != 101010256L && (long)num != 101075792L && num != 67324752)
                {
                    throw new BadReadException(string.Format("  Bad signature (0x{0:X8}) at position 0x{1:X8}", num, readStream.Position));
                }
                return null;
            }
            else
            {
                int num2 = 46;
                byte[] array = new byte[42];
                int num3 = readStream.Read(array, 0, array.Length);
                if (num3 != array.Length)
                {
                    return null;
                }
                int num4 = 0;
                ZipEntry zipEntry = new ZipEntry();
                zipEntry.AlternateEncoding = encoding;
                zipEntry._Source = ZipEntrySource.ZipFile;
                zipEntry._container = new ZipContainer(zf);
                zipEntry._VersionMadeBy = (short)((int)array[num4++] + (int)array[num4++] * 256);
                zipEntry._VersionNeeded = (short)((int)array[num4++] + (int)array[num4++] * 256);
                zipEntry._BitField = (short)((int)array[num4++] + (int)array[num4++] * 256);
                zipEntry._CompressionMethod = (short)((int)array[num4++] + (int)array[num4++] * 256);
                zipEntry._TimeBlob = (int)array[num4++] + (int)array[num4++] * 256 + (int)array[num4++] * 256 * 256 + (int)array[num4++] * 256 * 256 * 256;
                zipEntry._LastModified = SharedUtilities.PackedToDateTime(zipEntry._TimeBlob);
                zipEntry._timestamp |= ZipEntryTimestamp.DOS;
                zipEntry._Crc32 = (int)array[num4++] + (int)array[num4++] * 256 + (int)array[num4++] * 256 * 256 + (int)array[num4++] * 256 * 256 * 256;
                zipEntry._CompressedSize = (long)((ulong)((int)array[num4++] + (int)array[num4++] * 256 + (int)array[num4++] * 256 * 256 + (int)array[num4++] * 256 * 256 * 256));
                zipEntry._UncompressedSize = (long)((ulong)((int)array[num4++] + (int)array[num4++] * 256 + (int)array[num4++] * 256 * 256 + (int)array[num4++] * 256 * 256 * 256));
                zipEntry._CompressionMethod_FromZipFile = zipEntry._CompressionMethod;
                zipEntry._filenameLength = (short)((int)array[num4++] + (int)array[num4++] * 256);
                zipEntry._extraFieldLength = (short)((int)array[num4++] + (int)array[num4++] * 256);
                zipEntry._commentLength = (short)((int)array[num4++] + (int)array[num4++] * 256);
                zipEntry._diskNumber = (uint)array[num4++] + (uint)array[num4++] * 256U;
                zipEntry._InternalFileAttrs = (short)((int)array[num4++] + (int)array[num4++] * 256);
                zipEntry._ExternalFileAttrs = (int)array[num4++] + (int)array[num4++] * 256 + (int)array[num4++] * 256 * 256 + (int)array[num4++] * 256 * 256 * 256;
                zipEntry._RelativeOffsetOfLocalHeader = (long)((ulong)((int)array[num4++] + (int)array[num4++] * 256 + (int)array[num4++] * 256 * 256 + (int)array[num4++] * 256 * 256 * 256));
                zipEntry.IsText = (zipEntry._InternalFileAttrs & 1) == 1;
                array = new byte[(int)zipEntry._filenameLength];
                num3 = readStream.Read(array, 0, array.Length);
                num2 += num3;
                if ((zipEntry._BitField & 2048) == 2048)
                {
                    zipEntry._FileNameInArchive = SharedUtilities.Utf8StringFromBuffer(array);
                }
                else
                {
                    zipEntry._FileNameInArchive = SharedUtilities.StringFromBuffer(array, encoding);
                }
                while (previouslySeen.ContainsKey(zipEntry._FileNameInArchive))
                {
                    zipEntry._FileNameInArchive = ZipEntry.CopyHelper.AppendCopyToFileName(zipEntry._FileNameInArchive);
                    zipEntry._metadataChanged = true;
                }
                if (zipEntry.AttributesIndicateDirectory)
                {
                    zipEntry.MarkAsDirectory();
                }
                else if (zipEntry._FileNameInArchive.EndsWith("/"))
                {
                    zipEntry.MarkAsDirectory();
                }
                zipEntry._CompressedFileDataSize = zipEntry._CompressedSize;
                if ((zipEntry._BitField & 1) == 1)
                {
                    zipEntry._Encryption_FromZipFile = (zipEntry._Encryption = EncryptionAlgorithm.PkzipWeak);
                    zipEntry._sourceIsEncrypted = true;
                }
                if (zipEntry._extraFieldLength > 0)
                {
                    zipEntry._InputUsesZip64 = zipEntry._CompressedSize == (long)((ulong)(-1)) || zipEntry._UncompressedSize == (long)((ulong)(-1)) || zipEntry._RelativeOffsetOfLocalHeader == (long)((ulong)(-1));
                    num2 += zipEntry.ProcessExtraField(readStream, zipEntry._extraFieldLength);
                    zipEntry._CompressedFileDataSize = zipEntry._CompressedSize;
                }
                if (zipEntry._Encryption == EncryptionAlgorithm.PkzipWeak)
                {
                    zipEntry._CompressedFileDataSize -= 12L;
                }
                if ((zipEntry._BitField & 8) == 8)
                {
                    if (zipEntry._InputUsesZip64)
                    {
                        zipEntry._LengthOfTrailer += 24;
                    }
                    else
                    {
                        zipEntry._LengthOfTrailer += 16;
                    }
                }
                zipEntry.AlternateEncoding = (((zipEntry._BitField & 2048) == 2048) ? Encoding.UTF8 : encoding);
                zipEntry.AlternateEncodingUsage = ZipOption.Always;
                if (zipEntry._commentLength > 0)
                {
                    array = new byte[(int)zipEntry._commentLength];
                    num3 = readStream.Read(array, 0, array.Length);
                    num2 += num3;
                    if ((zipEntry._BitField & 2048) == 2048)
                    {
                        zipEntry._Comment = SharedUtilities.Utf8StringFromBuffer(array);
                    }
                    else
                    {
                        zipEntry._Comment = SharedUtilities.StringFromBuffer(array, encoding);
                    }
                }
                return zipEntry;
            }
        }
References Ionic.Zip.ZipEntry._BitField, Ionic.Zip.ZipEntry._commentLength, Ionic.Zip.ZipEntry._CompressedSize, Ionic.Zip.ZipEntry._CompressionMethod, Ionic.Zip.ZipEntry._Encryption, Ionic.Zip.ZipEntry._extraFieldLength, Ionic.Zip.ZipEntry._FileNameInArchive, Ionic.Zip.ZipEntry._filenameLength, Ionic.Zip.ZipEntry._InputUsesZip64, Ionic.Zip.ZipEntry._TimeBlob, Ionic.Zip.ZipFile.AlternateEncoding, Ionic.Zip.ZipEntry.CopyHelper.AppendCopyToFileName(), System.array, Ionic.Zip.ZipEntry.AttributesIndicateDirectory, System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), Ionic.Zip.ZipFile.DefaultEncoding, System.Format, int, Ionic.Zip.ZipEntry.IsNotValidZipDirEntrySig(), System.L, long, Ionic.Zip.ZipEntry.MarkAsDirectory(), Ionic.Zip.SharedUtilities.PackedToDateTime(), System.IO.Stream.Position, Ionic.Zip.ZipEntry.ProcessExtraField(), System.IO.Stream.Read(), Ionic.Zip.SharedUtilities.ReadSignature(), Ionic.Zip.ZipFile.ReadStream, System.IO.Stream.Seek(), Ionic.Zip.SharedUtilities.StringFromBuffer(), System.U, Ionic.Zip.SharedUtilities.Utf8StringFromBuffer(), Ionic.Zip.SharedUtilities.Workaround_Ladybug318918(), and Ionic.Zip.ZipEntry.ZipEntry().
Referenced by Ionic.Zip.ZipFile.ReadCentralDirectory(), and Ionic.Zip.ZipFile.ReadIntoInstance_Orig().