Terraria Decompiled: Ionic.Zip.ZipEntry.ProcessExtraFieldUnixTimes
ProcessExtraFieldUnixTimes()
int Ionic.Zip.ZipEntry.ProcessExtraFieldUnixTimes (byte[] buffer, int j, short dataSize, long posn) inline private
Definition at line 2128 of file ZipEntry.cs.
        {
            ZipEntry.<>c__DisplayClass4 <>c__DisplayClass = new ZipEntry.<>c__DisplayClass4();
            <>c__DisplayClass.buffer = buffer;
            <>c__DisplayClass.j = j;
            <>c__DisplayClass.<>4__this = this;
            if (dataSize != 13 && dataSize != 9 && dataSize != 5)
            {
                throw new BadReadException(string.Format("  Unexpected size (0x{0:X4}) for Extended Timestamp extra field at position 0x{1:X16}", dataSize, posn));
            }
            <>c__DisplayClass.remainingData = (int)dataSize;
            ZipEntry.Func<DateTime> func = new ZipEntry.Func<DateTime>(<>c__DisplayClass.<ProcessExtraFieldUnixTimes>b__3);
            if (dataSize == 13 || this._readExtraDepth > 0)
            {
                byte b = <>c__DisplayClass.buffer[<>c__DisplayClass.j++];
                <>c__DisplayClass.remainingData--;
                if ((b & 1) != 0 && <>c__DisplayClass.remainingData >= 4)
                {
                    this._Mtime = func();
                }
                this._Atime = (((b & 2) != 0 && <>c__DisplayClass.remainingData >= 4) ? func() : DateTime.UtcNow);
                this._Ctime = (((b & 4) != 0 && <>c__DisplayClass.remainingData >= 4) ? func() : DateTime.UtcNow);
                this._timestamp |= ZipEntryTimestamp.Unix;
                this._ntfsTimesAreSet = true;
                this._emitUnixTimes = true;
            }
            else
            {
                this.ReadExtraField();
            }
            return <>c__DisplayClass.j;
        }
References Ionic.Zip.ZipEntry._readExtraDepth, System.Format, int, Ionic.Zip.ZipEntry.ProcessExtraFieldUnixTimes(), Ionic.Zip.ZipEntry.ReadExtraField(), and System.DateTime.UtcNow.
Referenced by Ionic.Zip.ZipEntry.ProcessExtraField(), and Ionic.Zip.ZipEntry.ProcessExtraFieldUnixTimes().