Terraria Decompiled: Ionic.Zip.ZipEntry.InternalExtract
InternalExtract()
void Ionic.Zip.ZipEntry.InternalExtract (string baseDir, Stream outstream, string password) inline private
Definition at line 1236 of file ZipEntry.cs.
        {
            if (this._container == null)
            {
                throw new BadStateException("This entry is an orphan");
            }
            if (this._container.ZipFile == null)
            {
                throw new InvalidOperationException("Use Extract() only with ZipFile.");
            }
            this._container.ZipFile.Reset(false);
            if (this._Source != ZipEntrySource.ZipFile)
            {
                throw new BadStateException("You must call ZipFile.Save before calling any Extract method");
            }
            this.OnBeforeExtract(baseDir);
            this._ioOperationCanceled = false;
            string text = null;
            Stream stream = null;
            bool flag = false;
            bool flag2 = false;
            try
            {
                this.ValidateCompression();
                this.ValidateEncryption();
                if (this.ValidateOutput(baseDir, outstream, out text))
                {
                    this.WriteStatus("extract dir {0}...", new object[] { text });
                    this.OnAfterExtract(baseDir);
                }
                else
                {
                    if (text != null && File.Exists(text))
                    {
                        flag = true;
                        int num = this.CheckExtractExistingFile(baseDir, text);
                        if (num == 2)
{
                            goto IL_028F;
                        }
                        if (num == 1)
{
                            return;
                        }
                    }
                    string text2 = password ?? this._Password ?? this._container.Password;
                    if (this._Encryption_FromZipFile != EncryptionAlgorithm.None)
                    {
                        if (text2 == null)
{
                            throw new BadPasswordException();
                        }
                        this.SetupCryptoForExtract(text2);
                    }
                    if (text != null)
                    {
                        this.WriteStatus("extract file {0}...", new object[] { text });
                        text += ".tmp";
                        string directoryName = Path.GetDirectoryName(text);
                        if (!Directory.Exists(directoryName))
{
                            Directory.CreateDirectory(directoryName);
                        }
                        else if (this._container.ZipFile != null)
{
                            flag2 = this._container.ZipFile._inExtractAll;
                        }
                        stream = new FileStream(text, 1);
                    }
                    else
                    {
                        this.WriteStatus("extract entry {0} to stream...", new object[] { this.FileName });
                        stream = outstream;
                    }
                    if (!this._ioOperationCanceled)
                    {
                        int num2 = this.ExtractOne(stream);
                        if (!this._ioOperationCanceled)
{
                            this.VerifyCrcAfterExtract(num2);
                            if (text != null)
{
                                stream.Close();
                                stream = null;
                                string text3 = text;
                                string text4 = null;
                                text = text3.Substring(0, text3.Length - 4);
                                if (flag)
{
                                    text4 = text + ".PendingOverwrite";
                                    File.Move(text, text4);
                                }
                                File.Move(text3, text);
                                this._SetTimes(text, true);
                                if (text4 != null && File.Exists(text4))
{
                                    ZipEntry.ReallyDelete(text4);
                                }
                                if (flag2 && this.FileName.IndexOf('/') != -1)
{
                                    string directoryName2 = Path.GetDirectoryName(this.FileName);
                                    if (this._container.ZipFile[directoryName2] == null)
{
                                        this._SetTimes(Path.GetDirectoryName(text), false);
                                    }
                                }
                                if (((int)this._VersionMadeBy & 65280) == 2560 || ((int)this._VersionMadeBy & 65280) == 0)
{
                                    NetCfFile.SetAttributes(text, (uint)this._ExternalFileAttrs);
                                }
                            }
                            this.OnAfterExtract(baseDir);
                        }
                    }
                    IL_028F:;
                }
            }
            catch (Exception)
            {
                this._ioOperationCanceled = true;
                throw;
            }
            finally
            {
                if (this._ioOperationCanceled && text != null)
                {
                    if (stream != null)
                    {
                        stream.Close();
                    }
                    if (File.Exists(text) && !flag)
                    {
                        File.Delete(text);
                    }
                }
            }
        }
References Ionic.Zip.ZipEntry._container, Ionic.Zip.ZipEntry._Encryption_FromZipFile, Ionic.Zip.ZipEntry._ExternalFileAttrs, Ionic.Zip.ZipFile._inExtractAll, Ionic.Zip.ZipEntry._ioOperationCanceled, Ionic.Zip.ZipEntry._SetTimes(), Ionic.Zip.ZipEntry._Source, Ionic.Zip.ZipEntry._VersionMadeBy, Ionic.Zip.ZipEntry.CheckExtractExistingFile(), System.IO.Stream.Close(), System.IO.Directory.CreateDirectory(), System.IO.File.Delete(), System.IO.Directory.Exists(), System.IO.File.Exists(), Ionic.Zip.ZipEntry.ExtractOne(), Ionic.Zip.ZipEntry.FileName, System.IO.Path.GetDirectoryName(), System.IO.File.Move(), Ionic.Zip.ZipEntry.OnAfterExtract(), Ionic.Zip.ZipEntry.OnBeforeExtract(), Ionic.Zip.ZipContainer.Password, Ionic.Zip.ZipEntry.ReallyDelete(), Ionic.Zip.ZipFile.Reset(), Ionic.Zip.NetCfFile.SetAttributes(), Ionic.Zip.ZipEntry.SetupCryptoForExtract(), System.text, Ionic.Zip.ZipEntry.ValidateCompression(), Ionic.Zip.ZipEntry.ValidateEncryption(), Ionic.Zip.ZipEntry.ValidateOutput(), Ionic.Zip.ZipEntry.VerifyCrcAfterExtract(), Ionic.Zip.ZipEntry.WriteStatus(), and Ionic.Zip.ZipContainer.ZipFile.
Referenced by Ionic.Zip.ZipEntry.Extract(), Ionic.Zip.ZipEntry.Extract(), Ionic.Zip.ZipEntry.Extract(), Ionic.Zip.ZipEntry.Extract(), Ionic.Zip.ZipEntry.Extract(), Ionic.Zip.ZipEntry.ExtractWithPassword(), Ionic.Zip.ZipEntry.ExtractWithPassword(), Ionic.Zip.ZipEntry.ExtractWithPassword(), Ionic.Zip.ZipEntry.ExtractWithPassword(), and Ionic.Zip.ZipEntry.ExtractWithPassword().