Terraria Decompiled: Terraria.GameContent.UI.States.UIGamepadHelper.LinkVerticalStrips
LinkVerticalStrips()
void Terraria.GameContent.UI.States.UIGamepadHelper.LinkVerticalStrips (UILinkPoint[] stripOnLeft, UILinkPoint[] stripOnRight, int leftStripStartOffset) inline
Definition at line 78 of file UIGamepadHelper.cs.
        {
            if (stripOnLeft == null || stripOnRight == null)
            {
                return;
            }
            int num = Math.Max(stripOnLeft.Length, stripOnRight.Length);
            int num2 = Math.Min(stripOnLeft.Length, stripOnRight.Length);
            for (int i = 0; i < leftStripStartOffset; i++)
            {
                this.PairLeftRight(stripOnLeft[i], stripOnRight[0]);
            }
            for (int j = 0; j < num2; j++)
            {
                this.PairLeftRight(stripOnLeft[j + leftStripStartOffset], stripOnRight[j]);
            }
            for (int k = num2; k < num; k++)
            {
                if (stripOnLeft.Length > k)
                {
                    stripOnLeft[k].Right = stripOnRight[stripOnRight.Length - 1].ID;
                }
                if (stripOnRight.Length > k)
                {
                    stripOnRight[k].Left = stripOnLeft[stripOnLeft.Length - 1].ID;
                }
            }
        }
References Terraria.UI.Gamepad.UILinkPoint.ID, Terraria.UI.Gamepad.UILinkPoint.Left, System.Math.Max(), System.Math.Min(), Terraria.GameContent.UI.States.UIGamepadHelper.PairLeftRight(), and Terraria.UI.Gamepad.UILinkPoint.Right.
Referenced by Terraria.GameContent.UI.States.UICreativePowersMenu.SetupGamepadPoints(), and Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.SetupGamepadPoints().