Terraria Decompiled: Terraria.GameContent.UI.States.UIGamepadHelper.MoveToVisuallyClosestPoint
MoveToVisuallyClosestPoint() [1/2]
void Terraria.GameContent.UI.States.UIGamepadHelper.MoveToVisuallyClosestPoint (int idRangeStartInclusive, int idRangeEndExclusive) inline
Definition at line 333 of file UIGamepadHelper.cs.
        {
            if (UILinkPointNavigator.CurrentPoint >= idRangeStartInclusive && UILinkPointNavigator.CurrentPoint < idRangeEndExclusive)
            {
                return;
            }
            Dictionary<int, UILinkPoint> points = UILinkPointNavigator.Points;
            Vector2 mouseScreen = Main.MouseScreen;
            UILinkPoint uilinkPoint = null;
            for (int i = idRangeStartInclusive; i < idRangeEndExclusive; i++)
            {
                UILinkPoint uilinkPoint2;
                if (!points.TryGetValue(i, out uilinkPoint2))
                {
                    return;
                }
                if (uilinkPoint == null || Vector2.Distance(mouseScreen, uilinkPoint.Position) > Vector2.Distance(mouseScreen, uilinkPoint2.Position))
                {
                    uilinkPoint = uilinkPoint2;
                }
            }
            if (uilinkPoint != null)
            {
                UILinkPointNavigator.ChangePoint(uilinkPoint.ID);
            }
        }
References Terraria.UI.Gamepad.UILinkPointNavigator.ChangePoint(), Terraria.UI.Gamepad.UILinkPointNavigator.CurrentPoint, Microsoft.Xna.Framework.Vector2.Distance(), Terraria.UI.Gamepad.UILinkPoint.ID, Terraria.Main.MouseScreen, Terraria.UI.Gamepad.UILinkPointNavigator.Points, Terraria.UI.Gamepad.UILinkPoint.Position, and System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue().