Terraria Decompiled: Terraria.GameContent.UI.States.UIGamepadHelper.CreateUILinkPointGrid
CreateUILinkPointGrid()
UILinkPoint[,] Terraria.GameContent.UI.States.UIGamepadHelper.CreateUILinkPointGrid (ref int currentID, List< SnapPoint > pointsForGrid, int pointsPerLine, UILinkPoint topLinkPoint, UILinkPoint leftLinkPoint, UILinkPoint rightLinkPoint, UILinkPoint bottomLinkPoint) inline
Definition at line 17 of file UIGamepadHelper.cs.
        {
            int num = (int)Math.Ceiling((double)((float)pointsForGrid.Count / (float)pointsPerLine));
            UILinkPoint[,] array = new UILinkPoint[pointsPerLine, num];
            for (int i = 0; i < pointsForGrid.Count; i++)
            {
                int num2 = i % pointsPerLine;
                int num3 = i / pointsPerLine;
                UILinkPoint[,] array2 = array;
                int num4 = num2;
                int num5 = num3;
                int num6 = currentID;
                currentID = num6 + 1;
                array2[num4, num5] = this.MakeLinkPointFromSnapPoint(num6, pointsForGrid[i]);
            }
            for (int j = 0; j < array.GetLength(0); j++)
            {
                for (int k = 0; k < array.GetLength(1); k++)
                {
                    UILinkPoint uilinkPoint = array[j, k];
                    if (uilinkPoint != null)
                    {
                        if (j < array.GetLength(0) - 1)
{
                            UILinkPoint uilinkPoint2 = array[j + 1, k];
                            if (uilinkPoint2 != null)
{
                                this.PairLeftRight(uilinkPoint, uilinkPoint2);
                            }
                        }
                        if (k < array.GetLength(1) - 1)
{
                            UILinkPoint uilinkPoint3 = array[j, k + 1];
                            if (uilinkPoint3 != null)
{
                                this.PairUpDown(uilinkPoint, uilinkPoint3);
                            }
                        }
                        if (leftLinkPoint != null && j == 0)
{
                            uilinkPoint.Left = leftLinkPoint.ID;
                        }
                        if (topLinkPoint != null && k == 0)
{
                            uilinkPoint.Up = topLinkPoint.ID;
                        }
                        if (rightLinkPoint != null && j == pointsPerLine - 1)
{
                            uilinkPoint.Right = rightLinkPoint.ID;
                        }
                        if (bottomLinkPoint != null && k == num - 1)
{
                            uilinkPoint.Down = bottomLinkPoint.ID;
                        }
                    }
                }
            }
            return array;
        }
References System.array, System.Math.Ceiling(), System.Collections.Generic.List< T >.Count, Terraria.UI.Gamepad.UILinkPoint.ID, int, Terraria.GameContent.UI.States.UIGamepadHelper.MakeLinkPointFromSnapPoint(), Terraria.GameContent.UI.States.UIGamepadHelper.PairLeftRight(), and Terraria.GameContent.UI.States.UIGamepadHelper.PairUpDown().
Referenced by Terraria.GameContent.UI.States.UICreativePowersMenu.SetupGamepadPoints(), Terraria.GameContent.UI.NewCraftingUI.SetupGamepadPoints(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIWorldCreationAdvanced.SetupGamepadPoints(), and Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.SetupGamepadPoints().