Terraria Decompiled: Terraria.GameContent.UI.States.UIGamepadHelper.GetOrderedPointsByCategoryName
GetOrderedPointsByCategoryName()
List< SnapPoint > Terraria.GameContent.UI.States.UIGamepadHelper.GetOrderedPointsByCategoryName (List< SnapPoint > pts, string name) inline
Definition at line 254 of file UIGamepadHelper.cs.
        {
            return (from x in pts
                where x.Name == name
                orderby x.Id
                select x).ToList<SnapPoint>();
        }
References System.name.
Referenced by Terraria.GameContent.UI.States.UIGamepadHelper.GetVerticalStripFromCategoryName(), Terraria.GameContent.UI.States.UICreativePowersMenu.SetupGamepadPoints(), and Terraria.GameContent.UI.NewCraftingUI.SetupGamepadPoints().