Terraria Decompiled: CsvHelper.CsvReader.GetField
GetField() [1/12]
virtual string CsvHelper.CsvReader.GetField (int index) inline virtual
Implements CsvHelper.ICsvReaderRow.
Definition at line 213 of file CsvReader.cs.
        {
            this.CheckDisposed();
            this.CheckHasBeenRead();
            this.currentIndex = index;
            if (index < this.currentRecord.Length)
            {
                string text = this.currentRecord[index];
                if (this.configuration.TrimFields && text != null)
                {
                    text = text.Trim();
                }
                return text;
            }
            if (this.configuration.WillThrowOnMissingField)
            {
                CsvMissingFieldException ex = new CsvMissingFieldException(string.Format("Field at index '{0}' does not exist.", index));
                ExceptionHelper.AddExceptionDataMessage(ex, this.Parser, typeof(string), this.namedIndexes, new int?(index), this.currentRecord);
                throw ex;
            }
            return null;
        }
References CsvHelper.ExceptionHelper.AddExceptionDataMessage(), CsvHelper.CsvReader.CheckDisposed(), CsvHelper.CsvReader.CheckHasBeenRead(), CsvHelper.CsvReader.configuration, CsvHelper.CsvReader.currentRecord, System.Globalization.Format, System.index, CsvHelper.CsvReader.namedIndexes, CsvHelper.CsvReader.Parser, System.text, CsvHelper.Configuration.CsvConfiguration.TrimFields, and CsvHelper.Configuration.CsvConfiguration.WillThrowOnMissingField.