Terraria Decompiled: CsvHelper.CsvReader.ParseNamedIndexes
ParseNamedIndexes()
virtual void CsvHelper.CsvReader.ParseNamedIndexes () inline protected virtual
Definition at line 790 of file CsvReader.cs.
        {
            if (this.headerRecord == null)
            {
                throw new CsvReaderException("No header record was found.");
            }
            for (int i = 0; i < this.headerRecord.Length; i++)
            {
                string text = this.headerRecord[i];
                if (!this.Configuration.IsHeaderCaseSensitive)
                {
                    text = text.ToLower();
                }
                if (this.namedIndexes.ContainsKey(text))
                {
                    this.namedIndexes[text].Add(i);
                }
                else
                {
                    Dictionary<string, List<int>> dictionary = this.namedIndexes;
                    string text2 = text;
                    List<int> list = new List<int>();
                    list.Add(i);
                    dictionary[text2] = list;
                }
            }
        }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), System.dictionary, CsvHelper.CsvReader.headerRecord, System.list, CsvHelper.CsvReader.namedIndexes, and System.text.
Referenced by CsvHelper.CsvReader.ReadHeader().