Terraria Decompiled: CsvHelper.CsvReader.Read
Read()
virtual bool CsvHelper.CsvReader.Read () inline virtual
Implements CsvHelper.ICsvReader.
Definition at line 154 of file CsvReader.cs.
        {
            this.CheckDisposed();
            if (this.doneReading)
            {
                throw new CsvReaderException("The reader has already exhausted all records. If you would like to iterate the records more than once, store the records in memory. i.e. Use CsvReader.GetRecords<T>().ToList()");
            }
            if (this.configuration.HasHeaderRecord && this.headerRecord == null)
            {
                this.ReadHeader();
            }
            do
            {
                this.currentRecord = this.parser.Read();
            }
            while (this.ShouldSkipRecord());
            this.currentIndex = -1;
            this.hasBeenRead = true;
            if (this.currentRecord == null)
            {
                this.doneReading = true;
            }
            return this.currentRecord != null;
        }
References CsvHelper.CsvReader.CheckDisposed(), CsvHelper.CsvReader.configuration, CsvHelper.CsvReader.currentRecord, CsvHelper.CsvReader.doneReading, CsvHelper.Configuration.CsvConfiguration.HasHeaderRecord, CsvHelper.CsvReader.parser, CsvHelper.ICsvParser.Read(), CsvHelper.CsvReader.ReadHeader(), and CsvHelper.CsvReader.ShouldSkipRecord().
Referenced by CsvHelper.CsvReader.GetRecords(), CsvHelper.CsvReader.GetRecords< T >(), and Terraria.Localization.LanguageManager.LoadLanguageFromFileTextCsv().