Terraria Decompiled: CsvHelper.CsvReader.GetField
GetField() [5/12]
virtual object CsvHelper.CsvReader.GetField (string name, int index, ITypeConverter converter) inline virtual
Definition at line 288 of file CsvReader.cs.
        {
            this.CheckDisposed();
            this.CheckHasBeenRead();
            int fieldIndex = this.GetFieldIndex(name, index, false);
            return this.GetField(fieldIndex, converter);
        }
References CsvHelper.CsvReader.CheckDisposed(), CsvHelper.CsvReader.CheckHasBeenRead(), System.converter, System.Reflection.GetField, CsvHelper.CsvReader.GetFieldIndex(), and System.index.