Terraria Decompiled: CsvHelper.CsvReader.TryGetField< T >
TryGetField< T >() [6/6]
virtual bool CsvHelper.CsvReader.TryGetField< T > (string name, out T field) inline virtual
Implements CsvHelper.ICsvReaderRow.
Definition at line 455 of file CsvReader.cs.
        {
            this.CheckDisposed();
            this.CheckHasBeenRead();
            ITypeConverter converter = TypeConverterFactory.GetConverter<T>();
            return this.TryGetField<T>(name, converter, out field);
        }
References CsvHelper.CsvReader.CheckDisposed(), CsvHelper.CsvReader.CheckHasBeenRead(), System.converter, CsvHelper.TypeConversion.TypeConverterFactory.GetConverter(), and CsvHelper.CsvReader.TryGetField< T >().