Terraria Decompiled: CsvHelper.CsvReader.GetField< T, TConverter >
GetField< T, TConverter >() [2/3]
virtual T CsvHelper.CsvReader.GetField< T, TConverter > (string name) inline virtual
Implements CsvHelper.ICsvReaderRow.
Type Constraints
TConverter : ITypeConverter
Definition at line 428 of file CsvReader.cs.
                                                                               : ITypeConverter
        {
            this.CheckDisposed();
            this.CheckHasBeenRead();
            TConverter tconverter = ReflectionHelper.CreateInstance<TConverter>(new object[0]);
            return this.GetField<T>(name, tconverter);
        }
References CsvHelper.CsvReader.CheckDisposed(), CsvHelper.CsvReader.CheckHasBeenRead(), CsvHelper.ReflectionHelper.CreateInstance(), and CsvHelper.CsvReader.GetField< T >().