Terraria Decompiled: CsvHelper.CsvReader.GetRecord
GetRecord()
virtual object CsvHelper.CsvReader.GetRecord (Type type) inline virtual
Implements CsvHelper.ICsvReaderRow.
Definition at line 578 of file CsvReader.cs.
        {
            this.CheckDisposed();
            this.CheckHasBeenRead();
            object obj;
            try
            {
                obj = this.CreateRecord(type);
            }
            catch (Exception ex)
            {
                ExceptionHelper.AddExceptionDataMessage(ex, this.parser, type, this.namedIndexes, new int?(this.currentIndex), this.currentRecord);
                throw;
            }
            return obj;
        }
References CsvHelper.ExceptionHelper.AddExceptionDataMessage(), CsvHelper.CsvReader.CheckDisposed(), CsvHelper.CsvReader.CheckHasBeenRead(), CsvHelper.CsvReader.CreateRecord(), CsvHelper.CsvReader.currentIndex, CsvHelper.CsvReader.currentRecord, CsvHelper.CsvReader.namedIndexes, System.obj, and CsvHelper.CsvReader.parser.