Terraria Decompiled: CsvHelper.CsvReader.TryGetField< T >
TryGetField< T >() [1/6]
virtual bool CsvHelper.CsvReader.TryGetField< T > (int index, ITypeConverter converter, out T field) inline virtual
Implements CsvHelper.ICsvReaderRow.
Definition at line 473 of file CsvReader.cs.
        {
            this.CheckDisposed();
            this.CheckHasBeenRead();
            if (converter is DateTimeConverter && StringHelper.IsNullOrWhiteSpace(this.currentRecord[index]))
            {
                field = default(T);
                return false;
            }
            bool flag;
            try
            {
                field = this.GetField<T>(index, converter);
                flag = true;
            }
            catch
            {
                field = default(T);
                flag = false;
            }
            return flag;
        }
References CsvHelper.CsvReader.CheckDisposed(), CsvHelper.CsvReader.CheckHasBeenRead(), System.converter, CsvHelper.CsvReader.GetField< T >(), System.index, and CsvHelper.StringHelper.IsNullOrWhiteSpace().