Terraria Decompiled: CsvHelper.CsvReader.GetRecords< T >
GetRecords< T >()
virtual IEnumerable< T > CsvHelper.CsvReader.GetRecords< T > () inline virtual
Implements CsvHelper.ICsvReaderRow.
Definition at line 596 of file CsvReader.cs.
        {
            this.CheckDisposed();
            while (this.Read())
            {
                T record;
                try
                {
                    record = this.CreateRecord<T>();
                }
                catch (Exception ex)
                {
                    ExceptionHelper.AddExceptionDataMessage(ex, this.parser, typeof(T), this.namedIndexes, new int?(this.currentIndex), this.currentRecord);
                    if (this.configuration.IgnoreReadingExceptions)
                    {
                        if (this.configuration.ReadingExceptionCallback != null)
{
                            this.configuration.ReadingExceptionCallback.Invoke(ex, this);
                        }
                        continue;
                    }
                    throw;
                }
                yield return record;
                record = default(T);
            }
            yield break;
        }
References CsvHelper.ExceptionHelper.AddExceptionDataMessage(), CsvHelper.CsvReader.CheckDisposed(), CsvHelper.CsvReader.configuration, CsvHelper.CsvReader.CreateRecord< T >(), CsvHelper.CsvReader.currentIndex, CsvHelper.CsvReader.currentRecord, CsvHelper.Configuration.CsvConfiguration.IgnoreReadingExceptions, CsvHelper.CsvReader.namedIndexes, CsvHelper.CsvReader.parser, CsvHelper.CsvReader.Read(), and CsvHelper.Configuration.CsvConfiguration.ReadingExceptionCallback.