Terraria Decompiled: CsvHelper.CsvReader.CreatePropertyBindingsForMapping
CreatePropertyBindingsForMapping()
virtual void CsvHelper.CsvReader.CreatePropertyBindingsForMapping (CsvClassMap mapping, Type recordType, List< MemberBinding > bindings) inline protected virtual
Definition at line 936 of file CsvReader.cs.
        {
            this.AddPropertyBindings(mapping.PropertyMaps, bindings);
            foreach (CsvPropertyReferenceMap csvPropertyReferenceMap in mapping.ReferenceMaps)
            {
                if (this.CanRead(csvPropertyReferenceMap))
                {
                    List<MemberBinding> list = new List<MemberBinding>();
                    this.CreatePropertyBindingsForMapping(csvPropertyReferenceMap.Data.Mapping, csvPropertyReferenceMap.Data.Property.PropertyType, list);
                    MemberInitExpression memberInitExpression = Expression.MemberInit(Expression.New(csvPropertyReferenceMap.Data.Property.PropertyType), list);
                    bindings.Add(Expression.Bind(csvPropertyReferenceMap.Data.Property, memberInitExpression));
                }
            }
        }
References CsvHelper.CsvReader.AddPropertyBindings(), CsvHelper.CsvReader.CanRead(), CsvHelper.CsvReader.CreatePropertyBindingsForMapping(), CsvHelper.Configuration.CsvPropertyReferenceMap.Data, System.list, CsvHelper.Configuration.CsvPropertyReferenceMapData.Mapping, CsvHelper.Configuration.CsvPropertyReferenceMapData.Property, CsvHelper.Configuration.CsvClassMap< T >.PropertyMaps, and System.Reflection.PropertyInfo.PropertyType.
Referenced by CsvHelper.CsvReader.CreateFuncForObject(), and CsvHelper.CsvReader.CreatePropertyBindingsForMapping().