Terraria Decompiled: CsvHelper.CsvReader.GetField
GetField() [8/12]
virtual object CsvHelper.CsvReader.GetField (Type type, int index, ITypeConverter converter) inline virtual
Implements CsvHelper.ICsvReaderRow.
Definition at line 324 of file CsvReader.cs.
        {
            this.CheckDisposed();
            this.CheckHasBeenRead();
            TypeConverterOptions options = TypeConverterOptionsFactory.GetOptions(type);
            if (options.CultureInfo == null)
            {
                options.CultureInfo = this.configuration.CultureInfo;
            }
            string field = this.GetField(index);
            return converter.ConvertFromString(options, field);
        }
References CsvHelper.CsvReader.CheckDisposed(), CsvHelper.CsvReader.CheckHasBeenRead(), CsvHelper.CsvReader.configuration, System.converter, CsvHelper.Configuration.CsvConfiguration.CultureInfo, System.Reflection.GetField, CsvHelper.TypeConversion.TypeConverterOptionsFactory.GetOptions(), and System.options.