Terraria Decompiled: CsvHelper.CsvReader.ReadHeader
ReadHeader()
virtual bool CsvHelper.CsvReader.ReadHeader () inline virtual
Implements CsvHelper.ICsvReader.
Definition at line 127 of file CsvReader.cs.
        {
            this.CheckDisposed();
            if (this.doneReading)
            {
                throw new CsvReaderException("The reader has already exhausted all records. If you would like to iterate the records more than once, store the records in memory. i.e. Use CsvReader.GetRecords<T>().ToList()");
            }
            if (!this.configuration.HasHeaderRecord)
            {
                throw new CsvReaderException("Configuration.HasHeaderRecord is false.");
            }
            if (this.headerRecord != null)
            {
                throw new CsvReaderException("Header record has already been read.");
            }
            do
            {
                this.currentRecord = this.parser.Read();
            }
            while (this.ShouldSkipRecord());
            this.headerRecord = this.currentRecord;
            this.currentRecord = null;
            this.ParseNamedIndexes();
            return this.headerRecord != null;
        }
References CsvHelper.CsvReader.CheckDisposed(), CsvHelper.CsvReader.configuration, CsvHelper.CsvReader.currentRecord, CsvHelper.CsvReader.doneReading, CsvHelper.Configuration.CsvConfiguration.HasHeaderRecord, CsvHelper.CsvReader.headerRecord, CsvHelper.CsvReader.ParseNamedIndexes(), CsvHelper.CsvReader.parser, CsvHelper.ICsvParser.Read(), and CsvHelper.CsvReader.ShouldSkipRecord().
Referenced by Terraria.Localization.LanguageManager.LoadLanguageFromFileTextCsv(), and CsvHelper.CsvReader.Read().