Terraria Decompiled: CsvHelper.CsvReader.GetRecords
GetRecords()
virtual IEnumerable< object > CsvHelper.CsvReader.GetRecords (Type type) inline virtual
Implements CsvHelper.ICsvReaderRow.
Definition at line 626 of file CsvReader.cs.
        {
            this.CheckDisposed();
            while (this.Read())
            {
                object record;
                try
                {
                    record = this.CreateRecord(type);
                }
                catch (Exception ex)
                {
                    ExceptionHelper.AddExceptionDataMessage(ex, this.parser, type, this.namedIndexes, new int?(this.currentIndex), this.currentRecord);
                    if (this.configuration.IgnoreReadingExceptions)
                    {
                        if (this.configuration.ReadingExceptionCallback != null)
{
                            this.configuration.ReadingExceptionCallback.Invoke(ex, this);
                        }
                        continue;
                    }
                    throw;
                }
                yield return record;
                record = null;
            }
            yield break;
        }
References CsvHelper.ExceptionHelper.AddExceptionDataMessage(), CsvHelper.CsvReader.CheckDisposed(), CsvHelper.CsvReader.configuration, CsvHelper.CsvReader.CreateRecord(), CsvHelper.CsvReader.currentIndex, CsvHelper.CsvReader.currentRecord, CsvHelper.Configuration.CsvConfiguration.IgnoreReadingExceptions, CsvHelper.CsvReader.namedIndexes, CsvHelper.CsvReader.parser, CsvHelper.CsvReader.Read(), and CsvHelper.Configuration.CsvConfiguration.ReadingExceptionCallback.