Terraria Decompiled: CsvHelper.CsvReader.CreateReadRecordFunc
CreateReadRecordFunc()
virtual void CsvHelper.CsvReader.CreateReadRecordFunc (Type recordType) inline protected virtual
Definition at line 882 of file CsvReader.cs.
        {
            if (this.recordFuncs.ContainsKey(recordType))
            {
                return;
            }
            if (this.configuration.Maps[recordType] == null)
            {
                this.configuration.Maps.Add(this.configuration.AutoMap(recordType));
            }
            if (recordType.GetTypeInfo().IsPrimitive)
            {
                this.CreateFuncForPrimitive(recordType);
                return;
            }
            this.CreateFuncForObject(recordType);
        }
References CsvHelper.Configuration.CsvClassMapCollection.Add(), CsvHelper.Configuration.CsvConfiguration.AutoMap(), CsvHelper.CsvReader.configuration, System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), CsvHelper.CsvReader.CreateFuncForObject(), CsvHelper.CsvReader.CreateFuncForPrimitive(), System.Type.GetTypeInfo(), CsvHelper.Configuration.CsvConfiguration.Maps, and CsvHelper.CsvReader.recordFuncs.
Referenced by CsvHelper.CsvReader.GetReadRecordFunc(), and CsvHelper.CsvReader.GetReadRecordFunc< T >().