Terraria Decompiled: CsvHelper.CsvReader.CheckHasBeenRead
CheckHasBeenRead()
virtual void CsvHelper.CsvReader.CheckHasBeenRead () inline protected virtual
Definition at line 708 of file CsvReader.cs.
        {
            if (!this.hasBeenRead)
            {
                throw new CsvReaderException("You must call read on the reader before accessing its data.");
            }
        }
References CsvHelper.CsvReader.hasBeenRead.
Referenced by CsvHelper.CsvReader.GetField(), CsvHelper.CsvReader.GetField(), CsvHelper.CsvReader.GetField(), CsvHelper.CsvReader.GetField(), CsvHelper.CsvReader.GetField(), CsvHelper.CsvReader.GetField(), CsvHelper.CsvReader.GetField(), CsvHelper.CsvReader.GetField(), CsvHelper.CsvReader.GetField(), CsvHelper.CsvReader.GetField(), CsvHelper.CsvReader.GetField(), CsvHelper.CsvReader.GetField(), CsvHelper.CsvReader.GetField< T >(), CsvHelper.CsvReader.GetField< T >(), CsvHelper.CsvReader.GetField< T >(), CsvHelper.CsvReader.GetField< T >(), CsvHelper.CsvReader.GetField< T >(), CsvHelper.CsvReader.GetField< T >(), CsvHelper.CsvReader.GetField< T, TConverter >(), CsvHelper.CsvReader.GetField< T, TConverter >(), CsvHelper.CsvReader.GetField< T, TConverter >(), CsvHelper.CsvReader.GetRecord(), CsvHelper.CsvReader.GetRecord< T >(), CsvHelper.CsvReader.IsRecordEmpty(), CsvHelper.CsvReader.IsRecordEmpty(), CsvHelper.CsvReader.TryGetField< T >(), CsvHelper.CsvReader.TryGetField< T >(), CsvHelper.CsvReader.TryGetField< T >(), CsvHelper.CsvReader.TryGetField< T >(), CsvHelper.CsvReader.TryGetField< T >(), CsvHelper.CsvReader.TryGetField< T >(), CsvHelper.CsvReader.TryGetField< T, TConverter >(), CsvHelper.CsvReader.TryGetField< T, TConverter >(), and CsvHelper.CsvReader.TryGetField< T, TConverter >().