Terraria Decompiled: CsvHelper.CsvReader.AddPropertyBindings
AddPropertyBindings()
virtual void CsvHelper.CsvReader.AddPropertyBindings (CsvPropertyMapCollection properties, List< MemberBinding > bindings) inline protected virtual
Definition at line 952 of file CsvReader.cs.
        {
            foreach (CsvPropertyMap csvPropertyMap in properties)
            {
                if (csvPropertyMap.Data.ConvertExpression != null)
                {
                    Expression expression = Expression.Invoke(csvPropertyMap.Data.ConvertExpression, new Expression[] { Expression.Constant(this) });
                    expression = Expression.Convert(expression, csvPropertyMap.Data.Property.PropertyType);
                    bindings.Add(Expression.Bind(csvPropertyMap.Data.Property, expression));
                }
                else if (this.CanRead(csvPropertyMap) && csvPropertyMap.Data.TypeConverter != null && csvPropertyMap.Data.TypeConverter.CanConvertFrom(typeof(string)))
                {
                    int num = -1;
                    if (csvPropertyMap.Data.IsNameSet)
                    {
                        num = this.GetFieldIndex(Enumerable.ToArray<string>(csvPropertyMap.Data.Names), csvPropertyMap.Data.NameIndex, false);
                        if (num == -1)
{
                            continue;
                        }
                    }
                    else if (csvPropertyMap.Data.IsIndexSet)
                    {
                        num = csvPropertyMap.Data.Index;
                    }
                    else if (this.configuration.HasHeaderRecord)
                    {
                        num = this.GetFieldIndex(Enumerable.ToArray<string>(csvPropertyMap.Data.Names), csvPropertyMap.Data.NameIndex, false);
                        if (num == -1)
{
                            continue;
                        }
                    }
                    else if (num == -1)
                    {
                        num = csvPropertyMap.Data.Index;
                    }
                    MethodInfo getMethod = typeof(ICsvReaderRow).GetProperty("Item", typeof(string), new Type[] { typeof(int) }).GetGetMethod();
                    Expression expression2 = Expression.Call(Expression.Constant(this), getMethod, new Expression[] { Expression.Constant(num, typeof(int)) });
                    ConstantExpression constantExpression = Expression.Constant(csvPropertyMap.Data.TypeConverter);
                    if (csvPropertyMap.Data.TypeConverterOptions.CultureInfo == null)
                    {
                        csvPropertyMap.Data.TypeConverterOptions.CultureInfo = this.configuration.CultureInfo;
                    }
                    ConstantExpression constantExpression2 = Expression.Constant(TypeConverterOptions.Merge(new TypeConverterOptions[]
                    {
                        TypeConverterOptionsFactory.GetOptions(csvPropertyMap.Data.Property.PropertyType),
                        csvPropertyMap.Data.TypeConverterOptions
                    }));
                    Expression expression3 = Expression.Call(constantExpression, "ConvertFromString", null, new Expression[] { constantExpression2, expression2 });
                    expression3 = Expression.Convert(expression3, csvPropertyMap.Data.Property.PropertyType);
                    if (csvPropertyMap.Data.IsDefaultSet)
                    {
                        Expression expression4 = Expression.Convert(Expression.Constant(csvPropertyMap.Data.Default), csvPropertyMap.Data.Property.PropertyType);
                        expression2 = Expression.Condition(Expression.Equal(Expression.Convert(Expression.Coalesce(expression2, Expression.Constant(string.Empty)), typeof(string)), Expression.Constant(string.Empty, typeof(string))), expression4, expression3);
                    }
                    else
                    {
                        expression2 = expression3;
                    }
                    bindings.Add(Expression.Bind(csvPropertyMap.Data.Property, expression2));
                }
            }
        }
References CsvHelper.TypeConversion.ITypeConverter.CanConvertFrom(), CsvHelper.CsvReader.CanRead(), CsvHelper.CsvReader.configuration, CsvHelper.Configuration.CsvPropertyMapData.ConvertExpression, CsvHelper.Configuration.CsvConfiguration.CultureInfo, CsvHelper.TypeConversion.TypeConverterOptions.CultureInfo, CsvHelper.Configuration.CsvPropertyMap.Data, CsvHelper.Configuration.CsvPropertyMapData.Default, CsvHelper.CsvReader.GetFieldIndex(), CsvHelper.Configuration.CsvConfiguration.HasHeaderRecord, CsvHelper.Configuration.CsvPropertyMapData.Index, CsvHelper.Configuration.CsvPropertyMapData.IsDefaultSet, CsvHelper.Configuration.CsvPropertyMapData.IsIndexSet, CsvHelper.Configuration.CsvPropertyMapData.IsNameSet, CsvHelper.TypeConversion.TypeConverterOptions.Merge(), CsvHelper.Configuration.CsvPropertyMapData.NameIndex, CsvHelper.Configuration.CsvPropertyMapData.Names, CsvHelper.Configuration.CsvPropertyMapData.Property, System.Reflection.PropertyInfo.PropertyType, CsvHelper.Configuration.CsvPropertyMapData.TypeConverter, and CsvHelper.Configuration.CsvPropertyMapData.TypeConverterOptions.
Referenced by CsvHelper.CsvReader.CreatePropertyBindingsForMapping().