Terraria Decompiled: CsvHelper.CsvReader.GetRecord< T >
GetRecord< T >()
virtual T CsvHelper.CsvReader.GetRecord< T > () inline virtual
Implements CsvHelper.ICsvReaderRow.
Definition at line 560 of file CsvReader.cs.
        {
            this.CheckDisposed();
            this.CheckHasBeenRead();
            T t;
            try
            {
                t = this.CreateRecord<T>();
            }
            catch (Exception ex)
            {
                ExceptionHelper.AddExceptionDataMessage(ex, this.parser, typeof(T), this.namedIndexes, new int?(this.currentIndex), this.currentRecord);
                throw;
            }
            return t;
        }
References CsvHelper.ExceptionHelper.AddExceptionDataMessage(), CsvHelper.CsvReader.CheckDisposed(), CsvHelper.CsvReader.CheckHasBeenRead(), CsvHelper.CsvReader.CreateRecord< T >(), CsvHelper.CsvReader.currentIndex, CsvHelper.CsvReader.currentRecord, CsvHelper.CsvReader.namedIndexes, and CsvHelper.CsvReader.parser.