Terraria Decompiled: CsvHelper.CsvReader.CanRead
CanRead() [1/2]
virtual bool CsvHelper.CsvReader.CanRead (CsvPropertyMap propertyMap) inline protected virtual
Definition at line 1018 of file CsvReader.cs.
        {
            return !propertyMap.Data.Ignore && (!(propertyMap.Data.Property.GetSetMethod() == null) || this.configuration.IgnorePrivateAccessor) && !(propertyMap.Data.Property.GetSetMethod(true) == null);
        }
References CsvHelper.CsvReader.configuration, CsvHelper.Configuration.CsvPropertyMap.Data, System.Reflection.PropertyInfo.GetSetMethod(), CsvHelper.Configuration.CsvConfiguration.IgnorePrivateAccessor, and CsvHelper.Configuration.CsvPropertyMapData.Property.
Referenced by CsvHelper.CsvReader.AddPropertyBindings(), and CsvHelper.CsvReader.CreatePropertyBindingsForMapping().