Terraria Decompiled: CsvHelper.CsvReader.CreateFuncForPrimitive
CreateFuncForPrimitive()
virtual void CsvHelper.CsvReader.CreateFuncForPrimitive (Type recordType) inline protected virtual
Definition at line 915 of file CsvReader.cs.
        {
            MethodInfo getMethod = typeof(ICsvReaderRow).GetProperty("Item", typeof(string), new Type[] { typeof(int) }).GetGetMethod();
            Expression expression = Expression.Call(Expression.Constant(this), getMethod, new Expression[] { Expression.Constant(0, typeof(int)) });
            object converter = TypeConverterFactory.GetConverter(recordType);
            TypeConverterOptions options = TypeConverterOptionsFactory.GetOptions(recordType);
            if (options.CultureInfo == null)
            {
                options.CultureInfo = this.configuration.CultureInfo;
            }
            expression = Expression.Call(Expression.Constant(converter), "ConvertFromString", null, new Expression[]
            {
                Expression.Constant(options),
                expression
            });
            expression = Expression.Convert(expression, recordType);
            Type type = typeof(Func).MakeGenericType(new Type[] { recordType });
            this.recordFuncs[recordType] = Expression.Lambda(type, expression, new ParameterExpression[0]).Compile();
        }
References CsvHelper.CsvReader.configuration, System.converter, CsvHelper.Configuration.CsvConfiguration.CultureInfo, CsvHelper.TypeConversion.TypeConverterFactory.GetConverter(), CsvHelper.TypeConversion.TypeConverterOptionsFactory.GetOptions(), System.Type.MakeGenericType(), System.options, and CsvHelper.CsvReader.recordFuncs.
Referenced by CsvHelper.CsvReader.CreateReadRecordFunc().