Terraria Decompiled: CsvHelper.CsvReader.ShouldSkipRecord
ShouldSkipRecord()
virtual bool CsvHelper.CsvReader.ShouldSkipRecord () inline protected virtual
Definition at line 819 of file CsvReader.cs.
        {
            this.CheckDisposed();
            if (this.currentRecord == null)
            {
                return false;
            }
            if (this.configuration.ShouldSkipRecord == null)
            {
                return this.configuration.SkipEmptyRecords && this.IsRecordEmpty(false);
            }
            return this.configuration.ShouldSkipRecord.Invoke(this.currentRecord);
        }
References CsvHelper.CsvReader.CheckDisposed(), CsvHelper.CsvReader.configuration, CsvHelper.CsvReader.currentRecord, CsvHelper.CsvReader.IsRecordEmpty(), and CsvHelper.Configuration.CsvConfiguration.ShouldSkipRecord.
Referenced by CsvHelper.CsvReader.Read(), and CsvHelper.CsvReader.ReadHeader().