Terraria Decompiled: CsvHelper.CsvReader.CreateFuncForObject
CreateFuncForObject()
virtual void CsvHelper.CsvReader.CreateFuncForObject (Type recordType) inline protected virtual
Definition at line 901 of file CsvReader.cs.
        {
            List<MemberBinding> list = new List<MemberBinding>();
            this.CreatePropertyBindingsForMapping(this.configuration.Maps[recordType], recordType, list);
            if (list.Count == 0)
            {
                throw new CsvReaderException(string.Format(string.Format("No properties are mapped for type '{0}'.", recordType.FullName), new object[0]));
            }
            MemberInitExpression memberInitExpression = Expression.MemberInit(this.configuration.Maps[recordType].Constructor ?? Expression.New(recordType), list);
            Type type = typeof(Func).MakeGenericType(new Type[] { recordType });
            this.recordFuncs[recordType] = Expression.Lambda(type, memberInitExpression, new ParameterExpression[0]).Compile();
        }
References CsvHelper.CsvReader.configuration, CsvHelper.CsvReader.CreatePropertyBindingsForMapping(), System.Globalization.Format, System.Type.FullName, System.list, System.Type.MakeGenericType(), CsvHelper.Configuration.CsvConfiguration.Maps, and CsvHelper.CsvReader.recordFuncs.
Referenced by CsvHelper.CsvReader.CreateReadRecordFunc().