Terraria Decompiled: CsvHelper.CsvReader.GetField< T >
GetField< T >() [2/6]
virtual T CsvHelper.CsvReader.GetField< T > (int index, ITypeConverter converter) inline virtual
Implements CsvHelper.ICsvReaderRow.
Definition at line 383 of file CsvReader.cs.
        {
            this.CheckDisposed();
            this.CheckHasBeenRead();
            if (index < this.currentRecord.Length && index >= 0)
            {
                return (T)((object)this.GetField(typeof(T), index, converter));
            }
            if (this.configuration.WillThrowOnMissingField)
            {
                CsvMissingFieldException ex = new CsvMissingFieldException(string.Format("Field at index '{0}' does not exist.", index));
                ExceptionHelper.AddExceptionDataMessage(ex, this.Parser, typeof(T), this.namedIndexes, new int?(index), this.currentRecord);
                throw ex;
            }
            return default(T);
        }
References CsvHelper.ExceptionHelper.AddExceptionDataMessage(), CsvHelper.CsvReader.CheckDisposed(), CsvHelper.CsvReader.CheckHasBeenRead(), CsvHelper.CsvReader.configuration, System.converter, CsvHelper.CsvReader.currentRecord, System.Globalization.Format, System.Reflection.GetField, System.index, CsvHelper.CsvReader.namedIndexes, CsvHelper.CsvReader.Parser, and CsvHelper.Configuration.CsvConfiguration.WillThrowOnMissingField.