Terraria Decompiled: System.Globalization.Calendar.IsValidDay
IsValidDay()
virtual bool System.Globalization.Calendar.IsValidDay (int year, int month, int day, int era) inline package virtual
Definition at line 456 of file Calendar.cs.
        {
            return this.IsValidMonth(year, month, era) && day >= 1 && day <= this.GetDaysInMonth(year, month, era);
        }
References System.Globalization.Calendar.GetDaysInMonth(), and System.Globalization.Calendar.IsValidMonth().
Referenced by System.Security.Cryptography.X509Certificates.X509Certificate.FormatDate().