Terraria Decompiled: System.Globalization.Calendar.GetWeekOfYearOfMinSupportedDateTime
GetWeekOfYearOfMinSupportedDateTime()
int System.Globalization.Calendar.GetWeekOfYearOfMinSupportedDateTime (int firstDayOfWeek, int minimumDaysInFirstWeek) inline private
Definition at line 303 of file Calendar.cs.
        {
            int num = this.GetDayOfYear(this.MinSupportedDateTime) - 1;
            int num2 = this.GetDayOfWeek(this.MinSupportedDateTime) - (DayOfWeek)(num % 7);
            int num3 = (firstDayOfWeek + 7 - num2) % 7;
            if (num3 == 0 || num3 >= minimumDaysInFirstWeek)
            {
                return 1;
            }
            int num4 = this.DaysInYearBeforeMinSupportedYear - 1;
            int num5 = num2 - 1 - num4 % 7;
            int num6 = (firstDayOfWeek - num5 + 14) % 7;
            int num7 = num4 - num6;
            if (num6 >= minimumDaysInFirstWeek)
            {
                num7 += 7;
            }
            return num7 / 7 + 1;
        }
References System.Globalization.Calendar.GetDayOfWeek(), System.Globalization.Calendar.GetDayOfYear(), and System.Globalization.Calendar.MinSupportedDateTime.
Referenced by System.Globalization.Calendar.GetWeekOfYearFullDays().