Terraria Decompiled: System.Globalization.Calendar.GetWeekOfYear
GetWeekOfYear()
virtual int System.Globalization.Calendar.GetWeekOfYear (DateTime time, CalendarWeekRule rule, DayOfWeek firstDayOfWeek) inline virtual
Reimplemented in System.Globalization.JapaneseCalendar, System.Globalization.KoreanCalendar, System.Globalization.TaiwanCalendar, and System.Globalization.ThaiBuddhistCalendar.
Definition at line 334 of file Calendar.cs.
        {
            if (firstDayOfWeek < DayOfWeek.Sunday || firstDayOfWeek > DayOfWeek.Saturday)
            {
                throw new ArgumentOutOfRangeException("firstDayOfWeek", Environment.GetResourceString("Valid values are between {0} and {1}, inclusive.", new object[]
                {
                    DayOfWeek.Sunday,
                    DayOfWeek.Saturday
                }));
            }
            switch (rule)
            {
            case CalendarWeekRule.FirstDay:
                return this.GetFirstDayWeekOfYear(time, (int)firstDayOfWeek);
            case CalendarWeekRule.FirstFullWeek:
                return this.GetWeekOfYearFullDays(time, (int)firstDayOfWeek, 7);
            case CalendarWeekRule.FirstFourDayWeek:
                return this.GetWeekOfYearFullDays(time, (int)firstDayOfWeek, 4);
            default:
                throw new ArgumentOutOfRangeException("rule", Environment.GetResourceString("Valid values are between {0} and {1}, inclusive.", new object[]
                {
                    CalendarWeekRule.FirstDay,
                    CalendarWeekRule.FirstFourDayWeek
                }));
            }
        }
References System.Globalization.Calendar.GetFirstDayWeekOfYear(), System.Environment.GetResourceString(), and System.Globalization.Calendar.GetWeekOfYearFullDays().
Referenced by System.Globalization.GregorianCalendarHelper.GetWeekOfYear().