Terraria Decompiled: System.Globalization.Calendar.TryToDateTime
TryToDateTime()
virtual bool System.Globalization.Calendar.TryToDateTime (int year, int month, int day, int hour, int minute, int second, int millisecond, int era, out DateTime result) inline package virtual
Reimplemented in System.Globalization.GregorianCalendar.
Definition at line 427 of file Calendar.cs.
        {
            result = DateTime.MinValue;
            bool flag;
            try
            {
                result = this.ToDateTime(year, month, day, hour, minute, second, millisecond, era);
                flag = true;
            }
            catch (ArgumentException)
            {
                flag = false;
            }
            return flag;
        }
References System.DateTime.MinValue, and System.Globalization.Calendar.ToDateTime().
Referenced by System.DateTimeParse.DoStrictParse(), and System.DateTimeParse.ParseISO8601().