Terraria Decompiled: System.Globalization.Calendar.GetLeapMonth
GetLeapMonth() [2/2]
virtual int System.Globalization.Calendar.GetLeapMonth (int year, int era) inline virtual
Reimplemented in System.Globalization.EastAsianLunisolarCalendar, System.Globalization.GregorianCalendar, System.Globalization.HebrewCalendar, System.Globalization.HijriCalendar, System.Globalization.JapaneseCalendar, System.Globalization.JulianCalendar, System.Globalization.KoreanCalendar, System.Globalization.PersianCalendar, System.Globalization.TaiwanCalendar, System.Globalization.ThaiBuddhistCalendar, and System.Globalization.UmAlQuraCalendar.
Definition at line 391 of file Calendar.cs.
        {
            if (!this.IsLeapYear(year, era))
            {
                return 0;
            }
            int monthsInYear = this.GetMonthsInYear(year, era);
            for (int i = 1; i <= monthsInYear; i++)
            {
                if (this.IsLeapMonth(year, i, era))
                {
                    return i;
                }
            }
            return 0;
        }
References System.Globalization.Calendar.GetMonthsInYear(), System.Globalization.Calendar.IsLeapMonth(), and System.Globalization.Calendar.IsLeapYear().