Terraria Decompiled: Terraria.GameContent.LeashedEntities.FlyerLeashedCritter.Update
Update()
override void Terraria.GameContent.LeashedEntities.FlyerLeashedCritter.Update () inline virtual
Reimplemented from Terraria.GameContent.LeashedEntity.
Definition at line 55 of file FlyerLeashedCritter.cs.
        {
            base.Update();
            this.WaitTime -= 1;
            if (this.WaitTime <= 0)
            {
                this.WaitTime = (short)this.rand.Next(this.minWaitTime, this.maxWaitTime + 1);
                this.PickNewTarget();
            }
            Vector2 vector = this.TargetPosition.ToWorldCoordinates(8f, 8f);
            Vector2 vector2 = vector - base.Center;
            float num = vector2.Length();
            Vector2 vector3 = vector2 / num;
            if (vector3.HasNaNs())
            {
                vector3 = Vector2.Zero;
            }
            this.velocity += vector3 * this.acceleration;
            float num2 = this.velocity.Length();
            float num3 = Math.Min(1f, num / ((float)this.brakeDuration * this.maxFlySpeed));
            float num4 = this.maxFlySpeed * Math.Max(num3, 0.25f);
            if (num2 > num4)
            {
                this.velocity *= num4 / num2;
            }
            bool flag = num < this.maxFlySpeed;
            bool flag2 = flag;
            if (!flag2)
            {
                flag2 = WorldGen.SolidTile2((base.Center + base.Size * 0.5f * vector3 + this.velocity).ToTileCoordinates());
            }
            if (flag2)
            {
                if (flag)
                {
                    base.Center = vector;
                }
                Point point = base.Center.ToTileCoordinates();
                this.velocity.X = 0f;
                this.velocity.Y = (WorldGen.SolidTile2(point.X, point.Y + 1) ? 0f : 0.0001f);
            }
            else
            {
                base.Center += this.velocity;
                Point point2 = base.Center.ToTileCoordinates();
                if (this.velocity.Y == 0f && !WorldGen.SolidTile2(point2.X, point2.Y + 1))
                {
                    this.velocity.Y = 0.0001f;
                }
            }
            int num5 = Math.Sign(this.velocity.X);
            if (num5 != 0 && num5 != this.direction)
            {
                this.direction = num5;
                this.spriteDirection = -this.direction;
            }
            if (Main.netMode != 2)
            {
                this.VisualEffects();
            }
            this.CopyToDummy();
            LeashedCritter._dummy.FindFrame();
            base.CopyFromDummy();
        }
References Terraria.GameContent.LeashedEntities.LeashedCritter._dummy, Terraria.GameContent.LeashedEntities.FlyerLeashedCritter.acceleration, Terraria.GameContent.LeashedEntities.FlyerLeashedCritter.brakeDuration, Terraria.GameContent.LeashedEntities.FlyerLeashedCritter.CopyToDummy(), Terraria.GameContent.LeashedEntity.direction, Terraria.NPC.FindFrame(), Microsoft.Xna.Framework.Vector2.Length(), System.Math.Max(), Terraria.GameContent.LeashedEntities.FlyerLeashedCritter.maxFlySpeed, System.Math.Min(), Terraria.Main.netMode, Terraria.GameContent.LeashedEntities.FlyerLeashedCritter.PickNewTarget(), Terraria.GameContent.LeashedEntities.LeashedCritter.rand, System.Math.Sign(), Terraria.WorldGen.SolidTile2(), Terraria.GameContent.LeashedEntities.LeashedCritter.TargetPosition, Terraria.GameContent.LeashedEntity.velocity, Terraria.GameContent.LeashedEntities.LeashedCritter.VisualEffects(), Terraria.GameContent.LeashedEntities.LeashedCritter.WaitTime, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Point.Y, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.