Terraria Decompiled: Terraria.GameContent.LeashedEntities.FlyerLeashedCritter.GetDrawOffset
GetDrawOffset()
override Vector2 Terraria.GameContent.LeashedEntities.FlyerLeashedCritter.GetDrawOffset () inline virtual
Reimplemented from Terraria.GameContent.LeashedEntities.LeashedCritter.
Definition at line 121 of file FlyerLeashedCritter.cs.
        {
            if (this.velocity.Y == 0f)
            {
                Point16 point = base.Center.ToTileCoordinates16();
                if (Framing.GetTileSafely((int)point.X, (int)(point.Y + 1)).halfBrick())
                {
                    return new Vector2(0f, 8f);
                }
                return Vector2.Zero;
            }
            else
            {
                if (this.hoverPeriod == 0f || this.hoverAmplitude == 0f)
                {
                    return Vector2.Zero;
                }
                return this.GetBobbingOffset();
            }
        }
References Terraria.GameContent.LeashedEntities.FlyerLeashedCritter.GetBobbingOffset(), Terraria.Framing.GetTileSafely(), Terraria.Tile.halfBrick(), Terraria.GameContent.LeashedEntities.FlyerLeashedCritter.hoverAmplitude, Terraria.GameContent.LeashedEntities.FlyerLeashedCritter.hoverPeriod, Terraria.GameContent.LeashedEntity.velocity, Terraria.DataStructures.Point16.X, Microsoft.Xna.Framework.Vector2.Y, Terraria.DataStructures.Point16.Y, and Microsoft.Xna.Framework.Vector2.Zero.