Terraria Decompiled: Ionic.BZip2.BZip2InputStream.SetupNoRandPartA
SetupNoRandPartA()
void Ionic.BZip2.BZip2InputStream.SetupNoRandPartA () inline private
Definition at line 852 of file BZip2InputStream.cs.
        {
            if (this.su_i2 <= this.last)
            {
                this.su_chPrev = this.su_ch2;
                int num = (int)(this.data.ll8[this.su_tPos] & byte.MaxValue);
                this.su_ch2 = num;
                this.su_tPos = this.data.tt[this.su_tPos];
                this.su_i2++;
                this.currentChar = num;
                this.currentState = BZip2InputStream.CState.NO_RAND_PART_B;
                this.crc.UpdateCRC((byte)num);
                return;
            }
            this.currentState = BZip2InputStream.CState.NO_RAND_PART_A;
            this.EndBlock();
            this.InitBlock();
            this.SetupBlock();
        }
References Ionic.BZip2.BZip2InputStream.crc, Ionic.BZip2.BZip2InputStream.data, Ionic.BZip2.BZip2InputStream.EndBlock(), Ionic.BZip2.BZip2InputStream.InitBlock(), int, Ionic.BZip2.BZip2InputStream.last, Ionic.BZip2.BZip2InputStream.SetupBlock(), Ionic.BZip2.BZip2InputStream.su_ch2, Ionic.BZip2.BZip2InputStream.su_i2, Ionic.BZip2.BZip2InputStream.su_tPos, and Ionic.Crc.CRC32.UpdateCRC().
Referenced by Ionic.BZip2.BZip2InputStream.SetupBlock(), Ionic.BZip2.BZip2InputStream.SetupNoRandPartB(), and Ionic.BZip2.BZip2InputStream.SetupNoRandPartC().