Terraria Decompiled: Ionic.BZip2.BZip2InputStream.getAndMoveToFrontDecode
getAndMoveToFrontDecode()
void Ionic.BZip2.BZip2InputStream.getAndMoveToFrontDecode () inline private
Definition at line 539 of file BZip2InputStream.cs.
        {
            BZip2InputStream.DecompressionState decompressionState = this.data;
            this.origPtr = this.GetBits(24);
            if (this.origPtr < 0)
            {
                throw new IOException("BZ_DATA_ERROR");
            }
            if (this.origPtr > 10 + BZip2.BlockSizeMultiple * this.blockSize100k)
            {
                throw new IOException("BZ_DATA_ERROR");
            }
            this.recvDecodingTables();
            byte[] getAndMoveToFrontDecode_yy = decompressionState.getAndMoveToFrontDecode_yy;
            int num = this.blockSize100k * BZip2.BlockSizeMultiple;
            int num2 = 256;
            while (--num2 >= 0)
            {
                getAndMoveToFrontDecode_yy[num2] = (byte)num2;
                decompressionState.unzftab[num2] = 0;
            }
            int num3 = 0;
            int num4 = BZip2.G_SIZE - 1;
            int num5 = this.nInUse + 1;
            int num6 = this.getAndMoveToFrontDecode0(0);
            int num7 = this.bsBuff;
            int i = this.bsLive;
            int num8 = -1;
            int num9 = (int)(decompressionState.selector[num3] & byte.MaxValue);
            int[] array = decompressionState.gBase[num9];
            int[] array2 = decompressionState.gLimit[num9];
            int[] array3 = decompressionState.gPerm[num9];
            int num10 = decompressionState.gMinlen[num9];
            while (num6 != num5)
            {
                if (num6 == (int)BZip2.RUNA || num6 == (int)BZip2.RUNB)
                {
                    int num11 = -1;
                    int num12 = 1;
                    for (;;)
                    {
                        if (num6 == (int)BZip2.RUNA)
{
                            num11 += num12;
                        }
                        else
{
                            if (num6 != (int)BZip2.RUNB)
{
                                break;
                            }
                            num11 += num12 << 1;
                        }
                        if (num4 == 0)
{
                            num4 = BZip2.G_SIZE - 1;
                            num9 = (int)(decompressionState.selector[++num3] & byte.MaxValue);
                            array = decompressionState.gBase[num9];
                            array2 = decompressionState.gLimit[num9];
                            array3 = decompressionState.gPerm[num9];
                            num10 = decompressionState.gMinlen[num9];
                        }
                        else
{
                            num4--;
                        }
                        int num13 = num10;
                        while (i < num13)
{
                            int num14 = this.input.ReadByte();
                            if (num14 < 0)
{
                                goto IL_01B9;
                            }
                            num7 = (num7 << 8) | num14;
                            i += 8;
                        }
                        int j = (num7 >> i - num13) & ((1 << num13) - 1);
                        i -= num13;
                        while (j > array2[num13])
{
                            num13++;
                            while (i < 1)
{
                                int num15 = this.input.ReadByte();
                                if (num15 < 0)
{
                                    goto IL_0215;
                                }
                                num7 = (num7 << 8) | num15;
                                i += 8;
                            }
                            i--;
                            j = (j << 1) | ((num7 >> i) & 1);
                        }
                        num6 = array3[j - array[num13]];
                        num12 <<= 1;
                    }
                    byte b = decompressionState.seqToUnseq[(int)getAndMoveToFrontDecode_yy[0]];
                    decompressionState.unzftab[(int)(b & byte.MaxValue)] += num11 + 1;
                    while (num11-- >= 0)
                    {
                        decompressionState.ll8[++num8] = b;
                    }
                    if (num8 >= num)
                    {
                        throw new IOException("block overrun");
                    }
                    continue;
                    IL_01B9:
                    throw new IOException("unexpected end of stream");
                    IL_0215:
                    throw new IOException("unexpected end of stream");
                }
                if (++num8 >= num)
                {
                    throw new IOException("block overrun");
                }
                byte b2 = getAndMoveToFrontDecode_yy[num6 - 1];
                decompressionState.unzftab[(int)(decompressionState.seqToUnseq[(int)b2] & byte.MaxValue)]++;
                decompressionState.ll8[num8] = decompressionState.seqToUnseq[(int)b2];
                if (num6 <= 16)
                {
                    int k = num6 - 1;
                    while (k > 0)
                    {
                        getAndMoveToFrontDecode_yy[k] = getAndMoveToFrontDecode_yy[--k];
                    }
                }
                else
                {
                    Buffer.BlockCopy(getAndMoveToFrontDecode_yy, 0, getAndMoveToFrontDecode_yy, 1, num6 - 1);
                }
                getAndMoveToFrontDecode_yy[0] = b2;
                if (num4 == 0)
                {
                    num4 = BZip2.G_SIZE - 1;
                    num9 = (int)(decompressionState.selector[++num3] & byte.MaxValue);
                    array = decompressionState.gBase[num9];
                    array2 = decompressionState.gLimit[num9];
                    array3 = decompressionState.gPerm[num9];
                    num10 = decompressionState.gMinlen[num9];
                }
                else
                {
                    num4--;
                }
                int num16 = num10;
                while (i < num16)
                {
                    int num17 = this.input.ReadByte();
                    if (num17 < 0)
                    {
                        throw new IOException("unexpected end of stream");
                    }
                    num7 = (num7 << 8) | num17;
                    i += 8;
                }
                int l = (num7 >> i - num16) & ((1 << num16) - 1);
                i -= num16;
                while (l > array2[num16])
                {
                    num16++;
                    while (i < 1)
                    {
                        int num18 = this.input.ReadByte();
                        if (num18 < 0)
{
                            throw new IOException("unexpected end of stream");
                        }
                        num7 = (num7 << 8) | num18;
                        i += 8;
                    }
                    i--;
                    l = (l << 1) | ((num7 >> i) & 1);
                }
                num6 = array3[l - array[num16]];
            }
            this.last = num8;
            this.bsLive = i;
            this.bsBuff = num7;
        }
References System.array, System.Buffer.BlockCopy(), Ionic.BZip2.BZip2.BlockSizeMultiple, Ionic.BZip2.BZip2InputStream.bsBuff, Ionic.BZip2.BZip2InputStream.bsLive, Ionic.BZip2.BZip2InputStream.data, Ionic.BZip2.BZip2InputStream.DecompressionState.gBase, Ionic.BZip2.BZip2InputStream.getAndMoveToFrontDecode0(), Ionic.BZip2.BZip2InputStream.DecompressionState.getAndMoveToFrontDecode_yy, Ionic.BZip2.BZip2InputStream.GetBits(), Ionic.BZip2.BZip2InputStream.DecompressionState.gLimit, Ionic.BZip2.BZip2InputStream.DecompressionState.gMinlen, Ionic.BZip2.BZip2InputStream.DecompressionState.gPerm, Ionic.BZip2.BZip2InputStream.input, int, Ionic.BZip2.BZip2InputStream.DecompressionState.ll8, Ionic.BZip2.BZip2InputStream.origPtr, System.IO.Stream.ReadByte(), Ionic.BZip2.BZip2InputStream.recvDecodingTables(), Ionic.BZip2.BZip2.RUNA, Ionic.BZip2.BZip2.RUNB, Ionic.BZip2.BZip2InputStream.DecompressionState.selector, Ionic.BZip2.BZip2InputStream.DecompressionState.seqToUnseq, and Ionic.BZip2.BZip2InputStream.DecompressionState.unzftab.
Referenced by Ionic.BZip2.BZip2InputStream.InitBlock().