Terraria Decompiled: Ionic.BZip2.BZip2InputStream.SetupNoRandPartC
SetupNoRandPartC()
void Ionic.BZip2.BZip2InputStream.SetupNoRandPartC () inline private
Definition at line 948 of file BZip2InputStream.cs.
        {
            if (this.su_j2 < (int)this.su_z)
            {
                int num = this.su_ch2;
                this.currentChar = num;
                this.crc.UpdateCRC((byte)num);
                this.su_j2++;
                this.currentState = BZip2InputStream.CState.NO_RAND_PART_C;
                return;
            }
            this.su_i2++;
            this.su_count = 0;
            this.SetupNoRandPartA();
        }
References Ionic.BZip2.BZip2InputStream.crc, Ionic.BZip2.BZip2InputStream.SetupNoRandPartA(), Ionic.BZip2.BZip2InputStream.su_ch2, Ionic.BZip2.BZip2InputStream.su_i2, Ionic.BZip2.BZip2InputStream.su_j2, Ionic.BZip2.BZip2InputStream.su_z, and Ionic.Crc.CRC32.UpdateCRC().
Referenced by Ionic.BZip2.BZip2InputStream.ReadByte(), and Ionic.BZip2.BZip2InputStream.SetupNoRandPartB().