Terraria Decompiled: Ionic.BZip2.BZip2InputStream.SetupRandPartB
SetupRandPartB()
void Ionic.BZip2.BZip2InputStream.SetupRandPartB () inline private
Definition at line 873 of file BZip2InputStream.cs.
        {
            if (this.su_ch2 != this.su_chPrev)
            {
                this.currentState = BZip2InputStream.CState.RAND_PART_A;
                this.su_count = 1;
                this.SetupRandPartA();
                return;
            }
            if (++this.su_count >= 4)
            {
                this.su_z = (char)(this.data.ll8[this.su_tPos] & byte.MaxValue);
                this.su_tPos = this.data.tt[this.su_tPos];
                if (this.su_rNToGo == 0)
                {
                    this.su_rNToGo = Rand.Rnums(this.su_rTPos) - 1;
                    if (++this.su_rTPos == 512)
                    {
                        this.su_rTPos = 0;
                    }
                }
                else
                {
                    this.su_rNToGo--;
                }
                this.su_j2 = 0;
                this.currentState = BZip2InputStream.CState.RAND_PART_C;
                if (this.su_rNToGo == 1)
                {
                    this.su_z ^= '\u0001';
                }
                this.SetupRandPartC();
                return;
            }
            this.currentState = BZip2InputStream.CState.RAND_PART_A;
            this.SetupRandPartA();
        }
References Ionic.BZip2.BZip2InputStream.data, Ionic.BZip2.Rand.Rnums(), Ionic.BZip2.BZip2InputStream.SetupRandPartA(), Ionic.BZip2.BZip2InputStream.SetupRandPartC(), Ionic.BZip2.BZip2InputStream.su_ch2, Ionic.BZip2.BZip2InputStream.su_chPrev, Ionic.BZip2.BZip2InputStream.su_count, Ionic.BZip2.BZip2InputStream.su_rNToGo, Ionic.BZip2.BZip2InputStream.su_rTPos, and Ionic.BZip2.BZip2InputStream.su_tPos.
Referenced by Ionic.BZip2.BZip2InputStream.ReadByte().