Terraria Decompiled: Ionic.BZip2.BZip2InputStream.init
init()
void Ionic.BZip2.BZip2InputStream.init () inline private
Definition at line 218 of file BZip2InputStream.cs.
        {
            if (this.input == null)
            {
                throw new IOException("No input Stream");
            }
            if (!this.input.CanRead)
            {
                throw new IOException("Unreadable input Stream");
            }
            this.CheckMagicChar('B', 0);
            this.CheckMagicChar('Z', 1);
            this.CheckMagicChar('h', 2);
            int num = this.input.ReadByte();
            if (num < 49 || num > 57)
            {
                throw new IOException("Stream is not BZip2 formatted: illegal blocksize " + (char)num);
            }
            this.blockSize100k = num - 48;
            this.InitBlock();
            this.SetupBlock();
        }
References System.IO.Stream.CanRead, Ionic.BZip2.BZip2InputStream.CheckMagicChar(), Ionic.BZip2.BZip2InputStream.InitBlock(), Ionic.BZip2.BZip2InputStream.input, System.IO.Stream.ReadByte(), and Ionic.BZip2.BZip2InputStream.SetupBlock().
Referenced by Ionic.BZip2.BZip2InputStream.BZip2InputStream().