Terraria Decompiled: Ionic.BZip2.BZip2InputStream.InitBlock
InitBlock()
void Ionic.BZip2.BZip2InputStream.InitBlock () inline private
Definition at line 253 of file BZip2InputStream.cs.
        {
            char c = this.bsGetUByte();
            char c2 = this.bsGetUByte();
            char c3 = this.bsGetUByte();
            char c4 = this.bsGetUByte();
            char c5 = this.bsGetUByte();
            char c6 = this.bsGetUByte();
            if (c == '\u0017' && c2 == 'r' && c3 == 'E' && c4 == '8' && c5 == 'P' && c6 == '\u0090')
            {
                this.complete();
                return;
            }
            if (c != '1' || c2 != 'A' || c3 != 'Y' || c4 != '&' || c5 != 'S' || c6 != 'Y')
            {
                this.currentState = BZip2InputStream.CState.EOF;
                string text = string.Format("bad block header at offset 0x{0:X}", this.input.Position);
                throw new IOException(text);
            }
            this.storedBlockCRC = this.bsGetInt();
            this.blockRandomised = this.GetBits(1) == 1;
            if (this.data == null)
            {
                this.data = new BZip2InputStream.DecompressionState(this.blockSize100k);
            }
            this.getAndMoveToFrontDecode();
            this.crc.Reset();
            this.currentState = BZip2InputStream.CState.START_BLOCK;
        }
References Ionic.BZip2.BZip2InputStream.blockSize100k, Ionic.BZip2.BZip2InputStream.bsGetInt(), Ionic.BZip2.BZip2InputStream.bsGetUByte(), Ionic.BZip2.BZip2InputStream.complete(), Ionic.BZip2.BZip2InputStream.crc, Ionic.BZip2.BZip2InputStream.data, Ionic.BZip2.BZip2InputStream.getAndMoveToFrontDecode(), Ionic.BZip2.BZip2InputStream.GetBits(), Ionic.BZip2.BZip2InputStream.input, System.IO.Stream.Position, Ionic.Crc.CRC32.Reset(), and System.text.
Referenced by Ionic.BZip2.BZip2InputStream.init(), Ionic.BZip2.BZip2InputStream.SetupNoRandPartA(), and Ionic.BZip2.BZip2InputStream.SetupRandPartA().