Terraria Decompiled: Ionic.BZip2.BZip2InputStream.ReadByte
ReadByte()
override int Ionic.BZip2.BZip2InputStream.ReadByte () inline virtual
Reimplemented from System.IO.Stream.
Definition at line 74 of file BZip2InputStream.cs.
        {
            int num = this.currentChar;
            this.totalBytesRead += 1L;
            switch (this.currentState)
            {
            case BZip2InputStream.CState.EOF:
                return -1;
            case BZip2InputStream.CState.START_BLOCK:
                throw new IOException("bad state");
            case BZip2InputStream.CState.RAND_PART_A:
                throw new IOException("bad state");
            case BZip2InputStream.CState.RAND_PART_B:
                this.SetupRandPartB();
                break;
            case BZip2InputStream.CState.RAND_PART_C:
                this.SetupRandPartC();
                break;
            case BZip2InputStream.CState.NO_RAND_PART_A:
                throw new IOException("bad state");
            case BZip2InputStream.CState.NO_RAND_PART_B:
                this.SetupNoRandPartB();
                break;
            case BZip2InputStream.CState.NO_RAND_PART_C:
                this.SetupNoRandPartC();
                break;
            default:
                throw new IOException("bad state");
            }
            return num;
        }
References Ionic.BZip2.BZip2InputStream.currentChar, Ionic.BZip2.BZip2InputStream.currentState, System.L, Ionic.BZip2.BZip2InputStream.SetupNoRandPartB(), Ionic.BZip2.BZip2InputStream.SetupNoRandPartC(), Ionic.BZip2.BZip2InputStream.SetupRandPartB(), and Ionic.BZip2.BZip2InputStream.SetupRandPartC().
Referenced by Ionic.BZip2.BZip2InputStream.Read().