Terraria Decompiled: Ionic.BZip2.BZip2InputStream.SetupBlock
SetupBlock()
void Ionic.BZip2.BZip2InputStream.SetupBlock () inline private
Definition at line 754 of file BZip2InputStream.cs.
        {
            if (this.data == null)
            {
                return;
            }
            BZip2InputStream.DecompressionState decompressionState = this.data;
            int[] array = decompressionState.initTT(this.last + 1);
            int i;
            for (i = 0; i <= 255; i++)
            {
                if (decompressionState.unzftab[i] < 0 || decompressionState.unzftab[i] > this.last)
                {
                    throw new Exception("BZ_DATA_ERROR");
                }
            }
            decompressionState.cftab[0] = 0;
            for (i = 1; i <= 256; i++)
            {
                decompressionState.cftab[i] = decompressionState.unzftab[i - 1];
            }
            for (i = 1; i <= 256; i++)
            {
                decompressionState.cftab[i] += decompressionState.cftab[i - 1];
            }
            for (i = 0; i <= 256; i++)
            {
                if (decompressionState.cftab[i] < 0 || decompressionState.cftab[i] > this.last + 1)
                {
                    string text = string.Format("BZ_DATA_ERROR: cftab[{0}]={1} last={2}", i, decompressionState.cftab[i], this.last);
                    throw new Exception(text);
                }
            }
            for (i = 1; i <= 256; i++)
            {
                if (decompressionState.cftab[i - 1] > decompressionState.cftab[i])
                {
                    throw new Exception("BZ_DATA_ERROR");
                }
            }
            i = 0;
            int num = this.last;
            while (i <= num)
            {
                array[decompressionState.cftab[(int)(decompressionState.ll8[i] & byte.MaxValue)]++] = i;
                i++;
            }
            if (this.origPtr < 0 || this.origPtr >= array.Length)
            {
                throw new IOException("stream corrupted");
            }
            this.su_tPos = array[this.origPtr];
            this.su_count = 0;
            this.su_i2 = 0;
            this.su_ch2 = 256;
            if (this.blockRandomised)
            {
                this.su_rNToGo = 0;
                this.su_rTPos = 0;
                this.SetupRandPartA();
                return;
            }
            this.SetupNoRandPartA();
        }
References System.array, Ionic.BZip2.BZip2InputStream.blockRandomised, Ionic.BZip2.BZip2InputStream.DecompressionState.cftab, Ionic.BZip2.BZip2InputStream.data, Ionic.BZip2.BZip2InputStream.DecompressionState.initTT(), int, Ionic.BZip2.BZip2InputStream.last, Ionic.BZip2.BZip2InputStream.DecompressionState.ll8, Ionic.BZip2.BZip2InputStream.origPtr, Ionic.BZip2.BZip2InputStream.SetupNoRandPartA(), Ionic.BZip2.BZip2InputStream.SetupRandPartA(), System.text, and Ionic.BZip2.BZip2InputStream.DecompressionState.unzftab.
Referenced by Ionic.BZip2.BZip2InputStream.init(), Ionic.BZip2.BZip2InputStream.SetupNoRandPartA(), and Ionic.BZip2.BZip2InputStream.SetupRandPartA().