Terraria Decompiled: Ionic.BZip2.BZip2InputStream.SetupRandPartA
SetupRandPartA()
void Ionic.BZip2.BZip2InputStream.SetupRandPartA () inline private
Definition at line 820 of file BZip2InputStream.cs.
        {
            if (this.su_i2 <= this.last)
            {
                this.su_chPrev = this.su_ch2;
                int num = (int)(this.data.ll8[this.su_tPos] & byte.MaxValue);
                this.su_tPos = this.data.tt[this.su_tPos];
                if (this.su_rNToGo == 0)
                {
                    this.su_rNToGo = Rand.Rnums(this.su_rTPos) - 1;
                    if (++this.su_rTPos == 512)
                    {
                        this.su_rTPos = 0;
                    }
                }
                else
                {
                    this.su_rNToGo--;
                }
                num = (this.su_ch2 = num ^ ((this.su_rNToGo == 1) ? 1 : 0));
                this.su_i2++;
                this.currentChar = num;
                this.currentState = BZip2InputStream.CState.RAND_PART_B;
                this.crc.UpdateCRC((byte)num);
                return;
            }
            this.EndBlock();
            this.InitBlock();
            this.SetupBlock();
        }
References Ionic.BZip2.BZip2InputStream.crc, Ionic.BZip2.BZip2InputStream.data, Ionic.BZip2.BZip2InputStream.EndBlock(), Ionic.BZip2.BZip2InputStream.InitBlock(), int, Ionic.BZip2.BZip2InputStream.last, Ionic.BZip2.Rand.Rnums(), Ionic.BZip2.BZip2InputStream.SetupBlock(), Ionic.BZip2.BZip2InputStream.su_ch2, Ionic.BZip2.BZip2InputStream.su_i2, Ionic.BZip2.BZip2InputStream.su_rNToGo, Ionic.BZip2.BZip2InputStream.su_rTPos, Ionic.BZip2.BZip2InputStream.su_tPos, and Ionic.Crc.CRC32.UpdateCRC().
Referenced by Ionic.BZip2.BZip2InputStream.SetupBlock(), Ionic.BZip2.BZip2InputStream.SetupRandPartB(), and Ionic.BZip2.BZip2InputStream.SetupRandPartC().