Terraria Decompiled: Ionic.BZip2.BZip2InputStream.SetupNoRandPartB
SetupNoRandPartB()
void Ionic.BZip2.BZip2InputStream.SetupNoRandPartB () inline private
Definition at line 928 of file BZip2InputStream.cs.
        {
            if (this.su_ch2 != this.su_chPrev)
            {
                this.su_count = 1;
                this.SetupNoRandPartA();
                return;
            }
            if (++this.su_count >= 4)
            {
                this.su_z = (char)(this.data.ll8[this.su_tPos] & byte.MaxValue);
                this.su_tPos = this.data.tt[this.su_tPos];
                this.su_j2 = 0;
                this.SetupNoRandPartC();
                return;
            }
            this.SetupNoRandPartA();
        }
References Ionic.BZip2.BZip2InputStream.data, Ionic.BZip2.BZip2InputStream.SetupNoRandPartA(), Ionic.BZip2.BZip2InputStream.SetupNoRandPartC(), Ionic.BZip2.BZip2InputStream.su_ch2, Ionic.BZip2.BZip2InputStream.su_chPrev, Ionic.BZip2.BZip2InputStream.su_count, and Ionic.BZip2.BZip2InputStream.su_tPos.
Referenced by Ionic.BZip2.BZip2InputStream.ReadByte().