Terraria Decompiled: Ionic.BZip2.BZip2InputStream.recvDecodingTables
recvDecodingTables()
void Ionic.BZip2.BZip2InputStream.recvDecodingTables () inline private
Definition at line 431 of file BZip2InputStream.cs.
        {
            BZip2InputStream.DecompressionState decompressionState = this.data;
            bool[] inUse = decompressionState.inUse;
            byte[] recvDecodingTables_pos = decompressionState.recvDecodingTables_pos;
            int num = 0;
            for (int i = 0; i < 16; i++)
            {
                if (this.bsGetBit())
                {
                    num |= 1 << i;
                }
            }
            int num2 = 256;
            while (--num2 >= 0)
            {
                inUse[num2] = false;
            }
            for (int j = 0; j < 16; j++)
            {
                if ((num & (1 << j)) != 0)
                {
                    int num3 = j << 4;
                    for (int k = 0; k < 16; k++)
                    {
                        if (this.bsGetBit())
{
                            inUse[num3 + k] = true;
                        }
                    }
                }
            }
            this.MakeMaps();
            int num4 = this.nInUse + 2;
            int bits = this.GetBits(3);
            int bits2 = this.GetBits(15);
            for (int l = 0; l < bits2; l++)
            {
                int num5 = 0;
                while (this.bsGetBit())
                {
                    num5++;
                }
                decompressionState.selectorMtf[l] = (byte)num5;
            }
            int num6 = bits;
            while (--num6 >= 0)
            {
                recvDecodingTables_pos[num6] = (byte)num6;
            }
            for (int m = 0; m < bits2; m++)
            {
                int n = (int)decompressionState.selectorMtf[m];
                byte b = recvDecodingTables_pos[n];
                while (n > 0)
                {
                    recvDecodingTables_pos[n] = recvDecodingTables_pos[n - 1];
                    n--;
                }
                recvDecodingTables_pos[0] = b;
                decompressionState.selector[m] = b;
            }
            char[][] temp_charArray2d = decompressionState.temp_charArray2d;
            for (int num7 = 0; num7 < bits; num7++)
            {
                int num8 = this.GetBits(5);
                char[] array = temp_charArray2d[num7];
                for (int num9 = 0; num9 < num4; num9++)
                {
                    while (this.bsGetBit())
                    {
                        num8 += (this.bsGetBit() ? (-1) : 1);
                    }
                    array[num9] = (char)num8;
                }
            }
            this.createHuffmanDecodingTables(num4, bits);
        }
References System.array, Ionic.BZip2.BZip2InputStream.bsGetBit(), Ionic.BZip2.BZip2InputStream.createHuffmanDecodingTables(), Ionic.BZip2.BZip2InputStream.data, Ionic.BZip2.BZip2InputStream.GetBits(), int, Ionic.BZip2.BZip2InputStream.DecompressionState.inUse, Ionic.BZip2.BZip2InputStream.MakeMaps(), Ionic.BZip2.BZip2InputStream.DecompressionState.recvDecodingTables_pos, Ionic.BZip2.BZip2InputStream.DecompressionState.selector, Ionic.BZip2.BZip2InputStream.DecompressionState.selectorMtf, and Ionic.BZip2.BZip2InputStream.DecompressionState.temp_charArray2d.
Referenced by Ionic.BZip2.BZip2InputStream.getAndMoveToFrontDecode().