Terraria Decompiled: Terraria.GameContent.Creative.ItemsSacrificedUnlocksTracker.Reset
Reset()
void Terraria.GameContent.Creative.ItemsSacrificedUnlocksTracker.Reset () inline
Implements Terraria.GameContent.IPersistentPerWorldContent.
Definition at line 242 of file ItemsSacrificedUnlocksTracker.cs.
        {
            this._sacrificeCountByItemPersistentId.Clear();
            this._sacrificesCountByItemIdCache.Clear();
            this.AnyNewUnlocksFromTeammates = false;
            this._unlockedByTeammate.Clear();
            this._newlyUnlocked.Clear();
            this.MarkContentsDirty();
        }
References Terraria.GameContent.Creative.ItemsSacrificedUnlocksTracker._newlyUnlocked, Terraria.GameContent.Creative.ItemsSacrificedUnlocksTracker._sacrificeCountByItemPersistentId, Terraria.GameContent.Creative.ItemsSacrificedUnlocksTracker._sacrificesCountByItemIdCache, Terraria.GameContent.Creative.ItemsSacrificedUnlocksTracker._unlockedByTeammate, System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), and Terraria.GameContent.Creative.ItemsSacrificedUnlocksTracker.MarkContentsDirty().
Referenced by Terraria.GameContent.Creative.CreativeUnlocksTracker.Reset().