Terraria Decompiled: Terraria.GameContent.Creative.ItemsSacrificedUnlocksTracker.Load
Load()
void Terraria.GameContent.Creative.ItemsSacrificedUnlocksTracker.Load (BinaryReader reader, int gameVersionSaveWasMadeOn) inline
Implements Terraria.GameContent.IPersistentPerWorldContent.
Definition at line 200 of file ItemsSacrificedUnlocksTracker.cs.
        {
            if (gameVersionSaveWasMadeOn >= 282)
            {
                reader.ReadBoolean();
            }
            int num = reader.ReadInt32();
            for (int i = 0; i < num; i++)
            {
                string text = reader.ReadString();
                int num2 = reader.ReadInt32();
                int num3;
                if (ContentSamples.ItemNetIdsByPersistentIds.TryGetValue(text, out num3))
                {
                    int num4;
                    if (ContentSamples.CreativeResearchItemPersistentIdOverride.TryGetValue(num3, out num4))
                    {
                        num3 = num4;
                    }
                    this._sacrificesCountByItemIdCache[num3] = num2;
                    string text2;
                    if (ContentSamples.ItemPersistentIdsByNetIds.TryGetValue(num3, out text2))
                    {
                        text = text2;
                    }
                }
                this._sacrificeCountByItemPersistentId[text] = num2;
            }
        }
References Terraria.GameContent.Creative.ItemsSacrificedUnlocksTracker._sacrificeCountByItemPersistentId, Terraria.GameContent.Creative.ItemsSacrificedUnlocksTracker._sacrificesCountByItemIdCache, Terraria.ID.ContentSamples.CreativeResearchItemPersistentIdOverride, Terraria.ID.ContentSamples.ItemNetIdsByPersistentIds, Terraria.ID.ContentSamples.ItemPersistentIdsByNetIds, System.IO.BinaryReader.ReadBoolean(), System.IO.BinaryReader.ReadInt32(), System.IO.BinaryReader.ReadString(), System.text, and System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue().
Referenced by Terraria.GameContent.Creative.CreativeUnlocksTracker.Load().