Terraria Decompiled: Terraria.GameContent.Creative.ItemsSacrificedUnlocksTracker.RegisterItemSacrifice
RegisterItemSacrifice()
void Terraria.GameContent.Creative.ItemsSacrificedUnlocksTracker.RegisterItemSacrifice (int itemId, int amount, string teammateName = null) inline
Definition at line 134 of file ItemsSacrificedUnlocksTracker.cs.
        {
            int num;
            if (ContentSamples.CreativeResearchItemPersistentIdOverride.TryGetValue(itemId, out num))
            {
                itemId = num;
            }
            string text;
            if (!ContentSamples.ItemPersistentIdsByNetIds.TryGetValue(itemId, out text))
            {
                return;
            }
            int num2;
            if (!CreativeItemSacrificesCatalog.Instance.TryGetSacrificeCountCapToUnlockInfiniteItems(itemId, out num2))
            {
                return;
            }
            int num3;
            this._sacrificeCountByItemPersistentId.TryGetValue(text, out num3);
            if (num3 >= num2)
            {
                return;
            }
            num3 = Math.Min(num3 + amount, num2);
            this._sacrificeCountByItemPersistentId[text] = num3;
            this._sacrificesCountByItemIdCache[itemId] = num3;
            this.MarkContentsDirty();
            if (num3 >= num2)
            {
                this._newlyUnlocked.Add(itemId);
                if (teammateName != null)
                {
                    this.AnyNewUnlocksFromTeammates = true;
                    this._unlockedByTeammate[itemId] = teammateName;
                }
            }
        }
References Terraria.GameContent.Creative.ItemsSacrificedUnlocksTracker._newlyUnlocked, Terraria.GameContent.Creative.ItemsSacrificedUnlocksTracker._sacrificeCountByItemPersistentId, Terraria.GameContent.Creative.ItemsSacrificedUnlocksTracker._sacrificesCountByItemIdCache, Terraria.GameContent.Creative.ItemsSacrificedUnlocksTracker._unlockedByTeammate, Terraria.ID.ContentSamples.CreativeResearchItemPersistentIdOverride, Terraria.GameContent.Creative.CreativeItemSacrificesCatalog.Instance, Terraria.ID.ContentSamples.ItemPersistentIdsByNetIds, Terraria.GameContent.Creative.ItemsSacrificedUnlocksTracker.MarkContentsDirty(), System.Math.Min(), System.text, Terraria.GameContent.Creative.CreativeItemSacrificesCatalog.TryGetSacrificeCountCapToUnlockInfiniteItems(), and System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue().