Terraria Decompiled: NVorbis.Ogg.ForwardOnlyPageReader.AddPage
AddPage()
override bool NVorbis.Ogg.ForwardOnlyPageReader.AddPage (int streamSerial, byte[] pageBuf, bool isResync) inline protected
Definition at line 38 of file ForwardOnlyPageReader.cs.
        {
            IForwardOnlyPacketProvider forwardOnlyPacketProvider;
            if (this._packetProviders.TryGetValue(streamSerial, ref forwardOnlyPacketProvider))
            {
                if (forwardOnlyPacketProvider.AddPage(pageBuf, isResync) && (pageBuf[5] & 4) == 0)
                {
                    return true;
                }
                this._packetProviders.Remove(streamSerial);
            }
            forwardOnlyPacketProvider = ForwardOnlyPageReader.CreatePacketProvider.Invoke(this, streamSerial);
            if (forwardOnlyPacketProvider.AddPage(pageBuf, isResync))
            {
                this._packetProviders.Add(streamSerial, forwardOnlyPacketProvider);
                if (this._newStreamCallback.Invoke(forwardOnlyPacketProvider))
                {
                    return true;
                }
                this._packetProviders.Remove(streamSerial);
            }
            return false;
        }
References NVorbis.Ogg.ForwardOnlyPageReader._newStreamCallback, NVorbis.Ogg.ForwardOnlyPageReader._packetProviders, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), NVorbis.Contracts.Ogg.IForwardOnlyPacketProvider.AddPage(), NVorbis.Ogg.ForwardOnlyPageReader.CreatePacketProvider, System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), and System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue().