Terraria Decompiled: System.Security.Policy.NetCodeGroup.AddConnectAccess
AddConnectAccess()
void System.Security.Policy.NetCodeGroup.AddConnectAccess (string originScheme, CodeConnectAccess connectAccess) inline
Definition at line 57 of file NetCodeGroup.cs.
        {
            if (originScheme == null)
            {
                throw new ArgumentException("originScheme");
            }
            if (originScheme == NetCodeGroup.AbsentOriginScheme && connectAccess.Scheme == CodeConnectAccess.OriginScheme)
            {
                throw new ArgumentOutOfRangeException("connectAccess", Locale.GetText("Schema == CodeConnectAccess.OriginScheme"));
            }
            if (this._rules.ContainsKey(originScheme))
            {
                if (connectAccess != null)
                {
                    CodeConnectAccess[] array = (CodeConnectAccess[])this._rules[originScheme];
                    CodeConnectAccess[] array2 = new CodeConnectAccess[array.Length + 1];
                    Array.Copy(array, 0, array2, 0, array.Length);
                    array2[array.Length] = connectAccess;
                    this._rules[originScheme] = array2;
                    return;
                }
            }
            else
            {
                CodeConnectAccess[] array3 = new CodeConnectAccess[] { connectAccess };
                this._rules.Add(originScheme, array3);
            }
        }
References System.Security.Policy.NetCodeGroup._rules, System.Security.Policy.NetCodeGroup.AbsentOriginScheme, System.Collections.Hashtable.Add(), System.array, System.Collections.Hashtable.ContainsKey(), System.Array.Copy(), Locale.GetText(), System.Security.Policy.CodeConnectAccess.OriginScheme, and System.Security.Policy.CodeConnectAccess.Scheme.