Terraria Decompiled: System.Security.Policy.StrongNameMembershipCondition.Equals
Equals()
override bool System.Security.Policy.StrongNameMembershipCondition.Equals (object o) inline
Implements System.Security.Policy.IMembershipCondition.
Definition at line 116 of file StrongNameMembershipCondition.cs.
        {
            StrongNameMembershipCondition strongNameMembershipCondition = o as StrongNameMembershipCondition;
            if (strongNameMembershipCondition == null)
            {
                return false;
            }
            if (!strongNameMembershipCondition.PublicKey.Equals(this.PublicKey))
            {
                return false;
            }
            if (this.name != strongNameMembershipCondition.Name)
            {
                return false;
            }
            if (this.assemblyVersion != null)
            {
                return this.assemblyVersion.Equals(strongNameMembershipCondition.Version);
            }
            return strongNameMembershipCondition.Version == null;
        }
References System.Security.Policy.StrongNameMembershipCondition.assemblyVersion, System.Security.Permissions.StrongNamePublicKeyBlob.Equals(), System.Version.Equals(), System.Security.Policy.StrongNameMembershipCondition.Name, System.Security.Policy.StrongNameMembershipCondition.name, System.Security.Policy.StrongNameMembershipCondition.PublicKey, System.Security.Policy.StrongNameMembershipCondition.StrongNameMembershipCondition(), and System.Security.Policy.StrongNameMembershipCondition.Version.