Terraria Decompiled: System.Security.Policy.StrongNameMembershipCondition.ToXml
ToXml() [2/2]
SecurityElement System.Security.Policy.StrongNameMembershipCondition.ToXml (PolicyLevel level) inline
Implements System.Security.ISecurityPolicyEncodable.
Definition at line 188 of file StrongNameMembershipCondition.cs.
        {
            SecurityElement securityElement = MembershipConditionHelper.Element(typeof(StrongNameMembershipCondition), this.version);
            if (this.blob != null)
            {
                securityElement.AddAttribute("PublicKeyBlob", this.blob.ToString());
            }
            if (this.name != null)
            {
                securityElement.AddAttribute("Name", this.name);
            }
            if (this.assemblyVersion != null)
            {
                string text = this.assemblyVersion.ToString();
                if (text != "0.0")
                {
                    securityElement.AddAttribute("AssemblyVersion", text);
                }
            }
            return securityElement;
        }
References System.Security.SecurityElement.AddAttribute(), System.Security.Policy.StrongNameMembershipCondition.assemblyVersion, System.Security.Policy.StrongNameMembershipCondition.blob, System.Security.Policy.MembershipConditionHelper.Element(), System.Security.Policy.StrongNameMembershipCondition.name, System.text, System.Security.Permissions.StrongNamePublicKeyBlob.ToString(), System.Version.ToString(), and System.Security.Policy.StrongNameMembershipCondition.version.