Terraria Decompiled: System.Security.Policy.StrongNameMembershipCondition.Check
Check()
bool System.Security.Policy.StrongNameMembershipCondition.Check (Evidence evidence) inline
Implements System.Security.Policy.IMembershipCondition.
Definition at line 90 of file StrongNameMembershipCondition.cs.
        {
            if (evidence == null)
            {
                return false;
            }
            IEnumerator hostEnumerator = evidence.GetHostEnumerator();
            while (hostEnumerator.MoveNext())
            {
                object obj = hostEnumerator.Current;
                StrongName strongName = obj as StrongName;
                if (strongName != null)
                {
                    return strongName.PublicKey.Equals(this.blob) && (this.name == null || !(this.name != strongName.Name)) && (!(this.assemblyVersion != null) || this.assemblyVersion.Equals(strongName.Version));
                }
            }
            return false;
        }
References System.Security.Policy.StrongNameMembershipCondition.assemblyVersion, System.Security.Policy.StrongNameMembershipCondition.blob, System.Collections.IEnumerator.Current, System.Security.Permissions.StrongNamePublicKeyBlob.Equals(), System.Version.Equals(), System.Security.Policy.Evidence.GetHostEnumerator(), System.Collections.IEnumerator.MoveNext(), System.Security.Policy.StrongName.Name, System.obj, System.Security.Policy.StrongName.PublicKey, and System.Security.Policy.StrongName.Version.