Terraria Decompiled: XPT.Core.Audio.MP3Sharp.Decoding.SynthesisFilter.calculate_pc_samples
calculate_pc_samples()
void XPT.Core.Audio.MP3Sharp.Decoding.SynthesisFilter.calculate_pc_samples (ABuffer buffer) inline package
Definition at line 687 of file SynthesisFilter.cs.
        {
            this.ComputeNewValues();
            this.compute_pc_samples(buffer);
            this._ActualWritePos = (this._ActualWritePos + 1) & 15;
            this._ActualV = ((this._ActualV == this._V1) ? this._V2 : this._V1);
            for (int i = 0; i < 32; i++)
            {
                this._Samples[i] = 0f;
            }
        }
References XPT.Core.Audio.MP3Sharp.Decoding.SynthesisFilter._Samples, XPT.Core.Audio.MP3Sharp.Decoding.SynthesisFilter._V1, XPT.Core.Audio.MP3Sharp.Decoding.SynthesisFilter._V2, XPT.Core.Audio.MP3Sharp.Decoding.SynthesisFilter.compute_pc_samples(), and XPT.Core.Audio.MP3Sharp.Decoding.SynthesisFilter.ComputeNewValues().
Referenced by XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.Decode(), and XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIDecoder.ReadSampleData().