Terraria Decompiled: XPT.Core.Audio.MP3Sharp.Decoding.SynthesisFilter.SynthesisFilter
SynthesisFilter() [1/2]
XPT.Core.Audio.MP3Sharp.Decoding.SynthesisFilter.SynthesisFilter (int channelnumber, float factor, float[] eq0) inline package
Definition at line 9 of file SynthesisFilter.cs.
        {
            this.InitBlock();
            if (SynthesisFilter._d == null)
            {
                SynthesisFilter._d = SynthesisFilter.DData;
                SynthesisFilter._d16 = SynthesisFilter.SplitArray(SynthesisFilter._d, 16);
            }
            this._V1 = new float[512];
            this._V2 = new float[512];
            this._Samples = new float[32];
            this._Channel = channelnumber;
            this._Scalefactor = factor;
            this.Eq = this._Eq;
            this.Reset();
        }
References XPT.Core.Audio.MP3Sharp.Decoding.SynthesisFilter._d, XPT.Core.Audio.MP3Sharp.Decoding.SynthesisFilter._Eq, XPT.Core.Audio.MP3Sharp.Decoding.SynthesisFilter.DData, XPT.Core.Audio.MP3Sharp.Decoding.SynthesisFilter.InitBlock(), XPT.Core.Audio.MP3Sharp.Decoding.SynthesisFilter.Reset(), and XPT.Core.Audio.MP3Sharp.Decoding.SynthesisFilter.SplitArray().