Terraria Decompiled: XPT.Core.Audio.MP3Sharp.Decoding.SynthesisFilter.compute_pc_samples
compute_pc_samples()
void XPT.Core.Audio.MP3Sharp.Decoding.SynthesisFilter.compute_pc_samples (ABuffer buffer) inline private
Definition at line 627 of file SynthesisFilter.cs.
        {
            switch (this._ActualWritePos)
            {
            case 0:
                this.compute_pc_samples0(buffer);
                break;
            case 1:
                this.compute_pc_samples1(buffer);
                break;
            case 2:
                this.compute_pc_samples2(buffer);
                break;
            case 3:
                this.compute_pc_samples3(buffer);
                break;
            case 4:
                this.compute_pc_samples4(buffer);
                break;
            case 5:
                this.compute_pc_samples5(buffer);
                break;
            case 6:
                this.compute_pc_samples6(buffer);
                break;
            case 7:
                this.compute_pc_samples7(buffer);
                break;
            case 8:
                this.compute_pc_samples8(buffer);
                break;
            case 9:
                this.compute_pc_samples9(buffer);
                break;
            case 10:
                this.compute_pc_samples10(buffer);
                break;
            case 11:
                this.compute_pc_samples11(buffer);
                break;
            case 12:
                this.compute_pc_samples12(buffer);
                break;
            case 13:
                this.compute_pc_samples13(buffer);
                break;
            case 14:
                this.compute_pc_samples14(buffer);
                break;
            case 15:
                this.Compute_pc_samples15(buffer);
                break;
            }
            if (buffer != null)
            {
                buffer.AppendSamples(this._Channel, this._TmpOut);
            }
        }
References XPT.Core.Audio.MP3Sharp.Decoding.SynthesisFilter._ActualWritePos, XPT.Core.Audio.MP3Sharp.Decoding.SynthesisFilter._Channel, XPT.Core.Audio.MP3Sharp.Decoding.SynthesisFilter._TmpOut, XPT.Core.Audio.MP3Sharp.Decoding.ABuffer.AppendSamples(), XPT.Core.Audio.MP3Sharp.Decoding.SynthesisFilter.compute_pc_samples0(), XPT.Core.Audio.MP3Sharp.Decoding.SynthesisFilter.compute_pc_samples1(), XPT.Core.Audio.MP3Sharp.Decoding.SynthesisFilter.compute_pc_samples10(), XPT.Core.Audio.MP3Sharp.Decoding.SynthesisFilter.compute_pc_samples11(), XPT.Core.Audio.MP3Sharp.Decoding.SynthesisFilter.compute_pc_samples12(), XPT.Core.Audio.MP3Sharp.Decoding.SynthesisFilter.compute_pc_samples13(), XPT.Core.Audio.MP3Sharp.Decoding.SynthesisFilter.compute_pc_samples14(), XPT.Core.Audio.MP3Sharp.Decoding.SynthesisFilter.Compute_pc_samples15(), XPT.Core.Audio.MP3Sharp.Decoding.SynthesisFilter.compute_pc_samples2(), XPT.Core.Audio.MP3Sharp.Decoding.SynthesisFilter.compute_pc_samples3(), XPT.Core.Audio.MP3Sharp.Decoding.SynthesisFilter.compute_pc_samples4(), XPT.Core.Audio.MP3Sharp.Decoding.SynthesisFilter.compute_pc_samples5(), XPT.Core.Audio.MP3Sharp.Decoding.SynthesisFilter.compute_pc_samples6(), XPT.Core.Audio.MP3Sharp.Decoding.SynthesisFilter.compute_pc_samples7(), XPT.Core.Audio.MP3Sharp.Decoding.SynthesisFilter.compute_pc_samples8(), and XPT.Core.Audio.MP3Sharp.Decoding.SynthesisFilter.compute_pc_samples9().
Referenced by XPT.Core.Audio.MP3Sharp.Decoding.SynthesisFilter.calculate_pc_samples().