Terraria Decompiled: System.Security.Cryptography.RSAPKCS1KeyExchangeDeformatter.DecryptKeyExchange
DecryptKeyExchange()
override byte[] System.Security.Cryptography.RSAPKCS1KeyExchangeDeformatter.DecryptKeyExchange (byte[] rgbIn) inline
Definition at line 55 of file RSAPKCS1KeyExchangeDeformatter.cs.
        {
            if (this._rsaKey == null)
            {
                throw new CryptographicUnexpectedOperationException(Environment.GetResourceString("No asymmetric key object has been associated with this formatter object."));
            }
            byte[] array;
            if (this.OverridesDecrypt)
            {
                array = this._rsaKey.Decrypt(rgbIn, RSAEncryptionPadding.Pkcs1);
            }
            else
            {
                byte[] array2 = this._rsaKey.DecryptValue(rgbIn);
                int num = 2;
                while (num < array2.Length && array2[num] != 0)
                {
                    num++;
                }
                if (num >= array2.Length)
                {
                    throw new CryptographicUnexpectedOperationException(Environment.GetResourceString("Error occurred while decoding PKCS1 padding."));
                }
                num++;
                array = new byte[array2.Length - num];
                Buffer.InternalBlockCopy(array2, num, array, 0, array.Length);
            }
            return array;
        }
References System.Security.Cryptography.RSAPKCS1KeyExchangeDeformatter._rsaKey, System.array, System.Security.Cryptography.RSA.Decrypt(), System.Security.Cryptography.RSA.DecryptValue(), System.Environment.GetResourceString(), System.Buffer.InternalBlockCopy(), System.Security.Cryptography.RSAPKCS1KeyExchangeDeformatter.OverridesDecrypt, and System.Security.Cryptography.RSAEncryptionPadding.Pkcs1.