Terraria Decompiled: Terraria.Graphics.SpriteViewMatrix.Rebuild
Rebuild()
void Terraria.Graphics.SpriteViewMatrix.Rebuild () inline private
Definition at line 135 of file SpriteViewMatrix.cs.
        {
            if (!this._overrideSystemViewport)
            {
                this._viewport = this._graphicsDevice.Viewport;
            }
            Vector2 vector = new Vector2((float)this._viewport.Width, (float)this._viewport.Height);
            Matrix matrix = Matrix.Identity;
            if ((this._effects & SpriteEffects.FlipHorizontally) != SpriteEffects.None)
            {
                matrix *= Matrix.CreateScale(-1f, 1f, 1f) * Matrix.CreateTranslation(vector.X, 0f, 0f);
            }
            if ((this._effects & SpriteEffects.FlipVertically) != SpriteEffects.None)
            {
                matrix *= Matrix.CreateScale(1f, -1f, 1f) * Matrix.CreateTranslation(0f, vector.Y, 0f);
            }
            Vector2 vector2 = Utils.Round(this._zoom / 0.0078125f) * 0.0078125f;
            Vector2 vector3 = vector * 0.5f;
            Vector2 vector4 = Utils.Round(vector3 - vector3 / vector2);
            Matrix matrix2 = Matrix.CreateOrthographicOffCenter(0f, vector.X, vector.Y, 0f, 0f, 1f);
            this._translation = vector4;
            this._zoomMatrix = Matrix.CreateTranslation(-vector4.X, -vector4.Y, 0f) * Matrix.CreateScale(vector2.X, vector2.Y, 1f);
            this._effectMatrix = matrix;
            this._transformationMatrix = matrix * this._zoomMatrix;
            Matrix matrix3 = Matrix.CreateTranslation(0.00390625f, 0.00390625f, 0f);
            this._transformationMatrix *= matrix3;
            this._normalizedTransformationMatrix = Matrix.Invert(matrix) * this._zoomMatrix * matrix2;
            this._needsRebuild = false;
        }
References Terraria.Graphics.SpriteViewMatrix._effects, Terraria.Graphics.SpriteViewMatrix._graphicsDevice, Terraria.Graphics.SpriteViewMatrix._overrideSystemViewport, Terraria.Graphics.SpriteViewMatrix._viewport, Terraria.Graphics.SpriteViewMatrix._zoom, Terraria.Graphics.SpriteViewMatrix._zoomMatrix, Microsoft.Xna.Framework.Matrix.CreateOrthographicOffCenter(), Microsoft.Xna.Framework.Matrix.CreateScale(), Microsoft.Xna.Framework.Matrix.CreateTranslation(), Microsoft.Xna.Framework.Matrix.Identity, Microsoft.Xna.Framework.Matrix.Invert(), Terraria.Utils.Round(), Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Graphics.GraphicsDevice.Viewport, Microsoft.Xna.Framework.Graphics.Viewport.Width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.