Terraria Decompiled: Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives< T >
DrawUserIndexedPrimitives< T >() [3/4]
void Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives< T > (PrimitiveType primitiveType, T[] vertexData, int vertexOffset, int numVertices, short[] indexData, int indexOffset, int primitiveCount) inline
Type Constraints
T : struct
T : IVertexType
Definition at line 1079 of file GraphicsDevice.cs.
                                                                                                                                                                                                 : struct, IVertexType
        {
            this.ApplyState();
            GCHandle gchandle = GCHandle.Alloc(vertexData, GCHandleType.Pinned);
            GCHandle gchandle2 = GCHandle.Alloc(indexData, GCHandleType.Pinned);
            this.PrepareUserVertexBuffer(gchandle.AddrOfPinnedObject(), numVertices, vertexOffset, VertexDeclarationCache<T>.VertexDeclaration);
            this.PrepareUserIndexBuffer(gchandle2.AddrOfPinnedObject(), GraphicsDevice.PrimitiveVerts(primitiveType, primitiveCount), indexOffset, 2);
            gchandle2.Free();
            gchandle.Free();
            FNA3D.FNA3D_DrawIndexedPrimitives(this.GLDevice, primitiveType, 0, 0, numVertices, 0, primitiveCount, this.userIndexBuffer, IndexElementSize.SixteenBits);
        }
References System.Runtime.InteropServices.GCHandle.AddrOfPinnedObject(), System.Runtime.InteropServices.GCHandle.Alloc(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.ApplyState(), Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_DrawIndexedPrimitives(), System.Runtime.InteropServices.GCHandle.Free(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.GLDevice, Microsoft.Xna.Framework.Graphics.GraphicsDevice.PrepareUserIndexBuffer(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.PrepareUserVertexBuffer(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.PrimitiveVerts(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.userIndexBuffer, and Microsoft.Xna.Framework.Graphics.VertexDeclarationCache< T >.VertexDeclaration.