Terraria Decompiled: Microsoft.Xna.Framework.Graphics.GraphicsDevice.PrimitiveVerts
PrimitiveVerts()
static int Microsoft.Xna.Framework.Graphics.GraphicsDevice.PrimitiveVerts (PrimitiveType primitiveType, int primitiveCount) inline static private
Definition at line 1291 of file GraphicsDevice.cs.
        {
            switch (primitiveType)
            {
            case PrimitiveType.TriangleList:
                return primitiveCount * 3;
            case PrimitiveType.TriangleStrip:
                return primitiveCount + 2;
            case PrimitiveType.LineList:
                return primitiveCount * 2;
            case PrimitiveType.LineStrip:
                return primitiveCount + 1;
            case PrimitiveType.PointListEXT:
                return primitiveCount;
            default:
                throw new InvalidOperationException("Unrecognized primitive type!");
            }
        }
Referenced by Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives< T >(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives< T >(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives< T >(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives< T >(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserPrimitives< T >(), and Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserPrimitives< T >().