Terraria Decompiled: Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawInstancedPrimitives
DrawInstancedPrimitives()
void Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawInstancedPrimitives (PrimitiveType primitiveType, int baseVertex, int minVertexIndex, int numVertices, int startIndex, int primitiveCount, int instanceCount) inline
Definition at line 1059 of file GraphicsDevice.cs.
        {
            if (FNA3D.FNA3D_SupportsHardwareInstancing(this.GLDevice) == 0)
            {
                throw new NoSuitableGraphicsDeviceException("Your hardware does not support hardware instancing!");
            }
            this.ApplyState();
            this.PrepareVertexBindingArray(baseVertex);
            FNA3D.FNA3D_DrawInstancedPrimitives(this.GLDevice, primitiveType, baseVertex, minVertexIndex, numVertices, startIndex, primitiveCount, instanceCount, this.Indices.buffer, this.Indices.IndexElementSize);
        }
References Microsoft.Xna.Framework.Graphics.GraphicsDevice.ApplyState(), Microsoft.Xna.Framework.Graphics.IndexBuffer.buffer, Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_DrawInstancedPrimitives(), Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_SupportsHardwareInstancing(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.GLDevice, Microsoft.Xna.Framework.Graphics.GraphicsDevice.Indices, Microsoft.Xna.Framework.Graphics.GraphicsDevice.PrepareVertexBindingArray(), and System.startIndex.