Terraria Decompiled: Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetRenderTargets
SetRenderTargets()
unsafe void Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetRenderTargets (params RenderTargetBinding[] renderTargets) inline
Definition at line 851 of file GraphicsDevice.cs.
        {
            FNA3D.FNA3D_ApplyRasterizerState(this.GLDevice, ref this.RasterizerState.state);
            this.ApplySamplers();
            if (renderTargets == null && this.renderTargetCount == 0)
            {
                return;
            }
            if (renderTargets != null && renderTargets.Length == this.renderTargetCount)
            {
                bool flag = true;
                for (int i = 0; i < renderTargets.Length; i++)
                {
                    if (renderTargets[i].RenderTarget != this.renderTargetBindings[i].RenderTarget || renderTargets[i].CubeMapFace != this.renderTargetBindings[i].CubeMapFace)
                    {
                        flag = false;
                        break;
                    }
                }
                if (flag)
                {
                    return;
                }
            }
            int num;
            int num2;
            RenderTargetUsage renderTargetUsage;
            if (renderTargets == null || renderTargets.Length == 0)
            {
                FNA3D.FNA3D_SetRenderTargets(this.GLDevice, IntPtr.Zero, 0, IntPtr.Zero, DepthFormat.None, (this.PresentationParameters.RenderTargetUsage > RenderTargetUsage.DiscardContents) ? 1 : 0);
                num = this.PresentationParameters.BackBufferWidth;
                num2 = this.PresentationParameters.BackBufferHeight;
                renderTargetUsage = this.PresentationParameters.RenderTargetUsage;
                for (int j = 0; j < this.renderTargetCount; j++)
                {
                    FNA3D.FNA3D_ResolveTarget(this.GLDevice, ref this.nativeTargetBindings[j]);
                }
                Array.Clear(this.renderTargetBindings, 0, this.renderTargetBindings.Length);
                Array.Clear(this.nativeTargetBindings, 0, this.nativeTargetBindings.Length);
                this.renderTargetCount = 0;
            }
            else
            {
                IRenderTarget renderTarget = renderTargets[0].RenderTarget as IRenderTarget;
                fixed (FNA3D.FNA3D_RenderTargetBinding* ptr = &this.nativeTargetBindingsNext[0])
                {
                    FNA3D.FNA3D_RenderTargetBinding* ptr2 = ptr;
                    GraphicsDevice.PrepareRenderTargetBindings(ptr2, renderTargets);
                    FNA3D.FNA3D_SetRenderTargets(this.GLDevice, ptr2, renderTargets.Length, renderTarget.DepthStencilBuffer, renderTarget.DepthStencilFormat, (renderTarget.RenderTargetUsage > RenderTargetUsage.DiscardContents) ? 1 : 0);
                }
                num = renderTarget.Width;
                num2 = renderTarget.Height;
                renderTargetUsage = renderTarget.RenderTargetUsage;
                for (int k = 0; k < this.renderTargetCount; k++)
                {
                    bool flag2 = false;
                    for (int l = 0; l < renderTargets.Length; l++)
                    {
                        if (this.renderTargetBindings[k].RenderTarget == renderTargets[l].RenderTarget)
{
                            flag2 = true;
                            break;
                        }
                    }
                    if (!flag2)
                    {
                        FNA3D.FNA3D_ResolveTarget(this.GLDevice, ref this.nativeTargetBindings[k]);
                    }
                }
                Array.Clear(this.renderTargetBindings, 0, this.renderTargetBindings.Length);
                Array.Copy(renderTargets, this.renderTargetBindings, renderTargets.Length);
                Array.Clear(this.nativeTargetBindings, 0, this.nativeTargetBindings.Length);
                Array.Copy(this.nativeTargetBindingsNext, this.nativeTargetBindings, renderTargets.Length);
                this.renderTargetCount = renderTargets.Length;
            }
            this.Viewport = new Viewport(0, 0, num, num2);
            this.ScissorRectangle = new Rectangle(0, 0, num, num2);
            if (renderTargetUsage == RenderTargetUsage.DiscardContents)
            {
                this.Clear(ClearOptions.Target | ClearOptions.DepthBuffer | ClearOptions.Stencil, GraphicsDevice.DiscardColor, this.Viewport.MaxDepth, 0);
            }
        }
References Microsoft.Xna.Framework.Graphics.GraphicsDevice.ApplySamplers(), Microsoft.Xna.Framework.Graphics.PresentationParameters.BackBufferHeight, Microsoft.Xna.Framework.Graphics.PresentationParameters.BackBufferWidth, System.Array.Clear(), System.Clear, System.Array.Copy(), Microsoft.Xna.Framework.Graphics.IRenderTarget.DepthStencilBuffer, Microsoft.Xna.Framework.Graphics.IRenderTarget.DepthStencilFormat, Microsoft.Xna.Framework.Graphics.GraphicsDevice.DiscardColor, Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_ApplyRasterizerState(), Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_ResolveTarget(), Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_SetRenderTargets(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.GLDevice, Microsoft.Xna.Framework.Graphics.IRenderTarget.Height, Microsoft.Xna.Framework.Graphics.GraphicsDevice.nativeTargetBindings, Microsoft.Xna.Framework.Graphics.GraphicsDevice.nativeTargetBindingsNext, Microsoft.Xna.Framework.Graphics.GraphicsDevice.PrepareRenderTargetBindings(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.renderTargetBindings, Microsoft.Xna.Framework.Graphics.GraphicsDevice.renderTargetCount, Microsoft.Xna.Framework.Graphics.IRenderTarget.RenderTargetUsage, Microsoft.Xna.Framework.Graphics.PresentationParameters.RenderTargetUsage, Microsoft.Xna.Framework.Graphics.RasterizerState.state, Microsoft.Xna.Framework.Graphics.GraphicsDevice.Viewport, Microsoft.Xna.Framework.Graphics.IRenderTarget.Width, and System.IntPtr.Zero.
Referenced by Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetRenderTarget(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetRenderTarget(), and Terraria.Graphics.WorldSceneLayerTarget.UpdateContent().