Terraria Decompiled: Microsoft.Xna.Framework.Graphics.GraphicsDevice.Dispose
Dispose() [2/2]
virtual void Microsoft.Xna.Framework.Graphics.GraphicsDevice.Dispose (bool disposing) inline protected virtual
Definition at line 593 of file GraphicsDevice.cs.
        {
            if (!this.IsDisposed)
            {
                this.IsDisposed = true;
                if (disposing)
                {
                    if (this.Disposing != null)
                    {
                        this.Disposing(this, EventArgs.Empty);
                    }
                    object obj = this.resourcesLock;
                    lock (obj)
                    {
                        GCHandle[] array = this.resources.ToArray();
                        this.resources.Clear();
                        foreach (GCHandle gchandle in array)
{
                            object target = gchandle.Target;
                            if (target != null)
{
                                (target as IDisposable).Dispose();
                            }
                        }
                    }
                    if (this.userVertexBuffer != IntPtr.Zero)
                    {
                        FNA3D.FNA3D_AddDisposeVertexBuffer(this.GLDevice, this.userVertexBuffer);
                    }
                    if (this.userIndexBuffer != IntPtr.Zero)
                    {
                        FNA3D.FNA3D_AddDisposeIndexBuffer(this.GLDevice, this.userIndexBuffer);
                    }
                    FNAPlatform.Free(this.effectStateChangesPtr);
                    FNA3D.FNA3D_DestroyDevice(this.GLDevice);
                }
            }
        }
References System.array, System.Collections.Generic.List< T >.Clear(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.Dispose(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.Disposing, Microsoft.Xna.Framework.Graphics.GraphicsDevice.effectStateChangesPtr, System.EventArgs.Empty, Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_AddDisposeIndexBuffer(), Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_AddDisposeVertexBuffer(), Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_DestroyDevice(), Microsoft.Xna.Framework.FNAPlatform.Free, Microsoft.Xna.Framework.Graphics.GraphicsDevice.GLDevice, Microsoft.Xna.Framework.Graphics.GraphicsDevice.IsDisposed, System.obj, Microsoft.Xna.Framework.Graphics.GraphicsDevice.resources, Microsoft.Xna.Framework.Graphics.GraphicsDevice.resourcesLock, System.Runtime.InteropServices.GCHandle.Target, System.Collections.Generic.List< T >.ToArray(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.userIndexBuffer, Microsoft.Xna.Framework.Graphics.GraphicsDevice.userVertexBuffer, and System.IntPtr.Zero.