Terraria Decompiled: Microsoft.Xna.Framework.Graphics.GraphicsDevice.PrepareUserIndexBuffer
PrepareUserIndexBuffer()
void Microsoft.Xna.Framework.Graphics.GraphicsDevice.PrepareUserIndexBuffer (IntPtr indexData, int numIndices, int indexOffset, int indexElementSizeInBytes) inline private
Definition at line 1246 of file GraphicsDevice.cs.
        {
            int num = numIndices * indexElementSizeInBytes;
            if (num > this.userIndexBufferSize)
            {
                if (this.userIndexBuffer != IntPtr.Zero)
                {
                    FNA3D.FNA3D_AddDisposeIndexBuffer(this.GLDevice, this.userIndexBuffer);
                }
                this.userIndexBuffer = FNA3D.FNA3D_GenIndexBuffer(this.GLDevice, 1, BufferUsage.WriteOnly, num);
                this.userIndexBufferSize = num;
            }
            FNA3D.FNA3D_SetIndexBufferData(this.GLDevice, this.userIndexBuffer, 0, indexData + indexOffset * indexElementSizeInBytes, num, SetDataOptions.Discard);
        }
References Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_AddDisposeIndexBuffer(), Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_GenIndexBuffer(), Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_SetIndexBufferData(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.GLDevice, Microsoft.Xna.Framework.Graphics.GraphicsDevice.userIndexBuffer, Microsoft.Xna.Framework.Graphics.GraphicsDevice.userIndexBufferSize, and System.IntPtr.Zero.
Referenced by Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives< T >(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives< T >(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives< T >(), and Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives< T >().