Terraria Decompiled: Microsoft.Xna.Framework.Graphics.GraphicsDevice.ApplySamplers
ApplySamplers()
void Microsoft.Xna.Framework.Graphics.GraphicsDevice.ApplySamplers () inline private
Definition at line 1174 of file GraphicsDevice.cs.
        {
            for (int i = 0; i < this.modifiedSamplers.Length; i++)
            {
                if (this.modifiedSamplers[i])
                {
                    this.modifiedSamplers[i] = false;
                    FNA3D.FNA3D_VerifySampler(this.GLDevice, i, (this.Textures[i] != null) ? this.Textures[i].texture : IntPtr.Zero, ref this.SamplerStates[i].state);
                }
            }
            for (int j = 0; j < this.modifiedVertexSamplers.Length; j++)
            {
                if (this.modifiedVertexSamplers[j])
                {
                    this.modifiedVertexSamplers[j] = false;
                    FNA3D.FNA3D_VerifyVertexSampler(this.GLDevice, j, (this.VertexTextures[j] != null) ? this.VertexTextures[j].texture : IntPtr.Zero, ref this.VertexSamplerStates[j].state);
                }
            }
        }
References Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_VerifySampler(), Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_VerifyVertexSampler(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.GLDevice, Microsoft.Xna.Framework.Graphics.GraphicsDevice.modifiedSamplers, Microsoft.Xna.Framework.Graphics.GraphicsDevice.modifiedVertexSamplers, Microsoft.Xna.Framework.Graphics.GraphicsDevice.SamplerStates, Microsoft.Xna.Framework.Graphics.GraphicsDevice.Textures, Microsoft.Xna.Framework.Graphics.GraphicsDevice.VertexSamplerStates, Microsoft.Xna.Framework.Graphics.GraphicsDevice.VertexTextures, and System.IntPtr.Zero.
Referenced by Microsoft.Xna.Framework.Graphics.GraphicsDevice.ApplyState(), and Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetRenderTargets().