Terraria Decompiled: Microsoft.Xna.Framework.Graphics.GraphicsDevice.GetBackBufferData< T >
GetBackBufferData< T >() [1/3]
void Microsoft.Xna.Framework.Graphics.GraphicsDevice.GetBackBufferData< T > (Rectangle? rect, T[] data, int startIndex, int elementCount) inline
Type Constraints
T : struct
Definition at line 800 of file GraphicsDevice.cs.
                                                                                                              : struct
        {
            int num;
            int num2;
            int width;
            int height;
            if (rect == null)
            {
                num = 0;
                num2 = 0;
                FNA3D.FNA3D_GetBackbufferSize(this.GLDevice, out width, out height);
            }
            else
            {
                num = rect.Value.X;
                num2 = rect.Value.Y;
                width = rect.Value.Width;
                height = rect.Value.Height;
            }
            int num3 = MarshalHelper.SizeOf<T>();
            Texture.ValidateGetDataFormat(FNA3D.FNA3D_GetBackbufferSurfaceFormat(this.GLDevice), num3);
            GCHandle gchandle = GCHandle.Alloc(data, GCHandleType.Pinned);
            FNA3D.FNA3D_ReadBackbuffer(this.GLDevice, num, num2, width, height, gchandle.AddrOfPinnedObject() + startIndex * num3, data.Length * num3);
            gchandle.Free();
        }
References System.Runtime.InteropServices.GCHandle.AddrOfPinnedObject(), System.Runtime.InteropServices.GCHandle.Alloc(), Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_GetBackbufferSize(), Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_GetBackbufferSurfaceFormat(), Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_ReadBackbuffer(), System.Runtime.InteropServices.GCHandle.Free(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.GLDevice, System.startIndex, and Microsoft.Xna.Framework.Graphics.Texture.ValidateGetDataFormat().