Terraria Decompiled: Microsoft.Xna.Framework.Graphics.GraphicsDevice.PrepareRenderTargetBindings
PrepareRenderTargetBindings()
static unsafe void Microsoft.Xna.Framework.Graphics.GraphicsDevice.PrepareRenderTargetBindings (FNA3D::FNA3D_RenderTargetBinding * b, RenderTargetBinding[] bindings) inline static package
Definition at line 1262 of file GraphicsDevice.cs.
        {
            int i = 0;
            while (i < bindings.Length)
            {
                Texture renderTarget = bindings[i].RenderTarget;
                IRenderTarget renderTarget2 = renderTarget as IRenderTarget;
                if (renderTarget is RenderTargetCube)
                {
                    b->type = 1;
                    b->data1 = renderTarget2.Width;
                    b->data2 = (int)bindings[i].CubeMapFace;
                }
                else
                {
                    b->type = 0;
                    b->data1 = renderTarget2.Width;
                    b->data2 = renderTarget2.Height;
                }
                b->levelCount = renderTarget2.LevelCount;
                b->multiSampleCount = renderTarget2.MultiSampleCount;
                b->texture = renderTarget.texture;
                b->colorBuffer = renderTarget2.ColorBuffer;
                i++;
                b++;
            }
        }
References Microsoft.Xna.Framework.Graphics.IRenderTarget.ColorBuffer, Microsoft.Xna.Framework.Graphics.IRenderTarget.Height, int, Microsoft.Xna.Framework.Graphics.IRenderTarget.LevelCount, Microsoft.Xna.Framework.Graphics.IRenderTarget.MultiSampleCount, Microsoft.Xna.Framework.Graphics.RenderTargetBinding.RenderTarget, Microsoft.Xna.Framework.Graphics.Texture.texture, and Microsoft.Xna.Framework.Graphics.IRenderTarget.Width.
Referenced by Microsoft.Xna.Framework.Media.BaseYUVPlayer.GL_popState(), Microsoft.Xna.Framework.Media.BaseYUVPlayer.GL_pushState(), and Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetRenderTargets().