Terraria Decompiled: Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawPrimitives
DrawPrimitives()
void Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawPrimitives (PrimitiveType primitiveType, int vertexStart, int primitiveCount) inline
Definition at line 1071 of file GraphicsDevice.cs.
        {
            this.ApplyState();
            this.PrepareVertexBindingArray(0);
            FNA3D.FNA3D_DrawPrimitives(this.GLDevice, primitiveType, vertexStart, primitiveCount);
        }
References Microsoft.Xna.Framework.Graphics.GraphicsDevice.ApplyState(), Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_DrawPrimitives(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.GLDevice, and Microsoft.Xna.Framework.Graphics.GraphicsDevice.PrepareVertexBindingArray().
Referenced by Microsoft.Xna.Framework.Media.VideoPlayerAV1.GetTexture(), and Microsoft.Xna.Framework.Media.VideoPlayerTheora.UpdateTexture().