Terraria Decompiled: Microsoft.Xna.Framework.Graphics.GraphicsDevice.PrepareVertexBindingArray
PrepareVertexBindingArray()
unsafe void Microsoft.Xna.Framework.Graphics.GraphicsDevice.PrepareVertexBindingArray (int baseVertex) inline private
Definition at line 1195 of file GraphicsDevice.cs.
        {
            fixed (FNA3D.FNA3D_VertexBufferBinding* ptr = &this.nativeBufferBindings[0])
            {
                FNA3D.FNA3D_VertexBufferBinding* ptr2 = ptr;
                for (int i = 0; i < this.vertexBufferCount; i++)
                {
                    VertexBuffer vertexBuffer = this.vertexBufferBindings[i].VertexBuffer;
                    ptr2[i].vertexBuffer = vertexBuffer.buffer;
                    ptr2[i].vertexDeclaration.vertexStride = vertexBuffer.VertexDeclaration.VertexStride;
                    ptr2[i].vertexDeclaration.elementCount = vertexBuffer.VertexDeclaration.elements.Length;
                    ptr2[i].vertexDeclaration.elements = vertexBuffer.VertexDeclaration.elementsPin;
                    ptr2[i].vertexOffset = this.vertexBufferBindings[i].VertexOffset;
                    ptr2[i].instanceFrequency = this.vertexBufferBindings[i].InstanceFrequency;
                }
                FNA3D.FNA3D_ApplyVertexBufferBindings(this.GLDevice, ptr2, this.vertexBufferCount, (this.vertexBuffersUpdated > false) ? 1 : 0, baseVertex);
            }
            this.vertexBuffersUpdated = false;
        }
References Microsoft.Xna.Framework.Graphics.VertexBuffer.buffer, Microsoft.Xna.Framework.Graphics.VertexDeclaration.elements, Microsoft.Xna.Framework.Graphics.VertexDeclaration.elementsPin, Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_ApplyVertexBufferBindings(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.GLDevice, Microsoft.Xna.Framework.Graphics.VertexBufferBinding.InstanceFrequency, Microsoft.Xna.Framework.Graphics.VertexBufferBinding.VertexBuffer, Microsoft.Xna.Framework.Graphics.GraphicsDevice.vertexBufferBindings, Microsoft.Xna.Framework.Graphics.GraphicsDevice.vertexBufferCount, Microsoft.Xna.Framework.Graphics.GraphicsDevice.vertexBuffersUpdated, Microsoft.Xna.Framework.Graphics.VertexBuffer.VertexDeclaration, Microsoft.Xna.Framework.Graphics.VertexBufferBinding.VertexOffset, and Microsoft.Xna.Framework.Graphics.VertexDeclaration.VertexStride.
Referenced by Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawIndexedPrimitives(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawInstancedPrimitives(), and Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawPrimitives().