Terraria Decompiled: Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetVertexBuffers
SetVertexBuffers()
void Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetVertexBuffers (params VertexBufferBinding[] vertexBuffers) inline
Definition at line 997 of file GraphicsDevice.cs.
        {
            if (vertexBuffers == null)
            {
                if (this.vertexBufferCount == 0)
                {
                    return;
                }
                for (int i = 0; i < this.vertexBufferCount; i++)
                {
                    this.vertexBufferBindings[i] = VertexBufferBinding.None;
                }
                this.vertexBufferCount = 0;
                this.vertexBuffersUpdated = true;
                return;
            }
            else
            {
                if (vertexBuffers.Length > this.vertexBufferBindings.Length)
                {
                    throw new ArgumentOutOfRangeException("vertexBuffers", string.Format("Max Vertex Buffers supported is {0}", this.vertexBufferBindings.Length));
                }
                int j;
                for (j = 0; j < vertexBuffers.Length; j++)
                {
                    if (this.vertexBufferBindings[j].VertexBuffer != vertexBuffers[j].VertexBuffer || this.vertexBufferBindings[j].VertexOffset != vertexBuffers[j].VertexOffset || this.vertexBufferBindings[j].InstanceFrequency != vertexBuffers[j].InstanceFrequency)
                    {
                        this.vertexBufferBindings[j] = vertexBuffers[j];
                        this.vertexBuffersUpdated = true;
                    }
                }
                if (vertexBuffers.Length < this.vertexBufferCount)
                {
                    while (j < this.vertexBufferCount)
                    {
                        this.vertexBufferBindings[j] = VertexBufferBinding.None;
                        j++;
                    }
                    this.vertexBuffersUpdated = true;
                }
                this.vertexBufferCount = vertexBuffers.Length;
                return;
            }
        }
References System.Format, Microsoft.Xna.Framework.Graphics.VertexBufferBinding.None, Microsoft.Xna.Framework.Graphics.GraphicsDevice.vertexBufferBindings, and Microsoft.Xna.Framework.Graphics.GraphicsDevice.vertexBufferCount.
Referenced by Terraria.Graphics.VertexStrip.DrawTrail(), Microsoft.Xna.Framework.Media.BaseYUVPlayer.GL_popState(), Microsoft.Xna.Framework.Media.BaseYUVPlayer.GL_pushState(), and Terraria.DataStructures.SpriteDrawBuffer.Unbind().