Terraria Decompiled: Microsoft.Xna.Framework.Graphics.GraphicsDevice.Clear
Clear() [3/3]
void Microsoft.Xna.Framework.Graphics.GraphicsDevice.Clear (Color color) inline
Definition at line 753 of file GraphicsDevice.cs.
        {
            this.Clear(ClearOptions.Target | ClearOptions.DepthBuffer | ClearOptions.Stencil, color.ToVector4(), this.Viewport.MaxDepth, 0);
        }
References System.Clear, and Microsoft.Xna.Framework.Color.ToVector4().
Referenced by Terraria.Graphics.Effects.FilterManager.BeginCapture(), Terraria.Graphics.Capture.CaptureCamera.BeginDrawCapture(), Terraria.Graphics.Capture.CaptureCamera.DrawTick(), Terraria.MapRenderer.DrawToMap(), Terraria.Graphics.Effects.FilterManager.EndCapture(), Terraria.GameContent.AnOutlinedDrawRenderTargetContent.HandleUseRequest(), Terraria.GameContent.PlayerQueenSlimeMountTextureContent.HandleUseRequest(), Terraria.GameContent.PlayerRainbowWingsTextureContent.HandleUseRequest(), Terraria.GameContent.PlayerTitaniumStormBuffTextureContent.HandleUseRequest(), Terraria.GameContent.Shaders.WaterShaderData.PreDraw(), Terraria.GameContent.TilePaintSystemV2.ARenderTargetHolder.PrepareTextureIfNecessary(), Terraria.GameContent.Shaders.WaterShaderData.StepLiquids(), Terraria.GameContent.UI.States.UIWorldGenDebug.UpdateAndDrawMap(), Terraria.Graphics.WorldSceneLayerTarget.UpdateContent(), and Terraria.GameContent.Drawing.HorizonHelper.UpdateSunVisibility().