Terraria Decompiled: Microsoft.Xna.Framework.Graphics.GraphicsDevice.PrepareUserVertexBuffer
PrepareUserVertexBuffer()
unsafe void Microsoft.Xna.Framework.Graphics.GraphicsDevice.PrepareUserVertexBuffer (IntPtr vertexData, int numVertices, int vertexOffset, VertexDeclaration vertexDeclaration) inline private
Definition at line 1216 of file GraphicsDevice.cs.
        {
            int num = numVertices * vertexDeclaration.VertexStride;
            int num2 = vertexOffset * vertexDeclaration.VertexStride;
            vertexDeclaration.GraphicsDevice = this;
            if (num > this.userVertexBufferSize)
            {
                if (this.userVertexBuffer != IntPtr.Zero)
                {
                    FNA3D.FNA3D_AddDisposeVertexBuffer(this.GLDevice, this.userVertexBuffer);
                }
                this.userVertexBuffer = FNA3D.FNA3D_GenVertexBuffer(this.GLDevice, 1, BufferUsage.WriteOnly, num);
                this.userVertexBufferSize = num;
            }
            FNA3D.FNA3D_SetVertexBufferData(this.GLDevice, this.userVertexBuffer, 0, vertexData + num2, num, 1, 1, SetDataOptions.Discard);
            fixed (FNA3D.FNA3D_VertexBufferBinding* ptr = &this.nativeBufferBindings[0])
            {
                FNA3D.FNA3D_VertexBufferBinding* ptr2 = ptr;
                ptr2->vertexBuffer = this.userVertexBuffer;
                ptr2->vertexDeclaration.vertexStride = vertexDeclaration.VertexStride;
                ptr2->vertexDeclaration.elementCount = vertexDeclaration.elements.Length;
                ptr2->vertexDeclaration.elements = vertexDeclaration.elementsPin;
                ptr2->vertexOffset = 0;
                ptr2->instanceFrequency = 0;
                FNA3D.FNA3D_ApplyVertexBufferBindings(this.GLDevice, ptr2, 1, 1, 0);
            }
            this.vertexBuffersUpdated = true;
        }
References Microsoft.Xna.Framework.Graphics.VertexDeclaration.elements, Microsoft.Xna.Framework.Graphics.VertexDeclaration.elementsPin, Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_AddDisposeVertexBuffer(), Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_ApplyVertexBufferBindings(), Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_GenVertexBuffer(), Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_SetVertexBufferData(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.GLDevice, Microsoft.Xna.Framework.Graphics.GraphicsDevice.userVertexBuffer, Microsoft.Xna.Framework.Graphics.GraphicsDevice.userVertexBufferSize, Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_VertexBufferBinding.vertexBuffer, Microsoft.Xna.Framework.Graphics.VertexDeclaration.VertexStride, and System.IntPtr.Zero.
Referenced by Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives< T >(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives< T >(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives< T >(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives< T >(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserPrimitives< T >(), and Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserPrimitives< T >().