Terraria Decompiled: Microsoft.Xna.Framework.Graphics.GraphicsDevice.ApplyState
ApplyState()
void Microsoft.Xna.Framework.Graphics.GraphicsDevice.ApplyState () inline private
Definition at line 1157 of file GraphicsDevice.cs.
        {
            if (this.currentBlend != this.nextBlend)
            {
                FNA3D.FNA3D_SetBlendState(this.GLDevice, ref this.nextBlend.state);
                this.currentBlend = this.nextBlend;
            }
            if (this.currentDepthStencil != this.nextDepthStencil)
            {
                FNA3D.FNA3D_SetDepthStencilState(this.GLDevice, ref this.nextDepthStencil.state);
                this.currentDepthStencil = this.nextDepthStencil;
            }
            FNA3D.FNA3D_ApplyRasterizerState(this.GLDevice, ref this.RasterizerState.state);
            this.ApplySamplers();
        }
References Microsoft.Xna.Framework.Graphics.GraphicsDevice.ApplySamplers(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.currentBlend, Microsoft.Xna.Framework.Graphics.GraphicsDevice.currentDepthStencil, Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_ApplyRasterizerState(), Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_SetBlendState(), Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_SetDepthStencilState(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.GLDevice, Microsoft.Xna.Framework.Graphics.GraphicsDevice.nextBlend, Microsoft.Xna.Framework.Graphics.GraphicsDevice.nextDepthStencil, Microsoft.Xna.Framework.Graphics.BlendState.state, Microsoft.Xna.Framework.Graphics.DepthStencilState.state, and Microsoft.Xna.Framework.Graphics.RasterizerState.state.
Referenced by Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawIndexedPrimitives(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawInstancedPrimitives(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawPrimitives(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives< T >(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives< T >(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives< T >(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives< T >(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserPrimitives< T >(), and Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserPrimitives< T >().