Terraria Decompiled: Microsoft.Xna.Framework.Graphics.GraphicsDevice.GraphicsDevice
GraphicsDevice() [1/2]
unsafe Microsoft.Xna.Framework.Graphics.GraphicsDevice.GraphicsDevice (GraphicsAdapter adapter, GraphicsProfile graphicsProfile, PresentationParameters presentationParameters) inline
Definition at line 537 of file GraphicsDevice.cs.
        {
            if (presentationParameters == null)
            {
                throw new ArgumentNullException("presentationParameters");
            }
            this.Adapter = adapter;
            this.PresentationParameters = presentationParameters;
            this.GraphicsProfile = graphicsProfile;
            this.PresentationParameters.MultiSampleCount = MathHelper.ClosestMSAAPower(this.PresentationParameters.MultiSampleCount);
            try
            {
                this.GLDevice = FNA3D.FNA3D_CreateDevice(ref this.PresentationParameters.parameters, 0);
            }
            catch (Exception ex)
            {
                throw new NoSuitableGraphicsDeviceException(ex.Message);
            }
            Mouse.INTERNAL_BackBufferWidth = this.PresentationParameters.BackBufferWidth;
            Mouse.INTERNAL_BackBufferHeight = this.PresentationParameters.BackBufferHeight;
            TouchPanel.DisplayWidth = this.PresentationParameters.BackBufferWidth;
            TouchPanel.DisplayHeight = this.PresentationParameters.BackBufferHeight;
            this.BlendState = BlendState.Opaque;
            this.DepthStencilState = DepthStencilState.Default;
            this.RasterizerState = RasterizerState.CullCounterClockwise;
            int num;
            int num2;
            FNA3D.FNA3D_GetMaxTextureSlots(this.GLDevice, out num, out num2);
            this.Textures = new TextureCollection(num, this.modifiedSamplers);
            this.SamplerStates = new SamplerStateCollection(num, this.modifiedSamplers);
            this.VertexTextures = new TextureCollection(num2, this.modifiedVertexSamplers);
            this.VertexSamplerStates = new SamplerStateCollection(num2, this.modifiedVertexSamplers);
            this.Viewport = new Viewport(this.PresentationParameters.Bounds);
            this.ScissorRectangle = this.Viewport.Bounds;
            this.PipelineCache = new PipelineCache(this);
            this.effectStateChangesPtr = FNAPlatform.Malloc(sizeof(Effect.MOJOSHADER_effectStateChanges));
            Effect.MOJOSHADER_effectStateChanges* ptr = (Effect.MOJOSHADER_effectStateChanges*)(void*)this.effectStateChangesPtr;
            ptr->render_state_change_count = 0U;
            ptr->sampler_state_change_count = 0U;
            ptr->vertex_sampler_state_change_count = 0U;
        }
References Microsoft.Xna.Framework.Graphics.PresentationParameters.BackBufferHeight, Microsoft.Xna.Framework.Graphics.PresentationParameters.BackBufferWidth, Microsoft.Xna.Framework.Graphics.PresentationParameters.Bounds, Microsoft.Xna.Framework.Graphics.Viewport.Bounds, Microsoft.Xna.Framework.MathHelper.ClosestMSAAPower(), Microsoft.Xna.Framework.Graphics.RasterizerState.CullCounterClockwise, Microsoft.Xna.Framework.Graphics.DepthStencilState.Default, Microsoft.Xna.Framework.Graphics.GraphicsDevice.effectStateChangesPtr, Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_CreateDevice(), Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_GetMaxTextureSlots(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.GLDevice, Microsoft.Xna.Framework.FNAPlatform.Malloc, System.Exception.Message, Microsoft.Xna.Framework.Graphics.GraphicsDevice.modifiedSamplers, Microsoft.Xna.Framework.Graphics.GraphicsDevice.modifiedVertexSamplers, Microsoft.Xna.Framework.Graphics.PresentationParameters.MultiSampleCount, Microsoft.Xna.Framework.Graphics.BlendState.Opaque, Microsoft.Xna.Framework.Graphics.PresentationParameters.parameters, Microsoft.Xna.Framework.Graphics.GraphicsDevice.PipelineCache, Microsoft.Xna.Framework.Input.U, and Microsoft.Xna.Framework.Graphics.GraphicsDevice.Viewport.