Terraria Decompiled: Microsoft.Xna.Framework.Graphics.GraphicsDevice.Reset
Reset() [3/3]
void Microsoft.Xna.Framework.Graphics.GraphicsDevice.Reset (PresentationParameters presentationParameters, GraphicsAdapter graphicsAdapter) inline
Definition at line 726 of file GraphicsDevice.cs.
        {
            if (presentationParameters == null)
            {
                throw new ArgumentNullException("presentationParameters");
            }
            this.PresentationParameters = presentationParameters;
            this.Adapter = graphicsAdapter;
            this.PresentationParameters.MultiSampleCount = FNA3D.FNA3D_GetMaxMultiSampleCount(this.GLDevice, this.PresentationParameters.BackBufferFormat, MathHelper.ClosestMSAAPower(this.PresentationParameters.MultiSampleCount));
            if (this.DeviceResetting != null)
            {
                this.DeviceResetting(this, EventArgs.Empty);
            }
            FNA3D.FNA3D_ResetBackbuffer(this.GLDevice, ref this.PresentationParameters.parameters);
            Mouse.INTERNAL_BackBufferWidth = this.PresentationParameters.BackBufferWidth;
            Mouse.INTERNAL_BackBufferHeight = this.PresentationParameters.BackBufferHeight;
            TouchPanel.DisplayWidth = this.PresentationParameters.BackBufferWidth;
            TouchPanel.DisplayHeight = this.PresentationParameters.BackBufferHeight;
            this.Viewport = new Viewport(0, 0, this.PresentationParameters.BackBufferWidth, this.PresentationParameters.BackBufferHeight);
            this.ScissorRectangle = new Rectangle(0, 0, this.PresentationParameters.BackBufferWidth, this.PresentationParameters.BackBufferHeight);
            if (this.DeviceReset != null)
            {
                this.DeviceReset(this, EventArgs.Empty);
            }
        }
References Microsoft.Xna.Framework.Graphics.PresentationParameters.BackBufferFormat, Microsoft.Xna.Framework.Graphics.PresentationParameters.BackBufferHeight, Microsoft.Xna.Framework.Graphics.PresentationParameters.BackBufferWidth, Microsoft.Xna.Framework.MathHelper.ClosestMSAAPower(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DeviceReset, Microsoft.Xna.Framework.Graphics.GraphicsDevice.DeviceResetting, System.EventArgs.Empty, Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_GetMaxMultiSampleCount(), Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_ResetBackbuffer(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.GLDevice, Microsoft.Xna.Framework.Graphics.PresentationParameters.parameters, and Microsoft.Xna.Framework.Graphics.GraphicsDevice.Viewport.