Terraria Decompiled: Terraria.GameContent.ShimmerTransforms.GetTransformToItem
GetTransformToItem()
static int Terraria.GameContent.ShimmerTransforms.GetTransformToItem (int type) inline static
Definition at line 67 of file ShimmerTransforms.cs.
        {
            int num = ItemID.Sets.ShimmerTransformToItem[type];
            if (num > 0)
            {
                return num;
            }
            if (ContentSamples.ItemsByType[type].createTile == 139)
            {
                int placeStyle = ContentSamples.ItemsByType[type].placeStyle;
                if (placeStyle == 90)
                {
                    return 5538;
                }
                if (placeStyle == 89)
                {
                    return 5579;
                }
                if (placeStyle == 97)
                {
                    return 5638;
                }
                if (placeStyle == 96)
                {
                    return 5639;
                }
                return 576;
            }
            else
            {
                if (type == 3461)
                {
                    return ShimmerTransforms.GetLunarBrickTransformFromMoonPhase(Main.GetMoonPhase());
                }
                return 0;
            }
        }
References Terraria.GameContent.ShimmerTransforms.GetLunarBrickTransformFromMoonPhase(), Terraria.Main.GetMoonPhase(), Terraria.ID.ContentSamples.ItemsByType, and Terraria.ID.ItemID.Sets.ShimmerTransformToItem.
Referenced by Terraria.Item.CanShimmer(), and Terraria.WorldItem.GetShimmered().