Terraria Decompiled: Terraria.GameContent.ShimmerTransforms.GetDecraftingRecipeIndex
GetDecraftingRecipeIndex()
static int Terraria.GameContent.ShimmerTransforms.GetDecraftingRecipeIndex (int type) inline static
Definition at line 12 of file ShimmerTransforms.cs.
        {
            int num = ItemID.Sets.IsCrafted[type];
            if (num < 0)
            {
                return -1;
            }
            if (WorldGen.crimson && ItemID.Sets.IsCraftedCrimson[type] >= 0)
            {
                return ItemID.Sets.IsCraftedCrimson[type];
            }
            if (!WorldGen.crimson && ItemID.Sets.IsCraftedCorruption[type] >= 0)
            {
                return ItemID.Sets.IsCraftedCorruption[type];
            }
            return num;
        }
References Terraria.WorldGen.crimson, Terraria.ID.ItemID.Sets.IsCrafted, Terraria.ID.ItemID.Sets.IsCraftedCorruption, and Terraria.ID.ItemID.Sets.IsCraftedCrimson.
Referenced by Terraria.Item.FindDecraftAmount(), Terraria.WorldItem.GetShimmered(), Terraria.GameContent.ShimmerTransforms.IsItemDecraftableAndIsDecraftUnlocked(), and Terraria.GameContent.ShimmerTransforms.IsItemDecraftLocked().