Terraria Decompiled: System.Text.UTF7Encoding.GetBytes
GetBytes() [4/4]
unsafe override int System.Text.UTF7Encoding.GetBytes (string s, int charIndex, int charCount, byte[] bytes, int byteIndex) inline virtual
Reimplemented from System.Text.Encoding.
Definition at line 140 of file UTF7Encoding.cs.
        {
            if (s == null || bytes == null)
            {
                throw new ArgumentNullException((s == null) ? "s" : "bytes", "Array cannot be null.");
            }
            if (charIndex < 0 || charCount < 0)
            {
                throw new ArgumentOutOfRangeException((charIndex < 0) ? "charIndex" : "charCount", "Non-negative number required.");
            }
            if (s.Length - charIndex < charCount)
            {
                throw new ArgumentOutOfRangeException("s", "Index and count must refer to a location within the string.");
            }
            if (byteIndex < 0 || byteIndex > bytes.Length)
            {
                throw new ArgumentOutOfRangeException("byteIndex", "Index was out of range. Must be non-negative and less than the size of the collection.");
            }
            int num = bytes.Length - byteIndex;
            char* ptr = s;
            if (ptr != null)
            {
                ptr += RuntimeHelpers.OffsetToStringData / 2;
            }
            fixed (byte* reference = MemoryMarshal.GetReference<byte>(bytes))
            {
                byte* ptr2 = reference;
                return this.GetBytes(ptr + charIndex, charCount, ptr2 + byteIndex, num, null);
            }
        }
References System.Text.UTF7Encoding.GetBytes(), and System.s.
Referenced by System.Text.UTF7Encoding.GetByteCount(), System.Text.UTF7Encoding.GetBytes(), System.Text.UTF7Encoding.GetBytes(), and System.Text.UTF7Encoding.GetBytes().