Terraria Decompiled: System.Text.UTF7Encoding.GetChars
GetChars() [2/3]
unsafe override int System.Text.UTF7Encoding.GetChars (byte * bytes, int byteCount, char * chars, int charCount, DecoderNLS baseDecoder) inline package virtual
Reimplemented from System.Text.Encoding.
Definition at line 477 of file UTF7Encoding.cs.
        {
            UTF7Encoding.Decoder decoder = (UTF7Encoding.Decoder)baseDecoder;
            Encoding.EncodingCharBuffer encodingCharBuffer = new Encoding.EncodingCharBuffer(this, decoder, chars, charCount, bytes, byteCount);
            int num = 0;
            int num2 = -1;
            bool flag = false;
            if (decoder != null)
            {
                num = decoder.bits;
                num2 = decoder.bitCount;
                flag = decoder.firstByte;
            }
            if (num2 >= 16)
            {
                if (!encodingCharBuffer.AddChar((char)((num >> num2 - 16) & 65535)))
                {
                    base.ThrowCharsOverflow(decoder, true);
                }
                num2 -= 16;
            }
            while (encodingCharBuffer.MoreData)
            {
                byte nextByte = encodingCharBuffer.GetNextByte();
                int num3;
                if (num2 >= 0)
                {
                    sbyte b;
                    if (nextByte < 128 && (b = this._base64Values[(int)nextByte]) >= 0)
                    {
                        flag = false;
                        num = (num << 6) | (int)((byte)b);
                        num2 += 6;
                        if (num2 < 16)
{
                            continue;
                        }
                        num3 = (num >> num2 - 16) & 65535;
                        num2 -= 16;
                    }
                    else
                    {
                        num2 = -1;
                        if (nextByte != 45)
{
                            if (!encodingCharBuffer.Fallback(nextByte))
{
                                break;
                            }
                            continue;
                        }
                        else
{
                            if (!flag)
{
                                continue;
                            }
                            num3 = 43;
                        }
                    }
                }
                else
                {
                    if (nextByte == 43)
                    {
                        num2 = 0;
                        flag = true;
                        continue;
                    }
                    if (nextByte >= 128)
                    {
                        if (!encodingCharBuffer.Fallback(nextByte))
{
                            break;
                        }
                        continue;
                    }
                    else
                    {
                        num3 = (int)nextByte;
                    }
                }
                if (num3 >= 0 && !encodingCharBuffer.AddChar((char)num3))
                {
                    if (num2 >= 0)
                    {
                        encodingCharBuffer.AdjustBytes(1);
                        num2 += 16;
                        break;
                    }
                    break;
                }
            }
            if (chars != null && decoder != null)
            {
                if (decoder.MustFlush)
                {
                    decoder.bits = 0;
                    decoder.bitCount = -1;
                    decoder.firstByte = false;
                }
                else
                {
                    decoder.bits = num;
                    decoder.bitCount = num2;
                    decoder.firstByte = flag;
                }
                decoder._bytesUsed = encodingCharBuffer.BytesUsed;
            }
            return encodingCharBuffer.Count;
        }
References System.Text.UTF7Encoding._base64Values, System.Text.Encoding.EncodingCharBuffer.AddChar(), System.Text.Encoding.EncodingCharBuffer.AdjustBytes(), System.Text.UTF7Encoding.Decoder.bitCount, System.Text.UTF7Encoding.Decoder.bits, System.Text.Encoding.EncodingCharBuffer.BytesUsed, System.Text.Encoding.EncodingCharBuffer.Count, System.Text.Encoding.EncodingCharBuffer.Fallback(), System.Text.UTF7Encoding.Decoder.firstByte, System.Text.Encoding.EncodingCharBuffer.GetNextByte(), int, System.Text.Encoding.EncodingCharBuffer.MoreData, and System.Text.DecoderNLS.MustFlush.