Terraria Decompiled: System.DateTime.DateToTicks
DateToTicks()
static long System.DateTime.DateToTicks (int year, int month, int day) inline static private
Definition at line 380 of file DateTime.cs.
        {
            if (year >= 1 && year <= 9999 && month >= 1 && month <= 12)
            {
                int[] array = (DateTime.IsLeapYear(year) ? DateTime.s_daysToMonth366 : DateTime.s_daysToMonth365);
                if (day >= 1 && day <= array[month] - array[month - 1])
                {
                    int num = year - 1;
                    return (long)(num * 365 + num / 4 - num / 100 + num / 400 + array[month - 1] + day - 1) * 864000000000L;
                }
            }
            throw new ArgumentOutOfRangeException(null, "Year, Month, and Day parameters describe an un-representable DateTime.");
        }
References System.array, System.DateTime.IsLeapYear(), System.L, and System.DateTime.s_daysToMonth365.
Referenced by System.DateTime.AddMonths(), System.DateTime.DateTime(), System.DateTime.DateTime(), System.DateTime.DateTime(), System.DateTime.DateTime(), System.DateTime.DateTime(), and System.DateTime.TryCreate().