Terraria Decompiled: System.DateTime.ToBinary
ToBinary()
long System.DateTime.ToBinary () inline
Definition at line 550 of file DateTime.cs.
        {
            if (this.Kind == DateTimeKind.Local)
            {
                TimeSpan localUtcOffset = TimeZoneInfo.GetLocalUtcOffset(this, TimeZoneInfoOptions.NoThrowOnInvalidTime);
                long num = this.Ticks - localUtcOffset.Ticks;
                if (num < 0L)
                {
                    num = 4611686018427387904L + num;
                }
                return num | long.MinValue;
            }
            return (long)this._dateData;
        }
References System.DateTime._dateData, System.TimeZoneInfo.GetLocalUtcOffset(), System.DateTime.Kind, System.L, and System.TimeSpan.Ticks.
Referenced by Terraria.Player.AdjustRespawnTimerForWorldJoining(), Terraria.Player.LoadPlayer(), Terraria.IO.WorldFile.SaveWorldHeader(), and Terraria.Player.Serialize().