Terraria Decompiled: System.DateTime.AddMonths
AddMonths()
DateTime System.DateTime.AddMonths (int months) inline
Definition at line 283 of file DateTime.cs.
        {
            if (months < -120000 || months > 120000)
            {
                throw new ArgumentOutOfRangeException("months", "Months value must be between +/-120000.");
            }
            int num;
            int num2;
            int num3;
            this.GetDatePart(out num, out num2, out num3);
            int num4 = num2 - 1 + months;
            if (num4 >= 0)
            {
                num2 = num4 % 12 + 1;
                num += num4 / 12;
            }
            else
            {
                num2 = 12 + (num4 + 1) % 12;
                num += (num4 - 11) / 12;
            }
            if (num < 1 || num > 9999)
            {
                throw new ArgumentOutOfRangeException("months", "The added or subtracted value results in an un-representable DateTime.");
            }
            int num5 = DateTime.DaysInMonth(num, num2);
            if (num3 > num5)
            {
                num3 = num5;
            }
            return new DateTime((ulong)((DateTime.DateToTicks(num, num2, num3) + this.InternalTicks % 864000000000L) | (long)this.InternalKind));
        }
References System.DateTime.DateTime(), System.DateTime.DateToTicks(), System.DateTime.DaysInMonth(), System.DateTime.GetDatePart(), and System.L.
Referenced by System.DateTimeOffset.AddMonths(), and System.DateTime.AddYears().