Terraria Decompiled: System.DateTime.AddTicks
AddTicks()
DateTime System.DateTime.AddTicks (long value) inline
Definition at line 323 of file DateTime.cs.
        {
            long internalTicks = this.InternalTicks;
            if (value > 3155378975999999999L - internalTicks || value < 0L - internalTicks)
            {
                throw new ArgumentOutOfRangeException("value", "The added or subtracted value results in an un-representable DateTime.");
            }
            return new DateTime((ulong)((internalTicks + value) | (long)this.InternalKind));
        }
References System.DateTime.DateTime(), System.DateTime.InternalKind, System.DateTime.InternalTicks, System.L, and System.value.
Referenced by System.DateTime.Add(), System.DateTime.Add(), System.DateTimeOffset.AddTicks(), Newtonsoft.Json.Utilities.DateTimeUtils.CreateDateTime(), System.TimeZoneInfo.GetIsDaylightSavingsFromUtc(), System.DateTimeParse.ParseISO8601(), System.DateTimeParse.TryParse(), and System.TimeZoneInfo.TZif_GenerateAdjustmentRule().