Terraria Decompiled: System.DateTime.ToString
ToString() [1/4]
override string System.DateTime.ToString () inline
Definition at line 1056 of file DateTime.cs.
        {
            return DateTimeFormat.Format(this, null, null);
        }
References System.DateTimeFormat.Format().
Referenced by Ionic.Zip.ZipFile._InternalExtractAll(), Newtonsoft.Json.Converters.XmlNodeConverter.ConvertTokenToXmlValue(), Terraria.Testing.PacketHistory.CreateDumpFileName(), Terraria.Utilities.CrashDump.CreateDumpName(), Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIWorldListItem.DrawSelf(), Terraria.Player.DropTombstone(), System.Security.Cryptography.X509Certificates.X509Certificate.FormatDate(), Mono.Security.ASN1Convert.FromDateTime(), System.Security.Cryptography.X509Certificates.X509Certificate.GetEffectiveDateString(), System.Security.Cryptography.X509Certificates.X509Certificate.GetExpirationDateString(), ReLogic.OS.Linux.PathService.MoveToRecycleBin(), System.Runtime.Remoting.Metadata.W3cXsd2001.SoapDate.ToString(), System.Runtime.Remoting.Metadata.W3cXsd2001.SoapDay.ToString(), System.Runtime.Remoting.Metadata.W3cXsd2001.SoapMonth.ToString(), System.Runtime.Remoting.Metadata.W3cXsd2001.SoapMonthDay.ToString(), System.Runtime.Remoting.Metadata.W3cXsd2001.SoapTime.ToString(), System.Runtime.Remoting.Metadata.W3cXsd2001.SoapYear.ToString(), System.Runtime.Remoting.Metadata.W3cXsd2001.SoapYearMonth.ToString(), Newtonsoft.Json.Serialization.MemoryTraceWriter.Trace(), Newtonsoft.Json.Converters.IsoDateTimeConverter.WriteJson(), and Newtonsoft.Json.JsonTextWriter.WriteValue().