Terraria Decompiled: System.DateTime.FromBinaryRaw
FromBinaryRaw()
static DateTime System.DateTime.FromBinaryRaw (long dateData) inline static package
Definition at line 494 of file DateTime.cs.
        {
            long num = dateData & 4611686018427387903L;
            if (num < 0L || num > 3155378975999999999L)
            {
                throw new ArgumentException("The binary data must result in a DateTime with ticks between DateTime.MinValue.Ticks and DateTime.MaxValue.Ticks.", "dateData");
            }
            return new DateTime((ulong)dateData);
        }
References System.DateTime.DateTime(), and System.L.
Referenced by System.DateTime.FromBinary(), and System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadDateTime().