Terraria Decompiled: System.DateTime.MinValue
MinValue
readonly DateTime System.DateTime.MinValue = new DateTime(0L, DateTimeKind.Unspecified) static
Definition at line 1513 of file DateTime.cs.
Referenced by System.DateTimeParse.AdjustTimeZoneToLocal(), CsvHelper.TypeConversion.DateTimeConverter.ConvertFromString(), System.TimeZoneInfo.ConvertToFromUtc(), System.TimeZoneInfo.ConvertUtcToTimeZone(), System.CurrentSystemTimeZone.CreateDaylightChanges(), System.DateTime.FromBinary(), System.TimeZoneInfo.GetIsDaylightSavingsFromUtc(), System.Security.Cryptography.X509Certificates.X509Certificate.GetNotAfter(), System.Security.Cryptography.X509Certificates.X509Certificate.GetNotBefore(), System.TimeZoneInfo.GetUtcOffsetFromUtc(), Microsoft.Xna.Framework.Input.Touch.GestureDetector.OnReleased(), Microsoft.Xna.Framework.Input.Touch.GestureDetector.OnUpdate(), System.Security.Cryptography.X509Certificates.X509Certificate.Reset(), System.IO.MonoIO.SetFileTime(), System.Convert.ToDateTime(), System.Convert.ToDateTime(), Newtonsoft.Json.Utilities.DateTimeUtils.ToUniversalTicks(), System.DateTime.TryCreate(), System.DateTimeParse.TryParse(), System.DateTimeParse.TryParse(), Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTimeIso(), System.DateTimeParse.TryParseExact(), System.DateTimeParse.TryParseExact(), System.DateTimeParse.TryParseExactMultiple(), System.DateTimeParse.TryParseExactMultiple(), System.Globalization.Calendar.TryToDateTime(), System.Globalization.GregorianCalendar.TryToDateTime(), System.TimeZoneInfo.TZif_GenerateAdjustmentRule(), System.TimeZoneInfo.TZif_UnixTimeToDateTime(), System.TimeZoneInfo.AdjustmentRule.ValidateAdjustmentRule(), and Newtonsoft.Json.Utilities.DateTimeUtils.WriteDateTimeString().