Terraria Decompiled: System.DateTime.DateTime
DateTime() [14/15]
System.DateTime.DateTime (SerializationInfo info, StreamingContext context) inline private
Definition at line 174 of file DateTime.cs.
        {
            if (info == null)
            {
                throw new ArgumentNullException("info");
            }
            bool flag = false;
            bool flag2 = false;
            long num = 0L;
            ulong num2 = 0UL;
            SerializationInfoEnumerator enumerator = info.GetEnumerator();
            while (enumerator.MoveNext())
            {
                string name = enumerator.Name;
                if (!(name == "ticks"))
                {
                    if (name == "dateData")
                    {
                        num2 = Convert.ToUInt64(enumerator.Value, CultureInfo.InvariantCulture);
                        flag2 = true;
                    }
                }
                else
                {
                    num = Convert.ToInt64(enumerator.Value, CultureInfo.InvariantCulture);
                    flag = true;
                }
            }
            if (flag2)
            {
                this._dateData = num2;
            }
            else
            {
                if (!flag)
                {
                    throw new SerializationException("Invalid serialized DateTime data. Unable to find 'ticks' or 'dateData'.");
                }
                this._dateData = (ulong)num;
            }
            long internalTicks = this.InternalTicks;
            if (internalTicks < 0L || internalTicks > 3155378975999999999L)
            {
                throw new SerializationException("Invalid serialized DateTime data. Ticks must be between DateTime.MinValue.Ticks and DateTime.MaxValue.Ticks.");
            }
        }
References System.info, System.DateTime.InternalTicks, System.Globalization.CultureInfo.InvariantCulture, System.L, System.Runtime.Serialization.SerializationInfoEnumerator.MoveNext(), System.name, System.Runtime.Serialization.SerializationInfoEnumerator.Name, System.Convert.ToInt64(), System.Convert.ToUInt64(), and System.Runtime.Serialization.SerializationInfoEnumerator.Value.