Terraria Decompiled: Microsoft.Xna.Framework.Content.LzxDecoder.BitBuffer.ReadBits
ReadBits()
uint Microsoft.Xna.Framework.Content.LzxDecoder.BitBuffer.ReadBits (byte bits) inline
Definition at line 677 of file LzxDecoder.cs.
            {
                uint num = 0U;
                if (bits > 0)
                {
                    this.EnsureBits(bits);
                    num = this.PeekBits(bits);
                    this.RemoveBits(bits);
                }
                return num;
            }
References Microsoft.Xna.Framework.Content.LzxDecoder.BitBuffer.EnsureBits(), Microsoft.Xna.Framework.Content.LzxDecoder.BitBuffer.PeekBits(), Microsoft.Xna.Framework.Content.LzxDecoder.BitBuffer.RemoveBits(), and System.U.
Referenced by Microsoft.Xna.Framework.Content.LzxDecoder.Decompress().