Terraria Decompiled: Microsoft.Xna.Framework.Content.LzxDecoder.BitBuffer.EnsureBits
EnsureBits()
void Microsoft.Xna.Framework.Content.LzxDecoder.BitBuffer.EnsureBits (byte bits) inline
Definition at line 652 of file LzxDecoder.cs.
            {
                while (this.bitsleft < bits)
                {
                    int num = (int)((byte)this.byteStream.ReadByte());
                    int num2 = (int)((byte)this.byteStream.ReadByte());
                    this.buffer |= (uint)((uint)((num2 << 8) | num) << (int)(16 - this.bitsleft));
                    this.bitsleft += 16;
                }
            }
References Microsoft.Xna.Framework.Content.LzxDecoder.BitBuffer.bitsleft, Microsoft.Xna.Framework.Content.LzxDecoder.BitBuffer.byteStream, int, and System.IO.Stream.ReadByte().
Referenced by Microsoft.Xna.Framework.Content.LzxDecoder.Decompress(), and Microsoft.Xna.Framework.Content.LzxDecoder.BitBuffer.ReadBits().