Terraria Decompiled: Terraria.DataStructures.PlayerGetItemLogger.Add
Add()
void Terraria.DataStructures.PlayerGetItemLogger.Add (Item[] array, int slot, int itemSlotContext, int stack) inline
Definition at line 16 of file PlayerGetItemLogger.cs.
        {
            if (!this._enabled)
            {
                return;
            }
            this.Entries.Add(new PlayerGetItemLogger.GetItemLoggerEntry
            {
                TargetArray = array,
                TargetSlot = slot,
                TargetItemSlotContext = itemSlotContext,
                Stack = stack
            });
        }
References Terraria.DataStructures.PlayerGetItemLogger._enabled, and Terraria.DataStructures.PlayerGetItemLogger.Entries.
Referenced by Terraria.Player.FillAmmo(), Terraria.Player.GetItem_FillEmptyInventorySlot(), Terraria.Player.GetItem_FillEmptyInventorySlot_VoidBag(), Terraria.Player.GetItem_FillIntoOccupiedSlot(), and Terraria.Player.GetItem_FillIntoOccupiedSlot_VoidBag().