Terraria Decompiled: System.Runtime.Remoting.Messaging.ClientContextReplySink.SyncProcessMessage
SyncProcessMessage()
IMessage System.Runtime.Remoting.Messaging.ClientContextReplySink.SyncProcessMessage (IMessage msg) inline
Implements System.Runtime.Remoting.Messaging.IMessageSink.
Definition at line 17 of file ClientContextReplySink.cs.
        {
            Context.NotifyGlobalDynamicSinks(false, msg, true, true);
            this._context.NotifyDynamicSinks(false, msg, true, true);
            return this._replySink.SyncProcessMessage(msg);
        }
References System.Runtime.Remoting.Messaging.ClientContextReplySink._context, System.Runtime.Remoting.Messaging.ClientContextReplySink._replySink, System.Runtime.Remoting.Contexts.Context.NotifyDynamicSinks(), System.Runtime.Remoting.Contexts.Context.NotifyGlobalDynamicSinks(), and System.Runtime.Remoting.Messaging.IMessageSink.SyncProcessMessage().