Terraria Decompiled: System.Reflection.Emit.ParameterBuilder.SetCustomAttribute
SetCustomAttribute() [2/2]
void System.Reflection.Emit.ParameterBuilder.SetCustomAttribute (CustomAttributeBuilder customBuilder) inline
Definition at line 130 of file ParameterBuilder.cs.
        {
            string fullName = customBuilder.Ctor.ReflectedType.FullName;
            if (fullName == "System.Runtime.InteropServices.InAttribute")
            {
                this.attrs |= ParameterAttributes.In;
                return;
            }
            if (fullName == "System.Runtime.InteropServices.OutAttribute")
            {
                this.attrs |= ParameterAttributes.Out;
                return;
            }
            if (fullName == "System.Runtime.InteropServices.OptionalAttribute")
            {
                this.attrs |= ParameterAttributes.Optional;
                return;
            }
            if (fullName == "System.Runtime.InteropServices.MarshalAsAttribute")
            {
                this.attrs |= ParameterAttributes.HasFieldMarshal;
                this.marshal_info = CustomAttributeBuilder.get_umarshal(customBuilder, false);
                return;
            }
            if (fullName == "System.Runtime.InteropServices.DefaultParameterValueAttribute")
            {
                CustomAttributeBuilder.CustomAttributeInfo customAttributeInfo = CustomAttributeBuilder.decode_cattr(customBuilder);
                this.SetConstant(customAttributeInfo.ctorArgs[0]);
                return;
            }
            if (this.cattrs != null)
            {
                CustomAttributeBuilder[] array = new CustomAttributeBuilder[this.cattrs.Length + 1];
                this.cattrs.CopyTo(array, 0);
                array[this.cattrs.Length] = customBuilder;
                this.cattrs = array;
                return;
            }
            this.cattrs = new CustomAttributeBuilder[1];
            this.cattrs[0] = customBuilder;
        }
References System.array, System.Reflection.Emit.ParameterBuilder.cattrs, System.Reflection.Emit.CustomAttributeBuilder.Ctor, System.Reflection.Emit.CustomAttributeBuilder.CustomAttributeInfo.ctorArgs, System.Reflection.Emit.CustomAttributeBuilder.decode_cattr(), System.Type.FullName, System.Reflection.Emit.CustomAttributeBuilder.get_umarshal(), System.Reflection.MemberInfo.ReflectedType, and System.Reflection.Emit.ParameterBuilder.SetConstant().
Referenced by System.Reflection.Emit.ParameterBuilder.SetCustomAttribute().