Terraria Decompiled: System.Runtime.Remoting.Activation.ActivationServices.CreateConstructionCall
CreateConstructionCall()
static ConstructionCall System.Runtime.Remoting.Activation.ActivationServices.CreateConstructionCall (Type type, string activationUrl, object[] activationAttributes) inline static
Definition at line 97 of file ActivationServices.cs.
        {
            ConstructionCall constructionCall = new ConstructionCall(type);
            if (!type.IsContextful)
            {
                constructionCall.Activator = new AppDomainLevelActivator(activationUrl, ActivationServices.ConstructionActivator);
                constructionCall.IsContextOk = false;
                return constructionCall;
            }
            IActivator activator = ActivationServices.ConstructionActivator;
            activator = new ContextLevelActivator(activator);
            ArrayList arrayList = new ArrayList();
            if (activationAttributes != null)
            {
                arrayList.AddRange(activationAttributes);
            }
            bool flag = activationUrl == ChannelServices.CrossContextUrl;
            Context currentContext = Thread.CurrentContext;
            if (flag)
            {
                using (IEnumerator enumerator = arrayList.GetEnumerator())
                {
                    while (enumerator.MoveNext())
                    {
                        if (!((IContextAttribute)enumerator.Current).IsContextOK(currentContext, constructionCall))
{
                            flag = false;
                            break;
                        }
                    }
                }
            }
            foreach (object obj in type.GetCustomAttributes(true))
            {
                if (obj is IContextAttribute)
                {
                    flag = flag && ((IContextAttribute)obj).IsContextOK(currentContext, constructionCall);
                    arrayList.Add(obj);
                }
            }
            if (!flag)
            {
                constructionCall.SetActivationAttributes(arrayList.ToArray());
                foreach (object obj2 in arrayList)
                {
                    ((IContextAttribute)obj2).GetPropertiesForNewContext(constructionCall);
                }
            }
            if (activationUrl != ChannelServices.CrossContextUrl)
            {
                activator = new AppDomainLevelActivator(activationUrl, activator);
            }
            constructionCall.Activator = activator;
            constructionCall.IsContextOk = flag;
            return constructionCall;
        }
References System.Collections.ArrayList.AddRange(), System.Runtime.Remoting.Activation.ActivationServices.ConstructionActivator, System.Runtime.Remoting.Channels.ChannelServices.CrossContextUrl, System.Collections.IEnumerator.Current, System.Threading.Thread.CurrentContext, System.Collections.ArrayList.GetEnumerator(), System.Type.IsContextful, System.Collections.IEnumerator.MoveNext(), and System.obj.
Referenced by System.Runtime.Remoting.Proxies.RemotingProxy.RemotingProxy().