Terraria Decompiled: System.Runtime.Remoting.Activation.ActivationServices.CreateInstanceFromMessage
CreateInstanceFromMessage()
static IMessage System.Runtime.Remoting.Activation.ActivationServices.CreateInstanceFromMessage (IConstructionCallMessage ctorCall) inline static
Definition at line 155 of file ActivationServices.cs.
        {
            object obj = ActivationServices.AllocateUninitializedClassInstance(ctorCall.ActivationType);
            ServerIdentity serverIdentity = (ServerIdentity)RemotingServices.GetMessageTargetIdentity(ctorCall);
            serverIdentity.AttachServerObject((MarshalByRefObject)obj, Thread.CurrentContext);
            ConstructionCall constructionCall = ctorCall as ConstructionCall;
            if (ctorCall.ActivationType.IsContextful && constructionCall != null && constructionCall.SourceProxy != null)
            {
                constructionCall.SourceProxy.AttachIdentity(serverIdentity);
                RemotingServices.InternalExecuteMessage((MarshalByRefObject)constructionCall.SourceProxy.GetTransparentProxy(), ctorCall);
            }
            else
            {
                ctorCall.MethodBase.Invoke(obj, ctorCall.Args);
            }
            return new ConstructionResponse(obj, null, ctorCall);
        }
References System.Runtime.Remoting.Activation.IConstructionCallMessage.ActivationType, System.Runtime.Remoting.Activation.ActivationServices.AllocateUninitializedClassInstance(), System.Runtime.Remoting.Messaging.IMethodMessage.Args, System.Runtime.Remoting.Proxies.RemotingProxy.AttachIdentity(), System.Runtime.Remoting.ServerIdentity.AttachServerObject(), System.Threading.Thread.CurrentContext, System.Runtime.Remoting.RemotingServices.GetMessageTargetIdentity(), System.Runtime.Remoting.Proxies.RealProxy.GetTransparentProxy(), System.Runtime.Remoting.RemotingServices.InternalExecuteMessage(), System.Type.IsContextful, System.Runtime.Remoting.Messaging.IMethodMessage.MethodBase, System.obj, and System.Runtime.Remoting.Messaging.ConstructionCall.SourceProxy.
Referenced by System.Runtime.Remoting.Messaging.ServerContextTerminatorSink.SyncProcessMessage().