Terraria Decompiled: System.Runtime.Remoting.Activation.ActivationServices.CreateProxyFromAttributes
CreateProxyFromAttributes()
static object System.Runtime.Remoting.Activation.ActivationServices.CreateProxyFromAttributes (Type type, object[] activationAttributes) inline static
Definition at line 66 of file ActivationServices.cs.
        {
            string text = null;
            foreach (object obj in activationAttributes)
            {
                if (!(obj is IContextAttribute))
                {
                    throw new RemotingException("Activation attribute does not implement the IContextAttribute interface");
                }
                if (obj is UrlAttribute)
                {
                    text = ((UrlAttribute)obj).UrlValue;
                }
            }
            if (text != null)
            {
                return RemotingServices.CreateClientProxy(type, text, activationAttributes);
            }
            ActivatedClientTypeEntry activatedClientTypeEntry = RemotingConfiguration.IsRemotelyActivatedClientType(type);
            if (activatedClientTypeEntry != null)
            {
                return RemotingServices.CreateClientProxy(activatedClientTypeEntry, activationAttributes);
            }
            if (type.IsContextful)
            {
                return RemotingServices.CreateClientProxyForContextBound(type, activationAttributes);
            }
            return null;
        }
References System.Runtime.Remoting.RemotingServices.CreateClientProxy(), System.Runtime.Remoting.RemotingServices.CreateClientProxyForContextBound(), System.Runtime.Remoting.RemotingConfiguration.IsRemotelyActivatedClientType(), System.obj, and System.text.
Referenced by System.RuntimeType.ActivationCreateInstance().