Terraria Decompiled: System.Runtime.Remoting.Activation.ActivationServices.Activate
Activate()
static IMessage System.Runtime.Remoting.Activation.ActivationServices.Activate (RemotingProxy proxy, ConstructionCall ctorCall) inline static
Definition at line 30 of file ActivationServices.cs.
        {
            ctorCall.SourceProxy = proxy;
            IMessage message;
            if (Thread.CurrentContext.HasExitSinks && !ctorCall.IsContextOk)
            {
                message = Thread.CurrentContext.GetClientContextSinkChain().SyncProcessMessage(ctorCall);
            }
            else
            {
                message = ActivationServices.RemoteActivate(ctorCall);
            }
            if (message is IConstructionReturnMessage && ((IConstructionReturnMessage)message).Exception == null && proxy.ObjectIdentity == null)
            {
                Identity messageTargetIdentity = RemotingServices.GetMessageTargetIdentity(ctorCall);
                proxy.AttachIdentity(messageTargetIdentity);
            }
            return message;
        }
References System.Runtime.Remoting.Proxies.RemotingProxy.AttachIdentity(), System.Threading.Thread.CurrentContext, System.Runtime.Remoting.Contexts.Context.GetClientContextSinkChain(), System.Runtime.Remoting.RemotingServices.GetMessageTargetIdentity(), System.Runtime.Remoting.Contexts.Context.HasExitSinks, System.Runtime.Remoting.Messaging.ConstructionCall.IsContextOk, System.Runtime.Remoting.Proxies.RealProxy.ObjectIdentity, System.Runtime.Remoting.Activation.ActivationServices.RemoteActivate(), and System.Runtime.Remoting.Messaging.IMessageSink.SyncProcessMessage().
Referenced by System.Runtime.Remoting.Proxies.RemotingProxy.ActivateRemoteObject().