Terraria Decompiled: System.ThrowHelper.GetArraySegmentCtorValidationFailedException
GetArraySegmentCtorValidationFailedException()
static Exception System.ThrowHelper.GetArraySegmentCtorValidationFailedException (Array array, int offset, int count) inline static private
Definition at line 522 of file ThrowHelper.cs.
        {
            if (array == null)
            {
                return ThrowHelper.GetArgumentNullException(ExceptionArgument.array);
            }
            if (offset < 0)
            {
                return ThrowHelper.GetArgumentOutOfRangeException(ExceptionArgument.offset, ExceptionResource.ArgumentOutOfRange_NeedNonNegNum);
            }
            if (count < 0)
            {
                return ThrowHelper.GetArgumentOutOfRangeException(ExceptionArgument.count, ExceptionResource.ArgumentOutOfRange_NeedNonNegNum);
            }
            return ThrowHelper.GetArgumentException(ExceptionResource.Argument_InvalidOffLen);
        }
References System.array, System.count, System.ThrowHelper.GetArgumentException(), System.ThrowHelper.GetArgumentNullException(), System.ThrowHelper.GetArgumentOutOfRangeException(), and System.offset.
Referenced by System.ThrowHelper.ThrowArraySegmentCtorValidationFailedExceptions().