Terraria Decompiled: System.ThrowHelper.ThrowStartOrEndArgumentValidationException
ThrowStartOrEndArgumentValidationException()
static void System.ThrowHelper.ThrowStartOrEndArgumentValidationException (long start) inline static
Definition at line 328 of file ThrowHelper.cs.
        {
            throw ThrowHelper.CreateStartOrEndArgumentValidationException(start);
        }
References System.ThrowHelper.CreateStartOrEndArgumentValidationException(), and System.start.
Referenced by System.Buffers.ReadOnlySequence< T >.Slice(), System.Buffers.ReadOnlySequence< T >.Slice(), System.Buffers.ReadOnlySequence< T >.Slice(), and System.Buffers.ReadOnlySequence< T >.Slice().