Terraria Decompiled: System.ThrowHelper.ThrowArgumentNullException
ThrowArgumentNullException()
static void System.ThrowHelper.ThrowArgumentNullException (ExceptionArgument argument) inline static package
Definition at line 16 of file ThrowHelper.cs.
        {
            throw ThrowHelper.CreateArgumentNullException(argument);
        }
References System.ThrowHelper.CreateArgumentNullException().
Referenced by System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Text.StringBuilder.AppendJoinCore< T >(), System.Text.StringBuilder.AppendJoinCore< T >(), System.ArraySegment< T >.ArraySegment(), System.MemoryExtensions.AsMemory(), System.MemoryExtensions.AsMemory(), System.MemoryExtensions.AsMemory< T >(), System.MemoryExtensions.AsMemory< T >(), System.MemoryExtensions.AsSpan< T >(), System.MemoryExtensions.AsSpan< T >(), System.SpanHelpers.BinarySearch< T, TComparable >(), System.MemoryExtensions.BinarySearch< T, TComparer >(), System.Collections.ObjectModel.Collection< T >.Collection(), System.Collections.Generic.List< T >.ConvertAll< TOutput >(), System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), System.Collections.Generic.Dictionary< TKey, TValue >.KeyCollection.CopyTo(), System.Collections.Generic.Dictionary< TKey, TValue >.ValueCollection.CopyTo(), System.Collections.ObjectModel.Collection< T >.CopyTo(), System.Collections.ObjectModel.ReadOnlyCollection< T >.CopyTo(), System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), System.Collections.Generic.Dictionary< TKey, TValue >.KeyCollection.CopyTo(), System.Collections.Generic.Dictionary< TKey, TValue >.ValueCollection.CopyTo(), System.Collections.Generic.Dictionary< TKey, TValue >.Dictionary(), System.Collections.Generic.Dictionary< TKey, TValue >.Dictionary(), System.Collections.Generic.List< T >.Find(), System.Collections.Generic.List< T >.FindAll(), System.Collections.Generic.Dictionary< TKey, TValue >.FindEntry(), System.Collections.Generic.List< T >.FindIndex(), System.Collections.Generic.List< T >.FindLast(), System.Collections.Generic.List< T >.FindLastIndex(), System.Collections.Generic.List< T >.ForEach(), System.OrdinalCaseSensitiveComparer.GetHashCode(), System.OrdinalComparer.GetHashCode(), System.OrdinalIgnoreCaseComparer.GetHashCode(), System.Collections.Generic.Dictionary< TKey, TValue >.GetObjectData(), System.ThrowHelper.IfNullAndNullsAreIllegalThenThrow< T >(), System.Collections.Generic.List< T >.InsertRange(), System.Collections.Generic.Dictionary< TKey, TValue >.IsCompatibleKey(), System.Collections.Generic.Dictionary< TKey, TValue >.KeyCollection.KeyCollection(), System.Collections.Generic.List< T >.List(), System.DateTimeOffset.Parse(), System.DateTimeOffset.Parse(), System.TimeSpan.Parse(), System.DateTimeOffset.Parse(), System.Byte.Parse(), System.DateTime.Parse(), System.Decimal.Parse(), System.Double.Parse(), System.Int16.Parse(), System.Int32.Parse(), System.Int64.Parse(), System.SByte.Parse(), System.Single.Parse(), System.TimeSpan.Parse(), System.UInt16.Parse(), System.UInt32.Parse(), System.UInt64.Parse(), System.Byte.Parse(), System.DateTime.Parse(), System.Decimal.Parse(), System.Double.Parse(), System.Int16.Parse(), System.Int32.Parse(), System.Int64.Parse(), System.SByte.Parse(), System.Single.Parse(), System.UInt16.Parse(), System.UInt32.Parse(), System.UInt64.Parse(), System.DateTime.Parse(), System.Byte.Parse(), System.Decimal.Parse(), System.Double.Parse(), System.Int16.Parse(), System.Int32.Parse(), System.Int64.Parse(), System.SByte.Parse(), System.Single.Parse(), System.UInt16.Parse(), System.UInt32.Parse(), System.UInt64.Parse(), System.Byte.Parse(), System.Decimal.Parse(), System.Double.Parse(), System.Int16.Parse(), System.Int32.Parse(), System.Int64.Parse(), System.SByte.Parse(), System.Single.Parse(), System.UInt16.Parse(), System.UInt32.Parse(), System.UInt64.Parse(), System.SByte.Parse(), System.DateTimeOffset.ParseExact(), System.TimeSpan.ParseExact(), System.DateTimeOffset.ParseExact(), System.TimeSpan.ParseExact(), System.TimeSpan.ParseExact(), System.DateTimeOffset.ParseExact(), System.TimeSpan.ParseExact(), System.DateTime.ParseExact(), System.DateTime.ParseExact(), System.DateTime.ParseExact(), System.Collections.ObjectModel.ReadOnlyCollection< T >.ReadOnlyCollection(), System.Buffers.ReadOnlySequence< T >.ReadOnlySequence(), System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), System.Collections.Generic.List< T >.RemoveAll(), System.Threading.Tasks.TaskCompletionSource< TResult >.SetException(), System.Collections.Generic.List< T >.Sort(), System.BitConverter.ToBoolean(), System.BitConverter.ToInt16(), System.BitConverter.ToInt32(), System.BitConverter.ToInt64(), System.MemoryExtensions.ToLower(), System.BitConverter.ToString(), System.BitConverter.ToString(), System.BitConverter.ToString(), System.MemoryExtensions.ToUpper(), System.Collections.Generic.List< T >.TrueForAll(), System.Collections.Generic.Dictionary< TKey, TValue >.TryInsert(), System.Threading.Tasks.TaskCompletionSource< TResult >.TrySetException(), System.Threading.Tasks.TaskCompletionSource< TResult >.TrySetException(), System.Collections.Generic.Dictionary< TKey, TValue >.ValueCollection.ValueCollection(), System.Threading.Tasks.ValueTask< TResult >.ValueTask(), System.Threading.Tasks.ValueTask< TResult >.ValueTask(), System.Threading.Tasks.ValueTask< TResult >.ValueTask(), and System.Threading.Tasks.ValueTask< TResult >.ValueTask().