Terraria Decompiled: System.ThrowHelper.GetResourceName
GetResourceName()
static string System.ThrowHelper.GetResourceName (ExceptionResource resource) inline static package
Definition at line 663 of file ThrowHelper.cs.
        {
            string text;
            switch (resource)
            {
            case ExceptionResource.Argument_ImplementIComparable:
                text = "At least one object must implement IComparable.";
                break;
            case ExceptionResource.Argument_InvalidType:
                text = "The type of arguments passed into generic comparer methods is invalid.";
                break;
            case ExceptionResource.Argument_InvalidArgumentForComparison:
                text = "Type of argument is not compatible with the generic comparer.";
                break;
            case ExceptionResource.Argument_InvalidRegistryKeyPermissionCheck:
                text = "The specified RegistryKeyPermissionCheck value is invalid.";
                break;
            case ExceptionResource.ArgumentOutOfRange_NeedNonNegNum:
                text = "Non-negative number required.";
                break;
            case ExceptionResource.Arg_ArrayPlusOffTooSmall:
                text = "Destination array is not long enough to copy all the items in the collection. Check array index and length.";
                break;
            case ExceptionResource.Arg_NonZeroLowerBound:
                text = "The lower bound of target array must be zero.";
                break;
            case ExceptionResource.Arg_RankMultiDimNotSupported:
                text = "Only single dimensional arrays are supported for the requested action.";
                break;
            case ExceptionResource.Arg_RegKeyDelHive:
                text = "Cannot delete a registry hive's subtree.";
                break;
            case ExceptionResource.Arg_RegKeyStrLenBug:
                text = "Registry key names should not be greater than 255 characters.";
                break;
            case ExceptionResource.Arg_RegSetStrArrNull:
                text = "RegistryKey.SetValue does not allow a String[] that contains a null String reference.";
                break;
            case ExceptionResource.Arg_RegSetMismatchedKind:
                text = "The type of the value object did not match the specified RegistryValueKind or the object could not be properly converted.";
                break;
            case ExceptionResource.Arg_RegSubKeyAbsent:
                text = "Cannot delete a subkey tree because the subkey does not exist.";
                break;
            case ExceptionResource.Arg_RegSubKeyValueAbsent:
                text = "No value exists with that name.";
                break;
            case ExceptionResource.Argument_AddingDuplicate:
                text = "An item with the same key has already been added.";
                break;
            case ExceptionResource.Serialization_InvalidOnDeser:
                text = "OnDeserialization method was called while the object was not being deserialized.";
                break;
            case ExceptionResource.Serialization_MissingKeys:
                text = "The Keys for this Hashtable are missing.";
                break;
            case ExceptionResource.Serialization_NullKey:
                text = "One of the serialized keys is null.";
                break;
            case ExceptionResource.Argument_InvalidArrayType:
                text = "Target array type is not compatible with the type of items in the collection.";
                break;
            case ExceptionResource.NotSupported_KeyCollectionSet:
                text = "Mutating a key collection derived from a dictionary is not allowed.";
                break;
            case ExceptionResource.NotSupported_ValueCollectionSet:
                text = "Mutating a value collection derived from a dictionary is not allowed.";
                break;
            case ExceptionResource.ArgumentOutOfRange_SmallCapacity:
                text = "capacity was less than the current size.";
                break;
            case ExceptionResource.ArgumentOutOfRange_Index:
                text = "Index was out of range. Must be non-negative and less than the size of the collection.";
                break;
            case ExceptionResource.Argument_InvalidOffLen:
                text = "Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.";
                break;
            case ExceptionResource.Argument_ItemNotExist:
                text = "The specified item does not exist in this KeyedCollection.";
                break;
            case ExceptionResource.ArgumentOutOfRange_Count:
                text = "Count must be positive and count must refer to a location within the string/array/collection.";
                break;
            case ExceptionResource.ArgumentOutOfRange_InvalidThreshold:
                text = "The specified threshold for creating dictionary is out of range.";
                break;
            case ExceptionResource.ArgumentOutOfRange_ListInsert:
                text = "Index must be within the bounds of the List.";
                break;
            case ExceptionResource.NotSupported_ReadOnlyCollection:
                text = "Collection is read-only.";
                break;
            case ExceptionResource.InvalidOperation_CannotRemoveFromStackOrQueue:
                text = "Removal is an invalid operation for Stack or Queue.";
                break;
            case ExceptionResource.InvalidOperation_EmptyQueue:
                text = "Queue empty.";
                break;
            case ExceptionResource.InvalidOperation_EnumOpCantHappen:
                text = "Enumeration has either not started or has already finished.";
                break;
            case ExceptionResource.InvalidOperation_EnumFailedVersion:
                text = "Collection was modified; enumeration operation may not execute.";
                break;
            case ExceptionResource.InvalidOperation_EmptyStack:
                text = "Stack empty.";
                break;
            case ExceptionResource.ArgumentOutOfRange_BiggerThanCollection:
                text = "Larger than collection size.";
                break;
            case ExceptionResource.InvalidOperation_EnumNotStarted:
                text = "Enumeration has not started. Call MoveNext.";
                break;
            case ExceptionResource.InvalidOperation_EnumEnded:
                text = "Enumeration already finished.";
                break;
            case ExceptionResource.NotSupported_SortedListNestedWrite:
                text = "This operation is not supported on SortedList nested types because they require modifying the original SortedList.";
                break;
            case ExceptionResource.InvalidOperation_NoValue:
                text = "Nullable object must have a value.";
                break;
            case ExceptionResource.InvalidOperation_RegRemoveSubKey:
                text = "Registry key has subkeys and recursive removes are not supported by this method.";
                break;
            case ExceptionResource.Security_RegistryPermission:
                text = "Requested registry access is not allowed.";
                break;
            case ExceptionResource.UnauthorizedAccess_RegistryNoWrite:
                text = "Cannot write to the registry key.";
                break;
            case ExceptionResource.ObjectDisposed_RegKeyClosed:
                text = "Cannot access a closed registry key.";
                break;
            case ExceptionResource.NotSupported_InComparableType:
                text = "A type must implement IComparable<T> or IComparable to support comparison.";
                break;
            case ExceptionResource.Argument_InvalidRegistryOptionsCheck:
                text = "The specified RegistryOptions value is invalid.";
                break;
            case ExceptionResource.Argument_InvalidRegistryViewCheck:
                text = "The specified RegistryView value is invalid.";
                break;
            default:
                return string.Empty;
            }
            return text;
        }
References System.text.
Referenced by System.ThrowHelper.ThrowArgumentException(), System.ThrowHelper.ThrowArgumentException(), System.ThrowHelper.ThrowArgumentOutOfRangeException(), System.ThrowHelper.ThrowInvalidOperationException(), System.ThrowHelper.ThrowNotSupportedException(), System.ThrowHelper.ThrowObjectDisposedException(), System.ThrowHelper.ThrowSecurityException(), System.ThrowHelper.ThrowSerializationException(), and System.ThrowHelper.ThrowUnauthorizedAccessException().