Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.Rooms.LegacyDungeonRoom.LegacyRoom
LegacyRoom()
void Terraria.GameContent.Generation.Dungeon.Rooms.LegacyDungeonRoom.LegacyRoom (DungeonData data, int i, int j, bool generating) inline
Definition at line 97 of file LegacyDungeonRoom.cs.
        {
            LegacyDungeonRoomSettings legacyDungeonRoomSettings = (LegacyDungeonRoomSettings)this.settings;
            UnifiedRandom unifiedRandom = new UnifiedRandom(legacyDungeonRoomSettings.RandomSeed);
            ushort brickTileType = this.settings.StyleData.BrickTileType;
            ushort brickWallType = this.settings.StyleData.BrickWallType;
            double num = data.roomStrengthScalar;
            if (legacyDungeonRoomSettings.StartingRoom)
            {
                num = 1.0;
            }
            double num2 = (double)((int)(15.0 * num) + unifiedRandom.Next(15));
            Vector2D vector2D;
            vector2D.X = (double)((float)unifiedRandom.Next(-10, 11) * 0.1f) * data.roomSlantVariantScalar;
            vector2D.Y = (double)((float)unifiedRandom.Next(-10, 11) * 0.1f) * data.roomSlantVariantScalar;
            if (vector2D.X == 0.0 && vector2D.Y == 0.0)
            {
                if (unifiedRandom.Next(2) == 0)
                {
                    vector2D.X = (double)((unifiedRandom.Next(2) == 0) ? (-1) : 1);
                }
                else
                {
                    vector2D.Y = (double)((unifiedRandom.Next(2) == 0) ? (-1) : 1);
                }
            }
            Vector2D vector2D2;
            vector2D2.X = (double)i;
            vector2D2.Y = (double)j - num2 / 2.0;
            if (this.calculated)
            {
                vector2D2 = this.StartPosition;
            }
            Vector2D vector2D3 = vector2D2;
            double num3 = data.roomStepScalar;
            if (legacyDungeonRoomSettings.StartingRoom)
            {
                num3 = 1.0;
            }
            int k = (int)(10.0 * num3) + unifiedRandom.Next(10);
            double num4 = num2;
            double num5 = data.roomInteriorToExteriorRatio;
            if (legacyDungeonRoomSettings.OverrideStartPosition != default(Vector2D) && legacyDungeonRoomSettings.OverrideEndPosition != default(Vector2D))
            {
                vector2D3 = (vector2D2 = legacyDungeonRoomSettings.OverrideStartPosition);
                Vector2D vector2D4 = legacyDungeonRoomSettings.OverrideEndPosition - vector2D2;
                vector2D = vector2D4.SafeNormalize(Vector2D.UnitX);
                k = (int)Math.Ceiling(vector2D4.Length() / vector2D.Length());
            }
            else if (legacyDungeonRoomSettings.OverrideVelocity != default(Vector2D))
            {
                vector2D = legacyDungeonRoomSettings.OverrideVelocity;
            }
            if (legacyDungeonRoomSettings.OverrideStrength > 0)
            {
                num4 = (num2 = (double)legacyDungeonRoomSettings.OverrideStrength);
            }
            if (legacyDungeonRoomSettings.OverrideSteps > 0)
            {
                k = legacyDungeonRoomSettings.OverrideSteps;
            }
            if (legacyDungeonRoomSettings.OverrideInteriorToExteriorRatio > 0.0)
            {
                num5 = legacyDungeonRoomSettings.OverrideInteriorToExteriorRatio;
            }
            this.InnerBounds.SetBounds((int)vector2D2.X, (int)vector2D2.Y, (int)vector2D2.X, (int)vector2D2.Y);
            this.OuterBounds.SetBounds((int)vector2D2.X, (int)vector2D2.Y, (int)vector2D2.X, (int)vector2D2.Y);
            while (k > 0)
            {
                k--;
                int num6 = Math.Max(0, Math.Min(Main.maxTilesX - 1, (int)(vector2D2.X - num2 * 0.800000011920929 - 5.0)));
                int num7 = Math.Max(0, Math.Min(Main.maxTilesX - 1, (int)(vector2D2.X + num2 * 0.800000011920929 + 5.0)));
                int num8 = Math.Max(0, Math.Min(Main.maxTilesY - 1, (int)(vector2D2.Y - num2 * 0.800000011920929 - 5.0)));
                int num9 = Math.Max(0, Math.Min(Main.maxTilesY - 1, (int)(vector2D2.Y + num2 * 0.800000011920929 + 5.0)));
                if (legacyDungeonRoomSettings.IsEntranceRoom && data.Type == DungeonType.DualDungeon)
                {
                    num9 = Math.Max(num9, DungeonUtils.GetDualDungeonBrickSupportCutoffY(data));
                }
                data.dungeonBounds.UpdateBounds(num6, num8, num7 - 1, num9 - 1);
                this.OuterBounds.UpdateBounds(num6, num8, num7 - 1, num9 - 1);
                int num10 = Math.Max(0, Math.Min(Main.maxTilesX - 1, (int)(vector2D2.X - num2 * num5)));
                int num11 = Math.Max(0, Math.Min(Main.maxTilesX - 1, (int)(vector2D2.X + num2 * num5)));
                int num12 = Math.Max(0, Math.Min(Main.maxTilesY - 1, (int)(vector2D2.Y - num2 * num5)));
                int num13 = Math.Max(0, Math.Min(Main.maxTilesY - 1, (int)(vector2D2.Y + num2 * num5)));
                this.InnerBounds.UpdateBounds(num10, num12, num11 - 1, num13 - 1);
                for (int l = num6; l < num7; l++)
                {
                    for (int m = num8; m < num9; m++)
                    {
                        if (!generating)
{
                            this._outerShapeData.Add(l - (int)vector2D3.X, m - (int)vector2D3.Y);
                            if (l >= num10 && l <= num11 && m >= num12 && m <= num13)
{
                                this._innerShapeData.Add(l - (int)vector2D3.X, m - (int)vector2D3.Y);
                            }
                        }
                        else
{
                            Main.tile[l, m].liquid = 0;
                            if (!DungeonUtils.IsHigherOrEqualTieredDungeonWall(data, (int)Main.tile[l, m].wall, (int)brickWallType))
{
                                DungeonUtils.ChangeTileType(Main.tile[l, m], brickTileType, true, legacyDungeonRoomSettings.OverridePaintTile);
                            }
                        }
                    }
                }
                if (generating)
                {
                    for (int n = num6 + 1; n < num7 - 1; n++)
                    {
                        for (int num14 = num8 + 1; num14 < num9 - 1; num14++)
{
                            DungeonUtils.ChangeWallType(Main.tile[n, num14], brickWallType, false, legacyDungeonRoomSettings.OverridePaintWall);
                        }
                    }
                }
                num6 = num10;
                num7 = num11;
                num8 = num12;
                num9 = num13;
                if (generating)
                {
                    for (int num15 = num6; num15 < num7; num15++)
                    {
                        for (int num16 = num8; num16 < num9; num16++)
{
                            DungeonUtils.ChangeWallType(Main.tile[num15, num16], brickWallType, true, legacyDungeonRoomSettings.OverridePaintWall);
                        }
                    }
                }
                vector2D2 += vector2D;
                vector2D.X = Math.Max(-1.0, Math.Min(1.0, vector2D.X + (double)((float)unifiedRandom.Next(-10, 11) * 0.05f) * data.roomSlantVariantScalar));
                vector2D.Y = Math.Max(-1.0, Math.Min(1.0, vector2D.Y + (double)((float)unifiedRandom.Next(-10, 11) * 0.05f) * data.roomSlantVariantScalar));
            }
            this.StartPosition = vector2D3;
            this.EndPosition = vector2D2;
            this.Strength = (int)num4;
            this.InnerBounds.CalculateHitbox();
            this.OuterBounds.CalculateHitbox();
            this._floodedTileCount = DungeonUtils.CalculateFloodedTileCountFromShapeData(this.InnerBounds, this._innerShapeData);
        }
References Terraria.GameContent.Generation.Dungeon.Rooms.LegacyDungeonRoom._innerShapeData, Terraria.GameContent.Generation.Dungeon.Rooms.LegacyDungeonRoom._outerShapeData, Terraria.WorldBuilding.ShapeData.Add(), Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.BrickTileType, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.BrickWallType, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.calculated, Terraria.GameContent.Generation.Dungeon.DungeonUtils.CalculateFloodedTileCountFromShapeData(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.CalculateHitbox(), System.Math.Ceiling(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.ChangeTileType(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.ChangeWallType(), Terraria.GameContent.Generation.Dungeon.DungeonData.dungeonBounds, Terraria.GameContent.Generation.Dungeon.DungeonUtils.GetDualDungeonBrickSupportCutoffY(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.InnerBounds, int, Terraria.GameContent.Generation.Dungeon.Rooms.LegacyDungeonRoomSettings.IsEntranceRoom, Terraria.GameContent.Generation.Dungeon.DungeonUtils.IsHigherOrEqualTieredDungeonWall(), ReLogic.Utilities.Vector2D.Length(), Terraria.Tile.liquid, System.Math.Max(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, System.Math.Min(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.OuterBounds, Terraria.GameContent.Generation.Dungeon.Rooms.StepBasedDungeonRoomSettings.OverrideInteriorToExteriorRatio, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.OverridePaintTile, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.OverridePaintWall, Terraria.GameContent.Generation.Dungeon.Rooms.StepBasedDungeonRoomSettings.OverrideStartPosition, Terraria.GameContent.Generation.Dungeon.Rooms.StepBasedDungeonRoomSettings.OverrideSteps, Terraria.GameContent.Generation.Dungeon.Rooms.StepBasedDungeonRoomSettings.OverrideStrength, Terraria.GameContent.Generation.Dungeon.Rooms.StepBasedDungeonRoomSettings.OverrideVelocity, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.RandomSeed, Terraria.GameContent.Generation.Dungeon.DungeonData.roomInteriorToExteriorRatio, Terraria.GameContent.Generation.Dungeon.DungeonData.roomSlantVariantScalar, Terraria.GameContent.Generation.Dungeon.DungeonData.roomStepScalar, Terraria.GameContent.Generation.Dungeon.DungeonData.roomStrengthScalar, Terraria.GameContent.Generation.Dungeon.DungeonBounds.SetBounds(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.settings, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.StartingRoom, Terraria.GameContent.Generation.Dungeon.Rooms.LegacyDungeonRoom.StartPosition, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.StyleData, Terraria.Main.tile, Terraria.GameContent.Generation.Dungeon.DungeonData.Type, ReLogic.Utilities.Vector2D.UnitX, Terraria.GameContent.Generation.Dungeon.DungeonBounds.UpdateBounds(), Terraria.Tile.wall, ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.GameContent.Generation.Dungeon.Rooms.LegacyDungeonRoom.CalculateRoom(), and Terraria.GameContent.Generation.Dungeon.Rooms.LegacyDungeonRoom.GenerateRoom().