Terraria Decompiled: Terraria.DataStructures.SelectionHolder.SetActiveFrame
SetActiveFrame() [1/2]
void Terraria.DataStructures.SelectionHolder< TCycleType >.SetActiveFrame (string frameName) inline private
Definition at line 91 of file SelectionHolder.cs.
        {
            TCycleType tcycleType = this.Options.FirstOrDefault((KeyValuePair<string, TCycleType> pair) => pair.Key == frameName).Value;
            if (tcycleType == null)
            {
                tcycleType = this.Options.Values.First<TCycleType>();
            }
            this.SetActiveFrame(tcycleType);
        }
References System.Collections.Generic.KeyValuePair< TKey, TValue >.Key, Terraria.DataStructures.SelectionHolder< TCycleType >.Options, Terraria.DataStructures.SelectionHolder< TCycleType >.SetActiveFrame(), and System.Collections.Generic.Dictionary< TKey, TValue >.Values.
Referenced by Terraria.DataStructures.SelectionHolder< TCycleType >.CycleSelection(), Terraria.DataStructures.SelectionHolder< TCycleType >.SetActiveFrame(), and Terraria.DataStructures.SelectionHolder< TCycleType >.SetActiveMinimapFromLoadedConfigKey().