Terraria Decompiled: System.Buffers.Text.Utf8Parser.TryParseTimeSpanC
TryParseTimeSpanC()
static bool System.Buffers.Text.Utf8Parser.TryParseTimeSpanC (ReadOnlySpan< byte > source, out TimeSpan value, out int bytesConsumed) inline static private
Definition at line 3812 of file Utf8Parser.cs.
        {
            Utf8Parser.TimeSpanSplitter timeSpanSplitter = default(Utf8Parser.TimeSpanSplitter);
            if (!timeSpanSplitter.TrySplitTimeSpan(source, true, out bytesConsumed))
            {
                value = default(TimeSpan);
                return false;
            }
            bool isNegative = timeSpanSplitter.IsNegative;
            uint separators = timeSpanSplitter.Separators;
            bool flag;
            if (separators <= 16842752U)
            {
                if (separators == 0U)
                {
                    flag = Utf8Parser.TryCreateTimeSpan(isNegative, timeSpanSplitter.V1, 0U, 0U, 0U, 0U, out value);
                    goto IL_0172;
                }
                if (separators == 16777216U)
                {
                    flag = Utf8Parser.TryCreateTimeSpan(isNegative, 0U, timeSpanSplitter.V1, timeSpanSplitter.V2, 0U, 0U, out value);
                    goto IL_0172;
                }
                if (separators == 16842752U)
                {
                    flag = Utf8Parser.TryCreateTimeSpan(isNegative, 0U, timeSpanSplitter.V1, timeSpanSplitter.V2, timeSpanSplitter.V3, 0U, out value);
                    goto IL_0172;
                }
            }
            else if (separators <= 33619968U)
            {
                if (separators == 16843264U)
                {
                    flag = Utf8Parser.TryCreateTimeSpan(isNegative, 0U, timeSpanSplitter.V1, timeSpanSplitter.V2, timeSpanSplitter.V3, timeSpanSplitter.V4, out value);
                    goto IL_0172;
                }
                if (separators == 33619968U)
                {
                    flag = Utf8Parser.TryCreateTimeSpan(isNegative, timeSpanSplitter.V1, timeSpanSplitter.V2, timeSpanSplitter.V3, 0U, 0U, out value);
                    goto IL_0172;
                }
            }
            else
            {
                if (separators == 33620224U)
                {
                    flag = Utf8Parser.TryCreateTimeSpan(isNegative, timeSpanSplitter.V1, timeSpanSplitter.V2, timeSpanSplitter.V3, timeSpanSplitter.V4, 0U, out value);
                    goto IL_0172;
                }
                if (separators == 33620226U)
                {
                    flag = Utf8Parser.TryCreateTimeSpan(isNegative, timeSpanSplitter.V1, timeSpanSplitter.V2, timeSpanSplitter.V3, timeSpanSplitter.V4, timeSpanSplitter.V5, out value);
                    goto IL_0172;
                }
            }
            value = default(TimeSpan);
            flag = false;
            IL_0172:
            if (!flag)
            {
                bytesConsumed = 0;
                return false;
            }
            return true;
        }
References System.Buffers.Text.Utf8Parser.TimeSpanSplitter.IsNegative, System.Buffers.Text.Utf8Parser.TimeSpanSplitter.Separators, System.source, System.Buffers.Text.Utf8Parser.TryCreateTimeSpan(), System.Buffers.Text.Utf8Parser.TimeSpanSplitter.TrySplitTimeSpan(), System.U, System.Buffers.Text.Utf8Parser.TimeSpanSplitter.V1, System.Buffers.Text.Utf8Parser.TimeSpanSplitter.V2, System.Buffers.Text.Utf8Parser.TimeSpanSplitter.V3, System.Buffers.Text.Utf8Parser.TimeSpanSplitter.V4, System.Buffers.Text.Utf8Parser.TimeSpanSplitter.V5, and System.value.
Referenced by System.Buffers.Text.Utf8Parser.TryParse().