Terraria Decompiled: System.Buffers.Text.Utf8Parser.TryParse
TryParse() [2/16]
static bool System.Buffers.Text.Utf8Parser.TryParse (ReadOnlySpan< byte > source, out byte value, out int bytesConsumed, char standardFormat = '\0') inline static
Definition at line 3296 of file Utf8Parser.cs.
        {
            if (standardFormat > 'N')
            {
                if (standardFormat <= 'd')
                {
                    if (standardFormat != 'X')
                    {
                        if (standardFormat != 'd')
{
                            goto IL_005D;
                        }
                        goto IL_0042;
                    }
                }
                else
                {
                    if (standardFormat == 'g')
                    {
                        goto IL_0042;
                    }
                    if (standardFormat == 'n')
                    {
                        goto IL_004B;
                    }
                    if (standardFormat != 'x')
                    {
                        goto IL_005D;
                    }
                }
                return Utf8Parser.TryParseByteX(source, out value, out bytesConsumed);
            }
            if (standardFormat <= 'D')
            {
                if (standardFormat != '\0' && standardFormat != 'D')
                {
                    goto IL_005D;
                }
            }
            else if (standardFormat != 'G')
            {
                if (standardFormat != 'N')
                {
                    goto IL_005D;
                }
                goto IL_004B;
            }
            IL_0042:
            return Utf8Parser.TryParseByteD(source, out value, out bytesConsumed);
            IL_004B:
            return Utf8Parser.TryParseByteN(source, out value, out bytesConsumed);
            IL_005D:
            return ThrowHelper.TryParseThrowFormatException<byte>(out value, out bytesConsumed);
        }
References System.source, System.Buffers.Text.Utf8Parser.TryParseByteD(), System.Buffers.Text.Utf8Parser.TryParseByteN(), System.Buffers.Text.Utf8Parser.TryParseByteX(), and System.value.