Terraria Decompiled: System.Buffers.Text.Utf8Parser.TryParseGuidN
TryParseGuidN()
static bool System.Buffers.Text.Utf8Parser.TryParseGuidN (ReadOnlySpan< byte > text, out Guid value, out int bytesConsumed) inline static private
Definition at line 1100 of file Utf8Parser.cs.
        {
            if (text.Length < 32)
            {
                value = default(Guid);
                bytesConsumed = 0;
                return false;
            }
            uint num;
            int num2;
            if (!Utf8Parser.TryParseUInt32X(text.Slice(0, 8), out num, out num2) || num2 != 8)
            {
                value = default(Guid);
                bytesConsumed = 0;
                return false;
            }
            ushort num3;
            if (!Utf8Parser.TryParseUInt16X(text.Slice(8, 4), out num3, out num2) || num2 != 4)
            {
                value = default(Guid);
                bytesConsumed = 0;
                return false;
            }
            ushort num4;
            if (!Utf8Parser.TryParseUInt16X(text.Slice(12, 4), out num4, out num2) || num2 != 4)
            {
                value = default(Guid);
                bytesConsumed = 0;
                return false;
            }
            ushort num5;
            if (!Utf8Parser.TryParseUInt16X(text.Slice(16, 4), out num5, out num2) || num2 != 4)
            {
                value = default(Guid);
                bytesConsumed = 0;
                return false;
            }
            ulong num6;
            if (!Utf8Parser.TryParseUInt64X(text.Slice(20), out num6, out num2) || num2 != 12)
            {
                value = default(Guid);
                bytesConsumed = 0;
                return false;
            }
            bytesConsumed = 32;
            value = new Guid((int)num, (short)num3, (short)num4, (byte)(num5 >> 8), (byte)num5, (byte)(num6 >> 40), (byte)(num6 >> 32), (byte)(num6 >> 24), (byte)(num6 >> 16), (byte)(num6 >> 8), (byte)num6);
            return true;
        }
References System.text, System.Buffers.Text.Utf8Parser.TryParseUInt16X(), System.Buffers.Text.Utf8Parser.TryParseUInt32X(), System.Buffers.Text.Utf8Parser.TryParseUInt64X(), and System.value.
Referenced by System.Buffers.Text.Utf8Parser.TryParse().