Terraria Decompiled: System.Buffers.Text.Utf8Parser.TryCreateTimeSpan
TryCreateTimeSpan()
static bool System.Buffers.Text.Utf8Parser.TryCreateTimeSpan (bool isNegative, uint days, uint hours, uint minutes, uint seconds, uint fraction, out TimeSpan timeSpan) inline static private
Definition at line 4036 of file Utf8Parser.cs.
        {
            if (hours > 23U || minutes > 59U || seconds > 59U)
            {
                timeSpan = default(TimeSpan);
                return false;
            }
            long num = (long)(((ulong)days * 3600UL * 24UL + (ulong)hours * 3600UL + (ulong)minutes * 60UL + (ulong)seconds) * 1000UL);
            long num3;
            if (isNegative)
            {
                num = -num;
                if (num < -922337203685477L)
                {
                    timeSpan = default(TimeSpan);
                    return false;
                }
                long num2 = num * 10000L;
                if (num2 < (long)(9223372036854775808UL + (ulong)fraction))
                {
                    timeSpan = default(TimeSpan);
                    return false;
                }
                num3 = num2 - (long)((ulong)fraction);
            }
            else
            {
                if (num > 922337203685477L)
                {
                    timeSpan = default(TimeSpan);
                    return false;
                }
                long num4 = num * 10000L;
                if (num4 > (long)(9223372036854775807UL - (ulong)fraction))
                {
                    timeSpan = default(TimeSpan);
                    return false;
                }
                num3 = num4 + (long)((ulong)fraction);
            }
            timeSpan = new TimeSpan(num3);
            return true;
        }
References System.L, long, and System.U.
Referenced by System.Buffers.Text.Utf8Parser.TryParseTimeSpanBigG(), System.Buffers.Text.Utf8Parser.TryParseTimeSpanC(), and System.Buffers.Text.Utf8Parser.TryParseTimeSpanLittleG().