Terraria Decompiled: System.Buffers.Text.Utf8Parser.TryParseNumber
TryParseNumber()
static unsafe bool System.Buffers.Text.Utf8Parser.TryParseNumber (ReadOnlySpan< byte > source, ref NumberBuffer number, out int bytesConsumed, Utf8Parser::ParseNumberOptions options, out bool textUsedExponentNotation) inline static private
Definition at line 3523 of file Utf8Parser.cs.
        {
            textUsedExponentNotation = false;
            if (source.Length == 0)
            {
                bytesConsumed = 0;
                return false;
            }
            Span<byte> digits = number.Digits;
            int num = 0;
            byte b = *source[num];
            if (b != 43)
            {
                if (b != 45)
                {
                    goto IL_0055;
                }
                number.IsNegative = true;
            }
            num++;
            if (num == source.Length)
            {
                bytesConsumed = 0;
                return false;
            }
            b = *source[num];
            IL_0055:
            int num2 = num;
            while (num != source.Length)
            {
                b = *source[num];
                if (b != 48)
                {
                    break;
                }
                num++;
            }
            if (num == source.Length)
            {
                *digits[0] = 0;
                number.Scale = 0;
                bytesConsumed = num;
                return true;
            }
            int num3 = num;
            while (num != source.Length)
            {
                b = *source[num];
                if (b - 48 > 9)
                {
                    break;
                }
                num++;
            }
            int num4 = num - num2;
            int num5 = num - num3;
            int num6 = Math.Min(num5, 50);
            source.Slice(num3, num6).CopyTo(digits);
            int num7 = num6;
            number.Scale = num5;
            if (num == source.Length)
            {
                bytesConsumed = num;
                return true;
            }
            int num8 = 0;
            if (b == 46)
            {
                num++;
                int num9 = num;
                while (num != source.Length)
                {
                    b = *source[num];
                    if (b - 48 > 9)
                    {
                        break;
                    }
                    num++;
                }
                num8 = num - num9;
                int num10 = num9;
                if (num7 == 0)
                {
                    while (num10 < num && *source[num10] == 48)
                    {
                        number.Scale--;
                        num10++;
                    }
                }
                int num11 = Math.Min(num - num10, 51 - num7 - 1);
                source.Slice(num10, num11).CopyTo(digits.Slice(num7));
                num7 += num11;
                if (num == source.Length)
                {
                    if (num4 == 0 && num8 == 0)
                    {
                        bytesConsumed = 0;
                        return false;
                    }
                    bytesConsumed = num;
                    return true;
                }
            }
            if (num4 == 0 && num8 == 0)
            {
                bytesConsumed = 0;
                return false;
            }
            if (((int)b & -33) != 69)
            {
                bytesConsumed = num;
                return true;
            }
            textUsedExponentNotation = true;
            num++;
            if ((options & Utf8Parser.ParseNumberOptions.AllowExponent) == (Utf8Parser.ParseNumberOptions)0)
            {
                bytesConsumed = 0;
                return false;
            }
            if (num == source.Length)
            {
                bytesConsumed = 0;
                return false;
            }
            bool flag = false;
            b = *source[num];
            if (b != 43)
            {
                if (b != 45)
                {
                    goto IL_0229;
                }
                flag = true;
            }
            num++;
            if (num == source.Length)
            {
                bytesConsumed = 0;
                return false;
            }
            b = *source[num];
            IL_0229:
            uint num12;
            int num13;
            if (!Utf8Parser.TryParseUInt32D(source.Slice(num), out num12, out num13))
            {
                bytesConsumed = 0;
                return false;
            }
            num += num13;
            if (flag)
            {
                if ((long)number.Scale < (long)(18446744071562067968UL + (ulong)num12))
                {
                    number.Scale = int.MinValue;
                }
                else
                {
                    number.Scale -= (int)num12;
                }
            }
            else
            {
                if ((long)number.Scale > (long)(2147483647UL - (ulong)num12))
                {
                    bytesConsumed = 0;
                    return false;
                }
                number.Scale += (int)num12;
            }
            bytesConsumed = num;
            return true;
        }
References int, long, System.Math.Min(), System.options, System.Span< T >.Slice(), System.source, and System.Buffers.Text.Utf8Parser.TryParseUInt32D().
Referenced by System.Buffers.Text.Utf8Parser.TryParse(), and System.Buffers.Text.Utf8Parser.TryParseNormalAsFloatingPoint().