Terraria Decompiled: System.Buffers.Text.Utf8Parser.TryParseUInt32D
TryParseUInt32D()
static unsafe bool System.Buffers.Text.Utf8Parser.TryParseUInt32D (ReadOnlySpan< byte > source, out uint value, out int bytesConsumed) inline static private
Definition at line 2471 of file Utf8Parser.cs.
        {
            if (source.Length >= 1)
            {
                int num = 0;
                int num2 = (int)(*source[num]);
                int num3 = 0;
                if (ParserHelpers.IsDigit(num2))
                {
                    if (num2 == 48)
                    {
                        do
{
                            num++;
                            if (num >= source.Length)
{
                                goto IL_023D;
                            }
                            num2 = (int)(*source[num]);
                        }
                        while (num2 == 48);
                        if (!ParserHelpers.IsDigit(num2))
{
                            goto IL_023D;
                        }
                    }
                    num3 = num2 - 48;
                    num++;
                    if (num < source.Length)
                    {
                        num2 = (int)(*source[num]);
                        if (ParserHelpers.IsDigit(num2))
{
                            num++;
                            num3 = 10 * num3 + num2 - 48;
                            if (num < source.Length)
{
                                num2 = (int)(*source[num]);
                                if (ParserHelpers.IsDigit(num2))
{
                                    num++;
                                    num3 = 10 * num3 + num2 - 48;
                                    if (num < source.Length)
{
                                        num2 = (int)(*source[num]);
                                        if (ParserHelpers.IsDigit(num2))
{
                                            num++;
                                            num3 = 10 * num3 + num2 - 48;
                                            if (num < source.Length)
{
                                                num2 = (int)(*source[num]);
                                                if (ParserHelpers.IsDigit(num2))
{
                                                    num++;
                                                    num3 = 10 * num3 + num2 - 48;
                                                    if (num < source.Length)
{
                                                        num2 = (int)(*source[num]);
                                                        if (ParserHelpers.IsDigit(num2))
{
                                                            num++;
                                                            num3 = 10 * num3 + num2 - 48;
                                                            if (num < source.Length)
{
                                                                num2 = (int)(*source[num]);
                                                                if (ParserHelpers.IsDigit(num2))
{
                                                                    num++;
                                                                    num3 = 10 * num3 + num2 - 48;
                                                                    if (num < source.Length)
{
                                                                        num2 = (int)(*source[num]);
                                                                        if (ParserHelpers.IsDigit(num2))
{
                                                                            num++;
                                                                            num3 = 10 * num3 + num2 - 48;
                                                                            if (num < source.Length)
{
                                                                                num2 = (int)(*source[num]);
                                                                                if (ParserHelpers.IsDigit(num2))
{
                                                                                    num++;
                                                                                    num3 = 10 * num3 + num2 - 48;
                                                                                    if (num < source.Length)
{
                                                                                        num2 = (int)(*source[num]);
                                                                                        if (ParserHelpers.IsDigit(num2))
{
                                                                                            num++;
                                                                                            if (num3 > 429496729 || (num3 == 429496729 && num2 > 53))
{
                                                                                                goto IL_0235;
                                                                                            }
                                                                                            num3 = num3 * 10 + num2 - 48;
                                                                                            if (num < source.Length && ParserHelpers.IsDigit((int)(*source[num])))
{
                                                                                                goto IL_0235;
                                                                                            }
                                                                                        }
                                                                                    }
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                    IL_023D:
                    bytesConsumed = num;
                    value = (uint)num3;
                    return true;
                }
            }
            IL_0235:
            bytesConsumed = 0;
            value = 0U;
            return false;
        }
References int, System.Buffers.Text.ParserHelpers.IsDigit(), System.source, System.U, and System.value.
Referenced by System.Buffers.Text.Utf8Parser.TimeSpanSplitter.ParseComponent(), System.Buffers.Text.Utf8Parser.TryParse(), System.Buffers.Text.Utf8Parser.TryParseNumber(), System.Buffers.Text.Utf8Parser.TryParseTimeSpanBigG(), and System.Buffers.Text.Utf8Parser.TimeSpanSplitter.TrySplitTimeSpan().