Terraria Decompiled: System.Buffers.Text.Utf8Parser.TryParseTimeSpanBigG
TryParseTimeSpanBigG()
static unsafe bool System.Buffers.Text.Utf8Parser.TryParseTimeSpanBigG (ReadOnlySpan< byte > source, out TimeSpan value, out int bytesConsumed) inline static private
Definition at line 3699 of file Utf8Parser.cs.
        {
            int num = 0;
            byte b = 0;
            while (num != source.Length)
            {
                b = *source[num];
                if (b != 32 && b != 9)
                {
                    break;
                }
                num++;
            }
            if (num == source.Length)
            {
                value = default(TimeSpan);
                bytesConsumed = 0;
                return false;
            }
            bool flag = false;
            if (b == 45)
            {
                flag = true;
                num++;
                if (num == source.Length)
                {
                    value = default(TimeSpan);
                    bytesConsumed = 0;
                    return false;
                }
            }
            uint num2;
            int num3;
            if (!Utf8Parser.TryParseUInt32D(source.Slice(num), out num2, out num3))
            {
                value = default(TimeSpan);
                bytesConsumed = 0;
                return false;
            }
            num += num3;
            if (num == source.Length || *source[num++] != 58)
            {
                value = default(TimeSpan);
                bytesConsumed = 0;
                return false;
            }
            uint num4;
            if (!Utf8Parser.TryParseUInt32D(source.Slice(num), out num4, out num3))
            {
                value = default(TimeSpan);
                bytesConsumed = 0;
                return false;
            }
            num += num3;
            if (num == source.Length || *source[num++] != 58)
            {
                value = default(TimeSpan);
                bytesConsumed = 0;
                return false;
            }
            uint num5;
            if (!Utf8Parser.TryParseUInt32D(source.Slice(num), out num5, out num3))
            {
                value = default(TimeSpan);
                bytesConsumed = 0;
                return false;
            }
            num += num3;
            if (num == source.Length || *source[num++] != 58)
            {
                value = default(TimeSpan);
                bytesConsumed = 0;
                return false;
            }
            uint num6;
            if (!Utf8Parser.TryParseUInt32D(source.Slice(num), out num6, out num3))
            {
                value = default(TimeSpan);
                bytesConsumed = 0;
                return false;
            }
            num += num3;
            if (num == source.Length || *source[num++] != 46)
            {
                value = default(TimeSpan);
                bytesConsumed = 0;
                return false;
            }
            uint num7;
            if (!Utf8Parser.TryParseTimeSpanFraction(source.Slice(num), out num7, out num3))
            {
                value = default(TimeSpan);
                bytesConsumed = 0;
                return false;
            }
            num += num3;
            if (!Utf8Parser.TryCreateTimeSpan(flag, num2, num4, num5, num6, num7, out value))
            {
                value = default(TimeSpan);
                bytesConsumed = 0;
                return false;
            }
            if (num != source.Length && (*source[num] == 46 || *source[num] == 58))
            {
                value = default(TimeSpan);
                bytesConsumed = 0;
                return false;
            }
            bytesConsumed = num;
            return true;
        }
References System.source, System.Buffers.Text.Utf8Parser.TryCreateTimeSpan(), System.Buffers.Text.Utf8Parser.TryParseTimeSpanFraction(), System.Buffers.Text.Utf8Parser.TryParseUInt32D(), and System.value.
Referenced by System.Buffers.Text.Utf8Parser.TryParse().