Terraria Decompiled: System.Buffers.Text.Utf8Parser.TryParse
TryParse() [3/16]
static bool System.Buffers.Text.Utf8Parser.TryParse (ReadOnlySpan< byte > source, out DateTime value, out int bytesConsumed, char standardFormat = '\0') inline static
Definition at line 799 of file Utf8Parser.cs.
        {
            if (standardFormat <= 'G')
            {
                if (standardFormat == '\0' || standardFormat == 'G')
                {
                    DateTimeOffset dateTimeOffset;
                    return Utf8Parser.TryParseDateTimeG(source, out value, out dateTimeOffset, out bytesConsumed);
                }
            }
            else if (standardFormat != 'O')
            {
                if (standardFormat != 'R')
                {
                    if (standardFormat == 'l')
                    {
                        DateTimeOffset dateTimeOffset2;
                        if (!Utf8Parser.TryParseDateTimeOffsetR(source, 32U, out dateTimeOffset2, out bytesConsumed))
{
                            value = default(DateTime);
                            return false;
                        }
                        value = dateTimeOffset2.DateTime;
                        return true;
                    }
                }
                else
                {
                    DateTimeOffset dateTimeOffset3;
                    if (!Utf8Parser.TryParseDateTimeOffsetR(source, 0U, out dateTimeOffset3, out bytesConsumed))
                    {
                        value = default(DateTime);
                        return false;
                    }
                    value = dateTimeOffset3.DateTime;
                    return true;
                }
            }
            else
            {
                DateTimeOffset dateTimeOffset4;
                DateTimeKind dateTimeKind;
                if (!Utf8Parser.TryParseDateTimeOffsetO(source, out dateTimeOffset4, out bytesConsumed, out dateTimeKind))
                {
                    value = default(DateTime);
                    bytesConsumed = 0;
                    return false;
                }
                if (dateTimeKind != DateTimeKind.Utc)
                {
                    if (dateTimeKind == DateTimeKind.Local)
                    {
                        value = dateTimeOffset4.LocalDateTime;
                    }
                    else
                    {
                        value = dateTimeOffset4.DateTime;
                    }
                }
                else
                {
                    value = dateTimeOffset4.UtcDateTime;
                }
                return true;
            }
            return ThrowHelper.TryParseThrowFormatException<DateTime>(out value, out bytesConsumed);
        }
References System.DateTimeOffset.DateTime, System.DateTimeOffset.LocalDateTime, System.source, System.Buffers.Text.Utf8Parser.TryParseDateTimeG(), System.Buffers.Text.Utf8Parser.TryParseDateTimeOffsetO(), System.Buffers.Text.Utf8Parser.TryParseDateTimeOffsetR(), System.U, System.DateTimeOffset.UtcDateTime, and System.value.