Terraria Decompiled: System.Buffers.Text.Utf8Parser.TryParseGuidCore
TryParseGuidCore()
static unsafe bool System.Buffers.Text.Utf8Parser.TryParseGuidCore (ReadOnlySpan< byte > source, bool ends, char begin, char end, out Guid value, out int bytesConsumed) inline static private
Definition at line 1150 of file Utf8Parser.cs.
        {
            int num = 36 + (ends ? 2 : 0);
            if (source.Length < num)
            {
                value = default(Guid);
                bytesConsumed = 0;
                return false;
            }
            if (ends)
            {
                if ((char)(*source[0]) != begin)
                {
                    value = default(Guid);
                    bytesConsumed = 0;
                    return false;
                }
                source = source.Slice(1);
            }
            uint num2;
            int num3;
            if (!Utf8Parser.TryParseUInt32X(source, out num2, out num3))
            {
                value = default(Guid);
                bytesConsumed = 0;
                return false;
            }
            if (num3 != 8)
            {
                value = default(Guid);
                bytesConsumed = 0;
                return false;
            }
            if (*source[num3] != 45)
            {
                value = default(Guid);
                bytesConsumed = 0;
                return false;
            }
            source = source.Slice(9);
            ushort num4;
            if (!Utf8Parser.TryParseUInt16X(source, out num4, out num3))
            {
                value = default(Guid);
                bytesConsumed = 0;
                return false;
            }
            if (num3 != 4)
            {
                value = default(Guid);
                bytesConsumed = 0;
                return false;
            }
            if (*source[num3] != 45)
            {
                value = default(Guid);
                bytesConsumed = 0;
                return false;
            }
            source = source.Slice(5);
            ushort num5;
            if (!Utf8Parser.TryParseUInt16X(source, out num5, out num3))
            {
                value = default(Guid);
                bytesConsumed = 0;
                return false;
            }
            if (num3 != 4)
            {
                value = default(Guid);
                bytesConsumed = 0;
                return false;
            }
            if (*source[num3] != 45)
            {
                value = default(Guid);
                bytesConsumed = 0;
                return false;
            }
            source = source.Slice(5);
            ushort num6;
            if (!Utf8Parser.TryParseUInt16X(source, out num6, out num3))
            {
                value = default(Guid);
                bytesConsumed = 0;
                return false;
            }
            if (num3 != 4)
            {
                value = default(Guid);
                bytesConsumed = 0;
                return false;
            }
            if (*source[num3] != 45)
            {
                value = default(Guid);
                bytesConsumed = 0;
                return false;
            }
            source = source.Slice(5);
            ulong num7;
            if (!Utf8Parser.TryParseUInt64X(source, out num7, out num3))
            {
                value = default(Guid);
                bytesConsumed = 0;
                return false;
            }
            if (num3 != 12)
            {
                value = default(Guid);
                bytesConsumed = 0;
                return false;
            }
            if (ends && (char)(*source[num3]) != end)
            {
                value = default(Guid);
                bytesConsumed = 0;
                return false;
            }
            bytesConsumed = num;
            value = new Guid((int)num2, (short)num4, (short)num5, (byte)(num6 >> 8), (byte)num6, (byte)(num7 >> 40), (byte)(num7 >> 32), (byte)(num7 >> 24), (byte)(num7 >> 16), (byte)(num7 >> 8), (byte)num7);
            return true;
        }
References System.source, System.Buffers.Text.Utf8Parser.TryParseUInt16X(), System.Buffers.Text.Utf8Parser.TryParseUInt32X(), System.Buffers.Text.Utf8Parser.TryParseUInt64X(), and System.value.
Referenced by System.Buffers.Text.Utf8Parser.TryParse().