Terraria Decompiled: System.Buffers.Text.Utf8Parser.TryCreateDateTime
TryCreateDateTime()
static bool System.Buffers.Text.Utf8Parser.TryCreateDateTime (int year, int month, int day, int hour, int minute, int second, int fraction, DateTimeKind kind, out DateTime value) inline static private
Definition at line 299 of file Utf8Parser.cs.
        {
            if (year == 0)
            {
                value = default(DateTime);
                return false;
            }
            if (month - 1 >= 12)
            {
                value = default(DateTime);
                return false;
            }
            uint num = (uint)(day - 1);
            if (num >= 28U && (ulong)num >= (ulong)((long)DateTime.DaysInMonth(year, month)))
            {
                value = default(DateTime);
                return false;
            }
            if (hour > 23)
            {
                value = default(DateTime);
                return false;
            }
            if (minute > 59)
            {
                value = default(DateTime);
                return false;
            }
            if (second > 59)
            {
                value = default(DateTime);
                return false;
            }
            int[] array = (DateTime.IsLeapYear(year) ? Utf8Parser.s_daysToMonth366 : Utf8Parser.s_daysToMonth365);
            int num2 = year - 1;
            long num3 = (long)(num2 * 365 + num2 / 4 - num2 / 100 + num2 / 400 + array[month - 1] + day - 1) * 864000000000L;
            int num4 = hour * 3600 + minute * 60 + second;
            num3 += (long)num4 * 10000000L;
            num3 += (long)fraction;
            value = new DateTime(num3, kind);
            return true;
        }
References System.array, System.DateTime, System.DateTime.DaysInMonth(), System.DateTime.IsLeapYear(), System.L, long, System.Buffers.Text.Utf8Parser.s_daysToMonth365, System.U, and System.value.
Referenced by System.Buffers.Text.Utf8Parser.TryCreateDateTimeOffset(), and System.Buffers.Text.Utf8Parser.TryCreateDateTimeOffsetInterpretingDataAsLocalTime().