Terraria Decompiled: System.Buffers.Text.Utf8Parser.TryParseDateTimeOffsetR
TryParseDateTimeOffsetR()
static unsafe bool System.Buffers.Text.Utf8Parser.TryParseDateTimeOffsetR (ReadOnlySpan< byte > source, uint caseFlipXorMask, out DateTimeOffset dateTimeOffset, out int bytesConsumed) inline static private
Definition at line 548 of file Utf8Parser.cs.
        {
            if (source.Length < 29)
            {
                bytesConsumed = 0;
                dateTimeOffset = default(DateTimeOffset);
                return false;
            }
            uint num = (uint)(*source[0]) ^ caseFlipXorMask;
            uint num2 = (uint)(*source[1]);
            uint num3 = (uint)(*source[2]);
            uint num4 = (uint)(*source[3]);
            uint num5 = (num << 24) | (num2 << 16) | (num3 << 8) | num4;
            DayOfWeek dayOfWeek;
            if (num5 <= 1398895660U)
            {
                if (num5 == 1181903148U)
                {
                    dayOfWeek = DayOfWeek.Friday;
                    goto IL_00D5;
                }
                if (num5 == 1299148332U)
                {
                    dayOfWeek = DayOfWeek.Monday;
                    goto IL_00D5;
                }
                if (num5 == 1398895660U)
                {
                    dayOfWeek = DayOfWeek.Saturday;
                    goto IL_00D5;
                }
            }
            else if (num5 <= 1416131884U)
            {
                if (num5 == 1400204844U)
                {
                    dayOfWeek = DayOfWeek.Sunday;
                    goto IL_00D5;
                }
                if (num5 == 1416131884U)
                {
                    dayOfWeek = DayOfWeek.Thursday;
                    goto IL_00D5;
                }
            }
            else
            {
                if (num5 == 1416979756U)
                {
                    dayOfWeek = DayOfWeek.Tuesday;
                    goto IL_00D5;
                }
                if (num5 == 1466262572U)
                {
                    dayOfWeek = DayOfWeek.Wednesday;
                    goto IL_00D5;
                }
            }
            bytesConsumed = 0;
            dateTimeOffset = default(DateTimeOffset);
            return false;
            IL_00D5:
            if (*source[4] != 32)
            {
                bytesConsumed = 0;
                dateTimeOffset = default(DateTimeOffset);
                return false;
            }
            uint num6 = (uint)(*source[5] - 48);
            uint num7 = (uint)(*source[6] - 48);
            if (num6 > 9U || num7 > 9U)
            {
                bytesConsumed = 0;
                dateTimeOffset = default(DateTimeOffset);
                return false;
            }
            int num8 = (int)(num6 * 10U + num7);
            if (*source[7] != 32)
            {
                bytesConsumed = 0;
                dateTimeOffset = default(DateTimeOffset);
                return false;
            }
            uint num9 = (uint)(*source[8]) ^ caseFlipXorMask;
            uint num10 = (uint)(*source[9]);
            uint num11 = (uint)(*source[10]);
            uint num12 = (uint)(*source[11]);
            uint num13 = (num9 << 24) | (num10 << 16) | (num11 << 8) | num12;
            int num14;
            if (num13 <= 1249209376U)
            {
                if (num13 <= 1147495200U)
                {
                    if (num13 == 1097888288U)
                    {
                        num14 = 4;
                        goto IL_0261;
                    }
                    if (num13 == 1098213152U)
                    {
                        num14 = 8;
                        goto IL_0261;
                    }
                    if (num13 == 1147495200U)
                    {
                        num14 = 12;
                        goto IL_0261;
                    }
                }
                else
                {
                    if (num13 == 1181049376U)
                    {
                        num14 = 2;
                        goto IL_0261;
                    }
                    if (num13 == 1247899168U)
                    {
                        num14 = 1;
                        goto IL_0261;
                    }
                    if (num13 == 1249209376U)
                    {
                        num14 = 7;
                        goto IL_0261;
                    }
                }
            }
            else if (num13 <= 1298233632U)
            {
                if (num13 == 1249209888U)
                {
                    num14 = 6;
                    goto IL_0261;
                }
                if (num13 == 1298231840U)
                {
                    num14 = 3;
                    goto IL_0261;
                }
                if (num13 == 1298233632U)
                {
                    num14 = 5;
                    goto IL_0261;
                }
            }
            else
            {
                if (num13 == 1315927584U)
                {
                    num14 = 11;
                    goto IL_0261;
                }
                if (num13 == 1331917856U)
                {
                    num14 = 10;
                    goto IL_0261;
                }
                if (num13 == 1399156768U)
                {
                    num14 = 9;
                    goto IL_0261;
                }
            }
            bytesConsumed = 0;
            dateTimeOffset = default(DateTimeOffset);
            return false;
            IL_0261:
            uint num15 = (uint)(*source[12] - 48);
            uint num16 = (uint)(*source[13] - 48);
            uint num17 = (uint)(*source[14] - 48);
            uint num18 = (uint)(*source[15] - 48);
            if (num15 > 9U || num16 > 9U || num17 > 9U || num18 > 9U)
            {
                bytesConsumed = 0;
                dateTimeOffset = default(DateTimeOffset);
                return false;
            }
            int num19 = (int)(num15 * 1000U + num16 * 100U + num17 * 10U + num18);
            if (*source[16] != 32)
            {
                bytesConsumed = 0;
                dateTimeOffset = default(DateTimeOffset);
                return false;
            }
            uint num20 = (uint)(*source[17] - 48);
            uint num21 = (uint)(*source[18] - 48);
            if (num20 > 9U || num21 > 9U)
            {
                bytesConsumed = 0;
                dateTimeOffset = default(DateTimeOffset);
                return false;
            }
            int num22 = (int)(num20 * 10U + num21);
            if (*source[19] != 58)
            {
                bytesConsumed = 0;
                dateTimeOffset = default(DateTimeOffset);
                return false;
            }
            uint num23 = (uint)(*source[20] - 48);
            uint num24 = (uint)(*source[21] - 48);
            if (num23 > 9U || num24 > 9U)
            {
                bytesConsumed = 0;
                dateTimeOffset = default(DateTimeOffset);
                return false;
            }
            int num25 = (int)(num23 * 10U + num24);
            if (*source[22] != 58)
            {
                bytesConsumed = 0;
                dateTimeOffset = default(DateTimeOffset);
                return false;
            }
            uint num26 = (uint)(*source[23] - 48);
            uint num27 = (uint)(*source[24] - 48);
            if (num26 > 9U || num27 > 9U)
            {
                bytesConsumed = 0;
                dateTimeOffset = default(DateTimeOffset);
                return false;
            }
            int num28 = (int)(num26 * 10U + num27);
            uint num29 = (uint)(*source[25]);
            uint num30 = (uint)(*source[26]) ^ caseFlipXorMask;
            uint num31 = (uint)(*source[27]) ^ caseFlipXorMask;
            uint num32 = (uint)(*source[28]) ^ caseFlipXorMask;
            if (((num29 << 24) | (num30 << 16) | (num31 << 8) | num32) != 541543764U)
            {
                bytesConsumed = 0;
                dateTimeOffset = default(DateTimeOffset);
                return false;
            }
            if (!Utf8Parser.TryCreateDateTimeOffset(num19, num14, num8, num22, num25, num28, 0, false, 0, 0, out dateTimeOffset))
            {
                bytesConsumed = 0;
                dateTimeOffset = default(DateTimeOffset);
                return false;
            }
            if (dayOfWeek != dateTimeOffset.DayOfWeek)
            {
                bytesConsumed = 0;
                dateTimeOffset = default(DateTimeOffset);
                return false;
            }
            bytesConsumed = 29;
            return true;
        }
References int, System.source, System.Buffers.Text.Utf8Parser.TryCreateDateTimeOffset(), and System.U.
Referenced by System.Buffers.Text.Utf8Parser.TryParse(), and System.Buffers.Text.Utf8Parser.TryParse().