Terraria Decompiled: System.Buffers.Text.Utf8Parser.TryParseDateTimeOffsetO
TryParseDateTimeOffsetO()
static unsafe bool System.Buffers.Text.Utf8Parser.TryParseDateTimeOffsetO (ReadOnlySpan< byte > source, out DateTimeOffset value, out int bytesConsumed, out DateTimeKind kind) inline static private
Definition at line 343 of file Utf8Parser.cs.
        {
            if (source.Length < 27)
            {
                value = default(DateTimeOffset);
                bytesConsumed = 0;
                kind = DateTimeKind.Unspecified;
                return false;
            }
            uint num = (uint)(*source[0] - 48);
            uint num2 = (uint)(*source[1] - 48);
            uint num3 = (uint)(*source[2] - 48);
            uint num4 = (uint)(*source[3] - 48);
            if (num > 9U || num2 > 9U || num3 > 9U || num4 > 9U)
            {
                value = default(DateTimeOffset);
                bytesConsumed = 0;
                kind = DateTimeKind.Unspecified;
                return false;
            }
            int num5 = (int)(num * 1000U + num2 * 100U + num3 * 10U + num4);
            if (*source[4] != 45)
            {
                value = default(DateTimeOffset);
                bytesConsumed = 0;
                kind = DateTimeKind.Unspecified;
                return false;
            }
            uint num6 = (uint)(*source[5] - 48);
            uint num7 = (uint)(*source[6] - 48);
            if (num6 > 9U || num7 > 9U)
            {
                value = default(DateTimeOffset);
                bytesConsumed = 0;
                kind = DateTimeKind.Unspecified;
                return false;
            }
            int num8 = (int)(num6 * 10U + num7);
            if (*source[7] != 45)
            {
                value = default(DateTimeOffset);
                bytesConsumed = 0;
                kind = DateTimeKind.Unspecified;
                return false;
            }
            uint num9 = (uint)(*source[8] - 48);
            uint num10 = (uint)(*source[9] - 48);
            if (num9 > 9U || num10 > 9U)
            {
                value = default(DateTimeOffset);
                bytesConsumed = 0;
                kind = DateTimeKind.Unspecified;
                return false;
            }
            int num11 = (int)(num9 * 10U + num10);
            if (*source[10] != 84)
            {
                value = default(DateTimeOffset);
                bytesConsumed = 0;
                kind = DateTimeKind.Unspecified;
                return false;
            }
            uint num12 = (uint)(*source[11] - 48);
            uint num13 = (uint)(*source[12] - 48);
            if (num12 > 9U || num13 > 9U)
            {
                value = default(DateTimeOffset);
                bytesConsumed = 0;
                kind = DateTimeKind.Unspecified;
                return false;
            }
            int num14 = (int)(num12 * 10U + num13);
            if (*source[13] != 58)
            {
                value = default(DateTimeOffset);
                bytesConsumed = 0;
                kind = DateTimeKind.Unspecified;
                return false;
            }
            uint num15 = (uint)(*source[14] - 48);
            uint num16 = (uint)(*source[15] - 48);
            if (num15 > 9U || num16 > 9U)
            {
                value = default(DateTimeOffset);
                bytesConsumed = 0;
                kind = DateTimeKind.Unspecified;
                return false;
            }
            int num17 = (int)(num15 * 10U + num16);
            if (*source[16] != 58)
            {
                value = default(DateTimeOffset);
                bytesConsumed = 0;
                kind = DateTimeKind.Unspecified;
                return false;
            }
            uint num18 = (uint)(*source[17] - 48);
            uint num19 = (uint)(*source[18] - 48);
            if (num18 > 9U || num19 > 9U)
            {
                value = default(DateTimeOffset);
                bytesConsumed = 0;
                kind = DateTimeKind.Unspecified;
                return false;
            }
            int num20 = (int)(num18 * 10U + num19);
            if (*source[19] != 46)
            {
                value = default(DateTimeOffset);
                bytesConsumed = 0;
                kind = DateTimeKind.Unspecified;
                return false;
            }
            uint num21 = (uint)(*source[20] - 48);
            uint num22 = (uint)(*source[21] - 48);
            uint num23 = (uint)(*source[22] - 48);
            uint num24 = (uint)(*source[23] - 48);
            uint num25 = (uint)(*source[24] - 48);
            uint num26 = (uint)(*source[25] - 48);
            uint num27 = (uint)(*source[26] - 48);
            if (num21 > 9U || num22 > 9U || num23 > 9U || num24 > 9U || num25 > 9U || num26 > 9U || num27 > 9U)
            {
                value = default(DateTimeOffset);
                bytesConsumed = 0;
                kind = DateTimeKind.Unspecified;
                return false;
            }
            int num28 = (int)(num21 * 1000000U + num22 * 100000U + num23 * 10000U + num24 * 1000U + num25 * 100U + num26 * 10U + num27);
            byte b = ((source.Length <= 27) ? 0 : (*source[27]));
            if (b != 90 && b != 43 && b != 45)
            {
                if (!Utf8Parser.TryCreateDateTimeOffsetInterpretingDataAsLocalTime(num5, num8, num11, num14, num17, num20, num28, out value))
                {
                    value = default(DateTimeOffset);
                    bytesConsumed = 0;
                    kind = DateTimeKind.Unspecified;
                    return false;
                }
                bytesConsumed = 27;
                kind = DateTimeKind.Unspecified;
                return true;
            }
            else if (b == 90)
            {
                if (!Utf8Parser.TryCreateDateTimeOffset(num5, num8, num11, num14, num17, num20, num28, false, 0, 0, out value))
                {
                    value = default(DateTimeOffset);
                    bytesConsumed = 0;
                    kind = DateTimeKind.Unspecified;
                    return false;
                }
                bytesConsumed = 28;
                kind = DateTimeKind.Utc;
                return true;
            }
            else
            {
                if (source.Length < 33)
                {
                    value = default(DateTimeOffset);
                    bytesConsumed = 0;
                    kind = DateTimeKind.Unspecified;
                    return false;
                }
                uint num29 = (uint)(*source[28] - 48);
                uint num30 = (uint)(*source[29] - 48);
                if (num29 > 9U || num30 > 9U)
                {
                    value = default(DateTimeOffset);
                    bytesConsumed = 0;
                    kind = DateTimeKind.Unspecified;
                    return false;
                }
                int num31 = (int)(num29 * 10U + num30);
                if (*source[30] != 58)
                {
                    value = default(DateTimeOffset);
                    bytesConsumed = 0;
                    kind = DateTimeKind.Unspecified;
                    return false;
                }
                uint num32 = (uint)(*source[31] - 48);
                uint num33 = (uint)(*source[32] - 48);
                if (num32 > 9U || num33 > 9U)
                {
                    value = default(DateTimeOffset);
                    bytesConsumed = 0;
                    kind = DateTimeKind.Unspecified;
                    return false;
                }
                int num34 = (int)(num32 * 10U + num33);
                if (!Utf8Parser.TryCreateDateTimeOffset(num5, num8, num11, num14, num17, num20, num28, b == 45, num31, num34, out value))
                {
                    value = default(DateTimeOffset);
                    bytesConsumed = 0;
                    kind = DateTimeKind.Unspecified;
                    return false;
                }
                bytesConsumed = 33;
                kind = DateTimeKind.Local;
                return true;
            }
        }
References int, System.source, System.Buffers.Text.Utf8Parser.TryCreateDateTimeOffset(), System.Buffers.Text.Utf8Parser.TryCreateDateTimeOffsetInterpretingDataAsLocalTime(), System.U, and System.value.
Referenced by System.Buffers.Text.Utf8Parser.TryParse(), and System.Buffers.Text.Utf8Parser.TryParse().