Terraria Decompiled: System.Buffers.Text.Utf8Parser.TryParseDateTimeG
TryParseDateTimeG()
static unsafe bool System.Buffers.Text.Utf8Parser.TryParseDateTimeG (ReadOnlySpan< byte > source, out DateTime value, out DateTimeOffset valueAsOffset, out int bytesConsumed) inline static private
Definition at line 107 of file Utf8Parser.cs.
        {
            if (source.Length < 19)
            {
                bytesConsumed = 0;
                value = default(DateTime);
                valueAsOffset = default(DateTimeOffset);
                return false;
            }
            uint num = (uint)(*source[0] - 48);
            uint num2 = (uint)(*source[1] - 48);
            if (num > 9U || num2 > 9U)
            {
                bytesConsumed = 0;
                value = default(DateTime);
                valueAsOffset = default(DateTimeOffset);
                return false;
            }
            int num3 = (int)(num * 10U + num2);
            if (*source[2] != 47)
            {
                bytesConsumed = 0;
                value = default(DateTime);
                valueAsOffset = default(DateTimeOffset);
                return false;
            }
            uint num4 = (uint)(*source[3] - 48);
            uint num5 = (uint)(*source[4] - 48);
            if (num4 > 9U || num5 > 9U)
            {
                bytesConsumed = 0;
                value = default(DateTime);
                valueAsOffset = default(DateTimeOffset);
                return false;
            }
            int num6 = (int)(num4 * 10U + num5);
            if (*source[5] != 47)
            {
                bytesConsumed = 0;
                value = default(DateTime);
                valueAsOffset = default(DateTimeOffset);
                return false;
            }
            uint num7 = (uint)(*source[6] - 48);
            uint num8 = (uint)(*source[7] - 48);
            uint num9 = (uint)(*source[8] - 48);
            uint num10 = (uint)(*source[9] - 48);
            if (num7 > 9U || num8 > 9U || num9 > 9U || num10 > 9U)
            {
                bytesConsumed = 0;
                value = default(DateTime);
                valueAsOffset = default(DateTimeOffset);
                return false;
            }
            int num11 = (int)(num7 * 1000U + num8 * 100U + num9 * 10U + num10);
            if (*source[10] != 32)
            {
                bytesConsumed = 0;
                value = default(DateTime);
                valueAsOffset = default(DateTimeOffset);
                return false;
            }
            uint num12 = (uint)(*source[11] - 48);
            uint num13 = (uint)(*source[12] - 48);
            if (num12 > 9U || num13 > 9U)
            {
                bytesConsumed = 0;
                value = default(DateTime);
                valueAsOffset = default(DateTimeOffset);
                return false;
            }
            int num14 = (int)(num12 * 10U + num13);
            if (*source[13] != 58)
            {
                bytesConsumed = 0;
                value = default(DateTime);
                valueAsOffset = default(DateTimeOffset);
                return false;
            }
            uint num15 = (uint)(*source[14] - 48);
            uint num16 = (uint)(*source[15] - 48);
            if (num15 > 9U || num16 > 9U)
            {
                bytesConsumed = 0;
                value = default(DateTime);
                valueAsOffset = default(DateTimeOffset);
                return false;
            }
            int num17 = (int)(num15 * 10U + num16);
            if (*source[16] != 58)
            {
                bytesConsumed = 0;
                value = default(DateTime);
                valueAsOffset = default(DateTimeOffset);
                return false;
            }
            uint num18 = (uint)(*source[17] - 48);
            uint num19 = (uint)(*source[18] - 48);
            if (num18 > 9U || num19 > 9U)
            {
                bytesConsumed = 0;
                value = default(DateTime);
                valueAsOffset = default(DateTimeOffset);
                return false;
            }
            int num20 = (int)(num18 * 10U + num19);
            if (!Utf8Parser.TryCreateDateTimeOffsetInterpretingDataAsLocalTime(num11, num3, num6, num14, num17, num20, 0, out valueAsOffset))
            {
                bytesConsumed = 0;
                value = default(DateTime);
                valueAsOffset = default(DateTimeOffset);
                return false;
            }
            bytesConsumed = 19;
            value = valueAsOffset.DateTime;
            return true;
        }
References int, System.source, System.Buffers.Text.Utf8Parser.TryCreateDateTimeOffsetInterpretingDataAsLocalTime(), System.U, and System.value.
Referenced by System.Buffers.Text.Utf8Parser.TryParse(), System.Buffers.Text.Utf8Parser.TryParse(), and System.Buffers.Text.Utf8Parser.TryParseDateTimeOffsetDefault().