Terraria Decompiled: System.Buffers.Text.Utf8Parser.TryParseNormalAsFloatingPoint
TryParseNormalAsFloatingPoint()
static unsafe bool System.Buffers.Text.Utf8Parser.TryParseNormalAsFloatingPoint (ReadOnlySpan< byte > source, out double value, out int bytesConsumed, char standardFormat) inline static private
Definition at line 985 of file Utf8Parser.cs.
        {
            Utf8Parser.ParseNumberOptions parseNumberOptions;
            if (standardFormat != '\0')
            {
                switch (standardFormat)
                {
                case 'E':
                case 'G':
                    goto IL_002F;
                case 'F':
                    break;
                default:
                    switch (standardFormat)
                    {
                    case 'e':
                    case 'g':
                        goto IL_002F;
                    case 'f':
                        break;
                    default:
                        return ThrowHelper.TryParseThrowFormatException<double>(out value, out bytesConsumed);
                    }
                    break;
                }
                parseNumberOptions = (Utf8Parser.ParseNumberOptions)0;
                goto IL_003F;
            }
            IL_002F:
            parseNumberOptions = Utf8Parser.ParseNumberOptions.AllowExponent;
            IL_003F:
            NumberBuffer numberBuffer = default(NumberBuffer);
            bool flag;
            if (!Utf8Parser.TryParseNumber(source, ref numberBuffer, out bytesConsumed, parseNumberOptions, out flag))
            {
                value = 0.0;
                return false;
            }
            if (!flag && (standardFormat == 'E' || standardFormat == 'e'))
            {
                value = 0.0;
                bytesConsumed = 0;
                return false;
            }
            if (*numberBuffer.Digits[0] == 0)
            {
                numberBuffer.IsNegative = false;
            }
            if (!Number.NumberBufferToDouble(ref numberBuffer, out value))
            {
                value = 0.0;
                bytesConsumed = 0;
                return false;
            }
            return true;
        }
References System.Buffers.Text.NumberBuffer.Digits, System.Buffers.Text.Number.NumberBufferToDouble(), System.source, System.Buffers.Text.Utf8Parser.TryParseNumber(), and System.value.
Referenced by System.Buffers.Text.Utf8Parser.TryParse(), and System.Buffers.Text.Utf8Parser.TryParse().