Terraria Decompiled: System.Buffers.Text.Utf8Parser.TryParseUInt16X
TryParseUInt16X()
static unsafe bool System.Buffers.Text.Utf8Parser.TryParseUInt16X (ReadOnlySpan< byte > source, out ushort value, out int bytesConsumed) inline static private
Definition at line 3080 of file Utf8Parser.cs.
        {
            if (source.Length < 1)
            {
                bytesConsumed = 0;
                value = 0;
                return false;
            }
            byte[] s_hexLookup = ParserHelpers.s_hexLookup;
            byte b = *source[0];
            byte b2 = s_hexLookup[(int)b];
            if (b2 == 255)
            {
                bytesConsumed = 0;
                value = 0;
                return false;
            }
            uint num = (uint)b2;
            if (source.Length <= 4)
            {
                for (int i = 1; i < source.Length; i++)
                {
                    b = *source[i];
                    b2 = s_hexLookup[(int)b];
                    if (b2 == 255)
                    {
                        bytesConsumed = i;
                        value = (ushort)num;
                        return true;
                    }
                    num = (num << 4) + (uint)b2;
                }
            }
            else
            {
                for (int j = 1; j < 4; j++)
                {
                    b = *source[j];
                    b2 = s_hexLookup[(int)b];
                    if (b2 == 255)
                    {
                        bytesConsumed = j;
                        value = (ushort)num;
                        return true;
                    }
                    num = (num << 4) + (uint)b2;
                }
                for (int k = 4; k < source.Length; k++)
                {
                    b = *source[k];
                    b2 = s_hexLookup[(int)b];
                    if (b2 == 255)
                    {
                        bytesConsumed = k;
                        value = (ushort)num;
                        return true;
                    }
                    if (num > 4095U)
                    {
                        bytesConsumed = 0;
                        value = 0;
                        return false;
                    }
                    num = (num << 4) + (uint)b2;
                }
            }
            bytesConsumed = source.Length;
            value = (ushort)num;
            return true;
        }
References int, System.Buffers.Text.ParserHelpers.s_hexLookup, System.source, System.U, and System.value.
Referenced by System.Buffers.Text.Utf8Parser.TryParse(), System.Buffers.Text.Utf8Parser.TryParse(), System.Buffers.Text.Utf8Parser.TryParseGuidCore(), and System.Buffers.Text.Utf8Parser.TryParseGuidN().