Terraria Decompiled: System.Buffers.Text.Utf8Parser.TryParseUInt64X
TryParseUInt64X()
static unsafe bool System.Buffers.Text.Utf8Parser.TryParseUInt64X (ReadOnlySpan< byte > source, out ulong value, out int bytesConsumed) inline static private
Definition at line 3224 of file Utf8Parser.cs.
        {
            if (source.Length < 1)
            {
                bytesConsumed = 0;
                value = 0UL;
                return false;
            }
            byte[] s_hexLookup = ParserHelpers.s_hexLookup;
            byte b = *source[0];
            byte b2 = s_hexLookup[(int)b];
            if (b2 == 255)
            {
                bytesConsumed = 0;
                value = 0UL;
                return false;
            }
            ulong num = (ulong)b2;
            if (source.Length <= 16)
            {
                for (int i = 1; i < source.Length; i++)
                {
                    b = *source[i];
                    b2 = s_hexLookup[(int)b];
                    if (b2 == 255)
                    {
                        bytesConsumed = i;
                        value = num;
                        return true;
                    }
                    num = (num << 4) + (ulong)b2;
                }
            }
            else
            {
                for (int j = 1; j < 16; j++)
                {
                    b = *source[j];
                    b2 = s_hexLookup[(int)b];
                    if (b2 == 255)
                    {
                        bytesConsumed = j;
                        value = num;
                        return true;
                    }
                    num = (num << 4) + (ulong)b2;
                }
                for (int k = 16; k < source.Length; k++)
                {
                    b = *source[k];
                    b2 = s_hexLookup[(int)b];
                    if (b2 == 255)
                    {
                        bytesConsumed = k;
                        value = num;
                        return true;
                    }
                    if (num > 1152921504606846975UL)
                    {
                        bytesConsumed = 0;
                        value = 0UL;
                        return false;
                    }
                    num = (num << 4) + (ulong)b2;
                }
            }
            bytesConsumed = source.Length;
            value = num;
            return true;
        }
References int, System.Buffers.Text.ParserHelpers.s_hexLookup, System.source, and System.value.
Referenced by System.Buffers.Text.Utf8Parser.TryParse(), System.Buffers.Text.Utf8Parser.TryParse(), System.Buffers.Text.Utf8Parser.TryParseGuidCore(), and System.Buffers.Text.Utf8Parser.TryParseGuidN().