Terraria Decompiled: System.Buffers.Text.Utf8Parser.TryParse
TryParse() [10/16]
static bool System.Buffers.Text.Utf8Parser.TryParse (ReadOnlySpan< byte > source, out long value, out int bytesConsumed, char standardFormat = '\0') inline static
Definition at line 2270 of file Utf8Parser.cs.
        {
            if (standardFormat > 'N')
            {
                if (standardFormat <= 'd')
                {
                    if (standardFormat != 'X')
                    {
                        if (standardFormat != 'd')
{
                            goto IL_0066;
                        }
                        goto IL_0042;
                    }
                }
                else
                {
                    if (standardFormat == 'g')
                    {
                        goto IL_0042;
                    }
                    if (standardFormat == 'n')
                    {
                        goto IL_004B;
                    }
                    if (standardFormat != 'x')
                    {
                        goto IL_0066;
                    }
                }
                value = 0L;
                return Utf8Parser.TryParseUInt64X(source, Unsafe.As<long, ulong>(ref value), out bytesConsumed);
            }
            if (standardFormat <= 'D')
            {
                if (standardFormat != '\0' && standardFormat != 'D')
                {
                    goto IL_0066;
                }
            }
            else if (standardFormat != 'G')
            {
                if (standardFormat != 'N')
                {
                    goto IL_0066;
                }
                goto IL_004B;
            }
            IL_0042:
            return Utf8Parser.TryParseInt64D(source, out value, out bytesConsumed);
            IL_004B:
            return Utf8Parser.TryParseInt64N(source, out value, out bytesConsumed);
            IL_0066:
            return ThrowHelper.TryParseThrowFormatException<long>(out value, out bytesConsumed);
        }
References System.L, System.source, System.Buffers.Text.Utf8Parser.TryParseInt64D(), System.Buffers.Text.Utf8Parser.TryParseInt64N(), System.Buffers.Text.Utf8Parser.TryParseUInt64X(), and System.value.