Terraria Decompiled: System.Buffers.Text.Utf8Parser.TryParse
TryParse() [9/16]
static bool System.Buffers.Text.Utf8Parser.TryParse (ReadOnlySpan< byte > source, out int value, out int bytesConsumed, char standardFormat = '\0') inline static
Definition at line 2213 of file Utf8Parser.cs.
        {
            if (standardFormat > 'N')
            {
                if (standardFormat <= 'd')
                {
                    if (standardFormat != 'X')
                    {
                        if (standardFormat != 'd')
{
                            goto IL_0065;
                        }
                        goto IL_0042;
                    }
                }
                else
                {
                    if (standardFormat == 'g')
                    {
                        goto IL_0042;
                    }
                    if (standardFormat == 'n')
                    {
                        goto IL_004B;
                    }
                    if (standardFormat != 'x')
                    {
                        goto IL_0065;
                    }
                }
                value = 0;
                return Utf8Parser.TryParseUInt32X(source, Unsafe.As<int, uint>(ref value), out bytesConsumed);
            }
            if (standardFormat <= 'D')
            {
                if (standardFormat != '\0' && standardFormat != 'D')
                {
                    goto IL_0065;
                }
            }
            else if (standardFormat != 'G')
            {
                if (standardFormat != 'N')
                {
                    goto IL_0065;
                }
                goto IL_004B;
            }
            IL_0042:
            return Utf8Parser.TryParseInt32D(source, out value, out bytesConsumed);
            IL_004B:
            return Utf8Parser.TryParseInt32N(source, out value, out bytesConsumed);
            IL_0065:
            return ThrowHelper.TryParseThrowFormatException<int>(out value, out bytesConsumed);
        }
References System.source, System.Buffers.Text.Utf8Parser.TryParseInt32D(), System.Buffers.Text.Utf8Parser.TryParseInt32N(), System.Buffers.Text.Utf8Parser.TryParseUInt32X(), and System.value.