Terraria Decompiled: System.Buffers.Text.Utf8Parser.TryParse
TryParse() [4/16]
static bool System.Buffers.Text.Utf8Parser.TryParse (ReadOnlySpan< byte > source, out DateTimeOffset value, out int bytesConsumed, char standardFormat = '\0') inline static
Definition at line 868 of file Utf8Parser.cs.
        {
            if (standardFormat <= 'G')
            {
                if (standardFormat == '\0')
                {
                    return Utf8Parser.TryParseDateTimeOffsetDefault(source, out value, out bytesConsumed);
                }
                if (standardFormat == 'G')
                {
                    DateTime dateTime;
                    return Utf8Parser.TryParseDateTimeG(source, out dateTime, out value, out bytesConsumed);
                }
            }
            else
            {
                if (standardFormat == 'O')
                {
                    DateTimeKind dateTimeKind;
                    return Utf8Parser.TryParseDateTimeOffsetO(source, out value, out bytesConsumed, out dateTimeKind);
                }
                if (standardFormat == 'R')
                {
                    return Utf8Parser.TryParseDateTimeOffsetR(source, 0U, out value, out bytesConsumed);
                }
                if (standardFormat == 'l')
                {
                    return Utf8Parser.TryParseDateTimeOffsetR(source, 32U, out value, out bytesConsumed);
                }
            }
            return ThrowHelper.TryParseThrowFormatException<DateTimeOffset>(out value, out bytesConsumed);
        }
References System.source, System.Buffers.Text.Utf8Parser.TryParseDateTimeG(), System.Buffers.Text.Utf8Parser.TryParseDateTimeOffsetDefault(), System.Buffers.Text.Utf8Parser.TryParseDateTimeOffsetO(), System.Buffers.Text.Utf8Parser.TryParseDateTimeOffsetR(), System.U, and System.value.