Terraria Decompiled: System.Runtime.Remoting.SoapServices.GetXmlNamespaceForMethodResponse
GetXmlNamespaceForMethodResponse()
static string System.Runtime.Remoting.SoapServices.GetXmlNamespaceForMethodResponse (MethodBase mb) inline static
Definition at line 258 of file SoapServices.cs.
        {
            return SoapServices.CodeXmlNamespaceForClrTypeNamespace(mb.DeclaringType.FullName, SoapServices.GetAssemblyName(mb));
        }
References System.Runtime.Remoting.SoapServices.CodeXmlNamespaceForClrTypeNamespace(), System.Reflection.MemberInfo.DeclaringType, System.Type.FullName, and System.Runtime.Remoting.SoapServices.GetAssemblyName().
Referenced by System.Runtime.Remoting.Metadata.SoapMethodAttribute.SetReflectionObject().