Terraria Decompiled: Terraria.GameContent.Skies.VortexSky.Update
Update()
override void Terraria.GameContent.Skies.VortexSky.Update (GameTime gameTime) inline
Definition at line 23 of file VortexSky.cs.
        {
            if (this._isActive)
            {
                this._fadeOpacity = Math.Min(1f, 0.01f + this._fadeOpacity);
            }
            else
            {
                this._fadeOpacity = Math.Max(0f, this._fadeOpacity - 0.01f);
            }
            if (this._ticksUntilNextBolt <= 0)
            {
                this._ticksUntilNextBolt = this._random.Next(1, 5);
                int num = 0;
                while (this._bolts[num].IsAlive && num != this._bolts.Length - 1)
                {
                    num++;
                }
                this._bolts[num].IsAlive = true;
                this._bolts[num].Position.X = this._random.NextFloat() * ((float)Main.maxTilesX * 16f + 4000f) - 2000f;
                this._bolts[num].Position.Y = this._random.NextFloat() * 500f;
                this._bolts[num].Depth = this._random.NextFloat() * 8f + 2f;
                this._bolts[num].Life = 30;
            }
            this._ticksUntilNextBolt--;
            for (int i = 0; i < this._bolts.Length; i++)
            {
                if (this._bolts[i].IsAlive)
                {
                    VortexSky.Bolt[] bolts = this._bolts;
                    int num2 = i;
                    bolts[num2].Life = bolts[num2].Life - 1;
                    if (this._bolts[i].Life <= 0)
                    {
                        this._bolts[i].IsAlive = false;
                    }
                }
            }
        }
References Terraria.GameContent.Skies.VortexSky._bolts, Terraria.GameContent.Skies.VortexSky._fadeOpacity, Terraria.GameContent.Skies.VortexSky._isActive, Terraria.GameContent.Skies.VortexSky._random, Terraria.GameContent.Skies.VortexSky._ticksUntilNextBolt, System.Math.Max(), Terraria.Main.maxTilesX, System.Math.Min(), and Terraria.Utilities.UnifiedRandom.Next().