Terraria Decompiled: System.Runtime.Remoting.SoapServices.PreLoad
PreLoad() [2/2]
static void System.Runtime.Remoting.SoapServices.PreLoad (Type type) inline static
Definition at line 309 of file SoapServices.cs.
        {
            SoapServices.TypeInfo typeInfo = SoapServices._typeInfos[type] as SoapServices.TypeInfo;
            if (typeInfo != null)
            {
                return;
            }
            string text;
            string text2;
            if (SoapServices.GetXmlTypeForInteropType(type, out text, out text2))
            {
                SoapServices.RegisterInteropXmlType(text, text2, type);
            }
            if (SoapServices.GetXmlElementForInteropType(type, out text, out text2))
            {
                SoapServices.RegisterInteropXmlElement(text, text2, type);
            }
            object syncRoot = SoapServices._typeInfos.SyncRoot;
            lock (syncRoot)
            {
                typeInfo = new SoapServices.TypeInfo();
                foreach (FieldInfo fieldInfo in type.GetFields(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic))
                {
                    SoapFieldAttribute soapFieldAttribute = (SoapFieldAttribute)InternalRemotingServices.GetCachedSoapAttribute(fieldInfo);
                    if (soapFieldAttribute.IsInteropXmlElement())
                    {
                        string nameKey = SoapServices.GetNameKey(soapFieldAttribute.XmlElementName, soapFieldAttribute.XmlNamespace);
                        if (soapFieldAttribute.UseAttribute)
{
                            if (typeInfo.Attributes == null)
{
                                typeInfo.Attributes = new Hashtable();
                            }
                            typeInfo.Attributes[nameKey] = fieldInfo;
                        }
                        else
{
                            if (typeInfo.Elements == null)
{
                                typeInfo.Elements = new Hashtable();
                            }
                            typeInfo.Elements[nameKey] = fieldInfo;
                        }
                    }
                }
                SoapServices._typeInfos[type] = typeInfo;
            }
        }
References System.Runtime.Remoting.SoapServices._typeInfos, System.Runtime.Remoting.SoapServices.TypeInfo.Attributes, System.Runtime.Remoting.SoapServices.TypeInfo.Elements, System.Runtime.Remoting.InternalRemotingServices.GetCachedSoapAttribute(), System.Type.GetFields(), System.Runtime.Remoting.SoapServices.GetNameKey(), System.Runtime.Remoting.SoapServices.GetXmlElementForInteropType(), System.Runtime.Remoting.SoapServices.GetXmlTypeForInteropType(), System.Runtime.Remoting.Metadata.SoapFieldAttribute.IsInteropXmlElement(), System.Runtime.Remoting.SoapServices.RegisterInteropXmlElement(), System.Runtime.Remoting.SoapServices.RegisterInteropXmlType(), System.Collections.Hashtable.SyncRoot, System.text, System.Runtime.Remoting.Metadata.SoapAttribute.UseAttribute, System.Runtime.Remoting.Metadata.SoapFieldAttribute.XmlElementName, and System.Runtime.Remoting.Metadata.SoapAttribute.XmlNamespace.