Terraria Decompiled: System.Runtime.Remoting.SoapServices.GetAssemblyName
GetAssemblyName()
static string System.Runtime.Remoting.SoapServices.GetAssemblyName (MethodBase mb) inline static private
Definition at line 182 of file SoapServices.cs.
        {
            if (mb.DeclaringType.Assembly == typeof(object).Assembly)
            {
                return string.Empty;
            }
            return mb.DeclaringType.Assembly.GetName().Name;
        }
References System.Type.Assembly, System.Reflection.MemberInfo.DeclaringType, System.Reflection.Assembly.GetName(), and System.Reflection.AssemblyName.Name.
Referenced by System.Runtime.Remoting.SoapServices.GetXmlNamespaceForMethodCall(), and System.Runtime.Remoting.SoapServices.GetXmlNamespaceForMethodResponse().