Terraria Decompiled: Terraria.UI.Gamepad.GamepadMainMenuHandler.Update
Update()
static void Terraria.UI.Gamepad.GamepadMainMenuHandler.Update () inline static
Definition at line 12 of file GamepadMainMenuHandler.cs.
        {
            if (!GamepadMainMenuHandler.CanRun)
            {
                UILinkPage uilinkPage = UILinkPointNavigator.Pages[1000];
                uilinkPage.CurrentPoint = uilinkPage.DefaultPoint;
                Vector2 vector = new Vector2((float)Math.Cos((double)(Main.GlobalTimeWrappedHourly * 6.2831855f)), (float)Math.Sin((double)(Main.GlobalTimeWrappedHourly * 6.2831855f * 2f))) * new Vector2(30f, 15f) + Vector2.UnitY * 20f;
                UILinkPointNavigator.SetPosition(2000, new Vector2((float)Main.screenWidth, (float)Main.screenHeight) / 2f + vector);
                return;
            }
            if (!Main.gameMenu)
            {
                return;
            }
            if (Main.MenuUI.IsVisible)
            {
                return;
            }
            if (GamepadMainMenuHandler.LastDrew != Main.menuMode)
            {
                return;
            }
            int lastMainMenu = GamepadMainMenuHandler.LastMainMenu;
            GamepadMainMenuHandler.LastMainMenu = Main.menuMode;
            switch (Main.menuMode)
            {
            case 17:
            case 18:
            case 19:
            case 21:
            case 22:
            case 23:
            case 24:
            case 26:
                if (GamepadMainMenuHandler.MenuItemPositions.Count >= 4)
                {
                    Vector2 vector2 = GamepadMainMenuHandler.MenuItemPositions[3];
                    GamepadMainMenuHandler.MenuItemPositions.RemoveAt(3);
                    if (Main.menuMode == 17)
                    {
                        GamepadMainMenuHandler.MenuItemPositions.Insert(0, vector2);
                    }
                }
                break;
            case 28:
                if (GamepadMainMenuHandler.MenuItemPositions.Count >= 3)
                {
                    GamepadMainMenuHandler.MenuItemPositions.RemoveAt(1);
                }
                break;
            }
            UILinkPage uilinkPage2 = UILinkPointNavigator.Pages[1000];
            if (lastMainMenu != Main.menuMode)
            {
                uilinkPage2.CurrentPoint = uilinkPage2.DefaultPoint;
            }
            for (int i = 0; i < GamepadMainMenuHandler.MenuItemPositions.Count; i++)
            {
                Vector2 vector3 = GamepadMainMenuHandler.MenuItemPositions[i] * Main.UIScale;
                if (i == 0 && lastMainMenu != GamepadMainMenuHandler.LastMainMenu && PlayerInput.UsingGamepad && Main.InvisibleCursorForGamepad)
                {
                    Main.mouseX = (PlayerInput.MouseX = (int)vector3.X);
                    Main.mouseY = (PlayerInput.MouseY = (int)vector3.Y);
                    Main.menuFocus = -1;
                }
                UILinkPoint uilinkPoint = uilinkPage2.LinkMap[2000 + i];
                uilinkPoint.Position = vector3;
                if (i == 0)
                {
                    uilinkPoint.Up = -1;
                }
                else
                {
                    uilinkPoint.Up = 2000 + i - 1;
                }
                uilinkPoint.Left = -3;
                uilinkPoint.Right = -4;
                if (i == GamepadMainMenuHandler.MenuItemPositions.Count - 1)
                {
                    uilinkPoint.Down = -2;
                }
                else
                {
                    uilinkPoint.Down = 2000 + i + 1;
                }
                if (GamepadMainMenuHandler.MoveCursorOnNextRun)
                {
                    GamepadMainMenuHandler.MoveCursorOnNextRun = false;
                    UILinkPointNavigator.ChangePoint(uilinkPoint.ID);
                }
            }
            GamepadMainMenuHandler.MenuItemPositions.Clear();
        }
References Terraria.UI.Gamepad.GamepadMainMenuHandler.CanRun, Terraria.UI.Gamepad.UILinkPointNavigator.ChangePoint(), System.Collections.Generic.List< T >.Clear(), System.Math.Cos(), System.Collections.Generic.List< T >.Count, Terraria.UI.Gamepad.UILinkPage.DefaultPoint, Terraria.Main.gameMenu, Terraria.Main.GlobalTimeWrappedHourly, Terraria.UI.Gamepad.UILinkPoint.ID, System.Collections.Generic.List< T >.Insert(), int, Terraria.Main.InvisibleCursorForGamepad, Terraria.UI.Gamepad.GamepadMainMenuHandler.LastDrew, Terraria.UI.Gamepad.GamepadMainMenuHandler.LastMainMenu, Terraria.UI.Gamepad.UILinkPage.LinkMap, Terraria.UI.Gamepad.GamepadMainMenuHandler.MenuItemPositions, Terraria.Main.menuMode, Terraria.Main.MenuUI, Terraria.UI.Gamepad.GamepadMainMenuHandler.MoveCursorOnNextRun, Terraria.UI.Gamepad.UILinkPointNavigator.Pages, System.Collections.Generic.List< T >.RemoveAt(), Terraria.Main.screenHeight, Terraria.Main.screenWidth, Terraria.UI.Gamepad.UILinkPointNavigator.SetPosition(), System.Math.Sin(), Terraria.Main.UIScale, Terraria.GameInput.PlayerInput.UsingGamepad, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Main.DrawMenu().