Terraria Decompiled: FullSerializer.Internal.fsPrimitiveConverter.TrySerialize
TrySerialize()
override fsResult FullSerializer.Internal.fsPrimitiveConverter.TrySerialize (object instance, out fsData serialized, Type storageType) inline
Definition at line 51 of file fsPrimitiveConverter.cs.
        {
            Type type = instance.GetType();
            if (this.Serializer.Config.Serialize64BitIntegerAsString && (type == typeof(long) || type == typeof(ulong)))
            {
                serialized = new fsData((string)Convert.ChangeType(instance, typeof(string)));
                return fsResult.Success;
            }
            if (fsPrimitiveConverter.UseBool(type))
            {
                serialized = new fsData((bool)instance);
                return fsResult.Success;
            }
            if (fsPrimitiveConverter.UseInt64(type))
            {
                serialized = new fsData((long)Convert.ChangeType(instance, typeof(long)));
                return fsResult.Success;
            }
            if (fsPrimitiveConverter.UseDouble(type))
            {
                if (instance.GetType() == typeof(float) && (float)instance != -3.4028235E+38f && (float)instance != 3.4028235E+38f && !float.IsInfinity((float)instance) && !float.IsNaN((float)instance))
                {
                    serialized = new fsData((double)((decimal)((float)instance)));
                    return fsResult.Success;
                }
                serialized = new fsData((double)Convert.ChangeType(instance, typeof(double)));
                return fsResult.Success;
            }
            else
            {
                if (fsPrimitiveConverter.UseString(type))
                {
                    serialized = new fsData((string)Convert.ChangeType(instance, typeof(string)));
                    return fsResult.Success;
                }
                serialized = null;
                return fsResult.Fail("Unhandled primitive type " + instance.GetType());
            }
        }
References System.Convert.ChangeType(), FullSerializer.fsSerializer.Config, System.E, FullSerializer.fsResult.Fail(), FullSerializer.fsConfig.Serialize64BitIntegerAsString, FullSerializer.fsBaseConverter.Serializer, FullSerializer.fsResult.Success, FullSerializer.Internal.fsPrimitiveConverter.UseBool(), FullSerializer.Internal.fsPrimitiveConverter.UseDouble(), FullSerializer.Internal.fsPrimitiveConverter.UseInt64(), and FullSerializer.Internal.fsPrimitiveConverter.UseString().