Terraria Decompiled: FullSerializer.Internal.fsPrimitiveConverter.TryDeserialize
TryDeserialize()
override fsResult FullSerializer.Internal.fsPrimitiveConverter.TryDeserialize (fsData storage, ref object instance, Type storageType) inline
Definition at line 92 of file fsPrimitiveConverter.cs.
        {
            fsResult fsResult = fsResult.Success;
            if (fsPrimitiveConverter.UseBool(storageType))
            {
                fsResult fsResult2;
                fsResult = (fsResult2 = fsResult + base.CheckType(storage, fsDataType.Boolean));
                if (fsResult2.Succeeded)
                {
                    instance = storage.AsBool;
                }
                return fsResult;
            }
            if (fsPrimitiveConverter.UseDouble(storageType) || fsPrimitiveConverter.UseInt64(storageType))
            {
                if (storage.IsDouble)
                {
                    instance = Convert.ChangeType(storage.AsDouble, storageType);
                }
                else if (storage.IsInt64)
                {
                    instance = Convert.ChangeType(storage.AsInt64, storageType);
                }
                else
                {
                    if (!this.Serializer.Config.Serialize64BitIntegerAsString || !storage.IsString || (!(storageType == typeof(long)) && !(storageType == typeof(ulong))))
                    {
                        return fsResult.Fail(string.Concat(new object[]
{
                            base.GetType().Name,
                            " expected number but got ",
                            storage.Type,
                            " in ",
                            storage
                        }));
                    }
                    instance = Convert.ChangeType(storage.AsString, storageType);
                }
                return fsResult.Success;
            }
            if (fsPrimitiveConverter.UseString(storageType))
            {
                fsResult fsResult2;
                fsResult = (fsResult2 = fsResult + base.CheckType(storage, fsDataType.String));
                if (fsResult2.Succeeded)
                {
                    instance = storage.AsString;
                }
                return fsResult;
            }
            return fsResult.Fail(base.GetType().Name + ": Bad data; expected bool, number, string, but got " + storage);
        }
References FullSerializer.fsData.AsBool, FullSerializer.fsData.AsDouble, FullSerializer.fsData.AsInt64, FullSerializer.fsData.AsString, System.Convert.ChangeType(), FullSerializer.fsSerializer.Config, FullSerializer.fsResult.Fail(), FullSerializer.fsData.IsDouble, FullSerializer.fsData.IsInt64, FullSerializer.fsData.IsString, System.Name, FullSerializer.fsConfig.Serialize64BitIntegerAsString, FullSerializer.fsBaseConverter.Serializer, FullSerializer.fsResult.Succeeded, FullSerializer.fsResult.Success, FullSerializer.fsData.Type, FullSerializer.Internal.fsPrimitiveConverter.UseBool(), FullSerializer.Internal.fsPrimitiveConverter.UseDouble(), FullSerializer.Internal.fsPrimitiveConverter.UseInt64(), and FullSerializer.Internal.fsPrimitiveConverter.UseString().