Terraria Decompiled: rail.IRailGameServerImpl.AsyncSetMetadata
AsyncSetMetadata()
virtual RailResult rail.IRailGameServerImpl.AsyncSetMetadata (List< RailKeyValue > key_values, string user_data) inline virtual
Implements rail.IRailGameServer.
Definition at line 340 of file IRailGameServerImpl.cs.
        {
            IntPtr intPtr = ((key_values == null) ? IntPtr.Zero : RAIL_API_PINVOKE.new_RailArrayRailKeyValue__SWIG_0());
            if (key_values != null)
            {
                RailConverter.Csharp2Cpp(key_values, intPtr);
            }
            RailResult railResult;
            try
            {
                railResult = (RailResult)RAIL_API_PINVOKE.IRailGameServer_AsyncSetMetadata(this.swigCPtr_, intPtr, user_data);
            }
            finally
            {
                RAIL_API_PINVOKE.delete_RailArrayRailKeyValue(intPtr);
            }
            return railResult;
        }
References rail.RailConverter.Csharp2Cpp(), rail.RAIL_API_PINVOKE.delete_RailArrayRailKeyValue(), rail.RAIL_API_PINVOKE.IRailGameServer_AsyncSetMetadata(), rail.RAIL_API_PINVOKE.new_RailArrayRailKeyValue__SWIG_0(), and System.IntPtr.Zero.