Terraria Decompiled: rail.IRailGameServerImpl.ReportPlayerQuitGameServer
ReportPlayerQuitGameServer()
virtual RailResult rail.IRailGameServerImpl.ReportPlayerQuitGameServer (List< GameServerPlayerInfo > player_infos) inline virtual
Implements rail.IRailGameServer.
Definition at line 474 of file IRailGameServerImpl.cs.
        {
            IntPtr intPtr = ((player_infos == null) ? IntPtr.Zero : RAIL_API_PINVOKE.new_RailArrayGameServerPlayerInfo__SWIG_0());
            if (player_infos != null)
            {
                RailConverter.Csharp2Cpp(player_infos, intPtr);
            }
            RailResult railResult;
            try
            {
                railResult = (RailResult)RAIL_API_PINVOKE.IRailGameServer_ReportPlayerQuitGameServer(this.swigCPtr_, intPtr);
            }
            finally
            {
                RAIL_API_PINVOKE.delete_RailArrayGameServerPlayerInfo(intPtr);
            }
            return railResult;
        }
References rail.RailConverter.Csharp2Cpp(), rail.RAIL_API_PINVOKE.delete_RailArrayGameServerPlayerInfo(), rail.RAIL_API_PINVOKE.IRailGameServer_ReportPlayerQuitGameServer(), rail.RAIL_API_PINVOKE.new_RailArrayGameServerPlayerInfo__SWIG_0(), and System.IntPtr.Zero.