Terraria Decompiled: rail.IRailGameServerImpl.SetMods
SetMods()
virtual bool rail.IRailGameServerImpl.SetMods (List< string > server_mods) inline virtual
Implements rail.IRailGameServer.
Definition at line 213 of file IRailGameServerImpl.cs.
        {
            IntPtr intPtr = ((server_mods == null) ? IntPtr.Zero : RAIL_API_PINVOKE.new_RailArrayRailString__SWIG_0());
            if (server_mods != null)
            {
                RailConverter.Csharp2Cpp(server_mods, intPtr);
            }
            bool flag;
            try
            {
                flag = RAIL_API_PINVOKE.IRailGameServer_SetMods(this.swigCPtr_, intPtr);
            }
            finally
            {
                RAIL_API_PINVOKE.delete_RailArrayRailString(intPtr);
            }
            return flag;
        }
References rail.RailConverter.Csharp2Cpp(), rail.RAIL_API_PINVOKE.delete_RailArrayRailString(), rail.RAIL_API_PINVOKE.IRailGameServer_SetMods(), rail.RAIL_API_PINVOKE.new_RailArrayRailString__SWIG_0(), rail.RailObject.swigCPtr_, and System.IntPtr.Zero.