Terraria Decompiled: System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.EventRegistrationTokenList.CopyTo
CopyTo()
void System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.EventRegistrationTokenList.CopyTo (List< EventRegistrationToken > tokens) inline
Definition at line 359 of file WindowsRuntimeMarshal.cs.
            {
                tokens.Add(this.firstToken);
                if (this.restTokens != null)
                {
                    tokens.AddRange(this.restTokens);
                }
            }
References System.Collections.Generic.List< T >.Add(), System.Collections.Generic.List< T >.AddRange(), System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.EventRegistrationTokenList.firstToken, and System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.EventRegistrationTokenList.restTokens.
Referenced by System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.ManagedEventRegistrationImpl.RemoveAllEventHandlers().