Terraria Decompiled: Terraria.UI.CraftingUI.DrawRecipesList
DrawRecipesList()
void Terraria.UI.CraftingUI.DrawRecipesList (SpriteBatch spriteBatch, int adjY, int middleY, Color craftingTipColor) inline
Definition at line 216 of file CraftingUI.cs.
        {
            UILinkPointNavigator.Shortcuts.CRAFT_CurrentRecipeBig = -1;
            UILinkPointNavigator.Shortcuts.CRAFT_CurrentRecipeSmall = -1;
            if (CraftingUI.numAvailableRecipes > 0)
            {
                string text = Lang.inter[25].Value;
                if (CraftingUI.RecipeFilterHack != null)
                {
                    text = CraftingUI.RecipeFilterHack.GetWindowDescription();
                }
                DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.MouseText.Value, text, new Vector2(76f, (float)(414 + adjY)), craftingTipColor, 0f, default(Vector2), 1f, SpriteEffects.None, 0f, null, null);
            }
            this.AdjustRecipeOffsets();
            for (int i = 0; i < Recipe.maxRecipes; i++)
            {
                if (i < CraftingUI.numAvailableRecipes && Math.Abs(CraftingUI.availableRecipeY[i]) <= (float)middleY)
                {
                    CraftingUI.inventoryScale = 100f / (Math.Abs(CraftingUI.availableRecipeY[i]) + 100f);
                    if ((double)CraftingUI.inventoryScale < 0.75)
                    {
                        CraftingUI.inventoryScale = 0.75f;
                    }
                    if (CraftingUI.recFastScroll)
                    {
                        CraftingUI.inventoryScale = 0.75f;
                    }
                    double num;
                    Color color;
                    this.GetItemSlotColors(middleY, 100f, i, out num, out color);
                    int num2 = (int)(46f - 26f * CraftingUI.inventoryScale);
                    int num3 = (int)(410f + CraftingUI.availableRecipeY[i] * CraftingUI.inventoryScale - 30f * CraftingUI.inventoryScale + (float)adjY);
                    if (!Main.LocalPlayer.creativeInterface && CraftingUI.mouseX >= num2 && (float)CraftingUI.mouseX <= (float)num2 + (float)TextureAssets.InventoryBack.Width() * CraftingUI.inventoryScale && CraftingUI.mouseY >= num3 && (float)CraftingUI.mouseY <= (float)num3 + (float)TextureAssets.InventoryBack.Height() * CraftingUI.inventoryScale && !PlayerInput.IgnoreMouseInterface)
                    {
                        Main.HoverOverCraftingItemButton(i);
                    }
                    if (CraftingUI.numAvailableRecipes > 0)
                    {
                        num -= 50.0;
                        if (num < 0.0)
{
                            num = 0.0;
                        }
                        if (i == CraftingUI.focusRecipe)
{
                            UILinkPointNavigator.Shortcuts.CRAFT_CurrentRecipeSmall = 0;
                            if (PlayerInput.SettingsForUI.HighlightThingsForMouse)
{
                                ItemSlot.DrawGoldBGForCraftingMaterial = true;
                            }
                        }
                        else
{
                            UILinkPointNavigator.Shortcuts.CRAFT_CurrentRecipeSmall = -1;
                        }
                        Color inventoryBack = CraftingUI.inventoryBack;
                        CraftingUI.inventoryBack = new Color((int)((byte)num), (int)((byte)num), (int)((byte)num), (int)((byte)num));
                        ItemSlot.Draw(spriteBatch, ref Main.recipe[Main.availableRecipe[i]].createItem, 22, new Vector2((float)num2, (float)num3), color);
                        CraftingUI.inventoryBack = inventoryBack;
                    }
                }
            }
            CraftingUI.inventoryScale = 0.6f;
            if (CraftingUI.numAvailableRecipes > 0)
            {
                UILinkPointNavigator.Shortcuts.CRAFT_CurrentRecipeBig = -1;
                UILinkPointNavigator.Shortcuts.CRAFT_CurrentRecipeSmall = -1;
                for (int j = 0; j < Recipe.maxRequirements; j++)
                {
                    Recipe recipe = Main.recipe[Main.availableRecipe[CraftingUI.focusRecipe]];
                    Item item = recipe.requiredItem[j];
                    if (item.type == 0)
                    {
                        UILinkPointNavigator.Shortcuts.CRAFT_CurrentIngredientsCount = j + 1;
                        return;
                    }
                    int num4 = 80 + j * 40;
                    int num5 = 380 + adjY;
                    double num6 = (double)((float)(CraftingUI.inventoryBack.A + 50) - Math.Abs(CraftingUI.availableRecipeY[CraftingUI.focusRecipe]) * 2f);
                    if (num6 == 0.0)
                    {
                        break;
                    }
                    if (CraftingUI.mouseX >= num4 && (float)CraftingUI.mouseX <= (float)num4 + (float)TextureAssets.InventoryBack.Width() * CraftingUI.inventoryScale && CraftingUI.mouseY >= num5 && (float)CraftingUI.mouseY <= (float)num5 + (float)TextureAssets.InventoryBack.Height() * CraftingUI.inventoryScale && !PlayerInput.IgnoreMouseInterface)
                    {
                        Main.craftingHide = true;
                        Main.LocalPlayer.mouseInterface = true;
                        ItemSlot.HoverOverrideClick(item, 22);
                        CraftingUI.SetRecipeMaterialDisplayName(recipe, item);
                    }
                    num6 -= 50.0;
                    if (num6 < 0.0)
                    {
                        num6 = 0.0;
                    }
                    UILinkPointNavigator.Shortcuts.CRAFT_CurrentRecipeSmall = 1 + j;
                    Color inventoryBack2 = CraftingUI.inventoryBack;
                    CraftingUI.inventoryBack = new Color((int)((byte)num6), (int)((byte)num6), (int)((byte)num6), (int)((byte)num6));
                    ItemSlot.Draw(spriteBatch, ref item, 22, new Vector2((float)num4, (float)num5), default(Color));
                    CraftingUI.inventoryBack = inventoryBack2;
                }
            }
        }
References System.Math.Abs(), Terraria.UI.CraftingUI.AdjustRecipeOffsets(), Terraria.Main.availableRecipe, Terraria.UI.CraftingUI.availableRecipeY, Microsoft.Xna.Framework.Graphics.Color, Terraria.Recipe.createItem, Terraria.Player.creativeInterface, Terraria.UI.ItemSlot.Draw(), ReLogic.Graphics.DynamicSpriteFontExtensionMethods.DrawString(), Terraria.UI.CraftingUI.focusRecipe, Terraria.UI.CraftingUI.GetItemSlotColors(), Terraria.GameInput.PlayerInput.SettingsForUI.HighlightThingsForMouse, Terraria.Main.HoverOverCraftingItemButton(), Terraria.UI.ItemSlot.HoverOverrideClick(), Terraria.GameInput.PlayerInput.IgnoreMouseInterface, int, Terraria.Lang.inter, Terraria.GameContent.TextureAssets.InventoryBack, Terraria.UI.CraftingUI.inventoryBack, Terraria.UI.CraftingUI.inventoryScale, System.item, Terraria.Main.LocalPlayer, Terraria.Recipe.maxRecipes, Terraria.Recipe.maxRequirements, Terraria.GameContent.FontAssets.MouseText, Terraria.UI.CraftingUI.mouseX, Terraria.UI.CraftingUI.mouseY, Terraria.UI.CraftingUI.numAvailableRecipes, Terraria.UI.CraftingUI.recFastScroll, Terraria.Main.recipe, Terraria.UI.CraftingUI.RecipeFilterHack, Terraria.Recipe.requiredItem, Terraria.UI.CraftingUI.SetRecipeMaterialDisplayName(), System.text, ReLogic.Content.Asset< T >.Value, Terraria.Localization.LocalizedText.Value, and Microsoft.Xna.Framework.Graphics.Vector2.
Referenced by Terraria.Main.DrawInventory().