Terraria Decompiled: Terraria.UI.CraftingUI.DrawRecipesGrid
DrawRecipesGrid()
void Terraria.UI.CraftingUI.DrawRecipesGrid (SpriteBatch spriteBatch) inline
Definition at line 526 of file CraftingUI.cs.
        {
            UILinkPointNavigator.Shortcuts.CRAFT_CurrentRecipeBig = -1;
            UILinkPointNavigator.Shortcuts.CRAFT_CurrentRecipeSmall = -1;
            int num = 42;
            CraftingUI.inventoryScale = 0.75f;
            int num2 = 340;
            int num3 = 310;
            int num4 = (Main.screenWidth - num3 - 280) / num;
            int num5 = (Main.screenHeight - num2 - 20) / num;
            UILinkPointNavigator.Shortcuts.CRAFT_IconsPerRow = num4;
            UILinkPointNavigator.Shortcuts.CRAFT_IconsPerColumn = num5;
            int num6 = 0;
            int num7 = 0;
            int num8 = num3;
            int num9 = num2;
            int num10 = num3 - 20;
            int num11 = num2 + 2;
            if (CraftingUI.recStart > CraftingUI.numAvailableRecipes - num4 * num5)
            {
                CraftingUI.recStart = CraftingUI.numAvailableRecipes - num4 * num5;
                if (CraftingUI.recStart < 0)
                {
                    CraftingUI.recStart = 0;
                }
            }
            if (CraftingUI.recStart > 0)
            {
                if (CraftingUI.mouseX >= num10 && CraftingUI.mouseX <= num10 + TextureAssets.CraftUpButton.Width() && CraftingUI.mouseY >= num11 && CraftingUI.mouseY <= num11 + TextureAssets.CraftUpButton.Height() && !PlayerInput.IgnoreMouseInterface)
                {
                    Main.LocalPlayer.mouseInterface = true;
                    if (Main.mouseLeftRelease && Main.mouseLeft)
                    {
                        CraftingUI.recStart -= num4;
                        if (CraftingUI.recStart < 0)
{
                            CraftingUI.recStart = 0;
                        }
                        SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                        Main.mouseLeftRelease = false;
                    }
                }
                spriteBatch.Draw(TextureAssets.CraftUpButton.Value, new Vector2((float)num10, (float)num11), null, new Color(200, 200, 200, 200), 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
            }
            if (CraftingUI.recStart < CraftingUI.numAvailableRecipes - num4 * num5)
            {
                num11 += 20;
                if (CraftingUI.mouseX >= num10 && CraftingUI.mouseX <= num10 + TextureAssets.CraftUpButton.Width() && CraftingUI.mouseY >= num11 && CraftingUI.mouseY <= num11 + TextureAssets.CraftUpButton.Height() && !PlayerInput.IgnoreMouseInterface)
                {
                    Main.LocalPlayer.mouseInterface = true;
                    if (Main.mouseLeftRelease && Main.mouseLeft)
                    {
                        CraftingUI.recStart += num4;
                        SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                        if (CraftingUI.recStart > CraftingUI.numAvailableRecipes - num4)
{
                            CraftingUI.recStart = CraftingUI.numAvailableRecipes - num4;
                        }
                        Main.mouseLeftRelease = false;
                    }
                }
                spriteBatch.Draw(TextureAssets.CraftDownButton.Value, new Vector2((float)num10, (float)num11), null, new Color(200, 200, 200, 200), 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
            }
            int num12 = CraftingUI.recStart;
            while (num12 < Recipe.maxRecipes && num12 < CraftingUI.numAvailableRecipes)
            {
                int num13 = num8;
                int num14 = num9;
                double num15 = (double)(CraftingUI.inventoryBack.A + 50);
                double num16 = 255.0;
                new Color((int)((byte)num15), (int)((byte)num15), (int)((byte)num15), (int)((byte)num15));
                new Color((int)((byte)num16), (int)((byte)num16), (int)((byte)num16), (int)((byte)num16));
                if (CraftingUI.mouseX >= num13 && (float)CraftingUI.mouseX <= (float)num13 + (float)TextureAssets.InventoryBack.Width() * CraftingUI.inventoryScale && CraftingUI.mouseY >= num14 && (float)CraftingUI.mouseY <= (float)num14 + (float)TextureAssets.InventoryBack.Height() * CraftingUI.inventoryScale && !PlayerInput.IgnoreMouseInterface)
                {
                    Main.LocalPlayer.mouseInterface = true;
                    if (Main.mouseLeftRelease && Main.mouseLeft)
                    {
                        CraftingUI.focusRecipe = num12;
                        CraftingUI.recFastScroll = true;
                        Main.PipsUseGrid = false;
                        SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                        Main.mouseLeftRelease = false;
                        if (PlayerInput.UsingGamepadUI)
{
                            UILinkPointNavigator.ChangePage(9);
                            Main.LockCraftingForThisCraftClickDuration();
                        }
                    }
                    Main.craftingHide = true;
                    Item createItem = Main.recipe[Main.availableRecipe[num12]].createItem;
                    Main.HoverItem = createItem.Clone();
                    ItemSlot.MouseHover(22);
                    Main.hoverItemName = createItem.Name;
                    if (createItem.stack > 1)
                    {
                        Main.hoverItemName = string.Concat(new object[]
{
                            Main.hoverItemName,
                            " (",
                            createItem.stack,
                            ")"
                        });
                    }
                }
                if (CraftingUI.numAvailableRecipes > 0)
                {
                    num15 -= 50.0;
                    if (num15 < 0.0)
                    {
                        num15 = 0.0;
                    }
                    UILinkPointNavigator.Shortcuts.CRAFT_CurrentRecipeBig = num12 - CraftingUI.recStart;
                    Color inventoryBack = CraftingUI.inventoryBack;
                    CraftingUI.inventoryBack = new Color((int)((byte)num15), (int)((byte)num15), (int)((byte)num15), (int)((byte)num15));
                    ItemSlot.Draw(spriteBatch, ref Main.recipe[Main.availableRecipe[num12]].createItem, 22, new Vector2((float)num13, (float)num14), default(Color));
                    CraftingUI.inventoryBack = inventoryBack;
                }
                num8 += num;
                num6++;
                if (num6 >= num4)
                {
                    num8 = num3;
                    num9 += num;
                    num6 = 0;
                    num7++;
                    if (num7 >= num5)
                    {
                        break;
                    }
                }
                num12++;
            }
        }
References Microsoft.Xna.Framework.Color.A, Terraria.Main.availableRecipe, Terraria.UI.Gamepad.UILinkPointNavigator.ChangePage(), Terraria.Item.Clone(), Microsoft.Xna.Framework.Graphics.Color, Terraria.GameContent.TextureAssets.CraftDownButton, Terraria.GameContent.TextureAssets.CraftUpButton, Terraria.Recipe.createItem, Terraria.UI.ItemSlot.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Main.hoverItemName, Terraria.GameInput.PlayerInput.IgnoreMouseInterface, Terraria.GameContent.TextureAssets.InventoryBack, Terraria.UI.CraftingUI.inventoryBack, Terraria.UI.CraftingUI.inventoryScale, Terraria.Main.LockCraftingForThisCraftClickDuration(), Terraria.Recipe.maxRecipes, Terraria.UI.ItemSlot.MouseHover(), Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.UI.CraftingUI.mouseX, Terraria.UI.CraftingUI.mouseY, Terraria.Item.Name, Terraria.UI.CraftingUI.numAvailableRecipes, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.recipe, Terraria.UI.CraftingUI.recStart, Terraria.Item.stack, Terraria.GameInput.PlayerInput.UsingGamepadUI, and ReLogic.Content.Asset< T >.Value.
Referenced by Terraria.Main.DrawInventory().