Terraria Decompiled: Terraria.UI.CraftingUI.SetRecipeMaterialDisplayName
SetRecipeMaterialDisplayName()
static void Terraria.UI.CraftingUI.SetRecipeMaterialDisplayName (Recipe recipe, Item material) inline static
Definition at line 502 of file CraftingUI.cs.
        {
            Item item = material.Clone();
            ItemSlot.MouseHover(item, 22);
            item = Main.HoverItem;
            string text;
            if (recipe.ProcessGroupsForText(material.type, out text))
            {
                item.SetNameOverride(text);
            }
            Main.hoverItemName = item.Name;
            if (material.stack > 1)
            {
                Main.hoverItemName = string.Concat(new object[]
                {
                    Main.hoverItemName,
                    " (",
                    material.stack,
                    ")"
                });
            }
        }
References Terraria.Item.Clone(), Terraria.Main.HoverItem, Terraria.Main.hoverItemName, System.item, Terraria.UI.ItemSlot.MouseHover(), Terraria.Recipe.ProcessGroupsForText(), Terraria.Item.SetNameOverride(), Terraria.Item.stack, System.text, and Terraria.Item.type.
Referenced by Terraria.GameContent.UI.NewCraftingUI.DrawChildren(), and Terraria.UI.CraftingUI.DrawRecipesList().