Terraria Decompiled: NVorbis.Ogg.ContainerReader.FindNextStream
FindNextStream()
bool NVorbis.Ogg.ContainerReader.FindNextStream () inline
Definition at line 140 of file ContainerReader.cs.
        {
            this._reader.Lock();
            bool flag;
            try
            {
                this._foundStream = false;
                while (this._reader.ReadNextPage())
                {
                    if (this._foundStream)
                    {
                        return true;
                    }
                }
                flag = false;
            }
            finally
            {
                this._reader.Release();
            }
            return flag;
        }
References NVorbis.Ogg.ContainerReader._foundStream, NVorbis.Ogg.ContainerReader._reader, NVorbis.Contracts.Ogg.IPageReader.Lock(), NVorbis.Contracts.Ogg.IPageReader.ReadNextPage(), and NVorbis.Contracts.Ogg.IPageReader.Release().
Referenced by NVorbis.Ogg.ContainerReader.TryInit().