Terraria Decompiled: NVorbis.Ogg.ContainerReader.ProcessNewStream
ProcessNewStream()
bool NVorbis.Ogg.ContainerReader.ProcessNewStream (IPacketProvider packetProvider) inline private
Definition at line 164 of file ContainerReader.cs.
        {
            bool flag = this._reader.Release();
            bool flag2;
            try
            {
                NewStreamHandler newStreamCallback = this.NewStreamCallback;
                if (newStreamCallback == null || newStreamCallback(packetProvider))
                {
                    this._packetProviders.Add(new WeakReference(packetProvider));
                    this._foundStream = true;
                    flag2 = true;
                }
                else
                {
                    flag2 = false;
                }
            }
            finally
            {
                if (flag)
                {
                    this._reader.Lock();
                }
            }
            return flag2;
        }
References NVorbis.Ogg.ContainerReader._packetProviders, NVorbis.Ogg.ContainerReader._reader, System.Collections.Generic.List< T >.Add(), NVorbis.Contracts.Ogg.IPageReader.Lock(), NVorbis.Ogg.ContainerReader.NewStreamCallback, NVorbis.Contracts.NewStreamHandler(), and NVorbis.Contracts.Ogg.IPageReader.Release().
Referenced by NVorbis.Ogg.ContainerReader.ContainerReader().