Terraria Decompiled: System.Security.Policy.CodeGroup.FromXml
FromXml() [2/2]
void System.Security.Policy.CodeGroup.FromXml (SecurityElement e, PolicyLevel level) inline
Definition at line 238 of file CodeGroup.cs.
        {
            if (e == null)
            {
                throw new ArgumentNullException("e");
            }
            string text = e.Attribute("PermissionSetName");
            PermissionSet permissionSet;
            if (text != null && level != null)
            {
                permissionSet = level.GetNamedPermissionSet(text);
            }
            else
            {
                SecurityElement securityElement = e.SearchForChildByTag("PermissionSet");
                if (securityElement != null)
                {
                    permissionSet = (PermissionSet)Activator.CreateInstance(Type.GetType(securityElement.Attribute("class")), true);
                    permissionSet.FromXml(securityElement);
                }
                else
                {
                    permissionSet = new PermissionSet(new PermissionSet(PermissionState.None));
                }
            }
            this.m_policy = new PolicyStatement(permissionSet);
            this.m_children.Clear();
            if (e.Children != null && e.Children.Count > 0)
            {
                foreach (object obj in e.Children)
                {
                    SecurityElement securityElement2 = (SecurityElement)obj;
                    if (securityElement2.Tag == "CodeGroup")
                    {
                        this.AddChild(CodeGroup.CreateFromXml(securityElement2, level));
                    }
                }
            }
            this.m_membershipCondition = null;
            SecurityElement securityElement3 = e.SearchForChildByTag("IMembershipCondition");
            if (securityElement3 != null)
            {
                string text2 = securityElement3.Attribute("class");
                Type type = Type.GetType(text2);
                if (type == null)
                {
                    type = Type.GetType("System.Security.Policy." + text2);
                }
                this.m_membershipCondition = (IMembershipCondition)Activator.CreateInstance(type, true);
                this.m_membershipCondition.FromXml(securityElement3, level);
            }
            this.m_name = e.Attribute("Name");
            this.m_description = e.Attribute("Description");
            this.ParseXml(e, level);
        }
References System.Security.Policy.CodeGroup.AddChild(), System.Security.SecurityElement.Attribute(), System.Security.SecurityElement.Children, System.Collections.ArrayList.Clear(), System.Collections.ArrayList.Count, System.Security.Policy.CodeGroup.CreateFromXml(), System.Activator.CreateInstance(), System.Security.ISecurityEncodable.FromXml(), System.Security.PermissionSet.FromXml(), System.Security.Policy.PolicyLevel.GetNamedPermissionSet(), System.Type.GetType(), System.Security.Policy.CodeGroup.m_children, System.Security.Policy.CodeGroup.m_membershipCondition, System.obj, System.Security.Policy.CodeGroup.ParseXml(), System.Security.Policy.CodeGroup.PolicyStatement, System.Security.SecurityElement.SearchForChildByTag(), System.Security.SecurityElement.Tag, and System.text.