Terraria Decompiled: System.Security.Policy.CodeGroup.Copy
Copy()
CodeGroup System.Security.Policy.CodeGroup.Copy () abstract
Referenced by System.Security.Policy.CodeGroup.AddChild(), System.Security.Policy.FileCodeGroup.Copy(), System.Security.Policy.FirstMatchCodeGroup.Copy(), System.Security.Policy.NetCodeGroup.Copy(), System.Security.Policy.UnionCodeGroup.Copy(), and System.Security.Policy.FirstMatchCodeGroup.ResolveMatchingCodeGroups().