Terraria Decompiled: System.Security.Policy.CodeGroup.CreateFromXml
CreateFromXml()
static CodeGroup System.Security.Policy.CodeGroup.CreateFromXml (SecurityElement se, PolicyLevel level) inline static package
Definition at line 342 of file CodeGroup.cs.
        {
            string text = se.Attribute("class");
            string text2 = text;
            int num = text2.IndexOf(",");
            if (num > 0)
            {
                text2 = text2.Substring(0, num);
            }
            num = text2.LastIndexOf(".");
            if (num > 0)
            {
                text2 = text2.Substring(num + 1);
            }
            if (text2 == "FileCodeGroup")
            {
                return new FileCodeGroup(se, level);
            }
            if (text2 == "FirstMatchCodeGroup")
            {
                return new FirstMatchCodeGroup(se, level);
            }
            if (text2 == "NetCodeGroup")
            {
                return new NetCodeGroup(se, level);
            }
            if (!(text2 == "UnionCodeGroup"))
            {
                CodeGroup codeGroup = (CodeGroup)Activator.CreateInstance(Type.GetType(text), true);
                codeGroup.FromXml(se, level);
                return codeGroup;
            }
            return new UnionCodeGroup(se, level);
        }
References System.Security.SecurityElement.Attribute(), System.Security.Policy.CodeGroup.CodeGroup(), System.Activator.CreateInstance(), System.Security.Policy.CodeGroup.FromXml(), System.Type.GetType(), and System.text.
Referenced by System.Security.Policy.PolicyLevel.FromXml(), and System.Security.Policy.CodeGroup.FromXml().