Terraria Decompiled: System.Security.Policy.CodeGroup.AddChild
AddChild()
void System.Security.Policy.CodeGroup.AddChild (CodeGroup group) inline
Definition at line 162 of file CodeGroup.cs.
        {
            if (group == null)
            {
                throw new ArgumentNullException("group");
            }
            this.m_children.Add(group.Copy());
        }
References System.Collections.ArrayList.Add(), System.Security.Policy.CodeGroup.Copy(), and System.Security.Policy.CodeGroup.m_children.
Referenced by System.Security.Policy.FileCodeGroup.Copy(), System.Security.Policy.FirstMatchCodeGroup.Copy(), System.Security.Policy.NetCodeGroup.Copy(), System.Security.Policy.UnionCodeGroup.Copy(), System.Security.Policy.PolicyLevel.CreateDefaultLevel(), System.Security.Policy.CodeGroup.FromXml(), System.Security.Policy.FileCodeGroup.ResolveMatchingCodeGroups(), System.Security.Policy.NetCodeGroup.ResolveMatchingCodeGroups(), System.Security.Policy.UnionCodeGroup.ResolveMatchingCodeGroups(), and System.Security.Policy.CodeGroup.ToXml().