Terraria Decompiled: System.Security.Policy.CodeGroup.CodeGroup
CodeGroup() [1/2]
System.Security.Policy.CodeGroup.CodeGroup (IMembershipCondition membershipCondition, PolicyStatement policy) inline protected
Definition at line 14 of file CodeGroup.cs.
        {
            if (membershipCondition == null)
            {
                throw new ArgumentNullException("membershipCondition");
            }
            if (policy != null)
            {
                this.m_policy = policy.Copy();
            }
            this.m_membershipCondition = membershipCondition.Copy();
        }
References System.Security.Policy.IMembershipCondition.Copy(), and System.Security.Policy.PolicyStatement.Copy().
Referenced by System.Security.Policy.FileCodeGroup.Copy(), System.Security.Policy.FirstMatchCodeGroup.Copy(), System.Security.Policy.NetCodeGroup.Copy(), System.Security.Policy.UnionCodeGroup.Copy(), System.Security.Policy.CodeGroup.CreateFromXml(), System.Security.Policy.CodeGroup.Equals(), System.Security.Policy.FileCodeGroup.Resolve(), System.Security.Policy.FirstMatchCodeGroup.Resolve(), System.Security.Policy.NetCodeGroup.Resolve(), System.Security.Policy.UnionCodeGroup.Resolve(), System.Security.Policy.FileCodeGroup.ResolveMatchingCodeGroups(), System.Security.Policy.FirstMatchCodeGroup.ResolveMatchingCodeGroups(), System.Security.Policy.NetCodeGroup.ResolveMatchingCodeGroups(), System.Security.Policy.UnionCodeGroup.ResolveMatchingCodeGroups(), and System.Security.Policy.CodeGroup.ToXml().