Terraria Decompiled: System.Security.Policy.CodeGroup.ToXml
ToXml() [2/2]
SecurityElement System.Security.Policy.CodeGroup.ToXml (PolicyLevel level) inline
Definition at line 306 of file CodeGroup.cs.
        {
            SecurityElement securityElement = new SecurityElement("CodeGroup");
            securityElement.AddAttribute("class", base.GetType().AssemblyQualifiedName);
            securityElement.AddAttribute("version", "1");
            if (this.Name != null)
            {
                securityElement.AddAttribute("Name", this.Name);
            }
            if (this.Description != null)
            {
                securityElement.AddAttribute("Description", this.Description);
            }
            if (this.MembershipCondition != null)
            {
                securityElement.AddChild(this.MembershipCondition.ToXml());
            }
            if (this.PolicyStatement != null && this.PolicyStatement.PermissionSet != null)
            {
                securityElement.AddChild(this.PolicyStatement.PermissionSet.ToXml());
            }
            foreach (object obj in this.Children)
            {
                CodeGroup codeGroup = (CodeGroup)obj;
                securityElement.AddChild(codeGroup.ToXml());
            }
            this.CreateXml(securityElement, level);
            return securityElement;
        }
References System.Security.SecurityElement.AddAttribute(), System.Security.Policy.CodeGroup.AddChild(), System.Security.SecurityElement.AddChild(), System.Security.Policy.CodeGroup.Children, System.Security.Policy.CodeGroup.CodeGroup(), System.Security.Policy.CodeGroup.CreateXml(), System.Security.Policy.CodeGroup.Description, System.Security.Policy.CodeGroup.MembershipCondition, System.Security.Policy.CodeGroup.Name, System.obj, System.Security.Policy.PolicyStatement.PermissionSet, System.Security.ISecurityEncodable.ToXml(), System.Security.PermissionSet.ToXml(), and System.Security.Policy.CodeGroup.ToXml().