Terraria Decompiled: Terraria.Graphics.Renderers.MapHeadRenderer.CreateOutlines
CreateOutlines()
void Terraria.Graphics.Renderers.MapHeadRenderer.CreateOutlines (float alpha, float scale, Color borderColor) inline private
Definition at line 97 of file MapHeadRenderer.cs.
        {
            if (borderColor != Color.Transparent)
            {
                List<DrawData> list = new List<DrawData>(this._drawData);
                List<DrawData> list2 = new List<DrawData>(this._drawData);
                this._drawData.Clear();
                float num = 2f * scale;
                Color color = borderColor * (alpha * alpha);
                Color color2 = Color.Black;
                color2 *= alpha * alpha;
                int colorOnlyShaderIndex = ContentSamples.DyeShaderIDs.ColorOnlyShaderIndex;
                for (int i = 0; i < list2.Count; i++)
                {
                    DrawData drawData = list2[i];
                    drawData.shader = colorOnlyShaderIndex;
                    drawData.color = color2;
                    list2[i] = drawData;
                }
                int num2 = 2;
                Vector2 zero;
                for (int j = -num2; j <= num2; j++)
                {
                    for (int k = -num2; k <= num2; k++)
                    {
                        if (Math.Abs(j) + Math.Abs(k) == num2)
{
                            zero = new Vector2((float)j * num, (float)k * num);
                            for (int l = 0; l < list2.Count; l++)
{
                                DrawData drawData2 = list2[l];
                                drawData2.position += zero;
                                this._drawData.Add(drawData2);
                            }
                        }
                    }
                }
                for (int m = 0; m < list2.Count; m++)
                {
                    DrawData drawData3 = list2[m];
                    drawData3.shader = colorOnlyShaderIndex;
                    drawData3.color = color;
                    list2[m] = drawData3;
                }
                zero = Vector2.Zero;
                num2 = 1;
                for (int n = -num2; n <= num2; n++)
                {
                    for (int num3 = -num2; num3 <= num2; num3++)
                    {
                        if (Math.Abs(n) + Math.Abs(num3) == num2)
{
                            zero = new Vector2((float)n * num, (float)num3 * num);
                            for (int num4 = 0; num4 < list2.Count; num4++)
{
                                DrawData drawData4 = list2[num4];
                                drawData4.position += zero;
                                this._drawData.Add(drawData4);
                            }
                        }
                    }
                }
                this._drawData.AddRange(list);
            }
        }
References Terraria.Graphics.Renderers.MapHeadRenderer._drawData, System.Math.Abs(), System.Collections.Generic.List< T >.Add(), System.Collections.Generic.List< T >.AddRange(), Microsoft.Xna.Framework.Color.Black, System.Collections.Generic.List< T >.Clear(), Terraria.ID.ContentSamples.DyeShaderIDs.ColorOnlyShaderIndex, System.Collections.Generic.List< T >.Count, System.list, Microsoft.Xna.Framework.Color.Transparent, Microsoft.Xna.Framework.Graphics.Vector2, and Microsoft.Xna.Framework.Vector2.Zero.