Terraria Decompiled: Terraria.Graphics.Renderers.MapHeadRenderer.RenderDrawData
RenderDrawData()
void Terraria.Graphics.Renderers.MapHeadRenderer.RenderDrawData (Player drawPlayer) inline private
Definition at line 52 of file MapHeadRenderer.cs.
        {
            Effect pixelShader = Main.pixelShader;
            SpriteBatch spriteBatch = Main.spriteBatch;
            for (int i = 0; i < this._drawData.Count; i++)
            {
                DrawData drawData = this._drawData[i];
                if (drawData.sourceRect == null)
                {
                    drawData.sourceRect = new Rectangle?(drawData.texture.Frame(1, 1, 0, 0, 0, 0));
                }
                PlayerDrawHelper.SetShaderForData(drawPlayer, drawPlayer.cHead, ref drawData);
                if (drawData.texture != null)
                {
                    drawData.Draw(spriteBatch);
                }
            }
            pixelShader.CurrentTechnique.Passes[0].Apply();
        }
References Terraria.Graphics.Renderers.MapHeadRenderer._drawData, Terraria.Player.cHead, System.Collections.Generic.List< T >.Count, Microsoft.Xna.Framework.Graphics.Effect.CurrentTechnique, Terraria.DataStructures.DrawData.Draw(), Microsoft.Xna.Framework.Graphics.EffectTechnique.Passes, Terraria.Main.pixelShader, Terraria.DataStructures.PlayerDrawHelper.SetShaderForData(), Terraria.DataStructures.DrawData.sourceRect, Terraria.Main.spriteBatch, and Terraria.DataStructures.DrawData.texture.
Referenced by Terraria.Graphics.Renderers.MapHeadRenderer.DrawPlayerHead().