Terraria Decompiled: Terraria.Graphics.Renderers.MapHeadRenderer.DrawPlayerHead
DrawPlayerHead()
void Terraria.Graphics.Renderers.MapHeadRenderer.DrawPlayerHead (Camera camera, Player drawPlayer, Vector2 position, float alpha = 1f, float scale = 1f, Color borderColor = default(Color)) inline
Definition at line 35 of file MapHeadRenderer.cs.
        {
            PlayerHeadDrawRenderTargetContent playerHeadDrawRenderTargetContent = this._playerRenders[drawPlayer.whoAmI];
            playerHeadDrawRenderTargetContent.UsePlayer(drawPlayer);
            playerHeadDrawRenderTargetContent.UseColor(borderColor);
            playerHeadDrawRenderTargetContent.Request();
            this._anyDirty = true;
            this._drawData.Clear();
            if (playerHeadDrawRenderTargetContent.IsReady)
            {
                RenderTarget2D target = playerHeadDrawRenderTargetContent.GetTarget();
                this._drawData.Add(new DrawData(target, position, null, Color.White, 0f, target.Size() / 2f, scale, SpriteEffects.None, 0f));
                this.RenderDrawData(drawPlayer);
            }
        }
References Terraria.Graphics.Renderers.MapHeadRenderer._drawData, Terraria.Graphics.Renderers.MapHeadRenderer._playerRenders, System.Collections.Generic.List< T >.Add(), System.Collections.Generic.List< T >.Clear(), Terraria.GameContent.ARenderTargetContentByRequest.GetTarget(), Terraria.GameContent.ARenderTargetContentByRequest.IsReady, Terraria.Graphics.Renderers.MapHeadRenderer.RenderDrawData(), Terraria.GameContent.ARenderTargetContentByRequest.Request(), Terraria.GameContent.AnOutlinedDrawRenderTargetContent.UseColor(), Terraria.GameContent.PlayerHeadDrawRenderTargetContent.UsePlayer(), Microsoft.Xna.Framework.Color.White, and Terraria.Entity.whoAmI.
Referenced by Terraria.Main.DrawMap().