Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.Features.DungeonWindowMosaic.Window
Window()
bool Terraria.GameContent.Generation.Dungeon.Features.DungeonWindowMosaic.Window (DungeonData data, int placeX, int placeY, DungeonGenerationStyleData style, bool generating = false) inline
Definition at line 30 of file DungeonWindowMosaic.cs.
        {
            UnifiedRandom genRand = WorldGen.genRand;
            DungeonWindowMosaicSettings dungeonWindowMosaicSettings = (DungeonWindowMosaicSettings)this.settings;
            int overrideGlassPaint = dungeonWindowMosaicSettings.OverrideGlassPaint;
            ushort num = (dungeonWindowMosaicSettings.Closed ? style.WindowClosedGlassWallType : style.WindowGlassWallType);
            ushort windowEdgeWallType = style.WindowEdgeWallType;
            if (dungeonWindowMosaicSettings.OverrideGlassType > 0)
            {
                num = (ushort)dungeonWindowMosaicSettings.OverrideGlassType;
            }
            this.Bounds.SetBounds(placeX, placeY, placeX + 1, placeY + 1);
            switch (dungeonWindowMosaicSettings.MosaicType)
            {
            case WindowType.SkeletronMosaic:
                this.Window_Skeletron(placeX, placeY, num, windowEdgeWallType, (overrideGlassPaint > 0) ? ((byte)overrideGlassPaint) : 0);
                break;
            case WindowType.MoonLordMosaic:
                this.Window_MoonLord(placeX, placeY, num, windowEdgeWallType, (overrideGlassPaint > 0) ? ((byte)overrideGlassPaint) : 0);
                break;
            }
            this.Bounds.CalculateHitbox();
            return true;
        }
References Terraria.GameContent.Generation.Dungeon.Features.DungeonFeature.Bounds, Terraria.GameContent.Generation.Dungeon.DungeonBounds.CalculateHitbox(), Terraria.WorldGen.genRand, Terraria.GameContent.Generation.Dungeon.Features.DungeonWindowMosaicSettings.MosaicType, Terraria.GameContent.Generation.Dungeon.Features.DungeonWindowSettings.OverrideGlassPaint, Terraria.GameContent.Generation.Dungeon.Features.DungeonWindowSettings.OverrideGlassType, Terraria.GameContent.Generation.Dungeon.DungeonBounds.SetBounds(), Terraria.GameContent.Generation.Dungeon.Features.DungeonFeature.settings, Terraria.GameContent.Generation.Dungeon.Features.DungeonWindowMosaic.Window_MoonLord(), Terraria.GameContent.Generation.Dungeon.Features.DungeonWindowMosaic.Window_Skeletron(), Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.WindowEdgeWallType, and Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.WindowGlassWallType.
Referenced by Terraria.GameContent.Generation.Dungeon.Features.DungeonWindowMosaic.GenerateFeature().