Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.Features.DungeonWindowMosaic.Window_MoonLord
Window_MoonLord()
void Terraria.GameContent.Generation.Dungeon.Features.DungeonWindowMosaic.Window_MoonLord (int placeX, int placeY, ushort glassWallType, ushort edgeWallType, byte paint = 0) inline
Definition at line 251 of file DungeonWindowMosaic.cs.
        {
            int num = 8;
            int num2 = num - 1;
            int num3 = 7;
            int num4 = num3 - 1;
            int num5 = 7;
            int num6 = num5 + 1;
            int num7 = 9;
            Point point = new Point(placeX, placeY);
            for (int i = 0; i < 2; i++)
            {
                bool flag = i == 0;
                for (int j = 0; j < num; j++)
                {
                    for (int k = 0; k < num2; k++)
                    {
                        if (this.MoonLord_ValidSideEyeSpot(j, k, flag, num, num2))
{
                            int num8 = point.X + j + (flag ? (-num7 - 1) : (num7 - num + 2));
                            int num9 = point.Y + k + num2 - 2;
                            this.Bounds.UpdateBounds(num8, num9);
                            Main.tile[num8, num9].wall = glassWallType;
                            if (paint != 0)
{
                                Main.tile[num8, num9].wallColor(paint);
                            }
                            if (!this.MoonLord_ValidSideEyeSpot(j - 1, k, flag, num, num2))
{
                                this.Bounds.UpdateBounds(num8 - 1, num9);
                                Main.tile[num8 - 1, num9].wall = edgeWallType;
                            }
                            if (!this.MoonLord_ValidSideEyeSpot(j + 1, k, flag, num, num2))
{
                                this.Bounds.UpdateBounds(num8 + 1, num9);
                                Main.tile[num8 + 1, num9].wall = edgeWallType;
                            }
                            if (!this.MoonLord_ValidSideEyeSpot(j, k - 1, flag, num, num2))
{
                                this.Bounds.UpdateBounds(num8, num9 - 1);
                                Main.tile[num8, num9 - 1].wall = edgeWallType;
                            }
                            if (!this.MoonLord_ValidSideEyeSpot(j, k + 1, flag, num, num2))
{
                                this.Bounds.UpdateBounds(num8, num9 + 1);
                                Main.tile[num8, num9 + 1].wall = edgeWallType;
                            }
                        }
                    }
                }
                for (int l = 0; l < num3; l++)
                {
                    for (int m = 0; m < num4; m++)
                    {
                        if (this.MoonLord_ValidSideEyeSpot(l, m, flag, num3, num4))
{
                            int num10 = point.X + l + (flag ? (-num7 + 1) : (num7 - num3));
                            int num11 = point.Y + m - num4 + 2;
                            this.Bounds.UpdateBounds(num10 - 1, num11);
                            Main.tile[num10, num11].wall = glassWallType;
                            if (paint != 0)
{
                                Main.tile[num10, num11].wallColor(paint);
                            }
                            if (!this.MoonLord_ValidSideEyeSpot(l - 1, m, flag, num3, num4))
{
                                this.Bounds.UpdateBounds(num10 - 1, num11);
                                Main.tile[num10 - 1, num11].wall = edgeWallType;
                            }
                            if (!this.MoonLord_ValidSideEyeSpot(l + 1, m, flag, num3, num4))
{
                                this.Bounds.UpdateBounds(num10 + 1, num11);
                                Main.tile[num10 + 1, num11].wall = edgeWallType;
                            }
                            if (!this.MoonLord_ValidSideEyeSpot(l, m - 1, flag, num3, num4))
{
                                this.Bounds.UpdateBounds(num10, num11 - 1);
                                Main.tile[num10, num11 - 1].wall = edgeWallType;
                            }
                            if (!this.MoonLord_ValidSideEyeSpot(l, m + 1, flag, num3, num4))
{
                                this.Bounds.UpdateBounds(num10, num11 + 1);
                                Main.tile[num10, num11 + 1].wall = edgeWallType;
                            }
                        }
                    }
                }
            }
            for (int n = 0; n < num5; n++)
            {
                for (int num12 = 0; num12 < num6; num12++)
                {
                    if (this.MoonLord_ValidMidEyeSpot(n, num12, num5, num6))
                    {
                        int num13 = point.X + n - num5 / 2;
                        int num14 = point.Y + num12 - num4 - num6;
                        this.Bounds.UpdateBounds(num13, num14);
                        Main.tile[num13, num14].wall = glassWallType;
                        if (paint != 0)
{
                            Main.tile[num13, num14].wallColor(paint);
                        }
                        if (!this.MoonLord_ValidMidEyeSpot(n - 1, num12, num5, num6))
{
                            this.Bounds.UpdateBounds(num13 - 1, num14);
                            Main.tile[num13 - 1, num14].wall = edgeWallType;
                        }
                        if (!this.MoonLord_ValidMidEyeSpot(n + 1, num12, num5, num6))
{
                            this.Bounds.UpdateBounds(num13 + 1, num14);
                            Main.tile[num13 + 1, num14].wall = edgeWallType;
                        }
                        if (!this.MoonLord_ValidMidEyeSpot(n, num12 - 1, num5, num6))
{
                            this.Bounds.UpdateBounds(num13, num14 - 1);
                            Main.tile[num13, num14 - 1].wall = edgeWallType;
                        }
                        if (!this.MoonLord_ValidMidEyeSpot(n, num12 + 1, num5, num6))
{
                            this.Bounds.UpdateBounds(num13, num14 + 1);
                            Main.tile[num13, num14 + 1].wall = edgeWallType;
                        }
                    }
                }
            }
        }
References Terraria.GameContent.Generation.Dungeon.Features.DungeonFeature.Bounds, Terraria.GameContent.Generation.Dungeon.Features.DungeonWindowMosaic.MoonLord_ValidMidEyeSpot(), Terraria.GameContent.Generation.Dungeon.Features.DungeonWindowMosaic.MoonLord_ValidSideEyeSpot(), Terraria.Main.tile, Terraria.GameContent.Generation.Dungeon.DungeonBounds.UpdateBounds(), Terraria.Tile.wall, and Terraria.Tile.wallColor().
Referenced by Terraria.GameContent.Generation.Dungeon.Features.DungeonWindowMosaic.Window().