Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.Features.DungeonWindowMosaic.Window_Skeletron
Window_Skeletron()
void Terraria.GameContent.Generation.Dungeon.Features.DungeonWindowMosaic.Window_Skeletron (int placeX, int placeY, ushort glassWallType, ushort edgeWallType, byte paint = 0) inline
Definition at line 56 of file DungeonWindowMosaic.cs.
        {
            Point point = new Point(placeX, placeY);
            int num = 17;
            int num2 = num / 2;
            int num3 = 15;
            int num4 = num3 / 2;
            int num5 = 11;
            int num6 = num5 / 2;
            int num7 = 7;
            int num8 = num7 / 2;
            for (int i = 0; i < num; i++)
            {
                int num9 = point.X + i - num2;
                for (int j = 0; j < num3; j++)
                {
                    if (this.Skeletron_ValidSkullSpot(i, j, num, num3))
                    {
                        int num10 = point.Y + j - num4;
                        Tile tile = Main.tile[num9, num10];
                        tile.wall = glassWallType;
                        if (paint != 0)
{
                            tile.wallColor(paint);
                        }
                        if (!this.Skeletron_ValidSkullSpot(i - 1, j, num, num3))
{
                            Main.tile[num9 - 1, num10].wall = edgeWallType;
                        }
                        if (!this.Skeletron_ValidSkullSpot(i + 1, j, num, num3))
{
                            Main.tile[num9 + 1, num10].wall = edgeWallType;
                        }
                        if (!this.Skeletron_ValidSkullSpot(i, j - 1, num, num3))
{
                            Main.tile[num9, num10 - 1].wall = edgeWallType;
                        }
                        if (j < num3 - 1 && !this.Skeletron_ValidSkullSpot(i, j + 1, num, num3))
{
                            Main.tile[num9, num10 + 1].wall = edgeWallType;
                        }
                    }
                }
            }
            for (int k = 0; k < num5; k++)
            {
                int num11 = point.X + k - num6;
                for (int l = 0; l < num7; l++)
                {
                    int num12 = point.Y + l + num4 + num8 - 2;
                    Tile tile2 = Main.tile[num11, num12];
                    if (this.Skeletron_ValidJawSpot(tile2, (int)glassWallType, k, l, num5, num7))
                    {
                        tile2.wall = glassWallType;
                        if (paint != 0)
{
                            tile2.wallColor(paint);
                        }
                        if (!this.Skeletron_ValidJawSpot(Main.tile[num11 - 1, num12], (int)glassWallType, k - 1, l, num5, num7))
{
                            Main.tile[num11 - 1, num12].wall = edgeWallType;
                        }
                        if (!this.Skeletron_ValidJawSpot(Main.tile[num11 + 1, num12], (int)glassWallType, k + 1, l, num5, num7))
{
                            Main.tile[num11 + 1, num12].wall = edgeWallType;
                        }
                        if (!this.Skeletron_ValidJawSpot(Main.tile[num11, num12 - 1], (int)glassWallType, k, l - 1, num5, num7))
{
                            Main.tile[num11, num12 - 1].wall = edgeWallType;
                        }
                        if (!this.Skeletron_ValidJawSpot(Main.tile[num11, num12 + 1], (int)glassWallType, k, l + 1, num5, num7))
{
                            Main.tile[num11, num12 + 1].wall = edgeWallType;
                        }
                    }
                }
            }
            Point point2 = new Point(point.X - num2, point.Y + num4 - 2);
            for (int m = 0; m < num; m++)
            {
                int num13 = point2.X + m;
                if (m >= 2 && m <= 5)
                {
                    int num14 = m - 2;
                    for (int n = 0; n < 6; n++)
                    {
                        if ((num14 != 3 || n > 1) && (num14 != 2 || n != 0) && (num14 != 1 || n != 5) && (num14 != 0 || n < 4))
{
                            Tile tile3 = Main.tile[num13, point.Y + n - 1];
                            tile3.wall = edgeWallType;
                            tile3.wallColor(0);
                        }
                    }
                }
                if (m >= 11 && m <= 14)
                {
                    int num15 = m - 11;
                    for (int num16 = 0; num16 < 6; num16++)
                    {
                        if ((num15 != 0 || num16 > 1) && (num15 != 1 || num16 != 0) && (num15 != 2 || num16 != 5) && (num15 != 3 || num16 < 4))
{
                            Tile tile4 = Main.tile[num13, point.Y + num16 - 1];
                            tile4.wall = edgeWallType;
                            tile4.wallColor(0);
                        }
                    }
                }
                if (m >= 7 && m <= 9)
                {
                    int num17 = m - 7;
                    for (int num18 = 0; num18 < 4; num18++)
                    {
                        if (((num17 != 0 && num17 != 2) || num18 != 0) && (num17 != 1 || num18 != 3))
{
                            Tile tile5 = Main.tile[num13, point.Y + num18 + 3];
                            tile5.wall = edgeWallType;
                            tile5.wallColor(0);
                        }
                    }
                }
                int num19 = point2.Y + 1;
                switch (m)
                {
                case 2:
                case 3:
                    num19++;
                    break;
                case 4:
                case 5:
                case 6:
                    num19 += 2;
                    break;
                case 7:
                case 8:
                case 9:
                    num19 += 3;
                    break;
                case 10:
                case 11:
                case 12:
                    num19 += 2;
                    break;
                case 13:
                case 14:
                    num19++;
                    break;
                }
                Tile tile6 = Main.tile[num13, num19];
                tile6.wall = edgeWallType;
                tile6.wallColor(0);
                if (m == 0 || m == num - 1)
                {
                    Tile tile7 = Main.tile[num13, num19 - 1];
                    Tile tile8 = Main.tile[num13, num19 + 1];
                    tile8.wall = edgeWallType;
                    tile7.wall = edgeWallType;
                    tile7.wallColor(0);
                    tile8.wallColor(0);
                }
                if (m == 4 || m == 6 || m == 8 || m == 10 || m == 12)
                {
                    for (int num20 = 0; num20 < 4; num20++)
                    {
                        Tile tile9 = Main.tile[num13, num19 + num20];
                        tile9.wall = edgeWallType;
                        tile9.wallColor(0);
                    }
                }
                if (m >= 5 && m <= 11)
                {
                    int num21 = point2.Y + 7;
                    if (m >= 7 && m <= 9)
                    {
                        num21++;
                    }
                    Tile tile10 = Main.tile[num13, num21];
                    tile10.wall = edgeWallType;
                    tile10.wallColor(0);
                }
            }
        }
References Terraria.GameContent.Generation.Dungeon.Features.DungeonWindowMosaic.Skeletron_ValidJawSpot(), Terraria.GameContent.Generation.Dungeon.Features.DungeonWindowMosaic.Skeletron_ValidSkullSpot(), Terraria.Main.tile, Terraria.Tile.wall, Terraria.Tile.wallColor(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.Generation.Dungeon.Features.DungeonWindowMosaic.Window().