Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalBase.IsErrorHandled
IsErrorHandled()
bool Newtonsoft.Json.Serialization.JsonSerializerInternalBase.IsErrorHandled (object currentObject, JsonContract contract, object keyValue, IJsonLineInfo lineInfo, string path, Exception ex) inline protected
Definition at line 58 of file JsonSerializerInternalBase.cs.
        {
            ErrorContext errorContext = this.GetErrorContext(currentObject, keyValue, path, ex);
            if (this.TraceWriter != null && this.TraceWriter.LevelFilter >= 1 && !errorContext.Traced)
            {
                errorContext.Traced = true;
                string text = ((base.GetType() == typeof(JsonSerializerInternalWriter)) ? "Error serializing" : "Error deserializing");
                if (contract != null)
                {
                    text = text + " " + contract.UnderlyingType;
                }
                text = text + ". " + ex.Message;
                if (!(ex is JsonException))
                {
                    text = JsonPosition.FormatMessage(lineInfo, path, text);
                }
                this.TraceWriter.Trace(1, text, ex);
            }
            if (contract != null && currentObject != null)
            {
                contract.InvokeOnError(currentObject, this.Serializer.Context, errorContext);
            }
            if (!errorContext.Handled)
            {
                this.Serializer.OnError(new ErrorEventArgs(currentObject, errorContext));
            }
            return errorContext.Handled;
        }
References Newtonsoft.Json.JsonSerializer.Context, Newtonsoft.Json.JsonPosition.FormatMessage(), Newtonsoft.Json.Serialization.JsonSerializerInternalBase.GetErrorContext(), Newtonsoft.Json.Serialization.ErrorContext.Handled, Newtonsoft.Json.Serialization.JsonContract.InvokeOnError(), Newtonsoft.Json.Serialization.ITraceWriter.LevelFilter, System.Exception.Message, Newtonsoft.Json.JsonSerializer.OnError(), Newtonsoft.Json.Serialization.JsonSerializerInternalBase.Serializer, System.text, Newtonsoft.Json.Serialization.ITraceWriter.Trace(), Newtonsoft.Json.Serialization.ErrorContext.Traced, Newtonsoft.Json.Serialization.JsonSerializerInternalBase.TraceWriter, and Newtonsoft.Json.Serialization.JsonContract.UnderlyingType.