Terraria Decompiled: System.TimeZoneInfo.TransitionTime.CreateFixedDateRule
CreateFixedDateRule()
static TimeZoneInfo.TransitionTime System.TimeZoneInfo.TransitionTime.CreateFixedDateRule (DateTime timeOfDay, int month, int day) inline static
Definition at line 3415 of file TimeZoneInfo.cs.
            {
                return new TimeZoneInfo.TransitionTime(timeOfDay, month, 1, day, DayOfWeek.Sunday, true);
            }
Referenced by System.TimeZoneInfo.GetAdjustmentRules(), System.TimeZoneInfo.StringSerializer.GetNextTransitionTimeValue(), System.TimeZoneInfo.TZif_CreateTransitionTimeFromPosixRule(), and System.TimeZoneInfo.TZif_GenerateAdjustmentRule().