Terraria Decompiled: System.__ComObject.__ComObject
__ComObject() [3/3]
System.__ComObject.__ComObject (IntPtr pItf, ComInteropProxy p) inline package
Definition at line 54 of file __ComObject.cs.
        {
            this.proxy = p;
            this.InitializeApartmentDetails();
            Guid iid_IUnknown = __ComObject.IID_IUnknown;
            Marshal.ThrowExceptionForHR(Marshal.QueryInterface(pItf, ref iid_IUnknown, out this.iunknown));
        }
References System.__ComObject.IID_IUnknown, System.__ComObject.InitializeApartmentDetails(), System.Runtime.InteropServices.Marshal.QueryInterface(), and System.Runtime.InteropServices.Marshal.ThrowExceptionForHR().