Terraria Decompiled: System.__ComObject.CreateIUnknown
CreateIUnknown()
static IntPtr System.__ComObject.CreateIUnknown (Type t) inline static package
Definition at line 82 of file __ComObject.cs.
        {
            RuntimeHelpers.RunClassConstructor(t.TypeHandle);
            ObjectCreationDelegate objectCreationCallback = ExtensibleClassFactory.GetObjectCreationCallback(t);
            IntPtr intPtr;
            if (objectCreationCallback != null)
            {
                intPtr = objectCreationCallback(IntPtr.Zero);
                if (intPtr == IntPtr.Zero)
                {
                    throw new COMException(string.Format("ObjectCreationDelegate for type {0} failed to return a valid COM object", t));
                }
            }
            else
            {
                Marshal.ThrowExceptionForHR(__ComObject.CoCreateInstance(__ComObject.GetCLSID(t), IntPtr.Zero, 21U, __ComObject.IID_IUnknown, out intPtr));
            }
            return intPtr;
        }
References System.__ComObject.CoCreateInstance(), System.Format, System.__ComObject.GetCLSID(), System.Runtime.InteropServices.ExtensibleClassFactory.GetObjectCreationCallback(), System.__ComObject.IID_IUnknown, System.Runtime.InteropServices.ObjectCreationDelegate(), System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor(), System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(), System.Type.TypeHandle, System.U, and System.IntPtr.Zero.
Referenced by Mono.Interop.ComInteropProxy.CreateProxy(), and System.__ComObject.Initialize().