Terraria Decompiled: System.Security.Cryptography.CryptoStream.d__42.MoveNext
MoveNext()
void IAsyncStateMachine. System.Security.Cryptography.CryptoStream.d__42.MoveNext () inline
Implements System.Runtime.CompilerServices.IAsyncStateMachine.
Definition at line 830 of file CryptoStream.cs.
            {
                int num2;
                int num = num2;
                CryptoStream cryptoStream = this;
                int num4;
                try
                {
                    ValueTaskAwaiter<int> valueTaskAwaiter2;
                    ValueTaskAwaiter<int> valueTaskAwaiter;
                    if (num != 0)
                    {
                        if (num == 1)
{
                            valueTaskAwaiter = valueTaskAwaiter2;
                            valueTaskAwaiter2 = default(ValueTaskAwaiter<int>);
                            num = (num2 = -1);
                            goto IL_04E4;
                        }
                        bytesToDeliver = count;
                        currentOutputIndex = offset;
                        if (cryptoStream._outputBufferIndex != 0)
{
                            if (cryptoStream._outputBufferIndex > count)
{
                                Buffer.BlockCopy(cryptoStream._outputBuffer, 0, buffer, offset, count);
                                Buffer.BlockCopy(cryptoStream._outputBuffer, count, cryptoStream._outputBuffer, 0, cryptoStream._outputBufferIndex - count);
                                cryptoStream._outputBufferIndex -= count;
                                int num3 = cryptoStream._outputBuffer.Length - cryptoStream._outputBufferIndex;
                                CryptographicOperations.ZeroMemory(new Span<byte>(cryptoStream._outputBuffer, cryptoStream._outputBufferIndex, num3));
                                num4 = count;
                                goto IL_078D;
                            }
                            Buffer.BlockCopy(cryptoStream._outputBuffer, 0, buffer, offset, cryptoStream._outputBufferIndex);
                            bytesToDeliver -= cryptoStream._outputBufferIndex;
                            currentOutputIndex += cryptoStream._outputBufferIndex;
                            int num5 = cryptoStream._outputBuffer.Length - cryptoStream._outputBufferIndex;
                            CryptographicOperations.ZeroMemory(new Span<byte>(cryptoStream._outputBuffer, cryptoStream._outputBufferIndex, num5));
                            cryptoStream._outputBufferIndex = 0;
                        }
                        if (cryptoStream._finalBlockTransformed)
{
                            num4 = count - bytesToDeliver;
                            goto IL_078D;
                        }
                        int num6 = bytesToDeliver / cryptoStream._outputBlockSize;
                        if (num6 <= 1 || !cryptoStream._transform.CanTransformMultipleBlocks)
{
                            goto IL_063F;
                        }
                        numWholeBlocksInBytes = num6 * cryptoStream._inputBlockSize;
                        tempInputBuffer = ArrayPool<byte>.Shared.Rent(numWholeBlocksInBytes);
                        tempOutputBuffer = null;
                    }
                    int num7;
                    int num8;
                    try
                    {
                        if (num != 0)
{
                            if (!useAsync)
{
                                num7 = cryptoStream._stream.Read(tempInputBuffer, cryptoStream._inputBufferIndex, numWholeBlocksInBytes - cryptoStream._inputBufferIndex);
                                goto IL_0284;
                            }
                            valueTaskAwaiter = cryptoStream._stream.ReadAsync(new Memory<byte>(tempInputBuffer, cryptoStream._inputBufferIndex, numWholeBlocksInBytes - cryptoStream._inputBufferIndex), cancellationToken).GetAwaiter();
                            if (!valueTaskAwaiter.IsCompleted)
{
                                num = (num2 = 0);
                                valueTaskAwaiter2 = valueTaskAwaiter;
                                this.<>t__builder.AwaitUnsafeOnCompleted<ValueTaskAwaiter<int>, CryptoStream.<ReadAsyncCore>d__42>(ref valueTaskAwaiter, ref this);
                                return;
                            }
                        }
                        else
{
                            valueTaskAwaiter = valueTaskAwaiter2;
                            valueTaskAwaiter2 = default(ValueTaskAwaiter<int>);
                            num = (num2 = -1);
                        }
                        num7 = valueTaskAwaiter.GetResult();
                        IL_0284:
                        num8 = num7;
                        int num9 = cryptoStream._inputBufferIndex + num8;
                        if (num9 < cryptoStream._inputBlockSize)
{
                            Buffer.BlockCopy(tempInputBuffer, cryptoStream._inputBufferIndex, cryptoStream._inputBuffer, cryptoStream._inputBufferIndex, num8);
                            cryptoStream._inputBufferIndex = num9;
                        }
                        else
{
                            Buffer.BlockCopy(cryptoStream._inputBuffer, 0, tempInputBuffer, 0, cryptoStream._inputBufferIndex);
                            CryptographicOperations.ZeroMemory(new Span<byte>(cryptoStream._inputBuffer, 0, cryptoStream._inputBufferIndex));
                            num8 += cryptoStream._inputBufferIndex;
                            cryptoStream._inputBufferIndex = 0;
                            int num10 = num8 / cryptoStream._inputBlockSize;
                            int num11 = num10 * cryptoStream._inputBlockSize;
                            int num12 = num8 - num11;
                            if (num12 != 0)
{
                                cryptoStream._inputBufferIndex = num12;
                                Buffer.BlockCopy(tempInputBuffer, num11, cryptoStream._inputBuffer, 0, num12);
                            }
                            tempOutputBuffer = ArrayPool<byte>.Shared.Rent(num10 * cryptoStream._outputBlockSize);
                            int num13 = cryptoStream._transform.TransformBlock(tempInputBuffer, 0, num11, tempOutputBuffer, 0);
                            Buffer.BlockCopy(tempOutputBuffer, 0, buffer, currentOutputIndex, num13);
                            CryptographicOperations.ZeroMemory(new Span<byte>(tempOutputBuffer, 0, num13));
                            ArrayPool<byte>.Shared.Return(tempOutputBuffer, false);
                            tempOutputBuffer = null;
                            bytesToDeliver -= num13;
                            currentOutputIndex += num13;
                        }
                    }
                    finally
                    {
                        if (num < 0)
{
                            if (tempOutputBuffer != null)
{
                                CryptographicOperations.ZeroMemory(tempOutputBuffer);
                                ArrayPool<byte>.Shared.Return(tempOutputBuffer, false);
                                tempOutputBuffer = null;
                            }
                            CryptographicOperations.ZeroMemory(new Span<byte>(tempInputBuffer, 0, numWholeBlocksInBytes));
                            ArrayPool<byte>.Shared.Return(tempInputBuffer, false);
                            tempInputBuffer = null;
                        }
                    }
                    tempInputBuffer = null;
                    tempOutputBuffer = null;
                    goto IL_063F;
                    IL_04E4:
                    num7 = valueTaskAwaiter.GetResult();
                    IL_0515:
                    num8 = num7;
                    if (num8 != 0)
                    {
                        cryptoStream._inputBufferIndex += num8;
                    }
                    else
                    {
                        byte[] array = cryptoStream._transform.TransformFinalBlock(cryptoStream._inputBuffer, 0, cryptoStream._inputBufferIndex);
                        cryptoStream._outputBuffer = array;
                        cryptoStream._outputBufferIndex = array.Length;
                        cryptoStream._finalBlockTransformed = true;
                        if (bytesToDeliver < cryptoStream._outputBufferIndex)
{
                            Buffer.BlockCopy(cryptoStream._outputBuffer, 0, buffer, currentOutputIndex, bytesToDeliver);
                            cryptoStream._outputBufferIndex -= bytesToDeliver;
                            Buffer.BlockCopy(cryptoStream._outputBuffer, bytesToDeliver, cryptoStream._outputBuffer, 0, cryptoStream._outputBufferIndex);
                            int num14 = cryptoStream._outputBuffer.Length - cryptoStream._outputBufferIndex;
                            CryptographicOperations.ZeroMemory(new Span<byte>(cryptoStream._outputBuffer, cryptoStream._outputBufferIndex, num14));
                            num4 = count;
                            goto IL_078D;
                        }
                        Buffer.BlockCopy(cryptoStream._outputBuffer, 0, buffer, currentOutputIndex, cryptoStream._outputBufferIndex);
                        bytesToDeliver -= cryptoStream._outputBufferIndex;
                        cryptoStream._outputBufferIndex = 0;
                        CryptographicOperations.ZeroMemory(cryptoStream._outputBuffer);
                        num4 = count - bytesToDeliver;
                        goto IL_078D;
                    }
                    IL_052C:
                    if (cryptoStream._inputBufferIndex >= cryptoStream._inputBlockSize)
                    {
                        int num13 = cryptoStream._transform.TransformBlock(cryptoStream._inputBuffer, 0, cryptoStream._inputBlockSize, cryptoStream._outputBuffer, 0);
                        cryptoStream._inputBufferIndex = 0;
                        if (bytesToDeliver < num13)
{
                            Buffer.BlockCopy(cryptoStream._outputBuffer, 0, buffer, currentOutputIndex, bytesToDeliver);
                            cryptoStream._outputBufferIndex = num13 - bytesToDeliver;
                            Buffer.BlockCopy(cryptoStream._outputBuffer, bytesToDeliver, cryptoStream._outputBuffer, 0, cryptoStream._outputBufferIndex);
                            int num15 = cryptoStream._outputBuffer.Length - cryptoStream._outputBufferIndex;
                            CryptographicOperations.ZeroMemory(new Span<byte>(cryptoStream._outputBuffer, cryptoStream._outputBufferIndex, num15));
                            num4 = count;
                            goto IL_078D;
                        }
                        Buffer.BlockCopy(cryptoStream._outputBuffer, 0, buffer, currentOutputIndex, num13);
                        CryptographicOperations.ZeroMemory(new Span<byte>(cryptoStream._outputBuffer, 0, num13));
                        currentOutputIndex += num13;
                        bytesToDeliver -= num13;
                    }
                    else
                    {
                        if (!useAsync)
{
                            num7 = cryptoStream._stream.Read(cryptoStream._inputBuffer, cryptoStream._inputBufferIndex, cryptoStream._inputBlockSize - cryptoStream._inputBufferIndex);
                            goto IL_0515;
                        }
                        valueTaskAwaiter = cryptoStream._stream.ReadAsync(new Memory<byte>(cryptoStream._inputBuffer, cryptoStream._inputBufferIndex, cryptoStream._inputBlockSize - cryptoStream._inputBufferIndex), cancellationToken).GetAwaiter();
                        if (!valueTaskAwaiter.IsCompleted)
{
                            num = (num2 = 1);
                            valueTaskAwaiter2 = valueTaskAwaiter;
                            this.<>t__builder.AwaitUnsafeOnCompleted<ValueTaskAwaiter<int>, CryptoStream.<ReadAsyncCore>d__42>(ref valueTaskAwaiter, ref this);
                            return;
                        }
                        goto IL_04E4;
                    }
                    IL_063F:
                    if (bytesToDeliver > 0)
                    {
                        goto IL_052C;
                    }
                    num4 = count;
                }
                catch (Exception ex)
                {
                    num2 = -2;
                    this.<>t__builder.SetException(ex);
                    return;
                }
                IL_078D:
                num2 = -2;
                this.<>t__builder.SetResult(num4);
            }
References System.Security.Cryptography.CryptoStream._finalBlockTransformed, System.Security.Cryptography.CryptoStream._inputBlockSize, System.Security.Cryptography.CryptoStream._inputBuffer, System.Security.Cryptography.CryptoStream._inputBufferIndex, System.Security.Cryptography.CryptoStream._outputBlockSize, System.Security.Cryptography.CryptoStream._outputBuffer, System.Security.Cryptography.CryptoStream._outputBufferIndex, System.Security.Cryptography.CryptoStream._stream, System.Security.Cryptography.CryptoStream._transform, System.array, System.Buffer.BlockCopy(), System.Security.Cryptography.ICryptoTransform.CanTransformMultipleBlocks, System.count, System.Runtime.CompilerServices.ValueTaskAwaiter< TResult >.GetResult(), System.Runtime.CompilerServices.ValueTaskAwaiter< TResult >.IsCompleted, System.offset, System.IO.Stream.Read(), System.IO.Stream.ReadAsync(), System.Security.Cryptography.CryptoStream.ReadAsyncCore(), System.Buffers.ArrayPool< T >.Shared, System.Security.Cryptography.ICryptoTransform.TransformBlock(), System.Security.Cryptography.ICryptoTransform.TransformFinalBlock(), and System.Security.Cryptography.CryptographicOperations.ZeroMemory().