Terraria Decompiled: Terraria.GameContent.Bestiary.NPCKillCounterInfoElement.ProvideUIElement
ProvideUIElement()
UIElement Terraria.GameContent.Bestiary.NPCKillCounterInfoElement.ProvideUIElement (BestiaryUICollectionInfo info) inline
Implements Terraria.GameContent.Bestiary.IBestiaryInfoElement.
Definition at line 25 of file NPCKillCounterInfoElement.cs.
        {
            int? killCount = this.GetKillCount();
            if (killCount == null || killCount.Value < 1)
            {
                return null;
            }
            UIElement uielement = new UIElement();
            uielement.Width = new StyleDimension(0f, 1f);
            uielement.Height = new StyleDimension(109f, 0f);
            if (killCount != null)
            {
                bool flag = killCount.Value > 0;
            }
            int num = 0;
            int num2 = 30;
            int num3 = num2;
            string text = killCount.Value.ToString();
            int length = text.Length;
            int num4 = Math.Max(0, -48 + 8 * text.Length);
            num4 = -3;
            float num5 = 1f;
            int num6 = 8;
            UIElement uielement2 = new UIPanel(Main.Assets.Request<Texture2D>("Images/UI/Bestiary/Stat_Panel", 1), null, 12, 7)
            {
                Width = new StyleDimension((float)(-8 + num4), num5),
                Height = new StyleDimension((float)num2, 0f),
                BackgroundColor = new Color(43, 56, 101),
                BorderColor = Color.Transparent,
                Top = new StyleDimension((float)num, 0f),
                Left = new StyleDimension((float)(-(float)num6), 0f),
                HAlign = 1f
            };
            uielement2.SetPadding(0f);
            uielement2.PaddingRight = 5f;
            uielement.Append(uielement2);
            uielement2.OnUpdate += this.ShowDescription;
            float num7 = 0.85f;
            UIText uitext = new UIText(text, num7, false)
            {
                HAlign = 1f,
                VAlign = 0.5f,
                Left = new StyleDimension(-3f, 0f),
                Top = new StyleDimension(0f, 0f)
            };
            Item item = new Item();
            item.SetDefaults(321, null);
            item.scale = 0.8f;
            UIItemIcon uiitemIcon = new UIItemIcon(item, false)
            {
                IgnoresMouseInteraction = true,
                HAlign = 0f,
                Left = new StyleDimension(-1f, 0f)
            };
            uielement.Height.Pixels = (float)num3;
            uielement2.Append(uiitemIcon);
            uielement2.Append(uitext);
            return uielement;
        }
References Terraria.UI.UIElement.Append(), Terraria.Main.Assets, Microsoft.Xna.Framework.Graphics.Color, Terraria.GameContent.Bestiary.NPCKillCounterInfoElement.GetKillCount(), System.item, System.length, System.Math.Max(), Terraria.UI.UIElement.SetPadding(), Terraria.GameContent.Bestiary.NPCKillCounterInfoElement.ShowDescription(), System.text, and Microsoft.Xna.Framework.Color.Transparent.