Terraria Decompiled: Microsoft.Xna.Framework.GraphicsDeviceManager.GraphicsDeviceManager
GraphicsDeviceManager() [1/2]
Microsoft.Xna.Framework.GraphicsDeviceManager.GraphicsDeviceManager (Game game) inline
Definition at line 366 of file GraphicsDeviceManager.cs.
        {
            if (game == null)
            {
                throw new ArgumentNullException("The game cannot be null!");
            }
            this.game = game;
            this.INTERNAL_supportedOrientations = DisplayOrientation.Default;
            this.INTERNAL_preferredBackBufferHeight = GraphicsDeviceManager.DefaultBackBufferHeight;
            this.INTERNAL_preferredBackBufferWidth = GraphicsDeviceManager.DefaultBackBufferWidth;
            this.INTERNAL_preferredBackBufferFormat = SurfaceFormat.Color;
            this.INTERNAL_preferredDepthStencilFormat = DepthFormat.Depth24;
            this.INTERNAL_synchronizeWithVerticalRetrace = true;
            this.INTERNAL_preferMultiSampling = false;
            if (game.Services.GetService(typeof(IGraphicsDeviceManager)) != null)
            {
                throw new ArgumentException("Graphics Device Manager Already Present");
            }
            game.Services.AddService(typeof(IGraphicsDeviceManager), this);
            game.Services.AddService(typeof(IGraphicsDeviceService), this);
            this.prefsChanged = true;
            this.useResizedBackBuffer = false;
            this.supportsOrientations = FNAPlatform.SupportsOrientationChanges();
            game.Window.ClientSizeChanged += this.INTERNAL_OnClientSizeChanged;
        }
References Microsoft.Xna.Framework.GameServiceContainer.AddService(), Microsoft.Xna.Framework.GraphicsDeviceManager.DefaultBackBufferHeight, Microsoft.Xna.Framework.GraphicsDeviceManager.DefaultBackBufferWidth, Microsoft.Xna.Framework.GraphicsDeviceManager.game, Microsoft.Xna.Framework.GameServiceContainer.GetService(), Microsoft.Xna.Framework.GraphicsDeviceManager.INTERNAL_OnClientSizeChanged(), Microsoft.Xna.Framework.Game.Services, and Microsoft.Xna.Framework.FNAPlatform.SupportsOrientationChanges.