Terraria Decompiled: Microsoft.Xna.Framework.GraphicsDeviceManager.Dispose
Dispose() [1/2]
void IDisposable. Microsoft.Xna.Framework.GraphicsDeviceManager.Dispose () inline private
Implements System.IDisposable.
Definition at line 419 of file GraphicsDeviceManager.cs.
        {
            this.Dispose(true);
            GC.SuppressFinalize(this);
        }
References Microsoft.Xna.Framework.GraphicsDeviceManager.Dispose(), and System.GC.SuppressFinalize().
Referenced by Microsoft.Xna.Framework.GraphicsDeviceManager.Dispose(), and Microsoft.Xna.Framework.GraphicsDeviceManager.~GraphicsDeviceManager().