Terraria Decompiled: Microsoft.Xna.Framework.GraphicsDeviceManager.ApplyChanges
ApplyChanges()
void Microsoft.Xna.Framework.GraphicsDeviceManager.ApplyChanges () inline
Definition at line 426 of file GraphicsDeviceManager.cs.
        {
            if (this.graphicsDevice == null)
            {
                ((IGraphicsDeviceManager)this).CreateDevice();
                return;
            }
            if (!this.prefsChanged && !this.useResizedBackBuffer)
            {
                return;
            }
            GraphicsDeviceInformation graphicsDeviceInformation = new GraphicsDeviceInformation();
            graphicsDeviceInformation.Adapter = this.graphicsDevice.Adapter;
            graphicsDeviceInformation.PresentationParameters = this.graphicsDevice.PresentationParameters.Clone();
            this.INTERNAL_CreateGraphicsDeviceInformation(graphicsDeviceInformation);
            if (this.supportsOrientations)
            {
                this.game.Window.SetSupportedOrientations(this.INTERNAL_supportedOrientations);
            }
            this.game.Window.BeginScreenDeviceChange(graphicsDeviceInformation.PresentationParameters.IsFullScreen);
            this.game.Window.EndScreenDeviceChange(graphicsDeviceInformation.Adapter.DeviceName, graphicsDeviceInformation.PresentationParameters.BackBufferWidth, graphicsDeviceInformation.PresentationParameters.BackBufferHeight);
            this.graphicsDevice.Reset(graphicsDeviceInformation.PresentationParameters, graphicsDeviceInformation.Adapter);
            this.prefsChanged = false;
        }
References Microsoft.Xna.Framework.Graphics.GraphicsDevice.Adapter, Microsoft.Xna.Framework.GraphicsDeviceInformation.Adapter, Microsoft.Xna.Framework.Graphics.PresentationParameters.BackBufferHeight, Microsoft.Xna.Framework.Graphics.PresentationParameters.BackBufferWidth, Microsoft.Xna.Framework.GameWindow.BeginScreenDeviceChange(), Microsoft.Xna.Framework.Graphics.PresentationParameters.Clone(), Microsoft.Xna.Framework.Graphics.GraphicsAdapter.DeviceName, Microsoft.Xna.Framework.GameWindow.EndScreenDeviceChange(), Microsoft.Xna.Framework.GraphicsDeviceManager.game, Microsoft.Xna.Framework.GraphicsDeviceManager.graphicsDevice, Microsoft.Xna.Framework.GraphicsDeviceManager.INTERNAL_CreateGraphicsDeviceInformation(), Microsoft.Xna.Framework.GraphicsDeviceManager.INTERNAL_supportedOrientations, Microsoft.Xna.Framework.Graphics.PresentationParameters.IsFullScreen, Microsoft.Xna.Framework.GraphicsDeviceManager.prefsChanged, Microsoft.Xna.Framework.Graphics.GraphicsDevice.PresentationParameters, Microsoft.Xna.Framework.GraphicsDeviceInformation.PresentationParameters, Microsoft.Xna.Framework.Graphics.GraphicsDevice.Reset(), Microsoft.Xna.Framework.GameWindow.SetSupportedOrientations(), Microsoft.Xna.Framework.GraphicsDeviceManager.supportsOrientations, Microsoft.Xna.Framework.GraphicsDeviceManager.useResizedBackBuffer, and Microsoft.Xna.Framework.Game.Window.
Referenced by Terraria.Main.ClientInitialize(), Microsoft.Xna.Framework.GraphicsDeviceManager.INTERNAL_OnClientSizeChanged(), Terraria.Main.SetDisplayMode(), Terraria.Main.SetGraphicsProfileInternal(), and Microsoft.Xna.Framework.GraphicsDeviceManager.ToggleFullScreen().