Terraria Decompiled: Microsoft.Xna.Framework.GraphicsDeviceManager.INTERNAL_CreateGraphicsDeviceInformation
INTERNAL_CreateGraphicsDeviceInformation()
void Microsoft.Xna.Framework.GraphicsDeviceManager.INTERNAL_CreateGraphicsDeviceInformation (GraphicsDeviceInformation gdi) inline private
Definition at line 534 of file GraphicsDeviceManager.cs.
        {
            if (this.useResizedBackBuffer)
            {
                gdi.PresentationParameters.BackBufferWidth = this.resizedBackBufferWidth;
                gdi.PresentationParameters.BackBufferHeight = this.resizedBackBufferHeight;
                this.useResizedBackBuffer = false;
            }
            else if (!this.supportsOrientations)
            {
                gdi.PresentationParameters.BackBufferWidth = this.PreferredBackBufferWidth;
                gdi.PresentationParameters.BackBufferHeight = this.PreferredBackBufferHeight;
            }
            else
            {
                int num = Math.Min(this.PreferredBackBufferWidth, this.PreferredBackBufferHeight);
                int num2 = Math.Max(this.PreferredBackBufferWidth, this.PreferredBackBufferHeight);
                if (gdi.PresentationParameters.DisplayOrientation == DisplayOrientation.Portrait)
                {
                    gdi.PresentationParameters.BackBufferWidth = num;
                    gdi.PresentationParameters.BackBufferHeight = num2;
                }
                else
                {
                    gdi.PresentationParameters.BackBufferWidth = num2;
                    gdi.PresentationParameters.BackBufferHeight = num;
                }
            }
            gdi.PresentationParameters.BackBufferFormat = this.PreferredBackBufferFormat;
            gdi.PresentationParameters.DepthStencilFormat = this.PreferredDepthStencilFormat;
            gdi.PresentationParameters.IsFullScreen = this.IsFullScreen;
            gdi.PresentationParameters.PresentationInterval = (this.SynchronizeWithVerticalRetrace ? PresentInterval.One : PresentInterval.Immediate);
            if (!this.PreferMultiSampling)
            {
                gdi.PresentationParameters.MultiSampleCount = 0;
            }
            else if (gdi.PresentationParameters.MultiSampleCount == 0)
            {
                int num3 = 0;
                if (this.graphicsDevice != null)
                {
                    num3 = FNA3D.FNA3D_GetMaxMultiSampleCount(this.graphicsDevice.GLDevice, gdi.PresentationParameters.BackBufferFormat, 8);
                }
                gdi.PresentationParameters.MultiSampleCount = Math.Min(num3, 8);
            }
            gdi.GraphicsProfile = this.GraphicsProfile;
            this.OnPreparingDeviceSettings(this, new PreparingDeviceSettingsEventArgs(gdi));
        }
References Microsoft.Xna.Framework.Graphics.PresentationParameters.BackBufferFormat, Microsoft.Xna.Framework.Graphics.PresentationParameters.DisplayOrientation, Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_GetMaxMultiSampleCount(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.GLDevice, Microsoft.Xna.Framework.GraphicsDeviceManager.graphicsDevice, Microsoft.Xna.Framework.GraphicsDeviceManager.GraphicsProfile, Microsoft.Xna.Framework.GraphicsDeviceManager.IsFullScreen, System.Math.Max(), System.Math.Min(), Microsoft.Xna.Framework.Graphics.PresentationParameters.MultiSampleCount, Microsoft.Xna.Framework.GraphicsDeviceManager.OnPreparingDeviceSettings(), Microsoft.Xna.Framework.GraphicsDeviceManager.PreferMultiSampling, Microsoft.Xna.Framework.GraphicsDeviceManager.PreferredBackBufferFormat, Microsoft.Xna.Framework.GraphicsDeviceManager.PreferredBackBufferHeight, Microsoft.Xna.Framework.GraphicsDeviceManager.PreferredBackBufferWidth, Microsoft.Xna.Framework.GraphicsDeviceManager.PreferredDepthStencilFormat, Microsoft.Xna.Framework.GraphicsDeviceInformation.PresentationParameters, Microsoft.Xna.Framework.GraphicsDeviceManager.resizedBackBufferHeight, Microsoft.Xna.Framework.GraphicsDeviceManager.resizedBackBufferWidth, Microsoft.Xna.Framework.GraphicsDeviceManager.supportsOrientations, and Microsoft.Xna.Framework.GraphicsDeviceManager.useResizedBackBuffer.
Referenced by Microsoft.Xna.Framework.GraphicsDeviceManager.ApplyChanges(), and Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice().