Terraria Decompiled: Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice
CreateDevice()
void IGraphicsDeviceManager. Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice () inline private
Implements Microsoft.Xna.Framework.IGraphicsDeviceManager.
Definition at line 584 of file GraphicsDeviceManager.cs.
        {
            if (this.graphicsDevice != null)
            {
                this.graphicsDevice.Dispose();
                this.graphicsDevice = null;
            }
            GraphicsDeviceInformation graphicsDeviceInformation = new GraphicsDeviceInformation();
            graphicsDeviceInformation.Adapter = GraphicsAdapter.DefaultAdapter;
            graphicsDeviceInformation.PresentationParameters = new PresentationParameters();
            graphicsDeviceInformation.PresentationParameters.DeviceWindowHandle = this.game.Window.Handle;
            this.INTERNAL_CreateGraphicsDeviceInformation(graphicsDeviceInformation);
            if (this.supportsOrientations)
            {
                this.game.Window.SetSupportedOrientations(this.INTERNAL_supportedOrientations);
            }
            this.game.Window.BeginScreenDeviceChange(graphicsDeviceInformation.PresentationParameters.IsFullScreen);
            this.game.Window.EndScreenDeviceChange(graphicsDeviceInformation.Adapter.DeviceName, graphicsDeviceInformation.PresentationParameters.BackBufferWidth, graphicsDeviceInformation.PresentationParameters.BackBufferHeight);
            this.graphicsDevice = new GraphicsDevice(graphicsDeviceInformation.Adapter, graphicsDeviceInformation.GraphicsProfile, graphicsDeviceInformation.PresentationParameters);
            this.graphicsDevice.Disposing += this.OnDeviceDisposing;
            this.graphicsDevice.DeviceResetting += this.OnDeviceResetting;
            this.graphicsDevice.DeviceReset += this.OnDeviceReset;
            this.OnDeviceCreated(this, EventArgs.Empty);
        }
References Microsoft.Xna.Framework.GraphicsDeviceInformation.Adapter, Microsoft.Xna.Framework.Graphics.PresentationParameters.BackBufferHeight, Microsoft.Xna.Framework.Graphics.PresentationParameters.BackBufferWidth, Microsoft.Xna.Framework.GameWindow.BeginScreenDeviceChange(), Microsoft.Xna.Framework.Graphics.GraphicsAdapter.DefaultAdapter, Microsoft.Xna.Framework.Graphics.GraphicsAdapter.DeviceName, Microsoft.Xna.Framework.Graphics.GraphicsDevice.Dispose(), System.EventArgs.Empty, Microsoft.Xna.Framework.GameWindow.EndScreenDeviceChange(), Microsoft.Xna.Framework.GraphicsDeviceManager.game, Microsoft.Xna.Framework.GraphicsDeviceManager.GraphicsDevice, Microsoft.Xna.Framework.GraphicsDeviceManager.graphicsDevice, Microsoft.Xna.Framework.GraphicsDeviceInformation.GraphicsProfile, Microsoft.Xna.Framework.GameWindow.Handle, Microsoft.Xna.Framework.GraphicsDeviceManager.INTERNAL_CreateGraphicsDeviceInformation(), Microsoft.Xna.Framework.GraphicsDeviceManager.INTERNAL_supportedOrientations, Microsoft.Xna.Framework.Graphics.PresentationParameters.IsFullScreen, Microsoft.Xna.Framework.GraphicsDeviceManager.OnDeviceCreated(), Microsoft.Xna.Framework.GraphicsDeviceManager.OnDeviceDisposing(), Microsoft.Xna.Framework.GraphicsDeviceManager.OnDeviceReset(), Microsoft.Xna.Framework.GraphicsDeviceManager.OnDeviceResetting(), Microsoft.Xna.Framework.GraphicsDeviceInformation.PresentationParameters, Microsoft.Xna.Framework.GameWindow.SetSupportedOrientations(), Microsoft.Xna.Framework.GraphicsDeviceManager.supportsOrientations, and Microsoft.Xna.Framework.Game.Window.