Terraria Decompiled: Terraria.GameContent.RGB.PlanteraShader.ProcessHighDetail
ProcessHighDetail()
void Terraria.GameContent.RGB.PlanteraShader.ProcessHighDetail (RgbDevice device, Fragment fragment, EffectDetailLevel quality, float time) inline private
Definition at line 32 of file PlanteraShader.cs.
        {
            for (int i = 0; i < fragment.Count; i++)
            {
                Point gridPositionOfIndex = fragment.GetGridPositionOfIndex(i);
                Vector2 canvasPositionOfIndex = fragment.GetCanvasPositionOfIndex(i);
                canvasPositionOfIndex.X -= 1.8f;
                if (canvasPositionOfIndex.X < 0f)
                {
                    canvasPositionOfIndex.X *= -1f;
                    gridPositionOfIndex.Y += 101;
                }
                float num = NoiseHelper.GetStaticNoise(gridPositionOfIndex.Y);
                num = (num * 5f + time * 0.4f) % 5f;
                float num2 = 1f;
                if (num > 1f)
                {
                    num2 = 1f - MathHelper.Clamp((num - 0.4f - 1f) / 0.4f, 0f, 1f);
                    num = 1f;
                }
                float num3 = num - canvasPositionOfIndex.X / 5f;
                Vector4 vector = this._backgroundColor;
                if (num3 > 0f)
                {
                    float num4 = 1f;
                    if (num3 < 0.2f)
                    {
                        num4 = num3 / 0.2f;
                    }
                    if ((gridPositionOfIndex.X + 7 * gridPositionOfIndex.Y) % 5 == 0)
                    {
                        vector = Vector4.Lerp(this._backgroundColor, this._bulbColor, num4 * num2);
                    }
                    else
                    {
                        vector = Vector4.Lerp(this._backgroundColor, this._vineColor, num4 * num2);
                    }
                }
                fragment.SetColor(i, vector);
            }
        }
References Terraria.GameContent.RGB.PlanteraShader._backgroundColor, Terraria.GameContent.RGB.PlanteraShader._bulbColor, Terraria.GameContent.RGB.PlanteraShader._vineColor, Microsoft.Xna.Framework.MathHelper.Clamp(), ReLogic.Peripherals.RGB.Fragment.Count, ReLogic.Peripherals.RGB.Fragment.GetCanvasPositionOfIndex(), ReLogic.Peripherals.RGB.Fragment.GetGridPositionOfIndex(), Terraria.GameContent.RGB.NoiseHelper.GetStaticNoise(), Microsoft.Xna.Framework.Vector4.Lerp(), ReLogic.Peripherals.RGB.Fragment.SetColor(), Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Point.Y.