Terraria Decompiled: Terraria.IngameOptions.DrawLeftSide
DrawLeftSide()
static bool Terraria.IngameOptions.DrawLeftSide (SpriteBatch sb, string txt, int i, Vector2 anchor, Vector2 offset, float[] scales, float minscale = 0::7f, float maxscale = 0::8f, float scalespeed = 0::01f) inline static
Definition at line 1497 of file IngameOptions.cs.
        {
            bool flag = false;
            int num;
            if (IngameOptions._leftSideCategoryMapping.TryGetValue(i, out num))
            {
                flag = IngameOptions.category == num;
            }
            Color color = Color.Lerp(Color.Gray, Color.White, (scales[i] - minscale) / (maxscale - minscale));
            if (flag)
            {
                color = Color.Gold;
            }
            Vector2 vector = Utils.DrawBorderStringBig(sb, txt, anchor + offset * (float)(1 + i), color, scales[i], 0.5f, 0.5f, -1);
            bool flag2 = new Rectangle((int)anchor.X - (int)vector.X / 2, (int)anchor.Y + (int)(offset.Y * (float)(1 + i)) - (int)vector.Y / 2, (int)vector.X, (int)vector.Y).Contains(new Point(Main.mouseX, Main.mouseY));
            if (!IngameOptions._canConsumeHover)
            {
                return false;
            }
            if (flag2)
            {
                IngameOptions._canConsumeHover = false;
                return true;
            }
            return false;
        }
References Terraria.IngameOptions._canConsumeHover, Terraria.IngameOptions._leftSideCategoryMapping, Microsoft.Xna.Framework.Rectangle.Contains(), Terraria.Utils.DrawBorderStringBig(), Microsoft.Xna.Framework.Color.Gold, Microsoft.Xna.Framework.Color.Gray, Microsoft.Xna.Framework.Color.Lerp(), Terraria.Main.mouseX, Terraria.Main.mouseY, System.offset, Microsoft.Xna.Framework.Graphics.Point, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.IngameOptions.Draw().