Terraria Decompiled: Terraria.IngameOptions.DrawRightSide
DrawRightSide()
static bool Terraria.IngameOptions.DrawRightSide (SpriteBatch sb, string txt, int i, Vector2 anchor, Vector2 offset, float scale, float colorScale, Color over = default(Color)) inline static
Definition at line 1525 of file IngameOptions.cs.
        {
            Color color = Color.Lerp(Color.Gray, Color.White, colorScale);
            if (over != default(Color))
            {
                color = over;
            }
            Vector2 vector = Utils.DrawBorderString(sb, txt, anchor + offset * (float)(1 + i), color, scale, 0.5f, 0.5f, -1);
            IngameOptions.valuePosition = anchor + offset * (float)(1 + i) + vector * new Vector2(0.5f, 0f);
            bool flag = new Rectangle((int)anchor.X - (int)vector.X / 2, (int)anchor.Y + (int)(offset.Y * (float)(1 + i)) - (int)vector.Y / 2, (int)vector.X, (int)vector.Y).Contains(new Point(Main.mouseX, Main.mouseY));
            if (!IngameOptions._canConsumeHover)
            {
                return false;
            }
            if (flag)
            {
                IngameOptions._canConsumeHover = false;
                return true;
            }
            return false;
        }
References Terraria.IngameOptions._canConsumeHover, Microsoft.Xna.Framework.Rectangle.Contains(), Terraria.Utils.DrawBorderString(), Microsoft.Xna.Framework.Color.Gray, Microsoft.Xna.Framework.Color.Lerp(), Terraria.Main.mouseX, Terraria.Main.mouseY, System.offset, Microsoft.Xna.Framework.Graphics.Point, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.IngameOptions.Draw().