Terraria Decompiled: Terraria.IngameOptions.Open
Open()
static void Terraria.IngameOptions.Open () inline static
Definition at line 20 of file IngameOptions.cs.
        {
            Main.ClosePlayerChat();
            Main.chatText = "";
            Main.playerInventory = false;
            Main.editChest = false;
            Main.npcChatText = "";
            SoundEngine.PlaySound(10, -1, -1, 1, 1f, 0f);
            Main.ingameOptionsWindow = true;
            IngameOptions.category = 0;
            for (int i = 0; i < IngameOptions.leftScale.Length; i++)
            {
                IngameOptions.leftScale[i] = 0f;
            }
            for (int j = 0; j < IngameOptions.rightScale.Length; j++)
            {
                IngameOptions.rightScale[j] = 0f;
            }
            IngameOptions.leftHover = -1;
            IngameOptions.rightHover = -1;
            IngameOptions.oldLeftHover = -1;
            IngameOptions.oldRightHover = -1;
            IngameOptions.rightLock = -1;
            IngameOptions.inBar = false;
            IngameOptions.notBar = false;
            IngameOptions.noSound = false;
        }
References Terraria.Main.ClosePlayerChat(), Terraria.IngameOptions.leftScale, Terraria.Audio.SoundEngine.PlaySound(), and Terraria.IngameOptions.rightScale.
Referenced by Terraria.Main.DrawInterface_29_SettingsButton(), and Terraria.Player.TryOpeningInGameOptionsBasedOnInput().