Terraria Decompiled: Terraria.GameContent.FishDropRules.GameContentFishDropPopulator.Populate
Populate()
void Terraria.GameContent.FishDropRules.GameContentFishDropPopulator.Populate () inline
Definition at line 15 of file GameContentFishDropPopulator.cs.
        {
            base.AddStopper(this.AnyEnemies);
            this.LavaDrops();
            this.HoneyDrops();
            this.JunkDrops();
            this.CrateDrops();
            this.RareDrops();
            this.RemixDrops();
            this.DungeonDrops();
            this.CorruptionDrops();
            this.CrimsonDrops();
            this.HallowedDrops();
            this.GlowingMushroomsDrops();
            this.SnowDrops();
            this.JungleDrops();
            this.OceanDrops();
            this.DesertDrops();
            this.FloatingIslandDrops();
            this.SurfaceDrops();
        }
References Terraria.GameContent.FishDropRules.AFishDropRulePopulator.AnyEnemies, Terraria.GameContent.FishDropRules.GameContentFishDropPopulator.CorruptionDrops(), Terraria.GameContent.FishDropRules.GameContentFishDropPopulator.CrateDrops(), Terraria.GameContent.FishDropRules.GameContentFishDropPopulator.CrimsonDrops(), Terraria.GameContent.FishDropRules.GameContentFishDropPopulator.DesertDrops(), Terraria.GameContent.FishDropRules.GameContentFishDropPopulator.DungeonDrops(), Terraria.GameContent.FishDropRules.GameContentFishDropPopulator.FloatingIslandDrops(), Terraria.GameContent.FishDropRules.GameContentFishDropPopulator.GlowingMushroomsDrops(), Terraria.GameContent.FishDropRules.GameContentFishDropPopulator.HallowedDrops(), Terraria.GameContent.FishDropRules.GameContentFishDropPopulator.HoneyDrops(), Terraria.GameContent.FishDropRules.GameContentFishDropPopulator.JungleDrops(), Terraria.GameContent.FishDropRules.GameContentFishDropPopulator.JunkDrops(), Terraria.GameContent.FishDropRules.GameContentFishDropPopulator.LavaDrops(), Terraria.GameContent.FishDropRules.GameContentFishDropPopulator.OceanDrops(), Terraria.GameContent.FishDropRules.GameContentFishDropPopulator.RareDrops(), Terraria.GameContent.FishDropRules.GameContentFishDropPopulator.RemixDrops(), Terraria.GameContent.FishDropRules.GameContentFishDropPopulator.SnowDrops(), and Terraria.GameContent.FishDropRules.GameContentFishDropPopulator.SurfaceDrops().
Referenced by Terraria.Main.Initialize_AlmostEverything().