Terraria Decompiled: Terraria.GameContent.Events.MoonlordDeathDrama.Update
Update()
static void Terraria.GameContent.Events.MoonlordDeathDrama.Update (SceneState sceneState, SceneMetrics metrics) inline static
Definition at line 13 of file MoonlordDeathDrama.cs.
        {
            for (int i = 0; i < MoonlordDeathDrama._pieces.Count; i++)
            {
                MoonlordDeathDrama.MoonlordPiece moonlordPiece = MoonlordDeathDrama._pieces[i];
                moonlordPiece.Update();
                if (moonlordPiece.Dead)
                {
                    MoonlordDeathDrama._pieces.Remove(moonlordPiece);
                    i--;
                }
            }
            for (int j = 0; j < MoonlordDeathDrama._explosions.Count; j++)
            {
                MoonlordDeathDrama.MoonlordExplosion moonlordExplosion = MoonlordDeathDrama._explosions[j];
                moonlordExplosion.Update();
                if (moonlordExplosion.Dead)
                {
                    MoonlordDeathDrama._explosions.Remove(moonlordExplosion);
                    j--;
                }
            }
            bool flag = false;
            for (int k = 0; k < MoonlordDeathDrama._lightSources.Count; k++)
            {
                if (metrics.Center.Distance(MoonlordDeathDrama._lightSources[k]) < 2000f)
                {
                    flag = true;
                    break;
                }
            }
            MoonlordDeathDrama._lightSources.Clear();
            if (!flag)
            {
                MoonlordDeathDrama.requestedLight = 0f;
            }
            sceneState.MoveTowards(ref MoonlordDeathDrama.whitening, MoonlordDeathDrama.requestedLight, 0.02f);
            MoonlordDeathDrama.requestedLight = 0f;
        }
References Terraria.GameContent.Events.MoonlordDeathDrama._explosions, Terraria.GameContent.Events.MoonlordDeathDrama._lightSources, Terraria.GameContent.Events.MoonlordDeathDrama._pieces, Terraria.SceneMetrics.Center, System.Collections.Generic.List< T >.Clear(), System.Collections.Generic.List< T >.Count, Terraria.GameContent.Events.MoonlordDeathDrama.MoonlordPiece.Dead, Terraria.GameContent.Events.MoonlordDeathDrama.MoonlordExplosion.Dead, Microsoft.Xna.Framework.Vector2.Distance(), Terraria.SceneState.MoveTowards(), Terraria.GameContent.Events.MoonlordDeathDrama.requestedLight, Terraria.GameContent.Events.MoonlordDeathDrama.MoonlordPiece.Update(), Terraria.GameContent.Events.MoonlordDeathDrama.MoonlordExplosion.Update(), and Terraria.GameContent.Events.MoonlordDeathDrama.whitening.
Referenced by Terraria.SceneState.ApplyVisuals().