Terraria Decompiled: Steamworks.SteamNetworkingUtils.CheckPingDataUpToDate
CheckPingDataUpToDate()
static bool Steamworks.SteamNetworkingUtils.CheckPingDataUpToDate (float flMaxAgeSeconds) inline static
Definition at line 74 of file SteamNetworkingUtils.cs.
        {
            InteropHelp.TestIfAvailableClient();
            return NativeMethods.ISteamNetworkingUtils_CheckPingDataUpToDate(CSteamAPIContext.GetSteamNetworkingUtils(), flMaxAgeSeconds);
        }
References Steamworks.CSteamAPIContext.GetSteamNetworkingUtils(), Steamworks.NativeMethods.ISteamNetworkingUtils_CheckPingDataUpToDate(), and Steamworks.InteropHelp.TestIfAvailableClient().