Terraria Decompiled: System.Security.Permissions.ZoneIdentityPermission.Union
Union()
override IPermission System.Security.Permissions.ZoneIdentityPermission.Union (IPermission target) inline virtual
Reimplemented from System.Security.CodeAccessPermission.
Definition at line 42 of file ZoneIdentityPermission.cs.
        {
            ZoneIdentityPermission zoneIdentityPermission = this.Cast(target);
            if (zoneIdentityPermission == null)
            {
                if (this.zone != SecurityZone.NoZone)
                {
                    return this.Copy();
                }
                return null;
            }
            else
            {
                if (this.zone == zoneIdentityPermission.zone || zoneIdentityPermission.zone == SecurityZone.NoZone)
                {
                    return this.Copy();
                }
                if (this.zone == SecurityZone.NoZone)
                {
                    return zoneIdentityPermission.Copy();
                }
                throw new ArgumentException(Locale.GetText("Union impossible"));
            }
        }
References System.Security.Permissions.ZoneIdentityPermission.Cast(), System.Security.Permissions.ZoneIdentityPermission.Copy(), Locale.GetText(), and System.Security.Permissions.ZoneIdentityPermission.zone.