Terraria Decompiled: System.Runtime.Remoting.ProviderData.CopyFrom
CopyFrom()
void System.Runtime.Remoting.ProviderData.CopyFrom (ProviderData other) inline
Definition at line 11 of file ProviderData.cs.
        {
            if (this.Ref == null)
            {
                this.Ref = other.Ref;
            }
            if (this.Id == null)
            {
                this.Id = other.Id;
            }
            if (this.Type == null)
            {
                this.Type = other.Type;
            }
            foreach (object obj in other.CustomProperties)
            {
                DictionaryEntry dictionaryEntry = (DictionaryEntry)obj;
                if (!this.CustomProperties.ContainsKey(dictionaryEntry.Key))
                {
                    this.CustomProperties[dictionaryEntry.Key] = dictionaryEntry.Value;
                }
            }
            if (other.CustomData != null)
            {
                if (this.CustomData == null)
                {
                    this.CustomData = new ArrayList();
                }
                foreach (object obj2 in other.CustomData)
                {
                    SinkProviderData sinkProviderData = (SinkProviderData)obj2;
                    this.CustomData.Add(sinkProviderData);
                }
            }
        }
References System.Collections.IList.Add(), System.Collections.Hashtable.ContainsKey(), System.Runtime.Remoting.ProviderData.CustomData, System.Runtime.Remoting.ProviderData.CustomProperties, System.Runtime.Remoting.ProviderData.Id, System.Collections.DictionaryEntry.Key, System.obj, System.Runtime.Remoting.ProviderData.Ref, System.Runtime.Remoting.ProviderData.Type, and System.Collections.DictionaryEntry.Value.
Referenced by System.Runtime.Remoting.ChannelData.CopyFrom(), and System.Runtime.Remoting.RemotingConfiguration.RegisterChannels().