Terraria Decompiled: System.DefaultBinder.SelectMethod
SelectMethod()
override MethodBase System.DefaultBinder.SelectMethod (BindingFlags bindingAttr, MethodBase[] match, Type[] types, ParameterModifier[] modifiers) inline sealed
Definition at line 1000 of file DefaultBinder.cs.
        {
            Type[] array = new Type[types.Length];
            for (int i = 0; i < types.Length; i++)
            {
                array[i] = types[i].UnderlyingSystemType;
                if (!array[i].IsRuntimeImplemented() && !(array[i] is SignatureType))
                {
                    throw new ArgumentException("Type must be a type provided by the runtime.", "types");
                }
            }
            types = array;
            if (match == null || match.Length == 0)
            {
                throw new ArgumentException("Array may not be empty.", "match");
            }
            MethodBase[] array2 = (MethodBase[])match.Clone();
            int num = 0;
            for (int i = 0; i < array2.Length; i++)
            {
                ParameterInfo[] parametersNoCopy = array2[i].GetParametersNoCopy();
                if (parametersNoCopy.Length == types.Length)
                {
                    int j;
                    for (j = 0; j < types.Length; j++)
                    {
                        Type parameterType = parametersNoCopy[j].ParameterType;
                        if (!types[j].MatchesParameterTypeExactly(parametersNoCopy[j]) && !(parameterType == typeof(object)))
{
                            Type type = types[j];
                            SignatureType signatureType = type as SignatureType;
                            if (signatureType != null)
{
                                MethodInfo methodInfo = array2[i] as MethodInfo;
                                if (methodInfo == null)
{
                                    break;
                                }
                                type = signatureType.TryResolveAgainstGenericMethod(methodInfo);
                                if (type == null)
{
                                    break;
                                }
                            }
                            if (parameterType.IsPrimitive)
{
                                if (!type.UnderlyingSystemType.IsRuntimeImplemented())
{
                                    break;
                                }
                                if (!DefaultBinder.CanChangePrimitive(type.UnderlyingSystemType, parameterType.UnderlyingSystemType))
{
                                    break;
                                }
                            }
                            else if (!parameterType.IsAssignableFrom(type))
{
                                break;
                            }
                        }
                    }
                    if (j == types.Length)
                    {
                        array2[num++] = array2[i];
                    }
                }
            }
            if (num == 0)
            {
                return null;
            }
            if (num == 1)
            {
                return array2[0];
            }
            int num2 = 0;
            bool flag = false;
            int[] array3 = new int[types.Length];
            for (int i = 0; i < types.Length; i++)
            {
                array3[i] = i;
            }
            for (int i = 1; i < num; i++)
            {
                int num3 = DefaultBinder.FindMostSpecificMethod(array2[num2], array3, null, array2[i], array3, null, types, null);
                if (num3 == 0)
                {
                    flag = true;
                }
                else if (num3 == 2)
                {
                    flag = false;
                    num2 = i;
                }
            }
            if (flag)
            {
                throw new AmbiguousMatchException("Ambiguous match found.");
            }
            return array2[num2];
        }
References System.array, System.DefaultBinder.CanChangePrimitive(), System.DefaultBinder.FindMostSpecificMethod(), System.Reflection.MethodBase.GetParametersNoCopy(), System.Type.IsAssignableFrom(), System.Type.IsPrimitive, System.Type.IsRuntimeImplemented(), System.match, System.Reflection.ParameterInfo.ParameterType, and System.Type.UnderlyingSystemType.