Terraria Decompiled: System.DefaultBinder.CanPrimitiveWiden
CanPrimitiveWiden()
static bool System.DefaultBinder.CanPrimitiveWiden (Type source, Type target) inline static private
Definition at line 1115 of file DefaultBinder.cs.
        {
            DefaultBinder.Primitives primitives = DefaultBinder._primitiveConversions[(int)Type.GetTypeCode(source)];
            DefaultBinder.Primitives primitives2 = (DefaultBinder.Primitives)(1 << (int)Type.GetTypeCode(target));
            return (primitives & primitives2) > (DefaultBinder.Primitives)0;
        }
References System.DefaultBinder._primitiveConversions, System.Type.GetTypeCode(), int, and System.source.
Referenced by System.DefaultBinder.CanChangePrimitive(), and System.DefaultBinder.CanChangePrimitiveObjectToType().