Terraria Decompiled: System.DefaultBinder.CanConvertPrimitive
CanConvertPrimitive()
static bool System.DefaultBinder.CanConvertPrimitive (RuntimeType source, RuntimeType target) inline static private
Definition at line 913 of file DefaultBinder.cs.
        {
            if (source.IsEnum)
            {
                return false;
            }
            TypeCode typeCode = Type.GetTypeCode(source);
            TypeCode typeCode2 = Type.GetTypeCode(target);
            if (typeCode == typeCode2 && source.IsPrimitive)
            {
                return true;
            }
            switch (typeCode2)
            {
            case TypeCode.Char:
                return typeCode == TypeCode.Byte || typeCode == TypeCode.UInt16;
            case TypeCode.Int16:
                return typeCode - TypeCode.SByte <= 1;
            case TypeCode.UInt16:
                return typeCode == TypeCode.Char || typeCode == TypeCode.Byte;
            case TypeCode.Int32:
                return typeCode - TypeCode.Char <= 4;
            case TypeCode.UInt32:
                switch (typeCode)
                {
                case TypeCode.Char:
                case TypeCode.Byte:
                case TypeCode.UInt16:
                    return true;
                }
                return false;
            case TypeCode.Int64:
                return typeCode - TypeCode.Char <= 6;
            case TypeCode.UInt64:
                switch (typeCode)
                {
                case TypeCode.Char:
                case TypeCode.Byte:
                case TypeCode.UInt16:
                case TypeCode.UInt32:
                    return true;
                }
                return false;
            case TypeCode.Single:
                return typeCode - TypeCode.Char <= 8;
            case TypeCode.Double:
                return typeCode - TypeCode.Char <= 9;
            }
            if (target == typeof(IntPtr))
            {
                return source == target;
            }
            return target == typeof(UIntPtr) && source == target;
        }
References System.Type.GetTypeCode(), and System.source.
Referenced by System.DefaultBinder.CanConvertPrimitiveObjectToType(), System.DefaultBinder.FindMostSpecificType(), and System.DefaultBinder.SelectProperty().