Terraria Decompiled: System.DefaultBinder.FindMostSpecificMethod
FindMostSpecificMethod()
static int System.DefaultBinder.FindMostSpecificMethod (MethodBase m1, int[] paramOrder1, Type paramArrayType1, MethodBase m2, int[] paramOrder2, Type paramArrayType2, Type[] types, object[] args) inline static private
Definition at line 734 of file DefaultBinder.cs.
        {
            int num = DefaultBinder.FindMostSpecific(m1.GetParametersNoCopy(), paramOrder1, paramArrayType1, m2.GetParametersNoCopy(), paramOrder2, paramArrayType2, types, args);
            if (num != 0)
            {
                return num;
            }
            if (!DefaultBinder.CompareMethodSigAndName(m1, m2))
            {
                return 0;
            }
            int hierarchyDepth = DefaultBinder.GetHierarchyDepth(m1.DeclaringType);
            int hierarchyDepth2 = DefaultBinder.GetHierarchyDepth(m2.DeclaringType);
            if (hierarchyDepth == hierarchyDepth2)
            {
                return 0;
            }
            if (hierarchyDepth < hierarchyDepth2)
            {
                return 2;
            }
            return 1;
        }
References System.DefaultBinder.CompareMethodSigAndName(), System.Reflection.MemberInfo.DeclaringType, System.DefaultBinder.FindMostSpecific(), System.DefaultBinder.GetHierarchyDepth(), and System.Reflection.MethodBase.GetParametersNoCopy().
Referenced by System.DefaultBinder.BindToMethod(), and System.DefaultBinder.SelectMethod().