Terraria Decompiled: System.DefaultBinder.FindMostDerivedNewSlotMeth
FindMostDerivedNewSlotMeth()
static MethodBase System.DefaultBinder.FindMostDerivedNewSlotMeth (MethodBase[] match, int cMatches) inline static package
Definition at line 833 of file DefaultBinder.cs.
        {
            int num = 0;
            MethodBase methodBase = null;
            for (int i = 0; i < cMatches; i++)
            {
                int hierarchyDepth = DefaultBinder.GetHierarchyDepth(match[i].DeclaringType);
                if (hierarchyDepth == num)
                {
                    throw new AmbiguousMatchException(Environment.GetResourceString("Ambiguous match found."));
                }
                if (hierarchyDepth > num)
                {
                    num = hierarchyDepth;
                    methodBase = match[i];
                }
            }
            return methodBase;
        }
References System.Reflection.DeclaringType, System.DefaultBinder.GetHierarchyDepth(), System.Environment.GetResourceString(), and System.match.
Referenced by System.DefaultBinder.ExactBinding().