Terraria Decompiled: System.DefaultBinder.CanConvertPrimitiveObjectToType
CanConvertPrimitiveObjectToType()
static bool System.DefaultBinder.CanConvertPrimitiveObjectToType (object source, RuntimeType type) inline static private
Definition at line 969 of file DefaultBinder.cs.
        {
            if (source == null)
            {
                return true;
            }
            Type type2 = source.GetType();
            return type2 == type || DefaultBinder.CanConvertPrimitive((RuntimeType)type2, type);
        }
References System.DefaultBinder.CanConvertPrimitive(), System.Type.GetType(), and System.source.
Referenced by System.DefaultBinder.BindToField(), and System.DefaultBinder.BindToMethod().