Terraria Decompiled: System.DefaultBinder.BindToField
BindToField()
override FieldInfo System.DefaultBinder.BindToField (BindingFlags bindingAttr, FieldInfo[] match, object value, CultureInfo cultureInfo) inline
Definition at line 297 of file DefaultBinder.cs.
        {
            if (match == null)
            {
                throw new ArgumentNullException("match");
            }
            int num = 0;
            FieldInfo[] array = (FieldInfo[])match.Clone();
            if ((bindingAttr & BindingFlags.SetField) != BindingFlags.Default)
            {
                Type type = value.GetType();
                for (int i = 0; i < array.Length; i++)
                {
                    Type fieldType = array[i].FieldType;
                    if (fieldType == type)
                    {
                        array[num++] = array[i];
                    }
                    else if (value == Empty.Value && fieldType.IsClass)
                    {
                        array[num++] = array[i];
                    }
                    else if (fieldType == typeof(object))
                    {
                        array[num++] = array[i];
                    }
                    else if (fieldType.IsPrimitive)
                    {
                        if (DefaultBinder.CanConvertPrimitiveObjectToType(value, (RuntimeType)fieldType))
{
                            array[num++] = array[i];
                        }
                    }
                    else if (fieldType.IsAssignableFrom(type))
                    {
                        array[num++] = array[i];
                    }
                }
                if (num == 0)
                {
                    throw new MissingFieldException(Environment.GetResourceString("Field not found."));
                }
                if (num == 1)
                {
                    return array[0];
                }
            }
            int num2 = 0;
            bool flag = false;
            for (int i = 1; i < num; i++)
            {
                int num3 = DefaultBinder.FindMostSpecificField(array[num2], array[i]);
                if (num3 == 0)
                {
                    flag = true;
                }
                else if (num3 == 2)
                {
                    num2 = i;
                    flag = false;
                }
            }
            if (flag)
            {
                throw new AmbiguousMatchException(Environment.GetResourceString("Ambiguous match found."));
            }
            return array[num2];
        }
References System.array, System.DefaultBinder.CanConvertPrimitiveObjectToType(), System.DefaultBinder.FindMostSpecificField(), System.Environment.GetResourceString(), System.Type.GetType(), System.Type.IsAssignableFrom(), System.Type.IsClass, System.Type.IsPrimitive, System.match, System.Empty.Value, and System.value.