Terraria Decompiled: System.DefaultBinder.FindMostSpecific
FindMostSpecific()
static int System.DefaultBinder.FindMostSpecific (ParameterInfo[] p1, int[] paramOrder1, Type paramArrayType1, ParameterInfo[] p2, int[] paramOrder2, Type paramArrayType2, Type[] types, object[] args) inline static private
Definition at line 598 of file DefaultBinder.cs.
        {
            if (paramArrayType1 != null && paramArrayType2 == null)
            {
                return 2;
            }
            if (paramArrayType2 != null && paramArrayType1 == null)
            {
                return 1;
            }
            bool flag = false;
            bool flag2 = false;
            for (int i = 0; i < types.Length; i++)
            {
                if (args == null || args[i] != Type.Missing)
                {
                    Type type;
                    if (paramArrayType1 != null && paramOrder1[i] >= p1.Length - 1)
                    {
                        type = paramArrayType1;
                    }
                    else
                    {
                        type = p1[paramOrder1[i]].ParameterType;
                    }
                    Type type2;
                    if (paramArrayType2 != null && paramOrder2[i] >= p2.Length - 1)
                    {
                        type2 = paramArrayType2;
                    }
                    else
                    {
                        type2 = p2[paramOrder2[i]].ParameterType;
                    }
                    if (!(type == type2))
                    {
                        switch (DefaultBinder.FindMostSpecificType(type, type2, types[i]))
{
                        case 0:
                            return 0;
                        case 1:
                            flag = true;
                            break;
                        case 2:
                            flag2 = true;
                            break;
                        }
                    }
                }
            }
            if (flag == flag2)
            {
                if (!flag && args != null)
                {
                    if (p1.Length > p2.Length)
                    {
                        return 1;
                    }
                    if (p2.Length > p1.Length)
                    {
                        return 2;
                    }
                }
                return 0;
            }
            if (!flag)
            {
                return 2;
            }
            return 1;
        }
References System.DefaultBinder.FindMostSpecificType(), System.Type.Missing, and System.Reflection.ParameterInfo.ParameterType.
Referenced by System.DefaultBinder.FindMostSpecificMethod(), and System.DefaultBinder.SelectProperty().