Terraria Decompiled: Newtonsoft.Json.Linq.JConstructor.Load
Load() [2/2]
static new JConstructor Newtonsoft.Json.Linq.JConstructor.Load (JsonReader reader, JsonLoadSettings settings) inline static
Definition at line 167 of file JConstructor.cs.
        {
            if (reader.TokenType == JsonToken.None && !reader.Read())
            {
                throw JsonReaderException.Create(reader, "Error reading JConstructor from JsonReader.");
            }
            reader.MoveToContent();
            if (reader.TokenType != JsonToken.StartConstructor)
            {
                throw JsonReaderException.Create(reader, "Error reading JConstructor from JsonReader. Current JsonReader item is not a constructor: {0}".FormatWith(CultureInfo.InvariantCulture, reader.TokenType));
            }
            JConstructor jconstructor = new JConstructor((string)reader.Value);
            jconstructor.SetLineInfo(reader as IJsonLineInfo, settings);
            jconstructor.ReadTokenFrom(reader, settings);
            return jconstructor;
        }
References Newtonsoft.Json.JsonReaderException.Create(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.Linq.JConstructor.JConstructor(), Newtonsoft.Json.JsonReader.MoveToContent(), Newtonsoft.Json.JsonReader.Read(), Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(), Newtonsoft.Json.Linq.JToken.SetLineInfo(), Newtonsoft.Json.JsonReader.TokenType, and Newtonsoft.Json.JsonReader.Value.