Terraria Decompiled: System.Collections.BitArray.RightShift
RightShift()
BitArray System.Collections.BitArray.RightShift (int count) inline
Definition at line 248 of file BitArray.cs.
        {
            if (count > 0)
            {
                int num = 0;
                int arrayLength = BitArray.GetArrayLength(this.m_length, 32);
                if (count < this.m_length)
                {
                    int i = count / 32;
                    int num2 = count - i * 32;
                    if (num2 == 0)
                    {
                        uint num3 = uint.MaxValue >> 32 - this.m_length % 32;
                        this.m_array[arrayLength - 1] &= (int)num3;
                        Array.Copy(this.m_array, i, this.m_array, 0, arrayLength - i);
                        num = arrayLength - i;
                    }
                    else
                    {
                        int num4 = arrayLength - 1;
                        while (i < num4)
{
                            uint num5 = (uint)this.m_array[i] >> num2;
                            int num6 = this.m_array[++i] << ((32 - num2) & 31);
                            this.m_array[num++] = num6 | (int)num5;
                        }
                        uint num7 = uint.MaxValue >> 32 - this.m_length % 32;
                        num7 &= (uint)this.m_array[i];
                        this.m_array[num++] = (int)(num7 >> num2);
                    }
                }
                Array.Clear(this.m_array, num, arrayLength - num);
                this._version++;
                return this;
            }
            if (count < 0)
            {
                throw new ArgumentOutOfRangeException("count", count, "Non-negative number required.");
            }
            this._version++;
            return this;
        }
References System.Collections.BitArray._version, System.Array.Clear(), System.Array.Copy(), System.count, System.Collections.BitArray.GetArrayLength(), int, System.Collections.BitArray.m_array, and System.Collections.BitArray.m_length.