Terraria Decompiled: System.IO.File.d__80.MoveNext
MoveNext()
void IAsyncStateMachine. System.IO.File.d__80.MoveNext () inline
Implements System.Runtime.CompilerServices.IAsyncStateMachine.
Definition at line 1781 of file File.cs.
            {
                int num2;
                int num = num2;
                try
                {
                    if (num > 1)
                    {
                        textWriter = writer;
                    }
                    try
                    {
                        ConfiguredTaskAwaitable.ConfiguredTaskAwaiter configuredTaskAwaiter2;
                        ConfiguredTaskAwaitable.ConfiguredTaskAwaiter configuredTaskAwaiter;
                        if (num != 0)
{
                            if (num == 1)
{
                                configuredTaskAwaiter = configuredTaskAwaiter2;
                                configuredTaskAwaiter2 = default(ConfiguredTaskAwaitable.ConfiguredTaskAwaiter);
                                num = (num2 = -1);
                                goto IL_0158;
                            }
                            enumerator = contents.GetEnumerator();
                        }
                        try
{
                            if (num != 0)
{
                                goto IL_00BD;
                            }
                            configuredTaskAwaiter = configuredTaskAwaiter2;
                            configuredTaskAwaiter2 = default(ConfiguredTaskAwaitable.ConfiguredTaskAwaiter);
                            num = (num2 = -1);
                            IL_00B6:
                            configuredTaskAwaiter.GetResult();
                            IL_00BD:
                            if (enumerator.MoveNext())
{
                                string text = enumerator.Current;
                                cancellationToken.ThrowIfCancellationRequested();
                                configuredTaskAwaiter = writer.WriteLineAsync(text).ConfigureAwait(false).GetAwaiter();
                                if (!configuredTaskAwaiter.IsCompleted)
{
                                    num = (num2 = 0);
                                    configuredTaskAwaiter2 = configuredTaskAwaiter;
                                    this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredTaskAwaitable.ConfiguredTaskAwaiter, File.<InternalWriteAllLinesAsync>d__80>(ref configuredTaskAwaiter, ref this);
                                    return;
                                }
                                goto IL_00B6;
                            }
                        }
                        finally
{
                            if (num < 0 && enumerator != null)
{
                                enumerator.Dispose();
                            }
                        }
                        enumerator = null;
                        cancellationToken.ThrowIfCancellationRequested();
                        configuredTaskAwaiter = writer.FlushAsync().ConfigureAwait(false).GetAwaiter();
                        if (!configuredTaskAwaiter.IsCompleted)
{
                            num = (num2 = 1);
                            configuredTaskAwaiter2 = configuredTaskAwaiter;
                            this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredTaskAwaitable.ConfiguredTaskAwaiter, File.<InternalWriteAllLinesAsync>d__80>(ref configuredTaskAwaiter, ref this);
                            return;
                        }
                        IL_0158:
                        configuredTaskAwaiter.GetResult();
                    }
                    finally
                    {
                        if (num < 0 && textWriter != null)
{
                            ((IDisposable)textWriter).Dispose();
                        }
                    }
                    textWriter = null;
                }
                catch (Exception ex)
                {
                    num2 = -2;
                    this.<>t__builder.SetException(ex);
                    return;
                }
                num2 = -2;
                this.<>t__builder.SetResult();
            }
References System.Collections.Generic.IEnumerable< out T >.GetEnumerator(), System.Runtime.CompilerServices.ConfiguredTaskAwaitable< TResult >.ConfiguredTaskAwaiter.GetResult(), System.IO.File.InternalWriteAllLinesAsync(), System.Runtime.CompilerServices.ConfiguredTaskAwaitable< TResult >.ConfiguredTaskAwaiter.IsCompleted, and System.text.