Terraria Decompiled: Ionic.Zip.CountingStream.Read
Read()
override int Ionic.Zip.CountingStream.Read (byte[] buffer, int offset, int count) inline
Definition at line 68 of file CountingStream.cs.
        {
            int num = this._s.Read(buffer, offset, count);
            this._bytesRead += (long)num;
            return num;
        }
References Ionic.Zip.CountingStream._s, System.count, long, System.offset, and System.IO.Stream.Read().
Referenced by Ionic.Zip.ZipEntry.CopyThroughWithNoChange(), and Ionic.Zip.ZipEntry.CopyThroughWithRecompute().