Terraria Decompiled: Terraria.Social.WeGame.WeGameP2PReader.Receive
Receive()
int Terraria.Social.WeGame.WeGameP2PReader.Receive (RailID user, byte[] buffer, int bufferOffset, int bufferSize) inline
Definition at line 148 of file WeGameP2PReader.cs.
        {
            uint num = 0U;
            Dictionary<RailID, Queue<WeGameP2PReader.ReadResult>> pendingReadBuffers = this._pendingReadBuffers;
            lock (pendingReadBuffers)
            {
                if (!this._pendingReadBuffers.ContainsKey(user))
                {
                    return 0;
                }
                Queue<WeGameP2PReader.ReadResult> queue = this._pendingReadBuffers[user];
                while (queue.Count > 0)
                {
                    WeGameP2PReader.ReadResult readResult = queue.Peek();
                    uint num2 = Math.Min((uint)(bufferSize - (int)num), readResult.Size - readResult.Offset);
                    if (num2 == 0U)
                    {
                        return (int)num;
                    }
                    Array.Copy(readResult.Data, (long)((ulong)readResult.Offset), buffer, (long)bufferOffset + (long)((ulong)num), (long)((ulong)num2));
                    if (num2 == readResult.Size - readResult.Offset)
                    {
                        this._bufferPool.Enqueue(queue.Dequeue().Data);
                    }
                    else
                    {
                        readResult.Offset += num2;
                    }
                    num += num2;
                }
            }
            return (int)num;
        }
References Terraria.Social.WeGame.WeGameP2PReader._bufferPool, Terraria.Social.WeGame.WeGameP2PReader._pendingReadBuffers, System.Array.Copy(), Terraria.Social.WeGame.WeGameP2PReader.ReadResult.Data, System.Collections.Generic.Queue< T >.Enqueue(), System.Math.Min(), Terraria.Social.WeGame.WeGameP2PReader.ReadResult.Offset, System.queue, Terraria.Social.WeGame.WeGameP2PReader.ReadResult.Size, and System.U.
Referenced by Terraria.Social.WeGame.NetSocialModule.Receive().