Terraria Decompiled: Terraria.Social.WeGame.WeGameP2PReader.ReadTick
ReadTick()
void Terraria.Social.WeGame.WeGameP2PReader.ReadTick () inline
Definition at line 96 of file WeGameP2PReader.cs.
        {
            if (!this.IsValid())
            {
                return;
            }
            Dictionary<RailID, Queue<WeGameP2PReader.ReadResult>> pendingReadBuffers = this._pendingReadBuffers;
            lock (pendingReadBuffers)
            {
                while (this._deletionQueue.Count > 0)
                {
                    this._pendingReadBuffers.Remove(this._deletionQueue.Dequeue());
                }
                uint num;
                while (this.IsPacketAvailable(out num))
                {
                    byte[] array;
                    if (this._bufferPool.Count == 0)
                    {
                        array = new byte[Math.Max(num, 4096U)];
                    }
                    else
                    {
                        array = this._bufferPool.Dequeue();
                    }
                    RailID railID = new RailID();
                    object railLock = this.RailLock;
                    bool flag3;
                    lock (railLock)
                    {
                        flag3 = rail_api.RailFactory().RailNetworkHelper().ReadData(this.GetLocalPeer(), railID, array, num) == 0;
                    }
                    if (flag3)
                    {
                        if (this._readEvent == null || this._readEvent(array, (int)num, railID))
{
                            if (!this._pendingReadBuffers.ContainsKey(railID))
{
                                this._pendingReadBuffers[railID] = new Queue<WeGameP2PReader.ReadResult>();
                            }
                            this._pendingReadBuffers[railID].Enqueue(new WeGameP2PReader.ReadResult(array, num));
                        }
                        else
{
                            this._bufferPool.Enqueue(array);
                        }
                    }
                }
            }
        }
References Terraria.Social.WeGame.WeGameP2PReader._bufferPool, Terraria.Social.WeGame.WeGameP2PReader._deletionQueue, Terraria.Social.WeGame.WeGameP2PReader._pendingReadBuffers, Terraria.Social.WeGame.WeGameP2PReader._readEvent, System.array, System.Collections.Generic.Queue< T >.Count, System.Collections.Generic.Queue< T >.Dequeue(), System.Collections.Generic.Queue< T >.Enqueue(), Terraria.Social.WeGame.WeGameP2PReader.GetLocalPeer(), Terraria.Social.WeGame.WeGameP2PReader.IsPacketAvailable(), Terraria.Social.WeGame.WeGameP2PReader.IsValid(), System.Math.Max(), rail.rail_api.RailFactory(), Terraria.Social.WeGame.WeGameP2PReader.RailLock, rail.IRailFactory.RailNetworkHelper(), rail.IRailNetwork.ReadData(), and System.U.
Referenced by Terraria.Social.WeGame.NetSocialModule.Initialize().