Terraria Decompiled: System.Threading.Tasks.TaskExceptionHolder.AddFaultException
AddFaultException()
void System.Threading.Tasks.TaskExceptionHolder.AddFaultException (object exceptionObject) inline private
Definition at line 89 of file TaskExceptionHolder.cs.
        {
            LowLevelListWithIList<ExceptionDispatchInfo> lowLevelListWithIList = this.m_faultExceptions;
            if (lowLevelListWithIList == null)
            {
                lowLevelListWithIList = (this.m_faultExceptions = new LowLevelListWithIList<ExceptionDispatchInfo>(1));
            }
            Exception ex = exceptionObject as Exception;
            if (ex != null)
            {
                lowLevelListWithIList.Add(ExceptionDispatchInfo.Capture(ex));
            }
            else
            {
                ExceptionDispatchInfo exceptionDispatchInfo = exceptionObject as ExceptionDispatchInfo;
                if (exceptionDispatchInfo != null)
                {
                    lowLevelListWithIList.Add(exceptionDispatchInfo);
                }
                else
                {
                    IEnumerable<Exception> enumerable = exceptionObject as IEnumerable<Exception>;
                    if (enumerable != null)
                    {
                        using (IEnumerator<Exception> enumerator = enumerable.GetEnumerator())
{
                            while (enumerator.MoveNext())
{
                                Exception ex2 = enumerator.Current;
                                lowLevelListWithIList.Add(ExceptionDispatchInfo.Capture(ex2));
                            }
                            goto IL_00AE;
                        }
                    }
                    IEnumerable<ExceptionDispatchInfo> enumerable2 = exceptionObject as IEnumerable<ExceptionDispatchInfo>;
                    if (enumerable2 == null)
                    {
                        throw new ArgumentException("(Internal)Expected an Exception or an IEnumerable<Exception>", "exceptionObject");
                    }
                    lowLevelListWithIList.AddRange(enumerable2);
                }
            }
            IL_00AE:
            if (lowLevelListWithIList.Count > 0)
            {
                this.MarkAsUnhandled();
            }
        }
References System.Collections.Generic.LowLevelList< T >.Add(), System.Collections.Generic.LowLevelList< T >.AddRange(), System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture(), System.Collections.Generic.LowLevelList< T >.Count, System.Collections.Generic.IEnumerator< out T >.Current, System.Collections.Generic.IEnumerable< out T >.GetEnumerator(), System.Threading.Tasks.TaskExceptionHolder.m_faultExceptions, System.Threading.Tasks.TaskExceptionHolder.MarkAsUnhandled(), and System.Collections.IEnumerator.MoveNext().
Referenced by System.Threading.Tasks.TaskExceptionHolder.Add().