Terraria Decompiled: Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.CreatePackInfoButton
CreatePackInfoButton()
UIElement Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.CreatePackInfoButton (ResourcePack resourcePack) inline private
Definition at line 225 of file UIResourcePackSelectionMenu.cs.
        {
            UIResourcePackInfoButton<string> uiresourcePackInfoButton = new UIResourcePackInfoButton<string>("", 0.8f, false);
            uiresourcePackInfoButton.Width = StyleDimension.FromPixelsAndPercent(0f, 0.5f);
            uiresourcePackInfoButton.Height = StyleDimension.Fill;
            uiresourcePackInfoButton.ResourcePack = resourcePack;
            uiresourcePackInfoButton.SetPadding(0f);
            UIImage uiimage = new UIImage(Main.Assets.Request<Texture2D>("Images/UI/CharCreation/CharInfo", 1))
            {
                HAlign = 0.5f,
                VAlign = 0.5f,
                IgnoresMouseInteraction = true
            };
            uiresourcePackInfoButton.Append(uiimage);
            uiresourcePackInfoButton.OnMouseOver += delegate(UIMouseEvent evt, UIElement listeningElement)
            {
                SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
            };
            uiresourcePackInfoButton.OnLeftClick += this.Click_Info;
            return uiresourcePackInfoButton;
        }
References Terraria.UI.UIElement.Append(), Terraria.Main.Assets, Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.Click_Info(), Terraria.UI.StyleDimension.Fill, Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.IgnoresMouseInteraction, Terraria.Audio.SoundEngine.PlaySound(), Terraria.UI.UIElement.SetPadding(), and Terraria.UI.UIElement.VAlign.
Referenced by Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.PopulatePackList().