Terraria Decompiled: Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.PopulatePackList
PopulatePackList()
void Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.PopulatePackList () inline private
Definition at line 34 of file UIResourcePackSelectionMenu.cs.
        {
            this._availablePacksList.Clear();
            this._enabledPacksList.Clear();
            this.CleanUpResourcePackPriority();
            IEnumerable<ResourcePack> enabledPacks = this._packsList.EnabledPacks;
            IEnumerable<ResourcePack> disabledPacks = this._packsList.DisabledPacks;
            int num = 0;
            foreach (ResourcePack resourcePack in disabledPacks)
            {
                UIResourcePack uiresourcePack = new UIResourcePack(resourcePack, num)
                {
                    Width = StyleDimension.FromPixelsAndPercent(0f, 1f)
                };
                UIElement uielement = this.CreatePackToggleButton(resourcePack);
                uielement.OnUpdate += this.EnablePackUpdate;
                uielement.SetSnapPoint("ToggleToOn", num, null, null);
                uiresourcePack.ContentPanel.Append(uielement);
                uielement = this.CreatePackInfoButton(resourcePack);
                uielement.OnUpdate += this.SeeInfoUpdate;
                uielement.SetSnapPoint("InfoOff", num, null, null);
                uiresourcePack.ContentPanel.Append(uielement);
                this._availablePacksList.Add(uiresourcePack);
                num++;
            }
            num = 0;
            foreach (ResourcePack resourcePack2 in enabledPacks)
            {
                UIResourcePack uiresourcePack2 = new UIResourcePack(resourcePack2, num)
                {
                    Width = StyleDimension.FromPixelsAndPercent(0f, 1f)
                };
                if (resourcePack2.IsEnabled)
                {
                    UIElement uielement2 = this.CreatePackToggleButton(resourcePack2);
                    uielement2.Left = new StyleDimension(0f, 0f);
                    uielement2.Width = new StyleDimension(0f, 0.5f);
                    uielement2.OnUpdate += this.DisablePackUpdate;
                    uielement2.SetSnapPoint("ToggleToOff", num, null, null);
                    uiresourcePack2.ContentPanel.Append(uielement2);
                    uielement2 = this.CreatePackInfoButton(resourcePack2);
                    uielement2.OnUpdate += this.SeeInfoUpdate;
                    uielement2.Left = new StyleDimension(0f, 0.5f);
                    uielement2.Width = new StyleDimension(0f, 0.16666667f);
                    uielement2.SetSnapPoint("InfoOn", num, null, null);
                    uiresourcePack2.ContentPanel.Append(uielement2);
                    uielement2 = this.CreateOffsetButton(resourcePack2, -1);
                    uielement2.Left = new StyleDimension(0f, 0.6666667f);
                    uielement2.Width = new StyleDimension(0f, 0.16666667f);
                    uielement2.SetSnapPoint("OrderUp", num, null, null);
                    uiresourcePack2.ContentPanel.Append(uielement2);
                    uielement2 = this.CreateOffsetButton(resourcePack2, 1);
                    uielement2.Left = new StyleDimension(0f, 0.8333334f);
                    uielement2.Width = new StyleDimension(0f, 0.16666667f);
                    uielement2.SetSnapPoint("OrderDown", num, null, null);
                    uiresourcePack2.ContentPanel.Append(uielement2);
                }
                this._enabledPacksList.Add(uiresourcePack2);
                num++;
            }
            this.UpdateTitles();
        }
References Terraria.GameContent.UI.States.UIResourcePackSelectionMenu._availablePacksList, Terraria.GameContent.UI.States.UIResourcePackSelectionMenu._enabledPacksList, Terraria.GameContent.UI.States.UIResourcePackSelectionMenu._packsList, Terraria.GameContent.UI.Elements.UIList.Add(), Terraria.UI.UIElement.Append(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.CleanUpResourcePackPriority(), Terraria.GameContent.UI.Elements.UIList.Clear(), Terraria.GameContent.UI.Elements.UIResourcePack.ContentPanel, Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.CreateOffsetButton(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.CreatePackInfoButton(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.CreatePackToggleButton(), Terraria.IO.ResourcePackList.DisabledPacks, Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.DisablePackUpdate(), Terraria.IO.ResourcePackList.EnabledPacks, Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.EnablePackUpdate(), Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.IO.ResourcePack.IsEnabled, Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.SeeInfoUpdate(), Terraria.UI.UIElement.SetSnapPoint(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.UpdateTitles(), and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.CreateOffsetButton(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.CreatePackToggleButton(), and Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.UIResourcePackSelectionMenu().