Terraria Decompiled: Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.BuildPage
BuildPage()
void Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.BuildPage () inline private
Definition at line 276 of file UIResourcePackSelectionMenu.cs.
        {
            base.RemoveAllChildren();
            UIElement uielement = new UIElement();
            uielement.Width.Set(0f, 0.8f);
            uielement.MaxWidth.Set(800f, 0f);
            uielement.MinWidth.Set(600f, 0f);
            uielement.Top.Set(240f, 0f);
            uielement.Height.Set(-240f, 1f);
            uielement.HAlign = 0.5f;
            base.Append(uielement);
            UIPanel uipanel = new UIPanel
            {
                Width = StyleDimension.Fill,
                Height = new StyleDimension(-110f, 1f),
                BackgroundColor = new Color(33, 43, 79) * 0.8f,
                PaddingRight = 0f,
                PaddingLeft = 0f
            };
            uielement.Append(uipanel);
            int num = 35;
            int num2 = num;
            int num3 = 30;
            UIElement uielement2 = new UIElement
            {
                Width = StyleDimension.Fill,
                Height = StyleDimension.FromPixelsAndPercent((float)(-(float)(num3 + 4 + 5)), 1f),
                VAlign = 1f
            };
            uielement2.SetPadding(0f);
            uipanel.Append(uielement2);
            UIElement uielement3 = new UIElement
            {
                Width = new StyleDimension(-20f, 0.5f),
                Height = new StyleDimension(0f, 1f),
                Left = new StyleDimension(10f, 0f)
            };
            uielement3.SetPadding(0f);
            uielement2.Append(uielement3);
            UIElement uielement4 = new UIElement
            {
                Width = new StyleDimension(-20f, 0.5f),
                Height = new StyleDimension(0f, 1f),
                Left = new StyleDimension(-10f, 0f),
                HAlign = 1f
            };
            uielement4.SetPadding(0f);
            uielement2.Append(uielement4);
            UIList uilist = new UIList
            {
                Width = new StyleDimension(-25f, 1f),
                Height = new StyleDimension(0f, 1f),
                ListPadding = 5f,
                HAlign = 1f
            };
            uielement3.Append(uilist);
            this._availablePacksList = uilist;
            UIList uilist2 = new UIList
            {
                Width = new StyleDimension(-25f, 1f),
                Height = new StyleDimension(0f, 1f),
                ListPadding = 5f,
                HAlign = 0f,
                Left = new StyleDimension(0f, 0f)
            };
            uielement4.Append(uilist2);
            this._enabledPacksList = uilist2;
            UIText uitext = new UIText(Language.GetText("UI.AvailableResourcePacksTitle"), 1f, false)
            {
                HAlign = 0f,
                Left = new StyleDimension(25f, 0f),
                Width = new StyleDimension(-25f, 0.5f),
                VAlign = 0f,
                Top = new StyleDimension(10f, 0f)
            };
            this._titleAvailable = uitext;
            uipanel.Append(uitext);
            UIText uitext2 = new UIText(Language.GetText("UI.EnabledResourcePacksTitle"), 1f, false)
            {
                HAlign = 1f,
                Left = new StyleDimension(-25f, 0f),
                Width = new StyleDimension(-25f, 0.5f),
                VAlign = 0f,
                Top = new StyleDimension(10f, 0f)
            };
            this._titleEnabled = uitext2;
            uipanel.Append(uitext2);
            UITextPanel<LocalizedText> uitextPanel = new UITextPanel<LocalizedText>(Language.GetText("UI.ResourcePacks"), 1f, true)
            {
                HAlign = 0.5f,
                VAlign = 0f,
                Top = new StyleDimension(-44f, 0f),
                BackgroundColor = new Color(73, 94, 171)
            };
            uitextPanel.SetPadding(13f);
            uielement.Append(uitextPanel);
            UIScrollbar uiscrollbar = new UIScrollbar(UIScrollbar.ColorTheme.Blue)
            {
                Height = new StyleDimension(0f, 1f),
                HAlign = 0f,
                Left = new StyleDimension(0f, 0f)
            };
            uielement3.Append(uiscrollbar);
            this._availablePacksList.SetScrollbar(uiscrollbar);
            UIVerticalSeparator uiverticalSeparator = new UIVerticalSeparator
            {
                Height = new StyleDimension(-12f, 1f),
                HAlign = 0.5f,
                VAlign = 1f,
                Color = new Color(89, 116, 213, 255) * 0.9f
            };
            uipanel.Append(uiverticalSeparator);
            UIHorizontalSeparator uihorizontalSeparator = new UIHorizontalSeparator(2, true);
            uihorizontalSeparator.Width = new StyleDimension((float)(-(float)num2), 0.5f);
            uihorizontalSeparator.VAlign = 0f;
            uihorizontalSeparator.HAlign = 0f;
            uihorizontalSeparator.Color = new Color(89, 116, 213, 255) * 0.9f;
            uihorizontalSeparator.Top = new StyleDimension((float)num3, 0f);
            uihorizontalSeparator.Left = new StyleDimension((float)num, 0f);
            UIHorizontalSeparator uihorizontalSeparator2 = new UIHorizontalSeparator(2, true);
            uihorizontalSeparator2.Width = new StyleDimension((float)(-(float)num2), 0.5f);
            uihorizontalSeparator2.VAlign = 0f;
            uihorizontalSeparator2.HAlign = 1f;
            uihorizontalSeparator2.Color = new Color(89, 116, 213, 255) * 0.9f;
            uihorizontalSeparator2.Top = new StyleDimension((float)num3, 0f);
            uihorizontalSeparator2.Left = new StyleDimension((float)(-(float)num), 0f);
            UIScrollbar uiscrollbar2 = new UIScrollbar(UIScrollbar.ColorTheme.Blue)
            {
                Height = new StyleDimension(0f, 1f),
                HAlign = 1f
            };
            uielement4.Append(uiscrollbar2);
            this._enabledPacksList.SetScrollbar(uiscrollbar2);
            this.AddBackAndFolderButtons(uielement);
        }
References Terraria.GameContent.UI.States.UIResourcePackSelectionMenu._availablePacksList, Terraria.GameContent.UI.States.UIResourcePackSelectionMenu._enabledPacksList, Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.AddBackAndFolderButtons(), Terraria.UI.UIElement.Append(), Microsoft.Xna.Framework.Graphics.Color, Terraria.UI.StyleDimension.Fill, Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.Localization.Language.GetText(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.Left, Terraria.UI.UIElement.MaxWidth, Terraria.UI.UIElement.MinWidth, Terraria.UI.UIElement.PaddingLeft, Terraria.UI.UIElement.PaddingRight, Terraria.UI.StyleDimension.Set(), Terraria.UI.UIElement.SetPadding(), Terraria.GameContent.UI.Elements.UIList.SetScrollbar(), Terraria.UI.UIElement.Top, Terraria.UI.UIElement.UIElement(), Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.UIResourcePackSelectionMenu().