Terraria Decompiled: Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.CreateOffsetButton
CreateOffsetButton()
UIElement Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.CreateOffsetButton (ResourcePack resourcePack, int offset) inline private
Definition at line 98 of file UIResourcePackSelectionMenu.cs.
        {
            GroupOptionButton<bool> groupOptionButton = new GroupOptionButton<bool>(true, null, null, Color.White, null, 0.8f, 0.5f, 10f)
            {
                Left = StyleDimension.FromPercent(0.5f),
                Width = StyleDimension.FromPixelsAndPercent(0f, 0.5f),
                Height = StyleDimension.Fill
            };
            bool flag = (offset == -1 && resourcePack.SortingOrder == 0) | (offset == 1 && resourcePack.SortingOrder == this._packsList.EnabledPacks.Count<ResourcePack>() - 1);
            Color lightCyan = Color.LightCyan;
            groupOptionButton.SetColorsBasedOnSelectionState(lightCyan, lightCyan, 0.7f, 0.7f);
            groupOptionButton.ShowHighlightWhenSelected = false;
            groupOptionButton.SetPadding(0f);
            Asset<Texture2D> asset = Main.Assets.Request<Texture2D>("Images/UI/TexturePackButtons", 1);
            UIImageFramed uiimageFramed = new UIImageFramed(asset, asset.Frame(2, 2, (offset == 1) ? 1 : 0, 0, 0, 0))
            {
                HAlign = 0.5f,
                VAlign = 0.5f,
                IgnoresMouseInteraction = true
            };
            groupOptionButton.Append(uiimageFramed);
            groupOptionButton.OnMouseOver += delegate(UIMouseEvent evt, UIElement listeningElement)
            {
                SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
            };
            int offsetLocalForLambda = offset;
            if (flag)
            {
                groupOptionButton.OnLeftClick += delegate(UIMouseEvent evt, UIElement listeningElement)
                {
                    SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                };
            }
            else
            {
                groupOptionButton.OnLeftClick += delegate(UIMouseEvent evt, UIElement listeningElement)
                {
                    SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                    this.OffsetResourcePackPriority(resourcePack, offsetLocalForLambda);
                    this.PopulatePackList();
                    Main.instance.ResetAllContentBasedRenderTargets();
                };
            }
            if (offset == 1)
            {
                groupOptionButton.OnUpdate += this.OffsetFrontwardUpdate;
            }
            else
            {
                groupOptionButton.OnUpdate += this.OffsetBackwardUpdate;
            }
            return groupOptionButton;
        }
References Terraria.UI.UIElement.Append(), Terraria.Main.Assets, Terraria.UI.StyleDimension.FromPercent(), Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.IgnoresMouseInteraction, Terraria.Main.instance, Terraria.UI.UIElement.Left, Microsoft.Xna.Framework.Color.LightCyan, System.offset, Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.OffsetBackwardUpdate(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.OffsetFrontwardUpdate(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.OffsetResourcePackPriority(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.PopulatePackList(), Terraria.Main.ResetAllContentBasedRenderTargets(), Terraria.GameContent.UI.Elements.GroupOptionButton< T >.SetColorsBasedOnSelectionState(), Terraria.UI.UIElement.SetPadding(), Terraria.IO.ResourcePack.SortingOrder, Terraria.UI.UIElement.VAlign, Microsoft.Xna.Framework.Color.White, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.PopulatePackList().