Terraria Decompiled: Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.CreatePackToggleButton
CreatePackToggleButton()
UIElement Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.CreatePackToggleButton (ResourcePack resourcePack) inline private
Definition at line 153 of file UIResourcePackSelectionMenu.cs.
        {
            Language.GetText(resourcePack.IsEnabled ? "GameUI.Enabled" : "GameUI.Disabled");
            GroupOptionButton<bool> groupOptionButton = new GroupOptionButton<bool>(true, null, null, Color.White, null, 0.8f, 0.5f, 10f);
            groupOptionButton.Left = StyleDimension.FromPercent(0.5f);
            groupOptionButton.Width = StyleDimension.FromPixelsAndPercent(0f, 0.5f);
            groupOptionButton.Height = StyleDimension.Fill;
            groupOptionButton.SetColorsBasedOnSelectionState(Color.LightGreen, Color.PaleVioletRed, 0.7f, 0.7f);
            groupOptionButton.SetCurrentOption(resourcePack.IsEnabled);
            groupOptionButton.ShowHighlightWhenSelected = false;
            groupOptionButton.SetPadding(0f);
            Asset<Texture2D> asset = Main.Assets.Request<Texture2D>("Images/UI/TexturePackButtons", 1);
            UIImageFramed uiimageFramed = new UIImageFramed(asset, asset.Frame(2, 2, resourcePack.IsEnabled ? 0 : 1, 1, 0, 0))
            {
                HAlign = 0.5f,
                VAlign = 0.5f,
                IgnoresMouseInteraction = true
            };
            groupOptionButton.Append(uiimageFramed);
            groupOptionButton.OnMouseOver += delegate(UIMouseEvent evt, UIElement listeningElement)
            {
                SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
            };
            groupOptionButton.OnLeftClick += delegate(UIMouseEvent evt, UIElement listeningElement)
            {
                SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                resourcePack.IsEnabled = !resourcePack.IsEnabled;
                this.SetResourcePackAsTopPriority(resourcePack);
                this.PopulatePackList();
                Main.instance.ResetAllContentBasedRenderTargets();
            };
            return groupOptionButton;
        }
References Terraria.UI.UIElement.Append(), Terraria.Main.Assets, Terraria.UI.StyleDimension.Fill, Terraria.UI.StyleDimension.FromPercent(), Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.Localization.Language.GetText(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.IgnoresMouseInteraction, Terraria.Main.instance, Terraria.IO.ResourcePack.IsEnabled, Microsoft.Xna.Framework.Color.LightGreen, Microsoft.Xna.Framework.Color.PaleVioletRed, Terraria.Audio.SoundEngine.PlaySound(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.PopulatePackList(), Terraria.Main.ResetAllContentBasedRenderTargets(), Terraria.GameContent.UI.Elements.GroupOptionButton< T >.SetColorsBasedOnSelectionState(), Terraria.GameContent.UI.Elements.GroupOptionButton< T >.SetCurrentOption(), Terraria.UI.UIElement.SetPadding(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.SetResourcePackAsTopPriority(), Terraria.UI.UIElement.VAlign, and Microsoft.Xna.Framework.Color.White.
Referenced by Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.PopulatePackList().