Terraria Decompiled: Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.HandleBackButtonUsage
HandleBackButtonUsage()
void Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.HandleBackButtonUsage () inline
Implements Terraria.UI.IHaveBackButtonCommand.
Definition at line 473 of file UIResourcePackSelectionMenu.cs.
        {
            SoundEngine.PlaySound(11, -1, -1, 1, 1f, 0f);
            this.ApplyListChanges();
            Main.SaveSettings();
            if (this._uiStateToGoBackTo != null)
            {
                Main.MenuUI.SetState(this._uiStateToGoBackTo);
                return;
            }
            Main.menuMode = 0;
            IngameFancyUI.Close(true);
        }
References Terraria.GameContent.UI.States.UIResourcePackSelectionMenu._uiStateToGoBackTo, Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.ApplyListChanges(), Terraria.UI.IngameFancyUI.Close(), Terraria.Main.MenuUI, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.SaveSettings(), and Terraria.UI.UserInterface.SetState().
Referenced by Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.GoBackClick().