Terraria Decompiled: Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.SetupGamepadPoints
SetupGamepadPoints()
void Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.SetupGamepadPoints (SpriteBatch spriteBatch) inline private
Definition at line 550 of file UIResourcePackSelectionMenu.cs.
        {
            UILinkPointNavigator.Shortcuts.BackButtonCommand = 7;
            int num = 3000;
            int num2 = num;
            List<SnapPoint> snapPoints = this.GetSnapPoints();
            List<SnapPoint> snapPoints2 = this._availablePacksList.GetSnapPoints();
            this._helper.CullPointsOutOfElementArea(spriteBatch, snapPoints2, this._availablePacksList);
            List<SnapPoint> snapPoints3 = this._enabledPacksList.GetSnapPoints();
            this._helper.CullPointsOutOfElementArea(spriteBatch, snapPoints3, this._enabledPacksList);
            UILinkPoint[] verticalStripFromCategoryName = this._helper.GetVerticalStripFromCategoryName(ref num2, snapPoints2, "ToggleToOn");
            UILinkPoint[] verticalStripFromCategoryName2 = this._helper.GetVerticalStripFromCategoryName(ref num2, snapPoints2, "InfoOff");
            UILinkPoint[] verticalStripFromCategoryName3 = this._helper.GetVerticalStripFromCategoryName(ref num2, snapPoints3, "ToggleToOff");
            UILinkPoint[] verticalStripFromCategoryName4 = this._helper.GetVerticalStripFromCategoryName(ref num2, snapPoints3, "InfoOn");
            UILinkPoint[] verticalStripFromCategoryName5 = this._helper.GetVerticalStripFromCategoryName(ref num2, snapPoints3, "OrderUp");
            UILinkPoint[] verticalStripFromCategoryName6 = this._helper.GetVerticalStripFromCategoryName(ref num2, snapPoints3, "OrderDown");
            UILinkPoint uilinkPoint = null;
            UILinkPoint uilinkPoint2 = null;
            for (int i = 0; i < snapPoints.Count; i++)
            {
                SnapPoint snapPoint = snapPoints[i];
                string name = snapPoint.Name;
                if (!(name == "GoBack"))
                {
                    if (name == "OpenFolder")
                    {
                        uilinkPoint2 = this._helper.MakeLinkPointFromSnapPoint(num2++, snapPoint);
                    }
                }
                else
                {
                    uilinkPoint = this._helper.MakeLinkPointFromSnapPoint(num2++, snapPoint);
                }
            }
            this._helper.LinkVerticalStrips(verticalStripFromCategoryName2, verticalStripFromCategoryName, 0);
            this._helper.LinkVerticalStrips(verticalStripFromCategoryName, verticalStripFromCategoryName3, 0);
            this._helper.LinkVerticalStrips(verticalStripFromCategoryName3, verticalStripFromCategoryName4, 0);
            this._helper.LinkVerticalStrips(verticalStripFromCategoryName4, verticalStripFromCategoryName5, 0);
            this._helper.LinkVerticalStrips(verticalStripFromCategoryName5, verticalStripFromCategoryName6, 0);
            this._helper.LinkVerticalStripBottomSideToSingle(verticalStripFromCategoryName, uilinkPoint);
            this._helper.LinkVerticalStripBottomSideToSingle(verticalStripFromCategoryName2, uilinkPoint);
            this._helper.LinkVerticalStripBottomSideToSingle(verticalStripFromCategoryName5, uilinkPoint2);
            this._helper.LinkVerticalStripBottomSideToSingle(verticalStripFromCategoryName6, uilinkPoint2);
            this._helper.LinkVerticalStripBottomSideToSingle(verticalStripFromCategoryName3, uilinkPoint2);
            this._helper.LinkVerticalStripBottomSideToSingle(verticalStripFromCategoryName4, uilinkPoint2);
            this._helper.PairLeftRight(uilinkPoint, uilinkPoint2);
            this._helper.MoveToVisuallyClosestPoint(num, num2);
        }
References Terraria.GameContent.UI.States.UIResourcePackSelectionMenu._availablePacksList, Terraria.GameContent.UI.States.UIResourcePackSelectionMenu._enabledPacksList, Terraria.GameContent.UI.States.UIResourcePackSelectionMenu._helper, System.Collections.Generic.List< T >.Count, Terraria.GameContent.UI.States.UIGamepadHelper.CullPointsOutOfElementArea(), Terraria.GameContent.UI.Elements.UIList.GetSnapPoints(), Terraria.UI.UIElement.GetSnapPoints(), Terraria.GameContent.UI.States.UIGamepadHelper.GetVerticalStripFromCategoryName(), Terraria.GameContent.UI.States.UIGamepadHelper.LinkVerticalStripBottomSideToSingle(), Terraria.GameContent.UI.States.UIGamepadHelper.LinkVerticalStrips(), Terraria.GameContent.UI.States.UIGamepadHelper.MakeLinkPointFromSnapPoint(), Terraria.GameContent.UI.States.UIGamepadHelper.MoveToVisuallyClosestPoint(), System.name, Terraria.UI.SnapPoint.Name, and Terraria.GameContent.UI.States.UIGamepadHelper.PairLeftRight().
Referenced by Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.Draw().