Terraria Decompiled: FullSerializer.Internal.fsDictionaryConverter.TrySerialize
TrySerialize()
override fsResult FullSerializer.Internal.fsDictionaryConverter.TrySerialize (object instance_, out fsData serialized, Type storageType) inline
Definition at line 109 of file fsDictionaryConverter.cs.
        {
            serialized = fsData.Null;
            fsResult fsResult = fsResult.Success;
            IDictionary dictionary = (IDictionary)instance_;
            Type type;
            Type type2;
            fsDictionaryConverter.GetKeyValueTypes(dictionary.GetType(), out type, out type2);
            IDictionaryEnumerator enumerator = dictionary.GetEnumerator();
            bool flag = true;
            List<fsData> list = new List<fsData>(dictionary.Count);
            List<fsData> list2 = new List<fsData>(dictionary.Count);
            while (enumerator.MoveNext())
            {
                fsData fsData;
                fsResult fsResult2;
                fsResult = (fsResult2 = fsResult + this.Serializer.TrySerialize(type, enumerator.Key, out fsData));
                if (fsResult2.Failed)
                {
                    return fsResult;
                }
                fsData fsData2;
                fsResult = (fsResult2 = fsResult + this.Serializer.TrySerialize(type2, enumerator.Value, out fsData2));
                if (fsResult2.Failed)
                {
                    return fsResult;
                }
                list.Add(fsData);
                list2.Add(fsData2);
                flag &= fsData.IsString;
            }
            if (flag)
            {
                serialized = fsData.CreateDictionary();
                Dictionary<string, fsData> asDictionary = serialized.AsDictionary;
                for (int i = 0; i < list.Count; i++)
                {
                    fsData fsData3 = list[i];
                    fsData fsData4 = list2[i];
                    asDictionary[fsData3.AsString] = fsData4;
                }
            }
            else
            {
                serialized = fsData.CreateList(list.Count);
                List<fsData> asList = serialized.AsList;
                for (int j = 0; j < list.Count; j++)
                {
                    fsData fsData5 = list[j];
                    fsData fsData6 = list2[j];
                    Dictionary<string, fsData> dictionary2 = new Dictionary<string, fsData>();
                    dictionary2["Key"] = fsData5;
                    dictionary2["Value"] = fsData6;
                    asList.Add(new fsData(dictionary2));
                }
            }
            return fsResult;
        }
References System.Collections.Generic.List< T >.Add(), FullSerializer.fsData.AsString, FullSerializer.fsData.CreateDictionary(), FullSerializer.fsData.CreateList(), System.dictionary, FullSerializer.fsResult.Failed, FullSerializer.Internal.fsDictionaryConverter.GetKeyValueTypes(), FullSerializer.fsData.IsString, System.Collections.IDictionaryEnumerator.Key, System.list, System.Collections.IEnumerator.MoveNext(), FullSerializer.fsData.Null, FullSerializer.fsBaseConverter.Serializer, FullSerializer.fsResult.Success, FullSerializer.fsSerializer.TrySerialize(), and System.Collections.IDictionaryEnumerator.Value.