Terraria Decompiled: FullSerializer.Internal.fsDictionaryConverter.GetKeyValueTypes
GetKeyValueTypes()
static void FullSerializer.Internal.fsDictionaryConverter.GetKeyValueTypes (Type dictionaryType, out Type keyStorageType, out Type valueStorageType) inline static private
Definition at line 187 of file fsDictionaryConverter.cs.
        {
            Type @interface = fsReflectionUtility.GetInterface(dictionaryType, typeof(IDictionary));
            if (@interface != null)
            {
                Type[] genericArguments = @interface.GetGenericArguments();
                keyStorageType = genericArguments[0];
                valueStorageType = genericArguments[1];
                return;
            }
            keyStorageType = typeof(object);
            valueStorageType = typeof(object);
        }
References System.Type.GetGenericArguments().
Referenced by FullSerializer.Internal.fsDictionaryConverter.TryDeserialize(), and FullSerializer.Internal.fsDictionaryConverter.TrySerialize().