Terraria Decompiled: Terraria.GameContent.Skies.PartySky.GenerateBalloons
GenerateBalloons()
void Terraria.GameContent.Skies.PartySky.GenerateBalloons (bool onlyMissing) inline private
Definition at line 25 of file PartySky.cs.
        {
            if (!onlyMissing)
            {
                this._balloons = new PartySky.Balloon[Main.maxTilesY / 4];
            }
            for (int i = 0; i < this._balloons.Length; i++)
            {
                if (!onlyMissing || !this._balloons[i].Active)
                {
                    int num = (int)((double)Main.screenPosition.Y * 0.7 - (double)Main.screenHeight);
                    int num2 = (int)((double)num - Main.worldSurface * 16.0);
                    this._balloons[i].Position = new Vector2((float)(this._random.Next(0, Main.maxTilesX) * 16), (float)this._random.Next(num2, num));
                    this.ResetBalloon(i);
                    this._balloons[i].Active = true;
                }
            }
            this._balloonsDrawing = this._balloons.Length;
        }
References Terraria.GameContent.Skies.PartySky._balloons, Terraria.GameContent.Skies.PartySky._random, Terraria.Graphics.Effects.Active, int, Terraria.Main.maxTilesX, Terraria.Utilities.UnifiedRandom.Next(), Terraria.GameContent.Skies.PartySky.ResetBalloon(), Terraria.Main.screenHeight, and Microsoft.Xna.Framework.Graphics.Vector2.
Referenced by Terraria.GameContent.Skies.PartySky.Activate(), and Terraria.GameContent.Skies.PartySky.OnLoad().