Terraria Decompiled: System.Tuple.GetHashCode
GetHashCode() [23/24]
int IStructuralEquatable. System.Tuple< T1, T2, T3, T4, T5, T6, T7, TRest >.GetHashCode (IEqualityComparer comparer) inline private
Definition at line 190 of file Tuple.9.cs.
        {
            ITupleInternal tupleInternal = (ITupleInternal)((object)this.m_Rest);
            if (tupleInternal.Length >= 8)
            {
                return tupleInternal.GetHashCode(comparer);
            }
            switch (8 - tupleInternal.Length)
            {
            case 1:
                return Tuple.CombineHashCodes(comparer.GetHashCode(this.m_Item7), tupleInternal.GetHashCode(comparer));
            case 2:
                return Tuple.CombineHashCodes(comparer.GetHashCode(this.m_Item6), comparer.GetHashCode(this.m_Item7), tupleInternal.GetHashCode(comparer));
            case 3:
                return Tuple.CombineHashCodes(comparer.GetHashCode(this.m_Item5), comparer.GetHashCode(this.m_Item6), comparer.GetHashCode(this.m_Item7), tupleInternal.GetHashCode(comparer));
            case 4:
                return Tuple.CombineHashCodes(comparer.GetHashCode(this.m_Item4), comparer.GetHashCode(this.m_Item5), comparer.GetHashCode(this.m_Item6), comparer.GetHashCode(this.m_Item7), tupleInternal.GetHashCode(comparer));
            case 5:
                return Tuple.CombineHashCodes(comparer.GetHashCode(this.m_Item3), comparer.GetHashCode(this.m_Item4), comparer.GetHashCode(this.m_Item5), comparer.GetHashCode(this.m_Item6), comparer.GetHashCode(this.m_Item7), tupleInternal.GetHashCode(comparer));
            case 6:
                return Tuple.CombineHashCodes(comparer.GetHashCode(this.m_Item2), comparer.GetHashCode(this.m_Item3), comparer.GetHashCode(this.m_Item4), comparer.GetHashCode(this.m_Item5), comparer.GetHashCode(this.m_Item6), comparer.GetHashCode(this.m_Item7), tupleInternal.GetHashCode(comparer));
            case 7:
                return Tuple.CombineHashCodes(comparer.GetHashCode(this.m_Item1), comparer.GetHashCode(this.m_Item2), comparer.GetHashCode(this.m_Item3), comparer.GetHashCode(this.m_Item4), comparer.GetHashCode(this.m_Item5), comparer.GetHashCode(this.m_Item6), comparer.GetHashCode(this.m_Item7), tupleInternal.GetHashCode(comparer));
            default:
                return -1;
            }
        }
References System.Tuple< T1, T2, T3, T4, T5, T6, T7, TRest >.CombineHashCodes(), System.comparer, System.ITupleInternal.GetHashCode(), System.Collections.Generic.IEqualityComparer< in T >.GetHashCode(), System.Runtime.CompilerServices.ITuple.Length, System.Tuple< T1, T2, T3, T4, T5, T6, T7, TRest >.m_Item2, System.Tuple< T1, T2, T3, T4, T5, T6, T7, TRest >.m_Item3, System.Tuple< T1, T2, T3, T4, T5, T6, T7, TRest >.m_Item4, System.Tuple< T1, T2, T3, T4, T5, T6, T7, TRest >.m_Item5, System.Tuple< T1, T2, T3, T4, T5, T6, T7, TRest >.m_Item6, System.Tuple< T1, T2, T3, T4, T5, T6, T7, TRest >.m_Item7, and System.Tuple< T1, T2, T3, T4, T5, T6, T7, TRest >.m_Rest.