Terraria Decompiled: Terraria.WorldGen.Skyblock.ScanTiles
ScanTiles()
static void Terraria.WorldGen.Skyblock.ScanTiles () inline static
Definition at line 91622 of file WorldGen.cs.
            {
                WorldGen.Skyblock.currentActiveTiles = 0;
                for (int i = 0; i < (int)TileID.Count; i++)
                {
                    WorldGen.Skyblock.hasTile[i] = false;
                }
                for (int j = 0; j < (int)WallID.Count; j++)
                {
                    WorldGen.Skyblock.hasWall[j] = false;
                }
                int num = 40;
                int num2 = Main.maxTilesX - 40;
                int num3 = 40;
                int num4 = Main.maxTilesY - 40;
                for (int k = num; k < num2; k++)
                {
                    for (int l = num3; l < num4; l++)
                    {
                        if (Main.tile[k, l].active())
{
                            WorldGen.Skyblock.currentActiveTiles++;
                            WorldGen.Skyblock.hasTile[(int)Main.tile[k, l].type] = true;
                        }
                        WorldGen.Skyblock.hasWall[(int)Main.tile[k, l].wall] = true;
                    }
                }
                WorldGen.Skyblock.Calculate();
            }
References Terraria.Tile.active(), Terraria.WorldGen.Skyblock.Calculate(), Terraria.ID.TileID.Count, Terraria.ID.WallID.Count, Terraria.WorldGen.Skyblock.currentActiveTiles, Terraria.WorldGen.Skyblock.hasTile, Terraria.WorldGen.Skyblock.hasWall, int, Terraria.Main.tile, Terraria.Tile.type, and Terraria.Tile.wall.
Referenced by Terraria.IO.WorldFile.LoadWorld().