Terraria Decompiled: Terraria.WorldGen.Skyblock.Calculate
Calculate()
static void Terraria.WorldGen.Skyblock.Calculate () inline static
Definition at line 91532 of file WorldGen.cs.
            {
                WorldGen.Skyblock.noAltars = true;
                WorldGen.Skyblock.noDungeon = true;
                WorldGen.Skyblock.noTemple = true;
                WorldGen.Skyblock.noHellstone = true;
                WorldGen.Skyblock.noFossils = true;
                WorldGen.Skyblock.noLifeCrystals = true;
                WorldGen.Skyblock.noHellforge = true;
                for (int i = 0; i < (int)TileID.Count; i++)
                {
                    if (WorldGen.Skyblock.hasTile[i])
                    {
                        if (Main.tileDungeon[i])
{
                            WorldGen.Skyblock.noDungeon = false;
                        }
                        if (i == 26)
{
                            WorldGen.Skyblock.noAltars = false;
                        }
                        if (i == 226)
{
                            WorldGen.Skyblock.noTemple = false;
                        }
                        if (i == 58)
{
                            WorldGen.Skyblock.noHellstone = false;
                        }
                        if (i == 404)
{
                            WorldGen.Skyblock.noFossils = false;
                        }
                        if (i == 12)
{
                            WorldGen.Skyblock.noLifeCrystals = false;
                        }
                        if (i == 77)
{
                            WorldGen.Skyblock.noHellforge = false;
                        }
                        if (i == 133)
{
                            WorldGen.Skyblock.noHellforge = false;
                        }
                    }
                }
                for (int j = 0; j < (int)WallID.Count; j++)
                {
                    if (WorldGen.Skyblock.hasWall[j])
                    {
                        if (Main.wallDungeon[j])
{
                            WorldGen.Skyblock.noDungeon = false;
                        }
                        if (j == 87)
{
                            WorldGen.Skyblock.noTemple = false;
                        }
                    }
                }
                int num = Main.maxTilesX * Main.maxTilesY;
                float num2 = (float)WorldGen.Skyblock.currentActiveTiles / (float)num;
                WorldGen.Skyblock.currentActiveTiles = 0;
                bool flag = WorldGen.Skyblock.lowTiles;
                WorldGen.Skyblock.lowTiles = false;
                if (num2 < 0.1f && Main.skyblockWorld)
                {
                    WorldGen.Skyblock.lowTiles = true;
                }
                for (int k = 0; k < (int)TileID.Count; k++)
                {
                    WorldGen.Skyblock.hasTile[k] = false;
                }
                for (int l = 0; l < (int)WallID.Count; l++)
                {
                    WorldGen.Skyblock.hasWall[l] = false;
                }
                if (WorldGen.Skyblock.noDungeon)
                {
                    Main.dungeonX = -1;
                    Main.dungeonY = -1;
                }
                if (WorldGen.Skyblock.lowTiles != flag)
                {
                    NetMessage.SendData(7, -1, -1, null, 0, 0f, 0f, 0f, 0, 0, 0);
                }
            }
References Terraria.ID.TileID.Count, Terraria.ID.WallID.Count, Terraria.WorldGen.Skyblock.currentActiveTiles, Terraria.WorldGen.Skyblock.hasTile, Terraria.WorldGen.Skyblock.hasWall, int, Terraria.WorldGen.Skyblock.lowTiles, Terraria.Main.maxTilesY, Terraria.WorldGen.Skyblock.noDungeon, Terraria.NetMessage.SendData(), Terraria.Main.skyblockWorld, Terraria.Main.tileDungeon, and Terraria.Main.wallDungeon.
Referenced by Terraria.WorldGen.CountTiles(), and Terraria.WorldGen.Skyblock.ScanTiles().