Terraria Decompiled: System.Security.SecurityDocument.ConvertElement
ConvertElement()
void System.Security.SecurityDocument.ConvertElement (SecurityElement elCurrent, ref int position) inline
Definition at line 147 of file SecurityDocument.cs.
        {
            this.AddToken(1, ref position);
            this.AddString(elCurrent.m_strTag, ref position);
            if (elCurrent.m_lAttributes != null)
            {
                for (int i = 0; i < elCurrent.m_lAttributes.Count; i += 2)
                {
                    this.AddToken(2, ref position);
                    this.AddString((string)elCurrent.m_lAttributes[i], ref position);
                    this.AddString((string)elCurrent.m_lAttributes[i + 1], ref position);
                }
            }
            if (elCurrent.m_strText != null)
            {
                this.AddToken(3, ref position);
                this.AddString(elCurrent.m_strText, ref position);
            }
            if (elCurrent.InternalChildren != null)
            {
                for (int j = 0; j < elCurrent.InternalChildren.Count; j++)
                {
                    this.ConvertElement((SecurityElement)elCurrent.Children[j], ref position);
                }
            }
            this.AddToken(4, ref position);
        }
References System.Security.SecurityDocument.AddString(), System.Security.SecurityDocument.AddToken(), System.Security.SecurityElement.Children, System.Security.SecurityDocument.ConvertElement(), System.Collections.ArrayList.Count, System.Security.SecurityElement.InternalChildren, System.Security.SecurityElement.m_lAttributes, System.Security.SecurityElement.m_strTag, and System.Security.SecurityElement.m_strText.
Referenced by System.Security.SecurityDocument.ConvertElement(), and System.Security.SecurityDocument.SecurityDocument().