Terraria Decompiled: System.Security.SecurityDocument.InternalGetElement
InternalGetElement()
SecurityElement System.Security.SecurityDocument.InternalGetElement (ref int position, bool bCreate) inline package
Definition at line 188 of file SecurityDocument.cs.
        {
            if (this.m_data.Length <= position)
            {
                throw new XmlSyntaxException();
            }
            byte[] data = this.m_data;
            int num = position;
            position = num + 1;
            if (data[num] != 1)
            {
                throw new XmlSyntaxException();
            }
            SecurityElement securityElement = null;
            string @string = this.GetString(ref position, bCreate);
            if (bCreate)
            {
                securityElement = new SecurityElement(@string);
            }
            while (this.m_data[position] == 2)
            {
                position++;
                string string2 = this.GetString(ref position, bCreate);
                string string3 = this.GetString(ref position, bCreate);
                if (bCreate)
                {
                    securityElement.AddAttribute(string2, string3);
                }
            }
            if (this.m_data[position] == 3)
            {
                position++;
                string string4 = this.GetString(ref position, bCreate);
                if (bCreate)
                {
                    securityElement.m_strText = string4;
                }
            }
            while (this.m_data[position] != 4)
            {
                SecurityElement securityElement2 = this.InternalGetElement(ref position, bCreate);
                if (bCreate)
                {
                    securityElement.AddChild(securityElement2);
                }
            }
            position++;
            return securityElement;
        }
References System.Security.SecurityElement.AddAttribute(), System.Security.SecurityElement.AddChild(), System.Security.SecurityDocument.GetString(), System.Security.SecurityDocument.InternalGetElement(), and System.Security.SecurityDocument.m_data.
Referenced by System.Security.SecurityDocument.GetChildrenPositionForElement(), System.Security.SecurityDocument.GetElement(), and System.Security.SecurityDocument.InternalGetElement().