Terraria Decompiled: System.Security.SecurityDocument.GetString
GetString() [2/2]
string System.Security.SecurityDocument.GetString (ref int position, bool bCreate) inline
Definition at line 81 of file SecurityDocument.cs.
        {
            int num = position;
            while (num < this.m_data.Length - 1 && (this.m_data[num] != 0 || this.m_data[num + 1] != 0))
            {
                num += 2;
            }
            Tokenizer.StringMaker sharedStringMaker = SharedStatics.GetSharedStringMaker();
            string text;
            try
            {
                if (bCreate)
                {
                    sharedStringMaker._outStringBuilder = null;
                    sharedStringMaker._outIndex = 0;
                    for (int i = position; i < num; i += 2)
                    {
                        char c = (char)(((int)this.m_data[i] << 8) | (int)this.m_data[i + 1]);
                        if (sharedStringMaker._outIndex < 512)
{
                            char[] outChars = sharedStringMaker._outChars;
                            Tokenizer.StringMaker stringMaker = sharedStringMaker;
                            int outIndex = stringMaker._outIndex;
                            stringMaker._outIndex = outIndex + 1;
                            outChars[outIndex] = c;
                        }
                        else
{
                            if (sharedStringMaker._outStringBuilder == null)
{
                                sharedStringMaker._outStringBuilder = new StringBuilder();
                            }
                            sharedStringMaker._outStringBuilder.Append(sharedStringMaker._outChars, 0, 512);
                            sharedStringMaker._outChars[0] = c;
                            sharedStringMaker._outIndex = 1;
                        }
                    }
                }
                position = num + 2;
                if (bCreate)
                {
                    text = sharedStringMaker.MakeString();
                }
                else
                {
                    text = null;
                }
            }
            finally
            {
                SharedStatics.ReleaseSharedStringMaker(ref sharedStringMaker);
            }
            return text;
        }
References System.Security.Util.Tokenizer.StringMaker._outChars, System.Security.Util.Tokenizer.StringMaker._outIndex, System.Security.Util.Tokenizer.StringMaker._outStringBuilder, System.Text.StringBuilder.Append(), System.SharedStatics.GetSharedStringMaker(), int, System.Security.SecurityDocument.m_data, System.Security.Util.Tokenizer.StringMaker.MakeString(), System.SharedStatics.ReleaseSharedStringMaker(), and System.text.