Terraria Decompiled: System.Security.SecurityDocument.AddString
AddString()
void System.Security.SecurityDocument.AddString (string str, ref int position) inline
Definition at line 44 of file SecurityDocument.cs.
        {
            this.GuaranteeSize(position + str.Length * 2 + 2);
            for (int i = 0; i < str.Length; i++)
            {
                this.m_data[position + 2 * i] = (byte)(str[i] >> 8);
                this.m_data[position + 2 * i + 1] = (byte)(str[i] & 'ÿ');
            }
            this.m_data[position + str.Length * 2] = 0;
            this.m_data[position + str.Length * 2 + 1] = 0;
            position += str.Length * 2 + 2;
        }
References System.Security.SecurityDocument.GuaranteeSize(), and System.Security.SecurityDocument.m_data.
Referenced by System.Security.SecurityDocument.AppendString(), System.Security.SecurityDocument.ConvertElement(), and System.Security.Util.Parser.ParseContents().