Terraria Decompiled: System.Security.SecurityDocument.GetChildrenPositionForElement
GetChildrenPositionForElement()
ArrayList System.Security.SecurityDocument.GetChildrenPositionForElement (int position) inline
Definition at line 253 of file SecurityDocument.cs.
        {
            if (this.m_data.Length <= position)
            {
                throw new XmlSyntaxException();
            }
            if (this.m_data[position++] != 1)
            {
                throw new XmlSyntaxException();
            }
            ArrayList arrayList = new ArrayList();
            this.GetString(ref position);
            while (this.m_data[position] == 2)
            {
                position++;
                this.GetString(ref position, false);
                this.GetString(ref position, false);
            }
            if (this.m_data[position] == 3)
            {
                position++;
                this.GetString(ref position, false);
            }
            while (this.m_data[position] != 4)
            {
                arrayList.Add(position);
                this.InternalGetElement(ref position, false);
            }
            position++;
            return arrayList;
        }
References System.Collections.ArrayList.Add(), System.Security.SecurityDocument.GetString(), System.Security.SecurityDocument.InternalGetElement(), and System.Security.SecurityDocument.m_data.