Terraria Decompiled: Microsoft.Xna.Framework.Graphics.RenderTargetCube.RenderTargetCube
RenderTargetCube() [2/2]
Microsoft.Xna.Framework.Graphics.RenderTargetCube.RenderTargetCube (GraphicsDevice graphicsDevice, int size, bool mipMap, SurfaceFormat preferredFormat, DepthFormat preferredDepthFormat, int preferredMultiSampleCount, RenderTargetUsage usage) inline
Definition at line 151 of file RenderTargetCube.cs.
            : base(graphicsDevice, size, mipMap, preferredFormat)
        {
            this.DepthStencilFormat = preferredDepthFormat;
            this.MultiSampleCount = FNA3D.FNA3D_GetMaxMultiSampleCount(graphicsDevice.GLDevice, base.Format, MathHelper.ClosestMSAAPower(preferredMultiSampleCount));
            this.RenderTargetUsage = usage;
            if (this.MultiSampleCount > 0)
            {
                this.glColorBuffer = FNA3D.FNA3D_GenColorRenderbuffer(graphicsDevice.GLDevice, base.Size, base.Size, base.Format, this.MultiSampleCount, this.texture);
            }
            if (this.DepthStencilFormat == DepthFormat.None)
            {
                return;
            }
            this.glDepthStencilBuffer = FNA3D.FNA3D_GenDepthStencilRenderbuffer(graphicsDevice.GLDevice, base.Size, base.Size, this.DepthStencilFormat, this.MultiSampleCount);
        }
References Microsoft.Xna.Framework.MathHelper.ClosestMSAAPower(), Microsoft.Xna.Framework.Graphics.RenderTargetCube.DepthStencilFormat, Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_GenColorRenderbuffer(), Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_GenDepthStencilRenderbuffer(), Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_GetMaxMultiSampleCount(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.GLDevice, Microsoft.Xna.Framework.Graphics.GraphicsResource.graphicsDevice, Microsoft.Xna.Framework.Graphics.RenderTargetCube.MultiSampleCount, and System.IntPtr.Size.