Terraria Decompiled: Newtonsoft.Json.Schema.JsonSchemaGenerator.GenerateObjectSchema
GenerateObjectSchema()
void Newtonsoft.Json.Schema.JsonSchemaGenerator.GenerateObjectSchema (Type type, JsonObjectContract contract) inline private
Definition at line 302 of file JsonSchemaGenerator.cs.
        {
            this.CurrentSchema.Properties = new Dictionary<string, JsonSchema>();
            foreach (JsonProperty jsonProperty in contract.Properties)
            {
                if (!jsonProperty.Ignored)
                {
                    bool flag = jsonProperty.NullValueHandling == NullValueHandling.Ignore || this.HasFlag(jsonProperty.DefaultValueHandling.GetValueOrDefault(), DefaultValueHandling.Ignore) || jsonProperty.ShouldSerialize != null || jsonProperty.GetIsSpecified != null;
                    JsonSchema jsonSchema = this.GenerateInternal(jsonProperty.PropertyType, jsonProperty.Required, !flag);
                    if (jsonProperty.DefaultValue != null)
                    {
                        jsonSchema.Default = JToken.FromObject(jsonProperty.DefaultValue);
                    }
                    this.CurrentSchema.Properties.Add(jsonProperty.PropertyName, jsonSchema);
                }
            }
            if (type.IsSealed())
            {
                this.CurrentSchema.AllowAdditionalProperties = false;
            }
        }
References Newtonsoft.Json.Schema.JsonSchemaGenerator.CurrentSchema, Newtonsoft.Json.Serialization.JsonProperty.DefaultValue, Newtonsoft.Json.Serialization.JsonProperty.DefaultValueHandling, Newtonsoft.Json.Linq.JToken.FromObject(), Newtonsoft.Json.Schema.JsonSchemaGenerator.GenerateInternal(), Newtonsoft.Json.Schema.JsonSchemaGenerator.HasFlag(), Newtonsoft.Json.Serialization.JsonProperty.Ignored, Newtonsoft.Json.Schema.JsonSchema.Properties, Newtonsoft.Json.Serialization.JsonProperty.PropertyName, Newtonsoft.Json.Serialization.JsonProperty.PropertyType, and Newtonsoft.Json.Serialization.JsonProperty.Required.
Referenced by Newtonsoft.Json.Schema.JsonSchemaGenerator.GenerateInternal().