Terraria Decompiled: Newtonsoft.Json.Schema.JsonSchemaGenerator.GenerateInternal
GenerateInternal()
JsonSchema Newtonsoft.Json.Schema.JsonSchemaGenerator.GenerateInternal (Type type, Required valueRequired, bool required) inline private
Definition at line 165 of file JsonSchemaGenerator.cs.
        {
            ValidationUtils.ArgumentNotNull(type, "type");
            string typeId = this.GetTypeId(type, false);
            string typeId2 = this.GetTypeId(type, true);
            if (!string.IsNullOrEmpty(typeId))
            {
                JsonSchema schema = this._resolver.GetSchema(typeId);
                if (schema != null)
                {
                    if (valueRequired != Required.Always && !JsonSchemaGenerator.HasFlag(schema.Type, JsonSchemaType.Null))
                    {
                        schema.Type |= JsonSchemaType.Null;
                    }
                    if (required && schema.Required != true)
                    {
                        schema.Required = new bool?(true);
                    }
                    return schema;
                }
            }
            if (Enumerable.Any<JsonSchemaGenerator.TypeSchema>(this._stack, (JsonSchemaGenerator.TypeSchema tc) => tc.Type == type))
            {
                throw new JsonException("Unresolved circular reference for type '{0}'. Explicitly define an Id for the type using a JsonObject/JsonArray attribute or automatically generate a type Id using the UndefinedSchemaIdHandling property.".FormatWith(CultureInfo.InvariantCulture, type));
            }
            JsonContract jsonContract = this.ContractResolver.ResolveContract(type);
            bool flag = (jsonContract.Converter ?? jsonContract.InternalConverter) != null;
            this.Push(new JsonSchemaGenerator.TypeSchema(type, new JsonSchema()));
            if (typeId2 != null)
            {
                this.CurrentSchema.Id = typeId2;
            }
            if (required)
            {
                this.CurrentSchema.Required = new bool?(true);
            }
            this.CurrentSchema.Title = this.GetTitle(type);
            this.CurrentSchema.Description = this.GetDescription(type);
            if (flag)
            {
                this.CurrentSchema.Type = new JsonSchemaType?(JsonSchemaType.Any);
            }
            else
            {
                switch (jsonContract.ContractType)
                {
                case JsonContractType.Object:
                    this.CurrentSchema.Type = new JsonSchemaType?(this.AddNullType(JsonSchemaType.Object, valueRequired));
                    this.CurrentSchema.Id = this.GetTypeId(type, false);
                    this.GenerateObjectSchema(type, (JsonObjectContract)jsonContract);
                    goto IL_04A9;
                case JsonContractType.Array:
                {
                    this.CurrentSchema.Type = new JsonSchemaType?(this.AddNullType(JsonSchemaType.Array, valueRequired));
                    this.CurrentSchema.Id = this.GetTypeId(type, false);
                    JsonArrayAttribute cachedAttribute = JsonTypeReflector.GetCachedAttribute<JsonArrayAttribute>(type);
                    bool flag2 = cachedAttribute == null || cachedAttribute.AllowNullItems;
                    Type collectionItemType = ReflectionUtils.GetCollectionItemType(type);
                    if (collectionItemType != null)
                    {
                        this.CurrentSchema.Items = new List<JsonSchema>();
                        this.CurrentSchema.Items.Add(this.GenerateInternal(collectionItemType, (!flag2) ? Required.Always : Required.Default, false));
                        goto IL_04A9;
                    }
                    goto IL_04A9;
                }
                case JsonContractType.Primitive:
                {
                    this.CurrentSchema.Type = new JsonSchemaType?(this.GetJsonSchemaType(type, valueRequired));
                    if (!(this.CurrentSchema.Type == JsonSchemaType.Integer) || !type.IsEnum() || type.IsDefined(typeof(FlagsAttribute), true))
                    {
                        goto IL_04A9;
                    }
                    this.CurrentSchema.Enum = new List<JToken>();
                    using (IEnumerator<EnumValue<long>> enumerator = EnumUtils.GetNamesAndValues<long>(type).GetEnumerator())
                    {
                        while (enumerator.MoveNext())
{
                            EnumValue<long> enumValue = enumerator.Current;
                            JToken jtoken = JToken.FromObject(enumValue.Value);
                            this.CurrentSchema.Enum.Add(jtoken);
                        }
                        goto IL_04A9;
                    }
                    break;
                }
                case JsonContractType.String:
                    break;
                case JsonContractType.Dictionary:
                {
                    this.CurrentSchema.Type = new JsonSchemaType?(this.AddNullType(JsonSchemaType.Object, valueRequired));
                    Type type2;
                    Type type3;
                    ReflectionUtils.GetDictionaryKeyValueTypes(type, out type2, out type3);
                    if (type2 != null && this.ContractResolver.ResolveContract(type2).ContractType == JsonContractType.Primitive)
                    {
                        this.CurrentSchema.AdditionalProperties = this.GenerateInternal(type3, Required.Default, false);
                        goto IL_04A9;
                    }
                    goto IL_04A9;
                }
                case JsonContractType.Dynamic:
                case JsonContractType.Linq:
                    this.CurrentSchema.Type = new JsonSchemaType?(JsonSchemaType.Any);
                    goto IL_04A9;
                case JsonContractType.Serializable:
                    this.CurrentSchema.Type = new JsonSchemaType?(this.AddNullType(JsonSchemaType.Object, valueRequired));
                    this.CurrentSchema.Id = this.GetTypeId(type, false);
                    this.GenerateISerializableContract(type, (JsonISerializableContract)jsonContract);
                    goto IL_04A9;
                default:
                    throw new JsonException("Unexpected contract type: {0}".FormatWith(CultureInfo.InvariantCulture, jsonContract));
                }
                JsonSchemaType jsonSchemaType = ((!ReflectionUtils.IsNullable(jsonContract.UnderlyingType)) ? JsonSchemaType.String : this.AddNullType(JsonSchemaType.String, valueRequired));
                this.CurrentSchema.Type = new JsonSchemaType?(jsonSchemaType);
            }
            IL_04A9:
            return this.Pop().Schema;
        }
References Newtonsoft.Json.Schema.JsonSchemaGenerator._resolver, Newtonsoft.Json.Schema.JsonSchemaGenerator.AddNullType(), Newtonsoft.Json.JsonArrayAttribute.AllowNullItems, Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(), Newtonsoft.Json.Schema.JsonSchemaGenerator.ContractResolver, Newtonsoft.Json.Serialization.JsonContract.ContractType, System.Collections.Generic.IEnumerator< out T >.Current, Newtonsoft.Json.Schema.JsonSchemaGenerator.CurrentSchema, Newtonsoft.Json.Schema.JsonSchema.Enum, Newtonsoft.Json.Linq.JToken.FromObject(), Newtonsoft.Json.Schema.JsonSchemaGenerator.GenerateInternal(), Newtonsoft.Json.Schema.JsonSchemaGenerator.GenerateISerializableContract(), Newtonsoft.Json.Schema.JsonSchemaGenerator.GenerateObjectSchema(), Newtonsoft.Json.Utilities.ReflectionUtils.GetCollectionItemType(), Newtonsoft.Json.Schema.JsonSchemaGenerator.GetDescription(), Newtonsoft.Json.Utilities.ReflectionUtils.GetDictionaryKeyValueTypes(), Newtonsoft.Json.Schema.JsonSchemaGenerator.GetJsonSchemaType(), Newtonsoft.Json.Schema.JsonSchemaResolver.GetSchema(), Newtonsoft.Json.Schema.JsonSchemaGenerator.GetTitle(), Newtonsoft.Json.Schema.JsonSchemaGenerator.GetTypeId(), Newtonsoft.Json.Schema.JsonSchemaGenerator.HasFlag(), Newtonsoft.Json.Serialization.JsonContract.InternalConverter, System.Globalization.CultureInfo.InvariantCulture, System.Reflection.MemberInfo.IsDefined(), System.Type.IsEnum, Newtonsoft.Json.Utilities.ReflectionUtils.IsNullable(), Newtonsoft.Json.Schema.JsonSchema.Items, System.Collections.IEnumerator.MoveNext(), Newtonsoft.Json.Schema.JsonSchemaGenerator.Pop(), Newtonsoft.Json.Schema.JsonSchemaGenerator.Push(), Newtonsoft.Json.Schema.JsonSchema.Required, Newtonsoft.Json.Serialization.IContractResolver.ResolveContract(), Newtonsoft.Json.Schema.JsonSchema.Type, Newtonsoft.Json.Serialization.JsonContract.UnderlyingType, and Newtonsoft.Json.Utilities.EnumValue< T >.Value.
Referenced by Newtonsoft.Json.Schema.JsonSchemaGenerator.Generate(), Newtonsoft.Json.Schema.JsonSchemaGenerator.GenerateInternal(), and Newtonsoft.Json.Schema.JsonSchemaGenerator.GenerateObjectSchema().