Terraria Decompiled: Newtonsoft.Json.Schema.JsonSchemaGenerator.GetJsonSchemaType
GetJsonSchemaType()
JsonSchemaType Newtonsoft.Json.Schema.JsonSchemaGenerator.GetJsonSchemaType (Type type, Required valueRequired) inline private
Definition at line 337 of file JsonSchemaGenerator.cs.
        {
            JsonSchemaType jsonSchemaType = JsonSchemaType.None;
            if (valueRequired != Required.Always && ReflectionUtils.IsNullable(type))
            {
                jsonSchemaType = JsonSchemaType.Null;
                if (ReflectionUtils.IsNullableType(type))
                {
                    type = Nullable.GetUnderlyingType(type);
                }
            }
            PrimitiveTypeCode typeCode = ConvertUtils.GetTypeCode(type);
            switch (typeCode)
            {
            case PrimitiveTypeCode.Empty:
            case PrimitiveTypeCode.Object:
                return jsonSchemaType | JsonSchemaType.String;
            case PrimitiveTypeCode.Char:
                return jsonSchemaType | JsonSchemaType.String;
            case PrimitiveTypeCode.Boolean:
                return jsonSchemaType | JsonSchemaType.Boolean;
            case PrimitiveTypeCode.SByte:
            case PrimitiveTypeCode.Int16:
            case PrimitiveTypeCode.UInt16:
            case PrimitiveTypeCode.Int32:
            case PrimitiveTypeCode.Byte:
            case PrimitiveTypeCode.UInt32:
            case PrimitiveTypeCode.Int64:
            case PrimitiveTypeCode.UInt64:
            case PrimitiveTypeCode.BigInteger:
                return jsonSchemaType | JsonSchemaType.Integer;
            case PrimitiveTypeCode.Single:
            case PrimitiveTypeCode.Double:
            case PrimitiveTypeCode.Decimal:
                return jsonSchemaType | JsonSchemaType.Float;
            case PrimitiveTypeCode.DateTime:
            case PrimitiveTypeCode.DateTimeOffset:
                return jsonSchemaType | JsonSchemaType.String;
            case PrimitiveTypeCode.Guid:
            case PrimitiveTypeCode.TimeSpan:
            case PrimitiveTypeCode.Uri:
            case PrimitiveTypeCode.String:
            case PrimitiveTypeCode.Bytes:
                return jsonSchemaType | JsonSchemaType.String;
            case PrimitiveTypeCode.DBNull:
                return jsonSchemaType | JsonSchemaType.Null;
            }
            throw new JsonException("Unexpected type code '{0}' for type '{1}'.".FormatWith(CultureInfo.InvariantCulture, typeCode, type));
        }
References Newtonsoft.Json.Utilities.ConvertUtils.GetTypeCode(), System.Nullable< T >.GetUnderlyingType(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.Utilities.ReflectionUtils.IsNullable(), and Newtonsoft.Json.Utilities.ReflectionUtils.IsNullableType().
Referenced by Newtonsoft.Json.Schema.JsonSchemaGenerator.GenerateInternal().