Terraria Decompiled: Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.FillRooms
FillRooms()
void Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.FillRooms () inline private
Definition at line 744 of file HouseBuilder.cs.
        {
            int num = 14;
            if (this.UsesTables2)
            {
                num = 469;
            }
            Point[] array = new Point[]
            {
                new Point(num, this.TableStyle),
                new Point(16, 0),
                new Point(18, this.WorkbenchStyle),
                new Point(86, 0),
                new Point(87, this.PianoStyle),
                new Point(94, 0),
                new Point(101, this.BookcaseStyle)
            };
            foreach (Rectangle rectangle in this.Rooms)
            {
                int num2 = rectangle.Width / 8;
                int num3 = rectangle.Width / (num2 + 1);
                int num4 = this._random.Next(2);
                for (int i = 0; i < num2; i++)
                {
                    int num5 = (i + 1) * num3 + rectangle.X;
                    int num6 = i + num4 % 2;
                    if (num6 != 0)
                    {
                        if (num6 == 1)
{
                            int num7 = rectangle.Y + 1;
                            WorldGen.PlaceTile(num5, num7, 34, true, false, -1, this._random.Next(6));
                            for (int j = -1; j < 2; j++)
{
                                for (int k = 0; k < 3; k++)
{
                                    Tile tile = this._tiles[j + num5, k + num7];
                                    tile.frameX += 54;
                                }
                            }
                        }
                    }
                    else
                    {
                        int num7 = rectangle.Y + Math.Min(rectangle.Height / 2, rectangle.Height - 5);
                        PaintingEntry paintingEntry = ((this.Type == HouseType.Desert) ? WorldGen.RandHousePictureDesert() : WorldGen.RandHousePicture());
                        WorldGen.PlaceTile(num5, num7, paintingEntry.tileType, true, false, -1, paintingEntry.style);
                    }
                }
                int l = rectangle.Width / 8 + 3;
                WorldGen.SetupStatueList();
                while (l > 0)
                {
                    int num8 = this._random.Next(rectangle.Width - 3) + 1 + rectangle.X;
                    int num9 = rectangle.Y + rectangle.Height - 2;
                    switch (this._random.Next(4))
                    {
                    case 0:
                        WorldGen.PlaceSmallPile(num8, num9, this._random.Next(31, 34), 1, 185);
                        break;
                    case 1:
                        WorldGen.PlaceTile(num8, num9, 186, true, false, -1, this._random.Next(22, 26));
                        break;
                    case 2:
                    {
                        int num10 = this._random.Next(2, GenVars.statueList.Length);
                        WorldGen.PlaceTile(num8, num9, (int)GenVars.statueList[num10].X, true, false, -1, (int)GenVars.statueList[num10].Y);
                        if (GenVars.StatuesWithTraps.Contains(num10))
{
                            WorldGen.PlaceStatueTrap(num8, num9);
                        }
                        break;
                    }
                    case 3:
                    {
                        Point point = Utils.SelectRandom<Point>(this._random, array);
                        WorldGen.PlaceTile(num8, num9, point.X, true, false, -1, point.Y);
                        break;
                    }
                    }
                    l--;
                }
            }
        }
References System.array, System.Collections.Generic.List< T >.Contains(), Microsoft.Xna.Framework.Rectangle.Height, int, System.Math.Min(), Terraria.WorldGen.PlaceSmallPile(), Terraria.WorldGen.PlaceStatueTrap(), Terraria.WorldGen.PlaceTile(), Terraria.WorldGen.RandHousePicture(), Terraria.WorldGen.RandHousePictureDesert(), Terraria.WorldGen.SetupStatueList(), Terraria.WorldBuilding.GenVars.statueList, Terraria.WorldBuilding.GenVars.StatuesWithTraps, Terraria.GameContent.Generation.PaintingEntry.style, Terraria.GameContent.Generation.PaintingEntry.tileType, Microsoft.Xna.Framework.Rectangle.Width, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Rectangle.X, and Microsoft.Xna.Framework.Point.Y.