Terraria Decompiled: Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PlaceStairs
PlaceStairs()
void Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PlaceStairs () inline private
Definition at line 830 of file HouseBuilder.cs.
        {
            foreach (Tuple<Point, Point> tuple in this.CreateStairsList())
            {
                Point item = tuple.Item1;
                Point item2 = tuple.Item2;
                int num = ((item2.X > item.X) ? 1 : (-1));
                ShapeData shapeData = new ShapeData();
                for (int i = 0; i < item2.Y - item.Y; i++)
                {
                    shapeData.Add(num * (i + 1), i);
                }
                WorldUtils.Gen(item, new ModShapes.All(shapeData), Actions.Chain(new GenAction[]
                {
                    new Actions.PlaceTile(19, this.PlatformStyle),
                    new Actions.SetSlope((num == 1) ? 1 : 2),
                    new Actions.SetFrames(true)
                }));
                WorldUtils.Gen(new Point(item.X + ((num == 1) ? 1 : (-4)), item.Y - 1), new Shapes.Rectangle(4, 1), Actions.Chain(new GenAction[]
                {
                    new Actions.Clear(),
                    new Actions.PlaceWall(this.WallType, true),
                    new Actions.PlaceTile(19, this.PlatformStyle),
                    new Actions.SetFrames(true)
                }));
            }
        }
References Terraria.WorldBuilding.ShapeData.Add(), Terraria.WorldBuilding.Actions.Chain(), Terraria.WorldBuilding.WorldUtils.Gen(), System.item, System.Tuple< T1, T2, T3, T4, T5, T6, T7, TRest >.Item1, and System.Tuple< T1, T2, T3, T4, T5, T6, T7, TRest >.Item2.