Terraria Decompiled: Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.FindSideExit
FindSideExit()
static bool Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.FindSideExit (Rectangle wall, bool isLeft, out int exitY) inline static private
Definition at line 1021 of file HouseBuilder.cs.
        {
            Point point;
            bool flag = WorldUtils.Find(new Point(wall.X + (isLeft ? (-4) : 0), wall.Y + wall.Height - 3), Searches.Chain(new Searches.Up(wall.Height - 3), new GenCondition[] { new Conditions.IsSolid().Not().AreaOr(4, 3) }), out point);
            exitY = point.Y;
            return flag;
        }
References Terraria.WorldBuilding.GenCondition.AreaOr(), Terraria.WorldBuilding.Searches.Chain(), Terraria.WorldBuilding.WorldUtils.Find(), Microsoft.Xna.Framework.Rectangle.Height, Terraria.WorldBuilding.GenCondition.Not(), Microsoft.Xna.Framework.Rectangle.X, Microsoft.Xna.Framework.Point.Y, and Microsoft.Xna.Framework.Rectangle.Y.
Referenced by Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.CreateDoorList().