Terraria Decompiled: Terraria.GameContent.Biomes.DunesBiome.Place
Place()
override bool Terraria.GameContent.Biomes.DunesBiome.Place (Point origin, StructureMap structures, GenerationProgress progress) inline
Definition at line 25 of file DunesBiome.cs.
        {
            int num = (int)((double)GenBase._random.Next(60, 100) * this._heightScale);
            int num2 = (int)((double)GenBase._random.Next(60, 100) * this._heightScale);
            int random = this._singleDunesWidth.GetRandom(GenBase._random);
            int random2 = this._singleDunesWidth.GetRandom(GenBase._random);
            DunesBiome.DunesDescription dunesDescription = DunesBiome.DunesDescription.CreateFromPlacement(new Point(origin.X - random / 2 + 30, origin.Y), random, num);
            DunesBiome.DunesDescription dunesDescription2 = DunesBiome.DunesDescription.CreateFromPlacement(new Point(origin.X + random2 / 2 - 30, origin.Y), random2, num2);
            this.PlaceSingle(dunesDescription, structures);
            this.PlaceSingle(dunesDescription2, structures);
            return true;
        }
References Terraria.GameContent.Biomes.DunesBiome._heightScale, Terraria.WorldBuilding.GenBase._random, Terraria.GameContent.Biomes.DunesBiome._singleDunesWidth, Terraria.GameContent.Biomes.DunesBiome.DunesDescription.CreateFromPlacement(), Terraria.WorldBuilding.WorldGenRange.GetRandom(), int, Terraria.GameContent.Biomes.DunesBiome.PlaceSingle(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.WorldGen.AddPasses().