Terraria Decompiled: Terraria.GameContent.Biomes.DunesBiome.PlaceCurvedLine
PlaceCurvedLine()
static void Terraria.GameContent.Biomes.DunesBiome.PlaceCurvedLine (Point startPoint, Point endPoint, Point anchorOffset, DunesBiome::DunesDescription description) inline static private
Definition at line 85 of file DunesBiome.cs.
        {
            Point point = new Point((startPoint.X + endPoint.X) / 2, (startPoint.Y + endPoint.Y) / 2);
            point.X += anchorOffset.X;
            point.Y += anchorOffset.Y;
            Vector2D vector2D = startPoint.ToVector2D();
            Vector2D vector2D2 = endPoint.ToVector2D();
            Vector2D vector2D3 = point.ToVector2D();
            double num = 0.5 / (vector2D2.X - vector2D.X);
            Point point2 = new Point(-1, -1);
            for (double num2 = 0.0; num2 <= 1.0; num2 += num)
            {
                Vector2D vector2D4 = Vector2D.Lerp(vector2D, vector2D3, num2);
                Vector2D vector2D5 = Vector2D.Lerp(vector2D3, vector2D2, num2);
                Point point3 = Vector2D.Lerp(vector2D4, vector2D5, num2).ToPoint();
                if (!(point3 == point2))
                {
                    point2 = point3;
                    int num3 = description.Area.Width / 2 - Math.Abs(point3.X - description.Area.Center.X);
                    int num4 = (int)description.Surface[point3.X] + (int)(Math.Sqrt((double)num3) * 3.0);
                    for (int i = point3.Y - 10; i < point3.Y; i++)
                    {
                        if (GenBase._tiles[point3.X, i].active() && GenBase._tiles[point3.X, i].type != 53)
{
                            GenBase._tiles[point3.X, i].ClearEverything();
                        }
                    }
                    for (int j = point3.Y; j < num4; j++)
                    {
                        GenBase._tiles[point3.X, j].ResetToType(53);
                    }
                }
            }
        }
References Terraria.WorldBuilding.GenBase._tiles, System.Math.Abs(), Terraria.Tile.active(), Terraria.Tile.ClearEverything(), int, ReLogic.Utilities.Vector2D.Lerp(), Terraria.Tile.ResetToType(), System.Math.Sqrt(), Terraria.Tile.type, Microsoft.Xna.Framework.Point.X, ReLogic.Utilities.Vector2D.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.Biomes.DunesBiome.PlaceHill().