Terraria Decompiled: System.AppDomainManager.CreateDomain
CreateDomain()
virtual AppDomain System.AppDomainManager.CreateDomain (string friendlyName, Evidence securityInfo, AppDomainSetup appDomainInfo) inline virtual
Definition at line 85 of file AppDomainManager.cs.
        {
            this.InitializeNewDomain(appDomainInfo);
            AppDomain appDomain = AppDomainManager.CreateDomainHelper(friendlyName, securityInfo, appDomainInfo);
            if ((this.HostSecurityManager.Flags & HostSecurityManagerOptions.HostPolicyLevel) == HostSecurityManagerOptions.HostPolicyLevel)
            {
                PolicyLevel domainPolicy = this.HostSecurityManager.DomainPolicy;
                if (domainPolicy != null)
                {
                    appDomain.SetAppDomainPolicy(domainPolicy);
                }
            }
            return appDomain;
        }
References System.AppDomainManager.CreateDomainHelper(), System.Security.HostSecurityManager.DomainPolicy, System.Security.HostSecurityManager.Flags, System.AppDomainManager.InitializeNewDomain(), and System.AppDomain.SetAppDomainPolicy().