Terraria Decompiled: NVorbis.Codebook.lookup1_values
lookup1_values()
int NVorbis.Codebook.lookup1_values () inline private
Definition at line 238 of file Codebook.cs.
        {
            int num = (int)Math.Floor(Math.Exp(Math.Log((double)this.Entries) / (double)this.Dimensions));
            if (Math.Floor(Math.Pow((double)(num + 1), (double)this.Dimensions)) <= (double)this.Entries)
            {
                num++;
            }
            return num;
        }
References NVorbis.Codebook.Entries, System.Math.Exp(), System.Math.Floor(), int, System.Math.Log(), and System.Math.Pow().
Referenced by NVorbis.Codebook.InitLookupTable().