Terraria Decompiled: NVorbis.Codebook.InitTree
InitTree()
void NVorbis.Codebook.InitTree (IPacket packet, IHuffman huffman) inline private
Definition at line 28 of file Codebook.cs.
        {
            int num = 0;
            bool flag;
            int num4;
            if (packet.ReadBit())
            {
                int num2 = (int)packet.ReadBits(5) + 1;
                int i = 0;
                while (i < this.Entries)
                {
                    int num3 = (int)packet.ReadBits(Utils.ilog(this.Entries - i));
                    while (--num3 >= 0)
                    {
                        this._lengths[i++] = num2;
                    }
                    num2++;
                }
                num = 0;
                flag = false;
                num4 = num2;
            }
            else
            {
                num4 = -1;
                flag = packet.ReadBit();
                for (int j = 0; j < this.Entries; j++)
                {
                    if (!flag || packet.ReadBit())
                    {
                        this._lengths[j] = (int)packet.ReadBits(5) + 1;
                        num++;
                    }
                    else
                    {
                        this._lengths[j] = -1;
                    }
                    if (this._lengths[j] > num4)
                    {
                        num4 = this._lengths[j];
                    }
                }
            }
            if ((this._maxBits = num4) > -1)
            {
                int[] array = null;
                if (flag && num >= this.Entries >> 2)
                {
                    array = new int[this.Entries];
                    Array.Copy(this._lengths, array, this.Entries);
                    flag = false;
                }
                int num5;
                if (flag)
                {
                    num5 = num;
                }
                else
                {
                    num5 = 0;
                }
                int[] array2 = null;
                int[] array3 = null;
                if (!flag)
                {
                    array3 = new int[this.Entries];
                }
                else if (num5 != 0)
                {
                    array = new int[num5];
                    array3 = new int[num5];
                    array2 = new int[num5];
                }
                if (!this.ComputeCodewords(flag, array3, array, this._lengths, this.Entries, array2))
                {
                    throw new InvalidDataException();
                }
                IList<int> list = array2;
                IList<int> list2 = list ?? Codebook.FastRange.Get(0, array3.Length);
                huffman.GenerateTable(list2, array ?? this._lengths, array3);
                this._prefixList = huffman.PrefixTree;
                this._prefixBitLength = huffman.TableBits;
                this._overflowList = huffman.OverflowList;
            }
        }
References NVorbis.Codebook._lengths, NVorbis.Codebook._maxBits, System.array, NVorbis.Codebook.ComputeCodewords(), System.Array.Copy(), NVorbis.Codebook.Entries, NVorbis.Contracts.IHuffman.GenerateTable(), NVorbis.Codebook.FastRange.Get(), NVorbis.Utils.ilog(), int, System.list, NVorbis.Contracts.IHuffman.OverflowList, NVorbis.Contracts.IHuffman.PrefixTree, NVorbis.Contracts.IPacket.ReadBits(), and NVorbis.Contracts.IHuffman.TableBits.
Referenced by NVorbis.Codebook.Init().