Terraria Decompiled: NVorbis.Codebook.InitLookupTable
InitLookupTable()
void NVorbis.Codebook.InitLookupTable (IPacket packet) inline private
Definition at line 175 of file Codebook.cs.
        {
            this.MapType = (int)packet.ReadBits(4);
            if (this.MapType == 0)
            {
                return;
            }
            float num = Utils.ConvertFromVorbisFloat32((uint)packet.ReadBits(32));
            float num2 = Utils.ConvertFromVorbisFloat32((uint)packet.ReadBits(32));
            int num3 = (int)packet.ReadBits(4) + 1;
            bool flag = packet.ReadBit();
            int num4 = this.Entries * this.Dimensions;
            float[] array = new float[num4];
            if (this.MapType == 1)
            {
                num4 = this.lookup1_values();
            }
            uint[] array2 = new uint[num4];
            for (int i = 0; i < num4; i++)
            {
                array2[i] = (uint)packet.ReadBits(num3);
            }
            if (this.MapType == 1)
            {
                for (int j = 0; j < this.Entries; j++)
                {
                    double num5 = 0.0;
                    int num6 = 1;
                    for (int k = 0; k < this.Dimensions; k++)
                    {
                        int num7 = j / num6 % num4;
                        double num8 = (double)(array2[num7] * num2 + num) + num5;
                        array[j * this.Dimensions + k] = (float)num8;
                        if (flag)
{
                            num5 = num8;
                        }
                        num6 *= num4;
                    }
                }
            }
            else
            {
                for (int l = 0; l < this.Entries; l++)
                {
                    double num9 = 0.0;
                    int num10 = l * this.Dimensions;
                    for (int m = 0; m < this.Dimensions; m++)
                    {
                        double num11 = (double)(array2[num10] * num2 + num) + num9;
                        array[l * this.Dimensions + m] = (float)num11;
                        if (flag)
{
                            num9 = num11;
                        }
                        num10++;
                    }
                }
            }
            this._lookupTable = array;
        }
References System.array, NVorbis.Utils.ConvertFromVorbisFloat32(), NVorbis.Codebook.Dimensions, NVorbis.Codebook.Entries, int, NVorbis.Codebook.lookup1_values(), NVorbis.Codebook.MapType, and NVorbis.Contracts.IPacket.ReadBits().
Referenced by NVorbis.Codebook.Init().