Terraria Decompiled: NVorbis.Codebook.Init
Init()
void NVorbis.Codebook.Init (IPacket packet, IHuffman huffman) inline
Implements NVorbis.Contracts.ICodebook.
Definition at line 14 of file Codebook.cs.
        {
            if (packet.ReadBits(24) != 5653314UL)
            {
                throw new InvalidDataException("Book header had invalid signature!");
            }
            this.Dimensions = (int)packet.ReadBits(16);
            this.Entries = (int)packet.ReadBits(24);
            this._lengths = new int[this.Entries];
            this.InitTree(packet, huffman);
            this.InitLookupTable(packet);
        }
References NVorbis.Codebook.Entries, NVorbis.Codebook.InitLookupTable(), NVorbis.Codebook.InitTree(), int, and NVorbis.Contracts.IPacket.ReadBits().