Terraria Decompiled: System.Security.Claims.Claim.Initialize
Initialize()
void System.Security.Claims.Claim.Initialize (BinaryReader reader, ClaimsIdentity subject) inline private
Definition at line 258 of file Claim.cs.
        {
            if (reader == null)
            {
                throw new ArgumentNullException("reader");
            }
            this.m_subject = subject;
            Claim.SerializationMask serializationMask = (Claim.SerializationMask)reader.ReadInt32();
            int num = 1;
            int num2 = reader.ReadInt32();
            this.m_value = reader.ReadString();
            if ((serializationMask & Claim.SerializationMask.NameClaimType) == Claim.SerializationMask.NameClaimType)
            {
                this.m_type = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name";
            }
            else if ((serializationMask & Claim.SerializationMask.RoleClaimType) == Claim.SerializationMask.RoleClaimType)
            {
                this.m_type = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role";
            }
            else
            {
                this.m_type = reader.ReadString();
                num++;
            }
            if ((serializationMask & Claim.SerializationMask.StringType) == Claim.SerializationMask.StringType)
            {
                this.m_valueType = reader.ReadString();
                num++;
            }
            else
            {
                this.m_valueType = "http://www.w3.org/2001/XMLSchema#string";
            }
            if ((serializationMask & Claim.SerializationMask.Issuer) == Claim.SerializationMask.Issuer)
            {
                this.m_issuer = reader.ReadString();
                num++;
            }
            else
            {
                this.m_issuer = "LOCAL AUTHORITY";
            }
            if ((serializationMask & Claim.SerializationMask.OriginalIssuerEqualsIssuer) == Claim.SerializationMask.OriginalIssuerEqualsIssuer)
            {
                this.m_originalIssuer = this.m_issuer;
            }
            else if ((serializationMask & Claim.SerializationMask.OriginalIssuer) == Claim.SerializationMask.OriginalIssuer)
            {
                this.m_originalIssuer = reader.ReadString();
                num++;
            }
            else
            {
                this.m_originalIssuer = "LOCAL AUTHORITY";
            }
            if ((serializationMask & Claim.SerializationMask.HasProperties) == Claim.SerializationMask.HasProperties)
            {
                int num3 = reader.ReadInt32();
                for (int i = 0; i < num3; i++)
                {
                    this.Properties.Add(reader.ReadString(), reader.ReadString());
                }
            }
            if ((serializationMask & Claim.SerializationMask.UserData) == Claim.SerializationMask.UserData)
            {
                int num4 = reader.ReadInt32();
                this.m_userSerializationData = reader.ReadBytes(num4);
                num++;
            }
            for (int j = num; j < num2; j++)
            {
                reader.ReadString();
            }
        }
References System.Collections.Generic.IDictionary< TKey, TValue >.Add(), System.Security.Claims.Claim.m_issuer, System.Security.Claims.Claim.Properties, System.IO.BinaryReader.ReadBytes(), System.IO.BinaryReader.ReadInt32(), and System.IO.BinaryReader.ReadString().
Referenced by System.Security.Claims.Claim.Claim().