Terraria Decompiled: System.Runtime.CompilerServices.AsyncMethodBuilderCore.ThrowAsync
ThrowAsync()
static void System.Runtime.CompilerServices.AsyncMethodBuilderCore.ThrowAsync (Exception exception, SynchronizationContext targetContext) inline static package
Definition at line 124 of file AsyncMethodBuilderCore.cs.
        {
            ExceptionDispatchInfo exceptionDispatchInfo = ExceptionDispatchInfo.Capture(exception);
            if (targetContext != null)
            {
                try
                {
                    targetContext.Post(delegate(object state)
                    {
                        ((ExceptionDispatchInfo)state).Throw();
                    }, exceptionDispatchInfo);
                    return;
                }
                catch (Exception ex)
                {
                    exceptionDispatchInfo = ExceptionDispatchInfo.Capture(new AggregateException(new Exception[] { exception, ex }));
                }
            }
            if (!WindowsRuntimeMarshal.ReportUnhandledError(exceptionDispatchInfo.SourceException))
            {
                ThreadPool.QueueUserWorkItem(delegate(object state)
                {
                    ((ExceptionDispatchInfo)state).Throw();
                }, exceptionDispatchInfo);
            }
        }
References System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture(), System.exception, System.Threading.SynchronizationContext.Post(), System.Threading.ThreadPool.QueueUserWorkItem(), System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.ReportUnhandledError(), System.Runtime.ExceptionServices.ExceptionDispatchInfo.SourceException, and System.state.
Referenced by System.Runtime.CompilerServices.AsyncTaskMethodBuilder< TResult >.AwaitOnCompleted< TAwaiter, TStateMachine >(), System.Runtime.CompilerServices.AsyncVoidMethodBuilder.AwaitOnCompleted< TAwaiter, TStateMachine >(), System.Runtime.CompilerServices.AsyncTaskMethodBuilder< TResult >.AwaitUnsafeOnCompleted< TAwaiter, TStateMachine >(), System.Runtime.CompilerServices.AsyncVoidMethodBuilder.AwaitUnsafeOnCompleted< TAwaiter, TStateMachine >(), System.Runtime.CompilerServices.AsyncVoidMethodBuilder.NotifySynchronizationContextOfCompletion(), and System.Runtime.CompilerServices.AsyncVoidMethodBuilder.SetException().