Terraria Decompiled: System.Runtime.CompilerServices.AsyncMethodBuilderCore.GetCompletionAction
GetCompletionAction()
Action System.Runtime.CompilerServices.AsyncMethodBuilderCore.GetCompletionAction (Task taskForTracing, ref AsyncMethodBuilderCore::MoveNextRunner runnerToInitialize) inline package
Definition at line 53 of file AsyncMethodBuilderCore.cs.
        {
            Debugger.NotifyOfCrossThreadDependency();
            ExecutionContext executionContext = ExecutionContext.FastCapture();
            Action action;
            AsyncMethodBuilderCore.MoveNextRunner moveNextRunner;
            if (executionContext != null && executionContext.IsPreAllocatedDefault)
            {
                action = this.m_defaultContextAction;
                if (action != null)
                {
                    return action;
                }
                moveNextRunner = new AsyncMethodBuilderCore.MoveNextRunner(executionContext, this.m_stateMachine);
                action = new Action(moveNextRunner.Run);
                if (taskForTracing != null)
                {
                    action = (this.m_defaultContextAction = this.OutputAsyncCausalityEvents(taskForTracing, action));
                }
                else
                {
                    this.m_defaultContextAction = action;
                }
            }
            else
            {
                moveNextRunner = new AsyncMethodBuilderCore.MoveNextRunner(executionContext, this.m_stateMachine);
                action = new Action(moveNextRunner.Run);
                if (taskForTracing != null)
                {
                    action = this.OutputAsyncCausalityEvents(taskForTracing, action);
                }
            }
            if (this.m_stateMachine == null)
            {
                runnerToInitialize = moveNextRunner;
            }
            return action;
        }
References System.Action(), System.action, System.Threading.ExecutionContext.FastCapture(), System.Threading.ExecutionContext.IsPreAllocatedDefault, System.Runtime.CompilerServices.AsyncMethodBuilderCore.m_defaultContextAction, System.Runtime.CompilerServices.AsyncMethodBuilderCore.m_stateMachine, System.Diagnostics.Debugger.NotifyOfCrossThreadDependency(), System.Runtime.CompilerServices.AsyncMethodBuilderCore.OutputAsyncCausalityEvents(), and System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run().
Referenced by System.Runtime.CompilerServices.AsyncTaskMethodBuilder< TResult >.AwaitOnCompleted< TAwaiter, TStateMachine >(), System.Runtime.CompilerServices.AsyncVoidMethodBuilder.AwaitOnCompleted< TAwaiter, TStateMachine >(), System.Runtime.CompilerServices.AsyncTaskMethodBuilder< TResult >.AwaitUnsafeOnCompleted< TAwaiter, TStateMachine >(), and System.Runtime.CompilerServices.AsyncVoidMethodBuilder.AwaitUnsafeOnCompleted< TAwaiter, TStateMachine >().