Terraria Decompiled: System.Runtime.CompilerServices.AsyncMethodBuilderCore.TryGetStateMachineForDebugger
TryGetStateMachineForDebugger()
static Action System.Runtime.CompilerServices.AsyncMethodBuilderCore.TryGetStateMachineForDebugger (Action action) inline static package
Definition at line 158 of file AsyncMethodBuilderCore.cs.
        {
            object target = action.Target;
            AsyncMethodBuilderCore.MoveNextRunner moveNextRunner = target as AsyncMethodBuilderCore.MoveNextRunner;
            if (moveNextRunner != null)
            {
                return new Action(moveNextRunner.m_stateMachine.MoveNext);
            }
            AsyncMethodBuilderCore.ContinuationWrapper continuationWrapper = target as AsyncMethodBuilderCore.ContinuationWrapper;
            if (continuationWrapper != null)
            {
                return AsyncMethodBuilderCore.TryGetStateMachineForDebugger(continuationWrapper.m_continuation);
            }
            return action;
        }
References System.Action(), System.action, System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.m_continuation, System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.m_stateMachine, System.Runtime.CompilerServices.IAsyncStateMachine.MoveNext(), and System.Runtime.CompilerServices.AsyncMethodBuilderCore.TryGetStateMachineForDebugger().
Referenced by System.Threading.Tasks.AwaitTaskContinuation.GetDelegateContinuationsForDebugger(), System.Threading.Tasks.Task< TResult >.GetDelegatesFromContinuationObject(), and System.Runtime.CompilerServices.AsyncMethodBuilderCore.TryGetStateMachineForDebugger().