Terraria Decompiled: System.Runtime.CompilerServices.AsyncMethodBuilderCore.PostBoxInitialization
PostBoxInitialization()
void System.Runtime.CompilerServices.AsyncMethodBuilderCore.PostBoxInitialization (IAsyncStateMachine stateMachine, AsyncMethodBuilderCore::MoveNextRunner runner, Task builtTask) inline package
Definition at line 105 of file AsyncMethodBuilderCore.cs.
        {
            if (builtTask != null)
            {
                if (AsyncCausalityTracer.LoggingOn)
                {
                    AsyncCausalityTracer.TraceOperationCreation(CausalityTraceLevel.Required, builtTask.Id, "Async: " + stateMachine.GetType().Name, 0UL);
                }
                if (Task.s_asyncDebuggingEnabled)
                {
                    Task.AddToActiveTasks(builtTask);
                }
            }
            this.m_stateMachine = stateMachine;
            this.m_stateMachine.SetStateMachine(this.m_stateMachine);
            runner.m_stateMachine = this.m_stateMachine;
        }
References System.Threading.Tasks.Task< TResult >.AddToActiveTasks(), System.Threading.Tasks.Task< TResult >.Id, System.Threading.Tasks.AsyncCausalityTracer.LoggingOn, System.Runtime.CompilerServices.AsyncMethodBuilderCore.m_stateMachine, System.Threading.Tasks.Task< TResult >.s_asyncDebuggingEnabled, System.Runtime.CompilerServices.IAsyncStateMachine.SetStateMachine(), and System.Threading.Tasks.AsyncCausalityTracer.TraceOperationCreation().
Referenced by System.Runtime.CompilerServices.AsyncTaskMethodBuilder< TResult >.AwaitOnCompleted< TAwaiter, TStateMachine >(), System.Runtime.CompilerServices.AsyncVoidMethodBuilder.AwaitOnCompleted< TAwaiter, TStateMachine >(), System.Runtime.CompilerServices.AsyncTaskMethodBuilder< TResult >.AwaitUnsafeOnCompleted< TAwaiter, TStateMachine >(), and System.Runtime.CompilerServices.AsyncVoidMethodBuilder.AwaitUnsafeOnCompleted< TAwaiter, TStateMachine >().