Terraria Decompiled: FullSerializer.fsJsonParser.TryParseNumber
TryParseNumber()
fsResult FullSerializer.fsJsonParser.TryParseNumber (out fsData data) inline private
Definition at line 313 of file fsJsonParser.cs.
        {
            int start = this._start;
            while (this.TryMoveNext() && this.HasValue() && !this.IsSeparator(this.Character()))
            {
            }
            string text = this._input.Substring(start, this._start - start);
            if (text.Contains(".") || text == "Infinity" || text == "-Infinity" || text == "NaN")
            {
                double num;
                if (!double.TryParse(text, 511, CultureInfo.InvariantCulture, ref num))
                {
                    data = null;
                    return this.MakeFailure("Bad double format with " + text);
                }
                data = new fsData(num);
                return fsResult.Success;
            }
            else
            {
                long num2;
                if (!long.TryParse(text, 511, CultureInfo.InvariantCulture, ref num2))
                {
                    data = null;
                    return this.MakeFailure("Bad Int64 format with " + text);
                }
                data = new fsData(num2);
                return fsResult.Success;
            }
        }
References FullSerializer.fsJsonParser._input, FullSerializer.fsJsonParser._start, FullSerializer.fsJsonParser.Character(), FullSerializer.fsJsonParser.HasValue(), System.Globalization.CultureInfo.InvariantCulture, FullSerializer.fsJsonParser.IsSeparator(), FullSerializer.fsJsonParser.MakeFailure(), System.start, FullSerializer.fsResult.Success, System.text, and FullSerializer.fsJsonParser.TryMoveNext().
Referenced by FullSerializer.fsJsonParser.RunParse().