Terraria Decompiled: FullSerializer.fsJsonParser.TryUnescapeChar
TryUnescapeChar()
fsResult FullSerializer.fsJsonParser.TryUnescapeChar (out char escaped) inline private
Definition at line 143 of file fsJsonParser.cs.
        {
            this.TryMoveNext();
            if (!this.HasValue())
            {
                escaped = ' ';
                return this.MakeFailure("Unexpected end of input after \\");
            }
            char c = this.Character();
            if (c <= '\\')
            {
                if (c <= '/')
                {
                    if (c == '"')
                    {
                        this.TryMoveNext();
                        escaped = '"';
                        return fsResult.Success;
                    }
                    if (c == '/')
                    {
                        this.TryMoveNext();
                        escaped = '/';
                        return fsResult.Success;
                    }
                }
                else
                {
                    if (c == '0')
                    {
                        this.TryMoveNext();
                        escaped = '\0';
                        return fsResult.Success;
                    }
                    if (c == '\\')
                    {
                        this.TryMoveNext();
                        escaped = '\\';
                        return fsResult.Success;
                    }
                }
            }
            else if (c <= 'b')
            {
                if (c == 'a')
                {
                    this.TryMoveNext();
                    escaped = '\a';
                    return fsResult.Success;
                }
                if (c == 'b')
                {
                    this.TryMoveNext();
                    escaped = '\b';
                    return fsResult.Success;
                }
            }
            else
            {
                if (c == 'f')
                {
                    this.TryMoveNext();
                    escaped = '\f';
                    return fsResult.Success;
                }
                if (c == 'n')
                {
                    this.TryMoveNext();
                    escaped = '\n';
                    return fsResult.Success;
                }
                switch (c)
                {
                case 'r':
                    this.TryMoveNext();
                    escaped = '\r';
                    return fsResult.Success;
                case 't':
                    this.TryMoveNext();
                    escaped = '\t';
                    return fsResult.Success;
                case 'u':
                    this.TryMoveNext();
                    if (this.IsHex(this.Character(0)) && this.IsHex(this.Character(1)) && this.IsHex(this.Character(2)) && this.IsHex(this.Character(3)))
                    {
                        uint num = this.ParseUnicode(this.Character(0), this.Character(1), this.Character(2), this.Character(3));
                        this.TryMoveNext();
                        this.TryMoveNext();
                        this.TryMoveNext();
                        this.TryMoveNext();
                        escaped = (char)num;
                        return fsResult.Success;
                    }
                    escaped = '\0';
                    return this.MakeFailure(string.Format("invalid escape sequence '\\u{0}{1}{2}{3}'\n", new object[]
                    {
                        this.Character(0),
                        this.Character(1),
                        this.Character(2),
                        this.Character(3)
                    }));
                }
            }
            escaped = '\0';
            return this.MakeFailure(string.Format("Invalid escape sequence \\{0}", this.Character()));
        }
References FullSerializer.fsJsonParser.Character(), System.Globalization.Format, FullSerializer.fsJsonParser.HasValue(), FullSerializer.fsJsonParser.IsHex(), FullSerializer.fsJsonParser.MakeFailure(), FullSerializer.fsJsonParser.ParseUnicode(), FullSerializer.fsResult.Success, and FullSerializer.fsJsonParser.TryMoveNext().
Referenced by FullSerializer.fsJsonParser.TryParseString().