Terraria Decompiled: FullSerializer.fsJsonParser.MakeFailure
MakeFailure()
fsResult FullSerializer.fsJsonParser.MakeFailure (string message) inline private
Definition at line 12 of file fsJsonParser.cs.
        {
            int num = Math.Max(0, this._start - 20);
            int num2 = Math.Min(50, this._input.Length - num);
            return fsResult.Fail(string.Concat(new string[]
            {
                "Error while parsing: ",
                message,
                "; context = <",
                this._input.Substring(num, num2),
                ">"
            }));
        }
References FullSerializer.fsJsonParser._input, FullSerializer.fsJsonParser._start, FullSerializer.fsResult.Fail(), System.Math.Max(), and System.Math.Min().
Referenced by FullSerializer.fsJsonParser.RunParse(), FullSerializer.fsJsonParser.TryParseArray(), FullSerializer.fsJsonParser.TryParseExact(), FullSerializer.fsJsonParser.TryParseNumber(), FullSerializer.fsJsonParser.TryParseObject(), FullSerializer.fsJsonParser.TryParseString(), and FullSerializer.fsJsonParser.TryUnescapeChar().