Terraria Decompiled: FullSerializer.fsJsonParser.TryParseExact
TryParseExact()
fsResult FullSerializer.fsJsonParser.TryParseExact (string content) inline private
Definition at line 251 of file fsJsonParser.cs.
        {
            for (int i = 0; i < content.Length; i++)
            {
                if (this.Character() != content.get_Chars(i))
                {
                    return this.MakeFailure("Expected " + content.get_Chars(i).ToString());
                }
                if (!this.TryMoveNext())
                {
                    return this.MakeFailure("Unexpected end of content when parsing " + content);
                }
            }
            return fsResult.Success;
        }
References FullSerializer.fsJsonParser.Character(), FullSerializer.fsJsonParser.MakeFailure(), FullSerializer.fsResult.Success, and FullSerializer.fsJsonParser.TryMoveNext().
Referenced by FullSerializer.fsJsonParser.TryParseFalse(), FullSerializer.fsJsonParser.TryParseNull(), and FullSerializer.fsJsonParser.TryParseTrue().