Terraria Decompiled: FullSerializer.fsJsonParser.TryParseArray
TryParseArray()
fsResult FullSerializer.fsJsonParser.TryParseArray (out fsData arr) inline private
Definition at line 387 of file fsJsonParser.cs.
        {
            if (this.Character() != '[')
            {
                arr = null;
                return this.MakeFailure("Expected initial [ when parsing an array");
            }
            if (!this.TryMoveNext())
            {
                arr = null;
                return this.MakeFailure("Unexpected end of input when parsing an array");
            }
            this.SkipSpace();
            List<fsData> list = new List<fsData>();
            while (this.HasValue() && this.Character() != ']')
            {
                fsData fsData;
                fsResult fsResult = this.RunParse(out fsData);
                if (fsResult.Failed)
                {
                    arr = null;
                    return fsResult;
                }
                list.Add(fsData);
                this.SkipSpace();
                if (this.HasValue() && this.Character() == ',')
                {
                    if (!this.TryMoveNext())
                    {
                        break;
                    }
                    this.SkipSpace();
                }
            }
            if (!this.HasValue() || this.Character() != ']' || !this.TryMoveNext())
            {
                arr = null;
                return this.MakeFailure("No closing ] for array");
            }
            arr = new fsData(list);
            return fsResult.Success;
        }
References FullSerializer.fsJsonParser.Character(), FullSerializer.fsResult.Failed, FullSerializer.fsJsonParser.HasValue(), System.list, FullSerializer.fsJsonParser.MakeFailure(), FullSerializer.fsJsonParser.RunParse(), FullSerializer.fsJsonParser.SkipSpace(), FullSerializer.fsResult.Success, and FullSerializer.fsJsonParser.TryMoveNext().
Referenced by FullSerializer.fsJsonParser.RunParse().