Terraria Decompiled: FullSerializer.fsJsonParser.RunParse
RunParse()
fsResult FullSerializer.fsJsonParser.RunParse (out fsData data) inline private
Definition at line 490 of file fsJsonParser.cs.
        {
            this.SkipSpace();
            if (!this.HasValue())
            {
                data = null;
                return this.MakeFailure("Unexpected end of input");
            }
            char c = this.Character();
            if (c <= '[')
            {
                if (c <= 'I')
                {
                    switch (c)
                    {
                    case '"':
                    {
                        string text;
                        fsResult fsResult = this.TryParseString(out text);
                        if (fsResult.Failed)
{
                            data = null;
                            return fsResult;
                        }
                        data = new fsData(text);
                        return fsResult.Success;
                    }
                    case '#':
                    case '$':
                    case '%':
                    case '&':
                    case '\'':
                    case '(':
                    case ')':
                    case '*':
                    case ',':
                    case '/':
                        goto IL_011F;
                    case '+':
                    case '-':
                    case '.':
                    case '0':
                    case '1':
                    case '2':
                    case '3':
                    case '4':
                    case '5':
                    case '6':
                    case '7':
                    case '8':
                    case '9':
                        break;
                    default:
                        if (c != 'I')
{
                            goto IL_011F;
                        }
                        break;
                    }
                }
                else if (c != 'N')
                {
                    if (c != '[')
                    {
                        goto IL_011F;
                    }
                    return this.TryParseArray(out data);
                }
                return this.TryParseNumber(out data);
            }
            if (c <= 'n')
            {
                if (c == 'f')
                {
                    return this.TryParseFalse(out data);
                }
                if (c == 'n')
                {
                    return this.TryParseNull(out data);
                }
            }
            else
            {
                if (c == 't')
                {
                    return this.TryParseTrue(out data);
                }
                if (c == '{')
                {
                    return this.TryParseObject(out data);
                }
            }
            IL_011F:
            data = null;
            return this.MakeFailure("unable to parse; invalid token \"" + this.Character().ToString() + "\"");
        }
References FullSerializer.fsJsonParser.Character(), FullSerializer.fsResult.Failed, FullSerializer.fsJsonParser.HasValue(), FullSerializer.fsJsonParser.MakeFailure(), FullSerializer.fsJsonParser.SkipSpace(), FullSerializer.fsResult.Success, System.text, System.ToString, FullSerializer.fsJsonParser.TryParseArray(), FullSerializer.fsJsonParser.TryParseFalse(), FullSerializer.fsJsonParser.TryParseNull(), FullSerializer.fsJsonParser.TryParseNumber(), FullSerializer.fsJsonParser.TryParseObject(), FullSerializer.fsJsonParser.TryParseString(), and FullSerializer.fsJsonParser.TryParseTrue().
Referenced by FullSerializer.fsJsonParser.TryParseArray(), and FullSerializer.fsJsonParser.TryParseObject().