Terraria Decompiled: FullSerializer.fsJsonParser.TryParseObject
TryParseObject()
fsResult FullSerializer.fsJsonParser.TryParseObject (out fsData obj) inline private
Definition at line 431 of file fsJsonParser.cs.
        {
            if (this.Character() != '{')
            {
                obj = null;
                return this.MakeFailure("Expected initial { when parsing an object");
            }
            if (!this.TryMoveNext())
            {
                obj = null;
                return this.MakeFailure("Unexpected end of input when parsing an object");
            }
            this.SkipSpace();
            Dictionary<string, fsData> dictionary = new Dictionary<string, fsData>(fsGlobalConfig.IsCaseSensitive ? StringComparer.Ordinal : StringComparer.OrdinalIgnoreCase);
            while (this.HasValue() && this.Character() != '}')
            {
                this.SkipSpace();
                string text;
                fsResult fsResult = this.TryParseString(out text);
                if (fsResult.Failed)
                {
                    obj = null;
                    return fsResult;
                }
                this.SkipSpace();
                if (!this.HasValue() || this.Character() != ':' || !this.TryMoveNext())
                {
                    obj = null;
                    return this.MakeFailure("Expected : after key \"" + text + "\"");
                }
                this.SkipSpace();
                fsData fsData;
                fsResult = this.RunParse(out fsData);
                if (fsResult.Failed)
                {
                    obj = null;
                    return fsResult;
                }
                dictionary.Add(text, fsData);
                this.SkipSpace();
                if (this.HasValue() && this.Character() == ',')
                {
                    if (!this.TryMoveNext())
                    {
                        break;
                    }
                    this.SkipSpace();
                }
            }
            if (!this.HasValue() || this.Character() != '}' || !this.TryMoveNext())
            {
                obj = null;
                return this.MakeFailure("No closing } for object");
            }
            obj = new fsData(dictionary);
            return fsResult.Success;
        }
References FullSerializer.fsJsonParser.Character(), System.dictionary, FullSerializer.fsResult.Failed, FullSerializer.fsJsonParser.HasValue(), FullSerializer.fsGlobalConfig.IsCaseSensitive, FullSerializer.fsJsonParser.MakeFailure(), System.obj, System.StringComparer.Ordinal, System.StringComparer.OrdinalIgnoreCase, FullSerializer.fsJsonParser.RunParse(), FullSerializer.fsJsonParser.SkipSpace(), FullSerializer.fsResult.Success, System.text, FullSerializer.fsJsonParser.TryMoveNext(), and FullSerializer.fsJsonParser.TryParseString().
Referenced by FullSerializer.fsJsonParser.RunParse().