Terraria Decompiled: FullSerializer.fsJsonParser.TryParseString
TryParseString()
fsResult FullSerializer.fsJsonParser.TryParseString (out string str) inline private
Definition at line 345 of file fsJsonParser.cs.
        {
            this._cachedStringBuilder.Length = 0;
            if (this.Character() != '"' || !this.TryMoveNext())
            {
                str = string.Empty;
                return this.MakeFailure("Expected initial \" when parsing a string");
            }
            while (this.HasValue() && this.Character() != '"')
            {
                char c = this.Character();
                if (c == '\\')
                {
                    char c2;
                    fsResult fsResult = this.TryUnescapeChar(out c2);
                    if (fsResult.Failed)
                    {
                        str = string.Empty;
                        return fsResult;
                    }
                    this._cachedStringBuilder.Append(c2);
                }
                else
                {
                    this._cachedStringBuilder.Append(c);
                    if (!this.TryMoveNext())
                    {
                        str = string.Empty;
                        return this.MakeFailure("Unexpected end of input when reading a string");
                    }
                }
            }
            if (!this.HasValue() || this.Character() != '"' || !this.TryMoveNext())
            {
                str = string.Empty;
                return this.MakeFailure("No closing \" when parsing a string");
            }
            str = this._cachedStringBuilder.ToString();
            return fsResult.Success;
        }
References FullSerializer.fsJsonParser._cachedStringBuilder, System.Text.StringBuilder.Append(), FullSerializer.fsJsonParser.Character(), FullSerializer.fsResult.Failed, FullSerializer.fsJsonParser.HasValue(), FullSerializer.fsJsonParser.MakeFailure(), FullSerializer.fsResult.Success, System.Text.StringBuilder.ToString(), FullSerializer.fsJsonParser.TryMoveNext(), and FullSerializer.fsJsonParser.TryUnescapeChar().
Referenced by FullSerializer.fsJsonParser.RunParse(), and FullSerializer.fsJsonParser.TryParseObject().