Terraria Decompiled: Steamworks.CallbackDispatcher.Unregister
Unregister() [1/2]
static void Steamworks.CallbackDispatcher.Unregister (Callback cb) inline static package
Definition at line 92 of file CallbackDispatcher.cs.
        {
            int callbackIdentity = CallbackIdentities.GetCallbackIdentity(cb.GetCallbackType());
            Dictionary<int, List<Callback>> dictionary = (cb.IsGameServer ? CallbackDispatcher.m_registeredGameServerCallbacks : CallbackDispatcher.m_registeredCallbacks);
            object sync = CallbackDispatcher.m_sync;
            lock (sync)
            {
                List<Callback> list;
                if (dictionary.TryGetValue(callbackIdentity, ref list))
                {
                    list.Remove(cb);
                    if (list.Count == 0)
                    {
                        dictionary.Remove(callbackIdentity);
                    }
                }
            }
        }
References System.dictionary, Steamworks.CallbackIdentities.GetCallbackIdentity(), Steamworks.Callback< T >.GetCallbackType(), System.list, Steamworks.CallbackDispatcher.m_registeredCallbacks, Steamworks.CallbackDispatcher.m_sync, and System.Collections.Generic.List< T >.Remove().
Referenced by Steamworks.CallResult< T >.Cancel(), Steamworks.CallResult< T >.Set(), and Steamworks.Callback< T >.Unregister().