Terraria Decompiled: Steamworks.CallbackDispatcher.RunFrame
RunFrame()
static void Steamworks.CallbackDispatcher.RunFrame (bool isGameServer) inline static package
Definition at line 164 of file CallbackDispatcher.cs.
        {
            if (!CallbackDispatcher.IsInitialized)
            {
                throw new InvalidOperationException("Callback dispatcher is not initialized.");
            }
            HSteamPipe hsteamPipe = (HSteamPipe)(isGameServer ? NativeMethods.SteamGameServer_GetHSteamPipe() : NativeMethods.SteamAPI_GetHSteamPipe());
            NativeMethods.SteamAPI_ManualDispatch_RunFrame(hsteamPipe);
            Dictionary<int, List<Callback>> dictionary = (isGameServer ? CallbackDispatcher.m_registeredGameServerCallbacks : CallbackDispatcher.m_registeredCallbacks);
            while (NativeMethods.SteamAPI_ManualDispatch_GetNextCallback(hsteamPipe, CallbackDispatcher.m_pCallbackMsg))
            {
                CallbackMsg_t callbackMsg_t = (CallbackMsg_t)Marshal.PtrToStructure(CallbackDispatcher.m_pCallbackMsg, typeof(CallbackMsg_t));
                try
                {
                    List<Callback> list2;
                    if (callbackMsg_t.m_iCallback == 703)
                    {
                        SteamAPICallCompleted_t steamAPICallCompleted_t = (SteamAPICallCompleted_t)Marshal.PtrToStructure(callbackMsg_t.m_pubParam, typeof(SteamAPICallCompleted_t));
                        IntPtr intPtr = Marshal.AllocHGlobal((int)steamAPICallCompleted_t.m_cubParam);
                        bool flag;
                        if (NativeMethods.SteamAPI_ManualDispatch_GetAPICallResult(hsteamPipe, steamAPICallCompleted_t.m_hAsyncCall, intPtr, (int)steamAPICallCompleted_t.m_cubParam, steamAPICallCompleted_t.m_iCallback, out flag))
{
                            object obj = CallbackDispatcher.m_sync;
                            lock (obj)
{
                                List<CallResult> list;
                                if (CallbackDispatcher.m_registeredCallResults.TryGetValue((ulong)steamAPICallCompleted_t.m_hAsyncCall, ref list))
{
                                    CallbackDispatcher.m_registeredCallResults.Remove((ulong)steamAPICallCompleted_t.m_hAsyncCall);
                                    foreach (CallResult callResult in list)
{
                                        callResult.OnRunCallResult(intPtr, flag, (ulong)steamAPICallCompleted_t.m_hAsyncCall);
                                        callResult.SetUnregistered();
                                    }
                                }
                            }
                        }
                        Marshal.FreeHGlobal(intPtr);
                    }
                    else if (dictionary.TryGetValue(callbackMsg_t.m_iCallback, ref list2))
                    {
                        object obj = CallbackDispatcher.m_sync;
                        List<Callback> list3;
                        lock (obj)
{
                            list3 = new List<Callback>(list2);
                        }
                        foreach (Callback callback in list3)
{
                            callback.OnRunCallback(callbackMsg_t.m_pubParam);
                        }
                    }
                }
                catch (Exception ex)
                {
                    CallbackDispatcher.ExceptionHandler(ex);
                }
                finally
                {
                    NativeMethods.SteamAPI_ManualDispatch_FreeLastCallback(hsteamPipe);
                }
            }
        }
References System.Runtime.InteropServices.Marshal.AllocHGlobal(), System.dictionary, Steamworks.CallbackDispatcher.ExceptionHandler(), System.Runtime.InteropServices.Marshal.FreeHGlobal(), Steamworks.CallbackDispatcher.IsInitialized, System.list, Steamworks.SteamAPICallCompleted_t.m_cubParam, Steamworks.SteamAPICallCompleted_t.m_hAsyncCall, Steamworks.CallbackMsg_t.m_iCallback, Steamworks.SteamAPICallCompleted_t.m_iCallback, Steamworks.CallbackDispatcher.m_pCallbackMsg, Steamworks.CallbackMsg_t.m_pubParam, Steamworks.CallbackDispatcher.m_registeredCallbacks, Steamworks.CallbackDispatcher.m_registeredCallResults, Steamworks.CallbackDispatcher.m_sync, System.obj, Steamworks.Callback< T >.OnRunCallback(), Steamworks.CallResult< T >.OnRunCallResult(), System.Runtime.InteropServices.Marshal.PtrToStructure(), Steamworks.CallResult< T >.SetUnregistered(), Steamworks.NativeMethods.SteamAPI_GetHSteamPipe(), Steamworks.NativeMethods.SteamAPI_ManualDispatch_FreeLastCallback(), Steamworks.NativeMethods.SteamAPI_ManualDispatch_GetAPICallResult(), Steamworks.NativeMethods.SteamAPI_ManualDispatch_GetNextCallback(), Steamworks.NativeMethods.SteamAPI_ManualDispatch_RunFrame(), and Steamworks.NativeMethods.SteamGameServer_GetHSteamPipe().
Referenced by Steamworks.GameServer.RunCallbacks(), and Steamworks.SteamAPI.RunCallbacks().