Terraria Decompiled: Steamworks.CallbackDispatcher.UnregisterAll
UnregisterAll()
static void Steamworks.CallbackDispatcher.UnregisterAll () inline static private
Definition at line 130 of file CallbackDispatcher.cs.
        {
            List<Callback> list = new List<Callback>();
            List<CallResult> list2 = new List<CallResult>();
            object sync = CallbackDispatcher.m_sync;
            lock (sync)
            {
                foreach (KeyValuePair<int, List<Callback>> keyValuePair in CallbackDispatcher.m_registeredCallbacks)
                {
                    list.AddRange(keyValuePair.Value);
                }
                CallbackDispatcher.m_registeredCallbacks.Clear();
                foreach (KeyValuePair<int, List<Callback>> keyValuePair2 in CallbackDispatcher.m_registeredGameServerCallbacks)
                {
                    list.AddRange(keyValuePair2.Value);
                }
                CallbackDispatcher.m_registeredGameServerCallbacks.Clear();
                foreach (KeyValuePair<ulong, List<CallResult>> keyValuePair3 in CallbackDispatcher.m_registeredCallResults)
                {
                    list2.AddRange(keyValuePair3.Value);
                }
                CallbackDispatcher.m_registeredCallResults.Clear();
                foreach (Callback callback in list)
                {
                    callback.SetUnregistered();
                }
                foreach (CallResult callResult in list2)
                {
                    callResult.SetUnregistered();
                }
            }
        }
References System.Collections.Generic.List< T >.AddRange(), System.list, Steamworks.CallbackDispatcher.m_registeredCallbacks, Steamworks.CallbackDispatcher.m_registeredCallResults, Steamworks.CallbackDispatcher.m_registeredGameServerCallbacks, Steamworks.CallbackDispatcher.m_sync, Steamworks.Callback< T >.SetUnregistered(), and Steamworks.CallResult< T >.SetUnregistered().
Referenced by Steamworks.CallbackDispatcher.Shutdown().