Terraria Decompiled: Steamworks.CallbackDispatcher.Initialize
Initialize()
static void Steamworks.CallbackDispatcher.Initialize () inline static package
Definition at line 27 of file CallbackDispatcher.cs.
        {
            object sync = CallbackDispatcher.m_sync;
            lock (sync)
            {
                if (CallbackDispatcher.m_initCount == 0)
                {
                    NativeMethods.SteamAPI_ManualDispatch_Init();
                    CallbackDispatcher.m_pCallbackMsg = Marshal.AllocHGlobal(Marshal.SizeOf(typeof(CallbackMsg_t)));
                }
                CallbackDispatcher.m_initCount++;
            }
        }
References System.Runtime.InteropServices.Marshal.AllocHGlobal(), Steamworks.CallbackDispatcher.m_initCount, Steamworks.CallbackDispatcher.m_sync, System.Runtime.InteropServices.Marshal.SizeOf(), and Steamworks.NativeMethods.SteamAPI_ManualDispatch_Init().
Referenced by Steamworks.SteamAPI.InitEx(), and Steamworks.GameServer.InitEx().