Terraria Decompiled: Steamworks.CallbackDispatcher.Shutdown
Shutdown()
static void Steamworks.CallbackDispatcher.Shutdown () inline static package
Definition at line 42 of file CallbackDispatcher.cs.
        {
            object sync = CallbackDispatcher.m_sync;
            lock (sync)
            {
                CallbackDispatcher.m_initCount--;
                if (CallbackDispatcher.m_initCount == 0)
                {
                    CallbackDispatcher.UnregisterAll();
                    Marshal.FreeHGlobal(CallbackDispatcher.m_pCallbackMsg);
                    CallbackDispatcher.m_pCallbackMsg = IntPtr.Zero;
                }
            }
        }
References System.Runtime.InteropServices.Marshal.FreeHGlobal(), Steamworks.CallbackDispatcher.m_initCount, Steamworks.CallbackDispatcher.m_pCallbackMsg, Steamworks.CallbackDispatcher.m_sync, Steamworks.CallbackDispatcher.UnregisterAll(), and System.IntPtr.Zero.
Referenced by Steamworks.GameServer.Shutdown(), and Steamworks.SteamAPI.Shutdown().