Terraria Decompiled: Steamworks.CallbackDispatcher.ExceptionHandler
ExceptionHandler()
static void Steamworks.CallbackDispatcher.ExceptionHandler (Exception e) inline static
Definition at line 11 of file CallbackDispatcher.cs.
        {
            Console.WriteLine(e.Message);
        }
References System.Exception.Message, and System.Console.WriteLine().
Referenced by Steamworks.ISteamMatchmakingServerListResponse.InternalOnRefreshComplete(), Steamworks.ISteamMatchmakingServerListResponse.InternalOnServerFailedToRespond(), Steamworks.ISteamMatchmakingServerListResponse.InternalOnServerResponded(), Steamworks.Callback< T >.OnRunCallback(), Steamworks.CallResult< T >.OnRunCallResult(), and Steamworks.CallbackDispatcher.RunFrame().