Terraria Decompiled: Terraria.GameContent.Shaders.SepiaScreenShaderData.GetDaylightPowers
GetDaylightPowers()
static void Terraria.GameContent.Shaders.SepiaScreenShaderData.GetDaylightPowers (out float nightlightPower, out float daylightPower, out float moonPower, out float dawnPower) inline static private
Definition at line 75 of file SepiaScreenShaderData.cs.
        {
            nightlightPower = 0f;
            daylightPower = 0f;
            moonPower = 0f;
            Vector2 dayTimeAsDirectionIn24HClock = Utils.GetDayTimeAsDirectionIn24HClock();
            Vector2 dayTimeAsDirectionIn24HClock2 = Utils.GetDayTimeAsDirectionIn24HClock(4.5f);
            Vector2 dayTimeAsDirectionIn24HClock3 = Utils.GetDayTimeAsDirectionIn24HClock(0f);
            float num = Vector2.Dot(dayTimeAsDirectionIn24HClock, dayTimeAsDirectionIn24HClock3);
            float num2 = Vector2.Dot(dayTimeAsDirectionIn24HClock, dayTimeAsDirectionIn24HClock2);
            nightlightPower = Utils.Remap(num, -0.2f, 0.1f, 0f, 1f, true);
            daylightPower = Utils.Remap(num, 0.1f, -1f, 0f, 1f, true);
            dawnPower = Utils.Remap(num2, 0.66f, 1f, 0f, 1f, true);
            if (!Main.dayTime)
            {
                float num3 = (float)(Main.time / 32400.0) * 2f;
                if (num3 > 1f)
                {
                    num3 = 2f - num3;
                }
                moonPower = Utils.Remap(num3, 0f, 0.25f, 0f, 1f, true);
            }
        }
References Terraria.Main.dayTime, Microsoft.Xna.Framework.Vector2.Dot(), Terraria.Utils.GetDayTimeAsDirectionIn24HClock(), Terraria.Utils.Remap(), and Terraria.Main.time.
Referenced by Terraria.GameContent.Shaders.SepiaScreenShaderData.Update().