Terraria Decompiled: System.Reflection.MemberInfoSerializationHolder.GetRealObject
GetRealObject()
virtual object System.Reflection.MemberInfoSerializationHolder.GetRealObject (StreamingContext context) inline virtual
Implements System.Runtime.Serialization.IObjectReference.
Definition at line 67 of file MemberInfoSerializationHolder.cs.
        {
            if (this.m_memberName == null || this.m_reflectedType == null || this.m_memberType == (MemberTypes)0)
            {
                throw new SerializationException(Environment.GetResourceString("Insufficient state to return the real object."));
            }
            BindingFlags bindingFlags = BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.OptionalParamBinding;
            MemberTypes memberType = this.m_memberType;
            switch (memberType)
            {
            case MemberTypes.Constructor:
            {
                if (this.m_signature == null)
                {
                    throw new SerializationException(Environment.GetResourceString("The method signature cannot be null."));
                }
                ConstructorInfo[] array = this.m_reflectedType.GetMember(this.m_memberName, MemberTypes.Constructor, bindingFlags) as ConstructorInfo[];
                if (array.Length == 1)
                {
                    return array[0];
                }
                if (array.Length > 1)
                {
                    for (int i = 0; i < array.Length; i++)
                    {
                        if (this.m_signature2 != null)
{
                            if (((RuntimeConstructorInfo)array[i]).SerializationToString().Equals(this.m_signature2))
{
                                return array[i];
                            }
                        }
                        else if (array[i].ToString().Equals(this.m_signature))
{
                            return array[i];
                        }
                    }
                }
                throw new SerializationException(Environment.GetResourceString("Cannot get the member '{0}'.", new object[] { this.m_memberName }));
            }
            case MemberTypes.Event:
            {
                EventInfo[] array2 = this.m_reflectedType.GetMember(this.m_memberName, MemberTypes.Event, bindingFlags) as EventInfo[];
                if (array2.Length == 0)
                {
                    throw new SerializationException(Environment.GetResourceString("Cannot get the member '{0}'.", new object[] { this.m_memberName }));
                }
                return array2[0];
            }
            case MemberTypes.Constructor | MemberTypes.Event:
                break;
            case MemberTypes.Field:
            {
                FieldInfo[] array3 = this.m_reflectedType.GetMember(this.m_memberName, MemberTypes.Field, bindingFlags) as FieldInfo[];
                if (array3.Length == 0)
                {
                    throw new SerializationException(Environment.GetResourceString("Cannot get the member '{0}'.", new object[] { this.m_memberName }));
                }
                return array3[0];
            }
            default:
                if (memberType != MemberTypes.Method)
                {
                    if (memberType == MemberTypes.Property)
                    {
                        PropertyInfo[] array4 = this.m_reflectedType.GetMember(this.m_memberName, MemberTypes.Property, bindingFlags) as PropertyInfo[];
                        if (array4.Length == 0)
{
                            throw new SerializationException(Environment.GetResourceString("Cannot get the member '{0}'.", new object[] { this.m_memberName }));
                        }
                        if (array4.Length == 1)
{
                            return array4[0];
                        }
                        if (array4.Length > 1)
{
                            for (int j = 0; j < array4.Length; j++)
{
                                if (this.m_signature2 != null)
{
                                    if (((RuntimePropertyInfo)array4[j]).SerializationToString().Equals(this.m_signature2))
{
                                        return array4[j];
                                    }
                                }
                                else if (array4[j].ToString().Equals(this.m_signature))
{
                                    return array4[j];
                                }
                            }
                        }
                        throw new SerializationException(Environment.GetResourceString("Cannot get the member '{0}'.", new object[] { this.m_memberName }));
                    }
                }
                else
                {
                    MethodInfo methodInfo = null;
                    if (this.m_signature == null)
                    {
                        throw new SerializationException(Environment.GetResourceString("The method signature cannot be null."));
                    }
                    Type[] array5 = this.m_info.GetValueNoThrow("GenericArguments", typeof(Type[])) as Type[];
                    MethodInfo[] array6 = this.m_reflectedType.GetMember(this.m_memberName, MemberTypes.Method, bindingFlags) as MethodInfo[];
                    if (array6.Length == 1)
                    {
                        methodInfo = array6[0];
                    }
                    else if (array6.Length > 1)
                    {
                        for (int k = 0; k < array6.Length; k++)
{
                            if (this.m_signature2 != null)
{
                                if (((RuntimeMethodInfo)array6[k]).SerializationToString().Equals(this.m_signature2))
{
                                    methodInfo = array6[k];
                                    break;
                                }
                            }
                            else if (array6[k].ToString().Equals(this.m_signature))
{
                                methodInfo = array6[k];
                                break;
                            }
                            if (array5 != null && array6[k].IsGenericMethod && array6[k].GetGenericArguments().Length == array5.Length)
{
                                MethodInfo methodInfo2 = array6[k].MakeGenericMethod(array5);
                                if (this.m_signature2 != null)
{
                                    if (((RuntimeMethodInfo)methodInfo2).SerializationToString().Equals(this.m_signature2))
{
                                        methodInfo = methodInfo2;
                                        break;
                                    }
                                }
                                else if (methodInfo2.ToString().Equals(this.m_signature))
{
                                    methodInfo = methodInfo2;
                                    break;
                                }
                            }
                        }
                    }
                    if (methodInfo == null)
                    {
                        throw new SerializationException(Environment.GetResourceString("Cannot get the member '{0}'.", new object[] { this.m_memberName }));
                    }
                    if (!methodInfo.IsGenericMethodDefinition)
                    {
                        return methodInfo;
                    }
                    if (array5 == null)
                    {
                        return methodInfo;
                    }
                    if (array5[0] == null)
                    {
                        return null;
                    }
                    return methodInfo.MakeGenericMethod(array5);
                }
                break;
            }
            throw new ArgumentException(Environment.GetResourceString("Unknown member type."));
        }
References System.array, System.RuntimeType.GetMember(), System.Environment.GetResourceString(), System.Runtime.Serialization.SerializationInfo.GetValueNoThrow(), System.Reflection.MethodBase.IsGenericMethodDefinition, System.Reflection.MemberInfoSerializationHolder.m_info, System.Reflection.MemberInfoSerializationHolder.m_memberName, System.Reflection.MemberInfoSerializationHolder.m_memberType, System.Reflection.MemberInfoSerializationHolder.m_reflectedType, System.Reflection.MemberInfoSerializationHolder.m_signature, System.Reflection.MemberInfoSerializationHolder.m_signature2, System.Reflection.MethodInfo.MakeGenericMethod(), System.Runtime.InteropServices._MethodInfo.ToString(), and System.ToString.