Terraria Decompiled: System.Runtime.Remoting.ServerIdentity.AttachServerObject
AttachServerObject()
void System.Runtime.Remoting.ServerIdentity.AttachServerObject (MarshalByRefObject serverObject, Context context) inline
Definition at line 78 of file ServerIdentity.cs.
        {
            this.DisposeServerObject();
            this._context = context;
            this._serverObject = serverObject;
            if (RemotingServices.IsTransparentProxy(serverObject))
            {
                RealProxy realProxy = RemotingServices.GetRealProxy(serverObject);
                if (realProxy.ObjectIdentity == null)
                {
                    realProxy.ObjectIdentity = this;
                    return;
                }
            }
            else
            {
                if (this._objectType.IsContextful)
                {
                    this._envoySink = context.CreateEnvoySink(serverObject);
                }
                this._serverObject.ObjectIdentity = this;
            }
        }
References System.Runtime.Remoting.ServerIdentity._objectType, System.Runtime.Remoting.Contexts.Context.CreateEnvoySink(), System.Runtime.Remoting.ServerIdentity.DisposeServerObject(), System.Runtime.Remoting.RemotingServices.GetRealProxy(), System.Type.IsContextful, System.Runtime.Remoting.RemotingServices.IsTransparentProxy(), and System.Runtime.Remoting.Proxies.RealProxy.ObjectIdentity.
Referenced by System.Runtime.Remoting.RemotingServices.CreateClientActivatedServerIdentity(), and System.Runtime.Remoting.Activation.ActivationServices.CreateInstanceFromMessage().