Terraria Decompiled: ReLogic.Peripherals.RGB.SteelSeries.SteelSeriesDeviceGroup.UpdateDeviceList
UpdateDeviceList()
void ReLogic.Peripherals.RGB.SteelSeries.SteelSeriesDeviceGroup.UpdateDeviceList (List< RgbDevice > deviceList) inline private
Definition at line 143 of file SteelSeriesDeviceGroup.cs.
        {
            foreach (RgbDevice rgbDevice in deviceList)
            {
                IGameSenseDevice gameSenseDevice = rgbDevice as IGameSenseDevice;
                if (gameSenseDevice != null)
                {
                    List<JObject> list = gameSenseDevice.TryGetEventUpdateRequest();
                    if (list != null)
                    {
                        for (int i = 0; i < list.Count; i++)
{
                            JObject jobject = list[i];
                            if (jobject != null)
{
                                jobject.Add("game", this._gameSenseConnection.GameName);
                                string text = jobject.ToString(Formatting.None, new JsonConverter[0]);
                                this._gameSenseConnection.SendEvent(text);
                            }
                        }
                    }
                }
            }
            foreach (IGameSenseUpdater gameSenseUpdater in this._miscEvents)
            {
                List<JObject> list2 = gameSenseUpdater.TryGetEventUpdateRequest();
                if (list2 != null)
                {
                    for (int j = 0; j < list2.Count; j++)
                    {
                        JObject jobject2 = list2[j];
                        if (jobject2 != null)
{
                            jobject2.Add("game", this._gameSenseConnection.GameName);
                            string text2 = jobject2.ToString(Formatting.None, new JsonConverter[0]);
                            this._gameSenseConnection.SendEvent(text2);
                        }
                    }
                }
            }
        }
References ReLogic.Peripherals.RGB.SteelSeries.SteelSeriesDeviceGroup._gameSenseConnection, ReLogic.Peripherals.RGB.SteelSeries.SteelSeriesDeviceGroup._miscEvents, Newtonsoft.Json.Linq.JObject.Add(), System.Collections.Generic.List< T >.Count, ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection.GameName, System.list, ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection.SendEvent(), System.text, Newtonsoft.Json.Linq.JToken.ToString(), and ReLogic.Peripherals.RGB.SteelSeries.IGameSenseUpdater.TryGetEventUpdateRequest().
Referenced by ReLogic.Peripherals.RGB.SteelSeries.SteelSeriesDeviceGroup.SendRelevantChangesToGameSense().