Terraria Decompiled: Steamworks.SteamNetworkingMessages.GetSessionConnectionInfo
GetSessionConnectionInfo()
static ESteamNetworkingConnectionState Steamworks.SteamNetworkingMessages.GetSessionConnectionInfo (ref SteamNetworkingIdentity identityRemote, out SteamNetConnectionInfo_t pConnectionInfo, out SteamNetConnectionRealTimeStatus_t pQuickStatus) inline static
Definition at line 48 of file SteamNetworkingMessages.cs.
        {
            InteropHelp.TestIfAvailableClient();
            return NativeMethods.ISteamNetworkingMessages_GetSessionConnectionInfo(CSteamAPIContext.GetSteamNetworkingMessages(), ref identityRemote, out pConnectionInfo, out pQuickStatus);
        }
References Steamworks.CSteamAPIContext.GetSteamNetworkingMessages(), Steamworks.NativeMethods.ISteamNetworkingMessages_GetSessionConnectionInfo(), and Steamworks.InteropHelp.TestIfAvailableClient().