Terraria Decompiled: Newtonsoft.Json.Converters.BinaryConverter.ReadJson
ReadJson()
override object Newtonsoft.Json.Converters.BinaryConverter.ReadJson (JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer) inline
Definition at line 49 of file BinaryConverter.cs.
        {
            if (reader.TokenType == JsonToken.Null)
            {
                if (!ReflectionUtils.IsNullable(objectType))
                {
                    throw JsonSerializationException.Create(reader, "Cannot convert null value to {0}.".FormatWith(CultureInfo.InvariantCulture, objectType));
                }
                return null;
            }
            else
            {
                byte[] array;
                if (reader.TokenType == JsonToken.StartArray)
                {
                    array = this.ReadByteArray(reader);
                }
                else
                {
                    if (reader.TokenType != JsonToken.String)
                    {
                        throw JsonSerializationException.Create(reader, "Unexpected token parsing binary. Expected String or StartArray, got {0}.".FormatWith(CultureInfo.InvariantCulture, reader.TokenType));
                    }
                    array = Convert.FromBase64String(reader.Value.ToString());
                }
                Type type = (ReflectionUtils.IsNullableType(objectType) ? Nullable.GetUnderlyingType(objectType) : objectType);
                if (type.FullName == "System.Data.Linq.Binary")
                {
                    BinaryConverter.EnsureReflectionObject(type);
                    return BinaryConverter._reflectionObject.Creator(new object[] { array });
                }
                if (type == typeof(SqlBinary))
                {
                    return new SqlBinary(array);
                }
                throw JsonSerializationException.Create(reader, "Unexpected object type when writing binary: {0}".FormatWith(CultureInfo.InvariantCulture, objectType));
            }
        }
References Newtonsoft.Json.Converters.BinaryConverter._reflectionObject, System.array, Newtonsoft.Json.JsonSerializationException.Create(), Newtonsoft.Json.Utilities.ReflectionObject.Creator, Newtonsoft.Json.Converters.BinaryConverter.EnsureReflectionObject(), System.Convert.FromBase64String(), System.Type.FullName, System.Nullable< T >.GetUnderlyingType(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.Utilities.ReflectionUtils.IsNullable(), Newtonsoft.Json.Utilities.ReflectionUtils.IsNullableType(), Newtonsoft.Json.Converters.BinaryConverter.ReadByteArray(), Newtonsoft.Json.JsonReader.TokenType, and Newtonsoft.Json.JsonReader.Value.