Terraria Decompiled: Newtonsoft.Json.Converters.BinaryConverter.EnsureReflectionObject
EnsureReflectionObject()
static void Newtonsoft.Json.Converters.BinaryConverter.EnsureReflectionObject (Type t) inline static private
Definition at line 40 of file BinaryConverter.cs.
        {
            if (BinaryConverter._reflectionObject == null)
            {
                BinaryConverter._reflectionObject = ReflectionObject.Create(t, t.GetConstructor(new Type[] { typeof(byte[]) }), new string[] { "ToArray" });
            }
        }
References Newtonsoft.Json.Converters.BinaryConverter._reflectionObject, Newtonsoft.Json.Utilities.ReflectionObject.Create(), and System.Type.GetConstructor().
Referenced by Newtonsoft.Json.Converters.BinaryConverter.GetByteArray(), and Newtonsoft.Json.Converters.BinaryConverter.ReadJson().