Terraria Decompiled: System.Security.Cryptography.SHA384Managed.SHATransform
SHATransform()
static unsafe void System.Security.Cryptography.SHA384Managed.SHATransform (ulong * expandedBuffer, ulong * state, byte * block) inline static private
Definition at line 150 of file SHA384Managed.cs.
        {
            ulong num = *state;
            ulong num2 = state[1];
            ulong num3 = state[2];
            ulong num4 = state[3];
            ulong num5 = state[4];
            ulong num6 = state[5];
            ulong num7 = state[6];
            ulong num8 = state[7];
            Utils.QuadWordFromBigEndian(expandedBuffer, 16, block);
            SHA384Managed.SHA384Expand(expandedBuffer);
            for (int i = 0; i < 80; i++)
            {
                ulong num9 = num8 + SHA384Managed.Sigma_1(num5) + SHA384Managed.Ch(num5, num6, num7) + SHA384Managed._K[i] + expandedBuffer[i];
                ulong num10 = num4 + num9;
                ulong num11 = num9 + SHA384Managed.Sigma_0(num) + SHA384Managed.Maj(num, num2, num3);
                i++;
                num9 = num7 + SHA384Managed.Sigma_1(num10) + SHA384Managed.Ch(num10, num5, num6) + SHA384Managed._K[i] + expandedBuffer[i];
                ulong num12 = num3 + num9;
                ulong num13 = num9 + SHA384Managed.Sigma_0(num11) + SHA384Managed.Maj(num11, num, num2);
                i++;
                num9 = num6 + SHA384Managed.Sigma_1(num12) + SHA384Managed.Ch(num12, num10, num5) + SHA384Managed._K[i] + expandedBuffer[i];
                ulong num14 = num2 + num9;
                ulong num15 = num9 + SHA384Managed.Sigma_0(num13) + SHA384Managed.Maj(num13, num11, num);
                i++;
                num9 = num5 + SHA384Managed.Sigma_1(num14) + SHA384Managed.Ch(num14, num12, num10) + SHA384Managed._K[i] + expandedBuffer[i];
                ulong num16 = num + num9;
                ulong num17 = num9 + SHA384Managed.Sigma_0(num15) + SHA384Managed.Maj(num15, num13, num11);
                i++;
                num9 = num10 + SHA384Managed.Sigma_1(num16) + SHA384Managed.Ch(num16, num14, num12) + SHA384Managed._K[i] + expandedBuffer[i];
                num8 = num11 + num9;
                num4 = num9 + SHA384Managed.Sigma_0(num17) + SHA384Managed.Maj(num17, num15, num13);
                i++;
                num9 = num12 + SHA384Managed.Sigma_1(num8) + SHA384Managed.Ch(num8, num16, num14) + SHA384Managed._K[i] + expandedBuffer[i];
                num7 = num13 + num9;
                num3 = num9 + SHA384Managed.Sigma_0(num4) + SHA384Managed.Maj(num4, num17, num15);
                i++;
                num9 = num14 + SHA384Managed.Sigma_1(num7) + SHA384Managed.Ch(num7, num8, num16) + SHA384Managed._K[i] + expandedBuffer[i];
                num6 = num15 + num9;
                num2 = num9 + SHA384Managed.Sigma_0(num3) + SHA384Managed.Maj(num3, num4, num17);
                i++;
                num9 = num16 + SHA384Managed.Sigma_1(num6) + SHA384Managed.Ch(num6, num7, num8) + SHA384Managed._K[i] + expandedBuffer[i];
                num5 = num17 + num9;
                num = num9 + SHA384Managed.Sigma_0(num2) + SHA384Managed.Maj(num2, num3, num4);
            }
            *state += num;
            state[1] += num2;
            state[2] += num3;
            state[3] += num4;
            state[4] += num5;
            state[5] += num6;
            state[6] += num7;
            state[7] += num8;
        }
References System.Security.Cryptography.SHA384Managed._K, System.Security.Cryptography.SHA384Managed.Ch(), System.Security.Cryptography.SHA384Managed.Maj(), System.Security.Cryptography.Utils.QuadWordFromBigEndian(), System.Security.Cryptography.SHA384Managed.SHA384Expand(), System.Security.Cryptography.SHA384Managed.Sigma_0(), System.Security.Cryptography.SHA384Managed.Sigma_1(), and System.state.
Referenced by System.Security.Cryptography.SHA384Managed._HashData().