Terraria Decompiled: FullSerializer.fsJsonPrinter.BuildCompressedString
BuildCompressedString()
static void FullSerializer.fsJsonPrinter.BuildCompressedString (fsData data, TextWriter stream) inline static private
Definition at line 132 of file fsJsonPrinter.cs.
        {
            switch (data.Type)
            {
            case fsDataType.Array:
            {
                stream.Write('[');
                bool flag = false;
                foreach (fsData fsData in data.AsList)
                {
                    if (flag)
                    {
                        stream.Write(',');
                    }
                    flag = true;
                    fsJsonPrinter.BuildCompressedString(fsData, stream);
                }
                stream.Write(']');
                return;
            }
            case fsDataType.Object:
            {
                stream.Write('{');
                bool flag2 = false;
                foreach (KeyValuePair<string, fsData> keyValuePair in data.AsDictionary)
                {
                    if (flag2)
                    {
                        stream.Write(',');
                    }
                    flag2 = true;
                    stream.Write('"');
                    stream.Write(keyValuePair.Key);
                    stream.Write('"');
                    stream.Write(":");
                    fsJsonPrinter.BuildCompressedString(keyValuePair.Value, stream);
                }
                stream.Write('}');
                return;
            }
            case fsDataType.Double:
                stream.Write(fsJsonPrinter.ConvertDoubleToString(data.AsDouble));
                return;
            case fsDataType.Int64:
                stream.Write(data.AsInt64);
                return;
            case fsDataType.Boolean:
                if (data.AsBool)
                {
                    stream.Write("true");
                    return;
                }
                stream.Write("false");
                return;
            case fsDataType.String:
                stream.Write('"');
                stream.Write(fsJsonPrinter.EscapeString(data.AsString));
                stream.Write('"');
                return;
            case fsDataType.Null:
                stream.Write("null");
                return;
            default:
                return;
            }
        }
References FullSerializer.fsData.AsBool, FullSerializer.fsData.AsDictionary, FullSerializer.fsData.AsDouble, FullSerializer.fsData.AsInt64, FullSerializer.fsData.AsList, FullSerializer.fsData.AsString, FullSerializer.fsJsonPrinter.BuildCompressedString(), FullSerializer.fsJsonPrinter.ConvertDoubleToString(), FullSerializer.fsJsonPrinter.EscapeString(), System.Collections.Generic.KeyValuePair< TKey, TValue >.Key, FullSerializer.fsData.Type, System.Collections.Generic.KeyValuePair< TKey, TValue >.Value, and System.IO.TextWriter.Write().
Referenced by FullSerializer.fsJsonPrinter.BuildCompressedString(), FullSerializer.fsJsonPrinter.CompressedJson(), and FullSerializer.fsJsonPrinter.CompressedJson().