Terraria Decompiled: Terraria.GameContent.Events.CultistRitual.TrySpawning
TrySpawning()
static bool Terraria.GameContent.Events.CultistRitual.TrySpawning (int x, int y, bool force = false) inline static
Definition at line 53 of file CultistRitual.cs.
        {
            if (x < 0 || y < 0 || x >= Main.maxTilesX || y >= Main.maxTilesY)
            {
                return false;
            }
            if (!force && (WorldGen.PlayerLOS(x - 6, y) || WorldGen.PlayerLOS(x + 6, y)))
            {
                return false;
            }
            if (!CultistRitual.CheckRitual(x, y, force))
            {
                return false;
            }
            NPC.NewNPC(new EntitySource_WorldEvent(), x * 16 + 8, (y - 4) * 16 - 8, 437, 0, 0f, 0f, 0f, 0f, 255);
            return true;
        }
References Terraria.GameContent.Events.CultistRitual.CheckRitual(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.NPC.NewNPC(), and Terraria.WorldGen.PlayerLOS().
Referenced by Terraria.GameContent.Events.CultistRitual.UpdateTime().