Terraria Decompiled: Newtonsoft.Json.Schema.JsonSchemaModel.Combine
Combine()
static void Newtonsoft.Json.Schema.JsonSchemaModel.Combine (JsonSchemaModel model, JsonSchema schema) inline static private
Definition at line 425 of file JsonSchemaModel.cs.
        {
            model.Required = model.Required || (schema.Required ?? false);
            model.Type &= schema.Type ?? JsonSchemaType.Any;
            model.MinimumLength = MathUtils.Max(model.MinimumLength, schema.MinimumLength);
            model.MaximumLength = MathUtils.Min(model.MaximumLength, schema.MaximumLength);
            model.DivisibleBy = MathUtils.Max(model.DivisibleBy, schema.DivisibleBy);
            model.Minimum = MathUtils.Max(model.Minimum, schema.Minimum);
            model.Maximum = MathUtils.Max(model.Maximum, schema.Maximum);
            model.ExclusiveMinimum = model.ExclusiveMinimum || (schema.ExclusiveMinimum ?? false);
            model.ExclusiveMaximum = model.ExclusiveMaximum || (schema.ExclusiveMaximum ?? false);
            model.MinimumItems = MathUtils.Max(model.MinimumItems, schema.MinimumItems);
            model.MaximumItems = MathUtils.Min(model.MaximumItems, schema.MaximumItems);
            model.PositionalItemsValidation = model.PositionalItemsValidation || schema.PositionalItemsValidation;
            model.AllowAdditionalProperties = model.AllowAdditionalProperties && schema.AllowAdditionalProperties;
            model.AllowAdditionalItems = model.AllowAdditionalItems && schema.AllowAdditionalItems;
            model.UniqueItems = model.UniqueItems || schema.UniqueItems;
            if (schema.Enum != null)
            {
                if (model.Enum == null)
                {
                    model.Enum = new List<JToken>();
                }
                model.Enum.AddRangeDistinct(schema.Enum, JToken.EqualityComparer);
            }
            model.Disallow |= schema.Disallow ?? JsonSchemaType.None;
            if (schema.Pattern != null)
            {
                if (model.Patterns == null)
                {
                    model.Patterns = new List<string>();
                }
                model.Patterns.AddDistinct(schema.Pattern);
            }
        }
References Newtonsoft.Json.Schema.JsonSchema.AllowAdditionalItems, Newtonsoft.Json.Schema.JsonSchema.AllowAdditionalProperties, Newtonsoft.Json.Schema.JsonSchema.DivisibleBy, Newtonsoft.Json.Schema.JsonSchemaModel.DivisibleBy, Newtonsoft.Json.Schema.JsonSchema.Enum, Newtonsoft.Json.Schema.JsonSchemaModel.Enum, Newtonsoft.Json.Linq.JToken.EqualityComparer, Newtonsoft.Json.Utilities.MathUtils.Max(), Newtonsoft.Json.Schema.JsonSchema.Maximum, Newtonsoft.Json.Schema.JsonSchemaModel.Maximum, Newtonsoft.Json.Schema.JsonSchema.MaximumItems, Newtonsoft.Json.Schema.JsonSchemaModel.MaximumItems, Newtonsoft.Json.Schema.JsonSchema.MaximumLength, Newtonsoft.Json.Schema.JsonSchemaModel.MaximumLength, Newtonsoft.Json.Utilities.MathUtils.Min(), Newtonsoft.Json.Schema.JsonSchema.Minimum, Newtonsoft.Json.Schema.JsonSchemaModel.Minimum, Newtonsoft.Json.Schema.JsonSchema.MinimumItems, Newtonsoft.Json.Schema.JsonSchemaModel.MinimumItems, Newtonsoft.Json.Schema.JsonSchema.MinimumLength, Newtonsoft.Json.Schema.JsonSchemaModel.MinimumLength, Newtonsoft.Json.Schema.JsonSchema.Pattern, Newtonsoft.Json.Schema.JsonSchemaModel.Patterns, Newtonsoft.Json.Schema.JsonSchema.PositionalItemsValidation, and Newtonsoft.Json.Schema.JsonSchema.UniqueItems.
Referenced by Newtonsoft.Json.Schema.JsonSchemaModel.Create().