Terraria Decompiled: Terraria.GameContent.Events.CultistRitual.CheckRitual
CheckRitual()
static bool Terraria.GameContent.Events.CultistRitual.CheckRitual (int x, int y, bool force = false) inline static private
Definition at line 72 of file CultistRitual.cs.
        {
            if (!force && (CultistRitual.delay != 0 || !Main.hardMode || !NPC.downedGolemBoss || !NPC.downedBoss3))
            {
                return false;
            }
            if (y < 7 || WorldGen.SolidTile(Main.tile[x, y - 7]))
            {
                return false;
            }
            if (!force && NPC.AnyNPCs(437))
            {
                return false;
            }
            Vector2 vector = new Vector2((float)(x * 16 + 8), (float)(y * 16 - 64 - 8 - 27));
            Point[] array = null;
            return CultistRitual.CheckFloor(vector, out array);
        }
References Terraria.NPC.AnyNPCs(), System.array, Terraria.GameContent.Events.CultistRitual.CheckFloor(), Terraria.GameContent.Events.CultistRitual.delay, Terraria.NPC.downedBoss3, Terraria.NPC.downedGolemBoss, Terraria.Main.hardMode, Terraria.WorldGen.SolidTile(), and Terraria.Main.tile.
Referenced by Terraria.GameContent.Events.CultistRitual.TrySpawning().