Terraria Decompiled: Newtonsoft.Json.Schema.JsonSchemaModel.Create
Create()
static JsonSchemaModel Newtonsoft.Json.Schema.JsonSchemaModel.Create (IList< JsonSchema > schemata) inline static
Definition at line 414 of file JsonSchemaModel.cs.
        {
            JsonSchemaModel jsonSchemaModel = new JsonSchemaModel();
            foreach (JsonSchema jsonSchema in schemata)
            {
                JsonSchemaModel.Combine(jsonSchemaModel, jsonSchema);
            }
            return jsonSchemaModel;
        }
References Newtonsoft.Json.Schema.JsonSchemaModel.Combine(), and Newtonsoft.Json.Schema.JsonSchemaModel.JsonSchemaModel().
Referenced by Newtonsoft.Json.Schema.JsonSchemaModelBuilder.BuildNodeModel().