Terraria Decompiled: System.Runtime.Serialization.ObjectManager.ResolveObjectReference
ResolveObjectReference()
bool System.Runtime.Serialization.ObjectManager.ResolveObjectReference (ObjectHolder holder) inline private
Definition at line 196 of file ObjectManager.cs.
        {
            int num = 0;
            try
            {
                object objectValue;
                for (;;)
                {
                    objectValue = holder.ObjectValue;
                    holder.SetObjectValue(((IObjectReference)holder.ObjectValue).GetRealObject(this.m_context), this);
                    if (holder.ObjectValue == null)
                    {
                        break;
                    }
                    if (num++ == 100)
                    {
                        goto Block_3;
                    }
                    if (!(holder.ObjectValue is IObjectReference) || objectValue == holder.ObjectValue)
                    {
                        goto IL_0069;
                    }
                }
                holder.SetObjectValue(objectValue, this);
                return false;
                Block_3:
                throw new SerializationException(Environment.GetResourceString("The implementation of the IObjectReference interface returns too many nested references to other objects that implement IObjectReference."));
                IL_0069:;
            }
            catch (NullReferenceException)
            {
                return false;
            }
            holder.IsIncompleteObjectReference = false;
            this.DoNewlyRegisteredObjectFixups(holder);
            return true;
        }
References System.Runtime.Serialization.ObjectManager.DoNewlyRegisteredObjectFixups(), System.Environment.GetResourceString(), System.Runtime.Serialization.ObjectHolder.ObjectValue, and System.Runtime.Serialization.ObjectHolder.SetObjectValue().