Terraria Decompiled: System.Runtime.Serialization.ObjectManager.AddObjectHolder
AddObjectHolder()
void System.Runtime.Serialization.ObjectManager.AddObjectHolder (ObjectHolder holder) inline private
Definition at line 105 of file ObjectManager.cs.
        {
            if (holder.m_id >= (long)this.m_objects.Length && this.m_objects.Length != 4096)
            {
                int num = 4096;
                if (holder.m_id < 2048L)
                {
                    num = this.m_objects.Length * 2;
                    while ((long)num <= holder.m_id && num < 4096)
                    {
                        num *= 2;
                    }
                    if (num > 4096)
                    {
                        num = 4096;
                    }
                }
                ObjectHolder[] array = new ObjectHolder[num];
                Array.Copy(this.m_objects, array, this.m_objects.Length);
                this.m_objects = array;
            }
            int num2 = (int)(holder.m_id & 4095L);
            ObjectHolder objectHolder = this.m_objects[num2];
            holder.m_next = objectHolder;
            this.m_objects[num2] = holder;
        }
References System.array, System.Array.Copy(), int, System.L, System.Runtime.Serialization.ObjectHolder.m_id, and System.Runtime.Serialization.ObjectManager.m_objects.
Referenced by System.Runtime.Serialization.ObjectManager.FindOrCreateObjectHolder(), System.Runtime.Serialization.ObjectManager.RegisterObject(), and System.Runtime.Serialization.ObjectManager.RegisterString().