Terraria Decompiled: System.Runtime.Serialization.ObjectManager.DoFixups
DoFixups()
virtual void System.Runtime.Serialization.ObjectManager.DoFixups () inline virtual
Definition at line 642 of file ObjectManager.cs.
        {
            int num = -1;
            while (num != 0)
            {
                num = 0;
                ObjectHolderListEnumerator fixupEnumerator = this.SpecialFixupObjects.GetFixupEnumerator();
                while (fixupEnumerator.MoveNext())
                {
                    ObjectHolder objectHolder = fixupEnumerator.Current;
                    if (objectHolder.ObjectValue == null)
                    {
                        throw new SerializationException(Environment.GetResourceString("The object with ID {0} was referenced in a fixup but does not exist.", new object[] { objectHolder.m_id }));
                    }
                    if (objectHolder.TotalDependentObjects == 0)
                    {
                        if (objectHolder.RequiresSerInfoFixup)
{
                            this.FixupSpecialObject(objectHolder);
                            num++;
                        }
                        else if (!objectHolder.IsIncompleteObjectReference)
{
                            this.CompleteObject(objectHolder, true);
                        }
                        if (objectHolder.IsIncompleteObjectReference && this.ResolveObjectReference(objectHolder))
{
                            num++;
                        }
                    }
                }
            }
            if (this.m_fixupCount != 0L)
            {
                for (int i = 0; i < this.m_objects.Length; i++)
                {
                    for (ObjectHolder objectHolder = this.m_objects[i]; objectHolder != null; objectHolder = objectHolder.m_next)
                    {
                        if (objectHolder.TotalDependentObjects > 0)
{
                            this.CompleteObject(objectHolder, true);
                        }
                    }
                    if (this.m_fixupCount == 0L)
                    {
                        return;
                    }
                }
                throw new SerializationException(Environment.GetResourceString("The ObjectManager found an invalid number of fixups. This usually indicates a problem in the Formatter."));
            }
            if (this.TopObject is TypeLoadExceptionHolder)
            {
                throw new SerializationException(Environment.GetResourceString("Unable to load type {0} required for deserialization.", new object[] { ((TypeLoadExceptionHolder)this.TopObject).TypeName }));
            }
        }
References System.Runtime.Serialization.ObjectManager.CompleteObject(), System.Runtime.Serialization.ObjectHolderListEnumerator.Current, System.Runtime.Serialization.ObjectManager.FixupSpecialObject(), System.Runtime.Serialization.ObjectHolderList.GetFixupEnumerator(), System.Environment.GetResourceString(), System.Runtime.Serialization.ObjectHolder.IsIncompleteObjectReference, System.L, System.Runtime.Serialization.ObjectManager.m_fixupCount, System.Runtime.Serialization.ObjectHolder.m_next, System.Runtime.Serialization.ObjectManager.m_objects, System.Runtime.Serialization.ObjectHolderListEnumerator.MoveNext(), System.Runtime.Serialization.ObjectHolder.ObjectValue, System.Runtime.Serialization.ObjectHolder.RequiresSerInfoFixup, System.Runtime.Serialization.ObjectManager.SpecialFixupObjects, System.Runtime.Serialization.ObjectManager.TopObject, and System.Runtime.Serialization.ObjectHolder.TotalDependentObjects.
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize().