Terraria Decompiled: System.Runtime.Serialization.ObjectManager.CompleteObject
CompleteObject()
void System.Runtime.Serialization.ObjectManager.CompleteObject (ObjectHolder holder, bool bObjectFullyComplete) inline package
Definition at line 331 of file ObjectManager.cs.
        {
            FixupHolderList missingElements = holder.m_missingElements;
            object obj = null;
            ObjectHolder objectHolder = null;
            int num = 0;
            if (holder.ObjectValue == null)
            {
                throw new SerializationException(Environment.GetResourceString("The object with ID {0} was referenced in a fixup but has not been registered.", new object[] { holder.m_id }));
            }
            if (missingElements == null)
            {
                return;
            }
            if (holder.HasSurrogate || holder.HasISerializable)
            {
                SerializationInfo serInfo = holder.m_serInfo;
                if (serInfo == null)
                {
                    throw new SerializationException(Environment.GetResourceString("A fixup on an object implementing ISerializable or having a surrogate was discovered for an object which does not have a SerializationInfo available."));
                }
                if (missingElements != null)
                {
                    for (int i = 0; i < missingElements.m_count; i++)
                    {
                        if (missingElements.m_values[i] != null && this.GetCompletionInfo(missingElements.m_values[i], out objectHolder, out obj, bObjectFullyComplete))
{
                            object objectValue = objectHolder.ObjectValue;
                            if (this.CanCallGetType(objectValue))
{
                                serInfo.UpdateValue((string)obj, objectValue, objectValue.GetType());
                            }
                            else
{
                                serInfo.UpdateValue((string)obj, objectValue, typeof(MarshalByRefObject));
                            }
                            num++;
                            missingElements.m_values[i] = null;
                            if (!bObjectFullyComplete)
{
                                holder.DecrementFixupsRemaining(this);
                                objectHolder.RemoveDependency(holder.m_id);
                            }
                        }
                    }
                }
            }
            else
            {
                for (int j = 0; j < missingElements.m_count; j++)
                {
                    FixupHolder fixupHolder = missingElements.m_values[j];
                    if (fixupHolder != null && this.GetCompletionInfo(fixupHolder, out objectHolder, out obj, bObjectFullyComplete))
                    {
                        if (objectHolder.TypeLoadExceptionReachable)
{
                            holder.TypeLoadException = objectHolder.TypeLoadException;
                            if (holder.Reachable)
{
                                throw new SerializationException(Environment.GetResourceString("Unable to load type {0} required for deserialization.", new object[] { holder.TypeLoadException.TypeName }));
                            }
                        }
                        if (holder.Reachable)
{
                            objectHolder.Reachable = true;
                        }
                        int fixupType = fixupHolder.m_fixupType;
                        if (fixupType != 1)
{
                            if (fixupType != 2)
{
                                throw new SerializationException(Environment.GetResourceString("Cannot perform fixup."));
                            }
                            MemberInfo memberInfo = (MemberInfo)obj;
                            if (memberInfo.MemberType != MemberTypes.Field)
{
                                throw new SerializationException(Environment.GetResourceString("Cannot perform fixup."));
                            }
                            if (holder.RequiresValueTypeFixup && holder.ValueTypeFixupPerformed)
{
                                if (!this.DoValueTypeFixup((FieldInfo)memberInfo, holder, objectHolder.ObjectValue))
{
                                    throw new SerializationException(Environment.GetResourceString("Fixing up a partially available ValueType chain is not implemented."));
                                }
                            }
                            else
{
                                FormatterServices.SerializationSetValue(memberInfo, holder.ObjectValue, objectHolder.ObjectValue);
                            }
                            if (objectHolder.RequiresValueTypeFixup)
{
                                objectHolder.ValueTypeFixupPerformed = true;
                            }
                        }
                        else
{
                            if (holder.RequiresValueTypeFixup)
{
                                throw new SerializationException(Environment.GetResourceString("ValueType fixup on Arrays is not implemented."));
                            }
                            ((Array)holder.ObjectValue).SetValue(objectHolder.ObjectValue, (int[])obj);
                        }
                        num++;
                        missingElements.m_values[j] = null;
                        if (!bObjectFullyComplete)
{
                            holder.DecrementFixupsRemaining(this);
                            objectHolder.RemoveDependency(holder.m_id);
                        }
                    }
                }
            }
            this.m_fixupCount -= (long)num;
            if (missingElements.m_count == num)
            {
                holder.m_missingElements = null;
            }
        }
References System.Reflection.Array, System.Runtime.Serialization.ObjectManager.CanCallGetType(), System.Runtime.Serialization.ObjectHolder.DecrementFixupsRemaining(), System.Runtime.Serialization.ObjectManager.DoValueTypeFixup(), System.Runtime.Serialization.ObjectManager.GetCompletionInfo(), System.Environment.GetResourceString(), System.Runtime.Serialization.ObjectHolder.HasISerializable, System.Runtime.Serialization.ObjectHolder.HasSurrogate, long, System.Runtime.Serialization.FixupHolderList.m_count, System.Runtime.Serialization.FixupHolder.m_fixupType, System.Runtime.Serialization.ObjectHolder.m_id, System.Runtime.Serialization.ObjectHolder.m_missingElements, System.Runtime.Serialization.ObjectHolder.m_serInfo, System.Runtime.Serialization.FixupHolderList.m_values, System.Reflection.MemberInfo.MemberType, System.obj, System.Runtime.Serialization.ObjectHolder.ObjectValue, System.Runtime.Serialization.ObjectHolder.Reachable, System.Runtime.Serialization.ObjectHolder.RequiresValueTypeFixup, System.Runtime.Serialization.FormatterServices.SerializationSetValue(), System.Runtime.Serialization.SerializationInfo.UpdateValue(), and System.Runtime.Serialization.ObjectHolder.ValueTypeFixupPerformed.
Referenced by System.Runtime.Serialization.ObjectManager.DoFixups(), System.Runtime.Serialization.ObjectManager.DoNewlyRegisteredObjectFixups(), System.Runtime.Serialization.ObjectManager.RegisterObject(), and System.Runtime.Serialization.ObjectHolder.SetObjectValue().