Terraria Decompiled: System.Runtime.Serialization.ObjectManager.FindObjectHolder
FindObjectHolder()
ObjectHolder System.Runtime.Serialization.ObjectManager.FindObjectHolder (long objectID) inline package
Definition at line 74 of file ObjectManager.cs.
        {
            int num = (int)(objectID & 4095L);
            if (num >= this.m_objects.Length)
            {
                return null;
            }
            ObjectHolder objectHolder;
            for (objectHolder = this.m_objects[num]; objectHolder != null; objectHolder = objectHolder.m_next)
            {
                if (objectHolder.m_id == objectID)
                {
                    return objectHolder;
                }
            }
            return objectHolder;
        }
References int, System.L, System.Runtime.Serialization.ObjectHolder.m_id, System.Runtime.Serialization.ObjectHolder.m_next, and System.Runtime.Serialization.ObjectManager.m_objects.
Referenced by System.Runtime.Serialization.ObjectManager.DoNewlyRegisteredObjectFixups(), System.Runtime.Serialization.ObjectManager.DoValueTypeFixup(), System.Runtime.Serialization.ObjectManager.FindOrCreateObjectHolder(), System.Runtime.Serialization.ObjectManager.GetCompletionInfo(), System.Runtime.Serialization.ObjectManager.GetObject(), and System.Runtime.Serialization.ObjectManager.RegisterObject().