Terraria Decompiled: System.Runtime.Serialization.ObjectManager.FixupSpecialObject
FixupSpecialObject()
void System.Runtime.Serialization.ObjectManager.FixupSpecialObject (ObjectHolder holder) inline private
Definition at line 163 of file ObjectManager.cs.
        {
            ISurrogateSelector surrogateSelector = null;
            if (holder.HasSurrogate)
            {
                ISerializationSurrogate surrogate = holder.Surrogate;
                object obj = surrogate.SetObjectData(holder.ObjectValue, holder.SerializationInfo, this.m_context, surrogateSelector);
                if (obj != null)
                {
                    if (!holder.CanSurrogatedObjectValueChange && obj != holder.ObjectValue)
                    {
                        throw new SerializationException(string.Format(CultureInfo.CurrentCulture, Environment.GetResourceString("{0}.SetObjectData returns a value that is neither null nor equal to the first parameter. Such Surrogates cannot be part of cyclical reference."), surrogate.GetType().FullName));
                    }
                    holder.SetObjectValue(obj, this);
                }
                holder.m_surrogate = null;
                holder.SetFlags();
            }
            else
            {
                this.CompleteISerializableObject(holder.ObjectValue, holder.SerializationInfo, this.m_context);
            }
            holder.SerializationInfo = null;
            holder.RequiresSerInfoFixup = false;
            if (holder.RequiresValueTypeFixup && holder.ValueTypeFixupPerformed)
            {
                this.DoValueTypeFixup(null, holder, holder.ObjectValue);
            }
            this.DoNewlyRegisteredObjectFixups(holder);
        }
References System.Runtime.Serialization.ObjectHolder.CanSurrogatedObjectValueChange, System.Runtime.Serialization.ObjectManager.CompleteISerializableObject(), System.Globalization.CultureInfo.CurrentCulture, System.Runtime.Serialization.ObjectManager.DoNewlyRegisteredObjectFixups(), System.Runtime.Serialization.ObjectManager.DoValueTypeFixup(), System.Format, System.Environment.GetResourceString(), System.Runtime.Serialization.ObjectHolder.HasSurrogate, System.obj, System.Runtime.Serialization.ObjectHolder.ObjectValue, System.Runtime.Serialization.ObjectHolder.RequiresValueTypeFixup, System.Runtime.Serialization.ObjectHolder.SerializationInfo, System.Runtime.Serialization.ObjectHolder.SetFlags(), System.Runtime.Serialization.ISerializationSurrogate.SetObjectData(), System.Runtime.Serialization.ObjectHolder.SetObjectValue(), System.Runtime.Serialization.ObjectHolder.Surrogate, and System.Runtime.Serialization.ObjectHolder.ValueTypeFixupPerformed.
Referenced by System.Runtime.Serialization.ObjectManager.DoFixups().