Terraria Decompiled: System.Runtime.Serialization.ObjectManager.DoNewlyRegisteredObjectFixups
DoNewlyRegisteredObjectFixups()
void System.Runtime.Serialization.ObjectManager.DoNewlyRegisteredObjectFixups (ObjectHolder holder) inline private
Definition at line 452 of file ObjectManager.cs.
        {
            if (holder.CanObjectValueChange)
            {
                return;
            }
            LongList dependentObjects = holder.DependentObjects;
            if (dependentObjects == null)
            {
                return;
            }
            dependentObjects.StartEnumeration();
            while (dependentObjects.MoveNext())
            {
                long num = dependentObjects.Current;
                ObjectHolder objectHolder = this.FindObjectHolder(num);
                objectHolder.DecrementFixupsRemaining(this);
                if (objectHolder.DirectlyDependentObjects == 0)
                {
                    if (objectHolder.ObjectValue != null)
                    {
                        this.CompleteObject(objectHolder, true);
                    }
                    else
                    {
                        objectHolder.MarkForCompletionWhenAvailable();
                    }
                }
            }
        }
References System.Runtime.Serialization.ObjectHolder.CanObjectValueChange, System.Runtime.Serialization.ObjectManager.CompleteObject(), System.Runtime.Serialization.LongList.Current, System.Runtime.Serialization.ObjectHolder.DecrementFixupsRemaining(), System.Runtime.Serialization.ObjectHolder.DependentObjects, System.Runtime.Serialization.ObjectHolder.DirectlyDependentObjects, System.Runtime.Serialization.ObjectManager.FindObjectHolder(), System.Runtime.Serialization.ObjectHolder.MarkForCompletionWhenAvailable(), System.Runtime.Serialization.LongList.MoveNext(), System.Runtime.Serialization.ObjectHolder.ObjectValue, and System.Runtime.Serialization.LongList.StartEnumeration().
Referenced by System.Runtime.Serialization.ObjectManager.FixupSpecialObject(), System.Runtime.Serialization.ObjectManager.RegisterObject(), and System.Runtime.Serialization.ObjectManager.ResolveObjectReference().