Terraria Decompiled: System.Runtime.Serialization.ObjectManager.DoValueTypeFixup
DoValueTypeFixup()
bool System.Runtime.Serialization.ObjectManager.DoValueTypeFixup (FieldInfo memberToFix, ObjectHolder holder, object value) inline private
Definition at line 236 of file ObjectManager.cs.
        {
            FieldInfo[] array = new FieldInfo[4];
            int num = 0;
            int[] array2 = null;
            object obj = holder.ObjectValue;
            while (holder.RequiresValueTypeFixup)
            {
                if (num + 1 >= array.Length)
                {
                    FieldInfo[] array3 = new FieldInfo[array.Length * 2];
                    Array.Copy(array, array3, array.Length);
                    array = array3;
                }
                ValueTypeFixupInfo valueFixup = holder.ValueFixup;
                obj = holder.ObjectValue;
                if (valueFixup.ParentField != null)
                {
                    FieldInfo parentField = valueFixup.ParentField;
                    ObjectHolder objectHolder = this.FindObjectHolder(valueFixup.ContainerID);
                    if (objectHolder.ObjectValue == null)
                    {
                        break;
                    }
                    if (Nullable.GetUnderlyingType(parentField.FieldType) != null)
                    {
                        array[num] = parentField.FieldType.GetField("value", BindingFlags.Instance | BindingFlags.NonPublic);
                        num++;
                    }
                    array[num] = parentField;
                    holder = objectHolder;
                    num++;
                }
                else
                {
                    holder = this.FindObjectHolder(valueFixup.ContainerID);
                    array2 = valueFixup.ParentIndex;
                    if (holder.ObjectValue == null)
                    {
                        break;
                    }
                    break;
                }
            }
            if (!(holder.ObjectValue is Array) && holder.ObjectValue != null)
            {
                obj = holder.ObjectValue;
            }
            if (num != 0)
            {
                FieldInfo[] array4 = new FieldInfo[num];
                for (int i = 0; i < num; i++)
                {
                    FieldInfo fieldInfo = array[num - 1 - i];
                    SerializationFieldInfo serializationFieldInfo = fieldInfo as SerializationFieldInfo;
                    array4[i] = ((serializationFieldInfo == null) ? fieldInfo : serializationFieldInfo.FieldInfo);
                }
                TypedReference typedReference = TypedReference.MakeTypedReference(obj, array4);
                if (memberToFix != null)
                {
                    ((RuntimeFieldInfo)memberToFix).SetValueDirect(typedReference, value);
                }
                else
                {
                    TypedReference.SetTypedReference(typedReference, value);
                }
            }
            else if (memberToFix != null)
            {
                FormatterServices.SerializationSetValue(memberToFix, obj, value);
            }
            if (array2 != null && holder.ObjectValue != null)
            {
                ((Array)holder.ObjectValue).SetValue(obj, array2);
            }
            return true;
        }
References System.array, System.Reflection.Array, System.Runtime.Serialization.ValueTypeFixupInfo.ContainerID, System.Array.Copy(), System.Runtime.Serialization.SerializationFieldInfo.FieldInfo, System.Reflection.FieldInfo.FieldType, System.Runtime.Serialization.ObjectManager.FindObjectHolder(), System.Type.GetField(), System.Nullable< T >.GetUnderlyingType(), System.TypedReference.MakeTypedReference(), System.obj, System.Runtime.Serialization.ObjectHolder.ObjectValue, System.Runtime.Serialization.ValueTypeFixupInfo.ParentField, System.Runtime.Serialization.ValueTypeFixupInfo.ParentIndex, System.Runtime.Serialization.ObjectHolder.RequiresValueTypeFixup, System.Runtime.Serialization.FormatterServices.SerializationSetValue(), System.TypedReference.SetTypedReference(), System.value, and System.Runtime.Serialization.ObjectHolder.ValueFixup.
Referenced by System.Runtime.Serialization.ObjectManager.CompleteObject(), and System.Runtime.Serialization.ObjectManager.FixupSpecialObject().