Terraria Decompiled: System.Runtime.Serialization.ObjectManager.RecordDelayedFixup
RecordDelayedFixup()
virtual void System.Runtime.Serialization.ObjectManager.RecordDelayedFixup (long objectToBeFixed, string memberName, long objectRequired) inline virtual
Definition at line 731 of file ObjectManager.cs.
        {
            if (objectToBeFixed <= 0L || objectRequired <= 0L)
            {
                throw new ArgumentOutOfRangeException((objectToBeFixed <= 0L) ? "objectToBeFixed" : "objectRequired", Environment.GetResourceString("Object IDs must be greater than zero."));
            }
            if (memberName == null)
            {
                throw new ArgumentNullException("memberName");
            }
            FixupHolder fixupHolder = new FixupHolder(objectRequired, memberName, 4);
            this.RegisterFixup(fixupHolder, objectToBeFixed, objectRequired);
        }
References System.Environment.GetResourceString(), System.L, and System.Runtime.Serialization.ObjectManager.RegisterFixup().
Referenced by System.Runtime.Serialization.Formatters.Binary.ValueFixup.Fixup(), and System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.RecordFixup().