Terraria Decompiled: System.Runtime.Serialization.ObjectManager.RegisterObject
RegisterObject() [4/4]
void System.Runtime.Serialization.ObjectManager.RegisterObject (object obj, long objectID, SerializationInfo info, long idOfContainingObj, MemberInfo member, int[] arrayIndex) inline
Definition at line 528 of file ObjectManager.cs.
        {
            if (obj == null)
            {
                throw new ArgumentNullException("obj");
            }
            if (objectID <= 0L)
            {
                throw new ArgumentOutOfRangeException("objectID", Environment.GetResourceString("objectID cannot be less than or equal to zero."));
            }
            if (member != null && !(member is RuntimeFieldInfo) && !(member is SerializationFieldInfo))
            {
                throw new SerializationException(Environment.GetResourceString("Only FieldInfo, PropertyInfo, and SerializationMemberInfo are recognized."));
            }
            ISerializationSurrogate serializationSurrogate = null;
            if (this.m_selector != null)
            {
                Type type;
                if (this.CanCallGetType(obj))
                {
                    type = obj.GetType();
                }
                else
                {
                    type = typeof(MarshalByRefObject);
                }
                ISurrogateSelector surrogateSelector;
                serializationSurrogate = this.m_selector.GetSurrogate(type, this.m_context, out surrogateSelector);
            }
            if (obj is IDeserializationCallback)
            {
                DeserializationEventHandler deserializationEventHandler = new DeserializationEventHandler(((IDeserializationCallback)obj).OnDeserialization);
                this.AddOnDeserialization(deserializationEventHandler);
            }
            if (arrayIndex != null)
            {
                arrayIndex = (int[])arrayIndex.Clone();
            }
            ObjectHolder objectHolder = this.FindObjectHolder(objectID);
            if (objectHolder == null)
            {
                objectHolder = new ObjectHolder(obj, objectID, info, serializationSurrogate, idOfContainingObj, (FieldInfo)member, arrayIndex);
                this.AddObjectHolder(objectHolder);
                if (objectHolder.RequiresDelayedFixup)
                {
                    this.SpecialFixupObjects.Add(objectHolder);
                }
                this.AddOnDeserialized(obj);
                return;
            }
            if (objectHolder.ObjectValue != null)
            {
                throw new SerializationException(Environment.GetResourceString("An object cannot be registered twice."));
            }
            objectHolder.UpdateData(obj, info, serializationSurrogate, idOfContainingObj, (FieldInfo)member, arrayIndex, this);
            if (objectHolder.DirectlyDependentObjects > 0)
            {
                this.CompleteObject(objectHolder, false);
            }
            if (objectHolder.RequiresDelayedFixup)
            {
                this.SpecialFixupObjects.Add(objectHolder);
            }
            if (objectHolder.CompletelyFixed)
            {
                this.DoNewlyRegisteredObjectFixups(objectHolder);
                objectHolder.DependentObjects = null;
            }
            if (objectHolder.TotalDependentObjects > 0)
            {
                this.AddOnDeserialized(obj);
                return;
            }
            this.RaiseOnDeserializedEvent(obj);
        }
References System.Runtime.Serialization.ObjectHolderList.Add(), System.Runtime.Serialization.ObjectManager.AddObjectHolder(), System.Runtime.Serialization.ObjectManager.AddOnDeserialization(), System.Runtime.Serialization.ObjectManager.AddOnDeserialized(), System.arrayIndex, System.Runtime.Serialization.ObjectManager.CanCallGetType(), System.Runtime.Serialization.ObjectHolder.CompletelyFixed, System.Runtime.Serialization.ObjectManager.CompleteObject(), System.Runtime.Serialization.DeserializationEventHandler(), System.Runtime.Serialization.ObjectHolder.DirectlyDependentObjects, System.Runtime.Serialization.ObjectManager.DoNewlyRegisteredObjectFixups(), System.Runtime.Serialization.ObjectManager.FindObjectHolder(), System.Environment.GetResourceString(), System.Runtime.Serialization.ISurrogateSelector.GetSurrogate(), System.Type.GetType(), System.info, System.L, System.Runtime.Serialization.ObjectManager.m_context, System.Runtime.Serialization.ObjectManager.m_selector, System.obj, System.Runtime.Serialization.ObjectHolder.ObjectValue, System.Runtime.Serialization.ObjectManager.RaiseOnDeserializedEvent(), System.Runtime.Serialization.ObjectHolder.RequiresDelayedFixup, System.Runtime.Serialization.ObjectManager.SpecialFixupObjects, System.Runtime.Serialization.ObjectHolder.TotalDependentObjects, and System.Runtime.Serialization.ObjectHolder.UpdateData().