Terraria Decompiled: System.Array.Copy
Copy() [2/4]
static void System.Array.Copy (Array sourceArray, Array destinationArray, long length) inline static
Definition at line 264 of file Array.cs.
        {
            if (length > 2147483647L || length < -2147483648L)
            {
                throw new ArgumentOutOfRangeException("length", "Arrays larger than 2GB are not supported.");
            }
            Array.Copy(sourceArray, destinationArray, (int)length);
        }
References System.Array.Copy(), System.L, and System.length.
Referenced by Ionic.Zlib.DeflateManager._fillWindow(), Mono.DataConverter.PackContext.Add(), System.Threading.ThreadPoolWorkQueue.SparseArray< T >.Add(), System.Reflection.Emit.ILExceptionInfo.add_block(), System.Security.Cryptography.CryptoConfig.AddAlgorithm(), System.Security.Policy.NetCodeGroup.AddConnectAccess(), System.Reflection.Emit.ModuleBuilder.addGlobalMethod(), System.Runtime.Serialization.ObjectManager.AddObjectHolder(), System.Text.EncodingProvider.AddProvider(), System.Reflection.Emit.DynamicMethod.AddRef(), System.Reflection.Emit.AssemblyBuilder.AddResourceFile(), System.Reflection.Emit.SequencePointList.AddSequencePoint(), System.Reflection.Emit.ModuleBuilder.AddType(), System.Reflection.Emit.AssemblyBuilder.AddUnmanagedResource(), System.Security.SecureString.Alloc(), System.Collections.Generic.LargeArrayBuilder< T >.AllocateBuffer(), System.LocalDataStoreMgr.AllocateDataSlot(), Terraria.Modules.AnchorTypesModule.AnchorTypesModule(), Newtonsoft.Json.Utilities.StringBuffer.Append(), System.Reflection.Emit.TypeBuilder.append_method(), System.Reflection.Emit.SignatureHelper.AppendArray(), System.Reflection.Emit.SignatureHelper.AppendArrayAt(), Mono.Globalization.Unicode.SortKeyBuffer.AppendBufferPrimitive(), System.Reflection.Emit.ILGenerator.BeginExceptionBlock(), Terraria.Net.Sockets.DebugNetworkStream.BeginRead(), System.DefaultBinder.BindToMethod(), System.Collections.BitArray.BitArray(), System.Collections.BitArray.BitArray(), Terraria.Player.clientClone(), System.Collections.ArrayList.Clone(), System.Collections.Queue.Clone(), System.Collections.SortedList.Clone(), System.Collections.Stack.Clone(), System.MulticastDelegate.CombineImpl(), System.Security.AccessControl.CommonAce.CommonAce(), Mono.Globalization.Unicode.CodePointIndexer.CompressArray(), System.Array.ConstrainedCopy(), Ionic.Zip.ZipEntry.ConstructExtraField(), System.Reflection.Emit.ConstructorBuilder.ConstructorBuilder(), System.Array.Copy(), System.Array.Copy(), System.Array.Copy(), Terraria.Projectile.CopyLocalNPCImmunityTo(), Terraria.Net.Sockets.DebugNetworkStream.Packet.CopyOfSlice(), System.Collections.ArrayList.CopyTo(), System.Collections.Generic.List< T >.CopyTo(), System.Collections.Generic.Stack< T >.CopyTo(), System.Collections.SortedList.KeyList.CopyTo(), System.Collections.SortedList.ValueList.CopyTo(), System.Array.CopyTo(), System.Collections.BitArray.CopyTo(), System.Collections.Generic.Queue< T >.CopyTo(), System.Collections.Queue.CopyTo(), System.Collections.ArrayList.CopyTo(), System.Collections.Generic.List< T >.CopyTo(), System.Collections.Generic.LowLevelList< T >.CopyTo(), NVorbis.Memory< T >.CopyTo(), System.RuntimeType.ListBuilder< T >.CopyTo(), System.Collections.Generic.List< T >.CopyTo(), System.Collections.Generic.LowLevelList< T >.CopyTo(), System.Collections.Generic.Queue< T >.CopyTo(), System.Collections.Generic.LargeArrayBuilder< T >.CopyTo(), Mono.Security.Cryptography.MACAlgorithm.Core(), System.Reflection.Emit.MethodBuilder.CreateMethodBody(), Mono.Security.Cryptography.DSAManaged.CreateSignature(), BCrypt.Net.BCrypt.CryptRaw(), System.Reflection.Emit.ILGenerator.DeclareLocal(), System.Reflection.Emit.TypeBuilder.DefineConstructor(), System.Reflection.Emit.ModuleBuilder.DefineDataImpl(), System.Reflection.Emit.AssemblyBuilder.DefineDynamicModule(), System.Reflection.Emit.TypeBuilder.DefineEvent(), System.Reflection.Emit.TypeBuilder.DefineField(), System.Reflection.Emit.ILGenerator.DefineLabel(), System.Reflection.Emit.ModuleBuilder.DefineManifestResource(), System.Reflection.Emit.TypeBuilder.DefineNestedType(), System.Reflection.Emit.ModuleBuilder.DefineResource(), System.Runtime.Remoting.Channels.CADSerializer.DeserializeObjectSafe(), System.Runtime.Serialization.ObjectManager.DoValueTypeFixup(), System.Delegate.DynamicInvokeImpl(), System.Reflection.Emit.AssemblyBuilder.EmbedResourceFile(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), Ionic.Zlib.GZipStream.EmitHeader(), System.Runtime.Serialization.FixupHolderList.EnlargeArray(), System.Runtime.Serialization.LongList.EnlargeArray(), System.Runtime.Serialization.ObjectHolderList.EnlargeArray(), System.Collections.Generic.ArrayBuilder< T >.EnsureCapacity(), Newtonsoft.Json.Utilities.StringBuffer.EnsureSize(), System.Runtime.ExceptionServices.ExceptionDispatchInfo.ExceptionDispatchInfo(), System.Runtime.Serialization.SerializationInfo.ExpandArrays(), System.Reflection.Emit.MethodBuilder.ExtendArray< T >(), Ionic.Zlib.ZlibBaseStream.finish(), Ionic.Zlib.InflateBlocks.Flush(), Ionic.Zlib.ZlibCodec.flush_pending(), System.Collections.Generic.LargeArrayBuilder< T >.g__CopyToCore(), Ionic.Zip.ZipOutput.GenCentralDirectoryFooter(), Mono.Security.Cryptography.DSAManaged.GenerateParams(), Ionic.Zip.ZipOutput.GenZip64EndOfCentralDirectory(), Mono.DataConverter.PackContext.Get(), System.Runtime.Remoting.Messaging.CADMethodCallMessage.GetArguments(), System.Runtime.Remoting.Messaging.CADMethodReturnMessage.GetArguments(), System.Security.AccessControl.CommonAce.GetBinaryForm(), System.Security.AccessControl.ObjectAce.GetBinaryForm(), System.Security.Principal.SecurityIdentifier.GetBinaryForm(), System.Security.Cryptography.RandomNumberGenerator.GetBytes(), System.MonoCustomAttrs.GetCustomAttributesBase(), System.MonoCustomAttrs.GetCustomAttributesDataBase(), Terraria.Social.Steam.AchievementsSocialModule.GetEncryptionKey(), Terraria.Social.WeGame.AchievementsSocialModule.GetEncryptionKey(), System.RuntimeType.GetEnumNames(), Terraria.Social.Steam.Lobby.GetMessage(), System.Runtime.Serialization.FormatterServices.GetParentTypes(), System.Collections.Generic.List< T >.GetRange(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.GetRenderTargets(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.GetRenderTargetsNoAllocEXT(), Mono.Globalization.Unicode.SortKeyBuffer.GetResult(), Newtonsoft.Json.Bson.BsonReader.GetString(), System.Reflection.Emit.ModuleBuilder.GetTypes(), System.Reflection.Emit.AssemblyBuilder.GetTypes(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.GetVertexBuffers(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.GrowTable(), System.Security.SecurityDocument.GuaranteeSize(), Ionic.Zlib.InfTree.huft_build(), System.Runtime.Serialization.Formatters.Binary.SerStack.IncreaseCapacity(), System.Runtime.Serialization.Formatters.Binary.IntSizedArray.IncreaseCapacity(), System.Runtime.Serialization.Formatters.Binary.SizedArray.IncreaseCapacity(), Ionic.Zlib.InflateCodes.InflateFast(), BCrypt.Net.BCrypt.InitializeKey(), NVorbis.Codebook.InitTree(), System.Collections.SortedList.Insert(), System.Collections.ArrayList.Insert(), System.Collections.Generic.List< T >.Insert(), System.Collections.Generic.LowLevelList< T >.Insert(), System.Collections.ArrayList.InsertRange(), System.Collections.Generic.List< T >.InsertRange(), System.Collections.Generic.LowLevelList< T >.InsertRange(), System.Array.InternalArray__ICollection_CopyTo< T >(), System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers(), System.Collections.BitArray.LeftShift(), System.Reflection.Emit.ILGenerator.make_room(), System.Reflection.Emit.MethodBuilder.MethodBuilder(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.NextRectangleMap(), Mono.Security.Cryptography.DSAManaged.NormalizeArray(), System.Security.AccessControl.ObjectAce.ObjectAce(), Terraria.Social.Steam.NetServerSocialModule.OnPacketRead(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseArrayMember(), System.Globalization.StringInfo.ParseCombiningCharacters(), System.LocalDataStore.PopulateElement(), Ionic.Zip.ZipEntry.PostProcessOutput(), Ionic.Zlib.InflateBlocks.Process(), System.Reflection.Emit.PropertyBuilder.PropertyBuilder(), System.Collections.Stack.Push(), System.ParameterizedStrings.LowLevelStack.Push(), Ionic.Zlib.DeflateManager.put_bytes(), Terraria.Social.Steam.SteamP2PWriter.QueueSend(), Terraria.Social.WeGame.WeGameP2PWriter.QueueSend(), XPT.Core.Audio.MP3Sharp.Buffer16BitStereo.Read(), Ionic.Zlib.ZlibCodec.read_buf(), System.Resources.Win32ResFileReader.read_ordinal(), System.Security.AccessControl.ObjectAce.ReadGuid(), Mono.Xml.SmallXmlParser.ReadName(), Newtonsoft.Json.Bson.BsonReader.ReadString(), Terraria.Social.Steam.SteamP2PReader.Receive(), Terraria.Social.WeGame.WeGameP2PReader.Receive(), System.Collections.ArrayList.RemoveAt(), System.Collections.Generic.List< T >.RemoveAt(), System.Collections.Generic.LowLevelList< T >.RemoveAt(), System.Collections.SortedList.RemoveAt(), System.MulticastDelegate.RemoveImpl(), System.Collections.ArrayList.RemoveRange(), System.Collections.Generic.List< T >.RemoveRange(), System.DefaultBinder.ReorderArgumentArray(), System.Collections.Generic.Dictionary< TKey, TValue >.Resize(), System.Array.Resize< T >(), Terraria.WorldGen.RestoreTemporaryStateChanges(), System.Collections.BitArray.RightShift(), System.Security.Cryptography.RijndaelManagedTransform.RijndaelManagedTransform(), System.Threading.AsyncLocalValueMap.MultiElementAsyncLocalValueMap.Set(), System.Collections.Generic.Queue< T >.SetCapacity(), System.Collections.Queue.SetCapacity(), Ionic.Zlib.InflateBlocks.SetDictionary(), Ionic.Zlib.DeflateManager.SetDictionary(), System.Reflection.Emit.MethodBuilder.SetParameters(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetRenderTargets(), Terraria.Utils.Shift< T >(), Terraria.Modules.TileObjectCoordinatesModule.TileObjectCoordinatesModule(), System.Collections.ArrayList.ToArray(), System.Collections.ArrayList.Range.ToArray(), System.Collections.Generic.ArrayBuilder< T >.ToArray(), System.Collections.Generic.List< T >.ToArray(), System.Collections.Generic.LowLevelList< T >.ToArray(), System.Collections.Generic.Queue< T >.ToArray(), System.Collections.Queue.ToArray(), System.Collections.ArrayList.ToArray(), System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionerForIEnumerable< TSource >.InternalPartitionEnumerable.TryCopyFromFillBuffer(), System.Reflection.Emit.TypeBuilder.TypeBuilder(), System.Runtime.Remoting.RemotingServices.UpdateOutArgObject(), Mono.Security.Cryptography.DSAManaged.VerifySignature(), Terraria.Utils.WordwrapString(), Terraria.Social.Steam.CloudSocialModule.Write(), Ionic.Zip.ZipOutput.WriteCentralDirectoryStructure(), Newtonsoft.Json.Utilities.JavaScriptUtils.WriteEscapedJavaScriptString(), and System.Security.AccessControl.ObjectAce.WriteGuid().