Terraria Decompiled: System.Array.Copy
Copy() [3/4]
static void System.Array.Copy (Array sourceArray, int sourceIndex, Array destinationArray, int destinationIndex, int length) inline static
Definition at line 1973 of file Array.cs.
        {
            if (sourceArray == null)
            {
                throw new ArgumentNullException("sourceArray");
            }
            if (destinationArray == null)
            {
                throw new ArgumentNullException("destinationArray");
            }
            if (length < 0)
            {
                throw new ArgumentOutOfRangeException("length", "Value has to be >= 0.");
            }
            if (sourceArray.Rank != destinationArray.Rank)
            {
                throw new RankException("Only single dimension arrays are supported here.");
            }
            if (sourceIndex < 0)
            {
                throw new ArgumentOutOfRangeException("sourceIndex", "Value has to be >= 0.");
            }
            if (destinationIndex < 0)
            {
                throw new ArgumentOutOfRangeException("destinationIndex", "Value has to be >= 0.");
            }
            if (Array.FastCopy(sourceArray, sourceIndex, destinationArray, destinationIndex, length))
            {
                return;
            }
            int num = sourceIndex - sourceArray.GetLowerBound(0);
            int num2 = destinationIndex - destinationArray.GetLowerBound(0);
            if (num2 < 0)
            {
                throw new ArgumentOutOfRangeException("destinationIndex", "Index was less than the array's lower bound in the first dimension.");
            }
            if (num > sourceArray.Length - length)
            {
                throw new ArgumentException("length");
            }
            if (num2 > destinationArray.Length - length)
            {
                throw new ArgumentException("Destination array was not long enough. Check destIndex and length, and the array's lower bounds", "destinationArray");
            }
            Type elementType = sourceArray.GetType().GetElementType();
            Type elementType2 = destinationArray.GetType().GetElementType();
            bool isValueType = elementType2.IsValueType;
            if (sourceArray != destinationArray || num > num2)
            {
                for (int i = 0; i < length; i++)
                {
                    object valueImpl = sourceArray.GetValueImpl(num + i);
                    if (valueImpl == null && isValueType)
                    {
                        throw new InvalidCastException();
                    }
                    try
                    {
                        destinationArray.SetValueImpl(valueImpl, num2 + i);
                    }
                    catch (ArgumentException)
                    {
                        throw Array.CreateArrayTypeMismatchException();
                    }
                    catch (InvalidCastException)
                    {
                        if (Array.CanAssignArrayElement(elementType, elementType2))
{
                            throw;
                        }
                        throw Array.CreateArrayTypeMismatchException();
                    }
                }
                return;
            }
            for (int j = length - 1; j >= 0; j--)
            {
                object valueImpl2 = sourceArray.GetValueImpl(num + j);
                try
                {
                    destinationArray.SetValueImpl(valueImpl2, num2 + j);
                }
                catch (ArgumentException)
                {
                    throw Array.CreateArrayTypeMismatchException();
                }
                catch
                {
                    if (Array.CanAssignArrayElement(elementType, elementType2))
                    {
                        throw;
                    }
                    throw Array.CreateArrayTypeMismatchException();
                }
            }
        }
References System.Array.CanAssignArrayElement(), System.Array.CreateArrayTypeMismatchException(), System.Array.FastCopy(), System.Array.GetLowerBound(), System.Array.GetValueImpl(), System.Type.IsValueType, System.Array.Length, System.length, System.Array.Rank, and System.Array.SetValueImpl().