Terraria Decompiled: System.Array.SortImpl
SortImpl()
static void System.Array.SortImpl (Array keys, Array items, int index, int length, IComparer comparer) inline static private
Definition at line 2125 of file Array.cs.
        {
            object[] array = keys as object[];
            object[] array2 = null;
            if (array != null)
            {
                array2 = items as object[];
            }
            if (array != null && (items == null || array2 != null))
            {
                Array.SorterObjectArray sorterObjectArray = new Array.SorterObjectArray(array, array2, comparer);
                sorterObjectArray.Sort(index, length);
                return;
            }
            Array.SorterGenericArray sorterGenericArray = new Array.SorterGenericArray(keys, items, comparer);
            sorterGenericArray.Sort(index, length);
        }
References System.array, System.comparer, System.index, System.length, System.Array.SorterObjectArray.Sort(), and System.Array.SorterGenericArray.Sort().
Referenced by System.Array.Sort().