Terraria Decompiled: System.Array.SetValue
SetValue() [4/8]
void System.Array.SetValue (object value, long index) inline
Definition at line 960 of file Array.cs.
        {
            if (index > 2147483647L || index < -2147483648L)
            {
                throw new ArgumentOutOfRangeException("index", "Arrays larger than 2GB are not supported.");
            }
            this.SetValue(value, (int)index);
        }
References System.index, System.L, and System.Array.SetValue().
Referenced by System.DefaultBinder.BindToMethod(), Newtonsoft.Json.Utilities.CollectionUtils.CopyFromJaggedToMultidimensionalArray(), System.Collections.Hashtable.CopyKeys(), System.Collections.Stack.CopyTo(), System.Collections.Hashtable.CopyValues(), System.Array.SorterGenericArray.DownHeap(), System.Runtime.Serialization.Formatters.Binary.ValueFixup.Fixup(), System.RuntimeType.GetEnumValues(), System.Array.SorterGenericArray.InsertionSort(), System.RuntimeType.InvokeMember(), System.Array.SetValue(), System.Array.SetValue(), System.Array.SetValue(), System.Array.SetValue(), System.Array.SetValue(), System.Array.SetValue(), System.Array.SorterGenericArray.Swap(), and System.Array.SorterGenericArray.SwapIfGreaterWithItems().