Terraria Decompiled: System.Array.GetValue
GetValue() [4/8]
object System.Array.GetValue (long index) inline
Definition at line 340 of file Array.cs.
        {
            if (index > 2147483647L || index < -2147483648L)
            {
                throw new ArgumentOutOfRangeException("index", "Arrays larger than 2GB are not supported.");
            }
            return this.GetValue((int)index);
        }
References System.Array.GetValue(), System.index, and System.L.
Referenced by System.Attribute.AreFieldValuesEqual(), System.Array.CompareTo(), System.Array.SorterGenericArray.DownHeap(), System.Array.Equals(), System.Array.GetValue(), System.Array.GetValue(), System.Array.GetValue(), System.Array.GetValue(), System.Array.GetValue(), System.Array.GetValue(), System.Array.SorterGenericArray.InsertionSort(), System.RuntimeType.InvokeMember(), System.Array.SorterGenericArray.PickPivotAndPartition(), System.Array.SorterGenericArray.Swap(), and System.Array.SorterGenericArray.SwapIfGreaterWithItems().