Terraria Decompiled: System.Array.Clear
Clear() [1/2]
void IList. System.Array.Clear () inline private
Implements System.Collections.Generic.ICollection< T >.
Definition at line 116 of file Array.cs.
        {
            Array.Clear(this, this.GetLowerBound(0), this.Length);
        }
References System.Array.Clear(), System.Array.GetLowerBound(), and System.Array.Length.
Referenced by Ionic.Zlib.DeflateManager._InitializeLazyMatch(), Terraria.WorldGen.AddUpAlignmentCounts(), Terraria.Player.AdjTiles(), System.Security.SecureString.Alloc(), NVorbis.Floor0.Apply(), NVorbis.Floor1.Apply(), System.Array.Clear(), System.Collections.ArrayList.Clear(), System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.Collections.Generic.List< T >.Clear(), System.Collections.Generic.LowLevelList< T >.Clear(), System.Collections.Generic.Queue< T >.Clear(), System.Collections.Generic.Stack< T >.Clear(), System.Collections.Queue.Clear(), System.Collections.SortedList.Clear(), System.Collections.Stack.Clear(), System.ParameterizedStrings.LowLevelStack.Clear(), System.Security.SecureString.Clear(), Terraria.Chest.Clear(), Terraria.GameContent.BannerSystem.Clear(), Terraria.GameContent.Items.TagEffectState.Clear(), Terraria.Utilities.Vertical64BitStrips.Clear(), Terraria.GameContent.LeashedEntity.Clear(), Terraria.DataStructures.DoubleStack< T1 >.Clear(), Terraria.WorldGen.clearWorld(), Terraria.GameContent.LeashedEntity.SectionEntityList.CompactIfNecesary(), System.Security.Cryptography.Utils.ConvertIntToByteArray(), Terraria.DataStructures.TileObjectPreviewData.CopyFrom(), Terraria.GameContent.LeashedEntities.LeashedCritter.CopyToDummy(), NVorbis.Mapping.DecodePacket(), Internal.Cryptography.PinAndClear.Dispose(), Mono.Security.Cryptography.HMACAlgorithm.Dispose(), System.Security.SecureString.Dispose(), Mono.Security.Cryptography.ARC4Managed.Dispose(), Mono.Security.Cryptography.SymmetricTransform.Dispose(), System.Security.Cryptography.CryptoStream.Dispose(), System.Security.Cryptography.FromBase64Transform.Dispose(), System.Security.Cryptography.HMAC.Dispose(), System.Security.Cryptography.KeyedHashAlgorithm.Dispose(), System.Security.Cryptography.MD5CryptoServiceProvider.Dispose(), System.Security.Cryptography.PasswordDeriveBytes.Dispose(), System.Security.Cryptography.Rfc2898DeriveBytes.Dispose(), System.Security.Cryptography.RijndaelManagedTransform.Dispose(), System.Security.Cryptography.SymmetricAlgorithm.Dispose(), System.Security.Cryptography.TailStream.Dispose(), Terraria.Main.DrawBackground(), Terraria.Main.DrawBackground_UpdateBackgroundStyles(), Mono.Security.Cryptography.HMACAlgorithm.Final(), Mono.Security.Cryptography.SymmetricTransform.FinalDecrypt(), Terraria.Graphics.TileBatch.Flush(), System.Security.Cryptography.CryptoStream.FlushFinalBlock(), Terraria.Graphics.TileBatch.FlushLayered(), System.Security.Cryptography.Rfc2898DeriveBytes.Func(), System.Security.Cryptography.RandomNumberGenerator.GetBytes(), System.Security.Cryptography.RandomNumberGenerator.GetNonZeroBytes(), Mono.Security.Cryptography.RSAManaged.GetPaddedValue(), System.Security.Cryptography.HashAlgorithm.HashCore(), System.IO.FileStream.InitBuffer(), Mono.Security.Cryptography.BlockProcessor.Initialize(), Mono.Security.Cryptography.HMACAlgorithm.Initialize(), Mono.Security.Cryptography.MD2Managed.Initialize(), Mono.Security.Cryptography.MD4Managed.Initialize(), System.Security.Cryptography.Rfc2898DeriveBytes.Initialize(), System.Security.Cryptography.RIPEMD160Managed.Initialize(), System.Security.Cryptography.SHA1Managed.Initialize(), System.Security.Cryptography.SHA256Managed.Initialize(), System.Security.Cryptography.SHA384Managed.Initialize(), System.Security.Cryptography.SHA512Managed.Initialize(), Mono.Security.Cryptography.MACAlgorithm.Initialize(), Ionic.Zlib.InfTree.initWorkArea(), System.Collections.BitArray.LeftShift(), Terraria.GameContent.EmergencyStacking.MemoStackableItems(), Terraria.GameContent.QuickStacking.PackQuickStackableItems(), Terraria.Player.Player(), Ionic.Zlib.InflateBlocks.Process(), Terraria.GameContent.EmergencyStacking.ProcessPendingTransfers(), Terraria.GameContent.QuickStacking.ReadNetInventory(), Terraria.GameContent.Items.TagEffectState.NetModule.ReadSparseNPCTimeArray(), System.Collections.Generic.List< T >.RemoveAll(), System.Collections.Generic.LowLevelList< T >.RemoveAll(), System.Collections.Generic.List< T >.RemoveRange(), Terraria.DataStructures.ActiveSections.Reset(), Terraria.DataStructures.TileObjectPreviewData.Reset(), Terraria.GameContent.QuickStacking.MatchingItemTypeDestinationList.Reset(), Terraria.MessageBuffer.Reset(), Terraria.RemoteClient.Reset(), Terraria.SceneMetrics.Reset(), Terraria.Utilities.BitSet2D.Reset(), Terraria.GameContent.QuickStacking.DestinationHelper.Reset(), Terraria.NPC.ResetForNewNPC(), Terraria.Projectile.ResetLocalNPCHitImmunity(), Terraria.Player.ResetMeleeHitCooldowns(), Terraria.GameContent.UI.NewCraftingUI.ResetRecipes(), Terraria.Netplay.ResetSections(), Terraria.GameContent.UI.States.UIWorldCreation.ResetSpecialSeedRing(), System.Buffers.ConfigurableArrayPool< T >.Return(), System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >.Return(), System.Collections.BitArray.RightShift(), Terraria.NetMessage.SendData(), Terraria.Projectile.SetDefaults(), System.Security.Cryptography.DESTransform.SetKey(), System.IO.MemoryStream.SetLength(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetRenderTargets(), Terraria.Recipe.SetupRecipes(), Terraria.Recipe.SetupTileInheritance(), Mono.Security.Cryptography.RSAManaged.ToXmlString(), System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >.Trim(), System.Security.Cryptography.DSA.TryHashData(), System.Security.Cryptography.RSA.TryHashData(), NVorbis.Floor0.Unpack(), Terraria.UI.BannerClaimingUI.UpdateAndGetClaimableItemsCount(), Terraria.Player.UpdateSunScorch(), System.Security.Cryptography.DSA.VerifyData(), System.Security.Cryptography.RSA.VerifyData(), System.IO.MemoryStream.Write(), System.IO.MemoryStream.Write(), System.IO.MemoryStream.WriteByte(), and Mono.Security.Cryptography.BlockProcessor.~BlockProcessor().