Terraria Decompiled: System.Array.CreateInstance
CreateInstance() [6/6]
static Array System.Array.CreateInstance (Type elementType, params long[] lengths) inline static
Definition at line 16 of file Array.cs.
        {
            if (lengths == null)
            {
                throw new ArgumentNullException("lengths");
            }
            if (lengths.Length == 0)
            {
                throw new ArgumentException("Must provide at least one rank.");
            }
            int[] array = new int[lengths.Length];
            for (int i = 0; i < lengths.Length; i++)
            {
                long num = lengths[i];
                if (num > 2147483647L || num < -2147483648L)
                {
                    throw new ArgumentOutOfRangeException("len", "Arrays larger than 2GB are not supported.");
                }
                array[i] = (int)num;
            }
            return Array.CreateInstance(elementType, array);
        }
References System.array, System.Array.CreateInstance(), int, and System.L.
Referenced by Mono.Globalization.Unicode.CodePointIndexer.CompressArray(), FullSerializer.fsMetaType.CreateInstance(), System.Array.CreateInstance(), System.Array.CreateInstance(), System.Array.CreateInstance(), System.Array.CreateInstance(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(), Newtonsoft.Json.Converters.DataTableConverter.CreateRow(), Newtonsoft.Json.Utilities.DynamicUtils.BinderWrapper.CreateSharpArgumentInfoArray(), System.MonoCustomAttrs.GetCustomAttributes(), System.RuntimeType.GetEnumValues(), System.Runtime.CompilerServices.RuntimeHelpers.GetSubArray< T >(), System.Attribute.InternalParamGetCustomAttributes(), System.Collections.ArrayList.ToArray(), System.Collections.ArrayList.IListWrapper.ToArray(), System.Collections.ArrayList.Range.ToArray(), Newtonsoft.Json.Utilities.CollectionUtils.ToMultidimensionalArray(), System.Array.UnsafeCreateInstance(), System.Array.UnsafeCreateInstance(), and System.Array.UnsafeCreateInstance().