Terraria Decompiled: FullSerializer.Internal.fsArrayConverter.TryDeserialize
TryDeserialize()
override fsResult FullSerializer.Internal.fsArrayConverter.TryDeserialize (fsData data, ref object instance, Type storageType) inline
Definition at line 51 of file fsArrayConverter.cs.
        {
            fsResult fsResult = fsResult.Success;
            fsResult fsResult2;
            fsResult = (fsResult2 = fsResult + base.CheckType(data, fsDataType.Array));
            if (fsResult2.Failed)
            {
                return fsResult;
            }
            Type elementType = storageType.GetElementType();
            List<fsData> asList = data.AsList;
            ArrayList arrayList = new ArrayList(asList.Count);
            int count = arrayList.Count;
            for (int i = 0; i < asList.Count; i++)
            {
                fsData fsData = asList[i];
                object obj = null;
                if (i < count)
                {
                    obj = arrayList[i];
                }
                fsResult fsResult3 = this.Serializer.TryDeserialize(fsData, elementType, ref obj);
                fsResult.AddMessages(fsResult3);
                if (!fsResult3.Failed)
                {
                    if (i < count)
                    {
                        arrayList[i] = obj;
                    }
                    else
                    {
                        arrayList.Add(obj);
                    }
                }
            }
            instance = arrayList.ToArray(elementType);
            return fsResult;
        }
References System.Collections.ArrayList.Add(), FullSerializer.fsResult.AddMessages(), FullSerializer.fsData.AsList, System.Collections.ArrayList.Count, System.Collections.Generic.List< T >.Count, System.count, FullSerializer.fsResult.Failed, System.Type.GetElementType(), System.obj, FullSerializer.fsBaseConverter.Serializer, FullSerializer.fsResult.Success, System.Collections.ArrayList.ToArray(), and FullSerializer.fsSerializer.TryDeserialize().