Terraria Decompiled: FullSerializer.Internal.fsArrayConverter.TrySerialize
TrySerialize()
override fsResult FullSerializer.Internal.fsArrayConverter.TrySerialize (object instance, out fsData serialized, Type storageType) inline
Definition at line 29 of file fsArrayConverter.cs.
        {
            IList list = (Array)instance;
            Type elementType = storageType.GetElementType();
            fsResult success = fsResult.Success;
            serialized = fsData.CreateList(list.Count);
            List<fsData> asList = serialized.AsList;
            for (int i = 0; i < list.Count; i++)
            {
                object obj = list[i];
                fsData fsData;
                fsResult fsResult = this.Serializer.TrySerialize(elementType, obj, out fsData);
                success.AddMessages(fsResult);
                if (!fsResult.Failed)
                {
                    asList.Add(fsData);
                }
            }
            return success;
        }
References System.Collections.Generic.List< T >.Add(), FullSerializer.fsResult.AddMessages(), FullSerializer.Array, FullSerializer.fsData.CreateList(), FullSerializer.fsResult.Failed, System.Type.GetElementType(), System.list, System.obj, FullSerializer.fsBaseConverter.Serializer, FullSerializer.fsResult.Success, and FullSerializer.fsSerializer.TrySerialize().