Terraria Decompiled: System.Globalization.CultureData.GetCalendar
GetCalendar()
CalendarData System.Globalization.CultureData.GetCalendar (int calendarId) inline
Definition at line 98 of file CultureData.cs.
        {
            int num = calendarId - 1;
            if (this.calendars == null)
            {
                this.calendars = new CalendarData[23];
            }
            CalendarData calendarData = this.calendars[num];
            if (calendarData == null)
            {
                calendarData = new CalendarData(this.sRealName, calendarId, this.bUseOverrides);
                this.calendars[num] = calendarData;
            }
            return calendarData;
        }
References System.Globalization.CultureData.bUseOverrides, System.Globalization.CultureData.calendarId, System.Globalization.CultureData.calendars, and System.Globalization.CultureData.sRealName.
Referenced by System.Globalization.CultureData.AbbrevEraNames(), System.Globalization.CultureData.AbbreviatedDayNames(), System.Globalization.CultureData.AbbreviatedEnglishEraNames(), System.Globalization.CultureData.AbbreviatedGenitiveMonthNames(), System.Globalization.CultureData.AbbreviatedMonthNames(), System.Globalization.CultureData.CalendarName(), System.Globalization.CultureData.DayNames(), System.Globalization.CultureData.EraNames(), System.Globalization.CultureData.GenitiveMonthNames(), System.Globalization.CalendarData.GetCalendarData(), System.Globalization.CultureData.LeapYearMonthNames(), System.Globalization.CultureData.LongDates(), System.Globalization.CultureData.MonthDay(), System.Globalization.CultureData.MonthNames(), System.Globalization.CultureData.ShortDates(), System.Globalization.CultureData.SuperShortDayNames(), and System.Globalization.CultureData.YearMonths().