Terraria Decompiled: System.Globalization.CultureData.GetNFIValues
GetNFIValues()
unsafe void System.Globalization.CultureData.GetNFIValues (NumberFormatInfo nfi) inline package
Definition at line 622 of file CultureData.cs.
        {
            if (!this.IsInvariantCulture)
            {
                CultureData.NumberFormatEntryManaged numberFormatEntryManaged = default(CultureData.NumberFormatEntryManaged);
                byte* ptr = CultureData.fill_number_data(this.numberIndex, ref numberFormatEntryManaged);
                nfi.currencyGroupSizes = this.create_group_sizes_array(numberFormatEntryManaged.currency_group_sizes0, numberFormatEntryManaged.currency_group_sizes1);
                nfi.numberGroupSizes = this.create_group_sizes_array(numberFormatEntryManaged.number_group_sizes0, numberFormatEntryManaged.number_group_sizes1);
                nfi.NaNSymbol = CultureData.idx2string(ptr, numberFormatEntryManaged.nan_symbol);
                nfi.currencyDecimalDigits = numberFormatEntryManaged.currency_decimal_digits;
                nfi.currencyDecimalSeparator = CultureData.idx2string(ptr, numberFormatEntryManaged.currency_decimal_separator);
                nfi.currencyGroupSeparator = CultureData.idx2string(ptr, numberFormatEntryManaged.currency_group_separator);
                nfi.currencyNegativePattern = numberFormatEntryManaged.currency_negative_pattern;
                nfi.currencyPositivePattern = numberFormatEntryManaged.currency_positive_pattern;
                nfi.currencySymbol = CultureData.idx2string(ptr, numberFormatEntryManaged.currency_symbol);
                nfi.negativeInfinitySymbol = CultureData.idx2string(ptr, numberFormatEntryManaged.negative_infinity_symbol);
                nfi.negativeSign = CultureData.idx2string(ptr, numberFormatEntryManaged.negative_sign);
                nfi.numberDecimalDigits = numberFormatEntryManaged.number_decimal_digits;
                nfi.numberDecimalSeparator = CultureData.idx2string(ptr, numberFormatEntryManaged.number_decimal_separator);
                nfi.numberGroupSeparator = CultureData.idx2string(ptr, numberFormatEntryManaged.number_group_separator);
                nfi.numberNegativePattern = numberFormatEntryManaged.number_negative_pattern;
                nfi.perMilleSymbol = CultureData.idx2string(ptr, numberFormatEntryManaged.per_mille_symbol);
                nfi.percentNegativePattern = numberFormatEntryManaged.percent_negative_pattern;
                nfi.percentPositivePattern = numberFormatEntryManaged.percent_positive_pattern;
                nfi.percentSymbol = CultureData.idx2string(ptr, numberFormatEntryManaged.percent_symbol);
                nfi.positiveInfinitySymbol = CultureData.idx2string(ptr, numberFormatEntryManaged.positive_infinity_symbol);
                nfi.positiveSign = CultureData.idx2string(ptr, numberFormatEntryManaged.positive_sign);
            }
            nfi.percentDecimalDigits = nfi.numberDecimalDigits;
            nfi.percentDecimalSeparator = nfi.numberDecimalSeparator;
            nfi.percentGroupSizes = nfi.numberGroupSizes;
            nfi.percentGroupSeparator = nfi.numberGroupSeparator;
        }
References System.Globalization.CultureData.create_group_sizes_array(), System.Globalization.CultureData.NumberFormatEntryManaged.currency_decimal_digits, System.Globalization.CultureData.NumberFormatEntryManaged.currency_decimal_separator, System.Globalization.CultureData.NumberFormatEntryManaged.currency_group_separator, System.Globalization.CultureData.NumberFormatEntryManaged.currency_group_sizes0, System.Globalization.CultureData.NumberFormatEntryManaged.currency_group_sizes1, System.Globalization.CultureData.NumberFormatEntryManaged.currency_negative_pattern, System.Globalization.CultureData.NumberFormatEntryManaged.currency_positive_pattern, System.Globalization.CultureData.NumberFormatEntryManaged.currency_symbol, System.Globalization.CultureData.fill_number_data(), System.Globalization.CultureData.idx2string(), System.Globalization.CultureData.IsInvariantCulture, System.Globalization.CultureData.NumberFormatEntryManaged.nan_symbol, System.Globalization.CultureData.NumberFormatEntryManaged.negative_infinity_symbol, System.Globalization.CultureData.NumberFormatEntryManaged.negative_sign, System.Globalization.CultureData.NumberFormatEntryManaged.number_decimal_digits, System.Globalization.CultureData.NumberFormatEntryManaged.number_decimal_separator, System.Globalization.CultureData.NumberFormatEntryManaged.number_group_separator, System.Globalization.CultureData.NumberFormatEntryManaged.number_group_sizes0, System.Globalization.CultureData.NumberFormatEntryManaged.number_group_sizes1, System.Globalization.CultureData.NumberFormatEntryManaged.number_negative_pattern, System.Globalization.NumberFormatInfo.numberDecimalDigits, System.Globalization.NumberFormatInfo.numberDecimalSeparator, System.Globalization.NumberFormatInfo.numberGroupSeparator, System.Globalization.NumberFormatInfo.numberGroupSizes, System.Globalization.CultureData.numberIndex, System.Globalization.CultureData.NumberFormatEntryManaged.per_mille_symbol, System.Globalization.CultureData.NumberFormatEntryManaged.percent_negative_pattern, System.Globalization.CultureData.NumberFormatEntryManaged.percent_positive_pattern, System.Globalization.CultureData.NumberFormatEntryManaged.percent_symbol, System.Globalization.CultureData.NumberFormatEntryManaged.positive_infinity_symbol, and System.Globalization.CultureData.NumberFormatEntryManaged.positive_sign.
Referenced by System.Globalization.NumberFormatInfo.NumberFormatInfo().