Terraria Decompiled: Terraria.Testing.ChatCommands.ToolkitDebugCommands.ShowDebugCommand
ShowDebugCommand()
static bool Terraria.Testing.ChatCommands.ToolkitDebugCommands.ShowDebugCommand (DebugMessage message) inline static
Definition at line 726 of file ToolkitDebugCommands.cs.
        {
            if (message.Author != 255 && !Main.player[(int)message.Author].host)
            {
                message.ReplyError("/showdebug can only be toggled by the host or server console.");
                return true;
            }
            if (DebugOptions.Shared_ReportCommandUsage)
            {
                DebugOptions.Shared_ReportCommandUsage = false;
                ChatHelper.BroadcastChatMessage(NetworkText.FromLiteral("Command reporting disabled"), new Color(250, 250, 0), -1);
            }
            else
            {
                DebugOptions.Shared_ReportCommandUsage = true;
                ChatHelper.BroadcastChatMessage(NetworkText.FromLiteral("Command reporting enabled"), new Color(250, 250, 0), -1);
            }
            NetMessage.SendData(94, -1, -1, NetworkText.FromLiteral("/showdebug"), 0, (float)(DebugOptions.Shared_ReportCommandUsage ? 1 : 0), 0f, 0f, 0, 0, 0);
            return true;
        }
References Terraria.Testing.ChatCommands.DebugMessage.Author, Terraria.Chat.ChatHelper.BroadcastChatMessage(), Terraria.Localization.NetworkText.FromLiteral(), Terraria.Player.host, Terraria.Main.player, Terraria.Testing.ChatCommands.DebugMessage.ReplyError(), Terraria.NetMessage.SendData(), and Terraria.Testing.DebugOptions.Shared_ReportCommandUsage.