Terraria Decompiled: Terraria.Testing.ChatCommands.ToolkitDebugCommands.FindCommand
FindCommand()
static bool Terraria.Testing.ChatCommands.ToolkitDebugCommands.FindCommand (DebugMessage message) inline static
Definition at line 389 of file ToolkitDebugCommands.cs.
        {
            int tileType;
            if (!int.TryParse(message.Arguments, out tileType))
            {
                return false;
            }
            if (tileType < 0 || tileType >= (int)TileID.Count)
            {
                return false;
            }
            string text = string.Empty;
            if (MapHelper.HasOption(tileType, 0))
            {
                text = Lang.GetMapObjectName(MapHelper.TileToLookup(tileType, 0));
            }
            if (text == string.Empty)
            {
                text = "#" + tileType;
            }
            ToolkitDebugCommands.FindNextEnumerable = ToolkitDebugCommands.FindTiles(message, (Tile t) => (int)t.type == tileType, "Tile " + text, 3);
            ToolkitDebugCommands.FindNext();
            return true;
        }
References Terraria.Testing.ChatCommands.DebugMessage.Arguments, Terraria.ID.TileID.Count, Terraria.Testing.ChatCommands.ToolkitDebugCommands.FindNext(), Terraria.Testing.ChatCommands.ToolkitDebugCommands.FindTiles(), Terraria.Lang.GetMapObjectName(), Terraria.Map.MapHelper.HasOption(), System.text, Terraria.Map.MapHelper.TileToLookup(), and Terraria.Tile.type.