Terraria Decompiled: Terraria.Testing.ChatCommands.ToolkitDebugCommands.SwapCommand
SwapCommand()
static bool Terraria.Testing.ChatCommands.ToolkitDebugCommands.SwapCommand (DebugMessage message) inline static
Definition at line 332 of file ToolkitDebugCommands.cs.
        {
            if (!TileSnapshot.IsCreated)
            {
                message.ReplyError("No snapshot to restore");
            }
            else if (!TileSnapshot.SizeMatches)
            {
                message.ReplyError("Tile snapshot does not match current world size");
            }
            else
            {
                Stopwatch stopwatch = Stopwatch.StartNew();
                TileSnapshot.Swap();
                message.Reply(string.Format("Tile snapshot swapped in {0}ms", stopwatch.ElapsedMilliseconds));
            }
            return true;
        }
References System.Format, Terraria.Utilities.TileSnapshot.IsCreated, Terraria.Testing.ChatCommands.DebugMessage.Reply(), Terraria.Testing.ChatCommands.DebugMessage.ReplyError(), Terraria.Utilities.TileSnapshot.SizeMatches, and Terraria.Utilities.TileSnapshot.Swap().