Terraria Decompiled: Terraria.Testing.ChatCommands.ToolkitDebugCommands.SnapshotSaveCommand
SnapshotSaveCommand()
static bool Terraria.Testing.ChatCommands.ToolkitDebugCommands.SnapshotSaveCommand (DebugMessage message) inline static
Definition at line 268 of file ToolkitDebugCommands.cs.
        {
            if (string.IsNullOrWhiteSpace(message.Arguments))
            {
                message.ReplyError("Snapshot name required");
                return true;
            }
            if (!TileSnapshot.IsCreated)
            {
                TileSnapshot.Create(null);
            }
            Directory.CreateDirectory(Path.Combine(Main.SavePath, "dev-snapshots"));
            TileSnapshot.Save(Path.Combine(Main.SavePath, "dev-snapshots", message.Arguments + ".gensnapshot"));
            message.Reply("Tile Snapshot Saved to dev-snapshots/" + message.Arguments + ".gensnapshot");
            return true;
        }
References Terraria.Testing.ChatCommands.DebugMessage.Arguments, System.IO.Path.Combine(), Terraria.Utilities.TileSnapshot.Create(), System.IO.Directory.CreateDirectory(), Terraria.Utilities.TileSnapshot.IsCreated, Terraria.Testing.ChatCommands.DebugMessage.Reply(), Terraria.Testing.ChatCommands.DebugMessage.ReplyError(), Terraria.Utilities.TileSnapshot.Save(), and Terraria.Main.SavePath.