Terraria Decompiled: Terraria.Testing.ChatCommands.ToolkitDebugCommands.FindTiles
FindTiles()
static IEnumerable< Point > Terraria.Testing.ChatCommands.ToolkitDebugCommands.FindTiles (DebugMessage message, Func< Tile, bool > predicate, string descriptor, int skipDistance) inline static private
Definition at line 461 of file ToolkitDebugCommands.cs.
        {
            Point lastPoint = Point.Zero;
            int num;
            for (int x = 0; x < Main.maxTilesX; x = num + 1)
            {
                for (int y = 0; y < Main.maxTilesY; y = num + 1)
                {
                    Tile tile = Main.tile[x, y];
                    if (tile != null && predicate(tile) && (x - lastPoint.X >= skipDistance || Math.Abs(y - lastPoint.Y) >= skipDistance))
                    {
                        lastPoint = new Point(x, y);
                        message.Reply(descriptor + " found at " + lastPoint);
                        yield return lastPoint;
                    }
                    num = y;
                }
                num = x;
            }
            message.Reply(descriptor + " scan complete.");
            yield break;
        }
References System.Math.Abs(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Testing.ChatCommands.DebugMessage.Reply(), Terraria.Main.tile, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Point.Y, and Microsoft.Xna.Framework.Point.Zero.
Referenced by Terraria.Testing.ChatCommands.ToolkitDebugCommands.FindCommand(), and Terraria.Testing.ChatCommands.ToolkitDebugCommands.FindWallCommand().