Terraria Decompiled: Terraria.Testing.ChatCommands.ToolkitDebugCommands.SetServerPingCommand
SetServerPingCommand()
static bool Terraria.Testing.ChatCommands.ToolkitDebugCommands.SetServerPingCommand (DebugMessage message) inline static
Definition at line 61 of file ToolkitDebugCommands.cs.
        {
            int num;
            if (!int.TryParse(message.Arguments, out num) || num < 0 || num > 10000)
            {
                return false;
            }
            DebugOptions.Shared_ServerPing = num;
            ChatHelper.BroadcastChatMessage(NetworkText.FromLiteral(string.Format("Target ping set {0}ms", num)), new Color(250, 250, 0), -1);
            NetMessage.SendData(94, -1, -1, NetworkText.FromLiteral("/setserverping"), 0, (float)DebugOptions.Shared_ServerPing, 0f, 0f, 0, 0, 0);
            return true;
        }
References Terraria.Testing.ChatCommands.DebugMessage.Arguments, Terraria.Chat.ChatHelper.BroadcastChatMessage(), Terraria.Localization.NetworkText.FromLiteral(), Terraria.NetMessage.SendData(), and Terraria.Testing.DebugOptions.Shared_ServerPing.