Terraria Decompiled: System.Security.Cryptography.RC2Transform.RC2Transform
RC2Transform() [1/2]
System.Security.Cryptography.RC2Transform.RC2Transform (RC2 rc2Algo, bool encryption, byte[] key, byte[] iv) inline
Definition at line 10 of file RC2Transform.cs.
            : base(rc2Algo, encryption, iv)
        {
            int num = rc2Algo.EffectiveKeySize;
            if (key == null)
            {
                key = KeyBuilder.Key(rc2Algo.KeySize >> 3);
            }
            else
            {
                key = (byte[])key.Clone();
                num = Math.Min(num, key.Length << 3);
            }
            int num2 = key.Length;
            if (!KeySizes.IsLegalKeySize(rc2Algo.LegalKeySizes, num2 << 3))
            {
                throw new CryptographicException(Locale.GetText("Key is too small ({0} bytes), it should be between {1} and {2} bytes long.", new object[] { num2, 5, 16 }));
            }
            byte[] array = new byte[128];
            int num3 = num + 7 >> 3;
            int num4 = 255 % (2 << 8 + num - (num3 << 3) - 1);
            for (int i = 0; i < num2; i++)
            {
                array[i] = key[i];
            }
            for (int j = num2; j < 128; j++)
            {
                array[j] = RC2Transform.pitable[(int)((array[j - 1] + array[j - num2]) & byte.MaxValue)];
            }
            array[128 - num3] = RC2Transform.pitable[(int)array[128 - num3] & num4];
            for (int k = 127 - num3; k >= 0; k--)
            {
                array[k] = RC2Transform.pitable[(int)(array[k + 1] ^ array[k + num3])];
            }
            this.K = new ushort[64];
            int num5 = 0;
            for (int l = 0; l < 64; l++)
            {
                this.K[l] = (ushort)((int)array[num5++] + ((int)array[num5++] << 8));
            }
        }
References System.array, System.Security.Cryptography.RC2.EffectiveKeySize, Locale.GetText(), int, System.Security.Cryptography.KeySizes.IsLegalKeySize(), System.Security.Cryptography.RC2Transform.j, System.Security.Cryptography.RC2Transform.K, Mono.Security.Cryptography.KeyBuilder.Key(), System.key, System.Security.Cryptography.RC2.KeySize, System.Security.Cryptography.SymmetricAlgorithm.LegalKeySizes, System.Math.Min(), and System.Security.Cryptography.RC2Transform.pitable.