Terraria Decompiled: Terraria.Wiring.Toggle2x2Light
Toggle2x2Light()
static void Terraria.Wiring.Toggle2x2Light (int i, int j, Tile tileCache, bool? forcedStateWhereTrueIsOn, bool doSkipWires) inline static
Definition at line 3058 of file Wiring.cs.
        {
            int k;
            for (k = (int)(tileCache.frameY / 18); k >= 2; k -= 2)
            {
            }
            k = j - k;
            int num = (int)(tileCache.frameX / 18);
            if (num > 1)
            {
                num -= 2;
            }
            num = i - num;
            short num2 = 36;
            if (Main.tile[num, k].frameX > 0)
            {
                num2 = -36;
            }
            bool flag = Main.tile[num, k].frameX > 0;
            if (forcedStateWhereTrueIsOn != null && !forcedStateWhereTrueIsOn.Value == flag)
            {
                return;
            }
            Tile tile = Main.tile[num, k];
            tile.frameX += num2;
            Tile tile2 = Main.tile[num, k + 1];
            tile2.frameX += num2;
            Tile tile3 = Main.tile[num + 1, k];
            tile3.frameX += num2;
            Tile tile4 = Main.tile[num + 1, k + 1];
            tile4.frameX += num2;
            if (doSkipWires)
            {
                Wiring.SkipWire(num, k);
                Wiring.SkipWire(num + 1, k);
                Wiring.SkipWire(num, k + 1);
                Wiring.SkipWire(num + 1, k + 1);
            }
            NetMessage.SendTileSquare(-1, num, k, 2, 2, TileChangeType.None);
        }
References Terraria.Tile.frameX, Terraria.Tile.frameY, int, Terraria.NetMessage.SendTileSquare(), Terraria.Wiring.SkipWire(), and Terraria.Main.tile.
Referenced by Terraria.Wiring.HitWireSingle(), and Terraria.WorldGen.TryToggleLight().