Terraria Decompiled: Terraria.Wiring.HitWireSingle
HitWireSingle()
static void Terraria.Wiring.HitWireSingle (int i, int j) inline static private
Definition at line 996 of file Wiring.cs.
        {
            Tile tile = Main.tile[i, j];
            bool? flag = null;
            bool flag2 = true;
            int type = (int)tile.type;
            if (tile.actuator())
            {
                Wiring.ActuateForced(i, j);
            }
            if (tile.active())
            {
                if (type == 144)
                {
                    Wiring.HitSwitch(i, j);
                    WorldGen.SquareTileFrame(i, j, true);
                    NetMessage.SendTileSquare(-1, i, j, TileChangeType.None);
                }
                else if (type == 421)
                {
                    if (!tile.actuator())
                    {
                        tile.type = 422;
                        WorldGen.SquareTileFrame(i, j, true);
                        NetMessage.SendTileSquare(-1, i, j, TileChangeType.None);
                    }
                }
                else if (type == 422 && !tile.actuator())
                {
                    tile.type = 421;
                    WorldGen.SquareTileFrame(i, j, true);
                    NetMessage.SendTileSquare(-1, i, j, TileChangeType.None);
                }
                if (type >= 255 && type <= 268)
                {
                    if (!tile.actuator())
                    {
                        if (type >= 262)
{
                            Tile tile2 = tile;
                            tile2.type -= 7;
                        }
                        else
{
                            Tile tile3 = tile;
                            tile3.type += 7;
                        }
                        WorldGen.SquareTileFrame(i, j, true);
                        NetMessage.SendTileSquare(-1, i, j, TileChangeType.None);
                        return;
                    }
                }
                else
                {
                    if (type == 419)
                    {
                        int num = 18;
                        if ((int)tile.frameX >= num)
{
                            num = -num;
                        }
                        if (tile.frameX == 36)
{
                            num = 0;
                        }
                        Wiring.SkipWire(i, j);
                        tile.frameX = (short)((int)tile.frameX + num);
                        WorldGen.SquareTileFrame(i, j, true);
                        NetMessage.SendTileSquare(-1, i, j, TileChangeType.None);
                        Wiring._LampsToCheck.Enqueue(new Point16(i, j));
                        return;
                    }
                    if (type == 406)
                    {
                        int num2 = (int)(tile.frameX % 54 / 18);
                        int num3 = (int)(tile.frameY % 54 / 18);
                        int num4 = i - num2;
                        int num5 = j - num3;
                        int num6 = 54;
                        if (Main.tile[num4, num5].frameY >= 108)
{
                            num6 = -108;
                        }
                        for (int k = num4; k < num4 + 3; k++)
{
                            for (int l = num5; l < num5 + 3; l++)
{
                                Wiring.SkipWire(k, l);
                                Main.tile[k, l].frameY = (short)((int)Main.tile[k, l].frameY + num6);
                            }
                        }
                        NetMessage.SendTileSquare(-1, num4 + 1, num5 + 1, 3, TileChangeType.None);
                        return;
                    }
                    if (type == 452)
                    {
                        int num7 = (int)(tile.frameX % 54 / 18);
                        int num8 = (int)(tile.frameY % 54 / 18);
                        int num9 = i - num7;
                        int num10 = j - num8;
                        int num11 = 54;
                        if (Main.tile[num9, num10].frameX >= 54)
{
                            num11 = -54;
                        }
                        for (int m = num9; m < num9 + 3; m++)
{
                            for (int n = num10; n < num10 + 3; n++)
{
                                Wiring.SkipWire(m, n);
                                Main.tile[m, n].frameX = (short)((int)Main.tile[m, n].frameX + num11);
                            }
                        }
                        NetMessage.SendTileSquare(-1, num9 + 1, num10 + 1, 3, TileChangeType.None);
                        return;
                    }
                    if (type == 411)
                    {
                        int num12 = (int)(tile.frameX % 36 / 18);
                        int num13 = (int)(tile.frameY % 36 / 18);
                        int num14 = i - num12;
                        int num15 = j - num13;
                        int num16 = 36;
                        if (Main.tile[num14, num15].frameX >= 36)
{
                            num16 = -36;
                        }
                        for (int num17 = num14; num17 < num14 + 2; num17++)
{
                            for (int num18 = num15; num18 < num15 + 2; num18++)
{
                                Wiring.SkipWire(num17, num18);
                                Main.tile[num17, num18].frameX = (short)((int)Main.tile[num17, num18].frameX + num16);
                            }
                        }
                        NetMessage.SendTileSquare(-1, num14, num15, 2, 2, TileChangeType.None);
                        return;
                    }
                    if (type == 356)
                    {
                        int num19 = (int)(tile.frameX % 36 / 18);
                        int num20 = (int)(tile.frameY % 54 / 18);
                        int num21 = i - num19;
                        int num22 = j - num20;
                        for (int num23 = num21; num23 < num21 + 2; num23++)
{
                            for (int num24 = num22; num24 < num22 + 3; num24++)
{
                                Wiring.SkipWire(num23, num24);
                            }
                        }
                        if (!Main.fastForwardTimeToDawn && Main.sundialCooldown == 0)
{
                            Main.Sundialing();
                        }
                        NetMessage.SendTileSquare(-1, num21, num22, 2, 2, TileChangeType.None);
                        return;
                    }
                    if (type == 663)
                    {
                        int num25 = (int)(tile.frameX % 36 / 18);
                        int num26 = (int)(tile.frameY % 54 / 18);
                        int num27 = i - num25;
                        int num28 = j - num26;
                        for (int num29 = num27; num29 < num27 + 2; num29++)
{
                            for (int num30 = num28; num30 < num28 + 3; num30++)
{
                                Wiring.SkipWire(num29, num30);
                            }
                        }
                        if (!Main.fastForwardTimeToDusk && Main.moondialCooldown == 0)
{
                            Main.Moondialing();
                        }
                        NetMessage.SendTileSquare(-1, num27, num28, 2, 2, TileChangeType.None);
                        return;
                    }
                    if (type == 425)
                    {
                        int num31 = (int)(tile.frameX % 36 / 18);
                        int num32 = (int)(tile.frameY % 36 / 18);
                        int num33 = i - num31;
                        int num34 = j - num32;
                        for (int num35 = num33; num35 < num33 + 2; num35++)
{
                            for (int num36 = num34; num36 < num34 + 2; num36++)
{
                                Wiring.SkipWire(num35, num36);
                            }
                        }
                        if (!Main.AnnouncementBoxDisabled)
{
                            Color pink = Color.Pink;
                            int num37 = Sign.ReadSign(num33, num34, false);
                            if (num37 != -1 && Main.sign[num37] != null && !string.IsNullOrWhiteSpace(Main.sign[num37].text))
{
                                if (Main.AnnouncementBoxRange == -1)
{
                                    if (Main.netMode == 0)
{
                                        Main.NewTextMultiline(Main.sign[num37].text, false, pink, 460);
                                        return;
                                    }
                                    if (Main.netMode == 2)
{
                                        NetMessage.SendData(107, -1, -1, NetworkText.FromLiteral(Main.sign[num37].text), 255, (float)pink.R, (float)pink.G, (float)pink.B, 460, 0, 0);
                                        return;
                                    }
                                }
                                else if (Main.netMode == 0)
{
                                    if (Main.player[Main.myPlayer].Distance(new Vector2((float)(num33 * 16 + 16), (float)(num34 * 16 + 16))) <= (float)Main.AnnouncementBoxRange)
{
                                        Main.NewTextMultiline(Main.sign[num37].text, false, pink, 460);
                                        return;
                                    }
                                }
                                else if (Main.netMode == 2)
{
                                    for (int num38 = 0; num38 < 255; num38++)
{
                                        if (Main.player[num38].active && Main.player[num38].Distance(new Vector2((float)(num33 * 16 + 16), (float)(num34 * 16 + 16))) <= (float)Main.AnnouncementBoxRange)
{
                                            NetMessage.SendData(107, num38, -1, NetworkText.FromLiteral(Main.sign[num37].text), 255, (float)pink.R, (float)pink.G, (float)pink.B, 460, 0, 0);
                                        }
                                    }
                                    return;
                                }
                            }
                        }
                    }
                    else
                    {
                        if (type == 405)
{
                            Wiring.ToggleFirePlace(i, j, tile, flag, flag2);
                            return;
                        }
                        if (type == 209)
{
                            int num39 = (int)(tile.frameX % 72 / 18);
                            int num40 = (int)(tile.frameY % 54 / 18);
                            int num41 = i - num39;
                            int num42 = j - num40;
                            int num43 = (int)(tile.frameY / 54);
                            int num44 = (int)(tile.frameX / 72);
                            int num45 = -1;
                            if (num39 == 1 || num39 == 2)
{
                                num45 = num40;
                            }
                            int num46 = 0;
                            if (num39 == 3)
{
                                num46 = -54;
                            }
                            if (num39 == 0)
{
                                num46 = 54;
                            }
                            if (num43 >= 8 && num46 > 0)
{
                                num46 = 0;
                            }
                            if (num43 == 0 && num46 < 0)
{
                                num46 = 0;
                            }
                            bool flag3 = false;
                            if (num46 != 0)
{
                                for (int num47 = num41; num47 < num41 + 4; num47++)
{
                                    for (int num48 = num42; num48 < num42 + 3; num48++)
{
                                        Wiring.SkipWire(num47, num48);
                                        Main.tile[num47, num48].frameY = (short)((int)Main.tile[num47, num48].frameY + num46);
                                    }
                                }
                                flag3 = true;
                            }
                            if ((num44 == 3 || num44 == 4) && (num45 == 0 || num45 == 1))
{
                                num46 = ((num44 == 3) ? 72 : (-72));
                                for (int num49 = num41; num49 < num41 + 4; num49++)
{
                                    for (int num50 = num42; num50 < num42 + 3; num50++)
{
                                        Wiring.SkipWire(num49, num50);
                                        Main.tile[num49, num50].frameX = (short)((int)Main.tile[num49, num50].frameX + num46);
                                    }
                                }
                                flag3 = true;
                            }
                            if (flag3)
{
                                NetMessage.SendTileSquare(-1, num41, num42, 4, 3, TileChangeType.None);
                            }
                            if (num45 != -1)
{
                                bool flag4 = true;
                                if ((num44 == 3 || num44 == 4) && num45 < 2)
{
                                    flag4 = false;
                                }
                                int num51 = 0;
                                float num52 = 0f;
                                int num53 = 30;
                                if (num44 == 0)
{
                                    if (Wiring.cannonCoolDown > 0)
{
                                        return;
                                    }
                                    num51 = 300;
                                    num52 = 8f;
                                    num53 = 480;
                                }
                                else if (num44 == 1)
{
                                    if (Wiring.bunnyCannonCoolDown > 0)
{
                                        return;
                                    }
                                    num51 = 350;
                                    num52 = 8f;
                                    num53 = 3600;
                                }
                                if (Wiring.CheckMech(num41, num42, num53) && flag4)
{
                                    if (num44 == 0)
{
                                        Wiring.cannonCoolDown = 120;
                                    }
                                    else if (num44 == 1)
{
                                        Wiring.bunnyCannonCoolDown = 480;
                                    }
                                    WorldGen.ShootFromCannon(num41, num42, num43, num44 + 1, num51, num52, Wiring.CurrentUser, true);
                                    return;
                                }
                            }
                        }
                        else if (type == 212)
{
                            int num54 = (int)(tile.frameX % 54 / 18);
                            int num55 = (int)(tile.frameY % 54 / 18);
                            int num56 = i - num54;
                            int num57 = j - num55;
                            short num58 = tile.frameX / 54;
                            int num59 = -1;
                            if (num54 == 1)
{
                                num59 = num55;
                            }
                            int num60 = 0;
                            if (num54 == 0)
{
                                num60 = -54;
                            }
                            if (num54 == 2)
{
                                num60 = 54;
                            }
                            if (num58 >= 1 && num60 > 0)
{
                                num60 = 0;
                            }
                            if (num58 == 0 && num60 < 0)
{
                                num60 = 0;
                            }
                            bool flag5 = false;
                            if (num60 != 0)
{
                                for (int num61 = num56; num61 < num56 + 3; num61++)
{
                                    for (int num62 = num57; num62 < num57 + 3; num62++)
{
                                        Wiring.SkipWire(num61, num62);
                                        Main.tile[num61, num62].frameX = (short)((int)Main.tile[num61, num62].frameX + num60);
                                    }
                                }
                                flag5 = true;
                            }
                            if (flag5)
{
                                NetMessage.SendTileSquare(-1, num56, num57, 3, 3, TileChangeType.None);
                            }
                            if (num59 != -1 && Wiring.snowballCannonCoolDown == 0 && Wiring.CheckMech(num56, num57, 60))
{
                                Wiring.snowballCannonCoolDown = 15;
                                float num63 = 12f + (float)Main.rand.Next(450) * 0.01f;
                                float num64 = (float)Main.rand.Next(85, 105);
                                float num65 = (float)Main.rand.Next(-35, 11);
                                int num66 = 166;
                                int num67 = 35;
                                float num68 = 3.5f;
                                Vector2 vector = new Vector2((float)((num56 + 2) * 16 - 8), (float)((num57 + 2) * 16 - 8));
                                if (tile.frameX / 54 == 0)
{
                                    num64 *= -1f;
                                    vector.X -= 12f;
                                }
                                else
{
                                    vector.X += 12f;
                                }
                                float num69 = num64;
                                float num70 = num65;
                                float num71 = (float)Math.Sqrt((double)(num69 * num69 + num70 * num70));
                                num71 = num63 / num71;
                                num69 *= num71;
                                num70 *= num71;
                                Projectile.NewProjectile(Wiring.GetProjectileSource(num56, num57), vector.X, vector.Y, num69, num70, num66, num67, num68, Wiring.CurrentUser, 0f, 0f, 0f, null);
                                return;
                            }
                        }
                        else
{
                            if (TileID.Sets.Campfires[type])
{
                                Wiring.ToggleCampFire(i, j, tile, flag, flag2);
                                return;
                            }
                            if (type == 130)
{
                                if (Main.tile[i, j - 1] != null && (!Main.tile[i, j - 1].active() || !TileID.Sets.PreventsActuationUnder[(int)Main.tile[i, j - 1].type]) && WorldGen.CanKillTile(i, j))
{
                                    tile.type = 131;
                                    WorldGen.SquareTileFrame(i, j, true);
                                    NetMessage.SendTileSquare(-1, i, j, TileChangeType.None);
                                    return;
                                }
                            }
                            else
{
                                if (type == 131)
{
                                    tile.type = 130;
                                    WorldGen.SquareTileFrame(i, j, true);
                                    NetMessage.SendTileSquare(-1, i, j, TileChangeType.None);
                                    return;
                                }
                                if (type == 387 || type == 386)
{
                                    bool flag6 = type == 387;
                                    int num72 = WorldGen.ShiftTrapdoor(i, j, true, -1).ToInt();
                                    if (num72 == 0)
{
                                        num72 = -WorldGen.ShiftTrapdoor(i, j, false, -1).ToInt();
                                    }
                                    if (num72 != 0)
{
                                        NetMessage.SendData(19, -1, -1, null, 3 - flag6.ToInt(), (float)i, (float)j, (float)num72, 0, 0, 0);
                                        return;
                                    }
                                }
                                else
{
                                    if (type == 389 || type == 388)
{
                                        bool flag7 = type == 389;
                                        WorldGen.ShiftTallGate(i, j, flag7, false);
                                        NetMessage.SendData(19, -1, -1, null, 4 + flag7.ToInt(), (float)i, (float)j, 0f, 0, 0, 0);
                                        return;
                                    }
                                    if (type == 11)
{
                                        if (WorldGen.CloseDoor(i, j, true))
{
                                            NetMessage.SendData(19, -1, -1, null, 1, (float)i, (float)j, 0f, 0, 0, 0);
                                            return;
                                        }
                                    }
                                    else if (type == 10)
{
                                        int num73 = 1;
                                        if (Main.rand.Next(2) == 0)
{
                                            num73 = -1;
                                        }
                                        if (WorldGen.OpenDoor(i, j, num73))
{
                                            NetMessage.SendData(19, -1, -1, null, 0, (float)i, (float)j, (float)num73, 0, 0, 0);
                                            return;
                                        }
                                        if (WorldGen.OpenDoor(i, j, -num73))
{
                                            NetMessage.SendData(19, -1, -1, null, 0, (float)i, (float)j, (float)(-(float)num73), 0, 0, 0);
                                            return;
                                        }
                                    }
                                    else
{
                                        if (type == 216)
{
                                            WorldGen.LaunchRocket(i, j, true);
                                            Wiring.SkipWire(i, j);
                                            return;
                                        }
                                        if (type == 497 || (type == 15 && tile.frameY / 40 == 1) || (type == 15 && tile.frameY / 40 == 20))
{
                                            int num74 = j - (int)(tile.frameY % 40 / 18);
                                            Wiring.SkipWire(i, num74);
                                            Wiring.SkipWire(i, num74 + 1);
                                            if (Wiring.CheckMech(i, num74, 60))
{
                                                Projectile.NewProjectile(Wiring.GetProjectileSource(i, num74), (float)(i * 16 + 8), (float)(num74 * 16 + 12), 0f, 0f, 733, 0, 0f, Main.myPlayer, 0f, 0f, 0f, null);
                                                return;
                                            }
                                        }
                                        else if (type == 335)
{
                                            int num75 = j - (int)(tile.frameY / 18);
                                            int num76 = i - (int)(tile.frameX / 18);
                                            Wiring.SkipWire(num76, num75);
                                            Wiring.SkipWire(num76, num75 + 1);
                                            Wiring.SkipWire(num76 + 1, num75);
                                            Wiring.SkipWire(num76 + 1, num75 + 1);
                                            if (Wiring.CheckMech(num76, num75, 30))
{
                                                WorldGen.LaunchRocketSmall(num76, num75, true);
                                                return;
                                            }
                                        }
                                        else if (type == 338)
{
                                            int num77 = j - (int)(tile.frameY / 18);
                                            int num78 = i - (int)(tile.frameX / 18);
                                            Wiring.SkipWire(num78, num77);
                                            Wiring.SkipWire(num78, num77 + 1);
                                            if (Wiring.CheckMech(num78, num77, 30))
{
                                                bool flag8 = false;
                                                for (int num79 = 0; num79 < 1000; num79++)
{
                                                    if (Main.projectile[num79].active && Main.projectile[num79].aiStyle == 73 && Main.projectile[num79].ai[0] == (float)num78 && Main.projectile[num79].ai[1] == (float)num77)
{
                                                        flag8 = true;
                                                        break;
                                                    }
                                                }
                                                if (!flag8)
{
                                                    int num80 = 419 + Main.rand.Next(4);
                                                    Projectile.NewProjectile(Wiring.GetProjectileSource(num78, num77), (float)(num78 * 16 + 8), (float)(num77 * 16 + 2), 0f, 0f, num80, 0, 0f, Main.myPlayer, (float)num78, (float)num77, 0f, null);
                                                    return;
                                                }
                                            }
                                        }
                                        else if (type == 235)
{
                                            int num81 = i - (int)(tile.frameX / 18);
                                            if (tile.wall != 87 || (double)j <= Main.worldSurface || NPC.downedPlantBoss)
{
                                                if (Wiring._teleport[0].X == -1f)
{
                                                    Wiring._teleport[0].X = (float)num81;
                                                    Wiring._teleport[0].Y = (float)j;
                                                    if (tile.halfBrick())
{
                                                        Vector2[] teleport = Wiring._teleport;
                                                        int num82 = 0;
                                                        teleport[num82].Y = teleport[num82].Y + 0.5f;
                                                        return;
                                                    }
                                                }
                                                else if (Wiring._teleport[0].X != (float)num81 || Wiring._teleport[0].Y != (float)j)
{
                                                    Wiring._teleport[1].X = (float)num81;
                                                    Wiring._teleport[1].Y = (float)j;
                                                    if (tile.halfBrick())
{
                                                        Vector2[] teleport2 = Wiring._teleport;
                                                        int num83 = 1;
                                                        teleport2[num83].Y = teleport2[num83].Y + 0.5f;
                                                        return;
                                                    }
                                                }
                                            }
                                        }
                                        else
{
                                            if (TileID.Sets.Torches[type])
{
                                                Wiring.ToggleTorch(i, j, tile, flag);
                                                return;
                                            }
                                            if (type == 429)
{
                                                short num84 = Main.tile[i, j].frameX / 18;
                                                bool flag9 = num84 % 2 >= 1;
                                                bool flag10 = num84 % 4 >= 2;
                                                bool flag11 = num84 % 8 >= 4;
                                                bool flag12 = num84 % 16 >= 8;
                                                bool flag13 = false;
                                                short num85 = 0;
                                                switch (Wiring._currentWireColor)
{
                                                case 1:
                                                    num85 = 18;
                                                    flag13 = !flag9;
                                                    break;
                                                case 2:
                                                    num85 = 72;
                                                    flag13 = !flag11;
                                                    break;
                                                case 3:
                                                    num85 = 36;
                                                    flag13 = !flag10;
                                                    break;
                                                case 4:
                                                    num85 = 144;
                                                    flag13 = !flag12;
                                                    break;
                                                }
                                                if (flag13)
{
                                                    Tile tile4 = tile;
                                                    tile4.frameX += num85;
                                                }
                                                else
{
                                                    Tile tile5 = tile;
                                                    tile5.frameX -= num85;
                                                }
                                                NetMessage.SendTileSquare(-1, i, j, TileChangeType.None);
                                                return;
                                            }
                                            if (type == 149)
{
                                                Wiring.ToggleHolidayLight(i, j, tile, flag);
                                                return;
                                            }
                                            if (type == 244)
{
                                                int num86;
                                                for (num86 = (int)(tile.frameX / 18); num86 >= 3; num86 -= 3)
{
                                                }
                                                int num87;
                                                for (num87 = (int)(tile.frameY / 18); num87 >= 3; num87 -= 3)
{
                                                }
                                                int num88 = i - num86;
                                                int num89 = j - num87;
                                                int num90 = 54;
                                                if (Main.tile[num88, num89].frameX >= 54)
{
                                                    num90 = -54;
                                                }
                                                for (int num91 = num88; num91 < num88 + 3; num91++)
{
                                                    for (int num92 = num89; num92 < num89 + 2; num92++)
{
                                                        Wiring.SkipWire(num91, num92);
                                                        Main.tile[num91, num92].frameX = (short)((int)Main.tile[num91, num92].frameX + num90);
                                                    }
                                                }
                                                NetMessage.SendTileSquare(-1, num88, num89, 3, 2, TileChangeType.None);
                                                return;
                                            }
                                            if (type == 565)
{
                                                int num93;
                                                for (num93 = (int)(tile.frameX / 18); num93 >= 2; num93 -= 2)
{
                                                }
                                                int num94;
                                                for (num94 = (int)(tile.frameY / 18); num94 >= 2; num94 -= 2)
{
                                                }
                                                int num95 = i - num93;
                                                int num96 = j - num94;
                                                int num97 = 36;
                                                if (Main.tile[num95, num96].frameX >= 36)
{
                                                    num97 = -36;
                                                }
                                                for (int num98 = num95; num98 < num95 + 2; num98++)
{
                                                    for (int num99 = num96; num99 < num96 + 2; num99++)
{
                                                        Wiring.SkipWire(num98, num99);
                                                        Main.tile[num98, num99].frameX = (short)((int)Main.tile[num98, num99].frameX + num97);
                                                    }
                                                }
                                                NetMessage.SendTileSquare(-1, num95, num96, 2, 2, TileChangeType.None);
                                                return;
                                            }
                                            if (type == 42)
{
                                                Wiring.ToggleHangingLantern(i, j, tile, flag, flag2);
                                                return;
                                            }
                                            if (type == 93)
{
                                                Wiring.ToggleLamp(i, j, tile, flag, flag2);
                                                return;
                                            }
                                            if (type == 126 || type == 95 || type == 100 || type == 173 || type == 564)
{
                                                Wiring.Toggle2x2Light(i, j, tile, flag, flag2);
                                                return;
                                            }
                                            if (type == 593)
{
                                                Wiring.SkipWire(i, j);
                                                short num100;
                                                if (Main.tile[i, j].frameX == 0)
{
                                                    num100 = 18;
                                                }
                                                else
{
                                                    num100 = -18;
                                                }
                                                Tile tile6 = Main.tile[i, j];
                                                tile6.frameX += num100;
                                                if (Main.netMode == 2)
{
                                                    NetMessage.SendTileSquare(-1, i, j, 1, 1, TileChangeType.None);
                                                }
                                                int num101 = ((num100 > 0) ? 4 : 3);
                                                Animation.NewTemporaryAnimation(num101, 593, i, j);
                                                NetMessage.SendTemporaryAnimation(-1, num101, 593, i, j);
                                                return;
                                            }
                                            if (type == 594)
{
                                                int num102;
                                                for (num102 = (int)(tile.frameY / 18); num102 >= 2; num102 -= 2)
{
                                                }
                                                num102 = j - num102;
                                                int num103 = (int)(tile.frameX / 18);
                                                if (num103 > 1)
{
                                                    num103 -= 2;
                                                }
                                                num103 = i - num103;
                                                Wiring.SkipWire(num103, num102);
                                                Wiring.SkipWire(num103, num102 + 1);
                                                Wiring.SkipWire(num103 + 1, num102);
                                                Wiring.SkipWire(num103 + 1, num102 + 1);
                                                short num104;
                                                if (Main.tile[num103, num102].frameX == 0)
{
                                                    num104 = 36;
                                                }
                                                else
{
                                                    num104 = -36;
                                                }
                                                for (int num105 = 0; num105 < 2; num105++)
{
                                                    for (int num106 = 0; num106 < 2; num106++)
{
                                                        Tile tile7 = Main.tile[num103 + num105, num102 + num106];
                                                        tile7.frameX += num104;
                                                    }
                                                }
                                                if (Main.netMode == 2)
{
                                                    NetMessage.SendTileSquare(-1, num103, num102, 2, 2, TileChangeType.None);
                                                }
                                                int num107 = ((num104 > 0) ? 4 : 3);
                                                Animation.NewTemporaryAnimation(num107, 594, num103, num102);
                                                NetMessage.SendTemporaryAnimation(-1, num107, 594, num103, num102);
                                                return;
                                            }
                                            if (type == 34)
{
                                                Wiring.ToggleChandelier(i, j, tile, flag, flag2);
                                                return;
                                            }
                                            if (type == 314)
{
                                                if (Wiring.CheckMech(i, j, 5))
{
                                                    Minecart.FlipSwitchTrack(i, j);
                                                    return;
                                                }
                                            }
                                            else
{
                                                if (type == 33 || type == 174 || type == 49 || type == 372 || type == 646)
{
                                                    Wiring.ToggleCandle(i, j, tile, flag);
                                                    return;
                                                }
                                                if (type == 92)
{
                                                    Wiring.ToggleLampPost(i, j, tile, flag, flag2);
                                                    return;
                                                }
                                                if (type == 137)
{
                                                    int num108 = (int)(tile.frameY / 18);
                                                    Vector2 zero = Vector2.Zero;
                                                    float num109 = 0f;
                                                    float num110 = 0f;
                                                    int num111 = 0;
                                                    int num112 = 0;
                                                    switch (num108)
{
                                                    case 0:
                                                    case 1:
                                                    case 2:
                                                    case 5:
                                                        if (Wiring.CheckMech(i, j, 200))
{
                                                            int num113 = ((tile.frameX == 0) ? (-1) : ((tile.frameX == 18) ? 1 : 0));
                                                            int num114 = ((tile.frameX < 36) ? 0 : ((tile.frameX < 72) ? (-1) : 1));
                                                            zero = new Vector2((float)(i * 16 + 8 + 10 * num113), (float)(j * 16 + 8 + 10 * num114));
                                                            float num115 = 3f;
                                                            if (num108 == 0)
{
                                                                num111 = 98;
                                                                num112 = 20;
                                                                num115 = 12f;
                                                            }
                                                            if (num108 == 1)
{
                                                                num111 = 184;
                                                                num112 = 40;
                                                                num115 = 12f;
                                                            }
                                                            if (num108 == 2)
{
                                                                num111 = 187;
                                                                num112 = 40;
                                                                num115 = 5f;
                                                            }
                                                            if (num108 == 5)
{
                                                                num111 = 980;
                                                                num112 = 30;
                                                                num115 = 12f;
                                                            }
                                                            num109 = (float)num113 * num115;
                                                            num110 = (float)num114 * num115;
                                                        }
                                                        break;
                                                    case 3:
                                                        if (Wiring.CheckMech(i, j, 300))
{
                                                            int num116 = 200;
                                                            for (int num117 = 0; num117 < 1000; num117++)
{
                                                                if (Main.projectile[num117].active && Main.projectile[num117].type == num111)
{
                                                                    float num118 = (new Vector2((float)(i * 16 + 8), (float)(j * 18 + 8)) - Main.projectile[num117].Center).Length();
                                                                    if (num118 < 50f)
{
                                                                        num116 -= 50;
                                                                    }
                                                                    else if (num118 < 100f)
{
                                                                        num116 -= 15;
                                                                    }
                                                                    else if (num118 < 200f)
{
                                                                        num116 -= 10;
                                                                    }
                                                                    else if (num118 < 300f)
{
                                                                        num116 -= 8;
                                                                    }
                                                                    else if (num118 < 400f)
{
                                                                        num116 -= 6;
                                                                    }
                                                                    else if (num118 < 500f)
{
                                                                        num116 -= 5;
                                                                    }
                                                                    else if (num118 < 700f)
{
                                                                        num116 -= 4;
                                                                    }
                                                                    else if (num118 < 900f)
{
                                                                        num116 -= 3;
                                                                    }
                                                                    else if (num118 < 1200f)
{
                                                                        num116 -= 2;
                                                                    }
                                                                    else
{
                                                                        num116--;
                                                                    }
                                                                }
                                                            }
                                                            if (num116 > 0)
{
                                                                num111 = 185;
                                                                num112 = 40;
                                                                int num119 = 0;
                                                                int num120 = 0;
                                                                switch (tile.frameX / 18)
{
                                                                case 0:
                                                                case 1:
                                                                    num119 = 0;
                                                                    num120 = 1;
                                                                    break;
                                                                case 2:
                                                                    num119 = 0;
                                                                    num120 = -1;
                                                                    break;
                                                                case 3:
                                                                    num119 = -1;
                                                                    num120 = 0;
                                                                    break;
                                                                case 4:
                                                                    num119 = 1;
                                                                    num120 = 0;
                                                                    break;
                                                                }
                                                                num109 = (float)(4 * num119) + (float)Main.rand.Next(-20 + ((num119 == 1) ? 20 : 0), 21 - ((num119 == -1) ? 20 : 0)) * 0.05f;
                                                                num110 = (float)(4 * num120) + (float)Main.rand.Next(-20 + ((num120 == 1) ? 20 : 0), 21 - ((num120 == -1) ? 20 : 0)) * 0.05f;
                                                                zero = new Vector2((float)(i * 16 + 8 + 14 * num119), (float)(j * 16 + 8 + 14 * num120));
                                                            }
                                                        }
                                                        break;
                                                    case 4:
                                                        if (Wiring.CheckMech(i, j, 90))
{
                                                            int num121 = 0;
                                                            int num122 = 0;
                                                            switch (tile.frameX / 18)
{
                                                            case 0:
                                                            case 1:
                                                                num121 = 0;
                                                                num122 = 1;
                                                                break;
                                                            case 2:
                                                                num121 = 0;
                                                                num122 = -1;
                                                                break;
                                                            case 3:
                                                                num121 = -1;
                                                                num122 = 0;
                                                                break;
                                                            case 4:
                                                                num121 = 1;
                                                                num122 = 0;
                                                                break;
                                                            }
                                                            num109 = (float)(8 * num121);
                                                            num110 = (float)(8 * num122);
                                                            num112 = 60;
                                                            num111 = 186;
                                                            zero = new Vector2((float)(i * 16 + 8 + 18 * num121), (float)(j * 16 + 8 + 18 * num122));
                                                        }
                                                        break;
                                                    }
                                                    switch (num108 + 10)
{
                                                    case 0:
                                                        if (Wiring.CheckMech(i, j, 200))
{
                                                            int num123 = -1;
                                                            if (tile.frameX != 0)
{
                                                                num123 = 1;
                                                            }
                                                            num109 = (float)(12 * num123);
                                                            num112 = 20;
                                                            num111 = 98;
                                                            zero = new Vector2((float)(i * 16 + 8), (float)(j * 16 + 7));
                                                            zero.X += (float)(10 * num123);
                                                            zero.Y += 2f;
                                                        }
                                                        break;
                                                    case 1:
                                                        if (Wiring.CheckMech(i, j, 200))
{
                                                            int num124 = -1;
                                                            if (tile.frameX != 0)
{
                                                                num124 = 1;
                                                            }
                                                            num109 = (float)(12 * num124);
                                                            num112 = 40;
                                                            num111 = 184;
                                                            zero = new Vector2((float)(i * 16 + 8), (float)(j * 16 + 7));
                                                            zero.X += (float)(10 * num124);
                                                            zero.Y += 2f;
                                                        }
                                                        break;
                                                    case 2:
                                                        if (Wiring.CheckMech(i, j, 200))
{
                                                            int num125 = -1;
                                                            if (tile.frameX != 0)
{
                                                                num125 = 1;
                                                            }
                                                            num109 = (float)(5 * num125);
                                                            num112 = 40;
                                                            num111 = 187;
                                                            zero = new Vector2((float)(i * 16 + 8), (float)(j * 16 + 7));
                                                            zero.X += (float)(10 * num125);
                                                            zero.Y += 2f;
                                                        }
                                                        break;
                                                    case 3:
                                                        if (Wiring.CheckMech(i, j, 300))
{
                                                            num111 = 185;
                                                            int num126 = 200;
                                                            for (int num127 = 0; num127 < 1000; num127++)
{
                                                                if (Main.projectile[num127].active && Main.projectile[num127].type == num111)
{
                                                                    float num128 = (new Vector2((float)(i * 16 + 8), (float)(j * 18 + 8)) - Main.projectile[num127].Center).Length();
                                                                    if (num128 < 50f)
{
                                                                        num126 -= 50;
                                                                    }
                                                                    else if (num128 < 100f)
{
                                                                        num126 -= 15;
                                                                    }
                                                                    else if (num128 < 200f)
{
                                                                        num126 -= 10;
                                                                    }
                                                                    else if (num128 < 300f)
{
                                                                        num126 -= 8;
                                                                    }
                                                                    else if (num128 < 400f)
{
                                                                        num126 -= 6;
                                                                    }
                                                                    else if (num128 < 500f)
{
                                                                        num126 -= 5;
                                                                    }
                                                                    else if (num128 < 700f)
{
                                                                        num126 -= 4;
                                                                    }
                                                                    else if (num128 < 900f)
{
                                                                        num126 -= 3;
                                                                    }
                                                                    else if (num128 < 1200f)
{
                                                                        num126 -= 2;
                                                                    }
                                                                    else
{
                                                                        num126--;
                                                                    }
                                                                }
                                                            }
                                                            if (num126 > 0)
{
                                                                num109 = (float)Main.rand.Next(-20, 21) * 0.05f;
                                                                num110 = 4f + (float)Main.rand.Next(0, 21) * 0.05f;
                                                                num112 = 40;
                                                                zero = new Vector2((float)(i * 16 + 8), (float)(j * 16 + 16));
                                                                zero.Y += 6f;
                                                                Projectile.NewProjectile(Wiring.GetProjectileSource(i, j), (float)((int)zero.X), (float)((int)zero.Y), num109, num110, num111, num112, 2f, Main.myPlayer, 0f, 0f, 0f, null);
                                                            }
                                                        }
                                                        break;
                                                    case 4:
                                                        if (Wiring.CheckMech(i, j, 90))
{
                                                            num109 = 0f;
                                                            num110 = 8f;
                                                            num112 = 60;
                                                            num111 = 186;
                                                            zero = new Vector2((float)(i * 16 + 8), (float)(j * 16 + 16));
                                                            zero.Y += 10f;
                                                        }
                                                        break;
                                                    }
                                                    if (num111 != 0)
{
                                                        Projectile.NewProjectile(Wiring.GetProjectileSource(i, j), (float)((int)zero.X), (float)((int)zero.Y), num109, num110, num111, num112, 2f, Main.myPlayer, 0f, 0f, 0f, null);
                                                        return;
                                                    }
                                                }
                                                else
{
                                                    if (type == 443)
{
                                                        Wiring.GeyserTrap(i, j);
                                                        return;
                                                    }
                                                    if (type == 21 || type == 467)
{
                                                        Wiring.Hopper(i, j);
                                                        return;
                                                    }
                                                    if (type == 219 || type == 642)
{
                                                        Wiring.Extractinator(i, j);
                                                        return;
                                                    }
                                                    if (type == 531)
{
                                                        int num129 = (int)(tile.frameX / 36);
                                                        int num130 = (int)(tile.frameY / 54);
                                                        int num131 = i - ((int)tile.frameX - num129 * 36) / 18;
                                                        int num132 = j - ((int)tile.frameY - num130 * 54) / 18;
                                                        if (Wiring.CheckMech(num131, num132, 900))
{
                                                            Vector2 vector2 = new Vector2((float)(num131 + 1), (float)num132) * 16f;
                                                            vector2.Y += 28f;
                                                            int num133 = 99;
                                                            int num134 = 70;
                                                            float num135 = 10f;
                                                            if (num133 != 0)
{
                                                                Projectile.NewProjectile(Wiring.GetProjectileSource(num131, num132), (float)((int)vector2.X), (float)((int)vector2.Y), 0f, 0f, num133, num134, num135, Main.myPlayer, 0f, 0f, 0f, null);
                                                                return;
                                                            }
                                                        }
                                                    }
                                                    else
{
                                                        if (type == 139 || type == 35)
{
                                                            WorldGen.SwitchMB(i, j);
                                                            return;
                                                        }
                                                        if (type == 207)
{
                                                            WorldGen.SwitchFountain(i, j);
                                                            return;
                                                        }
                                                        if (type == 410 || type == 480 || type == 509 || type == 657 || type == 658 || type == 720 || type == 721 || type == 725 || type == 733)
{
                                                            WorldGen.SwitchMonolith(i, j);
                                                            return;
                                                        }
                                                        if (type == 455)
{
                                                            BirthdayParty.ToggleManualParty();
                                                            return;
                                                        }
                                                        if (type == 141)
{
                                                            WorldGen.KillTile(i, j, false, false, true);
                                                            NetMessage.SendTileSquare(-1, i, j, TileChangeType.None);
                                                            Projectile.NewProjectile(Wiring.GetProjectileSource(i, j), (float)(i * 16 + 8), (float)(j * 16 + 8), 0f, 0f, 108, 500, 10f, Main.myPlayer, 0f, 0f, 0f, null);
                                                            return;
                                                        }
                                                        if (type == 210)
{
                                                            Wiring.ExplodeMine(i, j);
                                                            return;
                                                        }
                                                        if (type == 142 || type == 143)
{
                                                            int num136 = j - (int)(tile.frameY / 18);
                                                            int num137 = (int)(tile.frameX / 18);
                                                            if (num137 > 1)
{
                                                                num137 -= 2;
                                                            }
                                                            num137 = i - num137;
                                                            Wiring.SkipWire(num137, num136);
                                                            Wiring.SkipWire(num137, num136 + 1);
                                                            Wiring.SkipWire(num137 + 1, num136);
                                                            Wiring.SkipWire(num137 + 1, num136 + 1);
                                                            if (type == 142)
{
                                                                for (int num138 = 0; num138 < 4; num138++)
{
                                                                    if (Wiring._numInPump >= 19)
{
                                                                        return;
                                                                    }
                                                                    int num139;
                                                                    int num140;
                                                                    if (num138 == 0)
{
                                                                        num139 = num137;
                                                                        num140 = num136 + 1;
                                                                    }
                                                                    else if (num138 == 1)
{
                                                                        num139 = num137 + 1;
                                                                        num140 = num136 + 1;
                                                                    }
                                                                    else if (num138 == 2)
{
                                                                        num139 = num137;
                                                                        num140 = num136;
                                                                    }
                                                                    else
{
                                                                        num139 = num137 + 1;
                                                                        num140 = num136;
                                                                    }
                                                                    Wiring._inPumpX[Wiring._numInPump] = num139;
                                                                    Wiring._inPumpY[Wiring._numInPump] = num140;
                                                                    Wiring._numInPump++;
                                                                }
                                                                return;
                                                            }
                                                            for (int num141 = 0; num141 < 4; num141++)
{
                                                                if (Wiring._numOutPump >= 19)
{
                                                                    return;
                                                                }
                                                                int num139;
                                                                int num140;
                                                                if (num141 == 0)
{
                                                                    num139 = num137;
                                                                    num140 = num136 + 1;
                                                                }
                                                                else if (num141 == 1)
{
                                                                    num139 = num137 + 1;
                                                                    num140 = num136 + 1;
                                                                }
                                                                else if (num141 == 2)
{
                                                                    num139 = num137;
                                                                    num140 = num136;
                                                                }
                                                                else
{
                                                                    num139 = num137 + 1;
                                                                    num140 = num136;
                                                                }
                                                                Wiring._outPumpX[Wiring._numOutPump] = num139;
                                                                Wiring._outPumpY[Wiring._numOutPump] = num140;
                                                                Wiring._numOutPump++;
                                                            }
                                                            return;
                                                        }
                                                        else if (type == 105)
{
                                                            int num142 = j - (int)(tile.frameY / 18);
                                                            int num143 = (int)(tile.frameX / 18);
                                                            int num144 = 0;
                                                            while (num143 >= 2)
{
                                                                num143 -= 2;
                                                                num144++;
                                                            }
                                                            num143 = i - num143;
                                                            num143 = i - (int)(tile.frameX % 36 / 18);
                                                            num142 = j - (int)(tile.frameY % 54 / 18);
                                                            int num145 = (int)(tile.frameY / 54);
                                                            num145 %= 3;
                                                            num144 = (int)(tile.frameX / 36) + num145 * 55;
                                                            Wiring.SkipWire(num143, num142);
                                                            Wiring.SkipWire(num143, num142 + 1);
                                                            Wiring.SkipWire(num143, num142 + 2);
                                                            Wiring.SkipWire(num143 + 1, num142);
                                                            Wiring.SkipWire(num143 + 1, num142 + 1);
                                                            Wiring.SkipWire(num143 + 1, num142 + 2);
                                                            int num146 = num143 * 16 + 16;
                                                            int num147 = (num142 + 3) * 16;
                                                            int num148 = -1;
                                                            int num149 = -1;
                                                            bool flag14 = true;
                                                            bool flag15 = false;
                                                            if (num144 != 5)
{
                                                                if (num144 != 13)
{
                                                                    switch (num144)
{
                                                                    case 30:
                                                                        num149 = 6;
                                                                        break;
                                                                    case 35:
                                                                        num149 = 2;
                                                                        break;
                                                                    case 51:
                                                                        num149 = (int)Utils.SelectRandom<short>(Main.rand, new short[] { 299, 538 });
                                                                        break;
                                                                    case 52:
                                                                        num149 = 356;
                                                                        break;
                                                                    case 53:
                                                                        num149 = 357;
                                                                        break;
                                                                    case 54:
                                                                        num149 = (int)Utils.SelectRandom<short>(Main.rand, new short[] { 355, 358 });
                                                                        break;
                                                                    case 55:
                                                                        num149 = (int)Utils.SelectRandom<short>(Main.rand, new short[] { 367, 366 });
                                                                        break;
                                                                    case 56:
                                                                        num149 = (int)Utils.SelectRandom<short>(Main.rand, new short[] { 359, 359, 359, 359, 360 });
                                                                        break;
                                                                    case 57:
                                                                        num149 = 377;
                                                                        break;
                                                                    case 58:
                                                                        num149 = 300;
                                                                        break;
                                                                    case 59:
                                                                        num149 = (int)Utils.SelectRandom<short>(Main.rand, new short[] { 364, 362 });
                                                                        break;
                                                                    case 60:
                                                                        num149 = 148;
                                                                        break;
                                                                    case 61:
                                                                        num149 = 361;
                                                                        break;
                                                                    case 62:
                                                                        num149 = (int)Utils.SelectRandom<short>(Main.rand, new short[] { 487, 486, 485 });
                                                                        break;
                                                                    case 63:
                                                                        num149 = 164;
                                                                        flag14 &= NPC.MechSpawn((float)num146, (float)num147, 165);
                                                                        break;
                                                                    case 64:
                                                                        num149 = 86;
                                                                        flag15 = true;
                                                                        break;
                                                                    case 65:
                                                                        num149 = 490;
                                                                        break;
                                                                    case 66:
                                                                        num149 = 82;
                                                                        break;
                                                                    case 67:
                                                                        num149 = 449;
                                                                        break;
                                                                    case 68:
                                                                        num149 = 167;
                                                                        break;
                                                                    case 69:
                                                                        num149 = 480;
                                                                        break;
                                                                    case 70:
                                                                        num149 = 48;
                                                                        break;
                                                                    case 71:
                                                                        num149 = (int)Utils.SelectRandom<short>(Main.rand, new short[] { 170, 180, 171 });
                                                                        flag15 = true;
                                                                        break;
                                                                    case 72:
                                                                        num149 = 481;
                                                                        break;
                                                                    case 73:
                                                                        num149 = 482;
                                                                        break;
                                                                    case 74:
                                                                        num149 = 430;
                                                                        break;
                                                                    case 75:
                                                                        num149 = 489;
                                                                        break;
                                                                    case 76:
                                                                        num149 = 611;
                                                                        break;
                                                                    case 77:
                                                                        num149 = 602;
                                                                        break;
                                                                    case 78:
                                                                        num149 = (int)Utils.SelectRandom<short>(Main.rand, new short[] { 595, 596, 599, 597, 600, 598 });
                                                                        break;
                                                                    case 79:
                                                                        num149 = (int)Utils.SelectRandom<short>(Main.rand, new short[] { 616, 617 });
                                                                        break;
                                                                    case 80:
                                                                        num149 = (int)Utils.SelectRandom<short>(Main.rand, new short[] { 671, 672 });
                                                                        break;
                                                                    case 81:
                                                                        num149 = 673;
                                                                        break;
                                                                    case 82:
                                                                        num149 = (int)Utils.SelectRandom<short>(Main.rand, new short[] { 674, 675 });
                                                                        break;
                                                                    }
                                                                }
                                                                else
{
                                                                    num149 = 24;
                                                                }
                                                            }
                                                            else
{
                                                                num149 = 73;
                                                            }
                                                            if (num149 != -1 && Wiring.CheckMech(num143, num142, 30) && NPC.MechSpawn((float)num146, (float)num147, num149) && flag14)
{
                                                                if (!flag15 || !Collision.SolidTiles(num143 - 2, num143 + 3, num142, num142 + 2))
{
                                                                    num148 = NPC.NewNPC(Wiring.GetNPCSource(num143, num142), num146, num147, num149, 0, 0f, 0f, 0f, 0f, 255);
                                                                }
                                                                else
{
                                                                    Vector2 vector3 = new Vector2((float)(num146 - 4), (float)(num147 - 22)) - new Vector2(10f);
                                                                    Utils.PoofOfSmoke(vector3);
                                                                    NetMessage.SendData(106, -1, -1, null, (int)vector3.X, vector3.Y, 0f, 0f, 0, 0, 0);
                                                                }
                                                            }
                                                            if (num148 <= -1)
{
                                                                if (num144 == 4)
{
                                                                    if (Wiring.CheckMech(num143, num142, 30) && NPC.MechSpawn((float)num146, (float)num147, 1))
{
                                                                        num148 = NPC.NewNPC(Wiring.GetNPCSource(num143, num142), num146, num147 - 12, 1, 0, 0f, 0f, 0f, 0f, 255);
                                                                    }
                                                                }
                                                                else if (num144 == 7)
{
                                                                    if (Wiring.CheckMech(num143, num142, 30) && NPC.MechSpawn((float)num146, (float)num147, 49))
{
                                                                        num148 = NPC.NewNPC(Wiring.GetNPCSource(num143, num142), num146 - 4, num147 - 6, 49, 0, 0f, 0f, 0f, 0f, 255);
                                                                    }
                                                                }
                                                                else if (num144 == 8)
{
                                                                    if (Wiring.CheckMech(num143, num142, 30) && NPC.MechSpawn((float)num146, (float)num147, 55))
{
                                                                        num148 = NPC.NewNPC(Wiring.GetNPCSource(num143, num142), num146, num147 - 12, 55, 0, 0f, 0f, 0f, 0f, 255);
                                                                    }
                                                                }
                                                                else if (num144 == 9)
{
                                                                    int num150 = 46;
                                                                    if (BirthdayParty.PartyIsUp)
{
                                                                        num150 = 540;
                                                                    }
                                                                    if (Wiring.CheckMech(num143, num142, 30) && NPC.MechSpawn((float)num146, (float)num147, num150))
{
                                                                        num148 = NPC.NewNPC(Wiring.GetNPCSource(num143, num142), num146, num147 - 12, num150, 0, 0f, 0f, 0f, 0f, 255);
                                                                    }
                                                                }
                                                                else if (num144 == 10)
{
                                                                    if (Wiring.CheckMech(num143, num142, 30) && NPC.MechSpawn((float)num146, (float)num147, 21))
{
                                                                        num148 = NPC.NewNPC(Wiring.GetNPCSource(num143, num142), num146, num147, 21, 0, 0f, 0f, 0f, 0f, 255);
                                                                    }
                                                                }
                                                                else if (num144 == 16)
{
                                                                    if (Wiring.CheckMech(num143, num142, 30) && NPC.MechSpawn((float)num146, (float)num147, 42))
{
                                                                        if (!Collision.SolidTiles(num143 - 1, num143 + 1, num142, num142 + 1))
{
                                                                            num148 = NPC.NewNPC(Wiring.GetNPCSource(num143, num142), num146, num147 - 12, 42, 0, 0f, 0f, 0f, 0f, 255);
                                                                        }
                                                                        else
{
                                                                            Vector2 vector4 = new Vector2((float)(num146 - 4), (float)(num147 - 22)) - new Vector2(10f);
                                                                            Utils.PoofOfSmoke(vector4);
                                                                            NetMessage.SendData(106, -1, -1, null, (int)vector4.X, vector4.Y, 0f, 0f, 0, 0, 0);
                                                                        }
                                                                    }
                                                                }
                                                                else if (num144 == 18)
{
                                                                    if (Wiring.CheckMech(num143, num142, 30) && NPC.MechSpawn((float)num146, (float)num147, 67))
{
                                                                        num148 = NPC.NewNPC(Wiring.GetNPCSource(num143, num142), num146, num147 - 12, 67, 0, 0f, 0f, 0f, 0f, 255);
                                                                    }
                                                                }
                                                                else if (num144 == 23)
{
                                                                    if (Wiring.CheckMech(num143, num142, 30) && NPC.MechSpawn((float)num146, (float)num147, 63))
{
                                                                        num148 = NPC.NewNPC(Wiring.GetNPCSource(num143, num142), num146, num147 - 12, 63, 0, 0f, 0f, 0f, 0f, 255);
                                                                    }
                                                                }
                                                                else if (num144 == 27)
{
                                                                    if (Wiring.CheckMech(num143, num142, 30) && NPC.MechSpawn((float)num146, (float)num147, 85))
{
                                                                        num148 = NPC.NewNPC(Wiring.GetNPCSource(num143, num142), num146 - 9, num147, 85, 0, 0f, 0f, 0f, 0f, 255);
                                                                    }
                                                                }
                                                                else if (num144 == 28)
{
                                                                    if (Wiring.CheckMech(num143, num142, 30) && NPC.MechSpawn((float)num146, (float)num147, 74))
{
                                                                        num148 = NPC.NewNPC(Wiring.GetNPCSource(num143, num142), num146, num147 - 12, (int)Utils.SelectRandom<short>(Main.rand, new short[] { 74, 297, 298 }), 0, 0f, 0f, 0f, 0f, 255);
                                                                    }
                                                                }
                                                                else if (num144 == 34)
{
                                                                    for (int num151 = 0; num151 < 2; num151++)
{
                                                                        for (int num152 = 0; num152 < 3; num152++)
{
                                                                            Tile tile8 = Main.tile[num143 + num151, num142 + num152];
                                                                            tile8.type = 349;
                                                                            tile8.frameX = (short)(num151 * 18 + 216);
                                                                            tile8.frameY = (short)(num152 * 18);
                                                                        }
                                                                    }
                                                                    Animation.NewTemporaryAnimation(0, 349, num143, num142);
                                                                    if (Main.netMode == 2)
{
                                                                        NetMessage.SendTileSquare(-1, num143, num142, 2, 3, TileChangeType.None);
                                                                    }
                                                                }
                                                                else if (num144 == 42)
{
                                                                    if (Wiring.CheckMech(num143, num142, 30) && NPC.MechSpawn((float)num146, (float)num147, 58))
{
                                                                        num148 = NPC.NewNPC(Wiring.GetNPCSource(num143, num142), num146, num147 - 12, 58, 0, 0f, 0f, 0f, 0f, 255);
                                                                    }
                                                                }
                                                                else if (num144 == 37)
{
                                                                    if (Wiring.CheckMech(num143, num142, 600) && Item.MechSpawn((float)num146, (float)num147, 58) && Item.MechSpawn((float)num146, (float)num147, 1734) && Item.MechSpawn((float)num146, (float)num147, 1867))
{
                                                                        Item.NewItem(Wiring.GetItemSource(num146, num147), num146, num147 - 16, 0, 0, 58, 1, false, 0, false);
                                                                    }
                                                                }
                                                                else if (num144 == 50)
{
                                                                    if (Wiring.CheckMech(num143, num142, 30) && NPC.MechSpawn((float)num146, (float)num147, 65))
{
                                                                        if (!Collision.SolidTiles(num143 - 2, num143 + 3, num142, num142 + 2))
{
                                                                            num148 = NPC.NewNPC(Wiring.GetNPCSource(num143, num142), num146, num147 - 12, 65, 0, 0f, 0f, 0f, 0f, 255);
                                                                        }
                                                                        else
{
                                                                            Vector2 vector5 = new Vector2((float)(num146 - 4), (float)(num147 - 22)) - new Vector2(10f);
                                                                            Utils.PoofOfSmoke(vector5);
                                                                            NetMessage.SendData(106, -1, -1, null, (int)vector5.X, vector5.Y, 0f, 0f, 0, 0, 0);
                                                                        }
                                                                    }
                                                                }
                                                                else if (num144 == 2)
{
                                                                    if (Wiring.CheckMech(num143, num142, 600) && Item.MechSpawn((float)num146, (float)num147, 184) && Item.MechSpawn((float)num146, (float)num147, 1735) && Item.MechSpawn((float)num146, (float)num147, 1868))
{
                                                                        Item.NewItem(Wiring.GetItemSource(num146, num147), num146, num147 - 16, 0, 0, 184, 1, false, 0, false);
                                                                    }
                                                                }
                                                                else if (num144 == 17)
{
                                                                    if (Wiring.CheckMech(num143, num142, 600) && Item.MechSpawn((float)num146, (float)num147, 166))
{
                                                                        Item.NewItem(Wiring.GetItemSource(num146, num147), num146, num147 - 20, 0, 0, 166, 1, false, 0, false);
                                                                    }
                                                                }
                                                                else if (num144 == 40)
{
                                                                    if (Wiring.CheckMech(num143, num142, 300))
{
                                                                        int num153 = 50;
                                                                        int[] array = new int[num153];
                                                                        int num154 = 0;
                                                                        for (int num155 = 0; num155 < Main.maxNPCs; num155++)
{
                                                                            if (Main.npc[num155].active && (Main.npc[num155].type == 17 || Main.npc[num155].type == 19 || Main.npc[num155].type == 22 || Main.npc[num155].type == 38 || Main.npc[num155].type == 54 || Main.npc[num155].type == 107 || Main.npc[num155].type == 108 || Main.npc[num155].type == 142 || Main.npc[num155].type == 160 || Main.npc[num155].type == 207 || Main.npc[num155].type == 209 || Main.npc[num155].type == 227 || Main.npc[num155].type == 228 || Main.npc[num155].type == 229 || Main.npc[num155].type == 368 || Main.npc[num155].type == 369 || Main.npc[num155].type == 550 || Main.npc[num155].type == 441 || Main.npc[num155].type == 588))
{
                                                                                array[num154] = num155;
                                                                                num154++;
                                                                                if (num154 >= num153)
{
                                                                                    break;
                                                                                }
                                                                            }
                                                                        }
                                                                        if (num154 > 0)
{
                                                                            int num156 = array[Main.rand.Next(num154)];
                                                                            Main.npc[num156].Teleport(new Vector2((float)(num146 - Main.npc[num156].width / 2), (float)(num147 - Main.npc[num156].height - 1)), 14, 0);
                                                                        }
                                                                    }
                                                                }
                                                                else if (num144 == 41 && Wiring.CheckMech(num143, num142, 300))
{
                                                                    int num157 = 50;
                                                                    int[] array2 = new int[num157];
                                                                    int num158 = 0;
                                                                    for (int num159 = 0; num159 < Main.maxNPCs; num159++)
{
                                                                        if (Main.npc[num159].active && (Main.npc[num159].type == 18 || Main.npc[num159].type == 20 || Main.npc[num159].type == 124 || Main.npc[num159].type == 178 || Main.npc[num159].type == 208 || Main.npc[num159].type == 353 || Main.npc[num159].type == 633 || Main.npc[num159].type == 663))
{
                                                                            array2[num158] = num159;
                                                                            num158++;
                                                                            if (num158 >= num157)
{
                                                                                break;
                                                                            }
                                                                        }
                                                                    }
                                                                    if (num158 > 0)
{
                                                                        int num160 = array2[Main.rand.Next(num158)];
                                                                        Main.npc[num160].Teleport(new Vector2((float)(num146 - Main.npc[num160].width / 2), (float)(num147 - Main.npc[num160].height - 1)), 14, 0);
                                                                    }
                                                                }
                                                            }
                                                            if (num148 >= 0)
{
                                                                Main.npc[num148].value = 0f;
                                                                Main.npc[num148].npcSlots = 0f;
                                                                Main.npc[num148].SpawnedFromStatue = true;
                                                                Main.npc[num148].CanBeReplacedByOtherNPCs = true;
                                                                return;
                                                            }
                                                        }
                                                        else
{
                                                            if (type == 349)
{
                                                                int num161 = (int)(tile.frameY / 18);
                                                                num161 %= 3;
                                                                int num162 = j - num161;
                                                                int num163;
                                                                for (num163 = (int)(tile.frameX / 18); num163 >= 2; num163 -= 2)
{
                                                                }
                                                                num163 = i - num163;
                                                                Wiring.SkipWire(num163, num162);
                                                                Wiring.SkipWire(num163, num162 + 1);
                                                                Wiring.SkipWire(num163, num162 + 2);
                                                                Wiring.SkipWire(num163 + 1, num162);
                                                                Wiring.SkipWire(num163 + 1, num162 + 1);
                                                                Wiring.SkipWire(num163 + 1, num162 + 2);
                                                                short num164;
                                                                if (Main.tile[num163, num162].frameX == 0)
{
                                                                    num164 = 216;
                                                                }
                                                                else
{
                                                                    num164 = -216;
                                                                }
                                                                for (int num165 = 0; num165 < 2; num165++)
{
                                                                    for (int num166 = 0; num166 < 3; num166++)
{
                                                                        Tile tile9 = Main.tile[num163 + num165, num162 + num166];
                                                                        tile9.frameX += num164;
                                                                    }
                                                                }
                                                                if (Main.netMode == 2)
{
                                                                    NetMessage.SendTileSquare(-1, num163, num162, 2, 3, TileChangeType.None);
                                                                }
                                                                Animation.NewTemporaryAnimation((num164 > 0) ? 0 : 1, 349, num163, num162);
                                                                return;
                                                            }
                                                            if (type == 506)
{
                                                                int num167 = (int)(tile.frameY / 18);
                                                                num167 %= 3;
                                                                int num168 = j - num167;
                                                                int num169;
                                                                for (num169 = (int)(tile.frameX / 18); num169 >= 2; num169 -= 2)
{
                                                                }
                                                                num169 = i - num169;
                                                                if (!WorldGen.ValidateTileSquareIsActiveAndOfType(num169, num168, 2, 3, type))
{
                                                                    return;
                                                                }
                                                                Wiring.SkipWire(num169, num168);
                                                                Wiring.SkipWire(num169, num168 + 1);
                                                                Wiring.SkipWire(num169, num168 + 2);
                                                                Wiring.SkipWire(num169 + 1, num168);
                                                                Wiring.SkipWire(num169 + 1, num168 + 1);
                                                                Wiring.SkipWire(num169 + 1, num168 + 2);
                                                                short num170;
                                                                if (Main.tile[num169, num168].frameX < 72)
{
                                                                    num170 = 72;
                                                                }
                                                                else
{
                                                                    num170 = -72;
                                                                }
                                                                for (int num171 = 0; num171 < 2; num171++)
{
                                                                    for (int num172 = 0; num172 < 3; num172++)
{
                                                                        Tile tile10 = Main.tile[num169 + num171, num168 + num172];
                                                                        tile10.frameX += num170;
                                                                    }
                                                                }
                                                                if (Main.netMode == 2)
{
                                                                    NetMessage.SendTileSquare(-1, num169, num168, 2, 3, TileChangeType.None);
                                                                    return;
                                                                }
                                                            }
                                                            else
{
                                                                if (type == 546)
{
                                                                    tile.type = 557;
                                                                    WorldGen.SquareTileFrame(i, j, true);
                                                                    NetMessage.SendTileSquare(-1, i, j, TileChangeType.None);
                                                                    return;
                                                                }
                                                                if (type == 557)
{
                                                                    tile.type = 546;
                                                                    WorldGen.SquareTileFrame(i, j, true);
                                                                    NetMessage.SendTileSquare(-1, i, j, TileChangeType.None);
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
References Terraria.Wiring._currentWireColor, Terraria.Wiring._inPumpX, Terraria.Wiring._inPumpY, Terraria.Wiring._LampsToCheck, Terraria.Wiring._numInPump, Terraria.Wiring._numOutPump, Terraria.Wiring._outPumpX, Terraria.Wiring._outPumpY, Terraria.Wiring._teleport, Terraria.NPC.active, Terraria.Player.active, Terraria.Projectile.active, Terraria.Tile.active(), Terraria.Wiring.ActuateForced(), Terraria.Tile.actuator(), Terraria.Projectile.ai, Terraria.Projectile.aiStyle, Terraria.Main.AnnouncementBoxDisabled, Terraria.Main.AnnouncementBoxRange, System.array, Microsoft.Xna.Framework.Color.B, Terraria.Wiring.bunnyCannonCoolDown, Terraria.ID.TileID.Sets.Campfires, Terraria.NPC.CanBeReplacedByOtherNPCs, Terraria.WorldGen.CanKillTile(), Terraria.Wiring.cannonCoolDown, Terraria.Entity.Center, Terraria.Wiring.CheckMech(), Terraria.WorldGen.CloseDoor(), Terraria.Wiring.CurrentUser, Terraria.Entity.Distance(), Terraria.NPC.downedPlantBoss, System.Collections.Generic.Queue< T >.Enqueue(), Terraria.Wiring.ExplodeMine(), Terraria.Wiring.Extractinator(), Terraria.Main.fastForwardTimeToDawn, Terraria.Main.fastForwardTimeToDusk, Terraria.Minecart.FlipSwitchTrack(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Localization.NetworkText.FromLiteral(), Microsoft.Xna.Framework.Color.G, Terraria.Wiring.GetItemSource(), Terraria.Wiring.GetNPCSource(), Terraria.Wiring.GetProjectileSource(), Terraria.Wiring.GeyserTrap(), Terraria.Tile.halfBrick(), Terraria.Entity.height, Terraria.Wiring.HitSwitch(), Terraria.Wiring.Hopper(), int, Terraria.WorldGen.KillTile(), Terraria.WorldGen.LaunchRocket(), Terraria.WorldGen.LaunchRocketSmall(), Terraria.Main.maxNPCs, Terraria.Item.MechSpawn(), Terraria.NPC.MechSpawn(), Terraria.Main.moondialCooldown, Terraria.Main.Moondialing(), Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.NPC.NewNPC(), Terraria.Projectile.NewProjectile(), Terraria.Animation.NewTemporaryAnimation(), Terraria.Main.NewTextMultiline(), Terraria.Main.npc, Terraria.NPC.npcSlots, Terraria.WorldGen.OpenDoor(), Terraria.GameContent.Events.BirthdayParty.PartyIsUp, Microsoft.Xna.Framework.Color.Pink, Terraria.Main.player, Terraria.Utils.PoofOfSmoke(), Terraria.ID.TileID.Sets.PreventsActuationUnder, Terraria.Main.projectile, Microsoft.Xna.Framework.Color.R, Terraria.Main.rand, Terraria.Sign.ReadSign(), Terraria.NetMessage.SendData(), Terraria.NetMessage.SendTemporaryAnimation(), Terraria.NetMessage.SendTileSquare(), Terraria.WorldGen.ShiftTallGate(), Terraria.WorldGen.ShiftTrapdoor(), Terraria.WorldGen.ShootFromCannon(), Terraria.Main.sign, Terraria.Wiring.SkipWire(), Terraria.Wiring.snowballCannonCoolDown, Terraria.Collision.SolidTiles(), Terraria.NPC.SpawnedFromStatue, System.Math.Sqrt(), Terraria.WorldGen.SquareTileFrame(), Terraria.Main.sundialCooldown, Terraria.Main.Sundialing(), Terraria.WorldGen.SwitchFountain(), Terraria.WorldGen.SwitchMB(), Terraria.WorldGen.SwitchMonolith(), Terraria.NPC.Teleport(), Terraria.Sign.text, Terraria.Main.tile, Terraria.Wiring.Toggle2x2Light(), Terraria.Wiring.ToggleCampFire(), Terraria.Wiring.ToggleCandle(), Terraria.Wiring.ToggleChandelier(), Terraria.Wiring.ToggleFirePlace(), Terraria.Wiring.ToggleHangingLantern(), Terraria.Wiring.ToggleHolidayLight(), Terraria.Wiring.ToggleLamp(), Terraria.Wiring.ToggleLampPost(), Terraria.GameContent.Events.BirthdayParty.ToggleManualParty(), Terraria.Wiring.ToggleTorch(), Terraria.ID.TileID.Sets.Torches, Terraria.NPC.type, Terraria.Projectile.type, Terraria.Tile.type, Terraria.WorldGen.ValidateTileSquareIsActiveAndOfType(), Terraria.NPC.value, Terraria.Tile.wall, Terraria.Entity.width, Terraria.Main.worldSurface, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.Wiring.HitWire().