Terraria Decompiled: Terraria.Wiring.HitWire
HitWire()
static void Terraria.Wiring.HitWire (DoubleStack< Point16 > next, int wireType) inline static private
Definition at line 812 of file Wiring.cs.
        {
            Wiring._wireDirectionList.Clear(true);
            for (int i = 0; i < next.Count; i++)
            {
                Point16 point = next.PopFront();
                Wiring.SkipWire(point);
                Wiring._toProcess.Add(point, 4);
                next.PushBack(point);
                Wiring._wireDirectionList.PushBack(0);
            }
            Wiring._currentWireColor = wireType;
            while (next.Count > 0)
            {
                Point16 point2 = next.PopFront();
                int num = (int)Wiring._wireDirectionList.PopFront();
                int x = (int)point2.X;
                int y = (int)point2.Y;
                if (!Wiring._wireSkip.ContainsKey(point2))
                {
                    Wiring.HitWireSingle(x, y);
                }
                for (int j = 0; j < 4; j++)
                {
                    int num2;
                    int num3;
                    switch (j)
                    {
                    case 0:
                        num2 = x;
                        num3 = y + 1;
                        break;
                    case 1:
                        num2 = x;
                        num3 = y - 1;
                        break;
                    case 2:
                        num2 = x + 1;
                        num3 = y;
                        break;
                    case 3:
                        num2 = x - 1;
                        num3 = y;
                        break;
                    default:
                        num2 = x;
                        num3 = y + 1;
                        break;
                    }
                    if (num2 >= 2 && num2 < Main.maxTilesX - 2 && num3 >= 2 && num3 < Main.maxTilesY - 2)
                    {
                        Tile tile = Main.tile[num2, num3];
                        if (tile != null)
{
                            Tile tile2 = Main.tile[x, y];
                            if (tile2 != null)
{
                                byte b = 3;
                                if (tile.type == 424 || tile.type == 445)
{
                                    b = 0;
                                }
                                if (tile2.type == 424)
{
                                    switch (tile2.frameX / 18)
{
                                    case 0:
                                        if (j != num)
{
                                            goto IL_0318;
                                        }
                                        break;
                                    case 1:
                                        if ((num != 0 || j != 3) && (num != 3 || j != 0) && (num != 1 || j != 2))
{
                                            if (num != 2)
{
                                                goto IL_0318;
                                            }
                                            if (j != 1)
{
                                                goto IL_0318;
                                            }
                                        }
                                        break;
                                    case 2:
                                        if ((num != 0 || j != 2) && (num != 2 || j != 0) && (num != 1 || j != 3) && (num != 3 || j != 1))
{
                                            goto IL_0318;
                                        }
                                        break;
                                    }
                                }
                                if (tile2.type == 445)
{
                                    if (j != num)
{
                                        goto IL_0318;
                                    }
                                    if (Wiring._PixelBoxTriggers.ContainsKey(point2))
{
                                        Dictionary<Point16, byte> pixelBoxTriggers = Wiring._PixelBoxTriggers;
                                        Point16 point3 = point2;
                                        pixelBoxTriggers[point3] |= (((j == 0) | (j == 1)) ? 2 : 1);
                                    }
                                    else
{
                                        Wiring._PixelBoxTriggers[point2] = (((j == 0) | (j == 1)) ? 2 : 1);
                                    }
                                }
                                bool flag;
                                switch (wireType)
{
                                case 1:
                                    flag = tile.wire();
                                    break;
                                case 2:
                                    flag = tile.wire2();
                                    break;
                                case 3:
                                    flag = tile.wire3();
                                    break;
                                case 4:
                                    flag = tile.wire4();
                                    break;
                                default:
                                    flag = false;
                                    break;
                                }
                                if (flag)
{
                                    Point16 point4 = new Point16(num2, num3);
                                    byte b2;
                                    if (Wiring._toProcess.TryGetValue(point4, out b2))
{
                                        b2 -= 1;
                                        if (b2 == 0)
{
                                            Wiring._toProcess.Remove(point4);
                                        }
                                        else
{
                                            Wiring._toProcess[point4] = b2;
                                        }
                                    }
                                    else
{
                                        next.PushBack(point4);
                                        Wiring._wireDirectionList.PushBack((byte)j);
                                        if (b > 0)
{
                                            Wiring._toProcess.Add(point4, b);
                                        }
                                    }
                                }
                            }
                        }
                    }
                    IL_0318:;
                }
            }
            Wiring._wireSkip.Clear();
            Wiring._toProcess.Clear();
        }
References Terraria.Wiring._PixelBoxTriggers, Terraria.Wiring._toProcess, Terraria.Wiring._wireDirectionList, Terraria.Wiring._wireSkip, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), Terraria.DataStructures.DoubleStack< T1 >.Clear(), System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), Terraria.DataStructures.DoubleStack< T1 >.Count, Terraria.Tile.frameX, Terraria.Wiring.HitWireSingle(), int, Terraria.Main.maxTilesY, Terraria.DataStructures.DoubleStack< T1 >.PopFront(), Terraria.DataStructures.DoubleStack< T1 >.PushBack(), System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), Terraria.Wiring.SkipWire(), Terraria.Main.tile, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), Terraria.Tile.type, Terraria.Tile.wire(), Terraria.Tile.wire2(), Terraria.Tile.wire3(), Terraria.Tile.wire4(), Terraria.DataStructures.Point16.X, and Terraria.DataStructures.Point16.Y.
Referenced by Terraria.Wiring.TripWire().