Terraria Decompiled: Terraria.Wiring.ToggleCampFire
ToggleCampFire()
static void Terraria.Wiring.ToggleCampFire (int i, int j, Tile tileCache, bool? forcedStateWhereTrueIsOn, bool doSkipWires) inline static
Definition at line 3234 of file Wiring.cs.
        {
            if (!TileID.Sets.Campfires[(int)tileCache.type])
            {
                return;
            }
            int num = 3;
            int num2 = 2;
            int num3 = (int)tileCache.frameX % (num * 18) / 18;
            int num4 = (int)tileCache.frameY % (num2 * 18) / 18;
            int num5 = i - num3;
            int num6 = j - num4;
            if (!WorldGen.ValidateTileSquareIsActiveAndOfType(num5, num6, num, num2, (int)tileCache.type))
            {
                return;
            }
            bool flag = Main.tile[num5, num6].frameY >= 36;
            if (forcedStateWhereTrueIsOn != null && !forcedStateWhereTrueIsOn.Value == flag)
            {
                return;
            }
            short num7 = 36;
            if (Main.tile[num5, num6].frameY >= 36)
            {
                num7 = -36;
            }
            for (int k = num5; k < num5 + num; k++)
            {
                for (int l = num6; l < num6 + num2; l++)
                {
                    if (doSkipWires)
                    {
                        Wiring.SkipWire(k, l);
                    }
                    Tile tile = Main.tile[k, l];
                    if (tile.active() && tile.type == tileCache.type)
                    {
                        Tile tile2 = tile;
                        tile2.frameY += num7;
                    }
                }
            }
            NetMessage.SendTileSquare(-1, num5, num6, num, num2, TileChangeType.None);
        }
References Terraria.Tile.active(), Terraria.ID.TileID.Sets.Campfires, Terraria.Tile.frameX, Terraria.Tile.frameY, int, Terraria.NetMessage.SendTileSquare(), Terraria.Wiring.SkipWire(), Terraria.Main.tile, Terraria.Tile.type, and Terraria.WorldGen.ValidateTileSquareIsActiveAndOfType().
Referenced by Terraria.Wiring.HitWireSingle(), and Terraria.WorldGen.TryToggleLight().