Terraria Decompiled: Terraria.Wiring.Extractinator
Extractinator()
static void Terraria.Wiring.Extractinator (int sourceX, int sourceY) inline static private
Definition at line 2729 of file Wiring.cs.
        {
            Tile tile = Main.tile[sourceX, sourceY];
            int num = sourceX - (int)(tile.frameX % 54 / 18);
            int num2 = sourceY - (int)(tile.frameY % 54 / 18);
            int num3 = 60;
            if (!Wiring.CheckMech(num, num2, num3))
            {
                return;
            }
            int num4;
            if (!Wiring.TryFindChestForExtractinator(num, num2, out num4))
            {
                return;
            }
            if (Chest.UsingChest(num4) != -1)
            {
                return;
            }
            int type = (int)tile.type;
            Item[] item = Main.chest[num4].item;
            for (int i = Main.chest[num4].maxItems - 1; i >= 0; i--)
            {
                Item item2 = item[i];
                if (!item2.IsAir)
                {
                    int num5;
                    int num6;
                    ExtractinatorHelper.RollExtractinatorDrop(ItemID.Sets.ExtractinatorMode[item2.type], type, out num5, out num6);
                    if (num5 > 0)
                    {
                        Item item3 = item2;
                        int num7 = item3.stack - 1;
                        item3.stack = num7;
                        if (num7 <= 0)
{
                            item2.TurnToAir(false);
                        }
                        Item.NewItem(new EntitySource_Wiring(num, num2), num * 16, num2 * 16, 32, 32, num5, num6, false, -1, false);
                        return;
                    }
                }
            }
        }
References Terraria.Wiring.CheckMech(), Terraria.Main.chest, Terraria.ID.ItemID.Sets.ExtractinatorMode, Terraria.Tile.frameX, Terraria.Tile.frameY, int, Terraria.Item.IsAir, System.item, Terraria.Chest.item, Terraria.Chest.maxItems, Terraria.Item.NewItem(), Terraria.GameContent.ExtractinatorHelper.RollExtractinatorDrop(), Terraria.Main.tile, Terraria.Wiring.TryFindChestForExtractinator(), Terraria.Item.TurnToAir(), Terraria.Item.type, Terraria.Tile.type, and Terraria.Chest.UsingChest().
Referenced by Terraria.Wiring.HitWireSingle().