Terraria Decompiled: Terraria.Wiring.MassWireOperation
MassWireOperation()
static void Terraria.Wiring.MassWireOperation (Point ps, Point pe, Player master) inline static
Definition at line 381 of file Wiring.cs.
        {
            int num = 0;
            int num2 = 0;
            for (int i = 0; i < 58; i++)
            {
                if (master.inventory[i].type == 530)
                {
                    num += master.inventory[i].stack;
                }
                if (master.inventory[i].type == 849)
                {
                    num2 += master.inventory[i].stack;
                }
            }
            int num3 = num;
            int num4 = num2;
            Wiring.MassWireOperationInner(master, ps, pe, master.Center, master.direction == 1, ref num, ref num2);
            int num5 = num3 - num;
            int num6 = num4 - num2;
            if (Main.netMode == 2)
            {
                NetMessage.SendData(110, master.whoAmI, -1, null, 530, (float)num5, (float)master.whoAmI, 0f, 0, 0, 0);
                NetMessage.SendData(110, master.whoAmI, -1, null, 849, (float)num6, (float)master.whoAmI, 0f, 0, 0, 0);
                return;
            }
            for (int j = 0; j < num5; j++)
            {
                master.ConsumeItem(530, false, false);
            }
            for (int k = 0; k < num6; k++)
            {
                master.ConsumeItem(849, false, false);
            }
        }
References Terraria.Entity.Center, Terraria.Player.ConsumeItem(), Terraria.Entity.direction, Terraria.Player.inventory, Terraria.Wiring.MassWireOperationInner(), Terraria.Main.netMode, Terraria.NetMessage.SendData(), Terraria.Item.stack, Terraria.Item.type, and Terraria.Entity.whoAmI.
Referenced by Terraria.Player.ItemCheck_UseWiringTools().