Terraria Decompiled: Terraria.Wiring.DeActive
DeActive()
static void Terraria.Wiring.DeActive (int i, int j) inline static private
Definition at line 3432 of file Wiring.cs.
        {
            if (!Main.tile[i, j].active())
            {
                return;
            }
            if (Main.tile[i, j].type == 226 && (double)j > Main.worldSurface && !NPC.downedPlantBoss)
            {
                return;
            }
            bool flag = Main.tileSolid[(int)Main.tile[i, j].type] && !TileID.Sets.NotReallySolid[(int)Main.tile[i, j].type];
            ushort type = Main.tile[i, j].type;
            if (type <= 379)
            {
                if (type != 314 && type != 379)
                {
                    goto IL_00B4;
                }
            }
            else if (type - 386 > 3 && type != 476)
            {
                goto IL_00B4;
            }
            flag = false;
            IL_00B4:
            if (!flag)
            {
                return;
            }
            if (Main.tile[i, j - 1].active() && (TileID.Sets.PreventsActuationUnder[(int)Main.tile[i, j - 1].type] || !WorldGen.CanKillTile(i, j)))
            {
                return;
            }
            Main.tile[i, j].inActive(true);
            WorldGen.SquareTileFrame(i, j, false);
            if (Main.netMode != 1)
            {
                NetMessage.SendTileSquare(-1, i, j, TileChangeType.None);
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.CanKillTile(), Terraria.NPC.downedPlantBoss, Terraria.Tile.inActive(), int, Terraria.Main.netMode, Terraria.ID.TileID.Sets.NotReallySolid, Terraria.ID.TileID.Sets.PreventsActuationUnder, Terraria.NetMessage.SendTileSquare(), Terraria.WorldGen.SquareTileFrame(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Tile.type, and Terraria.Main.worldSurface.
Referenced by Terraria.Wiring.Actuate(), and Terraria.Wiring.ActuateForced().