Terraria Decompiled: Terraria.Wiring.TryMoveCoinsInChest
TryMoveCoinsInChest()
static bool Terraria.Wiring.TryMoveCoinsInChest (int itemIndex, int chestIndex) inline static private
Definition at line 2906 of file Wiring.cs.
        {
            WorldItem worldItem = Main.item[itemIndex];
            if (!worldItem.IsACoin)
            {
                return false;
            }
            int maxItems = Main.chest[chestIndex].maxItems;
            Item[] item = Main.chest[chestIndex].item;
            bool flag;
            long num = Utils.CoinsCount(out flag, item, new int[0]);
            int num2 = worldItem.value / 5;
            int[] array = Utils.CoinsSplit(num + (long)(num2 * worldItem.stack));
            int[] array2 = new int[array.Length];
            int i = 0;
            for (int j = array.Length - 1; j >= 0; j--)
            {
                if (array[j] != 0)
                {
                    while (i < maxItems)
                    {
                        if (item[i].IsAir || item[i].IsACoin)
{
                            array2[j] = i++;
                            goto IL_00A6;
                        }
                        i++;
                    }
                    return false;
                }
                IL_00A6:;
            }
            foreach (Item item2 in item)
            {
                if (item2.IsACoin)
                {
                    item2.TurnToAir(false);
                }
            }
            for (int l = array.Length - 1; l >= 0; l--)
            {
                if (array[l] != 0)
                {
                    int num3 = 71 + l;
                    int num4 = Math.Min(ContentSamples.ItemsByType[num3].maxStack, array[l]);
                    Item item3 = item[array2[l]];
                    item3.SetDefaults(num3, null);
                    item3.stack = num4;
                    array[l] -= num4;
                    int num5 = array[l];
                }
            }
            worldItem.TurnToAir(false);
            return true;
        }
References System.array, Terraria.Main.chest, Terraria.Utils.CoinsCount(), Terraria.Utils.CoinsSplit(), Terraria.Item.IsACoin, Terraria.WorldItem.IsACoin, System.item, Terraria.Chest.item, Terraria.Main.item, Terraria.ID.ContentSamples.ItemsByType, Terraria.Chest.maxItems, System.Math.Min(), Terraria.Item.SetDefaults(), Terraria.WorldItem.stack, and Terraria.Item.TurnToAir().
Referenced by Terraria.Wiring.TryToPutItemInChest().