Terraria Decompiled: Terraria.Wiring.CheckLogicGate
CheckLogicGate()
static void Terraria.Wiring.CheckLogicGate (int lampX, int lampY) inline static private
Definition at line 690 of file Wiring.cs.
        {
            if (!WorldGen.InWorld(lampX, lampY, 1))
            {
                return;
            }
            int i = lampY;
            while (i < Main.maxTilesY)
            {
                Tile tile = Main.tile[lampX, i];
                if (!tile.active())
                {
                    return;
                }
                if (tile.type == 420)
                {
                    bool flag;
                    Wiring._GatesDone.TryGetValue(new Point16(lampX, i), out flag);
                    int num = (int)(tile.frameY / 18);
                    bool flag2 = tile.frameX == 18;
                    bool flag3 = tile.frameX == 36;
                    if (num < 0)
                    {
                        return;
                    }
                    int num2 = 0;
                    int num3 = 0;
                    bool flag4 = false;
                    for (int j = i - 1; j > 0; j--)
                    {
                        Tile tile2 = Main.tile[lampX, j];
                        if (!tile2.active() || tile2.type != 419)
{
                            break;
                        }
                        if (tile2.frameX == 36)
{
                            flag4 = true;
                            break;
                        }
                        num2++;
                        num3 += (tile2.frameX == 18).ToInt();
                    }
                    bool flag5;
                    switch (num)
                    {
                    case 0:
                        flag5 = num2 == num3;
                        break;
                    case 1:
                        flag5 = num3 > 0;
                        break;
                    case 2:
                        flag5 = num2 != num3;
                        break;
                    case 3:
                        flag5 = num3 == 0;
                        break;
                    case 4:
                        flag5 = num3 == 1;
                        break;
                    case 5:
                        flag5 = num3 != 1;
                        break;
                    default:
                        return;
                    }
                    bool flag6 = !flag4 && flag3;
                    bool flag7 = false;
                    if (flag4 && Framing.GetTileSafely(lampX, lampY).frameX == 36)
                    {
                        flag7 = true;
                    }
                    if (flag5 != flag2 || flag6 || flag7)
                    {
                        short num4 = tile.frameX % 18 / 18;
                        tile.frameX = (short)(18 * flag5.ToInt());
                        if (flag4)
{
                            tile.frameX = 36;
                        }
                        Wiring.SkipWire(lampX, i);
                        WorldGen.SquareTileFrame(lampX, i, true);
                        NetMessage.SendTileSquare(-1, lampX, i, TileChangeType.None);
                        bool flag8 = !flag4 || flag7;
                        if (flag7)
{
                            if (num3 == 0 || num2 == 0)
{
                            }
                            flag8 = Main.rand.NextFloat() < (float)num3 / (float)num2;
                        }
                        if (flag6)
{
                            flag8 = false;
                        }
                        if (flag8)
{
                            if (!flag)
{
                                Wiring._GatesNext.Enqueue(new Point16(lampX, i));
                                return;
                            }
                            Vector2 vector = new Vector2((float)lampX, (float)i) * 16f - new Vector2(10f);
                            Utils.PoofOfSmoke(vector);
                            NetMessage.SendData(106, -1, -1, null, (int)vector.X, vector.Y, 0f, 0f, 0, 0, 0);
                        }
                    }
                    return;
                }
                else
                {
                    if (tile.type != 419)
                    {
                        return;
                    }
                    i++;
                }
            }
        }
References Terraria.Wiring._GatesDone, Terraria.Wiring._GatesNext, Terraria.Tile.active(), System.Collections.Generic.Queue< T >.Enqueue(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Framing.GetTileSafely(), int, Terraria.WorldGen.InWorld(), Terraria.Main.maxTilesY, Terraria.Utils.PoofOfSmoke(), Terraria.Main.rand, Terraria.NetMessage.SendData(), Terraria.NetMessage.SendTileSquare(), Terraria.Wiring.SkipWire(), Terraria.WorldGen.SquareTileFrame(), Terraria.Main.tile, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), Terraria.Tile.type, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Wiring.LogicGatePass().