Terraria Decompiled: Terraria.Wiring.UpdateMech
UpdateMech()
static void Terraria.Wiring.UpdateMech () inline static
Definition at line 92 of file Wiring.cs.
        {
            if (Wiring.cannonCoolDown > 0)
            {
                Wiring.cannonCoolDown--;
            }
            if (Wiring.bunnyCannonCoolDown > 0)
            {
                Wiring.bunnyCannonCoolDown--;
            }
            if (Wiring.snowballCannonCoolDown > 0)
            {
                Wiring.snowballCannonCoolDown--;
            }
            Wiring.SetCurrentUser(-1);
            for (int i = Wiring._numMechs - 1; i >= 0; i--)
            {
                Wiring._mechTime[i]--;
                int num = Wiring._mechX[i];
                int num2 = Wiring._mechY[i];
                if (!WorldGen.InWorld(num, num2, 1))
                {
                    Wiring._numMechs--;
                }
                else
                {
                    Tile tile = Main.tile[num, num2];
                    if (tile == null)
                    {
                        Wiring._numMechs--;
                    }
                    else
                    {
                        if (tile.active() && tile.type == 144)
{
                            if (tile.frameY == 0)
{
                                Wiring._mechTime[i] = 0;
                            }
                            else
{
                                int num3 = (int)(tile.frameX / 18);
                                if (num3 == 0)
{
                                    num3 = 60;
                                }
                                else if (num3 == 1)
{
                                    num3 = 180;
                                }
                                else if (num3 == 2)
{
                                    num3 = 300;
                                }
                                else if (num3 == 3)
{
                                    num3 = 30;
                                }
                                else if (num3 == 4)
{
                                    num3 = 15;
                                }
                                if (Math.IEEERemainder((double)Wiring._mechTime[i], (double)num3) == 0.0)
{
                                    Wiring._mechTime[i] = 18000;
                                    Wiring.TripWire(Wiring._mechX[i], Wiring._mechY[i], 1, 1);
                                }
                            }
                        }
                        if (Wiring._mechTime[i] <= 0)
{
                            if (tile.active() && tile.type == 144)
{
                                tile.frameY = 0;
                                NetMessage.SendTileSquare(-1, Wiring._mechX[i], Wiring._mechY[i], TileChangeType.None);
                            }
                            if (tile.active() && tile.type == 411)
{
                                int num4 = (int)(tile.frameX % 36 / 18);
                                int num5 = (int)(tile.frameY % 36 / 18);
                                int num6 = Wiring._mechX[i] - num4;
                                int num7 = Wiring._mechY[i] - num5;
                                int num8 = 36;
                                if (Main.tile[num6, num7].frameX >= 36)
{
                                    num8 = -36;
                                }
                                for (int j = num6; j < num6 + 2; j++)
{
                                    for (int k = num7; k < num7 + 2; k++)
{
                                        if (WorldGen.InWorld(j, k, 1))
{
                                            Tile tile2 = Main.tile[j, k];
                                            if (tile2 != null)
{
                                                tile2.frameX = (short)((int)tile2.frameX + num8);
                                            }
                                        }
                                    }
                                }
                                NetMessage.SendTileSquare(-1, num6, num7, 2, 2, TileChangeType.None);
                            }
                            for (int l = i; l < Wiring._numMechs; l++)
{
                                Wiring._mechX[l] = Wiring._mechX[l + 1];
                                Wiring._mechY[l] = Wiring._mechY[l + 1];
                                Wiring._mechTime[l] = Wiring._mechTime[l + 1];
                            }
                            Wiring._numMechs--;
                        }
                    }
                }
            }
        }
References Terraria.Wiring._mechTime, Terraria.Wiring._mechX, Terraria.Wiring._mechY, Terraria.Wiring._numMechs, Terraria.Tile.active(), Terraria.Wiring.bunnyCannonCoolDown, Terraria.Wiring.cannonCoolDown, Terraria.Tile.frameX, Terraria.Tile.frameY, System.Math.IEEERemainder(), int, Terraria.WorldGen.InWorld(), Terraria.NetMessage.SendTileSquare(), Terraria.Wiring.SetCurrentUser(), Terraria.Wiring.snowballCannonCoolDown, Terraria.Main.tile, and Terraria.Wiring.TripWire().
Referenced by Terraria.WorldGen.UpdateWorld().