Terraria Decompiled: Terraria.Wiring.ToggleHangingLantern
ToggleHangingLantern()
static void Terraria.Wiring.ToggleHangingLantern (int i, int j, Tile tileCache, bool? forcedStateWhereTrueIsOn, bool doSkipWires) inline static
Definition at line 3028 of file Wiring.cs.
        {
            int k;
            for (k = (int)(tileCache.frameY / 18); k >= 2; k -= 2)
            {
            }
            int num = j - k;
            short num2 = 18;
            if (tileCache.frameX > 0)
            {
                num2 = -18;
            }
            bool flag = tileCache.frameX > 0;
            if (forcedStateWhereTrueIsOn != null && !forcedStateWhereTrueIsOn.Value == flag)
            {
                return;
            }
            Tile tile = Main.tile[i, num];
            tile.frameX += num2;
            Tile tile2 = Main.tile[i, num + 1];
            tile2.frameX += num2;
            if (doSkipWires)
            {
                Wiring.SkipWire(i, num);
                Wiring.SkipWire(i, num + 1);
            }
            NetMessage.SendTileSquare(-1, i, num, 1, 2, TileChangeType.None);
        }
References Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.NetMessage.SendTileSquare(), Terraria.Wiring.SkipWire(), and Terraria.Main.tile.
Referenced by Terraria.Wiring.HitWireSingle(), and Terraria.WorldGen.TryToggleLight().