Terraria Decompiled: Terraria.Wiring.XferWater
XferWater()
static void Terraria.Wiring.XferWater () inline static private
Definition at line 439 of file Wiring.cs.
        {
            for (int i = 0; i < Wiring._numInPump; i++)
            {
                int num = Wiring._inPumpX[i];
                int num2 = Wiring._inPumpY[i];
                int num3 = (int)Main.tile[num, num2].liquid;
                if (num3 > 0)
                {
                    byte b = Main.tile[num, num2].liquidType();
                    for (int j = 0; j < Wiring._numOutPump; j++)
                    {
                        int num4 = Wiring._outPumpX[j];
                        int num5 = Wiring._outPumpY[j];
                        int liquid = (int)Main.tile[num4, num5].liquid;
                        if (liquid < 255)
{
                            byte b2 = Main.tile[num4, num5].liquidType();
                            if (liquid == 0)
{
                                b2 = b;
                            }
                            if (b2 == b)
{
                                int num6 = num3;
                                if (num6 + liquid > 255)
{
                                    num6 = 255 - liquid;
                                }
                                Tile tile = Main.tile[num4, num5];
                                tile.liquid += (byte)num6;
                                Tile tile2 = Main.tile[num, num2];
                                tile2.liquid -= (byte)num6;
                                num3 = (int)Main.tile[num, num2].liquid;
                                Main.tile[num4, num5].liquidType((int)b);
                                WorldGen.SquareTileFrame(num4, num5, true);
                                if (Main.tile[num, num2].liquid == 0)
{
                                    Main.tile[num, num2].liquidType(0);
                                    WorldGen.SquareTileFrame(num, num2, true);
                                    break;
                                }
                            }
                        }
                    }
                    WorldGen.SquareTileFrame(num, num2, true);
                }
            }
        }
References Terraria.Wiring._inPumpX, Terraria.Wiring._inPumpY, Terraria.Wiring._numInPump, Terraria.Wiring._numOutPump, Terraria.Wiring._outPumpX, Terraria.Wiring._outPumpY, int, Terraria.Tile.liquid, Terraria.Tile.liquidType(), Terraria.WorldGen.SquareTileFrame(), and Terraria.Main.tile.
Referenced by Terraria.Wiring.TripWire().