Terraria Decompiled: Terraria.Wiring.Hopper
Hopper()
static void Terraria.Wiring.Hopper (int sourceX, int sourceY) inline static private
Definition at line 2829 of file Wiring.cs.
        {
            Tile tile = Main.tile[sourceX, sourceY];
            int num = sourceX;
            int num2 = sourceY;
            if (tile.frameX % 36 != 0)
            {
                num--;
            }
            if (tile.frameY % 36 != 0)
            {
                num2--;
            }
            int num3 = 60;
            if (!Wiring.CheckMech(num, num2, num3))
            {
                return;
            }
            if (Chest.IsLocked(num, num2))
            {
                return;
            }
            int num4 = Chest.FindChest(num, num2);
            if (num4 == -1)
            {
                return;
            }
            if (Chest.UsingChest(num4) != -1)
            {
                return;
            }
            Rectangle rectangle = Utils.CenteredRectangle(new Vector2((float)(num * 16 + 16), (float)(num2 * 16 + 16)), Wiring.HopperGrabHitboxSize);
            bool flag = false;
            for (int i = 0; i < 400; i++)
            {
                WorldItem worldItem = Main.item[i];
                int type = worldItem.type;
                if (worldItem.active && worldItem.playerIndexTheItemIsReservedFor == Main.myPlayer && !ItemID.Sets.ItemsThatShouldNotBeInInventory[worldItem.type] && worldItem.Hitbox.Intersects(rectangle) && Wiring.TryToPutItemInChest(i, num4))
                {
                    flag = true;
                    NetMessage.SendData(21, -1, -1, null, i, 0f, 0f, 0f, 0, 0, 0);
                    Chest.VisualizeChestTransfer(worldItem.Center, rectangle.Center.ToVector2(), type, Chest.ItemTransferVisualizationSettings.Hopper);
                }
            }
            if (flag)
            {
                ItemSorting.SortInventory(Main.chest[num4], false, false);
            }
        }
References Terraria.WorldItem.active, Microsoft.Xna.Framework.Rectangle.Center, Terraria.Entity.Center, Terraria.Utils.CenteredRectangle(), Terraria.Wiring.CheckMech(), Terraria.Main.chest, Terraria.Chest.FindChest(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Entity.Hitbox, Terraria.Chest.ItemTransferVisualizationSettings.Hopper, Terraria.Wiring.HopperGrabHitboxSize, Microsoft.Xna.Framework.Rectangle.Intersects(), Terraria.Chest.IsLocked(), Terraria.Main.item, Terraria.ID.ItemID.Sets.ItemsThatShouldNotBeInInventory, Terraria.Main.myPlayer, Terraria.WorldItem.playerIndexTheItemIsReservedFor, Terraria.NetMessage.SendData(), Terraria.UI.ItemSorting.SortInventory(), Terraria.Main.tile, Terraria.Wiring.TryToPutItemInChest(), Terraria.WorldItem.type, Terraria.Chest.UsingChest(), and Terraria.Chest.VisualizeChestTransfer().
Referenced by Terraria.Wiring.HitWireSingle().