Terraria Decompiled: Terraria.Wiring.LogicGatePass
LogicGatePass()
static void Terraria.Wiring.LogicGatePass () inline static private
Definition at line 649 of file Wiring.cs.
        {
            if (Wiring._GatesCurrent.Count == 0)
            {
                Wiring._GatesDone.Clear();
                while (Wiring._LampsToCheck.Count > 0)
                {
                    while (Wiring._LampsToCheck.Count > 0)
                    {
                        Point16 point = Wiring._LampsToCheck.Dequeue();
                        Wiring.CheckLogicGate((int)point.X, (int)point.Y);
                    }
                    while (Wiring._GatesNext.Count > 0)
                    {
                        Utils.Swap<Queue<Point16>>(ref Wiring._GatesCurrent, ref Wiring._GatesNext);
                        while (Wiring._GatesCurrent.Count > 0)
{
                            Point16 point2 = Wiring._GatesCurrent.Peek();
                            bool flag;
                            if (Wiring._GatesDone.TryGetValue(point2, out flag) && flag)
{
                                Wiring._GatesCurrent.Dequeue();
                            }
                            else
{
                                Wiring._GatesDone.Add(point2, true);
                                Wiring.TripWire((int)point2.X, (int)point2.Y, 1, 1);
                                Wiring._GatesCurrent.Dequeue();
                            }
                        }
                    }
                }
                Wiring._GatesDone.Clear();
                if (Wiring.blockPlayerTeleportationForOneIteration)
                {
                    Wiring.blockPlayerTeleportationForOneIteration = false;
                }
            }
        }
References Terraria.Wiring._GatesCurrent, Terraria.Wiring._GatesDone, Terraria.Wiring._GatesNext, Terraria.Wiring._LampsToCheck, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), Terraria.Wiring.blockPlayerTeleportationForOneIteration, Terraria.Wiring.CheckLogicGate(), System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.Collections.Generic.Queue< T >.Count, System.Collections.Generic.Queue< T >.Dequeue(), int, System.Collections.Generic.Queue< T >.Peek(), Terraria.Wiring.TripWire(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), Terraria.DataStructures.Point16.X, and Terraria.DataStructures.Point16.Y.
Referenced by Terraria.Wiring.PokeLogicGate(), and Terraria.Wiring.TripWire().