Terraria Decompiled: Terraria.Wiring.MassWireOperationStep
MassWireOperationStep()
static ? bool Terraria.Wiring.MassWireOperationStep (Player user, Point pt, WiresUI::Settings::MultiToolMode mode, ref int wiresLeftToConsume, ref int actuatorsLeftToConsume) inline static private
Definition at line 3575 of file Wiring.cs.
        {
            if (!WorldGen.InWorld(pt.X, pt.Y, 1))
            {
                return null;
            }
            Tile tile = Main.tile[pt.X, pt.Y];
            if (tile == null)
            {
                return null;
            }
            if (user != null && !user.CanDoWireStuffHere(pt.X, pt.Y))
            {
                return null;
            }
            if ((mode & WiresUI.Settings.MultiToolMode.Cutter) == (WiresUI.Settings.MultiToolMode)0)
            {
                if ((mode & WiresUI.Settings.MultiToolMode.Red) != (WiresUI.Settings.MultiToolMode)0 && !tile.wire())
                {
                    if (wiresLeftToConsume <= 0)
                    {
                        return new bool?(false);
                    }
                    wiresLeftToConsume--;
                    WorldGen.PlaceWire(pt.X, pt.Y);
                    NetMessage.SendData(17, -1, -1, null, 5, (float)pt.X, (float)pt.Y, 0f, 0, 0, 0);
                }
                if ((mode & WiresUI.Settings.MultiToolMode.Green) != (WiresUI.Settings.MultiToolMode)0 && !tile.wire3())
                {
                    if (wiresLeftToConsume <= 0)
                    {
                        return new bool?(false);
                    }
                    wiresLeftToConsume--;
                    WorldGen.PlaceWire3(pt.X, pt.Y);
                    NetMessage.SendData(17, -1, -1, null, 12, (float)pt.X, (float)pt.Y, 0f, 0, 0, 0);
                }
                if ((mode & WiresUI.Settings.MultiToolMode.Blue) != (WiresUI.Settings.MultiToolMode)0 && !tile.wire2())
                {
                    if (wiresLeftToConsume <= 0)
                    {
                        return new bool?(false);
                    }
                    wiresLeftToConsume--;
                    WorldGen.PlaceWire2(pt.X, pt.Y);
                    NetMessage.SendData(17, -1, -1, null, 10, (float)pt.X, (float)pt.Y, 0f, 0, 0, 0);
                }
                if ((mode & WiresUI.Settings.MultiToolMode.Yellow) != (WiresUI.Settings.MultiToolMode)0 && !tile.wire4())
                {
                    if (wiresLeftToConsume <= 0)
                    {
                        return new bool?(false);
                    }
                    wiresLeftToConsume--;
                    WorldGen.PlaceWire4(pt.X, pt.Y);
                    NetMessage.SendData(17, -1, -1, null, 16, (float)pt.X, (float)pt.Y, 0f, 0, 0, 0);
                }
                if ((mode & WiresUI.Settings.MultiToolMode.Actuator) != (WiresUI.Settings.MultiToolMode)0 && !tile.actuator())
                {
                    if (actuatorsLeftToConsume <= 0)
                    {
                        return new bool?(false);
                    }
                    actuatorsLeftToConsume--;
                    WorldGen.PlaceActuator(pt.X, pt.Y);
                    NetMessage.SendData(17, -1, -1, null, 8, (float)pt.X, (float)pt.Y, 0f, 0, 0, 0);
                }
            }
            if ((mode & WiresUI.Settings.MultiToolMode.Cutter) != (WiresUI.Settings.MultiToolMode)0)
            {
                if ((mode & WiresUI.Settings.MultiToolMode.Red) != (WiresUI.Settings.MultiToolMode)0 && tile.wire() && WorldGen.KillWire(pt.X, pt.Y))
                {
                    NetMessage.SendData(17, -1, -1, null, 6, (float)pt.X, (float)pt.Y, 0f, 0, 0, 0);
                }
                if ((mode & WiresUI.Settings.MultiToolMode.Green) != (WiresUI.Settings.MultiToolMode)0 && tile.wire3() && WorldGen.KillWire3(pt.X, pt.Y))
                {
                    NetMessage.SendData(17, -1, -1, null, 13, (float)pt.X, (float)pt.Y, 0f, 0, 0, 0);
                }
                if ((mode & WiresUI.Settings.MultiToolMode.Blue) != (WiresUI.Settings.MultiToolMode)0 && tile.wire2() && WorldGen.KillWire2(pt.X, pt.Y))
                {
                    NetMessage.SendData(17, -1, -1, null, 11, (float)pt.X, (float)pt.Y, 0f, 0, 0, 0);
                }
                if ((mode & WiresUI.Settings.MultiToolMode.Yellow) != (WiresUI.Settings.MultiToolMode)0 && tile.wire4() && WorldGen.KillWire4(pt.X, pt.Y))
                {
                    NetMessage.SendData(17, -1, -1, null, 17, (float)pt.X, (float)pt.Y, 0f, 0, 0, 0);
                }
                if ((mode & WiresUI.Settings.MultiToolMode.Actuator) != (WiresUI.Settings.MultiToolMode)0 && tile.actuator() && WorldGen.KillActuator(pt.X, pt.Y))
                {
                    NetMessage.SendData(17, -1, -1, null, 9, (float)pt.X, (float)pt.Y, 0f, 0, 0, 0);
                }
            }
            return new bool?(true);
        }
References Terraria.Tile.actuator(), Terraria.Player.CanDoWireStuffHere(), Terraria.WorldGen.InWorld(), Terraria.WorldGen.KillActuator(), Terraria.WorldGen.KillWire(), Terraria.WorldGen.KillWire2(), Terraria.WorldGen.KillWire3(), Terraria.WorldGen.KillWire4(), System.mode, Terraria.WorldGen.PlaceActuator(), Terraria.WorldGen.PlaceWire(), Terraria.WorldGen.PlaceWire2(), Terraria.WorldGen.PlaceWire3(), Terraria.WorldGen.PlaceWire4(), Terraria.NetMessage.SendData(), Terraria.Main.tile, Terraria.Tile.wire(), Terraria.Tile.wire2(), Terraria.Tile.wire3(), Terraria.Tile.wire4(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.Wiring.MassWireOperationInner().