Terraria Decompiled: Terraria.Wiring.ToggleChandelier
ToggleChandelier()
static void Terraria.Wiring.ToggleChandelier (int i, int j, Tile tileCache, bool? forcedStateWhereTrueIsOn, bool doSkipWires) inline static
Definition at line 3195 of file Wiring.cs.
        {
            int k;
            for (k = (int)(tileCache.frameY / 18); k >= 3; k -= 3)
            {
            }
            int num = j - k;
            int num2 = (int)(tileCache.frameX % 108 / 18);
            if (num2 > 2)
            {
                num2 -= 3;
            }
            num2 = i - num2;
            short num3 = 54;
            if (Main.tile[num2, num].frameX % 108 > 0)
            {
                num3 = -54;
            }
            bool flag = Main.tile[num2, num].frameX % 108 > 0;
            if (forcedStateWhereTrueIsOn != null && !forcedStateWhereTrueIsOn.Value == flag)
            {
                return;
            }
            for (int l = num2; l < num2 + 3; l++)
            {
                for (int m = num; m < num + 3; m++)
                {
                    Tile tile = Main.tile[l, m];
                    tile.frameX += num3;
                    if (doSkipWires)
                    {
                        Wiring.SkipWire(l, m);
                    }
                }
            }
            NetMessage.SendTileSquare(-1, num2 + 1, num + 1, 3, TileChangeType.None);
        }
References Terraria.Tile.frameX, Terraria.Tile.frameY, int, Terraria.NetMessage.SendTileSquare(), Terraria.Wiring.SkipWire(), and Terraria.Main.tile.
Referenced by Terraria.Wiring.HitWireSingle(), and Terraria.WorldGen.TryToggleLight().