Terraria Decompiled: Terraria.WorldBuilding.StructureMap.AddStructure
AddStructure()
void Terraria.WorldBuilding.StructureMap.AddStructure (Rectangle area, int padding = 0) inline
Definition at line 83 of file StructureMap.cs.
        {
            object @lock = this._lock;
            lock (@lock)
            {
                area.Inflate(padding, padding);
                this._structures.Add(area);
            }
        }
References Terraria.WorldBuilding.StructureMap._lock, Terraria.WorldBuilding.StructureMap._structures, System.Collections.Generic.List< T >.Add(), and Microsoft.Xna.Framework.Rectangle.Inflate().
Referenced by Terraria.GameContent.Biomes.DesertBiome.Place(), Terraria.GameContent.Biomes.GraniteBiome.Place(), Terraria.GameContent.Biomes.MarbleBiome.Place(), Terraria.GameContent.Biomes.ThinIceBiome.Place(), and Terraria.GameContent.Biomes.DunesBiome.PlaceSingle().