Terraria Decompiled: Terraria.Wiring.ToggleTorch
ToggleTorch()
static void Terraria.Wiring.ToggleTorch (int i, int j, Tile tileCache, bool? forcedStateWhereTrueIsOn) inline static
Definition at line 3126 of file Wiring.cs.
        {
            bool flag = tileCache.frameX >= 66;
            if (forcedStateWhereTrueIsOn != null && !forcedStateWhereTrueIsOn.Value == flag)
            {
                return;
            }
            if (tileCache.frameX < 66)
            {
                tileCache.frameX += 66;
            }
            else
            {
                tileCache.frameX -= 66;
            }
            NetMessage.SendTileSquare(-1, i, j, TileChangeType.None);
        }
References Terraria.Tile.frameX, and Terraria.NetMessage.SendTileSquare().
Referenced by Terraria.Wiring.HitWireSingle(), and Terraria.WorldGen.TryToggleLight().