Terraria Decompiled: Terraria.Wiring.IsHopperInRangeOf
IsHopperInRangeOf()
static bool Terraria.Wiring.IsHopperInRangeOf (WorldItem item) inline static
Definition at line 2800 of file Wiring.cs.
        {
            if (ItemID.Sets.ItemsThatShouldNotBeInInventory[item.type])
            {
                return false;
            }
            Rectangle hitbox = item.Hitbox;
            hitbox.Inflate((int)(Wiring.HopperGrabHitboxSize.X / 2f), (int)(Wiring.HopperGrabHitboxSize.Y / 2f));
            Point point = hitbox.TopLeft().ToTileCoordinates().ClampedInWorld(0);
            Point point2 = hitbox.BottomRight().ToTileCoordinates().ClampedInWorld(0);
            for (int i = point.X; i <= point2.X; i++)
            {
                for (int j = point.Y; j <= point2.Y; j++)
                {
                    Tile tile = Main.tile[i, j];
                    if (tile != null && tile.active())
                    {
                        int type = (int)tile.type;
                        if ((type == 21 || type == 467) && tile.anyWire())
{
                            return true;
                        }
                    }
                }
            }
            return false;
        }
References Terraria.Tile.active(), Terraria.Tile.anyWire(), Terraria.Wiring.HopperGrabHitboxSize, Microsoft.Xna.Framework.Rectangle.Inflate(), int, System.item, Terraria.ID.ItemID.Sets.ItemsThatShouldNotBeInInventory, Terraria.Main.tile, Terraria.Tile.type, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Point.Y, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.WorldItem.FindOwner().