Terraria Decompiled: Newtonsoft.Json.Linq.JValue.Compare
Compare()
static int Newtonsoft.Json.Linq.JValue.Compare (JTokenType valueType, object objA, object objB) inline static package
Definition at line 151 of file JValue.cs.
        {
            if (objA == objB)
            {
                return 0;
            }
            if (objB == null)
            {
                return 1;
            }
            if (objA == null)
            {
                return -1;
            }
            switch (valueType)
            {
            case JTokenType.Comment:
            case JTokenType.String:
            case JTokenType.Raw:
            {
                string text = Convert.ToString(objA, CultureInfo.InvariantCulture);
                string text2 = Convert.ToString(objB, CultureInfo.InvariantCulture);
                return string.CompareOrdinal(text, text2);
            }
            case JTokenType.Integer:
                if (objA is BigInteger)
                {
                    return JValue.CompareBigInteger((BigInteger)objA, objB);
                }
                if (objB is BigInteger)
                {
                    return -JValue.CompareBigInteger((BigInteger)objB, objA);
                }
                if (objA is ulong || objB is ulong || objA is decimal || objB is decimal)
                {
                    return Convert.ToDecimal(objA, CultureInfo.InvariantCulture).CompareTo(Convert.ToDecimal(objB, CultureInfo.InvariantCulture));
                }
                if (objA is float || objB is float || objA is double || objB is double)
                {
                    return JValue.CompareFloat(objA, objB);
                }
                return Convert.ToInt64(objA, CultureInfo.InvariantCulture).CompareTo(Convert.ToInt64(objB, CultureInfo.InvariantCulture));
            case JTokenType.Float:
                if (objA is BigInteger)
                {
                    return JValue.CompareBigInteger((BigInteger)objA, objB);
                }
                if (objB is BigInteger)
                {
                    return -JValue.CompareBigInteger((BigInteger)objB, objA);
                }
                return JValue.CompareFloat(objA, objB);
            case JTokenType.Boolean:
            {
                bool flag = Convert.ToBoolean(objA, CultureInfo.InvariantCulture);
                bool flag2 = Convert.ToBoolean(objB, CultureInfo.InvariantCulture);
                return flag.CompareTo(flag2);
            }
            case JTokenType.Date:
            {
                if (objA is DateTime)
                {
                    DateTime dateTime = (DateTime)objA;
                    DateTime dateTime2;
                    if (objB is DateTimeOffset)
                    {
                        dateTime2 = ((DateTimeOffset)objB).DateTime;
                    }
                    else
                    {
                        dateTime2 = Convert.ToDateTime(objB, CultureInfo.InvariantCulture);
                    }
                    return dateTime.CompareTo(dateTime2);
                }
                DateTimeOffset dateTimeOffset = (DateTimeOffset)objA;
                DateTimeOffset dateTimeOffset2;
                if (objB is DateTimeOffset)
                {
                    dateTimeOffset2 = (DateTimeOffset)objB;
                }
                else
                {
                    dateTimeOffset2..ctor(Convert.ToDateTime(objB, CultureInfo.InvariantCulture));
                }
                return dateTimeOffset.CompareTo(dateTimeOffset2);
            }
            case JTokenType.Bytes:
            {
                byte[] array = objB as byte[];
                if (array == null)
                {
                    throw new ArgumentException("Object must be of type byte[].");
                }
                return MiscellaneousUtils.ByteArrayCompare(objA as byte[], array);
            }
            case JTokenType.Guid:
            {
                if (!(objB is Guid))
                {
                    throw new ArgumentException("Object must be of type Guid.");
                }
                Guid guid = (Guid)objA;
                Guid guid2 = (Guid)objB;
                return guid.CompareTo(guid2);
            }
            case JTokenType.Uri:
            {
                Uri uri = objB as Uri;
                if (uri == null)
                {
                    throw new ArgumentException("Object must be of type Uri.");
                }
                Uri uri2 = (Uri)objA;
                return Comparer<string>.Default.Compare(uri2.ToString(), uri.ToString());
            }
            case JTokenType.TimeSpan:
            {
                if (!(objB is TimeSpan))
                {
                    throw new ArgumentException("Object must be of type TimeSpan.");
                }
                TimeSpan timeSpan = (TimeSpan)objA;
                TimeSpan timeSpan2 = (TimeSpan)objB;
                return timeSpan.CompareTo(timeSpan2);
            }
            }
            throw MiscellaneousUtils.CreateArgumentOutOfRangeException("valueType", valueType, "Unexpected value type: {0}".FormatWith(CultureInfo.InvariantCulture, valueType));
        }
References System.array, Newtonsoft.Json.Utilities.BigInteger, Newtonsoft.Json.Utilities.MiscellaneousUtils.ByteArrayCompare(), Newtonsoft.Json.Linq.JValue.CompareBigInteger(), Newtonsoft.Json.Linq.JValue.CompareFloat(), System.DateTimeOffset.CompareTo(), System.DateTime.CompareTo(), System.Guid.CompareTo(), System.TimeSpan.CompareTo(), Newtonsoft.Json.Utilities.MiscellaneousUtils.CreateArgumentOutOfRangeException(), System.DateTime.DateTime(), Newtonsoft.Json.DateTime, Newtonsoft.Json.DateTimeOffset, System.Collections.Generic.Comparer< T >.Default, Newtonsoft.Json.Linq.Guid, System.Globalization.CultureInfo.InvariantCulture, System.text, Newtonsoft.Json.Linq.TimeSpan, System.Convert.ToBoolean(), System.Convert.ToDateTime(), System.Convert.ToDecimal(), System.Convert.ToInt64(), System.Convert.ToString(), and Newtonsoft.Json.Linq.Uri.
Referenced by Newtonsoft.Json.Linq.JValue.CompareTo(), Newtonsoft.Json.Linq.JValue.CompareTo(), Newtonsoft.Json.Linq.JValue.JValueDynamicProxy.TryBinaryOperation(), Newtonsoft.Json.JsonValidatingReader.ValidateInteger(), and Newtonsoft.Json.Linq.JValue.ValuesEquals().