Terraria Decompiled: Newtonsoft.Json.Linq.JValue.Operation
Operation()
static bool Newtonsoft.Json.Linq.JValue.Operation (ExpressionType operation, object objA, object objB, out object result) inline static private
Definition at line 293 of file JValue.cs.
        {
            if ((objA is string || objB is string) && (operation == null || operation == 63))
            {
                result = ((objA != null) ? objA.ToString() : null) + ((objB != null) ? objB.ToString() : null);
                return true;
            }
            if (objA is BigInteger || objB is BigInteger)
            {
                if (objA == null || objB == null)
                {
                    result = null;
                    return true;
                }
                BigInteger bigInteger = ConvertUtils.ToBigInteger(objA);
                BigInteger bigInteger2 = ConvertUtils.ToBigInteger(objB);
                if (operation <= 42)
                {
                    if (operation <= 12)
                    {
                        if (operation != null)
{
                            if (operation != 12)
{
                                goto IL_0393;
                            }
                            goto IL_00DE;
                        }
                    }
                    else
                    {
                        if (operation == 26)
{
                            goto IL_00CE;
                        }
                        if (operation != 42)
{
                            goto IL_0393;
                        }
                        goto IL_00BE;
                    }
                }
                else if (operation <= 65)
                {
                    if (operation != 63)
                    {
                        if (operation != 65)
{
                            goto IL_0393;
                        }
                        goto IL_00DE;
                    }
                }
                else
                {
                    if (operation == 69)
                    {
                        goto IL_00CE;
                    }
                    if (operation != 73)
                    {
                        goto IL_0393;
                    }
                    goto IL_00BE;
                }
                result = bigInteger + bigInteger2;
                return true;
                IL_00BE:
                result = bigInteger - bigInteger2;
                return true;
                IL_00CE:
                result = bigInteger * bigInteger2;
                return true;
                IL_00DE:
                result = bigInteger / bigInteger2;
                return true;
            }
            else if (objA is ulong || objB is ulong || objA is decimal || objB is decimal)
            {
                if (objA == null || objB == null)
                {
                    result = null;
                    return true;
                }
                decimal num = Convert.ToDecimal(objA, CultureInfo.InvariantCulture);
                decimal num2 = Convert.ToDecimal(objB, CultureInfo.InvariantCulture);
                if (operation <= 42)
                {
                    if (operation <= 12)
                    {
                        if (operation != null)
{
                            if (operation != 12)
{
                                goto IL_0393;
                            }
                            goto IL_01AD;
                        }
                    }
                    else
                    {
                        if (operation == 26)
{
                            goto IL_019D;
                        }
                        if (operation != 42)
{
                            goto IL_0393;
                        }
                        goto IL_018D;
                    }
                }
                else if (operation <= 65)
                {
                    if (operation != 63)
                    {
                        if (operation != 65)
{
                            goto IL_0393;
                        }
                        goto IL_01AD;
                    }
                }
                else
                {
                    if (operation == 69)
                    {
                        goto IL_019D;
                    }
                    if (operation != 73)
                    {
                        goto IL_0393;
                    }
                    goto IL_018D;
                }
                result = num + num2;
                return true;
                IL_018D:
                result = num - num2;
                return true;
                IL_019D:
                result = num * num2;
                return true;
                IL_01AD:
                result = num / num2;
                return true;
            }
            else if (objA is float || objB is float || objA is double || objB is double)
            {
                if (objA == null || objB == null)
                {
                    result = null;
                    return true;
                }
                double num3 = Convert.ToDouble(objA, CultureInfo.InvariantCulture);
                double num4 = Convert.ToDouble(objB, CultureInfo.InvariantCulture);
                if (operation <= 42)
                {
                    if (operation <= 12)
                    {
                        if (operation != null)
{
                            if (operation != 12)
{
                                goto IL_0393;
                            }
                            goto IL_0278;
                        }
                    }
                    else
                    {
                        if (operation == 26)
{
                            goto IL_026A;
                        }
                        if (operation != 42)
{
                            goto IL_0393;
                        }
                        goto IL_025C;
                    }
                }
                else if (operation <= 65)
                {
                    if (operation != 63)
                    {
                        if (operation != 65)
{
                            goto IL_0393;
                        }
                        goto IL_0278;
                    }
                }
                else
                {
                    if (operation == 69)
                    {
                        goto IL_026A;
                    }
                    if (operation != 73)
                    {
                        goto IL_0393;
                    }
                    goto IL_025C;
                }
                result = num3 + num4;
                return true;
                IL_025C:
                result = num3 - num4;
                return true;
                IL_026A:
                result = num3 * num4;
                return true;
                IL_0278:
                result = num3 / num4;
                return true;
            }
            else if (objA is int || objA is uint || objA is long || objA is short || objA is ushort || objA is sbyte || objA is byte || objB is int || objB is uint || objB is long || objB is short || objB is ushort || objB is sbyte || objB is byte)
            {
                if (objA == null || objB == null)
                {
                    result = null;
                    return true;
                }
                long num5 = Convert.ToInt64(objA, CultureInfo.InvariantCulture);
                long num6 = Convert.ToInt64(objB, CultureInfo.InvariantCulture);
                if (operation <= 42)
                {
                    if (operation <= 12)
                    {
                        if (operation != null)
{
                            if (operation != 12)
{
                                goto IL_0393;
                            }
                            goto IL_0385;
                        }
                    }
                    else
                    {
                        if (operation == 26)
{
                            goto IL_0377;
                        }
                        if (operation != 42)
{
                            goto IL_0393;
                        }
                        goto IL_0369;
                    }
                }
                else if (operation <= 65)
                {
                    if (operation != 63)
                    {
                        if (operation != 65)
{
                            goto IL_0393;
                        }
                        goto IL_0385;
                    }
                }
                else
                {
                    if (operation == 69)
                    {
                        goto IL_0377;
                    }
                    if (operation != 73)
                    {
                        goto IL_0393;
                    }
                    goto IL_0369;
                }
                result = num5 + num6;
                return true;
                IL_0369:
                result = num5 - num6;
                return true;
                IL_0377:
                result = num5 * num6;
                return true;
                IL_0385:
                result = num5 / num6;
                return true;
            }
            IL_0393:
            result = null;
            return false;
        }
References Newtonsoft.Json.Utilities.BigInteger, System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.Utilities.ConvertUtils.ToBigInteger(), System.Convert.ToDecimal(), System.Convert.ToDouble(), and System.Convert.ToInt64().
Referenced by Newtonsoft.Json.Linq.JValue.JValueDynamicProxy.TryBinaryOperation().