Terraria Decompiled: Newtonsoft.Json.Linq.JValue.CompareBigInteger
CompareBigInteger()
static int Newtonsoft.Json.Linq.JValue.CompareBigInteger (BigInteger i1, object i2) inline static private
Definition at line 130 of file JValue.cs.
        {
            int num = i1.CompareTo(ConvertUtils.ToBigInteger(i2));
            if (num != 0)
            {
                return num;
            }
            if (i2 is decimal)
            {
                decimal num2 = (decimal)i2;
                return 0m.CompareTo(Math.Abs(num2 - Math.Truncate(num2)));
            }
            if (i2 is double || i2 is float)
            {
                double num3 = Convert.ToDouble(i2, CultureInfo.InvariantCulture);
                return 0.0.CompareTo(Math.Abs(num3 - Math.Truncate(num3)));
            }
            return num;
        }
References System.Math.Abs(), Newtonsoft.Json.Linq.JValue.CompareTo(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.Utilities.ConvertUtils.ToBigInteger(), System.Convert.ToDouble(), and System.Math.Truncate().
Referenced by Newtonsoft.Json.Linq.JValue.Compare().