Terraria Decompiled: Newtonsoft.Json.Linq.JValue.WriteTo
WriteTo()
override void Newtonsoft.Json.Linq.JValue.WriteTo (JsonWriter writer, params JsonConverter[] converters) inline
Definition at line 725 of file JValue.cs.
        {
            if (converters != null && converters.Length != 0 && this._value != null)
            {
                JsonConverter matchingConverter = JsonSerializer.GetMatchingConverter(converters, this._value.GetType());
                if (matchingConverter != null && matchingConverter.CanWrite)
                {
                    matchingConverter.WriteJson(writer, this._value, JsonSerializer.CreateDefault());
                    return;
                }
            }
            switch (this._valueType)
            {
            case JTokenType.Comment:
            {
                object value = this._value;
                writer.WriteComment((value != null) ? value.ToString() : null);
                return;
            }
            case JTokenType.Integer:
                if (this._value is int)
                {
                    writer.WriteValue((int)this._value);
                    return;
                }
                if (this._value is long)
                {
                    writer.WriteValue((long)this._value);
                    return;
                }
                if (this._value is ulong)
                {
                    writer.WriteValue((ulong)this._value);
                    return;
                }
                if (this._value is BigInteger)
                {
                    writer.WriteValue((BigInteger)this._value);
                    return;
                }
                writer.WriteValue(Convert.ToInt64(this._value, CultureInfo.InvariantCulture));
                return;
            case JTokenType.Float:
                if (this._value is decimal)
                {
                    writer.WriteValue((decimal)this._value);
                    return;
                }
                if (this._value is double)
                {
                    writer.WriteValue((double)this._value);
                    return;
                }
                if (this._value is float)
                {
                    writer.WriteValue((float)this._value);
                    return;
                }
                writer.WriteValue(Convert.ToDouble(this._value, CultureInfo.InvariantCulture));
                return;
            case JTokenType.String:
            {
                object value2 = this._value;
                writer.WriteValue((value2 != null) ? value2.ToString() : null);
                return;
            }
            case JTokenType.Boolean:
                writer.WriteValue(Convert.ToBoolean(this._value, CultureInfo.InvariantCulture));
                return;
            case JTokenType.Null:
                writer.WriteNull();
                return;
            case JTokenType.Undefined:
                writer.WriteUndefined();
                return;
            case JTokenType.Date:
                if (this._value is DateTimeOffset)
                {
                    writer.WriteValue((DateTimeOffset)this._value);
                    return;
                }
                writer.WriteValue(Convert.ToDateTime(this._value, CultureInfo.InvariantCulture));
                return;
            case JTokenType.Raw:
            {
                object value3 = this._value;
                writer.WriteRawValue((value3 != null) ? value3.ToString() : null);
                return;
            }
            case JTokenType.Bytes:
                writer.WriteValue((byte[])this._value);
                return;
            case JTokenType.Guid:
                writer.WriteValue((this._value != null) ? ((Guid?)this._value) : default(Guid?));
                return;
            case JTokenType.Uri:
                writer.WriteValue((Uri)this._value);
                return;
            case JTokenType.TimeSpan:
                writer.WriteValue((this._value != null) ? ((TimeSpan?)this._value) : default(TimeSpan?));
                return;
            default:
                throw MiscellaneousUtils.CreateArgumentOutOfRangeException("Type", this._valueType, "Unexpected token type.");
            }
        }
References Newtonsoft.Json.Linq.JValue._value, Newtonsoft.Json.Linq.JValue._valueType, Newtonsoft.Json.Utilities.BigInteger, Newtonsoft.Json.JsonConverter.CanWrite, Newtonsoft.Json.Utilities.MiscellaneousUtils.CreateArgumentOutOfRangeException(), Newtonsoft.Json.JsonSerializer.CreateDefault(), Newtonsoft.Json.JsonSerializer.GetMatchingConverter(), System.Globalization.CultureInfo.InvariantCulture, System.Convert.ToBoolean(), System.Convert.ToDateTime(), System.Convert.ToDouble(), System.Convert.ToInt64(), System.value, Newtonsoft.Json.JsonWriter.WriteComment(), Newtonsoft.Json.JsonConverter.WriteJson(), Newtonsoft.Json.JsonWriter.WriteNull(), Newtonsoft.Json.JsonWriter.WriteRawValue(), Newtonsoft.Json.JsonWriter.WriteUndefined(), and Newtonsoft.Json.JsonWriter.WriteValue().