Terraria Decompiled: System.Security.Policy.MembershipConditionHelper.Element
Element()
static SecurityElement System.Security.Policy.MembershipConditionHelper.Element (Type type, int version) inline static package
Definition at line 36 of file MembershipConditionHelper.cs.
        {
            SecurityElement securityElement = new SecurityElement(MembershipConditionHelper.XmlTag);
            securityElement.AddAttribute("class", type.FullName + ", " + type.Assembly.ToString().Replace('"', '\''));
            securityElement.AddAttribute("version", version.ToString());
            return securityElement;
        }
References System.Security.SecurityElement.AddAttribute(), System.Type.Assembly, System.Type.FullName, and System.Security.Policy.MembershipConditionHelper.XmlTag.
Referenced by System.Security.Policy.AllMembershipCondition.ToXml(), System.Security.Policy.ApplicationDirectoryMembershipCondition.ToXml(), System.Security.Policy.GacMembershipCondition.ToXml(), System.Security.Policy.HashMembershipCondition.ToXml(), System.Security.Policy.SiteMembershipCondition.ToXml(), System.Security.Policy.StrongNameMembershipCondition.ToXml(), System.Security.Policy.UrlMembershipCondition.ToXml(), and System.Security.Policy.ZoneMembershipCondition.ToXml().