Terraria Decompiled: Terraria.CombatText.NewText
NewText() [1/2]
static int Terraria.CombatText.NewText (Rectangle location, Color color, int amount, bool dramatic = false, bool dot = false) inline static
Definition at line 11 of file CombatText.cs.
        {
            return CombatText.NewText(location, color, amount.ToString(), dramatic, dot);
        }
References Terraria.CombatText.color, Terraria.CombatText.dot, and Terraria.CombatText.NewText().
Referenced by Terraria.NPC.GetHurtByDebuff(), Terraria.Player.HealEffect(), Terraria.NPC.HealEffect(), Terraria.Player.HurtLifeRegen(), Terraria.Player.ManaEffect(), Terraria.CombatText.NewText(), and Terraria.NPC.StrikeNPC().