Terraria Decompiled: Terraria.UI.IngameFancyUI.OpenVirtualKeyboard
OpenVirtualKeyboard()
static void Terraria.UI.IngameFancyUI.OpenVirtualKeyboard (int keyboardContext) inline static
Definition at line 91 of file IngameFancyUI.cs.
        {
            IngameFancyUI.CoverNextFrame();
            IngameFancyUI.ClearChat();
            SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
            string text = "";
            if (keyboardContext != 1)
            {
                if (keyboardContext == 2)
                {
                    text = Language.GetTextValue("UI.EnterNewName");
                    Player player = Main.player[Main.myPlayer];
                    Main.npcChatText = Main.chest[player.chest].name;
                    Tile tile = Main.tile[player.chestX, player.chestY];
                    if (tile.type == 21)
                    {
                        Main.defaultChestName = Lang.chestType[(int)(tile.frameX / 36)].Value;
                    }
                    else if (tile.type == 467 && tile.frameX / 36 == 4)
                    {
                        Main.defaultChestName = Lang.GetItemNameValue(3988);
                    }
                    else if (tile.type == 467)
                    {
                        Main.defaultChestName = Lang.chestType2[(int)(tile.frameX / 36)].Value;
                    }
                    else if (tile.type == 88)
                    {
                        Main.defaultChestName = Lang.dresserType[(int)(tile.frameX / 54)].Value;
                    }
                    if (Main.npcChatText == "")
                    {
                        Main.npcChatText = Main.defaultChestName;
                    }
                    Main.editChest = true;
                }
            }
            else
            {
                Main.editSign = true;
                text = Language.GetTextValue("UI.EnterMessage");
            }
            Main.clrInput();
            if (!IngameFancyUI.CanShowVirtualKeyboard(keyboardContext))
            {
                return;
            }
            Main.inFancyUI = true;
            if (keyboardContext != 1)
            {
                if (keyboardContext == 2)
                {
                    Main.InGameUI.SetState(new UIVirtualKeyboard(text, Main.npcChatText, delegate(string s)
                    {
                        ChestUI.RenameChestSubmit(Main.player[Main.myPlayer]);
                        IngameFancyUI.Close(true);
                    }, delegate
                    {
                        ChestUI.RenameChestCancel();
                        IngameFancyUI.Close(true);
                    }, keyboardContext, false, 20));
                }
            }
            else
            {
                Main.InGameUI.SetState(new UIVirtualKeyboard(text, Main.npcChatText, delegate(string s)
                {
                    Main.SubmitSignText();
                    IngameFancyUI.Close(true);
                }, delegate
                {
                    Main.InputTextSignCancel();
                    IngameFancyUI.Close(true);
                }, keyboardContext, false, 1200));
            }
            UILinkPointNavigator.GoToDefaultPage(1);
        }
References Terraria.UI.IngameFancyUI.CanShowVirtualKeyboard(), Terraria.Main.chest, Terraria.Player.chest, Terraria.Lang.chestType, Terraria.Lang.chestType2, Terraria.Player.chestX, Terraria.Player.chestY, Terraria.UI.IngameFancyUI.ClearChat(), Terraria.UI.IngameFancyUI.Close(), Terraria.Main.clrInput(), Terraria.UI.IngameFancyUI.CoverNextFrame(), Terraria.Main.defaultChestName, Terraria.Lang.dresserType, Terraria.Tile.frameX, Terraria.Lang.GetItemNameValue(), Terraria.Localization.Language.GetTextValue(), Terraria.UI.Gamepad.UILinkPointNavigator.GoToDefaultPage(), Terraria.Main.InGameUI, Terraria.Main.InputTextSignCancel(), int, Terraria.Main.myPlayer, Terraria.Chest.name, Terraria.Main.npcChatText, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.UI.ChestUI.RenameChestCancel(), Terraria.UI.ChestUI.RenameChestSubmit(), System.s, Terraria.Main.SubmitSignText(), System.text, Terraria.Main.tile, Terraria.Tile.type, and Terraria.Localization.LocalizedText.Value.
Referenced by Terraria.GameContent.NPCInteractions.Actions.OpenSign.Interact(), and Terraria.UI.ChestUI.RenameChest().