Terraria Decompiled: Terraria.UI.IngameFancyUI.Close
Close()
static void Terraria.UI.IngameFancyUI.Close (bool quiet = false) inline static
Definition at line 170 of file IngameFancyUI.cs.
        {
            Main.inFancyUI = false;
            if (!quiet)
            {
                SoundEngine.PlaySound(11, -1, -1, 1, 1f, 0f);
            }
            bool flag = false;
            if (!Main.gameMenu)
            {
                if (Main.InGameUI.CurrentState is UIVirtualKeyboard)
                {
                    flag = UIVirtualKeyboard.KeyboardContext == 2;
                }
                else if (!(Main.InGameUI.CurrentState is UIEmotesMenu))
                {
                    flag = true;
                }
            }
            if (flag)
            {
                Main.playerInventory = true;
            }
            Main.LocalPlayer.releaseInventory = false;
            Main.InGameUI.SetState(null);
            UILinkPointNavigator.Shortcuts.FANCYUI_SPECIAL_INSTRUCTIONS = 0;
        }
References Terraria.Main.gameMenu, Terraria.Main.InGameUI, and Terraria.Audio.SoundEngine.PlaySound().
Referenced by Terraria.GameContent.UI.States.UIBestiaryTest.Click_GoBack(), Terraria.GameContent.UI.States.UIWorldGenDebug.Close(), Terraria.UI.IngameUIWindows.CloseAll(), Terraria.GameContent.UI.States.UIVirtualKeyboard.DrawSelf(), Terraria.Initializers.UILinksInitializer.FancyExit(), Terraria.GameContent.UI.States.UIAchievementsMenu.GoBackClick(), Terraria.GameContent.UI.States.UIDebugCommandsList.GoBackClick(), Terraria.GameContent.UI.States.UIEmotesMenu.GoBackClick(), Terraria.GameContent.UI.States.UIManageControls.GoBackClick(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.GoBackFromVirtualKeyboard(), Terraria.GameContent.UI.NewCraftingUI.GoBackFromVirtualKeyboard(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.HandleBackButtonUsage(), Terraria.GameContent.UI.Elements.EmoteButton.LeftClick(), Terraria.GameContent.UI.Elements.UIDebugCommandItem.LeftClick(), Terraria.UI.IngameFancyUI.OpenVirtualKeyboard(), Terraria.Player.ToggleInv(), and Terraria.GameContent.UI.States.UIVirtualKeyboard.TryEscapingMenu().