Terraria Decompiled: System.Diagnostics.StackTrace.ConvertAsyncStateMachineMethod
ConvertAsyncStateMachineMethod()
static void System.Diagnostics.StackTrace.ConvertAsyncStateMachineMethod (ref MethodBase method, ref Type declaringType) inline static private
Definition at line 331 of file StackTrace.cs.
        {
            Type declaringType2 = declaringType.DeclaringType;
            if (declaringType2 == null)
            {
                return;
            }
            MethodInfo[] methods = declaringType2.GetMethods(BindingFlags.DeclaredOnly | BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic);
            if (methods == null)
            {
                return;
            }
            foreach (MethodInfo methodInfo in methods)
            {
                IEnumerable<AsyncStateMachineAttribute> customAttributes = methodInfo.GetCustomAttributes<AsyncStateMachineAttribute>();
                if (customAttributes != null)
                {
                    using (IEnumerator<AsyncStateMachineAttribute> enumerator = customAttributes.GetEnumerator())
                    {
                        while (enumerator.MoveNext())
{
                            if (enumerator.Current.StateMachineType == declaringType)
{
                                method = methodInfo;
                                declaringType = methodInfo.DeclaringType;
                                return;
                            }
                        }
                    }
                }
            }
        }
References System.Collections.Generic.IEnumerator< out T >.Current, System.Runtime.InteropServices._MethodInfo.DeclaringType, System.Type.DeclaringType, System.Runtime.InteropServices._MethodInfo.GetCustomAttributes(), System.Collections.Generic.IEnumerable< out T >.GetEnumerator(), System.Type.GetMethods(), and System.Collections.IEnumerator.MoveNext().
Referenced by System.Diagnostics.StackTrace.GetFullNameForStackTrace().