Terraria Decompiled: System.Diagnostics.StackTrace.GetFullNameForStackTrace
GetFullNameForStackTrace()
void System.Diagnostics.StackTrace.GetFullNameForStackTrace (StringBuilder sb, MethodBase mi, bool needsNewLine, out bool skipped, out bool isAsync) inline private
Definition at line 259 of file StackTrace.cs.
        {
            Type type = mi.DeclaringType;
            if (type.IsGenericType && !type.IsGenericTypeDefinition)
            {
                type = type.GetGenericTypeDefinition();
                foreach (MethodInfo methodInfo in type.GetMethods(BindingFlags.DeclaredOnly | BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic))
                {
                    if (methodInfo.MetadataToken == mi.MetadataToken)
                    {
                        mi = methodInfo;
                        break;
                    }
                }
            }
            isAsync = typeof(IAsyncStateMachine).IsAssignableFrom(type);
            skipped = mi.IsDefined(typeof(StackTraceHiddenAttribute)) || type.IsDefined(typeof(StackTraceHiddenAttribute));
            if (skipped)
            {
                return;
            }
            if (isAsync)
            {
                StackTrace.ConvertAsyncStateMachineMethod(ref mi, ref type);
            }
            if (needsNewLine)
            {
                sb.Append(Environment.NewLine);
            }
            sb.Append("  at ");
            sb.Append(type.ToString());
            sb.Append(".");
            sb.Append(mi.Name);
            if (mi.IsGenericMethod)
            {
                mi = ((MethodInfo)mi).GetGenericMethodDefinition();
                Type[] genericArguments = mi.GetGenericArguments();
                sb.Append("[");
                for (int j = 0; j < genericArguments.Length; j++)
                {
                    if (j > 0)
                    {
                        sb.Append(",");
                    }
                    sb.Append(genericArguments[j].Name);
                }
                sb.Append("]");
            }
            ParameterInfo[] parameters = mi.GetParameters();
            sb.Append(" (");
            for (int k = 0; k < parameters.Length; k++)
            {
                if (k > 0)
                {
                    sb.Append(", ");
                }
                Type type2 = parameters[k].ParameterType;
                if (type2.IsGenericType && !type2.IsGenericTypeDefinition)
                {
                    type2 = type2.GetGenericTypeDefinition();
                }
                sb.Append(type2.ToString());
                if (parameters[k].Name != null)
                {
                    sb.Append(" ");
                    sb.Append(parameters[k].Name);
                }
            }
            sb.Append(")");
        }
References System.Text.StringBuilder.Append(), System.Diagnostics.StackTrace.ConvertAsyncStateMachineMethod(), System.Reflection.MemberInfo.DeclaringType, System.Reflection.MethodBase.GetGenericArguments(), System.Type.GetGenericTypeDefinition(), System.Type.GetMethods(), System.Reflection.MethodBase.GetParameters(), System.Reflection.MemberInfo.IsDefined(), System.Reflection.MethodBase.IsGenericMethod, System.Type.IsGenericType, System.Type.IsGenericTypeDefinition, System.Reflection.MemberInfo.MetadataToken, System.Reflection.MemberInfo.Name, System.Name, System.Reflection.ParameterInfo.ParameterType, and System.Type.ToString().
Referenced by System.Diagnostics.StackTrace.AddFrames().