Terraria Decompiled: System.Diagnostics.StackTrace.AddFrames
AddFrames()
bool System.Diagnostics.StackTrace.AddFrames (StringBuilder sb, bool separator, out bool isAsync) inline private
Definition at line 188 of file StackTrace.cs.
        {
            isAsync = false;
            bool flag = false;
            int i = 0;
            while (i < this.FrameCount)
            {
                StackFrame frame = this.GetFrame(i);
                if (frame.GetMethod() == null)
                {
                    if (flag || separator)
                    {
                        sb.Append(Environment.NewLine);
                    }
                    sb.Append("  at ");
                    string internalMethodName = frame.GetInternalMethodName();
                    if (internalMethodName != null)
                    {
                        sb.Append(internalMethodName);
                        goto IL_0180;
                    }
                    sb.AppendFormat("<0x{0:x5} + 0x{1:x5}> <unknown method>", frame.GetMethodAddress(), frame.GetNativeOffset());
                    goto IL_0180;
                }
                else
                {
                    bool flag2;
                    this.GetFullNameForStackTrace(sb, frame.GetMethod(), flag || separator, out flag2, out isAsync);
                    if (!flag2)
                    {
                        if (frame.GetILOffset() == -1)
{
                            sb.AppendFormat(" <0x{0:x5} + 0x{1:x5}>", frame.GetMethodAddress(), frame.GetNativeOffset());
                            if (frame.GetMethodIndex() != 16777215U)
{
                                sb.AppendFormat(" {0}", frame.GetMethodIndex());
                            }
                        }
                        else
{
                            sb.AppendFormat(" [0x{0:x5}]", frame.GetILOffset());
                        }
                        string text = frame.GetSecureFileName();
                        if (text[0] == '<')
{
                            string text2 = frame.GetMethod().Module.ModuleVersionId.ToString("N");
                            string aotId = StackTrace.GetAotId();
                            if (frame.GetILOffset() != -1 || aotId == null)
{
                                text = string.Format("<{0}>", text2);
                            }
                            else
{
                                text = string.Format("<{0}#{1}>", text2, aotId);
                            }
                        }
                        sb.AppendFormat(" in {0}:{1} ", text, frame.GetFileLineNumber());
                        goto IL_0180;
                    }
                }
                IL_0182:
                i++;
                continue;
                IL_0180:
                flag = true;
                goto IL_0182;
            }
            return flag;
        }
References System.Text.StringBuilder.Append(), System.Text.StringBuilder.AppendFormat(), System.Diagnostics.StackTrace.FrameCount, System.Diagnostics.StackTrace.GetAotId(), System.Diagnostics.StackFrame.GetFileLineNumber(), System.Diagnostics.StackTrace.GetFrame(), System.Diagnostics.StackTrace.GetFullNameForStackTrace(), System.Diagnostics.StackFrame.GetILOffset(), System.Diagnostics.StackFrame.GetInternalMethodName(), System.Diagnostics.StackFrame.GetMethod(), System.Diagnostics.StackFrame.GetMethodAddress(), System.Diagnostics.StackFrame.GetMethodIndex(), System.Diagnostics.StackFrame.GetNativeOffset(), System.Diagnostics.StackFrame.GetSecureFileName(), System.Reflection.MemberInfo.Module, System.Reflection.Module.ModuleVersionId, System.text, System.Guid.ToString(), and System.U.
Referenced by System.Diagnostics.StackTrace.ToString().