Terraria Decompiled: System.Diagnostics.StackTrace.init_frames
init_frames()
void System.Diagnostics.StackTrace.init_frames (int skipFrames, bool fNeedFileInfo) inline private
Definition at line 47 of file StackTrace.cs.
        {
            if (skipFrames < 0)
            {
                throw new ArgumentOutOfRangeException("< 0", "skipFrames");
            }
            List<StackFrame> list = new List<StackFrame>();
            skipFrames += 2;
            StackFrame stackFrame;
            while ((stackFrame = new StackFrame(skipFrames, fNeedFileInfo)) != null && stackFrame.GetMethod() != null)
            {
                list.Add(stackFrame);
                skipFrames++;
            }
            this.debug_info = fNeedFileInfo;
            this.frames = list.ToArray();
        }
References System.Diagnostics.StackFrame.GetMethod(), and System.list.
Referenced by System.Diagnostics.StackTrace.StackTrace(), System.Diagnostics.StackTrace.StackTrace(), System.Diagnostics.StackTrace.StackTrace(), System.Diagnostics.StackTrace.StackTrace(), and System.Diagnostics.StackTrace.StackTrace().