Terraria Decompiled: Steamworks.SteamApps.BGetDLCDataByIndex
BGetDLCDataByIndex()
static bool Steamworks.SteamApps.BGetDLCDataByIndex (int iDLC, out AppId_t pAppID, out bool pbAvailable, out string pchName, int cchNameBufferSize) inline static
Definition at line 87 of file SteamApps.cs.
        {
            InteropHelp.TestIfAvailableClient();
            IntPtr intPtr = Marshal.AllocHGlobal(cchNameBufferSize);
            bool flag = NativeMethods.ISteamApps_BGetDLCDataByIndex(CSteamAPIContext.GetSteamApps(), iDLC, out pAppID, out pbAvailable, intPtr, cchNameBufferSize);
            pchName = (flag ? InteropHelp.PtrToStringUTF8(intPtr) : null);
            Marshal.FreeHGlobal(intPtr);
            return flag;
        }
References System.Runtime.InteropServices.Marshal.AllocHGlobal(), System.Runtime.InteropServices.Marshal.FreeHGlobal(), Steamworks.CSteamAPIContext.GetSteamApps(), Steamworks.NativeMethods.ISteamApps_BGetDLCDataByIndex(), Steamworks.InteropHelp.PtrToStringUTF8(), and Steamworks.InteropHelp.TestIfAvailableClient().