Terraria Decompiled: Terraria.GameContent.Drawing.NextNatureRenderer.DrawAfterAllObjects
DrawAfterAllObjects()
void Terraria.GameContent.Drawing.NextNatureRenderer.DrawAfterAllObjects (SpriteBatchBeginner beginner) inline
Implements Terraria.GameContent.Drawing.INatureRenderer.
Definition at line 65 of file NextNatureRenderer.cs.
        {
            if (this._entries.Count == 0)
            {
                return;
            }
            TimeLogger.StartTimestamp startTimestamp = TimeLogger.Start();
            float num = 0f;
            if (Main.dayTime)
            {
                float num2 = (float)Main.time;
                float num3 = 54000f;
                float num4 = Utils.Remap(num2, 1200f, 5400f, 0f, 1f, true) * Utils.Remap(num2, 1200f, 7200f, 1f, 0f, true) * 0.3f;
                float num5 = Utils.Remap(num2, num3 - 10800f, num3 - 4200f, 0f, 1f, true) * Utils.Remap(num2, num3 - 1800f, num3 - 600f, 1f, 0f, true) * 0.4f;
                num5 *= num5;
                float num6 = Utils.Remap(num2, 0f, 7200f, 0f, 1f, true) * Utils.Remap(num2, num3 - 7200f, num3, 1f, 0f, true) * 0f;
                num = Math.Max(Math.Max(num4, num5), num6);
                if (Main.eclipse)
                {
                    num = 0f;
                }
            }
            num *= 0.4f;
            Vector2 lastCelestialBodyPosition = Main.LastCelestialBodyPosition;
            float num7 = Utils.Remap(Math.Min(lastCelestialBodyPosition.X, 1f - lastCelestialBodyPosition.X), 0f, 0.010416667f, 0f, 1f, true);
            num *= num7;
            if (!Main.ShouldDrawSurfaceBackground() || !Main.HorizonHelper.SunVisibilityEnabled)
            {
                num = 0f;
            }
            if (num == 0f)
            {
                this.DrawWithoutShader(beginner, Main.spriteBatch);
            }
            else
            {
                this.DrawWithLitNatureShader(beginner, num, lastCelestialBodyPosition);
            }
            this._entries.Clear();
            TimeLogger.Nature.AddTime(startTimestamp);
        }
References Terraria.GameContent.Drawing.NextNatureRenderer._entries, Terraria.Main.dayTime, Terraria.GameContent.Drawing.NextNatureRenderer.DrawWithLitNatureShader(), Terraria.GameContent.Drawing.NextNatureRenderer.DrawWithoutShader(), Terraria.Main.eclipse, Terraria.Main.HorizonHelper, Terraria.Main.LastCelestialBodyPosition, System.Math.Max(), System.Math.Min(), Terraria.TimeLogger.Nature, Terraria.Utils.Remap(), Terraria.Main.ShouldDrawSurfaceBackground(), Terraria.Main.spriteBatch, Terraria.TimeLogger.Start(), Terraria.Main.time, and Microsoft.Xna.Framework.Vector2.X.