Terraria Decompiled: Terraria.GameContent.Drawing.NextNatureRenderer.DrawWithLitNatureShader
DrawWithLitNatureShader()
void Terraria.GameContent.Drawing.NextNatureRenderer.DrawWithLitNatureShader (SpriteBatchBeginner beginner, float visibility, Vector2 sunPosition) inline private
Definition at line 120 of file NextNatureRenderer.cs.
        {
            SpriteDrawBuffer spriteBuffer = Main.spriteBuffer;
            foreach (NextNatureRenderer.Entry entry in this._entries)
            {
                DrawData data = entry.Data;
                data.Draw(spriteBuffer);
            }
            MiscShaderData miscShaderData = GameShaders.Misc["LitNature"];
            Vector2 vector = Vector2.Transform(Main.ReverseGravitySupport(sunPosition * Main.ScreenSize.ToVector2(), 0f), Matrix.Invert(Main.Transform));
            Vector4 vector2 = new Vector4(vector.X, vector.Y, visibility, 0f);
            miscShaderData.UseImage1(Main.HorizonHelper.SunVisibilityPixelTexture);
            miscShaderData.UseSpriteTransformMatrix(new Matrix?(beginner.transformMatrix));
            Color color;
            Color color2;
            HorizonHelper.GetCelestialBodyColors(out color, out color2);
            Color color3 = (Main.dayTime ? color : color2);
            Vector3 vector3 = Main.rgbToHsl(color3);
            color3 = Main.hslToRgb(vector3.X, Utils.Clamp<float>(vector3.Y * 8f, 0f, 1f), vector3.Z * 1f, byte.MaxValue) * 0.5f;
            miscShaderData.UseColor(Color.Lerp(color3, new Color(255, 200, 0), 0.8f));
            int num = 0;
            foreach (NextNatureRenderer.Entry entry2 in this._entries)
            {
                vector2.W = (float)(entry2.IsGlowMask ? ((SideFlags)(-1)) : entry2.Seams);
                miscShaderData.UseShaderSpecificData(vector2);
                miscShaderData.Apply(new DrawData?(entry2.Data));
                spriteBuffer.DrawSingle(num++);
            }
            spriteBuffer.Unbind();
        }
References Terraria.Graphics.Shaders.MiscShaderData.Apply(), Terraria.Utils.Clamp(), Terraria.DataStructures.DrawData.Draw(), Terraria.DataStructures.SpriteDrawBuffer.DrawSingle(), Terraria.GameContent.Drawing.HorizonHelper.GetCelestialBodyColors(), Terraria.Main.HorizonHelper, Terraria.Main.hslToRgb(), Microsoft.Xna.Framework.Matrix.Invert(), Microsoft.Xna.Framework.Color.Lerp(), Terraria.Graphics.Shaders.GameShaders.Misc, Terraria.Main.ReverseGravitySupport(), Terraria.Main.rgbToHsl(), Terraria.Main.ScreenSize, Terraria.Main.spriteBuffer, Microsoft.Xna.Framework.Vector2.Transform(), Terraria.Main.Transform, Terraria.DataStructures.SpriteBatchBeginner.transformMatrix, Terraria.DataStructures.SpriteDrawBuffer.Unbind(), Terraria.Graphics.Shaders.MiscShaderData.UseColor(), Terraria.Graphics.Shaders.MiscShaderData.UseImage1(), Terraria.Graphics.Shaders.MiscShaderData.UseShaderSpecificData(), Terraria.Graphics.Shaders.MiscShaderData.UseSpriteTransformMatrix(), Microsoft.Xna.Framework.Graphics.Vector4, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector3.X, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector3.Y.
Referenced by Terraria.GameContent.Drawing.NextNatureRenderer.DrawAfterAllObjects().