Terraria Decompiled: Terraria.GameContent.ShopHelper.IsFarFromHome
IsFarFromHome()
bool Terraria.GameContent.ShopHelper.IsFarFromHome (NPC npc) inline private
Definition at line 350 of file ShopHelper.cs.
        {
            Vector2 vector = new Vector2((float)npc.homeTileX, (float)npc.homeTileY);
            Vector2 vector2 = new Vector2(npc.Center.X / 16f, npc.Center.Y / 16f);
            if (Vector2.Distance(vector, vector2) > 120f)
            {
                this.AddHappinessReportText("FarFromHome", null);
                return true;
            }
            return false;
        }
References Terraria.GameContent.ShopHelper.AddHappinessReportText(), Terraria.Entity.Center, Microsoft.Xna.Framework.Vector2.Distance(), Terraria.NPC.homeTileX, Terraria.NPC.homeTileY, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.GameContent.ShopHelper.ProcessMood().