Terraria Decompiled: Terraria.GameContent.ShopHelper.IsPlayerInEvilBiomes
IsPlayerInEvilBiomes()
bool Terraria.GameContent.ShopHelper.IsPlayerInEvilBiomes (Player player) inline private
Definition at line 363 of file ShopHelper.cs.
        {
            for (int i = 0; i < this._dangerousBiomes.Length; i++)
            {
                AShoppingBiome ashoppingBiome = this._dangerousBiomes[i];
                if (ashoppingBiome.IsInBiome(player))
                {
                    this.AddHappinessReportText("HateBiome", new
                    {
                        BiomeName = ShopHelper.BiomeNameByKey(ashoppingBiome.NameKey)
                    });
                    return true;
                }
            }
            return false;
        }
References Terraria.GameContent.ShopHelper._dangerousBiomes, Terraria.GameContent.ShopHelper.AddHappinessReportText(), Terraria.GameContent.ShopHelper.BiomeNameByKey(), Terraria.GameContent.Personalities.AShoppingBiome.IsInBiome(), and Terraria.GameContent.Personalities.AShoppingBiome.NameKey.
Referenced by Terraria.GameContent.ShopHelper.ProcessMood().