Terraria Decompiled: Terraria.GameContent.ShopHelper.ProcessMood
ProcessMood()
void Terraria.GameContent.ShopHelper.ProcessMood (Player player, NPC npc) inline private
Definition at line 74 of file ShopHelper.cs.
        {
            this._currentHappiness = "";
            this._currentPriceAdjustment = 1f;
            if (npc.loveStruck)
            {
                this._currentPriceAdjustment *= 0.9f;
            }
            if (Main.remixWorld)
            {
                return;
            }
            if (npc.type == 368)
            {
                return;
            }
            if (npc.type == 453)
            {
                return;
            }
            if (NPCID.Sets.IsTownPet[npc.type])
            {
                return;
            }
            if (this.IsNotReallyTownNPC(npc))
            {
                return;
            }
            if (this.RuinMoodIfHomeless(npc))
            {
                this._currentPriceAdjustment = 1000f;
            }
            else if (this.IsFarFromHome(npc))
            {
                this._currentPriceAdjustment = 1000f;
            }
            if (this.IsPlayerInEvilBiomes(player))
            {
                this._currentPriceAdjustment = 1000f;
            }
            int num;
            int num2;
            List<NPC> nearbyResidentNPCs = this.GetNearbyResidentNPCs(npc, out num, out num2);
            bool flag = true;
            bool flag2 = true;
            float num3 = 1.05f;
            if (npc.type == 663)
            {
                flag = false;
                num3 = 1f;
                if (num < 2 && num2 < 2)
                {
                    this.AddHappinessReportText("HateLonely", null);
                    this._currentPriceAdjustment = 1000f;
                }
            }
            if (flag2 && num > 3)
            {
                for (int i = 3; i < num; i++)
                {
                    this._currentPriceAdjustment *= num3;
                }
                if (num > 6)
                {
                    this.AddHappinessReportText("HateCrowded", null);
                }
                else
                {
                    this.AddHappinessReportText("DislikeCrowded", null);
                }
            }
            if (flag && num <= 2 && num2 < 4)
            {
                this.AddHappinessReportText("LoveSpace", null);
                this._currentPriceAdjustment *= 0.95f;
            }
            bool[] array = new bool[(int)NPCID.Count];
            foreach (NPC npc2 in nearbyResidentNPCs)
            {
                array[npc2.type] = true;
            }
            HelperInfo helperInfo = new HelperInfo
            {
                player = player,
                npc = npc,
                NearbyNPCs = nearbyResidentNPCs,
                nearbyNPCsByType = array
            };
            foreach (IShopPersonalityTrait shopPersonalityTrait in this._database.GetByNPCID(npc.type).ShopModifiers)
            {
                shopPersonalityTrait.ModifyShopPrice(helperInfo, this);
            }
            new AllPersonalitiesModifier().ModifyShopPrice(helperInfo, this);
            if (this._currentHappiness == "")
            {
                this.AddHappinessReportText("Content", null);
            }
            this._currentPriceAdjustment = this.LimitAndRoundMultiplier(this._currentPriceAdjustment);
        }
References Terraria.GameContent.ShopHelper._currentHappiness, Terraria.GameContent.ShopHelper._currentPriceAdjustment, Terraria.GameContent.ShopHelper._database, Terraria.GameContent.ShopHelper.AddHappinessReportText(), System.array, Terraria.ID.NPCID.Count, Terraria.GameContent.Personalities.PersonalityDatabase.GetByNPCID(), Terraria.GameContent.ShopHelper.GetNearbyResidentNPCs(), int, Terraria.GameContent.ShopHelper.IsFarFromHome(), Terraria.GameContent.ShopHelper.IsNotReallyTownNPC(), Terraria.GameContent.ShopHelper.IsPlayerInEvilBiomes(), Terraria.ID.NPCID.Sets.IsTownPet, Terraria.GameContent.ShopHelper.LimitAndRoundMultiplier(), Terraria.NPC.loveStruck, Terraria.GameContent.Personalities.AllPersonalitiesModifier.ModifyShopPrice(), Terraria.GameContent.Personalities.IShopPersonalityTrait.ModifyShopPrice(), Terraria.Main.remixWorld, Terraria.GameContent.ShopHelper.RuinMoodIfHomeless(), Terraria.GameContent.Personalities.PersonalityProfile.ShopModifiers, and Terraria.NPC.type.
Referenced by Terraria.GameContent.ShopHelper.GetShoppingSettings().