Terraria Decompiled: System.DateTimeParse.GetDateTimeParseException
GetDateTimeParseException()
static Exception System.DateTimeParse.GetDateTimeParseException (ref DateTimeResult result) inline static private
Definition at line 3629 of file DateTimeParse.cs.
        {
            switch (result.failure)
            {
            case ParseFailureKind.ArgumentNull:
                return new ArgumentNullException(result.failureArgumentName, SR.GetResourceString(result.failureMessageID));
            case ParseFailureKind.Format:
                return new FormatException(SR.GetResourceString(result.failureMessageID));
            case ParseFailureKind.FormatWithParameter:
                return new FormatException(SR.Format(SR.GetResourceString(result.failureMessageID), result.failureMessageFormatArgument));
            case ParseFailureKind.FormatWithOriginalDateTime:
                return new FormatException(SR.Format(SR.GetResourceString(result.failureMessageID), new string(result.originalDateTimeString)));
            case ParseFailureKind.FormatWithFormatSpecifier:
                return new FormatException(SR.Format(SR.GetResourceString(result.failureMessageID), new string(result.failedFormatSpecifier)));
            case ParseFailureKind.FormatWithOriginalDateTimeAndParameter:
                return new FormatException(SR.Format(SR.GetResourceString(result.failureMessageID), new string(result.originalDateTimeString), result.failureMessageFormatArgument));
            case ParseFailureKind.FormatBadDateTimeCalendar:
                return new FormatException(SR.Format(SR.GetResourceString(result.failureMessageID), new string(result.originalDateTimeString), result.calendar));
            default:
                return null;
            }
        }
References SR.Format(), and SR.GetResourceString().
Referenced by System.DateTimeParse.Parse(), System.DateTimeParse.Parse(), System.DateTimeParse.ParseExact(), System.DateTimeParse.ParseExact(), System.DateTimeParse.ParseExactMultiple(), and System.DateTimeParse.ParseExactMultiple().