Terraria Decompiled: System.DateTimeParse.DateTimeOffsetTimeZonePostProcessing
DateTimeOffsetTimeZonePostProcessing()
static bool System.DateTimeParse.DateTimeOffsetTimeZonePostProcessing (ref __DTString str, ref DateTimeResult result, DateTimeStyles styles) inline static private
Definition at line 2210 of file DateTimeParse.cs.
        {
            if ((result.flags & ParseFlags.TimeZoneUsed) == (ParseFlags)0)
            {
                if ((styles & DateTimeStyles.AssumeUniversal) != DateTimeStyles.None)
                {
                    result.timeZoneOffset = TimeSpan.Zero;
                }
                else
                {
                    result.timeZoneOffset = TimeZoneInfo.GetLocalUtcOffset(result.parsedDate, TimeZoneInfoOptions.NoThrowOnInvalidTime);
                }
            }
            long ticks = result.timeZoneOffset.Ticks;
            long num = result.parsedDate.Ticks - ticks;
            if (num < 0L || num > 3155378975999999999L)
            {
                result.SetFailure(ParseFailureKind.FormatWithOriginalDateTime, "The UTC representation of the date falls outside the year range 1-9999.");
                return false;
            }
            if (ticks < -504000000000L || ticks > 504000000000L)
            {
                result.SetFailure(ParseFailureKind.FormatWithOriginalDateTime, "The time zone offset must be within plus or minus 14 hours.");
                return false;
            }
            if ((styles & DateTimeStyles.AdjustToUniversal) != DateTimeStyles.None)
            {
                if ((result.flags & ParseFlags.TimeZoneUsed) == (ParseFlags)0 && (styles & DateTimeStyles.AssumeUniversal) == DateTimeStyles.None)
                {
                    bool flag = DateTimeParse.AdjustTimeZoneToUniversal(ref result);
                    result.timeZoneOffset = TimeSpan.Zero;
                    return flag;
                }
                result.parsedDate = new DateTime(num, DateTimeKind.Utc);
                result.timeZoneOffset = TimeSpan.Zero;
            }
            return true;
        }
References System.DateTimeParse.AdjustTimeZoneToUniversal(), System.DateTime, System.TimeZoneInfo.GetLocalUtcOffset(), System.L, System.TimeSpan.Ticks, and System.TimeSpan.Zero.
Referenced by System.DateTimeParse.DetermineTimeZoneAdjustments().