Terraria Decompiled: System.DateTimeParse.AdjustTimeZoneToLocal
AdjustTimeZoneToLocal()
static bool System.DateTimeParse.AdjustTimeZoneToLocal (ref DateTimeResult result, bool bTimeOnly) inline static private
Definition at line 2268 of file DateTimeParse.cs.
        {
            long num = result.parsedDate.Ticks;
            TimeZoneInfo local = TimeZoneInfo.Local;
            bool flag = false;
            if (num < 864000000000L)
            {
                num -= result.timeZoneOffset.Ticks;
                num += local.GetUtcOffset(bTimeOnly ? DateTime.Now : result.parsedDate, TimeZoneInfoOptions.NoThrowOnInvalidTime).Ticks;
                if (num < 0L)
                {
                    num += 864000000000L;
                }
            }
            else
            {
                num -= result.timeZoneOffset.Ticks;
                if (num < 0L || num > 3155378975999999999L)
                {
                    num += local.GetUtcOffset(result.parsedDate, TimeZoneInfoOptions.NoThrowOnInvalidTime).Ticks;
                }
                else
                {
                    DateTime dateTime = new DateTime(num, DateTimeKind.Utc);
                    bool flag2 = false;
                    num += TimeZoneInfo.GetUtcOffsetFromUtc(dateTime, TimeZoneInfo.Local, out flag2, out flag).Ticks;
                }
            }
            if (num < 0L || num > 3155378975999999999L)
            {
                result.parsedDate = DateTime.MinValue;
                result.SetFailure(ParseFailureKind.FormatWithOriginalDateTime, "The DateTime represented by the string is out of range.");
                return false;
            }
            result.parsedDate = new DateTime(num, DateTimeKind.Local, flag);
            return true;
        }
References System.DateTime, System.TimeZoneInfo.GetUtcOffset(), System.TimeZoneInfo.GetUtcOffsetFromUtc(), System.L, System.TimeZoneInfo.Local, System.DateTime.MinValue, System.DateTime.Now, and System.TimeSpan.Ticks.
Referenced by System.DateTimeParse.DetermineTimeZoneAdjustments().