Terraria Decompiled: System.DateTimeParse.Lex
Lex()
static unsafe bool System.DateTimeParse.Lex (DateTimeParse::DS dps, ref __DTString str, ref DateTimeToken dtok, ref DateTimeRawInfo raw, ref DateTimeResult result, ref DateTimeFormatInfo dtfi, DateTimeStyles styles) inline static private
Definition at line 330 of file DateTimeParse.cs.
        {
            dtok.dtt = DateTimeParse.DTT.Unk;
            TokenType tokenType;
            int num;
            str.GetRegularToken(out tokenType, out num, dtfi);
            switch (tokenType)
            {
            case TokenType.NumberToken:
            case TokenType.YearNumberToken:
                if (raw.numCount == 3 || num == -1)
                {
                    result.SetBadDateTimeFailure();
                    return false;
                }
                if (dps == DateTimeParse.DS.T_NNt && str.Index < str.Length - 1 && *str.Value[str.Index] == 46)
                {
                    DateTimeParse.ParseFraction(ref str, out raw.fraction);
                }
                if ((dps == DateTimeParse.DS.T_NNt || dps == DateTimeParse.DS.T_Nt) && str.Index < str.Length - 1 && !DateTimeParse.HandleTimeZone(ref str, ref result))
                {
                    return false;
                }
                dtok.num = num;
                if (tokenType != TokenType.YearNumberToken)
                {
                    int num2;
                    char c;
                    TokenType tokenType3;
                    TokenType tokenType2 = (tokenType3 = str.GetSeparatorToken(dtfi, out num2, out c));
                    if (tokenType3 > TokenType.SEP_YearSuff)
                    {
                        if (tokenType3 <= TokenType.SEP_HourSuff)
{
                            if (tokenType3 == TokenType.SEP_MonthSuff || tokenType3 == TokenType.SEP_DaySuff)
{
                                dtok.dtt = DateTimeParse.DTT.NumDatesuff;
                                dtok.suffix = tokenType2;
                                break;
                            }
                            if (tokenType3 != TokenType.SEP_HourSuff)
{
                                goto IL_059F;
                            }
                        }
                        else if (tokenType3 <= TokenType.SEP_SecondSuff)
{
                            if (tokenType3 != TokenType.SEP_MinuteSuff && tokenType3 != TokenType.SEP_SecondSuff)
{
                                goto IL_059F;
                            }
                        }
                        else
{
                            if (tokenType3 == TokenType.SEP_LocalTimeMark)
{
                                dtok.dtt = DateTimeParse.DTT.NumLocalTimeMark;
                                raw.AddNumber(dtok.num);
                                break;
                            }
                            if (tokenType3 != TokenType.SEP_DateOrOffset)
{
                                goto IL_059F;
                            }
                            if (DateTimeParse.dateParsingStates[(int)dps][4] == DateTimeParse.DS.ERROR && DateTimeParse.dateParsingStates[(int)dps][3] > DateTimeParse.DS.ERROR)
{
                                str.Index = num2;
                                str.m_current = c;
                                dtok.dtt = DateTimeParse.DTT.NumSpace;
                            }
                            else
{
                                dtok.dtt = DateTimeParse.DTT.NumDatesep;
                            }
                            raw.AddNumber(dtok.num);
                            break;
                        }
                        dtok.dtt = DateTimeParse.DTT.NumTimesuff;
                        dtok.suffix = tokenType2;
                        break;
                    }
                    if (tokenType3 <= TokenType.SEP_Am)
                    {
                        if (tokenType3 == TokenType.SEP_End)
{
                            dtok.dtt = DateTimeParse.DTT.NumEnd;
                            raw.AddNumber(dtok.num);
                            break;
                        }
                        if (tokenType3 == TokenType.SEP_Space)
{
                            dtok.dtt = DateTimeParse.DTT.NumSpace;
                            raw.AddNumber(dtok.num);
                            break;
                        }
                        if (tokenType3 != TokenType.SEP_Am)
{
                            goto IL_059F;
                        }
                    }
                    else if (tokenType3 <= TokenType.SEP_Date)
                    {
                        if (tokenType3 != TokenType.SEP_Pm)
{
                            if (tokenType3 != TokenType.SEP_Date)
{
                                goto IL_059F;
                            }
                            dtok.dtt = DateTimeParse.DTT.NumDatesep;
                            raw.AddNumber(dtok.num);
                            break;
                        }
                    }
                    else if (tokenType3 != TokenType.SEP_Time)
                    {
                        if (tokenType3 != TokenType.SEP_YearSuff)
{
                            goto IL_059F;
                        }
                        try
{
                            dtok.num = dtfi.Calendar.ToFourDigitYear(num);
                        }
                        catch (ArgumentOutOfRangeException)
{
                            result.SetBadDateTimeFailure();
                            return false;
                        }
                        dtok.dtt = DateTimeParse.DTT.NumDatesuff;
                        dtok.suffix = tokenType2;
                        break;
                    }
                    else
                    {
                        if (raw.hasSameDateAndTimeSeparators && (dps == DateTimeParse.DS.D_Y || dps == DateTimeParse.DS.D_YN || dps == DateTimeParse.DS.D_YNd || dps == DateTimeParse.DS.D_YM || dps == DateTimeParse.DS.D_YMd))
{
                            dtok.dtt = DateTimeParse.DTT.NumDatesep;
                            raw.AddNumber(dtok.num);
                            break;
                        }
                        dtok.dtt = DateTimeParse.DTT.NumTimesep;
                        raw.AddNumber(dtok.num);
                        break;
                    }
                    if (raw.timeMark != DateTimeParse.TM.NotSet)
                    {
                        result.SetBadDateTimeFailure();
                        break;
                    }
                    raw.timeMark = ((tokenType2 == TokenType.SEP_Am) ? DateTimeParse.TM.AM : DateTimeParse.TM.PM);
                    dtok.dtt = DateTimeParse.DTT.NumAmpm;
                    if (dps == DateTimeParse.DS.D_NN && !DateTimeParse.ProcessTerminalState(DateTimeParse.DS.DX_NN, ref str, ref result, ref styles, ref raw, dtfi))
                    {
                        return false;
                    }
                    raw.AddNumber(dtok.num);
                    if ((dps == DateTimeParse.DS.T_NNt || dps == DateTimeParse.DS.T_Nt) && !DateTimeParse.HandleTimeZone(ref str, ref result))
                    {
                        return false;
                    }
                    break;
                    IL_059F:
                    result.SetBadDateTimeFailure();
                    return false;
                }
                if (raw.year == -1)
                {
                    raw.year = num;
                    int num2;
                    char c;
                    TokenType tokenType3;
                    TokenType tokenType2 = (tokenType3 = str.GetSeparatorToken(dtfi, out num2, out c));
                    if (tokenType3 <= TokenType.SEP_Time)
                    {
                        if (tokenType3 <= TokenType.SEP_Am)
{
                            if (tokenType3 == TokenType.SEP_End)
{
                                dtok.dtt = DateTimeParse.DTT.YearEnd;
                                return true;
                            }
                            if (tokenType3 == TokenType.SEP_Space)
{
                                dtok.dtt = DateTimeParse.DTT.YearSpace;
                                return true;
                            }
                            if (tokenType3 != TokenType.SEP_Am)
{
                                goto IL_02B4;
                            }
                        }
                        else if (tokenType3 != TokenType.SEP_Pm)
{
                            if (tokenType3 == TokenType.SEP_Date)
{
                                dtok.dtt = DateTimeParse.DTT.YearDateSep;
                                return true;
                            }
                            if (tokenType3 != TokenType.SEP_Time)
{
                                goto IL_02B4;
                            }
                            if (!raw.hasSameDateAndTimeSeparators)
{
                                result.SetBadDateTimeFailure();
                                return false;
                            }
                            dtok.dtt = DateTimeParse.DTT.YearDateSep;
                            return true;
                        }
                        if (raw.timeMark == DateTimeParse.TM.NotSet)
{
                            raw.timeMark = ((tokenType2 == TokenType.SEP_Am) ? DateTimeParse.TM.AM : DateTimeParse.TM.PM);
                            dtok.dtt = DateTimeParse.DTT.YearSpace;
                            return true;
                        }
                        result.SetBadDateTimeFailure();
                        return true;
                    }
                    else
                    {
                        if (tokenType3 > TokenType.SEP_DaySuff)
{
                            if (tokenType3 <= TokenType.SEP_MinuteSuff)
{
                                if (tokenType3 != TokenType.SEP_HourSuff && tokenType3 != TokenType.SEP_MinuteSuff)
{
                                    goto IL_02B4;
                                }
                            }
                            else if (tokenType3 != TokenType.SEP_SecondSuff)
{
                                if (tokenType3 != TokenType.SEP_DateOrOffset)
{
                                    goto IL_02B4;
                                }
                                if (DateTimeParse.dateParsingStates[(int)dps][13] == DateTimeParse.DS.ERROR && DateTimeParse.dateParsingStates[(int)dps][12] > DateTimeParse.DS.ERROR)
{
                                    str.Index = num2;
                                    str.m_current = c;
                                    dtok.dtt = DateTimeParse.DTT.YearSpace;
                                    return true;
                                }
                                dtok.dtt = DateTimeParse.DTT.YearDateSep;
                                return true;
                            }
                            dtok.dtt = DateTimeParse.DTT.NumTimesuff;
                            dtok.suffix = tokenType2;
                            return true;
                        }
                        if (tokenType3 == TokenType.SEP_YearSuff || tokenType3 == TokenType.SEP_MonthSuff || tokenType3 == TokenType.SEP_DaySuff)
{
                            dtok.dtt = DateTimeParse.DTT.NumDatesuff;
                            dtok.suffix = tokenType2;
                            return true;
                        }
                    }
                    IL_02B4:
                    result.SetBadDateTimeFailure();
                    return false;
                }
                result.SetBadDateTimeFailure();
                return false;
            case TokenType.Am:
            case TokenType.Pm:
                if (raw.timeMark != DateTimeParse.TM.NotSet)
                {
                    result.SetBadDateTimeFailure();
                    return false;
                }
                raw.timeMark = (DateTimeParse.TM)num;
                break;
            case TokenType.MonthToken:
            {
                if (raw.month != -1)
                {
                    result.SetBadDateTimeFailure();
                    return false;
                }
                int num2;
                char c;
                TokenType tokenType3;
                TokenType tokenType2 = (tokenType3 = str.GetSeparatorToken(dtfi, out num2, out c));
                if (tokenType3 <= TokenType.SEP_Space)
                {
                    if (tokenType3 == TokenType.SEP_End)
                    {
                        dtok.dtt = DateTimeParse.DTT.MonthEnd;
                        goto IL_07F7;
                    }
                    if (tokenType3 == TokenType.SEP_Space)
                    {
                        dtok.dtt = DateTimeParse.DTT.MonthSpace;
                        goto IL_07F7;
                    }
                }
                else
                {
                    if (tokenType3 == TokenType.SEP_Date)
                    {
                        dtok.dtt = DateTimeParse.DTT.MonthDatesep;
                        goto IL_07F7;
                    }
                    if (tokenType3 != TokenType.SEP_Time)
                    {
                        if (tokenType3 == TokenType.SEP_DateOrOffset)
{
                            if (DateTimeParse.dateParsingStates[(int)dps][8] == DateTimeParse.DS.ERROR && DateTimeParse.dateParsingStates[(int)dps][7] > DateTimeParse.DS.ERROR)
{
                                str.Index = num2;
                                str.m_current = c;
                                dtok.dtt = DateTimeParse.DTT.MonthSpace;
                                goto IL_07F7;
                            }
                            dtok.dtt = DateTimeParse.DTT.MonthDatesep;
                            goto IL_07F7;
                        }
                    }
                    else
                    {
                        if (!raw.hasSameDateAndTimeSeparators)
{
                            result.SetBadDateTimeFailure();
                            return false;
                        }
                        dtok.dtt = DateTimeParse.DTT.MonthDatesep;
                        goto IL_07F7;
                    }
                }
                result.SetBadDateTimeFailure();
                return false;
                IL_07F7:
                raw.month = num;
                break;
            }
            case TokenType.EndOfString:
                dtok.dtt = DateTimeParse.DTT.End;
                break;
            case TokenType.DayOfWeekToken:
                if (raw.dayOfWeek != -1)
                {
                    result.SetBadDateTimeFailure();
                    return false;
                }
                raw.dayOfWeek = num;
                dtok.dtt = DateTimeParse.DTT.DayOfWeek;
                break;
            case TokenType.TimeZoneToken:
                if ((result.flags & ParseFlags.TimeZoneUsed) != (ParseFlags)0)
                {
                    result.SetBadDateTimeFailure();
                    return false;
                }
                dtok.dtt = DateTimeParse.DTT.TimeZone;
                result.flags |= ParseFlags.TimeZoneUsed;
                result.timeZoneOffset = new TimeSpan(0L);
                result.flags |= ParseFlags.TimeZoneUtc;
                break;
            case TokenType.EraToken:
                if (result.era == -1)
                {
                    result.SetBadDateTimeFailure();
                    return false;
                }
                result.era = num;
                dtok.dtt = DateTimeParse.DTT.Era;
                break;
            case TokenType.UnknownToken:
                if (char.IsLetter(str.m_current))
                {
                    result.SetFailure(ParseFailureKind.FormatWithOriginalDateTimeAndParameter, "Format_UnknownDateTimeWord", str.Index);
                    return false;
                }
                if ((str.m_current == '-' || str.m_current == '+') && (result.flags & ParseFlags.TimeZoneUsed) == (ParseFlags)0)
                {
                    int index = str.Index;
                    if (DateTimeParse.ParseTimeZone(ref str, ref result.timeZoneOffset))
                    {
                        result.flags |= ParseFlags.TimeZoneUsed;
                        return true;
                    }
                    str.Index = index;
                }
                if (DateTimeParse.VerifyValidPunctuation(ref str))
                {
                    return true;
                }
                result.SetBadDateTimeFailure();
                return false;
            case TokenType.HebrewNumber:
            {
                int num2;
                char c;
                TokenType tokenType3;
                TokenType tokenType2;
                if (num < 100)
                {
                    dtok.num = num;
                    raw.AddNumber(dtok.num);
                    tokenType2 = (tokenType3 = str.GetSeparatorToken(dtfi, out num2, out c));
                    if (tokenType3 <= TokenType.SEP_Space)
                    {
                        if (tokenType3 == TokenType.SEP_End)
{
                            dtok.dtt = DateTimeParse.DTT.NumEnd;
                            break;
                        }
                        if (tokenType3 != TokenType.SEP_Space)
{
                            goto IL_06F5;
                        }
                    }
                    else if (tokenType3 != TokenType.SEP_Date)
                    {
                        if (tokenType3 != TokenType.SEP_DateOrOffset)
{
                            goto IL_06F5;
                        }
                        if (DateTimeParse.dateParsingStates[(int)dps][4] == DateTimeParse.DS.ERROR && DateTimeParse.dateParsingStates[(int)dps][3] > DateTimeParse.DS.ERROR)
{
                            str.Index = num2;
                            str.m_current = c;
                            dtok.dtt = DateTimeParse.DTT.NumSpace;
                            break;
                        }
                        dtok.dtt = DateTimeParse.DTT.NumDatesep;
                        break;
                    }
                    dtok.dtt = DateTimeParse.DTT.NumDatesep;
                    break;
                    IL_06F5:
                    result.SetBadDateTimeFailure();
                    return false;
                }
                if (raw.year != -1)
                {
                    result.SetBadDateTimeFailure();
                    return false;
                }
                raw.year = num;
                tokenType2 = (tokenType3 = str.GetSeparatorToken(dtfi, out num2, out c));
                if (tokenType3 != TokenType.SEP_End)
                {
                    if (tokenType3 != TokenType.SEP_Space)
                    {
                        if (tokenType3 == TokenType.SEP_DateOrOffset)
{
                            if (DateTimeParse.dateParsingStates[(int)dps][12] > DateTimeParse.DS.ERROR)
{
                                str.Index = num2;
                                str.m_current = c;
                                dtok.dtt = DateTimeParse.DTT.YearSpace;
                                break;
                            }
                        }
                        result.SetBadDateTimeFailure();
                        return false;
                    }
                    dtok.dtt = DateTimeParse.DTT.YearSpace;
                }
                else
                {
                    dtok.dtt = DateTimeParse.DTT.YearEnd;
                }
                break;
            }
            case TokenType.JapaneseEraToken:
                if (GlobalizationMode.Invariant)
                {
                    throw new PlatformNotSupportedException();
                }
                result.calendar = DateTimeParse.GetJapaneseCalendarDefaultInstance();
                dtfi = DateTimeFormatInfo.GetJapaneseCalendarDTFI();
                if (result.era == -1)
                {
                    result.SetBadDateTimeFailure();
                    return false;
                }
                result.era = num;
                dtok.dtt = DateTimeParse.DTT.Era;
                break;
            case TokenType.TEraToken:
                if (GlobalizationMode.Invariant)
                {
                    throw new PlatformNotSupportedException();
                }
                result.calendar = DateTimeParse.GetTaiwanCalendarDefaultInstance();
                dtfi = DateTimeFormatInfo.GetTaiwanCalendarDTFI();
                if (result.era == -1)
                {
                    result.SetBadDateTimeFailure();
                    return false;
                }
                result.era = num;
                dtok.dtt = DateTimeParse.DTT.Era;
                break;
            }
            return true;
        }
References System.DateTimeParse.dateParsingStates, System.DateTimeParse.GetJapaneseCalendarDefaultInstance(), System.DateTimeParse.GetTaiwanCalendarDefaultInstance(), System.DateTimeParse.HandleTimeZone(), System.index, int, System.Globalization.GlobalizationMode.Invariant, System.L, System.DateTimeParse.ParseFraction(), System.DateTimeParse.ParseTimeZone(), System.DateTimeParse.ProcessTerminalState(), and System.DateTimeParse.VerifyValidPunctuation().
Referenced by System.DateTimeParse.TryParse().