Terraria Decompiled: System.DateTimeParse.GetYearMonthDayOrder
GetYearMonthDayOrder()
static bool System.DateTimeParse.GetYearMonthDayOrder (string datePattern, DateTimeFormatInfo dtfi, out int order) inline static private
Definition at line 914 of file DateTimeParse.cs.
        {
            int num = -1;
            int num2 = -1;
            int num3 = -1;
            int num4 = 0;
            bool flag = false;
            int num5 = 0;
            while (num5 < datePattern.Length && num4 < 3)
            {
                char c = datePattern[num5];
                if (c == '\\' || c == '%')
                {
                    num5++;
                }
                else
                {
                    if (c == '\'' || c == '"')
                    {
                        flag = !flag;
                    }
                    if (!flag)
                    {
                        if (c == 'y')
{
                            num = num4++;
                            while (num5 + 1 < datePattern.Length)
{
                                if (datePattern[num5 + 1] != 'y')
{
                                    break;
                                }
                                num5++;
                            }
                        }
                        else if (c == 'M')
{
                            num2 = num4++;
                            while (num5 + 1 < datePattern.Length)
{
                                if (datePattern[num5 + 1] != 'M')
{
                                    break;
                                }
                                num5++;
                            }
                        }
                        else if (c == 'd')
{
                            int num6 = 1;
                            while (num5 + 1 < datePattern.Length && datePattern[num5 + 1] == 'd')
{
                                num6++;
                                num5++;
                            }
                            if (num6 <= 2)
{
                                num3 = num4++;
                            }
                        }
                    }
                }
                num5++;
            }
            if (num == 0 && num2 == 1 && num3 == 2)
            {
                order = 0;
                return true;
            }
            if (num2 == 0 && num3 == 1 && num == 2)
            {
                order = 1;
                return true;
            }
            if (num3 == 0 && num2 == 1 && num == 2)
            {
                order = 2;
                return true;
            }
            if (num == 0 && num3 == 1 && num2 == 2)
            {
                order = 3;
                return true;
            }
            order = -1;
            return false;
        }
Referenced by System.DateTimeParse.GetDateOfNNDS(), System.DateTimeParse.GetDayOfMNN(), System.DateTimeParse.GetDayOfNNN(), System.DateTimeParse.GetDayOfNNY(), and System.DateTimeParse.GetDayOfYNN().