Terraria Decompiled: System.DateTimeParse.ParseTimeZoneOffset
ParseTimeZoneOffset()
static bool System.DateTimeParse.ParseTimeZoneOffset (ref __DTString str, int len, ref TimeSpan result) inline static private
Definition at line 2507 of file DateTimeParse.cs.
        {
            bool flag = true;
            int num = 0;
            int num2;
            if (len - 1 <= 1)
            {
                if (!DateTimeParse.ParseSign(ref str, ref flag))
                {
                    return false;
                }
                if (!DateTimeParse.ParseDigits(ref str, len, out num2))
                {
                    return false;
                }
            }
            else
            {
                if (!DateTimeParse.ParseSign(ref str, ref flag))
                {
                    return false;
                }
                if (!DateTimeParse.ParseDigits(ref str, 1, out num2))
                {
                    return false;
                }
                if (str.Match(":"))
                {
                    if (!DateTimeParse.ParseDigits(ref str, 2, out num))
                    {
                        return false;
                    }
                }
                else
                {
                    str.Index--;
                    if (!DateTimeParse.ParseDigits(ref str, 2, out num))
                    {
                        return false;
                    }
                }
            }
            if (num < 0 || num >= 60)
            {
                return false;
            }
            result = new TimeSpan(num2, num, 0);
            if (!flag)
            {
                result = result.Negate();
            }
            return true;
        }
References System.DateTimeParse.ParseDigits(), and System.DateTimeParse.ParseSign().
Referenced by System.DateTimeParse.ParseByFormat().