Terraria Decompiled: System.DateTimeParse.ExpandPredefinedFormat
ExpandPredefinedFormat()
static unsafe string System.DateTimeParse.ExpandPredefinedFormat (ReadOnlySpan< char > format, ref DateTimeFormatInfo dtfi, ref ParsingInfo parseInfo, ref DateTimeResult result) inline static private
Definition at line 2877 of file DateTimeParse.cs.
        {
            char c = (char)(*format[0]);
            if (c <= 'R')
            {
                if (c != 'O')
                {
                    if (c != 'R')
                    {
                        goto IL_0153;
                    }
                    goto IL_0067;
                }
            }
            else if (c != 'U')
            {
                switch (c)
                {
                case 'o':
                    break;
                case 'p':
                case 'q':
                case 't':
                    goto IL_0153;
                case 'r':
                    goto IL_0067;
                case 's':
                    dtfi = DateTimeFormatInfo.InvariantInfo;
                    parseInfo.calendar = GregorianCalendar.GetDefaultInstance();
                    goto IL_0153;
                case 'u':
                    parseInfo.calendar = GregorianCalendar.GetDefaultInstance();
                    dtfi = DateTimeFormatInfo.InvariantInfo;
                    if ((result.flags & ParseFlags.CaptureOffset) != (ParseFlags)0)
                    {
                        result.flags |= ParseFlags.UtcSortPattern;
                        goto IL_0153;
                    }
                    goto IL_0153;
                default:
                    goto IL_0153;
                }
            }
            else
            {
                parseInfo.calendar = GregorianCalendar.GetDefaultInstance();
                result.flags |= ParseFlags.TimeZoneUsed;
                result.timeZoneOffset = new TimeSpan(0L);
                result.flags |= ParseFlags.TimeZoneUtc;
                if (dtfi.Calendar.GetType() != typeof(GregorianCalendar))
                {
                    dtfi = (DateTimeFormatInfo)dtfi.Clone();
                    dtfi.Calendar = GregorianCalendar.GetDefaultInstance();
                    goto IL_0153;
                }
                goto IL_0153;
            }
            parseInfo.calendar = GregorianCalendar.GetDefaultInstance();
            dtfi = DateTimeFormatInfo.InvariantInfo;
            goto IL_0153;
            IL_0067:
            parseInfo.calendar = GregorianCalendar.GetDefaultInstance();
            dtfi = DateTimeFormatInfo.InvariantInfo;
            if ((result.flags & ParseFlags.CaptureOffset) != (ParseFlags)0)
            {
                result.flags |= ParseFlags.Rfc1123Pattern;
            }
            IL_0153:
            return DateTimeFormat.GetRealFormat(format, dtfi);
        }
References System.format, System.Globalization.GregorianCalendar.GetDefaultInstance(), System.DateTimeFormat.GetRealFormat(), System.Globalization.DateTimeFormatInfo.InvariantInfo, and System.L.
Referenced by System.DateTimeParse.DoStrictParse().