Terraria Decompiled: System.DateTimeParse.GetDateOfNNDS
GetDateOfNNDS()
static bool System.DateTimeParse.GetDateOfNNDS (ref DateTimeResult result, ref DateTimeRawInfo raw, DateTimeFormatInfo dtfi) inline static private
Definition at line 1674 of file DateTimeParse.cs.
        {
            if ((result.flags & ParseFlags.HaveYear) != (ParseFlags)0)
            {
                if ((result.flags & ParseFlags.HaveMonth) == (ParseFlags)0 && (result.flags & ParseFlags.HaveDay) == (ParseFlags)0 && DateTimeParse.TryAdjustYear(ref result, raw.year, out result.Year) && DateTimeParse.SetDateYMD(ref result, result.Year, raw.GetNumber(0), raw.GetNumber(1)))
                {
                    return true;
                }
            }
            else if ((result.flags & ParseFlags.HaveMonth) != (ParseFlags)0 && (result.flags & ParseFlags.HaveYear) == (ParseFlags)0 && (result.flags & ParseFlags.HaveDay) == (ParseFlags)0)
            {
                int num;
                if (!DateTimeParse.GetYearMonthDayOrder(dtfi.ShortDatePattern, dtfi, out num))
                {
                    result.SetFailure(ParseFailureKind.FormatWithParameter, "Could not determine the order of year, month, and date from '{0}'.", dtfi.ShortDatePattern);
                    return false;
                }
                int num2;
                if (num == 0)
                {
                    if (DateTimeParse.TryAdjustYear(ref result, raw.GetNumber(0), out num2) && DateTimeParse.SetDateYMD(ref result, num2, result.Month, raw.GetNumber(1)))
                    {
                        return true;
                    }
                }
                else if (DateTimeParse.TryAdjustYear(ref result, raw.GetNumber(1), out num2) && DateTimeParse.SetDateYMD(ref result, num2, result.Month, raw.GetNumber(0)))
                {
                    return true;
                }
            }
            result.SetBadDateTimeFailure();
            return false;
        }
References System.DateTimeParse.GetYearMonthDayOrder(), System.DateTimeParse.SetDateYMD(), System.Globalization.DateTimeFormatInfo.ShortDatePattern, and System.DateTimeParse.TryAdjustYear().
Referenced by System.DateTimeParse.ProcessTerminalState().