Terraria Decompiled: System.DateTimeParse.ParseExact
ParseExact() [1/2]
static DateTime System.DateTimeParse.ParseExact (ReadOnlySpan< char > s, ReadOnlySpan< char > format, DateTimeFormatInfo dtfi, DateTimeStyles style) inline static package
Definition at line 14 of file DateTimeParse.cs.
        {
            DateTimeResult dateTimeResult = default(DateTimeResult);
            dateTimeResult.Init(s);
            if (DateTimeParse.TryParseExact(s, format, dtfi, style, ref dateTimeResult))
            {
                return dateTimeResult.parsedDate;
            }
            throw DateTimeParse.GetDateTimeParseException(ref dateTimeResult);
        }
References System.format, System.DateTimeParse.GetDateTimeParseException(), System.DateTimeResult.Init(), System.DateTimeResult.parsedDate, System.s, and System.DateTimeParse.TryParseExact().
Referenced by System.DateTimeOffset.ParseExact(), System.DateTime.ParseExact(), System.DateTimeOffset.ParseExact(), System.DateTime.ParseExact(), and System.DateTime.ParseExact().