Terraria Decompiled: System.DateTimeParse.ProcessHebrewTerminalState
ProcessHebrewTerminalState()
static bool System.DateTimeParse.ProcessHebrewTerminalState (DateTimeParse::DS dps, ref __DTString str, ref DateTimeResult result, ref DateTimeStyles styles, ref DateTimeRawInfo raw, DateTimeFormatInfo dtfi) inline static package
Definition at line 1785 of file DateTimeParse.cs.
        {
            switch (dps)
            {
            case DateTimeParse.DS.DX_MN:
            case DateTimeParse.DS.DX_NM:
                DateTimeParse.GetDefaultYear(ref result, ref styles);
                if (!dtfi.YearMonthAdjustment(ref result.Year, ref raw.month, true))
                {
                    result.SetFailure(ParseFailureKind.FormatBadDateTimeCalendar, "The DateTime represented by the string is not supported in calendar {0}.");
                    return false;
                }
                if (!GlobalizationMode.Invariant && !DateTimeParse.GetHebrewDayOfNM(ref result, ref raw, dtfi))
                {
                    return false;
                }
                goto IL_01BC;
            case DateTimeParse.DS.DX_MNN:
                raw.year = raw.GetNumber(1);
                if (!dtfi.YearMonthAdjustment(ref raw.year, ref raw.month, true))
                {
                    result.SetFailure(ParseFailureKind.FormatBadDateTimeCalendar, "The DateTime represented by the string is not supported in calendar {0}.");
                    return false;
                }
                if (!DateTimeParse.GetDayOfMNN(ref result, ref raw, dtfi))
                {
                    return false;
                }
                goto IL_01BC;
            case DateTimeParse.DS.DX_YMN:
                if (!dtfi.YearMonthAdjustment(ref raw.year, ref raw.month, true))
                {
                    result.SetFailure(ParseFailureKind.FormatBadDateTimeCalendar, "The DateTime represented by the string is not supported in calendar {0}.");
                    return false;
                }
                if (!DateTimeParse.GetDayOfYMN(ref result, ref raw))
                {
                    return false;
                }
                goto IL_01BC;
            case DateTimeParse.DS.DX_YM:
                if (!dtfi.YearMonthAdjustment(ref raw.year, ref raw.month, true))
                {
                    result.SetFailure(ParseFailureKind.FormatBadDateTimeCalendar, "The DateTime represented by the string is not supported in calendar {0}.");
                    return false;
                }
                if (!DateTimeParse.GetDayOfYM(ref result, ref raw))
                {
                    return false;
                }
                goto IL_01BC;
            case DateTimeParse.DS.TX_N:
                if (!DateTimeParse.GetTimeOfN(ref result, ref raw))
                {
                    return false;
                }
                goto IL_01BC;
            case DateTimeParse.DS.TX_NN:
                if (!DateTimeParse.GetTimeOfNN(ref result, ref raw))
                {
                    return false;
                }
                goto IL_01BC;
            case DateTimeParse.DS.TX_NNN:
                if (!DateTimeParse.GetTimeOfNNN(ref result, ref raw))
                {
                    return false;
                }
                goto IL_01BC;
            case DateTimeParse.DS.DX_NNY:
                if (raw.year < 1000)
                {
                    raw.year += 5000;
                }
                if (!DateTimeParse.GetDayOfNNY(ref result, ref raw, dtfi))
                {
                    return false;
                }
                if (!dtfi.YearMonthAdjustment(ref result.Year, ref raw.month, true))
                {
                    result.SetFailure(ParseFailureKind.FormatBadDateTimeCalendar, "The DateTime represented by the string is not supported in calendar {0}.");
                    return false;
                }
                goto IL_01BC;
            }
            result.SetBadDateTimeFailure();
            return false;
            IL_01BC:
            if (dps > DateTimeParse.DS.ERROR)
            {
                raw.numCount = 0;
            }
            return true;
        }
References System.DateTimeParse.GetDayOfMNN(), System.DateTimeParse.GetDayOfNNY(), System.DateTimeParse.GetDayOfYM(), System.DateTimeParse.GetDayOfYMN(), System.DateTimeParse.GetDefaultYear(), System.DateTimeParse.GetHebrewDayOfNM(), System.DateTimeParse.GetTimeOfN(), System.DateTimeParse.GetTimeOfNN(), System.DateTimeParse.GetTimeOfNNN(), and System.Globalization.GlobalizationMode.Invariant.
Referenced by System.DateTimeParse.TryParse().