Terraria Decompiled: System.DateTimeParse.ParseTimeZone
ParseTimeZone()
static bool System.DateTimeParse.ParseTimeZone (ref __DTString str, ref TimeSpan result) inline static private
Definition at line 237 of file DateTimeParse.cs.
        {
            int num = 0;
            DTSubString dtsubString = str.GetSubString();
            if (dtsubString.length != 1)
            {
                return false;
            }
            char c = dtsubString[0];
            if (c != '+' && c != '-')
            {
                return false;
            }
            str.ConsumeSubString(dtsubString);
            dtsubString = str.GetSubString();
            if (dtsubString.type != DTSubStringType.Number)
            {
                return false;
            }
            int value = dtsubString.value;
            int length = dtsubString.length;
            int num2;
            if (length == 1 || length == 2)
            {
                num2 = value;
                str.ConsumeSubString(dtsubString);
                dtsubString = str.GetSubString();
                if (dtsubString.length == 1 && dtsubString[0] == ':')
                {
                    str.ConsumeSubString(dtsubString);
                    dtsubString = str.GetSubString();
                    if (dtsubString.type != DTSubStringType.Number || dtsubString.length < 1 || dtsubString.length > 2)
                    {
                        return false;
                    }
                    num = dtsubString.value;
                    str.ConsumeSubString(dtsubString);
                }
            }
            else
            {
                if (length != 3 && length != 4)
                {
                    return false;
                }
                num2 = value / 100;
                num = value % 100;
                str.ConsumeSubString(dtsubString);
            }
            if (num < 0 || num >= 60)
            {
                return false;
            }
            result = new TimeSpan(num2, num, 0);
            if (c == '-')
            {
                result = result.Negate();
            }
            return true;
        }
References System.DTSubString.length, System.length, System.DTSubString.type, System.DTSubString.value, and System.value.
Referenced by System.DateTimeParse.HandleTimeZone(), System.DateTimeParse.Lex(), and System.DateTimeParse.ParseISO8601().