Terraria Decompiled: System.DateTimeParse.Parse
Parse() [1/2]
static DateTime System.DateTimeParse.Parse (ReadOnlySpan< char > s, DateTimeFormatInfo dtfi, DateTimeStyles styles) inline static package
Definition at line 1953 of file DateTimeParse.cs.
        {
            DateTimeResult dateTimeResult = default(DateTimeResult);
            dateTimeResult.Init(s);
            if (DateTimeParse.TryParse(s, dtfi, styles, ref dateTimeResult))
            {
                return dateTimeResult.parsedDate;
            }
            throw DateTimeParse.GetDateTimeParseException(ref dateTimeResult);
        }
References System.DateTimeParse.GetDateTimeParseException(), System.DateTimeResult.Init(), System.DateTimeResult.parsedDate, System.s, and System.DateTimeParse.TryParse().
Referenced by System.DateTimeOffset.Parse(), System.DateTime.Parse(), System.DateTimeOffset.Parse(), System.DateTimeOffset.Parse(), System.DateTime.Parse(), System.DateTime.Parse(), and System.DateTime.Parse().