Terraria Decompiled: System.DateTimeParse.ProcessTerminalState
ProcessTerminalState()
static bool System.DateTimeParse.ProcessTerminalState (DateTimeParse::DS dps, ref __DTString str, ref DateTimeResult result, ref DateTimeStyles styles, ref DateTimeRawInfo raw, DateTimeFormatInfo dtfi) inline static package
Definition at line 1881 of file DateTimeParse.cs.
        {
            bool flag = true;
            switch (dps)
            {
            case DateTimeParse.DS.DX_NN:
                flag = DateTimeParse.GetDayOfNN(ref result, ref styles, ref raw, dtfi);
                break;
            case DateTimeParse.DS.DX_NNN:
                flag = DateTimeParse.GetDayOfNNN(ref result, ref raw, dtfi);
                break;
            case DateTimeParse.DS.DX_MN:
                flag = DateTimeParse.GetDayOfMN(ref result, ref styles, ref raw, dtfi);
                break;
            case DateTimeParse.DS.DX_NM:
                flag = DateTimeParse.GetDayOfNM(ref result, ref styles, ref raw, dtfi);
                break;
            case DateTimeParse.DS.DX_MNN:
                flag = DateTimeParse.GetDayOfMNN(ref result, ref raw, dtfi);
                break;
            case DateTimeParse.DS.DX_DS:
                flag = true;
                break;
            case DateTimeParse.DS.DX_DSN:
                flag = DateTimeParse.GetDateOfDSN(ref result, ref raw);
                break;
            case DateTimeParse.DS.DX_NDS:
                flag = DateTimeParse.GetDateOfNDS(ref result, ref raw);
                break;
            case DateTimeParse.DS.DX_NNDS:
                flag = DateTimeParse.GetDateOfNNDS(ref result, ref raw, dtfi);
                break;
            case DateTimeParse.DS.DX_YNN:
                flag = DateTimeParse.GetDayOfYNN(ref result, ref raw, dtfi);
                break;
            case DateTimeParse.DS.DX_YMN:
                flag = DateTimeParse.GetDayOfYMN(ref result, ref raw);
                break;
            case DateTimeParse.DS.DX_YN:
                flag = DateTimeParse.GetDayOfYN(ref result, ref raw);
                break;
            case DateTimeParse.DS.DX_YM:
                flag = DateTimeParse.GetDayOfYM(ref result, ref raw);
                break;
            case DateTimeParse.DS.TX_N:
                flag = DateTimeParse.GetTimeOfN(ref result, ref raw);
                break;
            case DateTimeParse.DS.TX_NN:
                flag = DateTimeParse.GetTimeOfNN(ref result, ref raw);
                break;
            case DateTimeParse.DS.TX_NNN:
                flag = DateTimeParse.GetTimeOfNNN(ref result, ref raw);
                break;
            case DateTimeParse.DS.TX_TS:
                flag = true;
                break;
            case DateTimeParse.DS.DX_NNY:
                flag = DateTimeParse.GetDayOfNNY(ref result, ref raw, dtfi);
                break;
            }
            if (!flag)
            {
                return false;
            }
            if (dps > DateTimeParse.DS.ERROR)
            {
                raw.numCount = 0;
            }
            return true;
        }
References System.DateTimeParse.GetDateOfDSN(), System.DateTimeParse.GetDateOfNDS(), System.DateTimeParse.GetDateOfNNDS(), System.DateTimeParse.GetDayOfMN(), System.DateTimeParse.GetDayOfMNN(), System.DateTimeParse.GetDayOfNM(), System.DateTimeParse.GetDayOfNN(), System.DateTimeParse.GetDayOfNNN(), System.DateTimeParse.GetDayOfNNY(), System.DateTimeParse.GetDayOfYM(), System.DateTimeParse.GetDayOfYMN(), System.DateTimeParse.GetDayOfYN(), System.DateTimeParse.GetDayOfYNN(), System.DateTimeParse.GetTimeOfN(), System.DateTimeParse.GetTimeOfNN(), and System.DateTimeParse.GetTimeOfNNN().
Referenced by System.DateTimeParse.Lex(), and System.DateTimeParse.TryParse().