Terraria Decompiled: System.DateTimeParse.MatchEraName
MatchEraName()
static bool System.DateTimeParse.MatchEraName (ref __DTString str, DateTimeFormatInfo dtfi, ref int result) inline static private
Definition at line 2692 of file DateTimeParse.cs.
        {
            if (str.GetNext())
            {
                int[] eras = dtfi.Calendar.Eras;
                if (eras != null)
                {
                    for (int i = 0; i < eras.Length; i++)
                    {
                        string text = dtfi.GetEraName(eras[i]);
                        if (str.MatchSpecifiedWord(text))
{
                            str.Index += text.Length - 1;
                            result = eras[i];
                            return true;
                        }
                        text = dtfi.GetAbbreviatedEraName(eras[i]);
                        if (str.MatchSpecifiedWord(text))
{
                            str.Index += text.Length - 1;
                            result = eras[i];
                            return true;
                        }
                    }
                }
            }
            return false;
        }
References System.Globalization.DateTimeFormatInfo.Calendar, System.Globalization.Calendar.Eras, System.Globalization.DateTimeFormatInfo.GetAbbreviatedEraName(), System.Globalization.DateTimeFormatInfo.GetEraName(), and System.text.
Referenced by System.DateTimeParse.ParseByFormat().