Terraria Decompiled: System.DateTimeParse.GetDayOfYNN
GetDayOfYNN()
static bool System.DateTimeParse.GetDayOfYNN (ref DateTimeResult result, ref DateTimeRawInfo raw, DateTimeFormatInfo dtfi) inline static private
Definition at line 1437 of file DateTimeParse.cs.
        {
            if ((result.flags & ParseFlags.HaveDate) != (ParseFlags)0)
            {
                result.SetBadDateTimeFailure();
                return false;
            }
            int number = raw.GetNumber(0);
            int number2 = raw.GetNumber(1);
            int num;
            if (DateTimeParse.GetYearMonthDayOrder(dtfi.ShortDatePattern, dtfi, out num) && num == 3)
            {
                if (DateTimeParse.SetDateYMD(ref result, raw.year, number2, number))
                {
                    result.flags |= ParseFlags.HaveDate;
                    return true;
                }
            }
            else if (DateTimeParse.SetDateYMD(ref result, raw.year, number, number2))
            {
                result.flags |= ParseFlags.HaveDate;
                return true;
            }
            result.SetBadDateTimeFailure();
            return false;
        }
References System.DateTimeParse.GetYearMonthDayOrder(), System.DateTimeParse.SetDateYMD(), and System.Globalization.DateTimeFormatInfo.ShortDatePattern.
Referenced by System.DateTimeParse.ProcessTerminalState().