Terraria Decompiled: System.DateTimeParse.ParseISO8601
ParseISO8601()
static bool System.DateTimeParse.ParseISO8601 (ref DateTimeRawInfo raw, ref __DTString str, DateTimeStyles styles, ref DateTimeResult result) inline static private
Definition at line 2307 of file DateTimeParse.cs.
        {
            if (raw.year >= 0 && raw.GetNumber(0) >= 0)
            {
                raw.GetNumber(1);
            }
            str.Index--;
            int num = 0;
            double num2 = 0.0;
            str.SkipWhiteSpaces();
            int num3;
            if (!DateTimeParse.ParseDigits(ref str, 2, out num3))
            {
                result.SetBadDateTimeFailure();
                return false;
            }
            str.SkipWhiteSpaces();
            if (!str.Match(':'))
            {
                result.SetBadDateTimeFailure();
                return false;
            }
            str.SkipWhiteSpaces();
            int num4;
            if (!DateTimeParse.ParseDigits(ref str, 2, out num4))
            {
                result.SetBadDateTimeFailure();
                return false;
            }
            str.SkipWhiteSpaces();
            if (str.Match(':'))
            {
                str.SkipWhiteSpaces();
                if (!DateTimeParse.ParseDigits(ref str, 2, out num))
                {
                    result.SetBadDateTimeFailure();
                    return false;
                }
                if (str.Match('.'))
                {
                    if (!DateTimeParse.ParseFraction(ref str, out num2))
                    {
                        result.SetBadDateTimeFailure();
                        return false;
                    }
                    str.Index--;
                }
                str.SkipWhiteSpaces();
            }
            if (str.GetNext())
            {
                char @char = str.GetChar();
                if (@char == '+' || @char == '-')
                {
                    result.flags |= ParseFlags.TimeZoneUsed;
                    if (!DateTimeParse.ParseTimeZone(ref str, ref result.timeZoneOffset))
                    {
                        result.SetBadDateTimeFailure();
                        return false;
                    }
                }
                else if (@char == 'Z' || @char == 'z')
                {
                    result.flags |= ParseFlags.TimeZoneUsed;
                    result.timeZoneOffset = TimeSpan.Zero;
                    result.flags |= ParseFlags.TimeZoneUtc;
                }
                else
                {
                    str.Index--;
                }
                str.SkipWhiteSpaces();
                if (str.Match('#'))
                {
                    if (!DateTimeParse.VerifyValidPunctuation(ref str))
                    {
                        result.SetBadDateTimeFailure();
                        return false;
                    }
                    str.SkipWhiteSpaces();
                }
                if (str.Match('\0') && !DateTimeParse.VerifyValidPunctuation(ref str))
                {
                    result.SetBadDateTimeFailure();
                    return false;
                }
                if (str.GetNext())
                {
                    result.SetBadDateTimeFailure();
                    return false;
                }
            }
            DateTime dateTime;
            if (!GregorianCalendar.GetDefaultInstance().TryToDateTime(raw.year, raw.GetNumber(0), raw.GetNumber(1), num3, num4, num, 0, result.era, out dateTime))
            {
                result.SetFailure(ParseFailureKind.FormatBadDateTimeCalendar, "The DateTime represented by the string is not supported in calendar {0}.");
                return false;
            }
            dateTime = dateTime.AddTicks((long)Math.Round(num2 * 10000000.0));
            result.parsedDate = dateTime;
            return DateTimeParse.DetermineTimeZoneAdjustments(ref str, ref result, styles, false);
        }
References System.DateTime.AddTicks(), System.DateTimeParse.DetermineTimeZoneAdjustments(), System.Globalization.GregorianCalendar.GetDefaultInstance(), System.DateTimeParse.ParseDigits(), System.DateTimeParse.ParseFraction(), System.DateTimeParse.ParseTimeZone(), System.Math.Round(), System.Globalization.Calendar.TryToDateTime(), System.DateTimeParse.VerifyValidPunctuation(), and System.TimeSpan.Zero.
Referenced by System.DateTimeParse.TryParse().