Terraria Decompiled: System.DateTimeParse.ParseByFormat
ParseByFormat()
static unsafe bool System.DateTimeParse.ParseByFormat (ref __DTString str, ref __DTString format, ref ParsingInfo parseInfo, DateTimeFormatInfo dtfi, ref DateTimeResult result) inline static private
Definition at line 2965 of file DateTimeParse.cs.
        {
            int num = 0;
            int num2 = 0;
            int num3 = 0;
            int num4 = 0;
            int num5 = 0;
            int num6 = 0;
            int num7 = 0;
            int num8 = 0;
            double num9 = 0.0;
            DateTimeParse.TM tm = DateTimeParse.TM.AM;
            char @char = format.GetChar();
            if (@char <= 'K')
            {
                if (@char <= '.')
                {
                    if (@char <= '%')
                    {
                        if (@char != '"')
{
                            if (@char != '%')
{
                                goto IL_093B;
                            }
                            if (format.Index >= format.Value.Length - 1 || *format.Value[format.Index + 1] == 37)
{
                                result.SetBadFormatSpecifierFailure(format.Value);
                                return false;
                            }
                            return true;
                        }
                    }
                    else if (@char != '\'')
                    {
                        if (@char != '.')
{
                            goto IL_093B;
                        }
                        if (str.Match(@char))
{
                            return true;
                        }
                        if (format.GetNext() && format.Match('F'))
{
                            format.GetRepeatCount();
                            return true;
                        }
                        result.SetBadDateTimeFailure();
                        return false;
                    }
                    StringBuilder stringBuilder = StringBuilderCache.Acquire(16);
                    if (!DateTimeParse.TryParseQuoteString(format.Value, format.Index, stringBuilder, out num))
                    {
                        result.SetFailure(ParseFailureKind.FormatWithParameter, "Cannot find a matching quote character for the character '{0}'.", @char);
                        StringBuilderCache.Release(stringBuilder);
                        return false;
                    }
                    format.Index += num - 1;
                    string stringAndRelease = StringBuilderCache.GetStringAndRelease(stringBuilder);
                    for (int i = 0; i < stringAndRelease.Length; i++)
                    {
                        if (stringAndRelease[i] == ' ' && parseInfo.fAllowInnerWhite)
{
                            str.SkipWhiteSpaces();
                        }
                        else if (!str.Match(stringAndRelease[i]))
{
                            result.SetBadDateTimeFailure();
                            return false;
                        }
                    }
                    if ((result.flags & ParseFlags.CaptureOffset) == (ParseFlags)0)
                    {
                        return true;
                    }
                    if ((result.flags & ParseFlags.Rfc1123Pattern) != (ParseFlags)0 && stringAndRelease == "GMT")
                    {
                        result.flags |= ParseFlags.TimeZoneUsed;
                        result.timeZoneOffset = TimeSpan.Zero;
                        return true;
                    }
                    if ((result.flags & ParseFlags.UtcSortPattern) != (ParseFlags)0 && stringAndRelease == "Z")
                    {
                        result.flags |= ParseFlags.TimeZoneUsed;
                        result.timeZoneOffset = TimeSpan.Zero;
                        return true;
                    }
                    return true;
                }
                else if (@char <= ':')
                {
                    if (@char != '/')
                    {
                        if (@char != ':')
{
                            goto IL_093B;
                        }
                        if (((dtfi.TimeSeparator.Length > 1 && dtfi.TimeSeparator[0] == ':') || !str.Match(':')) && !str.Match(dtfi.TimeSeparator))
{
                            result.SetBadDateTimeFailure();
                            return false;
                        }
                        return true;
                    }
                    else
                    {
                        if (((dtfi.DateSeparator.Length > 1 && dtfi.DateSeparator[0] == '/') || !str.Match('/')) && !str.Match(dtfi.DateSeparator))
{
                            result.SetBadDateTimeFailure();
                            return false;
                        }
                        return true;
                    }
                }
                else if (@char != 'F')
                {
                    if (@char != 'H')
                    {
                        if (@char != 'K')
{
                            goto IL_093B;
                        }
                        if (str.Match('Z'))
{
                            if ((result.flags & ParseFlags.TimeZoneUsed) != (ParseFlags)0 && result.timeZoneOffset != TimeSpan.Zero)
{
                                result.SetFailure(ParseFailureKind.FormatWithParameter, "DateTime pattern '{0}' appears more than once with different values.", 'K');
                                return false;
                            }
                            result.flags |= ParseFlags.TimeZoneUsed;
                            result.timeZoneOffset = new TimeSpan(0L);
                            result.flags |= ParseFlags.TimeZoneUtc;
                            return true;
                        }
                        else
{
                            if (!str.Match('+') && !str.Match('-'))
{
                                return true;
                            }
                            str.Index--;
                            TimeSpan timeSpan = new TimeSpan(0L);
                            if (!DateTimeParse.ParseTimeZoneOffset(ref str, 3, ref timeSpan))
{
                                result.SetBadDateTimeFailure();
                                return false;
                            }
                            if ((result.flags & ParseFlags.TimeZoneUsed) != (ParseFlags)0 && timeSpan != result.timeZoneOffset)
{
                                result.SetFailure(ParseFailureKind.FormatWithParameter, "DateTime pattern '{0}' appears more than once with different values.", 'K');
                                return false;
                            }
                            result.timeZoneOffset = timeSpan;
                            result.flags |= ParseFlags.TimeZoneUsed;
                            return true;
                        }
                    }
                    else
                    {
                        num = format.GetRepeatCount();
                        if (!DateTimeParse.ParseDigits(ref str, (num < 2) ? 1 : 2, out num6))
{
                            result.SetBadDateTimeFailure();
                            return false;
                        }
                        if (!DateTimeParse.CheckNewValue(ref result.Hour, num6, @char, ref result))
{
                            return false;
                        }
                        return true;
                    }
                }
            }
            else if (@char <= 'h')
            {
                if (@char <= 'Z')
                {
                    if (@char != 'M')
                    {
                        if (@char != 'Z')
{
                            goto IL_093B;
                        }
                        if ((result.flags & ParseFlags.TimeZoneUsed) != (ParseFlags)0 && result.timeZoneOffset != TimeSpan.Zero)
{
                            result.SetFailure(ParseFailureKind.FormatWithParameter, "DateTime pattern '{0}' appears more than once with different values.", 'Z');
                            return false;
                        }
                        result.flags |= ParseFlags.TimeZoneUsed;
                        result.timeZoneOffset = new TimeSpan(0L);
                        result.flags |= ParseFlags.TimeZoneUtc;
                        str.Index++;
                        if (!DateTimeParse.GetTimeZoneName(ref str))
{
                            result.SetBadDateTimeFailure();
                            return false;
                        }
                        str.Index--;
                        return true;
                    }
                    else
                    {
                        num = format.GetRepeatCount();
                        if (num <= 2)
{
                            if (!DateTimeParse.ParseDigits(ref str, num, out num3) && (!parseInfo.fCustomNumberParser || !parseInfo.parseNumberDelegate(ref str, num, out num3)))
{
                                result.SetBadDateTimeFailure();
                                return false;
                            }
                        }
                        else
{
                            if (num == 3)
{
                                if (!DateTimeParse.MatchAbbreviatedMonthName(ref str, dtfi, ref num3))
{
                                    result.SetBadDateTimeFailure();
                                    return false;
                                }
                            }
                            else if (!DateTimeParse.MatchMonthName(ref str, dtfi, ref num3))
{
                                result.SetBadDateTimeFailure();
                                return false;
                            }
                            result.flags |= ParseFlags.ParsedMonthName;
                        }
                        if (!DateTimeParse.CheckNewValue(ref result.Month, num3, @char, ref result))
{
                            return false;
                        }
                        return true;
                    }
                }
                else if (@char != '\\')
                {
                    switch (@char)
                    {
                    case 'd':
                        num = format.GetRepeatCount();
                        if (num <= 2)
{
                            if (!DateTimeParse.ParseDigits(ref str, num, out num4) && (!parseInfo.fCustomNumberParser || !parseInfo.parseNumberDelegate(ref str, num, out num4)))
{
                                result.SetBadDateTimeFailure();
                                return false;
                            }
                            if (!DateTimeParse.CheckNewValue(ref result.Day, num4, @char, ref result))
{
                                return false;
                            }
                            return true;
                        }
                        else
{
                            if (num == 3)
{
                                if (!DateTimeParse.MatchAbbreviatedDayName(ref str, dtfi, ref num5))
{
                                    result.SetBadDateTimeFailure();
                                    return false;
                                }
                            }
                            else if (!DateTimeParse.MatchDayName(ref str, dtfi, ref num5))
{
                                result.SetBadDateTimeFailure();
                                return false;
                            }
                            if (!DateTimeParse.CheckNewValue(ref parseInfo.dayOfWeek, num5, @char, ref result))
{
                                return false;
                            }
                            return true;
                        }
                        break;
                    case 'e':
                        goto IL_093B;
                    case 'f':
                        break;
                    case 'g':
                        num = format.GetRepeatCount();
                        if (!DateTimeParse.MatchEraName(ref str, dtfi, ref result.era))
{
                            result.SetBadDateTimeFailure();
                            return false;
                        }
                        return true;
                    case 'h':
                        parseInfo.fUseHour12 = true;
                        num = format.GetRepeatCount();
                        if (!DateTimeParse.ParseDigits(ref str, (num < 2) ? 1 : 2, out num6))
{
                            result.SetBadDateTimeFailure();
                            return false;
                        }
                        if (!DateTimeParse.CheckNewValue(ref result.Hour, num6, @char, ref result))
{
                            return false;
                        }
                        return true;
                    default:
                        goto IL_093B;
                    }
                }
                else
                {
                    if (!format.GetNext())
                    {
                        result.SetBadFormatSpecifierFailure(format.Value);
                        return false;
                    }
                    if (!str.Match(format.GetChar()))
                    {
                        result.SetBadDateTimeFailure();
                        return false;
                    }
                    return true;
                }
            }
            else if (@char <= 's')
            {
                if (@char != 'm')
                {
                    if (@char != 's')
                    {
                        goto IL_093B;
                    }
                    num = format.GetRepeatCount();
                    if (!DateTimeParse.ParseDigits(ref str, (num < 2) ? 1 : 2, out num8))
                    {
                        result.SetBadDateTimeFailure();
                        return false;
                    }
                    if (!DateTimeParse.CheckNewValue(ref result.Second, num8, @char, ref result))
                    {
                        return false;
                    }
                    return true;
                }
                else
                {
                    num = format.GetRepeatCount();
                    if (!DateTimeParse.ParseDigits(ref str, (num < 2) ? 1 : 2, out num7))
                    {
                        result.SetBadDateTimeFailure();
                        return false;
                    }
                    if (!DateTimeParse.CheckNewValue(ref result.Minute, num7, @char, ref result))
                    {
                        return false;
                    }
                    return true;
                }
            }
            else if (@char != 't')
            {
                if (@char != 'y')
                {
                    if (@char != 'z')
                    {
                        goto IL_093B;
                    }
                    num = format.GetRepeatCount();
                    TimeSpan timeSpan2 = new TimeSpan(0L);
                    if (!DateTimeParse.ParseTimeZoneOffset(ref str, num, ref timeSpan2))
                    {
                        result.SetBadDateTimeFailure();
                        return false;
                    }
                    if ((result.flags & ParseFlags.TimeZoneUsed) != (ParseFlags)0 && timeSpan2 != result.timeZoneOffset)
                    {
                        result.SetFailure(ParseFailureKind.FormatWithParameter, "DateTime pattern '{0}' appears more than once with different values.", 'z');
                        return false;
                    }
                    result.timeZoneOffset = timeSpan2;
                    result.flags |= ParseFlags.TimeZoneUsed;
                    return true;
                }
                else
                {
                    num = format.GetRepeatCount();
                    bool flag;
                    if (DateTimeParse.ParseJapaneseEraStart(ref str, dtfi))
                    {
                        num2 = 1;
                        flag = true;
                    }
                    else if (dtfi.HasForceTwoDigitYears)
                    {
                        flag = DateTimeParse.ParseDigits(ref str, 1, 4, out num2);
                    }
                    else
                    {
                        if (num <= 2)
{
                            parseInfo.fUseTwoDigitYear = true;
                        }
                        flag = DateTimeParse.ParseDigits(ref str, num, out num2);
                    }
                    if (!flag && parseInfo.fCustomNumberParser)
                    {
                        flag = parseInfo.parseNumberDelegate(ref str, num, out num2);
                    }
                    if (!flag)
                    {
                        result.SetBadDateTimeFailure();
                        return false;
                    }
                    if (!DateTimeParse.CheckNewValue(ref result.Year, num2, @char, ref result))
                    {
                        return false;
                    }
                    return true;
                }
            }
            else
            {
                num = format.GetRepeatCount();
                if (num == 1)
                {
                    if (!DateTimeParse.MatchAbbreviatedTimeMark(ref str, dtfi, ref tm))
                    {
                        result.SetBadDateTimeFailure();
                        return false;
                    }
                }
                else if (!DateTimeParse.MatchTimeMark(ref str, dtfi, ref tm))
                {
                    result.SetBadDateTimeFailure();
                    return false;
                }
                if (parseInfo.timeMark == DateTimeParse.TM.NotSet)
                {
                    parseInfo.timeMark = tm;
                    return true;
                }
                if (parseInfo.timeMark != tm)
                {
                    result.SetFailure(ParseFailureKind.FormatWithParameter, "DateTime pattern '{0}' appears more than once with different values.", @char);
                    return false;
                }
                return true;
            }
            num = format.GetRepeatCount();
            if (num > 7)
            {
                result.SetBadDateTimeFailure();
                return false;
            }
            if (!DateTimeParse.ParseFractionExact(ref str, num, ref num9) && @char == 'f')
            {
                result.SetBadDateTimeFailure();
                return false;
            }
            if (result.fraction < 0.0)
            {
                result.fraction = num9;
                return true;
            }
            if (num9 != result.fraction)
            {
                result.SetFailure(ParseFailureKind.FormatWithParameter, "DateTime pattern '{0}' appears more than once with different values.", @char);
                return false;
            }
            return true;
            IL_093B:
            if (@char == ' ')
            {
                if (!parseInfo.fAllowInnerWhite && !str.Match(@char))
                {
                    if (parseInfo.fAllowTrailingWhite && format.GetNext() && DateTimeParse.ParseByFormat(ref str, ref format, ref parseInfo, dtfi, ref result))
                    {
                        return true;
                    }
                    result.SetBadDateTimeFailure();
                    return false;
                }
            }
            else if (format.MatchSpecifiedWord("GMT"))
            {
                format.Index += "GMT".Length - 1;
                result.flags |= ParseFlags.TimeZoneUsed;
                result.timeZoneOffset = TimeSpan.Zero;
                if (!str.Match("GMT"))
                {
                    result.SetBadDateTimeFailure();
                    return false;
                }
            }
            else if (!str.Match(@char))
            {
                result.SetBadDateTimeFailure();
                return false;
            }
            return true;
        }
References System.Text.StringBuilderCache.Acquire(), System.DateTimeParse.CheckNewValue(), System.Globalization.DateTimeFormatInfo.DateSeparator, System.format, System.Text.StringBuilderCache.GetStringAndRelease(), System.DateTimeParse.GetTimeZoneName(), System.L, System.DateTimeParse.MatchAbbreviatedDayName(), System.DateTimeParse.MatchAbbreviatedMonthName(), System.DateTimeParse.MatchAbbreviatedTimeMark(), System.DateTimeParse.MatchDayName(), System.DateTimeParse.MatchEraName(), System.DateTimeParse.MatchMonthName(), System.DateTimeParse.MatchTimeMark(), System.DateTimeParse.ParseByFormat(), System.DateTimeParse.ParseDigits(), System.DateTimeParse.ParseFractionExact(), System.DateTimeParse.ParseJapaneseEraStart(), System.DateTimeParse.ParseTimeZoneOffset(), System.Text.StringBuilderCache.Release(), System.DateTimeParse.TryParseQuoteString(), and System.TimeSpan.Zero.
Referenced by System.DateTimeParse.DoStrictParse(), and System.DateTimeParse.ParseByFormat().