Terraria Decompiled: System.DateTimeParse.CheckDefaultDateTime
CheckDefaultDateTime()
static bool System.DateTimeParse.CheckDefaultDateTime (ref DateTimeResult result, ref Calendar cal, DateTimeStyles styles) inline static private
Definition at line 2809 of file DateTimeParse.cs.
        {
            if ((result.flags & ParseFlags.CaptureOffset) != (ParseFlags)0 && (result.Month != -1 || result.Day != -1) && (result.Year == -1 || (result.flags & ParseFlags.YearDefault) != (ParseFlags)0) && (result.flags & ParseFlags.TimeZoneUsed) != (ParseFlags)0)
            {
                result.SetFailure(ParseFailureKind.FormatWithOriginalDateTime, "There must be at least a partial date with a year present in the input.");
                return false;
            }
            if (result.Year == -1 || result.Month == -1 || result.Day == -1)
            {
                DateTime dateTimeNow = DateTimeParse.GetDateTimeNow(ref result, ref styles);
                if (result.Month == -1 && result.Day == -1)
                {
                    if (result.Year == -1)
                    {
                        if ((styles & DateTimeStyles.NoCurrentDateDefault) != DateTimeStyles.None)
{
                            cal = GregorianCalendar.GetDefaultInstance();
                            result.Year = (result.Month = (result.Day = 1));
                        }
                        else
{
                            result.Year = cal.GetYear(dateTimeNow);
                            result.Month = cal.GetMonth(dateTimeNow);
                            result.Day = cal.GetDayOfMonth(dateTimeNow);
                        }
                    }
                    else
                    {
                        result.Month = 1;
                        result.Day = 1;
                    }
                }
                else
                {
                    if (result.Year == -1)
                    {
                        result.Year = cal.GetYear(dateTimeNow);
                    }
                    if (result.Month == -1)
                    {
                        result.Month = 1;
                    }
                    if (result.Day == -1)
                    {
                        result.Day = 1;
                    }
                }
            }
            if (result.Hour == -1)
            {
                result.Hour = 0;
            }
            if (result.Minute == -1)
            {
                result.Minute = 0;
            }
            if (result.Second == -1)
            {
                result.Second = 0;
            }
            if (result.era == -1)
            {
                result.era = 0;
            }
            return true;
        }
References System.DateTimeParse.GetDateTimeNow(), System.Globalization.GregorianCalendar.GetDefaultInstance(), and System.Globalization.Calendar.GetYear().
Referenced by System.DateTimeParse.DoStrictParse(), and System.DateTimeParse.TryParse().