Terraria Decompiled: System.DateTimeParse.GetDayOfMN
GetDayOfMN()
static bool System.DateTimeParse.GetDayOfMN (ref DateTimeResult result, ref DateTimeStyles styles, ref DateTimeRawInfo raw, DateTimeFormatInfo dtfi) inline static private
Definition at line 1266 of file DateTimeParse.cs.
        {
            if ((result.flags & ParseFlags.HaveDate) != (ParseFlags)0)
            {
                result.SetBadDateTimeFailure();
                return false;
            }
            int num;
            if (!DateTimeParse.GetMonthDayOrder(dtfi.MonthDayPattern, dtfi, out num))
            {
                result.SetFailure(ParseFailureKind.FormatWithParameter, "Could not determine the order of year, month, and date from '{0}'.", dtfi.MonthDayPattern);
                return false;
            }
            if (num == 7)
            {
                int num2;
                if (!DateTimeParse.GetYearMonthOrder(dtfi.YearMonthPattern, dtfi, out num2))
                {
                    result.SetFailure(ParseFailureKind.FormatWithParameter, "Could not determine the order of year, month, and date from '{0}'.", dtfi.YearMonthPattern);
                    return false;
                }
                if (num2 == 5)
                {
                    int num3;
                    if (!DateTimeParse.TryAdjustYear(ref result, raw.GetNumber(0), out num3) || !DateTimeParse.SetDateYMD(ref result, num3, raw.month, 1))
                    {
                        result.SetBadDateTimeFailure();
                        return false;
                    }
                    return true;
                }
            }
            DateTimeParse.GetDefaultYear(ref result, ref styles);
            if (!DateTimeParse.SetDateYMD(ref result, result.Year, raw.month, raw.GetNumber(0)))
            {
                result.SetBadDateTimeFailure();
                return false;
            }
            return true;
        }
References System.DateTimeParse.GetDefaultYear(), System.DateTimeParse.GetMonthDayOrder(), System.DateTimeParse.GetYearMonthOrder(), System.Globalization.DateTimeFormatInfo.MonthDayPattern, System.DateTimeParse.SetDateYMD(), and System.DateTimeParse.TryAdjustYear().
Referenced by System.DateTimeParse.ProcessTerminalState().