Terraria Decompiled: System.DateTimeParse.TryParse
TryParse() [3/3]
static unsafe bool System.DateTimeParse.TryParse (ReadOnlySpan< char > s, DateTimeFormatInfo dtfi, DateTimeStyles styles, ref DateTimeResult result) inline static package
Definition at line 2010 of file DateTimeParse.cs.
        {
            if (s.Length == 0)
            {
                result.SetFailure(ParseFailureKind.FormatWithParameter, "String was not recognized as a valid DateTime.");
                return false;
            }
            DateTimeParse.DS ds = DateTimeParse.DS.BEGIN;
            bool flag = false;
            DateTimeToken dateTimeToken = default(DateTimeToken);
            dateTimeToken.suffix = TokenType.SEP_Unk;
            DateTimeRawInfo dateTimeRawInfo = default(DateTimeRawInfo);
            int* ptr = stackalloc int[(UIntPtr)12];
            dateTimeRawInfo.Init(ptr);
            dateTimeRawInfo.hasSameDateAndTimeSeparators = dtfi.DateSeparator.Equals(dtfi.TimeSeparator, StringComparison.Ordinal);
            result.calendar = dtfi.Calendar;
            result.era = 0;
            __DTString _DTString = new __DTString(s, dtfi);
            _DTString.GetNext();
            while (DateTimeParse.Lex(ds, ref _DTString, ref dateTimeToken, ref dateTimeRawInfo, ref result, ref dtfi, styles))
            {
                if (dateTimeToken.dtt != DateTimeParse.DTT.Unk)
                {
                    if (dateTimeToken.suffix != TokenType.SEP_Unk)
                    {
                        if (!DateTimeParse.ProcessDateTimeSuffix(ref result, ref dateTimeRawInfo, ref dateTimeToken))
{
                            result.SetBadDateTimeFailure();
                            return false;
                        }
                        dateTimeToken.suffix = TokenType.SEP_Unk;
                    }
                    if (dateTimeToken.dtt == DateTimeParse.DTT.NumLocalTimeMark)
                    {
                        if (ds == DateTimeParse.DS.D_YNd || ds == DateTimeParse.DS.D_YN)
{
                            return DateTimeParse.ParseISO8601(ref dateTimeRawInfo, ref _DTString, styles, ref result);
                        }
                        result.SetBadDateTimeFailure();
                        return false;
                    }
                    else
                    {
                        if (dateTimeRawInfo.hasSameDateAndTimeSeparators)
{
                            if (dateTimeToken.dtt == DateTimeParse.DTT.YearEnd || dateTimeToken.dtt == DateTimeParse.DTT.YearSpace || dateTimeToken.dtt == DateTimeParse.DTT.YearDateSep)
{
                                if (ds == DateTimeParse.DS.T_Nt)
{
                                    ds = DateTimeParse.DS.D_Nd;
                                }
                                if (ds == DateTimeParse.DS.T_NNt)
{
                                    ds = DateTimeParse.DS.D_NNd;
                                }
                            }
                            bool flag2 = _DTString.AtEnd();
                            if (DateTimeParse.dateParsingStates[(int)ds][(int)dateTimeToken.dtt] == DateTimeParse.DS.ERROR || flag2)
{
                                DateTimeParse.DTT dtt = dateTimeToken.dtt;
                                switch (dtt)
{
                                case DateTimeParse.DTT.NumDatesep:
                                    dateTimeToken.dtt = (flag2 ? DateTimeParse.DTT.NumEnd : DateTimeParse.DTT.NumSpace);
                                    break;
                                case DateTimeParse.DTT.NumTimesep:
                                    dateTimeToken.dtt = (flag2 ? DateTimeParse.DTT.NumEnd : DateTimeParse.DTT.NumSpace);
                                    break;
                                case DateTimeParse.DTT.MonthEnd:
                                case DateTimeParse.DTT.MonthSpace:
                                    break;
                                case DateTimeParse.DTT.MonthDatesep:
                                    dateTimeToken.dtt = (flag2 ? DateTimeParse.DTT.MonthEnd : DateTimeParse.DTT.MonthSpace);
                                    break;
                                default:
                                    if (dtt == DateTimeParse.DTT.YearDateSep)
{
                                        dateTimeToken.dtt = (flag2 ? DateTimeParse.DTT.YearEnd : DateTimeParse.DTT.YearSpace);
                                    }
                                    break;
                                }
                            }
                        }
                        ds = DateTimeParse.dateParsingStates[(int)ds][(int)dateTimeToken.dtt];
                        if (ds == DateTimeParse.DS.ERROR)
{
                            result.SetBadDateTimeFailure();
                            return false;
                        }
                        if (ds > DateTimeParse.DS.ERROR)
{
                            if ((dtfi.FormatFlags & DateTimeFormatFlags.UseHebrewRule) != DateTimeFormatFlags.None)
{
                                if (!GlobalizationMode.Invariant && !DateTimeParse.ProcessHebrewTerminalState(ds, ref _DTString, ref result, ref styles, ref dateTimeRawInfo, dtfi))
{
                                    return false;
                                }
                            }
                            else if (!DateTimeParse.ProcessTerminalState(ds, ref _DTString, ref result, ref styles, ref dateTimeRawInfo, dtfi))
{
                                return false;
                            }
                            flag = true;
                            ds = DateTimeParse.DS.BEGIN;
                        }
                    }
                }
                if (dateTimeToken.dtt == DateTimeParse.DTT.End || dateTimeToken.dtt == DateTimeParse.DTT.NumEnd || dateTimeToken.dtt == DateTimeParse.DTT.MonthEnd)
                {
                    if (!flag)
                    {
                        result.SetBadDateTimeFailure();
                        return false;
                    }
                    DateTimeParse.AdjustTimeMark(dtfi, ref dateTimeRawInfo);
                    if (!DateTimeParse.AdjustHour(ref result.Hour, dateTimeRawInfo.timeMark))
                    {
                        result.SetBadDateTimeFailure();
                        return false;
                    }
                    bool flag3 = result.Year == -1 && result.Month == -1 && result.Day == -1;
                    if (!DateTimeParse.CheckDefaultDateTime(ref result, ref result.calendar, styles))
                    {
                        return false;
                    }
                    DateTime dateTime;
                    if (!result.calendar.TryToDateTime(result.Year, result.Month, result.Day, result.Hour, result.Minute, result.Second, 0, result.era, out dateTime))
                    {
                        result.SetFailure(ParseFailureKind.FormatBadDateTimeCalendar, "The DateTime represented by the string is not supported in calendar {0}.");
                        return false;
                    }
                    if (dateTimeRawInfo.fraction > 0.0)
                    {
                        dateTime = dateTime.AddTicks((long)Math.Round(dateTimeRawInfo.fraction * 10000000.0));
                    }
                    if (dateTimeRawInfo.dayOfWeek != -1 && dateTimeRawInfo.dayOfWeek != (int)result.calendar.GetDayOfWeek(dateTime))
                    {
                        result.SetFailure(ParseFailureKind.FormatWithOriginalDateTime, "String was not recognized as a valid DateTime because the day of week was incorrect.");
                        return false;
                    }
                    result.parsedDate = dateTime;
                    return DateTimeParse.DetermineTimeZoneAdjustments(ref _DTString, ref result, styles, flag3);
                }
            }
            return false;
        }
References System.DateTime.AddTicks(), System.DateTimeParse.AdjustHour(), System.DateTimeParse.AdjustTimeMark(), System.__DTString.AtEnd(), System.Globalization.DateTimeFormatInfo.Calendar, System.DateTimeParse.CheckDefaultDateTime(), System.DateTimeParse.dateParsingStates, System.Globalization.DateTimeFormatInfo.DateSeparator, System.DateTimeParse.DetermineTimeZoneAdjustments(), System.DateTimeToken.dtt, System.__DTString.GetNext(), System.DateTimeRawInfo.hasSameDateAndTimeSeparators, System.DateTimeRawInfo.Init(), int, System.Globalization.GlobalizationMode.Invariant, System.DateTimeParse.Lex(), System.DateTimeParse.ParseISO8601(), System.DateTimeParse.ProcessDateTimeSuffix(), System.DateTimeParse.ProcessHebrewTerminalState(), System.DateTimeParse.ProcessTerminalState(), System.Math.Round(), System.s, and System.DateTimeToken.suffix.