Terraria Decompiled: System.DateTimeParse.GetMonthDayOrder
GetMonthDayOrder()
static bool System.DateTimeParse.GetMonthDayOrder (string pattern, DateTimeFormatInfo dtfi, out int order) inline static private
Definition at line 1064 of file DateTimeParse.cs.
        {
            int num = -1;
            int num2 = -1;
            int num3 = 0;
            bool flag = false;
            int num4 = 0;
            while (num4 < pattern.Length && num3 < 2)
            {
                char c = pattern[num4];
                if (c == '\\' || c == '%')
                {
                    num4++;
                }
                else
                {
                    if (c == '\'' || c == '"')
                    {
                        flag = !flag;
                    }
                    if (!flag)
                    {
                        if (c == 'd')
{
                            int num5 = 1;
                            while (num4 + 1 < pattern.Length && pattern[num4 + 1] == 'd')
{
                                num5++;
                                num4++;
                            }
                            if (num5 <= 2)
{
                                num2 = num3++;
                            }
                        }
                        else if (c == 'M')
{
                            num = num3++;
                            while (num4 + 1 < pattern.Length && pattern[num4 + 1] == 'M')
{
                                num4++;
                            }
                        }
                    }
                }
                num4++;
            }
            if (num == 0 && num2 == 1)
            {
                order = 6;
                return true;
            }
            if (num2 == 0 && num == 1)
            {
                order = 7;
                return true;
            }
            order = -1;
            return false;
        }
Referenced by System.DateTimeParse.GetDayOfMN(), System.DateTimeParse.GetDayOfNM(), System.DateTimeParse.GetDayOfNN(), and System.DateTimeParse.GetHebrewDayOfNM().