Terraria Decompiled: Ionic.BZip2.BZip2OutputStream.Finish
Finish()
void Ionic.BZip2.BZip2OutputStream.Finish () inline private
Definition at line 97 of file BZip2OutputStream.cs.
        {
            try
            {
                int totalBytesWrittenOut = this.bw.TotalBytesWrittenOut;
                this.compressor.CompressAndWrite();
                this.combinedCRC = (this.combinedCRC << 1) | (this.combinedCRC >> 31);
                this.combinedCRC ^= this.compressor.Crc32;
                this.EmitTrailer();
            }
            finally
            {
                this.output = null;
                this.compressor = null;
                this.bw = null;
            }
        }
References Ionic.BZip2.BZip2OutputStream.bw, Ionic.BZip2.BZip2OutputStream.combinedCRC, Ionic.BZip2.BZip2Compressor.CompressAndWrite(), Ionic.BZip2.BZip2OutputStream.compressor, Ionic.BZip2.BZip2Compressor.Crc32, Ionic.BZip2.BZip2OutputStream.EmitTrailer(), and Ionic.BZip2.BitWriter.TotalBytesWrittenOut.
Referenced by Ionic.BZip2.BZip2OutputStream.Close().