Terraria Decompiled: System.Security.Policy.PermissionRequestEvidence.ToString
ToString()
override string System.Security.Policy.PermissionRequestEvidence.ToString () inline
Definition at line 65 of file PermissionRequestEvidence.cs.
        {
            SecurityElement securityElement = new SecurityElement("System.Security.Policy.PermissionRequestEvidence");
            securityElement.AddAttribute("version", "1");
            if (this.requested != null)
            {
                SecurityElement securityElement2 = new SecurityElement("Request");
                securityElement2.AddChild(this.requested.ToXml());
                securityElement.AddChild(securityElement2);
            }
            if (this.optional != null)
            {
                SecurityElement securityElement3 = new SecurityElement("Optional");
                securityElement3.AddChild(this.optional.ToXml());
                securityElement.AddChild(securityElement3);
            }
            if (this.denied != null)
            {
                SecurityElement securityElement4 = new SecurityElement("Denied");
                securityElement4.AddChild(this.denied.ToXml());
                securityElement.AddChild(securityElement4);
            }
            return securityElement.ToString();
        }
References System.Security.SecurityElement.AddAttribute(), System.Security.SecurityElement.AddChild(), System.Security.Policy.PermissionRequestEvidence.denied, System.Security.Policy.PermissionRequestEvidence.optional, System.Security.Policy.PermissionRequestEvidence.requested, System.Security.SecurityElement.ToString(), and System.Security.PermissionSet.ToXml().