Terraria Decompiled: System.Buffers.SequenceReader.TryCopyMultisegment
TryCopyMultisegment()
readonly bool System.Buffers.SequenceReader< T >.TryCopyMultisegment (Span< T > destination) inline package
Definition at line 968 of file SequenceReader.cs.
        {
            if (this.Remaining < (long)destination.Length)
            {
                return false;
            }
            ReadOnlySpan<T> unreadSpan = this.UnreadSpan;
            unreadSpan.CopyTo(destination);
            int num = unreadSpan.Length;
            SequencePosition nextPosition = this._nextPosition;
            ReadOnlyMemory<T> readOnlyMemory;
            while (this.Sequence.TryGet(ref nextPosition, out readOnlyMemory, true))
            {
                if (readOnlyMemory.Length > 0)
                {
                    ReadOnlySpan<T> span = readOnlyMemory.Span;
                    int num2 = Math.Min(span.Length, destination.Length - num);
                    span.Slice(0, num2).CopyTo(destination.Slice(num));
                    num += num2;
                    if (num >= destination.Length)
                    {
                        break;
                    }
                }
            }
            return true;
        }
References System.Buffers.SequenceReader< T >._nextPosition, System.ReadOnlySpan< T >.CopyTo(), System.destination, System.ReadOnlyMemory< T >.Length, System.ReadOnlySpan< T >.Length, System.Span< T >.Length, System.Math.Min(), System.Buffers.SequenceReader< T >.Remaining, System.Buffers.SequenceReader< T >.Sequence, System.ReadOnlySpan< T >.Slice(), System.ReadOnlyMemory< T >.Span, and System.Buffers.SequenceReader< T >.UnreadSpan.
Referenced by System.Buffers.SequenceReader< T >.TryCopyTo().