Terraria Decompiled: System.Buffers.SequenceReader.IsNextSlow
IsNextSlow()
bool System.Buffers.SequenceReader< T >.IsNextSlow (ReadOnlySpan< T > next, bool advancePast) inline private
Definition at line 605 of file SequenceReader.cs.
        {
            ReadOnlySpan<T> readOnlySpan = this.UnreadSpan;
            int length = next.Length;
            SequencePosition nextPosition = this._nextPosition;
            IL_008F:
            while (next.StartsWith(readOnlySpan))
            {
                if (next.Length == readOnlySpan.Length)
                {
                    if (advancePast)
                    {
                        this.Advance((long)length);
                    }
                    return true;
                }
                ReadOnlyMemory<T> readOnlyMemory;
                while (this.Sequence.TryGet(ref nextPosition, out readOnlyMemory, true))
                {
                    if (readOnlyMemory.Length > 0)
                    {
                        next = next.Slice(readOnlySpan.Length);
                        readOnlySpan = readOnlyMemory.Span;
                        if (readOnlySpan.Length > next.Length)
{
                            readOnlySpan = readOnlySpan.Slice(0, next.Length);
                            goto IL_008F;
                        }
                        goto IL_008F;
                    }
                }
                return false;
            }
            return false;
        }
References System.Buffers.SequenceReader< T >._nextPosition, System.Buffers.SequenceReader< T >.Advance(), System.length, System.ReadOnlyMemory< T >.Length, System.ReadOnlySpan< T >.Length, System.Buffers.SequenceReader< T >.Sequence, System.ReadOnlySpan< T >.Slice(), System.ReadOnlyMemory< T >.Span, and System.Buffers.SequenceReader< T >.UnreadSpan.
Referenced by System.Buffers.SequenceReader< T >.IsNext().