Terraria Decompiled: Terraria.GameContent.Events.MysticLogFairiesEvent.TrySpawningFairies
TrySpawningFairies()
void Terraria.GameContent.Events.MysticLogFairiesEvent.TrySpawningFairies () inline private
Definition at line 83 of file MysticLogFairiesEvent.cs.
        {
            if (Main.maxRaining > 0f || Main.bloodMoon || NPC.MoonLordCountdown > 0 || Main.snowMoon || Main.pumpkinMoon || Main.invasionType > 0)
            {
                return;
            }
            if (this._stumpCoords.Count == 0)
            {
                return;
            }
            int oneOverSpawnChance = this.GetOneOverSpawnChance();
            bool flag = false;
            for (int i = 0; i < Main.dayRate; i++)
            {
                if (Main.rand.Next(oneOverSpawnChance) == 0)
                {
                    flag = true;
                    break;
                }
            }
            if (!flag)
            {
                return;
            }
            int num = Main.rand.Next(this._stumpCoords.Count);
            Point point = this._stumpCoords[num];
            Vector2 vector = point.ToWorldCoordinates(24f, 8f);
            vector.Y -= 50f;
            if (WorldGen.PlayerLOS(point.X, point.Y))
            {
                return;
            }
            int num2 = Main.rand.Next(1, 4);
            if (Main.rand.Next(7) == 0)
            {
                num2++;
            }
            int num3 = (int)Utils.SelectRandom<short>(Main.rand, new short[] { 585, 584, 583 });
            for (int j = 0; j < num2; j++)
            {
                num3 = (int)Utils.SelectRandom<short>(Main.rand, new short[] { 585, 584, 583 });
                if (Main.tenthAnniversaryWorld && Main.rand.Next(4) != 0)
                {
                    num3 = 583;
                }
                int num4 = NPC.NewNPC(new EntitySource_WorldEvent(), (int)vector.X, (int)vector.Y, num3, 0, 0f, 0f, 0f, 0f, 255);
                if (Main.netMode == 2 && num4 < Main.maxNPCs)
                {
                    NetMessage.SendData(23, -1, -1, null, num4, 0f, 0f, 0f, 0, 0, 0);
                }
            }
            this._canSpawnFairies = false;
        }
References Terraria.GameContent.Events.MysticLogFairiesEvent._stumpCoords, Terraria.Main.bloodMoon, System.Collections.Generic.List< T >.Count, Terraria.Main.dayRate, Terraria.GameContent.Events.MysticLogFairiesEvent.GetOneOverSpawnChance(), int, Terraria.Main.invasionType, Terraria.Main.maxRaining, Terraria.NPC.MoonLordCountdown, Terraria.WorldGen.PlayerLOS(), Terraria.Main.pumpkinMoon, Terraria.Main.rand, Terraria.Main.snowMoon, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.Events.MysticLogFairiesEvent.UpdateTime().