Terraria Decompiled: Terraria.GameContent.Items.TagEffectState.TrySetActiveEffect
TrySetActiveEffect()
void Terraria.GameContent.Items.TagEffectState.TrySetActiveEffect (int type) inline
Definition at line 145 of file TagEffectState.cs.
        {
            if (this.Type == type)
            {
                return;
            }
            if (this._effect != null)
            {
                this._effect.OnRemovedFromPlayer(this._owner);
            }
            this.Clear();
            UniqueTagEffect effect = this._effect;
            this.Type = type;
            this._effect = ItemID.Sets.UniqueTagEffects[type];
            if (this._owner == Main.LocalPlayer && ((this._effect != null && this._effect.NetSync) || (effect != null && effect.NetSync)))
            {
                NetManager.Instance.SendToServer(TagEffectState.NetModule.WriteChangeActiveEffect(this));
            }
            if (this._effect != null)
            {
                this._effect.OnSetToPlayer(this._owner);
            }
        }
References Terraria.GameContent.Items.TagEffectState._effect, Terraria.GameContent.Items.TagEffectState._owner, Terraria.GameContent.Items.TagEffectState.Clear(), Terraria.Net.NetManager.Instance, Terraria.Main.LocalPlayer, Terraria.GameContent.Items.UniqueTagEffect.NetSync, Terraria.GameContent.Items.UniqueTagEffect.OnRemovedFromPlayer(), Terraria.GameContent.Items.UniqueTagEffect.OnSetToPlayer(), Terraria.Net.NetManager.SendToServer(), Terraria.ID.ItemID.Sets.UniqueTagEffects, and Terraria.GameContent.Items.TagEffectState.NetModule.WriteChangeActiveEffect().
Referenced by Terraria.GameContent.Items.TagEffectState.NetModule.Deserialize(), and Terraria.GameContent.Items.TagEffectState.TryApplyTagToNPC().