Terraria Decompiled: Terraria.GameContent.Items.TagEffectState.EnableProcOnNPC
EnableProcOnNPC()
void Terraria.GameContent.Items.TagEffectState.EnableProcOnNPC (NPC npc) inline private
Definition at line 80 of file TagEffectState.cs.
        {
            if (this._effect == null)
            {
                return;
            }
            this.ProcTimeLeftOnNPC[npc.whoAmI] = this._effect.TagDuration;
            if (this._effect.NetSync && this._owner == Main.LocalPlayer)
            {
                NetManager.Instance.SendToServer(TagEffectState.NetModule.WriteEnableProcOnNPC(this, npc.whoAmI));
            }
        }
References Terraria.GameContent.Items.TagEffectState._effect, Terraria.Net.NetManager.Instance, Terraria.Main.LocalPlayer, Terraria.GameContent.Items.UniqueTagEffect.NetSync, Terraria.GameContent.Items.TagEffectState.ProcTimeLeftOnNPC, Terraria.Net.NetManager.SendToServer(), Terraria.GameContent.Items.UniqueTagEffect.TagDuration, Terraria.Entity.whoAmI, and Terraria.GameContent.Items.TagEffectState.NetModule.WriteEnableProcOnNPC().
Referenced by Terraria.GameContent.Items.TagEffectState.NetModule.Deserialize(), and Terraria.GameContent.Items.TagEffectState.TryEnableProcOnNPC().