Terraria Decompiled: Terraria.GameContent.Items.TagEffectState.ModifyHit
ModifyHit()
void Terraria.GameContent.Items.TagEffectState.ModifyHit (Projectile optionalProjectile, NPC npcHit, ref int damageDealt, ref bool crit) inline
Definition at line 170 of file TagEffectState.cs.
        {
            if (this._effect == null)
            {
                return;
            }
            if (!this.IsNPCTagged(npcHit.whoAmI))
            {
                return;
            }
            if (!this._effect.CanRunHitEffects(this._owner, optionalProjectile, npcHit))
            {
                return;
            }
            this._effect.ModifyTaggedHit(this._owner, optionalProjectile, npcHit, ref damageDealt, ref crit);
            if (this.CanProcOnNPC(npcHit.whoAmI))
            {
                this._effect.ModifyProcHit(this._owner, optionalProjectile, npcHit, ref damageDealt, ref crit);
            }
        }
References Terraria.GameContent.Items.TagEffectState._effect, Terraria.GameContent.Items.TagEffectState._owner, Terraria.GameContent.Items.TagEffectState.CanProcOnNPC(), Terraria.GameContent.Items.UniqueTagEffect.CanRunHitEffects(), Terraria.GameContent.Items.TagEffectState.IsNPCTagged(), Terraria.GameContent.Items.UniqueTagEffect.ModifyProcHit(), Terraria.GameContent.Items.UniqueTagEffect.ModifyTaggedHit(), and Terraria.Entity.whoAmI.