Terraria Decompiled: Terraria.GameContent.Items.TagEffectState.OnHit
OnHit()
void Terraria.GameContent.Items.TagEffectState.OnHit (Projectile optionalProjectile, NPC npcHit, int calcDamage) inline
Definition at line 192 of file TagEffectState.cs.
        {
            if (this._effect == null)
            {
                return;
            }
            if (!this.IsNPCTagged(npcHit.whoAmI))
            {
                return;
            }
            if (!this._effect.CanRunHitEffects(this._owner, optionalProjectile, npcHit))
            {
                return;
            }
            this._effect.OnTaggedHit(this._owner, optionalProjectile, npcHit, calcDamage);
            if (this.CanProcOnNPC(npcHit.whoAmI))
            {
                this.ClearProcOnNPC(npcHit.whoAmI);
                this._effect.OnProcHit(this._owner, optionalProjectile, npcHit, calcDamage);
            }
        }
References Terraria.GameContent.Items.TagEffectState._effect, Terraria.GameContent.Items.TagEffectState._owner, Terraria.GameContent.Items.TagEffectState.CanProcOnNPC(), Terraria.GameContent.Items.UniqueTagEffect.CanRunHitEffects(), Terraria.GameContent.Items.TagEffectState.ClearProcOnNPC(), Terraria.GameContent.Items.TagEffectState.IsNPCTagged(), Terraria.GameContent.Items.UniqueTagEffect.OnProcHit(), Terraria.GameContent.Items.UniqueTagEffect.OnTaggedHit(), and Terraria.Entity.whoAmI.