Terraria Decompiled: Terraria.GameContent.Items.TagEffectState.TryApplyTagToNPC
TryApplyTagToNPC()
void Terraria.GameContent.Items.TagEffectState.TryApplyTagToNPC (int itemType, NPC npc) inline
Definition at line 124 of file TagEffectState.cs.
        {
            if (!ItemID.Sets.UniqueTagEffects[itemType].CanApplyTagToNPC(npc.type))
            {
                return;
            }
            this.TrySetActiveEffect(itemType);
            this.ApplyTagToNPC(npc);
        }
References Terraria.GameContent.Items.TagEffectState.ApplyTagToNPC(), Terraria.GameContent.Items.TagEffectState.TrySetActiveEffect(), Terraria.NPC.type, and Terraria.ID.ItemID.Sets.UniqueTagEffects.
Referenced by Terraria.Player.ApplyNPCOnHitEffects().