Terraria Decompiled: Terraria.GameContent.Items.TagEffectState.ApplyTagToNPC
ApplyTagToNPC()
void Terraria.GameContent.Items.TagEffectState.ApplyTagToNPC (NPC npc) inline private
Definition at line 65 of file TagEffectState.cs.
        {
            if (this._effect == null)
            {
                return;
            }
            this.TimeLeftOnNPC[npc.whoAmI] = this._effect.TagDuration;
            if (this._effect.NetSync && this._owner == Main.LocalPlayer)
            {
                NetManager.Instance.SendToServer(TagEffectState.NetModule.WriteApplyTagToNPC(this, npc.whoAmI));
            }
            this._effect.OnTagAppliedToNPC(this._owner, npc);
        }
References Terraria.GameContent.Items.TagEffectState._effect, Terraria.GameContent.Items.TagEffectState._owner, Terraria.Net.NetManager.Instance, Terraria.Main.LocalPlayer, Terraria.GameContent.Items.UniqueTagEffect.NetSync, Terraria.GameContent.Items.UniqueTagEffect.OnTagAppliedToNPC(), Terraria.Net.NetManager.SendToServer(), Terraria.GameContent.Items.UniqueTagEffect.TagDuration, Terraria.GameContent.Items.TagEffectState.TimeLeftOnNPC, Terraria.Entity.whoAmI, and Terraria.GameContent.Items.TagEffectState.NetModule.WriteApplyTagToNPC().
Referenced by Terraria.GameContent.Items.TagEffectState.NetModule.Deserialize(), and Terraria.GameContent.Items.TagEffectState.TryApplyTagToNPC().