Terraria Decompiled: Terraria.DataStructures.MinionRespawner.RestoreMinionsFor
RestoreMinionsFor()
void Terraria.DataStructures.MinionRespawner.RestoreMinionsFor (Player player) inline
Definition at line 31 of file MinionRespawner.cs.
        {
            int mouseX = Main.mouseX;
            int mouseY = Main.mouseY;
            Main.mouseX = Main.screenWidth / 2;
            Main.mouseY = Main.screenHeight / 2;
            foreach (MinionSpawnInfo minionSpawnInfo in this._minions)
            {
                minionSpawnInfo.TryRespawn(player);
            }
            Main.mouseX = mouseX;
            Main.mouseY = mouseY;
            this.Clear();
        }
References Terraria.DataStructures.MinionRespawner._minions, Terraria.DataStructures.MinionRespawner.Clear(), Terraria.Main.mouseX, Terraria.Main.mouseY, and Terraria.DataStructures.MinionSpawnInfo.TryRespawn().
Referenced by Terraria.Player.Spawn().