Terraria Decompiled: Terraria.GameContent.Events.DD2Event.Difficulty_1_SpawnMonsterFromGate
Difficulty_1_SpawnMonsterFromGate()
static void Terraria.GameContent.Events.DD2Event.Difficulty_1_SpawnMonsterFromGate (Vector2 gateBottom, bool leftGate) inline static private
Definition at line 1050 of file DD2Event.cs.
        {
            int num = (int)gateBottom.X;
            int num2 = (int)gateBottom.Y;
            int num3 = 50;
            int num4 = 6;
            if (NPC.waveNumber > 4)
            {
                num4 = 12;
            }
            else if (NPC.waveNumber > 3)
            {
                num4 = 8;
            }
            int num5 = 6;
            if (NPC.waveNumber > 4)
            {
                num5 = 8;
            }
            for (int i = 1; i < Main.CurrentFrameFlags.ActivePlayersCount; i++)
            {
                num3 = (int)((double)num3 * 1.3);
                num4 = (int)((double)num4 * 1.3);
                num5 = (int)((double)num5 * 1.3);
            }
            int num6 = Main.maxNPCs;
            switch (NPC.waveNumber)
            {
            case 1:
                if (NPC.CountNPCS(552) + NPC.CountNPCS(555) < num3)
                {
                    num6 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 552, 0, 0f, 0f, 0f, 0f, 255);
                }
                break;
            case 2:
                if (NPC.CountNPCS(552) + NPC.CountNPCS(555) < num3)
                {
                    if (Main.rand.Next(7) == 0)
                    {
                        num6 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 555, 0, 0f, 0f, 0f, 0f, 255);
                    }
                    else
                    {
                        num6 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 552, 0, 0f, 0f, 0f, 0f, 255);
                    }
                }
                break;
            case 3:
                if (Main.rand.Next(6) == 0 && NPC.CountNPCS(561) < num4)
                {
                    num6 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 561, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (NPC.CountNPCS(552) + NPC.CountNPCS(555) < num3)
                {
                    if (Main.rand.Next(5) == 0)
                    {
                        num6 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 555, 0, 0f, 0f, 0f, 0f, 255);
                    }
                    else
                    {
                        num6 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 552, 0, 0f, 0f, 0f, 0f, 255);
                    }
                }
                break;
            case 4:
                if (Main.rand.Next(12) == 0 && NPC.CountNPCS(558) < num5)
                {
                    num6 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 558, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (Main.rand.Next(5) == 0 && NPC.CountNPCS(561) < num4)
                {
                    num6 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 561, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (NPC.CountNPCS(552) + NPC.CountNPCS(555) < num3)
                {
                    if (Main.rand.Next(5) == 0)
                    {
                        num6 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 555, 0, 0f, 0f, 0f, 0f, 255);
                    }
                    else
                    {
                        num6 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 552, 0, 0f, 0f, 0f, 0f, 255);
                    }
                }
                break;
            case 5:
            {
                int num7;
                int num8;
                int num9;
                DD2Event.GetInvasionStatus(out num7, out num8, out num9, false);
                if ((!leftGate || Main.rand.Next(2) == 0) && (float)num9 > (float)num8 * 0.5f && !NPC.AnyNPCs(564))
                {
                    num6 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 564, 0, 0f, 0f, 0f, 0f, 255);
                }
                if (Main.rand.Next(10) == 0 && NPC.CountNPCS(558) < num5)
                {
                    num6 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 558, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (Main.rand.Next(4) == 0 && NPC.CountNPCS(561) < num4)
                {
                    num6 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 561, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (NPC.CountNPCS(552) + NPC.CountNPCS(555) < num3)
                {
                    if (Main.rand.Next(4) == 0)
                    {
                        num6 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 555, 0, 0f, 0f, 0f, 0f, 255);
                    }
                    else
                    {
                        num6 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 552, 0, 0f, 0f, 0f, 0f, 255);
                    }
                }
                break;
            }
            default:
                num6 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 552, 0, 0f, 0f, 0f, 0f, 255);
                break;
            }
            if (Main.netMode == 2 && num6 < Main.maxNPCs)
            {
                NetMessage.SendData(23, -1, -1, null, num6, 0f, 0f, 0f, 0, 0, 0);
            }
        }
References Terraria.Main.CurrentFrameFlags.ActivePlayersCount, Terraria.NPC.AnyNPCs(), Terraria.NPC.CountNPCS(), Terraria.GameContent.Events.DD2Event.GetInvasionStatus(), Terraria.GameContent.Events.DD2Event.GetSpawnSource_OldOnesArmy(), int, Terraria.Main.maxNPCs, Terraria.Main.netMode, Terraria.NPC.NewNPC(), Terraria.Main.rand, Terraria.NetMessage.SendData(), Terraria.NPC.waveNumber, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.GameContent.Events.DD2Event.SpawnMonsterFromGate().