Terraria Decompiled: Terraria.GameContent.Events.DD2Event.UpdateTime
UpdateTime()
static void Terraria.GameContent.Events.DD2Event.UpdateTime () inline static
Definition at line 129 of file DD2Event.cs.
        {
            if (!DD2Event.Ongoing && !Main.dedServ)
            {
                Filters.Scene.Deactivate("CrystalDestructionVortex", new object[0]);
                Filters.Scene.Deactivate("CrystalDestructionColor", new object[0]);
                Filters.Scene.Deactivate("CrystalWin", new object[0]);
                return;
            }
            if (Main.netMode != 1 && !NPC.AnyNPCs(548))
            {
                DD2Event.StopInvasion(false);
            }
            if (Main.netMode == 1)
            {
                if (DD2Event._timeLeftUntilSpawningBegins > 0)
                {
                    DD2Event._timeLeftUntilSpawningBegins--;
                }
                if (DD2Event._timeLeftUntilSpawningBegins < 0)
                {
                    DD2Event._timeLeftUntilSpawningBegins = 0;
                }
                return;
            }
            if (DD2Event._timeLeftUntilSpawningBegins > 0)
            {
                DD2Event._timeLeftUntilSpawningBegins--;
                if (DD2Event._timeLeftUntilSpawningBegins == 0)
                {
                    int num;
                    int num2;
                    int num3;
                    DD2Event.GetInvasionStatus(out num, out num2, out num3, false);
                    if (!DD2Event.LostThisRun)
                    {
                        WorldGen.BroadcastText(Lang.GetInvasionWaveText(num, DD2Event.GetEnemiesForWave(num)), DD2Event.INFO_NEW_WAVE_COLOR);
                        if (num == 7 && DD2Event.OngoingDifficulty == 3)
{
                            DD2Event.SummonBetsy();
                        }
                    }
                    else
                    {
                        DD2Event.LoseInvasionMessage();
                    }
                    if (Main.netMode != 1)
                    {
                        Main.ReportInvasionProgress(num3, num2, 3, num);
                    }
                    if (Main.netMode == 2)
                    {
                        NetMessage.SendData(78, -1, -1, null, Main.invasionProgress, (float)Main.invasionProgressMax, 3f, (float)num, 0, 0, 0);
                    }
                }
            }
            if (DD2Event._timeLeftUntilSpawningBegins < 0)
            {
                DD2Event._timeLeftUntilSpawningBegins = 0;
            }
        }
References Terraria.GameContent.Events.DD2Event._timeLeftUntilSpawningBegins, Terraria.NPC.AnyNPCs(), Terraria.WorldGen.BroadcastText(), Terraria.Graphics.Effects.EffectManager< T >.Deactivate(), Terraria.Main.dedServ, Terraria.GameContent.Events.DD2Event.GetEnemiesForWave(), Terraria.GameContent.Events.DD2Event.GetInvasionStatus(), Terraria.Lang.GetInvasionWaveText(), Terraria.GameContent.Events.DD2Event.INFO_NEW_WAVE_COLOR, Terraria.Main.invasionProgress, Terraria.Main.invasionProgressMax, Terraria.GameContent.Events.DD2Event.LoseInvasionMessage(), Terraria.GameContent.Events.DD2Event.LostThisRun, Terraria.Main.netMode, Terraria.GameContent.Events.DD2Event.Ongoing, Terraria.GameContent.Events.DD2Event.OngoingDifficulty, Terraria.Main.ReportInvasionProgress(), Terraria.Graphics.Effects.Filters.Scene, Terraria.NetMessage.SendData(), Terraria.GameContent.Events.DD2Event.StopInvasion(), and Terraria.GameContent.Events.DD2Event.SummonBetsy().
Referenced by Terraria.Main.UpdateTime().