Terraria Decompiled: Terraria.GameContent.Events.DD2Event.RaiseGoblins
RaiseGoblins()
static void Terraria.GameContent.Events.DD2Event.RaiseGoblins (NPC caller, Vector2 spot) inline static
Definition at line 735 of file DD2Event.cs.
        {
            List<Vector2> list = new List<Vector2>();
            foreach (Vector2 vector in DD2Event._deadGoblinSpots)
            {
                if (Vector2.DistanceSquared(vector, spot) <= 722500f)
                {
                    list.Add(vector);
                }
            }
            foreach (Vector2 vector2 in list)
            {
                DD2Event._deadGoblinSpots.Remove(vector2);
            }
            int num = 0;
            foreach (Vector2 vector3 in list)
            {
                Point point = vector3.ToTileCoordinates();
                point.X += Main.rand.Next(-15, 16);
                Point point2;
                if (WorldUtils.Find(point, Searches.Chain(new Searches.Down(50), new GenCondition[]
                {
                    new Conditions.IsSolid()
                }), out point2))
                {
                    if (DD2Event.OngoingDifficulty == 3)
                    {
                        NPC.NewNPC(caller.GetSpawnSourceForNPCFromNPCAI(), point2.X * 16 + 8, point2.Y * 16, 567, 0, 0f, 0f, 0f, 0f, 255);
                    }
                    else
                    {
                        NPC.NewNPC(caller.GetSpawnSourceForNPCFromNPCAI(), point2.X * 16 + 8, point2.Y * 16, 566, 0, 0f, 0f, 0f, 0f, 255);
                    }
                    if (++num >= 8)
                    {
                        break;
                    }
                }
            }
        }
References Terraria.GameContent.Events.DD2Event._deadGoblinSpots, Terraria.WorldBuilding.Searches.Chain(), Microsoft.Xna.Framework.Vector2.DistanceSquared(), Terraria.WorldBuilding.WorldUtils.Find(), System.list, Terraria.NPC.NewNPC(), Terraria.GameContent.Events.DD2Event.OngoingDifficulty, Terraria.Main.rand, System.Collections.Generic.List< T >.Remove(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.NPC.AI_109_DarkMage().