Terraria Decompiled: Terraria.GameContent.Events.DD2Event.Difficulty_3_SpawnMonsterFromGate
Difficulty_3_SpawnMonsterFromGate()
static void Terraria.GameContent.Events.DD2Event.Difficulty_3_SpawnMonsterFromGate (Vector2 gateBottom, bool leftGate) inline static private
Definition at line 1640 of file DD2Event.cs.
        {
            int num = (int)gateBottom.X;
            int num2 = (int)gateBottom.Y;
            int num3 = 60;
            int num4 = 7;
            if (NPC.waveNumber > 1)
            {
                num4 = 9;
            }
            if (NPC.waveNumber > 3)
            {
                num4 = 12;
            }
            if (NPC.waveNumber > 5)
            {
                num4 = 15;
            }
            int num5 = 7;
            if (NPC.waveNumber > 4)
            {
                num5 = 10;
            }
            int num6 = 2;
            if (NPC.waveNumber > 5)
            {
                num6 = 3;
            }
            int num7 = 12;
            if (NPC.waveNumber > 3)
            {
                num7 = 18;
            }
            int num8 = 4;
            if (NPC.waveNumber > 5)
            {
                num8 = 6;
            }
            int num9 = 4;
            for (int i = 1; i < Main.CurrentFrameFlags.ActivePlayersCount; i++)
            {
                num3 = (int)((double)num3 * 1.3);
                num4 = (int)((double)num4 * 1.3);
                num7 = (int)((double)num3 * 1.3);
                num8 = (int)((double)num3 * 1.35);
                num9 = (int)((double)num9 * 1.3);
            }
            int num10 = Main.maxNPCs;
            int num11 = Main.maxNPCs;
            switch (NPC.waveNumber)
            {
            case 1:
                if (Main.rand.Next(18) == 0 && NPC.CountNPCS(563) < num4)
                {
                    num10 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 563, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (NPC.CountNPCS(554) < num3)
                {
                    if (Main.rand.Next(7) == 0)
                    {
                        num10 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 557, 0, 0f, 0f, 0f, 0f, 255);
                    }
                    num11 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 554, 0, 0f, 0f, 0f, 0f, 255);
                }
                break;
            case 2:
                if (Main.rand.Next(3) == 0 && NPC.CountNPCS(578) < num9)
                {
                    num10 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 578, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (Main.rand.Next(7) == 0 && NPC.CountNPCS(563) < num4)
                {
                    num10 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 563, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (Main.rand.Next(3) == 0 && NPC.CountNPCS(573) < num7)
                {
                    num10 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 573, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (NPC.CountNPCS(554) < num3)
                {
                    if (Main.rand.Next(4) == 0)
                    {
                        num10 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 557, 0, 0f, 0f, 0f, 0f, 255);
                    }
                    num11 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 554, 0, 0f, 0f, 0f, 0f, 255);
                }
                break;
            case 3:
                if (Main.rand.Next(13) == 0 && NPC.CountNPCS(571) < num8)
                {
                    num10 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 571, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (Main.rand.Next(7) == 0 && NPC.CountNPCS(573) < num7)
                {
                    num10 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 573, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (Main.rand.Next(10) == 0 && NPC.CountNPCS(560) < num5)
                {
                    num10 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 560, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (Main.rand.Next(8) == 0 && NPC.CountNPCS(563) < num4)
                {
                    num10 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 563, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (NPC.CountNPCS(554) + NPC.CountNPCS(557) < num3)
                {
                    num10 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 554, 0, 0f, 0f, 0f, 0f, 255);
                }
                break;
            case 4:
                if (Main.rand.Next(24) == 0 && !NPC.AnyNPCs(565))
                {
                    num10 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 565, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (Main.rand.Next(12) == 0 && NPC.CountNPCS(571) < num8)
                {
                    num10 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 571, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (Main.rand.Next(15) == 0 && NPC.CountNPCS(560) < num5)
                {
                    num10 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 560, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (Main.rand.Next(7) == 0 && NPC.CountNPCS(563) < num4)
                {
                    num10 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 563, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (Main.rand.Next(5) == 0 && NPC.CountNPCS(573) + NPC.CountNPCS(575) < num7)
                {
                    if (Main.rand.Next(3) != 0)
                    {
                        num10 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 573, 0, 0f, 0f, 0f, 0f, 255);
                    }
                    else
                    {
                        num10 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 575, 0, 0f, 0f, 0f, 0f, 255);
                    }
                }
                else if (NPC.CountNPCS(554) < num3)
                {
                    num10 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 554, 0, 0f, 0f, 0f, 0f, 255);
                }
                break;
            case 5:
                if (Main.rand.Next(20) == 0 && !NPC.AnyNPCs(577))
                {
                    num10 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 577, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (Main.rand.Next(17) == 0 && NPC.CountNPCS(569) < num6)
                {
                    num10 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 569, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (Main.rand.Next(8) == 0 && NPC.CountNPCS(571) < num8)
                {
                    num10 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 571, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (Main.rand.Next(7) == 0 && NPC.CountNPCS(573) + NPC.CountNPCS(575) < num7)
                {
                    if (Main.rand.Next(4) != 0)
                    {
                        num10 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 573, 0, 0f, 0f, 0f, 0f, 255);
                    }
                    else
                    {
                        num10 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 575, 0, 0f, 0f, 0f, 0f, 255);
                    }
                }
                else if (NPC.CountNPCS(554) + NPC.CountNPCS(557) < num3)
                {
                    if (Main.rand.Next(3) == 0)
                    {
                        num10 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 557, 0, 0f, 0f, 0f, 0f, 255);
                    }
                    num11 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 554, 0, 0f, 0f, 0f, 0f, 255);
                }
                break;
            case 6:
                if (Main.rand.Next(20) == 0 && !NPC.AnyNPCs(577))
                {
                    num10 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 577, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (Main.rand.Next(20) == 0 && !NPC.AnyNPCs(565))
                {
                    num10 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 565, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (Main.rand.Next(12) == 0 && NPC.CountNPCS(571) < num8)
                {
                    num10 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 571, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (Main.rand.Next(25) == 0 && NPC.CountNPCS(569) < num6)
                {
                    num10 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 569, 0, 0f, 0f, 0f, 0f, 255);
                }
                if (Main.rand.Next(7) == 0 && NPC.CountNPCS(578) < num9)
                {
                    num10 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 578, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (Main.rand.Next(7) == 0 && NPC.CountNPCS(573) + NPC.CountNPCS(575) < num7)
                {
                    if (Main.rand.Next(3) != 0)
                    {
                        num10 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 573, 0, 0f, 0f, 0f, 0f, 255);
                    }
                    else
                    {
                        num10 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 575, 0, 0f, 0f, 0f, 0f, 255);
                    }
                }
                else if (Main.rand.Next(5) == 0 && NPC.CountNPCS(563) < num4)
                {
                    num10 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 563, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (NPC.CountNPCS(554) + NPC.CountNPCS(557) < num3)
                {
                    if (Main.rand.Next(3) == 0)
                    {
                        num10 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 557, 0, 0f, 0f, 0f, 0f, 255);
                    }
                    num11 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 554, 0, 0f, 0f, 0f, 0f, 255);
                }
                break;
            case 7:
                if (Main.rand.Next(20) == 0 && NPC.CountNPCS(571) < num8)
                {
                    num10 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 571, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (Main.rand.Next(17) == 0 && NPC.CountNPCS(569) < num6)
                {
                    num10 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 569, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (Main.rand.Next(10) == 0 && NPC.CountNPCS(563) < num4)
                {
                    num10 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 563, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (NPC.CountNPCS(554) + NPC.CountNPCS(557) < num3)
                {
                    if (Main.rand.Next(5) == 0)
                    {
                        num10 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 557, 0, 0f, 0f, 0f, 0f, 255);
                    }
                    num11 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 554, 0, 0f, 0f, 0f, 0f, 255);
                }
                break;
            default:
                num10 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 554, 0, 0f, 0f, 0f, 0f, 255);
                break;
            }
            if (Main.netMode == 2 && num10 < Main.maxNPCs)
            {
                NetMessage.SendData(23, -1, -1, null, num10, 0f, 0f, 0f, 0, 0, 0);
            }
            if (Main.netMode == 2 && num11 < Main.maxNPCs)
            {
                NetMessage.SendData(23, -1, -1, null, num11, 0f, 0f, 0f, 0, 0, 0);
            }
        }
References Terraria.Main.CurrentFrameFlags.ActivePlayersCount, Terraria.NPC.AnyNPCs(), Terraria.NPC.CountNPCS(), Terraria.GameContent.Events.DD2Event.GetSpawnSource_OldOnesArmy(), int, Terraria.Main.maxNPCs, Terraria.Main.netMode, Terraria.NPC.NewNPC(), Terraria.Main.rand, Terraria.NetMessage.SendData(), Terraria.NPC.waveNumber, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.GameContent.Events.DD2Event.SpawnMonsterFromGate().