Terraria Decompiled: Terraria.GameContent.Events.DD2Event.ShouldDropCrystals
ShouldDropCrystals()
static bool Terraria.GameContent.Events.DD2Event.ShouldDropCrystals () inline static
Definition at line 841 of file DD2Event.cs.
        {
            int num;
            int num2;
            int num3;
            DD2Event.GetInvasionStatus(out num, out num2, out num3, false);
            if (DD2Event._crystalsDropping_lastWave < num)
            {
                DD2Event._crystalsDropping_lastWave++;
                if (DD2Event._crystalsDropping_alreadyDropped > 0)
                {
                    DD2Event._crystalsDropping_alreadyDropped -= DD2Event._crystalsDropping_toDrop;
                }
                if (DD2Event.OngoingDifficulty == 1)
                {
                    switch (num)
                    {
                    case 1:
                        DD2Event._crystalsDropping_toDrop = 20;
                        break;
                    case 2:
                        DD2Event._crystalsDropping_toDrop = 20;
                        break;
                    case 3:
                        DD2Event._crystalsDropping_toDrop = 30;
                        break;
                    case 4:
                        DD2Event._crystalsDropping_toDrop = 30;
                        break;
                    case 5:
                        DD2Event._crystalsDropping_toDrop = 40;
                        break;
                    }
                }
                else if (DD2Event.OngoingDifficulty == 2)
                {
                    switch (num)
                    {
                    case 1:
                        DD2Event._crystalsDropping_toDrop = 20;
                        break;
                    case 2:
                        DD2Event._crystalsDropping_toDrop = 20;
                        break;
                    case 3:
                        DD2Event._crystalsDropping_toDrop = 20;
                        break;
                    case 4:
                        DD2Event._crystalsDropping_toDrop = 20;
                        break;
                    case 5:
                        DD2Event._crystalsDropping_toDrop = 20;
                        break;
                    case 6:
                        DD2Event._crystalsDropping_toDrop = 30;
                        break;
                    case 7:
                        DD2Event._crystalsDropping_toDrop = 30;
                        break;
                    }
                }
                else if (DD2Event.OngoingDifficulty == 3)
                {
                    switch (num)
                    {
                    case 1:
                        DD2Event._crystalsDropping_toDrop = 20;
                        break;
                    case 2:
                        DD2Event._crystalsDropping_toDrop = 20;
                        break;
                    case 3:
                        DD2Event._crystalsDropping_toDrop = 20;
                        break;
                    case 4:
                        DD2Event._crystalsDropping_toDrop = 20;
                        break;
                    case 5:
                        DD2Event._crystalsDropping_toDrop = 30;
                        break;
                    case 6:
                        DD2Event._crystalsDropping_toDrop = 30;
                        break;
                    case 7:
                        DD2Event._crystalsDropping_toDrop = 30;
                        break;
                    }
                }
            }
            if (Main.netMode != 0 && Main.expertMode)
            {
                DD2Event._crystalsDropping_toDrop = (int)((float)DD2Event._crystalsDropping_toDrop * NPC.GetBalance());
            }
            float num4 = (float)num3 / (float)num2;
            if ((float)DD2Event._crystalsDropping_alreadyDropped < (float)DD2Event._crystalsDropping_toDrop * num4)
            {
                DD2Event._crystalsDropping_alreadyDropped++;
                return true;
            }
            return false;
        }
References Terraria.GameContent.Events.DD2Event._crystalsDropping_alreadyDropped, Terraria.GameContent.Events.DD2Event._crystalsDropping_lastWave, Terraria.GameContent.Events.DD2Event._crystalsDropping_toDrop, Terraria.Main.expertMode, Terraria.NPC.GetBalance(), Terraria.GameContent.Events.DD2Event.GetInvasionStatus(), int, Terraria.Main.netMode, and Terraria.GameContent.Events.DD2Event.OngoingDifficulty.
Referenced by Terraria.NPC.DoDeathEvents().