Terraria Decompiled: Terraria.GameContent.Events.DD2Event.DropMedals
DropMedals()
static void Terraria.GameContent.Events.DD2Event.DropMedals (int numberOfMedals) inline static
Definition at line 829 of file DD2Event.cs.
        {
            for (int i = 0; i < Main.maxNPCs; i++)
            {
                if (Main.npc[i].active && Main.npc[i].type == 548)
                {
                    Main.npc[i].DropItemInstanced(Main.npc[i].position, Main.npc[i].Size, 3817, numberOfMedals, false);
                }
            }
        }
References Terraria.NPC.active, Terraria.NPC.DropItemInstanced(), Terraria.Main.maxNPCs, Terraria.Main.npc, Terraria.Entity.position, Terraria.Entity.Size, and Terraria.NPC.type.
Referenced by Terraria.GameContent.Events.DD2Event.CheckProgress(), and Terraria.GameContent.Events.DD2Event.WinInvasionInternal().