Terraria Decompiled: System.Nullable.GetUnderlyingType
GetUnderlyingType()
static Type System.Nullable< T >.GetUnderlyingType (Type nullableType) inline static
Definition at line 41 of file Nullable.2.cs.
        {
            if (nullableType == null)
            {
                throw new ArgumentNullException("nullableType");
            }
            if (nullableType.IsGenericType && !nullableType.IsGenericTypeDefinition && nullableType.GetGenericTypeDefinition() == typeof(Nullable<>))
            {
                return nullableType.GetGenericArguments()[0];
            }
            return null;
        }
References System.Type.GetGenericArguments(), System.Type.GetGenericTypeDefinition(), System.Type.IsGenericType, and System.Type.IsGenericTypeDefinition.
Referenced by Newtonsoft.Json.Converters.KeyValuePairConverter.CanConvert(), Newtonsoft.Json.Converters.StringEnumConverter.CanConvert(), Newtonsoft.Json.Linq.Extensions.Convert< T, U >(), System.Runtime.Serialization.ObjectManager.DoValueTypeFixup(), Newtonsoft.Json.Utilities.ReflectionUtils.EnsureNotNullableType(), System.Collections.Concurrent.Partitioner< TSource >.GetDefaultChunkSize< TSource >(), Newtonsoft.Json.Schema.JsonSchemaGenerator.GetJsonSchemaType(), Newtonsoft.Json.Utilities.ConvertUtils.GetTypeCode(), Newtonsoft.Json.Serialization.DefaultContractResolver.IsIConvertible(), System.SpanHelpers.IsReferenceOrContainsReferencesCore(), Newtonsoft.Json.Serialization.JsonContract.JsonContract(), CsvHelper.TypeConversion.NullableConverter.NullableConverter(), Newtonsoft.Json.Converters.BinaryConverter.ReadJson(), Newtonsoft.Json.Converters.IsoDateTimeConverter.ReadJson(), Newtonsoft.Json.Converters.JavaScriptDateTimeConverter.ReadJson(), Newtonsoft.Json.Converters.KeyValuePairConverter.ReadJson(), Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(), System.Reflection.Emit.TypeBuilder.SetConstantValue(), Newtonsoft.Json.Linq.JToken.ToObject(), Newtonsoft.Json.Utilities.ConvertUtils.TryConvertInternal(), FullSerializer.Internal.fsNullableConverter.TryDeserialize(), FullSerializer.Internal.fsNullableConverter.TrySerialize(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteArray(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteArrayMember(), and System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteMembers().