Terraria Decompiled: Terraria.GameContent.Events.DD2Event.Difficulty_2_SpawnMonsterFromGate
Difficulty_2_SpawnMonsterFromGate()
static void Terraria.GameContent.Events.DD2Event.Difficulty_2_SpawnMonsterFromGate (Vector2 gateBottom, bool leftGate) inline static private
Definition at line 1305 of file DD2Event.cs.
        {
            int num = (int)gateBottom.X;
            int num2 = (int)gateBottom.Y;
            int num3 = 50;
            int num4 = 5;
            if (NPC.waveNumber > 1)
            {
                num4 = 8;
            }
            if (NPC.waveNumber > 3)
            {
                num4 = 10;
            }
            if (NPC.waveNumber > 5)
            {
                num4 = 12;
            }
            int num5 = 5;
            if (NPC.waveNumber > 4)
            {
                num5 = 7;
            }
            int num6 = 2;
            int num7 = 8;
            if (NPC.waveNumber > 3)
            {
                num7 = 12;
            }
            int num8 = 3;
            if (NPC.waveNumber > 5)
            {
                num8 = 5;
            }
            for (int i = 1; i < Main.CurrentFrameFlags.ActivePlayersCount; i++)
            {
                num3 = (int)((double)num3 * 1.3);
                num4 = (int)((double)num4 * 1.3);
                num7 = (int)((double)num3 * 1.3);
                num8 = (int)((double)num3 * 1.35);
            }
            int num9 = Main.maxNPCs;
            int num10 = Main.maxNPCs;
            switch (NPC.waveNumber)
            {
            case 1:
                if (Main.rand.Next(20) == 0 && NPC.CountNPCS(562) < num4)
                {
                    num9 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 562, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (NPC.CountNPCS(553) < num3)
                {
                    num9 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 553, 0, 0f, 0f, 0f, 0f, 255);
                }
                break;
            case 2:
                if (Main.rand.Next(3) == 0 && NPC.CountNPCS(572) < num7)
                {
                    num9 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 572, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (Main.rand.Next(8) == 0 && NPC.CountNPCS(562) < num4)
                {
                    num9 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 562, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (NPC.CountNPCS(553) < num3)
                {
                    num9 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 553, 0, 0f, 0f, 0f, 0f, 255);
                }
                break;
            case 3:
                if (Main.rand.Next(7) == 0 && NPC.CountNPCS(572) < num7)
                {
                    num9 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 572, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (Main.rand.Next(10) == 0 && NPC.CountNPCS(559) < num5)
                {
                    num9 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 559, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (Main.rand.Next(8) == 0 && NPC.CountNPCS(562) < num4)
                {
                    num9 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 562, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (NPC.CountNPCS(553) + NPC.CountNPCS(556) < num3)
                {
                    if (Main.rand.Next(4) == 0)
                    {
                        num9 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 556, 0, 0f, 0f, 0f, 0f, 255);
                    }
                    num10 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 553, 0, 0f, 0f, 0f, 0f, 255);
                }
                break;
            case 4:
                if (Main.rand.Next(10) == 0 && NPC.CountNPCS(570) < num8)
                {
                    num9 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 570, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (Main.rand.Next(12) == 0 && NPC.CountNPCS(559) < num5)
                {
                    num9 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 559, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (Main.rand.Next(6) == 0 && NPC.CountNPCS(562) < num4)
                {
                    num9 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 562, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (Main.rand.Next(3) == 0 && NPC.CountNPCS(572) < num7)
                {
                    num9 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 572, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (NPC.CountNPCS(553) < num3)
                {
                    num9 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 553, 0, 0f, 0f, 0f, 0f, 255);
                }
                break;
            case 5:
                if (Main.rand.Next(7) == 0 && NPC.CountNPCS(570) < num8)
                {
                    num9 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 570, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (Main.rand.Next(10) == 0 && NPC.CountNPCS(559) < num5)
                {
                    num9 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 559, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (Main.rand.Next(4) == 0 && NPC.CountNPCS(572) + NPC.CountNPCS(574) < num7)
                {
                    if (Main.rand.Next(2) == 0)
                    {
                        num9 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 572, 0, 0f, 0f, 0f, 0f, 255);
                    }
                    else
                    {
                        num9 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 574, 0, 0f, 0f, 0f, 0f, 255);
                    }
                }
                else if (NPC.CountNPCS(553) + NPC.CountNPCS(556) < num3)
                {
                    if (Main.rand.Next(3) == 0)
                    {
                        num9 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 556, 0, 0f, 0f, 0f, 0f, 255);
                    }
                    num10 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 553, 0, 0f, 0f, 0f, 0f, 255);
                }
                break;
            case 6:
                if (Main.rand.Next(7) == 0 && NPC.CountNPCS(570) < num8)
                {
                    num9 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 570, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (Main.rand.Next(17) == 0 && NPC.CountNPCS(568) < num6)
                {
                    num9 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 568, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (Main.rand.Next(5) == 0 && NPC.CountNPCS(572) + NPC.CountNPCS(574) < num7)
                {
                    if (Main.rand.Next(2) != 0)
                    {
                        num9 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 572, 0, 0f, 0f, 0f, 0f, 255);
                    }
                    else
                    {
                        num9 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 574, 0, 0f, 0f, 0f, 0f, 255);
                    }
                }
                else if (Main.rand.Next(9) == 0 && NPC.CountNPCS(559) < num5)
                {
                    num9 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 559, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (Main.rand.Next(3) == 0 && NPC.CountNPCS(562) < num4)
                {
                    num9 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 562, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (NPC.CountNPCS(553) + NPC.CountNPCS(556) < num3)
                {
                    if (Main.rand.Next(3) != 0)
                    {
                        num9 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 556, 0, 0f, 0f, 0f, 0f, 255);
                    }
                    num10 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 553, 0, 0f, 0f, 0f, 0f, 255);
                }
                break;
            case 7:
            {
                int num11;
                int num12;
                int num13;
                DD2Event.GetInvasionStatus(out num11, out num12, out num13, false);
                if ((!leftGate || Main.rand.Next(2) == 0) && (float)num13 > (float)num12 * 0.1f && !NPC.AnyNPCs(576))
                {
                    num9 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 576, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (Main.rand.Next(7) == 0 && NPC.CountNPCS(570) < num8)
                {
                    num9 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 570, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (Main.rand.Next(17) == 0 && NPC.CountNPCS(568) < num6)
                {
                    num9 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 568, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (Main.rand.Next(7) == 0 && NPC.CountNPCS(572) + NPC.CountNPCS(574) < num7)
                {
                    if (Main.rand.Next(3) != 0)
                    {
                        num9 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 572, 0, 0f, 0f, 0f, 0f, 255);
                    }
                    else
                    {
                        num9 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 574, 0, 0f, 0f, 0f, 0f, 255);
                    }
                }
                else if (Main.rand.Next(11) == 0 && NPC.CountNPCS(559) < num5)
                {
                    num9 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 559, 0, 0f, 0f, 0f, 0f, 255);
                }
                else if (NPC.CountNPCS(553) + NPC.CountNPCS(556) < num3)
                {
                    if (Main.rand.Next(2) == 0)
                    {
                        num9 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 556, 0, 0f, 0f, 0f, 0f, 255);
                    }
                    num10 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 553, 0, 0f, 0f, 0f, 0f, 255);
                }
                break;
            }
            default:
                num9 = NPC.NewNPC(DD2Event.GetSpawnSource_OldOnesArmy(), num, num2, 553, 0, 0f, 0f, 0f, 0f, 255);
                break;
            }
            if (Main.netMode == 2 && num9 < Main.maxNPCs)
            {
                NetMessage.SendData(23, -1, -1, null, num9, 0f, 0f, 0f, 0, 0, 0);
            }
            if (Main.netMode == 2 && num10 < Main.maxNPCs)
            {
                NetMessage.SendData(23, -1, -1, null, num10, 0f, 0f, 0f, 0, 0, 0);
            }
        }
References Terraria.Main.CurrentFrameFlags.ActivePlayersCount, Terraria.NPC.AnyNPCs(), Terraria.NPC.CountNPCS(), Terraria.GameContent.Events.DD2Event.GetInvasionStatus(), Terraria.GameContent.Events.DD2Event.GetSpawnSource_OldOnesArmy(), int, Terraria.Main.maxNPCs, Terraria.Main.netMode, Terraria.NPC.NewNPC(), Terraria.Main.rand, Terraria.NetMessage.SendData(), Terraria.NPC.waveNumber, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.GameContent.Events.DD2Event.SpawnMonsterFromGate().