Terraria Decompiled: Terraria.GameContent.Events.DD2Event.StartVictoryScene
StartVictoryScene()
static void Terraria.GameContent.Events.DD2Event.StartVictoryScene () inline static
Definition at line 461 of file DD2Event.cs.
        {
            DD2Event.WonThisRun = true;
            if (DD2Event._damageTracker != null)
            {
                DD2Event._damageTracker.Stop(true);
            }
            int num = NPC.FindFirstNPC(548);
            if (num == -1)
            {
                return;
            }
            Main.npc[num].ai[1] = 2f;
            Main.npc[num].ai[0] = 2f;
            Main.npc[num].netUpdate = true;
            for (int i = 0; i < Main.maxNPCs; i++)
            {
                if (Main.npc[i] != null && Main.npc[i].active && Main.npc[i].type == 549)
                {
                    Main.npc[i].ai[0] = 0f;
                    Main.npc[i].ai[1] = 1f;
                    Main.npc[i].netUpdate = true;
                }
            }
        }
References Terraria.GameContent.Events.DD2Event._damageTracker, Terraria.NPC.active, Terraria.NPC.ai, Terraria.NPC.FindFirstNPC(), Terraria.Main.maxNPCs, Terraria.NPC.netUpdate, Terraria.Main.npc, and Terraria.NPC.type.
Referenced by Terraria.GameContent.Events.DD2Event.Difficulty_1_GetRequiredWaveKills(), Terraria.GameContent.Events.DD2Event.Difficulty_2_GetRequiredWaveKills(), and Terraria.GameContent.Events.DD2Event.Difficulty_3_GetRequiredWaveKills().