Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.Features.DungeonPillar.Pillar
Pillar()
bool Terraria.GameContent.Generation.Dungeon.Features.DungeonPillar.Pillar (DungeonData data, int i, int j, ushort tileType, ushort wallType, bool generating = false) inline
Definition at line 36 of file DungeonPillar.cs.
        {
            UnifiedRandom genRand = WorldGen.genRand;
            DungeonPillarSettings dungeonPillarSettings = (DungeonPillarSettings)this.settings;
            int width = dungeonPillarSettings.Width;
            int height = dungeonPillarSettings.Height;
            bool crowningOnTop = dungeonPillarSettings.CrowningOnTop;
            bool crowningOnBottom = dungeonPillarSettings.CrowningOnBottom;
            bool crowningStopsAtPillar = dungeonPillarSettings.CrowningStopsAtPillar;
            int num = 3;
            int num2 = 0;
            this.Bounds.SetBounds(i, j, i, j);
            int num3 = width / 2;
            for (int k = 0; k < width; k++)
            {
                int num4 = i + k - width / 2;
                int num5 = j;
                int num6 = j;
                DungeonPillar.GenerateTileStrip(dungeonPillarSettings, true, out num5, out num6, num4, j, height, (int)tileType, (int)wallType, false, false);
                this.Bounds.UpdateBounds(num4, num5, num4, num6);
                if (crowningOnTop)
                {
                    int num7 = (crowningStopsAtPillar ? (num + 1) : 0);
                    if (k == 0)
                    {
                        DungeonPillar.GenerateTileStrip(dungeonPillarSettings, true, out num2, out num2, num4 - 1, num5 + num, num7, (int)tileType, (int)wallType, false, true);
                    }
                    else if (k == width - 1)
                    {
                        DungeonPillar.GenerateTileStrip(dungeonPillarSettings, true, out num2, out num2, num4 + 1, num5 + num, num7, (int)tileType, (int)wallType, false, true);
                    }
                }
                if (crowningOnBottom)
                {
                    int num8 = (crowningStopsAtPillar ? (num + 1) : 0);
                    if (k == 0)
                    {
                        DungeonPillar.GenerateTileStrip(dungeonPillarSettings, false, out num2, out num2, num4 - 1, num6 - num, num8, (int)tileType, (int)wallType, true, false);
                    }
                    else if (k == width - 1)
                    {
                        DungeonPillar.GenerateTileStrip(dungeonPillarSettings, false, out num2, out num2, num4 + 1, num6 - num, num8, (int)tileType, (int)wallType, true, false);
                    }
                }
            }
            this.Bounds.CalculateHitbox();
            return true;
        }
References Terraria.GameContent.Generation.Dungeon.Features.DungeonFeature.Bounds, Terraria.GameContent.Generation.Dungeon.DungeonBounds.CalculateHitbox(), Terraria.GameContent.Generation.Dungeon.Features.DungeonPillarSettings.CrowningOnBottom, Terraria.GameContent.Generation.Dungeon.Features.DungeonPillarSettings.CrowningOnTop, Terraria.GameContent.Generation.Dungeon.Features.DungeonPillarSettings.CrowningStopsAtPillar, Terraria.GameContent.Generation.Dungeon.Features.DungeonPillar.GenerateTileStrip(), Terraria.WorldGen.genRand, Terraria.GameContent.Generation.Dungeon.Features.DungeonPillarSettings.Height, int, Terraria.GameContent.Generation.Dungeon.DungeonBounds.SetBounds(), Terraria.GameContent.Generation.Dungeon.Features.DungeonFeature.settings, Terraria.GameContent.Generation.Dungeon.DungeonBounds.UpdateBounds(), and Terraria.GameContent.Generation.Dungeon.Features.DungeonPillarSettings.Width.
Referenced by Terraria.GameContent.Generation.Dungeon.Features.DungeonPillar.GenerateFeature().