Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.Features.DungeonPillar.GenerateTileStrip
GenerateTileStrip()
static void Terraria.GameContent.Generation.Dungeon.Features.DungeonPillar.GenerateTileStrip (DungeonPillarSettings pillarSettings, bool upwards, out int topY, out int bottomY, int placeX, int placeY, int pillarHeight, int tileType, int wallType, bool smoothTop, bool smoothBottom) inline static
Definition at line 86 of file DungeonPillar.cs.
        {
            PillarType pillarType = pillarSettings.PillarType;
            ushort num = (ushort)((pillarType == PillarType.Wall) ? wallType : tileType);
            bool flag = pillarType == PillarType.Wall;
            int num2 = (flag ? pillarSettings.OverridePaintWall : pillarSettings.OverridePaintTile);
            bool flag2 = pillarType == PillarType.BlockActuatedSolidTop || pillarType == PillarType.BlockActuatedSolidTopAndBottom;
            bool flag3 = pillarType == PillarType.BlockActuatedSolidBottom || pillarType == PillarType.BlockActuatedSolidTopAndBottom;
            bool flag4 = pillarType == PillarType.BlockActuated || pillarType == PillarType.BlockActuatedSolidTop || pillarType == PillarType.BlockActuatedSolidBottom || pillarType == PillarType.BlockActuatedSolidTopAndBottom;
            int num3 = pillarHeight;
            if (num3 == 0)
            {
                int num4 = 0;
                if (upwards)
                {
                    while (num4 > -100 && WorldGen.InWorld(placeX, placeY + num4, 10) && !Main.tile[placeX, placeY + num4].active())
                    {
                        num4--;
                    }
                    num3 = -num4;
                }
                else
                {
                    while (num4 < 100 && WorldGen.InWorld(placeX, placeY + num4, 10) && !Main.tile[placeX, placeY + num4].active())
                    {
                        num4++;
                    }
                    num3 = num4;
                    placeY += num3 - 1;
                }
            }
            topY = placeY;
            bottomY = placeY;
            if (num3 == 0)
            {
                return;
            }
            int num5 = -num3 + 1;
            int num6 = 0;
            if (upwards)
            {
                for (int i = num5; i <= num6; i++)
                {
                    int num7 = placeY + i;
                    if (num7 <= 10)
                    {
                        return;
                    }
                    Tile tile = Main.tile[placeX, num7];
                    if (!pillarSettings.AlwaysPlaceEntirePillar && tile.active())
                    {
                        return;
                    }
                    if (flag)
                    {
                        tile.wall = num;
                        if (num2 >= 0)
{
                            tile.wallColor((byte)num2);
                        }
                    }
                    else
                    {
                        tile.ClearTile();
                        tile.active(true);
                        tile.type = num;
                        if (num2 >= 0)
{
                            tile.color((byte)num2);
                        }
                        if ((i == num5 && smoothTop) || (i == num6 && smoothBottom))
{
                            Tile.SmoothSlope(placeX, num7, false, false);
                        }
                        if ((!flag2 || i >= num5 + 2) && (!flag3 || i <= num6 - 2) && flag4)
{
                            tile.inActive(true);
                        }
                    }
                    if (num7 < topY)
                    {
                        topY = num7;
                    }
                    if (num7 > bottomY)
                    {
                        bottomY = num7;
                    }
                }
                return;
            }
            for (int j = num6; j >= num5; j--)
            {
                int num8 = placeY + j;
                if (num8 >= Main.maxTilesY - 10)
                {
                    break;
                }
                Tile tile2 = Main.tile[placeX, num8];
                if (!pillarSettings.AlwaysPlaceEntirePillar && tile2.active())
                {
                    break;
                }
                if (flag)
                {
                    tile2.wall = num;
                    if (num2 >= 0)
                    {
                        tile2.wallColor((byte)num2);
                    }
                }
                else
                {
                    tile2.ClearTile();
                    tile2.active(true);
                    tile2.type = num;
                    if (num2 >= 0)
                    {
                        tile2.color((byte)num2);
                    }
                    if ((j == num5 && smoothTop) || (j == num6 && smoothBottom))
                    {
                        Tile.SmoothSlope(placeX, num8, false, false);
                    }
                    if ((!flag2 || j >= num5 + 2) && (!flag3 || j <= num6 - 2) && flag4)
                    {
                        tile2.inActive(true);
                    }
                }
                if (num8 < topY)
                {
                    topY = num8;
                }
                if (num8 > bottomY)
                {
                    bottomY = num8;
                }
            }
        }
References Terraria.Tile.active(), Terraria.GameContent.Generation.Dungeon.Features.DungeonPillarSettings.AlwaysPlaceEntirePillar, Terraria.Tile.ClearTile(), Terraria.Tile.color(), Terraria.Tile.inActive(), Terraria.WorldGen.InWorld(), Terraria.Main.maxTilesY, Terraria.GameContent.Generation.Dungeon.Features.DungeonPillarSettings.OverridePaintTile, Terraria.GameContent.Generation.Dungeon.Features.DungeonPillarSettings.PillarType, Terraria.Tile.SmoothSlope(), Terraria.Main.tile, and Terraria.Tile.wallColor().
Referenced by Terraria.GameContent.Generation.Dungeon.Features.DungeonPillar.Pillar().