Terraria Decompiled: Terraria.Initializers.LaunchInitializer.LoadServerParameters
LoadServerParameters()
static void Terraria.Initializers.LaunchInitializer.LoadServerParameters (Main game) inline static private
Definition at line 61 of file LaunchInitializer.cs.
        {
            try
            {
                string text;
                if ((text = LaunchInitializer.TryParameter(new string[] { "-forcepriority" })) != null)
                {
                    Process currentProcess = Process.GetCurrentProcess();
                    int num;
                    if (int.TryParse(text, out num))
                    {
                        switch (num)
{
                        case 0:
                            currentProcess.PriorityClass = ProcessPriorityClass.RealTime;
                            break;
                        case 1:
                            currentProcess.PriorityClass = ProcessPriorityClass.High;
                            break;
                        case 2:
                            currentProcess.PriorityClass = ProcessPriorityClass.AboveNormal;
                            break;
                        case 3:
                            currentProcess.PriorityClass = ProcessPriorityClass.Normal;
                            break;
                        case 4:
                            currentProcess.PriorityClass = ProcessPriorityClass.BelowNormal;
                            break;
                        case 5:
                            currentProcess.PriorityClass = ProcessPriorityClass.Idle;
                            break;
                        default:
                            currentProcess.PriorityClass = ProcessPriorityClass.High;
                            break;
                        }
                    }
                    else
                    {
                        currentProcess.PriorityClass = ProcessPriorityClass.High;
                    }
                }
                else
                {
                    Process.GetCurrentProcess().PriorityClass = ProcessPriorityClass.High;
                }
            }
            catch
            {
            }
            string text2;
            if ((text2 = LaunchInitializer.TryParameter(new string[] { "-maxplayers", "-players" })) != null)
            {
                int num2 = Convert.ToInt32(text2);
                if (num2 <= 255 && num2 >= 1)
                {
                    game.SetNetPlayers(num2);
                }
            }
            string text3;
            if ((text3 = LaunchInitializer.TryParameter(new string[] { "-pass", "-password" })) != null)
            {
                Netplay.ServerPassword = Main.ConvertFromSafeArgument(text3);
            }
            string text4;
            int num3;
            if ((text4 = LaunchInitializer.TryParameter(new string[] { "-lang" })) != null && int.TryParse(text4, out num3))
            {
                LanguageManager.Instance.SetLanguage(num3);
            }
            if ((text4 = LaunchInitializer.TryParameter(new string[] { "-language" })) != null)
            {
                LanguageManager.Instance.SetLanguage(text4);
            }
            string text5;
            if ((text5 = LaunchInitializer.TryParameter(new string[] { "-worldname" })) != null)
            {
                game.SetWorldName(text5);
            }
            string text6;
            if ((text6 = LaunchInitializer.TryParameter(new string[] { "-motd" })) != null)
            {
                game.NewMOTD(text6);
            }
            string text7;
            if ((text7 = LaunchInitializer.TryParameter(new string[] { "-banlist" })) != null)
            {
                Netplay.BanFilePath = text7;
            }
            if (LaunchInitializer.HasParameter(new string[] { "-autoshutdown" }))
            {
                game.EnableAutoShutdown();
            }
            string text8;
            if ((text8 = LaunchInitializer.TryParameter(new string[] { "-hosttoken" })) != null)
            {
                Netplay.HostToken = text8;
            }
            if (LaunchInitializer.HasParameter(new string[] { "-secure" }))
            {
                Netplay.SpamCheck = true;
            }
            string text9;
            if ((text9 = LaunchInitializer.TryParameter(new string[] { "-worldrollbackstokeep" })) != null)
            {
                game.setServerWorldRollbacks(text9);
            }
            string text10;
            if ((text10 = LaunchInitializer.TryParameter(new string[] { "-autocreate" })) != null)
            {
                game.autoCreate(text10);
            }
            if (LaunchInitializer.HasParameter(new string[] { "-noupnp" }))
            {
                Netplay.UseUPNP = false;
            }
            if (LaunchInitializer.HasParameter(new string[] { "-experimental" }))
            {
                Main.UseExperimentalFeatures = true;
            }
            string text11;
            if ((text11 = LaunchInitializer.TryParameter(new string[] { "-world" })) != null)
            {
                if (FileUtilities.Exists(text11, false) || !Main.autoGen)
                {
                    game.SetWorld(text11, false);
                }
                else
                {
                    new WorldFileData(text11, false).SetAsActive();
                    Main.autoGenFileLocation = text11;
                }
            }
            else if (SocialAPI.Mode == SocialMode.Steam && (text11 = LaunchInitializer.TryParameter(new string[] { "-cloudworld" })) != null)
            {
                if (FileUtilities.Exists(text11, true) || !Main.autoGen)
                {
                    game.SetWorld(text11, true);
                }
                else
                {
                    new WorldFileData(text11, true).SetAsActive();
                    Main.autoGenFileLocation = text11;
                }
            }
            string text12;
            if ((text12 = LaunchInitializer.TryParameter(new string[] { "-config" })) != null)
            {
                game.LoadDedConfig(text12);
            }
            string text13;
            if ((text13 = LaunchInitializer.TryParameter(new string[] { "-seed" })) != null)
            {
                Main.AutogenSeedName = text13;
            }
        }
References Terraria.Main.autoCreate(), Terraria.Main.autoGen, Terraria.Main.ConvertFromSafeArgument(), Terraria.Main.EnableAutoShutdown(), Terraria.Utilities.FileUtilities.Exists(), Terraria.Initializers.LaunchInitializer.HasParameter(), Terraria.Localization.LanguageManager.Instance, Terraria.Main.LoadDedConfig(), Terraria.Social.SocialAPI.Mode, Terraria.Main.NewMOTD(), System.Process, Terraria.IO.WorldFileData.SetAsActive(), Terraria.Localization.LanguageManager.SetLanguage(), Terraria.Main.SetNetPlayers(), Terraria.Main.setServerWorldRollbacks(), Terraria.Main.SetWorld(), Terraria.Main.SetWorldName(), System.text, System.Convert.ToInt32(), and Terraria.Initializers.LaunchInitializer.TryParameter().
Referenced by Terraria.Initializers.LaunchInitializer.LoadParameters().