Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateTileStrip
GenerateTileStrip()
static void Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateTileStrip (bool upwards, out int topY, out int bottomY, int placeX, int placeY, int pillarHeight, ushort pillarType, bool wall = false, bool actuated = false, int paint = -1, bool smoothTop = false, bool smoothBottom = false, bool solidTop = false) inline static private
Definition at line 414 of file DungeonUtils.cs.
        {
            topY = placeY;
            bottomY = placeY;
            int num = pillarHeight;
            if (num == -1)
            {
                int num2 = 0;
                if (upwards)
                {
                    while (num2 > -100 && WorldGen.InWorld(placeX, placeY + num2, 10) && !Main.tile[placeX, placeY + num2].active())
                    {
                        num2--;
                    }
                    num = -num2;
                }
                else
                {
                    while (num2 < 100 && WorldGen.InWorld(placeX, placeY + num2, 10) && !Main.tile[placeX, placeY + num2].active())
                    {
                        num2++;
                    }
                    num = num2;
                }
            }
            if (num == 0)
            {
                return;
            }
            int num3 = -num + 1;
            int num4 = 0;
            if (!upwards)
            {
                num3 = 0;
                num4 = num - 1;
            }
            for (int i = num3; i <= num4; i++)
            {
                int num5 = placeY + i;
                if (WorldGen.InWorld(placeX, num5, 10))
                {
                    Tile tile = Main.tile[placeX, num5];
                    if (wall)
                    {
                        tile.wall = pillarType;
                        if (paint >= 0)
{
                            tile.wallColor((byte)paint);
                        }
                    }
                    else
                    {
                        tile.ClearTile();
                        tile.active(true);
                        tile.type = pillarType;
                        if (paint >= 0)
{
                            tile.color((byte)paint);
                        }
                        if ((i == num3 && smoothTop) || (i == num4 && smoothBottom))
{
                            Tile.SmoothSlope(placeX, num5, false, false);
                        }
                        if ((!solidTop || i >= num3 + 2) && actuated)
{
                            tile.inActive(true);
                        }
                    }
                    if (num5 < topY)
                    {
                        topY = num5;
                    }
                    if (num5 > bottomY)
                    {
                        bottomY = num5;
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.Tile.ClearTile(), Terraria.Tile.color(), Terraria.Tile.inActive(), Terraria.WorldGen.InWorld(), Terraria.Tile.SmoothSlope(), Terraria.Main.tile, and Terraria.Tile.wallColor().
Referenced by Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateBottomWedge().