Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateShimmerPool
GenerateShimmerPool()
static void Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateShimmerPool (int x, int y, int outerShapeSize = 15) inline static
Definition at line 213 of file DungeonUtils.cs.
        {
            int num = 5;
            int num2 = Math.Max(1, outerShapeSize - num);
            Shapes.HalfCircle halfCircle = new Shapes.HalfCircle(outerShapeSize, true);
            Shapes.HalfCircle halfCircle2 = new Shapes.HalfCircle(num2, true);
            Point point = new Point(x, y + num2);
            WorldUtils.Gen(point, halfCircle, Actions.Chain(new GenAction[]
            {
                new Actions.SetTile(667, false, false, false)
            }));
            WorldUtils.Gen(new Point(point.X, point.Y - num), halfCircle2, Actions.Chain(new GenAction[]
            {
                new Actions.ClearTile(false),
                new Actions.SetLiquid(3, byte.MaxValue)
            }));
        }
References Terraria.WorldBuilding.Actions.Chain(), Terraria.WorldBuilding.WorldUtils.Gen(), System.Math.Max(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.