Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.DungeonUtils.SetOldManSpawnAndSpawnOldManIfDefaultDungeon
SetOldManSpawnAndSpawnOldManIfDefaultDungeon()
static Point Terraria.GameContent.Generation.Dungeon.DungeonUtils.SetOldManSpawnAndSpawnOldManIfDefaultDungeon (int x, int y, bool generating = false) inline static
Definition at line 1727 of file DungeonUtils.cs.
        {
            Point point = new Point(x, y);
            if (GenVars.CurrentDungeon == 0)
            {
                Main.dungeonX = point.X;
                Main.dungeonY = point.Y;
                if (generating)
                {
                    int num = NPC.NewNPC(new EntitySource_WorldGen(), Main.dungeonX * 16 + 8, Main.dungeonY * 16, 37, 0, 0f, 0f, 0f, 0f, 255);
                    Main.npc[num].homeless = false;
                    Main.npc[num].homeTileX = Main.dungeonX;
                    Main.npc[num].homeTileY = Main.dungeonY;
                    if (Main.onlyShimmerOceanWorldsGeneration)
                    {
                        Main.npc[num].GivenName = "Old Man James";
                    }
                }
            }
            return point;
        }
References Terraria.WorldBuilding.GenVars.CurrentDungeon, Terraria.Main.dungeonX, Terraria.Main.dungeonY, Terraria.NPC.GivenName, Terraria.NPC.homeless, Terraria.NPC.homeTileX, Terraria.NPC.homeTileY, Terraria.NPC.NewNPC(), Terraria.Main.npc, Terraria.Main.onlyShimmerOceanWorldsGeneration, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.Generation.Dungeon.Entrances.DomeDungeonEntrance.DomeEntrance(), Terraria.GameContent.Generation.Dungeon.Entrances.LegacyDungeonEntrance.LegacyEntrance(), and Terraria.GameContent.Generation.Dungeon.Entrances.TowerDungeonEntrance.TowerEntrance().