Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateDungeonStairs
GenerateDungeonStairs()
static void Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateDungeonStairs (DungeonData data, int i, int j, int direction, ushort tileType, ushort wallType, int depth = 100) inline static
Definition at line 1259 of file DungeonUtils.cs.
        {
            if (!WorldGen.InWorld(i, j, 20))
            {
                return;
            }
            int num = depth;
            int num2 = depth;
            int num3 = ((direction == 1) ? 1 : (-1));
            int num4 = 0;
            int num5 = i;
            while ((direction == 1) ? (num5 < i + num2) : (num5 > i - num2))
            {
                num4++;
                for (int k = j + num4; k < j + num; k++)
                {
                    if (WorldGen.InWorld(num5, k, 10) && !DungeonUtils.GenerateDungeonStairs_CanPlaceTile(num5, k + 5) && num > k)
                    {
                        num = k;
                        break;
                    }
                }
                num5 += num3;
            }
            num2 = num;
            depth = num;
            num4 = 0;
            int num6 = i;
            while ((direction == 1) ? (num6 < i + num2) : (num6 > i - num2))
            {
                num4++;
                for (int l = j + num4; l < j + depth; l++)
                {
                    if (WorldGen.InWorld(num6, l, 10) && l < DungeonCrawler.CurrentDungeonData.genVars.outerPotentialDungeonBounds.Top - 5)
                    {
                        Tile tile = Main.tile[num6, l];
                        tile.liquid = 0;
                        Main.tile[num6, l - 1].liquid = 0;
                        Main.tile[num6, l - 2].liquid = 0;
                        Main.tile[num6, l - 3].liquid = 0;
                        if (DungeonUtils.GenerateDungeonStairs_CanPlaceTile(num6, l))
{
                            bool flag = data.genVars.dungeonStyle.WallIsInStyle((int)tile.wall, false);
                            if (!flag)
{
                                using (List<DungeonGenerationStyleData>.Enumerator enumerator = data.genVars.dungeonGenerationStyles.GetEnumerator())
{
                                    while (enumerator.MoveNext())
{
                                        if (enumerator.Current.WallIsInStyle((int)tile.wall, false))
{
                                            flag = true;
                                            break;
                                        }
                                    }
                                }
                            }
                            if (flag)
{
                                if (tile.active())
{
                                    tile.active(true);
                                    tile.type = tileType;
                                    tile.Clear(TileDataType.Slope);
                                }
                                tile.wall = wallType;
                            }
                            else
{
                                tile.active(true);
                                tile.type = tileType;
                                tile.Clear(TileDataType.Slope);
                                if (l != j + num4)
{
                                    tile.wall = wallType;
                                }
                            }
                        }
                    }
                }
                num6 += num3;
            }
        }
References Terraria.Tile.active(), Terraria.Tile.Clear(), Terraria.GameContent.Generation.Dungeon.DungeonGenVars.dungeonGenerationStyles, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.dungeonStyle, Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateDungeonStairs_CanPlaceTile(), Terraria.GameContent.Generation.Dungeon.DungeonData.genVars, Terraria.WorldGen.InWorld(), Terraria.Tile.liquid, Terraria.Main.tile, Terraria.Tile.wall, and Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.WallIsInStyle().
Referenced by Terraria.GameContent.Generation.Dungeon.Entrances.DomeDungeonEntrance.DomeEntrance(), Terraria.GameContent.Generation.Dungeon.Entrances.LegacyDungeonEntrance.LegacyEntrance(), and Terraria.GameContent.Generation.Dungeon.Entrances.TowerDungeonEntrance.TowerEntrance().