Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.DungeonUtils.FirstSolid
FirstSolid()
static Point Terraria.GameContent.Generation.Dungeon.DungeonUtils.FirstSolid (bool ceiling, Point currentPoint, DungeonBounds bounds) inline static
Definition at line 495 of file DungeonUtils.cs.
        {
            int num = Main.maxTilesX * 5;
            for (;;)
            {
                num--;
                if (num <= 0)
                {
                    return currentPoint;
                }
                if (ceiling && WorldGen.SolidTileAllowTopSlope(currentPoint.X, currentPoint.Y))
                {
                    break;
                }
                if (!ceiling && WorldGen.SolidTileAllowBottomSlope(currentPoint.X, currentPoint.Y))
                {
                    return currentPoint;
                }
                if (ceiling)
                {
                    currentPoint.Y--;
                }
                else
                {
                    currentPoint.Y++;
                }
                if (currentPoint.Y <= 10 || currentPoint.Y >= Main.maxTilesY - 10 || (bounds != null && !bounds.Contains(currentPoint)))
                {
                    return currentPoint;
                }
            }
            return currentPoint;
        }
References Terraria.GameContent.Generation.Dungeon.DungeonBounds.Contains(), Terraria.Main.maxTilesY, Terraria.WorldGen.SolidTileAllowBottomSlope(), Terraria.WorldGen.SolidTileAllowTopSlope(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateHangingLeafCluster(), Terraria.GameContent.Generation.Dungeon.Rooms.LivingTreeDungeonRoom.GenerateLateDungeonFeaturesInRoom(), and Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalGroundFurniture.GroundFurniture_DualDungeons().