Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateDungeonStairs_CanPlaceTile
GenerateDungeonStairs_CanPlaceTile()
static bool Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateDungeonStairs_CanPlaceTile (int x, int y) inline static private
Definition at line 1344 of file DungeonUtils.cs.
        {
            if (y >= DungeonCrawler.CurrentDungeonData.genVars.outerPotentialDungeonBounds.Top - 5)
            {
                return false;
            }
            Tile tile = Main.tile[x, y];
            if (tile.active())
            {
                if (!WorldGen.CanKillTile(x, y))
                {
                    return false;
                }
                if (tile.type >= 0 && Main.tileFrameImportant[(int)tile.type])
                {
                    return false;
                }
            }
            return true;
        }
References Terraria.Tile.active(), Terraria.WorldGen.CanKillTile(), Terraria.GameContent.Generation.Dungeon.DungeonCrawler.CurrentDungeonData, Terraria.GameContent.Generation.Dungeon.DungeonData.genVars, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.outerPotentialDungeonBounds, Terraria.Main.tile, Terraria.Main.tileFrameImportant, Terraria.GameContent.Generation.Dungeon.DungeonBounds.Top, and Terraria.Tile.type.
Referenced by Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateDungeonStairs().