Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.DungeonUtils.IsConsideredDungeonTile
IsConsideredDungeonTile()
static bool Terraria.GameContent.Generation.Dungeon.DungeonUtils.IsConsideredDungeonTile (int tileType, bool allDungeons = false) inline static
Definition at line 1919 of file DungeonUtils.cs.
        {
            if (tileType > 0 && Main.tileDungeon[tileType])
            {
                return true;
            }
            if (allDungeons)
            {
                for (int i = 0; i < GenVars.dungeonGenVars.Count; i++)
                {
                    if (GenVars.dungeonGenVars[i].isDungeonTile[tileType])
                    {
                        return true;
                    }
                }
            }
            else if (GenVars.CurrentDungeonGenVars.isDungeonTile[tileType])
            {
                return true;
            }
            return false;
        }
References System.Collections.Generic.List< T >.Count, Terraria.WorldBuilding.GenVars.CurrentDungeonGenVars, Terraria.WorldBuilding.GenVars.dungeonGenVars, and Terraria.Main.tileDungeon.
Referenced by Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalBookshelves.Bookshelves(), Terraria.WorldGen.CanBeClearedDuringGeneration(), Terraria.WorldGen.Cavinator(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalDoors.Doors(), Terraria.WorldGen.GetLeftMostDungeonTile(), Terraria.WorldGen.GetRightMostDungeonTile(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalLights.Lights(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalLights.Lights_GenerateSwitch(), Terraria.GameContent.Generation.Dungeon.Features.DungeonPitTrap.PitTrap(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalPlatforms.Platforms(), and Terraria.Player.Spawn_IsAreaValidSpawn().