Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.DungeonUtils.RoomCanBeChosen
RoomCanBeChosen()
static bool Terraria.GameContent.Generation.Dungeon.DungeonUtils.RoomCanBeChosen (DungeonRoom room, DungeonRoomSearchSettings settings) inline static
Definition at line 1871 of file DungeonUtils.cs.
        {
            if (room == null)
            {
                return false;
            }
            if (settings.ProgressionStage != null)
            {
                int progressionStage = room.settings.ProgressionStage;
                int value = settings.ProgressionStage.Value;
                switch (settings.ProgressionStageCheck)
                {
                case ProgressionStageCheck.Equals:
                    if (progressionStage != value)
                    {
                        return false;
                    }
                    break;
                case ProgressionStageCheck.GreaterThenOrEqualTo:
                    if (progressionStage < value)
                    {
                        return false;
                    }
                    break;
                case ProgressionStageCheck.LesserThenOrEqualTo:
                    if (progressionStage > value)
                    {
                        return false;
                    }
                    break;
                }
            }
            DungeonRoom excludedRoom = settings.ExcludedRoom;
            if (excludedRoom != null)
            {
                if (excludedRoom == room)
                {
                    return false;
                }
                if (settings.MaximumDistance != null && room.Center.ToVector2().Distance(excludedRoom.Center.ToVector2()) >= (float)settings.MaximumDistance.Value)
                {
                    return false;
                }
            }
            return true;
        }
References Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.Center, Terraria.GameContent.Generation.Dungeon.DungeonRoomSearchSettings.ExcludedRoom, Terraria.GameContent.Generation.Dungeon.DungeonRoomSearchSettings.MaximumDistance, Terraria.GameContent.Generation.Dungeon.DungeonRoomSearchSettings.ProgressionStage, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.ProgressionStage, Terraria.GameContent.Generation.Dungeon.DungeonRoomSearchSettings.ProgressionStageCheck, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.settings, and System.value.
Referenced by Terraria.GameContent.Generation.Dungeon.DungeonUtils.GetAllRoomsInSpots(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GetAllRoomsNearSpot(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GetClosestRoomTo(), and Terraria.GameContent.Generation.Dungeon.DungeonData.IsAnyRoomInSpot().