Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.DungeonUtils.ChangeTileType
ChangeTileType()
static void Terraria.GameContent.Generation.Dungeon.DungeonUtils.ChangeTileType (Tile tile, ushort tileType, bool resetTile, int paint = -1) inline static
Definition at line 1668 of file DungeonUtils.cs.
        {
            if (resetTile)
            {
                tile.ClearEverything();
            }
            tile.active(true);
            tile.Clear(TileDataType.Slope);
            tile.type = tileType;
            if (paint > -1)
            {
                tile.color((byte)paint);
            }
        }
References Terraria.Tile.active(), Terraria.Tile.Clear(), Terraria.Tile.ClearEverything(), and Terraria.Tile.color().
Referenced by Terraria.GameContent.Generation.Dungeon.Rooms.BiomeRuggedDungeonRoom.BiomeRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeSquareDungeonRoom.BiomeRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeStructuredDungeonRoom.BiomeRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeDungeonRoom.BiomeRoom_GrassySurface(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeDungeonRoom.BiomeRoom_SandySurface(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeDungeonRoom.BiomeRoom_SnowySurface(), Terraria.GameContent.Generation.Dungeon.Halls.DungeonHall.GenerateDungeonSquareHall(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.GenerateDungeonSquareRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.GenerateDungeonSquareRoom(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateHangingLeafCluster(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateRockPlatform(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateSpeleothem(), Terraria.GameContent.Generation.Dungeon.Halls.LegacyDungeonHall.LegacyHall(), Terraria.GameContent.Generation.Dungeon.Halls.LegacyEntranceDungeonHall.LegacyHall(), Terraria.GameContent.Generation.Dungeon.Rooms.LegacyDungeonRoom.LegacyRoom(), Terraria.GameContent.Generation.Dungeon.Features.DungeonPitTrap.PitTrap(), and Terraria.GameContent.Generation.Dungeon.Entrances.TowerDungeonEntrance.TowerEntrance().