Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.DungeonUtils.GetAllRoomsNearSpot
GetAllRoomsNearSpot()
static List< DungeonRoom > Terraria.GameContent.Generation.Dungeon.DungeonUtils.GetAllRoomsNearSpot (List< DungeonRoom > roomsToCheck, int x, int y, DungeonRoomSearchSettings settings) inline static
Definition at line 1838 of file DungeonUtils.cs.
        {
            List<DungeonRoom> list = new List<DungeonRoom>();
            for (int i = 0; i < roomsToCheck.Count; i++)
            {
                DungeonRoom dungeonRoom = roomsToCheck[i];
                if (DungeonUtils.RoomCanBeChosen(dungeonRoom, settings) && dungeonRoom.OuterBounds.ContainsWithFluff(x, y, settings.Fluff))
                {
                    list.Add(dungeonRoom);
                }
            }
            return list;
        }
References System.Collections.Generic.List< T >.Add(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.ContainsWithFluff(), System.Collections.Generic.List< T >.Count, Terraria.GameContent.Generation.Dungeon.DungeonRoomSearchSettings.Fluff, System.list, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.OuterBounds, and Terraria.GameContent.Generation.Dungeon.DungeonUtils.RoomCanBeChosen().