Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateSpeleothem
GenerateSpeleothem()
static void Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateSpeleothem (DungeonData data, UnifiedRandom genRand, int x, int y, int width, int height = -1, ushort tileType = 1, int paint = -1) inline static
Definition at line 1626 of file DungeonUtils.cs.
        {
            if (width % 2 == 1)
            {
                width++;
            }
            int num = width / 2;
            if (height <= -1)
            {
                height = width * 2 + genRand.Next(2);
            }
            int num2 = height / 2;
            y -= num2;
            if (!Main.tile[x, y].active())
            {
                y++;
            }
            for (int i = 0; i < data.dungeonDoorData.Count; i++)
            {
                if (data.dungeonDoorData[i].Position.ToVector2().Distance(new Vector2((float)x, (float)y)) <= 5f)
                {
                    return;
                }
            }
            for (int j = 0; j <= width; j++)
            {
                int num3 = x + j - num;
                int num4 = (int)Utils.WrappedLerp(1f, (float)height, (float)j / (float)width);
                if (genRand.Next(2) == 0)
                {
                    num4 += 2;
                }
                int num5 = (height - num4) / 2;
                for (int k = 0; k < num4; k++)
                {
                    int num6 = y + k + num5;
                    DungeonUtils.ChangeTileType(Main.tile[num3, num6], tileType, false, paint);
                }
            }
        }
References Terraria.Tile.active(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.ChangeTileType(), Terraria.GameContent.Generation.Dungeon.DungeonData.dungeonDoorData, int, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.tile, and Terraria.Utils.WrappedLerp().
Referenced by Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateSpeleothemsInArea().