Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.DungeonUtils.CalculatePlatformsAndDoorsOnEdgesOfRoom
CalculatePlatformsAndDoorsOnEdgesOfRoom()
static void Terraria.GameContent.Generation.Dungeon.DungeonUtils.CalculatePlatformsAndDoorsOnEdgesOfRoom (DungeonData dungeonData, DungeonBounds innerBounds, DungeonGenerationStyleData styleData, int? doorFluff = null, int? platformFluff = null) inline static
Definition at line 20 of file DungeonUtils.cs.
        {
            UnifiedRandom genRand = WorldGen.genRand;
            if (styleData == null)
            {
                if (!WorldGen.InWorld(innerBounds.Center.X, innerBounds.Center.Y, 5))
                {
                    return;
                }
                Tile tile = Main.tile[innerBounds.Center.X, innerBounds.Center.Y];
                styleData = DungeonGenerationStyles.GetStyleForWall(dungeonData.genVars.dungeonGenerationStyles, (int)tile.wall);
                if (styleData == null && tile.active())
                {
                    styleData = DungeonGenerationStyles.GetStyleForTile(dungeonData.genVars.dungeonGenerationStyles, (int)tile.type);
                }
                if (styleData == null)
                {
                    styleData = dungeonData.genVars.dungeonStyle;
                }
            }
            bool flag = styleData.Style == 0;
            ushort brickTileType = styleData.BrickTileType;
            ushort brickWallType = styleData.BrickWallType;
            int num = Math.Max(5, innerBounds.Left);
            int num2 = Math.Min(Main.maxTilesX - 5, innerBounds.Right);
            int num3 = Math.Max(5, innerBounds.Top);
            int num4 = Math.Min(Main.maxTilesY - 5, innerBounds.Bottom);
            bool flag2 = false;
            bool flag3 = false;
            for (int i = num; i <= num2; i++)
            {
                if (!flag2 && !Main.tile[i, num3 - 1].active())
                {
                    DungeonPlatformData dungeonPlatformData = new DungeonPlatformData
                    {
                        Position = new Point(i, num3 - 1),
                        InAHallway = false,
                        OverrideStyle = new int?(styleData.GetPlatformStyle(genRand))
                    };
                    if (platformFluff != null)
                    {
                        dungeonPlatformData.OverrideHeightFluff = new int?(platformFluff.Value);
                    }
                    dungeonData.dungeonPlatformData.Add(dungeonPlatformData);
                    flag2 = true;
                }
                if (!flag3 && !Main.tile[i, num4 + 1].active())
                {
                    DungeonPlatformData dungeonPlatformData2 = new DungeonPlatformData
                    {
                        Position = new Point(i, num4 + 1),
                        InAHallway = false,
                        OverrideStyle = new int?(styleData.GetPlatformStyle(genRand))
                    };
                    if (platformFluff != null)
                    {
                        dungeonPlatformData2.OverrideHeightFluff = new int?(platformFluff.Value);
                    }
                    dungeonData.dungeonPlatformData.Add(dungeonPlatformData2);
                    flag3 = true;
                }
                if (flag2 && flag3)
                {
                    break;
                }
            }
            if (styleData.DoorItemTypes != null)
            {
                int num5 = ((flag || styleData.DoorItemTypes.Length == 0) ? (-1) : styleData.DoorItemTypes[genRand.Next(styleData.DoorItemTypes.Length)]);
                bool flag4 = false;
                bool flag5 = false;
                for (int j = num3; j <= num4; j++)
                {
                    if (!flag4 && !Main.tile[num - 1, j].active())
                    {
                        bool flag6 = doorFluff != null && doorFluff.Value == 0;
                        DungeonDoorData dungeonDoorData = new DungeonDoorData
{
                            OverrideBrickTileType = new ushort?(brickTileType),
                            OverrideBrickWallType = new ushort?(brickWallType),
                            Position = new Point(num - 1, j),
                            Direction = -1,
                            InAHallway = false,
                            SkipOtherDoorsCheck = flag6,
                            SkipSpaceCheck = flag6,
                            AlwaysClearArea = true
                        };
                        if (doorFluff != null)
{
                            dungeonDoorData.OverrideWidthFluff = new int?(doorFluff.Value);
                        }
                        if (num5 >= 0)
{
                            PlacementDetails placementDetails = ItemID.Sets.DerivedPlacementDetails[num5];
                            dungeonDoorData.OverrideStyle = new int?((int)placementDetails.tileStyle);
                        }
                        dungeonData.dungeonDoorData.Add(dungeonDoorData);
                        flag4 = true;
                    }
                    if (!flag5 && !Main.tile[num2 + 1, j].active())
                    {
                        bool flag7 = doorFluff != null && doorFluff.Value == 0;
                        DungeonDoorData dungeonDoorData2 = new DungeonDoorData
{
                            OverrideBrickTileType = new ushort?(brickTileType),
                            OverrideBrickWallType = new ushort?(brickWallType),
                            Position = new Point(num2 + 1, j),
                            Direction = 1,
                            InAHallway = false,
                            SkipOtherDoorsCheck = flag7,
                            SkipSpaceCheck = flag7,
                            AlwaysClearArea = true
                        };
                        if (doorFluff != null)
{
                            dungeonDoorData2.OverrideWidthFluff = new int?(doorFluff.Value);
                        }
                        if (num5 >= 0)
{
                            PlacementDetails placementDetails2 = ItemID.Sets.DerivedPlacementDetails[num5];
                            dungeonDoorData2.OverrideStyle = new int?((int)placementDetails2.tileStyle);
                        }
                        dungeonData.dungeonDoorData.Add(dungeonDoorData2);
                        flag5 = true;
                    }
                    if (flag4 && flag5)
                    {
                        break;
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.Bottom, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.BrickTileType, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.BrickWallType, Terraria.GameContent.Generation.Dungeon.DungeonBounds.Center, Terraria.ID.ItemID.Sets.DerivedPlacementDetails, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.DoorItemTypes, Terraria.GameContent.Generation.Dungeon.DungeonData.dungeonDoorData, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.dungeonGenerationStyles, Terraria.GameContent.Generation.Dungeon.DungeonData.dungeonPlatformData, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.dungeonStyle, Terraria.WorldGen.genRand, Terraria.GameContent.Generation.Dungeon.DungeonData.genVars, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.GetPlatformStyle(), Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyles.GetStyleForTile(), Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyles.GetStyleForWall(), int, Terraria.WorldGen.InWorld(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.Left, System.Math.Max(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, System.Math.Min(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.Right, Terraria.Main.tile, Terraria.DataStructures.PlacementDetails.tileStyle, Terraria.GameContent.Generation.Dungeon.DungeonBounds.Top, Terraria.Tile.type, Terraria.Tile.wall, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.Generation.Dungeon.Rooms.BiomeDungeonRoom.CalculatePlatformsAndDoors(), and Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.CalculatePlatformsAndDoors().