Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateRockPlatform
GenerateRockPlatform()
static void Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateRockPlatform (UnifiedRandom genRand, int x, int y, int width, ushort tileType, int paint = -1) inline static
Definition at line 1457 of file DungeonUtils.cs.
        {
            int num = width / 2;
            int num2 = Math.Max(2, num + genRand.Next(2));
            for (int i = 0; i < width; i++)
            {
                int num3 = x + i - num;
                int num4 = num2;
                if (i == 0 || i == width - 1)
                {
                    num4 = Math.Max(1, num4 / 2);
                }
                else if (i == 1 || i == width - 2)
                {
                    num4 = Math.Max(2, (int)((float)num4 * 0.66f));
                }
                for (int j = 0; j < num4; j++)
                {
                    int num5 = y + j;
                    DungeonUtils.ChangeTileType(Main.tile[num3, num5], tileType, false, paint);
                }
            }
        }
References Terraria.GameContent.Generation.Dungeon.DungeonUtils.ChangeTileType(), System.Math.Max(), Terraria.Utilities.UnifiedRandom.Next(), and Terraria.Main.tile.
Referenced by Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateFloatingRocksInArea().