Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateDungeonTree
GenerateDungeonTree()
static void Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateDungeonTree (DungeonData data, int x, int y, int attachmentY, bool generateRoots = true) inline static
Definition at line 590 of file DungeonUtils.cs.
        {
            if (!WorldGen.InWorld(x, y, 20))
            {
                return;
            }
            int num = y;
            while (Main.tile[x, num].active() || Main.tile[x, num].wall > 0 || Main.tile[x, num - 1].active() || Main.tile[x, num - 1].wall > 0 || Main.tile[x, num - 2].active() || Main.tile[x, num - 2].wall > 0 || Main.tile[x, num - 3].active() || Main.tile[x, num - 3].wall > 0 || Main.tile[x, num - 4].active() || Main.tile[x, num - 4].wall > 0)
            {
                num--;
                if (num < 50)
                {
                    break;
                }
            }
            if (num > 50)
            {
                DungeonUtils.GrowDungeonTree(data, x, num, attachmentY, false, generateRoots);
            }
        }
References Terraria.Tile.active(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GrowDungeonTree(), Terraria.WorldGen.InWorld(), Terraria.Main.tile, and Terraria.Tile.wall.
Referenced by Terraria.GameContent.Generation.Dungeon.Entrances.DomeDungeonEntrance.DomeEntrance(), Terraria.GameContent.Generation.Dungeon.Entrances.LegacyDungeonEntrance.LegacyEntrance(), and Terraria.GameContent.Generation.Dungeon.Entrances.TowerDungeonEntrance.TowerEntrance().