Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateSpeleothemsInArea
GenerateSpeleothemsInArea() [3/3]
static void Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateSpeleothemsInArea (DungeonData data, int x, int y, int width, int height, int maxSpeleothems, ushort tileType, int paint = -1, int speleothemWidth = -1, int speleothemHeight = -1) inline static
Definition at line 1494 of file DungeonUtils.cs.
        {
            UnifiedRandom genRand = WorldGen.genRand;
            int i = 1;
            int num = maxSpeleothems - 1;
            int num2 = 100;
            int num3 = width / 2;
            int num4 = y + height;
            int num5 = y + height / 2;
            int num6 = genRand.Next(2);
            if (speleothemWidth <= -1)
            {
                speleothemWidth = (int)Math.Max(5f, (float)width / (float)num);
            }
            if (speleothemHeight <= -1)
            {
                speleothemHeight = height / 4;
            }
            while (i < num)
            {
                num2--;
                if (num2 <= 0)
                {
                    break;
                }
                int num7 = speleothemWidth + genRand.Next(3);
                int num8 = x + (int)((float)width * ((float)i / (float)(num - 1)));
                int num9 = num5;
                int num10 = num8;
                int num11 = num9;
                bool flag = (i + num6) % 2 == 0;
                if (genRand.Next(3) == 0)
                {
                    flag = !flag;
                }
                if (flag)
                {
                    Tile tile = Main.tile[num8, num9];
                    int num12 = Math.Max((int)((float)width * 1.5f), (int)((float)height * 1.5f));
                    while (!tile.active())
                    {
                        if (num9 >= num4)
{
                            break;
                        }
                        num12--;
                        if (num12 <= 0)
{
                            break;
                        }
                        num9++;
                        tile = Main.tile[num8, num9];
                    }
                }
                else
                {
                    Tile tile2 = Main.tile[num8, num9];
                    int num13 = Math.Max((int)((float)width * 1.5f), (int)((float)height * 1.5f));
                    while (!tile2.active() && num9 > y)
                    {
                        num13--;
                        if (num13 <= 0)
{
                            break;
                        }
                        num9--;
                        tile2 = Main.tile[num8, num9];
                    }
                }
                bool flag2 = true;
                if (flag2 && Math.Abs(num5 - num9) < 10)
                {
                    flag2 = false;
                }
                if (flag2)
                {
                    DungeonUtils.GenerateSpeleothem(data, genRand, num8, num9, num7, speleothemHeight + genRand.Next(3), tileType, paint);
                }
                if (genRand.Next(3) == 0)
                {
                    num7 = speleothemWidth + genRand.Next(3);
                    num8 = num10;
                    num9 = num11;
                    if (!flag)
                    {
                        Tile tile3 = Main.tile[num8, num9];
                        int num14 = Math.Max((int)((float)width * 1.5f), (int)((float)height * 1.5f));
                        while (!tile3.active())
{
                            if (num9 >= num4)
{
                                break;
                            }
                            num14--;
                            if (num14 <= 0)
{
                                break;
                            }
                            num9++;
                            tile3 = Main.tile[num8, num9];
                        }
                    }
                    else
                    {
                        Tile tile4 = Main.tile[num8, num9];
                        int num15 = Math.Max((int)((float)width * 1.5f), (int)((float)height * 1.5f));
                        while (!tile4.active() && num9 > y)
{
                            num15--;
                            if (num15 <= 0)
{
                                break;
                            }
                            num9--;
                            tile4 = Main.tile[num8, num9];
                        }
                    }
                    flag2 = true;
                    if (flag2 && Math.Abs(num5 - num9) < 10)
                    {
                        flag2 = false;
                    }
                    if (flag2)
                    {
                        DungeonUtils.GenerateSpeleothem(data, genRand, num8, num9, num7, speleothemHeight + genRand.Next(3), tileType, paint);
                    }
                }
                i++;
            }
        }
References System.Math.Abs(), Terraria.Tile.active(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateSpeleothem(), Terraria.WorldGen.genRand, int, System.Math.Max(), Terraria.Utilities.UnifiedRandom.Next(), and Terraria.Main.tile.