Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.DungeonUtils.CalculatePlatformAndDoorsOnHallway
CalculatePlatformAndDoorsOnHallway()
static void Terraria.GameContent.Generation.Dungeon.DungeonUtils.CalculatePlatformAndDoorsOnHallway (DungeonData dungeonData, Vector2D hallwayPoint, double hallwayDirectionY, DungeonGenerationStyleData styleData, double doorVariance = 0::1) inline static
Definition at line 154 of file DungeonUtils.cs.
        {
            UnifiedRandom genRand = WorldGen.genRand;
            if (styleData == null)
            {
                if (!WorldGen.InWorld((int)hallwayPoint.X, (int)hallwayPoint.Y, 5))
                {
                    return;
                }
                Tile tile = Main.tile[(int)hallwayPoint.X, (int)hallwayPoint.Y];
                styleData = DungeonGenerationStyles.GetStyleForWall(dungeonData.genVars.dungeonGenerationStyles, (int)tile.wall);
                if (styleData == null && tile.active())
                {
                    styleData = DungeonGenerationStyles.GetStyleForTile(dungeonData.genVars.dungeonGenerationStyles, (int)tile.type);
                }
                if (styleData == null)
                {
                    styleData = dungeonData.genVars.dungeonStyle;
                }
            }
            bool flag = styleData.Style == 0;
            ushort brickTileType = styleData.BrickTileType;
            ushort brickWallType = styleData.BrickWallType;
            if (Math.Abs(hallwayDirectionY) <= doorVariance)
            {
                if (styleData.DoorItemTypes != null)
                {
                    int num = ((flag || styleData.DoorItemTypes.Length == 0) ? (-1) : styleData.DoorItemTypes[genRand.Next(styleData.DoorItemTypes.Length)]);
                    DungeonDoorData dungeonDoorData = new DungeonDoorData
                    {
                        OverrideBrickTileType = new ushort?(brickTileType),
                        OverrideBrickWallType = new ushort?(brickWallType),
                        Position = hallwayPoint.ToPoint(),
                        Direction = 0,
                        InAHallway = true,
                        AlwaysClearArea = true
                    };
                    if (num >= 0)
                    {
                        PlacementDetails placementDetails = ItemID.Sets.DerivedPlacementDetails[num];
                        dungeonDoorData.OverrideStyle = new int?((int)placementDetails.tileStyle);
                    }
                    dungeonData.dungeonDoorData.Add(dungeonDoorData);
                    return;
                }
            }
            else
            {
                DungeonPlatformData dungeonPlatformData = new DungeonPlatformData
                {
                    Position = hallwayPoint.ToPoint(),
                    InAHallway = true,
                    OverrideStyle = new int?(styleData.GetPlatformStyle(genRand))
                };
                dungeonData.dungeonPlatformData.Add(dungeonPlatformData);
            }
        }
References System.Math.Abs(), Terraria.Tile.active(), Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.BrickTileType, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.BrickWallType, Terraria.ID.ItemID.Sets.DerivedPlacementDetails, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.DoorItemTypes, Terraria.GameContent.Generation.Dungeon.DungeonData.dungeonDoorData, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.dungeonGenerationStyles, Terraria.GameContent.Generation.Dungeon.DungeonData.dungeonPlatformData, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.dungeonStyle, Terraria.WorldGen.genRand, Terraria.GameContent.Generation.Dungeon.DungeonData.genVars, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.GetPlatformStyle(), Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyles.GetStyleForTile(), Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyles.GetStyleForWall(), int, Terraria.WorldGen.InWorld(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.tile, Terraria.DataStructures.PlacementDetails.tileStyle, Terraria.Tile.type, Terraria.Tile.wall, ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.GameContent.Generation.Dungeon.Halls.LegacyDungeonHall.CalculatePlatformsAndDoors(), Terraria.GameContent.Generation.Dungeon.Halls.RegularDungeonHall.CalculatePlatformsAndDoors(), Terraria.GameContent.Generation.Dungeon.Halls.SineDungeonHall.CalculatePlatformsAndDoors(), and Terraria.GameContent.Generation.Dungeon.Halls.StairwellDungeonHall.CalculatePlatformsAndDoors().