Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.DungeonUtils.GrowDungeonTree_MakePassage
GrowDungeonTree_MakePassage()
static void Terraria.GameContent.Generation.Dungeon.DungeonUtils.GrowDungeonTree_MakePassage (DungeonData data, int j, int attachmentY, int width, ref int minimumLeft, ref int minimumRight, bool noSecretRoom = false) inline static private
Definition at line 1104 of file DungeonUtils.cs.
        {
            UnifiedRandom genRand = WorldGen.genRand;
            int num = minimumLeft;
            int num2 = minimumRight;
            int num3 = (minimumLeft + minimumRight) / 2;
            int num4 = 5;
            int num5 = j - 6;
            int num6 = 0;
            bool flag = true;
            genRand.Next(5, 16);
            PlacementDetails placementDetails = ItemID.Sets.DerivedPlacementDetails[data.platformItemType];
            int tileType = placementDetails.tileType;
            short tileStyle = placementDetails.tileStyle;
            for (;;)
            {
                num5++;
                if (num5 > attachmentY)
                {
                    break;
                }
                int num7 = (minimumLeft + minimumRight) / 2;
                int num8 = 1;
                if (num5 > j && width <= 4)
                {
                    num8++;
                }
                for (int i = minimumLeft - num8; i <= minimumRight + num8; i++)
                {
                    if (i > num7 - 2 && i <= num7 + 1)
                    {
                        if (num5 > j - 4)
{
                            if (Main.tile[i, num5].type != 19 && Main.tile[i, num5].type != 15 && Main.tile[i, num5].type != 304 && Main.tile[i, num5].type != 21 && Main.tile[i, num5].type != 10 && Main.tile[i, num5 - 1].type != 15 && Main.tile[i, num5 - 1].type != 304 && Main.tile[i, num5 - 1].type != 21 && Main.tile[i, num5 - 1].type != 10 && Main.tile[i, num5 + 1].type != 10)
{
                                Main.tile[i, num5].ClearTileAndPaint();
                            }
                            if (!DungeonUtils.IsConsideredDungeonWall((int)Main.tile[i, num5].wall, false))
{
                                Main.tile[i, num5].wall = 244;
                            }
                            if (!DungeonUtils.IsConsideredDungeonWall((int)Main.tile[i - 1, num5].wall, false) && (Main.tile[i - 1, num5].wall > 0 || (double)num5 >= Main.worldSurface))
{
                                Main.tile[i - 1, num5].wall = 244;
                            }
                            if (!DungeonUtils.IsConsideredDungeonWall((int)Main.tile[i + 1, num5].wall, false) && (Main.tile[i + 1, num5].wall > 0 || (double)num5 >= Main.worldSurface))
{
                                Main.tile[i + 1, num5].wall = 244;
                            }
                            if (num5 == j && i > num7 - 2 && i <= num7 + 1)
{
                                Main.tile[i, num5 + 1].ClearTileAndPaint();
                                WorldGen.PlaceTile(i, num5 + 1, 19, true, false, -1, 23);
                            }
                        }
                    }
                    else
                    {
                        if (Main.tile[i, num5].type != 15 && Main.tile[i, num5].type != 304 && Main.tile[i, num5].type != 21 && Main.tile[i, num5].type != 10 && Main.tile[i - 1, num5].type != 10 && Main.tile[i + 1, num5].type != 10)
{
                            if (!DungeonUtils.IsConsideredDungeonWall((int)Main.tile[i, num5].wall, false))
{
                                Main.tile[i, num5].type = 191;
                                Main.tile[i, num5].active(true);
                                Main.tile[i, num5].Clear(TileDataType.Slope);
                            }
                            if (Main.tile[i - 1, num5].type == 40)
{
                                Main.tile[i - 1, num5].type = 0;
                            }
                            if (Main.tile[i + 1, num5].type == 40)
{
                                Main.tile[i + 1, num5].type = 0;
                            }
                        }
                        if (num5 <= j && num5 > j - 4 && i > minimumLeft - num8 && i <= minimumRight + num8 - 1)
{
                            Main.tile[i, num5].wall = 244;
                        }
                    }
                    if (!WorldGen.isGeneratingOrLoadingWorld)
                    {
                        WorldGen.SquareTileFrame(i, num5, true);
                        WorldGen.SquareWallFrame(i, num5, true);
                    }
                }
                num6++;
                if (num6 >= 6)
                {
                    num6 = 0;
                    int num9 = genRand.Next(3);
                    if (num9 == 0)
                    {
                        num9 = -1;
                    }
                    if (flag)
                    {
                        num9 = 2;
                    }
                    if (num9 == -1 && Main.tile[minimumLeft - num4, num5].wall == 244)
                    {
                        num9 = 1;
                    }
                    else if (num9 == 1 && Main.tile[minimumRight + num4, num5].wall == 244)
                    {
                        num9 = -1;
                    }
                    if (num9 == 2)
                    {
                        flag = false;
                        ushort num10 = 19;
                        int num11 = 23;
                        bool flag2 = false;
                        if (DungeonUtils.IsConsideredDungeonWall((int)Main.tile[minimumLeft, num5 + 1].wall, false) || DungeonUtils.IsConsideredDungeonWall((int)Main.tile[minimumLeft + 1, num5 + 1].wall, false) || DungeonUtils.IsConsideredDungeonWall((int)Main.tile[minimumLeft + 2, num5 + 1].wall, false))
{
                            flag2 = true;
                            num10 = (ushort)tileType;
                            num11 = (int)tileStyle;
                        }
                        if (WorldGen.SolidTile(minimumLeft - 1, num5 + 1, false) || WorldGen.SolidTile(minimumRight + 1, num5 + 1, false) || !flag2)
{
                            for (int k = minimumLeft; k <= minimumRight; k++)
{
                                if (k > num7 - 2 && k <= num7 + 1)
{
                                    Main.tile[k, num5 + 1].ClearTileAndPaint();
                                    WorldGen.PlaceTile(k, num5 + 1, (int)num10, true, false, -1, num11);
                                }
                            }
                        }
                    }
                    else
                    {
                        minimumLeft += num9;
                        minimumRight += num9;
                    }
                }
            }
            minimumLeft = num;
            minimumRight = num2;
            for (int l = minimumLeft; l <= minimumRight; l++)
            {
                for (int m = j - 3; m <= j; m++)
                {
                    Tile tile = Main.tile[l, m];
                    tile.ClearTileAndPaint();
                    if (!DungeonUtils.IsConsideredDungeonWall((int)tile.wall, false) && !DungeonUtils.IsConsideredDungeonWallGlass((int)tile.wall, false))
                    {
                        tile.wall = 244;
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.Tile.Clear(), Terraria.Tile.ClearTileAndPaint(), Terraria.ID.ItemID.Sets.DerivedPlacementDetails, Terraria.WorldGen.genRand, int, Terraria.GameContent.Generation.Dungeon.DungeonUtils.IsConsideredDungeonWall(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.IsConsideredDungeonWallGlass(), Terraria.WorldGen.isGeneratingOrLoadingWorld, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.PlaceTile(), Terraria.GameContent.Generation.Dungeon.DungeonData.platformItemType, Terraria.WorldGen.SolidTile(), Terraria.WorldGen.SquareTileFrame(), Terraria.WorldGen.SquareWallFrame(), Terraria.Main.tile, Terraria.DataStructures.PlacementDetails.tileStyle, Terraria.DataStructures.PlacementDetails.tileType, Terraria.Tile.type, Terraria.Tile.wall, and Terraria.Main.worldSurface.
Referenced by Terraria.GameContent.Generation.Dungeon.DungeonUtils.GrowDungeonTree().