Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateHangingLeafCluster
GenerateHangingLeafCluster()
static void Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateHangingLeafCluster (DungeonData data, UnifiedRandom genRand, DungeonBounds bounds, Point startPoint, int growthLength, int branchDensity, int leafDensity, ushort leafType, ushort woodType, int leafPaintColor = 0, int woodPaintColor = 0, bool goDown = true, bool includeVines = true) inline static
Definition at line 530 of file DungeonUtils.cs.
        {
            Point point = new Point(startPoint.X, startPoint.Y);
            int num = (goDown ? 1 : (-1));
            point = DungeonUtils.FirstSolid(goDown, point, bounds);
            Point point2 = point;
            Point? point3 = null;
            int num2 = growthLength;
            while (growthLength > 0)
            {
                int y = point.Y;
                float num3 = (float)growthLength / (float)num2;
                if (point3 == null && num3 > 0.65f)
                {
                    point3 = new Point?(point);
                }
                int num4 = (int)Utils.Lerp(0.0, (double)((float)branchDensity), (double)num3);
                for (int i = -num4; i <= num4; i++)
                {
                    int num5 = point.X + i;
                    DungeonUtils.ChangeTileType(Main.tile[num5, y], woodType, false, woodPaintColor);
                }
                point.Y += num;
                growthLength--;
            }
            int num6 = genRand.Next(3);
            if (!goDown)
            {
                num6 *= -1;
            }
            if (point3 != null)
            {
                point = new Point(point3.Value.X, point3.Value.Y + num6);
            }
            else
            {
                point = new Point(point2.X, point2.Y + (int)((float)num2 * 0.65f) + num6);
            }
            int j = leafDensity * 2 + 3;
            int num7 = j;
            while (j > 0)
            {
                int y2 = point.Y;
                float num8 = (float)j / (float)num7;
                int num9 = (int)Utils.WrappedLerp(1f, (float)leafDensity, num8);
                for (int k = -num9; k <= num9; k++)
                {
                    int num10 = point.X + k;
                    Tile tile = Main.tile[num10, y2];
                    if (!tile.active())
                    {
                        DungeonUtils.ChangeTileType(tile, leafType, false, leafPaintColor);
                    }
                }
                point.Y += num;
                j--;
            }
        }
References Terraria.Tile.active(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.ChangeTileType(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.FirstSolid(), int, Terraria.Utils.Lerp(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.tile, Terraria.Utils.WrappedLerp(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.Generation.Dungeon.Rooms.LivingTreeDungeonRoom.GenerateEarlyDungeonFeaturesInRoom().