Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.DungeonUtils.GrowDungeonTree
GrowDungeonTree()
static bool Terraria.GameContent.Generation.Dungeon.DungeonUtils.GrowDungeonTree (DungeonData data, int i, int j, int attachmentY, bool patch = false, bool generateRoots = true) inline static private
Definition at line 612 of file DungeonUtils.cs.
        {
            byte b = 28;
            byte b2 = 28;
            if (WorldGen.notTheBees)
            {
                b = 0;
                b2 = 0;
            }
            UnifiedRandom genRand = WorldGen.genRand;
            int num = 0;
            int[] array = new int[1000];
            int[] array2 = new int[1000];
            int[] array3 = new int[1000];
            int[] array4 = new int[1000];
            int num2 = 0;
            int[] array5 = new int[2000];
            int[] array6 = new int[2000];
            bool[] array7 = new bool[2000];
            int num3 = i - genRand.Next(2, 3);
            int num4 = i + genRand.Next(2, 3);
            if (genRand.Next(5) == 0)
            {
                if (genRand.Next(2) == 0)
                {
                    num3--;
                }
                else
                {
                    num4++;
                }
            }
            int num5 = num4 - num3;
            int num6 = num3;
            int num7 = num4;
            int num8 = num3;
            int num9 = num4;
            bool flag = true;
            int num10 = genRand.Next(-8, -4);
            int num11 = genRand.Next(2);
            int num12 = j;
            int num13 = genRand.Next(5, 15);
            Main.tileSolid[48] = false;
            while (flag)
            {
                num10++;
                if (num10 > num13)
                {
                    num13 = genRand.Next(5, 15);
                    num10 = 0;
                    array2[num] = num12 + genRand.Next(5);
                    if (genRand.Next(5) == 0)
                    {
                        if (num11 == 0)
{
                            num11 = 1;
                        }
                        else
{
                            num11 = 0;
                        }
                    }
                    if (num11 == 0)
                    {
                        array3[num] = -1;
                        array[num] = num3;
                        array4[num] = num4 - num3;
                        if (genRand.Next(2) == 0)
{
                            num3++;
                        }
                        num6++;
                        num11 = 1;
                    }
                    else
                    {
                        array3[num] = 1;
                        array[num] = num4;
                        array4[num] = num4 - num3;
                        if (genRand.Next(2) == 0)
{
                            num4--;
                        }
                        num7--;
                        num11 = 0;
                    }
                    if (num6 == num7)
                    {
                        flag = false;
                    }
                    num++;
                }
                for (int k = num3; k <= num4; k++)
                {
                    Main.tile[k, num12].type = 191;
                    Main.tile[k, num12].active(true);
                    Main.tile[k, num12].Clear(TileDataType.Slope);
                    if (b != 0)
                    {
                        Main.tile[k, num12].color(b);
                    }
                }
                num12--;
            }
            for (int l = 0; l < num - 1; l++)
            {
                int num14 = array[l] + array3[l];
                int num15 = array2[l];
                int m = (int)((double)array4[l] * (1.0 + (double)genRand.Next(20, 30) * 0.1));
                Main.tile[num14, num15 + 1].type = 191;
                Main.tile[num14, num15 + 1].active(true);
                Main.tile[num14, num15 + 1].Clear(TileDataType.Slope);
                if (b != 0)
                {
                    Main.tile[num14, num15 + 1].color(b);
                }
                int num16 = genRand.Next(3, 5);
                while (m > 0)
                {
                    m--;
                    Main.tile[num14, num15].type = 191;
                    Main.tile[num14, num15].active(true);
                    Main.tile[num14, num15].Clear(TileDataType.Slope);
                    if (b != 0)
                    {
                        Main.tile[num14, num15].color(b);
                    }
                    if (genRand.Next(10) == 0)
                    {
                        if (genRand.Next(2) == 0)
{
                            num15--;
                        }
                        else
{
                            num15++;
                        }
                    }
                    else
                    {
                        num14 += array3[l];
                    }
                    if (num16 > 0)
                    {
                        num16--;
                    }
                    else if (genRand.Next(2) == 0)
                    {
                        num16 = genRand.Next(2, 5);
                        if (genRand.Next(2) == 0)
{
                            Main.tile[num14, num15].type = 191;
                            Main.tile[num14, num15].active(true);
                            Main.tile[num14, num15].Clear(TileDataType.Slope);
                            if (b != 0)
{
                                Main.tile[num14, num15].color(b);
                            }
                            Main.tile[num14, num15 - 1].type = 191;
                            Main.tile[num14, num15 - 1].Clear(TileDataType.Slope);
                            if (b != 0)
{
                                Main.tile[num14, num15 - 1].color(b);
                            }
                            array5[num2] = num14;
                            array6[num2] = num15;
                            num2++;
                        }
                        else
{
                            Main.tile[num14, num15].type = 191;
                            Main.tile[num14, num15].active(true);
                            Main.tile[num14, num15].Clear(TileDataType.Slope);
                            if (b != 0)
{
                                Main.tile[num14, num15].color(b);
                            }
                            Main.tile[num14, num15 + 1].type = 191;
                            Main.tile[num14, num15 + 1].active(true);
                            Main.tile[num14, num15 + 1].Clear(TileDataType.Slope);
                            if (b != 0)
{
                                Main.tile[num14, num15 + 1].color(b);
                            }
                            array5[num2] = num14;
                            array6[num2] = num15;
                            num2++;
                        }
                    }
                    if (m == 0)
                    {
                        array5[num2] = num14;
                        array6[num2] = num15;
                        num2++;
                    }
                }
            }
            int num17 = (num3 + num4) / 2;
            int num18 = num12;
            int n = genRand.Next(num5 * 3, num5 * 5);
            int num19 = 0;
            int num20 = 0;
            while (n > 0)
            {
                Main.tile[num17, num18].type = 191;
                Main.tile[num17, num18].active(true);
                Main.tile[num17, num18].Clear(TileDataType.Slope);
                if (b != 0)
                {
                    Main.tile[num17, num18].color(b);
                }
                if (num19 > 0)
                {
                    num19--;
                }
                if (num20 > 0)
                {
                    num20--;
                }
                for (int num21 = -1; num21 < 2; num21++)
                {
                    if (num21 != 0 && ((num21 < 0 && num19 == 0) || (num21 > 0 && num20 == 0)) && genRand.Next(2) == 0)
                    {
                        int num22 = num17;
                        int num23 = num18;
                        int num24 = genRand.Next(num5, num5 * 3);
                        if (num21 < 0)
{
                            num19 = genRand.Next(3, 5);
                        }
                        if (num21 > 0)
{
                            num20 = genRand.Next(3, 5);
                        }
                        int num25 = 0;
                        while (num24 > 0)
{
                            num24--;
                            num22 += num21;
                            Main.tile[num22, num23].type = 191;
                            Main.tile[num22, num23].active(true);
                            Main.tile[num22, num23].Clear(TileDataType.Slope);
                            if (b != 0)
{
                                Main.tile[num22, num23].color(b);
                            }
                            if (num24 == 0)
{
                                array5[num2] = num22;
                                array6[num2] = num23;
                                array7[num2] = true;
                                num2++;
                            }
                            if (genRand.Next(5) == 0)
{
                                if (genRand.Next(2) == 0)
{
                                    num23--;
                                }
                                else
{
                                    num23++;
                                }
                                Main.tile[num22, num23].type = 191;
                                Main.tile[num22, num23].active(true);
                                Main.tile[num22, num23].Clear(TileDataType.Slope);
                                if (b != 0)
{
                                    Main.tile[num22, num23].color(b);
                                }
                            }
                            if (num25 > 0)
{
                                num25--;
                            }
                            else if (genRand.Next(3) == 0)
{
                                num25 = genRand.Next(2, 4);
                                int num26 = num22;
                                int num27 = num23;
                                if (genRand.Next(2) == 0)
{
                                    num27--;
                                }
                                else
{
                                    num27++;
                                }
                                Main.tile[num26, num27].type = 191;
                                Main.tile[num26, num27].active(true);
                                Main.tile[num26, num27].Clear(TileDataType.Slope);
                                if (b != 0)
{
                                    Main.tile[num26, num27].color(b);
                                }
                                array5[num2] = num26;
                                array6[num2] = num27;
                                array7[num2] = true;
                                num2++;
                                array5[num2] = num26 + genRand.Next(-5, 6);
                                array6[num2] = num27 + genRand.Next(-5, 6);
                                array7[num2] = true;
                                num2++;
                            }
                        }
                    }
                }
                array5[num2] = num17;
                array6[num2] = num18;
                num2++;
                if (genRand.Next(4) == 0)
                {
                    if (genRand.Next(2) == 0)
                    {
                        num17--;
                    }
                    else
                    {
                        num17++;
                    }
                    Main.tile[num17, num18].type = 191;
                    Main.tile[num17, num18].active(true);
                    Main.tile[num17, num18].Clear(TileDataType.Slope);
                    if (b != 0)
                    {
                        Main.tile[num17, num18].color(b);
                    }
                }
                num18--;
                n--;
            }
            if (generateRoots)
            {
                for (int num28 = num8; num28 <= num9; num28++)
                {
                    int num29 = genRand.Next(1, 6);
                    int num30 = j + 1;
                    while (num29 > 0)
                    {
                        if (WorldGen.SolidTile(num28, num30, false))
{
                            num29--;
                        }
                        Main.tile[num28, num30].type = 191;
                        Main.tile[num28, num30].active(true);
                        Main.tile[num28, num30].Clear(TileDataType.Slope);
                        num30++;
                    }
                    int num31 = num30;
                    int num32 = genRand.Next(2, num5 + 1);
                    for (int num33 = 0; num33 < num32; num33++)
                    {
                        num30 = num31;
                        int num34 = (num8 + num9) / 2;
                        int num35 = 1;
                        int num36;
                        if (num28 < num34)
{
                            num36 = -1;
                        }
                        else
{
                            num36 = 1;
                        }
                        if (num28 == num34 || (num5 > 6 && (num28 == num34 - 1 || num28 == num34 + 1)))
{
                            num36 = 0;
                        }
                        int num37 = num36;
                        int num38 = num28;
                        num29 = genRand.Next((int)((double)num5 * 3.5), num5 * 6);
                        while (num29 > 0)
{
                            num29--;
                            num38 += num36;
                            if (Main.tile[num38, num30].wall != 244)
{
                                Main.tile[num38, num30].type = 191;
                                Main.tile[num38, num30].active(true);
                                Main.tile[num38, num30].Clear(TileDataType.Slope);
                            }
                            num30 += num35;
                            if (Main.tile[num38, num30].wall != 244)
{
                                Main.tile[num38, num30].type = 191;
                                Main.tile[num38, num30].active(true);
                                Main.tile[num38, num30].Clear(TileDataType.Slope);
                            }
                            if (!Main.tile[num38, num30 + 1].active())
{
                                num36 = 0;
                                num35 = 1;
                            }
                            if (genRand.Next(3) == 0)
{
                                if (num37 < 0)
{
                                    if (num36 == 0)
{
                                        num36 = -1;
                                    }
                                    else
{
                                        num36 = 0;
                                    }
                                }
                                else if (num37 > 0)
{
                                    if (num36 == 0)
{
                                        num36 = 1;
                                    }
                                    else
{
                                        num36 = 0;
                                    }
                                }
                                else
{
                                    num36 = genRand.Next(-1, 2);
                                }
                            }
                            if (genRand.Next(3) == 0)
{
                                if (num35 == 0)
{
                                    num35 = 1;
                                }
                                else
{
                                    num35 = 0;
                                }
                            }
                        }
                    }
                }
            }
            if (!WorldGen.remixWorldGen)
            {
                for (int num39 = 0; num39 < num2; num39++)
                {
                    int num40 = genRand.Next(5, 8);
                    num40 = (int)((double)num40 * (1.0 + (double)num5 * 0.05));
                    if (array7[num39])
                    {
                        num40 = genRand.Next(6, 12) + num5;
                    }
                    int num41 = array5[num39] - num40 * 2;
                    int num42 = array5[num39] + num40 * 2;
                    int num43 = array6[num39] - num40 * 2;
                    int num44 = array6[num39] + num40 * 2;
                    double num45 = 2.0 - (double)genRand.Next(5) * 0.1;
                    for (int num46 = num41; num46 <= num42; num46++)
                    {
                        for (int num47 = num43; num47 <= num44; num47++)
{
                            if (Main.tile[num46, num47].type != 191)
{
                                if (array7[num39])
{
                                    if ((new Vector2D((double)array5[num39], (double)array6[num39]) - new Vector2D((double)num46, (double)num47)).Length() < (double)num40 * 0.9)
{
                                        Main.tile[num46, num47].type = 192;
                                        Main.tile[num46, num47].active(true);
                                        Main.tile[num46, num47].Clear(TileDataType.Slope);
                                        if (b2 != 0)
{
                                            Main.tile[num46, num47].color(b2);
                                        }
                                    }
                                }
                                else if ((double)Math.Abs(array5[num39] - num46) + (double)Math.Abs(array6[num39] - num47) * num45 < (double)num40)
{
                                    Main.tile[num46, num47].type = 192;
                                    Main.tile[num46, num47].active(true);
                                    Main.tile[num46, num47].Clear(TileDataType.Slope);
                                    if (b2 != 0)
{
                                        Main.tile[num46, num47].color(b2);
                                    }
                                }
                            }
                        }
                    }
                }
            }
            DungeonUtils.GrowDungeonTree_MakePassage(data, j, attachmentY, num5, ref num8, ref num9, patch);
            Main.tileSolid[48] = true;
            return true;
        }
References System.Math.Abs(), Terraria.Tile.active(), System.array, Terraria.Tile.Clear(), Terraria.Tile.color(), Terraria.WorldGen.genRand, Terraria.GameContent.Generation.Dungeon.DungeonUtils.GrowDungeonTree_MakePassage(), int, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.notTheBees, Terraria.WorldGen.remixWorldGen, Terraria.WorldGen.SolidTile(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Tile.type, and Terraria.Tile.wall.
Referenced by Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateDungeonTree().