Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateFloatingRocksInArea
GenerateFloatingRocksInArea() [4/4]
static void Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateFloatingRocksInArea (DungeonData data, int x, int y, int width, int height, ushort tileType, bool includePlatform = true, int platformStyle = -1, int paint = -1, int platformDistance = 7) inline static
Definition at line 1390 of file DungeonUtils.cs.
        {
            UnifiedRandom genRand = WorldGen.genRand;
            int num = Math.Max(2, (width + height) / 2 / platformDistance);
            int i = 0;
            int num2 = 100;
            int num3 = x + width / 2;
            int num4 = 8;
            bool flag = true;
            Func<DungeonData, int, int, bool> <>9__0;
            while (i < num)
            {
                num2--;
                if (num2 <= 0)
                {
                    break;
                }
                int num5 = 4 + genRand.Next(3);
                int num6 = x;
                int num7 = y;
                if (i % 2 == 0)
                {
                    int num8 = width / 2;
                    if (flag)
                    {
                        num6 = x + num4 + genRand.Next(Math.Max(1, num8 - num4));
                    }
                    else
                    {
                        num6 = x + num4 + num8 + genRand.Next(Math.Max(1, num8 - num4 * 2));
                    }
                    flag = !flag;
                }
                else
                {
                    num6 = x + num4 + genRand.Next(width - num4 * 2);
                }
                num7 = y + num4 + (int)((float)(height - num4 * 2) * ((float)i / (float)num));
                DungeonUtils.GenerateRockPlatform(genRand, num6, num7, num5, tileType, paint);
                if (includePlatform)
                {
                    int num9 = ((num6 < num3) ? (num6 - 5) : (num6 + 5));
                    int num10 = ((num6 < num3) ? (num6 - x) : (x + width - num6));
                    DungeonPlatformData dungeonPlatformData = default(DungeonPlatformData);
                    dungeonPlatformData.Position = new Point(num9, num7);
                    dungeonPlatformData.InAHallway = false;
                    dungeonPlatformData.OverrideHeightFluff = new int?(0);
                    dungeonPlatformData.ForcePlacement = true;
                    dungeonPlatformData.OverrideMaxLengthAllowed = 5 + num10;
                    Func<DungeonData, int, int, bool> func;
                    if ((func = <>9__0) == null)
                    {
                        func = (<>9__0 = (DungeonData dungeonData, int platformX, int platformY) => platformX >= x && platformX <= x + width && platformY >= y && platformY <= y + height);
                    }
                    dungeonPlatformData.canPlaceHereCallback = func;
                    DungeonPlatformData dungeonPlatformData2 = dungeonPlatformData;
                    if (platformStyle > -1)
                    {
                        dungeonPlatformData2.OverrideStyle = new int?(platformStyle);
                    }
                    data.dungeonPlatformData.Add(dungeonPlatformData2);
                }
                i++;
            }
        }
References Terraria.GameContent.Generation.Dungeon.DungeonData.dungeonPlatformData, Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateRockPlatform(), Terraria.WorldGen.genRand, int, System.Math.Max(), and Terraria.Utilities.UnifiedRandom.Next().