Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateDungeonRegularChest
GenerateDungeonRegularChest() [2/2]
static bool Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateDungeonRegularChest (DungeonData data, DungeonGlobalBasicChests feature, DungeonGenerationStyleData styleData, int minX, int minY, int maxX, int maxY) inline static
Definition at line 287 of file DungeonUtils.cs.
        {
            UnifiedRandom genRand = WorldGen.genRand;
            int num = (int)Utils.Lerp((double)minX, (double)maxX, genRand.NextDouble());
            int num2 = (int)Utils.Lerp((double)minY, (double)maxY, genRand.NextDouble());
            if (!data.CanGenerateFeatureInArea(feature, num, num2, 1))
            {
                return false;
            }
            int num3 = -1;
            ushort num4 = 21;
            int num5 = 2;
            bool flag = false;
            byte style = styleData.Style;
            if (style != 0)
            {
                switch (style)
                {
                case 8:
                case 9:
                case 14:
                    num3 = WorldGen.GetNextJungleChestItem();
                    break;
                case 10:
                    num3 = 1293;
                    break;
                case 13:
                    num3 = 832;
                    if (genRand.Next(3) == 0)
                    {
                        num3 = 4281;
                    }
                    break;
                }
            }
            else
            {
                WorldGen.GetDungeonLootAndChestStyle(num, num2, ref num3, ref num5);
                flag = true;
            }
            if (!flag && styleData.ChestItemTypes.Length != 0)
            {
                PlacementDetails placementDetails = ItemID.Sets.DerivedPlacementDetails[styleData.ChestItemTypes[genRand.Next(styleData.ChestItemTypes.Length)]];
                num4 = (ushort)placementDetails.tileType;
                num5 = (int)placementDetails.tileStyle;
            }
            if (num3 == 0 && genRand.Next(2) == 0)
            {
                return true;
            }
            bool flag2 = WorldGen.AddBuriedChest(num, num2, num3, false, num5, false, num4);
            if (flag2 && styleData.Style == 0)
            {
                GenVars.CurrentDungeonGenVars.dungeonLootStyle++;
            }
            return flag2;
        }
References Terraria.WorldGen.AddBuriedChest(), Terraria.GameContent.Generation.Dungeon.DungeonData.CanGenerateFeatureInArea(), Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.ChestItemTypes, Terraria.WorldBuilding.GenVars.CurrentDungeonGenVars, Terraria.ID.ItemID.Sets.DerivedPlacementDetails, Terraria.WorldGen.genRand, Terraria.WorldGen.GetDungeonLootAndChestStyle(), Terraria.WorldGen.GetNextJungleChestItem(), int, Terraria.Utils.Lerp(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Utilities.UnifiedRandom.NextDouble(), Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.Style, Terraria.DataStructures.PlacementDetails.tileStyle, and Terraria.DataStructures.PlacementDetails.tileType.