Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateDungeonBiomeChest
GenerateDungeonBiomeChest() [2/2]
static bool Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateDungeonBiomeChest (DungeonData data, DungeonGlobalBiomeChests feature, DungeonGenerationStyleData styleData, int minX, int minY, int maxX, int maxY, bool locked = true) inline static
Definition at line 242 of file DungeonUtils.cs.
        {
            UnifiedRandom genRand = WorldGen.genRand;
            int num = (int)Utils.Lerp((double)minX, (double)maxX, genRand.NextDouble());
            int num2 = (int)Utils.Lerp((double)minY, (double)maxY, genRand.NextDouble());
            if (!data.CanGenerateFeatureInArea(feature, num, num2, 1))
            {
                return false;
            }
            int num3 = 0;
            ushort num4 = 21;
            int num5 = 2;
            if (styleData.BiomeChestLootItemType >= 0)
            {
                num3 = styleData.BiomeChestLootItemType;
            }
            if (styleData.BiomeChestItemType >= 0)
            {
                PlacementDetails placementDetails = ItemID.Sets.DerivedPlacementDetails[styleData.BiomeChestItemType];
                num4 = (ushort)placementDetails.tileType;
                num5 = (int)placementDetails.tileStyle;
            }
            if (locked && styleData.LockedBiomeChestStyle >= 0)
            {
                num5 = styleData.LockedBiomeChestStyle;
            }
            if (num3 == 0)
            {
                return false;
            }
            Point zero = Point.Zero;
            return WorldGen.AddBuriedChest(num, num2, out zero, num3, false, num5, false, num4);
        }
References Terraria.WorldGen.AddBuriedChest(), Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.BiomeChestItemType, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.BiomeChestLootItemType, Terraria.GameContent.Generation.Dungeon.DungeonData.CanGenerateFeatureInArea(), Terraria.ID.ItemID.Sets.DerivedPlacementDetails, Terraria.WorldGen.genRand, int, Terraria.Utils.Lerp(), Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.LockedBiomeChestStyle, Terraria.Utilities.UnifiedRandom.NextDouble(), Terraria.DataStructures.PlacementDetails.tileStyle, Terraria.DataStructures.PlacementDetails.tileType, and Microsoft.Xna.Framework.Point.Zero.