Terraria Decompiled: Steamworks.SteamHTMLSurface.SetCookie
SetCookie()
static void Steamworks.SteamHTMLSurface.SetCookie (string pchHostname, string pchKey, string pchValue, string pchPath = "/", uint nExpires = 0U, bool bSecure = false, bool bHTTPOnly = false) inline static
Definition at line 238 of file SteamHTMLSurface.cs.
        {
            InteropHelp.TestIfAvailableClient();
            using (InteropHelp.UTF8StringHandle utf8StringHandle = new InteropHelp.UTF8StringHandle(pchHostname))
            {
                using (InteropHelp.UTF8StringHandle utf8StringHandle2 = new InteropHelp.UTF8StringHandle(pchKey))
                {
                    using (InteropHelp.UTF8StringHandle utf8StringHandle3 = new InteropHelp.UTF8StringHandle(pchValue))
                    {
                        using (InteropHelp.UTF8StringHandle utf8StringHandle4 = new InteropHelp.UTF8StringHandle(pchPath))
{
                            NativeMethods.ISteamHTMLSurface_SetCookie(CSteamAPIContext.GetSteamHTMLSurface(), utf8StringHandle, utf8StringHandle2, utf8StringHandle3, utf8StringHandle4, nExpires, bSecure, bHTTPOnly);
                        }
                    }
                }
            }
        }
References Steamworks.CSteamAPIContext.GetSteamHTMLSurface(), Steamworks.NativeMethods.ISteamHTMLSurface_SetCookie(), and Steamworks.InteropHelp.TestIfAvailableClient().