Terraria Decompiled: System.Text.UTF8Encoding.GetByteCount
GetByteCount() [2/4]
unsafe override int System.Text.UTF8Encoding.GetByteCount (char * chars, int count, EncoderNLS baseEncoder) inline package virtual
Reimplemented from System.Text.Encoding.
Definition at line 329 of file UTF8Encoding.cs.
        {
            EncoderFallbackBuffer encoderFallbackBuffer = null;
            char* ptr = chars;
            char* ptr2 = ptr + count;
            int num = count;
            int num2 = 0;
            if (baseEncoder != null)
            {
                UTF8Encoding.UTF8Encoder utf8Encoder = (UTF8Encoding.UTF8Encoder)baseEncoder;
                num2 = utf8Encoder.surrogateChar;
                if (utf8Encoder.InternalHasFallbackBuffer)
                {
                    encoderFallbackBuffer = utf8Encoder.FallbackBuffer;
                    if (encoderFallbackBuffer.Remaining > 0)
                    {
                        throw new ArgumentException(SR.Format("Must complete Convert() operation or call Encoder.Reset() before calling GetBytes() or GetByteCount(). Encoder '{0}' fallback '{1}'.", this.EncodingName, utf8Encoder.Fallback.GetType()));
                    }
                    encoderFallbackBuffer.InternalInitialize(chars, ptr2, utf8Encoder, false);
                }
            }
            for (;;)
            {
                if (ptr >= ptr2)
                {
                    if (num2 == 0)
                    {
                        num2 = (int)((encoderFallbackBuffer != null) ? encoderFallbackBuffer.InternalGetNextChar() : '\0');
                        if (num2 > 0)
{
                            num++;
                            goto IL_014C;
                        }
                    }
                    else if (encoderFallbackBuffer != null && encoderFallbackBuffer.bFallingBack)
                    {
                        num2 = (int)encoderFallbackBuffer.InternalGetNextChar();
                        num++;
                        if (UTF8Encoding.InRange(num2, 56320, 57343))
{
                            num2 = 65533;
                            num++;
                            goto IL_016A;
                        }
                        if (num2 <= 0)
{
                            break;
                        }
                        goto IL_014C;
                    }
                    if (num2 > 0 && (baseEncoder == null || baseEncoder.MustFlush))
                    {
                        num++;
                        goto IL_016A;
                    }
                    goto IL_0432;
                }
                else if (num2 > 0)
                {
                    int num3 = (int)(*ptr);
                    num++;
                    if (UTF8Encoding.InRange(num3, 56320, 57343))
                    {
                        num2 = 65533;
                        ptr++;
                        goto IL_016A;
                    }
                    goto IL_016A;
                }
                else
                {
                    if (encoderFallbackBuffer != null)
                    {
                        num2 = (int)encoderFallbackBuffer.InternalGetNextChar();
                        if (num2 > 0)
{
                            num++;
                            goto IL_014C;
                        }
                    }
                    num2 = (int)(*ptr);
                    ptr++;
                }
                IL_014C:
                if (UTF8Encoding.InRange(num2, 55296, 56319))
                {
                    num--;
                    continue;
                }
                IL_016A:
                if (UTF8Encoding.InRange(num2, 55296, 57343))
                {
                    if (encoderFallbackBuffer == null)
                    {
                        if (baseEncoder == null)
{
                            encoderFallbackBuffer = this.encoderFallback.CreateFallbackBuffer();
                        }
                        else
{
                            encoderFallbackBuffer = baseEncoder.FallbackBuffer;
                        }
                        encoderFallbackBuffer.InternalInitialize(chars, chars + count, baseEncoder, false);
                    }
                    char* ptr3 = ptr;
                    encoderFallbackBuffer.InternalFallback((char)num2, ref ptr3);
                    ptr = ptr3;
                    num--;
                    num2 = 0;
                }
                else
                {
                    if (num2 > 127)
                    {
                        if (num2 > 2047)
{
                            num++;
                        }
                        num++;
                    }
                    if (num < 0)
                    {
                        goto IL_0432;
                    }
                    if (encoderFallbackBuffer != null && (num2 = (int)encoderFallbackBuffer.InternalGetNextChar()) != 0)
                    {
                        num++;
                        goto IL_014C;
                    }
                    int num4 = UTF8Encoding.PtrDiff(ptr2, ptr);
                    if (num4 <= 13)
                    {
                        char* ptr4 = ptr2;
                        while (ptr < ptr4)
{
                            num2 = (int)(*ptr);
                            ptr++;
                            if (num2 > 127)
{
                                goto IL_014C;
                            }
                        }
                        goto Block_28;
                    }
                    num4 &= 268435455;
                    char* ptr5 = ptr + num4 - 7;
                    IL_0422:
                    while (ptr < ptr5)
                    {
                        num2 = (int)(*ptr);
                        ptr++;
                        if (num2 > 127)
{
                            if (num2 > 2047)
{
                                if ((num2 & 63488) == 55296)
{
                                    goto IL_03D0;
                                }
                                num++;
                            }
                            num++;
                        }
                        if ((ptr & 2) != 0)
{
                            num2 = (int)(*ptr);
                            ptr++;
                            if (num2 > 127)
{
                                if (num2 > 2047)
{
                                    if ((num2 & 63488) == 55296)
{
                                        goto IL_03D0;
                                    }
                                    num++;
                                }
                                num++;
                            }
                        }
                        while (ptr < ptr5)
{
                            num2 = *(int*)ptr;
                            int num5 = *(int*)(ptr + 2);
                            if (((num2 | num5) & -8323200) != 0)
{
                                if (((num2 | num5) & -134154240) != 0)
{
                                    goto IL_03B1;
                                }
                                if ((num2 & -8388608) != 0)
{
                                    num++;
                                }
                                if ((num2 & 65408) != 0)
{
                                    num++;
                                }
                                if ((num5 & -8388608) != 0)
{
                                    num++;
                                }
                                if ((num5 & 65408) != 0)
{
                                    num++;
                                }
                            }
                            ptr += 4;
                            num2 = *(int*)ptr;
                            num5 = *(int*)(ptr + 2);
                            if (((num2 | num5) & -8323200) != 0)
{
                                if (((num2 | num5) & -134154240) != 0)
{
                                    goto IL_03B1;
                                }
                                if ((num2 & -8388608) != 0)
{
                                    num++;
                                }
                                if ((num2 & 65408) != 0)
{
                                    num++;
                                }
                                if ((num5 & -8388608) != 0)
{
                                    num++;
                                }
                                if ((num5 & 65408) != 0)
{
                                    num++;
                                }
                            }
                            ptr += 4;
                            continue;
                            IL_03B1:
                            if (BitConverter.IsLittleEndian)
{
                                num2 = (int)((ushort)num2);
                            }
                            else
{
                                num2 = (int)((uint)num2 >> 16);
                            }
                            ptr++;
                            if (num2 > 127)
{
                                goto IL_03D0;
                            }
                            goto IL_0422;
                        }
                        break;
                        IL_03D0:
                        if (num2 > 2047)
{
                            if (UTF8Encoding.InRange(num2, 55296, 57343))
{
                                int num6 = (int)(*ptr);
                                if (num2 > 56319 || !UTF8Encoding.InRange(num6, 56320, 57343))
{
                                    ptr--;
                                    break;
                                }
                                ptr++;
                            }
                            num++;
                        }
                        num++;
                    }
                    num2 = 0;
                }
            }
            num--;
            Block_28:
            IL_0432:
            if (num < 0)
            {
                throw new ArgumentException("Conversion buffer overflow.");
            }
            return num;
        }
References System.Text.EncoderFallbackBuffer.bFallingBack, System.count, System.Text.EncoderFallback.CreateFallbackBuffer(), System.Text.Encoding.encoderFallback, System.Text.Encoder.Fallback, System.Text.Encoder.FallbackBuffer, SR.Format(), System.Text.UTF8Encoding.InRange(), int, System.Text.EncoderFallbackBuffer.InternalFallback(), System.Text.EncoderFallbackBuffer.InternalGetNextChar(), System.Text.Encoder.InternalHasFallbackBuffer, System.Text.EncoderFallbackBuffer.InternalInitialize(), System.BitConverter.IsLittleEndian, System.Text.EncoderNLS.MustFlush, System.Text.UTF8Encoding.PtrDiff(), System.Text.EncoderFallbackBuffer.Remaining, and System.Text.UTF8Encoding.UTF8Encoder.surrogateChar.