Terraria Decompiled: System.Text.UTF8Encoding.GetCharCount
GetCharCount() [2/3]
unsafe override int System.Text.UTF8Encoding.GetCharCount (byte * bytes, int count, DecoderNLS baseDecoder) inline package virtual
Reimplemented from System.Text.Encoding.
Definition at line 970 of file UTF8Encoding.cs.
        {
            byte* ptr = bytes;
            byte* ptr2 = ptr + count;
            int num = count;
            int num2 = 0;
            DecoderFallbackBuffer decoderFallbackBuffer = null;
            if (baseDecoder != null)
            {
                num2 = ((UTF8Encoding.UTF8Decoder)baseDecoder).bits;
                num -= num2 >> 30;
            }
            IL_0023:
            while (ptr < ptr2)
            {
                if (num2 == 0)
                {
                    num2 = (int)(*ptr);
                    ptr++;
                    goto IL_0106;
                }
                int num3 = (int)(*ptr);
                ptr++;
                if ((num3 & -64) != 128)
                {
                    ptr--;
                    num += num2 >> 30;
                }
                else
                {
                    num2 = (num2 << 6) | (num3 & 63);
                    if ((num2 & 536870912) == 0)
                    {
                        if ((num2 & 268435456) != 0)
{
                            if ((num2 & 8388608) != 0 || UTF8Encoding.InRange(num2 & 496, 16, 256))
{
                                continue;
                            }
                        }
                        else if ((num2 & 992) != 0)
{
                            if ((num2 & 992) != 864)
{
                                continue;
                            }
                        }
                    }
                    else
                    {
                        if ((num2 & 270467072) == 268435456)
{
                            num--;
                            goto IL_017C;
                        }
                        goto IL_017C;
                    }
                }
                IL_00C3:
                if (decoderFallbackBuffer == null)
                {
                    if (baseDecoder == null)
                    {
                        decoderFallbackBuffer = this.decoderFallback.CreateFallbackBuffer();
                    }
                    else
                    {
                        decoderFallbackBuffer = baseDecoder.FallbackBuffer;
                    }
                    decoderFallbackBuffer.InternalInitialize(bytes, null);
                }
                num += this.FallbackInvalidByteSequence(ptr, num2, decoderFallbackBuffer);
                num2 = 0;
                continue;
                IL_017C:
                int num4 = UTF8Encoding.PtrDiff(ptr2, ptr);
                if (num4 <= 13)
                {
                    byte* ptr3 = ptr2;
                    while (ptr < ptr3)
                    {
                        num2 = (int)(*ptr);
                        ptr++;
                        if (num2 > 127)
{
                            goto IL_0106;
                        }
                    }
                    num2 = 0;
                    break;
                }
                byte* ptr4 = ptr + num4 - 7;
                while (ptr < ptr4)
                {
                    num2 = (int)(*ptr);
                    ptr++;
                    if (num2 <= 127)
                    {
                        if ((ptr & 1) != 0)
{
                            num2 = (int)(*ptr);
                            ptr++;
                            if (num2 > 127)
{
                                goto IL_026F;
                            }
                        }
                        if ((ptr & 2) != 0)
{
                            num2 = (int)(*(ushort*)ptr);
                            if ((num2 & 32896) != 0)
{
                                goto IL_024E;
                            }
                            ptr += 2;
                        }
                        while (ptr < ptr4)
{
                            num2 = *(int*)ptr;
                            int num5 = *(int*)(ptr + 4);
                            if (((num2 | num5) & -2139062144) == 0)
{
                                ptr += 8;
                                if (ptr >= ptr4)
{
                                    break;
                                }
                                num2 = *(int*)ptr;
                                num5 = *(int*)(ptr + 4);
                                if (((num2 | num5) & -2139062144) == 0)
{
                                    ptr += 8;
                                    continue;
                                }
                            }
                            if (BitConverter.IsLittleEndian)
{
                                num2 &= 255;
                                goto IL_024E;
                            }
                            num2 = (int)((uint)num2 >> 16);
                            goto IL_024E;
                        }
                        break;
                        IL_024E:
                        if (BitConverter.IsLittleEndian)
{
                            num2 &= 255;
                        }
                        else
{
                            num2 = (int)((uint)num2 >> 8);
                        }
                        ptr++;
                        if (num2 <= 127)
{
                            continue;
                        }
                    }
                    IL_026F:
                    int num6 = (int)(*ptr);
                    ptr++;
                    if ((num2 & 64) != 0 && (num6 & -64) == 128)
                    {
                        num6 &= 63;
                        if ((num2 & 32) != 0)
{
                            num6 |= (num2 & 15) << 6;
                            if ((num2 & 16) != 0)
{
                                num2 = (int)(*ptr);
                                if (!UTF8Encoding.InRange(num6 >> 4, 1, 16) || (num2 & -64) != 128)
{
                                    goto IL_033B;
                                }
                                num6 = (num6 << 6) | (num2 & 63);
                                num2 = (int)ptr[1];
                                if ((num2 & -64) != 128)
{
                                    goto IL_033B;
                                }
                                ptr += 2;
                                num--;
                            }
                            else
{
                                num2 = (int)(*ptr);
                                if ((num6 & 992) == 0 || (num6 & 992) == 864 || (num2 & -64) != 128)
{
                                    goto IL_033B;
                                }
                                ptr++;
                                num--;
                            }
                        }
                        else if ((num2 & 30) == 0)
{
                            goto IL_033B;
                        }
                        num--;
                        continue;
                    }
                    IL_033B:
                    ptr -= 2;
                    num2 = 0;
                    goto IL_0023;
                }
                num2 = 0;
                continue;
                IL_0106:
                if (num2 <= 127)
                {
                    goto IL_017C;
                }
                num--;
                if ((num2 & 64) == 0)
                {
                    goto IL_00C3;
                }
                if ((num2 & 32) != 0)
                {
                    if ((num2 & 16) != 0)
                    {
                        num2 &= 15;
                        if (num2 > 4)
{
                            num2 |= 240;
                            goto IL_00C3;
                        }
                        num2 |= 1347226624;
                        num--;
                    }
                    else
                    {
                        num2 = (num2 & 15) | 1210220544;
                        num--;
                    }
                }
                else
                {
                    num2 &= 31;
                    if (num2 <= 1)
                    {
                        num2 |= 192;
                        goto IL_00C3;
                    }
                    num2 |= 8388608;
                }
            }
            if (num2 != 0)
            {
                num += num2 >> 30;
                if (baseDecoder == null || baseDecoder.MustFlush)
                {
                    if (decoderFallbackBuffer == null)
                    {
                        if (baseDecoder == null)
{
                            decoderFallbackBuffer = this.decoderFallback.CreateFallbackBuffer();
                        }
                        else
{
                            decoderFallbackBuffer = baseDecoder.FallbackBuffer;
                        }
                        decoderFallbackBuffer.InternalInitialize(bytes, null);
                    }
                    num += this.FallbackInvalidByteSequence(ptr, num2, decoderFallbackBuffer);
                }
            }
            return num;
        }
References System.count, System.Text.DecoderFallback.CreateFallbackBuffer(), System.Text.Encoding.decoderFallback, System.Text.Decoder.FallbackBuffer, System.Text.UTF8Encoding.FallbackInvalidByteSequence(), System.Text.UTF8Encoding.InRange(), int, System.Text.DecoderFallbackBuffer.InternalInitialize(), System.BitConverter.IsLittleEndian, System.Text.DecoderNLS.MustFlush, and System.Text.UTF8Encoding.PtrDiff().