Terraria Decompiled: System.Text.UTF8Encoding.GetChars
GetChars() [2/3]
unsafe override int System.Text.UTF8Encoding.GetChars (byte * bytes, int byteCount, char * chars, int charCount, DecoderNLS baseDecoder) inline package virtual
Reimplemented from System.Text.Encoding.
Definition at line 1243 of file UTF8Encoding.cs.
        {
            byte* ptr = bytes;
            char* ptr2 = chars;
            byte* ptr3 = ptr + byteCount;
            char* ptr4 = ptr2 + charCount;
            int num = 0;
            DecoderFallbackBuffer decoderFallbackBuffer = null;
            if (baseDecoder != null)
            {
                num = ((UTF8Encoding.UTF8Decoder)baseDecoder).bits;
            }
            IL_0028:
            while (ptr < ptr3)
            {
                if (num == 0)
                {
                    num = (int)(*ptr);
                    ptr++;
                    goto IL_0169;
                }
                int num2 = (int)(*ptr);
                ptr++;
                if ((num2 & -64) != 128)
                {
                    ptr--;
                }
                else
                {
                    num = (num << 6) | (num2 & 63);
                    if ((num & 536870912) == 0)
                    {
                        if ((num & 268435456) != 0)
{
                            if ((num & 8388608) != 0 || UTF8Encoding.InRange(num & 496, 16, 256))
{
                                continue;
                            }
                        }
                        else if ((num & 992) != 0)
{
                            if ((num & 992) != 864)
{
                                continue;
                            }
                        }
                    }
                    else
                    {
                        if ((num & 270467072) > 268435456 && ptr2 < ptr4)
{
                            *ptr2 = (char)(((num >> 10) & 2047) + -10304);
                            ptr2++;
                            num = (num & 1023) + 56320;
                            goto IL_01EA;
                        }
                        goto IL_01EA;
                    }
                }
                IL_00F9:
                if (decoderFallbackBuffer == null)
                {
                    if (baseDecoder == null)
                    {
                        decoderFallbackBuffer = this.decoderFallback.CreateFallbackBuffer();
                    }
                    else
                    {
                        decoderFallbackBuffer = baseDecoder.FallbackBuffer;
                    }
                    decoderFallbackBuffer.InternalInitialize(bytes, ptr4);
                }
                byte* ptr5 = ptr;
                char* ptr6 = ptr2;
                bool flag = this.FallbackInvalidByteSequence(ref ptr5, num, decoderFallbackBuffer, ref ptr6);
                ptr = ptr5;
                ptr2 = ptr6;
                if (!flag)
                {
                    decoderFallbackBuffer.InternalReset();
                    base.ThrowCharsOverflow(baseDecoder, ptr2 == chars);
                    num = 0;
                    break;
                }
                num = 0;
                continue;
                IL_01EA:
                if (ptr2 >= ptr4)
                {
                    num &= 2097151;
                    if (num > 127)
                    {
                        if (num > 2047)
{
                            if (num >= 56320 && num <= 57343)
{
                                ptr--;
                                ptr2--;
                            }
                            else if (num > 65535)
{
                                ptr--;
                            }
                            ptr--;
                        }
                        ptr--;
                    }
                    ptr--;
                    base.ThrowCharsOverflow(baseDecoder, ptr2 == chars);
                    num = 0;
                    break;
                }
                *ptr2 = (char)num;
                ptr2++;
                int num3 = UTF8Encoding.PtrDiff(ptr4, ptr2);
                int num4 = UTF8Encoding.PtrDiff(ptr3, ptr);
                if (num4 > 13)
                {
                    if (num3 < num4)
                    {
                        num4 = num3;
                    }
                    char* ptr7 = ptr2 + num4 - 7;
                    while (ptr2 < ptr7)
                    {
                        num = (int)(*ptr);
                        ptr++;
                        if (num <= 127)
{
                            *ptr2 = (char)num;
                            ptr2++;
                            if ((ptr & 1) != 0)
{
                                num = (int)(*ptr);
                                ptr++;
                                if (num > 127)
{
                                    goto IL_04DC;
                                }
                                *ptr2 = (char)num;
                                ptr2++;
                            }
                            if ((ptr & 2) != 0)
{
                                num = (int)(*(ushort*)ptr);
                                if ((num & 32896) != 0)
{
                                    goto IL_04AB;
                                }
                                if (BitConverter.IsLittleEndian)
{
                                    *ptr2 = (char)(num & 127);
                                    ptr += 2;
                                    ptr2[1] = (char)((num >> 8) & 127);
                                    ptr2 += 2;
                                }
                                else
{
                                    *ptr2 = (char)((num >> 8) & 127);
                                    ptr += 2;
                                    ptr2[1] = (char)(num & 127);
                                    ptr2 += 2;
                                }
                            }
                            while (ptr2 < ptr7)
{
                                num = *(int*)ptr;
                                int num5 = *(int*)(ptr + 4);
                                if (((num | num5) & -2139062144) == 0)
{
                                    if (BitConverter.IsLittleEndian)
{
                                        *ptr2 = (char)(num & 127);
                                        ptr2[1] = (char)((num >> 8) & 127);
                                        ptr2[2] = (char)((num >> 16) & 127);
                                        ptr2[3] = (char)((num >> 24) & 127);
                                        ptr += 8;
                                        ptr2[4] = (char)(num5 & 127);
                                        ptr2[5] = (char)((num5 >> 8) & 127);
                                        ptr2[6] = (char)((num5 >> 16) & 127);
                                        ptr2[7] = (char)((num5 >> 24) & 127);
                                        ptr2 += 8;
                                    }
                                    else
{
                                        *ptr2 = (char)((num >> 24) & 127);
                                        ptr2[1] = (char)((num >> 16) & 127);
                                        ptr2[2] = (char)((num >> 8) & 127);
                                        ptr2[3] = (char)(num & 127);
                                        ptr += 8;
                                        ptr2[4] = (char)((num5 >> 24) & 127);
                                        ptr2[5] = (char)((num5 >> 16) & 127);
                                        ptr2[6] = (char)((num5 >> 8) & 127);
                                        ptr2[7] = (char)(num5 & 127);
                                        ptr2 += 8;
                                    }
                                }
                                else
{
                                    if (BitConverter.IsLittleEndian)
{
                                        num &= 255;
                                        goto IL_04AB;
                                    }
                                    num = (int)((uint)num >> 16);
                                    goto IL_04AB;
                                }
                            }
                            break;
                            IL_04AB:
                            if (BitConverter.IsLittleEndian)
{
                                num &= 255;
                            }
                            else
{
                                num = (int)((uint)num >> 8);
                            }
                            ptr++;
                            if (num <= 127)
{
                                *ptr2 = (char)num;
                                ptr2++;
                                continue;
                            }
                        }
                        IL_04DC:
                        int num6 = (int)(*ptr);
                        ptr++;
                        if ((num & 64) != 0 && (num6 & -64) == 128)
{
                            num6 &= 63;
                            if ((num & 32) != 0)
{
                                num6 |= (num & 15) << 6;
                                if ((num & 16) != 0)
{
                                    num = (int)(*ptr);
                                    if (!UTF8Encoding.InRange(num6 >> 4, 1, 16) || (num & -64) != 128)
{
                                        goto IL_061E;
                                    }
                                    num6 = (num6 << 6) | (num & 63);
                                    num = (int)ptr[1];
                                    if ((num & -64) != 128)
{
                                        goto IL_061E;
                                    }
                                    ptr += 2;
                                    num = (num6 << 6) | (num & 63);
                                    *ptr2 = (char)(((num >> 10) & 2047) + -10304);
                                    ptr2++;
                                    num = (num & 1023) + -9216;
                                    ptr7--;
                                }
                                else
{
                                    num = (int)(*ptr);
                                    if ((num6 & 992) == 0 || (num6 & 992) == 864 || (num & -64) != 128)
{
                                        goto IL_061E;
                                    }
                                    ptr++;
                                    num = (num6 << 6) | (num & 63);
                                    ptr7--;
                                }
                            }
                            else
{
                                num &= 31;
                                if (num <= 1)
{
                                    goto IL_061E;
                                }
                                num = (num << 6) | num6;
                            }
                            *ptr2 = (char)num;
                            ptr2++;
                            ptr7--;
                            continue;
                        }
                        IL_061E:
                        ptr -= 2;
                        num = 0;
                        goto IL_0028;
                    }
                    num = 0;
                    continue;
                }
                if (num3 < num4)
                {
                    num = 0;
                    continue;
                }
                byte* ptr8 = ptr3;
                while (ptr < ptr8)
                {
                    num = (int)(*ptr);
                    ptr++;
                    if (num > 127)
                    {
                        goto IL_0169;
                    }
                    *ptr2 = (char)num;
                    ptr2++;
                }
                num = 0;
                break;
                IL_0169:
                if (num <= 127)
                {
                    goto IL_01EA;
                }
                if ((num & 64) == 0)
                {
                    goto IL_00F9;
                }
                if ((num & 32) != 0)
                {
                    if ((num & 16) != 0)
                    {
                        num &= 15;
                        if (num > 4)
{
                            num |= 240;
                            goto IL_00F9;
                        }
                        num |= 1347226624;
                    }
                    else
                    {
                        num = (num & 15) | 1210220544;
                    }
                }
                else
                {
                    num &= 31;
                    if (num <= 1)
                    {
                        num |= 192;
                        goto IL_00F9;
                    }
                    num |= 8388608;
                }
            }
            if (num != 0 && (baseDecoder == null || baseDecoder.MustFlush))
            {
                if (decoderFallbackBuffer == null)
                {
                    if (baseDecoder == null)
                    {
                        decoderFallbackBuffer = this.decoderFallback.CreateFallbackBuffer();
                    }
                    else
                    {
                        decoderFallbackBuffer = baseDecoder.FallbackBuffer;
                    }
                    decoderFallbackBuffer.InternalInitialize(bytes, ptr4);
                }
                byte* ptr5 = ptr;
                char* ptr6 = ptr2;
                bool flag2 = this.FallbackInvalidByteSequence(ref ptr5, num, decoderFallbackBuffer, ref ptr6);
                ptr = ptr5;
                ptr2 = ptr6;
                if (!flag2)
                {
                    decoderFallbackBuffer.InternalReset();
                    base.ThrowCharsOverflow(baseDecoder, ptr2 == chars);
                }
                num = 0;
            }
            if (baseDecoder != null)
            {
                ((UTF8Encoding.UTF8Decoder)baseDecoder).bits = num;
                baseDecoder._bytesUsed = (int)((long)(ptr - bytes));
            }
            return UTF8Encoding.PtrDiff(ptr2, chars);
        }
References System.Text.DecoderFallback.CreateFallbackBuffer(), System.Text.Encoding.decoderFallback, System.Text.Decoder.FallbackBuffer, System.Text.UTF8Encoding.FallbackInvalidByteSequence(), System.Text.UTF8Encoding.InRange(), int, System.Text.DecoderFallbackBuffer.InternalInitialize(), System.Text.DecoderFallbackBuffer.InternalReset(), System.BitConverter.IsLittleEndian, System.Text.DecoderNLS.MustFlush, and System.Text.UTF8Encoding.PtrDiff().