Terraria Decompiled: System.Text.UTF8Encoding.GetBytes
GetBytes() [2/4]
unsafe override int System.Text.UTF8Encoding.GetBytes (char * chars, int charCount, byte * bytes, int byteCount, EncoderNLS baseEncoder) inline package virtual
Reimplemented from System.Text.Encoding.
Definition at line 630 of file UTF8Encoding.cs.
        {
            UTF8Encoding.UTF8Encoder utf8Encoder = null;
            EncoderFallbackBuffer encoderFallbackBuffer = null;
            char* ptr = chars;
            byte* ptr2 = bytes;
            char* ptr3 = ptr + charCount;
            byte* ptr4 = ptr2 + byteCount;
            int num = 0;
            if (baseEncoder != null)
            {
                utf8Encoder = (UTF8Encoding.UTF8Encoder)baseEncoder;
                num = utf8Encoder.surrogateChar;
                if (utf8Encoder.InternalHasFallbackBuffer)
                {
                    encoderFallbackBuffer = utf8Encoder.FallbackBuffer;
                    if (encoderFallbackBuffer.Remaining > 0 && utf8Encoder._throwOnOverflow)
                    {
                        throw new ArgumentException(SR.Format("Must complete Convert() operation or call Encoder.Reset() before calling GetBytes() or GetByteCount(). Encoder '{0}' fallback '{1}'.", this.EncodingName, utf8Encoder.Fallback.GetType()));
                    }
                    encoderFallbackBuffer.InternalInitialize(chars, ptr3, utf8Encoder, true);
                }
            }
            for (;;)
            {
                if (ptr >= ptr3)
                {
                    if (num == 0)
                    {
                        num = (int)((encoderFallbackBuffer != null) ? encoderFallbackBuffer.InternalGetNextChar() : '\0');
                        if (num > 0)
{
                            goto IL_0147;
                        }
                    }
                    else if (encoderFallbackBuffer != null && encoderFallbackBuffer.bFallingBack)
                    {
                        int num2 = num;
                        num = (int)encoderFallbackBuffer.InternalGetNextChar();
                        if (UTF8Encoding.InRange(num, 56320, 57343))
{
                            num = num + (num2 << 10) + -56613888;
                            goto IL_015D;
                        }
                        if (num > 0)
{
                            goto IL_0147;
                        }
                        goto IL_053C;
                    }
                    if (num <= 0)
                    {
                        goto IL_053C;
                    }
                    if (utf8Encoder == null)
                    {
                        goto IL_015D;
                    }
                    if (utf8Encoder.MustFlush)
                    {
                        goto IL_015D;
                    }
                    goto IL_053C;
                }
                else if (num > 0)
                {
                    int num3 = (int)(*ptr);
                    if (UTF8Encoding.InRange(num3, 56320, 57343))
                    {
                        num = num3 + (num << 10) + -56613888;
                        ptr++;
                        goto IL_015D;
                    }
                    goto IL_015D;
                }
                else
                {
                    if (encoderFallbackBuffer != null)
                    {
                        num = (int)encoderFallbackBuffer.InternalGetNextChar();
                        if (num > 0)
{
                            goto IL_0147;
                        }
                    }
                    num = (int)(*ptr);
                    ptr++;
                }
                IL_0147:
                if (UTF8Encoding.InRange(num, 55296, 56319))
                {
                    continue;
                }
                IL_015D:
                if (UTF8Encoding.InRange(num, 55296, 57343))
                {
                    if (encoderFallbackBuffer == null)
                    {
                        if (baseEncoder == null)
{
                            encoderFallbackBuffer = this.encoderFallback.CreateFallbackBuffer();
                        }
                        else
{
                            encoderFallbackBuffer = baseEncoder.FallbackBuffer;
                        }
                        encoderFallbackBuffer.InternalInitialize(chars, ptr3, baseEncoder, true);
                    }
                    char* ptr5 = ptr;
                    encoderFallbackBuffer.InternalFallback((char)num, ref ptr5);
                    ptr = ptr5;
                    num = 0;
                }
                else
                {
                    int num4 = 1;
                    if (num > 127)
                    {
                        if (num > 2047)
{
                            if (num > 65535)
{
                                num4++;
                            }
                            num4++;
                        }
                        num4++;
                    }
                    if (ptr2 != ptr4 - num4)
                    {
                        break;
                    }
                    if (num <= 127)
                    {
                        *ptr2 = (byte)num;
                    }
                    else
                    {
                        int num5;
                        if (num <= 2047)
{
                            num5 = (int)((byte)(-64 | (num >> 6)));
                        }
                        else
{
                            if (num <= 65535)
{
                                num5 = (int)((byte)(-32 | (num >> 12)));
                            }
                            else
{
                                *ptr2 = (byte)(-16 | (num >> 18));
                                ptr2++;
                                num5 = -128 | ((num >> 12) & 63);
                            }
                            *ptr2 = (byte)num5;
                            ptr2++;
                            num5 = -128 | ((num >> 6) & 63);
                        }
                        *ptr2 = (byte)num5;
                        ptr2++;
                        *ptr2 = (byte)(-128 | (num & 63));
                    }
                    ptr2++;
                    if (encoderFallbackBuffer != null && (num = (int)encoderFallbackBuffer.InternalGetNextChar()) != 0)
                    {
                        goto IL_0147;
                    }
                    int num6 = UTF8Encoding.PtrDiff(ptr3, ptr);
                    int num7 = UTF8Encoding.PtrDiff(ptr4, ptr2);
                    if (num6 <= 13)
                    {
                        if (num7 >= num6)
{
                            char* ptr6 = ptr3;
                            while (ptr < ptr6)
{
                                num = (int)(*ptr);
                                ptr++;
                                if (num > 127)
{
                                    goto IL_0147;
                                }
                                *ptr2 = (byte)num;
                                ptr2++;
                            }
                            goto Block_37;
                        }
                        num = 0;
                    }
                    else
                    {
                        if (num7 < num6)
{
                            num6 = num7;
                        }
                        char* ptr7 = ptr + num6 - 5;
                        while (ptr < ptr7)
{
                            num = (int)(*ptr);
                            ptr++;
                            if (num <= 127)
{
                                *ptr2 = (byte)num;
                                ptr2++;
                                if ((ptr & 2) != 0)
{
                                    num = (int)(*ptr);
                                    ptr++;
                                    if (num > 127)
{
                                        goto IL_044F;
                                    }
                                    *ptr2 = (byte)num;
                                    ptr2++;
                                }
                                while (ptr < ptr7)
{
                                    num = *(int*)ptr;
                                    int num8 = *(int*)(ptr + 2);
                                    if (((num | num8) & -8323200) == 0)
{
                                        if (BitConverter.IsLittleEndian)
{
                                            *ptr2 = (byte)num;
                                            ptr2[1] = (byte)(num >> 16);
                                            ptr += 4;
                                            ptr2[2] = (byte)num8;
                                            ptr2[3] = (byte)(num8 >> 16);
                                            ptr2 += 4;
                                        }
                                        else
{
                                            *ptr2 = (byte)(num >> 16);
                                            ptr2[1] = (byte)num;
                                            ptr += 4;
                                            ptr2[2] = (byte)(num8 >> 16);
                                            ptr2[3] = (byte)num8;
                                            ptr2 += 4;
                                        }
                                    }
                                    else
{
                                        if (BitConverter.IsLittleEndian)
{
                                            num = (int)((ushort)num);
                                        }
                                        else
{
                                            num = (int)((uint)num >> 16);
                                        }
                                        ptr++;
                                        if (num <= 127)
{
                                            *ptr2 = (byte)num;
                                            ptr2++;
                                            break;
                                        }
                                        goto IL_044F;
                                    }
                                }
                                continue;
                            }
                            IL_044F:
                            int num9;
                            if (num <= 2047)
{
                                num9 = -64 | (num >> 6);
                            }
                            else
{
                                if (!UTF8Encoding.InRange(num, 55296, 57343))
{
                                    num9 = -32 | (num >> 12);
                                }
                                else
{
                                    if (num > 56319)
{
                                        ptr--;
                                        break;
                                    }
                                    num9 = (int)(*ptr);
                                    ptr++;
                                    if (!UTF8Encoding.InRange(num9, 56320, 57343))
{
                                        ptr -= 2;
                                        break;
                                    }
                                    num = num9 + (num << 10) + -56613888;
                                    *ptr2 = (byte)(-16 | (num >> 18));
                                    ptr2++;
                                    num9 = -128 | ((num >> 12) & 63);
                                }
                                *ptr2 = (byte)num9;
                                ptr7--;
                                ptr2++;
                                num9 = -128 | ((num >> 6) & 63);
                            }
                            *ptr2 = (byte)num9;
                            ptr7--;
                            ptr2++;
                            *ptr2 = (byte)(-128 | (num & 63));
                            ptr2++;
                        }
                        num = 0;
                    }
                }
            }
            if (encoderFallbackBuffer != null && encoderFallbackBuffer.bFallingBack)
            {
                encoderFallbackBuffer.MovePrevious();
                if (num > 65535)
                {
                    encoderFallbackBuffer.MovePrevious();
                }
            }
            else
            {
                ptr--;
                if (num > 65535)
                {
                    ptr--;
                }
            }
            base.ThrowBytesOverflow(utf8Encoder, ptr2 == bytes);
            num = 0;
            goto IL_053C;
            Block_37:
            num = 0;
            IL_053C:
            if (utf8Encoder != null)
            {
                utf8Encoder.surrogateChar = num;
                utf8Encoder._charsUsed = (int)((long)(ptr - chars));
            }
            return (int)((long)(ptr2 - bytes));
        }
References System.Text.EncoderNLS._throwOnOverflow, System.Text.EncoderFallbackBuffer.bFallingBack, System.Text.EncoderFallback.CreateFallbackBuffer(), System.Text.Encoding.encoderFallback, System.Text.Encoder.Fallback, System.Text.Encoder.FallbackBuffer, SR.Format(), System.Text.UTF8Encoding.InRange(), int, System.Text.EncoderFallbackBuffer.InternalFallback(), System.Text.EncoderFallbackBuffer.InternalGetNextChar(), System.Text.Encoder.InternalHasFallbackBuffer, System.Text.EncoderFallbackBuffer.InternalInitialize(), System.BitConverter.IsLittleEndian, long, System.Text.EncoderFallbackBuffer.MovePrevious(), System.Text.EncoderNLS.MustFlush, System.Text.UTF8Encoding.PtrDiff(), System.Text.EncoderFallbackBuffer.Remaining, and System.Text.UTF8Encoding.UTF8Encoder.surrogateChar.