Terraria Decompiled: System.Security.Cryptography.CryptoStream.FlushFinalBlock
FlushFinalBlock()
void System.Security.Cryptography.CryptoStream.FlushFinalBlock () inline
Definition at line 118 of file CryptoStream.cs.
        {
            if (this._finalBlockTransformed)
            {
                throw new NotSupportedException("FlushFinalBlock() method was called twice on a CryptoStream. It can only be called once.");
            }
            byte[] array = this._transform.TransformFinalBlock(this._inputBuffer, 0, this._inputBufferIndex);
            this._finalBlockTransformed = true;
            if (this._canWrite && this._outputBufferIndex > 0)
            {
                this._stream.Write(this._outputBuffer, 0, this._outputBufferIndex);
                this._outputBufferIndex = 0;
            }
            if (this._canWrite)
            {
                this._stream.Write(array, 0, array.Length);
            }
            CryptoStream cryptoStream = this._stream as CryptoStream;
            if (cryptoStream != null)
            {
                if (!cryptoStream.HasFlushedFinalBlock)
                {
                    cryptoStream.FlushFinalBlock();
                }
            }
            else
            {
                this._stream.Flush();
            }
            if (this._inputBuffer != null)
            {
                Array.Clear(this._inputBuffer, 0, this._inputBuffer.Length);
            }
            if (this._outputBuffer != null)
            {
                Array.Clear(this._outputBuffer, 0, this._outputBuffer.Length);
            }
        }
References System.Security.Cryptography.CryptoStream._canWrite, System.Security.Cryptography.CryptoStream._finalBlockTransformed, System.Security.Cryptography.CryptoStream._inputBuffer, System.Security.Cryptography.CryptoStream._inputBufferIndex, System.Security.Cryptography.CryptoStream._outputBuffer, System.Security.Cryptography.CryptoStream._outputBufferIndex, System.Security.Cryptography.CryptoStream._stream, System.Security.Cryptography.CryptoStream._transform, System.array, System.Array.Clear(), System.Security.Cryptography.CryptoStream.CryptoStream(), System.IO.Stream.Flush(), System.Security.Cryptography.CryptoStream.FlushFinalBlock(), System.Security.Cryptography.CryptoStream.HasFlushedFinalBlock, System.Security.Cryptography.ICryptoTransform.TransformFinalBlock(), and System.IO.Stream.Write().
Referenced by System.Security.Cryptography.CryptoStream.Dispose(), System.Security.Cryptography.CryptoStream.FlushFinalBlock(), System.Security.Cryptography.MACTripleDES.HashFinal(), Terraria.Player.InternalSavePlayerFile(), and Terraria.Achievements.AchievementManager.Save().