Terraria Decompiled: System.Security.Cryptography.CryptoStream.Read
Read()
override int System.Security.Cryptography.CryptoStream.Read (byte[] buffer, int offset, int count) inline
Definition at line 252 of file CryptoStream.cs.
        {
            this.CheckReadArguments(buffer, offset, count);
            return this.ReadAsyncCore(buffer, offset, count, default(CancellationToken), false).GetAwaiter().GetResult();
        }
References System.Security.Cryptography.CryptoStream.CheckReadArguments(), System.count, System.Threading.Tasks.Task< TResult >.GetAwaiter(), System.Runtime.CompilerServices.TaskAwaiter< TResult >.GetResult(), System.offset, and System.Security.Cryptography.CryptoStream.ReadAsyncCore().