Terraria Decompiled: System.Security.Cryptography.CryptoStream.ReadAsyncInternal
ReadAsyncInternal()
async Task< int > System.Security.Cryptography.CryptoStream.ReadAsyncInternal (byte[] buffer, int offset, int count, CancellationToken cancellationToken) inline private
Definition at line 208 of file CryptoStream.cs.
        {
            SemaphoreSlim semaphore = this.AsyncActiveSemaphore;
            await semaphore.WaitAsync().ForceAsync();
            int num;
            try
            {
                num = await this.ReadAsyncCore(buffer, offset, count, cancellationToken, true);
            }
            finally
            {
                semaphore.Release();
            }
            return num;
        }
References System.Security.Cryptography.CryptoStream.AsyncActiveSemaphore, System.count, System.offset, System.Security.Cryptography.CryptoStream.ReadAsyncCore(), System.Threading.SemaphoreSlim.Release(), and System.Threading.SemaphoreSlim.WaitAsync().
Referenced by System.Security.Cryptography.CryptoStream.d__37.MoveNext(), and System.Security.Cryptography.CryptoStream.ReadAsync().