Terraria Decompiled: System.Security.Cryptography.CryptoStream.ReadAsyncCore
ReadAsyncCore()
async Task< int > System.Security.Cryptography.CryptoStream.ReadAsyncCore (byte[] buffer, int offset, int count, CancellationToken cancellationToken, bool useAsync) inline private
Definition at line 280 of file CryptoStream.cs.
        {
            int bytesToDeliver = count;
            int currentOutputIndex = offset;
            if (this._outputBufferIndex != 0)
            {
                if (this._outputBufferIndex > count)
                {
                    Buffer.BlockCopy(this._outputBuffer, 0, buffer, offset, count);
                    Buffer.BlockCopy(this._outputBuffer, count, this._outputBuffer, 0, this._outputBufferIndex - count);
                    this._outputBufferIndex -= count;
                    int num = this._outputBuffer.Length - this._outputBufferIndex;
                    CryptographicOperations.ZeroMemory(new Span<byte>(this._outputBuffer, this._outputBufferIndex, num));
                    return count;
                }
                Buffer.BlockCopy(this._outputBuffer, 0, buffer, offset, this._outputBufferIndex);
                bytesToDeliver -= this._outputBufferIndex;
                currentOutputIndex += this._outputBufferIndex;
                int num2 = this._outputBuffer.Length - this._outputBufferIndex;
                CryptographicOperations.ZeroMemory(new Span<byte>(this._outputBuffer, this._outputBufferIndex, num2));
                this._outputBufferIndex = 0;
            }
            int num3;
            if (this._finalBlockTransformed)
            {
                num3 = count - bytesToDeliver;
            }
            else
            {
                int num4 = bytesToDeliver / this._outputBlockSize;
                if (num4 > 1 && this._transform.CanTransformMultipleBlocks)
                {
                    int numWholeBlocksInBytes = num4 * this._inputBlockSize;
                    byte[] tempInputBuffer = ArrayPool<byte>.Shared.Rent(numWholeBlocksInBytes);
                    byte[] tempOutputBuffer = null;
                    try
                    {
                        int num5;
                        if (useAsync)
{
                            num5 = await this._stream.ReadAsync(new Memory<byte>(tempInputBuffer, this._inputBufferIndex, numWholeBlocksInBytes - this._inputBufferIndex), cancellationToken);
                        }
                        else
{
                            num5 = this._stream.Read(tempInputBuffer, this._inputBufferIndex, numWholeBlocksInBytes - this._inputBufferIndex);
                        }
                        int num6 = num5;
                        int num7 = this._inputBufferIndex + num6;
                        if (num7 < this._inputBlockSize)
{
                            Buffer.BlockCopy(tempInputBuffer, this._inputBufferIndex, this._inputBuffer, this._inputBufferIndex, num6);
                            this._inputBufferIndex = num7;
                        }
                        else
{
                            Buffer.BlockCopy(this._inputBuffer, 0, tempInputBuffer, 0, this._inputBufferIndex);
                            CryptographicOperations.ZeroMemory(new Span<byte>(this._inputBuffer, 0, this._inputBufferIndex));
                            num6 += this._inputBufferIndex;
                            this._inputBufferIndex = 0;
                            int num8 = num6 / this._inputBlockSize;
                            int num9 = num8 * this._inputBlockSize;
                            int num10 = num6 - num9;
                            if (num10 != 0)
{
                                this._inputBufferIndex = num10;
                                Buffer.BlockCopy(tempInputBuffer, num9, this._inputBuffer, 0, num10);
                            }
                            tempOutputBuffer = ArrayPool<byte>.Shared.Rent(num8 * this._outputBlockSize);
                            int num11 = this._transform.TransformBlock(tempInputBuffer, 0, num9, tempOutputBuffer, 0);
                            Buffer.BlockCopy(tempOutputBuffer, 0, buffer, currentOutputIndex, num11);
                            CryptographicOperations.ZeroMemory(new Span<byte>(tempOutputBuffer, 0, num11));
                            ArrayPool<byte>.Shared.Return(tempOutputBuffer, false);
                            tempOutputBuffer = null;
                            bytesToDeliver -= num11;
                            currentOutputIndex += num11;
                        }
                    }
                    finally
                    {
                        if (tempOutputBuffer != null)
{
                            CryptographicOperations.ZeroMemory(tempOutputBuffer);
                            ArrayPool<byte>.Shared.Return(tempOutputBuffer, false);
                            tempOutputBuffer = null;
                        }
                        CryptographicOperations.ZeroMemory(new Span<byte>(tempInputBuffer, 0, numWholeBlocksInBytes));
                        ArrayPool<byte>.Shared.Return(tempInputBuffer, false);
                        tempInputBuffer = null;
                    }
                    tempInputBuffer = null;
                    tempOutputBuffer = null;
                }
                while (bytesToDeliver > 0)
                {
                    while (this._inputBufferIndex < this._inputBlockSize)
                    {
                        int num5;
                        if (useAsync)
{
                            num5 = await this._stream.ReadAsync(new Memory<byte>(this._inputBuffer, this._inputBufferIndex, this._inputBlockSize - this._inputBufferIndex), cancellationToken);
                        }
                        else
{
                            num5 = this._stream.Read(this._inputBuffer, this._inputBufferIndex, this._inputBlockSize - this._inputBufferIndex);
                        }
                        int num6 = num5;
                        if (num6 != 0)
{
                            this._inputBufferIndex += num6;
                        }
                        else
{
                            byte[] array = this._transform.TransformFinalBlock(this._inputBuffer, 0, this._inputBufferIndex);
                            this._outputBuffer = array;
                            this._outputBufferIndex = array.Length;
                            this._finalBlockTransformed = true;
                            if (bytesToDeliver < this._outputBufferIndex)
{
                                Buffer.BlockCopy(this._outputBuffer, 0, buffer, currentOutputIndex, bytesToDeliver);
                                this._outputBufferIndex -= bytesToDeliver;
                                Buffer.BlockCopy(this._outputBuffer, bytesToDeliver, this._outputBuffer, 0, this._outputBufferIndex);
                                int num12 = this._outputBuffer.Length - this._outputBufferIndex;
                                CryptographicOperations.ZeroMemory(new Span<byte>(this._outputBuffer, this._outputBufferIndex, num12));
                                return count;
                            }
                            Buffer.BlockCopy(this._outputBuffer, 0, buffer, currentOutputIndex, this._outputBufferIndex);
                            bytesToDeliver -= this._outputBufferIndex;
                            this._outputBufferIndex = 0;
                            CryptographicOperations.ZeroMemory(this._outputBuffer);
                            return count - bytesToDeliver;
                        }
                    }
                    int num11 = this._transform.TransformBlock(this._inputBuffer, 0, this._inputBlockSize, this._outputBuffer, 0);
                    this._inputBufferIndex = 0;
                    if (bytesToDeliver < num11)
                    {
                        Buffer.BlockCopy(this._outputBuffer, 0, buffer, currentOutputIndex, bytesToDeliver);
                        this._outputBufferIndex = num11 - bytesToDeliver;
                        Buffer.BlockCopy(this._outputBuffer, bytesToDeliver, this._outputBuffer, 0, this._outputBufferIndex);
                        int num13 = this._outputBuffer.Length - this._outputBufferIndex;
                        CryptographicOperations.ZeroMemory(new Span<byte>(this._outputBuffer, this._outputBufferIndex, num13));
                        return count;
                    }
                    Buffer.BlockCopy(this._outputBuffer, 0, buffer, currentOutputIndex, num11);
                    CryptographicOperations.ZeroMemory(new Span<byte>(this._outputBuffer, 0, num11));
                    currentOutputIndex += num11;
                    bytesToDeliver -= num11;
                }
                num3 = count;
            }
            return num3;
        }
References System.Security.Cryptography.CryptoStream._finalBlockTransformed, System.Security.Cryptography.CryptoStream._inputBlockSize, System.Security.Cryptography.CryptoStream._inputBuffer, System.Security.Cryptography.CryptoStream._inputBufferIndex, System.Security.Cryptography.CryptoStream._outputBlockSize, System.Security.Cryptography.CryptoStream._outputBuffer, System.Security.Cryptography.CryptoStream._outputBufferIndex, System.Security.Cryptography.CryptoStream._stream, System.Security.Cryptography.CryptoStream._transform, System.array, System.Buffer.BlockCopy(), System.Security.Cryptography.ICryptoTransform.CanTransformMultipleBlocks, System.count, System.offset, System.IO.Stream.Read(), System.IO.Stream.ReadAsync(), System.Buffers.ArrayPool< T >.Shared, System.Security.Cryptography.ICryptoTransform.TransformBlock(), System.Security.Cryptography.ICryptoTransform.TransformFinalBlock(), and System.Security.Cryptography.CryptographicOperations.ZeroMemory().
Referenced by System.Security.Cryptography.CryptoStream.d__37.MoveNext(), System.Security.Cryptography.CryptoStream.d__42.MoveNext(), System.Security.Cryptography.CryptoStream.Read(), and System.Security.Cryptography.CryptoStream.ReadAsyncInternal().