Terraria Decompiled: System.Security.Cryptography.CryptoStream.WriteAsyncCore
WriteAsyncCore()
async Task System.Security.Cryptography.CryptoStream.WriteAsyncCore (byte[] buffer, int offset, int count, CancellationToken cancellationToken, bool useAsync) inline private
Definition at line 496 of file CryptoStream.cs.
        {
            int bytesToWrite = count;
            int currentInputIndex = offset;
            if (this._inputBufferIndex > 0)
            {
                if (count < this._inputBlockSize - this._inputBufferIndex)
                {
                    Buffer.BlockCopy(buffer, offset, this._inputBuffer, this._inputBufferIndex, count);
                    this._inputBufferIndex += count;
                    return;
                }
                Buffer.BlockCopy(buffer, offset, this._inputBuffer, this._inputBufferIndex, this._inputBlockSize - this._inputBufferIndex);
                currentInputIndex += this._inputBlockSize - this._inputBufferIndex;
                bytesToWrite -= this._inputBlockSize - this._inputBufferIndex;
                this._inputBufferIndex = this._inputBlockSize;
            }
            if (this._outputBufferIndex > 0)
            {
                if (useAsync)
                {
                    await this._stream.WriteAsync(new ReadOnlyMemory<byte>(this._outputBuffer, 0, this._outputBufferIndex), cancellationToken);
                }
                else
                {
                    this._stream.Write(this._outputBuffer, 0, this._outputBufferIndex);
                }
                this._outputBufferIndex = 0;
            }
            if (this._inputBufferIndex == this._inputBlockSize)
            {
                int numOutputBytes = this._transform.TransformBlock(this._inputBuffer, 0, this._inputBlockSize, this._outputBuffer, 0);
                if (useAsync)
                {
                    await this._stream.WriteAsync(new ReadOnlyMemory<byte>(this._outputBuffer, 0, numOutputBytes), cancellationToken);
                }
                else
                {
                    this._stream.Write(this._outputBuffer, 0, numOutputBytes);
                }
                this._inputBufferIndex = 0;
            }
            while (bytesToWrite > 0)
            {
                if (bytesToWrite < this._inputBlockSize)
                {
                    Buffer.BlockCopy(buffer, currentInputIndex, this._inputBuffer, 0, bytesToWrite);
                    this._inputBufferIndex += bytesToWrite;
                    break;
                }
                int num = bytesToWrite / this._inputBlockSize;
                if (this._transform.CanTransformMultipleBlocks && num > 1)
                {
                    int numWholeBlocksInBytes = num * this._inputBlockSize;
                    byte[] tempOutputBuffer = ArrayPool<byte>.Shared.Rent(num * this._outputBlockSize);
                    int numOutputBytes = 0;
                    try
                    {
                        numOutputBytes = this._transform.TransformBlock(buffer, currentInputIndex, numWholeBlocksInBytes, tempOutputBuffer, 0);
                        if (useAsync)
{
                            await this._stream.WriteAsync(new ReadOnlyMemory<byte>(tempOutputBuffer, 0, numOutputBytes), cancellationToken);
                        }
                        else
{
                            this._stream.Write(tempOutputBuffer, 0, numOutputBytes);
                        }
                        currentInputIndex += numWholeBlocksInBytes;
                        bytesToWrite -= numWholeBlocksInBytes;
                    }
                    finally
                    {
                        CryptographicOperations.ZeroMemory(new Span<byte>(tempOutputBuffer, 0, numOutputBytes));
                        ArrayPool<byte>.Shared.Return(tempOutputBuffer, false);
                        tempOutputBuffer = null;
                    }
                    tempOutputBuffer = null;
                }
                else
                {
                    int numOutputBytes = this._transform.TransformBlock(buffer, currentInputIndex, this._inputBlockSize, this._outputBuffer, 0);
                    if (useAsync)
                    {
                        await this._stream.WriteAsync(new ReadOnlyMemory<byte>(this._outputBuffer, 0, numOutputBytes), cancellationToken);
                    }
                    else
                    {
                        this._stream.Write(this._outputBuffer, 0, numOutputBytes);
                    }
                    currentInputIndex += this._inputBlockSize;
                    bytesToWrite -= this._inputBlockSize;
                }
            }
        }
References System.Security.Cryptography.CryptoStream._inputBlockSize, System.Security.Cryptography.CryptoStream._inputBuffer, System.Security.Cryptography.CryptoStream._inputBufferIndex, System.Security.Cryptography.CryptoStream._outputBlockSize, System.Security.Cryptography.CryptoStream._outputBuffer, System.Security.Cryptography.CryptoStream._outputBufferIndex, System.Security.Cryptography.CryptoStream._stream, System.Security.Cryptography.CryptoStream._transform, System.Buffer.BlockCopy(), System.Security.Cryptography.ICryptoTransform.CanTransformMultipleBlocks, System.count, System.offset, System.Buffers.ArrayPool< T >.Shared, System.Security.Cryptography.ICryptoTransform.TransformBlock(), System.IO.Stream.Write(), System.IO.Stream.WriteAsync(), and System.Security.Cryptography.CryptographicOperations.ZeroMemory().
Referenced by System.Security.Cryptography.CryptoStream.d__46.MoveNext(), System.Security.Cryptography.CryptoStream.d__49.MoveNext(), System.Security.Cryptography.CryptoStream.Write(), and System.Security.Cryptography.CryptoStream.WriteAsyncInternal().