Terraria Decompiled: System.Security.Cryptography.CryptoStream.WriteAsyncInternal
WriteAsyncInternal()
async Task System.Security.Cryptography.CryptoStream.WriteAsyncInternal (byte[] buffer, int offset, int count, CancellationToken cancellationToken) inline private
Definition at line 453 of file CryptoStream.cs.
        {
            SemaphoreSlim semaphore = this.AsyncActiveSemaphore;
            await semaphore.WaitAsync().ForceAsync();
            try
            {
                await this.WriteAsyncCore(buffer, offset, count, cancellationToken, true);
            }
            finally
            {
                semaphore.Release();
            }
        }
References System.Security.Cryptography.CryptoStream.AsyncActiveSemaphore, System.count, System.offset, System.Threading.SemaphoreSlim.Release(), System.Threading.SemaphoreSlim.WaitAsync(), and System.Security.Cryptography.CryptoStream.WriteAsyncCore().
Referenced by System.Security.Cryptography.CryptoStream.d__46.MoveNext(), and System.Security.Cryptography.CryptoStream.WriteAsync().