Terraria Decompiled: System.Security.Cryptography.CryptoStream.Dispose
Dispose()
override void System.Security.Cryptography.CryptoStream.Dispose (bool disposing) inline protected virtual
Reimplemented from System.IO.Stream.
Definition at line 598 of file CryptoStream.cs.
        {
            try
            {
                if (disposing)
                {
                    if (!this._finalBlockTransformed)
                    {
                        this.FlushFinalBlock();
                    }
                    if (!this._leaveOpen)
                    {
                        this._stream.Dispose();
                    }
                }
            }
            finally
            {
                try
                {
                    this._finalBlockTransformed = true;
                    if (this._inputBuffer != null)
                    {
                        Array.Clear(this._inputBuffer, 0, this._inputBuffer.Length);
                    }
                    if (this._outputBuffer != null)
                    {
                        Array.Clear(this._outputBuffer, 0, this._outputBuffer.Length);
                    }
                    this._inputBuffer = null;
                    this._outputBuffer = null;
                    this._canRead = false;
                    this._canWrite = false;
                }
                finally
                {
                    base.Dispose(disposing);
                }
            }
        }
References System.Security.Cryptography.CryptoStream._finalBlockTransformed, System.Security.Cryptography.CryptoStream._inputBuffer, System.Security.Cryptography.CryptoStream._leaveOpen, System.Security.Cryptography.CryptoStream._outputBuffer, System.Security.Cryptography.CryptoStream._stream, System.Array.Clear(), System.IO.Stream.Dispose(), and System.Security.Cryptography.CryptoStream.FlushFinalBlock().