Terraria Decompiled: System.Threading.SpinWait.SpinOnceCore
SpinOnceCore()
void System.Threading.SpinWait.SpinOnceCore (int sleep1Threshold) inline private
Definition at line 55 of file SpinWait.cs.
        {
            if ((this._count >= 10 && ((this._count >= sleep1Threshold && sleep1Threshold >= 0) || (this._count - 10) % 2 == 0)) || PlatformHelper.IsSingleProcessor)
            {
                if (this._count >= sleep1Threshold && sleep1Threshold >= 0)
                {
                    RuntimeThread.Sleep(1);
                }
                else if (((this._count >= 10) ? ((this._count - 10) / 2) : this._count) % 5 == 4)
                {
                    RuntimeThread.Sleep(0);
                }
                else
                {
                    RuntimeThread.Yield();
                }
            }
            else
            {
                int num = RuntimeThread.OptimalMaxSpinWaitsPerSpinIteration;
                if (this._count <= 30 && 1 << this._count < num)
                {
                    num = 1 << this._count;
                }
                RuntimeThread.SpinWait(num);
            }
            this._count = ((this._count == int.MaxValue) ? 10 : (this._count + 1));
        }
References System.Threading.SpinWait._count, System.Threading.PlatformHelper.IsSingleProcessor, Internal.Runtime.Augments.RuntimeThread.OptimalMaxSpinWaitsPerSpinIteration, Internal.Runtime.Augments.RuntimeThread.Sleep(), Internal.Runtime.Augments.RuntimeThread.SpinWait(), and Internal.Runtime.Augments.RuntimeThread.Yield().
Referenced by System.Threading.SpinWait.SpinOnce(), and System.Threading.SpinWait.SpinOnce().