Terraria Decompiled: System.Security.Cryptography.RijndaelManagedTransform.DecryptData
DecryptData()
unsafe int System.Security.Cryptography.RijndaelManagedTransform.DecryptData (byte[] inputBuffer, int inputOffset, int inputCount, ref byte[] outputBuffer, int outputOffset, PaddingMode paddingMode, bool fLast) inline private
Definition at line 553 of file RijndaelManagedTransform.cs.
        {
            if (inputBuffer.Length < inputOffset + inputCount)
            {
                throw new CryptographicException(Environment.GetResourceString("Input buffer contains insufficient data."));
            }
            if (outputBuffer == null)
            {
                outputBuffer = new byte[inputCount];
                outputOffset = 0;
            }
            else if (outputBuffer.Length - outputOffset < inputCount)
            {
                throw new CryptographicException(Environment.GetResourceString("Input buffer contains insufficient data."));
            }
            int[] encryptindex;
            int* ptr;
            if ((encryptindex = this.m_encryptindex) == null || encryptindex.Length == 0)
            {
                ptr = null;
            }
            else
            {
                ptr = &encryptindex[0];
            }
            int[] encryptKeyExpansion;
            int* ptr2;
            if ((encryptKeyExpansion = this.m_encryptKeyExpansion) == null || encryptKeyExpansion.Length == 0)
            {
                ptr2 = null;
            }
            else
            {
                ptr2 = &encryptKeyExpansion[0];
            }
            int[] decryptindex;
            int* ptr3;
            if ((decryptindex = this.m_decryptindex) == null || decryptindex.Length == 0)
            {
                ptr3 = null;
            }
            else
            {
                ptr3 = &decryptindex[0];
            }
            int[] decryptKeyExpansion;
            int* ptr4;
            if ((decryptKeyExpansion = this.m_decryptKeyExpansion) == null || decryptKeyExpansion.Length == 0)
            {
                ptr4 = null;
            }
            else
            {
                ptr4 = &decryptKeyExpansion[0];
            }
            int[] array;
            int* ptr5;
            if ((array = RijndaelManagedTransform.s_T) == null || array.Length == 0)
            {
                ptr5 = null;
            }
            else
            {
                ptr5 = &array[0];
            }
            int[] array2;
            int* ptr6;
            if ((array2 = RijndaelManagedTransform.s_TF) == null || array2.Length == 0)
            {
                ptr6 = null;
            }
            else
            {
                ptr6 = &array2[0];
            }
            int[] array3;
            int* ptr7;
            if ((array3 = RijndaelManagedTransform.s_iT) == null || array3.Length == 0)
            {
                ptr7 = null;
            }
            else
            {
                ptr7 = &array3[0];
            }
            int[] array4;
            int* ptr8;
            if ((array4 = RijndaelManagedTransform.s_iTF) == null || array4.Length == 0)
            {
                ptr8 = null;
            }
            else
            {
                ptr8 = &array4[0];
            }
            int* ptr9;
            int* ptr10;
            int num;
            int num2;
            int num3;
            checked
            {
                ptr9 = stackalloc int[unchecked((UIntPtr)this.m_Nb) * 4];
                ptr10 = stackalloc int[unchecked((UIntPtr)this.m_Nb) * 4];
                num = inputCount / this.m_inputBlockSize;
                num2 = inputOffset;
                num3 = outputOffset;
            }
            for (int i = 0; i < num; i++)
            {
                if (this.m_cipherMode == CipherMode.CFB)
                {
                    int j = 0;
                    for (int k = 0; k < this.m_Nb; k++)
                    {
                        int num4 = (int)this.m_shiftRegister[j++];
                        int num5 = (int)this.m_shiftRegister[j++];
                        int num6 = (int)this.m_shiftRegister[j++];
                        int num7 = (int)this.m_shiftRegister[j++];
                        ptr9[k] = (num7 << 24) | (num6 << 16) | (num5 << 8) | num4;
                    }
                }
                else
                {
                    int j = num2;
                    for (int l = 0; l < this.m_Nb; l++)
                    {
                        int num8 = (int)inputBuffer[j++];
                        int num9 = (int)inputBuffer[j++];
                        int num10 = (int)inputBuffer[j++];
                        int num11 = (int)inputBuffer[j++];
                        ptr9[l] = (num11 << 24) | (num10 << 16) | (num9 << 8) | num8;
                    }
                }
                if (this.m_cipherMode == CipherMode.CFB)
                {
                    this.Enc(ptr, ptr2, ptr5, ptr6, ptr9, ptr10);
                    int j = num2;
                    int num12 = 0;
                    while (num12 < this.m_Nb && j < num2 + this.m_inputBlockSize)
                    {
                        outputBuffer[num3++] = (byte)((ptr10[num12] & 255) ^ (int)inputBuffer[j++]);
                        if (j >= num2 + this.m_inputBlockSize)
{
                            break;
                        }
                        outputBuffer[num3++] = (byte)(((ptr10[num12] >> 8) & 255) ^ (int)inputBuffer[j++]);
                        if (j >= num2 + this.m_inputBlockSize)
{
                            break;
                        }
                        outputBuffer[num3++] = (byte)(((ptr10[num12] >> 16) & 255) ^ (int)inputBuffer[j++]);
                        if (j >= num2 + this.m_inputBlockSize)
{
                            break;
                        }
                        outputBuffer[num3++] = (byte)(((ptr10[num12] >> 24) & 255) ^ (int)inputBuffer[j++]);
                        num12++;
                    }
                    for (j = 0; j < this.m_blockSizeBytes - this.m_inputBlockSize; j++)
                    {
                        this.m_shiftRegister[j] = this.m_shiftRegister[j + this.m_inputBlockSize];
                    }
                    Buffer.InternalBlockCopy(inputBuffer, num2, this.m_shiftRegister, this.m_blockSizeBytes - this.m_inputBlockSize, this.m_inputBlockSize);
                }
                else
                {
                    this.Dec(ptr3, ptr4, ptr7, ptr8, ptr9, ptr10);
                    if (this.m_cipherMode == CipherMode.CBC)
                    {
                        int j = num2;
                        for (int m = 0; m < this.m_Nb; m++)
{
                            ptr10[m] ^= this.m_lastBlockBuffer[m];
                            int num13 = (int)inputBuffer[j++];
                            int num14 = (int)inputBuffer[j++];
                            int num15 = (int)inputBuffer[j++];
                            int num16 = (int)inputBuffer[j++];
                            this.m_lastBlockBuffer[m] = (num16 << 24) | (num15 << 16) | (num14 << 8) | num13;
                        }
                    }
                    for (int n = 0; n < this.m_Nb; n++)
                    {
                        outputBuffer[num3++] = (byte)(ptr10[n] & 255);
                        outputBuffer[num3++] = (byte)((ptr10[n] >> 8) & 255);
                        outputBuffer[num3++] = (byte)((ptr10[n] >> 16) & 255);
                        outputBuffer[num3++] = (byte)((ptr10[n] >> 24) & 255);
                    }
                }
                num2 += this.m_inputBlockSize;
            }
            if (!fLast)
            {
                return inputCount;
            }
            byte[] array5 = outputBuffer;
            switch (paddingMode)
            {
            case PaddingMode.PKCS7:
            {
                if (inputCount == 0)
                {
                    throw new CryptographicException(Environment.GetResourceString("Padding is invalid and cannot be removed."));
                }
                int num17 = (int)outputBuffer[inputCount - 1];
                if (num17 > outputBuffer.Length || num17 > this.InputBlockSize || num17 <= 0)
                {
                    throw new CryptographicException(Environment.GetResourceString("Padding is invalid and cannot be removed."));
                }
                for (int j = 1; j <= num17; j++)
                {
                    if ((int)outputBuffer[inputCount - j] != num17)
                    {
                        throw new CryptographicException(Environment.GetResourceString("Padding is invalid and cannot be removed."));
                    }
                }
                array5 = new byte[outputBuffer.Length - num17];
                Buffer.InternalBlockCopy(outputBuffer, 0, array5, 0, outputBuffer.Length - num17);
                break;
            }
            case PaddingMode.ANSIX923:
            {
                if (inputCount == 0)
                {
                    throw new CryptographicException(Environment.GetResourceString("Padding is invalid and cannot be removed."));
                }
                int num17 = (int)outputBuffer[inputCount - 1];
                if (num17 > outputBuffer.Length || num17 > this.InputBlockSize || num17 <= 0)
                {
                    throw new CryptographicException(Environment.GetResourceString("Padding is invalid and cannot be removed."));
                }
                for (int j = 2; j <= num17; j++)
                {
                    if (outputBuffer[inputCount - j] != 0)
                    {
                        throw new CryptographicException(Environment.GetResourceString("Padding is invalid and cannot be removed."));
                    }
                }
                array5 = new byte[outputBuffer.Length - num17];
                Buffer.InternalBlockCopy(outputBuffer, 0, array5, 0, outputBuffer.Length - num17);
                break;
            }
            case PaddingMode.ISO10126:
            {
                if (inputCount == 0)
                {
                    throw new CryptographicException(Environment.GetResourceString("Padding is invalid and cannot be removed."));
                }
                int num17 = (int)outputBuffer[inputCount - 1];
                if (num17 > outputBuffer.Length || num17 > this.InputBlockSize || num17 <= 0)
                {
                    throw new CryptographicException(Environment.GetResourceString("Padding is invalid and cannot be removed."));
                }
                array5 = new byte[outputBuffer.Length - num17];
                Buffer.InternalBlockCopy(outputBuffer, 0, array5, 0, outputBuffer.Length - num17);
                break;
            }
            }
            outputBuffer = array5;
            return array5.Length;
        }
References System.array, System.Security.Cryptography.RijndaelManagedTransform.Dec(), System.Security.Cryptography.RijndaelManagedTransform.Enc(), System.Environment.GetResourceString(), int, System.Buffer.InternalBlockCopy(), System.Security.Cryptography.RijndaelManagedTransform.m_blockSizeBytes, System.Security.Cryptography.RijndaelManagedTransform.m_cipherMode, System.Security.Cryptography.RijndaelManagedTransform.m_decryptindex, System.Security.Cryptography.RijndaelManagedTransform.m_decryptKeyExpansion, System.Security.Cryptography.RijndaelManagedTransform.m_encryptindex, System.Security.Cryptography.RijndaelManagedTransform.m_encryptKeyExpansion, System.Security.Cryptography.RijndaelManagedTransform.m_inputBlockSize, System.Security.Cryptography.RijndaelManagedTransform.m_lastBlockBuffer, System.Security.Cryptography.RijndaelManagedTransform.m_Nb, System.Security.Cryptography.RijndaelManagedTransform.m_shiftRegister, System.Security.Cryptography.RijndaelManagedTransform.s_iT, System.Security.Cryptography.RijndaelManagedTransform.s_iTF, System.Security.Cryptography.RijndaelManagedTransform.s_T, and System.Security.Cryptography.RijndaelManagedTransform.s_TF.
Referenced by System.Security.Cryptography.RijndaelManagedTransform.TransformBlock(), and System.Security.Cryptography.RijndaelManagedTransform.TransformFinalBlock().