Terraria Decompiled: System.Security.Cryptography.RijndaelManagedTransform.GenerateKeyExpansion
GenerateKeyExpansion()
void System.Security.Cryptography.RijndaelManagedTransform.GenerateKeyExpansion (byte[] rgbKey) inline private
Definition at line 889 of file RijndaelManagedTransform.cs.
        {
            int num = ((this.m_blockSizeBits > rgbKey.Length * 8) ? this.m_blockSizeBits : (rgbKey.Length * 8));
            if (num != 128)
            {
                if (num != 192)
                {
                    if (num != 256)
                    {
                        throw new CryptographicException(Environment.GetResourceString("Specified key is not a valid size for this algorithm."));
                    }
                    this.m_Nr = 14;
                }
                else
                {
                    this.m_Nr = 12;
                }
            }
            else
            {
                this.m_Nr = 10;
            }
            this.m_encryptKeyExpansion = new int[this.m_Nb * (this.m_Nr + 1)];
            this.m_decryptKeyExpansion = new int[this.m_Nb * (this.m_Nr + 1)];
            int num2 = 0;
            for (int i = 0; i < this.m_Nk; i++)
            {
                int num3 = (int)rgbKey[num2++];
                int num4 = (int)rgbKey[num2++];
                int num5 = (int)rgbKey[num2++];
                int num6 = (int)rgbKey[num2++];
                this.m_encryptKeyExpansion[i] = (num6 << 24) | (num5 << 16) | (num4 << 8) | num3;
            }
            if (this.m_Nk <= 6)
            {
                for (int j = this.m_Nk; j < this.m_Nb * (this.m_Nr + 1); j++)
                {
                    int num7 = this.m_encryptKeyExpansion[j - 1];
                    if (j % this.m_Nk == 0)
                    {
                        num7 = RijndaelManagedTransform.SubWord(RijndaelManagedTransform.rot3(num7));
                        num7 ^= RijndaelManagedTransform.s_Rcon[j / this.m_Nk - 1];
                    }
                    this.m_encryptKeyExpansion[j] = this.m_encryptKeyExpansion[j - this.m_Nk] ^ num7;
                }
            }
            else
            {
                for (int k = this.m_Nk; k < this.m_Nb * (this.m_Nr + 1); k++)
                {
                    int num7 = this.m_encryptKeyExpansion[k - 1];
                    if (k % this.m_Nk == 0)
                    {
                        num7 = RijndaelManagedTransform.SubWord(RijndaelManagedTransform.rot3(num7));
                        num7 ^= RijndaelManagedTransform.s_Rcon[k / this.m_Nk - 1];
                    }
                    else if (k % this.m_Nk == 4)
                    {
                        num7 = RijndaelManagedTransform.SubWord(num7);
                    }
                    this.m_encryptKeyExpansion[k] = this.m_encryptKeyExpansion[k - this.m_Nk] ^ num7;
                }
            }
            for (int l = 0; l < this.m_Nb; l++)
            {
                this.m_decryptKeyExpansion[l] = this.m_encryptKeyExpansion[l];
                this.m_decryptKeyExpansion[this.m_Nb * this.m_Nr + l] = this.m_encryptKeyExpansion[this.m_Nb * this.m_Nr + l];
            }
            for (int m = this.m_Nb; m < this.m_Nb * this.m_Nr; m++)
            {
                int num8 = this.m_encryptKeyExpansion[m];
                int num9 = RijndaelManagedTransform.MulX(num8);
                int num10 = RijndaelManagedTransform.MulX(num9);
                int num11 = RijndaelManagedTransform.MulX(num10);
                int num12 = num8 ^ num11;
                this.m_decryptKeyExpansion[m] = num9 ^ num10 ^ num11 ^ RijndaelManagedTransform.rot3(num9 ^ num12) ^ RijndaelManagedTransform.rot2(num10 ^ num12) ^ RijndaelManagedTransform.rot1(num12);
            }
        }
References System.Environment.GetResourceString(), int, System.Security.Cryptography.RijndaelManagedTransform.m_blockSizeBits, System.Security.Cryptography.RijndaelManagedTransform.m_decryptKeyExpansion, System.Security.Cryptography.RijndaelManagedTransform.m_encryptKeyExpansion, System.Security.Cryptography.RijndaelManagedTransform.m_Nb, System.Security.Cryptography.RijndaelManagedTransform.m_Nk, System.Security.Cryptography.RijndaelManagedTransform.m_Nr, System.Security.Cryptography.RijndaelManagedTransform.MulX(), System.Security.Cryptography.RijndaelManagedTransform.rot1(), System.Security.Cryptography.RijndaelManagedTransform.rot2(), System.Security.Cryptography.RijndaelManagedTransform.rot3(), System.Security.Cryptography.RijndaelManagedTransform.s_Rcon, and System.Security.Cryptography.RijndaelManagedTransform.SubWord().
Referenced by System.Security.Cryptography.RijndaelManagedTransform.RijndaelManagedTransform().