Terraria Decompiled: System.Security.Cryptography.RijndaelManagedTransform.TransformBlock
TransformBlock()
int System.Security.Cryptography.RijndaelManagedTransform.TransformBlock (byte[] inputBuffer, int inputOffset, int inputCount, byte[] outputBuffer, int outputOffset) inline
Implements System.Security.Cryptography.ICryptoTransform.
Definition at line 199 of file RijndaelManagedTransform.cs.
        {
            if (inputBuffer == null)
            {
                throw new ArgumentNullException("inputBuffer");
            }
            if (outputBuffer == null)
            {
                throw new ArgumentNullException("outputBuffer");
            }
            if (inputOffset < 0)
            {
                throw new ArgumentOutOfRangeException("inputOffset", Environment.GetResourceString("Non-negative number required."));
            }
            if (inputCount <= 0 || inputCount % this.InputBlockSize != 0 || inputCount > inputBuffer.Length)
            {
                throw new ArgumentException(Environment.GetResourceString("Value was invalid."));
            }
            if (inputBuffer.Length - inputCount < inputOffset)
            {
                throw new ArgumentException(Environment.GetResourceString("Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection."));
            }
            if (this.m_transformMode == RijndaelManagedTransformMode.Encrypt)
            {
                return this.EncryptData(inputBuffer, inputOffset, inputCount, ref outputBuffer, outputOffset, this.m_paddingValue, false);
            }
            if (this.m_paddingValue == PaddingMode.Zeros || this.m_paddingValue == PaddingMode.None)
            {
                return this.DecryptData(inputBuffer, inputOffset, inputCount, ref outputBuffer, outputOffset, this.m_paddingValue, false);
            }
            if (this.m_depadBuffer == null)
            {
                this.m_depadBuffer = new byte[this.InputBlockSize];
                int num = inputCount - this.InputBlockSize;
                Buffer.InternalBlockCopy(inputBuffer, inputOffset + num, this.m_depadBuffer, 0, this.InputBlockSize);
                return this.DecryptData(inputBuffer, inputOffset, num, ref outputBuffer, outputOffset, this.m_paddingValue, false);
            }
            int num2 = this.DecryptData(this.m_depadBuffer, 0, this.m_depadBuffer.Length, ref outputBuffer, outputOffset, this.m_paddingValue, false);
            outputOffset += this.OutputBlockSize;
            int num3 = inputCount - this.InputBlockSize;
            Buffer.InternalBlockCopy(inputBuffer, inputOffset + num3, this.m_depadBuffer, 0, this.InputBlockSize);
            num2 = this.DecryptData(inputBuffer, inputOffset, num3, ref outputBuffer, outputOffset, this.m_paddingValue, false);
            return this.OutputBlockSize + num2;
        }
References System.Security.Cryptography.RijndaelManagedTransform.DecryptData(), System.Security.Cryptography.RijndaelManagedTransform.EncryptData(), System.Environment.GetResourceString(), System.Security.Cryptography.RijndaelManagedTransform.InputBlockSize, System.Buffer.InternalBlockCopy(), System.Security.Cryptography.RijndaelManagedTransform.m_depadBuffer, System.Security.Cryptography.RijndaelManagedTransform.m_paddingValue, System.Security.Cryptography.RijndaelManagedTransform.m_transformMode, and System.Security.Cryptography.RijndaelManagedTransform.OutputBlockSize.