Terraria Decompiled: System.Security.Cryptography.RijndaelManagedTransform.EncryptData
EncryptData()
unsafe int System.Security.Cryptography.RijndaelManagedTransform.EncryptData (byte[] inputBuffer, int inputOffset, int inputCount, ref byte[] outputBuffer, int outputOffset, PaddingMode paddingMode, bool fLast) inline private
Definition at line 306 of file RijndaelManagedTransform.cs.
        {
            if (inputBuffer.Length < inputOffset + inputCount)
            {
                throw new CryptographicException(Environment.GetResourceString("Input buffer contains insufficient data."));
            }
            int num = 0;
            int num2 = inputCount % this.m_inputBlockSize;
            byte[] array = null;
            int num3 = inputOffset;
            if (fLast)
            {
                switch (paddingMode)
                {
                case PaddingMode.None:
                    if (num2 != 0)
                    {
                        throw new CryptographicException(Environment.GetResourceString("Length of the data to encrypt is invalid."));
                    }
                    break;
                case PaddingMode.PKCS7:
                    num = this.m_inputBlockSize - num2;
                    break;
                case PaddingMode.Zeros:
                    if (num2 != 0)
                    {
                        num = this.m_inputBlockSize - num2;
                    }
                    break;
                case PaddingMode.ANSIX923:
                    num = this.m_inputBlockSize - num2;
                    break;
                case PaddingMode.ISO10126:
                    num = this.m_inputBlockSize - num2;
                    break;
                }
                if (num != 0)
                {
                    array = new byte[num];
                    switch (paddingMode)
                    {
                    case PaddingMode.PKCS7:
                    {
                        for (int i = 0; i < num; i++)
{
                            array[i] = (byte)num;
                        }
                        break;
                    }
                    case PaddingMode.ANSIX923:
                        array[num - 1] = (byte)num;
                        break;
                    case PaddingMode.ISO10126:
                        Utils.StaticRandomNumberGenerator.GetBytes(array);
                        array[num - 1] = (byte)num;
                        break;
                    }
                }
            }
            if (outputBuffer == null)
            {
                outputBuffer = new byte[inputCount + num];
                outputOffset = 0;
            }
            else if (outputBuffer.Length - outputOffset < inputCount + num)
            {
                throw new CryptographicException(Environment.GetResourceString("Input buffer contains insufficient data."));
            }
            int[] array2;
            int* ptr;
            if ((array2 = this.m_encryptindex) == null || array2.Length == 0)
            {
                ptr = null;
            }
            else
            {
                ptr = &array2[0];
            }
            int[] array3;
            int* ptr2;
            if ((array3 = this.m_encryptKeyExpansion) == null || array3.Length == 0)
            {
                ptr2 = null;
            }
            else
            {
                ptr2 = &array3[0];
            }
            int[] array4;
            int* ptr3;
            if ((array4 = RijndaelManagedTransform.s_T) == null || array4.Length == 0)
            {
                ptr3 = null;
            }
            else
            {
                ptr3 = &array4[0];
            }
            int[] array5;
            int* ptr4;
            if ((array5 = RijndaelManagedTransform.s_TF) == null || array5.Length == 0)
            {
                ptr4 = null;
            }
            else
            {
                ptr4 = &array5[0];
            }
            int* ptr5;
            int* ptr6;
            checked
            {
                ptr5 = stackalloc int[unchecked((UIntPtr)this.m_Nb) * 4];
                ptr6 = stackalloc int[unchecked((UIntPtr)this.m_Nb) * 4];
            }
            int num4 = (inputCount + num) / this.m_inputBlockSize;
            int num5 = outputOffset;
            for (int j = 0; j < num4; j++)
            {
                if (this.m_cipherMode == CipherMode.CFB)
                {
                    Buffer.Memcpy((byte*)ptr5, 0, this.m_shiftRegister, 0, this.m_blockSizeBytes);
                }
                else if (j != num4 - 1 || num == 0)
                {
                    Buffer.Memcpy((byte*)ptr5, 0, inputBuffer, num3, this.m_blockSizeBytes);
                }
                else
                {
                    int num6 = 0;
                    int i = num3;
                    for (int k = 0; k < this.m_Nb; k++)
                    {
                        int num7 = (int)((i >= num3 + num2) ? array[num6++] : inputBuffer[i++]);
                        int num8 = (int)((i >= num3 + num2) ? array[num6++] : inputBuffer[i++]);
                        int num9 = (int)((i >= num3 + num2) ? array[num6++] : inputBuffer[i++]);
                        int num10 = (int)((i >= num3 + num2) ? array[num6++] : inputBuffer[i++]);
                        ptr5[k] = (num10 << 24) | (num9 << 16) | (num8 << 8) | num7;
                    }
                }
                if (this.m_cipherMode == CipherMode.CBC)
                {
                    for (int l = 0; l < this.m_Nb; l++)
                    {
                        ptr5[l] ^= this.m_lastBlockBuffer[l];
                    }
                }
                this.Enc(ptr, ptr2, ptr3, ptr4, ptr5, ptr6);
                if (this.m_cipherMode == CipherMode.CFB)
                {
                    int i = num3;
                    if (j != num4 - 1 || num == 0)
                    {
                        for (int m = 0; m < this.m_Nb; m++)
{
                            if (i >= num3 + this.m_inputBlockSize)
{
                                break;
                            }
                            outputBuffer[num5++] = (byte)((ptr6[m] & 255) ^ (int)inputBuffer[i++]);
                            if (i >= num3 + this.m_inputBlockSize)
{
                                break;
                            }
                            outputBuffer[num5++] = (byte)(((ptr6[m] >> 8) & 255) ^ (int)inputBuffer[i++]);
                            if (i >= num3 + this.m_inputBlockSize)
{
                                break;
                            }
                            outputBuffer[num5++] = (byte)(((ptr6[m] >> 16) & 255) ^ (int)inputBuffer[i++]);
                            if (i >= num3 + this.m_inputBlockSize)
{
                                break;
                            }
                            outputBuffer[num5++] = (byte)(((ptr6[m] >> 24) & 255) ^ (int)inputBuffer[i++]);
                        }
                    }
                    else
                    {
                        byte[] array6 = new byte[this.m_inputBlockSize];
                        Buffer.InternalBlockCopy(inputBuffer, num3, array6, 0, num2);
                        Buffer.InternalBlockCopy(array, 0, array6, num2, num);
                        i = 0;
                        int num11 = 0;
                        while (num11 < this.m_Nb && i < this.m_inputBlockSize)
{
                            outputBuffer[num5++] = (byte)((ptr6[num11] & 255) ^ (int)array6[i++]);
                            if (i >= this.m_inputBlockSize)
{
                                break;
                            }
                            outputBuffer[num5++] = (byte)(((ptr6[num11] >> 8) & 255) ^ (int)array6[i++]);
                            if (i >= this.m_inputBlockSize)
{
                                break;
                            }
                            outputBuffer[num5++] = (byte)(((ptr6[num11] >> 16) & 255) ^ (int)array6[i++]);
                            if (i >= this.m_inputBlockSize)
{
                                break;
                            }
                            outputBuffer[num5++] = (byte)(((ptr6[num11] >> 24) & 255) ^ (int)array6[i++]);
                            num11++;
                        }
                    }
                    for (i = 0; i < this.m_blockSizeBytes - this.m_inputBlockSize; i++)
                    {
                        this.m_shiftRegister[i] = this.m_shiftRegister[i + this.m_inputBlockSize];
                    }
                    Buffer.InternalBlockCopy(outputBuffer, j * this.m_inputBlockSize, this.m_shiftRegister, this.m_blockSizeBytes - this.m_inputBlockSize, this.m_inputBlockSize);
                }
                else
                {
                    for (int n = 0; n < this.m_Nb; n++)
                    {
                        outputBuffer[num5++] = (byte)(ptr6[n] & 255);
                        outputBuffer[num5++] = (byte)((ptr6[n] >> 8) & 255);
                        outputBuffer[num5++] = (byte)((ptr6[n] >> 16) & 255);
                        outputBuffer[num5++] = (byte)((ptr6[n] >> 24) & 255);
                    }
                    if (this.m_cipherMode == CipherMode.CBC)
                    {
                        int[] array7;
                        int* ptr7;
                        if ((array7 = this.m_lastBlockBuffer) == null || array7.Length == 0)
{
                            ptr7 = null;
                        }
                        else
{
                            ptr7 = &array7[0];
                        }
                        Buffer.Memcpy((byte*)ptr7, (byte*)ptr6, this.m_blockSizeBytes);
                        array7 = null;
                    }
                }
                num3 += this.m_inputBlockSize;
            }
            array5 = null;
            array4 = null;
            array3 = null;
            array2 = null;
            return inputCount + num;
        }
References System.array, System.Security.Cryptography.RijndaelManagedTransform.Enc(), System.Security.Cryptography.RNGCryptoServiceProvider.GetBytes(), System.Environment.GetResourceString(), int, System.Buffer.InternalBlockCopy(), System.Security.Cryptography.RijndaelManagedTransform.m_blockSizeBytes, System.Security.Cryptography.RijndaelManagedTransform.m_cipherMode, System.Security.Cryptography.RijndaelManagedTransform.m_encryptindex, System.Security.Cryptography.RijndaelManagedTransform.m_encryptKeyExpansion, System.Security.Cryptography.RijndaelManagedTransform.m_inputBlockSize, System.Security.Cryptography.RijndaelManagedTransform.m_lastBlockBuffer, System.Security.Cryptography.RijndaelManagedTransform.m_Nb, System.Security.Cryptography.RijndaelManagedTransform.m_shiftRegister, System.Buffer.Memcpy(), System.Security.Cryptography.RijndaelManagedTransform.s_T, System.Security.Cryptography.RijndaelManagedTransform.s_TF, and System.Security.Cryptography.Utils.StaticRandomNumberGenerator.
Referenced by System.Security.Cryptography.RijndaelManagedTransform.TransformBlock(), and System.Security.Cryptography.RijndaelManagedTransform.TransformFinalBlock().