Terraria Decompiled: System.Security.Cryptography.RijndaelManagedTransform.RijndaelManagedTransform
RijndaelManagedTransform() [1/2]
System.Security.Cryptography.RijndaelManagedTransform.RijndaelManagedTransform (byte[] rgbKey, CipherMode mode, byte[] rgbIV, int blockSize, int feedbackSize, PaddingMode PaddingValue, RijndaelManagedTransformMode transformMode) inline package
Definition at line 11 of file RijndaelManagedTransform.cs.
        {
            if (rgbKey == null)
            {
                throw new ArgumentNullException("rgbKey");
            }
            this.m_blockSizeBits = blockSize;
            this.m_blockSizeBytes = blockSize / 8;
            this.m_cipherMode = mode;
            this.m_paddingValue = PaddingValue;
            this.m_transformMode = transformMode;
            this.m_Nb = blockSize / 32;
            this.m_Nk = rgbKey.Length / 4;
            int num = ((this.m_Nb > 6) ? 3 : 2);
            int num2 = ((this.m_Nb > 6) ? 4 : 3);
            int[] array = new int[this.m_Nb];
            int[] array2 = new int[this.m_Nb];
            int[] array3 = new int[this.m_Nb];
            int[] array4 = new int[this.m_Nb];
            int[] array5 = new int[this.m_Nb];
            int[] array6 = new int[this.m_Nb];
            for (int i = 0; i < this.m_Nb; i++)
            {
                array[i] = (i + 1) % this.m_Nb;
                array2[i] = (i + num) % this.m_Nb;
                array3[i] = (i + num2) % this.m_Nb;
                array4[i] = (i - 1 + this.m_Nb) % this.m_Nb;
                array5[i] = (i - num + this.m_Nb) % this.m_Nb;
                array6[i] = (i - num2 + this.m_Nb) % this.m_Nb;
            }
            this.m_encryptindex = new int[this.m_Nb * 3];
            Array.Copy(array, 0, this.m_encryptindex, 0, this.m_Nb);
            Array.Copy(array2, 0, this.m_encryptindex, this.m_Nb, this.m_Nb);
            Array.Copy(array3, 0, this.m_encryptindex, this.m_Nb * 2, this.m_Nb);
            this.m_decryptindex = new int[this.m_Nb * 3];
            Array.Copy(array4, 0, this.m_decryptindex, 0, this.m_Nb);
            Array.Copy(array5, 0, this.m_decryptindex, this.m_Nb, this.m_Nb);
            Array.Copy(array6, 0, this.m_decryptindex, this.m_Nb * 2, this.m_Nb);
            CipherMode cipherMode = this.m_cipherMode;
            if (cipherMode - CipherMode.CBC > 1)
            {
                if (cipherMode != CipherMode.CFB)
                {
                    throw new CryptographicException(Environment.GetResourceString("Specified cipher mode is not valid for this algorithm."));
                }
                this.m_inputBlockSize = feedbackSize / 8;
                this.m_outputBlockSize = feedbackSize / 8;
            }
            else
            {
                this.m_inputBlockSize = this.m_blockSizeBytes;
                this.m_outputBlockSize = this.m_blockSizeBytes;
            }
            if (mode == CipherMode.CBC || mode == CipherMode.CFB)
            {
                if (rgbIV == null)
                {
                    throw new ArgumentNullException("rgbIV");
                }
                if (rgbIV.Length / 4 != this.m_Nb)
                {
                    throw new CryptographicException(Environment.GetResourceString("Specified initialization vector (IV) does not match the block size for this algorithm."));
                }
                this.m_IV = new int[this.m_Nb];
                int num3 = 0;
                for (int j = 0; j < this.m_Nb; j++)
                {
                    int num4 = (int)rgbIV[num3++];
                    int num5 = (int)rgbIV[num3++];
                    int num6 = (int)rgbIV[num3++];
                    int num7 = (int)rgbIV[num3++];
                    this.m_IV[j] = (num7 << 24) | (num6 << 16) | (num5 << 8) | num4;
                }
            }
            this.GenerateKeyExpansion(rgbKey);
            if (this.m_cipherMode == CipherMode.CBC)
            {
                this.m_lastBlockBuffer = new int[this.m_Nb];
                Buffer.InternalBlockCopy(this.m_IV, 0, this.m_lastBlockBuffer, 0, this.m_blockSizeBytes);
            }
            if (this.m_cipherMode == CipherMode.CFB)
            {
                this.m_shiftRegister = new byte[4 * this.m_Nb];
                Buffer.InternalBlockCopy(this.m_IV, 0, this.m_shiftRegister, 0, 4 * this.m_Nb);
            }
        }
References System.array, System.Array.Copy(), System.Security.Cryptography.RijndaelManagedTransform.GenerateKeyExpansion(), System.Environment.GetResourceString(), int, System.Buffer.InternalBlockCopy(), System.Security.Cryptography.RijndaelManagedTransform.m_blockSizeBytes, System.Security.Cryptography.RijndaelManagedTransform.m_cipherMode, System.Security.Cryptography.RijndaelManagedTransform.m_decryptindex, System.Security.Cryptography.RijndaelManagedTransform.m_encryptindex, System.Security.Cryptography.RijndaelManagedTransform.m_IV, System.Security.Cryptography.RijndaelManagedTransform.m_lastBlockBuffer, System.Security.Cryptography.RijndaelManagedTransform.m_Nb, System.Security.Cryptography.RijndaelManagedTransform.m_shiftRegister, and System.mode.