Terraria Decompiled: System.Lazy.CreateValue
CreateValue()
T System.Lazy< T >.CreateValue () inline private
Definition at line 159 of file Lazy.cs.
        {
            LazyHelper state = this._state;
            if (state != null)
            {
                switch (state.State)
                {
                case LazyState.NoneViaConstructor:
                    this.ViaConstructor();
                    goto IL_0084;
                case LazyState.NoneViaFactory:
                    this.ViaFactory(LazyThreadSafetyMode.None);
                    goto IL_0084;
                case LazyState.PublicationOnlyViaConstructor:
                    this.PublicationOnlyViaConstructor(state);
                    goto IL_0084;
                case LazyState.PublicationOnlyViaFactory:
                    this.PublicationOnlyViaFactory(state);
                    goto IL_0084;
                case LazyState.PublicationOnlyWait:
                    this.PublicationOnlyWaitForOtherThreadToPublish();
                    goto IL_0084;
                case LazyState.ExecutionAndPublicationViaConstructor:
                    this.ExecutionAndPublication(state, true);
                    goto IL_0084;
                case LazyState.ExecutionAndPublicationViaFactory:
                    this.ExecutionAndPublication(state, false);
                    goto IL_0084;
                }
                state.ThrowException();
            }
            IL_0084:
            return this.Value;
        }
References System.Lazy< T >._state, System.Threading.ExecutionAndPublication, System.LazyHelper.NoneViaConstructor, System.PublicationOnlyViaConstructor, System.PublicationOnlyViaFactory, System.Lazy< T >.PublicationOnlyWaitForOtherThreadToPublish(), System.state, System.Lazy< T >.Value, System.Lazy< T >.ViaConstructor(), and System.Lazy< T >.ViaFactory().