Terraria Decompiled: Newtonsoft.Json.JsonReader.ReadAsDouble
ReadAsDouble()
virtual ? double Newtonsoft.Json.JsonReader.ReadAsDouble () inline virtual
Reimplemented in Newtonsoft.Json.JsonTextReader, Newtonsoft.Json.JsonValidatingReader, and Newtonsoft.Json.Serialization.TraceJsonReader.
Definition at line 521 of file JsonReader.cs.
        {
            JsonToken contentToken = this.GetContentToken();
            if (contentToken != JsonToken.None)
            {
                switch (contentToken)
                {
                case JsonToken.Integer:
                case JsonToken.Float:
                    if (!(this.Value is double))
                    {
                        double num;
                        if (this.Value is BigInteger)
{
                            num = (double)((BigInteger)this.Value);
                        }
                        else
{
                            num = Convert.ToDouble(this.Value, CultureInfo.InvariantCulture);
                        }
                        this.SetToken(JsonToken.Float, num, false);
                    }
                    return new double?((double)this.Value);
                case JsonToken.String:
                    return this.ReadDoubleString((string)this.Value);
                case JsonToken.Null:
                case JsonToken.EndArray:
                    goto IL_0034;
                }
                throw JsonReaderException.Create(this, "Error reading double. Unexpected token: {0}.".FormatWith(CultureInfo.InvariantCulture, contentToken));
            }
            IL_0034:
            return default(double?);
        }
References Newtonsoft.Json.Utilities.BigInteger, Newtonsoft.Json.JsonReaderException.Create(), Newtonsoft.Json.JsonReader.GetContentToken(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.JsonReader.ReadDoubleString(), Newtonsoft.Json.JsonReader.SetToken(), System.Convert.ToDouble(), and Newtonsoft.Json.JsonReader.Value.
Referenced by Newtonsoft.Json.JsonValidatingReader.ReadAsDouble(), Newtonsoft.Json.Serialization.TraceJsonReader.ReadAsDouble(), and Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType().