Terraria Decompiled: Newtonsoft.Json.JsonReader.ReadAndAssert
ReadAndAssert()
void Newtonsoft.Json.JsonReader.ReadAndAssert () inline package
Definition at line 1016 of file JsonReader.cs.
        {
            if (!this.Read())
            {
                throw JsonSerializationException.Create(this, "Unexpected end when reading JSON.");
            }
        }
References Newtonsoft.Json.JsonSerializationException.Create(), and Newtonsoft.Json.JsonReader.Read().
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateISerializableItem(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(), Newtonsoft.Json.Converters.DataTableConverter.CreateRow(), Newtonsoft.Json.Converters.DataTableConverter.GetColumnDataType(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(), Newtonsoft.Json.Converters.EntityKeyMemberConverter.ReadAndAssertProperty(), Newtonsoft.Json.Converters.DataSetConverter.ReadJson(), Newtonsoft.Json.Converters.DataTableConverter.ReadJson(), Newtonsoft.Json.Converters.DiscriminatedUnionConverter.ReadJson(), Newtonsoft.Json.Converters.EntityKeyMemberConverter.ReadJson(), Newtonsoft.Json.Converters.KeyValuePairConverter.ReadJson(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataProperties(), and Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataPropertiesToken().