Terraria Decompiled: Newtonsoft.Json.JsonReader.ReadDateTimeOffsetString
ReadDateTimeOffsetString()
DateTimeOffset? Newtonsoft.Json.JsonReader.ReadDateTimeOffsetString (string s) inline package
Definition at line 765 of file JsonReader.cs.
        {
            if (string.IsNullOrEmpty(s))
            {
                this.SetToken(JsonToken.Null, null, false);
                return default(DateTimeOffset?);
            }
            DateTimeOffset dateTimeOffset;
            if (DateTimeUtils.TryParseDateTimeOffset(s, this._dateFormatString, this.Culture, out dateTimeOffset))
            {
                this.SetToken(JsonToken.Date, dateTimeOffset, false);
                return new DateTimeOffset?(dateTimeOffset);
            }
            if (DateTimeOffset.TryParse(s, this.Culture, 128, ref dateTimeOffset))
            {
                this.SetToken(JsonToken.Date, dateTimeOffset, false);
                return new DateTimeOffset?(dateTimeOffset);
            }
            this.SetToken(JsonToken.String, s, false);
            throw JsonReaderException.Create(this, "Could not convert string to DateTimeOffset: {0}.".FormatWith(CultureInfo.InvariantCulture, s));
        }
References Newtonsoft.Json.JsonReaderException.Create(), System.Globalization.CultureInfo.InvariantCulture, System.s, Newtonsoft.Json.JsonReader.SetToken(), System.DateTimeOffset.TryParse(), and Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTimeOffset().
Referenced by Newtonsoft.Json.JsonReader.ReadAsDateTimeOffset().