Terraria Decompiled: Newtonsoft.Json.JsonReader.ReadAsInt32
ReadAsInt32()
virtual ? int Newtonsoft.Json.JsonReader.ReadAsInt32 () inline virtual
Reimplemented in Newtonsoft.Json.JsonTextReader, Newtonsoft.Json.JsonValidatingReader, and Newtonsoft.Json.Serialization.TraceJsonReader.
Definition at line 317 of file JsonReader.cs.
        {
            JsonToken contentToken = this.GetContentToken();
            if (contentToken != JsonToken.None)
            {
                switch (contentToken)
                {
                case JsonToken.Integer:
                case JsonToken.Float:
                    if (!(this.Value is int))
                    {
                        this.SetToken(JsonToken.Integer, Convert.ToInt32(this.Value, CultureInfo.InvariantCulture), false);
                    }
                    return new int?((int)this.Value);
                case JsonToken.String:
                {
                    string text = (string)this.Value;
                    return this.ReadInt32String(text);
                }
                case JsonToken.Null:
                case JsonToken.EndArray:
                    goto IL_0034;
                }
                throw JsonReaderException.Create(this, "Error reading integer. Unexpected token: {0}.".FormatWith(CultureInfo.InvariantCulture, contentToken));
            }
            IL_0034:
            return default(int?);
        }
References Newtonsoft.Json.JsonReaderException.Create(), Newtonsoft.Json.JsonReader.GetContentToken(), int, System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.JsonReader.ReadInt32String(), Newtonsoft.Json.JsonReader.SetToken(), System.text, System.Convert.ToInt32(), and Newtonsoft.Json.JsonReader.Value.
Referenced by Newtonsoft.Json.JsonValidatingReader.ReadAsInt32(), Newtonsoft.Json.Serialization.TraceJsonReader.ReadAsInt32(), and Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType().