Terraria Decompiled: Newtonsoft.Json.JsonReader.ReadAsDateTime
ReadAsDateTime()
virtual ? DateTime Newtonsoft.Json.JsonReader.ReadAsDateTime () inline virtual
Reimplemented in Newtonsoft.Json.JsonTextReader, Newtonsoft.Json.JsonValidatingReader, and Newtonsoft.Json.Serialization.TraceJsonReader.
Definition at line 675 of file JsonReader.cs.
        {
            JsonToken contentToken = this.GetContentToken();
            if (contentToken <= JsonToken.String)
            {
                if (contentToken != JsonToken.None)
                {
                    if (contentToken != JsonToken.String)
                    {
                        goto IL_0084;
                    }
                    string text = (string)this.Value;
                    return this.ReadDateTimeString(text);
                }
            }
            else if (contentToken != JsonToken.Null && contentToken != JsonToken.EndArray)
            {
                if (contentToken != JsonToken.Date)
                {
                    goto IL_0084;
                }
                if (this.Value is DateTimeOffset)
                {
                    this.SetToken(JsonToken.Date, ((DateTimeOffset)this.Value).DateTime, false);
                }
                return new DateTime?((DateTime)this.Value);
            }
            return default(DateTime?);
            IL_0084:
            throw JsonReaderException.Create(this, "Error reading date. Unexpected token: {0}.".FormatWith(CultureInfo.InvariantCulture, this.TokenType));
        }
References Newtonsoft.Json.JsonReaderException.Create(), Newtonsoft.Json.DateTime, Newtonsoft.Json.JsonReader.GetContentToken(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.JsonReader.ReadDateTimeString(), Newtonsoft.Json.JsonReader.SetToken(), System.text, and Newtonsoft.Json.JsonReader.Value.
Referenced by Newtonsoft.Json.JsonValidatingReader.ReadAsDateTime(), Newtonsoft.Json.Serialization.TraceJsonReader.ReadAsDateTime(), and Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType().