Terraria Decompiled: System.Reflection.Emit.AssemblyBuilder.DefineUnmanagedResource
DefineUnmanagedResource() [2/2]
void System.Reflection.Emit.AssemblyBuilder.DefineUnmanagedResource (string resourceFileName) inline
Definition at line 415 of file AssemblyBuilder.cs.
        {
            if (resourceFileName == null)
            {
                throw new ArgumentNullException("resourceFileName");
            }
            if (resourceFileName.Length == 0)
            {
                throw new ArgumentException("resourceFileName");
            }
            if (!File.Exists(resourceFileName) || Directory.Exists(resourceFileName))
            {
                throw new FileNotFoundException("File '" + resourceFileName + "' does not exist or is a directory.");
            }
            if (this.native_resource != NativeResourceType.None)
            {
                throw new ArgumentException("Native resource has already been defined.");
            }
            this.native_resource = NativeResourceType.Unmanaged;
            using (FileStream fileStream = new FileStream(resourceFileName, FileMode.Open, FileAccess.Read))
            {
                foreach (object obj in new Win32ResFileReader(fileStream).ReadResources())
                {
                    Win32EncodedResource win32EncodedResource = (Win32EncodedResource)obj;
                    if (win32EncodedResource.Name.IsName || win32EncodedResource.Type.IsName)
                    {
                        throw new InvalidOperationException("resource files with named resources or non-default resource types are not supported.");
                    }
                    this.AddUnmanagedResource(win32EncodedResource);
                }
            }
        }
References System.Reflection.Emit.AssemblyBuilder.AddUnmanagedResource(), System.IO.Directory.Exists(), System.IO.File.Exists(), System.Resources.NameOrId.IsName, System.Resources.Win32Resource.Name, System.Reflection.Emit.AssemblyBuilder.native_resource, System.obj, System.Resources.Win32ResFileReader.ReadResources(), and System.Resources.Win32Resource.Type.