Terraria Decompiled: System.Reflection.Emit.AssemblyBuilder.AddUnmanagedResource
AddUnmanagedResource()
void System.Reflection.Emit.AssemblyBuilder.AddUnmanagedResource (Win32Resource res) inline private
Definition at line 381 of file AssemblyBuilder.cs.
        {
            MemoryStream memoryStream = new MemoryStream();
            res.WriteTo(memoryStream);
            if (this.win32_resources != null)
            {
                MonoWin32Resource[] array = new MonoWin32Resource[this.win32_resources.Length + 1];
                Array.Copy(this.win32_resources, array, this.win32_resources.Length);
                this.win32_resources = array;
            }
            else
            {
                this.win32_resources = new MonoWin32Resource[1];
            }
            this.win32_resources[this.win32_resources.Length - 1] = new MonoWin32Resource(res.Type.Id, res.Name.Id, res.Language, memoryStream.ToArray());
        }
References System.array, System.Array.Copy(), System.Resources.NameOrId.Id, System.Resources.Win32Resource.Language, System.Resources.Win32Resource.Name, System.IO.MemoryStream.ToArray(), System.Resources.Win32Resource.Type, System.Reflection.Emit.AssemblyBuilder.win32_resources, and System.Resources.Win32Resource.WriteTo().
Referenced by System.Reflection.Emit.AssemblyBuilder.DefineUnmanagedResource(), and System.Reflection.Emit.AssemblyBuilder.DefineVersionInfoResourceImpl().