Terraria Decompiled: Newtonsoft.Json.JsonReader.ReadDateTimeString
ReadDateTimeString()
DateTime? Newtonsoft.Json.JsonReader.ReadDateTimeString (string s) inline package
Definition at line 708 of file JsonReader.cs.
        {
            if (string.IsNullOrEmpty(s))
            {
                this.SetToken(JsonToken.Null, null, false);
                return default(DateTime?);
            }
            DateTime dateTime;
            if (DateTimeUtils.TryParseDateTime(s, this.DateTimeZoneHandling, this._dateFormatString, this.Culture, out dateTime))
            {
                dateTime = DateTimeUtils.EnsureDateTime(dateTime, this.DateTimeZoneHandling);
                this.SetToken(JsonToken.Date, dateTime, false);
                return new DateTime?(dateTime);
            }
            if (DateTime.TryParse(s, this.Culture, 128, ref dateTime))
            {
                dateTime = DateTimeUtils.EnsureDateTime(dateTime, this.DateTimeZoneHandling);
                this.SetToken(JsonToken.Date, dateTime, false);
                return new DateTime?(dateTime);
            }
            throw JsonReaderException.Create(this, "Could not convert string to DateTime: {0}.".FormatWith(CultureInfo.InvariantCulture, s));
        }
References Newtonsoft.Json.JsonReaderException.Create(), Newtonsoft.Json.Utilities.DateTimeUtils.EnsureDateTime(), System.Globalization.CultureInfo.InvariantCulture, System.s, Newtonsoft.Json.JsonReader.SetToken(), System.DateTime.TryParse(), and Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTime().
Referenced by Newtonsoft.Json.JsonReader.ReadAsDateTime().