Terraria Decompiled: Newtonsoft.Json.JsonReader.ReadAsDecimal
ReadAsDecimal()
virtual ? decimal Newtonsoft.Json.JsonReader.ReadAsDecimal () inline virtual
Reimplemented in Newtonsoft.Json.JsonTextReader, Newtonsoft.Json.JsonValidatingReader, and Newtonsoft.Json.Serialization.TraceJsonReader.
Definition at line 630 of file JsonReader.cs.
        {
            JsonToken contentToken = this.GetContentToken();
            if (contentToken != JsonToken.None)
            {
                switch (contentToken)
                {
                case JsonToken.Integer:
                case JsonToken.Float:
                    if (!(this.Value is decimal))
                    {
                        this.SetToken(JsonToken.Float, Convert.ToDecimal(this.Value, CultureInfo.InvariantCulture), false);
                    }
                    return new decimal?((decimal)this.Value);
                case JsonToken.String:
                    return this.ReadDecimalString((string)this.Value);
                case JsonToken.Null:
                case JsonToken.EndArray:
                    goto IL_0034;
                }
                throw JsonReaderException.Create(this, "Error reading decimal. Unexpected token: {0}.".FormatWith(CultureInfo.InvariantCulture, contentToken));
            }
            IL_0034:
            return default(decimal?);
        }
References Newtonsoft.Json.JsonReaderException.Create(), Newtonsoft.Json.JsonReader.GetContentToken(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.JsonReader.ReadDecimalString(), Newtonsoft.Json.JsonReader.SetToken(), System.Convert.ToDecimal(), and Newtonsoft.Json.JsonReader.Value.
Referenced by Newtonsoft.Json.JsonValidatingReader.ReadAsDecimal(), Newtonsoft.Json.Serialization.TraceJsonReader.ReadAsDecimal(), and Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType().