Terraria Decompiled: Newtonsoft.Json.JsonReader.ReadAsDateTimeOffset
ReadAsDateTimeOffset()
virtual ? DateTimeOffset Newtonsoft.Json.JsonReader.ReadAsDateTimeOffset () inline virtual
Reimplemented in Newtonsoft.Json.JsonTextReader, Newtonsoft.Json.JsonValidatingReader, and Newtonsoft.Json.Serialization.TraceJsonReader.
Definition at line 732 of file JsonReader.cs.
        {
            JsonToken contentToken = this.GetContentToken();
            if (contentToken <= JsonToken.String)
            {
                if (contentToken != JsonToken.None)
                {
                    if (contentToken != JsonToken.String)
                    {
                        goto IL_0081;
                    }
                    string text = (string)this.Value;
                    return this.ReadDateTimeOffsetString(text);
                }
            }
            else if (contentToken != JsonToken.Null && contentToken != JsonToken.EndArray)
            {
                if (contentToken != JsonToken.Date)
                {
                    goto IL_0081;
                }
                if (this.Value is DateTime)
                {
                    this.SetToken(JsonToken.Date, new DateTimeOffset((DateTime)this.Value), false);
                }
                return new DateTimeOffset?((DateTimeOffset)this.Value);
            }
            return default(DateTimeOffset?);
            IL_0081:
            throw JsonReaderException.Create(this, "Error reading date. Unexpected token: {0}.".FormatWith(CultureInfo.InvariantCulture, contentToken));
        }
References Newtonsoft.Json.JsonReaderException.Create(), Newtonsoft.Json.DateTimeOffset, Newtonsoft.Json.JsonReader.GetContentToken(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.JsonReader.ReadDateTimeOffsetString(), Newtonsoft.Json.JsonReader.SetToken(), System.text, and Newtonsoft.Json.JsonReader.Value.
Referenced by Newtonsoft.Json.JsonValidatingReader.ReadAsDateTimeOffset(), Newtonsoft.Json.Serialization.TraceJsonReader.ReadAsDateTimeOffset(), and Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType().