Terraria Decompiled: Newtonsoft.Json.JsonReader.ReadArrayElementIntoByteArrayReportDone
ReadArrayElementIntoByteArrayReportDone()
bool Newtonsoft.Json.JsonReader.ReadArrayElementIntoByteArrayReportDone (List< byte > buffer) inline private
Definition at line 491 of file JsonReader.cs.
        {
            JsonToken tokenType = this.TokenType;
            if (tokenType <= JsonToken.Comment)
            {
                if (tokenType == JsonToken.None)
                {
                    throw JsonReaderException.Create(this, "Unexpected end when reading bytes.");
                }
                if (tokenType == JsonToken.Comment)
                {
                    return false;
                }
            }
            else
            {
                if (tokenType == JsonToken.Integer)
                {
                    buffer.Add(Convert.ToByte(this.Value, CultureInfo.InvariantCulture));
                    return false;
                }
                if (tokenType == JsonToken.EndArray)
                {
                    return true;
                }
            }
            throw JsonReaderException.Create(this, "Unexpected token when reading bytes: {0}.".FormatWith(CultureInfo.InvariantCulture, this.TokenType));
        }
References System.Collections.Generic.List< T >.Add(), Newtonsoft.Json.JsonReaderException.Create(), System.Globalization.CultureInfo.InvariantCulture, System.Convert.ToByte(), and Newtonsoft.Json.JsonReader.TokenType.
Referenced by Newtonsoft.Json.JsonReader.ReadArrayIntoByteArray().