Terraria Decompiled: System.Reflection.Emit.AssemblyBuilder.AddResourceFile
AddResourceFile() [3/3]
void System.Reflection.Emit.AssemblyBuilder.AddResourceFile (string name, string fileName, ResourceAttributes attribute, bool fileNeedsToExists) inline private
Definition at line 193 of file AssemblyBuilder.cs.
        {
            this.check_name_and_filename(name, fileName, fileNeedsToExists);
            if (this.dir != null)
            {
                fileName = Path.Combine(this.dir, fileName);
            }
            if (this.resources != null)
            {
                MonoResource[] array = new MonoResource[this.resources.Length + 1];
                Array.Copy(this.resources, array, this.resources.Length);
                this.resources = array;
            }
            else
            {
                this.resources = new MonoResource[1];
            }
            int num = this.resources.Length - 1;
            this.resources[num].name = name;
            this.resources[num].filename = fileName;
            this.resources[num].attrs = attribute;
        }
References System.array, System.Reflection.Emit.MonoResource.attrs, System.Reflection.Emit.AssemblyBuilder.check_name_and_filename(), System.IO.Path.Combine(), System.Array.Copy(), System.Reflection.Emit.AssemblyBuilder.dir, System.Reflection.Emit.MonoResource.filename, System.Reflection.Emit.AssemblyBuilder.name, System.Reflection.Emit.MonoResource.name, and System.Reflection.Emit.AssemblyBuilder.resources.