Terraria Decompiled: System.Reflection.Emit.AssemblyBuilder.check_name_and_filename
check_name_and_filename()
void System.Reflection.Emit.AssemblyBuilder.check_name_and_filename (string name, string fileName, bool fileNeedsToExists) inline private
Definition at line 909 of file AssemblyBuilder.cs.
        {
            if (name == null)
            {
                throw new ArgumentNullException("name");
            }
            if (fileName == null)
            {
                throw new ArgumentNullException("fileName");
            }
            if (name.Length == 0)
            {
                throw new ArgumentException("Empty name is not legal.", "name");
            }
            if (fileName.Length == 0)
            {
                throw new ArgumentException("Empty file name is not legal.", "fileName");
            }
            if (Path.GetFileName(fileName) != fileName)
            {
                throw new ArgumentException("fileName '" + fileName + "' must not include a path.", "fileName");
            }
            string text = fileName;
            if (this.dir != null)
            {
                text = Path.Combine(this.dir, fileName);
            }
            if (fileNeedsToExists && !File.Exists(text))
            {
                throw new FileNotFoundException("Could not find file '" + fileName + "'");
            }
            if (this.resources != null)
            {
                for (int i = 0; i < this.resources.Length; i++)
                {
                    if (this.resources[i].filename == text)
                    {
                        throw new ArgumentException("Duplicate file name '" + fileName + "'");
                    }
                    if (this.resources[i].name == name)
                    {
                        throw new ArgumentException("Duplicate name '" + name + "'");
                    }
                }
            }
            if (this.modules != null)
            {
                for (int j = 0; j < this.modules.Length; j++)
                {
                    if (!this.modules[j].IsTransient() && this.modules[j].FileName == fileName)
                    {
                        throw new ArgumentException("Duplicate file name '" + fileName + "'");
                    }
                    if (this.modules[j].Name == name)
                    {
                        throw new ArgumentException("Duplicate name '" + name + "'");
                    }
                }
            }
        }
References System.IO.Path.Combine(), System.Reflection.Emit.AssemblyBuilder.dir, System.IO.File.Exists(), System.IO.Path.GetFileName(), System.Reflection.Emit.AssemblyBuilder.modules, System.Reflection.Emit.AssemblyBuilder.name, System.Reflection.Name, System.Reflection.Emit.AssemblyBuilder.resources, and System.text.
Referenced by System.Reflection.Emit.AssemblyBuilder.AddResourceFile(), and System.Reflection.Emit.AssemblyBuilder.DefineDynamicModule().