Terraria Decompiled: System.Reflection.Emit.AssemblyBuilder.AssemblyBuilder
AssemblyBuilder()
System.Reflection.Emit.AssemblyBuilder.AssemblyBuilder (AssemblyName n, string directory, AssemblyBuilderAccess access, bool corlib_internal) inline package
Definition at line 58 of file AssemblyBuilder.cs.
        {
            if ((access & (AssemblyBuilderAccess)2048) != (AssemblyBuilderAccess)0)
            {
                throw new NotImplementedException("COMPILER_ACCESS is no longer supperted, use a newer mcs.");
            }
            if (!Enum.IsDefined(typeof(AssemblyBuilderAccess), access))
            {
                throw new ArgumentException(string.Format(CultureInfo.InvariantCulture, "Argument value {0} is not valid.", (int)access), "access");
            }
            this.name = n.Name;
            this.access = (uint)access;
            this.flags = (uint)n.Flags;
            if (this.IsSave && (directory == null || directory.Length == 0))
            {
                this.dir = Directory.GetCurrentDirectory();
            }
            else
            {
                this.dir = directory;
            }
            if (n.CultureInfo != null)
            {
                this.culture = n.CultureInfo.Name;
                this.versioninfo_culture = n.CultureInfo.Name;
            }
            Version version = n.Version;
            if (version != null)
            {
                this.version = version.ToString();
            }
            if (n.KeyPair != null)
            {
                this.sn = n.KeyPair.StrongName();
            }
            else
            {
                byte[] publicKey = n.GetPublicKey();
                if (publicKey != null && publicKey.Length != 0)
                {
                    this.sn = new Mono.Security.StrongName(publicKey);
                }
            }
            if (this.sn != null)
            {
                this.flags |= 1U;
            }
            this.corlib_internal = corlib_internal;
            if (this.sn != null)
            {
                this.pktoken = new byte[this.sn.PublicKeyToken.Length * 2];
                int num = 0;
                foreach (byte b in this.sn.PublicKeyToken)
                {
                    string text = b.ToString("x2");
                    this.pktoken[num++] = (byte)text[0];
                    this.pktoken[num++] = (byte)text[1];
                }
            }
            AssemblyBuilder.basic_init(this);
        }
References System.Reflection.Emit.AssemblyBuilder.access, System.Reflection.Emit.AssemblyBuilder.basic_init(), System.Reflection.Emit.AssemblyBuilder.corlib_internal, System.Reflection.AssemblyName.CultureInfo, System.Reflection.AssemblyName.Flags, System.Format, System.IO.Directory.GetCurrentDirectory(), System.Reflection.AssemblyName.GetPublicKey(), System.Globalization.CultureInfo.InvariantCulture, System.Enum.IsDefined(), System.Reflection.Emit.AssemblyBuilder.IsSave, System.Reflection.AssemblyName.KeyPair, System.Globalization.CultureInfo.Name, System.Reflection.AssemblyName.Name, System.Reflection.Emit.AssemblyBuilder.pktoken, System.Reflection.Emit.AssemblyBuilder.sn, System.Reflection.StrongNameKeyPair.StrongName(), System.text, System.Reflection.U, System.Reflection.AssemblyName.Version, and System.Reflection.Emit.AssemblyBuilder.version.
Referenced by System.Reflection.Emit.AssemblyBuilder.DefineDynamicAssembly().