Terraria Decompiled: Newtonsoft.Json.JsonReader.ReadAsBytes
ReadAsBytes()
virtual byte[] Newtonsoft.Json.JsonReader.ReadAsBytes () inline virtual
Reimplemented in Newtonsoft.Json.JsonTextReader, Newtonsoft.Json.JsonValidatingReader, and Newtonsoft.Json.Serialization.TraceJsonReader.
Definition at line 405 of file JsonReader.cs.
        {
            JsonToken contentToken = this.GetContentToken();
            if (contentToken <= JsonToken.String)
            {
                switch (contentToken)
                {
                case JsonToken.None:
                    break;
                case JsonToken.StartObject:
                {
                    this.ReadIntoWrappedTypeObject();
                    byte[] array = this.ReadAsBytes();
                    this.ReaderReadAndAssert();
                    if (this.TokenType != JsonToken.EndObject)
                    {
                        throw JsonReaderException.Create(this, "Error reading bytes. Unexpected token: {0}.".FormatWith(CultureInfo.InvariantCulture, this.TokenType));
                    }
                    this.SetToken(JsonToken.Bytes, array, false);
                    return array;
                }
                case JsonToken.StartArray:
                    return this.ReadArrayIntoByteArray();
                default:
                {
                    if (contentToken != JsonToken.String)
                    {
                        goto IL_0122;
                    }
                    string text = (string)this.Value;
                    byte[] array2;
                    Guid guid;
                    if (text.Length == 0)
                    {
                        array2 = CollectionUtils.ArrayEmpty<byte>();
                    }
                    else if (ConvertUtils.TryConvertGuid(text, out guid))
                    {
                        array2 = guid.ToByteArray();
                    }
                    else
                    {
                        array2 = Convert.FromBase64String(text);
                    }
                    this.SetToken(JsonToken.Bytes, array2, false);
                    return array2;
                }
                }
            }
            else if (contentToken != JsonToken.Null && contentToken != JsonToken.EndArray)
            {
                if (contentToken != JsonToken.Bytes)
                {
                    goto IL_0122;
                }
                if (this.ValueType == typeof(Guid))
                {
                    byte[] array3 = ((Guid)this.Value).ToByteArray();
                    this.SetToken(JsonToken.Bytes, array3, false);
                    return array3;
                }
                return (byte[])this.Value;
            }
            return null;
            IL_0122:
            throw JsonReaderException.Create(this, "Error reading bytes. Unexpected token: {0}.".FormatWith(CultureInfo.InvariantCulture, contentToken));
        }
References System.array, Newtonsoft.Json.JsonReaderException.Create(), System.Convert.FromBase64String(), Newtonsoft.Json.JsonReader.GetContentToken(), Newtonsoft.Json.Utilities.Guid, System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.JsonReader.ReadArrayIntoByteArray(), Newtonsoft.Json.JsonReader.ReadAsBytes(), Newtonsoft.Json.JsonReader.ReaderReadAndAssert(), Newtonsoft.Json.JsonReader.ReadIntoWrappedTypeObject(), Newtonsoft.Json.JsonReader.SetToken(), System.text, System.Guid.ToByteArray(), Newtonsoft.Json.Utilities.ConvertUtils.TryConvertGuid(), and Newtonsoft.Json.JsonReader.Value.
Referenced by Newtonsoft.Json.JsonReader.ReadAsBytes(), Newtonsoft.Json.JsonValidatingReader.ReadAsBytes(), Newtonsoft.Json.Serialization.TraceJsonReader.ReadAsBytes(), and Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType().