Terraria Decompiled: System.Reflection.Emit.AssemblyBuilder.DefineVersionInfoResourceImpl
DefineVersionInfoResourceImpl()
void System.Reflection.Emit.AssemblyBuilder.DefineVersionInfoResourceImpl (string fileName) inline private
Definition at line 476 of file AssemblyBuilder.cs.
        {
            if (this.versioninfo_culture != null)
            {
                this.version_res.FileLanguage = new CultureInfo(this.versioninfo_culture).LCID;
            }
            this.version_res.Version = ((this.version == null) ? "0.0.0.0" : this.version);
            if (this.cattrs != null)
            {
                NativeResourceType nativeResourceType = this.native_resource;
                if (nativeResourceType != NativeResourceType.Assembly)
                {
                    if (nativeResourceType == NativeResourceType.Explicit)
                    {
                        foreach (CustomAttributeBuilder customAttributeBuilder in this.cattrs)
{
                            string fullName = customAttributeBuilder.Ctor.ReflectedType.FullName;
                            if (fullName == "System.Reflection.AssemblyCultureAttribute")
{
                                this.version_res.FileLanguage = new CultureInfo(customAttributeBuilder.string_arg()).LCID;
                            }
                            else if (fullName == "System.Reflection.AssemblyDescriptionAttribute")
{
                                this.version_res.Comments = customAttributeBuilder.string_arg();
                            }
                        }
                    }
                }
                else
                {
                    foreach (CustomAttributeBuilder customAttributeBuilder2 in this.cattrs)
                    {
                        string fullName2 = customAttributeBuilder2.Ctor.ReflectedType.FullName;
                        if (fullName2 == "System.Reflection.AssemblyProductAttribute")
{
                            this.version_res.ProductName = customAttributeBuilder2.string_arg();
                        }
                        else if (fullName2 == "System.Reflection.AssemblyCompanyAttribute")
{
                            this.version_res.CompanyName = customAttributeBuilder2.string_arg();
                        }
                        else if (fullName2 == "System.Reflection.AssemblyCopyrightAttribute")
{
                            this.version_res.LegalCopyright = customAttributeBuilder2.string_arg();
                        }
                        else if (fullName2 == "System.Reflection.AssemblyTrademarkAttribute")
{
                            this.version_res.LegalTrademarks = customAttributeBuilder2.string_arg();
                        }
                        else if (fullName2 == "System.Reflection.AssemblyCultureAttribute")
{
                            this.version_res.FileLanguage = new CultureInfo(customAttributeBuilder2.string_arg()).LCID;
                        }
                        else if (fullName2 == "System.Reflection.AssemblyFileVersionAttribute")
{
                            this.version_res.FileVersion = customAttributeBuilder2.string_arg();
                        }
                        else if (fullName2 == "System.Reflection.AssemblyInformationalVersionAttribute")
{
                            this.version_res.ProductVersion = customAttributeBuilder2.string_arg();
                        }
                        else if (fullName2 == "System.Reflection.AssemblyTitleAttribute")
{
                            this.version_res.FileDescription = customAttributeBuilder2.string_arg();
                        }
                        else if (fullName2 == "System.Reflection.AssemblyDescriptionAttribute")
{
                            this.version_res.Comments = customAttributeBuilder2.string_arg();
                        }
                    }
                }
            }
            this.version_res.OriginalFilename = fileName;
            this.version_res.InternalName = Path.GetFileNameWithoutExtension(fileName);
            this.AddUnmanagedResource(this.version_res);
        }
References System.Reflection.Emit.AssemblyBuilder.AddUnmanagedResource(), System.Reflection.Emit.AssemblyBuilder.cattrs, System.Reflection.Emit.CustomAttributeBuilder.Ctor, System.Type.FullName, System.IO.Path.GetFileNameWithoutExtension(), System.Globalization.CultureInfo.LCID, System.Reflection.Emit.AssemblyBuilder.native_resource, System.Reflection.MemberInfo.ReflectedType, System.Reflection.Emit.CustomAttributeBuilder.string_arg(), System.Reflection.Emit.AssemblyBuilder.version, System.Reflection.Emit.AssemblyBuilder.version_res, and System.Reflection.Emit.AssemblyBuilder.versioninfo_culture.
Referenced by System.Reflection.Emit.AssemblyBuilder.Save().