Terraria Decompiled: Newtonsoft.Json.JsonReader.SetToken
SetToken() [3/3]
void Newtonsoft.Json.JsonReader.SetToken (JsonToken newToken, object value, bool updateIndex) inline protected
Definition at line 850 of file JsonReader.cs.
        {
            this._tokenType = newToken;
            this._value = value;
            switch (newToken)
            {
            case JsonToken.StartObject:
                this._currentState = JsonReader.State.ObjectStart;
                this.Push(JsonContainerType.Object);
                return;
            case JsonToken.StartArray:
                this._currentState = JsonReader.State.ArrayStart;
                this.Push(JsonContainerType.Array);
                return;
            case JsonToken.StartConstructor:
                this._currentState = JsonReader.State.ConstructorStart;
                this.Push(JsonContainerType.Constructor);
                return;
            case JsonToken.PropertyName:
                this._currentState = JsonReader.State.Property;
                this._currentPosition.PropertyName = (string)value;
                return;
            case JsonToken.Comment:
                break;
            case JsonToken.Raw:
            case JsonToken.Integer:
            case JsonToken.Float:
            case JsonToken.String:
            case JsonToken.Boolean:
            case JsonToken.Null:
            case JsonToken.Undefined:
            case JsonToken.Date:
            case JsonToken.Bytes:
                this.SetPostValueState(updateIndex);
                break;
            case JsonToken.EndObject:
                this.ValidateEnd(JsonToken.EndObject);
                return;
            case JsonToken.EndArray:
                this.ValidateEnd(JsonToken.EndArray);
                return;
            case JsonToken.EndConstructor:
                this.ValidateEnd(JsonToken.EndConstructor);
                return;
            default:
                return;
            }
        }
References Newtonsoft.Json.JsonReader.Push(), Newtonsoft.Json.JsonReader.SetPostValueState(), Newtonsoft.Json.JsonReader.ValidateEnd(), and System.value.