Terraria Decompiled: Newtonsoft.Json.JsonReader.Push
Push()
void Newtonsoft.Json.JsonReader.Push (JsonContainerType value) inline private
Definition at line 264 of file JsonReader.cs.
        {
            this.UpdateScopeWithFinishedValue();
            if (this._currentPosition.Type == JsonContainerType.None)
            {
                this._currentPosition = new JsonPosition(value);
                return;
            }
            if (this._stack == null)
            {
                this._stack = new List<JsonPosition>();
            }
            this._stack.Add(this._currentPosition);
            this._currentPosition = new JsonPosition(value);
            if (this._maxDepth != null && this.Depth + 1 > this._maxDepth && !this._hasExceededMaxDepth)
            {
                this._hasExceededMaxDepth = true;
                throw JsonReaderException.Create(this, "The reader's MaxDepth of {0} has been exceeded.".FormatWith(CultureInfo.InvariantCulture, this._maxDepth));
            }
        }
References Newtonsoft.Json.JsonReader._currentPosition, Newtonsoft.Json.JsonReader._hasExceededMaxDepth, Newtonsoft.Json.JsonReader._maxDepth, Newtonsoft.Json.JsonReader._stack, Newtonsoft.Json.JsonReaderException.Create(), Newtonsoft.Json.JsonReader.Depth, System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.JsonPosition.Type, Newtonsoft.Json.JsonReader.UpdateScopeWithFinishedValue(), and System.value.
Referenced by Newtonsoft.Json.JsonReader.SetToken().