Terraria Decompiled: Newtonsoft.Json.JsonReader.ReadIntoWrappedTypeObject
ReadIntoWrappedTypeObject()
void Newtonsoft.Json.JsonReader.ReadIntoWrappedTypeObject () inline package
Definition at line 803 of file JsonReader.cs.
        {
            this.ReaderReadAndAssert();
            if (this.Value != null && this.Value.ToString() == "$type")
            {
                this.ReaderReadAndAssert();
                if (this.Value != null && this.Value.ToString().StartsWith("System.Byte[]", 4))
                {
                    this.ReaderReadAndAssert();
                    if (this.Value.ToString() == "$value")
                    {
                        return;
                    }
                }
            }
            throw JsonReaderException.Create(this, "Error reading bytes. Unexpected token: {0}.".FormatWith(CultureInfo.InvariantCulture, JsonToken.StartObject));
        }
References Newtonsoft.Json.JsonReaderException.Create(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.JsonReader.ReaderReadAndAssert(), and Newtonsoft.Json.JsonReader.Value.
Referenced by Newtonsoft.Json.JsonReader.ReadAsBytes().