Terraria Decompiled: Newtonsoft.Json.JsonReader.ReadAsBoolean
ReadAsBoolean()
virtual ? bool Newtonsoft.Json.JsonReader.ReadAsBoolean () inline virtual
Reimplemented in Newtonsoft.Json.JsonTextReader, Newtonsoft.Json.JsonValidatingReader, and Newtonsoft.Json.Serialization.TraceJsonReader.
Definition at line 575 of file JsonReader.cs.
        {
            JsonToken contentToken = this.GetContentToken();
            if (contentToken != JsonToken.None)
            {
                switch (contentToken)
                {
                case JsonToken.Integer:
                case JsonToken.Float:
                {
                    bool flag;
                    if (this.Value is BigInteger)
                    {
                        flag = (BigInteger)this.Value != 0L;
                    }
                    else
                    {
                        flag = Convert.ToBoolean(this.Value, CultureInfo.InvariantCulture);
                    }
                    this.SetToken(JsonToken.Boolean, flag, false);
                    return new bool?(flag);
                }
                case JsonToken.String:
                    return this.ReadBooleanString((string)this.Value);
                case JsonToken.Boolean:
                    return new bool?((bool)this.Value);
                case JsonToken.Null:
                case JsonToken.EndArray:
                    goto IL_0034;
                }
                throw JsonReaderException.Create(this, "Error reading boolean. Unexpected token: {0}.".FormatWith(CultureInfo.InvariantCulture, contentToken));
            }
            IL_0034:
            return default(bool?);
        }
References Newtonsoft.Json.Utilities.BigInteger, Newtonsoft.Json.JsonReaderException.Create(), Newtonsoft.Json.JsonReader.GetContentToken(), System.Globalization.CultureInfo.InvariantCulture, System.L, Newtonsoft.Json.JsonReader.ReadBooleanString(), Newtonsoft.Json.JsonReader.SetToken(), System.Convert.ToBoolean(), and Newtonsoft.Json.JsonReader.Value.
Referenced by Newtonsoft.Json.JsonValidatingReader.ReadAsBoolean(), Newtonsoft.Json.Serialization.TraceJsonReader.ReadAsBoolean(), and Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType().