Terraria Decompiled: System.Reflection.Emit.AssemblyBuilder.AddPermissionRequests
AddPermissionRequests()
void System.Reflection.Emit.AssemblyBuilder.AddPermissionRequests (PermissionSet required, PermissionSet optional, PermissionSet refused) inline package
Definition at line 217 of file AssemblyBuilder.cs.
        {
            if (this.created)
            {
                throw new InvalidOperationException("Assembly was already saved.");
            }
            this._minimum = required;
            this._optional = optional;
            this._refuse = refused;
            if (required != null)
            {
                this.permissions_minimum = new RefEmitPermissionSet[1];
                this.permissions_minimum[0] = new RefEmitPermissionSet(SecurityAction.RequestMinimum, required.ToXml().ToString());
            }
            if (optional != null)
            {
                this.permissions_optional = new RefEmitPermissionSet[1];
                this.permissions_optional[0] = new RefEmitPermissionSet(SecurityAction.RequestOptional, optional.ToXml().ToString());
            }
            if (refused != null)
            {
                this.permissions_refused = new RefEmitPermissionSet[1];
                this.permissions_refused[0] = new RefEmitPermissionSet(SecurityAction.RequestRefuse, refused.ToXml().ToString());
            }
        }
References System.Reflection.Emit.AssemblyBuilder.created, System.Reflection.Emit.AssemblyBuilder.permissions_minimum, System.Reflection.Emit.AssemblyBuilder.permissions_optional, System.Reflection.Emit.AssemblyBuilder.permissions_refused, System.Security.SecurityElement.ToString(), and System.Security.PermissionSet.ToXml().
Referenced by System.AppDomain.DefineDynamicAssembly().