Terraria Decompiled: Newtonsoft.Json.JsonReader.Skip
Skip()
void Newtonsoft.Json.JsonReader.Skip () inline
Definition at line 822 of file JsonReader.cs.
        {
            if (this.TokenType == JsonToken.PropertyName)
            {
                this.Read();
            }
            if (JsonTokenUtils.IsStartToken(this.TokenType))
            {
                int depth = this.Depth;
                while (this.Read() && depth < this.Depth)
                {
                }
            }
        }
References Newtonsoft.Json.JsonReader.Depth, Newtonsoft.Json.Utilities.JsonTokenUtils.IsStartToken(), and Newtonsoft.Json.JsonReader.Read().
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CheckPropertyName(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateDynamic(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.HandleError(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(), Newtonsoft.Json.Converters.KeyValuePairConverter.ReadJson(), Terraria.WorldBuilding.WorldGenSnapshot.SnapshotGenVars.ReadJson(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataPropertiesToken(), Newtonsoft.Json.Converters.RegexConverter.ReadRegexObject(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetExtensionData(), and Newtonsoft.Json.Linq.JTokenWriter.WriteToken().