Terraria Decompiled: Newtonsoft.Json.JsonReader.Close
Close()
virtual void Newtonsoft.Json.JsonReader.Close () inline virtual
Reimplemented in Newtonsoft.Json.Bson.BsonReader, Newtonsoft.Json.JsonTextReader, Newtonsoft.Json.JsonValidatingReader, and Newtonsoft.Json.Serialization.TraceJsonReader.
Definition at line 1008 of file JsonReader.cs.
        {
            this._currentState = JsonReader.State.Closed;
            this._tokenType = JsonToken.None;
            this._value = null;
        }
Referenced by Newtonsoft.Json.JsonValidatingReader.Close(), Newtonsoft.Json.Serialization.TraceJsonReader.Close(), and Newtonsoft.Json.JsonReader.Dispose().