Terraria Decompiled: Newtonsoft.Json.JsonReader.SetPostValueState
SetPostValueState()
void Newtonsoft.Json.JsonReader.SetPostValueState (bool updateIndex) inline package
Definition at line 900 of file JsonReader.cs.
        {
            if (this.Peek() != JsonContainerType.None)
            {
                this._currentState = JsonReader.State.PostValue;
            }
            else
            {
                this.SetFinished();
            }
            if (updateIndex)
            {
                this.UpdateScopeWithFinishedValue();
            }
        }
References Newtonsoft.Json.JsonReader.Peek(), Newtonsoft.Json.JsonReader.SetFinished(), and Newtonsoft.Json.JsonReader.UpdateScopeWithFinishedValue().
Referenced by Newtonsoft.Json.JsonReader.SetToken().