Terraria Decompiled: System.Reflection.Emit.AssemblyBuilder.Save
Save() [2/2]
void System.Reflection.Emit.AssemblyBuilder.Save (string assemblyFileName, PortableExecutableKinds portableExecutableKind, ImageFileMachine imageFileMachine) inline
Definition at line 750 of file AssemblyBuilder.cs.
        {
            this.peKind = portableExecutableKind;
            this.machine = imageFileMachine;
            if ((this.peKind & PortableExecutableKinds.PE32Plus) != PortableExecutableKinds.NotAPortableExecutableImage || (this.peKind & PortableExecutableKinds.Unmanaged32Bit) != PortableExecutableKinds.NotAPortableExecutableImage)
            {
                throw new NotImplementedException(this.peKind.ToString());
            }
            if (this.machine == ImageFileMachine.IA64 || this.machine == ImageFileMachine.AMD64)
            {
                throw new NotImplementedException(this.machine.ToString());
            }
            if (this.resource_writers != null)
            {
                foreach (object obj in this.resource_writers)
                {
                    IResourceWriter resourceWriter = (IResourceWriter)obj;
                    resourceWriter.Generate();
                    resourceWriter.Close();
                }
            }
            ModuleBuilder moduleBuilder = null;
            if (this.modules != null)
            {
                foreach (ModuleBuilder moduleBuilder2 in this.modules)
                {
                    if (moduleBuilder2.FileName == assemblyFileName)
                    {
                        moduleBuilder = moduleBuilder2;
                    }
                }
            }
            if (moduleBuilder == null)
            {
                moduleBuilder = this.DefineDynamicModule("RefEmit_OnDiskManifestModule", assemblyFileName);
            }
            if (!this.is_module_only)
            {
                moduleBuilder.IsMain = true;
            }
            if (this.entry_point != null && this.entry_point.DeclaringType.Module != moduleBuilder)
            {
                Type[] array2;
                if (this.entry_point.GetParametersCount() == 1)
                {
                    array2 = new Type[] { typeof(string) };
                }
                else
                {
                    array2 = Type.EmptyTypes;
                }
                MethodBuilder methodBuilder = moduleBuilder.DefineGlobalMethod("__EntryPoint$", MethodAttributes.Static, this.entry_point.ReturnType, array2);
                ILGenerator ilgenerator = methodBuilder.GetILGenerator();
                if (array2.Length == 1)
                {
                    ilgenerator.Emit(OpCodes.Ldarg_0);
                }
                ilgenerator.Emit(OpCodes.Tailcall);
                ilgenerator.Emit(OpCodes.Call, this.entry_point);
                ilgenerator.Emit(OpCodes.Ret);
                this.entry_point = methodBuilder;
            }
            if (this.version_res != null)
            {
                this.DefineVersionInfoResourceImpl(assemblyFileName);
            }
            if (this.sn != null)
            {
                this.public_key = this.sn.PublicKey;
            }
            foreach (ModuleBuilder moduleBuilder3 in this.modules)
            {
                if (moduleBuilder3 != moduleBuilder)
                {
                    moduleBuilder3.Save();
                }
            }
            moduleBuilder.Save();
            if (this.sn != null && this.sn.CanSign)
            {
                this.sn.Sign(Path.Combine(this.AssemblyDir, assemblyFileName));
            }
            this.created = true;
        }
References System.Reflection.Emit.OpCodes.Call, System.Resources.IResourceWriter.Close(), System.IO.Path.Combine(), System.Runtime.InteropServices._MethodInfo.DeclaringType, System.Reflection.Emit.AssemblyBuilder.DefineDynamicModule(), System.Reflection.Emit.ModuleBuilder.DefineGlobalMethod(), System.Reflection.Emit.AssemblyBuilder.DefineVersionInfoResourceImpl(), System.Reflection.Emit.ILGenerator.Emit(), System.Type.EmptyTypes, System.Reflection.Emit.AssemblyBuilder.entry_point, System.Reflection.Emit.ModuleBuilder.FileName, System.Resources.IResourceWriter.Generate(), System.Reflection.Emit.MethodBuilder.GetILGenerator(), System.Reflection.MethodBase.GetParametersCount(), System.Reflection.Emit.AssemblyBuilder.is_module_only, System.Reflection.Emit.OpCodes.Ldarg_0, System.Reflection.Emit.AssemblyBuilder.machine, System.Type.Module, System.Reflection.Emit.AssemblyBuilder.modules, System.obj, System.Reflection.Emit.AssemblyBuilder.peKind, System.Reflection.Emit.AssemblyBuilder.resource_writers, System.Reflection.Emit.OpCodes.Ret, System.Reflection.Emit.ModuleBuilder.Save(), System.Reflection.Emit.AssemblyBuilder.sn, System.Reflection.Emit.OpCodes.Tailcall, and System.Reflection.Emit.AssemblyBuilder.version_res.