Terraria Decompiled: Newtonsoft.Json.JsonReader.Read
Read()
bool Newtonsoft.Json.JsonReader.Read () abstract
Referenced by Newtonsoft.Json.Converters.XmlNodeConverter.CreateDocumentType(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateDynamic(), Newtonsoft.Json.Converters.XmlNodeConverter.CreateInstruction(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateISerializable(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateJObject(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(), Newtonsoft.Json.Converters.XmlNodeConverter.DeserializeNode(), Newtonsoft.Json.JsonReader.GetContentToken(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.HandleError(), Newtonsoft.Json.Linq.JArray.Load(), Newtonsoft.Json.Linq.JConstructor.Load(), Newtonsoft.Json.Linq.JObject.Load(), Newtonsoft.Json.Linq.JProperty.Load(), Newtonsoft.Json.JsonReader.MoveToContent(), Newtonsoft.Json.Linq.JArray.Parse(), Newtonsoft.Json.Linq.JObject.Parse(), Newtonsoft.Json.Linq.JToken.Parse(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateMultidimensionalArray(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(), Newtonsoft.Json.JsonConvert.PopulateObject(), Newtonsoft.Json.JsonValidatingReader.Read(), Newtonsoft.Json.Serialization.TraceJsonReader.Read(), Newtonsoft.Json.JsonReader.ReadAndAssert(), Newtonsoft.Json.JsonReader.ReadAndMoveToContent(), Newtonsoft.Json.Converters.XmlNodeConverter.ReadArrayElements(), Newtonsoft.Json.JsonReader.ReadArrayIntoByteArray(), Newtonsoft.Json.Converters.XmlNodeConverter.ReadAttributeElements(), Newtonsoft.Json.Converters.BinaryConverter.ReadByteArray(), Newtonsoft.Json.Linq.JContainer.ReadContentFrom(), Newtonsoft.Json.JsonReader.ReaderReadAndAssert(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(), Newtonsoft.Json.Linq.JToken.ReadFrom(), Newtonsoft.Json.Converters.JavaScriptDateTimeConverter.ReadJson(), Newtonsoft.Json.Converters.XmlNodeConverter.ReadJson(), Terraria.WorldBuilding.WorldGenSnapshot.SnapshotGenVars.ReadJson(), Newtonsoft.Json.Converters.ExpandoObjectConverter.ReadList(), Newtonsoft.Json.Converters.ExpandoObjectConverter.ReadObject(), Newtonsoft.Json.Converters.RegexConverter.ReadRegexObject(), Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(), Newtonsoft.Json.JsonReader.Skip(), Newtonsoft.Json.JsonWriter.WriteConstructorDate(), and Newtonsoft.Json.JsonWriter.WriteToken().