Terraria Decompiled: System.Reflection.Emit.AssemblyBuilder.DefineDynamicModule
DefineDynamicModule() [5/5]
ModuleBuilder System.Reflection.Emit.AssemblyBuilder.DefineDynamicModule (string name, string fileName, bool emitSymbolInfo, bool transient) inline private
Definition at line 324 of file AssemblyBuilder.cs.
        {
            this.check_name_and_filename(name, fileName, false);
            if (!transient)
            {
                if (Path.GetExtension(fileName) == string.Empty)
                {
                    throw new ArgumentException("Module file name '" + fileName + "' must have file extension.");
                }
                if (!this.IsSave)
                {
                    throw new NotSupportedException("Persistable modules are not supported in a dynamic assembly created with AssemblyBuilderAccess.Run");
                }
                if (this.created)
                {
                    throw new InvalidOperationException("Assembly was already saved.");
                }
            }
            ModuleBuilder moduleBuilder = new ModuleBuilder(this, name, fileName, emitSymbolInfo, transient);
            if (this.modules != null && this.is_module_only)
            {
                throw new InvalidOperationException("A module-only assembly can only contain one module.");
            }
            if (this.modules != null)
            {
                ModuleBuilder[] array = new ModuleBuilder[this.modules.Length + 1];
                Array.Copy(this.modules, array, this.modules.Length);
                this.modules = array;
            }
            else
            {
                this.modules = new ModuleBuilder[1];
            }
            this.modules[this.modules.Length - 1] = moduleBuilder;
            return moduleBuilder;
        }
References System.array, System.Reflection.Emit.AssemblyBuilder.check_name_and_filename(), System.Array.Copy(), System.Reflection.Emit.AssemblyBuilder.created, System.IO.Path.GetExtension(), System.Reflection.Emit.AssemblyBuilder.is_module_only, System.Reflection.Emit.AssemblyBuilder.IsSave, System.Reflection.Emit.AssemblyBuilder.modules, and System.Reflection.Emit.AssemblyBuilder.name.