Terraria Decompiled: System.Runtime.Remoting.Messaging.MethodCall.ResolveMethod
ResolveMethod()
void System.Runtime.Remoting.Messaging.MethodCall.ResolveMethod () inline
Definition at line 448 of file MethodCall.cs.
        {
            if (this._uri != null)
            {
                Type serverTypeForUri = RemotingServices.GetServerTypeForUri(this._uri);
                if (serverTypeForUri == null)
                {
                    string text = ((this._typeName != null) ? (" (" + this._typeName + ")") : "");
                    throw new RemotingException("Requested service not found" + text + ". No receiver for uri " + this._uri);
                }
                Type type = this.CastTo(this._typeName, serverTypeForUri);
                if (type == null)
                {
                    throw new RemotingException(string.Concat(new string[] { "Cannot cast from client type '", this._typeName, "' to server type '", serverTypeForUri.FullName, "'" }));
                }
                this._methodBase = RemotingServices.GetMethodBaseFromName(type, this._methodName, this._methodSignature);
                if (this._methodBase == null)
                {
                    string text2 = "Method ";
                    string methodName = this._methodName;
                    string text3 = " not found in ";
                    Type type2 = type;
                    throw new RemotingException(text2 + methodName + text3 + ((type2 != null) ? type2.ToString() : null));
                }
                if (type != serverTypeForUri && type.IsInterface && !serverTypeForUri.IsInterface)
                {
                    this._methodBase = RemotingServices.GetVirtualMethod(serverTypeForUri, this._methodBase);
                    if (this._methodBase == null)
                    {
                        string text4 = "Method ";
                        string methodName2 = this._methodName;
                        string text5 = " not found in ";
                        Type type3 = serverTypeForUri;
                        throw new RemotingException(text4 + methodName2 + text5 + ((type3 != null) ? type3.ToString() : null));
                    }
                }
            }
            else
            {
                this._methodBase = RemotingServices.GetMethodBaseFromMethodMessage(this);
                if (this._methodBase == null)
                {
                    throw new RemotingException("Method " + this._methodName + " not found in " + this.TypeName);
                }
            }
            if (this._methodBase.IsGenericMethod && this._methodBase.ContainsGenericParameters)
            {
                if (this.GenericArguments == null)
                {
                    throw new RemotingException("The remoting infrastructure does not support open generic methods.");
                }
                this._methodBase = ((MethodInfo)this._methodBase).MakeGenericMethod(this.GenericArguments);
            }
        }
References System.Runtime.Remoting.Messaging.MethodCall._methodBase, System.Runtime.Remoting.Messaging.MethodCall._methodName, System.Runtime.Remoting.Messaging.MethodCall._methodSignature, System.Runtime.Remoting.Messaging.MethodCall._typeName, System.Runtime.Remoting.Messaging.MethodCall._uri, System.Runtime.Remoting.Messaging.MethodCall.CastTo(), System.Type.FullName, System.Runtime.Remoting.Messaging.MethodCall.GenericArguments, System.Runtime.Remoting.RemotingServices.GetMethodBaseFromMethodMessage(), System.Runtime.Remoting.RemotingServices.GetMethodBaseFromName(), System.Runtime.Remoting.RemotingServices.GetServerTypeForUri(), System.Runtime.Remoting.RemotingServices.GetVirtualMethod(), System.Reflection.MethodBase.IsGenericMethod, System.Type.IsInterface, System.text, and System.Type.ToString().
Referenced by System.Runtime.Remoting.Messaging.MethodCall.MethodCall(), System.Runtime.Remoting.Messaging.MethodCall.MethodCall(), and System.Runtime.Remoting.Messaging.MethodCall.MethodCall().