Terraria Decompiled: System.Runtime.Remoting.Messaging.MethodCall.InitMethodProperty
InitMethodProperty()
virtual void System.Runtime.Remoting.Messaging.MethodCall.InitMethodProperty (string key, object value) inline package virtual
Reimplemented in System.Runtime.Remoting.Messaging.ConstructionCall.
Definition at line 130 of file MethodCall.cs.
        {
            uint num = <PrivateImplementationDetails>.ComputeStringHash(key);
            if (num <= 1619225942U)
            {
                if (num != 990701179U)
                {
                    if (num != 1201911322U)
                    {
                        if (num == 1619225942U)
{
                            if (key == "__Args")
{
                                this._args = (object[])value;
                                return;
                            }
                        }
                    }
                    else if (key == "__CallContext")
                    {
                        this._callContext = (LogicalCallContext)value;
                        return;
                    }
                }
                else if (key == "__Uri")
                {
                    this._uri = (string)value;
                    return;
                }
            }
            else if (num <= 2850677384U)
            {
                if (num != 2010141056U)
                {
                    if (num == 2850677384U)
                    {
                        if (key == "__GenericArguments")
{
                            this._genericArguments = (Type[])value;
                            return;
                        }
                    }
                }
                else if (key == "__TypeName")
                {
                    this._typeName = (string)value;
                    return;
                }
            }
            else if (num != 3166241401U)
            {
                if (num == 3679129400U)
                {
                    if (key == "__MethodSignature")
                    {
                        this._methodSignature = (Type[])value;
                        return;
                    }
                }
            }
            else if (key == "__MethodName")
            {
                this._methodName = (string)value;
                return;
            }
            this.Properties[key] = value;
        }
References System.key, System.Runtime.Remoting.Messaging.MethodCall.LogicalCallContext, System.Runtime.Remoting.Messaging.MethodCall.Properties, System.U, and System.value.
Referenced by System.Runtime.Remoting.Messaging.MethodCall.MethodCall(), System.Runtime.Remoting.Messaging.MethodCall.MethodCall(), and System.Runtime.Remoting.Messaging.MethodCall.MethodCall().