Terraria Decompiled: System.Runtime.Remoting.Messaging.MethodCall.MethodCall
MethodCall() [1/7]
System.Runtime.Remoting.Messaging.MethodCall.MethodCall (Header[] h1) inline
Definition at line 17 of file MethodCall.cs.
        {
            this.Init();
            if (h1 == null || h1.Length == 0)
            {
                return;
            }
            foreach (Header header in h1)
            {
                this.InitMethodProperty(header.Name, header.Value);
            }
            this.ResolveMethod();
        }
References System.Runtime.Remoting.Messaging.MethodCall.Init(), System.Runtime.Remoting.Messaging.MethodCall.InitMethodProperty(), System.Runtime.Remoting.Messaging.Header.Name, System.Runtime.Remoting.Messaging.MethodCall.ResolveMethod(), and System.Runtime.Remoting.Messaging.Header.Value.