Terraria Decompiled: NVorbis.Floor0.Apply
Apply()
void NVorbis.Floor0.Apply (IFloorData floorData, int blockSize, float[] residue) inline
Implements NVorbis.Contracts.IFloor.
Definition at line 136 of file Floor0.cs.
        {
            Floor0.Data data = floorData as Floor0.Data;
            if (data == null)
            {
                throw new ArgumentException("Incorrect packet data!");
            }
            int num = blockSize / 2;
            if (data.Amp > 0f)
            {
                int[] array = this._barkMaps[blockSize];
                float[] array2 = this._wMap[blockSize];
                int i;
                for (i = 0; i < this._order; i++)
                {
                    data.Coeff[i] = 2f * (float)Math.Cos((double)data.Coeff[i]);
                }
                i = 0;
                while (i < num)
                {
                    int num2 = array[i];
                    float num3 = 0.5f;
                    float num4 = 0.5f;
                    float num5 = array2[num2];
                    int j;
                    for (j = 1; j < this._order; j += 2)
                    {
                        num4 *= num5 - data.Coeff[j - 1];
                        num3 *= num5 - data.Coeff[j];
                    }
                    if (j == this._order)
                    {
                        num4 *= num5 - data.Coeff[j - 1];
                        num3 *= num3 * (4f - num5 * num5);
                        num4 *= num4;
                    }
                    else
                    {
                        num3 *= num3 * (2f - num5);
                        num4 *= num4 * (2f + num5);
                    }
                    num4 = data.Amp / (float)Math.Sqrt((double)(num3 + num4)) - (float)this._ampOfs;
                    num4 = (float)Math.Exp((double)(num4 * 0.11512925f));
                    residue[i] *= num4;
                    while (array[++i] == num2)
                    {
                        residue[i] *= num4;
                    }
                }
                return;
            }
            Array.Clear(residue, 0, num);
        }
References NVorbis.Floor0._ampOfs, NVorbis.Floor0._barkMaps, NVorbis.Floor0._order, NVorbis.Floor0._wMap, NVorbis.Floor0.Data.Amp, System.array, System.Array.Clear(), NVorbis.Floor0.Data.Coeff, System.Math.Cos(), System.Math.Exp(), and System.Math.Sqrt().