Terraria Decompiled: NVorbis.Floor0.SynthesizeBarkCurve
SynthesizeBarkCurve()
int[] NVorbis.Floor0.SynthesizeBarkCurve (int n) inline private
Definition at line 52 of file Floor0.cs.
        {
            float num = (float)this._bark_map_size / Floor0.toBARK((double)(this._rate / 2));
            int[] array = new int[n + 1];
            for (int i = 0; i < n - 1; i++)
            {
                array[i] = Math.Min(this._bark_map_size - 1, (int)Math.Floor((double)(Floor0.toBARK((double)((float)this._rate / 2f / (float)n * (float)i)) * num)));
            }
            array[n] = -1;
            return array;
        }
References NVorbis.Floor0._bark_map_size, NVorbis.Floor0._rate, System.array, System.Math.Floor(), System.Math.Min(), and NVorbis.Floor0.toBARK().
Referenced by NVorbis.Floor0.Init().