Terraria Decompiled: NVorbis.Floor0.Init
Init()
void NVorbis.Floor0.Init (IPacket packet, int channels, int block0Size, int block1Size, ICodebook[] codebooks) inline
Implements NVorbis.Contracts.IFloor.
Definition at line 13 of file Floor0.cs.
        {
            this._order = (int)packet.ReadBits(8);
            this._rate = (int)packet.ReadBits(16);
            this._bark_map_size = (int)packet.ReadBits(16);
            this._ampBits = (int)packet.ReadBits(6);
            this._ampOfs = (int)packet.ReadBits(8);
            this._books = new ICodebook[(int)packet.ReadBits(4) + 1];
            if (this._order < 1 || this._rate < 1 || this._bark_map_size < 1 || this._books.Length == 0)
            {
                throw new InvalidDataException();
            }
            this._ampDiv = (1 << this._ampBits) - 1;
            for (int i = 0; i < this._books.Length; i++)
            {
                int num = (int)packet.ReadBits(8);
                if (num < 0 || num >= codebooks.Length)
                {
                    throw new InvalidDataException();
                }
                ICodebook codebook = codebooks[num];
                if (codebook.MapType == 0 || codebook.Dimensions < 1)
                {
                    throw new InvalidDataException();
                }
                this._books[i] = codebook;
            }
            this._bookBits = Utils.ilog(this._books.Length);
            Dictionary<int, int[]> dictionary = new Dictionary<int, int[]>();
            dictionary[block0Size] = this.SynthesizeBarkCurve(block0Size / 2);
            dictionary[block1Size] = this.SynthesizeBarkCurve(block1Size / 2);
            this._barkMaps = dictionary;
            Dictionary<int, float[]> dictionary2 = new Dictionary<int, float[]>();
            dictionary2[block0Size] = this.SynthesizeWDelMap(block0Size / 2);
            dictionary2[block1Size] = this.SynthesizeWDelMap(block1Size / 2);
            this._wMap = dictionary2;
        }
References NVorbis.Floor0._ampBits, NVorbis.Floor0._bark_map_size, NVorbis.Floor0._books, NVorbis.Floor0._order, NVorbis.Floor0._rate, System.dictionary, NVorbis.Contracts.ICodebook.Dimensions, NVorbis.Utils.ilog(), int, NVorbis.Contracts.ICodebook.MapType, NVorbis.Contracts.IPacket.ReadBits(), NVorbis.Floor0.SynthesizeBarkCurve(), and NVorbis.Floor0.SynthesizeWDelMap().