Terraria Decompiled: NVorbis.Floor0.Unpack
Unpack()
IFloorData NVorbis.Floor0.Unpack (IPacket packet, int blockSize, int channel) inline
Implements NVorbis.Contracts.IFloor.
Definition at line 83 of file Floor0.cs.
        {
            Floor0.Data data = new Floor0.Data
            {
                Coeff = new float[this._order + 1]
            };
            data.Amp = packet.ReadBits(this._ampBits);
            if (data.Amp > 0f)
            {
                Array.Clear(data.Coeff, 0, data.Coeff.Length);
                data.Amp = data.Amp / (float)this._ampDiv * (float)this._ampOfs;
                uint num = (uint)packet.ReadBits(this._bookBits);
                if ((ulong)num >= (ulong)((long)this._books.Length))
                {
                    data.Amp = 0f;
                    return data;
                }
                ICodebook codebook = this._books[(int)num];
                int i = 0;
                while (i < this._order)
                {
                    int num2 = codebook.DecodeScalar(packet);
                    if (num2 == -1)
                    {
                        data.Amp = 0f;
                        return data;
                    }
                    int num3 = 0;
                    while (i < this._order && num3 < codebook.Dimensions)
                    {
                        data.Coeff[i] = codebook[num2, num3];
                        num3++;
                        i++;
                    }
                }
                float num4 = 0f;
                int j = 0;
                while (j < this._order)
                {
                    int num5 = 0;
                    while (j < this._order && num5 < codebook.Dimensions)
                    {
                        data.Coeff[j] += num4;
                        j++;
                        num5++;
                    }
                    num4 = data.Coeff[j - 1];
                }
            }
            return data;
        }
References NVorbis.Floor0._ampBits, NVorbis.Floor0._ampDiv, NVorbis.Floor0._ampOfs, NVorbis.Floor0._books, NVorbis.Floor0._order, NVorbis.Floor0.Data.Amp, System.Array.Clear(), NVorbis.Floor0.Data.Coeff, NVorbis.Contracts.ICodebook.DecodeScalar(), NVorbis.Contracts.ICodebook.Dimensions, int, and NVorbis.Contracts.IPacket.ReadBits().