Terraria Decompiled: System.Action
Action()
delegate void System.Action ()
Referenced by Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.BuildInfinitesMenuContents(), Terraria.GameContent.UI.NewCraftingUI.BuildInfinitesMenuContents(), Terraria.GameContent.UI.States.UIBestiaryTest.BuildPage(), System.Runtime.CompilerServices.AsyncMethodBuilderCore.CreateContinuationWrapper(), Terraria.GameContent.UI.States.UICharacterCreation.CreateHSLSliderButtonBase(), Terraria.Main.DrawInterface_29_SettingsButton(), Terraria.Main.DrawMenu(), System.Threading.Tasks.Task< TResult >.FinishContinuations(), System.Runtime.CompilerServices.AsyncMethodBuilderCore.GetCompletionAction(), System.Threading.Tasks.Task< TResult >.GetDelegatesFromContinuationObject(), System.Threading.Tasks.Task< TResult >.InnerInvoke(), System.Threading.Tasks.AwaitTaskContinuation.InvokeAction(), Terraria.WorldGen.JustQuit(), Terraria.GameContent.UI.States.UICharacterCreation.MakeCharPreview(), Terraria.GameContent.UI.States.UICharacterCreation.MakeClothStylesMenu(), Terraria.GameContent.UI.States.UITextWrappingTest.MakeElement(), Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem.OnFinishedSettingName(), Terraria.Social.WeGame.NetServerSocialModule.OnLobbyCreated(), Terraria.WorldBuilding.WorldGenerator.Controller.OnPassCompleted(), Terraria.Social.WeGame.CoreSocialModule.ProcessRailSystemStateChange(), Terraria.Main.RenderToTargets(), Terraria.WorldGen.Reset(), System.Threading.Tasks.TaskSchedulerAwaitTaskContinuation.Run(), System.Runtime.CompilerServices.YieldAwaitable.YieldAwaiter.RunAction(), Terraria.WorldGen.SaveAndQuitCallBack(), Terraria.Map.MapHelper.SaveMap(), Terraria.WorldGen.serverLoadWorld(), Terraria.WorldGen.StartHardmode(), System.Runtime.CompilerServices.AsyncMethodBuilderCore.TryGetStateMachineForDebugger(), and Terraria.GameContent.UI.States.UIWorldGenDebug.UIWorldGenDebug().