Terraria Decompiled: FAudio.FACTAudioEngine_PrepareWave
FACTAudioEngine_PrepareWave() [2/2]
static unsafe uint FAudio.FACTAudioEngine_PrepareWave (IntPtr pEngine, uint dwFlags, string szWavePath, uint wStreamingPacketSize, uint dwAlignment, uint dwPlayOffset, byte nLoopCount, out IntPtr ppWave) inline static
Definition at line 328 of file FAudio.cs.
    {
        byte* ptr = FAudio.Utf8Encode(szWavePath);
        uint num = FAudio.FACTAudioEngine_PrepareWave(pEngine, dwFlags, ptr, wStreamingPacketSize, dwAlignment, dwPlayOffset, nLoopCount, out ppWave);
        Marshal.FreeHGlobal((IntPtr)((void*)ptr));
        return num;
    }
References FACTAudioEngine_PrepareWave(), System.Runtime.InteropServices.Marshal.FreeHGlobal(), and Utf8Encode().