Terraria Decompiled: FAudio.FACTWaveBank_GetWaveIndex
FACTWaveBank_GetWaveIndex() [2/2]
static unsafe ushort FAudio.FACTWaveBank_GetWaveIndex (IntPtr pWaveBank, string szFriendlyName) inline static
Definition at line 461 of file FAudio.cs.
    {
        int num = FAudio.Utf8Size(szFriendlyName);
        byte* ptr = stackalloc byte[(UIntPtr)num];
        return FAudio.FACTWaveBank_GetWaveIndex(pWaveBank, FAudio.Utf8Encode(szFriendlyName, ptr, num));
    }
References FACTWaveBank_GetWaveIndex(), Utf8Encode(), and Utf8Size().