Terraria Decompiled: System.IO.TextReader.ReadLine
ReadLine()
virtual string System.IO.TextReader.ReadLine () inline virtual
Reimplemented in System.IO.CStreamReader, System.IO.StreamReader, System.IO.StreamReader.NullStreamReader, System.IO.StringReader, System.IO.TextReader.NullTextReader, System.IO.TextReader.SyncTextReader, and System.IO.UnexceptionalStreamReader.
Definition at line 155 of file TextReader.cs.
        {
            StringBuilder stringBuilder = new StringBuilder();
            int num;
            for (;;)
            {
                num = this.Read();
                if (num == -1)
                {
                    goto IL_0043;
                }
                if (num == 13 || num == 10)
                {
                    break;
                }
                stringBuilder.Append((char)num);
            }
            if (num == 13 && this.Peek() == 10)
            {
                this.Read();
            }
            return stringBuilder.ToString();
            IL_0043:
            if (stringBuilder.Length > 0)
            {
                return stringBuilder.ToString();
            }
            return null;
        }
References System.Text.StringBuilder.Append(), System.Text.StringBuilder.Length, System.IO.TextReader.Peek(), System.IO.TextReader.Read(), and System.Text.StringBuilder.ToString().
Referenced by CsvHelper.CsvParser.ReadExcelSeparator(), System.Console.ReadLine(), System.IO.TextReader.SyncTextReader.ReadLine(), and System.IO.TextReader.ReadLineAsync().