Terraria Decompiled: Microsoft.Xna.Framework.BoundingFrustum.IntersectionPoint
IntersectionPoint()
static void Microsoft.Xna.Framework.BoundingFrustum.IntersectionPoint (ref Plane a, ref Plane b, ref Plane c, out Vector3 result) inline static private
Definition at line 391 of file BoundingFrustum.cs.
        {
            Vector3 vector;
            Vector3.Cross(ref b.Normal, ref c.Normal, out vector);
            float num;
            Vector3.Dot(ref a.Normal, ref vector, out num);
            num *= -1f;
            Vector3.Cross(ref b.Normal, ref c.Normal, out vector);
            Vector3 vector2;
            Vector3.Multiply(ref vector, a.D, out vector2);
            Vector3.Cross(ref c.Normal, ref a.Normal, out vector);
            Vector3 vector3;
            Vector3.Multiply(ref vector, b.D, out vector3);
            Vector3.Cross(ref a.Normal, ref b.Normal, out vector);
            Vector3 vector4;
            Vector3.Multiply(ref vector, c.D, out vector4);
            result.X = (vector2.X + vector3.X + vector4.X) / num;
            result.Y = (vector2.Y + vector3.Y + vector4.Y) / num;
            result.Z = (vector2.Z + vector3.Z + vector4.Z) / num;
        }
References Microsoft.Xna.Framework.Vector3.Cross(), Microsoft.Xna.Framework.Vector3.Dot(), Microsoft.Xna.Framework.Vector3.Multiply(), Microsoft.Xna.Framework.Vector3.X, Microsoft.Xna.Framework.Vector3.Y, and Microsoft.Xna.Framework.Vector3.Z.
Referenced by Microsoft.Xna.Framework.BoundingFrustum.CreateCorners().