Terraria Decompiled: System.Runtime.Remoting.Messaging.CADMessageBase.MarshalArgument
MarshalArgument()
object System.Runtime.Remoting.Messaging.CADMessageBase.MarshalArgument (object arg, ref ArrayList args) inline protected
Definition at line 110 of file CADMessageBase.cs.
        {
            if (arg == null)
            {
                return null;
            }
            if (CADMessageBase.IsPossibleToIgnoreMarshal(arg))
            {
                return arg;
            }
            MarshalByRefObject marshalByRefObject = arg as MarshalByRefObject;
            if (marshalByRefObject != null && !RemotingServices.IsTransparentProxy(marshalByRefObject))
            {
                return new CADObjRef(RemotingServices.Marshal(marshalByRefObject), Thread.GetDomainID());
            }
            if (args == null)
            {
                args = new ArrayList();
            }
            args.Add(arg);
            return new CADArgHolder(args.Count - 1);
        }
References System.Threading.Thread.GetDomainID(), System.Runtime.Remoting.Messaging.CADMessageBase.IsPossibleToIgnoreMarshal(), System.Runtime.Remoting.RemotingServices.IsTransparentProxy(), and System.Runtime.Remoting.RemotingServices.Marshal().
Referenced by System.Runtime.Remoting.Messaging.CADMessageBase.MarshalArguments().