Terraria Decompiled: System.Runtime.Remoting.Messaging.CADMessageBase.UnmarshalArgument
UnmarshalArgument()
object System.Runtime.Remoting.Messaging.CADMessageBase.UnmarshalArgument (object arg, ArrayList args) inline protected
Definition at line 134 of file CADMessageBase.cs.
        {
            if (arg == null)
            {
                return null;
            }
            CADArgHolder cadargHolder = arg as CADArgHolder;
            if (cadargHolder != null)
            {
                return args[cadargHolder.index];
            }
            CADObjRef cadobjRef = arg as CADObjRef;
            if (cadobjRef != null)
            {
                return RemotingServices.Unmarshal(cadobjRef.objref.DeserializeInTheCurrentDomain(cadobjRef.SourceDomain, cadobjRef.TypeInfo));
            }
            if (arg is Array)
            {
                Array array = (Array)arg;
                Array array2;
                switch (Type.GetTypeCode(arg.GetType().GetElementType()))
                {
                case TypeCode.Boolean:
                    array2 = new bool[array.Length];
                    break;
                case TypeCode.Char:
                    array2 = new char[array.Length];
                    break;
                case TypeCode.SByte:
                    array2 = new sbyte[array.Length];
                    break;
                case TypeCode.Byte:
                    array2 = new byte[array.Length];
                    break;
                case TypeCode.Int16:
                    array2 = new short[array.Length];
                    break;
                case TypeCode.UInt16:
                    array2 = new ushort[array.Length];
                    break;
                case TypeCode.Int32:
                    array2 = new int[array.Length];
                    break;
                case TypeCode.UInt32:
                    array2 = new uint[array.Length];
                    break;
                case TypeCode.Int64:
                    array2 = new long[array.Length];
                    break;
                case TypeCode.UInt64:
                    array2 = new ulong[array.Length];
                    break;
                case TypeCode.Single:
                    array2 = new float[array.Length];
                    break;
                case TypeCode.Double:
                    array2 = new double[array.Length];
                    break;
                case TypeCode.Decimal:
                    array2 = new decimal[array.Length];
                    break;
                default:
                    throw new NotSupportedException();
                }
                array.CopyTo(array2, 0);
                return array2;
            }
            switch (Type.GetTypeCode(arg.GetType()))
            {
            case TypeCode.Boolean:
                return (bool)arg;
            case TypeCode.Char:
                return (char)arg;
            case TypeCode.SByte:
                return (sbyte)arg;
            case TypeCode.Byte:
                return (byte)arg;
            case TypeCode.Int16:
                return (short)arg;
            case TypeCode.UInt16:
                return (ushort)arg;
            case TypeCode.Int32:
                return (int)arg;
            case TypeCode.UInt32:
                return (uint)arg;
            case TypeCode.Int64:
                return (long)arg;
            case TypeCode.UInt64:
                return (ulong)arg;
            case TypeCode.Single:
                return (float)arg;
            case TypeCode.Double:
                return (double)arg;
            case TypeCode.Decimal:
                return (decimal)arg;
            case TypeCode.DateTime:
                return new DateTime(((DateTime)arg).Ticks);
            case TypeCode.String:
                return string.Copy((string)arg);
            }
            if (arg is TimeSpan)
            {
                return new TimeSpan(((TimeSpan)arg).Ticks);
            }
            if (arg is IntPtr)
            {
                return (IntPtr)arg;
            }
            string text = "Parameter of type ";
            Type type = arg.GetType();
            throw new NotSupportedException(text + ((type != null) ? type.ToString() : null) + " cannot be unmarshalled");
        }
References System.array, System.Reflection.Array, System.DateTime, System.Runtime.Remoting.ObjRef.DeserializeInTheCurrentDomain(), System.Type.GetTypeCode(), System.Runtime.Remoting.Messaging.CADArgHolder.index, System.Runtime.Remoting.Messaging.CADObjRef.objref, System.Runtime.Remoting.Messaging.CADObjRef.SourceDomain, System.text, System.Type.ToString(), System.Runtime.Remoting.Messaging.CADObjRef.TypeInfo, and System.Runtime.Remoting.RemotingServices.Unmarshal().
Referenced by System.Runtime.Remoting.Messaging.CADMessageBase.UnmarshalArguments().