Terraria Decompiled: Terraria.Social.Base.AWorkshopEntry.TryReadingManifest
TryReadingManifest()
static bool Terraria.Social.Base.AWorkshopEntry.TryReadingManifest (string filePath, out FoundWorkshopEntryInfo info) inline static
Definition at line 40 of file AWorkshopEntry.cs.
        {
            info = null;
            if (!File.Exists(filePath))
            {
                return false;
            }
            string text = File.ReadAllText(filePath);
            info = new FoundWorkshopEntryInfo();
            Dictionary<string, object> dictionary = JsonConvert.DeserializeObject<Dictionary<string, object>>(text, AWorkshopEntry.SerializerSettings);
            if (dictionary == null)
            {
                return false;
            }
            if (!AWorkshopEntry.TryGet<ulong>(dictionary, "SteamEntryId", out info.workshopEntryId))
            {
                return false;
            }
            int num;
            if (!AWorkshopEntry.TryGet<int>(dictionary, "WorkshopPublishedVersion", out num))
            {
                num = 1;
            }
            info.publishedVersion = num;
            JArray jarray;
            if (AWorkshopEntry.TryGet<JArray>(dictionary, "Tags", out jarray))
            {
                info.tags = jarray.ToObject<string[]>();
            }
            int num2;
            if (AWorkshopEntry.TryGet<int>(dictionary, "Publicity", out num2))
            {
                info.publicity = (WorkshopItemPublicSettingId)num2;
            }
            AWorkshopEntry.TryGet<string>(dictionary, "PreviewImagePath", out info.previewImagePath);
            return true;
        }
References Newtonsoft.Json.JsonConvert.DeserializeObject(), System.dictionary, System.IO.File.Exists(), System.info, System.IO.File.ReadAllText(), Terraria.Social.Base.AWorkshopEntry.SerializerSettings, System.text, and Newtonsoft.Json.Linq.JToken.ToObject().
Referenced by Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.PublishContent(), Terraria.Social.Steam.WorkshopSocialModule.TryGetInfoForResourcePack(), and Terraria.Social.Steam.WorkshopSocialModule.TryGetInfoForWorld().