Terraria Decompiled: System.Runtime.Remoting.Messaging.CADMessageBase.GetSignature
GetSignature()
static Type[] System.Runtime.Remoting.Messaging.CADMessageBase.GetSignature (MethodBase methodBase, bool load) inline static protected
Definition at line 26 of file CADMessageBase.cs.
        {
            ParameterInfo[] parameters = methodBase.GetParameters();
            Type[] array = new Type[parameters.Length];
            for (int i = 0; i < parameters.Length; i++)
            {
                if (load)
                {
                    array[i] = Type.GetType(parameters[i].ParameterType.AssemblyQualifiedName, true);
                }
                else
                {
                    array[i] = parameters[i].ParameterType;
                }
            }
            return array;
        }
References System.array, System.Reflection.MethodBase.GetParameters(), System.Type.GetType(), and System.Reflection.ParameterInfo.ParameterType.
Referenced by System.Runtime.Remoting.Messaging.CADMethodReturnMessage.CADMethodReturnMessage().