Terraria Decompiled: System.Runtime.Remoting.Messaging.CADMessageBase.IsPossibleToIgnoreMarshal
IsPossibleToIgnoreMarshal()
static bool System.Runtime.Remoting.Messaging.CADMessageBase.IsPossibleToIgnoreMarshal (object obj) inline static private
Definition at line 103 of file CADMessageBase.cs.
        {
            Type type = obj.GetType();
            return type.IsPrimitive || type == typeof(void) || (type.IsArray && type.GetElementType().IsPrimitive && ((Array)obj).Rank == 1) || (obj is string || obj is DateTime || obj is TimeSpan);
        }
References System.Reflection.Array, System.Type.GetElementType(), System.Type.GetType(), System.Type.IsPrimitive, and System.obj.
Referenced by System.Runtime.Remoting.Messaging.CADMessageBase.MarshalArgument().