Terraria Decompiled: Terraria.Social.Base.AWorkshopEntry.CreateHeaderJson
CreateHeaderJson()
static string Terraria.Social.Base.AWorkshopEntry.CreateHeaderJson (string contentTypeName, ulong workshopEntryId, string[] tags, WorkshopItemPublicSettingId publicity, string previewImagePath) inline static protected
Definition at line 24 of file AWorkshopEntry.cs.
        {
            new JObject();
            Dictionary<string, object> dictionary = new Dictionary<string, object>();
            dictionary["WorkshopPublishedVersion"] = 1;
            dictionary["ContentType"] = contentTypeName;
            dictionary["SteamEntryId"] = workshopEntryId;
            if (tags != null && tags.Length != 0)
            {
                dictionary["Tags"] = JArray.FromObject(tags);
            }
            dictionary["Publicity"] = publicity;
            return JsonConvert.SerializeObject(dictionary, AWorkshopEntry.SerializerSettings);
        }
References System.dictionary, Newtonsoft.Json.Linq.JArray.FromObject(), Newtonsoft.Json.JsonConvert.SerializeObject(), and Terraria.Social.Base.AWorkshopEntry.SerializerSettings.
Referenced by Terraria.Social.Base.TexturePackWorkshopEntry.GetHeaderTextFor(), and Terraria.Social.Base.WorldWorkshopEntry.GetHeaderTextFor().