Terraria Decompiled: System.Runtime.Remoting.Messaging.CADMessageBase.MarshalProperties
MarshalProperties()
static int System.Runtime.Remoting.Messaging.CADMessageBase.MarshalProperties (IDictionary dict, ref ArrayList args) inline static package
Definition at line 45 of file CADMessageBase.cs.
        {
            int num = 0;
            MessageDictionary messageDictionary = dict as MessageDictionary;
            if (messageDictionary != null)
            {
                if (!messageDictionary.HasUserData())
                {
                    return num;
                }
                IDictionary internalDictionary = messageDictionary.InternalDictionary;
                if (internalDictionary == null)
                {
                    return num;
                }
                using (IDictionaryEnumerator dictionaryEnumerator = internalDictionary.GetEnumerator())
                {
                    while (dictionaryEnumerator.MoveNext())
                    {
                        object obj = dictionaryEnumerator.Current;
                        DictionaryEntry dictionaryEntry = (DictionaryEntry)obj;
                        if (args == null)
{
                            args = new ArrayList();
                        }
                        args.Add(dictionaryEntry);
                        num++;
                    }
                    return num;
                }
            }
            if (dict != null)
            {
                foreach (object obj2 in dict)
                {
                    DictionaryEntry dictionaryEntry2 = (DictionaryEntry)obj2;
                    if (args == null)
                    {
                        args = new ArrayList();
                    }
                    args.Add(dictionaryEntry2);
                    num++;
                }
            }
            return num;
        }
References System.Collections.IEnumerator.Current, System.Collections.IDictionary.GetEnumerator(), System.Runtime.Remoting.Messaging.MessageDictionary.HasUserData(), System.Runtime.Remoting.Messaging.MessageDictionary.InternalDictionary, System.Collections.IEnumerator.MoveNext(), and System.obj.
Referenced by System.Runtime.Remoting.Messaging.CADMethodCallMessage.CADMethodCallMessage(), and System.Runtime.Remoting.Messaging.CADMethodReturnMessage.CADMethodReturnMessage().