Terraria Decompiled: System.Security.AccessControl.CommonAcl.AddAce
AddAce() [3/3]
void System.Security.AccessControl.CommonAcl.AddAce (QualifiedAce newAce) inline private
Definition at line 470 of file CommonAcl.cs.
        {
            this.RequireCanonicity();
            int aceInsertPosition = this.GetAceInsertPosition(newAce.AceQualifier);
            this.raw_acl.InsertAce(aceInsertPosition, CommonAcl.CopyAce(newAce));
            this.CanonicalizeAndClearAefa();
        }
References System.Security.AccessControl.QualifiedAce.AceQualifier, System.Security.AccessControl.CommonAcl.CanonicalizeAndClearAefa(), System.Security.AccessControl.CommonAcl.CopyAce(), System.Security.AccessControl.CommonAcl.GetAceInsertPosition(), System.Security.AccessControl.RawAcl.InsertAce(), System.Security.AccessControl.CommonAcl.raw_acl, and System.Security.AccessControl.CommonAcl.RequireCanonicity().