Terraria Decompiled: System.Security.AccessControl.CommonAcl.CanonicalizeAndClearAefa
CanonicalizeAndClearAefa()
void System.Security.AccessControl.CommonAcl.CanonicalizeAndClearAefa () inline package
Definition at line 165 of file CommonAcl.cs.
        {
            this.RemoveAces<GenericAce>(new CommonAcl.RemoveAcesCallback<GenericAce>(this.IsAceMeaningless));
            this.is_canonical = this.TestCanonicity();
            if (this.IsCanonical)
            {
                this.ApplyCanonicalSortToExplicitAces();
                this.MergeExplicitAces();
            }
            this.IsAefa = false;
        }
References System.Security.AccessControl.CommonAcl.ApplyCanonicalSortToExplicitAces(), System.Security.AccessControl.CommonAcl.IsCanonical, System.Security.AccessControl.CommonAcl.MergeExplicitAces(), and System.Security.AccessControl.CommonAcl.TestCanonicity().
Referenced by System.Security.AccessControl.CommonAcl.AddAce(), System.Security.AccessControl.CommonAcl.Init(), System.Security.AccessControl.CommonAcl.RemoveAceSpecific(), System.Security.AccessControl.CommonAcl.RemoveAceSpecific(), and System.Security.AccessControl.CommonAcl.SetAce().