Terraria Decompiled: System.Security.AccessControl.CommonAcl.MergeExplicitAcePair
MergeExplicitAcePair()
GenericAce System.Security.AccessControl.CommonAcl.MergeExplicitAcePair (GenericAce ace1, GenericAce ace2) inline private
Definition at line 300 of file CommonAcl.cs.
        {
            QualifiedAce qualifiedAce = ace1 as QualifiedAce;
            QualifiedAce qualifiedAce2 = ace2 as QualifiedAce;
            if (!(null != qualifiedAce) || !(null != qualifiedAce2))
            {
                return null;
            }
            if (qualifiedAce.AceQualifier != qualifiedAce2.AceQualifier)
            {
                return null;
            }
            if (!(qualifiedAce.SecurityIdentifier == qualifiedAce2.SecurityIdentifier))
            {
                return null;
            }
            AceFlags aceFlags = qualifiedAce.AceFlags;
            AceFlags aceFlags2 = qualifiedAce2.AceFlags;
            int accessMask = qualifiedAce.AccessMask;
            int accessMask2 = qualifiedAce2.AccessMask;
            if (!this.IsContainer)
            {
                aceFlags &= ~(AceFlags.ObjectInherit | AceFlags.ContainerInherit | AceFlags.NoPropagateInherit | AceFlags.InheritOnly);
                aceFlags2 &= ~(AceFlags.ObjectInherit | AceFlags.ContainerInherit | AceFlags.NoPropagateInherit | AceFlags.InheritOnly);
            }
            AceFlags aceFlags3;
            int num;
            if (aceFlags != aceFlags2)
            {
                if (accessMask != accessMask2)
                {
                    return null;
                }
                if ((aceFlags & ~(AceFlags.ObjectInherit | AceFlags.ContainerInherit)) == (aceFlags2 & ~(AceFlags.ObjectInherit | AceFlags.ContainerInherit)))
                {
                    aceFlags3 = aceFlags | aceFlags2;
                    num = accessMask;
                }
                else
                {
                    if ((aceFlags & ~(AceFlags.SuccessfulAccess | AceFlags.FailedAccess)) != (aceFlags2 & ~(AceFlags.SuccessfulAccess | AceFlags.FailedAccess)))
                    {
                        return null;
                    }
                    aceFlags3 = aceFlags | aceFlags2;
                    num = accessMask;
                }
            }
            else
            {
                aceFlags3 = aceFlags;
                num = accessMask | accessMask2;
            }
            CommonAce commonAce = ace1 as CommonAce;
            CommonAce commonAce2 = ace2 as CommonAce;
            if (null != commonAce && null != commonAce2)
            {
                return new CommonAce(aceFlags3, commonAce.AceQualifier, num, commonAce.SecurityIdentifier, commonAce.IsCallback, commonAce.GetOpaque());
            }
            ObjectAce objectAce = ace1 as ObjectAce;
            ObjectAce objectAce2 = ace2 as ObjectAce;
            if (null != objectAce && null != objectAce2)
            {
                Guid guid;
                Guid guid2;
                CommonAcl.GetObjectAceTypeGuids(objectAce, out guid, out guid2);
                Guid guid3;
                Guid guid4;
                CommonAcl.GetObjectAceTypeGuids(objectAce2, out guid3, out guid4);
                if (guid == guid3 && guid2 == guid4)
                {
                    return new ObjectAce(aceFlags3, objectAce.AceQualifier, num, objectAce.SecurityIdentifier, objectAce.ObjectAceFlags, objectAce.ObjectAceType, objectAce.InheritedObjectAceType, objectAce.IsCallback, objectAce.GetOpaque());
                }
            }
            return null;
        }
References System.Security.AccessControl.KnownAce.AccessMask, System.Security.AccessControl.GenericAce.AceFlags, System.Security.AccessControl.QualifiedAce.AceQualifier, System.Security.AccessControl.CommonAcl.GetObjectAceTypeGuids(), System.Security.AccessControl.QualifiedAce.GetOpaque(), System.Security.AccessControl.ObjectAce.InheritedObjectAceType, System.Security.AccessControl.QualifiedAce.IsCallback, System.Security.AccessControl.CommonAcl.IsContainer, System.Security.AccessControl.ObjectAce.ObjectAceFlags, System.Security.AccessControl.ObjectAce.ObjectAceType, and System.Security.AccessControl.KnownAce.SecurityIdentifier.
Referenced by System.Security.AccessControl.CommonAcl.MergeExplicitAces().