Terraria Decompiled: System.Security.AccessControl.CommonAcl.MergeExplicitAces
MergeExplicitAces()
void System.Security.AccessControl.CommonAcl.MergeExplicitAces () inline private
Definition at line 279 of file CommonAcl.cs.
        {
            int num = this.GetCanonicalExplicitAceCount();
            int i = 0;
            while (i < num - 1)
            {
                GenericAce genericAce = this.MergeExplicitAcePair(this.raw_acl[i], this.raw_acl[i + 1]);
                if (null != genericAce)
                {
                    this.raw_acl[i] = genericAce;
                    this.raw_acl.RemoveAce(i + 1);
                    num--;
                }
                else
                {
                    i++;
                }
            }
        }
References System.Security.AccessControl.CommonAcl.GetCanonicalExplicitAceCount(), System.Security.AccessControl.CommonAcl.MergeExplicitAcePair(), System.Security.AccessControl.CommonAcl.raw_acl, and System.Security.AccessControl.RawAcl.RemoveAce().
Referenced by System.Security.AccessControl.CommonAcl.CanonicalizeAndClearAefa().