Terraria Decompiled: Terraria.GameContent.ItemDropRules.DropRateInfoChainFeed.With
With()
DropRateInfoChainFeed Terraria.GameContent.ItemDropRules.DropRateInfoChainFeed.With (float multiplier) inline
Definition at line 27 of file DropRateInfoChainFeed.cs.
        {
            DropRateInfoChainFeed dropRateInfoChainFeed = new DropRateInfoChainFeed(this.parentDroprateChance * multiplier);
            if (this.conditions != null)
            {
                dropRateInfoChainFeed.conditions = new List<IItemDropRuleCondition>(this.conditions);
            }
            return dropRateInfoChainFeed;
        }
References Terraria.GameContent.ItemDropRules.DropRateInfoChainFeed.conditions, Terraria.GameContent.ItemDropRules.DropRateInfoChainFeed.DropRateInfoChainFeed(), and Terraria.GameContent.ItemDropRules.DropRateInfoChainFeed.parentDroprateChance.
Referenced by Terraria.GameContent.ItemDropRules.Chains.TryIfFailedRandomRoll.ReportDroprates(), Terraria.GameContent.ItemDropRules.Chains.TryIfSucceeded.ReportDroprates(), Terraria.GameContent.ItemDropRules.Chains.TryIfDoesntFillConditions.ReportDroprates(), Terraria.GameContent.ItemDropRules.DropBasedOnExpertMode.ReportDroprates(), Terraria.GameContent.ItemDropRules.DropBasedOnExtraGel.ReportDroprates(), Terraria.GameContent.ItemDropRules.DropBasedOnMasterAndExpertMode.ReportDroprates(), Terraria.GameContent.ItemDropRules.DropBasedOnMasterMode.ReportDroprates(), Terraria.GameContent.ItemDropRules.ItemDropWithConditionRule.ReportDroprates(), and Terraria.GameContent.ItemDropRules.OneFromRulesRule.ReportDroprates().