Terraria Decompiled: System.Security.Cryptography.X509Certificates.X509Helper.Import
Import() [1/2]
static X509CertificateImpl System.Security.Cryptography.X509Certificates.X509Helper.Import (byte[] rawData) inline static
Definition at line 59 of file X509Helper.cs.
        {
            return X509Helper.CertificateProvider.Import(rawData, CertificateImportFlags.None);
        }
References System.Security.Cryptography.X509Certificates.X509Helper.CertificateProvider, and Mono.ISystemCertificateProvider.Import().
Referenced by System.Security.Cryptography.X509Certificates.X509Certificate.X509Certificate(), System.Security.Cryptography.X509Certificates.X509Certificate.X509Certificate(), System.Security.Cryptography.X509Certificates.X509Certificate.X509Certificate(), System.Security.Cryptography.X509Certificates.X509Certificate.X509Certificate(), and System.Security.Cryptography.X509Certificates.X509Certificate.X509Certificate().