Terraria Decompiled: System.Security.PermissionSet.ToString
ToString()
override string System.Security.PermissionSet.ToString () inline
Definition at line 551 of file PermissionSet.cs.
        {
            return this.ToXml().ToString();
        }
References System.Security.SecurityElement.ToString(), and System.Security.PermissionSet.ToXml().
Referenced by System.Security.PermissionSet.ConvertPermissionSet(), System.Security.SecurityException.SecurityException(), System.Security.SecurityException.SecurityException(), and System.Security.PermissionSet.ToXml().