Terraria Decompiled: System.Security.PermissionSet.Equals
Equals()
override bool System.Security.PermissionSet.Equals (object obj) inline
Definition at line 658 of file PermissionSet.cs.
        {
            if (obj == null)
            {
                return false;
            }
            PermissionSet permissionSet = obj as PermissionSet;
            if (permissionSet == null)
            {
                return false;
            }
            if (this.state != permissionSet.state)
            {
                return false;
            }
            if (this.list.Count != permissionSet.Count)
            {
                return false;
            }
            for (int i = 0; i < this.list.Count; i++)
            {
                bool flag = false;
                int num = 0;
                while (i < permissionSet.list.Count)
                {
                    if (this.list[i].Equals(permissionSet.list[num]))
                    {
                        flag = true;
                        break;
                    }
                    num++;
                }
                if (!flag)
                {
                    return false;
                }
            }
            return true;
        }
References System.Collections.ArrayList.Count, System.Security.PermissionSet.Count, System.Security.PermissionSet.Equals(), System.Security.PermissionSet.list, System.obj, System.Security.PermissionSet.PermissionSet(), and System.Security.PermissionSet.state.
Referenced by System.Security.PermissionSet.Equals(), and System.Security.Policy.PolicyStatement.Equals().