Terraria Decompiled: System.Security.PermissionSet.IsSubsetOf
IsSubsetOf()
bool System.Security.PermissionSet.IsSubsetOf (PermissionSet target) inline
Definition at line 256 of file PermissionSet.cs.
        {
            if (target == null || target.IsEmpty())
            {
                return this.IsEmpty();
            }
            if (target.IsUnrestricted())
            {
                return true;
            }
            if (this.IsUnrestricted())
            {
                return false;
            }
            if (this.IsUnrestricted() && (target == null || !target.IsUnrestricted()))
            {
                return false;
            }
            foreach (object obj in this.list)
            {
                IPermission permission = (IPermission)obj;
                Type type = permission.GetType();
                IPermission permission2;
                if (target.IsUnrestricted() && permission is CodeAccessPermission && permission is IUnrestrictedPermission)
                {
                    permission2 = (IPermission)Activator.CreateInstance(type, PermissionSet.psUnrestricted);
                }
                else
                {
                    permission2 = target.GetPermission(type);
                }
                if (!permission.IsSubsetOf(permission2))
                {
                    return false;
                }
            }
            return true;
        }
References System.Activator.CreateInstance(), System.Security.PermissionSet.IsEmpty(), System.Security.IPermission.IsSubsetOf(), System.Security.PermissionSet.IsUnrestricted(), System.Security.PermissionSet.list, System.obj, and System.Security.PermissionSet.psUnrestricted.
Referenced by System.Security.SecurityManager.ResolvePolicy().