Terraria Decompiled: CsvHelper.ExceptionHelper.AddExceptionDataMessage
AddExceptionDataMessage()
static void CsvHelper.ExceptionHelper.AddExceptionDataMessage (Exception exception, ICsvParser parser, Type type, Dictionary< string, List< int > > namedIndexes, int? currentIndex, string[] currentRecord) inline static
Definition at line 13 of file ExceptionHelper.cs.
        {
            try
            {
                exception.Data["CsvHelper"] = ExceptionHelper.GetErrorMessage(parser, type, namedIndexes, currentIndex, currentRecord);
            }
            catch (Exception ex)
            {
                StringBuilder stringBuilder = new StringBuilder();
                stringBuilder.AppendLine("An error occurred while creating exception details.");
                stringBuilder.AppendLine();
                stringBuilder.AppendLine(ex.ToString());
                exception.Data["CsvHelper"] = stringBuilder.ToString();
            }
        }
References System.Text.StringBuilder.AppendLine(), System.exception, CsvHelper.ExceptionHelper.GetErrorMessage(), System.Exception.ToString(), and System.Text.StringBuilder.ToString().
Referenced by CsvHelper.CsvReader.GetField(), CsvHelper.CsvReader.GetField< T >(), CsvHelper.CsvReader.GetFieldIndex(), CsvHelper.CsvReader.GetRecord(), CsvHelper.CsvReader.GetRecord< T >(), CsvHelper.CsvReader.GetRecords(), CsvHelper.CsvReader.GetRecords< T >(), CsvHelper.CsvParser.Read(), CsvHelper.CsvWriter.WriteRecord(), CsvHelper.CsvWriter.WriteRecord< T >(), and CsvHelper.CsvWriter.WriteRecords().