Terraria Decompiled: System.Security.PermissionSet.ProcessAttribute
ProcessAttribute()
static IPermission System.Security.PermissionSet.ProcessAttribute (byte[] data, ref int position) inline static package
Definition at line 798 of file PermissionSet.cs.
        {
            int num = PermissionSet.ReadEncodedInt(data, ref position);
            string @string = Encoding.UTF8.GetString(data, position, num);
            position += num;
            Type type = Type.GetType(@string);
            SecurityAttribute securityAttribute = Activator.CreateInstance(type, PermissionSet.action) as SecurityAttribute;
            if (securityAttribute == null)
            {
                return null;
            }
            PermissionSet.ReadEncodedInt(data, ref position);
            int num2 = PermissionSet.ReadEncodedInt(data, ref position);
            for (int i = 0; i < num2; i++)
            {
                int num3 = position;
                position = num3 + 1;
                byte b = data[num3];
                bool flag;
                if (b != 83)
                {
                    if (b != 84)
                    {
                        return null;
                    }
                    flag = true;
                }
                else
                {
                    flag = false;
                }
                bool flag2 = false;
                num3 = position;
                position = num3 + 1;
                byte b2 = data[num3];
                if (b2 == 29)
                {
                    flag2 = true;
                    num3 = position;
                    position = num3 + 1;
                    b2 = data[num3];
                }
                int num4 = PermissionSet.ReadEncodedInt(data, ref position);
                string string2 = Encoding.UTF8.GetString(data, position, num4);
                position += num4;
                int num5 = 1;
                if (flag2)
                {
                    num5 = BitConverter.ToInt32(data, position);
                    position += 4;
                }
                object[] array = null;
                for (int j = 0; j < num5; j++)
                {
                    object obj;
                    switch (b2)
                    {
                    case 2:
                        num3 = position;
                        position = num3 + 1;
                        obj = Convert.ToBoolean(data[num3]);
                        break;
                    case 3:
                        obj = Convert.ToChar(data[position]);
                        position += 2;
                        break;
                    case 4:
                        num3 = position;
                        position = num3 + 1;
                        obj = Convert.ToSByte(data[num3]);
                        break;
                    case 5:
                        num3 = position;
                        position = num3 + 1;
                        obj = Convert.ToByte(data[num3]);
                        break;
                    case 6:
                        obj = Convert.ToInt16(data[position]);
                        position += 2;
                        break;
                    case 7:
                        obj = Convert.ToUInt16(data[position]);
                        position += 2;
                        break;
                    case 8:
                        obj = Convert.ToInt32(data[position]);
                        position += 4;
                        break;
                    case 9:
                        obj = Convert.ToUInt32(data[position]);
                        position += 4;
                        break;
                    case 10:
                        obj = Convert.ToInt64(data[position]);
                        position += 8;
                        break;
                    case 11:
                        obj = Convert.ToUInt64(data[position]);
                        position += 8;
                        break;
                    case 12:
                        obj = Convert.ToSingle(data[position]);
                        position += 4;
                        break;
                    case 13:
                        obj = Convert.ToDouble(data[position]);
                        position += 8;
                        break;
                    case 14:
                    {
                        string text = null;
                        if (data[position] != 255)
{
                            int num6 = PermissionSet.ReadEncodedInt(data, ref position);
                            text = Encoding.UTF8.GetString(data, position, num6);
                            position += num6;
                        }
                        else
{
                            position++;
                        }
                        obj = text;
                        break;
                    }
                    default:
                    {
                        if (b2 != 80)
{
                            return null;
                        }
                        int num7 = PermissionSet.ReadEncodedInt(data, ref position);
                        obj = Type.GetType(Encoding.UTF8.GetString(data, position, num7));
                        position += num7;
                        break;
                    }
                    }
                    if (flag)
                    {
                        type.GetProperty(string2).SetValue(securityAttribute, obj, array);
                    }
                    else
                    {
                        type.GetField(string2).SetValue(securityAttribute, obj);
                    }
                }
            }
            return securityAttribute.CreatePermission();
        }
References System.Security.PermissionSet.action, System.array, System.Activator.CreateInstance(), System.Security.Permissions.SecurityAttribute.CreatePermission(), System.Type.GetField(), System.Type.GetProperty(), System.Text.Encoding.GetString(), System.Type.GetType(), System.obj, System.Security.PermissionSet.ReadEncodedInt(), System.text, System.Convert.ToBoolean(), System.Convert.ToByte(), System.Convert.ToChar(), System.Convert.ToDouble(), System.Convert.ToInt16(), System.BitConverter.ToInt32(), System.Convert.ToInt32(), System.Convert.ToInt64(), System.Convert.ToSByte(), System.Convert.ToSingle(), System.Convert.ToUInt16(), System.Convert.ToUInt32(), System.Convert.ToUInt64(), and System.Text.Encoding.UTF8.
Referenced by System.Security.PermissionSet.CreateFromBinaryFormat().