Terraria Decompiled: System.Security.PermissionSet.IsEmpty
IsEmpty()
bool System.Security.PermissionSet.IsEmpty () inline
Definition at line 482 of file PermissionSet.cs.
        {
            if (this.state == PermissionState.Unrestricted)
            {
                return false;
            }
            if (this.list == null || this.list.Count == 0)
            {
                return true;
            }
            using (IEnumerator enumerator = this.list.GetEnumerator())
            {
                while (enumerator.MoveNext())
                {
                    if (!((IPermission)enumerator.Current).IsSubsetOf(null))
                    {
                        return false;
                    }
                }
            }
            return true;
        }
References System.Collections.ArrayList.Count, System.Collections.IEnumerator.Current, System.Collections.ArrayList.GetEnumerator(), System.Security.PermissionSet.list, System.Collections.IEnumerator.MoveNext(), and System.Security.PermissionSet.state.
Referenced by System.Security.PermissionSet.Demand(), System.Security.PermissionSet.Intersect(), System.Security.SecurityManager.IsGranted(), and System.Security.PermissionSet.IsSubsetOf().