Terraria Decompiled: System.Security.PermissionSet.Demand
Demand()
void System.Security.PermissionSet.Demand () inline
Implements System.Security.IStackWalk.
Definition at line 151 of file PermissionSet.cs.
        {
            if (this.IsEmpty())
            {
                return;
            }
            int count = this.list.Count;
            if (this._ignored == null || this._ignored.Length != count)
            {
                this._ignored = new bool[count];
            }
            bool flag = this.IsUnrestricted();
            for (int i = 0; i < count; i++)
            {
                IPermission permission = (IPermission)this.list[i];
                if (permission.GetType().IsSubclassOf(typeof(CodeAccessPermission)))
                {
                    this._ignored[i] = false;
                    flag = true;
                }
                else
                {
                    this._ignored[i] = true;
                    permission.Demand();
                }
            }
            if (flag && SecurityManager.SecurityEnabled)
            {
                this.CasOnlyDemand(this._declsec ? 5 : 3);
            }
        }
References System.Security.PermissionSet._declsec, System.Security.PermissionSet._ignored, System.Security.PermissionSet.CasOnlyDemand(), System.Collections.ArrayList.Count, System.count, System.Security.IPermission.Demand(), System.Security.PermissionSet.IsEmpty(), System.Security.PermissionSet.IsUnrestricted(), System.Security.PermissionSet.list, and System.Security.SecurityManager.SecurityEnabled.