Terraria Decompiled: System.Security.PermissionSet.AddPermission
AddPermission()
IPermission System.Security.PermissionSet.AddPermission (IPermission perm) inline
Definition at line 71 of file PermissionSet.cs.
        {
            if (perm == null || this._readOnly)
            {
                return perm;
            }
            if (this.state == PermissionState.Unrestricted)
            {
                return (IPermission)Activator.CreateInstance(perm.GetType(), PermissionSet.psUnrestricted);
            }
            IPermission permission = this.RemovePermission(perm.GetType());
            if (permission != null)
            {
                perm = perm.Union(permission);
            }
            this.list.Add(perm);
            return perm;
        }
References System.Security.PermissionSet._readOnly, System.Collections.ArrayList.Add(), System.Activator.CreateInstance(), System.Security.PermissionSet.list, System.Security.PermissionSet.psUnrestricted, System.Security.PermissionSet.RemovePermission(), System.Security.PermissionSet.state, and System.Security.IPermission.Union().
Referenced by System.Security.Policy.DefaultPolicies.BuildEverything(), System.Security.Policy.DefaultPolicies.BuildExecution(), System.Security.Policy.DefaultPolicies.BuildInternet(), System.Security.Policy.DefaultPolicies.BuildLocalIntranet(), System.Security.Policy.DefaultPolicies.BuildSkipVerification(), System.Security.PermissionSet.CreateFromBinaryFormat(), and System.Security.SecurityManager.ResolveIdentityPermissions().