Terraria Decompiled: System.Security.PermissionSet.Union
Union()
PermissionSet System.Security.PermissionSet.Union (PermissionSet other) inline
Definition at line 575 of file PermissionSet.cs.
        {
            if (other == null)
            {
                return this.Copy();
            }
            PermissionSet permissionSet = null;
            if (this.IsUnrestricted() || other.IsUnrestricted())
            {
                return new PermissionSet(PermissionState.Unrestricted);
            }
            permissionSet = this.Copy();
            foreach (object obj in other.list)
            {
                IPermission permission = (IPermission)obj;
                permissionSet.AddPermission(permission);
            }
            return permissionSet;
        }
References System.Security.PermissionSet.Copy(), System.Security.PermissionSet.IsUnrestricted(), System.obj, and System.Security.PermissionSet.PermissionSet().
Referenced by System.Security.Policy.FileCodeGroup.Resolve(), System.Security.Policy.NetCodeGroup.Resolve(), and System.Security.Policy.UnionCodeGroup.Resolve().