Terraria Decompiled: CsvHelper.ExceptionHelper.GetErrorMessage
GetErrorMessage()
static string CsvHelper.ExceptionHelper.GetErrorMessage (ICsvParser parser, Type type, Dictionary< string, List< int > > namedIndexes, int? currentIndex, string[] currentRecord) inline static
Definition at line 30 of file ExceptionHelper.cs.
        {
            StringBuilder stringBuilder = new StringBuilder();
            if (parser != null)
            {
                stringBuilder.AppendFormat("Row: '{0}' (1 based)", parser.Row).AppendLine();
            }
            if (type != null)
            {
                stringBuilder.AppendFormat("Type: '{0}'", type.FullName).AppendLine();
            }
            if (currentIndex != null)
            {
                stringBuilder.AppendFormat("Field Index: '{0}' (0 based)", currentIndex).AppendLine();
            }
            if (namedIndexes != null)
            {
                string text = Enumerable.SingleOrDefault<string>(Enumerable.Select(Enumerable.Where(Enumerable.SelectMany(namedIndexes, (KeyValuePair<string, List<int>> pair) => pair.Value, (KeyValuePair<string, List<int>> pair, int index) => new { pair, index }), <>h__TransparentIdentifier0 => <>h__TransparentIdentifier0.index == currentIndex), <>h__TransparentIdentifier0 => <>h__TransparentIdentifier0.pair.Key));
                if (text != null)
                {
                    stringBuilder.AppendFormat("Field Name: '{0}'", text).AppendLine();
                }
            }
            if (currentRecord != null && currentIndex > -1 && currentIndex < currentRecord.Length && currentIndex.Value < currentRecord.Length)
            {
                string text2 = currentRecord[currentIndex.Value];
                stringBuilder.AppendFormat("Field Value: '{0}'", text2).AppendLine();
            }
            return stringBuilder.ToString();
        }
References System.Text.StringBuilder.AppendFormat(), System.Text.StringBuilder.AppendLine(), System.Type.FullName, System.index, CsvHelper.ICsvParser.Row, System.text, and System.Text.StringBuilder.ToString().
Referenced by CsvHelper.ExceptionHelper.AddExceptionDataMessage().