Terraria Decompiled: System.Security.PermissionSet.FromXml
FromXml()
virtual void System.Security.PermissionSet.FromXml (SecurityElement et) inline virtual
Implements System.Security.ISecurityEncodable.
Reimplemented in System.Security.NamedPermissionSet.
Definition at line 213 of file PermissionSet.cs.
        {
            if (et == null)
            {
                throw new ArgumentNullException("et");
            }
            if (et.Tag != "PermissionSet")
            {
                throw new ArgumentException(string.Format("Invalid tag {0} expected {1}", et.Tag, "PermissionSet"), "et");
            }
            this.list.Clear();
            if (CodeAccessPermission.IsUnrestricted(et))
            {
                this.state = PermissionState.Unrestricted;
                return;
            }
            this.state = PermissionState.None;
            if (et.Children != null)
            {
                foreach (object obj in et.Children)
                {
                    SecurityElement securityElement = (SecurityElement)obj;
                    string text = securityElement.Attribute("class");
                    if (text == null)
                    {
                        throw new ArgumentException(Locale.GetText("No permission class is specified."));
                    }
                    if (this.Resolver != null)
                    {
                        text = this.Resolver.ResolveClassName(text);
                    }
                    this.list.Add(PermissionBuilder.Create(text, securityElement));
                }
            }
        }
References System.Collections.ArrayList.Add(), System.Security.SecurityElement.Attribute(), System.Security.SecurityElement.Children, System.Collections.ArrayList.Clear(), System.Security.PermissionBuilder.Create(), System.Security.Format, Locale.GetText(), System.Security.CodeAccessPermission.IsUnrestricted(), System.Security.PermissionSet.list, System.obj, System.Security.Policy.PolicyLevel.ResolveClassName(), System.Security.PermissionSet.Resolver, System.Security.SecurityElement.Tag, and System.text.
Referenced by System.Security.PermissionSet.ConvertPermissionSet(), System.Security.Permissions.PermissionSetAttribute.CreateFromXml(), System.Security.Policy.CodeGroup.FromXml(), System.Security.Policy.PolicyStatement.FromXml(), and System.Security.PermissionSet.PermissionSet().