Terraria Decompiled: System.Security.PermissionSet.ToXml
ToXml()
virtual SecurityElement System.Security.PermissionSet.ToXml () inline virtual
Implements System.Security.ISecurityEncodable.
Reimplemented in System.Security.NamedPermissionSet.
Definition at line 557 of file PermissionSet.cs.
        {
            SecurityElement securityElement = new SecurityElement("PermissionSet");
            securityElement.AddAttribute("class", base.GetType().FullName);
            securityElement.AddAttribute("version", 1.ToString());
            if (this.state == PermissionState.Unrestricted)
            {
                securityElement.AddAttribute("Unrestricted", "true");
            }
            foreach (object obj in this.list)
            {
                IPermission permission = (IPermission)obj;
                securityElement.AddChild(permission.ToXml());
            }
            return securityElement;
        }
References System.Security.SecurityElement.AddAttribute(), System.Security.PermissionSet.list, System.obj, System.Security.PermissionSet.state, System.Security.PermissionSet.ToString(), and System.Security.ISecurityEncodable.ToXml().
Referenced by System.Reflection.Emit.ConstructorBuilder.AddDeclarativeSecurity(), System.Reflection.Emit.MethodBuilder.AddDeclarativeSecurity(), System.Reflection.Emit.TypeBuilder.AddDeclarativeSecurity(), System.Reflection.Emit.AssemblyBuilder.AddPermissionRequests(), System.Security.Policy.PermissionRequestEvidence.GetRequiredSize(), System.Security.PermissionSet.ToString(), System.Security.Policy.PermissionRequestEvidence.ToString(), System.Security.Policy.CodeGroup.ToXml(), and System.Security.Policy.PolicyStatement.ToXml().