Terraria Decompiled: System.Globalization.TimeSpanFormat.FormatCustomized
FormatCustomized()
static unsafe StringBuilder System.Globalization.TimeSpanFormat.FormatCustomized (TimeSpan value, ReadOnlySpan< char > format, DateTimeFormatInfo dtfi, StringBuilder result) inline static private
Definition at line 160 of file TimeSpanFormat.cs.
        {
            bool flag = false;
            if (result == null)
            {
                result = StringBuilderCache.Acquire(16);
                flag = true;
            }
            int num = (int)(value.Ticks / 864000000000L);
            long num2 = value.Ticks % 864000000000L;
            if (value.Ticks < 0L)
            {
                num = -num;
                num2 = -num2;
            }
            int num3 = (int)(num2 / 36000000000L % 24L);
            int num4 = (int)(num2 / 600000000L % 60L);
            int num5 = (int)(num2 / 10000000L % 60L);
            int num6 = (int)(num2 % 10000000L);
            int i = 0;
            while (i < format.Length)
            {
                char c = (char)(*format[i]);
                int num8;
                if (c <= 'F')
                {
                    if (c <= '%')
                    {
                        if (c != '"')
{
                            if (c != '%')
{
                                goto IL_02B5;
                            }
                            int num7 = DateTimeFormat.ParseNextChar(format, i);
                            if (num7 >= 0 && num7 != 37)
{
                                char c2 = (char)num7;
                                ReadOnlySpan<char> readOnlySpan = new ReadOnlySpan<char>((void*)(&c2), 1);
                                TimeSpanFormat.FormatCustomized(value, readOnlySpan, dtfi, result);
                                num8 = 2;
                                goto IL_02C9;
                            }
                            goto IL_02B5;
                        }
                    }
                    else if (c != '\'')
                    {
                        if (c != 'F')
{
                            goto IL_02B5;
                        }
                        num8 = DateTimeFormat.ParseRepeatPattern(format, i, c);
                        if (num8 > 7)
{
                            goto IL_02B5;
                        }
                        long num9 = (long)num6;
                        num9 /= TimeSpanParse.Pow10(7 - num8);
                        int num10 = num8;
                        while (num10 > 0 && num9 % 10L == 0L)
{
                            num9 /= 10L;
                            num10--;
                        }
                        if (num10 > 0)
{
                            result.Append(num9.ToString(DateTimeFormat.fixedNumberFormats[num10 - 1], CultureInfo.InvariantCulture));
                            goto IL_02C9;
                        }
                        goto IL_02C9;
                    }
                    num8 = DateTimeFormat.ParseQuoteString(format, i, result);
                }
                else if (c <= 'h')
                {
                    if (c != '\\')
                    {
                        switch (c)
{
                        case 'd':
                            num8 = DateTimeFormat.ParseRepeatPattern(format, i, c);
                            if (num8 > 8)
{
                                goto IL_02B5;
                            }
                            DateTimeFormat.FormatDigits(result, num, num8, true);
                            break;
                        case 'e':
                        case 'g':
                            goto IL_02B5;
                        case 'f':
{
                            num8 = DateTimeFormat.ParseRepeatPattern(format, i, c);
                            if (num8 > 7)
{
                                goto IL_02B5;
                            }
                            long num9 = (long)num6;
                            result.Append((num9 / TimeSpanParse.Pow10(7 - num8)).ToString(DateTimeFormat.fixedNumberFormats[num8 - 1], CultureInfo.InvariantCulture));
                            break;
                        }
                        case 'h':
                            num8 = DateTimeFormat.ParseRepeatPattern(format, i, c);
                            if (num8 > 2)
{
                                goto IL_02B5;
                            }
                            DateTimeFormat.FormatDigits(result, num3, num8);
                            break;
                        default:
                            goto IL_02B5;
                        }
                    }
                    else
                    {
                        int num7 = DateTimeFormat.ParseNextChar(format, i);
                        if (num7 < 0)
{
                            goto IL_02B5;
                        }
                        result.Append((char)num7);
                        num8 = 2;
                    }
                }
                else if (c != 'm')
                {
                    if (c != 's')
                    {
                        goto IL_02B5;
                    }
                    num8 = DateTimeFormat.ParseRepeatPattern(format, i, c);
                    if (num8 > 2)
                    {
                        goto IL_02B5;
                    }
                    DateTimeFormat.FormatDigits(result, num5, num8);
                }
                else
                {
                    num8 = DateTimeFormat.ParseRepeatPattern(format, i, c);
                    if (num8 > 2)
                    {
                        goto IL_02B5;
                    }
                    DateTimeFormat.FormatDigits(result, num4, num8);
                }
                IL_02C9:
                i += num8;
                continue;
                IL_02B5:
                if (flag)
                {
                    StringBuilderCache.Release(result);
                }
                throw new FormatException("Input string was not in a correct format.");
            }
            return result;
        }
References System.Text.StringBuilderCache.Acquire(), System.Text.StringBuilder.Append(), System.DateTimeFormat.fixedNumberFormats, System.format, System.Globalization.TimeSpanFormat.FormatCustomized(), System.DateTimeFormat.FormatDigits(), int, System.Globalization.CultureInfo.InvariantCulture, System.L, long, System.DateTimeFormat.ParseNextChar(), System.DateTimeFormat.ParseQuoteString(), System.DateTimeFormat.ParseRepeatPattern(), System.Globalization.TimeSpanParse.Pow10(), System.Text.StringBuilderCache.Release(), System.ToString, and System.value.
Referenced by System.Globalization.TimeSpanFormat.FormatCustomized(), and System.Globalization.TimeSpanFormat.FormatToBuilder().