Terraria Decompiled: System.Globalization.TimeSpanFormat.FormatToBuilder
FormatToBuilder()
static unsafe StringBuilder System.Globalization.TimeSpanFormat.FormatToBuilder (TimeSpan value, ReadOnlySpan< char > format, IFormatProvider formatProvider) inline static private
Definition at line 55 of file TimeSpanFormat.cs.
        {
            if (format.Length == 0)
            {
                format = "c";
            }
            if (format.Length == 1)
            {
                char c = (char)(*format[0]);
                if (c <= 'T')
                {
                    if (c == 'G')
                    {
                        goto IL_0053;
                    }
                    if (c != 'T')
                    {
                        goto IL_0089;
                    }
                }
                else if (c != 'c')
                {
                    if (c == 'g')
                    {
                        goto IL_0053;
                    }
                    if (c != 't')
                    {
                        goto IL_0089;
                    }
                }
                return TimeSpanFormat.FormatStandard(value, true, format, TimeSpanFormat.Pattern.Minimum);
                IL_0053:
                DateTimeFormatInfo instance = DateTimeFormatInfo.GetInstance(formatProvider);
                return TimeSpanFormat.FormatStandard(value, false, (value.Ticks < 0L) ? instance.FullTimeSpanNegativePattern : instance.FullTimeSpanPositivePattern, (c == 'g') ? TimeSpanFormat.Pattern.Minimum : TimeSpanFormat.Pattern.Full);
                IL_0089:
                throw new FormatException("Input string was not in a correct format.");
            }
            return TimeSpanFormat.FormatCustomized(value, format, DateTimeFormatInfo.GetInstance(formatProvider), null);
        }
References System.format, System.Globalization.TimeSpanFormat.FormatCustomized(), System.Globalization.TimeSpanFormat.FormatStandard(), System.Globalization.DateTimeFormatInfo.GetInstance(), System.L, and System.value.
Referenced by System.Globalization.TimeSpanFormat.Format(), and System.Globalization.TimeSpanFormat.TryFormat().