Terraria Decompiled: System.Globalization.TimeSpanFormat.FormatStandard
FormatStandard()
static StringBuilder System.Globalization.TimeSpanFormat.FormatStandard (TimeSpan value, bool isInvariant, ReadOnlySpan< char > format, TimeSpanFormat::Pattern pattern) inline static private
Definition at line 97 of file TimeSpanFormat.cs.
        {
            StringBuilder stringBuilder = StringBuilderCache.Acquire(16);
            int num = (int)(value.Ticks / 864000000000L);
            long num2 = value.Ticks % 864000000000L;
            if (value.Ticks < 0L)
            {
                num = -num;
                num2 = -num2;
            }
            int num3 = (int)(num2 / 36000000000L % 24L);
            int num4 = (int)(num2 / 600000000L % 60L);
            int num5 = (int)(num2 / 10000000L % 60L);
            int num6 = (int)(num2 % 10000000L);
            TimeSpanFormat.FormatLiterals formatLiterals;
            if (isInvariant)
            {
                formatLiterals = ((value.Ticks < 0L) ? TimeSpanFormat.NegativeInvariantFormatLiterals : TimeSpanFormat.PositiveInvariantFormatLiterals);
            }
            else
            {
                formatLiterals = default(TimeSpanFormat.FormatLiterals);
                formatLiterals.Init(format, pattern == TimeSpanFormat.Pattern.Full);
            }
            if (num6 != 0)
            {
                num6 = (int)((long)num6 / TimeSpanParse.Pow10(7 - formatLiterals.ff));
            }
            stringBuilder.Append(formatLiterals.Start);
            if (pattern == TimeSpanFormat.Pattern.Full || num != 0)
            {
                stringBuilder.Append(num);
                stringBuilder.Append(formatLiterals.DayHourSep);
            }
            TimeSpanFormat.AppendNonNegativeInt32(stringBuilder, num3, formatLiterals.hh);
            stringBuilder.Append(formatLiterals.HourMinuteSep);
            TimeSpanFormat.AppendNonNegativeInt32(stringBuilder, num4, formatLiterals.mm);
            stringBuilder.Append(formatLiterals.MinuteSecondSep);
            TimeSpanFormat.AppendNonNegativeInt32(stringBuilder, num5, formatLiterals.ss);
            if (!isInvariant && pattern == TimeSpanFormat.Pattern.Minimum)
            {
                int num7 = formatLiterals.ff;
                while (num7 > 0 && num6 % 10 == 0)
                {
                    num6 /= 10;
                    num7--;
                }
                if (num7 > 0)
                {
                    stringBuilder.Append(formatLiterals.SecondFractionSep);
                    stringBuilder.Append(num6.ToString(DateTimeFormat.fixedNumberFormats[num7 - 1], CultureInfo.InvariantCulture));
                }
            }
            else if (pattern == TimeSpanFormat.Pattern.Full || num6 != 0)
            {
                stringBuilder.Append(formatLiterals.SecondFractionSep);
                TimeSpanFormat.AppendNonNegativeInt32(stringBuilder, num6, formatLiterals.ff);
            }
            stringBuilder.Append(formatLiterals.End);
            return stringBuilder;
        }
References System.Text.StringBuilderCache.Acquire(), System.Text.StringBuilder.Append(), System.Globalization.TimeSpanFormat.AppendNonNegativeInt32(), System.Globalization.TimeSpanFormat.FormatLiterals.DayHourSep, System.Globalization.TimeSpanFormat.FormatLiterals.End, System.Globalization.TimeSpanFormat.FormatLiterals.ff, System.DateTimeFormat.fixedNumberFormats, System.format, System.Globalization.TimeSpanFormat.FormatLiterals.hh, System.Globalization.TimeSpanFormat.FormatLiterals.HourMinuteSep, System.Globalization.TimeSpanFormat.FormatLiterals.Init(), int, System.Globalization.CultureInfo.InvariantCulture, System.L, System.Globalization.TimeSpanFormat.FormatLiterals.MinuteSecondSep, System.Globalization.TimeSpanFormat.FormatLiterals.mm, System.Globalization.TimeSpanFormat.NegativeInvariantFormatLiterals, System.Globalization.TimeSpanFormat.PositiveInvariantFormatLiterals, System.Globalization.TimeSpanParse.Pow10(), System.Globalization.TimeSpanFormat.FormatLiterals.SecondFractionSep, System.Globalization.TimeSpanFormat.FormatLiterals.ss, System.Globalization.TimeSpanFormat.FormatLiterals.Start, and System.value.
Referenced by System.Globalization.TimeSpanFormat.FormatToBuilder().