Terraria Decompiled: System.Runtime.Remoting.Messaging.MethodResponse.MethodResponse
MethodResponse() [4/6]
System.Runtime.Remoting.Messaging.MethodResponse.MethodResponse (IMethodCallMessage msg, CADMethodReturnMessage retmsg) inline package
Definition at line 65 of file MethodResponse.cs.
        {
            this._callMsg = msg;
            this._methodBase = msg.MethodBase;
            this._uri = msg.Uri;
            this._methodName = msg.MethodName;
            ArrayList arguments = retmsg.GetArguments();
            this._exception = retmsg.GetException(arguments);
            this._returnValue = retmsg.GetReturnValue(arguments);
            this._args = retmsg.GetArgs(arguments);
            this._callContext = retmsg.GetLogicalCallContext(arguments);
            if (this._callContext == null)
            {
                this._callContext = new LogicalCallContext();
            }
            if (retmsg.PropertiesCount > 0)
            {
                CADMessageBase.UnmarshalProperties(this.Properties, retmsg.PropertiesCount, arguments);
            }
        }
References System.Runtime.Remoting.Messaging.MethodResponse._callContext, System.Runtime.Remoting.Messaging.CADMethodReturnMessage.GetArgs(), System.Runtime.Remoting.Messaging.CADMethodReturnMessage.GetArguments(), System.Runtime.Remoting.Messaging.CADMethodReturnMessage.GetException(), System.Runtime.Remoting.Messaging.CADMessageBase.GetLogicalCallContext(), System.Runtime.Remoting.Messaging.CADMethodReturnMessage.GetReturnValue(), System.Runtime.Remoting.Messaging.MethodResponse.LogicalCallContext, System.Runtime.Remoting.Messaging.IMethodMessage.MethodBase, System.Runtime.Remoting.Messaging.IMethodMessage.MethodName, System.Runtime.Remoting.Messaging.MethodResponse.Properties, System.Runtime.Remoting.Messaging.CADMethodReturnMessage.PropertiesCount, System.Runtime.Remoting.Messaging.CADMessageBase.UnmarshalProperties(), and System.Runtime.Remoting.Messaging.IMethodMessage.Uri.