Terraria Decompiled: Terraria.NetMessage.DecompressTileBlock_Inner
DecompressTileBlock_Inner()
static void Terraria.NetMessage.DecompressTileBlock_Inner (BinaryReader reader, int xStart, int yStart, int width, int height) inline static
Definition at line 2258 of file NetMessage.cs.
        {
            Tile tile = null;
            int num = 0;
            for (int i = yStart; i < yStart + height; i++)
            {
                for (int j = xStart; j < xStart + width; j++)
                {
                    if (num != 0)
                    {
                        num--;
                        if (Main.tile[j, i] == null)
{
                            Main.tile[j, i] = new Tile(tile);
                        }
                        else
{
                            Main.tile[j, i].CopyFrom(tile);
                        }
                    }
                    else
                    {
                        byte b3;
                        byte b2;
                        byte b = (b2 = (b3 = 0));
                        tile = Main.tile[j, i];
                        if (tile == null)
{
                            tile = new Tile();
                            Main.tile[j, i] = tile;
                        }
                        else
{
                            tile.ClearEverything();
                        }
                        byte b4 = reader.ReadByte();
                        bool flag = false;
                        if ((b4 & 1) == 1)
{
                            flag = true;
                            b2 = reader.ReadByte();
                        }
                        bool flag2 = false;
                        if (flag && (b2 & 1) == 1)
{
                            flag2 = true;
                            b = reader.ReadByte();
                        }
                        if (flag2 && (b & 1) == 1)
{
                            b3 = reader.ReadByte();
                        }
                        bool flag3 = tile.active();
                        byte b5;
                        if ((b4 & 2) == 2)
{
                            tile.active(true);
                            ushort type = tile.type;
                            int num2;
                            if ((b4 & 32) == 32)
{
                                b5 = reader.ReadByte();
                                num2 = (int)reader.ReadByte();
                                num2 = (num2 << 8) | (int)b5;
                            }
                            else
{
                                num2 = (int)reader.ReadByte();
                            }
                            tile.type = (ushort)num2;
                            if (Main.tileFrameImportant[num2])
{
                                tile.frameX = reader.ReadInt16();
                                tile.frameY = reader.ReadInt16();
                            }
                            else if (!flag3 || tile.type != type)
{
                                tile.frameX = -1;
                                tile.frameY = -1;
                            }
                            if ((b & 8) == 8)
{
                                tile.color(reader.ReadByte());
                            }
                        }
                        if ((b4 & 4) == 4)
{
                            tile.wall = (ushort)reader.ReadByte();
                            if ((b & 16) == 16)
{
                                tile.wallColor(reader.ReadByte());
                            }
                        }
                        b5 = (byte)((b4 & 24) >> 3);
                        if (b5 != 0)
{
                            tile.liquid = reader.ReadByte();
                            if ((b & 128) == 128)
{
                                tile.shimmer(true);
                            }
                            else if (b5 > 1)
{
                                if (b5 == 2)
{
                                    tile.lava(true);
                                }
                                else
{
                                    tile.honey(true);
                                }
                            }
                        }
                        if (b2 > 1)
{
                            if ((b2 & 2) == 2)
{
                                tile.wire(true);
                            }
                            if ((b2 & 4) == 4)
{
                                tile.wire2(true);
                            }
                            if ((b2 & 8) == 8)
{
                                tile.wire3(true);
                            }
                            b5 = (byte)((b2 & 112) >> 4);
                            if (b5 != 0 && Main.tileSolid[(int)tile.type])
{
                                if (b5 == 1)
{
                                    tile.halfBrick(true);
                                }
                                else
{
                                    tile.slope(b5 - 1);
                                }
                            }
                        }
                        if (b > 1)
{
                            if ((b & 2) == 2)
{
                                tile.actuator(true);
                            }
                            if ((b & 4) == 4)
{
                                tile.inActive(true);
                            }
                            if ((b & 32) == 32)
{
                                tile.wire4(true);
                            }
                            if ((b & 64) == 64)
{
                                b5 = reader.ReadByte();
                                tile.wall = (ushort)(((int)b5 << 8) | (int)tile.wall);
                            }
                        }
                        if (b3 > 1)
{
                            if ((b3 & 2) == 2)
{
                                tile.invisibleBlock(true);
                            }
                            if ((b3 & 4) == 4)
{
                                tile.invisibleWall(true);
                            }
                            if ((b3 & 8) == 8)
{
                                tile.fullbrightBlock(true);
                            }
                            if ((b3 & 16) == 16)
{
                                tile.fullbrightWall(true);
                            }
                        }
                        b5 = (byte)((b4 & 192) >> 6);
                        if (b5 == 0)
{
                            num = 0;
                        }
                        else if (b5 == 1)
{
                            num = (int)reader.ReadByte();
                        }
                        else
{
                            num = (int)reader.ReadInt16();
                        }
                    }
                }
            }
            short num3 = reader.ReadInt16();
            for (int k = 0; k < (int)num3; k++)
            {
                short num4 = reader.ReadInt16();
                short num5 = reader.ReadInt16();
                short num6 = reader.ReadInt16();
                string text = reader.ReadString();
                if (num4 >= 0 && num4 < 8000)
                {
                    Chest.CreateWorldChest((int)num4, (int)num5, (int)num6).name = text;
                }
            }
            num3 = reader.ReadInt16();
            for (int l = 0; l < (int)num3; l++)
            {
                short num7 = reader.ReadInt16();
                short num8 = reader.ReadInt16();
                short num9 = reader.ReadInt16();
                string text2 = reader.ReadString();
                if (num7 >= 0 && num7 < 32000)
                {
                    if (Main.sign[(int)num7] == null)
                    {
                        Main.sign[(int)num7] = new Sign();
                    }
                    Main.sign[(int)num7].text = text2;
                    Main.sign[(int)num7].x = (int)num8;
                    Main.sign[(int)num7].y = (int)num9;
                }
            }
            num3 = reader.ReadInt16();
            for (int m = 0; m < (int)num3; m++)
            {
                TileEntity.Add(TileEntity.Read(reader, 319, false));
            }
            MapUpdateQueue.Add(new Rectangle(xStart, yStart, width, height));
            Main.sectionManager.SetTilesLoaded(xStart, yStart, xStart + width - 1, yStart + height - 1);
        }
References Terraria.Tile.active(), Terraria.Tile.actuator(), Terraria.Map.MapUpdateQueue.Add(), Terraria.DataStructures.TileEntity.Add(), Terraria.Tile.ClearEverything(), Terraria.Tile.color(), Terraria.Tile.CopyFrom(), Terraria.Chest.CreateWorldChest(), Terraria.Tile.fullbrightBlock(), Terraria.Tile.fullbrightWall(), Terraria.Tile.halfBrick(), Terraria.Tile.honey(), Terraria.Tile.inActive(), int, Terraria.Tile.invisibleBlock(), Terraria.Tile.invisibleWall(), Terraria.Tile.lava(), System.name, Terraria.DataStructures.TileEntity.Read(), System.IO.BinaryReader.ReadByte(), System.IO.BinaryReader.ReadInt16(), System.IO.BinaryReader.ReadString(), Terraria.Main.sectionManager, Terraria.WorldSections.SetTilesLoaded(), Terraria.Tile.shimmer(), Terraria.Main.sign, Terraria.Tile.slope(), System.text, Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.Main.tileFrameImportant, Terraria.Main.tileSolid, Terraria.Tile.type, Terraria.Tile.wall, Terraria.Tile.wallColor(), Terraria.Tile.wire(), Terraria.Tile.wire2(), Terraria.Tile.wire3(), and Terraria.Tile.wire4().
Referenced by Terraria.NetMessage.DecompressTileBlock().