Terraria Decompiled: Terraria.NetMessage.SendTileSquare
SendTileSquare() [2/3]
static void Terraria.NetMessage.SendTileSquare (int whoAmi, int tileX, int tileY, int xSize, int ySize, TileChangeType changeType = TileChangeType::None) inline static
Definition at line 2651 of file NetMessage.cs.
        {
            NetMessage.SendData(20, whoAmi, -1, null, tileX, (float)tileY, (float)xSize, (float)ySize, (int)changeType, 0, 0);
        }
References Terraria.NetMessage.SendData().
Referenced by Terraria.Projectile.AI(), Terraria.NPC.AI_001_Slimes(), Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_045_Golem(), Terraria.NPC.AI_047_GolemFist(), Terraria.Projectile.AI_202_TorchGodHelper(), Terraria.WorldGen.AttemptToGeneratePlanteraBulbAt(), Terraria.NPC.BigMimicSummonCheck(), Terraria.GameContent.Tile_Entities.TELogicSensor.ChangeState(), Terraria.WorldGen.CheckAlch(), Terraria.WorldGen.CheckBamboo(), Terraria.WorldGen.CheckCatTail(), Terraria.WorldGen.CheckExploitDestroyQueue(), Terraria.WorldGen.CheckLilyPad(), Terraria.Wiring.CheckLogicGate(), Terraria.WorldGen.CheckUnderwaterPlant(), Terraria.WorldGen.Convert_ActuallyConvertTile(), Terraria.WorldGen.Convert_ActuallyConvertTorch(), Terraria.WorldGen.Convert_ActuallyConvertWall(), Terraria.WorldGen.ConvertTreeAndGround(), Terraria.NPC.CreateBrickBoxForWallOfFlesh(), Terraria.Liquid.CreateLiquidMergeTile(), Terraria.Wiring.DeActive(), Terraria.Liquid.DelWater(), Terraria.Player.DoBootsEffect_PlaceFlowersOnTile(), Terraria.Wiring.ExplodeMine(), Terraria.Minecart.FlipSwitchTrack(), Terraria.MessageBuffer.GetData(), Terraria.WorldGen.GrowAlch(), Terraria.WorldGen.GrowCactus(), Terraria.WorldGen.GrowCatTail(), Terraria.WorldGen.GrowCheckSeaweed(), Terraria.WorldGen.GrowEpicTree(), Terraria.WorldGen.GrowPalmTree(), Terraria.WorldGen.GrowPumpkin(), Terraria.WorldGen.GrowSeaOat(), Terraria.WorldGen.GrowShroom(), Terraria.WorldGen.GrowSpike(), Terraria.WorldGen.GrowTree(), Terraria.WorldGen.GrowTreeWithSettings(), Terraria.WorldGen.GrowUndergroundTree(), Terraria.WorldGen.GrowWeb(), Terraria.WorldGen.hardUpdateWorld(), Terraria.Wiring.HitWireSingle(), Terraria.GameContent.Tile_Entities.TETrainingDummy.Hook_AfterPlacement(), Terraria.GameContent.Tile_Entities.TEItemFrame.Hook_AfterPlacement(), Terraria.GameContent.Tile_Entities.TELogicSensor.Hook_AfterPlacement(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.Hook_AfterPlacement(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.Hook_AfterPlacement(), Terraria.GameContent.Tile_Entities.TEHatRack.Hook_AfterPlacement(), Terraria.GameContent.Tile_Entities.TEFoodPlatter.Hook_AfterPlacement(), Terraria.GameContent.Tile_Entities.TEDeadCellsDisplayJar.Hook_AfterPlacement(), Terraria.Player.ItemCheck_TryPlacingWearablesOnMannequins(), Terraria.Player.ItemCheck_UseMiningTools_TryPoundingTile(), Terraria.WorldGen.LaunchRocket(), Terraria.Liquid.LiquidCheck(), Terraria.WorldGen.meteor(), Terraria.Player.MowGrassTile(), Terraria.WorldGen.OreRunner(), Terraria.Wiring.PixelBoxPass(), Terraria.GameContent.Tile_Entities.TELeashedEntityAnchor.PlaceFromPlayerPlacementHook(), Terraria.WorldGen.PlaceLiquid(), Terraria.GameContent.Tile_Entities.TETeleportationPylon.PlacementPreviewHook_AfterPlacement(), Terraria.Player.PlaceThing_Tiles_PlaceIt_AdjustPlants(), Terraria.Player.PlaceThing_Tiles_PlaceIt_SpinBedsAndBaths(), Terraria.Player.PlaceThing_Tiles_PlaceIt_SpinChairs(), Terraria.Player.PlaceThing_Tiles_PlaceIt_SpinTraps(), Terraria.Player.PlaceThing_Tiles_PlaceIt_StaffOfRegrowthCheck(), Terraria.Player.PlaceThing_XMasTreeTops(), Terraria.Player.PlaceWeapon(), Terraria.WorldGen.PlantAlch(), Terraria.WorldGen.PlantSeaOat(), Terraria.Wiring.ReActive(), Terraria.Player.RelightTorches(), Terraria.NetMessage.SendTileSquare(), Terraria.NetMessage.SendTileSquare(), Terraria.WorldGen.SpawnFallingBlockProjectile(), Terraria.WorldGen.SpawnPlanteraThorns(), Terraria.Projectile.SpawnWebs(), Terraria.WorldGen.SpreadGrass(), Terraria.WorldGen.SwitchCannon(), Terraria.WorldGen.SwitchFountain(), Terraria.WorldGen.SwitchMB(), Terraria.WorldGen.SwitchMonolith(), Terraria.Player.TileInteractionsUse(), Terraria.Wiring.Toggle2x2Light(), Terraria.Wiring.ToggleCampFire(), Terraria.Wiring.ToggleCandle(), Terraria.Wiring.ToggleChandelier(), Terraria.Wiring.ToggleFirePlace(), Terraria.WorldGen.ToggleGemLock(), Terraria.Wiring.ToggleHangingLantern(), Terraria.Wiring.ToggleHolidayLight(), Terraria.Wiring.ToggleLamp(), Terraria.Wiring.ToggleLampPost(), Terraria.Wiring.ToggleTorch(), Terraria.Player.TorchAttack(), Terraria.Minecart.TryFittingTileOrientation(), Terraria.WorldGen.TryGrowingAbigailsFlower(), Terraria.WorldGen.TryGrowingGlowTulip(), Terraria.WorldGen.TryPlacingChilletEgg(), Terraria.Wiring.UpdateMech(), Terraria.WorldGen.UpdateStalagtiteStyle(), Terraria.WorldGen.UpdateWorld_GrassGrowth(), Terraria.WorldGen.UpdateWorld_OvergroundTile(), and Terraria.WorldGen.UpdateWorld_UndergroundTile().