Terraria Decompiled: Terraria.NetMessage.CheckBytes
CheckBytes()
static void Terraria.NetMessage.CheckBytes (int bufferIndex = 256) inline static
Definition at line 2521 of file NetMessage.cs.
        {
            if (Main.dedServ && Netplay.Clients[bufferIndex].PendingTermination)
            {
                Netplay.Clients[bufferIndex].PendingTerminationApproved = true;
                return;
            }
            if (!Main.dedServ && !Netplay.Connection.IsConnected() && !Netplay.Connection.IsReading && !NetMessage.buffer[bufferIndex].checkBytes)
            {
                Netplay.Disconnect = true;
                Main.statusText = Language.GetTextValue("Net.LostConnection");
            }
            if (!NetMessage.buffer[bufferIndex].checkBytes)
            {
                return;
            }
            MessageBuffer messageBuffer = NetMessage.buffer[bufferIndex];
            lock (messageBuffer)
            {
                NetMessage.buffer[bufferIndex].checkBytes = false;
                int num = 0;
                int i = NetMessage.buffer[bufferIndex].totalData;
                try
                {
                    while (i >= 2)
                    {
                        int num2 = (int)BitConverter.ToUInt16(NetMessage.buffer[bufferIndex].readBuffer, num);
                        if (num2 < 3)
{
                            throw new IndexOutOfRangeException("Invalid packet. Message size too small (" + num2 + ")");
                        }
                        if (i < num2)
{
                            break;
                        }
                        long position = NetMessage.buffer[bufferIndex].reader.BaseStream.Position;
                        int num3;
                        NetMessage.buffer[bufferIndex].GetData(num + 2, num2 - 2, out num3);
                        NetMessage.buffer[bufferIndex].reader.BaseStream.Position = position + (long)num2;
                        i -= num2;
                        num += num2;
                    }
                }
                catch (Exception)
                {
                    if (Main.dedServ && num < NetMessage.buffer.Length - 100)
                    {
                        Console.WriteLine(Language.GetTextValue("Error.NetMessageError", NetMessage.buffer[num + 2]));
                    }
                    i = 0;
                    num = 0;
                }
                if (i != NetMessage.buffer[bufferIndex].totalData)
                {
                    for (int j = 0; j < i; j++)
                    {
                        NetMessage.buffer[bufferIndex].readBuffer[j] = NetMessage.buffer[bufferIndex].readBuffer[j + num];
                    }
                    NetMessage.buffer[bufferIndex].totalData = i;
                }
            }
        }
References System.IO.BinaryReader.BaseStream, Terraria.NetMessage.buffer, Terraria.MessageBuffer.checkBytes, Terraria.Netplay.Clients, Terraria.Netplay.Connection, Terraria.Main.dedServ, Terraria.MessageBuffer.GetData(), Terraria.Localization.Language.GetTextValue(), int, Terraria.RemoteServer.IsConnected(), Terraria.RemoteServer.IsReading, long, Terraria.RemoteClient.PendingTermination, Terraria.RemoteClient.PendingTerminationApproved, System.IO.Stream.Position, Terraria.MessageBuffer.readBuffer, Terraria.MessageBuffer.reader, Terraria.MessageBuffer.totalData, System.BitConverter.ToUInt16(), and System.Console.WriteLine().
Referenced by Terraria.Netplay.InnerClientLoop(), Terraria.Netplay.UpdateClientInMainThread(), and Terraria.Netplay.UpdateServerInMainThread().