Terraria Decompiled: Terraria.NetMessage.SendPacket
SendPacket()
static void Terraria.NetMessage.SendPacket (byte[] data, int remoteClient) inline static private
Definition at line 1800 of file NetMessage.cs.
        {
            try
            {
                ushort num = BitConverter.ToUInt16(data, 0);
                byte b = data[2];
                NetMessage.buffer[remoteClient].spamCount++;
                Main.ActiveNetDiagnosticsUI.CountSentMessage((int)b, (int)num);
                if (!Main.dedServ)
                {
                    Netplay.Connection.Socket.AsyncSend(data, 0, (int)num, new SocketSendCallback(Netplay.Connection.ClientWriteCallBack), null);
                }
                else
                {
                    Netplay.Clients[remoteClient].Socket.AsyncSend(data, 0, (int)num, new SocketSendCallback(Netplay.Clients[remoteClient].ServerWriteCallBack), null);
                }
            }
            catch
            {
                bool dedServ = Main.dedServ;
            }
        }
References Terraria.Main.ActiveNetDiagnosticsUI, Terraria.Net.Sockets.ISocket.AsyncSend(), Terraria.NetMessage.buffer, Terraria.Netplay.Clients, Terraria.RemoteServer.ClientWriteCallBack(), Terraria.Netplay.Connection, Terraria.Main.dedServ, Terraria.RemoteClient.ServerWriteCallBack(), Terraria.RemoteClient.Socket, Terraria.RemoteServer.Socket, Terraria.Net.Sockets.SocketSendCallback(), Terraria.MessageBuffer.spamCount, and System.BitConverter.ToUInt16().
Referenced by Terraria.NetMessage.SendData(), and Terraria.NetMessage.SendPacketToServer().