Terraria Decompiled: Terraria.NetMessage.SyncOnePlayer
SyncOnePlayer()
static void Terraria.NetMessage.SyncOnePlayer (int plr, int toWho, int fromWho) inline static private
Definition at line 2936 of file NetMessage.cs.
        {
            int num = 0;
            if (Main.player[plr].active)
            {
                num = 1;
            }
            if (Netplay.Clients[plr].State == 10)
            {
                NetMessage.SendData(14, toWho, fromWho, null, plr, (float)num, 0f, 0f, 0, 0, 0);
                NetMessage.SendData(4, toWho, fromWho, null, plr, 0f, 0f, 0f, 0, 0, 0);
                NetMessage.SendData(13, toWho, fromWho, null, plr, 0f, 0f, 0f, 0, 0, 0);
                if (Main.player[plr].statLife <= 0)
                {
                    NetMessage.SendData(135, toWho, fromWho, null, plr, 0f, 0f, 0f, 0, 0, 0);
                }
                NetMessage.SendData(16, toWho, fromWho, null, plr, 0f, 0f, 0f, 0, 0, 0);
                NetMessage.SendData(30, toWho, fromWho, null, plr, 0f, 0f, 0f, 0, 0, 0);
                NetMessage.SendData(45, toWho, fromWho, null, plr, 0f, 0f, 0f, 0, 0, 0);
                NetMessage.SendData(42, toWho, fromWho, null, plr, 0f, 0f, 0f, 0, 0, 0);
                NetMessage.SendData(50, toWho, fromWho, null, plr, 0f, 0f, 0f, 0, 0, 0);
                NetMessage.SendData(80, toWho, fromWho, null, plr, (float)Main.player[plr].chest, 0f, 0f, 0, 0, 0);
                NetMessage.SendData(142, toWho, fromWho, null, plr, 0f, 0f, 0f, 0, 0, 0);
                NetMessage.SendData(147, toWho, fromWho, null, plr, (float)Main.player[plr].CurrentLoadoutIndex, 0f, 0f, 0, 0, 0);
                TagEffectState.NetModule.SyncStateIfNecessary(Main.player[plr].TagEffectState, toWho, fromWho);
                for (int i = 0; i < 59; i++)
                {
                    NetMessage.SendData(5, toWho, fromWho, null, plr, (float)(PlayerItemSlotID.Inventory0 + i), 0f, 0f, 0, 0, 0);
                }
                for (int j = 0; j < Main.player[plr].armor.Length; j++)
                {
                    NetMessage.SendData(5, toWho, fromWho, null, plr, (float)(PlayerItemSlotID.Armor0 + j), 0f, 0f, 0, 0, 0);
                }
                for (int k = 0; k < Main.player[plr].dye.Length; k++)
                {
                    NetMessage.SendData(5, toWho, fromWho, null, plr, (float)(PlayerItemSlotID.Dye0 + k), 0f, 0f, 0, 0, 0);
                }
                NetMessage.SyncOnePlayer_ItemArray(plr, toWho, fromWho, Main.player[plr].miscEquips, PlayerItemSlotID.Misc0);
                NetMessage.SyncOnePlayer_ItemArray(plr, toWho, fromWho, Main.player[plr].miscDyes, PlayerItemSlotID.MiscDye0);
                NetMessage.SyncOnePlayer_ItemArray(plr, toWho, fromWho, Main.player[plr].Loadouts[0].Armor, PlayerItemSlotID.Loadout1_Armor_0);
                NetMessage.SyncOnePlayer_ItemArray(plr, toWho, fromWho, Main.player[plr].Loadouts[0].Dye, PlayerItemSlotID.Loadout1_Dye_0);
                NetMessage.SyncOnePlayer_ItemArray(plr, toWho, fromWho, Main.player[plr].Loadouts[1].Armor, PlayerItemSlotID.Loadout2_Armor_0);
                NetMessage.SyncOnePlayer_ItemArray(plr, toWho, fromWho, Main.player[plr].Loadouts[1].Dye, PlayerItemSlotID.Loadout2_Dye_0);
                NetMessage.SyncOnePlayer_ItemArray(plr, toWho, fromWho, Main.player[plr].Loadouts[2].Armor, PlayerItemSlotID.Loadout3_Armor_0);
                NetMessage.SyncOnePlayer_ItemArray(plr, toWho, fromWho, Main.player[plr].Loadouts[2].Dye, PlayerItemSlotID.Loadout3_Dye_0);
                if (!Netplay.Clients[plr].IsAnnouncementCompleted)
                {
                    Netplay.Clients[plr].IsAnnouncementCompleted = true;
                    ChatHelper.BroadcastChatMessage(NetworkText.FromKey(Lang.mp[19].Key, new object[] { Main.player[plr].name }), new Color(255, 240, 20), plr);
                    if (Main.dedServ)
                    {
                        Console.WriteLine(Lang.mp[19].Format(Main.player[plr].name));
                    }
                }
                for (int l = 0; l < 1000; l++)
                {
                    Projectile projectile = Main.projectile[l];
                    if (projectile.active && projectile.owner == plr)
                    {
                        NetMessage.SendData(27, toWho, -1, null, l, 0f, 0f, 0f, 0, 0, 0);
                    }
                }
                return;
            }
            num = 0;
            NetMessage.SendData(14, -1, plr, null, plr, (float)num, 0f, 0f, 0, 0, 0);
            if (Netplay.Clients[plr].IsAnnouncementCompleted)
            {
                Netplay.Clients[plr].IsAnnouncementCompleted = false;
                ChatHelper.BroadcastChatMessage(NetworkText.FromKey(Lang.mp[20].Key, new object[] { Netplay.Clients[plr].Name }), new Color(255, 240, 20), plr);
                if (Main.dedServ)
                {
                    Console.WriteLine(Lang.mp[20].Format(Netplay.Clients[plr].Name));
                }
                Netplay.Clients[plr].Name = "Anonymous";
            }
            Player.Hooks.PlayerDisconnect(plr);
        }
References Terraria.Player.active, Terraria.Projectile.active, Terraria.EquipmentLoadout.Armor, Terraria.Player.armor, Terraria.ID.PlayerItemSlotID.Armor0, Terraria.Chat.ChatHelper.BroadcastChatMessage(), Terraria.Player.chest, Terraria.Netplay.Clients, Terraria.Player.CurrentLoadoutIndex, Terraria.Main.dedServ, Terraria.EquipmentLoadout.Dye, Terraria.Player.dye, Terraria.ID.PlayerItemSlotID.Dye0, Terraria.Localization.LocalizedText.Format(), Terraria.Localization.NetworkText.FromKey(), Terraria.ID.PlayerItemSlotID.Inventory0, Terraria.RemoteClient.IsAnnouncementCompleted, Terraria.Localization.LocalizedText.Key, Terraria.ID.PlayerItemSlotID.Loadout1_Armor_0, Terraria.ID.PlayerItemSlotID.Loadout1_Dye_0, Terraria.ID.PlayerItemSlotID.Loadout2_Armor_0, Terraria.ID.PlayerItemSlotID.Loadout2_Dye_0, Terraria.ID.PlayerItemSlotID.Loadout3_Armor_0, Terraria.ID.PlayerItemSlotID.Loadout3_Dye_0, Terraria.Player.Loadouts, Terraria.ID.PlayerItemSlotID.Misc0, Terraria.ID.PlayerItemSlotID.MiscDye0, Terraria.Player.miscDyes, Terraria.Player.miscEquips, Terraria.Lang.mp, Terraria.Player.name, Terraria.RemoteClient.Name, Terraria.Projectile.owner, Terraria.Main.player, Terraria.Player.Hooks.PlayerDisconnect(), Terraria.Main.projectile, Terraria.NetMessage.SendData(), Terraria.RemoteClient.State, Terraria.Player.statLife, Terraria.NetMessage.SyncOnePlayer_ItemArray(), Terraria.GameContent.Items.TagEffectState.NetModule.SyncStateIfNecessary(), Terraria.Player.TagEffectState, and System.Console.WriteLine().
Referenced by Terraria.NetMessage.SyncConnectedPlayer(), and Terraria.NetMessage.SyncDisconnectedPlayer().