Terraria Decompiled: Terraria.NetMessage.DoesPlayerSlotCountAsAHost
DoesPlayerSlotCountAsAHost()
static bool Terraria.NetMessage.DoesPlayerSlotCountAsAHost (int plr) inline static
Definition at line 2930 of file NetMessage.cs.
        {
            return Netplay.Clients[plr].State == 10 && Netplay.Clients[plr].Socket.GetRemoteAddress().IsLocalHost();
        }
References Terraria.Netplay.Clients, Terraria.Net.Sockets.ISocket.GetRemoteAddress(), Terraria.Net.RemoteAddress.IsLocalHost(), Terraria.RemoteClient.Socket, and Terraria.RemoteClient.State.
Referenced by Terraria.NetMessage.EnsureLocalPlayerIsPresent(), and Terraria.MessageBuffer.GetData().