Terraria Decompiled: Terraria.NetMessage.SendData
SendData()
static void Terraria.NetMessage.SendData (int msgType, int remoteClient = -1, int ignoreClient = -1, NetworkText text = null, int number = 0, float number2 = 0f, float number3 = 0f, float number4 = 0f, int number5 = 0, int number6 = 0, int number7 = 0) inline static
Definition at line 39 of file NetMessage.cs.
        {
            if (Main.netMode == 0)
            {
                return;
            }
            if (msgType == 21 && (Main.item[number].shimmerTime > 0f || Main.item[number].shimmered))
            {
                msgType = 145;
            }
            if (msgType == 21 && Main.item[number].type == 0)
            {
                msgType = 151;
            }
            int num = 256;
            if (text == null)
            {
                text = NetworkText.Empty;
            }
            if (Main.netMode == 2 && remoteClient >= 0)
            {
                num = remoteClient;
            }
            MessageBuffer messageBuffer = NetMessage.buffer[num];
            lock (messageBuffer)
            {
                BinaryWriter binaryWriter = NetMessage.buffer[num].writer;
                if (binaryWriter == null)
                {
                    NetMessage.buffer[num].ResetWriter();
                    binaryWriter = NetMessage.buffer[num].writer;
                }
                binaryWriter.BaseStream.Position = 0L;
                long position = binaryWriter.BaseStream.Position;
                binaryWriter.BaseStream.Position += 2L;
                binaryWriter.Write((byte)msgType);
                switch (msgType)
                {
                case 1:
                    binaryWriter.Write("Terraria" + 319);
                    break;
                case 2:
                    text.Serialize(binaryWriter);
                    if (Main.dedServ)
                    {
                        Console.WriteLine(Language.GetTextValue("CLI.ClientWasBooted", Netplay.Clients[num].Socket.GetRemoteAddress().ToString(), text));
                    }
                    break;
                case 3:
                    binaryWriter.Write((byte)remoteClient);
                    binaryWriter.Write(false);
                    break;
                case 4:
                {
                    Player player = Main.player[number];
                    binaryWriter.Write((byte)number);
                    binaryWriter.Write((byte)player.skinVariant);
                    binaryWriter.Write((byte)player.voiceVariant);
                    binaryWriter.Write(player.voicePitchOffset);
                    binaryWriter.Write((byte)player.hair);
                    binaryWriter.Write(player.name);
                    binaryWriter.Write(player.hairDye);
                    NetMessage.WriteAccessoryVisibility(binaryWriter, player.hideVisibleAccessory);
                    binaryWriter.Write(player.hideMisc);
                    binaryWriter.WriteRGB(player.hairColor);
                    binaryWriter.WriteRGB(player.skinColor);
                    binaryWriter.WriteRGB(player.eyeColor);
                    binaryWriter.WriteRGB(player.shirtColor);
                    binaryWriter.WriteRGB(player.underShirtColor);
                    binaryWriter.WriteRGB(player.pantsColor);
                    binaryWriter.WriteRGB(player.shoeColor);
                    BitsByte bitsByte = 0;
                    if (player.difficulty == 1)
                    {
                        bitsByte[0] = true;
                    }
                    else if (player.difficulty == 2)
                    {
                        bitsByte[1] = true;
                    }
                    else if (player.difficulty == 3)
                    {
                        bitsByte[3] = true;
                    }
                    bitsByte[2] = player.extraAccessory;
                    binaryWriter.Write(bitsByte);
                    BitsByte bitsByte2 = 0;
                    bitsByte2[0] = player.UsingBiomeTorches;
                    bitsByte2[1] = player.happyFunTorchTime;
                    bitsByte2[2] = player.unlockedBiomeTorches;
                    bitsByte2[3] = player.unlockedSuperCart;
                    bitsByte2[4] = player.enabledSuperCart;
                    binaryWriter.Write(bitsByte2);
                    BitsByte bitsByte3 = 0;
                    bitsByte3[0] = player.usedAegisCrystal;
                    bitsByte3[1] = player.usedAegisFruit;
                    bitsByte3[2] = player.usedArcaneCrystal;
                    bitsByte3[3] = player.usedGalaxyPearl;
                    bitsByte3[4] = player.usedGummyWorm;
                    bitsByte3[5] = player.usedAmbrosia;
                    bitsByte3[6] = player.ateArtisanBread;
                    binaryWriter.Write(bitsByte3);
                    break;
                }
                case 5:
                {
                    binaryWriter.Write((byte)number);
                    binaryWriter.Write((short)number2);
                    PlayerItemSlotID.SlotReference slotReference = new PlayerItemSlotID.SlotReference(Main.player[number], (int)number2);
                    Item item = slotReference.Item;
                    if (item.Name == "" || item.stack == 0 || item.type == 0)
                    {
                        item.SetDefaults(0, null);
                    }
                    int num2 = item.stack;
                    int type = item.type;
                    if (num2 < 0)
                    {
                        num2 = 0;
                    }
                    binaryWriter.Write((short)num2);
                    binaryWriter.Write(item.prefix);
                    binaryWriter.Write((short)type);
                    BitsByte bitsByte4 = default(BitsByte);
                    bitsByte4[0] = item.favorited;
                    bitsByte4[1] = number3 != 0f;
                    binaryWriter.Write(bitsByte4);
                    break;
                }
                case 7:
                {
                    binaryWriter.Write((int)Main.time);
                    BitsByte bitsByte5 = 0;
                    bitsByte5[0] = Main.dayTime;
                    bitsByte5[1] = Main.bloodMoon;
                    bitsByte5[2] = Main.eclipse;
                    binaryWriter.Write(bitsByte5);
                    binaryWriter.Write((byte)Main.moonPhase);
                    binaryWriter.Write((short)Main.maxTilesX);
                    binaryWriter.Write((short)Main.maxTilesY);
                    binaryWriter.Write((short)Main.spawnTileX);
                    binaryWriter.Write((short)Main.spawnTileY);
                    binaryWriter.Write((short)Main.worldSurface);
                    binaryWriter.Write((short)Main.rockLayer);
                    binaryWriter.Write(Main.ActiveWorldFileData.WorldId);
                    binaryWriter.Write(Main.worldName);
                    binaryWriter.Write((byte)Main.GameMode);
                    binaryWriter.Write(Main.ActiveWorldFileData.UniqueId.ToByteArray());
                    binaryWriter.Write(Main.ActiveWorldFileData.WorldGeneratorVersion);
                    binaryWriter.Write((byte)Main.moonType);
                    binaryWriter.Write((byte)WorldGen.treeBG1);
                    binaryWriter.Write((byte)WorldGen.treeBG2);
                    binaryWriter.Write((byte)WorldGen.treeBG3);
                    binaryWriter.Write((byte)WorldGen.treeBG4);
                    binaryWriter.Write((byte)WorldGen.corruptBG);
                    binaryWriter.Write((byte)WorldGen.jungleBG);
                    binaryWriter.Write((byte)WorldGen.snowBG);
                    binaryWriter.Write((byte)WorldGen.hallowBG);
                    binaryWriter.Write((byte)WorldGen.crimsonBG);
                    binaryWriter.Write((byte)WorldGen.desertBG);
                    binaryWriter.Write((byte)WorldGen.oceanBG);
                    binaryWriter.Write((byte)WorldGen.mushroomBG);
                    binaryWriter.Write((byte)WorldGen.underworldBG);
                    binaryWriter.Write((byte)Main.iceBackStyle);
                    binaryWriter.Write((byte)Main.jungleBackStyle);
                    binaryWriter.Write((byte)Main.hellBackStyle);
                    binaryWriter.Write(Main.windSpeedTarget);
                    binaryWriter.Write((byte)Main.numClouds);
                    for (int i = 0; i < 3; i++)
                    {
                        binaryWriter.Write(Main.treeX[i]);
                    }
                    for (int j = 0; j < 4; j++)
                    {
                        binaryWriter.Write((byte)Main.treeStyle[j]);
                    }
                    for (int k = 0; k < 3; k++)
                    {
                        binaryWriter.Write(Main.caveBackX[k]);
                    }
                    for (int l = 0; l < 4; l++)
                    {
                        binaryWriter.Write((byte)Main.caveBackStyle[l]);
                    }
                    WorldGen.TreeTops.SyncSend(binaryWriter);
                    if (!Main.raining)
                    {
                        Main.maxRaining = 0f;
                    }
                    binaryWriter.Write(Main.maxRaining);
                    BitsByte bitsByte6 = 0;
                    bitsByte6[0] = WorldGen.shadowOrbSmashed;
                    bitsByte6[1] = NPC.downedBoss1;
                    bitsByte6[2] = NPC.downedBoss2;
                    bitsByte6[3] = NPC.downedBoss3;
                    bitsByte6[4] = Main.hardMode;
                    bitsByte6[5] = NPC.downedClown;
                    bitsByte6[7] = NPC.downedPlantBoss;
                    binaryWriter.Write(bitsByte6);
                    BitsByte bitsByte7 = 0;
                    bitsByte7[0] = NPC.downedMechBoss1;
                    bitsByte7[1] = NPC.downedMechBoss2;
                    bitsByte7[2] = NPC.downedMechBoss3;
                    bitsByte7[3] = NPC.downedMechBossAny;
                    bitsByte7[4] = Main.cloudBGActive >= 1f;
                    bitsByte7[5] = WorldGen.crimson;
                    bitsByte7[6] = Main.pumpkinMoon;
                    bitsByte7[7] = Main.snowMoon;
                    binaryWriter.Write(bitsByte7);
                    BitsByte bitsByte8 = 0;
                    bitsByte8[1] = Main.fastForwardTimeToDawn;
                    bitsByte8[2] = Main.slimeRain;
                    bitsByte8[3] = NPC.downedSlimeKing;
                    bitsByte8[4] = NPC.downedQueenBee;
                    bitsByte8[5] = NPC.downedFishron;
                    bitsByte8[6] = NPC.downedMartians;
                    bitsByte8[7] = NPC.downedAncientCultist;
                    binaryWriter.Write(bitsByte8);
                    BitsByte bitsByte9 = 0;
                    bitsByte9[0] = NPC.downedMoonlord;
                    bitsByte9[1] = NPC.downedHalloweenKing;
                    bitsByte9[2] = NPC.downedHalloweenTree;
                    bitsByte9[3] = NPC.downedChristmasIceQueen;
                    bitsByte9[4] = NPC.downedChristmasSantank;
                    bitsByte9[5] = NPC.downedChristmasTree;
                    bitsByte9[6] = NPC.downedGolemBoss;
                    bitsByte9[7] = BirthdayParty.PartyIsUp;
                    binaryWriter.Write(bitsByte9);
                    BitsByte bitsByte10 = 0;
                    bitsByte10[0] = NPC.downedPirates;
                    bitsByte10[1] = NPC.downedFrost;
                    bitsByte10[2] = NPC.downedGoblins;
                    bitsByte10[3] = Sandstorm.Happening;
                    bitsByte10[4] = DD2Event.Ongoing;
                    bitsByte10[5] = DD2Event.DownedInvasionT1;
                    bitsByte10[6] = DD2Event.DownedInvasionT2;
                    bitsByte10[7] = DD2Event.DownedInvasionT3;
                    binaryWriter.Write(bitsByte10);
                    BitsByte bitsByte11 = 0;
                    bitsByte11[0] = NPC.combatBookWasUsed;
                    bitsByte11[1] = LanternNight.LanternsUp;
                    bitsByte11[2] = NPC.downedTowerSolar;
                    bitsByte11[3] = NPC.downedTowerVortex;
                    bitsByte11[4] = NPC.downedTowerNebula;
                    bitsByte11[5] = NPC.downedTowerStardust;
                    bitsByte11[6] = Main.forceHalloweenForToday;
                    bitsByte11[7] = Main.forceXMasForToday;
                    binaryWriter.Write(bitsByte11);
                    BitsByte bitsByte12 = 0;
                    bitsByte12[0] = NPC.boughtCat;
                    bitsByte12[1] = NPC.boughtDog;
                    bitsByte12[2] = NPC.boughtBunny;
                    bitsByte12[3] = NPC.freeCake;
                    bitsByte12[4] = Main.drunkWorld;
                    bitsByte12[5] = NPC.downedEmpressOfLight;
                    bitsByte12[6] = NPC.downedQueenSlime;
                    bitsByte12[7] = Main.getGoodWorld;
                    binaryWriter.Write(bitsByte12);
                    BitsByte bitsByte13 = 0;
                    bitsByte13[0] = Main.tenthAnniversaryWorld;
                    bitsByte13[1] = Main.dontStarveWorld;
                    bitsByte13[2] = NPC.downedDeerclops;
                    bitsByte13[3] = Main.notTheBeesWorld;
                    bitsByte13[4] = Main.remixWorld;
                    bitsByte13[5] = NPC.unlockedSlimeBlueSpawn;
                    bitsByte13[6] = NPC.combatBookVolumeTwoWasUsed;
                    bitsByte13[7] = NPC.peddlersSatchelWasUsed;
                    binaryWriter.Write(bitsByte13);
                    BitsByte bitsByte14 = 0;
                    bitsByte14[0] = NPC.unlockedSlimeGreenSpawn;
                    bitsByte14[1] = NPC.unlockedSlimeOldSpawn;
                    bitsByte14[2] = NPC.unlockedSlimePurpleSpawn;
                    bitsByte14[3] = NPC.unlockedSlimeRainbowSpawn;
                    bitsByte14[4] = NPC.unlockedSlimeRedSpawn;
                    bitsByte14[5] = NPC.unlockedSlimeYellowSpawn;
                    bitsByte14[6] = NPC.unlockedSlimeCopperSpawn;
                    bitsByte14[7] = Main.fastForwardTimeToDusk;
                    binaryWriter.Write(bitsByte14);
                    BitsByte bitsByte15 = 0;
                    bitsByte15[0] = Main.noTrapsWorld;
                    bitsByte15[1] = Main.zenithWorld;
                    bitsByte15[2] = NPC.unlockedTruffleSpawn;
                    bitsByte15[3] = Main.vampireSeed;
                    bitsByte15[4] = Main.infectedSeed;
                    bitsByte15[5] = Main.teamBasedSpawnsSeed;
                    bitsByte15[6] = Main.skyblockWorld;
                    bitsByte15[7] = Main.dualDungeonsSeed;
                    binaryWriter.Write(bitsByte15);
                    BitsByte bitsByte16 = 0;
                    bitsByte16[0] = WorldGen.Skyblock.lowTiles;
                    binaryWriter.Write(bitsByte16);
                    binaryWriter.Write((byte)Main.sundialCooldown);
                    binaryWriter.Write((byte)Main.moondialCooldown);
                    binaryWriter.Write((short)WorldGen.SavedOreTiers.Copper);
                    binaryWriter.Write((short)WorldGen.SavedOreTiers.Iron);
                    binaryWriter.Write((short)WorldGen.SavedOreTiers.Silver);
                    binaryWriter.Write((short)WorldGen.SavedOreTiers.Gold);
                    binaryWriter.Write((short)WorldGen.SavedOreTiers.Cobalt);
                    binaryWriter.Write((short)WorldGen.SavedOreTiers.Mythril);
                    binaryWriter.Write((short)WorldGen.SavedOreTiers.Adamantite);
                    binaryWriter.Write((sbyte)Main.invasionType);
                    if (SocialAPI.Network != null)
                    {
                        binaryWriter.Write(SocialAPI.Network.GetLobbyId());
                    }
                    else
                    {
                        binaryWriter.Write(0UL);
                    }
                    binaryWriter.Write(Sandstorm.IntendedSeverity);
                    ExtraSpawnPointManager.Write(binaryWriter, true);
                    break;
                }
                case 8:
                    binaryWriter.Write(number);
                    binaryWriter.Write((int)number2);
                    binaryWriter.Write((byte)number3);
                    break;
                case 9:
                {
                    binaryWriter.Write(number);
                    text.Serialize(binaryWriter);
                    BitsByte bitsByte17 = (byte)number2;
                    binaryWriter.Write(bitsByte17);
                    break;
                }
                case 10:
                    NetMessage.CompressTileBlock(number, (int)number2, (short)number3, (short)number4, binaryWriter.BaseStream);
                    break;
                case 11:
                    binaryWriter.Write((short)number);
                    binaryWriter.Write((short)number2);
                    binaryWriter.Write((short)number3);
                    binaryWriter.Write((short)number4);
                    break;
                case 12:
                {
                    Player player2 = Main.player[number];
                    binaryWriter.Write((byte)number);
                    binaryWriter.Write((short)player2.SpawnX);
                    binaryWriter.Write((short)player2.SpawnY);
                    binaryWriter.Write(player2.respawnTimer);
                    binaryWriter.Write((short)player2.numberOfDeathsPVE);
                    binaryWriter.Write((short)player2.numberOfDeathsPVP);
                    binaryWriter.Write((byte)player2.team);
                    binaryWriter.Write((byte)number2);
                    break;
                }
                case 13:
                {
                    Player player3 = Main.player[number];
                    binaryWriter.Write((byte)number);
                    BitsByte bitsByte18 = 0;
                    bitsByte18[0] = player3.controlUp;
                    bitsByte18[1] = player3.controlDown;
                    bitsByte18[2] = player3.controlLeft;
                    bitsByte18[3] = player3.controlRight;
                    bitsByte18[4] = player3.controlJump;
                    bitsByte18[5] = player3.controlUseItem;
                    bitsByte18[6] = player3.direction == 1;
                    binaryWriter.Write(bitsByte18);
                    BitsByte bitsByte19 = 0;
                    bitsByte19[0] = player3.pulley;
                    bitsByte19[1] = player3.pulley && player3.pulleyDir == 2;
                    bitsByte19[2] = player3.velocity != Vector2.Zero;
                    bitsByte19[3] = player3.vortexStealthActive;
                    bitsByte19[4] = player3.gravDir == 1f;
                    bitsByte19[5] = player3.shieldRaised;
                    bitsByte19[6] = player3.ghost;
                    bitsByte19[7] = player3.mount.Active;
                    binaryWriter.Write(bitsByte19);
                    BitsByte bitsByte20 = 0;
                    bitsByte20[0] = player3.tryKeepingHoveringUp;
                    bitsByte20[1] = player3.IsVoidVaultEnabled;
                    bitsByte20[2] = player3.sitting.isSitting;
                    bitsByte20[3] = player3.downedDD2EventAnyDifficulty;
                    bitsByte20[4] = player3.petting.isPetting;
                    bitsByte20[5] = player3.petting.isPetSmall;
                    bitsByte20[6] = player3.PotionOfReturnOriginalUsePosition != null;
                    bitsByte20[7] = player3.tryKeepingHoveringDown;
                    binaryWriter.Write(bitsByte20);
                    BitsByte bitsByte21 = 0;
                    bitsByte21[0] = player3.sleeping.isSleeping;
                    bitsByte21[1] = player3.autoReuseAllWeapons;
                    bitsByte21[2] = player3.controlDownHold;
                    bitsByte21[3] = player3.isOperatingAnotherEntity;
                    bitsByte21[4] = player3.controlUseTile;
                    bitsByte21[5] = player3.netCameraTarget != null;
                    bitsByte21[6] = player3.lastItemUseAttemptSuccess;
                    binaryWriter.Write(bitsByte21);
                    binaryWriter.Write((byte)player3.selectedItem);
                    binaryWriter.WriteVector2(player3.position);
                    if (bitsByte19[2])
                    {
                        binaryWriter.WriteVector2(player3.velocity);
                    }
                    if (bitsByte19[7])
                    {
                        binaryWriter.Write((ushort)player3.mount.Type);
                    }
                    if (bitsByte20[6])
                    {
                        binaryWriter.WriteVector2(player3.PotionOfReturnOriginalUsePosition.Value);
                        binaryWriter.WriteVector2(player3.PotionOfReturnHomePosition.Value);
                    }
                    if (bitsByte21[5])
                    {
                        binaryWriter.WriteVector2(player3.netCameraTarget.Value);
                    }
                    if (player3 == Main.LocalPlayer)
                    {
                        player3.lastSyncedNetCameraTarget = player3.netCameraTarget;
                    }
                    break;
                }
                case 14:
                    binaryWriter.Write((byte)number);
                    binaryWriter.Write((byte)number2);
                    break;
                case 16:
                    binaryWriter.Write((byte)number);
                    binaryWriter.Write((short)Main.player[number].statLife);
                    binaryWriter.Write((short)Main.player[number].statLifeMax);
                    break;
                case 17:
                    binaryWriter.Write((byte)number);
                    binaryWriter.Write((short)number2);
                    binaryWriter.Write((short)number3);
                    binaryWriter.Write((short)number4);
                    binaryWriter.Write((byte)number5);
                    break;
                case 18:
                    binaryWriter.Write(Main.dayTime ? 1 : 0);
                    binaryWriter.Write((int)Main.time);
                    binaryWriter.Write(Main.sunModY);
                    binaryWriter.Write(Main.moonModY);
                    break;
                case 19:
                    binaryWriter.Write((byte)number);
                    binaryWriter.Write((short)number2);
                    binaryWriter.Write((short)number3);
                    binaryWriter.Write((number4 == 1f) ? 1 : 0);
                    break;
                case 20:
                {
                    int num3 = number;
                    int num4 = (int)number2;
                    int num5 = (int)number3;
                    if (num5 < 0)
                    {
                        num5 = 0;
                    }
                    int num6 = (int)number4;
                    if (num6 < 0)
                    {
                        num6 = 0;
                    }
                    if (num3 < num5)
                    {
                        num3 = num5;
                    }
                    if (num3 >= Main.maxTilesX + num5)
                    {
                        num3 = Main.maxTilesX - num5 - 1;
                    }
                    if (num4 < num6)
                    {
                        num4 = num6;
                    }
                    if (num4 >= Main.maxTilesY + num6)
                    {
                        num4 = Main.maxTilesY - num6 - 1;
                    }
                    binaryWriter.Write((short)num3);
                    binaryWriter.Write((short)num4);
                    binaryWriter.Write((byte)num5);
                    binaryWriter.Write((byte)num6);
                    binaryWriter.Write((byte)number5);
                    for (int m = num3; m < num3 + num5; m++)
                    {
                        for (int n = num4; n < num4 + num6; n++)
{
                            BitsByte bitsByte22 = 0;
                            BitsByte bitsByte23 = 0;
                            BitsByte bitsByte24 = 0;
                            byte b = 0;
                            byte b2 = 0;
                            Tile tile = Main.tile[m, n];
                            bitsByte22[0] = tile.active();
                            bitsByte22[2] = tile.wall > 0;
                            bitsByte22[3] = tile.liquid > 0 && Main.netMode == 2;
                            bitsByte22[4] = tile.wire();
                            bitsByte22[5] = tile.halfBrick();
                            bitsByte22[6] = tile.actuator();
                            bitsByte22[7] = tile.inActive();
                            bitsByte23[0] = tile.wire2();
                            bitsByte23[1] = tile.wire3();
                            if (tile.active() && tile.color() > 0)
{
                                bitsByte23[2] = true;
                                b = tile.color();
                            }
                            if (tile.wall > 0 && tile.wallColor() > 0)
{
                                bitsByte23[3] = true;
                                b2 = tile.wallColor();
                            }
                            bitsByte23 += (byte)(tile.slope() << 4);
                            bitsByte23[7] = tile.wire4();
                            bitsByte24[0] = tile.fullbrightBlock();
                            bitsByte24[1] = tile.fullbrightWall();
                            bitsByte24[2] = tile.invisibleBlock();
                            bitsByte24[3] = tile.invisibleWall();
                            binaryWriter.Write(bitsByte22);
                            binaryWriter.Write(bitsByte23);
                            binaryWriter.Write(bitsByte24);
                            if (b > 0)
{
                                binaryWriter.Write(b);
                            }
                            if (b2 > 0)
{
                                binaryWriter.Write(b2);
                            }
                            if (tile.active())
{
                                binaryWriter.Write(tile.type);
                                if (Main.tileFrameImportant[(int)tile.type])
{
                                    binaryWriter.Write(tile.frameX);
                                    binaryWriter.Write(tile.frameY);
                                }
                            }
                            if (tile.wall > 0)
{
                                binaryWriter.Write(tile.wall);
                            }
                            if (tile.liquid > 0 && Main.netMode == 2)
{
                                binaryWriter.Write(tile.liquid);
                                binaryWriter.Write(tile.liquidType());
                            }
                        }
                    }
                    break;
                }
                case 21:
                case 90:
                case 145:
                case 148:
                {
                    WorldItem worldItem = Main.item[number];
                    Item inner = worldItem.inner;
                    binaryWriter.Write((short)number);
                    binaryWriter.WriteVector2(worldItem.position);
                    binaryWriter.WriteVector2(worldItem.velocity);
                    binaryWriter.Write((short)inner.stack);
                    binaryWriter.Write(inner.prefix);
                    binaryWriter.Write((byte)number2);
                    short num7 = 0;
                    if (worldItem.active && worldItem.stack > 0)
                    {
                        num7 = (short)worldItem.type;
                    }
                    binaryWriter.Write(num7);
                    if (msgType == 145)
                    {
                        binaryWriter.Write(worldItem.shimmered);
                        binaryWriter.Write(worldItem.shimmerTime);
                    }
                    if (msgType == 148)
                    {
                        binaryWriter.Write((byte)MathHelper.Clamp((float)worldItem.timeLeftInWhichTheItemCannotBeTakenByEnemies, 0f, 255f));
                    }
                    break;
                }
                case 22:
                {
                    WorldItem worldItem2 = Main.item[number];
                    binaryWriter.Write((short)number);
                    binaryWriter.Write((byte)worldItem2.playerIndexTheItemIsReservedFor);
                    binaryWriter.WriteVector2(worldItem2.position);
                    break;
                }
                case 23:
                {
                    NPC npc = Main.npc[number];
                    binaryWriter.Write((short)number);
                    binaryWriter.WriteVector2(npc.position);
                    binaryWriter.WriteVector2(npc.velocity);
                    binaryWriter.Write((ushort)npc.target);
                    int num8 = npc.life;
                    if (!npc.active)
                    {
                        num8 = 0;
                    }
                    short num9 = (short)npc.netID;
                    bool[] array = new bool[4];
                    BitsByte bitsByte25 = 0;
                    bitsByte25[0] = npc.direction > 0;
                    bitsByte25[1] = npc.directionY > 0;
                    bitsByte25[2] = (array[0] = npc.ai[0] != 0f);
                    bitsByte25[3] = (array[1] = npc.ai[1] != 0f);
                    bitsByte25[4] = (array[2] = npc.ai[2] != 0f);
                    bitsByte25[5] = (array[3] = npc.ai[3] != 0f);
                    bitsByte25[6] = npc.spriteDirection > 0;
                    bitsByte25[7] = num8 == npc.lifeMax;
                    binaryWriter.Write(bitsByte25);
                    BitsByte bitsByte26 = 0;
                    bitsByte26[0] = npc.statsAreScaledForThisManyPlayers > 1;
                    bitsByte26[1] = npc.SpawnedFromStatue;
                    bitsByte26[2] = npc.difficulty != 1f;
                    bitsByte26[3] = npc.spawnNeedsSyncing;
                    bitsByte26[4] = npc.spawnNeedsSyncing && npc.shimmerTransparency > 0f;
                    binaryWriter.Write(bitsByte26);
                    for (int num10 = 0; num10 < NPC.maxAI; num10++)
                    {
                        if (array[num10])
{
                            binaryWriter.Write(npc.ai[num10]);
                        }
                    }
                    binaryWriter.Write(num9);
                    if (bitsByte26[0])
                    {
                        binaryWriter.Write((byte)npc.statsAreScaledForThisManyPlayers);
                    }
                    if (bitsByte26[2])
                    {
                        binaryWriter.Write(npc.difficulty);
                    }
                    if (!bitsByte25[7])
                    {
                        byte b3 = 1;
                        if (npc.lifeMax > 32767)
{
                            b3 = 4;
                        }
                        else if (npc.lifeMax > 127)
{
                            b3 = 2;
                        }
                        binaryWriter.Write(b3);
                        if (b3 == 2)
{
                            binaryWriter.Write((short)num8);
                        }
                        else if (b3 == 4)
{
                            binaryWriter.Write(num8);
                        }
                        else
{
                            binaryWriter.Write((sbyte)num8);
                        }
                    }
                    if (npc.type >= 0 && npc.type < (int)NPCID.Count && Main.npcCatchable[npc.type])
                    {
                        binaryWriter.Write((byte)npc.releaseOwner);
                    }
                    break;
                }
                case 24:
                    binaryWriter.Write((short)number);
                    binaryWriter.Write((byte)number2);
                    break;
                case 27:
                {
                    Projectile projectile = Main.projectile[number];
                    binaryWriter.Write((short)projectile.identity);
                    binaryWriter.WriteVector2(projectile.position);
                    binaryWriter.WriteVector2(projectile.velocity);
                    binaryWriter.Write((byte)projectile.owner);
                    binaryWriter.Write((short)projectile.type);
                    BitsByte bitsByte27 = 0;
                    BitsByte bitsByte28 = 0;
                    bitsByte27[0] = projectile.ai[0] != 0f;
                    bitsByte27[1] = projectile.ai[1] != 0f;
                    bitsByte28[0] = projectile.ai[2] != 0f;
                    if (projectile.bannerIdToRespondTo != 0)
                    {
                        bitsByte27[3] = true;
                    }
                    if (projectile.damage != 0)
                    {
                        bitsByte27[4] = true;
                    }
                    if (projectile.knockBack != 0f)
                    {
                        bitsByte27[5] = true;
                    }
                    if (projectile.type > 0 && projectile.type < (int)ProjectileID.Count && ProjectileID.Sets.NeedsUUID[projectile.type])
                    {
                        bitsByte27[7] = true;
                    }
                    if (projectile.originalDamage != 0)
                    {
                        bitsByte27[6] = true;
                    }
                    if (bitsByte28 != 0)
                    {
                        bitsByte27[2] = true;
                    }
                    binaryWriter.Write(bitsByte27);
                    if (bitsByte27[2])
                    {
                        binaryWriter.Write(bitsByte28);
                    }
                    if (bitsByte27[0])
                    {
                        binaryWriter.Write(projectile.ai[0]);
                    }
                    if (bitsByte27[1])
                    {
                        binaryWriter.Write(projectile.ai[1]);
                    }
                    if (bitsByte27[3])
                    {
                        binaryWriter.Write((ushort)projectile.bannerIdToRespondTo);
                    }
                    if (bitsByte27[4])
                    {
                        binaryWriter.Write((short)projectile.damage);
                    }
                    if (bitsByte27[5])
                    {
                        binaryWriter.Write(projectile.knockBack);
                    }
                    if (bitsByte27[6])
                    {
                        binaryWriter.Write((short)projectile.originalDamage);
                    }
                    if (bitsByte27[7])
                    {
                        binaryWriter.Write((short)projectile.projUUID);
                    }
                    if (bitsByte28[0])
                    {
                        binaryWriter.Write(projectile.ai[2]);
                    }
                    break;
                }
                case 28:
                    binaryWriter.Write((short)number);
                    binaryWriter.Write((short)number2);
                    binaryWriter.Write(number3);
                    binaryWriter.Write((byte)(number4 + 1f));
                    binaryWriter.Write((byte)number5);
                    break;
                case 29:
                    binaryWriter.Write((short)number);
                    binaryWriter.Write((byte)number2);
                    break;
                case 30:
                    binaryWriter.Write((byte)number);
                    binaryWriter.Write(Main.player[number].hostile);
                    break;
                case 31:
                    binaryWriter.Write((short)number);
                    binaryWriter.Write((short)number2);
                    break;
                case 32:
                {
                    Item item2 = Main.chest[number].item[(int)((byte)number2)];
                    binaryWriter.Write((short)number);
                    binaryWriter.Write((byte)number2);
                    short num11 = (short)item2.type;
                    if (item2.Name == null)
                    {
                        num11 = 0;
                    }
                    binaryWriter.Write((short)item2.stack);
                    binaryWriter.Write(item2.prefix);
                    binaryWriter.Write(num11);
                    break;
                }
                case 33:
                {
                    int num12 = 0;
                    int num13 = 0;
                    int num14 = 0;
                    string text2 = null;
                    if (number > -1)
                    {
                        num12 = Main.chest[number].x;
                        num13 = Main.chest[number].y;
                    }
                    if (number2 == 1f)
                    {
                        string text3 = text.ToString();
                        num14 = (int)((byte)text3.Length);
                        if (num14 == 0 || num14 > 20)
{
                            num14 = 255;
                        }
                        else
{
                            text2 = text3;
                        }
                    }
                    binaryWriter.Write((short)number);
                    binaryWriter.Write((short)num12);
                    binaryWriter.Write((short)num13);
                    binaryWriter.Write((byte)num14);
                    if (text2 != null)
                    {
                        binaryWriter.Write(text2);
                    }
                    break;
                }
                case 34:
                    binaryWriter.Write((byte)number);
                    binaryWriter.Write((short)number2);
                    binaryWriter.Write((short)number3);
                    binaryWriter.Write((short)number4);
                    if (Main.netMode == 2)
                    {
                        Netplay.GetSectionX((int)number2);
                        Netplay.GetSectionY((int)number3);
                        binaryWriter.Write((short)number5);
                    }
                    else
                    {
                        binaryWriter.Write(0);
                    }
                    break;
                case 35:
                    binaryWriter.Write((byte)number);
                    binaryWriter.Write((short)number2);
                    break;
                case 36:
                {
                    Player player4 = Main.player[number];
                    binaryWriter.Write((byte)number);
                    binaryWriter.Write(player4.zone1);
                    binaryWriter.Write(player4.zone2);
                    binaryWriter.Write(player4.zone3);
                    binaryWriter.Write(player4.zone4);
                    binaryWriter.Write(player4.zone5);
                    binaryWriter.Write((byte)player4.townNPCs);
                    break;
                }
                case 38:
                    binaryWriter.Write(Netplay.ServerPassword);
                    break;
                case 39:
                    binaryWriter.Write((short)number);
                    break;
                case 40:
                    binaryWriter.Write((byte)number);
                    binaryWriter.Write((short)Main.player[number].talkNPC);
                    break;
                case 41:
                    binaryWriter.Write((byte)number);
                    binaryWriter.Write(Main.player[number].itemRotation);
                    binaryWriter.Write((short)Main.player[number].itemAnimation);
                    break;
                case 42:
                    binaryWriter.Write((byte)number);
                    binaryWriter.Write((short)Main.player[number].statMana);
                    binaryWriter.Write((short)Main.player[number].statManaMax);
                    break;
                case 43:
                    binaryWriter.Write((byte)number);
                    binaryWriter.Write((short)number2);
                    break;
                case 45:
                case 157:
                    binaryWriter.Write((byte)number);
                    binaryWriter.Write((byte)Main.player[number].team);
                    break;
                case 46:
                    binaryWriter.Write((short)number);
                    binaryWriter.Write((short)number2);
                    break;
                case 47:
                    binaryWriter.Write((short)number);
                    binaryWriter.Write((short)Main.sign[number].x);
                    binaryWriter.Write((short)Main.sign[number].y);
                    binaryWriter.Write(Main.sign[number].text);
                    binaryWriter.Write((byte)number2);
                    binaryWriter.Write((byte)number3);
                    break;
                case 48:
                {
                    Tile tile2 = Main.tile[number, (int)number2];
                    binaryWriter.Write((short)number);
                    binaryWriter.Write((short)number2);
                    binaryWriter.Write(tile2.liquid);
                    binaryWriter.Write(tile2.liquidType());
                    break;
                }
                case 50:
                {
                    binaryWriter.Write((byte)number);
                    Player player5 = Main.player[number];
                    for (int num15 = 0; num15 < Player.maxBuffs; num15++)
                    {
                        if (player5.buffType[num15] > 0)
{
                            binaryWriter.Write((ushort)player5.buffType[num15]);
                        }
                    }
                    binaryWriter.Write(0);
                    break;
                }
                case 51:
                    binaryWriter.Write((byte)number);
                    binaryWriter.Write((byte)number2);
                    break;
                case 52:
                    binaryWriter.Write((byte)number2);
                    binaryWriter.Write((short)number3);
                    binaryWriter.Write((short)number4);
                    break;
                case 53:
                    binaryWriter.Write((short)number);
                    binaryWriter.Write((ushort)number2);
                    binaryWriter.Write((short)number3);
                    break;
                case 54:
                {
                    NPC npc2 = Main.npc[number];
                    binaryWriter.Write((short)number);
                    for (int num16 = 0; num16 < NPC.maxBuffs; num16++)
                    {
                        int num17 = npc2.buffType[num16];
                        int num18 = npc2.buffTime[num16];
                        if (num17 > 0 && num18 > 0)
{
                            binaryWriter.Write((ushort)num17);
                            binaryWriter.Write((ushort)num18);
                        }
                    }
                    binaryWriter.Write(0);
                    break;
                }
                case 55:
                    binaryWriter.Write((byte)number);
                    binaryWriter.Write((ushort)number2);
                    binaryWriter.Write((int)number3);
                    break;
                case 56:
                    binaryWriter.Write((short)number);
                    if (Main.netMode == 2)
                    {
                        string givenName = Main.npc[number].GivenName;
                        binaryWriter.Write(givenName);
                        binaryWriter.Write(Main.npc[number].townNpcVariationIndex);
                    }
                    break;
                case 57:
                    binaryWriter.Write(WorldGen.tGood);
                    binaryWriter.Write(WorldGen.tEvil);
                    binaryWriter.Write(WorldGen.tBlood);
                    break;
                case 58:
                    binaryWriter.Write((byte)number);
                    binaryWriter.Write(number2);
                    break;
                case 59:
                    binaryWriter.Write((short)number);
                    binaryWriter.Write((short)number2);
                    break;
                case 60:
                    binaryWriter.Write((short)number);
                    binaryWriter.Write((short)number2);
                    binaryWriter.Write((short)number3);
                    binaryWriter.Write((byte)number4);
                    break;
                case 61:
                    binaryWriter.Write((short)number);
                    binaryWriter.Write((short)number2);
                    break;
                case 62:
                    binaryWriter.Write((byte)number);
                    binaryWriter.Write((byte)number2);
                    break;
                case 63:
                case 64:
                    binaryWriter.Write((short)number);
                    binaryWriter.Write((short)number2);
                    binaryWriter.Write((byte)number3);
                    binaryWriter.Write((byte)number4);
                    break;
                case 65:
                {
                    BitsByte bitsByte29 = 0;
                    bitsByte29[0] = (number & 1) == 1;
                    bitsByte29[1] = (number & 2) == 2;
                    bitsByte29[2] = number6 == 1;
                    bitsByte29[3] = number7 != 0;
                    binaryWriter.Write(bitsByte29);
                    binaryWriter.Write((short)number2);
                    binaryWriter.Write(number3);
                    binaryWriter.Write(number4);
                    binaryWriter.Write((byte)number5);
                    if (bitsByte29[3])
                    {
                        binaryWriter.Write(number7);
                    }
                    if (Main.netMode == 2 && number == 0 && number2 != (float)ignoreClient)
                    {
                        Main.player[(int)number2].unacknowledgedTeleports++;
                    }
                    break;
                }
                case 66:
                    binaryWriter.Write((byte)number);
                    binaryWriter.Write((short)number2);
                    break;
                case 68:
                    binaryWriter.Write(Main.clientUUID);
                    break;
                case 69:
                    Netplay.GetSectionX((int)number2);
                    Netplay.GetSectionY((int)number3);
                    binaryWriter.Write((short)number);
                    binaryWriter.Write((short)number2);
                    binaryWriter.Write((short)number3);
                    binaryWriter.Write(Main.chest[(int)((short)number)].name);
                    break;
                case 70:
                    binaryWriter.Write((short)number);
                    binaryWriter.Write((byte)number2);
                    break;
                case 71:
                    binaryWriter.Write(number);
                    binaryWriter.Write((int)number2);
                    binaryWriter.Write((short)number3);
                    binaryWriter.Write((byte)number4);
                    break;
                case 72:
                {
                    for (int num19 = 0; num19 < Main.TravelShopMaxSlots; num19++)
                    {
                        binaryWriter.Write((short)Main.travelShop[num19]);
                    }
                    break;
                }
                case 73:
                    binaryWriter.Write((byte)number);
                    break;
                case 74:
                {
                    binaryWriter.Write((byte)Main.anglerQuest);
                    bool flag2 = Main.anglerWhoFinishedToday.Contains(text.ToString());
                    binaryWriter.Write(flag2);
                    break;
                }
                case 76:
                    binaryWriter.Write((byte)number);
                    binaryWriter.Write(Main.player[number].anglerQuestsFinished);
                    binaryWriter.Write(Main.player[number].golferScoreAccumulated);
                    break;
                case 77:
                    binaryWriter.Write((short)number);
                    binaryWriter.Write((ushort)number2);
                    binaryWriter.Write((short)number3);
                    binaryWriter.Write((short)number4);
                    break;
                case 78:
                    binaryWriter.Write(number);
                    binaryWriter.Write((int)number2);
                    binaryWriter.Write((sbyte)number3);
                    binaryWriter.Write((sbyte)number4);
                    break;
                case 79:
                    binaryWriter.Write((short)number);
                    binaryWriter.Write((short)number2);
                    binaryWriter.Write((short)number3);
                    binaryWriter.Write((short)number4);
                    binaryWriter.Write((byte)number5);
                    binaryWriter.Write((sbyte)number6);
                    binaryWriter.Write(number7 == 1);
                    break;
                case 80:
                    binaryWriter.Write((byte)number);
                    binaryWriter.Write((short)number2);
                    break;
                case 81:
                    binaryWriter.Write(number2);
                    binaryWriter.Write(number3);
                    binaryWriter.WriteRGB(new Color
                    {
                        PackedValue = (uint)number
                    });
                    binaryWriter.Write((int)number4);
                    break;
                case 84:
                {
                    byte b4 = (byte)number;
                    float stealth = Main.player[(int)b4].stealth;
                    binaryWriter.Write(b4);
                    binaryWriter.Write(stealth);
                    break;
                }
                case 85:
                    if (Main.netMode == 1)
                    {
                        QuickStacking.WriteNetInventorySlots(binaryWriter);
                        binaryWriter.Write((byte)number);
                    }
                    else
                    {
                        QuickStacking.WriteBlockedChestList(binaryWriter);
                    }
                    break;
                case 86:
                {
                    binaryWriter.Write(number);
                    TileEntity tileEntity;
                    bool flag3 = TileEntity.TryGet<TileEntity>(number, out tileEntity);
                    binaryWriter.Write(flag3);
                    if (flag3)
                    {
                        TileEntity.Write(binaryWriter, tileEntity, true);
                    }
                    break;
                }
                case 87:
                    binaryWriter.Write((short)number);
                    binaryWriter.Write((short)number2);
                    binaryWriter.Write((byte)number3);
                    break;
                case 88:
                {
                    BitsByte bitsByte30 = (byte)number2;
                    BitsByte bitsByte31 = (byte)number3;
                    binaryWriter.Write((short)number);
                    binaryWriter.Write(bitsByte30);
                    WorldItem worldItem3 = Main.item[number];
                    if (bitsByte30[0])
                    {
                        binaryWriter.Write(worldItem3.color.PackedValue);
                    }
                    if (bitsByte30[1])
                    {
                        binaryWriter.Write((ushort)worldItem3.damage);
                    }
                    if (bitsByte30[2])
                    {
                        binaryWriter.Write(worldItem3.knockBack);
                    }
                    if (bitsByte30[3])
                    {
                        binaryWriter.Write((ushort)worldItem3.useAnimation);
                    }
                    if (bitsByte30[4])
                    {
                        binaryWriter.Write((ushort)worldItem3.useTime);
                    }
                    if (bitsByte30[5])
                    {
                        binaryWriter.Write((short)worldItem3.shoot);
                    }
                    if (bitsByte30[6])
                    {
                        binaryWriter.Write(worldItem3.shootSpeed);
                    }
                    if (bitsByte30[7])
                    {
                        binaryWriter.Write(bitsByte31);
                        if (bitsByte31[0])
{
                            binaryWriter.Write((ushort)worldItem3.width);
                        }
                        if (bitsByte31[1])
{
                            binaryWriter.Write((ushort)worldItem3.height);
                        }
                        if (bitsByte31[2])
{
                            binaryWriter.Write(worldItem3.scale);
                        }
                        if (bitsByte31[3])
{
                            binaryWriter.Write((short)worldItem3.ammo);
                        }
                        if (bitsByte31[4])
{
                            binaryWriter.Write((short)worldItem3.useAmmo);
                        }
                        if (bitsByte31[5])
{
                            binaryWriter.Write(worldItem3.notAmmo);
                        }
                    }
                    break;
                }
                case 89:
                {
                    binaryWriter.Write((short)number);
                    binaryWriter.Write((short)number2);
                    Item item3 = Main.player[(int)number4].inventory[(int)number3];
                    binaryWriter.Write((short)item3.type);
                    binaryWriter.Write(item3.prefix);
                    binaryWriter.Write((short)number5);
                    break;
                }
                case 91:
                    binaryWriter.Write(number);
                    binaryWriter.Write((byte)number2);
                    if (number2 != 255f)
                    {
                        binaryWriter.Write((ushort)number3);
                        binaryWriter.Write((ushort)number4);
                        binaryWriter.Write((byte)number5);
                        if (number5 < 0)
{
                            binaryWriter.Write((short)number6);
                        }
                    }
                    break;
                case 92:
                    binaryWriter.Write((short)number);
                    binaryWriter.Write((int)number2);
                    binaryWriter.Write(number3);
                    binaryWriter.Write(number4);
                    break;
                case 95:
                    binaryWriter.Write((ushort)number);
                    binaryWriter.Write((byte)number2);
                    break;
                case 96:
                {
                    binaryWriter.Write((byte)number);
                    Player player6 = Main.player[number];
                    binaryWriter.Write((short)number4);
                    binaryWriter.Write(number2);
                    binaryWriter.Write(number3);
                    binaryWriter.WriteVector2(player6.velocity);
                    break;
                }
                case 97:
                    binaryWriter.Write((short)number);
                    break;
                case 98:
                    binaryWriter.Write((short)number);
                    break;
                case 99:
                    binaryWriter.Write((byte)number);
                    binaryWriter.WriteVector2(Main.player[number].MinionRestTargetPoint);
                    break;
                case 100:
                {
                    binaryWriter.Write((ushort)number);
                    NPC npc3 = Main.npc[number];
                    binaryWriter.Write((short)number4);
                    binaryWriter.Write(number2);
                    binaryWriter.Write(number3);
                    binaryWriter.WriteVector2(npc3.velocity);
                    break;
                }
                case 101:
                    binaryWriter.Write((ushort)NPC.ShieldStrengthTowerSolar);
                    binaryWriter.Write((ushort)NPC.ShieldStrengthTowerVortex);
                    binaryWriter.Write((ushort)NPC.ShieldStrengthTowerNebula);
                    binaryWriter.Write((ushort)NPC.ShieldStrengthTowerStardust);
                    break;
                case 102:
                    binaryWriter.Write((byte)number);
                    binaryWriter.Write((ushort)number2);
                    binaryWriter.Write(number3);
                    binaryWriter.Write(number4);
                    break;
                case 103:
                    binaryWriter.Write(NPC.MaxMoonLordCountdown);
                    binaryWriter.Write(NPC.MoonLordCountdown);
                    break;
                case 104:
                    binaryWriter.Write((byte)number);
                    binaryWriter.Write((short)number2);
                    binaryWriter.Write(((short)number3 < 0) ? 0f : number3);
                    binaryWriter.Write((byte)number4);
                    binaryWriter.Write(number5);
                    binaryWriter.Write((byte)number6);
                    break;
                case 105:
                    binaryWriter.Write((short)number);
                    binaryWriter.Write((short)number2);
                    binaryWriter.Write(number3 == 1f);
                    break;
                case 106:
                {
                    HalfVector2 halfVector = new HalfVector2((float)number, number2);
                    binaryWriter.Write(halfVector.PackedValue);
                    break;
                }
                case 107:
                    binaryWriter.Write((byte)number2);
                    binaryWriter.Write((byte)number3);
                    binaryWriter.Write((byte)number4);
                    text.Serialize(binaryWriter);
                    binaryWriter.Write((short)number5);
                    break;
                case 108:
                    binaryWriter.Write((short)number);
                    binaryWriter.Write(number2);
                    binaryWriter.Write((short)number3);
                    binaryWriter.Write((short)number4);
                    binaryWriter.Write((short)number5);
                    binaryWriter.Write((short)number6);
                    binaryWriter.Write((byte)number7);
                    break;
                case 109:
                    binaryWriter.Write((short)number);
                    binaryWriter.Write((short)number2);
                    binaryWriter.Write((short)number3);
                    binaryWriter.Write((short)number4);
                    binaryWriter.Write((byte)number5);
                    break;
                case 110:
                    binaryWriter.Write((short)number);
                    binaryWriter.Write((short)number2);
                    binaryWriter.Write((byte)number3);
                    break;
                case 112:
                    binaryWriter.Write((byte)number);
                    binaryWriter.Write((int)number2);
                    binaryWriter.Write((int)number3);
                    binaryWriter.Write((byte)number4);
                    binaryWriter.Write((short)number5);
                    binaryWriter.Write((byte)number6);
                    break;
                case 113:
                    binaryWriter.Write((short)number);
                    binaryWriter.Write((short)number2);
                    break;
                case 115:
                    binaryWriter.Write((byte)number);
                    binaryWriter.Write((short)Main.player[number].MinionAttackTargetNPC);
                    break;
                case 116:
                    binaryWriter.Write(number);
                    break;
                case 117:
                    binaryWriter.Write((byte)number);
                    NetMessage._currentPlayerDeathReason.WriteSelfTo(binaryWriter);
                    binaryWriter.Write((short)number2);
                    binaryWriter.Write((byte)(number3 + 1f));
                    binaryWriter.Write((byte)number4);
                    binaryWriter.Write((sbyte)number5);
                    break;
                case 118:
                    binaryWriter.Write((byte)number);
                    NetMessage._currentPlayerDeathReason.WriteSelfTo(binaryWriter);
                    binaryWriter.Write((short)number2);
                    binaryWriter.Write((byte)(number3 + 1f));
                    binaryWriter.Write((byte)number4);
                    break;
                case 119:
                    binaryWriter.Write(number2);
                    binaryWriter.Write(number3);
                    binaryWriter.WriteRGB(new Color
                    {
                        PackedValue = (uint)number
                    });
                    text.Serialize(binaryWriter);
                    break;
                case 120:
                    binaryWriter.Write((byte)number);
                    binaryWriter.Write((byte)number2);
                    break;
                case 121:
                {
                    int num20 = (int)number3;
                    binaryWriter.Write((byte)number);
                    binaryWriter.Write((int)number2);
                    binaryWriter.Write((byte)num20);
                    binaryWriter.Write((byte)number4);
                    TEDisplayDoll tedisplayDoll;
                    if (TileEntity.TryGet<TEDisplayDoll>((int)number2, out tedisplayDoll))
                    {
                        tedisplayDoll.WriteData((int)number3, (int)number4, binaryWriter);
                    }
                    else
                    {
                        TEDisplayDoll.WriteDummySync((int)number3, (int)number4, binaryWriter);
                    }
                    break;
                }
                case 122:
                    binaryWriter.Write(number);
                    binaryWriter.Write((byte)number2);
                    break;
                case 123:
                {
                    binaryWriter.Write((short)number);
                    binaryWriter.Write((short)number2);
                    Item item4 = Main.player[(int)number4].inventory[(int)number3];
                    binaryWriter.Write((short)item4.type);
                    binaryWriter.Write(item4.prefix);
                    binaryWriter.Write((short)number5);
                    break;
                }
                case 124:
                {
                    int num21 = (int)number3;
                    bool flag4 = number4 == 1f;
                    if (flag4)
                    {
                        num21 += 2;
                    }
                    binaryWriter.Write((byte)number);
                    binaryWriter.Write((int)number2);
                    binaryWriter.Write((byte)num21);
                    TEHatRack tehatRack;
                    if (TileEntity.TryGet<TEHatRack>((int)number2, out tehatRack))
                    {
                        tehatRack.WriteItem((int)number3, binaryWriter, flag4);
                    }
                    else
                    {
                        binaryWriter.Write(0);
                        binaryWriter.Write(0);
                    }
                    break;
                }
                case 125:
                    binaryWriter.Write((byte)number);
                    binaryWriter.Write((short)number2);
                    binaryWriter.Write((short)number3);
                    binaryWriter.Write((byte)number4);
                    break;
                case 126:
                    NetMessage._currentRevengeMarker.WriteSelfTo(binaryWriter);
                    break;
                case 127:
                    binaryWriter.Write(number);
                    break;
                case 128:
                    binaryWriter.Write((byte)number);
                    binaryWriter.Write((ushort)number5);
                    binaryWriter.Write((ushort)number6);
                    binaryWriter.Write((ushort)number2);
                    binaryWriter.Write((ushort)number3);
                    break;
                case 130:
                    binaryWriter.Write((ushort)number);
                    binaryWriter.Write((ushort)number2);
                    binaryWriter.Write((short)number3);
                    break;
                case 131:
                {
                    binaryWriter.Write((ushort)number);
                    binaryWriter.Write((byte)number2);
                    byte b5 = (byte)number2;
                    if (b5 == 1)
                    {
                        binaryWriter.Write((int)number3);
                        binaryWriter.Write((short)number4);
                    }
                    break;
                }
                case 132:
                    NetMessage._currentNetSoundInfo.WriteSelfTo(binaryWriter);
                    break;
                case 133:
                {
                    binaryWriter.Write((short)number);
                    binaryWriter.Write((short)number2);
                    Item item5 = Main.player[(int)number4].inventory[(int)number3];
                    binaryWriter.Write((short)item5.type);
                    binaryWriter.Write(item5.prefix);
                    binaryWriter.Write((short)number5);
                    break;
                }
                case 134:
                {
                    binaryWriter.Write((byte)number);
                    Player player7 = Main.player[number];
                    binaryWriter.Write(player7.ladyBugLuckTimeLeft);
                    binaryWriter.Write(player7.torchLuck);
                    binaryWriter.Write(player7.luckPotion);
                    binaryWriter.Write(player7.HasGardenGnomeNearby);
                    binaryWriter.Write(player7.brokenMirrorBadLuck);
                    binaryWriter.Write(player7.equipmentBasedLuckBonus);
                    binaryWriter.Write(player7.coinLuck);
                    binaryWriter.Write(player7.kiteLuckLevel);
                    break;
                }
                case 135:
                    binaryWriter.Write((byte)number);
                    break;
                case 136:
                {
                    for (int num22 = 0; num22 < 2; num22++)
                    {
                        for (int num23 = 0; num23 < 3; num23++)
{
                            binaryWriter.Write((ushort)NPC.cavernMonsterType[num22, num23]);
                        }
                    }
                    break;
                }
                case 137:
                    binaryWriter.Write((short)number);
                    binaryWriter.Write((ushort)number2);
                    break;
                case 139:
                {
                    binaryWriter.Write((byte)number);
                    bool flag5 = number2 == 1f;
                    binaryWriter.Write(flag5);
                    break;
                }
                case 140:
                    binaryWriter.Write((byte)number);
                    binaryWriter.Write((int)number2);
                    break;
                case 141:
                    binaryWriter.Write((byte)number);
                    binaryWriter.Write((byte)number2);
                    binaryWriter.Write(number3);
                    binaryWriter.Write(number4);
                    binaryWriter.Write(number5);
                    binaryWriter.Write(number6);
                    break;
                case 142:
                {
                    binaryWriter.Write((byte)number);
                    Player player8 = Main.player[number];
                    player8.piggyBankProjTracker.Write(binaryWriter);
                    player8.voidLensChest.Write(binaryWriter);
                    break;
                }
                case 146:
                    binaryWriter.Write((byte)number);
                    if (number == 0)
                    {
                        binaryWriter.WriteVector2(new Vector2((float)((int)number2), (float)((int)number3)));
                    }
                    else if (number == 1)
                    {
                        binaryWriter.WriteVector2(new Vector2((float)((int)number2), (float)((int)number3)));
                        binaryWriter.Write((int)number4);
                    }
                    break;
                case 147:
                    binaryWriter.Write((byte)number);
                    binaryWriter.Write((byte)number2);
                    NetMessage.WriteAccessoryVisibility(binaryWriter, Main.player[number].hideVisibleAccessory);
                    break;
                case 149:
                {
                    binaryWriter.Write((short)number);
                    binaryWriter.Write((short)number2);
                    Item item6 = Main.player[(int)number4].inventory[(int)number3];
                    binaryWriter.Write((short)item6.type);
                    binaryWriter.Write(item6.prefix);
                    binaryWriter.Write((short)number5);
                    break;
                }
                case 150:
                    binaryWriter.Write((byte)number);
                    binaryWriter.Write((short)number2);
                    break;
                case 151:
                    Main.item[number].playerIndexTheItemIsReservedFor = 255;
                    binaryWriter.Write((short)number);
                    break;
                case 152:
                    binaryWriter.Write((byte)number);
                    break;
                case 153:
                    binaryWriter.Write((byte)number);
                    binaryWriter.Write((short)number2);
                    break;
                case 155:
                    binaryWriter.Write((short)number);
                    binaryWriter.Write((short)number2);
                    break;
                case 156:
                    binaryWriter.Write((short)number);
                    binaryWriter.Write((short)number2);
                    binaryWriter.Write((short)number3);
                    break;
                case 158:
                    binaryWriter.Write((byte)number);
                    break;
                case 159:
                    binaryWriter.Write((short)number);
                    binaryWriter.Write((short)number2);
                    break;
                case 160:
                {
                    WorldItem worldItem4 = Main.item[number];
                    binaryWriter.Write((short)number);
                    binaryWriter.WriteVector2(worldItem4.position);
                    break;
                }
                case 161:
                    binaryWriter.Write(text.ToString());
                    break;
                }
                int num24 = (int)binaryWriter.BaseStream.Position;
                if (num24 > 65535)
                {
                    throw new Exception(string.Concat(new object[] { "Maximum packet length exceeded. id: ", msgType, " length: ", num24 }));
                }
                binaryWriter.BaseStream.Position = position;
                binaryWriter.Write((ushort)num24);
                binaryWriter.BaseStream.Position = (long)num24;
                if (Main.netMode == 1)
                {
                    if (Netplay.Connection.IsConnected())
                    {
                        NetMessage.SendPacketToServer(NetMessage.buffer[num].writeBuffer);
                    }
                }
                else if (remoteClient == -1)
                {
                    if (msgType == 34 || msgType == 69)
                    {
                        for (int num25 = 0; num25 < 256; num25++)
{
                            if (num25 != ignoreClient && NetMessage.buffer[num25].broadcast && Netplay.Clients[num25].IsConnected())
{
                                NetMessage.SendPacket(NetMessage.buffer[num].writeBuffer, num25);
                            }
                        }
                    }
                    else if (msgType == 20)
                    {
                        for (int num26 = 0; num26 < 256; num26++)
{
                            if (num26 != ignoreClient && NetMessage.buffer[num26].broadcast && Netplay.Clients[num26].IsConnected() && Netplay.Clients[num26].SectionRange((int)Math.Max(number3, number4), number, (int)number2))
{
                                NetMessage.SendPacket(NetMessage.buffer[num].writeBuffer, num26);
                            }
                        }
                    }
                    else if (msgType == 23)
                    {
                        NPC npc4 = Main.npc[number];
                        bool flag6 = npc4.boss || npc4.netAlways || npc4.townNPC || !npc4.active || npc4.life <= 0 || npc4.spawnNeedsSyncing;
                        if (flag6)
{
                            npc4.spawnNeedsSyncing = false;
                            npc4.netStream = 0;
                            npc4.netUpdate = false;
                            npc4.netUpdatePendingSpamCooldown = false;
                            npc4.netUpdatePendingFullSpamCooldown = false;
                            Array.Clear(npc4.playerNetSyncState, 0, npc4.playerNetSyncState.Length);
                        }
                        for (int num27 = 0; num27 < 256; num27++)
{
                            if (num27 != ignoreClient && NetMessage.buffer[num27].broadcast && Netplay.Clients[num27].IsConnected())
{
                                if (!flag6)
{
                                    if (npc4.playerNetSyncState[num27].skippedSyncs < 4 && !Netplay.Clients[num27].IsSectionActive(npc4.NetSectionCoordinates))
{
                                        NPC.PlayerNetSyncState[] playerNetSyncState = npc4.playerNetSyncState;
                                        int num28 = num27;
                                        playerNetSyncState[num28].skippedSyncs = playerNetSyncState[num28].skippedSyncs + 1;
                                        goto IL_3526;
                                    }
                                    npc4.playerNetSyncState[num27] = default(NPC.PlayerNetSyncState);
                                }
                                NetMessage.SendPacket(NetMessage.buffer[num].writeBuffer, num27);
                            }
                            IL_3526:;
                        }
                    }
                    else if (msgType == 28)
                    {
                        NPC npc5 = Main.npc[number];
                        for (int num29 = 0; num29 < 256; num29++)
{
                            if (num29 != ignoreClient && NetMessage.buffer[num29].broadcast && Netplay.Clients[num29].IsConnected() && (npc5.life <= 0 || Netplay.Clients[num29].IsSectionActive(npc5.NetSectionCoordinates)))
{
                                NetMessage.SendPacket(NetMessage.buffer[num].writeBuffer, num29);
                            }
                        }
                    }
                    else if (msgType == 13)
                    {
                        for (int num30 = 0; num30 < 256; num30++)
{
                            if (num30 != ignoreClient && NetMessage.buffer[num30].broadcast && Netplay.Clients[num30].IsConnected())
{
                                NetMessage.SendPacket(NetMessage.buffer[num].writeBuffer, num30);
                            }
                        }
                    }
                    else if (msgType == 27)
                    {
                        Projectile projectile2 = Main.projectile[number];
                        bool flag7 = projectile2.type == 12 || Main.projPet[projectile2.type] || projectile2.aiStyle == 11 || projectile2.netImportant;
                        if (flag7)
{
                            Array.Clear(projectile2.netSyncSkippedForPlayer, 0, projectile2.netSyncSkippedForPlayer.Length);
                        }
                        for (int num31 = 0; num31 < 256; num31++)
{
                            if (num31 != ignoreClient && NetMessage.buffer[num31].broadcast && Netplay.Clients[num31].IsConnected())
{
                                if (!flag7)
{
                                    if (!Netplay.Clients[num31].IsSectionActive(projectile2.NetSectionCoordinates))
{
                                        projectile2.netSyncSkippedForPlayer[num31] = true;
                                        goto IL_36DC;
                                    }
                                    projectile2.netSyncSkippedForPlayer[num31] = false;
                                }
                                NetMessage.SendPacket(NetMessage.buffer[num].writeBuffer, num31);
                            }
                            IL_36DC:;
                        }
                    }
                    else
                    {
                        for (int num32 = 0; num32 < 256; num32++)
{
                            if (num32 != ignoreClient && (NetMessage.buffer[num32].broadcast || (Netplay.Clients[num32].State >= 3 && msgType == 10)) && Netplay.Clients[num32].IsConnected())
{
                                NetMessage.SendPacket(NetMessage.buffer[num].writeBuffer, num32);
                            }
                        }
                    }
                }
                else if (Netplay.Clients[remoteClient].IsConnected())
                {
                    if (msgType == 23)
                    {
                        Main.npc[number].playerNetSyncState[remoteClient] = default(NPC.PlayerNetSyncState);
                    }
                    else if (msgType == 27)
                    {
                        Main.projectile[number].netSyncSkippedForPlayer[remoteClient] = false;
                    }
                    NetMessage.SendPacket(NetMessage.buffer[num].writeBuffer, remoteClient);
                }
                if (Main.verboseNetplay)
                {
                    for (int num33 = 0; num33 < num24; num33++)
                    {
                    }
                    for (int num34 = 0; num34 < num24; num34++)
                    {
                        byte b6 = NetMessage.buffer[num].writeBuffer[num34];
                    }
                }
                NetMessage.buffer[num].writeLocked = false;
                if (msgType == 2 && Main.netMode == 2)
                {
                    Netplay.Clients[num].PendingTermination = true;
                }
            }
        }
References Terraria.NetMessage._currentNetSoundInfo, Terraria.NetMessage._currentPlayerDeathReason, Terraria.NetMessage._currentRevengeMarker, Terraria.Mount.Active, Terraria.NPC.active, Terraria.Tile.active(), Terraria.WorldItem.active, Terraria.Main.ActiveWorldFileData, Terraria.Tile.actuator(), Terraria.WorldGen.SavedOreTiers.Adamantite, Terraria.NPC.ai, Terraria.Projectile.ai, Terraria.WorldItem.ammo, Terraria.Main.anglerQuest, Terraria.Player.anglerQuestsFinished, Terraria.Main.anglerWhoFinishedToday, System.array, Terraria.Player.ateArtisanBread, Terraria.Player.autoReuseAllWeapons, Terraria.Projectile.bannerIdToRespondTo, System.IO.BinaryWriter.BaseStream, Terraria.Main.bloodMoon, Terraria.NPC.boughtBunny, Terraria.NPC.boughtCat, Terraria.NPC.boughtDog, Terraria.MessageBuffer.broadcast, Terraria.Player.brokenMirrorBadLuck, Terraria.NetMessage.buffer, Terraria.NPC.buffTime, Terraria.NPC.buffType, Terraria.Player.buffType, Terraria.Main.caveBackStyle, Terraria.Main.caveBackX, Terraria.NPC.cavernMonsterType, Terraria.Main.chest, Microsoft.Xna.Framework.MathHelper.Clamp(), System.Array.Clear(), Terraria.Netplay.Clients, Terraria.Main.clientUUID, Terraria.WorldGen.SavedOreTiers.Cobalt, Terraria.Player.coinLuck, Terraria.Tile.color(), Terraria.WorldItem.color, Terraria.NPC.combatBookVolumeTwoWasUsed, Terraria.NPC.combatBookWasUsed, Terraria.NetMessage.CompressTileBlock(), Terraria.Netplay.Connection, System.Collections.Generic.List< T >.Contains(), Terraria.Player.controlDown, Terraria.Player.controlDownHold, Terraria.Player.controlJump, Terraria.Player.controlLeft, Terraria.Player.controlRight, Terraria.Player.controlUp, Terraria.Player.controlUseItem, Terraria.Player.controlUseTile, Terraria.WorldGen.SavedOreTiers.Copper, Terraria.WorldGen.corruptBG, Terraria.WorldGen.crimson, Terraria.WorldGen.crimsonBG, Terraria.Projectile.damage, Terraria.WorldItem.damage, Terraria.Main.dayTime, Terraria.Main.dedServ, Terraria.WorldGen.desertBG, Terraria.NPC.difficulty, Terraria.Player.difficulty, Terraria.Main.dontStarveWorld, Terraria.NPC.downedAncientCultist, Terraria.NPC.downedBoss1, Terraria.NPC.downedBoss2, Terraria.NPC.downedBoss3, Terraria.NPC.downedChristmasIceQueen, Terraria.NPC.downedChristmasSantank, Terraria.NPC.downedChristmasTree, Terraria.NPC.downedClown, Terraria.Player.downedDD2EventAnyDifficulty, Terraria.NPC.downedDeerclops, Terraria.NPC.downedEmpressOfLight, Terraria.NPC.downedFishron, Terraria.NPC.downedFrost, Terraria.NPC.downedGoblins, Terraria.NPC.downedGolemBoss, Terraria.NPC.downedHalloweenKing, Terraria.NPC.downedHalloweenTree, Terraria.GameContent.Events.DD2Event.DownedInvasionT1, Terraria.GameContent.Events.DD2Event.DownedInvasionT2, Terraria.GameContent.Events.DD2Event.DownedInvasionT3, Terraria.NPC.downedMartians, Terraria.NPC.downedMechBoss1, Terraria.NPC.downedMechBoss2, Terraria.NPC.downedMechBoss3, Terraria.NPC.downedMechBossAny, Terraria.NPC.downedMoonlord, Terraria.NPC.downedPirates, Terraria.NPC.downedPlantBoss, Terraria.NPC.downedQueenBee, Terraria.NPC.downedQueenSlime, Terraria.NPC.downedSlimeKing, Terraria.NPC.downedTowerNebula, Terraria.NPC.downedTowerSolar, Terraria.NPC.downedTowerStardust, Terraria.NPC.downedTowerVortex, Terraria.Main.drunkWorld, Terraria.Main.dualDungeonsSeed, Terraria.Main.eclipse, Terraria.Localization.NetworkText.Empty, Terraria.Player.enabledSuperCart, Terraria.Player.equipmentBasedLuckBonus, Terraria.Player.extraAccessory, Terraria.Player.eyeColor, Terraria.Main.fastForwardTimeToDawn, Terraria.Main.fastForwardTimeToDusk, Terraria.Main.forceHalloweenForToday, Terraria.Main.forceXMasForToday, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.NPC.freeCake, Terraria.Tile.fullbrightBlock(), Terraria.Tile.fullbrightWall(), Terraria.Main.GameMode, Terraria.Main.getGoodWorld, Terraria.Net.Sockets.ISocket.GetRemoteAddress(), Terraria.Netplay.GetSectionX(), Terraria.Netplay.GetSectionY(), Terraria.Localization.Language.GetTextValue(), Terraria.Player.ghost, Terraria.NPC.GivenName, Terraria.WorldGen.SavedOreTiers.Gold, Terraria.Player.golferScoreAccumulated, Terraria.Player.hair, Terraria.Player.hairColor, Terraria.Player.hairDye, Terraria.Tile.halfBrick(), Terraria.WorldGen.hallowBG, Terraria.GameContent.Events.Sandstorm.Happening, Terraria.Player.happyFunTorchTime, Terraria.Main.hardMode, Terraria.Player.HasGardenGnomeNearby, Terraria.Entity.height, Terraria.Main.hellBackStyle, Terraria.Player.hideMisc, Terraria.Player.hideVisibleAccessory, Terraria.Player.hostile, Terraria.Main.iceBackStyle, Terraria.Projectile.identity, Terraria.Tile.inActive(), Terraria.Main.infectedSeed, Terraria.WorldItem.inner, int, Terraria.GameContent.Events.Sandstorm.IntendedSeverity, Terraria.Main.invasionType, Terraria.Tile.invisibleBlock(), Terraria.Tile.invisibleWall(), Terraria.WorldGen.SavedOreTiers.Iron, Terraria.RemoteClient.IsConnected(), Terraria.RemoteServer.IsConnected(), Terraria.Player.isOperatingAnotherEntity, Terraria.GameContent.PlayerPettingInfo.isPetSmall, Terraria.GameContent.PlayerPettingInfo.isPetting, Terraria.RemoteClient.IsSectionActive(), Terraria.GameContent.PlayerSittingHelper.isSitting, Terraria.GameContent.PlayerSleepingHelper.isSleeping, Terraria.Player.IsVoidVaultEnabled, System.item, Terraria.Chest.item, Terraria.ID.PlayerItemSlotID.SlotReference.Item, Terraria.Main.item, Terraria.Player.itemAnimation, Terraria.Player.itemRotation, Terraria.Main.jungleBackStyle, Terraria.WorldGen.jungleBG, Terraria.Player.kiteLuckLevel, Terraria.Projectile.knockBack, Terraria.WorldItem.knockBack, System.L, Terraria.Player.ladyBugLuckTimeLeft, Terraria.GameContent.Events.LanternNight.LanternsUp, Terraria.Player.lastItemUseAttemptSuccess, Terraria.NPC.life, Terraria.NPC.lifeMax, Terraria.Tile.liquid, Terraria.Tile.liquidType(), Terraria.Main.LocalPlayer, long, Terraria.WorldGen.Skyblock.lowTiles, Terraria.Player.luckPotion, System.Math.Max(), Terraria.NPC.maxAI, Terraria.NPC.maxBuffs, Terraria.Player.maxBuffs, Terraria.NPC.MaxMoonLordCountdown, Terraria.Main.maxRaining, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Player.MinionAttackTargetNPC, Terraria.Player.MinionRestTargetPoint, Terraria.Main.moondialCooldown, Terraria.NPC.MoonLordCountdown, Terraria.Main.moonModY, Terraria.Main.moonPhase, Terraria.Main.moonType, Terraria.Player.mount, Terraria.WorldGen.mushroomBG, Terraria.WorldGen.SavedOreTiers.Mythril, Terraria.Chest.name, Terraria.Item.Name, Terraria.Player.name, Terraria.ID.ProjectileID.Sets.NeedsUUID, Terraria.Player.netCameraTarget, Terraria.NPC.netID, Terraria.Projectile.netImportant, Terraria.Main.netMode, Terraria.NPC.NetSectionCoordinates, Terraria.Projectile.NetSectionCoordinates, Terraria.Projectile.netSyncSkippedForPlayer, Terraria.Social.SocialAPI.Network, Terraria.WorldItem.notAmmo, Terraria.Main.noTrapsWorld, Terraria.Main.notTheBeesWorld, Terraria.Main.npc, Terraria.Main.npcCatchable, Terraria.Player.numberOfDeathsPVE, Terraria.Player.numberOfDeathsPVP, Terraria.Main.numClouds, Terraria.WorldGen.oceanBG, Terraria.GameContent.Events.DD2Event.Ongoing, Terraria.Projectile.originalDamage, Terraria.Projectile.owner, Microsoft.Xna.Framework.Color.PackedValue, Microsoft.Xna.Framework.Graphics.PackedVector.HalfVector2.PackedValue, Terraria.Player.pantsColor, Terraria.GameContent.Events.BirthdayParty.PartyIsUp, Terraria.NPC.peddlersSatchelWasUsed, Terraria.RemoteClient.PendingTermination, Terraria.Player.petting, Terraria.Player.piggyBankProjTracker, Terraria.Main.player, Terraria.WorldItem.playerIndexTheItemIsReservedFor, Terraria.NPC.playerNetSyncState, System.IO.Stream.Position, Terraria.Entity.position, Terraria.Player.PotionOfReturnHomePosition, Terraria.Player.PotionOfReturnOriginalUsePosition, Terraria.Item.prefix, Terraria.Main.projectile, Terraria.Main.projPet, Terraria.Projectile.projUUID, Terraria.Player.pulley, Terraria.Main.pumpkinMoon, Terraria.Main.raining, Terraria.NPC.releaseOwner, Terraria.Main.remixWorld, Terraria.MessageBuffer.ResetWriter(), Terraria.Player.respawnTimer, Terraria.Main.rockLayer, Terraria.WorldItem.scale, Terraria.RemoteClient.SectionRange(), Terraria.Player.selectedItem, Terraria.NetMessage.SendPacket(), Terraria.NetMessage.SendPacketToServer(), Terraria.Netplay.ServerPassword, Terraria.Item.SetDefaults(), Terraria.WorldGen.shadowOrbSmashed, Terraria.Player.shieldRaised, Terraria.NPC.ShieldStrengthTowerNebula, Terraria.NPC.ShieldStrengthTowerSolar, Terraria.NPC.ShieldStrengthTowerStardust, Terraria.NPC.ShieldStrengthTowerVortex, Terraria.WorldItem.shimmered, Terraria.WorldItem.shimmerTime, Terraria.Player.shirtColor, Terraria.Player.shoeColor, Terraria.WorldItem.shoot, Terraria.WorldItem.shootSpeed, Terraria.Main.sign, Terraria.WorldGen.SavedOreTiers.Silver, Terraria.Player.sitting, Terraria.Player.skinColor, Terraria.Player.skinVariant, Terraria.Main.skyblockWorld, Terraria.Player.sleeping, Terraria.Main.slimeRain, Terraria.Tile.slope(), Terraria.WorldGen.snowBG, Terraria.Main.snowMoon, Terraria.RemoteClient.Socket, Terraria.NPC.SpawnedFromStatue, Terraria.NPC.spawnNeedsSyncing, Terraria.Main.spawnTileX, Terraria.Main.spawnTileY, Terraria.Player.SpawnX, Terraria.Player.SpawnY, Terraria.Item.stack, Terraria.WorldItem.stack, Terraria.RemoteClient.State, Terraria.Player.statLife, Terraria.Player.statLifeMax, Terraria.Player.statMana, Terraria.Player.statManaMax, Terraria.NPC.statsAreScaledForThisManyPlayers, Terraria.Main.sundialCooldown, Terraria.Main.sunModY, Terraria.GameContent.TreeTopsInfo.SyncSend(), Terraria.Player.talkNPC, Terraria.NPC.target, Terraria.WorldGen.tBlood, Terraria.Player.team, Terraria.Main.teamBasedSpawnsSeed, Terraria.Main.tenthAnniversaryWorld, Terraria.WorldGen.tEvil, System.text, Terraria.Sign.text, Terraria.WorldGen.tGood, Terraria.Main.tile, Terraria.Main.tileFrameImportant, Terraria.Main.time, Terraria.WorldItem.timeLeftInWhichTheItemCannotBeTakenByEnemies, Terraria.Player.torchLuck, Terraria.Player.townNPCs, Terraria.NPC.townNpcVariationIndex, Terraria.Main.travelShop, Terraria.Main.TravelShopMaxSlots, Terraria.WorldGen.treeBG1, Terraria.WorldGen.treeBG2, Terraria.WorldGen.treeBG3, Terraria.WorldGen.treeBG4, Terraria.Main.treeStyle, Terraria.WorldGen.TreeTops, Terraria.Main.treeX, Terraria.Player.tryKeepingHoveringDown, Terraria.Player.tryKeepingHoveringUp, Terraria.Item.type, Terraria.Mount.Type, Terraria.NPC.type, Terraria.Projectile.type, Terraria.Tile.type, Terraria.WorldItem.type, Terraria.Player.underShirtColor, Terraria.WorldGen.underworldBG, Terraria.Player.unlockedBiomeTorches, Terraria.NPC.unlockedSlimeBlueSpawn, Terraria.NPC.unlockedSlimeCopperSpawn, Terraria.NPC.unlockedSlimeGreenSpawn, Terraria.NPC.unlockedSlimeOldSpawn, Terraria.NPC.unlockedSlimePurpleSpawn, Terraria.NPC.unlockedSlimeRainbowSpawn, Terraria.NPC.unlockedSlimeRedSpawn, Terraria.NPC.unlockedSlimeYellowSpawn, Terraria.Player.unlockedSuperCart, Terraria.NPC.unlockedTruffleSpawn, Terraria.WorldItem.useAmmo, Terraria.WorldItem.useAnimation, Terraria.Player.usedAegisCrystal, Terraria.Player.usedAegisFruit, Terraria.Player.usedAmbrosia, Terraria.Player.usedArcaneCrystal, Terraria.Player.usedGalaxyPearl, Terraria.Player.usedGummyWorm, Terraria.WorldItem.useTime, Terraria.Player.UsingBiomeTorches, Terraria.Main.vampireSeed, Terraria.Entity.velocity, Terraria.Main.verboseNetplay, Terraria.Player.voicePitchOffset, Terraria.Player.voiceVariant, Terraria.Player.voidLensChest, Terraria.Player.vortexStealthActive, Terraria.Tile.wall, Terraria.Tile.wallColor(), Terraria.Entity.width, Terraria.Main.windSpeedTarget, Terraria.Tile.wire(), Terraria.Tile.wire2(), Terraria.Tile.wire3(), Terraria.Tile.wire4(), Terraria.Main.worldName, Terraria.Main.worldSurface, Terraria.DataStructures.TrackedProjectileReference.Write(), Terraria.GameContent.ExtraSpawnPointManager.Write(), Terraria.DataStructures.TileEntity.Write(), System.IO.BinaryWriter.Write(), Terraria.NetMessage.WriteAccessoryVisibility(), Terraria.GameContent.QuickStacking.WriteBlockedChestList(), Terraria.MessageBuffer.writeBuffer, Terraria.GameContent.Tile_Entities.TEDisplayDoll.WriteData(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.WriteDummySync(), Terraria.GameContent.Tile_Entities.TEHatRack.WriteItem(), System.Console.WriteLine(), Terraria.MessageBuffer.writeLocked, Terraria.GameContent.QuickStacking.WriteNetInventorySlots(), Terraria.MessageBuffer.writer, Terraria.DataStructures.PlayerDeathReason.WriteSelfTo(), Terraria.Chest.x, Terraria.Sign.x, Terraria.Chest.y, Terraria.Sign.y, Terraria.Main.zenithWorld, Microsoft.Xna.Framework.Vector2.Zero, Terraria.Player.zone1, Terraria.Player.zone2, Terraria.Player.zone3, Terraria.Player.zone4, and Terraria.Player.zone5.
Referenced by Terraria.GameContent.Tile_Entities.TETrainingDummy.Activate(), Terraria.Player.AddBuff(), Terraria.NPC.AddBuff(), Terraria.Liquid.AddWater(), Terraria.Chest.AfterPlacement_Hook(), Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.NPC.AI_000_TransformBoundNPC(), Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_006_Worms(), Terraria.Projectile.AI_007_GrapplingHooks(), Terraria.NPC.AI_007_TownEntities(), Terraria.Projectile.AI_010(), Terraria.NPC.AI_015_KingSlime(), Terraria.NPC.AI_037_Destroyer(), Terraria.NPC.AI_065_Butterflies(), Terraria.NPC.AI_084_LunaticCultist(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_112_FairyCritter(), Terraria.NPC.AI_120_HallowBoss(), Terraria.NPC.AI_121_QueenSlime(), Terraria.NPC.AI_123_Deerclops(), Terraria.NPC.AI_124_DeerclopsLeg(), Terraria.Projectile.AI_150_GolfClubHelper(), Terraria.Projectile.AI_155_MysticSnakeCoil(), Terraria.Projectile.AI_155_RemoveRope(), Terraria.NPC.AI_87_BigMimic_ShootItem(), Terraria.Player.ApplyDamageToNPC(), Terraria.Player.ApplyNPCOnHitEffects(), Terraria.Player.ApplyTouchDamage(), Terraria.WorldGen.AttemptFossilShattering(), Terraria.DataStructures.TileEntity.BasicOpenCloseInteraction(), Terraria.NPC.BeHurtByOtherNPC(), Terraria.NPC.BigMimicSpawnSmoke(), Terraria.NPC.BigMimicSummonCheck(), Terraria.NetMessage.BootPlayer(), Terraria.Player.BrainOfConfusionDodge(), Terraria.Main.BuyHairWindow(), Terraria.WorldGen.Skyblock.Calculate(), Terraria.NPC.CatchNPC(), Terraria.GameContent.Events.Sandstorm.ChangeSeverityIntentions(), Terraria.NPC.CheckActive(), Terraria.NPC.CheckActive_WormSegments(), Terraria.WorldGen.CheckBamboo(), Terraria.WorldGen.CheckCatTail(), Terraria.Player.CheckCrackedBrickBreak(), Terraria.NPC.checkDead(), Terraria.NPC.CheckDrowning(), Terraria.Player.CheckIceBreak(), Terraria.WorldItem.CheckInWorld(), Terraria.WorldItem.CheckLavaDeath(), Terraria.WorldGen.CheckLilyPad(), Terraria.Wiring.CheckLogicGate(), Terraria.GameContent.Events.DD2Event.CheckProgress(), Terraria.NPC.CheckProgressFrostMoon(), Terraria.NPC.CheckProgressPumpkinMoon(), Terraria.GameContent.CoinLossRevengeSystem.CheckRespawns(), Terraria.WorldGen.CheckSeaOat(), Terraria.RemoteClient.CheckSection_ForClient(), Terraria.WorldGen.CheckSuper(), Terraria.WorldGen.CheckUnderwaterPlant(), Terraria.GameContent.Events.DD2Event.ClearAllDD2EnergyCrystalsInChests(), Terraria.GameContent.Events.DD2Event.ClearAllDD2EnergyCrystalsInGame(), Terraria.GameContent.Events.DD2Event.ClearAllDD2HostilesInGame(), Terraria.NPC.Collision_LavaCollision(), Terraria.GameContent.CraftingRequests.ConsumeItemsFrom(), Terraria.WorldGen.Convert(), Terraria.WorldGen.ConvertTreeAndGround(), Terraria.WorldGen.CountTiles(), Terraria.GameContent.LucyAxeMessage.Create(), Terraria.DelegateMethods.CutTiles(), Terraria.Projectile.CutTilesAt(), Terraria.Projectile.Damage_PVE_Inner(), Terraria.Projectile.Damage_TryUsingPowders(), Terraria.GameContent.Tile_Entities.TETrainingDummy.Deactivate(), Terraria.GameContent.Tile_Entities.TEKiteAnchor.DebugPlace(), Terraria.NPC.DelBuff(), Terraria.Player.DemonConch(), Terraria.UI.ChestUI.DepositAll(), Terraria.UI.ChestUI.DepositAll_IntoWorldChest(), Terraria.WorldItem.DespawnIfMeetingConditions(), Terraria.GameContent.Events.DD2Event.Difficulty_1_SpawnMonsterFromGate(), Terraria.GameContent.Events.DD2Event.Difficulty_2_SpawnMonsterFromGate(), Terraria.GameContent.Events.DD2Event.Difficulty_3_SpawnMonsterFromGate(), Terraria.Mount.Dismount(), Terraria.NPC.DoDeathEvents(), Terraria.WorldGen.DontStarveTryWateringTile(), Terraria.Player.DoPotionOfReturnReturnToOriginalUsePosition(), Terraria.Player.DoPotionOfReturnTeleportationAndSetTheComebackPoint(), Terraria.Player.DoQueenSlimeHookTeleport(), Terraria.GameContent.EmergencyStacking.DoTransfer(), Terraria.Main.DoUpdateInWorld(), Terraria.Main.DrawInventory(), Terraria.Main.DrawPVPIcons(), Terraria.Projectile.DropGeodeGems(), Terraria.Player.DropItemFromExtractinator(), Terraria.NPC.DropItemInstanced(), Terraria.GameContent.ItemDropRules.CommonCode.DropItemLocalPerClientAndSetNPCMoneyTo0(), Terraria.Player.DropSelectedItem(), Terraria.WorldGen.dropXmasTree(), Terraria.Main.DryadText_Do_StardewValleyBit(), Terraria.Player.EndOngoingTorchGodEvent(), Terraria.Projectile.ExplodeCrackedTiles(), Terraria.Projectile.ExplodeTiles(), Terraria.WorldItem.FindOwner(), Terraria.GameContent.ConditionalDialogue.FreeCakeDialogue.GetChatAndClearCondition(), Terraria.UI.ItemSlot.GetGamepadInstructions(), Terraria.NPC.GetHurtByDebuff(), Terraria.Player.GetOrDropItem(), Terraria.WorldItem.GetPickedUpByMonsters_Money(), Terraria.WorldItem.GetPickedUpByMonsters_Special(), Terraria.WorldGen.GetRidOfCultists(), Terraria.NPC.GetShimmered(), Terraria.WorldItem.GetShimmered(), Terraria.WorldGen.GrowCatTail(), Terraria.WorldGen.GrowCheckSeaweed(), Terraria.Projectile.HandleMovement(), Terraria.GameContent.TeleportPylonsSystem.HandleTeleportRequest(), Terraria.Player.HealEffect(), Terraria.NPC.HealEffect(), Terraria.NPC.HitEffect(), Terraria.Minecart.HitTrackSwitch(), Terraria.Wiring.HitWireSingle(), Terraria.GameContent.Tile_Entities.TETrainingDummy.Hook_AfterPlacement(), Terraria.GameContent.Tile_Entities.TEItemFrame.Hook_AfterPlacement(), Terraria.GameContent.Tile_Entities.TELogicSensor.Hook_AfterPlacement(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.Hook_AfterPlacement(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.Hook_AfterPlacement(), Terraria.GameContent.Tile_Entities.TEHatRack.Hook_AfterPlacement(), Terraria.GameContent.Tile_Entities.TEFoodPlatter.Hook_AfterPlacement(), Terraria.GameContent.Tile_Entities.TEDeadCellsDisplayJar.Hook_AfterPlacement(), Terraria.Wiring.Hopper(), Terraria.GameContent.QuickStacking.IndicateBlockedChests(), Terraria.Netplay.InnerClientLoop(), Terraria.GameContent.NPCInteractions.Actions.OldManCurse.Interact(), Terraria.Player.ItemCheck(), Terraria.Player.ItemCheck_CheckCanUse_KillDirtBlock(), Terraria.Player.ItemCheck_CheckFishingBobber_PullBobber(), Terraria.Player.ItemCheck_CutTiles(), Terraria.Player.ItemCheck_MeleeHitPVP(), Terraria.Player.ItemCheck_OwnerOnlyCode(), Terraria.Player.ItemCheck_PlayInstruments(), Terraria.Player.ItemCheck_Shoot(), Terraria.Player.ItemCheck_StartActualUse(), Terraria.Player.ItemCheck_TryPlacingWearablesOnMannequins(), Terraria.Player.ItemCheck_UseArtisanLoaf(), Terraria.Player.ItemCheck_UseBossSpawners(), Terraria.Player.ItemCheck_UseCombatBook(), Terraria.Player.ItemCheck_UseDemonHeart(), Terraria.Player.ItemCheck_UseEventItems(), Terraria.Player.ItemCheck_UseMinecartPowerUp(), Terraria.Player.ItemCheck_UseMiningTools_ActuallyUseMiningTool(), Terraria.Player.ItemCheck_UseMiningTools_TryPoundingTile(), Terraria.Player.ItemCheck_UsePeddlersSatchel(), Terraria.Player.ItemCheck_UseShimmerPermanentItems(), Terraria.Player.ItemCheck_UseTeleportRod(), Terraria.Player.ItemCheck_UseTorchGodsFavor(), Terraria.Player.ItemCheck_UseWiringTools(), Terraria.WorldGen.kickOut(), Terraria.GameContent.Tile_Entities.TELogicSensor.Kill(), Terraria.Projectile.Kill_SpiderBoulder_SpawnSpider(), Terraria.WorldGen.KillTile(), Terraria.UI.ItemSlot.LeftClick(), Terraria.Liquid.LiquidCheck(), Terraria.UI.ChestUI.LootAll(), Terraria.Player.MagicConch(), Terraria.GameContent.UI.EmoteBubble.MakeLocalPlayerEmote(), Terraria.Player.ManaEffect(), Terraria.Wiring.MassWireOperation(), Terraria.Wiring.MassWireOperationStep(), Terraria.GameContent.MinecartDiggerHelper.MineTheTileIfNecessary(), Terraria.GameContent.ItemDropRules.CommonCode.ModifyItemDropFromNPC(), Terraria.Main.Moondialing(), Terraria.UI.ChestUI.MoveCoins(), Terraria.WorldGen.moveRoom(), Terraria.GameContent.Events.BirthdayParty.NaturalAttempt(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.NetPlaceEntity(), Terraria.DataStructures.TileEntityType< T >.NetPlaceEntityAttempt(), Terraria.GameContent.Tile_Entities.TELeashedEntityAnchor.NetPlaceEntityAttempt(), Terraria.GameContent.UI.EmoteBubble.NewBubble(), Terraria.GameContent.UI.EmoteBubble.NewBubbleNPC(), Terraria.Projectile.NewProjectile(), Terraria.Player.NinjaDodge(), Terraria.GameContent.Achievements.AchievementsHelper.NotifyNPCKilled(), Terraria.GameContent.Achievements.AchievementsHelper.NotifyProgressionEvent(), Terraria.Main.NPCChatText_DoAnglerQuest(), Terraria.Main.NPCChatText_DoTaxCollector(), Terraria.GameContent.Tile_Entities.TEDeadCellsDisplayJar.OnPlayerInteraction(), Terraria.GameContent.Tile_Entities.TEFoodPlatter.OnPlayerInteraction(), Terraria.GameContent.Tile_Entities.TEItemFrame.OnPlayerInteraction(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.OnPlayerInteraction(), Terraria.Main.OnSubmitServerPasswordFromRequest(), Terraria.UI.ItemSlot.OverrideLeftClick(), Terraria.WorldGen.paintCoatTile(), Terraria.WorldGen.paintCoatWall(), Terraria.WorldGen.paintTile(), Terraria.WorldGen.paintWall(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.PerformShiftClickAction(), Terraria.GameContent.Tile_Entities.TEHatRack.PerformShiftClickAction(), Terraria.Player.PickTile(), Terraria.Player.PickupItem(), Terraria.UI.ItemSlot.PickupItemIntoMouse(), Terraria.Player.PickWall(), Terraria.TileObject.Place(), Terraria.WorldGen.Place3x2(), Terraria.GameContent.MinecartDiggerHelper.PlaceATrack(), Terraria.WorldGen.PlaceChest(), Terraria.GameContent.Tile_Entities.TELeashedEntityAnchor.PlaceFromPlayerPlacementHook(), Terraria.GameContent.Tile_Entities.TELeashedEntityAnchorWithItem.PlaceFromPlayerPlacementHook(), Terraria.GameContent.Tile_Entities.TEFoodPlatter.PlaceItemInFrame(), Terraria.GameContent.Tile_Entities.TEItemFrame.PlaceItemInFrame(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.PlaceItemInFrame(), Terraria.GameContent.Tile_Entities.TEDeadCellsDisplayJar.PlaceItemInJar(), Terraria.GameContent.Tile_Entities.TETeleportationPylon.PlacementPreviewHook_AfterPlacement(), Terraria.Player.PlaceThing_LockChest(), Terraria.Player.PlaceThing_PaintScrapper_LongMoss(), Terraria.Player.PlaceThing_Tiles_BlockPlacementForAssortedThings(), Terraria.Player.PlaceThing_Tiles_CheckRopeUsability(), Terraria.Player.PlaceThing_Tiles_PlaceIt(), Terraria.Player.PlaceThing_Tiles_PlaceIt_AutoPaintAndActuate(), Terraria.Player.PlaceThing_Tiles_PlaceIt_KillGrassForSolids(), Terraria.Player.PlaceThing_Tiles_PlaceIt_TriggerLogicLamp(), Terraria.Player.PlaceThing_Tiles_PlaceIt_UnslopeForSolids(), Terraria.Player.PlaceThing_TryReplacingTiles(), Terraria.Player.PlaceThing_TryReplacingWalls(), Terraria.Player.PlaceThing_Walls(), Terraria.Player.PlaceThing_Walls_FillEmptySpace(), Terraria.Player.PlaceWeapon(), Terraria.Player.PlayerNoSpaceTeleport(), Terraria.NetMessage.PlayNetSound(), Terraria.GameContent.PressurePlateHelper.PokeLocation(), Terraria.WorldGen.PoundPlatform(), Terraria.GameContent.MinecartDiggerHelper.PoundTrack(), Terraria.Player.ProcessHitAgainstNPC(), Terraria.Chat.Commands.EmojiCommand.ProcessOutgoingMessage(), Terraria.Chat.Commands.RockPaperScissorsCommand.ProcessOutgoingMessage(), Terraria.Player.PurgeDD2EnergyCrystals(), Terraria.GameContent.Golf.GolfHelper.ContactListener.PutBallInCup(), Terraria.Player.QuickGrapple(), Terraria.Player.QuickMount(), Terraria.UI.ChestUI.QuickStack(), Terraria.GameContent.TreeTopsInfo.RandomizeTreeStyle(), Terraria.NPC.RecheckSectionsForSkippedUpdates(), Terraria.Projectile.RecheckSectionsForSkippedUpdates(), Terraria.NPC.RedHatSkeletron(), Terraria.GameContent.Tile_Entities.TETeleportationPylon.RejectPlacementFromNet(), Terraria.NPC.ReleaseNPC(), Terraria.GameContent.CoinLossRevengeSystem.RemoveExpiredOrInvalidMarkers(), Terraria.GameContent.PortalHelper.RemoveIntersectingPortals(), Terraria.WorldGen.ReplaceTile_DoActualReplacement(), Terraria.NPC.RequestBuffRemoval(), Terraria.GameContent.Events.DD2Event.RequestToSkipWaitTime(), Terraria.UI.ChestUI.Restock(), Terraria.GameContent.QuickStacking.RestoreToPlayer(), Terraria.NetMessage.ResyncTiles(), Terraria.Main.SaveClothesWindow(), Terraria.NetMessage.SendAnglerQuest(), Terraria.NetMessage.SendCoinLossRevengeMarker(), Terraria.GameContent.Events.CreditsRollEvent.SendCreditsRollRemainingTimeToPlayer(), Terraria.NetMessage.SendNPCHousesAndTravelShop(), Terraria.NetMessage.SendObjectPlacement(), Terraria.NetMessage.SendPlayerDeath(), Terraria.NetMessage.SendPlayerHurt(), Terraria.GameContent.QuickStacking.SendQuickStackToNearbyChests(), Terraria.NetMessage.SendSection(), Terraria.NetMessage.SendTemporaryAnimation(), Terraria.NetMessage.SendTileSquare(), Terraria.NetMessage.SendTravelShop(), Terraria.NetMessage.sendWater(), Terraria.GameContent.Events.DD2Event.SetEnemySpawningOnHold(), Terraria.Mount.SetMount(), Terraria.Player.SetOrRequestSpectating(), Terraria.Testing.ChatCommands.ToolkitDebugCommands.SetServerPingCommand(), Terraria.Player.ShadowDodge(), Terraria.Player.Shellphone_Spawn(), Terraria.Projectile.Shimmer(), Terraria.WorldGen.ShootFromCannon(), Terraria.Testing.ChatCommands.ToolkitDebugCommands.ShowDebugCommand(), Terraria.GameContent.PlayerSittingHelper.SitDown(), Terraria.GameContent.PlayerSittingHelper.SitUp(), Terraria.WorldGen.SlopeTile(), Terraria.WorldGen.SmashAltar(), Terraria.Tile.SmoothSlope(), Terraria.UI.ItemSorting.SortInventory(), Terraria.Player.Spawn(), Terraria.NPC.SpawnBoss(), Terraria.GameContent.CoinLossRevengeSystem.RevengeMarker.SpawnEnemy(), Terraria.NPC.Spawner.SpawnFaelings(), Terraria.NPC.SpawnMechQueen(), Terraria.WorldItem.SpawnShimmeredItem(), Terraria.NPC.SpawnSkeletron(), Terraria.WorldGen.SpawnTownNPC(), Terraria.DelegateMethods.SpreadTile(), Terraria.Main.startDedInputCallBack(), Terraria.WorldGen.StartImpendingDoom(), Terraria.GameContent.Events.DD2Event.StartInvasion(), Terraria.GameContent.PlayerSleepingHelper.StartSleeping(), Terraria.Main.StartSlimeRain(), Terraria.Player.StickyMovement(), Terraria.GameContent.Events.DD2Event.StopInvasion(), Terraria.GameContent.PlayerSleepingHelper.StopSleeping(), Terraria.Main.StopSlimeRain(), Terraria.NPC.StreamUpdatesToNearbyPlayers(), Terraria.Main.SubmitSignText(), Terraria.GameContent.Events.DD2Event.SummonCrystal(), Terraria.Main.Sundialing(), Terraria.UI.ItemSlot.SwapEquip(), Terraria.Collision.SwitchTiles(), Terraria.Main.SyncAnInvasion(), Terraria.GameContent.Events.DD2Event.SyncInvasionProgress(), Terraria.WorldItem.SyncItemsInSection(), Terraria.NPC.Spawner.SyncNewlySpawnedNPCs(), Terraria.NetMessage.SyncNPCsForSection(), Terraria.ObjectData.TileObjectData.SyncObjectPlacement(), Terraria.NetMessage.SyncOnePlayer(), Terraria.NetMessage.SyncOnePlayer_ItemArray(), Terraria.GameContent.QuickStacking.DestinationHelper.SyncSlot(), Terraria.Testing.DebugOptions.SyncToJoiningPlayer(), Terraria.Wiring.Teleport(), Terraria.NPC.Teleport(), Terraria.Player.TeleportationPotion(), Terraria.Player.TileInteractionsUse(), Terraria.WorldGen.ToggleGemLock(), Terraria.GameContent.Events.LanternNight.ToggleManualLanterns(), Terraria.GameContent.Events.BirthdayParty.ToggleManualParty(), Terraria.Player.TorchAttack(), Terraria.NPC.Transform(), Terraria.NPC.TransformCopperSlime(), Terraria.NPC.TransformElderSlime(), Terraria.WorldGen.TreeGrowFXCheck(), Terraria.WorldGen.TriggerLunarApocalypse(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.TryChangePose(), Terraria.GameContent.DoorOpeningHelper.CommonDoorOpeningInfoProvider.TryCloseDoor(), Terraria.GameContent.DoorOpeningHelper.TallGateOpeningInfoProvider.TryCloseDoor(), Terraria.WorldItem.TryCombiningIntoNearbyItems(), Terraria.WorldGen.TryConvertingOrKillingTreesAboveIfTheyWouldBecomeInvalid(), Terraria.Player.TryDroppingSingleItem(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.TryFitting(), Terraria.GameContent.Tile_Entities.TEHatRack.TryFitting(), Terraria.GameContent.PortalHelper.TryGoingThroughPortals(), Terraria.WorldItem.TryGrantingMakeAWishSet(), Terraria.WorldGen.TryKillingReplaceableTile(), Terraria.Player.TryLandingOnDetonator(), Terraria.GameContent.DoorOpeningHelper.CommonDoorOpeningInfoProvider.TryOpenDoor(), Terraria.GameContent.DoorOpeningHelper.TallGateOpeningInfoProvider.TryOpenDoor(), Terraria.GameContent.Tile_Entities.TEDeadCellsDisplayJar.TryPlacing(), Terraria.GameContent.Tile_Entities.TEFoodPlatter.TryPlacing(), Terraria.GameContent.Tile_Entities.TEItemFrame.TryPlacing(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.TryPlacing(), Terraria.UI.ChestUI.TryPlacingInChest(), Terraria.Player.TryReplantingHerbs(), Terraria.NetMessage.TrySendData(), Terraria.GameContent.Events.CreditsRollEvent.TryStartingCreditsRoll(), Terraria.Player.TrySyncingInput(), Terraria.Main.TrySyncingItemArray(), Terraria.Main.TrySyncingMyPlayer(), Terraria.NPC.TrySyncingUniqueTownNPCData(), Terraria.NPC.TryTeleportingCaughtMysticFrog(), Terraria.Player.UnityTeleport(), Terraria.NPC.UnlockOrExchangePet(), Terraria.WorldGen.UnspawnHomelessNPC(), Terraria.WorldGen.UnspawnTravelNPC(), Terraria.Net.Ping.Update(), Terraria.Player.Update(), Terraria.Projectile.Update(), Terraria.Main.UpdateCameraPan(), Terraria.Main.UpdateClient(), Terraria.Main.updateCloudLayer(), Terraria.GameContent.Tile_Entities.TELogicSensor.UpdateEndInternal(), Terraria.NPC.UpdateHomeTileState(), Terraria.Main.UpdateInvasion(), Terraria.WorldItem.UpdateItem(), Terraria.Player.UpdateLuck(), Terraria.NPC.UpdateNetworkCode(), Terraria.NPC.UpdateNPC(), Terraria.NPC.UpdateNPC_BuffClearExpiredBuffs(), Terraria.Main.UpdateServer(), Terraria.GameContent.Events.BirthdayParty.UpdateTime(), Terraria.GameContent.Events.DD2Event.UpdateTime(), Terraria.GameContent.Events.LanternNight.UpdateTime(), Terraria.Main.UpdateTime(), Terraria.Main.UpdateTime_StartDay(), Terraria.Main.UpdateTime_StartNight(), Terraria.Main.UpdateWeather(), Terraria.WorldGen.UpdateWorld_OvergroundTile(), Terraria.WorldGen.UpdateWorld_UndergroundTile(), Terraria.Projectile.UseGasTrapInChest(), Terraria.WorldGen.ValidateTileSquareIsActiveAndOfType(), Terraria.GameContent.Events.DD2Event.WipeEntities(), and Terraria.Testing.QuickLoad.JoinWorld.WithCurrentState().