Terraria Decompiled: Terraria.NetMessage.SyncConnectedPlayer
SyncConnectedPlayer()
static void Terraria.NetMessage.SyncConnectedPlayer (int plr) inline static
Definition at line 2857 of file NetMessage.cs.
        {
            NetMessage.SyncOnePlayer(plr, -1, plr);
            for (int i = 0; i < 255; i++)
            {
                if (plr != i && Main.player[i].active)
                {
                    NetMessage.SyncOnePlayer(i, plr, -1);
                }
            }
            NetMessage.SendNPCHousesAndTravelShop(plr);
            NetMessage.SendAnglerQuest(plr);
            CreditsRollEvent.SendCreditsRollRemainingTimeToPlayer(plr);
            NPC.RevengeManager.SendAllMarkersToPlayer(plr);
            NetMessage.EnsureLocalPlayerIsPresent();
            DebugOptions.SyncToJoiningPlayer(plr);
        }
References Terraria.Player.active, Terraria.NetMessage.EnsureLocalPlayerIsPresent(), Terraria.Main.player, Terraria.NPC.RevengeManager, Terraria.GameContent.CoinLossRevengeSystem.SendAllMarkersToPlayer(), Terraria.NetMessage.SendAnglerQuest(), Terraria.GameContent.Events.CreditsRollEvent.SendCreditsRollRemainingTimeToPlayer(), Terraria.NetMessage.SendNPCHousesAndTravelShop(), Terraria.NetMessage.SyncOnePlayer(), and Terraria.Testing.DebugOptions.SyncToJoiningPlayer().
Referenced by Terraria.MessageBuffer.GetData().