Terraria Decompiled: Terraria.NetMessage.CompressTileBlock_Inner
CompressTileBlock_Inner()
static void Terraria.NetMessage.CompressTileBlock_Inner (BinaryWriter writer, int xStart, int yStart, int width, int height) inline static
Definition at line 1862 of file NetMessage.cs.
        {
            short num = 0;
            short num2 = 0;
            short num3 = 0;
            short num4 = 0;
            int num5 = 0;
            int num6 = 0;
            byte b = 0;
            byte[] array = new byte[16];
            Tile tile = null;
            for (int i = yStart; i < yStart + height; i++)
            {
                for (int j = xStart; j < xStart + width; j++)
                {
                    Tile tile2 = Main.tile[j, i];
                    if (tile2.isTheSameAs(tile) && TileID.Sets.AllowsSaveCompressionBatching[(int)tile2.type])
                    {
                        num4 += 1;
                    }
                    else
                    {
                        if (tile != null)
{
                            if (num4 > 0)
{
                                array[num5] = (byte)(num4 & 255);
                                num5++;
                                if (num4 > 255)
{
                                    b |= 128;
                                    array[num5] = (byte)(((int)num4 & 65280) >> 8);
                                    num5++;
                                }
                                else
{
                                    b |= 64;
                                }
                            }
                            array[num6] = b;
                            writer.Write(array, num6, num5 - num6);
                            num4 = 0;
                        }
                        num5 = 4;
                        byte b4;
                        byte b3;
                        byte b2 = (b = (b3 = (b4 = 0)));
                        if (tile2.active())
{
                            b |= 2;
                            array[num5] = (byte)tile2.type;
                            num5++;
                            if (tile2.type > 255)
{
                                array[num5] = (byte)(tile2.type >> 8);
                                num5++;
                                b |= 32;
                            }
                            if (TileID.Sets.BasicChest[(int)tile2.type] && tile2.frameX % 36 == 0 && tile2.frameY % 36 == 0)
{
                                short num7 = (short)Chest.FindChest(j, i);
                                if (num7 != -1)
{
                                    NetMessage._compressChestList[(int)num] = num7;
                                    num += 1;
                                }
                            }
                            if (tile2.type == 88 && tile2.frameX % 54 == 0 && tile2.frameY % 36 == 0)
{
                                short num8 = (short)Chest.FindChest(j, i);
                                if (num8 != -1)
{
                                    NetMessage._compressChestList[(int)num] = num8;
                                    num += 1;
                                }
                            }
                            if (tile2.type == 85 && tile2.frameX % 36 == 0 && tile2.frameY % 36 == 0)
{
                                short num9 = (short)Sign.ReadSign(j, i, true);
                                if (num9 != -1)
{
                                    short[] compressSignList = NetMessage._compressSignList;
                                    short num10 = num2;
                                    num2 = num10 + 1;
                                    compressSignList[(int)num10] = num9;
                                }
                            }
                            if (tile2.type == 55 && tile2.frameX % 36 == 0 && tile2.frameY % 36 == 0)
{
                                short num11 = (short)Sign.ReadSign(j, i, true);
                                if (num11 != -1)
{
                                    short[] compressSignList2 = NetMessage._compressSignList;
                                    short num12 = num2;
                                    num2 = num12 + 1;
                                    compressSignList2[(int)num12] = num11;
                                }
                            }
                            if (tile2.type == 425 && tile2.frameX % 36 == 0 && tile2.frameY % 36 == 0)
{
                                short num13 = (short)Sign.ReadSign(j, i, true);
                                if (num13 != -1)
{
                                    short[] compressSignList3 = NetMessage._compressSignList;
                                    short num14 = num2;
                                    num2 = num14 + 1;
                                    compressSignList3[(int)num14] = num13;
                                }
                            }
                            if (tile2.type == 573 && tile2.frameX % 36 == 0 && tile2.frameY % 36 == 0)
{
                                short num15 = (short)Sign.ReadSign(j, i, true);
                                if (num15 != -1)
{
                                    short[] compressSignList4 = NetMessage._compressSignList;
                                    short num16 = num2;
                                    num2 = num16 + 1;
                                    compressSignList4[(int)num16] = num15;
                                }
                            }
                            if (tile2.type == 378 && tile2.frameX % 36 == 0 && tile2.frameY == 0)
{
                                int num17 = TileEntityType<TETrainingDummy>.Find(j, i);
                                if (num17 != -1)
{
                                    short[] compressEntities = NetMessage._compressEntities;
                                    short num18 = num3;
                                    num3 = num18 + 1;
                                    compressEntities[(int)num18] = (short)num17;
                                }
                            }
                            if (tile2.type == 395 && tile2.frameX % 36 == 0 && tile2.frameY == 0)
{
                                int num19 = TileEntityType<TEItemFrame>.Find(j, i);
                                if (num19 != -1)
{
                                    short[] compressEntities2 = NetMessage._compressEntities;
                                    short num20 = num3;
                                    num3 = num20 + 1;
                                    compressEntities2[(int)num20] = (short)num19;
                                }
                            }
                            if (tile2.type == 698 && tile2.frameX % 18 == 0 && tile2.frameY == 0)
{
                                int num21 = TileEntityType<TEDeadCellsDisplayJar>.Find(j, i);
                                if (num21 != -1)
{
                                    short[] compressEntities3 = NetMessage._compressEntities;
                                    short num22 = num3;
                                    num3 = num22 + 1;
                                    compressEntities3[(int)num22] = (short)num21;
                                }
                            }
                            if (tile2.type == 520 && tile2.frameX % 18 == 0 && tile2.frameY == 0)
{
                                int num23 = TileEntityType<TEFoodPlatter>.Find(j, i);
                                if (num23 != -1)
{
                                    short[] compressEntities4 = NetMessage._compressEntities;
                                    short num24 = num3;
                                    num3 = num24 + 1;
                                    compressEntities4[(int)num24] = (short)num23;
                                }
                            }
                            if (tile2.type == 471 && tile2.frameX % 54 == 0 && tile2.frameY == 0)
{
                                int num25 = TileEntityType<TEWeaponsRack>.Find(j, i);
                                if (num25 != -1)
{
                                    short[] compressEntities5 = NetMessage._compressEntities;
                                    short num26 = num3;
                                    num3 = num26 + 1;
                                    compressEntities5[(int)num26] = (short)num25;
                                }
                            }
                            if (tile2.type == 470 && tile2.frameX % 36 == 0 && tile2.frameY == 0)
{
                                int num27 = TileEntityType<TEDisplayDoll>.Find(j, i);
                                if (num27 != -1)
{
                                    short[] compressEntities6 = NetMessage._compressEntities;
                                    short num28 = num3;
                                    num3 = num28 + 1;
                                    compressEntities6[(int)num28] = (short)num27;
                                }
                            }
                            if (tile2.type == 475 && tile2.frameX % 54 == 0 && tile2.frameY == 0)
{
                                int num29 = TileEntityType<TEHatRack>.Find(j, i);
                                if (num29 != -1)
{
                                    short[] compressEntities7 = NetMessage._compressEntities;
                                    short num30 = num3;
                                    num3 = num30 + 1;
                                    compressEntities7[(int)num30] = (short)num29;
                                }
                            }
                            if (tile2.type == 597 && tile2.frameX % 54 == 0 && tile2.frameY % 72 == 0)
{
                                int num31 = TileEntityType<TETeleportationPylon>.Find(j, i);
                                if (num31 != -1)
{
                                    short[] compressEntities8 = NetMessage._compressEntities;
                                    short num32 = num3;
                                    num3 = num32 + 1;
                                    compressEntities8[(int)num32] = (short)num31;
                                }
                            }
                            if (Main.tileFrameImportant[(int)tile2.type])
{
                                array[num5] = (byte)(tile2.frameX & 255);
                                num5++;
                                array[num5] = (byte)(((int)tile2.frameX & 65280) >> 8);
                                num5++;
                                array[num5] = (byte)(tile2.frameY & 255);
                                num5++;
                                array[num5] = (byte)(((int)tile2.frameY & 65280) >> 8);
                                num5++;
                            }
                            if (tile2.color() != 0)
{
                                b3 |= 8;
                                array[num5] = tile2.color();
                                num5++;
                            }
                        }
                        if (tile2.wall != 0)
{
                            b |= 4;
                            array[num5] = (byte)tile2.wall;
                            num5++;
                            if (tile2.wallColor() != 0)
{
                                b3 |= 16;
                                array[num5] = tile2.wallColor();
                                num5++;
                            }
                        }
                        if (tile2.liquid != 0)
{
                            if (tile2.shimmer())
{
                                b3 |= 128;
                                b |= 8;
                            }
                            else if (tile2.lava())
{
                                b |= 16;
                            }
                            else if (tile2.honey())
{
                                b |= 24;
                            }
                            else
{
                                b |= 8;
                            }
                            array[num5] = tile2.liquid;
                            num5++;
                        }
                        if (tile2.wire())
{
                            b2 |= 2;
                        }
                        if (tile2.wire2())
{
                            b2 |= 4;
                        }
                        if (tile2.wire3())
{
                            b2 |= 8;
                        }
                        int num33;
                        if (tile2.halfBrick())
{
                            num33 = 16;
                        }
                        else if (tile2.slope() != 0)
{
                            num33 = (int)(tile2.slope() + 1) << 4;
                        }
                        else
{
                            num33 = 0;
                        }
                        b2 |= (byte)num33;
                        if (tile2.actuator())
{
                            b3 |= 2;
                        }
                        if (tile2.inActive())
{
                            b3 |= 4;
                        }
                        if (tile2.wire4())
{
                            b3 |= 32;
                        }
                        if (tile2.wall > 255)
{
                            array[num5] = (byte)(tile2.wall >> 8);
                            num5++;
                            b3 |= 64;
                        }
                        if (tile2.invisibleBlock())
{
                            b4 |= 2;
                        }
                        if (tile2.invisibleWall())
{
                            b4 |= 4;
                        }
                        if (tile2.fullbrightBlock())
{
                            b4 |= 8;
                        }
                        if (tile2.fullbrightWall())
{
                            b4 |= 16;
                        }
                        num6 = 3;
                        if (b4 != 0)
{
                            b3 |= 1;
                            array[num6] = b4;
                            num6--;
                        }
                        if (b3 != 0)
{
                            b2 |= 1;
                            array[num6] = b3;
                            num6--;
                        }
                        if (b2 != 0)
{
                            b |= 1;
                            array[num6] = b2;
                            num6--;
                        }
                        tile = tile2;
                    }
                }
            }
            if (num4 > 0)
            {
                array[num5] = (byte)(num4 & 255);
                num5++;
                if (num4 > 255)
                {
                    b |= 128;
                    array[num5] = (byte)(((int)num4 & 65280) >> 8);
                    num5++;
                }
                else
                {
                    b |= 64;
                }
            }
            array[num6] = b;
            writer.Write(array, num6, num5 - num6);
            writer.Write(num);
            for (int k = 0; k < (int)num; k++)
            {
                Chest chest = Main.chest[(int)NetMessage._compressChestList[k]];
                writer.Write(NetMessage._compressChestList[k]);
                writer.Write((short)chest.x);
                writer.Write((short)chest.y);
                writer.Write(chest.name);
            }
            writer.Write(num2);
            for (int l = 0; l < (int)num2; l++)
            {
                Sign sign = Main.sign[(int)NetMessage._compressSignList[l]];
                writer.Write(NetMessage._compressSignList[l]);
                writer.Write((short)sign.x);
                writer.Write((short)sign.y);
                writer.Write(sign.text);
            }
            writer.Write(num3);
            for (int m = 0; m < (int)num3; m++)
            {
                TileEntity.Write(writer, TileEntity.ByID[(int)NetMessage._compressEntities[m]], false);
            }
        }
References Terraria.NetMessage._compressChestList, Terraria.NetMessage._compressEntities, Terraria.NetMessage._compressSignList, Terraria.Tile.active(), Terraria.Tile.actuator(), Terraria.ID.TileID.Sets.AllowsSaveCompressionBatching, System.array, Terraria.ID.TileID.Sets.BasicChest, Terraria.DataStructures.TileEntity.ByID, Terraria.Main.chest, Terraria.Tile.color(), Terraria.DataStructures.TileEntityType< T >.Find(), Terraria.Chest.FindChest(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Tile.fullbrightBlock(), Terraria.Tile.fullbrightWall(), Terraria.Tile.halfBrick(), Terraria.Tile.honey(), Terraria.Tile.inActive(), int, Terraria.Tile.invisibleBlock(), Terraria.Tile.invisibleWall(), Terraria.Tile.isTheSameAs(), Terraria.Tile.lava(), Terraria.Tile.liquid, Terraria.Chest.name, Terraria.Sign.ReadSign(), Terraria.Tile.shimmer(), Terraria.Main.sign, Terraria.Tile.slope(), Terraria.Sign.text, Terraria.Main.tile, Terraria.Main.tileFrameImportant, Terraria.Tile.type, Terraria.Tile.wall, Terraria.Tile.wallColor(), Terraria.Tile.wire(), Terraria.Tile.wire2(), Terraria.Tile.wire3(), Terraria.Tile.wire4(), Terraria.DataStructures.TileEntity.Write(), System.IO.BinaryWriter.Write(), Terraria.Chest.x, Terraria.Sign.x, Terraria.Chest.y, and Terraria.Sign.y.
Referenced by Terraria.NetMessage.CompressTileBlock().