Terraria Decompiled: Terraria.GameContent.UI.Elements.UICharacterListItem.UICharacterListItem
UICharacterListItem()
Terraria.GameContent.UI.Elements.UICharacterListItem.UICharacterListItem (PlayerFileData data, int orderInList) inline
Definition at line 29 of file UICharacterListItem.cs.
        {
            this.BorderColor = new Color(89, 116, 213) * 0.7f;
            this._dividerTexture = Main.Assets.Request<Texture2D>("Images/UI/Divider", 1);
            this._innerPanelTexture = Main.Assets.Request<Texture2D>("Images/UI/InnerPanelBackground", 1);
            this._buttonCloudActiveTexture = Main.Assets.Request<Texture2D>("Images/UI/ButtonCloudActive", 1);
            this._buttonCloudInactiveTexture = Main.Assets.Request<Texture2D>("Images/UI/ButtonCloudInactive", 1);
            this._buttonFavoriteActiveTexture = Main.Assets.Request<Texture2D>("Images/UI/ButtonFavoriteActive", 1);
            this._buttonFavoriteInactiveTexture = Main.Assets.Request<Texture2D>("Images/UI/ButtonFavoriteInactive", 1);
            this._buttonPlayTexture = Main.Assets.Request<Texture2D>("Images/UI/ButtonPlay", 1);
            this._buttonRenameTexture = Main.Assets.Request<Texture2D>("Images/UI/ButtonRename", 1);
            this._buttonDeleteTexture = Main.Assets.Request<Texture2D>("Images/UI/ButtonDelete", 1);
            this.Height.Set(96f, 0f);
            this.Width.Set(0f, 1f);
            base.SetPadding(6f);
            this._data = data;
            this._orderInList = orderInList;
            this._playerPanel = new UICharacter(data.Player, false, true, 1f, true);
            this._playerPanel.Left.Set(4f, 0f);
            this._playerPanel.OnLeftDoubleClick += this.PlayGame;
            base.OnLeftDoubleClick += this.PlayGame;
            base.Append(this._playerPanel);
            float num = 4f;
            UIImageButton uiimageButton = new UIImageButton(this._buttonPlayTexture, null);
            uiimageButton.VAlign = 1f;
            uiimageButton.Left.Set(num, 0f);
            uiimageButton.OnLeftClick += this.PlayGame;
            uiimageButton.OnMouseOver += this.PlayMouseOver;
            uiimageButton.OnMouseOut += this.ButtonMouseOut;
            base.Append(uiimageButton);
            num += 24f;
            UIImageButton uiimageButton2 = new UIImageButton(this._data.IsFavorite ? this._buttonFavoriteActiveTexture : this._buttonFavoriteInactiveTexture, null);
            uiimageButton2.VAlign = 1f;
            uiimageButton2.Left.Set(num, 0f);
            uiimageButton2.OnLeftClick += this.FavoriteButtonClick;
            uiimageButton2.OnMouseOver += this.FavoriteMouseOver;
            uiimageButton2.OnMouseOut += this.ButtonMouseOut;
            uiimageButton2.SetVisibility(1f, this._data.IsFavorite ? 0.8f : 0.4f);
            base.Append(uiimageButton2);
            num += 24f;
            if (SocialAPI.Cloud != null)
            {
                UIImageButton uiimageButton3 = new UIImageButton(this._data.IsCloudSave ? this._buttonCloudActiveTexture : this._buttonCloudInactiveTexture, null);
                uiimageButton3.VAlign = 1f;
                uiimageButton3.Left.Set(num, 0f);
                uiimageButton3.OnLeftClick += this.CloudButtonClick;
                uiimageButton3.OnMouseOver += this.CloudMouseOver;
                uiimageButton3.OnMouseOut += this.ButtonMouseOut;
                base.Append(uiimageButton3);
                uiimageButton3.SetSnapPoint("Cloud", orderInList, null, null);
                num += 24f;
            }
            UIImageButton uiimageButton4 = new UIImageButton(this._buttonRenameTexture, null);
            uiimageButton4.VAlign = 1f;
            uiimageButton4.Left.Set(num, 0f);
            uiimageButton4.OnLeftClick += this.RenameButtonClick;
            uiimageButton4.OnMouseOver += this.RenameMouseOver;
            uiimageButton4.OnMouseOut += this.ButtonMouseOut;
            base.Append(uiimageButton4);
            num += 24f;
            UIImageButton uiimageButton5 = new UIImageButton(this._buttonDeleteTexture, null);
            uiimageButton5.VAlign = 1f;
            uiimageButton5.HAlign = 1f;
            if (!this._data.IsFavorite)
            {
                uiimageButton5.OnLeftClick += this.DeleteButtonClick;
            }
            uiimageButton5.OnMouseOver += this.DeleteMouseOver;
            uiimageButton5.OnMouseOut += this.DeleteMouseOut;
            this._deleteButton = uiimageButton5;
            base.Append(uiimageButton5);
            num += 4f;
            this._buttonLabel = new UIText("", 1f, false);
            this._buttonLabel.VAlign = 1f;
            this._buttonLabel.Left.Set(num, 0f);
            this._buttonLabel.Top.Set(-3f, 0f);
            base.Append(this._buttonLabel);
            this._deleteButtonLabel = new UIText("", 1f, false);
            this._deleteButtonLabel.VAlign = 1f;
            this._deleteButtonLabel.HAlign = 1f;
            this._deleteButtonLabel.Left.Set(-30f, 0f);
            this._deleteButtonLabel.Top.Set(-3f, 0f);
            base.Append(this._deleteButtonLabel);
            uiimageButton.SetSnapPoint("Play", orderInList, null, null);
            uiimageButton2.SetSnapPoint("Favorite", orderInList, null, null);
            uiimageButton4.SetSnapPoint("Rename", orderInList, null, null);
            uiimageButton5.SetSnapPoint("Delete", orderInList, null, null);
        }
References Terraria.GameContent.UI.Elements.UICharacterListItem._buttonCloudInactiveTexture, Terraria.GameContent.UI.Elements.UICharacterListItem._buttonDeleteTexture, Terraria.GameContent.UI.Elements.UICharacterListItem._buttonFavoriteInactiveTexture, Terraria.GameContent.UI.Elements.UICharacterListItem._buttonLabel, Terraria.GameContent.UI.Elements.UICharacterListItem._buttonPlayTexture, Terraria.GameContent.UI.Elements.UICharacterListItem._buttonRenameTexture, Terraria.GameContent.UI.Elements.UICharacterListItem._data, Terraria.GameContent.UI.Elements.UICharacterListItem._deleteButtonLabel, Terraria.GameContent.UI.Elements.UICharacterListItem._playerPanel, Terraria.UI.UIElement.Append(), Terraria.Main.Assets, Terraria.GameContent.UI.Elements.UICharacterListItem.ButtonMouseOut(), Terraria.Social.SocialAPI.Cloud, Terraria.GameContent.UI.Elements.UICharacterListItem.CloudButtonClick(), Terraria.GameContent.UI.Elements.UICharacterListItem.CloudMouseOver(), Microsoft.Xna.Framework.Graphics.Color, Terraria.GameContent.UI.Elements.UICharacterListItem.DeleteButtonClick(), Terraria.GameContent.UI.Elements.UICharacterListItem.DeleteMouseOut(), Terraria.GameContent.UI.Elements.UICharacterListItem.DeleteMouseOver(), Terraria.GameContent.UI.Elements.UICharacterListItem.FavoriteButtonClick(), Terraria.GameContent.UI.Elements.UICharacterListItem.FavoriteMouseOver(), Terraria.UI.UIElement.Height, Terraria.IO.FileData.IsCloudSave, Terraria.IO.FileData.IsFavorite, Terraria.UI.UIElement.Left, Terraria.IO.PlayerFileData.Player, Terraria.GameContent.UI.Elements.UICharacterListItem.PlayGame(), Terraria.GameContent.UI.Elements.UICharacterListItem.PlayMouseOver(), Terraria.GameContent.UI.Elements.UICharacterListItem.RenameButtonClick(), Terraria.GameContent.UI.Elements.UICharacterListItem.RenameMouseOver(), Terraria.UI.StyleDimension.Set(), Terraria.UI.UIElement.SetSnapPoint(), Terraria.GameContent.UI.Elements.UIImageButton.SetVisibility(), Terraria.UI.UIElement.Top, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.Elements.UICharacterListItem.CompareTo().