Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.BinaryMethodReturn.WriteArray
WriteArray()
object[] System.Runtime.Serialization.Formatters.Binary.BinaryMethodReturn.WriteArray (object returnValue, object[] args, Exception exception, object callContext, object[] properties) inline package
Definition at line 23 of file BinaryMethodReturn.cs.
        {
            this.returnValue = returnValue;
            this.args = args;
            this.exception = exception;
            this.callContext = callContext;
            this.properties = properties;
            int num = 0;
            if (args == null || args.Length == 0)
            {
                this.messageEnum = MessageEnum.NoArgs;
            }
            else
            {
                this.argTypes = new Type[args.Length];
                this.bArgsPrimitive = true;
                for (int i = 0; i < args.Length; i++)
                {
                    if (args[i] != null)
                    {
                        this.argTypes[i] = args[i].GetType();
                        if (Converter.ToCode(this.argTypes[i]) <= InternalPrimitiveTypeE.Invalid && this.argTypes[i] != Converter.typeofString)
{
                            this.bArgsPrimitive = false;
                            break;
                        }
                    }
                }
                if (this.bArgsPrimitive)
                {
                    this.messageEnum = MessageEnum.ArgsInline;
                }
                else
                {
                    num++;
                    this.messageEnum = MessageEnum.ArgsInArray;
                }
            }
            if (returnValue == null)
            {
                this.messageEnum |= MessageEnum.NoReturnValue;
            }
            else if (returnValue.GetType() == typeof(void))
            {
                this.messageEnum |= MessageEnum.ReturnValueVoid;
            }
            else
            {
                this.returnType = returnValue.GetType();
                if (Converter.ToCode(this.returnType) > InternalPrimitiveTypeE.Invalid || this.returnType == Converter.typeofString)
                {
                    this.messageEnum |= MessageEnum.ReturnValueInline;
                }
                else
                {
                    num++;
                    this.messageEnum |= MessageEnum.ReturnValueInArray;
                }
            }
            if (exception != null)
            {
                num++;
                this.messageEnum |= MessageEnum.ExceptionInArray;
            }
            if (callContext == null)
            {
                this.messageEnum |= MessageEnum.NoContext;
            }
            else if (callContext is string)
            {
                this.messageEnum |= MessageEnum.ContextInline;
            }
            else
            {
                num++;
                this.messageEnum |= MessageEnum.ContextInArray;
            }
            if (properties != null)
            {
                num++;
                this.messageEnum |= MessageEnum.PropertyInArray;
            }
            if (IOUtil.FlagTest(this.messageEnum, MessageEnum.ArgsInArray) && num == 1)
            {
                this.messageEnum ^= MessageEnum.ArgsInArray;
                this.messageEnum |= MessageEnum.ArgsIsArray;
                return args;
            }
            if (num > 0)
            {
                int num2 = 0;
                this.callA = new object[num];
                if (IOUtil.FlagTest(this.messageEnum, MessageEnum.ArgsInArray))
                {
                    this.callA[num2++] = args;
                }
                if (IOUtil.FlagTest(this.messageEnum, MessageEnum.ReturnValueInArray))
                {
                    this.callA[num2++] = returnValue;
                }
                if (IOUtil.FlagTest(this.messageEnum, MessageEnum.ExceptionInArray))
                {
                    this.callA[num2++] = exception;
                }
                if (IOUtil.FlagTest(this.messageEnum, MessageEnum.ContextInArray))
                {
                    this.callA[num2++] = callContext;
                }
                if (IOUtil.FlagTest(this.messageEnum, MessageEnum.PropertyInArray))
                {
                    this.callA[num2] = properties;
                }
                return this.callA;
            }
            return null;
        }
References System.Runtime.Serialization.Formatters.Binary.BinaryMethodReturn.args, System.Runtime.Serialization.Formatters.Binary.BinaryMethodReturn.argTypes, System.Runtime.Serialization.Formatters.Binary.BinaryMethodReturn.bArgsPrimitive, System.Runtime.Serialization.Formatters.Binary.BinaryMethodReturn.callA, System.Runtime.Serialization.Formatters.Binary.BinaryMethodReturn.callContext, System.Runtime.Serialization.Formatters.Binary.BinaryMethodReturn.exception, System.Runtime.Serialization.Formatters.Binary.IOUtil.FlagTest(), System.Runtime.Serialization.Formatters.Binary.BinaryMethodReturn.properties, System.Runtime.Serialization.Formatters.Binary.BinaryMethodReturn.returnValue, System.Runtime.Serialization.Formatters.Binary.Converter.ToCode(), and System.Runtime.Serialization.Formatters.Binary.Converter.typeofString.
Referenced by System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteReturnArray().