Terraria Decompiled: Ionic.Crc.CRC32.UpdateCRC
UpdateCRC() [1/2]
void Ionic.Crc.CRC32.UpdateCRC (byte b) inline
Definition at line 105 of file CRC32.cs.
        {
            if (this.reverseBits)
            {
                uint num = (this._register >> 24) ^ (uint)b;
                this._register = (this._register << 8) ^ this.crc32Table[(int)((UIntPtr)num)];
                return;
            }
            uint num2 = (this._register & 255U) ^ (uint)b;
            this._register = (this._register >> 8) ^ this.crc32Table[(int)((UIntPtr)num2)];
        }
References Ionic.Crc.CRC32.crc32Table, Ionic.Crc.CRC32.reverseBits, and System.U.
Referenced by Ionic.BZip2.BZip2Compressor.AddRunToOutputBlock(), Ionic.BZip2.BZip2InputStream.SetupNoRandPartA(), Ionic.BZip2.BZip2InputStream.SetupNoRandPartC(), Ionic.BZip2.BZip2InputStream.SetupRandPartA(), and Ionic.BZip2.BZip2InputStream.SetupRandPartC().