Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.BinaryMethodReturn.ReadArray
ReadArray()
IMethodReturnMessage System.Runtime.Serialization.Formatters.Binary.BinaryMethodReturn.ReadArray (object[] returnA, IMethodCallMessage methodCallMessage, object handlerObject) inline package
Definition at line 199 of file BinaryMethodReturn.cs.
        {
            if (IOUtil.FlagTest(this.messageEnum, MessageEnum.ArgsIsArray))
            {
                this.args = returnA;
            }
            else
            {
                int num = 0;
                if (IOUtil.FlagTest(this.messageEnum, MessageEnum.ArgsInArray))
                {
                    if (returnA.Length < num)
                    {
                        throw new SerializationException(Environment.GetResourceString("Invalid MethodCall or MethodReturn stream format."));
                    }
                    this.args = (object[])returnA[num++];
                }
                if (IOUtil.FlagTest(this.messageEnum, MessageEnum.ReturnValueInArray))
                {
                    if (returnA.Length < num)
                    {
                        throw new SerializationException(Environment.GetResourceString("Invalid MethodCall or MethodReturn stream format."));
                    }
                    this.returnValue = returnA[num++];
                }
                if (IOUtil.FlagTest(this.messageEnum, MessageEnum.ExceptionInArray))
                {
                    if (returnA.Length < num)
                    {
                        throw new SerializationException(Environment.GetResourceString("Invalid MethodCall or MethodReturn stream format."));
                    }
                    this.exception = (Exception)returnA[num++];
                }
                if (IOUtil.FlagTest(this.messageEnum, MessageEnum.ContextInArray))
                {
                    if (returnA.Length < num)
                    {
                        throw new SerializationException(Environment.GetResourceString("Invalid MethodCall or MethodReturn stream format."));
                    }
                    this.callContext = returnA[num++];
                }
                if (IOUtil.FlagTest(this.messageEnum, MessageEnum.PropertyInArray))
                {
                    if (returnA.Length < num)
                    {
                        throw new SerializationException(Environment.GetResourceString("Invalid MethodCall or MethodReturn stream format."));
                    }
                    this.properties = returnA[num++];
                }
            }
            return new MethodResponse(methodCallMessage, handlerObject, new BinaryMethodReturnMessage(this.returnValue, this.args, this.exception, (LogicalCallContext)this.callContext, (object[])this.properties));
        }
References System.Runtime.Serialization.Formatters.Binary.BinaryMethodReturn.args, System.Runtime.Serialization.Formatters.Binary.BinaryMethodReturn.callContext, System.Runtime.Serialization.Formatters.Binary.BinaryMethodReturn.exception, System.Runtime.Serialization.Formatters.Binary.IOUtil.FlagTest(), System.Environment.GetResourceString(), System.Runtime.Serialization.Formatters.Binary.BinaryMethodReturn.properties, and System.Runtime.Serialization.Formatters.Binary.BinaryMethodReturn.returnValue.
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize().