Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.BinaryMethodReturn.Write
Write()
void System.Runtime.Serialization.Formatters.Binary.BinaryMethodReturn.Write (__BinaryWriter sout) inline
Implements System.Runtime.Serialization.Formatters.Binary.IStreamable.
Definition at line 141 of file BinaryMethodReturn.cs.
        {
            sout.WriteByte(22);
            sout.WriteInt32((int)this.messageEnum);
            if (IOUtil.FlagTest(this.messageEnum, MessageEnum.ReturnValueInline))
            {
                IOUtil.WriteWithCode(this.returnType, this.returnValue, sout);
            }
            if (IOUtil.FlagTest(this.messageEnum, MessageEnum.ContextInline))
            {
                IOUtil.WriteStringWithCode((string)this.callContext, sout);
            }
            if (IOUtil.FlagTest(this.messageEnum, MessageEnum.ArgsInline))
            {
                sout.WriteInt32(this.args.Length);
                for (int i = 0; i < this.args.Length; i++)
                {
                    IOUtil.WriteWithCode(this.argTypes[i], this.args[i], sout);
                }
            }
        }
References System.Runtime.Serialization.Formatters.Binary.BinaryMethodReturn.args, System.Runtime.Serialization.Formatters.Binary.BinaryMethodReturn.argTypes, System.Runtime.Serialization.Formatters.Binary.BinaryMethodReturn.callContext, System.Runtime.Serialization.Formatters.Binary.IOUtil.FlagTest(), System.Runtime.Serialization.Formatters.Binary.BinaryMethodReturn.messageEnum, System.Runtime.Serialization.Formatters.Binary.BinaryMethodReturn.returnType, System.Runtime.Serialization.Formatters.Binary.BinaryMethodReturn.returnValue, System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteByte(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteInt32(), System.Runtime.Serialization.Formatters.Binary.IOUtil.WriteStringWithCode(), and System.Runtime.Serialization.Formatters.Binary.IOUtil.WriteWithCode().
Referenced by System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteMethodReturn().