Terraria Decompiled: Terraria.Graphics.EmpressBladeDrawer.Draw
Draw()
void Terraria.Graphics.EmpressBladeDrawer.Draw (Projectile proj) inline
Definition at line 11 of file EmpressBladeDrawer.cs.
        {
            float num = proj.ai[1];
            MiscShaderData miscShaderData = GameShaders.Misc["EmpressBlade"];
            int num2 = 1;
            int num3 = 0;
            int num4 = 0;
            float num5 = 0.6f;
            miscShaderData.UseShaderSpecificData(new Vector4((float)num2, (float)num3, (float)num4, num5));
            miscShaderData.Apply(null);
            EmpressBladeDrawer._vertexStrip.PrepareStrip(proj.oldPos, proj.oldRot, new VertexStrip.StripColorFunction(this.StripColors), new VertexStrip.StripHalfWidthFunction(this.StripWidth), -Main.screenPosition + proj.Size / 2f, new int?(proj.oldPos.Length), true);
            EmpressBladeDrawer._vertexStrip.DrawTrail();
            Main.pixelShader.CurrentTechnique.Passes[0].Apply();
        }
References Terraria.Graphics.EmpressBladeDrawer._vertexStrip, Terraria.Projectile.ai, Terraria.Graphics.Shaders.MiscShaderData.Apply(), Terraria.Graphics.VertexStrip.DrawTrail(), Microsoft.Xna.Framework.Vector2.Length(), Terraria.Graphics.Shaders.GameShaders.Misc, Terraria.Projectile.oldPos, Terraria.Projectile.oldRot, Terraria.Main.pixelShader, Terraria.Graphics.VertexStrip.PrepareStrip(), Terraria.Main.screenPosition, Terraria.Entity.Size, Terraria.Graphics.VertexStrip.StripColorFunction(), Terraria.Graphics.VertexStrip.StripHalfWidthFunction(), and Terraria.Graphics.Shaders.MiscShaderData.UseShaderSpecificData().
Referenced by Terraria.Main.DrawProjDirect().