Terraria Decompiled: System.Security.PermissionBuilder.Create
Create() [2/4]
static IPermission System.Security.PermissionBuilder.Create (string fullname, PermissionState state) inline static
Definition at line 10 of file PermissionBuilder.cs.
        {
            if (fullname == null)
            {
                throw new ArgumentNullException("fullname");
            }
            SecurityElement securityElement = new SecurityElement("IPermission");
            securityElement.AddAttribute("class", fullname);
            securityElement.AddAttribute("version", "1");
            if (state == PermissionState.Unrestricted)
            {
                securityElement.AddAttribute("Unrestricted", "true");
            }
            return PermissionBuilder.CreatePermission(fullname, securityElement);
        }
References System.Security.SecurityElement.AddAttribute(), System.Security.PermissionBuilder.CreatePermission(), and System.state.
Referenced by System.Security.Policy.DefaultPolicies.BuildEverything(), System.Security.Policy.DefaultPolicies.BuildInternet(), System.Security.Policy.DefaultPolicies.BuildLocalIntranet(), System.Security.PermissionBuilder.CreatePermission(), and System.Security.PermissionSet.FromXml().