Terraria Decompiled: System.Security.PermissionBuilder.CreatePermission
CreatePermission()
static IPermission System.Security.PermissionBuilder.CreatePermission (string fullname, SecurityElement se) inline static package
Definition at line 62 of file PermissionBuilder.cs.
        {
            Type type = Type.GetType(fullname);
            if (type == null)
            {
                throw new TypeLoadException(string.Format(Locale.GetText("Can't create an instance of permission class {0}."), fullname));
            }
            IPermission permission = PermissionBuilder.Create(type);
            permission.FromXml(se);
            return permission;
        }
References System.Security.PermissionBuilder.Create(), System.Security.Format, System.Security.ISecurityEncodable.FromXml(), Locale.GetText(), and System.Type.GetType().
Referenced by System.Security.PermissionBuilder.Create(), System.Security.PermissionBuilder.Create(), and System.Security.PermissionBuilder.Create().