Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.SetupGamepadPoints
SetupGamepadPoints()
void Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.SetupGamepadPoints (SpriteBatch spriteBatch) inline private
Definition at line 458 of file UIWorldCreationAdvancedSecretSeedsList.cs.
        {
            UILinkPointNavigator.Shortcuts.BackButtonCommand = 7;
            int num = 3000;
            int num2 = num;
            this.GetSnapPoints();
            UILinkPoint linkPoint = this._helper.GetLinkPoint(num2++, this._backButton);
            List<SnapPoint> snapPoints = this._worldList.GetSnapPoints();
            UILinkPoint[,] array = this._helper.CreateUILinkPointGrid(ref num2, snapPoints, 1, null, null, null, linkPoint);
            UILinkPoint uilinkPoint = array[0, array.GetLength(1) - 1];
            this._helper.PairUpDown(uilinkPoint, linkPoint);
            this._helper.MoveToVisuallyClosestPoint(num, num2);
        }
References Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList._backButton, Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList._helper, Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList._worldList, System.array, Terraria.GameContent.UI.States.UIGamepadHelper.CreateUILinkPointGrid(), Terraria.GameContent.UI.States.UIGamepadHelper.GetLinkPoint(), Terraria.GameContent.UI.Elements.UIList.GetSnapPoints(), Terraria.UI.UIElement.GetSnapPoints(), Terraria.GameContent.UI.States.UIGamepadHelper.MoveToVisuallyClosestPoint(), and Terraria.GameContent.UI.States.UIGamepadHelper.PairUpDown().
Referenced by Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.Draw().