Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.Spawn_BestReforge
Spawn_BestReforge()
void Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.Spawn_BestReforge (ParticleOrchestraSettings settings) inline private
Definition at line 306 of file UIWorldCreationAdvancedSecretSeedsList.cs.
        {
            Vector2 vector = new Vector2(0f, 0.16350001f);
            Asset<Texture2D> asset = Main.Assets.Request<Texture2D>("Images/UI/Creative/Research_Spark", 1);
            for (int i = 0; i < 2; i++)
            {
                Vector2 vector2 = Main.rand.NextVector2Circular(3f, 4f);
                Vector2 vector3 = new Vector2(0f, Main.rand.NextFloatDirection() * 20f);
                this.SeedParticleSystem.Add(new CreativeSacrificeParticle(asset, null, settings.MovementVector + vector2, settings.PositionInWorld + vector3)
                {
                    AccelerationPerFrame = vector,
                    ScaleOffsetPerFrame = -0.016666668f
                });
            }
            float num = Main.rand.NextFloat();
            for (int j = 0; j < 3; j++)
            {
                Color color = Main.hslToRgb((num + Main.rand.NextFloat() * 0.12f) % 1f, 1f, 0.4f + Main.rand.NextFloat() * 0.25f, byte.MaxValue);
                Dust dust = this.SeedDust.NewDust(settings.PositionInWorld, 0, 0, 267, 0f, 0f, 0, color, 1f);
                dust.velocity = Main.rand.NextVector2Circular(1f, 1f);
                dust.velocity += settings.MovementVector * Main.rand.NextFloatDirection() * 0.5f;
                dust.noGravity = true;
                dust.scale = 0.6f + Main.rand.NextFloat() * 0.9f;
                dust.fadeIn = 0.7f + Main.rand.NextFloat() * 0.8f;
                Vector2 vector4 = new Vector2(0f, Main.rand.NextFloatDirection() * 20f);
                dust.position += vector4;
                if (dust.dustIndex != 200 && dust.type != 0)
                {
                    Dust dust2 = this.SeedDust.CloneDust(dust);
                    dust2.scale /= 2f;
                    dust2.fadeIn *= 0.75f;
                    dust2.color = new Color(255, 255, 255, 255);
                }
            }
        }
References Terraria.Graphics.Renderers.ParticleRenderer.Add(), Terraria.Main.Assets, Terraria.GameContent.UI.UIDust.CloneDust(), Microsoft.Xna.Framework.Graphics.Color, Terraria.Dust.dustIndex, Terraria.Main.hslToRgb(), Terraria.GameContent.Drawing.ParticleOrchestraSettings.MovementVector, Terraria.GameContent.UI.UIDust.NewDust(), Terraria.GameContent.Drawing.ParticleOrchestraSettings.PositionInWorld, Terraria.Main.rand, Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.SeedDust, Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.SeedParticleSystem, Terraria.Dust.type, and Microsoft.Xna.Framework.Graphics.Vector2.
Referenced by Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.SpawnParticles().