Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.ClickSecretSeed
ClickSecretSeed()
void Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.ClickSecretSeed (UIMouseEvent evt, UIElement listeningElement) inline private
Definition at line 214 of file UIWorldCreationAdvancedSecretSeedsList.cs.
        {
            GroupOptionButton<WorldGen.SecretSeed> groupOptionButton = (GroupOptionButton<WorldGen.SecretSeed>)listeningElement;
            WorldGen.SecretSeed optionValue = groupOptionButton.OptionValue;
            if (optionValue.Enabled)
            {
                groupOptionButton.SetCurrentOption(null);
                WorldGen.SecretSeed.Disable(optionValue);
                this._creationState2.RemoveSeedFromSeedMenu(optionValue.TextThatWasUsedToUnlock);
                return;
            }
            groupOptionButton.SetCurrentOption(optionValue);
            WorldGen.SecretSeed.Enable(optionValue, true);
            this._creationState2.AddSeedFromSeedmenu(optionValue.TextThatWasUsedToUnlock);
            this.SpawnParticles(groupOptionButton);
        }
References Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList._creationState2, Terraria.GameContent.UI.States.UIWorldCreation.AddSeedFromSeedmenu(), Terraria.WorldGen.SecretSeed.Disable(), Terraria.WorldGen.SecretSeed.Enable(), Terraria.WorldGen.SecretSeed.Enabled, Terraria.GameContent.UI.States.UIWorldCreation.RemoveSeedFromSeedMenu(), Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.SpawnParticles(), and Terraria.WorldGen.SecretSeed.TextThatWasUsedToUnlock.
Referenced by Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.BuildPage().