Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.MakeBackAndCreatebuttons
MakeBackAndCreatebuttons()
void Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.MakeBackAndCreatebuttons (UIElement outerContainer) inline private
Definition at line 364 of file UIWorldCreationAdvancedSecretSeedsList.cs.
        {
            UITextPanel<LocalizedText> uitextPanel = new UITextPanel<LocalizedText>(Language.GetText("UI.Apply"), 0.65f, true)
            {
                Width = StyleDimension.FromPixelsAndPercent(-10f, 0.5f),
                Height = StyleDimension.FromPixels(50f),
                VAlign = 1f,
                HAlign = 0.5f,
                Top = StyleDimension.FromPixels(-43f)
            };
            uitextPanel.OnMouseOver += this.FadedMouseOver;
            uitextPanel.OnMouseOut += this.FadedMouseOut;
            uitextPanel.OnLeftMouseDown += this.Click_GoBack;
            uitextPanel.SetSnapPoint("Back", 0, null, null);
            outerContainer.Append(uitextPanel);
            this._backButton = uitextPanel;
        }
References Terraria.UI.UIElement.Append(), Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.Click_GoBack(), Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.FadedMouseOut(), Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.FadedMouseOver(), Terraria.UI.StyleDimension.FromPixels(), Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.Localization.Language.GetText(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.SetSnapPoint(), Terraria.UI.UIElement.Top, Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.BuildPage().