Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.Spawn_RainbowRodHit
Spawn_RainbowRodHit()
void Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.Spawn_RainbowRodHit (ParticleOrchestraSettings settings) inline private
Definition at line 254 of file UIWorldCreationAdvancedSecretSeedsList.cs.
        {
            float num = Main.rand.NextFloat() * 6.2831855f;
            float num2 = 6f;
            float num3 = Main.rand.NextFloat();
            for (float num4 = 0f; num4 < 1f; num4 += 1f / num2)
            {
                Vector2 vector = settings.MovementVector * Main.rand.NextFloatDirection() * 0.15f;
                Vector2 vector2 = new Vector2(Main.rand.NextFloat() * 0.4f + 0.4f);
                float num5 = num + Main.rand.NextFloat() * 6.2831855f;
                float num6 = 1.5707964f;
                Vector2 vector3 = 1.5f * vector2;
                float num7 = 60f;
                Vector2 vector4 = Main.rand.NextVector2Circular(8f, 8f) * vector2;
                PrettySparkleParticle prettySparkleParticle = new PrettySparkleParticle();
                prettySparkleParticle.Velocity = num5.ToRotationVector2() * vector3 + vector;
                prettySparkleParticle.AccelerationPerFrame = num5.ToRotationVector2() * -(vector3 / num7) - vector * 1f / 60f;
                prettySparkleParticle.ColorTint = Main.hslToRgb((num3 + Main.rand.NextFloat() * 0.33f) % 1f, 1f, 0.4f + Main.rand.NextFloat() * 0.25f, byte.MaxValue);
                prettySparkleParticle.ColorTint.A = 0;
                prettySparkleParticle.LocalPosition = settings.PositionInWorld + vector4;
                prettySparkleParticle.Rotation = num6;
                prettySparkleParticle.Scale = vector2;
                this.SeedParticleSystem.Add(prettySparkleParticle);
                prettySparkleParticle = new PrettySparkleParticle();
                prettySparkleParticle.Velocity = num5.ToRotationVector2() * vector3 + vector;
                prettySparkleParticle.AccelerationPerFrame = num5.ToRotationVector2() * -(vector3 / num7) - vector * 1f / 60f;
                prettySparkleParticle.ColorTint = new Color(255, 255, 255, 0);
                prettySparkleParticle.LocalPosition = settings.PositionInWorld + vector4;
                prettySparkleParticle.Rotation = num6;
                prettySparkleParticle.Scale = vector2 * 0.6f;
                this.SeedParticleSystem.Add(prettySparkleParticle);
            }
            for (int i = 0; i < 12; i++)
            {
                Color color = Main.hslToRgb((num3 + Main.rand.NextFloat() * 0.12f) % 1f, 1f, 0.4f + Main.rand.NextFloat() * 0.25f, byte.MaxValue);
                Dust dust = this.SeedDust.NewDust(settings.PositionInWorld, 0, 0, 267, 0f, 0f, 0, color, 1f);
                dust.velocity = Main.rand.NextVector2Circular(1f, 1f);
                dust.velocity += settings.MovementVector * Main.rand.NextFloatDirection() * 0.5f;
                dust.noGravity = true;
                dust.scale = 0.6f + Main.rand.NextFloat() * 0.9f;
                dust.fadeIn = 0.7f + Main.rand.NextFloat() * 0.8f;
                if (dust.dustIndex != 200 && dust.type != 0)
                {
                    Dust dust2 = this.SeedDust.CloneDust(dust);
                    dust2.scale /= 2f;
                    dust2.fadeIn *= 0.75f;
                    dust2.color = new Color(255, 255, 255, 255);
                }
            }
        }
References Terraria.Graphics.Renderers.ParticleRenderer.Add(), Terraria.GameContent.UI.UIDust.CloneDust(), Microsoft.Xna.Framework.Graphics.Color, Terraria.Dust.dustIndex, Terraria.Main.hslToRgb(), Terraria.GameContent.UI.UIDust.NewDust(), Terraria.GameContent.Drawing.ParticleOrchestraSettings.PositionInWorld, Terraria.Main.rand, Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.SeedDust, Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.SeedParticleSystem, Terraria.Dust.type, and Microsoft.Xna.Framework.Graphics.Vector2.
Referenced by Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.SpawnParticles().