Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.DrawSeedSystems
DrawSeedSystems()
void Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.DrawSeedSystems (SpriteBatch spriteBatch) inline
Definition at line 449 of file UIWorldCreationAdvancedSecretSeedsList.cs.
        {
            this.SeedDust.UpdateDust();
            this.SeedDust.DrawDust();
            this.SeedParticleSystem.Update();
            this.SeedParticleSystem.Draw(spriteBatch);
        }
References Terraria.Graphics.Renderers.ParticleRenderer.Draw(), Terraria.GameContent.UI.UIDust.DrawDust(), Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.SeedDust, Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.SeedParticleSystem, Terraria.Graphics.Renderers.ParticleRenderer.Update(), and Terraria.GameContent.UI.UIDust.UpdateDust().
Referenced by Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.Draw().