Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.BuildPage
BuildPage()
void Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.BuildPage () inline private
Definition at line 30 of file UIWorldCreationAdvancedSecretSeedsList.cs.
        {
            this.SeedDust.Clear();
            this.SeedParticleSystem.Clear();
            base.RemoveAllChildren();
            UIElement uielement = new UIElement
            {
                Width = StyleDimension.FromPixels(500f),
                Height = StyleDimension.FromPixelsAndPercent(-200f, 1f),
                Top = StyleDimension.FromPixels(202f),
                HAlign = 0.5f,
                VAlign = 0f
            };
            uielement.MaxHeight = StyleDimension.FromPixels(400f);
            uielement.SetPadding(0f);
            base.Append(uielement);
            UIPanel uipanel = new UIPanel
            {
                Width = StyleDimension.FromPercent(1f),
                Height = StyleDimension.FromPixelsAndPercent(-102f, 1f),
                BackgroundColor = new Color(33, 43, 79) * 0.8f
            };
            uipanel.SetPadding(0f);
            uielement.Append(uipanel);
            this.MakeBackAndCreatebuttons(uielement);
            int num = 56;
            int num2 = 4;
            UIElement uielement2 = new UIElement
            {
                Top = StyleDimension.FromPixelsAndPercent((float)num2, 0f),
                Width = StyleDimension.FromPixelsAndPercent(-20f, 1f),
                Left = StyleDimension.FromPixelsAndPercent(2f, 0f),
                Height = StyleDimension.FromPixelsAndPercent((float)(-(float)num2 - num), 1f),
                HAlign = 0.5f
            };
            uielement2.SetPadding(0f);
            uielement2.PaddingTop = 8f;
            uielement2.PaddingBottom = 12f;
            uipanel.Append(uielement2);
            this._worldList = new UIList();
            this._worldList.Width.Set(0f, 1f);
            this._worldList.Height.Set(0f, 1f);
            this._worldList.ListPadding = 5f;
            uielement2.Append(this._worldList);
            this._containerPanel = uielement2;
            this._scrollbar = new UIScrollbar(UIScrollbar.ColorTheme.Blue);
            this._scrollbar.SetView(100f, 1000f);
            this._scrollbar.Height.Set(0f, 1f);
            this._scrollbar.HAlign = 1f;
            this._worldList.SetScrollbar(this._scrollbar);
            List<WorldGen.SecretSeed> seedsForInterface = SecretSeedsTracker.SeedsForInterface;
            this._worldList.ManualSortMethod = new Action<List<UIElement>>(this.CustomSort);
            int num3 = 0;
            foreach (WorldGen.SecretSeed secretSeed in seedsForInterface)
            {
                GroupOptionButton<WorldGen.SecretSeed> groupOptionButton = new GroupOptionButton<WorldGen.SecretSeed>(secretSeed, null, Language.GetText(secretSeed.Localization), Color.White, null, 1f, 0.5f, 10f)
                {
                    Width = StyleDimension.FromPixelsAndPercent(0f, 1f),
                    Height = new StyleDimension(40f, 0f),
                    HAlign = 0f
                };
                groupOptionButton.SetSnapPoint("Seed", num3++, null, null);
                UIElement uielement3 = new UIElement();
                groupOptionButton.Append(uielement3);
                groupOptionButton.SetTextWithoutLocalization(secretSeed.TextThatWasUsedToUnlock, 1f, Color.White, 0f, 10f);
                groupOptionButton.OnLeftMouseDown += this.ClickSecretSeed;
                groupOptionButton.OnMouseOver += this.MouseOverSeed;
                groupOptionButton.OnMouseOut += this.MouseOutSeed;
                groupOptionButton.SetCurrentOption(secretSeed.Enabled ? secretSeed : null);
                uielement3.OnDraw += this.DrawGlowRing;
                this._worldList.Add(groupOptionButton);
            }
            UIElement uielement4 = new UIElement
            {
                Width = StyleDimension.FromPixelsAndPercent(-20f, 1f),
                Height = StyleDimension.FromPixelsAndPercent((float)(num + num2), 0f),
                HAlign = 0.5f,
                VAlign = 1f
            };
            uielement4.SetPadding(0f);
            uielement4.PaddingBottom = 12f;
            uipanel.Append(uielement4);
            this.AddDescriptionPanel(uielement4, (float)num, "desc");
        }
References Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList._scrollbar, Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList._worldList, Terraria.GameContent.UI.Elements.UIList.Add(), Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.AddDescriptionPanel(), Terraria.UI.UIElement.Append(), Terraria.GameContent.UI.UIDust.Clear(), Terraria.Graphics.Renderers.ParticleRenderer.Clear(), Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.ClickSecretSeed(), Microsoft.Xna.Framework.Graphics.Color, Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.CustomSort(), Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.DrawGlowRing(), Terraria.UI.StyleDimension.FromPercent(), Terraria.UI.StyleDimension.FromPixels(), Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.Localization.Language.GetText(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.Left, Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.MakeBackAndCreatebuttons(), Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.MouseOutSeed(), Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.MouseOverSeed(), Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.SeedDust, Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.SeedParticleSystem, Terraria.GameContent.SecretSeedsTracker.SeedsForInterface, Terraria.UI.StyleDimension.Set(), Terraria.UI.UIElement.SetPadding(), Terraria.GameContent.UI.Elements.UIList.SetScrollbar(), Terraria.GameContent.UI.Elements.UIScrollbar.SetView(), Terraria.UI.UIElement.Top, Terraria.UI.UIElement.UIElement(), Terraria.UI.UIElement.VAlign, Microsoft.Xna.Framework.Color.White, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.UIWorldCreationAdvancedSecretSeedsList().