Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.LayoutProviders.LegacyDungeonLayoutProvider.LegacyDungeonLayout
LegacyDungeonLayout()
void Terraria.GameContent.Generation.Dungeon.LayoutProviders.LegacyDungeonLayoutProvider.LegacyDungeonLayout (DungeonData data, GenerationProgress progress, UnifiedRandom genRand, ushort tileType, ushort crackedTileType, ushort wallType, int steps, int maxSteps, ref int roomDelay) inline
Definition at line 30 of file LegacyDungeonLayoutProvider.cs.
        {
            if (data.genVars.preGenDungeonEntranceSettings.PrecalculateEntrancePosition)
            {
                data.genVars.generatingDungeonPositionX = -10 + (int)data.genVars.dungeonEntrancePosition.X + genRand.Next(20);
                data.genVars.generatingDungeonPositionY = (int)data.genVars.dungeonEntrancePosition.Y + 30;
            }
            data.outerProgressionBounds = new DungeonBounds[1];
            data.outerProgressionBounds[0] = data.genVars.outerPotentialDungeonBounds;
            LegacyDungeonHallSettings legacyDungeonHallSettings = new LegacyDungeonHallSettings
            {
                StyleData = data.genVars.dungeonStyle,
                RandomSeed = genRand.Next()
            };
            LegacyDungeonRoomSettings legacyDungeonRoomSettings = new LegacyDungeonRoomSettings
            {
                StyleData = data.genVars.dungeonStyle,
                RandomSeed = genRand.Next()
            };
            DungeonCrawler.MakeDungeon_GetRoom(new LegacyDungeonRoomSettings
            {
                StyleData = data.genVars.dungeonStyle,
                StartingRoom = true,
                RandomSeed = genRand.Next(),
                RoomPosition = new Point(data.genVars.generatingDungeonPositionX, data.genVars.generatingDungeonPositionY)
            }, true).GenerateRoom(data);
            while (steps > 0)
            {
                data.dungeonBounds.UpdateBounds(data.genVars.generatingDungeonPositionX, data.genVars.generatingDungeonPositionY);
                steps--;
                int num = (maxSteps - steps) / maxSteps * 60;
                DungeonUtils.UpdateDungeonProgress(progress, (float)num / 100f, Language.GetTextValue("WorldGeneration.DungeonRoomsAndHalls"), false);
                if (roomDelay > 0)
                {
                    roomDelay--;
                }
                if ((roomDelay == 0) & (genRand.Next(3) == 0))
                {
                    roomDelay = 5;
                    if (genRand.Next(2) == 0)
                    {
                        int generatingDungeonPositionX = data.genVars.generatingDungeonPositionX;
                        int generatingDungeonPositionY = data.genVars.generatingDungeonPositionY;
                        legacyDungeonHallSettings.RandomSeed = genRand.Next();
                        DungeonCrawler.MakeDungeon_GetHall_Legacy(legacyDungeonHallSettings).GenerateHall(data, data.genVars.generatingDungeonPositionX, data.genVars.generatingDungeonPositionY);
                        if (genRand.Next(2) == 0)
{
                            legacyDungeonHallSettings.RandomSeed = genRand.Next();
                            DungeonCrawler.MakeDungeon_GetHall_Legacy(legacyDungeonHallSettings).GenerateHall(data, data.genVars.generatingDungeonPositionX, data.genVars.generatingDungeonPositionY);
                        }
                        legacyDungeonRoomSettings.RandomSeed = genRand.Next();
                        legacyDungeonRoomSettings.RoomPosition = new Point(data.genVars.generatingDungeonPositionX, data.genVars.generatingDungeonPositionY);
                        DungeonCrawler.MakeDungeon_GetRoom(legacyDungeonRoomSettings, true).GenerateRoom(data);
                        data.genVars.generatingDungeonPositionX = generatingDungeonPositionX;
                        data.genVars.generatingDungeonPositionY = generatingDungeonPositionY;
                    }
                    else
                    {
                        legacyDungeonRoomSettings.RandomSeed = genRand.Next();
                        legacyDungeonRoomSettings.RoomPosition = new Point(data.genVars.generatingDungeonPositionX, data.genVars.generatingDungeonPositionY);
                        DungeonCrawler.MakeDungeon_GetRoom(legacyDungeonRoomSettings, true).GenerateRoom(data);
                    }
                }
                else
                {
                    legacyDungeonHallSettings.RandomSeed = genRand.Next();
                    DungeonCrawler.MakeDungeon_GetHall_Legacy(legacyDungeonHallSettings).GenerateHall(data, data.genVars.generatingDungeonPositionX, data.genVars.generatingDungeonPositionY);
                }
            }
            legacyDungeonRoomSettings.RandomSeed = genRand.Next();
            legacyDungeonRoomSettings.RoomPosition = new Point(data.genVars.generatingDungeonPositionX, data.genVars.generatingDungeonPositionY);
            DungeonCrawler.MakeDungeon_GetRoom(legacyDungeonRoomSettings, true).GenerateRoom(data);
            data.outerProgressionBounds[0] = data.dungeonBounds;
        }
References Terraria.GameContent.Generation.Dungeon.DungeonData.dungeonBounds, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.dungeonEntrancePosition, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.dungeonStyle, Terraria.GameContent.Generation.Dungeon.Halls.LegacyDungeonHall.GenerateHall(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.GenerateRoom(), Terraria.GameContent.Generation.Dungeon.DungeonGenVars.generatingDungeonPositionX, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.generatingDungeonPositionY, Terraria.GameContent.Generation.Dungeon.DungeonData.genVars, Terraria.Localization.Language.GetTextValue(), int, Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GetHall_Legacy(), Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GetRoom(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.GameContent.Generation.Dungeon.DungeonGenVars.outerPotentialDungeonBounds, Terraria.GameContent.Generation.Dungeon.DungeonData.outerProgressionBounds, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.preGenDungeonEntranceSettings, Terraria.GameContent.Generation.Dungeon.DungeonBounds.UpdateBounds(), and Terraria.GameContent.Generation.Dungeon.DungeonUtils.UpdateDungeonProgress().
Referenced by Terraria.GameContent.Generation.Dungeon.LayoutProviders.LegacyDungeonLayoutProvider.ProvideLayout().