Terraria Decompiled: Terraria.GameContent.Biomes.DesertBiome.Place
Place()
override bool Terraria.GameContent.Biomes.DesertBiome.Place (Point origin, StructureMap structures, GenerationProgress progress) inline
Definition at line 13 of file DesertBiome.cs.
        {
            DesertDescription desertDescription = DesertDescription.CreateFromPlacement(origin);
            if (!desertDescription.IsValid)
            {
                return false;
            }
            DesertBiome.ExportDescriptionToEngine(desertDescription);
            SandMound.Place(desertDescription, progress, 0f, 0.1f);
            desertDescription.UpdateSurfaceMap();
            if (!Main.tenthAnniversaryWorld && GenBase._random.NextDouble() <= this.ChanceOfEntrance && !WorldGen.SecretSeed.extraLiquid.Enabled)
            {
                switch (GenBase._random.Next(4))
                {
                case 0:
                    ChambersEntrance.Place(desertDescription, progress, 0.1f, 0.2f);
                    break;
                case 1:
                    AnthillEntrance.Place(desertDescription, progress, 0.1f, 0.2f);
                    break;
                case 2:
                    LarvaHoleEntrance.Place(desertDescription, progress, 0.1f, 0.2f);
                    break;
                case 3:
                    PitEntrance.Place(desertDescription, progress, 0.1f, 0.2f);
                    break;
                }
            }
            DesertHive.Place(desertDescription, progress, 0.2f, 0.75f);
            DesertBiome.CleanupArea(desertDescription.Hive, progress, 0.75f, 1f);
            Rectangle rectangle = new Rectangle(desertDescription.CombinedArea.X, 50, desertDescription.CombinedArea.Width, desertDescription.CombinedArea.Bottom - 20);
            structures.AddStructure(rectangle, 10);
            return true;
        }
References Terraria.WorldBuilding.GenBase._random, Terraria.WorldBuilding.StructureMap.AddStructure(), Microsoft.Xna.Framework.Rectangle.Bottom, Terraria.GameContent.Biomes.DesertBiome.CleanupArea(), Terraria.GameContent.Biomes.Desert.DesertDescription.CombinedArea, Terraria.GameContent.Biomes.Desert.DesertDescription.CreateFromPlacement(), Terraria.GameContent.Biomes.DesertBiome.ExportDescriptionToEngine(), Terraria.WorldGen.SecretSeed.extraLiquid, Terraria.GameContent.Biomes.Desert.DesertDescription.Hive, Terraria.GameContent.Biomes.Desert.DesertDescription.IsValid, Terraria.GameContent.Biomes.Desert.AnthillEntrance.Place(), Terraria.GameContent.Biomes.Desert.ChambersEntrance.Place(), Terraria.GameContent.Biomes.Desert.DesertHive.Place(), Terraria.GameContent.Biomes.Desert.LarvaHoleEntrance.Place(), Terraria.GameContent.Biomes.Desert.PitEntrance.Place(), Terraria.GameContent.Biomes.Desert.SandMound.Place(), Terraria.Main.tenthAnniversaryWorld, Terraria.GameContent.Biomes.Desert.DesertDescription.UpdateSurfaceMap(), Microsoft.Xna.Framework.Rectangle.Width, and Microsoft.Xna.Framework.Rectangle.X.
Referenced by Terraria.WorldGen.AddPasses().