Terraria Decompiled: Terraria.GameContent.Biomes.DesertBiome.CleanupArea
CleanupArea()
static void Terraria.GameContent.Biomes.DesertBiome.CleanupArea (Rectangle area, GenerationProgress progress, float progressMin, float progressMax) inline static private
Definition at line 57 of file DesertBiome.cs.
        {
            int num = 20 - area.Left;
            int num2 = num + area.Right + 20;
            for (int i = -20 + area.Left; i < area.Right + 20; i++)
            {
                progress.Set((double)((float)(i + num) / (float)num2), (double)progressMin, (double)progressMax);
                for (int j = -20 + area.Top; j < area.Bottom + 20; j++)
                {
                    if (i > 0 && i < Main.maxTilesX - 1 && j > 0 && j < Main.maxTilesY - 1)
                    {
                        WorldGen.SquareWallFrame(i, j, true);
                        WorldUtils.TileFrame(i, j, true);
                    }
                }
            }
        }
References Microsoft.Xna.Framework.Rectangle.Left, Terraria.Main.maxTilesY, Terraria.WorldBuilding.GenerationProgress.Set(), Terraria.WorldGen.SquareWallFrame(), Terraria.WorldBuilding.WorldUtils.TileFrame(), and Microsoft.Xna.Framework.Rectangle.Top.
Referenced by Terraria.GameContent.Biomes.DesertBiome.Place().