Terraria Decompiled: Terraria.Graphics.StormLightningDrawer.Draw
Draw()
void Terraria.Graphics.StormLightningDrawer.Draw (Vector2[] positions, float[] rotations, float width, Color color, float progress, bool isMainBolt, FloatRange progressRange, float intensity) inline
Definition at line 13 of file StormLightningDrawer.cs.
        {
            this._width = width;
            this._color = color;
            this._isMainBolt = isMainBolt;
            this._progress = progress;
            this._progressRange = progressRange;
            this._taperEnd = this._progressRange.Maximum < 1f;
            MiscShaderData miscShaderData = GameShaders.Misc["StormLightning"];
            miscShaderData.UseSaturation(intensity);
            miscShaderData.UseOpacity(Utils.Remap(this._progress, 0.1f, 0.25f, 0.5f, 1f, true) * Utils.Remap(this._progress, 0.25f, 0.75f, 1f, 0f, true));
            miscShaderData.Apply(null);
            StormLightningDrawer._vertexStrip.PrepareStrip(positions, rotations, new VertexStrip.StripColorFunction(this.StripColors), new VertexStrip.StripHalfWidthFunction(this.StripWidth), -Main.screenPosition, null, false);
            StormLightningDrawer._vertexStrip.DrawTrail();
            Main.graphics.GraphicsDevice.SamplerStates[0] = SamplerState.PointClamp;
            Main.pixelShader.CurrentTechnique.Passes[0].Apply();
        }
References Terraria.Graphics.StormLightningDrawer._vertexStrip, Terraria.Graphics.Shaders.MiscShaderData.Apply(), Microsoft.Xna.Framework.Graphics.Effect.CurrentTechnique, Terraria.Graphics.VertexStrip.DrawTrail(), Terraria.Main.graphics, Microsoft.Xna.Framework.GraphicsDeviceManager.GraphicsDevice, Terraria.Graphics.Shaders.GameShaders.Misc, Microsoft.Xna.Framework.Graphics.EffectTechnique.Passes, Terraria.Main.pixelShader, Microsoft.Xna.Framework.Graphics.SamplerState.PointClamp, Terraria.Graphics.VertexStrip.PrepareStrip(), Terraria.Utils.Remap(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.SamplerStates, Terraria.Main.screenPosition, Terraria.Graphics.VertexStrip.StripColorFunction(), Terraria.Graphics.VertexStrip.StripHalfWidthFunction(), Terraria.Graphics.Shaders.MiscShaderData.UseOpacity(), and Terraria.Graphics.Shaders.MiscShaderData.UseSaturation().
Referenced by Terraria.Graphics.Renderers.StormLightningParticle.Draw().