Terraria Decompiled: Microsoft.Xna.Framework.Input.GamePadThumbSticks.ApplyDeadZone
ApplyDeadZone()
void Microsoft.Xna.Framework.Input.GamePadThumbSticks.ApplyDeadZone (GamePadDeadZone dz) inline private
Definition at line 51 of file GamePadThumbSticks.cs.
        {
            switch (dz)
            {
            case GamePadDeadZone.None:
                break;
            case GamePadDeadZone.IndependentAxes:
                this.left.X = GamePad.ExcludeAxisDeadZone(this.left.X, 0.23953247f);
                this.left.Y = GamePad.ExcludeAxisDeadZone(this.left.Y, 0.23953247f);
                this.right.X = GamePad.ExcludeAxisDeadZone(this.right.X, 0.26516724f);
                this.right.Y = GamePad.ExcludeAxisDeadZone(this.right.Y, 0.26516724f);
                return;
            case GamePadDeadZone.Circular:
                this.left = GamePadThumbSticks.ExcludeCircularDeadZone(this.left, 0.23953247f);
                this.right = GamePadThumbSticks.ExcludeCircularDeadZone(this.right, 0.26516724f);
                break;
            default:
                return;
            }
        }
References Microsoft.Xna.Framework.Input.GamePad.ExcludeAxisDeadZone(), Microsoft.Xna.Framework.Input.GamePadThumbSticks.ExcludeCircularDeadZone(), Microsoft.Xna.Framework.Input.GamePadThumbSticks.left, Microsoft.Xna.Framework.Input.GamePadThumbSticks.right, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Microsoft.Xna.Framework.Input.GamePadThumbSticks.GamePadThumbSticks().