Terraria Decompiled: ReLogic.Graphics.DynamicSpriteFont.GetCharacterData
GetCharacterData()
DynamicSpriteFont.SpriteCharacterData ReLogic.Graphics.DynamicSpriteFont.GetCharacterData (char character) inline private
Definition at line 172 of file DynamicSpriteFont.cs.
        {
            DynamicSpriteFont.SpriteCharacterData defaultCharacterData;
            if (!this._spriteCharacters.TryGetValue(character, ref defaultCharacterData))
            {
                defaultCharacterData = this._defaultCharacterData;
            }
            return defaultCharacterData;
        }
References ReLogic.Graphics.DynamicSpriteFont._defaultCharacterData, and ReLogic.Graphics.DynamicSpriteFont._spriteCharacters.
Referenced by ReLogic.Graphics.DynamicSpriteFont.GetCharacterMetrics(), ReLogic.Graphics.DynamicSpriteFont.InternalDraw(), and ReLogic.Graphics.DynamicSpriteFont.MeasureString().