Terraria Decompiled: Terraria.GameContent.Biomes.Desert.SandMound.Place
Place()
static void Terraria.GameContent.Biomes.Desert.SandMound.Place (DesertDescription description, GenerationProgress progress, float progressMin, float progressMax) inline static
Definition at line 11 of file SandMound.cs.
        {
            Rectangle desert = description.Desert;
            desert.Height = Math.Min(description.Desert.Height, description.Hive.Height / 2);
            Rectangle desert2 = description.Desert;
            desert2.Y = desert.Bottom;
            desert2.Height = Math.Max(0, description.Desert.Bottom - desert.Bottom);
            SurfaceMap surface = description.Surface;
            int num = 0;
            int num2 = 0;
            progress.Set((double)progressMin);
            int num3 = desert.Width + 5;
            for (int i = -5; i < num3; i++)
            {
                double num4 = Math.Abs((double)(i + 5) / (double)(desert.Width + 10)) * 2.0 - 1.0;
                num4 = Utils.Clamp<double>(num4, -1.0, 1.0);
                progress.Set((double)((float)(i + 5) / (float)(num3 + 5)), (double)progressMin, (double)progressMax);
                if (i % 3 == 0)
                {
                    num += WorldGen.genRand.Next(-1, 2);
                    num = Utils.Clamp<int>(num, -10, 10);
                }
                num2 += WorldGen.genRand.Next(-1, 2);
                num2 = Utils.Clamp<int>(num2, -10, 10);
                double num5 = Math.Sqrt(1.0 - num4 * num4 * num4 * num4);
                int num6 = desert.Bottom - (int)(num5 * (double)desert.Height) + num;
                if (Math.Abs(num4) < 1.0)
                {
                    double num7 = Utils.UnclampedSmoothStep(0.5, 0.8, Math.Abs(num4));
                    num7 = num7 * num7 * num7;
                    int num8 = 10 + (int)((double)desert.Top - num7 * 20.0) + num2;
                    num8 = Math.Min(num8, num6);
                    for (int j = (int)(surface[i + desert.X] - 1); j < num8; j++)
                    {
                        int num9 = i + desert.X;
                        int num10 = j;
                        Main.tile[num9, num10].active(false);
                        Main.tile[num9, num10].wall = 0;
                    }
                }
                SandMound.PlaceSandColumn(i + desert.X, num6, desert2.Bottom - num6);
            }
        }
References System.Math.Abs(), Terraria.Tile.active(), Microsoft.Xna.Framework.Rectangle.Bottom, Terraria.Utils.Clamp(), Terraria.GameContent.Biomes.Desert.DesertDescription.Desert, Terraria.WorldGen.genRand, Microsoft.Xna.Framework.Rectangle.Height, Terraria.GameContent.Biomes.Desert.DesertDescription.Hive, int, System.Math.Max(), System.Math.Min(), Terraria.GameContent.Biomes.Desert.SandMound.PlaceSandColumn(), Terraria.WorldBuilding.GenerationProgress.Set(), System.Math.Sqrt(), Terraria.GameContent.Biomes.Desert.DesertDescription.Surface, Terraria.Main.tile, Terraria.Utils.UnclampedSmoothStep(), Terraria.Tile.wall, Microsoft.Xna.Framework.Rectangle.Width, and Microsoft.Xna.Framework.Rectangle.X.
Referenced by Terraria.GameContent.Biomes.DesertBiome.Place().