Terraria Decompiled: ReLogic.Graphics.DynamicSpriteFont.InternalDraw
InternalDraw() [2/2]
void ReLogic.Graphics.DynamicSpriteFont.InternalDraw (string text, SpriteBatch spriteBatch, Vector2 startPosition, Color color, float rotation, Vector2 origin, ref Vector2 scale, SpriteEffects spriteEffects, float depth, Vector2[] charOffsets, Color[] charColors, float[] charRotations) inline package
Definition at line 89 of file DynamicSpriteFont.cs.
        {
            Matrix matrix = Matrix.CreateTranslation(-origin.X * scale.X, -origin.Y * scale.Y, 0f) * Matrix.CreateRotationZ(rotation);
            Vector2 zero = Vector2.Zero;
            Vector2 one = Vector2.One;
            bool flag = true;
            float num = 0f;
            if (spriteEffects != null)
            {
                Vector2 vector = this.MeasureString(text);
                if ((spriteEffects & 1) != null)
                {
                    num = vector.X * scale.X;
                    one.X = -1f;
                }
                if ((spriteEffects & 2) != null)
                {
                    zero.Y = (vector.Y - (float)this.LineSpacing) * scale.Y;
                    one.Y = -1f;
                }
            }
            zero.X = num;
            for (int i = 0; i < text.Length; i++)
            {
                char c = text.get_Chars(i);
                if (c != '\n')
                {
                    if (c != '\r')
                    {
                        DynamicSpriteFont.SpriteCharacterData characterData = this.GetCharacterData(c);
                        Vector3 kerning = characterData.Kerning;
                        Rectangle padding = characterData.Padding;
                        if ((spriteEffects & 1) != null)
{
                            padding.X -= padding.Width;
                        }
                        if ((spriteEffects & 2) != null)
{
                            padding.Y = this.LineSpacing - characterData.Glyph.Height - padding.Y;
                        }
                        if (flag)
{
                            kerning.X = Math.Max(kerning.X, 0f);
                        }
                        else
{
                            zero.X += this.CharacterSpacing * scale.X * one.X;
                        }
                        zero.X += kerning.X * scale.X * one.X;
                        Color color2 = color;
                        if (charColors != null)
{
                            color2 = charColors[i];
                        }
                        float num2 = rotation;
                        if (charRotations != null)
{
                            num2 += charRotations[i];
                        }
                        Vector2 vector2 = zero;
                        vector2.X += (float)padding.X * scale.X;
                        vector2.Y += (float)padding.Y * scale.Y;
                        if (charOffsets != null)
{
                            vector2 += charOffsets[i];
                        }
                        Vector2.Transform(ref vector2, ref matrix, ref vector2);
                        vector2 += startPosition;
                        spriteBatch.Draw(characterData.Texture, vector2, new Rectangle?(characterData.Glyph), color2, num2, Vector2.Zero, scale, spriteEffects, depth);
                        zero.X += (kerning.Y + kerning.Z) * scale.X * one.X;
                        flag = false;
                    }
                }
                else
                {
                    zero.X = num;
                    zero.Y += (float)this.LineSpacing * scale.Y * one.Y;
                    flag = true;
                }
            }
        }
References Microsoft.Xna.Framework.Matrix.CreateRotationZ(), Microsoft.Xna.Framework.Matrix.CreateTranslation(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), ReLogic.Graphics.DynamicSpriteFont.GetCharacterData(), ReLogic.Graphics.DynamicSpriteFont.SpriteCharacterData.Glyph, ReLogic.Graphics.DynamicSpriteFont.SpriteCharacterData.Kerning, ReLogic.Graphics.DynamicSpriteFont.LineSpacing, System.Math.Max(), ReLogic.Graphics.DynamicSpriteFont.MeasureString(), Microsoft.Xna.Framework.Vector2.One, ReLogic.Graphics.DynamicSpriteFont.SpriteCharacterData.Padding, System.text, ReLogic.Graphics.DynamicSpriteFont.SpriteCharacterData.Texture, Microsoft.Xna.Framework.Vector2.Transform(), Microsoft.Xna.Framework.Rectangle.Width, Microsoft.Xna.Framework.Rectangle.X, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector3.X, Microsoft.Xna.Framework.Rectangle.Y, Microsoft.Xna.Framework.Vector2.Y, Microsoft.Xna.Framework.Vector3.Z, and Microsoft.Xna.Framework.Vector2.Zero.