Terraria Decompiled: Terraria.Net.NetManager.Instance
Instance
readonly NetManager Terraria.Net.NetManager.Instance = new NetManager() static
Definition at line 195 of file NetManager.cs.
Referenced by Terraria.GameContent.BannerSystem.AddClaimableBanner(), Terraria.GameContent.BannerSystem.AddKill(), Terraria.GameContent.Items.TagEffectState.ApplyTagToNPC(), Terraria.GameContent.Creative.CreativePowers.ASharedSliderPower.AttemptPushingChange(), Terraria.GameContent.NetModules.NetLiquidModule.BroadcastAllChanges(), Terraria.GameContent.UnbreakableWallScan.NetModule.BroadcastChange(), Terraria.Chat.ChatHelper.BroadcastChatMessageAs(), Terraria.GameContent.NetModules.NetLiquidModule.BroadcastEachChunkSeparately(), Terraria.GameContent.Drawing.ParticleOrchestrator.BroadcastOrRequestParticleSpawn(), Terraria.GameContent.Drawing.ParticleOrchestrator.BroadcastParticleSpawn(), Terraria.GameContent.Items.TagEffectState.ClearProcOnNPC(), Terraria.Net.NetModule.CreatePacket< T >(), Terraria.GameContent.Creative.CreativePowers.APerPlayerSliderPower.DebugCall(), Terraria.GameContent.Creative.CreativePowers.ASharedSliderPower.DebugCall(), Terraria.GameContent.Items.TagEffectState.NetModule.Deserialize(), Terraria.GameContent.NetModules.NetCreativeUnlocksPlayerReportModule.Deserialize(), Terraria.GameContent.NetModules.NetParticlesModule.Deserialize(), Terraria.GameContent.NetModules.NetPingModule.Deserialize(), Terraria.GameContent.Creative.CreativePowers.ASharedTogglePower.DeserializeNetMessage(), Terraria.GameContent.Creative.CreativePowers.ASharedSliderPower.DeserializeNetMessage(), Terraria.Chat.ChatHelper.DisplayMessageOnClient(), Terraria.GameContent.Items.TagEffectState.EnableProcOnNPC(), Terraria.MessageBuffer.GetData(), Terraria.GameContent.BannerSystem.HandleBannerClaimRequest(), Terraria.GameContent.CraftingRequests.HandleRequest(), Terraria.Initializers.NetworkInitializer.Load(), Terraria.GameContent.Bestiary.NPCKillsTracker.OnPlayerJoining(), Terraria.GameContent.Bestiary.NPCWasChatWithTracker.OnPlayerJoining(), Terraria.GameContent.Bestiary.NPCWasNearPlayerTracker.OnPlayerJoining(), Terraria.GameContent.Creative.CreativePowers.APerPlayerTogglePower.OnPlayerJoining(), Terraria.GameContent.Creative.CreativePowers.ASharedTogglePower.OnPlayerJoining(), Terraria.GameContent.Creative.CreativePowers.ASharedSliderPower.OnPlayerJoining(), Terraria.GameContent.TeleportPylonsSystem.OnPlayerJoining(), Terraria.GameContent.NetModules.NetLiquidModule.PrepareAndSendToEachPlayerSeparately(), Terraria.Testing.ChatCommands.DebugCommandProcessor.Process(), Terraria.GameContent.Creative.CreativePowers.APerPlayerSliderPower.PushChange(), Terraria.GameContent.Bestiary.NPCWasChatWithTracker.RegisterChatStartWith(), Terraria.GameContent.Bestiary.NPCKillsTracker.RegisterKill(), Terraria.GameContent.Bestiary.NPCWasNearPlayerTracker.RegisterWasNearby(), Terraria.GameContent.LeashedEntity.NetModule.Remove(), Terraria.GameContent.BannerSystem.RequestBannerClaim(), Terraria.GameContent.Drawing.ParticleOrchestrator.RequestParticleSpawn(), Terraria.GameContent.TeleportPylonsSystem.RequestTeleportation(), Terraria.GameContent.Creative.CreativePowers.APerPlayerTogglePower.RequestUse(), Terraria.GameContent.Creative.CreativePowers.ASharedButtonPower.RequestUse(), Terraria.GameContent.Creative.CreativePowers.ASharedTogglePower.RequestUse(), Terraria.GameContent.Creative.CreativeUI.SacrificeItem(), Terraria.Chat.ChatHelper.SendChatMessageFromClient(), Terraria.Chat.ChatHelper.SendChatMessageToClientAs(), Terraria.GameContent.Creative.CreativePowers.APerPlayerTogglePower.SetEnabledState(), Terraria.GameContent.Ambience.AmbienceServer.SpawnForPlayer(), Terraria.GameContent.LeashedEntity.NetModule.Sync(), Terraria.GameContent.Items.TagEffectState.NetModule.SyncStateIfNecessary(), Terraria.GameContent.Creative.CreativePowerManager.SyncThingsToJoiningPlayer(), Terraria.Main.TriggerPing(), Terraria.GameContent.Items.TagEffectState.TrySetActiveEffect(), and Terraria.GameContent.TeleportPylonsSystem.UpdatePylonsListAndBroadcastChanges().