Terraria Decompiled: Terraria.Net.NetManager.SendToServer
SendToServer()
void Terraria.Net.NetManager.SendToServer (NetPacket packet) inline
Definition at line 141 of file NetManager.cs.
        {
            this.SendData(Netplay.Connection.Socket, packet);
            packet.Recycle();
        }
References Terraria.Netplay.Connection, Terraria.Net.NetPacket.Recycle(), Terraria.Net.NetManager.SendData(), and Terraria.RemoteServer.Socket.
Referenced by Terraria.GameContent.Items.TagEffectState.ApplyTagToNPC(), Terraria.GameContent.Items.TagEffectState.ClearProcOnNPC(), Terraria.GameContent.Items.TagEffectState.EnableProcOnNPC(), Terraria.Testing.ChatCommands.DebugCommandProcessor.Process(), Terraria.GameContent.Drawing.ParticleOrchestrator.RequestParticleSpawn(), Terraria.GameContent.Creative.CreativeUI.SacrificeItem(), Terraria.Chat.ChatHelper.SendChatMessageFromClient(), Terraria.Net.NetManager.SendToServerOrBroadcast(), Terraria.Net.NetManager.SendToServerOrLoopback(), Terraria.Main.TriggerPing(), and Terraria.GameContent.Items.TagEffectState.TrySetActiveEffect().