Terraria Decompiled: Steamworks.SteamNetworkingSockets.SendMessageToConnection
SendMessageToConnection()
static EResult Steamworks.SteamNetworkingSockets.SendMessageToConnection (HSteamNetConnection hConn, IntPtr pData, uint cbData, int nSendFlags, out long pOutMessageNumber) inline static
Definition at line 99 of file SteamNetworkingSockets.cs.
        {
            InteropHelp.TestIfAvailableClient();
            return NativeMethods.ISteamNetworkingSockets_SendMessageToConnection(CSteamAPIContext.GetSteamNetworkingSockets(), hConn, pData, cbData, nSendFlags, out pOutMessageNumber);
        }
References Steamworks.CSteamAPIContext.GetSteamNetworkingSockets(), Steamworks.NativeMethods.ISteamNetworkingSockets_SendMessageToConnection(), and Steamworks.InteropHelp.TestIfAvailableClient().