Terraria Decompiled: Steamworks.SteamNetworkingSockets.ReceiveMessagesOnConnection
ReceiveMessagesOnConnection()
static int Steamworks.SteamNetworkingSockets.ReceiveMessagesOnConnection (HSteamNetConnection hConn, IntPtr[] ppOutMessages, int nMaxMessages) inline static
Definition at line 120 of file SteamNetworkingSockets.cs.
        {
            InteropHelp.TestIfAvailableClient();
            if (ppOutMessages != null && ppOutMessages.Length != nMaxMessages)
            {
                throw new ArgumentException("ppOutMessages must be the same size as nMaxMessages!");
            }
            return NativeMethods.ISteamNetworkingSockets_ReceiveMessagesOnConnection(CSteamAPIContext.GetSteamNetworkingSockets(), hConn, ppOutMessages, nMaxMessages);
        }
References Steamworks.CSteamAPIContext.GetSteamNetworkingSockets(), Steamworks.NativeMethods.ISteamNetworkingSockets_ReceiveMessagesOnConnection(), and Steamworks.InteropHelp.TestIfAvailableClient().