Terraria Decompiled: System.Threading.Tasks.UnwrapPromise.TrySetFromTask
TrySetFromTask()
bool System.Threading.Tasks.UnwrapPromise< TResult >.TrySetFromTask (Task task, bool lookForOce) inline private
Definition at line 98 of file UnwrapPromise.cs.
        {
            if (DebuggerSupport.LoggingOn)
            {
                DebuggerSupport.TraceOperationRelation(CausalityTraceLevel.Important, this, CausalityRelation.Join);
            }
            bool flag = false;
            switch (task.Status)
            {
            case TaskStatus.RanToCompletion:
            {
                Task<TResult> task2 = task as Task<TResult>;
                if (DebuggerSupport.LoggingOn)
                {
                    DebuggerSupport.TraceOperationCompletion(CausalityTraceLevel.Required, this, AsyncStatus.Completed);
                }
                DebuggerSupport.RemoveFromActiveTasks(this);
                flag = base.TrySetResult((task2 != null) ? task2.Result : default(TResult));
                break;
            }
            case TaskStatus.Canceled:
                flag = base.TrySetCanceled(task.CancellationToken, task.GetCancellationExceptionDispatchInfo());
                break;
            case TaskStatus.Faulted:
            {
                ReadOnlyCollection<ExceptionDispatchInfo> exceptionDispatchInfos = task.GetExceptionDispatchInfos();
                ExceptionDispatchInfo exceptionDispatchInfo;
                OperationCanceledException ex;
                if (lookForOce && exceptionDispatchInfos.Count > 0 && (exceptionDispatchInfo = exceptionDispatchInfos[0]) != null && (ex = exceptionDispatchInfo.SourceException as OperationCanceledException) != null)
                {
                    flag = base.TrySetCanceled(ex.CancellationToken, exceptionDispatchInfo);
                }
                else
                {
                    flag = base.TrySetException(exceptionDispatchInfos);
                }
                break;
            }
            }
            return flag;
        }
References System.OperationCanceledException.CancellationToken, System.Collections.ObjectModel.ReadOnlyCollection< T >.Count, System.Threading.Tasks.DebuggerSupport.LoggingOn, System.Threading.Tasks.DebuggerSupport.RemoveFromActiveTasks(), System.Threading.Tasks.Task< TResult >.Result, System.task, System.Threading.Tasks.DebuggerSupport.TraceOperationCompletion(), and System.Threading.Tasks.DebuggerSupport.TraceOperationRelation().
Referenced by System.Threading.Tasks.UnwrapPromise< TResult >.InvokeCore(), System.Threading.Tasks.UnwrapPromise< TResult >.ProcessCompletedOuterTask(), and System.Threading.Tasks.UnwrapPromise< TResult >.ProcessInnerTask().