Terraria Decompiled: Terraria.TileObject.DrawPreview
DrawPreview()
static void Terraria.TileObject.DrawPreview (SpriteBatch sb, TileObjectPreviewData op, Vector2 position, float opacity) inline static
Definition at line 874 of file TileObject.cs.
        {
            Point16 coordinates = op.Coordinates;
            Texture2D value = TextureAssets.Tile[(int)op.Type].Value;
            TileObjectData tileData = TileObjectData.GetTileData((int)op.Type, (int)op.Style, op.Alternate);
            int num = tileData.CalculatePlacementStyle((int)op.Style, op.Alternate, op.Random);
            int num2 = 0;
            int num3 = tileData.DrawYOffset;
            int drawXOffset = tileData.DrawXOffset;
            num += tileData.DrawStyleOffset;
            int num4 = tileData.StyleWrapLimit;
            int num5 = tileData.StyleLineSkip;
            if (tileData.StyleWrapLimitVisualOverride != null)
            {
                num4 = tileData.StyleWrapLimitVisualOverride.Value;
            }
            if (tileData.styleLineSkipVisualOverride != null)
            {
                num5 = tileData.styleLineSkipVisualOverride.Value;
            }
            if (num4 > 0)
            {
                num2 = num / num4 * num5;
                num %= num4;
            }
            int num6;
            int num7;
            if (tileData.StyleHorizontal)
            {
                num6 = tileData.CoordinateFullWidth * num;
                num7 = tileData.CoordinateFullHeight * num2;
            }
            else
            {
                num6 = tileData.CoordinateFullWidth * num2;
                num7 = tileData.CoordinateFullHeight * num;
            }
            for (int i = 0; i < (int)op.Size.X; i++)
            {
                int num8 = num6 + (i - (int)op.ObjectStart.X) * (tileData.CoordinateWidth + tileData.CoordinatePadding);
                int num9 = num7;
                int j = 0;
                while (j < (int)op.Size.Y)
                {
                    int num10 = (int)coordinates.X + i;
                    int num11 = (int)coordinates.Y + j;
                    if (j == 0 && tileData.DrawStepDown != 0 && WorldGen.SolidTile(Framing.GetTileSafely(num10, num11 - 1)))
                    {
                        num3 += tileData.DrawStepDown;
                    }
                    if (op.Type == 567)
                    {
                        if (j == 0)
{
                            num3 = tileData.DrawYOffset - 2;
                        }
                        else
{
                            num3 = tileData.DrawYOffset;
                        }
                    }
                    int num12 = op[i, j];
                    Color color;
                    if (num12 == 1)
                    {
                        color = Color.White;
                        goto IL_01D7;
                    }
                    if (num12 == 2)
                    {
                        color = Color.Red * 0.7f;
                        goto IL_01D7;
                    }
                    IL_04EC:
                    j++;
                    continue;
                    IL_01D7:
                    color *= 0.5f;
                    color *= opacity;
                    if (i >= (int)op.ObjectStart.X && i < (int)op.ObjectStart.X + tileData.Width && j >= (int)op.ObjectStart.Y && j < (int)op.ObjectStart.Y + tileData.Height)
                    {
                        SpriteEffects spriteEffects = SpriteEffects.None;
                        if (tileData.DrawFlipHorizontal && num10 % 2 == 0)
{
                            spriteEffects |= SpriteEffects.FlipHorizontally;
                        }
                        if (tileData.DrawFlipVertical && num11 % 2 == 0)
{
                            spriteEffects |= SpriteEffects.FlipVertically;
                        }
                        int coordinateWidth = tileData.CoordinateWidth;
                        int num13 = tileData.CoordinateHeights[j - (int)op.ObjectStart.Y];
                        float num14 = (float)(coordinateWidth - 16) / 2f;
                        if (op.Type >= 0 && TileID.Sets.DoNotAdjustDrawPositionBasedOnTileWidth[(int)op.Type])
{
                            num14 = 0f;
                        }
                        Vector2 vector = new Vector2((float)(num10 * 16 - (int)(position.X + num14 + (float)drawXOffset)), (float)(num11 * 16 - (int)position.Y + num3));
                        Rectangle rectangle = new Rectangle(num8, num9, coordinateWidth, num13);
                        if (tileData.DrawFrameOffsets != null)
{
                            Rectangle rectangle2 = tileData.DrawFrameOffsets[i - (int)op.ObjectStart.X, j - (int)op.ObjectStart.Y];
                            rectangle.X += rectangle2.X;
                            rectangle.Y += rectangle2.Y;
                            rectangle.Width += rectangle2.Width;
                            rectangle.Height += rectangle2.Height;
                        }
                        if (TileID.Sets.CritterCageLidStyle[(int)op.Type] >= 0)
{
                            int num15 = TileID.Sets.CritterCageLidStyle[(int)op.Type];
                            if ((num15 < 3 && rectangle.Y % 54 == 0) || (num15 >= 3 && rectangle.Y % 36 == 0))
{
                                Vector2 vector2 = vector;
                                vector2.Y += 8f;
                                Rectangle rectangle3 = rectangle;
                                rectangle3.Y += 8;
                                rectangle3.Height -= 8;
                                Main.spriteBatch.Draw(value, vector2, new Rectangle?(rectangle3), color, 0f, Vector2.Zero, 1f, spriteEffects, 0f);
                                vector2 = vector;
                                vector2.Y -= 2f;
                                rectangle3 = rectangle;
                                if (num15 == 0)
{
                                    rectangle3.X = rectangle.X % 108;
                                }
                                rectangle3.Y = 0;
                                rectangle3.Height = 10;
                                Main.spriteBatch.Draw(TextureAssets.CageTop[num15].Value, vector2, new Rectangle?(rectangle3), color, 0f, Vector2.Zero, 1f, spriteEffects, 0f);
                            }
                            else
{
                                sb.Draw(value, vector, new Rectangle?(rectangle), color, 0f, Vector2.Zero, 1f, spriteEffects, 0f);
                            }
                        }
                        else
{
                            sb.Draw(value, vector, new Rectangle?(rectangle), color, 0f, Vector2.Zero, 1f, spriteEffects, 0f);
                        }
                        num9 += num13 + tileData.CoordinatePadding;
                        goto IL_04EC;
                    }
                    goto IL_04EC;
                }
            }
        }
References Terraria.DataStructures.TileObjectPreviewData.Alternate, Terraria.GameContent.TextureAssets.CageTop, Terraria.ObjectData.TileObjectData.CalculatePlacementStyle(), Terraria.ObjectData.TileObjectData.CoordinateHeights, Terraria.ObjectData.TileObjectData.CoordinatePadding, Terraria.DataStructures.TileObjectPreviewData.Coordinates, Terraria.ObjectData.TileObjectData.CoordinateWidth, Terraria.ID.TileID.Sets.CritterCageLidStyle, Terraria.ID.TileID.Sets.DoNotAdjustDrawPositionBasedOnTileWidth, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.ObjectData.TileObjectData.DrawFlipHorizontal, Terraria.ObjectData.TileObjectData.DrawFlipVertical, Terraria.ObjectData.TileObjectData.DrawFrameOffsets, Terraria.ObjectData.TileObjectData.DrawStepDown, Terraria.ObjectData.TileObjectData.DrawStyleOffset, Terraria.ObjectData.TileObjectData.DrawXOffset, Terraria.ObjectData.TileObjectData.DrawYOffset, Terraria.ObjectData.TileObjectData.GetTileData(), Terraria.Framing.GetTileSafely(), Microsoft.Xna.Framework.Rectangle.Height, Terraria.ObjectData.TileObjectData.Height, int, Terraria.DataStructures.TileObjectPreviewData.ObjectStart, Terraria.DataStructures.TileObjectPreviewData.Random, Terraria.DataStructures.TileObjectPreviewData.Size, Terraria.WorldGen.SolidTile(), Terraria.Main.spriteBatch, Terraria.DataStructures.TileObjectPreviewData.Style, Terraria.ObjectData.TileObjectData.StyleHorizontal, Terraria.ObjectData.TileObjectData.StyleLineSkip, Terraria.ObjectData.TileObjectData.styleLineSkipVisualOverride, Terraria.ObjectData.TileObjectData.StyleWrapLimit, Terraria.ObjectData.TileObjectData.StyleWrapLimitVisualOverride, Terraria.GameContent.TextureAssets.Tile, Terraria.DataStructures.TileObjectPreviewData.Type, System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Rectangle.Width, Terraria.ObjectData.TileObjectData.Width, Microsoft.Xna.Framework.Rectangle.X, Microsoft.Xna.Framework.Vector2.X, Terraria.DataStructures.Point16.X, Microsoft.Xna.Framework.Rectangle.Y, Microsoft.Xna.Framework.Vector2.Y, Terraria.DataStructures.Point16.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.Drawing.TileDrawing.Draw().