Terraria Decompiled: Terraria.TileObject.Place
Place()
static bool Terraria.TileObject.Place (TileObject toBePlaced) inline static
Definition at line 16 of file TileObject.cs.
        {
            TileObjectData tileData = TileObjectData.GetTileData(toBePlaced.type, toBePlaced.style, toBePlaced.alternate);
            if (tileData == null)
            {
                return false;
            }
            if (tileData.HookPlaceOverride.hook != null)
            {
                int num;
                int num2;
                if (tileData.HookPlaceOverride.processedCoordinates)
                {
                    num = toBePlaced.xCoord;
                    num2 = toBePlaced.yCoord;
                }
                else
                {
                    num = toBePlaced.xCoord + (int)tileData.Origin.X;
                    num2 = toBePlaced.yCoord + (int)tileData.Origin.Y;
                }
                if (tileData.HookPlaceOverride.hook(num, num2, toBePlaced.type, toBePlaced.style, 1, toBePlaced.alternate) == tileData.HookPlaceOverride.badReturn)
                {
                    return false;
                }
            }
            else
            {
                ushort num3 = (ushort)toBePlaced.type;
                int num4 = tileData.CalculatePlacementStyle(toBePlaced.style, toBePlaced.alternate, toBePlaced.random);
                int num5 = 0;
                if (tileData.StyleWrapLimit > 0)
                {
                    num5 = num4 / tileData.StyleWrapLimit * tileData.StyleLineSkip;
                    num4 %= tileData.StyleWrapLimit;
                }
                int num6;
                int num7;
                if (tileData.StyleHorizontal)
                {
                    num6 = tileData.CoordinateFullWidth * num4;
                    num7 = tileData.CoordinateFullHeight * num5;
                }
                else
                {
                    num6 = tileData.CoordinateFullWidth * num5;
                    num7 = tileData.CoordinateFullHeight * num4;
                }
                int num8 = toBePlaced.xCoord;
                int num9 = toBePlaced.yCoord;
                for (int i = 0; i < tileData.Width; i++)
                {
                    for (int j = 0; j < tileData.Height; j++)
                    {
                        Tile tileSafely = Framing.GetTileSafely(num8 + i, num9 + j);
                        if (tileSafely.active() && tileSafely.type != 484 && (Main.tileCut[(int)tileSafely.type] || TileID.Sets.BreakableWhenPlacing[(int)tileSafely.type]))
{
                            WorldGen.KillTile(num8 + i, num9 + j, false, false, false);
                            if (!Main.tile[num8 + i, num9 + j].active() && Main.netMode != 0)
{
                                NetMessage.SendData(17, -1, -1, null, 0, (float)(num8 + i), (float)(num9 + j), 0f, 0, 0, 0);
                            }
                        }
                    }
                }
                for (int k = 0; k < tileData.Width; k++)
                {
                    int num10 = num6 + k * (tileData.CoordinateWidth + tileData.CoordinatePadding);
                    int num11 = num7;
                    for (int l = 0; l < tileData.Height; l++)
                    {
                        Tile tileSafely2 = Framing.GetTileSafely(num8 + k, num9 + l);
                        if (!tileSafely2.active())
{
                            tileSafely2.active(true);
                            tileSafely2.frameX = (short)num10;
                            tileSafely2.frameY = (short)num11;
                            tileSafely2.type = num3;
                        }
                        num11 += tileData.CoordinateHeights[l] + tileData.CoordinatePadding;
                    }
                }
            }
            if (tileData.FlattenAnchors)
            {
                AnchorData anchorData = tileData.AnchorBottom;
                if (anchorData.tileCount != 0 && (anchorData.type & AnchorType.SolidTile) == AnchorType.SolidTile)
                {
                    int num12 = toBePlaced.xCoord + anchorData.checkStart;
                    int num13 = toBePlaced.yCoord + tileData.Height;
                    for (int m = 0; m < anchorData.tileCount; m++)
                    {
                        Tile tileSafely3 = Framing.GetTileSafely(num12 + m, num13);
                        if (Main.tileSolid[(int)tileSafely3.type] && !Main.tileSolidTop[(int)tileSafely3.type] && tileSafely3.blockType() != 0)
{
                            WorldGen.SlopeTile(num12 + m, num13, 0, false, true);
                        }
                    }
                }
                anchorData = tileData.AnchorTop;
                if (anchorData.tileCount != 0 && (anchorData.type & AnchorType.SolidTile) == AnchorType.SolidTile)
                {
                    int num14 = toBePlaced.xCoord + anchorData.checkStart;
                    int num15 = toBePlaced.yCoord - 1;
                    for (int n = 0; n < anchorData.tileCount; n++)
                    {
                        Tile tileSafely4 = Framing.GetTileSafely(num14 + n, num15);
                        if (Main.tileSolid[(int)tileSafely4.type] && !Main.tileSolidTop[(int)tileSafely4.type] && tileSafely4.blockType() != 0)
{
                            WorldGen.SlopeTile(num14 + n, num15, 0, false, true);
                        }
                    }
                }
                anchorData = tileData.AnchorRight;
                if (anchorData.tileCount != 0 && (anchorData.type & AnchorType.SolidTile) == AnchorType.SolidTile)
                {
                    int num16 = toBePlaced.xCoord + tileData.Width;
                    int num17 = toBePlaced.yCoord + anchorData.checkStart;
                    for (int num18 = 0; num18 < anchorData.tileCount; num18++)
                    {
                        Tile tileSafely5 = Framing.GetTileSafely(num16, num17 + num18);
                        if (Main.tileSolid[(int)tileSafely5.type] && !Main.tileSolidTop[(int)tileSafely5.type] && tileSafely5.blockType() != 0)
{
                            WorldGen.SlopeTile(num16, num17 + num18, 0, false, true);
                        }
                    }
                }
                anchorData = tileData.AnchorLeft;
                if (anchorData.tileCount != 0 && (anchorData.type & AnchorType.SolidTile) == AnchorType.SolidTile)
                {
                    int num19 = toBePlaced.xCoord - 1;
                    int num20 = toBePlaced.yCoord + anchorData.checkStart;
                    for (int num21 = 0; num21 < anchorData.tileCount; num21++)
                    {
                        Tile tileSafely6 = Framing.GetTileSafely(num19, num20 + num21);
                        if (Main.tileSolid[(int)tileSafely6.type] && !Main.tileSolidTop[(int)tileSafely6.type] && tileSafely6.blockType() != 0)
{
                            WorldGen.SlopeTile(num19, num20 + num21, 0, false, true);
                        }
                    }
                }
            }
            return true;
        }
References Terraria.Tile.active(), Terraria.TileObject.alternate, Terraria.ObjectData.TileObjectData.AnchorBottom, Terraria.ObjectData.TileObjectData.AnchorLeft, Terraria.ObjectData.TileObjectData.AnchorRight, Terraria.ObjectData.TileObjectData.AnchorTop, Terraria.DataStructures.PlacementHook.badReturn, Terraria.Tile.blockType(), Terraria.ID.TileID.Sets.BreakableWhenPlacing, Terraria.ObjectData.TileObjectData.CalculatePlacementStyle(), Terraria.DataStructures.AnchorData.checkStart, Terraria.ObjectData.TileObjectData.CoordinateHeights, Terraria.ObjectData.TileObjectData.CoordinatePadding, Terraria.ObjectData.TileObjectData.FlattenAnchors, Terraria.ObjectData.TileObjectData.GetTileData(), Terraria.Framing.GetTileSafely(), Terraria.ObjectData.TileObjectData.Height, Terraria.DataStructures.PlacementHook.hook, Terraria.ObjectData.TileObjectData.HookPlaceOverride, int, Terraria.WorldGen.KillTile(), Terraria.Main.netMode, Terraria.ObjectData.TileObjectData.Origin, Terraria.DataStructures.PlacementHook.processedCoordinates, Terraria.TileObject.random, Terraria.NetMessage.SendData(), Terraria.WorldGen.SlopeTile(), Terraria.TileObject.style, Terraria.ObjectData.TileObjectData.StyleHorizontal, Terraria.ObjectData.TileObjectData.StyleLineSkip, Terraria.ObjectData.TileObjectData.StyleWrapLimit, Terraria.Main.tile, Terraria.DataStructures.AnchorData.tileCount, Terraria.Main.tileCut, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.DataStructures.AnchorData.type, Terraria.Tile.type, Terraria.TileObject.type, Terraria.ObjectData.TileObjectData.Width, Terraria.DataStructures.Point16.X, Terraria.TileObject.xCoord, Terraria.DataStructures.Point16.Y, and Terraria.TileObject.yCoord.
Referenced by Terraria.Projectile.AI(), Terraria.WorldGen.PlaceChest(), Terraria.WorldGen.PlaceObject(), Terraria.Player.PlaceThing_Tiles_PlaceIt(), and Terraria.Player.TryReplantingTree().