Terraria Decompiled: Terraria.Physics.BallCollision.GetLeftOrRightEdge
GetLeftOrRightEdge()
static bool Terraria.Physics.BallCollision.GetLeftOrRightEdge (BallCollision::TileEdges edgesToTest, int x, int y, Vector2 tilePosition, ref LineSegment edge) inline static private
Definition at line 346 of file BallCollision.cs.
        {
            if ((edgesToTest & BallCollision.TileEdges.Left) != BallCollision.TileEdges.None)
            {
                Tile tile = Main.tile[x, y];
                Tile tile2 = Main.tile[x - 1, y];
                if (BallCollision.IsNeighborSolid(tile2) && tile2.slope() != 1 && tile2.slope() != 3 && (!tile2.halfBrick() || tile.halfBrick()))
                {
                    return false;
                }
                edge.Start = new Vector2(tilePosition.X, tilePosition.Y);
                edge.End = new Vector2(tilePosition.X, tilePosition.Y + 16f);
                if (tile.halfBrick())
                {
                    edge.Start.Y = edge.Start.Y + 8f;
                }
                return true;
            }
            else
            {
                if ((edgesToTest & BallCollision.TileEdges.Right) == BallCollision.TileEdges.None)
                {
                    return false;
                }
                Tile tile3 = Main.tile[x, y];
                Tile tile4 = Main.tile[x + 1, y];
                if (BallCollision.IsNeighborSolid(tile4) && tile4.slope() != 2 && tile4.slope() != 4 && (!tile4.halfBrick() || tile3.halfBrick()))
                {
                    return false;
                }
                edge.Start = new Vector2(tilePosition.X + 16f, tilePosition.Y);
                edge.End = new Vector2(tilePosition.X + 16f, tilePosition.Y + 16f);
                if (tile3.halfBrick())
                {
                    edge.Start.Y = edge.Start.Y + 8f;
                }
                return true;
            }
        }
References Terraria.Tile.halfBrick(), Terraria.Physics.BallCollision.IsNeighborSolid(), Terraria.Tile.slope(), Terraria.Main.tile, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Physics.BallCollision.GetCollisionPointForTile().