Terraria Decompiled: Terraria.Physics.BallCollision.CheckForPassThrough
CheckForPassThrough()
static bool Terraria.Physics.BallCollision.CheckForPassThrough (Vector2 center, out BallPassThroughType type, out Tile contactTile) inline static private
Definition at line 83 of file BallCollision.cs.
        {
            Point point = center.ToTileCoordinates();
            Tile tile = Main.tile[point.X, point.Y];
            contactTile = tile;
            type = BallPassThroughType.None;
            if (tile == null)
            {
                return false;
            }
            if (tile.nactive())
            {
                type = BallPassThroughType.Tile;
                return BallCollision.IsPositionInsideTile(center, point, tile);
            }
            if (tile.liquid > 0)
            {
                float num = (float)(point.Y + 1) * 16f - (float)tile.liquid / 255f * 16f;
                byte b = tile.liquidType();
                if (b != 1)
                {
                    if (b != 2)
                    {
                        type = BallPassThroughType.Water;
                    }
                    else
                    {
                        type = BallPassThroughType.Honey;
                    }
                }
                else
                {
                    type = BallPassThroughType.Lava;
                }
                return num < center.Y;
            }
            return false;
        }
References Terraria.Physics.BallCollision.IsPositionInsideTile(), Terraria.Tile.liquid, Terraria.Tile.liquidType(), Terraria.Tile.nactive(), Terraria.Main.tile, Terraria.Tile.Tile(), Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Point.Y, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Physics.BallCollision.Step().