Terraria Decompiled: Terraria.Physics.BallCollision.GetCollisionPointForTile
GetCollisionPointForTile()
static bool Terraria.Physics.BallCollision.GetCollisionPointForTile (BallCollision::TileEdges edgesToTest, int x, int y, Vector2 center, ref Vector2 closestPointOut, ref float distanceSquaredOut) inline static private
Definition at line 213 of file BallCollision.cs.
        {
            Tile tile = Main.tile[x, y];
            if (tile == null || !tile.nactive() || (!Main.tileSolid[(int)tile.type] && !Main.tileSolidTop[(int)tile.type]))
            {
                return false;
            }
            if (!Main.tileSolid[(int)tile.type] && Main.tileSolidTop[(int)tile.type] && tile.frameY != 0)
            {
                return false;
            }
            if (Main.tileSolidTop[(int)tile.type])
            {
                edgesToTest &= BallCollision.TileEdges.Top | BallCollision.TileEdges.BottomLeftSlope | BallCollision.TileEdges.BottomRightSlope;
            }
            Vector2 vector = new Vector2((float)x * 16f, (float)y * 16f);
            bool flag = false;
            LineSegment lineSegment = default(LineSegment);
            if (BallCollision.GetSlopeEdge(ref edgesToTest, tile, vector, ref lineSegment))
            {
                closestPointOut = BallCollision.ClosestPointOnLineSegment(center, lineSegment);
                distanceSquaredOut = Vector2.DistanceSquared(closestPointOut, center);
                flag = true;
            }
            if (BallCollision.GetTopOrBottomEdge(edgesToTest, x, y, vector, ref lineSegment))
            {
                Vector2 vector2 = BallCollision.ClosestPointOnLineSegment(center, lineSegment);
                float num = Vector2.DistanceSquared(vector2, center);
                if (!flag || num < distanceSquaredOut)
                {
                    distanceSquaredOut = num;
                    closestPointOut = vector2;
                }
                flag = true;
            }
            if (BallCollision.GetLeftOrRightEdge(edgesToTest, x, y, vector, ref lineSegment))
            {
                Vector2 vector3 = BallCollision.ClosestPointOnLineSegment(center, lineSegment);
                float num2 = Vector2.DistanceSquared(vector3, center);
                if (!flag || num2 < distanceSquaredOut)
                {
                    distanceSquaredOut = num2;
                    closestPointOut = vector3;
                }
                flag = true;
            }
            return flag;
        }
References Terraria.Physics.BallCollision.ClosestPointOnLineSegment(), Microsoft.Xna.Framework.Vector2.DistanceSquared(), Terraria.Tile.frameY, Terraria.Physics.BallCollision.GetLeftOrRightEdge(), Terraria.Physics.BallCollision.GetSlopeEdge(), Terraria.Physics.BallCollision.GetTopOrBottomEdge(), Terraria.Tile.nactive(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, and Terraria.Tile.type.
Referenced by Terraria.Physics.BallCollision.GetClosestEdgeToCircle().