Terraria Decompiled: Terraria.Minecart.FrameTrack
FrameTrack()
static bool Terraria.Minecart.FrameTrack (int i, int j, bool pound, bool mute = false) inline static
Definition at line 966 of file Minecart.cs.
        {
            if (Minecart._trackType == null)
            {
                return false;
            }
            Tile tile = Main.tile[i, j];
            if (tile == null)
            {
                tile = new Tile();
                Main.tile[i, j] = tile;
            }
            if (mute && tile.type != 314)
            {
                return false;
            }
            int nearbyTilesSetLookupIndex = Minecart.GetNearbyTilesSetLookupIndex(i, j);
            int num = (int)tile.FrontTrack();
            int num2 = (int)tile.BackTrack();
            int num3;
            if (num >= 0 && num < Minecart._trackType.Length)
            {
                num3 = Minecart._trackType[num];
            }
            else
            {
                num3 = 0;
            }
            int num4 = -1;
            int num5 = -1;
            int[] array = Minecart._trackSwitchOptions[nearbyTilesSetLookupIndex];
            if (array != null)
            {
                if (!pound)
                {
                    int num6 = -1;
                    int num7 = -1;
                    bool flag = false;
                    for (int k = 0; k < array.Length; k++)
                    {
                        int num8 = array[k];
                        if (num2 == array[k])
{
                            num5 = k;
                        }
                        if (Minecart._trackType[num8] == num3)
{
                            if (Minecart._leftSideConnection[num8] == -1 || Minecart._rightSideConnection[num8] == -1)
{
                                if (num == array[k])
{
                                    num4 = k;
                                    flag = true;
                                }
                                if (num6 == -1)
{
                                    num6 = k;
                                }
                            }
                            else
{
                                if (num == array[k])
{
                                    num4 = k;
                                    flag = false;
                                }
                                if (num7 == -1)
{
                                    num7 = k;
                                }
                            }
                        }
                    }
                    if (num7 != -1)
                    {
                        if (num4 == -1 || flag)
{
                            num4 = num7;
                        }
                    }
                    else
                    {
                        if (num4 == -1)
{
                            if (num3 == 2)
{
                                return false;
                            }
                            if (num3 == 1)
{
                                return false;
                            }
                            num4 = num6;
                        }
                        num5 = -1;
                    }
                }
                else
                {
                    for (int l = 0; l < array.Length; l++)
                    {
                        if (num == array[l])
{
                            num4 = l;
                        }
                        if (num2 == array[l])
{
                            num5 = l;
                        }
                    }
                    int num9 = 0;
                    int num10 = 0;
                    for (int m = 0; m < array.Length; m++)
                    {
                        if (Minecart._trackType[array[m]] == num3)
{
                            if (Minecart._leftSideConnection[array[m]] == -1 || Minecart._rightSideConnection[array[m]] == -1)
{
                                num10++;
                            }
                            else
{
                                num9++;
                            }
                        }
                    }
                    if (num9 < 2 && num10 < 2)
                    {
                        return false;
                    }
                    bool flag2 = num9 == 0;
                    bool flag3 = false;
                    if (!flag2)
                    {
                        while (!flag3)
{
                            num5++;
                            if (num5 >= array.Length)
{
                                num5 = -1;
                                break;
                            }
                            if ((Minecart._leftSideConnection[array[num5]] != Minecart._leftSideConnection[array[num4]] || Minecart._rightSideConnection[array[num5]] != Minecart._rightSideConnection[array[num4]]) && Minecart._trackType[array[num5]] == num3 && Minecart._leftSideConnection[array[num5]] != -1 && Minecart._rightSideConnection[array[num5]] != -1)
{
                                flag3 = true;
                            }
                        }
                    }
                    if (!flag3)
                    {
                        for (;;)
{
                            num4++;
                            if (num4 >= array.Length)
{
                                break;
                            }
                            if (Minecart._trackType[array[num4]] == num3 && (Minecart._leftSideConnection[array[num4]] == -1 || Minecart._rightSideConnection[array[num4]] == -1) == flag2)
{
                                goto IL_02EA;
                            }
                        }
                        num4 = -1;
                        for (;;)
{
                            num4++;
                            if (Minecart._trackType[array[num4]] == num3)
{
                                if ((Minecart._leftSideConnection[array[num4]] == -1 || Minecart._rightSideConnection[array[num4]] == -1) == flag2)
{
                                    break;
                                }
                            }
                        }
                    }
                }
                IL_02EA:
                bool flag4 = false;
                if (num4 == -2)
                {
                    if (tile.FrontTrack() != Minecart._firstPressureFrame)
                    {
                        flag4 = true;
                    }
                }
                else if (num4 == -1)
                {
                    if (tile.FrontTrack() != 0)
                    {
                        flag4 = true;
                    }
                }
                else if ((int)tile.FrontTrack() != array[num4])
                {
                    flag4 = true;
                }
                if (num5 == -1)
                {
                    if (tile.BackTrack() != -1)
                    {
                        flag4 = true;
                    }
                }
                else if ((int)tile.BackTrack() != array[num5])
                {
                    flag4 = true;
                }
                if (num4 == -2)
                {
                    tile.FrontTrack(Minecart._firstPressureFrame);
                }
                else if (num4 == -1)
                {
                    tile.FrontTrack(0);
                }
                else
                {
                    tile.FrontTrack((short)array[num4]);
                }
                if (num5 == -1)
                {
                    tile.BackTrack(-1);
                }
                else
                {
                    tile.BackTrack((short)array[num5]);
                }
                if (pound && flag4 && !mute)
                {
                    WorldGen.KillTile(i, j, true, false, false);
                }
                return true;
            }
            if (pound)
            {
                return false;
            }
            tile.FrontTrack(0);
            tile.BackTrack(-1);
            return false;
        }
References Terraria.Minecart._firstPressureFrame, Terraria.Minecart._leftSideConnection, Terraria.Minecart._rightSideConnection, Terraria.Minecart._trackSwitchOptions, Terraria.Minecart._trackType, System.array, Terraria.Minecart.GetNearbyTilesSetLookupIndex(), int, Terraria.WorldGen.KillTile(), Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.Minecart.FlipSwitchTrack(), Terraria.MessageBuffer.GetData(), Terraria.Player.ItemCheck_UseMiningTools_TryPoundingTile(), Terraria.GameContent.MinecartDiggerHelper.PoundTrack(), and Terraria.WorldGen.TileFrameImportant().