Terraria Decompiled: Terraria.Minecart.FlipSwitchTrack
FlipSwitchTrack()
static void Terraria.Minecart.FlipSwitchTrack (int i, int j) inline static
Definition at line 1342 of file Minecart.cs.
        {
            Tile tile = Main.tile[i, j];
            short num = tile.FrontTrack();
            if (num == -1)
            {
                return;
            }
            int num2 = Minecart._trackType[(int)num];
            if (num2 != 0)
            {
                if (num2 != 2)
                {
                    return;
                }
                Minecart.FrameTrack(i, j, true, true);
                NetMessage.SendTileSquare(-1, i, j, TileChangeType.None);
            }
            else if (tile.BackTrack() != -1)
            {
                tile.FrontTrack(tile.BackTrack());
                tile.BackTrack(num);
                NetMessage.SendTileSquare(-1, i, j, TileChangeType.None);
                return;
            }
        }
References Terraria.Minecart._trackType, Terraria.Minecart.FrameTrack(), int, Terraria.NetMessage.SendTileSquare(), and Terraria.Main.tile.
Referenced by Terraria.Wiring.HitWireSingle().