Terraria Decompiled: Terraria.Minecart.Initialize
Initialize()
static void Terraria.Minecart.Initialize () inline static
Definition at line 12 of file Minecart.cs.
        {
            if (!Main.dedServ && (float)TextureAssets.MinecartMount.Width() != Minecart.Customization.Default.MinecartTextureWidth)
            {
                throw new Exception("Be sure to update Minecart.textureWidth to match the actual texture size of " + Minecart.Customization.Default.MinecartTextureWidth + ".");
            }
            Minecart._rightSideConnection = new int[36];
            Minecart._leftSideConnection = new int[36];
            Minecart._trackType = new int[36];
            Minecart._boostLeft = new bool[36];
            Minecart._texturePosition = new Vector2[40];
            Minecart._tileHeight = new int[36][];
            for (int i = 0; i < 36; i++)
            {
                int[] array = new int[8];
                for (int j = 0; j < array.Length; j++)
                {
                    array[j] = 5;
                }
                Minecart._tileHeight[i] = array;
            }
            int num = 0;
            Minecart._leftSideConnection[num] = -1;
            Minecart._rightSideConnection[num] = -1;
            Minecart._tileHeight[num][0] = -4;
            Minecart._tileHeight[num][7] = -4;
            Minecart._texturePosition[num] = new Vector2(0f, 0f);
            num++;
            Minecart._leftSideConnection[num] = 1;
            Minecart._rightSideConnection[num] = 1;
            Minecart._texturePosition[num] = new Vector2(1f, 0f);
            num++;
            Minecart._leftSideConnection[num] = -1;
            Minecart._rightSideConnection[num] = 1;
            for (int k = 0; k < 4; k++)
            {
                Minecart._tileHeight[num][k] = -1;
            }
            Minecart._texturePosition[num] = new Vector2(2f, 1f);
            num++;
            Minecart._leftSideConnection[num] = 1;
            Minecart._rightSideConnection[num] = -1;
            for (int l = 4; l < 8; l++)
            {
                Minecart._tileHeight[num][l] = -1;
            }
            Minecart._texturePosition[num] = new Vector2(3f, 1f);
            num++;
            Minecart._leftSideConnection[num] = 2;
            Minecart._rightSideConnection[num] = 1;
            Minecart._tileHeight[num][0] = 1;
            Minecart._tileHeight[num][1] = 2;
            Minecart._tileHeight[num][2] = 3;
            Minecart._tileHeight[num][3] = 3;
            Minecart._tileHeight[num][4] = 4;
            Minecart._tileHeight[num][5] = 4;
            Minecart._texturePosition[num] = new Vector2(0f, 2f);
            num++;
            Minecart._leftSideConnection[num] = 1;
            Minecart._rightSideConnection[num] = 2;
            Minecart._tileHeight[num][2] = 4;
            Minecart._tileHeight[num][3] = 4;
            Minecart._tileHeight[num][4] = 3;
            Minecart._tileHeight[num][5] = 3;
            Minecart._tileHeight[num][6] = 2;
            Minecart._tileHeight[num][7] = 1;
            Minecart._texturePosition[num] = new Vector2(1f, 2f);
            num++;
            Minecart._leftSideConnection[num] = 1;
            Minecart._rightSideConnection[num] = 0;
            Minecart._tileHeight[num][4] = 6;
            Minecart._tileHeight[num][5] = 6;
            Minecart._tileHeight[num][6] = 7;
            Minecart._tileHeight[num][7] = 8;
            Minecart._texturePosition[num] = new Vector2(0f, 1f);
            num++;
            Minecart._leftSideConnection[num] = 0;
            Minecart._rightSideConnection[num] = 1;
            Minecart._tileHeight[num][0] = 8;
            Minecart._tileHeight[num][1] = 7;
            Minecart._tileHeight[num][2] = 6;
            Minecart._tileHeight[num][3] = 6;
            Minecart._texturePosition[num] = new Vector2(1f, 1f);
            num++;
            Minecart._leftSideConnection[num] = 0;
            Minecart._rightSideConnection[num] = 2;
            for (int m = 0; m < 8; m++)
            {
                Minecart._tileHeight[num][m] = 8 - m;
            }
            Minecart._texturePosition[num] = new Vector2(0f, 3f);
            num++;
            Minecart._leftSideConnection[num] = 2;
            Minecart._rightSideConnection[num] = 0;
            for (int n = 0; n < 8; n++)
            {
                Minecart._tileHeight[num][n] = n + 1;
            }
            Minecart._texturePosition[num] = new Vector2(1f, 3f);
            num++;
            Minecart._leftSideConnection[num] = 2;
            Minecart._rightSideConnection[num] = -1;
            Minecart._tileHeight[num][0] = 1;
            Minecart._tileHeight[num][1] = 2;
            for (int num2 = 2; num2 < 8; num2++)
            {
                Minecart._tileHeight[num][num2] = -1;
            }
            Minecart._texturePosition[num] = new Vector2(4f, 1f);
            num++;
            Minecart._leftSideConnection[num] = -1;
            Minecart._rightSideConnection[num] = 2;
            Minecart._tileHeight[num][6] = 2;
            Minecart._tileHeight[num][7] = 1;
            for (int num3 = 0; num3 < 6; num3++)
            {
                Minecart._tileHeight[num][num3] = -1;
            }
            Minecart._texturePosition[num] = new Vector2(5f, 1f);
            num++;
            Minecart._leftSideConnection[num] = 0;
            Minecart._rightSideConnection[num] = -1;
            Minecart._tileHeight[num][0] = 8;
            Minecart._tileHeight[num][1] = 7;
            Minecart._tileHeight[num][2] = 6;
            for (int num4 = 3; num4 < 8; num4++)
            {
                Minecart._tileHeight[num][num4] = -1;
            }
            Minecart._texturePosition[num] = new Vector2(6f, 1f);
            num++;
            Minecart._leftSideConnection[num] = -1;
            Minecart._rightSideConnection[num] = 0;
            Minecart._tileHeight[num][5] = 6;
            Minecart._tileHeight[num][6] = 7;
            Minecart._tileHeight[num][7] = 8;
            for (int num5 = 0; num5 < 5; num5++)
            {
                Minecart._tileHeight[num][num5] = -1;
            }
            Minecart._texturePosition[num] = new Vector2(7f, 1f);
            num++;
            Minecart._leftSideConnection[num] = -1;
            Minecart._rightSideConnection[num] = 1;
            Minecart._tileHeight[num][0] = -4;
            Minecart._texturePosition[num] = new Vector2(2f, 0f);
            num++;
            Minecart._leftSideConnection[num] = 1;
            Minecart._rightSideConnection[num] = -1;
            Minecart._tileHeight[num][7] = -4;
            Minecart._texturePosition[num] = new Vector2(3f, 0f);
            num++;
            Minecart._leftSideConnection[num] = 2;
            Minecart._rightSideConnection[num] = -1;
            for (int num6 = 0; num6 < 6; num6++)
            {
                Minecart._tileHeight[num][num6] = num6 + 1;
            }
            Minecart._tileHeight[num][6] = -3;
            Minecart._tileHeight[num][7] = -3;
            Minecart._texturePosition[num] = new Vector2(4f, 0f);
            num++;
            Minecart._leftSideConnection[num] = -1;
            Minecart._rightSideConnection[num] = 2;
            Minecart._tileHeight[num][0] = -3;
            Minecart._tileHeight[num][1] = -3;
            for (int num7 = 2; num7 < 8; num7++)
            {
                Minecart._tileHeight[num][num7] = 8 - num7;
            }
            Minecart._texturePosition[num] = new Vector2(5f, 0f);
            num++;
            Minecart._leftSideConnection[num] = 0;
            Minecart._rightSideConnection[num] = -1;
            for (int num8 = 0; num8 < 6; num8++)
            {
                Minecart._tileHeight[num][num8] = 8 - num8;
            }
            Minecart._tileHeight[num][6] = -3;
            Minecart._tileHeight[num][7] = -3;
            Minecart._texturePosition[num] = new Vector2(6f, 0f);
            num++;
            Minecart._leftSideConnection[num] = -1;
            Minecart._rightSideConnection[num] = 0;
            Minecart._tileHeight[num][0] = -3;
            Minecart._tileHeight[num][1] = -3;
            for (int num9 = 2; num9 < 8; num9++)
            {
                Minecart._tileHeight[num][num9] = num9 + 1;
            }
            Minecart._texturePosition[num] = new Vector2(7f, 0f);
            num++;
            Minecart._leftSideConnection[num] = -1;
            Minecart._rightSideConnection[num] = -1;
            Minecart._tileHeight[num][0] = -4;
            Minecart._tileHeight[num][7] = -4;
            Minecart._trackType[num] = 1;
            Minecart._texturePosition[num] = new Vector2(0f, 4f);
            num++;
            Minecart._leftSideConnection[num] = 1;
            Minecart._rightSideConnection[num] = 1;
            Minecart._trackType[num] = 1;
            Minecart._texturePosition[num] = new Vector2(1f, 4f);
            num++;
            Minecart._leftSideConnection[num] = -1;
            Minecart._rightSideConnection[num] = 1;
            Minecart._tileHeight[num][0] = -4;
            Minecart._trackType[num] = 1;
            Minecart._texturePosition[num] = new Vector2(0f, 5f);
            num++;
            Minecart._leftSideConnection[num] = 1;
            Minecart._rightSideConnection[num] = -1;
            Minecart._tileHeight[num][7] = -4;
            Minecart._trackType[num] = 1;
            Minecart._texturePosition[num] = new Vector2(1f, 5f);
            num++;
            Minecart._leftSideConnection[num] = -1;
            Minecart._rightSideConnection[num] = 1;
            for (int num10 = 0; num10 < 6; num10++)
            {
                Minecart._tileHeight[num][num10] = -2;
            }
            Minecart._texturePosition[num] = new Vector2(2f, 2f);
            num++;
            Minecart._leftSideConnection[num] = 1;
            Minecart._rightSideConnection[num] = -1;
            for (int num11 = 2; num11 < 8; num11++)
            {
                Minecart._tileHeight[num][num11] = -2;
            }
            Minecart._texturePosition[num] = new Vector2(3f, 2f);
            num++;
            Minecart._leftSideConnection[num] = 2;
            Minecart._rightSideConnection[num] = -1;
            Minecart._tileHeight[num][0] = 1;
            Minecart._tileHeight[num][1] = 2;
            for (int num12 = 2; num12 < 8; num12++)
            {
                Minecart._tileHeight[num][num12] = -2;
            }
            Minecart._texturePosition[num] = new Vector2(4f, 2f);
            num++;
            Minecart._leftSideConnection[num] = -1;
            Minecart._rightSideConnection[num] = 2;
            Minecart._tileHeight[num][6] = 2;
            Minecart._tileHeight[num][7] = 1;
            for (int num13 = 0; num13 < 6; num13++)
            {
                Minecart._tileHeight[num][num13] = -2;
            }
            Minecart._texturePosition[num] = new Vector2(5f, 2f);
            num++;
            Minecart._leftSideConnection[num] = 0;
            Minecart._rightSideConnection[num] = -1;
            Minecart._tileHeight[num][0] = 8;
            Minecart._tileHeight[num][1] = 7;
            Minecart._tileHeight[num][2] = 6;
            for (int num14 = 3; num14 < 8; num14++)
            {
                Minecart._tileHeight[num][num14] = -2;
            }
            Minecart._texturePosition[num] = new Vector2(6f, 2f);
            num++;
            Minecart._leftSideConnection[num] = -1;
            Minecart._rightSideConnection[num] = 0;
            Minecart._tileHeight[num][5] = 6;
            Minecart._tileHeight[num][6] = 7;
            Minecart._tileHeight[num][7] = 8;
            for (int num15 = 0; num15 < 5; num15++)
            {
                Minecart._tileHeight[num][num15] = -2;
            }
            Minecart._texturePosition[num] = new Vector2(7f, 2f);
            num++;
            Minecart._leftSideConnection[num] = 1;
            Minecart._rightSideConnection[num] = 1;
            Minecart._trackType[num] = 2;
            Minecart._boostLeft[num] = false;
            Minecart._texturePosition[num] = new Vector2(2f, 3f);
            num++;
            Minecart._leftSideConnection[num] = 1;
            Minecart._rightSideConnection[num] = 1;
            Minecart._trackType[num] = 2;
            Minecart._boostLeft[num] = true;
            Minecart._texturePosition[num] = new Vector2(3f, 3f);
            num++;
            Minecart._leftSideConnection[num] = 0;
            Minecart._rightSideConnection[num] = 2;
            for (int num16 = 0; num16 < 8; num16++)
            {
                Minecart._tileHeight[num][num16] = 8 - num16;
            }
            Minecart._trackType[num] = 2;
            Minecart._boostLeft[num] = false;
            Minecart._texturePosition[num] = new Vector2(4f, 3f);
            num++;
            Minecart._leftSideConnection[num] = 2;
            Minecart._rightSideConnection[num] = 0;
            for (int num17 = 0; num17 < 8; num17++)
            {
                Minecart._tileHeight[num][num17] = num17 + 1;
            }
            Minecart._trackType[num] = 2;
            Minecart._boostLeft[num] = true;
            Minecart._texturePosition[num] = new Vector2(5f, 3f);
            num++;
            Minecart._leftSideConnection[num] = 0;
            Minecart._rightSideConnection[num] = 2;
            for (int num18 = 0; num18 < 8; num18++)
            {
                Minecart._tileHeight[num][num18] = 8 - num18;
            }
            Minecart._trackType[num] = 2;
            Minecart._boostLeft[num] = true;
            Minecart._texturePosition[num] = new Vector2(6f, 3f);
            num++;
            Minecart._leftSideConnection[num] = 2;
            Minecart._rightSideConnection[num] = 0;
            for (int num19 = 0; num19 < 8; num19++)
            {
                Minecart._tileHeight[num][num19] = num19 + 1;
            }
            Minecart._trackType[num] = 2;
            Minecart._boostLeft[num] = false;
            Minecart._texturePosition[num] = new Vector2(7f, 3f);
            num++;
            Minecart._texturePosition[36] = new Vector2(0f, 6f);
            Minecart._texturePosition[37] = new Vector2(1f, 6f);
            Minecart._texturePosition[39] = new Vector2(0f, 7f);
            Minecart._texturePosition[38] = new Vector2(1f, 7f);
            for (int num20 = 0; num20 < Minecart._texturePosition.Length; num20++)
            {
                Minecart._texturePosition[num20] = Minecart._texturePosition[num20] * 18f;
            }
            for (int num21 = 0; num21 < Minecart._tileHeight.Length; num21++)
            {
                int[] array2 = Minecart._tileHeight[num21];
                for (int num22 = 0; num22 < array2.Length; num22++)
                {
                    if (array2[num22] >= 0)
                    {
                        array2[num22] = (8 - array2[num22]) * 2;
                    }
                }
            }
            int[] array3 = new int[36];
            Minecart._trackSwitchOptions = new int[64][];
            for (int num23 = 0; num23 < 64; num23++)
            {
                int num24 = 0;
                for (int num25 = 1; num25 < 256; num25 <<= 1)
                {
                    if ((num23 & num25) == num25)
                    {
                        num24++;
                    }
                }
                int num26 = 0;
                int num27 = 0;
                while (num27 < 36)
                {
                    array3[num27] = -1;
                    int num28 = 0;
                    switch (Minecart._leftSideConnection[num27])
                    {
                    case 0:
                        num28 |= 1;
                        break;
                    case 1:
                        num28 |= 2;
                        break;
                    case 2:
                        num28 |= 4;
                        break;
                    }
                    switch (Minecart._rightSideConnection[num27])
                    {
                    case 0:
                        num28 |= 8;
                        break;
                    case 1:
                        num28 |= 16;
                        break;
                    case 2:
                        num28 |= 32;
                        break;
                    }
                    if (num24 < 2)
                    {
                        if (num23 == num28)
{
                            goto IL_0E41;
                        }
                    }
                    else if (num28 != 0 && (num23 & num28) == num28)
                    {
                        goto IL_0E41;
                    }
                    IL_0E4D:
                    num27++;
                    continue;
                    IL_0E41:
                    array3[num27] = num27;
                    num26++;
                    goto IL_0E4D;
                }
                if (num26 != 0)
                {
                    int[] array4 = new int[num26];
                    int num29 = 0;
                    for (int num30 = 0; num30 < 36; num30++)
                    {
                        if (array3[num30] != -1)
{
                            array4[num29] = array3[num30];
                            num29++;
                        }
                    }
                    Minecart._trackSwitchOptions[num23] = array4;
                }
            }
            Minecart._firstPressureFrame = -1;
            Minecart._firstLeftBoostFrame = -1;
            Minecart._firstRightBoostFrame = -1;
            for (int num31 = 0; num31 < Minecart._trackType.Length; num31++)
            {
                int num32 = Minecart._trackType[num31];
                if (num32 != 1)
                {
                    if (num32 == 2)
                    {
                        if (Minecart._boostLeft[num31])
{
                            if (Minecart._firstLeftBoostFrame == -1)
{
                                Minecart._firstLeftBoostFrame = (short)num31;
                            }
                        }
                        else if (Minecart._firstRightBoostFrame == -1)
{
                            Minecart._firstRightBoostFrame = (short)num31;
                        }
                    }
                }
                else if (Minecart._firstPressureFrame == -1)
                {
                    Minecart._firstPressureFrame = (short)num31;
                }
            }
        }
References Terraria.Minecart._boostLeft, Terraria.Minecart._firstLeftBoostFrame, Terraria.Minecart._firstPressureFrame, Terraria.Minecart._firstRightBoostFrame, Terraria.Minecart._leftSideConnection, Terraria.Minecart._rightSideConnection, Terraria.Minecart._texturePosition, Terraria.Minecart._tileHeight, Terraria.Minecart._trackSwitchOptions, Terraria.Minecart._trackType, System.array, Terraria.Main.dedServ, Terraria.Minecart.Customization.Default, Microsoft.Xna.Framework.Vector2.Length(), and Terraria.GameContent.TextureAssets.MinecartMount.
Referenced by Terraria.Main.Initialize_AlmostEverything(), and Terraria.Main.PostContentLoadInitialize().