Terraria Decompiled: Terraria.Minecart.TrackColors
TrackColors()
static void Terraria.Minecart.TrackColors (int i, int j, Tile trackTile, out int frontColor, out int backColor) inline static
Definition at line 1370 of file Minecart.cs.
        {
            if (trackTile.type == 314)
            {
                frontColor = (int)trackTile.color();
                backColor = frontColor;
                if (trackTile.frameY == -1)
                {
                    return;
                }
                int num = Minecart._leftSideConnection[(int)trackTile.frameX];
                int num2 = Minecart._rightSideConnection[(int)trackTile.frameX];
                int num3 = Minecart._leftSideConnection[(int)trackTile.frameY];
                int num4 = Minecart._rightSideConnection[(int)trackTile.frameY];
                int num5 = 0;
                int num6 = 0;
                int num7 = 0;
                int num8 = 0;
                for (int k = 0; k < 4; k++)
                {
                    int num9;
                    switch (k)
                    {
                    case 1:
                        num9 = num2;
                        break;
                    case 2:
                        num9 = num3;
                        break;
                    case 3:
                        num9 = num4;
                        break;
                    default:
                        num9 = num;
                        break;
                    }
                    int num10;
                    switch (num9)
                    {
                    case 0:
                        num10 = -1;
                        break;
                    case 1:
                        num10 = 0;
                        break;
                    case 2:
                        num10 = 1;
                        break;
                    default:
                        num10 = 0;
                        break;
                    }
                    Tile tile;
                    if (k % 2 == 0)
                    {
                        tile = Main.tile[i - 1, j + num10];
                    }
                    else
                    {
                        tile = Main.tile[i + 1, j + num10];
                    }
                    int num11;
                    if (tile == null || !tile.active() || tile.type != 314)
                    {
                        num11 = 0;
                    }
                    else
                    {
                        num11 = (int)tile.color();
                    }
                    switch (k)
                    {
                    case 1:
                        num6 = num11;
                        break;
                    case 2:
                        num7 = num11;
                        break;
                    case 3:
                        num8 = num11;
                        break;
                    default:
                        num5 = num11;
                        break;
                    }
                }
                if (num == num3)
                {
                    if (num6 != 0)
                    {
                        frontColor = num6;
                    }
                    else if (num5 != 0)
                    {
                        frontColor = num5;
                    }
                    if (num8 != 0)
                    {
                        backColor = num8;
                        return;
                    }
                    if (num7 != 0)
                    {
                        backColor = num7;
                        return;
                    }
                }
                else if (num2 == num4)
                {
                    if (num5 != 0)
                    {
                        frontColor = num5;
                    }
                    else if (num6 != 0)
                    {
                        frontColor = num6;
                    }
                    if (num7 != 0)
                    {
                        backColor = num7;
                        return;
                    }
                    if (num8 != 0)
                    {
                        backColor = num8;
                        return;
                    }
                }
                else
                {
                    if (num6 == 0)
                    {
                        if (num5 != 0)
{
                            frontColor = num5;
                        }
                    }
                    else if (num5 != 0)
                    {
                        frontColor = ((num2 <= num) ? num6 : num5);
                    }
                    if (num8 == 0)
                    {
                        if (num7 != 0)
{
                            backColor = num7;
                            return;
                        }
                    }
                    else if (num7 != 0)
                    {
                        backColor = ((num4 <= num3) ? num8 : num7);
                        return;
                    }
                }
            }
            else
            {
                frontColor = 0;
                backColor = 0;
            }
        }
References Terraria.Minecart._leftSideConnection, Terraria.Minecart._rightSideConnection, Terraria.Tile.active(), Terraria.Tile.color(), Terraria.Tile.frameX, Terraria.Tile.frameY, int, Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.GameContent.Drawing.TileDrawing.DrawTile_MinecartTrack().