Terraria Decompiled: Terraria.Minecart.TryFittingTileOrientation
TryFittingTileOrientation()
static void Terraria.Minecart.TryFittingTileOrientation (Point tileCoords, int? expectedYOffsetForLeft, int? expectedYOffsetForRight) inline static
Definition at line 1640 of file Minecart.cs.
        {
            int nearbyTilesSetLookupIndex = Minecart.GetNearbyTilesSetLookupIndex(tileCoords.X, tileCoords.Y);
            int[] array = Minecart._trackSwitchOptions[nearbyTilesSetLookupIndex];
            if (array == null)
            {
                return;
            }
            Tile tileSafely = Framing.GetTileSafely(tileCoords);
            int num = Minecart._trackType[(int)tileSafely.FrontTrack()];
            int? num2 = null;
            int i = 0;
            while (i < array.Length)
            {
                int num3 = array[i];
                int num4 = Minecart._leftSideConnection[num3];
                int num5 = Minecart._rightSideConnection[num3];
                int num6 = Minecart._trackType[num3];
                if (expectedYOffsetForLeft == null)
                {
                    goto IL_0086;
                }
                int num7 = Minecart.ConvertOffsetYToTrackConnectionValue(expectedYOffsetForLeft.Value);
                if (Minecart._leftSideConnection[num3] == num7)
                {
                    goto IL_0086;
                }
                IL_00BF:
                i++;
                continue;
                IL_0086:
                if (expectedYOffsetForRight != null)
                {
                    int num8 = Minecart.ConvertOffsetYToTrackConnectionValue(expectedYOffsetForRight.Value);
                    if (Minecart._rightSideConnection[num3] != num8)
                    {
                        goto IL_00BF;
                    }
                }
                if (Minecart._trackType[num3] == num)
                {
                    num2 = new int?(num3);
                    break;
                }
                goto IL_00BF;
            }
            if (num2 != null)
            {
                tileSafely.FrontTrack((short)num2.Value);
                NetMessage.SendTileSquare(-1, tileCoords.X, tileCoords.Y, TileChangeType.None);
            }
        }
References Terraria.Minecart._leftSideConnection, Terraria.Minecart._rightSideConnection, Terraria.Minecart._trackSwitchOptions, Terraria.Minecart._trackType, System.array, Terraria.Minecart.ConvertOffsetYToTrackConnectionValue(), Terraria.Minecart.GetNearbyTilesSetLookupIndex(), Terraria.Framing.GetTileSafely(), int, Terraria.NetMessage.SendTileSquare(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.MinecartDiggerHelper.CorrectTrackConnections().