Terraria Decompiled: System.Security.AccessControl.DirectoryObjectSecurity.ModifyAccess
ModifyAccess()
override bool System.Security.AccessControl.DirectoryObjectSecurity.ModifyAccess (AccessControlModification modification, AccessRule rule, out bool modified) inline protected
Definition at line 116 of file DirectoryObjectSecurity.cs.
        {
            if (rule == null)
            {
                throw new ArgumentNullException("rule");
            }
            ObjectAccessRule objectAccessRule = rule as ObjectAccessRule;
            if (objectAccessRule == null)
            {
                throw new ArgumentException("rule");
            }
            modified = true;
            base.WriteLock();
            try
            {
                switch (modification)
                {
                case AccessControlModification.Add:
                    break;
                case AccessControlModification.Set:
                    this.descriptor.DiscretionaryAcl.SetAccess(objectAccessRule.AccessControlType, ObjectSecurity.SidFromIR(objectAccessRule.IdentityReference), objectAccessRule.AccessMask, objectAccessRule.InheritanceFlags, objectAccessRule.PropagationFlags, objectAccessRule.ObjectFlags, objectAccessRule.ObjectType, objectAccessRule.InheritedObjectType);
                    goto IL_019D;
                case AccessControlModification.Reset:
                    this.PurgeAccessRules(objectAccessRule.IdentityReference);
                    break;
                case AccessControlModification.Remove:
                    modified = this.descriptor.DiscretionaryAcl.RemoveAccess(objectAccessRule.AccessControlType, ObjectSecurity.SidFromIR(objectAccessRule.IdentityReference), rule.AccessMask, objectAccessRule.InheritanceFlags, objectAccessRule.PropagationFlags, objectAccessRule.ObjectFlags, objectAccessRule.ObjectType, objectAccessRule.InheritedObjectType);
                    goto IL_019D;
                case AccessControlModification.RemoveAll:
                    this.PurgeAccessRules(objectAccessRule.IdentityReference);
                    goto IL_019D;
                case AccessControlModification.RemoveSpecific:
                    this.descriptor.DiscretionaryAcl.RemoveAccessSpecific(objectAccessRule.AccessControlType, ObjectSecurity.SidFromIR(objectAccessRule.IdentityReference), objectAccessRule.AccessMask, objectAccessRule.InheritanceFlags, objectAccessRule.PropagationFlags, objectAccessRule.ObjectFlags, objectAccessRule.ObjectType, objectAccessRule.InheritedObjectType);
                    goto IL_019D;
                default:
                    throw new ArgumentOutOfRangeException("modification");
                }
                this.descriptor.DiscretionaryAcl.AddAccess(objectAccessRule.AccessControlType, ObjectSecurity.SidFromIR(objectAccessRule.IdentityReference), objectAccessRule.AccessMask, objectAccessRule.InheritanceFlags, objectAccessRule.PropagationFlags, objectAccessRule.ObjectFlags, objectAccessRule.ObjectType, objectAccessRule.InheritedObjectType);
                IL_019D:
                if (modified)
                {
                    base.AccessRulesModified = true;
                }
            }
            finally
            {
                base.WriteUnlock();
            }
            return modified;
        }
References System.Security.AccessControl.AccessRule< T >.AccessControlType, System.Security.AccessControl.AuthorizationRule.AccessMask, System.Security.AccessControl.DiscretionaryAcl.AddAccess(), System.Security.AccessControl.ObjectSecurity< T >.descriptor, System.Security.AccessControl.CommonSecurityDescriptor.DiscretionaryAcl, System.Security.AccessControl.AuthorizationRule.IdentityReference, System.Security.AccessControl.AuthorizationRule.InheritanceFlags, System.Security.AccessControl.ObjectAccessRule.InheritedObjectType, System.Security.AccessControl.ObjectAccessRule.ObjectFlags, System.Security.AccessControl.ObjectAccessRule.ObjectType, System.Security.AccessControl.AuthorizationRule.PropagationFlags, System.Security.AccessControl.ObjectSecurity< T >.PurgeAccessRules(), System.Security.AccessControl.DiscretionaryAcl.RemoveAccess(), System.Security.AccessControl.DiscretionaryAcl.RemoveAccessSpecific(), System.Security.AccessControl.DiscretionaryAcl.SetAccess(), and System.Security.AccessControl.ObjectSecurity< T >.SidFromIR().
Referenced by System.Security.AccessControl.DirectoryObjectSecurity.AddAccessRule(), System.Security.AccessControl.DirectoryObjectSecurity.RemoveAccessRule(), System.Security.AccessControl.DirectoryObjectSecurity.RemoveAccessRuleAll(), System.Security.AccessControl.DirectoryObjectSecurity.RemoveAccessRuleSpecific(), System.Security.AccessControl.DirectoryObjectSecurity.ResetAccessRule(), and System.Security.AccessControl.DirectoryObjectSecurity.SetAccessRule().