Terraria Decompiled: Terraria.Utilities.NPCUtils.SearchForTarget
SearchForTarget() [2/3]
static NPCUtils.TargetSearchResults Terraria.Utilities.NPCUtils.SearchForTarget (NPC searcher, Vector2 position, NPCUtils::TargetSearchFlag flags = NPCUtils::TargetSearchFlag::All, NPCUtils::SearchFilter< Player > playerFilter = null, NPCUtils::SearchFilter< NPC > npcFilter = null) inline static
Definition at line 23 of file NPCUtils.cs.
        {
            float num = float.MaxValue;
            int num2 = -1;
            float num3 = float.MaxValue;
            float num4 = float.MaxValue;
            int num5 = -1;
            NPCUtils.TargetType targetType = NPCUtils.TargetType.Player;
            if ((flags & NPCUtils.TargetSearchFlag.NPCs) != NPCUtils.TargetSearchFlag.None)
            {
                for (int i = 0; i < Main.maxNPCs; i++)
                {
                    NPC npc = Main.npc[i];
                    if (npc.active && npc.whoAmI != searcher.whoAmI && (npcFilter == null || npcFilter(npc)))
                    {
                        float num6 = Vector2.DistanceSquared(position, npc.Center);
                        if (num6 < num)
{
                            num2 = i;
                            num = num6;
                        }
                    }
                }
            }
            if ((flags & NPCUtils.TargetSearchFlag.Players) != NPCUtils.TargetSearchFlag.None)
            {
                for (int j = 0; j < 255; j++)
                {
                    Player player = Main.player[j];
                    if (player.active && !player.dead && !player.ghost && (playerFilter == null || playerFilter(player)))
                    {
                        float num7 = Vector2.Distance(position, player.Center);
                        float num8 = num7 - (float)player.aggro;
                        bool flag = searcher != null && player.npcTypeNoAggro[searcher.type];
                        if (searcher != null && flag && searcher.direction == 0)
{
                            num8 += 1000f;
                        }
                        if (num8 < num3)
{
                            num5 = j;
                            num3 = num8;
                            num4 = num7;
                            targetType = NPCUtils.TargetType.Player;
                        }
                        if (player.tankPet >= 0 && !flag)
{
                            Vector2 center = Main.projectile[player.tankPet].Center;
                            num7 = Vector2.Distance(position, center);
                            num8 = num7 - 200f;
                            if (num8 < num3 && num8 < 200f && Collision.CanHit(position, 0, 0, center, 0, 0))
{
                                num5 = j;
                                num3 = num8;
                                num4 = num7;
                                targetType = NPCUtils.TargetType.TankPet;
                            }
                        }
                    }
                }
            }
            return new NPCUtils.TargetSearchResults(searcher, num2, (float)Math.Sqrt((double)num), num5, num4, num3, targetType);
        }
References Terraria.NPC.active, Terraria.Player.active, Terraria.Player.aggro, Terraria.Collision.CanHit(), Terraria.Entity.Center, Terraria.Player.dead, Terraria.Entity.direction, Microsoft.Xna.Framework.Vector2.Distance(), Microsoft.Xna.Framework.Vector2.DistanceSquared(), Terraria.Player.ghost, Terraria.Main.maxNPCs, Terraria.Main.npc, Terraria.Player.npcTypeNoAggro, Terraria.Main.player, Terraria.Main.projectile, System.Math.Sqrt(), Terraria.Player.tankPet, Terraria.NPC.type, and Terraria.Entity.whoAmI.