Terraria Decompiled: System.Security.AccessControl.DirectoryObjectSecurity.ModifyAudit
ModifyAudit()
override bool System.Security.AccessControl.DirectoryObjectSecurity.ModifyAudit (AccessControlModification modification, AuditRule rule, out bool modified) inline protected
Definition at line 203 of file DirectoryObjectSecurity.cs.
        {
            if (rule == null)
            {
                throw new ArgumentNullException("rule");
            }
            ObjectAuditRule objectAuditRule = rule as ObjectAuditRule;
            if (objectAuditRule == null)
            {
                throw new ArgumentException("rule");
            }
            modified = true;
            base.WriteLock();
            try
            {
                switch (modification)
                {
                case AccessControlModification.Add:
                    if (this.descriptor.SystemAcl == null)
                    {
                        this.descriptor.SystemAcl = new SystemAcl(base.IsContainer, base.IsDS, 1);
                    }
                    this.descriptor.SystemAcl.AddAudit(objectAuditRule.AuditFlags, ObjectSecurity.SidFromIR(objectAuditRule.IdentityReference), objectAuditRule.AccessMask, objectAuditRule.InheritanceFlags, objectAuditRule.PropagationFlags, objectAuditRule.ObjectFlags, objectAuditRule.ObjectType, objectAuditRule.InheritedObjectType);
                    break;
                case AccessControlModification.Set:
                    if (this.descriptor.SystemAcl == null)
                    {
                        this.descriptor.SystemAcl = new SystemAcl(base.IsContainer, base.IsDS, 1);
                    }
                    this.descriptor.SystemAcl.SetAudit(objectAuditRule.AuditFlags, ObjectSecurity.SidFromIR(objectAuditRule.IdentityReference), objectAuditRule.AccessMask, objectAuditRule.InheritanceFlags, objectAuditRule.PropagationFlags, objectAuditRule.ObjectFlags, objectAuditRule.ObjectType, objectAuditRule.InheritedObjectType);
                    break;
                case AccessControlModification.Reset:
                    break;
                case AccessControlModification.Remove:
                    if (this.descriptor.SystemAcl == null)
                    {
                        modified = false;
                    }
                    else
                    {
                        modified = this.descriptor.SystemAcl.RemoveAudit(objectAuditRule.AuditFlags, ObjectSecurity.SidFromIR(objectAuditRule.IdentityReference), objectAuditRule.AccessMask, objectAuditRule.InheritanceFlags, objectAuditRule.PropagationFlags, objectAuditRule.ObjectFlags, objectAuditRule.ObjectType, objectAuditRule.InheritedObjectType);
                    }
                    break;
                case AccessControlModification.RemoveAll:
                    this.PurgeAuditRules(objectAuditRule.IdentityReference);
                    break;
                case AccessControlModification.RemoveSpecific:
                    if (this.descriptor.SystemAcl != null)
                    {
                        this.descriptor.SystemAcl.RemoveAuditSpecific(objectAuditRule.AuditFlags, ObjectSecurity.SidFromIR(objectAuditRule.IdentityReference), objectAuditRule.AccessMask, objectAuditRule.InheritanceFlags, objectAuditRule.PropagationFlags, objectAuditRule.ObjectFlags, objectAuditRule.ObjectType, objectAuditRule.InheritedObjectType);
                    }
                    break;
                default:
                    throw new ArgumentOutOfRangeException("modification");
                }
                if (modified)
                {
                    base.AuditRulesModified = true;
                }
            }
            finally
            {
                base.WriteUnlock();
            }
            return modified;
        }
References System.Security.AccessControl.AuthorizationRule.AccessMask, System.Security.AccessControl.SystemAcl.AddAudit(), System.Security.AccessControl.AuditRule< T >.AuditFlags, System.Security.AccessControl.ObjectSecurity< T >.descriptor, System.Security.AccessControl.AuthorizationRule.IdentityReference, System.Security.AccessControl.AuthorizationRule.InheritanceFlags, System.Security.AccessControl.ObjectAuditRule.InheritedObjectType, System.Security.AccessControl.ObjectAuditRule.ObjectFlags, System.Security.AccessControl.ObjectAuditRule.ObjectType, System.Security.AccessControl.AuthorizationRule.PropagationFlags, System.Security.AccessControl.ObjectSecurity< T >.PurgeAuditRules(), System.Security.AccessControl.SystemAcl.RemoveAudit(), System.Security.AccessControl.SystemAcl.RemoveAuditSpecific(), System.Security.AccessControl.SystemAcl.SetAudit(), System.Security.AccessControl.ObjectSecurity< T >.SidFromIR(), System.Security.AccessControl.CommonSecurityDescriptor.SystemAcl, and System.Security.AccessControl.SystemAcl.
Referenced by System.Security.AccessControl.DirectoryObjectSecurity.AddAuditRule(), System.Security.AccessControl.DirectoryObjectSecurity.RemoveAuditRule(), System.Security.AccessControl.DirectoryObjectSecurity.RemoveAuditRuleAll(), System.Security.AccessControl.DirectoryObjectSecurity.RemoveAuditRuleSpecific(), and System.Security.AccessControl.DirectoryObjectSecurity.SetAuditRule().