Terraria Decompiled: System.Threading.Tasks.TaskToApm.Begin
Begin()
static IAsyncResult System.Threading.Tasks.TaskToApm.Begin (Task task, AsyncCallback callback, object state) inline static
Definition at line 10 of file TaskToApm.cs.
        {
            IAsyncResult asyncResult;
            if (task.IsCompleted)
            {
                asyncResult = new TaskToApm.TaskWrapperAsyncResult(task, state, true);
                if (callback != null)
                {
                    callback(asyncResult);
                }
            }
            else
            {
                IAsyncResult asyncResult3;
                if (task.AsyncState != state)
                {
                    IAsyncResult asyncResult2 = new TaskToApm.TaskWrapperAsyncResult(task, state, false);
                    asyncResult3 = asyncResult2;
                }
                else
                {
                    asyncResult3 = task;
                }
                asyncResult = asyncResult3;
                if (callback != null)
                {
                    TaskToApm.InvokeCallbackWhenTaskCompletes(task, callback, asyncResult);
                }
            }
            return asyncResult;
        }
References System.Threading.Tasks.TaskToApm.InvokeCallbackWhenTaskCompletes(), System.state, and System.task.
Referenced by System.IO.BufferedStream.BeginRead(), System.Security.Cryptography.CryptoStream.BeginRead(), System.IO.BufferedStream.BeginWrite(), and System.Security.Cryptography.CryptoStream.BeginWrite().