Terraria Decompiled: Steamworks.SteamAPI.InitEx
InitEx()
static ESteamAPIInitResult Steamworks.SteamAPI.InitEx (out string OutSteamErrMsg) inline static
Definition at line 11 of file SteamAPI.cs.
        {
            InteropHelp.TestIfPlatformSupported();
            StringBuilder stringBuilder = new StringBuilder();
            stringBuilder.Append("SteamUtils010").Append("\0");
            stringBuilder.Append("SteamNetworkingUtils004").Append("\0");
            stringBuilder.Append("STEAMAPPS_INTERFACE_VERSION008").Append("\0");
            stringBuilder.Append("SteamFriends017").Append("\0");
            stringBuilder.Append("SteamMatchGameSearch001").Append("\0");
            stringBuilder.Append("STEAMHTMLSURFACE_INTERFACE_VERSION_005").Append("\0");
            stringBuilder.Append("STEAMHTTP_INTERFACE_VERSION003").Append("\0");
            stringBuilder.Append("SteamInput006").Append("\0");
            stringBuilder.Append("STEAMINVENTORY_INTERFACE_V003").Append("\0");
            stringBuilder.Append("SteamMatchMakingServers002").Append("\0");
            stringBuilder.Append("SteamMatchMaking009").Append("\0");
            stringBuilder.Append("STEAMMUSICREMOTE_INTERFACE_VERSION001").Append("\0");
            stringBuilder.Append("STEAMMUSIC_INTERFACE_VERSION001").Append("\0");
            stringBuilder.Append("SteamNetworkingMessages002").Append("\0");
            stringBuilder.Append("SteamNetworkingSockets012").Append("\0");
            stringBuilder.Append("SteamNetworking006").Append("\0");
            stringBuilder.Append("STEAMPARENTALSETTINGS_INTERFACE_VERSION001").Append("\0");
            stringBuilder.Append("SteamParties002").Append("\0");
            stringBuilder.Append("STEAMREMOTEPLAY_INTERFACE_VERSION002").Append("\0");
            stringBuilder.Append("STEAMREMOTESTORAGE_INTERFACE_VERSION016").Append("\0");
            stringBuilder.Append("STEAMSCREENSHOTS_INTERFACE_VERSION003").Append("\0");
            stringBuilder.Append("STEAMUGC_INTERFACE_VERSION020").Append("\0");
            stringBuilder.Append("STEAMUSERSTATS_INTERFACE_VERSION012").Append("\0");
            stringBuilder.Append("SteamUser023").Append("\0");
            stringBuilder.Append("STEAMVIDEO_INTERFACE_V007").Append("\0");
            ESteamAPIInitResult esteamAPIInitResult2;
            using (InteropHelp.UTF8StringHandle utf8StringHandle = new InteropHelp.UTF8StringHandle(stringBuilder.ToString()))
            {
                IntPtr intPtr = Marshal.AllocHGlobal(1024);
                ESteamAPIInitResult esteamAPIInitResult = NativeMethods.SteamInternal_SteamAPI_Init(utf8StringHandle, intPtr);
                OutSteamErrMsg = InteropHelp.PtrToStringUTF8(intPtr);
                Marshal.FreeHGlobal(intPtr);
                if (esteamAPIInitResult == ESteamAPIInitResult.k_ESteamAPIInitResult_OK)
                {
                    if (CSteamAPIContext.Init())
                    {
                        CallbackDispatcher.Initialize();
                    }
                    else
                    {
                        esteamAPIInitResult = ESteamAPIInitResult.k_ESteamAPIInitResult_FailedGeneric;
                        OutSteamErrMsg = "[Steamworks.NET] Failed to initialize CSteamAPIContext";
                    }
                }
                esteamAPIInitResult2 = esteamAPIInitResult;
            }
            return esteamAPIInitResult2;
        }
References System.Runtime.InteropServices.Marshal.AllocHGlobal(), System.Text.StringBuilder.Append(), System.Runtime.InteropServices.Marshal.FreeHGlobal(), Steamworks.CSteamAPIContext.Init(), Steamworks.CallbackDispatcher.Initialize(), Steamworks.InteropHelp.PtrToStringUTF8(), Steamworks.NativeMethods.SteamInternal_SteamAPI_Init(), Steamworks.InteropHelp.TestIfPlatformSupported(), and System.Text.StringBuilder.ToString().
Referenced by Steamworks.SteamAPI.Init().