Terraria Decompiled: Mono.Math.Prime.PrimalityTests.GetSPPRounds
GetSPPRounds()
static int Mono.Math.Prime.PrimalityTests.GetSPPRounds (BigInteger bi, ConfidenceFactor confidence) inline static private
Definition at line 14 of file PrimalityTests.cs.
        {
            int num = bi.BitCount();
            int num2;
            if (num <= 100)
            {
                num2 = 27;
            }
            else if (num <= 150)
            {
                num2 = 18;
            }
            else if (num <= 200)
            {
                num2 = 15;
            }
            else if (num <= 250)
            {
                num2 = 12;
            }
            else if (num <= 300)
            {
                num2 = 9;
            }
            else if (num <= 350)
            {
                num2 = 8;
            }
            else if (num <= 400)
            {
                num2 = 7;
            }
            else if (num <= 500)
            {
                num2 = 6;
            }
            else if (num <= 600)
            {
                num2 = 5;
            }
            else if (num <= 800)
            {
                num2 = 4;
            }
            else if (num <= 1250)
            {
                num2 = 3;
            }
            else
            {
                num2 = 2;
            }
            switch (confidence)
            {
            case ConfidenceFactor.ExtraLow:
                num2 >>= 2;
                if (num2 == 0)
                {
                    return 1;
                }
                return num2;
            case ConfidenceFactor.Low:
                num2 >>= 1;
                if (num2 == 0)
                {
                    return 1;
                }
                return num2;
            case ConfidenceFactor.Medium:
                return num2;
            case ConfidenceFactor.High:
                return num2 << 1;
            case ConfidenceFactor.ExtraHigh:
                return num2 << 2;
            case ConfidenceFactor.Provable:
                throw new Exception("The Rabin-Miller test can not be executed in a way such that its results are provable");
            default:
                throw new ArgumentOutOfRangeException("confidence");
            }
        }
References Mono.Math.BigInteger.BitCount().
Referenced by Mono.Math.Prime.PrimalityTests.RabinMillerTest(), and Mono.Math.Prime.PrimalityTests.SmallPrimeSppTest().