Terraria Decompiled: Mono.Math.Prime.PrimalityTests.SmallPrimeSppTest
SmallPrimeSppTest()
static bool Mono.Math.Prime.PrimalityTests.SmallPrimeSppTest (BigInteger bi, ConfidenceFactor confidence) inline static
Definition at line 153 of file PrimalityTests.cs.
        {
            int spprounds = PrimalityTests.GetSPPRounds(bi, confidence);
            BigInteger bigInteger = bi - 1;
            int num = bigInteger.LowestSetBit();
            BigInteger bigInteger2 = bigInteger >> num;
            BigInteger.ModulusRing modulusRing = new BigInteger.ModulusRing(bi);
            for (int i = 0; i < spprounds; i++)
            {
                BigInteger bigInteger3 = modulusRing.Pow(BigInteger.smallPrimes[i], bigInteger2);
                if (!(bigInteger3 == 1U))
                {
                    bool flag = false;
                    for (int j = 0; j < num; j++)
                    {
                        if (bigInteger3 == bigInteger)
{
                            flag = true;
                            break;
                        }
                        bigInteger3 = bigInteger3 * bigInteger3 % bi;
                    }
                    if (!flag)
                    {
                        return false;
                    }
                }
            }
            return true;
        }
References Mono.Math.Prime.PrimalityTests.GetSPPRounds(), Mono.Math.BigInteger.LowestSetBit(), Mono.Math.BigInteger.ModulusRing.Pow(), Mono.Math.BigInteger.smallPrimes, and System.U.
Referenced by Mono.Math.Prime.PrimalityTests.Test().