Terraria Decompiled: rail.RAIL_API_PINVOKE.new_RailString__SWIG_0
new_RailString__SWIG_0()
static IntPtr rail.RAIL_API_PINVOKE.new_RailString__SWIG_0 ()
Referenced by rail.RailConverter.Csharp2Cpp(), rail.IRailPlayerAchievementImpl.GetAchievementInfo(), rail.IRailUtilsImpl.GetCountryCodeOfCurrentLoggedInIP(), rail.IRailBrowserImpl.GetCurrentUrl(), rail.IRailBrowserRenderImpl.GetCurrentUrl(), rail.IRailSpaceWorkImpl.GetDescription(), rail.IRailUtilsImpl.GetErrorString(), rail.IRailStorageHelperImpl.GetFileNameAndSize(), rail.IRailGameImpl.GetGameInstallPath(), rail.IRailGameServerImpl.GetGameServerDescription(), rail.IRailGameServerImpl.GetGameServerFullName(), rail.IRailGameServerImpl.GetGameServerName(), rail.IRailGameServerImpl.GetGameServerTags(), rail.IRailGameServerImpl.GetGameServerVersion(), rail.IRailGlobalAchievementImpl.GetGlobalAchievedPercentDescending(), rail.IRailGameServerImpl.GetHost(), rail.IRailUtilsImpl.GetLaunchAppParameters(), rail.IRailSpaceWorkImpl.GetLocalVersion(), rail.IRailGameServerImpl.GetMapName(), rail.IRailRoomImpl.GetMemberMetadata(), rail.IRailRoomImpl.GetMemberNameByIndex(), rail.IRailGameServerImpl.GetMetadata(), rail.IRailSpaceWorkImpl.GetMetadata(), rail.IRailSpaceWorkImpl.GetName(), rail.IRailSmallObjectServiceHelperImpl.GetObjectContent(), rail.IRailUtilsImpl.GetPlatformLanguageCode(), rail.IRailPlayerImpl.GetPlayerDataPath(), rail.IRailPlayerImpl.GetPlayerMetadata(), rail.IRailPlayerImpl.GetPlayerName(), rail.IRailGameImpl.GetPlayerSelectedLanguageCode(), rail.IRailSpaceWorkImpl.GetPreviewImage(), rail.IRailSpaceWorkImpl.GetPreviewUrl(), rail.IRailRoomImpl.GetRoomMetadata(), rail.IRailRoomImpl.GetRoomName(), rail.IRailGameServerImpl.GetServerInfo(), rail.IRailGameServerImpl.GetSpectatorHost(), rail.IRailTextInputHelperImpl.GetTextInputContent(), rail.IRailSpaceWorkImpl.GetUrl(), rail.IRailSpaceWorkImpl.GetVersion(), rail.IRailSpaceWorkImpl.GetWorkLocalFolder(), rail.IRailZoneServerImpl.GetZoneDescription(), rail.IRailZoneServerImpl.GetZoneName(), rail.IRailDlcHelperImpl.IsDlcInstalled(), and rail.rail_api.RailGetSdkVersion().