Terraria Decompiled: rail.RAIL_API_PINVOKE.new_RailID__SWIG_0
new_RailID__SWIG_0()
static IntPtr rail.RAIL_API_PINVOKE.new_RailID__SWIG_0 ()
Referenced by rail.IRailNetworkImpl.AcceptSessionRequest(), rail.IRailGameServerHelperImpl.AsyncAddFavoriteGameServer(), rail.IRailGameServerHelperImpl.AsyncAddFavoriteGameServer(), rail.IRailFriendsImpl.AsyncGetFriendMetadata(), rail.IRailGameServerHelperImpl.AsyncGetGameServerPlayerList(), rail.IRailFriendsImpl.AsyncGetInviteCommandLine(), rail.IRailUsersHelperImpl.AsyncGetInviteDetail(), rail.IRailRoomImpl.AsyncGetMemberMetadata(), rail.IRailUsersHelperImpl.AsyncGetUserLimits(), rail.IRailRoomImpl.AsyncKickOffMember(), rail.IRailFriendsImpl.AsyncQueryFriendPlayedGamesInfo(), rail.IRailGameServerHelperImpl.AsyncRemoveFavoriteGameServer(), rail.IRailGameServerHelperImpl.AsyncRemoveFavoriteGameServer(), rail.IRailLeaderboardEntriesImpl.AsyncRequestLeaderboardEntries(), rail.IRailRoomImpl.AsyncSetMemberMetadata(), rail.IRailUsersHelperImpl.AsyncShowChatWindowWithFriend(), rail.IRailUsersHelperImpl.AsyncShowUserHomepageWindow(), rail.IRailGameServerImpl.AsyncStartSessionWithPlayer(), rail.IRailPlayerImpl.AsyncStartSessionWithPlayer(), rail.IRailNetworkImpl.BlockMessageType(), rail.IRailNetworkImpl.CloseSession(), rail.IRailAchievementHelperImpl.CreatePlayerAchievement(), rail.IRailStatisticHelperImpl.CreatePlayerStats(), rail.RailConverter.Csharp2Cpp(), rail.IRailRoomImpl.GetMemberMetadata(), rail.IRailNetworkImpl.GetSessionState(), rail.IRailNetworkImpl.IsDataReady(), rail.IRailNetworkImpl.IsDataReady(), rail.IRailGameServerImpl.IsUserInGameServer(), rail.IRailRoomImpl.IsUserInRoom(), rail.IRailNetworkImpl.ReadData(), rail.IRailNetworkImpl.ReadData(), rail.IRailNetworkImpl.SendData(), rail.IRailNetworkImpl.SendData(), rail.IRailRoomImpl.SendDataToMember(), rail.IRailRoomImpl.SendDataToMember(), rail.IRailNetworkImpl.SendReliableData(), rail.IRailNetworkImpl.SendReliableData(), rail.IRailRoomImpl.SetMemberMetadata(), rail.IRailRoomImpl.SetNewOwner(), rail.IRailGameServerImpl.TerminateSessionOfPlayer(), rail.IRailPlayerImpl.TerminateSessionOfPlayer(), and rail.IRailNetworkImpl.UnblockMessageType().