Terraria Decompiled: rail.RAIL_API_PINVOKE.delete_RailArrayRailString
delete_RailArrayRailString()
static void rail.RAIL_API_PINVOKE.delete_RailArrayRailString (IntPtr jarg1)
Referenced by rail.IRailRoomImpl.AsyncClearRoomMetadata(), rail.IRailFriendsImpl.AsyncGetFriendMetadata(), rail.IRailRoomImpl.AsyncGetMemberMetadata(), rail.IRailGameServerImpl.AsyncGetMetadata(), rail.IRailRoomImpl.AsyncGetRoomMetadata(), rail.IRailSpaceWorkImpl.GetAdditionalPreviewUrls(), rail.IRailPlayerAchievementImpl.GetAllAchievementsName(), rail.IRailZoneServerImpl.GetGameServerAddresses(), rail.IRailGameImpl.GetGameSupportedLanguageCodes(), rail.IRailSpaceWorkImpl.GetLanguages(), rail.IRailGameServerImpl.GetMods(), rail.IRailHttpResponseImpl.GetResponseHeaderKeys(), rail.IRailSpaceWorkImpl.GetTags(), rail.IRailZoneServerImpl.GetZoneDescriptionLanguages(), rail.IRailZoneServerImpl.GetZoneNameLanguages(), rail.IRailStorageHelperImpl.ListFiles(), rail.IRailNetworkImpl.ResolveHostname(), rail.IRailSpaceWorkImpl.SetAdditionalPreviews(), rail.IRailSpaceWorkImpl.SetLanguages(), rail.IRailGameServerImpl.SetMods(), rail.IRailHttpSessionImpl.SetRequestHeaders(), and rail.IRailSpaceWorkImpl.SetTags().