Terraria Decompiled: System.Console.WriteLine
WriteLine() [1/19]
static void System.Console.WriteLine () inline static
Definition at line 325 of file Console.cs.
        {
            Console.stdout.WriteLine();
        }
References System.Console.stdout, and System.IO.TextWriter.WriteLine().
Referenced by ReLogic.Peripherals.RGB.Corsair.CorsairDeviceGroup.AddDeviceIfSupported(), Terraria.Graphics.Capture.CaptureCamera.Capture(), Terraria.NetMessage.CheckBytes(), Terraria.IO.ResourcePackList.CreatePackEntryListFromJson(), Terraria.IO.ResourcePackList.CreatePacksFromDirectories(), Terraria.IO.ResourcePackList.CreatePacksFromSavedJson(), Terraria.IO.ResourcePackList.CreatePacksFromWorkshopFolders(), Terraria.IO.ResourcePackList.CreatePacksFromZips(), Terraria.Main.DedServ(), Terraria.Main.DedServ_SeedFlagsMenu(), Ionic.Zip.ZipFile.DeleteFileWithRetry(), Terraria.Program.DisplayException(), Terraria.Testing.ChatCommands.DebugMessage.DisplayMessage(), Terraria.Main.DoUpdate(), Terraria.NetMessage.EnsureLocalPlayerIsPresent(), Steamworks.CallbackDispatcher.ExceptionHandler(), Terraria.Graphics.Capture.CaptureCamera.FinishCapture(), Terraria.WorldGen.GenerateWorld(), Microsoft.Xna.Framework.FNALoggerEXT.Initialize(), ReLogic.Peripherals.RGB.Corsair.CorsairDeviceGroup.Initialize(), ReLogic.Peripherals.RGB.Logitech.LogitechDeviceGroup.Initialize(), ReLogic.Peripherals.RGB.Razer.RazerDeviceGroup.Initialize(), Terraria.Social.Steam.NetServerSocialModule.Initialize(), Terraria.Social.WeGame.NetServerSocialModule.Initialize(), Terraria.Utilities.CrashWatcher.Inititialize(), Terraria.GameContent.Shaders.WaterShaderData.InitRenderTargets(), XPT.Core.Audio.MP3Sharp.Decoding.Bitstream.IsSyncMark(), Terraria.Netplay.KickClient(), Terraria.Audio.LegacyAudioSystem.LegacyAudioSystem(), Terraria.Net.Sockets.TcpSocket.ListenLoop(), Terraria.IO.FavoritesFile.Load(), Terraria.IO.WorldFile.LoadFileFormatHeader(), Terraria.Localization.LanguageManager.LoadFilesForCulture(), Terraria.Main.LoadSettings(), Terraria.Program.LogFNANativeLibVersions(), Terraria.Main.Main(), Terraria.DataStructures.TitleLinkButton.OpenLink(), Terraria.WorldGen.playWorldCallBack(), Terraria.DataStructures.BufferPool.PrintBufferSizes(), Terraria.Net.LegacyNetBufferPool.PrintBufferSizes(), Terraria.Main.PrintTimedMessage(), Terraria.Chat.Commands.SayChatCommand.ProcessIncomingMessage(), Terraria.GameContent.Shaders.WaterShaderData.ReleaseRenderTargets(), Terraria.IO.Preferences.Save(), Terraria.Graphics.Capture.CaptureCamera.SaveImage(), Terraria.NetMessage.SendData(), Terraria.WorldGen.serverLoadWorldCallBack(), ReLogic.OS.Windows.Clipboard.SetClipboard(), Terraria.Main.SetDisplayMode(), Terraria.Program.SetupLogging(), Terraria.GameContent.Liquid.LiquidRenderer.SetWaveMaskData(), Terraria.UI.FancyErrorPrinter.ShowDirectoryCreationFailError(), Terraria.UI.FancyErrorPrinter.ShowFailedToLoadAssetError(), Terraria.UI.FancyErrorPrinter.ShowFileSavingFailError(), Terraria.Main.startDedInputCallBack(), Terraria.Liquid.StartPanic(), ReLogic.Utilities.MultiTimer.StopAndPrint(), Terraria.NetMessage.SyncOnePlayer(), Terraria.Audio.SoundEngine.TestAudioSupport(), ReLogic.IO.ConsoleOutputMirror.ToFile(), Ionic.BZip2.BZip2OutputStream.TraceOutput(), Ionic.Zip.ZipEntry.TraceWriteLine(), ReLogic.OS.Windows.Clipboard.TryToGetClipboardText(), ReLogic.Peripherals.RGB.Corsair.CorsairDeviceGroup.Uninitialize(), ReLogic.Peripherals.RGB.Logitech.LogitechDeviceGroup.Uninitialize(), ReLogic.Peripherals.RGB.Razer.RazerDeviceGroup.Uninitialize(), Terraria.Liquid.UpdateLiquid(), and Terraria.Main.WriteFancyWorldLoadErrorToConsole().