Terraria Decompiled: System.Runtime.Remoting.Contexts.SynchronizedClientContextSink.SyncProcessMessage
SyncProcessMessage()
IMessage System.Runtime.Remoting.Contexts.SynchronizedClientContextSink.SyncProcessMessage (IMessage msg) inline
Implements System.Runtime.Remoting.Messaging.IMessageSink.
Definition at line 38 of file SynchronizedClientContextSink.cs.
        {
            if (this._att.IsReEntrant)
            {
                this._att.ReleaseLock();
            }
            IMessage message;
            try
            {
                message = this._next.SyncProcessMessage(msg);
            }
            finally
            {
                if (this._att.IsReEntrant)
                {
                    this._att.AcquireLock();
                }
            }
            return message;
        }
References System.Runtime.Remoting.Contexts.SynchronizedClientContextSink._att, System.Runtime.Remoting.Contexts.SynchronizedClientContextSink._next, System.Runtime.Remoting.Contexts.SynchronizationAttribute.AcquireLock(), System.Runtime.Remoting.Contexts.SynchronizationAttribute.IsReEntrant, System.Runtime.Remoting.Contexts.SynchronizationAttribute.ReleaseLock(), and System.Runtime.Remoting.Messaging.IMessageSink.SyncProcessMessage().