Terraria Decompiled: System.Console.Console
Console()
static System.Console.Console () inline static private
Definition at line 15 of file Console.cs.
        {
            if (Environment.IsRunningOnWindows)
            {
                try
                {
                    Console.inputEncoding = Encoding.GetEncoding(Console.WindowsConsole.GetInputCodePage());
                    Console.outputEncoding = Encoding.GetEncoding(Console.WindowsConsole.GetOutputCodePage());
                    goto IL_007D;
                }
                catch
                {
                    Console.inputEncoding = (Console.outputEncoding = Encoding.Default);
                    goto IL_007D;
                }
            }
            int num = 0;
            EncodingHelper.InternalCodePage(ref num);
            if (num != -1 && ((num & 268435455) == 3 || (num & 268435456) != 0))
            {
                Console.inputEncoding = (Console.outputEncoding = EncodingHelper.UTF8Unmarked);
            }
            else
            {
                Console.inputEncoding = (Console.outputEncoding = Encoding.Default);
            }
            IL_007D:
            Console.SetupStreams(Console.inputEncoding, Console.outputEncoding);
        }
References System.Text.Encoding.Default, System.Text.Encoding.GetEncoding(), System.Console.WindowsConsole.GetInputCodePage(), System.Console.WindowsConsole.GetOutputCodePage(), System.Console.inputEncoding, System.Text.EncodingHelper.InternalCodePage(), System.Console.outputEncoding, System.Console.SetupStreams(), and System.Text.EncodingHelper.UTF8Unmarked.