Terraria Decompiled: System.Console.SetupStreams
SetupStreams()
static void System.Console.SetupStreams (Encoding inputEncoding, Encoding outputEncoding) inline static private
Definition at line 46 of file Console.cs.
        {
            if (!Environment.IsRunningOnWindows && ConsoleDriver.IsConsole)
            {
                Console.stdin = new CStreamReader(Console.OpenStandardInput(0), inputEncoding);
                Console.stdout = TextWriter.Synchronized(new CStreamWriter(Console.OpenStandardOutput(0), outputEncoding, true)
                {
                    AutoFlush = true
                });
                Console.stderr = TextWriter.Synchronized(new CStreamWriter(Console.OpenStandardError(0), outputEncoding, true)
                {
                    AutoFlush = true
                });
            }
            else
            {
                Console.stdin = TextReader.Synchronized(new UnexceptionalStreamReader(Console.OpenStandardInput(0), inputEncoding));
                Console.stdout = TextWriter.Synchronized(new UnexceptionalStreamWriter(Console.OpenStandardOutput(0), outputEncoding)
                {
                    AutoFlush = true
                });
                Console.stderr = TextWriter.Synchronized(new UnexceptionalStreamWriter(Console.OpenStandardError(0), outputEncoding)
                {
                    AutoFlush = true
                });
            }
            GC.SuppressFinalize(Console.stdout);
            GC.SuppressFinalize(Console.stderr);
            GC.SuppressFinalize(Console.stdin);
        }
References System.Console.inputEncoding, System.ConsoleDriver.IsConsole, System.Console.OpenStandardError(), System.Console.OpenStandardInput(), System.Console.OpenStandardOutput(), System.Console.outputEncoding, System.Console.stderr, System.Console.stdin, System.Console.stdout, System.GC.SuppressFinalize(), System.IO.TextReader.Synchronized(), and System.IO.TextWriter.Synchronized().
Referenced by System.Console.Console().