Terraria Decompiled: System.Console.Open
Open()
static Stream System.Console.Open (IntPtr handle, FileAccess access, int bufferSize) inline static private
Definition at line 108 of file Console.cs.
        {
            Stream stream;
            try
            {
                FileStream fileStream = new FileStream(handle, access, false, bufferSize, false, true);
                GC.SuppressFinalize(fileStream);
                stream = fileStream;
            }
            catch (IOException)
            {
                stream = Stream.Null;
            }
            return stream;
        }
References System.IO.Stream.Null, and System.GC.SuppressFinalize().
Referenced by System.Console.OpenStandardError(), System.Console.OpenStandardInput(), and System.Console.OpenStandardOutput().