Terraria Decompiled: System.Runtime.InteropServices.Marshal.GetExceptionForHR
GetExceptionForHR() [2/2]
static Exception System.Runtime.InteropServices.Marshal.GetExceptionForHR (int errorCode, IntPtr errorInfo) inline static
Definition at line 2064 of file Marshal.cs.
        {
            IErrorInfo errorInfo2 = null;
            if (errorInfo != (IntPtr)(-1))
            {
                if (errorInfo == IntPtr.Zero)
                {
                    if (Marshal.GetErrorInfo(0, out errorInfo2) != 0)
                    {
                        errorInfo2 = null;
                    }
                }
                else
                {
                    errorInfo2 = Marshal.GetObjectForIUnknown(errorInfo) as IErrorInfo;
                }
            }
            if (errorInfo2 is ManagedErrorInfo && ((ManagedErrorInfo)errorInfo2).Exception._HResult == errorCode)
            {
                return ((ManagedErrorInfo)errorInfo2).Exception;
            }
            Exception ex = Marshal.ConvertHrToException(errorCode);
            if (errorInfo2 != null && ex != null)
            {
                uint num;
                errorInfo2.GetHelpContext(out num);
                string text;
                errorInfo2.GetSource(out text);
                ex.Source = text;
                errorInfo2.GetDescription(out text);
                ex.SetMessage(text);
                errorInfo2.GetHelpFile(out text);
                if (num == 0U)
                {
                    ex.HelpLink = text;
                }
                else
                {
                    ex.HelpLink = string.Format("{0}#{1}", text, num);
                }
            }
            return ex;
        }
References System.Exception._HResult, System.Runtime.InteropServices.Marshal.ConvertHrToException(), System.Runtime.InteropServices.IErrorInfo.GetDescription(), System.Runtime.InteropServices.Marshal.GetErrorInfo(), System.Runtime.InteropServices.IErrorInfo.GetHelpContext(), System.Runtime.InteropServices.IErrorInfo.GetHelpFile(), System.Runtime.InteropServices.Marshal.GetObjectForIUnknown(), System.Runtime.InteropServices.IErrorInfo.GetSource(), System.Exception.SetMessage(), System.text, System.U, and System.IntPtr.Zero.