Terraria Decompiled: System.Runtime.InteropServices.Marshal.Copy
Copy() [10/16]
static unsafe void System.Runtime.InteropServices.Marshal.Copy (IntPtr source, int[] destination, int startIndex, int length) inline static
Definition at line 306 of file Marshal.cs.
        {
            if (Marshal.skip_fixed(destination, startIndex))
            {
                Marshal.copy_from_unmanaged(source, startIndex, destination, length);
                return;
            }
            fixed (int* ptr = &destination[startIndex])
            {
                void* ptr2 = (void*)ptr;
                Marshal.copy_from_unmanaged_fixed(source, startIndex, destination, length, ptr2);
            }
        }
References System.Runtime.InteropServices.Marshal.copy_from_unmanaged(), System.Runtime.InteropServices.Marshal.copy_from_unmanaged_fixed(), System.destination, System.length, System.Runtime.InteropServices.Marshal.skip_fixed(), System.source, and System.startIndex.