Terraria Decompiled: System.Runtime.InteropServices.Marshal.Release
Release()
static int System.Runtime.InteropServices.Marshal.Release (IntPtr pUnk) inline static
Definition at line 1206 of file Marshal.cs.
        {
            if (pUnk == IntPtr.Zero)
            {
                throw new ArgumentNullException("pUnk");
            }
            return Marshal.ReleaseInternal(pUnk);
        }
References System.Runtime.InteropServices.Marshal.ReleaseInternal(), and System.IntPtr.Zero.
Referenced by System.Variant.Clear(), Mono.Interop.ComInteropProxy.CreateProxy(), System.Runtime.InteropServices.DispatchWrapper.DispatchWrapper(), Mono.Interop.ComInteropProxy.GetProxy(), System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeInterfaceAsObject(), and System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.ReportUnhandledError().