Terraria Decompiled: Terraria.GameContent.CraftingRequests.HandleRequest
HandleRequest()
static void Terraria.GameContent.CraftingRequests.HandleRequest (int whoAmI, List< Recipe::RequiredItemEntry > items, List< Chest > chests) inline static private
Definition at line 255 of file CraftingRequests.cs.
        {
            chests.RemoveAll((Chest chest) => chest == null || !CraftingRequests.CanCraftFromChest(chest, whoAmI));
            if (!items.All((Recipe.RequiredItemEntry req) => CraftingRequests.CountMatches(req, chests) >= req.stack))
            {
                NetManager.Instance.SendToClient(CraftingRequests.NetCraftingRequestsModule.WriteResponse(false), whoAmI);
                return;
            }
            foreach (Recipe.RequiredItemEntry requiredItemEntry in items)
            {
                CraftingRequests.Consume(requiredItemEntry, chests, null, true);
            }
            NetManager.Instance.SendToClient(CraftingRequests.NetCraftingRequestsModule.WriteResponse(true), whoAmI);
        }
References Terraria.GameContent.CraftingRequests.CanCraftFromChest(), Terraria.GameContent.CraftingRequests.Consume(), Terraria.GameContent.CraftingRequests.CountMatches(), Terraria.Net.NetManager.Instance, System.Collections.Generic.List< T >.RemoveAll(), Terraria.Net.NetManager.SendToClient(), and Terraria.GameContent.CraftingRequests.NetCraftingRequestsModule.WriteResponse().
Referenced by Terraria.GameContent.CraftingRequests.NetCraftingRequestsModule.DeserializeRequest().