Terraria Decompiled: System.Runtime.InteropServices.Marshal.CreateWrapperOfType
CreateWrapperOfType()
static object System.Runtime.InteropServices.Marshal.CreateWrapperOfType (object o, Type t) inline static
Definition at line 393 of file Marshal.cs.
        {
            __ComObject _ComObject = o as __ComObject;
            if (_ComObject == null)
            {
                throw new ArgumentException("o must derive from __ComObject", "o");
            }
            if (t == null)
            {
                throw new ArgumentNullException("t");
            }
            foreach (Type type in o.GetType().GetInterfaces())
            {
                if (type.IsImport && _ComObject.GetInterface(type) == IntPtr.Zero)
                {
                    throw new InvalidCastException();
                }
            }
            return ComInteropProxy.GetProxy(_ComObject.IUnknown, t).GetTransparentProxy();
        }
References System.Type.GetInterfaces(), Mono.Interop.ComInteropProxy.GetProxy(), System.Runtime.Remoting.Proxies.RealProxy.GetTransparentProxy(), System.Type.GetType(), System.Type.IsImport, and System.IntPtr.Zero.
Referenced by System.Runtime.InteropServices.Marshal.CreateWrapperOfType< T, TWrapper >().