Terraria Decompiled: System.Runtime.InteropServices.Marshal.ClearAnsi
ClearAnsi()
static void System.Runtime.InteropServices.Marshal.ClearAnsi (IntPtr ptr) inline static private
Definition at line 462 of file Marshal.cs.
        {
            int num = 0;
            while (Marshal.ReadByte(ptr, num) != 0)
            {
                Marshal.WriteByte(ptr, num, 0);
                num++;
            }
        }
References System.Runtime.InteropServices.Marshal.ReadByte(), and System.Runtime.InteropServices.Marshal.WriteByte().
Referenced by System.Runtime.InteropServices.Marshal.ZeroFreeCoTaskMemAnsi(), System.Runtime.InteropServices.Marshal.ZeroFreeCoTaskMemUTF8(), and System.Runtime.InteropServices.Marshal.ZeroFreeGlobalAllocAnsi().