Terraria Decompiled: System.Runtime.InteropServices.Marshal.FreeHGlobal
FreeHGlobal()
static void System.Runtime.InteropServices.Marshal.FreeHGlobal (IntPtr hglobal)
Referenced by Microsoft.Xna.Framework.Audio.AudioEngine.AudioEngine(), Steamworks.SteamApps.BGetDLCDataByIndex(), UTF8Marshaler.CleanUpNativeData(), Steamworks.SteamGameServerNetworkingUtils.ConvertPingLocationToString(), Steamworks.SteamNetworkingUtils.ConvertPingLocationToString(), Dav1dfile.Bindings.df_fopen(), System.IO.HGlobalUnmanagedMemoryStream.Dispose(), FAudio.FACTAudioEngine_PrepareWave(), Steamworks.SteamGameServerUtils.FilterText(), Steamworks.SteamUtils.FilterText(), Steamworks.InteropHelp.SteamParamStringArray.Finalize(), Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_SetStringMarker(), Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_SetTextureName(), System.Threading.Overlapped.Free(), Steamworks.SteamApps.GetAppInstallDir(), Steamworks.SteamParties.GetBeaconDetails(), Steamworks.SteamParties.GetBeaconLocationData(), Steamworks.SteamApps.GetBetaInfo(), Steamworks.SteamFriends.GetClanChatMessage(), Steamworks.SteamGameServerNetworkingSockets.GetConnectionName(), Steamworks.SteamNetworkingSockets.GetConnectionName(), Steamworks.SteamApps.GetCurrentBetaName(), Steamworks.SteamGameServerNetworkingSockets.GetDetailedConnectionStatus(), Steamworks.SteamNetworkingSockets.GetDetailedConnectionStatus(), Steamworks.SteamGameServerUtils.GetEnteredGamepadTextInput(), Steamworks.SteamUtils.GetEnteredGamepadTextInput(), Steamworks.SteamFriends.GetFriendMessage(), Steamworks.SteamGameServerInventory.GetItemDefinitionProperty(), Steamworks.SteamInventory.GetItemDefinitionProperty(), Steamworks.SteamGameServerUGC.GetItemInstallInfo(), Steamworks.SteamUGC.GetItemInstallInfo(), Steamworks.SteamApps.GetLaunchCommandLine(), Steamworks.SteamMatchmaking.GetLobbyDataByIndex(), Steamworks.SteamUserStats.GetMostAchievedAchievementInfo(), Steamworks.SteamUserStats.GetNextMostAchievedAchievementInfo(), Steamworks.SteamVideo.GetOPFStringForApp(), Steamworks.SteamGameServerUGC.GetQueryUGCAdditionalPreview(), Steamworks.SteamUGC.GetQueryUGCAdditionalPreview(), Steamworks.SteamGameServerUGC.GetQueryUGCKeyValueTag(), Steamworks.SteamUGC.GetQueryUGCKeyValueTag(), Steamworks.SteamGameServerUGC.GetQueryUGCKeyValueTag(), Steamworks.SteamUGC.GetQueryUGCKeyValueTag(), Steamworks.SteamGameServerUGC.GetQueryUGCMetadata(), Steamworks.SteamUGC.GetQueryUGCMetadata(), Steamworks.SteamGameServerUGC.GetQueryUGCPreviewURL(), Steamworks.SteamUGC.GetQueryUGCPreviewURL(), Steamworks.SteamGameServerUGC.GetQueryUGCTag(), Steamworks.SteamUGC.GetQueryUGCTag(), Steamworks.SteamGameServerUGC.GetQueryUGCTagDisplayName(), Steamworks.SteamUGC.GetQueryUGCTagDisplayName(), Steamworks.SteamGameServerInventory.GetResultItemProperty(), Steamworks.SteamInventory.GetResultItemProperty(), Steamworks.SteamGameServerUGC.GetSupportedGameVersionData(), Steamworks.SteamUGC.GetSupportedGameVersionData(), Steamworks.SteamUser.GetUserDataFolder(), Steamworks.SteamAPI.InitEx(), Steamworks.GameServer.InitEx(), ReLogic.OS.OSX.PathService.MarshalNSString(), nativefiledialog.NFD_OpenDialog(), nativefiledialog.NFD_OpenDialogMultiple(), nativefiledialog.NFD_PickFolder(), nativefiledialog.NFD_SaveDialog(), Steamworks.InteropHelp.UTF8StringHandle.ReleaseHandle(), Steamworks.SteamGameSearch.RetrieveConnectionDetails(), Steamworks.CallbackDispatcher.RunFrame(), SDL2.SDL.SDL_AndroidRequestPermission(), SDL2.SDL.SDL_AndroidShowToast(), SDL2.SDL.SDL_CreateShapedWindow(), SDL2.SDL.SDL_GameControllerAddMapping(), SDL2.SDL.SDL_GL_LoadLibrary(), SDL2.SDL.SDL_LoadFile(), SDL2.SDL.SDL_OpenURL(), SDL2.SDL.SDL_RWFromFile(), SDL2.SDL.SDL_SetClipboardText(), SDL2.SDL.SDL_ShowMessageBox(), SDL2.SDL.SDL_Vulkan_LoadLibrary(), Terraria.Utilities.MessageBox.Show(), Steamworks.CallbackDispatcher.Shutdown(), Steamworks.SteamGameServerNetworkingUtils.SteamNetworkingIdentity_ToString(), Steamworks.SteamNetworkingUtils.SteamNetworkingIdentity_ToString(), Steamworks.SteamGameServerNetworkingUtils.SteamNetworkingIPAddr_ToString(), Steamworks.SteamNetworkingUtils.SteamNetworkingIPAddr_ToString(), Theorafile.tf_close(), Theorafile.tf_fopen(), Steamworks.SteamNetworkingIdentity.ToString(), Steamworks.SteamNetworkingIPAddr.ToString(), System.Runtime.InteropServices.Marshal.ZeroFreeGlobalAllocAnsi(), System.Runtime.InteropServices.Marshal.ZeroFreeGlobalAllocUnicode(), Steamworks.ISteamMatchmakingPingResponse.~ISteamMatchmakingPingResponse(), Steamworks.ISteamMatchmakingPlayersResponse.~ISteamMatchmakingPlayersResponse(), Steamworks.ISteamMatchmakingRulesResponse.~ISteamMatchmakingRulesResponse(), Steamworks.ISteamMatchmakingServerListResponse.~ISteamMatchmakingServerListResponse(), and Steamworks.MMKVPMarshaller.~MMKVPMarshaller().