Terraria Decompiled: System.Runtime.InteropServices.Marshal.GetObjectForIUnknown
GetObjectForIUnknown()
static object System.Runtime.InteropServices.Marshal.GetObjectForIUnknown (IntPtr pUnk) inline static
Definition at line 744 of file Marshal.cs.
        {
            object obj = Marshal.GetObjectForCCW(pUnk);
            if (obj == null)
            {
                obj = ComInteropProxy.GetProxy(pUnk, typeof(__ComObject)).GetTransparentProxy();
            }
            return obj;
        }
References System.Runtime.InteropServices.Marshal.GetObjectForCCW(), Mono.Interop.ComInteropProxy.GetProxy(), System.Runtime.Remoting.Proxies.RealProxy.GetTransparentProxy(), and System.obj.
Referenced by System.Runtime.InteropServices.Marshal.GetExceptionForHR(), System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeInterfaceAsObject(), System.Variant.GetValue(), and System.Variant.GetValueAt().