Terraria Decompiled: System.Runtime.InteropServices.Marshal.StringToAllocatedMemoryUTF8
StringToAllocatedMemoryUTF8()
static unsafe IntPtr System.Runtime.InteropServices.Marshal.StringToAllocatedMemoryUTF8 (string s) inline static
Definition at line 1349 of file Marshal.cs.
        {
            if (s == null)
            {
                return IntPtr.Zero;
            }
            int num = (s.Length + 1) * 3;
            if (num < s.Length)
            {
                throw new ArgumentOutOfRangeException("s");
            }
            IntPtr intPtr = Marshal.AllocCoTaskMemSize(new UIntPtr((uint)(num + 1)));
            if (intPtr == IntPtr.Zero)
            {
                throw new OutOfMemoryException();
            }
            byte* ptr = (byte*)(void*)intPtr;
            fixed (string text = s)
            {
                char* ptr2 = text;
                if (ptr2 != null)
                {
                    ptr2 += RuntimeHelpers.OffsetToStringData / 2;
                }
                int bytes = Encoding.UTF8.GetBytes(ptr2, s.Length, ptr, num);
                ptr[bytes] = 0;
            }
            return intPtr;
        }
References System.Runtime.InteropServices.Marshal.AllocCoTaskMemSize(), System.Text.Encoding.GetBytes(), System.s, System.text, System.Text.Encoding.UTF8, and System.IntPtr.Zero.
Referenced by System.Runtime.InteropServices.Marshal.StringToCoTaskMemAnsi().