Terraria Decompiled: Terraria.GameContent.CraftingRequests.CraftItem
CraftItem()
static void Terraria.GameContent.CraftingRequests.CraftItem (Recipe recipe, int qty = 1, bool quickCraft = false) inline static
Definition at line 31 of file CraftingRequests.cs.
        {
            Player localPlayer = Main.LocalPlayer;
            List<Chest> chests = Recipe._recipeChests;
            List<Recipe.RequiredItemEntry> list = new List<Recipe.RequiredItemEntry>();
            int num = 0;
            Func<Recipe.RequiredItemEntry, bool> <>9__0;
            while (num < qty && (num <= 0 || (Recipe.CollectedEnoughItemsToCraft(recipe) && Main.CursorHasSpaceToCraftRecipe(recipe))))
            {
                list.Clear();
                recipe.GetIngredientsForOneCraft(localPlayer, list);
                if (Main.netMode == 0)
                {
                    goto IL_007C;
                }
                IEnumerable<Recipe.RequiredItemEntry> enumerable = list;
                Func<Recipe.RequiredItemEntry, bool> func;
                if ((func = <>9__0) == null)
                {
                    func = (<>9__0 = (Recipe.RequiredItemEntry req) => CraftingRequests.CanCraftLocally(req, chests));
                }
                if (enumerable.All(func))
                {
                    goto IL_007C;
                }
                CraftingRequests.CraftViaRequest(recipe, quickCraft, chests, list);
                IL_009A:
                foreach (Recipe.RequiredItemEntry requiredItemEntry in list)
                {
                    Recipe.SubtractOwnedItem(requiredItemEntry);
                }
                num++;
                continue;
                IL_007C:
                CraftingRequests.CraftLocally(recipe, quickCraft, chests, list);
                goto IL_009A;
            }
            CraftingEffects.OnCraft(recipe, quickCraft);
        }
References Terraria.Recipe._recipeChests, Terraria.GameContent.CraftingRequests.CanCraftLocally(), Terraria.Recipe.CollectedEnoughItemsToCraft(), Terraria.GameContent.CraftingRequests.CraftLocally(), Terraria.GameContent.CraftingRequests.CraftViaRequest(), Terraria.Main.CursorHasSpaceToCraftRecipe(), Terraria.Recipe.GetIngredientsForOneCraft(), System.list, Terraria.Main.LocalPlayer, Terraria.Main.netMode, Terraria.GameContent.CraftingEffects.OnCraft(), and Terraria.Recipe.SubtractOwnedItem().
Referenced by Terraria.UI.ItemSlot.GetQuickCraftGamepadInstructions(), Terraria.Main.HoverOverCraftingItemButton(), and Terraria.Initializers.UILinksInitializer.TryQuickCrafting().