Terraria Decompiled: Terraria.WorldBuilding.Actions.SetTileKeepWall.Apply
Apply()
override bool Terraria.WorldBuilding.Actions.SetTileKeepWall.Apply (Point origin, int x, int y, params object[] args) inline
Definition at line 376 of file Actions.cs.
            {
                ushort wall = GenBase._tiles[x, y].wall;
                int num = GenBase._tiles[x, y].wallFrameX();
                int num2 = GenBase._tiles[x, y].wallFrameY();
                GenBase._tiles[x, y].Clear(~(TileDataType.Wiring | TileDataType.Actuator));
                GenBase._tiles[x, y].type = this._type;
                GenBase._tiles[x, y].active(true);
                if (wall > 0)
                {
                    GenBase._tiles[x, y].wall = wall;
                    GenBase._tiles[x, y].wallFrameX(num);
                    GenBase._tiles[x, y].wallFrameY(num2);
                }
                if (this._doFraming)
                {
                    WorldUtils.TileFrame(x, y, this._doNeighborFraming);
                }
                return base.UnitApply(origin, x, y, args);
            }
References Terraria.WorldBuilding.Actions.SetTileKeepWall._doFraming, Terraria.WorldBuilding.Actions.SetTileKeepWall._doNeighborFraming, Terraria.WorldBuilding.GenBase._tiles, Terraria.WorldBuilding.Actions.SetTileKeepWall._type, Terraria.Tile.active(), Terraria.Tile.Clear(), Terraria.WorldBuilding.WorldUtils.TileFrame(), Terraria.Tile.type, Terraria.Tile.wall, Terraria.Tile.wallFrameX(), and Terraria.Tile.wallFrameY().