Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.ObjectMap.ObjectMap
ObjectMap() [2/2]
System.Runtime.Serialization.Formatters.Binary.ObjectMap.ObjectMap (string objectName, string[] memberNames, BinaryTypeEnum[] binaryTypeEnumA, object[] typeInformationA, int[] memberAssemIds, ObjectReader objectReader, int objectId, BinaryAssemblyInfo assemblyInfo, SizedArray assemIdToAssemblyTable) inline package
Definition at line 34 of file ObjectMap.cs.
        {
            this.objectName = objectName;
            this.memberNames = memberNames;
            this.binaryTypeEnumA = binaryTypeEnumA;
            this.typeInformationA = typeInformationA;
            this.objectReader = objectReader;
            this.objectId = objectId;
            this.assemblyInfo = assemblyInfo;
            if (assemblyInfo == null)
            {
                throw new SerializationException(Environment.GetResourceString("No assembly information is available for object on the wire, '{0}'.", new object[] { objectName }));
            }
            this.objectType = objectReader.GetType(assemblyInfo, objectName);
            this.memberTypes = new Type[memberNames.Length];
            for (int i = 0; i < memberNames.Length; i++)
            {
                InternalPrimitiveTypeE internalPrimitiveTypeE;
                string text;
                Type type;
                bool flag;
                BinaryConverter.TypeFromInfo(binaryTypeEnumA[i], typeInformationA[i], objectReader, (BinaryAssemblyInfo)assemIdToAssemblyTable[memberAssemIds[i]], out internalPrimitiveTypeE, out text, out type, out flag);
                this.memberTypes[i] = type;
            }
            this.objectInfo = objectReader.CreateReadObjectInfo(this.objectType, memberNames, null);
            if (!this.objectInfo.isSi)
            {
                this.objectInfo.GetMemberTypes(memberNames, this.objectInfo.objectType);
            }
        }
References System.Runtime.Serialization.Formatters.Binary.ObjectMap.assemblyInfo, System.Runtime.Serialization.Formatters.Binary.ObjectMap.binaryTypeEnumA, System.Runtime.Serialization.Formatters.Binary.ObjectReader.CreateReadObjectInfo(), System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.GetMemberTypes(), System.Environment.GetResourceString(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.GetType(), System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.isSi, System.Runtime.Serialization.Formatters.Binary.ObjectMap.memberNames, System.Runtime.Serialization.Formatters.Binary.ObjectMap.memberTypes, System.Runtime.Serialization.Formatters.Binary.ObjectMap.objectId, System.Runtime.Serialization.Formatters.Binary.ObjectMap.objectInfo, System.Runtime.Serialization.Formatters.Binary.ObjectMap.objectName, System.Runtime.Serialization.Formatters.Binary.ObjectMap.objectReader, System.Runtime.Serialization.Formatters.Binary.ObjectMap.objectType, System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.objectType, System.text, System.Runtime.Serialization.Formatters.Binary.BinaryConverter.TypeFromInfo(), and System.Runtime.Serialization.Formatters.Binary.ObjectMap.typeInformationA.