Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.Features.DungeonWindowBasic.Window
Window()
bool Terraria.GameContent.Generation.Dungeon.Features.DungeonWindowBasic.Window (DungeonData data, int placeX, int placeY, DungeonGenerationStyleData style, bool generating = false) inline
Definition at line 30 of file DungeonWindowBasic.cs.
        {
            UnifiedRandom genRand = WorldGen.genRand;
            DungeonWindowBasicSettings dungeonWindowBasicSettings = (DungeonWindowBasicSettings)this.settings;
            int width = dungeonWindowBasicSettings.Width;
            int height = dungeonWindowBasicSettings.Height;
            int overrideGlassPaint = dungeonWindowBasicSettings.OverrideGlassPaint;
            ushort num = (dungeonWindowBasicSettings.Closed ? style.WindowClosedGlassWallType : style.WindowGlassWallType);
            ushort windowEdgeWallType = style.WindowEdgeWallType;
            int num2 = style.GetWindowPlatformStyle(genRand);
            if (dungeonWindowBasicSettings.OverrideGlassType > 0)
            {
                num = (ushort)dungeonWindowBasicSettings.OverrideGlassType;
            }
            if (dungeonWindowBasicSettings.OverridePlatformStyle > -1)
            {
                num2 = dungeonWindowBasicSettings.OverridePlatformStyle;
            }
            this.Bounds.SetBounds(placeX, placeY, placeX, placeY);
            for (int i = 0; i < width; i++)
            {
                int num3 = placeX + i - width / 2;
                for (int j = 0; j < height; j++)
                {
                    if (this.Window_ValidWindowSpot(i, j, width, height))
                    {
                        int num4 = placeY + j - height / 2;
                        if (i == width / 2 || j == height / 2)
{
                            Main.tile[num3, num4].wall = windowEdgeWallType;
                        }
                        else
{
                            Main.tile[num3, num4].wall = num;
                            if (overrideGlassPaint >= 0)
{
                                Main.tile[num3, num4].wallColor((byte)overrideGlassPaint);
                            }
                        }
                        this.Bounds.UpdateBounds(num3, num4);
                        if (!this.Window_ValidWindowSpot(i - 1, j, width, height))
{
                            Main.tile[num3 - 1, num4].wall = windowEdgeWallType;
                            this.Bounds.UpdateBounds(num3 - 1, num4);
                        }
                        if (!this.Window_ValidWindowSpot(i + 1, j, width, height))
{
                            Main.tile[num3 + 1, num4].wall = windowEdgeWallType;
                            this.Bounds.UpdateBounds(num3 + 1, num4);
                        }
                        if (!this.Window_ValidWindowSpot(i, j - 1, width, height))
{
                            Main.tile[num3, num4 - 1].wall = windowEdgeWallType;
                            this.Bounds.UpdateBounds(num3, num4 - 1);
                        }
                        if (!this.Window_ValidWindowSpot(i, j + 1, width, height))
{
                            Main.tile[num3, num4 + 1].wall = windowEdgeWallType;
                            this.Bounds.UpdateBounds(num3, num4 + 1);
                            if (num2 > -1)
{
                                Main.tile[num3, num4 + 1].active(true);
                                Main.tile[num3, num4 + 1].type = 19;
                                Main.tile[num3, num4 + 1].Clear(TileDataType.Slope);
                                Main.tile[num3, num4 + 1].frameY = (short)(num2 * 18);
                                WorldGen.TileFrame(num3, num4 + 1, false, false);
                            }
                        }
                    }
                }
            }
            this.Bounds.CalculateHitbox();
            return true;
        }
References Terraria.Tile.active(), Terraria.GameContent.Generation.Dungeon.Features.DungeonFeature.Bounds, Terraria.GameContent.Generation.Dungeon.DungeonBounds.CalculateHitbox(), Terraria.Tile.Clear(), Terraria.Tile.frameY, Terraria.WorldGen.genRand, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.GetWindowPlatformStyle(), Terraria.GameContent.Generation.Dungeon.Features.DungeonWindowBasicSettings.Height, Terraria.GameContent.Generation.Dungeon.Features.DungeonWindowSettings.OverrideGlassPaint, Terraria.GameContent.Generation.Dungeon.Features.DungeonWindowSettings.OverrideGlassType, Terraria.GameContent.Generation.Dungeon.Features.DungeonWindowBasicSettings.OverridePlatformStyle, Terraria.GameContent.Generation.Dungeon.DungeonBounds.SetBounds(), Terraria.GameContent.Generation.Dungeon.Features.DungeonFeature.settings, Terraria.Main.tile, Terraria.WorldGen.TileFrame(), Terraria.Tile.type, Terraria.GameContent.Generation.Dungeon.DungeonBounds.UpdateBounds(), Terraria.Tile.wall, Terraria.Tile.wallColor(), Terraria.GameContent.Generation.Dungeon.Features.DungeonWindowBasicSettings.Width, Terraria.GameContent.Generation.Dungeon.Features.DungeonWindowBasic.Window_ValidWindowSpot(), Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.WindowEdgeWallType, and Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.WindowGlassWallType.
Referenced by Terraria.GameContent.Generation.Dungeon.Features.DungeonWindowBasic.GenerateFeature().