Terraria Decompiled: Microsoft.Xna.Framework.FrameworkDispatcher.Update
Update()
static void Microsoft.Xna.Framework.FrameworkDispatcher.Update () inline static
Definition at line 13 of file FrameworkDispatcher.cs.
        {
            List<DynamicSoundEffectInstance> streams = FrameworkDispatcher.Streams;
            lock (streams)
            {
                for (int i = 0; i < FrameworkDispatcher.Streams.Count; i++)
                {
                    DynamicSoundEffectInstance dynamicSoundEffectInstance = FrameworkDispatcher.Streams[i];
                    dynamicSoundEffectInstance.Update();
                    if (dynamicSoundEffectInstance.IsDisposed)
                    {
                        i--;
                    }
                }
            }
            if (Microphone.micList != null)
            {
                for (int j = 0; j < Microphone.micList.Count; j++)
                {
                    Microphone.micList[j].CheckBuffer();
                }
            }
            MediaPlayer.Update();
            if (FrameworkDispatcher.ActiveSongChanged)
            {
                MediaPlayer.OnActiveSongChanged();
                FrameworkDispatcher.ActiveSongChanged = false;
            }
            if (FrameworkDispatcher.MediaStateChanged)
            {
                MediaPlayer.OnMediaStateChanged();
                FrameworkDispatcher.MediaStateChanged = false;
            }
            if (TouchPanel.TouchDeviceExists)
            {
                TouchPanel.Update();
            }
        }
References Microsoft.Xna.Framework.FrameworkDispatcher.ActiveSongChanged, System.Collections.Generic.List< T >.Count, Microsoft.Xna.Framework.Audio.SoundEffectInstance.IsDisposed, Microsoft.Xna.Framework.FrameworkDispatcher.MediaStateChanged, Microsoft.Xna.Framework.Audio.Microphone.micList, Microsoft.Xna.Framework.Media.MediaPlayer.OnActiveSongChanged(), Microsoft.Xna.Framework.Media.MediaPlayer.OnMediaStateChanged(), Microsoft.Xna.Framework.FrameworkDispatcher.Streams, Microsoft.Xna.Framework.Input.Touch.TouchPanel.TouchDeviceExists, Microsoft.Xna.Framework.Audio.DynamicSoundEffectInstance.Update(), Microsoft.Xna.Framework.Input.Touch.TouchPanel.Update(), and Microsoft.Xna.Framework.Media.MediaPlayer.Update().
Referenced by Microsoft.Xna.Framework.Game.Game(), and Microsoft.Xna.Framework.Game.Update().