Terraria Decompiled: System.Globalization.Bootstring.Decode
Decode()
string System.Globalization.Bootstring.Decode (string s, int offset) inline
Definition at line 139 of file Bootstring.cs.
        {
            int num = this.initial_n;
            int num2 = 0;
            int num3 = this.initial_bias;
            int num4 = 0;
            StringBuilder stringBuilder = new StringBuilder();
            for (int i = 0; i < s.Length; i++)
            {
                if (s[i] == this.delimiter)
                {
                    num4 = i;
                }
            }
            if (num4 < 0)
            {
                return s;
            }
            stringBuilder.Append(s, 0, num4);
            int j = ((num4 > 0) ? (num4 + 1) : 0);
            while (j < s.Length)
            {
                int num5 = num2;
                int num6 = 1;
                int num7 = this.base_num;
                for (;;)
                {
                    int num8 = this.DecodeDigit(s[j++]);
                    num2 += num8 * num6;
                    int num9 = ((num7 <= num3 + this.tmin) ? this.tmin : ((num7 >= num3 + this.tmax) ? this.tmax : (num7 - num3)));
                    if (num8 < num9)
                    {
                        break;
                    }
                    num6 *= this.base_num - num9;
                    num7 += this.base_num;
                }
                num3 = this.Adapt(num2 - num5, stringBuilder.Length + 1, num5 == 0);
                num += num2 / (stringBuilder.Length + 1);
                num2 %= stringBuilder.Length + 1;
                if (num < 128)
                {
                    throw new ArgumentException(string.Format("Invalid Bootstring decode result, at {0}", offset + j));
                }
                stringBuilder.Insert(num2, (char)num);
                num2++;
            }
            return stringBuilder.ToString();
        }
References System.Globalization.Bootstring.Adapt(), System.Text.StringBuilder.Append(), System.Globalization.Bootstring.base_num, System.Globalization.Bootstring.DecodeDigit(), System.Globalization.Bootstring.delimiter, System.Globalization.Format, System.Globalization.Bootstring.initial_bias, System.Globalization.Bootstring.initial_n, System.Text.StringBuilder.Insert(), System.Text.StringBuilder.Length, System.offset, System.s, System.Globalization.Bootstring.tmax, System.Globalization.Bootstring.tmin, and System.Text.StringBuilder.ToString().
Referenced by System.Globalization.IdnMapping.ToUnicode().