Terraria Decompiled: System.Globalization.Bootstring.Encode
Encode()
string System.Globalization.Bootstring.Encode (string s, int offset) inline
Definition at line 23 of file Bootstring.cs.
        {
            int num = this.initial_n;
            int num2 = 0;
            int num3 = this.initial_bias;
            StringBuilder stringBuilder = new StringBuilder();
            for (int i = 0; i < s.Length; i++)
            {
                if (s[i] < '\u0080')
                {
                    stringBuilder.Append(s[i]);
                }
            }
            int length;
            int j = (length = stringBuilder.Length);
            if (length > 0)
            {
                stringBuilder.Append(this.delimiter);
            }
            while (j < s.Length)
            {
                int num4 = int.MaxValue;
                for (int k = 0; k < s.Length; k++)
                {
                    if ((int)s[k] >= num && (int)s[k] < num4)
                    {
                        num4 = (int)s[k];
                    }
                }
                checked
                {
                    num2 += (num4 - num) * (j + 1);
                    num = num4;
                    foreach (char c in s)
                    {
                        if ((int)c < num || c < '\u0080')
{
                            num2++;
                        }
                        unchecked
{
                            if ((int)c == num)
{
                                int num5 = num2;
                                int num6 = this.base_num;
                                for (;;)
{
                                    int num7 = ((num6 <= num3 + this.tmin) ? this.tmin : ((num6 >= num3 + this.tmax) ? this.tmax : (num6 - num3)));
                                    if (num5 < num7)
{
                                        break;
                                    }
                                    stringBuilder.Append(this.EncodeDigit(num7 + (num5 - num7) % (this.base_num - num7)));
                                    num5 = (num5 - num7) / (this.base_num - num7);
                                    num6 += this.base_num;
                                }
                                stringBuilder.Append(this.EncodeDigit(num5));
                                num3 = this.Adapt(num2, j + 1, j == length);
                                num2 = 0;
                                j++;
                            }
                        }
                    }
                }
                num2++;
                num++;
            }
            return stringBuilder.ToString();
        }
References System.Globalization.Bootstring.Adapt(), System.Text.StringBuilder.Append(), System.Globalization.Bootstring.base_num, System.Globalization.Bootstring.delimiter, System.Globalization.Bootstring.EncodeDigit(), System.Globalization.Bootstring.initial_bias, System.Globalization.Bootstring.initial_n, int, System.length, System.Text.StringBuilder.Length, System.s, System.Globalization.Bootstring.tmax, System.Globalization.Bootstring.tmin, and System.Text.StringBuilder.ToString().
Referenced by System.Globalization.IdnMapping.ToAscii().