Terraria Decompiled: Terraria.DataStructures.TitleLinkButton.DrawTooltip
DrawTooltip()
void Terraria.DataStructures.TitleLinkButton.DrawTooltip () inline private
Definition at line 44 of file TitleLinkButton.cs.
        {
            Item fakeItem = TitleLinkButton._fakeItem;
            fakeItem.SetDefaults(0, null);
            string textValue = Language.GetTextValue(this.TooltipTextKey);
            fakeItem.SetNameOverride(textValue);
            fakeItem.type = 1;
            fakeItem.scale = 0f;
            fakeItem.rare = 8;
            fakeItem.value = -1;
            Main.HoverItem = TitleLinkButton._fakeItem;
            Main.instance.MouseText("", 0, 0, -1, -1, -1, -1, 0);
            Main.mouseText = true;
        }
References Terraria.DataStructures.TitleLinkButton._fakeItem, Terraria.Localization.Language.GetTextValue(), Terraria.Main.instance, Terraria.Main.MouseText(), Terraria.Item.SetDefaults(), Terraria.Item.SetNameOverride(), and Terraria.DataStructures.TitleLinkButton.TooltipTextKey.
Referenced by Terraria.DataStructures.TitleLinkButton.Draw().