Terraria Decompiled: Terraria.RemoteClient.Reset
Reset()
void Terraria.RemoteClient.Reset () inline
Definition at line 228 of file RemoteClient.cs.
        {
            Array.Clear(this.TileSections, 0, this.TileSections.Length);
            Array.Clear(this.TileSectionsCheckTime, 0, this.TileSectionsCheckTime.Length);
            if (this.Id < 255)
            {
                Main.player[this.Id] = new Player();
            }
            this.TimeOutTimer = 0;
            this.StatusCount = 0;
            this.StatusMax = 0;
            this.StatusText2 = "";
            this.StatusText = "";
            this.State = 0;
            this._isReading = false;
            this.PendingTermination = false;
            this.PendingTerminationApproved = false;
            this.SpamClear();
            this.IsActive = false;
            NetMessage.buffer[this.Id].Reset();
            if (this.Socket != null)
            {
                this.Socket.Close();
            }
        }
References Terraria.NetMessage.buffer, System.Array.Clear(), Terraria.Net.Sockets.ISocket.Close(), Terraria.RemoteClient.Id, Terraria.Main.player, Terraria.MessageBuffer.Reset(), Terraria.RemoteClient.Socket, Terraria.RemoteClient.SpamClear(), Terraria.RemoteClient.TileSections, and Terraria.RemoteClient.TileSectionsCheckTime.
Referenced by Terraria.Netplay.InitializeServer(), Terraria.Netplay.OnConnectionAccepted(), and Terraria.Netplay.UpdateConnectedClients().