Terraria Decompiled: Terraria.RemoteClient.UpdateStatusText
UpdateStatusText()
void Terraria.RemoteClient.UpdateStatusText () inline private
Definition at line 325 of file RemoteClient.cs.
        {
            if (this.StatusMax > 0 && this.StatusText2 != "")
            {
                if (this.StatusCount >= this.StatusMax)
                {
                    this.StatusText = Language.GetTextValue("Net.ClientStatusComplete", this.Socket.GetRemoteAddress(), this.Name, this.StatusText2);
                    this.StatusText2 = "";
                    this.StatusMax = 0;
                    this.StatusCount = 0;
                    return;
                }
                this.StatusText = string.Concat(new object[]
                {
                    "(",
                    this.Socket.GetRemoteAddress(),
                    ") ",
                    this.Name,
                    " ",
                    this.StatusText2,
                    ": ",
                    (int)((float)this.StatusCount / (float)this.StatusMax * 100f),
                    "%"
                });
                return;
            }
            else
            {
                if (this.State == 0)
                {
                    this.StatusText = Language.GetTextValue("Net.ClientConnecting", string.Format("({0}) {1}", this.Socket.GetRemoteAddress(), this.Name));
                    return;
                }
                if (this.State == 1)
                {
                    this.StatusText = Language.GetTextValue("Net.ClientSendingData", this.Socket.GetRemoteAddress(), this.Name);
                    return;
                }
                if (this.State == 2)
                {
                    this.StatusText = Language.GetTextValue("Net.ClientRequestedWorldInfo", this.Socket.GetRemoteAddress(), this.Name);
                    return;
                }
                if (this.State != 3 && this.State == 10)
                {
                    try
                    {
                        this.StatusText = Language.GetTextValue("Net.ClientPlaying", this.Socket.GetRemoteAddress(), this.Name);
                    }
                    catch (Exception)
                    {
                        this.PendingTermination = true;
                    }
                }
                return;
            }
        }
References System.Format, Terraria.Net.Sockets.ISocket.GetRemoteAddress(), Terraria.Localization.Language.GetTextValue(), Terraria.RemoteClient.Name, Terraria.RemoteClient.Socket, Terraria.RemoteClient.State, Terraria.RemoteClient.StatusCount, Terraria.RemoteClient.StatusMax, and Terraria.RemoteClient.StatusText2.
Referenced by Terraria.RemoteClient.Update().