Terraria Decompiled: Terraria.RemoteClient.CheckSection_ForClient
CheckSection_ForClient()
static void Terraria.RemoteClient.CheckSection_ForClient (RemoteClient client, Vector2 position, int fluff) inline static private
Definition at line 149 of file RemoteClient.cs.
        {
            ActiveSections.CheckSection(position, fluff);
            int sectionX = Netplay.GetSectionX((int)(position.X / 16f));
            int sectionY = Netplay.GetSectionY((int)(position.Y / 16f));
            int num = 0;
            for (int i = sectionX - fluff; i < sectionX + fluff + 1; i++)
            {
                for (int j = sectionY - fluff; j < sectionY + fluff + 1; j++)
                {
                    if (i >= 0 && i < Main.maxSectionsX && j >= 0 && j < Main.maxSectionsY)
                    {
                        bool flag = client.IsSectionActive(new Point(i, j));
                        client.TileSectionsCheckTime[i, j] = Main.GameUpdateCount;
                        if (!flag)
{
                            RemoteClient.NetSectionActivated(client.Id, new Point(i, j));
                        }
                        if (!client.TileSections[i, j])
{
                            num++;
                        }
                    }
                }
            }
            if (num > 0)
            {
                int num2 = num;
                NetMessage.SendData(9, client.Id, -1, Lang.inter[44].ToNetworkText(), num2, 0f, 0f, 0f, 0, 0, 0);
                client.StatusText2 = Language.GetTextValue("Net.IsReceivingTileData");
                client.StatusMax += num2;
                for (int k = sectionX - fluff; k < sectionX + fluff + 1; k++)
                {
                    for (int l = sectionY - fluff; l < sectionY + fluff + 1; l++)
                    {
                        NetMessage.SendSection(client.Id, k, l);
                    }
                }
            }
        }
References Terraria.DataStructures.ActiveSections.CheckSection(), Terraria.Main.GameUpdateCount, Terraria.Netplay.GetSectionX(), Terraria.Netplay.GetSectionY(), Terraria.Localization.Language.GetTextValue(), Terraria.RemoteClient.Id, Terraria.Lang.inter, Terraria.RemoteClient.IsSectionActive(), Terraria.Main.maxSectionsY, Terraria.RemoteClient.NetSectionActivated, Terraria.NetMessage.SendData(), Terraria.NetMessage.SendSection(), Terraria.RemoteClient.TileSections, Terraria.RemoteClient.TileSectionsCheckTime, Terraria.Localization.LocalizedText.ToNetworkText(), Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.RemoteClient.CheckSection().