Terraria Decompiled: Terraria.RemoteClient.SectionRange
SectionRange()
bool Terraria.RemoteClient.SectionRange (int size, int firstX, int firstY) inline
Definition at line 191 of file RemoteClient.cs.
        {
            for (int i = 0; i < 4; i++)
            {
                int num = firstX;
                int num2 = firstY;
                if (i == 1)
                {
                    num += size;
                }
                if (i == 2)
                {
                    num2 += size;
                }
                if (i == 3)
                {
                    num += size;
                    num2 += size;
                }
                int sectionX = Netplay.GetSectionX(num);
                int sectionY = Netplay.GetSectionY(num2);
                if (this.TileSections[sectionX, sectionY])
                {
                    return true;
                }
            }
            return false;
        }
References Terraria.Netplay.GetSectionX(), Terraria.Netplay.GetSectionY(), and Terraria.RemoteClient.TileSections.
Referenced by Terraria.NetMessage.SendData().