Terraria Decompiled: Microsoft.Win32.KeyHandler.VolatileKeyExists
VolatileKeyExists()
static bool Microsoft.Win32.KeyHandler.VolatileKeyExists (string dir) inline static
Definition at line 350 of file KeyHandler.cs.
        {
            Type typeFromHandle = typeof(KeyHandler);
            lock (typeFromHandle)
            {
                KeyHandler keyHandler = (KeyHandler)KeyHandler.dir_to_handler[dir];
                if (keyHandler != null)
                {
                    return keyHandler.IsVolatile;
                }
            }
            return !Directory.Exists(dir) && Directory.Exists(KeyHandler.GetVolatileDir(dir));
        }
References Microsoft.Win32.KeyHandler.dir_to_handler, System.IO.Directory.Exists(), Microsoft.Win32.KeyHandler.GetVolatileDir(), Microsoft.Win32.KeyHandler.IsVolatile, and Microsoft.Win32.KeyHandler.KeyHandler().
Referenced by Microsoft.Win32.UnixRegistryApi.CreateSubKey(), and Microsoft.Win32.KeyHandler.Probe().