Terraria Decompiled: Microsoft.Win32.KeyHandler.CleanVolatileKeys
CleanVolatileKeys()
static void Microsoft.Win32.KeyHandler.CleanVolatileKeys () inline static private
Definition at line 323 of file KeyHandler.cs.
        {
            long systemBootTime = KeyHandler.GetSystemBootTime();
            foreach (string text in new string[]
            {
                KeyHandler.UserStore,
                KeyHandler.MachineStore
            })
            {
                if (Directory.Exists(text))
                {
                    string text2 = Path.Combine(text, "last-btime");
                    string text3 = Path.Combine(text, "volatile-keys");
                    if (Directory.Exists(text3))
                    {
                        long registeredBootTime = KeyHandler.GetRegisteredBootTime(text2);
                        if (systemBootTime < 0L || registeredBootTime < 0L || registeredBootTime != systemBootTime)
{
                            Directory.Delete(text3, true);
                        }
                    }
                    KeyHandler.SaveRegisteredBootTime(text2, systemBootTime);
                }
            }
        }
References System.IO.Path.Combine(), System.IO.Directory.Delete(), System.IO.Directory.Exists(), Microsoft.Win32.KeyHandler.GetRegisteredBootTime(), Microsoft.Win32.KeyHandler.GetSystemBootTime(), System.L, Microsoft.Win32.KeyHandler.SaveRegisteredBootTime(), System.text, and Microsoft.Win32.KeyHandler.UserStore.
Referenced by Microsoft.Win32.KeyHandler.KeyHandler().