Terraria Decompiled: Microsoft.Win32.KeyHandler.Save
Save()
void Microsoft.Win32.KeyHandler.Save () inline private
Definition at line 839 of file KeyHandler.cs.
        {
            if (this.IsMarkedForDeletion)
            {
                return;
            }
            SecurityElement securityElement = new SecurityElement("values");
            Hashtable hashtable = this.values;
            lock (hashtable)
            {
                if (!File.Exists(this.file) && this.values.Count == 0)
                {
                    return;
                }
                foreach (object obj in this.values)
                {
                    DictionaryEntry dictionaryEntry = (DictionaryEntry)obj;
                    object value = dictionaryEntry.Value;
                    SecurityElement securityElement2 = new SecurityElement("value");
                    securityElement2.AddAttribute("name", SecurityElement.Escape((string)dictionaryEntry.Key));
                    if (value is string)
                    {
                        securityElement2.AddAttribute("type", "string");
                        securityElement2.Text = SecurityElement.Escape((string)value);
                    }
                    else if (value is int)
                    {
                        securityElement2.AddAttribute("type", "int");
                        securityElement2.Text = value.ToString();
                    }
                    else if (value is long)
                    {
                        securityElement2.AddAttribute("type", "qword");
                        securityElement2.Text = value.ToString();
                    }
                    else if (value is byte[])
                    {
                        securityElement2.AddAttribute("type", "bytearray");
                        securityElement2.Text = Convert.ToBase64String((byte[])value);
                    }
                    else if (value is ExpandString)
                    {
                        securityElement2.AddAttribute("type", "expand");
                        securityElement2.Text = SecurityElement.Escape(value.ToString());
                    }
                    else if (value is string[])
                    {
                        securityElement2.AddAttribute("type", "string-array");
                        foreach (string text in (string[])value)
{
                            securityElement2.AddChild(new SecurityElement("string")
{
                                Text = SecurityElement.Escape(text)
                            });
                        }
                    }
                    securityElement.AddChild(securityElement2);
                }
            }
            using (FileStream fileStream = File.Create(this.file))
            {
                StreamWriter streamWriter = new StreamWriter(fileStream);
                streamWriter.Write(securityElement.ToString());
                streamWriter.Flush();
            }
        }
References System.Security.SecurityElement.AddAttribute(), System.Security.SecurityElement.AddChild(), System.IO.File.Create(), System.Security.SecurityElement.Escape(), System.IO.File.Exists(), Microsoft.Win32.KeyHandler.file, System.IO.StreamWriter.Flush(), Microsoft.Win32.KeyHandler.IsMarkedForDeletion, System.Collections.DictionaryEntry.Key, System.obj, System.text, System.Convert.ToBase64String(), System.Security.SecurityElement.ToString(), System.Collections.DictionaryEntry.Value, System.value, Microsoft.Win32.KeyHandler.values, and System.IO.StreamWriter.Write().
Referenced by Microsoft.Win32.KeyHandler.Flush().