Terraria Decompiled: Microsoft.Win32.KeyHandler.GetSubKeyNames
GetSubKeyNames()
string[] Microsoft.Win32.KeyHandler.GetSubKeyNames () inline
Definition at line 624 of file KeyHandler.cs.
        {
            DirectoryInfo[] directories = new DirectoryInfo(this.ActualDir).GetDirectories();
            string[] array;
            if (this.IsVolatile || !Directory.Exists(KeyHandler.GetVolatileDir(this.Dir)))
            {
                array = new string[directories.Length];
                for (int i = 0; i < directories.Length; i++)
                {
                    DirectoryInfo directoryInfo = directories[i];
                    array[i] = directoryInfo.Name;
                }
                return array;
            }
            DirectoryInfo[] directories2 = new DirectoryInfo(KeyHandler.GetVolatileDir(this.Dir)).GetDirectories();
            Dictionary<string, string> dictionary = new Dictionary<string, string>();
            foreach (DirectoryInfo directoryInfo2 in directories)
            {
                dictionary[directoryInfo2.Name] = directoryInfo2.Name;
            }
            foreach (DirectoryInfo directoryInfo3 in directories2)
            {
                dictionary[directoryInfo3.Name] = directoryInfo3.Name;
            }
            array = new string[dictionary.Count];
            int num = 0;
            foreach (KeyValuePair<string, string> keyValuePair in dictionary)
            {
                array[num++] = keyValuePair.Value;
            }
            return array;
        }
References Microsoft.Win32.KeyHandler.ActualDir, System.array, System.dictionary, System.IO.Directory.Exists(), System.IO.DirectoryInfo.GetDirectories(), Microsoft.Win32.KeyHandler.GetVolatileDir(), Microsoft.Win32.KeyHandler.IsVolatile, System.IO.FileSystemInfo.Name, and System.Collections.Generic.KeyValuePair< TKey, TValue >.Value.
Referenced by Microsoft.Win32.KeyHandler.GetSubKeyCount(), and Microsoft.Win32.UnixRegistryApi.GetSubKeyNames().