Terraria Decompiled: Microsoft.Win32.KeyHandler.Drop
Drop() [1/2]
static void Microsoft.Win32.KeyHandler.Drop (RegistryKey rkey) inline static
Definition at line 436 of file KeyHandler.cs.
        {
            Type typeFromHandle = typeof(KeyHandler);
            lock (typeFromHandle)
            {
                KeyHandler keyHandler = (KeyHandler)KeyHandler.key_to_handler[rkey];
                if (keyHandler != null)
                {
                    KeyHandler.key_to_handler.Remove(rkey);
                    int num = 0;
                    foreach (object obj in KeyHandler.key_to_handler)
                    {
                        if (((DictionaryEntry)obj).Value == keyHandler)
{
                            num++;
                        }
                    }
                    if (num == 0)
                    {
                        KeyHandler.dir_to_handler.Remove(keyHandler.Dir);
                    }
                }
            }
        }
References Microsoft.Win32.KeyHandler.Dir, Microsoft.Win32.KeyHandler.dir_to_handler, Microsoft.Win32.KeyHandler.key_to_handler, Microsoft.Win32.KeyHandler.KeyHandler(), System.obj, and System.Collections.Hashtable.Remove().
Referenced by Microsoft.Win32.UnixRegistryApi.Close(), and Microsoft.Win32.KeyHandler.Delete().