Terraria Decompiled: Microsoft.Win32.KeyHandler.KeyHandler
KeyHandler() [1/3]
static Microsoft.Win32.KeyHandler.KeyHandler () inline static private
Definition at line 15 of file KeyHandler.cs.
        {
            KeyHandler.CleanVolatileKeys();
        }
References Microsoft.Win32.KeyHandler.CleanVolatileKeys().
Referenced by Microsoft.Win32.KeyHandler.Drop(), Microsoft.Win32.KeyHandler.Drop(), Microsoft.Win32.KeyHandler.Ensure(), Microsoft.Win32.KeyHandler.Lookup(), Microsoft.Win32.KeyHandler.Probe(), and Microsoft.Win32.KeyHandler.VolatileKeyExists().