Terraria Decompiled: Microsoft.Win32.KeyHandler.GetValueNames
GetValueNames()
string[] Microsoft.Win32.KeyHandler.GetValueNames () inline
Definition at line 602 of file KeyHandler.cs.
        {
            this.AssertNotMarkedForDeletion();
            Hashtable hashtable = this.values;
            string[] array2;
            lock (hashtable)
            {
                ICollection keys = this.values.Keys;
                string[] array = new string[keys.Count];
                keys.CopyTo(array, 0);
                array2 = array;
            }
            return array2;
        }
References System.array, Microsoft.Win32.KeyHandler.AssertNotMarkedForDeletion(), System.Collections.Generic.ICollection< T >.CopyTo(), System.Collections.Generic.ICollection< T >.Count, System.Collections.Hashtable.Keys, and Microsoft.Win32.KeyHandler.values.
Referenced by Microsoft.Win32.UnixRegistryApi.GetValueNames().