Terraria Decompiled: Microsoft.Win32.KeyHandler.Load
Load()
void Microsoft.Win32.KeyHandler.Load () inline
Definition at line 63 of file KeyHandler.cs.
        {
            this.values = new Hashtable();
            if (!File.Exists(this.file))
            {
                return;
            }
            try
            {
                using (FileStream fileStream = File.OpenRead(this.file))
                {
                    string text = new StreamReader(fileStream).ReadToEnd();
                    if (text.Length != 0)
                    {
                        SecurityElement securityElement = SecurityElement.FromString(text);
                        if (securityElement.Tag == "values" && securityElement.Children != null)
{
                            foreach (object obj in securityElement.Children)
{
                                SecurityElement securityElement2 = (SecurityElement)obj;
                                if (securityElement2.Tag == "value")
{
                                    this.LoadKey(securityElement2);
                                }
                            }
                        }
                    }
                }
            }
            catch (UnauthorizedAccessException)
            {
                this.values.Clear();
                throw new SecurityException("No access to the given key");
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine("While loading registry key at {0}: {1}", this.file, ex);
                this.values.Clear();
            }
        }
References System.Security.SecurityElement.Children, System.Collections.Hashtable.Clear(), System.Console.Error, System.IO.File.Exists(), Microsoft.Win32.KeyHandler.file, System.Security.SecurityElement.FromString(), Microsoft.Win32.KeyHandler.LoadKey(), System.obj, System.IO.File.OpenRead(), System.IO.StreamReader.ReadToEnd(), System.Security.SecurityElement.Tag, System.text, Microsoft.Win32.KeyHandler.values, and System.IO.TextWriter.WriteLine().
Referenced by Microsoft.Win32.KeyHandler.KeyHandler().