Terraria Decompiled: Microsoft.Win32.KeyHandler.Probe
Probe()
RegistryKey Microsoft.Win32.KeyHandler.Probe (RegistryKey rkey, string extra, bool writable) inline
Definition at line 200 of file KeyHandler.cs.
        {
            RegistryKey registryKey = null;
            Type typeFromHandle = typeof(KeyHandler);
            RegistryKey registryKey2;
            lock (typeFromHandle)
            {
                string text = Path.Combine(this.Dir, extra);
                KeyHandler keyHandler = (KeyHandler)KeyHandler.dir_to_handler[text];
                if (keyHandler != null)
                {
                    registryKey = new RegistryKey(keyHandler, KeyHandler.CombineName(rkey, extra), writable);
                    KeyHandler.key_to_handler[registryKey] = keyHandler;
                }
                else if (Directory.Exists(text) || KeyHandler.VolatileKeyExists(text))
                {
                    keyHandler = new KeyHandler(rkey, text);
                    registryKey = new RegistryKey(keyHandler, KeyHandler.CombineName(rkey, extra), writable);
                    KeyHandler.dir_to_handler[text] = keyHandler;
                    KeyHandler.key_to_handler[registryKey] = keyHandler;
                }
                registryKey2 = registryKey;
            }
            return registryKey2;
        }
References System.IO.Path.Combine(), Microsoft.Win32.KeyHandler.CombineName(), Microsoft.Win32.KeyHandler.Dir, Microsoft.Win32.KeyHandler.dir_to_handler, System.IO.Directory.Exists(), Microsoft.Win32.KeyHandler.key_to_handler, Microsoft.Win32.KeyHandler.KeyHandler(), System.text, and Microsoft.Win32.KeyHandler.VolatileKeyExists().
Referenced by Microsoft.Win32.UnixRegistryApi.OpenSubKey().