Terraria Decompiled: Microsoft.Win32.KeyHandler.LoadKey
LoadKey()
void Microsoft.Win32.KeyHandler.LoadKey (SecurityElement se) inline private
Definition at line 105 of file KeyHandler.cs.
        {
            Hashtable attributes = se.Attributes;
            try
            {
                string text = (string)attributes["name"];
                if (text != null)
                {
                    string text2 = (string)attributes["type"];
                    if (text2 != null)
                    {
                        if (!(text2 == "int"))
{
                            if (!(text2 == "bytearray"))
{
                                if (!(text2 == "string"))
{
                                    if (!(text2 == "expand"))
{
                                        if (!(text2 == "qword"))
{
                                            if (text2 == "string-array")
{
                                                List<string> list = new List<string>();
                                                if (se.Children != null)
{
                                                    foreach (object obj in se.Children)
{
                                                        SecurityElement securityElement = (SecurityElement)obj;
                                                        list.Add(securityElement.Text);
                                                    }
                                                }
                                                this.values[text] = list.ToArray();
                                            }
                                        }
                                        else
{
                                            this.values[text] = long.Parse(se.Text);
                                        }
                                    }
                                    else
{
                                        this.values[text] = new ExpandString(se.Text);
                                    }
                                }
                                else
{
                                    this.values[text] = ((se.Text == null) ? string.Empty : se.Text);
                                }
                            }
                            else
{
                                this.values[text] = Convert.FromBase64String(se.Text);
                            }
                        }
                        else
{
                            this.values[text] = int.Parse(se.Text);
                        }
                    }
                }
            }
            catch
            {
            }
        }
References System.Security.SecurityElement.Attributes, System.Security.SecurityElement.Children, Microsoft.Win32.ExpandString, System.Convert.FromBase64String(), System.list, System.obj, System.text, System.Security.SecurityElement.Text, System.Collections.Generic.List< T >.ToArray(), and Microsoft.Win32.KeyHandler.values.
Referenced by Microsoft.Win32.KeyHandler.Load().