Terraria Decompiled: Microsoft.Win32.KeyHandler.SetValue
SetValue() [2/2]
void Microsoft.Win32.KeyHandler.SetValue (string name, object value, RegistryValueKind valueKind) inline
Definition at line 658 of file KeyHandler.cs.
        {
            this.SetDirty();
            if (name == null)
            {
                name = string.Empty;
            }
            Hashtable hashtable = this.values;
            lock (hashtable)
            {
                switch (valueKind)
                {
                case RegistryValueKind.String:
                    if (value is string)
                    {
                        this.values[name] = value;
                        return;
                    }
                    goto IL_0116;
                case RegistryValueKind.ExpandString:
                    if (value is string)
                    {
                        this.values[name] = new ExpandString((string)value);
                        return;
                    }
                    goto IL_0116;
                case RegistryValueKind.Binary:
                    if (value is byte[])
                    {
                        this.values[name] = value;
                        return;
                    }
                    goto IL_0116;
                case RegistryValueKind.DWord:
                    try
                    {
                        this.values[name] = Convert.ToInt32(value);
                        return;
                    }
                    catch (OverflowException)
                    {
                        goto IL_0122;
                    }
                    break;
                case (RegistryValueKind)5:
                case (RegistryValueKind)6:
                case (RegistryValueKind)8:
                case (RegistryValueKind)9:
                case (RegistryValueKind)10:
                    goto IL_0106;
                case RegistryValueKind.MultiString:
                    break;
                case RegistryValueKind.QWord:
                    try
                    {
                        this.values[name] = Convert.ToInt64(value);
                        return;
                    }
                    catch (OverflowException)
                    {
                        goto IL_0122;
                    }
                    goto IL_0106;
                default:
                    goto IL_0106;
                }
                if (value is string[])
                {
                    this.values[name] = value;
                    return;
                }
                goto IL_0116;
                IL_0106:
                throw new ArgumentException("unknown value", "valueKind");
                IL_0116:;
            }
            IL_0122:
            throw new ArgumentException("Value could not be converted to specified type", "valueKind");
        }
References Microsoft.Win32.ExpandString, System.name, Microsoft.Win32.KeyHandler.SetDirty(), System.Convert.ToInt32(), System.Convert.ToInt64(), System.value, and Microsoft.Win32.KeyHandler.values.