Terraria Decompiled: Microsoft.Win32.KeyHandler.GetRegisteredBootTime
GetRegisteredBootTime()
static long Microsoft.Win32.KeyHandler.GetRegisteredBootTime (string path) inline static private
Definition at line 277 of file KeyHandler.cs.
        {
            if (!File.Exists(path))
            {
                return -1L;
            }
            string text = null;
            try
            {
                using (StreamReader streamReader = new StreamReader(path, Encoding.ASCII))
                {
                    text = streamReader.ReadLine();
                }
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine("While reading registry data at {0}: {1}", path, ex);
            }
            if (text == null)
            {
                return -1L;
            }
            long num;
            if (!long.TryParse(text, out num))
            {
                return -1L;
            }
            return num;
        }
References System.Text.Encoding.ASCII, System.Console.Error, System.IO.File.Exists(), System.L, System.IO.StreamReader.ReadLine(), System.text, and System.IO.TextWriter.WriteLine().
Referenced by Microsoft.Win32.KeyHandler.CleanVolatileKeys().