Terraria Decompiled: Microsoft.Win32.KeyHandler.RemoveValue
RemoveValue()
void Microsoft.Win32.KeyHandler.RemoveValue (string name) inline
Definition at line 821 of file KeyHandler.cs.
        {
            this.AssertNotMarkedForDeletion();
            Hashtable hashtable = this.values;
            lock (hashtable)
            {
                this.values.Remove(name);
            }
            this.SetDirty();
        }
References Microsoft.Win32.KeyHandler.AssertNotMarkedForDeletion(), System.Collections.Hashtable.Remove(), Microsoft.Win32.KeyHandler.SetDirty(), and Microsoft.Win32.KeyHandler.values.
Referenced by Microsoft.Win32.UnixRegistryApi.DeleteValue().