Terraria Decompiled: Microsoft.Win32.KeyHandler.Delete
Delete()
static bool Microsoft.Win32.KeyHandler.Delete (string dir) inline static
Definition at line 489 of file KeyHandler.cs.
        {
            if (!Directory.Exists(dir))
            {
                string volatileDir = KeyHandler.GetVolatileDir(dir);
                if (!Directory.Exists(volatileDir))
                {
                    return false;
                }
                dir = volatileDir;
            }
            Directory.Delete(dir, true);
            KeyHandler.Drop(dir);
            return true;
        }
References System.IO.Directory.Delete(), Microsoft.Win32.KeyHandler.Drop(), System.IO.Directory.Exists(), and Microsoft.Win32.KeyHandler.GetVolatileDir().
Referenced by Microsoft.Win32.UnixRegistryApi.DeleteKey().