Terraria Decompiled: Microsoft.Xna.Framework.Content.ContentTypeReaderManager.LoadAssetReaders
LoadAssetReaders()
ContentTypeReader[] Microsoft.Xna.Framework.Content.ContentTypeReaderManager.LoadAssetReaders (ContentReader reader) inline package
Definition at line 40 of file ContentTypeReaderManager.cs.
        {
            if (ContentTypeReaderManager.falseflag)
            {
                new ByteReader();
                new SByteReader();
                new DateTimeReader();
                new DecimalReader();
                new BoundingSphereReader();
                new BoundingFrustumReader();
                new RayReader();
                new ListReader<char>();
                new ListReader<Rectangle>();
                new ArrayReader<Rectangle>();
                new ListReader<Vector3>();
                new ListReader<StringReader>();
                new ListReader<int>();
                new SpriteFontReader();
                new Texture2DReader();
                new CharReader();
                new RectangleReader();
                new StringReader();
                new Vector2Reader();
                new Vector3Reader();
                new Vector4Reader();
                new CurveReader();
                new IndexBufferReader();
                new BoundingBoxReader();
                new MatrixReader();
                new BasicEffectReader();
                new VertexBufferReader();
                new AlphaTestEffectReader();
                new EnumReader<SpriteEffects>();
                new ArrayReader<float>();
                new ArrayReader<Vector2>();
                new ListReader<Vector2>();
                new ArrayReader<Matrix>();
                new EnumReader<Blend>();
                new NullableReader<Rectangle>();
                new EffectMaterialReader();
                new ExternalReferenceReader();
                new SoundEffectReader();
                new SongReader();
                new ModelReader();
                new Int32Reader();
            }
            int num = reader.Read7BitEncodedInt();
            ContentTypeReader[] array = new ContentTypeReader[num];
            BitArray bitArray = new BitArray(num);
            this.contentReaders = new Dictionary<Type, ContentTypeReader>(num);
            object obj = ContentTypeReaderManager.locker;
            lock (obj)
            {
                for (int i = 0; i < num; i++)
                {
                    string text = reader.ReadString();
                    Func<ContentTypeReader> func;
                    if (ContentTypeReaderManager.typeCreators.TryGetValue(text, out func))
                    {
                        array[i] = func();
                        bitArray[i] = true;
                    }
                    else
                    {
                        string text2 = text;
                        text2 = ContentTypeReaderManager.PrepareType(text2);
                        Type type = Type.GetType(text2);
                        if (!(type != null))
{
                            throw new ContentLoadException(string.Concat(new string[] { "Could not find ContentTypeReader Type. Please ensure the name of the Assembly that contains the Type matches the assembly in the full type name: ", text, " (", text2, ")" }));
                        }
                        ContentTypeReader contentTypeReader;
                        if (!ContentTypeReaderManager.contentReadersCache.TryGetValue(type, out contentTypeReader))
{
                            try
{
                                contentTypeReader = type.GetDefaultConstructor().Invoke(null) as ContentTypeReader;
                            }
                            catch (TargetInvocationException ex)
{
                                throw new InvalidOperationException("Failed to get default constructor for ContentTypeReader. To work around, add a creation function to ContentTypeReaderManager.AddTypeCreator() with the following failed type string: " + text, ex);
                            }
                            catch (NullReferenceException ex2)
{
                                throw new InvalidOperationException("Failed to get default constructor for ContentTypeReader. If you're using .NET Native AOT, ensure your rd.xml contains the following type: " + text, ex2);
                            }
                            bitArray[i] = true;
                            ContentTypeReaderManager.contentReadersCache.Add(type, contentTypeReader);
                        }
                        array[i] = contentTypeReader;
                    }
                    if (array[i].TargetType != null)
                    {
                        this.contentReaders.Add(array[i].TargetType, array[i]);
                    }
                    reader.ReadInt32();
                }
                for (int j = 0; j < array.Length; j++)
                {
                    if (bitArray.Get(j))
                    {
                        array[j].Initialize(this);
                    }
                }
            }
            return array;
        }
References System.array, Microsoft.Xna.Framework.Content.ContentTypeReaderManager.contentReaders, Microsoft.Xna.Framework.Content.ContentTypeReaderManager.contentReadersCache, Microsoft.Xna.Framework.Content.ContentTypeReaderManager.falseflag, System.Collections.BitArray.Get(), System.Type.GetType(), System.Type.Invoke(), Microsoft.Xna.Framework.Content.ContentTypeReaderManager.locker, System.obj, Microsoft.Xna.Framework.Content.ContentTypeReaderManager.PrepareType(), Microsoft.Xna.Framework.Content.ContentReader.Read7BitEncodedInt(), System.IO.BinaryReader.ReadInt32(), System.IO.BinaryReader.ReadString(), System.text, and Microsoft.Xna.Framework.Content.ContentTypeReaderManager.typeCreators.
Referenced by Microsoft.Xna.Framework.Content.ContentReader.InitializeTypeReaders().