Terraria Decompiled: Microsoft.Xna.Framework.Content.ContentTypeReaderManager.GetTypeReader
GetTypeReader()
ContentTypeReader Microsoft.Xna.Framework.Content.ContentTypeReaderManager.GetTypeReader (Type targetType) inline
Definition at line 24 of file ContentTypeReaderManager.cs.
        {
            ContentTypeReader contentTypeReader;
            if (this.contentReaders.TryGetValue(targetType, out contentTypeReader))
            {
                return contentTypeReader;
            }
            Type type = Type.GetType(ContentTypeReaderManager.PrepareType(targetType.FullName), false);
            if (type != null && this.contentReaders.TryGetValue(type, out contentTypeReader))
            {
                return contentTypeReader;
            }
            return null;
        }
References Microsoft.Xna.Framework.Content.ContentTypeReaderManager.contentReaders, System.Type.FullName, System.Type.GetType(), and Microsoft.Xna.Framework.Content.ContentTypeReaderManager.PrepareType().
Referenced by Microsoft.Xna.Framework.Content.ReflectiveReader< T >.GetElementReader(), Microsoft.Xna.Framework.Content.ArrayReader< T >.Initialize(), Microsoft.Xna.Framework.Content.DictionaryReader< TKey, TValue >.Initialize(), Microsoft.Xna.Framework.Content.EnumReader< T >.Initialize(), Microsoft.Xna.Framework.Content.ListReader< T >.Initialize(), Microsoft.Xna.Framework.Content.NullableReader< T >.Initialize(), and Microsoft.Xna.Framework.Content.ReflectiveReader< T >.Initialize().