Terraria Decompiled: System.Resources.FileBasedResourceGroveler.FindResourceFile
FindResourceFile()
string System.Resources.FileBasedResourceGroveler.FindResourceFile (CultureInfo culture, string fileName) inline private
Definition at line 67 of file FileBasedResourceGroveler.cs.
        {
            if (this._mediator.ModuleDir != null)
            {
                string text = Path.Combine(this._mediator.ModuleDir, fileName);
                if (File.Exists(text))
                {
                    return text;
                }
            }
            if (File.Exists(fileName))
            {
                return fileName;
            }
            return null;
        }
References System.Resources.FileBasedResourceGroveler._mediator, System.IO.Path.Combine(), System.IO.File.Exists(), and System.text.
Referenced by System.Resources.FileBasedResourceGroveler.GrovelForResourceSet(), and System.Resources.FileBasedResourceGroveler.HasNeutralResources().