Terraria Decompiled: System.Resources.FileBasedResourceGroveler.GrovelForResourceSet
GrovelForResourceSet()
ResourceSet System.Resources.FileBasedResourceGroveler.GrovelForResourceSet (CultureInfo culture, Dictionary< string, ResourceSet > localResourceSets, bool tryParents, bool createIfNotExists, ref StackCrawlMark stackMark) inline
Implements System.Resources.IResourceGroveler.
Definition at line 21 of file FileBasedResourceGroveler.cs.
        {
            ResourceSet resourceSet = null;
            string resourceFileName = this._mediator.GetResourceFileName(culture);
            string text = this.FindResourceFile(culture, resourceFileName);
            if (text == null)
            {
                if (tryParents && culture.HasInvariantCultureName)
                {
                    throw new MissingManifestResourceException(string.Concat(new string[]
                    {
                        Environment.GetResourceString("Could not find any resources appropriate for the specified culture (or the neutral culture) on disk."),
                        Environment.NewLine,
                        "baseName: ",
                        this._mediator.BaseNameField,
                        "  locationInfo: ",
                        (this._mediator.LocationInfo == null) ? "<null>" : this._mediator.LocationInfo.FullName,
                        "  fileName: ",
                        this._mediator.GetResourceFileName(culture)
                    }));
                }
            }
            else
            {
                resourceSet = this.CreateResourceSet(text);
            }
            return resourceSet;
        }
References System.Resources.FileBasedResourceGroveler._mediator, System.Resources.FileBasedResourceGroveler.CreateResourceSet(), System.culture, System.Resources.FileBasedResourceGroveler.FindResourceFile(), System.Resources.ResourceManager.GetResourceFileName(), System.Environment.GetResourceString(), and System.text.