Terraria Decompiled: System.Resources.FileBasedResourceGroveler.CreateResourceSet
CreateResourceSet()
ResourceSet System.Resources.FileBasedResourceGroveler.CreateResourceSet (string file) inline private
Definition at line 86 of file FileBasedResourceGroveler.cs.
        {
            if (this._mediator.UserResourceSet == null)
            {
                return new RuntimeResourceSet(file);
            }
            object[] array = new object[] { file };
            ResourceSet resourceSet;
            try
            {
                resourceSet = (ResourceSet)Activator.CreateInstance(this._mediator.UserResourceSet, array);
            }
            catch (MissingMethodException ex)
            {
                throw new InvalidOperationException(Environment.GetResourceString("'{0}': ResourceSet derived classes must provide a constructor that takes a String file name and a constructor that takes a Stream.", new object[] { this._mediator.UserResourceSet.AssemblyQualifiedName }), ex);
            }
            return resourceSet;
        }
References System.Resources.FileBasedResourceGroveler._mediator, System.array, System.Activator.CreateInstance(), and System.Environment.GetResourceString().
Referenced by System.Resources.FileBasedResourceGroveler.GrovelForResourceSet().