Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.Halls.StairwellDungeonHall.GenerateHallway
GenerateHallway()
void Terraria.GameContent.Generation.Dungeon.Halls.StairwellDungeonHall.GenerateHallway (DungeonData data, Vector2D startPoint, Vector2D endPoint, List< DungeonRoom > roomsInArea, bool crackedBricks, bool generating) inline private
Definition at line 100 of file StairwellDungeonHall.cs.
        {
            ushort brickTileType = this.settings.StyleData.BrickTileType;
            ushort brickCrackedTileType = this.settings.StyleData.BrickCrackedTileType;
            ushort brickWallType = this.settings.StyleData.BrickWallType;
            StairwellDungeonHallSettings stairwellDungeonHallSettings = (StairwellDungeonHallSettings)this.settings;
            int innerBoundsSize = stairwellDungeonHallSettings.InnerBoundsSize;
            int outerBoundsSize = stairwellDungeonHallSettings.OuterBoundsSize;
            int num = innerBoundsSize + outerBoundsSize;
            Vector2D vector2D = endPoint - startPoint;
            double num2 = Math.Ceiling(Math.Max(Math.Abs(vector2D.X), Math.Abs(vector2D.Y)));
            int num3 = 0;
            while ((double)num3 < num2)
            {
                Vector2D vector2D2 = startPoint + vector2D * ((double)num3 / num2);
                if (!base.Processed)
                {
                    data.dungeonBounds.UpdateBounds((int)vector2D2.X - num, (int)vector2D2.Y - num, (int)vector2D2.Y + num, (int)vector2D2.Y + num);
                    this.Bounds.UpdateBounds((int)vector2D2.X - num, (int)vector2D2.Y - num, (int)vector2D2.Y + num, (int)vector2D2.Y + num);
                }
                if (generating)
                {
                    base.GenerateDungeonSquareHall(data, roomsInArea, vector2D2, brickTileType, brickCrackedTileType, brickWallType, innerBoundsSize, outerBoundsSize, stairwellDungeonHallSettings.PlaceOverProtectedBricks, crackedBricks, stairwellDungeonHallSettings.IsEntranceHall);
                }
                num3++;
            }
        }
References System.Math.Abs(), Terraria.GameContent.Generation.Dungeon.Halls.DungeonHall.Bounds, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.BrickCrackedTileType, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.BrickTileType, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.BrickWallType, System.Math.Ceiling(), Terraria.GameContent.Generation.Dungeon.DungeonData.dungeonBounds, Terraria.GameContent.Generation.Dungeon.Halls.StairwellDungeonHallSettings.InnerBoundsSize, Terraria.GameContent.Generation.Dungeon.Halls.StairwellDungeonHallSettings.IsEntranceHall, System.Math.Max(), Terraria.GameContent.Generation.Dungeon.Halls.StairwellDungeonHallSettings.OuterBoundsSize, Terraria.GameContent.Generation.Dungeon.Halls.DungeonHallSettings.PlaceOverProtectedBricks, Terraria.GameContent.Generation.Dungeon.Halls.DungeonHall.settings, Terraria.GameContent.Generation.Dungeon.Halls.DungeonHallSettings.StyleData, Terraria.GameContent.Generation.Dungeon.DungeonBounds.UpdateBounds(), ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.GameContent.Generation.Dungeon.Halls.StairwellDungeonHall.Stairwell().