Terraria Decompiled: Microsoft.Win32.Win32RegistryApi.GetValueNames
GetValueNames()
unsafe string[] Microsoft.Win32.Win32RegistryApi.GetValueNames (RegistryKey rkey) inline
Implements Microsoft.Win32.IRegistryApi.
Definition at line 504 of file Win32RegistryApi.cs.
        {
            int num = this.ValueCount(rkey);
            string[] array = new string[num];
            if (num > 0)
            {
                IntPtr handle = this.GetHandle(rkey);
                char[] array2 = new char[16384];
                fixed (char* ptr = &array2[0])
                {
                    char* ptr2 = ptr;
                    for (int i = 0; i < num; i++)
                    {
                        int num2 = array2.Length;
                        int num3 = Win32RegistryApi.RegEnumValue(handle, i, ptr2, ref num2, IntPtr.Zero, null, null, null);
                        if (num3 != 0 && num3 != 234)
{
                            this.GenerateException(num3);
                        }
                        array[i] = new string(ptr2);
                    }
                }
            }
            return array;
        }
References System.array, Microsoft.Win32.Win32RegistryApi.GenerateException(), Microsoft.Win32.Win32RegistryApi.GetHandle(), Microsoft.Win32.Win32RegistryApi.RegEnumValue(), Microsoft.Win32.Win32RegistryApi.ValueCount(), and System.IntPtr.Zero.