Terraria Decompiled: Microsoft.Win32.Win32RegistryApi.SetValue
SetValue() [1/2]
void Microsoft.Win32.Win32RegistryApi.SetValue (RegistryKey rkey, string name, object value) inline
Implements Microsoft.Win32.IRegistryApi.
Definition at line 266 of file Win32RegistryApi.cs.
        {
            Type type = value.GetType();
            IntPtr handle = this.GetHandle(rkey);
            int num2;
            if (type == typeof(int))
            {
                int num = (int)value;
                num2 = Win32RegistryApi.RegSetValueEx(handle, name, IntPtr.Zero, RegistryValueKind.DWord, ref num, 4);
            }
            else if (type == typeof(byte[]))
            {
                byte[] array = (byte[])value;
                num2 = Win32RegistryApi.RegSetValueEx(handle, name, IntPtr.Zero, RegistryValueKind.Binary, array, array.Length);
            }
            else if (type == typeof(string[]))
            {
                string[] array2 = (string[])value;
                StringBuilder stringBuilder = new StringBuilder();
                foreach (string text in array2)
                {
                    stringBuilder.Append(text);
                    stringBuilder.Append('\0');
                }
                stringBuilder.Append('\0');
                byte[] bytes = Encoding.Unicode.GetBytes(stringBuilder.ToString());
                num2 = Win32RegistryApi.RegSetValueEx(handle, name, IntPtr.Zero, RegistryValueKind.MultiString, bytes, bytes.Length);
            }
            else
            {
                if (type.IsArray)
                {
                    throw new ArgumentException("Only string and byte arrays can written as registry values");
                }
                string text2 = string.Format("{0}{1}", value, '\0');
                num2 = Win32RegistryApi.RegSetValueEx(handle, name, IntPtr.Zero, RegistryValueKind.String, text2, text2.Length * this.NativeBytesPerCharacter);
            }
            if (num2 != 0)
            {
                this.GenerateException(num2);
            }
        }
References System.array, Microsoft.Win32.Win32RegistryApi.GenerateException(), System.Text.Encoding.GetBytes(), Microsoft.Win32.Win32RegistryApi.GetHandle(), System.Type.GetType(), int, System.Type.IsArray, System.name, Microsoft.Win32.Win32RegistryApi.RegSetValueEx(), System.text, System.Text.Encoding.Unicode, System.value, and System.IntPtr.Zero.