Terraria Decompiled: Microsoft.Win32.Win32RegistryApi.Close
Close()
void Microsoft.Win32.Win32RegistryApi.Close (RegistryKey rkey) inline
Implements Microsoft.Win32.IRegistryApi.
Definition at line 389 of file Win32RegistryApi.cs.
        {
            if (!Win32RegistryApi.IsHandleValid(rkey))
            {
                return;
            }
            SafeRegistryHandle handle = rkey.Handle;
            if (handle != null)
            {
                handle.Close();
                return;
            }
            Win32RegistryApi.RegCloseKey(this.GetHandle(rkey));
        }
References System.Runtime.InteropServices.SafeHandle.Close(), Microsoft.Win32.Win32RegistryApi.GetHandle(), Microsoft.Win32.RegistryKey.Handle, Microsoft.Win32.Win32RegistryApi.IsHandleValid(), and Microsoft.Win32.Win32RegistryApi.RegCloseKey().