Terraria Decompiled: Microsoft.Win32.Win32RegistryApi.GetValue
GetValue()
object Microsoft.Win32.Win32RegistryApi.GetValue (RegistryKey rkey, string name, object defaultValue, RegistryValueOptions options) inline
Implements Microsoft.Win32.IRegistryApi.
Definition at line 111 of file Win32RegistryApi.cs.
        {
            RegistryValueKind registryValueKind = RegistryValueKind.Unknown;
            int num = 0;
            IntPtr handle = this.GetHandle(rkey);
            int num2 = Win32RegistryApi.RegQueryValueEx(handle, name, IntPtr.Zero, ref registryValueKind, IntPtr.Zero, ref num);
            if (num2 == 2 || num2 == 1018)
            {
                return defaultValue;
            }
            if (num2 != 234 && num2 != 0)
            {
                this.GenerateException(num2);
            }
            object obj;
            if (registryValueKind == RegistryValueKind.String)
            {
                byte[] array;
                num2 = this.GetBinaryValue(rkey, name, registryValueKind, out array, num);
                obj = RegistryKey.DecodeString(array);
            }
            else if (registryValueKind == RegistryValueKind.ExpandString)
            {
                byte[] array2;
                num2 = this.GetBinaryValue(rkey, name, registryValueKind, out array2, num);
                obj = RegistryKey.DecodeString(array2);
                if ((options & RegistryValueOptions.DoNotExpandEnvironmentNames) == RegistryValueOptions.None)
                {
                    obj = Environment.ExpandEnvironmentVariables((string)obj);
                }
            }
            else if (registryValueKind == RegistryValueKind.DWord)
            {
                int num3 = 0;
                num2 = Win32RegistryApi.RegQueryValueEx(handle, name, IntPtr.Zero, ref registryValueKind, ref num3, ref num);
                obj = num3;
            }
            else if (registryValueKind == RegistryValueKind.QWord)
            {
                long num4 = 0L;
                num2 = Win32RegistryApi.RegQueryValueEx(handle, name, IntPtr.Zero, ref registryValueKind, ref num4, ref num);
                obj = num4;
            }
            else if (registryValueKind == RegistryValueKind.Binary)
            {
                byte[] array3;
                num2 = this.GetBinaryValue(rkey, name, registryValueKind, out array3, num);
                obj = array3;
            }
            else
            {
                if (registryValueKind != RegistryValueKind.MultiString)
                {
                    throw new SystemException();
                }
                obj = null;
                byte[] array4;
                num2 = this.GetBinaryValue(rkey, name, registryValueKind, out array4, num);
                if (num2 == 0)
                {
                    obj = RegistryKey.DecodeString(array4).Split('\0', StringSplitOptions.None);
                }
            }
            if (num2 != 0)
            {
                this.GenerateException(num2);
            }
            return obj;
        }
References System.array, Microsoft.Win32.RegistryKey.DecodeString(), Microsoft.Win32.Win32RegistryApi.GenerateException(), Microsoft.Win32.Win32RegistryApi.GetBinaryValue(), Microsoft.Win32.Win32RegistryApi.GetHandle(), System.L, System.name, System.obj, System.options, Microsoft.Win32.Win32RegistryApi.RegQueryValueEx(), and System.IntPtr.Zero.