Terraria Decompiled: Microsoft.Win32.Win32RegistryApi.CreateSubKey
CreateSubKey() [1/2]
RegistryKey Microsoft.Win32.Win32RegistryApi.CreateSubKey (RegistryKey rkey, string keyName) inline
Implements Microsoft.Win32.IRegistryApi.
Definition at line 411 of file Win32RegistryApi.cs.
        {
            IntPtr intPtr;
            int num2;
            int num = Win32RegistryApi.RegCreateKeyEx(this.GetHandle(rkey), keyName, 0, IntPtr.Zero, 0, 131103, IntPtr.Zero, out intPtr, out num2);
            if (num != 0)
            {
                this.GenerateException(num);
            }
            return new RegistryKey(intPtr, Win32RegistryApi.CombineName(rkey, keyName), true);
        }
References Microsoft.Win32.Win32RegistryApi.CombineName(), Microsoft.Win32.Win32RegistryApi.GenerateException(), Microsoft.Win32.Win32RegistryApi.GetHandle(), Microsoft.Win32.Win32RegistryApi.RegCreateKeyEx(), and System.IntPtr.Zero.