Terraria Decompiled: Microsoft.Win32.Win32RegistryApi.SetValue
SetValue() [2/2]
void Microsoft.Win32.Win32RegistryApi.SetValue (RegistryKey rkey, string name, object value, RegistryValueKind valueKind) inline
Implements Microsoft.Win32.IRegistryApi.
Definition at line 182 of file Win32RegistryApi.cs.
        {
            Type type = value.GetType();
            IntPtr handle = this.GetHandle(rkey);
            switch (valueKind)
            {
            case RegistryValueKind.String:
            case RegistryValueKind.ExpandString:
                if (type == typeof(string))
                {
                    string text = string.Format("{0}{1}", value, '\0');
                    this.CheckResult(Win32RegistryApi.RegSetValueEx(handle, name, IntPtr.Zero, valueKind, text, text.Length * this.NativeBytesPerCharacter));
                    return;
                }
                goto IL_01B7;
            case RegistryValueKind.Binary:
                goto IL_009C;
            case RegistryValueKind.DWord:
                break;
            case (RegistryValueKind)5:
            case (RegistryValueKind)6:
            case (RegistryValueKind)8:
            case (RegistryValueKind)9:
            case (RegistryValueKind)10:
                goto IL_01A4;
            case RegistryValueKind.MultiString:
                if (type == typeof(string[]))
                {
                    string[] array = (string[])value;
                    StringBuilder stringBuilder = new StringBuilder();
                    foreach (string text2 in array)
                    {
                        stringBuilder.Append(text2);
                        stringBuilder.Append('\0');
                    }
                    stringBuilder.Append('\0');
                    byte[] bytes = Encoding.Unicode.GetBytes(stringBuilder.ToString());
                    this.CheckResult(Win32RegistryApi.RegSetValueEx(handle, name, IntPtr.Zero, RegistryValueKind.MultiString, bytes, bytes.Length));
                    return;
                }
                goto IL_01B7;
            case RegistryValueKind.QWord:
                try
                {
                    long num = Convert.ToInt64(value);
                    this.CheckResult(Win32RegistryApi.RegSetValueEx(handle, name, IntPtr.Zero, RegistryValueKind.QWord, ref num, 8));
                    return;
                }
                catch (OverflowException)
                {
                    goto IL_01B7;
                }
                break;
            default:
                goto IL_01A4;
            }
            try
            {
                int num2 = Convert.ToInt32(value);
                this.CheckResult(Win32RegistryApi.RegSetValueEx(handle, name, IntPtr.Zero, RegistryValueKind.DWord, ref num2, 4));
                return;
            }
            catch (OverflowException)
            {
                goto IL_01B7;
            }
            IL_009C:
            if (type == typeof(byte[]))
            {
                byte[] array3 = (byte[])value;
                this.CheckResult(Win32RegistryApi.RegSetValueEx(handle, name, IntPtr.Zero, RegistryValueKind.Binary, array3, array3.Length));
                return;
            }
            goto IL_01B7;
            IL_01A4:
            if (type.IsArray)
            {
                throw new ArgumentException("Only string and byte arrays can written as registry values");
            }
            IL_01B7:
            throw new ArgumentException("Type does not match the valueKind");
        }
References System.array, Microsoft.Win32.Win32RegistryApi.CheckResult(), System.Text.Encoding.GetBytes(), Microsoft.Win32.Win32RegistryApi.GetHandle(), System.Type.GetType(), System.Type.IsArray, System.name, Microsoft.Win32.Win32RegistryApi.RegSetValueEx(), System.text, System.Convert.ToInt32(), System.Convert.ToInt64(), System.Text.Encoding.Unicode, System.value, and System.IntPtr.Zero.