Terraria Decompiled: Microsoft.Win32.Win32RegistryApi.ValueCount
ValueCount()
int Microsoft.Win32.Win32RegistryApi.ValueCount (RegistryKey rkey) inline
Implements Microsoft.Win32.IRegistryApi.
Definition at line 332 of file Win32RegistryApi.cs.
        {
            int num = 0;
            int num2 = 0;
            int num3 = Win32RegistryApi.RegQueryInfoKey(this.GetHandle(rkey), null, null, IntPtr.Zero, ref num2, null, null, ref num, null, null, null, null);
            if (num3 != 0)
            {
                this.GenerateException(num3);
            }
            return num;
        }
References Microsoft.Win32.Win32RegistryApi.GenerateException(), Microsoft.Win32.Win32RegistryApi.GetHandle(), Microsoft.Win32.Win32RegistryApi.RegQueryInfoKey(), and System.IntPtr.Zero.
Referenced by Microsoft.Win32.Win32RegistryApi.GetValueNames().