Terraria Decompiled: Microsoft.Win32.Win32RegistryApi.DeleteValue
DeleteValue()
void Microsoft.Win32.Win32RegistryApi.DeleteValue (RegistryKey rkey, string value, bool shouldThrowWhenKeyMissing) inline
Implements Microsoft.Win32.IRegistryApi.
Definition at line 455 of file Win32RegistryApi.cs.
        {
            int num = Win32RegistryApi.RegDeleteValue(this.GetHandle(rkey), value);
            if (num == 1018)
            {
                return;
            }
            if (num != 2)
            {
                if (num != 0)
                {
                    this.GenerateException(num);
                }
                return;
            }
            if (shouldThrowWhenKeyMissing)
            {
                throw new ArgumentException("value " + value);
            }
        }
References Microsoft.Win32.Win32RegistryApi.GenerateException(), Microsoft.Win32.Win32RegistryApi.GetHandle(), Microsoft.Win32.Win32RegistryApi.RegDeleteValue(), and System.value.