Terraria Decompiled: Newtonsoft.Json.Bson.BsonWriter.AddToken
AddToken()
void Newtonsoft.Json.Bson.BsonWriter.AddToken (BsonToken token) inline package
Definition at line 139 of file BsonWriter.cs.
        {
            if (this._parent != null)
            {
                BsonObject bsonObject = this._parent as BsonObject;
                if (bsonObject != null)
                {
                    bsonObject.Add(this._propertyName, token);
                    this._propertyName = null;
                    return;
                }
                ((BsonArray)this._parent).Add(token);
                return;
            }
            else
            {
                if (token.Type != BsonType.Object && token.Type != BsonType.Array)
                {
                    throw JsonWriterException.Create(this, "Error writing {0} value. BSON must start with an Object or Array.".FormatWith(CultureInfo.InvariantCulture, token.Type), null);
                }
                this._parent = token;
                this._root = token;
                return;
            }
        }
References Newtonsoft.Json.Bson.BsonWriter._parent, Newtonsoft.Json.Bson.BsonWriter._propertyName, Newtonsoft.Json.Bson.BsonObject.Add(), Newtonsoft.Json.JsonWriterException.Create(), System.Globalization.CultureInfo.InvariantCulture, and Newtonsoft.Json.Bson.BsonToken.Type.
Referenced by Newtonsoft.Json.Bson.BsonWriter.AddParent(), Newtonsoft.Json.Bson.BsonWriter.AddValue(), Newtonsoft.Json.Bson.BsonWriter.WriteNull(), Newtonsoft.Json.Bson.BsonWriter.WriteRegex(), Newtonsoft.Json.Bson.BsonWriter.WriteUndefined(), Newtonsoft.Json.Bson.BsonWriter.WriteValue(), Newtonsoft.Json.Bson.BsonWriter.WriteValue(), Newtonsoft.Json.Bson.BsonWriter.WriteValue(), Newtonsoft.Json.Bson.BsonWriter.WriteValue(), Newtonsoft.Json.Bson.BsonWriter.WriteValue(), Newtonsoft.Json.Bson.BsonWriter.WriteValue(), Newtonsoft.Json.Bson.BsonWriter.WriteValue(), and Newtonsoft.Json.Bson.BsonWriter.WriteValue().