Terraria Decompiled: Mono.Security.Cryptography.CryptoConvert.GetParametersFromCapiPublicKeyBlob
GetParametersFromCapiPublicKeyBlob()
static RSAParameters Mono.Security.Cryptography.CryptoConvert.GetParametersFromCapiPublicKeyBlob (byte[] blob, int offset) inline static private
Definition at line 408 of file CryptoConvert.cs.
        {
            if (blob == null)
            {
                throw new ArgumentNullException("blob");
            }
            if (offset >= blob.Length)
            {
                throw new ArgumentException("blob is too small.");
            }
            RSAParameters rsaparameters2;
            try
            {
                if (blob[offset] != 6 || blob[offset + 1] != 2 || blob[offset + 2] != 0 || blob[offset + 3] != 0 || CryptoConvert.ToUInt32LE(blob, offset + 8) != 826364754U)
                {
                    throw new CryptographicException("Invalid blob header");
                }
                int num = CryptoConvert.ToInt32LE(blob, offset + 12);
                RSAParameters rsaparameters = new RSAParameters
                {
                    Exponent = new byte[3]
                };
                rsaparameters.Exponent[0] = blob[offset + 18];
                rsaparameters.Exponent[1] = blob[offset + 17];
                rsaparameters.Exponent[2] = blob[offset + 16];
                int num2 = offset + 20;
                int num3 = num >> 3;
                rsaparameters.Modulus = new byte[num3];
                Buffer.BlockCopy(blob, num2, rsaparameters.Modulus, 0, num3);
                Array.Reverse<byte>(rsaparameters.Modulus);
                rsaparameters2 = rsaparameters;
            }
            catch (Exception ex)
            {
                throw new CryptographicException("Invalid blob.", ex);
            }
            return rsaparameters2;
        }
References System.Buffer.BlockCopy(), System.Security.Cryptography.RSAParameters.Exponent, System.Security.Cryptography.RSAParameters.Modulus, System.offset, System.Array.Reverse(), Mono.Security.Cryptography.CryptoConvert.ToInt32LE(), Mono.Security.Cryptography.CryptoConvert.ToUInt32LE(), and System.U.
Referenced by Mono.Security.Cryptography.CryptoConvert.FromCapiPublicKeyBlob(), and Mono.Security.Cryptography.CryptoConvert.TryImportCapiPublicKeyBlob().