Terraria Decompiled: Mono.Security.Cryptography.CryptoConvert.ToCapiPublicKeyBlob
ToCapiPublicKeyBlob() [1/2]
static byte[] Mono.Security.Cryptography.CryptoConvert.ToCapiPublicKeyBlob (DSA dsa) inline static
Definition at line 542 of file CryptoConvert.cs.
        {
            DSAParameters dsaparameters = dsa.ExportParameters(false);
            int num = dsaparameters.P.Length;
            byte[] array = new byte[16 + num + 20 + num + num + 4 + 20];
            array[0] = 6;
            array[1] = 2;
            array[5] = 34;
            array[8] = 68;
            array[9] = 83;
            array[10] = 83;
            array[11] = 49;
            byte[] bytesLE = CryptoConvert.GetBytesLE(num << 3);
            array[12] = bytesLE[0];
            array[13] = bytesLE[1];
            array[14] = bytesLE[2];
            array[15] = bytesLE[3];
            int num2 = 16;
            byte[] p = dsaparameters.P;
            Array.Reverse<byte>(p);
            Buffer.BlockCopy(p, 0, array, num2, num);
            num2 += num;
            byte[] q = dsaparameters.Q;
            Array.Reverse<byte>(q);
            Buffer.BlockCopy(q, 0, array, num2, 20);
            num2 += 20;
            byte[] g = dsaparameters.G;
            Array.Reverse<byte>(g);
            Buffer.BlockCopy(g, 0, array, num2, num);
            num2 += num;
            byte[] y = dsaparameters.Y;
            Array.Reverse<byte>(y);
            Buffer.BlockCopy(y, 0, array, num2, num);
            num2 += num;
            Buffer.BlockCopy(CryptoConvert.GetBytesLE(dsaparameters.Counter), 0, array, num2, 4);
            num2 += 4;
            byte[] seed = dsaparameters.Seed;
            Array.Reverse<byte>(seed);
            Buffer.BlockCopy(seed, 0, array, num2, 20);
            return array;
        }
References System.array, System.Buffer.BlockCopy(), System.Security.Cryptography.DSAParameters.Counter, System.Security.Cryptography.DSA.ExportParameters(), System.Security.Cryptography.DSAParameters.G, Mono.Security.Cryptography.CryptoConvert.GetBytesLE(), System.Security.Cryptography.DSAParameters.P, System.Security.Cryptography.DSAParameters.Q, System.Array.Reverse(), System.Security.Cryptography.DSAParameters.Seed, and System.Security.Cryptography.DSAParameters.Y.