Terraria Decompiled: Mono.Security.Cryptography.CryptoConvert.FromCapiPrivateKeyBlobDSA
FromCapiPrivateKeyBlobDSA() [2/2]
static DSA Mono.Security.Cryptography.CryptoConvert.FromCapiPrivateKeyBlobDSA (byte[] blob, int offset) inline static
Definition at line 179 of file CryptoConvert.cs.
        {
            if (blob == null)
            {
                throw new ArgumentNullException("blob");
            }
            if (offset >= blob.Length)
            {
                throw new ArgumentException("blob is too small.");
            }
            DSAParameters dsaparameters = default(DSAParameters);
            try
            {
                if (blob[offset] != 7 || blob[offset + 1] != 2 || blob[offset + 2] != 0 || blob[offset + 3] != 0 || CryptoConvert.ToUInt32LE(blob, offset + 8) != 844321604U)
                {
                    throw new CryptographicException("Invalid blob header");
                }
                int num = CryptoConvert.ToInt32LE(blob, offset + 12) >> 3;
                int num2 = offset + 16;
                dsaparameters.P = new byte[num];
                Buffer.BlockCopy(blob, num2, dsaparameters.P, 0, num);
                Array.Reverse<byte>(dsaparameters.P);
                num2 += num;
                dsaparameters.Q = new byte[20];
                Buffer.BlockCopy(blob, num2, dsaparameters.Q, 0, 20);
                Array.Reverse<byte>(dsaparameters.Q);
                num2 += 20;
                dsaparameters.G = new byte[num];
                Buffer.BlockCopy(blob, num2, dsaparameters.G, 0, num);
                Array.Reverse<byte>(dsaparameters.G);
                num2 += num;
                dsaparameters.X = new byte[20];
                Buffer.BlockCopy(blob, num2, dsaparameters.X, 0, 20);
                Array.Reverse<byte>(dsaparameters.X);
                num2 += 20;
                dsaparameters.Counter = CryptoConvert.ToInt32LE(blob, num2);
                num2 += 4;
                dsaparameters.Seed = new byte[20];
                Buffer.BlockCopy(blob, num2, dsaparameters.Seed, 0, 20);
                Array.Reverse<byte>(dsaparameters.Seed);
                num2 += 20;
            }
            catch (Exception ex)
            {
                throw new CryptographicException("Invalid blob.", ex);
            }
            DSA dsa = null;
            try
            {
                dsa = DSA.Create();
                dsa.ImportParameters(dsaparameters);
            }
            catch (CryptographicException ex2)
            {
                try
                {
                    dsa = new DSACryptoServiceProvider(new CspParameters
                    {
                        Flags = CspProviderFlags.UseMachineKeyStore
                    });
                    dsa.ImportParameters(dsaparameters);
                }
                catch
                {
                    throw ex2;
                }
            }
            return dsa;
        }
References System.Buffer.BlockCopy(), System.Security.Cryptography.DSA.Create(), System.Security.Cryptography.DSAParameters.G, System.Security.Cryptography.DSA.ImportParameters(), System.offset, System.Security.Cryptography.DSAParameters.P, System.Security.Cryptography.DSAParameters.Q, System.Array.Reverse(), System.Security.Cryptography.DSAParameters.Seed, Mono.Security.Cryptography.CryptoConvert.ToInt32LE(), Mono.Security.Cryptography.CryptoConvert.ToUInt32LE(), System.U, and System.Security.Cryptography.DSAParameters.X.