Terraria Decompiled: Mono.Security.Cryptography.CryptoConvert.ToCapiPublicKeyBlob
ToCapiPublicKeyBlob() [2/2]
static byte[] Mono.Security.Cryptography.CryptoConvert.ToCapiPublicKeyBlob (RSA rsa) inline static
Definition at line 509 of file CryptoConvert.cs.
        {
            RSAParameters rsaparameters = rsa.ExportParameters(false);
            int num = rsaparameters.Modulus.Length;
            byte[] array = new byte[20 + num];
            array[0] = 6;
            array[1] = 2;
            array[5] = 36;
            array[8] = 82;
            array[9] = 83;
            array[10] = 65;
            array[11] = 49;
            byte[] bytesLE = CryptoConvert.GetBytesLE(num << 3);
            array[12] = bytesLE[0];
            array[13] = bytesLE[1];
            array[14] = bytesLE[2];
            array[15] = bytesLE[3];
            int num2 = 16;
            int i = rsaparameters.Exponent.Length;
            while (i > 0)
            {
                array[num2++] = rsaparameters.Exponent[--i];
            }
            num2 = 20;
            byte[] modulus = rsaparameters.Modulus;
            int num3 = modulus.Length;
            Array.Reverse<byte>(modulus, 0, num3);
            Buffer.BlockCopy(modulus, 0, array, num2, num3);
            num2 += num3;
            return array;
        }
References System.array, System.Buffer.BlockCopy(), System.Security.Cryptography.RSAParameters.Exponent, System.Security.Cryptography.RSA.ExportParameters(), Mono.Security.Cryptography.CryptoConvert.GetBytesLE(), System.Security.Cryptography.RSAParameters.Modulus, and System.Array.Reverse().
Referenced by System.Security.Cryptography.DSACryptoServiceProvider.ExportCspBlob(), System.Security.Cryptography.RSACryptoServiceProvider.ExportCspBlob(), Mono.Security.Cryptography.CryptoConvert.ToCapiKeyBlob(), and Mono.Security.Cryptography.CryptoConvert.ToCapiKeyBlob().