Terraria Decompiled: Mono.Security.Cryptography.CryptoConvert.GetParametersFromCapiPrivateKeyBlob
GetParametersFromCapiPrivateKeyBlob()
static RSAParameters Mono.Security.Cryptography.CryptoConvert.GetParametersFromCapiPrivateKeyBlob (byte[] blob, int offset) inline static private
Definition at line 107 of file CryptoConvert.cs.
        {
            if (blob == null)
            {
                throw new ArgumentNullException("blob");
            }
            if (offset >= blob.Length)
            {
                throw new ArgumentException("blob is too small.");
            }
            RSAParameters rsaparameters = default(RSAParameters);
            RSAParameters rsaparameters2;
            try
            {
                if (blob[offset] != 7 || blob[offset + 1] != 2 || blob[offset + 2] != 0 || blob[offset + 3] != 0 || CryptoConvert.ToUInt32LE(blob, offset + 8) != 843141970U)
                {
                    throw new CryptographicException("Invalid blob header");
                }
                int num = CryptoConvert.ToInt32LE(blob, offset + 12);
                byte[] array = new byte[4];
                Buffer.BlockCopy(blob, offset + 16, array, 0, 4);
                Array.Reverse<byte>(array);
                rsaparameters.Exponent = CryptoConvert.Trim(array);
                int num2 = offset + 20;
                int num3 = num >> 3;
                rsaparameters.Modulus = new byte[num3];
                Buffer.BlockCopy(blob, num2, rsaparameters.Modulus, 0, num3);
                Array.Reverse<byte>(rsaparameters.Modulus);
                num2 += num3;
                int num4 = num3 >> 1;
                rsaparameters.P = new byte[num4];
                Buffer.BlockCopy(blob, num2, rsaparameters.P, 0, num4);
                Array.Reverse<byte>(rsaparameters.P);
                num2 += num4;
                rsaparameters.Q = new byte[num4];
                Buffer.BlockCopy(blob, num2, rsaparameters.Q, 0, num4);
                Array.Reverse<byte>(rsaparameters.Q);
                num2 += num4;
                rsaparameters.DP = new byte[num4];
                Buffer.BlockCopy(blob, num2, rsaparameters.DP, 0, num4);
                Array.Reverse<byte>(rsaparameters.DP);
                num2 += num4;
                rsaparameters.DQ = new byte[num4];
                Buffer.BlockCopy(blob, num2, rsaparameters.DQ, 0, num4);
                Array.Reverse<byte>(rsaparameters.DQ);
                num2 += num4;
                rsaparameters.InverseQ = new byte[num4];
                Buffer.BlockCopy(blob, num2, rsaparameters.InverseQ, 0, num4);
                Array.Reverse<byte>(rsaparameters.InverseQ);
                num2 += num4;
                rsaparameters.D = new byte[num3];
                if (num2 + num3 + offset <= blob.Length)
                {
                    Buffer.BlockCopy(blob, num2, rsaparameters.D, 0, num3);
                    Array.Reverse<byte>(rsaparameters.D);
                }
                rsaparameters2 = rsaparameters;
            }
            catch (Exception ex)
            {
                throw new CryptographicException("Invalid blob.", ex);
            }
            return rsaparameters2;
        }
References System.array, System.Buffer.BlockCopy(), System.Security.Cryptography.RSAParameters.D, System.Security.Cryptography.RSAParameters.DP, System.Security.Cryptography.RSAParameters.DQ, System.Security.Cryptography.RSAParameters.InverseQ, System.Security.Cryptography.RSAParameters.Modulus, System.offset, System.Security.Cryptography.RSAParameters.P, System.Security.Cryptography.RSAParameters.Q, System.Array.Reverse(), Mono.Security.Cryptography.CryptoConvert.ToInt32LE(), Mono.Security.Cryptography.CryptoConvert.ToUInt32LE(), Mono.Security.Cryptography.CryptoConvert.Trim(), and System.U.
Referenced by Mono.Security.Cryptography.CryptoConvert.FromCapiPrivateKeyBlob(), and Mono.Security.Cryptography.CryptoConvert.TryImportCapiPrivateKeyBlob().