Terraria Decompiled: Mono.Security.Cryptography.CryptoConvert.FromCapiPublicKeyBlobDSA
FromCapiPublicKeyBlobDSA() [2/2]
static DSA Mono.Security.Cryptography.CryptoConvert.FromCapiPublicKeyBlobDSA (byte[] blob, int offset) inline static
Definition at line 454 of file CryptoConvert.cs.
        {
            if (blob == null)
            {
                throw new ArgumentNullException("blob");
            }
            if (offset >= blob.Length)
            {
                throw new ArgumentException("blob is too small.");
            }
            DSA dsa2;
            try
            {
                if (blob[offset] != 6 || blob[offset + 1] != 2 || blob[offset + 2] != 0 || blob[offset + 3] != 0 || CryptoConvert.ToUInt32LE(blob, offset + 8) != 827544388U)
                {
                    throw new CryptographicException("Invalid blob header");
                }
                int num = CryptoConvert.ToInt32LE(blob, offset + 12);
                DSAParameters dsaparameters = default(DSAParameters);
                int num2 = num >> 3;
                int num3 = offset + 16;
                dsaparameters.P = new byte[num2];
                Buffer.BlockCopy(blob, num3, dsaparameters.P, 0, num2);
                Array.Reverse<byte>(dsaparameters.P);
                num3 += num2;
                dsaparameters.Q = new byte[20];
                Buffer.BlockCopy(blob, num3, dsaparameters.Q, 0, 20);
                Array.Reverse<byte>(dsaparameters.Q);
                num3 += 20;
                dsaparameters.G = new byte[num2];
                Buffer.BlockCopy(blob, num3, dsaparameters.G, 0, num2);
                Array.Reverse<byte>(dsaparameters.G);
                num3 += num2;
                dsaparameters.Y = new byte[num2];
                Buffer.BlockCopy(blob, num3, dsaparameters.Y, 0, num2);
                Array.Reverse<byte>(dsaparameters.Y);
                num3 += num2;
                dsaparameters.Counter = CryptoConvert.ToInt32LE(blob, num3);
                num3 += 4;
                dsaparameters.Seed = new byte[20];
                Buffer.BlockCopy(blob, num3, dsaparameters.Seed, 0, 20);
                Array.Reverse<byte>(dsaparameters.Seed);
                num3 += 20;
                DSA dsa = DSA.Create();
                dsa.ImportParameters(dsaparameters);
                dsa2 = dsa;
            }
            catch (Exception ex)
            {
                throw new CryptographicException("Invalid blob.", ex);
            }
            return dsa2;
        }
References System.Buffer.BlockCopy(), System.Security.Cryptography.DSA.Create(), System.Security.Cryptography.DSAParameters.G, System.Security.Cryptography.DSA.ImportParameters(), System.offset, System.Security.Cryptography.DSAParameters.P, System.Security.Cryptography.DSAParameters.Q, System.Array.Reverse(), System.Security.Cryptography.DSAParameters.Seed, Mono.Security.Cryptography.CryptoConvert.ToInt32LE(), Mono.Security.Cryptography.CryptoConvert.ToUInt32LE(), System.U, and System.Security.Cryptography.DSAParameters.Y.