Terraria Decompiled: Mono.Security.Cryptography.CryptoConvert.ToCapiPrivateKeyBlob
ToCapiPrivateKeyBlob() [2/2]
static byte[] Mono.Security.Cryptography.CryptoConvert.ToCapiPrivateKeyBlob (RSA rsa) inline static
Definition at line 250 of file CryptoConvert.cs.
        {
            RSAParameters rsaparameters = rsa.ExportParameters(true);
            int num = rsaparameters.Modulus.Length;
            byte[] array = new byte[20 + (num << 2) + (num >> 1)];
            array[0] = 7;
            array[1] = 2;
            array[5] = 36;
            array[8] = 82;
            array[9] = 83;
            array[10] = 65;
            array[11] = 50;
            byte[] bytesLE = CryptoConvert.GetBytesLE(num << 3);
            array[12] = bytesLE[0];
            array[13] = bytesLE[1];
            array[14] = bytesLE[2];
            array[15] = bytesLE[3];
            int num2 = 16;
            int i = rsaparameters.Exponent.Length;
            while (i > 0)
            {
                array[num2++] = rsaparameters.Exponent[--i];
            }
            num2 = 20;
            byte[] modulus = rsaparameters.Modulus;
            int num3 = modulus.Length;
            Array.Reverse<byte>(modulus, 0, num3);
            Buffer.BlockCopy(modulus, 0, array, num2, num3);
            num2 += num3;
            byte[] p = rsaparameters.P;
            num3 = p.Length;
            Array.Reverse<byte>(p, 0, num3);
            Buffer.BlockCopy(p, 0, array, num2, num3);
            num2 += num3;
            byte[] q = rsaparameters.Q;
            num3 = q.Length;
            Array.Reverse<byte>(q, 0, num3);
            Buffer.BlockCopy(q, 0, array, num2, num3);
            num2 += num3;
            byte[] dp = rsaparameters.DP;
            num3 = dp.Length;
            Array.Reverse<byte>(dp, 0, num3);
            Buffer.BlockCopy(dp, 0, array, num2, num3);
            num2 += num3;
            byte[] dq = rsaparameters.DQ;
            num3 = dq.Length;
            Array.Reverse<byte>(dq, 0, num3);
            Buffer.BlockCopy(dq, 0, array, num2, num3);
            num2 += num3;
            byte[] inverseQ = rsaparameters.InverseQ;
            num3 = inverseQ.Length;
            Array.Reverse<byte>(inverseQ, 0, num3);
            Buffer.BlockCopy(inverseQ, 0, array, num2, num3);
            num2 += num3;
            byte[] d = rsaparameters.D;
            num3 = d.Length;
            Array.Reverse<byte>(d, 0, num3);
            Buffer.BlockCopy(d, 0, array, num2, num3);
            return array;
        }
References System.array, System.Buffer.BlockCopy(), System.Security.Cryptography.RSAParameters.D, System.Security.Cryptography.RSAParameters.DP, System.Security.Cryptography.RSAParameters.DQ, System.Security.Cryptography.RSAParameters.Exponent, System.Security.Cryptography.RSA.ExportParameters(), Mono.Security.Cryptography.CryptoConvert.GetBytesLE(), System.Security.Cryptography.RSAParameters.InverseQ, System.Security.Cryptography.RSAParameters.Modulus, System.Security.Cryptography.RSAParameters.P, System.Security.Cryptography.RSAParameters.Q, and System.Array.Reverse().
Referenced by System.Security.Cryptography.DSACryptoServiceProvider.ExportCspBlob(), System.Security.Cryptography.RSACryptoServiceProvider.ExportCspBlob(), Mono.Security.StrongName.GetBytes(), Mono.Security.Cryptography.CryptoConvert.ToCapiKeyBlob(), and Mono.Security.Cryptography.CryptoConvert.ToCapiKeyBlob().