Terraria Decompiled: System.AppContext.TryGetSwitch
TryGetSwitch()
static bool System.AppContext.TryGetSwitch (string switchName, out bool isEnabled) inline static
Definition at line 50 of file AppContext.cs.
        {
            if (switchName == null)
            {
                throw new ArgumentNullException("switchName");
            }
            if (switchName.Length == 0)
            {
                throw new ArgumentException(Environment.GetResourceString("Empty name is not legal."), "switchName");
            }
            if (!AppContext.s_defaultsInitialized)
            {
                AppContext.InitializeDefaultSwitchValues();
            }
            isEnabled = false;
            Dictionary<string, AppContext.SwitchValueState> dictionary = AppContext.s_switchMap;
            lock (dictionary)
            {
                AppContext.SwitchValueState switchValueState;
                if (AppContext.s_switchMap.TryGetValue(switchName, out switchValueState))
                {
                    if (switchValueState == AppContext.SwitchValueState.UnknownValue)
                    {
                        isEnabled = false;
                        return false;
                    }
                    isEnabled = (switchValueState & AppContext.SwitchValueState.HasTrueValue) == AppContext.SwitchValueState.HasTrueValue;
                    if ((switchValueState & AppContext.SwitchValueState.HasLookedForOverride) == AppContext.SwitchValueState.HasLookedForOverride)
                    {
                        return true;
                    }
                    bool flag2;
                    if (AppContextDefaultValues.TryGetSwitchOverride(switchName, out flag2))
                    {
                        isEnabled = flag2;
                    }
                    AppContext.s_switchMap[switchName] = (isEnabled ? AppContext.SwitchValueState.HasTrueValue : AppContext.SwitchValueState.HasFalseValue) | AppContext.SwitchValueState.HasLookedForOverride;
                    return true;
                }
                else
                {
                    bool flag3;
                    if (AppContextDefaultValues.TryGetSwitchOverride(switchName, out flag3))
                    {
                        isEnabled = flag3;
                        AppContext.s_switchMap[switchName] = (isEnabled ? AppContext.SwitchValueState.HasTrueValue : AppContext.SwitchValueState.HasFalseValue) | AppContext.SwitchValueState.HasLookedForOverride;
                        return true;
                    }
                    AppContext.s_switchMap[switchName] = AppContext.SwitchValueState.UnknownValue;
                }
            }
            return false;
        }
References System.dictionary, System.Environment.GetResourceString(), System.AppContext.InitializeDefaultSwitchValues(), System.AppContext.s_defaultsInitialized, System.AppContext.s_switchMap, and System.AppContextDefaultValues.TryGetSwitchOverride().
Referenced by System.AppContextSwitches.AppContextSwitches(), and System.AppContextSwitches.GetCachedSwitchValueInternal().