Terraria Decompiled: Terraria.WorldGen.SecretSeed.DoSurfaceIsDesertFinish
DoSurfaceIsDesertFinish()
static void Terraria.WorldGen.SecretSeed.DoSurfaceIsDesertFinish () inline static
Definition at line 90328 of file WorldGen.cs.
            {
                int num = WorldGen.FindLowestCloud() + 1;
                for (int i = 5; i < Main.maxTilesX - 5; i++)
                {
                    int num2 = 0;
                    bool flag = false;
                    int num3 = 7;
                    int num4 = 5;
                    while ((double)num4 <= Main.worldSurface)
                    {
                        if (Main.tile[i, num4].wall == 63)
{
                            Main.tile[i, num4].wall = 2;
                        }
                        if (Main.tile[i, num4].type == 3 || Main.tile[i, num4].type == 73 || Main.tile[i, num4].type == 27)
{
                            WorldGen.TileFrame(i, num4, false, false);
                        }
                        if (num4 > num)
{
                            if (WorldGen.SolidTile3(i, num4))
{
                                flag = true;
                            }
                            if (flag && num3 > 0)
{
                                num3--;
                                if ((Main.tile[i, num4].type == 397 || Main.tile[i, num4].type == 396 || TileID.Sets.Ore[(int)Main.tile[i, num4].type] || Main.tile[i, num4].type == 40) && WorldGen.SolidTile3(i, num4 + 1))
{
                                    Main.tile[i, num4].type = 53;
                                }
                            }
                            if (WorldGen.SolidTile3(i, num4) && (WorldGen.SolidTile3(i - 1, num4) || Main.tile[i - 1, num4].wall > 0) && (WorldGen.SolidTile3(i + 1, num4) || Main.tile[i + 1, num4].wall > 0))
{
                                if (num2 == 0 && (Main.tile[i, num4].type == 53 || Main.tile[i, num4].type == 112 || Main.tile[i, num4].type == 234 || Main.tile[i, num4].type == 116))
{
                                    num2 = 1;
                                }
                                if (num2 == 1 && Main.tile[i, num4].type != 53 && Main.tile[i, num4].type != 112 && Main.tile[i, num4].type != 234 && Main.tile[i, num4].type != 116)
{
                                    num2 = 2;
                                }
                            }
                            if (num2 == 2)
{
                                if (Main.tile[i, num4].wall == 0)
{
                                    Main.tile[i, num4].wall = 2;
                                }
                            }
                            else if (!flag && Main.tile[i, num4].wall == 2)
{
                                Main.tile[i, num4].wall = 0;
                            }
                            else if (Main.tile[i, num4].active() && Main.tile[i, num4].type == 53 && !WallID.Sets.Fences[(int)Main.tile[i, num4].wall])
{
                                Main.tile[i, num4].wall = 0;
                            }
                        }
                        num4++;
                    }
                }
            }
References Terraria.Tile.active(), Terraria.ID.WallID.Sets.Fences, Terraria.WorldGen.FindLowestCloud(), Terraria.ID.TileID.Sets.Ore, Terraria.WorldGen.SolidTile3(), Terraria.Main.tile, Terraria.WorldGen.TileFrame(), Terraria.Tile.type, Terraria.Tile.wall, and Terraria.Main.worldSurface.
Referenced by Terraria.WorldGen.SecretSeed.FinalizeSecretSeeds().