Terraria Decompiled: Terraria.WorldGen.SecretSeed.DoSurfaceIsDesert
DoSurfaceIsDesert()
static void Terraria.WorldGen.SecretSeed.DoSurfaceIsDesert () inline static
Definition at line 90394 of file WorldGen.cs.
            {
                if (WorldGen.skyblockWorldGen)
                {
                    return;
                }
                if (WorldGen.SecretSeed.noSurface.Enabled)
                {
                    for (int i = 5; i < Main.maxTilesY - 5; i++)
                    {
                        int num = Main.maxTilesX + 10;
                        int num2 = -10;
                        for (int j = 0; j < Main.maxTilesX; j++)
{
                            if (Main.tile[j, i].type == 147 || Main.tile[j, i].type == 161)
{
                                if (j > num2)
{
                                    num2 = j;
                                }
                                if (j < num)
{
                                    num = j;
                                }
                            }
                        }
                        for (int k = 5; k < Main.maxTilesX - 5; k++)
{
                            if (k >= num && k <= num2)
{
                                if ((double)i >= Main.worldSurface - (double)WorldGen.genRand.Next(3) && k > num && k < num2 && (!WorldGen.remixWorldGen || (double)i <= Main.rockLayer + (double)WorldGen.genRand.Next(-1, 2)) && (Main.tile[k, i].wall == 0 || Main.tile[k, i].wall == 40 || Main.tile[k, i].wall == 71))
{
                                    if (WorldGen.SolidTile(k, i, false) || Main.tile[k, i].wall == 40 || Main.tile[k, i].wall == 71)
{
                                        Main.tile[k, i].wall = 216;
                                    }
                                    else
{
                                        Main.tile[k, i].wall = 187;
                                        if (WorldGen.genRand.Next(3) == 0)
{
                                            Main.tile[k, i - 1].wall = 187;
                                        }
                                        if (WorldGen.genRand.Next(3) == 0)
{
                                            Main.tile[k, i + 1].wall = 187;
                                            if (WorldGen.genRand.Next(3) == 0)
{
                                                Main.tile[k, i + 2].wall = 187;
                                            }
                                        }
                                    }
                                }
                                if (Main.tile[k, i].type == 147)
{
                                    Main.tile[k, i].type = 397;
                                }
                                else if (Main.tile[k, i].type == 161)
{
                                    Main.tile[k, i].type = 396;
                                }
                                if (WorldGen.remixWorldGen && (double)i > Main.rockLayer + (double)WorldGen.genRand.Next(-1, 2))
{
                                    if (!Main.tile[k, i - 1].active())
{
                                        int num3 = WorldGen.genRand.Next(5, 8);
                                        int num4 = i;
                                        while (num4 < Main.UnderworldLayer && num4 <= i + num3 && WorldGen.SolidTile3(k, num4))
{
                                            if (!WorldGen.SolidTile3(k, num4 + 1))
{
                                                break;
                                            }
                                            if (Main.tile[k, num4].type == 147 || Main.tile[k, num4].type == 161 || Main.tile[k, num4].type == 397 || Main.tile[k, num4].type == 396)
{
                                                Main.tile[k, num4].type = 53;
                                            }
                                            num4++;
                                        }
                                    }
                                }
                                else if (WorldGen.genRand.Next(2) == 0 && !Main.tile[k, i - 1].active() && !Main.tile[k + 1, i - 1].active() && !Main.tile[k, i - 2].active() && !Main.tile[k + 1, i - 2].active())
{
                                    if (WorldGen.genRand.Next(2) == 0)
{
                                        WorldGen.PlaceTile(k, i - 1, 485, false, false, -1, 0);
                                    }
                                    else
{
                                        WorldGen.PlaceTile(k, i - 1, 484, false, false, -1, 0);
                                    }
                                }
                            }
                            else if (Main.tile[k, i].wall == 187 || Main.tile[k, i].wall == 216)
{
                                if (!Main.tile[k, i].active() && Main.tile[k, i].type == 0)
{
                                    Main.tile[k, i].type = 147;
                                }
                                if (Main.tile[k, i].type == 484 || Main.tile[k, i].type == 485)
{
                                    WorldGen.KillTile(k, i, false, false, false);
                                }
                                int num5 = k;
                                while (num5 > 0 && Main.tile[num5, i].active() && (Main.tile[num5, i].type == 397 || Main.tile[num5, i].type == 396 || Main.tile[num5, i].type == 53 || Main.tile[num5, i].type == 404))
{
                                    if (Main.tile[num5, i].type == 397)
{
                                        Main.tile[num5, i].type = 147;
                                    }
                                    if (Main.tile[num5, i].type == 396)
{
                                        Main.tile[num5, i].type = 161;
                                    }
                                    if (Main.tile[num5, i].type == 53)
{
                                        Main.tile[num5, i].type = 224;
                                    }
                                    num5--;
                                }
                                num5 = k + 1;
                                while (num5 < Main.maxTilesX && Main.tile[num5, i].active() && (Main.tile[num5, i].type == 397 || Main.tile[num5, i].type == 396 || Main.tile[num5, i].type == 53 || Main.tile[num5, i].type == 404))
{
                                    if (Main.tile[num5, i].type == 397)
{
                                        Main.tile[num5, i].type = 147;
                                    }
                                    if (Main.tile[num5, i].type == 396)
{
                                        Main.tile[num5, i].type = 161;
                                    }
                                    if (Main.tile[num5, i].type == 53)
{
                                        Main.tile[num5, i].type = 224;
                                    }
                                    num5++;
                                }
                                int num6 = i - 1;
                                while (num6 > 0 && (i == (int)(Main.rockLayer / 2.0) || Main.tile[k, num6].type == 397 || Main.tile[k, num6].type == 396 || Main.tile[k, num6].type == 53 || Main.tile[k, num6].type == 404))
{
                                    if (Main.tile[k, num6].type == 397)
{
                                        Main.tile[k, num6].type = 147;
                                    }
                                    if (Main.tile[k, num6].type == 396)
{
                                        Main.tile[k, num6].type = 161;
                                    }
                                    if (Main.tile[k, num6].type == 53)
{
                                        Main.tile[k, num6].type = 224;
                                    }
                                    num6--;
                                }
                                Main.tile[k, i].wall = 0;
                            }
                        }
                    }
                    return;
                }
                for (int l = 0; l < Main.maxTilesX; l++)
                {
                    int num7 = 0;
                    while ((double)num7 < Main.worldSurface + (double)WorldGen.genRand.Next(3))
                    {
                        if (Main.tile[l, num7].active())
{
                            if (Main.tile[l, num7].type == 1)
{
                                Main.tile[l, num7].type = 396;
                            }
                            if (Main.tile[l, num7].type == 25)
{
                                Main.tile[l, num7].type = 398;
                            }
                            if (Main.tile[l, num7].type == 203)
{
                                Main.tile[l, num7].type = 399;
                            }
                            if (Main.tile[l, num7].type == 117)
{
                                Main.tile[l, num7].type = 402;
                            }
                            if (Main.tile[l, num7].type == 0)
{
                                Main.tile[l, num7].type = 53;
                            }
                            if (Main.tile[l, num7].type == 2)
{
                                Main.tile[l, num7].type = 53;
                            }
                            if (Main.tile[l, num7].type == 23)
{
                                Main.tile[l, num7].type = 112;
                                for (int m = l - 3; m <= l + 3; m++)
{
                                    for (int n = num7 - 3; n <= num7 + 3; n++)
{
                                        if (Main.tile[m, n].type == 53)
{
                                            Main.tile[m, n].type = 112;
                                        }
                                    }
                                }
                            }
                            if (Main.tile[l, num7].type == 199)
{
                                Main.tile[l, num7].type = 234;
                                for (int num8 = l - 3; num8 <= l + 3; num8++)
{
                                    for (int num9 = num7 - 3; num9 <= num7 + 3; num9++)
{
                                        if (Main.tile[num8, num9].type == 53)
{
                                            Main.tile[num8, num9].type = 234;
                                        }
                                    }
                                }
                            }
                            if (Main.tile[l, num7].type == 109)
{
                                Main.tile[l, num7].type = 116;
                                for (int num10 = l - 3; num10 <= l + 3; num10++)
{
                                    for (int num11 = num7 - 3; num11 <= num7 + 3; num11++)
{
                                        if (Main.tile[num10, num11].type == 53)
{
                                            Main.tile[num10, num11].type = 116;
                                        }
                                    }
                                }
                            }
                        }
                        if ((Main.tile[l, num7].wall == 2 || Main.tile[l, num7].wall == 59) && Main.tile[l, num7].active() && Main.tile[l, num7].type == 53)
{
                            Main.tile[l, num7].wall = 0;
                        }
                        num7++;
                    }
                }
            }
References Terraria.Tile.active(), Terraria.WorldGen.genRand, Terraria.WorldGen.KillTile(), Terraria.Main.maxTilesX, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.SecretSeed.noSurface, Terraria.WorldGen.PlaceTile(), Terraria.WorldGen.remixWorldGen, Terraria.Main.rockLayer, Terraria.WorldGen.skyblockWorldGen, Terraria.WorldGen.SolidTile(), Terraria.WorldGen.SolidTile3(), Terraria.Main.tile, Terraria.Tile.type, Terraria.Main.UnderworldLayer, Terraria.Tile.wall, and Terraria.Main.worldSurface.
Referenced by Terraria.WorldGen.AddPasses().