Terraria Decompiled: Terraria.WorldGen.SecretSeed.Enable
Enable()
static void Terraria.WorldGen.SecretSeed.Enable (WorldGen::SecretSeed seed, bool playSound = true) inline static
Definition at line 88405 of file WorldGen.cs.
            {
                if (seed.Enabled)
                {
                    return;
                }
                WorldGen.SecretSeed.activeSecretSeedCount++;
                seed._enabled = true;
                if (!Main.dedServ)
                {
                    SecretSeedsTracker.AddSeedToTrack(seed.TextThatWasUsedToUnlock);
                }
                if (playSound)
                {
                    SoundEngine.PlaySound(seed._sound, -1, -1, 0f, 1f);
                }
            }
References Terraria.WorldGen.SecretSeed.activeSecretSeedCount, Terraria.GameContent.SecretSeedsTracker.AddSeedToTrack(), Terraria.Main.dedServ, and Terraria.Audio.SoundEngine.PlaySound().
Referenced by Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.ClickSecretSeed(), Terraria.Main.DedServ(), Terraria.GameContent.UI.States.UIWorldCreation.EnableSecretSeedOptions(), Terraria.GameContent.UI.States.UIWorldCreation.OnFinishedSettingSeed(), Terraria.IO.WorldFileData.SetSeedToRandomWithCurrentEvents(), and Terraria.IO.WorldFileData.TryApplyingCopiedSeed().