Terraria Decompiled: Terraria.WorldGen.SecretSeed.DoAddTeleporters_CanPutTeleporterHere
DoAddTeleporters_CanPutTeleporterHere()
static bool Terraria.WorldGen.SecretSeed.DoAddTeleporters_CanPutTeleporterHere (int x1, int y1, bool moreForcefulPlacement) inline static
Definition at line 89835 of file WorldGen.cs.
            {
                if (!moreForcefulPlacement && (!WorldGen.SolidTile(x1 - 1, y1, false) || !WorldGen.SolidTile(x1, y1, false) || !WorldGen.SolidTile(x1 + 1, y1, false)))
                {
                    return false;
                }
                y1--;
                if (Main.wallDungeon[(int)Main.tile[x1, y1].wall] || Main.tile[x1, y1].wall == 112 || Main.tile[x1, y1].wall == 86 || TileID.Sets.Clouds[(int)Main.tile[x1, y1 + 1].type])
                {
                    return false;
                }
                if (WorldGen.SecretSeed.dualDungeons.Enabled && DungeonUtils.InAnyPotentialDungeonBounds(x1, y1, 0, false))
                {
                    return false;
                }
                for (int i = x1 - 1; i <= x1 + 1; i++)
                {
                    for (int j = y1 - 3; j <= y1; j++)
                    {
                        if (Main.tile[i, y1].active() || Main.tile[i, y1].liquid > 0)
{
                            return false;
                        }
                    }
                }
                return Math.Abs(x1 - Main.spawnTileX) + Math.Abs(y1 - Main.spawnTileY) >= 20 && !WorldGen.IsTileNearby(x1, y1, 235, moreForcefulPlacement ? 150 : 300);
            }
References System.Math.Abs(), Terraria.Tile.active(), Terraria.ID.TileID.Sets.Clouds, Terraria.WorldGen.SecretSeed.dualDungeons, Terraria.GameContent.Generation.Dungeon.DungeonUtils.InAnyPotentialDungeonBounds(), Terraria.WorldGen.IsTileNearby(), Terraria.Tile.liquid, Terraria.WorldGen.SolidTile(), Terraria.Main.spawnTileX, Terraria.Main.spawnTileY, Terraria.Main.tile, Terraria.Tile.type, Terraria.Tile.wall, and Terraria.Main.wallDungeon.
Referenced by Terraria.WorldGen.SecretSeed.DoAddTeleporters().