Terraria Decompiled: Terraria.WorldGen.SecretSeed.DoDigExtraHoles
DoDigExtraHoles()
static void Terraria.WorldGen.SecretSeed.DoDigExtraHoles () inline static
Definition at line 90885 of file WorldGen.cs.
            {
                int num = (int)((double)Main.maxTilesX * 0.1);
                for (int i = 0; i < num; i++)
                {
                    int num2 = WorldGen.genRand.Next(50, Main.maxTilesX - 50);
                    int num3 = WorldGen.genRand.Next(50, Main.maxTilesY - 50);
                    int num4 = WorldGen.genRand.Next(5, 16);
                    if (WorldGen.genRand.Next(3) == 0)
                    {
                        num4 += WorldGen.genRand.Next(15);
                    }
                    int num5 = WorldGen.genRand.Next(30, 201);
                    WorldGen.TileRunner(num2, num3, (double)num4, num5, -1, false, (double)((float)WorldGen.genRand.Next(-15, 16) * 0.1f), (double)((float)WorldGen.genRand.Next(10, 26) * 0.1f), true, true, -1);
                }
            }
References Terraria.WorldGen.genRand, int, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), and Terraria.WorldGen.TileRunner().
Referenced by Terraria.WorldGen.AddPasses().