Terraria Decompiled: Terraria.WorldGen.SecretSeed.DoExtraLiquidAddBubbleBlocks
DoExtraLiquidAddBubbleBlocks()
static void Terraria.WorldGen.SecretSeed.DoExtraLiquidAddBubbleBlocks () inline static
Definition at line 89481 of file WorldGen.cs.
            {
                if (WorldGen.skyblockWorldGen)
                {
                    return;
                }
                bool flag = Main.tileSolid[225];
                Main.tileSolid[225] = true;
                Liquid.QuickWater(-2, -1, -1);
                if (WorldGen.remixWorldGen)
                {
                    bool flag2 = true;
                    while (flag2)
                    {
                        int num = (int)((double)Main.maxTilesX * 0.38);
                        int num2 = (int)((double)Main.maxTilesX * 0.62);
                        int num3 = Main.maxTilesY - 135;
                        for (int i = num; i < num2 + 15; i++)
{
                            for (int j = Main.maxTilesY - 200; j < num3 + 10; j++)
{
                                Main.tile[i, j].liquid = 0;
                            }
                        }
                        Liquid.QuickWater(-2, -1, -1);
                        flag2 = false;
                        int num4 = Main.maxTilesX / 2;
                        int num5 = Main.maxTilesY - 10;
                        while (WorldGen.SolidTile(num4, num5, false))
{
                            num5--;
                        }
                        int num6 = num5 + 1;
                        for (int k = num4 - 40; k <= num4 + 40; k++)
{
                            for (int l = num6 - 10; l <= num6 + 10; l++)
{
                                if (Main.tile[k, l].liquid > 0)
{
                                    flag2 = true;
                                    break;
                                }
                            }
                            if (flag2)
{
                                break;
                            }
                        }
                    }
                }
                Main.tileSolid[225] = flag;
                int num7 = Main.maxTilesX * 20;
                int num8 = 10;
                int num9 = 30;
                int num10 = num8;
                int num11 = num9;
                int num12 = 15;
                if (WorldGen.SecretSeed.teamBasedSpawns.Enabled)
                {
                    num10 = 20;
                    num11 = 30;
                }
                for (int m = 0; m < num7; m++)
                {
                    bool flag3 = false;
                    int num13 = WorldGen.genRand.Next(100, Main.maxTilesX - 100);
                    int num14 = WorldGen.genRand.Next(100, Main.maxTilesY - 100);
                    int num15;
                    if (WorldGen.SecretSeed.IsConsideredTheSpawnArea(num13, num14))
                    {
                        num15 = WorldGen.genRand.Next(num10, num11 + 1);
                    }
                    else
                    {
                        num15 = WorldGen.genRand.Next(num8, num9 + 1);
                    }
                    if (Vector2D.Distance(new Vector2D((double)num13, (double)num14), GenVars.shimmerPosition) >= 100.0)
                    {
                        if (m > num7 / 2)
{
                            num15 /= 2;
                        }
                        if (!WorldGen.IsTileNearby(num13, num14, 379, num15 + num12))
{
                            float num16 = 0f;
                            int num17 = 0;
                            for (int n = num13 - num15; n <= num13 + num15; n++)
{
                                for (int num18 = num14 - num15; num18 <= num14 + num15; num18++)
{
                                    if (n == num13 - num15 || n == num13 + num15 || num18 == num14 - num15 || num18 == num14 + num15)
{
                                        if (WorldGen.SolidTile(n, num18, false))
{
                                            num17++;
                                        }
                                        if (Main.tile[n, num18].active() && (!WorldGen.SolidTile(n, num18, false) || Main.tile[n, num18].type == 10 || Main.tile[n, num18].type == 192 || Main.tile[n, num18].type == 384 || Main.tile[n, num18].type == 189 || Main.tile[n, num18].type == 196 || Main.tile[n, num18].type == 460 || Main.tile[n, num18].type == 48 || Main.tile[n, num18].type == 232 || (Main.tile[n, num18].type >= 0 && TileID.Sets.Boulders[(int)Main.tile[n, num18].type])))
{
                                            flag3 = true;
                                        }
                                    }
                                    if (WorldGen.SolidTile(n, num18, false))
{
                                        num16 += 0.334f;
                                    }
                                    else if (Main.tile[n, num18].liquid > 0)
{
                                        num16 += 1f;
                                    }
                                    if (Main.tile[n, num18].wall == 86 || Main.tile[n, num18].wall == 62)
{
                                        flag3 = true;
                                    }
                                    if (flag3)
{
                                        break;
                                    }
                                }
                                if (flag3)
{
                                    break;
                                }
                            }
                            if (!flag3 && num16 >= (float)((num15 * 2 + 1) * (num15 * 2 + 1) / 2) && num17 >= (num15 * 2 + 1) / 3)
{
                                for (int num19 = num13 - num15; num19 <= num13 + num15; num19++)
{
                                    for (int num20 = num14 - num15; num20 <= num14 + num15; num20++)
{
                                        if (num19 == num13 - num15 || num19 == num13 + num15 || num20 == num14 - num15 || num20 == num14 + num15)
{
                                            if (!Main.tile[num19, num20].active())
{
                                                WorldGen.PlaceTile(num19, num20, 379, false, false, -1, 0);
                                            }
                                            Main.tile[num19, num20].slope(0);
                                            Main.tile[num19, num20].halfBrick(false);
                                        }
                                        Main.tile[num19, num20].liquid = 0;
                                        Main.tile[num19, num20].fullbrightBlock(true);
                                    }
                                }
                                LandmassData landmassData = new LandmassData
{
                                    DataType = LandmassDataType.ExtraLiquidBubbleSquare,
                                    Position = new Vector2((float)num13, (float)num14),
                                    RadiusOrHalfSize = num15
                                };
                                GenVars.landmassData.Add(landmassData);
                            }
                        }
                    }
                }
                for (int num21 = num12; num21 < Main.maxTilesX - num12; num21++)
                {
                    for (int num22 = num12; num22 < Main.maxTilesY - num12; num22++)
                    {
                        if (WorldGen.SolidTile(num21, num22, false))
{
                            Main.tile[num21, num22].liquid = 0;
                        }
                    }
                }
            }
References Terraria.Tile.active(), System.Collections.Generic.List< T >.Add(), Terraria.ID.TileID.Sets.Boulders, ReLogic.Utilities.Vector2D.Distance(), Terraria.Tile.fullbrightBlock(), Terraria.WorldGen.genRand, Terraria.Tile.halfBrick(), int, Terraria.WorldGen.SecretSeed.IsConsideredTheSpawnArea(), Terraria.WorldGen.IsTileNearby(), Terraria.WorldBuilding.GenVars.landmassData, Terraria.Tile.liquid, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.PlaceTile(), Terraria.Liquid.QuickWater(), Terraria.WorldGen.remixWorldGen, Terraria.WorldBuilding.GenVars.shimmerPosition, Terraria.WorldGen.skyblockWorldGen, Terraria.Tile.slope(), Terraria.WorldGen.SolidTile(), Terraria.WorldGen.SecretSeed.teamBasedSpawns, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Tile.type, and Terraria.Tile.wall.