Terraria Decompiled: Terraria.WorldGen.SecretSeed.DoActuallyNoTraps
DoActuallyNoTraps()
static void Terraria.WorldGen.SecretSeed.DoActuallyNoTraps () inline static
Definition at line 90679 of file WorldGen.cs.
            {
                if (WorldGen.SecretSeed.Variations.actuallyNoTrapsForRealIMeanIt)
                {
                    for (int i = 0; i < Main.maxTilesX; i++)
                    {
                        for (int j = 0; j < Main.maxTilesY; j++)
{
                            if (Main.tile[i, j].type == 48)
{
                                WorldGen.KillTile(i, j, false, false, false);
                            }
                            if (Main.tile[i, j].type == 232)
{
                                WorldGen.KillTile(i, j, false, false, false);
                            }
                        }
                    }
                    return;
                }
                int num = 20;
                for (int k = num; k < Main.maxTilesX - num; k++)
                {
                    for (int l = num; l < Main.maxTilesY - num; l++)
                    {
                        if (Main.tile[k, l].active() && (Main.tile[k, l].type == 21 || Main.tile[k, l].type == 467 || Main.tile[k, l].type == 12 || Main.tile[k, l].type == 639 || Main.tile[k, l].type == 665) && Math.Abs(k - Main.spawnTileX) + Math.Abs(l - Main.spawnTileY) > 100)
{
                            int num2 = WorldGen.genRand.Next(1, 10);
                            int num3 = num2;
                            if (!WorldGen.SecretSeed.coatEverythingEcho.Enabled)
{
                                num3 = 1;
                            }
                            for (int m = k - num2; m <= k + num2; m++)
{
                                for (int n = l - num2; n <= l + num3; n++)
{
                                    if ((!Main.tile[m, n].active() || Main.tileCut[(int)Main.tile[m, n].type] || (!WorldGen.SecretSeed.coatEverythingEcho.Enabled && !Main.tileFrameImportant[(int)Main.tile[m, n].type] && WorldGen.SolidTile3(m, n))) && !Main.tile[m, n].actuator() && Main.tile[m, n].type != 60 && Main.tile[m, n].type != 70)
{
                                        Main.tile[m, n].active(true);
                                        Main.tile[m, n].slope(0);
                                        Main.tile[m, n].halfBrick(false);
                                        if (Main.tile[m, n].wall == 87)
{
                                            Main.tile[m, n].type = 232;
                                        }
                                        else
{
                                            Main.tile[m, n].type = 48;
                                        }
                                        if (WorldGen.SecretSeed.coatEverythingEcho.Enabled)
{
                                            Main.tile[m, n].invisibleBlock(true);
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
References System.Math.Abs(), Terraria.Tile.active(), Terraria.WorldGen.SecretSeed.Variations.actuallyNoTrapsForRealIMeanIt, Terraria.Tile.actuator(), Terraria.WorldGen.SecretSeed.coatEverythingEcho, Terraria.WorldGen.genRand, Terraria.Tile.halfBrick(), Terraria.Tile.invisibleBlock(), Terraria.WorldGen.KillTile(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Tile.slope(), Terraria.WorldGen.SolidTile3(), Terraria.Main.spawnTileX, Terraria.Main.spawnTileY, Terraria.Main.tile, Terraria.Main.tileCut, Terraria.Main.tileFrameImportant, Terraria.Tile.type, and Terraria.Tile.wall.
Referenced by Terraria.WorldGen.SecretSeed.FinalizeSecretSeeds().