Terraria Decompiled: Terraria.WorldGen.SecretSeed.DoWorldIsFrozen
DoWorldIsFrozen()
static void Terraria.WorldGen.SecretSeed.DoWorldIsFrozen () inline static
Definition at line 90256 of file WorldGen.cs.
            {
                if (WorldGen.skyblockWorldGen)
                {
                    return;
                }
                int num = Main.UnderworldLayer - Main.maxTilesY / 10;
                if (WorldGen.SecretSeed.activeSecretSeedCount >= 6)
                {
                    num = (int)Main.rockLayer;
                }
                for (int i = 0; i < Main.maxTilesX; i++)
                {
                    for (int j = 0; j < num + WorldGen.genRand.Next(3); j++)
                    {
                        if (Main.tile[i, j].type == 1)
{
                            Main.tile[i, j].type = 161;
                        }
                        if (Main.tile[i, j].type == 25)
{
                            Main.tile[i, j].type = 163;
                        }
                        if (Main.tile[i, j].type == 203)
{
                            Main.tile[i, j].type = 200;
                        }
                        if (Main.tile[i, j].type == 117)
{
                            Main.tile[i, j].type = 164;
                        }
                        if (Main.tile[i, j].type == 0)
{
                            Main.tile[i, j].type = 147;
                        }
                        if (Main.tile[i, j].type == 2)
{
                            Main.tile[i, j].type = 147;
                        }
                        if (Main.tile[i, j].type == 23)
{
                            Main.tile[i, j].type = 147;
                        }
                        if (Main.tile[i, j].type == 199)
{
                            Main.tile[i, j].type = 147;
                        }
                        if (Main.tile[i, j].type == 109)
{
                            Main.tile[i, j].type = 147;
                        }
                        if (Main.tile[i, j].type == 123)
{
                            Main.tile[i, j].type = 224;
                        }
                        if (Main.tile[i, j].type == 196)
{
                            Main.tile[i, j].type = 460;
                        }
                        if (Main.tile[i, j].wall == 2)
{
                            Main.tile[i, j].wall = 40;
                        }
                        if (Main.tile[i, j].wall == 59)
{
                            Main.tile[i, j].wall = 40;
                        }
                    }
                }
            }
References Terraria.WorldGen.SecretSeed.activeSecretSeedCount, Terraria.WorldGen.genRand, int, Terraria.Main.maxTilesX, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rockLayer, Terraria.WorldGen.skyblockWorldGen, Terraria.Main.tile, Terraria.Tile.type, and Terraria.Tile.wall.
Referenced by Terraria.WorldGen.AddPasses(), and Terraria.WorldGen.SecretSeed.FinalizeSecretSeeds().