Terraria Decompiled: Terraria.WorldGen.SecretSeed.FinalizeSecretSeeds
FinalizeSecretSeeds()
static void Terraria.WorldGen.SecretSeed.FinalizeSecretSeeds () inline static
Definition at line 88484 of file WorldGen.cs.
            {
                if (WorldGen.SecretSeed.surfaceIsDesert.Enabled)
                {
                    WorldGen.SecretSeed.DoSurfaceIsDesertFinish();
                }
                if (WorldGen.SecretSeed.extraLiquid.Enabled)
                {
                    WorldGen.SecretSeed.DoExtraLiquidFinish();
                }
                if (WorldGen.SecretSeed.surfaceIsInSpace.Enabled)
                {
                    WorldGen.SecretSeed.DoSurfaceIsInSpace();
                }
                if (WorldGen.SecretSeed.actuallyNoTraps.Enabled)
                {
                    WorldGen.SecretSeed.DoActuallyNoTraps();
                }
                if (WorldGen.SecretSeed.surfaceIsMushrooms.Enabled)
                {
                    if (!WorldGen.SecretSeed.noSurface.Enabled)
                    {
                        WorldGen.SecretSeed.DoSurfaceIsMushrooms();
                    }
                    WorldGen.SecretSeed.DoSurfaceIsMushrooms();
                }
                if (WorldGen.SecretSeed.worldIsFrozen.Enabled)
                {
                    WorldGen.SecretSeed.DoWorldIsFrozen();
                }
                if (WorldGen.SecretSeed.noInfection.Enabled)
                {
                    WorldGen.SecretSeed.DoNoInfection();
                }
                if (WorldGen.SecretSeed.hallowOnTheSurface.Enabled)
                {
                    WorldGen.SecretSeed.DoHallowOnSurface();
                }
                if (WorldGen.SecretSeed.worldIsInfected.Enabled)
                {
                    WorldGen.SecretSeed.DoWorldIsInfected();
                }
                if (WorldGen.SecretSeed.startInHardmode.Enabled)
                {
                    WorldGen.SecretSeed.DoStartInHardmode();
                }
                if (WorldGen.SecretSeed.noSurface.Enabled)
                {
                    WorldGen.SecretSeed.DoNoSurface();
                }
                if (WorldGen.SecretSeed.coatEverythingEcho.Enabled)
                {
                    WorldGen.SecretSeed.DoCoatEverythingEcho();
                }
                if (WorldGen.SecretSeed.coatEverythingIlluminant.Enabled)
                {
                    WorldGen.SecretSeed.DoCoatEverythingIlluminant();
                }
                if (WorldGen.SecretSeed.paintEverythingGray.Enabled)
                {
                    WorldGen.SecretSeed.DoPaintEverythingGray();
                }
                if (WorldGen.SecretSeed.paintEverythingNegative.Enabled)
                {
                    WorldGen.SecretSeed.DoPaintEverythingNegative();
                }
                if (WorldGen.SecretSeed.randomSpawn.Enabled)
                {
                    WorldGen.SecretSeed.DoRandomSpawn();
                }
                if (WorldGen.SecretSeed.rainbowStuff.Enabled)
                {
                    WorldGen.SecretSeed.DoRainbowStuff();
                }
                if (WorldGen.SecretSeed.portalGunInChests.Enabled)
                {
                    WorldGen.SecretSeed.DoPortalGunInChests();
                }
                if (WorldGen.SecretSeed.worldIsFrozen.Enabled)
                {
                    WorldGen.SecretSeed.DoWorldIsFrozenFinish();
                }
                if (WorldGen.SecretSeed.errorWorld.Enabled)
                {
                    WorldGen.SecretSeed.DoErrorWorldFinish();
                }
                if (WorldGen.SecretSeed.teamBasedSpawns.Enabled)
                {
                    ExtraSpawnPointManager.settings = new ExtraSpawnSettings
                    {
                        spawnType = ExtraSpawnType.TeamBased,
                        surface = (!GenVars.worldSpawnHasBeenRandomized && Main.isThereAWorldSurface),
                        remix = Main.remixWorld,
                        roundLandmass = WorldGen.SecretSeed.roundLandmasses.Enabled,
                        skyblock = Main.skyblockWorld,
                        extraLiquid = WorldGen.SecretSeed.extraLiquid.Enabled
                    };
                    ExtraSpawnPointManager.GenerateExtraSpawns();
                }
                if (WorldGen.SecretSeed.Variations.noSpiderCavesActuallyNoSpiderCaves)
                {
                    NPC.savedStylist = true;
                }
            }
References Terraria.WorldGen.SecretSeed.actuallyNoTraps, Terraria.WorldGen.SecretSeed.coatEverythingEcho, Terraria.WorldGen.SecretSeed.coatEverythingIlluminant, Terraria.WorldGen.SecretSeed.DoActuallyNoTraps(), Terraria.WorldGen.SecretSeed.DoCoatEverythingEcho(), Terraria.WorldGen.SecretSeed.DoCoatEverythingIlluminant(), Terraria.WorldGen.SecretSeed.DoErrorWorldFinish(), Terraria.WorldGen.SecretSeed.DoExtraLiquidFinish(), Terraria.WorldGen.SecretSeed.DoHallowOnSurface(), Terraria.WorldGen.SecretSeed.DoNoInfection(), Terraria.WorldGen.SecretSeed.DoNoSurface(), Terraria.WorldGen.SecretSeed.DoPaintEverythingGray(), Terraria.WorldGen.SecretSeed.DoPaintEverythingNegative(), Terraria.WorldGen.SecretSeed.DoPortalGunInChests(), Terraria.WorldGen.SecretSeed.DoRainbowStuff(), Terraria.WorldGen.SecretSeed.DoRandomSpawn(), Terraria.WorldGen.SecretSeed.DoStartInHardmode(), Terraria.WorldGen.SecretSeed.DoSurfaceIsDesertFinish(), Terraria.WorldGen.SecretSeed.DoSurfaceIsInSpace(), Terraria.WorldGen.SecretSeed.DoSurfaceIsMushrooms(), Terraria.WorldGen.SecretSeed.DoWorldIsFrozen(), Terraria.WorldGen.SecretSeed.DoWorldIsFrozenFinish(), Terraria.WorldGen.SecretSeed.DoWorldIsInfected(), Terraria.WorldGen.SecretSeed.errorWorld, Terraria.WorldGen.SecretSeed.extraLiquid, Terraria.GameContent.ExtraSpawnPointManager.GenerateExtraSpawns(), Terraria.WorldGen.SecretSeed.hallowOnTheSurface, Terraria.Main.isThereAWorldSurface, Terraria.WorldGen.SecretSeed.noInfection, Terraria.WorldGen.SecretSeed.Variations.noSpiderCavesActuallyNoSpiderCaves, Terraria.WorldGen.SecretSeed.noSurface, Terraria.WorldGen.SecretSeed.paintEverythingGray, Terraria.WorldGen.SecretSeed.paintEverythingNegative, Terraria.WorldGen.SecretSeed.portalGunInChests, Terraria.WorldGen.SecretSeed.rainbowStuff, Terraria.WorldGen.SecretSeed.randomSpawn, Terraria.Main.remixWorld, Terraria.WorldGen.SecretSeed.roundLandmasses, Terraria.Main.skyblockWorld, Terraria.WorldGen.SecretSeed.startInHardmode, Terraria.WorldGen.SecretSeed.surfaceIsDesert, Terraria.WorldGen.SecretSeed.surfaceIsInSpace, Terraria.WorldGen.SecretSeed.surfaceIsMushrooms, Terraria.WorldGen.SecretSeed.teamBasedSpawns, Terraria.WorldGen.SecretSeed.worldIsFrozen, and Terraria.WorldGen.SecretSeed.worldIsInfected.