Terraria Decompiled: Terraria.WorldGen.SecretSeed.DoSurfaceIsMushrooms
DoSurfaceIsMushrooms()
static void Terraria.WorldGen.SecretSeed.DoSurfaceIsMushrooms () inline static
Definition at line 90125 of file WorldGen.cs.
            {
                if (WorldGen.skyblockWorldGen)
                {
                    return;
                }
                if (WorldGen.SecretSeed.noSurface.Enabled)
                {
                    for (int i = 0; i < Main.maxTilesX; i++)
                    {
                        for (int j = 0; j < Main.maxTilesY; j++)
{
                            if (Main.tile[i, j].active() && Main.tile[i, j].type == 60)
{
                                WorldGen.Convert(i, j, 3, 0, true, true);
                            }
                            else if (Main.tile[i, j].wall == 64 || Main.tile[i, j].wall == 204 || Main.tile[i, j].wall == 205 || Main.tile[i, j].wall == 206 || Main.tile[i, j].wall == 207)
{
                                Main.tile[i, j].wall = 80;
                            }
                            else if (Main.tile[i, j].active() && Main.tile[i, j].type == 70)
{
                                WorldGen.Convert(i, j, 0, 0, true, true);
                            }
                            else if (Main.tile[i, j].wall == 80)
{
                                WorldGen.Convert(i, j, 0, 0, true, true);
                            }
                        }
                    }
                    return;
                }
                for (int k = 0; k < Main.maxTilesX; k++)
                {
                    int num = 0;
                    while ((double)num < Main.worldSurface + (double)WorldGen.genRand.Next(3))
                    {
                        if (Main.tile[k, num].type == 60)
{
                            WorldGen.Convert(k, num, 3, 0, true, true);
                        }
                        if (Main.tile[k, num].wall == 15)
{
                            WorldGen.Convert(k, num, 3, 0, true, true);
                        }
                        if (Main.tile[k, num].type == 0)
{
                            Main.tile[k, num].type = 59;
                        }
                        if (Main.tile[k, num].type == 2)
{
                            Main.tile[k, num].type = 60;
                        }
                        if (Main.tile[k, num].wall == 63)
{
                            Main.tile[k, num].wall = 80;
                        }
                        if (Main.tile[k, num].wall == 65)
{
                            Main.tile[k, num].wall = 80;
                        }
                        if (Main.tile[k, num].wall == 66)
{
                            Main.tile[k, num].wall = 80;
                        }
                        if (Main.tile[k, num].wall == 68)
{
                            Main.tile[k, num].wall = 80;
                        }
                        if (Main.tile[k, num].wall == 64)
{
                            Main.tile[k, num].wall = 80;
                        }
                        if (Main.tile[k, num].wall == 205)
{
                            Main.tile[k, num].wall = 80;
                        }
                        if (Main.tile[k, num].wall == 206)
{
                            Main.tile[k, num].wall = 80;
                        }
                        if (Main.tile[k, num].wall == 207)
{
                            Main.tile[k, num].wall = 80;
                        }
                        num++;
                    }
                }
            }
References Terraria.Tile.active(), Terraria.WorldGen.Convert(), Terraria.WorldGen.genRand, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.SecretSeed.noSurface, Terraria.WorldGen.skyblockWorldGen, Terraria.Main.tile, Terraria.Tile.type, Terraria.Tile.wall, and Terraria.Main.worldSurface.
Referenced by Terraria.WorldGen.AddPasses(), and Terraria.WorldGen.SecretSeed.FinalizeSecretSeeds().