Terraria Decompiled: Terraria.WorldGen.SecretSeed.DoWorldIsInfected
DoWorldIsInfected()
static void Terraria.WorldGen.SecretSeed.DoWorldIsInfected () inline static
Definition at line 90049 of file WorldGen.cs.
            {
                if (WorldGen.skyblockWorldGen)
                {
                    return;
                }
                int num = 0;
                if (WorldGen.SecretSeed.noInfection.Enabled)
                {
                    if (WorldGen.SecretSeed.noSurface.Enabled)
                    {
                        num = (int)(Main.rockLayer + (double)Main.UnderworldLayer) / 2;
                    }
                    else
                    {
                        num = (int)Main.worldSurface + 10;
                        if (WorldGen.SecretSeed.hallowOnTheSurface.Enabled)
{
                            num = (int)(Main.rockLayer + (double)Main.UnderworldLayer) / 2;
                        }
                    }
                }
                else if (WorldGen.SecretSeed.hallowOnTheSurface.Enabled)
                {
                    num = (int)Main.worldSurface - 3;
                }
                for (int i = 0; i < Main.maxTilesX; i++)
                {
                    int num2 = 1;
                    if (WorldGen.drunkWorldGen)
                    {
                        if (GenVars.crimsonLeft && i < Main.maxTilesX / 2)
{
                            num2 = 4;
                        }
                        if (!GenVars.crimsonLeft && i > Main.maxTilesX / 2)
{
                            num2 = 4;
                        }
                    }
                    else if (WorldGen.crimson)
                    {
                        num2 = 4;
                    }
                    for (int j = num + WorldGen.genRand.Next(3); j < Main.maxTilesY; j++)
                    {
                        Tile tile = Main.tile[i, j];
                        bool flag = tile.type != 60 && tile.type != 109 && tile.type != 117 && tile.type != 164 && tile.type != 116 && tile.type != 403 && tile.type != 402;
                        bool flag2 = tile.wall != 64 && tile.wall != 204 && tile.wall != 205 && tile.wall != 206 && tile.wall != 207 && tile.wall != 70 && tile.wall != 265 && tile.wall != 28 && tile.wall != 219 && tile.wall != 222;
                        WorldGen.Convert(i, j, num2, 0, flag, flag2);
                    }
                }
            }
References Terraria.WorldGen.Convert(), Terraria.WorldGen.crimson, Terraria.WorldBuilding.GenVars.crimsonLeft, Terraria.WorldGen.drunkWorldGen, Terraria.WorldGen.genRand, Terraria.WorldGen.SecretSeed.hallowOnTheSurface, int, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.SecretSeed.noInfection, Terraria.WorldGen.SecretSeed.noSurface, Terraria.Main.rockLayer, Terraria.WorldGen.skyblockWorldGen, Terraria.Main.tile, Terraria.Main.UnderworldLayer, and Terraria.Main.worldSurface.
Referenced by Terraria.WorldGen.SecretSeed.FinalizeSecretSeeds().