Terraria Decompiled: Terraria.WorldGen.SecretSeed.DoCoatEverythingIlluminant
DoCoatEverythingIlluminant()
static void Terraria.WorldGen.SecretSeed.DoCoatEverythingIlluminant () inline static
Definition at line 88790 of file WorldGen.cs.
            {
                bool coatEverythingIlluminantJustSomeThings = WorldGen.SecretSeed.Variations.coatEverythingIlluminantJustSomeThings;
                bool coatEverythingIlluminantJustRandomSpots = WorldGen.SecretSeed.Variations.coatEverythingIlluminantJustRandomSpots;
                for (int i = 0; i < Main.maxTilesX; i++)
                {
                    for (int j = 0; j < Main.maxTilesY; j++)
                    {
                        if (coatEverythingIlluminantJustSomeThings)
{
                            if (Main.tile[i, j].type == 12 || Main.tile[i, j].type == 665 || Main.tile[i, j].type == 639)
{
                                Main.tile[i, j].fullbrightBlock(true);
                            }
                        }
                        else if (coatEverythingIlluminantJustRandomSpots)
{
                            if (WorldGen.genRand.Next(2) == 0)
{
                                Main.tile[i, j].fullbrightBlock(true);
                                Main.tile[i, j].fullbrightWall(true);
                                Main.tile[i, j].invisibleBlock(false);
                                Main.tile[i, j].invisibleWall(false);
                            }
                        }
                        else
{
                            Main.tile[i, j].fullbrightBlock(true);
                            Main.tile[i, j].fullbrightWall(true);
                        }
                    }
                }
            }
References Terraria.WorldGen.SecretSeed.Variations.coatEverythingIlluminantJustRandomSpots, Terraria.WorldGen.SecretSeed.Variations.coatEverythingIlluminantJustSomeThings, Terraria.Tile.fullbrightBlock(), Terraria.Tile.fullbrightWall(), Terraria.WorldGen.genRand, Terraria.Tile.invisibleBlock(), Terraria.Tile.invisibleWall(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.SecretSeed.FinalizeSecretSeeds().