Terraria Decompiled: Terraria.WorldGen.SecretSeed.DoHallowOnSurface
DoHallowOnSurface()
static void Terraria.WorldGen.SecretSeed.DoHallowOnSurface () inline static
Definition at line 89974 of file WorldGen.cs.
            {
                if (WorldGen.skyblockWorldGen)
                {
                    return;
                }
                int num = (int)Main.worldSurface;
                if (WorldGen.SecretSeed.noSurface.Enabled)
                {
                    if (WorldGen.SecretSeed.worldIsInfected.Enabled && WorldGen.SecretSeed.noInfection.Enabled)
                    {
                        num = (int)Main.rockLayer / 2;
                    }
                    else
                    {
                        num = (int)Main.rockLayer;
                    }
                }
                for (int i = 0; i < Main.maxTilesX; i++)
                {
                    for (int j = 0; j < num + WorldGen.genRand.Next(3); j++)
                    {
                        if (Main.tile[i, j].type == 2)
{
                            WorldGen.Convert(i, j, 2, 0, true, false);
                        }
                        if (Main.tile[i, j].type == 161)
{
                            WorldGen.Convert(i, j, 2, 0, true, false);
                        }
                        if (WorldGen.SecretSeed.noSurface.Enabled && Main.tile[i, j].type == 1)
{
                            WorldGen.Convert(i, j, 2, 0, true, false);
                        }
                        if (Main.tile[i, j].type == 53)
{
                            WorldGen.Convert(i, j, 2, 0, true, false);
                        }
                        if (Main.tile[i, j].type == 396)
{
                            WorldGen.Convert(i, j, 2, 0, true, false);
                        }
                        if (Main.tile[i, j].type == 397)
{
                            WorldGen.Convert(i, j, 2, 0, true, false);
                        }
                        if (Main.tile[i, j].wall == 187)
{
                            WorldGen.Convert(i, j, 2, 0, false, true);
                        }
                        if (Main.tile[i, j].wall == 216)
{
                            WorldGen.Convert(i, j, 2, 0, false, true);
                        }
                        if (Main.tile[i, j].wall == 63)
{
                            WorldGen.Convert(i, j, 2, 0, false, true);
                        }
                        if (Main.tile[i, j].wall == 65)
{
                            WorldGen.Convert(i, j, 2, 0, false, true);
                        }
                        if (Main.tile[i, j].wall == 66)
{
                            WorldGen.Convert(i, j, 2, 0, false, true);
                        }
                        if (Main.tile[i, j].wall == 68)
{
                            WorldGen.Convert(i, j, 2, 0, false, true);
                        }
                    }
                }
            }
References Terraria.WorldGen.Convert(), Terraria.WorldGen.genRand, int, Terraria.Main.maxTilesX, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.SecretSeed.noInfection, Terraria.WorldGen.SecretSeed.noSurface, Terraria.Main.rockLayer, Terraria.WorldGen.skyblockWorldGen, Terraria.Main.tile, Terraria.Tile.type, Terraria.Tile.wall, Terraria.WorldGen.SecretSeed.worldIsInfected, and Terraria.Main.worldSurface.
Referenced by Terraria.WorldGen.SecretSeed.FinalizeSecretSeeds().