Terraria Decompiled: Terraria.WorldGen.SecretSeed.DoPooEverywhere
DoPooEverywhere()
static void Terraria.WorldGen.SecretSeed.DoPooEverywhere () inline static
Definition at line 91019 of file WorldGen.cs.
            {
                int num = 40;
                int num2 = (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.0002);
                int num3 = (2 + WorldGen.SecretSeed.activeSecretSeedCount) / 3;
                if (num3 < 1)
                {
                    num3 = 1;
                }
                num2 /= num3;
                for (int i = 0; i < num2; i++)
                {
                    int num4 = WorldGen.genRand.Next(num, Main.maxTilesX - num);
                    int num5 = WorldGen.genRand.Next(num, Main.maxTilesY - num);
                    int num6 = 0;
                    while (num6 < 30 && !WorldGen.SolidTile(num4, num5, false))
                    {
                        num5++;
                        num6++;
                    }
                    if ((WorldGen.skyblockWorldGen || !Main.tile[num4, num5].active() || (!Main.tileDungeon[(int)Main.tile[num4, num5].type] && !Main.wallDungeon[(int)Main.tile[num4, num5].wall] && !TileID.Sets.Clouds[(int)Main.tile[num4, num5].type] && Main.tile[num4, num5].wall != 73)) && WorldGen.SolidTile(num4, num5, false))
                    {
                        WorldGen.TileRunner(num4, num5, (double)WorldGen.genRand.Next(5, 12), WorldGen.genRand.Next(10, 31), 666, true, 0.0, 0.0, false, true, -1);
                    }
                }
            }
References Terraria.Tile.active(), Terraria.WorldGen.SecretSeed.activeSecretSeedCount, Terraria.ID.TileID.Sets.Clouds, Terraria.WorldGen.genRand, int, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.skyblockWorldGen, Terraria.WorldGen.SolidTile(), Terraria.Main.tile, Terraria.Main.tileDungeon, Terraria.WorldGen.TileRunner(), Terraria.Tile.type, Terraria.Tile.wall, and Terraria.Main.wallDungeon.
Referenced by Terraria.WorldGen.AddPasses(), and Terraria.WorldGen.GenerateSkyBlockWorld().