Terraria Decompiled: Terraria.WorldGen.SecretSeed.DoPaintEverythingNegative
DoPaintEverythingNegative()
static void Terraria.WorldGen.SecretSeed.DoPaintEverythingNegative () inline static
Definition at line 88627 of file WorldGen.cs.
            {
                bool paintEverythingNegativeJustUnderground = WorldGen.SecretSeed.Variations.paintEverythingNegativeJustUnderground;
                bool paintEverythingNegativeJustSomeThings = WorldGen.SecretSeed.Variations.paintEverythingNegativeJustSomeThings;
                int num = 0;
                for (int i = 0; i < Main.maxTilesX; i++)
                {
                    if (paintEverythingNegativeJustUnderground)
                    {
                        num = (int)Main.worldSurface - WorldGen.genRand.Next(3);
                    }
                    for (int j = num; j < Main.maxTilesY - 30; j++)
                    {
                        if (paintEverythingNegativeJustSomeThings)
{
                            if (Main.tileDungeon[(int)Main.tile[i, j].type])
{
                                Main.tile[i, j].color(30);
                            }
                            if (TileID.Sets.CrackedBricks[(int)Main.tile[i, j].type])
{
                                Main.tile[i, j].color(30);
                            }
                            if (Main.wallDungeon[(int)Main.tile[i, j].wall])
{
                                Main.tile[i, j].wallColor(30);
                                if (Main.tile[i, j].type == 19)
{
                                    Main.tile[i, j].color(30);
                                }
                            }
                            if (TileID.Sets.Clouds[(int)Main.tile[i, j].type])
{
                                Main.tile[i, j].color(30);
                            }
                            if (Main.tile[i, j].wall == 73)
{
                                Main.tile[i, j].wallColor(30);
                            }
                            if (Main.tile[i, j].type == 192 || Main.tile[i, j].type == 384)
{
                                Main.tile[i, j].color(30);
                                if (Main.tile[i, j + 1].type == 52 || Main.tile[i, j + 1].type == 382 || Main.tile[i, j + 1].type == 62)
{
                                    int num2 = j + 1;
                                    while (num2 < Main.maxTilesY && Main.tile[i, num2].active() && (Main.tile[i, num2].type == 52 || Main.tile[i, num2].type == 382 || Main.tile[i, num2].type == 62))
{
                                        Main.tile[i, num2].color(30);
                                        num2++;
                                    }
                                }
                                if (Main.tile[i, j - 1].type == 186 || Main.tile[i, j - 1].type == 187)
{
                                    Main.tile[i, j - 1].color(30);
                                    if (Main.tile[i, j - 2].type == 186 || Main.tile[i, j - 2].type == 187)
{
                                        Main.tile[i, j - 2].color(30);
                                    }
                                }
                            }
                            if (Main.tile[i, j].wall == 60)
{
                                Main.tile[i, j].wallColor(30);
                            }
                        }
                        else
{
                            Main.tile[i, j].color(30);
                            Main.tile[i, j].wallColor(30);
                        }
                    }
                }
            }
References Terraria.Tile.active(), Terraria.ID.TileID.Sets.Clouds, Terraria.Tile.color(), Terraria.ID.TileID.Sets.CrackedBricks, Terraria.WorldGen.genRand, int, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.SecretSeed.Variations.paintEverythingNegativeJustSomeThings, Terraria.WorldGen.SecretSeed.Variations.paintEverythingNegativeJustUnderground, Terraria.Main.tile, Terraria.Main.tileDungeon, Terraria.Tile.type, Terraria.Tile.wall, Terraria.Tile.wallColor(), Terraria.Main.wallDungeon, and Terraria.Main.worldSurface.
Referenced by Terraria.WorldGen.SecretSeed.FinalizeSecretSeeds().