Terraria Decompiled: Terraria.WorldGen.SecretSeed.DoExtraLiquidFinish
DoExtraLiquidFinish()
static void Terraria.WorldGen.SecretSeed.DoExtraLiquidFinish () inline static
Definition at line 89661 of file WorldGen.cs.
            {
                if (WorldGen.skyblockWorldGen)
                {
                    return;
                }
                bool flag = Main.tileSolid[225];
                Main.tileSolid[225] = true;
                Liquid.QuickWater(-2, -1, -1);
                Main.tileSolid[225] = flag;
                for (int i = 0; i < Main.maxTilesX; i++)
                {
                    for (int j = 0; j < Main.maxTilesY; j++)
                    {
                        if (Main.tile[i, j].type == 518)
{
                            WorldGen.SquareTileFrame(i, j, true);
                        }
                        if (Main.tile[i, j].fullbrightBlock())
{
                            Main.tile[i, j].liquid = 0;
                            Main.tile[i, j].fullbrightBlock(false);
                            if (Main.tile[i, j].type == 375 || Main.tile[i, j].type == 373 || Main.tile[i, j].type == 374 || Main.tile[i, j].type == 709)
{
                                Main.tile[i, j].active(false);
                            }
                        }
                        if (j >= Main.UnderworldLayer)
{
                            if (Main.tile[i, j].liquid > 0)
{
                                Main.tile[i, j].lava(true);
                            }
                            if (Main.tile[i, j].type == 56 || Main.tile[i, j].type == 230 || Main.tile[i, j].type == 659)
{
                                Main.tile[i, j].active(false);
                            }
                        }
                    }
                }
            }
References Terraria.Tile.active(), Terraria.Tile.fullbrightBlock(), Terraria.Tile.lava(), Terraria.Tile.liquid, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Liquid.QuickWater(), Terraria.WorldGen.skyblockWorldGen, Terraria.WorldGen.SquareTileFrame(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Tile.type, and Terraria.Main.UnderworldLayer.
Referenced by Terraria.WorldGen.SecretSeed.FinalizeSecretSeeds().