Terraria Decompiled: Terraria.WorldGen.SecretSeed.DoAddTeleporters_ClearArea
DoAddTeleporters_ClearArea()
static void Terraria.WorldGen.SecretSeed.DoAddTeleporters_ClearArea (int tileX, int tileY) inline static
Definition at line 89864 of file WorldGen.cs.
            {
                Tile tile = Main.tile[tileX - 1, tileY];
                Tile tile2 = Main.tile[tileX, tileY];
                Tile tile3 = Main.tile[tileX + 1, tileY];
                if (tile.active() && WorldGen.CanKillTile(tileX - 1, tileY))
                {
                    tile.ClearTile();
                    tile.ClearBlockPaintAndCoating();
                }
                if (tile2.active() && WorldGen.CanKillTile(tileX, tileY))
                {
                    tile2.ClearTile();
                    tile2.ClearBlockPaintAndCoating();
                }
                if (tile3.active() && WorldGen.CanKillTile(tileX + 1, tileY))
                {
                    tile3.ClearTile();
                    tile3.ClearBlockPaintAndCoating();
                }
                ushort type = Main.tile[tileX, tileY + 1].type;
                Tile tile4 = Main.tile[tileX - 1, tileY + 1];
                Tile tile5 = Main.tile[tileX, tileY + 1];
                Tile tile6 = Main.tile[tileX + 1, tileY + 1];
                if (!tile4.active() || tile4.slope() != 0 || tile4.halfBrick())
                {
                    if (!tile4.active())
                    {
                        tile4.type = type;
                        tile4.active(true);
                    }
                    tile4.slope(0);
                    tile4.halfBrick(false);
                }
                if (!tile5.active() || tile5.slope() != 0 || tile5.halfBrick())
                {
                    if (!tile5.active())
                    {
                        tile5.type = type;
                        tile5.active(true);
                    }
                    tile5.slope(0);
                    tile5.halfBrick(false);
                }
                if (!tile6.active() || tile6.slope() != 0 || tile6.halfBrick())
                {
                    if (!tile6.active())
                    {
                        tile6.type = type;
                        tile6.active(true);
                    }
                    tile6.slope(0);
                    tile6.halfBrick(false);
                }
            }
References Terraria.Tile.active(), Terraria.WorldGen.CanKillTile(), Terraria.Tile.ClearBlockPaintAndCoating(), Terraria.Tile.ClearTile(), Terraria.Tile.halfBrick(), Terraria.Tile.slope(), Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.SecretSeed.DoAddTeleporters().