Terraria Decompiled: Terraria.WorldGen.SecretSeed.DoRoundLandMasses
DoRoundLandMasses()
static void Terraria.WorldGen.SecretSeed.DoRoundLandMasses () inline static
Definition at line 90903 of file WorldGen.cs.
            {
                int num = Main.maxTilesX * 10;
                int num2 = 25;
                GenVars.landmassData.Clear();
                for (int i = 0; i < 3; i++)
                {
                    int num3 = WorldGen.genRand.Next(235, 266);
                    Vector2 vector = new Vector2((float)(115 + WorldGen.genRand.Next(20)), (float)((int)Main.worldSurface - 100 + WorldGen.genRand.Next(-20, 21)));
                    if (i == 1)
                    {
                        vector = new Vector2((float)(Main.maxTilesX - 115 - WorldGen.genRand.Next(20)), (float)((int)Main.worldSurface - 100 + WorldGen.genRand.Next(-20, 21)));
                    }
                    else if (i == 2)
                    {
                        vector = new Vector2((float)(Main.maxTilesX / 2 + WorldGen.genRand.Next(-50, 51)), (float)((int)Main.worldSurface - WorldGen.genRand.Next(101)));
                        num3 = WorldGen.genRand.Next(100, 201);
                    }
                    LandmassData landmassData = new LandmassData
                    {
                        DataType = LandmassDataType.RoundLandmass,
                        Position = vector,
                        RadiusOrHalfSize = num3
                    };
                    GenVars.landmassData.Add(landmassData);
                    int num4 = (int)vector.X - num3;
                    while ((float)num4 <= vector.X + (float)num3)
                    {
                        int num5 = (int)vector.Y - num3;
                        while ((float)num5 <= vector.Y + (float)num3)
{
                            if (WorldGen.InWorld(num4, num5, 0) && Vector2.Distance(vector, new Vector2((float)num4, (float)num5)) < (float)num3)
{
                                Main.tile[num4, num5].fullbrightBlock(true);
                            }
                            num5++;
                        }
                        num4++;
                    }
                }
                for (int j = 0; j < num; j++)
                {
                    Vector2 vector2 = new Vector2((float)WorldGen.genRand.Next(50, Main.maxTilesX - 50), (float)WorldGen.genRand.Next(50, Main.maxTilesY - 50));
                    int num6 = 10;
                    int num7 = WorldGen.genRand.Next(30, 170);
                    if (j > num / 2)
                    {
                        num7 /= 2;
                        num6 /= 2;
                    }
                    bool flag = false;
                    int num8 = (int)vector2.X - num7 - num6;
                    while ((float)num8 <= vector2.X + (float)num7 + (float)num6)
                    {
                        int num9 = (int)vector2.Y - num7 - num6;
                        while ((float)num9 <= vector2.Y + (float)num7 + (float)num6)
{
                            if (WorldGen.InWorld(num8, num9, 0) && Vector2.Distance(vector2, new Vector2((float)num8, (float)num9)) < (float)(num7 + num6) && Main.tile[num8, num9].fullbrightBlock())
{
                                flag = true;
                                break;
                            }
                            num9++;
                        }
                        if (flag)
{
                            break;
                        }
                        num8++;
                    }
                    if (!flag)
                    {
                        LandmassData landmassData2 = new LandmassData
{
                            DataType = LandmassDataType.RoundLandmass,
                            Position = vector2,
                            RadiusOrHalfSize = num7
                        };
                        GenVars.landmassData.Add(landmassData2);
                        int num10 = (int)vector2.X - num7;
                        while ((float)num10 <= vector2.X + (float)num7)
{
                            int num11 = (int)vector2.Y - num7;
                            while ((float)num11 <= vector2.Y + (float)num7)
{
                                if (WorldGen.InWorld(num10, num11, 0) && Vector2.Distance(vector2, new Vector2((float)num10, (float)num11)) < (float)num7)
{
                                    Main.tile[num10, num11].fullbrightBlock(true);
                                }
                                num11++;
                            }
                            num10++;
                        }
                    }
                }
                for (int k = num2; k < Main.maxTilesX - num2; k++)
                {
                    for (int l = num2; l < Main.maxTilesY - 100; l++)
                    {
                        if (!Main.tile[k, l].fullbrightBlock())
{
                            Main.tile[k, l].active(false);
                            Main.tile[k, l].wall = 0;
                        }
                    }
                }
                for (int m = 0; m < Main.maxTilesX; m++)
                {
                    for (int n = 0; n < Main.maxTilesY; n++)
                    {
                        Main.tile[m, n].fullbrightBlock(false);
                    }
                }
            }
References Terraria.Tile.active(), System.Collections.Generic.List< T >.Add(), System.Collections.Generic.List< T >.Clear(), Microsoft.Xna.Framework.Vector2.Distance(), Terraria.Tile.fullbrightBlock(), Terraria.WorldGen.genRand, int, Terraria.WorldGen.InWorld(), Terraria.WorldBuilding.GenVars.landmassData, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.tile, Terraria.Tile.wall, Terraria.Main.worldSurface, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.WorldGen.AddPasses().