Terraria Decompiled: Terraria.WorldGen.SecretSeed.DoCoatEverythingEcho
DoCoatEverythingEcho()
static void Terraria.WorldGen.SecretSeed.DoCoatEverythingEcho () inline static
Definition at line 88702 of file WorldGen.cs.
            {
                bool coatEverythingEchoJustSomeThings = WorldGen.SecretSeed.Variations.coatEverythingEchoJustSomeThings;
                bool coatEverythingJustInnerBlocks = WorldGen.SecretSeed.Variations.coatEverythingJustInnerBlocks;
                for (int i = 0; i < Main.maxTilesX; i++)
                {
                    for (int j = 0; j < Main.maxTilesY; j++)
                    {
                        if (coatEverythingEchoJustSomeThings)
{
                            if (Main.tile[i, j].type == 48 || Main.tile[i, j].type == 232 || Main.tile[i, j].type == 137 || (TileID.Sets.Boulders[(int)Main.tile[i, j].type] && Main.tile[i, j].type != 665 && Main.tile[i, j].type != 711) || Main.tile[i, j].type == 141 || Main.tile[i, j].type == 135 || Main.tile[i, j].type == 443)
{
                                Main.tile[i, j].invisibleBlock(true);
                            }
                        }
                        else if (coatEverythingJustInnerBlocks)
{
                            bool flag = true;
                            for (int k = i - 1; k <= i + 1; k++)
{
                                for (int l = j - 1; l <= j + 1; l++)
{
                                    if (!WorldGen.SolidTile3(k, l))
{
                                        flag = false;
                                    }
                                }
                            }
                            if (flag)
{
                                Main.tile[i, j].invisibleBlock(true);
                                Main.tile[i, j].invisibleWall(true);
                            }
                            if (!WorldGen.SecretSeed.errorWorld.Enabled)
{
                                Main.tile[i, j].invisibleWall(true);
                            }
                        }
                        else
{
                            Main.tile[i, j].invisibleBlock(true);
                            Main.tile[i, j].invisibleWall(true);
                        }
                    }
                }
                if (coatEverythingJustInnerBlocks && WorldGen.SecretSeed.errorWorld.Enabled)
                {
                    for (int m = 0; m < Main.maxTilesX; m++)
                    {
                        for (int n = 0; n < Main.maxTilesY; n++)
{
                            if (Main.tile[m, n].invisibleBlock())
{
                                Main.tile[m, n].active(false);
                            }
                            if (Main.tile[m, n].invisibleWall())
{
                                Main.tile[m, n].wall = 0;
                            }
                            if (WorldGen.SolidTile3(m, n))
{
                                Main.tile[m, n].wall = 0;
                            }
                        }
                    }
                }
                for (int num = 0; num < 8000; num++)
                {
                    Chest chest = Main.chest[num];
                    if (chest == null)
                    {
                        break;
                    }
                    if (WorldGen.genRand.Next(25) == 0 && chest.item[1].stack != 0)
                    {
                        for (int num2 = 1; num2 < chest.maxItems; num2++)
{
                            if (chest.item[num2].stack == 0)
{
                                chest.item[num2].SetDefaults(4409, null);
                                break;
                            }
                        }
                    }
                }
            }
References Terraria.Tile.active(), Terraria.ID.TileID.Sets.Boulders, Terraria.Main.chest, Terraria.WorldGen.SecretSeed.Variations.coatEverythingEchoJustSomeThings, Terraria.WorldGen.SecretSeed.Variations.coatEverythingJustInnerBlocks, Terraria.WorldGen.SecretSeed.errorWorld, Terraria.WorldGen.genRand, Terraria.Tile.invisibleBlock(), Terraria.Tile.invisibleWall(), Terraria.Chest.item, Terraria.Chest.maxItems, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Item.SetDefaults(), Terraria.WorldGen.SolidTile3(), Terraria.Item.stack, Terraria.Main.tile, Terraria.Tile.type, and Terraria.Tile.wall.
Referenced by Terraria.WorldGen.SecretSeed.FinalizeSecretSeeds().