Terraria Decompiled: Terraria.WorldGen.SecretSeed.DoRainbowStuff
DoRainbowStuff()
static void Terraria.WorldGen.SecretSeed.DoRainbowStuff () inline static
Definition at line 90742 of file WorldGen.cs.
            {
                Main.tileSolid[379] = false;
                bool flag = !WorldGen.SecretSeed.extraLiquid.Enabled || !WorldGen.SecretSeed.roundLandmasses.Enabled;
                for (int i = 0; i < Main.maxTilesX; i++)
                {
                    for (int j = 0; j < Main.maxTilesY; j++)
                    {
                        if (Main.tile[i, j].type == 189)
{
                            Main.tile[i, j].type = 719;
                        }
                        if (Main.tile[i, j].type == 4)
{
                            Main.tile[i, j].frameY = 308;
                            Main.tile[i, j].ClearBlockPaintAndCoating();
                        }
                        if (flag && Main.tile[i, j].halfBrick())
{
                            if (Main.tile[i - 1, j].liquid == 255 && Main.tile[i - 1, j].liquidType() == 0 && (!Main.tile[i + 1, j].active() || Main.tile[i + 1, j].halfBrick()) && Main.tile[i + 1, j].liquid == 0)
{
                                Main.tile[i, j].type = 160;
                                Main.tile[i, j].ClearBlockPaintAndCoating();
                            }
                            if (Main.tile[i + 1, j].liquid == 255 && Main.tile[i + 1, j].liquidType() == 0 && (!Main.tile[i - 1, j].active() || Main.tile[i - 1, j].halfBrick()) && Main.tile[i - 1, j].liquid == 0)
{
                                Main.tile[i, j].type = 160;
                                Main.tile[i, j].ClearBlockPaintAndCoating();
                            }
                        }
                        if (Main.tile[i, j].type == 138 && Main.tile[i, j].frameX == 0 && Main.tile[i, j].frameY == 0 && WorldGen.genRand.Next(4) == 0)
{
                            Main.tile[i, j].type = 711;
                            Main.tile[i + 1, j].type = 711;
                            Main.tile[i, j + 1].type = 711;
                            Main.tile[i + 1, j + 1].type = 711;
                            Main.tile[i, j].ClearBlockPaintAndCoating();
                            Main.tile[i + 1, j].ClearBlockPaintAndCoating();
                            Main.tile[i, j + 1].ClearBlockPaintAndCoating();
                            Main.tile[i + 1, j + 1].ClearBlockPaintAndCoating();
                        }
                        if (Main.tile[i, j].type == 202)
{
                            Main.tile[i, j].type = 692;
                            Main.tile[i, j].ClearBlockPaintAndCoating();
                        }
                        if (Main.tile[i, j].wall == 82)
{
                            Main.tile[i, j].wall = 346;
                            Main.tile[i, j].ClearBlockPaintAndCoating();
                        }
                        if (Main.tile[i, j].type == 91 && Main.tile[i, j].frameY % 54 == 0 && (WorldGen.genRand.Next(5) == 0 || ((double)j < Main.worldSurface && WorldGen.genRand.Next(2) == 0)))
{
                            Main.tile[i, j].frameX = 1206;
                            Main.tile[i, j].frameY = 54;
                            Main.tile[i, j + 1].frameX = 1206;
                            Main.tile[i, j + 1].frameY = 72;
                            Main.tile[i, j + 2].frameX = 1206;
                            Main.tile[i, j + 2].frameY = 90;
                            Main.tile[i, j].ClearBlockPaintAndCoating();
                            Main.tile[i, j + 1].ClearBlockPaintAndCoating();
                            Main.tile[i, j + 2].ClearBlockPaintAndCoating();
                        }
                        if (TileID.Sets.Conversion.Moss[(int)Main.tile[i, j].type])
{
                            Main.tile[i, j].type = 627;
                            Main.tile[i, j].ClearBlockPaintAndCoating();
                        }
                        else if (Main.tile[i, j].type == 184)
{
                            Main.tile[i, j].frameX = 220;
                            Main.tile[i, j].ClearBlockPaintAndCoating();
                        }
                    }
                }
                int num = Main.maxTilesX * 2;
                if (WorldGen.skyblockWorldGen)
                {
                    num /= 2;
                }
                else if (!flag)
                {
                    num *= 2;
                }
                int num2 = 40;
                for (int k = 0; k < num; k++)
                {
                    int num3 = WorldGen.genRand.Next(num2, Main.maxTilesX - num2);
                    int num4 = WorldGen.genRand.Next(num2, Main.maxTilesY - num2);
                    if (!Main.tile[num3, num4].active())
                    {
                        while (!Main.tile[num3, num4].active())
{
                            num4--;
                            if (!WorldGen.InWorld(num3, num4, num2))
{
                                break;
                            }
                        }
                        num4++;
                        if (!Main.tile[num3 + 1, num4].active() && Main.tile[num3 + 1, num4].type != 162 && WorldGen.SolidTile(num3 - 1, num4 - 1, false) && WorldGen.SolidTile(num3, num4 - 1, false) && Main.tile[num3 - 1, num4 - 1].type != 48 && Main.tile[num3, num4 - 1].type != 48 && Main.tile[num3 - 1, num4 - 1].type != 232 && Main.tile[num3, num4 - 1].type != 232 && !WorldGen.IsTileNearby(num3, num4, 126, 20) && WorldGen.PlaceTile(num3, num4, 126, false, false, -1, 0))
{
                            Main.tile[num3 - 1, num4].ClearBlockPaintAndCoating();
                            Main.tile[num3, num4].ClearBlockPaintAndCoating();
                            Main.tile[num3 - 1, num4 + 1].ClearBlockPaintAndCoating();
                            Main.tile[num3, num4 + 1].ClearBlockPaintAndCoating();
                        }
                    }
                }
                for (int l = 0; l < 8000; l++)
                {
                    Chest chest = Main.chest[l];
                    if (chest == null)
                    {
                        break;
                    }
                    if (WorldGen.genRand.Next(3) == 0 && chest.item[1].stack != 0)
                    {
                        int m = 1;
                        while (m < chest.maxItems)
{
                            if (chest.item[m].stack == 0)
{
                                chest.item[m].SetDefaults((int)WorldGen.genRand.NextFromList(new short[] { 3556, 2870, 1067, 1066, 5075, 4469 }), null);
                                if (chest.item[m].dye > 0)
{
                                    chest.item[m].stack = 3;
                                    break;
                                }
                                break;
                            }
                            else
{
                                m++;
                            }
                        }
                    }
                }
                WorldGen.OverGrownDungeonWithRainbowMoss();
                Main.tileSolid[379] = true;
            }
References Terraria.Tile.active(), Terraria.Main.chest, Terraria.Tile.ClearBlockPaintAndCoating(), Terraria.Item.dye, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.genRand, Terraria.Tile.halfBrick(), Terraria.WorldGen.InWorld(), Terraria.WorldGen.IsTileNearby(), Terraria.Chest.item, Terraria.Tile.liquid, Terraria.Tile.liquidType(), Terraria.Chest.maxItems, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.ID.TileID.Sets.Conversion.Moss, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.OverGrownDungeonWithRainbowMoss(), Terraria.WorldGen.PlaceTile(), Terraria.WorldGen.SecretSeed.roundLandmasses, Terraria.Item.SetDefaults(), Terraria.WorldGen.skyblockWorldGen, Terraria.WorldGen.SolidTile(), Terraria.Item.stack, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Tile.type, Terraria.Tile.wall, and Terraria.Main.worldSurface.
Referenced by Terraria.WorldGen.SecretSeed.FinalizeSecretSeeds().