Terraria Decompiled: Terraria.WorldGen.SecretSeed.DoErrorWorldFinish
DoErrorWorldFinish()
static void Terraria.WorldGen.SecretSeed.DoErrorWorldFinish () inline static
Definition at line 89106 of file WorldGen.cs.
            {
                int num = Main.maxTilesX * 2;
                for (int i = 0; i < num; i++)
                {
                    int num2 = WorldGen.genRand.Next(8000);
                    int num3 = 100000;
                    while (Main.chest[num2] == null || Main.chest[num2].item[0].type == 0)
                    {
                        num2 = WorldGen.genRand.Next(8000);
                        if (num3-- <= 0)
{
                            return;
                        }
                    }
                    int num4 = WorldGen.genRand.Next(Main.chest[num2].item.Length);
                    num3 = 100000;
                    while (ItemID.Sets.ErrorWorldChestSwapImmunity[Main.chest[num2].item[num4].type])
                    {
                        num4 = WorldGen.genRand.Next(Main.chest[num2].item.Length);
                        if (num3-- <= 0)
{
                            return;
                        }
                    }
                    int num5 = WorldGen.genRand.Next(8000);
                    while (Main.chest[num5] == null || Main.chest[num5].item[0].type == 0)
                    {
                        num5 = WorldGen.genRand.Next(8000);
                    }
                    int num6 = WorldGen.genRand.Next(Main.chest[num5].item.Length);
                    while (ItemID.Sets.ErrorWorldChestSwapImmunity[Main.chest[num5].item[num6].type])
                    {
                        num6 = WorldGen.genRand.Next(Main.chest[num5].item.Length);
                    }
                    if (!WorldGen.SecretSeed.Variations.errorWorldBalancedChests || Main.chest[num2].item[num4].rare == Main.chest[num5].item[num6].rare)
                    {
                        Item item = Main.chest[num2].item[num4].Clone();
                        Item item2 = Main.chest[num5].item[num6].Clone();
                        Main.chest[num2].item[num4] = item2;
                        Main.chest[num5].item[num6] = item;
                    }
                }
                int num7 = 20;
                for (int j = num7; j < Main.maxTilesX - num7; j++)
                {
                    for (int k = num7; k < Main.maxTilesY - num7; k++)
                    {
                        if (TileID.Sets.CrackedBricks[(int)Main.tile[j, k].type])
{
                            Main.tile[j, k].invisibleBlock(true);
                        }
                        if (TileID.Sets.Conversion.Moss[(int)Main.tile[j, k].type] && Main.tile[j, k].type != 381 && WorldGen.genRand.Next(WorldGen.SecretSeed.Variations.errorWorldAdjustment(5.0)) == 0)
{
                            Main.tile[j, k].type = WorldGen.genRand.NextFromList(new ushort[] { 539, 536, 534, 625, 627 });
                        }
                        if ((double)k > Main.worldSurface && Main.tile[j, k].wall == 73)
{
                            Main.tile[j, k].wall = 0;
                        }
                        if (Main.tile[j, k].type == 501)
{
                            if (!WorldGen.CanKillTile(j, k))
{
                                Main.tile[j, k].invisibleBlock(true);
                            }
                            else
{
                                Main.tile[j, k].active(false);
                            }
                        }
                        if (Main.tile[j, k].wall == 238)
{
                            Main.tile[j, k].wall = 0;
                        }
                        if (Main.tile[j, k].type == 137 && !Main.tile[j, k].wire())
{
                            Main.tile[j, k].frameX = (short)(WorldGen.genRand.Next(6) * 18);
                        }
                        if (Main.tile[j, k].type == 28 && WorldGen.genRand.Next(5) == 0)
{
                            Main.tile[j, k].active(false);
                        }
                        if (WorldGen.genRand.Next(WorldGen.SecretSeed.Variations.errorWorldAdjustment(7.0)) == 0 && (Main.tile[j, k].type == 48 || Main.tile[j, k].type == 232 || Main.tile[j, k].type == 21 || Main.tile[j, k].type == 467 || Main.tile[j, k].type == 28 || Main.tile[j, k].type == 639 || Main.tile[j, k].type == 12 || Main.tile[j, k].type == 484))
{
                            Main.tile[j, k].invisibleBlock(true);
                        }
                        if (WorldGen.genRand.Next(WorldGen.SecretSeed.Variations.errorWorldAdjustment(15.0)) == 0 && WorldGen.SolidTile3(j, k) && !Main.tileFrameImportant[(int)Main.tile[j, k].type] && Main.tile[j, k - 1].active() && !WorldGen.SolidTile3(j, k - 1) && Main.tile[j, k - 1].type != 237 && Main.tile[j, k - 1].type != 231 && Main.tile[j, k - 1].type != 355 && Main.tile[j, k - 1].type != 354 && Main.tile[j, k - 1].type != 26 && Main.tile[j, k - 1].type != 77 && Main.tile[j, k - 1].type != 642 && Main.tile[j, k - 1].type != 506 && Main.tile[j, k - 1].type != 377)
{
                            if (WorldGen.CanKillTile(j, k))
{
                                Main.tile[j, k].active(false);
                            }
                            else
{
                                Main.tile[j, k].invisibleBlock(true);
                            }
                        }
                        if (WorldGen.genRand.Next(WorldGen.SecretSeed.Variations.errorWorldAdjustment(10000.0)) == 0)
{
                            Main.tile[j, k].color(30);
                        }
                        if (WorldGen.genRand.Next(WorldGen.SecretSeed.Variations.errorWorldAdjustment(10000.0)) == 0)
{
                            Main.tile[j, k].wallColor(30);
                        }
                        if (WorldGen.genRand.Next(WorldGen.SecretSeed.Variations.errorWorldAdjustment(50000.0)) == 0)
{
                            Main.tile[j, k].fullbrightBlock(true);
                        }
                        if (WorldGen.genRand.Next(WorldGen.SecretSeed.Variations.errorWorldAdjustment(50000.0)) == 0)
{
                            Main.tile[j, k].fullbrightWall(true);
                        }
                        if (WorldGen.genRand.Next(WorldGen.SecretSeed.Variations.errorWorldAdjustment(250000.0)) == 0)
{
                            Main.tile[j, k].invisibleBlock(true);
                        }
                    }
                }
                for (int l = num7; l < Main.maxTilesX - num7; l++)
                {
                    for (int m = num7; m < Main.maxTilesY - num7; m++)
                    {
                        if (Main.tile[l, m].active() && Main.tile[l, m].type == 137 && !Main.tile[l, m].wire())
{
                            bool flag = false;
                            int num8 = 1;
                            while (num8 < 50 && !flag)
{
                                int num9 = l - num8;
                                while (num9 <= l + num8 && !flag)
{
                                    int num10 = m - num8;
                                    while (num10 <= m + num8 && !flag)
{
                                        if (WorldGen.InWorld(num9, num10, 0) && Main.tile[num9, num10].wire())
{
                                            flag = true;
                                            int n = num9;
                                            int num11 = num10;
                                            if (Math.Abs(n - l) < Math.Abs(num11 - m))
{
                                                while (n < l)
{
                                                    n++;
                                                    Main.tile[n, num11].wire(true);
                                                }
                                                while (n > l)
{
                                                    n--;
                                                    Main.tile[n, num11].wire(true);
                                                }
                                                while (num11 < m)
{
                                                    num11++;
                                                    Main.tile[n, num11].wire(true);
                                                }
                                                while (num11 > m)
{
                                                    num11--;
                                                    Main.tile[n, num11].wire(true);
                                                }
                                            }
                                            else
{
                                                while (num11 < m)
{
                                                    num11++;
                                                    Main.tile[n, num11].wire(true);
                                                }
                                                while (num11 > m)
{
                                                    num11--;
                                                    Main.tile[n, num11].wire(true);
                                                }
                                                while (n < l)
{
                                                    n++;
                                                    Main.tile[n, num11].wire(true);
                                                }
                                                while (n > l)
{
                                                    n--;
                                                    Main.tile[n, num11].wire(true);
                                                }
                                            }
                                        }
                                        num10++;
                                    }
                                    num9++;
                                }
                                num8++;
                            }
                        }
                    }
                }
                num = Main.maxTilesX / 3 / WorldGen.SecretSeed.Variations.errorWorldAdjustment(1.0);
                for (int num12 = 0; num12 < num; num12++)
                {
                    int num13 = WorldGen.genRand.Next(50, Main.maxTilesX - 50);
                    int num14 = WorldGen.genRand.Next((int)Main.worldSurface, Main.maxTilesY - 50);
                    if (!Main.tile[num13, num14].active() && Main.tile[num13, num14].liquid == 0 && !Main.tile[num13 + 1, num14].active() && Main.tile[num13 + 1, num14].liquid == 0 && !Main.tile[num13, num14 + 1].active() && Main.tile[num13, num14 + 1].liquid == 0 && !Main.tile[num13 + 1, num14 + 1].active() && Main.tile[num13 + 1, num14 + 1].liquid == 0)
                    {
                        int num15 = WorldGen.genRand.Next(4);
                        for (int num16 = num13; num16 <= num13 + 1; num16++)
{
                            for (int num17 = num14; num17 <= num14 + 1; num17++)
{
                                Main.tile[num16, num17].active(true);
                                Main.tile[num16, num17].type = 379;
                                Main.tile[num16, num17].liquid = byte.MaxValue;
                                Main.tile[num16, num17].liquidType(num15);
                                if (num15 == 0)
{
                                    Main.tile[num16, num17].color(9);
                                }
                                else if (num15 == 1)
{
                                    Main.tile[num16, num17].color(1);
                                }
                                else if (num15 == 2)
{
                                    Main.tile[num16, num17].color(2);
                                }
                                else if (num15 == 3)
{
                                    Main.tile[num16, num17].color(10);
                                }
                            }
                        }
                    }
                }
                if (!WorldGen.SecretSeed.worldIsInfected.Enabled && !WorldGen.SecretSeed.vampirism.Enabled)
                {
                    for (int num18 = 0; num18 < Main.maxNPCs; num18++)
                    {
                        if (Main.npc[num18].active && Main.npc[num18].townNPC && Main.npc[num18].type != 37)
{
                            int num19 = NPC.NewNPC(new EntitySource_WorldGen(), Main.spawnTileX * 16, Main.spawnTileY * 16, 37, 0, 0f, 0f, 0f, 0f, 255);
                            Main.npc[num19].homeTileX = Main.spawnTileX;
                            Main.npc[num19].homeTileY = Main.spawnTileY;
                            Main.npc[num19].direction = 1;
                            Main.npc[num19].homeless = true;
                            Main.npc[num19].position = Main.npc[num18].position;
                            Main.npc[num18].active = false;
                        }
                    }
                }
            }
References System.Math.Abs(), Terraria.NPC.active, Terraria.Tile.active(), Terraria.WorldGen.CanKillTile(), Terraria.Main.chest, Terraria.Item.Clone(), Terraria.Tile.color(), Terraria.ID.TileID.Sets.CrackedBricks, Terraria.Entity.direction, Terraria.WorldGen.SecretSeed.Variations.errorWorldAdjustment(), Terraria.WorldGen.SecretSeed.Variations.errorWorldBalancedChests, Terraria.ID.ItemID.Sets.ErrorWorldChestSwapImmunity, Terraria.Tile.frameX, Terraria.Tile.fullbrightBlock(), Terraria.Tile.fullbrightWall(), Terraria.WorldGen.genRand, Terraria.NPC.homeless, Terraria.NPC.homeTileX, Terraria.NPC.homeTileY, int, Terraria.Tile.invisibleBlock(), Terraria.WorldGen.InWorld(), System.item, Terraria.Chest.item, Terraria.Tile.liquid, Terraria.Tile.liquidType(), Terraria.Main.maxNPCs, Terraria.Main.maxTilesX, Terraria.ID.TileID.Sets.Conversion.Moss, Terraria.NPC.NewNPC(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.npc, Terraria.Entity.position, Terraria.Item.rare, Terraria.WorldGen.SolidTile3(), Terraria.Main.spawnTileX, Terraria.Main.spawnTileY, Terraria.Main.tile, Terraria.Main.tileFrameImportant, Terraria.NPC.townNPC, Terraria.Item.type, Terraria.NPC.type, Terraria.Tile.type, Terraria.WorldGen.SecretSeed.vampirism, Terraria.Tile.wall, Terraria.Tile.wallColor(), Terraria.Tile.wire(), Terraria.WorldGen.SecretSeed.worldIsInfected, and Terraria.Main.worldSurface.
Referenced by Terraria.WorldGen.SecretSeed.FinalizeSecretSeeds().