Terraria Decompiled: Terraria.WorldGen.SecretSeed.DoErrorWorldShuffleBlocks
DoErrorWorldShuffleBlocks()
static void Terraria.WorldGen.SecretSeed.DoErrorWorldShuffleBlocks () inline static
Definition at line 88886 of file WorldGen.cs.
            {
                int num = 30;
                int num2 = 50;
                int num3 = Main.maxTilesX * 10 / WorldGen.SecretSeed.Variations.errorWorldAdjustment(1.0);
                if (WorldGen.skyblockWorldGen)
                {
                    num3 /= 2;
                }
                for (int i = 0; i < num3; i++)
                {
                    int num4 = WorldGen.genRand.Next(num, Main.maxTilesX - num);
                    int num5 = WorldGen.genRand.Next(num + num2, Main.maxTilesY - num);
                    while (!Main.tileSolid[(int)Main.tile[num4, num5].type] || Main.tileSolidTop[(int)Main.tile[num4, num5].type] || Main.tileFrameImportant[(int)Main.tile[num4, num5].type])
                    {
                        num4 = WorldGen.genRand.Next(num, Main.maxTilesX - num);
                        num5 = WorldGen.genRand.Next(num + num2, Main.maxTilesY - num);
                    }
                    Main.tile[num4, num5].type = WorldGen.SecretSeed.DoErrorWorldGetRandomBlock();
                    if (WorldGen.skyblockWorldGen)
                    {
                        Main.tile[num4, num5].active(true);
                    }
                }
                num3 = Main.maxTilesX / 2 / WorldGen.SecretSeed.Variations.errorWorldAdjustment(1.0);
                int j = 0;
                while (j < num3)
                {
                    int num6 = WorldGen.genRand.Next(num, Main.maxTilesX - num);
                    int num7 = WorldGen.genRand.Next(num + num2, Main.maxTilesY - num);
                    while (Main.tile[num6, num7].anyShimmer() || !Main.tileSolid[(int)Main.tile[num6, num7].type] || Main.tileSolidTop[(int)Main.tile[num6, num7].type] || Main.tileFrameImportant[(int)Main.tile[num6, num7].type] || Main.tileFrameImportant[(int)Main.tile[num6, num7 - 1].type] || Main.tileFrameImportant[(int)Main.tile[num6, num7 + 1].type])
                    {
                        num6 = WorldGen.genRand.Next(num, Main.maxTilesX - num);
                        num7 = WorldGen.genRand.Next(num + num2, Main.maxTilesY - num);
                    }
                    int num8 = WorldGen.genRand.Next(num, Main.maxTilesX - num);
                    int num9 = WorldGen.genRand.Next(num + num2, Main.maxTilesY - num);
                    while (Main.tile[num8, num9].anyShimmer() || !Main.tileSolid[(int)Main.tile[num8, num9].type] || Main.tileSolidTop[(int)Main.tile[num8, num9].type] || Main.tileFrameImportant[(int)Main.tile[num8, num9].type] || Main.tileFrameImportant[(int)Main.tile[num8, num9 - 1].type] || Main.tileFrameImportant[(int)Main.tile[num8, num9 + 1].type])
                    {
                        num8 = WorldGen.genRand.Next(num, Main.maxTilesX - num);
                        num9 = WorldGen.genRand.Next(num + num2, Main.maxTilesY - num);
                    }
                    if (WorldGen.remixWorldGen)
                    {
                        if (num6 <= Main.maxTilesX / 2 - 30 || num6 >= Main.maxTilesX / 2 + 30 || num7 <= Main.UnderworldLayer)
{
                            if (num8 <= Main.maxTilesX / 2 - 30 || num8 >= Main.maxTilesX / 2 + 30 || num9 <= Main.UnderworldLayer)
{
                                goto IL_03DD;
                            }
                        }
                    }
                    else if ((num6 <= Main.maxTilesX / 2 - 30 || num6 >= Main.maxTilesX / 2 + 30 || (double)num7 >= Main.worldSurface) && (num8 <= Main.maxTilesX / 2 - 30 || num8 >= Main.maxTilesX / 2 + 30 || (double)num9 >= Main.worldSurface))
                    {
                        goto IL_03DD;
                    }
                    IL_050B:
                    j++;
                    continue;
                    IL_03DD:
                    Tile tile = new Tile(Main.tile[num6, num7]);
                    Tile tile2 = new Tile(Main.tile[num8, num9]);
                    Main.tile[num6, num7].active(tile2.active());
                    Main.tile[num6, num7].type = tile2.type;
                    Main.tile[num6, num7].color(tile2.color());
                    Main.tile[num6, num7].fullbrightBlock(tile2.fullbrightBlock());
                    Main.tile[num6, num7].invisibleBlock(tile2.invisibleBlock());
                    Main.tile[num8, num9].active(tile.active());
                    Main.tile[num8, num9].type = tile.type;
                    Main.tile[num8, num9].color(tile.color());
                    Main.tile[num8, num9].fullbrightBlock(tile.fullbrightBlock());
                    Main.tile[num8, num9].invisibleBlock(tile.invisibleBlock());
                    goto IL_050B;
                }
                num3 = Main.maxTilesX / 2 / WorldGen.SecretSeed.Variations.errorWorldAdjustment(1.0);
                for (int k = 0; k < num3; k++)
                {
                    int num10;
                    int num11;
                    if (WorldGen.genRand.Next(2) == 0)
                    {
                        num10 = WorldGen.genRand.Next(5, 21);
                        num11 = WorldGen.genRand.Next(1, 4);
                    }
                    else
                    {
                        num10 = WorldGen.genRand.Next(1, 4);
                        num11 = WorldGen.genRand.Next(5, 21);
                    }
                    int num12 = WorldGen.genRand.Next(num, Main.maxTilesX - num);
                    int num13 = WorldGen.genRand.Next(num + num2, Main.maxTilesY - num);
                    bool flag = false;
                    for (int l = num12; l < num12 + num10; l++)
                    {
                        for (int m = num13; m < num13 + num11; m++)
{
                            if (Main.tile[l, m].anyShimmer() || !Main.tileSolid[(int)Main.tile[l, m].type] || Main.tileSolidTop[(int)Main.tile[l, m].type] || Main.tileFrameImportant[(int)Main.tile[l, m].type] || Main.tileFrameImportant[(int)Main.tile[l, m - 1].type] || Main.tileFrameImportant[(int)Main.tile[l, m + 1].type])
{
                                flag = true;
                                break;
                            }
                        }
                        if (flag)
{
                            break;
                        }
                    }
                    if (!flag)
                    {
                        int num14 = WorldGen.genRand.Next(num, Main.maxTilesX - num);
                        int num15 = WorldGen.genRand.Next(num + num2, Main.maxTilesY - num);
                        flag = false;
                        for (int n = num14; n < num14 + num10; n++)
{
                            for (int num16 = num15; num16 < num15 + num11; num16++)
{
                                if (Main.tile[n, num16].anyShimmer() || !Main.tileSolid[(int)Main.tile[n, num16].type] || Main.tileSolidTop[(int)Main.tile[n, num16].type] || Main.tileFrameImportant[(int)Main.tile[n, num16].type] || Main.tileFrameImportant[(int)Main.tile[n, num16 - 1].type] || Main.tileFrameImportant[(int)Main.tile[n, num16 + 1].type])
{
                                    flag = true;
                                    break;
                                }
                            }
                            if (flag)
{
                                break;
                            }
                        }
                        if (!flag)
{
                            if (WorldGen.remixWorldGen)
{
                                if (num12 + num10 / 2 > Main.maxTilesX / 2 - 50 && num12 < Main.maxTilesX / 2 + 50 && num13 > Main.UnderworldLayer)
{
                                    goto IL_0A16;
                                }
                                if (num14 + num10 / 2 > Main.maxTilesX / 2 - 50 && num14 < Main.maxTilesX / 2 + 50 && num15 > Main.UnderworldLayer)
{
                                    goto IL_0A16;
                                }
                            }
                            else if ((num12 + num10 / 2 > Main.maxTilesX / 2 - 50 && num12 < Main.maxTilesX / 2 + 50 && (double)num13 < Main.worldSurface) || (num14 + num10 / 2 > Main.maxTilesX / 2 - 50 && num14 < Main.maxTilesX / 2 + 50 && (double)num15 < Main.worldSurface))
{
                                goto IL_0A16;
                            }
                            for (int num17 = 0; num17 < num10; num17++)
{
                                for (int num18 = 0; num18 < num11; num18++)
{
                                    Tile tile3 = new Tile(Main.tile[num12 + num17, num13 + num18]);
                                    Tile tile4 = new Tile(Main.tile[num14 + num17, num15 + num18]);
                                    Main.tile[num12 + num17, num13 + num18].active(tile4.active());
                                    Main.tile[num12 + num17, num13 + num18].type = tile4.type;
                                    Main.tile[num12 + num17, num13 + num18].color(tile4.color());
                                    Main.tile[num12 + num17, num13 + num18].fullbrightBlock(tile4.fullbrightBlock());
                                    Main.tile[num12 + num17, num13 + num18].invisibleBlock(tile4.invisibleBlock());
                                    Main.tile[num14 + num17, num15 + num18].active(tile3.active());
                                    Main.tile[num14 + num17, num15 + num18].type = tile3.type;
                                    Main.tile[num14 + num17, num15 + num18].color(tile3.color());
                                    Main.tile[num14 + num17, num15 + num18].fullbrightBlock(tile3.fullbrightBlock());
                                    Main.tile[num14 + num17, num15 + num18].invisibleBlock(tile3.invisibleBlock());
                                }
                            }
                        }
                    }
                    IL_0A16:;
                }
                num3 = Main.maxTilesX * 10 / WorldGen.SecretSeed.Variations.errorWorldAdjustment(1.0);
                for (int num19 = 0; num19 < num3; num19++)
                {
                    int num20 = WorldGen.genRand.Next(num, Main.maxTilesX - num);
                    int num21 = WorldGen.genRand.Next(num + num2, Main.maxTilesY - num);
                    while (!Main.tileSolid[(int)Main.tile[num20, num21].type] || Main.tileSolidTop[(int)Main.tile[num20, num21].type] || Main.tileFrameImportant[(int)Main.tile[num20, num21].type] || Main.tileDungeon[(int)Main.tile[num20, num21].type])
                    {
                        num20 = WorldGen.genRand.Next(num, Main.maxTilesX - num);
                        num21 = WorldGen.genRand.Next(num + num2, Main.maxTilesY - num);
                    }
                    Vector2D vector2D = default(Vector2D);
                    if (WorldGen.genRand.Next(2) == 0)
                    {
                        if (WorldGen.genRand.Next(2) == 0)
{
                            vector2D.X = -1.0;
                        }
                        else
{
                            vector2D.X = 1.0;
                        }
                    }
                    else if (WorldGen.genRand.Next(2) == 0)
                    {
                        vector2D.Y = -1.0;
                    }
                    else
                    {
                        vector2D.Y = 1.0;
                    }
                    int num22 = WorldGen.genRand.Next(5, 21);
                    int num23 = num20;
                    int num24 = num21;
                    Tile tile5 = new Tile(Main.tile[num20, num21]);
                    for (int num25 = 0; num25 < num22; num25++)
                    {
                        num23 += (int)vector2D.X;
                        num24 += (int)vector2D.Y;
                        if (Main.tile[num23, num24].active())
{
                            break;
                        }
                        Main.tile[num20, num21].slope(0);
                        Main.tile[num20, num21].halfBrick(false);
                        Main.tile[num23, num24].active(tile5.active());
                        Main.tile[num23, num24].type = tile5.type;
                        Main.tile[num23, num24].color(tile5.color());
                        Main.tile[num23, num24].fullbrightBlock(tile5.fullbrightBlock());
                        Main.tile[num23, num24].invisibleBlock(tile5.invisibleBlock());
                    }
                }
            }
References Terraria.Tile.active(), Terraria.Tile.anyShimmer(), Terraria.Tile.color(), Terraria.WorldGen.SecretSeed.DoErrorWorldGetRandomBlock(), Terraria.WorldGen.SecretSeed.Variations.errorWorldAdjustment(), Terraria.Tile.fullbrightBlock(), Terraria.WorldGen.genRand, Terraria.Tile.halfBrick(), int, Terraria.Tile.invisibleBlock(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.remixWorldGen, Terraria.WorldGen.skyblockWorldGen, Terraria.Tile.slope(), Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.Main.tileDungeon, Terraria.Main.tileFrameImportant, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Tile.type, Terraria.Main.UnderworldLayer, Terraria.Main.worldSurface, ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.WorldGen.GenerateSkyBlockWorld().