Terraria Decompiled: Terraria.WorldGen.SecretSeed.DoAddTeleporters
DoAddTeleporters()
static void Terraria.WorldGen.SecretSeed.DoAddTeleporters () inline static
Definition at line 89723 of file WorldGen.cs.
            {
                double num = (double)(Main.maxTilesX / 4200);
                int num2 = 0;
                int num3 = 10;
                int num4 = (int)(40000.0 * num);
                int num5 = 1;
                num3 = (int)((double)num3 * num);
                int num6 = 0;
                while (num6 < num4 && num2 < num3)
                {
                    bool flag = num6 > num4 / 2;
                    int num7 = WorldGen.genRand.Next(WorldGen.beachDistance, Main.maxTilesX - WorldGen.beachDistance);
                    int num8;
                    if (WorldGen.skyblockWorldGen)
                    {
                        if (num2 == 0)
{
                            num8 = 50;
                        }
                        else
{
                            num8 = WorldGen.genRand.Next(50, Main.UnderworldLayer - 100);
                        }
                    }
                    else
                    {
                        num8 = WorldGen.genRand.Next((int)Main.worldSurface, Main.UnderworldLayer - 100);
                    }
                    if (!Main.tile[num7, num8].active())
                    {
                        while (!Main.tile[num7, num8].active())
{
                            num8++;
                            if (num8 > Main.UnderworldLayer)
{
                                break;
                            }
                        }
                        if (WorldGen.SecretSeed.DoAddTeleporters_CanPutTeleporterHere(num7, num8, flag))
{
                            int num9 = 0;
                            int num10 = 0;
                            int i = 500;
                            while (i > 0)
{
                                i--;
                                num9 = WorldGen.genRand.Next(WorldGen.beachDistance, Main.maxTilesX - WorldGen.beachDistance);
                                if (WorldGen.skyblockWorldGen)
{
                                    if (num2 == 0)
{
                                        num10 = 50;
                                    }
                                    else
{
                                        num10 = WorldGen.genRand.Next(50, Main.UnderworldLayer - 100);
                                    }
                                }
                                else
{
                                    num10 = WorldGen.genRand.Next((int)Main.worldSurface, Main.UnderworldLayer - 100);
                                }
                                if (!Main.tile[num9, num10].active())
{
                                    while (!Main.tile[num9, num10].active())
{
                                        num10++;
                                        if (num10 > Main.UnderworldLayer)
{
                                            break;
                                        }
                                    }
                                    if (WorldGen.SecretSeed.DoAddTeleporters_CanPutTeleporterHere(num9, num10, flag))
{
                                        break;
                                    }
                                }
                            }
                            if (flag)
{
                                WorldGen.SecretSeed.DoAddTeleporters_ClearArea(num7, num8);
                                WorldGen.SecretSeed.DoAddTeleporters_ClearArea(num9, num10);
                            }
                            WorldGen.PlaceTile(num7, num8, 235, false, false, -1, 0);
                            if (Main.tile[num7, num8].active() && Main.tile[num7, num8].type == 235)
{
                                WorldGen.PlaceTile(num9, num10, 235, false, false, -1, 0);
                                if (Main.tile[num9, num10].active() && Main.tile[num9, num10].type == 235)
{
                                    num2++;
                                    WorldGen.PlaceTile(num7, num8 - 1, 135, true, false, -1, 4);
                                    WorldGen.AddWire(num7, num8 - 1, num5);
                                    WorldGen.AddWire(num7, num8, num5);
                                    WorldGen.PlaceTile(num9, num10 - 1, 135, true, false, -1, 4);
                                    WorldGen.AddWire(num9, num10 - 1, num5);
                                    WorldGen.AddWire(num9, num10, num5);
                                    WorldGen.AddWireFromPointToPoint(num7, num8, num9, num10, num5, false);
                                    num5++;
                                    if (num5 > 3)
{
                                        num5 = 1;
                                    }
                                }
                            }
                        }
                    }
                    num6++;
                }
            }
References Terraria.Tile.active(), Terraria.WorldGen.AddWire(), Terraria.WorldGen.AddWireFromPointToPoint(), Terraria.WorldGen.beachDistance, Terraria.WorldGen.SecretSeed.DoAddTeleporters_CanPutTeleporterHere(), Terraria.WorldGen.SecretSeed.DoAddTeleporters_ClearArea(), Terraria.WorldGen.genRand, int, Terraria.Main.maxTilesX, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.PlaceTile(), Terraria.WorldGen.skyblockWorldGen, Terraria.Main.tile, Terraria.Tile.type, Terraria.Main.UnderworldLayer, and Terraria.Main.worldSurface.
Referenced by Terraria.WorldGen.AddPasses().