Terraria Decompiled: Terraria.WorldGen.SecretSeed.CheckInputForSecretSeed
CheckInputForSecretSeed()
static bool Terraria.WorldGen.SecretSeed.CheckInputForSecretSeed (string worldSeed, out WorldGen::SecretSeed secretSeed) inline static
Definition at line 88375 of file WorldGen.cs.
            {
                string worldSeed2 = worldSeed;
                secretSeed = null;
                if (string.IsNullOrWhiteSpace(worldSeed))
                {
                    return false;
                }
                worldSeed = Regex.Replace(worldSeed.ToLower(), "[^a-z0-9]+", "");
                if (string.IsNullOrWhiteSpace(worldSeed))
                {
                    return false;
                }
                secretSeed = WorldGen.SecretSeed.AllSecretSeeds.FirstOrDefault((WorldGen.SecretSeed s) => s._plaintext == worldSeed);
                if (secretSeed == null)
                {
                    string code = Secrets.ToSecret(worldSeed);
                    secretSeed = WorldGen.SecretSeed.AllSecretSeeds.FirstOrDefault((WorldGen.SecretSeed s) => s._code == code);
                }
                if (secretSeed == null)
                {
                    return false;
                }
                secretSeed._plaintext = worldSeed;
                string text = Regex.Replace(worldSeed2, "[^a-zA-Z0-9 ]+", "");
                secretSeed.TextThatWasUsedToUnlock = text;
                return true;
            }
References Terraria.WorldGen.SecretSeed.AllSecretSeeds, System.s, System.text, and Terraria.Utilities.Secrets.ToSecret().
Referenced by Terraria.Main.DedServ(), Terraria.GameContent.UI.States.UIWorldCreation.EnableSecretSeedOptions(), Terraria.GameContent.UI.States.UIWorldCreation.OnFinishedSettingSeed(), Terraria.GameContent.SecretSeedsTracker.SeedHasSecret(), and Terraria.IO.WorldFileData.TryParseSecretSeed().