Terraria Decompiled: Terraria.WorldGen.SecretSeed.DoWorldIsFrozenFinish
DoWorldIsFrozenFinish()
static void Terraria.WorldGen.SecretSeed.DoWorldIsFrozenFinish () inline static
Definition at line 90216 of file WorldGen.cs.
            {
                for (int i = 0; i < 8000; i++)
                {
                    Chest chest = Main.chest[i];
                    if (chest == null)
                    {
                        break;
                    }
                    if (WorldGen.genRand.Next(2) == 0 && chest.item[1].stack != 0)
                    {
                        for (int j = 1; j < chest.maxItems; j++)
{
                            if (chest.item[j].stack == 0)
{
                                chest.item[j].SetDefaults(1869, null);
                                break;
                            }
                        }
                    }
                }
                if (!WorldGen.skyblockWorldGen && WorldGen.SecretSeed.endlessChristmas.Enabled)
                {
                    for (int k = 0; k < Main.maxNPCs; k++)
                    {
                        if (Main.npc[k].type == 22)
{
                            int num = NPC.NewNPC(new EntitySource_WorldGen(), Main.spawnTileX * 16, Main.spawnTileY * 16, 142, 0, 0f, 0f, 0f, 0f, 255);
                            Main.npc[num].homeTileX = Main.spawnTileX;
                            Main.npc[num].homeTileY = Main.spawnTileY;
                            Main.npc[num].direction = 1;
                            Main.npc[num].homeless = true;
                            Main.npc[num].position = Main.npc[k].position;
                            Main.npc[k].active = false;
                        }
                    }
                }
            }
References Terraria.NPC.active, Terraria.Main.chest, Terraria.Entity.direction, Terraria.WorldGen.SecretSeed.endlessChristmas, Terraria.WorldGen.genRand, Terraria.NPC.homeless, Terraria.NPC.homeTileX, Terraria.NPC.homeTileY, Terraria.Chest.item, Terraria.Chest.maxItems, Terraria.Main.maxNPCs, Terraria.NPC.NewNPC(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.npc, Terraria.Entity.position, Terraria.Item.SetDefaults(), Terraria.WorldGen.skyblockWorldGen, Terraria.Main.spawnTileX, Terraria.Main.spawnTileY, Terraria.Item.stack, and Terraria.NPC.type.
Referenced by Terraria.WorldGen.SecretSeed.FinalizeSecretSeeds().