Terraria Decompiled: System.Globalization.CultureInfo.GetCultures
GetCultures()
static CultureInfo[] System.Globalization.CultureInfo.GetCultures (CultureTypes types) inline static
Definition at line 874 of file CultureInfo.cs.
        {
            bool flag = (types & CultureTypes.NeutralCultures) > (CultureTypes)0;
            bool flag2 = (types & CultureTypes.SpecificCultures) > (CultureTypes)0;
            bool flag3 = (types & CultureTypes.InstalledWin32Cultures) > (CultureTypes)0;
            CultureInfo[] array = CultureInfo.internal_get_cultures(flag, flag2, flag3);
            int i = 0;
            if (flag && array.Length != 0 && array[0] == null)
            {
                array[i++] = (CultureInfo)CultureInfo.InvariantCulture.Clone();
            }
            while (i < array.Length)
            {
                CultureInfo cultureInfo = array[i];
                CultureInfo.Data textInfoData = cultureInfo.GetTextInfoData();
                CultureInfo cultureInfo2 = array[i];
                string name = cultureInfo.m_name;
                bool flag4 = false;
                int num = cultureInfo.datetime_index;
                int calendarType = cultureInfo.CalendarType;
                int num2 = cultureInfo.number_index;
                string text = cultureInfo.iso2lang;
                int ansi = textInfoData.ansi;
                int oem = textInfoData.oem;
                int mac = textInfoData.mac;
                int ebcdic = textInfoData.ebcdic;
                bool right_to_left = textInfoData.right_to_left;
                char list_sep = (char)textInfoData.list_sep;
                cultureInfo2.m_cultureData = CultureData.GetCultureData(name, flag4, num, calendarType, num2, text, ansi, oem, mac, ebcdic, right_to_left, list_sep.ToString());
                i++;
            }
            return array;
        }
References System.Globalization.CultureInfo.Data.ansi, System.array, System.Globalization.CultureInfo.CalendarType, System.Globalization.CultureInfo.Clone(), System.Globalization.CultureInfo.CultureInfo(), System.Globalization.CultureInfo.datetime_index, System.Globalization.CultureInfo.Data.ebcdic, System.Globalization.CultureData.GetCultureData(), System.Globalization.CultureInfo.GetTextInfoData(), System.Globalization.CultureInfo.internal_get_cultures(), System.Globalization.CultureInfo.InvariantCulture, System.Globalization.CultureInfo.iso2lang, System.Globalization.CultureInfo.Data.list_sep, System.Globalization.CultureInfo.m_name, System.Globalization.CultureInfo.Data.mac, System.name, System.Globalization.CultureInfo.number_index, System.Globalization.CultureInfo.Data.oem, System.Globalization.CultureInfo.Data.right_to_left, and System.text.