Terraria Decompiled: System.Globalization.CultureInfo.CultureInfo
CultureInfo() [3/8]
System.Globalization.CultureInfo.CultureInfo (int culture, bool useUserOverride, bool read_only) inline private
Definition at line 1204 of file CultureInfo.cs.
        {
            if (culture < 0)
            {
                throw new ArgumentOutOfRangeException("culture", "Positive number required.");
            }
            this.constructed = true;
            this.m_isReadOnly = read_only;
            this.m_useUserOverride = useUserOverride;
            if (culture == 127)
            {
                this.m_cultureData = CultureData.Invariant;
                this.ConstructInvariant(read_only);
                return;
            }
            if (!this.construct_internal_locale_from_lcid(culture))
            {
                string text = string.Format(CultureInfo.InvariantCulture, "Culture ID {0} (0x{1}) is not a supported culture.", culture.ToString(CultureInfo.InvariantCulture), culture.ToString("X4", CultureInfo.InvariantCulture));
                throw new CultureNotFoundException("culture", text);
            }
            CultureInfo.Data textInfoData = this.GetTextInfoData();
            string name = this.m_name;
            bool useUserOverride2 = this.m_useUserOverride;
            int num = this.datetime_index;
            int calendarType = this.CalendarType;
            int num2 = this.number_index;
            string text2 = this.iso2lang;
            int ansi = textInfoData.ansi;
            int oem = textInfoData.oem;
            int mac = textInfoData.mac;
            int ebcdic = textInfoData.ebcdic;
            bool right_to_left = textInfoData.right_to_left;
            char list_sep = (char)textInfoData.list_sep;
            this.m_cultureData = CultureData.GetCultureData(name, useUserOverride2, num, calendarType, num2, text2, ansi, oem, mac, ebcdic, right_to_left, list_sep.ToString());
        }
References System.Globalization.CultureInfo.Data.ansi, System.Globalization.CultureInfo.CalendarType, System.Globalization.CultureInfo.construct_internal_locale_from_lcid(), System.Globalization.CultureInfo.ConstructInvariant(), System.culture, System.Globalization.CultureInfo.datetime_index, System.Globalization.CultureInfo.Data.ebcdic, System.Globalization.CultureData.GetCultureData(), System.Globalization.CultureInfo.GetTextInfoData(), System.Globalization.CultureData.Invariant, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.CultureInfo.iso2lang, System.Globalization.CultureInfo.Data.list_sep, System.Globalization.CultureInfo.m_name, System.Globalization.CultureInfo.m_useUserOverride, System.Globalization.CultureInfo.Data.mac, System.name, System.Globalization.CultureInfo.number_index, System.Globalization.CultureInfo.Data.oem, System.Globalization.CultureInfo.Data.right_to_left, System.text, and System.Globalization.CultureInfo.ToString().