Terraria Decompiled: System.Globalization.CultureInfo.CreateSpecificCulture
CreateSpecificCulture()
static CultureInfo System.Globalization.CultureInfo.CreateSpecificCulture (string name) inline static
Definition at line 1407 of file CultureInfo.cs.
        {
            if (name == null)
            {
                throw new ArgumentNullException("name");
            }
            if (name.Length == 0)
            {
                return CultureInfo.InvariantCulture;
            }
            string text = name;
            name = name.ToLowerInvariant();
            CultureInfo cultureInfo = new CultureInfo();
            if (!cultureInfo.construct_internal_locale_from_name(name))
            {
                int num = name.Length - 1;
                if (num > 0)
                {
                    while ((num = name.LastIndexOf('-', num - 1)) > 0 && !cultureInfo.construct_internal_locale_from_name(name.Substring(0, num)))
                    {
                    }
                }
                if (num <= 0)
                {
                    throw CultureInfo.CreateNotFoundException(text);
                }
            }
            if (cultureInfo.IsNeutralCulture)
            {
                cultureInfo = CultureInfo.CreateSpecificCultureFromNeutral(cultureInfo.Name);
            }
            CultureInfo.Data textInfoData = cultureInfo.GetTextInfoData();
            CultureInfo cultureInfo2 = cultureInfo;
            string name2 = cultureInfo.m_name;
            bool flag = false;
            int num2 = cultureInfo.datetime_index;
            int calendarType = cultureInfo.CalendarType;
            int num3 = cultureInfo.number_index;
            string text2 = cultureInfo.iso2lang;
            int ansi = textInfoData.ansi;
            int oem = textInfoData.oem;
            int mac = textInfoData.mac;
            int ebcdic = textInfoData.ebcdic;
            bool right_to_left = textInfoData.right_to_left;
            char list_sep = (char)textInfoData.list_sep;
            cultureInfo2.m_cultureData = CultureData.GetCultureData(name2, flag, num2, calendarType, num3, text2, ansi, oem, mac, ebcdic, right_to_left, list_sep.ToString());
            return cultureInfo;
        }
References System.Globalization.CultureInfo.Data.ansi, System.Globalization.CultureInfo.CalendarType, System.Globalization.CultureInfo.construct_internal_locale_from_name(), System.Globalization.CultureInfo.CreateNotFoundException(), System.Globalization.CultureInfo.CreateSpecificCultureFromNeutral(), System.Globalization.CultureInfo.CultureInfo(), System.Globalization.CultureInfo.datetime_index, System.Globalization.CultureInfo.Data.ebcdic, System.Globalization.CultureData.GetCultureData(), System.Globalization.CultureInfo.GetTextInfoData(), System.Globalization.CultureInfo.InvariantCulture, System.Globalization.CultureInfo.IsNeutralCulture, System.Globalization.CultureInfo.iso2lang, System.Globalization.CultureInfo.Data.list_sep, System.Globalization.CultureInfo.m_name, System.Globalization.CultureInfo.Data.mac, System.name, System.Globalization.CultureInfo.Name, System.Globalization.CultureInfo.number_index, System.Globalization.CultureInfo.Data.oem, System.Globalization.CultureInfo.Data.right_to_left, and System.text.
Referenced by System.Globalization.CultureInfo.ConstructCurrentCulture().