Terraria Decompiled: System.Globalization.CultureInfo.CultureInfo
CultureInfo() [6/8]
System.Globalization.CultureInfo.CultureInfo (string name, bool useUserOverride, bool read_only) inline private
Definition at line 1253 of file CultureInfo.cs.
        {
            if (name == null)
            {
                throw new ArgumentNullException("name");
            }
            this.constructed = true;
            this.m_isReadOnly = read_only;
            this.m_useUserOverride = useUserOverride;
            this.m_isInherited = base.GetType() != typeof(CultureInfo);
            if (name.Length == 0)
            {
                this.m_cultureData = CultureData.Invariant;
                this.ConstructInvariant(read_only);
                return;
            }
            if (!this.construct_internal_locale_from_name(name.ToLowerInvariant()))
            {
                throw CultureInfo.CreateNotFoundException(name);
            }
            CultureInfo.Data textInfoData = this.GetTextInfoData();
            string name2 = this.m_name;
            int num = this.datetime_index;
            int calendarType = this.CalendarType;
            int num2 = this.number_index;
            string text = this.iso2lang;
            int ansi = textInfoData.ansi;
            int oem = textInfoData.oem;
            int mac = textInfoData.mac;
            int ebcdic = textInfoData.ebcdic;
            bool right_to_left = textInfoData.right_to_left;
            char list_sep = (char)textInfoData.list_sep;
            this.m_cultureData = CultureData.GetCultureData(name2, useUserOverride, num, calendarType, num2, text, ansi, oem, mac, ebcdic, right_to_left, list_sep.ToString());
        }
References System.Globalization.CultureInfo.Data.ansi, System.Globalization.CultureInfo.CalendarType, System.Globalization.CultureInfo.construct_internal_locale_from_name(), System.Globalization.CultureInfo.ConstructInvariant(), System.Globalization.CultureInfo.CreateNotFoundException(), System.Globalization.CultureInfo.datetime_index, System.Globalization.CultureInfo.Data.ebcdic, System.Globalization.CultureData.GetCultureData(), System.Globalization.CultureInfo.GetTextInfoData(), System.Globalization.CultureData.Invariant, System.Globalization.CultureInfo.iso2lang, System.Globalization.CultureInfo.Data.list_sep, System.Globalization.CultureInfo.m_name, System.Globalization.CultureInfo.Data.mac, System.name, System.Globalization.CultureInfo.number_index, System.Globalization.CultureInfo.Data.oem, System.Globalization.CultureInfo.Data.right_to_left, and System.text.