Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalBanners.Banners
Banners()
void Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalBanners.Banners (DungeonData data) inline
Definition at line 28 of file DungeonGlobalBanners.cs.
        {
            UnifiedRandom genRand = WorldGen.genRand;
            float num = (float)Main.maxTilesX / 4200f;
            double num2 = Math.Max(1.0, data.globalFeatureScalar * 0.75);
            int num3 = (int)((double)(200f * num) * num2);
            for (int i = 0; i < num3; i++)
            {
                int num4 = genRand.Next(data.dungeonBounds.Left, data.dungeonBounds.Right);
                int num5 = genRand.Next(data.dungeonBounds.Top, data.dungeonBounds.Bottom);
                int num6 = 1000;
                while (!DungeonUtils.IsConsideredDungeonWall((int)Main.tile[num4, num5].wall, false) || Main.tile[num4, num5].active())
                {
                    num6--;
                    if (num6 <= 0)
                    {
                        break;
                    }
                    num4 = genRand.Next(data.dungeonBounds.Left, data.dungeonBounds.Right);
                    num5 = genRand.Next(data.dungeonBounds.Top, data.dungeonBounds.Bottom);
                }
                num6 = 1000;
                while (!WorldGen.SolidTile(num4, num5, false) && num5 > 10)
                {
                    num6--;
                    if (num6 <= 0)
                    {
                        break;
                    }
                    num5--;
                }
                num5++;
                if (data.CanGenerateFeatureAt(this, num4, num5) && DungeonUtils.IsConsideredDungeonWall((int)Main.tile[num4, num5].wall, false) && Main.tile[num4, num5 - 1].type != 48 && !Main.tile[num4, num5].active() && !Main.tile[num4, num5 + 1].active() && !Main.tile[num4, num5 + 2].active() && !Main.tile[num4, num5 + 3].active())
                {
                    bool flag = true;
                    for (int j = num4 - 1; j <= num4 + 1; j++)
                    {
                        for (int k = num5; k <= num5 + 3; k++)
{
                            if (Main.tile[j, k].active() && (Main.tile[j, k].type == 10 || Main.tile[j, k].type == 11 || Main.tile[j, k].type == 91))
{
                                flag = false;
                            }
                        }
                    }
                    if (flag)
                    {
                        ushort num7 = 91;
                        DungeonGenerationStyleData styleForWall = DungeonGenerationStyles.GetStyleForWall(data.genVars.dungeonGenerationStyles, (int)Main.tile[num4, num5].wall);
                        if (styleForWall == null || styleForWall.BannerItemTypes != null)
{
                            int num9;
                            if (styleForWall == null || styleForWall.Style == 0 || styleForWall.BannerItemTypes.Length == 0)
{
                                int num8 = 0;
                                if ((int)Main.tile[num4, num5].wall == data.wallVariants[1])
{
                                    num8 = 1;
                                }
                                if ((int)Main.tile[num4, num5].wall == data.wallVariants[2])
{
                                    num8 = 2;
                                }
                                num8 *= 2;
                                num8 += genRand.Next(2);
                                num9 = data.bannerStyles[num8];
                            }
                            else
{
                                PlacementDetails placementDetails = ItemID.Sets.DerivedPlacementDetails[styleForWall.BannerItemTypes[genRand.Next(styleForWall.BannerItemTypes.Length)]];
                                num7 = (ushort)placementDetails.tileType;
                                num9 = (int)placementDetails.tileStyle;
                            }
                            WorldGen.PlaceTile(num4, num5, (int)num7, true, false, -1, num9);
                        }
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.BannerItemTypes, Terraria.GameContent.Generation.Dungeon.DungeonData.bannerStyles, Terraria.GameContent.Generation.Dungeon.DungeonBounds.Bottom, Terraria.GameContent.Generation.Dungeon.DungeonData.CanGenerateFeatureAt(), Terraria.ID.ItemID.Sets.DerivedPlacementDetails, Terraria.GameContent.Generation.Dungeon.DungeonData.dungeonBounds, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.dungeonGenerationStyles, Terraria.WorldGen.genRand, Terraria.GameContent.Generation.Dungeon.DungeonData.genVars, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyles.GetStyleForWall(), Terraria.GameContent.Generation.Dungeon.DungeonData.globalFeatureScalar, int, Terraria.GameContent.Generation.Dungeon.DungeonUtils.IsConsideredDungeonWall(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.Left, System.Math.Max(), Terraria.Main.maxTilesX, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.PlaceTile(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.Right, Terraria.WorldGen.SolidTile(), Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.Style, Terraria.Main.tile, Terraria.DataStructures.PlacementDetails.tileStyle, Terraria.DataStructures.PlacementDetails.tileType, Terraria.GameContent.Generation.Dungeon.DungeonBounds.Top, Terraria.Tile.type, Terraria.Tile.wall, and Terraria.GameContent.Generation.Dungeon.DungeonData.wallVariants.
Referenced by Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalBanners.GenerateFeature().