Terraria Decompiled: Terraria.GameContent.ObjectInteractions.AHoverInteractionChecker.AttemptInteraction
AttemptInteraction()
AHoverInteractionChecker.HoverStatus Terraria.GameContent.ObjectInteractions.AHoverInteractionChecker.AttemptInteraction (Player player, Rectangle Hitbox) inline package
Definition at line 12 of file AHoverInteractionChecker.cs.
        {
            Point point = Hitbox.ClosestPointInRect(player.Center).ToTileCoordinates();
            if (!player.IsInTileInteractionRange(point.X, point.Y, TileReachCheckSettings.Simple, 0))
            {
                return AHoverInteractionChecker.HoverStatus.NotSelectable;
            }
            Vector2 vector = Main.ReverseGravitySupport(Main.MouseScreen, 0f) + Main.screenPosition;
            bool flag = Hitbox.Contains(vector.ToPoint());
            bool flag2 = flag;
            bool? flag3 = this.AttemptOverridingHoverStatus(player, Hitbox);
            if (flag3 != null)
            {
                flag2 = flag3.Value;
            }
            flag2 &= !player.lastMouseInterface;
            bool flag4 = !Main.SmartCursorIsUsed && !PlayerInput.UsingGamepad;
            if (!flag2)
            {
                if (!flag4)
                {
                    return AHoverInteractionChecker.HoverStatus.SelectableButNotSelected;
                }
                return AHoverInteractionChecker.HoverStatus.NotSelectable;
            }
            else
            {
                Main.HasInteractableObjectThatIsNotATile = true;
                if (flag)
                {
                    this.DoHoverEffect(player, Hitbox);
                }
                if (PlayerInput.UsingGamepad)
                {
                    player.GamepadEnableGrappleCooldown();
                }
                bool flag5 = this.ShouldBlockInteraction(player, Hitbox);
                if (Main.mouseRight && Main.mouseRightRelease && !flag5)
                {
                    Main.mouseRightRelease = false;
                    player.tileInteractAttempted = true;
                    player.tileInteractionHappened = true;
                    player.releaseUseTile = false;
                    this.PerformInteraction(player, Hitbox);
                }
                if (!Main.SmartCursorIsUsed && !PlayerInput.UsingGamepad)
                {
                    return AHoverInteractionChecker.HoverStatus.NotSelectable;
                }
                if (!flag4)
                {
                    return AHoverInteractionChecker.HoverStatus.Selected;
                }
                return AHoverInteractionChecker.HoverStatus.NotSelectable;
            }
        }
References Terraria.GameContent.ObjectInteractions.AHoverInteractionChecker.AttemptOverridingHoverStatus(), Terraria.Entity.Center, Microsoft.Xna.Framework.Rectangle.Contains(), Terraria.GameContent.ObjectInteractions.AHoverInteractionChecker.DoHoverEffect(), Terraria.Player.GamepadEnableGrappleCooldown(), Terraria.Player.IsInTileInteractionRange(), Terraria.Player.lastMouseInterface, Terraria.Main.mouseRight, Terraria.Main.mouseRightRelease, Terraria.Main.MouseScreen, Terraria.GameContent.ObjectInteractions.AHoverInteractionChecker.PerformInteraction(), Terraria.Main.ReverseGravitySupport(), Terraria.Main.screenPosition, Terraria.GameContent.ObjectInteractions.AHoverInteractionChecker.ShouldBlockInteraction(), Terraria.DataStructures.TileReachCheckSettings.Simple, Terraria.Main.SmartCursorIsUsed, Terraria.GameInput.PlayerInput.UsingGamepad, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.Graphics.Renderers.ReturnGatePlayerRenderer.DrawReturnGateInWorld().