Terraria Decompiled: System.Globalization.TimeSpanParse.StringParser.ParseTime
ParseTime()
bool System.Globalization.TimeSpanParse.StringParser.ParseTime (out long time, ref TimeSpanParse::TimeSpanResult result) inline package
Definition at line 1561 of file TimeSpanParse.cs.
            {
                time = 0L;
                int num;
                if (!this.ParseInt(23, out num, ref result))
                {
                    return false;
                }
                time = (long)num * 36000000000L;
                if (this._ch != ':')
                {
                    return result.SetFailure(TimeSpanParse.ParseFailureKind.Format, "String was not recognized as a valid TimeSpan.", null, null);
                }
                this.NextChar();
                if (!this.ParseInt(59, out num, ref result))
                {
                    return false;
                }
                time += (long)num * 600000000L;
                if (this._ch == ':')
                {
                    this.NextChar();
                    if (this._ch != '.')
                    {
                        if (!this.ParseInt(59, out num, ref result))
{
                            return false;
                        }
                        time += (long)num * 10000000L;
                    }
                    if (this._ch == '.')
                    {
                        this.NextChar();
                        int num2 = 10000000;
                        while (num2 > 1 && this._ch >= '0' && this._ch <= '9')
{
                            num2 /= 10;
                            time += (long)((int)(this._ch - '0') * num2);
                            this.NextChar();
                        }
                    }
                }
                return true;
            }
References System.Globalization.TimeSpanParse.StringParser._ch, System.L, long, System.Globalization.TimeSpanParse.StringParser.NextChar(), and System.Globalization.TimeSpanParse.StringParser.ParseInt().
Referenced by System.Globalization.TimeSpanParse.StringParser.TryParse().