Terraria Decompiled: System.Globalization.TimeSpanParse.StringParser.ParseInt
ParseInt()
bool System.Globalization.TimeSpanParse.StringParser.ParseInt (int max, out int i, ref TimeSpanParse::TimeSpanResult result) inline package
Definition at line 1536 of file TimeSpanParse.cs.
            {
                i = 0;
                int pos = this._pos;
                while (this._ch >= '0' && this._ch <= '9')
                {
                    if (((long)i & (long)((ulong)(-268435456))) != 0L)
                    {
                        return result.SetFailure(TimeSpanParse.ParseFailureKind.Overflow, "The TimeSpan could not be parsed because at least one of the numeric components is out of range or contains too many digits.", null, null);
                    }
                    i = i * 10 + (int)this._ch - 48;
                    if (i < 0)
                    {
                        return result.SetFailure(TimeSpanParse.ParseFailureKind.Overflow, "The TimeSpan could not be parsed because at least one of the numeric components is out of range or contains too many digits.", null, null);
                    }
                    this.NextChar();
                }
                if (pos == this._pos)
                {
                    return result.SetFailure(TimeSpanParse.ParseFailureKind.Format, "String was not recognized as a valid TimeSpan.", null, null);
                }
                return i <= max || result.SetFailure(TimeSpanParse.ParseFailureKind.Overflow, "The TimeSpan could not be parsed because at least one of the numeric components is out of range or contains too many digits.", null, null);
            }
References System.Globalization.TimeSpanParse.StringParser._ch, System.Globalization.TimeSpanParse.StringParser._pos, int, System.L, and System.Globalization.TimeSpanParse.StringParser.NextChar().
Referenced by System.Globalization.TimeSpanParse.StringParser.ParseTime(), and System.Globalization.TimeSpanParse.StringParser.TryParse().