Terraria Decompiled: System.Globalization.TimeSpanParse.StringParser.TryParse
TryParse()
bool System.Globalization.TimeSpanParse.StringParser.TryParse (ReadOnlySpan< char > input, ref TimeSpanParse::TimeSpanResult result) inline package
Definition at line 1473 of file TimeSpanParse.cs.
            {
                result.parsedTimeSpan = default(TimeSpan);
                this._str = input;
                this._len = input.Length;
                this._pos = -1;
                this.NextChar();
                this.SkipBlanks();
                bool flag = false;
                if (this._ch == '-')
                {
                    flag = true;
                    this.NextChar();
                }
                long num;
                if (this.NextNonDigit() == ':')
                {
                    if (!this.ParseTime(out num, ref result))
                    {
                        return false;
                    }
                }
                else
                {
                    int num2;
                    if (!this.ParseInt(10675199, out num2, ref result))
                    {
                        return false;
                    }
                    num = (long)num2 * 864000000000L;
                    if (this._ch == '.')
                    {
                        this.NextChar();
                        long num3;
                        if (!this.ParseTime(out num3, ref result))
{
                            return false;
                        }
                        num += num3;
                    }
                }
                if (flag)
                {
                    num = -num;
                    if (num > 0L)
                    {
                        return result.SetFailure(TimeSpanParse.ParseFailureKind.Overflow, "The TimeSpan could not be parsed because at least one of the numeric components is out of range or contains too many digits.", null, null);
                    }
                }
                else if (num < 0L)
                {
                    return result.SetFailure(TimeSpanParse.ParseFailureKind.Overflow, "The TimeSpan could not be parsed because at least one of the numeric components is out of range or contains too many digits.", null, null);
                }
                this.SkipBlanks();
                if (this._pos < this._len)
                {
                    return result.SetFailure(TimeSpanParse.ParseFailureKind.Format, "String was not recognized as a valid TimeSpan.", null, null);
                }
                result.parsedTimeSpan = new TimeSpan(num);
                return true;
            }
References System.Globalization.TimeSpanParse.StringParser._ch, System.Globalization.TimeSpanParse.StringParser._len, System.Globalization.TimeSpanParse.StringParser._pos, System.input, System.L, long, System.Globalization.TimeSpanParse.StringParser.NextChar(), System.Globalization.TimeSpanParse.StringParser.NextNonDigit(), System.Globalization.TimeSpanParse.StringParser.ParseInt(), System.Globalization.TimeSpanParse.StringParser.ParseTime(), and System.Globalization.TimeSpanParse.StringParser.SkipBlanks().