Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.DungeonBounds.SetBounds
SetBounds() [2/2]
void Terraria.GameContent.Generation.Dungeon.DungeonBounds.SetBounds (Rectangle rect) inline
Definition at line 292 of file DungeonBounds.cs.
        {
            this.SetBounds(rect.Left, rect.Top, rect.Right, rect.Bottom);
        }
References Microsoft.Xna.Framework.Rectangle.Bottom, Microsoft.Xna.Framework.Rectangle.Left, Microsoft.Xna.Framework.Rectangle.Right, Terraria.GameContent.Generation.Dungeon.DungeonBounds.SetBounds(), and Microsoft.Xna.Framework.Rectangle.Top.
Referenced by Terraria.GameContent.Generation.Dungeon.Rooms.BiomeRuggedDungeonRoom.BiomeRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeSquareDungeonRoom.BiomeRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeStructuredDungeonRoom.BiomeRoom(), Terraria.GameContent.Generation.Dungeon.DungeonData.CanGenerateFeatureInArea(), Terraria.GameContent.Generation.Dungeon.Entrances.DomeDungeonEntrance.DomeEntrance(), Terraria.GameContent.Generation.Dungeon.Features.DungeonDropTrap.DropTrap(), Terraria.GameContent.Generation.Dungeon.Rooms.GenShapeDungeonRoom.GenShapeRoom(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.Inflate(), Terraria.GameContent.Generation.Dungeon.Entrances.LegacyDungeonEntrance.LegacyEntrance(), Terraria.GameContent.Generation.Dungeon.Halls.LegacyDungeonHall.LegacyHall(), Terraria.GameContent.Generation.Dungeon.Halls.LegacyEntranceDungeonHall.LegacyHall(), Terraria.GameContent.Generation.Dungeon.Rooms.LegacyDungeonRoom.LegacyRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.LivingTreeDungeonRoom.LivingTreeRoom(), Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon(), Terraria.GameContent.Generation.Dungeon.Features.DungeonPillar.Pillar(), Terraria.GameContent.Generation.Dungeon.Features.DungeonPitTrap.PitTrap(), Terraria.GameContent.Generation.Dungeon.Halls.RegularDungeonHall.RegularHall(), Terraria.GameContent.Generation.Dungeon.Rooms.RegularDungeonRoom.RegularRoom(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.SetBounds(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.Shrink(), Terraria.GameContent.Generation.Dungeon.Halls.SineDungeonHall.SineHall(), Terraria.GameContent.Generation.Dungeon.Halls.StairwellDungeonHall.Stairwell(), Terraria.GameContent.Generation.Dungeon.Features.DungeonTileClump.TileClump(), Terraria.GameContent.Generation.Dungeon.Entrances.TowerDungeonEntrance.TowerEntrance(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.UpdateBounds(), Terraria.GameContent.Generation.Dungeon.Features.DungeonWindowBasic.Window(), Terraria.GameContent.Generation.Dungeon.Features.DungeonWindowMosaic.Window(), and Terraria.GameContent.Generation.Dungeon.Rooms.WormlikeDungeonRoom.WormlikeRoom().