Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.DungeonBounds.UpdateBounds
UpdateBounds() [3/3]
void Terraria.GameContent.Generation.Dungeon.DungeonBounds.UpdateBounds (int x, int y) inline
Definition at line 308 of file DungeonBounds.cs.
        {
            if (x < this._boundsLeft)
            {
                this.Left = x;
            }
            if (x > this._boundsRight)
            {
                this.Right = x;
            }
            if (y < this._boundsTop)
            {
                this.Top = y;
            }
            if (y > this._boundsBottom)
            {
                this.Bottom = y;
            }
        }
References Terraria.GameContent.Generation.Dungeon.DungeonBounds._boundsBottom, Terraria.GameContent.Generation.Dungeon.DungeonBounds._boundsLeft, Terraria.GameContent.Generation.Dungeon.DungeonBounds._boundsRight, and Terraria.GameContent.Generation.Dungeon.DungeonBounds._boundsTop.
Referenced by Terraria.WorldBuilding.Actions.UpdateBounds.Apply(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeRuggedDungeonRoom.BiomeRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeSquareDungeonRoom.BiomeRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeStructuredDungeonRoom.BiomeRoom(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.CalculateDungeonBounds(), Terraria.GameContent.Generation.Dungeon.Entrances.DomeDungeonEntrance.DomeEntrance(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.GenerateDungeonSquareRoom(), Terraria.GameContent.Generation.Dungeon.Halls.StairwellDungeonHall.GenerateHallway(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.LegacyDungeonLayoutProvider.LegacyDungeonLayout(), Terraria.GameContent.Generation.Dungeon.Entrances.LegacyDungeonEntrance.LegacyEntrance(), Terraria.GameContent.Generation.Dungeon.Halls.LegacyDungeonHall.LegacyHall(), Terraria.GameContent.Generation.Dungeon.Halls.LegacyEntranceDungeonHall.LegacyHall(), Terraria.GameContent.Generation.Dungeon.Rooms.LegacyDungeonRoom.LegacyRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.LivingTreeDungeonRoom.LivingTreeRoom(), Terraria.GameContent.Generation.Dungeon.Features.DungeonPillar.Pillar(), Terraria.GameContent.Generation.Dungeon.Halls.RegularDungeonHall.RegularHall(), Terraria.GameContent.Generation.Dungeon.Rooms.RegularDungeonRoom.RegularRoom(), Terraria.GameContent.Generation.Dungeon.Halls.SineDungeonHall.SineHall(), Terraria.GameContent.Generation.Dungeon.Features.DungeonTileClump.TileClump(), Terraria.GameContent.Generation.Dungeon.Entrances.TowerDungeonEntrance.TowerEntrance(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.UpdateBounds(), Terraria.GameContent.Generation.Dungeon.Features.DungeonWindowBasic.Window(), Terraria.GameContent.Generation.Dungeon.Features.DungeonWindowMosaic.Window_MoonLord(), and Terraria.GameContent.Generation.Dungeon.Rooms.WormlikeDungeonRoom.WormlikeRoom().