Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.DungeonBounds.CalculateHitbox
CalculateHitbox()
Rectangle Terraria.GameContent.Generation.Dungeon.DungeonBounds.CalculateHitbox () inline
Definition at line 361 of file DungeonBounds.cs.
        {
            if (this.Right <= this.Left)
            {
                this.Right = this.Left + 1;
            }
            if (this.Bottom <= this.Top)
            {
                this.Bottom = this.Top + 1;
            }
            this._hitbox = new Rectangle?(new Rectangle(this.X, this.Y, this.Width, this.Height));
            return this._hitbox.Value;
        }
References Terraria.GameContent.Generation.Dungeon.DungeonBounds._hitbox, Terraria.GameContent.Generation.Dungeon.DungeonBounds.Bottom, Terraria.GameContent.Generation.Dungeon.DungeonBounds.Height, Terraria.GameContent.Generation.Dungeon.DungeonBounds.Left, Terraria.GameContent.Generation.Dungeon.DungeonBounds.Right, Terraria.GameContent.Generation.Dungeon.DungeonBounds.Top, Terraria.GameContent.Generation.Dungeon.DungeonBounds.Width, Terraria.GameContent.Generation.Dungeon.DungeonBounds.X, and Terraria.GameContent.Generation.Dungeon.DungeonBounds.Y.
Referenced by Terraria.GameContent.Generation.Dungeon.Rooms.BiomeRuggedDungeonRoom.BiomeRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeSquareDungeonRoom.BiomeRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeStructuredDungeonRoom.BiomeRoom(), Terraria.GameContent.Generation.Dungeon.DungeonData.CanGenerateFeatureInArea(), Terraria.GameContent.Generation.Dungeon.Entrances.DomeDungeonEntrance.DomeEntrance(), Terraria.GameContent.Generation.Dungeon.Features.DungeonDropTrap.DropTrap(), Terraria.GameContent.Generation.Dungeon.Entrances.LegacyDungeonEntrance.LegacyEntrance(), Terraria.GameContent.Generation.Dungeon.Halls.LegacyDungeonHall.LegacyHall(), Terraria.GameContent.Generation.Dungeon.Halls.LegacyEntranceDungeonHall.LegacyHall(), Terraria.GameContent.Generation.Dungeon.Rooms.LegacyDungeonRoom.LegacyRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.LivingTreeDungeonRoom.LivingTreeRoom(), Terraria.GameContent.Generation.Dungeon.Features.DungeonPillar.Pillar(), Terraria.GameContent.Generation.Dungeon.Features.DungeonPitTrap.PitTrap(), Terraria.GameContent.Generation.Dungeon.Halls.RegularDungeonHall.RegularHall(), Terraria.GameContent.Generation.Dungeon.Rooms.RegularDungeonRoom.RegularRoom(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.SetBounds(), Terraria.GameContent.Generation.Dungeon.Halls.SineDungeonHall.SineHall(), Terraria.GameContent.Generation.Dungeon.Halls.StairwellDungeonHall.Stairwell(), Terraria.GameContent.Generation.Dungeon.Features.DungeonTileClump.TileClump(), Terraria.GameContent.Generation.Dungeon.Entrances.TowerDungeonEntrance.TowerEntrance(), Terraria.GameContent.Generation.Dungeon.Features.DungeonWindowBasic.Window(), Terraria.GameContent.Generation.Dungeon.Features.DungeonWindowMosaic.Window(), and Terraria.GameContent.Generation.Dungeon.Rooms.WormlikeDungeonRoom.WormlikeRoom().