Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.DungeonBounds.Contains
Contains() [3/3]
bool Terraria.GameContent.Generation.Dungeon.DungeonBounds.Contains (Vector2D point) inline
Definition at line 214 of file DungeonBounds.cs.
        {
            return this.Contains((int)point.X, (int)point.Y);
        }
References Microsoft.Xna.Framework.Contains, ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.GameContent.Generation.Dungeon.Rooms.BiomeRuggedDungeonRoom.BiomeRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeSquareDungeonRoom.BiomeRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeStructuredDungeonRoom.BiomeRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeDungeonRoom.BiomeRoom_FinishRoom(), Terraria.GameContent.Generation.Dungeon.DungeonData.CanGenerateFeatureAt(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.FirstSolid(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeDungeonRoom.GetProtectionTypeFromPoint(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.GetProtectionTypeFromPoint(), Terraria.GameContent.Generation.Dungeon.Rooms.GenShapeDungeonRoom.GetProtectionTypeFromPoint(), Terraria.GameContent.Generation.Dungeon.Rooms.LegacyDungeonRoom.GetProtectionTypeFromPoint(), Terraria.GameContent.Generation.Dungeon.Rooms.LivingTreeDungeonRoom.GetProtectionTypeFromPoint(), Terraria.GameContent.Generation.Dungeon.Rooms.WormlikeDungeonRoom.GetProtectionTypeFromPoint(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.IsInsideRoom(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalLateDualDungeonFeatures.LateDualDungeonFeatures_CleanOutEntrancesOfLiquids(), Terraria.GameContent.Generation.Dungeon.Features.DungeonPitTrap.PitTrap(), and Terraria.GameContent.Generation.Dungeon.Features.DungeonTileClump.TileClump().