Terraria Decompiled: System.IO.StreamWriter.d__62.MoveNext
MoveNext()
void IAsyncStateMachine. System.IO.StreamWriter.d__62.MoveNext () inline
Implements System.Runtime.CompilerServices.IAsyncStateMachine.
Definition at line 1372 of file StreamWriter.cs.
            {
                int num2;
                int num = num2;
                try
                {
                    ConfiguredTaskAwaitable.ConfiguredTaskAwaiter configuredTaskAwaiter;
                    switch (num)
                    {
                    case 0:
                    {
                        ConfiguredTaskAwaitable.ConfiguredTaskAwaiter configuredTaskAwaiter2;
                        configuredTaskAwaiter = configuredTaskAwaiter2;
                        configuredTaskAwaiter2 = default(ConfiguredTaskAwaitable.ConfiguredTaskAwaiter);
                        num2 = -1;
                        break;
                    }
                    case 1:
                    {
                        ConfiguredTaskAwaitable.ConfiguredTaskAwaiter configuredTaskAwaiter2;
                        configuredTaskAwaiter = configuredTaskAwaiter2;
                        configuredTaskAwaiter2 = default(ConfiguredTaskAwaitable.ConfiguredTaskAwaiter);
                        num2 = -1;
                        goto IL_01E5;
                    }
                    case 2:
                    {
                        ConfiguredTaskAwaitable.ConfiguredTaskAwaiter configuredTaskAwaiter2;
                        configuredTaskAwaiter = configuredTaskAwaiter2;
                        configuredTaskAwaiter2 = default(ConfiguredTaskAwaitable.ConfiguredTaskAwaiter);
                        num2 = -1;
                        goto IL_02C2;
                    }
                    default:
                        copied = 0;
                        goto IL_0131;
                    }
                    IL_00AC:
                    configuredTaskAwaiter.GetResult();
                    charPos = 0;
                    IL_00BA:
                    int num3 = Math.Min(charLen - charPos, source.Length - copied);
                    source.Span.Slice(copied, num3).CopyTo(new Span<char>(charBuffer, charPos, num3));
                    charPos += num3;
                    copied += num3;
                    IL_0131:
                    if (copied >= source.Length)
                    {
                        if (appendNewLine)
{
                            i = 0;
                            goto IL_0231;
                        }
                        goto IL_0244;
                    }
                    else
                    {
                        if (charPos != charLen)
{
                            goto IL_00BA;
                        }
                        configuredTaskAwaiter = _this.FlushAsyncInternal(false, false, charBuffer, charPos, cancellationToken).ConfigureAwait(false).GetAwaiter();
                        if (!configuredTaskAwaiter.IsCompleted)
{
                            num2 = 0;
                            ConfiguredTaskAwaitable.ConfiguredTaskAwaiter configuredTaskAwaiter2 = configuredTaskAwaiter;
                            this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredTaskAwaitable.ConfiguredTaskAwaiter, StreamWriter.<WriteAsyncInternal>d__62>(ref configuredTaskAwaiter, ref this);
                            return;
                        }
                        goto IL_00AC;
                    }
                    IL_01E5:
                    configuredTaskAwaiter.GetResult();
                    charPos = 0;
                    IL_01F3:
                    charBuffer[charPos] = coreNewLine[i];
                    int num4 = charPos;
                    charPos = num4 + 1;
                    num4 = i;
                    i = num4 + 1;
                    IL_0231:
                    if (i < coreNewLine.Length)
                    {
                        if (charPos != charLen)
{
                            goto IL_01F3;
                        }
                        configuredTaskAwaiter = _this.FlushAsyncInternal(false, false, charBuffer, charPos, cancellationToken).ConfigureAwait(false).GetAwaiter();
                        if (!configuredTaskAwaiter.IsCompleted)
{
                            num2 = 1;
                            ConfiguredTaskAwaitable.ConfiguredTaskAwaiter configuredTaskAwaiter2 = configuredTaskAwaiter;
                            this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredTaskAwaitable.ConfiguredTaskAwaiter, StreamWriter.<WriteAsyncInternal>d__62>(ref configuredTaskAwaiter, ref this);
                            return;
                        }
                        goto IL_01E5;
                    }
                    IL_0244:
                    if (!autoFlush)
                    {
                        goto IL_02D0;
                    }
                    configuredTaskAwaiter = _this.FlushAsyncInternal(true, false, charBuffer, charPos, cancellationToken).ConfigureAwait(false).GetAwaiter();
                    if (!configuredTaskAwaiter.IsCompleted)
                    {
                        num2 = 2;
                        ConfiguredTaskAwaitable.ConfiguredTaskAwaiter configuredTaskAwaiter2 = configuredTaskAwaiter;
                        this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredTaskAwaitable.ConfiguredTaskAwaiter, StreamWriter.<WriteAsyncInternal>d__62>(ref configuredTaskAwaiter, ref this);
                        return;
                    }
                    IL_02C2:
                    configuredTaskAwaiter.GetResult();
                    charPos = 0;
                    IL_02D0:
                    _this.CharPos_Prop = charPos;
                }
                catch (Exception ex)
                {
                    num2 = -2;
                    this.<>t__builder.SetException(ex);
                    return;
                }
                num2 = -2;
                this.<>t__builder.SetResult();
            }
References System.Runtime.CompilerServices.ConfiguredTaskAwaitable< TResult >.ConfiguredTaskAwaiter.GetResult(), System.Runtime.CompilerServices.ConfiguredTaskAwaitable< TResult >.ConfiguredTaskAwaiter.IsCompleted, System.Math.Min(), System.source, and System.IO.StreamWriter.WriteAsyncInternal().