Terraria Decompiled: rail.IRailSpaceWorkImpl.GetMetadata
GetMetadata()
virtual RailResult rail.IRailSpaceWorkImpl.GetMetadata (string key, out string value) inline virtual
Implements rail.IRailSpaceWork.
Definition at line 244 of file IRailSpaceWorkImpl.cs.
        {
            IntPtr intPtr = RAIL_API_PINVOKE.new_RailString__SWIG_0();
            RailResult railResult;
            try
            {
                railResult = (RailResult)RAIL_API_PINVOKE.IRailSpaceWork_GetMetadata(this.swigCPtr_, key, intPtr);
            }
            finally
            {
                value = RAIL_API_PINVOKE.RailString_c_str(intPtr);
                RAIL_API_PINVOKE.delete_RailString(intPtr);
            }
            return railResult;
        }
References rail.RAIL_API_PINVOKE.delete_RailString(), rail.RAIL_API_PINVOKE.IRailSpaceWork_GetMetadata(), System.key, rail.RAIL_API_PINVOKE.new_RailString__SWIG_0(), rail.RAIL_API_PINVOKE.RailString_c_str(), and System.value.