Terraria Decompiled: rail.IRailSpaceWorkImpl.SetLanguages
SetLanguages()
virtual RailResult rail.IRailSpaceWorkImpl.SetLanguages (List< string > languages) inline virtual
Implements rail.IRailSpaceWork.
Definition at line 473 of file IRailSpaceWorkImpl.cs.
        {
            IntPtr intPtr = ((languages == null) ? IntPtr.Zero : RAIL_API_PINVOKE.new_RailArrayRailString__SWIG_0());
            if (languages != null)
            {
                RailConverter.Csharp2Cpp(languages, intPtr);
            }
            RailResult railResult;
            try
            {
                railResult = (RailResult)RAIL_API_PINVOKE.IRailSpaceWork_SetLanguages(this.swigCPtr_, intPtr);
            }
            finally
            {
                RAIL_API_PINVOKE.delete_RailArrayRailString(intPtr);
            }
            return railResult;
        }
References rail.RailConverter.Csharp2Cpp(), rail.RAIL_API_PINVOKE.delete_RailArrayRailString(), rail.RAIL_API_PINVOKE.IRailSpaceWork_SetLanguages(), rail.RAIL_API_PINVOKE.new_RailArrayRailString__SWIG_0(), and System.IntPtr.Zero.