Terraria Decompiled: rail.IRailSpaceWorkImpl.GetLocalVersion
GetLocalVersion()
virtual RailResult rail.IRailSpaceWorkImpl.GetLocalVersion (out string version) inline virtual
Implements rail.IRailSpaceWork.
Definition at line 648 of file IRailSpaceWorkImpl.cs.
        {
            IntPtr intPtr = RAIL_API_PINVOKE.new_RailString__SWIG_0();
            RailResult railResult;
            try
            {
                railResult = (RailResult)RAIL_API_PINVOKE.IRailSpaceWork_GetLocalVersion(this.swigCPtr_, intPtr);
            }
            finally
            {
                version = RAIL_API_PINVOKE.RailString_c_str(intPtr);
                RAIL_API_PINVOKE.delete_RailString(intPtr);
            }
            return railResult;
        }
References rail.RAIL_API_PINVOKE.delete_RailString(), rail.RAIL_API_PINVOKE.IRailSpaceWork_GetLocalVersion(), rail.RAIL_API_PINVOKE.new_RailString__SWIG_0(), and rail.RAIL_API_PINVOKE.RailString_c_str().