Terraria Decompiled: System.Runtime.InteropServices._MethodInfo.ToString
ToString()
string System.Runtime.InteropServices._MethodInfo.ToString ()
Implemented in System.Reflection.Emit.DynamicMethod, System.Reflection.Emit.MethodBuilder, System.Reflection.Emit.MethodOnTypeBuilderInst, System.Reflection.MonoArrayMethod, and System.Reflection.RuntimeMethodInfo.
Referenced by System.Reflection.MemberInfoSerializationHolder.GetRealObject(), System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.NativeOrStaticEventRegistrationImpl.EventCacheKey.ToString(), and System.Security.SecurityException.ToString().