Terraria Decompiled: System.Text.Normalization.GetCombiningClass
GetCombiningClass()
static unsafe byte System.Text.Normalization.GetCombiningClass (int c) inline static private
Definition at line 23 of file Normalization.cs.
        {
            return Normalization.combiningClass[NormalizationTableUtil.Combining.ToIndex(c)];
        }
References Mono.Globalization.Unicode.NormalizationTableUtil.Combining, System.Text.Normalization.combiningClass, and Mono.Globalization.Unicode.CodePointIndexer.ToIndex().
Referenced by System.Text.Normalization.IsNormalized(), System.Text.Normalization.ReorderCanonical(), and System.Text.Normalization.TryComposeWithPreviousStarter().