Terraria Decompiled: System.Text.Normalization.QuickCheck
QuickCheck()
static NormalizationCheck System.Text.Normalization.QuickCheck (char c, int type) inline static
Definition at line 340 of file Normalization.cs.
        {
            switch (type)
            {
            case 1:
                if ('가' <= c && c <= '힣')
                {
                    return NormalizationCheck.No;
                }
                if ((Normalization.PropValue((int)c) & 1U) == 0U)
                {
                    return NormalizationCheck.Yes;
                }
                return NormalizationCheck.No;
            case 2:
            {
                uint num = Normalization.PropValue((int)c);
                if ((num & 16U) != 0U)
                {
                    return NormalizationCheck.No;
                }
                if ((num & 32U) == 0U)
                {
                    return NormalizationCheck.Yes;
                }
                return NormalizationCheck.Maybe;
            }
            case 3:
                if ('가' <= c && c <= '힣')
                {
                    return NormalizationCheck.No;
                }
                if ((Normalization.PropValue((int)c) & 2U) == 0U)
                {
                    return NormalizationCheck.Yes;
                }
                return NormalizationCheck.No;
            default:
            {
                uint num = Normalization.PropValue((int)c);
                if ((num & 4U) != 0U)
                {
                    return NormalizationCheck.No;
                }
                if ((num & 8U) != 0U)
                {
                    return NormalizationCheck.Maybe;
                }
                return NormalizationCheck.Yes;
            }
            }
        }
References System.Text.Normalization.PropValue(), and System.U.
Referenced by System.Text.Normalization.Combine(), System.Text.Normalization.Combine(), System.Text.Normalization.Decompose(), System.Text.Normalization.GetCanonical(), and System.Text.Normalization.IsNormalized().