Terraria Decompiled: System.Text.Normalization.TryComposeWithPreviousStarter
TryComposeWithPreviousStarter()
static int System.Text.Normalization.TryComposeWithPreviousStarter (StringBuilder sb, string s, int current) inline static private
Definition at line 160 of file Normalization.cs.
        {
            int num = current - 1;
            if (Normalization.GetCombiningClass(Normalization.Fetch(sb, s, current)) == 0)
            {
                if (num < 0 || Normalization.GetCombiningClass(Normalization.Fetch(sb, s, num)) != 0)
                {
                    return current + 1;
                }
            }
            else
            {
                while (num >= 0 && Normalization.GetCombiningClass(Normalization.Fetch(sb, s, num)) != 0)
                {
                    num--;
                }
                if (num < 0)
                {
                    return current + 1;
                }
            }
            int num2 = Normalization.Fetch(sb, s, num);
            int primaryCompositeHelperIndex = Normalization.GetPrimaryCompositeHelperIndex(num2);
            if (primaryCompositeHelperIndex == 0)
            {
                return current + 1;
            }
            int num3 = ((sb != null) ? sb.Length : s.Length);
            int num4 = -1;
            for (int i = num + 1; i < num3; i++)
            {
                int num5 = Normalization.Fetch(sb, s, i);
                int num6 = (int)Normalization.GetCombiningClass(num5);
                if (num6 != num4)
                {
                    int num7 = Normalization.TryCompose(primaryCompositeHelperIndex, num2, num5);
                    if (num7 != 0)
                    {
                        if (sb == null)
{
                            return -1;
                        }
                        sb[num] = (char)num7;
                        sb.Remove(i, 1);
                        return current;
                    }
                    else
                    {
                        if (num6 == 0)
{
                            return i + 1;
                        }
                        num4 = num6;
                    }
                }
            }
            return num3;
        }
References System.Text.Normalization.Fetch(), System.Text.Normalization.GetCombiningClass(), System.Text.Normalization.GetPrimaryCompositeHelperIndex(), int, System.Text.StringBuilder.Length, System.Text.StringBuilder.Remove(), System.s, and System.Text.Normalization.TryCompose().
Referenced by System.Text.Normalization.Combine(), and System.Text.Normalization.IsNormalized().