Terraria Decompiled: System.Text.Normalization.CombineHangul
CombineHangul()
static int System.Text.Normalization.CombineHangul (StringBuilder sb, string s, int current) inline static private
Definition at line 94 of file Normalization.cs.
        {
            int num = ((sb != null) ? sb.Length : s.Length);
            int num2 = Normalization.Fetch(sb, s, current);
            int i = current + 1;
            while (i < num)
            {
                int num3 = Normalization.Fetch(sb, s, i);
                int num4 = num2 - 4352;
                if (0 > num4 || num4 >= 19)
                {
                    goto IL_008A;
                }
                int num5 = num3 - 4449;
                if (0 > num5 || num5 >= 21)
                {
                    goto IL_008A;
                }
                if (sb == null)
                {
                    return -1;
                }
                num2 = 44032 + (num4 * 21 + num5) * 28;
                sb[i - 1] = (char)num2;
                sb.Remove(i, 1);
                i--;
                num--;
                IL_00E6:
                i++;
                continue;
                IL_008A:
                int num6 = num2 - 44032;
                if (0 <= num6 && num6 < 11172 && num6 % 28 == 0)
                {
                    int num7 = num3 - 4519;
                    if (0 < num7 && num7 < 28)
                    {
                        if (sb == null)
{
                            return -1;
                        }
                        num2 += num7;
                        sb[i - 1] = (char)num2;
                        sb.Remove(i, 1);
                        i--;
                        num--;
                        goto IL_00E6;
                    }
                }
                num2 = num3;
                goto IL_00E6;
            }
            return num;
        }
References System.Text.Normalization.Fetch(), System.Text.StringBuilder.Length, System.Text.StringBuilder.Remove(), and System.s.
Referenced by System.Text.Normalization.Combine(), and System.Text.Normalization.IsNormalized().