Terraria Decompiled: System.Text.Normalization.GetCanonical
GetCanonical()
static unsafe int System.Text.Normalization.GetCanonical (int c, int[] buf, int bufIdx, int checkType) inline static private
Definition at line 415 of file Normalization.cs.
        {
            int canonicalHangul = Normalization.GetCanonicalHangul(c, buf, bufIdx);
            if (canonicalHangul > bufIdx)
            {
                return canonicalHangul;
            }
            int num = Normalization.CharMapIdx(c);
            if (num == 0 || Normalization.mappedChars[num] == c)
            {
                buf[bufIdx++] = c;
            }
            else
            {
                while (Normalization.mappedChars[num] != 0)
                {
                    int num2 = Normalization.mappedChars[num];
                    if (num2 <= 65535 && Normalization.QuickCheck((char)num2, checkType) == NormalizationCheck.Yes)
                    {
                        buf[bufIdx++] = num2;
                    }
                    else
                    {
                        bufIdx = Normalization.GetCanonical(num2, buf, bufIdx, checkType);
                    }
                    num++;
                }
            }
            return bufIdx;
        }
References System.Text.Normalization.CharMapIdx(), System.Text.Normalization.GetCanonical(), System.Text.Normalization.GetCanonicalHangul(), System.Text.Normalization.mappedChars, and System.Text.Normalization.QuickCheck().
Referenced by System.Text.Normalization.DecomposeChar(), and System.Text.Normalization.GetCanonical().