var InterfaceImplementedInVersionAttribute_8cs =
[
    [ "System.Runtime.InteropServices.WindowsRuntime.InterfaceImplementedInVersionAttribute", "dd/da4/classSystem_1_1Runtime_1_1InteropServices_1_1WindowsRuntime_1_1InterfaceImplementedInVersionAttribute.html", "dd/da4/classSystem_1_1Runtime_1_1InteropServices_1_1WindowsRuntime_1_1InterfaceImplementedInVersionAttribute" ]
];