Terraria Decompiled: Terraria.DataStructures.PlayerDrawLayers.DrawSittingLegs
DrawSittingLegs()
static void Terraria.DataStructures.PlayerDrawLayers.DrawSittingLegs (ref PlayerDrawSet drawinfo, Texture2D textureToDraw, Color matchingColor, int shaderIndex = 0, int legIndex = -1, Vector2 offset = default(Vector2), bool skin = false) inline static private
Definition at line 1636 of file PlayerDrawLayers.cs.
        {
            Vector2 legsOffset = drawinfo.legsOffset;
            Vector2 vector = new Vector2((float)((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.legFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2))), (float)((int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.legFrame.Height + 4f))) + drawinfo.drawPlayer.legPosition + drawinfo.legVect;
            Rectangle rectangle = drawinfo.drawPlayer.legFrame;
            vector.Y -= 2f;
            vector.Y += drawinfo.seatYOffset;
            vector += legsOffset;
            vector += offset;
            int num = 2;
            int num2 = 42;
            int num3 = 2;
            int num4 = 2;
            int num5 = 0;
            int num6 = 0;
            int num7 = 0;
            int num8 = 0;
            int num9 = 0;
            bool flag = false;
            bool flag2 = false;
            bool flag3 = legIndex == 169 || !skin;
            if (flag3)
            {
                if (legIndex > 172)
                {
                    if (legIndex <= 194)
                    {
                        if (legIndex - 177 > 1 && legIndex - 181 > 1)
{
                            if (legIndex - 193 > 1)
{
                                goto IL_041C;
                            }
                            if (drawinfo.drawPlayer.body == 218)
{
                                num = -2;
                                num7 = 2;
                                vector.Y += 2f;
                                goto IL_041C;
                            }
                            goto IL_041C;
                        }
                    }
                    else if (legIndex != 206)
                    {
                        switch (legIndex)
{
                        case 214:
                        case 215:
                        case 216:
                            num = -6;
                            num4 = 2;
                            num5 = 2;
                            num3 = 4;
                            num2 = 6;
                            rectangle = drawinfo.drawPlayer.legFrame;
                            vector.Y += 6f;
                            goto IL_041C;
                        case 217:
                            num = 0;
                            num4 = 0;
                            num5 = 0;
                            num3 = 1;
                            num2 = 0;
                            rectangle = drawinfo.drawPlayer.legFrame;
                            flag2 = true;
                            goto IL_041C;
                        case 218:
                        case 219:
                        case 220:
                        case 221:
                        case 224:
                        case 225:
                            goto IL_041C;
                        case 222:
                            vector.X -= 2f * drawinfo.drawPlayer.Directions.X;
                            goto IL_041C;
                        case 223:
                            vector.X -= 2f * drawinfo.drawPlayer.Directions.X;
                            vector.Y -= drawinfo.seatYOffset;
                            goto IL_041C;
                        case 226:
                            goto IL_0340;
                        default:
                            if (legIndex - 238 > 1)
{
                                goto IL_041C;
                            }
                            num = 2;
                            num4 = 2;
                            num5 = -2;
                            num2 = 42;
                            vector.Y -= drawinfo.seatYOffset;
                            flag = true;
                            goto IL_041C;
                        }
                    }
                    num = 0;
                    num4 = 0;
                    num5 = 0;
                    num3 = 1;
                    num2 = 0;
                    rectangle = drawinfo.drawPlayer.legFrame;
                    num8 = 4;
                    num9 = 6;
                    goto IL_041C;
                }
                if (legIndex > 143)
                {
                    if (legIndex != 149)
                    {
                        if (legIndex != 169)
{
                            if (legIndex - 171 > 1)
{
                                goto IL_041C;
                            }
                        }
                        else
{
                            if (skin)
{
                                num = -6;
                                num4 = 2;
                                num5 = 2;
                                num3 = 4;
                                num2 = 6;
                                rectangle = drawinfo.drawPlayer.legFrame;
                                vector.Y += 6f;
                                goto IL_041C;
                            }
                            num = 0;
                            num4 = 0;
                            num5 = 0;
                            num3 = 1;
                            num2 = 0;
                            rectangle = drawinfo.drawPlayer.legFrame;
                            vector.Y -= drawinfo.seatYOffset;
                            flag = true;
                            goto IL_041C;
                        }
                    }
                    num = -6;
                    num4 = 2;
                    num5 = 2;
                    num3 = 4;
                    num2 = 6;
                    rectangle = drawinfo.drawPlayer.legFrame;
                    vector.Y += 6f;
                    vector.Y -= drawinfo.seatYOffset;
                    goto IL_041C;
                }
                if (legIndex != 106)
                {
                    if (legIndex == 132)
                    {
                        num = -2;
                        num7 = 2;
                        goto IL_041C;
                    }
                    if (legIndex != 143)
                    {
                        goto IL_041C;
                    }
                }
                IL_0340:
                num = 0;
                num4 = 0;
                num2 = 6;
                vector.Y += 4f;
                rectangle.Y = rectangle.Height * 5;
            }
            IL_041C:
            for (int i = num3; i >= 0; i--)
            {
                Vector2 vector2 = vector + new Vector2((float)num, 2f) * new Vector2((float)drawinfo.drawPlayer.direction, 1f);
                Rectangle rectangle2 = rectangle;
                if (!flag2)
                {
                    rectangle2.Y += i * 2;
                    rectangle2.Y += num2;
                    rectangle2.Height -= num2;
                    rectangle2.Height -= i * 2;
                    if (i != num3)
                    {
                        rectangle2.Height = 2;
                    }
                }
                vector2.X += (float)(drawinfo.drawPlayer.direction * num4 * i + num6 * drawinfo.drawPlayer.direction);
                if (i != 0)
                {
                    vector2.X += (float)(num7 * drawinfo.drawPlayer.direction);
                }
                vector2.Y += (float)num2;
                vector2.Y += (float)num5;
                vector2.X += (float)(num8 * drawinfo.drawPlayer.direction);
                vector2.Y += (float)num9;
                DrawData drawData = new DrawData(textureToDraw, vector2, new Rectangle?(rectangle2), matchingColor, drawinfo.drawPlayer.legRotation, drawinfo.legVect, 1f, drawinfo.playerEffect, 0f);
                drawData.shader = shaderIndex;
                if (flag)
                {
                    PlayerDrawLayers.DrawLongCoat(ref drawinfo, ref drawData, legIndex);
                }
                else
                {
                    drawinfo.DrawDataCache.Add(drawData);
                }
            }
        }
References Terraria.DataStructures.PlayerDrawLayers.DrawLongCoat(), System.offset, Terraria.Main.screenPosition, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_12_Skin(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_12_Skin_Composite(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_13_ArmorBackCoat(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_13_Leggings(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_14_Shoes(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_15_SkinLongCoat(), and Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_16_ArmorLongCoat().