Terraria Decompiled: Terraria.DataStructures.PlayerDrawLayers.DrawCompositeArmorPiece
DrawCompositeArmorPiece()
static void Terraria.DataStructures.PlayerDrawLayers.DrawCompositeArmorPiece (ref PlayerDrawSet drawinfo, CompositePlayerDrawContext context, DrawData data, int bodyIndex) inline static
Definition at line 46 of file PlayerDrawLayers.cs.
        {
            drawinfo.DrawDataCache.Add(data);
            if (drawinfo.hideEntirePlayer || drawinfo.hideEntirePlayerExceptHelmetsAndFaceAccessories)
            {
                return;
            }
            switch (context)
            {
            case CompositePlayerDrawContext.BackShoulder:
            case CompositePlayerDrawContext.BackArm:
            case CompositePlayerDrawContext.FrontArm:
            case CompositePlayerDrawContext.FrontShoulder:
                if (drawinfo.armGlowColor.PackedValue > 0U)
                {
                    DrawData drawData = data;
                    drawData.color = drawinfo.armGlowColor;
                    Rectangle value = drawData.sourceRect.Value;
                    value.Y += 224;
                    drawData.sourceRect = new Rectangle?(value);
                    if (bodyIndex == 227)
                    {
                        Vector2 position = drawData.position;
                        for (int i = 0; i < 2; i++)
{
                            Vector2 vector = new Vector2((float)Main.rand.Next(-10, 10) * 0.125f, (float)Main.rand.Next(-10, 10) * 0.125f);
                            drawData.position = position + vector;
                            if (i == 0)
{
                                drawinfo.DrawDataCache.Add(drawData);
                            }
                        }
                    }
                    drawinfo.DrawDataCache.Add(drawData);
                }
                break;
            case CompositePlayerDrawContext.Torso:
                if (drawinfo.bodyGlowColor.PackedValue > 0U)
                {
                    DrawData drawData2 = data;
                    drawData2.color = drawinfo.bodyGlowColor;
                    Rectangle value2 = drawData2.sourceRect.Value;
                    value2.Y += 224;
                    drawData2.sourceRect = new Rectangle?(value2);
                    if (bodyIndex == 227)
                    {
                        Vector2 position2 = drawData2.position;
                        for (int j = 0; j < 2; j++)
{
                            Vector2 vector2 = new Vector2((float)Main.rand.Next(-10, 10) * 0.125f, (float)Main.rand.Next(-10, 10) * 0.125f);
                            drawData2.position = position2 + vector2;
                            if (j == 0)
{
                                drawinfo.DrawDataCache.Add(drawData2);
                            }
                        }
                    }
                    drawinfo.DrawDataCache.Add(drawData2);
                }
                break;
            }
            if (context == CompositePlayerDrawContext.FrontShoulder && drawinfo.drawPlayer.head == 269)
            {
                Vector2 vector3 = drawinfo.helmetOffset + new Vector2((float)((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2))), (float)((int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f))) + drawinfo.drawPlayer.headPosition + drawinfo.headVect;
                drawinfo.drawPlayer.ApplyHeadOffsetFromMount(ref vector3);
                DrawData drawData3 = new DrawData(TextureAssets.Extra[214].Value, vector3, new Rectangle?(drawinfo.drawPlayer.bodyFrame), drawinfo.colorArmorHead, drawinfo.drawPlayer.headRotation, drawinfo.headVect, 1f, drawinfo.playerEffect, 0f);
                drawData3.shader = drawinfo.cHead;
                drawinfo.DrawDataCache.Add(drawData3);
                drawData3 = new DrawData(TextureAssets.GlowMask[308].Value, vector3, new Rectangle?(drawinfo.drawPlayer.bodyFrame), drawinfo.headGlowColor, drawinfo.drawPlayer.headRotation, drawinfo.headVect, 1f, drawinfo.playerEffect, 0f);
                drawData3.shader = drawinfo.cHead;
                drawinfo.DrawDataCache.Add(drawData3);
            }
            if (context == CompositePlayerDrawContext.FrontArm && bodyIndex == 205)
            {
                Color immuneAlphaPure = drawinfo.drawPlayer.GetImmuneAlphaPure(new Color(100, 100, 100, 0), drawinfo.shadow);
                ulong num = (ulong)((long)(drawinfo.drawPlayer.miscCounter / 4));
                int num2 = 4;
                for (int k = 0; k < num2; k++)
                {
                    float num3 = (float)Utils.RandomInt(ref num, -10, 11) * 0.2f;
                    float num4 = (float)Utils.RandomInt(ref num, -10, 1) * 0.15f;
                    DrawData drawData4 = data;
                    Rectangle value3 = drawData4.sourceRect.Value;
                    value3.Y += 224;
                    drawData4.sourceRect = new Rectangle?(value3);
                    drawData4.position.X = drawData4.position.X + num3;
                    drawData4.position.Y = drawData4.position.Y + num4;
                    drawData4.color = immuneAlphaPure;
                    drawinfo.DrawDataCache.Add(drawData4);
                }
            }
            if (bodyIndex == 251)
            {
                DrawData drawData5 = data;
                drawData5.texture = TextureAssets.GlowMask[364].Value;
                drawData5.color = PlayerDrawLayers.GetChickenBonesGlowColor(ref drawinfo, true, false);
                float num5 = drawinfo.stealth * drawinfo.stealth;
                num5 *= 1f - drawinfo.shadow;
                drawData5.color = Color.Multiply(drawData5.color, num5);
                drawinfo.DrawDataCache.Add(drawData5);
                return;
            }
            if (bodyIndex == 259)
            {
                DrawData drawData6 = data;
                drawData6.texture = TextureAssets.GlowMask[376].Value;
                drawData6.color = drawinfo.drawPlayer.GetImmuneAlphaPure(Color.White, drawinfo.shadow);
                float num6 = drawinfo.stealth * drawinfo.stealth;
                num6 *= 1f - drawinfo.shadow;
                drawData6.color = Color.Multiply(drawData6.color, num6);
                drawinfo.DrawDataCache.Add(drawData6);
            }
        }
References Microsoft.Xna.Framework.Vector2.Add(), Microsoft.Xna.Framework.Graphics.Color, Terraria.DataStructures.DrawData.color, Terraria.GameContent.TextureAssets.Extra, Terraria.DataStructures.PlayerDrawLayers.GetChickenBonesGlowColor(), Terraria.GameContent.TextureAssets.GlowMask, Microsoft.Xna.Framework.Color.Multiply(), Terraria.DataStructures.DrawData.position, Terraria.Main.rand, Terraria.Utils.RandomInt(), Terraria.Main.screenPosition, Terraria.DataStructures.DrawData.sourceRect, System.U, System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_12_SkinComposite_BackArmShirt(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_17_TorsoComposite(), and Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_28_ArmOverItemComposite().