Terraria Decompiled: Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_RenderAllLayersSlow
DrawPlayer_RenderAllLayersSlow()
static void Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_RenderAllLayersSlow (ref PlayerDrawSet drawinfo) inline static
Definition at line 4733 of file PlayerDrawLayers.cs.
        {
            int num = -1;
            List<DrawData> drawDataCache = drawinfo.DrawDataCache;
            Effect pixelShader = Main.pixelShader;
            Projectile[] projectile = Main.projectile;
            SpriteBatch spriteBatch = Main.spriteBatch;
            for (int i = 0; i <= drawDataCache.Count; i++)
            {
                if (drawinfo.projectileDrawPosition == i)
                {
                    if (num != 0)
                    {
                        pixelShader.CurrentTechnique.Passes[0].Apply();
                        num = 0;
                    }
                    try
                    {
                        Main.instance.DrawProjDirect(drawinfo.SelectedDrawnProjectile, drawinfo.drawPlayer);
                    }
                    catch
                    {
                        drawinfo.SelectedDrawnProjectile.active = false;
                    }
                }
                if (i != drawDataCache.Count)
                {
                    DrawData drawData = drawDataCache[i];
                    if (drawData.sourceRect == null)
                    {
                        drawData.sourceRect = new Rectangle?(drawData.texture.Frame(1, 1, 0, 0, 0, 0));
                    }
                    PlayerDrawHelper.SetShaderForData(drawinfo.drawPlayer, drawinfo.cHead, ref drawData);
                    num = drawData.shader;
                    if (drawData.texture != null)
                    {
                        drawData.Draw(spriteBatch);
                    }
                }
            }
            pixelShader.CurrentTechnique.Passes[0].Apply();
        }
References System.Collections.Generic.List< T >.Count, Microsoft.Xna.Framework.Graphics.Effect.CurrentTechnique, Terraria.DataStructures.DrawData.Draw(), Terraria.Main.DrawProjDirect(), Terraria.Main.instance, Microsoft.Xna.Framework.Graphics.EffectTechnique.Passes, Terraria.Main.pixelShader, Terraria.Main.projectile, Terraria.DataStructures.PlayerDrawHelper.SetShaderForData(), Terraria.DataStructures.DrawData.shader, Terraria.DataStructures.DrawData.sourceRect, Terraria.Main.spriteBatch, and Terraria.DataStructures.DrawData.texture.