Terraria Decompiled: Terraria.DataStructures.PlayerDrawLayers.DrawStarboardRainbowTrail
DrawStarboardRainbowTrail()
static void Terraria.DataStructures.PlayerDrawLayers.DrawStarboardRainbowTrail (ref PlayerDrawSet drawinfo, Vector2 commonWingPosPreFloor, Vector2 dirsVec) inline static
Definition at line 3164 of file PlayerDrawLayers.cs.
        {
            if (drawinfo.shadow != 0f)
            {
                return;
            }
            int num = Math.Min(drawinfo.drawPlayer.availableAdvancedShadowsCount - 1, 30);
            float num2 = 0f;
            for (int i = num; i > 0; i--)
            {
                EntityShadowInfo advancedShadow = drawinfo.drawPlayer.GetAdvancedShadow(i);
                EntityShadowInfo advancedShadow2 = drawinfo.drawPlayer.GetAdvancedShadow(i - 1);
                num2 += Vector2.Distance(advancedShadow.Position, advancedShadow2.Position);
            }
            float num3 = MathHelper.Clamp(num2 / 160f, 0f, 1f);
            Main.instance.LoadProjectile(250);
            Texture2D value = TextureAssets.Projectile[250].Value;
            float num4 = 1.7f;
            Vector2 vector = new Vector2((float)(value.Width / 2), (float)(value.Height / 2));
            new Vector2((float)drawinfo.drawPlayer.width, (float)drawinfo.drawPlayer.height) / 2f;
            Color white = Color.White;
            white.A = 64;
            Vector2 vector2 = drawinfo.drawPlayer.DefaultSize * new Vector2(0.5f, 1f) + new Vector2(0f, -4f);
            if (dirsVec.Y < 0f)
            {
                vector2 = drawinfo.drawPlayer.DefaultSize * new Vector2(0.5f, 0f) + new Vector2(0f, 4f);
            }
            for (int j = num; j > 0; j--)
            {
                EntityShadowInfo advancedShadow3 = drawinfo.drawPlayer.GetAdvancedShadow(j);
                EntityShadowInfo advancedShadow4 = drawinfo.drawPlayer.GetAdvancedShadow(j - 1);
                Vector2 vector3 = advancedShadow3.Position + vector2 + advancedShadow3.HeadgearOffset;
                Vector2 vector4 = advancedShadow4.Position + vector2 + advancedShadow4.HeadgearOffset;
                vector3 = drawinfo.drawPlayer.RotatedRelativePoint(vector3, true, false);
                vector4 = drawinfo.drawPlayer.RotatedRelativePoint(vector4, true, false);
                float num5 = (vector4 - vector3).ToRotation() - 1.5707964f;
                num5 = 1.5707964f * (float)drawinfo.drawPlayer.direction;
                float num6 = Math.Abs(vector4.X - vector3.X);
                Vector2 vector5 = new Vector2(num4, num6 / (float)value.Height);
                float num7 = 1f - (float)j / (float)num;
                num7 *= num7;
                num7 *= Utils.GetLerpValue(0f, 4f, num6, true);
                num7 *= 0.5f;
                num7 *= num7;
                Color color = white * num7 * num3;
                if (!(color == Color.Transparent))
                {
                    DrawData drawData = new DrawData(value, vector3 - Main.screenPosition, null, color, num5, vector, vector5, drawinfo.playerEffect, 0f);
                    drawData.shader = drawinfo.cWings;
                    drawinfo.DrawDataCache.Add(drawData);
                    for (float num8 = 0.25f; num8 < 1f; num8 += 0.25f)
                    {
                        drawData = new DrawData(value, Vector2.Lerp(vector3, vector4, num8) - Main.screenPosition, null, color, num5, vector, vector5, drawinfo.playerEffect, 0f);
                        drawData.shader = drawinfo.cWings;
                        drawinfo.DrawDataCache.Add(drawData);
                    }
                }
            }
        }
References System.Math.Abs(), Microsoft.Xna.Framework.MathHelper.Clamp(), Microsoft.Xna.Framework.Vector2.Distance(), Terraria.Utils.GetLerpValue(), Terraria.DataStructures.EntityShadowInfo.HeadgearOffset, Terraria.Main.instance, Microsoft.Xna.Framework.Vector2.Lerp(), Terraria.Main.LoadProjectile(), System.Math.Min(), Terraria.DataStructures.EntityShadowInfo.Position, Terraria.GameContent.TextureAssets.Projectile, Terraria.Main.screenPosition, Microsoft.Xna.Framework.Color.Transparent, System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_09_Wings().