Terraria Decompiled: Terraria.DataStructures.PlayerDrawLayers.GetLunaGlowColor
GetLunaGlowColor()
static Color Terraria.DataStructures.PlayerDrawLayers.GetLunaGlowColor (ref PlayerDrawSet drawinfo, bool scaleByShadow) inline static
Definition at line 181 of file PlayerDrawLayers.cs.
        {
            if (drawinfo.hideEntirePlayer || drawinfo.hideEntirePlayerExceptHelmetsAndFaceAccessories)
            {
                return Color.Transparent;
            }
            Color color = new Color(255, 255, 255, 100);
            float num = Utils.Remap(Utils.WrappedLerp(0f, 1f, (float)(drawinfo.drawPlayer.miscCounter % 100) / 100f), 0f, 1f, 0.85f, 1f, true);
            color *= num;
            if (!scaleByShadow)
            {
                return color;
            }
            return drawinfo.drawPlayer.GetImmuneAlphaPure(color, drawinfo.shadow);
        }
References Microsoft.Xna.Framework.Graphics.Color, Terraria.Utils.Remap(), Microsoft.Xna.Framework.Color.Transparent, and Terraria.Utils.WrappedLerp().
Referenced by Terraria.DataStructures.PlayerDrawSet.BoringSetup(), and Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_09_Wings().