Terraria Decompiled: Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_TransformDrawData
DrawPlayer_TransformDrawData()
static void Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_TransformDrawData (ref PlayerDrawSet drawinfo) inline static
Definition at line 4578 of file PlayerDrawLayers.cs.
        {
            float rotation = drawinfo.rotation;
            Vector2 vector = drawinfo.Position - Main.screenPosition + drawinfo.rotationOrigin;
            Vector2 vector2 = drawinfo.drawPlayer.position + drawinfo.rotationOrigin;
            Matrix matrix = Matrix.CreateRotationZ(drawinfo.rotation);
            for (int i = 0; i < drawinfo.DustCache.Count; i++)
            {
                Vector2 vector3 = Main.dust[drawinfo.DustCache[i]].position - vector2;
                vector3 = Vector2.Transform(vector3, matrix);
                Main.dust[drawinfo.DustCache[i]].position = vector3 + vector2;
            }
            for (int j = 0; j < drawinfo.GoreCache.Count; j++)
            {
                Vector2 vector4 = Main.gore[drawinfo.GoreCache[j]].position - vector2;
                vector4 = Vector2.Transform(vector4, matrix);
                Main.gore[drawinfo.GoreCache[j]].position = vector4 + vector2;
            }
            for (int k = 0; k < drawinfo.DrawDataCache.Count; k++)
            {
                DrawData drawData = drawinfo.DrawDataCache[k];
                if (!drawData.ignorePlayerRotation)
                {
                    Vector2 vector5 = drawData.position - vector;
                    vector5 = Vector2.Transform(vector5, matrix);
                    drawData.position = vector5 + vector;
                    drawData.rotation += drawinfo.rotation;
                    drawinfo.DrawDataCache[k] = drawData;
                }
            }
        }
References Microsoft.Xna.Framework.Matrix.CreateRotationZ(), Terraria.Main.dust, Terraria.Main.gore, Terraria.DataStructures.DrawData.ignorePlayerRotation, Terraria.Dust.position, Terraria.Gore.position, and Microsoft.Xna.Framework.Vector2.Transform().
Referenced by Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayer().