Terraria Decompiled: Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_ChippysHeadband
DrawPlayer_ChippysHeadband()
static void Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_ChippysHeadband (ref PlayerDrawSet drawinfo) inline static
Definition at line 2931 of file PlayerDrawLayers.cs.
        {
            Texture2D value = TextureAssets.Extra[279].Value;
            float num = 0.4f;
            float num2 = 0.8f;
            float num3 = 160f;
            Vector2 zero = Vector2.Zero;
            float num4 = 0f;
            bool flag = false;
            bool flag2 = false;
            Vector2 vector = PlayerDrawLayers.DrawPlayer_GetMountOffsetForFaceAcc(ref drawinfo, ref flag, ref flag2);
            Vector2 vector2 = drawinfo.drawPlayer.GetFaceDrawOffset((int)drawinfo.drawPlayer.face);
            if (flag && flag2)
            {
                vector2 += drawinfo.drawPlayer.GetHelmetOffsetAddonFromMount();
            }
            vector2 += vector;
            int num5 = Math.Min(drawinfo.drawPlayer.availableAdvancedShadowsCount - 1, 30);
            float num6 = 0f;
            for (int i = num5; i > 0; i--)
            {
                EntityShadowInfo advancedShadow = drawinfo.drawPlayer.GetAdvancedShadow(i);
                EntityShadowInfo advancedShadow2 = drawinfo.drawPlayer.GetAdvancedShadow(i - 1);
                if (i == 1)
                {
                    num4 = drawinfo.drawPlayer.position.AngleFrom(advancedShadow.Position);
                }
                num6 += Vector2.Distance(advancedShadow.Position, advancedShadow2.Position);
            }
            float num7 = MathHelper.Clamp(num6 / num3, 0f, 1f);
            float num8 = -Main.WindForVisuals * 0.45f * drawinfo.drawPlayer.Directions.Y;
            float num9 = Utils.MultiLerp((float)drawinfo.drawPlayer.miscCounter % 100f / 100f, new float[] { 0.3f, 0.5f, 0.8f, 1f, 0.8f, 1f, 0.7f, 0.6f, 0.8f, 0.3f });
            num8 *= num9;
            float num10 = num7;
            int num11;
            if (num10 >= num2)
            {
                num11 = 2;
            }
            else if (num10 >= num)
            {
                num11 = 1;
            }
            else
            {
                num11 = 0;
            }
            int num12;
            switch (num11)
            {
            default:
                num12 = 0;
                break;
            case 1:
            {
                float num13 = (float)drawinfo.drawPlayer.miscCounter % 24f / 24f;
                num12 = (int)Utils.Lerp(1.0, 6.0, (double)num13);
                break;
            }
            case 2:
            {
                float num13 = (float)drawinfo.drawPlayer.miscCounter % 18f / 18f;
                num12 = (int)Utils.Lerp(7.0, 12.0, (double)num13);
                break;
            }
            }
            float num14 = num4;
            if (num14 != 0f && drawinfo.drawPlayer.Directions.X == -1f)
            {
                num14 += 3.1415927f;
            }
            num14 += num8;
            num14 %= 6.2831855f;
            Rectangle rectangle = value.Frame(1, 13, 0, num12, 0, 0);
            Vector2 vector3 = new Vector2(26f, 22f);
            if (drawinfo.drawPlayer.Directions.X == -1f)
            {
                vector3.X = 46f;
            }
            if (drawinfo.drawPlayer.Directions.Y == -1f)
            {
                vector3.Y = 56f - vector3.Y;
            }
            Vector2 vector4 = new Vector2((float)((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(rectangle.Width / 2) + (float)(drawinfo.drawPlayer.width / 2))), (float)((int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)rectangle.Height + 4f))) + drawinfo.drawPlayer.headPosition + vector3;
            vector2 += new Vector2(1f, -2f) * drawinfo.drawPlayer.Directions;
            Vector2 vector5 = Main.OffsetsPlayerHeadgear[drawinfo.drawPlayer.bodyFrame.Y / drawinfo.drawPlayer.bodyFrame.Height];
            vector5.Y -= 2f;
            vector5 *= drawinfo.drawPlayer.Directions.Y;
            DrawData drawData = new DrawData(value, vector2 + zero + vector4 + vector5, new Rectangle?(rectangle), drawinfo.colorArmorHead, num14, vector3, 1f, drawinfo.playerEffect, 0f);
            drawData.shader = drawinfo.cFace;
            drawinfo.DrawDataCache.Add(drawData);
        }
References Microsoft.Xna.Framework.MathHelper.Clamp(), Microsoft.Xna.Framework.Vector2.Distance(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_GetMountOffsetForFaceAcc(), Terraria.GameContent.TextureAssets.Extra, Microsoft.Xna.Framework.Rectangle.Height, int, Terraria.Utils.Lerp(), System.Math.Min(), Terraria.Utils.MultiLerp(), Terraria.Main.OffsetsPlayerHeadgear, Terraria.DataStructures.EntityShadowInfo.Position, Terraria.Main.screenPosition, System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Rectangle.Width, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_01_3_BackHead().