Terraria Decompiled: Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_22_FaceAcc
DrawPlayer_22_FaceAcc()
static void Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_22_FaceAcc (ref PlayerDrawSet drawinfo) inline static
Definition at line 3061 of file PlayerDrawLayers.cs.
        {
            bool flag = false;
            bool flag2 = false;
            bool flag3 = drawinfo.drawPlayer.head == 287;
            Vector2 vector = PlayerDrawLayers.DrawPlayer_GetMountOffsetForFaceAcc(ref drawinfo, ref flag, ref flag2);
            if (drawinfo.drawPlayer.face > 0 && drawinfo.drawPlayer.face < ArmorIDs.Face.Count && !ArmorIDs.Face.Sets.DrawInFaceUnderHairLayer[(int)drawinfo.drawPlayer.face] && (!flag || ArmorIDs.Face.Sets.CanDrawOnVelociraptorMount[(int)drawinfo.drawPlayer.face]) && (drawinfo.drawPlayer.face != 23 || !flag3))
            {
                Vector2 vector2 = drawinfo.drawPlayer.GetFaceDrawOffset((int)drawinfo.drawPlayer.face);
                if (flag && flag2)
                {
                    vector2 += drawinfo.drawPlayer.GetHelmetOffsetAddonFromMount();
                }
                DrawData drawData = new DrawData(TextureAssets.AccFace[(int)drawinfo.drawPlayer.face].Value, vector2 + vector + new Vector2((float)((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2))), (float)((int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f))) + drawinfo.drawPlayer.headPosition + drawinfo.headVect, new Rectangle?(drawinfo.drawPlayer.bodyFrame), drawinfo.colorArmorHead, drawinfo.drawPlayer.headRotation, drawinfo.headVect, 1f, drawinfo.playerEffect, 0f);
                drawData.shader = drawinfo.cFace;
                drawinfo.DrawDataCache.Add(drawData);
            }
            bool flag4 = drawinfo.drawPlayer.faceMask > 0 && drawinfo.drawPlayer.faceMask < ArmorIDs.Face.Count;
            if (flag4 && drawinfo.drawPlayer.head > 0 && drawinfo.drawPlayer.head < ArmorIDs.Head.Count && (ArmorIDs.Head.Sets.PreventFaceMaskDraw[drawinfo.drawPlayer.head] || ArmorIDs.Head.Sets.DrawFaceMaskUnderHeadLayer[drawinfo.drawPlayer.head]))
            {
                flag4 = false;
            }
            else if (flag4 && drawinfo.drawPlayer.mount.Active && drawinfo.drawPlayer.mount.Type == 54 && !ArmorIDs.Face.Sets.CanDrawOnVelociraptorMount[(int)drawinfo.drawPlayer.faceMask])
            {
                flag4 = false;
            }
            if (flag4)
            {
                Vector2 vector3 = drawinfo.drawPlayer.GetFaceDrawOffset((int)drawinfo.drawPlayer.faceMask);
                if (flag && flag2)
                {
                    vector3 += drawinfo.drawPlayer.GetHelmetOffsetAddonFromMount();
                }
                DrawData drawData = new DrawData(TextureAssets.AccFace[(int)drawinfo.drawPlayer.faceMask].Value, vector3 + vector + drawinfo.helmetOffset + new Vector2((float)((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2))), (float)((int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f))) + drawinfo.drawPlayer.headPosition + drawinfo.headVect, new Rectangle?(drawinfo.drawPlayer.bodyFrame), drawinfo.colorArmorHead, drawinfo.drawPlayer.headRotation, drawinfo.headVect, 1f, drawinfo.playerEffect, 0f);
                drawData.shader = drawinfo.cFaceMask;
                drawinfo.DrawDataCache.Add(drawData);
            }
            bool flag5 = drawinfo.drawPlayer.faceFlower > 0 && drawinfo.drawPlayer.faceFlower < ArmorIDs.Face.Count;
            if (flag5 && drawinfo.drawPlayer.head > 0 && drawinfo.drawPlayer.head < ArmorIDs.Head.Count && ArmorIDs.Head.Sets.PreventFaceFlowerDraw[drawinfo.drawPlayer.head])
            {
                flag5 = false;
            }
            else if (flag5 && drawinfo.drawPlayer.mount.Active && drawinfo.drawPlayer.mount.Type == 54 && !ArmorIDs.Face.Sets.CanDrawOnVelociraptorMount[(int)drawinfo.drawPlayer.faceFlower])
            {
                flag5 = false;
            }
            if (flag5)
            {
                Vector2 vector4 = drawinfo.drawPlayer.GetFaceDrawOffset((int)drawinfo.drawPlayer.faceFlower);
                if (flag && flag2)
                {
                    vector4 += drawinfo.drawPlayer.GetHelmetOffsetAddonFromMount();
                }
                DrawData drawData = new DrawData(TextureAssets.AccFace[(int)drawinfo.drawPlayer.faceFlower].Value, vector4 + vector + drawinfo.helmetOffset + new Vector2((float)((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2))), (float)((int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f))) + drawinfo.drawPlayer.headPosition + drawinfo.headVect, new Rectangle?(drawinfo.drawPlayer.bodyFrame), drawinfo.colorArmorHead, drawinfo.drawPlayer.headRotation, drawinfo.headVect, 1f, drawinfo.playerEffect, 0f);
                drawData.shader = drawinfo.cFaceFlower;
                drawinfo.DrawDataCache.Add(drawData);
            }
            if (drawinfo.drawUnicornHorn)
            {
                Vector2 vector5 = Vector2.Zero;
                if (flag && flag2)
                {
                    vector5 += drawinfo.drawPlayer.GetHelmetOffsetAddonFromMount();
                }
                DrawData drawData = new DrawData(TextureAssets.Extra[143].Value, vector + vector5 + new Vector2((float)((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2))), (float)((int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f))) + drawinfo.drawPlayer.headPosition + drawinfo.headVect, new Rectangle?(drawinfo.drawPlayer.bodyFrame), drawinfo.colorArmorHead, drawinfo.drawPlayer.headRotation, drawinfo.headVect, 1f, drawinfo.playerEffect, 0f);
                drawData.shader = drawinfo.cUnicornHorn;
                drawinfo.DrawDataCache.Add(drawData);
            }
            if (drawinfo.drawAngelHalo)
            {
                Vector2 vector6 = Vector2.Zero;
                if (flag && flag2)
                {
                    vector6 += drawinfo.drawPlayer.GetHelmetOffsetAddonFromMount() + new Vector2(-4f, -14f) * drawinfo.drawPlayer.Directions;
                }
                Color color = drawinfo.drawPlayer.GetImmuneAlphaPure(new Color(200, 200, 200, 150), drawinfo.shadow);
                color *= drawinfo.drawPlayer.stealth;
                Main.instance.LoadAccFace(7);
                DrawData drawData = new DrawData(TextureAssets.AccFace[7].Value, vector + vector6 + new Vector2((float)((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2))), (float)((int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f))) + drawinfo.drawPlayer.headPosition + drawinfo.headVect, new Rectangle?(drawinfo.drawPlayer.bodyFrame), color, drawinfo.drawPlayer.headRotation, drawinfo.headVect, 1f, drawinfo.playerEffect, 0f);
                drawData.shader = drawinfo.cAngelHalo;
                drawinfo.DrawDataCache.Add(drawData);
            }
        }
References Terraria.GameContent.TextureAssets.AccFace, Terraria.ID.ArmorIDs.Face.Sets.CanDrawOnVelociraptorMount, Microsoft.Xna.Framework.Graphics.Color, Terraria.ID.ArmorIDs.Head.Count, Terraria.ID.ArmorIDs.Face.Count, Terraria.ID.ArmorIDs.Head.Sets.DrawFaceMaskUnderHeadLayer, Terraria.ID.ArmorIDs.Face.Sets.DrawInFaceUnderHairLayer, Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_GetMountOffsetForFaceAcc(), Terraria.GameContent.TextureAssets.Extra, Terraria.Main.instance, Terraria.Main.LoadAccFace(), Terraria.ID.ArmorIDs.Head.Sets.PreventFaceFlowerDraw, Terraria.ID.ArmorIDs.Head.Sets.PreventFaceMaskDraw, Terraria.Main.screenPosition, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_23_MountFront(), and Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayer_UseNormalLayers().