Terraria Decompiled: Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_09_Wings
DrawPlayer_09_Wings()
static void Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_09_Wings (ref PlayerDrawSet drawinfo) inline static
Definition at line 651 of file PlayerDrawLayers.cs.
        {
            if (drawinfo.drawPlayer.dead || drawinfo.hideEntirePlayer || drawinfo.hideEntirePlayerExceptHelmetsAndFaceAccessories)
            {
                return;
            }
            Vector2 directions = drawinfo.drawPlayer.Directions;
            Vector2 vector = drawinfo.Position - Main.screenPosition + drawinfo.drawPlayer.Size / 2f;
            Vector2 vector2 = new Vector2(0f, 7f);
            vector = drawinfo.Position - Main.screenPosition + new Vector2((float)(drawinfo.drawPlayer.width / 2), (float)(drawinfo.drawPlayer.height - drawinfo.drawPlayer.bodyFrame.Height / 2)) + vector2;
            if (drawinfo.drawPlayer.wings > 0)
            {
                Main.instance.LoadWings(drawinfo.drawPlayer.wings);
                if (drawinfo.drawPlayer.wings == 22)
                {
                    if (drawinfo.drawPlayer.ShouldDrawWingsThatAreAlwaysAnimated(false))
                    {
                        Main.instance.LoadItemFlames(1866);
                        Color colorArmorBody = drawinfo.colorArmorBody;
                        int num = 26;
                        int num2 = -9;
                        Vector2 vector3 = vector + new Vector2((float)num2, (float)num) * directions;
                        DrawData drawData;
                        if (drawinfo.shadow == 0f && drawinfo.drawPlayer.grappling[0] == -1)
{
                            for (int i = 0; i < 7; i++)
{
                                Color color = new Color(250 - i * 10, 250 - i * 10, 250 - i * 10, 150 - i * 10);
                                Vector2 vector4 = new Vector2((float)Main.rand.Next(-10, 11) * 0.2f, (float)Main.rand.Next(-10, 11) * 0.2f);
                                drawinfo.stealth *= drawinfo.stealth;
                                drawinfo.stealth *= 1f - drawinfo.shadow;
                                color = new Color((int)((float)color.R * drawinfo.stealth), (int)((float)color.G * drawinfo.stealth), (int)((float)color.B * drawinfo.stealth), (int)((float)color.A * drawinfo.stealth));
                                vector4.X = drawinfo.drawPlayer.itemFlamePos[i].X;
                                vector4.Y = -drawinfo.drawPlayer.itemFlamePos[i].Y;
                                vector4 *= 0.5f;
                                Vector2 vector5 = (vector3 + vector4).Floor();
                                drawData = new DrawData(TextureAssets.ItemFlame[1866].Value, vector5, new Rectangle?(new Rectangle(0, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 7 * drawinfo.drawPlayer.wingFrame, TextureAssets.Wings[drawinfo.drawPlayer.wings].Width(), TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 7 - 2)), color, drawinfo.drawPlayer.bodyRotation, new Vector2((float)(TextureAssets.Wings[drawinfo.drawPlayer.wings].Width() / 2), (float)(TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 14)), 1f, drawinfo.playerEffect, 0f);
                                drawData.shader = drawinfo.cWings;
                                drawinfo.DrawDataCache.Add(drawData);
                            }
                        }
                        drawData = new DrawData(TextureAssets.Wings[drawinfo.drawPlayer.wings].Value, vector3.Floor(), new Rectangle?(new Rectangle(0, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 7 * drawinfo.drawPlayer.wingFrame, TextureAssets.Wings[drawinfo.drawPlayer.wings].Width(), TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 7)), colorArmorBody, drawinfo.drawPlayer.bodyRotation, new Vector2((float)(TextureAssets.Wings[drawinfo.drawPlayer.wings].Width() / 2), (float)(TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 14)), 1f, drawinfo.playerEffect, 0f);
                        drawData.shader = drawinfo.cWings;
                        drawinfo.DrawDataCache.Add(drawData);
                        return;
                    }
                }
                else if (drawinfo.drawPlayer.wings == 28)
                {
                    if (drawinfo.drawPlayer.ShouldDrawWingsThatAreAlwaysAnimated(false))
                    {
                        Color colorArmorBody2 = drawinfo.colorArmorBody;
                        Vector2 vector6 = new Vector2(0f, 19f);
                        Vector2 vector7 = vector + vector6 * directions;
                        Texture2D texture2D = TextureAssets.Wings[drawinfo.drawPlayer.wings].Value;
                        Rectangle rectangle = texture2D.Frame(1, 4, 0, drawinfo.drawPlayer.miscCounter / 5 % 4, 0, 0);
                        rectangle.Width -= 2;
                        rectangle.Height -= 2;
                        DrawData drawData = new DrawData(texture2D, vector7.Floor(), new Rectangle?(rectangle), Color.Lerp(colorArmorBody2, Color.White, 1f), drawinfo.drawPlayer.bodyRotation, rectangle.Size() / 2f, 1f, drawinfo.playerEffect, 0f);
                        drawData.shader = drawinfo.cWings;
                        drawinfo.DrawDataCache.Add(drawData);
                        texture2D = TextureAssets.Extra[38].Value;
                        drawData = new DrawData(texture2D, vector7.Floor(), new Rectangle?(rectangle), Color.Lerp(colorArmorBody2, Color.White, 0.5f), drawinfo.drawPlayer.bodyRotation, rectangle.Size() / 2f, 1f, drawinfo.playerEffect, 0f);
                        drawData.shader = drawinfo.cWings;
                        drawinfo.DrawDataCache.Add(drawData);
                        return;
                    }
                }
                else if (drawinfo.drawPlayer.wings == 45)
                {
                    if (drawinfo.drawPlayer.ShouldDrawWingsThatAreAlwaysAnimated(false))
                    {
                        PlayerDrawLayers.DrawStarboardRainbowTrail(ref drawinfo, vector, directions);
                        Color color2 = new Color(255, 255, 255, 255);
                        int num3 = 22;
                        int num4 = 0;
                        Vector2 vector8 = vector + new Vector2((float)num4, (float)num3) * directions;
                        Color color3 = color2 * (1f - drawinfo.shadow);
                        DrawData drawData = new DrawData(TextureAssets.Wings[drawinfo.drawPlayer.wings].Value, vector8.Floor(), new Rectangle?(new Rectangle(0, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 6 * drawinfo.drawPlayer.wingFrame, TextureAssets.Wings[drawinfo.drawPlayer.wings].Width(), TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 6)), color3, drawinfo.drawPlayer.bodyRotation, new Vector2((float)(TextureAssets.Wings[drawinfo.drawPlayer.wings].Width() / 2), (float)(TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 12)), 1f, drawinfo.playerEffect, 0f);
                        drawData.shader = drawinfo.cWings;
                        drawinfo.DrawDataCache.Add(drawData);
                        if (drawinfo.shadow == 0f)
{
                            float num5 = ((float)drawinfo.drawPlayer.miscCounter / 75f * 6.2831855f).ToRotationVector2().X * 4f;
                            Color color4 = new Color(70, 70, 70, 0) * (num5 / 8f + 0.5f) * 0.4f;
                            for (float num6 = 0f; num6 < 6.2831855f; num6 += 1.5707964f)
{
                                drawData = new DrawData(TextureAssets.Wings[drawinfo.drawPlayer.wings].Value, vector8.Floor() + num6.ToRotationVector2() * num5, new Rectangle?(new Rectangle(0, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 6 * drawinfo.drawPlayer.wingFrame, TextureAssets.Wings[drawinfo.drawPlayer.wings].Width(), TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 6)), color4, drawinfo.drawPlayer.bodyRotation, new Vector2((float)(TextureAssets.Wings[drawinfo.drawPlayer.wings].Width() / 2), (float)(TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 12)), 1f, drawinfo.playerEffect, 0f);
                                drawData.shader = drawinfo.cWings;
                                drawinfo.DrawDataCache.Add(drawData);
                            }
                            return;
                        }
                    }
                }
                else if (drawinfo.drawPlayer.wings == 34)
                {
                    if (drawinfo.drawPlayer.ShouldDrawWingsThatAreAlwaysAnimated(false))
                    {
                        drawinfo.stealth *= drawinfo.stealth;
                        drawinfo.stealth *= 1f - drawinfo.shadow;
                        Color color5 = new Color((int)(250f * drawinfo.stealth), (int)(250f * drawinfo.stealth), (int)(250f * drawinfo.stealth), (int)(100f * drawinfo.stealth));
                        Vector2 vector9 = new Vector2(0f, 0f);
                        Texture2D value = TextureAssets.Wings[drawinfo.drawPlayer.wings].Value;
                        Vector2 vector10 = drawinfo.Position + drawinfo.drawPlayer.Size / 2f - Main.screenPosition + vector9 * drawinfo.drawPlayer.Directions - Vector2.UnitX * (float)drawinfo.drawPlayer.direction * 4f;
                        Rectangle rectangle2 = value.Frame(1, 6, 0, drawinfo.drawPlayer.wingFrame, 0, 0);
                        rectangle2.Width -= 2;
                        rectangle2.Height -= 2;
                        DrawData drawData = new DrawData(value, vector10.Floor(), new Rectangle?(rectangle2), color5, drawinfo.drawPlayer.bodyRotation, rectangle2.Size() / 2f, 1f, drawinfo.playerEffect, 0f);
                        drawData.shader = drawinfo.cWings;
                        drawinfo.DrawDataCache.Add(drawData);
                        return;
                    }
                }
                else
                {
                    if (drawinfo.drawPlayer.wings == 51)
                    {
                        drawinfo.stealth *= drawinfo.stealth;
                        drawinfo.stealth *= 1f - drawinfo.shadow;
                        Color color6 = PlayerDrawLayers.GetLunaGlowColor(ref drawinfo, true) * drawinfo.stealth;
                        Vector2 vector11 = new Vector2(0f, (float)((drawinfo.drawPlayer.Directions.Y < 0f) ? 8 : 6));
                        Texture2D value2 = TextureAssets.Wings[drawinfo.drawPlayer.wings].Value;
                        Vector2 vector12 = drawinfo.Position + new Vector2((float)(drawinfo.drawPlayer.width / 2), (float)(drawinfo.drawPlayer.height - drawinfo.drawPlayer.bodyFrame.Height / 2)) - Main.screenPosition + vector11 - Vector2.UnitX * (float)drawinfo.drawPlayer.direction * 4f;
                        Rectangle rectangle3 = value2.Frame(1, 8, 0, drawinfo.drawPlayer.wingFrame, 0, 0);
                        rectangle3.Width -= 2;
                        rectangle3.Height -= 2;
                        DrawData drawData = new DrawData(value2, vector12.Floor(), new Rectangle?(rectangle3), color6, drawinfo.drawPlayer.bodyRotation, rectangle3.Size() / 2f, 1f, drawinfo.playerEffect, 0f);
                        drawData.shader = drawinfo.cWings;
                        drawinfo.DrawDataCache.Add(drawData);
                        return;
                    }
                    if (drawinfo.drawPlayer.wings == 47)
                    {
                        Color colorArmorBody3 = drawinfo.colorArmorBody;
                        Color color7 = PlayerDrawLayers.GetChickenBonesGlowColor(ref drawinfo, true, true);
                        drawinfo.stealth *= drawinfo.stealth;
                        drawinfo.stealth *= 1f - drawinfo.shadow;
                        if (drawinfo.stealth == 1f)
{
                            color7.A = 180;
                        }
                        color7 = Color.Multiply(color7, drawinfo.stealth);
                        Vector2 vector13 = Main.OffsetsPlayerHeadgear[drawinfo.drawPlayer.bodyFrame.Y / drawinfo.drawPlayer.bodyFrame.Height];
                        vector13.Y -= 2f;
                        Vector2 vector14 = new Vector2(1f, 1f) + vector13;
                        Texture2D value3 = TextureAssets.Wings[drawinfo.drawPlayer.wings].Value;
                        Vector2 vector15 = vector + vector14 * drawinfo.drawPlayer.Directions - Vector2.UnitX * (float)drawinfo.drawPlayer.direction * 4f;
                        Rectangle rectangle4 = value3.Frame(1, 11, 0, drawinfo.drawPlayer.wingFrame, 0, 0);
                        rectangle4.Width -= 2;
                        rectangle4.Height -= 2;
                        DrawData drawData = new DrawData(value3, vector15.Floor(), new Rectangle?(rectangle4), colorArmorBody3, drawinfo.drawPlayer.bodyRotation, rectangle4.Size() / 2f, 1f, drawinfo.playerEffect, 0f);
                        drawData.shader = drawinfo.cWings;
                        drawinfo.DrawDataCache.Add(drawData);
                        drawData = new DrawData(TextureAssets.GlowMask[366].Value, vector15.Floor(), new Rectangle?(rectangle4), color7, drawinfo.drawPlayer.bodyRotation, rectangle4.Size() / 2f, 1f, drawinfo.playerEffect, 0f);
                        drawData.shader = drawinfo.cWings;
                        drawinfo.DrawDataCache.Add(drawData);
                        return;
                    }
                    if (drawinfo.drawPlayer.wings == 49)
                    {
                        Color colorArmorBody4 = drawinfo.colorArmorBody;
                        Vector2 vector16 = Main.OffsetsPlayerHeadgear[drawinfo.drawPlayer.bodyFrame.Y / drawinfo.drawPlayer.bodyFrame.Height];
                        vector16.Y -= 2f;
                        Vector2 vector17 = new Vector2(1f, 1f) + vector16;
                        Texture2D value4 = TextureAssets.Wings[drawinfo.drawPlayer.wings].Value;
                        Vector2 vector18 = vector + vector17 * drawinfo.drawPlayer.Directions - Vector2.UnitX * (float)drawinfo.drawPlayer.direction * 4f;
                        Rectangle rectangle5 = value4.Frame(1, 11, 0, drawinfo.drawPlayer.wingFrame, 0, 0);
                        rectangle5.Width -= 2;
                        rectangle5.Height -= 2;
                        DrawData drawData = new DrawData(value4, vector18.Floor(), new Rectangle?(rectangle5), colorArmorBody4, drawinfo.drawPlayer.bodyRotation, rectangle5.Size() / 2f, 1f, drawinfo.playerEffect, 0f);
                        drawData.shader = drawinfo.cWings;
                        drawinfo.DrawDataCache.Add(drawData);
                        return;
                    }
                    if (drawinfo.drawPlayer.wings == 48)
                    {
                        if (drawinfo.drawPlayer.ShouldDrawWingsThatAreAlwaysAnimated(false))
{
                            Color colorArmorBody5 = drawinfo.colorArmorBody;
                            Vector2 vector19 = new Vector2(4f, 0f);
                            Texture2D value5 = TextureAssets.Wings[drawinfo.drawPlayer.wings].Value;
                            Vector2 vector20 = drawinfo.Position + drawinfo.drawPlayer.Size / 2f - Main.screenPosition + vector19 * drawinfo.drawPlayer.Directions - Vector2.UnitX * (float)drawinfo.drawPlayer.direction * 4f;
                            Rectangle rectangle6 = value5.Frame(1, 8, 0, drawinfo.drawPlayer.wingFrame, 0, 0);
                            rectangle6.Width -= 2;
                            rectangle6.Height -= 2;
                            DrawData drawData = new DrawData(value5, vector20.Floor(), new Rectangle?(rectangle6), colorArmorBody5, drawinfo.drawPlayer.bodyRotation, rectangle6.Size() / 2f, 1f, drawinfo.playerEffect, 0f);
                            drawData.shader = drawinfo.cWings;
                            drawinfo.DrawDataCache.Add(drawData);
                            return;
                        }
                    }
                    else
                    {
                        if (drawinfo.drawPlayer.wings == 40)
{
                            drawinfo.stealth *= drawinfo.stealth;
                            drawinfo.stealth *= 1f - drawinfo.shadow;
                            Color color8 = new Color((int)(250f * drawinfo.stealth), (int)(250f * drawinfo.stealth), (int)(250f * drawinfo.stealth), (int)(100f * drawinfo.stealth));
                            Vector2 vector21 = new Vector2(-4f, 0f);
                            Texture2D value6 = TextureAssets.Wings[drawinfo.drawPlayer.wings].Value;
                            Vector2 vector22 = vector + vector21 * directions;
                            for (int j = 0; j < 1; j++)
{
                                SpriteEffects spriteEffects = drawinfo.playerEffect;
                                Vector2 vector23 = new Vector2(1f);
                                Vector2 zero = Vector2.Zero;
                                zero.X = (float)(drawinfo.drawPlayer.direction * 3);
                                if (j == 1)
{
                                    spriteEffects ^= SpriteEffects.FlipHorizontally;
                                    vector23 = new Vector2(0.7f, 1f);
                                    zero.X += (float)(-(float)drawinfo.drawPlayer.direction) * 6f;
                                }
                                Vector2 vector24 = drawinfo.drawPlayer.velocity * -1.5f;
                                int num7 = 0;
                                int num8 = 8;
                                float num9 = 4f;
                                if (drawinfo.drawPlayer.velocity.Y == 0f)
{
                                    num7 = 8;
                                    num8 = 14;
                                    num9 = 3f;
                                }
                                for (int k = num7; k < num8; k++)
{
                                    Vector2 vector25 = vector22;
                                    Rectangle rectangle7 = value6.Frame(1, 14, 0, k, 0, 0);
                                    rectangle7.Width -= 2;
                                    rectangle7.Height -= 2;
                                    int num10 = (k - num7) % (int)num9;
                                    Vector2 vector26 = new Vector2(0f, 0.5f).RotatedBy((double)((drawinfo.drawPlayer.miscCounterNormalized * (2f + (float)num10) + (float)num10 * 0.5f + (float)j * 1.3f) * 6.2831855f), default(Vector2)) * (float)(num10 + 1);
                                    vector25 += vector26;
                                    vector25 += vector24 * ((float)num10 / num9);
                                    vector25 += zero;
                                    DrawData drawData = new DrawData(value6, vector25.Floor(), new Rectangle?(rectangle7), color8, drawinfo.drawPlayer.bodyRotation, rectangle7.Size() / 2f, vector23, spriteEffects, 0f);
                                    drawData.shader = drawinfo.cWings;
                                    drawinfo.DrawDataCache.Add(drawData);
                                }
                            }
                            return;
                        }
                        if (drawinfo.drawPlayer.wings == 39)
{
                            if (drawinfo.drawPlayer.ShouldDrawWingsThatAreAlwaysAnimated(false))
{
                                drawinfo.stealth *= drawinfo.stealth;
                                drawinfo.stealth *= 1f - drawinfo.shadow;
                                Color colorArmorBody6 = drawinfo.colorArmorBody;
                                Vector2 vector27 = new Vector2(-6f, -7f);
                                Texture2D value7 = TextureAssets.Wings[drawinfo.drawPlayer.wings].Value;
                                Vector2 vector28 = vector + vector27 * directions;
                                Rectangle rectangle8 = value7.Frame(1, 6, 0, drawinfo.drawPlayer.wingFrame, 0, 0);
                                rectangle8.Width -= 2;
                                rectangle8.Height -= 2;
                                DrawData drawData = new DrawData(value7, vector28.Floor(), new Rectangle?(rectangle8), colorArmorBody6, drawinfo.drawPlayer.bodyRotation, rectangle8.Size() / 2f, 1f, drawinfo.playerEffect, 0f);
                                drawData.shader = drawinfo.cWings;
                                drawinfo.DrawDataCache.Add(drawData);
                                return;
                            }
                        }
                        else
{
                            DrawData drawData;
                            if (drawinfo.drawPlayer.wings == 50)
{
                                Texture2D value8 = TextureAssets.Wings[drawinfo.drawPlayer.wings].Value;
                                Vector2 zero2 = Vector2.Zero;
                                Vector2 vector29 = vector + zero2 * drawinfo.drawPlayer.Directions - Vector2.UnitX * (float)drawinfo.drawPlayer.direction * 4f;
                                int num11 = 11;
                                Rectangle rectangle9 = value8.Frame(1, num11, 0, drawinfo.drawPlayer.wingFrame, 0, 0);
                                drawData = new DrawData(value8, vector29.Floor(), new Rectangle?(rectangle9), drawinfo.colorArmorBody, drawinfo.drawPlayer.bodyRotation, new Vector2((float)(TextureAssets.Wings[drawinfo.drawPlayer.wings].Width() / 2), (float)(TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / num11 / 2)), 1f, drawinfo.playerEffect, 0f);
                                drawData.shader = drawinfo.cWings;
                                drawinfo.DrawDataCache.Add(drawData);
                                Color color9 = drawinfo.drawPlayer.GetImmuneAlphaPure(Color.White, drawinfo.shadow) * (drawinfo.stealth * drawinfo.stealth) * (1f - drawinfo.shadow);
                                drawData = new DrawData(TextureAssets.Wings[drawinfo.drawPlayer.wings].Value, vector29.Floor(), new Rectangle?(rectangle9), color9, drawinfo.drawPlayer.bodyRotation, new Vector2((float)(TextureAssets.Wings[drawinfo.drawPlayer.wings].Width() / 2), (float)(TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / num11 / 2)), 1f, drawinfo.playerEffect, 0f);
                                drawData.shader = drawinfo.cWings;
                                drawinfo.DrawDataCache.Add(drawData);
                                return;
                            }
                            int num12 = 0;
                            int num13 = 0;
                            int num14 = 4;
                            if (drawinfo.drawPlayer.wings == 43)
{
                                num13 = -5;
                                num12 = -7;
                                num14 = 7;
                            }
                            else if (drawinfo.drawPlayer.wings == 44)
{
                                num14 = 7;
                            }
                            else if (drawinfo.drawPlayer.wings == 5)
{
                                num13 = 4;
                                num12 -= 4;
                            }
                            else if (drawinfo.drawPlayer.wings == 27)
{
                                num13 = 3;
                            }
                            else if (drawinfo.drawPlayer.wings == 41)
{
                                num13 = -1;
                            }
                            else if (drawinfo.drawPlayer.wings == 12)
{
                                num13 = -1;
                                num12 = -1;
                            }
                            Color color10 = drawinfo.colorArmorBody;
                            if (drawinfo.drawPlayer.wings == 9 || drawinfo.drawPlayer.wings == 29)
{
                                drawinfo.stealth *= drawinfo.stealth;
                                drawinfo.stealth *= 1f - drawinfo.shadow;
                                color10 = new Color((int)(250f * drawinfo.stealth), (int)(250f * drawinfo.stealth), (int)(250f * drawinfo.stealth), (int)(100f * drawinfo.stealth));
                            }
                            if (drawinfo.drawPlayer.wings == 10)
{
                                drawinfo.stealth *= drawinfo.stealth;
                                drawinfo.stealth *= 1f - drawinfo.shadow;
                                color10 = new Color((int)(250f * drawinfo.stealth), (int)(250f * drawinfo.stealth), (int)(250f * drawinfo.stealth), (int)(175f * drawinfo.stealth));
                            }
                            if (drawinfo.drawPlayer.wings == 11 && color10.A > Main.gFade)
{
                                color10.A = Main.gFade;
                            }
                            if (drawinfo.drawPlayer.wings == 31)
{
                                color10.A = (byte)(220f * drawinfo.stealth);
                            }
                            if (drawinfo.drawPlayer.wings == 32)
{
                                color10.A = (byte)(127f * drawinfo.stealth);
                            }
                            if (drawinfo.drawPlayer.wings == 6)
{
                                color10.A = (byte)(160f * drawinfo.stealth);
                                color10 *= 0.9f;
                            }
                            Vector2 vector30 = vector + new Vector2((float)(num13 - 9), (float)(num12 + 2)) * directions;
                            drawData = new DrawData(TextureAssets.Wings[drawinfo.drawPlayer.wings].Value, vector30.Floor(), new Rectangle?(new Rectangle(0, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / num14 * drawinfo.drawPlayer.wingFrame, TextureAssets.Wings[drawinfo.drawPlayer.wings].Width(), TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / num14)), color10, drawinfo.drawPlayer.bodyRotation, new Vector2((float)(TextureAssets.Wings[drawinfo.drawPlayer.wings].Width() / 2), (float)(TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / num14 / 2)), 1f, drawinfo.playerEffect, 0f);
                            drawData.shader = drawinfo.cWings;
                            drawinfo.DrawDataCache.Add(drawData);
                            if (drawinfo.drawPlayer.wings == 43 && drawinfo.shadow == 0f)
{
                                float num15 = drawinfo.stealth * drawinfo.stealth;
                                Vector2 vector31 = vector30;
                                Vector2 vector32 = new Vector2((float)(TextureAssets.Wings[drawinfo.drawPlayer.wings].Width() / 2), (float)(TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / num14 / 2));
                                Rectangle rectangle10 = new Rectangle(0, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / num14 * drawinfo.drawPlayer.wingFrame, TextureAssets.Wings[drawinfo.drawPlayer.wings].Width(), TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / num14);
                                for (int l = 0; l < 2; l++)
{
                                    Vector2 vector33 = new Vector2((float)Main.rand.Next(-10, 10) * 0.125f, (float)Main.rand.Next(-10, 10) * 0.125f);
                                    drawData = new DrawData(TextureAssets.GlowMask[272].Value, vector31 + vector33, new Rectangle?(rectangle10), Color.Multiply(new Color(230, 230, 230, 60), num15), drawinfo.drawPlayer.bodyRotation, vector32, 1f, drawinfo.playerEffect, 0f);
                                    drawData.shader = drawinfo.cWings;
                                    drawinfo.DrawDataCache.Add(drawData);
                                }
                            }
                            if (drawinfo.drawPlayer.wings == 23)
{
                                drawinfo.stealth *= drawinfo.stealth;
                                drawinfo.stealth *= 1f - drawinfo.shadow;
                                color10 = new Color((int)(200f * drawinfo.stealth), (int)(200f * drawinfo.stealth), (int)(200f * drawinfo.stealth), (int)(200f * drawinfo.stealth));
                                drawData = new DrawData(TextureAssets.Flames[8].Value, vector30.Floor(), new Rectangle?(new Rectangle(0, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 4 * drawinfo.drawPlayer.wingFrame, TextureAssets.Wings[drawinfo.drawPlayer.wings].Width(), TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 4)), color10, drawinfo.drawPlayer.bodyRotation, new Vector2((float)(TextureAssets.Wings[drawinfo.drawPlayer.wings].Width() / 2), (float)(TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 8)), 1f, drawinfo.playerEffect, 0f);
                                drawData.shader = drawinfo.cWings;
                                drawinfo.DrawDataCache.Add(drawData);
                                return;
                            }
                            if (drawinfo.drawPlayer.wings == 27)
{
                                drawData = new DrawData(TextureAssets.GlowMask[92].Value, vector30.Floor(), new Rectangle?(new Rectangle(0, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 4 * drawinfo.drawPlayer.wingFrame, TextureAssets.Wings[drawinfo.drawPlayer.wings].Width(), TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 4)), new Color(255, 255, 255, 127) * drawinfo.stealth * (1f - drawinfo.shadow), drawinfo.drawPlayer.bodyRotation, new Vector2((float)(TextureAssets.Wings[drawinfo.drawPlayer.wings].Width() / 2), (float)(TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 8)), 1f, drawinfo.playerEffect, 0f);
                                drawData.shader = drawinfo.cWings;
                                drawinfo.DrawDataCache.Add(drawData);
                                return;
                            }
                            if (drawinfo.drawPlayer.wings == 44)
{
                                PlayerRainbowWingsTextureContent playerRainbowWings = TextureAssets.RenderTargets.PlayerRainbowWings;
                                playerRainbowWings.Request();
                                if (playerRainbowWings.IsReady)
{
                                    RenderTarget2D target = playerRainbowWings.GetTarget();
                                    drawData = new DrawData(target, vector30.Floor(), new Rectangle?(new Rectangle(0, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 7 * drawinfo.drawPlayer.wingFrame, TextureAssets.Wings[drawinfo.drawPlayer.wings].Width(), TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 7)), new Color(255, 255, 255, 255) * drawinfo.stealth * (1f - drawinfo.shadow), drawinfo.drawPlayer.bodyRotation, new Vector2((float)(TextureAssets.Wings[drawinfo.drawPlayer.wings].Width() / 2), (float)(TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 14)), 1f, drawinfo.playerEffect, 0f);
                                    drawData.shader = drawinfo.cWings;
                                    drawinfo.DrawDataCache.Add(drawData);
                                    return;
                                }
                            }
                            else
{
                                if (drawinfo.drawPlayer.wings == 30)
{
                                    drawData = new DrawData(TextureAssets.GlowMask[181].Value, vector30.Floor(), new Rectangle?(new Rectangle(0, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 4 * drawinfo.drawPlayer.wingFrame, TextureAssets.Wings[drawinfo.drawPlayer.wings].Width(), TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 4)), new Color(255, 255, 255, 127) * drawinfo.stealth * (1f - drawinfo.shadow), drawinfo.drawPlayer.bodyRotation, new Vector2((float)(TextureAssets.Wings[drawinfo.drawPlayer.wings].Width() / 2), (float)(TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 8)), 1f, drawinfo.playerEffect, 0f);
                                    drawData.shader = drawinfo.cWings;
                                    drawinfo.DrawDataCache.Add(drawData);
                                    return;
                                }
                                if (drawinfo.drawPlayer.wings == 38)
{
                                    Color color11 = drawinfo.ArkhalisColor * drawinfo.stealth * (1f - drawinfo.shadow);
                                    drawData = new DrawData(TextureAssets.GlowMask[251].Value, vector30.Floor(), new Rectangle?(new Rectangle(0, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 4 * drawinfo.drawPlayer.wingFrame, TextureAssets.Wings[drawinfo.drawPlayer.wings].Width(), TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 4)), color11, drawinfo.drawPlayer.bodyRotation, new Vector2((float)(TextureAssets.Wings[drawinfo.drawPlayer.wings].Width() / 2), (float)(TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 8)), 1f, drawinfo.playerEffect, 0f);
                                    drawData.shader = drawinfo.cWings;
                                    drawinfo.DrawDataCache.Add(drawData);
                                    for (int m = drawinfo.drawPlayer.shadowPos.Length - 2; m >= 0; m--)
{
                                        Color color12 = color11;
                                        color12.A = 0;
                                        color12 *= MathHelper.Lerp(1f, 0f, (float)m / 3f);
                                        color12 *= 0.1f;
                                        Vector2 vector34 = drawinfo.drawPlayer.shadowPos[m] - drawinfo.drawPlayer.position;
                                        for (float num16 = 0f; num16 < 1f; num16 += 0.01f)
{
                                            Vector2 vector35 = new Vector2(2f, 0f).RotatedBy((double)(num16 / 0.04f * 6.2831855f), default(Vector2));
                                            drawData = new DrawData(TextureAssets.GlowMask[251].Value, vector35 + vector34 * num16 + vector30, new Rectangle?(new Rectangle(0, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 4 * drawinfo.drawPlayer.wingFrame, TextureAssets.Wings[drawinfo.drawPlayer.wings].Width(), TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 4)), color12 * (1f - num16), drawinfo.drawPlayer.bodyRotation, new Vector2((float)(TextureAssets.Wings[drawinfo.drawPlayer.wings].Width() / 2), (float)(TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 8)), 1f, drawinfo.playerEffect, 0f);
                                            drawData.shader = drawinfo.cWings;
                                            drawinfo.DrawDataCache.Add(drawData);
                                        }
                                    }
                                    return;
                                }
                                if (drawinfo.drawPlayer.wings == 29)
{
                                    drawData = new DrawData(TextureAssets.Wings[drawinfo.drawPlayer.wings].Value, vector30.Floor(), new Rectangle?(new Rectangle(0, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 4 * drawinfo.drawPlayer.wingFrame, TextureAssets.Wings[drawinfo.drawPlayer.wings].Width(), TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 4)), new Color(255, 255, 255, 0) * drawinfo.stealth * (1f - drawinfo.shadow) * 0.5f, drawinfo.drawPlayer.bodyRotation, new Vector2((float)(TextureAssets.Wings[drawinfo.drawPlayer.wings].Width() / 2), (float)(TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 8)), 1.06f, drawinfo.playerEffect, 0f);
                                    drawData.shader = drawinfo.cWings;
                                    drawinfo.DrawDataCache.Add(drawData);
                                    return;
                                }
                                if (drawinfo.drawPlayer.wings == 36)
{
                                    drawData = new DrawData(TextureAssets.GlowMask[213].Value, vector30.Floor(), new Rectangle?(new Rectangle(0, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 4 * drawinfo.drawPlayer.wingFrame, TextureAssets.Wings[drawinfo.drawPlayer.wings].Width(), TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 4)), new Color(255, 255, 255, 0) * drawinfo.stealth * (1f - drawinfo.shadow), drawinfo.drawPlayer.bodyRotation, new Vector2((float)(TextureAssets.Wings[drawinfo.drawPlayer.wings].Width() / 2), (float)(TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 8)), 1.06f, drawinfo.playerEffect, 0f);
                                    drawData.shader = drawinfo.cWings;
                                    drawinfo.DrawDataCache.Add(drawData);
                                    Vector2 vector36 = new Vector2(0f, 2f - drawinfo.shadow * 2f);
                                    for (int n = 0; n < 4; n++)
{
                                        drawData = new DrawData(TextureAssets.GlowMask[213].Value, vector36.RotatedBy((double)(1.5707964f * (float)n), default(Vector2)) + vector30.Floor(), new Rectangle?(new Rectangle(0, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 4 * drawinfo.drawPlayer.wingFrame, TextureAssets.Wings[drawinfo.drawPlayer.wings].Width(), TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 4)), new Color(127, 127, 127, 127) * drawinfo.stealth * (1f - drawinfo.shadow), drawinfo.drawPlayer.bodyRotation, new Vector2((float)(TextureAssets.Wings[drawinfo.drawPlayer.wings].Width() / 2), (float)(TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 8)), 1f, drawinfo.playerEffect, 0f);
                                        drawData.shader = drawinfo.cWings;
                                        drawinfo.DrawDataCache.Add(drawData);
                                    }
                                    return;
                                }
                                if (drawinfo.drawPlayer.wings == 31)
{
                                    Color color13 = new Color(255, 255, 255, 0);
                                    color13 = Color.Lerp(Color.HotPink, Color.Crimson, (float)Math.Cos((double)(6.2831855f * ((float)drawinfo.drawPlayer.miscCounter / 100f))) * 0.4f + 0.5f);
                                    color13.A = 0;
                                    for (int num17 = 0; num17 < 4; num17++)
{
                                        Vector2 vector37 = new Vector2((float)Math.Cos((double)(6.2831855f * ((float)drawinfo.drawPlayer.miscCounter / 60f))) * 0.5f + 0.5f, 0f).RotatedBy((double)((float)num17 * 1.5707964f), default(Vector2)) * 1f;
                                        drawData = new DrawData(TextureAssets.Wings[drawinfo.drawPlayer.wings].Value, vector30.Floor() + vector37, new Rectangle?(new Rectangle(0, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 4 * drawinfo.drawPlayer.wingFrame, TextureAssets.Wings[drawinfo.drawPlayer.wings].Width(), TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 4)), color13 * drawinfo.stealth * (1f - drawinfo.shadow) * 0.5f, drawinfo.drawPlayer.bodyRotation, new Vector2((float)(TextureAssets.Wings[drawinfo.drawPlayer.wings].Width() / 2), (float)(TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 8)), 1f, drawinfo.playerEffect, 0f);
                                        drawData.shader = drawinfo.cWings;
                                        drawinfo.DrawDataCache.Add(drawData);
                                    }
                                    drawData = new DrawData(TextureAssets.Wings[drawinfo.drawPlayer.wings].Value, vector30.Floor(), new Rectangle?(new Rectangle(0, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 4 * drawinfo.drawPlayer.wingFrame, TextureAssets.Wings[drawinfo.drawPlayer.wings].Width(), TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 4)), color13 * drawinfo.stealth * (1f - drawinfo.shadow) * 1f, drawinfo.drawPlayer.bodyRotation, new Vector2((float)(TextureAssets.Wings[drawinfo.drawPlayer.wings].Width() / 2), (float)(TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 8)), 1f, drawinfo.playerEffect, 0f);
                                    drawData.shader = drawinfo.cWings;
                                    drawinfo.DrawDataCache.Add(drawData);
                                    return;
                                }
                                if (drawinfo.drawPlayer.wings == 32)
{
                                    drawData = new DrawData(TextureAssets.GlowMask[183].Value, vector30.Floor(), new Rectangle?(new Rectangle(0, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 4 * drawinfo.drawPlayer.wingFrame, TextureAssets.Wings[drawinfo.drawPlayer.wings].Width(), TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 4)), new Color(255, 255, 255, 0) * drawinfo.stealth * (1f - drawinfo.shadow), drawinfo.drawPlayer.bodyRotation, new Vector2((float)(TextureAssets.Wings[drawinfo.drawPlayer.wings].Width() / 2), (float)(TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 8)), 1.06f, drawinfo.playerEffect, 0f);
                                    drawData.shader = drawinfo.cWings;
                                    drawinfo.DrawDataCache.Add(drawData);
                                }
                            }
                        }
                    }
                }
            }
        }
References Microsoft.Xna.Framework.Color.A, Microsoft.Xna.Framework.Color.B, Microsoft.Xna.Framework.Graphics.Color, System.Math.Cos(), Microsoft.Xna.Framework.Color.Crimson, Terraria.DataStructures.PlayerDrawLayers.DrawStarboardRainbowTrail(), Terraria.GameContent.TextureAssets.Extra, Terraria.GameContent.TextureAssets.Flames, Microsoft.Xna.Framework.Color.G, Terraria.DataStructures.PlayerDrawLayers.GetChickenBonesGlowColor(), Terraria.DataStructures.PlayerDrawLayers.GetLunaGlowColor(), Terraria.GameContent.ARenderTargetContentByRequest.GetTarget(), Terraria.Main.gFade, Terraria.GameContent.TextureAssets.GlowMask, Microsoft.Xna.Framework.Color.HotPink, Terraria.Main.instance, Terraria.GameContent.ARenderTargetContentByRequest.IsReady, Terraria.GameContent.TextureAssets.ItemFlame, Microsoft.Xna.Framework.Color.Lerp(), Microsoft.Xna.Framework.MathHelper.Lerp(), Terraria.Main.LoadItemFlames(), Terraria.Main.LoadWings(), Microsoft.Xna.Framework.Color.Multiply(), Terraria.Main.OffsetsPlayerHeadgear, Terraria.GameContent.TextureAssets.RenderTargets.PlayerRainbowWings, Microsoft.Xna.Framework.Color.R, Terraria.Main.rand, Terraria.GameContent.ARenderTargetContentByRequest.Request(), System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Color.White, Terraria.GameContent.TextureAssets.Wings, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayer_UseNormalLayers().