Terraria Decompiled: System.IO.Enumeration.FileSystemEnumerableFactory.NormalizeInputs
NormalizeInputs()
static void System.IO.Enumeration.FileSystemEnumerableFactory.NormalizeInputs (ref string directory, ref string expression, EnumerationOptions options) inline static package
Definition at line 11 of file FileSystemEnumerableFactory.cs.
        {
            if (Path.IsPathRooted(expression))
            {
                throw new ArgumentException("Second path fragment must not be a drive or UNC name.", "expression");
            }
            ReadOnlySpan<char> directoryName = Path.GetDirectoryName(expression.AsSpan());
            if (directoryName.Length != 0)
            {
                directory = Path.Join(directory, directoryName);
                expression = expression.Substring(directoryName.Length + 1);
            }
            MatchType matchType = options.MatchType;
            if (matchType == MatchType.Simple)
            {
                return;
            }
            if (matchType != MatchType.Win32)
            {
                throw new ArgumentOutOfRangeException("options");
            }
            if (string.IsNullOrEmpty(expression) || expression == "." || expression == "*.*")
            {
                expression = "*";
                return;
            }
            if (Path.DirectorySeparatorChar != '\\' && expression.IndexOfAny(FileSystemEnumerableFactory.s_unixEscapeChars) != -1)
            {
                expression = expression.Replace("\\", "\\\\");
                expression = expression.Replace("\"", "\\\"");
                expression = expression.Replace(">", "\\>");
                expression = expression.Replace("<", "\\<");
            }
            expression = FileSystemName.TranslateWin32Expression(expression);
        }
References System.IO.Path.DirectorySeparatorChar, System.IO.Path.GetDirectoryName(), System.IO.Path.IsPathRooted(), System.IO.Path.Join(), System.ReadOnlySpan< T >.Length, System.options, System.IO.Enumeration.FileSystemEnumerableFactory.s_unixEscapeChars, and System.IO.Enumeration.FileSystemName.TranslateWin32Expression().
Referenced by System.IO.DirectoryInfo.InternalEnumerateInfos(), and System.IO.Directory.InternalEnumeratePaths().