Terraria Decompiled: ReLogic.Content.AsyncAssetLoader.DelayedLoad< T >
DelayedLoad< T >()
void ReLogic.Content.AsyncAssetLoader.DelayedLoad< T > (string assetName, IContentSource source, LoadAssetDelegate< T > callback) inline private
Type Constraints
T : class
Definition at line 135 of file AsyncAssetLoader.cs.
                                                                                                                    : class
        {
            AsyncAssetLoader.<>c__DisplayClass22_0<T> CS$<>8__locals1 = new AsyncAssetLoader.<>c__DisplayClass22_0<T>();
            CS$<>8__locals1.source = source;
            CS$<>8__locals1.assetName = assetName;
            CS$<>8__locals1.<>4__this = this;
            CS$<>8__locals1.callback = callback;
            this._loadDispatcher.Queue(delegate
            {
                AsyncAssetLoader.<>c__DisplayClass22_1<T> CS$<>8__locals2 = new AsyncAssetLoader.<>c__DisplayClass22_1<T>();
                CS$<>8__locals2.CS$<>8__locals1 = CS$<>8__locals1;
                CS$<>8__locals2.extension = CS$<>8__locals1.source.GetExtension(CS$<>8__locals1.assetName);
                if (!CS$<>8__locals1.<>4__this._readers.CanReadExtension(CS$<>8__locals2.extension))
                {
                    ConcurrentQueue<Action> pendingDelayedCallbacks = CS$<>8__locals1.<>4__this._pendingDelayedCallbacks;
                    Action action;
                    if ((action = CS$<>8__locals1.<>9__1) == null)
                    {
                        action = (CS$<>8__locals1.<>9__1 = delegate
{
                            CS$<>8__locals1.callback(false, default(T));
                        });
                    }
                    pendingDelayedCallbacks.Enqueue(action);
                    return;
                }
                byte[] rawContent;
                using (Stream stream = CS$<>8__locals1.source.OpenStream(CS$<>8__locals1.assetName))
                {
                    rawContent = new byte[stream.Length];
                    stream.Read(rawContent, 0, rawContent.Length);
                }
                CS$<>8__locals1.<>4__this._pendingDelayedCallbacks.Enqueue(delegate
                {
                    T t;
                    using (MemoryStream memoryStream = new MemoryStream(rawContent, 0, rawContent.Length, false, true))
                    {
                        t = CS$<>8__locals2.CS$<>8__locals1.<>4__this._readers.Read<T>(memoryStream, CS$<>8__locals2.extension);
                    }
                    CS$<>8__locals2.CS$<>8__locals1.callback(true, t);
                });
            });
        }
References ReLogic.Content.AsyncAssetLoader._loadDispatcher, System.action, ReLogic.Content.AsyncAssetLoader.assetName, ReLogic.Content.AsyncAssetLoader.callback, System.Collections.Concurrent.ConcurrentQueue< T >.Enqueue(), ReLogic.Threading.AsyncActionDispatcher.Queue(), ReLogic.Content.AsyncAssetLoader.rawContent, and ReLogic.Content.AsyncAssetLoader.source.
Referenced by ReLogic.Content.AsyncAssetLoader.Load< T >().