Terraria Decompiled: System.Security.Policy.Url.Prepare
Prepare()
string System.Security.Policy.Url.Prepare (string url) inline private
Definition at line 110 of file Url.cs.
        {
            if (url == null)
            {
                throw new ArgumentNullException("Url");
            }
            if (url == string.Empty)
            {
                throw new FormatException(Locale.GetText("Invalid (empty) Url"));
            }
            if (url.IndexOf(Uri.SchemeDelimiter) > 0)
            {
                if (url.StartsWith("file://"))
                {
                    url = "file://" + url.Substring(7);
                }
                url = new Uri(url, false, false).ToString();
            }
            int num = url.Length - 1;
            if (url[num] == '/')
            {
                url = url.Substring(0, num);
            }
            return url;
        }
References Locale.GetText(), Mono.Security.Uri.SchemeDelimiter, and Mono.Security.Uri.ToString().
Referenced by System.Security.Policy.Url.Url().