Terraria Decompiled: System.Text.ASCIIEncoding.GetBytes
GetBytes() [2/4]
unsafe override int System.Text.ASCIIEncoding.GetBytes (char * chars, int charCount, byte * bytes, int byteCount, EncoderNLS encoder) inline package virtual
Reimplemented from System.Text.Encoding.
Definition at line 381 of file ASCIIEncoding.cs.
        {
            char c = '\0';
            EncoderFallbackBuffer encoderFallbackBuffer = null;
            char* ptr = chars + charCount;
            byte* ptr2 = bytes;
            char* ptr3 = chars;
            EncoderReplacementFallback encoderReplacementFallback;
            if (encoder != null)
            {
                c = encoder._charLeftOver;
                encoderReplacementFallback = encoder.Fallback as EncoderReplacementFallback;
                if (encoder.InternalHasFallbackBuffer)
                {
                    encoderFallbackBuffer = encoder.FallbackBuffer;
                    if (encoderFallbackBuffer.Remaining > 0 && encoder._throwOnOverflow)
                    {
                        throw new ArgumentException(SR.Format("Must complete Convert() operation or call Encoder.Reset() before calling GetBytes() or GetByteCount(). Encoder '{0}' fallback '{1}'.", this.EncodingName, encoder.Fallback.GetType()));
                    }
                    encoderFallbackBuffer.InternalInitialize(ptr3, ptr, encoder, true);
                }
            }
            else
            {
                encoderReplacementFallback = base.EncoderFallback as EncoderReplacementFallback;
            }
            if (encoderReplacementFallback != null && encoderReplacementFallback.MaxCharCount == 1)
            {
                char c2 = encoderReplacementFallback.DefaultString[0];
                if (c2 <= '\u007f')
                {
                    if (c > '\0')
                    {
                        if (byteCount == 0)
{
                            base.ThrowBytesOverflow(encoder, true);
                        }
                        *(bytes++) = (byte)c2;
                        byteCount--;
                    }
                    if (byteCount < charCount)
                    {
                        base.ThrowBytesOverflow(encoder, byteCount < 1);
                        ptr = chars + byteCount;
                    }
                    while (chars < ptr)
                    {
                        char c3 = *(chars++);
                        if (c3 >= '\u0080')
{
                            *(bytes++) = (byte)c2;
                        }
                        else
{
                            *(bytes++) = (byte)c3;
                        }
                    }
                    if (encoder != null)
                    {
                        encoder._charLeftOver = '\0';
                        encoder._charsUsed = (int)((long)(chars - ptr3));
                    }
                    return (int)((long)(bytes - ptr2));
                }
            }
            byte* ptr4 = bytes + byteCount;
            if (c > '\0')
            {
                encoderFallbackBuffer = encoder.FallbackBuffer;
                encoderFallbackBuffer.InternalInitialize(chars, ptr, encoder, true);
                char* ptr5 = chars;
                encoderFallbackBuffer.InternalFallback(c, ref ptr5);
                chars = ptr5;
            }
            char c4;
            while ((c4 = ((encoderFallbackBuffer == null) ? '\0' : encoderFallbackBuffer.InternalGetNextChar())) != '\0' || chars < ptr)
            {
                if (c4 == '\0')
                {
                    c4 = *chars;
                    chars++;
                }
                if (c4 > '\u007f')
                {
                    if (encoderFallbackBuffer == null)
                    {
                        if (encoder == null)
{
                            encoderFallbackBuffer = this.encoderFallback.CreateFallbackBuffer();
                        }
                        else
{
                            encoderFallbackBuffer = encoder.FallbackBuffer;
                        }
                        encoderFallbackBuffer.InternalInitialize(ptr - charCount, ptr, encoder, true);
                    }
                    char* ptr5 = chars;
                    encoderFallbackBuffer.InternalFallback(c4, ref ptr5);
                    chars = ptr5;
                }
                else
                {
                    if (bytes >= ptr4)
                    {
                        if (encoderFallbackBuffer == null || !encoderFallbackBuffer.bFallingBack)
{
                            chars--;
                        }
                        else
{
                            encoderFallbackBuffer.MovePrevious();
                        }
                        base.ThrowBytesOverflow(encoder, bytes == ptr2);
                        break;
                    }
                    *bytes = (byte)c4;
                    bytes++;
                }
            }
            if (encoder != null)
            {
                if (encoderFallbackBuffer != null && !encoderFallbackBuffer.bUsedEncoder)
                {
                    encoder._charLeftOver = '\0';
                }
                encoder._charsUsed = (int)((long)(chars - ptr3));
            }
            return (int)((long)(bytes - ptr2));
        }
References System.Text.EncoderNLS._charLeftOver, System.Text.EncoderNLS._throwOnOverflow, System.Text.EncoderFallbackBuffer.bFallingBack, System.Text.EncoderFallbackBuffer.bUsedEncoder, System.Text.EncoderFallback.CreateFallbackBuffer(), System.Text.EncoderReplacementFallback.DefaultString, System.Text.Encoding.encoderFallback, System.Text.Encoder.Fallback, System.Text.Encoder.FallbackBuffer, SR.Format(), int, System.Text.EncoderFallbackBuffer.InternalFallback(), System.Text.EncoderFallbackBuffer.InternalGetNextChar(), System.Text.Encoder.InternalHasFallbackBuffer, System.Text.EncoderFallbackBuffer.InternalInitialize(), long, System.Text.EncoderReplacementFallback.MaxCharCount, System.Text.EncoderFallbackBuffer.MovePrevious(), and System.Text.EncoderFallbackBuffer.Remaining.