Terraria Decompiled: Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_Plantera
RegisterBoss_Plantera()
void Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_Plantera () inline private
Definition at line 452 of file ItemDropDatabase.cs.
        {
            short num = 262;
            this.RegisterToNPC((int)num, ItemDropRule.BossBag(3328));
            this.RegisterToNPC((int)num, ItemDropRule.MasterModeCommonDrop(4934));
            this.RegisterToNPC((int)num, ItemDropRule.MasterModeDropOnAllPlayers(4806, this._masterModeDropRng));
            LeadingConditionRule leadingConditionRule = new LeadingConditionRule(new Conditions.NotExpert());
            this.RegisterToNPC((int)num, leadingConditionRule);
            LeadingConditionRule leadingConditionRule2 = new LeadingConditionRule(new Conditions.FirstTimeKillingPlantera());
            leadingConditionRule.OnSuccess(leadingConditionRule2, false);
            leadingConditionRule.OnSuccess(ItemDropRule.Common(2109, 7, 1, 1), false);
            leadingConditionRule.OnSuccess(ItemDropRule.Common(1141, 1, 1, 1), false);
            leadingConditionRule.OnSuccess(ItemDropRule.Common(1182, 20, 1, 1), false);
            leadingConditionRule.OnSuccess(ItemDropRule.Common(1305, 50, 1, 1), false);
            leadingConditionRule.OnSuccess(ItemDropRule.Common(1157, 4, 1, 1), false);
            leadingConditionRule.OnSuccess(ItemDropRule.Common(3021, 10, 1, 1), false);
            IItemDropRule itemDropRule = ItemDropRule.Common(758, 1, 1, 1);
            itemDropRule.OnSuccess(ItemDropRule.Common(771, 1, 50, 150), true);
            leadingConditionRule2.OnSuccess(itemDropRule, true);
            leadingConditionRule2.OnFailedConditions(new OneFromRulesRule(1, new IItemDropRule[]
            {
                itemDropRule,
                ItemDropRule.Common(1255, 1, 1, 1),
                ItemDropRule.Common(788, 1, 1, 1),
                ItemDropRule.Common(1178, 1, 1, 1),
                ItemDropRule.Common(1259, 1, 1, 1),
                ItemDropRule.Common(1155, 1, 1, 1),
                ItemDropRule.Common(3018, 1, 1, 1),
                ItemDropRule.Common(5477, 1, 1, 1)
            }), false);
        }
References Terraria.GameContent.ItemDropRules.ItemDropRule.BossBag(), Terraria.GameContent.ItemDropRules.ItemDropRule.Common(), Terraria.GameContent.ItemDropRules.ItemDropRule.MasterModeCommonDrop(), Terraria.GameContent.ItemDropRules.ItemDropRule.MasterModeDropOnAllPlayers(), and Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterToNPC().
Referenced by Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBosses().