Terraria Decompiled: Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_Golem
RegisterBoss_Golem()
void Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_Golem () inline private
Definition at line 712 of file ItemDropDatabase.cs.
        {
            Conditions.NotExpert notExpert = new Conditions.NotExpert();
            short num = 245;
            this.RegisterToNPC((int)num, ItemDropRule.BossBag(3329));
            this.RegisterToNPC((int)num, ItemDropRule.MasterModeCommonDrop(4935));
            this.RegisterToNPC((int)num, ItemDropRule.MasterModeDropOnAllPlayers(4807, this._masterModeDropRng));
            this.RegisterToNPC((int)num, ItemDropRule.ByCondition(notExpert, 2110, 7, 1, 1, 1));
            this.RegisterToNPC((int)num, ItemDropRule.ByCondition(notExpert, 1294, 4, 1, 1, 1));
            IItemDropRule itemDropRule = ItemDropRule.Common(1258, 1, 1, 1);
            itemDropRule.OnSuccess(ItemDropRule.Common(1261, 1, 60, 180), true);
            this.RegisterToNPC((int)num, new LeadingConditionRule(notExpert)).OnSuccess(new OneFromRulesRule(1, new IItemDropRule[]
            {
                itemDropRule,
                ItemDropRule.Common(1122, 1, 1, 1),
                ItemDropRule.Common(899, 1, 1, 1),
                ItemDropRule.Common(1248, 1, 1, 1),
                ItemDropRule.Common(1295, 1, 1, 1),
                ItemDropRule.Common(1296, 1, 1, 1),
                ItemDropRule.Common(1297, 1, 1, 1)
            }), false);
            this.RegisterToNPC((int)num, ItemDropRule.ByCondition(notExpert, 2218, 1, 4, 8, 1));
        }
References Terraria.GameContent.ItemDropRules.ItemDropRule.BossBag(), Terraria.GameContent.ItemDropRules.ItemDropRule.ByCondition(), Terraria.GameContent.ItemDropRules.ItemDropRule.Common(), Terraria.GameContent.ItemDropRules.ItemDropRule.MasterModeCommonDrop(), Terraria.GameContent.ItemDropRules.ItemDropRule.MasterModeDropOnAllPlayers(), and Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterToNPC().
Referenced by Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBosses().