Terraria Decompiled: Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_AncientCultist
RegisterBoss_AncientCultist()
void Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_AncientCultist () inline private
Definition at line 649 of file ItemDropDatabase.cs.
        {
            short num = 439;
            this.RegisterToNPC((int)num, ItemDropRule.MasterModeCommonDrop(4937));
            this.RegisterToNPC((int)num, ItemDropRule.MasterModeDropOnAllPlayers(4809, this._masterModeDropRng));
            this.RegisterToNPC((int)num, ItemDropRule.Common(3372, 7, 1, 1));
            this.RegisterToNPC((int)num, ItemDropRule.Common(3549, 1, 1, 1));
        }
References Terraria.GameContent.ItemDropRules.ItemDropRule.Common(), Terraria.GameContent.ItemDropRules.ItemDropRule.MasterModeCommonDrop(), Terraria.GameContent.ItemDropRules.ItemDropRule.MasterModeDropOnAllPlayers(), and Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterToNPC().
Referenced by Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBosses().