Terraria Decompiled: Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterToNPC
RegisterToNPC()
IItemDropRule Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterToNPC (int type, IItemDropRule entry) inline
Definition at line 63 of file ItemDropDatabase.cs.
        {
            this.RegisterToNPCNetId(type, entry);
            List<int> list;
            if (type > 0 && this._npcNetIdsByType.TryGetValue(type, out list))
            {
                for (int i = 0; i < list.Count; i++)
                {
                    this.RegisterToNPCNetId(list[i], entry);
                }
            }
            return entry;
        }
References Terraria.GameContent.ItemDropRules.ItemDropDatabase._npcNetIdsByType, System.list, Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterToNPCNetId(), and System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue().
Referenced by Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBloodMoonFishing(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_AncientCultist(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_Betsy(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_BOC(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_Deerclops(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_DukeFishron(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_EOC(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_FrostMoon(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_Golem(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_HallowBoss(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_KingSlime(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_LunarTowers(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_MoonLord(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_Plantera(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_PumpkinMoon(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_QueenBee(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_QueenSlime(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_Skeletron(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_SkeletronPrime(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_TheDestroyer(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_WOF(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBossTrophies(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterDD2EventDrops(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterEclipse(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterFoodDrops(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterHardmodeDungeonDrops(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterHardmodeFeathers(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterIceMimic(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterMartianDrops(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterMimic(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterMiscDrops(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterPirateDrops(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterToMultipleNPCs(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterToMultipleNPCsNotRemixSeed(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterToMultipleNPCsRemixSeed(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterTownNPCDrops(), and Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterWeirdRules().