Terraria Decompiled: Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterWeirdRules
RegisterWeirdRules()
void Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterWeirdRules () inline private
Definition at line 751 of file ItemDropDatabase.cs.
        {
            Conditions.BeatAnyMechBoss beatAnyMechBoss = new Conditions.BeatAnyMechBoss();
            this.RegisterToMultipleNPCs(ItemDropRule.NormalvsExpert(3260, 40, 30), new int[] { 86 });
            this.RegisterToNPC(75, ItemDropRule.ByCondition(beatAnyMechBoss, 5662, 200, 1, 1, 1));
            this.RegisterToMultipleNPCs(ItemDropRule.NormalvsExpert(5488, 200, 150), new int[] { 171, 475, 84, 137, 138, 527, 120 });
            this.RegisterToMultipleNPCs(ItemDropRule.NormalvsExpert(5489, 200, 150), new int[]
            {
                170, 180, 473, 474, 83, 179, 101, 98, 94, 182,
                268, 525, 526, 529, 533
            });
        }
References Terraria.GameContent.ItemDropRules.ItemDropRule.ByCondition(), Terraria.GameContent.ItemDropRules.ItemDropRule.NormalvsExpert(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterToMultipleNPCs(), and Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterToNPC().
Referenced by Terraria.GameContent.ItemDropRules.ItemDropDatabase.Populate().