Terraria Decompiled: System.Resources.ResourceWriter.FindTypeCode
FindTypeCode()
ResourceTypeCode System.Resources.ResourceWriter.FindTypeCode (object value, List< string > types) inline private
Definition at line 331 of file ResourceWriter.cs.
        {
            if (value == null)
            {
                return ResourceTypeCode.Null;
            }
            Type type = value.GetType();
            if (type == typeof(string))
            {
                return ResourceTypeCode.String;
            }
            if (type == typeof(int))
            {
                return ResourceTypeCode.Int32;
            }
            if (type == typeof(bool))
            {
                return ResourceTypeCode.Boolean;
            }
            if (type == typeof(char))
            {
                return ResourceTypeCode.Char;
            }
            if (type == typeof(byte))
            {
                return ResourceTypeCode.Byte;
            }
            if (type == typeof(sbyte))
            {
                return ResourceTypeCode.SByte;
            }
            if (type == typeof(short))
            {
                return ResourceTypeCode.Int16;
            }
            if (type == typeof(long))
            {
                return ResourceTypeCode.Int64;
            }
            if (type == typeof(ushort))
            {
                return ResourceTypeCode.UInt16;
            }
            if (type == typeof(uint))
            {
                return ResourceTypeCode.UInt32;
            }
            if (type == typeof(ulong))
            {
                return ResourceTypeCode.UInt64;
            }
            if (type == typeof(float))
            {
                return ResourceTypeCode.Single;
            }
            if (type == typeof(double))
            {
                return ResourceTypeCode.Double;
            }
            if (type == typeof(decimal))
            {
                return ResourceTypeCode.Decimal;
            }
            if (type == typeof(DateTime))
            {
                return ResourceTypeCode.DateTime;
            }
            if (type == typeof(TimeSpan))
            {
                return ResourceTypeCode.TimeSpan;
            }
            if (type == typeof(byte[]))
            {
                return ResourceTypeCode.ByteArray;
            }
            if (type == typeof(ResourceWriter.StreamWrapper))
            {
                return ResourceTypeCode.Stream;
            }
            string text;
            if (type == typeof(ResourceWriter.PrecannedResource))
            {
                text = ((ResourceWriter.PrecannedResource)value).TypeName;
                if (text.StartsWith("ResourceTypeCode.", StringComparison.Ordinal))
                {
                    text = text.Substring(17);
                    return (ResourceTypeCode)Enum.Parse(typeof(ResourceTypeCode), text);
                }
            }
            else
            {
                text = MultitargetingHelpers.GetAssemblyQualifiedName(type, this.typeConverter);
            }
            int num = types.IndexOf(text);
            if (num == -1)
            {
                num = types.Count;
                types.Add(text);
            }
            return num + ResourceTypeCode.StartOfUserTypes;
        }
References System.Collections.Generic.List< T >.Add(), System.Collections.Generic.List< T >.Count, System.Runtime.Versioning.MultitargetingHelpers.GetAssemblyQualifiedName(), System.Type.GetType(), System.Collections.Generic.List< T >.IndexOf(), System.Enum.Parse(), System.text, System.Resources.ResourceWriter.typeConverter, and System.value.
Referenced by System.Resources.ResourceWriter.Generate().