Terraria Decompiled: System.Resources.ResourceWriter.WriteValue
WriteValue()
void System.Resources.ResourceWriter.WriteValue (ResourceTypeCode typeCode, object value, BinaryWriter writer, IFormatter objFormatter) inline private
Definition at line 434 of file ResourceWriter.cs.
        {
            switch (typeCode)
            {
            case ResourceTypeCode.Null:
                return;
            case ResourceTypeCode.String:
                writer.Write((string)value);
                return;
            case ResourceTypeCode.Boolean:
                writer.Write((bool)value);
                return;
            case ResourceTypeCode.Char:
                writer.Write((ushort)((char)value));
                return;
            case ResourceTypeCode.Byte:
                writer.Write((byte)value);
                return;
            case ResourceTypeCode.SByte:
                writer.Write((sbyte)value);
                return;
            case ResourceTypeCode.Int16:
                writer.Write((short)value);
                return;
            case ResourceTypeCode.UInt16:
                writer.Write((ushort)value);
                return;
            case ResourceTypeCode.Int32:
                writer.Write((int)value);
                return;
            case ResourceTypeCode.UInt32:
                writer.Write((uint)value);
                return;
            case ResourceTypeCode.Int64:
                writer.Write((long)value);
                return;
            case ResourceTypeCode.UInt64:
                writer.Write((ulong)value);
                return;
            case ResourceTypeCode.Single:
                writer.Write((float)value);
                return;
            case ResourceTypeCode.Double:
                writer.Write((double)value);
                return;
            case ResourceTypeCode.Decimal:
                writer.Write((decimal)value);
                return;
            case ResourceTypeCode.DateTime:
            {
                long num = ((DateTime)value).ToBinary();
                writer.Write(num);
                return;
            }
            case ResourceTypeCode.TimeSpan:
                writer.Write(((TimeSpan)value).Ticks);
                return;
            case ResourceTypeCode.ByteArray:
            {
                byte[] array = (byte[])value;
                writer.Write(array.Length);
                writer.Write(array, 0, array.Length);
                return;
            }
            case ResourceTypeCode.Stream:
            {
                ResourceWriter.StreamWrapper streamWrapper = (ResourceWriter.StreamWrapper)value;
                if (streamWrapper.m_stream.GetType() == typeof(MemoryStream))
                {
                    MemoryStream memoryStream = (MemoryStream)streamWrapper.m_stream;
                    if (memoryStream.Length > 2147483647L)
                    {
                        throw new ArgumentException(Environment.GetResourceString("Stream length must be non-negative and less than 2^31 - 1 - origin."));
                    }
                    int num2;
                    int num3;
                    memoryStream.InternalGetOriginAndLength(out num2, out num3);
                    byte[] array2 = memoryStream.InternalGetBuffer();
                    writer.Write(num3);
                    writer.Write(array2, num2, num3);
                    return;
                }
                else
                {
                    Stream stream = streamWrapper.m_stream;
                    if (stream.Length > 2147483647L)
                    {
                        throw new ArgumentException(Environment.GetResourceString("Stream length must be non-negative and less than 2^31 - 1 - origin."));
                    }
                    stream.Position = 0L;
                    writer.Write((int)stream.Length);
                    byte[] array3 = new byte[4096];
                    int num4;
                    while ((num4 = stream.Read(array3, 0, array3.Length)) != 0)
                    {
                        writer.Write(array3, 0, num4);
                    }
                    if (streamWrapper.m_closeAfterWrite)
                    {
                        stream.Close();
                        return;
                    }
                    return;
                }
                break;
            }
            }
            objFormatter.Serialize(writer.BaseStream, value);
        }
References System.array, System.IO.BinaryWriter.BaseStream, System.IO.Stream.Close(), System.Resources.DateTime, System.Environment.GetResourceString(), System.IO.MemoryStream.InternalGetBuffer(), System.IO.MemoryStream.InternalGetOriginAndLength(), System.L, System.IO.MemoryStream.Length, System.IO.Stream.Length, System.Resources.ResourceWriter.StreamWrapper.m_closeAfterWrite, System.Resources.ResourceWriter.StreamWrapper.m_stream, System.IO.Stream.Read(), System.Runtime.Serialization.IFormatter.Serialize(), System.value, and System.IO.BinaryWriter.Write().
Referenced by System.Resources.ResourceWriter.Generate().