Terraria Decompiled: System.Resources.ResourceWriter.Generate
Generate()
void System.Resources.ResourceWriter.Generate () inline
Implements System.Resources.IResourceWriter.
Definition at line 215 of file ResourceWriter.cs.
        {
            if (this._resourceList == null)
            {
                throw new InvalidOperationException(Environment.GetResourceString("The resource writer has already been closed and cannot be edited."));
            }
            BinaryWriter binaryWriter = new BinaryWriter(this._output, Encoding.UTF8);
            List<string> list = new List<string>();
            binaryWriter.Write(ResourceManager.MagicNumber);
            binaryWriter.Write(ResourceManager.HeaderVersionNumber);
            MemoryStream memoryStream = new MemoryStream(240);
            BinaryWriter binaryWriter2 = new BinaryWriter(memoryStream);
            binaryWriter2.Write(MultitargetingHelpers.GetAssemblyQualifiedName(typeof(ResourceReader), this.typeConverter));
            binaryWriter2.Write(ResourceManager.ResSetTypeName);
            binaryWriter2.Flush();
            binaryWriter.Write((int)memoryStream.Length);
            binaryWriter.Write(memoryStream.GetBuffer(), 0, (int)memoryStream.Length);
            binaryWriter.Write(2);
            int num = this._resourceList.Count;
            if (this._preserializedData != null)
            {
                num += this._preserializedData.Count;
            }
            binaryWriter.Write(num);
            int[] array = new int[num];
            int[] array2 = new int[num];
            int num2 = 0;
            MemoryStream memoryStream2 = new MemoryStream(num * 40);
            BinaryWriter binaryWriter3 = new BinaryWriter(memoryStream2, Encoding.Unicode);
            Stream stream = null;
            try
            {
                string tempFileName = Path.GetTempFileName();
                File.SetAttributes(tempFileName, FileAttributes.Temporary | FileAttributes.NotContentIndexed);
                stream = new FileStream(tempFileName, FileMode.Open, FileAccess.ReadWrite, FileShare.Read, 4096, FileOptions.DeleteOnClose | FileOptions.SequentialScan);
            }
            catch (UnauthorizedAccessException)
            {
                stream = new MemoryStream();
            }
            catch (IOException)
            {
                stream = new MemoryStream();
            }
            using (stream)
            {
                BinaryWriter binaryWriter4 = new BinaryWriter(stream, Encoding.UTF8);
                IFormatter formatter = new BinaryFormatter(null, new StreamingContext(StreamingContextStates.File | StreamingContextStates.Persistence));
                SortedList sortedList = new SortedList(this._resourceList, FastResourceComparer.Default);
                if (this._preserializedData != null)
                {
                    foreach (KeyValuePair<string, ResourceWriter.PrecannedResource> keyValuePair in this._preserializedData)
                    {
                        sortedList.Add(keyValuePair.Key, keyValuePair.Value);
                    }
                }
                IDictionaryEnumerator enumerator2 = sortedList.GetEnumerator();
                while (enumerator2.MoveNext())
                {
                    array[num2] = FastResourceComparer.HashFunction((string)enumerator2.Key);
                    array2[num2++] = (int)binaryWriter3.Seek(0, SeekOrigin.Current);
                    binaryWriter3.Write((string)enumerator2.Key);
                    binaryWriter3.Write((int)binaryWriter4.Seek(0, SeekOrigin.Current));
                    object value = enumerator2.Value;
                    ResourceTypeCode resourceTypeCode = this.FindTypeCode(value, list);
                    ResourceWriter.Write7BitEncodedInt(binaryWriter4, (int)resourceTypeCode);
                    ResourceWriter.PrecannedResource precannedResource = value as ResourceWriter.PrecannedResource;
                    if (precannedResource != null)
                    {
                        binaryWriter4.Write(precannedResource.Data);
                    }
                    else
                    {
                        this.WriteValue(resourceTypeCode, value, binaryWriter4, formatter);
                    }
                }
                binaryWriter.Write(list.Count);
                for (int i = 0; i < list.Count; i++)
                {
                    binaryWriter.Write(list[i]);
                }
                Array.Sort<int, int>(array, array2);
                binaryWriter.Flush();
                int num3 = (int)binaryWriter.BaseStream.Position & 7;
                if (num3 > 0)
                {
                    for (int j = 0; j < 8 - num3; j++)
                    {
                        binaryWriter.Write("PAD"[j % 3]);
                    }
                }
                foreach (int num4 in array)
                {
                    binaryWriter.Write(num4);
                }
                foreach (int num5 in array2)
                {
                    binaryWriter.Write(num5);
                }
                binaryWriter.Flush();
                binaryWriter3.Flush();
                binaryWriter4.Flush();
                int num6 = (int)(binaryWriter.Seek(0, SeekOrigin.Current) + memoryStream2.Length);
                num6 += 4;
                binaryWriter.Write(num6);
                binaryWriter.Write(memoryStream2.GetBuffer(), 0, (int)memoryStream2.Length);
                binaryWriter3.Close();
                stream.Position = 0L;
                stream.CopyTo(binaryWriter.BaseStream);
                binaryWriter4.Close();
            }
            binaryWriter.Flush();
            this._resourceList = null;
        }
References System.Resources.ResourceWriter._output, System.Resources.ResourceWriter._preserializedData, System.Resources.ResourceWriter._resourceList, System.Collections.SortedList.Add(), System.array, System.IO.BinaryWriter.BaseStream, System.IO.BinaryWriter.Close(), System.IO.Stream.CopyTo(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Resources.ResourceWriter.PrecannedResource.Data, System.Resources.FastResourceComparer.Default, System.Resources.ResourceWriter.FindTypeCode(), System.IO.BinaryWriter.Flush(), System.Runtime.Versioning.MultitargetingHelpers.GetAssemblyQualifiedName(), System.IO.MemoryStream.GetBuffer(), System.Collections.SortedList.GetEnumerator(), System.Environment.GetResourceString(), System.IO.Path.GetTempFileName(), System.Resources.FastResourceComparer.HashFunction(), System.Resources.ResourceManager.HeaderVersionNumber, int, System.Collections.Generic.KeyValuePair< TKey, TValue >.Key, System.Collections.IDictionaryEnumerator.Key, System.L, System.IO.MemoryStream.Length, System.list, System.Resources.ResourceManager.MagicNumber, System.Collections.IEnumerator.MoveNext(), System.IO.Stream.Position, System.Resources.ResourceManager.ResSetTypeName, System.IO.BinaryWriter.Seek(), System.IO.File.SetAttributes(), System.Array.Sort(), System.Resources.ResourceWriter.typeConverter, System.Text.Encoding.Unicode, System.Text.Encoding.UTF8, System.Collections.Generic.KeyValuePair< TKey, TValue >.Value, System.Collections.IDictionaryEnumerator.Value, System.value, System.IO.BinaryWriter.Write(), System.Resources.ResourceWriter.Write7BitEncodedInt(), and System.Resources.ResourceWriter.WriteValue().
Referenced by System.Resources.ResourceWriter.Dispose(), and System.Reflection.Emit.ModuleBuilder.Save().