Terraria Decompiled: Terraria.GameContent.Skies.CreditsRollSky.Update
Update()
override void Terraria.GameContent.Skies.CreditsRollSky.Update (GameTime gameTime) inline
Definition at line 31 of file CreditsRollSky.cs.
        {
            if (FocusHelper.PauseSkies)
            {
                return;
            }
            this._currentTime++;
            float num = 0.008333334f;
            if (Main.gameMenu)
            {
                num = 0.06666667f;
            }
            this._opacity = MathHelper.Clamp(this._opacity + num * (float)this._wantsToBeSeen.ToDirectionInt(), 0f, 1f);
            if (this._opacity == 0f && !this._wantsToBeSeen)
            {
                this._isActive = false;
                return;
            }
            bool flag = true;
            if (!Main.CanPlayCreditsRoll())
            {
                flag = false;
            }
            if (this._currentTime >= this._endTime)
            {
                flag = false;
            }
            if (!flag)
            {
                SkyManager.Instance.Deactivate("CreditsRoll", new object[0]);
            }
        }
References Terraria.GameContent.Skies.CreditsRollSky._currentTime, Terraria.GameContent.Skies.CreditsRollSky._endTime, Terraria.GameContent.Skies.CreditsRollSky._opacity, Terraria.GameContent.Skies.CreditsRollSky._wantsToBeSeen, Terraria.Main.CanPlayCreditsRoll(), Microsoft.Xna.Framework.MathHelper.Clamp(), Terraria.Graphics.Effects.EffectManager< T >.Deactivate(), Terraria.Main.gameMenu, Terraria.Graphics.Effects.SkyManager.Instance, and Terraria.FocusHelper.PauseSkies.