Terraria Decompiled: Terraria.GameContent.Skies.CreditsRollSky.EnsureSegmentsAreMade
EnsureSegmentsAreMade()
void Terraria.GameContent.Skies.CreditsRollSky.EnsureSegmentsAreMade () inline private
Definition at line 123 of file CreditsRollSky.cs.
        {
            if (this._segmentsInMainMenu.Count > 0 && this._segmentsInGame.Count > 0)
            {
                return;
            }
            this._segmentsInGame.Clear();
            this._composer.FillSegments(this._segmentsInGame, out this._endTime, true);
            this._segmentsInMainMenu.Clear();
            this._composer.FillSegments(this._segmentsInMainMenu, out this._endTime, false);
        }
References Terraria.GameContent.Skies.CreditsRollSky._composer, Terraria.GameContent.Skies.CreditsRollSky._endTime, Terraria.GameContent.Skies.CreditsRollSky._segmentsInGame, Terraria.GameContent.Skies.CreditsRollSky._segmentsInMainMenu, System.Collections.Generic.List< T >.Clear(), System.Collections.Generic.List< T >.Count, and Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.FillSegments().
Referenced by Terraria.GameContent.Skies.CreditsRollSky.Activate(), Terraria.GameContent.Skies.CreditsRollSky.CreditsRollSky(), and Terraria.GameContent.Skies.CreditsRollSky.Reset().