Terraria Decompiled: Terraria.GameContent.Creative.CreativePowers.DifficultySliderPower.AddIndication
AddIndication()
static void Terraria.GameContent.Creative.CreativePowers.DifficultySliderPower.AddIndication (UIPanel panel, float yAnchor, string indicationText, string iconImagePath, UIElement::ElementEvent updateEvent, UIElement::MouseEvent clickEvent) inline static private
Definition at line 1742 of file CreativePowers.cs.
            {
                UIImage uiimage = new UIImage(Main.Assets.Request<Texture2D>(iconImagePath, 1))
                {
                    HAlign = 1f,
                    VAlign = yAnchor,
                    Left = new StyleDimension(4f, 0f),
                    Top = new StyleDimension(2f, 0f),
                    RemoveFloatingPointsFromDrawPosition = true
                };
                uiimage.OnMouseOut += CreativePowers.DifficultySliderPower.Button_OnMouseOut;
                uiimage.OnMouseOver += CreativePowers.DifficultySliderPower.Button_OnMouseOver;
                if (updateEvent != null)
                {
                    uiimage.OnUpdate += updateEvent;
                }
                if (clickEvent != null)
                {
                    uiimage.OnLeftClick += clickEvent;
                }
                panel.Append(uiimage);
            }
References Terraria.UI.UIElement.Append(), Terraria.Main.Assets, Terraria.GameContent.Creative.CreativePowers.DifficultySliderPower.Button_OnMouseOut(), and Terraria.GameContent.Creative.CreativePowers.DifficultySliderPower.Button_OnMouseOver().
Referenced by Terraria.GameContent.Creative.CreativePowers.DifficultySliderPower.ProvideSlider().