Terraria Decompiled: Terraria.Graphics.Shaders.GameShaders.Misc
Misc
Dictionary<string, MiscShaderData> Terraria.Graphics.Shaders.GameShaders.Misc = new Dictionary<string, MiscShaderData>() static
Definition at line 27 of file GameShaders.cs.
Referenced by Terraria.GameContent.Animations.Segments.SpriteSegment.MaskedFadeEffect.BeforeDrawing(), Terraria.GameContent.Drawing.NextHorizonRenderer.CloudsEnd(), Terraria.Graphics.EmpressBladeDrawer.Draw(), Terraria.Graphics.FinalFractalHelper.Draw(), Terraria.Graphics.FlameLashDrawer.Draw(), Terraria.Graphics.LightDiscDrawer.Draw(), Terraria.Graphics.MagicMissileDrawer.Draw(), Terraria.Graphics.RainbowRodDrawer.Draw(), Terraria.UI.ItemSlot.Draw(), Terraria.Graphics.StormLightningDrawer.Draw(), Terraria.GameContent.Skies.AuroraSky.DrawAuroraSky(), Terraria.GameContent.Drawing.NextHorizonRenderer.DrawLensFlare(), Terraria.Main.DrawNPCDirect(), Terraria.Main.DrawNPCDirect_HallowBoss(), Terraria.GameContent.UI.States.UIWorldCreation.DrawSpecialSeedRing(), Terraria.GameContent.Shaders.WaterShaderData.DrawWaves(), Terraria.GameContent.Drawing.NextNatureRenderer.DrawWithLitNatureShader(), Terraria.GameContent.PlayerQueenSlimeMountTextureContent.HandleUseRequest(), Terraria.GameContent.PlayerRainbowWingsTextureContent.HandleUseRequest(), Terraria.Initializers.DyeInitializer.LoadMisc(), Terraria.Initializers.DyeInitializer.LoadMiscVertexShaders(), and Terraria.GameContent.Shaders.WaterShaderData.StepLiquids().