Terraria Decompiled: Terraria.GameContent.UI.States.UIWorkshopSelectResourcePackToPublish.SetupGamepadPoints
SetupGamepadPoints()
void Terraria.GameContent.UI.States.UIWorkshopSelectResourcePackToPublish.SetupGamepadPoints (SpriteBatch spriteBatch) inline private
Definition at line 162 of file UIWorkshopSelectResourcePackToPublish.cs.
        {
            UILinkPointNavigator.Shortcuts.BackButtonCommand = 7;
            int num = 3000;
            UILinkPointNavigator.SetPosition(num, this._backPanel.GetInnerDimensions().ToRectangle().Center.ToVector2());
            int num2 = num;
            UILinkPoint uilinkPoint = UILinkPointNavigator.Points[num2];
            uilinkPoint.Unlink();
            uilinkPoint.Right = num2;
            float num3 = 1f / Main.UIScale;
            Rectangle clippingRectangle = this._containerPanel.GetClippingRectangle(spriteBatch);
            Vector2 vector = clippingRectangle.TopLeft() * num3;
            Vector2 vector2 = clippingRectangle.BottomRight() * num3;
            List<SnapPoint> snapPoints = this.GetSnapPoints();
            for (int i = 0; i < snapPoints.Count; i++)
            {
                if (!snapPoints[i].Position.Between(vector, vector2))
                {
                    snapPoints.Remove(snapPoints[i]);
                    i--;
                }
            }
            int num4 = 1;
            SnapPoint[,] array = new SnapPoint[this._entryList.Count, num4];
            foreach (SnapPoint snapPoint in snapPoints.Where((SnapPoint a) => a.Name == "Publish"))
            {
                array[snapPoint.Id, 0] = snapPoint;
            }
            num2 = num + 1;
            int[] array2 = new int[this._entryList.Count];
            for (int j = 0; j < array2.Length; j++)
            {
                array2[j] = -1;
            }
            for (int k = 0; k < num4; k++)
            {
                int num5 = -1;
                for (int l = 0; l < array.GetLength(0); l++)
                {
                    if (array[l, k] != null)
                    {
                        uilinkPoint = UILinkPointNavigator.Points[num2];
                        uilinkPoint.Unlink();
                        UILinkPointNavigator.SetPosition(num2, array[l, k].Position);
                        if (num5 != -1)
{
                            uilinkPoint.Up = num5;
                            UILinkPointNavigator.Points[num5].Down = num2;
                        }
                        if (array2[l] != -1)
{
                            uilinkPoint.Left = array2[l];
                            UILinkPointNavigator.Points[array2[l]].Right = num2;
                        }
                        uilinkPoint.Down = num;
                        if (k == 0)
{
                            UILinkPointNavigator.Points[num].Up = (UILinkPointNavigator.Points[num + 1].Up = num2);
                        }
                        num5 = num2;
                        array2[l] = num2;
                        UILinkPointNavigator.Shortcuts.FANCYUI_HIGHEST_INDEX = num2;
                        num2++;
                    }
                }
            }
            if (PlayerInput.UsingGamepadUI && this._entryList.Count == 0 && UILinkPointNavigator.CurrentPoint > 3000)
            {
                UILinkPointNavigator.ChangePoint(3000);
            }
        }
References Terraria.GameContent.UI.States.UIWorkshopSelectResourcePackToPublish._backPanel, Terraria.GameContent.UI.States.UIWorkshopSelectResourcePackToPublish._containerPanel, Terraria.GameContent.UI.States.UIWorkshopSelectResourcePackToPublish._entryList, System.array, Terraria.UI.Gamepad.UILinkPointNavigator.ChangePoint(), System.Collections.Generic.List< T >.Count, Terraria.GameContent.UI.Elements.UIList.Count, Terraria.UI.Gamepad.UILinkPointNavigator.CurrentPoint, Terraria.UI.UIElement.GetClippingRectangle(), Terraria.UI.UIElement.GetSnapPoints(), Terraria.UI.SnapPoint.Id, Terraria.UI.SnapPoint.Name, Terraria.UI.Gamepad.UILinkPointNavigator.Points, Microsoft.Xna.Framework.Graphics.Position, System.Collections.Generic.List< T >.Remove(), Terraria.UI.Gamepad.UILinkPointNavigator.SetPosition(), Terraria.Main.UIScale, Terraria.UI.Gamepad.UILinkPoint.Unlink(), and Terraria.GameInput.PlayerInput.UsingGamepadUI.
Referenced by Terraria.GameContent.UI.States.UIWorkshopSelectResourcePackToPublish.Draw().