Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.ObjectReader.ResolveSimpleAssemblyName
ResolveSimpleAssemblyName()
static Assembly System.Runtime.Serialization.Formatters.Binary.ObjectReader.ResolveSimpleAssemblyName (AssemblyName assemblyName) inline static private
Definition at line 997 of file ObjectReader.cs.
        {
            StackCrawlMark stackCrawlMark = StackCrawlMark.LookForMe;
            Assembly assembly = RuntimeAssembly.LoadWithPartialNameInternal(assemblyName, null, ref stackCrawlMark);
            if (assembly == null && assemblyName != null)
            {
                assembly = RuntimeAssembly.LoadWithPartialNameInternal(assemblyName.Name, null, ref stackCrawlMark);
            }
            return assembly;
        }
References System.Reflection.RuntimeAssembly.LoadWithPartialNameInternal(), and System.Reflection.AssemblyName.Name.
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectReader.FastBindToType(), and System.Runtime.Serialization.Formatters.Binary.ObjectReader.GetSimplyNamedTypeFromAssembly().