Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.ObjectReader.GetId
GetId()
long System.Runtime.Serialization.Formatters.Binary.ObjectReader.GetId (long objectId) inline package
Definition at line 881 of file ObjectReader.cs.
        {
            if (!this.bFullDeserialization)
            {
                this.InitFullDeserialization();
            }
            if (objectId > 0L)
            {
                return objectId;
            }
            if (this.bOldFormatDetected || objectId == -1L)
            {
                this.bOldFormatDetected = true;
                if (this.valTypeObjectIdTable == null)
                {
                    this.valTypeObjectIdTable = new IntSizedArray();
                }
                long num;
                if ((num = (long)this.valTypeObjectIdTable[(int)objectId]) == 0L)
                {
                    num = 2147483647L + objectId;
                    this.valTypeObjectIdTable[(int)objectId] = (int)num;
                }
                return num;
            }
            return -1L * objectId;
        }
References System.Runtime.Serialization.Formatters.Binary.ObjectReader.bFullDeserialization, System.Runtime.Serialization.Formatters.Binary.ObjectReader.bOldFormatDetected, System.Runtime.Serialization.Formatters.Binary.ObjectReader.InitFullDeserialization(), int, System.L, and System.Runtime.Serialization.Formatters.Binary.ObjectReader.valTypeObjectIdTable.
Referenced by System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadArray(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadMemberReference(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObject(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectString(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMap(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMapTyped(), and System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadSerializationHeaderRecord().