Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseObjectEnd
ParseObjectEnd()
void System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseObjectEnd (ParseRecord pr) inline private
Definition at line 351 of file ObjectReader.cs.
        {
            ParseRecord parseRecord = (ParseRecord)this.stack.Peek();
            if (parseRecord == null)
            {
                parseRecord = pr;
            }
            if (parseRecord.PRobjectPositionEnum == InternalObjectPositionE.Top && parseRecord.PRdtType == Converter.typeofString)
            {
                parseRecord.PRnewObj = parseRecord.PRvalue;
                this.TopObject = parseRecord.PRnewObj;
                return;
            }
            this.stack.Pop();
            ParseRecord parseRecord2 = (ParseRecord)this.stack.Peek();
            if (parseRecord.PRnewObj == null)
            {
                return;
            }
            if (parseRecord.PRobjectTypeEnum == InternalObjectTypeE.Array)
            {
                if (parseRecord.PRobjectPositionEnum == InternalObjectPositionE.Top)
                {
                    this.TopObject = parseRecord.PRnewObj;
                }
                this.RegisterObject(parseRecord.PRnewObj, parseRecord, parseRecord2);
                return;
            }
            parseRecord.PRobjectInfo.PopulateObjectMembers(parseRecord.PRnewObj, parseRecord.PRmemberData);
            if (!parseRecord.PRisRegistered && parseRecord.PRobjectId > 0L)
            {
                this.RegisterObject(parseRecord.PRnewObj, parseRecord, parseRecord2);
            }
            if (parseRecord.PRisValueTypeFixup)
            {
                ((ValueFixup)this.ValueFixupStack.Pop()).Fixup(parseRecord, parseRecord2);
            }
            if (parseRecord.PRobjectPositionEnum == InternalObjectPositionE.Top)
            {
                this.TopObject = parseRecord.PRnewObj;
            }
            parseRecord.PRobjectInfo.ObjectEnd();
        }
References System.L, System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.ObjectEnd(), System.Runtime.Serialization.Formatters.Binary.SerStack.Peek(), System.Runtime.Serialization.Formatters.Binary.SerStack.Pop(), System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.PopulateObjectMembers(), System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRdtType, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRisRegistered, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRisValueTypeFixup, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRmemberData, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRnewObj, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRobjectId, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRobjectInfo, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRobjectPositionEnum, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRobjectTypeEnum, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRvalue, System.Runtime.Serialization.Formatters.Binary.ObjectReader.RegisterObject(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.stack, System.Runtime.Serialization.Formatters.Binary.Converter.typeofString, and System.Runtime.Serialization.Formatters.Binary.ObjectReader.ValueFixupStack.
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectReader.Parse(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseArrayMemberEnd(), and System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseMemberEnd().