Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseArrayMember
ParseArrayMember()
void System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseArrayMember (ParseRecord pr) inline private
Definition at line 541 of file ObjectReader.cs.
        {
            ParseRecord parseRecord = (ParseRecord)this.stack.Peek();
            if (parseRecord.PRarrayTypeEnum == InternalArrayTypeE.Rectangular)
            {
                if (parseRecord.PRmemberIndex > 0)
                {
                    this.NextRectangleMap(parseRecord);
                }
                if (parseRecord.PRisLowerBound)
                {
                    for (int i = 0; i < parseRecord.PRrank; i++)
                    {
                        parseRecord.PRindexMap[i] = parseRecord.PRrectangularMap[i] + parseRecord.PRlowerBoundA[i];
                    }
                }
            }
            else if (!parseRecord.PRisLowerBound)
            {
                parseRecord.PRindexMap[0] = parseRecord.PRmemberIndex;
            }
            else
            {
                parseRecord.PRindexMap[0] = parseRecord.PRlowerBoundA[0] + parseRecord.PRmemberIndex;
            }
            if (pr.PRmemberValueEnum == InternalMemberValueE.Reference)
            {
                object @object = this.m_objectManager.GetObject(pr.PRidRef);
                if (@object == null)
                {
                    int[] array = new int[parseRecord.PRrank];
                    Array.Copy(parseRecord.PRindexMap, 0, array, 0, parseRecord.PRrank);
                    this.m_objectManager.RecordArrayElementFixup(parseRecord.PRobjectId, array, pr.PRidRef);
                }
                else if (parseRecord.PRobjectA != null)
                {
                    parseRecord.PRobjectA[parseRecord.PRindexMap[0]] = @object;
                }
                else
                {
                    ((Array)parseRecord.PRnewObj).SetValue(@object, parseRecord.PRindexMap);
                }
            }
            else if (pr.PRmemberValueEnum == InternalMemberValueE.Nested)
            {
                if (pr.PRdtType == null)
                {
                    pr.PRdtType = parseRecord.PRarrayElementType;
                }
                this.ParseObject(pr);
                this.stack.Push(pr);
                if (parseRecord.PRarrayElementType != null)
                {
                    if (parseRecord.PRarrayElementType.IsValueType && pr.PRarrayElementTypeCode == InternalPrimitiveTypeE.Invalid)
                    {
                        pr.PRisValueTypeFixup = true;
                        this.ValueFixupStack.Push(new ValueFixup((Array)parseRecord.PRnewObj, parseRecord.PRindexMap));
                    }
                    else if (parseRecord.PRobjectA != null)
                    {
                        parseRecord.PRobjectA[parseRecord.PRindexMap[0]] = pr.PRnewObj;
                    }
                    else
                    {
                        ((Array)parseRecord.PRnewObj).SetValue(pr.PRnewObj, parseRecord.PRindexMap);
                    }
                }
            }
            else if (pr.PRmemberValueEnum == InternalMemberValueE.InlineValue)
            {
                if (parseRecord.PRarrayElementType == Converter.typeofString || pr.PRdtType == Converter.typeofString)
                {
                    this.ParseString(pr, parseRecord);
                    if (parseRecord.PRobjectA != null)
                    {
                        parseRecord.PRobjectA[parseRecord.PRindexMap[0]] = pr.PRvalue;
                    }
                    else
                    {
                        ((Array)parseRecord.PRnewObj).SetValue(pr.PRvalue, parseRecord.PRindexMap);
                    }
                }
                else if (parseRecord.PRisArrayVariant)
                {
                    if (pr.PRkeyDt == null)
                    {
                        throw new SerializationException(Environment.GetResourceString("Array element type is Object, 'dt' attribute is null."));
                    }
                    object obj;
                    if (pr.PRdtType == Converter.typeofString)
                    {
                        this.ParseString(pr, parseRecord);
                        obj = pr.PRvalue;
                    }
                    else if (pr.PRdtTypeCode == InternalPrimitiveTypeE.Invalid)
                    {
                        this.CheckSerializable(pr.PRdtType);
                        if (this.IsRemoting && this.formatterEnums.FEsecurityLevel != TypeFilterLevel.Full)
{
                            obj = FormatterServices.GetSafeUninitializedObject(pr.PRdtType);
                        }
                        else
{
                            obj = FormatterServices.GetUninitializedObject(pr.PRdtType);
                        }
                    }
                    else if (pr.PRvarValue != null)
                    {
                        obj = pr.PRvarValue;
                    }
                    else
                    {
                        obj = Converter.FromString(pr.PRvalue, pr.PRdtTypeCode);
                    }
                    if (parseRecord.PRobjectA != null)
                    {
                        parseRecord.PRobjectA[parseRecord.PRindexMap[0]] = obj;
                    }
                    else
                    {
                        ((Array)parseRecord.PRnewObj).SetValue(obj, parseRecord.PRindexMap);
                    }
                }
                else if (parseRecord.PRprimitiveArray != null)
                {
                    parseRecord.PRprimitiveArray.SetValue(pr.PRvalue, parseRecord.PRindexMap[0]);
                }
                else
                {
                    object obj2;
                    if (pr.PRvarValue != null)
                    {
                        obj2 = pr.PRvarValue;
                    }
                    else
                    {
                        obj2 = Converter.FromString(pr.PRvalue, parseRecord.PRarrayElementTypeCode);
                    }
                    if (parseRecord.PRobjectA != null)
                    {
                        parseRecord.PRobjectA[parseRecord.PRindexMap[0]] = obj2;
                    }
                    else
                    {
                        ((Array)parseRecord.PRnewObj).SetValue(obj2, parseRecord.PRindexMap);
                    }
                }
            }
            else if (pr.PRmemberValueEnum == InternalMemberValueE.Null)
            {
                parseRecord.PRmemberIndex += pr.PRnullCount - 1;
            }
            else
            {
                this.ParseError(pr, parseRecord);
            }
            parseRecord.PRmemberIndex++;
        }
References System.array, System.Runtime.Serialization.Formatters.Binary.Array, System.Runtime.Serialization.Formatters.Binary.ObjectReader.CheckSerializable(), System.Array.Copy(), System.Runtime.Serialization.Formatters.Binary.InternalFE.FEsecurityLevel, System.Runtime.Serialization.Formatters.Binary.ObjectReader.formatterEnums, System.Runtime.Serialization.Formatters.Binary.Converter.FromString(), System.Runtime.Serialization.ObjectManager.GetObject(), System.Environment.GetResourceString(), System.Runtime.Serialization.FormatterServices.GetSafeUninitializedObject(), System.Runtime.Serialization.FormatterServices.GetUninitializedObject(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.IsRemoting, System.Type.IsValueType, System.Runtime.Serialization.Formatters.Binary.ObjectReader.m_objectManager, System.Runtime.Serialization.Formatters.Binary.ObjectReader.NextRectangleMap(), System.obj, System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseError(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseObject(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseString(), System.Runtime.Serialization.Formatters.Binary.SerStack.Peek(), System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRarrayElementType, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRarrayElementTypeCode, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRarrayTypeEnum, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRdtType, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRdtTypeCode, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRidRef, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRindexMap, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRisArrayVariant, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRisLowerBound, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRkeyDt, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRlowerBoundA, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRmemberIndex, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRmemberValueEnum, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRnewObj, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRobjectA, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRobjectId, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRprimitiveArray, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRrank, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRrectangularMap, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRvalue, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRvarValue, System.Runtime.Serialization.Formatters.Binary.SerStack.Push(), System.Runtime.Serialization.ObjectManager.RecordArrayElementFixup(), System.Runtime.Serialization.Formatters.Binary.PrimitiveArray.SetValue(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.stack, System.Runtime.Serialization.Formatters.Binary.Converter.typeofString, and System.Runtime.Serialization.Formatters.Binary.ObjectReader.ValueFixupStack.
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseMember().