Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.ObjectReader.Parse
Parse()
void System.Runtime.Serialization.Formatters.Binary.ObjectReader.Parse (ParseRecord pr) inline package
Definition at line 188 of file ObjectReader.cs.
        {
            switch (pr.PRparseTypeEnum)
            {
            case InternalParseTypeE.SerializedStreamHeader:
                this.ParseSerializedStreamHeader(pr);
                return;
            case InternalParseTypeE.Object:
                this.ParseObject(pr);
                return;
            case InternalParseTypeE.Member:
                this.ParseMember(pr);
                return;
            case InternalParseTypeE.ObjectEnd:
                this.ParseObjectEnd(pr);
                return;
            case InternalParseTypeE.MemberEnd:
                this.ParseMemberEnd(pr);
                return;
            case InternalParseTypeE.SerializedStreamHeaderEnd:
                this.ParseSerializedStreamHeaderEnd(pr);
                return;
            case InternalParseTypeE.Envelope:
            case InternalParseTypeE.EnvelopeEnd:
            case InternalParseTypeE.Body:
            case InternalParseTypeE.BodyEnd:
                return;
            }
            throw new SerializationException(Environment.GetResourceString("Invalid element '{0}'.", new object[] { pr.PRname }));
        }
References System.Environment.GetResourceString(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseMember(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseMemberEnd(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseObject(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseObjectEnd(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseSerializedStreamHeader(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseSerializedStreamHeaderEnd(), and System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRparseTypeEnum.
Referenced by System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadArray(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadMemberPrimitiveTyped(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadMemberPrimitiveUnTyped(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadMemberReference(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObject(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectNull(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectString(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMap(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMapTyped(), and System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run().