Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.ObjectReader.FastBindToType
FastBindToType()
Type System.Runtime.Serialization.Formatters.Binary.ObjectReader.FastBindToType (string assemblyName, string typeName) inline package
Definition at line 944 of file ObjectReader.cs.
        {
            Type type = null;
            ObjectReader.TypeNAssembly typeNAssembly = (ObjectReader.TypeNAssembly)this.typeCache.GetCachedValue(typeName);
            if (typeNAssembly == null || typeNAssembly.assemblyName != assemblyName)
            {
                Assembly assembly = null;
                if (this.bSimpleAssembly)
                {
                    try
                    {
                        assembly = ObjectReader.ResolveSimpleAssemblyName(new AssemblyName(assemblyName));
                    }
                    catch (Exception)
                    {
                    }
                    if (assembly == null)
                    {
                        return null;
                    }
                    ObjectReader.GetSimplyNamedTypeFromAssembly(assembly, typeName, ref type);
                }
                else
                {
                    try
                    {
                        assembly = Assembly.Load(assemblyName);
                    }
                    catch (Exception)
                    {
                    }
                    if (assembly == null)
                    {
                        return null;
                    }
                    type = FormatterServices.GetTypeFromAssembly(assembly, typeName);
                }
                if (type == null)
                {
                    return null;
                }
                ObjectReader.CheckTypeForwardedTo(assembly, type.Assembly, type);
                typeNAssembly = new ObjectReader.TypeNAssembly();
                typeNAssembly.type = type;
                typeNAssembly.assemblyName = assemblyName;
                this.typeCache.SetCachedValue(typeNAssembly);
            }
            return typeNAssembly.type;
        }
References System.Type.Assembly, System.Runtime.Serialization.Formatters.Binary.ObjectReader.TypeNAssembly.assemblyName, System.Runtime.Serialization.Formatters.Binary.ObjectReader.bSimpleAssembly, System.Runtime.Serialization.Formatters.Binary.ObjectReader.CheckTypeForwardedTo(), System.Runtime.Serialization.Formatters.Binary.NameCache.GetCachedValue(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.GetSimplyNamedTypeFromAssembly(), System.Runtime.Serialization.FormatterServices.GetTypeFromAssembly(), System.Reflection.Assembly.Load(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ResolveSimpleAssemblyName(), System.Runtime.Serialization.Formatters.Binary.NameCache.SetCachedValue(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.TypeNAssembly.type, and System.Runtime.Serialization.Formatters.Binary.ObjectReader.typeCache.
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectReader.Bind().