Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.ObjectReader.CheckTypeForwardedTo
CheckTypeForwardedTo()
static void System.Runtime.Serialization.Formatters.Binary.ObjectReader.CheckTypeForwardedTo (Assembly sourceAssembly, Assembly destAssembly, Type resolvedType) inline static private
Definition at line 1071 of file ObjectReader.cs.
        {
            if (!FormatterServices.UnsafeTypeForwardersIsEnabled() && sourceAssembly != destAssembly)
            {
                TypeInformation typeInformation = BinaryFormatter.GetTypeInformation(resolvedType);
                if (typeInformation.HasTypeForwardedFrom)
                {
                    try
                    {
                        Assembly.Load(typeInformation.AssemblyString);
                    }
                    catch
                    {
                    }
                }
            }
        }
References System.Runtime.Serialization.Formatters.Binary.TypeInformation.AssemblyString, System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.GetTypeInformation(), System.Runtime.Serialization.Formatters.Binary.TypeInformation.HasTypeForwardedFrom, System.Reflection.Assembly.Load(), and System.Runtime.Serialization.FormatterServices.UnsafeTypeForwardersIsEnabled().
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectReader.FastBindToType(), and System.Runtime.Serialization.Formatters.Binary.ObjectReader.GetType().