Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseString
ParseString()
void System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseString (ParseRecord pr, ParseRecord parentPr) inline private
Definition at line 835 of file ObjectReader.cs.
        {
            if (!pr.PRisRegistered && pr.PRobjectId > 0L)
            {
                this.RegisterObject(pr.PRvalue, pr, parentPr, true);
            }
        }
References System.L, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRisRegistered, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRobjectId, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRvalue, and System.Runtime.Serialization.Formatters.Binary.ObjectReader.RegisterObject().
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseArrayMember(), and System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseMember().