Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.ObjectReader.CreateReadObjectInfo
CreateReadObjectInfo() [1/2]
ReadObjectInfo System.Runtime.Serialization.Formatters.Binary.ObjectReader.CreateReadObjectInfo (Type objectType) inline package
Definition at line 174 of file ObjectReader.cs.
        {
            return ReadObjectInfo.Create(objectType, this.m_surrogates, this.m_context, this.m_objectManager, this.serObjectInfoInit, this.m_formatterConverter, this.bSimpleAssembly);
        }
References System.Runtime.Serialization.Formatters.Binary.ObjectReader.bSimpleAssembly, System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.Create(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.m_context, System.Runtime.Serialization.Formatters.Binary.ObjectReader.m_formatterConverter, System.Runtime.Serialization.Formatters.Binary.ObjectReader.m_objectManager, System.Runtime.Serialization.Formatters.Binary.ObjectReader.m_surrogates, and System.Runtime.Serialization.Formatters.Binary.ObjectReader.serObjectInfoInit.
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectMap.ObjectMap(), and System.Runtime.Serialization.Formatters.Binary.ObjectMap.ObjectMap().