Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseMember
ParseMember()
void System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseMember (ParseRecord pr) inline private
Definition at line 712 of file ObjectReader.cs.
        {
            ParseRecord parseRecord = (ParseRecord)this.stack.Peek();
            InternalMemberTypeE prmemberTypeEnum = pr.PRmemberTypeEnum;
            if (prmemberTypeEnum != InternalMemberTypeE.Field && prmemberTypeEnum == InternalMemberTypeE.Item)
            {
                this.ParseArrayMember(pr);
                return;
            }
            if (pr.PRdtType == null && parseRecord.PRobjectInfo.isTyped)
            {
                pr.PRdtType = parseRecord.PRobjectInfo.GetType(pr.PRname);
                if (pr.PRdtType != null)
                {
                    pr.PRdtTypeCode = Converter.ToCode(pr.PRdtType);
                }
            }
            if (pr.PRmemberValueEnum == InternalMemberValueE.Null)
            {
                parseRecord.PRobjectInfo.AddValue(pr.PRname, null, ref parseRecord.PRsi, ref parseRecord.PRmemberData);
                return;
            }
            if (pr.PRmemberValueEnum == InternalMemberValueE.Nested)
            {
                this.ParseObject(pr);
                this.stack.Push(pr);
                if (pr.PRobjectInfo != null && pr.PRobjectInfo.objectType != null && pr.PRobjectInfo.objectType.IsValueType)
                {
                    pr.PRisValueTypeFixup = true;
                    this.ValueFixupStack.Push(new ValueFixup(parseRecord.PRnewObj, pr.PRname, parseRecord.PRobjectInfo));
                    return;
                }
                parseRecord.PRobjectInfo.AddValue(pr.PRname, pr.PRnewObj, ref parseRecord.PRsi, ref parseRecord.PRmemberData);
                return;
            }
            else
            {
                if (pr.PRmemberValueEnum != InternalMemberValueE.Reference)
                {
                    if (pr.PRmemberValueEnum == InternalMemberValueE.InlineValue)
                    {
                        if (pr.PRdtType == Converter.typeofString)
{
                            this.ParseString(pr, parseRecord);
                            parseRecord.PRobjectInfo.AddValue(pr.PRname, pr.PRvalue, ref parseRecord.PRsi, ref parseRecord.PRmemberData);
                            return;
                        }
                        if (pr.PRdtTypeCode != InternalPrimitiveTypeE.Invalid)
{
                            object obj;
                            if (pr.PRvarValue != null)
{
                                obj = pr.PRvarValue;
                            }
                            else
{
                                obj = Converter.FromString(pr.PRvalue, pr.PRdtTypeCode);
                            }
                            parseRecord.PRobjectInfo.AddValue(pr.PRname, obj, ref parseRecord.PRsi, ref parseRecord.PRmemberData);
                            return;
                        }
                        if (pr.PRarrayTypeEnum == InternalArrayTypeE.Base64)
{
                            parseRecord.PRobjectInfo.AddValue(pr.PRname, Convert.FromBase64String(pr.PRvalue), ref parseRecord.PRsi, ref parseRecord.PRmemberData);
                            return;
                        }
                        if (pr.PRdtType == Converter.typeofObject)
{
                            throw new SerializationException(Environment.GetResourceString("Type is missing for member of type Object '{0}'.", new object[] { pr.PRname }));
                        }
                        this.ParseString(pr, parseRecord);
                        if (pr.PRdtType == Converter.typeofSystemVoid)
{
                            parseRecord.PRobjectInfo.AddValue(pr.PRname, pr.PRdtType, ref parseRecord.PRsi, ref parseRecord.PRmemberData);
                            return;
                        }
                        if (parseRecord.PRobjectInfo.isSi)
{
                            parseRecord.PRobjectInfo.AddValue(pr.PRname, pr.PRvalue, ref parseRecord.PRsi, ref parseRecord.PRmemberData);
                            return;
                        }
                    }
                    else
                    {
                        this.ParseError(pr, parseRecord);
                    }
                    return;
                }
                object @object = this.m_objectManager.GetObject(pr.PRidRef);
                if (@object == null)
                {
                    parseRecord.PRobjectInfo.AddValue(pr.PRname, null, ref parseRecord.PRsi, ref parseRecord.PRmemberData);
                    parseRecord.PRobjectInfo.RecordFixup(parseRecord.PRobjectId, pr.PRname, pr.PRidRef);
                    return;
                }
                parseRecord.PRobjectInfo.AddValue(pr.PRname, @object, ref parseRecord.PRsi, ref parseRecord.PRmemberData);
                return;
            }
        }
References System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.AddValue(), System.Convert.FromBase64String(), System.Runtime.Serialization.Formatters.Binary.Converter.FromString(), System.Runtime.Serialization.ObjectManager.GetObject(), System.Environment.GetResourceString(), System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.GetType(), System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.isSi, System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.isTyped, System.Type.IsValueType, System.Runtime.Serialization.Formatters.Binary.ObjectReader.m_objectManager, System.obj, System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.objectType, System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseArrayMember(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseError(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseObject(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseString(), System.Runtime.Serialization.Formatters.Binary.SerStack.Peek(), System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRarrayTypeEnum, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRdtType, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRdtTypeCode, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRidRef, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRmemberData, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRmemberTypeEnum, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRmemberValueEnum, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRname, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRnewObj, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRobjectId, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRobjectInfo, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRsi, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRvalue, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRvarValue, System.Runtime.Serialization.Formatters.Binary.SerStack.Push(), System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.RecordFixup(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.stack, System.Runtime.Serialization.Formatters.Binary.Converter.ToCode(), System.Runtime.Serialization.Formatters.Binary.Converter.typeofObject, System.Runtime.Serialization.Formatters.Binary.Converter.typeofString, System.Runtime.Serialization.Formatters.Binary.Converter.typeofSystemVoid, and System.Runtime.Serialization.Formatters.Binary.ObjectReader.ValueFixupStack.
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectReader.Parse().