Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseArray
ParseArray()
void System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseArray (ParseRecord pr) inline private
Definition at line 397 of file ObjectReader.cs.
        {
            if (pr.PRarrayTypeEnum == InternalArrayTypeE.Base64)
            {
                if (pr.PRvalue.Length > 0)
                {
                    pr.PRnewObj = Convert.FromBase64String(pr.PRvalue);
                }
                else
                {
                    pr.PRnewObj = new byte[0];
                }
                if (this.stack.Peek() == pr)
                {
                    this.stack.Pop();
                }
                if (pr.PRobjectPositionEnum == InternalObjectPositionE.Top)
                {
                    this.TopObject = pr.PRnewObj;
                }
                ParseRecord parseRecord = (ParseRecord)this.stack.Peek();
                this.RegisterObject(pr.PRnewObj, pr, parseRecord);
            }
            else if (pr.PRnewObj != null && Converter.IsWriteAsByteArray(pr.PRarrayElementTypeCode))
            {
                if (pr.PRobjectPositionEnum == InternalObjectPositionE.Top)
                {
                    this.TopObject = pr.PRnewObj;
                }
                ParseRecord parseRecord2 = (ParseRecord)this.stack.Peek();
                this.RegisterObject(pr.PRnewObj, pr, parseRecord2);
            }
            else if (pr.PRarrayTypeEnum == InternalArrayTypeE.Jagged || pr.PRarrayTypeEnum == InternalArrayTypeE.Single)
            {
                bool flag = true;
                if (pr.PRlowerBoundA == null || pr.PRlowerBoundA[0] == 0)
                {
                    if (pr.PRarrayElementType == Converter.typeofString)
                    {
                        object[] array = new string[pr.PRlengthA[0]];
                        pr.PRobjectA = array;
                        pr.PRnewObj = pr.PRobjectA;
                        flag = false;
                    }
                    else if (pr.PRarrayElementType == Converter.typeofObject)
                    {
                        pr.PRobjectA = new object[pr.PRlengthA[0]];
                        pr.PRnewObj = pr.PRobjectA;
                        flag = false;
                    }
                    else if (pr.PRarrayElementType != null)
                    {
                        pr.PRnewObj = Array.UnsafeCreateInstance(pr.PRarrayElementType, new int[] { pr.PRlengthA[0] });
                    }
                    pr.PRisLowerBound = false;
                }
                else
                {
                    if (pr.PRarrayElementType != null)
                    {
                        pr.PRnewObj = Array.UnsafeCreateInstance(pr.PRarrayElementType, pr.PRlengthA, pr.PRlowerBoundA);
                    }
                    pr.PRisLowerBound = true;
                }
                if (pr.PRarrayTypeEnum == InternalArrayTypeE.Single)
                {
                    if (!pr.PRisLowerBound && Converter.IsWriteAsByteArray(pr.PRarrayElementTypeCode))
                    {
                        pr.PRprimitiveArray = new PrimitiveArray(pr.PRarrayElementTypeCode, (Array)pr.PRnewObj);
                    }
                    else if (flag && pr.PRarrayElementType != null && !pr.PRarrayElementType.IsValueType && !pr.PRisLowerBound)
                    {
                        pr.PRobjectA = (object[])pr.PRnewObj;
                    }
                }
                if (pr.PRobjectPositionEnum == InternalObjectPositionE.Headers)
                {
                    this.headers = (Header[])pr.PRnewObj;
                }
                pr.PRindexMap = new int[1];
            }
            else
            {
                if (pr.PRarrayTypeEnum != InternalArrayTypeE.Rectangular)
                {
                    throw new SerializationException(Environment.GetResourceString("Invalid array type '{0}'.", new object[] { pr.PRarrayTypeEnum }));
                }
                pr.PRisLowerBound = false;
                if (pr.PRlowerBoundA != null)
                {
                    for (int i = 0; i < pr.PRrank; i++)
                    {
                        if (pr.PRlowerBoundA[i] != 0)
{
                            pr.PRisLowerBound = true;
                        }
                    }
                }
                if (pr.PRarrayElementType != null)
                {
                    if (!pr.PRisLowerBound)
                    {
                        pr.PRnewObj = Array.UnsafeCreateInstance(pr.PRarrayElementType, pr.PRlengthA);
                    }
                    else
                    {
                        pr.PRnewObj = Array.UnsafeCreateInstance(pr.PRarrayElementType, pr.PRlengthA, pr.PRlowerBoundA);
                    }
                }
                int num = 1;
                for (int j = 0; j < pr.PRrank; j++)
                {
                    num *= pr.PRlengthA[j];
                }
                pr.PRindexMap = new int[pr.PRrank];
                pr.PRrectangularMap = new int[pr.PRrank];
                pr.PRlinearlength = num;
            }
            this.CheckSecurity(pr);
        }
References System.array, System.Runtime.Serialization.Formatters.Binary.ObjectReader.CheckSecurity(), System.Convert.FromBase64String(), System.Environment.GetResourceString(), System.Type.IsValueType, System.Runtime.Serialization.Formatters.Binary.Converter.IsWriteAsByteArray(), System.Runtime.Serialization.Formatters.Binary.SerStack.Peek(), System.Runtime.Serialization.Formatters.Binary.SerStack.Pop(), System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRarrayElementType, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRarrayElementTypeCode, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRarrayTypeEnum, System.Runtime.Serialization.Formatters.Binary.PrimitiveArray, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRisLowerBound, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRlengthA, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRlowerBoundA, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRnewObj, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRobjectA, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRobjectPositionEnum, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRrank, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRvalue, System.Runtime.Serialization.Formatters.Binary.ObjectReader.RegisterObject(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.stack, System.Runtime.Serialization.Formatters.Binary.Converter.typeofObject, System.Runtime.Serialization.Formatters.Binary.Converter.typeofString, and System.Array.UnsafeCreateInstance().
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseObject().