Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.ObjectReader.GetSimplyNamedTypeFromAssembly
GetSimplyNamedTypeFromAssembly()
static void System.Runtime.Serialization.Formatters.Binary.ObjectReader.GetSimplyNamedTypeFromAssembly (Assembly assm, string typeName, ref Type type) inline static private
Definition at line 1010 of file ObjectReader.cs.
        {
            try
            {
                type = FormatterServices.GetTypeFromAssembly(assm, typeName);
            }
            catch (TypeLoadException)
            {
            }
            catch (FileNotFoundException)
            {
            }
            catch (FileLoadException)
            {
            }
            catch (BadImageFormatException)
            {
            }
            if (type == null)
            {
                type = Type.GetType(typeName, new Func<AssemblyName, Assembly>(ObjectReader.ResolveSimpleAssemblyName), new Func<Assembly, string, bool, Type>(new ObjectReader.TopLevelAssemblyTypeResolver(assm).ResolveType), false);
            }
        }
References System.Type.GetType(), System.Runtime.Serialization.FormatterServices.GetTypeFromAssembly(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ResolveSimpleAssemblyName(), and System.Runtime.Serialization.Formatters.Binary.ObjectReader.TopLevelAssemblyTypeResolver.ResolveType().
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectReader.FastBindToType(), and System.Runtime.Serialization.Formatters.Binary.ObjectReader.GetType().