Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseObject
ParseObject()
void System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseObject (ParseRecord pr) inline private
Definition at line 280 of file ObjectReader.cs.
        {
            if (!this.bFullDeserialization)
            {
                this.InitFullDeserialization();
            }
            if (pr.PRobjectPositionEnum == InternalObjectPositionE.Top)
            {
                this.topId = pr.PRobjectId;
            }
            if (pr.PRparseTypeEnum == InternalParseTypeE.Object)
            {
                this.stack.Push(pr);
            }
            if (pr.PRobjectTypeEnum == InternalObjectTypeE.Array)
            {
                this.ParseArray(pr);
                return;
            }
            if (pr.PRdtType == null)
            {
                pr.PRnewObj = new TypeLoadExceptionHolder(pr.PRkeyDt);
                return;
            }
            if (pr.PRdtType == Converter.typeofString)
            {
                if (pr.PRvalue == null)
                {
                    return;
                }
                pr.PRnewObj = pr.PRvalue;
                if (pr.PRobjectPositionEnum == InternalObjectPositionE.Top)
                {
                    this.TopObject = pr.PRnewObj;
                    return;
                }
                this.stack.Pop();
                this.RegisterObject(pr.PRnewObj, pr, (ParseRecord)this.stack.Peek());
                return;
            }
            else
            {
                this.CheckSerializable(pr.PRdtType);
                if (this.IsRemoting && this.formatterEnums.FEsecurityLevel != TypeFilterLevel.Full)
                {
                    pr.PRnewObj = FormatterServices.GetSafeUninitializedObject(pr.PRdtType);
                }
                else
                {
                    pr.PRnewObj = FormatterServices.GetUninitializedObject(pr.PRdtType);
                }
                this.m_objectManager.RaiseOnDeserializingEvent(pr.PRnewObj);
                if (pr.PRnewObj == null)
                {
                    throw new SerializationException(Environment.GetResourceString("Top object cannot be instantiated for element '{0}'.", new object[] { pr.PRdtType }));
                }
                if (pr.PRobjectPositionEnum == InternalObjectPositionE.Top)
                {
                    this.TopObject = pr.PRnewObj;
                }
                if (pr.PRobjectInfo == null)
                {
                    pr.PRobjectInfo = ReadObjectInfo.Create(pr.PRdtType, this.m_surrogates, this.m_context, this.m_objectManager, this.serObjectInfoInit, this.m_formatterConverter, this.bSimpleAssembly);
                }
                this.CheckSecurity(pr);
                return;
            }
        }
References System.Runtime.Serialization.Formatters.Binary.ObjectReader.bFullDeserialization, System.Runtime.Serialization.Formatters.Binary.ObjectReader.CheckSecurity(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.CheckSerializable(), System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.Create(), System.Runtime.Serialization.Formatters.Binary.InternalFE.FEsecurityLevel, System.Runtime.Serialization.Formatters.Binary.ObjectReader.formatterEnums, System.Environment.GetResourceString(), System.Runtime.Serialization.FormatterServices.GetSafeUninitializedObject(), System.Runtime.Serialization.FormatterServices.GetUninitializedObject(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.InitFullDeserialization(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.IsRemoting, System.Runtime.Serialization.Formatters.Binary.ObjectReader.m_objectManager, System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseArray(), System.Runtime.Serialization.Formatters.Binary.SerStack.Pop(), System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRdtType, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRkeyDt, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRnewObj, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRobjectId, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRobjectInfo, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRobjectPositionEnum, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRobjectTypeEnum, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRparseTypeEnum, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRvalue, System.Runtime.Serialization.Formatters.Binary.SerStack.Push(), System.Runtime.Serialization.ObjectManager.RaiseOnDeserializingEvent(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.RegisterObject(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.stack, and System.Runtime.Serialization.Formatters.Binary.Converter.typeofString.
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectReader.Parse(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseArrayMember(), and System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseMember().