Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize
Deserialize()
object System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize (HeaderHandler handler, __BinaryParser serParser, bool fCheck, bool isCrossAppDomain, IMethodCallMessage methodCallMessage) inline package
Definition at line 80 of file ObjectReader.cs.
        {
            if (serParser == null)
            {
                throw new ArgumentNullException("serParser", Environment.GetResourceString("Parameter '{0}' cannot be null.", new object[] { serParser }));
            }
            this.bFullDeserialization = false;
            this.TopObject = null;
            this.topId = 0L;
            this.bMethodCall = false;
            this.bMethodReturn = false;
            this.bIsCrossAppDomain = isCrossAppDomain;
            this.bSimpleAssembly = this.formatterEnums.FEassemblyFormat == FormatterAssemblyStyle.Simple;
            this.handler = handler;
            serParser.Run();
            if (this.bFullDeserialization)
            {
                this.m_objectManager.DoFixups();
            }
            if (!this.bMethodCall && !this.bMethodReturn)
            {
                if (this.TopObject == null)
                {
                    throw new SerializationException(Environment.GetResourceString("No top object."));
                }
                if (this.HasSurrogate(this.TopObject.GetType()) && this.topId != 0L)
                {
                    this.TopObject = this.m_objectManager.GetObject(this.topId);
                }
                if (this.TopObject is IObjectReference)
                {
                    this.TopObject = ((IObjectReference)this.TopObject).GetRealObject(this.m_context);
                }
            }
            if (this.bFullDeserialization)
            {
                this.m_objectManager.RaiseDeserializationEvent();
            }
            if (handler != null)
            {
                this.handlerObject = handler(this.headers);
            }
            if (this.bMethodCall)
            {
                object[] array = this.TopObject as object[];
                this.TopObject = this.binaryMethodCall.ReadArray(array, this.handlerObject);
            }
            else if (this.bMethodReturn)
            {
                object[] array2 = this.TopObject as object[];
                this.TopObject = this.binaryMethodReturn.ReadArray(array2, methodCallMessage, this.handlerObject);
            }
            return this.TopObject;
        }
References System.array, System.Runtime.Serialization.Formatters.Binary.ObjectReader.bFullDeserialization, System.Runtime.Serialization.Formatters.Binary.ObjectReader.binaryMethodCall, System.Runtime.Serialization.Formatters.Binary.ObjectReader.binaryMethodReturn, System.Runtime.Serialization.Formatters.Binary.ObjectReader.bMethodCall, System.Runtime.Serialization.Formatters.Binary.ObjectReader.bMethodReturn, System.Runtime.Serialization.ObjectManager.DoFixups(), System.Runtime.Serialization.ObjectManager.GetObject(), System.Environment.GetResourceString(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.handler, System.Runtime.Serialization.Formatters.Binary.ObjectReader.handlerObject, System.Runtime.Serialization.Formatters.Binary.ObjectReader.HasSurrogate(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.headers, System.L, System.Runtime.Serialization.Formatters.Binary.ObjectReader.m_context, System.Runtime.Serialization.Formatters.Binary.ObjectReader.m_objectManager, System.Runtime.Serialization.ObjectManager.RaiseDeserializationEvent(), System.Runtime.Serialization.Formatters.Binary.BinaryMethodCall.ReadArray(), System.Runtime.Serialization.Formatters.Binary.BinaryMethodReturn.ReadArray(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.topId, and System.Runtime.Serialization.Formatters.Binary.ObjectReader.TopObject.
Referenced by System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize().