Terraria Decompiled: ReLogic.OS.Windows.WindowsMessageHook.WindowsMessageHook
WindowsMessageHook()
ReLogic.OS.Windows.WindowsMessageHook.WindowsMessageHook (IntPtr windowHandle) inline
Definition at line 12 of file WindowsMessageHook.cs.
        {
            this._windowHandle = windowHandle;
            Application.AddMessageFilter(this);
            this._wndProc = new WindowsMessageHook.WndProcCallback(this.WndProc);
            this._previousWndProc = (IntPtr)NativeMethods.SetWindowLong(this._windowHandle, -4, (int)Marshal.GetFunctionPointerForDelegate(this._wndProc));
        }
References ReLogic.OS.Windows.WindowsMessageHook._wndProc, System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate(), ReLogic.OS.Windows.NativeMethods.SetWindowLong(), ReLogic.OS.Windows.WindowsMessageHook.WndProc(), and ReLogic.OS.Windows.WindowsMessageHook.WndProcCallback().