Terraria Decompiled: Ionic.Zlib.ZlibCodec.Inflate
Inflate()
int Ionic.Zlib.ZlibCodec.Inflate (FlushType flush) inline
Definition at line 83 of file ZlibCodec.cs.
        {
            if (this.istate == null)
            {
                throw new ZlibException("No Inflate State!");
            }
            return this.istate.Inflate(flush);
        }
References Ionic.Zlib.InflateManager.Inflate(), and Ionic.Zlib.ZlibCodec.istate.
Referenced by Terraria.Map.MapHelper.DecompressChunk(), Ionic.Zlib.ZlibBaseStream.finish(), Ionic.Zlib.ZlibBaseStream.Read(), and Ionic.Zlib.ZlibBaseStream.Write().