Terraria Decompiled: Ionic.Zlib.ZlibCodec._InternalInitializeDeflate
_InternalInitializeDeflate()
int Ionic.Zlib.ZlibCodec._InternalInitializeDeflate (bool wantRfc1950Header) inline private
Definition at line 151 of file ZlibCodec.cs.
        {
            if (this.istate != null)
            {
                throw new ZlibException("You may not call InitializeDeflate() after calling InitializeInflate().");
            }
            this.dstate = new DeflateManager();
            this.dstate.WantRfc1950HeaderBytes = wantRfc1950Header;
            return this.dstate.Initialize(this, this.CompressLevel, this.WindowBits, this.Strategy);
        }
References Ionic.Zlib.ZlibCodec.CompressLevel, Ionic.Zlib.ZlibCodec.dstate, Ionic.Zlib.DeflateManager.Initialize(), Ionic.Zlib.ZlibCodec.istate, Ionic.Zlib.ZlibCodec.Strategy, and Ionic.Zlib.ZlibCodec.WindowBits.
Referenced by Ionic.Zlib.ZlibCodec.InitializeDeflate(), Ionic.Zlib.ZlibCodec.InitializeDeflate(), Ionic.Zlib.ZlibCodec.InitializeDeflate(), Ionic.Zlib.ZlibCodec.InitializeDeflate(), and Ionic.Zlib.ZlibCodec.InitializeDeflate().