Terraria Decompiled: System.Runtime.InteropServices.SafeHandle.DangerousReleaseInternal
DangerousReleaseInternal()
void System.Runtime.InteropServices.SafeHandle.DangerousReleaseInternal (bool dispose) inline private
Definition at line 181 of file SafeHandle.cs.
        {
            try
            {
            }
            finally
            {
                if (!this._fullyInitialized)
                {
                    throw new InvalidOperationException();
                }
                bool flag;
                for (;;)
                {
                    int state = this._state;
                    if (dispose && (state & 2) != 0)
                    {
                        break;
                    }
                    if ((state & 2147483644) == 0)
                    {
                        goto Block_6;
                    }
                    flag = (state & 2147483644) == 4 && (state & 1) == 0 && this._ownsHandle && !this.IsInvalid;
                    int num = state - 4;
                    if ((state & 2147483644) == 4)
                    {
                        num |= 1;
                    }
                    if (dispose)
                    {
                        num |= 2;
                    }
                    if (Interlocked.CompareExchange(ref this._state, num, state) == state)
                    {
                        goto IL_009A;
                    }
                }
                flag = false;
                goto IL_009A;
                Block_6:
                throw new ObjectDisposedException(null, "Safe handle has been closed");
                IL_009A:
                if (flag)
                {
                    this.ReleaseHandle();
                }
            }
        }
References System.Runtime.InteropServices.SafeHandle._fullyInitialized, System.Runtime.InteropServices.SafeHandle._state, System.Threading.Interlocked.CompareExchange(), System.Runtime.InteropServices.SafeHandle.IsInvalid, System.Runtime.InteropServices.SafeHandle.ReleaseHandle(), and System.state.
Referenced by System.Runtime.InteropServices.SafeHandle.DangerousRelease(), System.Runtime.InteropServices.SafeHandle.InternalDispose(), and System.Runtime.InteropServices.SafeHandle.InternalFinalize().