Terraria Decompiled: Terraria.Social.Steam.Lobby.Create
Create()
void Terraria.Social.Steam.Lobby.Create (bool inviteOnly, CallResult< LobbyCreated_t >::APIDispatchDelegate callResult) inline
Definition at line 18 of file Lobby.cs.
        {
            SteamAPICall_t steamAPICall_t = SteamMatchmaking.CreateLobby(inviteOnly ? 0 : 1, 256);
            this._lobbyCreatedExternalCallback = callResult;
            this._lobbyCreated.Set(steamAPICall_t, null);
            this.State = LobbyState.Creating;
        }
References Terraria.Social.Steam.Lobby._lobbyCreated, Steamworks.SteamMatchmaking.CreateLobby(), and Steamworks.CallResult< T >.Set().
Referenced by Terraria.Social.Steam.NetServerSocialModule.Initialize().