Terraria Decompiled: System.Reflection.Emit.UnmanagedMarshal.DefineCustom
DefineCustom()
static UnmanagedMarshal System.Reflection.Emit.UnmanagedMarshal.DefineCustom (Type typeref, string cookie, string mtype, Guid id) inline static package
Definition at line 108 of file UnmanagedMarshal.cs.
        {
            UnmanagedMarshal unmanagedMarshal = new UnmanagedMarshal(UnmanagedType.CustomMarshaler, UnmanagedType.CustomMarshaler);
            unmanagedMarshal.mcookie = cookie;
            unmanagedMarshal.marshaltype = mtype;
            unmanagedMarshal.marshaltyperef = typeref;
            if (id == Guid.Empty)
            {
                unmanagedMarshal.guid = string.Empty;
            }
            else
            {
                unmanagedMarshal.guid = id.ToString();
            }
            return unmanagedMarshal;
        }
References System.Guid.Empty, System.Type.ToString(), and System.Reflection.Emit.UnmanagedMarshal.UnmanagedMarshal().
Referenced by System.Reflection.Emit.CustomAttributeBuilder.get_umarshal().