Terraria Decompiled: Terraria.Social.Steam.Lobby.GetMessage
GetMessage()
byte[] Terraria.Social.Steam.Lobby.GetMessage (int index) inline
Definition at line 51 of file Lobby.cs.
        {
            CSteamID csteamID;
            EChatEntryType echatEntryType;
            int lobbyChatEntry = SteamMatchmaking.GetLobbyChatEntry(this.Id, index, ref csteamID, this._messageBuffer, this._messageBuffer.Length, ref echatEntryType);
            byte[] array = new byte[lobbyChatEntry];
            Array.Copy(this._messageBuffer, array, lobbyChatEntry);
            return array;
        }
References Terraria.Social.Steam.Lobby._messageBuffer, System.array, System.Array.Copy(), Steamworks.SteamMatchmaking.GetLobbyChatEntry(), and Terraria.Social.Steam.Lobby.Id.
Referenced by Terraria.Social.Steam.NetSocialModule.OnLobbyChatMessage().