Terraria Decompiled: Terraria.Social.Steam.Lobby.Leave
Leave()
void Terraria.Social.Steam.Lobby.Leave () inline
Definition at line 105 of file Lobby.cs.
        {
            if (this.State == LobbyState.Active)
            {
                SteamMatchmaking.LeaveLobby(this.Id);
            }
            this.State = LobbyState.Inactive;
            this._usersSeen.Clear();
        }
References Terraria.Social.Steam.Lobby._usersSeen, Terraria.Social.Steam.Lobby.Id, Steamworks.SteamMatchmaking.LeaveLobby(), and Terraria.Social.Steam.Lobby.State.
Referenced by Terraria.Social.Steam.NetClientSocialModule.CancelJoin(), Terraria.Social.Steam.NetClientSocialModule.Close(), Terraria.Social.Steam.NetClientSocialModule.LaunchLocalServer(), Terraria.Social.Steam.NetClientSocialModule.OnLobbyJoinRequest(), and Terraria.Social.Steam.NetSocialModule.Shutdown().