Terraria Decompiled: Terraria.Social.Steam.Lobby.Join
Join()
void Terraria.Social.Steam.Lobby.Join (CSteamID lobbyId, CallResult< LobbyEnter_t >::APIDispatchDelegate callResult) inline
Definition at line 38 of file Lobby.cs.
        {
            if (this.State != LobbyState.Inactive)
            {
                return;
            }
            this.State = LobbyState.Connecting;
            this._lobbyEnterExternalCallback = callResult;
            SteamAPICall_t steamAPICall_t = SteamMatchmaking.JoinLobby(lobbyId);
            this._lobbyEnter.Set(steamAPICall_t, null);
        }
References Terraria.Social.Steam.Lobby._lobbyEnter, Steamworks.SteamMatchmaking.JoinLobby(), Steamworks.CallResult< T >.Set(), and Terraria.Social.Steam.Lobby.State.
Referenced by Terraria.Social.Steam.NetClientSocialModule.ConnectToLobby(), and Terraria.Social.Steam.NetClientSocialModule.OnLobbyJoinRequest().