Terraria Decompiled: System.IO.BufferedStream.d__63.MoveNext
MoveNext()
void IAsyncStateMachine. System.IO.BufferedStream.d__63.MoveNext () inline
Implements System.Runtime.CompilerServices.IAsyncStateMachine.
Definition at line 1691 of file BufferedStream.cs.
            {
                int num2;
                int num = num2;
                BufferedStream bufferedStream = this;
                try
                {
                    ConfiguredTaskAwaitable.ConfiguredTaskAwaiter configuredTaskAwaiter;
                    if (num != 0)
                    {
                        if (num - 1 <= 3)
{
                            goto IL_007B;
                        }
                        configuredTaskAwaiter = semaphoreLockTask.ConfigureAwait(false).GetAwaiter();
                        if (!configuredTaskAwaiter.IsCompleted)
{
                            num = (num2 = 0);
                            ConfiguredTaskAwaitable.ConfiguredTaskAwaiter configuredTaskAwaiter2 = configuredTaskAwaiter;
                            this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredTaskAwaitable.ConfiguredTaskAwaiter, BufferedStream.<WriteToUnderlyingStreamAsync>d__63>(ref configuredTaskAwaiter, ref this);
                            return;
                        }
                    }
                    else
                    {
                        ConfiguredTaskAwaitable.ConfiguredTaskAwaiter configuredTaskAwaiter2;
                        configuredTaskAwaiter = configuredTaskAwaiter2;
                        configuredTaskAwaiter2 = default(ConfiguredTaskAwaitable.ConfiguredTaskAwaiter);
                        num = (num2 = -1);
                    }
                    configuredTaskAwaiter.GetResult();
                    IL_007B:
                    try
                    {
                        ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter;
                        switch (num)
{
                        case 1:
{
                            ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter2;
                            configuredValueTaskAwaiter = configuredValueTaskAwaiter2;
                            configuredValueTaskAwaiter2 = default(ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter);
                            num = (num2 = -1);
                            break;
                        }
                        case 2:
{
                            ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter2;
                            configuredValueTaskAwaiter = configuredValueTaskAwaiter2;
                            configuredValueTaskAwaiter2 = default(ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter);
                            num = (num2 = -1);
                            goto IL_0294;
                        }
                        case 3:
{
                            ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter2;
                            configuredValueTaskAwaiter = configuredValueTaskAwaiter2;
                            configuredValueTaskAwaiter2 = default(ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter);
                            num = (num2 = -1);
                            goto IL_0329;
                        }
                        case 4:
{
                            ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter2;
                            configuredValueTaskAwaiter = configuredValueTaskAwaiter2;
                            configuredValueTaskAwaiter2 = default(ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter);
                            num = (num2 = -1);
                            goto IL_03AA;
                        }
                        default:
{
                            if (bufferedStream._writePos == 0)
{
                                bufferedStream.ClearReadBufferBeforeWrite();
                            }
                            int num3 = checked(bufferedStream._writePos + buffer.Length);
                            if (checked(num3 + buffer.Length < bufferedStream._bufferSize + bufferedStream._bufferSize))
{
                                buffer = buffer.Slice(bufferedStream.WriteToBuffer(buffer.Span));
                                if (bufferedStream._writePos < bufferedStream._bufferSize)
{
                                    goto IL_03DF;
                                }
                                configuredValueTaskAwaiter = bufferedStream._stream.WriteAsync(new ReadOnlyMemory<byte>(bufferedStream._buffer, 0, bufferedStream._writePos), cancellationToken).ConfigureAwait(false).GetAwaiter();
                                if (!configuredValueTaskAwaiter.IsCompleted)
{
                                    num = (num2 = 1);
                                    ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter2 = configuredValueTaskAwaiter;
                                    this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter, BufferedStream.<WriteToUnderlyingStreamAsync>d__63>(ref configuredValueTaskAwaiter, ref this);
                                    return;
                                }
                            }
                            else
{
                                if (bufferedStream._writePos <= 0)
{
                                    goto IL_0337;
                                }
                                if (num3 <= bufferedStream._bufferSize + bufferedStream._bufferSize && num3 <= 81920)
{
                                    bufferedStream.EnsureShadowBufferAllocated();
                                    buffer.Span.CopyTo(new Span<byte>(bufferedStream._buffer, bufferedStream._writePos, buffer.Length));
                                    configuredValueTaskAwaiter = bufferedStream._stream.WriteAsync(new ReadOnlyMemory<byte>(bufferedStream._buffer, 0, num3), cancellationToken).ConfigureAwait(false).GetAwaiter();
                                    if (!configuredValueTaskAwaiter.IsCompleted)
{
                                        num = (num2 = 2);
                                        ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter2 = configuredValueTaskAwaiter;
                                        this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter, BufferedStream.<WriteToUnderlyingStreamAsync>d__63>(ref configuredValueTaskAwaiter, ref this);
                                        return;
                                    }
                                    goto IL_0294;
                                }
                                else
{
                                    configuredValueTaskAwaiter = bufferedStream._stream.WriteAsync(new ReadOnlyMemory<byte>(bufferedStream._buffer, 0, bufferedStream._writePos), cancellationToken).ConfigureAwait(false).GetAwaiter();
                                    if (!configuredValueTaskAwaiter.IsCompleted)
{
                                        num = (num2 = 3);
                                        ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter2 = configuredValueTaskAwaiter;
                                        this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter, BufferedStream.<WriteToUnderlyingStreamAsync>d__63>(ref configuredValueTaskAwaiter, ref this);
                                        return;
                                    }
                                    goto IL_0329;
                                }
                            }
                            break;
                        }
                        }
                        configuredValueTaskAwaiter.GetResult();
                        bufferedStream._writePos = 0;
                        bufferedStream.WriteToBuffer(buffer.Span);
                        goto IL_03B1;
                        IL_0294:
                        configuredValueTaskAwaiter.GetResult();
                        bufferedStream._writePos = 0;
                        goto IL_03DF;
                        IL_0329:
                        configuredValueTaskAwaiter.GetResult();
                        bufferedStream._writePos = 0;
                        IL_0337:
                        configuredValueTaskAwaiter = bufferedStream._stream.WriteAsync(buffer, cancellationToken).ConfigureAwait(false).GetAwaiter();
                        if (!configuredValueTaskAwaiter.IsCompleted)
{
                            num = (num2 = 4);
                            ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter2 = configuredValueTaskAwaiter;
                            this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter, BufferedStream.<WriteToUnderlyingStreamAsync>d__63>(ref configuredValueTaskAwaiter, ref this);
                            return;
                        }
                        IL_03AA:
                        configuredValueTaskAwaiter.GetResult();
                        IL_03B1:;
                    }
                    finally
                    {
                        if (num < 0)
{
                            bufferedStream.LazyEnsureAsyncActiveSemaphoreInitialized().Release();
                        }
                    }
                }
                catch (Exception ex)
                {
                    num2 = -2;
                    this.<>t__builder.SetException(ex);
                    return;
                }
                IL_03DF:
                num2 = -2;
                this.<>t__builder.SetResult();
            }
References System.IO.BufferedStream._buffer, System.IO.BufferedStream._bufferSize, System.IO.BufferedStream._stream, System.IO.BufferedStream._writePos, System.IO.BufferedStream.ClearReadBufferBeforeWrite(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.IO.BufferedStream.EnsureShadowBufferAllocated(), System.Runtime.CompilerServices.ConfiguredTaskAwaitable< TResult >.GetAwaiter(), System.Threading.Tasks.Task< TResult >.GetAwaiter(), System.Runtime.CompilerServices.ConfiguredTaskAwaitable< TResult >.ConfiguredTaskAwaiter.GetResult(), System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable< TResult >.ConfiguredValueTaskAwaiter.GetResult(), System.Runtime.CompilerServices.ConfiguredTaskAwaitable< TResult >.ConfiguredTaskAwaiter.IsCompleted, System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable< TResult >.ConfiguredValueTaskAwaiter.IsCompleted, System.IO.BufferedStream.LazyEnsureAsyncActiveSemaphoreInitialized(), System.ReadOnlyMemory< T >.Length, System.Threading.SemaphoreSlim.Release(), System.ReadOnlyMemory< T >.Slice(), System.ReadOnlyMemory< T >.Span, System.IO.Stream.WriteAsync(), System.IO.BufferedStream.WriteToBuffer(), and System.IO.BufferedStream.WriteToUnderlyingStreamAsync().