Terraria Decompiled: Terraria.GameContent.UI.Elements.UICreativeItemsInfiniteFilteringOptions.UICreativeItemsInfiniteFilteringOptions
UICreativeItemsInfiniteFilteringOptions()
Terraria.GameContent.UI.Elements.UICreativeItemsInfiniteFilteringOptions.UICreativeItemsInfiniteFilteringOptions (EntryFilterer< Item, IItemEntryFilter > filterer, string snapPointsName, UICreativeItemsInfiniteFilteringOptions::ColorTheme theme = UICreativeItemsInfiniteFilteringOptions::ColorTheme::Blue) inline
Definition at line 53 of file UICreativeItemsInfiniteFilteringOptions.cs.
        {
            this._theme = theme;
            this._filterer = filterer;
            int num = 40;
            int count = this._filterer.AvailableFilters.Count;
            int num2 = num * count;
            this.Height = new StyleDimension((float)num, 0f);
            this.Width = new StyleDimension((float)num2, 0f);
            this.Top = new StyleDimension(4f, 0f);
            base.SetPadding(0f);
            string text = "Images/UI/Creative/Infinite_Tabs_B";
            if (this._theme == UICreativeItemsInfiniteFilteringOptions.ColorTheme.Cyan)
            {
                text = "Images/UI/Creative/Infinite_Tabs_B_2";
            }
            Asset<Texture2D> asset = Main.Assets.Request<Texture2D>(text, 1);
            for (int i = 0; i < this._filterer.AvailableFilters.Count; i++)
            {
                IItemEntryFilter itemEntryFilter = this._filterer.AvailableFilters[i];
                asset.Frame(2, 4, 0, 0, 0, 0).OffsetSize(-2, -2);
                UIImageFramed uiimageFramed = new UIImageFramed(asset, asset.Frame(2, 4, 0, 0, 0, 0).OffsetSize(-2, -2));
                uiimageFramed.Left.Set((float)(num * i), 0f);
                uiimageFramed.OnLeftClick += this.singleFilterButtonClick;
                uiimageFramed.OnMouseOver += this.button_OnMouseOver;
                uiimageFramed.SetPadding(0f);
                uiimageFramed.SetSnapPoint(snapPointsName, i, null, null);
                this.AddOnHover(itemEntryFilter, uiimageFramed, i);
                UIElement image = itemEntryFilter.GetImage();
                image.IgnoresMouseInteraction = true;
                image.Left = new StyleDimension(6f, 0f);
                image.HAlign = 0f;
                uiimageFramed.Append(image);
                this._filtersByButtons[uiimageFramed] = itemEntryFilter;
                this._iconsByButtons[uiimageFramed] = image;
                base.Append(uiimageFramed);
                this.UpdateVisuals(uiimageFramed, i);
            }
        }
References Terraria.GameContent.UI.Elements.UICreativeItemsInfiniteFilteringOptions._filterer, Terraria.GameContent.UI.Elements.UICreativeItemsInfiniteFilteringOptions._filtersByButtons, Terraria.GameContent.UI.Elements.UICreativeItemsInfiniteFilteringOptions._iconsByButtons, Terraria.GameContent.UI.Elements.UICreativeItemsInfiniteFilteringOptions._theme, Terraria.GameContent.UI.Elements.UICreativeItemsInfiniteFilteringOptions.AddOnHover(), Terraria.UI.UIElement.Append(), Terraria.Main.Assets, Terraria.DataStructures.EntryFilterer< T, U >.AvailableFilters, Terraria.GameContent.UI.Elements.UICreativeItemsInfiniteFilteringOptions.button_OnMouseOver(), System.Collections.Generic.List< T >.Count, System.count, Terraria.DataStructures.IEntryFilter< T >.GetImage(), Terraria.UI.UIElement.Left, Terraria.UI.StyleDimension.Set(), Terraria.UI.UIElement.SetPadding(), Terraria.UI.UIElement.SetSnapPoint(), Terraria.GameContent.UI.Elements.UICreativeItemsInfiniteFilteringOptions.singleFilterButtonClick(), System.text, and Terraria.GameContent.UI.Elements.UICreativeItemsInfiniteFilteringOptions.UpdateVisuals().