Terraria Decompiled: Terraria.Dust.CloneDust
CloneDust() [2/2]
static Dust Terraria.Dust.CloneDust (int dustIndex) inline static
Definition at line 236 of file Dust.cs.
        {
            return Dust.CloneDust(Main.dust[dustIndex]);
        }
References Terraria.Dust.CloneDust(), Terraria.Main.dust, and Terraria.Dust.dustIndex.
Referenced by Terraria.Projectile.AI(), Terraria.Projectile.AI_001(), Terraria.NPC.AI_065_Butterflies(), Terraria.Projectile.AI_113_TargetSticker(), Terraria.NPC.AI_120_HallowBoss(), Terraria.Projectile.AI_165_Whip(), Terraria.Projectile.AI_186_PrincessWeapon(), Terraria.Projectile.AI_203_StormLightning(), Terraria.Dust.CloneDust(), Terraria.Projectile.DoRainbowCrystalStaffExplosion(), Terraria.Mount.DoSpawnDust(), Terraria.PopupText.EmitFancyFlashDust(), Terraria.NPC.HitEffect(), Terraria.Player.ItemCheck_ApplyUseStyle(), Terraria.Projectile.LightDisc_Bounce(), Terraria.Graphics.Renderers.StormLightningParticle.Prepare(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsDownDashExplosion(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_PaladinsHammer(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_PrincessWeapon(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_RainbowBoulder3(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_RainbowRodHit(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_StardustPunch(), Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnLightningExplosionDust(), Terraria.Main.TeleportEffect(), Terraria.GameContent.LeashedEntities.EmpressButterflyLeashedCritter.VisualEffects(), and Terraria.Player.WingFrame().