Terraria Decompiled: Terraria.Dust.NewDust
NewDust()
static int Terraria.Dust.NewDust (Vector2 Position, int Width, int Height, int Type, float SpeedX = 0f, float SpeedY = 0f, int Alpha = 0, Color newColor = default(Color), float Scale = 1f) inline static
Definition at line 37 of file Dust.cs.
        {
            if (Main.gameMenu)
            {
                return 6000;
            }
            if (Main.rand == null)
            {
                Main.rand = new UnifiedRandom((int)DateTime.Now.Ticks);
            }
            if (Main.gamePaused)
            {
                return 6000;
            }
            if (WorldGen.isGeneratingOrLoadingWorld)
            {
                return 6000;
            }
            if (Main.netMode == 2)
            {
                return 6000;
            }
            int num = (int)(400f * (1f - Dust.dCount));
            Rectangle rectangle = new Rectangle((int)(Main.screenPosition.X - (float)num), (int)(Main.screenPosition.Y - (float)num), Main.screenWidth + num * 2, Main.screenHeight + num * 2);
            Rectangle rectangle2 = new Rectangle((int)Position.X, (int)Position.Y, 10, 10);
            if (!rectangle.Intersects(rectangle2))
            {
                return 6000;
            }
            int num2 = 6000;
            int i = 0;
            while (i < 6000)
            {
                Dust dust = Main.dust[i];
                if (!dust.active)
                {
                    if (Main.NoPooling)
                    {
                        dust = (Main.dust[i] = new Dust());
                    }
                    if ((double)i > (double)Main.maxDustToDraw * 0.9)
                    {
                        if (Main.rand.Next(4) != 0)
{
                            return 6000;
                        }
                    }
                    else if ((double)i > (double)Main.maxDustToDraw * 0.8)
                    {
                        if (Main.rand.Next(3) != 0)
{
                            return 6000;
                        }
                    }
                    else if ((double)i > (double)Main.maxDustToDraw * 0.7)
                    {
                        if (Main.rand.Next(2) == 0)
{
                            return 6000;
                        }
                    }
                    else if ((double)i > (double)Main.maxDustToDraw * 0.6)
                    {
                        if (Main.rand.Next(4) == 0)
{
                            return 6000;
                        }
                    }
                    else if ((double)i > (double)Main.maxDustToDraw * 0.5)
                    {
                        if (Main.rand.Next(5) == 0)
{
                            return 6000;
                        }
                    }
                    else
                    {
                        Dust.dCount = 0f;
                    }
                    int num3 = Width;
                    int num4 = Height;
                    if (num3 < 5)
                    {
                        num3 = 5;
                    }
                    if (num4 < 5)
                    {
                        num4 = 5;
                    }
                    num2 = i;
                    dust.fadeIn = 0f;
                    dust.active = true;
                    dust.type = Type;
                    dust.noGravity = false;
                    dust.color = newColor;
                    dust.alpha = Alpha;
                    dust.position.X = Position.X + (float)Main.rand.Next(num3 - 4) + 4f;
                    dust.position.Y = Position.Y + (float)Main.rand.Next(num4 - 4) + 4f;
                    dust.velocity.X = (float)Main.rand.Next(-20, 21) * 0.1f + SpeedX;
                    dust.velocity.Y = (float)Main.rand.Next(-20, 21) * 0.1f + SpeedY;
                    dust.frame.X = 10 * Type;
                    dust.frame.Y = 10 * Main.rand.Next(3);
                    dust.shader = null;
                    dust.customData = null;
                    dust.noLightEmittance = false;
                    dust.fullBright = false;
                    int j = Type;
                    while (j >= 100)
                    {
                        j -= 100;
                        Dust dust2 = dust;
                        dust2.frame.X = dust2.frame.X - 1000;
                        Dust dust3 = dust;
                        dust3.frame.Y = dust3.frame.Y + 30;
                    }
                    dust.frame.Width = 8;
                    dust.frame.Height = 8;
                    dust.rotation = 0f;
                    dust.scale = 1f + (float)Main.rand.Next(-20, 21) * 0.01f;
                    dust.scale *= Scale;
                    dust.noLight = false;
                    dust.firstFrame = true;
                    if (!ChildSafety.Disabled && ChildSafety.DangerousDust(dust.type))
                    {
                        if (Main.rand.Next(2) != 0)
{
                            dust.active = false;
                            return 6000;
                        }
                        dust.firstFrame = false;
                        dust.type = 16;
                        dust.scale = Main.rand.NextFloat() * 1.6f + 0.3f;
                        dust.color = Color.Transparent;
                        dust.frame.X = 10 * dust.type;
                        dust.frame.Y = 10 * Main.rand.Next(3);
                        dust.shader = null;
                        dust.customData = null;
                        int num5 = dust.type / 100;
                        Dust dust4 = dust;
                        dust4.frame.X = dust4.frame.X - 1000 * num5;
                        Dust dust5 = dust;
                        dust5.frame.Y = dust5.frame.Y + 30 * num5;
                        dust.noGravity = true;
                    }
                    if (dust.type == 228 || dust.type == 279 || dust.type == 269 || dust.type == 135 || dust.type == 6 || dust.type == 242 || dust.type == 75 || dust.type == 169 || dust.type == 29 || (dust.type >= 59 && dust.type <= 65) || dust.type == 158 || dust.type == 293 || dust.type == 294 || dust.type == 295 || dust.type == 296 || dust.type == 297 || dust.type == 298 || dust.type == 302 || dust.type == 307 || dust.type == 310)
                    {
                        dust.velocity.Y = (float)Main.rand.Next(-10, 6) * 0.1f;
                        Dust dust6 = dust;
                        dust6.velocity.X = dust6.velocity.X * 0.3f;
                        dust.scale *= 0.7f;
                    }
                    if (dust.type == 127 || dust.type == 187)
                    {
                        dust.velocity *= 0.3f;
                        dust.scale *= 0.7f;
                    }
                    if (dust.type == 308)
                    {
                        dust.velocity *= 0.5f;
                        Dust dust7 = dust;
                        dust7.velocity.Y = dust7.velocity.Y + 1f;
                    }
                    if (dust.type == 33 || dust.type == 52 || dust.type == 266 || dust.type == 98 || dust.type == 99 || dust.type == 100 || dust.type == 101 || dust.type == 102 || dust.type == 103 || dust.type == 104 || dust.type == 105)
                    {
                        dust.alpha = 170;
                        dust.velocity *= 0.5f;
                        Dust dust8 = dust;
                        dust8.velocity.Y = dust8.velocity.Y + 1f;
                    }
                    if (dust.type == 41)
                    {
                        dust.velocity *= 0f;
                    }
                    if (dust.type == 80)
                    {
                        dust.alpha = 50;
                    }
                    if (dust.type != 34 && dust.type != 35 && dust.type != 152)
                    {
                        break;
                    }
                    dust.velocity *= 0.1f;
                    dust.velocity.Y = -0.5f;
                    if (dust.type == 34 && !Collision.WetCollision(new Vector2(dust.position.X, dust.position.Y - 8f), 4, 4))
                    {
                        dust.active = false;
                        break;
                    }
                    break;
                }
                else
                {
                    i++;
                }
            }
            return num2;
        }
References Terraria.Dust.active, Terraria.GameContent.ChildSafety.DangerousDust(), Terraria.Dust.dCount, Terraria.GameContent.ChildSafety.Disabled, Terraria.Dust.Dust(), Terraria.Main.dust, Terraria.Main.gameMenu, Terraria.Main.gamePaused, int, Microsoft.Xna.Framework.Rectangle.Intersects(), Terraria.WorldGen.isGeneratingOrLoadingWorld, Terraria.Main.maxDustToDraw, Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.NoPooling, System.DateTime.Now, Terraria.Dust.position, Terraria.Main.rand, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.screenWidth, System.DateTime.Ticks, Microsoft.Xna.Framework.Color.Transparent, Terraria.Dust.type, Terraria.Collision.WetCollision(), Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.Projectile.AI_001(), Terraria.NPC.AI_001_Slimes(), Terraria.NPC.AI_002_FloatingEye(), Terraria.Projectile.AI_003_Boomerang(), Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_005_EaterOfSouls(), Terraria.NPC.AI_006_Worms(), Terraria.Projectile.AI_009_MagicMissiles(), Terraria.Projectile.AI_009_MagicMissiles_Old(), Terraria.Projectile.AI_010(), Terraria.Projectile.AI_015_Flails_Dust(), Terraria.NPC.AI_015_KingSlime(), Terraria.Projectile.AI_016_Bombs(), Terraria.Projectile.AI_019_Spears(), Terraria.Projectile.AI_019_Spears_Old(), Terraria.Projectile.AI_026(), Terraria.NPC.AI_026_Unicorns(), Terraria.NPC.AI_037_Destroyer(), Terraria.NPC.AI_045_Golem(), Terraria.Projectile.AI_061_FishingBobber_DoASplash(), Terraria.Projectile.AI_062(), Terraria.NPC.AI_065_Butterflies(), Terraria.Projectile.AI_067_FreakingPirates(), Terraria.NPC.AI_069_DukeFishron(), Terraria.Projectile.AI_075(), Terraria.Projectile.AI_099_2_Yoyos(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_108_DivingFlyer(), Terraria.Projectile.AI_111_DryadsWard(), Terraria.NPC.AI_117_BloodNautilus(), Terraria.NPC.AI_120_HallowBoss(), Terraria.Projectile.AI_120_StardustGuardian(), Terraria.NPC.AI_121_QueenSlime(), Terraria.Projectile.AI_121_StardustDragon(), Terraria.Projectile.AI_135_OgreStomp(), Terraria.Projectile.AI_145_BookStaffStorm(), Terraria.Projectile.AI_147_Celeb2Rocket(), Terraria.Projectile.AI_147_Explosion(), Terraria.Projectile.AI_162_TigerPounce(), Terraria.Projectile.AI_165_Whip(), Terraria.Projectile.AI_177_IceWhipSlicer(), Terraria.Projectile.AI_178_FireExplosion(), Terraria.Projectile.AI_184_BadTorchLuck(), Terraria.Projectile.AI_186_PrincessWeapon(), Terraria.Projectile.AI_197_CeilingAndHoverTurret(), Terraria.Projectile.AI_197_HandleTileCollision(), Terraria.Projectile.AI_199_MeteorOre(), Terraria.Projectile.AI_200_BirdDroppings(), Terraria.Projectile.AI_202_TorchGodHelper(), Terraria.Player.ApplySetBonus_Solar(), Terraria.NPC.BigMimicSpawnSmoke(), Terraria.DataStructures.PlayerDrawSet.BoringSetup(), Terraria.NPC.CheckDrowning(), Terraria.Player.CheckDrowning(), Terraria.Dust.CloneDust(), Terraria.NPC.Collision_WaterCollision(), Terraria.Player.CommandForbiddenStorm(), Terraria.Player.DashMovement(), Terraria.WorldItem.DespawnIfMeetingConditions(), Terraria.Mount.DoFailedDismountDust(), Terraria.Player.DoGlassSlipperSparkles(), Terraria.Projectile.DoRainbowCrystalStaffExplosion(), Terraria.Mount.DoSpawnDust(), Terraria.Graphics.Renderers.FakeFishParticle.DoStandardWaterSplash(), Terraria.Player.DoubleJumpVisuals(), Terraria.GameContent.Drawing.TileDrawing.DrawAnimatedTile_AdjustForVisionChangers(), Terraria.Main.DrawItem(), Terraria.Main.DrawNPCDirect(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_07_LeinforsHairShampoo(), Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile(), Terraria.GameContent.Drawing.TileDrawing.DrawTiles_EmitParticles(), Terraria.GameContent.Drawing.TileDrawing.DrawVineStrip(), Terraria.GameContent.Drawing.TileDrawing.EmitAlchemyHerbParticles(), Terraria.GameContent.Events.Sandstorm.EmitDust(), Terraria.Projectile.EmitEnchantmentVisualsAt(), Terraria.Player.EmitMaxManaEffect(), Terraria.NPC.FindFrame(), Terraria.Gore.Gore_UpdateLeaf(), Terraria.Projectile.HandleMovement(), Terraria.NPC.HitEffect(), Terraria.GameContent.Liquid.LiquidRenderer.InternalPrepareDraw(), Terraria.Player.ItemCheck(), Terraria.Player.ItemCheck_ApplyHoldStyle(), Terraria.Player.ItemCheck_ApplyUseStyle(), Terraria.Player.ItemCheck_EmitHeldItemLight(), Terraria.Player.ItemCheck_EmitUseVisuals(), Terraria.Player.ItemCheck_GetMeleeHitboxParticles(), Terraria.Player.ItemCheck_ManageRightClickFeatures_ShieldRaise(), Terraria.Player.JumpMovement(), Terraria.WorldGen.KillActuator(), Terraria.Player.KillMe(), Terraria.Player.KillMe_DustExplosion(), Terraria.WorldGen.KillTile_MakeTileDust(), Terraria.WorldGen.KillWall_MakeWallDust(), Terraria.WorldGen.KillWire(), Terraria.WorldGen.KillWire2(), Terraria.WorldGen.KillWire3(), Terraria.WorldGen.KillWire4(), Terraria.Player.MakeFloorDust(), Terraria.NPC.MakeTransitionEffectsForTextureChanges(), Terraria.NPC.moneyPing(), Terraria.WorldItem.MoveInWorld(), Terraria.Dust.NewDustDirect(), Terraria.Dust.NewDustPerfect(), Terraria.Player.NinjaDodge(), Terraria.Main.oldDrawWater(), Terraria.WorldGen.paintCoatEffect(), Terraria.WorldGen.paintEffect(), Terraria.WorldGen.PlaceTile(), Terraria.Player.PlayerFrame(), Terraria.Utils.PoofOfSmoke(), Terraria.Dust.QuickDust(), Terraria.NPC.ReflectProjectile(), Terraria.WorldItem.ShimmerEffect(), Terraria.Main.snowing(), Terraria.DelegateMethods.Minecart.Sparks(), Terraria.DelegateMethods.Minecart.SparksFart(), Terraria.DelegateMethods.Minecart.SparksMech(), Terraria.DelegateMethods.Minecart.SparksMeow(), Terraria.DelegateMethods.Minecart.SparksTerraFart(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ClassyCane(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_Digestion(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_PaladinsHammer(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_PaladinsHammerShockwave(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_PrincessWeapon(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_RainbowBoulder3(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_RainbowBoulder4(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_RainbowRodHit(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ShimmerTownNPC(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_StardustPunch(), Terraria.Player.SpawnFastRunParticles(), Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnHelper_SpawnSingleLineDust(), Terraria.GameContent.TeleportPylonsSystem.SpawnInWorldDust(), Terraria.Player.StickyMovement(), Terraria.Collision.StickyTiles(), Terraria.Main.TeleportEffect(), Terraria.DelegateMethods.TestDust(), Terraria.NPC.TransformVisuals(), Terraria.WaterfallManager.TrySparkling(), Terraria.Chest.Unlock(), Terraria.WorldGen.UnlockDoor(), Terraria.Gore.Update(), Terraria.Rain.Update(), Terraria.Player.Update(), Terraria.Projectile.Update(), Terraria.Graphics.Renderers.BloodyExplosionParticle.Update(), Terraria.Dust.UpdateDust(), Terraria.Mount.UpdateEffects(), Terraria.Mount.UpdateFrame(), Terraria.Player.UpdateHairDyeDust(), Terraria.WorldItem.UpdateItem(), Terraria.WorldItem.UpdateItem_VisualEffects(), Terraria.Player.UpdateLifeRegen(), Terraria.Player.UpdateManaRegen(), Terraria.Player.UpdateMinionTarget(), Terraria.NPC.UpdateNPC(), Terraria.NPC.UpdateNPC_CastLights(), Terraria.NPC.UpdateNPC_SoulDrainDebuff(), Terraria.NPC.UpdateNPC_TeleportVisuals(), Terraria.Player.UpdateTeleportVisuals(), Terraria.Mount.UseDrill(), Terraria.GameContent.LeashedEntities.EmpressButterflyLeashedCritter.VisualEffects(), Terraria.GameContent.LeashedEntities.HellButterflyLeashedCritter.VisualEffects(), Terraria.GameContent.LeashedEntities.LeashedCritter.VisualEffects(), Terraria.Player.WallClimbMovement(), Terraria.Player.WallslideMovement(), Terraria.Player.WingAirVisuals(), Terraria.Player.WingFrame(), and Terraria.Player.Yoraiz0rEye().