Terraria Decompiled: Terraria.Dust.QuickDustLine
QuickDustLine()
static void Terraria.Dust.QuickDustLine (Vector2 start, Vector2 end, float splits, Color color) inline static
Definition at line 395 of file Dust.cs.
        {
            Dust.QuickDust(start, color).scale = 0.3f;
            Dust.QuickDust(end, color).scale = 0.3f;
            float num = 1f / splits;
            for (float num2 = 0f; num2 < 1f; num2 += num)
            {
                Dust.QuickDust(Vector2.Lerp(start, end, num2), color).scale = 0.3f;
            }
        }
References Terraria.Dust.color, Microsoft.Xna.Framework.Vector2.Lerp(), Terraria.Dust.QuickDust(), Terraria.Dust.scale, and System.start.
Referenced by Terraria.StrayMethods.CheckArenaScore(), and Terraria.MessageBuffer.GetData().