Terraria Decompiled: Terraria.Dust.QuickBox
QuickBox()
static void Terraria.Dust.QuickBox (Vector2 topLeft, Vector2 bottomRight, int divisions, Color color, float fadein = 1f, float dustScale = 1f, Action< Dust > manipulator = null) inline static
Definition at line 294 of file Dust.cs.
        {
            float num = (float)(divisions + 2);
            for (float num2 = 0f; num2 <= (float)(divisions + 2); num2 += 1f)
            {
                Dust dust = Dust.QuickDust(new Vector2(MathHelper.Lerp(topLeft.X, bottomRight.X, num2 / num), topLeft.Y), color);
                dust.scale = dustScale;
                dust.fadeIn = fadein;
                if (manipulator != null)
                {
                    manipulator(dust);
                }
                dust = Dust.QuickDust(new Vector2(MathHelper.Lerp(topLeft.X, bottomRight.X, num2 / num), bottomRight.Y), color);
                dust.scale = dustScale;
                dust.fadeIn = fadein;
                if (manipulator != null)
                {
                    manipulator(dust);
                }
                dust = Dust.QuickDust(new Vector2(topLeft.X, MathHelper.Lerp(topLeft.Y, bottomRight.Y, num2 / num)), color);
                dust.scale = dustScale;
                dust.fadeIn = fadein;
                if (manipulator != null)
                {
                    manipulator(dust);
                }
                dust = Dust.QuickDust(new Vector2(bottomRight.X, MathHelper.Lerp(topLeft.Y, bottomRight.Y, num2 / num)), color);
                dust.scale = dustScale;
                dust.fadeIn = fadein;
                if (manipulator != null)
                {
                    manipulator(dust);
                }
            }
        }
References Terraria.Dust.color, Microsoft.Xna.Framework.MathHelper.Lerp(), Terraria.Dust.QuickDust(), Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.StrayMethods.SendWalker().