Terraria Decompiled: Terraria.Dust.GetAlpha
GetAlpha()
Color Terraria.Dust.GetAlpha (Color newColor) inline
Definition at line 2549 of file Dust.cs.
        {
            if (this.fullBright)
            {
                return Color.White;
            }
            float num = (float)(255 - this.alpha) / 255f;
            int num2 = this.type;
            switch (num2)
            {
            case 299:
            case 300:
            case 301:
            case 305:
            {
                Color color = default(Color);
                switch (this.type)
                {
                case 299:
                    color = new Color(50, 255, 50, 200);
                    break;
                case 300:
                    color = new Color(50, 200, 255, 255);
                    break;
                case 301:
                    color = new Color(255, 50, 125, 200);
                    break;
                default:
                    color = new Color(255, 150, 150, 200);
                    break;
                case 305:
                    color = new Color(200, 50, 200, 200);
                    break;
                }
                return color;
            }
            case 302:
            case 303:
            case 304:
            case 306:
            case 307:
                break;
            case 308:
            case 309:
                return new Color(225, 200, 250, 190);
            default:
                if (num2 == 323)
                {
                    return Color.White;
                }
                if (num2 == 324)
                {
                    return new Color(225, 200, 250, 190) * num;
                }
                break;
            }
            if (this.type == 304)
            {
                return Color.White * num;
            }
            if (this.type == 306)
            {
                return this.color * num;
            }
            if (this.type == 292)
            {
                return Color.White;
            }
            if (this.type == 259)
            {
                return new Color(230, 230, 230, 230);
            }
            if (this.type == 261)
            {
                return new Color(230, 230, 230, 115);
            }
            if (this.type == 254 || this.type == 255)
            {
                return new Color(255, 255, 255, 0);
            }
            if (this.type == 258)
            {
                return new Color(150, 50, 50, 0);
            }
            if (this.type == 263 || this.type == 264)
            {
                return new Color((int)(this.color.R / 2 + 127), (int)(this.color.G + 127), (int)(this.color.B + 127), (int)(this.color.A / 8)) * 0.5f;
            }
            if (this.type == 235)
            {
                return new Color(255, 255, 255, 0);
            }
            if (((this.type >= 86 && this.type <= 91) || this.type == 262 || this.type == 286 || this.type == 138 || this.type == 325) && !this.noLight)
            {
                return new Color(255, 255, 255, 0);
            }
            if (this.type == 213 || this.type == 260)
            {
                int num3 = (int)(this.scale / 2.5f * 255f);
                return new Color(num3, num3, num3, num3);
            }
            if (this.type == 64 && this.alpha == 255 && this.noLight)
            {
                return new Color(255, 255, 255, 0);
            }
            if (this.type == 197)
            {
                return new Color(250, 250, 250, 150);
            }
            if ((this.type >= 110 && this.type <= 114) || this.type == 311 || this.type == 312 || this.type == 313)
            {
                return new Color(200, 200, 200, 0);
            }
            if (this.type == 204)
            {
                return new Color(255, 255, 255, 0);
            }
            if (this.type == 181)
            {
                return new Color(200, 200, 200, 0);
            }
            if (this.type == 182 || this.type == 206)
            {
                return new Color(255, 255, 255, 0);
            }
            if (this.type == 159)
            {
                return new Color(250, 250, 250, 50);
            }
            if (this.type == 163 || this.type == 205)
            {
                return new Color(250, 250, 250, 0);
            }
            if (this.type == 170)
            {
                return new Color(200, 200, 200, 100);
            }
            if (this.type == 180)
            {
                return new Color(200, 200, 200, 0);
            }
            if (this.type == 175)
            {
                return new Color(200, 200, 200, 0);
            }
            if (this.type == 183)
            {
                return new Color(50, 0, 0, 0);
            }
            if (this.type == 172)
            {
                return new Color(250, 250, 250, 150);
            }
            if (this.type == 160 || this.type == 162 || this.type == 164 || this.type == 173)
            {
                int num4 = (int)(250f * this.scale);
                return new Color(num4, num4, num4, 0);
            }
            if (this.type == 92 || this.type == 106 || this.type == 107)
            {
                return new Color(255, 255, 255, 0);
            }
            if (this.type == 185)
            {
                return new Color(200, 200, 255, 125);
            }
            if (this.type == 127 || this.type == 187)
            {
                return new Color((int)newColor.R, (int)newColor.G, (int)newColor.B, 25);
            }
            if (this.type == 156 || this.type == 230 || this.type == 234)
            {
                return new Color(255, 255, 255, 0);
            }
            if (this.type == 270)
            {
                return new Color((int)(newColor.R / 2 + 127), (int)(newColor.G / 2 + 127), (int)(newColor.B / 2 + 127), 25);
            }
            if (this.type == 271)
            {
                return new Color((int)(newColor.R / 2 + 127), (int)(newColor.G / 2 + 127), (int)(newColor.B / 2 + 127), 127);
            }
            if (this.type == 6 || this.type == 242 || this.type == 174 || this.type == 135 || this.type == 75 || this.type == 20 || this.type == 21 || this.type == 231 || this.type == 169 || (this.type >= 130 && this.type <= 134) || this.type == 158 || this.type == 293 || this.type == 294 || this.type == 295 || this.type == 296 || this.type == 297 || this.type == 298 || this.type == 307 || this.type == 310)
            {
                return new Color((int)newColor.R, (int)newColor.G, (int)newColor.B, 25);
            }
            if (this.type == 278)
            {
                return new Color(newColor.ToVector3() * this.color.ToVector3())
                {
                    A = 25
                };
            }
            if (this.type >= 219 && this.type <= 223)
            {
                newColor = Color.Lerp(newColor, Color.White, 0.5f);
                return new Color((int)newColor.R, (int)newColor.G, (int)newColor.B, 25);
            }
            if (this.type == 226 || this.type == 272)
            {
                newColor = Color.Lerp(newColor, Color.White, 0.8f);
                return new Color((int)newColor.R, (int)newColor.G, (int)newColor.B, 25);
            }
            if (this.type == 228)
            {
                newColor = Color.Lerp(newColor, Color.White, 0.8f);
                return new Color((int)newColor.R, (int)newColor.G, (int)newColor.B, 25);
            }
            if (this.type == 279)
            {
                int a = (int)newColor.A;
                newColor = Color.Lerp(newColor, Color.White, 0.8f);
                return new Color((int)newColor.R, (int)newColor.G, (int)newColor.B, a) * MathHelper.Min(this.scale, 1f);
            }
            if (this.type == 229 || this.type == 269)
            {
                newColor = Color.Lerp(newColor, Color.White, 0.6f);
                return new Color((int)newColor.R, (int)newColor.G, (int)newColor.B, 25);
            }
            if ((this.type == 68 || this.type == 70) && this.noGravity)
            {
                return new Color(255, 255, 255, 0);
            }
            int num7;
            int num6;
            int num5;
            if (this.type == 157)
            {
                num5 = (num6 = (num7 = 255));
                float num8 = (float)Main.mouseTextColor / 100f - 1.6f;
                num6 = (int)((float)num6 * num8);
                num5 = (int)((float)num5 * num8);
                num7 = (int)((float)num7 * num8);
                int num9 = (int)(100f * num8);
                num6 += 50;
                if (num6 > 255)
                {
                    num6 = 255;
                }
                num5 += 50;
                if (num5 > 255)
                {
                    num5 = 255;
                }
                num7 += 50;
                if (num7 > 255)
                {
                    num7 = 255;
                }
                return new Color(num6, num5, num7, num9);
            }
            if (this.type == 284)
            {
                return new Color(newColor.ToVector4() * this.color.ToVector4())
                {
                    A = this.color.A
                };
            }
            if (this.type == 327 && !Main.dayTime)
            {
                num6 = (int)(Main.rand.NextFloat() * 0.04f + 0.1f + (float)Main.DiscoR / 800f) * 255;
                num5 = (int)(Main.rand.NextFloat() * 0.04f + 0.1f + (float)Main.DiscoG / 800f) * 255;
                num7 = (int)(Main.rand.NextFloat() * 0.04f + 0.1f + (float)Main.DiscoB / 800f) * 255;
                if (num6 > (int)newColor.R)
                {
                    newColor.R = (byte)num6;
                }
                if (num5 > (int)newColor.G)
                {
                    newColor.G = (byte)num5;
                }
                if (num7 > (int)newColor.B)
                {
                    newColor.B = (byte)num7;
                }
                return newColor;
            }
            if (this.type == 58)
            {
                return new Color(255, 255, 255, 0);
            }
            if (this.type == 15 || this.type == 274 || this.type == 20 || this.type == 21 || this.type == 29 || this.type == 35 || this.type == 41 || this.type == 44 || this.type == 27 || this.type == 45 || this.type == 55 || this.type == 56 || this.type == 57 || this.type == 58 || this.type == 73 || this.type == 74)
            {
                num = (num + 3f) / 4f;
            }
            else if (this.type == 43)
            {
                num = (num + 9f) / 10f;
            }
            else
            {
                if (this.type >= 244 && this.type <= 247)
                {
                    return new Color(255, 255, 255, 0);
                }
                if (this.type == 66)
                {
                    return new Color((int)newColor.R, (int)newColor.G, (int)newColor.B, 0);
                }
                if (this.type == 267)
                {
                    return new Color((int)this.color.R, (int)this.color.G, (int)this.color.B, 0);
                }
                if (this.type == 71)
                {
                    return new Color(200, 200, 200, 0);
                }
                if (this.type == 72)
                {
                    return new Color(200, 200, 200, 200);
                }
            }
            num6 = (int)((float)newColor.R * num);
            num5 = (int)((float)newColor.G * num);
            num7 = (int)((float)newColor.B * num);
            int num10 = (int)newColor.A - this.alpha;
            if (num10 < 0)
            {
                num10 = 0;
            }
            if (num10 > 255)
            {
                num10 = 255;
            }
            return new Color(num6, num5, num7, num10);
        }
References Microsoft.Xna.Framework.Color.A, System.A, Terraria.Dust.alpha, Microsoft.Xna.Framework.Color.B, Terraria.Dust.color, Terraria.Main.dayTime, Terraria.Main.DiscoB, Terraria.Main.DiscoG, Terraria.Main.DiscoR, Terraria.Dust.fullBright, Microsoft.Xna.Framework.Color.G, int, Microsoft.Xna.Framework.Color.Lerp(), Microsoft.Xna.Framework.MathHelper.Min(), Terraria.Main.mouseTextColor, Terraria.Dust.noGravity, Terraria.Dust.noLight, Microsoft.Xna.Framework.Color.R, Terraria.Main.rand, Terraria.Dust.scale, Microsoft.Xna.Framework.Color.ToVector3(), Microsoft.Xna.Framework.Color.ToVector4(), Terraria.Dust.type, and Microsoft.Xna.Framework.Color.White.
Referenced by Terraria.GameContent.UI.UIDust.DrawDust(), and Terraria.Main.DrawDust().