Terraria Decompiled: Terraria.Dust.NewDustPerfect
NewDustPerfect()
static Dust Terraria.Dust.NewDustPerfect (Vector2 Position, int Type, Vector2? Velocity = null, int Alpha = 0, Color newColor = default(Color), float Scale = 1f) inline static
Definition at line 14 of file Dust.cs.
        {
            Dust dust = Main.dust[Dust.NewDust(Position, 0, 0, Type, 0f, 0f, Alpha, newColor, Scale)];
            dust.position = Position;
            if (Velocity != null)
            {
                dust.velocity = Velocity.Value;
            }
            return dust;
        }
References Terraria.Main.dust, and Terraria.Dust.NewDust().
Referenced by Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.Projectile.AI_001(), Terraria.NPC.AI_001_Slimes(), Terraria.NPC.AI_007_TownEntities(), Terraria.Projectile.AI_016_Bombs(), Terraria.Projectile.AI_026(), Terraria.NPC.AI_026_Unicorns(), Terraria.NPC.AI_047_GolemFist(), Terraria.Projectile.AI_075(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_111_DD2LightningBug(), Terraria.Projectile.AI_113_TargetSticker(), Terraria.NPC.AI_120_HallowBoss_DoMagicEffect(), Terraria.Projectile.AI_147_Explosion(), Terraria.Projectile.AI_150_GolfClubHelper(), Terraria.Projectile.AI_157_SharpTears(), Terraria.Projectile.AI_162_TigerPounce(), Terraria.Projectile.AI_165_Whip(), Terraria.Projectile.AI_168_FirstFractal(), Terraria.Projectile.AI_171_HallowBossRainbowStreak(), Terraria.Projectile.AI_179_FairyQueenLance(), Terraria.Projectile.AI_181_FairyQueenRangedItemShot(), Terraria.Projectile.AI_188_LightsBane(), Terraria.Projectile.AI_189_Volcano(), Terraria.Projectile.AI_190_NightsEdge(), Terraria.Projectile.AI_191_TrueNightsEdge(), Terraria.Projectile.AI_192_JuminoAnimation(), Terraria.Projectile.AI_195_JimsDrone(), Terraria.Projectile.AI_198_Flint(), Terraria.Projectile.AI_203_StormLightning(), Terraria.Projectile.AI_205_RemoteControlCar(), Terraria.GameContent.Drawing.ParticleOrchestrator.CopperSlimeEffect(), Terraria.Mount.DoConfettiMinecartEffect(), Terraria.Mount.DoExhaustMinecartEffect(), Terraria.Mount.DoGemMinecartEffect(), Terraria.Projectile.DoPalAppearEffect(), Terraria.Mount.DoSteamMinecartEffect(), Terraria.GameContent.Drawing.ParticleOrchestrator.ElderSlimeEffect(), Terraria.PopupText.EmitFancyFlashDust(), Terraria.GameContent.Golf.GolfHelper.ContactListener.EmitGolfballExplosion(), Terraria.GameContent.Golf.GolfHelper.ContactListener.EmitGolfballExplosion_v1(), Terraria.DelegateMethods.EmitGolfCartDust_StopForSolids(), Terraria.Projectile.HandleMovement(), Terraria.Player.ItemCheck(), Terraria.Player.ItemCheck_ApplyHoldStyle(), Terraria.Player.ItemCheck_ApplyUseStyle(), Terraria.Player.ItemCheck_EmitDrinkParticles(), Terraria.Player.ItemCheck_EmitFoodParticles(), Terraria.Player.ItemCheck_EmitHeldItemLight(), Terraria.Player.ItemCheck_EmitUseVisuals(), Terraria.Projectile.LightDisc_Bounce(), Terraria.Projectile.MakeBoulderOfEarthExplosion(), Terraria.GameContent.Drawing.ParticleOrchestrator.NerdySlimeEffect(), Terraria.GameContent.Golf.GolfHelper.ContactListener.OnCollision(), Terraria.Graphics.Renderers.StormLightningParticle.Prepare(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_BlueLightningSmall(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsBarnacleShotFiring(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsBarrelExplosion(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsDownDashExplosion(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsFlint(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_Excalibur(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_LoadOutChange(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_MoonLordWhip(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ShadowOrbExplosion(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ShimmerArrow(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_TerraBlade(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_TrueExcalibur(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_TrueNightsEdge(), Terraria.DelegateMethods.Minecart.SpawnFartCloud(), Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnLightningExplosionDust(), Terraria.Graphics.FinalFractalHelper.FinalFractalProfile.StripDust(), Terraria.Main.TeleportEffect(), Terraria.Mount.UpdateEffects(), Terraria.WorldItem.UpdateItem_VisualEffects(), and Terraria.Player.WingFrame().