Terraria Decompiled: Terraria.Dust.QuickDust
QuickDust() [1/3]
static Dust Terraria.Dust.QuickDust (int x, int y, Color color) inline static
Definition at line 268 of file Dust.cs.
        {
            return Dust.QuickDust(new Point(x, y), color);
        }
References Terraria.Dust.color, and Terraria.Dust.QuickDust().
Referenced by Terraria.Projectile.AI(), Terraria.StrayMethods.CheckArenaScore(), Terraria.GameContent.TownRoomManager.DisplayRooms(), Terraria.Dust.DrawDebugBox(), Terraria.Dust.QuickBox(), Terraria.Dust.QuickCircle(), Terraria.Dust.QuickDust(), Terraria.Dust.QuickDust(), Terraria.Dust.QuickDustLine(), Terraria.Dust.QuickDustSmall(), Terraria.StrayMethods.SendWalker(), Terraria.DataStructures.NPCFollowState.Update(), Terraria.Player.UpdateNetOffset(), and Terraria.NPC.UpdateNPC().