Terraria Decompiled: Terraria.Dust.dustWater
dustWater()
static int Terraria.Dust.dustWater () inline static
Definition at line 407 of file Dust.cs.
        {
            switch (Main.waterStyle)
            {
            case 2:
                return 98;
            case 3:
                return 99;
            case 4:
                return 100;
            case 5:
                return 101;
            case 6:
                return 102;
            case 7:
                return 103;
            case 8:
                return 104;
            case 9:
                return 105;
            case 10:
                return 123;
            case 12:
                return 288;
            }
            return 33;
        }
References Terraria.Main.waterStyle.
Referenced by Terraria.Projectile.AI_016_Bombs(), Terraria.Projectile.AI_061_FishingBobber_DoASplash(), Terraria.NPC.Collision_WaterCollision(), Terraria.Graphics.Renderers.FakeFishParticle.DoStandardWaterSplash(), Terraria.Player.ItemCheck(), Terraria.WorldItem.MoveInWorld(), Terraria.DelegateMethods.SpreadWater(), Terraria.Main.TeleportEffect(), Terraria.Rain.Update(), and Terraria.Projectile.Update().