Terraria Decompiled: Terraria.Dust.NewDustDirect
NewDustDirect()
static Dust Terraria.Dust.NewDustDirect (Vector2 Position, int Width, int Height, int Type, float SpeedX = 0f, float SpeedY = 0f, int Alpha = 0, Color newColor = default(Color), float Scale = 1f) inline static
Definition at line 26 of file Dust.cs.
        {
            Dust dust = Main.dust[Dust.NewDust(Position, Width, Height, Type, SpeedX, SpeedY, Alpha, newColor, Scale)];
            if (dust.velocity.HasNaNs())
            {
                dust.velocity = Vector2.Zero;
            }
            return dust;
        }
References Terraria.Main.dust, Terraria.Dust.NewDust(), Terraria.Dust.velocity, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.Projectile.AI_001(), Terraria.NPC.AI_001_Slimes(), Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_005_EaterOfSouls(), Terraria.Projectile.AI_009_MagicMissiles(), Terraria.Projectile.AI_009_MagicMissiles_Old(), Terraria.Projectile.AI_015_Flails_Dust(), Terraria.Projectile.AI_016_Bombs(), Terraria.Projectile.AI_019_Spears(), Terraria.Projectile.AI_019_Spears_Old(), Terraria.Projectile.AI_026(), Terraria.Projectile.AI_067_FreakingPirates(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_108_DivingFlyer(), Terraria.NPC.AI_109_DarkMage(), Terraria.NPC.AI_111_DD2LightningBug(), Terraria.NPC.AI_112_FairyCritter(), Terraria.Projectile.AI_113_TargetSticker(), Terraria.NPC.AI_117_BloodNautilus(), Terraria.NPC.AI_123_Deerclops(), Terraria.Projectile.AI_130_FlameBurstTower(), Terraria.Projectile.AI_131_FlameBurstShot(), Terraria.Projectile.AI_136_BetsyBreath(), Terraria.Projectile.AI_137_LightningAura(), Terraria.Projectile.AI_140_MonkStaffT1(), Terraria.Projectile.AI_142_MonkStaffT2And3(), Terraria.Projectile.AI_143_MonkStaffT2Ghast(), Terraria.Projectile.AI_144_DD2Pet(), Terraria.Projectile.AI_145_BookStaffStorm(), Terraria.Projectile.AI_151_SuperStar(), Terraria.Projectile.AI_152_SuperStarSlash(), Terraria.Projectile.AI_153_ToiletPop(), Terraria.Projectile.AI_155_MysticSnakeCoil(), Terraria.Projectile.AI_155_SpawnRopeIn(), Terraria.Projectile.AI_165_Whip(), Terraria.Projectile.AI_169_Smolstars(), Terraria.Projectile.AI_177_IceWhipSlicer(), Terraria.Projectile.AI_192_JuminoAnimation(), Terraria.Projectile.AI_193_Flamethrower(), Terraria.Projectile.AI_194_HorsemanPumpkin(), Terraria.Projectile.AI_199_MeteorOre(), Terraria.Projectile.AI_203_StormLightning(), Terraria.Projectile.AI_204_Digtoise(), Terraria.Projectile.AI_205_RemoteControlCar(), Terraria.DataStructures.PlayerDrawSet.BoringSetup(), Terraria.GameContent.SpelunkerProjectileHelper.CheckSpot(), Terraria.Player.ChickenBonesWingDust(), Terraria.Projectile.CreateImpactExplosion2_FlailTileCollision(), Terraria.Projectile.CreateImpactExplosion2_SleepyOctopod(), Terraria.Mount.DoSpawnDust(), Terraria.Main.DrawNPCExtras(), Terraria.GameContent.Drawing.TileDrawing.DrawTiles_EmitParticles(), Terraria.Cinematics.DD2Film.DryadPortalFade(), Terraria.Mount.EmitGolfCartSmoke(), Terraria.NPC.FairyEffects(), Terraria.NPC.FindFrame(), Terraria.Player.HeroicisWingDust(), Terraria.NPC.HitEffect(), Terraria.Player.ItemCheck_EmitUseVisuals(), Terraria.Player.KazzymodusWingDust(), Terraria.NPC.MakeTransitionEffectsForTextureChanges(), Terraria.Player.MowTheLawn(), Terraria.GameContent.LeashedEntities.LeashedCritter.Recall(), Terraria.Player.RocketBootVisuals(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_FlameWaders(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_PaladinsShieldHit(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_RainbowBoulder1(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_StormLightning(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_WallOfFleshGoatMountFlames(), Terraria.Player.SpawnFastRunParticles(), Terraria.GameContent.PotionOfReturnGateHelper.SpawnReturnPortalDust(), Terraria.GameContent.VoidLensHelper.SpawnVoidLensDust(), Terraria.DelegateMethods.SpreadDry(), Terraria.DelegateMethods.SpreadHoney(), Terraria.DelegateMethods.SpreadLava(), Terraria.DelegateMethods.SpreadTile(), Terraria.DelegateMethods.SpreadWater(), Terraria.Main.TeleportEffect(), Terraria.WorldGen.TreeGrowFX_AshShake(), Terraria.Player.Update(), Terraria.Mount.UpdateEffects(), Terraria.NPC.UpdateNPC_BuffApplyVFX(), Terraria.GameContent.LeashedEntities.FairyLeashedCritter.VisualEffects(), Terraria.Player.WingAirVisuals(), and Terraria.Player.WingFrame().