Terraria Decompiled: System.Runtime.InteropServices.DllImportAttribute.GetCustomAttribute
GetCustomAttribute()
static Attribute System.Runtime.InteropServices.DllImportAttribute.GetCustomAttribute (RuntimeMethodInfo method) inline static package
Definition at line 14 of file DllImportAttribute.cs.
        {
            if ((method.Attributes & MethodAttributes.PinvokeImpl) == MethodAttributes.PrivateScope)
            {
                return null;
            }
            string text = null;
            int metadataToken = method.MetadataToken;
            PInvokeAttributes pinvokeAttributes = PInvokeAttributes.CharSetNotSpec;
            string text2;
            method.GetPInvoke(out pinvokeAttributes, out text2, out text);
            CharSet charSet = CharSet.None;
            switch (pinvokeAttributes & PInvokeAttributes.CharSetMask)
            {
            case PInvokeAttributes.CharSetNotSpec:
                charSet = CharSet.None;
                break;
            case PInvokeAttributes.CharSetAnsi:
                charSet = CharSet.Ansi;
                break;
            case PInvokeAttributes.CharSetUnicode:
                charSet = CharSet.Unicode;
                break;
            case PInvokeAttributes.CharSetMask:
                charSet = CharSet.Auto;
                break;
            }
            CallingConvention callingConvention = CallingConvention.Cdecl;
            PInvokeAttributes pinvokeAttributes2 = pinvokeAttributes & PInvokeAttributes.CallConvMask;
            if (pinvokeAttributes2 <= PInvokeAttributes.CallConvCdecl)
            {
                if (pinvokeAttributes2 != PInvokeAttributes.CallConvWinapi)
                {
                    if (pinvokeAttributes2 == PInvokeAttributes.CallConvCdecl)
                    {
                        callingConvention = CallingConvention.Cdecl;
                    }
                }
                else
                {
                    callingConvention = CallingConvention.Winapi;
                }
            }
            else if (pinvokeAttributes2 != PInvokeAttributes.CallConvStdcall)
            {
                if (pinvokeAttributes2 != PInvokeAttributes.CallConvThiscall)
                {
                    if (pinvokeAttributes2 == PInvokeAttributes.CallConvFastcall)
                    {
                        callingConvention = CallingConvention.FastCall;
                    }
                }
                else
                {
                    callingConvention = CallingConvention.ThisCall;
                }
            }
            else
            {
                callingConvention = CallingConvention.StdCall;
            }
            bool flag = (pinvokeAttributes & PInvokeAttributes.NoMangle) > PInvokeAttributes.CharSetNotSpec;
            bool flag2 = (pinvokeAttributes & PInvokeAttributes.SupportsLastError) > PInvokeAttributes.CharSetNotSpec;
            bool flag3 = (pinvokeAttributes & PInvokeAttributes.BestFitMask) == PInvokeAttributes.BestFitEnabled;
            bool flag4 = (pinvokeAttributes & PInvokeAttributes.ThrowOnUnmappableCharMask) == PInvokeAttributes.ThrowOnUnmappableCharEnabled;
            bool flag5 = (method.GetMethodImplementationFlags() & MethodImplAttributes.PreserveSig) > MethodImplAttributes.IL;
            return new DllImportAttribute(text, text2, charSet, flag, flag2, flag5, callingConvention, flag3, flag4);
        }
References System.Reflection.RuntimeMethodInfo.Attributes, System.Runtime.InteropServices.DllImportAttribute.DllImportAttribute(), System.Reflection.RuntimeMethodInfo.GetMethodImplementationFlags(), System.Reflection.RuntimeMethodInfo.GetPInvoke(), System.Reflection.RuntimeMethodInfo.MetadataToken, and System.text.
Referenced by System.Reflection.RuntimeMethodInfo.GetPseudoCustomAttributes().