Terraria Decompiled: rail.RAIL_API_PINVOKE.SWIGPendingException.Retrieve
Retrieve()
static Exception rail.RAIL_API_PINVOKE.SWIGPendingException.Retrieve () inline static
Definition at line 17499 of file RAIL_API_PINVOKE.cs.
            {
                Exception ex = null;
                if (RAIL_API_PINVOKE.SWIGPendingException.numExceptionsPending > 0 && RAIL_API_PINVOKE.SWIGPendingException.pendingException != null)
                {
                    ex = RAIL_API_PINVOKE.SWIGPendingException.pendingException;
                    RAIL_API_PINVOKE.SWIGPendingException.pendingException = null;
                    Type typeFromHandle = typeof(RAIL_API_PINVOKE);
                    lock (typeFromHandle)
                    {
                        RAIL_API_PINVOKE.SWIGPendingException.numExceptionsPending--;
                    }
                }
                return ex;
            }
References rail.RAIL_API_PINVOKE.SWIGPendingException.numExceptionsPending, and rail.RAIL_API_PINVOKE.SWIGPendingException.pendingException.
Referenced by rail.RAIL_API_PINVOKE.SWIGExceptionHelper.SetPendingApplicationException(), rail.RAIL_API_PINVOKE.SWIGExceptionHelper.SetPendingArgumentException(), rail.RAIL_API_PINVOKE.SWIGExceptionHelper.SetPendingArgumentNullException(), rail.RAIL_API_PINVOKE.SWIGExceptionHelper.SetPendingArgumentOutOfRangeException(), rail.RAIL_API_PINVOKE.SWIGExceptionHelper.SetPendingArithmeticException(), rail.RAIL_API_PINVOKE.SWIGExceptionHelper.SetPendingDivideByZeroException(), rail.RAIL_API_PINVOKE.SWIGExceptionHelper.SetPendingIndexOutOfRangeException(), rail.RAIL_API_PINVOKE.SWIGExceptionHelper.SetPendingInvalidCastException(), rail.RAIL_API_PINVOKE.SWIGExceptionHelper.SetPendingInvalidOperationException(), rail.RAIL_API_PINVOKE.SWIGExceptionHelper.SetPendingIOException(), rail.RAIL_API_PINVOKE.SWIGExceptionHelper.SetPendingNullReferenceException(), rail.RAIL_API_PINVOKE.SWIGExceptionHelper.SetPendingOutOfMemoryException(), rail.RAIL_API_PINVOKE.SWIGExceptionHelper.SetPendingOverflowException(), and rail.RAIL_API_PINVOKE.SWIGExceptionHelper.SetPendingSystemException().