Terraria Decompiled: rail.RAIL_API_PINVOKE.SWIGPendingException.Set
Set()
static void rail.RAIL_API_PINVOKE.SWIGPendingException.Set (Exception e) inline static
Definition at line 17484 of file RAIL_API_PINVOKE.cs.
            {
                if (RAIL_API_PINVOKE.SWIGPendingException.pendingException != null)
                {
                    throw new ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + RAIL_API_PINVOKE.SWIGPendingException.pendingException.ToString() + ")", e);
                }
                RAIL_API_PINVOKE.SWIGPendingException.pendingException = e;
                Type typeFromHandle = typeof(RAIL_API_PINVOKE);
                lock (typeFromHandle)
                {
                    RAIL_API_PINVOKE.SWIGPendingException.numExceptionsPending++;
                }
            }
References rail.RAIL_API_PINVOKE.SWIGPendingException.numExceptionsPending, rail.RAIL_API_PINVOKE.SWIGPendingException.pendingException, and System.Exception.ToString().
Referenced by rail.RAIL_API_PINVOKE.SWIGExceptionHelper.SetPendingApplicationException(), rail.RAIL_API_PINVOKE.SWIGExceptionHelper.SetPendingArgumentException(), rail.RAIL_API_PINVOKE.SWIGExceptionHelper.SetPendingArgumentNullException(), rail.RAIL_API_PINVOKE.SWIGExceptionHelper.SetPendingArgumentOutOfRangeException(), rail.RAIL_API_PINVOKE.SWIGExceptionHelper.SetPendingArithmeticException(), rail.RAIL_API_PINVOKE.SWIGExceptionHelper.SetPendingDivideByZeroException(), rail.RAIL_API_PINVOKE.SWIGExceptionHelper.SetPendingIndexOutOfRangeException(), rail.RAIL_API_PINVOKE.SWIGExceptionHelper.SetPendingInvalidCastException(), rail.RAIL_API_PINVOKE.SWIGExceptionHelper.SetPendingInvalidOperationException(), rail.RAIL_API_PINVOKE.SWIGExceptionHelper.SetPendingIOException(), rail.RAIL_API_PINVOKE.SWIGExceptionHelper.SetPendingNullReferenceException(), rail.RAIL_API_PINVOKE.SWIGExceptionHelper.SetPendingOutOfMemoryException(), rail.RAIL_API_PINVOKE.SWIGExceptionHelper.SetPendingOverflowException(), and rail.RAIL_API_PINVOKE.SWIGExceptionHelper.SetPendingSystemException().