Terraria Decompiled: Newtonsoft.Json.Linq.JPropertyKeyedCollection.SetItem
SetItem()
override void Newtonsoft.Json.Linq.JPropertyKeyedCollection.SetItem (int index, JToken item) inline protected
Definition at line 131 of file JPropertyKeyedCollection.cs.
        {
            string keyForItem = this.GetKeyForItem(item);
            string keyForItem2 = this.GetKeyForItem(base.Items[index]);
            if (JPropertyKeyedCollection.Comparer.Equals(keyForItem2, keyForItem))
            {
                if (this._dictionary != null)
                {
                    this._dictionary[keyForItem] = item;
                }
            }
            else
            {
                this.AddKey(keyForItem, item);
                if (keyForItem2 != null)
                {
                    this.RemoveKey(keyForItem2);
                }
            }
            base.SetItem(index, item);
        }
References Newtonsoft.Json.Linq.JPropertyKeyedCollection._dictionary, Newtonsoft.Json.Linq.JPropertyKeyedCollection.AddKey(), Newtonsoft.Json.Linq.JPropertyKeyedCollection.Comparer, System.Collections.Generic.IEqualityComparer< in T >.Equals(), Newtonsoft.Json.Linq.JPropertyKeyedCollection.GetKeyForItem(), System.index, System.item, and Newtonsoft.Json.Linq.JPropertyKeyedCollection.RemoveKey().