Terraria Decompiled: Terraria.GameContent.UI.Elements.EmotesGroupListItem.EmotesGroupListItem
EmotesGroupListItem()
Terraria.GameContent.UI.Elements.EmotesGroupListItem.EmotesGroupListItem (LocalizedText groupTitle, int groupIndex, int maxEmotesPerRow, params int[] emotes) inline
Definition at line 14 of file EmotesGroupListItem.cs.
        {
            maxEmotesPerRow = 14;
            base.SetPadding(0f);
            this._groupIndex = groupIndex;
            this._maxEmotesPerRow = maxEmotesPerRow;
            this._tempTex = Main.Assets.Request<Texture2D>("Images/UI/ButtonFavoriteInactive", 1);
            int num = emotes.Length / this._maxEmotesPerRow;
            if (emotes.Length % this._maxEmotesPerRow != 0)
            {
                num++;
            }
            this.Height.Set((float)(30 + 36 * num), 0f);
            this.Width.Set(0f, 1f);
            UIElement uielement = new UIElement
            {
                Height = StyleDimension.FromPixels(30f),
                Width = StyleDimension.FromPixelsAndPercent(-20f, 1f),
                HAlign = 0.5f
            };
            uielement.SetPadding(0f);
            base.Append(uielement);
            UIHorizontalSeparator uihorizontalSeparator = new UIHorizontalSeparator(2, true)
            {
                Width = StyleDimension.FromPixelsAndPercent(0f, 1f),
                VAlign = 1f,
                HAlign = 0.5f,
                Color = Color.Lerp(Color.White, new Color(63, 65, 151, 255), 0.85f) * 0.9f
            };
            uielement.Append(uihorizontalSeparator);
            UIText uitext = new UIText(groupTitle, 1f, false)
            {
                VAlign = 1f,
                HAlign = 0.5f,
                Top = StyleDimension.FromPixels(-6f)
            };
            uielement.Append(uitext);
            float num2 = 6f;
            for (int i = 0; i < emotes.Length; i++)
            {
                int num3 = emotes[i];
                int num4 = i / this._maxEmotesPerRow;
                int num5 = i % this._maxEmotesPerRow;
                int num6 = emotes.Length % this._maxEmotesPerRow;
                if (emotes.Length / this._maxEmotesPerRow != num4)
                {
                    num6 = this._maxEmotesPerRow;
                }
                if (num6 == 0)
                {
                    num6 = this._maxEmotesPerRow;
                }
                float num7 = 36f * ((float)num6 / 2f);
                num7 -= 16f;
                num7 = -16f;
                EmoteButton emoteButton = new EmoteButton(num3)
                {
                    HAlign = 0f,
                    VAlign = 0f,
                    Top = StyleDimension.FromPixels((float)(30 + num4 * 36) + num2),
                    Left = StyleDimension.FromPixels((float)(36 * num5) - num7)
                };
                base.Append(emoteButton);
                emoteButton.SetSnapPoint("Group " + groupIndex, i, null, null);
            }
        }
References Terraria.GameContent.UI.Elements.EmotesGroupListItem._maxEmotesPerRow, Terraria.UI.UIElement.Append(), Terraria.Main.Assets, Terraria.UI.StyleDimension.FromPixels(), Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.Left, Microsoft.Xna.Framework.Color.Lerp(), Terraria.UI.StyleDimension.Set(), Terraria.UI.UIElement.SetPadding(), Terraria.UI.UIElement.SetSnapPoint(), Terraria.UI.UIElement.Top, Terraria.UI.UIElement.VAlign, Microsoft.Xna.Framework.Color.White, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.Elements.EmotesGroupListItem.CompareTo().