Terraria Decompiled: System.IO.FileSystemInfo.ThrowNotFound
ThrowNotFound()
static void System.IO.FileSystemInfo.ThrowNotFound (string path) inline static package
Definition at line 124 of file FileSystemInfo.cs.
        {
            bool flag = !Directory.Exists(Path.GetDirectoryName(PathInternal.TrimEndingDirectorySeparator(path)));
            throw Interop.GetExceptionForIoErrno(new Interop.ErrorInfo(Interop.Error.ENOENT), path, flag);
        }
References System.IO.Directory.Exists(), System.IO.Path.GetDirectoryName(), and System.IO.PathInternal.TrimEndingDirectorySeparator().
Referenced by System.IO.FileSystem.GetAttributes(), and System.IO.FileStatus.SetAttributes().