Terraria Decompiled: System.Resources.Win32IconFileReader.ReadIcons
ReadIcons()
ICONDIRENTRY[] System.Resources.Win32IconFileReader.ReadIcons () inline
Definition at line 16 of file Win32IconFileReader.cs.
        {
            ICONDIRENTRY[] array2;
            using (BinaryReader binaryReader = new BinaryReader(this.iconFile))
            {
                bool flag = binaryReader.ReadInt16() != 0;
                int num = (int)binaryReader.ReadInt16();
                if (flag || num != 1)
                {
                    throw new Exception("Invalid .ico file format");
                }
                long num2 = (long)binaryReader.ReadInt16();
                ICONDIRENTRY[] array = new ICONDIRENTRY[num2];
                int num3 = 0;
                while ((long)num3 < num2)
                {
                    ICONDIRENTRY icondirentry = new ICONDIRENTRY();
                    icondirentry.bWidth = binaryReader.ReadByte();
                    icondirentry.bHeight = binaryReader.ReadByte();
                    icondirentry.bColorCount = binaryReader.ReadByte();
                    icondirentry.bReserved = binaryReader.ReadByte();
                    icondirentry.wPlanes = binaryReader.ReadInt16();
                    icondirentry.wBitCount = binaryReader.ReadInt16();
                    int num4 = binaryReader.ReadInt32();
                    int num5 = binaryReader.ReadInt32();
                    icondirentry.image = new byte[num4];
                    long position = this.iconFile.Position;
                    this.iconFile.Position = (long)num5;
                    this.iconFile.Read(icondirentry.image, 0, num4);
                    this.iconFile.Position = position;
                    if (icondirentry.wPlanes == 0)
                    {
                        icondirentry.wPlanes = (short)((int)icondirentry.image[12] | ((int)icondirentry.image[13] << 8));
                    }
                    if (icondirentry.wBitCount == 0)
                    {
                        icondirentry.wBitCount = (short)((int)icondirentry.image[14] | ((int)icondirentry.image[15] << 8));
                    }
                    array[num3] = icondirentry;
                    num3++;
                }
                array2 = array;
            }
            return array2;
        }
References System.array, System.Resources.Win32IconFileReader.iconFile, System.Resources.ICONDIRENTRY.image, int, long, System.IO.Stream.Position, System.IO.Stream.Read(), System.IO.BinaryReader.ReadByte(), System.IO.BinaryReader.ReadInt16(), System.IO.BinaryReader.ReadInt32(), System.Resources.ICONDIRENTRY.wBitCount, and System.Resources.ICONDIRENTRY.wPlanes.