Terraria Decompiled: Microsoft.Xna.Framework.Audio.SoundEffect.FAudioContext.Dispose
Dispose()
void Microsoft.Xna.Framework.Audio.SoundEffect.FAudioContext.Dispose () inline
Definition at line 472 of file SoundEffect.cs.
            {
                if (this.ReverbVoice != IntPtr.Zero)
                {
                    FAudio.FAudioVoice_DestroyVoice(this.ReverbVoice);
                    this.ReverbVoice = IntPtr.Zero;
                    FNAPlatform.Free(this.reverbSends.pSends);
                }
                if (this.MasterVoice != IntPtr.Zero)
                {
                    FAudio.FAudioVoice_DestroyVoice(this.MasterVoice);
                }
                if (this.Handle != IntPtr.Zero)
                {
                    FAudio.FAudio_Release(this.Handle);
                }
            }
References FAudio.FAudio_Release(), FAudio.FAudioVoice_DestroyVoice(), Microsoft.Xna.Framework.FNAPlatform.Free, Microsoft.Xna.Framework.Audio.SoundEffect.FAudioContext.Handle, Microsoft.Xna.Framework.Audio.SoundEffect.FAudioContext.MasterVoice, Microsoft.Xna.Framework.Audio.SoundEffect.FAudioContext.reverbSends, Microsoft.Xna.Framework.Audio.SoundEffect.FAudioContext.ReverbVoice, and System.IntPtr.Zero.
Referenced by Microsoft.Xna.Framework.Audio.SoundEffect.FAudioContext.Create().