Terraria Decompiled: Microsoft.Xna.Framework.Audio.SoundEffect.FAudioContext.FAudioContext
FAudioContext()
Microsoft.Xna.Framework.Audio.SoundEffect.FAudioContext.FAudioContext (IntPtr ctx, uint devices) inline private
Definition at line 439 of file SoundEffect.cs.
            {
                this.Handle = ctx;
                uint num;
                for (num = 0U; num < devices; num += 1U)
                {
                    FAudio.FAudio_GetDeviceDetails(this.Handle, num, out this.DeviceDetails);
                    if ((this.DeviceDetails.Role & FAudio.FAudioDeviceRole.FAudioDefaultGameDevice) == FAudio.FAudioDeviceRole.FAudioDefaultGameDevice)
                    {
                        break;
                    }
                }
                if (num == devices)
                {
                    num = 0U;
                    FAudio.FAudio_GetDeviceDetails(this.Handle, num, out this.DeviceDetails);
                }
                if (FAudio.FAudio_CreateMasteringVoice(this.Handle, out this.MasterVoice, 0U, 0U, 0U, num, IntPtr.Zero) != 0U)
                {
                    FAudio.FAudio_Release(ctx);
                    this.Handle = IntPtr.Zero;
                    FNALoggerEXT.LogError("Failed to create mastering voice!");
                    return;
                }
                this.CurveDistanceScaler = 1f;
                this.DopplerScale = 1f;
                this.SpeedOfSound = 343.5f;
                this.Handle3D = new byte[20];
                FAudio.F3DAudioInitialize(this.DeviceDetails.OutputFormat.dwChannelMask, this.SpeedOfSound, this.Handle3D);
                SoundEffect.FAudioContext.Context = this;
            }
References Microsoft.Xna.Framework.Audio.SoundEffect.FAudioContext.DeviceDetails, FAudio.F3DAudioInitialize(), FAudio.FAudio_CreateMasteringVoice(), FAudio.FAudio_GetDeviceDetails(), FAudio.FAudio_Release(), Microsoft.Xna.Framework.Audio.SoundEffect.FAudioContext.Handle, Microsoft.Xna.Framework.FNALoggerEXT.LogError, System.U, and System.IntPtr.Zero.