Terraria Decompiled: Microsoft.Xna.Framework.Audio.SoundEffect.FAudioContext.AttachReverb
AttachReverb()
unsafe void Microsoft.Xna.Framework.Audio.SoundEffect.FAudioContext.AttachReverb (IntPtr voice) inline
Definition at line 491 of file SoundEffect.cs.
            {
                if (this.ReverbVoice == IntPtr.Zero)
                {
                    IntPtr intPtr;
                    FAudio.FAudioCreateReverb(out intPtr, 0U);
                    IntPtr intPtr2 = FNAPlatform.Malloc(MarshalHelper.SizeOf<FAudio.FAudioEffectChain>());
                    FAudio.FAudioEffectChain* ptr = (FAudio.FAudioEffectChain*)(void*)intPtr2;
                    ptr->EffectCount = 1U;
                    ptr->pEffectDescriptors = FNAPlatform.Malloc(MarshalHelper.SizeOf<FAudio.FAudioEffectDescriptor>());
                    FAudio.FAudioEffectDescriptor* ptr2 = (FAudio.FAudioEffectDescriptor*)(void*)ptr->pEffectDescriptors;
                    ptr2->InitialState = 1;
                    ptr2->OutputChannels = ((this.DeviceDetails.OutputFormat.Format.nChannels == 6) ? 6U : 1U);
                    ptr2->pEffect = intPtr;
                    FAudio.FAudio_CreateSubmixVoice(this.Handle, out this.ReverbVoice, 1U, this.DeviceDetails.OutputFormat.Format.nSamplesPerSec, 0U, 0U, IntPtr.Zero, intPtr2);
                    FAudio.FAPOBase_Release(intPtr);
                    FNAPlatform.Free(ptr->pEffectDescriptors);
                    FNAPlatform.Free(intPtr2);
                    IntPtr intPtr3 = FNAPlatform.Malloc(MarshalHelper.SizeOf<FAudio.FAudioFXReverbParameters>());
                    FAudio.FAudioFXReverbParameters* ptr3 = (FAudio.FAudioFXReverbParameters*)(void*)intPtr3;
                    ptr3->WetDryMix = 100f;
                    ptr3->ReflectionsDelay = 7U;
                    ptr3->ReverbDelay = 11;
                    ptr3->RearDelay = 5;
                    ptr3->PositionLeft = 6;
                    ptr3->PositionRight = 6;
                    ptr3->PositionMatrixLeft = 27;
                    ptr3->PositionMatrixRight = 27;
                    ptr3->EarlyDiffusion = 15;
                    ptr3->LateDiffusion = 15;
                    ptr3->LowEQGain = 8;
                    ptr3->LowEQCutoff = 4;
                    ptr3->HighEQGain = 8;
                    ptr3->HighEQCutoff = 6;
                    ptr3->RoomFilterFreq = 5000f;
                    ptr3->RoomFilterMain = -10f;
                    ptr3->RoomFilterHF = -1f;
                    ptr3->ReflectionsGain = -26.02f;
                    ptr3->ReverbGain = 10f;
                    ptr3->DecayTime = 1.49f;
                    ptr3->Density = 100f;
                    ptr3->RoomSize = 100f;
                    FAudio.FAudioVoice_SetEffectParameters(this.ReverbVoice, 0U, intPtr3, (uint)MarshalHelper.SizeOf<FAudio.FAudioFXReverbParameters>(), 0U);
                    FNAPlatform.Free(intPtr3);
                    this.reverbSends = default(FAudio.FAudioVoiceSends);
                    this.reverbSends.SendCount = 2U;
                    this.reverbSends.pSends = FNAPlatform.Malloc(2 * MarshalHelper.SizeOf<FAudio.FAudioSendDescriptor>());
                    FAudio.FAudioSendDescriptor* ptr4 = (FAudio.FAudioSendDescriptor*)(void*)this.reverbSends.pSends;
                    ptr4->Flags = 0U;
                    ptr4->pOutputVoice = this.MasterVoice;
                    ptr4[1].Flags = 0U;
                    ptr4[1].pOutputVoice = this.ReverbVoice;
                }
                FAudio.FAudioVoice_SetOutputVoices(voice, ref this.reverbSends);
            }
References Microsoft.Xna.Framework.Audio.SoundEffect.FAudioContext.DeviceDetails, FAudio.FAPOBase_Release(), FAudio.FAudio_CreateSubmixVoice(), FAudio.FAudioCreateReverb(), FAudio.FAudioVoice_SetEffectParameters(), FAudio.FAudioVoice_SetOutputVoices(), Microsoft.Xna.Framework.FNAPlatform.Free, Microsoft.Xna.Framework.Audio.SoundEffect.FAudioContext.Handle, FAudio.FAudioEffectDescriptor.InitialState, Microsoft.Xna.Framework.FNAPlatform.Malloc, Microsoft.Xna.Framework.Audio.SoundEffect.FAudioContext.MasterVoice, Microsoft.Xna.Framework.Audio.SoundEffect.FAudioContext.reverbSends, Microsoft.Xna.Framework.Audio.SoundEffect.FAudioContext.ReverbVoice, System.U, and System.IntPtr.Zero.