Terraria Decompiled: Microsoft.Xna.Framework.Audio.SoundEffect.FAudioContext.ProgramExit
ProgramExit()
static void Microsoft.Xna.Framework.Audio.SoundEffect.FAudioContext.ProgramExit (object sender, EventArgs e) inline static private
Definition at line 578 of file SoundEffect.cs.
            {
                SoundEffect.FAudioContext.ProgramExiting = true;
                if (SoundEffect.FAudioContext.Context != null)
                {
                    GC.Collect();
                    SoundEffect.FAudioContext.Context.Dispose();
                }
            }
References System.GC.Collect(), Microsoft.Xna.Framework.Audio.SoundEffect.FAudioContext.Context, and Microsoft.Xna.Framework.Audio.SoundEffect.Dispose().
Referenced by Microsoft.Xna.Framework.Audio.SoundEffect.FAudioContext.Create().