Terraria Decompiled: Terraria.Localization.LanguageManager.LoadLanguageFromFileTextJson
LoadLanguageFromFileTextJson()
void Terraria.Localization.LanguageManager.LoadLanguageFromFileTextJson (string fileText, bool canCreateCategories) inline
Definition at line 331 of file LanguageManager.cs.
        {
            foreach (KeyValuePair<string, Dictionary<string, string>> keyValuePair in JsonConvert.DeserializeObject<Dictionary<string, Dictionary<string, string>>>(fileText))
            {
                string key = keyValuePair.Key;
                foreach (KeyValuePair<string, string> keyValuePair2 in keyValuePair.Value)
                {
                    string text = keyValuePair.Key + "." + keyValuePair2.Key;
                    if (!this.UpdateTextValue(text, keyValuePair2.Value) && canCreateCategories)
                    {
                        this._localizedTexts.Add(text, new LocalizedText(text, keyValuePair2.Value));
                        List<string> list;
                        if (!this._categoryGroupedKeys.TryGetValue(keyValuePair.Key, out list))
{
                            this._categoryGroupedKeys.Add(keyValuePair.Key, list = new List<string>());
                        }
                        list.Add(keyValuePair2.Key);
                    }
                }
            }
        }
References Terraria.Localization.LanguageManager._categoryGroupedKeys, Terraria.Localization.LanguageManager._localizedTexts, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), Newtonsoft.Json.JsonConvert.DeserializeObject(), System.Collections.Generic.KeyValuePair< TKey, TValue >.Key, System.key, System.list, System.text, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), Terraria.Localization.LanguageManager.UpdateTextValue(), and System.Collections.Generic.KeyValuePair< TKey, TValue >.Value.
Referenced by Terraria.Localization.LanguageManager.LoadFilesForCulture(), and Terraria.Localization.LanguageManager.LoadFromContentSources().