Terraria Decompiled: Terraria.Localization.LanguageManager.LoadFromContentSources
LoadFromContentSources()
void Terraria.Localization.LanguageManager.LoadFromContentSources () inline private
Definition at line 240 of file LanguageManager.cs.
        {
            string name = this.ActiveCulture.Name;
            string text = ("Localization" + Path.DirectorySeparatorChar.ToString() + name).ToLower();
            foreach (IContentSource contentSource in this._contentSources)
            {
                foreach (string text2 in contentSource.GetAllAssetsStartingWith(text))
                {
                    string extension = contentSource.GetExtension(text2);
                    if (extension == ".json" || extension == ".csv")
                    {
                        try
{
                            using (Stream stream = contentSource.OpenStream(text2))
{
                                using (StreamReader streamReader = new StreamReader(stream))
{
                                    string text3 = streamReader.ReadToEnd();
                                    if (extension == ".json")
{
                                        this.LoadLanguageFromFileTextJson(text3, false);
                                    }
                                    if (extension == ".csv")
{
                                        this.LoadLanguageFromFileTextCsv(text3);
                                    }
                                }
                            }
                        }
                        catch (Exception ex)
{
                            IAssetRepository assetRepository = XnaExtensions.Get<IAssetRepository>(Main.instance.Services);
                            if (assetRepository != null && assetRepository.AssetLoadFailHandler != null)
{
                                string text4 = text2 + extension;
                                assetRepository.AssetLoadFailHandler.Invoke(text4, AssetLoadException.FromAssetException(text4, ex));
                            }
                        }
                    }
                }
            }
        }
References Terraria.Localization.LanguageManager._contentSources, Terraria.Localization.LanguageManager.ActiveCulture, ReLogic.Content.IAssetRepository.AssetLoadFailHandler, System.IO.Path.DirectorySeparatorChar, ReLogic.Content.AssetLoadException.FromAssetException(), ReLogic.Content.Sources.IContentSource.GetAllAssetsStartingWith(), ReLogic.Content.Sources.IContentSource.GetExtension(), Terraria.Main.instance, Terraria.Localization.LanguageManager.LoadLanguageFromFileTextCsv(), Terraria.Localization.LanguageManager.LoadLanguageFromFileTextJson(), System.name, Terraria.Localization.GameCulture.Name, ReLogic.Content.Sources.IContentSource.OpenStream(), System.IO.StreamReader.ReadToEnd(), Microsoft.Xna.Framework.Game.Services, and System.text.
Referenced by Terraria.Localization.LanguageManager.LoadLanguage().