Terraria Decompiled: Terraria.Localization.LanguageManager.LoadLanguage
LoadLanguage()
void Terraria.Localization.LanguageManager.LoadLanguage (GameCulture culture) inline private
Definition at line 164 of file LanguageManager.cs.
        {
            this.ActiveCulture = culture;
            this._textVariations.Clear();
            this.LoadFilesForCulture(culture);
            this.LoadFromContentSources();
            this.ProcessCopyCommandsInTexts();
        }
References Terraria.Localization.LanguageManager._textVariations, System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.culture, Terraria.Localization.LanguageManager.LoadFilesForCulture(), Terraria.Localization.LanguageManager.LoadFromContentSources(), and Terraria.Localization.LanguageManager.ProcessCopyCommandsInTexts().
Referenced by Terraria.Localization.LanguageManager.ReloadLanguage().