Terraria Decompiled: Terraria.Localization.LanguageManager.LoadFilesForCulture
LoadFilesForCulture()
void Terraria.Localization.LanguageManager.LoadFilesForCulture (GameCulture culture) inline private
Definition at line 174 of file LanguageManager.cs.
        {
            foreach (string text in this.GetLanguageFilesForCulture(culture))
            {
                try
                {
                    string text2 = null;
                    if (text2 == null)
                    {
                        text2 = Utils.ReadEmbeddedResource(text);
                    }
                    if (text2 == null || text2.Length < 2)
                    {
                        throw new FormatException();
                    }
                    this.LoadLanguageFromFileTextJson(text2, true);
                }
                catch (Exception)
                {
                    if (Debugger.IsAttached)
                    {
                        Debugger.Break();
                    }
                    Console.WriteLine("Failed to load language file: " + text);
                    break;
                }
            }
        }
References System.Diagnostics.Debugger.Break(), System.culture, Terraria.Localization.LanguageManager.GetLanguageFilesForCulture(), System.Diagnostics.Debugger.IsAttached, Terraria.Localization.LanguageManager.LoadLanguageFromFileTextJson(), Terraria.Utils.ReadEmbeddedResource(), System.text, and System.Console.WriteLine().
Referenced by Terraria.Localization.LanguageManager.LoadLanguage().