Terraria Decompiled: Terraria.Localization.LanguageManager.IndexedFromCategory
IndexedFromCategory()
LocalizedText Terraria.Localization.LanguageManager.IndexedFromCategory (string categoryName, int index) inline
Definition at line 498 of file LanguageManager.cs.
        {
            List<string> list;
            if (!this._categoryGroupedKeys.TryGetValue(categoryName, out list))
            {
                return new LocalizedText(categoryName + ".INDEXED", categoryName + ".INDEXED");
            }
            int num = index % list.Count;
            return this.GetText(categoryName + "." + list[num]);
        }
References Terraria.Localization.LanguageManager._categoryGroupedKeys, Terraria.Localization.LanguageManager.GetText(), System.index, System.list, and System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue().
Referenced by Terraria.GameContent.LucyAxeMessage.GetTextForVariation().