Terraria Decompiled: Terraria.Localization.LanguageManager.ReloadLanguage
ReloadLanguage()
void Terraria.Localization.LanguageManager.ReloadLanguage (GameCulture targetCulture) inline private
Definition at line 146 of file LanguageManager.cs.
        {
            if (this.ActiveCulture != this._fallbackCulture)
            {
                this.SetAllTextValuesToKeys();
                if (targetCulture != this._fallbackCulture)
                {
                    this.LoadLanguage(this._fallbackCulture);
                }
            }
            this.LoadLanguage(targetCulture);
            if (this.OnLanguageChanged != null)
            {
                this.OnLanguageChanged(this);
            }
        }
References Terraria.Localization.LanguageManager._fallbackCulture, Terraria.Localization.LanguageManager.ActiveCulture, Terraria.Localization.LanguageManager.LoadLanguage(), Terraria.Localization.LanguageManager.OnLanguageChanged, and Terraria.Localization.LanguageManager.SetAllTextValuesToKeys().
Referenced by Terraria.Localization.LanguageManager.HotReloadContentFile(), Terraria.Localization.LanguageManager.SetLanguage(), and Terraria.Localization.LanguageManager.UseSources().