Terraria Decompiled: Terraria.Localization.LanguageManager.LoadLanguageFromFileTextCsv
LoadLanguageFromFileTextCsv()
void Terraria.Localization.LanguageManager.LoadLanguageFromFileTextCsv (string fileText) inline
Definition at line 284 of file LanguageManager.cs.
        {
            using (TextReader textReader = new StringReader(fileText))
            {
                using (CsvReader csvReader = new CsvReader(textReader))
                {
                    csvReader.Configuration.HasHeaderRecord = true;
                    if (csvReader.ReadHeader())
                    {
                        string[] fieldHeaders = csvReader.FieldHeaders;
                        int num = -1;
                        int num2 = -1;
                        for (int i = 0; i < fieldHeaders.Length; i++)
{
                            string text = fieldHeaders[i].ToLower();
                            if (text == "translation")
{
                                num2 = i;
                            }
                            if (text == "key")
{
                                num = i;
                            }
                        }
                        if (num != -1 && num2 != -1)
{
                            int num3 = Math.Max(num, num2) + 1;
                            while (csvReader.Read())
{
                                string[] currentRecord = csvReader.CurrentRecord;
                                if (currentRecord.Length >= num3)
{
                                    string text2 = currentRecord[num];
                                    string text3 = currentRecord[num2];
                                    if (!string.IsNullOrWhiteSpace(text2) && !string.IsNullOrWhiteSpace(text3))
{
                                        this.UpdateTextValue(text2, text3);
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
References CsvHelper.CsvReader.CurrentRecord, CsvHelper.CsvReader.FieldHeaders, System.Math.Max(), CsvHelper.CsvReader.Read(), CsvHelper.CsvReader.ReadHeader(), System.text, and Terraria.Localization.LanguageManager.UpdateTextValue().
Referenced by Terraria.Localization.LanguageManager.LoadFromContentSources().