Terraria Decompiled: System.Security.AccessControl.GenericSecurityDescriptor.GetBinaryForm
GetBinaryForm()
void System.Security.AccessControl.GenericSecurityDescriptor.GetBinaryForm (byte[] binaryForm, int offset) inline
Definition at line 98 of file GenericSecurityDescriptor.cs.
        {
            if (binaryForm == null)
            {
                throw new ArgumentNullException("binaryForm");
            }
            int binaryLength = this.BinaryLength;
            if (offset < 0 || offset > binaryForm.Length - binaryLength)
            {
                throw new ArgumentOutOfRangeException("offset");
            }
            ControlFlags controlFlags = this.ControlFlags;
            if (this.DaclIsUnmodifiedAefa)
            {
                controlFlags &= ~ControlFlags.DiscretionaryAclPresent;
            }
            binaryForm[offset] = GenericSecurityDescriptor.Revision;
            binaryForm[offset + 1] = this.InternalReservedField;
            this.WriteUShort((ushort)controlFlags, binaryForm, offset + 2);
            int num = 20;
            if (this.Owner != null)
            {
                this.WriteInt(num, binaryForm, offset + 4);
                this.Owner.GetBinaryForm(binaryForm, offset + num);
                num += this.Owner.BinaryLength;
            }
            else
            {
                this.WriteInt(0, binaryForm, offset + 4);
            }
            if (this.Group != null)
            {
                this.WriteInt(num, binaryForm, offset + 8);
                this.Group.GetBinaryForm(binaryForm, offset + num);
                num += this.Group.BinaryLength;
            }
            else
            {
                this.WriteInt(0, binaryForm, offset + 8);
            }
            GenericAcl internalSacl = this.InternalSacl;
            if (this.SaclPresent)
            {
                this.WriteInt(num, binaryForm, offset + 12);
                internalSacl.GetBinaryForm(binaryForm, offset + num);
                num += this.InternalSacl.BinaryLength;
            }
            else
            {
                this.WriteInt(0, binaryForm, offset + 12);
            }
            GenericAcl internalDacl = this.InternalDacl;
            if (this.DaclPresent && !this.DaclIsUnmodifiedAefa)
            {
                this.WriteInt(num, binaryForm, offset + 16);
                internalDacl.GetBinaryForm(binaryForm, offset + num);
                num += this.InternalDacl.BinaryLength;
                return;
            }
            this.WriteInt(0, binaryForm, offset + 16);
        }
References System.Security.AccessControl.GenericAcl.BinaryLength, System.Security.AccessControl.GenericSecurityDescriptor.BinaryLength, System.Security.Principal.SecurityIdentifier.BinaryLength, System.Security.AccessControl.GenericSecurityDescriptor.ControlFlags, System.Security.AccessControl.GenericSecurityDescriptor.DaclIsUnmodifiedAefa, System.Security.AccessControl.GenericSecurityDescriptor.DaclPresent, System.Security.AccessControl.GenericAcl.GetBinaryForm(), System.Security.Principal.SecurityIdentifier.GetBinaryForm(), System.Security.AccessControl.GenericSecurityDescriptor.Group, System.Security.AccessControl.GenericSecurityDescriptor.InternalDacl, System.Security.AccessControl.GenericSecurityDescriptor.InternalReservedField, System.Security.AccessControl.GenericSecurityDescriptor.InternalSacl, System.offset, System.Security.AccessControl.GenericSecurityDescriptor.Owner, System.Security.AccessControl.GenericSecurityDescriptor.Revision, System.Security.AccessControl.GenericSecurityDescriptor.SaclPresent, System.Security.AccessControl.GenericSecurityDescriptor.WriteInt(), and System.Security.AccessControl.GenericSecurityDescriptor.WriteUShort().
Referenced by System.Security.AccessControl.ObjectSecurity< T >.GetSecurityDescriptorBinaryForm().