Terraria Decompiled: System.Security.AccessControl.GenericSecurityDescriptor.GetSddlForm
GetSddlForm()
string System.Security.AccessControl.GenericSecurityDescriptor.GetSddlForm (AccessControlSections includeSections) inline
Definition at line 161 of file GenericSecurityDescriptor.cs.
        {
            StringBuilder stringBuilder = new StringBuilder();
            if ((includeSections & AccessControlSections.Owner) != AccessControlSections.None && this.Owner != null)
            {
                stringBuilder.AppendFormat(CultureInfo.InvariantCulture, "O:{0}", this.Owner.GetSddlForm());
            }
            if ((includeSections & AccessControlSections.Group) != AccessControlSections.None && this.Group != null)
            {
                stringBuilder.AppendFormat(CultureInfo.InvariantCulture, "G:{0}", this.Group.GetSddlForm());
            }
            if ((includeSections & AccessControlSections.Access) != AccessControlSections.None && this.DaclPresent && !this.DaclIsUnmodifiedAefa)
            {
                stringBuilder.AppendFormat(CultureInfo.InvariantCulture, "D:{0}", this.InternalDacl.GetSddlForm(this.ControlFlags, true));
            }
            if ((includeSections & AccessControlSections.Audit) != AccessControlSections.None && this.SaclPresent)
            {
                stringBuilder.AppendFormat(CultureInfo.InvariantCulture, "S:{0}", this.InternalSacl.GetSddlForm(this.ControlFlags, false));
            }
            return stringBuilder.ToString();
        }
References System.Text.StringBuilder.AppendFormat(), System.Globalization.CultureInfo.InvariantCulture, and System.Text.StringBuilder.ToString().
Referenced by System.Security.AccessControl.ObjectSecurity< T >.GetSecurityDescriptorSddlForm().