Terraria Decompiled: Terraria.UI.StyleDimension.Set
Set()
void Terraria.UI.StyleDimension.Set (float pixels, float precent) inline
Definition at line 16 of file StyleDimension.cs.
        {
            this.Pixels = pixels;
            this.Precent = precent;
        }
Referenced by Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.AddBackButton(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.AddPublishButton(), Terraria.GameContent.UI.States.UIWorldCreationAdvanced.AddSpecialSeedOptions(), Terraria.GameContent.UI.States.UIWorldCreation.AddWorldDifficultyOptions(), Terraria.GameContent.UI.States.UIWorldCreation.AddWorldEvilOptions(), Terraria.GameContent.UI.States.UIWorldCreation.AddWorldSizeOptions(), Terraria.GameContent.UI.States.UIBestiaryTest.BuildPage(), Terraria.GameContent.UI.States.UIDebugCommandsList.BuildPage(), Terraria.GameContent.UI.States.UIReportsPage.BuildPage(), Terraria.GameContent.UI.States.UIResourcePackInfoMenu.BuildPage(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.BuildPage(), Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.BuildPage(), Terraria.GameContent.UI.Elements.UIBestiaryEntryInfoPage.CheckScrollBar(), Terraria.GameContent.UI.States.UIManageControls.CreateBindingGroup(), Terraria.GameContent.UI.States.UICharacterCreation.CreateColorPicker(), Terraria.GameContent.UI.States.UIManageControls.CreateElementGroup(), Terraria.GameContent.UI.States.UICharacterCreation.CreateHSLSlider(), Terraria.GameContent.UI.States.UICharacterCreation.CreatePickerWithoutClick(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.CreatePublicSettingsRow(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.CreateSteamDisclaimer(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.CreateTagOptionsPanel(), Terraria.GameContent.UI.Elements.UIList.DrawSelf(), Terraria.GameContent.UI.States.UITextWrappingTest.TestElement.DrawSelf(), Terraria.GameContent.UI.Elements.EmoteButton.EmoteButton(), Terraria.GameContent.UI.Elements.EmotesGroupListItem.EmotesGroupListItem(), Terraria.GameContent.UI.Elements.UIBestiaryEntryGrid.FillBestiarySpaceWithEntries(), Terraria.GameContent.UI.States.UIWorldGenDebug.GenPassElement.GenPassElement(), Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem.InitializeAppearance(), Terraria.GameContent.UI.Elements.UIWorkshopPublishResourcePackListItem.InitializeAppearance(), Terraria.GameContent.UI.Elements.UIWorkshopPublishWorldListItem.InitializeAppearance(), Terraria.GameContent.UI.Elements.UIWorldListItem.InitializeAppearance(), Terraria.GameContent.UI.States.UIAchievementsMenu.InitializePage(), Terraria.GameContent.UI.States.UIEmotesMenu.InitializePage(), Terraria.GameContent.UI.Elements.UIText.InternalSetText(), Terraria.GameContent.UI.States.UIWorkshopHub.MakeFancyButton(), Terraria.GameContent.UI.States.UIAchievementsMenu.OnActivate(), Terraria.GameContent.UI.States.UIEmotesMenu.OnActivate(), Terraria.GameContent.UI.States.UIManageControls.OnActivate(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.OnInitialize(), Terraria.GameContent.UI.States.UICharacterSelect.OnInitialize(), Terraria.GameContent.UI.States.UIManageControls.OnInitialize(), Terraria.GameContent.UI.States.UIWorkshopHub.OnInitialize(), Terraria.GameContent.UI.States.UIWorkshopSelectResourcePackToPublish.OnInitialize(), Terraria.GameContent.UI.States.UIWorkshopSelectWorldToPublish.OnInitialize(), Terraria.GameContent.UI.States.UIWorkshopWorldImport.OnInitialize(), Terraria.GameContent.UI.States.UIWorldSelect.OnInitialize(), Terraria.GameContent.UI.States.UICharacterSelect.Recalculate(), Terraria.GameContent.UI.States.UIEmotesMenu.Recalculate(), Terraria.GameContent.UI.States.UIReportsPage.Recalculate(), Terraria.GameContent.UI.States.UIResourcePackInfoMenu.Recalculate(), Terraria.GameContent.UI.States.UIWorkshopSelectResourcePackToPublish.Recalculate(), Terraria.GameContent.UI.States.UIWorkshopSelectWorldToPublish.Recalculate(), Terraria.GameContent.UI.States.UIWorkshopWorldImport.Recalculate(), Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.Recalculate(), Terraria.GameContent.UI.States.UIWorldSelect.Recalculate(), Terraria.GameContent.UI.Elements.UIImageWithBorder.SetBorder(), Terraria.GameContent.UI.Elements.UIImageWithBorder.SetBorder(), Terraria.GameContent.UI.Elements.UIImageFramed.SetFrame(), Terraria.GameContent.UI.Elements.UIColoredImageButton.SetImage(), Terraria.GameContent.UI.Elements.UIImage.SetImage(), Terraria.GameContent.UI.Elements.UIImageFramed.SetImage(), Terraria.GameContent.UI.Elements.UIImageButton.SetImage(), Terraria.GameContent.UI.Elements.UIImage.SetImage(), Terraria.GameContent.UI.Elements.UIIconTextButton.SetText(), Terraria.GameContent.UI.Elements.UIBestiaryInfoLine< T >.SetText(), Terraria.GameContent.UI.Elements.UITextPanel< T >.SetText(), Terraria.GameContent.UI.Elements.UIAchievementListItem.UIAchievementListItem(), Terraria.GameContent.UI.Elements.UIBestiaryEntryButton.UIBestiaryEntryButton(), Terraria.GameContent.UI.Elements.UIBestiaryEntryIcon.UIBestiaryEntryIcon(), Terraria.GameContent.UI.Elements.UIBestiaryEntryInfoPage.UIBestiaryEntryInfoPage(), Terraria.GameContent.UI.Elements.UIBestiaryInfoItemLine.UIBestiaryInfoItemLine(), Terraria.GameContent.UI.Elements.UIBestiaryNPCEntryPortrait.UIBestiaryNPCEntryPortrait(), Terraria.GameContent.UI.Elements.UICharacter.UICharacter(), Terraria.GameContent.UI.Elements.UICharacterListItem.UICharacterListItem(), Terraria.GameContent.UI.Elements.UIColoredImageButton.UIColoredImageButton(), Terraria.GameContent.UI.Elements.UICreativeItemsInfiniteFilteringOptions.UICreativeItemsInfiniteFilteringOptions(), Terraria.GameContent.UI.Elements.UIDebugCommandItem.UIDebugCommandItem(), Terraria.GameContent.UI.Elements.UIHorizontalSeparator.UIHorizontalSeparator(), Terraria.GameContent.UI.Elements.UIImageButton.UIImageButton(), Terraria.GameContent.UI.Elements.UIImageFramed.UIImageFramed(), Terraria.GameContent.UI.Elements.UIItemIcon.UIItemIcon(), Terraria.GameContent.UI.Elements.UIList.UIList(), Terraria.GameContent.UI.Elements.UIScrollbar.UIScrollbar(), Terraria.GameContent.UI.Elements.UISlicedImage.UISlicedImage(), Terraria.GameContent.UI.States.UITextWrappingTest.UITextWrappingTest(), Terraria.GameContent.UI.Elements.UIToggleImage.UIToggleImage(), Terraria.GameContent.UI.Elements.UIVerticalSeparator.UIVerticalSeparator(), Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem.UIWorkshopImportWorldListItem(), Terraria.GameContent.UI.Elements.UIWorkshopPublishWorldListItem.UIWorkshopPublishWorldListItem(), Terraria.GameContent.UI.Elements.UIWorldCreationPreview.UIWorldCreationPreview(), Terraria.GameContent.UI.Elements.UIWorldListItem.UIWorldListItem(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.UpdateScrollbar(), and Terraria.GameContent.UI.Elements.UIDynamicItemCollection< TEntry >.UpdateSize().