Terraria Decompiled: SDL2.SDL.SDL_OpenAudioDevice
SDL_OpenAudioDevice() [2/2]
static unsafe uint SDL2.SDL.SDL_OpenAudioDevice (string device, int iscapture, ref SDL::SDL_AudioSpec desired, out SDL::SDL_AudioSpec obtained, int allowed_changes) inline static
Definition at line 3360 of file SDL.cs.
        {
            int num = SDL.Utf8Size(device);
            byte* ptr = stackalloc byte[(UIntPtr)num];
            return SDL.INTERNAL_SDL_OpenAudioDevice(SDL.Utf8Encode(device, ptr, num), iscapture, ref desired, out obtained, allowed_changes);
        }
References SDL2.SDL.INTERNAL_SDL_OpenAudioDevice(), SDL2.SDL.Utf8Encode(), and SDL2.SDL.Utf8Size().