Terraria Decompiled: SDL2.SDL.Utf8Encode
Utf8Encode()
static unsafe byte * SDL2.SDL.Utf8Encode (string str, byte * buffer, int bufferSize) inline static package
Definition at line 40 of file SDL.cs.
        {
            if (str == null)
            {
                return null;
            }
            fixed (string text = str)
            {
                char* ptr = text;
                if (ptr != null)
                {
                    ptr += RuntimeHelpers.OffsetToStringData / 2;
                }
                Encoding.UTF8.GetBytes(ptr, str.Length + 1, buffer, bufferSize);
            }
            return buffer;
        }
References System.Text.Encoding.GetBytes(), System.text, and System.Text.Encoding.UTF8.
Referenced by SDL2.SDL.SDL_AudioInit(), SDL2.SDL.SDL_CreateWindow(), SDL2.SDL.SDL_GameControllerGetAxisFromString(), SDL2.SDL.SDL_GameControllerGetButtonFromString(), SDL2.SDL.SDL_GetHint(), SDL2.SDL.SDL_GetHintBoolean(), SDL2.SDL.SDL_GetKeyFromName(), SDL2.SDL.SDL_GetPrefPath(), SDL2.SDL.SDL_GetScancodeFromName(), SDL2.SDL.SDL_GetWindowData(), SDL2.SDL.SDL_GL_ExtensionSupported(), SDL2.SDL.SDL_GL_GetProcAddress(), SDL2.SDL.SDL_JoystickGetGUIDFromString(), SDL2.SDL.SDL_Log(), SDL2.SDL.SDL_LogCritical(), SDL2.SDL.SDL_LogDebug(), SDL2.SDL.SDL_LogError(), SDL2.SDL.SDL_LogInfo(), SDL2.SDL.SDL_LogMessage(), SDL2.SDL.SDL_LogMessageV(), SDL2.SDL.SDL_LogVerbose(), SDL2.SDL.SDL_LogWarn(), SDL2.SDL.SDL_OpenAudioDevice(), SDL2.SDL.SDL_SetError(), SDL2.SDL.SDL_SetHint(), SDL2.SDL.SDL_SetHintWithPriority(), SDL2.SDL.SDL_SetWindowData(), SDL2.SDL.SDL_SetWindowTitle(), SDL2.SDL.SDL_ShowSimpleMessageBox(), and SDL2.SDL.SDL_VideoInit().