Terraria Decompiled: SDL2.SDL.SDL_ShowMessageBox
SDL_ShowMessageBox()
static unsafe int SDL2.SDL.SDL_ShowMessageBox ([In] ref SDL::SDL_MessageBoxData messageboxdata, out int buttonid) inline static
Definition at line 550 of file SDL.cs.
        {
            SDL.INTERNAL_SDL_MessageBoxData internal_SDL_MessageBoxData = new SDL.INTERNAL_SDL_MessageBoxData
            {
                flags = messageboxdata.flags,
                window = messageboxdata.window,
                title = SDL.INTERNAL_AllocUTF8(messageboxdata.title),
                message = SDL.INTERNAL_AllocUTF8(messageboxdata.message),
                numbuttons = messageboxdata.numbuttons
            };
            SDL.INTERNAL_SDL_MessageBoxButtonData[] array = new SDL.INTERNAL_SDL_MessageBoxButtonData[messageboxdata.numbuttons];
            for (int i = 0; i < messageboxdata.numbuttons; i++)
            {
                array[i] = new SDL.INTERNAL_SDL_MessageBoxButtonData
                {
                    flags = messageboxdata.buttons[i].flags,
                    buttonid = messageboxdata.buttons[i].buttonid,
                    text = SDL.INTERNAL_AllocUTF8(messageboxdata.buttons[i].text)
                };
            }
            if (messageboxdata.colorScheme != null)
            {
                internal_SDL_MessageBoxData.colorScheme = Marshal.AllocHGlobal(SDL.SizeOf<SDL.SDL_MessageBoxColorScheme>());
                Marshal.StructureToPtr(messageboxdata.colorScheme.Value, internal_SDL_MessageBoxData.colorScheme, false);
            }
            int num;
            fixed (SDL.INTERNAL_SDL_MessageBoxButtonData* ptr = &array[0])
            {
                SDL.INTERNAL_SDL_MessageBoxButtonData* ptr2 = ptr;
                internal_SDL_MessageBoxData.buttons = (IntPtr)((void*)ptr2);
                num = SDL.INTERNAL_SDL_ShowMessageBox(ref internal_SDL_MessageBoxData, out buttonid);
            }
            Marshal.FreeHGlobal(internal_SDL_MessageBoxData.colorScheme);
            for (int j = 0; j < messageboxdata.numbuttons; j++)
            {
                SDL.SDL_free(array[j].text);
            }
            SDL.SDL_free(internal_SDL_MessageBoxData.message);
            SDL.SDL_free(internal_SDL_MessageBoxData.title);
            return num;
        }
References System.Runtime.InteropServices.Marshal.AllocHGlobal(), System.array, SDL2.SDL.INTERNAL_SDL_MessageBoxData.colorScheme, SDL2.SDL.INTERNAL_SDL_MessageBoxButtonData.flags, SDL2.SDL.INTERNAL_SDL_MessageBoxData.flags, System.Runtime.InteropServices.Marshal.FreeHGlobal(), SDL2.SDL.INTERNAL_AllocUTF8(), SDL2.SDL.INTERNAL_SDL_ShowMessageBox(), SDL2.SDL.INTERNAL_SDL_MessageBoxData.message, SDL2.SDL.SDL_free(), System.Runtime.InteropServices.Marshal.StructureToPtr(), System.text, and SDL2.SDL.INTERNAL_SDL_MessageBoxData.title.