Terraria Decompiled: SDL2.SDL.SDL_CreateShapedWindow
SDL_CreateShapedWindow()
static unsafe IntPtr SDL2.SDL.SDL_CreateShapedWindow (string title, uint x, uint y, uint w, uint h, SDL::SDL_WindowFlags flags) inline static
Definition at line 1856 of file SDL.cs.
        {
            byte* ptr = SDL.Utf8EncodeHeap(title);
            IntPtr intPtr = SDL.INTERNAL_SDL_CreateShapedWindow(ptr, x, y, w, h, flags);
            Marshal.FreeHGlobal((IntPtr)((void*)ptr));
            return intPtr;
        }
References System.Runtime.InteropServices.Marshal.FreeHGlobal(), SDL2.SDL.INTERNAL_SDL_CreateShapedWindow(), and SDL2.SDL.Utf8EncodeHeap().