Terraria Decompiled: SDL2.SDL.Utf8Size
Utf8Size()
static int SDL2.SDL.Utf8Size (string str) inline static package
Definition at line 30 of file SDL.cs.
        {
            if (str == null)
            {
                return 0;
            }
            return str.Length * 4 + 1;
        }
Referenced by SDL2.SDL.SDL_AudioInit(), SDL2.SDL.SDL_CreateWindow(), SDL2.SDL.SDL_GameControllerGetAxisFromString(), SDL2.SDL.SDL_GameControllerGetButtonFromString(), SDL2.SDL.SDL_GetHint(), SDL2.SDL.SDL_GetHintBoolean(), SDL2.SDL.SDL_GetKeyFromName(), SDL2.SDL.SDL_GetPrefPath(), SDL2.SDL.SDL_GetScancodeFromName(), SDL2.SDL.SDL_GetWindowData(), SDL2.SDL.SDL_GL_ExtensionSupported(), SDL2.SDL.SDL_GL_GetProcAddress(), SDL2.SDL.SDL_JoystickGetGUIDFromString(), SDL2.SDL.SDL_Log(), SDL2.SDL.SDL_LogCritical(), SDL2.SDL.SDL_LogDebug(), SDL2.SDL.SDL_LogError(), SDL2.SDL.SDL_LogInfo(), SDL2.SDL.SDL_LogMessage(), SDL2.SDL.SDL_LogMessageV(), SDL2.SDL.SDL_LogVerbose(), SDL2.SDL.SDL_LogWarn(), SDL2.SDL.SDL_OpenAudioDevice(), SDL2.SDL.SDL_SetError(), SDL2.SDL.SDL_SetHint(), SDL2.SDL.SDL_SetHintWithPriority(), SDL2.SDL.SDL_SetWindowData(), SDL2.SDL.SDL_SetWindowTitle(), SDL2.SDL.SDL_ShowSimpleMessageBox(), SDL2.SDL.SDL_VideoInit(), and SDL2.SDL.Utf8EncodeHeap().