Terraria Decompiled: SDL2.SDL.INTERNAL_AllocUTF8
INTERNAL_AllocUTF8()
static IntPtr SDL2.SDL.INTERNAL_AllocUTF8 (string str) inline static private
Definition at line 537 of file SDL.cs.
        {
            if (string.IsNullOrEmpty(str))
            {
                return IntPtr.Zero;
            }
            byte[] bytes = Encoding.UTF8.GetBytes(str + "\0");
            IntPtr intPtr = SDL.SDL_malloc((IntPtr)bytes.Length);
            Marshal.Copy(bytes, 0, intPtr, bytes.Length);
            return intPtr;
        }
References System.Runtime.InteropServices.Marshal.Copy(), System.Text.Encoding.GetBytes(), SDL2.SDL.SDL_malloc(), System.Text.Encoding.UTF8, and System.IntPtr.Zero.
Referenced by SDL2.SDL.SDL_ShowMessageBox().