Terraria Decompiled: SDL2.SDL.UTF8_ToManaged
UTF8_ToManaged()
static unsafe string SDL2.SDL.UTF8_ToManaged (IntPtr s, bool freePtr = false) inline static
Definition at line 80 of file SDL.cs.
        {
            if (s == IntPtr.Zero)
            {
                return null;
            }
            byte* ptr = (byte*)(void*)s;
            while (*ptr != 0)
            {
                ptr++;
            }
            int num = (int)((long)((byte*)ptr - (byte*)(void*)s));
            if (num == 0)
            {
                return string.Empty;
            }
            checked
            {
                char* ptr2 = stackalloc char[unchecked((UIntPtr)num) * 2];
                int chars = Encoding.UTF8.GetChars((byte*)(void*)s, num, ptr2, num);
                string text = new string(ptr2, 0, chars);
                if (freePtr)
                {
                    SDL.SDL_free(s);
                }
                return text;
            }
        }
References System.Text.Encoding.GetChars(), int, System.s, SDL2.SDL.SDL_free(), System.text, System.Text.Encoding.UTF8, and System.IntPtr.Zero.
Referenced by SDL2.SDL.SDL_AndroidGetExternalStoragePath(), SDL2.SDL.SDL_AndroidGetInternalStoragePath(), SDL2.SDL.SDL_GameControllerGetAppleSFSymbolsNameForAxis(), SDL2.SDL.SDL_GameControllerGetAppleSFSymbolsNameForButton(), SDL2.SDL.SDL_GameControllerGetSerial(), SDL2.SDL.SDL_GameControllerGetStringForAxis(), SDL2.SDL.SDL_GameControllerGetStringForButton(), SDL2.SDL.SDL_GameControllerMapping(), SDL2.SDL.SDL_GameControllerMappingForDeviceIndex(), SDL2.SDL.SDL_GameControllerMappingForGUID(), SDL2.SDL.SDL_GameControllerMappingForIndex(), SDL2.SDL.SDL_GameControllerName(), SDL2.SDL.SDL_GameControllerNameForIndex(), SDL2.SDL.SDL_GetAudioDeviceName(), SDL2.SDL.SDL_GetAudioDriver(), SDL2.SDL.SDL_GetBasePath(), SDL2.SDL.SDL_GetClipboardText(), SDL2.SDL.SDL_GetCurrentAudioDriver(), SDL2.SDL.SDL_GetCurrentVideoDriver(), SDL2.SDL.SDL_GetDisplayName(), SDL2.SDL.SDL_GetError(), SDL2.SDL.SDL_GetHint(), SDL2.SDL.SDL_GetKeyName(), SDL2.SDL.SDL_GetPixelFormatName(), SDL2.SDL.SDL_GetPlatform(), SDL2.SDL.SDL_GetPrefPath(), SDL2.SDL.SDL_GetRevision(), SDL2.SDL.SDL_GetScancodeName(), SDL2.SDL.SDL_GetTouchName(), SDL2.SDL.SDL_GetVideoDriver(), SDL2.SDL.SDL_GetWindowTitle(), SDL2.SDL.SDL_HapticName(), SDL2.SDL.SDL_JoystickGetSerial(), SDL2.SDL.SDL_JoystickName(), SDL2.SDL.SDL_JoystickNameForIndex(), SDL2.SDL.SDL_SensorGetDeviceName(), and SDL2.SDL.SDL_SensorGetName().