Terraria Decompiled: SDL2.SDL.SDL_SetHint
SDL_SetHint()
static unsafe SDL.SDL_bool SDL2.SDL.SDL_SetHint (string name, string value) inline static
Definition at line 322 of file SDL.cs.
        {
            int num = SDL.Utf8Size(name);
            byte* ptr = stackalloc byte[(UIntPtr)num];
            int num2 = SDL.Utf8Size(value);
            byte* ptr2 = stackalloc byte[(UIntPtr)num2];
            return SDL.INTERNAL_SDL_SetHint(SDL.Utf8Encode(name, ptr, num), SDL.Utf8Encode(value, ptr2, num2));
        }
References SDL2.SDL.INTERNAL_SDL_SetHint(), System.name, SDL2.SDL.Utf8Encode(), SDL2.SDL.Utf8Size(), and System.value.
Referenced by Microsoft.Xna.Framework.SDL2_FNAPlatform.CreateWindow(), and Microsoft.Xna.Framework.SDL2_FNAPlatform.ProgramInit().