Terraria Decompiled: XPT.Core.Audio.MP3Sharp.Decoding.Decoder.RetrieveDecoder
RetrieveDecoder()
virtual IFrameDecoder XPT.Core.Audio.MP3Sharp.Decoding.Decoder.RetrieveDecoder (Header header, Bitstream stream, int layer) inline protected virtual
Definition at line 137 of file Decoder.cs.
        {
            IFrameDecoder frameDecoder = null;
            switch (layer)
            {
            case 1:
                if (this._L1Decoder == null)
                {
                    this._L1Decoder = new LayerIDecoder();
                    this._L1Decoder.Create(stream, header, this._LeftChannelFilter, this._RightChannelFilter, this._Output, 0);
                }
                frameDecoder = this._L1Decoder;
                break;
            case 2:
                if (this._L2Decoder == null)
                {
                    this._L2Decoder = new LayerIIDecoder();
                    this._L2Decoder.Create(stream, header, this._LeftChannelFilter, this._RightChannelFilter, this._Output, 0);
                }
                frameDecoder = this._L2Decoder;
                break;
            case 3:
                if (this._L3Decoder == null)
                {
                    this._L3Decoder = new LayerIIIDecoder(stream, header, this._LeftChannelFilter, this._RightChannelFilter, this._Output, 0);
                }
                frameDecoder = this._L3Decoder;
                break;
            }
            if (frameDecoder == null)
            {
                throw this.NewDecoderException(513, null);
            }
            return frameDecoder;
        }
References XPT.Core.Audio.MP3Sharp.Decoding.Decoder._L1Decoder, XPT.Core.Audio.MP3Sharp.Decoding.Decoder._L2Decoder, XPT.Core.Audio.MP3Sharp.Decoding.Decoder._L3Decoder, XPT.Core.Audio.MP3Sharp.Decoding.Decoder._LeftChannelFilter, XPT.Core.Audio.MP3Sharp.Decoding.Decoder._Output, XPT.Core.Audio.MP3Sharp.Decoding.Decoder._RightChannelFilter, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIDecoder.Create(), and XPT.Core.Audio.MP3Sharp.Decoding.Decoder.NewDecoderException().
Referenced by XPT.Core.Audio.MP3Sharp.Decoding.Decoder.DecodeFrame().