Terraria Decompiled: XPT.Core.Audio.MP3Sharp.Decoding.Decoder.DecodeFrame
DecodeFrame()
virtual ABuffer XPT.Core.Audio.MP3Sharp.Decoding.Decoder.DecodeFrame (Header header, Bitstream stream) inline package virtual
Definition at line 111 of file Decoder.cs.
        {
            if (!this._IsInitialized)
            {
                this.Initialize(header);
            }
            int num = header.Layer();
            this._Output.ClearBuffer();
            this.RetrieveDecoder(header, stream, num).DecodeFrame();
            this._Output.WriteBuffer(1);
            return this._Output;
        }
References XPT.Core.Audio.MP3Sharp.Decoding.Decoder._IsInitialized, XPT.Core.Audio.MP3Sharp.Decoding.Decoder._Output, XPT.Core.Audio.MP3Sharp.Decoding.ABuffer.ClearBuffer(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.IFrameDecoder.DecodeFrame(), XPT.Core.Audio.MP3Sharp.Decoding.Decoder.Initialize(), XPT.Core.Audio.MP3Sharp.Decoding.Header.Layer(), XPT.Core.Audio.MP3Sharp.Decoding.Decoder.RetrieveDecoder(), and XPT.Core.Audio.MP3Sharp.Decoding.ABuffer.WriteBuffer().
Referenced by XPT.Core.Audio.MP3Sharp.MP3Stream.ReadFrame().