Terraria Decompiled: Terraria.GameContent.ObjectInteractions.SmartInteractSystem.RunQuery
RunQuery()
void Terraria.GameContent.ObjectInteractions.SmartInteractSystem.RunQuery (SmartInteractScanSettings settings) inline
Definition at line 30 of file SmartInteractSystem.cs.
        {
            this.Clear();
            using (List<ISmartInteractBlockReasonProvider>.Enumerator enumerator = this._blockProviders.GetEnumerator())
            {
                while (enumerator.MoveNext())
                {
                    if (enumerator.Current.ShouldBlockSmartInteract(settings))
                    {
                        return;
                    }
                }
            }
            using (List<ISmartInteractCandidateProvider>.Enumerator enumerator2 = this._candidateProvidersByOrderOfPriority.GetEnumerator())
            {
                while (enumerator2.MoveNext())
                {
                    ISmartInteractCandidate smartInteractCandidate;
                    if (enumerator2.Current.ProvideCandidate(settings, out smartInteractCandidate))
                    {
                        this._candidates.Add(smartInteractCandidate);
                        if (smartInteractCandidate.DistanceFromCursor == 0f)
{
                            break;
                        }
                    }
                }
            }
            ISmartInteractCandidate smartInteractCandidate2 = null;
            foreach (ISmartInteractCandidate smartInteractCandidate3 in this._candidates)
            {
                if (smartInteractCandidate2 == null || smartInteractCandidate2.DistanceFromCursor > smartInteractCandidate3.DistanceFromCursor)
                {
                    smartInteractCandidate2 = smartInteractCandidate3;
                }
            }
            if (smartInteractCandidate2 == null)
            {
                return;
            }
            smartInteractCandidate2.WinCandidacy();
        }
References Terraria.GameContent.ObjectInteractions.SmartInteractSystem._blockProviders, Terraria.GameContent.ObjectInteractions.SmartInteractSystem._candidateProvidersByOrderOfPriority, Terraria.GameContent.ObjectInteractions.SmartInteractSystem._candidates, Terraria.GameContent.ObjectInteractions.SmartInteractSystem.Clear(), Terraria.GameContent.ObjectInteractions.ISmartInteractCandidate.DistanceFromCursor, and Terraria.GameContent.ObjectInteractions.ISmartInteractCandidate.WinCandidacy().
Referenced by Terraria.Player.SmartInteractLookup().