Terraria Decompiled: Terraria.GameContent.Animations.Segments.NPCSegment.Draw
Draw()
override void Terraria.GameContent.Animations.Segments.NPCSegment.Draw (ref GameAnimationSegment info) inline
Definition at line 320 of file Segments.cs.
            {
                if ((float)info.TimeInAnimation > (float)this._targetTime + base.DedicatedTimeNeeded)
                {
                    return;
                }
                if (info.TimeInAnimation < this._targetTime)
                {
                    return;
                }
                this.ResetNPCAnimation(ref info);
                float num = (float)(info.TimeInAnimation - this._targetTime);
                base.ProcessActions(this._npc, num);
                if (this._npc.alpha >= 255)
                {
                    return;
                }
                this._npc.FindFrame();
                ITownNPCProfile townNPCProfile;
                if (TownNPCProfiles.Instance.GetProfile(this._npc.type, out townNPCProfile))
                {
                    TextureAssets.Npc[this._npc.type] = townNPCProfile.GetTextureNPCShouldUse(this._npc);
                }
                this._npc.Opacity *= info.DisplayOpacity;
                Main.instance.DrawNPCDirect(info.SpriteBatch, this._npc, this._npc.behindTiles, Vector2.Zero);
            }
References Terraria.GameContent.Animations.Segments.NPCSegment._npc, Terraria.NPC.alpha, Terraria.Main.DrawNPCDirect(), Terraria.NPC.FindFrame(), Terraria.GameContent.TownNPCProfiles.GetProfile(), Terraria.GameContent.ITownNPCProfile.GetTextureNPCShouldUse(), System.info, Terraria.GameContent.TownNPCProfiles.Instance, Terraria.Main.instance, Terraria.GameContent.TextureAssets.Npc, Terraria.GameContent.Animations.Segments.NPCSegment.ResetNPCAnimation(), Terraria.NPC.type, and Microsoft.Xna.Framework.Vector2.Zero.