Terraria Decompiled: Terraria.Program.ForceJITOnAssembly
ForceJITOnAssembly()
static void Terraria.Program.ForceJITOnAssembly (Assembly assembly) inline static private
Definition at line 59 of file Program.cs.
        {
            foreach (Type type in assembly.GetTypes())
            {
                foreach (MethodInfo methodInfo in Program.IsMono ? type.GetMethods() : type.GetMethods(BindingFlags.DeclaredOnly | BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic))
                {
                    if (!methodInfo.IsAbstract && !methodInfo.ContainsGenericParameters && methodInfo.GetMethodBody() != null)
                    {
                        if (Program.IsMono)
{
                            Program.JitForcedMethodCache = methodInfo.MethodHandle.GetFunctionPointer();
                        }
                        else
{
                            RuntimeHelpers.PrepareMethod(methodInfo.MethodHandle);
                        }
                    }
                }
                Program.ThingsLoaded++;
            }
        }
References System.Reflection.MethodBase.ContainsGenericParameters, System.RuntimeMethodHandle.GetFunctionPointer(), System.Reflection.MethodBase.GetMethodBody(), System.Type.GetMethods(), System.Reflection.MethodBase.IsAbstract, Terraria.Program.IsMono, System.Reflection.MethodBase.MethodHandle, System.Runtime.CompilerServices.RuntimeHelpers.PrepareMethod(), and Terraria.Program.ThingsLoaded.
Referenced by Terraria.Program.ForceLoadAssembly().