Terraria Decompiled: System.Collections.DictionaryBase.Add
Add()
void IDictionary. System.Collections.DictionaryBase.Add (object key, object value) inline private
Implements System.Collections.IDictionary.
Definition at line 159 of file DictionaryBase.cs.
        {
            this.OnValidate(key, value);
            this.OnInsert(key, value);
            this.InnerHashtable.Add(key, value);
            try
            {
                this.OnInsertComplete(key, value);
            }
            catch
            {
                this.InnerHashtable.Remove(key);
                throw;
            }
        }
References System.Collections.Hashtable.Add(), System.Collections.DictionaryBase.InnerHashtable, System.Collections.DictionaryBase.OnInsert(), System.Collections.DictionaryBase.OnInsertComplete(), System.Collections.DictionaryBase.OnValidate(), System.Collections.Hashtable.Remove(), and System.value.