Terraria Decompiled: Terraria.Program.LogFNANativeLibVersions
LogFNANativeLibVersions()
static void Terraria.Program.LogFNANativeLibVersions () inline static private
Definition at line 244 of file Program.cs.
        {
            Console.WriteLine(string.Concat(new object[]
            {
                "SDL v",
                SDL.SDL_GetVersion(),
                ".",
                SDL.SDL_GetRevision()
            }) ?? "");
            uint num = FNA3D.FNA3D_LinkedVersion();
            Console.WriteLine(string.Concat(new object[]
            {
                "FNA3D v",
                num / 10000U,
                ".",
                num / 100U % 100U,
                ".",
                num % 100U
            }) ?? "");
            uint num2 = FAudio.FAudioLinkedVersion();
            Console.WriteLine(string.Concat(new object[]
            {
                "FAudio v",
                num2 / 10000U,
                ".",
                num2 / 100U % 100U,
                ".",
                num2 % 100U
            }) ?? "");
        }
References FAudio.FAudioLinkedVersion(), Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_LinkedVersion(), SDL3.SDL.SDL_GetRevision(), SDL3.SDL.SDL_GetVersion(), System.U, and System.Console.WriteLine().
Referenced by Terraria.Program.LaunchGame().