Terraria Decompiled: Terraria.Program.LaunchGame
LaunchGame()
static void Terraria.Program.LaunchGame (string[] args, bool monoArgs = false) inline static
Definition at line 176 of file Program.cs.
        {
            Thread.CurrentThread.Name = "Main Thread";
            if (monoArgs)
            {
                args = Utils.ConvertMonoArgsToDotNet(args);
            }
            Program.LogFNANativeLibVersions();
            Program.LaunchParameters = Utils.ParseArguements(args);
            Program.SavePath = (Program.LaunchParameters.ContainsKey("-savedirectory") ? Program.LaunchParameters["-savedirectory"] : Platform.Get<IPathService>().GetStoragePath("Terraria"));
            ThreadPool.SetMinThreads(8, 8);
            Program.InitializeConsoleOutput();
            Program.SetupLogging();
            Platform.Get<IWindowService>().SetQuickEditEnabled(false);
            Program.RunGame();
        }
References System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), Terraria.Utils.ConvertMonoArgsToDotNet(), Terraria.Program.InitializeConsoleOutput(), Terraria.Program.LaunchParameters, Terraria.Program.LogFNANativeLibVersions(), Terraria.Utils.ParseArguements(), Terraria.Program.RunGame(), System.Threading.ThreadPool.SetMinThreads(), and Terraria.Program.SetupLogging().
Referenced by Terraria.LinuxLaunch.Main().