Terraria Decompiled: Terraria.GameContent.Bestiary.SortingSteps.ByStat.Compare
Compare() [1/2]
int Terraria.GameContent.Bestiary.SortingSteps.ByStat.Compare (BestiaryEntry x, BestiaryEntry y) inline
Definition at line 398 of file SortingSteps.cs.
            {
                NPCStatsReportInfoElement npcstatsReportInfoElement = x.Info.FirstOrDefault((IBestiaryInfoElement element) => this.IsAStatsCardINeed(element)) as NPCStatsReportInfoElement;
                NPCStatsReportInfoElement npcstatsReportInfoElement2 = y.Info.FirstOrDefault((IBestiaryInfoElement element) => this.IsAStatsCardINeed(element)) as NPCStatsReportInfoElement;
                if (npcstatsReportInfoElement == null && npcstatsReportInfoElement2 != null)
                {
                    return 1;
                }
                if (npcstatsReportInfoElement2 == null && npcstatsReportInfoElement != null)
                {
                    return -1;
                }
                if (npcstatsReportInfoElement == null || npcstatsReportInfoElement2 == null)
                {
                    return 0;
                }
                return this.Compare(npcstatsReportInfoElement, npcstatsReportInfoElement2);
            }
References Terraria.GameContent.Bestiary.SortingSteps.ByStat.Compare(), Terraria.GameContent.Bestiary.BestiaryEntry.Info, and Terraria.GameContent.Bestiary.SortingSteps.ByStat.IsAStatsCardINeed().
Referenced by Terraria.GameContent.Bestiary.SortingSteps.ByStat.Compare().