Terraria Decompiled: System.Text.StringBuilderCache.Acquire
Acquire()
static StringBuilder System.Text.StringBuilderCache.Acquire (int capacity = 16) inline static
Definition at line 9 of file StringBuilderCache.cs.
        {
            if (capacity <= 360)
            {
                StringBuilder stringBuilder = StringBuilderCache.t_cachedInstance;
                if (stringBuilder != null && capacity <= stringBuilder.Capacity)
                {
                    StringBuilderCache.t_cachedInstance = null;
                    stringBuilder.Clear();
                    return stringBuilder;
                }
            }
            return new StringBuilder(capacity);
        }
References System.capacity, System.Text.StringBuilder.Capacity, System.Text.StringBuilder.Clear(), and System.Text.StringBuilderCache.t_cachedInstance.
Referenced by Interop.CallStringMethod< TArg1, TArg2, TArg3 >(), System.String.Concat(), System.String.Concat< T >(), System.DateTimeFormat.FormatCustomized(), System.Globalization.TimeSpanFormat.FormatCustomized(), System.String.FormatHelper(), System.Globalization.TimeSpanFormat.FormatStandard(), System.TimeZoneInfo.StringSerializer.GetNextStringValue(), System.IO.Path.GetRelativePath(), System.TimeZoneInfo.StringSerializer.GetSerializedString(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.IndexTraceMessage(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.IndexTraceMessage(), System.Globalization.TimeSpanFormat.FormatLiterals.Init(), System.String.Join(), System.String.JoinCore(), System.String.JoinCore< T >(), System.Collections.Generic.KeyValuePair< TKey, TValue >.PairToString(), System.DateTimeParse.ParseByFormat(), System.IO.BinaryReader.ReadString(), System.String.ReplaceCore(), System.Version.ToCachedStringBuilder(), System.ApplicationId.ToString(), and System.Globalization.TimeSpanParse.TryParseByFormat().