Terraria Decompiled: Terraria.GameContent.Creative.CreativePowers.APerPlayerTogglePower.SetEnabledState
SetEnabledState()
void Terraria.GameContent.Creative.CreativePowers.APerPlayerTogglePower.SetEnabledState (int playerIndex, bool state) inline
Definition at line 157 of file CreativePowers.cs.
            {
                this._perPlayerIsEnabled[playerIndex] = state;
                if (Main.netMode == 2)
                {
                    NetPacket netPacket = NetCreativePowersModule.PreparePacket(this.PowerId, 3);
                    netPacket.Writer.Write(1);
                    netPacket.Writer.Write((byte)playerIndex);
                    netPacket.Writer.Write(state);
                    NetManager.Instance.Broadcast(netPacket, -1);
                }
            }
References Terraria.GameContent.Creative.CreativePowers.APerPlayerTogglePower._perPlayerIsEnabled, Terraria.Net.NetManager.Broadcast(), Terraria.Net.NetManager.Instance, Terraria.Main.netMode, Terraria.GameContent.Creative.CreativePowers.APerPlayerTogglePower.PowerId, Terraria.GameContent.NetModules.NetCreativePowersModule.PreparePacket(), System.state, System.IO.BinaryWriter.Write(), and Terraria.Net.NetPacket.Writer.
Referenced by Terraria.GameContent.Creative.CreativePowers.APerPlayerTogglePower.Deserialize_SyncEveryone(), and Terraria.GameContent.Creative.CreativePowers.APerPlayerTogglePower.DeserializeNetMessage().