Terraria Decompiled: Terraria.Utilities.FileUtilities.Write
Write()
static bool Terraria.Utilities.FileUtilities.Write (string path, byte[] data, int length, bool cloud) inline static
Definition at line 144 of file FileUtilities.cs.
        {
            if (cloud)
            {
                return SocialAPI.Cloud != null && SocialAPI.Cloud.Write(path, data, length);
            }
            string parentFolderPath = FileUtilities.GetParentFolderPath(path, true);
            if (parentFolderPath != "")
            {
                Utils.TryCreatingDirectory(parentFolderPath);
            }
            FileUtilities.RemoveReadOnlyAttribute(path);
            using (FileStream fileStream = File.Open(path, FileMode.Create))
            {
                while (fileStream.Position < (long)length)
                {
                    fileStream.Write(data, (int)fileStream.Position, Math.Min(length - (int)fileStream.Position, 2048));
                }
            }
            return true;
        }
References Terraria.Social.SocialAPI.Cloud, Terraria.Utilities.FileUtilities.GetParentFolderPath(), System.length, System.Math.Min(), System.IO.File.Open(), System.IO.FileStream.Position, Terraria.Utilities.FileUtilities.RemoveReadOnlyAttribute(), Terraria.Utils.TryCreatingDirectory(), and System.IO.FileStream.Write().
Referenced by Terraria.IO.WorldFile.InternalSaveWorld(), and Terraria.Utilities.FileUtilities.WriteAllBytes().