Terraria Decompiled: Terraria.Utilities.FileUtilities.Move
Move()
static void Terraria.Utilities.FileUtilities.Move (string source, string destination, bool cloud) inline static
Definition at line 82 of file FileUtilities.cs.
        {
            if (!cloud)
            {
                try
                {
                    if (File.Exists(destination))
                    {
                        File.Delete(destination);
                    }
                    File.Move(source, destination);
                    return;
                }
                catch (IOException)
                {
                }
            }
            FileUtilities.Copy(source, destination, cloud);
            FileUtilities.Delete(source, cloud, true);
        }
References Terraria.Utilities.FileUtilities.Copy(), System.IO.File.Delete(), Terraria.Utilities.FileUtilities.Delete(), System.destination, System.IO.File.Exists(), System.IO.File.Move(), and System.source.
Referenced by Terraria.IO.WorldFile.DoRollingBackups(), Terraria.Main.DrawMenu(), and Terraria.Player.GetFileData().