Terraria Decompiled: Terraria.Utilities.FileUtilities.Copy
Copy()
static void Terraria.Utilities.FileUtilities.Copy (string source, string destination, bool cloud) inline static
Definition at line 50 of file FileUtilities.cs.
        {
            if (!cloud)
            {
                try
                {
                    File.Copy(source, destination, true);
                }
                catch (IOException ex)
                {
                    if (ex.GetType() != typeof(IOException))
                    {
                        throw;
                    }
                    using (FileStream fileStream = File.OpenRead(source))
                    {
                        using (FileStream fileStream2 = File.Create(destination))
{
                            fileStream.CopyTo(fileStream2);
                        }
                    }
                }
                return;
            }
            if (SocialAPI.Cloud == null)
            {
                return;
            }
            SocialAPI.Cloud.Write(destination, SocialAPI.Cloud.Read(source));
        }
References Terraria.Social.SocialAPI.Cloud, System.IO.File.Copy(), System.IO.Stream.CopyTo(), System.IO.File.Create(), System.destination, System.Exception.GetType(), System.IO.File.OpenRead(), and System.source.
Referenced by Terraria.IO.WorldFileData.CopyToLocal(), Terraria.Player.InternalSavePlayerFile(), Terraria.Utilities.FileUtilities.Move(), Terraria.WorldGen.playWorldCallBack(), Terraria.Social.Steam.WorkshopHelper.UGCBased.WorldPublisherInstance.PrepareContentForUpdate(), and Terraria.WorldGen.serverLoadWorldCallBack().