Terraria Decompiled: System.IO.Stream.d__28.MoveNext
MoveNext()
void IAsyncStateMachine. System.IO.Stream.d__28.MoveNext () inline
Implements System.Runtime.CompilerServices.IAsyncStateMachine.
Definition at line 1680 of file Stream.cs.
            {
                int num2;
                int num = num2;
                Stream stream = this;
                try
                {
                    if (num > 1)
                    {
                        buffer = ArrayPool<byte>.Shared.Rent(bufferSize);
                    }
                    try
                    {
                        ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter;
                        if (num == 0)
{
                            ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter2;
                            configuredValueTaskAwaiter = configuredValueTaskAwaiter2;
                            configuredValueTaskAwaiter2 = default(ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter);
                            num = (num2 = -1);
                            goto IL_00A6;
                        }
                        ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter3;
                        if (num == 1)
{
                            ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter4;
                            configuredValueTaskAwaiter3 = configuredValueTaskAwaiter4;
                            configuredValueTaskAwaiter4 = default(ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter);
                            num = (num2 = -1);
                            goto IL_012E;
                        }
                        IL_0033:
                        configuredValueTaskAwaiter = stream.ReadAsync(new Memory<byte>(buffer), cancellationToken).ConfigureAwait(false).GetAwaiter();
                        if (!configuredValueTaskAwaiter.IsCompleted)
{
                            num = (num2 = 0);
                            ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter2 = configuredValueTaskAwaiter;
                            this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter, Stream.<CopyToAsyncInternal>d__28>(ref configuredValueTaskAwaiter, ref this);
                            return;
                        }
                        IL_00A6:
                        int result = configuredValueTaskAwaiter.GetResult();
                        if (result == 0)
{
                            goto IL_0152;
                        }
                        configuredValueTaskAwaiter3 = destination.WriteAsync(new ReadOnlyMemory<byte>(buffer, 0, result), cancellationToken).ConfigureAwait(false).GetAwaiter();
                        if (!configuredValueTaskAwaiter3.IsCompleted)
{
                            num = (num2 = 1);
                            ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter4 = configuredValueTaskAwaiter3;
                            this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter, Stream.<CopyToAsyncInternal>d__28>(ref configuredValueTaskAwaiter3, ref this);
                            return;
                        }
                        IL_012E:
                        configuredValueTaskAwaiter3.GetResult();
                        goto IL_0033;
                    }
                    finally
                    {
                        if (num < 0)
{
                            ArrayPool<byte>.Shared.Return(buffer, false);
                        }
                    }
                    IL_0152:;
                }
                catch (Exception ex)
                {
                    num2 = -2;
                    buffer = null;
                    this.<>t__builder.SetException(ex);
                    return;
                }
                num2 = -2;
                buffer = null;
                this.<>t__builder.SetResult();
            }
References System.IO.Stream.CopyToAsyncInternal(), System.destination, System.Threading.Tasks.Task< TResult >.GetAwaiter(), System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable< TResult >.ConfiguredValueTaskAwaiter.GetResult(), System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable< TResult >.ConfiguredValueTaskAwaiter.IsCompleted, System.IO.Stream.ReadAsync(), and System.Buffers.ArrayPool< T >.Shared.