Terraria Decompiled: System.Threading.Tasks.ForceAsyncAwaiter.GetResult
GetResult()
void System.Threading.Tasks.ForceAsyncAwaiter.GetResult () inline
Definition at line 32 of file ForceAsyncAwaiter.cs.
        {
            this._task.GetAwaiter().GetResult();
        }
References System.Threading.Tasks.ForceAsyncAwaiter._task, System.Threading.Tasks.Task< TResult >.GetAwaiter(), and System.Runtime.CompilerServices.TaskAwaiter< TResult >.GetResult().
Referenced by System.Security.Cryptography.CryptoStream.d__37.MoveNext(), and System.Security.Cryptography.CryptoStream.d__46.MoveNext().