Terraria Decompiled: Terraria.GameContent.ItemDropRules.FromOptionsWithoutRepeatsDropRule.TryDroppingItem
TryDroppingItem()
ItemDropAttemptResult Terraria.GameContent.ItemDropRules.FromOptionsWithoutRepeatsDropRule.TryDroppingItem (DropAttemptInfo info) inline
Implements Terraria.GameContent.ItemDropRules.IItemDropRule.
Definition at line 42 of file FromOptionsWithoutRepeatsDropRule.cs.
        {
            this._temporaryAvailableItems.Clear();
            this._temporaryAvailableItems.AddRange(this.dropIds);
            int num = 0;
            while (num < this.dropCount && this._temporaryAvailableItems.Count > 0)
            {
                int num2 = info.rng.Next(this._temporaryAvailableItems.Count);
                CommonCode.DropItemFromNPC(info.npc, this._temporaryAvailableItems[num2], 1, false);
                this._temporaryAvailableItems.RemoveAt(num2);
                num++;
            }
            return new ItemDropAttemptResult
            {
                State = ItemDropAttemptResultState.Success
            };
        }
References Terraria.GameContent.ItemDropRules.FromOptionsWithoutRepeatsDropRule._temporaryAvailableItems, System.Collections.Generic.List< T >.AddRange(), System.Collections.Generic.List< T >.Clear(), System.Collections.Generic.List< T >.Count, Terraria.GameContent.ItemDropRules.FromOptionsWithoutRepeatsDropRule.dropIds, Terraria.GameContent.ItemDropRules.CommonCode.DropItemFromNPC(), System.info, and System.Collections.Generic.List< T >.RemoveAt().