Terraria Decompiled: System.Globalization.HebrewNumber.ToString
ToString()
static string System.Globalization.HebrewNumber.ToString (int Number) inline static package
Definition at line 15 of file HebrewNumber.cs.
        {
            char c = '\0';
            StringBuilder stringBuilder = new StringBuilder();
            if (Number > 5000)
            {
                Number -= 5000;
            }
            int num = Number / 100;
            if (num > 0)
            {
                Number -= num * 100;
                for (int i = 0; i < num / 4; i++)
                {
                    stringBuilder.Append('ת');
                }
                int num2 = num % 4;
                if (num2 > 0)
                {
                    stringBuilder.Append((char)(1510 + num2));
                }
            }
            int num3 = Number / 10;
            Number %= 10;
            switch (num3)
            {
            case 0:
                c = '\0';
                break;
            case 1:
                c = 'י';
                break;
            case 2:
                c = 'כ';
                break;
            case 3:
                c = 'ל';
                break;
            case 4:
                c = 'מ';
                break;
            case 5:
                c = 'נ';
                break;
            case 6:
                c = 'ס';
                break;
            case 7:
                c = 'ע';
                break;
            case 8:
                c = 'פ';
                break;
            case 9:
                c = 'צ';
                break;
            }
            char c2 = (char)((Number > 0) ? (1488 + Number - 1) : 0);
            if (c2 == 'ה' && c == 'י')
            {
                c2 = 'ו';
                c = 'ט';
            }
            if (c2 == 'ו' && c == 'י')
            {
                c2 = 'ז';
                c = 'ט';
            }
            if (c != '\0')
            {
                stringBuilder.Append(c);
            }
            if (c2 != '\0')
            {
                stringBuilder.Append(c2);
            }
            if (stringBuilder.Length > 1)
            {
                stringBuilder.Insert(stringBuilder.Length - 1, '"');
            }
            else
            {
                stringBuilder.Append('\'');
            }
            return stringBuilder.ToString();
        }
References System.Text.StringBuilder.Append(), System.Text.StringBuilder.Insert(), System.Text.StringBuilder.Length, and System.Text.StringBuilder.ToString().
Referenced by System.DateTimeFormat.HebrewFormatDigits().