Terraria Decompiled: System.IO.StreamWriter.d__74.MoveNext
MoveNext()
void IAsyncStateMachine. System.IO.StreamWriter.d__74.MoveNext () inline
Implements System.Runtime.CompilerServices.IAsyncStateMachine.
Definition at line 1554 of file StreamWriter.cs.
            {
                int num2;
                int num = num2;
                try
                {
                    ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter;
                    ConfiguredTaskAwaitable.ConfiguredTaskAwaiter configuredTaskAwaiter;
                    switch (num)
                    {
                    case 0:
                    {
                        ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter2;
                        configuredValueTaskAwaiter = configuredValueTaskAwaiter2;
                        configuredValueTaskAwaiter2 = default(ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter);
                        num2 = -1;
                        break;
                    }
                    case 1:
                    {
                        ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter2;
                        configuredValueTaskAwaiter = configuredValueTaskAwaiter2;
                        configuredValueTaskAwaiter2 = default(ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter);
                        num2 = -1;
                        goto IL_0161;
                    }
                    case 2:
                    {
                        ConfiguredTaskAwaitable.ConfiguredTaskAwaiter configuredTaskAwaiter2;
                        configuredTaskAwaiter = configuredTaskAwaiter2;
                        configuredTaskAwaiter2 = default(ConfiguredTaskAwaitable.ConfiguredTaskAwaiter);
                        num2 = -1;
                        goto IL_01D9;
                    }
                    default:
                    {
                        if (haveWrittenPreamble)
{
                            goto IL_00BA;
                        }
                        _this.HaveWrittenPreamble_Prop = true;
                        byte[] preamble = encoding.GetPreamble();
                        if (preamble.Length == 0)
{
                            goto IL_00BA;
                        }
                        configuredValueTaskAwaiter = stream.WriteAsync(new ReadOnlyMemory<byte>(preamble), cancellationToken).ConfigureAwait(false).GetAwaiter();
                        if (!configuredValueTaskAwaiter.IsCompleted)
{
                            num2 = 0;
                            ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter2 = configuredValueTaskAwaiter;
                            this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter, StreamWriter.<FlushAsyncInternal>d__74>(ref configuredValueTaskAwaiter, ref this);
                            return;
                        }
                        break;
                    }
                    }
                    configuredValueTaskAwaiter.GetResult();
                    IL_00BA:
                    int bytes = encoder.GetBytes(charBuffer, 0, charPos, byteBuffer, 0, flushEncoder);
                    if (bytes <= 0)
                    {
                        goto IL_0168;
                    }
                    configuredValueTaskAwaiter = stream.WriteAsync(new ReadOnlyMemory<byte>(byteBuffer, 0, bytes), cancellationToken).ConfigureAwait(false).GetAwaiter();
                    if (!configuredValueTaskAwaiter.IsCompleted)
                    {
                        num2 = 1;
                        ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter2 = configuredValueTaskAwaiter;
                        this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter, StreamWriter.<FlushAsyncInternal>d__74>(ref configuredValueTaskAwaiter, ref this);
                        return;
                    }
                    IL_0161:
                    configuredValueTaskAwaiter.GetResult();
                    IL_0168:
                    if (!flushStream)
                    {
                        goto IL_01E0;
                    }
                    configuredTaskAwaiter = stream.FlushAsync(cancellationToken).ConfigureAwait(false).GetAwaiter();
                    if (!configuredTaskAwaiter.IsCompleted)
                    {
                        num2 = 2;
                        ConfiguredTaskAwaitable.ConfiguredTaskAwaiter configuredTaskAwaiter2 = configuredTaskAwaiter;
                        this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredTaskAwaitable.ConfiguredTaskAwaiter, StreamWriter.<FlushAsyncInternal>d__74>(ref configuredTaskAwaiter, ref this);
                        return;
                    }
                    IL_01D9:
                    configuredTaskAwaiter.GetResult();
                    IL_01E0:;
                }
                catch (Exception ex)
                {
                    num2 = -2;
                    this.<>t__builder.SetException(ex);
                    return;
                }
                num2 = -2;
                this.<>t__builder.SetResult();
            }
References System.IO.StreamWriter.FlushAsyncInternal(), System.Runtime.CompilerServices.ConfiguredTaskAwaitable< TResult >.ConfiguredTaskAwaiter.GetResult(), System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable< TResult >.ConfiguredValueTaskAwaiter.GetResult(), System.Runtime.CompilerServices.ConfiguredTaskAwaitable< TResult >.ConfiguredTaskAwaiter.IsCompleted, and System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable< TResult >.ConfiguredValueTaskAwaiter.IsCompleted.