Terraria Decompiled: Microsoft.Xna.Framework.Graphics.BasicEffect.OnApply
OnApply()
override void Microsoft.Xna.Framework.Graphics.BasicEffect.OnApply () inline package virtual
Reimplemented from Microsoft.Xna.Framework.Graphics.Effect.
Definition at line 402 of file BasicEffect.cs.
        {
            this.dirtyFlags = EffectHelpers.SetWorldViewProjAndFog(this.dirtyFlags, ref this.world, ref this.view, ref this.projection, ref this.worldView, this.fogEnabled, this.fogStart, this.fogEnd, this.worldViewProjParam, this.fogVectorParam);
            if ((this.dirtyFlags & EffectDirtyFlags.MaterialColor) != (EffectDirtyFlags)0)
            {
                EffectHelpers.SetMaterialColor(this.lightingEnabled, this.alpha, ref this.diffuseColor, ref this.emissiveColor, ref this.ambientLightColor, this.diffuseColorParam, this.emissiveColorParam);
                this.dirtyFlags &= ~EffectDirtyFlags.MaterialColor;
            }
            if (this.lightingEnabled)
            {
                this.dirtyFlags = EffectHelpers.SetLightingMatrices(this.dirtyFlags, ref this.world, ref this.view, this.worldParam, this.worldInverseTransposeParam, this.eyePositionParam);
                bool flag = !this.light1.Enabled && !this.light2.Enabled;
                if (this.oneLight != flag)
                {
                    this.oneLight = flag;
                    this.dirtyFlags |= EffectDirtyFlags.ShaderIndex;
                }
            }
            if ((this.dirtyFlags & EffectDirtyFlags.ShaderIndex) != (EffectDirtyFlags)0)
            {
                int num = 0;
                if (!this.fogEnabled)
                {
                    num++;
                }
                if (this.vertexColorEnabled)
                {
                    num += 2;
                }
                if (this.textureEnabled)
                {
                    num += 4;
                }
                if (this.lightingEnabled)
                {
                    if (this.preferPerPixelLighting)
                    {
                        num += 24;
                    }
                    else if (this.oneLight)
                    {
                        num += 16;
                    }
                    else
                    {
                        num += 8;
                    }
                }
                this.shaderIndexParam.SetValue(num);
                this.dirtyFlags &= ~EffectDirtyFlags.ShaderIndex;
            }
        }
References Microsoft.Xna.Framework.Graphics.BasicEffect.alpha, Microsoft.Xna.Framework.Graphics.BasicEffect.ambientLightColor, Microsoft.Xna.Framework.Graphics.BasicEffect.diffuseColor, Microsoft.Xna.Framework.Graphics.BasicEffect.diffuseColorParam, Microsoft.Xna.Framework.Graphics.BasicEffect.dirtyFlags, Microsoft.Xna.Framework.Graphics.BasicEffect.emissiveColor, Microsoft.Xna.Framework.Graphics.BasicEffect.emissiveColorParam, Microsoft.Xna.Framework.Graphics.DirectionalLight.Enabled, Microsoft.Xna.Framework.Graphics.BasicEffect.eyePositionParam, Microsoft.Xna.Framework.Graphics.BasicEffect.fogEnabled, Microsoft.Xna.Framework.Graphics.BasicEffect.fogEnd, Microsoft.Xna.Framework.Graphics.BasicEffect.fogStart, Microsoft.Xna.Framework.Graphics.BasicEffect.fogVectorParam, Microsoft.Xna.Framework.Graphics.BasicEffect.light2, Microsoft.Xna.Framework.Graphics.BasicEffect.lightingEnabled, Microsoft.Xna.Framework.Graphics.BasicEffect.oneLight, Microsoft.Xna.Framework.Graphics.BasicEffect.preferPerPixelLighting, Microsoft.Xna.Framework.Graphics.BasicEffect.projection, Microsoft.Xna.Framework.Graphics.EffectHelpers.SetLightingMatrices(), Microsoft.Xna.Framework.Graphics.EffectHelpers.SetMaterialColor(), Microsoft.Xna.Framework.Graphics.EffectParameter.SetValue(), Microsoft.Xna.Framework.Graphics.EffectHelpers.SetWorldViewProjAndFog(), Microsoft.Xna.Framework.Graphics.BasicEffect.shaderIndexParam, Microsoft.Xna.Framework.Graphics.BasicEffect.textureEnabled, Microsoft.Xna.Framework.Graphics.BasicEffect.vertexColorEnabled, Microsoft.Xna.Framework.Graphics.BasicEffect.view, Microsoft.Xna.Framework.Graphics.BasicEffect.world, Microsoft.Xna.Framework.Graphics.BasicEffect.worldInverseTransposeParam, Microsoft.Xna.Framework.Graphics.BasicEffect.worldParam, Microsoft.Xna.Framework.Graphics.BasicEffect.worldView, and Microsoft.Xna.Framework.Graphics.BasicEffect.worldViewProjParam.