Terraria Decompiled: Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsMushroomBoiTargetFound
Spawn_DeadCellsMushroomBoiTargetFound()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsMushroomBoiTargetFound (ParticleOrchestraSettings settings) inline static private
Definition at line 2001 of file ParticleOrchestrator.cs.
        {
            ShockIconParticle shockIconParticle = ParticleOrchestrator._poolShockIcon.RequestParticle();
            shockIconParticle.ColorTint = new Color(255, 255, 10, 150);
            shockIconParticle.LocalPosition = settings.PositionInWorld;
            shockIconParticle.TimeToLive = 15f;
            shockIconParticle.FadeInNormalizedTime = 0.2f;
            shockIconParticle.FadeOutNormalizedTime = 0.7f;
            shockIconParticle.Velocity = Vector2.Zero;
            shockIconParticle.InitialScale = 1f;
            shockIconParticle.ParentProjectileID = settings.UniqueInfoPiece;
            shockIconParticle.OffsetFromParent = new Vector2(0f, -40f);
            Main.ParticleSystem_World_BehindPlayers.Add(shockIconParticle);
        }
References Terraria.GameContent.Drawing.ParticleOrchestrator._poolShockIcon, Terraria.Graphics.Renderers.ParticleRenderer.Add(), Microsoft.Xna.Framework.Graphics.Color, Terraria.Main.ParticleSystem_World_BehindPlayers, Terraria.GameContent.Drawing.ParticleOrchestraSettings.PositionInWorld, Terraria.Graphics.Renderers.ParticlePool< T >.RequestParticle(), Terraria.GameContent.Drawing.ParticleOrchestraSettings.UniqueInfoPiece, Microsoft.Xna.Framework.Graphics.Vector2, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnParticlesDirect().