Terraria Decompiled: Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_WallOfFleshGoatMountFlames
Spawn_WallOfFleshGoatMountFlames()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_WallOfFleshGoatMountFlames (ParticleOrchestraSettings settings) inline static private
Definition at line 3357 of file ParticleOrchestrator.cs.
        {
            float num = 50f;
            for (int i = -1; i <= 1; i++)
            {
                int num2 = (int)Main.rand.NextFromList(new short[] { 326, 327, 328 });
                Main.instance.LoadProjectile(num2);
                Player player = Main.player[(int)settings.IndexOfPlayerWhoInvokedThis];
                float num3 = Main.rand.NextFloat() * 0.9f + 0.1f;
                Vector2 vector = settings.PositionInWorld + new Vector2((float)i * 5.3333335f, 0f);
                FlameParticle flameParticle = ParticleOrchestrator._poolFlame.RequestParticle();
                flameParticle.SetBasicInfo(TextureAssets.Projectile[num2], null, Vector2.Zero, vector);
                flameParticle.SetTypeInfo(num, (int)settings.IndexOfPlayerWhoInvokedThis, player.cMount);
                flameParticle.FadeOutNormalizedTime = 0.3f;
                flameParticle.ScaleAcceleration = Vector2.One * num3 * -0.016666668f / num;
                flameParticle.Scale = Vector2.One * num3;
                Main.ParticleSystem_World_BehindPlayers.Add(flameParticle);
                if (Main.rand.Next(8) == 0)
                {
                    Dust dust = Dust.NewDustDirect(vector, 4, 4, 6, 0f, 0f, 100, default(Color), 1f);
                    if (Main.rand.Next(2) == 0)
                    {
                        dust.noGravity = true;
                        dust.fadeIn = 1.15f;
                    }
                    else
                    {
                        dust.scale = 0.6f;
                    }
                    dust.velocity *= 0.6f;
                    Dust dust2 = dust;
                    dust2.velocity.Y = dust2.velocity.Y - 1.2f;
                    dust.noLight = true;
                    Dust dust3 = dust;
                    dust3.position.Y = dust3.position.Y - 4f;
                    dust.shader = GameShaders.Armor.GetSecondaryShader(player.cMount, player);
                }
            }
        }
References Terraria.GameContent.Drawing.ParticleOrchestrator._poolFlame, Terraria.Graphics.Renderers.ParticleRenderer.Add(), Terraria.Graphics.Shaders.GameShaders.Armor, Terraria.Player.cMount, Terraria.Graphics.Shaders.ArmorShaderDataSet.GetSecondaryShader(), Terraria.GameContent.Drawing.ParticleOrchestraSettings.IndexOfPlayerWhoInvokedThis, Terraria.Main.instance, int, Terraria.Main.LoadProjectile(), Terraria.Dust.NewDustDirect(), Terraria.Main.ParticleSystem_World_BehindPlayers, Terraria.Main.player, Terraria.GameContent.TextureAssets.Projectile, Terraria.Main.rand, Terraria.Graphics.Renderers.ParticlePool< T >.RequestParticle(), Terraria.Graphics.Renderers.FlameParticle.SetBasicInfo(), Terraria.Graphics.Renderers.FlameParticle.SetTypeInfo(), Microsoft.Xna.Framework.Graphics.Vector2, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnParticlesDirect().