Terraria Decompiled: Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_RainbowBoulder1
Spawn_RainbowBoulder1()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_RainbowBoulder1 (ParticleOrchestraSettings settings) inline static private
Definition at line 960 of file ParticleOrchestrator.cs.
        {
            float num = Main.rand.NextFloat() * 6.2831855f;
            float num2 = (float)(6 + Main.rand.Next(7));
            float num3 = Main.rand.NextFloat();
            Main.rand.Next(2);
            for (float num4 = 0f; num4 < 1f; num4 += 1f / num2)
            {
                Vector2 zero = Vector2.Zero;
                Vector2 vector = new Vector2(Main.rand.NextFloat() * 0.3f + 1f);
                float num5 = num + Main.rand.NextFloat() * 6.2831855f;
                num5 = num + 6.2831855f * num4;
                float num6 = 1.5707964f;
                Vector2 vector2 = 0.8f * vector * (0.9f + 0.1f * Main.rand.NextFloat());
                float num7 = (float)(Main.rand.Next(20) + 180);
                Vector2 vector3 = Main.rand.NextVector2Circular(16f, 16f) * vector;
                vector2 = Main.rand.NextVector2CircularEdge(1.5f, 1.5f);
                vector2.X = 0f;
                if (vector2.Y > 0f)
                {
                    vector2.Y *= -1f;
                }
                PrettySparkleParticle prettySparkleParticle = ParticleOrchestrator._poolPrettySparkle.RequestParticle();
                prettySparkleParticle.Velocity = vector2 + zero;
                prettySparkleParticle.AccelerationPerFrame = num5.ToRotationVector2() * -(vector2 / num7) - zero * 1f / num7;
                prettySparkleParticle.ColorTint = Main.hslToRgb((num3 + Main.rand.NextFloat() * 0.33f) % 1f, 1f, 0.4f + Main.rand.NextFloat() * 0.25f, byte.MaxValue);
                prettySparkleParticle.ColorTint = Main.hslToRgb((num4 + num3) % 1f, 1f, 0.5f, byte.MaxValue);
                prettySparkleParticle.ColorTint.A = byte.MaxValue;
                prettySparkleParticle.LocalPosition = settings.PositionInWorld + vector3;
                prettySparkleParticle.Rotation = num6;
                prettySparkleParticle.Scale = vector;
                Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle);
                prettySparkleParticle = ParticleOrchestrator._poolPrettySparkle.RequestParticle();
                prettySparkleParticle.Velocity = vector2 + zero;
                prettySparkleParticle.AccelerationPerFrame = num5.ToRotationVector2() * -(vector2 / num7) - zero * 1f / num7;
                prettySparkleParticle.ColorTint = new Color(255, 255, 255, 0);
                prettySparkleParticle.LocalPosition = settings.PositionInWorld + vector3;
                prettySparkleParticle.Rotation = num6;
                prettySparkleParticle.Scale = vector * 0.3f;
                Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle);
            }
            for (int i = 0; i < 21; i++)
            {
                Dust dust = Dust.NewDustDirect(settings.PositionInWorld, 16, 16, 66, 0f, 0f, 100, Main.hslToRgb(Main.rand.NextFloat(), 1f, 0.5f, byte.MaxValue), 1.7f);
                dust.noGravity = true;
                dust.velocity = Main.rand.NextVector2CircularEdge(1f, 1f) * (8f + 2f * Main.rand.NextFloat());
                dust.fadeIn = 1f + Main.rand.NextFloat();
                dust.velocity.X = 0f;
                if (dust.velocity.Y > 0f)
                {
                    Dust dust2 = dust;
                    dust2.velocity.Y = dust2.velocity.Y * -1f;
                }
                dust.position -= dust.velocity * 5f;
            }
        }
References Terraria.GameContent.Drawing.ParticleOrchestrator._poolPrettySparkle, Terraria.Graphics.Renderers.ParticleRenderer.Add(), Microsoft.Xna.Framework.Graphics.Color, Terraria.Main.hslToRgb(), Terraria.Dust.NewDustDirect(), Terraria.Main.ParticleSystem_World_OverPlayers, Terraria.GameContent.Drawing.ParticleOrchestraSettings.PositionInWorld, Terraria.Main.rand, Terraria.Graphics.Renderers.ParticlePool< T >.RequestParticle(), Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Dust.velocity, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnParticlesDirect().