Terraria Decompiled: Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ShadowOrbExplosion
Spawn_ShadowOrbExplosion()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ShadowOrbExplosion (ParticleOrchestraSettings settings) inline static private
Definition at line 1505 of file ParticleOrchestrator.cs.
        {
            float num = 20f + 10f * Main.rand.NextFloat();
            float num2 = -0.7853982f;
            float num3 = 0.2f + 0.4f * Main.rand.NextFloat();
            Color color = Main.hslToRgb(Main.rand.NextFloat() * 0.05f + 0.75f, 1f, 0.5f, byte.MaxValue);
            color.A /= 2;
            color *= Main.rand.NextFloat() * 0.3f + 0.7f;
            for (float num4 = 0f; num4 < 2f; num4 += 1f)
            {
                PrettySparkleParticle prettySparkleParticle = ParticleOrchestrator._poolPrettySparkle.RequestParticle();
                Vector2 vector = (0.7853982f + 3.1415927f * num4 + num2).ToRotationVector2() * 4f;
                prettySparkleParticle.ColorTint = color;
                prettySparkleParticle.LocalPosition = settings.PositionInWorld + Main.rand.NextVector2Circular(16f, 16f);
                prettySparkleParticle.Rotation = vector.ToRotation();
                prettySparkleParticle.Scale = new Vector2(4f, 1f) * 1.1f * num3;
                prettySparkleParticle.FadeInNormalizedTime = 5E-06f;
                prettySparkleParticle.FadeOutNormalizedTime = 0.95f;
                prettySparkleParticle.TimeToLive = num;
                prettySparkleParticle.FadeOutEnd = num;
                prettySparkleParticle.FadeInEnd = num / 2f;
                prettySparkleParticle.FadeOutStart = num / 2f;
                prettySparkleParticle.AdditiveAmount = 0.35f;
                prettySparkleParticle.LocalPosition -= vector * num * 0.25f;
                prettySparkleParticle.Velocity = vector * 0.05f;
                prettySparkleParticle.DrawVerticalAxis = false;
                if (num4 == 1f)
                {
                    prettySparkleParticle.Scale *= 1.5f;
                    prettySparkleParticle.Velocity *= 1.5f;
                    prettySparkleParticle.LocalPosition -= prettySparkleParticle.Velocity * 4f;
                }
                Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle);
            }
            for (float num5 = 0f; num5 < 2f; num5 += 1f)
            {
                PrettySparkleParticle prettySparkleParticle2 = ParticleOrchestrator._poolPrettySparkle.RequestParticle();
                Vector2 vector2 = (0.7853982f + 3.1415927f * num5 + num2).ToRotationVector2() * 4f;
                prettySparkleParticle2.ColorTint = new Color(0.7583333f, 0.4f, 0.2f, 1f);
                prettySparkleParticle2.LocalPosition = settings.PositionInWorld + Main.rand.NextVector2Circular(16f, 16f);
                prettySparkleParticle2.Rotation = vector2.ToRotation();
                prettySparkleParticle2.Scale = new Vector2(4f, 1f) * 0.7f * num3;
                prettySparkleParticle2.FadeInNormalizedTime = 5E-06f;
                prettySparkleParticle2.FadeOutNormalizedTime = 0.95f;
                prettySparkleParticle2.TimeToLive = num;
                prettySparkleParticle2.FadeOutEnd = num;
                prettySparkleParticle2.FadeInEnd = num / 2f;
                prettySparkleParticle2.FadeOutStart = num / 2f;
                prettySparkleParticle2.LocalPosition -= vector2 * num * 0.25f;
                prettySparkleParticle2.Velocity = vector2 * 0.05f;
                prettySparkleParticle2.DrawVerticalAxis = false;
                if (num5 == 1f)
                {
                    prettySparkleParticle2.Scale *= 1.5f;
                    prettySparkleParticle2.Velocity *= 1.5f;
                    prettySparkleParticle2.LocalPosition -= prettySparkleParticle2.Velocity * 4f;
                }
                Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle2);
                for (int i = 0; i < 1; i++)
                {
                    Dust dust = Dust.NewDustPerfect(settings.PositionInWorld, 6, new Vector2?(vector2.RotatedBy((double)(Main.rand.NextFloatDirection() * 6.2831855f * 0.025f), default(Vector2)) * Main.rand.NextFloat()), 0, default(Color), 1f);
                    dust.noGravity = true;
                    dust.scale = 1.4f;
                    Dust dust2 = Dust.NewDustPerfect(settings.PositionInWorld, 6, new Vector2?(-vector2.RotatedBy((double)(Main.rand.NextFloatDirection() * 6.2831855f * 0.025f), default(Vector2)) * Main.rand.NextFloat()), 0, default(Color), 1f);
                    dust2.noGravity = true;
                    dust2.scale = 1.4f;
                }
            }
            Vector2 vector3 = settings.PositionInWorld + new Vector2(-18f, -16f);
            float num6 = 4f;
            float num7 = 4f;
            for (int j = 0; j < 0; j++)
            {
                int num8 = j % 2;
                Gore gore = Gore.NewGoreDirect(vector3, Vector2.Zero, 99, 1f + Main.rand.NextFloat() * 0.3f);
                gore.velocity = Main.rand.NextVector2Circular(num6, num7);
                gore.alpha = 127;
                gore.rotation = 6.2831855f * Main.rand.NextFloat();
                gore.position += gore.velocity * 4f;
                gore = Gore.NewGoreDirect(vector3, Vector2.Zero, 99, 0.8f + Main.rand.NextFloat() * 0.3f);
                gore.velocity = Main.rand.NextVector2Circular(num6, num7);
                gore.alpha = 127;
                gore.rotation = 6.2831855f * Main.rand.NextFloat();
                gore.position += gore.velocity * 4f;
                gore = Gore.NewGoreDirect(vector3, Vector2.Zero, 99, 1.2f + Main.rand.NextFloat() * 0.3f);
                gore.velocity = Main.rand.NextVector2Circular(num6, num7);
                gore.alpha = 127;
                gore.rotation = 6.2831855f * Main.rand.NextFloat();
                gore.position += gore.velocity * 4f;
            }
        }
References Terraria.GameContent.Drawing.ParticleOrchestrator._poolPrettySparkle, Terraria.Graphics.Renderers.ParticleRenderer.Add(), Microsoft.Xna.Framework.Graphics.Color, System.E, Terraria.Main.hslToRgb(), Terraria.Dust.NewDustPerfect(), Terraria.Gore.NewGoreDirect(), Terraria.Main.ParticleSystem_World_OverPlayers, Terraria.GameContent.Drawing.ParticleOrchestraSettings.PositionInWorld, Terraria.Main.rand, Terraria.Graphics.Renderers.ParticlePool< T >.RequestParticle(), Microsoft.Xna.Framework.Graphics.Vector2, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnParticlesDirect().