Terraria Decompiled: Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_InScreenDungeonSpawn
Spawn_InScreenDungeonSpawn()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_InScreenDungeonSpawn (ParticleOrchestraSettings settings) inline static private
Definition at line 398 of file ParticleOrchestrator.cs.
        {
            Vector2 movementVector = settings.MovementVector;
            Vector2 positionInWorld = settings.PositionInWorld;
            int uniqueInfoPiece = settings.UniqueInfoPiece;
            Vector2 vector = positionInWorld + new Vector2(-0.5f, -1f) * movementVector;
            int num = Main.rand.Next(2, 5);
            for (int i = 0; i < num; i++)
            {
                Gore gore = Gore.NewGorePerfect(vector + new Vector2(-16f, -16f) + movementVector * new Vector2(Main.rand.NextFloat(), 0.5f + Main.rand.NextFloat() * 0.5f), Main.rand.NextVector2Circular(2f, 2f), Main.rand.Next(61, 64), 1f);
                gore.scale *= 1f;
                gore.position -= gore.velocity * 5f;
            }
            SoundEngine.PlaySound(ContentSamples.NpcsByNetId[uniqueInfoPiece].HitSound, (int)settings.PositionInWorld.X, (int)settings.PositionInWorld.Y, 0f, 1f);
        }
References Terraria.GameContent.Drawing.ParticleOrchestraSettings.MovementVector, Terraria.Gore.NewGorePerfect(), Terraria.ID.ContentSamples.NpcsByNetId, Terraria.Audio.SoundEngine.PlaySound(), Terraria.GameContent.Drawing.ParticleOrchestraSettings.PositionInWorld, Terraria.Main.rand, Terraria.GameContent.Drawing.ParticleOrchestraSettings.UniqueInfoPiece, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnParticlesDirect().