Terraria Decompiled: Terraria.GameContent.Drawing.ParticleOrchestrator.CopperSlimeEffect
CopperSlimeEffect()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.CopperSlimeEffect (ParticleOrchestraSettings settings) inline static private
Definition at line 2078 of file ParticleOrchestrator.cs.
        {
            for (int i = 0; i < 40; i++)
            {
                Dust dust = Dust.NewDustPerfect(settings.PositionInWorld + Main.rand.NextVector2Circular(20f, 20f), 43, new Vector2?((settings.MovementVector * 0.75f + Main.rand.NextVector2Circular(6f, 6f)) * Main.rand.NextFloat()), 26, Color.Lerp(new Color(183, 88, 25), Color.White, Main.rand.NextFloat() * 0.5f), 1f + Main.rand.NextFloat() * 1.4f);
                dust.fadeIn = 1.5f;
                if (dust.velocity.Y > 0f && Main.rand.Next(2) == 0)
                {
                    Dust dust2 = dust;
                    dust2.velocity.Y = dust2.velocity.Y * -1f;
                }
                dust.noGravity = true;
            }
        }
References Microsoft.Xna.Framework.Color.Lerp(), Terraria.GameContent.Drawing.ParticleOrchestraSettings.MovementVector, Terraria.Dust.NewDustPerfect(), Terraria.GameContent.Drawing.ParticleOrchestraSettings.PositionInWorld, Terraria.Main.rand, Terraria.Dust.velocity, Microsoft.Xna.Framework.Color.White, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_TownSlimeTransform().