Terraria Decompiled: Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_StormLightningWindup
Spawn_StormLightningWindup()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_StormLightningWindup (ParticleOrchestraSettings settings) inline static private
Definition at line 494 of file ParticleOrchestrator.cs.
        {
            float num = Main.rand.NextFloat() * 6.2831855f;
            float num2 = (float)Main.rand.Next(1, 3);
            float num3 = 0.7f;
            short num4 = 916;
            Main.instance.LoadProjectile((int)num4);
            Color white = Color.White;
            if (settings.UniqueInfoPiece != 0)
            {
                white.PackedValue = (uint)settings.UniqueInfoPiece;
            }
            white.A = 0;
            for (float num5 = 0f; num5 < 1f; num5 += 1f / num2)
            {
                int num6 = Main.rand.Next(7, 11);
                float num7 = 6.2831855f * num5 + num + Main.rand.NextFloatDirection() * 0.25f;
                float num8 = Main.rand.NextFloat() * 3f + 0.1f;
                Vector2 vector = Main.rand.NextVector2Circular(6f, 6f) * num3;
                Color color = white;
                RandomizedFrameParticle randomizedFrameParticle = ParticleOrchestrator._poolRandomizedFrame.RequestParticle();
                randomizedFrameParticle.SetBasicInfo(TextureAssets.Projectile[(int)num4], null, Vector2.Zero, vector);
                randomizedFrameParticle.SetTypeInfo(Main.projFrames[(int)num4], 2, (float)num6);
                randomizedFrameParticle.Velocity = num7.ToRotationVector2() * num8 * new Vector2(1f, 0.5f) + settings.MovementVector * 0.5f;
                randomizedFrameParticle.ColorTint = color;
                randomizedFrameParticle.LocalPosition = settings.PositionInWorld + vector;
                randomizedFrameParticle.Rotation = randomizedFrameParticle.Velocity.ToRotation();
                randomizedFrameParticle.Scale = new Vector2(1.5f, 0.75f) * 1f;
                randomizedFrameParticle.FadeInNormalizedTime = 1f;
                randomizedFrameParticle.FadeOutNormalizedTime = 0.9f;
                randomizedFrameParticle.ScaleVelocity = new Vector2(0.025f);
                if (Main.rand.Next(3) == 0)
                {
                    randomizedFrameParticle.LocalPosition += randomizedFrameParticle.Velocity * (float)(num6 - 1);
                    randomizedFrameParticle.Velocity *= -0.5f;
                }
                Main.ParticleSystem_World_OverPlayers.Add(randomizedFrameParticle);
                RandomizedFrameParticle randomizedFrameParticle2 = ParticleOrchestrator._poolRandomizedFrame.RequestParticle();
                randomizedFrameParticle2.SetBasicInfo(TextureAssets.Projectile[(int)num4], null, Vector2.Zero, vector);
                randomizedFrameParticle2.SetTypeInfo(Main.projFrames[(int)num4], 2, (float)num6);
                randomizedFrameParticle2.Velocity = randomizedFrameParticle.Velocity;
                randomizedFrameParticle2.ColorTint = new Color(255, 255, 255, 0);
                randomizedFrameParticle2.LocalPosition = randomizedFrameParticle.LocalPosition;
                randomizedFrameParticle2.Rotation = randomizedFrameParticle.Rotation;
                randomizedFrameParticle2.Scale = randomizedFrameParticle.Scale * 0.5f;
                randomizedFrameParticle2.FadeInNormalizedTime = randomizedFrameParticle.FadeInNormalizedTime;
                randomizedFrameParticle2.FadeOutNormalizedTime = randomizedFrameParticle.FadeOutNormalizedTime;
                randomizedFrameParticle2.ScaleVelocity = randomizedFrameParticle.ScaleVelocity * 0.5f;
                Main.ParticleSystem_World_OverPlayers.Add(randomizedFrameParticle2);
            }
        }
References Terraria.GameContent.Drawing.ParticleOrchestrator._poolRandomizedFrame, Terraria.Graphics.Renderers.ParticleRenderer.Add(), Microsoft.Xna.Framework.Graphics.Color, Terraria.Graphics.Renderers.RandomizedFrameParticle.FadeInNormalizedTime, Terraria.Graphics.Renderers.RandomizedFrameParticle.FadeOutNormalizedTime, Terraria.Main.instance, Terraria.Main.LoadProjectile(), Terraria.Graphics.Renderers.ABasicParticle.LocalPosition, Terraria.Main.ParticleSystem_World_OverPlayers, Terraria.GameContent.TextureAssets.Projectile, Terraria.Main.projFrames, Terraria.Main.rand, Terraria.Graphics.Renderers.ParticlePool< T >.RequestParticle(), Terraria.Graphics.Renderers.ABasicParticle.Rotation, Terraria.Graphics.Renderers.ABasicParticle.SetBasicInfo(), Terraria.Graphics.Renderers.RandomizedFrameParticle.SetTypeInfo(), Terraria.GameContent.Drawing.ParticleOrchestraSettings.UniqueInfoPiece, Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Graphics.Renderers.ABasicParticle.Velocity, Microsoft.Xna.Framework.Color.White, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnParticlesDirect().