Terraria Decompiled: Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_StormLightning
Spawn_StormLightning()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_StormLightning (ParticleOrchestraSettings settings) inline static private
Definition at line 547 of file ParticleOrchestrator.cs.
        {
            StormLightningParticle stormLightningParticle = ParticleOrchestrator.StormLightningParticles.RequestParticle();
            Color white = Color.White;
            if (settings.UniqueInfoPiece != 0)
            {
                white.PackedValue = (uint)settings.UniqueInfoPiece;
            }
            int num = 45;
            int num2 = (int)settings.MovementVector.X;
            stormLightningParticle.Prepare((uint)num2, settings.PositionInWorld, num, white);
            Main.ParticleSystem_World_OverPlayers.Add(stormLightningParticle);
            settings.PositionInWorld = stormLightningParticle.EndPosition;
            PunchCameraModifier punchCameraModifier = new PunchCameraModifier(settings.PositionInWorld, (Main.rand.NextFloat() * 6.2831855f).ToRotationVector2() * new Vector2(0.5f, 1f), MathHelper.Lerp(2f, 10f, Main.SceneState.outsideWeatherEffectIntensity), 3f, 45, 1500f, "StormLightning");
            Main.instance.CameraModifiers.Add(punchCameraModifier);
            Main.NewLightning(true, true);
            SoundEngine.PlaySound(SoundID.InstantThunder, settings.PositionInWorld, 0f, MathHelper.Lerp(0.4f, 1f, Main.SceneState.outsideWeatherEffectIntensity));
            Lighting.AddLight(settings.PositionInWorld, (float)white.R / 255f, (float)white.G / 255f, (float)white.B / 255f);
            int num3 = 3;
            Point point = settings.PositionInWorld.ToTileCoordinates();
            for (int i = point.X - 1; i <= point.X + 1; i++)
            {
                for (int j = point.Y - 1; j <= point.Y + 1; j++)
                {
                    Tile tileSafely = Framing.GetTileSafely(i, j);
                    if (tileSafely.active())
                    {
                        int num4 = WorldGen.KillTile_GetTileDustAmount(true, tileSafely);
                        for (int k = 0; k < num4; k++)
{
                            Dust dust = Main.dust[WorldGen.KillTile_MakeTileDust(i, j, tileSafely)];
                            dust.velocity.Y = dust.velocity.Y - (3f + (float)num3 * 1.5f);
                            dust.velocity.Y = dust.velocity.Y * Main.rand.NextFloat();
                            dust.velocity.Y = dust.velocity.Y * 0.75f;
                            dust.scale += (float)num3 * 0.03f;
                        }
                        for (int l = 0; l < num4 - 1; l++)
{
                            Dust dust2 = Main.dust[WorldGen.KillTile_MakeTileDust(i, j, tileSafely)];
                            dust2.velocity.Y = dust2.velocity.Y - (1f + (float)num3);
                            dust2.velocity.Y = dust2.velocity.Y * Main.rand.NextFloat();
                            dust2.velocity.Y = dust2.velocity.Y * 0.75f;
                        }
                        if (tileSafely.type == 5)
{
                            for (int m = 0; m < 6; m++)
{
                                Dust dust3 = Dust.NewDustDirect(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16, 6, 0f, 0f, 0, default(Color), 1f);
                                dust3.velocity *= 2f;
                                dust3.fadeIn += Main.rand.NextFloat();
                                dust3.noLightEmittance = true;
                            }
                            for (int n = 0; n < 3; n++)
{
                                Dust dust4 = Dust.NewDustDirect(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16, 31, 0f, 0f, 0, default(Color), 1f);
                                dust4.velocity *= 3f;
                                dust4.noGravity = true;
                                dust4.fadeIn += 1f + Main.rand.NextFloat();
                            }
                        }
                    }
                }
            }
            ParticleOrchestrator.SpawnLightningExplosionDust(settings.PositionInWorld, white);
            for (int num5 = 0; num5 < 4; num5++)
            {
                Gore.NewGoreDirect(settings.PositionInWorld + Utils.RandomVector2(Main.rand, -15f, 15f) * new Vector2(0.5f, 1f) + new Vector2(-20f, 0f), Vector2.Zero, 61 + Main.rand.Next(3), 1f).velocity *= 0.5f;
            }
            Vector2 vector = new Vector2(1.1f);
            Vector2 vector2 = new Vector2(-0.9f);
            short num6 = 1091;
            Main.instance.LoadProjectile((int)num6);
            FadingParticle fadingParticle = ParticleOrchestrator._poolFading.RequestParticle();
            fadingParticle.SetBasicInfo(TextureAssets.Projectile[(int)num6], null, Vector2.Zero, settings.PositionInWorld);
            fadingParticle.SetTypeInfo((float)num, true);
            fadingParticle.ColorTint = white;
            fadingParticle.ColorTint.A = 0;
            fadingParticle.FadeInNormalizedTime = 0.01f;
            fadingParticle.FadeOutNormalizedTime = 0.6f;
            fadingParticle.Scale = vector;
            fadingParticle.ScaleVelocity = vector2 / (float)num;
            fadingParticle.ScaleAcceleration = fadingParticle.ScaleVelocity * (-1f / (float)num);
            Main.ParticleSystem_World_OverPlayers.Add(fadingParticle);
            FadingParticle fadingParticle2 = ParticleOrchestrator._poolFading.RequestParticle();
            fadingParticle2.SetBasicInfo(TextureAssets.Projectile[(int)num6], null, Vector2.Zero, settings.PositionInWorld);
            fadingParticle2.SetTypeInfo((float)num, true);
            fadingParticle2.ColorTint = new Color(255, 255, 255);
            fadingParticle2.FadeInNormalizedTime = 0.01f;
            fadingParticle2.FadeOutNormalizedTime = 0.6f;
            fadingParticle2.Scale = vector * 0.7f;
            fadingParticle2.ScaleVelocity = vector2 * 0.7f / (float)num;
            fadingParticle2.ScaleAcceleration = fadingParticle2.ScaleVelocity * (-1f / (float)num);
            Main.ParticleSystem_World_OverPlayers.Add(fadingParticle2);
            float num7 = 12f;
            num6 = 916;
            Main.instance.LoadProjectile((int)num6);
            for (float num8 = 0f; num8 < 1f; num8 += 1f / num7)
            {
                int num9 = Main.rand.Next(14, 22);
                Vector2 vector3 = Main.rand.NextVector2Circular(6f, 6f) * 0.7f;
                Color color = white;
                RandomizedFrameParticle randomizedFrameParticle = ParticleOrchestrator._poolRandomizedFrame.RequestParticle();
                randomizedFrameParticle.SetBasicInfo(TextureAssets.Projectile[(int)num6], null, Vector2.Zero, vector3);
                randomizedFrameParticle.SetTypeInfo(Main.projFrames[(int)num6], 3, (float)num9);
                randomizedFrameParticle.Velocity = Main.rand.NextVector2Circular(6f, 3f);
                randomizedFrameParticle.ColorTint = color;
                randomizedFrameParticle.LocalPosition = settings.PositionInWorld + vector3;
                randomizedFrameParticle.Rotation = randomizedFrameParticle.Velocity.ToRotation();
                randomizedFrameParticle.Scale = new Vector2(1.5f, 0.75f) * 0.85f;
                randomizedFrameParticle.FadeInNormalizedTime = 0.01f;
                randomizedFrameParticle.FadeOutNormalizedTime = 0f;
                randomizedFrameParticle.ScaleVelocity = new Vector2(0.025f);
                Main.ParticleSystem_World_OverPlayers.Add(randomizedFrameParticle);
                RandomizedFrameParticle randomizedFrameParticle2 = ParticleOrchestrator._poolRandomizedFrame.RequestParticle();
                randomizedFrameParticle2.SetBasicInfo(TextureAssets.Projectile[(int)num6], null, Vector2.Zero, vector3);
                randomizedFrameParticle2.SetTypeInfo(Main.projFrames[(int)num6], 3, (float)num9);
                randomizedFrameParticle2.Velocity = randomizedFrameParticle.Velocity;
                randomizedFrameParticle2.ColorTint = new Color(255, 255, 255, 0);
                randomizedFrameParticle2.LocalPosition = randomizedFrameParticle.LocalPosition;
                randomizedFrameParticle2.Rotation = randomizedFrameParticle.Rotation;
                randomizedFrameParticle2.Scale = randomizedFrameParticle.Scale * 0.5f;
                randomizedFrameParticle2.FadeInNormalizedTime = randomizedFrameParticle.FadeInNormalizedTime;
                randomizedFrameParticle2.FadeOutNormalizedTime = randomizedFrameParticle.FadeOutNormalizedTime;
                randomizedFrameParticle2.ScaleVelocity = randomizedFrameParticle.ScaleVelocity * 0.5f;
                Main.ParticleSystem_World_OverPlayers.Add(randomizedFrameParticle2);
            }
        }
References Terraria.GameContent.Drawing.ParticleOrchestrator._poolFading, Terraria.GameContent.Drawing.ParticleOrchestrator._poolRandomizedFrame, Terraria.Tile.active(), Terraria.Graphics.CameraModifiers.CameraModifierStack.Add(), Terraria.Graphics.Renderers.ParticleRenderer.Add(), Terraria.Lighting.AddLight(), Microsoft.Xna.Framework.Color.B, Terraria.Main.CameraModifiers, Microsoft.Xna.Framework.Graphics.Color, Terraria.Main.dust, Terraria.Graphics.Renderers.StormLightningParticle.EndPosition, Terraria.Graphics.Renderers.RandomizedFrameParticle.FadeInNormalizedTime, Terraria.Graphics.Renderers.RandomizedFrameParticle.FadeOutNormalizedTime, Microsoft.Xna.Framework.Color.G, Terraria.Framing.GetTileSafely(), Terraria.Main.instance, Terraria.ID.SoundID.InstantThunder, int, Terraria.WorldGen.KillTile_GetTileDustAmount(), Terraria.WorldGen.KillTile_MakeTileDust(), Microsoft.Xna.Framework.MathHelper.Lerp(), Terraria.Main.LoadProjectile(), Terraria.Graphics.Renderers.ABasicParticle.LocalPosition, Terraria.GameContent.Drawing.ParticleOrchestraSettings.MovementVector, Terraria.Dust.NewDustDirect(), Terraria.Gore.NewGoreDirect(), Terraria.Main.NewLightning(), Terraria.SceneState.outsideWeatherEffectIntensity, Terraria.Main.ParticleSystem_World_OverPlayers, Terraria.Audio.SoundEngine.PlaySound(), Terraria.GameContent.Drawing.ParticleOrchestraSettings.PositionInWorld, Terraria.Graphics.Renderers.StormLightningParticle.Prepare(), Terraria.GameContent.TextureAssets.Projectile, Terraria.Main.projFrames, Microsoft.Xna.Framework.Color.R, Terraria.Main.rand, Terraria.Utils.RandomVector2(), Terraria.Graphics.Renderers.ParticlePool< T >.RequestParticle(), Terraria.Graphics.Renderers.ABasicParticle.Rotation, Terraria.Main.SceneState, Terraria.Graphics.Renderers.ABasicParticle.SetBasicInfo(), Terraria.Graphics.Renderers.FadingParticle.SetTypeInfo(), Terraria.Graphics.Renderers.RandomizedFrameParticle.SetTypeInfo(), Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnLightningExplosionDust(), Terraria.GameContent.Drawing.ParticleOrchestrator.StormLightningParticles, Terraria.Tile.type, Terraria.GameContent.Drawing.ParticleOrchestraSettings.UniqueInfoPiece, Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Gore.velocity, Terraria.Graphics.Renderers.ABasicParticle.Velocity, Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Point.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnParticlesDirect().