Terraria Decompiled: Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_PaladinsShieldHit
Spawn_PaladinsShieldHit()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_PaladinsShieldHit (ParticleOrchestraSettings settings) inline static private
Definition at line 421 of file ParticleOrchestrator.cs.
        {
            Main.instance.LoadItem(938);
            Asset<Texture2D> asset = TextureAssets.Item[938];
            if (!asset.IsLoaded)
            {
                return;
            }
            Vector2 positionInWorld = settings.PositionInWorld;
            int num = (int)positionInWorld.X;
            int num2 = (int)positionInWorld.Y;
            Vector2 vector = Vector2.Zero;
            if (Main.player.IndexInRange(num))
            {
                Player player = Main.player[num];
                vector = player.MountedCenter;
                FadingParticle fadingParticle = ParticleOrchestrator._poolFading.RequestParticle();
                int num3 = 30;
                fadingParticle.followPlayerIndex = num;
                fadingParticle.ColorTint = new Color(255, 255, 255, 220) * 0.85f;
                fadingParticle.SetBasicInfo(asset, null, Vector2.Zero, Vector2.Zero);
                fadingParticle.SetTypeInfo((float)num3, true);
                fadingParticle.FadeInNormalizedTime = 0.1f;
                fadingParticle.FadeOutNormalizedTime = 0.1f;
                fadingParticle.Scale = new Vector2(1f, 1f) * 0.65f;
                fadingParticle.ScaleVelocity = new Vector2(2f, 2f) / (float)num3;
                fadingParticle.ScaleAcceleration = -fadingParticle.ScaleVelocity / (float)num3;
                Main.ParticleSystem_World_OverPlayers.Add(fadingParticle);
                for (int i = 0; i < 4; i++)
                {
                    Dust dust = Dust.NewDustDirect(player.position, player.width, player.height, 57, 0f, 0f, 0, default(Color), 1f);
                    dust.velocity *= 3f;
                    dust.noGravity = true;
                    dust.scale = 1f;
                    dust.fadeIn = 1.5f;
                    dust.noLight = true;
                }
            }
            if (Main.player.IndexInRange(num2))
            {
                Player player2 = Main.player[num2];
                FadingParticle fadingParticle2 = ParticleOrchestrator._poolFading.RequestParticle();
                float num4 = 15f;
                fadingParticle2.followPlayerIndex = num;
                fadingParticle2.ColorTint = new Color(255, 255, 255, 127) * 0.75f;
                fadingParticle2.SetBasicInfo(asset, null, Vector2.Zero, Vector2.Zero);
                fadingParticle2.SetTypeInfo(num4, true);
                fadingParticle2.FadeInNormalizedTime = 0.1f;
                fadingParticle2.FadeOutNormalizedTime = 0.1f;
                fadingParticle2.Scale = new Vector2(1f, 1f) * 0.65f;
                fadingParticle2.ScaleVelocity = new Vector2(2f, 2f) / num4;
                fadingParticle2.ScaleAcceleration = -fadingParticle2.ScaleVelocity / num4;
                Vector2 vector2 = vector - player2.MountedCenter;
                fadingParticle2.LocalPosition = -vector2;
                if (num == -1)
                {
                    fadingParticle2.LocalPosition = player2.MountedCenter;
                }
                fadingParticle2.Velocity = vector2 * 0.5f / num4;
                Main.ParticleSystem_World_OverPlayers.Add(fadingParticle2);
                for (int j = 0; j < 4; j++)
                {
                    Dust dust2 = Dust.NewDustDirect(player2.position, player2.width, player2.height, 57, 0f, 0f, 0, default(Color), 1f);
                    dust2.velocity *= 3f;
                    dust2.noGravity = true;
                    dust2.scale = 1f;
                    dust2.fadeIn = 1.5f;
                    dust2.noLight = true;
                }
            }
        }
References Terraria.GameContent.Drawing.ParticleOrchestrator._poolFading, Terraria.Graphics.Renderers.ParticleRenderer.Add(), Microsoft.Xna.Framework.Graphics.Color, Terraria.Entity.height, Terraria.Main.instance, int, ReLogic.Content.Asset< T >.IsLoaded, Terraria.GameContent.TextureAssets.Item, Terraria.Main.LoadItem(), Terraria.Player.MountedCenter, Terraria.Dust.NewDustDirect(), Terraria.Main.ParticleSystem_World_OverPlayers, Terraria.Main.player, Terraria.Entity.position, Terraria.GameContent.Drawing.ParticleOrchestraSettings.PositionInWorld, Terraria.Graphics.Renderers.ParticlePool< T >.RequestParticle(), Terraria.Graphics.Renderers.ABasicParticle.SetBasicInfo(), Terraria.Graphics.Renderers.FadingParticle.SetTypeInfo(), Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnParticlesDirect().