Terraria Decompiled: Terraria.GameContent.Drawing.ParticleOrchestrator.PushAwayFakeFish
PushAwayFakeFish()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.PushAwayFakeFish (Projectile proj, int searchedItemType) inline static
Definition at line 850 of file ParticleOrchestrator.cs.
        {
            foreach (FakeFishParticle fakeFishParticle in from x in Main.ParticleSystem_World_BehindPlayers.Particles.OfType<FakeFishParticle>()
                orderby x.Position.Distance(proj.Center)
                select x)
            {
                fakeFishParticle.TryToPushAway(proj, searchedItemType);
            }
        }
References Microsoft.Xna.Framework.Vector2.Distance(), Terraria.Graphics.Renderers.ParticleRenderer.Particles, Terraria.Main.ParticleSystem_World_BehindPlayers, Terraria.Graphics.Renderers.FakeFishParticle.Position, and Terraria.Graphics.Renderers.FakeFishParticle.TryToPushAway().
Referenced by Terraria.Projectile.FishingCheck_RollItemDrop().