Terraria Decompiled: Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_FakeFish
Spawn_FakeFish()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_FakeFish (ParticleOrchestraSettings settings, bool jumping = false) inline static private
Definition at line 792 of file ParticleOrchestrator.cs.
        {
            FakeFishParticle fakeFishParticle = ParticleOrchestrator._fakeFish.RequestParticle();
            Vector2 movementVector = settings.MovementVector;
            int uniqueInfoPiece = settings.UniqueInfoPiece;
            int num = Main.rand.Next(240, 421);
            fakeFishParticle.Position = settings.PositionInWorld;
            fakeFishParticle.Velocity = Vector2.Zero;
            fakeFishParticle.Prepare(uniqueInfoPiece, num, movementVector);
            if (jumping)
            {
                fakeFishParticle.Velocity = settings.MovementVector;
                fakeFishParticle.TryJumping();
            }
            Main.ParticleSystem_World_BehindPlayers.Add(fakeFishParticle);
        }
References Terraria.GameContent.Drawing.ParticleOrchestrator._fakeFish, Terraria.Graphics.Renderers.ParticleRenderer.Add(), Terraria.GameContent.Drawing.ParticleOrchestraSettings.MovementVector, Terraria.Main.ParticleSystem_World_BehindPlayers, Terraria.GameContent.Drawing.ParticleOrchestraSettings.PositionInWorld, Terraria.Graphics.Renderers.FakeFishParticle.Prepare(), Terraria.Main.rand, Terraria.Graphics.Renderers.ParticlePool< T >.RequestParticle(), Terraria.Graphics.Renderers.FakeFishParticle.TryJumping(), Terraria.GameContent.Drawing.ParticleOrchestraSettings.UniqueInfoPiece, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnParticlesDirect().