Terraria Decompiled: Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsDownDashExplosion
Spawn_DeadCellsDownDashExplosion()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsDownDashExplosion (ParticleOrchestraSettings settings) inline static private
Definition at line 1598 of file ParticleOrchestrator.cs.
        {
            Vector2 positionInWorld = settings.PositionInWorld;
            SoundEngine.PlayTrackedSound(SoundID.DD2_MonkStaffGroundImpact, positionInWorld, default(SoundPlayOverrides));
            float x = settings.MovementVector.X;
            Point point = (positionInWorld + new Vector2(-x, -160f)).ToTileCoordinates();
            Point point2 = (positionInWorld + new Vector2(x, 160f)).ToTileCoordinates();
            int num = point.X / 2 + point2.X / 2;
            int num2 = (int)x / 2;
            bool flag = settings.UniqueInfoPiece == 1;
            float num3 = (flag ? 0.01f : 0.55f);
            float num4 = (flag ? 2f : 1f);
            float num5 = (flag ? 3f : 2f);
            for (int i = 0; i < 40; i++)
            {
                Vector2 vector = Main.rand.NextVector2Circular(5f, 3f);
                if (vector.Y > 0f)
                {
                    vector.Y *= -1f;
                }
                if (flag)
                {
                    vector *= 1.5f;
                }
                Dust dust = Dust.CloneDust(Dust.NewDustPerfect(positionInWorld + Main.rand.NextVector2Circular(10f, 0f), 306, new Vector2?(vector), 0, Main.hslToRgb(num3, 1f, 0.5f, byte.MaxValue), 1.9f + 0.8f * Main.rand.NextFloat()));
                dust.scale -= 0.6f;
                dust.color = Color.White;
            }
            float num6 = 40f;
            int num7 = 3;
            for (int j = point.X; j <= point2.X; j++)
            {
                for (int k = point.Y; k <= point2.Y; k++)
                {
                    if (Vector2.Distance(positionInWorld, new Vector2((float)(j * 16), (float)(k * 16))) <= (float)num2)
                    {
                        Tile tileSafely = Framing.GetTileSafely(j, k);
                        if (tileSafely.active() && Main.tileSolid[(int)tileSafely.type] && (!Main.tileSolidTop[(int)tileSafely.type] || tileSafely.frameY == 0) && (!Main.tileFrameImportant[(int)tileSafely.type] || Main.tileSolidTop[(int)tileSafely.type]))
{
                            Tile tileSafely2 = Framing.GetTileSafely(j, k - 1);
                            if (!tileSafely2.active() || !Main.tileSolid[(int)tileSafely2.type] || Main.tileSolidTop[(int)tileSafely2.type])
{
                                int num8 = WorldGen.KillTile_GetTileDustAmount(true, tileSafely);
                                for (int l = 0; l < num8; l++)
{
                                    Dust dust2 = Main.dust[WorldGen.KillTile_MakeTileDust(j, k, tileSafely)];
                                    dust2.velocity.Y = dust2.velocity.Y - (3f + (float)num7 * 1.5f);
                                    dust2.velocity.Y = dust2.velocity.Y * Main.rand.NextFloat();
                                    dust2.velocity.Y = dust2.velocity.Y * 0.75f;
                                    dust2.scale += (float)num7 * 0.03f;
                                }
                                if (num7 >= 2)
{
                                    for (int m = 0; m < num8 - 1; m++)
{
                                        Dust dust3 = Main.dust[WorldGen.KillTile_MakeTileDust(j, k, tileSafely)];
                                        dust3.velocity.Y = dust3.velocity.Y - (1f + (float)num7);
                                        dust3.velocity.Y = dust3.velocity.Y * Main.rand.NextFloat();
                                        dust3.velocity.Y = dust3.velocity.Y * 0.75f;
                                    }
                                }
                                if (num8 > 0 && Main.rand.Next(3) != 0)
{
                                    float num9 = (float)Math.Abs(num - j) / (num6 / 2f);
                                    Gore gore = Gore.NewGoreDirect(positionInWorld, Vector2.Zero, 61 + Main.rand.Next(3), 1f - (float)num7 * 0.15f + num9 * 0.5f);
                                    Gore gore2 = gore;
                                    gore2.velocity.Y = gore2.velocity.Y - (0.1f + (float)num7 * 0.5f + num9 * (float)num7 * 1f);
                                    Gore gore3 = gore;
                                    gore3.velocity.Y = gore3.velocity.Y * Main.rand.NextFloat();
                                    gore.position = new Vector2((float)(j * 16 + 20), (float)(k * 16));
                                    PrettySparkleParticle prettySparkleParticle = ParticleOrchestrator._poolPrettySparkle.RequestParticle();
                                    int num10 = Main.rand.Next(20, 40);
                                    prettySparkleParticle.ColorTint = Main.hslToRgb(num3 + 0.1f * Main.rand.NextFloat(), 1f, 0.5f, 0);
                                    prettySparkleParticle.LocalPosition = gore.position;
                                    prettySparkleParticle.Rotation = 1.5707964f;
                                    prettySparkleParticle.Scale = new Vector2(num4 + Main.rand.NextFloat() * num5, 0.7f + Main.rand.NextFloat() * 0.7f);
                                    prettySparkleParticle.Velocity = new Vector2(0f, -2f);
                                    prettySparkleParticle.FadeInNormalizedTime = 0.1f;
                                    prettySparkleParticle.FadeOutNormalizedTime = 0.95f;
                                    prettySparkleParticle.TimeToLive = (float)num10;
                                    prettySparkleParticle.FadeOutEnd = (float)num10;
                                    prettySparkleParticle.FadeInEnd = (float)(num10 / 2);
                                    prettySparkleParticle.FadeOutStart = (float)(num10 / 2);
                                    prettySparkleParticle.AdditiveAmount = 0.35f;
                                    prettySparkleParticle.DrawVerticalAxis = false;
                                    Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle);
                                }
                            }
                        }
                    }
                }
            }
        }
References Terraria.GameContent.Drawing.ParticleOrchestrator._poolPrettySparkle, System.Math.Abs(), Terraria.Tile.active(), Terraria.Graphics.Renderers.ParticleRenderer.Add(), Terraria.Dust.CloneDust(), Terraria.ID.SoundID.DD2_MonkStaffGroundImpact, Microsoft.Xna.Framework.Vector2.Distance(), Terraria.Main.dust, Terraria.Framing.GetTileSafely(), Terraria.Main.hslToRgb(), int, Terraria.WorldGen.KillTile_GetTileDustAmount(), Terraria.WorldGen.KillTile_MakeTileDust(), Terraria.GameContent.Drawing.ParticleOrchestraSettings.MovementVector, Terraria.Dust.NewDustPerfect(), Terraria.Gore.NewGoreDirect(), Terraria.Main.ParticleSystem_World_OverPlayers, Terraria.Audio.SoundEngine.PlayTrackedSound(), Terraria.Gore.position, Terraria.GameContent.Drawing.ParticleOrchestraSettings.PositionInWorld, Terraria.Main.rand, Terraria.Graphics.Renderers.ParticlePool< T >.RequestParticle(), Terraria.Main.tileFrameImportant, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Tile.type, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Point.Y, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnParticlesDirect().