Terraria Decompiled: XPT.Core.Audio.MP3Sharp.Decoding.Bitstream.ReadFully
ReadFully()
void XPT.Core.Audio.MP3Sharp.Decoding.Bitstream.ReadFully (sbyte[] b, int offs, int len) inline private
Definition at line 278 of file Bitstream.cs.
        {
            try
            {
                while (len > 0)
                {
                    int num = this._SourceStream.Read(b, offs, len);
                    if (num != -1)
                    {
                        if (num != 0)
{
                            offs += num;
                            len -= num;
                            continue;
                        }
                    }
                    while (len-- > 0)
                    {
                        b[offs++] = 0;
                    }
                    break;
                }
            }
            catch (IOException ex)
            {
                throw this.NewBitstreamException(258, ex);
            }
        }
References XPT.Core.Audio.MP3Sharp.Decoding.Bitstream._SourceStream, XPT.Core.Audio.MP3Sharp.Decoding.Bitstream.NewBitstreamException(), and XPT.Core.Audio.MP3Sharp.Decoding.PushbackStream.Read().
Referenced by XPT.Core.Audio.MP3Sharp.Decoding.Bitstream.Read_frame_data().