Terraria Decompiled: Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsHeadEffect
Spawn_DeadCellsHeadEffect()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsHeadEffect (ParticleOrchestraSettings settings) inline static private
Definition at line 1380 of file ParticleOrchestrator.cs.
        {
            Asset<Texture2D> asset = TextureAssets.Extra[266];
            if (!asset.IsLoaded)
            {
                return;
            }
            Player player = Main.player[(int)settings.IndexOfPlayerWhoInvokedThis];
            if (!player.active)
            {
                return;
            }
            Vector2 vector = settings.MovementVector;
            vector += new Vector2(0f, 0f);
            for (float num = 0f; num < 1f; num += 0.5f)
            {
                float num2 = 0.5f * Utils.Remap(settings.MovementVector.Length(), 0f, 10f, 0.5f, 1f, true);
                float num3 = 1f;
                float num4 = 15f;
                float num5 = 6.2831855f * Main.rand.NextFloat();
                Vector2 vector2 = Main.rand.NextVector2Circular(4f, 4f) * num2;
                FadingPlayerShaderParticle fadingPlayerShaderParticle = ParticleOrchestrator._poolFadingPlayerShader.RequestParticle();
                fadingPlayerShaderParticle.SetBasicInfo(asset, null, Vector2.Zero, Vector2.Zero);
                fadingPlayerShaderParticle.SetTypeInfo(num4, player, player.cHead, false);
                fadingPlayerShaderParticle.Velocity = vector * 0.5f;
                fadingPlayerShaderParticle.AccelerationPerFrame = fadingPlayerShaderParticle.Velocity * -(-1f / num4) * 0.25f;
                fadingPlayerShaderParticle.LocalPosition = settings.PositionInWorld + num5.ToRotationVector2() * num3 * num2 * num4 * 0.5f + vector2 + vector * num;
                fadingPlayerShaderParticle.LocalPosition += fadingPlayerShaderParticle.Velocity * -0.5f;
                fadingPlayerShaderParticle.Rotation = vector.ToRotation() + 1.5707964f;
                fadingPlayerShaderParticle.FadeInNormalizedTime = 0.01f;
                fadingPlayerShaderParticle.FadeOutNormalizedTime = 0.1f;
                fadingPlayerShaderParticle.Scale = new Vector2(0.6f, 1.2f) * num2;
                fadingPlayerShaderParticle.ScaleVelocity = fadingPlayerShaderParticle.Scale * (-1f / num4);
                Main.ParticleSystem_World_BehindPlayers.Add(fadingPlayerShaderParticle);
            }
        }
References Terraria.GameContent.Drawing.ParticleOrchestrator._poolFadingPlayerShader, Terraria.Player.active, Terraria.Graphics.Renderers.ParticleRenderer.Add(), Terraria.Player.cHead, Terraria.GameContent.TextureAssets.Extra, Terraria.GameContent.Drawing.ParticleOrchestraSettings.IndexOfPlayerWhoInvokedThis, int, ReLogic.Content.Asset< T >.IsLoaded, Microsoft.Xna.Framework.Vector2.Length(), Terraria.GameContent.Drawing.ParticleOrchestraSettings.MovementVector, Terraria.Main.ParticleSystem_World_BehindPlayers, Terraria.Main.player, Terraria.Main.rand, Terraria.Utils.Remap(), Terraria.Graphics.Renderers.ParticlePool< T >.RequestParticle(), Terraria.Graphics.Renderers.ABasicParticle.SetBasicInfo(), Terraria.Graphics.Renderers.FadingPlayerShaderParticle.SetTypeInfo(), Microsoft.Xna.Framework.Graphics.Vector2, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnParticlesDirect().