Terraria Decompiled: XPT.Core.Audio.MP3Sharp.Decoding.Bitstream.GetBitsFromBuffer
GetBitsFromBuffer()
int XPT.Core.Audio.MP3Sharp.Decoding.Bitstream.GetBitsFromBuffer (int countBits) inline package
Definition at line 245 of file Bitstream.cs.
        {
            int num = this._BitIndex + countBits;
            if (this._WordPointer < 0)
            {
                this._WordPointer = 0;
            }
            if (num <= 32)
            {
                int num2 = SupportClass.URShift(this._FrameBuffer[this._WordPointer], 32 - num) & this._Bitmask[countBits];
                if ((this._BitIndex += countBits) == 32)
                {
                    this._BitIndex = 0;
                    this._WordPointer++;
                }
                return num2;
            }
            int num3 = this._FrameBuffer[this._WordPointer] & 65535;
            this._WordPointer++;
            int num4 = this._FrameBuffer[this._WordPointer] & (int)SupportClass.Identity((long)((ulong)(-65536)));
            int num5 = SupportClass.URShift(((num3 << 16) & (int)SupportClass.Identity((long)((ulong)(-65536)))) | (SupportClass.URShift(num4, 16) & 65535), 48 - num) & this._Bitmask[countBits];
            this._BitIndex = num - 32;
            return num5;
        }
References XPT.Core.Audio.MP3Sharp.Decoding.Bitstream._BitIndex, XPT.Core.Audio.MP3Sharp.Decoding.Bitstream._Bitmask, XPT.Core.Audio.MP3Sharp.Decoding.Bitstream._FrameBuffer, XPT.Core.Audio.MP3Sharp.Decoding.Bitstream._WordPointer, XPT.Core.Audio.MP3Sharp.Support.SupportClass.Identity(), int, and XPT.Core.Audio.MP3Sharp.Support.SupportClass.URShift().
Referenced by XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.Decode(), XPT.Core.Audio.MP3Sharp.Decoding.Header.read_header(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerI.SubbandLayer1.ReadAllocation(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerI.SubbandLayer1Stereo.ReadAllocation(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerII.SubbandLayer2.ReadAllocation(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerII.SubbandLayer2Stereo.ReadAllocation(), XPT.Core.Audio.MP3Sharp.Decoding.Bitstream.ReadBits(), XPT.Core.Audio.MP3Sharp.Decoding.Bitstream.ReadCheckedBits(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerI.SubbandLayer1.ReadSampleData(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerI.SubbandLayer1Stereo.ReadSampleData(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerII.SubbandLayer2.ReadSampleData(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerII.SubbandLayer2Stereo.ReadSampleData(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerI.SubbandLayer1.ReadScaleFactor(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerI.SubbandLayer1IntensityStereo.ReadScaleFactor(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerI.SubbandLayer1Stereo.ReadScaleFactor(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerII.SubbandLayer2.ReadScaleFactor(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerII.SubbandLayer2IntensityStereo.ReadScaleFactor(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerII.SubbandLayer2Stereo.ReadScaleFactor(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerII.SubbandLayer2.ReadScaleFactorSelection(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerII.SubbandLayer2IntensityStereo.ReadScaleFactorSelection(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerII.SubbandLayer2Stereo.ReadScaleFactorSelection(), and XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.ReadSideInfo().