Terraria Decompiled: Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnLightningExplosionDust
SpawnLightningExplosionDust()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnLightningExplosionDust (Vector2 position, Color customColor) inline static
Definition at line 676 of file ParticleOrchestrator.cs.
        {
            for (int i = 0; i < 12; i++)
            {
                Dust dust = Dust.NewDustPerfect(position, 226, null, 0, default(Color), 1f);
                dust.HackFrame(278);
                dust.color = customColor;
                dust.customData = dust.color;
                dust.velocity *= 1f + Main.rand.NextFloat() * 2.5f;
                dust.velocity += new Vector2(0f, -2f);
                dust.fadeIn = 0f;
                dust.scale = 0.4f + Main.rand.NextFloat() * 0.5f;
                Dust dust2 = dust;
                dust2.velocity.X = dust2.velocity.X * 2f;
                dust.position -= dust.velocity * 3f;
            }
            for (int j = 0; j < 6; j++)
            {
                Dust dust3 = Dust.NewDustPerfect(position, 226, null, 0, default(Color), 1f);
                dust3.HackFrame(278);
                dust3.color = customColor;
                dust3.customData = dust3.color;
                dust3.velocity *= 1f + Main.rand.NextFloat() * 2.5f;
                dust3.velocity += new Vector2(0f, -2f);
                dust3.fadeIn = 1.7f + (float)Main.rand.Next() * 1f;
                dust3.noGravity = true;
                dust3.scale = 0.4f + Main.rand.NextFloat() * 0.5f;
                Dust dust4 = dust3;
                dust4.velocity.X = dust4.velocity.X * 2f;
                dust3.velocity *= 0.6f;
                dust3.position -= dust3.velocity * 3f;
            }
            for (int k = 0; k < 6; k++)
            {
                Dust dust5 = Dust.NewDustPerfect(position + Main.rand.NextVector2Circular(20f, 20f), 226, null, 0, default(Color), 1f);
                dust5.HackFrame(278);
                dust5.color = customColor;
                dust5.customData = dust5.color;
                dust5.velocity = new Vector2(0f, -1f).RotatedByRandom(0.7853981852531433);
                dust5.velocity *= 3f + Main.rand.NextFloat() * 6.5f;
                dust5.fadeIn = 0f;
                dust5.scale = 0.4f + Main.rand.NextFloat() * 0.5f;
                dust5.noGravity = true;
                dust5.position -= dust5.velocity * 2f;
            }
            for (int l = 0; l < 6; l++)
            {
                Dust dust6 = Dust.NewDustPerfect(position, 306, new Vector2?(new Vector2(0f, -4f).RotatedByRandom(1.5707963705062866)), 0, default(Color), 1f);
                dust6.color = new Color((int)customColor.R, (int)customColor.G, (int)customColor.B, 0);
                dust6.scale = 2.8f;
                dust6.fadeIn = 0f;
                dust6.noGravity = Main.rand.Next(3) != 0;
                Dust dust7 = Dust.CloneDust(dust6);
                dust7.color = new Color(255, 255, 255, 0);
                dust7.scale = 1.9f;
            }
            for (int m = 0; m < 6; m++)
            {
                Dust dust8 = Dust.NewDustPerfect(position, 306, new Vector2?(new Vector2(0f, -2f).RotatedByRandom(1.5707963705062866)), 0, default(Color), 1f);
                dust8.color = new Color((int)customColor.R, (int)customColor.G, (int)customColor.B, 0);
                dust8.scale = 2.8f;
                dust8.fadeIn = 0f;
                dust8.noGravity = Main.rand.Next(3) != 0;
                Dust dust9 = Dust.CloneDust(dust8);
                dust9.color = new Color(255, 255, 255, 0);
                dust9.scale = 1.9f;
            }
            for (int n = 0; n < 3; n++)
            {
                Dust dust10 = Dust.NewDustPerfect(position + Main.rand.NextVector2Circular(20f, 20f), 43, new Vector2?(Main.rand.NextVector2Circular(6f, 6f) * Main.rand.NextFloat()), 26, Color.Lerp(customColor, Color.White, Main.rand.NextFloat()), 1f + Main.rand.NextFloat() * 1.4f);
                dust10.fadeIn = 1.5f;
                if (dust10.velocity.Y > 0f && Main.rand.Next(2) == 0)
                {
                    Dust dust11 = dust10;
                    dust11.velocity.Y = dust11.velocity.Y * -1f;
                }
                dust10.noGravity = true;
            }
        }
References Microsoft.Xna.Framework.Color.B, Terraria.Dust.CloneDust(), Microsoft.Xna.Framework.Graphics.Color, Terraria.Dust.color, Microsoft.Xna.Framework.Color.G, Terraria.Dust.HackFrame(), Microsoft.Xna.Framework.Color.Lerp(), Terraria.Dust.NewDustPerfect(), Microsoft.Xna.Framework.Color.R, Terraria.Main.rand, Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Dust.velocity, Microsoft.Xna.Framework.Color.White, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_StormLightning(), and Terraria.Projectile.SpawnHitVisuals().