Terraria Decompiled: XPT.Core.Audio.MP3Sharp.Decoding.Bitstream.IsSyncCurrentPosition
IsSyncCurrentPosition()
bool XPT.Core.Audio.MP3Sharp.Decoding.Bitstream.IsSyncCurrentPosition (int syncmode) inline package
Definition at line 98 of file Bitstream.cs.
        {
            int num = this.ReadBytes(this._SyncBuffer, 0, 4);
            int num2 = (((int)this._SyncBuffer[0] << 24) & (int)SupportClass.Identity((long)((ulong)(-16777216)))) | (((int)this._SyncBuffer[1] << 16) & 16711680) | (((int)this._SyncBuffer[2] << 8) & 65280) | ((int)this._SyncBuffer[3] & 255);
            try
            {
                this._SourceStream.UnRead(num);
            }
            catch (Exception ex)
            {
                throw new MP3SharpException("Could not restore file after reading frame header.", ex);
            }
            bool flag = false;
            if (num != 0)
            {
                if (num == 4)
                {
                    flag = this.IsSyncMark(num2, syncmode, this._SyncWord);
                }
            }
            else
            {
                flag = true;
            }
            return flag;
        }
References XPT.Core.Audio.MP3Sharp.Decoding.Bitstream._SourceStream, XPT.Core.Audio.MP3Sharp.Decoding.Bitstream._SyncBuffer, XPT.Core.Audio.MP3Sharp.Decoding.Bitstream._SyncWord, XPT.Core.Audio.MP3Sharp.Support.SupportClass.Identity(), int, XPT.Core.Audio.MP3Sharp.Decoding.Bitstream.IsSyncMark(), XPT.Core.Audio.MP3Sharp.Decoding.Bitstream.ReadBytes(), and XPT.Core.Audio.MP3Sharp.Decoding.PushbackStream.UnRead().
Referenced by XPT.Core.Audio.MP3Sharp.Decoding.Header.read_header().