Terraria Decompiled: Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ClassyCane
Spawn_ClassyCane()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ClassyCane (ParticleOrchestraSettings settings) inline static private
Definition at line 2392 of file ParticleOrchestrator.cs.
        {
            int num = 7;
            float num2 = 1.1f;
            int num3 = 10;
            Color color = default(Color);
            Vector2 positionInWorld = settings.PositionInWorld;
            int num4 = 20;
            int num5 = 20;
            positionInWorld.X -= (float)(num4 / 2);
            positionInWorld.Y -= (float)(num5 / 2);
            int num6 = Main.rand.Next(0, 2);
            for (int i = 0; i < num6; i++)
            {
                int num7 = Gore.NewGore(new Vector2(positionInWorld.X + (float)Main.rand.Next(num4), positionInWorld.Y + (float)Main.rand.Next(num5)), Vector2.Zero, 1218, 1f);
                Main.gore[num7].velocity = new Vector2((float)Main.rand.Next(-10, 11) * 0.4f, -(3f + (float)Main.rand.Next(6) * 0.3f));
            }
            for (int j = 0; j < num; j++)
            {
                int num8 = Dust.NewDust(positionInWorld, num4, num5, num3, 0f, -1f, 80, color, num2);
                if (Main.rand.Next(3) != 0)
                {
                    Main.dust[num8].noGravity = true;
                }
            }
        }
References Terraria.Main.dust, Terraria.Main.gore, Terraria.Dust.NewDust(), Terraria.Gore.NewGore(), Terraria.Dust.noGravity, Terraria.GameContent.Drawing.ParticleOrchestraSettings.PositionInWorld, Terraria.Main.rand, Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Gore.velocity, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnParticlesDirect().