Terraria Decompiled: Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_PaladinsHammerShockwave
Spawn_PaladinsHammerShockwave()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_PaladinsHammerShockwave (ParticleOrchestraSettings settings) inline static private
Definition at line 369 of file ParticleOrchestrator.cs.
        {
            Vector2 positionInWorld = settings.PositionInWorld;
            int num = (int)settings.MovementVector.X;
            int num2 = (int)settings.MovementVector.Y;
            Vector2 vector = positionInWorld + new Vector2((float)num * 0.5f, (float)num2 * 0.5f);
            SoundEngine.PlaySound(SoundID.Item180, vector, 0f, 1f);
            for (int i = 0; i < 200; i++)
            {
                if (Main.rand.Next(2) == 0)
                {
                    int num3 = Dust.NewDust(positionInWorld, num, num2, 57, 0f, 0f, 200, default(Color), 1.2f);
                    Main.dust[num3].velocity = Main.dust[num3].position - vector;
                    Main.dust[num3].velocity.Normalize();
                    Main.dust[num3].velocity *= 9.5f;
                    Main.dust[num3].noGravity = true;
                }
                if (Main.rand.Next(3) == 0)
                {
                    int num4 = Dust.NewDust(positionInWorld, num, num2, 43, 0f, 0f, 254, default(Color), 0.3f);
                    Main.dust[num4].velocity = Main.dust[num4].position - vector;
                    Main.dust[num4].velocity.Normalize();
                    Main.dust[num4].velocity *= 9.5f;
                    Main.dust[num4].noGravity = true;
                }
            }
        }
References Terraria.Main.dust, int, Terraria.ID.SoundID.Item180, Terraria.GameContent.Drawing.ParticleOrchestraSettings.MovementVector, Terraria.Dust.NewDust(), Terraria.Dust.noGravity, Microsoft.Xna.Framework.Vector2.Normalize(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.Dust.position, Terraria.GameContent.Drawing.ParticleOrchestraSettings.PositionInWorld, Terraria.Main.rand, Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Dust.velocity, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnParticlesDirect().