Terraria Decompiled: Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_BlueLightningSmallLong
Spawn_BlueLightningSmallLong()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_BlueLightningSmallLong (ParticleOrchestraSettings settings) inline static private
Definition at line 3118 of file ParticleOrchestrator.cs.
        {
            Vector2 vector = settings.PositionInWorld;
            Vector2 vector2 = settings.MovementVector.SafeNormalize(Vector2.Zero);
            float num = settings.MovementVector.Length();
            int num2 = 25;
            int num3 = 40;
            if (num < (float)num3)
            {
                return;
            }
            float num4 = 0f;
            while (num4 < num)
            {
                ParticleOrchestrator.Spawn_BlueLightningSmall(new ParticleOrchestraSettings
                {
                    PositionInWorld = vector,
                    MovementVector = vector2 * 2f
                });
                num4 += (float)num2;
                vector += vector2 * (float)num2;
            }
        }
References Microsoft.Xna.Framework.Vector2.Length(), Terraria.GameContent.Drawing.ParticleOrchestraSettings.MovementVector, Terraria.GameContent.Drawing.ParticleOrchestraSettings.PositionInWorld, Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_BlueLightningSmall(), and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnParticlesDirect().