Terraria Decompiled: Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_TerraBlade
Spawn_TerraBlade()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_TerraBlade (ParticleOrchestraSettings settings) inline static private
Definition at line 2213 of file ParticleOrchestrator.cs.
        {
            float num = 30f;
            float num2 = settings.MovementVector.ToRotation() + 1.5707964f;
            float num3 = 3f;
            for (float num4 = 0f; num4 < 4f; num4 += 1f)
            {
                PrettySparkleParticle prettySparkleParticle = ParticleOrchestrator._poolPrettySparkle.RequestParticle();
                Vector2 vector = (1.5707964f * num4 + num2).ToRotationVector2() * 4f;
                prettySparkleParticle.ColorTint = new Color(0.2f, 0.85f, 0.4f, 0.5f);
                prettySparkleParticle.LocalPosition = settings.PositionInWorld;
                prettySparkleParticle.Rotation = vector.ToRotation();
                prettySparkleParticle.Scale = new Vector2(num3, 0.5f) * 1.1f;
                prettySparkleParticle.FadeInNormalizedTime = 5E-06f;
                prettySparkleParticle.FadeOutNormalizedTime = 0.95f;
                prettySparkleParticle.TimeToLive = num;
                prettySparkleParticle.FadeOutEnd = num;
                prettySparkleParticle.FadeInEnd = num / 2f;
                prettySparkleParticle.FadeOutStart = num / 2f;
                prettySparkleParticle.AdditiveAmount = 0.35f;
                prettySparkleParticle.Velocity = -vector * 0.2f;
                prettySparkleParticle.DrawVerticalAxis = false;
                if (num4 % 2f == 1f)
                {
                    prettySparkleParticle.Scale *= 1.5f;
                    prettySparkleParticle.Velocity *= 2f;
                }
                Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle);
            }
            for (float num5 = -1f; num5 <= 1f; num5 += 2f)
            {
                PrettySparkleParticle prettySparkleParticle2 = ParticleOrchestrator._poolPrettySparkle.RequestParticle();
                num2.ToRotationVector2() * 4f;
                Vector2 vector2 = (1.5707964f * num5 + num2).ToRotationVector2() * 2f;
                prettySparkleParticle2.ColorTint = new Color(0.4f, 1f, 0.4f, 0.5f);
                prettySparkleParticle2.LocalPosition = settings.PositionInWorld;
                prettySparkleParticle2.Rotation = vector2.ToRotation();
                prettySparkleParticle2.Scale = new Vector2(num3, 0.5f) * 1.1f;
                prettySparkleParticle2.FadeInNormalizedTime = 5E-06f;
                prettySparkleParticle2.FadeOutNormalizedTime = 0.95f;
                prettySparkleParticle2.TimeToLive = num;
                prettySparkleParticle2.FadeOutEnd = num;
                prettySparkleParticle2.FadeInEnd = num / 2f;
                prettySparkleParticle2.FadeOutStart = num / 2f;
                prettySparkleParticle2.AdditiveAmount = 0.35f;
                prettySparkleParticle2.Velocity = vector2.RotatedBy(1.5707963705062866, default(Vector2)) * 0.5f;
                prettySparkleParticle2.DrawVerticalAxis = false;
                Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle2);
            }
            for (float num6 = 0f; num6 < 4f; num6 += 1f)
            {
                PrettySparkleParticle prettySparkleParticle3 = ParticleOrchestrator._poolPrettySparkle.RequestParticle();
                Vector2 vector3 = (1.5707964f * num6 + num2).ToRotationVector2() * 4f;
                prettySparkleParticle3.ColorTint = new Color(0.2f, 1f, 0.2f, 1f);
                prettySparkleParticle3.LocalPosition = settings.PositionInWorld;
                prettySparkleParticle3.Rotation = vector3.ToRotation();
                prettySparkleParticle3.Scale = new Vector2(num3, 0.5f) * 0.7f;
                prettySparkleParticle3.FadeInNormalizedTime = 5E-06f;
                prettySparkleParticle3.FadeOutNormalizedTime = 0.95f;
                prettySparkleParticle3.TimeToLive = num;
                prettySparkleParticle3.FadeOutEnd = num;
                prettySparkleParticle3.FadeInEnd = num / 2f;
                prettySparkleParticle3.FadeOutStart = num / 2f;
                prettySparkleParticle3.Velocity = vector3 * 0.2f;
                prettySparkleParticle3.DrawVerticalAxis = false;
                if (num6 % 2f == 1f)
                {
                    prettySparkleParticle3.Scale *= 1.5f;
                    prettySparkleParticle3.Velocity *= 2f;
                }
                Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle3);
                for (int i = 0; i < 1; i++)
                {
                    Dust dust = Dust.NewDustPerfect(settings.PositionInWorld, 107, new Vector2?(vector3.RotatedBy((double)(Main.rand.NextFloatDirection() * 6.2831855f * 0.025f), default(Vector2)) * Main.rand.NextFloat()), 0, default(Color), 1f);
                    dust.noGravity = true;
                    dust.scale = 0.8f;
                    Dust dust2 = Dust.NewDustPerfect(settings.PositionInWorld, 107, new Vector2?(-vector3.RotatedBy((double)(Main.rand.NextFloatDirection() * 6.2831855f * 0.025f), default(Vector2)) * Main.rand.NextFloat()), 0, default(Color), 1f);
                    dust2.noGravity = true;
                    dust2.scale = 1.4f;
                }
            }
        }
References Terraria.GameContent.Drawing.ParticleOrchestrator._poolPrettySparkle, Terraria.Graphics.Renderers.ParticleRenderer.Add(), Microsoft.Xna.Framework.Graphics.Color, System.E, Terraria.GameContent.Drawing.ParticleOrchestraSettings.MovementVector, Terraria.Dust.NewDustPerfect(), Terraria.Main.ParticleSystem_World_OverPlayers, Terraria.GameContent.Drawing.ParticleOrchestraSettings.PositionInWorld, Terraria.Main.rand, Terraria.Graphics.Renderers.ParticlePool< T >.RequestParticle(), and Microsoft.Xna.Framework.Graphics.Vector2.
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnParticlesDirect().