Terraria Decompiled: Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_MoonLordWhipEye
Spawn_MoonLordWhipEye()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_MoonLordWhipEye (ParticleOrchestraSettings settings) inline static private
Definition at line 1355 of file ParticleOrchestrator.cs.
        {
            Asset<Texture2D> asset = TextureAssets.Extra[270];
            if (!asset.IsLoaded)
            {
                return;
            }
            float num = 1f;
            float num2 = 45f;
            float num3 = 6.2831855f * Main.rand.NextFloat();
            FadingParticle fadingParticle = ParticleOrchestrator._poolFading.RequestParticle();
            fadingParticle.SetBasicInfo(asset, null, Vector2.Zero, Vector2.Zero);
            fadingParticle.SetTypeInfo(num2, true);
            fadingParticle.ColorTint = new Color(255, 255, 255, 0);
            fadingParticle.LocalPosition = settings.PositionInWorld + num3.ToRotationVector2() * num * num2 * 0.5f;
            fadingParticle.Rotation = 0f;
            fadingParticle.FadeInNormalizedTime = 0.01f;
            fadingParticle.FadeOutNormalizedTime = 0.1f;
            fadingParticle.Velocity = settings.MovementVector * 0.05f;
            fadingParticle.AccelerationPerFrame = -(settings.MovementVector * 0.25f) / num2;
            fadingParticle.Scale = new Vector2(1f, 1f) * (0.7f + 0.45f * Main.rand.NextFloat());
            Main.ParticleSystem_World_BehindPlayers.Add(fadingParticle);
        }
References Terraria.GameContent.Drawing.ParticleOrchestrator._poolFading, Terraria.Graphics.Renderers.ParticleRenderer.Add(), Microsoft.Xna.Framework.Graphics.Color, Terraria.GameContent.TextureAssets.Extra, ReLogic.Content.Asset< T >.IsLoaded, Terraria.Main.ParticleSystem_World_BehindPlayers, Terraria.Main.rand, Terraria.Graphics.Renderers.ParticlePool< T >.RequestParticle(), Terraria.Graphics.Renderers.ABasicParticle.SetBasicInfo(), Terraria.Graphics.Renderers.FadingParticle.SetTypeInfo(), Microsoft.Xna.Framework.Graphics.Vector2, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnParticlesDirect().