Terraria Decompiled: Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnHelper_SpawnInLine
SpawnHelper_SpawnInLine()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnHelper_SpawnInLine (ParticleOrchestraSettings settings, Action< Vector2, Vector2 > effectsPerStep = null) inline static private
Definition at line 1468 of file ParticleOrchestrator.cs.
        {
            if (effectsPerStep == null)
            {
                return;
            }
            Vector2 positionInWorld = settings.PositionInWorld;
            Vector2 movementVector = settings.MovementVector;
            Vector2 vector = (positionInWorld - movementVector).SafeNormalize(Vector2.Zero) * ((float)settings.UniqueInfoPiece / 1000f);
            float num = (positionInWorld - movementVector).Length();
            float num2 = vector.Length();
            if (num2 < 4f)
            {
                num2 = 4f;
            }
            for (float num3 = 0f; num3 < num; num3 += num2)
            {
                float num4 = num3 / num;
                Vector2 vector2 = Vector2.Lerp(movementVector, positionInWorld, num4);
                effectsPerStep(vector2, vector);
            }
        }
References Microsoft.Xna.Framework.Vector2.Length(), Microsoft.Xna.Framework.Vector2.Lerp(), Terraria.GameContent.Drawing.ParticleOrchestraSettings.MovementVector, Terraria.GameContent.Drawing.ParticleOrchestraSettings.PositionInWorld, Terraria.GameContent.Drawing.ParticleOrchestraSettings.UniqueInfoPiece, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_HeatRay(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_MagnetSphereBolt(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_Shadowbeam(), and Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_UFOLaser().