Terraria Decompiled: Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_LakeSparkle
Spawn_LakeSparkle()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_LakeSparkle (ParticleOrchestraSettings settings) inline static private
Definition at line 772 of file ParticleOrchestrator.cs.
        {
            FadingParticle fadingParticle = ParticleOrchestrator._poolFading.RequestParticle();
            Vector2 vector = Vector2.UnitY * (-0.1f - 0.4f * Main.rand.NextFloat());
            vector = settings.MovementVector / 60f;
            fadingParticle.SetBasicInfo(TextureAssets.Star[0], null, Vector2.Zero, settings.PositionInWorld);
            float num = 50f + 90f * Main.rand.NextFloat();
            fadingParticle.SetTypeInfo(num, true);
            fadingParticle.AccelerationPerFrame = vector / num;
            fadingParticle.ColorTint = new Color(255, 255, 255, 0) * Main.rand.NextFloat();
            fadingParticle.FadeInNormalizedTime = 0.45f;
            fadingParticle.FadeOutNormalizedTime = 0.45f;
            fadingParticle.Rotation = Main.rand.NextFloat() * 6.2831855f;
            fadingParticle.RotationVelocity = Main.rand.NextFloatDirection() * 6.2831855f / 32f;
            fadingParticle.RotationVelocity *= Utils.Clamp<float>(settings.MovementVector.Length() / 32f, 0f, 1f);
            fadingParticle.Scale = Vector2.One * (0.5f + 0.5f * Main.rand.NextFloat());
            Main.ParticleSystem_World_BehindPlayers.Add(fadingParticle);
        }
References Terraria.GameContent.Drawing.ParticleOrchestrator._poolFading, Terraria.Graphics.Renderers.ParticleRenderer.Add(), Terraria.Utils.Clamp(), Microsoft.Xna.Framework.Graphics.Color, Microsoft.Xna.Framework.Vector2.Length(), Terraria.GameContent.Drawing.ParticleOrchestraSettings.MovementVector, Terraria.Main.ParticleSystem_World_BehindPlayers, Terraria.GameContent.Drawing.ParticleOrchestraSettings.PositionInWorld, Terraria.Main.rand, Terraria.Graphics.Renderers.ParticlePool< T >.RequestParticle(), Terraria.Graphics.Renderers.ABasicParticle.SetBasicInfo(), Terraria.Graphics.Renderers.FadingParticle.SetTypeInfo(), Terraria.GameContent.TextureAssets.Star, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnParticlesDirect().