Terraria Decompiled: XPT.Core.Audio.MP3Sharp.Decoding.Bitstream.SyncHeader
SyncHeader()
int XPT.Core.Audio.MP3Sharp.Decoding.Bitstream.SyncHeader (sbyte syncmode) inline package
Definition at line 150 of file Bitstream.cs.
        {
            if (this.ReadBytes(this._SyncBuffer, 0, 3) != 3)
            {
                throw this.NewBitstreamException(260, null);
            }
            int num = (((int)this._SyncBuffer[0] << 16) & 16711680) | (((int)this._SyncBuffer[1] << 8) & 65280) | ((int)this._SyncBuffer[2] & 255);
            for (;;)
            {
                num <<= 8;
                if (this.ReadBytes(this._SyncBuffer, 3, 1) != 1)
                {
                    break;
                }
                num |= (int)this._SyncBuffer[3] & 255;
                bool flag = this.IsSyncMark(num, (int)syncmode, this._SyncWord);
                if (flag)
                {
                    return num;
                }
            }
            throw this.NewBitstreamException(260, null);
        }
References XPT.Core.Audio.MP3Sharp.Decoding.Bitstream._SyncBuffer, XPT.Core.Audio.MP3Sharp.Decoding.Bitstream._SyncWord, int, XPT.Core.Audio.MP3Sharp.Decoding.Bitstream.IsSyncMark(), XPT.Core.Audio.MP3Sharp.Decoding.Bitstream.NewBitstreamException(), and XPT.Core.Audio.MP3Sharp.Decoding.Bitstream.ReadBytes().
Referenced by XPT.Core.Audio.MP3Sharp.Decoding.Header.read_header().