Terraria Decompiled: Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_RainbowBoulder4
Spawn_RainbowBoulder4()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_RainbowBoulder4 (ParticleOrchestraSettings settings, bool pet = false) inline static private
Definition at line 888 of file ParticleOrchestrator.cs.
        {
            if (!pet)
            {
                SoundEngine.PlaySound(SoundID.RainbowBoulder, (int)settings.PositionInWorld.X, (int)settings.PositionInWorld.Y, 0f, 1f);
            }
            int num = 14;
            int num2 = 20;
            if (pet)
            {
                num = 8;
                num2 = 10;
            }
            for (int i = 0; i < num; i++)
            {
                int num3 = Dust.NewDust(settings.PositionInWorld, 0, 0, 66, 0f, 0f, 100, Main.hslToRgb(Main.rand.NextFloat(), 1f, 0.5f, byte.MaxValue), pet ? 1.2f : 1.7f);
                Main.dust[num3].noGravity = true;
                if (pet)
                {
                    Main.dust[num3].velocity *= 2f;
                    Main.dust[num3].position = settings.PositionInWorld + Main.rand.NextVector2Circular(30f, 30f);
                }
                else
                {
                    Main.dust[num3].velocity *= 3f;
                    Main.dust[num3].position = settings.PositionInWorld + Main.rand.NextVector2Circular(30f, 30f);
                }
            }
            int num4 = 20;
            if (pet)
            {
                num4 = 12;
            }
            Rectangle rectangle = Utils.CenteredRectangle(settings.PositionInWorld, new Vector2((float)num4, (float)num4));
            float num5 = settings.MovementVector.ToRotation() + 1.5707964f;
            for (float num6 = 0f; num6 < (float)num2; num6 += 1f)
            {
                PrettySparkleParticle prettySparkleParticle = ParticleOrchestrator._poolPrettySparkle.RequestParticle();
                int num7 = Main.rand.Next(20, 40);
                prettySparkleParticle.ColorTint = Main.hslToRgb(Main.rand.NextFloat(), 1f, 0.5f, 0);
                prettySparkleParticle.LocalPosition = Main.rand.NextVector2FromRectangle(rectangle);
                prettySparkleParticle.Rotation = 1.5707964f + num5;
                prettySparkleParticle.Scale = new Vector2(1f + Main.rand.NextFloat() * 1f, 0.7f + Main.rand.NextFloat() * 0.7f);
                prettySparkleParticle.Velocity = new Vector2(0f, -1f).RotatedBy((double)num5, default(Vector2));
                prettySparkleParticle.FadeInNormalizedTime = 5E-06f;
                prettySparkleParticle.FadeOutNormalizedTime = 0.95f;
                prettySparkleParticle.TimeToLive = (float)num7;
                prettySparkleParticle.FadeOutEnd = (float)num7;
                prettySparkleParticle.FadeInEnd = (float)(num7 / 2);
                prettySparkleParticle.FadeOutStart = (float)(num7 / 2);
                prettySparkleParticle.AdditiveAmount = 0.35f;
                prettySparkleParticle.DrawVerticalAxis = false;
                Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle);
                PrettySparkleParticle prettySparkleParticle2 = ParticleOrchestrator._poolPrettySparkle.RequestParticle();
                prettySparkleParticle2.ColorTint = new Color(255, 255, 255, 0);
                prettySparkleParticle2.LocalPosition = Main.rand.NextVector2FromRectangle(rectangle);
                prettySparkleParticle2.Rotation = 1.5707964f + num5;
                prettySparkleParticle2.Scale = prettySparkleParticle.Scale * 0.5f;
                prettySparkleParticle2.Velocity = new Vector2(0f, 1f).RotatedBy((double)num5, default(Vector2));
                prettySparkleParticle2.FadeInNormalizedTime = 5E-06f;
                prettySparkleParticle2.FadeOutNormalizedTime = 0.95f;
                prettySparkleParticle2.TimeToLive = (float)num7;
                prettySparkleParticle2.FadeOutEnd = (float)num7;
                prettySparkleParticle2.FadeInEnd = (float)(num7 / 2);
                prettySparkleParticle2.FadeOutStart = (float)(num7 / 2);
                prettySparkleParticle2.AdditiveAmount = 1f;
                prettySparkleParticle2.DrawVerticalAxis = false;
                Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle2);
            }
        }
References Terraria.GameContent.Drawing.ParticleOrchestrator._poolPrettySparkle, Terraria.Graphics.Renderers.ParticleRenderer.Add(), Terraria.Utils.CenteredRectangle(), Microsoft.Xna.Framework.Graphics.Color, Terraria.Main.dust, System.E, Terraria.Main.hslToRgb(), Terraria.GameContent.Drawing.ParticleOrchestraSettings.MovementVector, Terraria.Dust.NewDust(), Terraria.Dust.noGravity, Terraria.Main.ParticleSystem_World_OverPlayers, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Dust.position, Terraria.GameContent.Drawing.ParticleOrchestraSettings.PositionInWorld, Terraria.ID.SoundID.RainbowBoulder, Terraria.Main.rand, Terraria.Graphics.Renderers.ParticlePool< T >.RequestParticle(), Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Dust.velocity, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnParticlesDirect().