Terraria Decompiled: XPT.Core.Audio.MP3Sharp.Decoding.Bitstream.IsSyncMark
IsSyncMark()
bool XPT.Core.Audio.MP3Sharp.Decoding.Bitstream.IsSyncMark (int headerstring, int syncmode, int word) inline package
Definition at line 175 of file Bitstream.cs.
        {
            bool flag;
            if (syncmode == 0)
            {
                flag = ((long)headerstring & (long)((ulong)(-2097152))) == (long)((ulong)(-2097152));
            }
            else
            {
                flag = ((long)headerstring & (long)((ulong)(-2097152))) == (long)((ulong)(-2097152)) && (headerstring & 192) == 192 == this._SingleChMode;
            }
            if (flag)
            {
                flag = (SupportClass.URShift(headerstring, 10) & 3) != 3;
            }
            if (flag)
            {
                flag = (SupportClass.URShift(headerstring, 17) & 3) != 0;
            }
            if (flag)
            {
                flag = (SupportClass.URShift(headerstring, 19) & 3) != 1;
                if (!flag)
                {
                    Console.WriteLine("INVALID VERSION DETECTED");
                }
            }
            return flag;
        }
References XPT.Core.Audio.MP3Sharp.Decoding.Bitstream._SingleChMode, long, XPT.Core.Audio.MP3Sharp.Support.SupportClass.URShift(), and System.Console.WriteLine().
Referenced by XPT.Core.Audio.MP3Sharp.Decoding.Bitstream.IsSyncCurrentPosition(), and XPT.Core.Audio.MP3Sharp.Decoding.Bitstream.SyncHeader().