Terraria Decompiled: Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ItemTransfer
Spawn_ItemTransfer()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ItemTransfer (ParticleOrchestraSettings settings) inline static private
Definition at line 2172 of file ParticleOrchestrator.cs.
        {
            Vector2 positionInWorld = settings.PositionInWorld;
            Vector2 vector = settings.PositionInWorld + settings.MovementVector;
            int num = settings.UniqueInfoPiece & 16777215;
            BitsByte bitsByte = (byte)(settings.UniqueInfoPiece >> 24);
            bool flag = bitsByte[0];
            bool flag2 = bitsByte[1];
            bool flag3 = bitsByte[2];
            bool flag4 = bitsByte[3];
            Item item;
            if (!ContentSamples.ItemsByType.TryGetValue(num, out item))
            {
                return;
            }
            if (item.IsAir)
            {
                return;
            }
            num = item.type;
            int num2 = Main.rand.Next(60, 80);
            Chest.AskForChestToEatItem(vector + new Vector2(-8f, -8f), num2 + 10);
            Vector2 vector2 = Main.rand.NextVector2Square(-1f, 1f);
            ItemTransferParticle itemTransferParticle = ParticleOrchestrator._poolItemTransfer.RequestParticle();
            itemTransferParticle.Prepare(num, num2, positionInWorld, vector, flag ? (vector2 * 24f) : Vector2.Zero, flag2 ? (vector2 * 8f) : Vector2.Zero, flag3, flag4, false, 1);
            Main.ParticleSystem_World_OverPlayers.Add(itemTransferParticle);
        }
References Terraria.GameContent.Drawing.ParticleOrchestrator._poolItemTransfer, Terraria.Graphics.Renderers.ParticleRenderer.Add(), Terraria.Chest.AskForChestToEatItem(), System.item, Terraria.ID.ContentSamples.ItemsByType, Terraria.GameContent.Drawing.ParticleOrchestraSettings.MovementVector, Terraria.Main.ParticleSystem_World_OverPlayers, Terraria.GameContent.Drawing.ParticleOrchestraSettings.PositionInWorld, Terraria.Graphics.Renderers.ItemTransferParticle.Prepare(), Terraria.Main.rand, Terraria.Graphics.Renderers.ParticlePool< T >.RequestParticle(), Terraria.GameContent.Drawing.ParticleOrchestraSettings.UniqueInfoPiece, Microsoft.Xna.Framework.Graphics.Vector2, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnParticlesDirect().