Terraria Decompiled: Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_CattivaHit
Spawn_CattivaHit()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_CattivaHit (ParticleOrchestraSettings settings) inline static private
Definition at line 3212 of file ParticleOrchestrator.cs.
        {
            float num = Main.rand.NextFloat() * 6.2831855f;
            float num2 = 6f;
            Vector2 vector = new Vector2(0.7f);
            for (float num3 = 0f; num3 < 1f; num3 += 1f / num2)
            {
                float num4 = 6.2831855f * num3 + num + Main.rand.NextFloatDirection() * 0.25f;
                Vector2 vector2 = 4.5f * vector;
                float num5 = 16f;
                Vector2 vector3 = Main.rand.NextVector2Circular(6f, 6f) * vector;
                Color color = Color.Lerp(Color.Gold, Color.Orange, Main.rand.NextFloat());
                if (Main.rand.Next(2) == 0)
                {
                    color = Color.Lerp(Color.White, Color.Orange, Main.rand.NextFloat());
                }
                PrettySparkleParticle prettySparkleParticle = ParticleOrchestrator._poolPrettySparkle.RequestParticle();
                prettySparkleParticle.Velocity = num4.ToRotationVector2() * vector2;
                prettySparkleParticle.AccelerationPerFrame = num4.ToRotationVector2() * -(vector2 / num5) * 0.5f;
                prettySparkleParticle.ColorTint = color;
                prettySparkleParticle.LocalPosition = settings.PositionInWorld + vector3;
                prettySparkleParticle.Rotation = num4;
                prettySparkleParticle.Scale = vector * (Main.rand.NextFloat() * 0.7f + 0.1f);
                prettySparkleParticle.DrawVerticalAxis = false;
                prettySparkleParticle.FadeInEnd = 0.1f;
                prettySparkleParticle.FadeOutNormalizedTime = 0.5f;
                prettySparkleParticle.TimeToLive = num5;
                PrettySparkleParticle prettySparkleParticle2 = prettySparkleParticle;
                prettySparkleParticle2.Scale.X = prettySparkleParticle2.Scale.X * 4f;
                Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle);
            }
        }
References Terraria.GameContent.Drawing.ParticleOrchestrator._poolPrettySparkle, Terraria.Graphics.Renderers.ParticleRenderer.Add(), Microsoft.Xna.Framework.Color.Gold, Microsoft.Xna.Framework.Color.Lerp(), Microsoft.Xna.Framework.Color.Orange, Terraria.Main.ParticleSystem_World_OverPlayers, Terraria.Main.rand, Terraria.Graphics.Renderers.ParticlePool< T >.RequestParticle(), Microsoft.Xna.Framework.Graphics.Vector2, and Microsoft.Xna.Framework.Color.White.
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnParticlesDirect().