Terraria Decompiled: Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnParticlesDirect
SpawnParticlesDirect()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnParticlesDirect (ParticleOrchestraType type, ParticleOrchestraSettings settings) inline static
Definition at line 148 of file ParticleOrchestrator.cs.
        {
            if (Main.netMode == 2)
            {
                return;
            }
            switch (type)
            {
            case ParticleOrchestraType.Keybrand:
                ParticleOrchestrator.Spawn_Keybrand(settings);
                return;
            case ParticleOrchestraType.FlameWaders:
                ParticleOrchestrator.Spawn_FlameWaders(settings);
                return;
            case ParticleOrchestraType.StellarTune:
                ParticleOrchestrator.Spawn_StellarTune(settings);
                return;
            case ParticleOrchestraType.WallOfFleshGoatMountFlames:
                ParticleOrchestrator.Spawn_WallOfFleshGoatMountFlames(settings);
                return;
            case ParticleOrchestraType.BlackLightningHit:
                ParticleOrchestrator.Spawn_BlackLightningHit(settings);
                return;
            case ParticleOrchestraType.RainbowRodHit:
                ParticleOrchestrator.Spawn_RainbowRodHit(settings);
                return;
            case ParticleOrchestraType.BlackLightningSmall:
                ParticleOrchestrator.Spawn_BlackLightningSmall(settings);
                return;
            case ParticleOrchestraType.StardustPunch:
                ParticleOrchestrator.Spawn_StardustPunch(settings);
                return;
            case ParticleOrchestraType.PrincessWeapon:
                ParticleOrchestrator.Spawn_PrincessWeapon(settings);
                return;
            case ParticleOrchestraType.PaladinsHammer:
                ParticleOrchestrator.Spawn_PaladinsHammer(settings);
                return;
            case ParticleOrchestraType.NightsEdge:
                ParticleOrchestrator.Spawn_NightsEdge(settings);
                return;
            case ParticleOrchestraType.SilverBulletSparkle:
                ParticleOrchestrator.Spawn_SilverBulletSparkle(settings);
                return;
            case ParticleOrchestraType.TrueNightsEdge:
                ParticleOrchestrator.Spawn_TrueNightsEdge(settings);
                return;
            case ParticleOrchestraType.Excalibur:
                ParticleOrchestrator.Spawn_Excalibur(settings);
                return;
            case ParticleOrchestraType.TrueExcalibur:
                ParticleOrchestrator.Spawn_TrueExcalibur(settings);
                return;
            case ParticleOrchestraType.TerraBlade:
                ParticleOrchestrator.Spawn_TerraBlade(settings);
                return;
            case ParticleOrchestraType.ChlorophyteLeafCrystalPassive:
                ParticleOrchestrator.Spawn_LeafCrystalPassive(settings);
                return;
            case ParticleOrchestraType.ChlorophyteLeafCrystalShot:
                ParticleOrchestrator.Spawn_LeafCrystalShot(settings);
                return;
            case ParticleOrchestraType.BestReforge:
                ParticleOrchestrator.Spawn_BestReforge(settings);
                return;
            case ParticleOrchestraType.PetExchange:
                ParticleOrchestrator.Spawn_PetExchange(settings);
                return;
            case ParticleOrchestraType.SlapHand:
                ParticleOrchestrator.Spawn_SlapHand(settings);
                return;
            case ParticleOrchestraType.FlyMeal:
                ParticleOrchestrator.Spawn_FlyMeal(settings);
                return;
            case ParticleOrchestraType.VampireOnFire:
                ParticleOrchestrator.Spawn_VampireOnFire(settings);
                return;
            case ParticleOrchestraType.GasTrap:
                ParticleOrchestrator.Spawn_GasTrap(settings);
                return;
            case ParticleOrchestraType.ItemTransfer:
                ParticleOrchestrator.Spawn_ItemTransfer(settings);
                return;
            case ParticleOrchestraType.ShimmerArrow:
                ParticleOrchestrator.Spawn_ShimmerArrow(settings);
                return;
            case ParticleOrchestraType.TownSlimeTransform:
                ParticleOrchestrator.Spawn_TownSlimeTransform(settings);
                return;
            case ParticleOrchestraType.LoadoutChange:
                ParticleOrchestrator.Spawn_LoadOutChange(settings);
                return;
            case ParticleOrchestraType.ShimmerBlock:
                ParticleOrchestrator.Spawn_ShimmerBlock(settings);
                return;
            case ParticleOrchestraType.Digestion:
                ParticleOrchestrator.Spawn_Digestion(settings);
                return;
            case ParticleOrchestraType.WaffleIron:
                ParticleOrchestrator.Spawn_WaffleIron(settings);
                return;
            case ParticleOrchestraType.PooFly:
                ParticleOrchestrator.Spawn_PooFly(settings);
                return;
            case ParticleOrchestraType.ShimmerTownNPC:
                ParticleOrchestrator.Spawn_ShimmerTownNPC(settings);
                return;
            case ParticleOrchestraType.ShimmerTownNPCSend:
                ParticleOrchestrator.Spawn_ShimmerTownNPCSend(settings);
                return;
            case ParticleOrchestraType.DeadCellsMushroomBoiExplosion:
                ParticleOrchestrator.Spawn_DeadCellsMushroomBoiExplosion(settings);
                return;
            case ParticleOrchestraType.DeadCellsDownDashExplosion:
                ParticleOrchestrator.Spawn_DeadCellsDownDashExplosion(settings);
                return;
            case ParticleOrchestraType.DeadCellsBarnacleShotFiring:
                ParticleOrchestrator.Spawn_DeadCellsBarnacleShotFiring(settings);
                return;
            case ParticleOrchestraType.BlueLightningSmall:
                ParticleOrchestrator.Spawn_BlueLightningSmall(settings);
                return;
            case ParticleOrchestraType.ShadowOrbExplosion:
                ParticleOrchestrator.Spawn_ShadowOrbExplosion(settings);
                return;
            case ParticleOrchestraType.UFOLaser:
                ParticleOrchestrator.Spawn_UFOLaser(settings);
                return;
            case ParticleOrchestraType.DeadCellsBeheadedEffect:
                ParticleOrchestrator.Spawn_DeadCellsHeadEffect(settings);
                return;
            case ParticleOrchestraType.DeadCellsFlint:
                ParticleOrchestrator.Spawn_DeadCellsFlint(settings);
                return;
            case ParticleOrchestraType.DeadCellsBarrelExplosion:
                ParticleOrchestrator.Spawn_DeadCellsBarrelExplosion(settings);
                return;
            case ParticleOrchestraType.DeadCellsMushroomBoiTargetFound:
                ParticleOrchestrator.Spawn_DeadCellsMushroomBoiTargetFound(settings);
                return;
            case ParticleOrchestraType.MoonLordWhipHit:
                ParticleOrchestrator.Spawn_MoonLordWhip(settings);
                return;
            case ParticleOrchestraType.MoonLordWhipEye:
                ParticleOrchestrator.Spawn_MoonLordWhipEye(settings);
                return;
            case ParticleOrchestraType.PlayerVoiceOverrideSound:
                ParticleOrchestrator.Spawn_PlayerVoiceOverrideSound(settings);
                return;
            case ParticleOrchestraType.RainbowBoulder1:
                ParticleOrchestrator.Spawn_RainbowBoulder1(settings);
                return;
            case ParticleOrchestraType.RainbowBoulder2:
                ParticleOrchestrator.Spawn_RainbowBoulder2(settings);
                return;
            case ParticleOrchestraType.RainbowBoulder3:
                ParticleOrchestrator.Spawn_RainbowBoulder3(settings);
                return;
            case ParticleOrchestraType.RainbowBoulder4:
                ParticleOrchestrator.Spawn_RainbowBoulder4(settings, false);
                return;
            case ParticleOrchestraType.FakeFish:
                ParticleOrchestrator.Spawn_FakeFish(settings, false);
                return;
            case ParticleOrchestraType.LakeSparkle:
                ParticleOrchestrator.Spawn_LakeSparkle(settings);
                return;
            case ParticleOrchestraType.NatureFly:
                ParticleOrchestrator.Spawn_NatureFly(settings);
                return;
            case ParticleOrchestraType.FakeFishJump:
                ParticleOrchestrator.Spawn_FakeFish(settings, true);
                return;
            case ParticleOrchestraType.ClassyCane:
                ParticleOrchestrator.Spawn_ClassyCane(settings);
                return;
            case ParticleOrchestraType.MagnetSphereBolt:
                ParticleOrchestrator.Spawn_MagnetSphereBolt(settings);
                return;
            case ParticleOrchestraType.HeatRay:
                ParticleOrchestrator.Spawn_HeatRay(settings);
                return;
            case ParticleOrchestraType.ShadowbeamHostile:
                ParticleOrchestrator.Spawn_Shadowbeam(settings, true);
                return;
            case ParticleOrchestraType.ShadowbeamFriendly:
                ParticleOrchestrator.Spawn_Shadowbeam(settings, false);
                return;
            case ParticleOrchestraType.RainbowBoulderPetBounce:
                ParticleOrchestrator.Spawn_RainbowBoulder4(settings, true);
                return;
            case ParticleOrchestraType.StormLightning:
                ParticleOrchestrator.Spawn_StormLightning(settings);
                return;
            case ParticleOrchestraType.StormlightningWindup:
                ParticleOrchestrator.Spawn_StormLightningWindup(settings);
                return;
            case ParticleOrchestraType.PaladinsShieldHit:
                ParticleOrchestrator.Spawn_PaladinsShieldHit(settings);
                return;
            case ParticleOrchestraType.HeroicisSetSpawnSound:
                ParticleOrchestrator.Spawn_HeroicisSetSpawnSound(settings);
                return;
            case ParticleOrchestraType.BlueLightningSmallLong:
                ParticleOrchestrator.Spawn_BlueLightningSmallLong(settings);
                return;
            case ParticleOrchestraType.InScreenDungeonSpawn:
                ParticleOrchestrator.Spawn_InScreenDungeonSpawn(settings);
                return;
            case ParticleOrchestraType.CattivaHit:
                ParticleOrchestrator.Spawn_CattivaHit(settings);
                return;
            case ParticleOrchestraType.PaladinsHammerShockwave:
                ParticleOrchestrator.Spawn_PaladinsHammerShockwave(settings);
                return;
            default:
                return;
            }
        }
References Terraria.Main.netMode, Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_BestReforge(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_BlackLightningHit(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_BlackLightningSmall(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_BlueLightningSmall(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_BlueLightningSmallLong(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_CattivaHit(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ClassyCane(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsBarnacleShotFiring(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsBarrelExplosion(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsDownDashExplosion(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsFlint(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsHeadEffect(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsMushroomBoiExplosion(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsMushroomBoiTargetFound(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_Digestion(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_Excalibur(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_FakeFish(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_FlameWaders(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_FlyMeal(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_GasTrap(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_HeatRay(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_HeroicisSetSpawnSound(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_InScreenDungeonSpawn(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ItemTransfer(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_Keybrand(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_LakeSparkle(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_LeafCrystalPassive(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_LeafCrystalShot(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_LoadOutChange(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_MagnetSphereBolt(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_MoonLordWhip(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_MoonLordWhipEye(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_NatureFly(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_NightsEdge(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_PaladinsHammer(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_PaladinsHammerShockwave(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_PaladinsShieldHit(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_PetExchange(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_PlayerVoiceOverrideSound(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_PooFly(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_PrincessWeapon(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_RainbowBoulder1(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_RainbowBoulder2(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_RainbowBoulder3(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_RainbowBoulder4(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_RainbowRodHit(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_Shadowbeam(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ShadowOrbExplosion(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ShimmerArrow(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ShimmerBlock(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ShimmerTownNPC(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ShimmerTownNPCSend(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_SilverBulletSparkle(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_SlapHand(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_StardustPunch(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_StellarTune(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_StormLightning(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_StormLightningWindup(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_TerraBlade(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_TownSlimeTransform(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_TrueExcalibur(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_TrueNightsEdge(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_UFOLaser(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_VampireOnFire(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_WaffleIron(), and Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_WallOfFleshGoatMountFlames().
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.BroadcastOrRequestParticleSpawn(), Terraria.GameContent.Drawing.ParticleOrchestrator.BroadcastParticleSpawn(), Terraria.GameContent.NetModules.NetParticlesModule.Deserialize(), and Terraria.GameContent.Drawing.ParticleOrchestrator.RequestParticleSpawn().