Terraria Decompiled: Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsBarnacleShotFiring
Spawn_DeadCellsBarnacleShotFiring()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsBarnacleShotFiring (ParticleOrchestraSettings settings) inline static private
Definition at line 2017 of file ParticleOrchestrator.cs.
        {
            Vector2 positionInWorld = settings.PositionInWorld;
            Vector2 movementVector = settings.MovementVector;
            SoundEngine.PlaySound(SoundID.Item95, positionInWorld, 0f, 1f);
            for (int i = 0; i < 15; i++)
            {
                Vector2 vector = positionInWorld + new Vector2((float)Main.rand.Next(-4, 4), (float)Main.rand.Next(-4, 4));
                Vector2 vector2 = movementVector.SafeNormalize(Vector2.Zero).RotatedByRandom(0.19634954631328583) * ((i >= 8) ? (3f + Main.rand.NextFloat() * 2f) : (7f + Main.rand.NextFloat() * 2f));
                Dust dust = Dust.NewDustPerfect(vector, 2, new Vector2?(vector2), 0, default(Color), 1f);
                dust.alpha = 50;
                dust.scale = 1.2f + (float)Main.rand.Next(-5, 5) * 0.01f;
                dust.fadeIn = 0.5f;
                dust.noGravity = true;
                dust.velocity = vector2;
            }
            for (int j = 0; j < 5; j++)
            {
                Vector2 vector3 = positionInWorld + new Vector2((float)Main.rand.Next(-4, 4), (float)Main.rand.Next(-4, 4));
                Vector2 vector4 = movementVector.SafeNormalize(Vector2.Zero).RotatedByRandom(0.09817477315664291) * (0f + Main.rand.NextFloat() * 8f);
                Dust dust2 = Dust.NewDustPerfect(vector3, 267, new Vector2?(vector4), 0, default(Color), 1f);
                dust2.alpha = 127;
                dust2.color = Color.Lerp(Color.DarkOliveGreen, Color.White, Main.rand.NextFloat() * 0.25f);
                dust2.fadeIn = 0.6f + Main.rand.NextFloat() * 0.6f;
                dust2.scale = 0.5f;
                dust2.noGravity = true;
                dust2.velocity = vector4;
            }
        }
References Microsoft.Xna.Framework.Color.DarkOliveGreen, Terraria.ID.SoundID.Item95, Microsoft.Xna.Framework.Color.Lerp(), Terraria.GameContent.Drawing.ParticleOrchestraSettings.MovementVector, Terraria.Dust.NewDustPerfect(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.GameContent.Drawing.ParticleOrchestraSettings.PositionInWorld, Terraria.Main.rand, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Color.White, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnParticlesDirect().