Terraria Decompiled: Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsMushroomBoiExplosion
Spawn_DeadCellsMushroomBoiExplosion()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsMushroomBoiExplosion (ParticleOrchestraSettings settings) inline static private
Definition at line 1910 of file ParticleOrchestrator.cs.
        {
            if (Main.rand.Next(2) == 0)
            {
                int num = Main.rand.Next(ParticleOrchestrator._mushBoiExplosionSounds.Length);
                ActiveSound activeSound = SoundEngine.GetActiveSound(ParticleOrchestrator._mushBoiExplosionSounds[num]);
                if (activeSound != null && activeSound.IsPlaying)
                {
                    activeSound.Stop();
                }
                ParticleOrchestrator._mushBoiExplosionSounds[num] = SoundEngine.PlayTrackedSound(SoundID.DeadCellsMushroomExplode, settings.PositionInWorld, default(SoundPlayOverrides));
            }
            BloodyExplosionParticle bloodyExplosionParticle = ParticleOrchestrator._poolBloodyExplosion.RequestParticle();
            Color color = new Color(255, 10, 10, 50) * 0.35f;
            bloodyExplosionParticle.ColorTint = (bloodyExplosionParticle.LightColorTint = color);
            bloodyExplosionParticle.LocalPosition = settings.PositionInWorld;
            bloodyExplosionParticle.TimeToLive = 10f;
            bloodyExplosionParticle.FadeInNormalizedTime = 0.3f;
            bloodyExplosionParticle.FadeOutNormalizedTime = 0.6f;
            bloodyExplosionParticle.Velocity = Vector2.Zero;
            bloodyExplosionParticle.InitialScale = 1f;
            Main.ParticleSystem_World_BehindPlayers.Add(bloodyExplosionParticle);
            Asset<Texture2D> asset = TextureAssets.Extra[269];
            Rectangle rectangle = new Rectangle(0, 0, 100, 100);
            Rectangle rectangle2 = new Rectangle(0, 101, 100, 100);
            Rectangle rectangle3 = new Rectangle(0, 202, 100, 100);
            Color color2 = new Color(255, 10, 10, 127) * 0.45f;
            Color color3 = new Color(255, 10, 10, 127) * 0.45f;
            float num2 = 15f;
            FadingParticle fadingParticle = ParticleOrchestrator._poolFading.RequestParticle();
            fadingParticle.SetBasicInfo(asset, new Rectangle?(rectangle), Vector2.Zero, settings.PositionInWorld);
            fadingParticle.SetTypeInfo(num2, true);
            fadingParticle.ColorTint = color3;
            fadingParticle.Rotation = Main.rand.NextFloat() * 6.2831855f;
            fadingParticle.RotationVelocity = 6.2831855f * (1f / num2) * 1f * Main.rand.NextFloatDirection();
            fadingParticle.RotationAcceleration = -fadingParticle.RotationVelocity * (1f / num2);
            fadingParticle.FadeInNormalizedTime = 0.01f;
            fadingParticle.FadeOutNormalizedTime = 0.1f;
            fadingParticle.Scale = Vector2.One * 0.6f;
            fadingParticle.ScaleVelocity = Vector2.One * (1.2f / num2);
            fadingParticle.ScaleAcceleration = fadingParticle.ScaleVelocity * (-1f / num2);
            Main.ParticleSystem_World_OverPlayers.Add(fadingParticle);
            FadingParticle fadingParticle2 = ParticleOrchestrator._poolFading.RequestParticle();
            fadingParticle2.SetBasicInfo(asset, new Rectangle?(rectangle2), Vector2.Zero, settings.PositionInWorld);
            fadingParticle2.SetTypeInfo(num2 * 0.8f, true);
            fadingParticle2.ColorTint = color3 * 0.25f;
            fadingParticle2.FadeInNormalizedTime = 0.1f;
            fadingParticle2.FadeOutNormalizedTime = 0.1f;
            fadingParticle2.Scale = Vector2.One * 0.3f;
            fadingParticle2.ScaleVelocity = Vector2.One * 6.5f * (1f / num2);
            fadingParticle2.ScaleAcceleration = fadingParticle2.ScaleVelocity * (-1f / num2);
            Main.ParticleSystem_World_OverPlayers.Add(fadingParticle2);
            FadingParticle fadingParticle3 = ParticleOrchestrator._poolFading.RequestParticle();
            fadingParticle3.SetBasicInfo(asset, new Rectangle?(rectangle2), Vector2.Zero, settings.PositionInWorld);
            fadingParticle3.SetTypeInfo(num2, true);
            fadingParticle3.ColorTint = color3 * 0.3f;
            fadingParticle3.FadeInNormalizedTime = 0.4f;
            fadingParticle3.FadeOutNormalizedTime = 0.5f;
            fadingParticle3.Scale = fadingParticle.Scale;
            fadingParticle3.ScaleVelocity = fadingParticle.ScaleVelocity;
            fadingParticle3.ScaleAcceleration = fadingParticle.ScaleAcceleration;
            Main.ParticleSystem_World_OverPlayers.Add(fadingParticle3);
            FadingParticle fadingParticle4 = ParticleOrchestrator._poolFading.RequestParticle();
            fadingParticle4.SetBasicInfo(asset, new Rectangle?(rectangle3), Vector2.Zero, settings.PositionInWorld);
            fadingParticle4.SetTypeInfo(num2, true);
            fadingParticle4.ColorTint = color3;
            fadingParticle4.FadeInNormalizedTime = 0.01f;
            fadingParticle4.FadeOutNormalizedTime = 0.7f;
            fadingParticle4.Scale = fadingParticle.Scale * 0.9f;
            fadingParticle4.ScaleVelocity = fadingParticle.ScaleVelocity * 1.5f;
            fadingParticle4.ScaleAcceleration = fadingParticle.ScaleAcceleration * 1.5f;
            Main.ParticleSystem_World_OverPlayers.Add(fadingParticle4);
            for (float num3 = 0f; num3 < 1f; num3 += 0.16666667f)
            {
                float num4 = 15f;
                float num5 = 6.2831855f * num3;
                FadingParticle fadingParticle5 = ParticleOrchestrator._poolFading.RequestParticle();
                fadingParticle5.SetBasicInfo(TextureAssets.Extra[89], null, num5.ToRotationVector2() * (4f + 7f * Main.rand.NextFloat()), settings.PositionInWorld + num5.ToRotationVector2() * (10f + 90f * Main.rand.NextFloat()));
                fadingParticle5.SetTypeInfo(num4, true);
                fadingParticle5.AccelerationPerFrame = fadingParticle5.Velocity * (-1f / num4);
                fadingParticle5.LocalPosition -= fadingParticle5.Velocity * 4f;
                fadingParticle5.ColorTint = color2;
                fadingParticle5.Rotation = num5 + 1.5707964f;
                fadingParticle5.FadeInNormalizedTime = 0.2f;
                fadingParticle5.FadeOutNormalizedTime = 0.3f;
                fadingParticle5.Scale = new Vector2(0.4f, 0.8f) * (0.6f + 0.6f * Main.rand.NextFloat());
                Main.ParticleSystem_World_BehindPlayers.Add(fadingParticle5);
            }
        }
References Terraria.GameContent.Drawing.ParticleOrchestrator._mushBoiExplosionSounds, Terraria.GameContent.Drawing.ParticleOrchestrator._poolBloodyExplosion, Terraria.GameContent.Drawing.ParticleOrchestrator._poolFading, Terraria.Graphics.Renderers.ParticleRenderer.Add(), Microsoft.Xna.Framework.Graphics.Color, Terraria.ID.SoundID.DeadCellsMushroomExplode, Terraria.GameContent.TextureAssets.Extra, Terraria.Audio.SoundEngine.GetActiveSound(), Terraria.Audio.ActiveSound.IsPlaying, Terraria.Main.ParticleSystem_World_BehindPlayers, Terraria.Main.ParticleSystem_World_OverPlayers, Terraria.Audio.SoundEngine.PlayTrackedSound(), Terraria.GameContent.Drawing.ParticleOrchestraSettings.PositionInWorld, Terraria.Main.rand, Terraria.Graphics.Renderers.ParticlePool< T >.RequestParticle(), Terraria.Graphics.Renderers.ABasicParticle.Scale, Terraria.Graphics.Renderers.ABasicParticle.ScaleAcceleration, Terraria.Graphics.Renderers.ABasicParticle.ScaleVelocity, Terraria.Graphics.Renderers.ABasicParticle.SetBasicInfo(), Terraria.Graphics.Renderers.FadingParticle.SetTypeInfo(), Terraria.Audio.ActiveSound.Stop(), Microsoft.Xna.Framework.Graphics.Vector2, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnParticlesDirect().