Terraria Decompiled: Terraria.GameContent.Drawing.ParticleOrchestrator.RequestParticleSpawn
RequestParticleSpawn()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.RequestParticleSpawn (bool clientOnly, ParticleOrchestraType type, ParticleOrchestraSettings settings, int? overrideInvokingPlayerIndex = null) inline static
Definition at line 23 of file ParticleOrchestrator.cs.
        {
            settings.IndexOfPlayerWhoInvokedThis = (byte)Main.myPlayer;
            if (overrideInvokingPlayerIndex != null)
            {
                settings.IndexOfPlayerWhoInvokedThis = (byte)overrideInvokingPlayerIndex.Value;
            }
            ParticleOrchestrator.SpawnParticlesDirect(type, settings);
            if (!clientOnly && Main.netMode == 1)
            {
                NetManager.Instance.SendToServer(NetParticlesModule.Serialize(type, settings));
            }
        }
References Terraria.Net.NetManager.Instance, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Net.NetManager.SendToServer(), Terraria.GameContent.NetModules.NetParticlesModule.Serialize(), and Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnParticlesDirect().
Referenced by Terraria.Projectile.AI(), Terraria.NPC.AI_001_Slimes(), Terraria.NPC.AI_007_TownEntities(), Terraria.Projectile.AI_067_FreakingPirates(), Terraria.Projectile.AI_067_FreakingPirates_TryJumpingToTarget(), Terraria.Projectile.AI_165_Whip(), Terraria.Projectile.AI_186_PrincessWeapon(), Terraria.Projectile.AI_198_Flint_EmitSpikes(), Terraria.Projectile.AI_203_StormLightning(), Terraria.NPC.ApplyEelWhipDoT(), Terraria.Projectile.Damage_PVE_Inner(), Terraria.Player.DoBootsEffect_PlaceFlamesOnTile(), Terraria.Player.DoDeadCellsBeheadedParticles(), Terraria.Player.DoDeadCellsGroundPoundEffect(), Terraria.GameContent.Drawing.TileDrawing.DrawTiles_EmitParticles(), Terraria.GameContent.Items.WhipTagEffect_DarkHarvest.EmitBlackLightningParticles(), Terraria.Projectile.EmitBlackLightningParticles(), Terraria.Projectile.FishingCheck_RollItemDrop(), Terraria.Projectile.HandleMovement(), Terraria.NPC.HitEffect(), Terraria.Player.Hurt(), Terraria.Player.ItemCheck_ApplyUseStyle(), Terraria.Player.ItemCheck_UsePlayerSoundOverrideAccessory(), Terraria.NPC.KeyBrandStrike(), Terraria.Projectile.LightningKillLambda_Step(), Terraria.Player.MakeFloorDust(), Terraria.GameContent.Items.WhipTagEffect_Kaleidoscope.OnTaggedHit(), Terraria.Player.ProcessHitAgainstNPC(), Terraria.Projectile.RainbowBoulder_HighlightNearbyTreasure(), Terraria.Projectile.RainbowBoulder_JumpToPosition(), Terraria.Main.ReforgeItemInReforgeSlot(), Terraria.Projectile.SpawnFakeFishInWater(), Terraria.Projectile.SpawnMoonLordWhipProc(), Terraria.Player.TryBouncingBlocks(), Terraria.Player.TrySwitchingLoadout(), Terraria.Player.TryToPoop(), Terraria.Graphics.Renderers.StormLightningParticle.Update(), Terraria.NPC.UpdateNPC_BuffApplyVFX(), and Terraria.Player.UpdateSunScorch().