Terraria Decompiled: Terraria.GameContent.Drawing.ParticleOrchestrator.MagnetFakeFish
MagnetFakeFish()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.MagnetFakeFish (Projectile proj, int searchedItemType) inline static
Definition at line 810 of file ParticleOrchestrator.cs.
        {
            using (IEnumerator<FakeFishParticle> enumerator = (from x in Main.ParticleSystem_World_BehindPlayers.Particles.OfType<FakeFishParticle>()
                orderby x.Position.Distance(proj.Center)
                select x).GetEnumerator())
            {
                while (enumerator.MoveNext())
                {
                    if (enumerator.Current.TryToMagnetizeTo(proj, searchedItemType))
                    {
                        return;
                    }
                }
            }
            using (IEnumerator<FakeFishParticle> enumerator = (from x in Main.ParticleSystem_World_BehindPlayers.Particles.OfType<FakeFishParticle>()
                orderby x.Position.Distance(proj.Center)
                select x).GetEnumerator())
            {
                while (enumerator.MoveNext())
                {
                    if (enumerator.Current.TryToMagnetizeTo(proj, -1))
                    {
                        break;
                    }
                }
            }
        }
References Terraria.Entity.Center, System.Collections.Generic.IEnumerator< out T >.Current, Microsoft.Xna.Framework.Vector2.Distance(), System.Collections.IEnumerator.MoveNext(), Terraria.Graphics.Renderers.ParticleRenderer.Particles, Terraria.Main.ParticleSystem_World_BehindPlayers, and Terraria.Graphics.Renderers.FakeFishParticle.Position.
Referenced by Terraria.Projectile.FishingCheck_RollItemDrop().