Terraria Decompiled: XPT.Core.Audio.MP3Sharp.Decoding.Crc16.AddBits
AddBits()
void XPT.Core.Audio.MP3Sharp.Decoding.Crc16.AddBits (int bitstring, int length) inline package
Definition at line 21 of file Crc16.cs.
        {
            int num = 1 << length - 1;
            do
            {
                if ((((int)this._CRC & 32768) == 0) ^ ((bitstring & num) == 0))
                {
                    this._CRC = (short)(this._CRC << 1);
                    this._CRC ^= Crc16.Polynomial;
                }
                else
                {
                    this._CRC = (short)(this._CRC << 1);
                }
            }
            while ((num = SupportClass.URShift(num, 1)) != 0);
        }
References XPT.Core.Audio.MP3Sharp.Decoding.Crc16._CRC, System.length, XPT.Core.Audio.MP3Sharp.Decoding.Crc16.Polynomial, and XPT.Core.Audio.MP3Sharp.Support.SupportClass.URShift().
Referenced by XPT.Core.Audio.MP3Sharp.Decoding.Header.read_header(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerI.SubbandLayer1.ReadAllocation(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerI.SubbandLayer1Stereo.ReadAllocation(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerII.SubbandLayer2.ReadAllocation(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerII.SubbandLayer2Stereo.ReadAllocation(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerII.SubbandLayer2.ReadScaleFactorSelection(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerII.SubbandLayer2IntensityStereo.ReadScaleFactorSelection(), and XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerII.SubbandLayer2Stereo.ReadScaleFactorSelection().