Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters
CreateObjectUsingCreatorWithParameters()
object Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters (JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor< object > creator, string id) inline private
Definition at line 1642 of file JsonSerializerInternalReader.cs.
        {
            ValidationUtils.ArgumentNotNull(creator, "creator");
            bool flag = contract.HasRequiredOrDefaultValueProperties || this.HasFlag(this.Serializer._defaultValueHandling, DefaultValueHandling.Populate);
            Type underlyingType = contract.UnderlyingType;
            if (this.TraceWriter != null && this.TraceWriter.LevelFilter >= 3)
            {
                string text = string.Join(", ", Enumerable.Select<JsonProperty, string>(contract.CreatorParameters, (JsonProperty p) => p.PropertyName));
                this.TraceWriter.Trace(3, JsonPosition.FormatMessage(reader as IJsonLineInfo, reader.Path, "Deserializing {0} using creator with parameters: {1}.".FormatWith(CultureInfo.InvariantCulture, contract.UnderlyingType, text)), null);
            }
            List<JsonSerializerInternalReader.CreatorPropertyContext> list = this.ResolvePropertyAndCreatorValues(contract, containerProperty, reader, underlyingType);
            if (flag)
            {
                using (IEnumerator<JsonProperty> enumerator = contract.Properties.GetEnumerator())
                {
                    while (enumerator.MoveNext())
                    {
                        JsonProperty property = enumerator.Current;
                        if (Enumerable.All<JsonSerializerInternalReader.CreatorPropertyContext>(list, (JsonSerializerInternalReader.CreatorPropertyContext p) => p.Property != property))
{
                            list.Add(new JsonSerializerInternalReader.CreatorPropertyContext
{
                                Property = property,
                                Name = property.PropertyName,
                                Presence = new JsonSerializerInternalReader.PropertyPresence?(JsonSerializerInternalReader.PropertyPresence.None)
                            });
                        }
                    }
                }
            }
            object[] array = new object[contract.CreatorParameters.Count];
            foreach (JsonSerializerInternalReader.CreatorPropertyContext creatorPropertyContext in list)
            {
                if (flag && creatorPropertyContext.Property != null && creatorPropertyContext.Presence == null)
                {
                    object value = creatorPropertyContext.Value;
                    JsonSerializerInternalReader.PropertyPresence propertyPresence;
                    if (value == null)
                    {
                        propertyPresence = JsonSerializerInternalReader.PropertyPresence.Null;
                    }
                    else if (value is string)
                    {
                        propertyPresence = (JsonSerializerInternalReader.CoerceEmptyStringToNull(creatorPropertyContext.Property.PropertyType, creatorPropertyContext.Property.PropertyContract, (string)value) ? JsonSerializerInternalReader.PropertyPresence.Null : JsonSerializerInternalReader.PropertyPresence.Value);
                    }
                    else
                    {
                        propertyPresence = JsonSerializerInternalReader.PropertyPresence.Value;
                    }
                    creatorPropertyContext.Presence = new JsonSerializerInternalReader.PropertyPresence?(propertyPresence);
                }
                JsonProperty jsonProperty = creatorPropertyContext.ConstructorProperty;
                if (jsonProperty == null && creatorPropertyContext.Property != null)
                {
                    jsonProperty = contract.CreatorParameters.ForgivingCaseSensitiveFind((JsonProperty p) => p.PropertyName, creatorPropertyContext.Property.UnderlyingName);
                }
                if (jsonProperty != null && !jsonProperty.Ignored)
                {
                    if (flag && (creatorPropertyContext.Presence == JsonSerializerInternalReader.PropertyPresence.None || creatorPropertyContext.Presence == JsonSerializerInternalReader.PropertyPresence.Null))
                    {
                        if (jsonProperty.PropertyContract == null)
{
                            jsonProperty.PropertyContract = this.GetContractSafe(jsonProperty.PropertyType);
                        }
                        if (this.HasFlag(jsonProperty.DefaultValueHandling.GetValueOrDefault(this.Serializer._defaultValueHandling), DefaultValueHandling.Populate))
{
                            creatorPropertyContext.Value = this.EnsureType(reader, jsonProperty.GetResolvedDefaultValue(), CultureInfo.InvariantCulture, jsonProperty.PropertyContract, jsonProperty.PropertyType);
                        }
                    }
                    int num = contract.CreatorParameters.IndexOf(jsonProperty);
                    array[num] = creatorPropertyContext.Value;
                    creatorPropertyContext.Used = true;
                }
            }
            object obj = creator(array);
            if (id != null)
            {
                this.AddReference(reader, id, obj);
            }
            this.OnDeserializing(reader, contract, obj);
            foreach (JsonSerializerInternalReader.CreatorPropertyContext creatorPropertyContext2 in list)
            {
                if (!creatorPropertyContext2.Used && creatorPropertyContext2.Property != null && !creatorPropertyContext2.Property.Ignored && !(creatorPropertyContext2.Presence == JsonSerializerInternalReader.PropertyPresence.None))
                {
                    JsonProperty property2 = creatorPropertyContext2.Property;
                    object value2 = creatorPropertyContext2.Value;
                    if (this.ShouldSetPropertyValue(property2, value2))
                    {
                        property2.ValueProvider.SetValue(obj, value2);
                        creatorPropertyContext2.Used = true;
                    }
                    else if (!property2.Writable && value2 != null)
                    {
                        JsonContract jsonContract = this.Serializer._contractResolver.ResolveContract(property2.PropertyType);
                        if (jsonContract.ContractType != JsonContractType.Array)
{
                            goto IL_04DF;
                        }
                        JsonArrayContract jsonArrayContract = (JsonArrayContract)jsonContract;
                        if (jsonArrayContract.CanDeserialize)
{
                            object value3 = property2.ValueProvider.GetValue(obj);
                            if (value3 != null)
{
                                IList list2;
                                if (!jsonArrayContract.ShouldCreateWrapper)
{
                                    list2 = (IList)value3;
                                }
                                else
{
                                    IList list3 = jsonArrayContract.CreateWrapper(value3);
                                    list2 = list3;
                                }
                                IList list4 = list2;
                                IEnumerable enumerable;
                                if (!jsonArrayContract.ShouldCreateWrapper)
{
                                    enumerable = (IList)value2;
                                }
                                else
{
                                    IList list3 = jsonArrayContract.CreateWrapper(value2);
                                    enumerable = list3;
                                }
                                using (IEnumerator enumerator3 = enumerable.GetEnumerator())
{
                                    while (enumerator3.MoveNext())
{
                                        object obj2 = enumerator3.Current;
                                        list4.Add(obj2);
                                    }
                                    goto IL_059D;
                                }
                                goto IL_04DF;
                            }
                        }
                        IL_059D:
                        creatorPropertyContext2.Used = true;
                        continue;
                        IL_04DF:
                        if (jsonContract.ContractType != JsonContractType.Dictionary)
{
                            goto IL_059D;
                        }
                        JsonDictionaryContract jsonDictionaryContract = (JsonDictionaryContract)jsonContract;
                        if (jsonDictionaryContract.IsReadOnlyOrFixedSize)
{
                            goto IL_059D;
                        }
                        object value4 = property2.ValueProvider.GetValue(obj);
                        if (value4 != null)
{
                            IDictionary dictionary;
                            if (!jsonDictionaryContract.ShouldCreateWrapper)
{
                                dictionary = (IDictionary)value4;
                            }
                            else
{
                                IDictionary dictionary2 = jsonDictionaryContract.CreateWrapper(value4);
                                dictionary = dictionary2;
                            }
                            IDictionary dictionary3 = dictionary;
                            IDictionary dictionary4;
                            if (!jsonDictionaryContract.ShouldCreateWrapper)
{
                                dictionary4 = (IDictionary)value2;
                            }
                            else
{
                                IDictionary dictionary2 = jsonDictionaryContract.CreateWrapper(value2);
                                dictionary4 = dictionary2;
                            }
                            using (IDictionaryEnumerator enumerator4 = dictionary4.GetEnumerator())
{
                                while (enumerator4.MoveNext())
{
                                    DictionaryEntry entry = enumerator4.Entry;
                                    dictionary3[entry.Key] = entry.Value;
                                }
                            }
                            goto IL_059D;
                        }
                        goto IL_059D;
                    }
                }
            }
            if (contract.ExtensionDataSetter != null)
            {
                foreach (JsonSerializerInternalReader.CreatorPropertyContext creatorPropertyContext3 in list)
                {
                    if (!creatorPropertyContext3.Used)
                    {
                        contract.ExtensionDataSetter(obj, creatorPropertyContext3.Name, creatorPropertyContext3.Value);
                    }
                }
            }
            if (flag)
            {
                foreach (JsonSerializerInternalReader.CreatorPropertyContext creatorPropertyContext4 in list)
                {
                    if (creatorPropertyContext4.Property != null)
                    {
                        this.EndProcessProperty(obj, reader, contract, reader.Depth, creatorPropertyContext4.Property, creatorPropertyContext4.Presence.GetValueOrDefault(), !creatorPropertyContext4.Used);
                    }
                }
            }
            this.OnDeserialized(reader, contract, obj);
            return obj;
        }
References Newtonsoft.Json.JsonSerializer._defaultValueHandling, Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(), Newtonsoft.Json.Serialization.JsonObjectContract.CreatorParameters, System.Collections.Generic.IEnumerator< out T >.Current, Newtonsoft.Json.JsonPosition.FormatMessage(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.HasFlag(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.Serialization.ITraceWriter.LevelFilter, System.list, System.Collections.IEnumerator.MoveNext(), System.Name, Newtonsoft.Json.JsonReader.Path, Newtonsoft.Json.Serialization.JsonObjectContract.Properties, Newtonsoft.Json.Property, Newtonsoft.Json.Serialization.JsonProperty.PropertyName, Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(), Newtonsoft.Json.Serialization.JsonSerializerInternalBase.Serializer, System.text, Newtonsoft.Json.Serialization.ITraceWriter.Trace(), Newtonsoft.Json.Serialization.JsonSerializerInternalBase.TraceWriter, and Newtonsoft.Json.Serialization.JsonContract.UnderlyingType.