Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize
Deserialize()
object Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (JsonReader reader, Type objectType, bool checkAdditionalContent) inline
Definition at line 105 of file JsonSerializerInternalReader.cs.
        {
            if (reader == null)
            {
                throw new ArgumentNullException("reader");
            }
            JsonContract contractSafe = this.GetContractSafe(objectType);
            object obj;
            try
            {
                JsonConverter converter = this.GetConverter(contractSafe, null, null, null);
                if (reader.TokenType == JsonToken.None && !this.ReadForType(reader, contractSafe, converter != null))
                {
                    if (contractSafe != null && !contractSafe.IsNullable)
                    {
                        throw JsonSerializationException.Create(reader, "No JSON content found and type '{0}' is not nullable.".FormatWith(CultureInfo.InvariantCulture, contractSafe.UnderlyingType));
                    }
                    obj = null;
                }
                else
                {
                    object obj2;
                    if (converter != null && converter.CanRead)
                    {
                        obj2 = this.DeserializeConvertable(converter, reader, objectType, null);
                    }
                    else
                    {
                        obj2 = this.CreateValueInternal(reader, objectType, contractSafe, null, null, null, null);
                    }
                    if (checkAdditionalContent)
                    {
                        while (reader.Read())
{
                            if (reader.TokenType != JsonToken.Comment)
{
                                throw JsonSerializationException.Create(reader, "Additional text found in JSON string after finishing deserializing object.");
                            }
                        }
                    }
                    obj = obj2;
                }
            }
            catch (Exception ex)
            {
                if (!base.IsErrorHandled(null, contractSafe, null, reader as IJsonLineInfo, reader.Path, ex))
                {
                    base.ClearErrorContext();
                    throw;
                }
                this.HandleError(reader, false, 0);
                obj = null;
            }
            return obj;
        }
References System.converter, Newtonsoft.Json.JsonSerializationException.Create(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.GetContractSafe(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.GetConverter(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.HandleError(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.Serialization.JsonContract.IsNullable, System.obj, Newtonsoft.Json.JsonReader.Path, Newtonsoft.Json.JsonReader.Read(), Newtonsoft.Json.JsonReader.TokenType, and Newtonsoft.Json.Serialization.JsonContract.UnderlyingType.
Referenced by Newtonsoft.Json.JsonSerializer.DeserializeInternal(), and Newtonsoft.Json.Serialization.JsonSerializerProxy.DeserializeInternal().