Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateDynamic
CreateDynamic()
object Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateDynamic (JsonReader reader, JsonDynamicContract contract, JsonProperty member, string id) inline private
Definition at line 1544 of file JsonSerializerInternalReader.cs.
        {
            if (!contract.IsInstantiable)
            {
                throw JsonSerializationException.Create(reader, "Could not create an instance of type {0}. Type is an interface or abstract class and cannot be instantiated.".FormatWith(CultureInfo.InvariantCulture, contract.UnderlyingType));
            }
            if (contract.DefaultCreator != null && (!contract.DefaultCreatorNonPublic || this.Serializer._constructorHandling == ConstructorHandling.AllowNonPublicDefaultConstructor))
            {
                IDynamicMetaObjectProvider dynamicMetaObjectProvider = (IDynamicMetaObjectProvider)contract.DefaultCreator.Invoke();
                if (id != null)
                {
                    this.AddReference(reader, id, dynamicMetaObjectProvider);
                }
                this.OnDeserializing(reader, contract, dynamicMetaObjectProvider);
                int depth = reader.Depth;
                bool flag = false;
                for (;;)
                {
                    JsonToken tokenType = reader.TokenType;
                    if (tokenType == JsonToken.PropertyName)
                    {
                        string text = reader.Value.ToString();
                        try
{
                            if (!reader.Read())
{
                                throw JsonSerializationException.Create(reader, "Unexpected end when setting {0}'s value.".FormatWith(CultureInfo.InvariantCulture, text));
                            }
                            JsonProperty closestMatchProperty = contract.Properties.GetClosestMatchProperty(text);
                            if (closestMatchProperty != null && closestMatchProperty.Writable && !closestMatchProperty.Ignored)
{
                                if (closestMatchProperty.PropertyContract == null)
{
                                    closestMatchProperty.PropertyContract = this.GetContractSafe(closestMatchProperty.PropertyType);
                                }
                                JsonConverter converter = this.GetConverter(closestMatchProperty.PropertyContract, closestMatchProperty.MemberConverter, null, null);
                                if (!this.SetPropertyValue(closestMatchProperty, converter, null, member, reader, dynamicMetaObjectProvider))
{
                                    reader.Skip();
                                }
                            }
                            else
{
                                Type type = (JsonTokenUtils.IsPrimitiveToken(reader.TokenType) ? reader.ValueType : typeof(IDynamicMetaObjectProvider));
                                JsonContract contractSafe = this.GetContractSafe(type);
                                JsonConverter converter2 = this.GetConverter(contractSafe, null, null, member);
                                object obj;
                                if (converter2 != null && converter2.CanRead)
{
                                    obj = this.DeserializeConvertable(converter2, reader, type, null);
                                }
                                else
{
                                    obj = this.CreateValueInternal(reader, type, contractSafe, null, null, member, null);
                                }
                                contract.TrySetMember(dynamicMetaObjectProvider, text, obj);
                            }
                            goto IL_0207;
                        }
                        catch (Exception ex)
{
                            if (base.IsErrorHandled(dynamicMetaObjectProvider, contract, text, reader as IJsonLineInfo, reader.Path, ex))
{
                                this.HandleError(reader, true, depth);
                                goto IL_0207;
                            }
                            throw;
                        }
                        goto IL_01E7;
                    }
                    if (tokenType != JsonToken.EndObject)
                    {
                        break;
                    }
                    goto IL_01E7;
                    IL_0207:
                    if (flag || !reader.Read())
                    {
                        goto IL_0215;
                    }
                    continue;
                    IL_01E7:
                    flag = true;
                    goto IL_0207;
                }
                throw JsonSerializationException.Create(reader, "Unexpected token when deserializing object: " + reader.TokenType);
                IL_0215:
                if (!flag)
                {
                    this.ThrowUnexpectedEndException(reader, contract, dynamicMetaObjectProvider, "Unexpected end when deserializing object.");
                }
                this.OnDeserialized(reader, contract, dynamicMetaObjectProvider);
                return dynamicMetaObjectProvider;
            }
            throw JsonSerializationException.Create(reader, "Unable to find a default constructor to use for type {0}.".FormatWith(CultureInfo.InvariantCulture, contract.UnderlyingType));
        }
References Newtonsoft.Json.Serialization.JsonSerializerInternalReader.AddReference(), Newtonsoft.Json.JsonConverter.CanRead, System.converter, Newtonsoft.Json.JsonSerializationException.Create(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(), Newtonsoft.Json.Serialization.JsonContract.DefaultCreator, Newtonsoft.Json.Serialization.JsonContract.DefaultCreatorNonPublic, Newtonsoft.Json.JsonReader.Depth, Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(), Newtonsoft.Json.Serialization.JsonPropertyCollection.GetClosestMatchProperty(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.GetContractSafe(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.GetConverter(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.HandleError(), Newtonsoft.Json.Serialization.JsonProperty.Ignored, System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.Serialization.JsonContract.IsInstantiable, Newtonsoft.Json.Utilities.JsonTokenUtils.IsPrimitiveToken(), Newtonsoft.Json.Serialization.JsonProperty.MemberConverter, System.obj, Newtonsoft.Json.Serialization.JsonSerializerInternalReader.OnDeserialized(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.OnDeserializing(), Newtonsoft.Json.JsonReader.Path, Newtonsoft.Json.Serialization.JsonDynamicContract.Properties, Newtonsoft.Json.Serialization.JsonProperty.PropertyContract, Newtonsoft.Json.Serialization.JsonProperty.PropertyType, Newtonsoft.Json.JsonReader.Read(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(), Newtonsoft.Json.JsonReader.Skip(), System.text, Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ThrowUnexpectedEndException(), Newtonsoft.Json.JsonReader.TokenType, Newtonsoft.Json.Serialization.JsonDynamicContract.TrySetMember(), Newtonsoft.Json.Serialization.JsonContract.UnderlyingType, Newtonsoft.Json.JsonReader.Value, and Newtonsoft.Json.Serialization.JsonProperty.Writable.
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject().