Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal
CreateValueInternal()
object Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, object existingValue) inline private
Definition at line 236 of file JsonSerializerInternalReader.cs.
        {
            if (contract != null && contract.ContractType == JsonContractType.Linq)
            {
                return this.CreateJToken(reader, contract);
            }
            for (;;)
            {
                switch (reader.TokenType)
                {
                case JsonToken.StartObject:
                    goto IL_006D;
                case JsonToken.StartArray:
                    goto IL_007F;
                case JsonToken.StartConstructor:
                    goto IL_00E4;
                case JsonToken.Comment:
                    if (!reader.Read())
                    {
                        goto Block_7;
                    }
                    continue;
                case JsonToken.Raw:
                    goto IL_012D;
                case JsonToken.Integer:
                case JsonToken.Float:
                case JsonToken.Boolean:
                case JsonToken.Date:
                case JsonToken.Bytes:
                    goto IL_008E;
                case JsonToken.String:
                    goto IL_00A3;
                case JsonToken.Null:
                case JsonToken.Undefined:
                    goto IL_0100;
                }
                break;
            }
            goto IL_013E;
            IL_006D:
            return this.CreateObject(reader, objectType, contract, member, containerContract, containerMember, existingValue);
            IL_007F:
            return this.CreateList(reader, objectType, contract, member, existingValue, null);
            IL_008E:
            return this.EnsureType(reader, reader.Value, CultureInfo.InvariantCulture, contract, objectType);
            IL_00A3:
            string text = (string)reader.Value;
            if (JsonSerializerInternalReader.CoerceEmptyStringToNull(objectType, contract, text))
            {
                return null;
            }
            if (objectType == typeof(byte[]))
            {
                return Convert.FromBase64String(text);
            }
            return this.EnsureType(reader, text, CultureInfo.InvariantCulture, contract, objectType);
            IL_00E4:
            string text2 = reader.Value.ToString();
            return this.EnsureType(reader, text2, CultureInfo.InvariantCulture, contract, objectType);
            IL_0100:
            if (objectType == typeof(DBNull))
            {
                return DBNull.Value;
            }
            return this.EnsureType(reader, reader.Value, CultureInfo.InvariantCulture, contract, objectType);
            IL_012D:
            return new JRaw((string)reader.Value);
            IL_013E:
            throw JsonSerializationException.Create(reader, "Unexpected token while deserializing object: " + reader.TokenType);
            Block_7:
            throw JsonSerializationException.Create(reader, "Unexpected end when deserializing object.");
        }
References Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CoerceEmptyStringToNull(), Newtonsoft.Json.Serialization.JsonContract.ContractType, Newtonsoft.Json.JsonSerializationException.Create(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateJToken(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(), System.Convert.FromBase64String(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.JsonReader.Read(), System.text, Newtonsoft.Json.JsonReader.TokenType, System.DBNull.Value, and Newtonsoft.Json.JsonReader.Value.
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateDynamic(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateISerializableItem(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateMultidimensionalArray(), and Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue().