Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary
PopulateDictionary()
object Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary (IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, string id) inline private
Definition at line 1115 of file JsonSerializerInternalReader.cs.
        {
            IWrappedDictionary wrappedDictionary = dictionary as IWrappedDictionary;
            object obj = ((wrappedDictionary != null) ? wrappedDictionary.UnderlyingDictionary : dictionary);
            if (id != null)
            {
                this.AddReference(reader, id, obj);
            }
            this.OnDeserializing(reader, contract, obj);
            int depth = reader.Depth;
            if (contract.KeyContract == null)
            {
                contract.KeyContract = this.GetContractSafe(contract.DictionaryKeyType);
            }
            if (contract.ItemContract == null)
            {
                contract.ItemContract = this.GetContractSafe(contract.DictionaryValueType);
            }
            JsonConverter jsonConverter = contract.ItemConverter ?? this.GetConverter(contract.ItemContract, null, contract, containerProperty);
            JsonPrimitiveContract jsonPrimitiveContract = contract.KeyContract as JsonPrimitiveContract;
            PrimitiveTypeCode primitiveTypeCode = ((jsonPrimitiveContract != null) ? jsonPrimitiveContract.TypeCode : PrimitiveTypeCode.Empty);
            bool flag = false;
            for (;;)
            {
                JsonToken tokenType = reader.TokenType;
                if (tokenType != JsonToken.PropertyName)
                {
                    if (tokenType != JsonToken.Comment)
                    {
                        if (tokenType != JsonToken.EndObject)
{
                            break;
                        }
                        goto IL_0261;
                    }
                }
                else
                {
                    object obj2 = reader.Value;
                    if (!this.CheckPropertyName(reader, obj2.ToString()))
                    {
                        try
{
                            try
{
                                switch (primitiveTypeCode)
{
                                case PrimitiveTypeCode.DateTime:
                                case PrimitiveTypeCode.DateTimeNullable:
{
                                    DateTime dateTime;
                                    if (DateTimeUtils.TryParseDateTime(obj2.ToString(), reader.DateTimeZoneHandling, reader.DateFormatString, reader.Culture, out dateTime))
{
                                        obj2 = dateTime;
                                    }
                                    else
{
                                        obj2 = this.EnsureType(reader, obj2, CultureInfo.InvariantCulture, contract.KeyContract, contract.DictionaryKeyType);
                                    }
                                    break;
                                }
                                case PrimitiveTypeCode.DateTimeOffset:
                                case PrimitiveTypeCode.DateTimeOffsetNullable:
{
                                    DateTimeOffset dateTimeOffset;
                                    if (DateTimeUtils.TryParseDateTimeOffset(obj2.ToString(), reader.DateFormatString, reader.Culture, out dateTimeOffset))
{
                                        obj2 = dateTimeOffset;
                                    }
                                    else
{
                                        obj2 = this.EnsureType(reader, obj2, CultureInfo.InvariantCulture, contract.KeyContract, contract.DictionaryKeyType);
                                    }
                                    break;
                                }
                                default:
                                    obj2 = this.EnsureType(reader, obj2, CultureInfo.InvariantCulture, contract.KeyContract, contract.DictionaryKeyType);
                                    break;
                                }
                            }
                            catch (Exception ex)
{
                                throw JsonSerializationException.Create(reader, "Could not convert string '{0}' to dictionary key type '{1}'. Create a TypeConverter to convert from the string to the key type object.".FormatWith(CultureInfo.InvariantCulture, reader.Value, contract.DictionaryKeyType), ex);
                            }
                            if (!this.ReadForType(reader, contract.ItemContract, jsonConverter != null))
{
                                throw JsonSerializationException.Create(reader, "Unexpected end when deserializing object.");
                            }
                            object obj3;
                            if (jsonConverter != null && jsonConverter.CanRead)
{
                                obj3 = this.DeserializeConvertable(jsonConverter, reader, contract.DictionaryValueType, null);
                            }
                            else
{
                                obj3 = this.CreateValueInternal(reader, contract.DictionaryValueType, contract.ItemContract, null, contract, containerProperty, null);
                            }
                            dictionary[obj2] = obj3;
                            goto IL_0282;
                        }
                        catch (Exception ex2)
{
                            if (base.IsErrorHandled(obj, contract, obj2, reader as IJsonLineInfo, reader.Path, ex2))
{
                                this.HandleError(reader, true, depth);
                                goto IL_0282;
                            }
                            throw;
                        }
                        goto IL_0261;
                    }
                }
                IL_0282:
                if (flag || !reader.Read())
                {
                    goto IL_0291;
                }
                continue;
                IL_0261:
                flag = true;
                goto IL_0282;
            }
            throw JsonSerializationException.Create(reader, "Unexpected token when deserializing object: " + reader.TokenType);
            IL_0291:
            if (!flag)
            {
                this.ThrowUnexpectedEndException(reader, contract, obj, "Unexpected end when deserializing object.");
            }
            this.OnDeserialized(reader, contract, obj);
            return obj;
        }
References Newtonsoft.Json.Serialization.JsonSerializerInternalReader.AddReference(), Newtonsoft.Json.JsonConverter.CanRead, Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CheckPropertyName(), Newtonsoft.Json.JsonSerializationException.Create(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(), Newtonsoft.Json.JsonReader.Culture, Newtonsoft.Json.JsonReader.DateFormatString, Newtonsoft.Json.JsonReader.DateTimeZoneHandling, Newtonsoft.Json.JsonReader.Depth, Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(), System.dictionary, Newtonsoft.Json.Serialization.JsonDictionaryContract.DictionaryKeyType, Newtonsoft.Json.Serialization.JsonDictionaryContract.DictionaryValueType, Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.GetContractSafe(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.GetConverter(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.HandleError(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.Serialization.JsonContainerContract.ItemContract, Newtonsoft.Json.Serialization.JsonDictionaryContract.KeyContract, System.obj, Newtonsoft.Json.Serialization.JsonSerializerInternalReader.OnDeserialized(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.OnDeserializing(), Newtonsoft.Json.JsonReader.Path, Newtonsoft.Json.JsonReader.Read(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ThrowUnexpectedEndException(), Newtonsoft.Json.JsonReader.TokenType, Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTime(), Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTimeOffset(), Newtonsoft.Json.Serialization.JsonPrimitiveContract.TypeCode, Newtonsoft.Json.Utilities.IWrappedDictionary.UnderlyingDictionary, and Newtonsoft.Json.JsonReader.Value.
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(), and Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate().