Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate
Populate()
void Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate (JsonReader reader, object target) inline
Definition at line 25 of file JsonSerializerInternalReader.cs.
        {
            ValidationUtils.ArgumentNotNull(target, "target");
            Type type = target.GetType();
            JsonContract jsonContract = this.Serializer._contractResolver.ResolveContract(type);
            if (!reader.MoveToContent())
            {
                throw JsonSerializationException.Create(reader, "No JSON content found.");
            }
            if (reader.TokenType == JsonToken.StartArray)
            {
                if (jsonContract.ContractType == JsonContractType.Array)
                {
                    JsonArrayContract jsonArrayContract = (JsonArrayContract)jsonContract;
                    IList list;
                    if (!jsonArrayContract.ShouldCreateWrapper)
                    {
                        list = (IList)target;
                    }
                    else
                    {
                        IList list2 = jsonArrayContract.CreateWrapper(target);
                        list = list2;
                    }
                    this.PopulateList(list, reader, jsonArrayContract, null, null);
                    return;
                }
                throw JsonSerializationException.Create(reader, "Cannot populate JSON array onto type '{0}'.".FormatWith(CultureInfo.InvariantCulture, type));
            }
            else
            {
                if (reader.TokenType != JsonToken.StartObject)
                {
                    throw JsonSerializationException.Create(reader, "Unexpected initial token '{0}' when populating object. Expected JSON object or array.".FormatWith(CultureInfo.InvariantCulture, reader.TokenType));
                }
                reader.ReadAndAssert();
                string text = null;
                if (this.Serializer.MetadataPropertyHandling != MetadataPropertyHandling.Ignore && reader.TokenType == JsonToken.PropertyName && string.Equals(reader.Value.ToString(), "$id", 4))
                {
                    reader.ReadAndAssert();
                    object value = reader.Value;
                    text = ((value != null) ? value.ToString() : null);
                    reader.ReadAndAssert();
                }
                if (jsonContract.ContractType == JsonContractType.Dictionary)
                {
                    JsonDictionaryContract jsonDictionaryContract = (JsonDictionaryContract)jsonContract;
                    IDictionary dictionary;
                    if (!jsonDictionaryContract.ShouldCreateWrapper)
                    {
                        dictionary = (IDictionary)target;
                    }
                    else
                    {
                        IDictionary dictionary2 = jsonDictionaryContract.CreateWrapper(target);
                        dictionary = dictionary2;
                    }
                    this.PopulateDictionary(dictionary, reader, jsonDictionaryContract, null, text);
                    return;
                }
                if (jsonContract.ContractType == JsonContractType.Object)
                {
                    this.PopulateObject(target, reader, (JsonObjectContract)jsonContract, null, text);
                    return;
                }
                throw JsonSerializationException.Create(reader, "Cannot populate JSON object onto type '{0}'.".FormatWith(CultureInfo.InvariantCulture, type));
            }
        }
References Newtonsoft.Json.JsonSerializer._contractResolver, Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(), Newtonsoft.Json.Serialization.JsonContract.ContractType, Newtonsoft.Json.JsonSerializationException.Create(), Newtonsoft.Json.Serialization.JsonDictionaryContract.CreateWrapper(), Newtonsoft.Json.Serialization.JsonArrayContract.CreateWrapper(), System.dictionary, System.Globalization.CultureInfo.InvariantCulture, System.list, Newtonsoft.Json.JsonSerializer.MetadataPropertyHandling, Newtonsoft.Json.JsonReader.MoveToContent(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(), Newtonsoft.Json.JsonReader.ReadAndAssert(), Newtonsoft.Json.Serialization.JsonSerializerInternalBase.Serializer, Newtonsoft.Json.Serialization.JsonArrayContract.ShouldCreateWrapper, Newtonsoft.Json.Serialization.JsonDictionaryContract.ShouldCreateWrapper, System.text, Newtonsoft.Json.JsonReader.TokenType, System.value, and Newtonsoft.Json.JsonReader.Value.
Referenced by Newtonsoft.Json.JsonSerializer.PopulateInternal(), and Newtonsoft.Json.Serialization.JsonSerializerProxy.PopulateInternal().