Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue
SetPropertyValue()
bool Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue (JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, object target) inline private
Definition at line 873 of file JsonSerializerInternalReader.cs.
        {
            bool flag;
            object value;
            JsonContract jsonContract;
            bool flag2;
            if (this.CalculatePropertyDetails(property, ref propertyConverter, containerContract, containerProperty, reader, target, out flag, out value, out jsonContract, out flag2))
            {
                return false;
            }
            object obj;
            if (propertyConverter != null && propertyConverter.CanRead)
            {
                if (!flag2 && target != null && property.Readable)
                {
                    value = property.ValueProvider.GetValue(target);
                }
                obj = this.DeserializeConvertable(propertyConverter, reader, property.PropertyType, value);
            }
            else
            {
                obj = this.CreateValueInternal(reader, property.PropertyType, jsonContract, property, containerContract, containerProperty, flag ? value : null);
            }
            if ((!flag || obj != value) && this.ShouldSetPropertyValue(property, obj))
            {
                property.ValueProvider.SetValue(target, obj);
                if (property.SetIsSpecified != null)
                {
                    if (this.TraceWriter != null && this.TraceWriter.LevelFilter >= 4)
                    {
                        this.TraceWriter.Trace(4, JsonPosition.FormatMessage(reader as IJsonLineInfo, reader.Path, "IsSpecified for property '{0}' on {1} set to true.".FormatWith(CultureInfo.InvariantCulture, property.PropertyName, property.DeclaringType)), null);
                    }
                    property.SetIsSpecified.Invoke(target, true);
                }
                return true;
            }
            return flag;
        }
References Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CalculatePropertyDetails(), Newtonsoft.Json.JsonConverter.CanRead, Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(), Newtonsoft.Json.Serialization.JsonProperty.DeclaringType, Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(), Newtonsoft.Json.JsonPosition.FormatMessage(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.Serialization.ITraceWriter.LevelFilter, System.obj, Newtonsoft.Json.JsonReader.Path, Newtonsoft.Json.Serialization.JsonProperty.PropertyName, Newtonsoft.Json.Serialization.JsonProperty.PropertyType, Newtonsoft.Json.Serialization.JsonProperty.Readable, Newtonsoft.Json.Serialization.JsonProperty.SetIsSpecified, Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ShouldSetPropertyValue(), Newtonsoft.Json.Serialization.ITraceWriter.Trace(), Newtonsoft.Json.Serialization.JsonSerializerInternalBase.TraceWriter, and System.value.
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateDynamic().