Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType
ReadForType()
bool Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType (JsonReader reader, JsonContract contract, bool hasConverter) inline private
Definition at line 1965 of file JsonSerializerInternalReader.cs.
        {
            if (hasConverter)
            {
                return reader.Read();
            }
            switch ((contract != null) ? contract.InternalReadType : ReadType.Read)
            {
            case ReadType.Read:
                return reader.ReadAndMoveToContent();
            case ReadType.ReadAsInt32:
                reader.ReadAsInt32();
                break;
            case ReadType.ReadAsBytes:
                reader.ReadAsBytes();
                break;
            case ReadType.ReadAsString:
                reader.ReadAsString();
                break;
            case ReadType.ReadAsDecimal:
                reader.ReadAsDecimal();
                break;
            case ReadType.ReadAsDateTime:
                reader.ReadAsDateTime();
                break;
            case ReadType.ReadAsDateTimeOffset:
                reader.ReadAsDateTimeOffset();
                break;
            case ReadType.ReadAsDouble:
                reader.ReadAsDouble();
                break;
            case ReadType.ReadAsBoolean:
                reader.ReadAsBoolean();
                break;
            default:
                throw new ArgumentOutOfRangeException();
            }
            return reader.TokenType > JsonToken.None;
        }
References Newtonsoft.Json.Serialization.JsonContract.InternalReadType, Newtonsoft.Json.JsonReader.Read(), Newtonsoft.Json.JsonReader.ReadAndMoveToContent(), Newtonsoft.Json.JsonReader.ReadAsBoolean(), Newtonsoft.Json.JsonReader.ReadAsBytes(), Newtonsoft.Json.JsonReader.ReadAsDateTime(), Newtonsoft.Json.JsonReader.ReadAsDateTimeOffset(), Newtonsoft.Json.JsonReader.ReadAsDecimal(), Newtonsoft.Json.JsonReader.ReadAsDouble(), Newtonsoft.Json.JsonReader.ReadAsInt32(), and Newtonsoft.Json.JsonReader.ReadAsString().
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(), and Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateMultidimensionalArray().