Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataPropertiesToken
ReadMetadataPropertiesToken()
bool Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataPropertiesToken (JTokenReader reader, ref Type objectType, ref JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, object existingValue, out object newValue, out string id) inline private
Definition at line 523 of file JsonSerializerInternalReader.cs.
        {
            id = null;
            newValue = null;
            if (reader.TokenType == JsonToken.StartObject)
            {
                JObject jobject = (JObject)reader.CurrentToken;
                JToken jtoken = jobject["$ref"];
                if (jtoken != null)
                {
                    if (jtoken.Type != JTokenType.String && jtoken.Type != JTokenType.Null)
                    {
                        throw JsonSerializationException.Create(jtoken, jtoken.Path, "JSON reference {0} property must have a string or null value.".FormatWith(CultureInfo.InvariantCulture, "$ref"), null);
                    }
                    JToken parent = jtoken.Parent;
                    JToken jtoken2 = null;
                    if (parent.Next != null)
                    {
                        jtoken2 = parent.Next;
                    }
                    else if (parent.Previous != null)
                    {
                        jtoken2 = parent.Previous;
                    }
                    string text = (string)jtoken;
                    if (text != null)
                    {
                        if (jtoken2 != null)
{
                            throw JsonSerializationException.Create(jtoken2, jtoken2.Path, "Additional content found in JSON reference object. A JSON reference object should only have a {0} property.".FormatWith(CultureInfo.InvariantCulture, "$ref"), null);
                        }
                        newValue = this.Serializer.GetReferenceResolver().ResolveReference(this, text);
                        if (this.TraceWriter != null && this.TraceWriter.LevelFilter >= 3)
{
                            this.TraceWriter.Trace(3, JsonPosition.FormatMessage(reader, reader.Path, "Resolved object reference '{0}' to {1}.".FormatWith(CultureInfo.InvariantCulture, text, newValue.GetType())), null);
                        }
                        reader.Skip();
                        return true;
                    }
                }
                JToken jtoken3 = jobject["$type"];
                if (jtoken3 != null)
                {
                    string text2 = (string)jtoken3;
                    JsonReader jsonReader = jtoken3.CreateReader();
                    jsonReader.ReadAndAssert();
                    this.ResolveTypeName(jsonReader, ref objectType, ref contract, member, containerContract, containerMember, text2);
                    if (jobject["$value"] != null)
                    {
                        for (;;)
{
                            reader.ReadAndAssert();
                            if (reader.TokenType == JsonToken.PropertyName && (string)reader.Value == "$value")
{
                                break;
                            }
                            reader.ReadAndAssert();
                            reader.Skip();
                        }
                        return false;
                    }
                }
                JToken jtoken4 = jobject["$id"];
                if (jtoken4 != null)
                {
                    id = (string)jtoken4;
                }
                JToken jtoken5 = jobject["$values"];
                if (jtoken5 != null)
                {
                    JsonReader jsonReader2 = jtoken5.CreateReader();
                    jsonReader2.ReadAndAssert();
                    newValue = this.CreateList(jsonReader2, objectType, contract, member, existingValue, id);
                    reader.Skip();
                    return true;
                }
            }
            reader.ReadAndAssert();
            return false;
        }
References Newtonsoft.Json.JsonSerializationException.Create(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(), Newtonsoft.Json.Linq.JToken.CreateReader(), Newtonsoft.Json.Linq.JTokenReader.CurrentToken, Newtonsoft.Json.JsonPosition.FormatMessage(), Newtonsoft.Json.JsonSerializer.GetReferenceResolver(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.Serialization.ITraceWriter.LevelFilter, Newtonsoft.Json.Linq.JToken.Next, Newtonsoft.Json.Linq.JToken.Parent, Newtonsoft.Json.Linq.JToken.Path, Newtonsoft.Json.Linq.JTokenReader.Path, Newtonsoft.Json.Linq.JToken.Previous, Newtonsoft.Json.JsonReader.ReadAndAssert(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolveTypeName(), Newtonsoft.Json.Serialization.JsonSerializerInternalBase.Serializer, Newtonsoft.Json.JsonReader.Skip(), System.text, Newtonsoft.Json.JsonReader.TokenType, Newtonsoft.Json.Serialization.ITraceWriter.Trace(), Newtonsoft.Json.Serialization.JsonSerializerInternalBase.TraceWriter, Newtonsoft.Json.Linq.JToken.Type, and Newtonsoft.Json.JsonReader.Value.
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject().