Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalReader.GetConverter
GetConverter()
JsonConverter Newtonsoft.Json.Serialization.JsonSerializerInternalReader.GetConverter (JsonContract contract, JsonConverter memberConverter, JsonContainerContract containerContract, JsonProperty containerProperty) inline private
Definition at line 337 of file JsonSerializerInternalReader.cs.
        {
            JsonConverter jsonConverter = null;
            if (memberConverter != null)
            {
                jsonConverter = memberConverter;
            }
            else if (((containerProperty != null) ? containerProperty.ItemConverter : null) != null)
            {
                jsonConverter = containerProperty.ItemConverter;
            }
            else if (((containerContract != null) ? containerContract.ItemConverter : null) != null)
            {
                jsonConverter = containerContract.ItemConverter;
            }
            else if (contract != null)
            {
                JsonConverter matchingConverter;
                if (contract.Converter != null)
                {
                    jsonConverter = contract.Converter;
                }
                else if ((matchingConverter = this.Serializer.GetMatchingConverter(contract.UnderlyingType)) != null)
                {
                    jsonConverter = matchingConverter;
                }
                else if (contract.InternalConverter != null)
                {
                    jsonConverter = contract.InternalConverter;
                }
            }
            return jsonConverter;
        }
References Newtonsoft.Json.Serialization.JsonContract.Converter, Newtonsoft.Json.JsonSerializer.GetMatchingConverter(), Newtonsoft.Json.Serialization.JsonContract.InternalConverter, Newtonsoft.Json.Serialization.JsonContainerContract.ItemConverter, Newtonsoft.Json.Serialization.JsonProperty.ItemConverter, Newtonsoft.Json.Serialization.JsonSerializerInternalBase.Serializer, and Newtonsoft.Json.Serialization.JsonContract.UnderlyingType.
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CalculatePropertyDetails(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateDynamic(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateISerializableItem(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(), and Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateMultidimensionalArray().