Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject
CreateObject()
object Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject (JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, object existingValue) inline private
Definition at line 372 of file JsonSerializerInternalReader.cs.
        {
            Type type = objectType;
            string text;
            if (this.Serializer.MetadataPropertyHandling == MetadataPropertyHandling.Ignore)
            {
                reader.ReadAndAssert();
                text = null;
            }
            else if (this.Serializer.MetadataPropertyHandling == MetadataPropertyHandling.ReadAhead)
            {
                JTokenReader jtokenReader = reader as JTokenReader;
                if (jtokenReader == null)
                {
                    jtokenReader = (JTokenReader)JToken.ReadFrom(reader).CreateReader();
                    jtokenReader.Culture = reader.Culture;
                    jtokenReader.DateFormatString = reader.DateFormatString;
                    jtokenReader.DateParseHandling = reader.DateParseHandling;
                    jtokenReader.DateTimeZoneHandling = reader.DateTimeZoneHandling;
                    jtokenReader.FloatParseHandling = reader.FloatParseHandling;
                    jtokenReader.SupportMultipleContent = reader.SupportMultipleContent;
                    jtokenReader.ReadAndAssert();
                    reader = jtokenReader;
                }
                object obj;
                if (this.ReadMetadataPropertiesToken(jtokenReader, ref type, ref contract, member, containerContract, containerMember, existingValue, out obj, out text))
                {
                    return obj;
                }
            }
            else
            {
                reader.ReadAndAssert();
                object obj2;
                if (this.ReadMetadataProperties(reader, ref type, ref contract, member, containerContract, containerMember, existingValue, out obj2, out text))
                {
                    return obj2;
                }
            }
            if (this.HasNoDefinedType(contract))
            {
                return this.CreateJObject(reader);
            }
            switch (contract.ContractType)
            {
            case JsonContractType.Object:
            {
                bool flag = false;
                JsonObjectContract jsonObjectContract = (JsonObjectContract)contract;
                object obj3;
                if (existingValue != null && (type == objectType || type.IsAssignableFrom(existingValue.GetType())))
                {
                    obj3 = existingValue;
                }
                else
                {
                    obj3 = this.CreateNewObject(reader, jsonObjectContract, member, containerMember, text, out flag);
                }
                if (flag)
                {
                    return obj3;
                }
                return this.PopulateObject(obj3, reader, jsonObjectContract, member, text);
            }
            case JsonContractType.Primitive:
            {
                JsonPrimitiveContract jsonPrimitiveContract = (JsonPrimitiveContract)contract;
                if (this.Serializer.MetadataPropertyHandling != MetadataPropertyHandling.Ignore && reader.TokenType == JsonToken.PropertyName && string.Equals(reader.Value.ToString(), "$value", 4))
                {
                    reader.ReadAndAssert();
                    if (reader.TokenType == JsonToken.StartObject)
                    {
                        throw JsonSerializationException.Create(reader, "Unexpected token when deserializing primitive value: " + reader.TokenType);
                    }
                    object obj4 = this.CreateValueInternal(reader, type, jsonPrimitiveContract, member, null, null, existingValue);
                    reader.ReadAndAssert();
                    return obj4;
                }
                break;
            }
            case JsonContractType.Dictionary:
            {
                JsonDictionaryContract jsonDictionaryContract = (JsonDictionaryContract)contract;
                object obj5;
                if (existingValue == null)
                {
                    bool flag2;
                    IDictionary dictionary = this.CreateNewDictionary(reader, jsonDictionaryContract, out flag2);
                    if (flag2)
                    {
                        if (text != null)
{
                            throw JsonSerializationException.Create(reader, "Cannot preserve reference to readonly dictionary, or dictionary created from a non-default constructor: {0}.".FormatWith(CultureInfo.InvariantCulture, contract.UnderlyingType));
                        }
                        if (contract.OnSerializingCallbacks.Count > 0)
{
                            throw JsonSerializationException.Create(reader, "Cannot call OnSerializing on readonly dictionary, or dictionary created from a non-default constructor: {0}.".FormatWith(CultureInfo.InvariantCulture, contract.UnderlyingType));
                        }
                        if (contract.OnErrorCallbacks.Count > 0)
{
                            throw JsonSerializationException.Create(reader, "Cannot call OnError on readonly list, or dictionary created from a non-default constructor: {0}.".FormatWith(CultureInfo.InvariantCulture, contract.UnderlyingType));
                        }
                        if (!jsonDictionaryContract.HasParameterizedCreatorInternal)
{
                            throw JsonSerializationException.Create(reader, "Cannot deserialize readonly or fixed size dictionary: {0}.".FormatWith(CultureInfo.InvariantCulture, contract.UnderlyingType));
                        }
                    }
                    this.PopulateDictionary(dictionary, reader, jsonDictionaryContract, member, text);
                    if (flag2)
                    {
                        return (jsonDictionaryContract.OverrideCreator ?? jsonDictionaryContract.ParameterizedCreator)(new object[] { dictionary });
                    }
                    if (dictionary is IWrappedDictionary)
                    {
                        return ((IWrappedDictionary)dictionary).UnderlyingDictionary;
                    }
                    obj5 = dictionary;
                }
                else
                {
                    IDictionary dictionary2;
                    if (!jsonDictionaryContract.ShouldCreateWrapper)
                    {
                        dictionary2 = (IDictionary)existingValue;
                    }
                    else
                    {
                        IDictionary dictionary3 = jsonDictionaryContract.CreateWrapper(existingValue);
                        dictionary2 = dictionary3;
                    }
                    obj5 = this.PopulateDictionary(dictionary2, reader, jsonDictionaryContract, member, text);
                }
                return obj5;
            }
            case JsonContractType.Dynamic:
            {
                JsonDynamicContract jsonDynamicContract = (JsonDynamicContract)contract;
                return this.CreateDynamic(reader, jsonDynamicContract, member, text);
            }
            case JsonContractType.Serializable:
            {
                JsonISerializableContract jsonISerializableContract = (JsonISerializableContract)contract;
                return this.CreateISerializable(reader, jsonISerializableContract, member, text);
            }
            }
            string text2 = "Cannot deserialize the current JSON object (e.g. {{\"name\":\"value\"}}) into type '{0}' because the type requires a {1} to deserialize correctly." + Environment.NewLine + "To fix this error either change the JSON to a {1} or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object." + Environment.NewLine;
            text2 = text2.FormatWith(CultureInfo.InvariantCulture, type, this.GetExpectedDescription(contract));
            throw JsonSerializationException.Create(reader, text2);
        }
References Newtonsoft.Json.Serialization.JsonContract.ContractType, Newtonsoft.Json.JsonSerializationException.Create(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateDynamic(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateISerializable(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateJObject(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewDictionary(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(), Newtonsoft.Json.Linq.JToken.CreateReader(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(), Newtonsoft.Json.Serialization.JsonDictionaryContract.CreateWrapper(), Newtonsoft.Json.JsonReader.Culture, Newtonsoft.Json.JsonReader.DateFormatString, Newtonsoft.Json.JsonReader.DateParseHandling, Newtonsoft.Json.JsonReader.DateTimeZoneHandling, System.dictionary, Newtonsoft.Json.JsonReader.FloatParseHandling, Newtonsoft.Json.Serialization.JsonSerializerInternalReader.HasNoDefinedType(), Newtonsoft.Json.Serialization.JsonDictionaryContract.HasParameterizedCreatorInternal, System.Globalization.CultureInfo.InvariantCulture, System.Type.IsAssignableFrom(), Newtonsoft.Json.JsonSerializer.MetadataPropertyHandling, System.obj, Newtonsoft.Json.Serialization.JsonContract.OnErrorCallbacks, Newtonsoft.Json.Serialization.JsonContract.OnSerializingCallbacks, Newtonsoft.Json.Serialization.JsonDictionaryContract.OverrideCreator, Newtonsoft.Json.Serialization.JsonDictionaryContract.ParameterizedCreator, Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(), Newtonsoft.Json.JsonReader.ReadAndAssert(), Newtonsoft.Json.Linq.JToken.ReadFrom(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataProperties(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataPropertiesToken(), Newtonsoft.Json.Serialization.JsonSerializerInternalBase.Serializer, Newtonsoft.Json.Serialization.JsonDictionaryContract.ShouldCreateWrapper, Newtonsoft.Json.JsonReader.SupportMultipleContent, System.text, Newtonsoft.Json.JsonReader.TokenType, Newtonsoft.Json.Serialization.JsonContract.UnderlyingType, and Newtonsoft.Json.JsonReader.Value.
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal().