Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateISerializableItem
CreateISerializableItem()
object Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateISerializableItem (JToken token, Type type, JsonISerializableContract contract, JsonProperty member) inline package
Definition at line 1525 of file JsonSerializerInternalReader.cs.
        {
            JsonContract contractSafe = this.GetContractSafe(type);
            JsonConverter converter = this.GetConverter(contractSafe, null, contract, member);
            JsonReader jsonReader = token.CreateReader();
            jsonReader.ReadAndAssert();
            object obj;
            if (converter != null && converter.CanRead)
            {
                obj = this.DeserializeConvertable(converter, jsonReader, type, null);
            }
            else
            {
                obj = this.CreateValueInternal(jsonReader, type, contractSafe, null, contract, member, null);
            }
            return obj;
        }
References System.converter, Newtonsoft.Json.Linq.JToken.CreateReader(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.GetContractSafe(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.GetConverter(), System.obj, and Newtonsoft.Json.JsonReader.ReadAndAssert().
Referenced by Newtonsoft.Json.Serialization.JsonFormatterConverter.Convert().