Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject
PopulateObject()
object Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject (object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, string id) inline private
Definition at line 2040 of file JsonSerializerInternalReader.cs.
        {
            this.OnDeserializing(reader, contract, newObject);
            Dictionary<JsonProperty, JsonSerializerInternalReader.PropertyPresence> dictionary;
            if (!contract.HasRequiredOrDefaultValueProperties && !this.HasFlag(this.Serializer._defaultValueHandling, DefaultValueHandling.Populate))
            {
                dictionary = null;
            }
            else
            {
                dictionary = Enumerable.ToDictionary<JsonProperty, JsonProperty, JsonSerializerInternalReader.PropertyPresence>(contract.Properties, (JsonProperty m) => m, (JsonProperty m) => JsonSerializerInternalReader.PropertyPresence.None);
            }
            Dictionary<JsonProperty, JsonSerializerInternalReader.PropertyPresence> dictionary2 = dictionary;
            if (id != null)
            {
                this.AddReference(reader, id, newObject);
            }
            int depth = reader.Depth;
            bool flag = false;
            for (;;)
            {
                JsonToken tokenType = reader.TokenType;
                if (tokenType != JsonToken.PropertyName)
                {
                    if (tokenType != JsonToken.Comment)
                    {
                        if (tokenType != JsonToken.EndObject)
{
                            break;
                        }
                        goto IL_026D;
                    }
                }
                else
                {
                    string text = reader.Value.ToString();
                    if (!this.CheckPropertyName(reader, text))
                    {
                        try
{
                            JsonProperty closestMatchProperty = contract.Properties.GetClosestMatchProperty(text);
                            if (closestMatchProperty != null)
{
                                if (closestMatchProperty.Ignored || !this.ShouldDeserialize(reader, closestMatchProperty, newObject))
{
                                    if (reader.Read())
{
                                        this.SetPropertyPresence(reader, closestMatchProperty, dictionary2);
                                        this.SetExtensionData(contract, member, reader, text, newObject);
                                    }
                                }
                                else
{
                                    if (closestMatchProperty.PropertyContract == null)
{
                                        closestMatchProperty.PropertyContract = this.GetContractSafe(closestMatchProperty.PropertyType);
                                    }
                                    JsonConverter converter = this.GetConverter(closestMatchProperty.PropertyContract, closestMatchProperty.MemberConverter, contract, member);
                                    if (!this.ReadForType(reader, closestMatchProperty.PropertyContract, converter != null))
{
                                        throw JsonSerializationException.Create(reader, "Unexpected end when setting {0}'s value.".FormatWith(CultureInfo.InvariantCulture, text));
                                    }
                                    this.SetPropertyPresence(reader, closestMatchProperty, dictionary2);
                                    if (!this.SetPropertyValue(closestMatchProperty, converter, contract, member, reader, newObject))
{
                                        this.SetExtensionData(contract, member, reader, text, newObject);
                                    }
                                }
                                goto IL_028D;
                            }
                            if (this.TraceWriter != null && this.TraceWriter.LevelFilter >= 4)
{
                                this.TraceWriter.Trace(4, JsonPosition.FormatMessage(reader as IJsonLineInfo, reader.Path, "Could not find member '{0}' on {1}".FormatWith(CultureInfo.InvariantCulture, text, contract.UnderlyingType)), null);
                            }
                            if (this.Serializer._missingMemberHandling == MissingMemberHandling.Error)
{
                                throw JsonSerializationException.Create(reader, "Could not find member '{0}' on object of type '{1}'".FormatWith(CultureInfo.InvariantCulture, text, contract.UnderlyingType.Name));
                            }
                            if (!reader.Read())
{
                                goto IL_028D;
                            }
                            this.SetExtensionData(contract, member, reader, text, newObject);
                            goto IL_028D;
                        }
                        catch (Exception ex)
{
                            if (base.IsErrorHandled(newObject, contract, text, reader as IJsonLineInfo, reader.Path, ex))
{
                                this.HandleError(reader, true, depth - 1);
                                goto IL_028D;
                            }
                            throw;
                        }
                        goto IL_026D;
                    }
                }
                IL_028D:
                if (flag || !reader.Read())
                {
                    goto IL_029B;
                }
                continue;
                IL_026D:
                flag = true;
                goto IL_028D;
            }
            throw JsonSerializationException.Create(reader, "Unexpected token when deserializing object: " + reader.TokenType);
            IL_029B:
            if (!flag)
            {
                this.ThrowUnexpectedEndException(reader, contract, newObject, "Unexpected end when deserializing object.");
            }
            if (dictionary2 != null)
            {
                foreach (KeyValuePair<JsonProperty, JsonSerializerInternalReader.PropertyPresence> keyValuePair in dictionary2)
                {
                    JsonProperty key = keyValuePair.Key;
                    JsonSerializerInternalReader.PropertyPresence value = keyValuePair.Value;
                    this.EndProcessProperty(newObject, reader, contract, depth, key, value, true);
                }
            }
            this.OnDeserialized(reader, contract, newObject);
            return newObject;
        }
References System.converter, Newtonsoft.Json.JsonSerializationException.Create(), Newtonsoft.Json.JsonReader.Depth, System.dictionary, Newtonsoft.Json.JsonPosition.FormatMessage(), Newtonsoft.Json.Serialization.JsonPropertyCollection.GetClosestMatchProperty(), Newtonsoft.Json.Serialization.JsonObjectContract.HasRequiredOrDefaultValueProperties, Newtonsoft.Json.Serialization.JsonProperty.Ignored, System.Globalization.CultureInfo.InvariantCulture, System.Collections.Generic.KeyValuePair< TKey, TValue >.Key, System.key, Newtonsoft.Json.Serialization.JsonProperty.MemberConverter, System.Reflection.MemberInfo.Name, Newtonsoft.Json.JsonReader.Path, Newtonsoft.Json.Serialization.JsonObjectContract.Properties, Newtonsoft.Json.Serialization.JsonProperty.PropertyContract, Newtonsoft.Json.Serialization.JsonProperty.PropertyType, Newtonsoft.Json.JsonReader.Read(), System.text, Newtonsoft.Json.JsonReader.TokenType, Newtonsoft.Json.Serialization.JsonContract.UnderlyingType, System.Collections.Generic.KeyValuePair< TKey, TValue >.Value, System.value, and Newtonsoft.Json.JsonReader.Value.
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(), and Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate().