Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateMultidimensionalArray
PopulateMultidimensionalArray()
object Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateMultidimensionalArray (IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, string id) inline private
Definition at line 1248 of file JsonSerializerInternalReader.cs.
        {
            int arrayRank = contract.UnderlyingType.GetArrayRank();
            if (id != null)
            {
                this.AddReference(reader, id, list);
            }
            this.OnDeserializing(reader, contract, list);
            JsonContract contractSafe = this.GetContractSafe(contract.CollectionItemType);
            JsonConverter converter = this.GetConverter(contractSafe, null, contract, containerProperty);
            int? num = default(int?);
            Stack<IList> stack = new Stack<IList>();
            stack.Push(list);
            IList list2 = list;
            bool flag = false;
            for (;;)
            {
                int depth = reader.Depth;
                JsonToken jsonToken;
                if (stack.Count == arrayRank)
                {
                    try
                    {
                        if (this.ReadForType(reader, contractSafe, converter != null))
{
                            jsonToken = reader.TokenType;
                            if (jsonToken == JsonToken.EndArray)
{
                                stack.Pop();
                                list2 = stack.Peek();
                                num = default(int?);
                            }
                            else
{
                                object obj;
                                if (converter != null && converter.CanRead)
{
                                    obj = this.DeserializeConvertable(converter, reader, contract.CollectionItemType, null);
                                }
                                else
{
                                    obj = this.CreateValueInternal(reader, contract.CollectionItemType, contractSafe, null, contract, containerProperty, null);
                                }
                                list2.Add(obj);
                            }
                            goto IL_01F9;
                        }
                        goto IL_0200;
                    }
                    catch (Exception ex)
                    {
                        JsonPosition position = reader.GetPosition(depth);
                        if (!base.IsErrorHandled(list, contract, position.Position, reader as IJsonLineInfo, reader.Path, ex))
{
                            throw;
                        }
                        this.HandleError(reader, true, depth);
                        if (num != null && num == position.Position)
{
                            throw JsonSerializationException.Create(reader, "Infinite loop detected from error handling.", ex);
                        }
                        num = new int?(position.Position);
                        goto IL_01F9;
                    }
                    goto IL_0179;
                }
                goto IL_0179;
                IL_01F9:
                if (flag)
                {
                    goto IL_0200;
                }
                continue;
                IL_0179:
                if (!reader.Read())
                {
                    goto IL_0200;
                }
                jsonToken = reader.TokenType;
                if (jsonToken == JsonToken.StartArray)
                {
                    IList list3 = new List<object>();
                    list2.Add(list3);
                    stack.Push(list3);
                    list2 = list3;
                    goto IL_01F9;
                }
                if (jsonToken == JsonToken.Comment)
                {
                    goto IL_01F9;
                }
                if (jsonToken != JsonToken.EndArray)
                {
                    break;
                }
                stack.Pop();
                if (stack.Count > 0)
                {
                    list2 = stack.Peek();
                    goto IL_01F9;
                }
                flag = true;
                goto IL_01F9;
            }
            throw JsonSerializationException.Create(reader, "Unexpected token when deserializing multidimensional array: " + reader.TokenType);
            IL_0200:
            if (!flag)
            {
                this.ThrowUnexpectedEndException(reader, contract, list, "Unexpected end when deserializing array.");
            }
            this.OnDeserialized(reader, contract, list);
            return list;
        }
References System.Collections.Generic.ICollection< T >.Add(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.AddReference(), Newtonsoft.Json.Serialization.JsonArrayContract.CollectionItemType, System.converter, Newtonsoft.Json.JsonSerializationException.Create(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(), Newtonsoft.Json.JsonReader.Depth, Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(), System.Type.GetArrayRank(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.GetContractSafe(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.GetConverter(), Newtonsoft.Json.JsonReader.GetPosition(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.HandleError(), System.list, System.obj, Newtonsoft.Json.Serialization.JsonSerializerInternalReader.OnDeserialized(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.OnDeserializing(), Newtonsoft.Json.JsonReader.Path, Newtonsoft.Json.JsonPosition.Position, Newtonsoft.Json.JsonReader.Read(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(), System.stack, Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ThrowUnexpectedEndException(), Newtonsoft.Json.JsonReader.TokenType, and Newtonsoft.Json.Serialization.JsonContract.UnderlyingType.
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList().