Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType
EnsureType()
object Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType (JsonReader reader, object value, CultureInfo culture, JsonContract contract, Type targetType) inline private
Definition at line 827 of file JsonSerializerInternalReader.cs.
        {
            if (targetType == null)
            {
                return value;
            }
            if (ReflectionUtils.GetObjectType(value) != targetType)
            {
                if (value == null && contract.IsNullable)
                {
                    return null;
                }
                try
                {
                    if (!contract.IsConvertable)
                    {
                        return ConvertUtils.ConvertOrCast(value, culture, contract.NonNullableUnderlyingType);
                    }
                    JsonPrimitiveContract jsonPrimitiveContract = (JsonPrimitiveContract)contract;
                    if (contract.IsEnum)
                    {
                        if (value is string)
{
                            return Enum.Parse(contract.NonNullableUnderlyingType, value.ToString(), true);
                        }
                        if (ConvertUtils.IsInteger(jsonPrimitiveContract.TypeCode))
{
                            return Enum.ToObject(contract.NonNullableUnderlyingType, value);
                        }
                    }
                    if (value is BigInteger)
                    {
                        return ConvertUtils.FromBigInteger((BigInteger)value, contract.NonNullableUnderlyingType);
                    }
                    return Convert.ChangeType(value, contract.NonNullableUnderlyingType, culture);
                }
                catch (Exception ex)
                {
                    throw JsonSerializationException.Create(reader, "Error converting value {0} to type '{1}'.".FormatWith(CultureInfo.InvariantCulture, MiscellaneousUtils.FormatValueForPrint(value), targetType), ex);
                }
                return value;
            }
            return value;
        }
References Newtonsoft.Json.Utilities.BigInteger, System.Convert.ChangeType(), Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(), Newtonsoft.Json.JsonSerializationException.Create(), System.culture, Newtonsoft.Json.Utilities.MiscellaneousUtils.FormatValueForPrint(), Newtonsoft.Json.Utilities.ConvertUtils.FromBigInteger(), Newtonsoft.Json.Utilities.ReflectionUtils.GetObjectType(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.Serialization.JsonContract.IsConvertable, Newtonsoft.Json.Serialization.JsonContract.IsEnum, Newtonsoft.Json.Utilities.ConvertUtils.IsInteger(), Newtonsoft.Json.Serialization.JsonContract.IsNullable, Newtonsoft.Json.Serialization.JsonContract.NonNullableUnderlyingType, System.Enum.Parse(), System.Enum.ToObject(), System.Type.ToString(), Newtonsoft.Json.Serialization.JsonPrimitiveContract.TypeCode, and System.value.
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(), and Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary().