Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolveTypeName
ResolveTypeName()
void Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolveTypeName (JsonReader reader, ref Type objectType, ref JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, string qualifiedTypeName) inline private
Definition at line 688 of file JsonSerializerInternalReader.cs.
        {
            if ((((member != null) ? member.TypeNameHandling : default(TypeNameHandling?)) ?? ((containerContract != null) ? containerContract.ItemTypeNameHandling : default(TypeNameHandling?)) ?? ((containerMember != null) ? containerMember.ItemTypeNameHandling : default(TypeNameHandling?)) ?? this.Serializer._typeNameHandling) != TypeNameHandling.None)
            {
                TypeNameKey typeNameKey = ReflectionUtils.SplitFullyQualifiedTypeName(qualifiedTypeName);
                Type type;
                try
                {
                    type = this.Serializer._serializationBinder.BindToType(typeNameKey.AssemblyName, typeNameKey.TypeName);
                }
                catch (Exception ex)
                {
                    throw JsonSerializationException.Create(reader, "Error resolving type specified in JSON '{0}'.".FormatWith(CultureInfo.InvariantCulture, qualifiedTypeName), ex);
                }
                if (type == null)
                {
                    throw JsonSerializationException.Create(reader, "Type specified in JSON '{0}' was not resolved.".FormatWith(CultureInfo.InvariantCulture, qualifiedTypeName));
                }
                if (this.TraceWriter != null && this.TraceWriter.LevelFilter >= 4)
                {
                    this.TraceWriter.Trace(4, JsonPosition.FormatMessage(reader as IJsonLineInfo, reader.Path, "Resolved type '{0}' to {1}.".FormatWith(CultureInfo.InvariantCulture, qualifiedTypeName, type)), null);
                }
                if (objectType != null && objectType != typeof(IDynamicMetaObjectProvider) && !objectType.IsAssignableFrom(type))
                {
                    throw JsonSerializationException.Create(reader, "Type specified in JSON '{0}' is not compatible with '{1}'.".FormatWith(CultureInfo.InvariantCulture, type.AssemblyQualifiedName, objectType.AssemblyQualifiedName));
                }
                objectType = type;
                contract = this.GetContractSafe(type);
            }
        }
References Newtonsoft.Json.JsonSerializer._serializationBinder, Newtonsoft.Json.JsonSerializer._typeNameHandling, Newtonsoft.Json.Utilities.TypeNameKey.AssemblyName, System.Type.AssemblyQualifiedName, Newtonsoft.Json.JsonSerializationException.Create(), Newtonsoft.Json.JsonPosition.FormatMessage(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.GetContractSafe(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.Serialization.ITraceWriter.LevelFilter, Newtonsoft.Json.JsonReader.Path, Newtonsoft.Json.Serialization.JsonSerializerInternalBase.Serializer, Newtonsoft.Json.Utilities.ReflectionUtils.SplitFullyQualifiedTypeName(), Newtonsoft.Json.Serialization.ITraceWriter.Trace(), Newtonsoft.Json.Serialization.JsonSerializerInternalBase.TraceWriter, Newtonsoft.Json.Utilities.TypeNameKey.TypeName, and Newtonsoft.Json.Serialization.JsonProperty.TypeNameHandling.
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataProperties(), and Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataPropertiesToken().