Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList
PopulateList()
object Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList (IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, string id) inline private
Definition at line 1380 of file JsonSerializerInternalReader.cs.
        {
            IWrappedCollection wrappedCollection = list as IWrappedCollection;
            object obj = ((wrappedCollection != null) ? wrappedCollection.UnderlyingCollection : list);
            if (id != null)
            {
                this.AddReference(reader, id, obj);
            }
            if (list.IsFixedSize)
            {
                reader.Skip();
                return obj;
            }
            this.OnDeserializing(reader, contract, obj);
            int depth = reader.Depth;
            if (contract.ItemContract == null)
            {
                contract.ItemContract = this.GetContractSafe(contract.CollectionItemType);
            }
            JsonConverter converter = this.GetConverter(contract.ItemContract, null, contract, containerProperty);
            int? num = default(int?);
            bool flag = false;
            do
            {
                try
                {
                    if (!this.ReadForType(reader, contract.ItemContract, converter != null))
                    {
                        break;
                    }
                    JsonToken tokenType = reader.TokenType;
                    if (tokenType == JsonToken.EndArray)
                    {
                        flag = true;
                    }
                    else
                    {
                        object obj2;
                        if (converter != null && converter.CanRead)
{
                            obj2 = this.DeserializeConvertable(converter, reader, contract.CollectionItemType, null);
                        }
                        else
{
                            obj2 = this.CreateValueInternal(reader, contract.CollectionItemType, contract.ItemContract, null, contract, containerProperty, null);
                        }
                        list.Add(obj2);
                    }
                }
                catch (Exception ex)
                {
                    JsonPosition position = reader.GetPosition(depth);
                    if (!base.IsErrorHandled(obj, contract, position.Position, reader as IJsonLineInfo, reader.Path, ex))
                    {
                        throw;
                    }
                    this.HandleError(reader, true, depth);
                    if (num != null && num == position.Position)
                    {
                        throw JsonSerializationException.Create(reader, "Infinite loop detected from error handling.", ex);
                    }
                    num = new int?(position.Position);
                }
            }
            while (!flag);
            if (!flag)
            {
                this.ThrowUnexpectedEndException(reader, contract, obj, "Unexpected end when deserializing array.");
            }
            this.OnDeserialized(reader, contract, obj);
            return obj;
        }
References Newtonsoft.Json.Serialization.JsonSerializerInternalReader.AddReference(), Newtonsoft.Json.Serialization.JsonArrayContract.CollectionItemType, System.converter, Newtonsoft.Json.JsonSerializationException.Create(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(), Newtonsoft.Json.JsonReader.Depth, Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.GetContractSafe(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.GetConverter(), Newtonsoft.Json.JsonReader.GetPosition(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.HandleError(), Newtonsoft.Json.Serialization.JsonContainerContract.ItemContract, System.list, System.obj, Newtonsoft.Json.Serialization.JsonSerializerInternalReader.OnDeserialized(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.OnDeserializing(), Newtonsoft.Json.JsonReader.Path, Newtonsoft.Json.JsonPosition.Position, Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(), Newtonsoft.Json.JsonReader.Skip(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ThrowUnexpectedEndException(), Newtonsoft.Json.JsonReader.TokenType, and Newtonsoft.Json.Utilities.IWrappedCollection.UnderlyingCollection.
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(), and Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate().