Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataProperties
ReadMetadataProperties()
bool Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataProperties (JsonReader reader, ref Type objectType, ref JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, object existingValue, out object newValue, out string id) inline private
Definition at line 605 of file JsonSerializerInternalReader.cs.
        {
            id = null;
            newValue = null;
            if (reader.TokenType == JsonToken.PropertyName)
            {
                string text = reader.Value.ToString();
                if (text.Length > 0 && text.get_Chars(0) == '$')
                {
                    string text2;
                    for (;;)
                    {
                        text = reader.Value.ToString();
                        bool flag;
                        if (string.Equals(text, "$ref", 4))
{
                            reader.ReadAndAssert();
                            if (reader.TokenType != JsonToken.String && reader.TokenType != JsonToken.Null)
{
                                break;
                            }
                            object value = reader.Value;
                            text2 = ((value != null) ? value.ToString() : null);
                            reader.ReadAndAssert();
                            if (text2 != null)
{
                                goto Block_7;
                            }
                            flag = true;
                        }
                        else if (string.Equals(text, "$type", 4))
{
                            reader.ReadAndAssert();
                            string text3 = reader.Value.ToString();
                            this.ResolveTypeName(reader, ref objectType, ref contract, member, containerContract, containerMember, text3);
                            reader.ReadAndAssert();
                            flag = true;
                        }
                        else if (string.Equals(text, "$id", 4))
{
                            reader.ReadAndAssert();
                            object value2 = reader.Value;
                            id = ((value2 != null) ? value2.ToString() : null);
                            reader.ReadAndAssert();
                            flag = true;
                        }
                        else
{
                            if (string.Equals(text, "$values", 4))
{
                                goto Block_14;
                            }
                            flag = false;
                        }
                        if (!flag || reader.TokenType != JsonToken.PropertyName)
{
                            return false;
                        }
                    }
                    throw JsonSerializationException.Create(reader, "JSON reference {0} property must have a string or null value.".FormatWith(CultureInfo.InvariantCulture, "$ref"));
                    Block_7:
                    if (reader.TokenType == JsonToken.PropertyName)
                    {
                        throw JsonSerializationException.Create(reader, "Additional content found in JSON reference object. A JSON reference object should only have a {0} property.".FormatWith(CultureInfo.InvariantCulture, "$ref"));
                    }
                    newValue = this.Serializer.GetReferenceResolver().ResolveReference(this, text2);
                    if (this.TraceWriter != null && this.TraceWriter.LevelFilter >= 3)
                    {
                        this.TraceWriter.Trace(3, JsonPosition.FormatMessage(reader as IJsonLineInfo, reader.Path, "Resolved object reference '{0}' to {1}.".FormatWith(CultureInfo.InvariantCulture, text2, newValue.GetType())), null);
                    }
                    return true;
                    Block_14:
                    reader.ReadAndAssert();
                    object obj = this.CreateList(reader, objectType, contract, member, existingValue, id);
                    reader.ReadAndAssert();
                    newValue = obj;
                    return true;
                }
            }
            return false;
        }
References Newtonsoft.Json.JsonSerializationException.Create(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(), Newtonsoft.Json.JsonPosition.FormatMessage(), Newtonsoft.Json.JsonSerializer.GetReferenceResolver(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.Serialization.ITraceWriter.LevelFilter, System.obj, Newtonsoft.Json.JsonReader.Path, Newtonsoft.Json.JsonReader.ReadAndAssert(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolveTypeName(), Newtonsoft.Json.Serialization.JsonSerializerInternalBase.Serializer, System.text, Newtonsoft.Json.JsonReader.TokenType, Newtonsoft.Json.Serialization.ITraceWriter.Trace(), Newtonsoft.Json.Serialization.JsonSerializerInternalBase.TraceWriter, System.value, and Newtonsoft.Json.JsonReader.Value.
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject().