Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewDictionary
CreateNewDictionary()
IDictionary Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewDictionary (JsonReader reader, JsonDictionaryContract contract, out bool createdFromNonDefaultCreator) inline private
Definition at line 1052 of file JsonSerializerInternalReader.cs.
        {
            if (contract.OverrideCreator != null)
            {
                if (contract.HasParameterizedCreator)
                {
                    createdFromNonDefaultCreator = true;
                    return contract.CreateTemporaryDictionary();
                }
                createdFromNonDefaultCreator = false;
                return (IDictionary)contract.OverrideCreator(new object[0]);
            }
            else
            {
                if (contract.IsReadOnlyOrFixedSize)
                {
                    createdFromNonDefaultCreator = true;
                    return contract.CreateTemporaryDictionary();
                }
                if (contract.DefaultCreator != null && (!contract.DefaultCreatorNonPublic || this.Serializer._constructorHandling == ConstructorHandling.AllowNonPublicDefaultConstructor))
                {
                    object obj = contract.DefaultCreator.Invoke();
                    if (contract.ShouldCreateWrapper)
                    {
                        obj = contract.CreateWrapper(obj);
                    }
                    createdFromNonDefaultCreator = false;
                    return (IDictionary)obj;
                }
                if (contract.HasParameterizedCreatorInternal)
                {
                    createdFromNonDefaultCreator = true;
                    return contract.CreateTemporaryDictionary();
                }
                if (!contract.IsInstantiable)
                {
                    throw JsonSerializationException.Create(reader, "Could not create an instance of type {0}. Type is an interface or abstract class and cannot be instantiated.".FormatWith(CultureInfo.InvariantCulture, contract.UnderlyingType));
                }
                throw JsonSerializationException.Create(reader, "Unable to find a default constructor to use for type {0}.".FormatWith(CultureInfo.InvariantCulture, contract.UnderlyingType));
            }
        }
References Newtonsoft.Json.JsonSerializationException.Create(), Newtonsoft.Json.Serialization.JsonDictionaryContract.CreateTemporaryDictionary(), Newtonsoft.Json.Serialization.JsonDictionaryContract.CreateWrapper(), Newtonsoft.Json.Serialization.JsonContract.DefaultCreator, Newtonsoft.Json.Serialization.JsonContract.DefaultCreatorNonPublic, Newtonsoft.Json.Serialization.JsonDictionaryContract.HasParameterizedCreator, Newtonsoft.Json.Serialization.JsonDictionaryContract.HasParameterizedCreatorInternal, System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.Serialization.JsonContract.IsInstantiable, Newtonsoft.Json.Serialization.JsonContract.IsReadOnlyOrFixedSize, System.obj, Newtonsoft.Json.Serialization.JsonDictionaryContract.OverrideCreator, Newtonsoft.Json.Serialization.JsonDictionaryContract.ShouldCreateWrapper, and Newtonsoft.Json.Serialization.JsonContract.UnderlyingType.
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject().