Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateJToken
CreateJToken()
JToken Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateJToken (JsonReader reader, JsonContract contract) inline private
Definition at line 172 of file JsonSerializerInternalReader.cs.
        {
            ValidationUtils.ArgumentNotNull(reader, "reader");
            if (contract != null)
            {
                if (contract.UnderlyingType == typeof(JRaw))
                {
                    return JRaw.Create(reader);
                }
                if (reader.TokenType == JsonToken.Null && !(contract.UnderlyingType == typeof(JValue)) && !(contract.UnderlyingType == typeof(JToken)))
                {
                    return null;
                }
            }
            JToken token;
            using (JTokenWriter jtokenWriter = new JTokenWriter())
            {
                jtokenWriter.WriteToken(reader);
                token = jtokenWriter.Token;
            }
            return token;
        }
References Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(), Newtonsoft.Json.Linq.JRaw.Create(), Newtonsoft.Json.Linq.JTokenWriter.Token, Newtonsoft.Json.JsonReader.TokenType, Newtonsoft.Json.Serialization.JsonContract.UnderlyingType, and Newtonsoft.Json.Linq.JTokenWriter.WriteToken().
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(), and Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal().