Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues
ResolvePropertyAndCreatorValues()
List< JsonSerializerInternalReader.CreatorPropertyContext > Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues (JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType) inline private
Definition at line 1870 of file JsonSerializerInternalReader.cs.
        {
            List<JsonSerializerInternalReader.CreatorPropertyContext> list = new List<JsonSerializerInternalReader.CreatorPropertyContext>();
            bool flag = false;
            string text;
            for (;;)
            {
                JsonToken tokenType = reader.TokenType;
                if (tokenType != JsonToken.PropertyName)
                {
                    if (tokenType != JsonToken.Comment)
                    {
                        if (tokenType != JsonToken.EndObject)
{
                            break;
                        }
                        flag = true;
                    }
                }
                else
                {
                    text = reader.Value.ToString();
                    JsonSerializerInternalReader.CreatorPropertyContext creatorPropertyContext = new JsonSerializerInternalReader.CreatorPropertyContext
                    {
                        Name = reader.Value.ToString(),
                        ConstructorProperty = contract.CreatorParameters.GetClosestMatchProperty(text),
                        Property = contract.Properties.GetClosestMatchProperty(text)
                    };
                    list.Add(creatorPropertyContext);
                    JsonProperty jsonProperty = creatorPropertyContext.ConstructorProperty ?? creatorPropertyContext.Property;
                    if (jsonProperty != null && !jsonProperty.Ignored)
                    {
                        if (jsonProperty.PropertyContract == null)
{
                            jsonProperty.PropertyContract = this.GetContractSafe(jsonProperty.PropertyType);
                        }
                        JsonConverter converter = this.GetConverter(jsonProperty.PropertyContract, jsonProperty.MemberConverter, contract, containerProperty);
                        if (!this.ReadForType(reader, jsonProperty.PropertyContract, converter != null))
{
                            goto Block_8;
                        }
                        if (converter != null && converter.CanRead)
{
                            creatorPropertyContext.Value = this.DeserializeConvertable(converter, reader, jsonProperty.PropertyType, null);
                        }
                        else
{
                            creatorPropertyContext.Value = this.CreateValueInternal(reader, jsonProperty.PropertyType, jsonProperty.PropertyContract, jsonProperty, contract, containerProperty, null);
                        }
                    }
                    else
                    {
                        if (!reader.Read())
{
                            goto Block_11;
                        }
                        if (this.TraceWriter != null && this.TraceWriter.LevelFilter >= 4)
{
                            this.TraceWriter.Trace(4, JsonPosition.FormatMessage(reader as IJsonLineInfo, reader.Path, "Could not find member '{0}' on {1}.".FormatWith(CultureInfo.InvariantCulture, text, contract.UnderlyingType)), null);
                        }
                        if (this.Serializer._missingMemberHandling == MissingMemberHandling.Error)
{
                            goto Block_14;
                        }
                        if (contract.ExtensionDataSetter != null)
{
                            creatorPropertyContext.Value = this.ReadExtensionDataValue(contract, containerProperty, reader);
                        }
                        else
{
                            reader.Skip();
                        }
                    }
                }
                if (flag || !reader.Read())
                {
                    goto IL_0234;
                }
            }
            throw JsonSerializationException.Create(reader, "Unexpected token when deserializing object: " + reader.TokenType);
            Block_8:
            throw JsonSerializationException.Create(reader, "Unexpected end when setting {0}'s value.".FormatWith(CultureInfo.InvariantCulture, text));
            Block_11:
            throw JsonSerializationException.Create(reader, "Unexpected end when setting {0}'s value.".FormatWith(CultureInfo.InvariantCulture, text));
            Block_14:
            throw JsonSerializationException.Create(reader, "Could not find member '{0}' on object of type '{1}'".FormatWith(CultureInfo.InvariantCulture, text, objectType.Name));
            IL_0234:
            if (!flag)
            {
                this.ThrowUnexpectedEndException(reader, contract, null, "Unexpected end when deserializing object.");
            }
            return list;
        }
References System.converter, Newtonsoft.Json.JsonSerializationException.Create(), Newtonsoft.Json.Serialization.JsonObjectContract.CreatorParameters, Newtonsoft.Json.Serialization.JsonObjectContract.ExtensionDataSetter, Newtonsoft.Json.JsonPosition.FormatMessage(), Newtonsoft.Json.Serialization.JsonPropertyCollection.GetClosestMatchProperty(), Newtonsoft.Json.Serialization.JsonProperty.Ignored, System.Globalization.CultureInfo.InvariantCulture, System.list, Newtonsoft.Json.Serialization.JsonProperty.MemberConverter, System.Reflection.MemberInfo.Name, System.Name, Newtonsoft.Json.JsonReader.Path, Newtonsoft.Json.Serialization.JsonObjectContract.Properties, Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreatorPropertyContext.Property, Newtonsoft.Json.Property, Newtonsoft.Json.Serialization.JsonProperty.PropertyContract, Newtonsoft.Json.Serialization.JsonProperty.PropertyType, Newtonsoft.Json.JsonReader.Read(), Newtonsoft.Json.JsonReader.Skip(), System.text, Newtonsoft.Json.JsonReader.TokenType, Newtonsoft.Json.Serialization.JsonContract.UnderlyingType, and Newtonsoft.Json.JsonReader.Value.
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters().