Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable
DeserializeConvertable()
object Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable (JsonConverter converter, JsonReader reader, Type objectType, object existingValue) inline private
Definition at line 1855 of file JsonSerializerInternalReader.cs.
        {
            if (this.TraceWriter != null && this.TraceWriter.LevelFilter >= 3)
            {
                this.TraceWriter.Trace(3, JsonPosition.FormatMessage(reader as IJsonLineInfo, reader.Path, "Started deserializing {0} with converter {1}.".FormatWith(CultureInfo.InvariantCulture, objectType, converter.GetType())), null);
            }
            object obj = converter.ReadJson(reader, objectType, existingValue, this.GetInternalSerializer());
            if (this.TraceWriter != null && this.TraceWriter.LevelFilter >= 3)
            {
                this.TraceWriter.Trace(3, JsonPosition.FormatMessage(reader as IJsonLineInfo, reader.Path, "Finished deserializing {0} with converter {1}.".FormatWith(CultureInfo.InvariantCulture, objectType, converter.GetType())), null);
            }
            return obj;
        }
References System.converter, Newtonsoft.Json.JsonPosition.FormatMessage(), System.Type.GetType(), System.Globalization.CultureInfo.InvariantCulture, System.obj, and Newtonsoft.Json.JsonReader.Path.
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateDynamic(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateISerializableItem(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateMultidimensionalArray(), and Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue().