Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList
CreateList()
object Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList (JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, object existingValue, string id) inline private
Definition at line 737 of file JsonSerializerInternalReader.cs.
        {
            if (this.HasNoDefinedType(contract))
            {
                return this.CreateJToken(reader, contract);
            }
            JsonArrayContract jsonArrayContract = this.EnsureArrayContract(reader, objectType, contract);
            object obj;
            if (existingValue == null)
            {
                bool flag;
                IList list = this.CreateNewList(reader, jsonArrayContract, out flag);
                if (flag)
                {
                    if (id != null)
                    {
                        throw JsonSerializationException.Create(reader, "Cannot preserve reference to array or readonly list, or list created from a non-default constructor: {0}.".FormatWith(CultureInfo.InvariantCulture, contract.UnderlyingType));
                    }
                    if (contract.OnSerializingCallbacks.Count > 0)
                    {
                        throw JsonSerializationException.Create(reader, "Cannot call OnSerializing on an array or readonly list, or list created from a non-default constructor: {0}.".FormatWith(CultureInfo.InvariantCulture, contract.UnderlyingType));
                    }
                    if (contract.OnErrorCallbacks.Count > 0)
                    {
                        throw JsonSerializationException.Create(reader, "Cannot call OnError on an array or readonly list, or list created from a non-default constructor: {0}.".FormatWith(CultureInfo.InvariantCulture, contract.UnderlyingType));
                    }
                    if (!jsonArrayContract.HasParameterizedCreatorInternal && !jsonArrayContract.IsArray)
                    {
                        throw JsonSerializationException.Create(reader, "Cannot deserialize readonly or fixed size list: {0}.".FormatWith(CultureInfo.InvariantCulture, contract.UnderlyingType));
                    }
                }
                if (!jsonArrayContract.IsMultidimensionalArray)
                {
                    this.PopulateList(list, reader, jsonArrayContract, member, id);
                }
                else
                {
                    this.PopulateMultidimensionalArray(list, reader, jsonArrayContract, member, id);
                }
                if (flag)
                {
                    if (jsonArrayContract.IsMultidimensionalArray)
                    {
                        list = CollectionUtils.ToMultidimensionalArray(list, jsonArrayContract.CollectionItemType, contract.CreatedType.GetArrayRank());
                    }
                    else
                    {
                        if (!jsonArrayContract.IsArray)
{
                            return (jsonArrayContract.OverrideCreator ?? jsonArrayContract.ParameterizedCreator)(new object[] { list });
                        }
                        Array array = Array.CreateInstance(jsonArrayContract.CollectionItemType, list.Count);
                        list.CopyTo(array, 0);
                        list = array;
                    }
                }
                else if (list is IWrappedCollection)
                {
                    return ((IWrappedCollection)list).UnderlyingCollection;
                }
                obj = list;
            }
            else
            {
                if (!jsonArrayContract.CanDeserialize)
                {
                    throw JsonSerializationException.Create(reader, "Cannot populate list type {0}.".FormatWith(CultureInfo.InvariantCulture, contract.CreatedType));
                }
                IList list2;
                if (!jsonArrayContract.ShouldCreateWrapper)
                {
                    list2 = (IList)existingValue;
                }
                else
                {
                    IList list3 = jsonArrayContract.CreateWrapper(existingValue);
                    list2 = list3;
                }
                obj = this.PopulateList(list2, reader, jsonArrayContract, member, id);
            }
            return obj;
        }
References System.array, Newtonsoft.Json.Serialization.JsonArrayContract.CanDeserialize, Newtonsoft.Json.Serialization.JsonArrayContract.CollectionItemType, System.Array.CopyTo(), Newtonsoft.Json.JsonSerializationException.Create(), Newtonsoft.Json.Serialization.JsonContract.CreatedType, System.Array.CreateInstance(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateJToken(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewList(), Newtonsoft.Json.Serialization.JsonArrayContract.CreateWrapper(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(), System.Type.GetArrayRank(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.HasNoDefinedType(), Newtonsoft.Json.Serialization.JsonArrayContract.HasParameterizedCreatorInternal, System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.Serialization.JsonArrayContract.IsArray, Newtonsoft.Json.Serialization.JsonArrayContract.IsMultidimensionalArray, System.list, System.obj, Newtonsoft.Json.Serialization.JsonContract.OnErrorCallbacks, Newtonsoft.Json.Serialization.JsonContract.OnSerializingCallbacks, Newtonsoft.Json.Serialization.JsonArrayContract.OverrideCreator, Newtonsoft.Json.Serialization.JsonArrayContract.ParameterizedCreator, Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateMultidimensionalArray(), Newtonsoft.Json.Serialization.JsonArrayContract.ShouldCreateWrapper, Newtonsoft.Json.Utilities.CollectionUtils.ToMultidimensionalArray(), and Newtonsoft.Json.Serialization.JsonContract.UnderlyingType.
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataProperties(), and Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataPropertiesToken().