Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateISerializable
CreateISerializable()
object Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateISerializable (JsonReader reader, JsonISerializableContract contract, JsonProperty member, string id) inline private
Definition at line 1454 of file JsonSerializerInternalReader.cs.
        {
            Type underlyingType = contract.UnderlyingType;
            if (!JsonTypeReflector.FullyTrusted)
            {
                string text = "Type '{0}' implements ISerializable but cannot be deserialized using the ISerializable interface because the current application is not fully trusted and ISerializable can expose secure data." + Environment.NewLine + "To fix this error either change the environment to be fully trusted, change the application to not deserialize the type, add JsonObjectAttribute to the type or change the JsonSerializer setting ContractResolver to use a new DefaultContractResolver with IgnoreSerializableInterface set to true." + Environment.NewLine;
                text = text.FormatWith(CultureInfo.InvariantCulture, underlyingType);
                throw JsonSerializationException.Create(reader, text);
            }
            if (this.TraceWriter != null && this.TraceWriter.LevelFilter >= 3)
            {
                this.TraceWriter.Trace(3, JsonPosition.FormatMessage(reader as IJsonLineInfo, reader.Path, "Deserializing {0} using ISerializable constructor.".FormatWith(CultureInfo.InvariantCulture, contract.UnderlyingType)), null);
            }
            SerializationInfo serializationInfo = new SerializationInfo(contract.UnderlyingType, new JsonFormatterConverter(this, contract, member));
            bool flag = false;
            string text2;
            for (;;)
            {
                JsonToken tokenType = reader.TokenType;
                if (tokenType != JsonToken.PropertyName)
                {
                    if (tokenType != JsonToken.Comment)
                    {
                        if (tokenType != JsonToken.EndObject)
{
                            break;
                        }
                        flag = true;
                    }
                }
                else
                {
                    text2 = reader.Value.ToString();
                    if (!reader.Read())
                    {
                        goto Block_7;
                    }
                    serializationInfo.AddValue(text2, JToken.ReadFrom(reader));
                }
                if (flag || !reader.Read())
                {
                    goto IL_0125;
                }
            }
            throw JsonSerializationException.Create(reader, "Unexpected token when deserializing object: " + reader.TokenType);
            Block_7:
            throw JsonSerializationException.Create(reader, "Unexpected end when setting {0}'s value.".FormatWith(CultureInfo.InvariantCulture, text2));
            IL_0125:
            if (!flag)
            {
                this.ThrowUnexpectedEndException(reader, contract, serializationInfo, "Unexpected end when deserializing object.");
            }
            if (contract.ISerializableCreator == null)
            {
                throw JsonSerializationException.Create(reader, "ISerializable type '{0}' does not have a valid constructor. To correctly implement ISerializable a constructor that takes SerializationInfo and StreamingContext parameters should be present.".FormatWith(CultureInfo.InvariantCulture, underlyingType));
            }
            object obj = contract.ISerializableCreator(new object[]
            {
                serializationInfo,
                this.Serializer._context
            });
            if (id != null)
            {
                this.AddReference(reader, id, obj);
            }
            this.OnDeserializing(reader, contract, obj);
            this.OnDeserialized(reader, contract, obj);
            return obj;
        }
References Newtonsoft.Json.Serialization.JsonSerializerInternalReader.AddReference(), System.Runtime.Serialization.SerializationInfo.AddValue(), Newtonsoft.Json.JsonSerializationException.Create(), Newtonsoft.Json.JsonPosition.FormatMessage(), Newtonsoft.Json.Serialization.JsonTypeReflector.FullyTrusted, System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.Serialization.JsonISerializableContract.ISerializableCreator, Newtonsoft.Json.Serialization.ITraceWriter.LevelFilter, System.obj, Newtonsoft.Json.Serialization.JsonSerializerInternalReader.OnDeserialized(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.OnDeserializing(), Newtonsoft.Json.JsonReader.Path, Newtonsoft.Json.JsonReader.Read(), Newtonsoft.Json.Linq.JToken.ReadFrom(), System.text, Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ThrowUnexpectedEndException(), Newtonsoft.Json.JsonReader.TokenType, Newtonsoft.Json.Serialization.ITraceWriter.Trace(), Newtonsoft.Json.Serialization.JsonSerializerInternalBase.TraceWriter, Newtonsoft.Json.Serialization.JsonContract.UnderlyingType, and Newtonsoft.Json.JsonReader.Value.
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject().