Terraria Decompiled: Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewList
CreateNewList()
IList Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewList (JsonReader reader, JsonArrayContract contract, out bool createdFromNonDefaultCreator) inline private
Definition at line 995 of file JsonSerializerInternalReader.cs.
        {
            if (!contract.CanDeserialize)
            {
                throw JsonSerializationException.Create(reader, "Cannot create and populate list type {0}.".FormatWith(CultureInfo.InvariantCulture, contract.CreatedType));
            }
            if (contract.OverrideCreator != null)
            {
                if (contract.HasParameterizedCreator)
                {
                    createdFromNonDefaultCreator = true;
                    return contract.CreateTemporaryCollection();
                }
                object obj = contract.OverrideCreator(new object[0]);
                if (contract.ShouldCreateWrapper)
                {
                    obj = contract.CreateWrapper(obj);
                }
                createdFromNonDefaultCreator = false;
                return (IList)obj;
            }
            else
            {
                if (contract.IsReadOnlyOrFixedSize)
                {
                    createdFromNonDefaultCreator = true;
                    IList list = contract.CreateTemporaryCollection();
                    if (contract.ShouldCreateWrapper)
                    {
                        list = contract.CreateWrapper(list);
                    }
                    return list;
                }
                if (contract.DefaultCreator != null && (!contract.DefaultCreatorNonPublic || this.Serializer._constructorHandling == ConstructorHandling.AllowNonPublicDefaultConstructor))
                {
                    object obj2 = contract.DefaultCreator.Invoke();
                    if (contract.ShouldCreateWrapper)
                    {
                        obj2 = contract.CreateWrapper(obj2);
                    }
                    createdFromNonDefaultCreator = false;
                    return (IList)obj2;
                }
                if (contract.HasParameterizedCreatorInternal)
                {
                    createdFromNonDefaultCreator = true;
                    return contract.CreateTemporaryCollection();
                }
                if (!contract.IsInstantiable)
                {
                    throw JsonSerializationException.Create(reader, "Could not create an instance of type {0}. Type is an interface or abstract class and cannot be instantiated.".FormatWith(CultureInfo.InvariantCulture, contract.UnderlyingType));
                }
                throw JsonSerializationException.Create(reader, "Unable to find a constructor to use for type {0}.".FormatWith(CultureInfo.InvariantCulture, contract.UnderlyingType));
            }
        }
References Newtonsoft.Json.Serialization.JsonArrayContract.CanDeserialize, Newtonsoft.Json.JsonSerializationException.Create(), Newtonsoft.Json.Serialization.JsonContract.CreatedType, Newtonsoft.Json.Serialization.JsonArrayContract.CreateTemporaryCollection(), Newtonsoft.Json.Serialization.JsonArrayContract.CreateWrapper(), Newtonsoft.Json.Serialization.JsonContract.DefaultCreator, Newtonsoft.Json.Serialization.JsonContract.DefaultCreatorNonPublic, Newtonsoft.Json.Serialization.JsonArrayContract.HasParameterizedCreator, Newtonsoft.Json.Serialization.JsonArrayContract.HasParameterizedCreatorInternal, System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.Serialization.JsonContract.IsInstantiable, Newtonsoft.Json.Serialization.JsonContract.IsReadOnlyOrFixedSize, System.list, System.obj, Newtonsoft.Json.Serialization.JsonArrayContract.OverrideCreator, Newtonsoft.Json.Serialization.JsonArrayContract.ShouldCreateWrapper, and Newtonsoft.Json.Serialization.JsonContract.UnderlyingType.
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList().