Terraria Decompiled: System.StringComparer.Compare
Compare() [1/2]
int System.StringComparer.Compare (object x, object y) inline
Definition at line 115 of file StringComparer.cs.
        {
            if (x == y)
            {
                return 0;
            }
            if (x == null)
            {
                return -1;
            }
            if (y == null)
            {
                return 1;
            }
            string text = x as string;
            if (text != null)
            {
                string text2 = y as string;
                if (text2 != null)
                {
                    return this.Compare(text, text2);
                }
            }
            IComparable comparable = x as IComparable;
            if (comparable != null)
            {
                return comparable.CompareTo(y);
            }
            throw new ArgumentException("At least one object must implement IComparable.");
        }
References System.comparable, System.StringComparer.Compare(), System.IComparable< in T >.CompareTo(), and System.text.
Referenced by System.StringComparer.Compare(), and Terraria.GameContent.UI.States.UIDebugCommandsList.PopulateCommandsList().