Terraria Decompiled: Microsoft.Xna.Framework.Input.Touch.GestureDetector.OnMoved
OnMoved()
static void Microsoft.Xna.Framework.Input.Touch.GestureDetector.OnMoved (int fingerId, Vector2 touchPosition, Vector2 delta) inline static package
Definition at line 97 of file GestureDetector.cs.
        {
            if (GestureDetector.state == GestureDetector.GestureState.PINCHING)
            {
                GestureDetector.OnMoved_Pinch(fingerId, touchPosition, delta);
                return;
            }
            if (GestureDetector.activeFingerId == -1)
            {
                GestureDetector.activeFingerId = fingerId;
            }
            if (fingerId != GestureDetector.activeFingerId)
            {
                return;
            }
            GestureDetector.activeFingerPosition = touchPosition;
            bool flag = GestureDetector.IsGestureEnabled(GestureType.HorizontalDrag);
            bool flag2 = GestureDetector.IsGestureEnabled(GestureType.VerticalDrag);
            bool flag3 = GestureDetector.IsGestureEnabled(GestureType.FreeDrag);
            if ((GestureDetector.state == GestureDetector.GestureState.HOLDING || GestureDetector.state == GestureDetector.GestureState.HELD) && (touchPosition - GestureDetector.pressPosition).Length() > 35f)
            {
                if (flag && Math.Abs(delta.X) > Math.Abs(delta.Y))
                {
                    GestureDetector.state = GestureDetector.GestureState.DRAGGING_H;
                }
                else if (flag2 && Math.Abs(delta.Y) > Math.Abs(delta.X))
                {
                    GestureDetector.state = GestureDetector.GestureState.DRAGGING_V;
                }
                else if (flag3)
                {
                    GestureDetector.state = GestureDetector.GestureState.DRAGGING_FREE;
                }
                else
                {
                    GestureDetector.state = GestureDetector.GestureState.NONE;
                }
            }
            if (GestureDetector.state == GestureDetector.GestureState.DRAGGING_H && flag)
            {
                TouchPanel.EnqueueGesture(new GestureSample(GestureType.HorizontalDrag, GestureDetector.GetGestureTimestamp(), touchPosition, Vector2.Zero, new Vector2(delta.X, 0f), Vector2.Zero, fingerId, -1));
            }
            else if (GestureDetector.state == GestureDetector.GestureState.DRAGGING_V && flag2)
            {
                TouchPanel.EnqueueGesture(new GestureSample(GestureType.VerticalDrag, GestureDetector.GetGestureTimestamp(), touchPosition, Vector2.Zero, new Vector2(0f, delta.Y), Vector2.Zero, fingerId, -1));
            }
            else if (GestureDetector.state == GestureDetector.GestureState.DRAGGING_FREE && flag3)
            {
                TouchPanel.EnqueueGesture(new GestureSample(GestureType.FreeDrag, GestureDetector.GetGestureTimestamp(), touchPosition, Vector2.Zero, delta, Vector2.Zero, fingerId, -1));
            }
            if ((GestureDetector.state == GestureDetector.GestureState.DRAGGING_H && !flag) || (GestureDetector.state == GestureDetector.GestureState.DRAGGING_V && !flag2) || (GestureDetector.state == GestureDetector.GestureState.DRAGGING_FREE && !flag3))
            {
                GestureDetector.state = GestureDetector.GestureState.HELD;
            }
        }
References System.Math.Abs(), Microsoft.Xna.Framework.Input.Touch.GestureDetector.activeFingerId, Microsoft.Xna.Framework.Input.Touch.TouchPanel.EnqueueGesture(), Microsoft.Xna.Framework.Input.Touch.GestureDetector.GetGestureTimestamp(), Microsoft.Xna.Framework.Input.Touch.GestureDetector.IsGestureEnabled(), Microsoft.Xna.Framework.Input.Touch.GestureDetector.OnMoved_Pinch(), Microsoft.Xna.Framework.Input.Touch.GestureDetector.pressPosition, Microsoft.Xna.Framework.Input.Touch.GestureDetector.state, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Microsoft.Xna.Framework.Input.Touch.TouchPanel.INTERNAL_onTouchEvent().