Terraria Decompiled: Terraria.GameContent.Biomes.TerrainPass.ApplyPass
ApplyPass()
override void Terraria.GameContent.Biomes.TerrainPass.ApplyPass (GenerationProgress progress, GameConfiguration configuration) inline protected
Definition at line 18 of file TerrainPass.cs.
        {
            int num = configuration.Get<int>("FlatBeachPadding");
            progress.Message = Lang.gen[0].Value;
            TerrainPass.TerrainFeatureType terrainFeatureType = TerrainPass.TerrainFeatureType.Plateau;
            double num2 = (double)Main.maxTilesY * 0.3;
            num2 *= (double)GenBase._random.Next(90, 110) * 0.005;
            double num3 = num2 + (double)Main.maxTilesY * 0.2;
            num3 *= (double)GenBase._random.Next(90, 110) * 0.01;
            if (WorldGen.remixWorldGen)
            {
                num3 = (double)Main.maxTilesY * 0.5;
                if (Main.maxTilesX > 2500)
                {
                    num3 = (double)Main.maxTilesY * 0.6;
                }
                num3 *= (double)GenBase._random.Next(95, 106) * 0.01;
            }
            double num4 = num2;
            double num5 = num2;
            double num6 = num3;
            double num7 = num3;
            if (WorldGen.SecretSeed.noSurface.Enabled)
            {
                num2 = 25.0;
                num3 = (double)Main.maxTilesY * 0.4;
                num3 *= (double)GenBase._random.Next(90, 110) * 0.01;
            }
            double num8 = (double)Main.maxTilesY * 0.23;
            TerrainPass.SurfaceHistory surfaceHistory = new TerrainPass.SurfaceHistory(500);
            int num9 = GenVars.leftBeachEnd + num;
            for (int i = 0; i < Main.maxTilesX; i++)
            {
                progress.Set((double)i / (double)Main.maxTilesX);
                num4 = Math.Min(num2, num4);
                num5 = Math.Max(num2, num5);
                num6 = Math.Min(num3, num6);
                num7 = Math.Max(num3, num7);
                if (num9 <= 0)
                {
                    terrainFeatureType = (TerrainPass.TerrainFeatureType)GenBase._random.Next(0, 5);
                    num9 = GenBase._random.Next(5, 40);
                    if (terrainFeatureType == TerrainPass.TerrainFeatureType.Plateau)
                    {
                        num9 *= (int)((double)GenBase._random.Next(5, 30) * 0.2);
                    }
                }
                num9--;
                if ((double)i > (double)Main.maxTilesX * 0.45 && (double)i < (double)Main.maxTilesX * 0.55 && (terrainFeatureType == TerrainPass.TerrainFeatureType.Mountain || terrainFeatureType == TerrainPass.TerrainFeatureType.Valley))
                {
                    terrainFeatureType = (TerrainPass.TerrainFeatureType)GenBase._random.Next(3);
                }
                if ((double)i > (double)Main.maxTilesX * 0.48 && (double)i < (double)Main.maxTilesX * 0.52)
                {
                    terrainFeatureType = TerrainPass.TerrainFeatureType.Plateau;
                }
                if (!WorldGen.SecretSeed.noSurface.Enabled)
                {
                    num2 += TerrainPass.GenerateWorldSurfaceOffset(terrainFeatureType);
                }
                double num10 = 0.17;
                double num11 = 0.26;
                if (WorldGen.SecretSeed.surfaceIsInSpace.Enabled)
                {
                    num11 = 0.2199999988079071;
                }
                else if (WorldGen.drunkWorldGen)
                {
                    num10 = 0.15;
                    num11 = 0.28;
                }
                if (WorldGen.GetWorldSize() == 0)
                {
                    num10 += 0.02;
                }
                if (!WorldGen.SecretSeed.noSurface.Enabled)
                {
                    if (i < GenVars.leftBeachEnd + num || i > GenVars.rightBeachStart - num)
                    {
                        num2 = Utils.Clamp<double>(num2, (double)Main.maxTilesY * num10, num8);
                    }
                    else if (num2 < (double)Main.maxTilesY * num10)
                    {
                        num2 = (double)Main.maxTilesY * num10;
                        num9 = 0;
                    }
                    else if (num2 > (double)Main.maxTilesY * num11)
                    {
                        num2 = (double)Main.maxTilesY * num11;
                        num9 = 0;
                    }
                }
                while (GenBase._random.Next(0, 3) == 0)
                {
                    num3 += (double)GenBase._random.Next(-2, 3);
                }
                if (WorldGen.SecretSeed.noSurface.Enabled)
                {
                    if (num3 < num2 + (double)Main.maxTilesY * 0.35)
                    {
                        num3 += 1.0;
                    }
                    if (num3 > num2 + (double)Main.maxTilesY * 0.45)
                    {
                        num3 -= 1.0;
                    }
                }
                else if (WorldGen.remixWorldGen)
                {
                    if (Main.maxTilesX > 2500)
                    {
                        if (num3 > (double)Main.maxTilesY * 0.7)
{
                            num3 -= 1.0;
                        }
                    }
                    else if (num3 > (double)Main.maxTilesY * 0.6)
                    {
                        num3 -= 1.0;
                    }
                }
                else
                {
                    if (num3 < num2 + (double)Main.maxTilesY * 0.06)
                    {
                        num3 += 1.0;
                    }
                    if (num3 > num2 + (double)Main.maxTilesY * 0.35)
                    {
                        num3 -= 1.0;
                    }
                }
                surfaceHistory.Record(num2);
                if (WorldGen.SecretSeed.surfaceIsInSpace.Enabled && !WorldGen.SecretSeed.noSurface.Enabled)
                {
                    TerrainPass.FillColumn(i, num2 - (double)Main.maxTilesY * 0.08, num3);
                }
                else
                {
                    TerrainPass.FillColumn(i, num2, num3);
                    if (i == GenVars.rightBeachStart - num)
                    {
                        if (num2 > num8)
{
                            TerrainPass.RetargetSurfaceHistory(surfaceHistory, i, num8);
                        }
                        terrainFeatureType = TerrainPass.TerrainFeatureType.Plateau;
                        num9 = Main.maxTilesX - i;
                    }
                }
            }
            Main.worldSurface = (double)((int)(num5 + 25.0));
            if (WorldGen.SecretSeed.noSurface.Enabled)
            {
                Main.worldSurface = 25.0;
            }
            Main.rockLayer = num7;
            double num12 = (double)((int)((Main.rockLayer - Main.worldSurface) / 6.0) * 6);
            Main.rockLayer = (double)((int)(Main.worldSurface + num12));
            int num13 = (int)(Main.rockLayer + (double)Main.maxTilesY) / 2 + GenBase._random.Next(-100, 20);
            int num14 = num13 + GenBase._random.Next(50, 80);
            if (WorldGen.remixWorldGen)
            {
                num14 = (int)(Main.worldSurface * 4.0 + num3) / 5;
            }
            int num15 = 20;
            if (num6 < num5 + (double)num15)
            {
                double num16 = (num6 + num5) / 2.0;
                double num17 = Math.Abs(num6 - num5);
                if (num17 < (double)num15)
                {
                    num17 = (double)num15;
                }
                num6 = num16 + num17 / 2.0;
                num5 = num16 - num17 / 2.0;
            }
            GenVars.rockLayer = num3;
            GenVars.rockLayerHigh = num7;
            GenVars.rockLayerLow = num6;
            GenVars.worldSurface = num2;
            GenVars.worldSurfaceHigh = num5;
            GenVars.worldSurfaceLow = num4;
            GenVars.waterLine = num13;
            GenVars.lavaLine = num14;
            GenVars.remixMushroomLayerLow = Main.maxTilesY - 350;
            GenVars.remixMushroomLayerHigh = Main.UnderworldLayer;
            GenVars.remixSurfaceLayerLow = (int)GenVars.rockLayerLow;
            GenVars.remixSurfaceLayerHigh = GenVars.remixMushroomLayerLow;
        }
References Terraria.WorldBuilding.GenBase._random, System.Math.Abs(), Terraria.Utils.Clamp(), Terraria.WorldGen.drunkWorldGen, Terraria.GameContent.Biomes.TerrainPass.FillColumn(), Terraria.Lang.gen, Terraria.GameContent.Biomes.TerrainPass.GenerateWorldSurfaceOffset(), Terraria.WorldGen.GetWorldSize(), int, System.Math.Max(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, System.Math.Min(), Terraria.WorldGen.SecretSeed.noSurface, Terraria.GameContent.Biomes.TerrainPass.SurfaceHistory.Record(), Terraria.WorldBuilding.GenVars.remixMushroomLayerLow, Terraria.WorldGen.remixWorldGen, Terraria.GameContent.Biomes.TerrainPass.RetargetSurfaceHistory(), Terraria.WorldBuilding.GenVars.rightBeachStart, Terraria.Main.rockLayer, Terraria.WorldBuilding.GenVars.rockLayerLow, Terraria.WorldBuilding.GenerationProgress.Set(), Terraria.WorldGen.SecretSeed.surfaceIsInSpace, Terraria.Main.UnderworldLayer, and Terraria.Main.worldSurface.