Terraria Decompiled: Microsoft.Xna.Framework.Input.Touch.GestureDetector.OnPressed
OnPressed()
static void Microsoft.Xna.Framework.Input.Touch.GestureDetector.OnPressed (int fingerId, Vector2 touchPosition) inline static package
Definition at line 10 of file GestureDetector.cs.
        {
            GestureDetector.fingerIds.Add(fingerId);
            if (GestureDetector.state == GestureDetector.GestureState.PINCHING)
            {
                return;
            }
            if (GestureDetector.activeFingerId == -1)
            {
                GestureDetector.activeFingerId = fingerId;
                GestureDetector.activeFingerPosition = touchPosition;
                if (GestureDetector.state == GestureDetector.GestureState.JUST_TAPPED && GestureDetector.IsGestureEnabled(GestureType.DoubleTap) && DateTime.UtcNow - GestureDetector.eventTimestamp <= TimeSpan.FromMilliseconds(300.0) && (touchPosition - GestureDetector.pressPosition).Length() <= 35f)
                {
                    TouchPanel.EnqueueGesture(new GestureSample(GestureType.DoubleTap, GestureDetector.GetGestureTimestamp(), touchPosition, Vector2.Zero, Vector2.Zero, Vector2.Zero, fingerId, -1));
                    GestureDetector.justDoubleTapped = true;
                }
                GestureDetector.state = GestureDetector.GestureState.HOLDING;
                GestureDetector.pressPosition = touchPosition;
                GestureDetector.eventTimestamp = DateTime.UtcNow;
                return;
            }
            if (GestureDetector.IsGestureEnabled(GestureType.Pinch))
            {
                GestureDetector.secondFingerId = fingerId;
                GestureDetector.secondFingerPosition = touchPosition;
                GestureDetector.state = GestureDetector.GestureState.PINCHING;
            }
        }
References Microsoft.Xna.Framework.Input.Touch.GestureDetector.activeFingerId, System.Collections.Generic.List< T >.Add(), Microsoft.Xna.Framework.Input.Touch.TouchPanel.EnqueueGesture(), Microsoft.Xna.Framework.Input.Touch.GestureDetector.eventTimestamp, Microsoft.Xna.Framework.Input.Touch.GestureDetector.fingerIds, System.TimeSpan.FromMilliseconds(), Microsoft.Xna.Framework.Input.Touch.GestureDetector.GetGestureTimestamp(), Microsoft.Xna.Framework.Input.Touch.GestureDetector.IsGestureEnabled(), Microsoft.Xna.Framework.Input.Touch.GestureDetector.pressPosition, Microsoft.Xna.Framework.Input.Touch.GestureDetector.state, System.DateTime.UtcNow, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Microsoft.Xna.Framework.Input.Touch.TouchPanel.INTERNAL_onTouchEvent().