Terraria Decompiled: Microsoft.Xna.Framework.Input.Touch.GestureDetector.OnReleased
OnReleased()
static void Microsoft.Xna.Framework.Input.Touch.GestureDetector.OnReleased (int fingerId, Vector2 touchPosition) inline static package
Definition at line 40 of file GestureDetector.cs.
        {
            GestureDetector.fingerIds.Remove(fingerId);
            if (GestureDetector.state == GestureDetector.GestureState.PINCHING)
            {
                GestureDetector.OnReleased_Pinch(fingerId, touchPosition);
                return;
            }
            if (fingerId == GestureDetector.activeFingerId)
            {
                GestureDetector.activeFingerId = -1;
            }
            if (FNAPlatform.GetNumTouchFingers() > 0)
            {
                return;
            }
            if (GestureDetector.state == GestureDetector.GestureState.HOLDING)
            {
                bool flag = GestureDetector.IsGestureEnabled(GestureType.Tap);
                bool flag2 = GestureDetector.IsGestureEnabled(GestureType.DoubleTap);
                if ((flag || flag2) && DateTime.UtcNow - GestureDetector.eventTimestamp < TimeSpan.FromSeconds(1.0) && !GestureDetector.justDoubleTapped)
                {
                    if (flag)
                    {
                        TouchPanel.EnqueueGesture(new GestureSample(GestureType.Tap, GestureDetector.GetGestureTimestamp(), touchPosition, Vector2.Zero, Vector2.Zero, Vector2.Zero, fingerId, -1));
                    }
                    GestureDetector.state = GestureDetector.GestureState.JUST_TAPPED;
                }
            }
            GestureDetector.justDoubleTapped = false;
            if (GestureDetector.IsGestureEnabled(GestureType.Flick))
            {
                if ((touchPosition - GestureDetector.pressPosition).Length() > 35f && GestureDetector.velocity.Length() >= 100f)
                {
                    TouchPanel.EnqueueGesture(new GestureSample(GestureType.Flick, GestureDetector.GetGestureTimestamp(), Vector2.Zero, Vector2.Zero, GestureDetector.velocity, Vector2.Zero, fingerId, -1));
                }
                GestureDetector.velocity = Vector2.Zero;
                GestureDetector.lastUpdatePosition = Vector2.Zero;
                GestureDetector.updateTimestamp = DateTime.MinValue;
            }
            if (GestureDetector.IsGestureEnabled(GestureType.DragComplete) && (GestureDetector.state == GestureDetector.GestureState.DRAGGING_H || GestureDetector.state == GestureDetector.GestureState.DRAGGING_V || GestureDetector.state == GestureDetector.GestureState.DRAGGING_FREE))
            {
                TouchPanel.EnqueueGesture(new GestureSample(GestureType.DragComplete, GestureDetector.GetGestureTimestamp(), Vector2.Zero, Vector2.Zero, Vector2.Zero, Vector2.Zero, fingerId, -1));
            }
            if (GestureDetector.callBelatedPinchComplete && GestureDetector.IsGestureEnabled(GestureType.PinchComplete))
            {
                TouchPanel.EnqueueGesture(new GestureSample(GestureType.PinchComplete, GestureDetector.GetGestureTimestamp(), Vector2.Zero, Vector2.Zero, Vector2.Zero, Vector2.Zero, -1, -1));
            }
            GestureDetector.callBelatedPinchComplete = false;
            if (GestureDetector.state != GestureDetector.GestureState.JUST_TAPPED)
            {
                GestureDetector.state = GestureDetector.GestureState.NONE;
            }
            GestureDetector.eventTimestamp = DateTime.UtcNow;
        }
References Microsoft.Xna.Framework.Input.Touch.GestureDetector.activeFingerId, Microsoft.Xna.Framework.Input.Touch.GestureDetector.callBelatedPinchComplete, Microsoft.Xna.Framework.Input.Touch.TouchPanel.EnqueueGesture(), Microsoft.Xna.Framework.Input.Touch.GestureDetector.eventTimestamp, Microsoft.Xna.Framework.Input.Touch.GestureDetector.fingerIds, System.TimeSpan.FromSeconds(), Microsoft.Xna.Framework.Input.Touch.GestureDetector.GetGestureTimestamp(), Microsoft.Xna.Framework.FNAPlatform.GetNumTouchFingers, Microsoft.Xna.Framework.Input.Touch.GestureDetector.IsGestureEnabled(), Microsoft.Xna.Framework.Input.Touch.GestureDetector.justDoubleTapped, Microsoft.Xna.Framework.Vector2.Length(), System.DateTime.MinValue, Microsoft.Xna.Framework.Input.Touch.GestureDetector.OnReleased_Pinch(), Microsoft.Xna.Framework.Input.Touch.GestureDetector.pressPosition, System.Collections.Generic.List< T >.Remove(), Microsoft.Xna.Framework.Input.Touch.GestureDetector.state, System.DateTime.UtcNow, Microsoft.Xna.Framework.Input.Touch.GestureDetector.velocity, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Microsoft.Xna.Framework.Input.Touch.TouchPanel.INTERNAL_onTouchEvent().