Terraria Decompiled: Microsoft.Xna.Framework.Input.Touch.GestureDetector.OnUpdate
OnUpdate()
static void Microsoft.Xna.Framework.Input.Touch.GestureDetector.OnUpdate () inline static package
Definition at line 154 of file GestureDetector.cs.
        {
            if (GestureDetector.state == GestureDetector.GestureState.PINCHING)
            {
                if (!GestureDetector.IsGestureEnabled(GestureType.Pinch))
                {
                    GestureDetector.state = GestureDetector.GestureState.HELD;
                    GestureDetector.secondFingerId = -1;
                    GestureDetector.callBelatedPinchComplete = true;
                }
                return;
            }
            if (GestureDetector.activeFingerId == -1)
            {
                return;
            }
            if (GestureDetector.IsGestureEnabled(GestureType.Flick))
            {
                if (GestureDetector.updateTimestamp != DateTime.MinValue)
                {
                    float num = (float)(DateTime.UtcNow - GestureDetector.updateTimestamp).TotalSeconds;
                    Vector2 vector = (GestureDetector.activeFingerPosition - GestureDetector.lastUpdatePosition) / (0.001f + num);
                    GestureDetector.velocity += (vector - GestureDetector.velocity) * 0.45f;
                }
                GestureDetector.lastUpdatePosition = GestureDetector.activeFingerPosition;
                GestureDetector.updateTimestamp = DateTime.UtcNow;
            }
            if (GestureDetector.IsGestureEnabled(GestureType.Hold) && GestureDetector.state == GestureDetector.GestureState.HOLDING && DateTime.UtcNow - GestureDetector.eventTimestamp >= TimeSpan.FromSeconds(1.0))
            {
                TouchPanel.EnqueueGesture(new GestureSample(GestureType.Hold, GestureDetector.GetGestureTimestamp(), GestureDetector.activeFingerPosition, Vector2.Zero, Vector2.Zero, Vector2.Zero, GestureDetector.activeFingerId, -1));
                GestureDetector.state = GestureDetector.GestureState.HELD;
            }
        }
References Microsoft.Xna.Framework.Input.Touch.GestureDetector.activeFingerId, Microsoft.Xna.Framework.Input.Touch.GestureDetector.activeFingerPosition, Microsoft.Xna.Framework.Input.Touch.TouchPanel.EnqueueGesture(), System.TimeSpan.FromSeconds(), Microsoft.Xna.Framework.Input.Touch.GestureDetector.GetGestureTimestamp(), Microsoft.Xna.Framework.Input.Touch.GestureDetector.IsGestureEnabled(), Microsoft.Xna.Framework.Input.Touch.GestureDetector.lastUpdatePosition, System.DateTime.MinValue, Microsoft.Xna.Framework.Input.Touch.GestureDetector.state, Microsoft.Xna.Framework.Input.Touch.GestureDetector.updateTimestamp, System.DateTime.UtcNow, Microsoft.Xna.Framework.Input.Touch.GestureDetector.velocity, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Microsoft.Xna.Framework.Input.Touch.TouchPanel.Update().