Terraria Decompiled: Microsoft.Xna.Framework.Color.ToVector3
ToVector3()
Vector3 Microsoft.Xna.Framework.Color.ToVector3 () inline
Definition at line 2587 of file Color.cs.
        {
            return new Vector3((float)this.R / 255f, (float)this.G / 255f, (float)this.B / 255f);
        }
References Microsoft.Xna.Framework.Color.B, Microsoft.Xna.Framework.Color.G, and Microsoft.Xna.Framework.Color.R.
Referenced by Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.Projectile.AI_001(), Terraria.NPC.AI_007_TownEntities(), Terraria.Projectile.AI_067_FreakingPirates(), Terraria.NPC.AI_112_FairyCritter(), Terraria.Projectile.AI_167_SparkleGuitar(), Terraria.Projectile.AI_182_FinalFractal(), Terraria.Projectile.AI_190_NightsEdge(), Terraria.Projectile.AI_191_TrueNightsEdge(), Terraria.Projectile.AI_203_StormLightning(), Terraria.Graphics.Light.TileLightScanner.ApplyTileLight(), Terraria.GameContent.Drawing.BackgroundGradientDrawer.Draw(), Terraria.Main.DrawBackground_DirtBackground(), Terraria.Main.DrawNPCDirect(), Terraria.Main.DrawProjDirect(), Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile_SlicedBlock(), Terraria.Dust.GetAlpha(), Terraria.Lighting.GetColor(), Terraria.Lighting.GetColor(), Terraria.Lighting.GetColorClamped(), Terraria.GameContent.Events.MoonlordDeathDrama.MoonlordPiece.GetLight(), ReLogic.Peripherals.RGB.RgbDevice.ProcessLedColor(), Terraria.Dust.UpdateDust(), Terraria.Mount.UpdateEffects(), Terraria.Mount.UpdateFrame(), Terraria.Graphics.Shaders.ArmorShaderData.UseColor(), Terraria.Graphics.Shaders.HairShaderData.UseColor(), Terraria.Graphics.Shaders.MiscShaderData.UseColor(), Terraria.Graphics.Shaders.ScreenShaderData.UseColor(), Terraria.Graphics.Shaders.ArmorShaderData.UseSecondaryColor(), Terraria.Graphics.Shaders.HairShaderData.UseSecondaryColor(), Terraria.Graphics.Shaders.MiscShaderData.UseSecondaryColor(), Terraria.Graphics.Shaders.ScreenShaderData.UseSecondaryColor(), and Terraria.GameContent.LeashedEntities.FairyLeashedCritter.VisualEffects().