Terraria Decompiled: Microsoft.Xna.Framework.Color.Black
Black
Color Microsoft.Xna.Framework.Color.Black = new Color(4278190080U) static get private set
Definition at line 232 of file Color.cs.
        {
            [CompilerGenerated]
            get
            {
                return Color.<Black>k__BackingField;
            }
            [CompilerGenerated]
            private set
            {
                Color.<Black>k__BackingField = value;
            }
        } = new Color(4278190080U);
Referenced by Terraria.NPC.AI(), Terraria.GameContent.Creative.CreativePowers.ModifyTimeRate.Button_OnMouseOut(), Terraria.GameContent.Creative.CreativePowers.ModifyWindDirectionAndStrength.Button_OnMouseOut(), Terraria.GameContent.Creative.CreativePowers.ModifyRainPower.Button_OnMouseOut(), Terraria.GameContent.Creative.CreativePowers.SpawnRateSliderPerPlayerPower.Button_OnMouseOut(), Terraria.DelegateMethods.ColorLerp_BlackToWhite(), Terraria.Utils.ColorLerp_BlackToWhite(), Terraria.Graphics.Renderers.LegacyPlayerRenderer.CreateOutlines(), Terraria.Graphics.Renderers.MapHeadRenderer.CreateOutlines(), Terraria.Mount.DoFailedDismountDust(), Terraria.Mount.DoSpawnDust(), Terraria.Map.TeleportPylonsMapLayer.Draw(), Terraria.Graphics.Renderers.FakeFishParticle.Draw(), Terraria.GameContent.UI.States.UIAchievementsMenu.Draw(), Terraria.GameContent.UI.States.UICharacterCreation.Draw(), Terraria.GameContent.UI.WorkshopPublishingIndicator.Draw(), Terraria.GameContent.Skies.MoonLordSky.Draw(), Terraria.GameContent.Skies.NebulaSky.Draw(), Terraria.GameContent.Skies.SolarSky.Draw(), Terraria.GameContent.Skies.StardustSky.Draw(), Terraria.GameContent.Skies.VortexSky.Draw(), Terraria.GameContent.UI.Minimap.MinimapFrame.DrawBackground(), Terraria.Main.DrawBackgroundBlackFill(), Terraria.Main.DrawBlack(), Terraria.Utils.DrawBorderStringBig(), Terraria.GameContent.UI.NPCChatPanel.DrawButtons(), Terraria.Graphics.Capture.CaptureInterface.DrawCameraLock(), Terraria.Main.DrawClothesWindow(), Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.GameContent.UI.WiresUI.WiresRadial.DrawCursorArea(), Terraria.GameContent.UI.UIDust.DrawDust(), Terraria.Main.DrawDust(), Terraria.Main.DrawHairWindow(), Terraria.GameContent.UI.BigProgressBar.BigProgressBarHelper.DrawHealthText(), Terraria.Main.DrawInfoAccs(), Terraria.Main.DrawInterface_14_EntityHealthBars(), Terraria.Main.DrawInterface_GolfBallIndicator(), Terraria.Main.DrawInventory(), Terraria.GameContent.UI.UIPopupTextManager.DrawItemTextPopups(), Terraria.PopupText.DrawItemTextPopups(), Terraria.Main.DrawMenu(), Terraria.UI.ItemSlot.DrawMoney(), Terraria.Main.DrawMouseOver(), Terraria.Main.DrawNPCChatButtons(), Terraria.Main.DrawNPCDirect(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_21_Head_TheFace_Eyelid(), Terraria.GameContent.UI.NewMultiplayerClosePlayersOverlay.PlayerOffScreenCache.DrawPlayerDistance(), Terraria.GameContent.UI.LegacyMultiplayerClosePlayersOverlay.DrawPlayerName(), Terraria.GameContent.UI.LegacyMultiplayerClosePlayersOverlay.DrawPlayerName2(), Terraria.GameContent.UI.NewMultiplayerClosePlayersOverlay.PlayerOnScreenCache.DrawPlayerName_WhenPlayerIsOnScreen(), Terraria.GameContent.UI.Elements.UIAchievementListItem.DrawProgressBar(), Terraria.Main.DrawProjDirect(), Terraria.GameContent.UI.CustomCurrencyManager.DrawSavings(), Terraria.GameContent.UI.CustomCurrencySingleCoin.DrawSavingsMoney(), Terraria.GameContent.UI.Elements.EmoteButton.DrawSelf(), Terraria.GameContent.UI.Elements.GroupOptionButton< T >.DrawSelf(), Terraria.GameContent.UI.Elements.UIAchievementListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIDifficultyButton.DrawSelf(), Terraria.GameContent.UI.Elements.UIGenProgressBar.DrawSelf(), Terraria.GameContent.UI.Elements.UIHeader.DrawSelf(), Terraria.GameContent.UI.Elements.UIIconTextButton.DrawSelf(), Terraria.GameContent.UI.Elements.UIItemIcon.DrawSelf(), Terraria.GameContent.UI.Elements.UIResourcePackInfoButton< T >.DrawSelf(), Terraria.GameContent.UI.Elements.UISelectableTextPanel< T >.DrawSelf(), Terraria.GameContent.UI.States.UITextWrappingTest.TestElement.DrawSelf(), Terraria.Main.DrawSettingButton(), Terraria.Main.DrawSimpleSurfaceBackground(), Terraria.Main.DrawSplash(), Terraria.GameContent.UI.NPCChatPanel.DrawText(), Terraria.GameContent.UI.Elements.UIVerticalSlider.DrawValueBarDynamicWidth(), Terraria.Main.DrawVersionNumber(), Terraria.Main.DrawWhip(), Terraria.Main.DrawWithOutlines(), Terraria.GameContent.Drawing.DrawBlackHelper.EndStrip(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.FadedMouseOut(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.FadedMouseOut(), Terraria.GameContent.UI.States.UIAchievementsMenu.FadedMouseOut(), Terraria.GameContent.UI.States.UIBestiaryTest.FadedMouseOut(), Terraria.GameContent.UI.States.UICharacterCreation.FadedMouseOut(), Terraria.GameContent.UI.States.UICharacterSelect.FadedMouseOut(), Terraria.GameContent.UI.States.UIDebugCommandsList.FadedMouseOut(), Terraria.GameContent.UI.States.UIEmotesMenu.FadedMouseOut(), Terraria.GameContent.UI.States.UIManageControls.FadedMouseOut(), Terraria.GameContent.UI.States.UIReportsPage.FadedMouseOut(), Terraria.GameContent.UI.States.UIResourcePackInfoMenu.FadedMouseOut(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.FadedMouseOut(), Terraria.GameContent.UI.States.UIVirtualKeyboard.FadedMouseOut(), Terraria.GameContent.UI.States.UIWorkshopHub.FadedMouseOut(), Terraria.GameContent.UI.States.UIWorkshopSelectResourcePackToPublish.FadedMouseOut(), Terraria.GameContent.UI.States.UIWorkshopSelectWorldToPublish.FadedMouseOut(), Terraria.GameContent.UI.States.UIWorkshopWorldImport.FadedMouseOut(), Terraria.GameContent.UI.States.UIWorldCreation.FadedMouseOut(), Terraria.GameContent.UI.States.UIWorldCreationAdvanced.FadedMouseOut(), Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.FadedMouseOut(), Terraria.GameContent.UI.States.UIWorldSelect.FadedMouseOut(), Terraria.Projectile.GetAlpha(), Terraria.GameContent.Bestiary.MoonLordPortraitBackgroundProviderBestiaryInfoElement.GetBackgroundColor(), Terraria.Testing.DetailedFPS.GetColor(), Terraria.Projectile.HandleMovement(), Terraria.GameContent.AnOutlinedDrawRenderTargetContent.HandleUseRequest(), Terraria.Map.MapHelper.Initialize(), Terraria.Initializers.ChromaInitializer.Load(), Terraria.GameContent.UI.States.UIManageControls.ManageBorderGamepadOff(), Terraria.GameContent.UI.States.UIManageControls.ManageBorderGamepadOn(), Terraria.GameContent.UI.States.UIManageControls.ManageBorderGameplayOff(), Terraria.GameContent.UI.States.UIManageControls.ManageBorderGameplayOn(), Terraria.GameContent.UI.States.UIManageControls.ManageBorderKeyboardOff(), Terraria.GameContent.UI.States.UIManageControls.ManageBorderKeyboardOn(), Terraria.GameContent.UI.States.UIManageControls.ManageBorderMenuOff(), Terraria.GameContent.UI.States.UIManageControls.ManageBorderMenuOn(), Terraria.GameContent.DontStarveSeed.ModifyNightColor(), Terraria.GameContent.UI.Elements.UIIconTextButton.MouseOut(), Terraria.Main.MouseText_DrawBuffTooltip(), Terraria.Main.MouseText_DrawItemTooltip(), Terraria.GameContent.RGB.EmpressShader.ProcessHighDetail(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_BlackLightningHit(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_BlackLightningSmall(), Terraria.GameContent.ChromaHotkeyPainter.Step_QuickHeal(), Terraria.GameContent.UI.Elements.UIColoredSlider.UIColoredSlider(), Terraria.GameContent.UI.Elements.UIIconTextButton.UIIconTextButton(), Terraria.GameContent.UI.Chat.GlyphTagHandler.GlyphSnippet.UniqueDraw(), Terraria.GameContent.UI.Chat.ItemTagHandler.ItemSnippet.UniqueDraw(), Terraria.GameContent.ChromaHotkeyPainter.ReactiveRGBKey.Update(), Terraria.Player.Update(), Terraria.GameContent.Events.ScreenDarkness.Update(), Terraria.Main.UpdateAtmosphereTransparencyToSkyColor(), Terraria.GameContent.Creative.CreativePowers.DifficultySliderPower.UpdateSliderColorAndShowMultiplierMouseOver(), Terraria.UI.Chat.ChatManager.WaveColor(), and Terraria.Player.WingFrame().