Terraria Decompiled: Microsoft.Xna.Framework.Color.Transparent
Transparent
Color Microsoft.Xna.Framework.Color.Transparent = new Color(0U) static get private set
Definition at line 96 of file Color.cs.
        {
            [CompilerGenerated]
            get
            {
                return Color.<Transparent>k__BackingField;
            }
            [CompilerGenerated]
            private set
            {
                Color.<Transparent>k__BackingField = value;
            }
        } = new Color(0U);
Referenced by Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.Projectile.AI_001(), Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_006_Worms(), Terraria.Projectile.AI_009_MagicMissiles(), Terraria.Projectile.AI_067_FreakingPirates(), Terraria.Projectile.AI_075(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.Projectile.AI_113_TargetSticker(), Terraria.NPC.AI_117_BloodNautilus(), Terraria.Projectile.AI_155_MysticSnakeCoil(), Terraria.Projectile.AI_155_SpawnRopeIn(), Terraria.Projectile.AI_156_GetColor(), Terraria.Projectile.AI_165_Whip(), Terraria.GameContent.UI.Elements.UIBestiaryEntryInfoPage.AppendBorderOverEverything(), Terraria.Graphics.Effects.FilterManager.BeginCapture(), Terraria.Graphics.Capture.CaptureCamera.BeginDrawCapture(), Terraria.DataStructures.PlayerDrawSet.BoringSetup(), Terraria.WorldGen.coatingColor(), Terraria.GameContent.UI.States.UICharacterCreation.CreateHSLSliderButtonBase(), Terraria.Graphics.Renderers.LegacyPlayerRenderer.CreateOutlines(), Terraria.Graphics.Renderers.MapHeadRenderer.CreateOutlines(), Terraria.GameContent.Bestiary.NPCPortraitInfoElement.CreateStarsContainer(), Terraria.Mount.DoFailedDismountDust(), Terraria.Mount.DoSpawnDust(), Terraria.Mount.Draw(), Terraria.UI.ItemSlot.Draw(), Terraria.Main.DrawDefenseCounter(), Terraria.Main.DrawInterface_35_YouDied(), Terraria.Main.DrawItem(), Terraria.UI.ItemSlot.DrawItemIcon(), Terraria.PopupText.DrawItemTextPopups(), Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileGrassInWind(), Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileVinesInWind(), Terraria.Main.DrawNPCDirect(), Terraria.Main.DrawNPCDirect_Deerclops(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_21_1_Magiluminescence(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_21_Head(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_27_HeldItem(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_AddSelectionGlow(), Terraria.GameContent.UI.Elements.UIAchievementListItem.DrawProgressBar(), Terraria.Main.DrawProj_Flamethrower(), Terraria.Main.DrawProj_Flamethrower_Foxsparks(), Terraria.Main.DrawProjDirect(), Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile(), Terraria.DataStructures.PlayerDrawLayers.DrawStarboardRainbowTrail(), Terraria.Main.DrawSurfaceBG_DrawChangeOverlay(), Terraria.GameContent.Drawing.NextHorizonRenderer.DrawSurfaceLayer(), Terraria.Graphics.Capture.CaptureCamera.DrawTick(), Terraria.MapRenderer.DrawToMap(), Terraria.MapRenderer.DrawToMap_Section(), Terraria.Main.DrawWires(), Terraria.Graphics.Effects.FilterManager.EndCapture(), Terraria.Graphics.Renderers.BloodyExplosionParticle.FetchFromPool(), Terraria.Graphics.Renderers.GasParticle.FetchFromPool(), Terraria.Graphics.Renderers.PrettySparkleParticle.FetchFromPool(), Terraria.Projectile.GetAlpha(), Terraria.Projectile.GetCeleb2Color(), Terraria.DataStructures.PlayerDrawLayers.GetChickenBonesGlowColor(), Terraria.Dust.GetColor(), Terraria.Player.GetImmuneAlpha(), Terraria.DataStructures.PlayerDrawLayers.GetLunaGlowColor(), Terraria.Main.GetPlayerHeadBordersColor(), Terraria.GameContent.Drawing.TileDrawing.GetTileDrawData(), Terraria.Projectile.HandleMovement(), Terraria.GameContent.AnOutlinedDrawRenderTargetContent.HandleUseRequest(), Terraria.GameContent.PlayerQueenSlimeMountTextureContent.HandleUseRequest(), Terraria.GameContent.PlayerRainbowWingsTextureContent.HandleUseRequest(), Terraria.GameContent.PlayerTitaniumStormBuffTextureContent.HandleUseRequest(), Terraria.NPC.HitEffect(), Terraria.Map.MapHelper.Initialize(), Terraria.Player.ItemCheck_EmitUseVisuals(), Terraria.DelegateMethods.LightningLaserDraw(), Terraria.GameContent.UI.States.UICharacterCreation.MakeCategoriesBar(), Terraria.GameContent.UI.States.UICharacterCreation.MakeClothStylesMenu(), Terraria.GameContent.UI.Elements.UIDebugCommandItem.MouseOut(), Terraria.Dust.NewDust(), Terraria.GameContent.UI.States.UIManageControls.OnInitialize(), Terraria.GameContent.TilePaintSystemV2.ARenderTargetHolder.PrepareTextureIfNecessary(), Terraria.GameContent.Bestiary.FilterProviderInfoElement.ProvideUIElement(), Terraria.GameContent.Bestiary.FlavorTextBestiaryInfoElement.ProvideUIElement(), Terraria.GameContent.Bestiary.NPCKillCounterInfoElement.ProvideUIElement(), Terraria.GameContent.Bestiary.UnlockProgressDisplayBestiaryInfoElement.ProvideUIElement(), Terraria.DelegateMethods.RainbowLaserDraw(), Terraria.DelegateMethods.SpreadDry(), Terraria.DelegateMethods.SpreadHoney(), Terraria.DelegateMethods.SpreadLava(), Terraria.DelegateMethods.SpreadTile(), Terraria.DelegateMethods.SpreadWater(), Terraria.DelegateMethods.TurretLaserDraw(), Terraria.GameContent.UI.Elements.UIDebugCommandItem.UIDebugCommandItem(), Terraria.GameContent.UI.Elements.UISearchBar.UISearchBar(), Terraria.GameContent.UI.States.UIVirtualKeyboard.UIVirtualKeyboard(), Terraria.Graphics.Renderers.BloodyExplosionParticle.Update(), Terraria.Graphics.Renderers.GasParticle.Update(), Terraria.Graphics.WorldSceneLayerTarget.UpdateContent(), Terraria.Dust.UpdateDust(), and Terraria.GameContent.Drawing.HorizonHelper.UpdateSunVisibility().