Terraria Decompiled: Microsoft.Xna.Framework.Color.ToString
ToString()
override string Microsoft.Xna.Framework.Color.ToString () inline
Definition at line 2654 of file Color.cs.
        {
            StringBuilder stringBuilder = new StringBuilder(25);
            stringBuilder.Append("{R:");
            stringBuilder.Append(this.R);
            stringBuilder.Append(" G:");
            stringBuilder.Append(this.G);
            stringBuilder.Append(" B:");
            stringBuilder.Append(this.B);
            stringBuilder.Append(" A:");
            stringBuilder.Append(this.A);
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
References Microsoft.Xna.Framework.Color.A, System.Text.StringBuilder.Append(), Microsoft.Xna.Framework.Color.B, Microsoft.Xna.Framework.Color.G, Microsoft.Xna.Framework.Color.R, and System.Text.StringBuilder.ToString().
Referenced by Microsoft.Xna.Framework.Graphics.VertexPositionColor.ToString(), and Microsoft.Xna.Framework.Graphics.VertexPositionColorTexture.ToString().