Terraria Decompiled: Microsoft.Xna.Framework.Color.White
White
Color Microsoft.Xna.Framework.Color.White = new Color(uint.MaxValue) static get private set
Definition at line 2425 of file Color.cs.
        {
            [CompilerGenerated]
            get
            {
                return Color.<White>k__BackingField;
            }
            [CompilerGenerated]
            private set
            {
                Color.<White>k__BackingField = value;
            }
        } = new Color(uint.MaxValue);
Referenced by Terraria.GameContent.UI.States.UIWorldGenDebug.AddButton(), Terraria.GameContent.UI.States.UIWorkshopHub.AddHorizontalSeparator(), Terraria.GameContent.UI.States.UIWorldCreation.AddHorizontalSeparator(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.AddHorizontalSeparator(), Terraria.GameContent.UI.States.UIWorldCreationAdvanced.AddSeedButtons(), Terraria.GameContent.UI.States.UIWorldCreation.AddWorldDifficultyOptions(), Terraria.GameContent.UI.States.UIWorldCreation.AddWorldEvilOptions(), Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.Projectile.AI_001(), Terraria.NPC.AI_003_Fighters(), Terraria.Projectile.AI_067_FreakingPirates(), Terraria.Projectile.AI_113_TargetSticker(), Terraria.Projectile.AI_147_Celeb2Rocket(), Terraria.Projectile.AI_147_Explosion(), Terraria.Projectile.AI_162_TigerPounce(), Terraria.Projectile.AI_165_Whip(), Terraria.Projectile.AI_168_FirstFractal(), Terraria.Projectile.AI_171_GetColor(), Terraria.Projectile.AI_173_GetColor(), Terraria.Projectile.AI_177_IceWhipSlicer(), Terraria.Projectile.AI_179_FairyQueenLance(), Terraria.Projectile.AI_190_NightsEdge(), Terraria.Projectile.AI_191_TrueNightsEdge(), ReLogic.Graphics.BasicDebugDrawer.BasicDebugDrawer(), Microsoft.Xna.Framework.Graphics.BlendState.BlendState(), Terraria.DataStructures.PlayerDrawHeadSet.BoringSetup(), Terraria.DataStructures.PlayerDrawSet.BoringSetup(), Terraria.GameContent.UI.Elements.UIBestiarySortingOptionsGrid.BuildGrid(), Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.BuildPage(), Terraria.Player.ChatColor(), Terraria.DelegateMethods.ColorLerp_BlackToWhite(), Terraria.Utils.ColorLerp_BlackToWhite(), Terraria.DelegateMethods.ColorLerp_HSL_O(), Terraria.GameContent.Animations.StardewValleyAnimation.ComposeAnimation(), Terraria.GameContent.Drawing.ParticleOrchestrator.CopperSlimeEffect(), Terraria.GameContent.UI.States.UIWorldCreationAdvanced.CreateButton(), Terraria.GameContent.Creative.CreativePowersHelper.CreateCategoryButton< T >(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.CreateOffsetButton(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.CreatePackToggleButton(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.CreatePublicSettingsRow(), Terraria.GameContent.Creative.CreativePowersHelper.CreateSimpleButton(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.CreateSteamDisclaimer(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.CreateTagOptionsPanel(), Terraria.GameContent.Creative.CreativePowersHelper.CreateToggleButton(), Terraria.Player.DashMovement(), Terraria.Main.DoDraw(), Terraria.Main.DoDraw_Tiles_NonSolid(), Terraria.Main.DoDraw_Tiles_Solid(), Terraria.Main.DoDraw_WallsAndBlacks(), Terraria.Mount.DoSpawnDust(), Terraria.GameContent.UI.GameTipsDisplay.Draw(), Terraria.Testing.DetailedFPS.Draw(), Terraria.GameContent.Bestiary.CustomEntryIcon.Draw(), Terraria.GameContent.Bestiary.UnlockableNPCEntryIcon.Draw(), Terraria.Mount.Draw(), Terraria.IngameOptions.Draw(), Terraria.GameContent.Animations.Segments.LocalizedTextSegment.Draw(), Terraria.GameContent.Animations.Segments.EmoteSegment.Draw(), Terraria.Map.TeleportPylonsMapLayer.Draw(), Terraria.Graphics.Renderers.CreativeSacrificeParticle.Draw(), Terraria.Graphics.Renderers.FakeFishParticle.Draw(), Terraria.GameContent.UI.EmoteBubble.Draw(), Terraria.Graphics.Capture.CaptureInterface.Draw(), Terraria.Graphics.Capture.CaptureInterface.ModeChangeSettings.Draw(), Terraria.GameContent.UI.IssueReportsIndicator.Draw(), Terraria.GameContent.UI.WorkshopPublishingIndicator.Draw(), Terraria.UI.NetDiagnosticsUI.Draw(), Terraria.GameContent.Skies.MartianSky.Draw(), Terraria.GameContent.Skies.NebulaSky.Draw(), Terraria.GameContent.Skies.SolarSky.Draw(), Terraria.GameContent.Skies.StardustSky.Draw(), Terraria.GameContent.Skies.VortexSky.Draw(), Terraria.UI.ItemSlot.Draw(), Terraria.GameContent.UI.ResourceSets.ResourceDrawSettings.Draw(), Terraria.DataStructures.TitleLinkButton.Draw(), Terraria.GameContent.UI.Minimap.MinimapFrame.Button.Draw(), Terraria.Graphics.Renderers.LittleFlyingCritterParticle.Draw_ButterFly(), Terraria.GameContent.Drawing.TileDrawing.DrawAnimatedTile_AdjustForVisionChangers(), Terraria.Main.DrawBestiaryIcon(), Terraria.Main.DrawBlockReplacementIcon(), Terraria.Graphics.Capture.CaptureInterface.ModeDragBounds.DrawBound(), Terraria.Main.DrawBuilderAccToggles(), Terraria.Graphics.Capture.CaptureInterface.DrawButtons(), Terraria.Graphics.Capture.CaptureInterface.DrawCameraLock(), Terraria.UI.AchievementAdvisor.DrawCard(), Terraria.GameContent.UI.NewCraftingUI.DrawChildren(), Terraria.Map.MapOverlayDrawContext.DrawClamped(), Terraria.Main.DrawClothesWindow(), Terraria.UI.Chat.ChatManager.DrawColorCodedString(), Terraria.DataStructures.PlayerDrawLayers.DrawCompositeArmorPiece(), Terraria.UI.NetDiagnosticsUI.DrawCounter(), Terraria.UI.CraftingUI.DrawCraftFromNearbyChestsToggle(), Terraria.Main.DrawCursor(), Terraria.Graphics.Capture.CaptureInterface.ModeEdgeSelection.DrawCursors(), Terraria.Dust.DrawDebugBox(), Terraria.Main.DrawDefenseCounter(), Terraria.TimeLogger.DrawDelta(), Terraria.GameContent.UI.UIDust.DrawDust(), Terraria.Main.DrawDust(), Terraria.Main.DrawEmoteBubblesButton(), Terraria.TimeLogger.DrawEntryData(), Terraria.TimeLogger.DrawExtras(), Terraria.GameContent.UI.BigProgressBar.BigProgressBarHelper.DrawFancyBar(), Terraria.GameContent.UI.BigProgressBar.BigProgressBarHelper.DrawFancyBar(), Terraria.GameContent.UI.Elements.UIGenProgressBar.DrawFilling(), Terraria.GameContent.UI.WiresUI.WiresRadial.DrawFlower(), Terraria.GameContent.UI.Minimap.MinimapFrame.DrawForeground(), Terraria.Testing.DetailedFPS.DrawFPSBox(), Terraria.Testing.DetailedFPS.DrawFrame(), Terraria.Main.DrawGamepadInstructions(), Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.DrawGlowRing(), Terraria.UI.BannerClaimingUI.DrawGridToggle(), Terraria.UI.CraftingUI.DrawGridToggle(), Terraria.Main.DrawHairWindow(), Terraria.GameContent.UI.BigProgressBar.BigProgressBarHelper.DrawHealthText(), Terraria.GameContent.Drawing.NextHorizonRenderer.DrawHorizon(), Terraria.Main.DrawHotbarLockIcon(), Terraria.GameContent.UI.Elements.UIResourcePack.DrawIcon(), Terraria.Main.DrawIMEPanel(), Terraria.Main.DrawInfoAccs(), Terraria.UI.InGamePopups.AchievementUnlockedPopup.DrawInGame(), Terraria.UI.InGamePopups.PlayerWantsToJoinGamePopup.DrawInGame(), Terraria.UI.InGamePopups.PlayerWantsToJoinGamePopup.DrawInNotificationsArea(), Terraria.Main.DrawInterface_14_EntityHealthBars(), Terraria.Main.DrawInterface_36_Cursor(), Terraria.Main.DrawInterface_38_MouseCarriedObject(), Terraria.Main.DrawInterface_40_InteractItemIcon(), Terraria.Main.DrawInterface_6_TileGridOption(), Terraria.Main.DrawInterface_GolfBallIndicator(), Terraria.Main.DrawInterface_Resources_GolfPower(), Terraria.Main.DrawInvasionProgress(), Terraria.Main.DrawInventory(), Terraria.Main.DrawItem(), Terraria.UI.CoinSlot.DrawItemCoin(), Terraria.UI.ItemSlot.DrawItemIcon(), Terraria.PopupText.DrawItemTextPopups(), Terraria.IngameOptions.DrawLeftSide(), Terraria.GameContent.UI.WiresUI.WiresRadial.DrawLine(), Terraria.Main.DrawLoadoutButtons(), Terraria.Main.DrawMap(), Terraria.Main.DrawMapFullscreenBackground(), Terraria.GameContent.CoinLossRevengeSystem.RevengeMarker.DrawMapIcon(), Terraria.Main.DrawMapIcons_LastGolfballHit(), Terraria.Main.DrawMapIcons_PotionOfReturnAppearAfterUsePosition(), Terraria.Main.DrawMapIcons_PotionOfReturnHomePosition(), Terraria.Graphics.Capture.CaptureInterface.ModeEdgeSelection.DrawMarkedArea(), Terraria.GameContent.Drawing.TileDrawing.DrawMasterTrophies(), Terraria.Main.DrawMenu(), Terraria.DataStructures.PlayerDrawLayers.DrawMeowcartTrail(), Terraria.UI.ItemSlot.DrawMoney(), Terraria.Main.DrawMouseOver(), Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileGrassInWind(), Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileVinesInWind(), Terraria.Main.DrawNetplayStatusText(), Terraria.Utils.DrawNotificationIcon(), Terraria.Main.DrawNPCChatBottomRightItem(), Terraria.Main.DrawNPCDirect(), Terraria.Main.DrawNPCDirect_Deerclops(), Terraria.Main.DrawNPCDirect_Faeling(), Terraria.Main.DrawNPCDirect_HallowBoss(), Terraria.Main.DrawNPCHousesInUI(), Terraria.Main.DrawNPCPortrait(), Terraria.Main.DrawPageIcons(), Terraria.GameContent.UI.Elements.UICharacterListItem.DrawPanel(), Terraria.GameContent.UI.Elements.UIDebugCommandItem.DrawPanel(), Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem.DrawPanel(), Terraria.GameContent.UI.Elements.UIWorldListItem.DrawPanel(), Terraria.GameContent.UI.Elements.UIWorkshopPublishResourcePackListItem.DrawPanel(), Terraria.GameContent.UI.Elements.UIWorkshopPublishWorldListItem.DrawPanel(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_05_2_SafemanSun(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_05_ForbiddenSetRing(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_09_Wings(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_21_Head(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_27_HeldItem(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_35_IceBarrier(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_DrawSelectionRect(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_DrawSelectionRect(), Terraria.Main.DrawPlayerChat(), Terraria.GameContent.UI.NewMultiplayerClosePlayersOverlay.PlayerOffScreenCache.DrawPlayerHead(), Terraria.Graphics.Renderers.MapHeadRenderer.DrawPlayerHead(), Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayerStoned(), Terraria.TileObject.DrawPreview(), Terraria.Main.DrawProj_DeadCellsFlintSlash(), Terraria.Main.DrawProj_Excalibur(), Terraria.Main.DrawProj_FlailChains(), Terraria.Main.DrawProj_LightsBane(), Terraria.Main.DrawProj_NightsEdge(), Terraria.Main.DrawProj_Spear(), Terraria.Main.DrawProj_TerraBlade2(), Terraria.Main.DrawProj_TerraBlade2Shot(), Terraria.Main.DrawProj_TheHorsemansBlade(), Terraria.Main.DrawProj_TrueExcalibur(), Terraria.Main.DrawProj_TrueNightsEdge(), Terraria.Main.DrawProjDirect(), Terraria.Main.DrawPVPIcons(), Terraria.UI.ItemSlot.DrawRadialCircular(), Terraria.UI.ItemSlot.DrawRadialDpad(), Terraria.UI.ItemSlot.DrawRadialQuicks(), Terraria.GameContent.UI.NewCraftingUI.DrawRecipeSlot(), Terraria.IngameOptions.DrawRightSide(), Terraria.GameContent.Drawing.TileDrawing.DrawRisingVineStrip(), Terraria.UI.ItemSlot.DrawSavings(), Terraria.GameContent.UI.CustomCurrencyManager.DrawSavings(), Terraria.GameContent.UI.CustomCurrencySingleCoin.DrawSavingsMoney(), Terraria.GameContent.UI.Elements.EmoteButton.DrawSelf(), Terraria.GameContent.UI.Elements.GroupOptionButton< T >.DrawSelf(), Terraria.GameContent.UI.Elements.UIAchievementListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIBestiaryEntryIcon.DrawSelf(), Terraria.GameContent.UI.Elements.UICharacter.DrawSelf(), Terraria.GameContent.UI.Elements.UICharacterListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UICharacterNameButton.DrawSelf(), Terraria.GameContent.UI.Elements.UIClothStyleButton.DrawSelf(), Terraria.GameContent.UI.Elements.UIColoredImageButton.DrawSelf(), Terraria.GameContent.UI.Elements.UIColoredSlider.DrawSelf(), Terraria.GameContent.UI.Elements.UIDebugCommandItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIDifficultyButton.DrawSelf(), Terraria.GameContent.UI.Elements.UIGenProgressBar.DrawSelf(), Terraria.GameContent.UI.Elements.UIHairStyleButton.DrawSelf(), Terraria.GameContent.UI.Elements.UIHeader.DrawSelf(), Terraria.GameContent.UI.Elements.UIIconTextButton.DrawSelf(), Terraria.GameContent.UI.Elements.UIItemIcon.DrawSelf(), Terraria.GameContent.UI.Elements.UIKeybindingListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIKeybindingSimpleListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIKeybindingSliderItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIKeybindingToggleListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIResourcePack.DrawSelf(), Terraria.GameContent.UI.Elements.UIResourcePackInfoButton< T >.DrawSelf(), Terraria.GameContent.UI.Elements.UIScrollbar.DrawSelf(), Terraria.GameContent.UI.Elements.UISelectableTextPanel< T >.DrawSelf(), Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIWorkshopPublishResourcePackListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIWorkshopPublishWorldListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIWorldCreationPreview.DrawSelf(), Terraria.GameContent.UI.Elements.UIWorldListItem.DrawSelf(), Terraria.GameContent.UI.States.UITextWrappingTest.TestElement.DrawSelf(), Terraria.GameContent.UI.States.UIVirtualKeyboard.DrawSelf(), Terraria.Main.DrawSettingButton(), Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile(), Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile_Flames(), Terraria.GameContent.UI.NewCraftingUI.ItemGrid.DrawSlot(), Terraria.Main.DrawSmartCursor(), Terraria.Main.DrawSplash(), Terraria.DataStructures.PlayerDrawLayers.DrawStarboardRainbowTrail(), Terraria.Main.DrawSunAndMoon(), Terraria.GameContent.Drawing.TileDrawing.DrawTeleportationPylons(), Terraria.GameContent.OutlinedDrawRenderTargetContent.DrawTheContent(), Terraria.Graphics.Capture.CaptureCamera.DrawTick(), Terraria.GameContent.Drawing.TileDrawing.DrawTiles_EmitParticles(), Terraria.GameContent.Drawing.TileDrawing.DrawTiles_GetLightOverride(), Terraria.TimeLogger.DrawTimes(), Terraria.GameContent.PotionOfReturnGateHelper.DrawToDrawData(), Terraria.GameContent.VoidLensHelper.DrawToDrawData(), Terraria.GameContent.Creative.CreativeUI.DrawToggleButton(), Terraria.MapRenderer.DrawToMap_Section(), Terraria.Main.DrawTorchBiomeSwapIcon(), Terraria.GameContent.Drawing.TileDrawing.DrawTrees(), Terraria.Main.DrawUnderworldBackgroundLayer(), Terraria.IngameOptions.DrawValue(), Terraria.IngameOptions.DrawValueBar(), Terraria.GameContent.UI.Elements.UIColoredSlider.DrawValueBar(), Terraria.GameContent.UI.Elements.UIColoredSliderSimple.DrawValueBarDynamicWidth(), Terraria.GameContent.UI.Elements.UIVerticalSlider.DrawValueBarDynamicWidth(), Terraria.GameContent.Drawing.TileDrawing.DrawVineStrip(), Terraria.Main.DrawWallOfBoulders(), Terraria.Main.DrawWallOfCopperShortswords(), Terraria.GameContent.Drawing.WallDrawing.DrawWalls(), Terraria.Graphics.Capture.CaptureInterface.ModeChangeSettings.DrawWaterChoices(), Terraria.WaterfallManager.DrawWaterfall(), Terraria.Main.DrawWhip(), Terraria.Main.DrawWires(), Terraria.Main.DrawWithOutlines(), Terraria.GameContent.Drawing.ParticleOrchestrator.ElderSlimeEffect(), Terraria.Projectile.EmitEnchantmentVisualsAt(), Terraria.GameContent.Golf.GolfHelper.ContactListener.EmitGolfballExplosion_v1(), Terraria.GameContent.UI.Elements.EmotesGroupListItem.EmotesGroupListItem(), Terraria.Graphics.Effects.FilterManager.EndCapture(), Terraria.Graphics.Renderers.BloodyExplosionParticle.FetchFromPool(), Terraria.Graphics.Renderers.FadingParticle.FetchFromPool(), Terraria.Graphics.Renderers.RandomizedFrameParticle.FetchFromPool(), Terraria.Graphics.Renderers.ShockIconParticle.FetchFromPool(), Terraria.GameContent.UI.States.UIWorldGenDebug.GenPassElement.GenPassElement(), Terraria.Dust.GetAlpha(), Terraria.Item.GetAlpha(), Terraria.NPC.GetAlpha(), Terraria.Projectile.GetAlpha(), Terraria.NPC.GetBestiaryEntryColor(), Terraria.GameContent.Skies.AmbientSky.FadingSkyEntity.GetColor(), Terraria.GameContent.Skies.AmbientSky.HellBatsGoupSkyEntity.GetColor(), Terraria.GameContent.Skies.AmbientSky.NormalizedBackgroundLayerSpaceSkyEntity.GetColor(), Terraria.Lighting.GetColor(), Terraria.Lighting.GetColor(), Terraria.UI.ItemSlot.GetColorByLoadout(), Terraria.Main.GetColorForDifficulty(), Terraria.Projectile.GetConstellationColor(), Terraria.GameContent.UI.Elements.AWorldListItem.GetDifficulty(), Terraria.Projectile.GetFairyQueenWeaponsColorFull(), Terraria.GameContent.Drawing.TileDrawing.GetFinalLight(), Terraria.Player.GetHairColor(), Terraria.GameContent.UI.States.UICharacterCreation.GetHSLSliderColorAt(), Terraria.Main.GetInputText(), Terraria.GameContent.Events.MoonlordDeathDrama.MoonlordPiece.GetLight(), Terraria.Item.GetPhaseColor(), Terraria.Item.GetPopupRarityColor(), Terraria.GameContent.PortalHelper.GetPortalColor(), Terraria.UI.Chat.ChatManager.GetStringSize(), Terraria.GameContent.Drawing.TileDrawing.GetTileDrawData(), Terraria.GameContent.UI.States.UICharacterCreation.GetVoicePitchColorAt(), Terraria.GameContent.UI.Chat.GlyphTagHandler.GlyphSnippet.GlyphSnippet(), Terraria.GameContent.UI.Chat.GlyphTagHandler.GlyphSnippet.GlyphSnippet(), Terraria.GameContent.UI.Elements.GroupOptionButton< T >.GroupOptionButton(), Terraria.Projectile.HandleMovement(), Terraria.GameContent.AnOutlinedDrawRenderTargetContent.HandleUseRequest(), Terraria.GameContent.PlayerQueenSlimeMountTextureContent.HandleUseRequest(), Terraria.GameContent.PlayerRainbowWingsTextureContent.HandleUseRequest(), Terraria.GameContent.PlayerTitaniumStormBuffTextureContent.HandleUseRequest(), Terraria.NPC.HitEffect(), Terraria.Main.Initialize_AlmostEverything(), Terraria.GameContent.Liquid.LiquidRenderer.InternalPrepareDraw(), Terraria.Player.ItemCheck(), Terraria.Player.ItemCheck_ApplyUseStyle(), Terraria.Player.ItemCheck_EmitUseVisuals(), Terraria.UI.ItemSlot.ItemSlot(), Terraria.Projectile.LightDisc_Bounce(), Terraria.Initializers.ChromaInitializer.Load(), Terraria.Initializers.ChromaInitializer.LoadSpecialRulesFor_GameSense_Keyboard(), Terraria.GameContent.UI.States.UICharacterCreation.MakeCategoriesBar(), Terraria.GameContent.UI.States.UICharacterCreation.MakeClothStylesMenu(), Terraria.GameContent.UI.States.UIWorldCreation.MakeInfoMenu(), Terraria.GameContent.UI.Elements.UIIconTextButton.MouseOver(), Terraria.Main.MouseText_DrawItemTooltip_GetItemNameColor(), Terraria.Player.OverheadMessage.NewMessage(), Terraria.PopupText.NewText(), Terraria.GameContent.UI.Chat.LegacyChatMonitor.NewTextMultiline(), Terraria.WorldGen.paintColor(), Terraria.TimeLogger.PerformanceColor(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_ClothierChasingTruffle(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_DryadTurningToTree(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_AnglerAndPirateTalkAboutFish(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_DemolitionistAndArmsDealerArguingThenNurseComes(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_DryadSayingByeToTavernKeep(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_GuideRunningFromZombie(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_MerchantAndTravelingMerchantTryingToSellJunk(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_SantaAndTaxCollectorThrowingPresents(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_SkeletonMerchantSearchesThroughBones(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_SteampunkerRepairingCyborg(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_WitchDoctorGoingToHisPeople(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_WizardPartyGirlDyeTraderAndPainterPartyWithBunnies(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_ZoologistAndPetsAnnoyGolfer(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_GuideEmotingAtRainbowPanel(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_PrincessAndEveryoneThanksPlayer(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_SantaItemExample(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_TinkererAndMechanic(), Terraria.GameContent.TilePaintSystemV2.ARenderTargetHolder.PrepareTextureIfNecessary(), Terraria.GameContent.Bestiary.NPCPortraitInfoElement.ProvideUIElement(), Terraria.GameContent.UI.States.UIWorldCreationAdvanced.RefreshSecretSeedButton(), ReLogic.Peripherals.RGB.RgbKey.RgbKey(), Terraria.Player.RocketBootVisuals(), Terraria.Main.SetBackColor(), Terraria.GameContent.UI.Elements.UISearchBar.SetContents(), Terraria.GameContent.UI.Elements.UICharacterNameButton.SetContents(), Terraria.GameContent.Liquid.LiquidRenderer.SetShimmerVertexColors(), Terraria.DelegateMethods.Minecart.SparksTerraFart(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_CattivaHit(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsBarnacleShotFiring(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsDownDashExplosion(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_GasTrap(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_Keybrand(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ShimmerArrow(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_SilverBulletSparkle(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_StormLightning(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_StormLightningWindup(), Terraria.DelegateMethods.Minecart.SpawnFartCloud(), Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnLightningExplosionDust(), Terraria.GameContent.Shaders.WaterShaderData.StepLiquids(), Terraria.Graphics.FinalFractalHelper.StripColors(), Terraria.Graphics.FlameLashDrawer.StripColors(), Terraria.Graphics.MagicMissileDrawer.StripColors(), Terraria.Graphics.RainbowRodDrawer.StripColors(), Terraria.Graphics.FinalFractalHelper.FinalFractalProfile.StripDust(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.TEDisplayDoll(), Terraria.GameContent.Tile_Entities.TEHatRack.TEHatRack(), Terraria.Main.TeleportEffect(), Terraria.GameContent.Drawing.HorizonHelper.Test_DrawSmallTarget(), Terraria.Main.TryGetAmmo(), Terraria.WaterfallManager.TrySparkling(), Terraria.GameContent.UI.Elements.UIBestiaryNPCEntryPortrait.UIBestiaryNPCEntryPortrait(), Terraria.GameContent.UI.Elements.UIColoredImageButton.UIColoredImageButton(), Terraria.GameContent.UI.Elements.UIColoredSlider.UIColoredSlider(), Terraria.GameContent.UI.Elements.UIHorizontalSeparator.UIHorizontalSeparator(), Terraria.GameContent.UI.Elements.UIIconTextButton.UIIconTextButton(), Terraria.GameContent.UI.Elements.UIImageFramed.UIImageFramed(), Terraria.GameContent.UI.Elements.UIVerticalSeparator.UIVerticalSeparator(), Terraria.GameContent.UI.States.UIVirtualKeyboard.UIVirtualKeyboard(), Terraria.GameContent.UI.Elements.UIWorkshopPublishResourcePackListItem.UIWorkshopPublishResourcePackListItem(), Terraria.GameContent.UI.Elements.UIWorkshopPublishWorldListItem.UIWorkshopPublishWorldListItem(), Terraria.GameContent.UI.Chat.ItemTagHandler.ItemSnippet.UniqueDraw(), Terraria.Player.Update(), Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid.UpdateAvailability(), Terraria.GameContent.Creative.CreativePowers.DifficultySliderPower.UpdateSliderColorAndShowMultiplierMouseOver(), Terraria.GameContent.Drawing.HorizonHelper.UpdateSunVisibility(), Terraria.GameContent.Creative.CreativePowersHelper.UpdateUnlockStateByPowerInternal(), Terraria.GameContent.UI.States.UIVirtualKeyboard.ValidateText(), and Terraria.Player.WingFrame().