Terraria Decompiled: Microsoft.Xna.Framework.Color.ToVector4
ToVector4()
Vector4 Microsoft.Xna.Framework.Color.ToVector4 () inline
Implements Microsoft.Xna.Framework.Graphics.PackedVector.IPackedVector< TPacked >.
Definition at line 2593 of file Color.cs.
        {
            return new Vector4((float)this.R / 255f, (float)this.G / 255f, (float)this.B / 255f, (float)this.A / 255f);
        }
References Microsoft.Xna.Framework.Color.A, Microsoft.Xna.Framework.Color.B, Microsoft.Xna.Framework.Color.G, and Microsoft.Xna.Framework.Color.R.
Referenced by Terraria.GameContent.RGB.BrainShader.BrainShader(), Terraria.GameContent.RGB.CavernShader.CavernShader(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.Clear(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.Clear(), Terraria.GameContent.RGB.CorruptSurfaceShader.CorruptSurfaceShader(), Terraria.GameContent.RGB.CorruptSurfaceShader.CorruptSurfaceShader(), Terraria.GameContent.RGB.DD2Shader.DD2Shader(), Terraria.GameContent.RGB.DeathShader.DeathShader(), Terraria.GameContent.RGB.DesertShader.DesertShader(), Terraria.Mount.Draw(), Terraria.Graphics.Renderers.LittleFlyingCritterParticle.Draw_ButterFly(), Terraria.Graphics.Renderers.LittleFlyingCritterParticle.Draw_Fly(), Terraria.Utils.DrawLine(), Terraria.Main.DrawProjDirect(), Terraria.Main.DrawSimpleSurfaceBackground(), Terraria.GameContent.RGB.DrippingShader.DrippingShader(), Terraria.GameContent.RGB.DukeFishronShader.DukeFishronShader(), Terraria.GameContent.RGB.EyeOfCthulhuShader.EyeOfCthulhuShader(), Terraria.GameContent.RGB.FrostLegionShader.FrostLegionShader(), Terraria.GameContent.RGB.GemCaveShader.GemCaveShader(), Terraria.Dust.GetAlpha(), Terraria.GameContent.Dyes.LegacyHairShaderData.GetColor(), Terraria.Graphics.Shaders.HairShaderData.GetColor(), Terraria.Graphics.Shaders.HairShaderDataSet.GetColor(), Terraria.UI.ItemSlot.GetColorByLoadout(), Terraria.GameContent.Liquid.LiquidRenderer.GetShimmerGlitterColor(), Terraria.GameContent.RGB.GoblinArmyShader.GoblinArmyShader(), Terraria.GameContent.RGB.GolemShader.GolemShader(), Terraria.GameContent.RGB.IceShader.IceShader(), Terraria.GameContent.RGB.KingSlimeShader.KingSlimeShader(), Terraria.GameContent.RGB.LavaIndicatorShader.LavaIndicatorShader(), Terraria.Initializers.ChromaInitializer.Load(), Terraria.GameContent.RGB.MartianMadnessShader.MartianMadnessShader(), Terraria.GameContent.RGB.MoonShader.MoonShader(), Terraria.Main.oldDrawWater(), Terraria.GameContent.Skies.MoonLordSky.OnTileColor(), Terraria.GameContent.Skies.NebulaSky.OnTileColor(), Terraria.GameContent.Skies.SolarSky.OnTileColor(), Terraria.GameContent.Skies.StardustSky.OnTileColor(), Terraria.GameContent.Skies.VortexSky.OnTileColor(), Terraria.GameContent.RGB.PillarShader.PillarShader(), Terraria.GameContent.RGB.PirateInvasionShader.PirateInvasionShader(), Terraria.GameContent.RGB.PlanteraShader.PlanteraShader(), Terraria.GameContent.RGB.EmpressShader.ProcessHighDetail(), Terraria.GameContent.RGB.QueenBeeShader.QueenBeeShader(), Terraria.GameContent.RGB.QueenSlimeShader.QueenSlimeShader(), ReLogic.Peripherals.RGB.Corsair.CorsairKeyboard.Render(), Terraria.GameContent.RGB.VirtualKeyboard.Render(), Terraria.GameContent.RGB.SkullShader.SkullShader(), Terraria.GameContent.RGB.SkyShader.SkyShader(), Terraria.GameContent.RGB.SurfaceBiomeShader.SurfaceBiomeShader(), Terraria.GameContent.RGB.TwinsShader.TwinsShader(), Terraria.GameContent.RGB.UnderworldShader.UnderworldShader(), Terraria.GameContent.RGB.WallOfFleshShader.WallOfFleshShader(), and Terraria.GameContent.RGB.WormShader.WormShader().