Terraria Decompiled: Microsoft.Xna.Framework.Color.Lerp
Lerp()
static Color Microsoft.Xna.Framework.Color.Lerp (Color value1, Color value2, float amount) inline static
Definition at line 2599 of file Color.cs.
        {
            amount = MathHelper.Clamp(amount, 0f, 1f);
            return new Color((int)MathHelper.Lerp((float)value1.R, (float)value2.R, amount), (int)MathHelper.Lerp((float)value1.G, (float)value2.G, amount), (int)MathHelper.Lerp((float)value1.B, (float)value2.B, amount), (int)MathHelper.Lerp((float)value1.A, (float)value2.A, amount));
        }
References Microsoft.Xna.Framework.Color.A, Microsoft.Xna.Framework.Color.B, Microsoft.Xna.Framework.MathHelper.Clamp(), Microsoft.Xna.Framework.Color.Color(), Microsoft.Xna.Framework.Color.G, Microsoft.Xna.Framework.MathHelper.Lerp(), and Microsoft.Xna.Framework.Color.R.
Referenced by Terraria.GameContent.UI.States.UIWorkshopHub.AddHorizontalSeparator(), Terraria.GameContent.UI.States.UIWorldCreation.AddHorizontalSeparator(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.AddHorizontalSeparator(), Terraria.GameContent.UI.States.UIWorldCreation.AddWorldSizeOptions(), Terraria.Projectile.AI(), Terraria.Projectile.AI_009_MagicMissiles(), Terraria.Projectile.AI_067_FreakingPirates(), Terraria.NPC.AI_112_FairyCritter(), Terraria.Projectile.AI_113_TargetSticker(), Terraria.NPC.AI_121_QueenSlime_GetDustColor(), Terraria.Projectile.AI_147_Celeb2Rocket(), Terraria.Projectile.AI_147_Explosion(), Terraria.Projectile.AI_168_FirstFractal(), Terraria.Projectile.AI_171_GetColor(), Terraria.Projectile.AI_173_GetColor(), Terraria.Projectile.AI_179_FairyQueenLance(), Terraria.Projectile.AI_190_NightsEdge(), Terraria.Projectile.AI_191_TrueNightsEdge(), Terraria.GameContent.Drawing.NextHorizonRenderer.BlendColor(), Terraria.GameContent.Drawing.NextHorizonRenderer.BlendColorAlongGradientBasedOnHeight(), Terraria.DelegateMethods.ColorLerp_BlackToWhite(), Terraria.Utils.ColorLerp_BlackToWhite(), Terraria.DelegateMethods.ColorLerp_HSL_O(), Terraria.GameContent.Drawing.ParticleOrchestrator.CopperSlimeEffect(), Terraria.GameContent.UI.States.UIManageControls.CreateBindingGroup(), Terraria.Player.DashMovement(), Terraria.WorldItem.DespawnIfMeetingConditions(), Terraria.Graphics.Renderers.BloodyExplosionParticle.Draw(), Terraria.Graphics.Renderers.CreativeSacrificeParticle.Draw(), Terraria.Graphics.Renderers.FakeFishParticle.Draw(), Terraria.Graphics.Renderers.GasParticle.Draw(), Terraria.Graphics.Renderers.ShockIconParticle.Draw(), Terraria.UI.ItemSlot.Draw(), Terraria.Main.DrawClothesWindow(), Terraria.GameContent.UI.WiresUI.WiresRadial.DrawCursorArea(), Terraria.TimeLogger.DrawDelta(), Terraria.Main.DrawItem(), Terraria.UI.ItemSlot.DrawItemIcon(), Terraria.GameContent.UI.UIPopupTextManager.DrawItemTextPopups(), Terraria.PopupText.DrawItemTextPopups(), Terraria.IngameOptions.DrawLeftSide(), Terraria.Utils.DrawLine(), Terraria.Main.DrawLoadoutButtons(), Terraria.Main.DrawMouseOver(), Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileVinesInWind(), Terraria.Utils.DrawNotificationIcon(), Terraria.Main.DrawNPCDirect(), Terraria.Main.DrawNPCDirect_Deerclops(), Terraria.Main.DrawNPCDirect_Faeling(), Terraria.Main.DrawNPCDirect_HallowBoss(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_05_2_SafemanSun(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_05_ForbiddenSetRing(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_09_Wings(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_21_1_Magiluminescence(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_21_Head(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_27_HeldItem(), Terraria.Main.DrawProj_Flamethrower(), Terraria.Main.DrawProj_Flamethrower_Foxsparks(), Terraria.Main.DrawProj_TrueExcalibur(), Terraria.Main.DrawProj_TrueNightsEdge(), Terraria.Main.DrawProjDirect(), Terraria.IngameOptions.DrawRightSide(), Terraria.GameContent.UI.Elements.GroupOptionButton< T >.DrawSelf(), Terraria.GameContent.UI.Elements.UIAchievementListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIColoredSlider.DrawSelf(), Terraria.GameContent.UI.Elements.UIDifficultyButton.DrawSelf(), Terraria.GameContent.UI.Elements.UIGenProgressBar.DrawSelf(), Terraria.GameContent.UI.Elements.UIIconTextButton.DrawSelf(), Terraria.GameContent.UI.Elements.UIKeybindingListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIKeybindingSimpleListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIKeybindingSliderItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIKeybindingToggleListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIResourcePackInfoButton< T >.DrawSelf(), Terraria.GameContent.UI.Elements.UISelectableTextPanel< T >.DrawSelf(), Terraria.GameContent.UI.States.UIVirtualKeyboard.DrawSelf(), Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile(), Terraria.Main.DrawStar(), Terraria.GameContent.Drawing.TileDrawing.DrawTeleportationPylons(), Terraria.GameContent.PotionOfReturnGateHelper.DrawToDrawData(), Terraria.GameContent.VoidLensHelper.DrawToDrawData(), Terraria.GameContent.Drawing.WallDrawing.DrawWalls(), Terraria.Main.DrawWhip_RainbowWhip(), Terraria.GameContent.Drawing.NextNatureRenderer.DrawWithLitNatureShader(), Terraria.GameContent.Drawing.ParticleOrchestrator.ElderSlimeEffect(), Terraria.Projectile.EmitEnchantmentVisualsAt(), Terraria.GameContent.Golf.GolfHelper.ContactListener.EmitGolfballExplosion_v1(), Terraria.GameContent.UI.Elements.EmotesGroupListItem.EmotesGroupListItem(), Terraria.NPC.FairyEffects(), Terraria.Dust.GetAlpha(), Terraria.Item.GetAlpha(), Terraria.NPC.GetAlpha(), Terraria.Projectile.GetAlpha(), Terraria.GameContent.Skies.AmbientSky.FadingSkyEntity.GetColor(), Terraria.GameContent.Skies.AmbientSky.GastropodGroupSkyEntity.GetColor(), Terraria.GameContent.Skies.AmbientSky.HellBatsGoupSkyEntity.GetColor(), Terraria.GameContent.Skies.AmbientSky.NormalizedBackgroundLayerSpaceSkyEntity.GetColor(), Terraria.GameContent.Golf.FancyGolfPredictionLine.GetColor(), Terraria.GameContent.Golf.FancyGolfPredictionLine.GetColor2(), Terraria.UI.ItemSlot.GetColorByLoadout(), Terraria.Projectile.GetConstellationColor(), Terraria.Projectile.GetFairyQueenWeaponsColorFull(), Terraria.Projectile.GetLastPrismHue(), Terraria.GameContent.Drawing.TileDrawing.GetTileDrawData(), Terraria.GameContent.UI.States.UICharacterCreation.GetVoicePitchColorAt(), Terraria.NPC.HitEffect(), Terraria.Player.ItemCheck_ApplyUseStyle(), Terraria.Player.ItemCheck_EmitUseVisuals(), Terraria.GameContent.Drawing.WallDrawing.LerpVertexColorsWithColor(), Terraria.Projectile.LightDisc_Bounce(), Terraria.GameContent.UI.States.UICharacterCreation.MakeCategoriesBar(), Terraria.GameContent.UI.States.UICharacterCreation.MakeClothStylesMenu(), Terraria.GameContent.DontStarveSeed.ModifyNightColor(), Terraria.GameContent.Skies.AuroraSky.ModifyTileColor(), Terraria.GameContent.UI.Elements.UIIconTextButton.MouseOut(), Terraria.GameContent.UI.Elements.UIIconTextButton.MouseOver(), Terraria.Utils.MultiLerp(), Terraria.PopupText.NewText(), Terraria.TimeLogger.PerformanceColor(), Terraria.GameContent.RGB.EmpressShader.ProcessHighDetail(), Terraria.Player.RocketBootVisuals(), Terraria.GameContent.UI.Elements.UIWorkshopPublishResourcePackListItem.SetColorsToHovered(), Terraria.GameContent.UI.Elements.UIWorldListItem.SetColorsToHovered(), Terraria.GameContent.UI.States.UIWorldGenDebug.GenPassElement.SetColorsToHovered(), Terraria.GameContent.UI.Elements.UIWorkshopPublishResourcePackListItem.SetColorsToNotHovered(), Terraria.GameContent.UI.Elements.UIWorldListItem.SetColorsToNotHovered(), Terraria.GameContent.UI.States.UIWorldGenDebug.GenPassElement.SetColorsToNotHovered(), Terraria.DelegateMethods.Minecart.SparksTerraFart(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_BlackLightningHit(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_BlackLightningSmall(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_BlueLightningSmall(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_CattivaHit(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsBarnacleShotFiring(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_Keybrand(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_LeafCrystalShot(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ShimmerArrow(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_StellarTune(), Terraria.DelegateMethods.Minecart.SpawnFartCloud(), Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnLightningExplosionDust(), Terraria.GameContent.ChromaHotkeyPainter.Step_QuickHeal(), Terraria.Graphics.EmpressBladeDrawer.StripColors(), Terraria.Graphics.FinalFractalHelper.StripColors(), Terraria.Graphics.FlameLashDrawer.StripColors(), Terraria.Graphics.MagicMissileDrawer.StripColors(), Terraria.Graphics.RainbowRodDrawer.StripColors(), Terraria.Graphics.FinalFractalHelper.FinalFractalProfile.StripDust(), Terraria.GameContent.UI.Elements.UIBestiaryNPCEntryPortrait.UIBestiaryNPCEntryPortrait(), Terraria.GameContent.UI.Elements.UIColoredSlider.UIColoredSlider(), Terraria.GameContent.UI.Elements.UIIconTextButton.UIIconTextButton(), Terraria.GameContent.ChromaHotkeyPainter.ReactiveRGBKey.Update(), Terraria.Player.Update(), Terraria.Mount.UpdateEffects(), ReLogic.Peripherals.RGB.RgbKey.UpdateFadeEffect(), ReLogic.Peripherals.RGB.RgbKey.UpdateFlashingEffect(), Terraria.GameContent.LeashedEntities.FairyLeashedCritter.VisualEffects(), and Terraria.UI.Chat.ChatManager.WaveColor().