Terraria Decompiled: Terraria.Lang.LocalizedDuration
LocalizedDuration()
static string Terraria.Lang.LocalizedDuration (TimeSpan time, bool abbreviated, bool showAllAvailableUnits) inline static
Definition at line 1255 of file Lang.cs.
        {
            string text = "";
            abbreviated |= !GameCulture.FromCultureName(GameCulture.CultureName.English).IsActive;
            if (time.Days > 0)
            {
                int num = time.Days;
                if (!showAllAvailableUnits && time > TimeSpan.FromDays(1.0))
                {
                    num++;
                }
                text = text + num + (abbreviated ? (" " + Language.GetTextValue("Misc.ShortDays")) : ((num == 1) ? " day" : " days"));
                if (!showAllAvailableUnits)
                {
                    return text;
                }
                text += " ";
            }
            if (time.Hours > 0)
            {
                int num2 = time.Hours;
                if (!showAllAvailableUnits && time > TimeSpan.FromHours(1.0))
                {
                    num2++;
                }
                text = text + num2 + (abbreviated ? (" " + Language.GetTextValue("Misc.ShortHours")) : ((num2 == 1) ? " hour" : " hours"));
                if (!showAllAvailableUnits)
                {
                    return text;
                }
                text += " ";
            }
            if (time.Minutes > 0)
            {
                int num3 = time.Minutes;
                if (!showAllAvailableUnits && time > TimeSpan.FromMinutes(1.0))
                {
                    num3++;
                }
                text = text + num3 + (abbreviated ? (" " + Language.GetTextValue("Misc.ShortMinutes")) : ((num3 == 1) ? " minute" : " minutes"));
                if (!showAllAvailableUnits)
                {
                    return text;
                }
                text += " ";
            }
            return text + time.Seconds + (abbreviated ? (" " + Language.GetTextValue("Misc.ShortSeconds")) : ((time.Seconds == 1) ? " second" : " seconds"));
        }
References System.TimeSpan.Days, Terraria.Localization.GameCulture.FromCultureName(), System.TimeSpan.FromDays(), System.TimeSpan.FromHours(), System.TimeSpan.FromMinutes(), Terraria.Localization.Language.GetTextValue(), System.TimeSpan.Hours, Terraria.Localization.GameCulture.IsActive, System.TimeSpan.Minutes, and System.text.
Referenced by Terraria.Main.DrawBuffIcon(), and Terraria.Main.DrawMap().