Terraria Decompiled: Terraria.Lang.BartenderChat
BartenderChat()
static string Terraria.Lang.BartenderChat () inline static
Definition at line 348 of file Lang.cs.
        {
            if (Main.rand.Next(5) == 0)
            {
                string text;
                if (DD2Event.DownedInvasionT3)
                {
                    text = "BartenderSpecialText.AfterDD2Tier3";
                }
                else if (DD2Event.DownedInvasionT2)
                {
                    text = "BartenderSpecialText.AfterDD2Tier2";
                }
                else if (DD2Event.DownedInvasionT1)
                {
                    text = "BartenderSpecialText.AfterDD2Tier1";
                }
                else
                {
                    text = "BartenderSpecialText.BeforeDD2Tier1";
                }
                return Language.GetTextValue(text);
            }
            return Language.SelectRandom(Lang.CreateDialogFilter("BartenderChatter.", true), null).Value;
        }
References Terraria.Lang.CreateDialogFilter(), Terraria.GameContent.Events.DD2Event.DownedInvasionT1, Terraria.GameContent.Events.DD2Event.DownedInvasionT2, Terraria.GameContent.Events.DD2Event.DownedInvasionT3, Terraria.Localization.Language.GetTextValue(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, Terraria.Localization.Language.SelectRandom(), System.text, and Terraria.Localization.LocalizedText.Value.
Referenced by Terraria.NPC.GetChat().