Terraria Decompiled: Newtonsoft.Json.Utilities.DynamicUtils.BinderWrapper.CreateMemberCalls
CreateMemberCalls()
static void Newtonsoft.Json.Utilities.DynamicUtils.BinderWrapper.CreateMemberCalls () inline static private
Definition at line 67 of file DynamicUtils.cs.
            {
                Type type = Type.GetType("Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo, Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a", true);
                Type type2 = Type.GetType("Microsoft.CSharp.RuntimeBinder.CSharpBinderFlags, Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a", true);
                Type type3 = Type.GetType("Microsoft.CSharp.RuntimeBinder.Binder, Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a", true);
                Type type4 = typeof(IEnumerable).MakeGenericType(new Type[] { type });
                MethodInfo method = type3.GetMethod("GetMember", new Type[]
                {
                    type2,
                    typeof(string),
                    typeof(Type),
                    type4
                });
                DynamicUtils.BinderWrapper._getMemberCall = JsonTypeReflector.ReflectionDelegateFactory.CreateMethodCall<object>(method);
                MethodInfo method2 = type3.GetMethod("SetMember", new Type[]
                {
                    type2,
                    typeof(string),
                    typeof(Type),
                    type4
                });
                DynamicUtils.BinderWrapper._setMemberCall = JsonTypeReflector.ReflectionDelegateFactory.CreateMethodCall<object>(method2);
            }
References System.Type.GetMethod(), System.Type.GetType(), System.Type.MakeGenericType(), and Newtonsoft.Json.Serialization.JsonTypeReflector.ReflectionDelegateFactory.
Referenced by Newtonsoft.Json.Utilities.DynamicUtils.BinderWrapper.Init().