Terraria Decompiled: Newtonsoft.Json.Utilities.DynamicUtils.BinderWrapper.CreateSharpArgumentInfoArray
CreateSharpArgumentInfoArray()
static object Newtonsoft.Json.Utilities.DynamicUtils.BinderWrapper.CreateSharpArgumentInfoArray (params int[] values) inline static private
Definition at line 45 of file DynamicUtils.cs.
            {
                Type type = Type.GetType("Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo, Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a");
                Type type2 = Type.GetType("Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfoFlags, Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a");
                Array array = Array.CreateInstance(type, values.Length);
                for (int i = 0; i < values.Length; i++)
                {
                    MethodBase method = type.GetMethod("Create", new Type[]
                    {
                        type2,
                        typeof(string)
                    });
                    object obj = null;
                    object[] array2 = new object[2];
                    array2[0] = 0;
                    object obj2 = method.Invoke(obj, array2);
                    array.SetValue(obj2, i);
                }
                return array;
            }
References System.array, System.Array.CreateInstance(), System.Type.GetMethod(), System.Type.GetType(), System.Reflection.MethodBase.Invoke(), System.obj, and System.values.
Referenced by Newtonsoft.Json.Utilities.DynamicUtils.BinderWrapper.Init().