Terraria Decompiled: Terraria.Lang.FillNameCacheArray< IdClass, IdType >
FillNameCacheArray< IdClass, IdType >()
static void Terraria.Lang.FillNameCacheArray< IdClass, IdType > (string category, LocalizedText[] nameCache, bool leaveMissingEntriesBlank = false) inline static private
Type Constraints
IdType : IConvertible
Definition at line 505 of file Lang.cs.
                                                                                                                                                                : IConvertible
        {
            for (int i = 0; i < nameCache.Length; i++)
            {
                nameCache[i] = LocalizedText.Empty;
            }
            (from f in typeof(IdClass).GetFields(BindingFlags.Static | BindingFlags.Public)
                where f.FieldType == typeof(IdType)
                select f).ToList<FieldInfo>().ForEach(delegate(FieldInfo field)
            {
                long num = Convert.ToInt64((IdType)((object)field.GetValue(null)));
                if (num >= 0L && num < (long)nameCache.Length)
                {
                    nameCache[(int)(checked((IntPtr)num))] = ((!leaveMissingEntriesBlank || Language.Exists(category + "." + field.Name)) ? Language.GetText(category + "." + field.Name) : LocalizedText.Empty);
                    return;
                }
                if (field.Name == "None")
                {
                    nameCache[(int)(checked((IntPtr)num))] = LocalizedText.Empty;
                }
            });
        }
References Terraria.Lang.category, Terraria.Localization.LocalizedText.Empty, Terraria.Localization.Language.Exists(), Terraria.Localization.Language.GetText(), System.Reflection.FieldInfo.GetValue(), Terraria.Lang.IdType, int, System.L, Terraria.Lang.leaveMissingEntriesBlank, System.Reflection.MemberInfo.Name, Terraria.Lang.nameCache, and System.Convert.ToInt64().