Terraria Decompiled: Terraria.Lang.GetInvasionWaveText
GetInvasionWaveText()
static NetworkText Terraria.Lang.GetInvasionWaveText (int wave, params short[] npcIds) inline static
Definition at line 1230 of file Lang.cs.
        {
            NetworkText[] array = new NetworkText[npcIds.Length + 1];
            for (int i = 0; i < npcIds.Length; i++)
            {
                array[i + 1] = NetworkText.FromKey(Lang.GetNPCName((int)npcIds[i]).Key, new object[0]);
            }
            if (wave == -1)
            {
                array[0] = NetworkText.FromKey("Game.FinalWave", new object[0]);
            }
            else if (wave == 1)
            {
                array[0] = NetworkText.FromKey("Game.FirstWave", new object[0]);
            }
            else
            {
                array[0] = NetworkText.FromKey("Game.Wave", new object[] { wave });
            }
            string text = "Game.InvasionWave_Type" + npcIds.Length;
            object[] array2 = array;
            return NetworkText.FromKey(text, array2);
        }
References System.array, Terraria.Localization.NetworkText.FromKey(), Terraria.Lang.GetNPCName(), Terraria.Localization.LocalizedText.Key, and System.text.
Referenced by Terraria.NPC.CheckProgressFrostMoon(), Terraria.NPC.CheckProgressPumpkinMoon(), Terraria.Main.startPumpkinMoon(), Terraria.Main.startSnowMoon(), and Terraria.GameContent.Events.DD2Event.UpdateTime().