Terraria Decompiled: Newtonsoft.Json.Utilities.DynamicUtils.BinderWrapper.Init
Init()
static void Newtonsoft.Json.Utilities.DynamicUtils.BinderWrapper.Init () inline static private
Definition at line 25 of file DynamicUtils.cs.
            {
                if (!DynamicUtils.BinderWrapper._init)
                {
                    if (Type.GetType("Microsoft.CSharp.RuntimeBinder.Binder, Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a", false) == null)
                    {
                        throw new InvalidOperationException("Could not resolve type '{0}'. You may need to add a reference to Microsoft.CSharp.dll to work with dynamic types.".FormatWith(CultureInfo.InvariantCulture, "Microsoft.CSharp.RuntimeBinder.Binder, Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"));
                    }
                    DynamicUtils.BinderWrapper._getCSharpArgumentInfoArray = DynamicUtils.BinderWrapper.CreateSharpArgumentInfoArray(new int[1]);
                    DynamicUtils.BinderWrapper._setCSharpArgumentInfoArray = DynamicUtils.BinderWrapper.CreateSharpArgumentInfoArray(new int[]
                    {
                        default(int),
                        3
                    });
                    DynamicUtils.BinderWrapper.CreateMemberCalls();
                    DynamicUtils.BinderWrapper._init = true;
                }
            }
References Newtonsoft.Json.Utilities.DynamicUtils.BinderWrapper._init, Newtonsoft.Json.Utilities.DynamicUtils.BinderWrapper.CreateMemberCalls(), Newtonsoft.Json.Utilities.DynamicUtils.BinderWrapper.CreateSharpArgumentInfoArray(), System.Type.GetType(), and System.Globalization.CultureInfo.InvariantCulture.
Referenced by Newtonsoft.Json.Utilities.DynamicUtils.BinderWrapper.GetMember(), and Newtonsoft.Json.Utilities.DynamicUtils.BinderWrapper.SetMember().