Terraria Decompiled: Terraria.Lang.GetPrefixedItemName
GetPrefixedItemName()
static string Terraria.Lang.GetPrefixedItemName (int id, int prefixType) inline static
Definition at line 205 of file Lang.cs.
        {
            LocalizedText itemName = Lang.GetItemName(id);
            LocalizedText localizedText = Lang.prefix[prefixType];
            string text = localizedText.Value;
            string text2;
            string text3;
            if (Language.TryGetVariation(itemName.Key, "Gender", out text2) && Language.TryGetVariation(localizedText.Key, text2, out text3))
            {
                text = text3;
            }
            return Lang._prefixFormatText.FormatWith(new Lang.ItemPrefixCombiner
            {
                PrefixName = text,
                ItemName = itemName.Value
            });
        }
References Terraria.Lang._prefixFormatText, Terraria.Localization.LocalizedText.FormatWith(), Terraria.Lang.GetItemName(), Terraria.Localization.LocalizedText.Key, Terraria.Lang.prefix, System.text, Terraria.Localization.Language.TryGetVariation(), and Terraria.Localization.LocalizedText.Value.
Referenced by Terraria.Item.AffixName().