Terraria Decompiled: Terraria.Lang.InitializeLegacyLocalization
InitializeLegacyLocalization()
static void Terraria.Lang.InitializeLegacyLocalization () inline static
Definition at line 529 of file Lang.cs.
        {
            Lang.FillNameCacheArray<PrefixID, int>("Prefix", Lang.prefix, false);
            for (int i = 0; i < Lang.gen.Length; i++)
            {
                Lang.gen[i] = Language.GetText("LegacyWorldGen." + i);
            }
            for (int j = 0; j < Lang.menu.Length; j++)
            {
                Lang.menu[j] = Language.GetText("LegacyMenu." + j);
            }
            for (int k = 0; k < Lang.inter.Length; k++)
            {
                Lang.inter[k] = Language.GetText("LegacyInterface." + k);
            }
            for (int l = 0; l < Lang.misc.Length; l++)
            {
                Lang.misc[l] = Language.GetText("LegacyMisc." + l);
            }
            for (int m = 0; m < Lang.mp.Length; m++)
            {
                Lang.mp[m] = Language.GetText("LegacyMultiplayer." + m);
            }
            for (int n = 0; n < Lang.tip.Length; n++)
            {
                Lang.tip[n] = Language.GetText("LegacyTooltip." + n);
            }
            for (int num = 0; num < Lang.chestType.Length; num++)
            {
                Lang.chestType[num] = Language.GetText("LegacyChestType." + num);
            }
            for (int num2 = 0; num2 < Lang.chestType2.Length; num2++)
            {
                Lang.chestType2[num2] = Language.GetText("LegacyChestType2." + num2);
            }
            for (int num3 = 0; num3 < Lang.dresserType.Length; num3++)
            {
                Lang.dresserType[num3] = Language.GetText("LegacyDresserType." + num3);
            }
            Lang.FillNameCacheArray<ItemID, short>("ItemName", Lang._itemNameCache, false);
            Lang.FillNameCacheArray<ProjectileID, short>("ProjectileName", Lang._projectileNameCache, false);
            Lang.FillNameCacheArray<NPCID, short>("NPCName", Lang._npcNameCache, false);
            Lang.FillNameCacheArray<BuffID, int>("BuffName", Lang._buffNameCache, false);
            Lang.FillNameCacheArray<BuffID, int>("BuffDescription", Lang._buffDescriptionCache, false);
            Lang.FillNameCacheArray<EmoteID, int>("EmojiName", Lang._emojiNameCache, true);
            for (int num4 = -65; num4 < 0; num4++)
            {
                Lang._negativeNpcNameCache[-num4 - 1] = Lang._npcNameCache[NPCID.FromNetId(num4)];
            }
            Lang._negativeNpcNameCache[0] = Language.GetText("NPCName.Slimeling");
            Lang._negativeNpcNameCache[1] = Language.GetText("NPCName.Slimer2");
            Lang._negativeNpcNameCache[2] = Language.GetText("NPCName.GreenSlime");
            Lang._negativeNpcNameCache[3] = Language.GetText("NPCName.Pinky");
            Lang._negativeNpcNameCache[4] = Language.GetText("NPCName.BabySlime");
            Lang._negativeNpcNameCache[5] = Language.GetText("NPCName.BlackSlime");
            Lang._negativeNpcNameCache[6] = Language.GetText("NPCName.PurpleSlime");
            Lang._negativeNpcNameCache[7] = Language.GetText("NPCName.RedSlime");
            Lang._negativeNpcNameCache[8] = Language.GetText("NPCName.YellowSlime");
            Lang._negativeNpcNameCache[9] = Language.GetText("NPCName.JungleSlime");
            Lang._negativeNpcNameCache[53] = Language.GetText("NPCName.SmallRainZombie");
            Lang._negativeNpcNameCache[54] = Language.GetText("NPCName.BigRainZombie");
            for (int num5 = 0; num5 < Lang._itemTooltipCache.Length; num5++)
            {
                Lang._itemTooltipCache[num5] = ItemTooltip.None;
            }
            (from f in typeof(ItemID).GetFields(BindingFlags.Static | BindingFlags.Public)
                where f.FieldType == typeof(short)
                select f).ToList<FieldInfo>().ForEach(delegate(FieldInfo field)
            {
                short num6 = (short)field.GetValue(null);
                if (num6 > 0 && (int)num6 < Lang._itemTooltipCache.Length)
                {
                    Lang._itemTooltipCache[(int)num6] = ItemTooltip.FromLanguageKey("ItemTooltip." + field.Name);
                }
            });
            Lang.InitGlobalSubstitutions();
        }
References Terraria.Lang._buffDescriptionCache, Terraria.Lang._buffNameCache, Terraria.Lang._emojiNameCache, Terraria.Lang._itemNameCache, Terraria.Lang._itemTooltipCache, Terraria.Lang._negativeNpcNameCache, Terraria.Lang._npcNameCache, Terraria.Lang._projectileNameCache, Terraria.Lang.chestType, Terraria.Lang.chestType2, Terraria.Lang.dresserType, Terraria.UI.ItemTooltip.FromLanguageKey(), Terraria.ID.NPCID.FromNetId(), Terraria.Lang.gen, Terraria.Localization.Language.GetText(), System.Reflection.FieldInfo.GetValue(), Terraria.Lang.InitGlobalSubstitutions(), int, Terraria.Lang.inter, Terraria.Lang.menu, Terraria.Lang.misc, Terraria.Lang.mp, System.Reflection.MemberInfo.Name, Terraria.UI.ItemTooltip.None, Terraria.Lang.prefix, and Terraria.Lang.tip.
Referenced by Terraria.Program.RunGame().