Terraria Decompiled: Terraria.Lang.InitGlobalSubstitutions
InitGlobalSubstitutions()
static void Terraria.Lang.InitGlobalSubstitutions () inline static private
Definition at line 49 of file Lang.cs.
        {
            Lang.RegisterGlobalSubstitution("Nurse", () => NPC.GetFirstNPCNameOrNull(18));
            Lang.RegisterGlobalSubstitution("Merchant", () => NPC.GetFirstNPCNameOrNull(17));
            Lang.RegisterGlobalSubstitution("ArmsDealer", () => NPC.GetFirstNPCNameOrNull(19));
            Lang.RegisterGlobalSubstitution("Dryad", () => NPC.GetFirstNPCNameOrNull(20));
            Lang.RegisterGlobalSubstitution("Demolitionist", () => NPC.GetFirstNPCNameOrNull(38));
            Lang.RegisterGlobalSubstitution("Clothier", () => NPC.GetFirstNPCNameOrNull(54));
            Lang.RegisterGlobalSubstitution("Guide", () => NPC.GetFirstNPCNameOrNull(22));
            Lang.RegisterGlobalSubstitution("Wizard", () => NPC.GetFirstNPCNameOrNull(108));
            Lang.RegisterGlobalSubstitution("GoblinTinkerer", () => NPC.GetFirstNPCNameOrNull(107));
            Lang.RegisterGlobalSubstitution("Mechanic", () => NPC.GetFirstNPCNameOrNull(124));
            Lang.RegisterGlobalSubstitution("Truffle", () => NPC.GetFirstNPCNameOrNull(160));
            Lang.RegisterGlobalSubstitution("Steampunker", () => NPC.GetFirstNPCNameOrNull(178));
            Lang.RegisterGlobalSubstitution("DyeTrader", () => NPC.GetFirstNPCNameOrNull(207));
            Lang.RegisterGlobalSubstitution("PartyGirl", () => NPC.GetFirstNPCNameOrNull(208));
            Lang.RegisterGlobalSubstitution("Cyborg", () => NPC.GetFirstNPCNameOrNull(209));
            Lang.RegisterGlobalSubstitution("Painter", () => NPC.GetFirstNPCNameOrNull(227));
            Lang.RegisterGlobalSubstitution("WitchDoctor", () => NPC.GetFirstNPCNameOrNull(228));
            Lang.RegisterGlobalSubstitution("Pirate", () => NPC.GetFirstNPCNameOrNull(229));
            Lang.RegisterGlobalSubstitution("Stylist", () => NPC.GetFirstNPCNameOrNull(353));
            Lang.RegisterGlobalSubstitution("TravelingMerchant", () => NPC.GetFirstNPCNameOrNull(368));
            Lang.RegisterGlobalSubstitution("Angler", () => NPC.GetFirstNPCNameOrNull(369));
            Lang.RegisterGlobalSubstitution("Bartender", () => NPC.GetFirstNPCNameOrNull(550));
            Lang.RegisterGlobalSubstitution("WorldName", () => Main.worldName);
            Lang.RegisterGlobalSubstitution("Day", () => Main.dayTime);
            Lang.RegisterGlobalSubstitution("BloodMoon", () => Main.bloodMoon);
            Lang.RegisterGlobalSubstitution("Eclipse", () => Main.eclipse);
            Lang.RegisterGlobalSubstitution("MoonLordDefeated", () => NPC.downedMoonlord);
            Lang.RegisterGlobalSubstitution("GolemDefeated", () => NPC.downedGolemBoss);
            Lang.RegisterGlobalSubstitution("DukeFishronDefeated", () => NPC.downedFishron);
            Lang.RegisterGlobalSubstitution("FrostLegionDefeated", () => NPC.downedFrost);
            Lang.RegisterGlobalSubstitution("MartiansDefeated", () => NPC.downedMartians);
            Lang.RegisterGlobalSubstitution("PumpkingDefeated", () => NPC.downedHalloweenKing);
            Lang.RegisterGlobalSubstitution("IceQueenDefeated", () => NPC.downedChristmasIceQueen);
            Lang.RegisterGlobalSubstitution("HardMode", () => Main.hardMode);
            Lang.RegisterGlobalSubstitution("Homeless", () => Main.LocalPlayer.talkNPC >= 0 && Main.npc[Main.LocalPlayer.talkNPC].homeless);
            Lang.RegisterGlobalSubstitution("InventoryKey", () => Main.cInv);
            Lang.RegisterGlobalSubstitution("PlayerName", () => Main.player[Main.myPlayer].name);
            Lang.RegisterGlobalSubstitution("GolfGuy", () => NPC.GetFirstNPCNameOrNull(588));
            Lang.RegisterGlobalSubstitution("TaxCollector", () => NPC.GetFirstNPCNameOrNull(441));
            Lang.RegisterGlobalSubstitution("Rain", () => Main.raining);
            Lang.RegisterGlobalSubstitution("Graveyard", () => Main.LocalPlayer.ZoneGraveyard);
            Lang.RegisterGlobalSubstitution("AnglerCompletedQuestsCount", () => Main.LocalPlayer.anglerQuestsFinished);
            Lang.RegisterGlobalSubstitution("TotalDeathsCount", () => Main.LocalPlayer.numberOfDeathsPVE);
            Lang.RegisterGlobalSubstitution("WorldEvilStone", delegate
            {
                if (!WorldGen.crimson)
                {
                    return Language.GetTextValue("Misc.Ebonstone");
                }
                return Language.GetTextValue("Misc.Crimstone");
            });
            Lang.RegisterGlobalSubstitution("InputTriggerUI_BuildFromInventory", () => PlayerInput.GenerateInputTag_ForCurrentGamemode(false, "QuickMount"));
            Lang.RegisterGlobalSubstitution("InputTriggerUI_TrashEnabled", () => !ItemSlot.Options.DisableQuickTrash);
            Lang.RegisterGlobalSubstitution("InputTriggerUI_Trash", delegate
            {
                if (!PlayerInput.UsingGamepad)
                {
                    return Language.GetTextValue(ItemSlot.Options.DisableLeftShiftTrashCan ? "Controls.Control" : "Controls.Shift");
                }
                return PlayerInput.GenerateInputTag_ForCurrentGamemode(false, "SmartSelect");
            });
            Lang.RegisterGlobalSubstitution("InputTriggerUI_FavoriteItem", delegate
            {
                if (!PlayerInput.UsingGamepad)
                {
                    return Main.FavoriteKey.ToString();
                }
                return PlayerInput.GenerateInputTag_ForCurrentGamemode(false, "SmartCursor");
            });
            Lang.RegisterGlobalSubstitution("InputTrigger_QuickEquip", () => PlayerInput.GenerateInputTag_ForCurrentGamemode(false, "Grapple"));
            Lang.RegisterGlobalSubstitution("InputTrigger_Grapple", () => PlayerInput.GenerateInputTag_ForCurrentGamemode(true, "Grapple"));
            Lang.RegisterGlobalSubstitution("InputTrigger_LockOn", () => PlayerInput.GenerateInputTag_ForCurrentGamemode(true, "LockOn"));
            Lang.RegisterGlobalSubstitution("InputTrigger_RadialQuickbar", () => PlayerInput.GenerateInputTag_ForCurrentGamemode(true, "HotbarMinus"));
            Lang.RegisterGlobalSubstitution("InputTrigger_RadialHotbar", () => PlayerInput.GenerateInputTag_ForCurrentGamemode(true, "HotbarPlus"));
            Lang.RegisterGlobalSubstitution("InputTrigger_SmartCursor", () => PlayerInput.GenerateInputTag_ForCurrentGamemode(true, "SmartCursor"));
            Lang.RegisterGlobalSubstitution("InputTrigger_UseOrAttack", () => PlayerInput.GenerateInputTag_ForCurrentGamemode(true, "MouseLeft"));
            Lang.RegisterGlobalSubstitution("InputTrigger_InteractWithTile", () => PlayerInput.GenerateInputTag_ForCurrentGamemode(true, "MouseRight"));
            Lang.RegisterGlobalSubstitution("InputTrigger_InteractWithTileUI", () => PlayerInput.GenerateInputTag_ForCurrentGamemode(false, "MouseRight"));
            Lang.RegisterGlobalSubstitution("InputTrigger_ToggleOrOpen", delegate
            {
                if (!PlayerInput.UsingGamepad)
                {
                    return PlayerInput.GenerateInputTag_ForCurrentGamemode(true, "MouseRight");
                }
                return PlayerInput.GenerateInputTag_ForCurrentGamemode(false, "Grapple");
            });
            Lang.RegisterGlobalSubstitution("InputTrigger_SmartSelect", () => PlayerInput.GenerateInputTag_ForCurrentGamemode(true, "SmartSelect"));
            Lang.RegisterGlobalSubstitution("ToggleArmorSetBonusKey", () => Language.GetTextValue(Main.ReversedUpDownArmorSetBonuses ? "Key.UP" : "Key.DOWN"));
        }
References Terraria.Player.anglerQuestsFinished, Terraria.Main.bloodMoon, Terraria.Main.cInv, Terraria.WorldGen.crimson, Terraria.Main.dayTime, Terraria.UI.ItemSlot.Options.DisableLeftShiftTrashCan, Terraria.UI.ItemSlot.Options.DisableQuickTrash, Terraria.NPC.downedChristmasIceQueen, Terraria.NPC.downedFishron, Terraria.NPC.downedFrost, Terraria.NPC.downedGolemBoss, Terraria.NPC.downedHalloweenKing, Terraria.NPC.downedMartians, Terraria.NPC.downedMoonlord, Terraria.Main.eclipse, Terraria.Main.FavoriteKey, Terraria.GameInput.PlayerInput.GenerateInputTag_ForCurrentGamemode(), Terraria.NPC.GetFirstNPCNameOrNull(), Terraria.Localization.Language.GetTextValue(), Terraria.Main.hardMode, Terraria.NPC.homeless, Terraria.Main.LocalPlayer, Terraria.Main.myPlayer, Terraria.Player.name, Terraria.Main.npc, Terraria.Player.numberOfDeathsPVE, Terraria.Main.player, Terraria.Main.raining, Terraria.Lang.RegisterGlobalSubstitution(), Terraria.Main.ReversedUpDownArmorSetBonuses, Terraria.Player.talkNPC, Terraria.GameInput.PlayerInput.UsingGamepad, Terraria.Main.worldName, and Terraria.Player.ZoneGraveyard.
Referenced by Terraria.Lang.InitializeLegacyLocalization().