Terraria Decompiled: Terraria.Lang.GetDryadWorldStatusDialog
GetDryadWorldStatusDialog()
static string Terraria.Lang.GetDryadWorldStatusDialog (out bool worldIsEntirelyPure) inline static
Definition at line 236 of file Lang.cs.
        {
            worldIsEntirelyPure = false;
            int tGood = (int)WorldGen.tGood;
            int tEvil = (int)WorldGen.tEvil;
            int tBlood = (int)WorldGen.tBlood;
            string text;
            if (tGood > 0 && tEvil > 0 && tBlood > 0)
            {
                text = Language.GetTextValue("DryadSpecialText.WorldStatusAll", new object[]
                {
                    Main.worldName,
                    tGood,
                    tEvil,
                    tBlood
                });
            }
            else if (tGood > 0 && tEvil > 0)
            {
                text = Language.GetTextValue("DryadSpecialText.WorldStatusHallowCorrupt", Main.worldName, tGood, tEvil);
            }
            else if (tGood > 0 && tBlood > 0)
            {
                text = Language.GetTextValue("DryadSpecialText.WorldStatusHallowCrimson", Main.worldName, tGood, tBlood);
            }
            else if (tEvil > 0 && tBlood > 0)
            {
                text = Language.GetTextValue("DryadSpecialText.WorldStatusCorruptCrimson", Main.worldName, tEvil, tBlood);
            }
            else if (tEvil > 0)
            {
                text = Language.GetTextValue("DryadSpecialText.WorldStatusCorrupt", Main.worldName, tEvil);
            }
            else if (tBlood > 0)
            {
                text = Language.GetTextValue("DryadSpecialText.WorldStatusCrimson", Main.worldName, tBlood);
            }
            else
            {
                if (tGood <= 0)
                {
                    text = Language.GetTextValue("DryadSpecialText.WorldStatusPure", Main.worldName);
                    worldIsEntirelyPure = true;
                    return text;
                }
                text = Language.GetTextValue("DryadSpecialText.WorldStatusHallow", Main.worldName, tGood);
            }
            string text2;
            if ((double)tGood * 1.2 >= (double)(tEvil + tBlood) && (double)tGood * 0.8 <= (double)(tEvil + tBlood))
            {
                text2 = Language.GetTextValue("DryadSpecialText.WorldDescriptionBalanced");
            }
            else if (tGood >= tEvil + tBlood)
            {
                text2 = Language.GetTextValue("DryadSpecialText.WorldDescriptionFairyTale");
            }
            else if (tEvil + tBlood > tGood + 20)
            {
                text2 = Language.GetTextValue("DryadSpecialText.WorldDescriptionGrim");
            }
            else if (tEvil + tBlood > 5)
            {
                text2 = Language.GetTextValue("DryadSpecialText.WorldDescriptionWork");
            }
            else
            {
                text2 = Language.GetTextValue("DryadSpecialText.WorldDescriptionClose");
            }
            return string.Format("{0} {1}", text, text2);
        }
References Terraria.Localization.Language.GetTextValue(), int, Terraria.WorldGen.tBlood, Terraria.WorldGen.tEvil, System.text, Terraria.WorldGen.tGood, and Terraria.Main.worldName.
Referenced by Terraria.Main.DryadText_WorldPurityOrStardewValleyBit(), and Terraria.GameContent.NPCInteractions.Actions.DryadPurification.Interact().