Terraria Decompiled: Terraria.Lang.CreateDeathMessage
CreateDeathMessage()
static NetworkText Terraria.Lang.CreateDeathMessage (string deadPlayerName, int plr = -1, int npc = -1, int proj = -1, int other = -1, int projType = 0, int plrItemType = 0) inline static
Definition at line 1066 of file Lang.cs.
        {
            NetworkText networkText = NetworkText.Empty;
            NetworkText networkText2 = NetworkText.Empty;
            NetworkText networkText3 = NetworkText.Empty;
            NetworkText networkText4 = NetworkText.Empty;
            if (proj >= 0)
            {
                networkText = NetworkText.FromKey(Lang.GetProjectileName(projType).Key, new object[0]);
            }
            if (npc >= 0)
            {
                networkText2 = Main.npc[npc].GetGivenOrTypeNetName();
            }
            if (plr >= 0 && plr < 255)
            {
                networkText3 = NetworkText.FromLiteral(Main.player[plr].name);
            }
            if (plrItemType >= 0)
            {
                networkText4 = NetworkText.FromKey(Lang.GetItemName(plrItemType).Key, new object[0]);
            }
            bool flag = networkText != NetworkText.Empty;
            bool flag2 = plr >= 0 && plr < 255;
            bool flag3 = networkText2 != NetworkText.Empty;
            NetworkText networkText5 = NetworkText.Empty;
            NetworkText networkText6 = NetworkText.Empty;
            networkText6 = NetworkText.FromKey(Language.RandomFromCategory("DeathTextGeneric", null).Key, new object[]
            {
                deadPlayerName,
                Main.worldName
            });
            if (flag2)
            {
                networkText5 = NetworkText.FromKey("DeathSource.Player", new object[]
                {
                    networkText6,
                    networkText3,
                    flag ? networkText : networkText4
                });
            }
            else if (flag3)
            {
                networkText5 = NetworkText.FromKey("DeathSource.NPC", new object[] { networkText6, networkText2 });
            }
            else if (flag)
            {
                networkText5 = NetworkText.FromKey("DeathSource.Projectile", new object[] { networkText6, networkText });
            }
            else if (other >= 0)
            {
                if (other == 0)
                {
                    networkText5 = NetworkText.FromKey("DeathText.Fell_" + (Main.rand.Next(9) + 1), new object[] { deadPlayerName });
                }
                else if (other == 1)
                {
                    networkText5 = NetworkText.FromKey("DeathText.Drowned_" + (Main.rand.Next(7) + 1), new object[] { deadPlayerName });
                }
                else if (other == 2)
                {
                    networkText5 = NetworkText.FromKey("DeathText.Lava_" + (Main.rand.Next(5) + 1), new object[] { deadPlayerName });
                }
                else if (other == 3)
                {
                    networkText5 = NetworkText.FromKey("DeathText.Default", new object[] { networkText6 });
                }
                else if (other == 4)
                {
                    networkText5 = NetworkText.FromKey("DeathText.Slain", new object[] { deadPlayerName });
                }
                else if (other == 5)
                {
                    networkText5 = NetworkText.FromKey("DeathText.Petrified_" + (Main.rand.Next(4) + 1), new object[] { deadPlayerName });
                }
                else if (other == 6)
                {
                    networkText5 = NetworkText.FromKey("DeathText.Stabbed", new object[] { deadPlayerName });
                }
                else if (other == 7)
                {
                    networkText5 = NetworkText.FromKey("DeathText.Suffocated_" + (Main.rand.Next(2) + 1), new object[] { deadPlayerName });
                }
                else if (other == 8)
                {
                    networkText5 = NetworkText.FromKey("DeathText.Burned_" + (Main.rand.Next(4) + 1), new object[] { deadPlayerName });
                }
                else if (other == 9)
                {
                    networkText5 = NetworkText.FromKey("DeathText.Poisoned", new object[] { deadPlayerName });
                }
                else if (other == 10)
                {
                    networkText5 = NetworkText.FromKey("DeathText.Electrocuted_" + (Main.rand.Next(4) + 1), new object[] { deadPlayerName });
                }
                else if (other == 11)
                {
                    networkText5 = NetworkText.FromKey("DeathText.TriedToEscape", new object[] { deadPlayerName });
                }
                else if (other == 12)
                {
                    networkText5 = NetworkText.FromKey("DeathText.WasLicked_" + (Main.rand.Next(2) + 1), new object[] { deadPlayerName });
                }
                else if (other == 13)
                {
                    networkText5 = NetworkText.FromKey("DeathText.Teleport_1", new object[] { deadPlayerName });
                }
                else if (other == 14)
                {
                    networkText5 = NetworkText.FromKey("DeathText.Teleport_2_Male", new object[] { deadPlayerName });
                }
                else if (other == 15)
                {
                    networkText5 = NetworkText.FromKey("DeathText.Teleport_2_Female", new object[] { deadPlayerName });
                }
                else if (other == 16)
                {
                    networkText5 = NetworkText.FromKey("DeathText.Inferno", new object[] { deadPlayerName });
                }
                else if (other == 17)
                {
                    networkText5 = NetworkText.FromKey("DeathText.DiedInTheDark", new object[] { deadPlayerName });
                }
                else if (other == 18)
                {
                    networkText5 = NetworkText.FromKey("DeathText.Starved_" + (Main.rand.Next(3) + 1), new object[] { deadPlayerName });
                }
                else if (other == 19)
                {
                    networkText5 = NetworkText.FromKey("DeathText.Space_" + (Main.rand.Next(5) + 1), new object[]
                    {
                        deadPlayerName,
                        Main.worldName
                    });
                }
                else if (other == 20)
                {
                    networkText5 = NetworkText.FromKey("DeathText.TeamTank", new object[] { deadPlayerName });
                }
                else if (other == 21)
                {
                    networkText5 = NetworkText.FromKey("DeathText.Underground_" + (Main.rand.Next(5) + 1), new object[]
                    {
                        deadPlayerName,
                        Main.worldName
                    });
                }
                else if (other == 22)
                {
                    networkText5 = NetworkText.FromKey("DeathText.VampireBurningInDaylight_" + (Main.rand.Next(6) + 1), new object[]
                    {
                        deadPlayerName,
                        Main.worldName
                    });
                }
                else if (other == 255)
                {
                    networkText5 = NetworkText.FromKey("DeathText.Slain", new object[] { deadPlayerName });
                }
            }
            return networkText5;
        }
References Terraria.Localization.NetworkText.Empty, Terraria.Localization.NetworkText.FromKey(), Terraria.Localization.NetworkText.FromLiteral(), Terraria.NPC.GetGivenOrTypeNetName(), Terraria.Lang.GetItemName(), Terraria.Lang.GetProjectileName(), Terraria.Localization.LocalizedText.Key, Terraria.Player.name, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.npc, Terraria.Main.player, Terraria.Main.rand, and Terraria.Localization.Language.RandomFromCategory().
Referenced by Terraria.DataStructures.PlayerDeathReason.GetDeathText().