Terraria Decompiled: NVorbis.VorbisReader.VorbisReader
VorbisReader() [2/5]
NVorbis.VorbisReader.VorbisReader (Stream stream, bool closeOnDispose = true) inline
Definition at line 89 of file VorbisReader.cs.
        {
            this._decoders = new List<IStreamDecoder>();
            IContainerReader containerReader = VorbisReader.CreateContainerReader.Invoke(stream, closeOnDispose);
            containerReader.NewStreamCallback = new NewStreamHandler(this.ProcessNewStream);
            if (!containerReader.TryInit() || this._decoders.Count == 0)
            {
                containerReader.NewStreamCallback = null;
                containerReader.Dispose();
                if (closeOnDispose)
                {
                    stream.Dispose();
                }
                throw new ArgumentException("Could not load the specified container!", "containerReader");
            }
            this._closeOnDispose = closeOnDispose;
            this._containerReader = containerReader;
            this._streamDecoder = this._decoders[0];
        }
References NVorbis.VorbisReader._decoders, NVorbis.VorbisReader.CreateContainerReader, System.IDisposable.Dispose(), System.IO.Stream.Dispose(), NVorbis.Contracts.NewStreamHandler(), and NVorbis.VorbisReader.ProcessNewStream().