Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.Halls.RegularDungeonHall.RegularHall
RegularHall()
void Terraria.GameContent.Generation.Dungeon.Halls.RegularDungeonHall.RegularHall (DungeonData data, Vector2D startPoint, Vector2D endPoint, bool generating = false) inline
Definition at line 46 of file RegularDungeonHall.cs.
        {
            RegularDungeonHallSettings regularDungeonHallSettings = (RegularDungeonHallSettings)this.settings;
            UnifiedRandom unifiedRandom = new UnifiedRandom(regularDungeonHallSettings.RandomSeed);
            ushort brickTileType = this.settings.StyleData.BrickTileType;
            ushort brickCrackedTileType = this.settings.StyleData.BrickCrackedTileType;
            ushort brickWallType = this.settings.StyleData.BrickWallType;
            Vector2D vector2D = startPoint;
            bool flag = false;
            if (regularDungeonHallSettings.CrackedBrickChance > 0.0)
            {
                flag = unifiedRandom.NextDouble() <= regularDungeonHallSettings.CrackedBrickChance;
            }
            int num = 3;
            int num2 = 8;
            if (regularDungeonHallSettings.OverrideInnerBoundsSize > 0)
            {
                num = regularDungeonHallSettings.OverrideInnerBoundsSize;
            }
            if (regularDungeonHallSettings.OverrideOuterBoundsSize > 0)
            {
                num2 = regularDungeonHallSettings.OverrideOuterBoundsSize;
            }
            int num3 = num + num2;
            Vector2D vector2D2 = endPoint - startPoint;
            Vector2D vector2D3 = vector2D2.SafeNormalize(Vector2D.UnitX);
            int num4 = (int)Math.Ceiling(vector2D2.Length() / vector2D3.Length());
            this.Bounds.SetBounds((int)startPoint.X, (int)startPoint.Y, (int)startPoint.X, (int)startPoint.Y);
            DungeonRoomSearchSettings dungeonRoomSearchSettings = new DungeonRoomSearchSettings
            {
                Fluff = num3
            };
            List<DungeonRoom> allRoomsInSpots = DungeonUtils.GetAllRoomsInSpots(data.dungeonRooms, startPoint, endPoint, dungeonRoomSearchSettings);
            Vector2D vector2D4 = vector2D3;
            while (num4 > 0 && WorldGen.InWorld((int)(vector2D.X + vector2D3.X), (int)(vector2D.Y + vector2D3.Y), 10))
            {
                if (!base.Processed)
                {
                    data.dungeonBounds.UpdateBounds((int)vector2D.X - num3, (int)vector2D.Y - num3, (int)vector2D.Y + num3, (int)vector2D.Y + num3);
                    this.Bounds.UpdateBounds((int)vector2D.X - num3, (int)vector2D.Y - num3, (int)vector2D.Y + num3, (int)vector2D.Y + num3);
                }
                if (generating)
                {
                    base.GenerateDungeonSquareHall(data, allRoomsInSpots, vector2D, brickTileType, brickCrackedTileType, brickWallType, num, num2, regularDungeonHallSettings.PlaceOverProtectedBricks, flag, false);
                }
                vector2D += vector2D3;
                num4--;
            }
            data.genVars.generatingDungeonPositionX = (int)endPoint.X;
            data.genVars.generatingDungeonPositionY = (int)endPoint.Y;
            this.StartPosition = startPoint;
            this.EndPosition = endPoint;
            this.StartDirection = new Vector2D(vector2D4.X, vector2D4.Y);
            this.EndDirection = new Vector2D(vector2D3.X, vector2D3.Y);
            this.CrackedBrick = flag;
            this.Bounds.CalculateHitbox();
        }
References Terraria.GameContent.Generation.Dungeon.Halls.DungeonHall.Bounds, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.BrickCrackedTileType, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.BrickTileType, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.BrickWallType, Terraria.GameContent.Generation.Dungeon.DungeonBounds.CalculateHitbox(), System.Math.Ceiling(), Terraria.GameContent.Generation.Dungeon.Halls.DungeonHallSettings.CrackedBrickChance, Terraria.GameContent.Generation.Dungeon.DungeonData.dungeonBounds, Terraria.GameContent.Generation.Dungeon.DungeonData.dungeonRooms, Terraria.GameContent.Generation.Dungeon.DungeonUtils.GetAllRoomsInSpots(), int, Terraria.WorldGen.InWorld(), ReLogic.Utilities.Vector2D.Length(), Terraria.Utilities.UnifiedRandom.NextDouble(), Terraria.GameContent.Generation.Dungeon.Halls.RegularDungeonHallSettings.OverrideInnerBoundsSize, Terraria.GameContent.Generation.Dungeon.Halls.RegularDungeonHallSettings.OverrideOuterBoundsSize, Terraria.GameContent.Generation.Dungeon.Halls.DungeonHallSettings.PlaceOverProtectedBricks, Terraria.GameContent.Generation.Dungeon.Halls.DungeonHallSettings.RandomSeed, Terraria.GameContent.Generation.Dungeon.DungeonBounds.SetBounds(), Terraria.GameContent.Generation.Dungeon.Halls.DungeonHall.settings, Terraria.GameContent.Generation.Dungeon.Halls.DungeonHallSettings.StyleData, ReLogic.Utilities.Vector2D.UnitX, Terraria.GameContent.Generation.Dungeon.DungeonBounds.UpdateBounds(), ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.GameContent.Generation.Dungeon.Halls.RegularDungeonHall.CalculateHall(), and Terraria.GameContent.Generation.Dungeon.Halls.RegularDungeonHall.GenerateHall().