Terraria Decompiled: System.Security.Permissions.StrongNameIdentityPermission.SNIP.CreateDefault
CreateDefault()
static StrongNameIdentityPermission.SNIP System.Security.Permissions.StrongNameIdentityPermission.SNIP.CreateDefault () inline static package
Definition at line 433 of file StrongNameIdentityPermission.cs.
            {
                return new StrongNameIdentityPermission.SNIP(null, string.Empty, (Version)StrongNameIdentityPermission.defaultVersion.Clone());
            }
References System.Version.Clone(), and System.Security.Permissions.StrongNameIdentityPermission.defaultVersion.
Referenced by System.Security.Permissions.StrongNameIdentityPermission.ResetToDefault(), and System.Security.Permissions.StrongNameIdentityPermission.StrongNameIdentityPermission().