Terraria Decompiled: System.Security.Permissions.StrongNameIdentityPermission.SNIP.IsSubsetOf
IsSubsetOf()
bool System.Security.Permissions.StrongNameIdentityPermission.SNIP.IsSubsetOf (StrongNameIdentityPermission::SNIP target) inline package
Definition at line 462 of file StrongNameIdentityPermission.cs.
            {
                return (this.PublicKey != null && this.PublicKey.Equals(target.PublicKey)) || (this.IsNameSubsetOf(target.Name) && (!(this.AssemblyVersion != null) || this.AssemblyVersion.Equals(target.AssemblyVersion)) && this.PublicKey == null && target.PublicKey == null);
            }
References System.Security.Permissions.StrongNameIdentityPermission.SNIP.AssemblyVersion, System.Security.Permissions.StrongNamePublicKeyBlob.Equals(), System.Version.Equals(), System.Security.Permissions.StrongNameIdentityPermission.SNIP.IsNameSubsetOf(), and System.Security.Permissions.StrongNameIdentityPermission.SNIP.PublicKey.