Terraria Decompiled: Terraria.GameContent.UI.Elements.PowerStripUIElement.PowerStripUIElement
PowerStripUIElement()
Terraria.GameContent.UI.Elements.PowerStripUIElement.PowerStripUIElement (string gamepadGroupName, List< UIElement > buttons) inline
Definition at line 12 of file PowerStripUIElement.cs.
        {
            this._buttonsBySorting = new List<UIElement>(buttons);
            this._gamepadPointGroupname = gamepadGroupName;
            int count = buttons.Count;
            int num = 4;
            int num2 = 40;
            int num3 = 40;
            int num4 = num3 + num;
            UIPanel uipanel = new UIPanel
            {
                Width = new StyleDimension((float)(num2 + num * 2), 0f),
                Height = new StyleDimension((float)(num3 * count + num * (1 + count)), 0f)
            };
            base.SetPadding(0f);
            this.Width = uipanel.Width;
            this.Height = uipanel.Height;
            uipanel.BorderColor = new Color(89, 116, 213, 255) * 0.9f;
            uipanel.BackgroundColor = new Color(73, 94, 171) * 0.9f;
            uipanel.SetPadding(0f);
            base.Append(uipanel);
            for (int i = 0; i < count; i++)
            {
                UIElement uielement = buttons[i];
                uielement.HAlign = 0.5f;
                uielement.Top = new StyleDimension((float)(num + num4 * i), 0f);
                uielement.SetSnapPoint(this._gamepadPointGroupname, i, null, null);
                uipanel.Append(uielement);
                this._buttonsBySorting.Add(uielement);
            }
        }
References Terraria.GameContent.UI.Elements.PowerStripUIElement._buttonsBySorting, Terraria.GameContent.UI.Elements.PowerStripUIElement._gamepadPointGroupname, System.Collections.Generic.List< T >.Add(), Terraria.UI.UIElement.Append(), System.Collections.Generic.List< T >.Count, System.count, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.SetPadding(), Terraria.UI.UIElement.SetSnapPoint(), and Terraria.UI.UIElement.Width.