Terraria Decompiled: Mono.DependencyInjector.ReflectionLoad
ReflectionLoad()
static ISystemDependencyProvider Mono.DependencyInjector.ReflectionLoad () inline static private
Definition at line 58 of file DependencyInjector.cs.
        {
            Type type = Type.GetType("Mono.SystemDependencyProvider, System");
            if (type == null)
            {
                return null;
            }
            PropertyInfo property = type.GetProperty("Instance", BindingFlags.DeclaredOnly | BindingFlags.Static | BindingFlags.Public);
            if (property == null)
            {
                return null;
            }
            return (ISystemDependencyProvider)property.GetValue(null);
        }
References System.Type.GetProperty(), System.Type.GetType(), and System.Reflection.PropertyInfo.GetValue().