Terraria Decompiled: Terraria.GameContent.Ambience.AmbienceServer.AmbienceServer
AmbienceServer()
Terraria.GameContent.Ambience.AmbienceServer.AmbienceServer () inline
Definition at line 32 of file AmbienceServer.cs.
        {
            this.ResetSpawnTime();
            this._spawnConditions[SkyEntityType.BirdsV] = new Func<bool>(AmbienceServer.IsSunnyDay);
            this._spawnConditions[SkyEntityType.Wyvern] = () => AmbienceServer.IsSunnyDay() && Main.hardMode;
            this._spawnConditions[SkyEntityType.Airship] = () => AmbienceServer.IsSunnyDay() && Main.IsItAHappyWindyDay;
            this._spawnConditions[SkyEntityType.AirBalloon] = () => AmbienceServer.IsSunnyDay() && !Main.IsItAHappyWindyDay;
            this._spawnConditions[SkyEntityType.Eyeball] = () => !Main.dayTime;
            this._spawnConditions[SkyEntityType.Butterflies] = () => AmbienceServer.IsSunnyDay() && !Main.IsItAHappyWindyDay && !NPC.TooWindyForButterflies && NPC.butterflyChance < 6;
            this._spawnConditions[SkyEntityType.LostKite] = () => Main.dayTime && !Main.eclipse && Main.IsItAHappyWindyDay;
            this._spawnConditions[SkyEntityType.Vulture] = () => AmbienceServer.IsSunnyDay();
            this._spawnConditions[SkyEntityType.Bats] = () => (AmbienceServer.IsSunset() && AmbienceServer.IsSunnyDay()) || AmbienceServer.IsCalmNight();
            this._spawnConditions[SkyEntityType.PixiePosse] = () => AmbienceServer.IsSunnyDay() || AmbienceServer.IsCalmNight();
            this._spawnConditions[SkyEntityType.Seagulls] = () => AmbienceServer.IsSunnyDay();
            this._spawnConditions[SkyEntityType.SlimeBalloons] = () => AmbienceServer.IsSunnyDay() && Main.IsItAHappyWindyDay;
            this._spawnConditions[SkyEntityType.Gastropods] = () => AmbienceServer.IsCalmNight();
            this._spawnConditions[SkyEntityType.Pegasus] = () => AmbienceServer.IsSunnyDay();
            this._spawnConditions[SkyEntityType.EaterOfSouls] = () => AmbienceServer.IsSunnyDay() || AmbienceServer.IsCalmNight();
            this._spawnConditions[SkyEntityType.Crimera] = () => AmbienceServer.IsSunnyDay() || AmbienceServer.IsCalmNight();
            this._spawnConditions[SkyEntityType.Hellbats] = () => true;
            this._secondarySpawnConditionsPerPlayer[SkyEntityType.Vulture] = (Player player) => player.ZoneDesert;
            this._secondarySpawnConditionsPerPlayer[SkyEntityType.PixiePosse] = (Player player) => player.ZoneHallow;
            this._secondarySpawnConditionsPerPlayer[SkyEntityType.Seagulls] = (Player player) => player.ZoneBeach;
            this._secondarySpawnConditionsPerPlayer[SkyEntityType.Gastropods] = (Player player) => player.ZoneHallow;
            this._secondarySpawnConditionsPerPlayer[SkyEntityType.Pegasus] = (Player player) => player.ZoneHallow;
            this._secondarySpawnConditionsPerPlayer[SkyEntityType.EaterOfSouls] = (Player player) => player.ZoneCorrupt;
            this._secondarySpawnConditionsPerPlayer[SkyEntityType.Crimera] = (Player player) => player.ZoneCrimson;
            this._secondarySpawnConditionsPerPlayer[SkyEntityType.Bats] = (Player player) => player.ZoneJungle;
        }
References Terraria.GameContent.Ambience.AmbienceServer._secondarySpawnConditionsPerPlayer, Terraria.GameContent.Ambience.AmbienceServer._spawnConditions, Terraria.Main.dayTime, Terraria.Main.eclipse, Terraria.Main.hardMode, Terraria.GameContent.Ambience.AmbienceServer.IsCalmNight(), Terraria.Main.IsItAHappyWindyDay, Terraria.GameContent.Ambience.AmbienceServer.IsSunnyDay(), Terraria.GameContent.Ambience.AmbienceServer.IsSunset(), and Terraria.GameContent.Ambience.AmbienceServer.ResetSpawnTime().