Terraria Decompiled: Terraria.GameContent.Ambience.AmbienceServer.Update
Update()
void Terraria.GameContent.Ambience.AmbienceServer.Update () inline
Definition at line 73 of file AmbienceServer.cs.
        {
            this.SpawnForcedEntities();
            if (this._updatesUntilNextAttempt > 0)
            {
                this._updatesUntilNextAttempt -= Main.dayRate;
                return;
            }
            this.ResetSpawnTime();
            IEnumerable<SkyEntityType> enumerable = from pair in this._spawnConditions
                where pair.Value()
                select pair.Key;
            if (enumerable.Count((SkyEntityType type) => true) == 0)
            {
                return;
            }
            Player player;
            AmbienceServer.FindPlayerThatCanSeeBackgroundAmbience(out player);
            if (player == null)
            {
                return;
            }
            IEnumerable<SkyEntityType> enumerable2 = enumerable.Where((SkyEntityType type) => this.IsPlayerAtRightHeightForType(type, player) && this._secondarySpawnConditionsPerPlayer.ContainsKey(type) && this._secondarySpawnConditionsPerPlayer[type](player));
            int num = enumerable2.Count((SkyEntityType type) => true);
            if (num == 0 || Main.rand.Next(5) < 3)
            {
                enumerable2 = enumerable.Where((SkyEntityType type) => this.IsPlayerAtRightHeightForType(type, player) && (!this._secondarySpawnConditionsPerPlayer.ContainsKey(type) || this._secondarySpawnConditionsPerPlayer[type](player)));
                num = enumerable2.Count((SkyEntityType type) => true);
            }
            if (num == 0)
            {
                return;
            }
            SkyEntityType skyEntityType = enumerable2.ElementAt(Main.rand.Next(num));
            this.SpawnForPlayer(player, skyEntityType);
        }
References Terraria.GameContent.Ambience.AmbienceServer._secondarySpawnConditionsPerPlayer, Terraria.GameContent.Ambience.AmbienceServer._updatesUntilNextAttempt, Terraria.Main.dayRate, Terraria.GameContent.Ambience.AmbienceServer.FindPlayerThatCanSeeBackgroundAmbience(), Terraria.GameContent.Ambience.AmbienceServer.IsPlayerAtRightHeightForType(), Terraria.Main.rand, Terraria.GameContent.Ambience.AmbienceServer.ResetSpawnTime(), Terraria.GameContent.Ambience.AmbienceServer.SpawnForcedEntities(), and Terraria.GameContent.Ambience.AmbienceServer.SpawnForPlayer().
Referenced by Terraria.Main.DoUpdate().