Terraria Decompiled: Terraria.GameContent.Ambience.AmbienceServer.SpawnForcedEntities
SpawnForcedEntities()
void Terraria.GameContent.Ambience.AmbienceServer.SpawnForcedEntities () inline private
Definition at line 127 of file AmbienceServer.cs.
        {
            if (this._forcedSpawns.Count == 0)
            {
                return;
            }
            for (int i = this._forcedSpawns.Count - 1; i >= 0; i--)
            {
                AmbienceServer.AmbienceSpawnInfo ambienceSpawnInfo = this._forcedSpawns[i];
                Player player;
                if (ambienceSpawnInfo.targetPlayer == -1)
                {
                    AmbienceServer.FindPlayerThatCanSeeBackgroundAmbience(out player);
                }
                else
                {
                    player = Main.player[ambienceSpawnInfo.targetPlayer];
                }
                if (player != null && this.IsPlayerAtRightHeightForType(ambienceSpawnInfo.skyEntityType, player))
                {
                    this.SpawnForPlayer(player, ambienceSpawnInfo.skyEntityType);
                }
                this._forcedSpawns.RemoveAt(i);
            }
        }
References Terraria.GameContent.Ambience.AmbienceServer._forcedSpawns, Terraria.GameContent.Ambience.AmbienceServer.FindPlayerThatCanSeeBackgroundAmbience(), Terraria.GameContent.Ambience.AmbienceServer.IsPlayerAtRightHeightForType(), Terraria.Main.player, Terraria.GameContent.Ambience.AmbienceServer.AmbienceSpawnInfo.skyEntityType, Terraria.GameContent.Ambience.AmbienceServer.SpawnForPlayer(), and Terraria.GameContent.Ambience.AmbienceServer.AmbienceSpawnInfo.targetPlayer.
Referenced by Terraria.GameContent.Ambience.AmbienceServer.Update().