Terraria Decompiled: System.Activator.CreateInstance
CreateInstance() [8/15]
static ObjectHandle System.Activator.CreateInstance (string assemblyString, string typeName, bool ignoreCase, BindingFlags bindingAttr, Binder binder, object[] args, CultureInfo culture, object[] activationAttributes, Evidence securityInfo, ref StackCrawlMark stackMark) inline static package
Definition at line 192 of file Activator.cs.
        {
            Type type = null;
            Assembly assembly = null;
            if (assemblyString == null)
            {
                assembly = RuntimeAssembly.GetExecutingAssembly(ref stackMark);
            }
            else
            {
                RuntimeAssembly runtimeAssembly;
                AssemblyName assemblyName = RuntimeAssembly.CreateAssemblyName(assemblyString, false, out runtimeAssembly);
                if (runtimeAssembly != null)
                {
                    assembly = runtimeAssembly;
                }
                else if (assemblyName.ContentType == AssemblyContentType.WindowsRuntime)
                {
                    type = Type.GetType(typeName + ", " + assemblyString, true, ignoreCase);
                }
                else
                {
                    assembly = RuntimeAssembly.InternalLoadAssemblyName(assemblyName, securityInfo, null, ref stackMark, true, false, false);
                }
            }
            if (type == null)
            {
                if (assembly == null)
                {
                    return null;
                }
                type = assembly.GetType(typeName, true, ignoreCase);
            }
            object obj = Activator.CreateInstance(type, bindingAttr, binder, args, culture, activationAttributes);
            if (obj == null)
            {
                return null;
            }
            return new ObjectHandle(obj);
        }
References System.Reflection.AssemblyName.ContentType, System.Reflection.RuntimeAssembly.CreateAssemblyName(), System.Activator.CreateInstance(), System.culture, System.Reflection.RuntimeAssembly.GetExecutingAssembly(), System.Type.GetType(), System.Reflection.Assembly.GetType(), System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(), and System.obj.