Terraria Decompiled: System.Activator.CreateInstance
CreateInstance() [10/15]
static object System.Activator.CreateInstance (Type type, BindingFlags bindingAttr, Binder binder, object[] args, CultureInfo culture) inline static
Definition at line 29 of file Activator.cs.
        {
            return Activator.CreateInstance(type, bindingAttr, binder, args, culture, null);
        }
References System.Activator.CreateInstance(), and System.culture.
Referenced by System.Runtime.Remoting.Activation.RemoteActivator.Activate(), FullSerializer.Internal.fsDictionaryConverter.AddItemToDictionary(), System.Security.PermissionSet.AddPermission(), System.Runtime.Remoting.SingleCallIdentity.AsyncObjectProcessMessage(), System.Security.PermissionBuilder.Create(), System.Globalization.CultureInfo.CreateCalendar(), System.Activator.CreateComInstanceFrom(), Newtonsoft.Json.Utilities.ExpressionReflectionDelegateFactory.CreateDefaultConstructor< T >(), Newtonsoft.Json.Utilities.LateBoundReflectionDelegateFactory.CreateDefaultConstructor< T >(), System.Security.Cryptography.CryptoConfig.CreateFromName(), System.Security.Policy.CodeGroup.CreateFromXml(), FullSerializer.fsMetaType.CreateInstance(), System.Activator.CreateInstance(), System.AppDomain.CreateInstance(), System.Activator.CreateInstance(), System.AppDomain.CreateInstance(), System.AppDomain.CreateInstance(), System.Activator.CreateInstance(), System.Activator.CreateInstance(), System.AppDomain.CreateInstance(), System.Activator.CreateInstance(), System.Reflection.Assembly.CreateInstance(), System.Reflection.Assembly.CreateInstance(), System.Activator.CreateInstance(), System.Activator.CreateInstance(), System.Activator.CreateInstance(), System.Activator.CreateInstance(), System.Activator.CreateInstance(), System.Activator.CreateInstanceFromInternal(), System.RuntimeType.CreateInstanceImpl(), System.Runtime.Remoting.Channels.ChannelServices.CreateProvider(), System.Resources.ManifestBasedResourceGroveler.CreateResourceSet(), System.Resources.FileBasedResourceGroveler.CreateResourceSet(), System.LazyHelper.CreateViaDefaultConstructor(), System.Threading.LazyInitializer.EnsureInitializedCore< T >(), System.Threading.LazyInitializer.EnsureInitializedCore< T >(), Microsoft.Xna.Framework.Graphics.VertexDeclaration.FromType(), System.Security.Policy.CodeGroup.FromXml(), FullSerializer.fsSerializer.fsSerializer(), FullSerializer.fsSerializer.GetConverter(), Newtonsoft.Json.Utilities.ReflectionUtils.GetDefaultValue(), System.Security.Cryptography.RSACryptoServiceProvider.GetHash(), System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.GetOrCreateValue(), FullSerializer.fsSerializer.GetProcessors(), System.Runtime.Remoting.SingletonIdentity.GetServerObject(), System.RuntimeType.InvokeMember(), System.Security.PermissionSet.IsSubsetOf(), FullSerializer.Internal.fsVersionedType.Migrate(), System.Reflection.Emit.ModuleBuilder.ModuleBuilder(), Terraria.GameContent.LeashedEntity.NewInstance(), System.Security.PermissionSet.ProcessAttribute(), Microsoft.Xna.Framework.Content.ReflectiveReader< T >.Read(), Newtonsoft.Json.Converters.DataSetConverter.ReadJson(), Newtonsoft.Json.Converters.DataTableConverter.ReadJson(), System.Runtime.Remoting.SingleCallIdentity.SyncObjectProcessMessage(), and FullSerializer.Internal.fsKeyValuePairConverter.TryDeserialize().