Terraria Decompiled: Terraria.Graphics.Shaders.ArmorShaderDataSet.GetSecondaryShader
GetSecondaryShader()
ArmorShaderData Terraria.Graphics.Shaders.ArmorShaderDataSet.GetSecondaryShader (int id, Player player) inline
Definition at line 64 of file ArmorShaderDataSet.cs.
        {
            if (id != 0 && id <= this._shaderDataCount && this._shaderData[id - 1] != null)
            {
                return this._shaderData[id - 1].GetSecondaryShader(player);
            }
            return null;
        }
References Terraria.Graphics.Shaders.ArmorShaderDataSet._shaderData, Terraria.Graphics.Shaders.ArmorShaderDataSet._shaderDataCount, and Terraria.Graphics.Shaders.ArmorShaderData.GetSecondaryShader().
Referenced by Terraria.Projectile.AI(), Terraria.Projectile.AI_026(), Terraria.Projectile.AI_067_FreakingPirates(), Terraria.Projectile.AI_120_StardustGuardian(), Terraria.Player.ApplySetBonus_Solar(), Terraria.Player.ChickenBonesWingDust(), Terraria.Player.DashMovement(), Terraria.Mount.DoConfettiMinecartEffect(), Terraria.Mount.DoExhaustMinecartEffect(), Terraria.Mount.DoGemMinecartEffect(), Terraria.Player.DoGlassSlipperSparkles(), Terraria.Mount.DoSteamMinecartEffect(), Terraria.Player.DoubleJumpVisuals(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_07_LeinforsHairShampoo(), Terraria.Player.HeroicisWingDust(), Terraria.Player.JumpMovement(), Terraria.Player.KazzymodusWingDust(), Terraria.Player.KillMe_DustExplosion(), Terraria.Player.NinjaDodge(), Terraria.Player.PlayerFrame(), Terraria.Player.RocketBootVisuals(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_FlameWaders(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_WallOfFleshGoatMountFlames(), Terraria.Player.SpawnFastRunParticles(), Terraria.Player.Update(), Terraria.Mount.UpdateEffects(), Terraria.Mount.UpdateFrame(), Terraria.Player.UpdateMinionTarget(), Terraria.Player.WallClimbMovement(), Terraria.Player.WallslideMovement(), Terraria.Player.WingAirVisuals(), Terraria.Player.WingFrame(), and Terraria.Player.Yoraiz0rEye().