Terraria Decompiled: Newtonsoft.Json.Converters.KeyValuePairConverter.ReadJson
ReadJson()
override object Newtonsoft.Json.Converters.KeyValuePairConverter.ReadJson (JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer) inline
Definition at line 34 of file KeyValuePairConverter.cs.
        {
            if (reader.TokenType != JsonToken.Null)
            {
                object obj = null;
                object obj2 = null;
                reader.ReadAndAssert();
                Type type = (ReflectionUtils.IsNullableType(objectType) ? Nullable.GetUnderlyingType(objectType) : objectType);
                ReflectionObject reflectionObject = KeyValuePairConverter.ReflectionObjectPerType.Get(type);
                while (reader.TokenType == JsonToken.PropertyName)
                {
                    string text = reader.Value.ToString();
                    if (string.Equals(text, "Key", 5))
                    {
                        reader.ReadAndAssert();
                        obj = serializer.Deserialize(reader, reflectionObject.GetType("Key"));
                    }
                    else if (string.Equals(text, "Value", 5))
                    {
                        reader.ReadAndAssert();
                        obj2 = serializer.Deserialize(reader, reflectionObject.GetType("Value"));
                    }
                    else
                    {
                        reader.Skip();
                    }
                    reader.ReadAndAssert();
                }
                return reflectionObject.Creator(new object[] { obj, obj2 });
            }
            if (!ReflectionUtils.IsNullableType(objectType))
            {
                throw JsonSerializationException.Create(reader, "Cannot convert null value to KeyValuePair.");
            }
            return null;
        }
References Newtonsoft.Json.JsonSerializationException.Create(), Newtonsoft.Json.Utilities.ReflectionObject.Creator, Newtonsoft.Json.JsonSerializer.Deserialize(), Newtonsoft.Json.Utilities.ThreadSafeStore< TKey, TValue >.Get(), Newtonsoft.Json.Utilities.ReflectionObject.GetType(), System.Nullable< T >.GetUnderlyingType(), Newtonsoft.Json.Utilities.ReflectionUtils.IsNullableType(), System.obj, Newtonsoft.Json.JsonReader.ReadAndAssert(), Newtonsoft.Json.Converters.KeyValuePairConverter.ReflectionObjectPerType, Newtonsoft.Json.JsonReader.Skip(), System.text, Newtonsoft.Json.JsonReader.TokenType, and Newtonsoft.Json.JsonReader.Value.