Terraria Decompiled: Newtonsoft.Json.Converters.KeyValuePairConverter.CanConvert
CanConvert()
override bool Newtonsoft.Json.Converters.KeyValuePairConverter.CanConvert (Type objectType) inline
Definition at line 72 of file KeyValuePairConverter.cs.
        {
            Type type = (ReflectionUtils.IsNullableType(objectType) ? Nullable.GetUnderlyingType(objectType) : objectType);
            return type.IsValueType() && type.IsGenericType() && type.GetGenericTypeDefinition() == typeof(KeyValuePair);
        }
References System.Type.GetGenericTypeDefinition(), System.Nullable< T >.GetUnderlyingType(), System.Type.IsGenericType, Newtonsoft.Json.Utilities.ReflectionUtils.IsNullableType(), and System.Type.IsValueType.