Terraria Decompiled: FullSerializer.Internal.fsKeyValuePairConverter.TrySerialize
TrySerialize()
override fsResult FullSerializer.Internal.fsKeyValuePairConverter.TrySerialize (object instance, out fsData serialized, Type storageType) inline
Definition at line 57 of file fsKeyValuePairConverter.cs.
        {
            PropertyInfo declaredProperty = storageType.GetDeclaredProperty("Key");
            PropertyInfo declaredProperty2 = storageType.GetDeclaredProperty("Value");
            object value = declaredProperty.GetValue(instance, null);
            object value2 = declaredProperty2.GetValue(instance, null);
            Type[] genericArguments = storageType.GetGenericArguments();
            Type type = genericArguments[0];
            Type type2 = genericArguments[1];
            fsResult success = fsResult.Success;
            fsData fsData;
            success.AddMessages(this.Serializer.TrySerialize(type, value, out fsData));
            fsData fsData2;
            success.AddMessages(this.Serializer.TrySerialize(type2, value2, out fsData2));
            serialized = fsData.CreateDictionary();
            if (fsData != null)
            {
                serialized.AsDictionary["Key"] = fsData;
            }
            if (fsData2 != null)
            {
                serialized.AsDictionary["Value"] = fsData2;
            }
            return success;
        }
References FullSerializer.fsResult.AddMessages(), FullSerializer.fsData.AsDictionary, FullSerializer.fsData.CreateDictionary(), System.Type.GetGenericArguments(), System.Reflection.PropertyInfo.GetValue(), FullSerializer.fsBaseConverter.Serializer, FullSerializer.fsResult.Success, FullSerializer.fsSerializer.TrySerialize(), and System.value.