Terraria Decompiled: FullSerializer.Internal.fsKeyValuePairConverter.TryDeserialize
TryDeserialize()
override fsResult FullSerializer.Internal.fsKeyValuePairConverter.TryDeserialize (fsData data, ref object instance, Type storageType) inline
Definition at line 29 of file fsKeyValuePairConverter.cs.
        {
            fsResult fsResult = fsResult.Success;
            fsData fsData;
            fsResult fsResult2;
            fsResult = (fsResult2 = fsResult + base.CheckKey(data, "Key", out fsData));
            if (fsResult2.Failed)
            {
                return fsResult;
            }
            fsData fsData2;
            fsResult = (fsResult2 = fsResult + base.CheckKey(data, "Value", out fsData2));
            if (fsResult2.Failed)
            {
                return fsResult;
            }
            Type[] genericArguments = storageType.GetGenericArguments();
            Type type = genericArguments[0];
            Type type2 = genericArguments[1];
            object obj = null;
            object obj2 = null;
            fsResult.AddMessages(this.Serializer.TryDeserialize(fsData, type, ref obj));
            fsResult.AddMessages(this.Serializer.TryDeserialize(fsData2, type2, ref obj2));
            instance = Activator.CreateInstance(storageType, new object[] { obj, obj2 });
            return fsResult;
        }
References FullSerializer.fsResult.AddMessages(), System.Activator.CreateInstance(), FullSerializer.fsResult.Failed, System.Type.GetGenericArguments(), System.obj, FullSerializer.fsBaseConverter.Serializer, FullSerializer.fsResult.Success, and FullSerializer.fsSerializer.TryDeserialize().