Terraria Decompiled: Terraria.GameContent.UI.Elements.UIBestiaryEntryInfoPage.AddInfoToList
AddInfoToList()
void Terraria.GameContent.UI.Elements.UIBestiaryEntryInfoPage.AddInfoToList (BestiaryEntry entry, ExtraBestiaryInfoPageInformation extraInfo) inline private
Definition at line 134 of file UIBestiaryEntryInfoPage.cs.
        {
            BestiaryUICollectionInfo uicollectionInfo = this.GetUICollectionInfo(entry, extraInfo);
            IEnumerable<IGrouping<UIBestiaryEntryInfoPage.BestiaryInfoCategory, IBestiaryInfoElement>> enumerable = from x in new List<IBestiaryInfoElement>(entry.Info).GroupBy(new Func<IBestiaryInfoElement, UIBestiaryEntryInfoPage.BestiaryInfoCategory>(this.GetBestiaryInfoCategory))
                orderby x.Key
                select x;
            UIElement uielement = null;
            foreach (IGrouping<UIBestiaryEntryInfoPage.BestiaryInfoCategory, IBestiaryInfoElement> grouping in enumerable)
            {
                if (grouping.Count<IBestiaryInfoElement>() != 0)
                {
                    bool flag = false;
                    foreach (IBestiaryInfoElement bestiaryInfoElement in grouping.OrderByDescending(new Func<IBestiaryInfoElement, float>(this.GetIndividualElementPriority)))
                    {
                        UIElement uielement2 = bestiaryInfoElement.ProvideUIElement(uicollectionInfo);
                        if (uielement2 != null)
{
                            this._list.Add(uielement2);
                            flag = true;
                        }
                    }
                    if (flag)
                    {
                        UIHorizontalSeparator uihorizontalSeparator = new UIHorizontalSeparator(2, true)
{
                            Width = StyleDimension.FromPixelsAndPercent(0f, 1f),
                            Color = new Color(89, 116, 213, 255) * 0.9f
                        };
                        this._list.Add(uihorizontalSeparator);
                        uielement = uihorizontalSeparator;
                    }
                }
            }
            this._list.Remove(uielement);
        }
References Terraria.GameContent.UI.Elements.UIBestiaryEntryInfoPage._list, Terraria.GameContent.UI.Elements.UIList.Add(), Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.GameContent.UI.Elements.UIBestiaryEntryInfoPage.GetBestiaryInfoCategory(), Terraria.GameContent.UI.Elements.UIBestiaryEntryInfoPage.GetUICollectionInfo(), Terraria.GameContent.Bestiary.BestiaryEntry.Info, Terraria.GameContent.Bestiary.IBestiaryInfoElement.ProvideUIElement(), Terraria.GameContent.UI.Elements.UIList.Remove(), and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.Elements.UIBestiaryEntryInfoPage.FillInfoForEntry().