Terraria Decompiled: Terraria.GameContent.AnOutlinedDrawRenderTargetContent.HandleUseRequest
HandleUseRequest()
override void Terraria.GameContent.AnOutlinedDrawRenderTargetContent.HandleUseRequest (GraphicsDevice device, SpriteBatch spriteBatch) inline protected
Definition at line 17 of file AnOutlinedDrawRenderTargetContent.cs.
        {
            Effect pixelShader = Main.pixelShader;
            EffectPass effectPass = pixelShader.CurrentTechnique.Passes["ColorOnly"];
            new Rectangle(0, 0, this.width, this.height);
            base.PrepareARenderTarget_AndListenToEvents(ref this._target, device, this.width, this.height, RenderTargetUsage.PreserveContents);
            base.PrepareARenderTarget_WithoutListeningToEvents(ref this._helperTarget, device, this.width, this.height, RenderTargetUsage.DiscardContents);
            device.SetRenderTarget(this._helperTarget);
            device.Clear(Color.Transparent);
            spriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend, SamplerState.PointClamp, DepthStencilState.None, RasterizerState.CullCounterClockwise, null);
            this.DrawTheContent(spriteBatch);
            spriteBatch.End();
            device.SetRenderTarget(this._target);
            device.Clear(Color.Transparent);
            spriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend, SamplerState.PointClamp, DepthStencilState.None, RasterizerState.CullCounterClockwise, null);
            effectPass.Apply();
            int num = 2;
            int num2 = num * 2;
            for (int i = -num2; i <= num2; i += num)
            {
                for (int j = -num2; j <= num2; j += num)
                {
                    if (Math.Abs(i) + Math.Abs(j) == num2)
                    {
                        spriteBatch.Draw(this._helperTarget, new Vector2((float)i, (float)j), Color.Black);
                    }
                }
            }
            num2 = num;
            for (int k = -num2; k <= num2; k += num)
            {
                for (int l = -num2; l <= num2; l += num)
                {
                    if (Math.Abs(k) + Math.Abs(l) == num2)
                    {
                        spriteBatch.Draw(this._helperTarget, new Vector2((float)k, (float)l), this._borderColor);
                    }
                }
            }
            pixelShader.CurrentTechnique.Passes[0].Apply();
            spriteBatch.Draw(this._helperTarget, Vector2.Zero, Color.White);
            spriteBatch.End();
            device.SetRenderTarget(null);
            this._wasPrepared = true;
        }
References Terraria.GameContent.AnOutlinedDrawRenderTargetContent._borderColor, Terraria.GameContent.AnOutlinedDrawRenderTargetContent._helperTarget, Terraria.GameContent.ARenderTargetContentByRequest._target, System.Math.Abs(), Microsoft.Xna.Framework.Graphics.BlendState.AlphaBlend, Microsoft.Xna.Framework.Graphics.EffectPass.Apply(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(), Microsoft.Xna.Framework.Color.Black, Microsoft.Xna.Framework.Graphics.GraphicsDevice.Clear(), Microsoft.Xna.Framework.Graphics.RasterizerState.CullCounterClockwise, Microsoft.Xna.Framework.Graphics.Effect.CurrentTechnique, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.GameContent.AnOutlinedDrawRenderTargetContent.DrawTheContent(), Microsoft.Xna.Framework.Graphics.SpriteBatch.End(), Terraria.GameContent.AnOutlinedDrawRenderTargetContent.height, Microsoft.Xna.Framework.Graphics.DepthStencilState.None, Microsoft.Xna.Framework.Graphics.EffectTechnique.Passes, Terraria.Main.pixelShader, Microsoft.Xna.Framework.Graphics.SamplerState.PointClamp, Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetRenderTarget(), Microsoft.Xna.Framework.Color.Transparent, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Color.White, Terraria.GameContent.AnOutlinedDrawRenderTargetContent.width, and Microsoft.Xna.Framework.Vector2.Zero.