Terraria Decompiled: Terraria.GameContent.LeashedEntities.LeashedKite.MoveKite
MoveKite()
void Terraria.GameContent.LeashedEntities.LeashedKite.MoveKite (bool fastForward = false) inline private
Definition at line 143 of file LeashedKite.cs.
        {
            this.CopyToDummy();
            LeashedKite._dummy.owner = 255;
            Player player = Main.player[255];
            Vector2 anchorWorldPosition = this.AnchorWorldPosition;
            player.Center = anchorWorldPosition;
            if (this.timeWithoutWind == 0)
            {
                int num = ((LeashedKite._dummy.Center.X - anchorWorldPosition.X < 0f) ? (-1) : 1);
                LeashedKite._dummy.spriteDirection = num;
                player.direction = num;
            }
            this.timeCounter += 0.016666668f;
            KiteFlyingInfo kiteFlyingInfo = new KiteFlyingInfo
            {
                BobOffset = (anchorWorldPosition.X + anchorWorldPosition.Y * 0.92f) * 0.0025f,
                WindInWorld = this.windCurrent,
                CloudAlpha = this.cloudAlpha,
                GlobalTime = this.timeCounter,
                CanReelThroughBlocks = false
            };
            if (fastForward)
            {
                LeashedKite._dummy.KiteLogic(anchorWorldPosition, kiteFlyingInfo);
                this.timeCounter = 6f;
                Vector2 vector = new Vector2(kiteFlyingInfo.WindInWorld, (float)((kiteFlyingInfo.WindInWorld > 0f) ? (-2) : 2)).SafeNormalize(Vector2.Zero) * this.kiteDistance;
                Vector2 position = LeashedKite._dummy.position;
                LeashedKite._dummy.velocity = vector;
                LeashedKite._dummy.HandleMovement(LeashedKite._dummy.velocity);
                LeashedKite._dummy.position = LeashedKite._dummy.position.MoveTowards(position, 1f);
                if (LeashedKite._dummy.velocity.Length() > 4f)
                {
                    LeashedKite._dummy.velocity = LeashedKite._dummy.velocity.SafeNormalize(Vector2.Zero) * 4f;
                }
                LeashedKite._dummy.KiteLogic(anchorWorldPosition, kiteFlyingInfo);
                if (kiteFlyingInfo.WindInWorld == 0f)
                {
                    LeashedKite._dummy.rotation = 0f;
                    LeashedKite._dummy.localAI[0] = 300f;
                    LeashedKite._dummy.localAI[1] = 1f;
                }
                for (int i = this.oldPos.Length - 1; i >= 0; i--)
                {
                    this.oldPos[i] = LeashedKite._dummy.position;
                    this.oldRot[i] = LeashedKite._dummy.rotation;
                    this.oldSpriteDirection[i] = LeashedKite._dummy.spriteDirection;
                }
            }
            else
            {
                Utils.Shift<Vector2>(this.oldPos, 1);
                Utils.Shift<float>(this.oldRot, 1);
                Utils.Shift<int>(this.oldSpriteDirection, 1);
                this.oldPos[0] = this.position;
                this.oldRot[0] = this.rotation;
                this.oldSpriteDirection[0] = this.spriteDirection;
                LeashedKite._dummy.KiteLogic(anchorWorldPosition, kiteFlyingInfo);
                LeashedKite._dummy.HandleMovement(LeashedKite._dummy.velocity);
                Vector2 vector2;
                int num2;
                int num3;
                LeashedKite._dummy.GetCollisionParams(out vector2, out num2, out num3);
                if (Collision.SolidFullTiles(LeashedKite._dummy.position + LeashedKite._dummy.Size / 2f - new Vector2((float)num2, (float)num3) * vector2, new Vector2((float)num2, (float)num3)))
                {
                    LeashedKite._dummy.Bottom = LeashedKite._dummy.Bottom.MoveTowards(anchorWorldPosition, 2f);
                }
            }
            this.CopyFromDummy();
        }
References Terraria.GameContent.LeashedEntities.LeashedKite._dummy, Terraria.GameContent.LeashedEntities.LeashedKite.AnchorWorldPosition, Terraria.Entity.Bottom, Terraria.GameContent.LeashedEntities.LeashedKite.cloudAlpha, Terraria.GameContent.LeashedEntities.LeashedKite.CopyFromDummy(), Terraria.GameContent.LeashedEntities.LeashedKite.CopyToDummy(), Terraria.Projectile.GetCollisionParams(), Terraria.Projectile.HandleMovement(), Terraria.GameContent.LeashedEntities.LeashedKite.kiteDistance, Terraria.Projectile.KiteLogic(), Microsoft.Xna.Framework.Vector2.Length(), Terraria.Projectile.localAI, Terraria.GameContent.LeashedEntities.LeashedKite.oldPos, Terraria.GameContent.LeashedEntities.LeashedKite.oldRot, Terraria.GameContent.LeashedEntities.LeashedKite.oldSpriteDirection, Terraria.Main.player, Terraria.Entity.position, Terraria.GameContent.LeashedEntity.position, Terraria.GameContent.LeashedEntities.LeashedKite.rotation, Terraria.Projectile.rotation, Terraria.Entity.Size, Terraria.Collision.SolidFullTiles(), Terraria.GameContent.LeashedEntities.LeashedKite.spriteDirection, Terraria.Projectile.spriteDirection, Terraria.GameContent.LeashedEntities.LeashedKite.timeCounter, Terraria.GameContent.LeashedEntities.LeashedKite.timeWithoutWind, Terraria.Entity.velocity, Terraria.GameContent.LeashedEntities.LeashedKite.windCurrent, Terraria.DataStructures.KiteFlyingInfo.WindInWorld, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.LeashedEntities.LeashedKite.Update().