Terraria Decompiled: Terraria.GameContent.LeashedEntities.LeashedKite.NetReceive
NetReceive()
override void Terraria.GameContent.LeashedEntities.LeashedKite.NetReceive (BinaryReader reader, bool full) inline virtual
Reimplemented from Terraria.GameContent.LeashedEntity.
Definition at line 36 of file LeashedKite.cs.
        {
            if (full)
            {
                this.SetDefaults(reader.Read7BitEncodedInt());
            }
            Vector2 position = this.position;
            this.position = reader.ReadVector2();
            this.velocity = reader.ReadPackedVector2();
            this.rotation = (float)((double)reader.ReadByte() * 3.141592653589793 * 2.0 / 256.0);
            this.windTarget = reader.ReadSingle();
            this.cloudAlpha = reader.ReadSingle();
            this.timeCounter = reader.ReadSingle();
            if (full)
            {
                this.netOffset = Vector2.Zero;
            }
            else
            {
                this.netOffset += position - this.position;
            }
            if (full)
            {
                this.Update();
                this.FixFirstTimeAppearance();
            }
        }
References Terraria.GameContent.LeashedEntities.LeashedKite.FixFirstTimeAppearance(), Terraria.GameContent.LeashedEntity.position, System.IO.BinaryReader.Read7BitEncodedInt(), System.IO.BinaryReader.ReadByte(), System.IO.BinaryReader.ReadSingle(), Terraria.GameContent.LeashedEntities.LeashedKite.SetDefaults(), Terraria.GameContent.LeashedEntities.LeashedKite.Update(), and Microsoft.Xna.Framework.Vector2.Zero.