Terraria Decompiled: Terraria.GameContent.LeashedEntities.LeashedKite.Update
Update() [2/2]
void Terraria.GameContent.LeashedEntities.LeashedKite.Update (bool fastForward) inline
Definition at line 100 of file LeashedKite.cs.
        {
            if (this.oldPos == null)
            {
                int num = ProjectileID.Sets.TrailCacheLength[this.projType];
                this.oldPos = new Vector2[num];
                this.oldRot = new float[num];
                this.oldSpriteDirection = new int[num];
            }
            if (base.NearbySectionsMissing(3))
            {
                return;
            }
            if (fastForward || Vector2.DistanceSquared(this.position, this.oldPos[0]) > 256f)
            {
                for (int i = 0; i < this.oldPos.Length; i++)
                {
                    this.oldPos[i] = this.position;
                    this.oldRot[i] = this.rotation;
                    this.oldSpriteDirection[i] = this.spriteDirection;
                }
            }
            if (Main.netMode != 1)
            {
                this.windTarget = Main.WindForVisuals;
                this.cloudAlpha = Main.cloudAlpha;
            }
            this.windCurrent = 0f;
            if (WorldGen.InAPlaceWithWind(this.position, this.width, this.height))
            {
                this.windCurrent = (fastForward ? this.windTarget : MathHelper.Lerp(this.windCurrent, this.windTarget, 0.05f));
            }
            else
            {
                this.windTarget = 0f;
            }
            this.timeWithoutWind = ((Math.Abs(this.windCurrent) >= 0.2f) ? 0 : (fastForward ? 3600 : (this.timeWithoutWind + 1)));
            this.kiteDistance = Utils.Remap((float)this.timeWithoutWind, 120f, 420f, 250f, 48f, true);
            this.MoveKite(fastForward);
            this.netOffset = this.netOffset.MoveTowards(Vector2.Zero, 2f);
        }
References System.Math.Abs(), Terraria.Main.cloudAlpha, Microsoft.Xna.Framework.Vector2.DistanceSquared(), Terraria.WorldGen.InAPlaceWithWind(), Microsoft.Xna.Framework.Vector2.Length(), Microsoft.Xna.Framework.MathHelper.Lerp(), Terraria.GameContent.LeashedEntities.LeashedKite.MoveKite(), Terraria.Main.netMode, Terraria.GameContent.LeashedEntities.LeashedKite.netOffset, Terraria.GameContent.LeashedEntities.LeashedKite.oldPos, Terraria.GameContent.LeashedEntities.LeashedKite.oldRot, Terraria.GameContent.LeashedEntities.LeashedKite.oldSpriteDirection, Terraria.GameContent.LeashedEntity.position, Terraria.GameContent.LeashedEntities.LeashedKite.projType, Terraria.Utils.Remap(), Terraria.GameContent.LeashedEntities.LeashedKite.rotation, Terraria.GameContent.LeashedEntities.LeashedKite.spriteDirection, Terraria.GameContent.LeashedEntities.LeashedKite.timeWithoutWind, Terraria.ID.ProjectileID.Sets.TrailCacheLength, Terraria.GameContent.LeashedEntities.LeashedKite.windCurrent, Terraria.Main.WindForVisuals, Terraria.GameContent.LeashedEntities.LeashedKite.windTarget, and Microsoft.Xna.Framework.Vector2.Zero.