Terraria Decompiled: Terraria.GameContent.LeashedEntities.LeashedKite.Draw
Draw()
override void Terraria.GameContent.LeashedEntities.LeashedKite.Draw () inline virtual
Reimplemented from Terraria.GameContent.LeashedEntity.
Definition at line 85 of file LeashedKite.cs.
        {
            Main.instance.LoadProjectile(this.projType);
            this.CopyToDummy();
            LeashedKite._dummy.position += this.netOffset;
            Main.DrawKite(LeashedKite._dummy, this.AnchorWorldPosition);
        }
References Terraria.GameContent.LeashedEntities.LeashedKite._dummy, Terraria.GameContent.LeashedEntities.LeashedKite.CopyToDummy(), Terraria.Main.DrawKite(), Terraria.Main.instance, Terraria.Main.LoadProjectile(), Terraria.GameContent.LeashedEntities.LeashedKite.netOffset, and Terraria.GameContent.LeashedEntities.LeashedKite.projType.