Terraria Decompiled: Terraria.Graphics.Renderers.ShockIconParticle.Update
Update()
override void Terraria.Graphics.Renderers.ShockIconParticle.Update (ref ParticleRendererSettings settings) inline virtual
Reimplemented from Terraria.Graphics.Renderers.ABasicParticle.
Definition at line 25 of file ShockIconParticle.cs.
        {
            if (this._timeSinceSpawn == 0f)
            {
                this.initialPosition = this.LocalPosition;
            }
            base.Update(ref settings);
            this._timeSinceSpawn += 1f;
            float num = this._timeSinceSpawn / this.TimeToLive;
            this.Scale = Vector2.One * this.InitialScale * Utils.MultiLerp(num, new float[] { 0.2f, 0.9f, 1.3f, 0.9f });
            this.Opacity = MathHelper.Clamp(Utils.Remap(num, 0f, this.FadeInNormalizedTime, 0f, 1f, true) * Utils.Remap(num, this.FadeOutNormalizedTime, 1f, 1f, 0f, true), 0f, 1f) * 0.5f;
            if (this.ParentProjectileID != -1 && this.ParentProjectileID >= 0 && this.ParentProjectileID < 1000)
            {
                Projectile projectile = Main.projectile[this.ParentProjectileID];
                this.LocalPosition = projectile.Top + num * this.OffsetFromParent;
            }
            else
            {
                this.LocalPosition = this.initialPosition + num * this.OffsetFromParent;
            }
            if (this._timeSinceSpawn >= this.TimeToLive)
            {
                base.ShouldBeRemovedFromRenderer = true;
            }
        }
References Terraria.Graphics.Renderers.ShockIconParticle._timeSinceSpawn, Microsoft.Xna.Framework.MathHelper.Clamp(), Terraria.Graphics.Renderers.ABasicParticle.LocalPosition, Terraria.Utils.MultiLerp(), Terraria.Graphics.Renderers.ShockIconParticle.OffsetFromParent, Terraria.Graphics.Renderers.ShockIconParticle.ParentProjectileID, Terraria.Main.projectile, Terraria.Utils.Remap(), and Terraria.Graphics.Renderers.ShockIconParticle.TimeToLive.