Terraria Decompiled: rail.IRailIMEHelperImpl.UpdateIMEHelperTextInputWindowPosition
UpdateIMEHelperTextInputWindowPosition()
virtual RailResult rail.IRailIMEHelperImpl.UpdateIMEHelperTextInputWindowPosition (RailWindowPosition position) inline virtual
Implements rail.IRailIMEHelper.
Definition at line 40 of file IRailIMEHelperImpl.cs.
        {
            IntPtr intPtr = ((position == null) ? IntPtr.Zero : RAIL_API_PINVOKE.new_RailWindowPosition__SWIG_0());
            if (position != null)
            {
                RailConverter.Csharp2Cpp(position, intPtr);
            }
            RailResult railResult;
            try
            {
                railResult = (RailResult)RAIL_API_PINVOKE.IRailIMEHelper_UpdateIMEHelperTextInputWindowPosition(this.swigCPtr_, intPtr);
            }
            finally
            {
                RAIL_API_PINVOKE.delete_RailWindowPosition(intPtr);
            }
            return railResult;
        }
References rail.RailConverter.Csharp2Cpp(), rail.RAIL_API_PINVOKE.delete_RailWindowPosition(), rail.RAIL_API_PINVOKE.IRailIMEHelper_UpdateIMEHelperTextInputWindowPosition(), rail.RAIL_API_PINVOKE.new_RailWindowPosition__SWIG_0(), and System.IntPtr.Zero.