Terraria Decompiled: Terraria.Audio.MusicCueHolder.Play
Play()
void Terraria.Audio.MusicCueHolder.Play (float volume) inline
Definition at line 112 of file MusicCueHolder.cs.
        {
            this.LoadTrack(false);
            this.SetVolume(volume);
            this._loadedCue.Play();
        }
References Terraria.Audio.MusicCueHolder._loadedCue, Terraria.Audio.MusicCueHolder.LoadTrack(), Microsoft.Xna.Framework.Audio.Cue.Play(), and Terraria.Audio.MusicCueHolder.SetVolume().