Terraria Decompiled: FullSerializer.fsResult.AddMessages
AddMessages()
void FullSerializer.fsResult.AddMessages (fsResult result) inline
Definition at line 21 of file fsResult.cs.
        {
            if (result._messages == null)
            {
                return;
            }
            if (this._messages == null)
            {
                this._messages = new List<string>();
            }
            this._messages.AddRange(result._messages);
        }
References FullSerializer.fsResult._messages, and System.Collections.Generic.List< T >.AddRange().
Referenced by FullSerializer.Internal.fsArrayConverter.TryDeserialize(), FullSerializer.Internal.fsKeyValuePairConverter.TryDeserialize(), FullSerializer.Internal.fsReflectedConverter.TryDeserialize(), FullSerializer.Internal.fsIEnumerableConverter.TryDeserialize(), FullSerializer.Internal.fsArrayConverter.TrySerialize(), FullSerializer.Internal.fsKeyValuePairConverter.TrySerialize(), FullSerializer.Internal.fsReflectedConverter.TrySerialize(), and FullSerializer.Internal.fsIEnumerableConverter.TrySerialize().