Terraria Decompiled: FullSerializer.fsResult.Fail
Fail()
static fsResult FullSerializer.fsResult.Fail (string warning) inline static
Definition at line 64 of file fsResult.cs.
        {
            fsResult fsResult = default(fsResult);
            fsResult._success = false;
            List<string> list = new List<string>();
            list.Add(warning);
            fsResult._messages = list;
            return fsResult;
        }
References FullSerializer.fsResult.fsResult(), and System.list.
Referenced by FullSerializer.fsBaseConverter.CheckKey(), FullSerializer.fsBaseConverter.CheckType(), FullSerializer.fsBaseConverter.DeserializeMember< T >(), SteelSeries.GameSense.BindEventConverter.DoDeserialize(), SteelSeries.GameSense.BindEventLocalizationsConverter.DoDeserialize(), SteelSeries.GameSense.BitmapEventTypeConverter.DoDeserialize(), SteelSeries.GameSense.ColorHandlerConverter.DoDeserialize(), SteelSeries.GameSense.ColorRangeConverter.DoDeserialize(), SteelSeries.GameSense.ContextColorEventTypeConverter.DoDeserialize(), SteelSeries.GameSense.PartialBitmapEventTypeConverter.DoDeserialize(), SteelSeries.GameSense.RateRangeConverter.DoDeserialize(), SteelSeries.GameSense.RateStaticConverter.DoDeserialize(), SteelSeries.GameSense.RegisterEventConverter.DoDeserialize(), SteelSeries.GameSense.RegisterGameConverter.DoDeserialize(), SteelSeries.GameSense.RepeatLimitConverter.DoDeserialize(), SteelSeries.GameSense.SendEventConverter.DoDeserialize(), SteelSeries.GameSense.TactileEffectCustomConverter.DoDeserialize(), SteelSeries.GameSense.TactileEffectRangeConverter.DoDeserialize(), SteelSeries.GameSense.TactileEffectSimpleConverter.DoDeserialize(), SteelSeries.GameSense.TactileHandlerConverter.DoDeserialize(), FullSerializer.fsBaseConverter.FailExpectedType(), FullSerializer.Internal.fsForwardConverter.GetProperty(), FullSerializer.Internal.fsVersionManager.GetVersionImportPath(), FullSerializer.fsJsonParser.MakeFailure(), FullSerializer.fsJsonParser.Parse(), FullSerializer.Internal.fsDateConverter.TryDeserialize(), FullSerializer.Internal.fsEnumConverter.TryDeserialize(), FullSerializer.Internal.fsGuidConverter.TryDeserialize(), FullSerializer.Internal.fsTypeConverter.TryDeserialize(), FullSerializer.Internal.fsPrimitiveConverter.TryDeserialize(), and FullSerializer.Internal.fsPrimitiveConverter.TrySerialize().