Terraria Decompiled: Mono.Math.BigInteger.operator-
operator-()
static BigInteger Mono.Math.BigInteger.operator- (BigInteger bi1, BigInteger bi2) inline static
Definition at line 210 of file BigInteger.cs.
        {
            if (bi2 == 0U)
            {
                return new BigInteger(bi1);
            }
            if (bi1 == 0U)
            {
                throw new ArithmeticException("Operation would return a negative value");
            }
            switch (BigInteger.Kernel.Compare(bi1, bi2))
            {
            case BigInteger.Sign.Negative:
                throw new ArithmeticException("Operation would return a negative value");
            case BigInteger.Sign.Zero:
                return 0;
            case BigInteger.Sign.Positive:
                return BigInteger.Kernel.Subtract(bi1, bi2);
            default:
                throw new Exception();
            }
        }
References Mono.Math.BigInteger.BigInteger(), Mono.Math.BigInteger.Kernel.Compare(), Mono.Math.BigInteger.Kernel.Subtract(), and System.U.