Terraria Decompiled: Mono.Math.BigInteger.LowestSetBit
LowestSetBit()
int Mono.Math.BigInteger.LowestSetBit () inline
Definition at line 527 of file BigInteger.cs.
        {
            if (this == 0U)
            {
                return -1;
            }
            int num = 0;
            while (!this.TestBit(num))
            {
                num++;
            }
            return num;
        }
References Mono.Math.BigInteger.TestBit(), and System.U.
Referenced by Mono.Math.Prime.PrimalityTests.RabinMillerTest(), and Mono.Math.Prime.PrimalityTests.SmallPrimeSppTest().