Terraria Decompiled: Mono.Math.BigInteger.operator*
operator*() [2/2]
static BigInteger Mono.Math.BigInteger.operator* (BigInteger bi1, BigInteger bi2) inline static
Definition at line 272 of file BigInteger.cs.
        {
            if (bi1 == 0U || bi2 == 0U)
            {
                return 0;
            }
            if ((long)bi1.data.Length < (long)((ulong)bi1.length))
            {
                throw new IndexOutOfRangeException("bi1 out of range");
            }
            if ((long)bi2.data.Length < (long)((ulong)bi2.length))
            {
                throw new IndexOutOfRangeException("bi2 out of range");
            }
            BigInteger bigInteger = new BigInteger(BigInteger.Sign.Positive, bi1.length + bi2.length);
            BigInteger.Kernel.Multiply(bi1.data, 0U, bi1.length, bi2.data, 0U, bi2.length, bigInteger.data, 0U);
            bigInteger.Normalize();
            return bigInteger;
        }
References Mono.Math.BigInteger.BigInteger(), Mono.Math.BigInteger.data, Mono.Math.BigInteger.length, Mono.Math.BigInteger.Kernel.Multiply(), Mono.Math.BigInteger.Normalize(), and System.U.