Terraria Decompiled: Mono.Math.BigInteger.GenerateRandom
GenerateRandom() [2/2]
static BigInteger Mono.Math.BigInteger.GenerateRandom (int bits, RandomNumberGenerator rng) inline static
Definition at line 391 of file BigInteger.cs.
        {
            int num = bits >> 5;
            int num2 = bits & 31;
            if (num2 != 0)
            {
                num++;
            }
            BigInteger bigInteger = new BigInteger(BigInteger.Sign.Positive, (uint)(num + 1));
            byte[] array = new byte[num << 2];
            rng.GetBytes(array);
            Buffer.BlockCopy(array, 0, bigInteger.data, 0, num << 2);
            if (num2 != 0)
            {
                uint num3 = 1U << num2 - 1;
                bigInteger.data[num - 1] |= num3;
                num3 = uint.MaxValue >> 32 - num2;
                bigInteger.data[num - 1] &= num3;
            }
            else
            {
                bigInteger.data[num - 1] |= 2147483648U;
            }
            bigInteger.Normalize();
            return bigInteger;
        }
References System.array, Mono.Math.BigInteger.BigInteger(), System.Buffer.BlockCopy(), Mono.Math.BigInteger.data, System.Security.Cryptography.RandomNumberGenerator.GetBytes(), Mono.Math.BigInteger.Normalize(), Mono.Math.BigInteger.rng, and System.U.
Referenced by Mono.Security.Cryptography.DSAManaged.CreateSignature(), Mono.Security.Cryptography.RSAManaged.DecryptValue(), Mono.Security.Cryptography.DSAManaged.GenerateKeyPair(), Mono.Security.Cryptography.DSAManaged.GenerateParams(), Mono.Math.BigInteger.GenerateRandom(), Mono.Math.Prime.Generator.SequentialSearchPrimeGeneratorBase.GenerateSearchBase(), and Mono.Math.Prime.PrimalityTests.RabinMillerTest().