Terraria Decompiled: Mono.Math.BigInteger.GetBytes
GetBytes()
byte[] Mono.Math.BigInteger.GetBytes () inline
Definition at line 542 of file BigInteger.cs.
        {
            if (this == 0U)
            {
                return new byte[1];
            }
            int num = this.BitCount();
            int num2 = num >> 3;
            if ((num & 7) != 0)
            {
                num2++;
            }
            byte[] array = new byte[num2];
            int num3 = num2 & 3;
            if (num3 == 0)
            {
                num3 = 4;
            }
            int num4 = 0;
            for (int i = (int)(this.length - 1U); i >= 0; i--)
            {
                uint num5 = this.data[i];
                for (int j = num3 - 1; j >= 0; j--)
                {
                    array[num4 + j] = (byte)(num5 & 255U);
                    num5 >>= 8;
                }
                num4 += num3;
                num3 = 4;
            }
            return array;
        }
References System.array, Mono.Math.BigInteger.BitCount(), Mono.Math.BigInteger.data, Mono.Math.BigInteger.length, and System.U.
Referenced by Mono.Security.Cryptography.DSAManaged.CreateSignature(), Mono.Security.Cryptography.DSAManaged.ExportParameters(), and Mono.Security.Cryptography.RSAManaged.ExportParameters().