Terraria Decompiled: Mono.Math.BigInteger.Randomize
Randomize() [2/2]
void Mono.Math.BigInteger.Randomize (RandomNumberGenerator rng) inline
Definition at line 425 of file BigInteger.cs.
        {
            if (this == 0U)
            {
                return;
            }
            int num = this.BitCount();
            int num2 = num >> 5;
            int num3 = num & 31;
            if (num3 != 0)
            {
                num2++;
            }
            byte[] array = new byte[num2 << 2];
            rng.GetBytes(array);
            Buffer.BlockCopy(array, 0, this.data, 0, num2 << 2);
            if (num3 != 0)
            {
                uint num4 = 1U << num3 - 1;
                this.data[num2 - 1] |= num4;
                num4 = uint.MaxValue >> 32 - num3;
                this.data[num2 - 1] &= num4;
            }
            else
            {
                this.data[num2 - 1] |= 2147483648U;
            }
            this.Normalize();
        }
References System.array, Mono.Math.BigInteger.BitCount(), System.Buffer.BlockCopy(), Mono.Math.BigInteger.data, System.Security.Cryptography.RandomNumberGenerator.GetBytes(), Mono.Math.BigInteger.Normalize(), Mono.Math.BigInteger.rng, and System.U.
Referenced by Mono.Security.Cryptography.DSAManaged.CreateSignature(), and Mono.Security.Cryptography.DSAManaged.GenerateKeyPair().