Terraria Decompiled: System.Reflection.RuntimeFieldInfo.GetCustomModifiers
GetCustomModifiers()
Type[] System.Reflection.RuntimeFieldInfo.GetCustomModifiers (bool optional) inline private
Definition at line 381 of file RuntimeFieldInfo.cs.
        {
            return this.GetTypeModifiers(optional) ?? Type.EmptyTypes;
        }
References System.Type.EmptyTypes, and System.Reflection.RuntimeFieldInfo.GetTypeModifiers().
Referenced by System.Reflection.RuntimeFieldInfo.GetOptionalCustomModifiers(), and System.Reflection.RuntimeFieldInfo.GetRequiredCustomModifiers().