Terraria Decompiled: System.Reflection.RuntimeFieldInfo.GetValue
GetValue()
override object System.Reflection.RuntimeFieldInfo.GetValue (object obj) inline
Definition at line 218 of file RuntimeFieldInfo.cs.
        {
            if (!base.IsStatic)
            {
                if (obj == null)
                {
                    throw new TargetException("Non-static field requires a target");
                }
                if (!this.DeclaringType.IsAssignableFrom(obj.GetType()))
                {
                    throw new ArgumentException(string.Format("Field {0} defined on type {1} is not a field on the target object which is of type {2}.", this.Name, this.DeclaringType, obj.GetType()), "obj");
                }
            }
            if (!base.IsLiteral)
            {
                this.CheckGeneric();
            }
            return this.GetValueInternal(obj);
        }
References System.Reflection.RuntimeFieldInfo.CheckGeneric(), System.Reflection.RuntimeFieldInfo.DeclaringType, System.Format, System.Reflection.RuntimeFieldInfo.GetValueInternal(), System.Type.IsAssignableFrom(), System.Reflection.RuntimeFieldInfo.Name, and System.obj.
Referenced by System.Runtime.Serialization.SerializationFieldInfo.GetValue(), System.Runtime.Serialization.SerializationFieldInfo.InternalGetValue(), and System.RuntimeFieldHandle.RuntimeFieldHandle().