Terraria Decompiled: System.Reflection.RuntimeFieldInfo.SetValue
SetValue()
override void System.Reflection.RuntimeFieldInfo.SetValue (object obj, object val, BindingFlags invokeAttr, Binder binder, CultureInfo culture) inline
Definition at line 249 of file RuntimeFieldInfo.cs.
        {
            if (!base.IsStatic)
            {
                if (obj == null)
                {
                    throw new TargetException("Non-static field requires a target");
                }
                if (!this.DeclaringType.IsAssignableFrom(obj.GetType()))
                {
                    throw new ArgumentException(string.Format("Field {0} defined on type {1} is not a field on the target object which is of type {2}.", this.Name, this.DeclaringType, obj.GetType()), "obj");
                }
            }
            if (base.IsLiteral)
            {
                throw new FieldAccessException("Cannot set a constant field");
            }
            if (binder == null)
            {
                binder = Type.DefaultBinder;
            }
            this.CheckGeneric();
            if (val != null)
            {
                val = ((RuntimeType)this.FieldType).CheckValue(val, binder, culture, invokeAttr);
            }
            RuntimeFieldInfo.SetValueInternal(this, obj, val);
        }
References System.Reflection.RuntimeFieldInfo.CheckGeneric(), System.culture, System.Reflection.RuntimeFieldInfo.DeclaringType, System.Type.DefaultBinder, System.Reflection.RuntimeFieldInfo.FieldType, System.Format, System.Type.IsAssignableFrom(), System.Reflection.RuntimeFieldInfo.Name, System.obj, and System.Reflection.RuntimeFieldInfo.SetValueInternal().
Referenced by System.Runtime.Serialization.SerializationFieldInfo.InternalSetValue(), and System.Runtime.Serialization.SerializationFieldInfo.SetValue().