Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.GetTypeInformation
GetTypeInformation()
static TypeInformation System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.GetTypeInformation (Type type) inline static package
Definition at line 222 of file BinaryFormatter.cs.
        {
            Dictionary<Type, TypeInformation> dictionary = BinaryFormatter.typeNameCache;
            TypeInformation typeInformation2;
            lock (dictionary)
            {
                TypeInformation typeInformation = null;
                if (!BinaryFormatter.typeNameCache.TryGetValue(type, out typeInformation))
                {
                    bool flag2;
                    string clrAssemblyName = FormatterServices.GetClrAssemblyName(type, out flag2);
                    typeInformation = new TypeInformation(FormatterServices.GetClrTypeFullName(type), clrAssemblyName, flag2);
                    BinaryFormatter.typeNameCache.Add(type, typeInformation);
                }
                typeInformation2 = typeInformation;
            }
            return typeInformation2;
        }
References System.dictionary, System.Runtime.Serialization.FormatterServices.GetClrAssemblyName(), System.Runtime.Serialization.FormatterServices.GetClrTypeFullName(), and System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.typeNameCache.
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectReader.CheckTypeForwardedTo(), System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSiWrite(), and System.Runtime.Serialization.Formatters.Binary.SerObjectInfoCache.SerObjectInfoCache().