Terraria Decompiled: Steamworks.SteamGameServerUtils.StartVRDashboard
StartVRDashboard()
static void Steamworks.SteamGameServerUtils.StartVRDashboard () inline static
Definition at line 202 of file SteamGameServerUtils.cs.
        {
            InteropHelp.TestIfAvailableGameServer();
            NativeMethods.ISteamUtils_StartVRDashboard(CSteamGameServerAPIContext.GetSteamUtils());
        }
References Steamworks.CSteamGameServerAPIContext.GetSteamUtils(), Steamworks.NativeMethods.ISteamUtils_StartVRDashboard(), and Steamworks.InteropHelp.TestIfAvailableGameServer().