Terraria Decompiled: Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayer
DrawPlayer()
void Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayer (Camera camera, Player drawPlayer, Vector2 position, float rotation, Vector2 rotationOrigin, float shadow = 0f, float scale = 1f) inline
Implements Terraria.Graphics.Renderers.IPlayerRenderer.
Definition at line 129 of file LegacyPlayerRenderer.cs.
        {
            if (drawPlayer.ShouldNotDraw)
            {
                return;
            }
            PlayerDrawSet playerDrawSet = default(PlayerDrawSet);
            this._drawData.Clear();
            this._dust.Clear();
            this._gore.Clear();
            playerDrawSet.BoringSetup(drawPlayer, this._drawData, this._dust, this._gore, position, shadow, rotation, rotationOrigin, this.OverrideHeldProjectile);
            LegacyPlayerRenderer.DrawPlayer_UseNormalLayers(ref playerDrawSet);
            PlayerDrawLayers.DrawPlayer_TransformDrawData(ref playerDrawSet);
            if (scale != 1f)
            {
                PlayerDrawLayers.DrawPlayer_ScaleDrawData(ref playerDrawSet, scale);
            }
            PlayerDrawLayers.DrawPlayer_RenderAllLayers(ref playerDrawSet);
            if (playerDrawSet.drawPlayer.mount.Active && playerDrawSet.drawPlayer.UsingSuperCart && this.OverrideHeldProjectile == null)
            {
                for (int i = 0; i < 1000; i++)
                {
                    if (Main.projectile[i].active && Main.projectile[i].owner == playerDrawSet.drawPlayer.whoAmI && Main.projectile[i].type == 591)
                    {
                        Main.instance.DrawProj(i);
                    }
                }
            }
        }
References Terraria.Graphics.Renderers.LegacyPlayerRenderer._drawData, Terraria.Graphics.Renderers.LegacyPlayerRenderer._dust, Terraria.Graphics.Renderers.LegacyPlayerRenderer._gore, Terraria.Mount.Active, Terraria.Projectile.active, Terraria.DataStructures.PlayerDrawSet.BoringSetup(), System.Collections.Generic.List< T >.Clear(), Terraria.DataStructures.PlayerDrawSet.drawPlayer, Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_RenderAllLayers(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_ScaleDrawData(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_TransformDrawData(), Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayer_UseNormalLayers(), Terraria.Main.DrawProj(), Terraria.Main.instance, Terraria.Player.mount, Terraria.Graphics.Renderers.LegacyPlayerRenderer.OverrideHeldProjectile, Terraria.Projectile.owner, Terraria.Main.projectile, Terraria.Player.ShouldNotDraw, Terraria.Projectile.type, Terraria.Player.UsingSuperCart, and Terraria.Entity.whoAmI.
Referenced by Terraria.GameContent.Tile_Entities.TEDisplayDoll.Draw(), and Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayerFull().