Terraria Decompiled: Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayerHead
DrawPlayerHead()
void Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayerHead (Camera camera, Player drawPlayer, Vector2 position, float alpha = 1f, float scale = 1f, Color borderColor = default(Color)) inline
Implements Terraria.Graphics.Renderers.IPlayerRenderer.
Definition at line 38 of file LegacyPlayerRenderer.cs.
        {
            if (drawPlayer.ShouldNotDraw)
            {
                return;
            }
            this._drawData.Clear();
            this._dust.Clear();
            this._gore.Clear();
            PlayerDrawHeadSet playerDrawHeadSet = default(PlayerDrawHeadSet);
            playerDrawHeadSet.BoringSetup(drawPlayer, this._drawData, this._dust, this._gore, position.X, position.Y, alpha, scale);
            PlayerDrawHeadLayers.DrawPlayer_00_BackHelmet(ref playerDrawHeadSet);
            PlayerDrawHeadLayers.DrawPlayer_01_FaceSkin(ref playerDrawHeadSet);
            PlayerDrawHeadLayers.DrawPlayer_02_DrawArmorWithFullHair(ref playerDrawHeadSet);
            PlayerDrawHeadLayers.DrawPlayer_03_HelmetHair(ref playerDrawHeadSet);
            PlayerDrawHeadLayers.DrawPlayer_04_HatsWithFullHair(ref playerDrawHeadSet);
            PlayerDrawHeadLayers.DrawPlayer_05_TallHats(ref playerDrawHeadSet);
            PlayerDrawHeadLayers.DrawPlayer_06_NormalHats(ref playerDrawHeadSet);
            PlayerDrawHeadLayers.DrawPlayer_07_JustHair(ref playerDrawHeadSet);
            PlayerDrawHeadLayers.DrawPlayer_08_FaceAcc(ref playerDrawHeadSet);
            this.CreateOutlines(alpha, scale, borderColor);
            PlayerDrawHeadLayers.DrawPlayer_RenderAllLayers(ref playerDrawHeadSet);
        }
References Terraria.Graphics.Renderers.LegacyPlayerRenderer._drawData, Terraria.Graphics.Renderers.LegacyPlayerRenderer._dust, Terraria.Graphics.Renderers.LegacyPlayerRenderer._gore, Terraria.DataStructures.PlayerDrawHeadSet.BoringSetup(), System.Collections.Generic.List< T >.Clear(), Terraria.Graphics.Renderers.LegacyPlayerRenderer.CreateOutlines(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_00_BackHelmet(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_01_FaceSkin(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_02_DrawArmorWithFullHair(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_03_HelmetHair(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_04_HatsWithFullHair(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_05_TallHats(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_06_NormalHats(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_07_JustHair(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_08_FaceAcc(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_RenderAllLayers(), Terraria.Player.ShouldNotDraw, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.