Terraria Decompiled: Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayerStoned
DrawPlayerStoned()
void Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayerStoned (Camera camera, Player drawPlayer, Vector2 position) inline private
Definition at line 505 of file LegacyPlayerRenderer.cs.
        {
            if (drawPlayer.dead)
            {
                return;
            }
            SpriteEffects spriteEffects;
            if (drawPlayer.direction == 1)
            {
                spriteEffects = SpriteEffects.None;
            }
            else
            {
                spriteEffects = SpriteEffects.FlipHorizontally;
            }
            camera.SpriteBatch.Draw(TextureAssets.Extra[37].Value, new Vector2((float)((int)(position.X - camera.UnscaledPosition.X - (float)(drawPlayer.bodyFrame.Width / 2) + (float)(drawPlayer.width / 2))), (float)((int)(position.Y - camera.UnscaledPosition.Y + (float)drawPlayer.height - (float)drawPlayer.bodyFrame.Height + 8f))) + drawPlayer.bodyPosition + new Vector2((float)(drawPlayer.bodyFrame.Width / 2), (float)(drawPlayer.bodyFrame.Height / 2)), null, Lighting.GetColor((int)((double)position.X + (double)drawPlayer.width * 0.5) / 16, (int)((double)position.Y + (double)drawPlayer.height * 0.5) / 16, Color.White), 0f, new Vector2((float)(TextureAssets.Extra[37].Width() / 2), (float)(TextureAssets.Extra[37].Height() / 2)), 1f, spriteEffects, 0f);
        }
References Terraria.Player.bodyFrame, Terraria.Player.bodyPosition, Terraria.Player.dead, Terraria.Entity.direction, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.GameContent.TextureAssets.Extra, Terraria.Lighting.GetColor(), Microsoft.Xna.Framework.Rectangle.Height, Terraria.Entity.height, Terraria.Graphics.Camera.SpriteBatch, Terraria.Graphics.Camera.UnscaledPosition, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Rectangle.Width, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayerFull().