Terraria Decompiled: FullSerializer.Internal.fsPortableReflection.GetAttribute
GetAttribute()
static Attribute FullSerializer.Internal.fsPortableReflection.GetAttribute (MemberInfo element, Type attributeType, bool shouldCache) inline static
Definition at line 28 of file fsPortableReflection.cs.
        {
            fsPortableReflection.AttributeQuery attributeQuery = new fsPortableReflection.AttributeQuery
            {
                MemberInfo = element,
                AttributeType = attributeType
            };
            Attribute attribute;
            if (!fsPortableReflection._cachedAttributeQueries.TryGetValue(attributeQuery, ref attribute))
            {
                attribute = (Attribute)Enumerable.FirstOrDefault<object>(element.GetCustomAttributes(attributeType, true));
                if (shouldCache)
                {
                    fsPortableReflection._cachedAttributeQueries[attributeQuery] = attribute;
                }
            }
            return attribute;
        }
References FullSerializer.Internal.fsPortableReflection._cachedAttributeQueries, and System.Reflection.MemberInfo.GetCustomAttributes().
Referenced by FullSerializer.fsMetaType.CollectProperties(), FullSerializer.Internal.fsMetaProperty.CommonInitialize(), FullSerializer.Internal.fsPortableReflection.GetAttribute< TAttribute >(), FullSerializer.Internal.fsPortableReflection.GetAttribute< TAttribute >(), FullSerializer.fsSerializer.GetConverter(), FullSerializer.fsSerializer.GetProcessors(), FullSerializer.Internal.fsVersionManager.GetVersionedType(), FullSerializer.Internal.fsPortableReflection.HasAttribute(), and FullSerializer.Internal.fsEnumConverter.TrySerialize().