Terraria Decompiled: System.RuntimeMethodHandle.ConstructInstantiation
ConstructInstantiation()
static string System.RuntimeMethodHandle.ConstructInstantiation (RuntimeMethodInfo method, TypeNameFormatFlags format) inline static package
Definition at line 104 of file RuntimeMethodHandle.cs.
        {
            StringBuilder stringBuilder = new StringBuilder();
            Type[] genericArguments = method.GetGenericArguments();
            stringBuilder.Append("[");
            for (int i = 0; i < genericArguments.Length; i++)
            {
                if (i > 0)
                {
                    stringBuilder.Append(",");
                }
                stringBuilder.Append(genericArguments[i].Name);
            }
            stringBuilder.Append("]");
            return stringBuilder.ToString();
        }
References System.Text.StringBuilder.Append(), System.Reflection.RuntimeMethodInfo.GetGenericArguments(), System.Name, and System.Text.StringBuilder.ToString().
Referenced by System.Reflection.RuntimeMethodInfo.FormatNameAndSig().