Terraria Decompiled: Terraria.GameContent.LeashedEntities.FairyLeashedCritter.VisualEffects
VisualEffects()
override void Terraria.GameContent.LeashedEntities.FairyLeashedCritter.VisualEffects () inline protected virtual
Reimplemented from Terraria.GameContent.LeashedEntities.LeashedCritter.
Definition at line 21 of file FairyLeashedCritter.cs.
        {
            base.VisualEffects();
            Color color = Color.HotPink;
            Color color2 = Color.LightPink;
            int num = 4;
            if (this.npcType == 584)
            {
                color = Color.LimeGreen;
                color2 = Color.LightSeaGreen;
            }
            if (this.npcType == 585)
            {
                color = Color.RoyalBlue;
                color2 = Color.LightBlue;
            }
            if ((int)Main.timeForVisualEffects % 4 == 0 && Main.rand.Next(4) != 0)
            {
                this.position += this.netOffset;
                Dust dust = Dust.NewDustDirect(base.Center - new Vector2(4f) + Main.rand.NextVector2Circular(2f, 2f), num, num, 278, 0f, 0f, 200, Color.Lerp(color, color2, Main.rand.NextFloat()), 0.65f);
                dust.velocity *= 0f;
                dust.velocity += this.velocity * 0.3f;
                dust.noGravity = true;
                dust.noLight = true;
                this.position -= this.netOffset;
            }
            Lighting.AddLight(base.Center, color.ToVector3() * 0.7f);
        }
References Terraria.Lighting.AddLight(), Microsoft.Xna.Framework.Color.HotPink, Microsoft.Xna.Framework.Color.Lerp(), Microsoft.Xna.Framework.Color.LightBlue, Microsoft.Xna.Framework.Color.LightPink, Microsoft.Xna.Framework.Color.LightSeaGreen, Microsoft.Xna.Framework.Color.LimeGreen, Terraria.GameContent.LeashedEntities.LeashedCritter.netOffset, Terraria.Dust.NewDustDirect(), Terraria.GameContent.LeashedEntities.LeashedCritter.npcType, Terraria.Main.rand, Microsoft.Xna.Framework.Color.RoyalBlue, Terraria.Main.timeForVisualEffects, and Microsoft.Xna.Framework.Color.ToVector3().