Terraria Decompiled: Microsoft.Xna.Framework.Media.VideoPlayerTheora.InitializeTheoraStream
InitializeTheoraStream()
void Microsoft.Xna.Framework.Media.VideoPlayerTheora.InitializeTheoraStream () inline private
Definition at line 417 of file VideoPlayerTheora.cs.
        {
            while (Theorafile.tf_readvideo(this.theora, this.yuvData, 1) == 0)
            {
            }
            if (Theorafile.tf_hasaudio(this.theora) == 1)
            {
                int num;
                int num2;
                Theorafile.tf_audioinfo(this.theora, out num, out num2);
                this.audioStream = new DynamicSoundEffectInstance(num2, (AudioChannels)num);
                this.audioStream.BufferNeeded += this.OnBufferRequest;
                this.UpdateVolume();
                for (int i = 0; i < 4; i++)
                {
                    this.OnBufferRequest(this.audioStream, EventArgs.Empty);
                    if (this.audioStream.PendingBufferCount == i)
                    {
                        break;
                    }
                }
            }
            this.currentFrame = -1;
        }
References Microsoft.Xna.Framework.Media.VideoPlayerTheora.audioStream, System.EventArgs.Empty, Microsoft.Xna.Framework.Media.VideoPlayerTheora.OnBufferRequest(), Microsoft.Xna.Framework.Audio.DynamicSoundEffectInstance.PendingBufferCount, Theorafile.tf_audioinfo(), Theorafile.tf_hasaudio(), Theorafile.tf_readvideo(), Microsoft.Xna.Framework.Media.VideoPlayerTheora.theora, and Microsoft.Xna.Framework.Media.VideoPlayerTheora.UpdateVolume().
Referenced by Microsoft.Xna.Framework.Media.VideoPlayerTheora.GetTexture(), and Microsoft.Xna.Framework.Media.VideoPlayerTheora.Play().