Terraria Decompiled: Microsoft.Xna.Framework.Media.VideoPlayerTheora.Play
Play()
void Microsoft.Xna.Framework.Media.VideoPlayerTheora.Play (Video video) inline
Implements Microsoft.Xna.Framework.Media.IVideoPlayerCodec.
Definition at line 227 of file VideoPlayerTheora.cs.
        {
            base.checkDisposed();
            this.Video = video;
            this.Video.parent = this;
            if (this.theora != IntPtr.Zero)
            {
                Theorafile.tf_close(ref this.theora);
                this.theora = IntPtr.Zero;
            }
            if (this.Video.needsDurationHack)
            {
                this.Video.Duration = TimeSpan.MaxValue;
            }
            Theorafile.tf_fopen(this.Video.handle, out this.theora);
            if (this.theora == IntPtr.Zero)
            {
                throw new FileNotFoundException(this.Video.handle);
            }
            int num;
            int num2;
            Theorafile.th_pixel_fmt th_pixel_fmt;
            Theorafile.tf_videoinfo(this.theora, out num, out num2, out this.fps, out th_pixel_fmt);
            int num3;
            int num4;
            if (th_pixel_fmt == Theorafile.th_pixel_fmt.TH_PF_420)
            {
                num3 = num / 2;
                num4 = num2 / 2;
            }
            else if (th_pixel_fmt == Theorafile.th_pixel_fmt.TH_PF_422)
            {
                num3 = num / 2;
                num4 = num2;
            }
            else
            {
                if (th_pixel_fmt != Theorafile.th_pixel_fmt.TH_PF_444)
                {
                    throw new NotSupportedException("Unrecognized YUV format!");
                }
                num3 = num;
                num4 = num2;
            }
            if (this.Video.Width != num || this.Video.Height != num2)
            {
                throw new InvalidOperationException("XNB/OGV width/height mismatch! Width: " + this.Video.Width.ToString() + " Height: " + this.Video.Height.ToString());
            }
            if (Math.Abs((double)this.Video.FramesPerSecond - this.fps) >= 1.0)
            {
                throw new InvalidOperationException("XNB/OGV framesPerSecond mismatch! FPS: " + this.Video.FramesPerSecond.ToString());
            }
            if (this.Video.audioTrack >= 0)
            {
                this.SetAudioTrackEXT(this.Video.audioTrack);
            }
            if (this.Video.videoTrack >= 0)
            {
                this.SetVideoTrackEXT(this.Video.videoTrack);
            }
            if (this.State != MediaState.Stopped)
            {
                return;
            }
            this.State = MediaState.Playing;
            if (this.yuvData != IntPtr.Zero)
            {
                FNAPlatform.Free(this.yuvData);
            }
            this.yuvDataLen = num * num2 + num3 * num4 * 2;
            this.yuvData = FNAPlatform.Malloc(this.yuvDataLen);
            this.InitializeTheoraStream();
            if (Theorafile.tf_hasvideo(this.theora) == 1)
            {
                if (this.currentDevice != this.Video.GraphicsDevice)
                {
                    base.GL_dispose();
                    this.currentDevice = this.Video.GraphicsDevice;
                    base.GL_initialize(Resources.YUVToRGBAEffect);
                }
                RenderTargetBinding renderTargetBinding = this.videoTexture[0];
                this.videoTexture[0] = new RenderTargetBinding(new RenderTarget2D(this.currentDevice, num, num2, false, SurfaceFormat.Color, DepthFormat.None, 0, RenderTargetUsage.PreserveContents));
                if (renderTargetBinding.RenderTarget != null)
                {
                    renderTargetBinding.RenderTarget.Dispose();
                }
                base.GL_setupTextures(num, num2, num3, num4, SurfaceFormat.Alpha8);
            }
            this.timer.Start();
            if (this.audioStream != null)
            {
                this.audioStream.Play();
            }
        }
References System.Math.Abs(), Microsoft.Xna.Framework.Media.VideoPlayerTheora.audioStream, Microsoft.Xna.Framework.Media.Video.audioTrack, Microsoft.Xna.Framework.Media.BaseYUVPlayer.currentDevice, Microsoft.Xna.Framework.Graphics.Texture.Dispose(), Microsoft.Xna.Framework.Media.VideoPlayerTheora.fps, Microsoft.Xna.Framework.Media.Video.FramesPerSecond, Microsoft.Xna.Framework.FNAPlatform.Free, Microsoft.Xna.Framework.Media.Video.GraphicsDevice, Microsoft.Xna.Framework.Media.Video.handle, Microsoft.Xna.Framework.Media.VideoPlayerTheora.InitializeTheoraStream(), Microsoft.Xna.Framework.FNAPlatform.Malloc, System.TimeSpan.MaxValue, Microsoft.Xna.Framework.Media.Video.needsDurationHack, Microsoft.Xna.Framework.Audio.DynamicSoundEffectInstance.Play(), Microsoft.Xna.Framework.Graphics.RenderTargetBinding.RenderTarget, Microsoft.Xna.Framework.Media.VideoPlayerTheora.SetAudioTrackEXT(), Microsoft.Xna.Framework.Media.VideoPlayerTheora.SetVideoTrackEXT(), Microsoft.Xna.Framework.Media.VideoPlayerTheora.State, Theorafile.tf_close(), Theorafile.tf_fopen(), Theorafile.tf_hasvideo(), Theorafile.tf_videoinfo(), Microsoft.Xna.Framework.Media.VideoPlayerTheora.theora, Microsoft.Xna.Framework.Media.VideoPlayerTheora.timer, Microsoft.Xna.Framework.Media.BaseYUVPlayer.videoTexture, Microsoft.Xna.Framework.Media.Video.videoTrack, Microsoft.Xna.Framework.Media.Video.Width, Microsoft.Xna.Framework.Media.VideoPlayerTheora.yuvData, Microsoft.Xna.Framework.Media.VideoPlayerTheora.yuvDataLen, Microsoft.Xna.Framework.Graphics.Resources.YUVToRGBAEffect, and System.IntPtr.Zero.