Terraria Decompiled: Microsoft.Xna.Framework.Media.VideoPlayerTheora.Stop
Stop()
void Microsoft.Xna.Framework.Media.VideoPlayerTheora.Stop () inline
Implements Microsoft.Xna.Framework.Media.IVideoPlayerCodec.
Definition at line 323 of file VideoPlayerTheora.cs.
        {
            base.checkDisposed();
            if (this.State == MediaState.Stopped)
            {
                return;
            }
            this.State = MediaState.Stopped;
            this.timer.Stop();
            this.timer.Reset();
            if (this.audioStream != null)
            {
                this.audioStream.Stop();
                this.audioStream.Dispose();
                this.audioStream = null;
            }
            Theorafile.tf_reset(this.theora);
        }
References Microsoft.Xna.Framework.Media.VideoPlayerTheora.audioStream, Microsoft.Xna.Framework.Audio.DynamicSoundEffectInstance.Dispose(), Microsoft.Xna.Framework.Media.VideoPlayerTheora.State, Microsoft.Xna.Framework.Audio.SoundEffectInstance.Stop(), Theorafile.tf_reset(), Microsoft.Xna.Framework.Media.VideoPlayerTheora.theora, and Microsoft.Xna.Framework.Media.VideoPlayerTheora.timer.
Referenced by Microsoft.Xna.Framework.Media.VideoPlayerTheora.Dispose().