Terraria Decompiled: Microsoft.Xna.Framework.Media.VideoPlayerTheora.ReadInfo
ReadInfo()
static VideoPlayer.VideoInfo Microsoft.Xna.Framework.Media.VideoPlayerTheora.ReadInfo (string fileName) inline static package
Definition at line 443 of file VideoPlayerTheora.cs.
        {
            IntPtr intPtr;
            Theorafile.tf_fopen(fileName, out intPtr);
            int num;
            int num2;
            double num3;
            Theorafile.th_pixel_fmt th_pixel_fmt;
            Theorafile.tf_videoinfo(intPtr, out num, out num2, out num3, out th_pixel_fmt);
            Theorafile.tf_close(ref intPtr);
            return new VideoPlayer.VideoInfo
            {
                fps = num3,
                width = num,
                height = num2
            };
        }
References Microsoft.Xna.Framework.Media.VideoPlayerTheora.fps, Theorafile.tf_close(), Theorafile.tf_fopen(), and Theorafile.tf_videoinfo().