Terraria Decompiled: Microsoft.Xna.Framework.Media.VideoPlayerTheora.Dispose
Dispose()
override void Microsoft.Xna.Framework.Media.VideoPlayerTheora.Dispose () inline virtual
Reimplemented from Microsoft.Xna.Framework.Media.BaseYUVPlayer.
Definition at line 144 of file VideoPlayerTheora.cs.
        {
            if (base.IsDisposed)
            {
                return;
            }
            this.Stop();
            base.Dispose();
            if (this.audioStream != null)
            {
                this.audioStream.Dispose();
                this.audioStream = null;
            }
            if (this.yuvData != IntPtr.Zero)
            {
                FNAPlatform.Free(this.yuvData);
                this.yuvData = IntPtr.Zero;
            }
            if (this.theora != IntPtr.Zero)
            {
                Theorafile.tf_close(ref this.theora);
            }
        }
References Microsoft.Xna.Framework.Media.VideoPlayerTheora.audioStream, Microsoft.Xna.Framework.Audio.DynamicSoundEffectInstance.Dispose(), Microsoft.Xna.Framework.FNAPlatform.Free, Microsoft.Xna.Framework.Media.VideoPlayerTheora.Stop(), Theorafile.tf_close(), Microsoft.Xna.Framework.Media.VideoPlayerTheora.theora, Microsoft.Xna.Framework.Media.VideoPlayerTheora.yuvData, and System.IntPtr.Zero.