Terraria Decompiled: Microsoft.Xna.Framework.Media.VideoPlayerTheora.UpdateTexture
UpdateTexture()
void Microsoft.Xna.Framework.Media.VideoPlayerTheora.UpdateTexture () inline private
Definition at line 408 of file VideoPlayerTheora.cs.
        {
            FNA3D.FNA3D_SetTextureDataYUV(this.currentDevice.GLDevice, this.yuvTextures[0].texture, this.yuvTextures[1].texture, this.yuvTextures[2].texture, this.yuvTextures[0].Width, this.yuvTextures[0].Height, this.yuvTextures[1].Width, this.yuvTextures[1].Height, this.yuvData, this.yuvDataLen);
            base.GL_pushState();
            this.currentDevice.DrawPrimitives(PrimitiveType.TriangleStrip, 0, 2);
            base.GL_popState();
        }
References Microsoft.Xna.Framework.Media.BaseYUVPlayer.currentDevice, Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawPrimitives(), Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_SetTextureDataYUV(), and Microsoft.Xna.Framework.Graphics.GraphicsDevice.GLDevice.
Referenced by Microsoft.Xna.Framework.Media.VideoPlayerTheora.GetTexture().