Terraria Decompiled: Microsoft.Xna.Framework.Media.VideoPlayerTheora.OnBufferRequest
OnBufferRequest()
void Microsoft.Xna.Framework.Media.VideoPlayerTheora.OnBufferRequest (object sender, EventArgs args) inline private
Definition at line 393 of file VideoPlayerTheora.cs.
        {
            int num = Theorafile.tf_readaudio(this.theora, this.audioDataPtr, 8192);
            if (num > 0)
            {
                this.audioStream.SubmitFloatBufferEXT(VideoPlayerTheora.audioData, 0, num);
                return;
            }
            if (Theorafile.tf_eos(this.theora) == 1)
            {
                this.audioStream.BufferNeeded -= this.OnBufferRequest;
            }
        }
References Microsoft.Xna.Framework.Media.VideoPlayerTheora.audioData, Microsoft.Xna.Framework.Media.VideoPlayerTheora.audioDataPtr, Microsoft.Xna.Framework.Media.VideoPlayerTheora.audioStream, Microsoft.Xna.Framework.Media.VideoPlayerTheora.OnBufferRequest(), Microsoft.Xna.Framework.Audio.DynamicSoundEffectInstance.SubmitFloatBufferEXT(), Theorafile.tf_eos(), Theorafile.tf_readaudio(), and Microsoft.Xna.Framework.Media.VideoPlayerTheora.theora.
Referenced by Microsoft.Xna.Framework.Media.VideoPlayerTheora.InitializeTheoraStream(), and Microsoft.Xna.Framework.Media.VideoPlayerTheora.OnBufferRequest().