Terraria Decompiled: Microsoft.Xna.Framework.Media.VideoPlayerTheora.GetTexture
GetTexture()
Texture2D Microsoft.Xna.Framework.Media.VideoPlayerTheora.GetTexture () inline
Implements Microsoft.Xna.Framework.Media.IVideoPlayerCodec.
Definition at line 169 of file VideoPlayerTheora.cs.
        {
            base.checkDisposed();
            if (this.Video == null)
            {
                throw new InvalidOperationException();
            }
            if (this.State == MediaState.Stopped || this.theora == IntPtr.Zero || Theorafile.tf_hasvideo(this.theora) == 0)
            {
                return this.videoTexture[0].RenderTarget as Texture2D;
            }
            int num = (int)(this.timer.Elapsed.TotalMilliseconds / (1000.0 / this.fps));
            if (num > this.currentFrame)
            {
                if (Theorafile.tf_readvideo(this.theora, this.yuvData, num - this.currentFrame) == 1 || this.currentFrame == -1)
                {
                    this.UpdateTexture();
                }
                this.currentFrame = num;
            }
            bool flag = Theorafile.tf_eos(this.theora) == 1;
            if (this.audioStream != null)
            {
                flag &= this.audioStream.PendingBufferCount == 0;
            }
            if (flag)
            {
                if (this.Video.needsDurationHack)
                {
                    this.Video.Duration = this.timer.Elapsed;
                }
                this.timer.Stop();
                this.timer.Reset();
                if (this.audioStream != null)
                {
                    this.audioStream.Stop();
                    this.audioStream.Dispose();
                    this.audioStream = null;
                }
                Theorafile.tf_reset(this.theora);
                if (this.IsLooped)
                {
                    this.InitializeTheoraStream();
                    this.timer.Start();
                    if (this.audioStream != null)
                    {
                        this.audioStream.Play();
                    }
                }
                else
                {
                    this.State = MediaState.Stopped;
                }
            }
            return this.videoTexture[0].RenderTarget as Texture2D;
        }
References Microsoft.Xna.Framework.Media.VideoPlayerTheora.audioStream, Microsoft.Xna.Framework.Media.VideoPlayerTheora.currentFrame, Microsoft.Xna.Framework.Audio.DynamicSoundEffectInstance.Dispose(), Microsoft.Xna.Framework.Media.VideoPlayerTheora.InitializeTheoraStream(), int, Microsoft.Xna.Framework.Media.VideoPlayerTheora.IsLooped, Microsoft.Xna.Framework.Media.Video.needsDurationHack, Microsoft.Xna.Framework.Audio.DynamicSoundEffectInstance.Play(), Microsoft.Xna.Framework.Graphics.RenderTargetBinding.RenderTarget, Microsoft.Xna.Framework.Media.VideoPlayerTheora.State, Microsoft.Xna.Framework.Audio.SoundEffectInstance.Stop(), Microsoft.Xna.Framework.Graphics.Texture2D, Theorafile.tf_eos(), Theorafile.tf_hasvideo(), Theorafile.tf_readvideo(), Theorafile.tf_reset(), Microsoft.Xna.Framework.Media.VideoPlayerTheora.theora, Microsoft.Xna.Framework.Media.VideoPlayerTheora.timer, Microsoft.Xna.Framework.Media.VideoPlayerTheora.UpdateTexture(), Microsoft.Xna.Framework.Media.BaseYUVPlayer.videoTexture, and System.IntPtr.Zero.