Terraria Decompiled: Terraria.GameContent.TeleportHelpers.RequestMagicConchTeleportPosition
RequestMagicConchTeleportPosition()
static bool Terraria.GameContent.TeleportHelpers.RequestMagicConchTeleportPosition (Player player, int crawlOffsetX, bool rightOcean, out Point landingPoint) inline static
Definition at line 52 of file TeleportHelpers.cs.
        {
            landingPoint = default(Point);
            int num = 50;
            int num2 = 50;
            int num3 = 0;
            if (WorldGen.Skyblock.lowTiles)
            {
                num2 = 100;
                num3 = 50;
            }
            int num4 = (rightOcean ? (Main.maxTilesX - num) : num);
            int num5 = num2;
            int num6 = (int)Main.worldSurface - num3;
            Point point = new Point(num4, num5);
            int num7 = 1;
            int num8 = -1;
            int num9 = 1;
            int num10 = 0;
            int num11 = 5000;
            Vector2 vector = new Vector2((float)player.width * 0.5f, (float)player.height);
            int num12 = 40;
            bool flag = WorldGen.SolidOrSlopedTile(Main.tile[point.X, point.Y]);
            int num13 = 0;
            int num14 = 400;
            if (WorldGen.Skyblock.lowTiles)
            {
                num11 = num14 * ((int)Main.worldSurface - 10);
            }
            while (num10 < num11 && num13 < num14)
            {
                num10++;
                Tile tile = Main.tile[point.X, point.Y];
                Tile tile2 = Main.tile[point.X, point.Y + num9];
                bool flag2 = WorldGen.SolidOrSlopedTile(tile) || tile.liquid > 0;
                bool flag3 = WorldGen.SolidOrSlopedTile(tile2) || tile2.liquid > 0;
                if (TeleportHelpers.IsInSolidTilesExtended(new Vector2((float)(point.X * 16 + 8), (float)(point.Y * 16 + 15)) - vector, player.velocity, player.width, player.height, (int)player.gravDir))
                {
                    if (flag)
                    {
                        point.Y += num7;
                    }
                    else
                    {
                        point.Y += num8;
                    }
                }
                else if (flag2)
                {
                    if (flag)
                    {
                        point.Y += num7;
                    }
                    else
                    {
                        point.Y += num8;
                    }
                }
                else
                {
                    flag = false;
                    if (!TeleportHelpers.IsInSolidTilesExtended(new Vector2((float)(point.X * 16 + 8), (float)(point.Y * 16 + 15 + 16)) - vector, player.velocity, player.width, player.height, (int)player.gravDir) && !flag3 && (double)point.Y < Main.worldSurface)
                    {
                        point.Y += num7;
                        if (WorldGen.Skyblock.lowTiles && point.Y >= num6)
{
                            point.Y = num5;
                            point.X += crawlOffsetX;
                            num13++;
                        }
                    }
                    else if (tile2.liquid > 0)
                    {
                        point.X += crawlOffsetX;
                        num13++;
                    }
                    else if (TeleportHelpers.TileIsDangerous(point.X, point.Y))
                    {
                        point.X += crawlOffsetX;
                        num13++;
                    }
                    else if (TeleportHelpers.TileIsDangerous(point.X, point.Y + num9))
                    {
                        point.X += crawlOffsetX;
                        num13++;
                    }
                    else
                    {
                        if (point.Y >= num12)
{
                            break;
                        }
                        point.Y += num7;
                    }
                }
            }
            if (num10 == num11 || num13 >= num14)
            {
                return false;
            }
            if (!WorldGen.InWorld(point.X, point.Y, 40))
            {
                return false;
            }
            bool flag4 = false;
            for (int i = 0; i < 10; i++)
            {
                int num15 = point.Y + i;
                Tile tile3 = Main.tile[point.X, num15];
                if (WorldGen.SolidOrSlopedTile(tile3) || tile3.liquid > 0)
                {
                    flag4 = true;
                    break;
                }
            }
            if (WorldGen.Skyblock.lowTiles)
            {
                if (!flag4)
                {
                    for (int j = 0; j < 10; j++)
                    {
                        int num16 = point.Y + j;
                        Tile tile4 = Main.tile[point.X - 1, num16];
                        if (WorldGen.SolidOrSlopedTile(tile4) || tile4.liquid > 0)
{
                            point.X--;
                            flag4 = true;
                            break;
                        }
                    }
                }
                if (!flag4)
                {
                    for (int k = 0; k < 10; k++)
                    {
                        int num17 = point.Y + k;
                        Tile tile5 = Main.tile[point.X + 1, num17];
                        if (WorldGen.SolidOrSlopedTile(tile5) || tile5.liquid > 0)
{
                            point.X++;
                            flag4 = true;
                            break;
                        }
                    }
                }
            }
            if (!flag4)
            {
                return false;
            }
            landingPoint = point;
            return true;
        }
References Terraria.Player.gravDir, Terraria.Entity.height, int, Terraria.WorldGen.InWorld(), Terraria.GameContent.TeleportHelpers.IsInSolidTilesExtended(), Terraria.Tile.liquid, Terraria.WorldGen.Skyblock.lowTiles, Terraria.WorldGen.SolidOrSlopedTile(), Terraria.Main.tile, Terraria.GameContent.TeleportHelpers.TileIsDangerous(), Terraria.Entity.velocity, Terraria.Entity.width, Terraria.Main.worldSurface, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.Player.MagicConch().