Terraria Decompiled: Terraria.GameContent.TeleportHelpers.FindClosestTeleportSpotNoSpace
FindClosestTeleportSpotNoSpace()
static bool Terraria.GameContent.TeleportHelpers.FindClosestTeleportSpotNoSpace (Player player, out Vector2 resultPosition) inline static
Definition at line 10 of file TeleportHelpers.cs.
        {
            bool flag = false;
            resultPosition = player.position;
            player.velocity = Vector2.Zero;
            Vector2 vector = new Vector2((float)player.width * 0.5f, (float)player.height);
            Vector2 bottom = player.Bottom;
            Point point = bottom.ToTileCoordinates();
            int num = point.X - 25;
            int num2 = point.X + 25;
            int num3 = point.Y - 25;
            int num4 = point.Y + 25;
            num = Utils.Clamp<int>(num, 40, Main.maxTilesX - 40);
            num2 = Utils.Clamp<int>(num2, 40, Main.maxTilesX - 40);
            num3 = Utils.Clamp<int>(num3, 40, Main.maxTilesY - 40);
            num4 = Utils.Clamp<int>(num4, 40, Main.maxTilesY - 40);
            float num5 = float.MaxValue;
            for (int i = num; i < num2; i++)
            {
                for (int j = num3; j < num4; j++)
                {
                    Vector2 vector2 = new Vector2((float)(i * 16 + 8), (float)(j * 16 + 15)) - vector;
                    Tile tile = Main.tile[i, j];
                    Tile tile2 = Main.tile[i, j + 1];
                    bool flag2 = WorldGen.SolidOrSlopedTile(tile) || tile.liquid > 0;
                    bool flag3 = WorldGen.SolidOrSlopedTile(tile2) && tile2.liquid == 0;
                    if (!TeleportHelpers.TileIsDangerous(i, j) && !flag2 && flag3 && !Collision.LavaCollision(vector2, player.width, player.height) && !Collision.AnyHurtingTiles(vector2, player.width, player.height) && !Collision.SolidCollision(vector2, player.width, player.height))
                    {
                        float num6 = (vector2 - bottom).Length();
                        if (num6 < num5)
{
                            resultPosition = vector2;
                            num5 = num6;
                            flag = true;
                        }
                    }
                }
            }
            return flag;
        }
References Terraria.Collision.AnyHurtingTiles(), Terraria.Entity.Bottom, Terraria.Utils.Clamp(), Terraria.Entity.height, Terraria.Collision.LavaCollision(), Terraria.Entity.position, Terraria.Collision.SolidCollision(), Terraria.WorldGen.SolidOrSlopedTile(), Terraria.Main.tile, Terraria.GameContent.TeleportHelpers.TileIsDangerous(), Terraria.Entity.width, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.Player.PlayerNoSpaceTeleport().