Terraria Decompiled: NVorbis.Ogg.ForwardOnlyPacketProvider.ReadNextPage
ReadNextPage()
bool NVorbis.Ogg.ForwardOnlyPacketProvider.ReadNextPage (out byte[] pageBuf, out bool isResync, out int dataStart, out int packetIndex, out bool isContinuation, out bool isContinued) inline private
Definition at line 214 of file ForwardOnlyPacketProvider.cs.
        {
            while (this._pageQueue.Count == 0)
            {
                if (this._isEndOfStream || !this._reader.ReadNextPage())
                {
                    pageBuf = null;
                    isResync = false;
                    dataStart = 0;
                    packetIndex = 0;
                    isContinuation = false;
                    isContinued = false;
                    return false;
                }
            }
            ValueTuple<byte[], bool> valueTuple = this._pageQueue.Dequeue();
            pageBuf = valueTuple.Item1;
            isResync = valueTuple.Item2;
            dataStart = (int)(pageBuf[26] + 27);
            packetIndex = 27;
            isContinuation = (pageBuf[5] & 1) > 0;
            isContinued = pageBuf[(int)(26 + pageBuf[26])] == byte.MaxValue;
            return true;
        }
References NVorbis.Ogg.ForwardOnlyPacketProvider._isEndOfStream, NVorbis.Ogg.ForwardOnlyPacketProvider._pageQueue, NVorbis.Ogg.ForwardOnlyPacketProvider._reader, System.Collections.Generic.Queue< T >.Count, System.Collections.Generic.Queue< T >.Dequeue(), int, System.ValueTuple< T1, T2, T3, T4, T5, T6, T7, TRest >.Item1, System.ValueTuple< T1, T2, T3, T4, T5, T6, T7, TRest >.Item2, and NVorbis.Contracts.Ogg.IPageReader.ReadNextPage().
Referenced by NVorbis.Ogg.ForwardOnlyPacketProvider.GetPacket().