Terraria Decompiled: NVorbis.Ogg.ForwardOnlyPacketProvider.GetPacket
GetPacket()
bool NVorbis.Ogg.ForwardOnlyPacketProvider.GetPacket () inline private
Definition at line 124 of file ForwardOnlyPacketProvider.cs.
        {
            byte[] pageBuf;
            bool flag;
            int num;
            int packetIndex;
            bool flag2;
            bool flag3;
            if (this._pageBuf != null && this._packetIndex < (int)(27 + this._pageBuf[26]))
            {
                pageBuf = this._pageBuf;
                flag = false;
                num = this._dataStart;
                packetIndex = this._packetIndex;
                flag2 = false;
                flag3 = pageBuf[(int)(26 + pageBuf[26])] == byte.MaxValue;
            }
            else if (!this.ReadNextPage(out pageBuf, out flag, out num, out packetIndex, out flag2, out flag3))
            {
                return false;
            }
            int num2 = num;
            bool flag4 = packetIndex == 27;
            if (flag2 && flag4)
            {
                flag = true;
                num2 += this.GetPacketLength(pageBuf, ref packetIndex);
                if (packetIndex == (int)(27 + pageBuf[26]))
                {
                    return this.GetPacket();
                }
            }
            if (!flag4)
            {
                num2 = 0;
            }
            int packetLength = this.GetPacketLength(pageBuf, ref packetIndex);
            Memory<byte> memory = new Memory<byte>(pageBuf, num, packetLength);
            num += packetLength;
            bool flag5 = packetIndex == (int)(27 + pageBuf[26]);
            if (flag3)
            {
                if (flag5)
                {
                    flag5 = false;
                }
                else
                {
                    int num3 = packetIndex;
                    this.GetPacketLength(pageBuf, ref num3);
                    flag5 = num3 == (int)(27 + pageBuf[26]);
                }
            }
            bool flag6 = false;
            long? num4 = default(long?);
            if (flag5)
            {
                num4 = new long?(BitConverter.ToInt64(pageBuf, 6));
                if ((pageBuf[5] & 4) != 0 || (this._isEndOfStream && this._pageQueue.Count == 0))
                {
                    flag6 = true;
                }
            }
            else
            {
                while (flag3 && packetIndex == (int)(27 + pageBuf[26]) && (this.ReadNextPage(out pageBuf, out flag, out num, out packetIndex, out flag2, out flag3) && !flag && flag2))
                {
                    num2 += (int)(27 + pageBuf[26]);
                    Memory<byte> memory2 = memory;
                    int packetLength2 = this.GetPacketLength(pageBuf, ref packetIndex);
                    memory = new Memory<byte>(new byte[memory2.Length + packetLength2]);
                    memory2.CopyTo(memory);
                    new Memory<byte>(pageBuf, num, packetLength2).CopyTo(memory.Slice(memory2.Length));
                    num += packetLength2;
                }
            }
            base.IsResync = flag;
            base.GranulePosition = num4;
            base.IsEndOfStream = flag6;
            base.ContainerOverheadBits = num2 * 8;
            this._pageBuf = pageBuf;
            this._dataStart = num;
            this._packetIndex = packetIndex;
            this._packetBuf = memory;
            this._isEndOfStream = this._isEndOfStream || flag6;
            this.Reset();
            return true;
        }
References NVorbis.Ogg.ForwardOnlyPacketProvider._dataStart, NVorbis.Ogg.ForwardOnlyPacketProvider._packetIndex, NVorbis.Ogg.ForwardOnlyPacketProvider._pageBuf, NVorbis.Memory< T >.CopyTo(), NVorbis.Ogg.ForwardOnlyPacketProvider.GetPacket(), NVorbis.Ogg.ForwardOnlyPacketProvider.GetPacketLength(), int, NVorbis.Memory< T >.Length, NVorbis.Ogg.ForwardOnlyPacketProvider.ReadNextPage(), NVorbis.Ogg.ForwardOnlyPacketProvider.Reset(), NVorbis.Memory< T >.Slice(), and System.BitConverter.ToInt64().
Referenced by NVorbis.Ogg.ForwardOnlyPacketProvider.GetNextPacket(), NVorbis.Ogg.ForwardOnlyPacketProvider.GetPacket(), and NVorbis.Ogg.ForwardOnlyPacketProvider.PeekNextPacket().