Terraria Decompiled: Newtonsoft.Json.Converters.RegexConverter.WriteBson
WriteBson()
void Newtonsoft.Json.Converters.RegexConverter.WriteBson (BsonWriter writer, Regex regex) inline private
Definition at line 32 of file RegexConverter.cs.
        {
            string text = null;
            if (this.HasFlag(regex.Options, 1))
            {
                text += "i";
            }
            if (this.HasFlag(regex.Options, 2))
            {
                text += "m";
            }
            if (this.HasFlag(regex.Options, 16))
            {
                text += "s";
            }
            text += "u";
            if (this.HasFlag(regex.Options, 4))
            {
                text += "x";
            }
            writer.WriteRegex(regex.ToString(), text);
        }
References Newtonsoft.Json.Converters.RegexConverter.HasFlag(), System.text, and Newtonsoft.Json.Bson.BsonWriter.WriteRegex().
Referenced by Newtonsoft.Json.Converters.RegexConverter.WriteJson().