Terraria Decompiled: Newtonsoft.Json.Converters.RegexConverter.ReadRegexObject
ReadRegexObject()
Regex Newtonsoft.Json.Converters.RegexConverter.ReadRegexObject (JsonReader reader, JsonSerializer serializer) inline private
Definition at line 128 of file RegexConverter.cs.
        {
            string text = null;
            RegexOptions? regexOptions = default(RegexOptions?);
            while (reader.Read())
            {
                JsonToken tokenType = reader.TokenType;
                if (tokenType != JsonToken.PropertyName)
                {
                    if (tokenType != JsonToken.Comment)
                    {
                        if (tokenType == JsonToken.EndObject)
{
                            if (text == null)
{
                                throw JsonSerializationException.Create(reader, "Error deserializing Regex. No pattern found.");
                            }
                            return new Regex(text, regexOptions ?? 0);
                        }
                    }
                }
                else
                {
                    string text2 = reader.Value.ToString();
                    if (!reader.Read())
                    {
                        throw JsonSerializationException.Create(reader, "Unexpected end when reading Regex.");
                    }
                    if (string.Equals(text2, "Pattern", 5))
                    {
                        text = (string)reader.Value;
                    }
                    else if (string.Equals(text2, "Options", 5))
                    {
                        regexOptions = new RegexOptions?(serializer.Deserialize<RegexOptions>(reader));
                    }
                    else
                    {
                        reader.Skip();
                    }
                }
            }
            throw JsonSerializationException.Create(reader, "Unexpected end when reading Regex.");
        }
References Newtonsoft.Json.JsonSerializationException.Create(), Newtonsoft.Json.JsonSerializer.Deserialize(), Newtonsoft.Json.JsonReader.Read(), Newtonsoft.Json.Bson.Regex, Newtonsoft.Json.JsonReader.Skip(), System.text, Newtonsoft.Json.JsonReader.TokenType, and Newtonsoft.Json.JsonReader.Value.
Referenced by Newtonsoft.Json.Converters.RegexConverter.ReadJson().