Terraria Decompiled: Terraria.GameContent.LeashedEntities.EmpressButterflyLeashedCritter.VisualEffects
VisualEffects()
override void Terraria.GameContent.LeashedEntities.EmpressButterflyLeashedCritter.VisualEffects () inline protected virtual
Reimplemented from Terraria.GameContent.LeashedEntities.LeashedCritter.
Definition at line 28 of file EmpressButterflyLeashedCritter.cs.
        {
            base.VisualEffects();
            Vector3 vector = Main.hslToRgb(Main.GlobalTimeWrappedHourly * 0.33f % 1f, 1f, 0.5f, byte.MaxValue).ToVector3() * 0.3f;
            vector += Vector3.One * 0.1f;
            Lighting.AddLight(base.Center, vector);
            bool flag = Main.LocalPlayer.Center.Distance(base.Center) > 300f;
            this.fadeAmount = MathHelper.Clamp(this.fadeAmount + (float)flag.ToDirectionInt(), 0f, 50f);
            if (this.fadeAmount > 0f)
            {
                float opacity = this.Opacity;
                int num = 1;
                for (int i = 0; i < num; i++)
                {
                    if (Main.rand.Next(5) == 0)
                    {
                        float num2 = MathHelper.Lerp(0.9f, 0.6f, opacity);
                        Color color = Main.hslToRgb(Main.GlobalTimeWrappedHourly * 0.3f % 1f, 1f, 0.5f, byte.MaxValue) * 0.5f;
                        int num3 = Dust.NewDust(this.position, this.width, this.height, 267, 0f, 0f, 0, color, 1f);
                        Main.dust[num3].position = base.Center + Main.rand.NextVector2Circular((float)this.width, (float)this.height);
                        Main.dust[num3].velocity *= Main.rand.NextFloat() * 0.8f;
                        Main.dust[num3].velocity += this.velocity * 0.6f;
                        Main.dust[num3].noGravity = true;
                        Main.dust[num3].fadeIn = 0.6f + Main.rand.NextFloat() * 0.7f * num2;
                        Main.dust[num3].scale = 0.35f;
                        if (num3 != 6000)
{
                            Dust dust = Dust.CloneDust(num3);
                            dust.scale /= 2f;
                            dust.fadeIn *= 0.85f;
                            dust.color = new Color(255, 255, 255, 255) * 0.5f;
                        }
                    }
                }
            }
        }
References Terraria.Lighting.AddLight(), Terraria.Entity.Center, Microsoft.Xna.Framework.MathHelper.Clamp(), Terraria.Dust.CloneDust(), Microsoft.Xna.Framework.Vector2.Distance(), Terraria.Main.dust, Terraria.GameContent.LeashedEntities.EmpressButterflyLeashedCritter.fadeAmount, Terraria.Dust.fadeIn, Terraria.Main.GlobalTimeWrappedHourly, Terraria.GameContent.LeashedEntity.height, Terraria.Main.hslToRgb(), Microsoft.Xna.Framework.MathHelper.Lerp(), Terraria.Main.LocalPlayer, Terraria.Dust.NewDust(), Terraria.Dust.noGravity, Terraria.GameContent.LeashedEntities.EmpressButterflyLeashedCritter.Opacity, Terraria.Dust.position, Terraria.GameContent.LeashedEntity.position, Terraria.Main.rand, Terraria.Dust.scale, Terraria.Dust.velocity, and Terraria.GameContent.LeashedEntity.width.