Terraria Decompiled: System.Runtime.Serialization.FormatterConverter.ThrowValueNullException
ThrowValueNullException()
static void System.Runtime.Serialization.FormatterConverter.ThrowValueNullException () inline static private
Definition at line 186 of file FormatterConverter.cs.
        {
            throw new ArgumentNullException("value");
        }
Referenced by System.Runtime.Serialization.FormatterConverter.Convert(), System.Runtime.Serialization.FormatterConverter.Convert(), System.Runtime.Serialization.FormatterConverter.ToBoolean(), System.Runtime.Serialization.FormatterConverter.ToByte(), System.Runtime.Serialization.FormatterConverter.ToChar(), System.Runtime.Serialization.FormatterConverter.ToDateTime(), System.Runtime.Serialization.FormatterConverter.ToDecimal(), System.Runtime.Serialization.FormatterConverter.ToDouble(), System.Runtime.Serialization.FormatterConverter.ToInt16(), System.Runtime.Serialization.FormatterConverter.ToInt32(), System.Runtime.Serialization.FormatterConverter.ToInt64(), System.Runtime.Serialization.FormatterConverter.ToSByte(), System.Runtime.Serialization.FormatterConverter.ToSingle(), System.Runtime.Serialization.FormatterConverter.ToString(), System.Runtime.Serialization.FormatterConverter.ToUInt16(), System.Runtime.Serialization.FormatterConverter.ToUInt32(), and System.Runtime.Serialization.FormatterConverter.ToUInt64().