Terraria Decompiled: Terraria.WorldBuilding.WorldGenSnapshot.SnapshotGenVars.Serialize
Serialize()
static string Terraria.WorldBuilding.WorldGenSnapshot.SnapshotGenVars.Serialize () inline static
Definition at line 394 of file WorldGenSnapshot.cs.
            {
                return JsonConvert.SerializeObject(new WorldGenSnapshot.SnapshotGenVars(), WorldGenSnapshot.SnapshotGenVars.SerializerSettings);
            }
References Newtonsoft.Json.JsonConvert.SerializeObject(), and Terraria.WorldBuilding.WorldGenSnapshot.SnapshotGenVars.SerializerSettings.
Referenced by Terraria.WorldBuilding.WorldGenSnapshot.Create(), and Terraria.WorldBuilding.WorldGenSnapshot.ResaveForCurrentVersion().