Terraria Decompiled: Terraria.WorldBuilding.WorldGenSnapshot.SnapshotGenVars.ReadJson
ReadJson()
override object Terraria.WorldBuilding.WorldGenSnapshot.SnapshotGenVars.ReadJson (JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer) inline
Definition at line 412 of file WorldGenSnapshot.cs.
            {
                if (reader.TokenType != 1)
                {
                    throw new JsonReaderException();
                }
                while (reader.Read() && reader.TokenType != 13)
                {
                    if (reader.TokenType != 4)
                    {
                        throw new JsonReaderException("Expected PropertyName");
                    }
                    string text = (string)reader.Value;
                    if (!reader.Read())
                    {
                        throw new JsonReaderException();
                    }
                    MemberInfo memberInfo;
                    if (WorldGenSnapshot.SnapshotGenVars.fieldsAndProperties.TryGetValue(text, out memberInfo))
                    {
                        this.SetValue(memberInfo, serializer.Deserialize(reader, this.GetType(memberInfo)));
                    }
                    else
                    {
                        reader.Skip();
                    }
                }
                return null;
            }
References Newtonsoft.Json.JsonSerializer.Deserialize(), Terraria.WorldBuilding.WorldGenSnapshot.SnapshotGenVars.fieldsAndProperties, Newtonsoft.Json.JsonReader.Read(), Terraria.WorldBuilding.WorldGenSnapshot.SnapshotGenVars.SetValue(), Newtonsoft.Json.JsonReader.Skip(), System.text, Newtonsoft.Json.JsonReader.TokenType, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and Newtonsoft.Json.JsonReader.Value.