Terraria Decompiled: Terraria.WorldBuilding.WorldGenSnapshot.SnapshotGenVars.WriteJson
WriteJson()
override void Terraria.WorldBuilding.WorldGenSnapshot.SnapshotGenVars.WriteJson (JsonWriter writer, object value, JsonSerializer serializer) inline
Definition at line 443 of file WorldGenSnapshot.cs.
            {
                writer.WriteStartObject();
                foreach (MemberInfo memberInfo in WorldGenSnapshot.SnapshotGenVars.fieldsAndProperties.Values)
                {
                    writer.WritePropertyName(memberInfo.Name);
                    serializer.Serialize(writer, this.GetValue(memberInfo), this.GetType(memberInfo));
                }
                writer.WriteEndObject();
            }
References Terraria.WorldBuilding.WorldGenSnapshot.SnapshotGenVars.fieldsAndProperties, Terraria.WorldBuilding.WorldGenSnapshot.SnapshotGenVars.GetType(), Terraria.WorldBuilding.WorldGenSnapshot.SnapshotGenVars.GetValue(), System.Reflection.MemberInfo.Name, System.Collections.Generic.Dictionary< TKey, TValue >.Values, and Newtonsoft.Json.JsonWriter.WriteStartObject().