Terraria Decompiled: Newtonsoft.Json.Utilities.CollectionWrapper.Remove
Remove() [2/2]
virtual bool Newtonsoft.Json.Utilities.CollectionWrapper< T >.Remove (T item) inline virtual
Implements System.Collections.Generic.ICollection< T >.
Definition at line 105 of file CollectionWrapper.cs.
        {
            if (this._genericCollection != null)
            {
                return this._genericCollection.Remove(item);
            }
            bool flag = this._list.Contains(item);
            if (flag)
            {
                this._list.Remove(item);
            }
            return flag;
        }
References Newtonsoft.Json.Utilities.CollectionWrapper< T >._genericCollection, Newtonsoft.Json.Utilities.CollectionWrapper< T >._list, System.Collections.Generic.ICollection< T >.Contains(), and System.Collections.Generic.ICollection< T >.Remove().
Referenced by Newtonsoft.Json.Utilities.CollectionWrapper< T >.Remove().