Terraria Decompiled: System.Security.Principal.SecurityIdentifier.CompareTo
CompareTo()
int System.Security.Principal.SecurityIdentifier.CompareTo (SecurityIdentifier sid) inline
Definition at line 155 of file SecurityIdentifier.cs.
        {
            if (sid == null)
            {
                throw new ArgumentNullException("sid");
            }
            int num;
            if ((num = this.GetSidAuthority().CompareTo(sid.GetSidAuthority())) != 0)
            {
                return num;
            }
            if ((num = this.GetSidSubAuthorityCount().CompareTo(sid.GetSidSubAuthorityCount())) != 0)
            {
                return num;
            }
            for (byte b = 0; b < this.GetSidSubAuthorityCount(); b += 1)
            {
                if ((num = this.GetSidSubAuthority(b).CompareTo(sid.GetSidSubAuthority(b))) != 0)
                {
                    return num;
                }
            }
            return 0;
        }
References System.Security.Principal.SecurityIdentifier.CompareTo(), System.Security.Principal.SecurityIdentifier.GetSidAuthority(), System.Security.Principal.SecurityIdentifier.GetSidSubAuthority(), and System.Security.Principal.SecurityIdentifier.GetSidSubAuthorityCount().
Referenced by System.Security.Principal.SecurityIdentifier.CompareTo().