Terraria Decompiled: System.Security.Principal.SecurityIdentifier.ParseSddlForm
ParseSddlForm() [2/2]
static SecurityIdentifier System.Security.Principal.SecurityIdentifier.ParseSddlForm (string sddlForm, ref int pos) inline static package
Definition at line 305 of file SecurityIdentifier.cs.
        {
            if (sddlForm.Length - pos < 2)
            {
                throw new ArgumentException("Invalid SDDL string.", "sddlForm");
            }
            string text = sddlForm.Substring(pos, 2).ToUpperInvariant();
            string text2;
            int num2;
            if (text == "S-")
            {
                int num = pos;
                char c = char.ToUpperInvariant(sddlForm[num]);
                while (c == 'S' || c == '-' || c == 'X' || (c >= '0' && c <= '9') || (c >= 'A' && c <= 'F'))
                {
                    num++;
                    c = char.ToUpperInvariant(sddlForm[num]);
                }
                if (c == ':' && sddlForm[num - 1] == 'D')
                {
                    num--;
                }
                text2 = sddlForm.Substring(pos, num - pos);
                num2 = num - pos;
            }
            else
            {
                text2 = text;
                num2 = 2;
            }
            SecurityIdentifier securityIdentifier = new SecurityIdentifier(text2);
            pos += num2;
            return securityIdentifier;
        }
References System.Security.Principal.SecurityIdentifier.SecurityIdentifier(), and System.text.
Referenced by System.Security.AccessControl.RawSecurityDescriptor.ParseSddl(), System.Security.Principal.SecurityIdentifier.SecurityIdentifier(), and System.Security.Principal.SecurityIdentifier.SecurityIdentifier().