Terraria Decompiled: System.Security.Principal.SecurityIdentifier.ParseSddlForm
ParseSddlForm() [1/2]
static byte[] System.Security.Principal.SecurityIdentifier.ParseSddlForm (string sddlForm) inline static private
Definition at line 341 of file SecurityIdentifier.cs.
        {
            string text = sddlForm;
            if (sddlForm.Length == 2)
            {
                WellKnownAccount wellKnownAccount = WellKnownAccount.LookupBySddlForm(sddlForm);
                if (wellKnownAccount == null)
                {
                    throw new ArgumentException("Invalid SDDL string - unrecognized account: " + sddlForm, "sddlForm");
                }
                if (!wellKnownAccount.IsAbsolute)
                {
                    throw new NotImplementedException("Mono unable to convert account to SID: " + ((wellKnownAccount.Name != null) ? wellKnownAccount.Name : sddlForm));
                }
                text = wellKnownAccount.Sid;
            }
            string[] array = text.ToUpperInvariant().Split('-', StringSplitOptions.None);
            int num = array.Length - 3;
            if (array.Length < 3 || array[0] != "S" || num > 15)
            {
                throw new ArgumentException("Value was invalid.");
            }
            if (array[1] != "1")
            {
                throw new ArgumentException("Only SIDs with revision 1 are supported");
            }
            byte[] array2 = new byte[8 + num * 4];
            array2[0] = 1;
            array2[1] = (byte)num;
            ulong num2;
            if (!SecurityIdentifier.TryParseAuthority(array[2], out num2))
            {
                throw new ArgumentException("Value was invalid.");
            }
            array2[2] = (byte)((num2 >> 40) & 255UL);
            array2[3] = (byte)((num2 >> 32) & 255UL);
            array2[4] = (byte)((num2 >> 24) & 255UL);
            array2[5] = (byte)((num2 >> 16) & 255UL);
            array2[6] = (byte)((num2 >> 8) & 255UL);
            array2[7] = (byte)(num2 & 255UL);
            for (int i = 0; i < num; i++)
            {
                uint num3;
                if (!SecurityIdentifier.TryParseSubAuthority(array[i + 3], out num3))
                {
                    throw new ArgumentException("Value was invalid.");
                }
                int num4 = 8 + i * 4;
                array2[num4] = (byte)num3;
                array2[num4 + 1] = (byte)(num3 >> 8);
                array2[num4 + 2] = (byte)(num3 >> 16);
                array2[num4 + 3] = (byte)(num3 >> 24);
            }
            return array2;
        }
References System.array, System.Security.Principal.WellKnownAccount.IsAbsolute, System.Security.Principal.WellKnownAccount.LookupBySddlForm(), System.Security.Principal.WellKnownAccount.Name, System.Security.Principal.WellKnownAccount.Sid, System.text, System.Security.Principal.SecurityIdentifier.TryParseAuthority(), and System.Security.Principal.SecurityIdentifier.TryParseSubAuthority().