Terraria Decompiled: System.Security.Principal.SecurityIdentifier.Translate
Translate()
override IdentityReference System.Security.Principal.SecurityIdentifier.Translate (Type targetType) inline
Definition at line 254 of file SecurityIdentifier.cs.
        {
            if (targetType == typeof(SecurityIdentifier))
            {
                return this;
            }
            if (!(targetType == typeof(NTAccount)))
            {
                throw new ArgumentException("Unknown type.", "targetType");
            }
            WellKnownAccount wellKnownAccount = WellKnownAccount.LookupBySid(this.Value);
            if (wellKnownAccount == null || wellKnownAccount.Name == null)
            {
                throw new IdentityNotMappedException("Unable to map SID: " + this.Value);
            }
            return new NTAccount(wellKnownAccount.Name);
        }
References System.Security.Principal.WellKnownAccount.LookupBySid(), System.Security.Principal.WellKnownAccount.Name, and System.Security.Principal.SecurityIdentifier.Value.
Referenced by System.Security.AccessControl.ObjectSecurity< T >.GetGroup(), System.Security.AccessControl.ObjectSecurity< T >.GetOwner(), System.Security.AccessControl.DirectoryObjectSecurity.InternalAccessRuleFactory(), System.Security.AccessControl.ObjectSecurity< T >.InternalAccessRuleFactory(), System.Security.AccessControl.DirectoryObjectSecurity.InternalAuditRuleFactory(), and System.Security.AccessControl.ObjectSecurity< T >.InternalAuditRuleFactory().