Terraria Decompiled: Terraria.GameContent.UI.States.UITextWrappingTest.TestElement.DrawSelf
DrawSelf()
override void Terraria.GameContent.UI.States.UITextWrappingTest.TestElement.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 318 of file UITextWrappingTest.cs.
            {
                Vector2 vector = base.GetDimensions().Position();
                float num = base.GetInnerDimensions().Width;
                if (num <= 0f)
                {
                    num = 1000f;
                }
                switch (this.mode)
                {
                case UITextWrappingTest.Mode.SignsAndNPCChat:
                {
                    int num2;
                    string[] array = Utils.WordwrapString(this.text, FontAssets.MouseText.Value, (int)(num / this.scale), 10, out num2);
                    float num3 = 30f * this.scale;
                    this.MinHeight.Set((float)num2 * num3, 0f);
                    this.OnHeightUpdate();
                    for (int i = 0; i < num2; i++)
                    {
                        Utils.DrawBorderStringFourWay(spriteBatch, FontAssets.MouseText.Value, array[i], vector.X, vector.Y + (float)i * num3, Color.White, Color.Black, Vector2.Zero, this.scale);
                    }
                    return;
                }
                case UITextWrappingTest.Mode.WordwrapStringLegacy:
                {
                    int num4;
                    string[] array2 = Utils.WordwrapStringLegacy(this.text, FontAssets.MouseText.Value, (int)(num / this.scale), 10, out num4);
                    float num5 = 30f * this.scale;
                    this.MinHeight.Set((float)num4 * num5, 0f);
                    this.OnHeightUpdate();
                    for (int j = 0; j < num4; j++)
                    {
                        Utils.DrawBorderStringFourWay(spriteBatch, FontAssets.MouseText.Value, array2[j], vector.X, vector.Y + (float)j * num5, Color.White, Color.Black, Vector2.Zero, this.scale);
                    }
                    return;
                }
                case UITextWrappingTest.Mode.DrawColorCodedStringWithShadow:
                {
                    ChatManager.DrawColorCodedStringWithShadow(spriteBatch, FontAssets.MouseText.Value, this.text, vector, Color.White, 0f, Vector2.Zero, new Vector2(this.scale), num, 2f);
                    Vector2 stringSize = ChatManager.GetStringSize(FontAssets.MouseText.Value, this.text, new Vector2(this.scale), num);
                    this.MinHeight.Set(stringSize.Y, 0f);
                    this.OnHeightUpdate();
                    return;
                }
                case UITextWrappingTest.Mode.DrawColorCodedStringLegacy:
                {
                    ChatManager.DrawColorCodedStringShadow(spriteBatch, FontAssets.MouseText.Value, this.text, vector, Color.Black, 0f, Vector2.Zero, new Vector2(this.scale), num, 2f);
                    ChatManager.DrawColorCodedString(spriteBatch, FontAssets.MouseText.Value, this.text, vector, Color.White, 0f, Vector2.Zero, new Vector2(this.scale), num, false);
                    Vector2 stringSize2 = ChatManager.GetStringSize(FontAssets.MouseText.Value, this.text, new Vector2(this.scale), num);
                    this.MinHeight.Set(stringSize2.Y, 0f);
                    this.OnHeightUpdate();
                    return;
                }
                case UITextWrappingTest.Mode.MultilineChat:
                {
                    List<List<TextSnippet>> list = Utils.WordwrapStringSmart(this.text, Color.White, FontAssets.MouseText.Value, (float)((int)(num / this.scale)), 10);
                    float num6 = 30f * this.scale;
                    this.MinHeight.Set((float)list.Count * num6, 0f);
                    this.OnHeightUpdate();
                    for (int k = 0; k < list.Count; k++)
                    {
                        int num7;
                        ChatManager.DrawColorCodedStringWithShadow(spriteBatch, FontAssets.MouseText.Value, list[k].ToArray(), vector + new Vector2(0f, (float)k * num6), 0f, Vector2.Zero, new Vector2(this.scale), out num7, -1f, 2f);
                    }
                    return;
                }
                default:
                    return;
                }
            }
References System.array, Microsoft.Xna.Framework.Color.Black, System.Collections.Generic.List< T >.Count, Terraria.GameContent.UI.Elements.UIList.Count, Terraria.Utils.DrawBorderStringFourWay(), Terraria.UI.Chat.ChatManager.DrawColorCodedString(), Terraria.UI.Chat.ChatManager.DrawColorCodedStringShadow(), Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.UI.Chat.ChatManager.GetStringSize(), Terraria.GameContent.UI.States.UITextWrappingTest.list, Terraria.UI.UIElement.MinHeight, Terraria.GameContent.FontAssets.MouseText, Terraria.GameContent.UI.States.UITextWrappingTest.TestElement.OnHeightUpdate, Terraria.GameContent.UI.States.UITextWrappingTest.TestElement.scale, Terraria.UI.StyleDimension.Set(), Terraria.GameContent.UI.States.UITextWrappingTest.TestElement.text, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Color.White, Terraria.Utils.WordwrapString(), Terraria.Utils.WordwrapStringLegacy(), Terraria.Utils.WordwrapStringSmart(), Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.