Terraria Decompiled: System.IO.IsolatedStorage.IsolatedStorageFileStream.CreateIsolatedPath
CreateIsolatedPath()
static string System.IO.IsolatedStorage.IsolatedStorageFileStream.CreateIsolatedPath (IsolatedStorageFile isf, string path, FileMode mode) inline static private
Definition at line 15 of file IsolatedStorageFileStream.cs.
        {
            if (path == null)
            {
                throw new ArgumentNullException("path");
            }
            if (!Enum.IsDefined(typeof(FileMode), mode))
            {
                throw new ArgumentException("mode");
            }
            if (isf == null)
            {
                isf = IsolatedStorageFile.GetStore(IsolatedStorageScope.User | IsolatedStorageScope.Domain | IsolatedStorageScope.Assembly, IsolatedStorageFile.GetDomainIdentityFromEvidence(AppDomain.CurrentDomain.Evidence), IsolatedStorageFile.GetAssemblyIdentityFromEvidence(new StackFrame(3).GetMethod().ReflectedType.Assembly.UnprotectedGetEvidence()));
            }
            if (isf.IsDisposed)
            {
                throw new ObjectDisposedException("IsolatedStorageFile");
            }
            if (isf.IsClosed)
            {
                throw new InvalidOperationException("Storage needs to be open for this operation.");
            }
            FileInfo fileInfo = new FileInfo(isf.Root);
            if (!fileInfo.Directory.Exists)
            {
                fileInfo.Directory.Create();
            }
            if (Path.IsPathRooted(path))
            {
                string pathRoot = Path.GetPathRoot(path);
                path = path.Remove(0, pathRoot.Length);
            }
            string text = Path.Combine(isf.Root, path);
            Path.GetFullPath(text);
            if (!Path.GetFullPath(text).StartsWith(isf.Root))
            {
                throw new IsolatedStorageException();
            }
            fileInfo = new FileInfo(text);
            if (!fileInfo.Directory.Exists)
            {
                throw new DirectoryNotFoundException(string.Format(Locale.GetText("Could not find a part of the path \"{0}\"."), path));
            }
            return text;
        }
References System.IO.Path.Combine(), System.IO.DirectoryInfo.Create(), System.AppDomain.CurrentDomain, System.IO.FileInfo.Directory, System.AppDomain.Evidence, System.IO.FileSystemInfo.Exists, System.Format, System.IO.IsolatedStorage.IsolatedStorageFile.GetAssemblyIdentityFromEvidence(), System.IO.IsolatedStorage.IsolatedStorageFile.GetDomainIdentityFromEvidence(), System.IO.Path.GetFullPath(), System.IO.Path.GetPathRoot(), System.IO.IsolatedStorage.IsolatedStorageFile.GetStore(), Locale.GetText(), System.IO.IsolatedStorage.IsolatedStorageFile.IsClosed, System.Enum.IsDefined(), System.IO.IsolatedStorage.IsolatedStorageFile.IsDisposed, System.IO.Path.IsPathRooted(), System.mode, System.IO.IsolatedStorage.IsolatedStorageFile.Root, and System.text.