Terraria Decompiled: System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore.InvokeContinuation
InvokeContinuation()
void System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.InvokeContinuation () inline private
Definition at line 208 of file ManualResetValueTaskSourceCore.cs.
        {
            object capturedContext = this._capturedContext;
            if (capturedContext != null)
            {
                SynchronizationContext synchronizationContext = capturedContext as SynchronizationContext;
                if (synchronizationContext != null)
                {
                    synchronizationContext.Post(delegate(object s)
                    {
                        Tuple<Action<object>, object> tuple = (Tuple<Action<object>, object>)s;
                        tuple.Item1(tuple.Item2);
                    }, Tuple.Create<Action<object>, object>(this._continuation, this._continuationState));
                    return;
                }
                TaskScheduler taskScheduler = capturedContext as TaskScheduler;
                if (taskScheduler == null)
                {
                    return;
                }
                Task.Factory.StartNew(this._continuation, this._continuationState, CancellationToken.None, TaskCreationOptions.DenyChildAttach, taskScheduler);
                return;
            }
            else
            {
                if (!this.RunContinuationsAsynchronously)
                {
                    this._continuation(this._continuationState);
                    return;
                }
                if (this._executionContext != null)
                {
                    ThreadPool.QueueUserWorkItem<object>(this._continuation, this._continuationState, true);
                    return;
                }
                ThreadPool.UnsafeQueueUserWorkItem<object>(this._continuation, this._continuationState, true);
                return;
            }
        }
References System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >._capturedContext, System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >._continuation, System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >._continuationState, System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >._executionContext, System.Threading.Tasks.Task< TResult >.Factory, System.Tuple< T1, T2, T3, T4, T5, T6, T7, TRest >.Item1, System.Tuple< T1, T2, T3, T4, T5, T6, T7, TRest >.Item2, System.Threading.CancellationToken.None, System.Threading.SynchronizationContext.Post(), System.Threading.ThreadPool.QueueUserWorkItem(), System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.RunContinuationsAsynchronously, System.s, System.Threading.Tasks.TaskFactory< TResult >.StartNew(), and System.Threading.ThreadPool.UnsafeQueueUserWorkItem().
Referenced by System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.SignalCompletion().