Terraria Decompiled: System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore.OnCompleted
OnCompleted()
void System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.OnCompleted (Action< object > continuation, object state, short token, ValueTaskSourceOnCompletedFlags flags) inline
Definition at line 104 of file ManualResetValueTaskSourceCore.cs.
        {
            if (continuation == null)
            {
                throw new ArgumentNullException("continuation");
            }
            this.ValidateToken(token);
            if ((flags & ValueTaskSourceOnCompletedFlags.FlowExecutionContext) != ValueTaskSourceOnCompletedFlags.None)
            {
                this._executionContext = ExecutionContext.Capture();
            }
            if ((flags & ValueTaskSourceOnCompletedFlags.UseSchedulingContext) != ValueTaskSourceOnCompletedFlags.None)
            {
                SynchronizationContext synchronizationContext = SynchronizationContext.Current;
                if (synchronizationContext != null && synchronizationContext.GetType() != typeof(SynchronizationContext))
                {
                    this._capturedContext = synchronizationContext;
                }
                else
                {
                    TaskScheduler taskScheduler = TaskScheduler.Current;
                    if (taskScheduler != TaskScheduler.Default)
                    {
                        this._capturedContext = taskScheduler;
                    }
                }
            }
            object obj = this._continuation;
            if (obj == null)
            {
                this._continuationState = state;
                obj = Interlocked.CompareExchange<Action<object>>(ref this._continuation, continuation, null);
            }
            if (obj != null)
            {
                if (obj != ManualResetValueTaskSourceCoreShared.s_sentinel)
                {
                    ManualResetValueTaskSourceCoreShared.ThrowInvalidOperationException();
                }
                object capturedContext = this._capturedContext;
                if (capturedContext != null)
                {
                    SynchronizationContext synchronizationContext2 = capturedContext as SynchronizationContext;
                    if (synchronizationContext2 != null)
                    {
                        synchronizationContext2.Post(delegate(object s)
{
                            Tuple<Action<object>, object> tuple = (Tuple<Action<object>, object>)s;
                            tuple.Item1(tuple.Item2);
                        }, Tuple.Create<Action<object>, object>(continuation, state));
                        return;
                    }
                    TaskScheduler taskScheduler2 = capturedContext as TaskScheduler;
                    if (taskScheduler2 == null)
                    {
                        return;
                    }
                    Task.Factory.StartNew(continuation, state, CancellationToken.None, TaskCreationOptions.DenyChildAttach, taskScheduler2);
                }
                else
                {
                    if (this._executionContext != null)
                    {
                        ThreadPool.QueueUserWorkItem<object>(continuation, state, true);
                        return;
                    }
                    ThreadPool.UnsafeQueueUserWorkItem<object>(continuation, state, true);
                    return;
                }
            }
        }
References System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >._capturedContext, System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >._continuation, System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >._executionContext, System.Threading.ExecutionContext.Capture(), System.Threading.Interlocked.CompareExchange(), System.Threading.SynchronizationContext.Current, System.Threading.Tasks.TaskScheduler.Current, System.Threading.Tasks.TaskScheduler.Default, System.Threading.Tasks.Task< TResult >.Factory, System.Tuple< T1, T2, T3, T4, T5, T6, T7, TRest >.Item1, System.Tuple< T1, T2, T3, T4, T5, T6, T7, TRest >.Item2, System.Threading.CancellationToken.None, System.obj, System.Threading.SynchronizationContext.Post(), System.Threading.ThreadPool.QueueUserWorkItem(), System.s, System.Threading.Tasks.Sources.ManualResetValueTaskSourceCoreShared.s_sentinel, System.Threading.Tasks.TaskFactory< TResult >.StartNew(), System.state, System.Threading.Tasks.Sources.ManualResetValueTaskSourceCoreShared.ThrowInvalidOperationException(), System.Threading.ThreadPool.UnsafeQueueUserWorkItem(), and System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.ValidateToken().