Terraria Decompiled: System.Runtime.InteropServices.WindowsRuntime.EventRegistrationToken.Equals
Equals()
override bool System.Runtime.InteropServices.WindowsRuntime.EventRegistrationToken.Equals (object obj) inline
Definition at line 37 of file EventRegistrationToken.cs.
        {
            return obj is EventRegistrationToken && ((EventRegistrationToken)obj).Value == this.Value;
        }
References System.Runtime.InteropServices.WindowsRuntime.EventRegistrationToken.EventRegistrationToken(), System.obj, and System.Runtime.InteropServices.WindowsRuntime.EventRegistrationToken.Value.
Referenced by System.Runtime.InteropServices.WindowsRuntime.EventRegistrationToken.operator!=(), and System.Runtime.InteropServices.WindowsRuntime.EventRegistrationToken.operator==().