Terraria Decompiled: Terraria.UI.InGameNotificationsTracker.DrawInGame
DrawInGame()
static void Terraria.UI.InGameNotificationsTracker.DrawInGame (SpriteBatch sb) inline static
Definition at line 42 of file InGameNotificationsTracker.cs.
        {
            float num = (float)(Main.screenHeight - 40);
            if (PlayerInput.UsingGamepad)
            {
                num -= 25f;
            }
            Vector2 vector = new Vector2((float)(Main.screenWidth / 2), num);
            foreach (IInGameNotification inGameNotification in InGameNotificationsTracker._notifications)
            {
                inGameNotification.DrawInGame(sb, vector);
                inGameNotification.PushAnchor(ref vector);
                if (vector.Y < -100f)
                {
                    break;
                }
            }
        }
References Terraria.UI.InGameNotificationsTracker._notifications, Terraria.UI.IInGameNotification.DrawInGame(), Terraria.UI.IInGameNotification.PushAnchor(), Terraria.Main.screenHeight, Terraria.Main.screenWidth, Terraria.GameInput.PlayerInput.UsingGamepad, and Microsoft.Xna.Framework.Graphics.Vector2.
Referenced by Terraria.Main.DrawInterface_13_AchievementCompletePopups().