Terraria Decompiled: Terraria.ID.TorchID.TorchColor
TorchColor()
static void Terraria.ID.TorchID.TorchColor (int torchID, out float R, out float G, out float B) inline static
Definition at line 41 of file TorchID.cs.
        {
            if (torchID < 0 || torchID >= TorchID._lights.Length)
            {
                R = (G = (B = 0f));
                return;
            }
            TorchID._lights[torchID].GetRGB(out R, out G, out B);
        }
References Terraria.ID.TorchID._lights, System.B, System.G, and System.R.
Referenced by Terraria.Lighting.AddLight(), Terraria.Lighting.AddLight(), Terraria.NPC.AI_007_TownEntities(), Terraria.Graphics.Light.TileLightScanner.ApplyTileLight(), and Terraria.Player.ItemCheck_EmitHeldItemLight().