Terraria Decompiled: System.Runtime.Remoting.Metadata.W3cXsd2001.SoapDuration.ToString
ToString()
static string System.Runtime.Remoting.Metadata.W3cXsd2001.SoapDuration.ToString (TimeSpan timeSpan) inline static
Definition at line 201 of file SoapDuration.cs.
        {
            StringBuilder stringBuilder = new StringBuilder();
            if (timeSpan.Ticks < 0L)
            {
                stringBuilder.Append('-');
                timeSpan = timeSpan.Negate();
            }
            stringBuilder.Append('P');
            if (timeSpan.Days > 0)
            {
                stringBuilder.Append(timeSpan.Days).Append('D');
            }
            if (timeSpan.Days > 0 || timeSpan.Minutes > 0 || timeSpan.Seconds > 0 || timeSpan.Milliseconds > 0)
            {
                stringBuilder.Append('T');
                if (timeSpan.Hours > 0)
                {
                    stringBuilder.Append(timeSpan.Hours).Append('H');
                }
                if (timeSpan.Minutes > 0)
                {
                    stringBuilder.Append(timeSpan.Minutes).Append('M');
                }
                if (timeSpan.Seconds > 0 || timeSpan.Milliseconds > 0)
                {
                    double num = (double)timeSpan.Seconds;
                    if (timeSpan.Milliseconds > 0)
                    {
                        num += (double)timeSpan.Milliseconds / 1000.0;
                    }
                    stringBuilder.Append(string.Format(CultureInfo.InvariantCulture, "{0:0.0000000}", num));
                    stringBuilder.Append('S');
                }
            }
            return stringBuilder.ToString();
        }
References System.Text.StringBuilder.Append(), System.TimeSpan.Days, System.Format, System.TimeSpan.Hours, System.Globalization.CultureInfo.InvariantCulture, System.L, System.TimeSpan.Milliseconds, System.TimeSpan.Minutes, System.TimeSpan.Negate(), System.TimeSpan.Seconds, System.TimeSpan.Ticks, and System.Text.StringBuilder.ToString().