Terraria Decompiled: FullSerializer.fsMetaType.EmitAotData
EmitAotData()
bool FullSerializer.fsMetaType.EmitAotData () inline
Definition at line 125 of file fsMetaType.cs.
        {
            if (this._hasEmittedAotData)
            {
                return false;
            }
            this._hasEmittedAotData = true;
            for (int i = 0; i < this.Properties.Length; i++)
            {
                if (!this.Properties[i].IsPublic)
                {
                    return false;
                }
            }
            if (!this.HasDefaultConstructor)
            {
                return false;
            }
            fsAotCompilationManager.AddAotCompilation(this.ReflectedType, this.Properties, this._isDefaultConstructorPublic);
            return true;
        }
References FullSerializer.fsMetaType._hasEmittedAotData, FullSerializer.fsMetaType._isDefaultConstructorPublic, FullSerializer.fsAotCompilationManager.AddAotCompilation(), FullSerializer.fsMetaType.HasDefaultConstructor, FullSerializer.fsMetaType.Properties, and FullSerializer.fsMetaType.ReflectedType.
Referenced by FullSerializer.Internal.fsReflectedConverter.TryDeserialize(), FullSerializer.Internal.fsReflectedConverter.TrySerialize(), and FullSerializer.fsAotCompilationManager.TryToPerformAotCompilation().