Terraria Decompiled: FullSerializer.fsMetaType.CollectProperties
CollectProperties()
static void FullSerializer.fsMetaType.CollectProperties (fsConfig config, List< fsMetaProperty > properties, Type reflectedType) inline static private
Definition at line 47 of file fsMetaType.cs.
        {
            bool flag = config.DefaultMemberSerialization == fsMemberSerialization.OptIn;
            bool flag2 = config.DefaultMemberSerialization == fsMemberSerialization.OptOut;
            fsObjectAttribute attribute = fsPortableReflection.GetAttribute<fsObjectAttribute>(reflectedType);
            if (attribute != null)
            {
                flag = attribute.MemberSerialization == fsMemberSerialization.OptIn;
                flag2 = attribute.MemberSerialization == fsMemberSerialization.OptOut;
            }
            MemberInfo[] declaredMembers = reflectedType.GetDeclaredMembers();
            MemberInfo[] array = declaredMembers;
            for (int i = 0; i < array.Length; i++)
            {
                MemberInfo member = array[i];
                if (!Enumerable.Any<Type>(config.IgnoreSerializeAttributes, (Type t) => fsPortableReflection.HasAttribute(member, t)))
                {
                    PropertyInfo propertyInfo = member as PropertyInfo;
                    FieldInfo fieldInfo = member as FieldInfo;
                    if ((!(propertyInfo == null) || !(fieldInfo == null)) && (!flag || Enumerable.Any<Type>(config.SerializeAttributes, (Type t) => fsPortableReflection.HasAttribute(member, t))) && (!flag2 || !Enumerable.Any<Type>(config.IgnoreSerializeAttributes, (Type t) => fsPortableReflection.HasAttribute(member, t))))
                    {
                        if (propertyInfo != null)
{
                            if (fsMetaType.CanSerializeProperty(config, propertyInfo, declaredMembers, flag2))
{
                                properties.Add(new fsMetaProperty(config, propertyInfo));
                            }
                        }
                        else if (fieldInfo != null && fsMetaType.CanSerializeField(config, fieldInfo, flag2))
{
                            properties.Add(new fsMetaProperty(config, fieldInfo));
                        }
                    }
                }
            }
            if (reflectedType.Resolve().BaseType != null)
            {
                fsMetaType.CollectProperties(config, properties, reflectedType.Resolve().BaseType);
            }
        }
References System.Collections.Generic.List< T >.Add(), System.array, System.Type.BaseType, FullSerializer.fsMetaType.CanSerializeField(), FullSerializer.fsMetaType.CanSerializeProperty(), FullSerializer.fsMetaType.CollectProperties(), FullSerializer.Internal.fsPortableReflection.GetAttribute(), FullSerializer.Internal.fsPortableReflection.HasAttribute(), FullSerializer.fsConfig.IgnoreSerializeAttributes, and FullSerializer.fsConfig.SerializeAttributes.
Referenced by FullSerializer.fsMetaType.CollectProperties(), and FullSerializer.fsMetaType.fsMetaType().