Terraria Decompiled: FullSerializer.fsMetaType.CreateInstance
CreateInstance()
object FullSerializer.fsMetaType.CreateInstance () inline
Definition at line 197 of file fsMetaType.cs.
        {
            if (this.ReflectedType.Resolve().IsInterface || this.ReflectedType.Resolve().IsAbstract)
            {
                throw new Exception("Cannot create an instance of an interface or abstract type for " + this.ReflectedType);
            }
            if (typeof(string) == this.ReflectedType)
            {
                return string.Empty;
            }
            if (!this.HasDefaultConstructor)
            {
                return FormatterServices.GetSafeUninitializedObject(this.ReflectedType);
            }
            if (this.ReflectedType.Resolve().IsArray)
            {
                return Array.CreateInstance(this.ReflectedType.GetElementType(), 0);
            }
            object obj;
            try
            {
                obj = Activator.CreateInstance(this.ReflectedType, true);
            }
            catch (MissingMethodException ex)
            {
                throw new InvalidOperationException("Unable to create instance of " + this.ReflectedType + "; there is no default constructor", ex);
            }
            catch (TargetInvocationException ex2)
            {
                throw new InvalidOperationException("Constructor of " + this.ReflectedType + " threw an exception when creating an instance", ex2);
            }
            catch (MemberAccessException ex3)
            {
                throw new InvalidOperationException("Unable to access constructor of " + this.ReflectedType, ex3);
            }
            return obj;
        }
References System.Array.CreateInstance(), System.Activator.CreateInstance(), System.Type.GetElementType(), System.Runtime.Serialization.FormatterServices.GetSafeUninitializedObject(), FullSerializer.fsMetaType.HasDefaultConstructor, System.Type.IsArray, System.Type.IsInterface, System.obj, and FullSerializer.fsMetaType.ReflectedType.
Referenced by FullSerializer.Internal.fsArrayConverter.CreateInstance(), FullSerializer.Internal.fsDictionaryConverter.CreateInstance(), FullSerializer.Internal.fsForwardConverter.CreateInstance(), FullSerializer.Internal.fsIEnumerableConverter.CreateInstance(), and FullSerializer.Internal.fsReflectedConverter.CreateInstance().