Terraria Decompiled: FullSerializer.fsMetaType.CanSerializeProperty
CanSerializeProperty()
static bool FullSerializer.fsMetaType.CanSerializeProperty (fsConfig config, PropertyInfo property, MemberInfo[] members, bool annotationFreeValue) inline static private
Definition at line 107 of file fsMetaType.cs.
        {
            if (typeof(Delegate).IsAssignableFrom(property.PropertyType))
            {
                return false;
            }
            MethodInfo getMethod = property.GetGetMethod(false);
            MethodInfo setMethod = property.GetSetMethod(false);
            return (!(getMethod != null) || !getMethod.IsStatic) && (!(setMethod != null) || !setMethod.IsStatic) && property.GetIndexParameters().Length == 0 && (Enumerable.Any<Type>(config.SerializeAttributes, (Type t) => fsPortableReflection.HasAttribute(property, t)) || (property.CanRead && property.CanWrite && (((config.SerializeNonAutoProperties || fsMetaType.IsAutoProperty(property, members)) && getMethod != null && (config.SerializeNonPublicSetProperties || setMethod != null)) || annotationFreeValue)));
        }
References System.Reflection.PropertyInfo.CanRead, System.Reflection.PropertyInfo.CanWrite, FullSerializer.Internal.fsPortableReflection.HasAttribute(), FullSerializer.fsMetaType.IsAutoProperty(), System.Reflection.MethodBase.IsStatic, System.Reflection.PropertyInfo.PropertyType, FullSerializer.fsConfig.SerializeAttributes, FullSerializer.fsConfig.SerializeNonAutoProperties, and FullSerializer.fsConfig.SerializeNonPublicSetProperties.
Referenced by FullSerializer.fsMetaType.CollectProperties().