Terraria Decompiled: System.Reflection.MethodInfo.GetGenericArguments
GetGenericArguments()
override Type[] System.Reflection.MethodInfo.GetGenericArguments () inline virtual
Reimplemented from System.Reflection.MethodBase.
Reimplemented in System.Reflection.Emit.MethodOnTypeBuilderInst, and System.Reflection.RuntimeMethodInfo.
Definition at line 49 of file MethodInfo.cs.
        {
            throw new NotSupportedException("Derived classes must provide an implementation.");
        }
Referenced by System.Reflection.Emit.MethodOnTypeBuilderInst.GetGenericArguments(), System.Reflection.Emit.MethodOnTypeBuilderInst.MakeGenericMethod(), System.Runtime.Remoting.Messaging.CADMethodRef.Resolve(), and System.Reflection.SignatureTypeExtensions.TryResolveAgainstGenericMethod().