Terraria Decompiled: System.Reflection.MethodInfo.GetBaseDefinition
GetBaseDefinition()
MethodInfo System.Reflection.MethodInfo.GetBaseDefinition () abstract
Implements System.Runtime.InteropServices._MethodInfo.
Referenced by System.Reflection.MethodInfoExtensions.GetBaseDefinition(), Newtonsoft.Json.Utilities.ReflectionUtils.GetBaseDefinition(), Newtonsoft.Json.Utilities.ReflectionUtils.GetChildPrivateProperties(), System.Reflection.RuntimeReflectionExtensions.GetRuntimeBaseDefinition(), Microsoft.Xna.Framework.Content.ReflectiveReader< T >.Initialize(), and System.Attribute.InternalParamGetCustomAttributes().