Terraria Decompiled: Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTime
TryParseDateTime() [1/2]
static bool Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTime (string s, DateTimeZoneHandling dateTimeZoneHandling, string dateFormatString, CultureInfo culture, out DateTime dt) inline static package
Definition at line 307 of file DateTimeUtils.cs.
        {
            if (s.Length > 0)
            {
                if (s.get_Chars(0) == '/')
                {
                    if (s.Length >= 9 && s.StartsWith("/Date(", 4) && s.EndsWith(")/", 4) && DateTimeUtils.TryParseDateTimeMicrosoft(new StringReference(s.ToCharArray(), 0, s.Length), dateTimeZoneHandling, out dt))
                    {
                        return true;
                    }
                }
                else if (s.Length >= 19 && s.Length <= 40 && char.IsDigit(s.get_Chars(0)) && s.get_Chars(10) == 'T' && DateTime.TryParseExact(s, "yyyy-MM-ddTHH:mm:ss.FFFFFFFK", CultureInfo.InvariantCulture, 128, ref dt))
                {
                    dt = DateTimeUtils.EnsureDateTime(dt, dateTimeZoneHandling);
                    return true;
                }
                if (!string.IsNullOrEmpty(dateFormatString) && DateTimeUtils.TryParseDateTimeExact(s, dateTimeZoneHandling, dateFormatString, culture, out dt))
                {
                    return true;
                }
            }
            dt = default(DateTime);
            return false;
        }
References System.culture, Newtonsoft.Json.Utilities.DateTimeUtils.EnsureDateTime(), System.Globalization.CultureInfo.InvariantCulture, System.s, Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTimeExact(), Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTimeMicrosoft(), and System.DateTime.TryParseExact().