Terraria Decompiled: Newtonsoft.Json.Utilities.DateTimeUtils.ToUniversalTicks
ToUniversalTicks() [1/2]
static long Newtonsoft.Json.Utilities.DateTimeUtils.ToUniversalTicks (DateTime dateTime) inline static private
Definition at line 93 of file DateTimeUtils.cs.
        {
            if (dateTime.Kind == 1)
            {
                return dateTime.Ticks;
            }
            return DateTimeUtils.ToUniversalTicks(dateTime, dateTime.GetUtcOffset());
        }
References System.DateTime.Kind, System.DateTime.Ticks, and Newtonsoft.Json.Utilities.DateTimeUtils.ToUniversalTicks().
Referenced by Newtonsoft.Json.Utilities.DateTimeUtils.ConvertDateTimeToJavaScriptTicks(), Newtonsoft.Json.Utilities.DateTimeUtils.ConvertDateTimeToJavaScriptTicks(), and Newtonsoft.Json.Utilities.DateTimeUtils.ToUniversalTicks().