Terraria Decompiled: Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTimeOffset
TryParseDateTimeOffset() [2/2]
static bool Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTimeOffset (StringReference s, string dateFormatString, CultureInfo culture, out DateTimeOffset dt) inline static package
Definition at line 333 of file DateTimeUtils.cs.
        {
            if (s.Length > 0)
            {
                int startIndex = s.StartIndex;
                if (s[startIndex] == '/')
                {
                    if (s.Length >= 9 && s.StartsWith("/Date(") && s.EndsWith(")/") && DateTimeUtils.TryParseDateTimeOffsetMicrosoft(s, out dt))
                    {
                        return true;
                    }
                }
                else if (s.Length >= 19 && s.Length <= 40 && char.IsDigit(s[startIndex]) && s[startIndex + 10] == 'T' && DateTimeUtils.TryParseDateTimeOffsetIso(s, out dt))
                {
                    return true;
                }
                if (!string.IsNullOrEmpty(dateFormatString) && DateTimeUtils.TryParseDateTimeOffsetExact(s.ToString(), dateFormatString, culture, out dt))
                {
                    return true;
                }
            }
            dt = default(DateTimeOffset);
            return false;
        }
References System.culture, System.s, System.startIndex, Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTimeOffsetExact(), Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTimeOffsetIso(), and Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTimeOffsetMicrosoft().
Referenced by Newtonsoft.Json.JsonTextReader.ParseReadString(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(), and Newtonsoft.Json.JsonReader.ReadDateTimeOffsetString().