Terraria Decompiled: Newtonsoft.Json.Utilities.DateTimeUtils.TryParseMicrosoftDate
TryParseMicrosoftDate()
static bool Newtonsoft.Json.Utilities.DateTimeUtils.TryParseMicrosoftDate (StringReference text, out long ticks, out TimeSpan offset, out DateTimeKind kind) inline static private
Definition at line 384 of file DateTimeUtils.cs.
        {
            kind = 1;
            int num = text.IndexOf('+', 7, text.Length - 8);
            if (num == -1)
            {
                num = text.IndexOf('-', 7, text.Length - 8);
            }
            if (num != -1)
            {
                kind = 2;
                if (!DateTimeUtils.TryReadOffset(text, num + text.StartIndex, out offset))
                {
                    ticks = 0L;
                    return false;
                }
            }
            else
            {
                offset = TimeSpan.Zero;
                num = text.Length - 2;
            }
            return ConvertUtils.Int64TryParse(text.Chars, 6 + text.StartIndex, num - 6, out ticks) == ParseResult.Success;
        }
References Newtonsoft.Json.Utilities.ConvertUtils.Int64TryParse(), System.L, System.offset, System.text, Newtonsoft.Json.Utilities.DateTimeUtils.TryReadOffset(), and System.TimeSpan.Zero.
Referenced by Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTimeMicrosoft(), and Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTimeOffsetMicrosoft().