Terraria Decompiled: Newtonsoft.Json.Utilities.DateTimeUtils.ConvertJavaScriptTicksToDateTime
ConvertJavaScriptTicksToDateTime()
static DateTime Newtonsoft.Json.Utilities.DateTimeUtils.ConvertJavaScriptTicksToDateTime (long javaScriptTicks) inline static package
Definition at line 146 of file DateTimeUtils.cs.
        {
            return new DateTime(javaScriptTicks * 10000L + DateTimeUtils.InitialJavaScriptDateTicks, 1);
        }
References Newtonsoft.Json.Utilities.DateTime, Newtonsoft.Json.Utilities.DateTimeUtils.InitialJavaScriptDateTicks, and System.L.
Referenced by Newtonsoft.Json.Converters.JavaScriptDateTimeConverter.ReadJson(), Newtonsoft.Json.Bson.BsonReader.ReadType(), Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTimeMicrosoft(), Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTimeOffsetMicrosoft(), and Newtonsoft.Json.JsonWriter.WriteConstructorDate().