Terraria Decompiled: Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTimeOffset
TryParseDateTimeOffset() [1/2]
static bool Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTimeOffset (string s, string dateFormatString, CultureInfo culture, out DateTimeOffset dt) inline static package
Definition at line 359 of file DateTimeUtils.cs.
        {
            if (s.Length > 0)
            {
                if (s.get_Chars(0) == '/')
                {
                    if (s.Length >= 9 && s.StartsWith("/Date(", 4) && s.EndsWith(")/", 4) && DateTimeUtils.TryParseDateTimeOffsetMicrosoft(new StringReference(s.ToCharArray(), 0, s.Length), out dt))
                    {
                        return true;
                    }
                }
                else if (s.Length >= 19 && s.Length <= 40 && char.IsDigit(s.get_Chars(0)) && s.get_Chars(10) == 'T' && DateTimeOffset.TryParseExact(s, "yyyy-MM-ddTHH:mm:ss.FFFFFFFK", CultureInfo.InvariantCulture, 128, ref dt) && DateTimeUtils.TryParseDateTimeOffsetIso(new StringReference(s.ToCharArray(), 0, s.Length), out dt))
                {
                    return true;
                }
                if (!string.IsNullOrEmpty(dateFormatString) && DateTimeUtils.TryParseDateTimeOffsetExact(s, dateFormatString, culture, out dt))
                {
                    return true;
                }
            }
            dt = default(DateTimeOffset);
            return false;
        }
References System.culture, System.Globalization.CultureInfo.InvariantCulture, System.s, Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTimeOffsetExact(), Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTimeOffsetIso(), Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTimeOffsetMicrosoft(), and System.DateTimeOffset.TryParseExact().