Terraria Decompiled: Newtonsoft.Json.Utilities.DateTimeUtils.WriteDefaultIsoDate
WriteDefaultIsoDate()
static int Newtonsoft.Json.Utilities.DateTimeUtils.WriteDefaultIsoDate (char[] chars, int start, DateTime dt) inline static package
Definition at line 565 of file DateTimeUtils.cs.
        {
            int num = 19;
            int num2;
            int num3;
            int num4;
            DateTimeUtils.GetDateValues(dt, out num2, out num3, out num4);
            DateTimeUtils.CopyIntToCharArray(chars, start, num2, 4);
            chars[start + 4] = '-';
            DateTimeUtils.CopyIntToCharArray(chars, start + 5, num3, 2);
            chars[start + 7] = '-';
            DateTimeUtils.CopyIntToCharArray(chars, start + 8, num4, 2);
            chars[start + 10] = 'T';
            DateTimeUtils.CopyIntToCharArray(chars, start + 11, dt.Hour, 2);
            chars[start + 13] = ':';
            DateTimeUtils.CopyIntToCharArray(chars, start + 14, dt.Minute, 2);
            chars[start + 16] = ':';
            DateTimeUtils.CopyIntToCharArray(chars, start + 17, dt.Second, 2);
            int num5 = (int)(dt.Ticks % 10000000L);
            if (num5 != 0)
            {
                int num6 = 7;
                while (num5 % 10 == 0)
                {
                    num6--;
                    num5 /= 10;
                }
                chars[start + 19] = '.';
                DateTimeUtils.CopyIntToCharArray(chars, start + 20, num5, num6);
                num += num6 + 1;
            }
            return start + num;
        }
References Newtonsoft.Json.Utilities.DateTimeUtils.CopyIntToCharArray(), Newtonsoft.Json.Utilities.DateTimeUtils.GetDateValues(), System.DateTime.Hour, int, System.L, System.DateTime.Minute, System.DateTime.Second, System.start, and System.DateTime.Ticks.
Referenced by Newtonsoft.Json.Utilities.DateTimeUtils.WriteDateTimeString().