Terraria Decompiled: Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTimeOffsetMicrosoft
TryParseDateTimeOffsetMicrosoft()
static bool Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTimeOffsetMicrosoft (StringReference text, out DateTimeOffset dt) inline static private
Definition at line 455 of file DateTimeUtils.cs.
        {
            long num;
            TimeSpan timeSpan;
            DateTimeKind dateTimeKind;
            if (!DateTimeUtils.TryParseMicrosoftDate(text, out num, out timeSpan, out dateTimeKind))
            {
                dt = default(DateTime);
                return false;
            }
            dt = new DateTimeOffset(DateTimeUtils.ConvertJavaScriptTicksToDateTime(num).Add(timeSpan).Ticks, timeSpan);
            return true;
        }
References System.DateTime.Add(), Newtonsoft.Json.Utilities.DateTimeUtils.ConvertJavaScriptTicksToDateTime(), Newtonsoft.Json.Utilities.DateTimeOffset, System.text, System.DateTime.Ticks, and Newtonsoft.Json.Utilities.DateTimeUtils.TryParseMicrosoftDate().
Referenced by Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTimeOffset(), and Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTimeOffset().