Terraria Decompiled: Newtonsoft.Json.Utilities.DateTimeUtils.EnsureDateTime
EnsureDateTime()
static DateTime Newtonsoft.Json.Utilities.DateTimeUtils.EnsureDateTime (DateTime value, DateTimeZoneHandling timeZone) inline static package
Definition at line 39 of file DateTimeUtils.cs.
        {
            switch (timeZone)
            {
            case DateTimeZoneHandling.Local:
                value = DateTimeUtils.SwitchToLocalTime(value);
                break;
            case DateTimeZoneHandling.Utc:
                value = DateTimeUtils.SwitchToUtcTime(value);
                break;
            case DateTimeZoneHandling.Unspecified:
                value..ctor(value.Ticks, 0);
                break;
            case DateTimeZoneHandling.RoundtripKind:
                break;
            default:
                throw new ArgumentException("Invalid date time handling value.");
            }
            return value;
        }
References Newtonsoft.Json.Utilities.DateTimeUtils.SwitchToLocalTime(), Newtonsoft.Json.Utilities.DateTimeUtils.SwitchToUtcTime(), and System.value.
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.GetPropertyName(), Newtonsoft.Json.JsonReader.ReadDateTimeString(), Newtonsoft.Json.JsonConvert.ToString(), Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTime(), Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTimeExact(), Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTimeIso(), Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTimeMicrosoft(), Newtonsoft.Json.Bson.BsonWriter.WriteValue(), Newtonsoft.Json.JsonTextWriter.WriteValue(), and Newtonsoft.Json.Linq.JTokenWriter.WriteValue().