Terraria Decompiled: Newtonsoft.Json.Utilities.DateTimeUtils.WriteDateTimeString
WriteDateTimeString() [2/2]
static void Newtonsoft.Json.Utilities.DateTimeUtils.WriteDateTimeString (TextWriter writer, DateTime value, DateFormatHandling format, string formatString, CultureInfo culture) inline static package
Definition at line 507 of file DateTimeUtils.cs.
        {
            if (string.IsNullOrEmpty(formatString))
            {
                char[] array = new char[64];
                int num = DateTimeUtils.WriteDateTimeString(array, 0, value, default(TimeSpan?), value.Kind, format);
                writer.Write(array, 0, num);
                return;
            }
            writer.Write(value.ToString(formatString, culture));
        }
References System.array, System.culture, System.format, System.value, System.IO.TextWriter.Write(), and Newtonsoft.Json.Utilities.DateTimeUtils.WriteDateTimeString().
Referenced by Newtonsoft.Json.Linq.JsonPath.BooleanQueryExpression.EqualsWithStringCoercion(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.GetPropertyName(), Newtonsoft.Json.JsonConvert.ToString(), Newtonsoft.Json.Utilities.DateTimeUtils.WriteDateTimeOffsetString(), Newtonsoft.Json.Utilities.DateTimeUtils.WriteDateTimeString(), Newtonsoft.Json.JsonTextWriter.WriteValueToBuffer(), and Newtonsoft.Json.JsonTextWriter.WriteValueToBuffer().