Terraria Decompiled: Newtonsoft.Json.Utilities.DateTimeUtils.WriteDateTimeOffset
WriteDateTimeOffset()
static int Newtonsoft.Json.Utilities.DateTimeUtils.WriteDateTimeOffset (char[] chars, int start, TimeSpan offset, DateFormatHandling format) inline static package
Definition at line 610 of file DateTimeUtils.cs.
        {
            chars[start++] = ((offset.Ticks >= 0L) ? '+' : '-');
            int num = Math.Abs(offset.Hours);
            DateTimeUtils.CopyIntToCharArray(chars, start, num, 2);
            start += 2;
            if (format == DateFormatHandling.IsoDateFormat)
            {
                chars[start++] = ':';
            }
            int num2 = Math.Abs(offset.Minutes);
            DateTimeUtils.CopyIntToCharArray(chars, start, num2, 2);
            start += 2;
            return start;
        }
References System.Math.Abs(), Newtonsoft.Json.Utilities.DateTimeUtils.CopyIntToCharArray(), System.format, System.L, System.offset, and System.start.
Referenced by Newtonsoft.Json.Utilities.DateTimeUtils.WriteDateTimeString().