Terraria Decompiled: Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTime
TryParseDateTime() [2/2]
static bool Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTime (StringReference s, DateTimeZoneHandling dateTimeZoneHandling, string dateFormatString, CultureInfo culture, out DateTime dt) inline static package
Definition at line 281 of file DateTimeUtils.cs.
        {
            if (s.Length > 0)
            {
                int startIndex = s.StartIndex;
                if (s[startIndex] == '/')
                {
                    if (s.Length >= 9 && s.StartsWith("/Date(") && s.EndsWith(")/") && DateTimeUtils.TryParseDateTimeMicrosoft(s, dateTimeZoneHandling, out dt))
                    {
                        return true;
                    }
                }
                else if (s.Length >= 19 && s.Length <= 40 && char.IsDigit(s[startIndex]) && s[startIndex + 10] == 'T' && DateTimeUtils.TryParseDateTimeIso(s, dateTimeZoneHandling, out dt))
                {
                    return true;
                }
                if (!string.IsNullOrEmpty(dateFormatString) && DateTimeUtils.TryParseDateTimeExact(s.ToString(), dateTimeZoneHandling, dateFormatString, culture, out dt))
                {
                    return true;
                }
            }
            dt = default(DateTime);
            return false;
        }
References System.culture, System.s, System.startIndex, Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTimeExact(), Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTimeIso(), and Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTimeMicrosoft().
Referenced by Newtonsoft.Json.JsonTextReader.ParseReadString(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(), and Newtonsoft.Json.JsonReader.ReadDateTimeString().