Terraria Decompiled: Newtonsoft.Json.Utilities.DateTimeUtils.TryReadOffset
TryReadOffset()
static bool Newtonsoft.Json.Utilities.DateTimeUtils.TryReadOffset (StringReference offsetText, int startIndex, out TimeSpan offset) inline static private
Definition at line 483 of file DateTimeUtils.cs.
        {
            bool flag = offsetText[startIndex] == '-';
            int num;
            if (ConvertUtils.Int32TryParse(offsetText.Chars, startIndex + 1, 2, out num) != ParseResult.Success)
            {
                offset = default(TimeSpan);
                return false;
            }
            int num2 = 0;
            if (offsetText.Length - startIndex > 5 && ConvertUtils.Int32TryParse(offsetText.Chars, startIndex + 3, 2, out num2) != ParseResult.Success)
            {
                offset = default(TimeSpan);
                return false;
            }
            offset = TimeSpan.FromHours((double)num) + TimeSpan.FromMinutes((double)num2);
            if (flag)
            {
                offset = offset.Negate();
            }
            return true;
        }
References Newtonsoft.Json.Utilities.StringReference.Chars, System.TimeSpan.FromHours(), System.TimeSpan.FromMinutes(), Newtonsoft.Json.Utilities.ConvertUtils.Int32TryParse(), Newtonsoft.Json.Utilities.StringReference.Length, System.TimeSpan.Negate(), System.offset, and System.startIndex.
Referenced by Newtonsoft.Json.Utilities.DateTimeUtils.TryParseMicrosoftDate().