Terraria Decompiled: Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTimeIso
TryParseDateTimeIso()
static bool Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTimeIso (StringReference text, DateTimeZoneHandling dateTimeZoneHandling, out DateTime dt) inline static package
Definition at line 152 of file DateTimeUtils.cs.
        {
            DateTimeParser dateTimeParser = default(DateTimeParser);
            if (!dateTimeParser.Parse(text.Chars, text.StartIndex, text.Length))
            {
                dt = default(DateTime);
                return false;
            }
            DateTime dateTime = DateTimeUtils.CreateDateTime(dateTimeParser);
            switch (dateTimeParser.Zone)
            {
            case ParserTimeZone.Utc:
                dateTime..ctor(dateTime.Ticks, 1);
                break;
            case ParserTimeZone.LocalWestOfUtc:
            {
                TimeSpan timeSpan;
                timeSpan..ctor(dateTimeParser.ZoneHour, dateTimeParser.ZoneMinute, 0);
                long num = dateTime.Ticks + timeSpan.Ticks;
                long num2 = num;
                DateTime dateTime2 = DateTime.MaxValue;
                if (num2 <= dateTime2.Ticks)
                {
                    dateTime = new DateTime(num, 1).ToLocalTime();
                }
                else
                {
                    num += dateTime.GetUtcOffset().Ticks;
                    long num3 = num;
                    dateTime2 = DateTime.MaxValue;
                    if (num3 > dateTime2.Ticks)
                    {
                        dateTime2 = DateTime.MaxValue;
                        num = dateTime2.Ticks;
                    }
                    dateTime..ctor(num, 2);
                }
                break;
            }
            case ParserTimeZone.LocalEastOfUtc:
            {
                TimeSpan timeSpan2;
                timeSpan2..ctor(dateTimeParser.ZoneHour, dateTimeParser.ZoneMinute, 0);
                long num = dateTime.Ticks - timeSpan2.Ticks;
                long num4 = num;
                DateTime dateTime2 = DateTime.MinValue;
                if (num4 >= dateTime2.Ticks)
                {
                    dateTime = new DateTime(num, 1).ToLocalTime();
                }
                else
                {
                    num += dateTime.GetUtcOffset().Ticks;
                    long num5 = num;
                    dateTime2 = DateTime.MinValue;
                    if (num5 < dateTime2.Ticks)
                    {
                        dateTime2 = DateTime.MinValue;
                        num = dateTime2.Ticks;
                    }
                    dateTime..ctor(num, 2);
                }
                break;
            }
            }
            dt = DateTimeUtils.EnsureDateTime(dateTime, dateTimeZoneHandling);
            return true;
        }
References Newtonsoft.Json.Utilities.DateTimeUtils.CreateDateTime(), Newtonsoft.Json.Utilities.DateTime, Newtonsoft.Json.Utilities.DateTimeUtils.EnsureDateTime(), System.DateTime.MaxValue, System.DateTime.MinValue, Newtonsoft.Json.Utilities.DateTimeParser.Parse(), System.text, System.DateTime.Ticks, System.TimeSpan.Ticks, System.DateTime.ToLocalTime(), Newtonsoft.Json.Utilities.DateTimeParser.Zone, Newtonsoft.Json.Utilities.DateTimeParser.ZoneHour, and Newtonsoft.Json.Utilities.DateTimeParser.ZoneMinute.
Referenced by Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTime().