Terraria Decompiled: Newtonsoft.Json.Utilities.DateTimeUtils.WriteDateTimeString
WriteDateTimeString() [1/2]
static int Newtonsoft.Json.Utilities.DateTimeUtils.WriteDateTimeString (char[] chars, int start, DateTime value, TimeSpan? offset, DateTimeKind kind, DateFormatHandling format) inline static package
Definition at line 520 of file DateTimeUtils.cs.
        {
            int num2;
            if (format == DateFormatHandling.MicrosoftDateFormat)
            {
                TimeSpan timeSpan = offset ?? value.GetUtcOffset();
                long num = DateTimeUtils.ConvertDateTimeToJavaScriptTicks(value, timeSpan);
                "\\/Date(".CopyTo(0, chars, start, 7);
                num2 = start + 7;
                string text = num.ToString(CultureInfo.InvariantCulture);
                text.CopyTo(0, chars, num2, text.Length);
                num2 += text.Length;
                if (kind != null)
                {
                    if (kind == 2)
                    {
                        num2 = DateTimeUtils.WriteDateTimeOffset(chars, num2, timeSpan, format);
                    }
                }
                else if (value != DateTime.MaxValue && value != DateTime.MinValue)
                {
                    num2 = DateTimeUtils.WriteDateTimeOffset(chars, num2, timeSpan, format);
                }
                ")\\/".CopyTo(0, chars, num2, 3);
                num2 += 3;
            }
            else
            {
                num2 = DateTimeUtils.WriteDefaultIsoDate(chars, start, value);
                if (kind != 1)
                {
                    if (kind == 2)
                    {
                        num2 = DateTimeUtils.WriteDateTimeOffset(chars, num2, offset ?? value.GetUtcOffset(), format);
                    }
                }
                else
                {
                    chars[num2++] = 'Z';
                }
            }
            return num2;
        }
References Newtonsoft.Json.Utilities.DateTimeUtils.ConvertDateTimeToJavaScriptTicks(), System.format, System.Globalization.CultureInfo.InvariantCulture, System.DateTime.MaxValue, System.DateTime.MinValue, System.offset, System.start, System.text, System.value, Newtonsoft.Json.Utilities.DateTimeUtils.WriteDateTimeOffset(), and Newtonsoft.Json.Utilities.DateTimeUtils.WriteDefaultIsoDate().