Terraria Decompiled: Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTimeOffsetIso
TryParseDateTimeOffsetIso()
static bool Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTimeOffsetIso (StringReference text, out DateTimeOffset dt) inline static package
Definition at line 222 of file DateTimeUtils.cs.
        {
            DateTimeParser dateTimeParser = default(DateTimeParser);
            if (!dateTimeParser.Parse(text.Chars, text.StartIndex, text.Length))
            {
                dt = default(DateTimeOffset);
                return false;
            }
            DateTime dateTime = DateTimeUtils.CreateDateTime(dateTimeParser);
            TimeSpan utcOffset;
            switch (dateTimeParser.Zone)
            {
            case ParserTimeZone.Utc:
                utcOffset..ctor(0L);
                break;
            case ParserTimeZone.LocalWestOfUtc:
                utcOffset..ctor(-dateTimeParser.ZoneHour, -dateTimeParser.ZoneMinute, 0);
                break;
            case ParserTimeZone.LocalEastOfUtc:
                utcOffset..ctor(dateTimeParser.ZoneHour, dateTimeParser.ZoneMinute, 0);
                break;
            default:
                utcOffset = TimeZoneInfo.Local.GetUtcOffset(dateTime);
                break;
            }
            long num = dateTime.Ticks - utcOffset.Ticks;
            if (num < 0L || num > 3155378975999999999L)
            {
                dt = default(DateTimeOffset);
                return false;
            }
            dt = new DateTimeOffset(dateTime, utcOffset);
            return true;
        }
References Newtonsoft.Json.Utilities.DateTimeUtils.CreateDateTime(), Newtonsoft.Json.Utilities.DateTimeOffset, System.TimeZoneInfo.GetUtcOffset(), System.L, System.TimeZoneInfo.Local, Newtonsoft.Json.Utilities.DateTimeParser.Parse(), System.text, System.TimeSpan.Ticks, Newtonsoft.Json.Utilities.DateTimeParser.Zone, Newtonsoft.Json.Utilities.DateTimeParser.ZoneHour, and Newtonsoft.Json.Utilities.DateTimeParser.ZoneMinute.
Referenced by Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTimeOffset(), and Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTimeOffset().