Terraria Decompiled: System.Globalization.DateTimeFormatInfo.GetInstance
GetInstance()
static DateTimeFormatInfo System.Globalization.DateTimeFormatInfo.GetInstance (IFormatProvider provider) inline static
Definition at line 209 of file DateTimeFormatInfo.cs.
        {
            if (provider == null)
            {
                return DateTimeFormatInfo.CurrentInfo;
            }
            CultureInfo cultureInfo = provider as CultureInfo;
            if (cultureInfo != null && !cultureInfo._isInherited)
            {
                return cultureInfo.DateTimeFormat;
            }
            DateTimeFormatInfo dateTimeFormatInfo = provider as DateTimeFormatInfo;
            if (dateTimeFormatInfo != null)
            {
                return dateTimeFormatInfo;
            }
            DateTimeFormatInfo dateTimeFormatInfo2 = provider.GetFormat(typeof(DateTimeFormatInfo)) as DateTimeFormatInfo;
            if (dateTimeFormatInfo2 == null)
            {
                return DateTimeFormatInfo.CurrentInfo;
            }
            return dateTimeFormatInfo2;
        }
References System.Globalization.CultureInfo._isInherited, System.Globalization.DateTimeFormatInfo.CurrentInfo, System.Globalization.CultureInfo.DateTimeFormat, System.Globalization.DateTimeFormatInfo.DateTimeFormatInfo(), and System.IFormatProvider.GetFormat().
Referenced by System.DateTimeFormat.Format(), System.Globalization.TimeSpanFormat.FormatToBuilder(), System.DateTime.GetDateTimeFormats(), System.DateTime.GetDateTimeFormats(), System.DateTimeOffset.Parse(), System.DateTime.Parse(), System.DateTimeOffset.Parse(), System.DateTime.Parse(), System.DateTime.Parse(), System.DateTimeOffset.ParseExact(), System.DateTimeOffset.ParseExact(), System.DateTime.ParseExact(), System.DateTime.ParseExact(), System.DateTimeOffset.ParseExact(), System.DateTimeOffset.ParseExact(), System.DateTime.ParseExact(), System.DateTime.ParseExact(), System.DateTime.ParseExact(), System.DateTimeFormat.TryFormat(), System.DateTimeOffset.TryParse(), System.DateTime.TryParse(), System.DateTimeOffset.TryParse(), System.DateTime.TryParse(), System.DateTimeOffset.TryParseExact(), System.DateTimeOffset.TryParseExact(), System.DateTime.TryParseExact(), System.DateTime.TryParseExact(), System.DateTimeOffset.TryParseExact(), System.DateTimeOffset.TryParseExact(), System.DateTime.TryParseExact(), System.DateTime.TryParseExact(), and System.Globalization.TimeSpanParse.TryParseTimeSpan().