Terraria Decompiled: Terraria.Graphics.VertexStrip.DrawTrail
DrawTrail()
void Terraria.Graphics.VertexStrip.DrawTrail () inline
Definition at line 198 of file VertexStrip.cs.
        {
            if (this._vertexAmountCurrentlyMaintained < 3)
            {
                return;
            }
            GraphicsDevice graphicsDevice = Main.instance.GraphicsDevice;
            VertexBufferBinding[] vertexBuffers = graphicsDevice.GetVertexBuffers();
            IndexBuffer indices = graphicsDevice.Indices;
            graphicsDevice.DrawUserIndexedPrimitives<VertexStrip.CustomVertexInfo>(PrimitiveType.TriangleList, this._vertices, 0, this._vertexAmountCurrentlyMaintained, this._indices, 0, this._indicesAmountCurrentlyMaintained / 3);
            graphicsDevice.SetVertexBuffers(vertexBuffers);
            graphicsDevice.Indices = indices;
        }
References Terraria.Graphics.VertexStrip._indices, Terraria.Graphics.VertexStrip._vertexAmountCurrentlyMaintained, Terraria.Graphics.VertexStrip._vertices, Microsoft.Xna.Framework.Graphics.GraphicsDevice.GetVertexBuffers(), Microsoft.Xna.Framework.Game.GraphicsDevice, Microsoft.Xna.Framework.Graphics.GraphicsDevice.Indices, Terraria.Main.instance, and Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetVertexBuffers().
Referenced by Terraria.Graphics.EmpressBladeDrawer.Draw(), Terraria.Graphics.FinalFractalHelper.Draw(), Terraria.Graphics.FlameLashDrawer.Draw(), Terraria.Graphics.LightDiscDrawer.Draw(), Terraria.Graphics.MagicMissileDrawer.Draw(), Terraria.Graphics.RainbowRodDrawer.Draw(), Terraria.Graphics.StormLightningDrawer.Draw(), Terraria.GameContent.Skies.AuroraSky.DrawAuroraSky(), and Terraria.GameContent.UI.States.UIWorldCreation.DrawSpecialSeedRing().