Terraria Decompiled: Terraria.Graphics.VertexStrip.AddVertexPair
AddVertexPair() [4/4]
void Terraria.Graphics.VertexStrip.AddVertexPair (VertexStrip::StripColorFunction colorFunction, VertexStrip::StripHalfWidthFunction widthFunction, Vector2 pos, float rot, float progressOnStrip) inline
Definition at line 137 of file VertexStrip.cs.
        {
            Color color = colorFunction(progressOnStrip);
            float num = widthFunction(progressOnStrip);
            Vector2 vector = MathHelper.WrapAngle(rot - 1.5707964f).ToRotationVector2() * num;
            this.AddVertexPair(pos + vector, pos - vector, progressOnStrip, color);
        }
References Terraria.Graphics.VertexStrip.AddVertexPair(), and Microsoft.Xna.Framework.MathHelper.WrapAngle().
Referenced by Terraria.Graphics.VertexStrip.AddVertexPair(), Terraria.GameContent.Skies.AuroraSky.DrawAuroraSky(), Terraria.GameContent.UI.States.UIWorldCreation.DrawSpecialSeedRing(), Terraria.Graphics.VertexStrip.PrepareStrip(), and Terraria.Graphics.VertexStrip.PrepareStripWithProceduralPadding().