Terraria Decompiled: Terraria.Graphics.VertexStrip.PrepareStripWithProceduralPadding
PrepareStripWithProceduralPadding()
void Terraria.Graphics.VertexStrip.PrepareStripWithProceduralPadding (Vector2[] positions, float[] rotations, VertexStrip::StripColorFunction colorFunction, VertexStrip::StripHalfWidthFunction widthFunction, Vector2 offsetForAllPositions = default(Vector2), bool includeBacksides = false, bool tryStoppingOddBug = true) inline
Definition at line 46 of file VertexStrip.cs.
        {
            this._temporaryPositionsCache.Clear();
            this._temporaryRotationsCache.Clear();
            int num = 0;
            while (num < positions.Length && !(positions[num] == Vector2.Zero))
            {
                Vector2 vector = positions[num];
                float num2 = MathHelper.WrapAngle(rotations[num]);
                this._temporaryPositionsCache.Add(vector);
                this._temporaryRotationsCache.Add(num2);
                if (num + 1 < positions.Length && positions[num + 1] != Vector2.Zero)
                {
                    Vector2 vector2 = positions[num + 1];
                    float num3 = MathHelper.WrapAngle(rotations[num + 1]);
                    int num4 = (int)(Math.Abs(MathHelper.WrapAngle(num3 - num2)) / 0.2617994f);
                    if (num4 != 0)
                    {
                        float num5 = vector.Distance(vector2);
                        Vector2 vector3 = vector + num2.ToRotationVector2() * num5;
                        Vector2 vector4 = vector2 + num3.ToRotationVector2() * -num5;
                        int num6 = num4 + 2;
                        float num7 = 1f / (float)num6;
                        Vector2 vector5 = vector;
                        for (float num8 = num7; num8 < 1f; num8 += num7)
{
                            Vector2 vector6 = Vector2.CatmullRom(vector3, vector, vector2, vector4, num8);
                            float num9 = MathHelper.WrapAngle(vector6.DirectionTo(vector5).ToRotation());
                            if (float.IsNaN(num9))
{
                                num9 = this._temporaryRotationsCache.Last<float>();
                            }
                            this._temporaryPositionsCache.Add(vector6);
                            this._temporaryRotationsCache.Add(num9);
                            vector5 = vector6;
                        }
                    }
                }
                num++;
            }
            this.Reset(this._temporaryPositionsCache.Count * 2);
            int count = this._temporaryPositionsCache.Count;
            Vector2 zero = Vector2.Zero;
            int num10 = 0;
            while (num10 < count && (!tryStoppingOddBug || !(this._temporaryPositionsCache[num10] == zero)))
            {
                Vector2 vector7 = this._temporaryPositionsCache[num10] + offsetForAllPositions;
                float num11 = this._temporaryRotationsCache[num10];
                float num12 = (float)num10 / (float)(count - 1);
                this.AddVertexPair(colorFunction, widthFunction, vector7, num11, num12);
                num10++;
            }
            this.PrepareIndices(includeBacksides);
        }
References Terraria.Graphics.VertexStrip._temporaryPositionsCache, Terraria.Graphics.VertexStrip._temporaryRotationsCache, System.Math.Abs(), System.Collections.Generic.List< T >.Add(), Terraria.Graphics.VertexStrip.AddVertexPair(), Microsoft.Xna.Framework.Vector2.CatmullRom(), System.Collections.Generic.List< T >.Clear(), System.Collections.Generic.List< T >.Count, System.count, Microsoft.Xna.Framework.Vector2.Distance(), int, Microsoft.Xna.Framework.Vector2.Length(), Terraria.Graphics.VertexStrip.PrepareIndices(), Terraria.Graphics.VertexStrip.Reset(), Microsoft.Xna.Framework.MathHelper.WrapAngle(), and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.Graphics.FlameLashDrawer.Draw(), Terraria.Graphics.LightDiscDrawer.Draw(), Terraria.Graphics.MagicMissileDrawer.Draw(), and Terraria.Graphics.RainbowRodDrawer.Draw().