Terraria Decompiled: Terraria.Graphics.VertexStrip.PrepareStrip
PrepareStrip()
void Terraria.Graphics.VertexStrip.PrepareStrip (Vector2[] positions, float[] rotations, VertexStrip::StripColorFunction colorFunction, VertexStrip::StripHalfWidthFunction widthFunction, Vector2 offsetForAllPositions = default(Vector2), int? expectedVertexPairsAmount = null, bool includeBacksides = false) inline
Definition at line 24 of file VertexStrip.cs.
        {
            int num = positions.Length;
            this.Reset(num * 2);
            int num2 = num;
            if (expectedVertexPairsAmount != null)
            {
                num2 = expectedVertexPairsAmount.Value;
            }
            int num3 = 0;
            while (num3 < num && !(positions[num3] == Vector2.Zero))
            {
                Vector2 vector = positions[num3] + offsetForAllPositions;
                float num4 = MathHelper.WrapAngle(rotations[num3]);
                float num5 = (float)num3 / (float)(num2 - 1);
                this.AddVertexPair(colorFunction, widthFunction, vector, num4, num5);
                num3++;
            }
            this.PrepareIndices(includeBacksides);
        }
References Terraria.Graphics.VertexStrip.AddVertexPair(), Microsoft.Xna.Framework.Vector2.Length(), Terraria.Graphics.VertexStrip.PrepareIndices(), Terraria.Graphics.VertexStrip.Reset(), Microsoft.Xna.Framework.MathHelper.WrapAngle(), and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.Graphics.EmpressBladeDrawer.Draw(), Terraria.Graphics.FinalFractalHelper.Draw(), and Terraria.Graphics.StormLightningDrawer.Draw().