Terraria Decompiled: Steamworks.Callback.Dispose
Dispose()
void Steamworks.Callback< T >.Dispose () inline
Implements System.IDisposable.
Definition at line 70 of file Callback.2.cs.
        {
            if (this.m_bDisposed)
            {
                return;
            }
            GC.SuppressFinalize(this);
            if (this.m_bIsRegistered)
            {
                this.Unregister();
            }
            this.m_bDisposed = true;
        }
References Steamworks.Callback< T >.m_bDisposed, Steamworks.Callback< T >.m_bIsRegistered, System.GC.SuppressFinalize(), and Steamworks.Callback< T >.Unregister().
Referenced by Steamworks.Callback< T >.~Callback().