Terraria Decompiled: System.Runtime.Serialization.SerializationEvents.GetMethodsWithAttribute
GetMethodsWithAttribute()
List< MethodInfo > System.Runtime.Serialization.SerializationEvents.GetMethodsWithAttribute (Type attribute, Type t) inline private
Definition at line 20 of file SerializationEvents.cs.
        {
            List<MethodInfo> list = null;
            Type type = t;
            while (type != null && type != typeof(object))
            {
                foreach (MethodInfo methodInfo in type.GetMethods(BindingFlags.DeclaredOnly | BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic))
                {
                    if (methodInfo.IsDefined(attribute, false))
                    {
                        if (list == null)
{
                            list = new List<MethodInfo>();
                        }
                        list.Add(methodInfo);
                    }
                }
                type = type.BaseType;
            }
            if (list != null)
            {
                list.Reverse();
            }
            return list;
        }
References System.Type.BaseType, System.Type.GetMethods(), System.Runtime.InteropServices._MethodInfo.IsDefined(), and System.list.
Referenced by System.Runtime.Serialization.SerializationEvents.SerializationEvents().