Terraria Decompiled: ReLogic.OS.Windows.WindowsMouseNotifier.HasMouseAttached
HasMouseAttached()
bool ReLogic.OS.Windows.WindowsMouseNotifier.HasMouseAttached () inline private
Definition at line 72 of file WindowsMouseNotifier.cs.
        {
            uint num = 0U;
            NativeMethods.GetRawInputDeviceList(null, ref num, (uint)Marshal.SizeOf(typeof(NativeMethods.RAWINPUTDEVICELIST)));
            NativeMethods.RAWINPUTDEVICELIST[] array = new NativeMethods.RAWINPUTDEVICELIST[num];
            NativeMethods.GetRawInputDeviceList(array, ref num, (uint)Marshal.SizeOf(typeof(NativeMethods.RAWINPUTDEVICELIST)));
            bool flag = false;
            NativeMethods.RAWINPUTDEVICELIST[] array2 = array;
            for (int i = 0; i < array2.Length; i++)
            {
                if (array2[i].dwType == 0U)
                {
                    flag = true;
                    break;
                }
            }
            return flag;
        }
References System.array, ReLogic.OS.Windows.NativeMethods.GetRawInputDeviceList(), System.Runtime.InteropServices.Marshal.SizeOf(), and System.U.
Referenced by ReLogic.OS.Windows.WindowsMouseNotifier.PreFilterMessage().