Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.Halls.SineDungeonHall.SineHall
SineHall()
void Terraria.GameContent.Generation.Dungeon.Halls.SineDungeonHall.SineHall (DungeonData data, Vector2D startPoint, Vector2D endPoint, bool generating = false) inline
Definition at line 58 of file SineDungeonHall.cs.
        {
            SineDungeonHallSettings sineDungeonHallSettings = (SineDungeonHallSettings)this.settings;
            UnifiedRandom unifiedRandom = new UnifiedRandom(sineDungeonHallSettings.RandomSeed);
            ushort brickTileType = this.settings.StyleData.BrickTileType;
            ushort brickCrackedTileType = this.settings.StyleData.BrickCrackedTileType;
            ushort brickWallType = this.settings.StyleData.BrickWallType;
            Vector2D vector2D = startPoint;
            bool flag = false;
            if (sineDungeonHallSettings.CrackedBrickChance > 0.0)
            {
                flag = unifiedRandom.NextDouble() <= sineDungeonHallSettings.CrackedBrickChance;
            }
            int num = 3;
            int num2 = 8;
            int num3 = num + num2;
            Vector2D vector2D2 = endPoint - startPoint;
            Vector2D vector2D3 = vector2D2.SafeNormalize(Vector2D.UnitX);
            int i = (int)Math.Ceiling(vector2D2.Length() / vector2D3.Length());
            int num4 = i;
            this.Bounds.SetBounds((int)startPoint.X, (int)startPoint.Y, (int)startPoint.X, (int)startPoint.Y);
            DungeonRoomSearchSettings dungeonRoomSearchSettings = new DungeonRoomSearchSettings
            {
                Fluff = (int)((float)num * sineDungeonHallSettings.Magnitude) + num2
            };
            List<DungeonRoom> allRoomsInSpots = DungeonUtils.GetAllRoomsInSpots(data.dungeonRooms, startPoint, endPoint, dungeonRoomSearchSettings);
            Vector2D vector2D4 = vector2D3;
            Vector2D vector2D5 = (Vector2.UnitY * sineDungeonHallSettings.Magnitude).ToVector2D();
            vector2D5 = vector2D5.ToVector2().RotatedBy(vector2D4.ToRotation(), Vector2.Zero).ToVector2D();
            float num5 = 0f;
            float num6 = 0f;
            float num7 = (float)sineDungeonHallSettings.Iterations / (float)num4 * 6.2831855f;
            while (i > 0)
            {
                Vector2D vector2D6 = vector2D5 * (double)((float)Math.Sin((double)num6));
                Vector2D vector2D7 = (sineDungeonHallSettings.FlipSine ? (vector2D - vector2D6) : (vector2D + vector2D6));
                if (!WorldGen.InWorld((int)(vector2D7.X + vector2D3.X), (int)(vector2D7.Y + vector2D3.Y), 10))
                {
                    break;
                }
                if (!base.Processed)
                {
                    data.dungeonBounds.UpdateBounds((int)vector2D7.X - num3, (int)vector2D7.Y - num3, (int)vector2D7.Y + num3, (int)vector2D7.Y + num3);
                    this.Bounds.UpdateBounds((int)vector2D7.X - num3, (int)vector2D7.Y - num3, (int)vector2D7.Y + num3, (int)vector2D7.Y + num3);
                }
                if (generating)
                {
                    base.GenerateDungeonSquareHall(data, allRoomsInSpots, vector2D7, brickTileType, brickCrackedTileType, brickWallType, num, num2, sineDungeonHallSettings.PlaceOverProtectedBricks, flag, false);
                }
                vector2D += vector2D3;
                num5 += num7;
                num6 += num7;
                if (num5 >= 0.5f)
                {
                    num5 = 0f;
                    this.PotentialPlatformPoints.Add(new Tuple<Vector2D, Vector2D>(vector2D, vector2D6));
                }
                i--;
            }
            data.genVars.generatingDungeonPositionX = (int)endPoint.X;
            data.genVars.generatingDungeonPositionY = (int)endPoint.Y;
            this.StartPosition = startPoint;
            this.EndPosition = endPoint;
            this.StartDirection = new Vector2D(vector2D4.X, vector2D4.Y);
            this.EndDirection = new Vector2D(vector2D3.X, vector2D3.Y);
            this.CrackedBrick = flag;
            this.Bounds.CalculateHitbox();
        }
References System.Collections.Generic.List< T >.Add(), Terraria.GameContent.Generation.Dungeon.Halls.DungeonHall.Bounds, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.BrickCrackedTileType, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.BrickTileType, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.BrickWallType, Terraria.GameContent.Generation.Dungeon.DungeonBounds.CalculateHitbox(), System.Math.Ceiling(), Terraria.GameContent.Generation.Dungeon.Halls.DungeonHallSettings.CrackedBrickChance, Terraria.GameContent.Generation.Dungeon.DungeonData.dungeonBounds, Terraria.GameContent.Generation.Dungeon.DungeonData.dungeonRooms, Terraria.GameContent.Generation.Dungeon.DungeonUtils.GetAllRoomsInSpots(), int, Terraria.WorldGen.InWorld(), Terraria.GameContent.Generation.Dungeon.Halls.SineDungeonHallSettings.Iterations, ReLogic.Utilities.Vector2D.Length(), Terraria.GameContent.Generation.Dungeon.Halls.SineDungeonHallSettings.Magnitude, Terraria.Utilities.UnifiedRandom.NextDouble(), Terraria.GameContent.Generation.Dungeon.Halls.DungeonHallSettings.PlaceOverProtectedBricks, Terraria.GameContent.Generation.Dungeon.Halls.SineDungeonHall.PotentialPlatformPoints, Terraria.GameContent.Generation.Dungeon.Halls.DungeonHallSettings.RandomSeed, Terraria.GameContent.Generation.Dungeon.DungeonBounds.SetBounds(), Terraria.GameContent.Generation.Dungeon.Halls.DungeonHall.settings, System.Math.Sin(), Terraria.GameContent.Generation.Dungeon.Halls.DungeonHallSettings.StyleData, ReLogic.Utilities.Vector2D.UnitX, Terraria.GameContent.Generation.Dungeon.DungeonBounds.UpdateBounds(), ReLogic.Utilities.Vector2D.X, ReLogic.Utilities.Vector2D.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.Generation.Dungeon.Halls.SineDungeonHall.CalculateHall(), and Terraria.GameContent.Generation.Dungeon.Halls.SineDungeonHall.GenerateHall().