Terraria Decompiled: System.Collections.Generic.Queue.SetCapacity
SetCapacity()
void System.Collections.Generic.Queue< T >.SetCapacity (int capacity) inline private
Definition at line 311 of file Queue.cs.
        {
            T[] array = new T[capacity];
            if (this._size > 0)
            {
                if (this._head < this._tail)
                {
                    Array.Copy(this._array, this._head, array, 0, this._size);
                }
                else
                {
                    Array.Copy(this._array, this._head, array, 0, this._array.Length - this._head);
                    Array.Copy(this._array, 0, array, this._array.Length - this._head, this._tail);
                }
            }
            this._array = array;
            this._head = 0;
            this._tail = ((this._size == capacity) ? 0 : this._size);
            this._version++;
        }
References System.Collections.Generic.Queue< T >._array, System.Collections.Generic.Queue< T >._head, System.Collections.Generic.Queue< T >._size, System.Collections.Generic.Queue< T >._tail, System.Collections.Generic.Queue< T >._version, System.array, System.capacity, and System.Array.Copy().
Referenced by System.Collections.Generic.Queue< T >.Enqueue(), and System.Collections.Generic.Queue< T >.TrimExcess().