Terraria Decompiled: System.Collections.Generic.Queue.Enqueue
Enqueue()
void System.Collections.Generic.Queue< T >.Enqueue (T item) inline
Definition at line 178 of file Queue.cs.
        {
            if (this._size == this._array.Length)
            {
                int num = (int)((long)this._array.Length * 200L / 100L);
                if (num < this._array.Length + 4)
                {
                    num = this._array.Length + 4;
                }
                this.SetCapacity(num);
            }
            this._array[this._tail] = item;
            this.MoveNext(ref this._tail);
            this._size++;
            this._version++;
        }
References System.Collections.Generic.Queue< T >._array, System.Collections.Generic.Queue< T >._size, System.Collections.Generic.Queue< T >._tail, System.Collections.Generic.Queue< T >._version, int, System.item, System.L, System.Collections.Generic.Queue< T >.MoveNext(), and System.Collections.Generic.Queue< T >.SetCapacity().
Referenced by NVorbis.Ogg.ForwardOnlyPacketProvider.AddPage(), Terraria.Wiring.CheckLogicGate(), Terraria.Social.Steam.SteamP2PReader.ClearUser(), Terraria.Social.WeGame.WeGameP2PReader.ClearUser(), Terraria.Social.WeGame.WeGameP2PWriter.ClearUser(), Terraria.Wiring.HitWireSingle(), System.IO.Enumeration.FileSystemEnumerator< TResult >.MoveNext(), Terraria.TimeLogger.OnNextFrame(), Terraria.Wiring.PokeLogicGate(), Terraria.Social.Steam.SteamP2PReader.ReadTick(), Terraria.Social.WeGame.WeGameP2PReader.ReadTick(), Terraria.Social.Steam.SteamP2PReader.Receive(), Terraria.Social.WeGame.WeGameP2PReader.Receive(), Terraria.ID.SetFactory.Recycle< T >(), Terraria.Net.LegacyNetBufferPool.ReturnBuffer(), Terraria.Social.WeGame.WeGameP2PWriter.SendAll(), Terraria.WorldGen.SpawnFallingBlockProjectile(), and Newtonsoft.Json.Serialization.MemoryTraceWriter.Trace().