Terraria Decompiled: System.Collections.Generic.Queue.Dequeue
Dequeue()
T System.Collections.Generic.Queue< T >.Dequeue () inline
Definition at line 214 of file Queue.cs.
        {
            int head = this._head;
            T[] array = this._array;
            if (this._size == 0)
            {
                this.ThrowForEmptyQueue();
            }
            T t = array[head];
            if (RuntimeHelpers.IsReferenceOrContainsReferences<T>())
            {
                array[head] = default(T);
            }
            this.MoveNext(ref this._head);
            this._size--;
            this._version++;
            return t;
        }
References System.Collections.Generic.Queue< T >._array, System.Collections.Generic.Queue< T >._head, System.Collections.Generic.Queue< T >._size, System.Collections.Generic.Queue< T >._version, System.array, System.Collections.Generic.Queue< T >.MoveNext(), and System.Collections.Generic.Queue< T >.ThrowForEmptyQueue().
Referenced by Terraria.WorldGen.CheckExploitDestroyQueue(), System.IO.Enumeration.FileSystemEnumerator< TResult >.DequeueNextDirectory(), Terraria.ID.SetFactory.GetBoolBuffer(), Terraria.ID.SetFactory.GetFloatBuffer(), Terraria.ID.SetFactory.GetIntBuffer(), Terraria.ID.SetFactory.GetUshortBuffer(), Terraria.Wiring.LogicGatePass(), Terraria.Social.WeGame.WeGameP2PWriter.QueueSend(), NVorbis.Ogg.ForwardOnlyPacketProvider.ReadNextPage(), Terraria.Social.Steam.SteamP2PReader.ReadTick(), Terraria.Social.WeGame.WeGameP2PReader.ReadTick(), Terraria.Net.LegacyNetBufferPool.RequestBuffer(), Terraria.TimeLogger.StartNextFrame(), and Newtonsoft.Json.Serialization.MemoryTraceWriter.Trace().