Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalGroundFurniture.GroundFurniture
GroundFurniture()
void Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalGroundFurniture.GroundFurniture (DungeonData data) inline
Definition at line 194 of file DungeonGlobalGroundFurniture.cs.
        {
            UnifiedRandom genRand = WorldGen.genRand;
            ushort num = (ushort)data.wallVariants[0];
            float num2 = (float)Main.maxTilesX / 4200f;
            int num3 = (int)((double)(2000f * num2) * data.globalFeatureScalar);
            int num4 = (int)((double)(1f + (float)((int)num2)) * data.globalFeatureScalar);
            int num5 = (int)((double)(1f + (float)((int)num2)) * data.globalFeatureScalar);
            bool flag = false;
            for (int i = 0; i < data.genVars.dungeonGenerationStyles.Count; i++)
            {
                if (data.genVars.dungeonGenerationStyles[i].Style == 0)
                {
                    flag = true;
                    break;
                }
            }
            if (!flag)
            {
                num4 = 0;
                num5 = 0;
            }
            int num6 = -1;
            if (data.Type == DungeonType.DualDungeon)
            {
                switch (WorldGen.GetWorldSize())
                {
                default:
                    num6 = 5;
                    break;
                case 1:
                    num6 = 10;
                    break;
                case 2:
                    num6 = 15;
                    break;
                }
            }
            int num7 = 2000;
            for (int j = 0; j < num3; j++)
            {
                if (num4 > 0 || num5 > 0)
                {
                    j--;
                    num7--;
                    if (num7 <= 0)
                    {
                        break;
                    }
                }
                int num8 = genRand.Next(data.dungeonBounds.Left, data.dungeonBounds.Right);
                int num9 = genRand.Next(Math.Max(data.dungeonBounds.Top, (int)Main.worldSurface + 10), data.dungeonBounds.Bottom);
                int num10 = 1000;
                while (!DungeonUtils.IsConsideredDungeonWall((int)Main.tile[num8, num9].wall, false) || Main.tile[num8, num9].active())
                {
                    num10--;
                    if (num10 <= 0)
                    {
                        break;
                    }
                    num8 = genRand.Next(data.dungeonBounds.Left, data.dungeonBounds.Right);
                    num9 = genRand.Next(Math.Max(data.dungeonBounds.Top, (int)Main.worldSurface + 10), data.dungeonBounds.Bottom);
                }
                if (DungeonUtils.IsConsideredDungeonWall((int)Main.tile[num8, num9].wall, false))
                {
                    if (!Main.tile[num8, num9].active())
                    {
                        while (!WorldGen.SolidTile(num8, num9, false) && num9 < Main.UnderworldLayer)
{
                            num9++;
                        }
                        num9--;
                        this.GroundFurniture_ActuallyGenerateFurniture(data, genRand, num8, num9, num, ref num4, ref num5, ref num6, j < num3 / 2, false);
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.Bottom, Terraria.GameContent.Generation.Dungeon.DungeonData.dungeonBounds, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.dungeonGenerationStyles, Terraria.WorldGen.genRand, Terraria.GameContent.Generation.Dungeon.DungeonData.genVars, Terraria.WorldGen.GetWorldSize(), Terraria.GameContent.Generation.Dungeon.DungeonData.globalFeatureScalar, Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalGroundFurniture.GroundFurniture_ActuallyGenerateFurniture(), int, Terraria.GameContent.Generation.Dungeon.DungeonUtils.IsConsideredDungeonWall(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.Left, System.Math.Max(), Terraria.Main.maxTilesX, Terraria.Utilities.UnifiedRandom.Next(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.Right, Terraria.WorldGen.SolidTile(), Terraria.Main.tile, Terraria.GameContent.Generation.Dungeon.DungeonBounds.Top, Terraria.GameContent.Generation.Dungeon.DungeonData.Type, Terraria.Main.UnderworldLayer, Terraria.Tile.wall, and Terraria.GameContent.Generation.Dungeon.DungeonData.wallVariants.
Referenced by Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalGroundFurniture.GenerateFeature().