Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalGroundFurniture.GroundFurniture_DualDungeons
GroundFurniture_DualDungeons()
void Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalGroundFurniture.GroundFurniture_DualDungeons (DungeonData data) inline
Definition at line 38 of file DungeonGlobalGroundFurniture.cs.
        {
            UnifiedRandom genRand = WorldGen.genRand;
            float num = (float)Main.maxTilesX / 4200f;
            int num2 = (int)((double)(1f + (float)((int)num)) * data.globalFeatureScalar);
            int num3 = (int)((double)(1f + (float)((int)num)) * data.globalFeatureScalar);
            bool flag = false;
            for (int i = 0; i < data.genVars.dungeonGenerationStyles.Count; i++)
            {
                if (data.genVars.dungeonGenerationStyles[i].Style == 0)
                {
                    flag = true;
                    break;
                }
            }
            if (!flag)
            {
                num2 = 0;
                num3 = 0;
            }
            int num4 = -1;
            if (data.Type == DungeonType.DualDungeon)
            {
                switch (WorldGen.GetWorldSize())
                {
                default:
                    num4 = 5;
                    break;
                case 1:
                    num4 = 10;
                    break;
                case 2:
                    num4 = 15;
                    break;
                }
            }
            int num5 = 4;
            int num6 = 6;
            int num7 = 0;
            for (int j = 0; j < data.dungeonRooms.Count; j++)
            {
                DungeonRoom dungeonRoom = data.dungeonRooms[j];
                if (dungeonRoom.generated)
                {
                    DungeonGenerationStyleData styleData = dungeonRoom.settings.StyleData;
                    DungeonBounds innerBounds = dungeonRoom.InnerBounds;
                    int k = dungeonRoom.GetFurnitureCount(num5);
                    bool flag2 = styleData.Style == 0 && (num2 > 0 || num3 > 0);
                    int num8 = 50;
                    while (k > 0)
                    {
                        num8--;
                        if (num8 <= 0)
{
                            break;
                        }
                        Point point = innerBounds.RandomPointInBounds(genRand);
                        Tile tile = Main.tile[point.X, point.Y];
                        if (DungeonUtils.IsConsideredDungeonWall((int)tile.wall, false) && !tile.active())
{
                            point = DungeonUtils.FirstSolid(false, point, null);
                            point.Y--;
                            tile = Main.tile[point.X, point.Y];
                            int num9 = num2;
                            int num10 = num3;
                            int num11 = 0;
                            bool flag3;
                            if (flag2)
{
                                flag3 = this.GroundFurniture_ActuallyGenerateFurniture(data, genRand, point.X, point.Y, tile.wall, ref num2, ref num3, ref num4, true, false);
                                if (!flag3)
{
                                    flag3 = this.GroundFurniture_ActuallyGenerateFurniture(data, genRand, point.X, point.Y, tile.wall, ref num11, ref num11, ref num4, false, num8 > 25);
                                }
                            }
                            else
{
                                flag3 = this.GroundFurniture_ActuallyGenerateFurniture(data, genRand, point.X, point.Y, tile.wall, ref num11, ref num11, ref num4, false, num8 > 25);
                                if (!flag3)
{
                                    flag3 = this.GroundFurniture_ActuallyGenerateFurniture(data, genRand, point.X, point.Y, tile.wall, ref num11, ref num11, ref num4, false, num8 > 25);
                                }
                            }
                            if ((flag2 && num9 != num2) || num10 != num3)
{
                                flag2 = false;
                            }
                            if (flag3)
{
                                k--;
                                num7++;
                            }
                        }
                    }
                }
            }
            for (int l = 0; l < data.dungeonHalls.Count; l++)
            {
                DungeonHall dungeonHall = data.dungeonHalls[l];
                if (dungeonHall.generated)
                {
                    DungeonGenerationStyleData styleData2 = dungeonHall.settings.StyleData;
                    DungeonBounds bounds = dungeonHall.Bounds;
                    int m = dungeonHall.GetFurnitureCount(num6);
                    bool flag4 = styleData2.Style == 0 && (num2 > 0 || num3 > 0);
                    int num12 = 50;
                    while (m > 0)
                    {
                        num12--;
                        if (num12 <= 0)
{
                            break;
                        }
                        Point point2 = bounds.RandomPointInBounds(genRand);
                        Tile tile2 = Main.tile[point2.X, point2.Y];
                        if (DungeonUtils.IsConsideredDungeonWall((int)tile2.wall, false) && !tile2.active())
{
                            point2 = DungeonUtils.FirstSolid(false, point2, bounds);
                            point2.Y--;
                            tile2 = Main.tile[point2.X, point2.Y];
                            int num13 = num2;
                            int num14 = num3;
                            int num15 = 0;
                            bool flag5;
                            if (flag4)
{
                                flag5 = this.GroundFurniture_ActuallyGenerateFurniture(data, genRand, point2.X, point2.Y, tile2.wall, ref num2, ref num3, ref num4, true, false);
                                if (!flag5)
{
                                    flag5 = this.GroundFurniture_ActuallyGenerateFurniture(data, genRand, point2.X, point2.Y, tile2.wall, ref num15, ref num15, ref num4, true, true);
                                }
                            }
                            else
{
                                flag5 = this.GroundFurniture_ActuallyGenerateFurniture(data, genRand, point2.X, point2.Y, tile2.wall, ref num15, ref num15, ref num4, true, false);
                                if (!flag5)
{
                                    flag5 = this.GroundFurniture_ActuallyGenerateFurniture(data, genRand, point2.X, point2.Y, tile2.wall, ref num15, ref num15, ref num4, true, true);
                                }
                            }
                            if ((flag4 && num13 != num2) || num14 != num3)
{
                                flag4 = false;
                            }
                            if (flag5)
{
                                m--;
                                num7++;
                            }
                        }
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.GameContent.Generation.Dungeon.Halls.DungeonHall.Bounds, System.Collections.Generic.List< T >.Count, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.dungeonGenerationStyles, Terraria.GameContent.Generation.Dungeon.DungeonData.dungeonHalls, Terraria.GameContent.Generation.Dungeon.DungeonData.dungeonRooms, Terraria.GameContent.Generation.Dungeon.DungeonUtils.FirstSolid(), Terraria.GameContent.Generation.Dungeon.Halls.DungeonHall.generated, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.generated, Terraria.WorldGen.genRand, Terraria.GameContent.Generation.Dungeon.DungeonData.genVars, Terraria.GameContent.Generation.Dungeon.Halls.DungeonHall.GetFurnitureCount(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.GetFurnitureCount(), Terraria.WorldGen.GetWorldSize(), Terraria.GameContent.Generation.Dungeon.DungeonData.globalFeatureScalar, Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalGroundFurniture.GroundFurniture_ActuallyGenerateFurniture(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.InnerBounds, int, Terraria.GameContent.Generation.Dungeon.DungeonUtils.IsConsideredDungeonWall(), Terraria.Main.maxTilesX, Terraria.GameContent.Generation.Dungeon.DungeonBounds.RandomPointInBounds(), Terraria.GameContent.Generation.Dungeon.Halls.DungeonHall.settings, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.settings, Terraria.GameContent.Generation.Dungeon.Halls.DungeonHallSettings.StyleData, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.StyleData, Terraria.Main.tile, Terraria.GameContent.Generation.Dungeon.DungeonData.Type, Terraria.Tile.wall, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalGroundFurniture.GenerateFeature().