Terraria Decompiled: System.Reflection.FieldInfo.GetPseudoCustomAttributes
GetPseudoCustomAttributes()
object[] System.Reflection.FieldInfo.GetPseudoCustomAttributes () inline package
Definition at line 301 of file FieldInfo.cs.
        {
            int num = 0;
            if (this.IsNotSerialized)
            {
                num++;
            }
            if (this.DeclaringType.IsExplicitLayout)
            {
                num++;
            }
            MarshalAsAttribute marshal_info = this.get_marshal_info();
            if (marshal_info != null)
            {
                num++;
            }
            if (num == 0)
            {
                return null;
            }
            object[] array = new object[num];
            num = 0;
            if (this.IsNotSerialized)
            {
                array[num++] = new NonSerializedAttribute();
            }
            if (this.DeclaringType.IsExplicitLayout)
            {
                array[num++] = new FieldOffsetAttribute(this.GetFieldOffset());
            }
            if (marshal_info != null)
            {
                array[num++] = marshal_info;
            }
            return array;
        }
References System.array, System.Reflection.MemberInfo.DeclaringType, System.Reflection.FieldInfo.get_marshal_info(), System.Reflection.FieldInfo.GetFieldOffset(), System.Type.IsExplicitLayout, and System.Reflection.FieldInfo.IsNotSerialized.
Referenced by System.MonoCustomAttrs.GetPseudoCustomAttributes().