Terraria Decompiled: System.Reflection.FieldInfo.GetPseudoCustomAttributesData
GetPseudoCustomAttributesData()
CustomAttributeData[] System.Reflection.FieldInfo.GetPseudoCustomAttributesData () inline package
Definition at line 339 of file FieldInfo.cs.
        {
            int num = 0;
            if (this.IsNotSerialized)
            {
                num++;
            }
            if (this.DeclaringType.IsExplicitLayout)
            {
                num++;
            }
            MarshalAsAttribute marshal_info = this.get_marshal_info();
            if (marshal_info != null)
            {
                num++;
            }
            if (num == 0)
            {
                return null;
            }
            CustomAttributeData[] array = new CustomAttributeData[num];
            num = 0;
            if (this.IsNotSerialized)
            {
                array[num++] = new CustomAttributeData(typeof(NonSerializedAttribute).GetConstructor(Type.EmptyTypes));
            }
            if (this.DeclaringType.IsExplicitLayout)
            {
                CustomAttributeTypedArgument[] array2 = new CustomAttributeTypedArgument[]
                {
                    new CustomAttributeTypedArgument(typeof(int), this.GetFieldOffset())
                };
                array[num++] = new CustomAttributeData(typeof(FieldOffsetAttribute).GetConstructor(new Type[] { typeof(int) }), array2, EmptyArray<CustomAttributeNamedArgument>.Value);
            }
            if (marshal_info != null)
            {
                CustomAttributeTypedArgument[] array3 = new CustomAttributeTypedArgument[]
                {
                    new CustomAttributeTypedArgument(typeof(UnmanagedType), marshal_info.Value)
                };
                array[num++] = new CustomAttributeData(typeof(MarshalAsAttribute).GetConstructor(new Type[] { typeof(UnmanagedType) }), array3, EmptyArray<CustomAttributeNamedArgument>.Value);
            }
            return array;
        }
References System.array, System.Reflection.MemberInfo.DeclaringType, System.Type.EmptyTypes, System.Reflection.FieldInfo.get_marshal_info(), System.Reflection.FieldInfo.GetFieldOffset(), System.Type.IsExplicitLayout, System.Reflection.FieldInfo.IsNotSerialized, and System.Runtime.InteropServices.MarshalAsAttribute.Value.
Referenced by System.MonoCustomAttrs.GetPseudoCustomAttributesData().