Terraria Decompiled: ReLogic.Peripherals.RGB.SteelSeries.SteelSeriesKeyboard.GetBitmapRequestForFullKeyboard
GetBitmapRequestForFullKeyboard()
JObject ReLogic.Peripherals.RGB.SteelSeries.SteelSeriesKeyboard.GetBitmapRequestForFullKeyboard () inline private
Definition at line 68 of file SteelSeriesKeyboard.cs.
        {
            JObject jobject = new JObject();
            jobject.Add("bitmap", JToken.FromObject(this._keyboardKeyColors));
            List<string> list = Enumerable.ToList<string>(Enumerable.Select<ColorKey, string>(Enumerable.Where<ColorKey>(this._keyboardTriggersForIteration, (ColorKey x) => x.IsVisible), (ColorKey x) => x.EventName));
            IEnumerable<string> enumerable = Enumerable.Select<ARgbGameValueTracker, string>(Enumerable.Where<ARgbGameValueTracker>(this.eventTrackers, (ARgbGameValueTracker x) => x.IsVisible), (ARgbGameValueTracker x) => x.EventName);
            list.AddRange(enumerable);
            jobject.Add("excluded-events", JToken.FromObject(list));
            JObject jobject2 = new JObject();
            jobject2.Add("frame", jobject);
            jobject2.Add("value", this._timesSent);
            this._timesSent++;
            if (this._timesSent >= 100)
            {
                this._timesSent = 1;
            }
            return new JObject
            {
                { "event", "DO_RAINBOWS" },
                { "data", jobject2 }
            };
        }
References ReLogic.Peripherals.RGB.SteelSeries.SteelSeriesKeyboard._keyboardTriggersForIteration, ReLogic.Peripherals.RGB.SteelSeries.SteelSeriesKeyboard._timesSent, Newtonsoft.Json.Linq.JObject.Add(), ReLogic.Peripherals.RGB.ARgbGameValueTracker< TValueType >.EventName, ReLogic.Peripherals.RGB.SteelSeries.ColorKey.EventName, ReLogic.Peripherals.RGB.SteelSeries.SteelSeriesKeyboard.eventTrackers, Newtonsoft.Json.Linq.JToken.FromObject(), and System.list.
Referenced by ReLogic.Peripherals.RGB.SteelSeries.SteelSeriesKeyboard.TryGetEventUpdateRequest().