Terraria Decompiled: ReLogic.Peripherals.RGB.SteelSeries.SteelSeriesKeyboard.TryGetEventUpdateRequest
TryGetEventUpdateRequest()
List< JObject > ReLogic.Peripherals.RGB.SteelSeries.SteelSeriesKeyboard.TryGetEventUpdateRequest () inline
Implements ReLogic.Peripherals.RGB.SteelSeries.IGameSenseUpdater.
Definition at line 52 of file SteelSeriesKeyboard.cs.
        {
            this._updateRequestsList.Clear();
            this._updateRequestsList.Add(this.GetBitmapRequestForFullKeyboard());
            for (int i = 0; i < this._keyboardTriggersForIteration.Count; i++)
            {
                JObject jobject = this._keyboardTriggersForIteration[i].TryGettingRequest();
                if (jobject != null)
                {
                    this._updateRequestsList.Add(jobject);
                }
            }
            return this._updateRequestsList;
        }
References ReLogic.Peripherals.RGB.SteelSeries.SteelSeriesKeyboard._keyboardTriggersForIteration, ReLogic.Peripherals.RGB.SteelSeries.SteelSeriesKeyboard._updateRequestsList, System.Collections.Generic.List< T >.Add(), System.Collections.Generic.List< T >.Clear(), and ReLogic.Peripherals.RGB.SteelSeries.SteelSeriesKeyboard.GetBitmapRequestForFullKeyboard().