Terraria Decompiled: Terraria.IO.WorldFile.ValidateLoadNPCs
ValidateLoadNPCs()
static void Terraria.IO.WorldFile.ValidateLoadNPCs (BinaryReader fileIO) inline static
Definition at line 2958 of file WorldFile.cs.
        {
            int num = fileIO.ReadInt32();
            while (num-- > 0)
            {
                fileIO.ReadInt32();
            }
            bool flag = fileIO.ReadBoolean();
            while (flag)
            {
                fileIO.ReadInt32();
                fileIO.ReadString();
                fileIO.ReadSingle();
                fileIO.ReadSingle();
                fileIO.ReadBoolean();
                fileIO.ReadInt32();
                fileIO.ReadInt32();
                if (fileIO.ReadByte()[0])
                {
                    fileIO.ReadInt32();
                }
                fileIO.ReadBoolean();
                flag = fileIO.ReadBoolean();
            }
            flag = fileIO.ReadBoolean();
            while (flag)
            {
                fileIO.ReadInt32();
                fileIO.ReadSingle();
                fileIO.ReadSingle();
                flag = fileIO.ReadBoolean();
            }
        }
References System.IO.BinaryReader.ReadBoolean(), System.IO.BinaryReader.ReadByte(), System.IO.BinaryReader.ReadInt32(), System.IO.BinaryReader.ReadSingle(), and System.IO.BinaryReader.ReadString().
Referenced by Terraria.IO.WorldFile.ValidateWorld().