Terraria Decompiled: Terraria.IO.WorldFile.InternalSaveWorld
InternalSaveWorld()
static void Terraria.IO.WorldFile.InternalSaveWorld (bool useCloudSaving, bool resetTime, bool useTemps) inline static private
Definition at line 833 of file WorldFile.cs.
        {
            Utils.TryCreatingDirectory(Main.WorldPath);
            if (!useTemps)
            {
                WorldFile.SetTempToOngoing();
            }
            if (resetTime)
            {
                WorldFile.ResetTempsToDayTime();
            }
            if (Main.worldPathName == null)
            {
                return;
            }
            new Stopwatch().Start();
            byte[] array;
            int num;
            using (MemoryStream memoryStream = new MemoryStream(7000000))
            {
                using (BinaryWriter binaryWriter = new BinaryWriter(memoryStream))
                {
                    WorldFile.SaveWorld_Version2(binaryWriter);
                }
                array = memoryStream.ToArray();
                num = array.Length;
            }
            byte[] array2 = null;
            if (FileUtilities.Exists(Main.worldPathName, useCloudSaving))
            {
                array2 = FileUtilities.ReadAllBytes(Main.worldPathName, useCloudSaving);
            }
            FileUtilities.Write(Main.worldPathName, array, num, useCloudSaving);
            array = FileUtilities.ReadAllBytes(Main.worldPathName, useCloudSaving);
            string text = null;
            using (MemoryStream memoryStream2 = new MemoryStream(array, 0, num, false))
            {
                using (BinaryReader binaryReader = new BinaryReader(memoryStream2))
                {
                    if (!Main.validateSaves || WorldFile.ValidateWorld(binaryReader))
                    {
                        if (array2 != null)
{
                            text = Main.worldPathName + ".bak";
                            Main.statusText = Lang.gen[50].Value;
                        }
                        WorldFile.DoRollingBackups(text);
                    }
                    else
                    {
                        text = Main.worldPathName;
                    }
                }
            }
            if (text != null && array2 != null)
            {
                FileUtilities.WriteAllBytes(text, array2, useCloudSaving);
            }
        }
References System.array, Terraria.IO.WorldFile.DoRollingBackups(), Terraria.Utilities.FileUtilities.Exists(), Terraria.Lang.gen, Terraria.Utilities.FileUtilities.ReadAllBytes(), Terraria.IO.WorldFile.ResetTempsToDayTime(), Terraria.IO.WorldFile.SaveWorld_Version2(), Terraria.IO.WorldFile.SetTempToOngoing(), System.text, System.IO.MemoryStream.ToArray(), Terraria.Utils.TryCreatingDirectory(), Terraria.Main.validateSaves, Terraria.IO.WorldFile.ValidateWorld(), Terraria.Localization.LocalizedText.Value, Terraria.Main.WorldPath, Terraria.Main.worldPathName, Terraria.Utilities.FileUtilities.Write(), and Terraria.Utilities.FileUtilities.WriteAllBytes().
Referenced by Terraria.IO.WorldFile._SaveWorld().