Terraria Decompiled: Terraria.IO.WorldFile.LoadWorld
LoadWorld()
static void Terraria.IO.WorldFile.LoadWorld () inline static
Definition at line 532 of file WorldFile.cs.
        {
            if (Main.rand == null)
            {
                Main.rand = new UnifiedRandom((int)DateTime.Now.Ticks);
            }
            Main.lockMenuBGChange = true;
            WorldFile._isWorldOnCloud = Main.ActiveWorldFileData.IsCloudSave;
            Main.checkXMas();
            Main.checkHalloween();
            if (WorldFile._isWorldOnCloud && SocialAPI.Cloud == null)
            {
                WorldFile.LastThrownLoadException = new Exception("Cloud inaccessible");
                WorldGen.loadFailed = true;
                return;
            }
            if (!FileUtilities.Exists(Main.worldPathName, WorldFile._isWorldOnCloud) && Main.autoGen)
            {
                if (!WorldFile._isWorldOnCloud)
                {
                    for (int i = Main.worldPathName.Length - 1; i >= 0; i--)
                    {
                        if (Main.worldPathName.Substring(i, 1) == (Path.DirectorySeparatorChar.ToString() ?? ""))
{
                            Utils.TryCreatingDirectory(Main.worldPathName.Substring(0, i));
                            break;
                        }
                    }
                }
                Main.ActiveWorldFileData = WorldFile.CreateMetadata((Main.worldName == "") ? "World" : Main.worldName, WorldFile._isWorldOnCloud, Main.GameMode);
                string text = (Main.AutogenSeedName ?? "").Trim();
                string text2;
                string text3;
                List<string> list;
                if (WorldFileData.TryApplyingCopiedSeed(text, true, out text2, out text3, out list))
                {
                    Main.ActiveWorldFileData.SetSeed(text3);
                }
                else
                {
                    text = Utils.TrimUserString(text, WorldFileData.MAX_USER_SEED_TEXT_LENGTH);
                    AWorldGenerationOption optionFromSeedText = WorldGenerationOptions.GetOptionFromSeedText(text);
                    WorldGenerationOptions.SelectOption(optionFromSeedText);
                    foreach (AWorldGenerationOption aworldGenerationOption in WorldGenerationOptions.Options)
                    {
                        if (aworldGenerationOption.AutoGenEnabled)
{
                            aworldGenerationOption.Enabled = true;
                        }
                    }
                    if (optionFromSeedText != null || string.IsNullOrWhiteSpace(text))
                    {
                        Main.ActiveWorldFileData.SetSeedToRandomWithCurrentEvents();
                    }
                    else
                    {
                        Main.ActiveWorldFileData.SetSeed(text);
                    }
                }
                if (WorldGen.GenerateWorld(Main.AutogenProgress, null))
                {
                    WorldFile.SaveNewWorld();
                }
            }
            try
            {
                using (MemoryStream memoryStream = new MemoryStream(FileUtilities.ReadAllBytes(Main.worldPathName, WorldFile._isWorldOnCloud)))
                {
                    using (BinaryReader binaryReader = new BinaryReader(memoryStream))
                    {
                        try
{
                            WorldGen.loadFailed = false;
                            int num = binaryReader.ReadInt32();
                            WorldFile._versionNumber = num;
                            int num2;
                            if (num <= 0)
{
                                num2 = StatusID.UnknownError;
                            }
                            else if (num > 319)
{
                                num2 = StatusID.LaterVersion;
                            }
                            else if (num <= 87)
{
                                num2 = WorldFile.LoadWorld_Version1_Old_BeforeRelease88(binaryReader);
                            }
                            else
{
                                num2 = WorldFile.LoadWorld_Version2(binaryReader);
                            }
                            if (num < 141)
{
                                if (!WorldFile._isWorldOnCloud)
{
                                    Main.ActiveWorldFileData.CreationTime = File.GetCreationTime(Main.worldPathName);
                                }
                                else
{
                                    Main.ActiveWorldFileData.CreationTime = DateTime.Now;
                                }
                            }
                            binaryReader.Close();
                            memoryStream.Close();
                            if (num2 != StatusID.Ok)
{
                                throw new Exception("LoadWorld failed with status: " + StatusID.Search.GetName(num2));
                            }
                            WorldFile.CheckSavedOreTiers();
                            WorldFile.ConvertOldTileEntities();
                            WorldFile.ClearTempTiles();
                            WorldGen.isGeneratingOrLoadingWorld = true;
                            GenVars.waterLine = Main.maxTilesY;
                            Liquid.QuickWater(2, -1, -1);
                            WorldGen.WaterCheck();
                            int num3 = 0;
                            Liquid.quickSettle = true;
                            int num4 = Liquid.numLiquid + LiquidBuffer.numLiquidBuffer;
                            float num5 = 0f;
                            while (Liquid.numLiquid > 0 && num3 < 100000)
{
                                num3++;
                                float num6 = (float)(num4 - (Liquid.numLiquid + LiquidBuffer.numLiquidBuffer)) / (float)num4;
                                if (Liquid.numLiquid + LiquidBuffer.numLiquidBuffer > num4)
{
                                    num4 = Liquid.numLiquid + LiquidBuffer.numLiquidBuffer;
                                }
                                if (num6 > num5)
{
                                    num5 = num6;
                                }
                                else
{
                                    num6 = num5;
                                }
                                Main.statusText = string.Concat(new object[]
{
                                    Lang.gen[27].Value,
                                    " ",
                                    (int)(num6 * 100f / 2f + 50f),
                                    "%"
                                });
                                Liquid.UpdateLiquid();
                            }
                            Liquid.quickSettle = false;
                            Main.weatherCounter = WorldGen.genRand.Next(3600, 18000);
                            Cloud.resetClouds();
                            WorldGen.WaterCheck();
                            WorldGen.isGeneratingOrLoadingWorld = false;
                            NPC.setFireFlyChance();
                            WorldGen.Skyblock.ScanTiles();
                            if (Main.slimeRainTime > 0.0)
{
                                Main.StartSlimeRain(false);
                            }
                            NPC.SetWorldSpecificMonstersByWorldID();
                        }
                        catch (Exception ex)
{
                            WorldFile.LastThrownLoadException = ex;
                            WorldGen.loadFailed = true;
                            try
{
                                binaryReader.Close();
                                memoryStream.Close();
                            }
                            catch
{
                            }
                        }
                    }
                }
            }
            catch (Exception ex2)
            {
                WorldFile.LastThrownLoadException = ex2;
                WorldGen.loadFailed = true;
            }
        }
References Terraria.IO.WorldFile._isWorldOnCloud, Terraria.Main.ActiveWorldFileData, Terraria.Main.autoGen, Terraria.WorldBuilding.AWorldGenerationOption.AutoGenEnabled, Terraria.Main.AutogenProgress, Terraria.Main.checkHalloween(), Terraria.IO.WorldFile.CheckSavedOreTiers(), Terraria.Main.checkXMas(), Terraria.IO.WorldFile.ClearTempTiles(), System.IO.BinaryReader.Close(), System.IO.Stream.Close(), Terraria.Social.SocialAPI.Cloud, Terraria.IO.WorldFile.ConvertOldTileEntities(), Terraria.IO.WorldFile.CreateMetadata(), System.IO.Path.DirectorySeparatorChar, Terraria.Utilities.FileUtilities.Exists(), Terraria.Main.GameMode, Terraria.Lang.gen, Terraria.WorldGen.GenerateWorld(), Terraria.WorldGen.genRand, System.IO.File.GetCreationTime(), Terraria.WorldBuilding.WorldGenerationOptions.GetOptionFromSeedText(), int, Terraria.ID.StatusID.LaterVersion, System.list, Terraria.IO.WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), Terraria.IO.WorldFile.LoadWorld_Version2(), Terraria.IO.WorldFileData.MAX_USER_SEED_TEXT_LENGTH, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), System.DateTime.Now, Terraria.Liquid.numLiquid, Terraria.LiquidBuffer.numLiquidBuffer, Terraria.ID.StatusID.Ok, Terraria.WorldBuilding.WorldGenerationOptions.Options, Terraria.Liquid.QuickWater(), Terraria.Main.rand, Terraria.Utilities.FileUtilities.ReadAllBytes(), System.IO.BinaryReader.ReadInt32(), Terraria.Cloud.resetClouds(), Terraria.IO.WorldFile.SaveNewWorld(), Terraria.WorldGen.Skyblock.ScanTiles(), Terraria.ID.StatusID.Search, Terraria.WorldBuilding.WorldGenerationOptions.SelectOption(), Terraria.NPC.setFireFlyChance(), Terraria.NPC.SetWorldSpecificMonstersByWorldID(), Terraria.Main.slimeRainTime, Terraria.Main.StartSlimeRain(), System.text, System.DateTime.Ticks, Terraria.Utils.TrimUserString(), Terraria.IO.WorldFileData.TryApplyingCopiedSeed(), Terraria.Utils.TryCreatingDirectory(), Terraria.ID.StatusID.UnknownError, Terraria.Liquid.UpdateLiquid(), Terraria.Localization.LocalizedText.Value, Terraria.WorldGen.WaterCheck(), Terraria.Main.worldName, and Terraria.Main.worldPathName.
Referenced by Terraria.WorldGen.playWorldCallBack(), Terraria.Testing.ChatCommands.ToolkitDebugCommands.ReloadCommand(), Terraria.WorldGen.RenameWorldCallBack(), and Terraria.WorldGen.serverLoadWorldCallBack().