Terraria Decompiled: Terraria.IO.WorldFile.LoadWorld_Version1_Old_BeforeRelease88
LoadWorld_Version1_Old_BeforeRelease88()
static int Terraria.IO.WorldFile.LoadWorld_Version1_Old_BeforeRelease88 (BinaryReader fileIO) inline static private
Definition at line 3484 of file WorldFile.cs.
        {
            Main.WorldFileMetadata = FileMetadata.FromCurrentSettings(FileType.World);
            int versionNumber = WorldFile._versionNumber;
            if (versionNumber > 319)
            {
                return StatusID.LaterVersion;
            }
            Main.worldName = fileIO.ReadString();
            Main.ActiveWorldFileData.WorldId = fileIO.ReadInt32();
            Main.leftWorld = (float)fileIO.ReadInt32();
            Main.rightWorld = (float)fileIO.ReadInt32();
            Main.topWorld = (float)fileIO.ReadInt32();
            Main.bottomWorld = (float)fileIO.ReadInt32();
            Main.maxTilesY = fileIO.ReadInt32();
            Main.maxTilesX = fileIO.ReadInt32();
            if (versionNumber >= 112)
            {
                Main.GameMode = (fileIO.ReadBoolean() ? 1 : 0);
            }
            else
            {
                Main.GameMode = 0;
            }
            if (versionNumber >= 63)
            {
                Main.moonType = (int)fileIO.ReadByte();
            }
            else
            {
                WorldGen.RandomizeMoonState(WorldGen.genRand, false);
            }
            WorldGen.clearWorld();
            if (versionNumber >= 44)
            {
                Main.treeX[0] = fileIO.ReadInt32();
                Main.treeX[1] = fileIO.ReadInt32();
                Main.treeX[2] = fileIO.ReadInt32();
                Main.treeStyle[0] = fileIO.ReadInt32();
                Main.treeStyle[1] = fileIO.ReadInt32();
                Main.treeStyle[2] = fileIO.ReadInt32();
                Main.treeStyle[3] = fileIO.ReadInt32();
            }
            if (versionNumber >= 60)
            {
                Main.caveBackX[0] = fileIO.ReadInt32();
                Main.caveBackX[1] = fileIO.ReadInt32();
                Main.caveBackX[2] = fileIO.ReadInt32();
                Main.caveBackStyle[0] = fileIO.ReadInt32();
                Main.caveBackStyle[1] = fileIO.ReadInt32();
                Main.caveBackStyle[2] = fileIO.ReadInt32();
                Main.caveBackStyle[3] = fileIO.ReadInt32();
                Main.iceBackStyle = fileIO.ReadInt32();
                if (versionNumber >= 61)
                {
                    Main.jungleBackStyle = fileIO.ReadInt32();
                    Main.hellBackStyle = fileIO.ReadInt32();
                }
            }
            else
            {
                WorldGen.RandomizeCaveBackgrounds();
            }
            Main.spawnTileX = fileIO.ReadInt32();
            Main.spawnTileY = fileIO.ReadInt32();
            Main.worldSurface = fileIO.ReadDouble();
            Main.rockLayer = fileIO.ReadDouble();
            WorldFile._tempTime = fileIO.ReadDouble();
            WorldFile._tempDayTime = fileIO.ReadBoolean();
            WorldFile._tempMoonPhase = fileIO.ReadInt32();
            WorldFile._tempBloodMoon = fileIO.ReadBoolean();
            if (versionNumber >= 70)
            {
                WorldFile._tempEclipse = fileIO.ReadBoolean();
                Main.eclipse = WorldFile._tempEclipse;
            }
            Main.dungeonX = fileIO.ReadInt32();
            Main.dungeonY = fileIO.ReadInt32();
            if (versionNumber >= 56)
            {
                WorldGen.crimson = fileIO.ReadBoolean();
            }
            else
            {
                WorldGen.crimson = false;
            }
            NPC.downedBoss1 = fileIO.ReadBoolean();
            NPC.downedBoss2 = fileIO.ReadBoolean();
            NPC.downedBoss3 = fileIO.ReadBoolean();
            if (versionNumber >= 66)
            {
                NPC.downedQueenBee = fileIO.ReadBoolean();
            }
            if (versionNumber >= 44)
            {
                NPC.downedMechBoss1 = fileIO.ReadBoolean();
                NPC.downedMechBoss2 = fileIO.ReadBoolean();
                NPC.downedMechBoss3 = fileIO.ReadBoolean();
                NPC.downedMechBossAny = fileIO.ReadBoolean();
            }
            if (versionNumber >= 64)
            {
                NPC.downedPlantBoss = fileIO.ReadBoolean();
                NPC.downedGolemBoss = fileIO.ReadBoolean();
            }
            if (versionNumber >= 29)
            {
                NPC.savedGoblin = fileIO.ReadBoolean();
                NPC.savedWizard = fileIO.ReadBoolean();
                if (versionNumber >= 34)
                {
                    NPC.savedMech = fileIO.ReadBoolean();
                    if (versionNumber >= 80)
                    {
                        NPC.savedStylist = fileIO.ReadBoolean();
                    }
                }
                if (versionNumber >= 129)
                {
                    NPC.savedTaxCollector = fileIO.ReadBoolean();
                }
                if (versionNumber >= 201)
                {
                    NPC.savedGolfer = fileIO.ReadBoolean();
                }
                NPC.downedGoblins = fileIO.ReadBoolean();
            }
            if (versionNumber >= 32)
            {
                NPC.downedClown = fileIO.ReadBoolean();
            }
            if (versionNumber >= 37)
            {
                NPC.downedFrost = fileIO.ReadBoolean();
            }
            if (versionNumber >= 56)
            {
                NPC.downedPirates = fileIO.ReadBoolean();
            }
            WorldGen.shadowOrbSmashed = fileIO.ReadBoolean();
            WorldGen.spawnMeteor = fileIO.ReadBoolean();
            WorldGen.shadowOrbCount = (int)fileIO.ReadByte();
            if (versionNumber >= 23)
            {
                WorldGen.altarCount = fileIO.ReadInt32();
                Main.hardMode = fileIO.ReadBoolean();
            }
            Main.invasionDelay = fileIO.ReadInt32();
            Main.invasionSize = fileIO.ReadInt32();
            Main.invasionType = fileIO.ReadInt32();
            Main.invasionX = fileIO.ReadDouble();
            if (versionNumber >= 113)
            {
                Main.sundialCooldown = (int)fileIO.ReadByte();
            }
            if (versionNumber >= 53)
            {
                WorldFile._tempRaining = fileIO.ReadBoolean();
                WorldFile._tempRainTime = fileIO.ReadInt32();
                WorldFile._tempMaxRain = fileIO.ReadSingle();
            }
            if (versionNumber >= 54)
            {
                WorldGen.SavedOreTiers.Cobalt = fileIO.ReadInt32();
                WorldGen.SavedOreTiers.Mythril = fileIO.ReadInt32();
                WorldGen.SavedOreTiers.Adamantite = fileIO.ReadInt32();
            }
            else if (versionNumber >= 23 && WorldGen.altarCount == 0)
            {
                WorldGen.SavedOreTiers.Cobalt = -1;
                WorldGen.SavedOreTiers.Mythril = -1;
                WorldGen.SavedOreTiers.Adamantite = -1;
            }
            else
            {
                WorldGen.SavedOreTiers.Cobalt = 107;
                WorldGen.SavedOreTiers.Mythril = 108;
                WorldGen.SavedOreTiers.Adamantite = 111;
            }
            int num = 0;
            int num2 = 0;
            int num3 = 0;
            int num4 = 0;
            int num5 = 0;
            int num6 = 0;
            int num7 = 0;
            int num8 = 0;
            int num9 = 0;
            int num10 = 0;
            if (versionNumber >= 55)
            {
                num = (int)fileIO.ReadByte();
                num2 = (int)fileIO.ReadByte();
                num3 = (int)fileIO.ReadByte();
            }
            if (versionNumber >= 60)
            {
                num4 = (int)fileIO.ReadByte();
                num5 = (int)fileIO.ReadByte();
                num6 = (int)fileIO.ReadByte();
                num7 = (int)fileIO.ReadByte();
                num8 = (int)fileIO.ReadByte();
            }
            WorldGen.setBG(0, num);
            WorldGen.setBG(1, num2);
            WorldGen.setBG(2, num3);
            WorldGen.setBG(3, num4);
            WorldGen.setBG(4, num5);
            WorldGen.setBG(5, num6);
            WorldGen.setBG(6, num7);
            WorldGen.setBG(7, num8);
            WorldGen.setBG(8, num9);
            WorldGen.setBG(9, num10);
            WorldGen.setBG(10, num);
            WorldGen.setBG(11, num);
            WorldGen.setBG(12, num);
            if (versionNumber >= 60)
            {
                Main.cloudBGActive = (float)fileIO.ReadInt32();
                if (Main.cloudBGActive >= 1f)
                {
                    Main.cloudBGAlpha = 1f;
                }
                else
                {
                    Main.cloudBGAlpha = 0f;
                }
            }
            else
            {
                Main.cloudBGActive = (float)(-(float)WorldGen.genRand.Next(8640, 86400));
            }
            if (versionNumber >= 62)
            {
                Main.numClouds = (int)fileIO.ReadInt16();
                Main.windSpeedTarget = fileIO.ReadSingle();
                Main.windSpeedCurrent = Main.windSpeedTarget;
            }
            else
            {
                WorldGen.RandomizeWeather();
            }
            for (int i = 0; i < Main.maxTilesX; i++)
            {
                float num11 = (float)i / (float)Main.maxTilesX;
                Main.statusText = string.Concat(new object[]
                {
                    Lang.gen[51].Value,
                    " ",
                    (int)(num11 * 100f + 1f),
                    "%"
                });
                for (int j = 0; j < Main.maxTilesY; j++)
                {
                    Tile tile = Main.tile[i, j];
                    int num12 = -1;
                    tile.active(fileIO.ReadBoolean());
                    if (tile.active())
                    {
                        if (versionNumber > 77)
{
                            num12 = (int)fileIO.ReadUInt16();
                        }
                        else
{
                            num12 = (int)fileIO.ReadByte();
                        }
                        tile.type = (ushort)num12;
                        if (tile.type == 127 || tile.type == 504)
{
                            tile.active(false);
                        }
                        if (versionNumber < 72 && (tile.type == 35 || tile.type == 36 || tile.type == 170 || tile.type == 171 || tile.type == 172))
{
                            tile.frameX = fileIO.ReadInt16();
                            tile.frameY = fileIO.ReadInt16();
                        }
                        else if (Main.tileFrameImportant[num12])
{
                            if (versionNumber < 28 && num12 == 4)
{
                                tile.frameX = 0;
                                tile.frameY = 0;
                            }
                            else if (versionNumber < 40 && tile.type == 19)
{
                                tile.frameX = 0;
                                tile.frameY = 0;
                            }
                            else if (versionNumber < 195 && tile.type == 49)
{
                                tile.frameX = 0;
                                tile.frameY = 0;
                            }
                            else
{
                                tile.frameX = fileIO.ReadInt16();
                                tile.frameY = fileIO.ReadInt16();
                                if (tile.type == 144)
{
                                    tile.frameY = 0;
                                }
                            }
                        }
                        else
{
                            tile.frameX = -1;
                            tile.frameY = -1;
                        }
                        if (versionNumber >= 48 && fileIO.ReadBoolean())
{
                            tile.color(fileIO.ReadByte());
                        }
                    }
                    if (versionNumber <= 25)
                    {
                        fileIO.ReadBoolean();
                    }
                    if (fileIO.ReadBoolean())
                    {
                        tile.wall = (ushort)fileIO.ReadByte();
                        if (tile.wall >= WallID.Count)
{
                            tile.wall = 0;
                        }
                        if (versionNumber >= 48 && fileIO.ReadBoolean())
{
                            tile.wallColor(fileIO.ReadByte());
                        }
                    }
                    if (fileIO.ReadBoolean())
                    {
                        tile.liquid = fileIO.ReadByte();
                        tile.lava(fileIO.ReadBoolean());
                        if (versionNumber >= 51)
{
                            tile.honey(fileIO.ReadBoolean());
                        }
                    }
                    if (versionNumber >= 33)
                    {
                        tile.wire(fileIO.ReadBoolean());
                    }
                    if (versionNumber >= 43)
                    {
                        tile.wire2(fileIO.ReadBoolean());
                        tile.wire3(fileIO.ReadBoolean());
                    }
                    if (versionNumber >= 41)
                    {
                        tile.halfBrick(fileIO.ReadBoolean());
                        if (!TileID.Sets.SaveSlopes[(int)tile.type])
{
                            tile.halfBrick(false);
                        }
                        if (versionNumber >= 49)
{
                            tile.slope(fileIO.ReadByte());
                            if (!TileID.Sets.SaveSlopes[(int)tile.type])
{
                                tile.slope(0);
                            }
                        }
                    }
                    if (versionNumber >= 42)
                    {
                        tile.actuator(fileIO.ReadBoolean());
                        tile.inActive(fileIO.ReadBoolean());
                    }
                    int num13 = 0;
                    if (versionNumber >= 25)
                    {
                        num13 = (int)fileIO.ReadInt16();
                    }
                    if (num12 != -1)
                    {
                        if ((double)j <= Main.worldSurface)
{
                            if ((double)(j + num13) <= Main.worldSurface)
{
                                WorldGen.tileCounts[num12] += (num13 + 1) * 5;
                            }
                            else
{
                                int num14 = (int)(Main.worldSurface - (double)j + 1.0);
                                int num15 = num13 + 1 - num14;
                                WorldGen.tileCounts[num12] += num14 * 5 + num15;
                            }
                        }
                        else
{
                            WorldGen.tileCounts[num12] += num13 + 1;
                        }
                    }
                    if (num13 > 0)
                    {
                        for (int k = j + 1; k < j + num13 + 1; k++)
{
                            Main.tile[i, k].CopyFrom(Main.tile[i, j]);
                        }
                        j += num13;
                    }
                }
            }
            WorldGen.AddUpAlignmentCounts(true);
            if (versionNumber < 67)
            {
                WorldGen.FixSunflowers();
            }
            if (versionNumber < 72)
            {
                WorldGen.FixChands();
            }
            int num16 = 40;
            if (versionNumber < 58)
            {
                num16 = 20;
            }
            int num17 = 1000;
            for (int l = 0; l < num17; l++)
            {
                if (fileIO.ReadBoolean())
                {
                    int num18 = fileIO.ReadInt32();
                    int num19 = fileIO.ReadInt32();
                    Chest chest = Chest.CreateWorldChest(l, num18, num19);
                    if (versionNumber >= 85)
                    {
                        chest.name = Utils.TrimUserString(fileIO.ReadString(), 20);
                    }
                    for (int m = 0; m < 40; m++)
                    {
                        if (m < num16)
{
                            int num20;
                            if (versionNumber >= 59)
{
                                num20 = (int)fileIO.ReadInt16();
                            }
                            else
{
                                num20 = (int)fileIO.ReadByte();
                            }
                            if (num20 > 0)
{
                                if (versionNumber >= 38)
{
                                    chest.item[m].netDefaults(fileIO.ReadInt32());
                                }
                                else
{
                                    short num21 = ItemID.FromLegacyName(fileIO.ReadString(), versionNumber);
                                    chest.item[m].SetDefaults((int)num21, null);
                                }
                                chest.item[m].stack = num20;
                                if (versionNumber >= 36)
{
                                    chest.item[m].Prefix((int)fileIO.ReadByte());
                                }
                            }
                        }
                    }
                }
            }
            for (int n = 0; n < 1000; n++)
            {
                if (fileIO.ReadBoolean())
                {
                    string text = fileIO.ReadString();
                    int num22 = fileIO.ReadInt32();
                    int num23 = fileIO.ReadInt32();
                    if (Main.tile[num22, num23].active() && (Main.tile[num22, num23].type == 55 || Main.tile[num22, num23].type == 85))
                    {
                        Main.sign[n] = new Sign();
                        Main.sign[n].x = num22;
                        Main.sign[n].y = num23;
                        Main.sign[n].text = text;
                    }
                }
            }
            bool flag = fileIO.ReadBoolean();
            int num24 = 0;
            while (flag)
            {
                if (versionNumber >= 190)
                {
                    Main.npc[num24].SetDefaults(fileIO.ReadInt32(), default(NPCSpawnParams));
                }
                else
                {
                    Main.npc[num24].SetDefaults(NPCID.FromLegacyName(fileIO.ReadString()), default(NPCSpawnParams));
                }
                if (versionNumber >= 83)
                {
                    Main.npc[num24].GivenName = fileIO.ReadString();
                }
                Main.npc[num24].position.X = fileIO.ReadSingle();
                Main.npc[num24].position.Y = fileIO.ReadSingle();
                Main.npc[num24].homeless = fileIO.ReadBoolean();
                Main.npc[num24].homeTileX = fileIO.ReadInt32();
                Main.npc[num24].homeTileY = fileIO.ReadInt32();
                flag = fileIO.ReadBoolean();
                num24++;
            }
            if (versionNumber >= 31 && versionNumber <= 83)
            {
                NPC.setNPCName(fileIO.ReadString(), 17, true);
                NPC.setNPCName(fileIO.ReadString(), 18, true);
                NPC.setNPCName(fileIO.ReadString(), 19, true);
                NPC.setNPCName(fileIO.ReadString(), 20, true);
                NPC.setNPCName(fileIO.ReadString(), 22, true);
                NPC.setNPCName(fileIO.ReadString(), 54, true);
                NPC.setNPCName(fileIO.ReadString(), 38, true);
                NPC.setNPCName(fileIO.ReadString(), 107, true);
                NPC.setNPCName(fileIO.ReadString(), 108, true);
                if (versionNumber >= 35)
                {
                    NPC.setNPCName(fileIO.ReadString(), 124, true);
                    if (versionNumber >= 65)
                    {
                        NPC.setNPCName(fileIO.ReadString(), 160, true);
                        NPC.setNPCName(fileIO.ReadString(), 178, true);
                        NPC.setNPCName(fileIO.ReadString(), 207, true);
                        NPC.setNPCName(fileIO.ReadString(), 208, true);
                        NPC.setNPCName(fileIO.ReadString(), 209, true);
                        NPC.setNPCName(fileIO.ReadString(), 227, true);
                        NPC.setNPCName(fileIO.ReadString(), 228, true);
                        NPC.setNPCName(fileIO.ReadString(), 229, true);
                        if (versionNumber >= 79)
{
                            NPC.setNPCName(fileIO.ReadString(), 353, true);
                        }
                    }
                }
            }
            if (Main.invasionType > 0 && Main.invasionSize > 0)
            {
                Main.FakeLoadInvasionStart();
            }
            if (versionNumber < 7)
            {
                return StatusID.Ok;
            }
            bool flag2 = fileIO.ReadBoolean();
            string text2 = fileIO.ReadString();
            int num25 = fileIO.ReadInt32();
            if (flag2 && (text2 == Main.worldName || num25 == Main.worldID))
            {
                return StatusID.Ok;
            }
            return StatusID.UnknownError;
        }
References Terraria.IO.WorldFile._tempEclipse, Terraria.IO.WorldFile._versionNumber, Terraria.Tile.active(), Terraria.Tile.actuator(), Terraria.WorldGen.AddUpAlignmentCounts(), Terraria.WorldGen.altarCount, Terraria.Main.caveBackStyle, Terraria.Main.caveBackX, Terraria.WorldGen.clearWorld(), Terraria.Main.cloudBGActive, Terraria.Tile.color(), Terraria.Tile.CopyFrom(), Terraria.ID.WallID.Count, Terraria.Chest.CreateWorldChest(), Terraria.Main.FakeLoadInvasionStart(), Terraria.WorldGen.FixChands(), Terraria.WorldGen.FixSunflowers(), Terraria.IO.FileMetadata.FromCurrentSettings(), Terraria.ID.NPCID.FromLegacyName(), Terraria.ID.ItemID.FromLegacyName(), Terraria.Lang.gen, Terraria.WorldGen.genRand, Terraria.NPC.GivenName, Terraria.Tile.halfBrick(), Terraria.NPC.homeless, Terraria.NPC.homeTileX, Terraria.NPC.homeTileY, Terraria.Tile.honey(), Terraria.Tile.inActive(), int, Terraria.Main.invasionSize, Terraria.Main.invasionType, Terraria.Chest.item, Terraria.ID.StatusID.LaterVersion, Terraria.Tile.lava(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Item.netDefaults(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.npc, Terraria.ID.StatusID.Ok, Terraria.Entity.position, Terraria.Item.Prefix(), Terraria.WorldGen.RandomizeCaveBackgrounds(), Terraria.WorldGen.RandomizeMoonState(), Terraria.WorldGen.RandomizeWeather(), System.IO.BinaryReader.ReadBoolean(), System.IO.BinaryReader.ReadByte(), System.IO.BinaryReader.ReadDouble(), System.IO.BinaryReader.ReadInt16(), System.IO.BinaryReader.ReadInt32(), System.IO.BinaryReader.ReadSingle(), System.IO.BinaryReader.ReadString(), System.IO.BinaryReader.ReadUInt16(), Terraria.ID.TileID.Sets.SaveSlopes, Terraria.WorldGen.setBG(), Terraria.Item.SetDefaults(), Terraria.NPC.SetDefaults(), Terraria.NPC.setNPCName(), Terraria.Main.sign, Terraria.Tile.slope(), Terraria.Item.stack, System.text, Terraria.Sign.text, Terraria.Main.tile, Terraria.WorldGen.tileCounts, Terraria.Main.tileFrameImportant, Terraria.Main.treeStyle, Terraria.Main.treeX, Terraria.Utils.TrimUserString(), Terraria.Tile.type, Terraria.ID.StatusID.UnknownError, Terraria.Localization.LocalizedText.Value, Terraria.Tile.wall, Terraria.Tile.wallColor(), Terraria.Main.windSpeedTarget, Terraria.Tile.wire(), Terraria.Tile.wire2(), Terraria.Tile.wire3(), Terraria.Main.worldID, Terraria.Main.worldName, Terraria.Main.worldSurface, Microsoft.Xna.Framework.Vector2.X, Terraria.Sign.x, Microsoft.Xna.Framework.Vector2.Y, and Terraria.Sign.y.
Referenced by Terraria.IO.WorldFile.LoadWorld().