Terraria Decompiled: Terraria.IO.WorldFile.LoadTileEntities
LoadTileEntities()
static void Terraria.IO.WorldFile.LoadTileEntities (BinaryReader reader) inline static
Definition at line 3364 of file WorldFile.cs.
        {
            TileEntity.Clear();
            int num = reader.ReadInt32();
            int num2 = 0;
            for (int i = 0; i < num; i++)
            {
                TileEntity tileEntity = TileEntity.Read(reader, WorldFile._versionNumber, false);
                tileEntity.ID = num2++;
                TileEntity tileEntity2;
                if (TileEntity.TryGetAt<TileEntity>((int)tileEntity.Position.X, (int)tileEntity.Position.Y, out tileEntity2))
                {
                    TileEntity.Remove(tileEntity2, false);
                }
                TileEntity.Add(tileEntity);
            }
            TileEntity.TileEntitiesNextID = num;
            List<TileEntity> list = new List<TileEntity>();
            foreach (KeyValuePair<Point16, TileEntity> keyValuePair in TileEntity.ByPosition)
            {
                if (!WorldGen.InWorld((int)keyValuePair.Value.Position.X, (int)keyValuePair.Value.Position.Y, 1))
                {
                    list.Add(keyValuePair.Value);
                }
                else if (!TileEntity.manager.CheckValidTile((int)keyValuePair.Value.type, (int)keyValuePair.Value.Position.X, (int)keyValuePair.Value.Position.Y))
                {
                    list.Add(keyValuePair.Value);
                }
            }
            try
            {
                foreach (TileEntity tileEntity3 in list)
                {
                    TileEntity.Remove(tileEntity3, false);
                }
            }
            catch
            {
            }
            foreach (TileEntity tileEntity4 in TileEntity.ByID.Values)
            {
                tileEntity4.OnWorldLoaded();
            }
        }
References Terraria.IO.WorldFile._versionNumber, Terraria.DataStructures.TileEntity.Add(), Terraria.DataStructures.TileEntity.ByID, Terraria.DataStructures.TileEntity.ByPosition, Terraria.DataStructures.TileEntitiesManager.CheckValidTile(), Terraria.DataStructures.TileEntity.Clear(), Terraria.WorldGen.InWorld(), System.list, Terraria.DataStructures.TileEntity.manager, Terraria.DataStructures.TileEntity.OnWorldLoaded(), Terraria.DataStructures.TileEntity.Position, Terraria.DataStructures.TileEntity.Read(), System.IO.BinaryReader.ReadInt32(), Terraria.DataStructures.TileEntity.Remove(), System.Collections.Generic.KeyValuePair< TKey, TValue >.Value, Terraria.DataStructures.Point16.X, and Terraria.DataStructures.Point16.Y.
Referenced by Terraria.IO.WorldFile.LoadWorld_Version2().