Terraria Decompiled: Terraria.IO.WorldFile.CreateMetadata
CreateMetadata()
static WorldFileData Terraria.IO.WorldFile.CreateMetadata (string name, bool cloudSave, int GameMode) inline static
Definition at line 476 of file WorldFile.cs.
        {
            WorldFileData worldFileData = new WorldFileData(Main.GetWorldPathFromName(name, cloudSave), cloudSave);
            if (Main.autoGenFileLocation != null && Main.autoGenFileLocation != "")
            {
                worldFileData = new WorldFileData(Main.autoGenFileLocation, cloudSave);
                Main.autoGenFileLocation = null;
            }
            worldFileData.Name = name;
            worldFileData.GameMode = GameMode;
            worldFileData.CreationTime = DateTime.Now;
            worldFileData.Metadata = FileMetadata.FromCurrentSettings(FileType.World);
            worldFileData.SetFavorite(false, true);
            worldFileData.WorldGeneratorVersion = 1370094567425UL;
            worldFileData.UniqueId = Guid.NewGuid();
            if (Main.DefaultSeed == "")
            {
                worldFileData.SetSeedToRandom();
            }
            else
            {
                worldFileData.SetSeed(Main.DefaultSeed);
            }
            return worldFileData;
        }
References Terraria.Main.autoGenFileLocation, Terraria.Main.DefaultSeed, Terraria.IO.FileMetadata.FromCurrentSettings(), Terraria.Main.GetWorldPathFromName(), System.name, System.Guid.NewGuid(), System.DateTime.Now, Terraria.IO.FileData.SetFavorite(), Terraria.IO.WorldFileData.SetSeed(), and Terraria.IO.WorldFileData.SetSeedToRandom().
Referenced by Terraria.Main.DedServ(), Terraria.GameContent.UI.States.UIWorldCreation.FinishCreatingWorld(), Terraria.IO.WorldFile.LoadWorld(), and Terraria.Main.OnWorldNamed().