Terraria Decompiled: Terraria.IO.WorldFile.SaveWorld_Version2
SaveWorld_Version2()
static void Terraria.IO.WorldFile.SaveWorld_Version2 (BinaryWriter writer) inline static
Definition at line 1084 of file WorldFile.cs.
        {
            int[] array = new int[]
            {
                WorldFile.SaveFileFormatHeader(writer),
                WorldFile.SaveWorldHeader(writer),
                WorldFile.SaveWorldTiles(writer),
                WorldFile.SaveChests(writer),
                WorldFile.SaveSigns(writer),
                WorldFile.SaveNPCs(writer),
                WorldFile.SaveTileEntities(writer),
                WorldFile.SaveWeightedPressurePlates(writer),
                WorldFile.SaveTownManager(writer),
                WorldFile.SaveBestiary(writer),
                WorldFile.SaveCreativePowers(writer)
            };
            WorldFile.SaveFooter(writer);
            WorldFile.SaveHeaderPointers(writer, array);
        }
References System.array, Terraria.IO.WorldFile.SaveBestiary(), Terraria.IO.WorldFile.SaveChests(), Terraria.IO.WorldFile.SaveCreativePowers(), Terraria.IO.WorldFile.SaveFileFormatHeader(), Terraria.IO.WorldFile.SaveFooter(), Terraria.IO.WorldFile.SaveHeaderPointers(), Terraria.IO.WorldFile.SaveNPCs(), Terraria.IO.WorldFile.SaveSigns(), Terraria.IO.WorldFile.SaveTileEntities(), Terraria.IO.WorldFile.SaveTownManager(), Terraria.IO.WorldFile.SaveWeightedPressurePlates(), Terraria.IO.WorldFile.SaveWorldHeader(), and Terraria.IO.WorldFile.SaveWorldTiles().
Referenced by Terraria.IO.WorldFile.InternalSaveWorld().