Terraria Decompiled: Terraria.IO.WorldFile.LoadWorldTiles
LoadWorldTiles()
static void Terraria.IO.WorldFile.LoadWorldTiles (BinaryReader reader, bool[] importance) inline static
Definition at line 2493 of file WorldFile.cs.
        {
            for (int i = 0; i < Main.maxTilesX; i++)
            {
                float num = (float)i / (float)Main.maxTilesX;
                Main.statusText = string.Concat(new object[]
                {
                    Lang.gen[51].Value,
                    " ",
                    (int)((double)num * 100.0 + 1.0),
                    "%"
                });
                for (int j = 0; j < Main.maxTilesY; j++)
                {
                    int num2 = -1;
                    byte b3;
                    byte b2;
                    byte b = (b2 = (b3 = 0));
                    Tile tile = Main.tile[i, j];
                    byte b4 = reader.ReadByte();
                    bool flag = false;
                    if ((b4 & 1) == 1)
                    {
                        flag = true;
                        b2 = reader.ReadByte();
                    }
                    bool flag2 = false;
                    if (flag && (b2 & 1) == 1)
                    {
                        flag2 = true;
                        b = reader.ReadByte();
                    }
                    if (flag2 && (b & 1) == 1)
                    {
                        b3 = reader.ReadByte();
                    }
                    byte b5;
                    if ((b4 & 2) == 2)
                    {
                        tile.active(true);
                        if ((b4 & 32) == 32)
{
                            b5 = reader.ReadByte();
                            num2 = (int)reader.ReadByte();
                            num2 = (num2 << 8) | (int)b5;
                        }
                        else
{
                            num2 = (int)reader.ReadByte();
                        }
                        tile.type = (ushort)num2;
                        if (importance[num2])
{
                            tile.frameX = reader.ReadInt16();
                            tile.frameY = reader.ReadInt16();
                            if (tile.type == 144)
{
                                tile.frameY = 0;
                            }
                        }
                        else
{
                            tile.frameX = -1;
                            tile.frameY = -1;
                        }
                        if ((b & 8) == 8)
{
                            tile.color(reader.ReadByte());
                        }
                    }
                    if ((b4 & 4) == 4)
                    {
                        tile.wall = (ushort)reader.ReadByte();
                        if (tile.wall >= WallID.Count)
{
                            tile.wall = 0;
                        }
                        if ((b & 16) == 16)
{
                            tile.wallColor(reader.ReadByte());
                        }
                    }
                    b5 = (byte)((b4 & 24) >> 3);
                    if (b5 != 0)
                    {
                        tile.liquid = reader.ReadByte();
                        if ((b & 128) == 128)
{
                            tile.shimmer(true);
                        }
                        else if (b5 > 1)
{
                            if (b5 == 2)
{
                                tile.lava(true);
                            }
                            else
{
                                tile.honey(true);
                            }
                        }
                    }
                    if (b2 > 1)
                    {
                        if ((b2 & 2) == 2)
{
                            tile.wire(true);
                        }
                        if ((b2 & 4) == 4)
{
                            tile.wire2(true);
                        }
                        if ((b2 & 8) == 8)
{
                            tile.wire3(true);
                        }
                        b5 = (byte)((b2 & 112) >> 4);
                        if (b5 != 0 && TileID.Sets.SaveSlopes[(int)tile.type])
{
                            if (b5 == 1)
{
                                tile.halfBrick(true);
                            }
                            else
{
                                tile.slope(b5 - 1);
                            }
                        }
                    }
                    if (b > 1)
                    {
                        if ((b & 2) == 2)
{
                            tile.actuator(true);
                        }
                        if ((b & 4) == 4)
{
                            tile.inActive(true);
                        }
                        if ((b & 32) == 32)
{
                            tile.wire4(true);
                        }
                        if ((b & 64) == 64)
{
                            b5 = reader.ReadByte();
                            tile.wall = (ushort)(((int)b5 << 8) | (int)tile.wall);
                            if (tile.wall >= WallID.Count)
{
                                tile.wall = 0;
                            }
                        }
                    }
                    if (b3 > 1)
                    {
                        if ((b3 & 2) == 2)
{
                            tile.invisibleBlock(true);
                        }
                        if ((b3 & 4) == 4)
{
                            tile.invisibleWall(true);
                        }
                        if ((b3 & 8) == 8)
{
                            tile.fullbrightBlock(true);
                        }
                        if ((b3 & 16) == 16)
{
                            tile.fullbrightWall(true);
                        }
                    }
                    b5 = (byte)((b4 & 192) >> 6);
                    int k;
                    if (b5 == 0)
                    {
                        k = 0;
                    }
                    else if (b5 == 1)
                    {
                        k = (int)reader.ReadByte();
                    }
                    else
                    {
                        k = (int)reader.ReadInt16();
                    }
                    if (num2 != -1)
                    {
                        if ((double)j <= Main.worldSurface)
{
                            if ((double)(j + k) <= Main.worldSurface)
{
                                WorldGen.tileCounts[num2] += (k + 1) * 5;
                            }
                            else
{
                                int num3 = (int)(Main.worldSurface - (double)j + 1.0);
                                int num4 = k + 1 - num3;
                                WorldGen.tileCounts[num2] += num3 * 5 + num4;
                            }
                        }
                        else
{
                            WorldGen.tileCounts[num2] += k + 1;
                        }
                    }
                    while (k > 0)
                    {
                        j++;
                        Main.tile[i, j].CopyFrom(tile);
                        k--;
                    }
                }
            }
            WorldGen.AddUpAlignmentCounts(true);
            if (WorldFile._versionNumber < 105)
            {
                WorldGen.FixHearts();
            }
        }
References Terraria.IO.WorldFile._versionNumber, Terraria.Tile.active(), Terraria.Tile.actuator(), Terraria.WorldGen.AddUpAlignmentCounts(), Terraria.Tile.color(), Terraria.Tile.CopyFrom(), Terraria.ID.WallID.Count, Terraria.WorldGen.FixHearts(), Terraria.Tile.fullbrightBlock(), Terraria.Tile.fullbrightWall(), Terraria.Lang.gen, Terraria.Tile.halfBrick(), Terraria.Tile.honey(), Terraria.Tile.inActive(), int, Terraria.Tile.invisibleBlock(), Terraria.Tile.invisibleWall(), Terraria.Tile.lava(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, System.IO.BinaryReader.ReadByte(), System.IO.BinaryReader.ReadInt16(), Terraria.ID.TileID.Sets.SaveSlopes, Terraria.Tile.shimmer(), Terraria.Tile.slope(), Terraria.Main.tile, Terraria.WorldGen.tileCounts, Terraria.Tile.type, Terraria.Localization.LocalizedText.Value, Terraria.Tile.wall, Terraria.Tile.wallColor(), Terraria.Tile.wire(), Terraria.Tile.wire2(), Terraria.Tile.wire3(), Terraria.Tile.wire4(), and Terraria.Main.worldSurface.
Referenced by Terraria.IO.WorldFile.LoadWorld_Version2().