Terraria Decompiled: Terraria.IO.WorldFile.LoadNPCs
LoadNPCs()
static void Terraria.IO.WorldFile.LoadNPCs (BinaryReader reader) inline static
Definition at line 2885 of file WorldFile.cs.
        {
            if (WorldFile._versionNumber >= 268)
            {
                int num = reader.ReadInt32();
                while (num-- > 0)
                {
                    NPC.ShimmeredTownNPCs[reader.ReadInt32()] = true;
                }
            }
            int num2 = 0;
            bool flag = reader.ReadBoolean();
            while (flag)
            {
                NPC npc = Main.npc[num2];
                if (WorldFile._versionNumber >= 190)
                {
                    npc.SetDefaults(reader.ReadInt32(), default(NPCSpawnParams));
                }
                else
                {
                    npc.SetDefaults(NPCID.FromLegacyName(reader.ReadString()), default(NPCSpawnParams));
                }
                npc.GivenName = reader.ReadString();
                npc.position.X = reader.ReadSingle();
                npc.position.Y = reader.ReadSingle();
                npc.homeless = reader.ReadBoolean();
                npc.homeTileX = reader.ReadInt32();
                npc.homeTileY = reader.ReadInt32();
                if (WorldFile._versionNumber >= 213 && reader.ReadByte()[0])
                {
                    npc.townNpcVariationIndex = reader.ReadInt32();
                }
                if (WorldFile._versionNumber >= 315)
                {
                    npc.homelessDespawn = reader.ReadBoolean();
                }
                num2++;
                flag = reader.ReadBoolean();
            }
            if (WorldFile._versionNumber >= 140)
            {
                flag = reader.ReadBoolean();
                while (flag)
                {
                    NPC npc = Main.npc[num2];
                    if (WorldFile._versionNumber >= 190)
                    {
                        npc.SetDefaults(reader.ReadInt32(), default(NPCSpawnParams));
                    }
                    else
                    {
                        npc.SetDefaults(NPCID.FromLegacyName(reader.ReadString()), default(NPCSpawnParams));
                    }
                    npc.position = reader.ReadVector2();
                    num2++;
                    flag = reader.ReadBoolean();
                }
            }
            if (WorldFile._versionNumber < 251)
            {
                NPC.unlockedMerchantSpawn = NPC.AnyNPCs(17);
                NPC.unlockedDemolitionistSpawn = NPC.AnyNPCs(38);
                NPC.unlockedPartyGirlSpawn = NPC.AnyNPCs(208);
                NPC.unlockedDyeTraderSpawn = NPC.AnyNPCs(207);
                NPC.unlockedTruffleSpawn = NPC.AnyNPCs(160);
                NPC.unlockedArmsDealerSpawn = NPC.AnyNPCs(19);
                NPC.unlockedNurseSpawn = NPC.AnyNPCs(18);
                NPC.unlockedPrincessSpawn = NPC.AnyNPCs(663);
            }
        }
References Terraria.IO.WorldFile._versionNumber, Terraria.NPC.AnyNPCs(), Terraria.ID.NPCID.FromLegacyName(), Terraria.Main.npc, System.IO.BinaryReader.ReadBoolean(), System.IO.BinaryReader.ReadByte(), System.IO.BinaryReader.ReadInt32(), System.IO.BinaryReader.ReadSingle(), System.IO.BinaryReader.ReadString(), Terraria.NPC.SetDefaults(), and Terraria.NPC.ShimmeredTownNPCs.
Referenced by Terraria.IO.WorldFile.LoadWorld_Version2().