Terraria Decompiled: Terraria.IO.WorldFile.SaveTileEntities
SaveTileEntities()
static int Terraria.IO.WorldFile.SaveTileEntities (BinaryWriter writer) inline static
Definition at line 3349 of file WorldFile.cs.
        {
            object entityCreationLock = TileEntity.EntityCreationLock;
            lock (entityCreationLock)
            {
                writer.Write(TileEntity.ByID.Count);
                foreach (KeyValuePair<int, TileEntity> keyValuePair in TileEntity.ByID)
                {
                    TileEntity.Write(writer, keyValuePair.Value, false);
                }
            }
            return (int)writer.BaseStream.Position;
        }
References System.IO.BinaryWriter.BaseStream, Terraria.DataStructures.TileEntity.ByID, Terraria.DataStructures.TileEntity.EntityCreationLock, System.IO.Stream.Position, System.Collections.Generic.KeyValuePair< TKey, TValue >.Value, Terraria.DataStructures.TileEntity.Write(), and System.IO.BinaryWriter.Write().
Referenced by Terraria.IO.WorldFile.SaveWorld_Version2().