Terraria Decompiled: Terraria.IO.WorldFile.GetAllMetadata
GetAllMetadata()
static WorldFileData Terraria.IO.WorldFile.GetAllMetadata (string file, bool cloudSave) inline static
Definition at line 62 of file WorldFile.cs.
        {
            WorldFileData worldFileData;
            try
            {
                if (!FileUtilities.Exists(file, cloudSave))
                {
                    throw new FileNotFoundException(file);
                }
                using (Stream stream = (cloudSave ? new MemoryStream(SocialAPI.Cloud.Read(file)) : new FileStream(file, FileMode.Open)))
                {
                    using (BinaryReader binaryReader = new BinaryReader(stream))
                    {
                        int num = binaryReader.ReadInt32();
                        if (num > 319)
{
                            worldFileData = WorldFileData.FromInvalidWorld(file, cloudSave, StatusID.LaterVersion, new FileFormatException("File is from a later version of Terraria. '" + file + "'"));
                        }
                        else
{
                            WorldFileData worldFileData2 = new WorldFileData(file, cloudSave);
                            if (num >= 135)
{
                                worldFileData2.Metadata = FileMetadata.Read(binaryReader, FileType.World);
                            }
                            else
{
                                worldFileData2.Metadata = FileMetadata.FromCurrentSettings(FileType.World);
                            }
                            if (num >= 88)
{
                                binaryReader.ReadInt16();
                                stream.Position = (long)binaryReader.ReadInt32();
                            }
                            worldFileData2.Name = binaryReader.ReadString();
                            if (num >= 179)
{
                                string text;
                                if (num == 179)
{
                                    text = binaryReader.ReadInt32().ToString();
                                }
                                else
{
                                    text = binaryReader.ReadString();
                                }
                                worldFileData2.SetSeed(text);
                                worldFileData2.WorldGeneratorVersion = binaryReader.ReadUInt64();
                            }
                            else
{
                                worldFileData2.SetSeedToEmpty();
                                worldFileData2.WorldGeneratorVersion = 0UL;
                            }
                            if (num >= 181)
{
                                worldFileData2.UniqueId = new Guid(binaryReader.ReadBytes(16));
                            }
                            else
{
                                worldFileData2.UniqueId = Guid.Empty;
                            }
                            worldFileData2.WorldId = binaryReader.ReadInt32();
                            binaryReader.ReadInt32();
                            binaryReader.ReadInt32();
                            binaryReader.ReadInt32();
                            binaryReader.ReadInt32();
                            int num2 = binaryReader.ReadInt32();
                            int num3 = binaryReader.ReadInt32();
                            worldFileData2.SetWorldSize(num3, num2);
                            if (num >= 209)
{
                                worldFileData2.GameMode = binaryReader.ReadInt32();
                                if (num >= 222)
{
                                    worldFileData2.DrunkWorld = binaryReader.ReadBoolean();
                                    if (num >= 227)
{
                                        worldFileData2.ForTheWorthy = binaryReader.ReadBoolean();
                                    }
                                    if (num >= 238)
{
                                        worldFileData2.Anniversary = binaryReader.ReadBoolean();
                                    }
                                    if (num >= 239)
{
                                        worldFileData2.DontStarve = binaryReader.ReadBoolean();
                                    }
                                    if (num >= 241)
{
                                        worldFileData2.NotTheBees = binaryReader.ReadBoolean();
                                    }
                                    if (num >= 249)
{
                                        worldFileData2.RemixWorld = binaryReader.ReadBoolean();
                                    }
                                    if (num >= 266)
{
                                        worldFileData2.NoTrapsWorld = binaryReader.ReadBoolean();
                                    }
                                    if (num >= 267)
{
                                        worldFileData2.ZenithWorld = binaryReader.ReadBoolean();
                                    }
                                    else
{
                                        worldFileData2.ZenithWorld = worldFileData2.DrunkWorld && worldFileData2.RemixWorld;
                                        if (worldFileData2.ZenithWorld)
{
                                            worldFileData2.NoTrapsWorld = true;
                                        }
                                    }
                                    if (num >= 302)
{
                                        worldFileData2.SkyblockWorld = binaryReader.ReadBoolean();
                                    }
                                }
                            }
                            else if (num >= 112)
{
                                if (binaryReader.ReadBoolean())
{
                                    worldFileData2.GameMode = 1;
                                }
                                else
{
                                    worldFileData2.GameMode = 0;
                                }
                            }
                            if (num >= 141)
{
                                worldFileData2.CreationTime = DateTime.FromBinary(binaryReader.ReadInt64());
                            }
                            else if (!cloudSave)
{
                                worldFileData2.CreationTime = File.GetCreationTime(file);
                            }
                            else
{
                                worldFileData2.CreationTime = DateTime.Now;
                            }
                            if (num >= 284)
{
                                worldFileData2.LastPlayed = DateTime.FromBinary(binaryReader.ReadInt64());
                            }
                            else if (!cloudSave)
{
                                worldFileData2.LastPlayed = File.GetLastWriteTimeUtc(file);
                            }
                            else
{
                                worldFileData2.LastPlayed = default(DateTime);
                            }
                            if (num >= 63)
{
                                binaryReader.ReadByte();
                            }
                            if (num >= 44)
{
                                binaryReader.ReadInt32();
                                binaryReader.ReadInt32();
                                binaryReader.ReadInt32();
                                binaryReader.ReadInt32();
                                binaryReader.ReadInt32();
                                binaryReader.ReadInt32();
                                binaryReader.ReadInt32();
                            }
                            if (num >= 60)
{
                                binaryReader.ReadInt32();
                                binaryReader.ReadInt32();
                                binaryReader.ReadInt32();
                                binaryReader.ReadInt32();
                                binaryReader.ReadInt32();
                                binaryReader.ReadInt32();
                                binaryReader.ReadInt32();
                                binaryReader.ReadInt32();
                            }
                            if (num >= 61)
{
                                binaryReader.ReadInt32();
                                binaryReader.ReadInt32();
                            }
                            binaryReader.ReadInt32();
                            binaryReader.ReadInt32();
                            binaryReader.ReadDouble();
                            binaryReader.ReadDouble();
                            binaryReader.ReadDouble();
                            binaryReader.ReadBoolean();
                            binaryReader.ReadInt32();
                            binaryReader.ReadBoolean();
                            if (num >= 70)
{
                                binaryReader.ReadBoolean();
                            }
                            binaryReader.ReadInt32();
                            binaryReader.ReadInt32();
                            worldFileData2.HasCrimson = num >= 56 && binaryReader.ReadBoolean();
                            binaryReader.ReadBoolean();
                            binaryReader.ReadBoolean();
                            binaryReader.ReadBoolean();
                            if (num >= 66)
{
                                binaryReader.ReadBoolean();
                            }
                            if (num >= 44)
{
                                binaryReader.ReadBoolean();
                            }
                            if (num >= 44)
{
                                binaryReader.ReadBoolean();
                            }
                            if (num >= 44)
{
                                binaryReader.ReadBoolean();
                            }
                            if (num >= 44)
{
                                binaryReader.ReadBoolean();
                            }
                            if (num >= 64)
{
                                binaryReader.ReadBoolean();
                            }
                            if (num >= 64)
{
                                binaryReader.ReadBoolean();
                            }
                            if (num >= 118)
{
                                binaryReader.ReadBoolean();
                            }
                            if (num >= 29)
{
                                binaryReader.ReadBoolean();
                            }
                            if (num >= 29)
{
                                binaryReader.ReadBoolean();
                            }
                            if (num >= 34)
{
                                binaryReader.ReadBoolean();
                            }
                            if (num >= 29)
{
                                binaryReader.ReadBoolean();
                            }
                            if (num >= 32)
{
                                binaryReader.ReadBoolean();
                            }
                            if (num >= 37)
{
                                binaryReader.ReadBoolean();
                            }
                            if (num >= 56)
{
                                binaryReader.ReadBoolean();
                            }
                            binaryReader.ReadBoolean();
                            binaryReader.ReadBoolean();
                            binaryReader.ReadByte();
                            if (num >= 23)
{
                                binaryReader.ReadInt32();
                            }
                            worldFileData2.IsHardMode = num >= 23 && binaryReader.ReadBoolean();
                            if (num >= 257)
{
                                binaryReader.ReadBoolean();
                            }
                            binaryReader.ReadInt32();
                            binaryReader.ReadInt32();
                            binaryReader.ReadInt32();
                            binaryReader.ReadDouble();
                            if (num >= 118)
{
                                binaryReader.ReadDouble();
                            }
                            if (num >= 113)
{
                                binaryReader.ReadByte();
                            }
                            if (num >= 53)
{
                                binaryReader.ReadBoolean();
                                binaryReader.ReadInt32();
                                binaryReader.ReadSingle();
                            }
                            if (num >= 54)
{
                                binaryReader.ReadInt32();
                                binaryReader.ReadInt32();
                                binaryReader.ReadInt32();
                            }
                            if (num >= 55)
{
                                binaryReader.ReadByte();
                                binaryReader.ReadByte();
                                binaryReader.ReadByte();
                            }
                            if (num >= 60)
{
                                binaryReader.ReadByte();
                                binaryReader.ReadByte();
                                binaryReader.ReadByte();
                                binaryReader.ReadByte();
                                binaryReader.ReadByte();
                            }
                            if (num >= 60)
{
                                binaryReader.ReadInt32();
                            }
                            if (num >= 62)
{
                                binaryReader.ReadInt16();
                            }
                            if (num >= 88)
{
                                binaryReader.ReadSingle();
                            }
                            if (num < 95)
{
                                worldFileData = worldFileData2;
                            }
                            else
{
                                for (int i = binaryReader.ReadInt32(); i > 0; i--)
{
                                    binaryReader.ReadString();
                                }
                                if (num < 99)
{
                                    worldFileData = worldFileData2;
                                }
                                else
{
                                    binaryReader.ReadBoolean();
                                    if (num < 101)
{
                                        worldFileData = worldFileData2;
                                    }
                                    else
{
                                        binaryReader.ReadInt32();
                                        if (num < 104)
{
                                            worldFileData = worldFileData2;
                                        }
                                        else
{
                                            binaryReader.ReadBoolean();
                                            if (num >= 129)
{
                                                binaryReader.ReadBoolean();
                                            }
                                            if (num >= 201)
{
                                                binaryReader.ReadBoolean();
                                            }
                                            if (num >= 107)
{
                                                binaryReader.ReadInt32();
                                            }
                                            if (num >= 108)
{
                                                binaryReader.ReadInt32();
                                            }
                                            if (num < 109)
{
                                                worldFileData = worldFileData2;
                                            }
                                            else
{
                                                BannerSystem.ValidateWorld(binaryReader, num);
                                                if (num < 128)
{
                                                    worldFileData = worldFileData2;
                                                }
                                                else
{
                                                    binaryReader.ReadBoolean();
                                                    if (num < 131)
{
                                                        worldFileData = worldFileData2;
                                                    }
                                                    else
{
                                                        binaryReader.ReadBoolean();
                                                        binaryReader.ReadBoolean();
                                                        binaryReader.ReadBoolean();
                                                        worldFileData2.DefeatedMoonlord = binaryReader.ReadBoolean();
                                                        worldFileData = worldFileData2;
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                worldFileData = WorldFileData.FromInvalidWorld(file, cloudSave, StatusID.UnknownError, ex);
            }
            return worldFileData;
        }
References Terraria.Social.SocialAPI.Cloud, System.Guid.Empty, Terraria.Utilities.FileUtilities.Exists(), System.DateTime.FromBinary(), Terraria.IO.FileMetadata.FromCurrentSettings(), Terraria.IO.WorldFileData.FromInvalidWorld(), System.IO.File.GetCreationTime(), System.IO.File.GetLastWriteTimeUtc(), Terraria.ID.StatusID.LaterVersion, long, System.DateTime.Now, Terraria.IO.FileMetadata.Read(), System.IO.BinaryReader.ReadBoolean(), System.IO.BinaryReader.ReadByte(), System.IO.BinaryReader.ReadBytes(), System.IO.BinaryReader.ReadDouble(), System.IO.BinaryReader.ReadInt16(), System.IO.BinaryReader.ReadInt32(), System.IO.BinaryReader.ReadInt64(), System.IO.BinaryReader.ReadSingle(), System.IO.BinaryReader.ReadString(), System.IO.BinaryReader.ReadUInt64(), Terraria.IO.WorldFileData.RemixWorld, Terraria.IO.WorldFileData.SetSeed(), Terraria.IO.WorldFileData.SetSeedToEmpty(), Terraria.IO.WorldFileData.SetWorldSize(), System.text, Terraria.ID.StatusID.UnknownError, Terraria.GameContent.BannerSystem.ValidateWorld(), and Terraria.IO.WorldFileData.ZenithWorld.
Referenced by Terraria.Main.LoadDedConfig(), Terraria.Main.LoadWorlds(), Terraria.Main.SetWorld(), and Terraria.GameContent.UI.States.UIWorkshopWorldImport.UpdateWorkshopWorldList().