Terraria Decompiled: Terraria.IO.WorldFile.SaveWorldHeader
SaveWorldHeader()
static int Terraria.IO.WorldFile.SaveWorldHeader (BinaryWriter writer) inline static
Definition at line 1158 of file WorldFile.cs.
        {
            writer.Write(Main.worldName);
            writer.Write(Main.ActiveWorldFileData.SeedText);
            writer.Write(Main.ActiveWorldFileData.WorldGeneratorVersion);
            writer.Write(Main.ActiveWorldFileData.UniqueId.ToByteArray());
            writer.Write(Main.ActiveWorldFileData.WorldId);
            writer.Write((int)Main.leftWorld);
            writer.Write((int)Main.rightWorld);
            writer.Write((int)Main.topWorld);
            writer.Write((int)Main.bottomWorld);
            writer.Write(Main.maxTilesY);
            writer.Write(Main.maxTilesX);
            writer.Write(Main.GameMode);
            writer.Write(Main.drunkWorld);
            writer.Write(Main.getGoodWorld);
            writer.Write(Main.tenthAnniversaryWorld);
            writer.Write(Main.dontStarveWorld);
            writer.Write(Main.notTheBeesWorld);
            writer.Write(Main.remixWorld);
            writer.Write(Main.noTrapsWorld);
            writer.Write(Main.zenithWorld);
            writer.Write(Main.skyblockWorld);
            writer.Write(Main.ActiveWorldFileData.CreationTime.ToBinary());
            writer.Write(DateTime.UtcNow.ToBinary());
            writer.Write((byte)Main.moonType);
            writer.Write(Main.treeX[0]);
            writer.Write(Main.treeX[1]);
            writer.Write(Main.treeX[2]);
            writer.Write(Main.treeStyle[0]);
            writer.Write(Main.treeStyle[1]);
            writer.Write(Main.treeStyle[2]);
            writer.Write(Main.treeStyle[3]);
            writer.Write(Main.caveBackX[0]);
            writer.Write(Main.caveBackX[1]);
            writer.Write(Main.caveBackX[2]);
            writer.Write(Main.caveBackStyle[0]);
            writer.Write(Main.caveBackStyle[1]);
            writer.Write(Main.caveBackStyle[2]);
            writer.Write(Main.caveBackStyle[3]);
            writer.Write(Main.iceBackStyle);
            writer.Write(Main.jungleBackStyle);
            writer.Write(Main.hellBackStyle);
            writer.Write(Main.spawnTileX);
            writer.Write(Main.spawnTileY);
            writer.Write(Main.worldSurface);
            writer.Write(Main.rockLayer);
            writer.Write(WorldFile._tempTime);
            writer.Write(WorldFile._tempDayTime);
            writer.Write(WorldFile._tempMoonPhase);
            writer.Write(WorldFile._tempBloodMoon);
            writer.Write(WorldFile._tempEclipse);
            writer.Write(Main.dungeonX);
            writer.Write(Main.dungeonY);
            writer.Write(WorldGen.crimson);
            writer.Write(NPC.downedBoss1);
            writer.Write(NPC.downedBoss2);
            writer.Write(NPC.downedBoss3);
            writer.Write(NPC.downedQueenBee);
            writer.Write(NPC.downedMechBoss1);
            writer.Write(NPC.downedMechBoss2);
            writer.Write(NPC.downedMechBoss3);
            writer.Write(NPC.downedMechBossAny);
            writer.Write(NPC.downedPlantBoss);
            writer.Write(NPC.downedGolemBoss);
            writer.Write(NPC.downedSlimeKing);
            writer.Write(NPC.savedGoblin);
            writer.Write(NPC.savedWizard);
            writer.Write(NPC.savedMech);
            writer.Write(NPC.downedGoblins);
            writer.Write(NPC.downedClown);
            writer.Write(NPC.downedFrost);
            writer.Write(NPC.downedPirates);
            writer.Write(WorldGen.shadowOrbSmashed);
            writer.Write(WorldGen.spawnMeteor);
            writer.Write((byte)WorldGen.shadowOrbCount);
            writer.Write(WorldGen.altarCount);
            writer.Write(Main.hardMode);
            writer.Write(Main.afterPartyOfDoom);
            writer.Write(Main.invasionDelay);
            writer.Write(Main.invasionSize);
            writer.Write(Main.invasionType);
            writer.Write(Main.invasionX);
            writer.Write(Main.slimeRainTime);
            writer.Write((byte)Main.sundialCooldown);
            writer.Write(WorldFile._tempRaining);
            writer.Write(WorldFile._tempRainTime);
            writer.Write(WorldFile._tempMaxRain);
            writer.Write(WorldGen.SavedOreTiers.Cobalt);
            writer.Write(WorldGen.SavedOreTiers.Mythril);
            writer.Write(WorldGen.SavedOreTiers.Adamantite);
            writer.Write((byte)WorldGen.treeBG1);
            writer.Write((byte)WorldGen.corruptBG);
            writer.Write((byte)WorldGen.jungleBG);
            writer.Write((byte)WorldGen.snowBG);
            writer.Write((byte)WorldGen.hallowBG);
            writer.Write((byte)WorldGen.crimsonBG);
            writer.Write((byte)WorldGen.desertBG);
            writer.Write((byte)WorldGen.oceanBG);
            writer.Write((int)Main.cloudBGActive);
            writer.Write((short)Main.numClouds);
            writer.Write(Main.windSpeedTarget);
            writer.Write(Main.anglerWhoFinishedToday.Count);
            for (int i = 0; i < Main.anglerWhoFinishedToday.Count; i++)
            {
                writer.Write(Main.anglerWhoFinishedToday[i]);
            }
            writer.Write(NPC.savedAngler);
            writer.Write(Main.anglerQuest);
            writer.Write(NPC.savedStylist);
            writer.Write(NPC.savedTaxCollector);
            writer.Write(NPC.savedGolfer);
            writer.Write(Main.invasionSizeStart);
            writer.Write(WorldFile._tempCultistDelay);
            BannerSystem.Save(writer);
            writer.Write(Main.fastForwardTimeToDawn);
            writer.Write(NPC.downedFishron);
            writer.Write(NPC.downedMartians);
            writer.Write(NPC.downedAncientCultist);
            writer.Write(NPC.downedMoonlord);
            writer.Write(NPC.downedHalloweenKing);
            writer.Write(NPC.downedHalloweenTree);
            writer.Write(NPC.downedChristmasIceQueen);
            writer.Write(NPC.downedChristmasSantank);
            writer.Write(NPC.downedChristmasTree);
            writer.Write(NPC.downedTowerSolar);
            writer.Write(NPC.downedTowerVortex);
            writer.Write(NPC.downedTowerNebula);
            writer.Write(NPC.downedTowerStardust);
            writer.Write(NPC.TowerActiveSolar);
            writer.Write(NPC.TowerActiveVortex);
            writer.Write(NPC.TowerActiveNebula);
            writer.Write(NPC.TowerActiveStardust);
            writer.Write(NPC.LunarApocalypseIsUp);
            writer.Write(WorldFile._tempPartyManual);
            writer.Write(WorldFile._tempPartyGenuine);
            writer.Write(WorldFile._tempPartyCooldown);
            writer.Write(WorldFile.TempPartyCelebratingNPCs.Count);
            for (int j = 0; j < WorldFile.TempPartyCelebratingNPCs.Count; j++)
            {
                writer.Write(WorldFile.TempPartyCelebratingNPCs[j]);
            }
            writer.Write(WorldFile._tempSandstormHappening);
            writer.Write(WorldFile._tempSandstormTimeLeft);
            writer.Write(WorldFile._tempSandstormSeverity);
            writer.Write(WorldFile._tempSandstormIntendedSeverity);
            writer.Write(NPC.savedBartender);
            DD2Event.Save(writer);
            writer.Write((byte)WorldGen.mushroomBG);
            writer.Write((byte)WorldGen.underworldBG);
            writer.Write((byte)WorldGen.treeBG2);
            writer.Write((byte)WorldGen.treeBG3);
            writer.Write((byte)WorldGen.treeBG4);
            writer.Write(NPC.combatBookWasUsed);
            writer.Write(WorldFile._tempLanternNightCooldown);
            writer.Write(WorldFile._tempLanternNightGenuine);
            writer.Write(WorldFile._tempLanternNightManual);
            writer.Write(WorldFile._tempLanternNightNextNightIsGenuine);
            WorldGen.TreeTops.Save(writer);
            writer.Write(Main.forceHalloweenForToday);
            writer.Write(Main.forceXMasForToday);
            writer.Write(WorldGen.SavedOreTiers.Copper);
            writer.Write(WorldGen.SavedOreTiers.Iron);
            writer.Write(WorldGen.SavedOreTiers.Silver);
            writer.Write(WorldGen.SavedOreTiers.Gold);
            writer.Write(NPC.boughtCat);
            writer.Write(NPC.boughtDog);
            writer.Write(NPC.boughtBunny);
            writer.Write(NPC.downedEmpressOfLight);
            writer.Write(NPC.downedQueenSlime);
            writer.Write(NPC.downedDeerclops);
            writer.Write(NPC.unlockedSlimeBlueSpawn);
            writer.Write(NPC.unlockedMerchantSpawn);
            writer.Write(NPC.unlockedDemolitionistSpawn);
            writer.Write(NPC.unlockedPartyGirlSpawn);
            writer.Write(NPC.unlockedDyeTraderSpawn);
            writer.Write(NPC.unlockedTruffleSpawn);
            writer.Write(NPC.unlockedArmsDealerSpawn);
            writer.Write(NPC.unlockedNurseSpawn);
            writer.Write(NPC.unlockedPrincessSpawn);
            writer.Write(NPC.combatBookVolumeTwoWasUsed);
            writer.Write(NPC.peddlersSatchelWasUsed);
            writer.Write(NPC.unlockedSlimeGreenSpawn);
            writer.Write(NPC.unlockedSlimeOldSpawn);
            writer.Write(NPC.unlockedSlimePurpleSpawn);
            writer.Write(NPC.unlockedSlimeRainbowSpawn);
            writer.Write(NPC.unlockedSlimeRedSpawn);
            writer.Write(NPC.unlockedSlimeYellowSpawn);
            writer.Write(NPC.unlockedSlimeCopperSpawn);
            writer.Write(Main.fastForwardTimeToDusk);
            writer.Write((byte)Main.moondialCooldown);
            writer.Write(Main.forceHalloweenForever);
            writer.Write(Main.forceXMasForever);
            writer.Write(Main.vampireSeed);
            writer.Write(Main.infectedSeed);
            writer.Write(WorldFile._tempMeteorShowerCount);
            writer.Write(WorldFile._tempCoinRain);
            writer.Write(Main.teamBasedSpawnsSeed);
            ExtraSpawnPointManager.Write(writer, false);
            writer.Write(Main.dualDungeonsSeed);
            writer.Write(WorldGen.Manifest.Serialize());
            return (int)writer.BaseStream.Position;
        }
References Terraria.IO.WorldFile._tempBloodMoon, Terraria.IO.WorldFile._tempCoinRain, Terraria.IO.WorldFile._tempCultistDelay, Terraria.IO.WorldFile._tempDayTime, Terraria.IO.WorldFile._tempEclipse, Terraria.IO.WorldFile._tempLanternNightCooldown, Terraria.IO.WorldFile._tempLanternNightGenuine, Terraria.IO.WorldFile._tempLanternNightManual, Terraria.IO.WorldFile._tempLanternNightNextNightIsGenuine, Terraria.IO.WorldFile._tempMaxRain, Terraria.IO.WorldFile._tempMeteorShowerCount, Terraria.IO.WorldFile._tempMoonPhase, Terraria.IO.WorldFile._tempPartyCooldown, Terraria.IO.WorldFile._tempPartyGenuine, Terraria.IO.WorldFile._tempPartyManual, Terraria.IO.WorldFile._tempRaining, Terraria.IO.WorldFile._tempRainTime, Terraria.IO.WorldFile._tempSandstormHappening, Terraria.IO.WorldFile._tempSandstormIntendedSeverity, Terraria.IO.WorldFile._tempSandstormSeverity, Terraria.IO.WorldFile._tempSandstormTimeLeft, Terraria.IO.WorldFile._tempTime, Terraria.Main.ActiveWorldFileData, Terraria.WorldGen.SavedOreTiers.Adamantite, Terraria.Main.afterPartyOfDoom, Terraria.WorldGen.altarCount, Terraria.Main.anglerQuest, Terraria.Main.anglerWhoFinishedToday, System.IO.BinaryWriter.BaseStream, Terraria.Main.bottomWorld, Terraria.NPC.boughtBunny, Terraria.NPC.boughtCat, Terraria.NPC.boughtDog, Terraria.Main.caveBackStyle, Terraria.Main.caveBackX, Terraria.Main.cloudBGActive, Terraria.WorldGen.SavedOreTiers.Cobalt, Terraria.NPC.combatBookVolumeTwoWasUsed, Terraria.NPC.combatBookWasUsed, Terraria.WorldGen.SavedOreTiers.Copper, Terraria.WorldGen.corruptBG, System.Collections.Generic.List< T >.Count, Terraria.WorldGen.crimson, Terraria.WorldGen.crimsonBG, Terraria.WorldGen.desertBG, Terraria.Main.dontStarveWorld, Terraria.NPC.downedAncientCultist, Terraria.NPC.downedBoss1, Terraria.NPC.downedBoss2, Terraria.NPC.downedBoss3, Terraria.NPC.downedChristmasIceQueen, Terraria.NPC.downedChristmasSantank, Terraria.NPC.downedChristmasTree, Terraria.NPC.downedClown, Terraria.NPC.downedDeerclops, Terraria.NPC.downedEmpressOfLight, Terraria.NPC.downedFishron, Terraria.NPC.downedFrost, Terraria.NPC.downedGoblins, Terraria.NPC.downedGolemBoss, Terraria.NPC.downedHalloweenKing, Terraria.NPC.downedHalloweenTree, Terraria.NPC.downedMartians, Terraria.NPC.downedMechBoss1, Terraria.NPC.downedMechBoss2, Terraria.NPC.downedMechBoss3, Terraria.NPC.downedMechBossAny, Terraria.NPC.downedMoonlord, Terraria.NPC.downedPirates, Terraria.NPC.downedPlantBoss, Terraria.NPC.downedQueenBee, Terraria.NPC.downedQueenSlime, Terraria.NPC.downedSlimeKing, Terraria.NPC.downedTowerNebula, Terraria.NPC.downedTowerSolar, Terraria.NPC.downedTowerStardust, Terraria.NPC.downedTowerVortex, Terraria.Main.drunkWorld, Terraria.Main.dualDungeonsSeed, Terraria.Main.dungeonX, Terraria.Main.dungeonY, Terraria.Main.fastForwardTimeToDawn, Terraria.Main.fastForwardTimeToDusk, Terraria.Main.forceHalloweenForever, Terraria.Main.forceHalloweenForToday, Terraria.Main.forceXMasForever, Terraria.Main.forceXMasForToday, Terraria.Main.GameMode, Terraria.Main.getGoodWorld, Terraria.WorldGen.SavedOreTiers.Gold, Terraria.WorldGen.hallowBG, Terraria.Main.hardMode, Terraria.Main.hellBackStyle, Terraria.Main.iceBackStyle, Terraria.Main.infectedSeed, Terraria.Main.invasionDelay, Terraria.Main.invasionSize, Terraria.Main.invasionSizeStart, Terraria.Main.invasionType, Terraria.Main.invasionX, Terraria.WorldGen.SavedOreTiers.Iron, Terraria.Main.jungleBackStyle, Terraria.WorldGen.jungleBG, Terraria.Main.leftWorld, Terraria.NPC.LunarApocalypseIsUp, Terraria.WorldGen.Manifest, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.moondialCooldown, Terraria.Main.moonType, Terraria.WorldGen.mushroomBG, Terraria.WorldGen.SavedOreTiers.Mythril, Terraria.Main.noTrapsWorld, Terraria.Main.notTheBeesWorld, Terraria.Main.numClouds, Terraria.WorldGen.oceanBG, Terraria.NPC.peddlersSatchelWasUsed, System.IO.Stream.Position, Terraria.Main.remixWorld, Terraria.Main.rightWorld, Terraria.Main.rockLayer, Terraria.GameContent.BannerSystem.Save(), Terraria.GameContent.Events.DD2Event.Save(), Terraria.GameContent.TreeTopsInfo.Save(), Terraria.NPC.savedAngler, Terraria.NPC.savedBartender, Terraria.NPC.savedGoblin, Terraria.NPC.savedGolfer, Terraria.NPC.savedMech, Terraria.NPC.savedStylist, Terraria.NPC.savedTaxCollector, Terraria.NPC.savedWizard, Terraria.WorldBuilding.WorldManifest.Serialize(), Terraria.WorldGen.shadowOrbCount, Terraria.WorldGen.shadowOrbSmashed, Terraria.WorldGen.SavedOreTiers.Silver, Terraria.Main.skyblockWorld, Terraria.Main.slimeRainTime, Terraria.WorldGen.snowBG, Terraria.WorldGen.spawnMeteor, Terraria.Main.spawnTileX, Terraria.Main.spawnTileY, Terraria.Main.sundialCooldown, Terraria.Main.teamBasedSpawnsSeed, Terraria.IO.WorldFile.TempPartyCelebratingNPCs, Terraria.Main.tenthAnniversaryWorld, System.DateTime.ToBinary(), Terraria.Main.topWorld, Terraria.NPC.TowerActiveNebula, Terraria.NPC.TowerActiveSolar, Terraria.NPC.TowerActiveStardust, Terraria.NPC.TowerActiveVortex, Terraria.WorldGen.treeBG1, Terraria.WorldGen.treeBG2, Terraria.WorldGen.treeBG3, Terraria.WorldGen.treeBG4, Terraria.Main.treeStyle, Terraria.WorldGen.TreeTops, Terraria.Main.treeX, Terraria.WorldGen.underworldBG, Terraria.NPC.unlockedArmsDealerSpawn, Terraria.NPC.unlockedDemolitionistSpawn, Terraria.NPC.unlockedDyeTraderSpawn, Terraria.NPC.unlockedMerchantSpawn, Terraria.NPC.unlockedNurseSpawn, Terraria.NPC.unlockedPartyGirlSpawn, Terraria.NPC.unlockedPrincessSpawn, Terraria.NPC.unlockedSlimeBlueSpawn, Terraria.NPC.unlockedSlimeCopperSpawn, Terraria.NPC.unlockedSlimeGreenSpawn, Terraria.NPC.unlockedSlimeOldSpawn, Terraria.NPC.unlockedSlimePurpleSpawn, Terraria.NPC.unlockedSlimeRainbowSpawn, Terraria.NPC.unlockedSlimeRedSpawn, Terraria.NPC.unlockedSlimeYellowSpawn, Terraria.NPC.unlockedTruffleSpawn, System.DateTime.UtcNow, Terraria.Main.vampireSeed, Terraria.Main.windSpeedTarget, Terraria.Main.worldName, Terraria.Main.worldSurface, Terraria.GameContent.ExtraSpawnPointManager.Write(), System.IO.BinaryWriter.Write(), and Terraria.Main.zenithWorld.
Referenced by Terraria.IO.WorldFile.SaveWorld_Version2().