Terraria Decompiled: Terraria.IO.WorldFile.SaveChests
SaveChests()
static int Terraria.IO.WorldFile.SaveChests (BinaryWriter writer) inline static
Definition at line 1564 of file WorldFile.cs.
        {
            short num = 0;
            for (int i = 0; i < 8000; i++)
            {
                Chest chest = Main.chest[i];
                if (chest != null)
                {
                    bool flag = false;
                    for (int j = chest.x; j <= chest.x + 1; j++)
                    {
                        for (int k = chest.y; k <= chest.y + 1; k++)
{
                            if (j < 0 || k < 0 || j >= Main.maxTilesX || k >= Main.maxTilesY)
{
                                flag = true;
                                break;
                            }
                            Tile tile = Main.tile[j, k];
                            if (!tile.active() || !Main.tileContainer[(int)tile.type])
{
                                flag = true;
                                break;
                            }
                        }
                    }
                    if (flag)
                    {
                        Chest.RemoveChest(i);
                    }
                    else
                    {
                        num += 1;
                    }
                }
            }
            writer.Write(num);
            for (int i = 0; i < 8000; i++)
            {
                Chest chest = Main.chest[i];
                if (chest != null)
                {
                    writer.Write(chest.x);
                    writer.Write(chest.y);
                    writer.Write(chest.name);
                    writer.Write(chest.maxItems);
                    for (int l = 0; l < chest.maxItems; l++)
                    {
                        Item item = chest.item[l];
                        if (item == null || ItemID.Sets.ItemsThatShouldNotBeInInventory[item.type])
{
                            writer.Write(0);
                        }
                        else
{
                            if (item.stack < 0)
{
                                item.stack = 1;
                            }
                            writer.Write((short)item.stack);
                            if (item.stack > 0)
{
                                writer.Write(item.type);
                                writer.Write(item.prefix);
                            }
                        }
                    }
                }
            }
            return (int)writer.BaseStream.Position;
        }
References Terraria.Tile.active(), System.IO.BinaryWriter.BaseStream, Terraria.Main.chest, int, System.item, Terraria.Chest.item, Terraria.ID.ItemID.Sets.ItemsThatShouldNotBeInInventory, Terraria.Chest.maxItems, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Chest.name, System.IO.Stream.Position, Terraria.Chest.RemoveChest(), Terraria.Main.tile, Terraria.Main.tileContainer, Terraria.Tile.type, System.IO.BinaryWriter.Write(), Terraria.Chest.x, and Terraria.Chest.y.
Referenced by Terraria.IO.WorldFile.SaveWorld_Version2().