Terraria Decompiled: Terraria.IO.WorldFile.LoadWeightedPressurePlates
LoadWeightedPressurePlates()
static void Terraria.IO.WorldFile.LoadWeightedPressurePlates (BinaryReader reader) inline static
Definition at line 3426 of file WorldFile.cs.
        {
            PressurePlateHelper.Reset();
            PressurePlateHelper.NeedsFirstUpdate = true;
            int num = reader.ReadInt32();
            for (int i = 0; i < num; i++)
            {
                Point point = new Point(reader.ReadInt32(), reader.ReadInt32());
                PressurePlateHelper.PressurePlatesPressed.Add(point, new bool[255]);
            }
        }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), Terraria.GameContent.PressurePlateHelper.PressurePlatesPressed, System.IO.BinaryReader.ReadInt32(), and Terraria.GameContent.PressurePlateHelper.Reset().
Referenced by Terraria.IO.WorldFile.LoadWorld_Version2().