Terraria Decompiled: Terraria.IO.WorldFile.LoadFooter
LoadFooter()
static int Terraria.IO.WorldFile.LoadFooter (BinaryReader reader) inline static
Definition at line 2993 of file WorldFile.cs.
        {
            if (!reader.ReadBoolean())
            {
                return StatusID.BadFooter;
            }
            if (reader.ReadString() != Main.worldName)
            {
                return StatusID.BadFooter;
            }
            if (reader.ReadInt32() != Main.ActiveWorldFileData.WorldId)
            {
                return StatusID.BadFooter;
            }
            return StatusID.Ok;
        }
References Terraria.Main.ActiveWorldFileData, Terraria.ID.StatusID.BadFooter, Terraria.ID.StatusID.Ok, System.IO.BinaryReader.ReadBoolean(), System.IO.BinaryReader.ReadInt32(), System.IO.BinaryReader.ReadString(), and Terraria.Main.worldName.
Referenced by Terraria.IO.WorldFile.LoadWorld_Version2().