Terraria Decompiled: Terraria.IO.WorldFile.FixAgainstExploits
FixAgainstExploits()
static void Terraria.IO.WorldFile.FixAgainstExploits () inline static private
Definition at line 1830 of file WorldFile.cs.
        {
            for (int i = 0; i < 8000; i++)
            {
                Chest chest = Main.chest[i];
                if (chest != null)
                {
                    chest.FixLoadedData();
                }
            }
            foreach (TileEntity tileEntity in TileEntity.ByID.Values)
            {
                IFixLoadedData fixLoadedData = tileEntity as IFixLoadedData;
                if (fixLoadedData != null)
                {
                    fixLoadedData.FixLoadedData();
                }
            }
            for (int j = 0; j < Main.npc.Length; j++)
            {
                NPC npc = Main.npc[j];
                if (npc.active && npc.townNPC && npc.type != 368 && npc.type != 37 && !npc.homeless)
                {
                    bool flag = WorldGen.StartRoomCheck(npc.homeTileX, npc.homeTileY - 1, NoRoomCheckFeedback.WithoutText);
                    if (!flag)
                    {
                        Point point;
                        if (WorldGen.TownManager.HasRoom(npc.type, out point))
{
                            npc.homeTileX = point.X;
                            npc.homeTileY = point.Y;
                            flag = WorldGen.StartRoomCheck(npc.homeTileX, npc.homeTileY - 1, NoRoomCheckFeedback.WithoutText);
                        }
                        if (!flag)
{
                            WorldGen.TownManager.KickOut(npc);
                            npc.homeless = true;
                        }
                    }
                }
            }
        }
References Terraria.NPC.active, Terraria.DataStructures.TileEntity.ByID, Terraria.Main.chest, Terraria.Chest.FixLoadedData(), Terraria.DataStructures.IFixLoadedData.FixLoadedData(), Terraria.GameContent.TownRoomManager.HasRoom(), Terraria.NPC.homeless, Terraria.NPC.homeTileX, Terraria.NPC.homeTileY, Terraria.GameContent.TownRoomManager.KickOut(), Terraria.Main.npc, Terraria.WorldGen.StartRoomCheck(), Terraria.WorldGen.TownManager, Terraria.NPC.townNPC, Terraria.NPC.type, Terraria.DataStructures.NoRoomCheckFeedback.WithoutText, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.IO.WorldFile.LoadWorld_LastMinuteFixes().