Terraria Decompiled: Terraria.IO.WorldFile.SaveWorldTiles
SaveWorldTiles()
static int Terraria.IO.WorldFile.SaveWorldTiles (BinaryWriter writer) inline static
Definition at line 1363 of file WorldFile.cs.
        {
            byte[] array = new byte[16];
            for (int i = 0; i < Main.maxTilesX; i++)
            {
                float num = (float)i / (float)Main.maxTilesX;
                Main.statusText = string.Concat(new object[]
                {
                    Lang.gen[49].Value,
                    " ",
                    (int)(num * 100f + 1f),
                    "%"
                });
                for (int j = 0; j < Main.maxTilesY; j++)
                {
                    Tile tile = Main.tile[i, j];
                    int num2 = 4;
                    byte b4;
                    byte b3;
                    byte b2;
                    byte b = (b2 = (b3 = (b4 = 0)));
                    bool flag = false;
                    if (tile.active())
                    {
                        flag = true;
                    }
                    if (flag)
                    {
                        b2 |= 2;
                        array[num2] = (byte)tile.type;
                        num2++;
                        if (tile.type > 255)
{
                            array[num2] = (byte)(tile.type >> 8);
                            num2++;
                            b2 |= 32;
                        }
                        if (Main.tileFrameImportant[(int)tile.type])
{
                            array[num2] = (byte)(tile.frameX & 255);
                            num2++;
                            array[num2] = (byte)(((int)tile.frameX & 65280) >> 8);
                            num2++;
                            array[num2] = (byte)(tile.frameY & 255);
                            num2++;
                            array[num2] = (byte)(((int)tile.frameY & 65280) >> 8);
                            num2++;
                        }
                        if (tile.color() != 0)
{
                            b3 |= 8;
                            array[num2] = tile.color();
                            num2++;
                        }
                    }
                    if (tile.wall != 0)
                    {
                        b2 |= 4;
                        array[num2] = (byte)tile.wall;
                        num2++;
                        if (tile.wallColor() != 0)
{
                            b3 |= 16;
                            array[num2] = tile.wallColor();
                            num2++;
                        }
                    }
                    if (tile.liquid != 0)
                    {
                        if (tile.shimmer())
{
                            b3 |= 128;
                            b2 |= 8;
                        }
                        else if (tile.lava())
{
                            b2 |= 16;
                        }
                        else if (tile.honey())
{
                            b2 |= 24;
                        }
                        else
{
                            b2 |= 8;
                        }
                        array[num2] = tile.liquid;
                        num2++;
                    }
                    if (tile.wire())
                    {
                        b |= 2;
                    }
                    if (tile.wire2())
                    {
                        b |= 4;
                    }
                    if (tile.wire3())
                    {
                        b |= 8;
                    }
                    int num3;
                    if (tile.halfBrick())
                    {
                        num3 = 16;
                    }
                    else if (tile.slope() != 0)
                    {
                        num3 = (int)(tile.slope() + 1) << 4;
                    }
                    else
                    {
                        num3 = 0;
                    }
                    b |= (byte)num3;
                    if (tile.actuator())
                    {
                        b3 |= 2;
                    }
                    if (tile.inActive())
                    {
                        b3 |= 4;
                    }
                    if (tile.wire4())
                    {
                        b3 |= 32;
                    }
                    if (tile.wall > 255)
                    {
                        array[num2] = (byte)(tile.wall >> 8);
                        num2++;
                        b3 |= 64;
                    }
                    if (tile.invisibleBlock())
                    {
                        b4 |= 2;
                    }
                    if (tile.invisibleWall())
                    {
                        b4 |= 4;
                    }
                    if (tile.fullbrightBlock())
                    {
                        b4 |= 8;
                    }
                    if (tile.fullbrightWall())
                    {
                        b4 |= 16;
                    }
                    int num4 = 3;
                    if (b4 != 0)
                    {
                        b3 |= 1;
                        array[num4] = b4;
                        num4--;
                    }
                    if (b3 != 0)
                    {
                        b |= 1;
                        array[num4] = b3;
                        num4--;
                    }
                    if (b != 0)
                    {
                        b2 |= 1;
                        array[num4] = b;
                        num4--;
                    }
                    short num5 = 0;
                    int num6 = j + 1;
                    int num7 = Main.maxTilesY - j - 1;
                    while (num7 > 0 && tile.isTheSameAs(Main.tile[i, num6]) && TileID.Sets.AllowsSaveCompressionBatching[(int)tile.type])
                    {
                        num5 += 1;
                        num7--;
                        num6++;
                    }
                    j += (int)num5;
                    if (num5 > 0)
                    {
                        array[num2] = (byte)(num5 & 255);
                        num2++;
                        if (num5 > 255)
{
                            b2 |= 128;
                            array[num2] = (byte)(((int)num5 & 65280) >> 8);
                            num2++;
                        }
                        else
{
                            b2 |= 64;
                        }
                    }
                    array[num4] = b2;
                    writer.Write(array, num4, num2 - num4);
                }
            }
            return (int)writer.BaseStream.Position;
        }
References Terraria.Tile.active(), Terraria.Tile.actuator(), Terraria.ID.TileID.Sets.AllowsSaveCompressionBatching, System.array, System.IO.BinaryWriter.BaseStream, Terraria.Tile.color(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Tile.fullbrightBlock(), Terraria.Tile.fullbrightWall(), Terraria.Lang.gen, Terraria.Tile.halfBrick(), Terraria.Tile.honey(), Terraria.Tile.inActive(), int, Terraria.Tile.invisibleBlock(), Terraria.Tile.invisibleWall(), Terraria.Tile.isTheSameAs(), Terraria.Tile.lava(), Terraria.Tile.liquid, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, System.IO.Stream.Position, Terraria.Tile.shimmer(), Terraria.Tile.slope(), Terraria.Main.tile, Terraria.Main.tileFrameImportant, Terraria.Tile.type, Terraria.Localization.LocalizedText.Value, Terraria.Tile.wall, Terraria.Tile.wallColor(), Terraria.Tile.wire(), Terraria.Tile.wire2(), Terraria.Tile.wire3(), Terraria.Tile.wire4(), and System.IO.BinaryWriter.Write().
Referenced by Terraria.IO.WorldFile.SaveWorld_Version2().