Terraria Decompiled: Terraria.IO.WorldFile.LoadSigns
LoadSigns()
static void Terraria.IO.WorldFile.LoadSigns (BinaryReader reader) inline static
Definition at line 2826 of file WorldFile.cs.
        {
            short num = reader.ReadInt16();
            int i;
            for (i = 0; i < (int)num; i++)
            {
                string text = reader.ReadString();
                int num2 = reader.ReadInt32();
                int num3 = reader.ReadInt32();
                Tile tile = Main.tile[num2, num3];
                Sign sign;
                if (tile.active() && Main.tileSign[(int)tile.type])
                {
                    sign = new Sign();
                    sign.text = text;
                    sign.x = num2;
                    sign.y = num3;
                }
                else
                {
                    sign = null;
                }
                Main.sign[i] = sign;
            }
            List<Point16> list = new List<Point16>();
            for (int j = 0; j < 32000; j++)
            {
                if (Main.sign[j] != null)
                {
                    Point16 point = new Point16(Main.sign[j].x, Main.sign[j].y);
                    if (list.Contains(point))
                    {
                        Main.sign[j] = null;
                    }
                    else
                    {
                        list.Add(point);
                    }
                }
            }
            while (i < 32000)
            {
                Main.sign[i] = null;
                i++;
            }
        }
References Terraria.Tile.active(), int, System.list, System.IO.BinaryReader.ReadInt16(), System.IO.BinaryReader.ReadInt32(), System.IO.BinaryReader.ReadString(), Terraria.Main.sign, System.text, Terraria.Main.tile, Terraria.Main.tileSign, Terraria.Tile.type, Terraria.Sign.x, and Terraria.Sign.y.
Referenced by Terraria.IO.WorldFile.LoadWorld_Version2().