Terraria Decompiled: Terraria.IO.WorldFile.LoadHeader
LoadHeader()
static void Terraria.IO.WorldFile.LoadHeader (BinaryReader reader) inline static
Definition at line 1924 of file WorldFile.cs.
        {
            int versionNumber = WorldFile._versionNumber;
            Main.worldName = reader.ReadString();
            if (versionNumber >= 179)
            {
                string text;
                if (versionNumber == 179)
                {
                    text = reader.ReadInt32().ToString();
                }
                else
                {
                    text = reader.ReadString();
                }
                Main.ActiveWorldFileData.SetSeed(text);
                Main.ActiveWorldFileData.WorldGeneratorVersion = reader.ReadUInt64();
            }
            if (versionNumber >= 181)
            {
                Main.ActiveWorldFileData.UniqueId = new Guid(reader.ReadBytes(16));
            }
            else
            {
                Main.ActiveWorldFileData.UniqueId = Guid.NewGuid();
            }
            Main.ActiveWorldFileData.WorldId = reader.ReadInt32();
            Main.leftWorld = (float)reader.ReadInt32();
            Main.rightWorld = (float)reader.ReadInt32();
            Main.topWorld = (float)reader.ReadInt32();
            Main.bottomWorld = (float)reader.ReadInt32();
            Main.maxTilesY = reader.ReadInt32();
            Main.maxTilesX = reader.ReadInt32();
            WorldGen.clearWorld();
            if (versionNumber >= 209)
            {
                Main.GameMode = reader.ReadInt32();
                if (versionNumber >= 222)
                {
                    Main.drunkWorld = reader.ReadBoolean();
                }
                if (versionNumber >= 227)
                {
                    Main.getGoodWorld = reader.ReadBoolean();
                }
                if (versionNumber >= 238)
                {
                    Main.tenthAnniversaryWorld = reader.ReadBoolean();
                }
                if (versionNumber >= 239)
                {
                    Main.dontStarveWorld = reader.ReadBoolean();
                }
                if (versionNumber >= 241)
                {
                    Main.notTheBeesWorld = reader.ReadBoolean();
                }
                if (versionNumber >= 249)
                {
                    Main.remixWorld = reader.ReadBoolean();
                }
                if (versionNumber >= 266)
                {
                    Main.noTrapsWorld = reader.ReadBoolean();
                }
                if (versionNumber >= 267)
                {
                    Main.zenithWorld = reader.ReadBoolean();
                }
                else
                {
                    Main.zenithWorld = Main.remixWorld && Main.drunkWorld;
                }
                if (versionNumber >= 302)
                {
                    Main.skyblockWorld = reader.ReadBoolean();
                }
            }
            else
            {
                if (versionNumber >= 112)
                {
                    Main.GameMode = (reader.ReadBoolean() ? 1 : 0);
                }
                else
                {
                    Main.GameMode = 0;
                }
                if (versionNumber == 208 && reader.ReadBoolean())
                {
                    Main.GameMode = 2;
                }
            }
            if (versionNumber >= 141)
            {
                Main.ActiveWorldFileData.CreationTime = DateTime.FromBinary(reader.ReadInt64());
            }
            if (versionNumber >= 284)
            {
                Main.ActiveWorldFileData.LastPlayed = DateTime.FromBinary(reader.ReadInt64());
            }
            Main.moonType = (int)reader.ReadByte();
            Main.treeX[0] = reader.ReadInt32();
            Main.treeX[1] = reader.ReadInt32();
            Main.treeX[2] = reader.ReadInt32();
            Main.treeStyle[0] = reader.ReadInt32();
            Main.treeStyle[1] = reader.ReadInt32();
            Main.treeStyle[2] = reader.ReadInt32();
            Main.treeStyle[3] = reader.ReadInt32();
            Main.caveBackX[0] = reader.ReadInt32();
            Main.caveBackX[1] = reader.ReadInt32();
            Main.caveBackX[2] = reader.ReadInt32();
            Main.caveBackStyle[0] = reader.ReadInt32();
            Main.caveBackStyle[1] = reader.ReadInt32();
            Main.caveBackStyle[2] = reader.ReadInt32();
            Main.caveBackStyle[3] = reader.ReadInt32();
            Main.iceBackStyle = reader.ReadInt32();
            Main.jungleBackStyle = reader.ReadInt32();
            Main.hellBackStyle = reader.ReadInt32();
            Main.spawnTileX = reader.ReadInt32();
            Main.spawnTileY = reader.ReadInt32();
            Main.worldSurface = reader.ReadDouble();
            Main.rockLayer = reader.ReadDouble();
            WorldFile._tempTime = reader.ReadDouble();
            WorldFile._tempDayTime = reader.ReadBoolean();
            WorldFile._tempMoonPhase = reader.ReadInt32();
            WorldFile._tempBloodMoon = reader.ReadBoolean();
            WorldFile._tempEclipse = reader.ReadBoolean();
            Main.eclipse = WorldFile._tempEclipse;
            Main.dungeonX = reader.ReadInt32();
            Main.dungeonY = reader.ReadInt32();
            WorldGen.crimson = reader.ReadBoolean();
            NPC.downedBoss1 = reader.ReadBoolean();
            NPC.downedBoss2 = reader.ReadBoolean();
            NPC.downedBoss3 = reader.ReadBoolean();
            NPC.downedQueenBee = reader.ReadBoolean();
            NPC.downedMechBoss1 = reader.ReadBoolean();
            NPC.downedMechBoss2 = reader.ReadBoolean();
            NPC.downedMechBoss3 = reader.ReadBoolean();
            NPC.downedMechBossAny = reader.ReadBoolean();
            NPC.downedPlantBoss = reader.ReadBoolean();
            NPC.downedGolemBoss = reader.ReadBoolean();
            if (versionNumber >= 118)
            {
                NPC.downedSlimeKing = reader.ReadBoolean();
            }
            NPC.savedGoblin = reader.ReadBoolean();
            NPC.savedWizard = reader.ReadBoolean();
            NPC.savedMech = reader.ReadBoolean();
            NPC.downedGoblins = reader.ReadBoolean();
            NPC.downedClown = reader.ReadBoolean();
            NPC.downedFrost = reader.ReadBoolean();
            NPC.downedPirates = reader.ReadBoolean();
            WorldGen.shadowOrbSmashed = reader.ReadBoolean();
            WorldGen.spawnMeteor = reader.ReadBoolean();
            WorldGen.shadowOrbCount = (int)reader.ReadByte();
            WorldGen.altarCount = reader.ReadInt32();
            Main.hardMode = reader.ReadBoolean();
            if (versionNumber >= 257)
            {
                Main.afterPartyOfDoom = reader.ReadBoolean();
            }
            else
            {
                Main.afterPartyOfDoom = false;
            }
            Main.invasionDelay = reader.ReadInt32();
            Main.invasionSize = reader.ReadInt32();
            Main.invasionType = reader.ReadInt32();
            Main.invasionX = reader.ReadDouble();
            if (versionNumber >= 118)
            {
                Main.slimeRainTime = reader.ReadDouble();
            }
            if (versionNumber >= 113)
            {
                Main.sundialCooldown = (int)reader.ReadByte();
            }
            WorldFile._tempRaining = reader.ReadBoolean();
            WorldFile._tempRainTime = reader.ReadInt32();
            WorldFile._tempMaxRain = reader.ReadSingle();
            WorldFile.FixEndlessRainWorlds();
            WorldGen.SavedOreTiers.Cobalt = reader.ReadInt32();
            WorldGen.SavedOreTiers.Mythril = reader.ReadInt32();
            WorldGen.SavedOreTiers.Adamantite = reader.ReadInt32();
            WorldGen.setBG(0, (int)reader.ReadByte());
            WorldGen.setBG(1, (int)reader.ReadByte());
            WorldGen.setBG(2, (int)reader.ReadByte());
            WorldGen.setBG(3, (int)reader.ReadByte());
            WorldGen.setBG(4, (int)reader.ReadByte());
            WorldGen.setBG(5, (int)reader.ReadByte());
            WorldGen.setBG(6, (int)reader.ReadByte());
            WorldGen.setBG(7, (int)reader.ReadByte());
            Main.cloudBGActive = (float)reader.ReadInt32();
            Main.cloudBGAlpha = (((double)Main.cloudBGActive < 1.0) ? 0f : 1f);
            Main.cloudBGActive = (float)(-(float)WorldGen.genRand.Next(8640, 86400));
            Main.numClouds = (int)reader.ReadInt16();
            Main.windSpeedTarget = reader.ReadSingle();
            Main.windSpeedCurrent = Main.windSpeedTarget;
            if (versionNumber < 95)
            {
                return;
            }
            Main.anglerWhoFinishedToday.Clear();
            for (int i = reader.ReadInt32(); i > 0; i--)
            {
                Main.anglerWhoFinishedToday.Add(reader.ReadString());
            }
            if (versionNumber < 99)
            {
                return;
            }
            NPC.savedAngler = reader.ReadBoolean();
            if (versionNumber < 101)
            {
                return;
            }
            Main.anglerQuest = reader.ReadInt32();
            if (versionNumber < 104)
            {
                return;
            }
            NPC.savedStylist = reader.ReadBoolean();
            if (versionNumber >= 129)
            {
                NPC.savedTaxCollector = reader.ReadBoolean();
            }
            if (versionNumber >= 201)
            {
                NPC.savedGolfer = reader.ReadBoolean();
            }
            if (versionNumber < 107)
            {
                if (Main.invasionType > 0 && Main.invasionSize > 0)
                {
                    Main.FakeLoadInvasionStart();
                }
            }
            else
            {
                Main.invasionSizeStart = reader.ReadInt32();
            }
            if (versionNumber < 108)
            {
                WorldFile._tempCultistDelay = 86400;
            }
            else
            {
                WorldFile._tempCultistDelay = reader.ReadInt32();
            }
            if (versionNumber < 109)
            {
                return;
            }
            BannerSystem.Load(reader, versionNumber);
            if (versionNumber < 128)
            {
                return;
            }
            Main.fastForwardTimeToDawn = reader.ReadBoolean();
            if (versionNumber < 131)
            {
                return;
            }
            NPC.downedFishron = reader.ReadBoolean();
            NPC.downedMartians = reader.ReadBoolean();
            NPC.downedAncientCultist = reader.ReadBoolean();
            NPC.downedMoonlord = reader.ReadBoolean();
            NPC.downedHalloweenKing = reader.ReadBoolean();
            NPC.downedHalloweenTree = reader.ReadBoolean();
            NPC.downedChristmasIceQueen = reader.ReadBoolean();
            NPC.downedChristmasSantank = reader.ReadBoolean();
            NPC.downedChristmasTree = reader.ReadBoolean();
            if (versionNumber < 140)
            {
                return;
            }
            NPC.downedTowerSolar = reader.ReadBoolean();
            NPC.downedTowerVortex = reader.ReadBoolean();
            NPC.downedTowerNebula = reader.ReadBoolean();
            NPC.downedTowerStardust = reader.ReadBoolean();
            NPC.TowerActiveSolar = reader.ReadBoolean();
            NPC.TowerActiveVortex = reader.ReadBoolean();
            NPC.TowerActiveNebula = reader.ReadBoolean();
            NPC.TowerActiveStardust = reader.ReadBoolean();
            NPC.LunarApocalypseIsUp = reader.ReadBoolean();
            if (NPC.TowerActiveSolar)
            {
                NPC.ShieldStrengthTowerSolar = NPC.ShieldStrengthTowerMax;
            }
            if (NPC.TowerActiveVortex)
            {
                NPC.ShieldStrengthTowerVortex = NPC.ShieldStrengthTowerMax;
            }
            if (NPC.TowerActiveNebula)
            {
                NPC.ShieldStrengthTowerNebula = NPC.ShieldStrengthTowerMax;
            }
            if (NPC.TowerActiveStardust)
            {
                NPC.ShieldStrengthTowerStardust = NPC.ShieldStrengthTowerMax;
            }
            if (versionNumber < 170)
            {
                WorldFile._tempPartyManual = false;
                WorldFile._tempPartyGenuine = false;
                WorldFile._tempPartyCooldown = 0;
                WorldFile.TempPartyCelebratingNPCs.Clear();
            }
            else
            {
                WorldFile._tempPartyManual = reader.ReadBoolean();
                WorldFile._tempPartyGenuine = reader.ReadBoolean();
                WorldFile._tempPartyCooldown = reader.ReadInt32();
                int num = reader.ReadInt32();
                WorldFile.TempPartyCelebratingNPCs.Clear();
                for (int j = 0; j < num; j++)
                {
                    WorldFile.TempPartyCelebratingNPCs.Add(reader.ReadInt32());
                }
            }
            if (versionNumber < 174)
            {
                WorldFile._tempSandstormHappening = false;
                WorldFile._tempSandstormTimeLeft = 0;
                WorldFile._tempSandstormSeverity = 0f;
                WorldFile._tempSandstormIntendedSeverity = 0f;
            }
            else
            {
                WorldFile._tempSandstormHappening = reader.ReadBoolean();
                WorldFile._tempSandstormTimeLeft = reader.ReadInt32();
                WorldFile._tempSandstormSeverity = reader.ReadSingle();
                WorldFile._tempSandstormIntendedSeverity = reader.ReadSingle();
            }
            DD2Event.Load(reader, versionNumber);
            if (versionNumber > 194)
            {
                WorldGen.setBG(8, (int)reader.ReadByte());
            }
            else
            {
                WorldGen.setBG(8, 0);
            }
            if (versionNumber >= 215)
            {
                WorldGen.setBG(9, (int)reader.ReadByte());
            }
            else
            {
                WorldGen.setBG(9, 0);
            }
            if (versionNumber > 195)
            {
                WorldGen.setBG(10, (int)reader.ReadByte());
                WorldGen.setBG(11, (int)reader.ReadByte());
                WorldGen.setBG(12, (int)reader.ReadByte());
            }
            else
            {
                WorldGen.setBG(10, WorldGen.treeBG1);
                WorldGen.setBG(11, WorldGen.treeBG1);
                WorldGen.setBG(12, WorldGen.treeBG1);
            }
            if (versionNumber >= 204)
            {
                NPC.combatBookWasUsed = reader.ReadBoolean();
            }
            if (versionNumber < 207)
            {
                WorldFile._tempLanternNightCooldown = 0;
                WorldFile._tempLanternNightGenuine = false;
                WorldFile._tempLanternNightManual = false;
                WorldFile._tempLanternNightNextNightIsGenuine = false;
            }
            else
            {
                WorldFile._tempLanternNightCooldown = reader.ReadInt32();
                WorldFile._tempLanternNightGenuine = reader.ReadBoolean();
                WorldFile._tempLanternNightManual = reader.ReadBoolean();
                WorldFile._tempLanternNightNextNightIsGenuine = reader.ReadBoolean();
            }
            WorldGen.TreeTops.Load(reader, versionNumber);
            if (versionNumber >= 212)
            {
                Main.forceHalloweenForToday = reader.ReadBoolean();
                Main.forceXMasForToday = reader.ReadBoolean();
            }
            else
            {
                Main.forceHalloweenForToday = false;
                Main.forceXMasForToday = false;
            }
            if (versionNumber >= 216)
            {
                WorldGen.SavedOreTiers.Copper = reader.ReadInt32();
                WorldGen.SavedOreTiers.Iron = reader.ReadInt32();
                WorldGen.SavedOreTiers.Silver = reader.ReadInt32();
                WorldGen.SavedOreTiers.Gold = reader.ReadInt32();
            }
            else
            {
                WorldGen.SavedOreTiers.Copper = -1;
                WorldGen.SavedOreTiers.Iron = -1;
                WorldGen.SavedOreTiers.Silver = -1;
                WorldGen.SavedOreTiers.Gold = -1;
            }
            if (versionNumber >= 217)
            {
                NPC.boughtCat = reader.ReadBoolean();
                NPC.boughtDog = reader.ReadBoolean();
                NPC.boughtBunny = reader.ReadBoolean();
            }
            else
            {
                NPC.boughtCat = false;
                NPC.boughtDog = false;
                NPC.boughtBunny = false;
            }
            if (versionNumber >= 223)
            {
                NPC.downedEmpressOfLight = reader.ReadBoolean();
                NPC.downedQueenSlime = reader.ReadBoolean();
            }
            else
            {
                NPC.downedEmpressOfLight = false;
                NPC.downedQueenSlime = false;
            }
            if (versionNumber >= 240)
            {
                NPC.downedDeerclops = reader.ReadBoolean();
            }
            else
            {
                NPC.downedDeerclops = false;
            }
            if (versionNumber >= 250)
            {
                NPC.unlockedSlimeBlueSpawn = reader.ReadBoolean();
            }
            else
            {
                NPC.unlockedSlimeBlueSpawn = false;
            }
            if (versionNumber >= 251)
            {
                NPC.unlockedMerchantSpawn = reader.ReadBoolean();
                NPC.unlockedDemolitionistSpawn = reader.ReadBoolean();
                NPC.unlockedPartyGirlSpawn = reader.ReadBoolean();
                NPC.unlockedDyeTraderSpawn = reader.ReadBoolean();
                NPC.unlockedTruffleSpawn = reader.ReadBoolean();
                NPC.unlockedArmsDealerSpawn = reader.ReadBoolean();
                NPC.unlockedNurseSpawn = reader.ReadBoolean();
                NPC.unlockedPrincessSpawn = reader.ReadBoolean();
            }
            else
            {
                NPC.unlockedMerchantSpawn = false;
                NPC.unlockedDemolitionistSpawn = false;
                NPC.unlockedPartyGirlSpawn = false;
                NPC.unlockedDyeTraderSpawn = false;
                NPC.unlockedTruffleSpawn = false;
                NPC.unlockedArmsDealerSpawn = false;
                NPC.unlockedNurseSpawn = false;
                NPC.unlockedPrincessSpawn = false;
            }
            if (versionNumber >= 259)
            {
                NPC.combatBookVolumeTwoWasUsed = reader.ReadBoolean();
            }
            else
            {
                NPC.combatBookVolumeTwoWasUsed = false;
            }
            if (versionNumber >= 260)
            {
                NPC.peddlersSatchelWasUsed = reader.ReadBoolean();
            }
            else
            {
                NPC.peddlersSatchelWasUsed = false;
            }
            if (versionNumber >= 261)
            {
                NPC.unlockedSlimeGreenSpawn = reader.ReadBoolean();
                NPC.unlockedSlimeOldSpawn = reader.ReadBoolean();
                NPC.unlockedSlimePurpleSpawn = reader.ReadBoolean();
                NPC.unlockedSlimeRainbowSpawn = reader.ReadBoolean();
                NPC.unlockedSlimeRedSpawn = reader.ReadBoolean();
                NPC.unlockedSlimeYellowSpawn = reader.ReadBoolean();
                NPC.unlockedSlimeCopperSpawn = reader.ReadBoolean();
            }
            else
            {
                NPC.unlockedSlimeGreenSpawn = false;
                NPC.unlockedSlimeOldSpawn = false;
                NPC.unlockedSlimePurpleSpawn = false;
                NPC.unlockedSlimeRainbowSpawn = false;
                NPC.unlockedSlimeRedSpawn = false;
                NPC.unlockedSlimeYellowSpawn = false;
                NPC.unlockedSlimeCopperSpawn = false;
            }
            if (versionNumber >= 264)
            {
                Main.fastForwardTimeToDusk = reader.ReadBoolean();
                Main.moondialCooldown = (int)reader.ReadByte();
            }
            else
            {
                Main.fastForwardTimeToDusk = false;
                Main.moondialCooldown = 0;
            }
            if (versionNumber >= 287)
            {
                Main.forceHalloweenForever = reader.ReadBoolean();
                Main.forceXMasForever = reader.ReadBoolean();
            }
            else
            {
                Main.forceHalloweenForever = false;
                Main.forceXMasForever = false;
            }
            if (versionNumber >= 288)
            {
                Main.vampireSeed = reader.ReadBoolean();
            }
            else
            {
                Main.vampireSeed = false;
            }
            if (versionNumber >= 296)
            {
                Main.infectedSeed = reader.ReadBoolean();
            }
            else
            {
                Main.infectedSeed = false;
            }
            if (versionNumber >= 291)
            {
                WorldFile._tempMeteorShowerCount = reader.ReadInt32();
                WorldFile._tempCoinRain = reader.ReadInt32();
            }
            else
            {
                WorldFile._tempMeteorShowerCount = 0;
                WorldFile._tempCoinRain = 0;
            }
            if (versionNumber >= 297)
            {
                Main.teamBasedSpawnsSeed = reader.ReadBoolean();
                ExtraSpawnPointManager.Read(reader, false);
            }
            else
            {
                Main.teamBasedSpawnsSeed = false;
                ExtraSpawnPointManager.Clear();
            }
            Main.dualDungeonsSeed = versionNumber >= 304 && reader.ReadBoolean();
            Main.UpdateTimeRate();
            if (versionNumber >= 299 && versionNumber < 313)
            {
                reader.ReadUInt32();
            }
            WorldGen.Manifest = WorldManifest.Deserialize((versionNumber < 299) ? "" : reader.ReadString());
        }
References Terraria.IO.WorldFile._tempEclipse, Terraria.IO.WorldFile._versionNumber, Terraria.Main.ActiveWorldFileData, System.Collections.Generic.List< T >.Add(), Terraria.Main.anglerWhoFinishedToday, Terraria.Main.caveBackStyle, Terraria.Main.caveBackX, System.Collections.Generic.List< T >.Clear(), Terraria.GameContent.ExtraSpawnPointManager.Clear(), Terraria.WorldGen.clearWorld(), Terraria.Main.cloudBGActive, Terraria.WorldBuilding.WorldManifest.Deserialize(), Terraria.Main.drunkWorld, Terraria.Main.FakeLoadInvasionStart(), Terraria.IO.WorldFile.FixEndlessRainWorlds(), System.DateTime.FromBinary(), Terraria.WorldGen.genRand, int, Terraria.Main.invasionSize, Terraria.Main.invasionType, Terraria.GameContent.Events.DD2Event.Load(), Terraria.GameContent.TreeTopsInfo.Load(), Terraria.GameContent.BannerSystem.Load(), System.Guid.NewGuid(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.GameContent.ExtraSpawnPointManager.Read(), System.IO.BinaryReader.ReadBoolean(), System.IO.BinaryReader.ReadByte(), System.IO.BinaryReader.ReadBytes(), System.IO.BinaryReader.ReadDouble(), System.IO.BinaryReader.ReadInt16(), System.IO.BinaryReader.ReadInt32(), System.IO.BinaryReader.ReadInt64(), System.IO.BinaryReader.ReadSingle(), System.IO.BinaryReader.ReadString(), System.IO.BinaryReader.ReadUInt32(), System.IO.BinaryReader.ReadUInt64(), Terraria.WorldGen.setBG(), Terraria.NPC.ShieldStrengthTowerMax, Terraria.IO.WorldFile.TempPartyCelebratingNPCs, System.text, Terraria.NPC.TowerActiveNebula, Terraria.NPC.TowerActiveSolar, Terraria.NPC.TowerActiveStardust, Terraria.NPC.TowerActiveVortex, Terraria.WorldGen.treeBG1, Terraria.Main.treeStyle, Terraria.WorldGen.TreeTops, Terraria.Main.treeX, Terraria.Main.UpdateTimeRate(), and Terraria.Main.windSpeedTarget.
Referenced by Terraria.IO.WorldFile.LoadWorld_Version2(), and Terraria.WorldGen.PrepForRegen().