Terraria Decompiled: Terraria.IO.WorldFile.SetOngoingToTemps
SetOngoingToTemps()
static void Terraria.IO.WorldFile.SetOngoingToTemps () inline static
Definition at line 26 of file WorldFile.cs.
        {
            Main.dayTime = WorldFile._tempDayTime;
            Main.time = WorldFile._tempTime;
            Main.moonPhase = WorldFile._tempMoonPhase;
            Main.bloodMoon = WorldFile._tempBloodMoon;
            Main.eclipse = WorldFile._tempEclipse;
            Main.raining = WorldFile._tempRaining;
            Main.rainTime = WorldFile._tempRainTime;
            Main.maxRaining = WorldFile._tempMaxRain;
            Main.cloudAlpha = WorldFile._tempMaxRain;
            CultistRitual.delay = WorldFile._tempCultistDelay;
            BirthdayParty.ManualParty = WorldFile._tempPartyManual;
            BirthdayParty.GenuineParty = WorldFile._tempPartyGenuine;
            BirthdayParty.PartyDaysOnCooldown = WorldFile._tempPartyCooldown;
            BirthdayParty.CelebratingNPCs.Clear();
            BirthdayParty.CelebratingNPCs.AddRange(WorldFile.TempPartyCelebratingNPCs);
            Sandstorm.Happening = WorldFile._tempSandstormHappening;
            Sandstorm.TimeLeft = WorldFile._tempSandstormTimeLeft;
            Sandstorm.Severity = WorldFile._tempSandstormSeverity;
            Sandstorm.IntendedSeverity = WorldFile._tempSandstormIntendedSeverity;
            LanternNight.GenuineLanterns = WorldFile._tempLanternNightGenuine;
            LanternNight.LanternNightsOnCooldown = WorldFile._tempLanternNightCooldown;
            LanternNight.ManualLanterns = WorldFile._tempLanternNightManual;
            LanternNight.NextNightIsLanternNight = WorldFile._tempLanternNightNextNightIsGenuine;
            WorldGen.meteorShowerCount = WorldFile._tempMeteorShowerCount;
            Main.coinRain = WorldFile._tempCoinRain;
        }
References Terraria.IO.WorldFile._tempBloodMoon, Terraria.IO.WorldFile._tempCoinRain, Terraria.IO.WorldFile._tempCultistDelay, Terraria.IO.WorldFile._tempDayTime, Terraria.IO.WorldFile._tempEclipse, Terraria.IO.WorldFile._tempLanternNightCooldown, Terraria.IO.WorldFile._tempLanternNightGenuine, Terraria.IO.WorldFile._tempLanternNightManual, Terraria.IO.WorldFile._tempLanternNightNextNightIsGenuine, Terraria.IO.WorldFile._tempMaxRain, Terraria.IO.WorldFile._tempMeteorShowerCount, Terraria.IO.WorldFile._tempMoonPhase, Terraria.IO.WorldFile._tempPartyCooldown, Terraria.IO.WorldFile._tempPartyGenuine, Terraria.IO.WorldFile._tempPartyManual, Terraria.IO.WorldFile._tempRaining, Terraria.IO.WorldFile._tempRainTime, Terraria.IO.WorldFile._tempSandstormHappening, Terraria.IO.WorldFile._tempSandstormIntendedSeverity, Terraria.IO.WorldFile._tempSandstormSeverity, Terraria.IO.WorldFile._tempSandstormTimeLeft, Terraria.IO.WorldFile._tempTime, System.Collections.Generic.List< T >.AddRange(), Terraria.GameContent.Events.BirthdayParty.CelebratingNPCs, System.Collections.Generic.List< T >.Clear(), and Terraria.IO.WorldFile.TempPartyCelebratingNPCs.
Referenced by Terraria.WorldGen.playWorldCallBack(), and Terraria.WorldGen.serverLoadWorldCallBack().