Terraria Decompiled: Terraria.IO.WorldFile.LoadFileFormatHeader
LoadFileFormatHeader()
static bool Terraria.IO.WorldFile.LoadFileFormatHeader (BinaryReader reader, out bool[] importance, out int[] positions) inline static
Definition at line 1874 of file WorldFile.cs.
        {
            importance = null;
            positions = null;
            if ((WorldFile._versionNumber = reader.ReadInt32()) >= 135)
            {
                try
                {
                    Main.WorldFileMetadata = FileMetadata.Read(reader, FileType.World);
                    goto IL_004B;
                }
                catch (FormatException ex)
                {
                    Console.WriteLine(Language.GetTextValue("Error.UnableToLoadWorld"));
                    Console.WriteLine(ex);
                    return false;
                }
            }
            Main.WorldFileMetadata = FileMetadata.FromCurrentSettings(FileType.World);
            IL_004B:
            short num = reader.ReadInt16();
            positions = new int[(int)num];
            for (int i = 0; i < (int)num; i++)
            {
                positions[i] = reader.ReadInt32();
            }
            ushort num2 = reader.ReadUInt16();
            importance = new bool[(int)num2];
            byte b = 0;
            byte b2 = 128;
            for (int i = 0; i < (int)num2; i++)
            {
                if (b2 == 128)
                {
                    b = reader.ReadByte();
                    b2 = 1;
                }
                else
                {
                    b2 = (byte)(b2 << 1);
                }
                if ((b & b2) == b2)
                {
                    importance[i] = true;
                }
            }
            return true;
        }
References Terraria.IO.WorldFile._versionNumber, Terraria.IO.FileMetadata.FromCurrentSettings(), Terraria.Localization.Language.GetTextValue(), int, Terraria.IO.FileMetadata.Read(), System.IO.BinaryReader.ReadByte(), System.IO.BinaryReader.ReadInt16(), System.IO.BinaryReader.ReadInt32(), System.IO.BinaryReader.ReadUInt16(), and System.Console.WriteLine().
Referenced by Terraria.IO.WorldFile.LoadWorld_Version2(), Terraria.WorldGen.PrepForRegen(), and Terraria.IO.WorldFile.ValidateWorld().