Terraria Decompiled: Terraria.IO.WorldFile.SetTempToOngoing
SetTempToOngoing()
static void Terraria.IO.WorldFile.SetTempToOngoing () inline static
Definition at line 970 of file WorldFile.cs.
        {
            WorldFile._tempDayTime = Main.dayTime;
            WorldFile._tempTime = Main.time;
            WorldFile._tempMoonPhase = Main.moonPhase;
            WorldFile._tempBloodMoon = Main.bloodMoon;
            WorldFile._tempEclipse = Main.eclipse;
            WorldFile._tempCultistDelay = CultistRitual.delay;
            WorldFile._tempPartyManual = BirthdayParty.ManualParty;
            WorldFile._tempPartyGenuine = BirthdayParty.GenuineParty;
            WorldFile._tempPartyCooldown = BirthdayParty.PartyDaysOnCooldown;
            WorldFile.TempPartyCelebratingNPCs.Clear();
            WorldFile.TempPartyCelebratingNPCs.AddRange(BirthdayParty.CelebratingNPCs);
            WorldFile._tempSandstormHappening = Sandstorm.Happening;
            WorldFile._tempSandstormTimeLeft = Sandstorm.TimeLeft;
            WorldFile._tempSandstormSeverity = Sandstorm.Severity;
            WorldFile._tempSandstormIntendedSeverity = Sandstorm.IntendedSeverity;
            WorldFile._tempRaining = Main.raining;
            WorldFile._tempRainTime = Main.rainTime;
            WorldFile._tempMaxRain = Main.maxRaining;
            WorldFile._tempLanternNightCooldown = LanternNight.LanternNightsOnCooldown;
            WorldFile._tempLanternNightGenuine = LanternNight.GenuineLanterns;
            WorldFile._tempLanternNightManual = LanternNight.ManualLanterns;
            WorldFile._tempLanternNightNextNightIsGenuine = LanternNight.NextNightIsLanternNight;
            WorldFile._tempMeteorShowerCount = WorldGen.meteorShowerCount;
            WorldFile._tempCoinRain = Main.coinRain;
        }
References System.Collections.Generic.List< T >.AddRange(), Terraria.Main.bloodMoon, Terraria.GameContent.Events.BirthdayParty.CelebratingNPCs, System.Collections.Generic.List< T >.Clear(), Terraria.Main.coinRain, Terraria.Main.dayTime, Terraria.GameContent.Events.CultistRitual.delay, Terraria.Main.eclipse, Terraria.GameContent.Events.LanternNight.GenuineLanterns, Terraria.GameContent.Events.BirthdayParty.GenuineParty, Terraria.GameContent.Events.Sandstorm.Happening, Terraria.GameContent.Events.Sandstorm.IntendedSeverity, Terraria.GameContent.Events.LanternNight.LanternNightsOnCooldown, Terraria.GameContent.Events.LanternNight.ManualLanterns, Terraria.GameContent.Events.BirthdayParty.ManualParty, Terraria.Main.maxRaining, Terraria.WorldGen.meteorShowerCount, Terraria.Main.moonPhase, Terraria.GameContent.Events.LanternNight.NextNightIsLanternNight, Terraria.GameContent.Events.BirthdayParty.PartyDaysOnCooldown, Terraria.Main.raining, Terraria.Main.rainTime, Terraria.GameContent.Events.Sandstorm.Severity, Terraria.IO.WorldFile.TempPartyCelebratingNPCs, Terraria.Main.time, and Terraria.GameContent.Events.Sandstorm.TimeLeft.
Referenced by Terraria.IO.WorldFile.InternalSaveWorld(), Terraria.WorldGen.saveAndPlay(), and Terraria.WorldGen.SaveAndQuit().