Terraria Decompiled: Terraria.IO.WorldFile._SaveWorld
_SaveWorld()
static void Terraria.IO.WorldFile._SaveWorld (bool useCloudSaving, bool resetTime, bool useTemps, bool canBeSkipped) inline static private
Definition at line 792 of file WorldFile.cs.
        {
            if (useCloudSaving && SocialAPI.Cloud == null)
            {
                return;
            }
            if (Main.worldName == "")
            {
                Main.worldName = "World";
            }
            while (WorldGen.TransformingWorld)
            {
                Main.statusText = Lang.gen[48].Value;
            }
            if (Monitor.TryEnter(WorldFile.IOLock))
            {
                try
                {
                    FileUtilities.ProtectedInvoke(delegate
                    {
                        WorldFile.InternalSaveWorld(useCloudSaving, resetTime, useTemps);
                    });
                    return;
                }
                finally
                {
                    Monitor.Exit(WorldFile.IOLock);
                }
            }
            if (!canBeSkipped)
            {
                object iolock = WorldFile.IOLock;
                lock (iolock)
                {
                    WorldFile._SaveWorld(useCloudSaving, resetTime, useTemps, canBeSkipped);
                    return;
                }
            }
        }
References Terraria.IO.WorldFile._SaveWorld(), Terraria.Social.SocialAPI.Cloud, System.Threading.Monitor.Exit(), Terraria.Lang.gen, Terraria.IO.WorldFile.InternalSaveWorld(), Terraria.IO.WorldFile.IOLock, Terraria.Utilities.FileUtilities.ProtectedInvoke(), Terraria.WorldGen.TransformingWorld, System.Threading.Monitor.TryEnter(), Terraria.Localization.LocalizedText.Value, and Terraria.Main.worldName.
Referenced by Terraria.IO.WorldFile._SaveWorld(), and Terraria.IO.WorldFile.SaveWorld().