Terraria Decompiled: Terraria.IO.WorldFile.ConvertOldTileEntities
ConvertOldTileEntities()
static void Terraria.IO.WorldFile.ConvertOldTileEntities () inline static private
Definition at line 999 of file WorldFile.cs.
        {
            List<Point> list = new List<Point>();
            List<Point> list2 = new List<Point>();
            for (int i = 0; i < Main.maxTilesX; i++)
            {
                for (int j = 0; j < Main.maxTilesY; j++)
                {
                    Tile tile = Main.tile[i, j];
                    if ((tile.type == 128 || tile.type == 269) && tile.frameY == 0 && (tile.frameX % 100 == 0 || tile.frameX % 100 == 36))
                    {
                        list.Add(new Point(i, j));
                    }
                    if (tile.type == 334 && tile.frameY == 0 && tile.frameX % 54 == 0)
                    {
                        list2.Add(new Point(i, j));
                    }
                    if (tile.type == 49 && (tile.frameX == -1 || tile.frameY == -1))
                    {
                        tile.frameX = 0;
                        tile.frameY = 0;
                    }
                }
            }
            foreach (Point point in list)
            {
                if (WorldGen.InWorld(point.X, point.Y, 5))
                {
                    int frameX = (int)Main.tile[point.X, point.Y].frameX;
                    int frameX2 = (int)Main.tile[point.X, point.Y + 1].frameX;
                    int frameX3 = (int)Main.tile[point.X, point.Y + 2].frameX;
                    for (int k = 0; k < 2; k++)
                    {
                        for (int l = 0; l < 3; l++)
{
                            Tile tile2 = Main.tile[point.X + k, point.Y + l];
                            Tile tile3 = tile2;
                            tile3.frameX %= 100;
                            if (tile2.type == 269)
{
                                Tile tile4 = tile2;
                                tile4.frameX += 72;
                            }
                            tile2.type = 470;
                        }
                    }
                    int num = TileEntityType<TEDisplayDoll>.Place(point.X, point.Y);
                    if (num != -1)
                    {
                        TEDisplayDoll tedisplayDoll;
                        TileEntity.TryGet<TEDisplayDoll>(num, out tedisplayDoll);
                        tedisplayDoll.SetInventoryFromMannequin(frameX, frameX2, frameX3);
                    }
                }
            }
            foreach (Point point2 in list2)
            {
                if (WorldGen.InWorld(point2.X, point2.Y, 5))
                {
                    bool flag = Main.tile[point2.X, point2.Y].frameX >= 54;
                    short frameX4 = Main.tile[point2.X, point2.Y + 1].frameX;
                    int frameX5 = (int)Main.tile[point2.X + 1, point2.Y + 1].frameX;
                    bool flag2 = frameX4 >= 5000;
                    int num2 = (int)(frameX4 % 5000);
                    num2 -= 100;
                    int num3 = frameX5 - ((frameX5 >= 25000) ? 25000 : 10000);
                    for (int m = 0; m < 3; m++)
                    {
                        for (int n = 0; n < 3; n++)
{
                            Tile tile5 = Main.tile[point2.X + m, point2.Y + n];
                            tile5.type = 471;
                            tile5.frameX = (short)((flag ? 54 : 0) + m * 18);
                            tile5.frameY = (short)(n * 18);
                        }
                    }
                    if (TileEntityType<TEWeaponsRack>.Place(point2.X, point2.Y) != -1 && flag2)
                    {
                        TEWeaponsRack.TryPlacing(point2.X, point2.Y, num2, num3, 1);
                    }
                }
            }
        }
References System.Collections.Generic.List< T >.Add(), Terraria.Tile.frameX, Terraria.Tile.frameY, int, Terraria.WorldGen.InWorld(), System.list, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.DataStructures.TileEntityType< T >.Place(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.SetInventoryFromMannequin(), Terraria.Main.tile, Terraria.GameContent.Tile_Entities.TEWeaponsRack.TryPlacing(), Terraria.Tile.type, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.IO.WorldFile.LoadWorld().