Terraria Decompiled: Terraria.IO.WorldFile.LoadChests
LoadChests()
static void Terraria.IO.WorldFile.LoadChests (BinaryReader reader) inline static
Definition at line 2715 of file WorldFile.cs.
        {
            int num = (int)reader.ReadInt16();
            int num2 = 0;
            if (WorldFile._versionNumber < 294)
            {
                num2 = (int)reader.ReadInt16();
            }
            int i;
            for (i = 0; i < num; i++)
            {
                int num3 = reader.ReadInt32();
                int num4 = reader.ReadInt32();
                Chest chest = Chest.CreateWorldChest(i, num3, num4);
                chest.name = reader.ReadString();
                if (WorldFile._versionNumber >= 294)
                {
                    int num5 = reader.ReadInt32();
                    chest.Resize(num5);
                    num2 = num5;
                }
                int num6;
                int num7;
                if (num2 < chest.maxItems)
                {
                    num6 = num2;
                    num7 = 0;
                }
                else
                {
                    num6 = chest.maxItems;
                    num7 = num2 - chest.maxItems;
                }
                for (int j = 0; j < num6; j++)
                {
                    short num8 = reader.ReadInt16();
                    Item item = new Item();
                    if (num8 > 0)
                    {
                        item.netDefaults(reader.ReadInt32());
                        item.stack = (int)num8;
                        item.Prefix((int)reader.ReadByte());
                    }
                    else if (num8 < 0)
                    {
                        item.netDefaults(reader.ReadInt32());
                        item.Prefix((int)reader.ReadByte());
                        item.stack = 1;
                    }
                    chest.item[j] = item;
                }
                for (int k = 0; k < num7; k++)
                {
                    short num8 = reader.ReadInt16();
                    if (num8 > 0)
                    {
                        reader.ReadInt32();
                        reader.ReadByte();
                    }
                }
            }
            List<Point16> list = new List<Point16>();
            for (int l = 0; l < i; l++)
            {
                if (Main.chest[l] != null)
                {
                    Point16 point = new Point16(Main.chest[l].x, Main.chest[l].y);
                    if (list.Contains(point))
                    {
                        Chest.RemoveChest(l);
                    }
                    else
                    {
                        list.Add(point);
                    }
                }
            }
            while (i < 8000)
            {
                Chest.RemoveChest(i);
                i++;
            }
            if (WorldFile._versionNumber < 115)
            {
                WorldFile.FixDresserChests();
            }
        }
References Terraria.IO.WorldFile._versionNumber, Terraria.Main.chest, Terraria.Chest.CreateWorldChest(), Terraria.IO.WorldFile.FixDresserChests(), int, System.item, Terraria.Chest.item, System.list, Terraria.Chest.maxItems, System.IO.BinaryReader.ReadByte(), System.IO.BinaryReader.ReadInt16(), System.IO.BinaryReader.ReadInt32(), System.IO.BinaryReader.ReadString(), Terraria.Chest.RemoveChest(), Terraria.Chest.Resize(), Terraria.Chest.x, and Terraria.Chest.y.
Referenced by Terraria.IO.WorldFile.LoadWorld_Version2().