Terraria Decompiled: Terraria.IO.WorldFile.GetFileMetadata
GetFileMetadata()
static FileMetadata Terraria.IO.WorldFile.GetFileMetadata (string file, bool cloudSave) inline static
Definition at line 3275 of file WorldFile.cs.
        {
            if (file == null)
            {
                return null;
            }
            try
            {
                byte[] array = null;
                bool flag = cloudSave && SocialAPI.Cloud != null;
                if (flag)
                {
                    int num = 24;
                    array = new byte[num];
                    SocialAPI.Cloud.Read(file, array, num);
                }
                using (Stream stream = (flag ? new MemoryStream(array) : new FileStream(file, FileMode.Open)))
                {
                    using (BinaryReader binaryReader = new BinaryReader(stream))
                    {
                        if (binaryReader.ReadInt32() >= 135)
{
                            return FileMetadata.Read(binaryReader, FileType.World);
                        }
                        return FileMetadata.FromCurrentSettings(FileType.World);
                    }
                }
            }
            catch
            {
            }
            return null;
        }
References System.array, Terraria.Social.SocialAPI.Cloud, Terraria.IO.FileMetadata.FromCurrentSettings(), Terraria.IO.FileMetadata.Read(), and System.IO.BinaryReader.ReadInt32().
Referenced by Terraria.IO.WorldFile.IsValidWorld().