Terraria Decompiled: Terraria.IO.WorldFile.LoadWorld_Version2
LoadWorld_Version2()
static int Terraria.IO.WorldFile.LoadWorld_Version2 (BinaryReader reader) inline static
Definition at line 1722 of file WorldFile.cs.
        {
            reader.BaseStream.Position = 0L;
            bool[] array;
            int[] array2;
            if (!WorldFile.LoadFileFormatHeader(reader, out array, out array2))
            {
                return StatusID.BadSectionPointer;
            }
            if (reader.BaseStream.Position != (long)array2[0])
            {
                return StatusID.BadSectionPointer;
            }
            WorldFile.LoadHeader(reader);
            if (reader.BaseStream.Position != (long)array2[1])
            {
                return StatusID.BadSectionPointer;
            }
            WorldFile.LoadWorldTiles(reader, array);
            if (reader.BaseStream.Position != (long)array2[2])
            {
                return StatusID.BadSectionPointer;
            }
            WorldFile.LoadChests(reader);
            if (reader.BaseStream.Position != (long)array2[3])
            {
                return StatusID.BadSectionPointer;
            }
            WorldFile.LoadSigns(reader);
            if (reader.BaseStream.Position != (long)array2[4])
            {
                return StatusID.BadSectionPointer;
            }
            WorldFile.LoadNPCs(reader);
            if (reader.BaseStream.Position != (long)array2[5])
            {
                return StatusID.BadSectionPointer;
            }
            if (WorldFile._versionNumber >= 116)
            {
                if (WorldFile._versionNumber < 122)
                {
                    WorldFile.LoadDummies(reader);
                    if (reader.BaseStream.Position != (long)array2[6])
                    {
                        return StatusID.BadSectionPointer;
                    }
                }
                else
                {
                    WorldFile.LoadTileEntities(reader);
                    if (reader.BaseStream.Position != (long)array2[6])
                    {
                        return StatusID.BadSectionPointer;
                    }
                }
            }
            if (WorldFile._versionNumber >= 170)
            {
                WorldFile.LoadWeightedPressurePlates(reader);
                if (reader.BaseStream.Position != (long)array2[7])
                {
                    return StatusID.BadSectionPointer;
                }
            }
            if (WorldFile._versionNumber >= 189)
            {
                WorldFile.LoadTownManager(reader);
                if (reader.BaseStream.Position != (long)array2[8])
                {
                    return StatusID.BadSectionPointer;
                }
            }
            if (WorldFile._versionNumber >= 210)
            {
                WorldFile.LoadBestiary(reader, WorldFile._versionNumber);
                if (reader.BaseStream.Position != (long)array2[9])
                {
                    return StatusID.BadSectionPointer;
                }
            }
            else
            {
                WorldFile.LoadBestiaryForVersionsBefore210();
            }
            if (WorldFile._versionNumber >= 220)
            {
                WorldFile.LoadCreativePowers(reader, WorldFile._versionNumber);
                if (reader.BaseStream.Position != (long)array2[10])
                {
                    return StatusID.BadSectionPointer;
                }
            }
            WorldFile.LoadWorld_LastMinuteFixes();
            return WorldFile.LoadFooter(reader);
        }
References Terraria.IO.WorldFile._versionNumber, System.array, Terraria.ID.StatusID.BadSectionPointer, System.IO.BinaryReader.BaseStream, System.L, Terraria.IO.WorldFile.LoadBestiary(), Terraria.IO.WorldFile.LoadBestiaryForVersionsBefore210(), Terraria.IO.WorldFile.LoadChests(), Terraria.IO.WorldFile.LoadCreativePowers(), Terraria.IO.WorldFile.LoadDummies(), Terraria.IO.WorldFile.LoadFileFormatHeader(), Terraria.IO.WorldFile.LoadFooter(), Terraria.IO.WorldFile.LoadHeader(), Terraria.IO.WorldFile.LoadNPCs(), Terraria.IO.WorldFile.LoadSigns(), Terraria.IO.WorldFile.LoadTileEntities(), Terraria.IO.WorldFile.LoadTownManager(), Terraria.IO.WorldFile.LoadWeightedPressurePlates(), Terraria.IO.WorldFile.LoadWorld_LastMinuteFixes(), Terraria.IO.WorldFile.LoadWorldTiles(), and System.IO.Stream.Position.
Referenced by Terraria.IO.WorldFile.LoadWorld().