Terraria Decompiled: Terraria.IO.WorldFile.ValidateWorld
ValidateWorld()
static bool Terraria.IO.WorldFile.ValidateWorld (BinaryReader fileIO) inline static
Definition at line 3011 of file WorldFile.cs.
        {
            new Stopwatch().Start();
            bool flag;
            try
            {
                Stream baseStream = fileIO.BaseStream;
                int num = fileIO.ReadInt32();
                if (num == 0 || num > 319)
                {
                    flag = false;
                }
                else
                {
                    baseStream.Position = 0L;
                    bool[] array;
                    int[] array2;
                    if (!WorldFile.LoadFileFormatHeader(fileIO, out array, out array2))
                    {
                        flag = false;
                    }
                    else
                    {
                        string text = fileIO.ReadString();
                        if (num >= 179)
{
                            if (num == 179)
{
                                fileIO.ReadInt32();
                            }
                            else
{
                                fileIO.ReadString();
                            }
                            fileIO.ReadUInt64();
                        }
                        if (num >= 181)
{
                            fileIO.ReadBytes(16);
                        }
                        int num2 = fileIO.ReadInt32();
                        fileIO.ReadInt32();
                        fileIO.ReadInt32();
                        fileIO.ReadInt32();
                        fileIO.ReadInt32();
                        int num3 = fileIO.ReadInt32();
                        int num4 = fileIO.ReadInt32();
                        baseStream.Position = (long)array2[1];
                        for (int i = 0; i < num4; i++)
{
                            float num5 = (float)i / (float)Main.maxTilesX;
                            Main.statusText = string.Concat(new object[]
{
                                Lang.gen[73].Value,
                                " ",
                                (int)(num5 * 100f + 1f),
                                "%"
                            });
                            for (int j = 0; j < num3; j++)
{
                                byte b2;
                                byte b = (b2 = 0);
                                byte b3 = fileIO.ReadByte();
                                bool flag2 = false;
                                if ((b3 & 1) == 1)
{
                                    flag2 = true;
                                    b2 = fileIO.ReadByte();
                                }
                                bool flag3 = false;
                                if (flag2 && (b2 & 1) == 1)
{
                                    flag3 = true;
                                    b = fileIO.ReadByte();
                                }
                                if (flag3 && (b & 1) == 1)
{
                                    fileIO.ReadByte();
                                }
                                byte b4;
                                if ((b3 & 2) == 2)
{
                                    int num6;
                                    if ((b3 & 32) == 32)
{
                                        b4 = fileIO.ReadByte();
                                        num6 = (int)fileIO.ReadByte();
                                        num6 = (num6 << 8) | (int)b4;
                                    }
                                    else
{
                                        num6 = (int)fileIO.ReadByte();
                                    }
                                    if (array[num6])
{
                                        fileIO.ReadInt16();
                                        fileIO.ReadInt16();
                                    }
                                    if ((b & 8) == 8)
{
                                        fileIO.ReadByte();
                                    }
                                }
                                if ((b3 & 4) == 4)
{
                                    fileIO.ReadByte();
                                    if ((b & 16) == 16)
{
                                        fileIO.ReadByte();
                                    }
                                }
                                if ((b3 & 24) >> 3 != 0)
{
                                    fileIO.ReadByte();
                                }
                                if ((b & 64) == 64)
{
                                    fileIO.ReadByte();
                                }
                                b4 = (byte)((b3 & 192) >> 6);
                                int num7;
                                if (b4 == 0)
{
                                    num7 = 0;
                                }
                                else if (b4 == 1)
{
                                    num7 = (int)fileIO.ReadByte();
                                }
                                else
{
                                    num7 = (int)fileIO.ReadInt16();
                                }
                                j += num7;
                            }
                        }
                        if (baseStream.Position != (long)array2[2])
{
                            flag = false;
                        }
                        else
{
                            int num8 = (int)fileIO.ReadInt16();
                            int num9 = 0;
                            if (num < 294)
{
                                num9 = (int)fileIO.ReadInt16();
                            }
                            for (int k = 0; k < num8; k++)
{
                                fileIO.ReadInt32();
                                fileIO.ReadInt32();
                                fileIO.ReadString();
                                if (num >= 294)
{
                                    num9 = fileIO.ReadInt32();
                                }
                                for (int l = 0; l < num9; l++)
{
                                    if (fileIO.ReadInt16() > 0)
{
                                        fileIO.ReadInt32();
                                        fileIO.ReadByte();
                                    }
                                }
                            }
                            if (baseStream.Position != (long)array2[3])
{
                                flag = false;
                            }
                            else
{
                                int num10 = (int)fileIO.ReadInt16();
                                for (int m = 0; m < num10; m++)
{
                                    fileIO.ReadString();
                                    fileIO.ReadInt32();
                                    fileIO.ReadInt32();
                                }
                                if (baseStream.Position != (long)array2[4])
{
                                    flag = false;
                                }
                                else
{
                                    WorldFile.ValidateLoadNPCs(fileIO);
                                    if (baseStream.Position != (long)array2[5])
{
                                        flag = false;
                                    }
                                    else
{
                                        if (WorldFile._versionNumber >= 116 && WorldFile._versionNumber <= 121)
{
                                            int num11 = fileIO.ReadInt32();
                                            for (int n = 0; n < num11; n++)
{
                                                fileIO.ReadInt16();
                                                fileIO.ReadInt16();
                                            }
                                            if (baseStream.Position != (long)array2[6])
{
                                                return false;
                                            }
                                        }
                                        if (WorldFile._versionNumber >= 122)
{
                                            int num12 = fileIO.ReadInt32();
                                            for (int num13 = 0; num13 < num12; num13++)
{
                                                TileEntity.Read(fileIO, WorldFile._versionNumber, false);
                                            }
                                        }
                                        if (WorldFile._versionNumber >= 170)
{
                                            int num14 = fileIO.ReadInt32();
                                            for (int num15 = 0; num15 < num14; num15++)
{
                                                fileIO.ReadInt64();
                                            }
                                        }
                                        if (WorldFile._versionNumber >= 189)
{
                                            int num16 = fileIO.ReadInt32();
                                            fileIO.ReadBytes(12 * num16);
                                        }
                                        if (WorldFile._versionNumber >= 210)
{
                                            Main.BestiaryTracker.ValidateWorld(fileIO, WorldFile._versionNumber);
                                        }
                                        if (WorldFile._versionNumber >= 220)
{
                                            CreativePowerManager.Instance.ValidateWorld(fileIO, WorldFile._versionNumber);
                                        }
                                        bool flag4 = fileIO.ReadBoolean();
                                        string text2 = fileIO.ReadString();
                                        int num17 = fileIO.ReadInt32();
                                        bool flag5 = false;
                                        if (flag4 && (text2 == text || num17 == num2))
{
                                            flag5 = true;
                                        }
                                        flag = flag5;
                                    }
                                }
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                using (StreamWriter streamWriter = new StreamWriter("client-crashlog.txt", true))
                {
                    streamWriter.WriteLine(DateTime.Now);
                    streamWriter.WriteLine(ex);
                    streamWriter.WriteLine("");
                }
                flag = false;
            }
            return flag;
        }
References Terraria.IO.WorldFile._versionNumber, System.array, System.IO.BinaryReader.BaseStream, Terraria.Main.BestiaryTracker, Terraria.Lang.gen, Terraria.GameContent.Creative.CreativePowerManager.Instance, int, System.L, Terraria.IO.WorldFile.LoadFileFormatHeader(), long, Terraria.Main.maxTilesX, System.DateTime.Now, System.IO.Stream.Position, Terraria.DataStructures.TileEntity.Read(), System.IO.BinaryReader.ReadBoolean(), System.IO.BinaryReader.ReadByte(), System.IO.BinaryReader.ReadBytes(), System.IO.BinaryReader.ReadInt16(), System.IO.BinaryReader.ReadInt32(), System.IO.BinaryReader.ReadInt64(), System.IO.BinaryReader.ReadString(), System.IO.BinaryReader.ReadUInt64(), System.text, Terraria.IO.WorldFile.ValidateLoadNPCs(), Terraria.GameContent.Creative.CreativePowerManager.ValidateWorld(), Terraria.Localization.LocalizedText.Value, and System.IO.StreamWriter.WriteLine().
Referenced by Terraria.IO.WorldFile.InternalSaveWorld().