Terraria Decompiled: ReLogic.Content.Readers.PngReader.FromStream< T >
FromStream< T >()
T ReLogic.Content.Readers.PngReader.FromStream< T > (Stream stream) inline
Implements ReLogic.Content.Readers.IAssetReader.
Type Constraints
T : class
Definition at line 20 of file PngReader.cs.
                                                      : class
        {
            if (typeof(T) != typeof(Texture2D))
            {
                throw AssetLoadException.FromInvalidReader<PngReader, T>();
            }
            Texture2D texture2D = Texture2D.FromStream(this._graphicsDevice, stream);
            int num = texture2D.Width * texture2D.Height;
            if (!this._colorProcessingCache.IsValueCreated || this._colorProcessingCache.Value.Length < num)
            {
                this._colorProcessingCache.Value = new Color[num];
            }
            Color[] value = this._colorProcessingCache.Value;
            texture2D.GetData<Color>(value, 0, num);
            for (int num2 = 0; num2 != num; num2++)
            {
                value[num2] = Color.FromNonPremultiplied(value[num2].ToVector4());
            }
            texture2D.SetData<Color>(value, 0, num);
            return texture2D as T;
        }
References ReLogic.Content.Readers.PngReader._colorProcessingCache, ReLogic.Content.Readers.PngReader._graphicsDevice, Microsoft.Xna.Framework.Color.FromNonPremultiplied(), Microsoft.Xna.Framework.Graphics.Texture2D.FromStream(), Microsoft.Xna.Framework.Graphics.Texture2D.Height, System.Threading.ThreadLocal< T >.IsValueCreated, ReLogic.Content.Readers.PngReader.PngReader(), System.T, System.value, and System.Threading.ThreadLocal< T >.Value.