Terraria Decompiled: System.Numerics.ConstantHelper.GetUInt32WithAllBitsSet
GetUInt32WithAllBitsSet()
static unsafe uint System.Numerics.ConstantHelper.GetUInt32WithAllBitsSet () inline static
Definition at line 47 of file ConstantHelper.cs.
        {
            uint num = 0U;
            *(&num) = uint.MaxValue;
            return num;
        }
References System.U.
Referenced by System.Numerics.Vector< T >.Equals(), System.Numerics.Vector< T >.GetAllBitsSetValue(), System.Numerics.Vector< T >.GreaterThan(), and System.Numerics.Vector< T >.LessThan().