Terraria Decompiled: System.Threading.Tasks.SingleProducerSingleConsumerQueue.EnqueueSlow
EnqueueSlow()
void System.Threading.Tasks.SingleProducerSingleConsumerQueue< T >.EnqueueSlow (T item, ref SingleProducerSingleConsumerQueue< T >::Segment segment) inline private
Definition at line 38 of file SingleProducerSingleConsumerQueue.cs.
        {
            if (segment.m_state.m_firstCopy != segment.m_state.m_first)
            {
                segment.m_state.m_firstCopy = segment.m_state.m_first;
                this.Enqueue(item);
                return;
            }
            int num = this.m_tail.m_array.Length << 1;
            if (num > 16777216)
            {
                num = 16777216;
            }
            SingleProducerSingleConsumerQueue<T>.Segment segment2 = new SingleProducerSingleConsumerQueue<T>.Segment(num);
            segment2.m_array[0] = item;
            segment2.m_state.m_last = 1;
            segment2.m_state.m_lastCopy = 1;
            try
            {
            }
            finally
            {
                Volatile.Write<SingleProducerSingleConsumerQueue<T>.Segment>(ref this.m_tail.m_next, segment2);
                this.m_tail = segment2;
            }
        }
References System.Threading.Tasks.SingleProducerSingleConsumerQueue< T >.Enqueue(), System.item, System.Threading.Tasks.SingleProducerSingleConsumerQueue< T >.Segment.m_array, System.Threading.Tasks.SingleProducerSingleConsumerQueue< T >.Segment.m_next, System.Threading.Tasks.SingleProducerSingleConsumerQueue< T >.m_tail, and System.Threading.Volatile.Write().
Referenced by System.Threading.Tasks.SingleProducerSingleConsumerQueue< T >.Enqueue().