Terraria Decompiled: System.Collections.SortedList.RemoveAt
RemoveAt()
virtual void System.Collections.SortedList.RemoveAt (int index) inline virtual
Reimplemented in System.Collections.SortedList.SyncSortedList.
Definition at line 420 of file SortedList.cs.
        {
            if (index < 0 || index >= this.Count)
            {
                throw new ArgumentOutOfRangeException("index", "Index was out of range. Must be non-negative and less than the size of the collection.");
            }
            this._size--;
            if (index < this._size)
            {
                Array.Copy(this.keys, index + 1, this.keys, index, this._size - index);
                Array.Copy(this.values, index + 1, this.values, index, this._size - index);
            }
            this.keys[this._size] = null;
            this.values[this._size] = null;
            this.version++;
        }
References System.Collections.SortedList._size, System.Array.Copy(), System.Collections.SortedList.Count, System.Collections.SortedList.keys, System.Collections.SortedList.values, and System.Collections.SortedList.version.
Referenced by System.Collections.SortedList.Remove(), and System.Collections.SortedList.SyncSortedList.RemoveAt().