Terraria Decompiled: System.Collections.SortedList.Clone
Clone()
virtual object System.Collections.SortedList.Clone () inline virtual
Implements System.ICloneable.
Reimplemented in System.Collections.SortedList.SyncSortedList.
Definition at line 218 of file SortedList.cs.
        {
            SortedList sortedList = new SortedList(this._size);
            Array.Copy(this.keys, 0, sortedList.keys, 0, this._size);
            Array.Copy(this.values, 0, sortedList.values, 0, this._size);
            sortedList._size = this._size;
            sortedList.version = this.version;
            sortedList.comparer = this.comparer;
            return sortedList;
        }
References System.Collections.SortedList._size, System.Collections.SortedList.comparer, System.Array.Copy(), System.Collections.SortedList.keys, System.Collections.SortedList.SortedList(), System.Collections.SortedList.values, and System.Collections.SortedList.version.
Referenced by System.Collections.SortedList.SyncSortedList.Clone().