Terraria Decompiled: Terraria.GameContent.Bestiary.UnlockProgressDisplayBestiaryInfoElement.ProvideUIElement
ProvideUIElement()
UIElement Terraria.GameContent.Bestiary.UnlockProgressDisplayBestiaryInfoElement.ProvideUIElement (BestiaryUICollectionInfo info) inline
Implements Terraria.GameContent.Bestiary.IBestiaryInfoElement.
Definition at line 20 of file UnlockProgressDisplayBestiaryInfoElement.cs.
        {
            UIElement uielement = new UIPanel(Main.Assets.Request<Texture2D>("Images/UI/Bestiary/Stat_Panel", 1), null, 12, 7)
            {
                Width = new StyleDimension(-11f, 1f),
                Height = new StyleDimension(109f, 0f),
                BackgroundColor = new Color(43, 56, 101),
                BorderColor = Color.Transparent,
                Left = new StyleDimension(3f, 0f)
            };
            uielement.PaddingLeft = 4f;
            uielement.PaddingRight = 4f;
            string text = Utils.PrettifyPercentDisplay((float)info.UnlockState / 4f, "P2");
            string text2 = string.Format("{0} Entry Collected", text);
            string text3 = Utils.PrettifyPercentDisplay(this._progressReport.CompletionPercent, "P2");
            string text4 = string.Format("{0} Bestiary Collected", text3);
            int num = 8;
            UIText uitext = new UIText(text2, 0.8f, false)
            {
                HAlign = 0f,
                VAlign = 0f,
                Width = StyleDimension.FromPixelsAndPercent(0f, 1f),
                Height = StyleDimension.FromPixelsAndPercent(0f, 1f),
                IsWrapped = true,
                PaddingTop = (float)(-(float)num),
                PaddingBottom = (float)(-(float)num)
            };
            UIText uitext2 = new UIText(text4, 0.8f, false)
            {
                HAlign = 0f,
                VAlign = 0f,
                Width = StyleDimension.FromPixelsAndPercent(0f, 1f),
                Height = StyleDimension.FromPixelsAndPercent(0f, 1f),
                IsWrapped = true,
                PaddingTop = (float)(-(float)num),
                PaddingBottom = (float)(-(float)num)
            };
            this._text1 = uitext;
            this._text2 = uitext2;
            this.AddDynamicResize(uielement, uitext);
            uielement.Append(uitext);
            uielement.Append(uitext2);
            return uielement;
        }
References Terraria.GameContent.Bestiary.UnlockProgressDisplayBestiaryInfoElement._progressReport, Terraria.GameContent.Bestiary.UnlockProgressDisplayBestiaryInfoElement.AddDynamicResize(), Terraria.UI.UIElement.Append(), Terraria.Main.Assets, Microsoft.Xna.Framework.Graphics.Color, Terraria.GameContent.Bestiary.BestiaryUnlockProgressReport.CompletionPercent, Terraria.UI.StyleDimension.FromPixelsAndPercent(), System.info, Terraria.Utils.PrettifyPercentDisplay(), System.text, and Microsoft.Xna.Framework.Color.Transparent.