Terraria Decompiled: Steamworks.SteamGameServerStats.GetUserStat
GetUserStat() [1/2]
static bool Steamworks.SteamGameServerStats.GetUserStat (CSteamID steamIDUser, string pchName, out float pData) inline static
Definition at line 28 of file SteamGameServerStats.cs.
        {
            InteropHelp.TestIfAvailableGameServer();
            bool flag;
            using (InteropHelp.UTF8StringHandle utf8StringHandle = new InteropHelp.UTF8StringHandle(pchName))
            {
                flag = NativeMethods.ISteamGameServerStats_GetUserStatFloat(CSteamGameServerAPIContext.GetSteamGameServerStats(), steamIDUser, utf8StringHandle, out pData);
            }
            return flag;
        }
References Steamworks.CSteamGameServerAPIContext.GetSteamGameServerStats(), Steamworks.NativeMethods.ISteamGameServerStats_GetUserStatFloat(), and Steamworks.InteropHelp.TestIfAvailableGameServer().