Terraria Decompiled: Ionic.Zlib.GZipStream.EmitHeader
EmitHeader()
int Ionic.Zlib.GZipStream.EmitHeader () inline private
Definition at line 314 of file GZipStream.cs.
        {
            byte[] array = ((this.Comment == null) ? null : GZipStream.iso8859dash1.GetBytes(this.Comment));
            byte[] array2 = ((this.FileName == null) ? null : GZipStream.iso8859dash1.GetBytes(this.FileName));
            int num = ((this.Comment == null) ? 0 : (array.Length + 1));
            int num2 = ((this.FileName == null) ? 0 : (array2.Length + 1));
            int num3 = 10 + num + num2;
            byte[] array3 = new byte[num3];
            int num4 = 0;
            array3[num4++] = 31;
            array3[num4++] = 139;
            array3[num4++] = 8;
            byte b = 0;
            if (this.Comment != null)
            {
                b ^= 16;
            }
            if (this.FileName != null)
            {
                b ^= 8;
            }
            array3[num4++] = b;
            if (this.LastModified == null)
            {
                this.LastModified = new DateTime?(DateTime.Now);
            }
            int num5 = (int)(this.LastModified.Value - GZipStream._unixEpoch).TotalSeconds;
            Array.Copy(BitConverter.GetBytes(num5), 0, array3, num4, 4);
            num4 += 4;
            array3[num4++] = 0;
            array3[num4++] = byte.MaxValue;
            if (num2 != 0)
            {
                Array.Copy(array2, 0, array3, num4, num2 - 1);
                num4 += num2 - 1;
                array3[num4++] = 0;
            }
            if (num != 0)
            {
                Array.Copy(array, 0, array3, num4, num - 1);
                num4 += num - 1;
                array3[num4++] = 0;
            }
            this._baseStream._stream.Write(array3, 0, array3.Length);
            return array3.Length;
        }
References Ionic.Zlib.GZipStream._baseStream, Ionic.Zlib.ZlibBaseStream._stream, Ionic.Zlib.GZipStream._unixEpoch, System.array, Ionic.Zlib.GZipStream.Comment, System.Array.Copy(), Ionic.Zlib.GZipStream.FileName, System.BitConverter.GetBytes(), System.Text.Encoding.GetBytes(), int, Ionic.Zlib.GZipStream.iso8859dash1, Ionic.Zlib.GZipStream.LastModified, System.DateTime.Now, and System.IO.Stream.Write().
Referenced by Ionic.Zlib.GZipStream.Write().