Terraria Decompiled: System.Runtime.CompilerServices.ConditionalWeakTable.Rehash
Rehash()
void System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Rehash () inline private
Definition at line 75 of file ConditionalWeakTable.cs.
        {
            this.RecomputeSize();
            uint prime = (uint)HashHelpers.GetPrime(((int)((float)this.size / 0.7f) << 1) | 1);
            if (prime > (float)this.data.Length * 0.5f && prime < (float)this.data.Length * 1.1f)
            {
                this.RehashWithoutResize();
                return;
            }
            Ephemeron[] array = new Ephemeron[prime];
            GC.register_ephemeron_array(array);
            this.size = 0;
            for (int i = 0; i < this.data.Length; i++)
            {
                object key = this.data[i].key;
                object value = this.data[i].value;
                if (key != null && key != GC.EPHEMERON_TOMBSTONE)
                {
                    int num = array.Length;
                    int num2 = -1;
                    int num4;
                    int num3 = (num4 = (RuntimeHelpers.GetHashCode(key) & int.MaxValue) % num);
                    do
                    {
                        object key2 = array[num4].key;
                        if (key2 == null || key2 == GC.EPHEMERON_TOMBSTONE)
{
                            goto IL_00D3;
                        }
                        if (++num4 == num)
{
                            num4 = 0;
                        }
                    }
                    while (num4 != num3);
                    IL_00ED:
                    array[num2].key = key;
                    array[num2].value = value;
                    this.size++;
                    goto IL_0118;
                    IL_00D3:
                    num2 = num4;
                    goto IL_00ED;
                }
                IL_0118:;
            }
            this.data = array;
        }
References System.array, System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.data, System.GC.EPHEMERON_TOMBSTONE, System.Runtime.CompilerServices.RuntimeHelpers.GetHashCode(), System.Collections.HashHelpers.GetPrime(), System.key, System.Runtime.CompilerServices.Ephemeron.key, System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.RecomputeSize(), System.GC.register_ephemeron_array(), System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.RehashWithoutResize(), System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.size, System.value, and System.Runtime.CompilerServices.Ephemeron.value.
Referenced by System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Add(), and System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.AddOrUpdate().