Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyles.GetStyleForWall
GetStyleForWall()
static DungeonGenerationStyleData Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyles.GetStyleForWall (List< DungeonGenerationStyleData > styles, int wallType) inline static
Definition at line 80 of file DungeonGenerationStyles.cs.
        {
            foreach (DungeonGenerationStyleData dungeonGenerationStyleData in styles)
            {
                if (dungeonGenerationStyleData.WallIsInStyle(wallType, false))
                {
                    return dungeonGenerationStyleData;
                }
                if (dungeonGenerationStyleData.SubStyles != null && dungeonGenerationStyleData.SubStyles.Count > 0)
                {
                    foreach (DungeonGenerationStyleData dungeonGenerationStyleData2 in dungeonGenerationStyleData.SubStyles)
                    {
                        if (dungeonGenerationStyleData2.WallIsInStyle(wallType, false))
{
                            return dungeonGenerationStyleData2;
                        }
                    }
                }
            }
            return null;
        }
References Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.SubStyles, and Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.WallIsInStyle().
Referenced by Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalBanners.Banners(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalBookshelves.Bookshelves(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.CalculatePlatformAndDoorsOnHallway(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.CalculatePlatformsAndDoorsOnEdgesOfRoom(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalGroundFurniture.GroundFurniture_ActuallyGenerateFurniture(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalLights.Lights(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalPaintings.Paintings(), and Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalPaintings.Paintings_GetPaintingEntry().