Terraria Decompiled: Terraria.Testing.ChatCommands.DebugMessage.Deserialize
Deserialize()
static DebugMessage Terraria.Testing.ChatCommands.DebugMessage.Deserialize (byte author, BinaryReader reader) inline static
Definition at line 96 of file DebugMessage.cs.
        {
            string text = reader.ReadString();
            string text2 = reader.ReadString();
            Vector2 vector = reader.ReadVector2();
            return new DebugMessage(author, text, text2, vector);
        }
References Terraria.Testing.ChatCommands.DebugMessage.DebugMessage(), System.IO.BinaryReader.ReadString(), and System.text.
Referenced by Terraria.GameContent.NetModules.NetDebugModule.Deserialize().