Terraria Decompiled: Terraria.GameContent.Creative.CreativePowers.ModifyWindDirectionAndStrength.UpdateSliderAndShowMultiplierMouseOver
UpdateSliderAndShowMultiplierMouseOver()
void Terraria.GameContent.Creative.CreativePowers.ModifyWindDirectionAndStrength.UpdateSliderAndShowMultiplierMouseOver (UIElement affectedElement) inline private
Definition at line 2009 of file CreativePowers.cs.
            {
                if (affectedElement.IsMouseHovering)
                {
                    int num = (int)(Main.windSpeedCurrent * 50f);
                    string text = "";
                    if (num < 0)
                    {
                        text += Language.GetTextValue("GameUI.EastWind", Math.Abs(num));
                    }
                    else if (num > 0)
                    {
                        text += Language.GetTextValue("GameUI.WestWind", num);
                    }
                    CreativePowersHelper.AddPermissionTextIfNeeded(this, ref text);
                    Main.instance.MouseTextNoOverride(text, 0, 0, -1, -1, -1, -1, 0);
                }
            }
References System.Math.Abs(), Terraria.GameContent.Creative.CreativePowersHelper.AddPermissionTextIfNeeded(), Terraria.Localization.Language.GetTextValue(), Terraria.Main.instance, int, Terraria.UI.UIElement.IsMouseHovering, Terraria.Main.MouseTextNoOverride(), System.text, and Terraria.Main.windSpeedCurrent.
Referenced by Terraria.GameContent.Creative.CreativePowers.ModifyWindDirectionAndStrength.ProvideSlider().