Terraria Decompiled: System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.ReportUnhandledError
ReportUnhandledError()
static bool System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.ReportUnhandledError (Exception e) inline static package
Definition at line 198 of file WindowsRuntimeMarshal.cs.
        {
            if (!AppDomain.IsAppXModel())
            {
                return false;
            }
            if (!WindowsRuntimeMarshal.s_haveBlueErrorApis)
            {
                return false;
            }
            if (e != null)
            {
                IntPtr intPtr = IntPtr.Zero;
                IntPtr zero = IntPtr.Zero;
                try
                {
                    intPtr = Marshal.GetIUnknownForObject(e);
                    if (intPtr != IntPtr.Zero)
                    {
                        Marshal.QueryInterface(intPtr, ref WindowsRuntimeMarshal.s_iidIErrorInfo, out zero);
                        if (zero != IntPtr.Zero && WindowsRuntimeMarshal.RoOriginateLanguageException(Marshal.GetHRForException_WinRT(e), e.Message, zero))
{
                            IRestrictedErrorInfo restrictedErrorInfo = UnsafeNativeMethods.GetRestrictedErrorInfo();
                            if (restrictedErrorInfo != null)
{
                                WindowsRuntimeMarshal.RoReportUnhandledError(restrictedErrorInfo);
                                return true;
                            }
                        }
                    }
                }
                finally
                {
                    if (zero != IntPtr.Zero)
                    {
                        Marshal.Release(zero);
                    }
                    if (intPtr != IntPtr.Zero)
                    {
                        Marshal.Release(intPtr);
                    }
                }
                return false;
            }
            return false;
        }
References System.Runtime.InteropServices.Marshal.GetHRForException_WinRT(), System.Runtime.InteropServices.Marshal.GetIUnknownForObject(), System.Runtime.InteropServices.WindowsRuntime.UnsafeNativeMethods.GetRestrictedErrorInfo(), System.AppDomain.IsAppXModel(), System.Exception.Message, System.Runtime.InteropServices.Marshal.QueryInterface(), System.Runtime.InteropServices.Marshal.Release(), System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.RoOriginateLanguageException(), System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.RoReportUnhandledError(), System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.s_haveBlueErrorApis, System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.s_iidIErrorInfo, and System.IntPtr.Zero.
Referenced by System.Runtime.CompilerServices.AsyncMethodBuilderCore.ThrowAsync().