Terraria Decompiled: System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.GetExceptionForHR
GetExceptionForHR() [2/2]
static Exception System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.GetExceptionForHR (int hresult, Exception innerException, string messageResource) inline static package
Definition at line 133 of file WindowsRuntimeMarshal.cs.
        {
            Exception ex;
            if (innerException != null)
            {
                string text = innerException.Message;
                if (text == null && messageResource != null)
                {
                    text = Environment.GetResourceString(messageResource);
                }
                ex = new Exception(text, innerException);
            }
            else
            {
                ex = new Exception((messageResource != null) ? Environment.GetResourceString(messageResource) : null);
            }
            ex.SetErrorCode(hresult);
            return ex;
        }
References System.Environment.GetResourceString(), System.Exception.Message, System.Exception.SetErrorCode(), and System.text.
Referenced by System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.GetExceptionForHR().