Terraria Decompiled: Terraria.GameInput.LockOnHelper.SetActive
SetActive()
static void Terraria.GameInput.LockOnHelper.SetActive (bool on) inline static private
Definition at line 307 of file LockOnHelper.cs.
        {
            if (on)
            {
                if (!LockOnHelper.CanEnable())
                {
                    return;
                }
                LockOnHelper.RefreshTargets(Main.MouseWorld, 2000f);
                LockOnHelper.GetClosestTarget(Main.MouseWorld);
                if (LockOnHelper._pickedTarget >= 0)
                {
                    LockOnHelper._enabled = true;
                    return;
                }
            }
            else
            {
                LockOnHelper._enabled = false;
                LockOnHelper._targets.Clear();
                LockOnHelper._lifeTimeCounter = 0;
                LockOnHelper._threeDSTarget = -1;
                LockOnHelper._targetClosestTarget = -1;
            }
        }
References Terraria.GameInput.LockOnHelper._pickedTarget, Terraria.GameInput.LockOnHelper._targets, Terraria.GameInput.LockOnHelper.CanEnable(), System.Collections.Generic.List< T >.Clear(), Terraria.GameInput.LockOnHelper.GetClosestTarget(), Terraria.Main.MouseWorld, and Terraria.GameInput.LockOnHelper.RefreshTargets().
Referenced by Terraria.GameInput.LockOnHelper.CycleTargetFocus(), Terraria.GameInput.LockOnHelper.CycleTargetThreeDS(), Terraria.GameInput.LockOnHelper.HandlePressing(), and Terraria.GameInput.LockOnHelper.Update().