Terraria Decompiled: System.Reflection.Emit.FieldBuilder.SetCustomAttribute
SetCustomAttribute() [2/2]
void System.Reflection.Emit.FieldBuilder.SetCustomAttribute (CustomAttributeBuilder customBuilder) inline
Definition at line 183 of file FieldBuilder.cs.
        {
            this.RejectIfCreated();
            if (customBuilder == null)
            {
                throw new ArgumentNullException("customBuilder");
            }
            string fullName = customBuilder.Ctor.ReflectedType.FullName;
            if (fullName == "System.Runtime.InteropServices.FieldOffsetAttribute")
            {
                byte[] data = customBuilder.Data;
                this.offset = (int)data[2];
                this.offset |= (int)data[3] << 8;
                this.offset |= (int)data[4] << 16;
                this.offset |= (int)data[5] << 24;
                return;
            }
            if (fullName == "System.NonSerializedAttribute")
            {
                this.attrs |= FieldAttributes.NotSerialized;
                return;
            }
            if (fullName == "System.Runtime.CompilerServices.SpecialNameAttribute")
            {
                this.attrs |= FieldAttributes.SpecialName;
                return;
            }
            if (fullName == "System.Runtime.InteropServices.MarshalAsAttribute")
            {
                this.attrs |= FieldAttributes.HasFieldMarshal;
                this.marshal_info = CustomAttributeBuilder.get_umarshal(customBuilder, true);
                return;
            }
            if (this.cattrs != null)
            {
                CustomAttributeBuilder[] array = new CustomAttributeBuilder[this.cattrs.Length + 1];
                this.cattrs.CopyTo(array, 0);
                array[this.cattrs.Length] = customBuilder;
                this.cattrs = array;
                return;
            }
            this.cattrs = new CustomAttributeBuilder[1];
            this.cattrs[0] = customBuilder;
        }
References System.array, System.Reflection.Emit.FieldBuilder.cattrs, System.Reflection.Emit.CustomAttributeBuilder.Ctor, System.Reflection.Emit.CustomAttributeBuilder.Data, System.Type.FullName, System.Reflection.Emit.CustomAttributeBuilder.get_umarshal(), int, System.Reflection.MemberInfo.ReflectedType, and System.Reflection.Emit.FieldBuilder.RejectIfCreated().
Referenced by System.Reflection.Emit.FieldBuilder.SetCustomAttribute().