Terraria Decompiled: Terraria.GameContent.DontStarveSeed.ModifyNightColor
ModifyNightColor()
static void Terraria.GameContent.DontStarveSeed.ModifyNightColor (ref Color bgColorToSet, ref Color moonColor) inline static
Definition at line 11 of file DontStarveSeed.cs.
        {
            if (Main.GetMoonPhase() == MoonPhase.Full)
            {
                return;
            }
            float num = (float)(Main.time / 32400.0);
            Color color = bgColorToSet;
            Color black = Color.Black;
            Color color2 = bgColorToSet;
            float num2 = Utils.Remap(num, 0f, 0.5f, 0f, 1f, true);
            float num3 = Utils.Remap(num, 0.5f, 1f, 0f, 1f, true);
            Color color3 = Color.Lerp(Color.Lerp(color, black, num2), color2, num3);
            bgColorToSet = color3;
        }
References Microsoft.Xna.Framework.Color.Black, Terraria.Main.GetMoonPhase(), Microsoft.Xna.Framework.Color.Lerp(), Terraria.Utils.Remap(), and Terraria.Main.time.
Referenced by Terraria.Main.SetBackColor().