Terraria Decompiled: Newtonsoft.Json.Linq.JsonPath.BooleanQueryExpression.EqualsWithStringCoercion
EqualsWithStringCoercion()
bool Newtonsoft.Json.Linq.JsonPath.BooleanQueryExpression.EqualsWithStringCoercion (JValue value, JValue queryValue) inline private
Definition at line 155 of file BooleanQueryExpression.cs.
        {
            if (value.Equals(queryValue))
            {
                return true;
            }
            if (queryValue.Type != JTokenType.String)
            {
                return false;
            }
            string text = (string)queryValue.Value;
            string text2;
            switch (value.Type)
            {
            case JTokenType.Date:
            {
                using (StringWriter stringWriter = StringUtils.CreateStringWriter(64))
                {
                    if (value.Value is DateTimeOffset)
                    {
                        DateTimeUtils.WriteDateTimeOffsetString(stringWriter, (DateTimeOffset)value.Value, DateFormatHandling.IsoDateFormat, null, CultureInfo.InvariantCulture);
                    }
                    else
                    {
                        DateTimeUtils.WriteDateTimeString(stringWriter, (DateTime)value.Value, DateFormatHandling.IsoDateFormat, null, CultureInfo.InvariantCulture);
                    }
                    text2 = stringWriter.ToString();
                    goto IL_00DF;
                }
                break;
            }
            case JTokenType.Raw:
                return false;
            case JTokenType.Bytes:
                break;
            case JTokenType.Guid:
            case JTokenType.TimeSpan:
                text2 = value.Value.ToString();
                goto IL_00DF;
            case JTokenType.Uri:
                text2 = ((Uri)value.Value).OriginalString;
                goto IL_00DF;
            default:
                return false;
            }
            text2 = Convert.ToBase64String((byte[])value.Value);
            IL_00DF:
            return string.Equals(text2, text, 4);
        }
References Newtonsoft.Json.Utilities.StringUtils.CreateStringWriter(), System.Globalization.CultureInfo.InvariantCulture, System.text, System.Convert.ToBase64String(), System.IO.StringWriter.ToString(), Newtonsoft.Json.Linq.JValue.Type, Newtonsoft.Json.Linq.Uri, System.value, Newtonsoft.Json.Linq.JValue.Value, Newtonsoft.Json.Utilities.DateTimeUtils.WriteDateTimeOffsetString(), and Newtonsoft.Json.Utilities.DateTimeUtils.WriteDateTimeString().
Referenced by Newtonsoft.Json.Linq.JsonPath.BooleanQueryExpression.MatchTokens().