Terraria Decompiled: Newtonsoft.Json.Linq.JsonPath.BooleanQueryExpression.IsMatch
IsMatch()
override bool Newtonsoft.Json.Linq.JsonPath.BooleanQueryExpression.IsMatch (JToken root, JToken t) inline
Definition at line 65 of file BooleanQueryExpression.cs.
        {
            if (base.Operator == QueryOperator.Exists)
            {
                return Enumerable.Any<JToken>(this.GetResult(root, t, this.Left));
            }
            using (IEnumerator<JToken> enumerator = this.GetResult(root, t, this.Left).GetEnumerator())
            {
                if (enumerator.MoveNext())
                {
                    IEnumerable<JToken> result = this.GetResult(root, t, this.Right);
                    ICollection<JToken> collection = (result as ICollection<JToken>) ?? Enumerable.ToList<JToken>(result);
                    do
                    {
                        JToken jtoken = enumerator.Current;
                        foreach (JToken jtoken2 in collection)
{
                            if (this.MatchTokens(jtoken, jtoken2))
{
                                return true;
                            }
                        }
                    }
                    while (enumerator.MoveNext());
                }
            }
            return false;
        }
References System.collection, System.Collections.Generic.IEnumerator< out T >.Current, System.Collections.Generic.IEnumerable< out T >.GetEnumerator(), Newtonsoft.Json.Linq.JsonPath.BooleanQueryExpression.GetResult(), Newtonsoft.Json.Linq.JsonPath.BooleanQueryExpression.Left, Newtonsoft.Json.Linq.JsonPath.BooleanQueryExpression.MatchTokens(), System.Collections.IEnumerator.MoveNext(), and Newtonsoft.Json.Linq.JsonPath.BooleanQueryExpression.Right.