Terraria Decompiled: Terraria.Graphics.Light.TileLightScanner.ApplyWallLight
ApplyWallLight()
void Terraria.Graphics.Light.TileLightScanner.ApplyWallLight (Tile tile, int x, int y, ref FastRandom localRandom, ref Vector3 lightColor) inline private
Definition at line 161 of file TileLightScanner.cs.
        {
            float num = 0f;
            float num2 = 0f;
            float num3 = 0f;
            bool flag = false;
            ushort wall = tile.wall;
            if (wall <= 156)
            {
                if (wall <= 44)
                {
                    if (wall != 33)
                    {
                        if (wall == 44)
{
                            if (!this.LightIsBlocked(tile))
{
                                num = (float)Main.DiscoR / 255f * 0.15f;
                                num2 = (float)Main.DiscoG / 255f * 0.15f;
                                num3 = (float)Main.DiscoB / 255f * 0.15f;
                            }
                        }
                    }
                    else if (!this.LightIsBlocked(tile))
                    {
                        num = 0.089999996f;
                        num2 = 0.052500002f;
                        num3 = 0.24f;
                    }
                }
                else if (wall != 137)
                {
                    switch (wall)
                    {
                    case 153:
                        num = 0.6f;
                        num2 = 0.3f;
                        break;
                    case 154:
                        num = 0.6f;
                        num3 = 0.6f;
                        break;
                    case 155:
                        num = 0.6f;
                        num2 = 0.6f;
                        num3 = 0.6f;
                        break;
                    case 156:
                        num2 = 0.6f;
                        break;
                    }
                }
                else if (!this.LightIsBlocked(tile))
                {
                    float num4 = 0.4f;
                    num4 += (float)(270 - (int)Main.mouseTextColor) / 1500f;
                    num4 += (float)localRandom.Next(0, 50) * 0.0005f;
                    num = 1f * num4;
                    num2 = 0.5f * num4;
                    num3 = 0.1f * num4;
                }
            }
            else if (wall <= 176)
            {
                switch (wall)
                {
                case 164:
                    num = 0.6f;
                    break;
                case 165:
                    num3 = 0.6f;
                    break;
                case 166:
                    num = 0.6f;
                    num2 = 0.6f;
                    break;
                default:
                    switch (wall)
                    {
                    case 174:
                        if (!this.LightIsBlocked(tile))
{
                            num = 0.2975f;
                        }
                        break;
                    case 175:
                        if (!this.LightIsBlocked(tile))
{
                            if (tile.wallColor() == 0)
{
                                num = 0.075f;
                                num2 = 0.15f;
                                num3 = 0.4f;
                            }
                            else
{
                                flag = true;
                            }
                        }
                        break;
                    case 176:
                        if (!this.LightIsBlocked(tile))
{
                            num = 0.1f;
                            num2 = 0.1f;
                            num3 = 0.1f;
                        }
                        break;
                    }
                    break;
                }
            }
            else if (wall != 182)
            {
                switch (wall)
                {
                case 341:
                    if (!this.LightIsBlocked(tile))
                    {
                        num = 0.25f;
                        num2 = 0.1f;
                        num3 = 0f;
                    }
                    break;
                case 342:
                    if (!this.LightIsBlocked(tile))
                    {
                        num = 0.3f;
                        num2 = 0f;
                        num3 = 0.17f;
                    }
                    break;
                case 343:
                    if (!this.LightIsBlocked(tile))
                    {
                        num = 0f;
                        num2 = 0.25f;
                        num3 = 0f;
                    }
                    break;
                case 344:
                    if (!this.LightIsBlocked(tile))
                    {
                        num = 0f;
                        num2 = 0.16f;
                        num3 = 0.34f;
                    }
                    break;
                case 345:
                    if (!this.LightIsBlocked(tile))
                    {
                        num = 0.3f;
                        num2 = 0f;
                        num3 = 0.35f;
                    }
                    break;
                case 346:
                    if (!this.LightIsBlocked(tile))
                    {
                        num = (float)Main.DiscoR / 255f * 0.25f;
                        num2 = (float)Main.DiscoG / 255f * 0.25f;
                        num3 = (float)Main.DiscoB / 255f * 0.25f;
                    }
                    break;
                default:
                    if (wall == 357 && !this.LightIsBlocked(tile))
                    {
                        num = 0.15f;
                        num2 = 0.27f;
                        num3 = 0.3f;
                        flag = true;
                    }
                    break;
                }
            }
            else if (!this.LightIsBlocked(tile))
            {
                num = 0.24f;
                num2 = 0.12f;
                num3 = 0.089999996f;
            }
            if (flag && tile.wallColor() != 0)
            {
                Color color = WorldGen.paintColor((int)tile.wallColor());
                num = (float)color.R / 765f;
                num2 = (float)color.G / 765f;
                num3 = (float)color.B / 765f;
            }
            if (lightColor.X < num)
            {
                lightColor.X = num;
            }
            if (lightColor.Y < num2)
            {
                lightColor.Y = num2;
            }
            if (lightColor.Z < num3)
            {
                lightColor.Z = num3;
            }
        }
References Microsoft.Xna.Framework.Color.B, Terraria.Main.DiscoB, Terraria.Main.DiscoG, Terraria.Main.DiscoR, Microsoft.Xna.Framework.Color.G, Terraria.Graphics.Light.TileLightScanner.LightIsBlocked(), Terraria.Main.mouseTextColor, Terraria.WorldGen.paintColor(), Microsoft.Xna.Framework.Color.R, Terraria.Tile.wall, and Terraria.Tile.wallColor().
Referenced by Terraria.Graphics.Light.TileLightScanner.GetTileLight().