Terraria Decompiled: Terraria.Graphics.Light.TileLightScanner.ApplySurfaceLight
ApplySurfaceLight()
void Terraria.Graphics.Light.TileLightScanner.ApplySurfaceLight (Tile tile, int x, int y, ref Vector3 lightColor) inline private
Definition at line 3604 of file TileLightScanner.cs.
        {
            float num = 0f;
            float num2 = 0f;
            float num3 = 0f;
            float num4 = (float)Main.tileColor.R / 255f;
            float num5 = (float)Main.tileColor.G / 255f;
            float num6 = (float)Main.tileColor.B / 255f;
            float num7 = (num4 + num5 + num6) / 3f;
            if (tile.active() && TileID.Sets.AllowLightInWater[(int)tile.type])
            {
                if (lightColor.X < num7 && (Main.wallLight[(int)tile.wall] || tile.wall == 73 || tile.wall == 227 || (tile.invisibleWall() && !this._drawInvisibleWalls)))
                {
                    num = num4;
                    num2 = num5;
                    num3 = num6;
                }
            }
            else if ((!tile.active() || !Main.tileNoSunLight[(int)tile.type] || ((tile.slope() != 0 || tile.halfBrick() || (tile.invisibleBlock() && !this._drawInvisibleWalls)) && Main.tile[x, y - 1].liquid == 0 && Main.tile[x, y + 1].liquid == 0 && Main.tile[x - 1, y].liquid == 0 && Main.tile[x + 1, y].liquid == 0)) && lightColor.X < num7 && (Main.wallLight[(int)tile.wall] || tile.wall == 73 || tile.wall == 227 || (tile.invisibleWall() && !this._drawInvisibleWalls)))
            {
                if (tile.liquid < 200)
                {
                    if (!tile.halfBrick() || Main.tile[x, y - 1].liquid < 200)
                    {
                        num = num4;
                        num2 = num5;
                        num3 = num6;
                    }
                }
                else if (Main.liquidAlpha[13] > 0f)
                {
                    if (Main.rand == null)
                    {
                        Main.rand = new UnifiedRandom();
                    }
                    num3 = num6 * 0.175f * (1f + Main.rand.NextFloat() * 0.13f) * Main.liquidAlpha[13];
                }
            }
            if ((!tile.active() || tile.halfBrick() || !Main.tileNoSunLight[(int)tile.type]) && ((tile.wall >= 88 && tile.wall <= 93) || tile.wall == 241) && tile.liquid < 255)
            {
                num = num4;
                num2 = num5;
                num3 = num6;
                int num8 = (int)(tile.wall - 88);
                if (tile.wall == 241)
                {
                    num8 = 6;
                }
                switch (num8)
                {
                case 0:
                    num *= 0.9f;
                    num2 *= 0.15f;
                    num3 *= 0.9f;
                    break;
                case 1:
                    num *= 0.9f;
                    num2 *= 0.9f;
                    num3 *= 0.15f;
                    break;
                case 2:
                    num *= 0.15f;
                    num2 *= 0.15f;
                    num3 *= 0.9f;
                    break;
                case 3:
                    num *= 0.15f;
                    num2 *= 0.9f;
                    num3 *= 0.15f;
                    break;
                case 4:
                    num *= 0.9f;
                    num2 *= 0.15f;
                    num3 *= 0.15f;
                    break;
                case 5:
                {
                    float num9 = 0.2f;
                    float num10 = 0.7f - num9;
                    num *= num10 + (float)Main.DiscoR / 255f * num9;
                    num2 *= num10 + (float)Main.DiscoG / 255f * num9;
                    num3 *= num10 + (float)Main.DiscoB / 255f * num9;
                    break;
                }
                case 6:
                    num *= 0.9f;
                    num2 *= 0.5f;
                    num3 *= 0f;
                    break;
                }
            }
            float num11 = 1f - Main.shimmerDarken;
            num *= num11;
            num2 *= num11;
            num3 *= num11;
            if (lightColor.X < num)
            {
                lightColor.X = num;
            }
            if (lightColor.Y < num2)
            {
                lightColor.Y = num2;
            }
            if (lightColor.Z < num3)
            {
                lightColor.Z = num3;
            }
        }
References Terraria.Graphics.Light.TileLightScanner._drawInvisibleWalls, Terraria.Tile.active(), Terraria.ID.TileID.Sets.AllowLightInWater, Terraria.Main.DiscoB, Terraria.Main.DiscoG, Terraria.Main.DiscoR, Terraria.Tile.halfBrick(), int, Terraria.Tile.invisibleBlock(), Terraria.Tile.invisibleWall(), Terraria.Tile.liquid, Terraria.Main.liquidAlpha, Terraria.Main.rand, Terraria.Main.shimmerDarken, Terraria.Tile.slope(), Terraria.Main.tile, Terraria.Main.tileColor, Terraria.Main.tileNoSunLight, Terraria.Tile.type, Terraria.Tile.wall, and Terraria.Main.wallLight.
Referenced by Terraria.Graphics.Light.TileLightScanner.GetTileLight().