Terraria Decompiled: Terraria.Graphics.Light.TileLightScanner.ApplyHellLight
ApplyHellLight()
void Terraria.Graphics.Light.TileLightScanner.ApplyHellLight (Tile tile, int x, int y, ref Vector3 lightColor) inline private
Definition at line 3714 of file TileLightScanner.cs.
        {
            float num = 0f;
            float num2 = 0f;
            float num3 = 0f;
            float num4 = 0.55f + (float)Math.Sin((double)(Main.GlobalTimeWrappedHourly * 2f)) * 0.08f;
            if ((!tile.active() || !Main.tileNoSunLight[(int)tile.type] || ((tile.slope() != 0 || tile.halfBrick()) && Main.tile[x, y - 1].liquid == 0 && Main.tile[x, y + 1].liquid == 0 && Main.tile[x - 1, y].liquid == 0 && Main.tile[x + 1, y].liquid == 0)) && lightColor.X < num4 && (Main.wallLight[(int)tile.wall] || tile.wall == 73 || tile.wall == 227 || (tile.invisibleWall() && !this._drawInvisibleWalls)) && tile.liquid < 200 && (!tile.halfBrick() || Main.tile[x, y - 1].liquid < 200))
            {
                num = num4;
                num2 = num4 * 0.6f;
                num3 = num4 * 0.2f;
            }
            if ((!tile.active() || tile.halfBrick() || !Main.tileNoSunLight[(int)tile.type]) && ((tile.wall >= 88 && tile.wall <= 93) || tile.wall == 241) && tile.liquid < 255)
            {
                num = num4;
                num2 = num4 * 0.6f;
                num3 = num4 * 0.2f;
                int num5 = (int)(tile.wall - 88);
                if (tile.wall == 241)
                {
                    num5 = 6;
                }
                switch (num5)
                {
                case 0:
                    num *= 0.9f;
                    num2 *= 0.15f;
                    num3 *= 0.9f;
                    break;
                case 1:
                    num *= 0.9f;
                    num2 *= 0.9f;
                    num3 *= 0.15f;
                    break;
                case 2:
                    num *= 0.15f;
                    num2 *= 0.15f;
                    num3 *= 0.9f;
                    break;
                case 3:
                    num *= 0.15f;
                    num2 *= 0.9f;
                    num3 *= 0.15f;
                    break;
                case 4:
                    num *= 0.9f;
                    num2 *= 0.15f;
                    num3 *= 0.15f;
                    break;
                case 5:
                {
                    float num6 = 0.2f;
                    float num7 = 0.7f - num6;
                    num *= num7 + (float)Main.DiscoR / 255f * num6;
                    num2 *= num7 + (float)Main.DiscoG / 255f * num6;
                    num3 *= num7 + (float)Main.DiscoB / 255f * num6;
                    break;
                }
                case 6:
                    num *= 0.9f;
                    num2 *= 0.5f;
                    num3 *= 0f;
                    break;
                }
            }
            if (lightColor.X < num)
            {
                lightColor.X = num;
            }
            if (lightColor.Y < num2)
            {
                lightColor.Y = num2;
            }
            if (lightColor.Z < num3)
            {
                lightColor.Z = num3;
            }
        }
References Terraria.Graphics.Light.TileLightScanner._drawInvisibleWalls, Terraria.Tile.active(), Terraria.Main.DiscoB, Terraria.Main.DiscoG, Terraria.Main.DiscoR, Terraria.Tile.halfBrick(), int, Terraria.Tile.invisibleWall(), Terraria.Tile.liquid, System.Math.Sin(), Terraria.Tile.slope(), Terraria.Main.tile, Terraria.Main.tileNoSunLight, Terraria.Tile.type, Terraria.Tile.wall, and Terraria.Main.wallLight.
Referenced by Terraria.Graphics.Light.TileLightScanner.GetTileLight().