Terraria Decompiled: Terraria.Graphics.Light.TileLightScanner.GetTileMask
GetTileMask()
LightMaskMode Terraria.Graphics.Light.TileLightScanner.GetTileMask (Tile tile) inline private
Definition at line 62 of file TileLightScanner.cs.
        {
            if (this.LightIsBlocked(tile) && tile.type != 131 && !tile.inActive() && tile.slope() == 0)
            {
                if (TileID.Sets.CrackedBricks[(int)tile.type])
                {
                    return LightMaskMode.CrackedBricks;
                }
                return LightMaskMode.Solid;
            }
            else
            {
                if (tile.lava() || tile.liquid <= 128)
                {
                    return LightMaskMode.None;
                }
                if (!tile.honey())
                {
                    return LightMaskMode.Water;
                }
                return LightMaskMode.Honey;
            }
        }
References Terraria.ID.TileID.Sets.CrackedBricks, Terraria.Tile.honey(), Terraria.Tile.inActive(), Terraria.Tile.lava(), Terraria.Graphics.Light.TileLightScanner.LightIsBlocked(), Terraria.Tile.liquid, Terraria.Tile.slope(), and Terraria.Tile.type.
Referenced by Terraria.Graphics.Light.TileLightScanner.ExportTo(), and Terraria.Graphics.Light.TileLightScanner.GetMaskMode().