Terraria Decompiled: System.Threading.ThreadPoolWorkQueue.Enqueue
Enqueue()
void System.Threading.ThreadPoolWorkQueue.Enqueue (IThreadPoolWorkItem callback, bool forceGlobal) inline
Definition at line 60 of file ThreadPoolWorkQueue.cs.
        {
            ThreadPoolWorkQueueThreadLocals threadPoolWorkQueueThreadLocals = null;
            if (!forceGlobal)
            {
                threadPoolWorkQueueThreadLocals = ThreadPoolWorkQueueThreadLocals.threadLocals;
            }
            if (threadPoolWorkQueueThreadLocals != null)
            {
                threadPoolWorkQueueThreadLocals.workStealingQueue.LocalPush(callback);
            }
            else
            {
                ThreadPoolWorkQueue.QueueSegment queueSegment = this.queueHead;
                while (!queueSegment.TryEnqueue(callback))
                {
                    Interlocked.CompareExchange<ThreadPoolWorkQueue.QueueSegment>(ref queueSegment.Next, new ThreadPoolWorkQueue.QueueSegment(), null);
                    while (queueSegment.Next != null)
                    {
                        Interlocked.CompareExchange<ThreadPoolWorkQueue.QueueSegment>(ref this.queueHead, queueSegment.Next, queueSegment);
                        queueSegment = this.queueHead;
                    }
                }
            }
            ThreadPool.NotifyWorkItemQueued();
            this.EnsureThreadRequested();
        }
References System.Threading.Interlocked.CompareExchange(), System.Threading.ThreadPoolWorkQueue.EnsureThreadRequested(), System.Threading.ThreadPoolWorkQueue.QueueSegment.Next, System.Threading.ThreadPool.NotifyWorkItemQueued(), System.Threading.ThreadPoolWorkQueue.queueHead, System.Threading.ThreadPoolWorkQueueThreadLocals.threadLocals, System.Threading.ThreadPoolWorkQueue.QueueSegment.TryEnqueue(), and System.Threading.ThreadPoolWorkQueueThreadLocals.workStealingQueue.
Referenced by System.Threading.ThreadPoolWorkQueueThreadLocals.CleanUp(), System.Threading.ThreadPool.QueueUserWorkItemHelper(), and System.Threading.ThreadPool.UnsafeQueueCustomWorkItem().