Terraria Decompiled: System.Security.Permissions.SiteIdentityPermission.Union
Union()
override IPermission System.Security.Permissions.SiteIdentityPermission.Union (IPermission target) inline virtual
Reimplemented from System.Security.CodeAccessPermission.
Definition at line 118 of file SiteIdentityPermission.cs.
        {
            SiteIdentityPermission siteIdentityPermission = this.Cast(target);
            if (siteIdentityPermission == null || siteIdentityPermission.IsEmpty())
            {
                return this.Copy();
            }
            if (this.IsEmpty())
            {
                return siteIdentityPermission.Copy();
            }
            if (this.Match(siteIdentityPermission._site))
            {
                return new SiteIdentityPermission((this._site.Length < siteIdentityPermission._site.Length) ? this._site : siteIdentityPermission._site);
            }
            throw new ArgumentException(Locale.GetText("Cannot union two different sites."), "target");
        }
References System.Security.Permissions.SiteIdentityPermission._site, System.Security.Permissions.SiteIdentityPermission.Cast(), System.Security.Permissions.SiteIdentityPermission.Copy(), Locale.GetText(), System.Security.Permissions.SiteIdentityPermission.IsEmpty(), System.Security.Permissions.SiteIdentityPermission.Match(), and System.Security.Permissions.SiteIdentityPermission.SiteIdentityPermission().