Terraria Decompiled: Terraria.GameContent.UI.Elements.UIKeybindingListItem.DrawSelf
DrawSelf()
override void Terraria.GameContent.UI.Elements.UIKeybindingListItem.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 40 of file UIKeybindingListItem.cs.
        {
            float num = 6f;
            base.DrawSelf(spriteBatch);
            CalculatedStyle dimensions = base.GetDimensions();
            float num2 = dimensions.Width + 1f;
            Vector2 vector = new Vector2(dimensions.X, dimensions.Y);
            bool flag = PlayerInput.ListeningTrigger == this._keybind;
            Vector2 vector2 = new Vector2(0.8f);
            Color color = (flag ? Color.Gold : (base.IsMouseHovering ? Color.White : Color.Silver));
            color = Color.Lerp(color, Color.White, base.IsMouseHovering ? 0.5f : 0f);
            Color color2 = (base.IsMouseHovering ? this._color : this._color.MultiplyRGBA(new Color(180, 180, 180)));
            Vector2 vector3 = vector;
            Utils.DrawSettingsPanel(spriteBatch, vector3, num2, color2);
            vector3.X += 8f;
            vector3.Y += 2f + num;
            ChatManager.DrawColorCodedStringWithShadow(spriteBatch, FontAssets.ItemStack.Value, this.GetFriendlyName(), vector3, color, 0f, Vector2.Zero, vector2, num2, 2f);
            vector3.X -= 17f;
            List<string> list = PlayerInput.CurrentProfile.InputModes[this._inputmode].KeyStatus[this._keybind];
            string text = this.GenInput(list);
            if (string.IsNullOrEmpty(text))
            {
                text = Lang.menu[195].Value;
                if (!flag)
                {
                    color = new Color(80, 80, 80);
                }
            }
            Vector2 stringSize = ChatManager.GetStringSize(FontAssets.ItemStack.Value, text, vector2, -1f);
            vector3 = new Vector2(dimensions.X + dimensions.Width - stringSize.X - 10f, dimensions.Y + 2f + num);
            if (this._inputmode == InputMode.XBoxGamepad || this._inputmode == InputMode.XBoxGamepadUI)
            {
                vector3 += new Vector2(0f, -3f);
            }
            GlyphTagHandler.GlyphsScale = 0.85f;
            ChatManager.DrawColorCodedStringWithShadow(spriteBatch, FontAssets.ItemStack.Value, text, vector3, color, 0f, Vector2.Zero, vector2, num2, 2f);
            GlyphTagHandler.GlyphsScale = 1f;
        }
References Terraria.GameContent.UI.Elements.UIKeybindingListItem._color, Terraria.GameContent.UI.Elements.UIKeybindingListItem._inputmode, Terraria.GameContent.UI.Elements.UIKeybindingListItem._keybind, Microsoft.Xna.Framework.Graphics.Color, Terraria.GameInput.PlayerInput.CurrentProfile, Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.Utils.DrawSettingsPanel(), Terraria.GameContent.UI.Elements.UIKeybindingListItem.GenInput(), Terraria.UI.Chat.ChatManager.GetStringSize(), Terraria.GameInput.PlayerInputProfile.InputModes, Terraria.GameContent.FontAssets.ItemStack, Microsoft.Xna.Framework.Color.Lerp(), System.list, Terraria.Lang.menu, Microsoft.Xna.Framework.Color.Silver, System.text, ReLogic.Content.Asset< T >.Value, Terraria.Localization.LocalizedText.Value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Color.White, Terraria.UI.CalculatedStyle.Width, Microsoft.Xna.Framework.Vector2.X, Terraria.UI.CalculatedStyle.X, Terraria.UI.CalculatedStyle.Y, and Microsoft.Xna.Framework.Vector2.Zero.