Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.BinaryConverter.TypeFromInfo
TypeFromInfo()
static void System.Runtime.Serialization.Formatters.Binary.BinaryConverter.TypeFromInfo (BinaryTypeEnum binaryTypeEnum, object typeInformation, ObjectReader objectReader, BinaryAssemblyInfo assemblyInfo, out InternalPrimitiveTypeE primitiveTypeEnum, out string typeString, out Type type, out bool isVariant) inline static package
Definition at line 183 of file BinaryConverter.cs.
        {
            isVariant = false;
            primitiveTypeEnum = InternalPrimitiveTypeE.Invalid;
            typeString = null;
            type = null;
            switch (binaryTypeEnum)
            {
            case BinaryTypeEnum.Primitive:
                primitiveTypeEnum = (InternalPrimitiveTypeE)typeInformation;
                typeString = Converter.ToComType(primitiveTypeEnum);
                type = Converter.ToType(primitiveTypeEnum);
                return;
            case BinaryTypeEnum.String:
                type = Converter.typeofString;
                return;
            case BinaryTypeEnum.Object:
                type = Converter.typeofObject;
                isVariant = true;
                return;
            case BinaryTypeEnum.ObjectUrt:
            case BinaryTypeEnum.ObjectUser:
                if (typeInformation != null)
                {
                    typeString = typeInformation.ToString();
                    type = objectReader.GetType(assemblyInfo, typeString);
                    if (type == Converter.typeofObject)
                    {
                        isVariant = true;
                        return;
                    }
                }
                return;
            case BinaryTypeEnum.ObjectArray:
                type = Converter.typeofObjectArray;
                return;
            case BinaryTypeEnum.StringArray:
                type = Converter.typeofStringArray;
                return;
            case BinaryTypeEnum.PrimitiveArray:
                primitiveTypeEnum = (InternalPrimitiveTypeE)typeInformation;
                type = Converter.ToArrayType(primitiveTypeEnum);
                return;
            default:
                throw new SerializationException(Environment.GetResourceString("Invalid read type request '{0}'.", new object[] { binaryTypeEnum.ToString() }));
            }
        }
References System.Environment.GetResourceString(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.GetType(), System.Runtime.Serialization.Formatters.Binary.Converter.ToArrayType(), System.Runtime.Serialization.Formatters.Binary.Converter.ToComType(), System.Runtime.Serialization.Formatters.Binary.Converter.ToType(), System.Runtime.Serialization.Formatters.Binary.Converter.typeofObject, System.Runtime.Serialization.Formatters.Binary.Converter.typeofObjectArray, System.Runtime.Serialization.Formatters.Binary.Converter.typeofString, and System.Runtime.Serialization.Formatters.Binary.Converter.typeofStringArray.
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectMap.ObjectMap(), and System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadArray().