Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.BinaryConverter.ReadTypeInfo
ReadTypeInfo()
static object System.Runtime.Serialization.Formatters.Binary.BinaryConverter.ReadTypeInfo (BinaryTypeEnum binaryTypeEnum, __BinaryParser input, out int assemId) inline static package
Definition at line 152 of file BinaryConverter.cs.
        {
            object obj = null;
            int num = 0;
            switch (binaryTypeEnum)
            {
            case BinaryTypeEnum.Primitive:
            case BinaryTypeEnum.PrimitiveArray:
                obj = (InternalPrimitiveTypeE)input.ReadByte();
                break;
            case BinaryTypeEnum.String:
            case BinaryTypeEnum.Object:
            case BinaryTypeEnum.ObjectArray:
            case BinaryTypeEnum.StringArray:
                break;
            case BinaryTypeEnum.ObjectUrt:
                obj = input.ReadString();
                break;
            case BinaryTypeEnum.ObjectUser:
                obj = input.ReadString();
                num = input.ReadInt32();
                break;
            default:
                throw new SerializationException(Environment.GetResourceString("Invalid read type request '{0}'.", new object[] { binaryTypeEnum.ToString() }));
            }
            assemId = num;
            return obj;
        }
References System.Environment.GetResourceString(), System.input, and System.obj.
Referenced by System.Runtime.Serialization.Formatters.Binary.BinaryArray.Read(), and System.Runtime.Serialization.Formatters.Binary.BinaryObjectWithMapTyped.Read().