Terraria Decompiled: Terraria.GameContent.PortalHelper.GetPortalOutingPoint
GetPortalOutingPoint()
static Vector2 Terraria.GameContent.PortalHelper.GetPortalOutingPoint (Vector2 objectSize, Vector2 portalPosition, float portalAngle, out int bonusX, out int bonusY) inline static private
Definition at line 373 of file PortalHelper.cs.
        {
            int num = (int)Math.Round((double)(MathHelper.WrapAngle(portalAngle) / 0.7853982f));
            if (num == 2 || num == -2)
            {
                bonusX = ((num == 2) ? (-1) : 1);
                bonusY = 0;
                return portalPosition + new Vector2((num == 2) ? (-objectSize.X) : 0f, -objectSize.Y / 2f);
            }
            if (num == 0 || num == 4)
            {
                bonusX = 0;
                bonusY = ((num == 0) ? 1 : (-1));
                return portalPosition + new Vector2(-objectSize.X / 2f, (num == 0) ? 0f : (-objectSize.Y));
            }
            if (num == -3 || num == 3)
            {
                bonusX = ((num == -3) ? 1 : (-1));
                bonusY = -1;
                return portalPosition + new Vector2((num == -3) ? 0f : (-objectSize.X), -objectSize.Y);
            }
            if (num == 1 || num == -1)
            {
                bonusX = ((num == -1) ? 1 : (-1));
                bonusY = 1;
                return portalPosition + new Vector2((num == -1) ? 0f : (-objectSize.X), 0f);
            }
            bonusX = 0;
            bonusY = 0;
            return portalPosition;
        }
References int, System.Math.Round(), Microsoft.Xna.Framework.MathHelper.WrapAngle(), Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.GameContent.PortalHelper.TryGoingThroughPortals().