Terraria Decompiled: Terraria.GameContent.PortalHelper.RemoveIntersectingPortals
RemoveIntersectingPortals()
static void Terraria.GameContent.PortalHelper.RemoveIntersectingPortals (Vector2 position, float angle) inline static private
Definition at line 309 of file PortalHelper.cs.
        {
            Vector2 vector;
            Vector2 vector2;
            PortalHelper.GetPortalEdges(position, angle, out vector, out vector2);
            for (int i = 0; i < 1000; i++)
            {
                Projectile projectile = Main.projectile[i];
                if (projectile.active && projectile.type == 602)
                {
                    Vector2 vector3;
                    Vector2 vector4;
                    PortalHelper.GetPortalEdges(projectile.Center, projectile.ai[0], out vector3, out vector4);
                    if (Collision.CheckLinevLine(vector, vector2, vector3, vector4).Length != 0)
                    {
                        if (projectile.owner != Main.myPlayer && Main.netMode != 2)
{
                            NetMessage.SendData(95, -1, -1, null, projectile.owner, (float)((int)projectile.ai[1]), 0f, 0f, 0, 0, 0);
                        }
                        projectile.Kill();
                    }
                }
            }
        }
References Terraria.Projectile.active, Terraria.Projectile.ai, Terraria.Entity.Center, Terraria.Collision.CheckLinevLine(), Terraria.GameContent.PortalHelper.GetPortalEdges(), Terraria.Projectile.Kill(), Microsoft.Xna.Framework.Vector2.Length(), Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Projectile.owner, Terraria.Main.projectile, Terraria.NetMessage.SendData(), and Terraria.Projectile.type.
Referenced by Terraria.GameContent.PortalHelper.AddPortal().