Terraria Decompiled: Terraria.GameContent.PortalHelper.SyncPortalsOnPlayerJoin
SyncPortalsOnPlayerJoin()
static void Terraria.GameContent.PortalHelper.SyncPortalsOnPlayerJoin (int plr, int fluff, List< Point > dontInclude, out List< Point > portalSections) inline static
Definition at line 406 of file PortalHelper.cs.
        {
            portalSections = new List<Point>();
            for (int i = 0; i < 1000; i++)
            {
                Projectile projectile = Main.projectile[i];
                if (projectile.active && (projectile.type == 602 || projectile.type == 601))
                {
                    Vector2 center = projectile.Center;
                    int sectionX = Netplay.GetSectionX((int)(center.X / 16f));
                    int sectionY = Netplay.GetSectionY((int)(center.Y / 16f));
                    for (int j = sectionX - fluff; j < sectionX + fluff + 1; j++)
                    {
                        for (int k = sectionY - fluff; k < sectionY + fluff + 1; k++)
{
                            if (j >= 0 && j < Main.maxSectionsX && k >= 0 && k < Main.maxSectionsY && !Netplay.Clients[plr].TileSections[j, k] && !dontInclude.Contains(new Point(j, k)))
{
                                portalSections.Add(new Point(j, k));
                            }
                        }
                    }
                }
            }
        }
References Terraria.Projectile.active, Terraria.Entity.Center, Terraria.Netplay.Clients, System.Collections.Generic.List< T >.Contains(), Terraria.Netplay.GetSectionX(), Terraria.Netplay.GetSectionY(), Terraria.Main.maxSectionsY, Terraria.Main.projectile, Terraria.RemoteClient.TileSections, Terraria.Projectile.type, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.MessageBuffer.GetData().