Terraria Decompiled: System.Threading.ManualResetEventSlim.Wait
Wait() [4/6]
bool System.Threading.ManualResetEventSlim.Wait (int millisecondsTimeout, CancellationToken cancellationToken) inline
Definition at line 226 of file ManualResetEventSlim.cs.
        {
            this.ThrowIfDisposed();
            cancellationToken.ThrowIfCancellationRequested();
            if (millisecondsTimeout < -1)
            {
                throw new ArgumentOutOfRangeException("millisecondsTimeout");
            }
            if (!this.IsSet)
            {
                if (millisecondsTimeout == 0)
                {
                    return false;
                }
                uint num = 0U;
                bool flag = false;
                int num2 = millisecondsTimeout;
                if (millisecondsTimeout != -1)
                {
                    num = TimeoutHelper.GetTime();
                    flag = true;
                }
                int spinCount = this.SpinCount;
                SpinWait spinWait = default(SpinWait);
                while (spinWait.Count < spinCount)
                {
                    spinWait.SpinOnce(40);
                    if (this.IsSet)
                    {
                        return true;
                    }
                    if (spinWait.Count >= 100 && spinWait.Count % 10 == 0)
                    {
                        cancellationToken.ThrowIfCancellationRequested();
                    }
                }
                this.EnsureLockObjectCreated();
                using (cancellationToken.InternalRegisterWithoutEC(ManualResetEventSlim.s_cancellationTokenCallback, this))
                {
                    object @lock = this.m_lock;
                    lock (@lock)
                    {
                        while (!this.IsSet)
{
                            cancellationToken.ThrowIfCancellationRequested();
                            if (flag)
{
                                num2 = TimeoutHelper.UpdateTimeOut(num, millisecondsTimeout);
                                if (num2 <= 0)
{
                                    return false;
                                }
                            }
                            this.Waiters++;
                            if (this.IsSet)
{
                                int waiters = this.Waiters;
                                this.Waiters = waiters - 1;
                                return true;
                            }
                            try
{
                                if (!Monitor.Wait(this.m_lock, num2))
{
                                    return false;
                                }
                            }
                            finally
{
                                this.Waiters--;
                            }
                        }
                    }
                }
                return true;
            }
            return true;
        }
References System.Threading.SpinWait.Count, System.Threading.ManualResetEventSlim.EnsureLockObjectCreated(), System.Threading.TimeoutHelper.GetTime(), System.Threading.CancellationToken.InternalRegisterWithoutEC(), System.Threading.ManualResetEventSlim.IsSet, System.Threading.ManualResetEventSlim.m_lock, System.Threading.ManualResetEventSlim.s_cancellationTokenCallback, System.Threading.ManualResetEventSlim.SpinCount, System.Threading.SpinWait.SpinOnce(), System.Threading.CancellationToken.ThrowIfCancellationRequested(), System.Threading.ManualResetEventSlim.ThrowIfDisposed(), System.U, System.Threading.TimeoutHelper.UpdateTimeOut(), System.Threading.Monitor.Wait(), and System.Threading.ManualResetEventSlim.Waiters.