Terraria Decompiled: XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.Stereo
Stereo()
void XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.Stereo (int gr) inline private
Definition at line 1122 of file LayerIIIDecoder.cs.
        {
            if (this._Channels == 1)
            {
                for (int i = 0; i < 32; i++)
                {
                    for (int j = 0; j < 18; j += 3)
                    {
                        this._Lr[0][i][j] = this._Ro[0][i][j];
                        this._Lr[0][i][j + 1] = this._Ro[0][i][j + 1];
                        this._Lr[0][i][j + 2] = this._Ro[0][i][j + 2];
                    }
                }
                return;
            }
            GranuleInfo granuleInfo = this._SideInfo.Channels[0].Granules[gr];
            int num = this._Header.mode_extension();
            bool flag = this._Header.Mode() == 1 && (num & 2) != 0;
            bool flag2 = this._Header.Mode() == 1 && (num & 1) != 0;
            bool flag3 = this._Header.Version() == 0 || this._Header.Version() == 2;
            int num2 = granuleInfo.ScaleFacCompress & 1;
            int k;
            for (k = 0; k < 576; k++)
            {
                this.IsPos[k] = 7;
                this.IsRatio[k] = 0f;
            }
            if (flag2)
            {
                if (granuleInfo.WindowSwitchingFlag != 0 && granuleInfo.BlockType == 2)
                {
                    if (granuleInfo.MixedBlockFlag != 0)
                    {
                        int num3 = 0;
                        for (int l = 0; l < 3; l++)
{
                            int num4 = 2;
                            int m;
                            for (m = 12; m >= 3; m--)
{
                                k = this._SfBandIndex[this._Sfreq].S[m];
                                int n = this._SfBandIndex[this._Sfreq].S[m + 1] - k;
                                k = (k << 2) - k + (l + 1) * n - 1;
                                while (n > 0)
{
                                    if (this._Ro[1][k / 18][k % 18] != 0f)
{
                                        num4 = m;
                                        m = -10;
                                        n = -10;
                                    }
                                    n--;
                                    k--;
                                }
                            }
                            m = num4 + 1;
                            if (m > num3)
{
                                num3 = m;
                            }
                            int i;
                            int num5;
                            while (m < 12)
{
                                num5 = this._SfBandIndex[this._Sfreq].S[m];
                                i = this._SfBandIndex[this._Sfreq].S[m + 1] - num5;
                                k = (num5 << 2) - num5 + l * i;
                                while (i > 0)
{
                                    this.IsPos[k] = this._Scalefac[1].S[l][m];
                                    if (this.IsPos[k] != 7)
{
                                        if (flag3)
{
                                            this.GetKStereoValues(this.IsPos[k], num2, k);
                                        }
                                        else
{
                                            this.IsRatio[k] = LayerIIIDecoder.Tan12[this.IsPos[k]];
                                        }
                                    }
                                    k++;
                                    i--;
                                }
                                m++;
                            }
                            m = this._SfBandIndex[this._Sfreq].S[10];
                            i = this._SfBandIndex[this._Sfreq].S[11] - m;
                            m = (m << 2) - m + l * i;
                            num5 = this._SfBandIndex[this._Sfreq].S[11];
                            i = this._SfBandIndex[this._Sfreq].S[12] - num5;
                            k = (num5 << 2) - num5 + l * i;
                            while (i > 0)
{
                                this.IsPos[k] = this.IsPos[m];
                                if (flag3)
{
                                    this._K[0][k] = this._K[0][m];
                                    this._K[1][k] = this._K[1][m];
                                }
                                else
{
                                    this.IsRatio[k] = this.IsRatio[m];
                                }
                                k++;
                                i--;
                            }
                        }
                        if (num3 <= 3)
{
                            k = 2;
                            int j = 17;
                            int i = -1;
                            while (k >= 0)
{
                                if (this._Ro[1][k][j] != 0f)
{
                                    i = (k << 4) + (k << 1) + j;
                                    k = -1;
                                }
                                else
{
                                    j--;
                                    if (j < 0)
{
                                        k--;
                                        j = 17;
                                    }
                                }
                            }
                            k = 0;
                            while (this._SfBandIndex[this._Sfreq].L[k] <= i)
{
                                k++;
                            }
                            int m = k;
                            k = this._SfBandIndex[this._Sfreq].L[k];
                            while (m < 8)
{
                                for (i = this._SfBandIndex[this._Sfreq].L[m + 1] - this._SfBandIndex[this._Sfreq].L[m]; i > 0; i--)
{
                                    this.IsPos[k] = this._Scalefac[1].L[m];
                                    if (this.IsPos[k] != 7)
{
                                        if (flag3)
{
                                            this.GetKStereoValues(this.IsPos[k], num2, k);
                                        }
                                        else
{
                                            this.IsRatio[k] = LayerIIIDecoder.Tan12[this.IsPos[k]];
                                        }
                                    }
                                    k++;
                                }
                                m++;
                            }
                        }
                    }
                    else
                    {
                        for (int num6 = 0; num6 < 3; num6++)
{
                            int num7 = -1;
                            int m;
                            int num5;
                            for (m = 12; m >= 0; m--)
{
                                num5 = this._SfBandIndex[this._Sfreq].S[m];
                                int n = this._SfBandIndex[this._Sfreq].S[m + 1] - num5;
                                k = (num5 << 2) - num5 + (num6 + 1) * n - 1;
                                while (n > 0)
{
                                    if (this._Ro[1][k / 18][k % 18] != 0f)
{
                                        num7 = m;
                                        m = -10;
                                        n = -10;
                                    }
                                    n--;
                                    k--;
                                }
                            }
                            int i;
                            for (m = num7 + 1; m < 12; m++)
{
                                num5 = this._SfBandIndex[this._Sfreq].S[m];
                                i = this._SfBandIndex[this._Sfreq].S[m + 1] - num5;
                                k = (num5 << 2) - num5 + num6 * i;
                                while (i > 0)
{
                                    this.IsPos[k] = this._Scalefac[1].S[num6][m];
                                    if (this.IsPos[k] != 7)
{
                                        if (flag3)
{
                                            this.GetKStereoValues(this.IsPos[k], num2, k);
                                        }
                                        else
{
                                            this.IsRatio[k] = LayerIIIDecoder.Tan12[this.IsPos[k]];
                                        }
                                    }
                                    k++;
                                    i--;
                                }
                            }
                            num5 = this._SfBandIndex[this._Sfreq].S[10];
                            int num8 = this._SfBandIndex[this._Sfreq].S[11];
                            i = num8 - num5;
                            m = (num5 << 2) - num5 + num6 * i;
                            i = this._SfBandIndex[this._Sfreq].S[12] - num8;
                            k = (num8 << 2) - num8 + num6 * i;
                            while (i > 0)
{
                                this.IsPos[k] = this.IsPos[m];
                                if (flag3)
{
                                    this._K[0][k] = this._K[0][m];
                                    this._K[1][k] = this._K[1][m];
                                }
                                else
{
                                    this.IsRatio[k] = this.IsRatio[m];
                                }
                                k++;
                                i--;
                            }
                        }
                    }
                }
                else
                {
                    k = 31;
                    int j = 17;
                    int i = 0;
                    while (k >= 0)
                    {
                        if (this._Ro[1][k][j] != 0f)
{
                            i = (k << 4) + (k << 1) + j;
                            k = -1;
                        }
                        else
{
                            j--;
                            if (j < 0)
{
                                k--;
                                j = 17;
                            }
                        }
                    }
                    k = 0;
                    while (this._SfBandIndex[this._Sfreq].L[k] <= i)
                    {
                        k++;
                    }
                    int m = k;
                    k = this._SfBandIndex[this._Sfreq].L[k];
                    while (m < 21)
                    {
                        for (i = this._SfBandIndex[this._Sfreq].L[m + 1] - this._SfBandIndex[this._Sfreq].L[m]; i > 0; i--)
{
                            this.IsPos[k] = this._Scalefac[1].L[m];
                            if (this.IsPos[k] != 7)
{
                                if (flag3)
{
                                    this.GetKStereoValues(this.IsPos[k], num2, k);
                                }
                                else
{
                                    this.IsRatio[k] = LayerIIIDecoder.Tan12[this.IsPos[k]];
                                }
                            }
                            k++;
                        }
                        m++;
                    }
                    m = this._SfBandIndex[this._Sfreq].L[20];
                    i = 576 - this._SfBandIndex[this._Sfreq].L[21];
                    while (i > 0 && k < 576)
                    {
                        this.IsPos[k] = this.IsPos[m];
                        if (flag3)
{
                            this._K[0][k] = this._K[0][m];
                            this._K[1][k] = this._K[1][m];
                        }
                        else
{
                            this.IsRatio[k] = this.IsRatio[m];
                        }
                        k++;
                        i--;
                    }
                }
            }
            k = 0;
            for (int i = 0; i < 32; i++)
            {
                for (int j = 0; j < 18; j++)
                {
                    if (this.IsPos[k] == 7)
                    {
                        if (flag)
{
                            this._Lr[0][i][j] = (this._Ro[0][i][j] + this._Ro[1][i][j]) * 0.70710677f;
                            this._Lr[1][i][j] = (this._Ro[0][i][j] - this._Ro[1][i][j]) * 0.70710677f;
                        }
                        else
{
                            this._Lr[0][i][j] = this._Ro[0][i][j];
                            this._Lr[1][i][j] = this._Ro[1][i][j];
                        }
                    }
                    else if (flag2)
                    {
                        if (flag3)
{
                            this._Lr[0][i][j] = this._Ro[0][i][j] * this._K[0][k];
                            this._Lr[1][i][j] = this._Ro[0][i][j] * this._K[1][k];
                        }
                        else
{
                            this._Lr[1][i][j] = this._Ro[0][i][j] / (1f + this.IsRatio[k]);
                            this._Lr[0][i][j] = this._Lr[1][i][j] * this.IsRatio[k];
                        }
                    }
                    k++;
                }
            }
        }
References XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._Channels, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._Header, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._K, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._Lr, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._Ro, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._Scalefac, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._SfBandIndex, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._Sfreq, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._SideInfo, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIII.GranuleInfo.BlockType, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIII.Layer3SideInfo.Channels, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.GetKStereoValues(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIII.ChannelData.Granules, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.IsPos, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.IsRatio, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIII.SBI.L, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIII.ScaleFactorData.L, System.L, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIII.GranuleInfo.MixedBlockFlag, XPT.Core.Audio.MP3Sharp.Decoding.Header.Mode(), XPT.Core.Audio.MP3Sharp.Decoding.Header.mode_extension(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIII.SBI.S, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIII.ScaleFactorData.S, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.Tan12, XPT.Core.Audio.MP3Sharp.Decoding.Header.Version(), and XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIII.GranuleInfo.WindowSwitchingFlag.
Referenced by XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.Decode().