Terraria Decompiled: XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.HuffmanDecode
HuffmanDecode()
void XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.HuffmanDecode (int ch, int gr) inline private
Definition at line 802 of file LayerIIIDecoder.cs.
        {
            this.X[0] = 0;
            this.Y[0] = 0;
            this.V[0] = 0;
            this.W[0] = 0;
            int num = this._Part2Start + this._SideInfo.Channels[ch].Granules[gr].Part23Length;
            int num2;
            int num3;
            if (this._SideInfo.Channels[ch].Granules[gr].WindowSwitchingFlag != 0 && this._SideInfo.Channels[ch].Granules[gr].BlockType == 2)
            {
                num2 = ((this._Sfreq == 8) ? 72 : 36);
                num3 = 576;
            }
            else
            {
                int num4 = this._SideInfo.Channels[ch].Granules[gr].Region0Count + 1;
                int num5 = num4 + this._SideInfo.Channels[ch].Granules[gr].Region1Count + 1;
                if (num5 > this._SfBandIndex[this._Sfreq].L.Length - 1)
                {
                    num5 = this._SfBandIndex[this._Sfreq].L.Length - 1;
                }
                num2 = this._SfBandIndex[this._Sfreq].L[num4];
                num3 = this._SfBandIndex[this._Sfreq].L[num5];
            }
            int i = 0;
            Huffman huffman;
            for (int j = 0; j < this._SideInfo.Channels[ch].Granules[gr].BigValues << 1; j += 2)
            {
                if (j < num2)
                {
                    huffman = Huffman.HuffmanTable[this._SideInfo.Channels[ch].Granules[gr].TableSelect[0]];
                }
                else if (j < num3)
                {
                    huffman = Huffman.HuffmanTable[this._SideInfo.Channels[ch].Granules[gr].TableSelect[1]];
                }
                else
                {
                    huffman = Huffman.HuffmanTable[this._SideInfo.Channels[ch].Granules[gr].TableSelect[2]];
                }
                Huffman.Decode(huffman, this.X, this.Y, this.V, this.W, this._BitReserve);
                this._Is1D[i++] = this.X[0];
                this._Is1D[i++] = this.Y[0];
                this._CheckSumHuff = this._CheckSumHuff + this.X[0] + this.Y[0];
            }
            huffman = Huffman.HuffmanTable[this._SideInfo.Channels[ch].Granules[gr].Count1TableSelect + 32];
            int num6 = this._BitReserve.HssTell();
            while (num6 < num && i < 576)
            {
                Huffman.Decode(huffman, this.X, this.Y, this.V, this.W, this._BitReserve);
                this._Is1D[i++] = this.V[0];
                this._Is1D[i++] = this.W[0];
                this._Is1D[i++] = this.X[0];
                this._Is1D[i++] = this.Y[0];
                this._CheckSumHuff = this._CheckSumHuff + this.V[0] + this.W[0] + this.X[0] + this.Y[0];
                num6 = this._BitReserve.HssTell();
            }
            if (num6 > num)
            {
                this._BitReserve.RewindStreamBits(num6 - num);
                i -= 4;
            }
            num6 = this._BitReserve.HssTell();
            if (num6 < num)
            {
                this._BitReserve.ReadBits(num - num6);
            }
            if (i < 576)
            {
                this._Nonzero[ch] = i;
            }
            else
            {
                this._Nonzero[ch] = 576;
            }
            if (i < 0)
            {
                i = 0;
            }
            while (i < 576)
            {
                this._Is1D[i] = 0;
                i++;
            }
        }
References XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._BitReserve, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._Is1D, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._Nonzero, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._SfBandIndex, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._Sfreq, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._SideInfo, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIII.GranuleInfo.BigValues, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIII.Layer3SideInfo.Channels, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIII.GranuleInfo.Count1TableSelect, XPT.Core.Audio.MP3Sharp.Decoding.Huffman.Decode(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIII.ChannelData.Granules, XPT.Core.Audio.MP3Sharp.Decoding.BitReserve.HssTell(), XPT.Core.Audio.MP3Sharp.Decoding.Huffman.HuffmanTable, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIII.SBI.L, System.L, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIII.GranuleInfo.Part23Length, XPT.Core.Audio.MP3Sharp.Decoding.BitReserve.ReadBits(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIII.GranuleInfo.Region0Count, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIII.GranuleInfo.Region1Count, XPT.Core.Audio.MP3Sharp.Decoding.BitReserve.RewindStreamBits(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIII.GranuleInfo.TableSelect, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.V, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.W, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIII.GranuleInfo.WindowSwitchingFlag, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.X, and XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.Y.
Referenced by XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.Decode().