Terraria Decompiled: XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.Decode
Decode()
void XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.Decode () inline package
Definition at line 309 of file LayerIIIDecoder.cs.
        {
            int num = this._Header.Slots();
            this.ReadSideInfo();
            for (int i = 0; i < num; i++)
            {
                this._BitReserve.PutBuffer(this._Stream.GetBitsFromBuffer(8));
            }
            int num2 = SupportClass.URShift(this._BitReserve.HssTell(), 3);
            int num3;
            if ((num3 = this._BitReserve.HssTell() & 7) != 0)
            {
                this._BitReserve.ReadBits(8 - num3);
                num2++;
            }
            int j = this._FrameStart - num2 - this._SideInfo.MainDataBegin;
            this._FrameStart += num;
            if (j < 0)
            {
                return;
            }
            if (num2 > 4096)
            {
                this._FrameStart -= 4096;
                this._BitReserve.RewindStreamBytes(4096);
            }
            while (j > 0)
            {
                this._BitReserve.ReadBits(8);
                j--;
            }
            for (int k = 0; k < this._MaxGr; k++)
            {
                for (int l = 0; l < this._Channels; l++)
                {
                    this._Part2Start = this._BitReserve.HssTell();
                    if (this._Header.Version() == 1)
                    {
                        this.ReadScaleFactors(l, k);
                    }
                    else
                    {
                        this.GLSFScaleFactors(l, k);
                    }
                    this.HuffmanDecode(l, k);
                    this.DequantizeSample(this._Ro[l], l, k);
                }
                this.Stereo(k);
                if (this._WhichChannels == 3 && this._Channels > 1)
                {
                    this.DoDownMix();
                }
                for (int l = this._FirstChannel; l <= this._LastChannel; l++)
                {
                    this.Reorder(this._Lr[l], l, k);
                    this.Antialias(l, k);
                    this.Hybrid(l, k);
                    for (int m = 18; m < 576; m += 36)
                    {
                        for (int n = 1; n < 18; n += 2)
{
                            this._Out1D[m + n] = -this._Out1D[m + n];
                        }
                    }
                    if (l == 0 || this._WhichChannels == 2)
                    {
                        for (int n = 0; n < 18; n++)
{
                            int num4 = 0;
                            for (int m = 0; m < 576; m += 18)
{
                                this._Samples1[num4] = this._Out1D[m + n];
                                num4++;
                            }
                            this._Filter1.AddSamples(this._Samples1);
                            this._Filter1.calculate_pc_samples(this._Buffer);
                        }
                    }
                    else
                    {
                        for (int n = 0; n < 18; n++)
{
                            int num4 = 0;
                            for (int m = 0; m < 576; m += 18)
{
                                this._Samples2[num4] = this._Out1D[m + n];
                                num4++;
                            }
                            this._Filter2.AddSamples(this._Samples2);
                            this._Filter2.calculate_pc_samples(this._Buffer);
                        }
                    }
                }
            }
            this._Buffer.WriteBuffer(1);
        }
References XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._BitReserve, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._Buffer, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._Channels, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._Filter1, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._Filter2, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._FirstChannel, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._Header, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._LastChannel, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._Lr, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._MaxGr, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._Out1D, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._Ro, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._Samples1, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._Samples2, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._SideInfo, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._Stream, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._WhichChannels, XPT.Core.Audio.MP3Sharp.Decoding.SynthesisFilter.AddSamples(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.Antialias(), XPT.Core.Audio.MP3Sharp.Decoding.SynthesisFilter.calculate_pc_samples(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.DequantizeSample(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.DoDownMix(), XPT.Core.Audio.MP3Sharp.Decoding.Bitstream.GetBitsFromBuffer(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.GLSFScaleFactors(), XPT.Core.Audio.MP3Sharp.Decoding.BitReserve.HssTell(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.HuffmanDecode(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.Hybrid(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIII.Layer3SideInfo.MainDataBegin, XPT.Core.Audio.MP3Sharp.Decoding.BitReserve.PutBuffer(), XPT.Core.Audio.MP3Sharp.Decoding.BitReserve.ReadBits(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.ReadScaleFactors(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.ReadSideInfo(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.Reorder(), XPT.Core.Audio.MP3Sharp.Decoding.BitReserve.RewindStreamBytes(), XPT.Core.Audio.MP3Sharp.Decoding.Header.Slots(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.Stereo(), XPT.Core.Audio.MP3Sharp.Support.SupportClass.URShift(), XPT.Core.Audio.MP3Sharp.Decoding.Header.Version(), and XPT.Core.Audio.MP3Sharp.Decoding.ABuffer.WriteBuffer().
Referenced by XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.DecodeFrame().