Terraria Decompiled: XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.LayerIIIDecoder
LayerIIIDecoder() [2/2]
XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.LayerIIIDecoder (Bitstream stream, Header header, SynthesisFilter filtera, SynthesisFilter filterb, ABuffer buffer, int whichCh) inline package
Definition at line 67 of file LayerIIIDecoder.cs.
        {
            Huffman.Initialize();
            this.InitBlock();
            this._Is1D = new int[580];
            this._Ro = new float[2][][];
            for (int i = 0; i < 2; i++)
            {
                this._Ro[i] = new float[32][];
                for (int j = 0; j < 32; j++)
                {
                    this._Ro[i][j] = new float[18];
                }
            }
            this._Lr = new float[2][][];
            for (int k = 0; k < 2; k++)
            {
                this._Lr[k] = new float[32][];
                for (int l = 0; l < 32; l++)
                {
                    this._Lr[k][l] = new float[18];
                }
            }
            this._Out1D = new float[576];
            this._Prevblck = new float[2][];
            for (int m = 0; m < 2; m++)
            {
                this._Prevblck[m] = new float[576];
            }
            this._K = new float[2][];
            for (int n = 0; n < 2; n++)
            {
                this._K[n] = new float[576];
            }
            this._Nonzero = new int[2];
            this._Scalefac = new ScaleFactorData[]
            {
                new ScaleFactorData(),
                new ScaleFactorData()
            };
            this._SfBandIndex = new SBI[9];
            int[] array = new int[]
            {
                0, 6, 12, 18, 24, 30, 36, 44, 54, 66,
                80, 96, 116, 140, 168, 200, 238, 284, 336, 396,
                464, 522, 576
            };
            int[] array2 = new int[]
            {
                0, 4, 8, 12, 18, 24, 32, 42, 56, 74,
                100, 132, 174, 192
            };
            int[] array3 = new int[]
            {
                0, 6, 12, 18, 24, 30, 36, 44, 54, 66,
                80, 96, 114, 136, 162, 194, 232, 278, 330, 394,
                464, 540, 576
            };
            int[] array4 = new int[]
            {
                0, 4, 8, 12, 18, 26, 36, 48, 62, 80,
                104, 136, 180, 192
            };
            int[] array5 = new int[]
            {
                0, 6, 12, 18, 24, 30, 36, 44, 54, 66,
                80, 96, 116, 140, 168, 200, 238, 284, 336, 396,
                464, 522, 576
            };
            int[] array6 = new int[]
            {
                0, 4, 8, 12, 18, 26, 36, 48, 62, 80,
                104, 134, 174, 192
            };
            int[] array7 = new int[]
            {
                0, 4, 8, 12, 16, 20, 24, 30, 36, 44,
                52, 62, 74, 90, 110, 134, 162, 196, 238, 288,
                342, 418, 576
            };
            int[] array8 = new int[]
            {
                0, 4, 8, 12, 16, 22, 30, 40, 52, 66,
                84, 106, 136, 192
            };
            int[] array9 = new int[]
            {
                0, 4, 8, 12, 16, 20, 24, 30, 36, 42,
                50, 60, 72, 88, 106, 128, 156, 190, 230, 276,
                330, 384, 576
            };
            int[] array10 = new int[]
            {
                0, 4, 8, 12, 16, 22, 28, 38, 50, 64,
                80, 100, 126, 192
            };
            int[] array11 = new int[]
            {
                0, 4, 8, 12, 16, 20, 24, 30, 36, 44,
                54, 66, 82, 102, 126, 156, 194, 240, 296, 364,
                448, 550, 576
            };
            int[] array12 = new int[]
            {
                0, 4, 8, 12, 16, 22, 30, 42, 58, 78,
                104, 138, 180, 192
            };
            int[] array13 = new int[]
            {
                0, 6, 12, 18, 24, 30, 36, 44, 54, 66,
                80, 96, 116, 140, 168, 200, 238, 284, 336, 396,
                464, 522, 576
            };
            int[] array14 = new int[]
            {
                0, 4, 8, 12, 18, 26, 36, 48, 62, 80,
                104, 134, 174, 192
            };
            int[] array15 = new int[]
            {
                0, 6, 12, 18, 24, 30, 36, 44, 54, 66,
                80, 96, 116, 140, 168, 200, 238, 284, 336, 396,
                464, 522, 576
            };
            int[] array16 = new int[]
            {
                0, 4, 8, 12, 18, 26, 36, 48, 62, 80,
                104, 134, 174, 192
            };
            int[] array17 = new int[]
            {
                0, 12, 24, 36, 48, 60, 72, 88, 108, 132,
                160, 192, 232, 280, 336, 400, 476, 566, 568, 570,
                572, 574, 576
            };
            int[] array18 = new int[]
            {
                0, 8, 16, 24, 36, 52, 72, 96, 124, 160,
                162, 164, 166, 192
            };
            this._SfBandIndex[0] = new SBI(array, array2);
            this._SfBandIndex[1] = new SBI(array3, array4);
            this._SfBandIndex[2] = new SBI(array5, array6);
            this._SfBandIndex[3] = new SBI(array7, array8);
            this._SfBandIndex[4] = new SBI(array9, array10);
            this._SfBandIndex[5] = new SBI(array11, array12);
            this._SfBandIndex[6] = new SBI(array13, array14);
            this._SfBandIndex[7] = new SBI(array15, array16);
            this._SfBandIndex[8] = new SBI(array17, array18);
            if (LayerIIIDecoder._reorderTable == null)
            {
                LayerIIIDecoder._reorderTable = new int[9][];
                for (int num = 0; num < 9; num++)
                {
                    LayerIIIDecoder._reorderTable[num] = LayerIIIDecoder.Reorder(this._SfBandIndex[num].S);
                }
            }
            int[] array19 = new int[] { 0, 6, 11, 16, 21 };
            int[] array20 = new int[]
            {
                default(int),
                6,
                12
            };
            this.Sftable = new ScaleFactorTable(this, array19, array20);
            this.ScalefacBuffer = new int[54];
            this._Stream = stream;
            this._Header = header;
            this._Filter1 = filtera;
            this._Filter2 = filterb;
            this._Buffer = buffer;
            this._WhichChannels = whichCh;
            this._FrameStart = 0;
            this._Channels = ((this._Header.Mode() == 3) ? 1 : 2);
            this._MaxGr = ((this._Header.Version() == 1) ? 2 : 1);
            this._Sfreq = this._Header.sample_frequency() + ((this._Header.Version() == 1) ? 3 : ((this._Header.Version() == 2) ? 6 : 0));
            if (this._Channels == 2)
            {
                switch (this._WhichChannels)
                {
                case 1:
                case 3:
                    this._FirstChannel = (this._LastChannel = 0);
                    break;
                case 2:
                    this._FirstChannel = (this._LastChannel = 1);
                    break;
                default:
                    this._FirstChannel = 0;
                    this._LastChannel = 1;
                    break;
                }
            }
            else
            {
                this._FirstChannel = (this._LastChannel = 0);
            }
            for (int num2 = 0; num2 < 2; num2++)
            {
                for (int num3 = 0; num3 < 576; num3++)
                {
                    this._Prevblck[num2][num3] = 0f;
                }
            }
            this._Nonzero[0] = (this._Nonzero[1] = 576);
            this._BitReserve = new BitReserve();
            this._SideInfo = new Layer3SideInfo();
        }
References XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._Channels, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._Header, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._K, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._Lr, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._Nonzero, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._Prevblck, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._reorderTable, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._Ro, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._SfBandIndex, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._WhichChannels, System.array, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.InitBlock(), XPT.Core.Audio.MP3Sharp.Decoding.Huffman.Initialize(), XPT.Core.Audio.MP3Sharp.Decoding.Header.Mode(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.Reorder(), System.S, XPT.Core.Audio.MP3Sharp.Decoding.Header.sample_frequency(), and XPT.Core.Audio.MP3Sharp.Decoding.Header.Version().