Terraria Decompiled: XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.GetLSFScaleData
GetLSFScaleData()
void XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.GetLSFScaleData (int ch, int gr) inline private
Definition at line 647 of file LayerIIIDecoder.cs.
        {
            int num = this._Header.mode_extension();
            int num2 = 0;
            GranuleInfo granuleInfo = this._SideInfo.Channels[ch].Granules[gr];
            int scaleFacCompress = granuleInfo.ScaleFacCompress;
            int num3;
            if (granuleInfo.BlockType == 2)
            {
                if (granuleInfo.MixedBlockFlag == 0)
                {
                    num3 = 1;
                }
                else if (granuleInfo.MixedBlockFlag == 1)
                {
                    num3 = 2;
                }
                else
                {
                    num3 = 0;
                }
            }
            else
            {
                num3 = 0;
            }
            if ((num != 1 && num != 3) || ch != 1)
            {
                if (scaleFacCompress < 400)
                {
                    this._NewSlen[0] = SupportClass.URShift(scaleFacCompress, 4) / 5;
                    this._NewSlen[1] = SupportClass.URShift(scaleFacCompress, 4) % 5;
                    this._NewSlen[2] = SupportClass.URShift(scaleFacCompress & 15, 2);
                    this._NewSlen[3] = scaleFacCompress & 3;
                    this._SideInfo.Channels[ch].Granules[gr].Preflag = 0;
                    num2 = 0;
                }
                else if (scaleFacCompress < 500)
                {
                    this._NewSlen[0] = SupportClass.URShift(scaleFacCompress - 400, 2) / 5;
                    this._NewSlen[1] = SupportClass.URShift(scaleFacCompress - 400, 2) % 5;
                    this._NewSlen[2] = (scaleFacCompress - 400) & 3;
                    this._NewSlen[3] = 0;
                    this._SideInfo.Channels[ch].Granules[gr].Preflag = 0;
                    num2 = 1;
                }
                else if (scaleFacCompress < 512)
                {
                    this._NewSlen[0] = (scaleFacCompress - 500) / 3;
                    this._NewSlen[1] = (scaleFacCompress - 500) % 3;
                    this._NewSlen[2] = 0;
                    this._NewSlen[3] = 0;
                    this._SideInfo.Channels[ch].Granules[gr].Preflag = 1;
                    num2 = 2;
                }
            }
            if ((num == 1 || num == 3) && ch == 1)
            {
                int num4 = SupportClass.URShift(scaleFacCompress, 1);
                if (num4 < 180)
                {
                    this._NewSlen[0] = num4 / 36;
                    this._NewSlen[1] = num4 % 36 / 6;
                    this._NewSlen[2] = num4 % 36 % 6;
                    this._NewSlen[3] = 0;
                    this._SideInfo.Channels[ch].Granules[gr].Preflag = 0;
                    num2 = 3;
                }
                else if (num4 < 244)
                {
                    this._NewSlen[0] = SupportClass.URShift((num4 - 180) & 63, 4);
                    this._NewSlen[1] = SupportClass.URShift((num4 - 180) & 15, 2);
                    this._NewSlen[2] = (num4 - 180) & 3;
                    this._NewSlen[3] = 0;
                    this._SideInfo.Channels[ch].Granules[gr].Preflag = 0;
                    num2 = 4;
                }
                else if (num4 < 255)
                {
                    this._NewSlen[0] = (num4 - 244) / 3;
                    this._NewSlen[1] = (num4 - 244) % 3;
                    this._NewSlen[2] = 0;
                    this._NewSlen[3] = 0;
                    this._SideInfo.Channels[ch].Granules[gr].Preflag = 0;
                    num2 = 5;
                }
            }
            for (int i = 0; i < 45; i++)
            {
                this.ScalefacBuffer[i] = 0;
            }
            int num5 = 0;
            for (int j = 0; j < 4; j++)
            {
                for (int k = 0; k < LayerIIIDecoder.NrOfSfbBlock[num2][num3][j]; k++)
                {
                    this.ScalefacBuffer[num5] = ((this._NewSlen[j] == 0) ? 0 : this._BitReserve.ReadBits(this._NewSlen[j]));
                    num5++;
                }
            }
        }
References XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._BitReserve, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._Header, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._NewSlen, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._SideInfo, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIII.GranuleInfo.BlockType, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIII.Layer3SideInfo.Channels, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIII.ChannelData.Granules, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIII.GranuleInfo.MixedBlockFlag, XPT.Core.Audio.MP3Sharp.Decoding.Header.mode_extension(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.NrOfSfbBlock, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIII.GranuleInfo.Preflag, XPT.Core.Audio.MP3Sharp.Decoding.BitReserve.ReadBits(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.ScalefacBuffer, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIII.GranuleInfo.ScaleFacCompress, and XPT.Core.Audio.MP3Sharp.Support.SupportClass.URShift().
Referenced by XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.GLSFScaleFactors().