Terraria Decompiled: XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.ReadSideInfo
ReadSideInfo()
bool XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.ReadSideInfo () inline private
Definition at line 407 of file LayerIIIDecoder.cs.
        {
            if (this._Header.Version() == 1)
            {
                this._SideInfo.MainDataBegin = this._Stream.GetBitsFromBuffer(9);
                if (this._Channels == 1)
                {
                    this._SideInfo.PrivateBits = this._Stream.GetBitsFromBuffer(5);
                }
                else
                {
                    this._SideInfo.PrivateBits = this._Stream.GetBitsFromBuffer(3);
                }
                for (int i = 0; i < this._Channels; i++)
                {
                    this._SideInfo.Channels[i].ScaleFactorBits[0] = this._Stream.GetBitsFromBuffer(1);
                    this._SideInfo.Channels[i].ScaleFactorBits[1] = this._Stream.GetBitsFromBuffer(1);
                    this._SideInfo.Channels[i].ScaleFactorBits[2] = this._Stream.GetBitsFromBuffer(1);
                    this._SideInfo.Channels[i].ScaleFactorBits[3] = this._Stream.GetBitsFromBuffer(1);
                }
                for (int j = 0; j < 2; j++)
                {
                    for (int i = 0; i < this._Channels; i++)
                    {
                        this._SideInfo.Channels[i].Granules[j].Part23Length = this._Stream.GetBitsFromBuffer(12);
                        this._SideInfo.Channels[i].Granules[j].BigValues = this._Stream.GetBitsFromBuffer(9);
                        this._SideInfo.Channels[i].Granules[j].GlobalGain = this._Stream.GetBitsFromBuffer(8);
                        this._SideInfo.Channels[i].Granules[j].ScaleFacCompress = this._Stream.GetBitsFromBuffer(4);
                        this._SideInfo.Channels[i].Granules[j].WindowSwitchingFlag = this._Stream.GetBitsFromBuffer(1);
                        if (this._SideInfo.Channels[i].Granules[j].WindowSwitchingFlag != 0)
{
                            this._SideInfo.Channels[i].Granules[j].BlockType = this._Stream.GetBitsFromBuffer(2);
                            this._SideInfo.Channels[i].Granules[j].MixedBlockFlag = this._Stream.GetBitsFromBuffer(1);
                            this._SideInfo.Channels[i].Granules[j].TableSelect[0] = this._Stream.GetBitsFromBuffer(5);
                            this._SideInfo.Channels[i].Granules[j].TableSelect[1] = this._Stream.GetBitsFromBuffer(5);
                            this._SideInfo.Channels[i].Granules[j].SubblockGain[0] = this._Stream.GetBitsFromBuffer(3);
                            this._SideInfo.Channels[i].Granules[j].SubblockGain[1] = this._Stream.GetBitsFromBuffer(3);
                            this._SideInfo.Channels[i].Granules[j].SubblockGain[2] = this._Stream.GetBitsFromBuffer(3);
                            if (this._SideInfo.Channels[i].Granules[j].BlockType == 0)
{
                                return false;
                            }
                            if (this._SideInfo.Channels[i].Granules[j].BlockType == 2 && this._SideInfo.Channels[i].Granules[j].MixedBlockFlag == 0)
{
                                this._SideInfo.Channels[i].Granules[j].Region0Count = 8;
                            }
                            else
{
                                this._SideInfo.Channels[i].Granules[j].Region0Count = 7;
                            }
                            this._SideInfo.Channels[i].Granules[j].Region1Count = 20 - this._SideInfo.Channels[i].Granules[j].Region0Count;
                        }
                        else
{
                            this._SideInfo.Channels[i].Granules[j].TableSelect[0] = this._Stream.GetBitsFromBuffer(5);
                            this._SideInfo.Channels[i].Granules[j].TableSelect[1] = this._Stream.GetBitsFromBuffer(5);
                            this._SideInfo.Channels[i].Granules[j].TableSelect[2] = this._Stream.GetBitsFromBuffer(5);
                            this._SideInfo.Channels[i].Granules[j].Region0Count = this._Stream.GetBitsFromBuffer(4);
                            this._SideInfo.Channels[i].Granules[j].Region1Count = this._Stream.GetBitsFromBuffer(3);
                            this._SideInfo.Channels[i].Granules[j].BlockType = 0;
                        }
                        this._SideInfo.Channels[i].Granules[j].Preflag = this._Stream.GetBitsFromBuffer(1);
                        this._SideInfo.Channels[i].Granules[j].ScaleFacScale = this._Stream.GetBitsFromBuffer(1);
                        this._SideInfo.Channels[i].Granules[j].Count1TableSelect = this._Stream.GetBitsFromBuffer(1);
                    }
                }
            }
            else
            {
                this._SideInfo.MainDataBegin = this._Stream.GetBitsFromBuffer(8);
                if (this._Channels == 1)
                {
                    this._SideInfo.PrivateBits = this._Stream.GetBitsFromBuffer(1);
                }
                else
                {
                    this._SideInfo.PrivateBits = this._Stream.GetBitsFromBuffer(2);
                }
                for (int i = 0; i < this._Channels; i++)
                {
                    this._SideInfo.Channels[i].Granules[0].Part23Length = this._Stream.GetBitsFromBuffer(12);
                    this._SideInfo.Channels[i].Granules[0].BigValues = this._Stream.GetBitsFromBuffer(9);
                    this._SideInfo.Channels[i].Granules[0].GlobalGain = this._Stream.GetBitsFromBuffer(8);
                    this._SideInfo.Channels[i].Granules[0].ScaleFacCompress = this._Stream.GetBitsFromBuffer(9);
                    this._SideInfo.Channels[i].Granules[0].WindowSwitchingFlag = this._Stream.GetBitsFromBuffer(1);
                    if (this._SideInfo.Channels[i].Granules[0].WindowSwitchingFlag != 0)
                    {
                        this._SideInfo.Channels[i].Granules[0].BlockType = this._Stream.GetBitsFromBuffer(2);
                        this._SideInfo.Channels[i].Granules[0].MixedBlockFlag = this._Stream.GetBitsFromBuffer(1);
                        this._SideInfo.Channels[i].Granules[0].TableSelect[0] = this._Stream.GetBitsFromBuffer(5);
                        this._SideInfo.Channels[i].Granules[0].TableSelect[1] = this._Stream.GetBitsFromBuffer(5);
                        this._SideInfo.Channels[i].Granules[0].SubblockGain[0] = this._Stream.GetBitsFromBuffer(3);
                        this._SideInfo.Channels[i].Granules[0].SubblockGain[1] = this._Stream.GetBitsFromBuffer(3);
                        this._SideInfo.Channels[i].Granules[0].SubblockGain[2] = this._Stream.GetBitsFromBuffer(3);
                        if (this._SideInfo.Channels[i].Granules[0].BlockType == 0)
{
                            return false;
                        }
                        if (this._SideInfo.Channels[i].Granules[0].BlockType == 2 && this._SideInfo.Channels[i].Granules[0].MixedBlockFlag == 0)
{
                            this._SideInfo.Channels[i].Granules[0].Region0Count = 8;
                        }
                        else
{
                            this._SideInfo.Channels[i].Granules[0].Region0Count = 7;
                            this._SideInfo.Channels[i].Granules[0].Region1Count = 20 - this._SideInfo.Channels[i].Granules[0].Region0Count;
                        }
                    }
                    else
                    {
                        this._SideInfo.Channels[i].Granules[0].TableSelect[0] = this._Stream.GetBitsFromBuffer(5);
                        this._SideInfo.Channels[i].Granules[0].TableSelect[1] = this._Stream.GetBitsFromBuffer(5);
                        this._SideInfo.Channels[i].Granules[0].TableSelect[2] = this._Stream.GetBitsFromBuffer(5);
                        this._SideInfo.Channels[i].Granules[0].Region0Count = this._Stream.GetBitsFromBuffer(4);
                        this._SideInfo.Channels[i].Granules[0].Region1Count = this._Stream.GetBitsFromBuffer(3);
                        this._SideInfo.Channels[i].Granules[0].BlockType = 0;
                    }
                    this._SideInfo.Channels[i].Granules[0].ScaleFacScale = this._Stream.GetBitsFromBuffer(1);
                    this._SideInfo.Channels[i].Granules[0].Count1TableSelect = this._Stream.GetBitsFromBuffer(1);
                }
            }
            return true;
        }
References XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._Channels, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._Header, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._SideInfo, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder._Stream, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIII.GranuleInfo.BigValues, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIII.GranuleInfo.BlockType, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIII.Layer3SideInfo.Channels, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIII.GranuleInfo.Count1TableSelect, XPT.Core.Audio.MP3Sharp.Decoding.Bitstream.GetBitsFromBuffer(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIII.GranuleInfo.GlobalGain, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIII.ChannelData.Granules, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIII.GranuleInfo.MixedBlockFlag, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIII.GranuleInfo.Part23Length, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIII.GranuleInfo.Preflag, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIII.GranuleInfo.Region0Count, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIII.GranuleInfo.Region1Count, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIII.GranuleInfo.ScaleFacCompress, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIII.GranuleInfo.ScaleFacScale, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIII.ChannelData.ScaleFactorBits, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIII.GranuleInfo.SubblockGain, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIII.GranuleInfo.TableSelect, XPT.Core.Audio.MP3Sharp.Decoding.Header.Version(), and XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIII.GranuleInfo.WindowSwitchingFlag.
Referenced by XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.Decode().