Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.Rooms.BiomeSquareDungeonRoom.BiomeRoom
BiomeRoom()
void Terraria.GameContent.Generation.Dungeon.Rooms.BiomeSquareDungeonRoom.BiomeRoom (DungeonData data, int i, int j, bool generating) inline
Definition at line 38 of file BiomeSquareDungeonRoom.cs.
        {
            UnifiedRandom unifiedRandom = new UnifiedRandom(this.settings.RandomSeed);
            BiomeDungeonRoomSettings biomeDungeonRoomSettings = (BiomeDungeonRoomSettings)this.settings;
            ushort brickTileType = this.settings.StyleData.BrickTileType;
            ushort brickWallType = this.settings.StyleData.BrickWallType;
            Vector2 position = new Vector2((float)i, (float)j);
            int num = BiomeDungeonRoom.GetBiomeRoomInnerSize(biomeDungeonRoomSettings.StyleData);
            int num2 = 8;
            int num3 = BiomeDungeonRoom.GetBiomeRoomOuterSize(biomeDungeonRoomSettings.StyleData);
            if (this.calculated)
            {
                position = this.Position;
                num = this.RoomInnerSize;
                num3 = this.RoomOuterSize;
                num2 = this.WallDepth;
            }
            int num4 = 20;
            int num5 = Math.Max(num4 + num2, Math.Min(Main.maxTilesX - num4 - num2, (int)position.X - num));
            int num6 = Math.Max(num4 + num2, Math.Min(Main.maxTilesX - num4 - num2, (int)position.X + num));
            int num7 = Math.Max(num4 + num2, Math.Min(Main.maxTilesY - num4 - num2, (int)position.Y - num));
            int num8 = Math.Max(num4 + num2, Math.Min(Main.maxTilesY - num4 - num2, (int)position.Y + num));
            int num9 = Math.Max(num4, Math.Min(Main.maxTilesX - num4, (int)position.X - num3));
            int num10 = Math.Max(num4, Math.Min(Main.maxTilesX - num4, (int)position.X + num3));
            int num11 = Math.Max(num4, Math.Min(Main.maxTilesY - num4, (int)position.Y - num3));
            int num12 = Math.Max(num4, Math.Min(Main.maxTilesY - num4, (int)position.Y + num3));
            this.InnerBounds.SetBounds(num5, num7, num6, num8);
            this.OuterBounds.SetBounds(num9, num11, num10, num12);
            data.dungeonBounds.UpdateBounds(num9, num11, num10, num12);
            if (generating)
            {
                Point center = this.OuterBounds.Center;
                for (int k = num9; k < num10; k++)
                {
                    int num13 = k;
                    for (int l = num11; l < num12; l++)
                    {
                        bool flag = false;
                        bool flag2 = false;
                        int num14 = l;
                        Tile tile = Main.tile[num13, num14];
                        Main.tile[num13, num14 - 1];
                        Main.tile[num13, num14 + 1];
                        Main.tile[num13, num14 + 2];
                        if (tile.type == 484 || tile.type == 485)
{
                            tile.active(false);
                        }
                        if (this.InnerBounds.Contains(num13, num14))
{
                            if (tile.liquid > 0)
{
                                if (flag2)
{
                                    tile.liquid = 0;
                                }
                                tile.liquidType(0);
                            }
                            if (flag)
{
                                DungeonUtils.ChangeWallType(tile, 0, false, biomeDungeonRoomSettings.OverridePaintWall);
                            }
                            else
{
                                DungeonUtils.ChangeWallType(tile, brickWallType, false, biomeDungeonRoomSettings.OverridePaintWall);
                            }
                            tile.active(false);
                        }
                        else
{
                            bool flag3 = k == num9 || k == num10 - 1 || l == num11 || l == num12 - 1 || k == num5 - 1 || k == num6 || l == num7 - 1 || l == num8;
                            if (tile.liquid > 0)
{
                                tile.liquid = 0;
                            }
                            DungeonUtils.ChangeTileType(tile, brickTileType, true, biomeDungeonRoomSettings.OverridePaintTile);
                            if (!flag3)
{
                                DungeonUtils.ChangeWallType(tile, brickWallType, false, biomeDungeonRoomSettings.OverridePaintWall);
                            }
                        }
                    }
                }
                base.BiomeRoom_FinishRoom(unifiedRandom, num9, num10, num11, num12, false);
            }
            this.RoomInnerSize = num;
            this.RoomOuterSize = num3;
            this.WallDepth = num2;
            this.Position = position;
            this.InnerBounds.CalculateHitbox();
            this.OuterBounds.CalculateHitbox();
        }
References Terraria.Tile.active(), Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.BrickTileType, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.BrickWallType, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.calculated, Terraria.GameContent.Generation.Dungeon.DungeonBounds.CalculateHitbox(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.Center, Terraria.GameContent.Generation.Dungeon.DungeonUtils.ChangeTileType(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.ChangeWallType(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.Contains(), Terraria.GameContent.Generation.Dungeon.DungeonData.dungeonBounds, Terraria.GameContent.Generation.Dungeon.Rooms.BiomeDungeonRoom.GetBiomeRoomInnerSize(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeDungeonRoom.GetBiomeRoomOuterSize(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.InnerBounds, Terraria.Tile.liquid, Terraria.Tile.liquidType(), System.Math.Max(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, System.Math.Min(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.OuterBounds, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.OverridePaintTile, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.OverridePaintWall, Terraria.GameContent.Generation.Dungeon.Rooms.BiomeSquareDungeonRoom.Position, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.RandomSeed, Terraria.GameContent.Generation.Dungeon.Rooms.BiomeSquareDungeonRoom.RoomInnerSize, Terraria.GameContent.Generation.Dungeon.Rooms.BiomeSquareDungeonRoom.RoomOuterSize, Terraria.GameContent.Generation.Dungeon.DungeonBounds.SetBounds(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.settings, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.StyleData, Terraria.Main.tile, Terraria.Tile.type, Terraria.GameContent.Generation.Dungeon.DungeonBounds.UpdateBounds(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeSquareDungeonRoom.WallDepth, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.GameContent.Generation.Dungeon.Rooms.BiomeSquareDungeonRoom.CalculateRoom(), and Terraria.GameContent.Generation.Dungeon.Rooms.BiomeSquareDungeonRoom.GenerateRoom().