Terraria Decompiled: Terraria.GameContent.UI.States.UIWorkshopHub.MakeFancyButton
MakeFancyButton()
UIElement Terraria.GameContent.UI.States.UIWorkshopHub.MakeFancyButton (string iconImagePath, string textKey) inline private
Definition at line 280 of file UIWorkshopHub.cs.
        {
            UIPanel uipanel = new UIPanel();
            int num = -3;
            int num2 = -3;
            uipanel.Width = StyleDimension.FromPixelsAndPercent((float)num, 0.5f);
            uipanel.Height = StyleDimension.FromPixelsAndPercent((float)num2, 0.5f);
            uipanel.OnMouseOver += this.SetColorsToHovered;
            uipanel.OnMouseOut += this.SetColorsToNotHovered;
            uipanel.BackgroundColor = new Color(63, 82, 151) * 0.7f;
            uipanel.BorderColor = new Color(89, 116, 213) * 0.7f;
            uipanel.SetPadding(6f);
            UIImage uiimage = new UIImage(Main.Assets.Request<Texture2D>(iconImagePath, 1))
            {
                IgnoresMouseInteraction = true,
                VAlign = 0.5f
            };
            uiimage.Left.Set(2f, 0f);
            uipanel.Append(uiimage);
            uipanel.OnMouseOver += this.ShowOptionDescription;
            uipanel.OnMouseOut += this.ClearOptionDescription;
            UIText uitext = new UIText(Language.GetText(textKey), 0.45f, true)
            {
                HAlign = 0f,
                VAlign = 0.5f,
                Width = StyleDimension.FromPixelsAndPercent(-80f, 1f),
                Height = StyleDimension.FromPixelsAndPercent(0f, 1f),
                Top = StyleDimension.FromPixelsAndPercent(5f, 0f),
                Left = StyleDimension.FromPixels(80f),
                IgnoresMouseInteraction = true,
                TextOriginX = 0f,
                TextOriginY = 0f
            };
            uitext.PaddingLeft = 0f;
            uitext.PaddingRight = 20f;
            uitext.PaddingTop = 10f;
            uitext.IsWrapped = true;
            uipanel.Append(uitext);
            uipanel.SetSnapPoint("Button", 0, null, null);
            return uipanel;
        }
References Terraria.UI.UIElement.Append(), Terraria.Main.Assets, Terraria.GameContent.UI.States.UIWorkshopHub.ClearOptionDescription(), Microsoft.Xna.Framework.Graphics.Color, Terraria.UI.StyleDimension.FromPixels(), Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.Localization.Language.GetText(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.IgnoresMouseInteraction, Terraria.UI.UIElement.Left, Terraria.UI.StyleDimension.Set(), Terraria.GameContent.UI.States.UIWorkshopHub.SetColorsToHovered(), Terraria.GameContent.UI.States.UIWorkshopHub.SetColorsToNotHovered(), Terraria.UI.UIElement.SetPadding(), Terraria.UI.UIElement.SetSnapPoint(), Terraria.GameContent.UI.States.UIWorkshopHub.ShowOptionDescription(), Terraria.UI.UIElement.Top, Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.UIWorkshopHub.MakeButton_OpenPublishResourcePacksMenu(), Terraria.GameContent.UI.States.UIWorkshopHub.MakeButton_OpenPublishWorldsMenu(), Terraria.GameContent.UI.States.UIWorkshopHub.MakeButton_OpenUseResourcePacksMenu(), and Terraria.GameContent.UI.States.UIWorkshopHub.MakeButton_OpenWorkshopWorldsImportMenu().