Terraria Decompiled: Terraria.GameContent.Events.ScreenDarkness.Update
Update()
static void Terraria.GameContent.Events.ScreenDarkness.Update (SceneState sceneState, SceneMetrics metrics) inline static
Definition at line 11 of file ScreenDarkness.cs.
        {
            float num = 0f;
            float num2 = 0.016666668f;
            Vector2 center = metrics.Center;
            for (int i = 0; i < Main.maxNPCs; i++)
            {
                if (Main.npc[i].active && Main.npc[i].type == 370 && Main.npc[i].Distance(center) < 3000f && (Main.npc[i].ai[0] >= 10f || (Main.npc[i].ai[0] == 9f && Main.npc[i].ai[2] > 120f)))
                {
                    num = 0.95f;
                    ScreenDarkness.frontColor = new Color(0, 0, 120) * 0.3f;
                    num2 = 0.03f;
                }
                if (Main.npc[i].active && Main.npc[i].type == 113 && Main.npc[i].Distance(center) < 3000f)
                {
                    float num3 = Utils.Remap(Main.npc[i].Distance(center), 2000f, 3000f, 1f, 0f, true);
                    num = Main.npc[i].localAI[1] * num3;
                    num2 = 1f;
                    ScreenDarkness.frontColor = Color.Black;
                }
            }
            sceneState.MoveTowards(ref ScreenDarkness.screenObstruction, num, num2);
        }
References Terraria.NPC.active, Terraria.NPC.ai, Microsoft.Xna.Framework.Color.Black, Terraria.SceneMetrics.Center, Microsoft.Xna.Framework.Graphics.Color, Terraria.Entity.Distance(), Terraria.NPC.localAI, Terraria.Main.maxNPCs, Terraria.SceneState.MoveTowards(), Terraria.Main.npc, Terraria.Utils.Remap(), Terraria.GameContent.Events.ScreenDarkness.screenObstruction, and Terraria.NPC.type.
Referenced by Terraria.SceneState.ApplyVisuals().