Terraria Decompiled: Terraria.GameContent.UI.States.UIWorkshopHub.OnInitialize
OnInitialize()
override void Terraria.GameContent.UI.States.UIWorkshopHub.OnInitialize () inline virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 64 of file UIWorkshopHub.cs.
        {
            base.OnInitialize();
            int num = 20;
            int num2 = 250;
            int num3 = 50 + num * 2;
            int num4 = 600;
            int num5 = num4 - num2 - num3;
            UIElement uielement = new UIElement();
            uielement.Width.Set(600f, 0f);
            uielement.Top.Set((float)num2, 0f);
            uielement.Height.Set((float)(num4 - num2), 0f);
            uielement.HAlign = 0.5f;
            int num6 = 154;
            UIPanel uipanel = new UIPanel();
            uipanel.Width.Set(0f, 1f);
            uipanel.Height.Set((float)num5, 0f);
            uipanel.BackgroundColor = new Color(33, 43, 79) * 0.8f;
            UIElement uielement2 = new UIElement();
            uielement2.Width.Set(0f, 1f);
            uielement2.Height.Set((float)num6, 0f);
            uielement2.SetPadding(0f);
            UITextPanel<LocalizedText> uitextPanel = new UITextPanel<LocalizedText>(Language.GetText("UI.WorkshopHub"), 0.8f, true);
            uitextPanel.HAlign = 0.5f;
            uitextPanel.Top.Set(-46f, 0f);
            uitextPanel.SetPadding(15f);
            uitextPanel.BackgroundColor = new Color(73, 94, 171);
            UITextPanel<LocalizedText> uitextPanel2 = new UITextPanel<LocalizedText>(Language.GetText("UI.Back"), 0.7f, true);
            uitextPanel2.Width.Set(-10f, 0.5f);
            uitextPanel2.Height.Set(50f, 0f);
            uitextPanel2.VAlign = 1f;
            uitextPanel2.HAlign = 0f;
            uitextPanel2.Top.Set((float)(-(float)num), 0f);
            uitextPanel2.OnMouseOver += this.FadedMouseOver;
            uitextPanel2.OnMouseOut += this.FadedMouseOut;
            uitextPanel2.OnLeftClick += this.GoBackClick;
            uitextPanel2.SetSnapPoint("Back", 0, null, null);
            uielement.Append(uitextPanel2);
            this._buttonBack = uitextPanel2;
            UITextPanel<LocalizedText> uitextPanel3 = new UITextPanel<LocalizedText>(Language.GetText("Workshop.ReportLogsButton"), 0.7f, true);
            uitextPanel3.Width.Set(-10f, 0.5f);
            uitextPanel3.Height.Set(50f, 0f);
            uitextPanel3.VAlign = 1f;
            uitextPanel3.HAlign = 1f;
            uitextPanel3.Top.Set((float)(-(float)num), 0f);
            uitextPanel3.OnMouseOver += this.FadedMouseOver;
            uitextPanel3.OnMouseOut += this.FadedMouseOut;
            uitextPanel3.OnLeftClick += this.GoLogsClick;
            uitextPanel3.SetSnapPoint("Logs", 0, null, null);
            uielement.Append(uitextPanel3);
            this._buttonLogs = uitextPanel3;
            UIElement uielement3 = this.MakeButton_OpenWorkshopWorldsImportMenu();
            uielement3.HAlign = 0f;
            uielement3.VAlign = 0f;
            uielement2.Append(uielement3);
            uielement3 = this.MakeButton_OpenUseResourcePacksMenu();
            uielement3.HAlign = 1f;
            uielement3.VAlign = 0f;
            uielement2.Append(uielement3);
            uielement3 = this.MakeButton_OpenPublishWorldsMenu();
            uielement3.HAlign = 0f;
            uielement3.VAlign = 1f;
            uielement2.Append(uielement3);
            uielement3 = this.MakeButton_OpenPublishResourcePacksMenu();
            uielement3.HAlign = 1f;
            uielement3.VAlign = 1f;
            uielement2.Append(uielement3);
            UIWorkshopHub.AddHorizontalSeparator(uipanel, (float)(num6 + 6 + 6));
            this.AddDescriptionPanel(uipanel, (float)(num6 + 8 + 6 + 6), (float)(num5 - num6 - 12 - 12 - 8), "desc");
            uipanel.Append(uielement2);
            uielement.Append(uipanel);
            uielement.Append(uitextPanel);
            base.Append(uielement);
        }
References Terraria.GameContent.UI.States.UIWorkshopHub.AddDescriptionPanel(), Terraria.GameContent.UI.States.UIWorkshopHub.AddHorizontalSeparator(), Terraria.UI.UIElement.Append(), Microsoft.Xna.Framework.Graphics.Color, Terraria.GameContent.UI.States.UIWorkshopHub.FadedMouseOut(), Terraria.GameContent.UI.States.UIWorkshopHub.FadedMouseOver(), Terraria.Localization.Language.GetText(), Terraria.GameContent.UI.States.UIWorkshopHub.GoBackClick(), Terraria.GameContent.UI.States.UIWorkshopHub.GoLogsClick(), Terraria.UI.UIElement.Height, Terraria.GameContent.UI.States.UIWorkshopHub.MakeButton_OpenPublishResourcePacksMenu(), Terraria.GameContent.UI.States.UIWorkshopHub.MakeButton_OpenPublishWorldsMenu(), Terraria.GameContent.UI.States.UIWorkshopHub.MakeButton_OpenUseResourcePacksMenu(), Terraria.GameContent.UI.States.UIWorkshopHub.MakeButton_OpenWorkshopWorldsImportMenu(), Terraria.UI.StyleDimension.Set(), Terraria.UI.UIElement.SetPadding(), Terraria.UI.UIElement.SetSnapPoint(), Terraria.UI.UIElement.Top, Terraria.UI.UIElement.UIElement(), and Terraria.UI.UIElement.Width.