Terraria Decompiled: Terraria.GameContent.UI.States.UIWorkshopHub.AddHorizontalSeparator
AddHorizontalSeparator()
static void Terraria.GameContent.UI.States.UIWorkshopHub.AddHorizontalSeparator (UIElement Container, float accumualtedHeight) inline static private
Definition at line 204 of file UIWorkshopHub.cs.
        {
            UIHorizontalSeparator uihorizontalSeparator = new UIHorizontalSeparator(2, true)
            {
                Width = StyleDimension.FromPercent(1f),
                Top = StyleDimension.FromPixels(accumualtedHeight - 8f),
                Color = Color.Lerp(Color.White, new Color(63, 65, 151, 255), 0.85f) * 0.9f
            };
            Container.Append(uihorizontalSeparator);
        }
References Terraria.UI.UIElement.Append(), Terraria.UI.StyleDimension.FromPercent(), Terraria.UI.StyleDimension.FromPixels(), Microsoft.Xna.Framework.Color.Lerp(), Terraria.UI.UIElement.Top, Microsoft.Xna.Framework.Color.White, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.UIWorkshopHub.OnInitialize().