Terraria Decompiled: Terraria.Graphics.Effects.FilterManager.EndCapture
EndCapture() [2/2]
void Terraria.Graphics.Effects.FilterManager.EndCapture (RenderTarget2D finalTexture, RenderTarget2D screenTarget1, RenderTarget2D screenTarget2, Vector2 screenSize, Vector2 sceneSize, Vector2 sceneOffset) inline
Definition at line 137 of file FilterManager.cs.
        {
            if (!this._captureThisFrame)
            {
                return;
            }
            this._captureThisFrame = false;
            TimeLogger.StartTimestamp startTimestamp = TimeLogger.Start();
            Rectangle rectangle = new Rectangle(0, 0, (int)screenSize.X, (int)screenSize.Y);
            RenderTarget2D renderTarget2D = screenTarget1;
            RenderTarget2D renderTarget2D2 = screenTarget2;
            GraphicsDevice graphicsDevice = Main.instance.GraphicsDevice;
            graphicsDevice.SetRenderTarget(renderTarget2D2);
            graphicsDevice.Clear(Color.Transparent);
            Main.spriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend);
            SpriteEffects effects = Main.GameViewMatrix.Effects;
            Main.spriteBatch.Draw(Main.skyTarget, Vector2.Zero, new Rectangle?(rectangle), Color.White, 0f, Vector2.Zero, 1f, effects, 0f);
            Main.spriteBatch.Draw(renderTarget2D, Vector2.Zero, new Rectangle?(rectangle), Color.White, 0f, Vector2.Zero, 1f, effects, 0f);
            Main.spriteBatch.End();
            Utils.Swap<RenderTarget2D>(ref renderTarget2D2, ref renderTarget2D);
            int num = 0;
            LinkedListNode<Filter> linkedListNode = this._activeFilters.First;
            Filter filter = null;
            while (linkedListNode != null)
            {
                Filter value = linkedListNode.Value;
                LinkedListNode<Filter> next = linkedListNode.Next;
                if (value.Priority >= this._priorityThreshold)
                {
                    num++;
                    if (num > this._activeFilterCount - this._filterLimit && value.IsVisible())
                    {
                        if (filter != null)
{
                            graphicsDevice.SetRenderTarget(renderTarget2D2);
                            graphicsDevice.Clear(Color.Transparent);
                            Main.spriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend);
                            filter.Apply(renderTarget2D.Size(), sceneSize, sceneOffset);
                            Main.spriteBatch.Draw(renderTarget2D, Vector2.Zero, new Rectangle?(rectangle), Main.ColorOfTheSkies);
                            Main.spriteBatch.End();
                            Utils.Swap<RenderTarget2D>(ref renderTarget2D2, ref renderTarget2D);
                        }
                        filter = value;
                    }
                }
                linkedListNode = next;
            }
            graphicsDevice.SetRenderTarget(finalTexture);
            graphicsDevice.Clear(Color.Transparent);
            if (Main.player[Main.myPlayer].gravDir == -1f)
            {
                Main.spriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend, SamplerState.LinearClamp, DepthStencilState.Default, RasterizerState.CullNone, null, Main.GameViewMatrix.EffectMatrix);
            }
            else
            {
                Main.spriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend);
            }
            if (filter != null)
            {
                filter.Apply(renderTarget2D.Size(), sceneSize, sceneOffset);
                Main.spriteBatch.Draw(renderTarget2D, Vector2.Zero, new Rectangle?(rectangle), Main.ColorOfTheSkies);
            }
            else
            {
                Main.spriteBatch.Draw(renderTarget2D, Vector2.Zero, new Rectangle?(rectangle), Color.White);
            }
            Main.spriteBatch.End();
            for (int i = 0; i < 8; i++)
            {
                graphicsDevice.Textures[i] = null;
            }
            TimeLogger.Filters.AddTime(startTimestamp);
        }
References Terraria.Graphics.Effects.FilterManager._activeFilterCount, Terraria.Graphics.Effects.FilterManager._activeFilters, Terraria.Graphics.Effects.FilterManager._captureThisFrame, Terraria.Graphics.Effects.FilterManager._filterLimit, Microsoft.Xna.Framework.Graphics.BlendState.AlphaBlend, Terraria.Graphics.Effects.Filter.Apply(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.Clear(), Terraria.Main.ColorOfTheSkies, Microsoft.Xna.Framework.Graphics.RasterizerState.CullNone, Microsoft.Xna.Framework.Graphics.DepthStencilState.Default, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.End(), Terraria.TimeLogger.Filters, Terraria.Main.GameViewMatrix, Microsoft.Xna.Framework.Game.GraphicsDevice, Terraria.Player.gravDir, Terraria.Main.instance, Terraria.Graphics.Effects.Filter.IsVisible(), Microsoft.Xna.Framework.Graphics.SamplerState.LinearClamp, Terraria.Main.myPlayer, Terraria.Main.player, Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetRenderTarget(), Terraria.Main.skyTarget, Terraria.Main.spriteBatch, Terraria.TimeLogger.Start(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.Textures, Microsoft.Xna.Framework.Color.Transparent, System.value, Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.