Terraria Decompiled: Ionic.Zlib.InflateBlocks.Reset
Reset()
uint Ionic.Zlib.InflateBlocks.Reset () inline package
Definition at line 21 of file InflateBlocks.cs.
        {
            uint num = this.check;
            this.mode = InflateBlocks.InflateBlockMode.TYPE;
            this.bitk = 0;
            this.bitb = 0;
            this.readAt = (this.writeAt = 0);
            if (this.checkfn != null)
            {
                this._codec._Adler32 = (this.check = Adler.Adler32(0U, null, 0, 0));
            }
            return num;
        }
References Ionic.Zlib.Adler.Adler32(), Ionic.Zlib.InflateBlocks.check, Ionic.Zlib.InflateBlocks.checkfn, and System.U.
Referenced by Ionic.Zlib.InflateBlocks.Free(), Ionic.Zlib.InflateManager.Inflate(), Ionic.Zlib.InflateBlocks.InflateBlocks(), and Ionic.Zlib.InflateManager.Reset().