Terraria Decompiled: Ionic.Zlib.InflateBlocks.Flush
Flush()
int Ionic.Zlib.InflateBlocks.Flush (int r) inline package
Definition at line 557 of file InflateBlocks.cs.
        {
            for (int i = 0; i < 2; i++)
            {
                int num;
                if (i == 0)
                {
                    num = ((this.readAt <= this.writeAt) ? this.writeAt : this.end) - this.readAt;
                }
                else
                {
                    num = this.writeAt - this.readAt;
                }
                if (num == 0)
                {
                    if (r == -5)
                    {
                        r = 0;
                    }
                    return r;
                }
                if (num > this._codec.AvailableBytesOut)
                {
                    num = this._codec.AvailableBytesOut;
                }
                if (num != 0 && r == -5)
                {
                    r = 0;
                }
                this._codec.AvailableBytesOut -= num;
                this._codec.TotalBytesOut += (long)num;
                if (this.checkfn != null)
                {
                    this._codec._Adler32 = (this.check = Adler.Adler32(this.check, this.window, this.readAt, num));
                }
                Array.Copy(this.window, this.readAt, this._codec.OutputBuffer, this._codec.NextOut, num);
                this._codec.NextOut += num;
                this.readAt += num;
                if (this.readAt == this.end && i == 0)
                {
                    this.readAt = 0;
                    if (this.writeAt == this.end)
                    {
                        this.writeAt = 0;
                    }
                }
                else
                {
                    i++;
                }
            }
            return r;
        }
References Ionic.Zlib.InflateBlocks._codec, Ionic.Zlib.Adler.Adler32(), Ionic.Zlib.ZlibCodec.AvailableBytesOut, Ionic.Zlib.InflateBlocks.check, Ionic.Zlib.InflateBlocks.checkfn, System.Array.Copy(), Ionic.Zlib.InflateBlocks.end, long, Ionic.Zlib.ZlibCodec.OutputBuffer, Ionic.Zlib.InflateBlocks.readAt, Ionic.Zlib.InflateBlocks.window, and Ionic.Zlib.InflateBlocks.writeAt.
Referenced by Ionic.Zlib.InflateCodes.Process(), and Ionic.Zlib.InflateBlocks.Process().