Terraria Decompiled: Ionic.Zlib.InflateBlocks.Process
Process()
int Ionic.Zlib.InflateBlocks.Process (int r) inline package
Definition at line 36 of file InflateBlocks.cs.
        {
            int num = this._codec.NextIn;
            int num2 = this._codec.AvailableBytesIn;
            int num3 = this.bitb;
            int i = this.bitk;
            int num4 = this.writeAt;
            int num5 = ((num4 < this.readAt) ? (this.readAt - num4 - 1) : (this.end - num4));
            int num6;
            for (;;)
            {
                switch (this.mode)
                {
                case InflateBlocks.InflateBlockMode.TYPE:
                    while (i < 3)
                    {
                        if (num2 == 0)
{
                            goto IL_0096;
                        }
                        r = 0;
                        num2--;
                        num3 |= (int)(this._codec.InputBuffer[num++] & byte.MaxValue) << i;
                        i += 8;
                    }
                    num6 = num3 & 7;
                    this.last = num6 & 1;
                    switch ((uint)num6 >> 1)
                    {
                    case 0U:
                        num3 >>= 3;
                        i -= 3;
                        num6 = i & 7;
                        num3 >>= num6;
                        i -= num6;
                        this.mode = InflateBlocks.InflateBlockMode.LENS;
                        continue;
                    case 1U:
                    {
                        int[] array = new int[1];
                        int[] array2 = new int[1];
                        int[][] array3 = new int[1][];
                        int[][] array4 = new int[1][];
                        InfTree.inflate_trees_fixed(array, array2, array3, array4, this._codec);
                        this.codes.Init(array[0], array2[0], array3[0], 0, array4[0], 0);
                        num3 >>= 3;
                        i -= 3;
                        this.mode = InflateBlocks.InflateBlockMode.CODES;
                        continue;
                    }
                    case 2U:
                        num3 >>= 3;
                        i -= 3;
                        this.mode = InflateBlocks.InflateBlockMode.TABLE;
                        continue;
                    case 3U:
                        goto IL_01E7;
                    default:
                        continue;
                    }
                    break;
                case InflateBlocks.InflateBlockMode.LENS:
                    while (i < 32)
                    {
                        if (num2 == 0)
{
                            goto IL_026B;
                        }
                        r = 0;
                        num2--;
                        num3 |= (int)(this._codec.InputBuffer[num++] & byte.MaxValue) << i;
                        i += 8;
                    }
                    if (((~num3 >> 16) & 65535) != (num3 & 65535))
                    {
                        goto Block_8;
                    }
                    this.left = num3 & 65535;
                    i = (num3 = 0);
                    this.mode = ((this.left != 0) ? InflateBlocks.InflateBlockMode.STORED : ((this.last != 0) ? InflateBlocks.InflateBlockMode.DRY : InflateBlocks.InflateBlockMode.TYPE));
                    continue;
                case InflateBlocks.InflateBlockMode.STORED:
                    if (num2 == 0)
                    {
                        goto Block_11;
                    }
                    if (num5 == 0)
                    {
                        if (num4 == this.end && this.readAt != 0)
{
                            num4 = 0;
                            num5 = ((num4 < this.readAt) ? (this.readAt - num4 - 1) : (this.end - num4));
                        }
                        if (num5 == 0)
{
                            this.writeAt = num4;
                            r = this.Flush(r);
                            num4 = this.writeAt;
                            num5 = ((num4 < this.readAt) ? (this.readAt - num4 - 1) : (this.end - num4));
                            if (num4 == this.end && this.readAt != 0)
{
                                num4 = 0;
                                num5 = ((num4 < this.readAt) ? (this.readAt - num4 - 1) : (this.end - num4));
                            }
                            if (num5 == 0)
{
                                goto Block_21;
                            }
                        }
                    }
                    r = 0;
                    num6 = this.left;
                    if (num6 > num2)
                    {
                        num6 = num2;
                    }
                    if (num6 > num5)
                    {
                        num6 = num5;
                    }
                    Array.Copy(this._codec.InputBuffer, num, this.window, num4, num6);
                    num += num6;
                    num2 -= num6;
                    num4 += num6;
                    num5 -= num6;
                    if ((this.left -= num6) == 0)
                    {
                        this.mode = ((this.last != 0) ? InflateBlocks.InflateBlockMode.DRY : InflateBlocks.InflateBlockMode.TYPE);
                        continue;
                    }
                    continue;
                case InflateBlocks.InflateBlockMode.TABLE:
                    while (i < 14)
                    {
                        if (num2 == 0)
{
                            goto IL_059C;
                        }
                        r = 0;
                        num2--;
                        num3 |= (int)(this._codec.InputBuffer[num++] & byte.MaxValue) << i;
                        i += 8;
                    }
                    num6 = (this.table = num3 & 16383);
                    if ((num6 & 31) > 29 || ((num6 >> 5) & 31) > 29)
                    {
                        goto IL_0645;
                    }
                    num6 = 258 + (num6 & 31) + ((num6 >> 5) & 31);
                    if (this.blens == null || this.blens.Length < num6)
                    {
                        this.blens = new int[num6];
                    }
                    else
                    {
                        Array.Clear(this.blens, 0, num6);
                    }
                    num3 >>= 14;
                    i -= 14;
                    this.index = 0;
                    this.mode = InflateBlocks.InflateBlockMode.BTREE;
                    goto IL_07D0;
                case InflateBlocks.InflateBlockMode.BTREE:
                    goto IL_07D0;
                case InflateBlocks.InflateBlockMode.DTREE:
                    goto IL_08C2;
                case InflateBlocks.InflateBlockMode.CODES:
                    goto IL_0CD0;
                case InflateBlocks.InflateBlockMode.DRY:
                    goto IL_0DA9;
                case InflateBlocks.InflateBlockMode.DONE:
                    goto IL_0E50;
                case InflateBlocks.InflateBlockMode.BAD:
                    goto IL_0EAA;
                }
                break;
                IL_07D0:
                while (this.index < 4 + (this.table >> 10))
                {
                    while (i < 3)
                    {
                        if (num2 == 0)
{
                            goto IL_071E;
                        }
                        r = 0;
                        num2--;
                        num3 |= (int)(this._codec.InputBuffer[num++] & byte.MaxValue) << i;
                        i += 8;
                    }
                    this.blens[InflateBlocks.border[this.index++]] = num3 & 7;
                    num3 >>= 3;
                    i -= 3;
                }
                while (this.index < 19)
                {
                    this.blens[InflateBlocks.border[this.index++]] = 0;
                }
                this.bb[0] = 7;
                num6 = this.inftree.inflate_trees_bits(this.blens, this.bb, this.tb, this.hufts, this._codec);
                if (num6 != 0)
                {
                    goto Block_34;
                }
                this.index = 0;
                this.mode = InflateBlocks.InflateBlockMode.DTREE;
                for (;;)
                {
                    IL_08C2:
                    num6 = this.table;
                    if (this.index >= 258 + (num6 & 31) + ((num6 >> 5) & 31))
                    {
                        break;
                    }
                    num6 = this.bb[0];
                    while (i < num6)
                    {
                        if (num2 == 0)
{
                            goto IL_08FC;
                        }
                        r = 0;
                        num2--;
                        num3 |= (int)(this._codec.InputBuffer[num++] & byte.MaxValue) << i;
                        i += 8;
                    }
                    num6 = this.hufts[(this.tb[0] + (num3 & InternalInflateConstants.InflateMask[num6])) * 3 + 1];
                    int num7 = this.hufts[(this.tb[0] + (num3 & InternalInflateConstants.InflateMask[num6])) * 3 + 2];
                    if (num7 < 16)
                    {
                        num3 >>= num6;
                        i -= num6;
                        this.blens[this.index++] = num7;
                    }
                    else
                    {
                        int num8 = ((num7 == 18) ? 7 : (num7 - 14));
                        int num9 = ((num7 == 18) ? 11 : 3);
                        while (i < num6 + num8)
{
                            if (num2 == 0)
{
                                goto IL_0A1D;
                            }
                            r = 0;
                            num2--;
                            num3 |= (int)(this._codec.InputBuffer[num++] & byte.MaxValue) << i;
                            i += 8;
                        }
                        num3 >>= num6;
                        i -= num6;
                        num9 += num3 & InternalInflateConstants.InflateMask[num8];
                        num3 >>= num8;
                        i -= num8;
                        num8 = this.index;
                        num6 = this.table;
                        if (num8 + num9 > 258 + (num6 & 31) + ((num6 >> 5) & 31) || (num7 == 16 && num8 < 1))
{
                            goto IL_0B00;
                        }
                        num7 = ((num7 == 16) ? this.blens[num8 - 1] : 0);
                        do
{
                            this.blens[num8++] = num7;
                        }
                        while (--num9 != 0);
                        this.index = num8;
                    }
                }
                this.tb[0] = -1;
                int[] array5 = new int[] { 9 };
                int[] array6 = new int[] { 6 };
                int[] array7 = new int[1];
                int[] array8 = new int[1];
                num6 = this.table;
                num6 = this.inftree.inflate_trees_dynamic(257 + (num6 & 31), 1 + ((num6 >> 5) & 31), this.blens, array5, array6, array7, array8, this.hufts, this._codec);
                if (num6 != 0)
                {
                    goto Block_48;
                }
                this.codes.Init(array5[0], array6[0], this.hufts, array7[0], this.hufts, array8[0]);
                this.mode = InflateBlocks.InflateBlockMode.CODES;
                IL_0CD0:
                this.bitb = num3;
                this.bitk = i;
                this._codec.AvailableBytesIn = num2;
                this._codec.TotalBytesIn += (long)(num - this._codec.NextIn);
                this._codec.NextIn = num;
                this.writeAt = num4;
                r = this.codes.Process(this, r);
                if (r != 1)
                {
                    goto Block_50;
                }
                r = 0;
                num = this._codec.NextIn;
                num2 = this._codec.AvailableBytesIn;
                num3 = this.bitb;
                i = this.bitk;
                num4 = this.writeAt;
                num5 = ((num4 < this.readAt) ? (this.readAt - num4 - 1) : (this.end - num4));
                if (this.last != 0)
                {
                    goto IL_0DA2;
                }
                this.mode = InflateBlocks.InflateBlockMode.TYPE;
            }
            r = -2;
            this.bitb = num3;
            this.bitk = i;
            this._codec.AvailableBytesIn = num2;
            this._codec.TotalBytesIn += (long)(num - this._codec.NextIn);
            this._codec.NextIn = num;
            this.writeAt = num4;
            return this.Flush(r);
            IL_0096:
            this.bitb = num3;
            this.bitk = i;
            this._codec.AvailableBytesIn = num2;
            this._codec.TotalBytesIn += (long)(num - this._codec.NextIn);
            this._codec.NextIn = num;
            this.writeAt = num4;
            return this.Flush(r);
            IL_01E7:
            num3 >>= 3;
            i -= 3;
            this.mode = InflateBlocks.InflateBlockMode.BAD;
            this._codec.Message = "invalid block type";
            r = -3;
            this.bitb = num3;
            this.bitk = i;
            this._codec.AvailableBytesIn = num2;
            this._codec.TotalBytesIn += (long)(num - this._codec.NextIn);
            this._codec.NextIn = num;
            this.writeAt = num4;
            return this.Flush(r);
            IL_026B:
            this.bitb = num3;
            this.bitk = i;
            this._codec.AvailableBytesIn = num2;
            this._codec.TotalBytesIn += (long)(num - this._codec.NextIn);
            this._codec.NextIn = num;
            this.writeAt = num4;
            return this.Flush(r);
            Block_8:
            this.mode = InflateBlocks.InflateBlockMode.BAD;
            this._codec.Message = "invalid stored block lengths";
            r = -3;
            this.bitb = num3;
            this.bitk = i;
            this._codec.AvailableBytesIn = num2;
            this._codec.TotalBytesIn += (long)(num - this._codec.NextIn);
            this._codec.NextIn = num;
            this.writeAt = num4;
            return this.Flush(r);
            Block_11:
            this.bitb = num3;
            this.bitk = i;
            this._codec.AvailableBytesIn = num2;
            this._codec.TotalBytesIn += (long)(num - this._codec.NextIn);
            this._codec.NextIn = num;
            this.writeAt = num4;
            return this.Flush(r);
            Block_21:
            this.bitb = num3;
            this.bitk = i;
            this._codec.AvailableBytesIn = num2;
            this._codec.TotalBytesIn += (long)(num - this._codec.NextIn);
            this._codec.NextIn = num;
            this.writeAt = num4;
            return this.Flush(r);
            IL_059C:
            this.bitb = num3;
            this.bitk = i;
            this._codec.AvailableBytesIn = num2;
            this._codec.TotalBytesIn += (long)(num - this._codec.NextIn);
            this._codec.NextIn = num;
            this.writeAt = num4;
            return this.Flush(r);
            IL_0645:
            this.mode = InflateBlocks.InflateBlockMode.BAD;
            this._codec.Message = "too many length or distance symbols";
            r = -3;
            this.bitb = num3;
            this.bitk = i;
            this._codec.AvailableBytesIn = num2;
            this._codec.TotalBytesIn += (long)(num - this._codec.NextIn);
            this._codec.NextIn = num;
            this.writeAt = num4;
            return this.Flush(r);
            IL_071E:
            this.bitb = num3;
            this.bitk = i;
            this._codec.AvailableBytesIn = num2;
            this._codec.TotalBytesIn += (long)(num - this._codec.NextIn);
            this._codec.NextIn = num;
            this.writeAt = num4;
            return this.Flush(r);
            Block_34:
            r = num6;
            if (r == -3)
            {
                this.blens = null;
                this.mode = InflateBlocks.InflateBlockMode.BAD;
            }
            this.bitb = num3;
            this.bitk = i;
            this._codec.AvailableBytesIn = num2;
            this._codec.TotalBytesIn += (long)(num - this._codec.NextIn);
            this._codec.NextIn = num;
            this.writeAt = num4;
            return this.Flush(r);
            IL_08FC:
            this.bitb = num3;
            this.bitk = i;
            this._codec.AvailableBytesIn = num2;
            this._codec.TotalBytesIn += (long)(num - this._codec.NextIn);
            this._codec.NextIn = num;
            this.writeAt = num4;
            return this.Flush(r);
            IL_0A1D:
            this.bitb = num3;
            this.bitk = i;
            this._codec.AvailableBytesIn = num2;
            this._codec.TotalBytesIn += (long)(num - this._codec.NextIn);
            this._codec.NextIn = num;
            this.writeAt = num4;
            return this.Flush(r);
            IL_0B00:
            this.blens = null;
            this.mode = InflateBlocks.InflateBlockMode.BAD;
            this._codec.Message = "invalid bit length repeat";
            r = -3;
            this.bitb = num3;
            this.bitk = i;
            this._codec.AvailableBytesIn = num2;
            this._codec.TotalBytesIn += (long)(num - this._codec.NextIn);
            this._codec.NextIn = num;
            this.writeAt = num4;
            return this.Flush(r);
            Block_48:
            if (num6 == -3)
            {
                this.blens = null;
                this.mode = InflateBlocks.InflateBlockMode.BAD;
            }
            r = num6;
            this.bitb = num3;
            this.bitk = i;
            this._codec.AvailableBytesIn = num2;
            this._codec.TotalBytesIn += (long)(num - this._codec.NextIn);
            this._codec.NextIn = num;
            this.writeAt = num4;
            return this.Flush(r);
            Block_50:
            return this.Flush(r);
            IL_0DA2:
            this.mode = InflateBlocks.InflateBlockMode.DRY;
            IL_0DA9:
            this.writeAt = num4;
            r = this.Flush(r);
            num4 = this.writeAt;
            int num10 = ((num4 < this.readAt) ? (this.readAt - num4 - 1) : (this.end - num4));
            if (this.readAt != this.writeAt)
            {
                this.bitb = num3;
                this.bitk = i;
                this._codec.AvailableBytesIn = num2;
                this._codec.TotalBytesIn += (long)(num - this._codec.NextIn);
                this._codec.NextIn = num;
                this.writeAt = num4;
                return this.Flush(r);
            }
            this.mode = InflateBlocks.InflateBlockMode.DONE;
            IL_0E50:
            r = 1;
            this.bitb = num3;
            this.bitk = i;
            this._codec.AvailableBytesIn = num2;
            this._codec.TotalBytesIn += (long)(num - this._codec.NextIn);
            this._codec.NextIn = num;
            this.writeAt = num4;
            return this.Flush(r);
            IL_0EAA:
            r = -3;
            this.bitb = num3;
            this.bitk = i;
            this._codec.AvailableBytesIn = num2;
            this._codec.TotalBytesIn += (long)(num - this._codec.NextIn);
            this._codec.NextIn = num;
            this.writeAt = num4;
            return this.Flush(r);
        }
References Ionic.Zlib.InflateBlocks._codec, System.array, Ionic.Zlib.ZlibCodec.AvailableBytesIn, Ionic.Zlib.InflateBlocks.bb, Ionic.Zlib.InflateBlocks.bitb, Ionic.Zlib.InflateBlocks.bitk, Ionic.Zlib.InflateBlocks.blens, Ionic.Zlib.InflateBlocks.border, System.Array.Clear(), Ionic.Zlib.InflateBlocks.codes, System.Array.Copy(), Ionic.Zlib.InflateBlocks.end, Ionic.Zlib.InflateBlocks.Flush(), Ionic.Zlib.InflateBlocks.hufts, Ionic.Zlib.InflateBlocks.index, Ionic.Zlib.InfTree.inflate_trees_bits(), Ionic.Zlib.InfTree.inflate_trees_dynamic(), Ionic.Zlib.InfTree.inflate_trees_fixed(), Ionic.Zlib.InternalInflateConstants.InflateMask, Ionic.Zlib.InflateBlocks.inftree, Ionic.Zlib.InflateCodes.Init(), Ionic.Zlib.ZlibCodec.InputBuffer, int, Ionic.Zlib.InflateBlocks.last, Ionic.Zlib.InflateBlocks.left, long, Ionic.Zlib.InflateBlocks.mode, Ionic.Zlib.ZlibCodec.NextIn, Ionic.Zlib.InflateCodes.Process(), Ionic.Zlib.InflateBlocks.readAt, Ionic.Zlib.InflateBlocks.table, Ionic.Zlib.InflateBlocks.tb, System.U, and Ionic.Zlib.InflateBlocks.writeAt.
Referenced by Ionic.Zlib.InflateManager.Inflate().