Terraria Decompiled: System.Reflection.CustomAttributeTypedArgument.CustomAttributeTypedArgument
CustomAttributeTypedArgument() [2/2]
System.Reflection.CustomAttributeTypedArgument.CustomAttributeTypedArgument (Type argumentType, object value) inline
Definition at line 24 of file CustomAttributeTypedArgument.cs.
        {
            if (argumentType == null)
            {
                throw new ArgumentNullException("argumentType");
            }
            this.Value = ((value == null) ? null : CustomAttributeTypedArgument.CanonicalizeValue(value));
            this.ArgumentType = argumentType;
            Array array = value as Array;
            if (array != null)
            {
                Type elementType = array.GetType().GetElementType();
                CustomAttributeTypedArgument[] array2 = new CustomAttributeTypedArgument[array.GetLength(0)];
                for (int i = 0; i < array2.Length; i++)
                {
                    object value2 = array.GetValue(i);
                    Type type = ((elementType == typeof(object) && value2 != null) ? value2.GetType() : elementType);
                    array2[i] = new CustomAttributeTypedArgument(type, value2);
                }
                this.Value = new ReadOnlyCollection<CustomAttributeTypedArgument>(array2);
            }
        }
References System.array, System.Reflection.Array, System.Reflection.CustomAttributeTypedArgument.CanonicalizeValue(), System.Reflection.CustomAttributeTypedArgument.CustomAttributeTypedArgument(), System.Type.GetElementType(), System.Type.GetType(), and System.value.