Terraria Decompiled: Terraria.GameContent.Items.TagEffectState.NetModule.WriteChangeActiveEffect
WriteChangeActiveEffect()
static NetPacket Terraria.GameContent.Items.TagEffectState.NetModule.WriteChangeActiveEffect (TagEffectState state) inline static
Definition at line 279 of file TagEffectState.cs.
            {
                NetPacket netPacket = Terraria.Net.NetModule.CreatePacket<TagEffectState.NetModule>(65530);
                netPacket.Writer.Write((byte)state._owner.whoAmI);
                netPacket.Writer.Write(1);
                netPacket.Writer.Write((short)state.Type);
                return netPacket;
            }
References System.state, System.IO.BinaryWriter.Write(), and Terraria.Net.NetPacket.Writer.
Referenced by Terraria.GameContent.Items.TagEffectState.NetModule.Deserialize(), and Terraria.GameContent.Items.TagEffectState.TrySetActiveEffect().