Terraria Decompiled: Newtonsoft.Json.Utilities.BidirectionalDictionary.Set
Set()
void Newtonsoft.Json.Utilities.BidirectionalDictionary< TFirst, TSecond >.Set (TFirst first, TSecond second) inline
Definition at line 32 of file BidirectionalDictionary.cs.
        {
            TSecond tsecond;
            if (this._firstToSecond.TryGetValue(first, ref tsecond) && !tsecond.Equals(second))
            {
                throw new ArgumentException(this._duplicateFirstErrorMessage.FormatWith(CultureInfo.InvariantCulture, first));
            }
            TFirst tfirst;
            if (this._secondToFirst.TryGetValue(second, ref tfirst) && !tfirst.Equals(first))
            {
                throw new ArgumentException(this._duplicateSecondErrorMessage.FormatWith(CultureInfo.InvariantCulture, second));
            }
            this._firstToSecond.Add(first, second);
            this._secondToFirst.Add(second, first);
        }
References Newtonsoft.Json.Utilities.BidirectionalDictionary< TFirst, TSecond >._duplicateFirstErrorMessage, Newtonsoft.Json.Utilities.BidirectionalDictionary< TFirst, TSecond >._duplicateSecondErrorMessage, Newtonsoft.Json.Utilities.BidirectionalDictionary< TFirst, TSecond >._firstToSecond, Newtonsoft.Json.Utilities.BidirectionalDictionary< TFirst, TSecond >._secondToFirst, System.Collections.Generic.IDictionary< TKey, TValue >.Add(), System.Globalization.CultureInfo.InvariantCulture, and System.Collections.Generic.IDictionary< TKey, TValue >.TryGetValue().
Referenced by Newtonsoft.Json.Serialization.DefaultReferenceResolver.AddReference(), and Newtonsoft.Json.Serialization.DefaultReferenceResolver.GetReference().