Terraria Decompiled: Terraria.GameContent.Items.TagEffectState.NetModule.SyncStateIfNecessary
SyncStateIfNecessary()
static void Terraria.GameContent.Items.TagEffectState.NetModule.SyncStateIfNecessary (TagEffectState state, int toClient, int ignoreClient) inline static
Definition at line 375 of file TagEffectState.cs.
            {
                if (state._effect == null || !state._effect.NetSync)
                {
                    return;
                }
                NetPacket netPacket = TagEffectState.NetModule.WriteFullState(state);
                if (toClient >= 0)
                {
                    NetManager.Instance.SendToClient(netPacket, toClient);
                    return;
                }
                NetManager.Instance.Broadcast(netPacket, ignoreClient);
            }
References Terraria.Net.NetManager.Broadcast(), Terraria.Net.NetManager.Instance, Terraria.Net.NetManager.SendToClient(), System.state, and Terraria.GameContent.Items.TagEffectState.NetModule.WriteFullState().
Referenced by Terraria.NetMessage.SyncOnePlayer().