Terraria Decompiled: Terraria.GameContent.Items.TagEffectState.NetModule.Deserialize
Deserialize()
override bool Terraria.GameContent.Items.TagEffectState.NetModule.Deserialize (BinaryReader reader, int userId) inline
Definition at line 317 of file TagEffectState.cs.
            {
                int num = (int)reader.ReadByte();
                if (Main.netMode == 2)
                {
                    num = userId;
                }
                TagEffectState tagEffectState = Main.player[num].TagEffectState;
                TagEffectState.NetModule.MessageType messageType = (TagEffectState.NetModule.MessageType)reader.ReadByte();
                switch (messageType)
                {
                case TagEffectState.NetModule.MessageType.FullState:
                    if (Main.netMode == 2)
                    {
                        return false;
                    }
                    tagEffectState.TrySetActiveEffect((int)reader.ReadInt16());
                    TagEffectState.NetModule.ReadSparseNPCTimeArray(reader, tagEffectState.TimeLeftOnNPC);
                    if (tagEffectState._effect.SyncProcs)
                    {
                        TagEffectState.NetModule.ReadSparseNPCTimeArray(reader, tagEffectState.ProcTimeLeftOnNPC);
                    }
                    break;
                case TagEffectState.NetModule.MessageType.ChangeActiveEffect:
                    tagEffectState.TrySetActiveEffect((int)reader.ReadInt16());
                    if (Main.netMode == 2)
                    {
                        NetManager.Instance.Broadcast(TagEffectState.NetModule.WriteChangeActiveEffect(tagEffectState), num);
                    }
                    break;
                case TagEffectState.NetModule.MessageType.ApplyTagToNPC:
                case TagEffectState.NetModule.MessageType.EnableProcOnNPC:
                case TagEffectState.NetModule.MessageType.ClearProcOnNPC:
                {
                    int num2 = (int)reader.ReadByte();
                    if (messageType == TagEffectState.NetModule.MessageType.ApplyTagToNPC)
                    {
                        tagEffectState.ApplyTagToNPC(Main.npc[num2]);
                    }
                    else if (messageType == TagEffectState.NetModule.MessageType.EnableProcOnNPC)
                    {
                        tagEffectState.EnableProcOnNPC(Main.npc[num2]);
                    }
                    else if (messageType == TagEffectState.NetModule.MessageType.ClearProcOnNPC)
                    {
                        tagEffectState.ClearProcOnNPC(num2);
                    }
                    if (Main.netMode == 2)
                    {
                        NetManager.Instance.Broadcast(TagEffectState.NetModule.WriteNPCChange(tagEffectState, messageType, num2), num);
                    }
                    break;
                }
                }
                return true;
            }
References Terraria.GameContent.Items.TagEffectState._effect, Terraria.GameContent.Items.TagEffectState.ApplyTagToNPC(), Terraria.Net.NetManager.Broadcast(), Terraria.GameContent.Items.TagEffectState.ClearProcOnNPC(), Terraria.GameContent.Items.TagEffectState.EnableProcOnNPC(), Terraria.Net.NetManager.Instance, int, Terraria.Main.netMode, Terraria.Main.npc, Terraria.Main.player, Terraria.GameContent.Items.TagEffectState.ProcTimeLeftOnNPC, System.IO.BinaryReader.ReadByte(), System.IO.BinaryReader.ReadInt16(), Terraria.GameContent.Items.TagEffectState.NetModule.ReadSparseNPCTimeArray(), Terraria.GameContent.Items.UniqueTagEffect.SyncProcs, Terraria.Player.TagEffectState, Terraria.GameContent.Items.TagEffectState.TimeLeftOnNPC, Terraria.GameContent.Items.TagEffectState.TrySetActiveEffect(), Terraria.GameContent.Items.TagEffectState.NetModule.WriteChangeActiveEffect(), and Terraria.GameContent.Items.TagEffectState.NetModule.WriteNPCChange().