Terraria Decompiled: Terraria.GameContent.DontStarveDarknessDamageDealer.Update
Update()
static void Terraria.GameContent.DontStarveDarknessDamageDealer.Update (Player player) inline static
Definition at line 46 of file DontStarveDarknessDamageDealer.cs.
        {
            if (player.dead || !FocusHelper.AllowDontStarveDarknessDamage || player.shimmering || Main.disableDontStarveDarknessDamage)
            {
                DontStarveDarknessDamageDealer.ResetTimer();
                return;
            }
            DontStarveDarknessDamageDealer.UpdateDarknessState(player);
            int darknessTimeBeforeStartingHits = DontStarveDarknessDamageDealer.GetDarknessTimeBeforeStartingHits();
            if (DontStarveDarknessDamageDealer.darknessTimer >= darknessTimeBeforeStartingHits)
            {
                DontStarveDarknessDamageDealer.darknessTimer = darknessTimeBeforeStartingHits;
                DontStarveDarknessDamageDealer.darknessHitTimer++;
                if (DontStarveDarknessDamageDealer.darknessHitTimer > 60 && !player.immune)
                {
                    int darknessDamagePerHit = DontStarveDarknessDamageDealer.GetDarknessDamagePerHit();
                    SoundEngine.PlaySound(SoundID.Item1, player.Center, 0f, 1f);
                    player.Hurt(PlayerDeathReason.ByOther(17), darknessDamagePerHit, 0, false, false, false, -1, true);
                    DontStarveDarknessDamageDealer.darknessHitTimer = 0;
                }
            }
        }
References Terraria.FocusHelper.AllowDontStarveDarknessDamage, Terraria.DataStructures.PlayerDeathReason.ByOther(), Terraria.Entity.Center, Terraria.GameContent.DontStarveDarknessDamageDealer.darknessHitTimer, Terraria.GameContent.DontStarveDarknessDamageDealer.darknessTimer, Terraria.Player.dead, Terraria.Main.disableDontStarveDarknessDamage, Terraria.GameContent.DontStarveDarknessDamageDealer.GetDarknessDamagePerHit(), Terraria.GameContent.DontStarveDarknessDamageDealer.GetDarknessTimeBeforeStartingHits(), Terraria.Player.Hurt(), Terraria.Player.immune, Terraria.ID.SoundID.Item1, Terraria.Audio.SoundEngine.PlaySound(), Terraria.GameContent.DontStarveDarknessDamageDealer.ResetTimer(), Terraria.Player.shimmering, and Terraria.GameContent.DontStarveDarknessDamageDealer.UpdateDarknessState().
Referenced by Terraria.Player.Update().