Terraria Decompiled: Ionic.Zip.ZipSegmentedStream.TruncateBackward
TruncateBackward()
long Ionic.Zip.ZipSegmentedStream.TruncateBackward (uint diskNumber, long offset) inline
Definition at line 245 of file ZipSegmentedStream.cs.
        {
            if (diskNumber >= 99U)
            {
                throw new ArgumentOutOfRangeException("diskNumber");
            }
            if (this.rwMode != ZipSegmentedStream.RwMode.Write)
            {
                this._exceptionPending = true;
                throw new ZipException("bad state.");
            }
            if (diskNumber == this.CurrentSegment)
            {
                long num = this._innerStream.Seek(offset, 0);
                SharedUtilities.Workaround_Ladybug318918(this._innerStream);
                return num;
            }
            if (this._innerStream != null)
            {
                this._innerStream.Close();
                if (File.Exists(this._currentTempName))
                {
                    File.Delete(this._currentTempName);
                }
            }
            for (uint num2 = this.CurrentSegment - 1U; num2 > diskNumber; num2 -= 1U)
            {
                string text = this._NameForSegment(num2);
                if (File.Exists(text))
                {
                    File.Delete(text);
                }
            }
            this.CurrentSegment = diskNumber;
            for (int i = 0; i < 3; i++)
            {
                try
                {
                    this._currentTempName = SharedUtilities.InternalGetTempFileName();
                    File.Move(this.CurrentName, this._currentTempName);
                    break;
                }
                catch (IOException)
                {
                    if (i == 2)
                    {
                        throw;
                    }
                }
            }
            this._innerStream = new FileStream(this._currentTempName, 3);
            long num3 = this._innerStream.Seek(offset, 0);
            SharedUtilities.Workaround_Ladybug318918(this._innerStream);
            return num3;
        }
References Ionic.Zip.ZipSegmentedStream._currentTempName, Ionic.Zip.ZipSegmentedStream._innerStream, Ionic.Zip.ZipSegmentedStream._NameForSegment(), System.IO.Stream.Close(), Ionic.Zip.ZipSegmentedStream.CurrentName, Ionic.Zip.ZipSegmentedStream.CurrentSegment, System.IO.File.Delete(), System.IO.File.Exists(), Ionic.Zip.SharedUtilities.InternalGetTempFileName(), System.IO.File.Move(), Ionic.Zip.ZipSegmentedStream.rwMode, System.IO.Stream.Seek(), System.text, System.U, and Ionic.Zip.SharedUtilities.Workaround_Ladybug318918().
Referenced by Ionic.Zip.ZipEntry.Write().