Terraria Decompiled: Ionic.Zip.ZipSegmentedStream._SetReadStream
_SetReadStream()
void Ionic.Zip.ZipSegmentedStream._SetReadStream () inline private
Definition at line 148 of file ZipSegmentedStream.cs.
        {
            if (this._innerStream != null)
            {
                this._innerStream.Close();
            }
            if (this.CurrentSegment + 1U == this._maxDiskNumber)
            {
                this._currentName = this._baseName;
            }
            this._innerStream = File.OpenRead(this.CurrentName);
        }
References Ionic.Zip.ZipSegmentedStream._baseName, Ionic.Zip.ZipSegmentedStream._innerStream, Ionic.Zip.ZipSegmentedStream._maxDiskNumber, System.IO.Stream.Close(), Ionic.Zip.ZipSegmentedStream.CurrentName, Ionic.Zip.ZipSegmentedStream.CurrentSegment, System.IO.File.OpenRead(), and System.U.
Referenced by Ionic.Zip.ZipSegmentedStream.ForReading(), and Ionic.Zip.ZipSegmentedStream.Read().