Terraria Decompiled: Ionic.Zip.ZipSegmentedStream.ForUpdate
ForUpdate()
static Stream Ionic.Zip.ZipSegmentedStream.ForUpdate (string name, uint diskNumber) inline static
Definition at line 49 of file ZipSegmentedStream.cs.
        {
            if (diskNumber >= 99U)
            {
                throw new ArgumentOutOfRangeException("diskNumber");
            }
            string text = string.Format("{0}.z{1:D2}", Path.Combine(Path.GetDirectoryName(name), Path.GetFileNameWithoutExtension(name)), diskNumber + 1U);
            return File.Open(text, 3, 3, 0);
        }
References System.IO.Path.Combine(), System.IO.Path.GetDirectoryName(), System.IO.Path.GetFileNameWithoutExtension(), System.name, System.IO.File.Open(), System.text, and System.U.
Referenced by Ionic.Zip.ZipEntry.PostProcessOutput().