Terraria Decompiled: Ionic.Zip.ZipSegmentedStream._NameForSegment
_NameForSegment()
string Ionic.Zip.ZipSegmentedStream._NameForSegment (uint diskNumber) inline private
Definition at line 115 of file ZipSegmentedStream.cs.
        {
            if (diskNumber >= 99U)
            {
                this._exceptionPending = true;
                throw new OverflowException("The number of zip segments would exceed 99.");
            }
            return string.Format("{0}.z{1:D2}", Path.Combine(Path.GetDirectoryName(this._baseName), Path.GetFileNameWithoutExtension(this._baseName)), diskNumber + 1U);
        }
References System.IO.Path.Combine(), System.IO.Path.GetDirectoryName(), System.IO.Path.GetFileNameWithoutExtension(), and System.U.
Referenced by Ionic.Zip.ZipSegmentedStream.TruncateBackward().