Terraria Decompiled: Terraria.GameContent.Drawing.TileDrawing.DrawTile_LiquidBehindTile
DrawTile_LiquidBehindTile()
void Terraria.GameContent.Drawing.TileDrawing.DrawTile_LiquidBehindTile (bool solidLayer, int waterStyleOverride, Vector2 screenPosition, Vector2 screenOffset, int tileX, int tileY, Tile tileCache) inline private
Definition at line 4243 of file TileDrawing.cs.
        {
            Tile tile = Main.tile[tileX + 1, tileY];
            Tile tile2 = Main.tile[tileX - 1, tileY];
            Tile tile3 = Main.tile[tileX, tileY - 1];
            Tile tile4 = Main.tile[tileX, tileY + 1];
            if (tile == null)
            {
                tile = new Tile();
                Main.tile[tileX + 1, tileY] = tile;
            }
            if (tile2 == null)
            {
                tile2 = new Tile();
                Main.tile[tileX - 1, tileY] = tile2;
            }
            if (tile3 == null)
            {
                tile3 = new Tile();
                Main.tile[tileX, tileY - 1] = tile3;
            }
            if (tile4 == null)
            {
                tile4 = new Tile();
                Main.tile[tileX, tileY + 1] = tile4;
            }
            if (tile.type == 379)
            {
                tile = new Tile();
            }
            if (tile2.type == 379)
            {
                tile2 = new Tile();
            }
            if (tile3.type == 379)
            {
                tile3 = new Tile();
            }
            if (tile4.type == 379)
            {
                tile4 = new Tile();
            }
            if (DebugOptions.hideWater)
            {
                return;
            }
            if (!tileCache.active())
            {
                return;
            }
            if (tileCache.inActive() || this._tileSolidTop[(int)tileCache.type])
            {
                return;
            }
            if (tileCache.halfBrick() && (tile2.liquid > 160 || tile.liquid > 160) && Main.instance.waterfallManager.CheckForWaterfall(tileX, tileY))
            {
                return;
            }
            if (TileID.Sets.BlocksWaterDrawingBehindSelf[(int)tileCache.type] && tileCache.slope() == 0)
            {
                return;
            }
            int num = 0;
            bool flag = false;
            bool flag2 = false;
            bool flag3 = false;
            bool flag4 = false;
            bool flag5 = false;
            int num2 = 0;
            bool flag6 = false;
            int num3 = (int)tileCache.slope();
            int num4 = tileCache.blockType();
            if (tileCache.type == 379 && tileCache.liquid > 0)
            {
                return;
            }
            if (tileCache.type == 546 && tileCache.liquid > 0)
            {
                flag5 = true;
                flag4 = true;
                flag = true;
                flag2 = true;
                switch (tileCache.liquidType())
                {
                case 0:
                    flag6 = true;
                    break;
                case 1:
                    num2 = 1;
                    break;
                case 2:
                    num2 = 11;
                    break;
                case 3:
                    num2 = 14;
                    break;
                }
                num = (int)tileCache.liquid;
            }
            else
            {
                if (tileCache.liquid > 0 && num4 != 0 && (num4 != 1 || tileCache.liquid > 160))
                {
                    flag5 = true;
                    switch (tileCache.liquidType())
                    {
                    case 0:
                        flag6 = true;
                        break;
                    case 1:
                        num2 = 1;
                        break;
                    case 2:
                        num2 = 11;
                        break;
                    case 3:
                        num2 = 14;
                        break;
                    }
                    if ((int)tileCache.liquid > num)
                    {
                        num = (int)tileCache.liquid;
                    }
                }
                if (tile2.liquid > 0 && num3 != 1 && num3 != 3)
                {
                    flag = true;
                    switch (tile2.liquidType())
                    {
                    case 0:
                        flag6 = true;
                        break;
                    case 1:
                        num2 = 1;
                        break;
                    case 2:
                        num2 = 11;
                        break;
                    case 3:
                        num2 = 14;
                        break;
                    }
                    if ((int)tile2.liquid > num)
                    {
                        num = (int)tile2.liquid;
                    }
                }
                if (tile.liquid > 0 && num3 != 2 && num3 != 4)
                {
                    flag2 = true;
                    switch (tile.liquidType())
                    {
                    case 0:
                        flag6 = true;
                        break;
                    case 1:
                        num2 = 1;
                        break;
                    case 2:
                        num2 = 11;
                        break;
                    case 3:
                        num2 = 14;
                        break;
                    }
                    if ((int)tile.liquid > num)
                    {
                        num = (int)tile.liquid;
                    }
                }
                if (tile3.liquid > 0 && num3 != 3 && num3 != 4)
                {
                    flag3 = true;
                    switch (tile3.liquidType())
                    {
                    case 0:
                        flag6 = true;
                        break;
                    case 1:
                        num2 = 1;
                        break;
                    case 2:
                        num2 = 11;
                        break;
                    case 3:
                        num2 = 14;
                        break;
                    }
                }
                if (tile4.liquid > 0 && num3 != 1 && num3 != 2)
                {
                    if (tile4.liquid > 240)
                    {
                        flag4 = true;
                    }
                    switch (tile4.liquidType())
                    {
                    case 0:
                        flag6 = true;
                        break;
                    case 1:
                        num2 = 1;
                        break;
                    case 2:
                        num2 = 11;
                        break;
                    case 3:
                        num2 = 14;
                        break;
                    }
                }
            }
            if (!flag3 && !flag4 && !flag && !flag2 && !flag5)
            {
                return;
            }
            if (waterStyleOverride != -1)
            {
                Main.waterStyle = waterStyleOverride;
            }
            if (num2 == 0)
            {
                num2 = Main.waterStyle;
            }
            VertexColors vertexColors;
            Lighting.GetCornerColors(tileX, tileY, out vertexColors, 1f);
            Vector2 vector = new Vector2((float)(tileX * 16), (float)(tileY * 16));
            Rectangle rectangle = new Rectangle(0, 4, 16, 16);
            if (flag4 && (flag || flag2))
            {
                flag = true;
                flag2 = true;
            }
            if (tileCache.active() && (Main.tileSolidTop[(int)tileCache.type] || !Main.tileSolid[(int)tileCache.type]))
            {
                return;
            }
            if ((!flag3 || (!flag && !flag2)) && (!flag4 || !flag3))
            {
                if (flag3)
                {
                    rectangle = new Rectangle(0, 4, 16, 4);
                    if (tileCache.halfBrick() || tileCache.slope() != 0)
                    {
                        rectangle = new Rectangle(0, 4, 16, 12);
                    }
                }
                else if (flag4 && !flag && !flag2)
                {
                    vector = new Vector2((float)(tileX * 16), (float)(tileY * 16 + 12));
                    rectangle = new Rectangle(0, 4, 16, 4);
                }
                else
                {
                    int num5 = (int)((float)(256 - num) / 32f);
                    int num6 = 4;
                    if (tile3.liquid == 0 && (num4 != 0 || !WorldGen.SolidTile(tileX, tileY - 1, false)))
                    {
                        num6 = 0;
                    }
                    int num7 = num5 * 2;
                    if (tileCache.slope() != 0)
                    {
                        vector = new Vector2((float)(tileX * 16), (float)(tileY * 16 + num7));
                        rectangle = new Rectangle(0, num7, 16, 16 - num7);
                    }
                    else if ((flag && flag2) || tileCache.halfBrick())
                    {
                        vector = new Vector2((float)(tileX * 16), (float)(tileY * 16 + num7));
                        rectangle = new Rectangle(0, num6, 16, 16 - num7);
                    }
                    else if (flag)
                    {
                        vector = new Vector2((float)(tileX * 16), (float)(tileY * 16 + num7));
                        rectangle = new Rectangle(0, num6, 4, 16 - num7);
                    }
                    else
                    {
                        vector = new Vector2((float)(tileX * 16 + 12), (float)(tileY * 16 + num7));
                        rectangle = new Rectangle(0, num6, 4, 16 - num7);
                    }
                }
            }
            Vector2 vector2 = vector - screenPosition + screenOffset;
            float num8 = 0.5f;
            if (num2 != 1)
            {
                if (num2 == 11)
                {
                    num8 = Math.Max(num8 * 1.7f, 1f);
                }
            }
            else
            {
                num8 = Main.player[Main.myPlayer].lavaOpacity;
            }
            if ((num2 != 1 || Main.player[Main.myPlayer].lavaOpacity >= 1f) && ((double)tileY <= Main.worldSurface || num8 > 1f))
            {
                num8 = 1f;
                if (tileCache.wall == 21)
                {
                    num8 = 0.9f;
                }
                else if (tileCache.wall > 0)
                {
                    num8 = 0.6f;
                }
            }
            if (tileCache.halfBrick() && tile3.liquid > 0 && tileCache.wall > 0)
            {
                num8 = 0f;
            }
            if (num3 == 4 && tile2.liquid == 0 && !WorldGen.SolidTile(tileX - 1, tileY, false))
            {
                num8 = 0f;
            }
            if (num3 == 3 && tile.liquid == 0 && !WorldGen.SolidTile(tileX + 1, tileY, false))
            {
                num8 = 0f;
            }
            vertexColors.BottomLeftColor *= num8;
            vertexColors.BottomRightColor *= num8;
            vertexColors.TopLeftColor *= num8;
            vertexColors.TopRightColor *= num8;
            if (tileCache.halfBrick() && tile3.liquid > 0 && (double)tileY > Main.worldSurface)
            {
                vertexColors.TopLeftColor *= 0f;
                vertexColors.TopRightColor *= 0f;
            }
            bool flag7 = false;
            if (flag6)
            {
                for (int i = 0; i < 15; i++)
                {
                    if (Main.IsLiquidStyleWater(i) && Main.liquidAlpha[i] > 0f && i != num2)
                    {
                        this.DrawPartialLiquid(!solidLayer, tileCache, ref vector2, ref rectangle, i, ref vertexColors);
                        flag7 = true;
                        break;
                    }
                }
            }
            VertexColors vertexColors2 = vertexColors;
            float num9 = (flag7 ? Main.liquidAlpha[num2] : 1f);
            vertexColors2.BottomLeftColor *= num9;
            vertexColors2.BottomRightColor *= num9;
            vertexColors2.TopLeftColor *= num9;
            vertexColors2.TopRightColor *= num9;
            if (num2 == 14)
            {
                LiquidRenderer.SetShimmerVertexColors(ref vertexColors2, solidLayer ? 0.75f : 1f, tileX, tileY);
            }
            this.DrawPartialLiquid(!solidLayer, tileCache, ref vector2, ref rectangle, num2, ref vertexColors2);
        }
References Terraria.Tile.active(), Terraria.ID.TileID.Sets.BlocksWaterDrawingBehindSelf, Terraria.Tile.blockType(), Terraria.WaterfallManager.CheckForWaterfall(), Terraria.GameContent.Drawing.TileDrawing.DrawPartialLiquid(), Terraria.Lighting.GetCornerColors(), Terraria.Tile.halfBrick(), Terraria.Testing.DebugOptions.hideWater, Terraria.Tile.inActive(), Terraria.Main.instance, int, Terraria.Main.IsLiquidStyleWater(), Terraria.Player.lavaOpacity, Terraria.Tile.liquid, Terraria.Main.liquidAlpha, Terraria.Tile.liquidType(), System.Math.Max(), Terraria.Main.myPlayer, Terraria.Main.player, Terraria.GameContent.Liquid.LiquidRenderer.SetShimmerVertexColors(), Terraria.Tile.slope(), Terraria.WorldGen.SolidTile(), Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Tile.type, Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Tile.wall, Terraria.Main.waterfallManager, Terraria.Main.waterStyle, and Terraria.Main.worldSurface.
Referenced by Terraria.GameContent.Drawing.TileDrawing.Draw(), and Terraria.GameContent.Drawing.TileDrawing.DrawLiquidBehindTiles().