Terraria Decompiled: Terraria.GameContent.Drawing.TileDrawing.DrawEntities_HatRacks
DrawEntities_HatRacks()
void Terraria.GameContent.Drawing.TileDrawing.DrawEntities_HatRacks () inline private
Definition at line 9508 of file TileDrawing.cs.
        {
            Main.spriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend, Main.DefaultSamplerState, DepthStencilState.None, Main.Rasterizer, null, Main.Transform);
            foreach (KeyValuePair<Point, int> keyValuePair in this._hatRackTileEntityPositions)
            {
                TEHatRack tehatRack;
                if (keyValuePair.Value != -1 && TileEntity.TryGetAt<TEHatRack>(keyValuePair.Key.X, keyValuePair.Key.Y, out tehatRack))
                {
                    tehatRack.Draw(keyValuePair.Key.X, keyValuePair.Key.Y);
                }
            }
            Main.spriteBatch.End();
        }
References Terraria.GameContent.Drawing.TileDrawing._hatRackTileEntityPositions, Microsoft.Xna.Framework.Graphics.BlendState.AlphaBlend, Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(), Terraria.Main.DefaultSamplerState, Terraria.GameContent.Tile_Entities.TEHatRack.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.End(), System.Collections.Generic.KeyValuePair< TKey, TValue >.Key, Microsoft.Xna.Framework.Graphics.DepthStencilState.None, Terraria.Main.Rasterizer, Terraria.Main.spriteBatch, Terraria.Main.Transform, and System.Collections.Generic.KeyValuePair< TKey, TValue >.Value.
Referenced by Terraria.GameContent.Drawing.TileDrawing.PostDrawTiles().