Terraria Decompiled: Terraria.GameContent.Drawing.TileDrawing.GetTreeBiome
GetTreeBiome()
static int Terraria.GameContent.Drawing.TileDrawing.GetTreeBiome (int tileX, int tileY, int tileFrameX, int tileFrameY) inline static private
Definition at line 2098 of file TileDrawing.cs.
        {
            int num = tileX;
            int num2 = tileY;
            int type = (int)Main.tile[num, num2].type;
            if (tileFrameX == 66 && tileFrameY <= 45)
            {
                num++;
            }
            if (tileFrameX == 88 && tileFrameY >= 66 && tileFrameY <= 110)
            {
                num--;
            }
            if (tileFrameY >= 198)
            {
                if (tileFrameX == 66)
                {
                    num--;
                }
                else if (tileFrameX == 44)
                {
                    num++;
                }
            }
            else if (tileFrameY >= 132)
            {
                if (tileFrameX == 22)
                {
                    num--;
                }
                else if (tileFrameX == 44)
                {
                    num++;
                }
            }
            while (Main.tile[num, num2].active() && (int)Main.tile[num, num2].type == type)
            {
                num2++;
            }
            return TileDrawing.GetTreeVariant(num, num2);
        }
References Terraria.Tile.active(), Terraria.GameContent.Drawing.TileDrawing.GetTreeVariant(), int, Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.GameContent.Drawing.TileDrawing.GetTileDrawData(), Terraria.GameContent.Drawing.TileDrawing.GetTileDrawTexture(), and Terraria.GameContent.Drawing.TileDrawing.PrepareForAreaDrawing().