Terraria Decompiled: Terraria.GameContent.Drawing.TileDrawing.ClearCachedTileDraws
ClearCachedTileDraws()
void Terraria.GameContent.Drawing.TileDrawing.ClearCachedTileDraws (bool solidLayer) inline
Definition at line 7838 of file TileDrawing.cs.
        {
            if (solidLayer)
            {
                this._displayDollTileEntityPositions.Clear();
                this._hatRackTileEntityPositions.Clear();
                return;
            }
            this.ClearSpecialBlockCounts();
        }
References Terraria.GameContent.Drawing.TileDrawing._displayDollTileEntityPositions, Terraria.GameContent.Drawing.TileDrawing._hatRackTileEntityPositions, System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), and Terraria.GameContent.Drawing.TileDrawing.ClearSpecialBlockCounts().
Referenced by Terraria.GameContent.Drawing.TileDrawing.Draw().