Terraria Decompiled: Terraria.GameContent.Drawing.TileDrawing.DrawVoidLenses
DrawVoidLenses()
void Terraria.GameContent.Drawing.TileDrawing.DrawVoidLenses () inline private
Definition at line 10242 of file TileDrawing.cs.
        {
            int num = 6;
            int num2 = this._specialsCount[num];
            this._voidLensData.Clear();
            for (int i = 0; i < num2; i++)
            {
                Point point = this._specialPositions[num][i];
                VoidLensHelper voidLensHelper = new VoidLensHelper(point.ToWorldCoordinates(8f, 8f), 1f);
                if (!Main.gamePaused)
                {
                    voidLensHelper.Update();
                }
                int num3 = 0;
                bool flag;
                if (Main.InSmartCursorHighlightArea(point.X, point.Y, out flag))
                {
                    num3 = 1;
                    if (flag)
                    {
                        num3 = 2;
                    }
                }
                voidLensHelper.DrawToDrawData(this._voidLensData, num3);
            }
            foreach (DrawData drawData in this._voidLensData)
            {
                drawData.Draw(Main.spriteBatch);
            }
        }
References Terraria.GameContent.Drawing.TileDrawing._specialPositions, Terraria.GameContent.Drawing.TileDrawing._specialsCount, Terraria.GameContent.Drawing.TileDrawing._voidLensData, System.Collections.Generic.List< T >.Clear(), Terraria.DataStructures.DrawData.Draw(), Terraria.GameContent.VoidLensHelper.DrawToDrawData(), Terraria.Main.gamePaused, Terraria.Main.InSmartCursorHighlightArea(), Terraria.Main.spriteBatch, Terraria.GameContent.VoidLensHelper.Update(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.Drawing.TileDrawing.PostDrawTiles().