Terraria Decompiled: Terraria.GameContent.Drawing.TileDrawing.EmitLivingTreeLeaf_Below
EmitLivingTreeLeaf_Below()
void Terraria.GameContent.Drawing.TileDrawing.EmitLivingTreeLeaf_Below (int x, int y, int leafGoreType) inline private
Definition at line 8990 of file TileDrawing.cs.
        {
            Tile tile = Main.tile[x, y + 1];
            if (WorldGen.SolidTile(tile) || tile.liquid > 0)
            {
                return;
            }
            float windForVisuals = Main.WindForVisuals;
            if (windForVisuals < -0.2f && (WorldGen.SolidTile(Main.tile[x - 1, y + 1]) || WorldGen.SolidTile(Main.tile[x - 2, y + 1])))
            {
                return;
            }
            if (windForVisuals > 0.2f && (WorldGen.SolidTile(Main.tile[x + 1, y + 1]) || WorldGen.SolidTile(Main.tile[x + 2, y + 1])))
            {
                return;
            }
            Gore.NewGorePerfect(new Vector2((float)(x * 16), (float)(y * 16 + 16)), Vector2.Zero, leafGoreType, 1f).Frame.CurrentColumn = Main.tile[x, y].color();
        }
References Terraria.Tile.color(), Terraria.DataStructures.SpriteFrame.CurrentColumn, Terraria.Gore.Frame, Terraria.Tile.liquid, Terraria.Gore.NewGorePerfect(), Terraria.WorldGen.SolidTile(), Terraria.Main.tile, Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Main.WindForVisuals, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.Drawing.TileDrawing.EmitLivingTreeLeaf().