Terraria Decompiled: Terraria.GameContent.Drawing.TileDrawing.LookupTileDrawTexture
LookupTileDrawTexture()
Texture2D Terraria.GameContent.Drawing.TileDrawing.LookupTileDrawTexture (TilePaintSystemV2::TileVariationkey key) inline private
Definition at line 1829 of file TileDrawing.cs.
        {
            Main.instance.LoadTiles(key.TileType);
            if (key.PaintColor != 0 || key.TileStyle != 0)
            {
                Texture2D texture2D = this._paintSystem.TryGetTileAndRequestIfNotReady(key.TileType, key.TileStyle, key.PaintColor);
                if (texture2D != null)
                {
                    return texture2D;
                }
            }
            return TextureAssets.Tile[key.TileType].Value;
        }
References Terraria.GameContent.Drawing.TileDrawing._paintSystem, Terraria.Main.instance, System.key, Terraria.Main.LoadTiles(), Terraria.GameContent.TextureAssets.Tile, Terraria.GameContent.TilePaintSystemV2.TryGetTileAndRequestIfNotReady(), and ReLogic.Content.Asset< T >.Value.
Referenced by Terraria.GameContent.Drawing.TileDrawing.GetTileDrawTexture().