Terraria Decompiled: Terraria.GameContent.Drawing.TileDrawing.DrawEntities_DisplayDolls
DrawEntities_DisplayDolls()
void Terraria.GameContent.Drawing.TileDrawing.DrawEntities_DisplayDolls () inline private
Definition at line 9493 of file TileDrawing.cs.
        {
            Main.spriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend, Main.DefaultSamplerState, DepthStencilState.None, Main.Rasterizer, null, Main.Transform);
            foreach (KeyValuePair<Point, int> keyValuePair in this._displayDollTileEntityPositions)
            {
                TEDisplayDoll tedisplayDoll;
                if (keyValuePair.Value != -1 && TileEntity.TryGetAt<TEDisplayDoll>(keyValuePair.Key.X, keyValuePair.Key.Y, out tedisplayDoll))
                {
                    tedisplayDoll.Draw(keyValuePair.Key.X, keyValuePair.Key.Y);
                }
            }
            Main.spriteBatch.End();
        }
References Terraria.GameContent.Drawing.TileDrawing._displayDollTileEntityPositions, Microsoft.Xna.Framework.Graphics.BlendState.AlphaBlend, Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(), Terraria.Main.DefaultSamplerState, Terraria.GameContent.Tile_Entities.TEDisplayDoll.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.End(), System.Collections.Generic.KeyValuePair< TKey, TValue >.Key, Microsoft.Xna.Framework.Graphics.DepthStencilState.None, Terraria.Main.Rasterizer, Terraria.Main.spriteBatch, Terraria.Main.Transform, and System.Collections.Generic.KeyValuePair< TKey, TValue >.Value.
Referenced by Terraria.GameContent.Drawing.TileDrawing.PostDrawTiles().