Terraria Decompiled: Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileVinesInWind
DrawMultiTileVinesInWind()
void Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileVinesInWind (Vector2 screenPosition, Vector2 offSet, int topLeftX, int topLeftY, int sizeX, int sizeY) inline private
Definition at line 10970 of file TileDrawing.cs.
        {
            float num = this.GetWindCycle(topLeftX, topLeftY, this._sunflowerWindCounter);
            float num2 = num;
            int num3 = 60;
            float num4 = 1.26f;
            float highestWindGridPushComplex = this.GetHighestWindGridPushComplex(topLeftX, topLeftY, sizeX, sizeY, num3, num4, 3, true);
            num += highestWindGridPushComplex;
            Vector2 vector = new Vector2((float)(topLeftX * 16 - (int)screenPosition.X) + (float)sizeX * 16f * 0.5f, (float)(topLeftY * 16 - (int)screenPosition.Y)) + offSet;
            Tile tile = Main.tile[topLeftX, topLeftY];
            int type = (int)tile.type;
            Vector2 vector2 = new Vector2(0f, -2f);
            vector += vector2;
            bool flag;
            if (type == 465 || type - 591 <= 1)
            {
                flag = WorldGen.IsBelowANonHammeredPlatform(topLeftX, topLeftY) && WorldGen.IsBelowANonHammeredPlatform(topLeftX + 1, topLeftY);
            }
            else
            {
                flag = sizeX == 1 && WorldGen.IsBelowANonHammeredPlatform(topLeftX, topLeftY);
            }
            if (flag)
            {
                vector.Y -= 8f;
                vector2.Y -= 8f;
            }
            Texture2D texture2D = null;
            Color transparent = Color.Transparent;
            float? num5 = null;
            float num6 = 1f;
            float num7 = -4f;
            bool flag2 = false;
            bool flag3 = false;
            float num8 = 0.15f;
            if (type <= 444)
            {
                int num9;
                if (type <= 95)
                {
                    if (type != 34)
                    {
                        if (type == 42)
{
                            num5 = new float?((float)1);
                            num7 = 0f;
                            num9 = (int)(tile.frameY / 36);
                            if (num9 <= 55)
{
                                if (num9 == 0)
{
                                    num5 = null;
                                    num7 = -1f;
                                    goto IL_06F9;
                                }
                                switch (num9)
{
                                case 9:
                                    num5 = new float?(0f);
                                    goto IL_06F9;
                                case 10:
                                case 11:
                                case 13:
                                case 15:
                                case 16:
                                case 17:
                                case 18:
                                case 19:
                                case 20:
                                case 21:
                                case 22:
                                case 23:
                                case 24:
                                case 25:
                                case 26:
                                case 27:
                                case 29:
                                case 31:
                                case 36:
                                case 37:
                                    goto IL_06F9;
                                case 12:
                                    num5 = null;
                                    num7 = -1f;
                                    goto IL_06F9;
                                case 14:
                                    num5 = null;
                                    num7 = -1f;
                                    goto IL_06F9;
                                case 28:
                                    num5 = null;
                                    num7 = -1f;
                                    goto IL_06F9;
                                case 30:
                                    num5 = new float?(0f);
                                    goto IL_06F9;
                                case 32:
                                    num5 = new float?(0f);
                                    goto IL_06F9;
                                case 33:
                                    num5 = new float?(0f);
                                    goto IL_06F9;
                                case 34:
                                    num5 = null;
                                    num7 = -1f;
                                    goto IL_06F9;
                                case 35:
                                    num5 = new float?(0f);
                                    goto IL_06F9;
                                case 38:
                                    num5 = null;
                                    num7 = -1f;
                                    goto IL_06F9;
                                case 39:
                                    num5 = null;
                                    num7 = -1f;
                                    flag2 = true;
                                    goto IL_06F9;
                                case 40:
                                case 41:
                                case 42:
                                case 43:
                                    num5 = new float?(0f);
                                    num5 = null;
                                    num7 = -1f;
                                    flag2 = true;
                                    goto IL_06F9;
                                default:
                                    if (num9 - 54 > 1)
{
                                        goto IL_06F9;
                                    }
                                    break;
                                }
                            }
                            else if (num9 <= 65)
{
                                if (num9 != 60 && num9 != 65)
{
                                    goto IL_06F9;
                                }
                            }
                            else if (num9 != 67 && num9 != 70)
{
                                goto IL_06F9;
                            }
                            num5 = new float?(0f);
                            goto IL_06F9;
                        }
                        if (type != 95)
{
                            goto IL_06F9;
                        }
                        goto IL_067D;
                    }
                }
                else if (type != 126)
                {
                    if (type - 270 > 1 && type != 444)
                    {
                        goto IL_06F9;
                    }
                    goto IL_067D;
                }
                num5 = new float?((float)1);
                num7 = 0f;
                num9 = (int)(tile.frameY / 54 + tile.frameX / 108 * 37);
                if (num9 > 44)
                {
                    if (num9 - 54 > 1 && num9 != 60)
                    {
                        switch (num9)
{
                        case 65:
                        case 67:
                        case 68:
                        case 70:
                            break;
                        case 66:
                        case 69:
                            goto IL_06F9;
                        default:
                            goto IL_06F9;
                        }
                    }
                    num5 = new float?(0f);
                    goto IL_06F9;
                }
                switch (num9)
                {
                case 9:
                    num5 = null;
                    num7 = -1f;
                    flag2 = true;
                    num8 *= 0.3f;
                    goto IL_06F9;
                case 10:
                    goto IL_06F9;
                case 11:
                    num8 *= 0.5f;
                    goto IL_06F9;
                case 12:
                    num5 = null;
                    num7 = -1f;
                    goto IL_06F9;
                default:
                    switch (num9)
                    {
                    case 18:
                        num5 = null;
                        num7 = -1f;
                        goto IL_06F9;
                    case 19:
                    case 20:
                    case 22:
                    case 24:
                    case 26:
                    case 27:
                    case 28:
                    case 29:
                    case 30:
                    case 31:
                    case 34:
                    case 38:
                        goto IL_06F9;
                    case 21:
                        num5 = null;
                        num7 = -1f;
                        goto IL_06F9;
                    case 23:
                        num5 = new float?(0f);
                        goto IL_06F9;
                    case 25:
                        num5 = null;
                        num7 = -1f;
                        flag2 = true;
                        goto IL_06F9;
                    case 32:
                        num8 *= 0.5f;
                        goto IL_06F9;
                    case 33:
                        num8 *= 0.5f;
                        goto IL_06F9;
                    case 35:
                        num5 = new float?(0f);
                        goto IL_06F9;
                    case 36:
                        num5 = null;
                        num7 = -1f;
                        flag2 = true;
                        goto IL_06F9;
                    case 37:
                        num5 = null;
                        num7 = -1f;
                        flag2 = true;
                        num8 *= 0.5f;
                        goto IL_06F9;
                    case 39:
                        num5 = null;
                        num7 = -1f;
                        flag2 = true;
                        goto IL_06F9;
                    case 40:
                    case 41:
                    case 42:
                    case 43:
                        num5 = null;
                        num7 = -2f;
                        flag2 = true;
                        num8 *= 0.5f;
                        goto IL_06F9;
                    case 44:
                        num5 = null;
                        num7 = -3f;
                        goto IL_06F9;
                    default:
                        goto IL_06F9;
                    }
                    break;
                }
            }
            else if (type <= 581)
            {
                if (type != 454 && type != 572 && type != 581)
                {
                    goto IL_06F9;
                }
            }
            else if (type <= 592)
            {
                if (type == 591)
                {
                    num6 = 0.5f;
                    num7 = -2f;
                    goto IL_06F9;
                }
                if (type != 592)
                {
                    goto IL_06F9;
                }
                num6 = 0.5f;
                num7 = -2f;
                texture2D = TextureAssets.GlowMask[294].Value;
                transparent = new Color(255, 255, 255, 0);
                goto IL_06F9;
            }
            else if (type != 660)
            {
                if (type != 698)
                {
                    goto IL_06F9;
                }
                num6 = 0.5f;
                num7 = -1f;
                offSet.X -= 10f;
                flag3 = true;
                goto IL_06F9;
            }
            IL_067D:
            num5 = new float?((float)1);
            num7 = 0f;
            IL_06F9:
            if (flag2)
            {
                vector += new Vector2(0f, 16f);
            }
            num8 *= -1f;
            bool flag4 = this.InAPlaceWithWind(topLeftX, topLeftY, sizeX, sizeY);
            if (flag3 || !flag4)
            {
                num -= num2;
            }
            ulong num10 = 0UL;
            for (int i = topLeftX; i < topLeftX + sizeX; i++)
            {
                for (int j = topLeftY; j < topLeftY + sizeY; j++)
                {
                    Tile tile2 = Main.tile[i, j];
                    ushort type2 = tile2.type;
                    if ((int)type2 == type && this.IsVisible(tile2))
                    {
                        Math.Abs(((float)(i - topLeftX) + 0.5f) / (float)sizeX - 0.5f);
                        short frameX = tile2.frameX;
                        short frameY = tile2.frameY;
                        float num11 = (float)(j - topLeftY + 1) / (float)sizeY;
                        if (num11 == 0f)
{
                            num11 = 0.1f;
                        }
                        if (num5 != null)
{
                            num11 = num5.Value;
                        }
                        if (flag2 && j == topLeftY)
{
                            num11 = 0f;
                        }
                        int num12;
                        int num13;
                        int num14;
                        int num15;
                        int num16;
                        int num17;
                        SpriteEffects spriteEffects;
                        Texture2D texture2D2;
                        Rectangle rectangle;
                        Color color;
                        this.GetTileDrawData(i, j, tile2, type2, ref frameX, ref frameY, out num12, out num13, out num14, out num15, out num16, out num17, out spriteEffects, out texture2D2, out rectangle, out color);
                        bool flag5 = this._rand.Next(4) == 0;
                        Color color2 = Lighting.GetColor(i, j);
                        this.DrawAnimatedTile_AdjustForVisionChangers(i, j, tile2, type2, frameX, frameY, ref color2, flag5);
                        color2 = this.DrawTiles_GetLightOverride(j, i, tile2, type2, frameX, frameY, color2);
                        if (this._isActiveAndNotPaused && flag5)
{
                            this.DrawTiles_EmitParticles(j, i, tile2, type2, frameX, frameY, color2);
                        }
                        Vector2 vector3 = new Vector2((float)(i * 16 - (int)screenPosition.X), (float)(j * 16 - (int)screenPosition.Y + num14)) + offSet;
                        vector3 += vector2;
                        Vector2 vector4 = new Vector2(num * num6, Math.Abs(num) * num7 * num11);
                        Vector2 vector5 = vector - vector3;
                        Texture2D tileDrawTexture = this.GetTileDrawTexture(tile2, i, j);
                        if (tileDrawTexture != null)
{
                            Vector2 vector6 = vector + new Vector2(0f, vector4.Y);
                            Rectangle rectangle2 = new Rectangle((int)frameX + num16, (int)frameY + num17, num12, num13 - num15);
                            float num18 = num * num8 * num11;
                            if (type2 == 660 && j == topLeftY + sizeY - 1)
{
                                Texture2D value = TextureAssets.Extra[260].Value;
                                float num19 = ((float)((i + j) % 200) * 0.11f + (float)Main.timeForVisualEffects / 360f) % 1f;
                                Color white = Color.White;
                                Main.spriteBatch.Draw(value, vector6, new Rectangle?(rectangle2), white, num18, vector5, 1f, spriteEffects, 0f);
                            }
                            Main.spriteBatch.Draw(tileDrawTexture, vector6, new Rectangle?(rectangle2), color2, num18, vector5, 1f, spriteEffects, 0f);
                            if (type2 == 660 && j == topLeftY + sizeY - 1)
{
                                Texture2D value2 = TextureAssets.Extra[260].Value;
                                Color color3 = Main.hslToRgb(((float)((i + j) % 200) * 0.11f + (float)Main.timeForVisualEffects / 360f) % 1f, 1f, 0.8f, byte.MaxValue);
                                color3.A = 127;
                                Rectangle rectangle3 = rectangle2;
                                Vector2 vector7 = vector6;
                                Vector2 vector8 = vector5;
                                Main.spriteBatch.Draw(value2, vector7, new Rectangle?(rectangle3), color3, num18, vector8, 1f, spriteEffects, 0f);
                            }
                            TEDeadCellsDisplayJar tedeadCellsDisplayJar;
                            if (type2 == 698 && TileEntity.TryGetAt<TEDeadCellsDisplayJar>(topLeftX, topLeftY, out tedeadCellsDisplayJar))
{
                                Item item = tedeadCellsDisplayJar.item;
                                short num20 = frameX / 38;
                                int num21 = 0;
                                int num22;
                                switch (num20)
{
                                default:
                                    num22 = 22;
                                    num21 = -1;
                                    break;
                                case 1:
                                    num22 = 18;
                                    break;
                                case 2:
                                    num22 = 20;
                                    break;
                                }
                                Rectangle rectangle4 = rectangle2;
                                rectangle4.Y += 46;
                                Rectangle rectangle5 = rectangle4;
                                rectangle5.Y += 46;
                                int num23 = 1;
                                Color color4 = new Color(150, 150, 255);
                                if (!item.IsAir)
{
                                    num23 = item.rare;
                                    if (item.expert)
{
                                        num23 = -12;
                                    }
                                    if (num23 == -12)
{
                                        color4 = new Color((int)((byte)Main.DiscoR), (int)((byte)Main.DiscoG), (int)((byte)Main.DiscoB));
                                    }
                                    else if (num23 == -13)
{
                                        color4 = new Color(255, (int)((byte)(Main.masterColor * 200f)), 0);
                                    }
                                    else
{
                                        color4 = item.GetPopupRarityColor();
                                    }
                                }
                                Vector3 vector9 = Main.rgbToHsl(color4);
                                float x = vector9.X;
                                Color color5 = color4;
                                color4 *= 0.25f;
                                if (num23 != -1)
{
                                    color5 = Main.hslToRgb(x, MathHelper.Clamp(vector9.Y + 0.5f, 0f, 1f), MathHelper.Clamp(vector9.Z, 0f, 1f), 127);
                                }
                                Main.spriteBatch.Draw(tileDrawTexture, vector6, new Rectangle?(rectangle5), color4, num18, vector5, 1f, spriteEffects, 0f);
                                if (!item.IsAir)
{
                                    Vector2 vector10 = new Vector2(-2f, (float)(24 + num21));
                                    int num9 = (int)(frameX / 38);
                                    if (num9 != 1)
{
                                        if (num9 == 2)
{
                                            vector10.Y += 6f;
                                        }
                                    }
                                    else
{
                                        vector10.Y += 4f;
                                    }
                                    Vector2 vector11 = vector6 + vector10.RotatedBy((double)num18, default(Vector2)) + new Vector2(2f, 0f);
                                    color2 = Color.Lerp(color2, Color.White, 0.5f);
                                    ItemSlot.DrawItemIcon(item, 40, Main.spriteBatch, vector11, item.scale, (float)num22, color2, 1f, false);
                                }
                                color4.A = byte.MaxValue;
                                Main.spriteBatch.Draw(tileDrawTexture, vector6, new Rectangle?(rectangle4), color5, num18, vector5, 1f, spriteEffects, 0f);
                            }
                            if (texture2D != null)
{
                                Main.spriteBatch.Draw(texture2D, vector6, new Rectangle?(rectangle2), transparent, num18, vector5, 1f, spriteEffects, 0f);
                            }
                            TileDrawing.TileFlameData tileFlameData = this.GetTileFlameData(i, j, (int)type2, (int)frameY);
                            if (num10 == 0UL)
{
                                num10 = tileFlameData.flameSeed;
                            }
                            tileFlameData.flameSeed = num10;
                            for (int k = 0; k < tileFlameData.flameCount; k++)
{
                                float num24 = (float)Utils.RandomInt(ref tileFlameData.flameSeed, tileFlameData.flameRangeXMin, tileFlameData.flameRangeXMax) * tileFlameData.flameRangeMultX;
                                float num25 = (float)Utils.RandomInt(ref tileFlameData.flameSeed, tileFlameData.flameRangeYMin, tileFlameData.flameRangeYMax) * tileFlameData.flameRangeMultY;
                                Main.spriteBatch.Draw(tileFlameData.flameTexture, vector6 + new Vector2(num24, num25), new Rectangle?(rectangle2), tileFlameData.flameColor, num18, vector5, 1f, spriteEffects, 0f);
                            }
                        }
                    }
                }
            }
        }
References Terraria.GameContent.Drawing.TileDrawing._isActiveAndNotPaused, Terraria.GameContent.Drawing.TileDrawing._rand, Terraria.GameContent.Drawing.TileDrawing._sunflowerWindCounter, System.Math.Abs(), Microsoft.Xna.Framework.MathHelper.Clamp(), Microsoft.Xna.Framework.Graphics.Color, Terraria.Main.DiscoB, Terraria.Main.DiscoG, Terraria.Main.DiscoR, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.GameContent.Drawing.TileDrawing.DrawAnimatedTile_AdjustForVisionChangers(), Terraria.UI.ItemSlot.DrawItemIcon(), Terraria.GameContent.Drawing.TileDrawing.DrawTiles_EmitParticles(), Terraria.GameContent.Drawing.TileDrawing.DrawTiles_GetLightOverride(), Terraria.GameContent.TextureAssets.Extra, Terraria.GameContent.Drawing.TileDrawing.TileFlameData.flameColor, Terraria.GameContent.Drawing.TileDrawing.TileFlameData.flameCount, Terraria.GameContent.Drawing.TileDrawing.TileFlameData.flameRangeMultX, Terraria.GameContent.Drawing.TileDrawing.TileFlameData.flameRangeMultY, Terraria.GameContent.Drawing.TileDrawing.TileFlameData.flameRangeXMax, Terraria.GameContent.Drawing.TileDrawing.TileFlameData.flameRangeXMin, Terraria.GameContent.Drawing.TileDrawing.TileFlameData.flameRangeYMax, Terraria.GameContent.Drawing.TileDrawing.TileFlameData.flameRangeYMin, Terraria.GameContent.Drawing.TileDrawing.TileFlameData.flameSeed, Terraria.GameContent.Drawing.TileDrawing.TileFlameData.flameTexture, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Lighting.GetColor(), Terraria.GameContent.Drawing.TileDrawing.GetHighestWindGridPushComplex(), Terraria.GameContent.Drawing.TileDrawing.GetTileDrawData(), Terraria.GameContent.Drawing.TileDrawing.GetTileDrawTexture(), Terraria.GameContent.Drawing.TileDrawing.GetTileFlameData(), Terraria.GameContent.Drawing.TileDrawing.GetWindCycle(), Terraria.GameContent.TextureAssets.GlowMask, Terraria.Main.hslToRgb(), Terraria.GameContent.Drawing.TileDrawing.InAPlaceWithWind(), int, Terraria.WorldGen.IsBelowANonHammeredPlatform(), Terraria.GameContent.Drawing.TileDrawing.IsVisible(), System.item, Terraria.GameContent.Tile_Entities.TEDeadCellsDisplayJar.item, Microsoft.Xna.Framework.Color.Lerp(), Terraria.Main.masterColor, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Utils.RandomInt(), Terraria.Main.rgbToHsl(), Terraria.Main.spriteBatch, Terraria.Main.tile, Terraria.Main.timeForVisualEffects, Microsoft.Xna.Framework.Color.Transparent, Terraria.Tile.type, System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector3.X, Microsoft.Xna.Framework.Vector2.Y, Microsoft.Xna.Framework.Vector3.Y, and Microsoft.Xna.Framework.Vector3.Z.
Referenced by Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileVines().