Terraria Decompiled: Terraria.GameContent.Drawing.TileDrawing.GetTileDrawData
GetTileDrawData()
void Terraria.GameContent.Drawing.TileDrawing.GetTileDrawData (int x, int y, Tile tileCache, ushort typeCache, ref short tileFrameX, ref short tileFrameY, out int tileWidth, out int tileHeight, out int tileTop, out int halfBrickHeight, out int addFrX, out int addFrY, out SpriteEffects tileSpriteEffect, out Texture2D glowTexture, out Rectangle glowSourceRect, out Color glowColor) inline private
Definition at line 4973 of file TileDrawing.cs.
        {
            tileTop = 0;
            tileWidth = 16;
            tileHeight = 16;
            halfBrickHeight = 0;
            addFrY = Main.tileFrame[(int)typeCache] * 38;
            addFrX = 0;
            tileSpriteEffect = SpriteEffects.None;
            glowTexture = null;
            glowSourceRect = Rectangle.Empty;
            glowColor = Color.Transparent;
            Color color = Lighting.GetColor(x, y);
            switch (typeCache)
            {
            case 3:
            case 24:
            case 61:
            case 71:
            case 110:
            case 201:
            case 637:
                break;
            case 4:
                tileWidth = 20;
                tileHeight = 20;
                if (WorldGen.SolidTile(x, y - 1, false))
                {
                    tileTop = 4;
                    goto IL_25BA;
                }
                goto IL_25BA;
            case 5:
            {
                tileWidth = 20;
                tileHeight = 20;
                int treeBiome = TileDrawing.GetTreeBiome(x, y, (int)tileFrameX, (int)tileFrameY);
                tileFrameX += (short)(176 * (treeBiome + 1));
                goto IL_25BA;
            }
            case 6:
            case 7:
            case 8:
            case 9:
            case 10:
            case 11:
            case 13:
            case 19:
            case 22:
            case 23:
            case 25:
            case 29:
            case 30:
            case 34:
            case 35:
            case 37:
            case 38:
            case 39:
            case 40:
            case 41:
            case 42:
            case 43:
            case 44:
            case 45:
            case 46:
            case 47:
            case 48:
            case 50:
            case 51:
            case 53:
            case 54:
            case 55:
            case 56:
            case 57:
            case 58:
            case 59:
            case 60:
            case 63:
            case 64:
            case 65:
            case 66:
            case 67:
            case 68:
            case 70:
            case 75:
            case 76:
            case 86:
            case 87:
            case 88:
            case 91:
            case 92:
            case 93:
            case 94:
            case 95:
            case 97:
            case 98:
            case 99:
            case 101:
            case 103:
            case 104:
            case 107:
            case 108:
            case 109:
            case 111:
            case 112:
            case 114:
            case 116:
            case 117:
            case 118:
            case 119:
            case 120:
            case 121:
            case 122:
            case 123:
            case 125:
            case 126:
            case 127:
            case 128:
            case 130:
            case 131:
            case 140:
            case 141:
            case 144:
            case 145:
            case 146:
            case 147:
            case 148:
            case 149:
            case 150:
            case 151:
            case 152:
            case 153:
            case 154:
            case 155:
            case 156:
            case 157:
            case 158:
            case 159:
            case 160:
            case 161:
            case 162:
            case 163:
            case 164:
            case 165:
            case 166:
            case 167:
            case 168:
            case 169:
            case 170:
            case 171:
            case 175:
            case 176:
            case 177:
            case 179:
            case 180:
            case 181:
            case 182:
            case 183:
            case 188:
            case 189:
            case 190:
            case 191:
            case 192:
            case 193:
            case 194:
            case 195:
            case 196:
            case 197:
            case 198:
            case 199:
            case 200:
            case 202:
            case 203:
            case 204:
            case 206:
            case 208:
            case 209:
            case 211:
            case 212:
            case 213:
            case 214:
            case 215:
            case 216:
            case 221:
            case 222:
            case 223:
            case 224:
            case 225:
            case 226:
            case 229:
            case 230:
            case 232:
            case 234:
            case 236:
            case 237:
            case 239:
            case 240:
            case 241:
            case 242:
            case 245:
            case 246:
            case 248:
            case 249:
            case 250:
            case 251:
            case 252:
            case 253:
            case 255:
            case 256:
            case 257:
            case 258:
            case 259:
            case 260:
            case 261:
            case 262:
            case 263:
            case 264:
            case 265:
            case 266:
            case 267:
            case 268:
            case 269:
            case 273:
            case 274:
            case 284:
            case 287:
            case 311:
            case 312:
            case 313:
            case 314:
            case 315:
            case 319:
            case 320:
            case 321:
            case 322:
            case 325:
            case 334:
            case 335:
            case 337:
            case 338:
            case 346:
            case 347:
            case 348:
            case 350:
            case 353:
            case 356:
            case 357:
            case 365:
            case 366:
            case 367:
            case 368:
            case 369:
            case 370:
            case 371:
            case 373:
            case 374:
            case 375:
            case 380:
            case 381:
            case 383:
            case 384:
            case 385:
            case 386:
            case 387:
            case 395:
            case 396:
            case 397:
            case 398:
            case 399:
            case 400:
            case 401:
            case 402:
            case 403:
            case 404:
            case 407:
            case 408:
            case 409:
            case 415:
            case 416:
            case 417:
            case 418:
            case 419:
            case 420:
            case 423:
            case 424:
            case 425:
            case 426:
            case 427:
            case 429:
            case 430:
            case 431:
            case 432:
            case 433:
            case 434:
            case 435:
            case 436:
            case 437:
            case 438:
            case 439:
            case 440:
            case 444:
            case 445:
            case 446:
            case 447:
            case 448:
            case 449:
            case 450:
            case 451:
            case 460:
            case 461:
            case 465:
            case 471:
            case 472:
            case 473:
            case 474:
            case 477:
            case 478:
            case 479:
            case 481:
            case 482:
            case 483:
            case 484:
            case 486:
            case 492:
            case 495:
            case 496:
            case 498:
            case 500:
            case 501:
            case 502:
            case 503:
            case 504:
            case 510:
            case 511:
            case 512:
            case 513:
            case 514:
            case 515:
            case 516:
            case 517:
            case 531:
            case 534:
            case 535:
            case 536:
            case 537:
            case 539:
            case 540:
            case 545:
            case 546:
            case 549:
            case 557:
            case 562:
            case 563:
            case 566:
            case 573:
            case 591:
            case 618:
            case 625:
            case 626:
            case 627:
            case 628:
            case 630:
            case 631:
            case 633:
            case 635:
            case 641:
            case 655:
            case 659:
            case 661:
            case 662:
            case 663:
                goto IL_25BA;
            case 12:
            case 31:
            case 96:
            case 639:
            case 665:
                goto IL_1AAA;
            case 14:
            case 21:
            case 411:
            case 467:
            case 469:
                if (tileFrameY == 18)
                {
                    tileHeight = 18;
                    goto IL_25BA;
                }
                goto IL_25BA;
            case 15:
            case 497:
                if (tileFrameY % 40 == 18)
                {
                    tileHeight = 18;
                    goto IL_25BA;
                }
                goto IL_25BA;
            case 16:
            case 17:
            case 26:
            case 32:
            case 69:
            case 72:
            case 77:
            case 124:
            case 137:
            case 138:
            case 352:
            case 462:
            case 487:
            case 488:
            case 574:
            case 575:
            case 576:
            case 577:
            case 578:
            case 664:
                goto IL_1187;
            case 18:
            {
                int num = (int)(tileFrameX / 2016);
                addFrX -= 2016 * num;
                addFrY += 20 * num;
                goto IL_25BA;
            }
            case 20:
            case 590:
            case 595:
                tileHeight = 18;
                if (x % 2 == 0)
                {
                    tileSpriteEffect = SpriteEffects.FlipHorizontally;
                    goto IL_25BA;
                }
                goto IL_25BA;
            case 27:
                if (tileFrameY % 74 == 54)
                {
                    tileHeight = 18;
                    goto IL_25BA;
                }
                goto IL_25BA;
            case 28:
            case 105:
            case 470:
            case 475:
            case 506:
            case 547:
            case 548:
            case 552:
            case 560:
            case 597:
            case 613:
            case 621:
            case 622:
            case 623:
            case 653:
                goto IL_17A9;
            case 33:
            case 49:
            case 174:
            case 372:
            case 646:
                tileHeight = 20;
                tileTop = -4;
                goto IL_25BA;
            case 36:
                tileTop = 2;
                goto IL_25BA;
            case 52:
            case 62:
            case 115:
            case 205:
            case 382:
            case 528:
            case 636:
            case 638:
                tileTop = -2;
                if (x % 2 == 0)
                {
                    tileSpriteEffect = SpriteEffects.FlipHorizontally;
                    goto IL_25BA;
                }
                goto IL_25BA;
            case 73:
            case 74:
            case 113:
                tileTop = -12;
                tileHeight = 32;
                if (x % 2 == 0)
                {
                    tileSpriteEffect = SpriteEffects.FlipHorizontally;
                    goto IL_25BA;
                }
                goto IL_25BA;
            case 78:
            case 85:
            case 133:
            case 134:
            case 173:
            case 210:
            case 233:
            case 254:
            case 283:
            case 378:
            case 457:
            case 466:
            case 520:
            case 651:
            case 652:
                tileTop = 2;
                goto IL_25BA;
            case 79:
            {
                tileHeight = 18;
                int num2 = (int)(tileFrameY / 2016);
                addFrY -= 2016 * num2;
                addFrX += 144 * num2;
                goto IL_25BA;
            }
            case 80:
            case 142:
            case 143:
                tileTop = 2;
                goto IL_25BA;
            case 81:
                tileTop -= 8;
                tileHeight = 26;
                tileWidth = 24;
                if (x % 2 == 0)
                {
                    tileSpriteEffect = SpriteEffects.FlipHorizontally;
                    goto IL_25BA;
                }
                goto IL_25BA;
            case 82:
            case 83:
            case 84:
                tileHeight = 20;
                tileTop = -2;
                if (x % 2 == 0)
                {
                    tileSpriteEffect = SpriteEffects.FlipHorizontally;
                    goto IL_25BA;
                }
                goto IL_25BA;
            case 89:
                tileTop = 2;
                goto IL_25BA;
            case 90:
            {
                int num3 = (int)(tileFrameY / 2016);
                addFrY -= 2016 * num3;
                addFrX += 144 * num3;
                goto IL_25BA;
            }
            case 100:
            {
                tileTop = 2;
                int num4 = (int)(tileFrameY / 2016);
                addFrY -= 2016 * num4;
                addFrX += 72 * num4;
                goto IL_25BA;
            }
            case 102:
                tileTop = 2;
                goto IL_25BA;
            case 106:
                addFrY = Main.tileFrame[(int)typeCache] * 54;
                goto IL_25BA;
            case 129:
                addFrY = 0;
                if (tileFrameX >= 324)
                {
                    int num5 = (int)((tileFrameX - 324) / 18);
                    int num6 = (num5 + Main.tileFrame[(int)typeCache]) % 6 - num5;
                    addFrX = num6 * 18;
                    goto IL_25BA;
                }
                goto IL_25BA;
            case 132:
            case 135:
                tileTop = 2;
                tileHeight = 18;
                goto IL_25BA;
            case 136:
                if (tileFrameX == 0)
                {
                    tileTop = 2;
                    goto IL_25BA;
                }
                goto IL_25BA;
            case 139:
            {
                tileTop = 2;
                int num7 = (int)(tileFrameY / 2016);
                addFrY -= 2016 * num7;
                addFrX += 72 * num7;
                goto IL_25BA;
            }
            case 172:
            case 376:
                if (tileFrameY % 38 == 18)
                {
                    tileHeight = 18;
                    goto IL_25BA;
                }
                goto IL_25BA;
            case 178:
                if (tileFrameY <= 36)
                {
                    tileTop = 2;
                    goto IL_25BA;
                }
                goto IL_25BA;
            case 184:
                tileWidth = 20;
                if (tileFrameY <= 36)
                {
                    tileTop = 2;
                    goto IL_25BA;
                }
                if (tileFrameY <= 108)
                {
                    tileTop = -2;
                    goto IL_25BA;
                }
                goto IL_25BA;
            case 185:
            case 186:
            case 187:
                tileTop = 2;
                if (typeCache == 185)
                {
                    if (tileFrameY == 18 && tileFrameX >= 576 && tileFrameX <= 882)
                    {
                        Main.tileShine2[185] = true;
                    }
                    else
                    {
                        Main.tileShine2[185] = false;
                    }
                    if (tileFrameY == 18)
                    {
                        int num8 = (int)(tileFrameX / 1908);
                        addFrX -= 1908 * num8;
                        addFrY += 18 * num8;
                        goto IL_25BA;
                    }
                    goto IL_25BA;
                }
                else if (typeCache == 186)
                {
                    if (tileFrameX >= 864 && tileFrameX <= 1170)
                    {
                        Main.tileShine2[186] = true;
                        goto IL_25BA;
                    }
                    Main.tileShine2[186] = false;
                    goto IL_25BA;
                }
                else
                {
                    if (typeCache == 187)
                    {
                        int num9 = (int)(tileFrameX / 1890);
                        addFrX -= 1890 * num9;
                        addFrY += 36 * num9;
                        goto IL_25BA;
                    }
                    goto IL_25BA;
                }
                break;
            case 207:
                tileTop = 2;
                if (tileFrameY >= 72)
                {
                    addFrY = Main.tileFrame[(int)typeCache];
                    int num10 = x;
                    if (tileFrameX % 36 != 0)
                    {
                        num10--;
                    }
                    addFrY += num10 % 6;
                    if (addFrY >= 6)
                    {
                        addFrY -= 6;
                    }
                    addFrY *= 72;
                    goto IL_25BA;
                }
                addFrY = 0;
                goto IL_25BA;
            case 217:
            case 218:
            case 564:
                addFrY = Main.tileFrame[(int)typeCache] * 36;
                tileTop = 2;
                goto IL_25BA;
            case 219:
            case 220:
            case 642:
                addFrY = Main.tileFrame[(int)typeCache] * 54;
                tileTop = 2;
                goto IL_25BA;
            case 227:
                tileWidth = 32;
                tileHeight = 38;
                if (tileFrameX == 238)
                {
                    tileTop -= 6;
                }
                else
                {
                    tileTop -= 20;
                }
                if (tileFrameX == 204)
                {
                    bool flag;
                    bool flag2;
                    bool flag3;
                    WorldGen.GetCactusType(x, y, (int)tileFrameX, (int)tileFrameY, out flag, out flag2, out flag3);
                    if (flag2)
                    {
                        tileFrameX += 238;
                    }
                    if (flag)
                    {
                        tileFrameX += 204;
                    }
                    if (flag3)
                    {
                        tileFrameX += 272;
                    }
                }
                if (x % 2 == 0)
                {
                    tileSpriteEffect = SpriteEffects.FlipHorizontally;
                    goto IL_25BA;
                }
                goto IL_25BA;
            case 228:
            case 231:
            case 243:
            case 247:
                tileTop = 2;
                addFrY = Main.tileFrame[(int)typeCache] * 54;
                goto IL_25BA;
            case 235:
                addFrY = Main.tileFrame[(int)typeCache] * 18;
                goto IL_25BA;
            case 238:
                tileTop = 2;
                addFrY = Main.tileFrame[(int)typeCache] * 36;
                goto IL_25BA;
            case 244:
                tileTop = 2;
                if (tileFrameX < 54)
                {
                    addFrY = Main.tileFrame[(int)typeCache] * 36;
                    goto IL_25BA;
                }
                addFrY = 0;
                goto IL_25BA;
            case 270:
            case 271:
            case 581:
            {
                int i = Main.tileFrame[(int)typeCache] + x % 6;
                if (x % 2 == 0)
                {
                    i += 3;
                }
                if (x % 3 == 0)
                {
                    i += 3;
                }
                if (x % 4 == 0)
                {
                    i += 3;
                }
                while (i > 5)
                {
                    i -= 6;
                }
                addFrX = i * 18;
                addFrY = 0;
                if (x % 2 == 0)
                {
                    tileSpriteEffect = SpriteEffects.FlipHorizontally;
                    goto IL_25BA;
                }
                goto IL_25BA;
            }
            case 272:
                addFrY = 0;
                goto IL_25BA;
            case 275:
            case 276:
            case 277:
            case 278:
            case 279:
            case 280:
            case 281:
            case 296:
            case 297:
            case 309:
            case 358:
            case 359:
            case 413:
            case 414:
            case 542:
            case 550:
            case 551:
            case 553:
            case 554:
            case 558:
            case 559:
            case 599:
            case 600:
            case 601:
            case 602:
            case 603:
            case 604:
            case 605:
            case 606:
            case 607:
            case 608:
            case 609:
            case 610:
            case 611:
            case 612:
            case 632:
            case 640:
            case 643:
            case 644:
            case 645:
                goto IL_1DA6;
            case 282:
            case 505:
            case 543:
            {
                tileTop = 2;
                Main.critterCage = true;
                int waterAnimalCageFrame = this.GetWaterAnimalCageFrame(x, y, (int)tileFrameX, (int)tileFrameY);
                addFrY = Main.fishBowlFrame[waterAnimalCageFrame] * 36;
                goto IL_25BA;
            }
            case 285:
            case 286:
            case 298:
            case 299:
            case 310:
            case 339:
            case 361:
            case 362:
            case 363:
            case 364:
            case 391:
            case 392:
            case 393:
            case 394:
            case 532:
            case 533:
            case 538:
            case 544:
            case 555:
            case 556:
            case 582:
            case 619:
            case 629:
            {
                tileTop = 2;
                Main.critterCage = true;
                int smallAnimalCageFrame = this.GetSmallAnimalCageFrame(x, y, (int)tileFrameX, (int)tileFrameY);
                if (typeCache <= 391)
                {
                    if (typeCache > 299)
                    {
                        if (typeCache <= 339)
{
                            if (typeCache == 310)
{
                                goto IL_2211;
                            }
                            if (typeCache != 339)
{
                                goto IL_25BA;
                            }
                        }
                        else
{
                            switch (typeCache)
{
                            case 361:
                                goto IL_21D8;
                            case 362:
                                break;
                            case 363:
                                goto IL_21FE;
                            case 364:
                                goto IL_2211;
                            default:
                                if (typeCache != 391)
{
                                    goto IL_25BA;
                                }
                                goto IL_2211;
                            }
                        }
                        addFrY = Main.grasshopperCageFrame[smallAnimalCageFrame] * 36;
                        goto IL_25BA;
                    }
                    if (typeCache <= 286)
                    {
                        if (typeCache == 285)
{
                            addFrY = Main.snailCageFrame[smallAnimalCageFrame] * 36;
                            goto IL_25BA;
                        }
                        if (typeCache != 286)
{
                            goto IL_25BA;
                        }
                        goto IL_21C5;
                    }
                    else if (typeCache != 298)
                    {
                        if (typeCache != 299)
{
                            goto IL_25BA;
                        }
                        goto IL_21FE;
                    }
                    IL_21D8:
                    addFrY = Main.frogCageFrame[smallAnimalCageFrame] * 36;
                    goto IL_25BA;
                    IL_21FE:
                    addFrY = Main.mouseCageFrame[smallAnimalCageFrame] * 36;
                    goto IL_25BA;
                }
                if (typeCache <= 538)
                {
                    if (typeCache <= 532)
                    {
                        if (typeCache - 392 <= 2)
{
                            addFrY = Main.slugCageFrame[(int)(typeCache - 392), smallAnimalCageFrame] * 36;
                            goto IL_25BA;
                        }
                        if (typeCache != 532)
{
                            goto IL_25BA;
                        }
                        addFrY = Main.maggotCageFrame[smallAnimalCageFrame] * 36;
                        goto IL_25BA;
                    }
                    else
                    {
                        if (typeCache == 533)
{
                            addFrY = Main.ratCageFrame[smallAnimalCageFrame] * 36;
                            goto IL_25BA;
                        }
                        if (typeCache != 538)
{
                            goto IL_25BA;
                        }
                    }
                }
                else if (typeCache <= 556)
                {
                    if (typeCache != 544)
                    {
                        if (typeCache - 555 > 1)
{
                            goto IL_25BA;
                        }
                        addFrY = Main.waterStriderCageFrame[smallAnimalCageFrame] * 36;
                        goto IL_25BA;
                    }
                }
                else
                {
                    if (typeCache == 582)
                    {
                        goto IL_21C5;
                    }
                    if (typeCache == 619)
                    {
                        goto IL_2211;
                    }
                    if (typeCache != 629)
                    {
                        goto IL_25BA;
                    }
                }
                addFrY = Main.ladybugCageFrame[smallAnimalCageFrame] * 36;
                goto IL_25BA;
                IL_21C5:
                addFrY = Main.snail2CageFrame[smallAnimalCageFrame] * 36;
                goto IL_25BA;
                IL_2211:
                addFrY = Main.wormCageFrame[smallAnimalCageFrame] * 36;
                goto IL_25BA;
            }
            case 288:
            case 289:
            case 290:
            case 291:
            case 292:
            case 293:
            case 294:
            case 295:
            case 360:
            case 580:
            case 620:
            {
                tileTop = 2;
                Main.critterCage = true;
                int waterAnimalCageFrame2 = this.GetWaterAnimalCageFrame(x, y, (int)tileFrameX, (int)tileFrameY);
                int num11 = (int)(typeCache - 288);
                if (typeCache == 360 || typeCache == 580 || typeCache == 620)
                {
                    num11 = 8;
                }
                addFrY = Main.butterflyCageFrame[num11, waterAnimalCageFrame2] * 36;
                goto IL_25BA;
            }
            case 300:
            case 301:
            case 302:
            case 303:
            case 304:
            case 305:
            case 306:
            case 307:
            case 308:
            case 354:
            case 355:
            case 499:
                addFrY = Main.tileFrame[(int)typeCache] * 54;
                tileTop = 2;
                goto IL_25BA;
            case 316:
            case 317:
            case 318:
            {
                tileTop = 2;
                Main.critterCage = true;
                int smallAnimalCageFrame2 = this.GetSmallAnimalCageFrame(x, y, (int)tileFrameX, (int)tileFrameY);
                int num12 = (int)(typeCache - 316);
                addFrY = Main.jellyfishCageFrame[num12, smallAnimalCageFrame2] * 36;
                goto IL_25BA;
            }
            case 323:
            {
                tileWidth = 20;
                tileHeight = 20;
                int palmTreeBiome = this.GetPalmTreeBiome(x, y);
                tileFrameY = (short)(22 * palmTreeBiome);
                goto IL_25BA;
            }
            case 324:
                tileWidth = 20;
                tileHeight = 20;
                tileTop = -2;
                if (x % 2 == 0)
                {
                    tileSpriteEffect = SpriteEffects.FlipHorizontally;
                    goto IL_25BA;
                }
                goto IL_25BA;
            case 326:
            case 327:
            case 328:
            case 329:
            case 345:
            case 351:
            case 421:
            case 422:
            case 458:
            case 459:
                goto IL_2550;
            case 330:
            case 331:
            case 332:
            case 333:
                tileTop += 2;
                goto IL_25BA;
            case 336:
            case 340:
            case 341:
            case 342:
            case 343:
            case 344:
                addFrY = Main.tileFrame[(int)typeCache] * 90;
                tileTop = 2;
                goto IL_25BA;
            case 349:
            {
                tileTop = 2;
                int num13 = (int)(tileFrameX % 36);
                int num14 = (int)(tileFrameY % 54);
                int num15;
                if (Animation.GetTemporaryFrame(x - num13 / 18, y - num14 / 18, out num15))
                {
                    tileFrameX = (short)(36 * num15 + num13);
                    goto IL_25BA;
                }
                goto IL_25BA;
            }
            case 377:
                addFrY = Main.tileFrame[(int)typeCache] * 38;
                tileTop = 2;
                goto IL_25BA;
            case 379:
                addFrY = Main.tileFrame[(int)typeCache] * 90;
                goto IL_25BA;
            case 388:
            case 389:
            {
                int num16 = 94;
                tileTop = -2;
                if ((int)tileFrameY == num16 - 20 || (int)tileFrameY == num16 * 2 - 20 || tileFrameY == 0 || (int)tileFrameY == num16)
                {
                    tileHeight = 18;
                }
                if (tileFrameY != 0 && (int)tileFrameY != num16)
                {
                    tileTop = 0;
                    goto IL_25BA;
                }
                goto IL_25BA;
            }
            case 390:
                addFrY = Main.tileFrame[(int)typeCache] * 36;
                goto IL_25BA;
            case 405:
            {
                tileHeight = 16;
                if (tileFrameY > 0)
                {
                    tileHeight = 18;
                }
                int num17 = Main.tileFrame[(int)typeCache];
                if (tileFrameX >= 54)
                {
                    num17 = 0;
                }
                addFrY = num17 * 38;
                goto IL_25BA;
            }
            case 406:
            {
                tileHeight = 16;
                if (tileFrameY % 54 >= 36)
                {
                    tileHeight = 18;
                }
                int num18 = Main.tileFrame[(int)typeCache];
                if (tileFrameY >= 108)
                {
                    num18 = (int)(6 - tileFrameY / 54);
                }
                else if (tileFrameY >= 54)
                {
                    num18 = Main.tileFrame[(int)typeCache] - 1;
                }
                addFrY = num18 * 56;
                addFrY += (int)(tileFrameY / 54 * 2);
                goto IL_25BA;
            }
            case 410:
                if (tileFrameY == 36)
                {
                    tileHeight = 18;
                }
                if (tileFrameY >= 56)
                {
                    addFrY = Main.tileFrame[(int)typeCache];
                    addFrY *= 56;
                    goto IL_25BA;
                }
                addFrY = 0;
                goto IL_25BA;
            case 412:
                addFrY = 0;
                tileTop = 2;
                goto IL_25BA;
            case 428:
                tileTop += 4;
                if (PressurePlateHelper.PressurePlatesPressed.ContainsKey(new Point(x, y)))
                {
                    addFrX += 18;
                    goto IL_25BA;
                }
                goto IL_25BA;
            case 441:
            case 468:
            {
                if (tileFrameY == 18)
                {
                    tileHeight = 18;
                }
                int num19 = (int)(tileFrameX % 36);
                int num20 = (int)(tileFrameY % 38);
                int num21;
                if (Animation.GetTemporaryFrame(x - num19 / 18, y - num20 / 18, out num21))
                {
                    tileFrameY = (short)(38 * num21 + num20);
                    goto IL_25BA;
                }
                goto IL_25BA;
            }
            case 442:
                tileWidth = 20;
                tileHeight = 20;
                switch (tileFrameX / 22)
                {
                case 1:
                    tileTop = -4;
                    goto IL_25BA;
                case 2:
                    tileTop = -2;
                    tileWidth = 24;
                    goto IL_25BA;
                case 3:
                    tileTop = -2;
                    goto IL_25BA;
                default:
                    goto IL_25BA;
                }
                break;
            case 443:
                if (tileFrameX / 36 >= 2)
                {
                    tileTop = -2;
                    goto IL_25BA;
                }
                tileTop = 2;
                goto IL_25BA;
            case 452:
            {
                int num22 = Main.tileFrame[(int)typeCache];
                if (tileFrameX >= 54)
                {
                    num22 = 0;
                }
                addFrY = num22 * 54;
                goto IL_25BA;
            }
            case 453:
            {
                int num23 = Main.tileFrameCounter[(int)typeCache];
                num23 /= 20;
                int num24 = y - (int)(tileFrameY / 18);
                num23 += num24 + x;
                num23 %= 3;
                addFrY = num23 * 54;
                goto IL_25BA;
            }
            case 454:
                addFrY = Main.tileFrame[(int)typeCache] * 54;
                goto IL_25BA;
            case 455:
            {
                addFrY = 0;
                tileTop = 2;
                int num25 = 1 + Main.tileFrame[(int)typeCache];
                if (!BirthdayParty.PartyIsUp)
                {
                    num25 = 0;
                }
                addFrY = num25 * 54;
                goto IL_25BA;
            }
            case 456:
            {
                int num26 = Main.tileFrameCounter[(int)typeCache];
                num26 /= 20;
                int num27 = y - (int)(tileFrameY / 18);
                int num28 = x - (int)(tileFrameX / 18);
                num26 += num27 + num28;
                num26 %= 4;
                addFrY = num26 * 54;
                goto IL_25BA;
            }
            case 463:
            case 464:
                addFrY = Main.tileFrame[(int)typeCache] * 72;
                tileTop = 2;
                goto IL_25BA;
            case 476:
                tileWidth = 20;
                tileHeight = 18;
                goto IL_25BA;
            case 480:
            case 509:
            case 657:
                goto IL_2477;
            case 485:
            {
                tileTop = 2;
                int num29 = Main.tileFrameCounter[(int)typeCache];
                num29 /= 5;
                int num30 = y - (int)(tileFrameY / 18);
                int num31 = x - (int)(tileFrameX / 18);
                num29 += num30 + num31;
                num29 %= 4;
                addFrY = num29 * 36;
                goto IL_25BA;
            }
            case 489:
            {
                tileTop = 2;
                int num32 = y - (int)(tileFrameY / 18);
                int num33 = x - (int)(tileFrameX / 18);
                if (this.InAPlaceWithWind(num33, num32, 2, 3))
                {
                    int num34 = Main.tileFrameCounter[(int)typeCache];
                    num34 /= 5;
                    num34 += num32 + num33;
                    num34 %= 16;
                    addFrY = num34 * 54;
                    goto IL_25BA;
                }
                goto IL_25BA;
            }
            case 490:
            {
                tileTop = 2;
                int num35 = y - (int)(tileFrameY / 18);
                int num36 = x - (int)(tileFrameX / 18);
                bool flag4 = this.InAPlaceWithWind(num36, num35, 2, 2);
                int num37 = (flag4 ? Main.tileFrame[(int)typeCache] : 0);
                int num38 = 0;
                if (flag4)
                {
                    if (Math.Abs(Main.WindForVisuals) > 0.5f)
                    {
                        switch (Main.weatherVaneBobframe)
{
                        case 0:
                            num38 = 0;
                            break;
                        case 1:
                            num38 = 1;
                            break;
                        case 2:
                            num38 = 2;
                            break;
                        case 3:
                            num38 = 1;
                            break;
                        case 4:
                            num38 = 0;
                            break;
                        case 5:
                            num38 = -1;
                            break;
                        case 6:
                            num38 = -2;
                            break;
                        case 7:
                            num38 = -1;
                            break;
                        }
                    }
                    else
                    {
                        switch (Main.weatherVaneBobframe)
{
                        case 0:
                            num38 = 0;
                            break;
                        case 1:
                            num38 = 1;
                            break;
                        case 2:
                            num38 = 0;
                            break;
                        case 3:
                            num38 = -1;
                            break;
                        case 4:
                            num38 = 0;
                            break;
                        case 5:
                            num38 = 1;
                            break;
                        case 6:
                            num38 = 0;
                            break;
                        case 7:
                            num38 = -1;
                            break;
                        }
                    }
                }
                num37 += num38;
                if (num37 < 0)
                {
                    num37 += 12;
                }
                num37 %= 12;
                addFrY = num37 * 36;
                goto IL_25BA;
            }
            case 491:
                tileTop = 2;
                addFrX = 54;
                goto IL_25BA;
            case 493:
                if (tileFrameY == 0)
                {
                    int num39 = Main.tileFrameCounter[(int)typeCache];
                    float num40 = Math.Abs(Main.WindForVisuals);
                    int num41 = y - (int)(tileFrameY / 18);
                    int num42 = x - (int)(tileFrameX / 18);
                    if (!this.InAPlaceWithWind(x, num41, 1, 1))
                    {
                        num40 = 0f;
                    }
                    if (num40 >= 0.1f)
                    {
                        if (num40 < 0.5f)
{
                            num39 /= 20;
                            num39 += num41 + num42;
                            num39 %= 6;
                            if (Main.WindForVisuals < 0f)
{
                                num39 = 6 - num39;
                            }
                            else
{
                                num39++;
                            }
                            addFrY = num39 * 36;
                        }
                        else
{
                            num39 /= 10;
                            num39 += num41 + num42;
                            num39 %= 6;
                            if (Main.WindForVisuals < 0f)
{
                                num39 = 12 - num39;
                            }
                            else
{
                                num39 += 7;
                            }
                            addFrY = num39 * 36;
                        }
                    }
                }
                tileTop = 2;
                goto IL_25BA;
            case 494:
                tileTop = 2;
                goto IL_25BA;
            case 507:
            case 508:
            {
                int num43 = 20;
                int num44 = (Main.tileFrameCounter[(int)typeCache] + x * 11 + y * 27) % (num43 * 8);
                addFrY = 90 * (num44 / num43);
                goto IL_25BA;
            }
            case 518:
            {
                int num45 = (int)(tileCache.liquid / 16);
                num45 -= 3;
                if (WorldGen.SolidTile(x, y - 1, false) && num45 > 8)
                {
                    num45 = 8;
                }
                if (tileCache.liquid == 0)
                {
                    Tile tileSafely = Framing.GetTileSafely(x, y + 1);
                    if (tileSafely.nactive())
                    {
                        int num46 = tileSafely.blockType();
                        if (num46 == 1)
{
                            num45 = -16 + Math.Max(8, (int)(tileSafely.liquid / 16));
                        }
                        else if (num46 == 3 || num46 == 2)
{
                            num45 -= 4;
                        }
                    }
                }
                tileTop -= num45;
                goto IL_25BA;
            }
            case 519:
                tileTop = 2;
                if (x % 2 == 0)
                {
                    tileSpriteEffect = SpriteEffects.FlipHorizontally;
                    goto IL_25BA;
                }
                goto IL_25BA;
            case 521:
            case 522:
            case 523:
            case 524:
            case 525:
            case 526:
            case 527:
            {
                tileTop = 2;
                Main.critterCage = true;
                int waterAnimalCageFrame3 = this.GetWaterAnimalCageFrame(x, y, (int)tileFrameX, (int)tileFrameY);
                int num47 = (int)(typeCache - 521);
                addFrY = Main.dragonflyJarFrame[num47, waterAnimalCageFrame3] * 36;
                goto IL_25BA;
            }
            case 529:
            {
                int num48 = y + 1;
                int num49;
                int num50;
                int num51;
                WorldGen.GetBiomeInfluence(x, x, num48, num48, out num49, out num50, out num51);
                int num52 = num49;
                if (num52 < num50)
                {
                    num52 = num50;
                }
                if (num52 < num51)
                {
                    num52 = num51;
                }
                int num53;
                if (num49 == 0 && num50 == 0 && num51 == 0)
                {
                    if (x < WorldGen.beachDistance || x > Main.maxTilesX - WorldGen.beachDistance)
                    {
                        num53 = 1;
                    }
                    else
                    {
                        num53 = 0;
                    }
                }
                else if (num51 == num52)
                {
                    num53 = 2;
                }
                else if (num50 == num52)
                {
                    num53 = 3;
                }
                else
                {
                    num53 = 4;
                }
                addFrY += 34 * num53 - (int)tileFrameY;
                tileHeight = 32;
                tileTop = -14;
                if (x % 2 == 0)
                {
                    tileSpriteEffect = SpriteEffects.FlipHorizontally;
                    goto IL_25BA;
                }
                goto IL_25BA;
            }
            case 530:
            {
                int num54 = y - (int)(tileFrameY % 36 / 18) + 2;
                int num55 = x - (int)(tileFrameX % 54 / 18);
                int num56;
                int num57;
                int num58;
                WorldGen.GetBiomeInfluence(num55, num55 + 3, num54, num54, out num56, out num57, out num58);
                int num59 = num56;
                if (num59 < num57)
                {
                    num59 = num57;
                }
                if (num59 < num58)
                {
                    num59 = num58;
                }
                int num60;
                if (num56 == 0 && num57 == 0 && num58 == 0)
                {
                    num60 = 0;
                }
                else if (num58 == num59)
                {
                    num60 = 1;
                }
                else if (num57 == num59)
                {
                    num60 = 2;
                }
                else
                {
                    num60 = 3;
                }
                addFrY += 36 * num60;
                tileTop = 2;
                goto IL_25BA;
            }
            case 541:
                addFrY = (this._shouldShowInvisibleBlocks ? 0 : 90);
                goto IL_25BA;
            case 561:
                tileTop -= 2;
                tileHeight = 20;
                addFrY = (int)(tileFrameY / 18 * 4);
                goto IL_25BA;
            case 565:
                tileTop = 2;
                if (tileFrameX < 36)
                {
                    addFrY = Main.tileFrame[(int)typeCache] * 36;
                    goto IL_25BA;
                }
                addFrY = 0;
                goto IL_25BA;
            case 567:
                tileWidth = 26;
                tileHeight = 18;
                if (tileFrameY == 0)
                {
                    tileTop = -2;
                }
                if (x % 2 == 0)
                {
                    tileSpriteEffect = SpriteEffects.FlipHorizontally;
                    goto IL_25BA;
                }
                goto IL_25BA;
            case 568:
            case 569:
            case 570:
            {
                tileTop = 2;
                Main.critterCage = true;
                int waterAnimalCageFrame4 = this.GetWaterAnimalCageFrame(x, y, (int)tileFrameX, (int)tileFrameY);
                addFrY = Main.fairyJarFrame[waterAnimalCageFrame4] * 36;
                goto IL_25BA;
            }
            case 571:
                if (x % 2 == 0)
                {
                    tileSpriteEffect = SpriteEffects.FlipHorizontally;
                }
                tileTop = 2;
                goto IL_25BA;
            case 572:
            {
                int j;
                for (j = Main.tileFrame[(int)typeCache] + x % 4; j > 3; j -= 4)
                {
                }
                addFrX = j * 18;
                addFrY = 0;
                if (x % 2 == 0)
                {
                    tileSpriteEffect = SpriteEffects.FlipHorizontally;
                    goto IL_25BA;
                }
                goto IL_25BA;
            }
            case 579:
            {
                tileWidth = 20;
                tileHeight = 20;
                tileTop -= 2;
                bool flag5 = (float)(x * 16 + 8) > Main.LocalPlayer.Center.X;
                if (tileFrameX > 0)
                {
                    if (flag5)
                    {
                        addFrY = 22;
                        goto IL_25BA;
                    }
                    addFrY = 0;
                    goto IL_25BA;
                }
                else
                {
                    if (flag5)
                    {
                        addFrY = 0;
                        goto IL_25BA;
                    }
                    addFrY = 22;
                    goto IL_25BA;
                }
                break;
            }
            case 583:
            case 584:
            case 585:
            case 586:
            case 587:
            case 588:
            case 589:
            case 596:
            case 616:
            case 634:
                tileWidth = 20;
                tileHeight = 20;
                goto IL_25BA;
            case 592:
                addFrY = Main.tileFrame[(int)typeCache] * 54;
                goto IL_25BA;
            case 593:
            {
                if (tileFrameX >= 18)
                {
                    addFrX = -18;
                }
                tileTop = 2;
                int num61;
                if (Animation.GetTemporaryFrame(x, y, out num61))
                {
                    addFrY = (int)((short)(18 * num61));
                    goto IL_25BA;
                }
                if (tileFrameX < 18)
                {
                    addFrY = Main.tileFrame[(int)typeCache] * 18;
                    goto IL_25BA;
                }
                addFrY = 0;
                goto IL_25BA;
            }
            case 594:
            {
                if (tileFrameX >= 36)
                {
                    addFrX = -36;
                }
                tileTop = 2;
                int num62 = (int)(tileFrameX % 36);
                int num63 = (int)(tileFrameY % 36);
                int num64;
                if (Animation.GetTemporaryFrame(x - num62 / 18, y - num63 / 18, out num64))
                {
                    addFrY = (int)((short)(36 * num64));
                    goto IL_25BA;
                }
                if (tileFrameX < 36)
                {
                    addFrY = Main.tileFrame[(int)typeCache] * 36;
                    goto IL_25BA;
                }
                addFrY = 0;
                goto IL_25BA;
            }
            case 598:
            {
                tileTop = 2;
                Main.critterCage = true;
                int waterAnimalCageFrame5 = this.GetWaterAnimalCageFrame(x, y, (int)tileFrameX, (int)tileFrameY);
                addFrY = Main.lavaFishBowlFrame[waterAnimalCageFrame5] * 36;
                goto IL_25BA;
            }
            case 614:
                addFrX = Main.tileFrame[(int)typeCache] * 54;
                addFrY = 0;
                tileTop = 2;
                goto IL_25BA;
            case 615:
                tileHeight = 18;
                if (x % 2 == 0)
                {
                    tileSpriteEffect = SpriteEffects.FlipHorizontally;
                    goto IL_25BA;
                }
                goto IL_25BA;
            case 617:
                tileTop = 2;
                tileFrameY %= 144;
                tileFrameX %= 54;
                goto IL_25BA;
            case 624:
                goto IL_1459;
            case 647:
                goto IL_164A;
            case 648:
            {
                tileTop = 2;
                int num65 = (int)(tileFrameX / 1890);
                addFrX -= 1890 * num65;
                addFrY += 36 * num65;
                goto IL_25BA;
            }
            case 649:
            {
                tileTop = 2;
                int num66 = (int)(tileFrameX / 1908);
                addFrX -= 1908 * num66;
                addFrY += 18 * num66;
                goto IL_25BA;
            }
            case 650:
                tileTop = 2;
                goto IL_25BA;
            case 654:
                tileTop += 2;
                goto IL_25BA;
            case 656:
                goto IL_147C;
            case 658:
                tileTop = 2;
                switch (tileFrameY / 54)
                {
                default:
                    addFrY = Main.tileFrame[(int)typeCache];
                    addFrY *= 54;
                    goto IL_25BA;
                case 1:
                    addFrY = Main.tileFrame[(int)typeCache];
                    addFrY *= 54;
                    addFrY += 486;
                    goto IL_25BA;
                case 2:
                    addFrY = Main.tileFrame[(int)typeCache];
                    addFrY *= 54;
                    addFrY += 972;
                    goto IL_25BA;
                }
                break;
            case 660:
            {
                int k = Main.tileFrame[(int)typeCache] + x % 5;
                if (x % 2 == 0)
                {
                    k += 3;
                }
                if (x % 3 == 0)
                {
                    k += 3;
                }
                if (x % 4 == 0)
                {
                    k += 3;
                }
                while (k > 4)
                {
                    k -= 5;
                }
                addFrX = k * 18;
                addFrY = 0;
                if (x % 2 == 0)
                {
                    tileSpriteEffect = SpriteEffects.FlipHorizontally;
                    goto IL_25BA;
                }
                goto IL_25BA;
            }
            default:
            {
                switch (typeCache)
                {
                case 695:
                case 704:
                case 712:
                case 713:
                case 714:
                case 715:
                case 716:
                    goto IL_1187;
                case 696:
                    goto IL_1AAA;
                case 697:
                case 702:
                case 707:
                case 709:
                case 717:
                case 718:
                case 722:
                case 723:
                case 724:
                case 727:
                case 728:
                case 729:
                case 730:
                case 731:
                case 732:
                case 734:
                case 735:
                case 736:
                case 737:
                case 738:
                    goto IL_25BA;
                case 698:
                {
                    tileWidth = 36;
                    int num67 = (int)(tileFrameX / 18);
                    tileFrameX = (short)(num67 * 38);
                    tileHeight = 44;
                    goto IL_25BA;
                }
                case 699:
                    goto IL_17A9;
                case 700:
                    goto IL_1459;
                case 701:
                    goto IL_147C;
                case 703:
                    goto IL_1145;
                case 705:
                    tileTop = 2;
                    goto IL_25BA;
                case 706:
                    goto IL_164A;
                case 708:
                    goto IL_2550;
                case 710:
                    goto IL_1DA6;
                case 711:
                    if (tileFrameX > 0)
                    {
                        tileWidth = 18;
                    }
                    tileHeight = 20;
                    glowTexture = TextureAssets.Tile[711].Value;
                    glowSourceRect = new Rectangle((int)tileFrameX + addFrX, (int)tileFrameY + addFrY, tileWidth, tileHeight);
                    goto IL_25BA;
                case 719:
                {
                    int num68 = (x + y + (int)(Main.GlobalTimeWrappedHourly * 15f)) % 14;
                    int num69 = num68 / 4;
                    int num70 = num68 % 4;
                    addFrX += 288 * num69;
                    addFrY += 270 * num70;
                    goto IL_25BA;
                }
                case 720:
                case 721:
                case 725:
                    goto IL_2477;
                case 726:
                    tileFrameX = 0;
                    tileFrameY = 0;
                    tileWidth = 20;
                    tileHeight = 20;
                    goto IL_25BA;
                case 733:
                    tileTop = 2;
                    if (tileFrameY < 54)
                    {
                        addFrX += 54;
                    }
                    tileFrameX %= 54;
                    tileFrameY %= 54;
                    goto IL_25BA;
                case 739:
                    break;
                default:
                    switch (typeCache)
                    {
                    case 748:
                        break;
                    case 749:
                    case 750:
                        goto IL_25BA;
                    case 751:
                    {
                        tileHeight = 46;
                        tileWidth = 56;
                        int num71 = (x + y * 2) % 7;
                        tileFrameY += (short)(num71 * 46);
                        goto IL_25BA;
                    }
                    case 752:
                        tileHeight = 38;
                        tileWidth = 36;
                        tileTop = 2;
                        goto IL_25BA;
                    default:
                        goto IL_25BA;
                    }
                    break;
                }
                int num72 = Main.tileFrame[(int)typeCache];
                addFrY = num72 * 90;
                goto IL_25BA;
            }
            }
            IL_1145:
            tileHeight = 20;
            if (x % 2 == 0)
            {
                tileSpriteEffect = SpriteEffects.FlipHorizontally;
                goto IL_25BA;
            }
            goto IL_25BA;
            IL_1187:
            tileHeight = 18;
            goto IL_25BA;
            IL_1459:
            tileWidth = 20;
            tileHeight = 16;
            tileTop += 2;
            if (x % 2 == 0)
            {
                tileSpriteEffect = SpriteEffects.FlipHorizontally;
                goto IL_25BA;
            }
            goto IL_25BA;
            IL_147C:
            tileWidth = 24;
            tileHeight = 34;
            tileTop -= 16;
            if (x % 2 == 0)
            {
                tileSpriteEffect = SpriteEffects.FlipHorizontally;
                goto IL_25BA;
            }
            goto IL_25BA;
            IL_164A:
            tileTop = 2;
            goto IL_25BA;
            IL_17A9:
            tileTop = 2;
            goto IL_25BA;
            IL_1AAA:
            addFrY = Main.tileFrame[(int)typeCache] * 36;
            goto IL_25BA;
            IL_1DA6:
            tileTop = 2;
            Main.critterCage = true;
            int bigAnimalCageFrame = this.GetBigAnimalCageFrame(x, y, (int)tileFrameX, (int)tileFrameY);
            if (typeCache <= 542)
            {
                if (typeCache <= 309)
                {
                    switch (typeCache)
                    {
                    case 275:
                        goto IL_1F03;
                    case 276:
                        goto IL_1F3C;
                    case 277:
                        addFrY = Main.mallardCageFrame[bigAnimalCageFrame] * 54;
                        goto IL_25BA;
                    case 278:
                        addFrY = Main.duckCageFrame[bigAnimalCageFrame] * 54;
                        goto IL_25BA;
                    case 279:
                        break;
                    case 280:
                        addFrY = Main.blueBirdCageFrame[bigAnimalCageFrame] * 54;
                        goto IL_25BA;
                    case 281:
                        addFrY = Main.redBirdCageFrame[bigAnimalCageFrame] * 54;
                        goto IL_25BA;
                    default:
                        if (typeCache - 296 <= 1)
{
                            addFrY = Main.scorpionCageFrame[0, bigAnimalCageFrame] * 54;
                            goto IL_25BA;
                        }
                        if (typeCache != 309)
{
                            goto IL_25BA;
                        }
                        addFrY = Main.penguinCageFrame[bigAnimalCageFrame] * 54;
                        goto IL_25BA;
                    }
                }
                else if (typeCache <= 359)
                {
                    if (typeCache != 358)
                    {
                        if (typeCache != 359)
{
                            goto IL_25BA;
                        }
                        goto IL_1F03;
                    }
                }
                else
                {
                    if (typeCache - 413 <= 1)
                    {
                        goto IL_1F3C;
                    }
                    if (typeCache != 542)
                    {
                        goto IL_25BA;
                    }
                    addFrY = Main.owlCageFrame[bigAnimalCageFrame] * 54;
                    goto IL_25BA;
                }
                addFrY = Main.birdCageFrame[bigAnimalCageFrame] * 54;
                goto IL_25BA;
            }
            if (typeCache > 612)
            {
                if (typeCache <= 640)
                {
                    if (typeCache != 632 && typeCache != 640)
                    {
                        goto IL_25BA;
                    }
                }
                else if (typeCache - 643 > 2)
                {
                    if (typeCache != 710)
                    {
                        goto IL_25BA;
                    }
                    int num73 = Main.pufferfishCageFrame[bigAnimalCageFrame] / 33;
                    addFrX = 108 * num73;
                    addFrY = (Main.pufferfishCageFrame[bigAnimalCageFrame] - num73 * 33) * 54;
                    goto IL_25BA;
                }
                addFrY = Main.macawCageFrame[bigAnimalCageFrame] * 54;
                goto IL_25BA;
            }
            switch (typeCache)
            {
            case 550:
            case 551:
                addFrY = Main.turtleCageFrame[bigAnimalCageFrame] * 54;
                goto IL_25BA;
            case 552:
            case 555:
            case 556:
            case 557:
                goto IL_25BA;
            case 553:
                addFrY = Main.grebeCageFrame[bigAnimalCageFrame] * 54;
                goto IL_25BA;
            case 554:
                addFrY = Main.seagullCageFrame[bigAnimalCageFrame] * 54;
                goto IL_25BA;
            case 558:
            case 559:
                addFrY = Main.seahorseCageFrame[bigAnimalCageFrame] * 54;
                goto IL_25BA;
            default:
                if (typeCache - 599 > 6)
                {
                    if (typeCache - 606 > 6)
                    {
                        goto IL_25BA;
                    }
                    goto IL_1F3C;
                }
                break;
            }
            IL_1F03:
            addFrY = Main.bunnyCageFrame[bigAnimalCageFrame] * 54;
            goto IL_25BA;
            IL_1F3C:
            addFrY = Main.squirrelCageFrame[bigAnimalCageFrame] * 54;
            goto IL_25BA;
            IL_2477:
            tileTop = 2;
            if (tileFrameY >= 54)
            {
                addFrY = Main.tileFrame[(int)typeCache];
                addFrY *= 54;
                goto IL_25BA;
            }
            addFrY = 0;
            goto IL_25BA;
            IL_2550:
            addFrY = Main.tileFrame[(int)typeCache] * 90;
            IL_25BA:
            if (TileID.Sets.Campfires[(int)tileCache.type])
            {
                if (tileFrameY < 36)
                {
                    addFrY = Main.tileFrame[(int)typeCache] * 36;
                }
                else
                {
                    addFrY = 252;
                }
                tileTop = 2;
            }
            if (tileCache.halfBrick())
            {
                halfBrickHeight = 8;
            }
            int num74;
            if (typeCache <= 412)
            {
                if (typeCache <= 79)
                {
                    if (typeCache <= 33)
                    {
                        switch (typeCache)
{
                        case 10:
                            num74 = (int)(tileFrameY / 54);
                            if (tileFrameX < 54 && num74 == 32)
{
                                glowTexture = TextureAssets.GlowMask[57].Value;
                                glowSourceRect = new Rectangle((int)tileFrameX, (int)(tileFrameY % 54), tileWidth, tileHeight);
                                glowColor = this._martianGlow;
                                return;
                            }
                            return;
                        case 11:
                            num74 = (int)(tileFrameY / 54);
                            if (tileFrameX >= 54)
{
                                return;
                            }
                            if (num74 == 32)
{
                                glowTexture = TextureAssets.GlowMask[58].Value;
                                glowSourceRect = new Rectangle((int)tileFrameX, (int)(tileFrameY % 54), tileWidth, tileHeight);
                                glowColor = this._martianGlow;
                            }
                            if (num74 == 33)
{
                                glowTexture = TextureAssets.GlowMask[119].Value;
                                glowSourceRect = new Rectangle((int)tileFrameX, (int)(tileFrameY % 54), tileWidth, tileHeight);
                                glowColor = this._meteorGlow;
                                return;
                            }
                            return;
                        case 12:
                        case 13:
                        case 16:
                        case 17:
                        case 20:
                            return;
                        case 14:
                            num74 = (int)(tileFrameX / 54);
                            if (num74 == 31)
{
                                glowTexture = TextureAssets.GlowMask[67].Value;
                                glowSourceRect = new Rectangle((int)(tileFrameX % 54), (int)tileFrameY, tileWidth, tileHeight);
                                glowColor = this._martianGlow;
                            }
                            if (num74 == 32)
{
                                glowTexture = TextureAssets.GlowMask[124].Value;
                                glowSourceRect = new Rectangle((int)(tileFrameX % 54), (int)tileFrameY, tileWidth, tileHeight);
                                glowColor = this._meteorGlow;
                                return;
                            }
                            return;
                        case 15:
                            break;
                        case 18:
                            num74 = (int)(tileFrameX / 36);
                            if (num74 == 27)
{
                                glowTexture = TextureAssets.GlowMask[69].Value;
                                glowSourceRect = new Rectangle((int)(tileFrameX % 36), (int)tileFrameY, tileWidth, tileHeight);
                                glowColor = this._martianGlow;
                            }
                            if (num74 == 28)
{
                                glowTexture = TextureAssets.GlowMask[125].Value;
                                glowSourceRect = new Rectangle((int)(tileFrameX % 36), (int)tileFrameY, tileWidth, tileHeight);
                                glowColor = this._meteorGlow;
                                return;
                            }
                            return;
                        case 19:
                            num74 = (int)(tileFrameY / 18);
                            if (num74 == 26)
{
                                glowTexture = TextureAssets.GlowMask[65].Value;
                                glowSourceRect = new Rectangle((int)tileFrameX, (int)(tileFrameY % 18), tileWidth, tileHeight);
                                glowColor = this._martianGlow;
                            }
                            if (num74 == 27)
{
                                glowTexture = TextureAssets.GlowMask[112].Value;
                                glowSourceRect = new Rectangle((int)tileFrameX, (int)(tileFrameY % 18), tileWidth, tileHeight);
                                glowColor = this._meteorGlow;
                                return;
                            }
                            return;
                        case 21:
                            goto IL_30AE;
                        default:
                            if (typeCache != 33)
{
                                return;
                            }
                            if (tileFrameX / 18 != 0)
{
                                return;
                            }
                            num74 = (int)(tileFrameY / 22);
                            if (num74 == 26)
{
                                glowTexture = TextureAssets.GlowMask[61].Value;
                                glowSourceRect = new Rectangle((int)tileFrameX, (int)(tileFrameY % 22), tileWidth, tileHeight);
                                glowColor = this._martianGlow;
                                return;
                            }
                            return;
                        }
                    }
                    else if (typeCache != 34)
                    {
                        if (typeCache != 42)
{
                            if (typeCache != 79)
{
                                return;
                            }
                            num74 = (int)(tileFrameY / 36);
                            if (num74 == 27)
{
                                glowTexture = TextureAssets.GlowMask[53].Value;
                                glowSourceRect = new Rectangle((int)tileFrameX, (int)(tileFrameY % 36), tileWidth, tileHeight);
                                glowColor = this._martianGlow;
                            }
                            if (num74 == 28)
{
                                glowTexture = TextureAssets.GlowMask[114].Value;
                                glowSourceRect = new Rectangle((int)tileFrameX, (int)(tileFrameY % 36), tileWidth, tileHeight);
                                glowColor = this._meteorGlow;
                                return;
                            }
                            return;
                        }
                        else
{
                            num74 = (int)(tileFrameY / 36);
                            int num75 = (int)(tileFrameY / 2016);
                            addFrY -= 2016 * num75;
                            addFrX += 36 * num75;
                            if (num74 == 33)
{
                                glowTexture = TextureAssets.GlowMask[63].Value;
                                glowSourceRect = new Rectangle((int)tileFrameX, (int)(tileFrameY % 36), tileWidth, tileHeight);
                                glowColor = this._martianGlow;
                                return;
                            }
                            return;
                        }
                    }
                    else
                    {
                        if (tileFrameX / 54 != 0)
{
                            return;
                        }
                        num74 = (int)(tileFrameY / 54);
                        if (num74 == 33)
{
                            glowTexture = TextureAssets.GlowMask[55].Value;
                            glowSourceRect = new Rectangle((int)tileFrameX, (int)(tileFrameY % 54), tileWidth, tileHeight);
                            glowColor = this._martianGlow;
                            return;
                        }
                        return;
                    }
                }
                else if (typeCache <= 104)
                {
                    switch (typeCache)
                    {
                    case 87:
                    {
                        num74 = (int)(tileFrameX / 54);
                        int num76 = (int)(tileFrameX / 1998);
                        addFrX -= 1998 * num76;
                        addFrY += 36 * num76;
                        if (num74 == 26)
{
                            glowTexture = TextureAssets.GlowMask[64].Value;
                            glowSourceRect = new Rectangle((int)(tileFrameX % 54), (int)tileFrameY, tileWidth, tileHeight);
                            glowColor = this._martianGlow;
                        }
                        if (num74 == 27)
{
                            glowTexture = TextureAssets.GlowMask[121].Value;
                            glowSourceRect = new Rectangle((int)(tileFrameX % 54), (int)tileFrameY, tileWidth, tileHeight);
                            glowColor = this._meteorGlow;
                            return;
                        }
                        return;
                    }
                    case 88:
                    {
                        num74 = (int)(tileFrameX / 54);
                        int num77 = (int)(tileFrameX / 1998);
                        addFrX -= 1998 * num77;
                        addFrY += 36 * num77;
                        if (num74 == 24)
{
                            glowTexture = TextureAssets.GlowMask[59].Value;
                            glowSourceRect = new Rectangle((int)(tileFrameX % 54), (int)tileFrameY, tileWidth, tileHeight);
                            glowColor = this._martianGlow;
                        }
                        if (num74 == 25)
{
                            glowTexture = TextureAssets.GlowMask[120].Value;
                            glowSourceRect = new Rectangle((int)(tileFrameX % 54), (int)tileFrameY, tileWidth, tileHeight);
                            glowColor = this._meteorGlow;
                            return;
                        }
                        return;
                    }
                    case 89:
                    {
                        num74 = (int)(tileFrameX / 54);
                        int num78 = (int)(tileFrameX / 1998);
                        addFrX -= 1998 * num78;
                        addFrY += 36 * num78;
                        if (num74 == 29)
{
                            glowTexture = TextureAssets.GlowMask[66].Value;
                            glowSourceRect = new Rectangle((int)(tileFrameX % 54), (int)tileFrameY, tileWidth, tileHeight);
                            glowColor = this._martianGlow;
                        }
                        if (num74 == 30)
{
                            glowTexture = TextureAssets.GlowMask[123].Value;
                            glowSourceRect = new Rectangle((int)(tileFrameX % 54), (int)tileFrameY, tileWidth, tileHeight);
                            glowColor = this._meteorGlow;
                            return;
                        }
                        return;
                    }
                    case 90:
                        num74 = (int)(tileFrameY / 36);
                        if (num74 == 27)
{
                            glowTexture = TextureAssets.GlowMask[52].Value;
                            glowSourceRect = new Rectangle((int)tileFrameX, (int)(tileFrameY % 36), tileWidth, tileHeight);
                            glowColor = this._martianGlow;
                        }
                        if (num74 == 28)
{
                            glowTexture = TextureAssets.GlowMask[113].Value;
                            glowSourceRect = new Rectangle((int)tileFrameX, (int)(tileFrameY % 36), tileWidth, tileHeight);
                            glowColor = this._meteorGlow;
                            return;
                        }
                        return;
                    case 91:
                    case 92:
                        return;
                    case 93:
                    {
                        num74 = (int)(tileFrameY / 54);
                        int num79 = (int)(tileFrameY / 1998);
                        addFrY -= 1998 * num79;
                        addFrX += 36 * num79;
                        tileTop += 2;
                        if (num74 == 27)
{
                            glowTexture = TextureAssets.GlowMask[62].Value;
                            glowSourceRect = new Rectangle((int)tileFrameX, (int)(tileFrameY % 54), tileWidth, tileHeight);
                            glowColor = this._martianGlow;
                            return;
                        }
                        return;
                    }
                    default:
                        switch (typeCache)
{
                        case 100:
                            if (tileFrameX / 36 != 0)
{
                                return;
                            }
                            num74 = (int)(tileFrameY / 36);
                            if (num74 == 27)
{
                                glowTexture = TextureAssets.GlowMask[68].Value;
                                glowSourceRect = new Rectangle((int)tileFrameX, (int)(tileFrameY % 36), tileWidth, tileHeight);
                                glowColor = this._martianGlow;
                                return;
                            }
                            return;
                        case 101:
{
                            num74 = (int)(tileFrameX / 54);
                            int num80 = (int)(tileFrameX / 1998);
                            addFrX -= 1998 * num80;
                            addFrY += 72 * num80;
                            if (num74 == 28)
{
                                glowTexture = TextureAssets.GlowMask[60].Value;
                                glowSourceRect = new Rectangle((int)(tileFrameX % 54), (int)tileFrameY, tileWidth, tileHeight);
                                glowColor = this._martianGlow;
                            }
                            if (num74 == 29)
{
                                glowTexture = TextureAssets.GlowMask[115].Value;
                                glowSourceRect = new Rectangle((int)(tileFrameX % 54), (int)tileFrameY, tileWidth, tileHeight);
                                glowColor = this._meteorGlow;
                                return;
                            }
                            return;
                        }
                        case 102:
                        case 103:
                            return;
                        case 104:
{
                            num74 = (int)(tileFrameX / 36);
                            int num81 = (int)(tileFrameX / 2016);
                            addFrX -= 2016 * num81;
                            addFrY += 90 * num81;
                            tileTop = 2;
                            if (num74 == 24)
{
                                glowTexture = TextureAssets.GlowMask[51].Value;
                                glowSourceRect = new Rectangle((int)(tileFrameX % 36), (int)tileFrameY, tileWidth, tileHeight);
                                glowColor = this._martianGlow;
                            }
                            if (num74 == 25)
{
                                glowTexture = TextureAssets.GlowMask[118].Value;
                                glowSourceRect = new Rectangle((int)(tileFrameX % 36), (int)tileFrameY, tileWidth, tileHeight);
                                glowColor = this._meteorGlow;
                                return;
                            }
                            return;
                        }
                        default:
                            return;
                        }
                        break;
                    }
                }
                else if (typeCache != 172)
                {
                    if (typeCache != 184)
                    {
                        if (typeCache != 412)
{
                            return;
                        }
                        glowTexture = TextureAssets.GlowMask[202].Value;
                        glowSourceRect = new Rectangle((int)tileFrameX, (int)tileFrameY + addFrY, tileWidth, tileHeight);
                        glowColor = new Color(255, 255, 255, 255);
                        return;
                    }
                    else
                    {
                        if (tileCache.frameX == 110)
{
                            glowTexture = TextureAssets.GlowMask[127].Value;
                            glowSourceRect = new Rectangle((int)tileFrameX, (int)tileFrameY, tileWidth, tileHeight);
                            glowColor = this._lavaMossGlow;
                        }
                        if (tileCache.frameX == 132)
{
                            glowTexture = TextureAssets.GlowMask[127].Value;
                            glowSourceRect = new Rectangle((int)tileFrameX, (int)tileFrameY, tileWidth, tileHeight);
                            glowColor = this._kryptonMossGlow;
                        }
                        if (tileCache.frameX == 154)
{
                            glowTexture = TextureAssets.GlowMask[127].Value;
                            glowSourceRect = new Rectangle((int)tileFrameX, (int)tileFrameY, tileWidth, tileHeight);
                            glowColor = this._xenonMossGlow;
                        }
                        if (tileCache.frameX == 176)
{
                            glowTexture = TextureAssets.GlowMask[127].Value;
                            glowSourceRect = new Rectangle((int)tileFrameX, (int)tileFrameY, tileWidth, tileHeight);
                            glowColor = this._argonMossGlow;
                        }
                        if (tileCache.frameX == 198)
{
                            glowTexture = TextureAssets.GlowMask[127].Value;
                            glowSourceRect = new Rectangle((int)tileFrameX, (int)tileFrameY, tileWidth, tileHeight);
                            glowColor = this._violetMossGlow;
                        }
                        if (tileCache.frameX == 220)
{
                            glowTexture = TextureAssets.GlowMask[127].Value;
                            glowSourceRect = new Rectangle((int)tileFrameX, (int)tileFrameY, tileWidth, tileHeight);
                            glowColor = new Color(Main.DiscoR, Main.DiscoG, Main.DiscoB);
                            return;
                        }
                        return;
                    }
                }
                else
                {
                    num74 = (int)(tileFrameY / 38);
                    int num82 = (int)(tileFrameY / 2014);
                    addFrY -= 2014 * num82;
                    addFrX += 36 * num82;
                    if (num74 == 28)
                    {
                        glowTexture = TextureAssets.GlowMask[88].Value;
                        glowSourceRect = new Rectangle((int)tileFrameX, (int)(tileFrameY % 38), tileWidth, tileHeight);
                        glowColor = this._martianGlow;
                    }
                    if (num74 == 29)
                    {
                        glowTexture = TextureAssets.GlowMask[122].Value;
                        glowSourceRect = new Rectangle((int)tileFrameX, (int)(tileFrameY % 38), tileWidth, tileHeight);
                        glowColor = this._meteorGlow;
                        return;
                    }
                    return;
                }
            }
            else if (typeCache <= 497)
            {
                if (typeCache <= 463)
                {
                    if (typeCache != 441)
                    {
                        if (typeCache != 463)
{
                            return;
                        }
                        glowTexture = TextureAssets.GlowMask[243].Value;
                        glowSourceRect = new Rectangle((int)tileFrameX, (int)tileFrameY + addFrY, tileWidth, tileHeight);
                        glowColor = new Color(127, 127, 127, 0);
                        return;
                    }
                }
                else
                {
                    if (typeCache == 467)
                    {
                        goto IL_30AE;
                    }
                    if (typeCache != 468)
                    {
                        if (typeCache != 497)
{
                            return;
                        }
                        goto IL_2FA6;
                    }
                }
                num74 = (int)(tileFrameX / 36);
                if (num74 == 48)
                {
                    glowTexture = TextureAssets.GlowMask[56].Value;
                    glowSourceRect = new Rectangle((int)(tileFrameX % 36), (int)tileFrameY, tileWidth, tileHeight);
                    glowColor = this._martianGlow;
                }
                if (num74 == 49)
                {
                    glowTexture = TextureAssets.GlowMask[117].Value;
                    glowSourceRect = new Rectangle((int)(tileFrameX % 36), (int)tileFrameY, tileWidth, tileHeight);
                    glowColor = this._meteorGlow;
                    return;
                }
                return;
            }
            else
            {
                if (typeCache > 638)
                {
                    if (typeCache != 656)
                    {
                        if (typeCache != 657)
{
                            if (typeCache != 701)
{
                                return;
                            }
                        }
                        else
{
                            if (tileFrameY >= 54)
{
                                glowTexture = TextureAssets.GlowMask[330].Value;
                                glowSourceRect = new Rectangle((int)tileFrameX, (int)tileFrameY + addFrY, tileWidth, tileHeight);
                                glowColor = Color.White;
                                return;
                            }
                            return;
                        }
                    }
                    glowTexture = TextureAssets.GlowMask[329].Value;
                    glowSourceRect = new Rectangle((int)tileFrameX, (int)tileFrameY + addFrY, tileWidth, tileHeight);
                    glowColor = new Color(255, 255, 255, 0) * ((float)Main.mouseTextColor / 255f);
                    return;
                }
                switch (typeCache)
                {
                case 564:
                    if (tileCache.frameX < 36)
                    {
                        glowTexture = TextureAssets.GlowMask[267].Value;
                        glowSourceRect = new Rectangle((int)tileFrameX, (int)tileFrameY + addFrY, tileWidth, tileHeight);
                        glowColor = new Color(200, 200, 200, 0) * ((float)Main.mouseTextColor / 255f);
                    }
                    addFrY = 0;
                    return;
                case 565:
                case 566:
                case 567:
                    return;
                case 568:
                    glowTexture = TextureAssets.GlowMask[268].Value;
                    glowSourceRect = new Rectangle((int)tileFrameX, (int)tileFrameY + addFrY, tileWidth, tileHeight);
                    glowColor = Color.White;
                    return;
                case 569:
                    glowTexture = TextureAssets.GlowMask[269].Value;
                    glowSourceRect = new Rectangle((int)tileFrameX, (int)tileFrameY + addFrY, tileWidth, tileHeight);
                    glowColor = Color.White;
                    return;
                case 570:
                    glowTexture = TextureAssets.GlowMask[270].Value;
                    glowSourceRect = new Rectangle((int)tileFrameX, (int)tileFrameY + addFrY, tileWidth, tileHeight);
                    glowColor = Color.White;
                    return;
                default:
                    if (typeCache == 580)
                    {
                        glowTexture = TextureAssets.GlowMask[289].Value;
                        glowSourceRect = new Rectangle((int)tileFrameX, (int)tileFrameY + addFrY, tileWidth, tileHeight);
                        glowColor = new Color(225, 110, 110, 0);
                        return;
                    }
                    switch (typeCache)
                    {
                    case 634:
                        glowTexture = TextureAssets.GlowMask[315].Value;
                        glowSourceRect = new Rectangle((int)tileFrameX, (int)tileFrameY + addFrY, tileWidth, tileHeight);
                        glowColor = Color.White;
                        return;
                    case 635:
                    case 636:
                        return;
                    case 637:
                        glowTexture = this.GetTileDrawTexture(tileCache, x, y);
                        glowSourceRect = new Rectangle((int)tileFrameX + addFrX, (int)tileFrameY + addFrY, tileWidth, tileHeight);
                        glowColor = Color.Lerp(Color.White, color, 0.75f);
                        return;
                    case 638:
                        glowTexture = TextureAssets.GlowMask[327].Value;
                        glowSourceRect = new Rectangle((int)tileFrameX + addFrX, (int)tileFrameY + addFrY, tileWidth, tileHeight - halfBrickHeight);
                        glowColor = Color.Lerp(Color.White, color, 0.75f);
                        return;
                    default:
                        return;
                    }
                    break;
                }
            }
            IL_2FA6:
            num74 = (int)(tileFrameY / 40);
            int num83 = num74 / 51;
            addFrY -= 2040 * num83;
            addFrX += 36 * num83;
            if (typeCache != 15)
            {
                return;
            }
            if (num74 == 32)
            {
                glowTexture = TextureAssets.GlowMask[54].Value;
                glowSourceRect = new Rectangle((int)tileFrameX, (int)(tileFrameY % 40), tileWidth, tileHeight);
                glowColor = this._martianGlow;
            }
            if (num74 == 33)
            {
                glowTexture = TextureAssets.GlowMask[116].Value;
                glowSourceRect = new Rectangle((int)tileFrameX, (int)(tileFrameY % 40), tileWidth, tileHeight);
                glowColor = this._meteorGlow;
                return;
            }
            return;
            IL_30AE:
            num74 = (int)(tileFrameX / 36);
            if (num74 == 48)
            {
                glowTexture = TextureAssets.GlowMask[56].Value;
                glowSourceRect = new Rectangle((int)(tileFrameX % 36), (int)tileFrameY, tileWidth, tileHeight);
                glowColor = this._martianGlow;
            }
            if (num74 == 49)
            {
                glowTexture = TextureAssets.GlowMask[117].Value;
                glowSourceRect = new Rectangle((int)(tileFrameX % 36), (int)tileFrameY, tileWidth, tileHeight);
                glowColor = this._meteorGlow;
                return;
            }
        }
References Terraria.GameContent.Drawing.TileDrawing._argonMossGlow, Terraria.GameContent.Drawing.TileDrawing._kryptonMossGlow, Terraria.GameContent.Drawing.TileDrawing._lavaMossGlow, Terraria.GameContent.Drawing.TileDrawing._martianGlow, Terraria.GameContent.Drawing.TileDrawing._meteorGlow, Terraria.GameContent.Drawing.TileDrawing._violetMossGlow, Terraria.GameContent.Drawing.TileDrawing._xenonMossGlow, System.Math.Abs(), Terraria.WorldGen.beachDistance, Terraria.Main.birdCageFrame, Terraria.Tile.blockType(), Terraria.Main.blueBirdCageFrame, Terraria.Main.bunnyCageFrame, Terraria.Main.butterflyCageFrame, Terraria.ID.TileID.Sets.Campfires, Terraria.Entity.Center, Microsoft.Xna.Framework.Graphics.Color, System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), Terraria.Main.DiscoB, Terraria.Main.DiscoG, Terraria.Main.DiscoR, Terraria.Main.dragonflyJarFrame, Terraria.Main.duckCageFrame, Microsoft.Xna.Framework.Rectangle.Empty, Terraria.Main.fairyJarFrame, Terraria.Main.fishBowlFrame, Terraria.Tile.frameX, Terraria.Main.frogCageFrame, Terraria.GameContent.Drawing.TileDrawing.GetBigAnimalCageFrame(), Terraria.WorldGen.GetBiomeInfluence(), Terraria.WorldGen.GetCactusType(), Terraria.Lighting.GetColor(), Terraria.GameContent.Drawing.TileDrawing.GetPalmTreeBiome(), Terraria.GameContent.Drawing.TileDrawing.GetSmallAnimalCageFrame(), Terraria.Animation.GetTemporaryFrame(), Terraria.GameContent.Drawing.TileDrawing.GetTileDrawTexture(), Terraria.Framing.GetTileSafely(), Terraria.GameContent.Drawing.TileDrawing.GetTreeBiome(), Terraria.GameContent.Drawing.TileDrawing.GetWaterAnimalCageFrame(), Terraria.Main.GlobalTimeWrappedHourly, Terraria.GameContent.TextureAssets.GlowMask, Terraria.Main.grasshopperCageFrame, Terraria.Main.grebeCageFrame, Terraria.Tile.halfBrick(), Terraria.GameContent.Drawing.TileDrawing.InAPlaceWithWind(), int, Terraria.Main.jellyfishCageFrame, Terraria.Main.ladybugCageFrame, Terraria.Main.lavaFishBowlFrame, Microsoft.Xna.Framework.Color.Lerp(), Terraria.Tile.liquid, Terraria.Main.LocalPlayer, Terraria.Main.macawCageFrame, Terraria.Main.maggotCageFrame, Terraria.Main.mallardCageFrame, System.Math.Max(), Terraria.Main.maxTilesX, Terraria.Main.mouseCageFrame, Terraria.Main.mouseTextColor, Terraria.Tile.nactive(), Terraria.Main.owlCageFrame, Terraria.GameContent.Events.BirthdayParty.PartyIsUp, Terraria.Main.penguinCageFrame, Terraria.GameContent.PressurePlateHelper.PressurePlatesPressed, Terraria.Main.pufferfishCageFrame, Terraria.Main.ratCageFrame, Terraria.Main.redBirdCageFrame, Terraria.Main.scorpionCageFrame, Terraria.Main.seagullCageFrame, Terraria.Main.seahorseCageFrame, Terraria.Main.slugCageFrame, Terraria.Main.snail2CageFrame, Terraria.Main.snailCageFrame, Terraria.WorldGen.SolidTile(), Terraria.Main.squirrelCageFrame, Terraria.GameContent.TextureAssets.Tile, Terraria.Main.tileFrame, Terraria.Main.tileFrameCounter, Terraria.Main.tileShine2, Microsoft.Xna.Framework.Color.Transparent, Terraria.Main.turtleCageFrame, Terraria.Tile.type, ReLogic.Content.Asset< T >.Value, Terraria.Main.waterStriderCageFrame, Terraria.Main.weatherVaneBobframe, Microsoft.Xna.Framework.Color.White, Terraria.Main.WindForVisuals, Terraria.Main.wormCageFrame, and Microsoft.Xna.Framework.Vector2.X.
Referenced by Terraria.GameContent.Drawing.TileDrawing.DrawAnyDirectionalGrass(), Terraria.GameContent.Drawing.TileDrawing.DrawGrass(), Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileGrassInWind(), Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileVinesInWind(), Terraria.GameContent.Drawing.TileDrawing.DrawRisingVineStrip(), Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile(), and Terraria.GameContent.Drawing.TileDrawing.DrawVineStrip().