Terraria Decompiled: Terraria.GameContent.Drawing.TileDrawing.DrawTiles_EmitParticles
DrawTiles_EmitParticles()
void Terraria.GameContent.Drawing.TileDrawing.DrawTiles_EmitParticles (int j, int i, Tile tileCache, ushort typeCache, short tileFrameX, short tileFrameY, Color tileLight) inline private
Definition at line 7971 of file TileDrawing.cs.
        {
            bool flag = this.IsVisible(tileCache);
            int num = this._leafFrequency;
            num /= 4;
            if (typeCache == 718 && !Main.dayTime && this._rand.Next(3) == 0 && !WorldGen.SolidTile3(i, j - 1))
            {
                if (Main.player[Main.myPlayer].RollLuck(100) == 0)
                {
                    int num2 = Gore.NewGore(new Vector2((float)(i * 16 + this._rand.Next(16)), (float)(j * 16 - 12)), default(Vector2), 16, 1f);
                    Main.gore[num2].scale *= this._rand.NextFloat() * 0.5f + 0.75f;
                    Main.gore[num2].velocity *= 0.2f;
                    Gore gore = Main.gore[num2];
                    gore.velocity.Y = gore.velocity.Y - (float)this._rand.Next(5, 31) * 0.1f;
                    if (this._rand.Next(5) == 0)
                    {
                        Gore gore2 = Main.gore[num2];
                        gore2.velocity.Y = gore2.velocity.Y - (float)this._rand.Next(5, 41) * 0.1f;
                    }
                    if (this._rand.Next(3) == 0)
                    {
                        Main.gore[num2].velocity *= 0.5f;
                    }
                    Main.gore[num2].velocity /= Main.gore[num2].scale;
                    int num3 = Gore.NewGore(new Vector2((float)(i * 16), (float)(j * 16)), default(Vector2), 16, 1f);
                    Main.gore[num3].scale = Main.gore[num2].scale;
                    Main.gore[num3].position = Main.gore[num2].position;
                    Main.gore[num3].velocity = Main.gore[num2].velocity;
                }
                if (Main.player[Main.myPlayer].RollLuck(60) == 0)
                {
                    int num4 = Gore.NewGore(new Vector2((float)(i * 16 + this._rand.Next(16)), (float)(j * 16 - 12)), default(Vector2), 17, 1f);
                    Main.gore[num4].scale *= this._rand.NextFloat() * 0.5f + 0.75f;
                    Main.gore[num4].velocity *= 0.2f;
                    Gore gore3 = Main.gore[num4];
                    gore3.velocity.Y = gore3.velocity.Y - (float)this._rand.Next(5, 41) * 0.1f;
                    if (this._rand.Next(5) == 0)
                    {
                        Gore gore4 = Main.gore[num4];
                        gore4.velocity.Y = gore4.velocity.Y - (float)this._rand.Next(5, 51) * 0.1f;
                    }
                    if (this._rand.Next(3) == 0)
                    {
                        Main.gore[num4].velocity *= 0.5f;
                    }
                    Main.gore[num4].velocity /= Main.gore[num4].scale;
                    int num5 = Gore.NewGore(new Vector2((float)(i * 16), (float)(j * 16)), default(Vector2), 17, 1f);
                    Main.gore[num5].scale = Main.gore[num4].scale;
                    Main.gore[num5].position = Main.gore[num4].position;
                    Main.gore[num5].velocity = Main.gore[num4].velocity;
                }
                if (Main.player[Main.myPlayer].RollLuck(30) == 0)
                {
                    int num6 = Dust.NewDust(new Vector2((float)(i * 16), (float)(j * 16 - 2)), 1, 1, 58, 0f, 0f, 150, default(Color), 1f);
                    Main.dust[num6].scale *= this._rand.NextFloat() * 0.5f + 0.75f;
                    Main.dust[num6].color = new Color(255, 255, 255, 0);
                    Main.dust[num6].velocity *= 0.2f;
                    Dust dust = Main.dust[num6];
                    dust.velocity.Y = dust.velocity.Y - (float)this._rand.Next(5, 51) * 0.1f;
                    if (this._rand.Next(5) == 0)
                    {
                        Dust dust2 = Main.dust[num6];
                        dust2.velocity.Y = dust2.velocity.Y - (float)this._rand.Next(5, 61) * 0.1f;
                    }
                    if (this._rand.Next(3) == 0)
                    {
                        Main.dust[num6].velocity *= 0.5f;
                    }
                    Main.dust[num6].velocity /= Main.dust[num6].scale;
                }
            }
            if (typeCache == 244 && tileFrameX == 18 && tileFrameY == 18 && this._rand.Next(2) == 0)
            {
                if (this._rand.Next(500) == 0)
                {
                    Gore.NewGore(new Vector2((float)(i * 16 + 8), (float)(j * 16 + 8)), default(Vector2), 415, (float)this._rand.Next(51, 101) * 0.01f);
                }
                else if (this._rand.Next(250) == 0)
                {
                    Gore.NewGore(new Vector2((float)(i * 16 + 8), (float)(j * 16 + 8)), default(Vector2), 414, (float)this._rand.Next(51, 101) * 0.01f);
                }
                else if (this._rand.Next(80) == 0)
                {
                    Gore.NewGore(new Vector2((float)(i * 16 + 8), (float)(j * 16 + 8)), default(Vector2), 413, (float)this._rand.Next(51, 101) * 0.01f);
                }
                else if (this._rand.Next(10) == 0)
                {
                    Gore.NewGore(new Vector2((float)(i * 16 + 8), (float)(j * 16 + 8)), default(Vector2), 412, (float)this._rand.Next(51, 101) * 0.01f);
                }
                else if (this._rand.Next(3) == 0)
                {
                    Gore.NewGore(new Vector2((float)(i * 16 + 8), (float)(j * 16 + 8)), default(Vector2), 411, (float)this._rand.Next(51, 101) * 0.01f);
                }
            }
            if (typeCache == 565 && tileFrameX == 0 && tileFrameY == 18 && this._rand.Next(3) == 0)
            {
                Vector2 vector = new Point(i, j).ToWorldCoordinates(8f, 8f);
                int num7 = 1202;
                float num8 = 8f + Main.rand.NextFloat() * 1.6f;
                Vector2 vector2 = vector + new Vector2(0f, -18f);
                Vector2 vector3 = Main.rand.NextVector2Circular(0.7f, 0.25f) * 0.4f + Main.rand.NextVector2CircularEdge(1f, 0.4f) * 0.1f;
                vector3 *= 4f;
                Gore.NewGorePerfect(vector2, vector3, num7, num8);
            }
            if (typeCache == 215 && tileFrameY < 36 && this._rand.Next(3) == 0 && tileFrameY == 0)
            {
                int num9 = Dust.NewDust(new Vector2((float)(i * 16 + 2), (float)(j * 16 - 4)), 4, 8, 31, 0f, 0f, 100, default(Color), 1f);
                if (tileFrameX == 0)
                {
                    Dust dust3 = this._dust[num9];
                    dust3.position.X = dust3.position.X + (float)this._rand.Next(8);
                }
                if (tileFrameX == 36)
                {
                    Dust dust4 = this._dust[num9];
                    dust4.position.X = dust4.position.X - (float)this._rand.Next(8);
                }
                this._dust[num9].alpha += this._rand.Next(100);
                this._dust[num9].velocity *= 0.2f;
                Dust dust5 = this._dust[num9];
                dust5.velocity.Y = dust5.velocity.Y - (0.5f + (float)this._rand.Next(10) * 0.1f);
                this._dust[num9].fadeIn = 0.5f + (float)this._rand.Next(10) * 0.1f;
            }
            if (typeCache == 592 && tileFrameY == 18 && this._rand.Next(3) == 0)
            {
                int num10 = Dust.NewDust(new Vector2((float)(i * 16 + 2), (float)(j * 16 + 4)), 4, 8, 31, 0f, 0f, 100, default(Color), 1f);
                if (tileFrameX == 0)
                {
                    Dust dust6 = this._dust[num10];
                    dust6.position.X = dust6.position.X + (float)this._rand.Next(8);
                }
                if (tileFrameX == 36)
                {
                    Dust dust7 = this._dust[num10];
                    dust7.position.X = dust7.position.X - (float)this._rand.Next(8);
                }
                this._dust[num10].alpha += this._rand.Next(100);
                this._dust[num10].velocity *= 0.2f;
                Dust dust8 = this._dust[num10];
                dust8.velocity.Y = dust8.velocity.Y - (0.5f + (float)this._rand.Next(10) * 0.1f);
                this._dust[num10].fadeIn = 0.5f + (float)this._rand.Next(10) * 0.1f;
            }
            else if (typeCache == 406 && tileFrameY == 54 && tileFrameX == 0 && this._rand.Next(3) == 0)
            {
                Vector2 vector4 = new Vector2((float)(i * 16 + 16), (float)(j * 16 + 8));
                Vector2 vector5 = new Vector2(0f, 0f);
                if (Main.WindForVisuals < 0f)
                {
                    vector5.X = -Main.WindForVisuals;
                }
                int num11 = this._rand.Next(825, 828);
                if (this._rand.Next(4) == 0)
                {
                    Gore.NewGore(vector4, vector5, num11, this._rand.NextFloat() * 0.2f + 0.2f);
                }
                else if (this._rand.Next(2) == 0)
                {
                    Gore.NewGore(vector4, vector5, num11, this._rand.NextFloat() * 0.3f + 0.3f);
                }
                else
                {
                    Gore.NewGore(vector4, vector5, num11, this._rand.NextFloat() * 0.4f + 0.4f);
                }
            }
            else if (typeCache == 452 && tileFrameY == 0 && tileFrameX == 0 && this._rand.Next(3) == 0)
            {
                Vector2 vector6 = new Vector2((float)(i * 16 + 16), (float)(j * 16 + 8));
                Vector2 vector7 = new Vector2(0f, 0f);
                if (Main.WindForVisuals < 0f)
                {
                    vector7.X = -Main.WindForVisuals;
                }
                int num12 = Main.tileFrame[(int)typeCache];
                int num13 = 907 + num12 / 5;
                if (this._rand.Next(2) == 0)
                {
                    Gore.NewGore(vector6, vector7, num13, this._rand.NextFloat() * 0.4f + 0.4f);
                }
            }
            if (typeCache == 192 && this._rand.Next(num) == 0)
            {
                this.EmitLivingTreeLeaf(i, j, 910);
            }
            if (typeCache == 384 && this._rand.Next(num) == 0)
            {
                this.EmitLivingTreeLeaf(i, j, 914);
            }
            if ((typeCache == 666 || typeCache == 712) && tileCache.liquid <= 0 && j - 1 > 0 && this._rand.Next(100) == 0 && !WorldGen.ActiveAndWalkableTile(i, j - 1) && !WorldGen.AnyLiquidAt(i, j - 1, -1))
            {
                ParticleOrchestrator.RequestParticleSpawn(true, ParticleOrchestraType.PooFly, new ParticleOrchestraSettings
                {
                    PositionInWorld = new Vector2((float)(i * 16 + 8), (float)(j * 16 - 8))
                }, null);
            }
            if (typeCache == 711 && tileFrameX == 0 && tileFrameY == 0)
            {
                if (this._rand.Next(45) == 0)
                {
                    ParticleOrchestrator.RequestParticleSpawn(true, ParticleOrchestraType.RainbowBoulder3, new ParticleOrchestraSettings
                    {
                        PositionInWorld = new Vector2((float)(i * 16 + 16), (float)(j * 16 + 16))
                    }, null);
                }
                if (this._rand.Next(3) != 0)
                {
                    ParticleOrchestrator.RequestParticleSpawn(true, ParticleOrchestraType.RainbowBoulder2, new ParticleOrchestraSettings
                    {
                        PositionInWorld = new Vector2((float)(i * 16 + 16), (float)(j * 16 + 16)) + this._rand.NextVector2Circular(16f, 16f),
                        MovementVector = this._rand.NextVector2Circular(1f, 0.5f) * 0.5f
                    }, null);
                }
            }
            if (TileID.Sets.SpawnsNatureFlies[(int)typeCache] && tileCache.liquid <= 0)
            {
                float num14 = Utils.GetLerpValue(0.08f, 0.18f, Math.Abs(Main.WindForVisuals), true);
                num14 += 0.3f;
                if (this._rand.NextFloat() < num14)
                {
                    bool flag2 = this._rand.Next(600) == 0;
                    if (!flag2)
                    {
                        int num15;
                        int num16;
                        this._windGrid.GetWindTime(i, j, 8, out num15, out num16, out num16);
                        flag2 = num15 > 0 && this._rand.Next(48) == 0;
                    }
                    if (flag2)
                    {
                        ParticleOrchestrator.RequestParticleSpawn(true, ParticleOrchestraType.NatureFly, new ParticleOrchestraSettings
{
                            PositionInWorld = new Vector2((float)(i * 16 + 8), (float)(j * 16))
                        }, null);
                    }
                }
            }
            if (this._rand.Next(1200) == 0)
            {
                bool flag3 = j + 1 < 0;
                bool flag4 = false;
                int num17 = 3;
                if ((double)j < Main.worldSurface)
                {
                    if (this._rand.Next(10) != 0)
                    {
                        flag3 = true;
                    }
                    else
                    {
                        num17--;
                        flag4 = true;
                    }
                }
                if (!TileID.Sets.MakesRubbleDust[(int)typeCache])
                {
                    flag3 = true;
                }
                if (!flag3 && WorldGen.ActiveAndWalkableTile(i, j + 1))
                {
                    flag3 = true;
                }
                if (!flag3 && !WallID.Sets.AllowsWind[(int)Main.tile[i, j].wall])
                {
                    if (this._rand.Next(2) == 0)
                    {
                        flag3 = true;
                    }
                    else
                    {
                        num17--;
                    }
                }
                if (!flag3)
                {
                    for (int k = 0; k < num17; k++)
                    {
                        int num18 = WorldGen.KillTile_MakeTileDust(i, j, tileCache);
                        Dust dust9 = Main.dust[num18];
                        Dust dust10 = dust9;
                        dust10.position.Y = dust10.position.Y + 8f;
                        dust9.velocity *= 0.1f;
                        if (flag4)
{
                            dust9.scale -= 0.3f;
                        }
                    }
                }
            }
            if (!flag)
            {
                return;
            }
            if (typeCache == 238 && this._rand.Next(10) == 0)
            {
                int num19 = Dust.NewDust(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16, 168, 0f, 0f, 0, default(Color), 1f);
                this._dust[num19].noGravity = true;
                this._dust[num19].alpha = 200;
            }
            if (typeCache == 139)
            {
                if (tileCache.frameX == 36 && tileCache.frameY % 36 == 0 && (int)Main.timeForVisualEffects % 7 == 0 && this._rand.Next(3) == 0)
                {
                    int num20 = this._rand.Next(570, 573);
                    Vector2 vector8 = new Vector2((float)(i * 16 + 8), (float)(j * 16 - 8));
                    Vector2 vector9 = new Vector2(Main.WindForVisuals * 2f, -0.5f);
                    vector9.X *= 1f + (float)this._rand.Next(-50, 51) * 0.01f;
                    vector9.Y *= 1f + (float)this._rand.Next(-50, 51) * 0.01f;
                    if (num20 == 572)
                    {
                        vector8.X -= 8f;
                    }
                    if (num20 == 571)
                    {
                        vector8.X -= 4f;
                    }
                    Gore.NewGore(vector8, vector9, num20, 0.8f);
                }
            }
            else if (typeCache == 463)
            {
                if (tileFrameY == 54 && tileFrameX == 0)
                {
                    for (int l = 0; l < 4; l++)
                    {
                        if (this._rand.Next(2) != 0)
{
                            Dust dust11 = Dust.NewDustDirect(new Vector2((float)(i * 16 + 4), (float)(j * 16)), 36, 8, 16, 0f, 0f, 0, default(Color), 1f);
                            dust11.noGravity = true;
                            dust11.alpha = 140;
                            dust11.fadeIn = 1.2f;
                            dust11.velocity = Vector2.Zero;
                        }
                    }
                }
                if (tileFrameY == 18 && (tileFrameX == 0 || tileFrameX == 36))
                {
                    for (int m = 0; m < 1; m++)
                    {
                        if (this._rand.Next(13) == 0)
{
                            Dust dust12 = Dust.NewDustDirect(new Vector2((float)(i * 16), (float)(j * 16)), 8, 8, 274, 0f, 0f, 0, default(Color), 1f);
                            dust12.position = new Vector2((float)(i * 16 + 8), (float)(j * 16 + 8));
                            dust12.position.X = dust12.position.X + (float)((tileFrameX == 36) ? 4 : (-4));
                            dust12.noGravity = true;
                            dust12.alpha = 128;
                            dust12.fadeIn = 1.2f;
                            dust12.noLight = true;
                            dust12.velocity = new Vector2(0f, this._rand.NextFloatDirection() * 1.2f);
                        }
                    }
                }
            }
            else if (typeCache == 497)
            {
                if (tileCache.frameY / 40 == 31 && tileCache.frameY % 40 == 0)
                {
                    for (int n = 0; n < 1; n++)
                    {
                        if (this._rand.Next(10) == 0)
{
                            Dust dust13 = Dust.NewDustDirect(new Vector2((float)(i * 16), (float)(j * 16 + 8)), 16, 12, 43, 0f, 0f, 0, default(Color), 1f);
                            dust13.noGravity = true;
                            dust13.alpha = 254;
                            dust13.color = Color.White;
                            dust13.scale = 0.7f;
                            dust13.velocity = Vector2.Zero;
                            dust13.noLight = true;
                        }
                    }
                }
            }
            else if (typeCache == 165 && tileFrameX >= 162 && tileFrameX <= 214 && tileFrameY == 72)
            {
                if (this._rand.Next(60) == 0)
                {
                    int num21 = Dust.NewDust(new Vector2((float)(i * 16 + 2), (float)(j * 16 + 6)), 8, 4, 153, 0f, 0f, 0, default(Color), 1f);
                    this._dust[num21].scale -= (float)this._rand.Next(3) * 0.1f;
                    this._dust[num21].velocity.Y = 0f;
                    Dust dust14 = this._dust[num21];
                    dust14.velocity.X = dust14.velocity.X * 0.05f;
                    this._dust[num21].alpha = 100;
                }
            }
            else if (typeCache == 42 && tileFrameX == 0)
            {
                int num22 = (int)(tileFrameY / 36);
                if (tileFrameY / 18 % 2 == 1)
                {
                    if (num22 == 7)
                    {
                        if (this._rand.Next(50) == 0)
{
                            int num23 = Dust.NewDust(new Vector2((float)(i * 16 + 4), (float)(j * 16 + 4)), 8, 8, 58, 0f, 0f, 150, default(Color), 1f);
                            this._dust[num23].velocity *= 0.5f;
                        }
                        if (this._rand.Next(100) == 0)
{
                            int num24 = Gore.NewGore(new Vector2((float)(i * 16 - 2), (float)(j * 16 - 4)), default(Vector2), this._rand.Next(16, 18), 1f);
                            this._gore[num24].scale *= 0.7f;
                            this._gore[num24].velocity *= 0.25f;
                        }
                    }
                    else if (num22 == 29)
                    {
                        if (this._rand.Next(40) == 0)
{
                            int num25 = Dust.NewDust(new Vector2((float)(i * 16 + 4), (float)(j * 16)), 8, 8, 59, 0f, 0f, 100, default(Color), 1f);
                            if (this._rand.Next(3) != 0)
{
                                this._dust[num25].noGravity = true;
                            }
                            this._dust[num25].velocity *= 0.3f;
                            Dust dust15 = this._dust[num25];
                            dust15.velocity.Y = dust15.velocity.Y - 1.5f;
                        }
                    }
                    else if (num22 == 50)
                    {
                        if (this._rand.Next(10) == 0)
{
                            int num26 = Dust.NewDust(new Vector2((float)(i * 16 + 4), (float)(j * 16)), 8, 8, 57, 0f, 0f, 100, default(Color), 1f);
                            if (this._rand.Next(3) != 0)
{
                                this._dust[num26].noGravity = true;
                            }
                            this._dust[num26].velocity *= 0.3f;
                            Dust dust16 = this._dust[num26];
                            dust16.velocity.Y = dust16.velocity.Y - 1.5f;
                        }
                    }
                    else if (num22 == 51 && this._rand.Next(40) == 0)
                    {
                        int num27 = Dust.NewDust(new Vector2((float)(i * 16 + 4), (float)(j * 16 + 2)), 4, 4, 242, 0f, 0f, 100, default(Color), 1f);
                        if (this._rand.Next(3) != 0)
{
                            this._dust[num27].noGravity = true;
                        }
                        this._dust[num27].velocity *= 0.3f;
                        Dust dust17 = this._dust[num27];
                        dust17.velocity.Y = dust17.velocity.Y - 1.5f;
                    }
                }
            }
            if (typeCache == 4 && this._rand.Next(40) == 0 && tileFrameX < 66)
            {
                int num28 = (int)MathHelper.Clamp((float)(tileCache.frameY / 22), 0f, (float)(TorchID.Count - 1));
                int num29 = TorchID.Dust[num28];
                int num30;
                if (tileFrameX == 22)
                {
                    num30 = Dust.NewDust(new Vector2((float)(i * 16 + 6), (float)(j * 16)), 4, 4, num29, 0f, 0f, 100, default(Color), 1f);
                }
                else if (tileFrameX == 44)
                {
                    num30 = Dust.NewDust(new Vector2((float)(i * 16 + 2), (float)(j * 16)), 4, 4, num29, 0f, 0f, 100, default(Color), 1f);
                }
                else
                {
                    num30 = Dust.NewDust(new Vector2((float)(i * 16 + 4), (float)(j * 16)), 4, 4, num29, 0f, 0f, 100, default(Color), 1f);
                }
                if (this._rand.Next(3) != 0)
                {
                    this._dust[num30].noGravity = true;
                }
                this._dust[num30].velocity *= 0.3f;
                Dust dust18 = this._dust[num30];
                dust18.velocity.Y = dust18.velocity.Y - 1.5f;
                if (num29 == 66)
                {
                    this._dust[num30].color = new Color(Main.DiscoR, Main.DiscoG, Main.DiscoB);
                    this._dust[num30].noGravity = true;
                }
            }
            if (typeCache == 93 && this._rand.Next(40) == 0 && tileFrameX == 0)
            {
                int num31 = (int)(tileFrameY / 54);
                if (tileFrameY / 18 % 3 == 0)
                {
                    int num32;
                    if (num31 <= 20)
                    {
                        if (num31 != 0)
{
                            switch (num31)
{
                            case 6:
                            case 7:
                            case 8:
                            case 10:
                            case 14:
                            case 15:
                            case 16:
                                break;
                            case 9:
                            case 11:
                            case 12:
                            case 13:
                            case 17:
                            case 18:
                            case 19:
                                goto IL_19D7;
                            case 20:
                                num32 = 59;
                                goto IL_19DA;
                            default:
                                goto IL_19D7;
                            }
                        }
                        num32 = 6;
                        goto IL_19DA;
                    }
                    if (num31 == 44)
                    {
                        num32 = 57;
                        goto IL_19DA;
                    }
                    if (num31 == 45)
                    {
                        num32 = 242;
                        goto IL_19DA;
                    }
                    IL_19D7:
                    num32 = -1;
                    IL_19DA:
                    if (num32 != -1)
                    {
                        int num33 = Dust.NewDust(new Vector2((float)(i * 16 + 4), (float)(j * 16 + 2)), 4, 4, num32, 0f, 0f, 100, default(Color), 1f);
                        if (this._rand.Next(3) != 0)
{
                            this._dust[num33].noGravity = true;
                        }
                        this._dust[num33].velocity *= 0.3f;
                        Dust dust19 = this._dust[num33];
                        dust19.velocity.Y = dust19.velocity.Y - 1.5f;
                    }
                }
            }
            if (typeCache == 100 && this._rand.Next(40) == 0 && tileFrameX < 36)
            {
                int num34 = (int)(tileFrameY / 36);
                if (tileFrameY / 18 % 2 == 0)
                {
                    int num35;
                    if (num34 <= 20)
                    {
                        switch (num34)
{
                        case 0:
                        case 5:
                        case 7:
                        case 8:
                        case 10:
                        case 12:
                        case 14:
                        case 15:
                        case 16:
                            num35 = 6;
                            goto IL_1B2D;
                        case 1:
                        case 2:
                        case 3:
                        case 4:
                        case 6:
                        case 9:
                        case 11:
                        case 13:
                            break;
                        default:
                            if (num34 == 20)
{
                                num35 = 59;
                                goto IL_1B2D;
                            }
                            break;
                        }
                    }
                    else
                    {
                        if (num34 == 44)
{
                            num35 = 57;
                            goto IL_1B2D;
                        }
                        if (num34 == 45)
{
                            num35 = 242;
                            goto IL_1B2D;
                        }
                    }
                    num35 = -1;
                    IL_1B2D:
                    if (num35 != -1)
                    {
                        Vector2 vector10;
                        if (tileFrameX == 0)
{
                            if (this._rand.Next(3) == 0)
{
                                vector10 = new Vector2((float)(i * 16 + 4), (float)(j * 16 + 2));
                            }
                            else
{
                                vector10 = new Vector2((float)(i * 16 + 14), (float)(j * 16 + 2));
                            }
                        }
                        else if (this._rand.Next(3) == 0)
{
                            vector10 = new Vector2((float)(i * 16 + 6), (float)(j * 16 + 2));
                        }
                        else
{
                            vector10 = new Vector2((float)(i * 16), (float)(j * 16 + 2));
                        }
                        int num36 = Dust.NewDust(vector10, 4, 4, num35, 0f, 0f, 100, default(Color), 1f);
                        if (this._rand.Next(3) != 0)
{
                            this._dust[num36].noGravity = true;
                        }
                        this._dust[num36].velocity *= 0.3f;
                        Dust dust20 = this._dust[num36];
                        dust20.velocity.Y = dust20.velocity.Y - 1.5f;
                    }
                }
            }
            if (typeCache == 98 && this._rand.Next(40) == 0 && tileFrameY == 0 && tileFrameX == 0)
            {
                int num37 = Dust.NewDust(new Vector2((float)(i * 16 + 12), (float)(j * 16 + 2)), 4, 4, 6, 0f, 0f, 100, default(Color), 1f);
                if (this._rand.Next(3) != 0)
                {
                    this._dust[num37].noGravity = true;
                }
                this._dust[num37].velocity *= 0.3f;
                Dust dust21 = this._dust[num37];
                dust21.velocity.Y = dust21.velocity.Y - 1.5f;
            }
            if (typeCache == 49 && tileFrameX == 0 && this._rand.Next(2) == 0)
            {
                int num38 = Dust.NewDust(new Vector2((float)(i * 16 + 4), (float)(j * 16 - 4)), 4, 4, 172, 0f, 0f, 100, default(Color), 1f);
                if (this._rand.Next(3) == 0)
                {
                    this._dust[num38].scale = 0.5f;
                }
                else
                {
                    this._dust[num38].scale = 0.9f;
                    this._dust[num38].noGravity = true;
                }
                this._dust[num38].velocity *= 0.3f;
                Dust dust22 = this._dust[num38];
                dust22.velocity.Y = dust22.velocity.Y - 1.5f;
            }
            if (typeCache == 372 && tileFrameX == 0 && this._rand.Next(2) == 0)
            {
                int num39 = Dust.NewDust(new Vector2((float)(i * 16 + 4), (float)(j * 16 - 4)), 4, 4, 242, 0f, 0f, 100, default(Color), 1f);
                if (this._rand.Next(3) == 0)
                {
                    this._dust[num39].scale = 0.5f;
                }
                else
                {
                    this._dust[num39].scale = 0.9f;
                    this._dust[num39].noGravity = true;
                }
                this._dust[num39].velocity *= 0.3f;
                Dust dust23 = this._dust[num39];
                dust23.velocity.Y = dust23.velocity.Y - 1.5f;
            }
            if (typeCache == 646 && tileFrameX == 0)
            {
                this._rand.Next(2);
            }
            if (typeCache == 34 && this._rand.Next(40) == 0 && tileFrameX % 108 < 54)
            {
                int num40 = (int)(tileFrameY / 54);
                if (tileFrameX >= 108)
                {
                    num40 += (int)(37 * (tileFrameX / 108));
                }
                int num41 = (int)(tileFrameX / 18 % 3);
                if (tileFrameY / 18 % 3 == 1 && num41 != 1)
                {
                    int num42;
                    if (num40 <= 21)
                    {
                        switch (num40)
{
                        case 0:
                        case 1:
                        case 2:
                        case 3:
                        case 4:
                        case 5:
                        case 12:
                        case 13:
                        case 16:
                            break;
                        case 6:
                        case 7:
                        case 8:
                        case 9:
                        case 10:
                        case 11:
                        case 14:
                        case 15:
                            goto IL_1FAA;
                        default:
                            if (num40 != 19 && num40 != 21)
{
                                goto IL_1FAA;
                            }
                            break;
                        }
                        num42 = 6;
                        goto IL_1FAD;
                    }
                    if (num40 == 25)
                    {
                        num42 = 59;
                        goto IL_1FAD;
                    }
                    if (num40 == 50)
                    {
                        num42 = 57;
                        goto IL_1FAD;
                    }
                    if (num40 == 51)
                    {
                        num42 = 242;
                        goto IL_1FAD;
                    }
                    IL_1FAA:
                    num42 = -1;
                    IL_1FAD:
                    if (num42 != -1)
                    {
                        int num43 = Dust.NewDust(new Vector2((float)(i * 16), (float)(j * 16 + 2)), 14, 6, num42, 0f, 0f, 100, default(Color), 1f);
                        if (this._rand.Next(3) != 0)
{
                            this._dust[num43].noGravity = true;
                        }
                        this._dust[num43].velocity *= 0.3f;
                        Dust dust24 = this._dust[num43];
                        dust24.velocity.Y = dust24.velocity.Y - 1.5f;
                    }
                }
            }
            if (typeCache == 83)
            {
                int num44 = (int)(tileFrameX / 18);
                if (WorldGen.IsAlchemyPlantHarvestable(num44, j))
                {
                    this.EmitAlchemyHerbParticles(j, i, num44);
                }
            }
            if (typeCache == 22 && this._rand.Next(400) == 0)
            {
                Dust.NewDust(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16, 14, 0f, 0f, 0, default(Color), 1f);
                return;
            }
            if ((typeCache == 23 || typeCache == 24 || typeCache == 32) && this._rand.Next(500) == 0)
            {
                Dust.NewDust(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16, 14, 0f, 0f, 0, default(Color), 1f);
                return;
            }
            if (typeCache == 25 && this._rand.Next(700) == 0)
            {
                Dust.NewDust(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16, 14, 0f, 0f, 0, default(Color), 1f);
                return;
            }
            if (typeCache == 112 && this._rand.Next(700) == 0)
            {
                Dust.NewDust(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16, 14, 0f, 0f, 0, default(Color), 1f);
                return;
            }
            if ((typeCache == 31 || typeCache == 696) && this._rand.Next(20) == 0)
            {
                if (tileFrameX >= 36)
                {
                    int num45 = Dust.NewDust(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16, 5, 0f, 0f, 100, default(Color), 1f);
                    this._dust[num45].velocity.Y = 0f;
                    Dust dust25 = this._dust[num45];
                    dust25.velocity.X = dust25.velocity.X * 0.3f;
                    return;
                }
                Dust.NewDust(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16, 14, 0f, 0f, 100, default(Color), 1f);
                return;
            }
            else if ((typeCache == 26 || typeCache == 695) && this._rand.Next(20) == 0)
            {
                if (tileFrameX >= 54)
                {
                    int num46 = Dust.NewDust(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16, 5, 0f, 0f, 100, default(Color), 1f);
                    this._dust[num46].scale = 1.5f;
                    this._dust[num46].noGravity = true;
                    this._dust[num46].velocity *= 0.75f;
                    return;
                }
                Dust.NewDust(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16, 14, 0f, 0f, 100, default(Color), 1f);
                return;
            }
            else
            {
                if ((typeCache == 71 || typeCache == 72) && tileCache.color() == 0 && this._rand.Next(500) == 0)
                {
                    Dust.NewDust(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16, 41, 0f, 0f, 250, default(Color), 0.8f);
                    return;
                }
                if ((typeCache == 17 || typeCache == 77 || typeCache == 133) && this._rand.Next(40) == 0)
                {
                    if ((tileFrameX == 18) & (tileFrameY == 18))
                    {
                        int num47 = Dust.NewDust(new Vector2((float)(i * 16 - 4), (float)(j * 16 - 6)), 8, 6, 6, 0f, 0f, 100, default(Color), 1f);
                        if (this._rand.Next(3) != 0)
{
                            this._dust[num47].noGravity = true;
                            return;
                        }
                    }
                }
                else if (typeCache == 405 && this._rand.Next(20) == 0)
                {
                    if ((tileFrameX == 18) & (tileFrameY == 18))
                    {
                        int num48 = Dust.NewDust(new Vector2((float)(i * 16 - 4), (float)(j * 16 - 6)), 24, 10, 6, 0f, 0f, 100, default(Color), 1f);
                        if (this._rand.Next(5) != 0)
{
                            this._dust[num48].noGravity = true;
                            return;
                        }
                    }
                }
                else if (typeCache == 37 && this._rand.Next(250) == 0)
                {
                    int num49 = Dust.NewDust(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16, 6, 0f, 0f, 0, default(Color), (float)this._rand.Next(3));
                    if (this._dust[num49].scale > 1f)
                    {
                        this._dust[num49].noGravity = true;
                        return;
                    }
                }
                else
                {
                    if ((typeCache == 58 || typeCache == 76 || typeCache == 684) && this._rand.Next(250) == 0)
                    {
                        int num50 = Dust.NewDust(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16, 6, 0f, 0f, 0, default(Color), (float)this._rand.Next(3));
                        if (this._dust[num50].scale > 1f)
{
                            this._dust[num50].noGravity = true;
                        }
                        this._dust[num50].noLight = true;
                        return;
                    }
                    if (typeCache == 61 || typeCache == 703)
                    {
                        if (tileFrameX == 144 && this._rand.Next(60) == 0)
{
                            int num51 = Dust.NewDust(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16, 44, 0f, 0f, 250, default(Color), 0.4f);
                            this._dust[num51].fadeIn = 0.7f;
                            return;
                        }
                    }
                    else if (Main.tileShine[(int)typeCache] > 0)
                    {
                        if (tileLight.R > 20 || tileLight.B > 20 || tileLight.G > 20)
{
                            int num52 = (int)tileLight.R;
                            if ((int)tileLight.G > num52)
{
                                num52 = (int)tileLight.G;
                            }
                            if ((int)tileLight.B > num52)
{
                                num52 = (int)tileLight.B;
                            }
                            num52 /= 30;
                            if (this._rand.Next(Main.tileShine[(int)typeCache]) < num52 && ((typeCache != 21 && typeCache != 441) || (tileFrameX >= 36 && tileFrameX < 180) || (tileFrameX >= 396 && tileFrameX <= 409)) && ((typeCache != 467 && typeCache != 468) || (tileFrameX >= 144 && tileFrameX < 180)))
{
                                Color white = Color.White;
                                if (typeCache == 617)
{
                                    int num53 = i;
                                    int num54 = j;
                                    WorldGen.GetTopLeftAndStyles(ref num53, ref num54, 3, 4, 18, 18);
                                    int num55 = num54;
                                    Tile tile = Main.tile[num53 + 1, num54 + 1];
                                    if (!this.IsVisible(tile))
{
                                        num55 = num54 + 3;
                                    }
                                    if (j >= num55)
{
                                        int num56 = Dust.NewDust(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16, 43, 0f, 0f, 254, white, 0.5f);
                                        this._dust[num56].velocity *= 0f;
                                        return;
                                    }
                                }
                                else
{
                                    if (typeCache == 178)
{
                                        int num57 = (int)(tileFrameX / 18);
                                        if (num57 == 0)
{
                                            white = new Color(255, 0, 255, 255);
                                        }
                                        else if (num57 == 1)
{
                                            white = new Color(255, 255, 0, 255);
                                        }
                                        else if (num57 == 2)
{
                                            white = new Color(0, 0, 255, 255);
                                        }
                                        else if (num57 == 3)
{
                                            white = new Color(0, 255, 0, 255);
                                        }
                                        else if (num57 == 4)
{
                                            white = new Color(255, 0, 0, 255);
                                        }
                                        else if (num57 == 5)
{
                                            white = new Color(255, 255, 255, 255);
                                        }
                                        else if (num57 == 6)
{
                                            white = new Color(255, 255, 0, 255);
                                        }
                                        int num58 = Dust.NewDust(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16, 43, 0f, 0f, 254, white, 0.5f);
                                        this._dust[num58].velocity *= 0f;
                                        return;
                                    }
                                    if (typeCache == 63)
{
                                        white = new Color(0, 0, 255, 255);
                                    }
                                    if (typeCache == 64)
{
                                        white = new Color(255, 0, 0, 255);
                                    }
                                    if (typeCache == 65)
{
                                        white = new Color(0, 255, 0, 255);
                                    }
                                    if (typeCache == 66)
{
                                        white = new Color(255, 255, 0, 255);
                                    }
                                    if (typeCache == 67)
{
                                        white = new Color(255, 0, 255, 255);
                                    }
                                    if (typeCache == 68)
{
                                        white = new Color(255, 255, 255, 255);
                                    }
                                    if (typeCache == 566)
{
                                        white = new Color(255, 255, 0, 255);
                                    }
                                    if (typeCache == 12 || typeCache == 665)
{
                                        white = new Color(255, 0, 0, 255);
                                    }
                                    if (typeCache == 639)
{
                                        white = new Color(0, 0, 255, 255);
                                    }
                                    if (typeCache == 204)
{
                                        white = new Color(255, 0, 0, 255);
                                    }
                                    if (typeCache == 211)
{
                                        white = new Color(50, 255, 100, 255);
                                    }
                                    int num59 = Dust.NewDust(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16, 43, 0f, 0f, 254, white, 0.5f);
                                    this._dust[num59].velocity *= 0f;
                                    return;
                                }
                            }
                        }
                    }
                    else if (Main.tileSolid[(int)tileCache.type] && Main.shimmerAlpha > 0f && (tileLight.R > 20 || tileLight.B > 20 || tileLight.G > 20))
                    {
                        int num60 = (int)tileLight.R;
                        if ((int)tileLight.G > num60)
{
                            num60 = (int)tileLight.G;
                        }
                        if ((int)tileLight.B > num60)
{
                            num60 = (int)tileLight.B;
                        }
                        int num61 = 500;
                        if ((float)this._rand.Next(num61) < 2f * Main.shimmerAlpha)
{
                            Color white2 = Color.White;
                            float num62 = ((float)num60 / 255f + 1f) / 2f;
                            int num63 = Dust.NewDust(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16, 43, 0f, 0f, 254, white2, num62);
                            this._dust[num63].velocity *= 0f;
                        }
                    }
                }
                return;
            }
        }
References Terraria.GameContent.Drawing.TileDrawing._dust, Terraria.GameContent.Drawing.TileDrawing._gore, Terraria.GameContent.Drawing.TileDrawing._leafFrequency, Terraria.GameContent.Drawing.TileDrawing._rand, Terraria.GameContent.Drawing.TileDrawing._windGrid, System.Math.Abs(), Terraria.WorldGen.ActiveAndWalkableTile(), Terraria.ID.WallID.Sets.AllowsWind, Terraria.Dust.alpha, Terraria.WorldGen.AnyLiquidAt(), Microsoft.Xna.Framework.Color.B, Microsoft.Xna.Framework.MathHelper.Clamp(), Microsoft.Xna.Framework.Graphics.Color, Terraria.Dust.color, Terraria.Tile.color(), Terraria.Main.dayTime, Terraria.Main.DiscoB, Terraria.Main.DiscoG, Terraria.Main.DiscoR, Terraria.ID.TorchID.Dust, Terraria.Main.dust, Terraria.GameContent.Drawing.TileDrawing.EmitAlchemyHerbParticles(), Terraria.GameContent.Drawing.TileDrawing.EmitLivingTreeLeaf(), Terraria.Dust.fadeIn, Terraria.Tile.frameX, Terraria.Tile.frameY, Microsoft.Xna.Framework.Color.G, Terraria.Utils.GetLerpValue(), Terraria.WorldGen.GetTopLeftAndStyles(), Terraria.GameContent.Drawing.WindGrid.GetWindTime(), Terraria.Main.gore, int, Terraria.WorldGen.IsAlchemyPlantHarvestable(), Terraria.GameContent.Drawing.TileDrawing.IsVisible(), Terraria.WorldGen.KillTile_MakeTileDust(), Terraria.Tile.liquid, Terraria.ID.TileID.Sets.MakesRubbleDust, Terraria.Main.myPlayer, Terraria.Dust.NewDust(), Terraria.Dust.NewDustDirect(), Terraria.Gore.NewGore(), Terraria.Gore.NewGorePerfect(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Terraria.Dust.noLight, Terraria.Main.player, Microsoft.Xna.Framework.Graphics.Point, Terraria.Gore.position, Microsoft.Xna.Framework.Color.R, Terraria.Main.rand, Terraria.GameContent.Drawing.ParticleOrchestrator.RequestParticleSpawn(), Terraria.Player.RollLuck(), Terraria.Dust.scale, Terraria.Gore.scale, Terraria.Main.shimmerAlpha, Terraria.WorldGen.SolidTile3(), Terraria.ID.TileID.Sets.SpawnsNatureFlies, Terraria.Main.tile, Terraria.Main.tileFrame, Terraria.Main.tileShine, Terraria.Main.tileSolid, Terraria.Main.timeForVisualEffects, Terraria.Tile.type, Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Dust.velocity, Terraria.Gore.velocity, Terraria.Tile.wall, Microsoft.Xna.Framework.Color.White, Terraria.Main.WindForVisuals, Terraria.Main.worldSurface, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.Drawing.TileDrawing.DrawAnyDirectionalGrass(), Terraria.GameContent.Drawing.TileDrawing.DrawGrass(), Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileGrassInWind(), Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileVinesInWind(), and Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile().