Terraria Decompiled: Terraria.GameContent.Drawing.TileDrawing.DrawTiles_GetLightOverride
DrawTiles_GetLightOverride()
Color Terraria.GameContent.Drawing.TileDrawing.DrawTiles_GetLightOverride (int j, int i, Tile tileCache, ushort typeCache, short tileFrameX, short tileFrameY, Color tileLight) inline private
Definition at line 7876 of file TileDrawing.cs.
        {
            if (tileCache.fullbrightBlock())
            {
                return Color.White;
            }
            if (typeCache > 84)
            {
                if (typeCache <= 541)
                {
                    if (typeCache - 481 <= 2)
                    {
                        float num = 1f + (float)Math.Sin((double)(Main.GlobalTimeWrappedHourly / 1.5f * 6.2831855f)) * 0.15f;
                        byte a = tileLight.A;
                        tileLight *= num;
                        tileLight.A = a;
                        return tileLight;
                    }
                    if (typeCache != 541)
                    {
                        return tileLight;
                    }
                }
                else if (typeCache != 631)
                {
                    if (typeCache != 703)
                    {
                        return tileLight;
                    }
                    goto IL_0140;
                }
                return Color.White;
            }
            if (typeCache <= 61)
            {
                if (typeCache != 19)
                {
                    if (typeCache != 61)
                    {
                        return tileLight;
                    }
                }
                else
                {
                    if (tileFrameY / 18 == 48)
                    {
                        return Color.White;
                    }
                    return tileLight;
                }
            }
            else if (typeCache != 83)
            {
                if (typeCache != 84)
                {
                    return tileLight;
                }
                if (tileFrameX / 18 != 6)
                {
                    return tileLight;
                }
                byte b = (Main.mouseTextColor + tileLight.G * 2) / 3;
                byte b2 = (Main.mouseTextColor + tileLight.B * 2) / 3;
                if (b > tileLight.G)
                {
                    tileLight.G = b;
                }
                if (b2 > tileLight.B)
                {
                    tileLight.B = b2;
                    return tileLight;
                }
                return tileLight;
            }
            else
            {
                int num2 = (int)(tileFrameX / 18);
                if (WorldGen.IsAlchemyPlantHarvestable(num2, j) && num2 == 5)
                {
                    tileLight.A = Main.mouseTextColor / 2;
                    tileLight.G = Main.mouseTextColor;
                    tileLight.B = Main.mouseTextColor;
                    return tileLight;
                }
                return tileLight;
            }
            IL_0140:
            if (tileFrameX == 144)
            {
                tileLight.A = (tileLight.R = (tileLight.G = (tileLight.B = (byte)(245f - (float)Main.mouseTextColor * 1.5f))));
            }
            return tileLight;
        }
References Microsoft.Xna.Framework.Color.A, Microsoft.Xna.Framework.Color.B, Terraria.Tile.fullbrightBlock(), Microsoft.Xna.Framework.Color.G, int, Terraria.WorldGen.IsAlchemyPlantHarvestable(), Terraria.Main.mouseTextColor, System.Math.Sin(), and Microsoft.Xna.Framework.Color.White.
Referenced by Terraria.GameContent.Drawing.TileDrawing.DrawAnyDirectionalGrass(), Terraria.GameContent.Drawing.TileDrawing.DrawGrass(), Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileGrassInWind(), Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileVinesInWind(), and Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile().