Terraria Decompiled: Terraria.GameContent.Drawing.TileDrawing.GetHighestWindGridPushComplex
GetHighestWindGridPushComplex()
float Terraria.GameContent.Drawing.TileDrawing.GetHighestWindGridPushComplex (int topLeftX, int topLeftY, int sizeX, int sizeY, int totalPushTime, float pushForcePerFrame, int loops, bool swapLoopDir) inline private
Definition at line 10946 of file TileDrawing.cs.
        {
            float num = 0f;
            int num2 = int.MaxValue;
            for (int i = 0; i < 1; i++)
            {
                for (int j = 0; j < sizeY; j++)
                {
                    int num3;
                    int num4;
                    int num5;
                    this._windGrid.GetWindTime(topLeftX + i + sizeX / 2, topLeftY + j, totalPushTime, out num3, out num4, out num5);
                    float windGridPushComplex = this.GetWindGridPushComplex(topLeftX + i, topLeftY + j, totalPushTime, pushForcePerFrame, loops, swapLoopDir);
                    if (num3 < num2 && num3 != 0)
                    {
                        num = windGridPushComplex;
                        num2 = num3;
                    }
                }
            }
            return num;
        }
References Terraria.GameContent.Drawing.TileDrawing._windGrid, Terraria.GameContent.Drawing.TileDrawing.GetWindGridPushComplex(), and Terraria.GameContent.Drawing.WindGrid.GetWindTime().
Referenced by Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileVinesInWind().