Terraria Decompiled: Terraria.GameContent.Drawing.TileDrawing.AddSpecialPoint
AddSpecialPoint()
void Terraria.GameContent.Drawing.TileDrawing.AddSpecialPoint (int x, int y, TileDrawing::TileCounterType type) inline private
Definition at line 24 of file TileDrawing.cs.
        {
            Point[] array = this._specialPositions[(int)type];
            int[] specialsCount = this._specialsCount;
            int num = specialsCount[(int)type];
            specialsCount[(int)type] = num + 1;
            array[num] = new Point(x, y);
        }
References Terraria.GameContent.Drawing.TileDrawing._specialPositions, Terraria.GameContent.Drawing.TileDrawing._specialsCount, System.array, int, and Microsoft.Xna.Framework.Graphics.Point.
Referenced by Terraria.GameContent.Drawing.TileDrawing.CacheSpecialDraws_Part1(), Terraria.GameContent.Drawing.TileDrawing.CrawlToBottomOfReverseVineAndAddSpecialPoint(), Terraria.GameContent.Drawing.TileDrawing.CrawlToTopOfVineAndAddSpecialPoint(), and Terraria.GameContent.Drawing.TileDrawing.Draw().