Terraria Decompiled: Terraria.GameContent.Drawing.TileDrawing.DistToWanderingCircle
DistToWanderingCircle()
static float Terraria.GameContent.Drawing.TileDrawing.DistToWanderingCircle (Point pos, int gridSize, float wanderDist, float cyclesPerTick, uint seed) inline static private
Definition at line 976 of file TileDrawing.cs.
        {
            Point point = new Point(pos.X / gridSize, pos.Y / gridSize);
            Vector2 vector = new Vector2(((float)point.X + 0.5f) * (float)gridSize, ((float)point.Y + 0.5f) * (float)gridSize);
            float num = (float)Main.timeForVisualEffects;
            uint num2 = (TileDrawing.Hash((uint)point.X) ^ TileDrawing.Hash2((uint)point.Y) ^ seed) & 16777215U;
            uint num3 = (TileDrawing.Hash2((uint)point.X) ^ TileDrawing.Hash((uint)point.Y) ^ seed) & 16777215U;
            vector.X += TileDrawing.LinearNoise((num2 + num) * cyclesPerTick) * wanderDist;
            vector.Y += TileDrawing.LinearNoise((num3 + num) * cyclesPerTick) * wanderDist;
            return Vector2.Distance(pos.ToVector2(), vector);
        }
References Microsoft.Xna.Framework.Vector2.Distance(), Terraria.GameContent.Drawing.TileDrawing.Hash(), Terraria.GameContent.Drawing.TileDrawing.Hash2(), Terraria.GameContent.Drawing.TileDrawing.LinearNoise(), Microsoft.Xna.Framework.Graphics.Point, Terraria.Main.timeForVisualEffects, System.U, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.Drawing.TileDrawing.LavaLightA().