Terraria Decompiled: Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileGrass
DrawMultiTileGrass()
void Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileGrass () inline private
Definition at line 10274 of file TileDrawing.cs.
        {
            Vector2 unscaledPosition = Main.Camera.UnscaledPosition;
            Vector2 zero = Vector2.Zero;
            int num = 2;
            int num2 = this._specialsCount[num];
            for (int i = 0; i < num2; i++)
            {
                Point point = this._specialPositions[num][i];
                int x = point.X;
                int num3 = point.Y;
                int num4 = 1;
                int num5 = 1;
                Tile tile = Main.tile[x, num3];
                if (tile != null && tile.active())
                {
                    ushort type = Main.tile[x, num3].type;
                    if (type <= 485)
                    {
                        if (type <= 233)
{
                            if (type != 27)
{
                                if (type == 233)
{
                                    if (Main.tile[x, num3].frameY == 0)
{
                                        num4 = 3;
                                    }
                                    else
{
                                        num4 = 2;
                                    }
                                    num5 = 2;
                                }
                            }
                            else
{
                                num4 = 2;
                                num5 = 5;
                            }
                        }
                        else
{
                            if (type == 236 || type == 238)
{
                                goto IL_016F;
                            }
                            if (type == 485)
{
                                goto IL_01A1;
                            }
                        }
                    }
                    else
                    {
                        if (type <= 651)
{
                            switch (type)
{
                            case 489:
                                num4 = 2;
                                num5 = 3;
                                goto IL_01D1;
                            case 490:
                                goto IL_01A1;
                            case 491:
                            case 492:
                                goto IL_01D1;
                            case 493:
                                num4 = 1;
                                num5 = 2;
                                goto IL_01D1;
                            default:
                                switch (type)
{
                                case 519:
                                    num4 = 1;
                                    num5 = this.ClimbCatTail(x, num3);
                                    num3 -= num5 - 1;
                                    goto IL_01D1;
                                case 520:
                                case 528:
                                case 529:
                                    goto IL_01D1;
                                case 521:
                                case 522:
                                case 523:
                                case 524:
                                case 525:
                                case 526:
                                case 527:
                                    goto IL_01A1;
                                case 530:
                                    break;
                                default:
                                    if (type != 651)
{
                                        goto IL_01D1;
                                    }
                                    break;
                                }
                                break;
                            }
                        }
                        else
{
                            if (type == 652)
{
                                goto IL_01A1;
                            }
                            if (type == 702)
{
                                goto IL_016F;
                            }
                            if (type != 705)
{
                                goto IL_01D1;
                            }
                        }
                        num4 = 3;
                        num5 = 2;
                    }
                    IL_01D1:
                    this.DrawMultiTileGrassInWind(unscaledPosition, zero, x, num3, num4, num5);
                    goto IL_01E1;
                    IL_016F:
                    num5 = (num4 = 2);
                    goto IL_01D1;
                    IL_01A1:
                    num4 = 2;
                    num5 = 2;
                    goto IL_01D1;
                }
                IL_01E1:;
            }
        }
References Terraria.GameContent.Drawing.TileDrawing._specialPositions, Terraria.GameContent.Drawing.TileDrawing._specialsCount, Terraria.Tile.active(), Terraria.Main.Camera, Terraria.GameContent.Drawing.TileDrawing.ClimbCatTail(), Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileGrassInWind(), Terraria.Tile.frameY, Terraria.Main.tile, Terraria.Tile.type, Terraria.Graphics.Camera.UnscaledPosition, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Point.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.Drawing.TileDrawing.PostDrawTiles().