Terraria Decompiled: Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile
DrawSingleTile()
void Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile (Vector2 screenPosition, Vector2 screenOffset, int tileX, int tileY) inline private
Definition at line 1006 of file TileDrawing.cs.
        {
            TileDrawInfo tileDrawInfo = new TileDrawInfo();
            tileDrawInfo.tileCache = Main.tile[tileX, tileY];
            tileDrawInfo.typeCache = tileDrawInfo.tileCache.type;
            tileDrawInfo.tileFrameX = tileDrawInfo.tileCache.frameX;
            tileDrawInfo.tileFrameY = tileDrawInfo.tileCache.frameY;
            tileDrawInfo.tileLight = Lighting.GetColor(tileX, tileY);
            if (tileDrawInfo.tileCache.liquid > 0 && tileDrawInfo.tileCache.type == 518)
            {
                return;
            }
            this.GetTileDrawData(tileX, tileY, tileDrawInfo.tileCache, tileDrawInfo.typeCache, ref tileDrawInfo.tileFrameX, ref tileDrawInfo.tileFrameY, out tileDrawInfo.tileWidth, out tileDrawInfo.tileHeight, out tileDrawInfo.tileTop, out tileDrawInfo.halfBrickHeight, out tileDrawInfo.addFrX, out tileDrawInfo.addFrY, out tileDrawInfo.tileSpriteEffect, out tileDrawInfo.glowTexture, out tileDrawInfo.glowSourceRect, out tileDrawInfo.glowColor);
            if (tileDrawInfo.tileTop < 0)
            {
                Main.tileBatch.SetLayer(TileDrawing.Layer_OverTiles, 0);
            }
            else if (tileDrawInfo.tileTop + tileDrawInfo.tileHeight <= 16)
            {
                Main.tileBatch.SetLayer(TileDrawing.Layer_Tiles, 0);
            }
            else
            {
                Main.tileBatch.SetLayer(TileDrawing.Layer_BehindTiles, 0);
            }
            tileDrawInfo.drawTexture = this.GetTileDrawTexture(tileDrawInfo.tileCache, tileX, tileY);
            Texture2D texture2D = null;
            Rectangle empty = Rectangle.Empty;
            Color transparent = Color.Transparent;
            if (TileID.Sets.HasOutlines[(int)tileDrawInfo.typeCache])
            {
                this.GetTileOutlineInfo(tileX, tileY, tileDrawInfo.typeCache, ref tileDrawInfo.tileLight, ref texture2D, ref transparent);
            }
            if (this._perspectivePlayer.dangerSense && TileDrawing.IsTileDangerous(this._perspectivePlayer, tileDrawInfo.tileCache, tileDrawInfo.typeCache))
            {
                if (tileDrawInfo.tileLight.R < 255)
                {
                    tileDrawInfo.tileLight.R = byte.MaxValue;
                }
                if (tileDrawInfo.tileLight.G < 50)
                {
                    tileDrawInfo.tileLight.G = 50;
                }
                if (tileDrawInfo.tileLight.B < 50)
                {
                    tileDrawInfo.tileLight.B = 50;
                }
                if (this._isActiveAndNotPaused && this._rand.Next(30) == 0)
                {
                    int num = Dust.NewDust(new Vector2((float)(tileX * 16), (float)(tileY * 16)), 16, 16, 60, 0f, 0f, 100, default(Color), 0.3f);
                    this._dust[num].fadeIn = 1f;
                    this._dust[num].velocity *= 0.1f;
                    this._dust[num].noLight = true;
                    this._dust[num].noGravity = true;
                }
            }
            if (this._perspectivePlayer.findTreasure && Main.IsTileSpelunkable(tileDrawInfo.typeCache, tileDrawInfo.tileFrameX, tileDrawInfo.tileFrameY))
            {
                if (tileDrawInfo.tileLight.R < 200)
                {
                    tileDrawInfo.tileLight.R = 200;
                }
                if (tileDrawInfo.tileLight.G < 170)
                {
                    tileDrawInfo.tileLight.G = 170;
                }
                if (this._isActiveAndNotPaused && this._rand.Next(60) == 0)
                {
                    int num2 = Dust.NewDust(new Vector2((float)(tileX * 16), (float)(tileY * 16)), 16, 16, 204, 0f, 0f, 150, default(Color), 0.3f);
                    this._dust[num2].fadeIn = 1f;
                    this._dust[num2].velocity *= 0.1f;
                    this._dust[num2].noLight = true;
                }
            }
            if (this._perspectivePlayer.biomeSight)
            {
                Color white = Color.White;
                if (Main.IsTileBiomeSightable(tileDrawInfo.typeCache, tileDrawInfo.tileFrameX, tileDrawInfo.tileFrameY, ref white))
                {
                    if (tileDrawInfo.tileLight.R < white.R)
                    {
                        tileDrawInfo.tileLight.R = white.R;
                    }
                    if (tileDrawInfo.tileLight.G < white.G)
                    {
                        tileDrawInfo.tileLight.G = white.G;
                    }
                    if (tileDrawInfo.tileLight.B < white.B)
                    {
                        tileDrawInfo.tileLight.B = white.B;
                    }
                    if (this._isActiveAndNotPaused && this._rand.Next(480) == 0)
                    {
                        Color color = white;
                        int num3 = Dust.NewDust(new Vector2((float)(tileX * 16), (float)(tileY * 16)), 16, 16, 267, 0f, 0f, 150, color, 0.3f);
                        this._dust[num3].noGravity = true;
                        this._dust[num3].fadeIn = 1f;
                        this._dust[num3].velocity *= 0.1f;
                        this._dust[num3].noLightEmittance = true;
                    }
                }
            }
            if (this._isActiveAndNotPaused)
            {
                if (!Lighting.UpdateEveryFrame || new FastRandom(Main.TileFrameSeed).WithModifier(tileX, tileY).Next(4) == 0)
                {
                    this.DrawTiles_EmitParticles(tileY, tileX, tileDrawInfo.tileCache, tileDrawInfo.typeCache, tileDrawInfo.tileFrameX, tileDrawInfo.tileFrameY, tileDrawInfo.tileLight);
                }
                tileDrawInfo.tileLight = this.DrawTiles_GetLightOverride(tileY, tileX, tileDrawInfo.tileCache, tileDrawInfo.typeCache, tileDrawInfo.tileFrameX, tileDrawInfo.tileFrameY, tileDrawInfo.tileLight);
            }
            bool flag = false;
            if (tileDrawInfo.glowTexture != null || Main.tileGlowMask[(int)tileDrawInfo.typeCache] != -1 || Main.tileFlame[(int)tileDrawInfo.typeCache])
            {
                flag = true;
            }
            if (tileDrawInfo.tileLight.R >= 1 || tileDrawInfo.tileLight.G >= 1 || tileDrawInfo.tileLight.B >= 1 || TileID.Sets.IgnoreDrawLightConditions[(int)tileDrawInfo.typeCache])
            {
                flag = true;
            }
            if (tileDrawInfo.tileCache.wall > 0 && (tileDrawInfo.tileCache.wall == 318 || tileDrawInfo.tileCache.fullbrightWall()))
            {
                flag = true;
            }
            bool flag2 = this.IsVisible(tileDrawInfo.tileCache);
            if (!flag2)
            {
                flag = false;
            }
            if (!flag && flag2 && TileDrawingBase.DrawOwnBlacks)
            {
                this.drawBlackHelper.DrawBlack(tileX, tileY);
            }
            this.CacheSpecialDraws_Part1(tileX, tileY, (int)tileDrawInfo.typeCache, (int)tileDrawInfo.tileFrameX, (int)tileDrawInfo.tileFrameY, !flag);
            this.CacheSpecialDraws_Part2(tileX, tileY, tileDrawInfo);
            if (tileDrawInfo.typeCache == 72 && tileDrawInfo.tileFrameX >= 36)
            {
                int num4 = 0;
                if (tileDrawInfo.tileFrameY == 18)
                {
                    num4 = 1;
                }
                else if (tileDrawInfo.tileFrameY == 36)
                {
                    num4 = 2;
                }
                Main.tileBatch.Draw(TextureAssets.ShroomCap.Value, new Vector2((float)(tileX * 16 - (int)screenPosition.X - 22), (float)(tileY * 16 - (int)screenPosition.Y - 26)) + screenOffset, new Rectangle?(new Rectangle(num4 * 62, 0, 60, 42)), Lighting.GetColor(tileX, tileY), TileDrawing._zero, 1f, tileDrawInfo.tileSpriteEffect);
            }
            Rectangle rectangle = new Rectangle((int)tileDrawInfo.tileFrameX + tileDrawInfo.addFrX, (int)tileDrawInfo.tileFrameY + tileDrawInfo.addFrY, tileDrawInfo.tileWidth, tileDrawInfo.tileHeight - tileDrawInfo.halfBrickHeight);
            float num5 = ((float)tileDrawInfo.tileWidth - 16f) / 2f;
            if (tileDrawInfo.typeCache >= 0 && TileID.Sets.DoNotAdjustDrawPositionBasedOnTileWidth[(int)tileDrawInfo.typeCache])
            {
                num5 = 0f;
            }
            Vector2 vector = new Vector2((float)(tileX * 16 - (int)screenPosition.X) - num5, (float)(tileY * 16 - (int)screenPosition.Y + tileDrawInfo.tileTop + tileDrawInfo.halfBrickHeight)) + screenOffset;
            if (flag)
            {
                tileDrawInfo.colorTint = Color.White;
                tileDrawInfo.finalColor = TileDrawing.GetFinalLight(tileDrawInfo.tileCache, tileDrawInfo.typeCache, tileDrawInfo.tileLight, tileDrawInfo.colorTint);
                ushort num6 = tileDrawInfo.typeCache;
                if (num6 <= 272)
                {
                    if (num6 <= 114)
                    {
                        if (num6 <= 80)
{
                            if (num6 != 51)
{
                                if (num6 != 80)
{
                                    goto IL_0D16;
                                }
                                bool flag3;
                                bool flag4;
                                bool flag5;
                                WorldGen.GetCactusType(tileX, tileY, (int)tileDrawInfo.tileFrameX, (int)tileDrawInfo.tileFrameY, out flag3, out flag4, out flag5);
                                if (flag3)
{
                                    rectangle.Y += 54;
                                }
                                if (flag4)
{
                                    rectangle.Y += 108;
                                }
                                if (flag5)
{
                                    rectangle.Y += 162;
                                    goto IL_0D16;
                                }
                                goto IL_0D16;
                            }
                        }
                        else
{
                            if (num6 == 83)
{
                                tileDrawInfo.drawTexture = this.GetTileDrawTexture(tileDrawInfo.tileCache, tileX, tileY);
                                goto IL_0D16;
                            }
                            if (num6 != 114)
{
                                goto IL_0D16;
                            }
                            if (tileDrawInfo.tileFrameY > 0)
{
                                rectangle.Height += 2;
                                goto IL_0D16;
                            }
                            goto IL_0D16;
                        }
                    }
                    else if (num6 <= 136)
                    {
                        if (num6 != 129)
{
                            if (num6 != 136)
{
                                goto IL_0D16;
                            }
                            int num7 = (int)(tileDrawInfo.tileFrameX / 18);
                            if (num7 == 1)
{
                                vector.X += -2f;
                                goto IL_0D16;
                            }
                            if (num7 != 2)
{
                                goto IL_0D16;
                            }
                            vector.X += 2f;
                            goto IL_0D16;
                        }
                        else
{
                            tileDrawInfo.finalColor = new Color(255, 255, 255, 100);
                            int num8 = 2;
                            if (tileDrawInfo.tileFrameX >= 324)
{
                                tileDrawInfo.finalColor = Color.Transparent;
                            }
                            if (tileDrawInfo.tileFrameY < 36)
{
                                vector.Y += (float)(num8 * (tileDrawInfo.tileFrameY == 0).ToDirectionInt());
                                goto IL_0D16;
                            }
                            vector.X += (float)(num8 * (tileDrawInfo.tileFrameY == 36).ToDirectionInt());
                            goto IL_0D16;
                        }
                    }
                    else
                    {
                        if (num6 == 160)
{
                            goto IL_0A9A;
                        }
                        if (num6 != 272)
{
                            goto IL_0D16;
                        }
                        int num9 = Main.tileFrame[(int)tileDrawInfo.typeCache];
                        num9 += tileX % 2;
                        num9 += tileY % 2;
                        num9 += tileX % 3;
                        num9 += tileY % 3;
                        num9 %= 2;
                        num9 *= 90;
                        tileDrawInfo.addFrY += num9;
                        rectangle.Y += num9;
                        goto IL_0D16;
                    }
                }
                else if (num6 <= 697)
                {
                    if (num6 <= 442)
                    {
                        if (num6 != 323)
{
                            if (num6 != 442)
{
                                goto IL_0D16;
                            }
                            int num7 = (int)(tileDrawInfo.tileFrameX / 22);
                            if (num7 == 3)
{
                                vector.X += 2f;
                                goto IL_0D16;
                            }
                            goto IL_0D16;
                        }
                        else
{
                            if (tileDrawInfo.tileCache.frameX <= 132 && tileDrawInfo.tileCache.frameX >= 88)
{
                                return;
                            }
                            vector.X += (float)tileDrawInfo.tileCache.frameY;
                            goto IL_0D16;
                        }
                    }
                    else
                    {
                        if (num6 == 692)
{
                            goto IL_0A9A;
                        }
                        if (num6 != 697)
{
                            goto IL_0D16;
                        }
                    }
                }
                else if (num6 <= 726)
                {
                    if (num6 - 723 > 1)
                    {
                        if (num6 != 726)
{
                            goto IL_0D16;
                        }
                        vector.X -= 2f;
                        switch (tileDrawInfo.tileCache.blockType())
{
                        case 2:
                            vector.X += 6f;
                            vector.Y += 2f;
                            goto IL_0D16;
                        case 3:
                            vector.X -= 6f;
                            vector.Y += 2f;
                            goto IL_0D16;
                        case 4:
                            vector.X += 6f;
                            goto IL_0D16;
                        case 5:
                            vector.X -= 6f;
                            goto IL_0D16;
                        default:
                            goto IL_0D16;
                        }
                    }
                    else
                    {
                        switch (tileDrawInfo.tileFrameX / 18)
{
                        case 0:
                            vector += new Vector2(0f, 2f);
                            goto IL_0D16;
                        case 1:
                            vector += new Vector2(0f, -2f);
                            goto IL_0D16;
                        case 2:
                            vector += new Vector2(-2f, 0f);
                            goto IL_0D16;
                        case 3:
                            vector += new Vector2(2f, 0f);
                            goto IL_0D16;
                        default:
                            goto IL_0D16;
                        }
                    }
                }
                else if (num6 != 751)
                {
                    if (num6 != 752)
                    {
                        goto IL_0D16;
                    }
                    if (tileDrawInfo.tileFrameX != 0 || tileDrawInfo.tileFrameY != 0)
                    {
                        return;
                    }
                    vector.X += 8f;
                    goto IL_0D16;
                }
                else
                {
                    if (tileDrawInfo.tileFrameX != 0 || tileDrawInfo.tileCache.frameY != 0)
                    {
                        return;
                    }
                    vector.X += 11f;
                    vector.Y -= 8f;
                    goto IL_0D16;
                }
                tileDrawInfo.finalColor = tileDrawInfo.tileLight * 0.5f;
                goto IL_0D16;
                IL_0A9A:
                Color color2 = new Color(Main.DiscoR, Main.DiscoG, Main.DiscoB, 255);
                if (tileDrawInfo.tileCache.inActive())
                {
                    color2 = tileDrawInfo.tileCache.actColor(color2);
                }
                tileDrawInfo.finalColor = color2;
                IL_0D16:
                if (tileDrawInfo.typeCache == 314)
                {
                    this.DrawTile_MinecartTrack(screenPosition, screenOffset, tileX, tileY, tileDrawInfo);
                }
                else if (tileDrawInfo.typeCache == 171)
                {
                    this.DrawXmasTree(screenPosition, screenOffset, tileX, tileY, tileDrawInfo);
                }
                else
                {
                    this.DrawBasicTile(screenPosition, screenOffset, tileX, tileY, tileDrawInfo, rectangle, vector);
                }
                if (Main.tileGlowMask[(int)tileDrawInfo.tileCache.type] != -1)
                {
                    short num10 = Main.tileGlowMask[(int)tileDrawInfo.tileCache.type];
                    if (TextureAssets.GlowMask.IndexInRange((int)num10))
                    {
                        tileDrawInfo.drawTexture = TextureAssets.GlowMask[(int)num10].Value;
                    }
                    double num11 = Main.timeForVisualEffects * 0.08;
                    Color color3 = Color.White;
                    bool flag6 = false;
                    num6 = tileDrawInfo.tileCache.type;
                    if (num6 <= 445)
                    {
                        if (num6 <= 370)
{
                            if (num6 <= 209)
{
                                if (num6 != 129)
{
                                    if (num6 != 209)
{
                                        goto IL_1334;
                                    }
                                    color3 = PortalHelper.GetPortalColor(Main.myPlayer, (tileDrawInfo.tileCache.frameX >= 288) ? 1 : 0);
                                    goto IL_1334;
                                }
                                else
{
                                    if (tileDrawInfo.tileFrameX < 324)
{
                                        flag6 = true;
                                        goto IL_1334;
                                    }
                                    tileDrawInfo.drawTexture = this.GetTileDrawTexture(tileDrawInfo.tileCache, tileX, tileY);
                                    color3 = Main.hslToRgb(0.7f + (float)Math.Sin((double)(6.2831855f * Main.GlobalTimeWrappedHourly * 0.16f + (float)tileX * 0.3f + (float)tileY * 0.7f)) * 0.16f, 1f, 0.5f, byte.MaxValue);
                                    color3.A /= 2;
                                    color3 *= 0.3f;
                                    int num12 = 72;
                                    for (float num13 = 0f; num13 < 6.2831855f; num13 += 1.5707964f)
{
                                        Main.tileBatch.Draw(tileDrawInfo.drawTexture, vector + num13.ToRotationVector2() * 2f, new Rectangle?(new Rectangle((int)tileDrawInfo.tileFrameX + tileDrawInfo.addFrX, (int)tileDrawInfo.tileFrameY + tileDrawInfo.addFrY + num12, tileDrawInfo.tileWidth, tileDrawInfo.tileHeight)), color3, Vector2.Zero, 1f, SpriteEffects.None);
                                    }
                                    color3 = new Color(255, 255, 255, 100);
                                    goto IL_1334;
                                }
                            }
                            else
{
                                if (num6 == 350)
{
                                    color3 = new Color(new Vector4((float)(-(float)Math.Cos(((int)(num11 / 6.283) % 3 == 1) ? num11 : 0.0) * 0.2 + 0.2)));
                                    goto IL_1334;
                                }
                                if (num6 != 370)
{
                                    goto IL_1334;
                                }
                            }
                        }
                        else if (num6 <= 390)
{
                            if (num6 == 381)
{
                                goto IL_103B;
                            }
                            if (num6 != 390)
{
                                goto IL_1334;
                            }
                        }
                        else
{
                            if (num6 == 391)
{
                                color3 = new Color(250, 250, 250, 200);
                                goto IL_1334;
                            }
                            if (num6 != 429 && num6 != 445)
{
                                goto IL_1334;
                            }
                            tileDrawInfo.drawTexture = this.GetTileDrawTexture(tileDrawInfo.tileCache, tileX, tileY);
                            tileDrawInfo.addFrY = 18;
                            goto IL_1334;
                        }
                        color3 = this._meteorGlow;
                        goto IL_1334;
                    }
                    if (num6 <= 667)
                    {
                        if (num6 <= 540)
{
                            if (num6 == 517)
{
                                goto IL_103B;
                            }
                            switch (num6)
{
                            case 534:
                            case 535:
                                goto IL_1048;
                            case 536:
                            case 537:
                                goto IL_1055;
                            case 538:
                                goto IL_1334;
                            case 539:
                            case 540:
                                goto IL_1062;
                            default:
                                goto IL_1334;
                            }
                        }
                        else
{
                            switch (num6)
{
                            case 625:
                            case 626:
                                goto IL_106F;
                            case 627:
                            case 628:
                                goto IL_107C;
                            case 629:
                            case 630:
                            case 631:
                            case 632:
                                goto IL_1334;
                            case 633:
                                color3 = Color.Lerp(Color.White, tileDrawInfo.finalColor, 0.75f);
                                goto IL_1334;
                            default:
                                if (num6 != 659 && num6 != 667)
{
                                    goto IL_1334;
                                }
                                break;
                            }
                        }
                    }
                    else if (num6 <= 708)
                    {
                        switch (num6)
{
                        case 687:
                            goto IL_103B;
                        case 688:
                            goto IL_1062;
                        case 689:
                            goto IL_1048;
                        case 690:
                            goto IL_1055;
                        case 691:
                            goto IL_106F;
                        case 692:
                            goto IL_107C;
                        case 693:
                        case 694:
                        case 695:
                        case 696:
                        case 697:
                        case 698:
                            goto IL_1334;
                        case 699:
                            color3 = Color.White;
                            goto IL_1334;
                        default:
                            if (num6 != 708)
{
                                goto IL_1334;
                            }
                            break;
                        }
                    }
                    else
                    {
                        if (num6 == 717)
{
                            float num14 = TileDrawing.LavaLightA(tileX, tileY);
                            color3 = new Color(num14, num14, num14, num14 / 2f);
                            goto IL_1334;
                        }
                        if (num6 == 718)
{
                            color3 = new Color(0, 0, 0, 0);
                            goto IL_1334;
                        }
                        if (num6 != 725)
{
                            goto IL_1334;
                        }
                        float opacity = Filters.Scene["Noir"].Opacity;
                        if (opacity > 0f && tileDrawInfo.tileFrameX % 36 == 0 && tileDrawInfo.tileFrameY == 54)
{
                            Vector2 vector2 = vector + new Vector2(16f, 24f);
                            SpriteEffects spriteEffects = ((tileDrawInfo.tileFrameX >= 36) ? SpriteEffects.FlipHorizontally : SpriteEffects.None);
                            color3 = new Color(255, 255, 255, 100) * opacity;
                            Main.tileBatch.Draw(tileDrawInfo.drawTexture, vector2, new Rectangle?(tileDrawInfo.drawTexture.Frame(1, 1, 0, 0, 0, 0)), color3, tileDrawInfo.drawTexture.Frame(1, 1, 0, 0, 0, 0).Center.ToVector2(), 1f, spriteEffects);
                        }
                        flag6 = true;
                        goto IL_1334;
                    }
                    color3 = LiquidRenderer.GetShimmerGlitterColor(true, (float)tileX, (float)tileY);
                    goto IL_1334;
                    IL_1048:
                    color3 = this._kryptonMossGlow;
                    goto IL_1334;
                    IL_1055:
                    color3 = this._xenonMossGlow;
                    goto IL_1334;
                    IL_1062:
                    color3 = this._argonMossGlow;
                    goto IL_1334;
                    IL_106F:
                    color3 = this._violetMossGlow;
                    goto IL_1334;
                    IL_107C:
                    color3 = new Color(Main.DiscoR, Main.DiscoG, Main.DiscoB);
                    goto IL_1334;
                    IL_103B:
                    color3 = this._lavaMossGlow;
                    IL_1334:
                    if (!flag6)
                    {
                        if (tileDrawInfo.tileCache.slope() == 0 && !tileDrawInfo.tileCache.halfBrick())
{
                            Main.tileBatch.Draw(tileDrawInfo.drawTexture, vector, new Rectangle?(new Rectangle((int)tileDrawInfo.tileFrameX + tileDrawInfo.addFrX, (int)tileDrawInfo.tileFrameY + tileDrawInfo.addFrY, tileDrawInfo.tileWidth, tileDrawInfo.tileHeight)), color3, Vector2.Zero, 1f, SpriteEffects.None);
                        }
                        else if (tileDrawInfo.tileCache.halfBrick())
{
                            Main.tileBatch.Draw(tileDrawInfo.drawTexture, vector, new Rectangle?(rectangle), color3, TileDrawing._zero, 1f, SpriteEffects.None);
                        }
                        else if (TileID.Sets.HasSlopeFrames[(int)tileDrawInfo.tileCache.type])
{
                            Main.tileBatch.Draw(tileDrawInfo.drawTexture, vector, new Rectangle?(new Rectangle((int)tileDrawInfo.tileFrameX + tileDrawInfo.addFrX, (int)tileDrawInfo.tileFrameY + tileDrawInfo.addFrY, 16, 16)), color3, TileDrawing._zero, 1f, tileDrawInfo.tileSpriteEffect);
                        }
                        else
{
                            int num15 = (int)tileDrawInfo.tileCache.slope();
                            int num16 = 2;
                            for (int i = 0; i < 8; i++)
{
                                int num17 = i * -2;
                                int num18 = 16 - i * 2;
                                int num19 = 16 - num18;
                                int num20;
                                switch (num15)
{
                                case 1:
                                    num17 = 0;
                                    num20 = i * 2;
                                    num18 = 14 - i * 2;
                                    num19 = 0;
                                    break;
                                case 2:
                                    num17 = 0;
                                    num20 = 16 - i * 2 - 2;
                                    num18 = 14 - i * 2;
                                    num19 = 0;
                                    break;
                                case 3:
                                    num20 = i * 2;
                                    break;
                                default:
                                    num20 = 16 - i * 2 - 2;
                                    break;
                                }
                                Main.tileBatch.Draw(tileDrawInfo.drawTexture, vector + new Vector2((float)num20, (float)(i * num16 + num17)), new Rectangle?(new Rectangle((int)tileDrawInfo.tileFrameX + tileDrawInfo.addFrX + num20, (int)tileDrawInfo.tileFrameY + tileDrawInfo.addFrY + num19, num16, num18)), color3, TileDrawing._zero, 1f, tileDrawInfo.tileSpriteEffect);
                            }
                            int num21 = ((num15 > 2) ? 0 : 14);
                            Main.tileBatch.Draw(tileDrawInfo.drawTexture, vector + new Vector2(0f, (float)num21), new Rectangle?(new Rectangle((int)tileDrawInfo.tileFrameX + tileDrawInfo.addFrX, (int)tileDrawInfo.tileFrameY + tileDrawInfo.addFrY + num21, 16, 2)), color3, TileDrawing._zero, 1f, tileDrawInfo.tileSpriteEffect);
                        }
                    }
                }
                if (tileDrawInfo.glowTexture != null)
                {
                    if (tileDrawInfo.typeCache == 412)
                    {
                        int num22 = Main.tileFrame[(int)tileDrawInfo.typeCache] / 60;
                        int num23 = (num22 + 1) % 4;
                        float num24 = (float)(Main.tileFrame[(int)tileDrawInfo.typeCache] % 60) / 60f;
                        Rectangle glowSourceRect = tileDrawInfo.glowSourceRect;
                        glowSourceRect.Y += num22 * 18 * 3;
                        Rectangle glowSourceRect2 = tileDrawInfo.glowSourceRect;
                        glowSourceRect2.Y += num23 * 18 * 3;
                        Vector2 vector3 = new Vector2((float)(tileX * 16 - (int)screenPosition.X) - ((float)tileDrawInfo.tileWidth - 16f) / 2f, (float)(tileY * 16 - (int)screenPosition.Y + tileDrawInfo.tileTop)) + screenOffset;
                        Main.tileBatch.Draw(tileDrawInfo.glowTexture, vector3, new Rectangle?(glowSourceRect), tileDrawInfo.glowColor * (1f - num24), TileDrawing._zero, 1f, tileDrawInfo.tileSpriteEffect);
                        Main.tileBatch.Draw(tileDrawInfo.glowTexture, vector3, new Rectangle?(glowSourceRect2), tileDrawInfo.glowColor * num24, TileDrawing._zero, 1f, tileDrawInfo.tileSpriteEffect);
                    }
                    else
                    {
                        Vector2 vector4 = new Vector2((float)(tileX * 16 - (int)screenPosition.X) - ((float)tileDrawInfo.tileWidth - 16f) / 2f, (float)(tileY * 16 - (int)screenPosition.Y + tileDrawInfo.tileTop)) + screenOffset;
                        if (TileID.Sets.Platforms[(int)tileDrawInfo.typeCache])
{
                            vector4 = vector;
                        }
                        Main.tileBatch.SetLayer(TileDrawing.Layer_Tiles, 1);
                        Main.tileBatch.Draw(tileDrawInfo.glowTexture, vector4, new Rectangle?(tileDrawInfo.glowSourceRect), tileDrawInfo.glowColor, TileDrawing._zero, 1f, tileDrawInfo.tileSpriteEffect);
                        if (TileID.Sets.Platforms[(int)tileDrawInfo.typeCache] && tileDrawInfo.tileCache.slope() != 0)
{
                            Tile tile = Main.tile[tileX, tileY + 1];
                            Tile tile2 = Main.tile[tileX - 1, tileY + 1];
                            Tile tile3 = Main.tile[tileX + 1, tileY + 1];
                            bool shouldShowInvisibleBlocks = this._shouldShowInvisibleBlocks;
                            if (tileDrawInfo.tileCache.slope() == 1 && tile3.active() && (shouldShowInvisibleBlocks || !tile3.invisibleBlock()) && Main.tileSolid[(int)tile3.type] && tile3.slope() != 2 && !tile3.halfBrick() && (!tile.active() || (!shouldShowInvisibleBlocks && tile.invisibleBlock()) || (tile.blockType() != 0 && tile.blockType() != 5) || !TileID.Sets.BlocksStairs[(int)tile.type]))
{
                                Rectangle glowSourceRect3 = tileDrawInfo.glowSourceRect;
                                if (TileID.Sets.Platforms[(int)tile3.type] && tile3.slope() == 0)
{
                                    glowSourceRect3.X = 324;
                                }
                                else
{
                                    glowSourceRect3.X = 198;
                                }
                                Main.tileBatch.SetLayer(TileDrawing.Layer_BehindTiles, 1);
                                Main.tileBatch.Draw(tileDrawInfo.glowTexture, vector4 + new Vector2(0f, 16f), new Rectangle?(glowSourceRect3), tileDrawInfo.glowColor, TileDrawing._zero, 1f, tileDrawInfo.tileSpriteEffect);
                            }
                            else if (tileDrawInfo.tileCache.slope() == 2 && tile2.active() && (shouldShowInvisibleBlocks || !tile2.invisibleBlock()) && Main.tileSolid[(int)tile2.type] && tile2.slope() != 1 && !tile2.halfBrick() && (!tile.active() || (!shouldShowInvisibleBlocks && tile.invisibleBlock()) || (tile.blockType() != 0 && tile.blockType() != 4) || !TileID.Sets.BlocksStairs[(int)tile.type]))
{
                                Rectangle glowSourceRect4 = tileDrawInfo.glowSourceRect;
                                if (TileID.Sets.Platforms[(int)tile2.type] && tile2.slope() == 0)
{
                                    glowSourceRect4.X = 306;
                                }
                                else
{
                                    glowSourceRect4.X = 162;
                                }
                                Main.tileBatch.SetLayer(TileDrawing.Layer_BehindTiles, 1);
                                Main.tileBatch.Draw(tileDrawInfo.glowTexture, vector4 + new Vector2(0f, 16f), new Rectangle?(glowSourceRect4), tileDrawInfo.glowColor, TileDrawing._zero, 1f, tileDrawInfo.tileSpriteEffect);
                            }
                        }
                    }
                }
                if (texture2D != null)
                {
                    empty = new Rectangle((int)tileDrawInfo.tileFrameX + tileDrawInfo.addFrX, (int)tileDrawInfo.tileFrameY + tileDrawInfo.addFrY, tileDrawInfo.tileWidth, tileDrawInfo.tileHeight);
                    int num25 = 0;
                    int num26 = 0;
                    Main.tileBatch.Draw(texture2D, new Vector2((float)(tileX * 16 - (int)screenPosition.X) - ((float)tileDrawInfo.tileWidth - 16f) / 2f + (float)num25, (float)(tileY * 16 - (int)screenPosition.Y + tileDrawInfo.tileTop + num26)) + screenOffset, new Rectangle?(empty), transparent, TileDrawing._zero, 1f, tileDrawInfo.tileSpriteEffect);
                }
            }
        }
References Terraria.GameContent.Drawing.TileDrawing._argonMossGlow, Terraria.GameContent.Drawing.TileDrawing._dust, Terraria.GameContent.Drawing.TileDrawing._isActiveAndNotPaused, Terraria.GameContent.Drawing.TileDrawing._kryptonMossGlow, Terraria.GameContent.Drawing.TileDrawing._lavaMossGlow, Terraria.GameContent.Drawing.TileDrawing._meteorGlow, Terraria.GameContent.Drawing.TileDrawing._perspectivePlayer, Terraria.GameContent.Drawing.TileDrawing._rand, Terraria.GameContent.Drawing.TileDrawing._shouldShowInvisibleBlocks, Terraria.GameContent.Drawing.TileDrawing._violetMossGlow, Terraria.GameContent.Drawing.TileDrawing._xenonMossGlow, Terraria.GameContent.Drawing.TileDrawing._zero, Terraria.Tile.actColor(), Terraria.Tile.active(), Terraria.DataStructures.TileDrawInfo.addFrX, Terraria.DataStructures.TileDrawInfo.addFrY, Microsoft.Xna.Framework.Color.B, Terraria.Player.biomeSight, Terraria.ID.TileID.Sets.BlocksStairs, Terraria.Tile.blockType(), Terraria.GameContent.Drawing.TileDrawing.CacheSpecialDraws_Part1(), Terraria.GameContent.Drawing.TileDrawing.CacheSpecialDraws_Part2(), Microsoft.Xna.Framework.Graphics.Color, Terraria.DataStructures.TileDrawInfo.colorTint, System.Math.Cos(), Terraria.Player.dangerSense, Terraria.Main.DiscoB, Terraria.Main.DiscoG, Terraria.Main.DiscoR, Terraria.ID.TileID.Sets.DoNotAdjustDrawPositionBasedOnTileWidth, Terraria.Graphics.TileBatch.Draw(), Terraria.GameContent.Drawing.TileDrawing.DrawBasicTile(), Terraria.GameContent.Drawing.DrawBlackHelper.DrawBlack(), Terraria.GameContent.Drawing.TileDrawing.drawBlackHelper, Terraria.GameContent.Drawing.TileDrawingBase.DrawOwnBlacks, Terraria.DataStructures.TileDrawInfo.drawTexture, Terraria.GameContent.Drawing.TileDrawing.DrawTile_MinecartTrack(), Terraria.GameContent.Drawing.TileDrawing.DrawTiles_EmitParticles(), Terraria.GameContent.Drawing.TileDrawing.DrawTiles_GetLightOverride(), Terraria.GameContent.Drawing.TileDrawing.DrawXmasTree(), Microsoft.Xna.Framework.Rectangle.Empty, Terraria.Dust.fadeIn, Terraria.DataStructures.TileDrawInfo.finalColor, Terraria.Player.findTreasure, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Tile.fullbrightWall(), Microsoft.Xna.Framework.Color.G, Terraria.WorldGen.GetCactusType(), Terraria.Lighting.GetColor(), Terraria.GameContent.Drawing.TileDrawing.GetFinalLight(), Terraria.GameContent.PortalHelper.GetPortalColor(), Terraria.GameContent.Liquid.LiquidRenderer.GetShimmerGlitterColor(), Terraria.GameContent.Drawing.TileDrawing.GetTileDrawData(), Terraria.GameContent.Drawing.TileDrawing.GetTileDrawTexture(), Terraria.GameContent.Drawing.TileDrawing.GetTileOutlineInfo(), Terraria.Main.GlobalTimeWrappedHourly, Terraria.DataStructures.TileDrawInfo.glowColor, Terraria.GameContent.TextureAssets.GlowMask, Terraria.DataStructures.TileDrawInfo.glowSourceRect, Terraria.DataStructures.TileDrawInfo.glowTexture, Terraria.Tile.halfBrick(), Terraria.DataStructures.TileDrawInfo.halfBrickHeight, Terraria.ID.TileID.Sets.HasOutlines, Terraria.ID.TileID.Sets.HasSlopeFrames, Terraria.Main.hslToRgb(), Terraria.ID.TileID.Sets.IgnoreDrawLightConditions, Terraria.Tile.inActive(), int, Terraria.Tile.invisibleBlock(), Terraria.Main.IsTileBiomeSightable(), Terraria.GameContent.Drawing.TileDrawing.IsTileDangerous(), Terraria.Main.IsTileSpelunkable(), Terraria.GameContent.Drawing.TileDrawing.IsVisible(), Terraria.GameContent.Drawing.TileDrawing.LavaLightA(), Terraria.GameContent.Drawing.TileDrawing.Layer_BehindTiles, Terraria.GameContent.Drawing.TileDrawing.Layer_OverTiles, Terraria.GameContent.Drawing.TileDrawing.Layer_Tiles, Microsoft.Xna.Framework.Color.Lerp(), Terraria.Tile.liquid, Terraria.Main.myPlayer, Terraria.Dust.NewDust(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Utilities.FastRandom.Next(), Terraria.Dust.noGravity, Terraria.Dust.noLight, Terraria.Dust.noLightEmittance, Terraria.ID.TileID.Sets.Platforms, Microsoft.Xna.Framework.Color.R, Terraria.Graphics.Effects.Filters.Scene, Terraria.Graphics.TileBatch.SetLayer(), Terraria.GameContent.TextureAssets.ShroomCap, System.Math.Sin(), Terraria.Tile.slope(), Terraria.Main.tile, Terraria.Main.tileBatch, Terraria.DataStructures.TileDrawInfo.tileCache, Terraria.Main.tileFlame, Terraria.Main.tileFrame, Terraria.Main.TileFrameSeed, Terraria.DataStructures.TileDrawInfo.tileFrameX, Terraria.DataStructures.TileDrawInfo.tileFrameY, Terraria.Main.tileGlowMask, Terraria.DataStructures.TileDrawInfo.tileHeight, Terraria.DataStructures.TileDrawInfo.tileLight, Terraria.Main.tileSolid, Terraria.DataStructures.TileDrawInfo.tileSpriteEffect, Terraria.DataStructures.TileDrawInfo.tileTop, Terraria.DataStructures.TileDrawInfo.tileWidth, Microsoft.Xna.Framework.Color.Transparent, Terraria.Tile.type, Terraria.DataStructures.TileDrawInfo.typeCache, Terraria.Lighting.UpdateEveryFrame, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Graphics.Vector4, Terraria.Dust.velocity, Terraria.Tile.wall, Microsoft.Xna.Framework.Color.White, Terraria.Utilities.FastRandom.WithModifier(), Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.Drawing.TileDrawing.Draw().