Terraria Decompiled: Terraria.GameContent.Drawing.TileDrawing.DrawTile_BackRope
DrawTile_BackRope()
void Terraria.GameContent.Drawing.TileDrawing.DrawTile_BackRope (Vector2 screenPosition, Vector2 screenOffset, int tileX, int tileY, TileDrawInfo drawData) inline private
Definition at line 4178 of file TileDrawing.cs.
        {
            if (!WorldGen.InWorld(tileX, tileY, 1))
            {
                return;
            }
            int num = tileX;
            int num2 = tileY;
            if (!WorldGen.IsRope(tileX, tileY, out num, out num2, 5))
            {
                return;
            }
            Tile tile = Main.tile[tileX, num];
            if (tile == null)
            {
                return;
            }
            int num3 = (tileY + tileX) % 3 * 18;
            Texture2D tileDrawTexture = this.GetTileDrawTexture(tile, tileX, tileY);
            Main.tileBatch.Draw(tileDrawTexture, new Vector2((float)(tileX * 16 - (int)screenPosition.X), (float)(tileY * 16 - (int)screenPosition.Y)) + screenOffset, new Rectangle?(new Rectangle(90, num3, 16, 16)), drawData.tileLight, default(Vector2), 1f, drawData.tileSpriteEffect);
        }
References Terraria.Graphics.TileBatch.Draw(), Terraria.GameContent.Drawing.TileDrawing.GetTileDrawTexture(), Terraria.WorldGen.InWorld(), Terraria.WorldGen.IsRope(), Terraria.Main.tile, Terraria.Main.tileBatch, Terraria.DataStructures.TileDrawInfo.tileLight, Terraria.DataStructures.TileDrawInfo.tileSpriteEffect, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.GameContent.Drawing.TileDrawing.DrawBasicTile(), and Terraria.GameContent.Drawing.TileDrawing.DrawTile_MinecartTrack().