Terraria Decompiled: Terraria.GameContent.Drawing.TileDrawing.GetScreenDrawArea
GetScreenDrawArea()
static void Terraria.GameContent.Drawing.TileDrawing.GetScreenDrawArea (bool useOffscreenRange, out Vector2 drawOffSet, out int firstTileX, out int lastTileX, out int firstTileY, out int lastTileY) inline static
Definition at line 7798 of file TileDrawing.cs.
        {
            Vector2 scaledPosition = Main.Camera.ScaledPosition;
            Vector2 scaledSize = Main.Camera.ScaledSize;
            drawOffSet = (useOffscreenRange ? new Vector2((float)Main.offScreenRange, (float)Main.offScreenRange) : Vector2.Zero);
            firstTileX = (int)((scaledPosition.X - drawOffSet.X) / 16f - 1f);
            lastTileX = (int)((scaledPosition.X + scaledSize.X + drawOffSet.X) / 16f) + 2;
            firstTileY = (int)((scaledPosition.Y - drawOffSet.Y) / 16f - 1f);
            lastTileY = (int)((scaledPosition.Y + scaledSize.Y + drawOffSet.Y) / 16f) + 5;
            if (firstTileX < 4)
            {
                firstTileX = 4;
            }
            if (lastTileX > Main.maxTilesX - 4)
            {
                lastTileX = Main.maxTilesX - 4;
            }
            if (firstTileY < 4)
            {
                firstTileY = 4;
            }
            if (lastTileY > Main.maxTilesY - 4)
            {
                lastTileY = Main.maxTilesY - 4;
            }
            if (Main.sectionManager.AnyUnfinishedSections)
            {
                TimeLogger.StartTimestamp startTimestamp = TimeLogger.Start();
                WorldGen.SectionTileFrameWithCheck(firstTileX, firstTileY, lastTileX, lastTileY);
                TimeLogger.SectionFraming.AddTime(startTimestamp);
            }
            if (Main.sectionManager.AnyNeedRefresh)
            {
                TimeLogger.StartTimestamp startTimestamp2 = TimeLogger.Start();
                WorldGen.RefreshSections(firstTileX, firstTileY, lastTileX, lastTileY);
                TimeLogger.SectionRefresh.AddTime(startTimestamp2);
            }
        }
References Terraria.WorldSections.AnyNeedRefresh, Terraria.WorldSections.AnyUnfinishedSections, Terraria.Main.Camera, int, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.offScreenRange, Terraria.WorldGen.RefreshSections(), Terraria.Graphics.Camera.ScaledPosition, Terraria.Graphics.Camera.ScaledSize, Terraria.TimeLogger.SectionFraming, Terraria.Main.sectionManager, Terraria.TimeLogger.SectionRefresh, Terraria.WorldGen.SectionTileFrameWithCheck(), Terraria.TimeLogger.Start(), Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.Drawing.TileDrawing.Draw(), Terraria.Main.DrawBlack(), Terraria.GameContent.Drawing.TileDrawing.DrawLiquidBehindTiles(), Terraria.GameContent.Drawing.WallDrawing.DrawWalls(), Terraria.Main.DrawWaters(), Terraria.Main.DrawWires(), Terraria.GameContent.Drawing.TileDrawing.EnsureWindGridSize(), and Terraria.GameContent.Drawing.TileDrawing.PreparePaintForTilesOnScreen().