Terraria Decompiled: Terraria.GameContent.Drawing.TileDrawing.GetTileFlameData
GetTileFlameData()
TileDrawing.TileFlameData Terraria.GameContent.Drawing.TileDrawing.GetTileFlameData (int tileX, int tileY, int type, int tileFrameY) inline private
Definition at line 2256 of file TileDrawing.cs.
        {
            if (type == 270)
            {
                return new TileDrawing.TileFlameData
                {
                    flameTexture = TextureAssets.FireflyJar.Value,
                    flameColor = new Color(200, 200, 200, 0),
                    flameCount = 1
                };
            }
            if (type == 271)
            {
                return new TileDrawing.TileFlameData
                {
                    flameTexture = TextureAssets.LightningbugJar.Value,
                    flameColor = new Color(200, 200, 200, 0),
                    flameCount = 1
                };
            }
            if (type == 581)
            {
                return new TileDrawing.TileFlameData
                {
                    flameTexture = TextureAssets.GlowMask[291].Value,
                    flameColor = new Color(200, 100, 100, 0),
                    flameCount = 1
                };
            }
            if (!Main.tileFlame[type])
            {
                return default(TileDrawing.TileFlameData);
            }
            ulong num = Main.TileFrameSeed ^ (ulong)(((long)tileX << 32) | (long)((ulong)tileY));
            int num2 = 0;
            if (type == 4)
            {
                num2 = 0;
            }
            else if (type == 33 || type == 174)
            {
                num2 = 1;
            }
            else if (type == 100 || type == 173)
            {
                num2 = 2;
            }
            else if (type == 34)
            {
                num2 = 3;
            }
            else if (type == 93)
            {
                num2 = 4;
            }
            else if (type == 49)
            {
                num2 = 5;
            }
            else if (type == 372)
            {
                num2 = 16;
            }
            else if (type == 646)
            {
                num2 = 17;
            }
            else if (type == 98)
            {
                num2 = 6;
            }
            else if (type == 35)
            {
                num2 = 7;
            }
            else if (type == 42)
            {
                num2 = 13;
            }
            TileDrawing.TileFlameData tileFlameData = new TileDrawing.TileFlameData
            {
                flameTexture = TextureAssets.Flames[num2].Value,
                flameSeed = num
            };
            switch (num2)
            {
            case 1:
            {
                int num3 = (int)(Main.tile[tileX, tileY].frameY / 22);
                switch (num3)
                {
                case 5:
                case 6:
                case 7:
                case 10:
                    tileFlameData.flameCount = 7;
                    tileFlameData.flameColor = new Color(50, 50, 50, 0);
                    tileFlameData.flameRangeXMin = -10;
                    tileFlameData.flameRangeXMax = 11;
                    tileFlameData.flameRangeYMin = -10;
                    tileFlameData.flameRangeYMax = 11;
                    tileFlameData.flameRangeMultX = 0.075f;
                    tileFlameData.flameRangeMultY = 0.075f;
                    return tileFlameData;
                case 8:
                    tileFlameData.flameCount = 7;
                    tileFlameData.flameColor = new Color(50, 50, 50, 0);
                    tileFlameData.flameRangeXMin = -10;
                    tileFlameData.flameRangeXMax = 11;
                    tileFlameData.flameRangeYMin = -10;
                    tileFlameData.flameRangeYMax = 11;
                    tileFlameData.flameRangeMultX = 0.3f;
                    tileFlameData.flameRangeMultY = 0.3f;
                    return tileFlameData;
                case 9:
                case 11:
                case 13:
                case 15:
                    break;
                case 12:
                    tileFlameData.flameCount = 7;
                    tileFlameData.flameColor = new Color(50, 50, 50, 0);
                    tileFlameData.flameRangeXMin = -10;
                    tileFlameData.flameRangeXMax = 11;
                    tileFlameData.flameRangeYMin = -10;
                    tileFlameData.flameRangeYMax = 1;
                    tileFlameData.flameRangeMultX = 0.1f;
                    tileFlameData.flameRangeMultY = 0.15f;
                    return tileFlameData;
                case 14:
                    tileFlameData.flameCount = 8;
                    tileFlameData.flameColor = new Color(75, 75, 75, 0);
                    tileFlameData.flameRangeXMin = -10;
                    tileFlameData.flameRangeXMax = 11;
                    tileFlameData.flameRangeYMin = -10;
                    tileFlameData.flameRangeYMax = 11;
                    tileFlameData.flameRangeMultX = 0.1f;
                    tileFlameData.flameRangeMultY = 0.1f;
                    return tileFlameData;
                case 16:
                    tileFlameData.flameCount = 4;
                    tileFlameData.flameColor = new Color(75, 75, 75, 0);
                    tileFlameData.flameRangeXMin = -10;
                    tileFlameData.flameRangeXMax = 11;
                    tileFlameData.flameRangeYMin = -10;
                    tileFlameData.flameRangeYMax = 11;
                    tileFlameData.flameRangeMultX = 0.15f;
                    tileFlameData.flameRangeMultY = 0.15f;
                    return tileFlameData;
                default:
                    switch (num3)
                    {
                    case 27:
                    case 28:
                        tileFlameData.flameCount = 1;
                        tileFlameData.flameColor = new Color(75, 75, 75, 0);
                        tileFlameData.flameRangeXMin = -10;
                        tileFlameData.flameRangeXMax = 11;
                        tileFlameData.flameRangeYMin = -10;
                        tileFlameData.flameRangeYMax = 11;
                        tileFlameData.flameRangeMultX = 0f;
                        tileFlameData.flameRangeMultY = 0f;
                        return tileFlameData;
                    case 43:
                        tileFlameData.flameCount = 1;
                        tileFlameData.flameColor = this.GetFallenStarFurnitureFlameColor();
                        tileFlameData.flameRangeMultX = 0f;
                        tileFlameData.flameRangeMultY = 0f;
                        return tileFlameData;
                    case 44:
                        tileFlameData.flameCount = 3;
                        tileFlameData.flameColor = new Color(200, 200, 200, 150);
                        tileFlameData.flameRangeXMin = -10;
                        tileFlameData.flameRangeXMax = 11;
                        tileFlameData.flameRangeYMin = -10;
                        tileFlameData.flameRangeYMax = 1;
                        tileFlameData.flameRangeMultX = 0.15f;
                        tileFlameData.flameRangeMultY = 0.35f;
                        return tileFlameData;
                    case 45:
                        tileFlameData.flameCount = 1;
                        tileFlameData.flameColor = this.GetHallowedFurnitureFlameColor();
                        tileFlameData.flameRangeMultX = 0f;
                        tileFlameData.flameRangeMultY = 0f;
                        return tileFlameData;
                    case 47:
                    case 48:
                    case 49:
                    case 51:
                    case 52:
                    case 54:
                        tileFlameData.flameCount = 0;
                        return tileFlameData;
                    case 56:
                        tileFlameData.flameCount = 1;
                        tileFlameData.flameColor = this.GetCloudFurnitureFlameColor();
                        tileFlameData.flameRangeMultX = 0f;
                        tileFlameData.flameRangeMultY = 0f;
                        return tileFlameData;
                    case 57:
                    case 60:
                        tileFlameData.flameCount = 1;
                        tileFlameData.flameColor = new Color(200, 200, 200, 150);
                        tileFlameData.flameRangeMultX = 0f;
                        tileFlameData.flameRangeMultY = 0f;
                        return tileFlameData;
                    case 58:
                        tileFlameData.flameCount = 1;
                        tileFlameData.flameColor = this.GetLibrarianFurnitureFlameColor();
                        tileFlameData.flameRangeMultX = 0f;
                        tileFlameData.flameRangeMultY = 0f;
                        return tileFlameData;
                    case 61:
                        tileFlameData.flameCount = 1;
                        tileFlameData.flameColor = this.GetForbiddenFurnitureFlameColor();
                        tileFlameData.flameRangeMultX = 0f;
                        tileFlameData.flameRangeMultY = 0f;
                        return tileFlameData;
                    case 63:
                        tileFlameData.flameCount = 1;
                        tileFlameData.flameColor = this.GetBoulderFurnitureFlameColor();
                        tileFlameData.flameRangeMultX = 0f;
                        tileFlameData.flameRangeMultY = 0f;
                        return tileFlameData;
                    }
                    break;
                }
                tileFlameData.flameCount = 7;
                tileFlameData.flameColor = new Color(100, 100, 100, 0);
                tileFlameData.flameRangeXMin = -10;
                tileFlameData.flameRangeXMax = 11;
                tileFlameData.flameRangeYMin = -10;
                tileFlameData.flameRangeYMax = 1;
                tileFlameData.flameRangeMultX = 0.15f;
                tileFlameData.flameRangeMultY = 0.35f;
                return tileFlameData;
            }
            case 2:
            {
                int num4 = (int)(Main.tile[tileX, tileY].frameY / 36);
                if (num4 <= 6)
                {
                    if (num4 == 3)
                    {
                        tileFlameData.flameCount = 3;
                        tileFlameData.flameColor = new Color(50, 50, 50, 0);
                        tileFlameData.flameRangeXMin = -10;
                        tileFlameData.flameRangeXMax = 11;
                        tileFlameData.flameRangeYMin = -10;
                        tileFlameData.flameRangeYMax = 11;
                        tileFlameData.flameRangeMultX = 0.05f;
                        tileFlameData.flameRangeMultY = 0.15f;
                        return tileFlameData;
                    }
                    if (num4 == 6)
                    {
                        tileFlameData.flameCount = 5;
                        tileFlameData.flameColor = new Color(75, 75, 75, 0);
                        tileFlameData.flameRangeXMin = -10;
                        tileFlameData.flameRangeXMax = 11;
                        tileFlameData.flameRangeYMin = -10;
                        tileFlameData.flameRangeYMax = 11;
                        tileFlameData.flameRangeMultX = 0.15f;
                        tileFlameData.flameRangeMultY = 0.15f;
                        return tileFlameData;
                    }
                }
                else
                {
                    switch (num4)
                    {
                    case 9:
                        tileFlameData.flameCount = 7;
                        tileFlameData.flameColor = new Color(100, 100, 100, 0);
                        tileFlameData.flameRangeXMin = -10;
                        tileFlameData.flameRangeXMax = 11;
                        tileFlameData.flameRangeYMin = -10;
                        tileFlameData.flameRangeYMax = 11;
                        tileFlameData.flameRangeMultX = 0.3f;
                        tileFlameData.flameRangeMultY = 0.3f;
                        return tileFlameData;
                    case 10:
                    case 12:
                        break;
                    case 11:
                        tileFlameData.flameCount = 7;
                        tileFlameData.flameColor = new Color(50, 50, 50, 0);
                        tileFlameData.flameRangeXMin = -10;
                        tileFlameData.flameRangeXMax = 11;
                        tileFlameData.flameRangeYMin = -10;
                        tileFlameData.flameRangeYMax = 1;
                        tileFlameData.flameRangeMultX = 0.1f;
                        tileFlameData.flameRangeMultY = 0.15f;
                        return tileFlameData;
                    case 13:
                        tileFlameData.flameCount = 8;
                        tileFlameData.flameColor = new Color(75, 75, 75, 0);
                        tileFlameData.flameRangeXMin = -10;
                        tileFlameData.flameRangeXMax = 11;
                        tileFlameData.flameRangeYMin = -10;
                        tileFlameData.flameRangeYMax = 11;
                        tileFlameData.flameRangeMultX = 0.1f;
                        tileFlameData.flameRangeMultY = 0.1f;
                        return tileFlameData;
                    default:
                        switch (num4)
{
                        case 28:
                        case 29:
                            tileFlameData.flameCount = 1;
                            tileFlameData.flameColor = new Color(75, 75, 75, 0);
                            tileFlameData.flameRangeXMin = -10;
                            tileFlameData.flameRangeXMax = 11;
                            tileFlameData.flameRangeYMin = -10;
                            tileFlameData.flameRangeYMax = 1;
                            tileFlameData.flameRangeMultX = 0f;
                            tileFlameData.flameRangeMultY = 0f;
                            return tileFlameData;
                        case 44:
                            tileFlameData.flameCount = 1;
                            tileFlameData.flameColor = this.GetFallenStarFurnitureFlameColor();
                            tileFlameData.flameRangeMultX = 0f;
                            tileFlameData.flameRangeMultY = 0f;
                            return tileFlameData;
                        case 45:
                            tileFlameData.flameCount = 3;
                            tileFlameData.flameColor = new Color(200, 200, 200, 150);
                            tileFlameData.flameRangeXMin = -10;
                            tileFlameData.flameRangeXMax = 11;
                            tileFlameData.flameRangeYMin = -10;
                            tileFlameData.flameRangeYMax = 1;
                            tileFlameData.flameRangeMultX = 0.15f;
                            tileFlameData.flameRangeMultY = 0.35f;
                            return tileFlameData;
                        case 46:
                            tileFlameData.flameCount = 1;
                            tileFlameData.flameColor = this.GetHallowedFurnitureFlameColor();
                            tileFlameData.flameRangeMultX = 0f;
                            tileFlameData.flameRangeMultY = 0f;
                            return tileFlameData;
                        case 48:
                        case 49:
                        case 50:
                        case 52:
                        case 53:
                        case 55:
                            tileFlameData.flameCount = 0;
                            return tileFlameData;
                        case 57:
                            tileFlameData.flameCount = 1;
                            tileFlameData.flameColor = this.GetCloudFurnitureFlameColor();
                            tileFlameData.flameRangeMultX = 0f;
                            tileFlameData.flameRangeMultY = 0f;
                            return tileFlameData;
                        case 58:
                        case 61:
                            tileFlameData.flameCount = 1;
                            tileFlameData.flameColor = new Color(200, 200, 200, 150);
                            tileFlameData.flameRangeMultX = 0f;
                            tileFlameData.flameRangeMultY = 0f;
                            return tileFlameData;
                        case 59:
                            tileFlameData.flameCount = 1;
                            tileFlameData.flameColor = this.GetLibrarianFurnitureFlameColor();
                            tileFlameData.flameRangeMultX = 0f;
                            tileFlameData.flameRangeMultY = 0f;
                            return tileFlameData;
                        case 62:
                            tileFlameData.flameCount = 1;
                            tileFlameData.flameColor = this.GetForbiddenFurnitureFlameColor();
                            tileFlameData.flameRangeMultX = 0f;
                            tileFlameData.flameRangeMultY = 0f;
                            return tileFlameData;
                        case 64:
                            tileFlameData.flameCount = 1;
                            tileFlameData.flameColor = this.GetBoulderFurnitureFlameColor();
                            tileFlameData.flameRangeMultX = 0f;
                            tileFlameData.flameRangeMultY = 0f;
                            return tileFlameData;
                        }
                        break;
                    }
                }
                tileFlameData.flameCount = 7;
                tileFlameData.flameColor = new Color(100, 100, 100, 0);
                tileFlameData.flameRangeXMin = -10;
                tileFlameData.flameRangeXMax = 11;
                tileFlameData.flameRangeYMin = -10;
                tileFlameData.flameRangeYMax = 1;
                tileFlameData.flameRangeMultX = 0.15f;
                tileFlameData.flameRangeMultY = 0.35f;
                return tileFlameData;
            }
            case 3:
            {
                int num5 = (int)(Main.tile[tileX, tileY].frameY / 54);
                if (Main.tile[tileX, tileY].frameX >= 108)
                {
                    num5 += (int)(37 * (Main.tile[tileX, tileY].frameX / 108));
                }
                switch (num5)
                {
                case 8:
                    tileFlameData.flameCount = 7;
                    tileFlameData.flameColor = new Color(50, 50, 50, 0);
                    tileFlameData.flameRangeXMin = -10;
                    tileFlameData.flameRangeXMax = 11;
                    tileFlameData.flameRangeYMin = -10;
                    tileFlameData.flameRangeYMax = 11;
                    tileFlameData.flameRangeMultX = 0.075f;
                    tileFlameData.flameRangeMultY = 0.075f;
                    return tileFlameData;
                case 9:
                    tileFlameData.flameCount = 3;
                    tileFlameData.flameColor = new Color(50, 50, 50, 0);
                    tileFlameData.flameRangeXMin = -1;
                    tileFlameData.flameRangeXMax = 1;
                    tileFlameData.flameRangeYMin = -1;
                    tileFlameData.flameRangeYMax = 1;
                    tileFlameData.flameRangeMultX = 2f;
                    tileFlameData.flameRangeMultY = 2f;
                    return tileFlameData;
                case 10:
                case 12:
                case 13:
                case 14:
                case 16:
                case 19:
                    break;
                case 11:
                    tileFlameData.flameCount = 7;
                    tileFlameData.flameColor = new Color(50, 50, 50, 0);
                    tileFlameData.flameRangeXMin = -10;
                    tileFlameData.flameRangeXMax = 11;
                    tileFlameData.flameRangeYMin = -10;
                    tileFlameData.flameRangeYMax = 11;
                    tileFlameData.flameRangeMultX = 0.3f;
                    tileFlameData.flameRangeMultY = 0.3f;
                    return tileFlameData;
                case 15:
                    tileFlameData.flameCount = 7;
                    tileFlameData.flameColor = new Color(50, 50, 50, 0);
                    tileFlameData.flameRangeXMin = -10;
                    tileFlameData.flameRangeXMax = 11;
                    tileFlameData.flameRangeYMin = -10;
                    tileFlameData.flameRangeYMax = 1;
                    tileFlameData.flameRangeMultX = 0.1f;
                    tileFlameData.flameRangeMultY = 0.15f;
                    return tileFlameData;
                case 17:
                case 20:
                    tileFlameData.flameCount = 7;
                    tileFlameData.flameColor = new Color(50, 50, 50, 0);
                    tileFlameData.flameRangeXMin = -10;
                    tileFlameData.flameRangeXMax = 11;
                    tileFlameData.flameRangeYMin = -10;
                    tileFlameData.flameRangeYMax = 11;
                    tileFlameData.flameRangeMultX = 0.075f;
                    tileFlameData.flameRangeMultY = 0.075f;
                    return tileFlameData;
                case 18:
                    tileFlameData.flameCount = 8;
                    tileFlameData.flameColor = new Color(75, 75, 75, 0);
                    tileFlameData.flameRangeXMin = -10;
                    tileFlameData.flameRangeXMax = 11;
                    tileFlameData.flameRangeYMin = -10;
                    tileFlameData.flameRangeYMax = 11;
                    tileFlameData.flameRangeMultX = 0.1f;
                    tileFlameData.flameRangeMultY = 0.1f;
                    return tileFlameData;
                default:
                    switch (num5)
                    {
                    case 34:
                    case 35:
                        tileFlameData.flameCount = 1;
                        tileFlameData.flameColor = new Color(75, 75, 75, 0);
                        tileFlameData.flameRangeXMin = -10;
                        tileFlameData.flameRangeXMax = 11;
                        tileFlameData.flameRangeYMin = -10;
                        tileFlameData.flameRangeYMax = 11;
                        tileFlameData.flameRangeMultX = 0f;
                        tileFlameData.flameRangeMultY = 0f;
                        return tileFlameData;
                    case 50:
                        tileFlameData.flameCount = 1;
                        tileFlameData.flameColor = this.GetFallenStarFurnitureFlameColor();
                        tileFlameData.flameRangeMultX = 0f;
                        tileFlameData.flameRangeMultY = 0f;
                        return tileFlameData;
                    case 51:
                        tileFlameData.flameCount = 3;
                        tileFlameData.flameColor = new Color(200, 200, 200, 150);
                        tileFlameData.flameRangeXMin = -10;
                        tileFlameData.flameRangeXMax = 11;
                        tileFlameData.flameRangeYMin = -10;
                        tileFlameData.flameRangeYMax = 1;
                        tileFlameData.flameRangeMultX = 0.15f;
                        tileFlameData.flameRangeMultY = 0.35f;
                        return tileFlameData;
                    case 52:
                        tileFlameData.flameCount = 1;
                        tileFlameData.flameColor = this.GetHallowedFurnitureFlameColor();
                        tileFlameData.flameRangeMultX = 0f;
                        tileFlameData.flameRangeMultY = 0f;
                        return tileFlameData;
                    case 54:
                    case 55:
                    case 56:
                    case 58:
                    case 59:
                    case 61:
                        tileFlameData.flameCount = 0;
                        return tileFlameData;
                    case 63:
                        tileFlameData.flameCount = 1;
                        tileFlameData.flameColor = this.GetCloudFurnitureFlameColor();
                        tileFlameData.flameRangeMultX = 0f;
                        tileFlameData.flameRangeMultY = 0f;
                        return tileFlameData;
                    case 64:
                    case 67:
                        tileFlameData.flameCount = 1;
                        tileFlameData.flameColor = new Color(200, 200, 200, 150);
                        tileFlameData.flameRangeMultX = 0f;
                        tileFlameData.flameRangeMultY = 0f;
                        return tileFlameData;
                    case 65:
                        tileFlameData.flameCount = 1;
                        tileFlameData.flameColor = this.GetLibrarianFurnitureFlameColor();
                        tileFlameData.flameRangeMultX = 0f;
                        tileFlameData.flameRangeMultY = 0f;
                        return tileFlameData;
                    case 68:
                        tileFlameData.flameCount = 1;
                        tileFlameData.flameColor = this.GetForbiddenFurnitureFlameColor();
                        tileFlameData.flameRangeMultX = 0f;
                        tileFlameData.flameRangeMultY = 0f;
                        return tileFlameData;
                    case 70:
                        tileFlameData.flameCount = 1;
                        tileFlameData.flameColor = this.GetBoulderFurnitureFlameColor();
                        tileFlameData.flameRangeMultX = 0f;
                        tileFlameData.flameRangeMultY = 0f;
                        return tileFlameData;
                    }
                    break;
                }
                tileFlameData.flameCount = 7;
                tileFlameData.flameColor = new Color(100, 100, 100, 0);
                tileFlameData.flameRangeXMin = -10;
                tileFlameData.flameRangeXMax = 11;
                tileFlameData.flameRangeYMin = -10;
                tileFlameData.flameRangeYMax = 1;
                tileFlameData.flameRangeMultX = 0.15f;
                tileFlameData.flameRangeMultY = 0.35f;
                return tileFlameData;
            }
            case 4:
            {
                int num6 = (int)(Main.tile[tileX, tileY].frameY / 54);
                switch (num6)
                {
                case 1:
                    tileFlameData.flameCount = 3;
                    tileFlameData.flameColor = new Color(50, 50, 50, 0);
                    tileFlameData.flameRangeXMin = -10;
                    tileFlameData.flameRangeXMax = 11;
                    tileFlameData.flameRangeYMin = -10;
                    tileFlameData.flameRangeYMax = 11;
                    tileFlameData.flameRangeMultX = 0.15f;
                    tileFlameData.flameRangeMultY = 0.15f;
                    return tileFlameData;
                case 2:
                case 4:
                    tileFlameData.flameCount = 7;
                    tileFlameData.flameColor = new Color(50, 50, 50, 0);
                    tileFlameData.flameRangeXMin = -10;
                    tileFlameData.flameRangeXMax = 11;
                    tileFlameData.flameRangeYMin = -10;
                    tileFlameData.flameRangeYMax = 11;
                    tileFlameData.flameRangeMultX = 0.075f;
                    tileFlameData.flameRangeMultY = 0.075f;
                    return tileFlameData;
                case 3:
                    tileFlameData.flameCount = 7;
                    tileFlameData.flameColor = new Color(100, 100, 100, 0);
                    tileFlameData.flameRangeXMin = -10;
                    tileFlameData.flameRangeXMax = 11;
                    tileFlameData.flameRangeYMin = -20;
                    tileFlameData.flameRangeYMax = 1;
                    tileFlameData.flameRangeMultX = 0.2f;
                    tileFlameData.flameRangeMultY = 0.35f;
                    return tileFlameData;
                case 5:
                    tileFlameData.flameCount = 7;
                    tileFlameData.flameColor = new Color(50, 50, 50, 0);
                    tileFlameData.flameRangeXMin = -10;
                    tileFlameData.flameRangeXMax = 11;
                    tileFlameData.flameRangeYMin = -10;
                    tileFlameData.flameRangeYMax = 11;
                    tileFlameData.flameRangeMultX = 0.3f;
                    tileFlameData.flameRangeMultY = 0.3f;
                    return tileFlameData;
                case 6:
                case 7:
                case 8:
                case 10:
                case 11:
                    break;
                case 9:
                    tileFlameData.flameCount = 7;
                    tileFlameData.flameColor = new Color(50, 50, 50, 0);
                    tileFlameData.flameRangeXMin = -10;
                    tileFlameData.flameRangeXMax = 11;
                    tileFlameData.flameRangeYMin = -10;
                    tileFlameData.flameRangeYMax = 1;
                    tileFlameData.flameRangeMultX = 0.1f;
                    tileFlameData.flameRangeMultY = 0.15f;
                    return tileFlameData;
                case 12:
                    tileFlameData.flameCount = 1;
                    tileFlameData.flameColor = new Color(100, 100, 100, 0);
                    tileFlameData.flameRangeXMin = -10;
                    tileFlameData.flameRangeXMax = 11;
                    tileFlameData.flameRangeYMin = -10;
                    tileFlameData.flameRangeYMax = 11;
                    tileFlameData.flameRangeMultX = 0.01f;
                    tileFlameData.flameRangeMultY = 0.01f;
                    return tileFlameData;
                case 13:
                    tileFlameData.flameCount = 8;
                    tileFlameData.flameColor = new Color(50, 50, 50, 0);
                    tileFlameData.flameRangeXMin = -10;
                    tileFlameData.flameRangeXMax = 11;
                    tileFlameData.flameRangeYMin = -10;
                    tileFlameData.flameRangeYMax = 11;
                    tileFlameData.flameRangeMultX = 0.1f;
                    tileFlameData.flameRangeMultY = 0.1f;
                    return tileFlameData;
                default:
                    switch (num6)
                    {
                    case 28:
                    case 29:
                        tileFlameData.flameCount = 1;
                        tileFlameData.flameColor = new Color(75, 75, 75, 0);
                        tileFlameData.flameRangeXMin = -10;
                        tileFlameData.flameRangeXMax = 11;
                        tileFlameData.flameRangeYMin = -10;
                        tileFlameData.flameRangeYMax = 11;
                        tileFlameData.flameRangeMultX = 0f;
                        tileFlameData.flameRangeMultY = 0f;
                        return tileFlameData;
                    case 44:
                        tileFlameData.flameCount = 1;
                        tileFlameData.flameColor = this.GetFallenStarFurnitureFlameColor();
                        tileFlameData.flameRangeMultX = 0f;
                        tileFlameData.flameRangeMultY = 0f;
                        return tileFlameData;
                    case 45:
                        tileFlameData.flameCount = 3;
                        tileFlameData.flameColor = new Color(200, 200, 200, 150);
                        tileFlameData.flameRangeXMin = -10;
                        tileFlameData.flameRangeXMax = 11;
                        tileFlameData.flameRangeYMin = -10;
                        tileFlameData.flameRangeYMax = 1;
                        tileFlameData.flameRangeMultX = 0.15f;
                        tileFlameData.flameRangeMultY = 0.35f;
                        return tileFlameData;
                    case 46:
                        tileFlameData.flameCount = 1;
                        tileFlameData.flameColor = this.GetHallowedFurnitureFlameColor();
                        tileFlameData.flameRangeMultX = 0f;
                        tileFlameData.flameRangeMultY = 0f;
                        return tileFlameData;
                    case 48:
                    case 49:
                    case 50:
                    case 52:
                    case 53:
                    case 55:
                        tileFlameData.flameCount = 0;
                        return tileFlameData;
                    case 57:
                        tileFlameData.flameCount = 1;
                        tileFlameData.flameColor = this.GetCloudFurnitureFlameColor();
                        tileFlameData.flameRangeMultX = 0f;
                        tileFlameData.flameRangeMultY = 0f;
                        return tileFlameData;
                    case 58:
                    case 61:
                        tileFlameData.flameCount = 1;
                        tileFlameData.flameColor = new Color(200, 200, 200, 150);
                        tileFlameData.flameRangeMultX = 0f;
                        tileFlameData.flameRangeMultY = 0f;
                        return tileFlameData;
                    case 59:
                        tileFlameData.flameCount = 1;
                        tileFlameData.flameColor = this.GetLibrarianFurnitureFlameColor();
                        tileFlameData.flameRangeMultX = 0f;
                        tileFlameData.flameRangeMultY = 0f;
                        return tileFlameData;
                    case 62:
                        tileFlameData.flameCount = 1;
                        tileFlameData.flameColor = this.GetForbiddenFurnitureFlameColor();
                        tileFlameData.flameRangeMultX = 0f;
                        tileFlameData.flameRangeMultY = 0f;
                        return tileFlameData;
                    case 64:
                        tileFlameData.flameCount = 1;
                        tileFlameData.flameColor = this.GetBoulderFurnitureFlameColor();
                        tileFlameData.flameRangeMultX = 0f;
                        tileFlameData.flameRangeMultY = 0f;
                        return tileFlameData;
                    }
                    break;
                }
                tileFlameData.flameCount = 7;
                tileFlameData.flameColor = new Color(100, 100, 100, 0);
                tileFlameData.flameRangeXMin = -10;
                tileFlameData.flameRangeXMax = 11;
                tileFlameData.flameRangeYMin = -10;
                tileFlameData.flameRangeYMax = 1;
                tileFlameData.flameRangeMultX = 0.15f;
                tileFlameData.flameRangeMultY = 0.35f;
                return tileFlameData;
            }
            case 5:
            case 6:
                break;
            case 7:
                tileFlameData.flameCount = 4;
                tileFlameData.flameColor = new Color(50, 50, 50, 0);
                tileFlameData.flameRangeXMin = -10;
                tileFlameData.flameRangeXMax = 11;
                tileFlameData.flameRangeYMin = -10;
                tileFlameData.flameRangeYMax = 10;
                tileFlameData.flameRangeMultX = 0f;
                tileFlameData.flameRangeMultY = 0f;
                return tileFlameData;
            default:
                if (num2 == 13)
                {
                    switch (tileFrameY / 36)
                    {
                    case 1:
                    case 3:
                    case 6:
                    case 8:
                    case 19:
                    case 27:
                    case 29:
                    case 30:
                    case 31:
                    case 32:
                    case 36:
                    case 39:
                    case 53:
                    case 57:
                    case 60:
                    case 62:
                    case 66:
                    case 69:
                        tileFlameData.flameCount = 7;
                        tileFlameData.flameColor = new Color(100, 100, 100, 0);
                        tileFlameData.flameRangeXMin = -10;
                        tileFlameData.flameRangeXMax = 11;
                        tileFlameData.flameRangeYMin = -10;
                        tileFlameData.flameRangeYMax = 1;
                        tileFlameData.flameRangeMultX = 0.15f;
                        tileFlameData.flameRangeMultY = 0.35f;
                        return tileFlameData;
                    case 2:
                    case 16:
                    case 25:
                        tileFlameData.flameCount = 7;
                        tileFlameData.flameColor = new Color(50, 50, 50, 0);
                        tileFlameData.flameRangeXMin = -10;
                        tileFlameData.flameRangeXMax = 11;
                        tileFlameData.flameRangeYMin = -10;
                        tileFlameData.flameRangeYMax = 1;
                        tileFlameData.flameRangeMultX = 0.15f;
                        tileFlameData.flameRangeMultY = 0.1f;
                        return tileFlameData;
                    case 11:
                        tileFlameData.flameCount = 7;
                        tileFlameData.flameColor = new Color(50, 50, 50, 0);
                        tileFlameData.flameRangeXMin = -10;
                        tileFlameData.flameRangeXMax = 11;
                        tileFlameData.flameRangeYMin = -10;
                        tileFlameData.flameRangeYMax = 11;
                        tileFlameData.flameRangeMultX = 0.075f;
                        tileFlameData.flameRangeMultY = 0.075f;
                        return tileFlameData;
                    case 34:
                    case 35:
                        tileFlameData.flameCount = 1;
                        tileFlameData.flameColor = new Color(75, 75, 75, 0);
                        tileFlameData.flameRangeXMin = -10;
                        tileFlameData.flameRangeXMax = 11;
                        tileFlameData.flameRangeYMin = -10;
                        tileFlameData.flameRangeYMax = 1;
                        tileFlameData.flameRangeMultX = 0f;
                        tileFlameData.flameRangeMultY = 0f;
                        return tileFlameData;
                    case 44:
                        tileFlameData.flameCount = 7;
                        tileFlameData.flameColor = new Color(100, 100, 100, 0);
                        tileFlameData.flameRangeXMin = -10;
                        tileFlameData.flameRangeXMax = 11;
                        tileFlameData.flameRangeYMin = -10;
                        tileFlameData.flameRangeYMax = 1;
                        tileFlameData.flameRangeMultX = 0.15f;
                        tileFlameData.flameRangeMultY = 0.35f;
                        return tileFlameData;
                    case 50:
                        tileFlameData.flameCount = 1;
                        tileFlameData.flameColor = this.GetFallenStarFurnitureFlameColor();
                        tileFlameData.flameRangeMultX = 0f;
                        tileFlameData.flameRangeMultY = 0f;
                        return tileFlameData;
                    case 51:
                        tileFlameData.flameCount = 3;
                        tileFlameData.flameColor = new Color(200, 200, 200, 150);
                        tileFlameData.flameRangeXMin = -10;
                        tileFlameData.flameRangeXMax = 11;
                        tileFlameData.flameRangeYMin = -10;
                        tileFlameData.flameRangeYMax = 1;
                        tileFlameData.flameRangeMultX = 0.15f;
                        tileFlameData.flameRangeMultY = 0.35f;
                        return tileFlameData;
                    case 52:
                        tileFlameData.flameCount = 1;
                        tileFlameData.flameColor = this.GetHallowedFurnitureFlameColor();
                        tileFlameData.flameRangeMultX = 0f;
                        tileFlameData.flameRangeMultY = 0f;
                        return tileFlameData;
                    case 54:
                    case 55:
                    case 56:
                    case 58:
                    case 59:
                    case 61:
                        tileFlameData.flameCount = 0;
                        return tileFlameData;
                    case 63:
                        tileFlameData.flameCount = 1;
                        tileFlameData.flameColor = this.GetCloudFurnitureFlameColor();
                        tileFlameData.flameRangeMultX = 0f;
                        tileFlameData.flameRangeMultY = 0f;
                        return tileFlameData;
                    case 64:
                    case 67:
                        tileFlameData.flameCount = 1;
                        tileFlameData.flameColor = new Color(200, 200, 200, 150);
                        tileFlameData.flameRangeMultX = 0f;
                        tileFlameData.flameRangeMultY = 0f;
                        return tileFlameData;
                    case 65:
                        tileFlameData.flameCount = 1;
                        tileFlameData.flameColor = this.GetLibrarianFurnitureFlameColor();
                        tileFlameData.flameRangeMultX = 0f;
                        tileFlameData.flameRangeMultY = 0f;
                        return tileFlameData;
                    case 68:
                        tileFlameData.flameCount = 1;
                        tileFlameData.flameColor = this.GetForbiddenFurnitureFlameColor();
                        tileFlameData.flameRangeMultX = 0f;
                        tileFlameData.flameRangeMultY = 0f;
                        return tileFlameData;
                    case 70:
                        tileFlameData.flameCount = 1;
                        tileFlameData.flameColor = this.GetBoulderFurnitureFlameColor();
                        tileFlameData.flameRangeMultX = 0f;
                        tileFlameData.flameRangeMultY = 0f;
                        return tileFlameData;
                    }
                    tileFlameData.flameCount = 0;
                    return tileFlameData;
                }
                break;
            }
            tileFlameData.flameCount = 7;
            tileFlameData.flameColor = new Color(100, 100, 100, 0);
            if (tileFrameY / 22 == 14)
            {
                tileFlameData.flameColor = new Color((float)Main.DiscoR / 255f, (float)Main.DiscoG / 255f, (float)Main.DiscoB / 255f, 0f);
            }
            tileFlameData.flameRangeXMin = -10;
            tileFlameData.flameRangeXMax = 11;
            tileFlameData.flameRangeYMin = -10;
            tileFlameData.flameRangeYMax = 1;
            tileFlameData.flameRangeMultX = 0.15f;
            tileFlameData.flameRangeMultY = 0.35f;
            return tileFlameData;
        }
References Microsoft.Xna.Framework.Graphics.Color, Terraria.Main.DiscoB, Terraria.Main.DiscoG, Terraria.Main.DiscoR, Terraria.GameContent.TextureAssets.FireflyJar, Terraria.GameContent.TextureAssets.Flames, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.GameContent.Drawing.TileDrawing.GetBoulderFurnitureFlameColor(), Terraria.GameContent.Drawing.TileDrawing.GetCloudFurnitureFlameColor(), Terraria.GameContent.Drawing.TileDrawing.GetFallenStarFurnitureFlameColor(), Terraria.GameContent.Drawing.TileDrawing.GetForbiddenFurnitureFlameColor(), Terraria.GameContent.Drawing.TileDrawing.GetHallowedFurnitureFlameColor(), Terraria.GameContent.Drawing.TileDrawing.GetLibrarianFurnitureFlameColor(), Terraria.GameContent.TextureAssets.GlowMask, int, Terraria.GameContent.TextureAssets.LightningbugJar, long, Terraria.Main.tile, Terraria.Main.tileFlame, and ReLogic.Content.Asset< T >.Value.
Referenced by Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileVinesInWind(), and Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile_Flames().