Terraria Decompiled: Terraria.GameContent.Drawing.TileDrawing.IsTileDangerous
IsTileDangerous()
static bool Terraria.GameContent.Drawing.TileDrawing.IsTileDangerous (Player localPlayer, Tile tileCache, ushort typeCache) inline static private
Definition at line 4885 of file TileDrawing.cs.
        {
            bool flag = false || typeCache == 135 || typeCache == 137 || TileID.Sets.Boulders[(int)typeCache] || typeCache == 141 || typeCache == 210 || typeCache == 442 || typeCache == 443 || typeCache == 444 || typeCache == 411 || typeCache == 485 || typeCache == 85 || typeCache == 654 || (typeCache == 314 && Minecart.IsPressurePlate(tileCache));
            flag |= Main.getGoodWorld && typeCache == 230;
            flag |= Main.dontStarveWorld && typeCache == 80;
            if (tileCache.slope() == 0 && !tileCache.inActive())
            {
                flag = flag || (typeCache >= 0 && TileID.Sets.TouchDamageImmediate[(int)typeCache] > 0) || typeCache == 483 || typeCache == 482 || typeCache == 481 || typeCache == 51 || typeCache == 229;
                if (!localPlayer.fireWalk)
                {
                    flag = flag || (typeCache >= 0 && TileID.Sets.TouchDamageHot[(int)typeCache]);
                }
                if (!localPlayer.iceSkate)
                {
                    flag = flag || typeCache == 162;
                }
            }
            return flag;
        }
References Terraria.ID.TileID.Sets.Boulders, Terraria.Player.fireWalk, Terraria.Player.iceSkate, Terraria.Tile.inActive(), int, Terraria.Minecart.IsPressurePlate(), Terraria.Tile.slope(), Terraria.ID.TileID.Sets.TouchDamageHot, and Terraria.ID.TileID.Sets.TouchDamageImmediate.
Referenced by Terraria.GameContent.Drawing.TileDrawing.DrawAnimatedTile_AdjustForVisionChangers(), and Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile().