Terraria Decompiled: Terraria.GameContent.Drawing.TileDrawing.DrawLiquidBehindTiles
DrawLiquidBehindTiles()
void Terraria.GameContent.Drawing.TileDrawing.DrawLiquidBehindTiles (int waterStyleOverride = -1) inline
Definition at line 357 of file TileDrawing.cs.
        {
            Main.tileBatch.Restart();
            Vector2 unscaledPosition = Main.Camera.UnscaledPosition;
            Vector2 vector;
            int num;
            int num2;
            int num3;
            int num4;
            TileDrawing.GetScreenDrawArea(!Main.drawToScreen, out vector, out num, out num2, out num3, out num4);
            for (int i = num3; i < num4 + 4; i++)
            {
                for (int j = num - 2; j < num2 + 2; j++)
                {
                    Tile tile = Main.tile[j, i];
                    if (tile != null)
                    {
                        Main.tileBatch.SetLayer(0U, 0);
                        this.DrawTile_LiquidBehindTile(false, waterStyleOverride, unscaledPosition, vector, j, i, tile);
                    }
                }
            }
            int num5 = Main.tileBatch.End();
            TimeLogger.LiquidBackgroundDrawCalls.Add(num5);
        }
References Terraria.Main.Camera, Terraria.GameContent.Drawing.TileDrawing.DrawTile_LiquidBehindTile(), Terraria.Main.drawToScreen, Terraria.Graphics.TileBatch.End(), Terraria.GameContent.Drawing.TileDrawing.GetScreenDrawArea(), Terraria.TimeLogger.LiquidBackgroundDrawCalls, Terraria.Graphics.TileBatch.Restart(), Terraria.Graphics.TileBatch.SetLayer(), Terraria.Main.tile, Terraria.Main.tileBatch, System.U, and Terraria.Graphics.Camera.UnscaledPosition.