Terraria Decompiled: Terraria.GameContent.Drawing.TileDrawing.CacheSpecialDraws_Part2
CacheSpecialDraws_Part2()
void Terraria.GameContent.Drawing.TileDrawing.CacheSpecialDraws_Part2 (int tileX, int tileY, TileDrawInfo drawData) inline private
Definition at line 4740 of file TileDrawing.cs.
        {
            if (TileID.Sets.BasicChest[(int)drawData.typeCache])
            {
                Point point = new Point(tileX, tileY);
                if (drawData.tileFrameX % 36 != 0)
                {
                    point.X--;
                }
                if (drawData.tileFrameY % 36 != 0)
                {
                    point.Y--;
                }
                if (!this._chestPositions.ContainsKey(point))
                {
                    this._chestPositions[point] = Chest.FindChest(point.X, point.Y);
                }
                int num = (int)(drawData.tileFrameX / 18);
                short num2 = drawData.tileFrameY / 18;
                int num3 = (int)(drawData.tileFrameX / 36);
                int num4 = num * 18;
                drawData.addFrX = num4 - (int)drawData.tileFrameX;
                int num5 = (int)(num2 * 18);
                if (this._chestPositions[point] != -1)
                {
                    int frame = Main.chest[this._chestPositions[point]].frame;
                    if (frame == 1)
                    {
                        num5 += 38;
                    }
                    if (frame == 2)
                    {
                        num5 += 76;
                    }
                }
                drawData.addFrY = num5 - (int)drawData.tileFrameY;
                if (num2 != 0)
                {
                    drawData.tileHeight = 18;
                }
                if (drawData.typeCache == 21 && (num3 == 48 || num3 == 49))
                {
                    drawData.glowSourceRect = new Rectangle(16 * (num % 2), (int)drawData.tileFrameY + drawData.addFrY, drawData.tileWidth, drawData.tileHeight);
                }
            }
            if (drawData.typeCache == 378)
            {
                Point point2 = new Point(tileX, tileY);
                if (drawData.tileFrameX % 36 != 0)
                {
                    point2.X--;
                }
                if (drawData.tileFrameY % 54 != 0)
                {
                    point2.Y -= (int)(drawData.tileFrameY / 18);
                }
                if (!this._trainingDummyTileEntityPositions.ContainsKey(point2))
                {
                    this._trainingDummyTileEntityPositions[point2] = TileEntityType<TETrainingDummy>.Find(point2.X, point2.Y);
                }
                TETrainingDummy tetrainingDummy;
                if (this._trainingDummyTileEntityPositions[point2] != -1 && TileEntity.TryGet<TETrainingDummy>(this._trainingDummyTileEntityPositions[point2], out tetrainingDummy))
                {
                    int npc = tetrainingDummy.npc;
                    if (npc != -1)
                    {
                        int num6 = Main.npc[npc].frame.Y / 55;
                        num6 *= 54;
                        num6 += (int)drawData.tileFrameY;
                        drawData.addFrY = num6 - (int)drawData.tileFrameY;
                    }
                }
            }
        }
References Terraria.GameContent.Drawing.TileDrawing._chestPositions, Terraria.GameContent.Drawing.TileDrawing._trainingDummyTileEntityPositions, Terraria.DataStructures.TileDrawInfo.addFrY, Terraria.ID.TileID.Sets.BasicChest, Terraria.Main.chest, System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), Terraria.DataStructures.TileEntityType< T >.Find(), Terraria.Chest.FindChest(), Terraria.Chest.frame, Terraria.NPC.frame, int, Terraria.GameContent.Tile_Entities.TETrainingDummy.npc, Terraria.Main.npc, Microsoft.Xna.Framework.Graphics.Point, Terraria.DataStructures.TileDrawInfo.tileFrameX, Terraria.DataStructures.TileDrawInfo.tileFrameY, Terraria.DataStructures.TileDrawInfo.tileHeight, Terraria.DataStructures.TileDrawInfo.tileWidth, Terraria.DataStructures.TileDrawInfo.typeCache, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Point.Y, and Microsoft.Xna.Framework.Rectangle.Y.
Referenced by Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile().