Terraria Decompiled: Terraria.GameContent.Drawing.TileDrawing.Draw
Draw()
void Terraria.GameContent.Drawing.TileDrawing.Draw (bool solidLayer, bool intoRenderTargets, int waterStyleOverride = -1) inline
Definition at line 384 of file TileDrawing.cs.
        {
            this.FlushLogData = (solidLayer ? TimeLogger.FlushSolidTiles : TimeLogger.FlushNonSolidTiles);
            this.DrawCallLogData = (solidLayer ? TimeLogger.SolidDrawCalls : TimeLogger.NonSolidDrawCalls);
            this._isActiveAndNotPaused = FocusHelper.AllowTileDrawingToEmitEffects;
            this._perspectivePlayer = Main.SceneMetrics.PerspectivePlayer;
            Vector2 unscaledPosition = Main.Camera.UnscaledPosition;
            if (!solidLayer)
            {
                Main.critterCage = false;
            }
            this.EnsureWindGridSize();
            this.ClearLegacyCachedDraws();
            this.ClearCachedTileDraws(solidLayer);
            float num = 255f * (1f - Main.gfxQuality) + 30f * Main.gfxQuality;
            this._highQualityLightingRequirement.R = (byte)num;
            this._highQualityLightingRequirement.G = (byte)((double)num * 1.1);
            this._highQualityLightingRequirement.B = (byte)((double)num * 1.2);
            float num2 = 50f * (1f - Main.gfxQuality) + 2f * Main.gfxQuality;
            this._mediumQualityLightingRequirement.R = (byte)num2;
            this._mediumQualityLightingRequirement.G = (byte)((double)num2 * 1.1);
            this._mediumQualityLightingRequirement.B = (byte)((double)num2 * 1.2);
            if (DebugOptions.devLightTilesCheat)
            {
                this._highQualityLightingRequirement.R = byte.MaxValue;
                this._highQualityLightingRequirement.G = byte.MaxValue;
                this._highQualityLightingRequirement.B = byte.MaxValue;
                this._mediumQualityLightingRequirement.R = byte.MaxValue;
                this._mediumQualityLightingRequirement.G = byte.MaxValue;
                this._mediumQualityLightingRequirement.B = byte.MaxValue;
            }
            Vector2 vector;
            int num3;
            int num4;
            int num5;
            int num6;
            TileDrawing.GetScreenDrawArea(!Main.drawToScreen, out vector, out num3, out num4, out num5, out num6);
            this.drawBlackHelper = new DrawBlackHelper(TileDrawing.Layer_Tiles, vector);
            byte b = (byte)(100f + 150f * Main.martianLight);
            this._martianGlow = new Color((int)b, (int)b, (int)b, 0);
            this._lastPaintLookupKey = new TilePaintSystemV2.TileVariationkey
            {
                TileType = -1
            };
            for (int i = num5; i < num6 + 4; i++)
            {
                for (int j = num3 - 2; j < num4 + 2; j++)
                {
                    Tile tile = Main.tile[j, i];
                    if (tile == null)
                    {
                        tile = new Tile();
                        Main.tile[j, i] = tile;
                        Main.mapTime += 60;
                    }
                    else if (tile.active() && this.IsTileDrawLayerSolid(tile.type) == solidLayer && (!DebugOptions.ShowUnbreakableWall || tile.wall != 350))
                    {
                        if (solidLayer)
{
                            Main.tileBatch.SetLayer(TileDrawing.Layer_LiquidBehindTiles, 0);
                            this.DrawTile_LiquidBehindTile(solidLayer, waterStyleOverride, unscaledPosition, vector, j, i, tile);
                        }
                        Main.tileBatch.SetLayer(TileDrawing.Layer_Tiles, 0);
                        ushort type = tile.type;
                        short frameX = tile.frameX;
                        short frameY = tile.frameY;
                        if (!TextureAssets.Tile[(int)type].IsLoaded)
{
                            Main.instance.LoadTiles((int)type);
                        }
                        if (type <= 454)
{
                            if (type <= 126)
{
                                if (type <= 52)
{
                                    if (type <= 34)
{
                                        if (type != 27)
{
                                            if (type != 34)
{
                                                goto IL_08C9;
                                            }
                                            if (frameX % 54 == 0 && frameY % 54 == 0)
{
                                                this.AddSpecialPoint(j, i, TileDrawing.TileCounterType.MultiTileVine);
                                                goto IL_08F0;
                                            }
                                            goto IL_08F0;
                                        }
                                        else
{
                                            if (frameX % 36 == 0 && frameY == 0)
{
                                                this.AddSpecialPoint(j, i, TileDrawing.TileCounterType.MultiTileGrass);
                                                goto IL_08F0;
                                            }
                                            goto IL_08F0;
                                        }
                                    }
                                    else
{
                                        if (type == 42)
{
                                            goto IL_063B;
                                        }
                                        if (type != 52)
{
                                            goto IL_08C9;
                                        }
                                        goto IL_05B4;
                                    }
                                }
                                else if (type <= 91)
{
                                    if (type == 62)
{
                                        goto IL_05B4;
                                    }
                                    if (type != 91)
{
                                        goto IL_08C9;
                                    }
                                    if (frameX % 18 == 0 && frameY % 54 == 0)
{
                                        this.AddSpecialPoint(j, i, TileDrawing.TileCounterType.MultiTileVine);
                                        goto IL_08F0;
                                    }
                                    goto IL_08F0;
                                }
                                else if (type != 95)
{
                                    if (type == 115)
{
                                        goto IL_05B4;
                                    }
                                    if (type != 126)
{
                                        goto IL_08C9;
                                    }
                                }
                            }
                            else if (type <= 238)
{
                                if (type <= 205)
{
                                    if (type == 184)
{
                                        this.AddSpecialPoint(j, i, TileDrawing.TileCounterType.AnyDirectionalGrass);
                                        goto IL_08F0;
                                    }
                                    if (type != 205)
{
                                        goto IL_08C9;
                                    }
                                    goto IL_05B4;
                                }
                                else if (type != 233)
{
                                    if (type != 236 && type != 238)
{
                                        goto IL_08C9;
                                    }
                                    goto IL_06EC;
                                }
                                else
{
                                    if (frameY == 0 && frameX % 54 == 0)
{
                                        this.AddSpecialPoint(j, i, TileDrawing.TileCounterType.MultiTileGrass);
                                    }
                                    if (frameY == 36 && frameX % 36 == 0)
{
                                        this.AddSpecialPoint(j, i, TileDrawing.TileCounterType.MultiTileGrass);
                                        goto IL_08F0;
                                    }
                                    goto IL_08F0;
                                }
                            }
                            else if (type <= 375)
{
                                if (type - 270 <= 1)
{
                                    goto IL_063B;
                                }
                                if (type - 373 > 2)
{
                                    goto IL_08C9;
                                }
                                goto IL_085B;
                            }
                            else
{
                                if (type == 382)
{
                                    goto IL_05B4;
                                }
                                if (type != 444)
{
                                    if (type != 454)
{
                                        goto IL_08C9;
                                    }
                                    if (frameX % 72 == 0 && frameY % 54 == 0)
{
                                        this.AddSpecialPoint(j, i, TileDrawing.TileCounterType.MultiTileVine);
                                        goto IL_08F0;
                                    }
                                    goto IL_08F0;
                                }
                            }
                            if (frameX % 36 == 0 && frameY % 36 == 0)
{
                                this.AddSpecialPoint(j, i, TileDrawing.TileCounterType.MultiTileVine);
                                goto IL_08F0;
                            }
                            goto IL_08F0;
                        }
                        else if (type <= 597)
{
                            if (type <= 530)
{
                                if (type <= 465)
{
                                    if (type == 461)
{
                                        goto IL_085B;
                                    }
                                    if (type != 465)
{
                                        goto IL_08C9;
                                    }
                                }
                                else
{
                                    switch (type)
{
                                    case 485:
                                    case 489:
                                    case 490:
                                        if (frameY == 0 && frameX % 36 == 0)
{
                                            this.AddSpecialPoint(j, i, TileDrawing.TileCounterType.MultiTileGrass);
                                            goto IL_08F0;
                                        }
                                        goto IL_08F0;
                                    case 486:
                                    case 487:
                                    case 488:
                                    case 492:
                                        goto IL_08C9;
                                    case 491:
                                        if (frameX == 18 && frameY == 18)
{
                                            this.AddSpecialPoint(j, i, TileDrawing.TileCounterType.VoidLens);
                                            goto IL_08E4;
                                        }
                                        goto IL_08E4;
                                    case 493:
                                        if (frameY == 0 && frameX % 18 == 0)
{
                                            this.AddSpecialPoint(j, i, TileDrawing.TileCounterType.MultiTileGrass);
                                            goto IL_08F0;
                                        }
                                        goto IL_08F0;
                                    default:
                                        switch (type)
{
                                        case 519:
                                            if (frameX / 18 <= 4)
{
                                                this.AddSpecialPoint(j, i, TileDrawing.TileCounterType.MultiTileGrass);
                                                goto IL_08F0;
                                            }
                                            goto IL_08F0;
                                        case 520:
                                        case 529:
                                            goto IL_08C9;
                                        case 521:
                                        case 522:
                                        case 523:
                                        case 524:
                                        case 525:
                                        case 526:
                                        case 527:
                                            if (frameY == 0 && frameX % 36 == 0)
{
                                                this.AddSpecialPoint(j, i, TileDrawing.TileCounterType.MultiTileGrass);
                                                goto IL_08F0;
                                            }
                                            goto IL_08F0;
                                        case 528:
                                            goto IL_05B4;
                                        case 530:
                                            if (frameX >= 270)
{
                                                goto IL_08E4;
                                            }
                                            if (frameX % 54 == 0 && frameY == 0)
{
                                                this.AddSpecialPoint(j, i, TileDrawing.TileCounterType.MultiTileGrass);
                                                goto IL_08F0;
                                            }
                                            goto IL_08F0;
                                        default:
                                            goto IL_08C9;
                                        }
                                        break;
                                    }
                                }
                            }
                            else if (type <= 572)
{
                                if (type == 549)
{
                                    this.CrawlToBottomOfReverseVineAndAddSpecialPoint(i, j);
                                    goto IL_08F0;
                                }
                                if (type != 572)
{
                                    goto IL_08C9;
                                }
                                goto IL_063B;
                            }
                            else
{
                                if (type == 581)
{
                                    goto IL_063B;
                                }
                                if (type - 591 > 1)
{
                                    if (type != 597)
{
                                        goto IL_08C9;
                                    }
                                    if (frameX % 54 == 0 && frameY == 0)
{
                                        this.AddSpecialPoint(j, i, TileDrawing.TileCounterType.TeleportationPylon);
                                        goto IL_08E4;
                                    }
                                    goto IL_08E4;
                                }
                            }
                            if (frameX % 36 == 0 && frameY % 54 == 0)
{
                                this.AddSpecialPoint(j, i, TileDrawing.TileCounterType.MultiTileVine);
                                goto IL_08F0;
                            }
                            goto IL_08F0;
                        }
                        else if (type <= 652)
{
                            if (type <= 636)
{
                                if (type != 617)
{
                                    if (type != 636)
{
                                        goto IL_08C9;
                                    }
                                }
                                else
{
                                    if (frameX % 54 == 0 && frameY % 72 == 0)
{
                                        this.AddSpecialPoint(j, i, TileDrawing.TileCounterType.MasterTrophy);
                                        goto IL_08E4;
                                    }
                                    goto IL_08E4;
                                }
                            }
                            else if (type != 638)
{
                                if (type != 651)
{
                                    if (type != 652)
{
                                        goto IL_08C9;
                                    }
                                    if (frameX % 36 == 0)
{
                                        this.AddSpecialPoint(j, i, TileDrawing.TileCounterType.MultiTileGrass);
                                        goto IL_08F0;
                                    }
                                    goto IL_08F0;
                                }
                                else
{
                                    if (frameX % 54 == 0)
{
                                        this.AddSpecialPoint(j, i, TileDrawing.TileCounterType.MultiTileGrass);
                                        goto IL_08F0;
                                    }
                                    goto IL_08F0;
                                }
                            }
                        }
                        else if (type <= 698)
{
                            if (type == 660)
{
                                goto IL_063B;
                            }
                            if (type != 698)
{
                                goto IL_08C9;
                            }
                            if (frameX % 18 == 0 && frameY == 0)
{
                                this.AddSpecialPoint(j, i, TileDrawing.TileCounterType.MultiTileVine);
                                goto IL_08F0;
                            }
                            goto IL_08F0;
                        }
                        else
{
                            if (type == 702)
{
                                goto IL_06EC;
                            }
                            if (type != 705)
{
                                if (type != 709)
{
                                    goto IL_08C9;
                                }
                                goto IL_085B;
                            }
                            else
{
                                if (frameX % 486 >= 270)
{
                                    goto IL_08E4;
                                }
                                if (frameX % 54 == 0 && frameY % 36 == 0)
{
                                    this.AddSpecialPoint(j, i, TileDrawing.TileCounterType.MultiTileGrass);
                                    goto IL_08F0;
                                }
                                goto IL_08F0;
                            }
                        }
                        IL_05B4:
                        this.CrawlToTopOfVineAndAddSpecialPoint(i, j);
                        goto IL_08F0;
                        IL_063B:
                        if (frameX % 18 == 0 && frameY % 36 == 0)
{
                            this.AddSpecialPoint(j, i, TileDrawing.TileCounterType.MultiTileVine);
                            goto IL_08F0;
                        }
                        goto IL_08F0;
                        IL_06EC:
                        if (frameX % 36 == 0 && frameY == 0)
{
                            this.AddSpecialPoint(j, i, TileDrawing.TileCounterType.MultiTileGrass);
                            goto IL_08F0;
                        }
                        goto IL_08F0;
                        IL_085B:
                        this.EmitLiquidDrops(i, j, tile, type);
                        goto IL_08F0;
                        IL_08C9:
                        if (this.ShouldSwayInWind(j, i, tile))
{
                            this.AddSpecialPoint(j, i, TileDrawing.TileCounterType.WindyGrass);
                            goto IL_08F0;
                        }
                        IL_08E4:
                        this.DrawSingleTile(unscaledPosition, vector, j, i);
                    }
                    IL_08F0:;
                }
            }
            this.drawBlackHelper.EndStrip();
            base.RestartLayeredBatch();
            if (solidLayer)
            {
                Main.instance.DrawTileCracks(1, Main.player[Main.myPlayer].hitReplace);
                Main.instance.DrawTileCracks(1, Main.player[Main.myPlayer].hitTile);
                base.RestartSpriteBatch();
            }
            this.DrawSpecialTilesLegacy(unscaledPosition, vector);
            if (TileObject.objectPreview.Active && Main.LocalPlayer.cursorItemIconEnabled && Main.placementPreview && !CaptureManager.Instance.Active)
            {
                Main.instance.LoadTiles((int)TileObject.objectPreview.Type);
                float placementPreviewOpacity = Main.LocalPlayer.GetPlacementPreviewOpacity();
                TileObject.DrawPreview(Main.spriteBatch, TileObject.objectPreview, unscaledPosition - vector, placementPreviewOpacity);
            }
        }
References Terraria.DataStructures.TileObjectPreviewData.Active, Terraria.Graphics.Capture.CaptureManager.Active, Terraria.Tile.active(), Terraria.GameContent.Drawing.TileDrawing.AddSpecialPoint(), Terraria.FocusHelper.AllowTileDrawingToEmitEffects, Terraria.Main.Camera, Terraria.GameContent.Drawing.TileDrawing.ClearCachedTileDraws(), Terraria.GameContent.Drawing.TileDrawing.ClearLegacyCachedDraws(), Microsoft.Xna.Framework.Graphics.Color, Terraria.GameContent.Drawing.TileDrawing.CrawlToBottomOfReverseVineAndAddSpecialPoint(), Terraria.GameContent.Drawing.TileDrawing.CrawlToTopOfVineAndAddSpecialPoint(), Terraria.Player.cursorItemIconEnabled, Terraria.Testing.DebugOptions.devLightTilesCheat, Terraria.GameContent.Drawing.TileDrawing.drawBlackHelper, Terraria.TileObject.DrawPreview(), Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile(), Terraria.GameContent.Drawing.TileDrawing.DrawSpecialTilesLegacy(), Terraria.GameContent.Drawing.TileDrawing.DrawTile_LiquidBehindTile(), Terraria.Main.DrawTileCracks(), Terraria.Main.drawToScreen, Terraria.GameContent.Drawing.TileDrawing.EmitLiquidDrops(), Terraria.GameContent.Drawing.DrawBlackHelper.EndStrip(), Terraria.GameContent.Drawing.TileDrawing.EnsureWindGridSize(), Terraria.TimeLogger.FlushNonSolidTiles, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Player.GetPlacementPreviewOpacity(), Terraria.GameContent.Drawing.TileDrawing.GetScreenDrawArea(), Terraria.Main.gfxQuality, Terraria.Player.hitReplace, Terraria.Player.hitTile, Terraria.Graphics.Capture.CaptureManager.Instance, Terraria.Main.instance, ReLogic.Content.Asset< T >.IsLoaded, Terraria.GameContent.Drawing.TileDrawing.Layer_LiquidBehindTiles, Terraria.GameContent.Drawing.TileDrawing.Layer_Tiles, Terraria.Main.LoadTiles(), Terraria.Main.LocalPlayer, Terraria.Main.martianLight, Terraria.Main.myPlayer, Terraria.TimeLogger.NonSolidDrawCalls, Terraria.TileObject.objectPreview, Terraria.SceneMetrics.PerspectivePlayer, Terraria.Main.placementPreview, Terraria.Main.player, Terraria.Main.SceneMetrics, Terraria.Graphics.TileBatch.SetLayer(), Terraria.GameContent.Drawing.TileDrawing.ShouldSwayInWind(), Terraria.Testing.DebugOptions.ShowUnbreakableWall, Terraria.Main.spriteBatch, Terraria.DataStructures.Tile, Terraria.GameContent.TextureAssets.Tile, Terraria.Main.tile, Terraria.Main.tileBatch, Terraria.DataStructures.TileObjectPreviewData.Type, Terraria.Tile.type, Terraria.Graphics.Camera.UnscaledPosition, and Terraria.Tile.wall.