Terraria Decompiled: Terraria.GameContent.Drawing.TileDrawing.MakeExtraPreparations
MakeExtraPreparations()
void Terraria.GameContent.Drawing.TileDrawing.MakeExtraPreparations (Tile tile, int x, int y) inline private
Definition at line 158 of file TileDrawing.cs.
        {
            ushort type = tile.type;
            if (type <= 589)
            {
                if (type != 5)
                {
                    if (type != 323)
                    {
                        if (type - 583 > 6)
{
                            return;
                        }
                        int num = 0;
                        int num2 = 0;
                        int num3 = 0;
                        int num4 = 0;
                        int num5 = 0;
                        int num6 = (tile.frameX == 44).ToInt() - (tile.frameX == 66).ToInt();
                        if (WorldGen.GetGemTreeFoliageData(x, y, num6, ref num, ref num5, out num2, out num3, out num4))
{
                            TilePaintSystemV2.TreeFoliageVariantKey treeFoliageVariantKey = new TilePaintSystemV2.TreeFoliageVariantKey
{
                                TextureIndex = num5,
                                PaintColor = (int)tile.color()
                            };
                            this._paintSystem.RequestTreeTop(ref treeFoliageVariantKey);
                            this._paintSystem.RequestTreeBranch(ref treeFoliageVariantKey);
                            return;
                        }
                    }
                    else
                    {
                        int num7 = 15;
                        if (x >= WorldGen.beachDistance && x <= Main.maxTilesX - WorldGen.beachDistance)
{
                            num7 = 21;
                        }
                        TilePaintSystemV2.TreeFoliageVariantKey treeFoliageVariantKey2 = new TilePaintSystemV2.TreeFoliageVariantKey
{
                            TextureIndex = num7,
                            PaintColor = (int)tile.color()
                        };
                        this._paintSystem.RequestTreeTop(ref treeFoliageVariantKey2);
                        this._paintSystem.RequestTreeBranch(ref treeFoliageVariantKey2);
                    }
                }
                else
                {
                    int num8 = 0;
                    int num9 = 0;
                    int num10 = 0;
                    int num11 = 0;
                    int num12 = 0;
                    int num13 = (tile.frameX == 44).ToInt() - (tile.frameX == 66).ToInt();
                    if (WorldGen.GetCommonTreeFoliageData(x, y, num13, ref num8, ref num12, out num9, out num10, out num11))
                    {
                        TilePaintSystemV2.TreeFoliageVariantKey treeFoliageVariantKey3 = new TilePaintSystemV2.TreeFoliageVariantKey
{
                            TextureIndex = num12,
                            PaintColor = (int)tile.color()
                        };
                        this._paintSystem.RequestTreeTop(ref treeFoliageVariantKey3);
                        this._paintSystem.RequestTreeBranch(ref treeFoliageVariantKey3);
                        return;
                    }
                }
            }
            else if (type != 596 && type != 616)
            {
                if (type != 634)
                {
                    return;
                }
                int num14 = 0;
                int num15 = 0;
                int num16 = 0;
                int num17 = 0;
                int num18 = 0;
                int num19 = (tile.frameX == 44).ToInt() - (tile.frameX == 66).ToInt();
                if (WorldGen.GetAshTreeFoliageData(x, y, num19, ref num14, ref num18, out num15, out num16, out num17))
                {
                    TilePaintSystemV2.TreeFoliageVariantKey treeFoliageVariantKey4 = new TilePaintSystemV2.TreeFoliageVariantKey
                    {
                        TextureIndex = num18,
                        PaintColor = (int)tile.color()
                    };
                    this._paintSystem.RequestTreeTop(ref treeFoliageVariantKey4);
                    this._paintSystem.RequestTreeBranch(ref treeFoliageVariantKey4);
                    return;
                }
            }
            else
            {
                int num20 = 0;
                int num21 = 0;
                int num22 = 0;
                int num23 = 0;
                int num24 = 0;
                int num25 = (tile.frameX == 44).ToInt() - (tile.frameX == 66).ToInt();
                if (WorldGen.GetVanityTreeFoliageData(x, y, num25, ref num20, ref num24, out num21, out num22, out num23))
                {
                    TilePaintSystemV2.TreeFoliageVariantKey treeFoliageVariantKey5 = new TilePaintSystemV2.TreeFoliageVariantKey
                    {
                        TextureIndex = num24,
                        PaintColor = (int)tile.color()
                    };
                    this._paintSystem.RequestTreeTop(ref treeFoliageVariantKey5);
                    this._paintSystem.RequestTreeBranch(ref treeFoliageVariantKey5);
                    return;
                }
            }
        }
References Terraria.GameContent.Drawing.TileDrawing._paintSystem, Terraria.WorldGen.beachDistance, Terraria.Tile.color(), Terraria.WorldGen.GetAshTreeFoliageData(), Terraria.WorldGen.GetCommonTreeFoliageData(), Terraria.WorldGen.GetGemTreeFoliageData(), Terraria.WorldGen.GetVanityTreeFoliageData(), int, Terraria.Main.maxTilesX, Terraria.GameContent.TilePaintSystemV2.RequestTreeBranch(), Terraria.GameContent.TilePaintSystemV2.RequestTreeTop(), and Terraria.Tile.type.
Referenced by Terraria.GameContent.Drawing.TileDrawing.PrepareForAreaDrawing().