Terraria Decompiled: Terraria.GameContent.Drawing.TileDrawing.GetWindCycle
GetWindCycle()
float Terraria.GameContent.Drawing.TileDrawing.GetWindCycle (int x, int y, double windCounter) inline private
Definition at line 9122 of file TileDrawing.cs.
        {
            if (!Main.SettingsEnabled_TilesSwayInWind)
            {
                return 0f;
            }
            float num = (float)x * 0.5f + (float)(y / 100) * 0.5f;
            float num2 = (float)Math.Cos(windCounter * 6.2831854820251465 + (double)num) * 0.5f;
            if (Main.remixWorld)
            {
                if ((double)y <= Main.worldSurface)
                {
                    return 0f;
                }
                num2 += Main.WindForVisuals;
            }
            else
            {
                if ((double)y >= Main.worldSurface)
                {
                    return 0f;
                }
                num2 += Main.WindForVisuals;
            }
            float lerpValue = Utils.GetLerpValue(0.08f, 0.18f, Math.Abs(Main.WindForVisuals), true);
            return num2 * lerpValue;
        }
References System.Math.Abs(), System.Math.Cos(), Terraria.Utils.GetLerpValue(), Terraria.Main.remixWorld, Terraria.Main.SettingsEnabled_TilesSwayInWind, Terraria.Main.WindForVisuals, and Terraria.Main.worldSurface.
Referenced by Terraria.GameContent.Drawing.TileDrawing.DrawAnyDirectionalGrass(), Terraria.GameContent.Drawing.TileDrawing.DrawGrass(), Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileGrassInWind(), Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileVinesInWind(), Terraria.GameContent.Drawing.TileDrawing.DrawRisingVineStrip(), Terraria.GameContent.Drawing.TileDrawing.DrawTrees(), and Terraria.GameContent.Drawing.TileDrawing.DrawVineStrip().