Terraria Decompiled: Terraria.GameContent.Drawing.TileDrawing.LavaLightA
LavaLightA()
static float Terraria.GameContent.Drawing.TileDrawing.LavaLightA (int tileX, int tileY) inline static private
Definition at line 989 of file TileDrawing.cs.
        {
            float num = TileDrawing.DistToWanderingCircle(new Point(tileX, tileY), 7, 2f, 0.025f, 2221713035U);
            float num2 = TileDrawing.DistToWanderingCircle(new Point(tileX + 3, tileY), 7, 2f, 0.025f, 657044585U);
            float num3 = TileDrawing.DistToWanderingCircle(new Point(tileX, tileY + 3), 7, 2f, 0.025f, 741521833U);
            float num4 = TileDrawing.DistToWanderingCircle(new Point(tileX + 3, tileY + 3), 7, 2f, 0.025f, 56936621U);
            float num5 = Math.Min(Math.Min(num, num2), Math.Min(num3, num4));
            num5 = TileDrawing.SmoothStep(1f - Utils.GetLerpValue(0f, 3.5f, num5, true));
            float num6 = 0f;
            if (!WorldGen.SolidTile(tileX, tileY - 1, false))
            {
                num6 = 0.8f;
            }
            return Utils.Remap(num5, 0.7f, 1f, num6, 1f, true);
        }
References Terraria.GameContent.Drawing.TileDrawing.DistToWanderingCircle(), Terraria.Utils.GetLerpValue(), System.Math.Min(), Microsoft.Xna.Framework.Graphics.Point, Terraria.Utils.Remap(), Terraria.GameContent.Drawing.TileDrawing.SmoothStep(), Terraria.WorldGen.SolidTile(), and System.U.
Referenced by Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile().