Terraria Decompiled: Terraria.GameContent.Drawing.TileDrawing.CrawlToBottomOfReverseVineAndAddSpecialPoint
CrawlToBottomOfReverseVineAndAddSpecialPoint()
void Terraria.GameContent.Drawing.TileDrawing.CrawlToBottomOfReverseVineAndAddSpecialPoint (int j, int i) inline private
Definition at line 900 of file TileDrawing.cs.
        {
            int num = j;
            for (int k = j; k < Main.maxTilesY; k++)
            {
                Tile tile = Main.tile[i, k];
                if (WorldGen.TopEdgeCanBeAttachedTo(i, k) || !tile.active())
                {
                    num = k - 1;
                    break;
                }
            }
            Point point = new Point(i, num);
            if (this._reverseVineRootsPositions.Contains(point))
            {
                return;
            }
            this._reverseVineRootsPositions.Add(point);
            this.AddSpecialPoint(i, num, TileDrawing.TileCounterType.ReverseVine);
        }
References Terraria.GameContent.Drawing.TileDrawing._reverseVineRootsPositions, Terraria.Tile.active(), System.Collections.Generic.List< T >.Add(), Terraria.GameContent.Drawing.TileDrawing.AddSpecialPoint(), System.Collections.Generic.List< T >.Contains(), Terraria.Main.maxTilesY, Microsoft.Xna.Framework.Graphics.Point, Terraria.Main.tile, and Terraria.WorldGen.TopEdgeCanBeAttachedTo().
Referenced by Terraria.GameContent.Drawing.TileDrawing.Draw().