Terraria Decompiled: Terraria.GameContent.Drawing.TileDrawing.PrepareForAreaDrawing
PrepareForAreaDrawing()
void Terraria.GameContent.Drawing.TileDrawing.PrepareForAreaDrawing (int firstTileX, int lastTileX, int firstTileY, int lastTileY, bool prepareLazily) inline
Definition at line 101 of file TileDrawing.cs.
        {
            TimeLogger.StartTimestamp startTimestamp = TimeLogger.Start();
            TilePaintSystemV2.TileVariationkey tileVariationkey = default(TilePaintSystemV2.TileVariationkey);
            TilePaintSystemV2.WallVariationKey wallVariationKey = default(TilePaintSystemV2.WallVariationKey);
            for (int i = firstTileY; i < lastTileY + 4; i++)
            {
                for (int j = firstTileX - 2; j < lastTileX + 2; j++)
                {
                    Tile tile = Main.tile[j, i];
                    if (tile != null)
                    {
                        if (tile.active())
{
                            Main.instance.LoadTiles((int)tile.type);
                            tileVariationkey.TileType = (int)tile.type;
                            tileVariationkey.PaintColor = (int)tile.color();
                            int num = 0;
                            ushort type = tile.type;
                            if (type != 5)
{
                                if (type == 323)
{
                                    num = this.GetPalmTreeBiome(j, i);
                                }
                            }
                            else
{
                                num = TileDrawing.GetTreeBiome(j, i, (int)tile.frameX, (int)tile.frameY);
                            }
                            tileVariationkey.TileStyle = num;
                            if (tileVariationkey.PaintColor != 0)
{
                                this._paintSystem.RequestTile(ref tileVariationkey);
                            }
                        }
                        if (tile.wall != 0)
{
                            Main.instance.LoadWall((int)tile.wall);
                            wallVariationKey.WallType = (int)tile.wall;
                            wallVariationKey.PaintColor = (int)tile.wallColor();
                            if (wallVariationKey.PaintColor != 0)
{
                                this._paintSystem.RequestWall(ref wallVariationKey);
                            }
                        }
                        if (!prepareLazily)
{
                            this.MakeExtraPreparations(tile, j, i);
                        }
                    }
                }
            }
            TimeLogger.FindPaintedTiles.AddTime(startTimestamp);
        }
References Terraria.GameContent.Drawing.TileDrawing._paintSystem, Terraria.Tile.active(), Terraria.Tile.color(), Terraria.TimeLogger.FindPaintedTiles, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.GameContent.Drawing.TileDrawing.GetPalmTreeBiome(), Terraria.GameContent.Drawing.TileDrawing.GetTreeBiome(), Terraria.Main.instance, int, Terraria.Main.LoadTiles(), Terraria.Main.LoadWall(), Terraria.GameContent.Drawing.TileDrawing.MakeExtraPreparations(), Terraria.GameContent.TilePaintSystemV2.TileVariationkey.PaintColor, Terraria.GameContent.TilePaintSystemV2.WallVariationKey.PaintColor, Terraria.GameContent.TilePaintSystemV2.RequestTile(), Terraria.GameContent.TilePaintSystemV2.RequestWall(), Terraria.TimeLogger.Start(), Terraria.Main.tile, Terraria.Tile.type, Terraria.Tile.wall, and Terraria.Tile.wallColor().
Referenced by Terraria.GameContent.Drawing.TileDrawing.PreparePaintForTilesOnScreen().