Terraria Decompiled: Terraria.GameContent.Drawing.TileDrawing.DrawXmasTree
DrawXmasTree()
void Terraria.GameContent.Drawing.TileDrawing.DrawXmasTree (Vector2 screenPosition, Vector2 screenOffset, int tileX, int tileY, TileDrawInfo drawData) inline private
Definition at line 4076 of file TileDrawing.cs.
        {
            int num = 2;
            if (tileY - (int)drawData.tileFrameY > 0 && drawData.tileFrameY == 7 && Main.tile[tileX, tileY - (int)drawData.tileFrameY] != null)
            {
                drawData.tileTop -= (int)(16 * drawData.tileFrameY);
                drawData.tileFrameX = Main.tile[tileX, tileY - (int)drawData.tileFrameY].frameX;
                drawData.tileFrameY = Main.tile[tileX, tileY - (int)drawData.tileFrameY].frameY;
            }
            if (drawData.tileFrameX >= 10)
            {
                int num2 = 0;
                if ((drawData.tileFrameY & 1) == 1)
                {
                    num2++;
                }
                if ((drawData.tileFrameY & 2) == 2)
                {
                    num2 += 2;
                }
                if ((drawData.tileFrameY & 4) == 4)
                {
                    num2 += 4;
                }
                int num3 = 0;
                if ((drawData.tileFrameY & 8) == 8)
                {
                    num3++;
                }
                if ((drawData.tileFrameY & 16) == 16)
                {
                    num3 += 2;
                }
                if ((drawData.tileFrameY & 32) == 32)
                {
                    num3 += 4;
                }
                int num4 = 0;
                if ((drawData.tileFrameY & 64) == 64)
                {
                    num4++;
                }
                if ((drawData.tileFrameY & 128) == 128)
                {
                    num4 += 2;
                }
                if ((drawData.tileFrameY & 256) == 256)
                {
                    num4 += 4;
                }
                if ((drawData.tileFrameY & 512) == 512)
                {
                    num4 += 8;
                }
                int num5 = 0;
                if ((drawData.tileFrameY & 1024) == 1024)
                {
                    num5++;
                }
                if ((drawData.tileFrameY & 2048) == 2048)
                {
                    num5 += 2;
                }
                if ((drawData.tileFrameY & 4096) == 4096)
                {
                    num5 += 4;
                }
                if ((drawData.tileFrameY & 8192) == 8192)
                {
                    num5 += 8;
                }
                Color color = Lighting.GetColor(tileX + 1, tileY - 3);
                Main.tileBatch.Draw(TextureAssets.XmasTree[0].Value, new Vector2((float)(tileX * 16 - (int)screenPosition.X) - ((float)drawData.tileWidth - 16f) / 2f, (float)(tileY * 16 - (int)screenPosition.Y + drawData.tileTop + num)) + screenOffset, new Rectangle?(new Rectangle(0, 0, 64, 128)), color, TileDrawing._zero, 1f, SpriteEffects.None);
                if (num2 > 0)
                {
                    num2--;
                    Color color2 = color;
                    if (num2 != 3)
                    {
                        color2 = new Color(255, 255, 255, 255);
                    }
                    Main.tileBatch.Draw(TextureAssets.XmasTree[3].Value, new Vector2((float)(tileX * 16 - (int)screenPosition.X) - ((float)drawData.tileWidth - 16f) / 2f, (float)(tileY * 16 - (int)screenPosition.Y + drawData.tileTop + num)) + screenOffset, new Rectangle?(new Rectangle(66 * num2, 0, 64, 128)), color2, TileDrawing._zero, 1f, SpriteEffects.None);
                }
                if (num3 > 0)
                {
                    num3--;
                    Main.tileBatch.Draw(TextureAssets.XmasTree[1].Value, new Vector2((float)(tileX * 16 - (int)screenPosition.X) - ((float)drawData.tileWidth - 16f) / 2f, (float)(tileY * 16 - (int)screenPosition.Y + drawData.tileTop + num)) + screenOffset, new Rectangle?(new Rectangle(66 * num3, 0, 64, 128)), color, TileDrawing._zero, 1f, SpriteEffects.None);
                }
                if (num4 > 0)
                {
                    num4--;
                    Main.tileBatch.Draw(TextureAssets.XmasTree[2].Value, new Vector2((float)(tileX * 16 - (int)screenPosition.X) - ((float)drawData.tileWidth - 16f) / 2f, (float)(tileY * 16 - (int)screenPosition.Y + drawData.tileTop + num)) + screenOffset, new Rectangle?(new Rectangle(66 * num4, 0, 64, 128)), color, TileDrawing._zero, 1f, SpriteEffects.None);
                }
                if (num5 > 0)
                {
                    num5--;
                    Main.tileBatch.Draw(TextureAssets.XmasTree[4].Value, new Vector2((float)(tileX * 16 - (int)screenPosition.X) - ((float)drawData.tileWidth - 16f) / 2f, (float)(tileY * 16 - (int)screenPosition.Y + drawData.tileTop + num)) + screenOffset, new Rectangle?(new Rectangle(66 * num5, 130 * Main.tileFrame[171], 64, 128)), new Color(255, 255, 255, 255), TileDrawing._zero, 1f, SpriteEffects.None);
                }
            }
        }
References Terraria.GameContent.Drawing.TileDrawing._zero, Microsoft.Xna.Framework.Graphics.Color, Terraria.Graphics.TileBatch.Draw(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Lighting.GetColor(), int, Terraria.Main.tile, Terraria.Main.tileBatch, Terraria.Main.tileFrame, Terraria.DataStructures.TileDrawInfo.tileFrameX, Terraria.DataStructures.TileDrawInfo.tileFrameY, Terraria.DataStructures.TileDrawInfo.tileTop, Terraria.DataStructures.TileDrawInfo.tileWidth, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Vector2.X, Terraria.GameContent.TextureAssets.XmasTree, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile().