Terraria Decompiled: Terraria.GameContent.Drawing.TileDrawing.PostDrawTiles
PostDrawTiles()
void Terraria.GameContent.Drawing.TileDrawing.PostDrawTiles (bool solidLayer) inline
Definition at line 326 of file TileDrawing.cs.
        {
            if (!solidLayer)
            {
                TimeLogger.StartTimestamp startTimestamp = TimeLogger.Start();
                SpriteBatchBeginner spriteBatchBeginner = new SpriteBatchBeginner(SpriteSortMode.Deferred, BlendState.AlphaBlend, Main.DefaultSamplerState, DepthStencilState.None, Main.Rasterizer, null, Main.Transform);
                spriteBatchBeginner.Begin(Main.spriteBatch);
                this.DrawMultiTileVines();
                this.DrawMultiTileGrass();
                this.DrawVoidLenses();
                this.DrawTeleportationPylons();
                this.DrawMasterTrophies();
                this.DrawGrass();
                this.DrawAnyDirectionalGrass();
                this.DrawTrees();
                this.DrawVines();
                this.DrawReverseVines();
                Main.spriteBatch.End();
                TimeLogger.TileExtras.AddTime(startTimestamp);
                this._natureRenderer.DrawAfterAllObjects(spriteBatchBeginner);
            }
            if (solidLayer)
            {
                TimeLogger.StartTimestamp startTimestamp2 = TimeLogger.Start();
                this.DrawEntities_HatRacks();
                this.DrawEntities_DisplayDolls();
                TimeLogger.ClothingRacks.AddTime(startTimestamp2);
            }
        }
References Terraria.GameContent.Drawing.TileDrawing._natureRenderer, Microsoft.Xna.Framework.Graphics.BlendState.AlphaBlend, Terraria.DataStructures.SpriteBatchBeginner.Begin(), Terraria.TimeLogger.ClothingRacks, Terraria.Main.DefaultSamplerState, Terraria.GameContent.Drawing.INatureRenderer.DrawAfterAllObjects(), Terraria.GameContent.Drawing.TileDrawing.DrawAnyDirectionalGrass(), Terraria.GameContent.Drawing.TileDrawing.DrawEntities_DisplayDolls(), Terraria.GameContent.Drawing.TileDrawing.DrawEntities_HatRacks(), Terraria.GameContent.Drawing.TileDrawing.DrawGrass(), Terraria.GameContent.Drawing.TileDrawing.DrawMasterTrophies(), Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileGrass(), Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileVines(), Terraria.GameContent.Drawing.TileDrawing.DrawReverseVines(), Terraria.GameContent.Drawing.TileDrawing.DrawTeleportationPylons(), Terraria.GameContent.Drawing.TileDrawing.DrawTrees(), Terraria.GameContent.Drawing.TileDrawing.DrawVines(), Terraria.GameContent.Drawing.TileDrawing.DrawVoidLenses(), Microsoft.Xna.Framework.Graphics.SpriteBatch.End(), Microsoft.Xna.Framework.Graphics.DepthStencilState.None, Terraria.Main.Rasterizer, Terraria.Main.spriteBatch, Terraria.TimeLogger.Start(), Terraria.TimeLogger.TileExtras, and Terraria.Main.Transform.