Terraria Decompiled: Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileVines
DrawMultiTileVines()
void Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileVines () inline private
Definition at line 10436 of file TileDrawing.cs.
        {
            Vector2 unscaledPosition = Main.Camera.UnscaledPosition;
            Vector2 zero = Vector2.Zero;
            int num = 3;
            int num2 = this._specialsCount[num];
            for (int i = 0; i < num2; i++)
            {
                Point point = this._specialPositions[num][i];
                int x = point.X;
                int y = point.Y;
                int num3 = 1;
                int num4 = 1;
                Tile tile = Main.tile[x, y];
                if (tile != null && tile.active())
                {
                    ushort type = Main.tile[x, y].type;
                    if (type <= 444)
                    {
                        if (type <= 91)
{
                            if (type != 34)
{
                                if (type == 42)
{
                                    goto IL_014E;
                                }
                                if (type == 91)
{
                                    num3 = 1;
                                    num4 = 3;
                                }
                            }
                            else
{
                                num3 = 3;
                                num4 = 3;
                            }
                        }
                        else
{
                            if (type <= 126)
{
                                if (type != 95 && type != 126)
{
                                    goto IL_0174;
                                }
                            }
                            else
{
                                if (type - 270 <= 1)
{
                                    goto IL_014E;
                                }
                                if (type != 444)
{
                                    goto IL_0174;
                                }
                            }
                            num3 = 2;
                            num4 = 2;
                        }
                    }
                    else
                    {
                        if (type <= 572)
{
                            if (type == 454)
{
                                num3 = 4;
                                num4 = 3;
                                goto IL_0174;
                            }
                            if (type != 465)
{
                                if (type != 572)
{
                                    goto IL_0174;
                                }
                                goto IL_014E;
                            }
                        }
                        else if (type <= 592)
{
                            if (type == 581)
{
                                goto IL_014E;
                            }
                            if (type - 591 > 1)
{
                                goto IL_0174;
                            }
                        }
                        else
{
                            if (type == 660)
{
                                goto IL_014E;
                            }
                            if (type != 698)
{
                                goto IL_0174;
                            }
                            num3 = 1;
                            num4 = 1;
                            goto IL_0174;
                        }
                        num3 = 2;
                        num4 = 3;
                    }
                    IL_0174:
                    this.DrawMultiTileVinesInWind(unscaledPosition, zero, x, y, num3, num4);
                    goto IL_0184;
                    IL_014E:
                    num3 = 1;
                    num4 = 2;
                    goto IL_0174;
                }
                IL_0184:;
            }
        }
References Terraria.GameContent.Drawing.TileDrawing._specialPositions, Terraria.GameContent.Drawing.TileDrawing._specialsCount, Terraria.Tile.active(), Terraria.Main.Camera, Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileVinesInWind(), Terraria.Main.tile, Terraria.Tile.type, Terraria.Graphics.Camera.UnscaledPosition, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Point.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.Drawing.TileDrawing.PostDrawTiles().