Terraria Decompiled: Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.ModifyEntriesThatNeedIt
ModifyEntriesThatNeedIt()
void Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.ModifyEntriesThatNeedIt () inline private
Definition at line 99 of file BestiaryDatabaseNPCsPopulator.cs.
        {
            this.FindEntryByNPCID(258).AddTags(new IBestiaryInfoElement[]
            {
                new BestiaryPortraitBackgroundProviderPreferenceInfoElement(BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.SurfaceMushroom)
            });
            this.FindEntryByNPCID(-1).AddTags(new IBestiaryInfoElement[]
            {
                new BestiaryPortraitBackgroundProviderPreferenceInfoElement(BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.TheCorruption)
            });
            this.FindEntryByNPCID(81).AddTags(new IBestiaryInfoElement[]
            {
                new BestiaryPortraitBackgroundProviderPreferenceInfoElement(BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.TheCorruption)
            });
            this.FindEntryByNPCID(121).AddTags(new IBestiaryInfoElement[]
            {
                new BestiaryPortraitBackgroundProviderPreferenceInfoElement(BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.TheCorruption)
            });
            this.FindEntryByNPCID(7).AddTags(new IBestiaryInfoElement[]
            {
                new BestiaryPortraitBackgroundProviderPreferenceInfoElement(BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.TheCorruption)
            });
            this.FindEntryByNPCID(98).AddTags(new IBestiaryInfoElement[]
            {
                new BestiaryPortraitBackgroundProviderPreferenceInfoElement(BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.TheCorruption)
            });
            this.FindEntryByNPCID(6).AddTags(new IBestiaryInfoElement[]
            {
                new BestiaryPortraitBackgroundProviderPreferenceInfoElement(BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.TheCorruption)
            });
            this.FindEntryByNPCID(94).AddTags(new IBestiaryInfoElement[]
            {
                new BestiaryPortraitBackgroundProviderPreferenceInfoElement(BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.TheCorruption)
            });
            this.FindEntryByNPCID(173).AddTags(new IBestiaryInfoElement[]
            {
                new BestiaryPortraitBackgroundProviderPreferenceInfoElement(BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.TheCrimson)
            });
            this.FindEntryByNPCID(181).AddTags(new IBestiaryInfoElement[]
            {
                new BestiaryPortraitBackgroundProviderPreferenceInfoElement(BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.TheCrimson)
            });
            this.FindEntryByNPCID(183).AddTags(new IBestiaryInfoElement[]
            {
                new BestiaryPortraitBackgroundProviderPreferenceInfoElement(BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.TheCrimson)
            });
            this.FindEntryByNPCID(242).AddTags(new IBestiaryInfoElement[]
            {
                new BestiaryPortraitBackgroundProviderPreferenceInfoElement(BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.TheCrimson)
            });
            this.FindEntryByNPCID(241).AddTags(new IBestiaryInfoElement[]
            {
                new BestiaryPortraitBackgroundProviderPreferenceInfoElement(BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.TheCrimson)
            });
            this.FindEntryByNPCID(174).AddTags(new IBestiaryInfoElement[]
            {
                new BestiaryPortraitBackgroundProviderPreferenceInfoElement(BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.TheCrimson)
            });
            this.FindEntryByNPCID(240).AddTags(new IBestiaryInfoElement[]
            {
                new BestiaryPortraitBackgroundProviderPreferenceInfoElement(BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.TheCrimson)
            });
            this.FindEntryByNPCID(175).AddTags(new IBestiaryInfoElement[]
            {
                new BestiaryPortraitBackgroundProviderPreferenceInfoElement(BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.UndergroundJungle)
            });
            this.FindEntryByNPCID(153).AddTags(new IBestiaryInfoElement[]
            {
                new BestiaryPortraitBackgroundProviderPreferenceInfoElement(BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.Jungle)
            });
            this.FindEntryByNPCID(52).AddTags(new IBestiaryInfoElement[]
            {
                new BestiaryPortraitBackgroundProviderPreferenceInfoElement(BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.Jungle)
            });
            this.FindEntryByNPCID(58).AddTags(new IBestiaryInfoElement[]
            {
                new BestiaryPortraitBackgroundProviderPreferenceInfoElement(BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.Jungle)
            });
            this.FindEntryByNPCID(102).AddTags(new IBestiaryInfoElement[]
            {
                new BestiaryPortraitBackgroundProviderPreferenceInfoElement(BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.Caverns)
            });
            this.FindEntryByNPCID(157).AddTags(new IBestiaryInfoElement[]
            {
                new BestiaryPortraitBackgroundProviderPreferenceInfoElement(BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.Jungle)
            });
            this.FindEntryByNPCID(51).AddTags(new IBestiaryInfoElement[]
            {
                new BestiaryPortraitBackgroundProviderPreferenceInfoElement(BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.Jungle)
            });
            this.FindEntryByNPCID(169).AddTags(new IBestiaryInfoElement[]
            {
                new BestiaryPortraitBackgroundProviderPreferenceInfoElement(BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.UndergroundSnow)
            });
            this.FindEntryByNPCID(510).AddTags(new IBestiaryInfoElement[]
            {
                new BestiaryPortraitBackgroundProviderPreferenceInfoElement(BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.UndergroundDesert)
            });
            this.FindEntryByNPCID(69).AddTags(new IBestiaryInfoElement[]
            {
                new BestiaryPortraitBackgroundProviderPreferenceInfoElement(BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.Desert)
            });
            this.FindEntryByNPCID(580).AddTags(new IBestiaryInfoElement[]
            {
                new BestiaryPortraitBackgroundProviderPreferenceInfoElement(BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.UndergroundDesert)
            });
            this.FindEntryByNPCID(581).AddTags(new IBestiaryInfoElement[]
            {
                new BestiaryPortraitBackgroundProviderPreferenceInfoElement(BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.UndergroundDesert)
            });
            this.FindEntryByNPCID(78).AddTags(new IBestiaryInfoElement[]
            {
                new BestiaryPortraitBackgroundProviderPreferenceInfoElement(BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.Desert)
            });
            this.FindEntryByNPCID(79).AddTags(new IBestiaryInfoElement[]
            {
                new BestiaryPortraitBackgroundProviderPreferenceInfoElement(BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.CorruptDesert)
            });
            this.FindEntryByNPCID(630).AddTags(new IBestiaryInfoElement[]
            {
                new BestiaryPortraitBackgroundProviderPreferenceInfoElement(BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.CrimsonDesert)
            });
            this.FindEntryByNPCID(80).AddTags(new IBestiaryInfoElement[]
            {
                new BestiaryPortraitBackgroundProviderPreferenceInfoElement(BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.HallowDesert)
            });
            this.FindEntryByNPCID(533).AddTags(new IBestiaryInfoElement[]
            {
                new BestiaryPortraitBackgroundBasedOnWorldEvilProviderPreferenceInfoElement(BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.CorruptUndergroundDesert, BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.CrimsonUndergroundDesert)
            });
            this.FindEntryByNPCID(528).AddTags(new IBestiaryInfoElement[]
            {
                new BestiaryPortraitBackgroundProviderPreferenceInfoElement(BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.UndergroundDesert)
            });
            this.FindEntryByNPCID(529).AddTags(new IBestiaryInfoElement[]
            {
                new BestiaryPortraitBackgroundBasedOnWorldEvilProviderPreferenceInfoElement(BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.CorruptUndergroundDesert, BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.CrimsonUndergroundDesert)
            });
            this._currentDatabase.ApplyPass(new BestiaryDatabase.BestiaryEntriesPass(this.TryGivingEntryFlavorTextIfItIsMissing));
            BestiaryEntry bestiaryEntry = this.FindEntryByNPCID(398);
            bestiaryEntry.Info.Add(new MoonLordPortraitBackgroundProviderBestiaryInfoElement());
            bestiaryEntry.Info.RemoveAll((IBestiaryInfoElement x) => x is NamePlateInfoElement);
            bestiaryEntry.Info.Add(new NamePlateInfoElement("Enemies.MoonLord", 398));
            bestiaryEntry.Icon = new UnlockableNPCEntryIcon(398, 0f, 0f, 0f, 0f, "Enemies.MoonLord");
            BestiaryEntry bestiaryEntry2 = this.FindEntryByNPCID(664);
            bestiaryEntry2.Info.RemoveAll((IBestiaryInfoElement x) => x is NPCKillCounterInfoElement);
            this.FindEntryByNPCID(687).Info.RemoveAll((IBestiaryInfoElement x) => x is NPCKillCounterInfoElement);
            this.ModifyEntriesThatNeedIt_NameOverride(637, "Friends.TownCat");
            this.ModifyEntriesThatNeedIt_NameOverride(638, "Friends.TownDog");
            this.ModifyEntriesThatNeedIt_NameOverride(656, "Friends.TownBunny");
            for (int i = 494; i <= 506; i++)
            {
                this.FindEntryByNPCID(i).UIInfoProvider = new SalamanderShellyDadUICollectionInfoProvider(ContentSamples.NpcBestiaryCreditIdsByNpcNetIds[i]);
            }
            this.FindEntryByNPCID(534).UIInfoProvider = new HighestOfMultipleUICollectionInfoProvider(new IBestiaryUICollectionInfoProvider[]
            {
                new CommonEnemyUICollectionInfoProvider(ContentSamples.NpcBestiaryCreditIdsByNpcNetIds[534], false),
                new TownNPCUICollectionInfoProvider(ContentSamples.NpcBestiaryCreditIdsByNpcNetIds[441])
            });
            foreach (NPCStatsReportInfoElement npcstatsReportInfoElement in from x in this.FindEntryByNPCID(13).Info
                select x as NPCStatsReportInfoElement into x
                where x != null
                select x)
            {
                npcstatsReportInfoElement.OnRefreshStats += this.AdjustEaterOfWorldStats;
            }
            foreach (NPCStatsReportInfoElement npcstatsReportInfoElement2 in from x in this.FindEntryByNPCID(491).Info
                select x as NPCStatsReportInfoElement into x
                where x != null
                select x)
            {
                npcstatsReportInfoElement2.OnRefreshStats += this.AdjustPirateShipStats;
            }
            this.FindEntryByNPCID(395).Info.RemoveAll((IBestiaryInfoElement x) => x is BossBestiaryInfoElement);
            foreach (NPCStatsReportInfoElement npcstatsReportInfoElement3 in from x in bestiaryEntry2.Info
                select x as NPCStatsReportInfoElement into x
                where x != null
                select x)
            {
                npcstatsReportInfoElement3.OnRefreshStats += this.HideStats;
            }
            this.FindEntryByNPCID(68).UIInfoProvider = new HighestOfMultipleUICollectionInfoProvider(new IBestiaryUICollectionInfoProvider[]
            {
                new CommonEnemyUICollectionInfoProvider(ContentSamples.NpcBestiaryCreditIdsByNpcNetIds[68], true),
                new CommonEnemyUICollectionInfoProvider(ContentSamples.NpcBestiaryCreditIdsByNpcNetIds[35], true),
                new TownNPCUICollectionInfoProvider(ContentSamples.NpcBestiaryCreditIdsByNpcNetIds[54])
            });
            this.FindEntryByNPCID(35).UIInfoProvider = new HighestOfMultipleUICollectionInfoProvider(new IBestiaryUICollectionInfoProvider[]
            {
                new CommonEnemyUICollectionInfoProvider(ContentSamples.NpcBestiaryCreditIdsByNpcNetIds[35], true),
                new TownNPCUICollectionInfoProvider(ContentSamples.NpcBestiaryCreditIdsByNpcNetIds[54])
            });
            this.FindEntryByNPCID(37).UIInfoProvider = new HighestOfMultipleUICollectionInfoProvider(new IBestiaryUICollectionInfoProvider[]
            {
                new TownNPCUICollectionInfoProvider(ContentSamples.NpcBestiaryCreditIdsByNpcNetIds[37]),
                new TownNPCUICollectionInfoProvider(ContentSamples.NpcBestiaryCreditIdsByNpcNetIds[54]),
                new CommonEnemyUICollectionInfoProvider(ContentSamples.NpcBestiaryCreditIdsByNpcNetIds[35], true)
            });
            this.FindEntryByNPCID(565).UIInfoProvider = new CommonEnemyUICollectionInfoProvider(ContentSamples.NpcBestiaryCreditIdsByNpcNetIds[565], true);
            this.FindEntryByNPCID(577).UIInfoProvider = new CommonEnemyUICollectionInfoProvider(ContentSamples.NpcBestiaryCreditIdsByNpcNetIds[577], true);
            this.FindEntryByNPCID(551).UIInfoProvider = new CommonEnemyUICollectionInfoProvider(ContentSamples.NpcBestiaryCreditIdsByNpcNetIds[551], true);
            this.FindEntryByNPCID(491).UIInfoProvider = new CommonEnemyUICollectionInfoProvider(ContentSamples.NpcBestiaryCreditIdsByNpcNetIds[491], true);
            foreach (KeyValuePair<int, int> keyValuePair in new Dictionary<int, int>
            {
                { 5, 4 },
                { 267, 266 },
                { 115, 113 },
                { 116, 113 },
                { 117, 113 },
                { 139, 134 },
                { 372, 370 },
                { 658, 657 },
                { 659, 657 },
                { 660, 657 },
                { 454, 439 },
                { 521, 439 }
            })
            {
                int key = keyValuePair.Key;
                int value = keyValuePair.Value;
                this.FindEntryByNPCID(key).UIInfoProvider = new CommonEnemyUICollectionInfoProvider(ContentSamples.NpcBestiaryCreditIdsByNpcNetIds[value], true);
            }
            foreach (KeyValuePair<int, int[]> keyValuePair2 in new Dictionary<int, int[]>
            {
                {
                    443,
                    new int[] { 46 }
                },
                {
                    442,
                    new int[] { 74 }
                },
                {
                    592,
                    new int[] { 55 }
                },
                {
                    444,
                    new int[] { 356 }
                },
                {
                    601,
                    new int[] { 599 }
                },
                {
                    445,
                    new int[] { 361 }
                },
                {
                    446,
                    new int[] { 377 }
                },
                {
                    605,
                    new int[] { 604 }
                },
                {
                    447,
                    new int[] { 300 }
                },
                {
                    627,
                    new int[] { 626 }
                },
                {
                    613,
                    new int[] { 612 }
                },
                {
                    448,
                    new int[] { 357 }
                },
                {
                    539,
                    new int[] { 299, 538 }
                }
            })
            {
                this.FindEntryByNPCID(keyValuePair2.Key).UIInfoProvider = new GoldCritterUICollectionInfoProvider(keyValuePair2.Value, ContentSamples.NpcBestiaryCreditIdsByNpcNetIds[keyValuePair2.Key]);
            }
            foreach (KeyValuePair<int, int> keyValuePair3 in new Dictionary<int, int>
            {
                { 362, 363 },
                { 364, 365 },
                { 602, 603 },
                { 608, 609 }
            })
            {
                this.FindEntryByNPCID(keyValuePair3.Key).UIInfoProvider = new HighestOfMultipleUICollectionInfoProvider(new IBestiaryUICollectionInfoProvider[]
                {
                    new CritterUICollectionInfoProvider(ContentSamples.NpcBestiaryCreditIdsByNpcNetIds[keyValuePair3.Key]),
                    new CritterUICollectionInfoProvider(ContentSamples.NpcBestiaryCreditIdsByNpcNetIds[keyValuePair3.Value])
                });
            }
            this.FindEntryByNPCID(4).AddTags(new IBestiaryInfoElement[]
            {
                new SearchAliasInfoElement("eoc")
            });
            this.FindEntryByNPCID(13).AddTags(new IBestiaryInfoElement[]
            {
                new SearchAliasInfoElement("eow")
            });
            this.FindEntryByNPCID(266).AddTags(new IBestiaryInfoElement[]
            {
                new SearchAliasInfoElement("boc")
            });
            this.FindEntryByNPCID(113).AddTags(new IBestiaryInfoElement[]
            {
                new SearchAliasInfoElement("wof")
            });
            this.FindEntryByNPCID(50).AddTags(new IBestiaryInfoElement[]
            {
                new SearchAliasInfoElement("slime king")
            });
            this.FindEntryByNPCID(125).AddTags(new IBestiaryInfoElement[]
            {
                new SearchAliasInfoElement("the twins")
            });
            this.FindEntryByNPCID(126).AddTags(new IBestiaryInfoElement[]
            {
                new SearchAliasInfoElement("the twins")
            });
            this.FindEntryByNPCID(222).AddTags(new IBestiaryInfoElement[]
            {
                new SearchAliasInfoElement("qb")
            });
            this.FindEntryByNPCID(222).AddTags(new IBestiaryInfoElement[]
            {
                new SearchAliasInfoElement("bee queen")
            });
            this.FindEntryByNPCID(398).AddTags(new IBestiaryInfoElement[]
            {
                new SearchAliasInfoElement("moonlord")
            });
            this.FindEntryByNPCID(398).AddTags(new IBestiaryInfoElement[]
            {
                new SearchAliasInfoElement("cthulhu")
            });
            this.FindEntryByNPCID(398).AddTags(new IBestiaryInfoElement[]
            {
                new SearchAliasInfoElement("ml")
            });
            this.FindEntryByNPCID(125).AddTags(new IBestiaryInfoElement[]
            {
                new SearchAliasInfoElement("mech boss")
            });
            this.FindEntryByNPCID(126).AddTags(new IBestiaryInfoElement[]
            {
                new SearchAliasInfoElement("mech boss")
            });
            this.FindEntryByNPCID(127).AddTags(new IBestiaryInfoElement[]
            {
                new SearchAliasInfoElement("mech boss")
            });
            this.FindEntryByNPCID(134).AddTags(new IBestiaryInfoElement[]
            {
                new SearchAliasInfoElement("mech boss")
            });
            this.FindEntryByNPCID(657).AddTags(new IBestiaryInfoElement[]
            {
                new SearchAliasInfoElement("slime queen")
            });
            this.FindEntryByNPCID(636).AddTags(new IBestiaryInfoElement[]
            {
                new SearchAliasInfoElement("eol")
            });
            this.FindEntryByNPCID(636).AddTags(new IBestiaryInfoElement[]
            {
                new SearchAliasInfoElement("fairy")
            });
        }
References Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator._currentDatabase, Terraria.GameContent.Bestiary.BestiaryEntry.AddTags(), Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.AdjustEaterOfWorldStats(), Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.AdjustPirateShipStats(), Terraria.GameContent.Bestiary.BestiaryDatabase.ApplyPass(), Terraria.GameContent.Bestiary.BestiaryDatabase.BestiaryEntriesPass(), Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.Caverns, Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.CorruptDesert, Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.CorruptUndergroundDesert, Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.CrimsonDesert, Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.CrimsonUndergroundDesert, Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.Desert, Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.FindEntryByNPCID(), Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.HallowDesert, Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.HideStats(), Terraria.GameContent.Bestiary.BestiaryEntry.Info, Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.Jungle, System.Collections.Generic.KeyValuePair< TKey, TValue >.Key, System.key, Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.ModifyEntriesThatNeedIt_NameOverride(), Terraria.ID.ContentSamples.NpcBestiaryCreditIdsByNpcNetIds, Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.SurfaceMushroom, Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.TheCorruption, Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.TheCrimson, Terraria.GameContent.Bestiary.BestiaryEntry.UIInfoProvider, Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.UndergroundDesert, Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.UndergroundJungle, Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.UndergroundSnow, System.Collections.Generic.KeyValuePair< TKey, TValue >.Value, and System.value.
Referenced by Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.Populate().