Terraria Decompiled: Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.Populate
Populate()
void Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.Populate (BestiaryDatabase database) inline
Definition at line 37 of file BestiaryDatabaseNPCsPopulator.cs.
        {
            this._currentDatabase = database;
            this.AddEmptyEntries_CrittersAndEnemies_Automated();
            this.AddTownNPCs_Manual();
            this.AddNPCBiomeRelationships_Automated();
            this.AddNPCBiomeRelationships_Manual();
            this.AddNPCBiomeRelationships_AddDecorations_Automated();
            this.ModifyEntriesThatNeedIt();
            this.RegisterFilters();
            this.RegisterSortSteps();
        }
References Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.AddEmptyEntries_CrittersAndEnemies_Automated(), Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.AddNPCBiomeRelationships_AddDecorations_Automated(), Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.AddNPCBiomeRelationships_Automated(), Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.AddNPCBiomeRelationships_Manual(), Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.AddTownNPCs_Manual(), Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.ModifyEntriesThatNeedIt(), Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.RegisterFilters(), and Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.RegisterSortSteps().
Referenced by Terraria.Main.Initialize_AlmostEverything().