Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.ScoreStairwell
ScoreStairwell()
double Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.ScoreStairwell (DualDungeonLayoutProvider::HallwayCalculator::HallLine line) inline private
Definition at line 821 of file DualDungeonLayoutProvider.cs.
            {
                Vector2D vector2D = line.targetPoint - line.sourcePoint;
                Vector2D vector2D2 = vector2D.SafeNormalize(Vector2D.UnitX);
                double num = 0.0;
                num -= Utils.Remap(Math.Abs(vector2D2.Y), 0.6, 1.0, 1.0, 0.0, true);
                num -= Utils.Remap(vector2D.Length(), this.avgLineLength * 0.5, this.avgLineLength * 1.5, 1.0, 0.0, true);
                if (line.target.backLinks.Any<DualDungeonLayoutProvider.HallwayCalculator.RoomEntry>() || line.target.forwardLinks.Any<DualDungeonLayoutProvider.HallwayCalculator.RoomEntry>())
                {
                    num -= 5.0;
                }
                if (DualDungeonLayoutProvider.HallwayCalculator.IsBiomeRoom(line.source) || DualDungeonLayoutProvider.HallwayCalculator.IsBiomeRoom(line.target))
                {
                    num -= 5.0;
                }
                return num;
            }
References System.Math.Abs(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.RoomEntry.forwardLinks, Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.IsBiomeRoom(), ReLogic.Utilities.Vector2D.Length(), Terraria.Utils.Remap(), ReLogic.Utilities.Vector2D.UnitX, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.Generate().