Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.ScoreHallway
ScoreHallway()
double Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.ScoreHallway (DualDungeonLayoutProvider::HallwayCalculator::HallLine line) inline private
Definition at line 797 of file DualDungeonLayoutProvider.cs.
            {
                double num = 0.0;
                double num2 = Math.Sin(0.6108652381980153);
                Vector2D vector2D = line.targetPoint - line.sourcePoint;
                Vector2D vector2D2 = vector2D.SafeNormalize(Vector2D.UnitX);
                num -= Utils.Remap(Math.Abs(vector2D2.Y), num2, 0.0, 0.0, 1.0, true);
                num -= Utils.Remap(Math.Abs(vector2D2.Y), num2, 1.0, 0.0, 5.0, true);
                num -= Utils.Remap(vector2D.Length(), this.avgLineLength * 1.5, this.avgLineLength * 3.0, 0.0, 3.0, true);
                num -= (double)Utils.Remap((float)line.target.forwardLinks.Count, 1f, 3f, 0f, 2f, true);
                num -= (double)Utils.Remap((float)line.source.backLinks.Count, 1f, 3f, 0f, 2f, true);
                num += (double)Utils.Remap((float)this.DistanceFromCommonAncestor(line.source, line.target), 3f, 6f, 0f, 1f, true);
                if ((DualDungeonLayoutProvider.HallwayCalculator.IsBiomeRoom(line.target) && line.target.forwardLinks.Any<DualDungeonLayoutProvider.HallwayCalculator.RoomEntry>()) || (DualDungeonLayoutProvider.HallwayCalculator.IsBiomeRoom(line.source) && line.source.backLinks.Any<DualDungeonLayoutProvider.HallwayCalculator.RoomEntry>()))
                {
                    num -= 5.0;
                }
                if (DualDungeonLayoutProvider.HallwayCalculator.IsBiomeRoom(line.target) || DualDungeonLayoutProvider.HallwayCalculator.IsBiomeRoom(line.source))
                {
                    num -= Utils.Remap(Math.Abs(vector2D2.Y), 0.6, 0.8, 0.0, 5.0, true);
                }
                return num;
            }
References System.Math.Abs(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.DistanceFromCommonAncestor(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.IsBiomeRoom(), ReLogic.Utilities.Vector2D.Length(), Terraria.Utils.Remap(), System.Math.Sin(), ReLogic.Utilities.Vector2D.UnitX, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.Generate().