Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.Generate
Generate()
List< DungeonHall > Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.Generate () inline
Definition at line 724 of file DualDungeonLayoutProvider.cs.
            {
                int num = 25;
                int num2 = 8;
                foreach (DualDungeonLayoutProvider.HallwayCalculator.RoomEntry roomEntry in this.rooms.Skip(2))
                {
                    if (WorldGen.genRand.Next(2) == 0)
                    {
                        double num3;
                        DualDungeonLayoutProvider.HallwayCalculator.HallLine hallLine = this.SelectGoodRoomForHallway(roomEntry, out num3, new Func<DualDungeonLayoutProvider.HallwayCalculator.HallLine, double>(this.ScoreStairwell), num);
                        if (hallLine != null && num3 > 0.0)
{
                            this.MakeHall(hallLine, DungeonHallType.Stairwell);
                        }
                    }
                }
                foreach (DualDungeonLayoutProvider.HallwayCalculator.RoomEntry roomEntry2 in this.rooms.Skip(1))
                {
                    if (!roomEntry2.backLinks.Any<DualDungeonLayoutProvider.HallwayCalculator.RoomEntry>())
                    {
                        int num4 = 0;
                        DualDungeonLayoutProvider.HallwayCalculator.HallLine hallLine2;
                        for (;;)
{
                            double num5;
                            hallLine2 = this.SelectGoodRoomForHallway(roomEntry2, out num5, new Func<DualDungeonLayoutProvider.HallwayCalculator.HallLine, double>(this.ScoreHallway), num2);
                            if (hallLine2 != null)
{
                                break;
                            }
                            if (num4 == 1000)
{
                                goto IL_00E5;
                            }
                            num4++;
                        }
                        this.MakeHall(hallLine2, DualDungeonLayoutProvider.DualDungeonLayout_GetGeneralHallType(WorldGen.genRand));
                    }
                    IL_00E5:
                    if (WorldGen.genRand.Next(2) == 0)
                    {
                        double num6;
                        DualDungeonLayoutProvider.HallwayCalculator.HallLine hallLine3 = this.SelectGoodRoomForHallway(roomEntry2, out num6, new Func<DualDungeonLayoutProvider.HallwayCalculator.HallLine, double>(this.ScoreHallway), num2);
                        if (hallLine3 != null && num6 > -2.0)
{
                            this.MakeHall(hallLine3, DualDungeonLayoutProvider.DualDungeonLayout_GetGeneralHallType(WorldGen.genRand));
                        }
                    }
                }
                return this.halls;
            }
References Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.DualDungeonLayout_GetGeneralHallType(), Terraria.WorldGen.genRand, Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.halls, Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.MakeHall(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.ScoreHallway(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.ScoreStairwell(), and Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.SelectGoodRoomForHallway().
Referenced by Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.ProvideLayout().