Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.SelectGoodRoomForHallway
SelectGoodRoomForHallway()
DualDungeonLayoutProvider.HallwayCalculator.HallLine Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.SelectGoodRoomForHallway (DualDungeonLayoutProvider::HallwayCalculator::RoomEntry source, out double bestScore, Func< DualDungeonLayoutProvider::HallwayCalculator::HallLine, double > scoreFunc, int hallRadius) inline private
Definition at line 840 of file DualDungeonLayoutProvider.cs.
            {
                UnifiedRandom genRand = WorldGen.genRand;
                int num = this.rooms.FindIndex((DualDungeonLayoutProvider.HallwayCalculator.RoomEntry r) => r.progressAlongSnake >= source.progressAlongSnake - this.maxProgressDelta);
                num = Math.Min(num, Math.Max(0, this.rooms.IndexOf(source) - 2));
                IEnumerable<DualDungeonLayoutProvider.HallwayCalculator.RoomEntry> enumerable = this.rooms.Skip(num).TakeWhile((DualDungeonLayoutProvider.HallwayCalculator.RoomEntry r) => r != source);
                double nearbyRoomSearchRadius = enumerable.Select((DualDungeonLayoutProvider.HallwayCalculator.RoomEntry r) => Vector2D.Distance(r.Center, source.Center)).Max() + this.extraNearbyRoomSearchRadius;
                List<DualDungeonLayoutProvider.HallwayCalculator.RoomEntry> list = this.rooms.Where((DualDungeonLayoutProvider.HallwayCalculator.RoomEntry r) => r != source && Vector2D.Distance(r.Center, source.Center) <= nearbyRoomSearchRadius).ToList<DualDungeonLayoutProvider.HallwayCalculator.RoomEntry>();
                DualDungeonLayoutProvider.HallwayCalculator.HallLine hallLine = null;
                bestScore = double.MinValue;
                foreach (DualDungeonLayoutProvider.HallwayCalculator.RoomEntry roomEntry in enumerable)
                {
                    if (this.CanConnect(source, roomEntry))
                    {
                        double num2 = genRand.NextDouble();
                        DualDungeonLayoutProvider.HallwayCalculator.HallLine hallLine2 = new DualDungeonLayoutProvider.HallwayCalculator.HallLine
{
                            source = source,
                            target = roomEntry
                        };
                        ConnectionPointQuality hallwayConnectionPoints = DualDungeonLayoutProvider.GetHallwayConnectionPoints(source.room, roomEntry.room, out hallLine2.sourcePoint, out hallLine2.targetPoint);
                        num2 -= (double)((hallwayConnectionPoints == ConnectionPointQuality.Bad) ? 10 : ((hallwayConnectionPoints == ConnectionPointQuality.Okay) ? 2 : 0));
                        num2 += scoreFunc(hallLine2);
                        if (num2 > bestScore)
{
                            foreach (DualDungeonLayoutProvider.HallwayCalculator.RoomEntry roomEntry2 in list)
{
                                if (roomEntry2 != roomEntry)
{
                                    Vector2D vector2D = roomEntry2.Center.ClosestPointOnLine(hallLine2.sourcePoint, hallLine2.targetPoint);
                                    double num3 = vector2D.Distance(roomEntry2.Center) - (double)roomEntry2.room.settings.GetBoundingRadius() - (double)hallRadius;
                                    if (num3 < 0.0)
{
                                        num2 += num3 / 4.0 - 3.0;
                                    }
                                    if (roomEntry2.room.OuterBounds.Contains(vector2D))
{
                                        num2 -= 1000.0;
                                    }
                                }
                            }
                            foreach (DualDungeonLayoutProvider.HallwayCalculator.HallLine hallLine3 in this.stairwells)
{
                                if (Utils.LineSegmentsIntersect(hallLine2.sourcePoint, hallLine2.targetPoint, hallLine3.sourcePoint, hallLine3.targetPoint))
{
                                    num2 -= 3.0;
                                }
                            }
                            if (num2 > bestScore && this.controlLines.IsLineInsideBorder(hallLine2.sourcePoint, hallLine2.targetPoint, hallRadius))
{
                                hallLine = hallLine2;
                                bestScore = num2;
                            }
                        }
                    }
                }
                return hallLine;
            }
References Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.CanConnect(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.controlLines, ReLogic.Utilities.Vector2D.Distance(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.extraNearbyRoomSearchRadius, Terraria.WorldGen.genRand, Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.GetHallwayConnectionPoints(), Terraria.GameContent.Biomes.DitherSnake.IsLineInsideBorder(), Terraria.Utils.LineSegmentsIntersect(), System.list, System.Math.Max(), System.Math.Min(), Terraria.Utilities.UnifiedRandom.NextDouble(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.rooms, System.source, Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.HallLine.sourcePoint, and Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.HallLine.targetPoint.
Referenced by Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.Generate().