Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.MakeHall
MakeHall()
void Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.MakeHall (DualDungeonLayoutProvider::HallwayCalculator::HallLine line, DungeonHallType hallType) inline private
Definition at line 777 of file DualDungeonLayoutProvider.cs.
            {
                DungeonGenerationStyleData style = this.data.genVars.dungeonDitherSnake.GetLineContaining(line.sourcePoint, null, 0).Style;
                DungeonHallSettings dungeonHallSettings = DungeonCrawler.MakeDungeon_GetHallSettings(hallType, this.data, line.sourcePoint.ToVector2(), line.targetPoint.ToVector2(), style);
                if (DualDungeonLayoutProvider.HallwayCalculator.IsBiomeRoom(line.target))
                {
                    dungeonHallSettings.CarveOnly = true;
                }
                DungeonHall dungeonHall = DungeonCrawler.MakeDungeon_GetHall(dungeonHallSettings, true);
                dungeonHall.CalculateHall(this.data, line.sourcePoint, line.targetPoint);
                this.halls.Add(dungeonHall);
                line.source.backLinks.Add(line.target);
                line.target.forwardLinks.Add(line.source);
                if (hallType == DungeonHallType.Stairwell)
                {
                    this.stairwells.Add(line);
                }
            }
References System.Collections.Generic.List< T >.Add(), Terraria.GameContent.Generation.Dungeon.Halls.DungeonHall.CalculateHall(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.data, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.dungeonDitherSnake, Terraria.GameContent.Generation.Dungeon.DungeonData.genVars, Terraria.GameContent.Biomes.DitherSnake.GetLineContaining(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.halls, Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.IsBiomeRoom(), Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GetHall(), Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GetHallSettings(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.stairwells, and Terraria.GameContent.Biomes.DungeonControlLine.Style.
Referenced by Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.Generate().