Terraria Decompiled: Microsoft.Xna.Framework.Audio.AudioEngine.OnXACTNotification
OnXACTNotification()
static unsafe void Microsoft.Xna.Framework.Audio.AudioEngine.OnXACTNotification (IntPtr notification) inline static private
Definition at line 248 of file AudioEngine.cs.
        {
            FAudio.FACTNotification* ptr = (FAudio.FACTNotification*)(void*)notification;
            if (ptr->type == 7)
            {
                IntPtr pWaveBank = ptr->anon.waveBank.pWaveBank;
                Dictionary<IntPtr, WeakReference> dictionary = AudioEngine.xactPtrs;
                lock (dictionary)
                {
                    WeakReference weakReference;
                    if (AudioEngine.xactPtrs.TryGetValue(pWaveBank, out weakReference) && weakReference.IsAlive)
                    {
                        (weakReference.Target as WaveBank).OnWaveBankDestroyed();
                    }
                    AudioEngine.xactPtrs.Remove(pWaveBank);
                    return;
                }
            }
            if (ptr->type == 6)
            {
                IntPtr pSoundBank = ptr->anon.soundBank.pSoundBank;
                Dictionary<IntPtr, WeakReference> dictionary = AudioEngine.xactPtrs;
                lock (dictionary)
                {
                    WeakReference weakReference;
                    if (AudioEngine.xactPtrs.TryGetValue(pSoundBank, out weakReference) && weakReference.IsAlive)
                    {
                        (weakReference.Target as SoundBank).OnSoundBankDestroyed();
                    }
                    AudioEngine.xactPtrs.Remove(pSoundBank);
                    return;
                }
            }
            if (ptr->type == 4)
            {
                IntPtr pCue = ptr->anon.cue.pCue;
                Dictionary<IntPtr, WeakReference> dictionary = AudioEngine.xactPtrs;
                lock (dictionary)
                {
                    WeakReference weakReference;
                    if (AudioEngine.xactPtrs.TryGetValue(pCue, out weakReference) && weakReference.IsAlive)
                    {
                        (weakReference.Target as Cue).OnCueDestroyed();
                    }
                    AudioEngine.xactPtrs.Remove(pCue);
                }
            }
        }
References System.dictionary, System.WeakReference< T >.IsAlive, System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and Microsoft.Xna.Framework.Audio.AudioEngine.xactPtrs.
Referenced by Microsoft.Xna.Framework.Audio.AudioEngine.AudioEngine().