Terraria Decompiled: Terraria.Graphics.Renderers.ParticlePool.RequestParticle
RequestParticle()
T Terraria.Graphics.Renderers.ParticlePool< T >.RequestParticle () inline
Definition at line 33 of file ParticlePool.cs.
        {
            if (Main.NoPooling)
            {
                this._particles.RemoveAll((T p) => p.IsRestingInPool);
            }
            int count = this._particles.Count;
            for (int i = 0; i < count; i++)
            {
                T t = this._particles[i];
                if (t.IsRestingInPool)
                {
                    t = this._particles[i];
                    t.FetchFromPool();
                    return this._particles[i];
                }
            }
            T t2 = this._instantiator();
            this._particles.Add(t2);
            t2.FetchFromPool();
            return t2;
        }
References Terraria.Graphics.Renderers.ParticlePool< T >._instantiator, Terraria.Graphics.Renderers.ParticlePool< T >._particles, System.count, and Terraria.Main.NoPooling.
Referenced by Terraria.GameContent.CraftingEffects.CreateBubbleParticles(), Terraria.DataStructures.RichRoomCheckFeedback.EndScoring(), Terraria.DataStructures.RichRoomCheckFeedback.EndSpread(), Terraria.Chest.IndicateBlockedChest(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_BlackLightningHit(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_BlackLightningSmall(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_BlueLightningSmall(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_CattivaHit(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsBarrelExplosion(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsDownDashExplosion(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsFlint(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsHeadEffect(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsMushroomBoiExplosion(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsMushroomBoiTargetFound(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_Excalibur(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_FakeFish(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_FlameWaders(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_GasTrap(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ItemTransfer(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_Keybrand(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_LakeSparkle(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_LeafCrystalPassive(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_LeafCrystalShot(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_MoonLordWhip(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_MoonLordWhipEye(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_NatureFly(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_NightsEdge(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_PaladinsHammer(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_PaladinsShieldHit(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_PooFly(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_PrincessWeapon(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_RainbowBoulder1(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_RainbowBoulder2(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_RainbowBoulder3(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_RainbowBoulder4(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_RainbowRodHit(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ShadowOrbExplosion(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ShimmerArrow(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ShimmerBlock(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ShimmerTownNPC(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ShimmerTownNPCSend(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_SilverBulletSparkle(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_StardustPunch(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_StellarTune(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_StormLightning(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_StormLightningWindup(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_TerraBlade(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_TrueExcalibur(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_TrueNightsEdge(), and Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_WallOfFleshGoatMountFlames().