Terraria Decompiled: Microsoft.Xna.Framework.Audio.AudioEngine.AudioEngine
AudioEngine() [2/3]
unsafe Microsoft.Xna.Framework.Audio.AudioEngine.AudioEngine (string settingsFile, TimeSpan lookAheadTime, string rendererId) inline
Definition at line 82 of file AudioEngine.cs.
        {
            if (string.IsNullOrEmpty(settingsFile))
            {
                throw new ArgumentNullException("settingsFile");
            }
            FAudio.FACTCreateEngine(0U, out this.handle);
            ushort num;
            FAudio.FACTAudioEngine_GetRendererCount(this.handle, out num);
            if (num == 0)
            {
                FAudio.FACTAudioEngine_Release(this.handle);
                throw new NoAudioHardwareException();
            }
            this.rendererDetails = new RendererDetail[(int)num];
            byte[] array = new byte[510];
            for (ushort num2 = 0; num2 < num; num2 += 1)
            {
                FAudio.FACTRendererDetails factrendererDetails;
                FAudio.FACTAudioEngine_GetRendererDetails(this.handle, num2, out factrendererDetails);
                Marshal.Copy((IntPtr)((void*)(&factrendererDetails.displayName.FixedElementField)), array, 0, array.Length);
                string text = Encoding.Unicode.GetString(array).TrimEnd(new char[1]);
                Marshal.Copy((IntPtr)((void*)(&factrendererDetails.rendererID.FixedElementField)), array, 0, array.Length);
                string text2 = Encoding.Unicode.GetString(array).TrimEnd(new char[1]);
                this.rendererDetails[(int)num2] = new RendererDetail(text, text2);
            }
            IntPtr intPtr2;
            IntPtr intPtr = TitleContainer.ReadToPointer(settingsFile, out intPtr2);
            FAudio.FACTRuntimeParameters factruntimeParameters = default(FAudio.FACTRuntimeParameters);
            factruntimeParameters.pGlobalSettingsBuffer = intPtr;
            factruntimeParameters.globalSettingsBufferSize = (uint)(int)intPtr2;
            factruntimeParameters.globalSettingsFlags = 1U;
            this.xactNotificationFunc = new FAudio.FACTNotificationCallback(AudioEngine.OnXACTNotification);
            factruntimeParameters.fnNotificationCallback = Marshal.GetFunctionPointerForDelegate(this.xactNotificationFunc);
            factruntimeParameters.lookAheadTime = (uint)lookAheadTime.Milliseconds;
            if (!string.IsNullOrEmpty(rendererId))
            {
                factruntimeParameters.pRendererID = Marshal.StringToHGlobalAuto(rendererId);
            }
            if (FAudio.FACTAudioEngine_Initialize(this.handle, ref factruntimeParameters) != 0U)
            {
                throw new InvalidOperationException("Engine initialization failed!");
            }
            if (factruntimeParameters.pRendererID != IntPtr.Zero)
            {
                Marshal.FreeHGlobal(factruntimeParameters.pRendererID);
            }
            this.handle3D = new byte[20];
            FAudio.FACT3DInitialize(this.handle, this.handle3D);
            FAudio.FAudioWaveFormatExtensible faudioWaveFormatExtensible;
            FAudio.FACTAudioEngine_GetFinalMixFormat(this.handle, out faudioWaveFormatExtensible);
            this.channels = faudioWaveFormatExtensible.Format.nChannels;
            this.notificationDesc = default(FAudio.FACTNotificationDescription);
            this.notificationDesc.flags = 1;
            this.notificationDesc.type = 7;
            FAudio.FACTAudioEngine_RegisterNotification(this.handle, ref this.notificationDesc);
            this.notificationDesc.type = 6;
            FAudio.FACTAudioEngine_RegisterNotification(this.handle, ref this.notificationDesc);
            this.notificationDesc.type = 4;
            FAudio.FACTAudioEngine_RegisterNotification(this.handle, ref this.notificationDesc);
        }
References System.array, System.Runtime.InteropServices.Marshal.Copy(), FAudio.FACTRendererDetails.displayName, FAudio.FACT3DInitialize(), FAudio.FACTAudioEngine_GetFinalMixFormat(), FAudio.FACTAudioEngine_GetRendererCount(), FAudio.FACTAudioEngine_GetRendererDetails(), FAudio.FACTAudioEngine_Initialize(), FAudio.FACTAudioEngine_RegisterNotification(), FAudio.FACTAudioEngine_Release(), FAudio.FACTCreateEngine(), FAudio.FACTNotificationCallback(), FAudio.FAudioWaveFormatExtensible.Format, System.Runtime.InteropServices.Marshal.FreeHGlobal(), System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate(), System.Text.Encoding.GetString(), Microsoft.Xna.Framework.Audio.AudioEngine.handle, Microsoft.Xna.Framework.Audio.AudioEngine.handle3D, int, System.TimeSpan.Milliseconds, Microsoft.Xna.Framework.Audio.AudioEngine.notificationDesc, Microsoft.Xna.Framework.Audio.AudioEngine.OnXACTNotification(), FAudio.FACTRuntimeParameters.pRendererID, Microsoft.Xna.Framework.TitleContainer.ReadToPointer(), Microsoft.Xna.Framework.Audio.AudioEngine.rendererDetails, FAudio.FACTRendererDetails.rendererID, System.Runtime.InteropServices.Marshal.StringToHGlobalAuto(), System.text, System.U, System.Text.Encoding.Unicode, Microsoft.Xna.Framework.Audio.AudioEngine.xactNotificationFunc, and System.IntPtr.Zero.