Terraria Decompiled: Terraria.Collision.noSlopeCollision
noSlopeCollision()
static Vector2 Terraria.Collision.noSlopeCollision (Vector2 Position, Vector2 Velocity, int Width, int Height, bool fallThrough = false, bool fall2 = false) inline static
Definition at line 2114 of file Collision.cs.
        {
            Collision.up = false;
            Collision.down = false;
            Vector2 vector = Velocity;
            Vector2 vector2 = Position + Velocity;
            int num = (int)(Position.X / 16f) - 1;
            int num2 = (int)((Position.X + (float)Width) / 16f) + 2;
            int num3 = (int)(Position.Y / 16f) - 1;
            int num4 = (int)((Position.Y + (float)Height) / 16f) + 2;
            int num5 = -1;
            int num6 = -1;
            int num7 = -1;
            int num8 = -1;
            int num9 = Utils.Clamp<int>(num, 0, Main.maxTilesX - 1);
            num2 = Utils.Clamp<int>(num2, 0, Main.maxTilesX - 1);
            num3 = Utils.Clamp<int>(num3, 0, Main.maxTilesY - 40);
            num4 = Utils.Clamp<int>(num4, 0, Main.maxTilesY - 40);
            float num10 = (float)((num4 + 3) * 16);
            for (int i = num9; i < num2; i++)
            {
                for (int j = num3; j < num4; j++)
                {
                    if (Main.tile[i, j] != null && Main.tile[i, j].active() && (Main.tileSolid[(int)Main.tile[i, j].type] || (Main.tileSolidTop[(int)Main.tile[i, j].type] && Main.tile[i, j].frameY == 0)))
                    {
                        Vector2 vector3;
                        vector3.X = (float)(i * 16);
                        vector3.Y = (float)(j * 16);
                        int num11 = 16;
                        if (Main.tile[i, j].halfBrick())
{
                            vector3.Y += 8f;
                            num11 -= 8;
                        }
                        if (vector2.X + (float)Width > vector3.X && vector2.X < vector3.X + 16f && vector2.Y + (float)Height > vector3.Y && vector2.Y < vector3.Y + (float)num11)
{
                            if (Position.Y + (float)Height <= vector3.Y)
{
                                Collision.down = true;
                                if ((!Main.tileSolidTop[(int)Main.tile[i, j].type] || !fallThrough || (Velocity.Y > 1f && !fall2)) && num10 > vector3.Y)
{
                                    num7 = i;
                                    num8 = j;
                                    if (num11 < 16)
{
                                        num8++;
                                    }
                                    if (num7 != num5)
{
                                        vector.Y = vector3.Y - (Position.Y + (float)Height);
                                        num10 = vector3.Y;
                                    }
                                }
                            }
                            else if (Position.X + (float)Width <= vector3.X && !Main.tileSolidTop[(int)Main.tile[i, j].type])
{
                                num5 = i;
                                num6 = j;
                                if (num6 != num8)
{
                                    vector.X = vector3.X - (Position.X + (float)Width);
                                }
                                if (num7 == num5)
{
                                    vector.Y = Velocity.Y;
                                }
                            }
                            else if (Position.X >= vector3.X + 16f && !Main.tileSolidTop[(int)Main.tile[i, j].type])
{
                                num5 = i;
                                num6 = j;
                                if (num6 != num8)
{
                                    vector.X = vector3.X + 16f - Position.X;
                                }
                                if (num7 == num5)
{
                                    vector.Y = Velocity.Y;
                                }
                            }
                            else if (Position.Y >= vector3.Y + (float)num11 && !Main.tileSolidTop[(int)Main.tile[i, j].type])
{
                                Collision.up = true;
                                num7 = i;
                                num8 = j;
                                vector.Y = vector3.Y + (float)num11 - Position.Y + 0.01f;
                                if (num8 == num6)
{
                                    vector.X = Velocity.X;
                                }
                            }
                        }
                    }
                }
            }
            return vector;
        }
References Terraria.Tile.active(), Terraria.Utils.Clamp(), Terraria.Tile.frameY, Terraria.Tile.halfBrick(), int, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Tile.type, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.NPC.Collision_MoveBlazingWheel().