Terraria Decompiled: Terraria.Collision.BuildTileContacts
BuildTileContacts()
static void Terraria.Collision.BuildTileContacts (Vector2 Position, int Width, int Height, List< Collision::TileContact > contactTiles) inline static
Definition at line 2213 of file Collision.cs.
        {
            Position.X = (float)((int)Position.X);
            Position.Y = (float)((int)Position.Y);
            contactTiles.Clear();
            int num = (int)((Position.X - 1f) / 16f) - 1;
            int num2 = (int)((Position.X + 1f + (float)Width) / 16f) + 1;
            int num3 = (int)((Position.Y - 1f) / 16f) - 1;
            int num4 = (int)((Position.Y + 3f + (float)Height) / 16f) + 1;
            int num5 = Utils.Clamp<int>(num, 0, Main.maxTilesX - 1);
            num2 = Utils.Clamp<int>(num2, 0, Main.maxTilesX - 1);
            num3 = Utils.Clamp<int>(num3, 0, Main.maxTilesY - 40);
            num4 = Utils.Clamp<int>(num4, 0, Main.maxTilesY - 40);
            for (int i = num5; i < num2; i++)
            {
                for (int j = num3; j < num4; j++)
                {
                    Tile tile = Main.tile[i, j];
                    if (tile != null && tile.active() && !tile.inActive())
                    {
                        ushort type = tile.type;
                        bool flag = Main.tileSolid[(int)type];
                        if (Main.tileSolidTop[(int)type] && tile.frameY == 0)
{
                            flag = true;
                        }
                        if (flag)
{
                            Vector2 vector;
                            vector.X = (float)(i * 16);
                            vector.Y = (float)(j * 16);
                            int num6 = 16;
                            if (tile.halfBrick())
{
                                vector.Y += 8f;
                                num6 -= 8;
                            }
                            byte b = tile.slope();
                            if (Math.Abs(Position.X - (vector.X + 16f)) < 0.1f && Position.Y + (float)Height > vector.Y && Position.Y < vector.Y + (float)num6 && b != 3 && b != 1)
{
                                float num7 = Math.Max(Math.Min(Position.Y + (float)Height, vector.Y + (float)num6) - Math.Max(Position.Y, vector.Y) + 0.5f, 1f);
                                contactTiles.Add(new Collision.TileContact(Collision.TileContactSide.Left, i, j, (int)type, (int)b, (int)num7));
                            }
                            if (Math.Abs(Position.X + (float)Width - vector.X) < 0.1f && Position.Y + (float)Height > vector.Y && Position.Y < vector.Y + (float)num6 && b != 4 && b != 2)
{
                                float num8 = Math.Max(Math.Min(Position.Y + (float)Height, vector.Y + (float)num6) - Math.Max(Position.Y, vector.Y) + 0.5f, 1f);
                                contactTiles.Add(new Collision.TileContact(Collision.TileContactSide.Right, i, j, (int)type, (int)b, (int)num8));
                            }
                            if (Position.Y + 3f + (float)Height > vector.Y && Position.Y - 1f < vector.Y + (float)num6)
{
                                if (Position.X + (float)Width > vector.X && Position.X < vector.X + 16f)
{
                                    float num9 = Math.Max(Math.Min(Position.X + (float)Width, vector.X + 16f) - Math.Max(Position.X, vector.X) + 0.5f, 1f);
                                    switch (b)
{
                                    case 0:
                                        if (Math.Abs(Position.Y - (vector.Y + (float)num6)) < 0.1f)
{
                                            contactTiles.Add(new Collision.TileContact(Collision.TileContactSide.Top, i, j, (int)type, (int)b, (int)num9));
                                        }
                                        if (Math.Abs(Position.Y + (float)Height - vector.Y) < 0.1f)
{
                                            contactTiles.Add(new Collision.TileContact(Collision.TileContactSide.Bottom, i, j, (int)type, (int)b, (int)num9));
                                        }
                                        break;
                                    case 1:
{
                                        if (Math.Abs(Position.Y - (vector.Y + (float)num6)) < 0.1f)
{
                                            contactTiles.Add(new Collision.TileContact(Collision.TileContactSide.Top, i, j, (int)type, (int)b, (int)num9));
                                        }
                                        float num10 = Math.Max(Position.X - vector.X, 0f);
                                        float num11 = Position.Y + (float)Height;
                                        if (num11 - vector.Y > -0.1f && num11 - (vector.Y + num10) < 0.1f)
{
                                            contactTiles.Add(new Collision.TileContact(Collision.TileContactSide.Bottom, i, j, (int)type, (int)b, (int)num9));
                                        }
                                        break;
                                    }
                                    case 2:
{
                                        if (Math.Abs(Position.Y - (vector.Y + (float)num6)) < 0.1f)
{
                                            contactTiles.Add(new Collision.TileContact(Collision.TileContactSide.Top, i, j, (int)type, (int)b, (int)num9));
                                        }
                                        float num12 = Math.Max(vector.X + 16f - (Position.X + (float)Width), 0f);
                                        float num13 = Position.Y + (float)Height;
                                        if (num13 - vector.Y > -0.1f && num13 - (vector.Y + num12) < 0.1f)
{
                                            contactTiles.Add(new Collision.TileContact(Collision.TileContactSide.Bottom, i, j, (int)type, (int)b, (int)num9));
                                        }
                                        break;
                                    }
                                    case 3:
{
                                        float num14 = Math.Max(Position.X - vector.X, 0f);
                                        if (Math.Abs(Position.Y - (vector.Y + (float)num6 - num14)) < 0.1f)
{
                                            contactTiles.Add(new Collision.TileContact(Collision.TileContactSide.Top, i, j, (int)type, (int)b, (int)num9));
                                        }
                                        if (Math.Abs(Position.Y + (float)Height - vector.Y) < 0.1f)
{
                                            contactTiles.Add(new Collision.TileContact(Collision.TileContactSide.Bottom, i, j, (int)type, (int)b, (int)num9));
                                        }
                                        break;
                                    }
                                    case 4:
{
                                        float num15 = Math.Max(vector.X + 16f - (Position.X + (float)Width), 0f);
                                        if (Math.Abs(Position.Y - (vector.Y + (float)num6 - num15)) < 0.1f)
{
                                            contactTiles.Add(new Collision.TileContact(Collision.TileContactSide.Top, i, j, (int)type, (int)b, (int)num9));
                                        }
                                        if (Math.Abs(Position.Y + (float)Height - vector.Y) < 0.1f)
{
                                            contactTiles.Add(new Collision.TileContact(Collision.TileContactSide.Bottom, i, j, (int)type, (int)b, (int)num9));
                                        }
                                        break;
                                    }
                                    }
                                }
                                else if (Position.X + 3f + (float)Width > vector.X && Position.X - 3f < vector.X + 16f && Position.Y < vector.Y)
{
                                    Collision.TileContactSide tileContactSide = ((vector.X < Position.X) ? Collision.TileContactSide.BottomLeft : Collision.TileContactSide.BottomRight);
                                    switch (b)
{
                                    case 0:
                                    case 3:
                                    case 4:
                                        contactTiles.Add(new Collision.TileContact(tileContactSide, i, j, (int)type, (int)b, 0));
                                        break;
                                    case 1:
                                        if (tileContactSide == Collision.TileContactSide.BottomRight)
{
                                            contactTiles.Add(new Collision.TileContact(tileContactSide, i, j, (int)type, (int)b, 0));
                                        }
                                        break;
                                    case 2:
                                        if (tileContactSide == Collision.TileContactSide.BottomLeft)
{
                                            contactTiles.Add(new Collision.TileContact(tileContactSide, i, j, (int)type, (int)b, 0));
                                        }
                                        break;
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
References System.Math.Abs(), Terraria.Tile.active(), System.Collections.Generic.List< T >.Add(), Terraria.Utils.Clamp(), System.Collections.Generic.List< T >.Clear(), Terraria.Tile.halfBrick(), Terraria.Tile.inActive(), int, System.Math.Max(), System.Math.Min(), Terraria.Tile.slope(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Tile.type, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Collision.ApplyConveyorBeltMovementToVelocity().