Terraria Decompiled: Terraria.Collision.SolidTiles
SolidTiles() [3/4]
static bool Terraria.Collision.SolidTiles (Vector2 position, int width, int height) inline static
Definition at line 3518 of file Collision.cs.
        {
            return Collision.SolidTiles((int)(position.X / 16f), (int)((position.X + (float)width) / 16f), (int)(position.Y / 16f), (int)((position.Y + (float)height) / 16f));
        }
References Terraria.Collision.SolidTiles(), Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_007_TownEntities(), Terraria.NPC.AI_007_TownEntities_TeleportToHome(), Terraria.NPC.AI_045_Golem(), Terraria.NPC.AI_084_LunaticCultist(), Terraria.Projectile.AI_191_TrueNightsEdge(), Terraria.NPC.AI_AttemptToFindTeleportSpot(), Terraria.NPC.BloodNautilus_CallForHelp(), Terraria.GameContent.Events.CultistRitual.CheckFloor(), Terraria.GameContent.Events.CultistRitual.CheckFloor2(), Terraria.Projectile.Damage_PVE_Inner(), Terraria.NPC.HitEffect(), Terraria.Wiring.HitWireSingle(), Terraria.Player.ItemCheck_CheckCanUse_Inner(), Terraria.WorldGen.ScoreRoom(), Terraria.WorldGen.ShakeTree(), Terraria.NPC.Spawner.SlimeRainSpawns(), Terraria.Collision.SolidTiles(), Terraria.Collision.SolidTiles(), Terraria.Collision.SolidTilesVersatile(), Terraria.NPC.Spawner.SpawnAnNPC(), Terraria.Projectile.SpawnFakeFishInWater(), Terraria.WorldGen.SpawnHomelessNPC(), Terraria.WorldGen.SpawnTownNPC(), Terraria.WorldGen.SpawnTravelNPC(), and Terraria.WorldGen.TriggerLunarApocalypse().