Terraria Decompiled: Terraria.Collision.StepConveyorBelt
StepConveyorBelt()
static void Terraria.Collision.StepConveyorBelt (Entity entity, float gravDir, bool artificialRising = false) inline static
Definition at line 4284 of file Collision.cs.
        {
            Player player = null;
            if (entity is Player)
            {
                player = (Player)entity;
                if (Math.Abs(player.gfxOffY) > 2f || player.grapCount > 0 || player.pulley)
                {
                    return;
                }
                entity.height -= 5;
                entity.position.Y = entity.position.Y + 5f;
            }
            int num = 0;
            int num2 = 0;
            bool flag = false;
            int num3 = (int)entity.position.Y + entity.height;
            entity.Hitbox.Inflate(2, 2);
            Vector2 topLeft = entity.TopLeft;
            Vector2 topRight = entity.TopRight;
            Vector2 bottomLeft = entity.BottomLeft;
            Vector2 bottomRight = entity.BottomRight;
            List<Point> cacheForConveyorBelts = Collision._cacheForConveyorBelts;
            cacheForConveyorBelts.Clear();
            Collision.GetEntityEdgeTiles(cacheForConveyorBelts, entity, false, false, true, true);
            Vector2 vector = new Vector2(0.0001f);
            for (int i = 0; i < cacheForConveyorBelts.Count; i++)
            {
                Point point = cacheForConveyorBelts[i];
                if (WorldGen.InWorld(point.X, point.Y, 0) && (player == null || !player.onTrack || point.Y >= num3))
                {
                    Tile tile = Main.tile[point.X, point.Y];
                    if (tile != null && tile.active() && tile.nactive())
                    {
                        int num4 = TileID.Sets.ConveyorDirection[(int)tile.type];
                        if (num4 != 0)
{
                            Vector2 vector2;
                            Vector2 vector3;
                            vector2.X = (vector3.X = (float)(point.X * 16));
                            Vector2 vector4;
                            Vector2 vector5;
                            vector4.X = (vector5.X = (float)(point.X * 16 + 16));
                            switch (tile.slope())
{
                            case 1:
                                vector3.Y = (float)(point.Y * 16);
                                vector5.Y = (vector4.Y = (vector2.Y = (float)(point.Y * 16 + 16)));
                                break;
                            case 2:
                                vector5.Y = (float)(point.Y * 16);
                                vector3.Y = (vector4.Y = (vector2.Y = (float)(point.Y * 16 + 16)));
                                break;
                            case 3:
                                vector4.Y = (vector3.Y = (vector5.Y = (float)(point.Y * 16)));
                                vector2.Y = (float)(point.Y * 16 + 16);
                                break;
                            case 4:
                                vector2.Y = (vector3.Y = (vector5.Y = (float)(point.Y * 16)));
                                vector4.Y = (float)(point.Y * 16 + 16);
                                break;
                            default:
                                if (tile.halfBrick())
{
                                    vector3.Y = (vector5.Y = (float)(point.Y * 16 + 8));
                                }
                                else
{
                                    vector3.Y = (vector5.Y = (float)(point.Y * 16));
                                }
                                vector2.Y = (vector4.Y = (float)(point.Y * 16 + 16));
                                break;
                            }
                            int num5 = 0;
                            if (!TileID.Sets.Platforms[(int)tile.type] && Collision.CheckAABBvLineCollision2(entity.position - vector, entity.Size + vector * 2f, vector2, vector4))
{
                                num5--;
                            }
                            if (Collision.CheckAABBvLineCollision2(entity.position - vector, entity.Size + vector * 2f, vector3, vector5))
{
                                num5++;
                            }
                            if (num5 != 0)
{
                                flag = true;
                                num += num4 * num5 * (int)gravDir;
                                if (tile.leftSlope())
{
                                    num2 += (int)gravDir * -num4;
                                }
                                if (tile.rightSlope())
{
                                    num2 -= (int)gravDir * -num4;
                                }
                            }
                        }
                    }
                }
            }
            if (entity is Player)
            {
                entity.height += 5;
                entity.position.Y = entity.position.Y - 5f;
            }
            if (!flag)
            {
                return;
            }
            if (artificialRising)
            {
                num2 = -1;
            }
            if (num != 0 || artificialRising)
            {
                num = Math.Sign(num);
                num2 = Math.Sign(num2);
                Vector2 vector6 = Vector2.Normalize(new Vector2((float)num * gravDir, (float)num2)) * 2.5f;
                Vector2 vector7 = Collision.TileCollision(entity.position, vector6, entity.width, entity.height, false, false, (int)gravDir, false, false, true);
                entity.position += vector7;
                if (!artificialRising)
                {
                    vector6 = new Vector2(0f, 2.5f * gravDir);
                    vector7 = Collision.TileCollision(entity.position, vector6, entity.width, entity.height, false, false, (int)gravDir, false, false, true);
                    entity.position += vector7;
                }
                if (artificialRising)
                {
                    vector6 = new Vector2((float)num, (float)num2);
                    vector7 = Collision.TileCollision(entity.position - vector6, vector6, entity.width, entity.height, false, false, (int)gravDir, false, false, true);
                    entity.position += vector7;
                }
            }
        }
References Terraria.Collision._cacheForConveyorBelts, System.Math.Abs(), Terraria.Tile.active(), Terraria.Entity.BottomLeft, Terraria.Entity.BottomRight, Terraria.Collision.CheckAABBvLineCollision2(), System.Collections.Generic.List< T >.Clear(), Terraria.ID.TileID.Sets.ConveyorDirection, System.Collections.Generic.List< T >.Count, Terraria.Collision.GetEntityEdgeTiles(), Terraria.Player.gfxOffY, Terraria.Tile.halfBrick(), Terraria.Entity.height, Terraria.Entity.Hitbox, Microsoft.Xna.Framework.Rectangle.Inflate(), int, Terraria.WorldGen.InWorld(), Terraria.Tile.leftSlope(), Terraria.Tile.nactive(), Microsoft.Xna.Framework.Vector2.Normalize(), Terraria.Player.onTrack, Terraria.ID.TileID.Sets.Platforms, Terraria.Entity.position, Terraria.Player.pulley, Terraria.Tile.rightSlope(), System.Math.Sign(), Terraria.Entity.Size, Terraria.Tile.slope(), Terraria.Main.tile, Terraria.Collision.TileCollision(), Terraria.Entity.TopLeft, Terraria.Entity.TopRight, Terraria.Tile.type, Terraria.Entity.width, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Point.Y, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Player.DryCollision(), and Terraria.NPC.UpdateCollision().