Terraria Decompiled: Terraria.Collision.SolidFullTiles
SolidFullTiles()
static bool Terraria.Collision.SolidFullTiles (Vector2 pos, Vector2 size) inline static
Definition at line 3612 of file Collision.cs.
        {
            int num = (int)(pos.X / 16f);
            int num2 = (int)(pos.Y / 16f);
            int num3 = (int)Math.Ceiling((double)((pos.X + size.X) / 16f));
            int num4 = (int)Math.Ceiling((double)((pos.Y + size.Y) / 16f));
            int num5 = Math.Max(num, 0);
            num2 = Math.Max(num2, 0);
            num3 = Math.Min(num3, Main.maxTilesX - 1);
            num4 = Math.Min(num4, Main.maxTilesY - 1);
            for (int i = num5; i < num3; i++)
            {
                for (int j = num2; j < num4; j++)
                {
                    Tile tile = Main.tile[i, j];
                    if (tile != null && tile.nactive() && tile.blockType() == 0 && Main.tileSolid[(int)tile.type] && !Main.tileSolidTop[(int)tile.type])
                    {
                        return true;
                    }
                }
            }
            return false;
        }
References Terraria.Tile.blockType(), System.Math.Ceiling(), int, System.Math.Max(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, System.Math.Min(), Terraria.Tile.nactive(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Tile.type, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.GameContent.LeashedEntities.LeashedKite.MoveKite().