Terraria Decompiled: Terraria.Collision.HitLineWall
HitLineWall()
static Point Terraria.Collision.HitLineWall (int x1, int y1, int x2, int y2) inline static
Definition at line 1228 of file Collision.cs.
        {
            int num = x1;
            int num2 = y1;
            int num3 = x2;
            int num4 = y2;
            if (num <= 1)
            {
                num = 1;
            }
            if (num >= Main.maxTilesX)
            {
                num = Main.maxTilesX - 1;
            }
            if (num3 <= 1)
            {
                num3 = 1;
            }
            if (num3 >= Main.maxTilesX)
            {
                num3 = Main.maxTilesX - 1;
            }
            if (num2 <= 1)
            {
                num2 = 1;
            }
            if (num2 >= Main.maxTilesY - 40)
            {
                num2 = Main.maxTilesY - 40;
            }
            if (num4 <= 1)
            {
                num4 = 1;
            }
            if (num4 >= Main.maxTilesY - 40)
            {
                num4 = Main.maxTilesY - 40;
            }
            float num5 = (float)Math.Abs(num - num3);
            float num6 = (float)Math.Abs(num2 - num4);
            if (num5 == 0f && num6 == 0f)
            {
                return new Point(num, num2);
            }
            float num7 = 1f;
            float num8 = 1f;
            if (num5 == 0f || num6 == 0f)
            {
                if (num5 == 0f)
                {
                    num7 = 0f;
                }
                if (num6 == 0f)
                {
                    num8 = 0f;
                }
            }
            else if (num5 > num6)
            {
                num7 = num5 / num6;
            }
            else
            {
                num8 = num6 / num5;
            }
            float num9 = 0f;
            float num10 = 0f;
            int num11 = 1;
            if (num2 < num4)
            {
                num11 = 2;
            }
            int num12 = (int)num5;
            int num13 = (int)num6;
            int num14 = Math.Sign(num3 - num);
            int num15 = Math.Sign(num4 - num2);
            bool flag = false;
            bool flag2 = false;
            Point point;
            try
            {
                for (;;)
                {
                    if (num11 == 2)
                    {
                        num9 += num7;
                        int num16 = (int)num9;
                        num9 -= (float)num16;
                        for (int i = 0; i < num16; i++)
{
                            Main.tile[num, num2];
                            if (Collision.HitWallSubstep(num, num2))
{
                                goto Block_18;
                            }
                            if (num12 == 0 && num13 == 0)
{
                                flag = true;
                                break;
                            }
                            num += num14;
                            num12--;
                            if (num12 == 0 && num13 == 0 && num16 == 1)
{
                                flag2 = true;
                            }
                        }
                        if (num13 != 0)
{
                            num11 = 1;
                        }
                    }
                    else if (num11 == 1)
                    {
                        num10 += num8;
                        int num17 = (int)num10;
                        num10 -= (float)num17;
                        for (int j = 0; j < num17; j++)
{
                            Main.tile[num, num2];
                            if (Collision.HitWallSubstep(num, num2))
{
                                goto Block_26;
                            }
                            if (num12 == 0 && num13 == 0)
{
                                flag = true;
                                break;
                            }
                            num2 += num15;
                            num13--;
                            if (num12 == 0 && num13 == 0 && num17 == 1)
{
                                flag2 = true;
                            }
                        }
                        if (num12 != 0)
{
                            num11 = 2;
                        }
                    }
                    if (Main.tile[num, num2] == null)
                    {
                        goto Block_33;
                    }
                    Main.tile[num, num2];
                    if (Collision.HitWallSubstep(num, num2))
                    {
                        goto Block_34;
                    }
                    if (flag || flag2)
                    {
                        goto Block_35;
                    }
                }
                Block_18:
                return new Point(num, num2);
                Block_26:
                return new Point(num, num2);
                Block_33:
                return new Point(-1, -1);
                Block_34:
                return new Point(num, num2);
                Block_35:
                point = new Point(num, num2);
            }
            catch
            {
                point = new Point(-1, -1);
            }
            return point;
        }
References System.Math.Abs(), Terraria.Collision.HitWallSubstep(), int, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, System.Math.Sign(), and Terraria.Main.tile.
Referenced by Terraria.GameContent.SmartCursorHelper.Step_Hammers().