Terraria Decompiled: Terraria.Collision.HitLine
HitLine()
static bool Terraria.Collision.HitLine (int x1, int y1, int x2, int y2, int ignoreX, int ignoreY, List< Point > ignoreTargets, out Point col) inline static
Definition at line 833 of file Collision.cs.
        {
            int num = Utils.Clamp<int>(x1, 1, Main.maxTilesX - 1);
            int num2 = Utils.Clamp<int>(x2, 1, Main.maxTilesX - 1);
            int num3 = Utils.Clamp<int>(y1, 1, Main.maxTilesY - 40);
            int num4 = Utils.Clamp<int>(y2, 1, Main.maxTilesY - 40);
            float num5 = (float)Math.Abs(num - num2);
            float num6 = (float)Math.Abs(num3 - num4);
            if (num5 == 0f && num6 == 0f)
            {
                col = new Point(num, num3);
                return true;
            }
            float num7 = 1f;
            float num8 = 1f;
            if (num5 == 0f || num6 == 0f)
            {
                if (num5 == 0f)
                {
                    num7 = 0f;
                }
                if (num6 == 0f)
                {
                    num8 = 0f;
                }
            }
            else if (num5 > num6)
            {
                num7 = num5 / num6;
            }
            else
            {
                num8 = num6 / num5;
            }
            float num9 = 0f;
            float num10 = 0f;
            int num11 = 1;
            if (num3 < num4)
            {
                num11 = 2;
            }
            int num12 = (int)num5;
            int num13 = (int)num6;
            int num14 = Math.Sign(num2 - num);
            int num15 = Math.Sign(num4 - num3);
            bool flag = false;
            bool flag2 = false;
            bool flag3;
            try
            {
                for (;;)
                {
                    if (num11 == 2)
                    {
                        num9 += num7;
                        int num16 = (int)num9;
                        num9 -= (float)num16;
                        for (int i = 0; i < num16; i++)
{
                            if (Main.tile[num, num3 - 1] == null)
{
                                goto Block_10;
                            }
                            if (Main.tile[num, num3 + 1] == null)
{
                                goto Block_11;
                            }
                            Tile tile = Main.tile[num, num3 - 1];
                            Tile tile2 = Main.tile[num, num3 + 1];
                            Tile tile3 = Main.tile[num, num3];
                            if (!ignoreTargets.Contains(new Point(num, num3)) && !ignoreTargets.Contains(new Point(num, num3 - 1)) && !ignoreTargets.Contains(new Point(num, num3 + 1)))
{
                                if (ignoreY != -1 && num15 < 0 && !tile.inActive() && tile.active() && Main.tileSolid[(int)tile.type] && !Main.tileSolidTop[(int)tile.type])
{
                                    goto Block_20;
                                }
                                if (ignoreY != 1 && num15 > 0 && !tile2.inActive() && tile2.active() && Main.tileSolid[(int)tile2.type] && !Main.tileSolidTop[(int)tile2.type])
{
                                    goto Block_26;
                                }
                                if (!tile3.inActive() && tile3.active() && Main.tileSolid[(int)tile3.type] && !Main.tileSolidTop[(int)tile3.type])
{
                                    goto Block_30;
                                }
                            }
                            if (num12 == 0 && num13 == 0)
{
                                flag = true;
                                break;
                            }
                            num += num14;
                            num12--;
                            if (num12 == 0 && num13 == 0 && num16 == 1)
{
                                flag2 = true;
                            }
                        }
                        if (num13 != 0)
{
                            num11 = 1;
                        }
                    }
                    else if (num11 == 1)
                    {
                        num10 += num8;
                        int num17 = (int)num10;
                        num10 -= (float)num17;
                        for (int j = 0; j < num17; j++)
{
                            if (Main.tile[num - 1, num3] == null)
{
                                goto Block_38;
                            }
                            if (Main.tile[num + 1, num3] == null)
{
                                goto Block_39;
                            }
                            Tile tile4 = Main.tile[num - 1, num3];
                            Tile tile5 = Main.tile[num + 1, num3];
                            Tile tile6 = Main.tile[num, num3];
                            if (!ignoreTargets.Contains(new Point(num, num3)) && !ignoreTargets.Contains(new Point(num - 1, num3)) && !ignoreTargets.Contains(new Point(num + 1, num3)))
{
                                if (ignoreX != -1 && num14 < 0 && !tile4.inActive() && tile4.active() && Main.tileSolid[(int)tile4.type] && !Main.tileSolidTop[(int)tile4.type])
{
                                    goto Block_48;
                                }
                                if (ignoreX != 1 && num14 > 0 && !tile5.inActive() && tile5.active() && Main.tileSolid[(int)tile5.type] && !Main.tileSolidTop[(int)tile5.type])
{
                                    goto Block_54;
                                }
                                if (!tile6.inActive() && tile6.active() && Main.tileSolid[(int)tile6.type] && !Main.tileSolidTop[(int)tile6.type])
{
                                    goto Block_58;
                                }
                            }
                            if (num12 == 0 && num13 == 0)
{
                                flag = true;
                                break;
                            }
                            num3 += num15;
                            num13--;
                            if (num12 == 0 && num13 == 0 && num17 == 1)
{
                                flag2 = true;
                            }
                        }
                        if (num12 != 0)
{
                            num11 = 2;
                        }
                    }
                    if (Main.tile[num, num3] == null)
                    {
                        goto Block_65;
                    }
                    Tile tile7 = Main.tile[num, num3];
                    if (!ignoreTargets.Contains(new Point(num, num3)) && !tile7.inActive() && tile7.active() && Main.tileSolid[(int)tile7.type] && !Main.tileSolidTop[(int)tile7.type])
                    {
                        goto Block_70;
                    }
                    if (flag || flag2)
                    {
                        goto Block_71;
                    }
                }
                Block_10:
                col = new Point(num, num3 - 1);
                return false;
                Block_11:
                col = new Point(num, num3 + 1);
                return false;
                Block_20:
                col = new Point(num, num3 - 1);
                return true;
                Block_26:
                col = new Point(num, num3 + 1);
                return true;
                Block_30:
                col = new Point(num, num3);
                return true;
                Block_38:
                col = new Point(num - 1, num3);
                return false;
                Block_39:
                col = new Point(num + 1, num3);
                return false;
                Block_48:
                col = new Point(num - 1, num3);
                return true;
                Block_54:
                col = new Point(num + 1, num3);
                return true;
                Block_58:
                col = new Point(num, num3);
                return true;
                Block_65:
                col = new Point(num, num3);
                return false;
                Block_70:
                col = new Point(num, num3);
                return true;
                Block_71:
                col = new Point(num, num3);
                flag3 = true;
            }
            catch
            {
                col = new Point(x1, y1);
                flag3 = false;
            }
            return flag3;
        }
References System.Math.Abs(), Terraria.Tile.active(), Terraria.Utils.Clamp(), System.Collections.Generic.List< T >.Contains(), Terraria.Tile.inActive(), int, System.Math.Sign(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, and Terraria.Tile.type.
Referenced by Terraria.Collision.LaserScan(), and Terraria.GameContent.SmartCursorHelper.Step_Pickaxe_MineSolids().