Terraria Decompiled: Terraria.Collision.FindOverlapPoints
FindOverlapPoints()
static float[] Terraria.Collision.FindOverlapPoints (float relativePoint1, float relativePoint2) inline static private
Definition at line 122 of file Collision.cs.
        {
            float num = Math.Min(relativePoint1, relativePoint2);
            float num2 = Math.Max(relativePoint1, relativePoint2);
            float num3 = Math.Max(0f, num);
            float num4 = Math.Min(1f, num2);
            if (num3 > num4)
            {
                return new float[0];
            }
            if (num3 == num4)
            {
                return new float[] { num3 };
            }
            return new float[] { num3, num4 };
        }
References System.Math.Max(), and System.Math.Min().
Referenced by Terraria.Collision.OneDimensionalIntersection().