Terraria Decompiled: Terraria.Collision.SlopeCollision
SlopeCollision()
static Vector4 Terraria.Collision.SlopeCollision (Vector2 Position, Vector2 Velocity, int Width, int Height, float gravity = 0f, bool fall = false, bool ignoreAetheriumPlatforms = false) inline static
Definition at line 1877 of file Collision.cs.
        {
            Collision.stair = false;
            Collision.stairFall = false;
            BitsByte bitsByte = 0;
            float num = Position.Y;
            float num2 = Position.Y;
            Collision.sloping = false;
            Vector2 vector = Position;
            Vector2 vector2 = Velocity;
            int num3 = (int)(Position.X / 16f) - 1;
            int num4 = (int)((Position.X + (float)Width) / 16f) + 2;
            int num5 = (int)(Position.Y / 16f) - 1;
            int num6 = (int)((Position.Y + (float)Height) / 16f) + 2;
            int num7 = Utils.Clamp<int>(num3, 0, Main.maxTilesX - 1);
            num4 = Utils.Clamp<int>(num4, 0, Main.maxTilesX - 1);
            num5 = Utils.Clamp<int>(num5, 0, Main.maxTilesY - 40);
            num6 = Utils.Clamp<int>(num6, 0, Main.maxTilesY - 40);
            for (int i = num7; i < num4; i++)
            {
                for (int j = num5; j < num6; j++)
                {
                    Tile tile = Main.tile[i, j];
                    if (tile != null && tile.active() && !tile.inActive())
                    {
                        bool flag = Main.tileSolid[(int)tile.type];
                        if (Main.tileSolidTop[(int)tile.type] && tile.frameY == 0)
{
                            flag = true;
                        }
                        if (ignoreAetheriumPlatforms && tile.type == 19 && tile.frameY / 18 == 50)
{
                            flag = false;
                        }
                        if (flag)
{
                            Vector2 vector3;
                            vector3.X = (float)(i * 16);
                            vector3.Y = (float)(j * 16);
                            int num8 = 16;
                            if (Main.tile[i, j].halfBrick())
{
                                vector3.Y += 8f;
                                num8 -= 8;
                            }
                            if (Position.X + (float)Width > vector3.X && Position.X < vector3.X + 16f && Position.Y + (float)Height > vector3.Y && Position.Y < vector3.Y + (float)num8)
{
                                bool flag2 = true;
                                if (TileID.Sets.Platforms[(int)Main.tile[i, j].type])
{
                                    if (Velocity.Y < 0f)
{
                                        flag2 = false;
                                    }
                                    if (Position.Y + (float)Height < (float)(j * 16) || Position.Y + (float)Height - (1f + Math.Abs(Velocity.X)) > (float)(j * 16 + 16))
{
                                        flag2 = false;
                                    }
                                    if (((Main.tile[i, j].slope() == 1 && Velocity.X >= 0f) || (Main.tile[i, j].slope() == 2 && Velocity.X <= 0f)) && (Position.Y + (float)Height) / 16f - 1f == (float)j)
{
                                        flag2 = false;
                                    }
                                }
                                if (flag2)
{
                                    bool flag3 = false;
                                    if (fall && TileID.Sets.Platforms[(int)Main.tile[i, j].type])
{
                                        flag3 = true;
                                    }
                                    int num9 = (int)Main.tile[i, j].slope();
                                    vector3.X = (float)(i * 16);
                                    vector3.Y = (float)(j * 16);
                                    if (Position.X + (float)Width > vector3.X && Position.X < vector3.X + 16f && Position.Y + (float)Height > vector3.Y && Position.Y < vector3.Y + 16f)
{
                                        float num10 = 0f;
                                        if (num9 == 3 || num9 == 4)
{
                                            if (num9 == 3)
{
                                                num10 = Position.X - vector3.X;
                                            }
                                            if (num9 == 4)
{
                                                num10 = vector3.X + 16f - (Position.X + (float)Width);
                                            }
                                            if (num10 >= 0f)
{
                                                if (Position.Y <= vector3.Y + 16f - num10)
{
                                                    float num11 = vector3.Y + 16f - Position.Y - num10;
                                                    if (Position.Y + num11 > num2)
{
                                                        vector.Y = Position.Y + num11;
                                                        num2 = vector.Y;
                                                        if (vector2.Y < 0.0101f)
{
                                                            vector2.Y = 0.0101f;
                                                        }
                                                        bitsByte[num9] = true;
                                                    }
                                                }
                                            }
                                            else if (Position.Y > vector3.Y)
{
                                                float num12 = vector3.Y + 16f;
                                                if (vector.Y < num12)
{
                                                    vector.Y = num12;
                                                    if (vector2.Y < 0.0101f)
{
                                                        vector2.Y = 0.0101f;
                                                    }
                                                }
                                            }
                                        }
                                        if (num9 == 1 || num9 == 2)
{
                                            if (num9 == 1)
{
                                                num10 = Position.X - vector3.X;
                                            }
                                            if (num9 == 2)
{
                                                num10 = vector3.X + 16f - (Position.X + (float)Width);
                                            }
                                            if (num10 >= 0f)
{
                                                if (Position.Y + (float)Height >= vector3.Y + num10)
{
                                                    float num13 = vector3.Y - (Position.Y + (float)Height) + num10;
                                                    if (Position.Y + num13 < num)
{
                                                        if (flag3)
{
                                                            Collision.stairFall = true;
                                                        }
                                                        else
{
                                                            if (TileID.Sets.Platforms[(int)Main.tile[i, j].type])
{
                                                                Collision.stair = true;
                                                            }
                                                            else
{
                                                                Collision.stair = false;
                                                            }
                                                            vector.Y = Position.Y + num13;
                                                            num = vector.Y;
                                                            if (vector2.Y > 0f)
{
                                                                vector2.Y = 0f;
                                                            }
                                                            bitsByte[num9] = true;
                                                        }
                                                    }
                                                }
                                            }
                                            else if (TileID.Sets.Platforms[(int)Main.tile[i, j].type] && Position.Y + (float)Height - 4f - Math.Abs(Velocity.X) > vector3.Y)
{
                                                if (flag3)
{
                                                    Collision.stairFall = true;
                                                }
                                            }
                                            else
{
                                                float num14 = vector3.Y - (float)Height;
                                                if (vector.Y > num14)
{
                                                    if (flag3)
{
                                                        Collision.stairFall = true;
                                                    }
                                                    else
{
                                                        if (TileID.Sets.Platforms[(int)Main.tile[i, j].type])
{
                                                            Collision.stair = true;
                                                        }
                                                        else
{
                                                            Collision.stair = false;
                                                        }
                                                        vector.Y = num14;
                                                        if (vector2.Y > 0f)
{
                                                            vector2.Y = 0f;
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            Vector2 vector4 = vector - Position;
            Vector2 vector5 = Collision.TileCollision(Position, vector4, Width, Height, false, false, 1, false, false, true);
            if (vector5.Y > vector4.Y)
            {
                float num15 = vector4.Y - vector5.Y;
                vector.Y = Position.Y + vector5.Y;
                if (bitsByte[1])
                {
                    vector.X = Position.X - num15;
                }
                if (bitsByte[2])
                {
                    vector.X = Position.X + num15;
                }
                vector2.X = 0f;
                vector2.Y = 0f;
                Collision.up = false;
            }
            else if (vector5.Y < vector4.Y)
            {
                float num16 = vector5.Y - vector4.Y;
                vector.Y = Position.Y + vector5.Y;
                if (bitsByte[3])
                {
                    vector.X = Position.X - num16;
                }
                if (bitsByte[4])
                {
                    vector.X = Position.X + num16;
                }
                vector2.X = 0f;
                vector2.Y = 0f;
            }
            return new Vector4(vector, vector2.X, vector2.Y);
        }
References System.Math.Abs(), Terraria.Tile.active(), Terraria.Utils.Clamp(), Terraria.Tile.frameY, Terraria.Tile.halfBrick(), Terraria.Tile.inActive(), int, Terraria.ID.TileID.Sets.Platforms, Terraria.Tile.slope(), Terraria.Main.tile, Terraria.Collision.TileCollision(), Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Tile.type, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Utils.CheckForGoodTeleportationSpot(), Terraria.NPC.Collision_MoveSlopesAndStairFall(), Terraria.NPC.Collision_MoveSnailOnSlopes(), Terraria.Collision.FindCollisionTile(), Terraria.Gore.Gore_UpdateLeaf(), Terraria.Projectile.HandleMovement(), Terraria.Collision.IsClearSpotTest(), Terraria.WorldItem.MoveInWorld(), Terraria.Player.SlopingCollision(), Terraria.Collision.TileCollisionInStepsOf16(), Terraria.Mount.TryStabilizingSmallMountPositionBetweenSlopes(), Terraria.Gore.Update(), and Terraria.Projectile.UpdatePosition().