Terraria Decompiled: Terraria.Collision.CanHitWithCheck
CanHitWithCheck() [2/2]
static bool Terraria.Collision.CanHitWithCheck (Vector2 Position1, int Width1, int Height1, Vector2 Position2, int Width2, int Height2, Utils::TileActionAttempt check) inline static
Definition at line 483 of file Collision.cs.
        {
            int num = (int)((Position1.X + (float)(Width1 / 2)) / 16f);
            int num2 = (int)((Position1.Y + (float)(Height1 / 2)) / 16f);
            int num3 = (int)((Position2.X + (float)(Width2 / 2)) / 16f);
            int num4 = (int)((Position2.Y + (float)(Height2 / 2)) / 16f);
            if (num <= 1)
            {
                num = 1;
            }
            if (num >= Main.maxTilesX)
            {
                num = Main.maxTilesX - 1;
            }
            if (num3 <= 1)
            {
                num3 = 1;
            }
            if (num3 >= Main.maxTilesX)
            {
                num3 = Main.maxTilesX - 1;
            }
            if (num2 <= 1)
            {
                num2 = 1;
            }
            if (num2 >= Main.maxTilesY - 40)
            {
                num2 = Main.maxTilesY - 40;
            }
            if (num4 <= 1)
            {
                num4 = 1;
            }
            if (num4 >= Main.maxTilesY - 40)
            {
                num4 = Main.maxTilesY - 40;
            }
            bool flag;
            try
            {
                for (;;)
                {
                    int num5 = Math.Abs(num - num3);
                    int num6 = Math.Abs(num2 - num4);
                    if (num == num3 && num2 == num4)
                    {
                        break;
                    }
                    if (num5 > num6)
                    {
                        if (num < num3)
{
                            num++;
                        }
                        else
{
                            num--;
                        }
                        if (Main.tile[num, num2 - 1] == null)
{
                            goto Block_14;
                        }
                        if (Main.tile[num, num2 + 1] == null)
{
                            goto Block_15;
                        }
                        if (!Main.tile[num, num2 - 1].inActive() && Main.tile[num, num2 - 1].active() && Main.tileSolid[(int)Main.tile[num, num2 - 1].type] && !Main.tileSolidTop[(int)Main.tile[num, num2 - 1].type] && Main.tile[num, num2 - 1].slope() == 0 && !Main.tile[num, num2 - 1].halfBrick() && !Main.tile[num, num2 + 1].inActive() && Main.tile[num, num2 + 1].active() && Main.tileSolid[(int)Main.tile[num, num2 + 1].type] && !Main.tileSolidTop[(int)Main.tile[num, num2 + 1].type] && Main.tile[num, num2 + 1].slope() == 0 && !Main.tile[num, num2 + 1].halfBrick())
{
                            goto Block_27;
                        }
                    }
                    else
                    {
                        if (num2 < num4)
{
                            num2++;
                        }
                        else
{
                            num2--;
                        }
                        if (Main.tile[num - 1, num2] == null)
{
                            goto Block_29;
                        }
                        if (Main.tile[num + 1, num2] == null)
{
                            goto Block_30;
                        }
                        if (!Main.tile[num - 1, num2].inActive() && Main.tile[num - 1, num2].active() && Main.tileSolid[(int)Main.tile[num - 1, num2].type] && !Main.tileSolidTop[(int)Main.tile[num - 1, num2].type] && Main.tile[num - 1, num2].slope() == 0 && !Main.tile[num - 1, num2].halfBrick() && !Main.tile[num + 1, num2].inActive() && Main.tile[num + 1, num2].active() && Main.tileSolid[(int)Main.tile[num + 1, num2].type] && !Main.tileSolidTop[(int)Main.tile[num + 1, num2].type] && Main.tile[num + 1, num2].slope() == 0 && !Main.tile[num + 1, num2].halfBrick())
{
                            goto Block_42;
                        }
                    }
                    if (Main.tile[num, num2] == null)
                    {
                        goto Block_43;
                    }
                    if (!Main.tile[num, num2].inActive() && Main.tile[num, num2].active() && Main.tileSolid[(int)Main.tile[num, num2].type] && !Main.tileSolidTop[(int)Main.tile[num, num2].type])
                    {
                        goto Block_47;
                    }
                    if (!check(num, num2))
                    {
                        goto Block_48;
                    }
                }
                return true;
                Block_14:
                return false;
                Block_15:
                return false;
                Block_27:
                return false;
                Block_29:
                return false;
                Block_30:
                return false;
                Block_42:
                return false;
                Block_43:
                return false;
                Block_47:
                return false;
                Block_48:
                flag = false;
            }
            catch
            {
                flag = false;
            }
            return flag;
        }
References System.Math.Abs(), Terraria.Tile.active(), Terraria.Tile.halfBrick(), Terraria.Tile.inActive(), int, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Tile.slope(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Tile.type, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.