Terraria Decompiled: Terraria.Collision.CanHitLine
CanHitLine()
static bool Terraria.Collision.CanHitLine (Vector2 Position1, int Width1, int Height1, Vector2 Position2, int Width2, int Height2) inline static
Definition at line 619 of file Collision.cs.
        {
            int num = (int)((Position1.X + (float)(Width1 / 2)) / 16f);
            int num2 = (int)((Position1.Y + (float)(Height1 / 2)) / 16f);
            int num3 = (int)((Position2.X + (float)(Width2 / 2)) / 16f);
            int num4 = (int)((Position2.Y + (float)(Height2 / 2)) / 16f);
            if (num <= 1)
            {
                num = 1;
            }
            if (num >= Main.maxTilesX)
            {
                num = Main.maxTilesX - 1;
            }
            if (num3 <= 1)
            {
                num3 = 1;
            }
            if (num3 >= Main.maxTilesX)
            {
                num3 = Main.maxTilesX - 1;
            }
            if (num2 <= 1)
            {
                num2 = 1;
            }
            if (num2 >= Main.maxTilesY - 40)
            {
                num2 = Main.maxTilesY - 40;
            }
            if (num4 <= 1)
            {
                num4 = 1;
            }
            if (num4 >= Main.maxTilesY - 40)
            {
                num4 = Main.maxTilesY - 40;
            }
            float num5 = (float)Math.Abs(num - num3);
            float num6 = (float)Math.Abs(num2 - num4);
            if (num5 == 0f && num6 == 0f)
            {
                return true;
            }
            float num7 = 1f;
            float num8 = 1f;
            if (num5 == 0f || num6 == 0f)
            {
                if (num5 == 0f)
                {
                    num7 = 0f;
                }
                if (num6 == 0f)
                {
                    num8 = 0f;
                }
            }
            else if (num5 > num6)
            {
                num7 = num5 / num6;
            }
            else
            {
                num8 = num6 / num5;
            }
            float num9 = 0f;
            float num10 = 0f;
            int num11 = 1;
            if (num2 < num4)
            {
                num11 = 2;
            }
            int num12 = (int)num5;
            int num13 = (int)num6;
            int num14 = Math.Sign(num3 - num);
            int num15 = Math.Sign(num4 - num2);
            bool flag = false;
            bool flag2 = false;
            bool flag3;
            try
            {
                for (;;)
                {
                    if (num11 == 2)
                    {
                        num9 += num7;
                        int num16 = (int)num9;
                        num9 -= (float)num16;
                        for (int i = 0; i < num16; i++)
{
                            if (Main.tile[num, num2 - 1] == null)
{
                                goto Block_18;
                            }
                            if (Main.tile[num, num2] == null)
{
                                goto Block_19;
                            }
                            if (Main.tile[num, num2 + 1] == null)
{
                                goto Block_20;
                            }
                            Tile tile = Main.tile[num, num2 - 1];
                            Tile tile2 = Main.tile[num, num2 + 1];
                            Tile tile3 = Main.tile[num, num2];
                            if ((!tile.inActive() && tile.active() && Main.tileSolid[(int)tile.type] && !Main.tileSolidTop[(int)tile.type]) || (!tile2.inActive() && tile2.active() && Main.tileSolid[(int)tile2.type] && !Main.tileSolidTop[(int)tile2.type]) || (!tile3.inActive() && tile3.active() && Main.tileSolid[(int)tile3.type] && !Main.tileSolidTop[(int)tile3.type]))
{
                                goto IL_0294;
                            }
                            if (num12 == 0 && num13 == 0)
{
                                flag = true;
                                break;
                            }
                            num += num14;
                            num12--;
                            if (num12 == 0 && num13 == 0 && num16 == 1)
{
                                flag2 = true;
                            }
                        }
                        if (num13 != 0)
{
                            num11 = 1;
                        }
                    }
                    else if (num11 == 1)
                    {
                        num10 += num8;
                        int num17 = (int)num10;
                        num10 -= (float)num17;
                        for (int j = 0; j < num17; j++)
{
                            if (Main.tile[num - 1, num2] == null)
{
                                goto Block_37;
                            }
                            if (Main.tile[num, num2] == null)
{
                                goto Block_38;
                            }
                            if (Main.tile[num + 1, num2] == null)
{
                                goto Block_39;
                            }
                            Tile tile4 = Main.tile[num - 1, num2];
                            Tile tile5 = Main.tile[num + 1, num2];
                            Tile tile6 = Main.tile[num, num2];
                            if ((!tile4.inActive() && tile4.active() && Main.tileSolid[(int)tile4.type] && !Main.tileSolidTop[(int)tile4.type]) || (!tile5.inActive() && tile5.active() && Main.tileSolid[(int)tile5.type] && !Main.tileSolidTop[(int)tile5.type]) || (!tile6.inActive() && tile6.active() && Main.tileSolid[(int)tile6.type] && !Main.tileSolidTop[(int)tile6.type]))
{
                                goto IL_040A;
                            }
                            if (num12 == 0 && num13 == 0)
{
                                flag = true;
                                break;
                            }
                            num2 += num15;
                            num13--;
                            if (num12 == 0 && num13 == 0 && num17 == 1)
{
                                flag2 = true;
                            }
                        }
                        if (num12 != 0)
{
                            num11 = 2;
                        }
                    }
                    if (Main.tile[num, num2] == null)
                    {
                        goto Block_55;
                    }
                    Tile tile7 = Main.tile[num, num2];
                    if (!tile7.inActive() && tile7.active() && Main.tileSolid[(int)tile7.type] && !Main.tileSolidTop[(int)tile7.type])
                    {
                        goto Block_59;
                    }
                    if (flag || flag2)
                    {
                        goto Block_60;
                    }
                }
                Block_18:
                return false;
                Block_19:
                return false;
                Block_20:
                return false;
                IL_0294:
                return false;
                Block_37:
                return false;
                Block_38:
                return false;
                Block_39:
                return false;
                IL_040A:
                return false;
                Block_55:
                return false;
                Block_59:
                return false;
                Block_60:
                flag3 = true;
            }
            catch
            {
                flag3 = false;
            }
            return flag3;
        }
References System.Math.Abs(), Terraria.Tile.active(), Terraria.Tile.inActive(), int, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, System.Math.Sign(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Tile.type, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.NPC.AddKingSlimeTeleportCacheTiles(), Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.Projectile.AI_001(), Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_006_Worms(), Terraria.NPC.AI_007_TownEntities(), Terraria.NPC.AI_015_KingSlime(), Terraria.Projectile.AI_053_HandleSentryNPCTargeting(), Terraria.Projectile.AI_062(), Terraria.Projectile.AI_100_Medusa(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_109_DarkMage(), Terraria.NPC.AI_121_QueenSlime(), Terraria.Projectile.AI_130_FlameBurstTower_FindTarget(), Terraria.Projectile.AI_134_Ballista_FindTarget(), Terraria.Projectile.AI_137_CanHit(), Terraria.NPC.BloodNautilus_CallForHelp(), Terraria.Player.CanHit(), Terraria.Graphics.Renderers.FakeFishParticle.CanHit(), Terraria.Projectile.CanHitWithMeleeWeapon(), Terraria.Projectile.CanHitWithOwnBody(), Terraria.Mount.CastSuperCartLaser(), Terraria.GameContent.UI.EmoteBubble.CheckForNPCsToReactToEmoteBubble(), Terraria.Projectile.Colliding(), Terraria.Projectile.Damage_PVE_Inner(), Terraria.Projectile.FindTargetWithinRange(), Terraria.Player.GetFarthestSpawnPositionOnLine(), Terraria.WorldGen.GrowMoreVines(), Terraria.Projectile.HandleMovement(), Terraria.NPC.HitEffect(), Terraria.Player.ItemCheck_Shoot(), Terraria.Player.QuickMinecart(), Terraria.Player.QuickMinecartSnap(), Terraria.Player.SpawnHallucination(), Terraria.GameInput.LockOnHelper.Update(), and Terraria.Mount.UpdateEffects().