Terraria Decompiled: Terraria.Collision.HitTilesInACircle
HitTilesInACircle()
static void Terraria.Collision.HitTilesInACircle (Vector2 Position, Vector2 Velocity, int Width, int Height) inline static
Definition at line 3100 of file Collision.cs.
        {
            Vector2 vector = Position + Velocity;
            int num = (int)(Position.X / 16f) - 1;
            int num2 = (int)((Position.X + (float)Width) / 16f) + 2;
            int num3 = (int)(Position.Y / 16f) - 1;
            int num4 = (int)((Position.Y + (float)Height) / 16f) + 2;
            if (num < 0)
            {
                num = 0;
            }
            if (num2 > Main.maxTilesX)
            {
                num2 = Main.maxTilesX;
            }
            if (num3 < 0)
            {
                num3 = 0;
            }
            if (num4 > Main.maxTilesY - 40)
            {
                num4 = Main.maxTilesY - 40;
            }
            for (int i = num; i < num2; i++)
            {
                for (int j = num3; j < num4; j++)
                {
                    if (Main.tile[i, j] != null && !Main.tile[i, j].inActive() && Main.tile[i, j].active() && (Main.tileSolid[(int)Main.tile[i, j].type] || (Main.tileSolidTop[(int)Main.tile[i, j].type] && Main.tile[i, j].frameY == 0)))
                    {
                        Vector2 vector2;
                        vector2.X = (float)(i * 16);
                        vector2.Y = (float)(j * 16);
                        int num5 = 16;
                        if (Main.tile[i, j].halfBrick())
{
                            vector2.Y += 8f;
                            num5 -= 8;
                        }
                        if (vector.X + (float)Width >= vector2.X && vector.X <= vector2.X + 16f && vector.Y + (float)Height >= vector2.Y && vector.Y <= vector2.Y + (float)num5 && (new Vector2(vector.X + (float)(Width / 2), vector.Y + (float)(Height / 2)) - new Vector2(vector2.X + 8f, vector2.Y + 8f)).Length() < (float)((Width + Height) / 4))
{
                            WorldGen.KillTile(i, j, true, true, false);
                        }
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.Tile.frameY, Terraria.Tile.halfBrick(), Terraria.Tile.inActive(), int, Terraria.WorldGen.KillTile(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Tile.type, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Projectile.AI(), and Terraria.Projectile.HandleMovement().