Terraria Decompiled: Terraria.Collision.StickyTiles
StickyTiles()
static Vector2 Terraria.Collision.StickyTiles (Vector2 Position, Vector2 Velocity, int Width, int Height) inline static
Definition at line 3433 of file Collision.cs.
        {
            int num = (int)(Position.X / 16f) - 1;
            int num2 = (int)((Position.X + (float)Width) / 16f) + 2;
            int num3 = (int)(Position.Y / 16f) - 1;
            int num4 = (int)((Position.Y + (float)Height) / 16f) + 2;
            if (num < 0)
            {
                num = 0;
            }
            if (num2 > Main.maxTilesX)
            {
                num2 = Main.maxTilesX;
            }
            if (num3 < 0)
            {
                num3 = 0;
            }
            if (num4 > Main.maxTilesY - 40)
            {
                num4 = Main.maxTilesY - 40;
            }
            for (int i = num; i < num2; i++)
            {
                for (int j = num3; j < num4; j++)
                {
                    if (Main.tile[i, j] != null && Main.tile[i, j].active() && !Main.tile[i, j].inActive())
                    {
                        if (Main.tile[i, j].type == 51)
{
                            int num5 = 0;
                            Vector2 vector;
                            vector.X = (float)(i * 16);
                            vector.Y = (float)(j * 16);
                            if (Position.X + (float)Width > vector.X - (float)num5 && Position.X < vector.X + 16f + (float)num5 && Position.Y + (float)Height > vector.Y && (double)Position.Y < (double)vector.Y + 16.01)
{
                                if (Main.tile[i, j].type == 51 && (double)(Math.Abs(Velocity.X) + Math.Abs(Velocity.Y)) > 0.7 && Main.rand.Next(30) == 0)
{
                                    Dust.NewDust(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16, 30, 0f, 0f, 0, default(Color), 1f);
                                }
                                return new Vector2((float)i, (float)j);
                            }
                        }
                        else if (Main.tile[i, j].type == 229 && Main.tile[i, j].slope() == 0)
{
                            int num6 = 1;
                            Vector2 vector;
                            vector.X = (float)(i * 16);
                            vector.Y = (float)(j * 16);
                            float num7 = 16.01f;
                            if (Main.tile[i, j].halfBrick())
{
                                vector.Y += 8f;
                                num7 -= 8f;
                            }
                            if (Position.X + (float)Width > vector.X - (float)num6 && Position.X < vector.X + 16f + (float)num6 && Position.Y + (float)Height > vector.Y && Position.Y < vector.Y + num7)
{
                                if (Main.tile[i, j].type == 51 && (double)(Math.Abs(Velocity.X) + Math.Abs(Velocity.Y)) > 0.7 && Main.rand.Next(30) == 0)
{
                                    Dust.NewDust(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16, 30, 0f, 0f, 0, default(Color), 1f);
                                }
                                return new Vector2((float)i, (float)j);
                            }
                        }
                    }
                }
            }
            return new Vector2(-1f, -1f);
        }
References System.Math.Abs(), Terraria.Tile.active(), Terraria.Tile.halfBrick(), Terraria.Tile.inActive(), int, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Dust.NewDust(), Terraria.Main.rand, Terraria.Tile.slope(), Terraria.Main.tile, Terraria.Tile.type, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Player.StickyMovement().