Terraria Decompiled: Terraria.Collision.ApplyConveyorBeltMovementToVelocity
ApplyConveyorBeltMovementToVelocity()
static bool Terraria.Collision.ApplyConveyorBeltMovementToVelocity (WorldItem item, ref Vector2 velocity) inline static
Definition at line 4006 of file Collision.cs.
        {
            bool flag = false;
            Collision.BuildTileContacts(item.position, item.width, item.height, Collision.contacts);
            if (Collision.contacts.Count > 0)
            {
                int num = -1;
                int num2 = -1;
                bool flag2 = false;
                Collision.TileContactSide tileContactSide = Collision.TileContactSide.Top;
                Collision.TileContactSide tileContactSide2 = Collision.TileContactSide.Top;
                Vector2 zero = Vector2.Zero;
                bool flag3 = false;
                bool flag4 = false;
                bool flag5 = false;
                for (int i = 0; i < Collision.contacts.Count; i++)
                {
                    int num3 = TileID.Sets.ConveyorDirection[Collision.contacts[i].Type];
                    switch (Collision.contacts[i].Side)
                    {
                    case Collision.TileContactSide.Left:
                        zero.Y += (float)(num3 * Collision.contacts[i].Overlap);
                        flag3 |= num3 != 0;
                        break;
                    case Collision.TileContactSide.Right:
                        zero.Y += (float)(-(float)num3 * Collision.contacts[i].Overlap);
                        flag3 |= num3 != 0;
                        break;
                    case Collision.TileContactSide.Top:
                        zero.X += (float)(-(float)num3 * Collision.contacts[i].Overlap);
                        flag4 = num3 != 0;
                        break;
                    case Collision.TileContactSide.Bottom:
                        flag5 = true;
                        zero.X += (float)(num3 * Collision.contacts[i].Overlap);
                        flag4 = num3 != 0;
                        if (Collision.contacts[i].Slope == 1)
{
                            if ((float)(Collision.contacts[i].X * 16) < item.position.X)
{
                                Tile tile = Main.tile[Collision.contacts[i].X, Collision.contacts[i].Y - 1];
                                if (tile != null && tile.active() && tile.slope() == 3)
{
                                    num2 = i;
                                }
                            }
                        }
                        else if (Collision.contacts[i].Slope == 2 && (float)(Collision.contacts[i].X * 16 + 16) > item.Right.X)
{
                            Tile tile2 = Main.tile[Collision.contacts[i].X, Collision.contacts[i].Y - 1];
                            if (tile2 != null && tile2.active() && tile2.slope() == 4)
{
                                num = i;
                            }
                        }
                        break;
                    case Collision.TileContactSide.BottomLeft:
                        if (num3 == -1)
{
                            int x = Collision.contacts[i].X;
                            int y = Collision.contacts[i].Y;
                            Tile tile3 = Main.tile[x, y - 1];
                            byte b = tile3.slope();
                            if (!tile3.active() || (b == 1 && TileID.Sets.ConveyorDirection[(int)tile3.type] == -1))
{
                                tileContactSide = Collision.TileContactSide.BottomLeft;
                                flag2 = Main.tile[x, y].halfBrick();
                            }
                        }
                        if (num3 == 1)
{
                            tileContactSide2 = Collision.TileContactSide.BottomLeft;
                        }
                        break;
                    case Collision.TileContactSide.BottomRight:
                        if (num3 == 1)
{
                            int x2 = Collision.contacts[i].X;
                            int y2 = Collision.contacts[i].Y;
                            Tile tile4 = Main.tile[x2, y2 - 1];
                            byte b2 = tile4.slope();
                            if (!tile4.active() || (b2 == 2 && TileID.Sets.ConveyorDirection[(int)tile4.type] == 1))
{
                                tileContactSide = Collision.TileContactSide.BottomRight;
                                flag2 = Main.tile[x2, y2].halfBrick();
                            }
                        }
                        if (num3 == -1)
{
                            tileContactSide2 = Collision.TileContactSide.BottomRight;
                        }
                        break;
                    }
                }
                if (zero.X < 0f)
                {
                    if (zero.X < -8f)
                    {
                        zero.X = -2.5f;
                    }
                    else if (zero.X < -4f)
                    {
                        zero.X = -1.25f;
                    }
                    else
                    {
                        zero.X = -0.75f;
                    }
                }
                else if (zero.X > 0f)
                {
                    if (zero.X > 8f)
                    {
                        zero.X = 2.5f;
                    }
                    else if (zero.X > 4f)
                    {
                        zero.X = 1.25f;
                    }
                    else
                    {
                        zero.X = 0.75f;
                    }
                }
                if (zero.Y < 0f)
                {
                    if (zero.Y < 8f)
                    {
                        zero.Y = -2.5f;
                    }
                    else
                    {
                        zero.Y = -1.25f;
                    }
                }
                else if (zero.Y > 0f)
                {
                    if (zero.Y > 8f)
                    {
                        zero.Y = 2.5f;
                    }
                    else
                    {
                        zero.Y = 1.25f;
                    }
                }
                else if (flag3 && velocity.Y <= 1f)
                {
                    velocity.Y = 0f;
                }
                if (zero.Y == 0f)
                {
                    if (velocity.Y < 0.11f && tileContactSide != Collision.TileContactSide.Top && !flag5)
                    {
                        if (tileContactSide == Collision.TileContactSide.BottomLeft)
{
                            flag = true;
                            Vector2 bottom = item.Bottom;
                            int num4 = (int)bottom.Y;
                            num4 = (num4 + 8) / 16;
                            num4 *= 16;
                            if (flag2)
{
                                num4 += 8;
                            }
                            bottom.Y = (float)num4;
                            item.Bottom = bottom;
                            velocity.Y = 0f;
                            velocity.X = -1.25f;
                            zero.X = -2.5f;
                        }
                        if (tileContactSide == Collision.TileContactSide.BottomRight)
{
                            flag = true;
                            Vector2 bottom2 = item.Bottom;
                            int num5 = (int)bottom2.Y;
                            num5 = (num5 + 8) / 16;
                            num5 *= 16;
                            if (flag2)
{
                                num5 += 8;
                            }
                            bottom2.Y = (float)num5;
                            item.Bottom = bottom2;
                            velocity.Y = 0f;
                            velocity.X = 1.25f;
                            zero.X = 2.5f;
                        }
                    }
                    else if ((double)velocity.Y < 0.3 && !flag5)
                    {
                        if (tileContactSide2 == Collision.TileContactSide.BottomRight)
{
                            if (velocity.X <= 0.75f && velocity.X >= -2.5f && !flag3)
{
                                flag = true;
                                int num6 = (int)item.position.X;
                                num6 = (num6 + 8) / 16;
                                num6 *= 16;
                                item.position.X = (float)num6;
                                velocity.X = 0f;
                                velocity.Y = 0.75f;
                                zero.Y = 2.5f;
                            }
                        }
                        else if (tileContactSide2 == Collision.TileContactSide.BottomLeft && velocity.X >= -0.75f && velocity.X <= 2.5f && !flag3)
{
                            flag = true;
                            Vector2 right = item.Right;
                            int num7 = (int)right.X;
                            num7 = (num7 + 8) / 16;
                            num7 *= 16;
                            right.X = (float)num7;
                            item.Right = right;
                            velocity.X = 0f;
                            velocity.Y = 0.75f;
                            zero.Y = 2.5f;
                        }
                    }
                }
                flag |= flag4 || flag3;
                if (zero.Y < 0f)
                {
                    velocity.Y = Math.Max(velocity.Y + zero.Y * 6f / 60f, zero.Y);
                }
                else if (zero.Y > 0f)
                {
                    velocity.Y = Math.Min(velocity.Y + zero.Y * 6f / 60f, zero.Y);
                }
                if (zero.X < 0f && velocity.X > zero.X)
                {
                    velocity.X = Math.Max(velocity.X + zero.X * 6f / 60f, zero.X);
                }
                if (zero.X > 0f && velocity.X < zero.X)
                {
                    velocity.X = Math.Min(velocity.X + zero.X * 6f / 60f, zero.X);
                }
                if (num != -1 && velocity.X > 0f)
                {
                    int num8 = Collision.contacts[num].X * 16 + Math.Max(16 - item.height / 2, 0);
                    Vector2 right2 = item.Right;
                    if (right2.X + velocity.X > (float)num8)
                    {
                        if (right2.X >= (float)num8)
{
                            right2.X = (float)num8;
                            velocity.X = 0f;
                            item.Right = right2;
                        }
                        else
{
                            velocity.X = (float)num8 - right2.X;
                        }
                    }
                }
                if (num2 != -1 && velocity.X < 0f)
                {
                    int num9 = Collision.contacts[num2].X * 16 + Math.Min(item.height / 2, 16);
                    Vector2 position = item.position;
                    if (position.X + velocity.X < (float)num9)
                    {
                        if (position.X <= (float)num9)
{
                            position.X = (float)num9;
                            velocity.X = 0f;
                            item.position = position;
                        }
                        else
{
                            velocity.X = (float)num9 - position.X;
                        }
                    }
                }
            }
            return flag;
        }
References Terraria.Tile.active(), Terraria.Collision.BuildTileContacts(), Terraria.Collision.contacts, Terraria.ID.TileID.Sets.ConveyorDirection, Terraria.Tile.halfBrick(), int, System.item, System.Math.Max(), System.Math.Min(), Terraria.Tile.slope(), Terraria.Main.tile, Terraria.Tile.type, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.WorldItem.MoveInWorld().