Terraria Decompiled: Terraria.Collision.CheckAABBvLineCollision
CheckAABBvLineCollision() [1/2]
static bool Terraria.Collision.CheckAABBvLineCollision (Vector2 aabbPosition, Vector2 aabbDimensions, Vector2 lineStart, Vector2 lineEnd) inline static
Definition at line 179 of file Collision.cs.
        {
            int num;
            if ((num = Collision.collisionOutcode(aabbPosition, aabbDimensions, lineEnd)) == 0)
            {
                return true;
            }
            int num2;
            while ((num2 = Collision.collisionOutcode(aabbPosition, aabbDimensions, lineStart)) != 0)
            {
                if ((num2 & num) != 0)
                {
                    return false;
                }
                if ((num2 & 5) != 0)
                {
                    float num3 = aabbPosition.X;
                    if ((num2 & 4) != 0)
                    {
                        num3 += aabbDimensions.X;
                    }
                    lineStart.Y += (num3 - lineStart.X) * (lineEnd.Y - lineStart.Y) / (lineEnd.X - lineStart.X);
                    lineStart.X = num3;
                }
                else
                {
                    float num4 = aabbPosition.Y;
                    if ((num2 & 8) != 0)
                    {
                        num4 += aabbDimensions.Y;
                    }
                    lineStart.X += (num4 - lineStart.Y) * (lineEnd.X - lineStart.X) / (lineEnd.Y - lineStart.Y);
                    lineStart.Y = num4;
                }
            }
            return true;
        }
References Terraria.Collision.collisionOutcode(), Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Collision.CheckAABBvLineCollision2(), Terraria.Projectile.Colliding(), and Terraria.GameContent.PortalHelper.TryGoingThroughPortals().