Terraria Decompiled: Terraria.Collision.TryChangingSizeFromBottomCenter
TryChangingSizeFromBottomCenter()
static bool Terraria.Collision.TryChangingSizeFromBottomCenter (Rectangle hitbox, int targetWidth, int targetHeight, out Rectangle changedHitbox) inline static
Definition at line 2558 of file Collision.cs.
        {
            changedHitbox = hitbox;
            int num = targetHeight - hitbox.Height;
            if (num > 0)
            {
                int num2 = (int)Collision.TileCollisionInStepsOf16(changedHitbox.TopLeft(), Vector2.UnitY, (float)num, changedHitbox.Width, changedHitbox.Height);
                int num3 = (int)Collision.TileCollisionInStepsOf16(changedHitbox.TopLeft(), -Vector2.UnitY, (float)num, changedHitbox.Width, changedHitbox.Height);
                if (num3 + num2 < num)
                {
                    return false;
                }
                int num4 = Math.Min(num, num3);
                int num5 = 0;
                int num6 = num - num4 - num5;
                num4 += Math.Min(num6, num3 - num4);
                num6 = num - num4 - num5;
                num5 += Math.Min(num6, num2 - num5);
                changedHitbox.Offset(0, -num4);
                changedHitbox.Height += num4 + num5;
            }
            else
            {
                changedHitbox.Offset(0, -num);
                changedHitbox.Height = targetHeight;
            }
            int num7 = targetWidth - hitbox.Width;
            if (num7 > 0)
            {
                int num8 = (int)Collision.TileCollisionInStepsOf16(changedHitbox.TopLeft(), Vector2.UnitX, (float)num7, changedHitbox.Width, changedHitbox.Height);
                int num9 = (int)Collision.TileCollisionInStepsOf16(changedHitbox.TopLeft(), -Vector2.UnitX, (float)num7, changedHitbox.Width, changedHitbox.Height);
                if (num9 + num8 < num7)
                {
                    return false;
                }
                int num11;
                int num10 = (num11 = Math.Min(num7 / 2, Math.Min(num9, num8)));
                int num12 = num7 - num10 - num11;
                num10 += Math.Min(num12, num9 - num10);
                num12 = num7 - num10 - num11;
                num11 += Math.Min(num12, num8 - num11);
                changedHitbox.Offset(-num10, 0);
                changedHitbox.Width += num10 + num11;
            }
            else
            {
                changedHitbox.Offset(num7 / 2, 0);
                changedHitbox.Width = targetWidth;
            }
            return true;
        }
References Microsoft.Xna.Framework.Rectangle.Height, int, System.Math.Min(), Terraria.Collision.TileCollisionInStepsOf16(), Microsoft.Xna.Framework.Vector2.UnitX, Microsoft.Xna.Framework.Vector2.UnitY, and Microsoft.Xna.Framework.Rectangle.Width.
Referenced by Terraria.Mount.CanDismountWithResult(), Terraria.Mount.Dismount(), Terraria.Projectile.Kill_SpiderBoulder_SpawnSpider(), and Terraria.NPC.TryMoveToTransformableSpaceInto().