Terraria Decompiled: Terraria.Collision.TryFindingConveyorBeltRising
TryFindingConveyorBeltRising()
static bool Terraria.Collision.TryFindingConveyorBeltRising (Entity entity, float gravDir) inline static
Definition at line 4419 of file Collision.cs.
        {
            if (entity is WorldItem)
            {
                Point point = (entity.BottomLeft + new Vector2(-0.5f, -0.01f)).ToTileCoordinates();
                float num = 0f;
                if (WorldGen.InWorld(point, 0))
                {
                    Tile tile = Main.tile[point.X, point.Y];
                    if (tile != null && tile.active() && tile.nactive() && tile.slope() == 0)
                    {
                        int num2 = TileID.Sets.ConveyorDirection[(int)tile.type];
                        num += (float)num2 * gravDir;
                    }
                }
                Point point2 = (entity.BottomRight + new Vector2(0.5f, -0.01f)).ToTileCoordinates();
                if (WorldGen.InWorld(point2, 0))
                {
                    Tile tile2 = Main.tile[point2.X, point2.Y];
                    if (tile2 != null && tile2.active() && tile2.nactive() && tile2.slope() == 0)
                    {
                        int num3 = TileID.Sets.ConveyorDirection[(int)tile2.type];
                        num += (float)num3 * gravDir * -1f;
                    }
                }
                return num < 0f;
            }
            return false;
        }
References Terraria.Tile.active(), Terraria.ID.TileID.Sets.ConveyorDirection, int, Terraria.WorldGen.InWorld(), Terraria.Tile.nactive(), Terraria.Tile.slope(), Terraria.Main.tile, Terraria.Tile.type, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.