Terraria Decompiled: Terraria.Collision.CheckAABBvLineCollision
CheckAABBvLineCollision() [2/2]
static bool Terraria.Collision.CheckAABBvLineCollision (Vector2 objectPosition, Vector2 objectDimensions, Vector2 lineStart, Vector2 lineEnd, float lineWidth, ref float collisionPoint) inline static
Definition at line 225 of file Collision.cs.
        {
            float num = lineWidth * 0.5f;
            Vector2 vector = lineStart;
            Vector2 vector2 = lineEnd - lineStart;
            if (vector2.X > 0f)
            {
                vector2.X += lineWidth;
                vector.X -= num;
            }
            else
            {
                vector.X += vector2.X - num;
                vector2.X = -vector2.X + lineWidth;
            }
            if (vector2.Y > 0f)
            {
                vector2.Y += lineWidth;
                vector.Y -= num;
            }
            else
            {
                vector.Y += vector2.Y - num;
                vector2.Y = -vector2.Y + lineWidth;
            }
            if (!Collision.CheckAABBvAABBCollision(objectPosition, objectDimensions, vector, vector2))
            {
                return false;
            }
            Vector2 vector3 = objectPosition - lineStart;
            Vector2 vector4 = vector3 + objectDimensions;
            Vector2 vector5 = new Vector2(vector3.X, vector4.Y);
            Vector2 vector6 = new Vector2(vector4.X, vector3.Y);
            Vector2 vector7 = lineEnd - lineStart;
            float num2 = vector7.Length();
            float num3 = (float)Math.Atan2((double)vector7.Y, (double)vector7.X);
            Vector2[] array = new Vector2[]
            {
                vector3.RotatedBy((double)(-(double)num3), default(Vector2)),
                vector6.RotatedBy((double)(-(double)num3), default(Vector2)),
                vector4.RotatedBy((double)(-(double)num3), default(Vector2)),
                vector5.RotatedBy((double)(-(double)num3), default(Vector2))
            };
            collisionPoint = num2;
            bool flag = false;
            for (int i = 0; i < array.Length; i++)
            {
                if (Math.Abs(array[i].Y) < num && array[i].X < collisionPoint && array[i].X >= 0f)
                {
                    collisionPoint = array[i].X;
                    flag = true;
                }
            }
            Vector2 vector8 = new Vector2(0f, num);
            Vector2 vector9 = new Vector2(num2, num);
            Vector2 vector10 = new Vector2(0f, -num);
            Vector2 vector11 = new Vector2(num2, -num);
            for (int j = 0; j < array.Length; j++)
            {
                int num4 = (j + 1) % array.Length;
                Vector2 vector12 = vector9 - vector8;
                Vector2 vector13 = array[num4] - array[j];
                float num5 = vector12.X * vector13.Y - vector12.Y * vector13.X;
                if (num5 != 0f)
                {
                    Vector2 vector14 = array[j] - vector8;
                    float num6 = (vector14.X * vector13.Y - vector14.Y * vector13.X) / num5;
                    if (num6 >= 0f && num6 <= 1f)
                    {
                        float num7 = (vector14.X * vector12.Y - vector14.Y * vector12.X) / num5;
                        if (num7 >= 0f && num7 <= 1f)
{
                            flag = true;
                            collisionPoint = Math.Min(collisionPoint, vector8.X + num6 * vector12.X);
                        }
                    }
                }
                vector12 = vector11 - vector10;
                num5 = vector12.X * vector13.Y - vector12.Y * vector13.X;
                if (num5 != 0f)
                {
                    Vector2 vector15 = array[j] - vector10;
                    float num8 = (vector15.X * vector13.Y - vector15.Y * vector13.X) / num5;
                    if (num8 >= 0f && num8 <= 1f)
                    {
                        float num9 = (vector15.X * vector12.Y - vector15.Y * vector12.X) / num5;
                        if (num9 >= 0f && num9 <= 1f)
{
                            flag = true;
                            collisionPoint = Math.Min(collisionPoint, vector10.X + num8 * vector12.X);
                        }
                    }
                }
            }
            return flag;
        }
References System.Math.Abs(), System.array, System.Math.Atan2(), Terraria.Collision.CheckAABBvAABBCollision(), Microsoft.Xna.Framework.Vector2.Length(), System.Math.Min(), Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.