Terraria Decompiled: Terraria.Collision.HitWallSubstep
HitWallSubstep()
static bool Terraria.Collision.HitWallSubstep (int x, int y) inline static
Definition at line 1402 of file Collision.cs.
        {
            if (Main.tile[x, y].wall == 0)
            {
                return false;
            }
            bool flag = false;
            if (Main.wallHouse[(int)Main.tile[x, y].wall])
            {
                flag = true;
            }
            if (!flag)
            {
                for (int i = -1; i < 2; i++)
                {
                    for (int j = -1; j < 2; j++)
                    {
                        if ((i != 0 || j != 0) && Main.tile[x + i, y + j].wall == 0)
{
                            flag = true;
                        }
                    }
                }
            }
            if (Main.tile[x, y].active() && flag)
            {
                bool flag2 = true;
                for (int k = -1; k < 2; k++)
                {
                    for (int l = -1; l < 2; l++)
                    {
                        if (k != 0 || l != 0)
{
                            Tile tile = Main.tile[x + k, y + l];
                            if (!tile.active() || !Main.tileSolid[(int)tile.type] || Main.tileSolidTop[(int)tile.type])
{
                                flag2 = false;
                            }
                        }
                    }
                }
                if (flag2)
                {
                    flag = false;
                }
            }
            return flag;
        }
References Terraria.Tile.active(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Tile.type, Terraria.Tile.wall, and Terraria.Main.wallHouse.
Referenced by Terraria.Collision.HitLineWall(), and Terraria.GameContent.SmartCursorHelper.Step_Hammers().