Terraria Decompiled: Terraria.Collision.WalkDownSlope
WalkDownSlope()
static Vector4 Terraria.Collision.WalkDownSlope (Vector2 Position, Vector2 Velocity, int Width, int Height, float gravity = 0f) inline static
Definition at line 1779 of file Collision.cs.
        {
            if (Velocity.Y != gravity)
            {
                return new Vector4(Position, Velocity.X, Velocity.Y);
            }
            int num = (int)(Position.X / 16f);
            int num2 = (int)((Position.X + (float)Width) / 16f);
            int num3 = (int)((Position.Y + (float)Height + 4f) / 16f);
            num = Utils.Clamp<int>(num, 0, Main.maxTilesX - 1);
            num2 = Utils.Clamp<int>(num2, 0, Main.maxTilesX - 1);
            num3 = Utils.Clamp<int>(num3, 0, Main.maxTilesY - 2 - 40);
            float num4 = (float)((num3 + 3) * 16);
            int num5 = -1;
            int num6 = -1;
            int num7 = 1;
            if (Velocity.X < 0f)
            {
                num7 = 2;
            }
            for (int i = num; i <= num2; i++)
            {
                for (int j = num3; j <= num3 + 1; j++)
                {
                    if (Main.tile[i, j] == null)
                    {
                        Main.tile[i, j] = new Tile();
                    }
                    if (Main.tile[i, j].nactive() && (Main.tileSolid[(int)Main.tile[i, j].type] || Main.tileSolidTop[(int)Main.tile[i, j].type]))
                    {
                        int num8 = j * 16;
                        if (Main.tile[i, j].halfBrick())
{
                            num8 += 8;
                        }
                        Rectangle rectangle = new Rectangle(i * 16, j * 16 - 17, 16, 16);
                        if (rectangle.Intersects(new Rectangle((int)Position.X, (int)Position.Y, Width, Height)) && (float)num8 <= num4)
{
                            if (num4 == (float)num8)
{
                                if (Main.tile[i, j].slope() != 0)
{
                                    if (num5 != -1 && num6 != -1 && Main.tile[num5, num6] != null && Main.tile[num5, num6].slope() != 0)
{
                                        if ((int)Main.tile[i, j].slope() == num7)
{
                                            num4 = (float)num8;
                                            num5 = i;
                                            num6 = j;
                                        }
                                    }
                                    else
{
                                        num4 = (float)num8;
                                        num5 = i;
                                        num6 = j;
                                    }
                                }
                            }
                            else
{
                                num4 = (float)num8;
                                num5 = i;
                                num6 = j;
                            }
                        }
                    }
                }
            }
            int num9 = num5;
            int num10 = num6;
            if (num5 != -1 && num6 != -1 && Main.tile[num9, num10] != null && Main.tile[num9, num10].slope() > 0)
            {
                int num11 = (int)Main.tile[num9, num10].slope();
                Vector2 vector;
                vector.X = (float)(num9 * 16);
                vector.Y = (float)(num10 * 16);
                if (num11 == 2)
                {
                    float num12 = vector.X + 16f - (Position.X + (float)Width);
                    if (Position.Y + (float)Height >= vector.Y + num12 && Velocity.X < 0f)
                    {
                        Velocity.Y += Math.Abs(Velocity.X);
                    }
                }
                else if (num11 == 1)
                {
                    float num12 = Position.X - vector.X;
                    if (Position.Y + (float)Height >= vector.Y + num12 && Velocity.X > 0f)
                    {
                        Velocity.Y += Math.Abs(Velocity.X);
                    }
                }
            }
            return new Vector4(Position, Velocity.X, Velocity.Y);
        }
References System.Math.Abs(), Terraria.Utils.Clamp(), Terraria.Tile.halfBrick(), int, Microsoft.Xna.Framework.Rectangle.Intersects(), Terraria.Tile.nactive(), Terraria.Tile.slope(), Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Tile.type, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Projectile.AI_205_RemoteControlCar(), Terraria.NPC.Collision_WalkDownSlopes(), and Terraria.Player.SlopeDownMovement().