Terraria Decompiled: Terraria.Collision.GetTileRotation
GetTileRotation()
static float Terraria.Collision.GetTileRotation (Vector2 position) inline static
Definition at line 3861 of file Collision.cs.
        {
            float num = position.Y % 16f;
            int num2 = (int)(position.X / 16f);
            int num3 = (int)(position.Y / 16f);
            Tile tile = Main.tile[num2, num3];
            if (tile == null)
            {
                return 0f;
            }
            bool flag = false;
            for (int i = 2; i >= 0; i--)
            {
                if (tile.active())
                {
                    if (Main.tileSolid[(int)tile.type])
                    {
                        int num4 = tile.blockType();
                        if (tile.type == 19)
{
                            int num5 = (int)(tile.frameX / 18);
                            if (((num5 >= 0 && num5 <= 7) || (num5 >= 12 && num5 <= 16)) && (num == 0f || flag))
{
                                return 0f;
                            }
                            switch (num5)
{
                            case 8:
                            case 19:
                            case 21:
                            case 23:
                                return -0.7853982f;
                            case 10:
                            case 20:
                            case 22:
                            case 24:
                                return 0.7853982f;
                            case 25:
                            case 26:
                                if (flag)
{
                                    return 0f;
                                }
                                if (num4 == 2)
{
                                    return 0.7853982f;
                                }
                                if (num4 == 3)
{
                                    return -0.7853982f;
                                }
                                break;
                            }
                        }
                        else
{
                            if (num4 == 1)
{
                                return 0f;
                            }
                            if (num4 == 2)
{
                                return 0.7853982f;
                            }
                            if (num4 == 3)
{
                                return -0.7853982f;
                            }
                            return 0f;
                        }
                    }
                    else if (Main.tileSolidTop[(int)tile.type] && tile.frameY == 0 && flag)
                    {
                        return 0f;
                    }
                }
                num3++;
                if (num3 >= Main.maxTilesY)
                {
                    return 0f;
                }
                tile = Main.tile[num2, num3];
                if (tile == null)
                {
                    return 0f;
                }
                flag = true;
            }
            return 0f;
        }
References Terraria.Tile.active(), Terraria.Tile.blockType(), Terraria.Tile.frameX, int, Terraria.Main.maxTilesY, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Tile.type, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Mount.UpdateFrame().