Terraria Decompiled: Terraria.Collision.LaserScan
LaserScan()
static void Terraria.Collision.LaserScan (Vector2 samplingPoint, Vector2 directionUnit, float samplingWidth, float maxDistance, float[] samples) inline static
Definition at line 4638 of file Collision.cs.
        {
            for (int i = 0; i < samples.Length; i++)
            {
                float num = (float)i / (float)(samples.Length - 1);
                Vector2 vector = samplingPoint + directionUnit.RotatedBy(1.5707963705062866, default(Vector2)) * (num - 0.5f) * samplingWidth;
                int num2 = (int)vector.X / 16;
                int num3 = (int)vector.Y / 16;
                Vector2 vector2 = vector + directionUnit * maxDistance;
                int num4 = (int)vector2.X / 16;
                int num5 = (int)vector2.Y / 16;
                Point point;
                float num6;
                if (!Collision.HitLine(num2, num3, num4, num5, 0, 0, new List<Point>(), out point))
                {
                    num6 = new Vector2((float)Math.Abs(num2 - point.X), (float)Math.Abs(num3 - point.Y)).Length() * 16f;
                }
                else if (point.X == num4 && point.Y == num5)
                {
                    num6 = maxDistance;
                }
                else
                {
                    num6 = new Vector2((float)Math.Abs(num2 - point.X), (float)Math.Abs(num3 - point.Y)).Length() * 16f;
                }
                samples[i] = num6;
            }
        }
References System.Math.Abs(), Terraria.Collision.HitLine(), int, Microsoft.Xna.Framework.Vector2.Length(), Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Point.Y, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Projectile.AI(), and Terraria.Collision.AimingLaserScan().