Terraria Decompiled: Terraria.Collision.TileCollision
TileCollision()
static Vector2 Terraria.Collision.TileCollision (Vector2 Position, Vector2 Velocity, int Width, int Height, bool fallThrough = false, bool fall2 = false, int gravDir = 1, bool ignoreDoors = false, bool ignoreAetheriumPlatforms = false, bool hoik = true) inline static
Definition at line 2366 of file Collision.cs.
        {
            Collision.up = false;
            Collision.down = false;
            Vector2 vector = Velocity;
            Vector2 vector2 = Position + Velocity;
            int num = (int)(Position.X / 16f) - 1;
            int num2 = (int)((Position.X + (float)Width) / 16f) + 2;
            int num3 = (int)(Position.Y / 16f) - 1;
            int num4 = (int)((Position.Y + (float)Height) / 16f) + 2;
            int num5 = -1;
            int num6 = -1;
            int num7 = -1;
            int num8 = -1;
            int num9 = Utils.Clamp<int>(num, 0, Main.maxTilesX - 1);
            num2 = Utils.Clamp<int>(num2, 0, Main.maxTilesX - 1);
            num3 = Utils.Clamp<int>(num3, 0, Main.maxTilesY - 40);
            num4 = Utils.Clamp<int>(num4, 0, Main.maxTilesY - 40);
            float num10 = (float)((num4 + 3) * 16);
            for (int i = num9; i < num2; i++)
            {
                for (int j = num3; j < num4; j++)
                {
                    Tile tile = Main.tile[i, j];
                    if (tile != null && tile.active() && !tile.inActive())
                    {
                        bool flag = Main.tileSolid[(int)tile.type];
                        if (Main.tileSolidTop[(int)tile.type] && tile.frameY == 0)
{
                            flag = true;
                        }
                        if (ignoreDoors && TileID.Sets.ForAdvancedCollision.ClosedDoors[(int)tile.type])
{
                            flag = false;
                        }
                        if (ignoreAetheriumPlatforms && tile.type == 19 && tile.frameY / 18 == 50)
{
                            flag = false;
                        }
                        if (flag)
{
                            Vector2 vector3;
                            vector3.X = (float)(i * 16);
                            vector3.Y = (float)(j * 16);
                            int num11 = 16;
                            if (Main.tile[i, j].halfBrick())
{
                                vector3.Y += 8f;
                                num11 -= 8;
                            }
                            if (vector2.X + (float)Width > vector3.X && vector2.X < vector3.X + 16f && vector2.Y + (float)Height > vector3.Y && vector2.Y < vector3.Y + (float)num11)
{
                                bool flag2 = false;
                                bool flag3 = false;
                                if (Main.tile[i, j].slope() > 2)
{
                                    if (Main.tile[i, j].slope() == 3 && Position.Y + Math.Abs(Velocity.X) >= vector3.Y && Position.X >= vector3.X)
{
                                        flag3 = true;
                                    }
                                    if (Main.tile[i, j].slope() == 4 && Position.Y + Math.Abs(Velocity.X) >= vector3.Y && Position.X + (float)Width <= vector3.X + 16f)
{
                                        flag3 = true;
                                    }
                                }
                                else if (Main.tile[i, j].slope() > 0)
{
                                    flag2 = true;
                                    if (Main.tile[i, j].slope() == 1 && Position.Y + (float)Height - Math.Abs(Velocity.X) <= vector3.Y + (float)num11 && Position.X >= vector3.X)
{
                                        flag3 = true;
                                    }
                                    if (Main.tile[i, j].slope() == 2 && Position.Y + (float)Height - Math.Abs(Velocity.X) <= vector3.Y + (float)num11 && Position.X + (float)Width <= vector3.X + 16f)
{
                                        flag3 = true;
                                    }
                                }
                                if (!flag3)
{
                                    if (Position.Y + (float)Height <= vector3.Y)
{
                                        Collision.down = true;
                                        if ((!Main.tileSolidTop[(int)Main.tile[i, j].type] || !fallThrough || (Velocity.Y > 1f && !fall2)) && num10 > vector3.Y)
{
                                            num7 = i;
                                            num8 = j;
                                            if (num11 < 16)
{
                                                num8++;
                                            }
                                            if (num7 != num5 && !flag2)
{
                                                vector.Y = vector3.Y - (Position.Y + (float)Height) + ((gravDir == -1) ? (-0.01f) : 0f);
                                                num10 = vector3.Y;
                                            }
                                        }
                                    }
                                    else if (Position.X + (float)Width <= vector3.X && !Main.tileSolidTop[(int)Main.tile[i, j].type])
{
                                        if (i >= 1 && Main.tile[i - 1, j] == null)
{
                                            Main.tile[i - 1, j] = new Tile();
                                        }
                                        if (!hoik || i < 1 || (Main.tile[i - 1, j].slope() != 2 && Main.tile[i - 1, j].slope() != 4))
{
                                            num5 = i;
                                            num6 = j;
                                            if (num6 != num8)
{
                                                vector.X = vector3.X - (Position.X + (float)Width);
                                            }
                                            if (num7 == num5)
{
                                                vector.Y = Velocity.Y;
                                            }
                                        }
                                    }
                                    else if (Position.X >= vector3.X + 16f && !Main.tileSolidTop[(int)Main.tile[i, j].type])
{
                                        if (Main.tile[i + 1, j] == null)
{
                                            Main.tile[i + 1, j] = new Tile();
                                        }
                                        if (!hoik || (Main.tile[i + 1, j].slope() != 1 && Main.tile[i + 1, j].slope() != 3))
{
                                            num5 = i;
                                            num6 = j;
                                            if (num6 != num8)
{
                                                vector.X = vector3.X + 16f - Position.X;
                                            }
                                            if (num7 == num5)
{
                                                vector.Y = Velocity.Y;
                                            }
                                        }
                                    }
                                    else if (Position.Y >= vector3.Y + (float)num11 && !Main.tileSolidTop[(int)Main.tile[i, j].type])
{
                                        Collision.up = true;
                                        num7 = i;
                                        num8 = j;
                                        vector.Y = vector3.Y + (float)num11 - Position.Y + ((gravDir == 1) ? 0.01f : 0f);
                                        if (num8 == num6)
{
                                            vector.X = Velocity.X;
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            return vector;
        }
References System.Math.Abs(), Terraria.Tile.active(), Terraria.Utils.Clamp(), Terraria.ID.TileID.Sets.ForAdvancedCollision.ClosedDoors, Terraria.Tile.frameY, Terraria.Tile.halfBrick(), Terraria.Tile.inActive(), int, Terraria.Tile.slope(), Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Tile.type, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Projectile.AI(), Terraria.Projectile.AI_067_FreakingPirates(), Terraria.Projectile.AI_195_JimsDrone(), Terraria.Projectile.AI_205_RemoteControlCar(), Terraria.Utils.CheckForGoodTeleportationSpot(), Terraria.NPC.Collision_MoveNormal(), Terraria.NPC.Collision_MoveSolarSroller(), Terraria.NPC.Collision_MoveStardustCell(), Terraria.Collision.FindCollisionDirection(), Terraria.Collision.FindCollisionTile(), Terraria.Gore.Gore_UpdateLeaf(), Terraria.Gore.Gore_UpdateSail(), Terraria.Projectile.HandleMovement(), Terraria.Mount.Hover(), Terraria.Collision.IsClearSpotTest(), Terraria.GameContent.TeleportHelpers.IsInSolidTilesExtended(), Terraria.WorldItem.MoveInWorld(), Terraria.Collision.SlopeCollision(), Terraria.Collision.StepConveyorBelt(), Terraria.Player.TileCollision(), Terraria.Collision.TileCollisionInStepsOf16(), Terraria.Mount.TryBeginningFlight(), Terraria.GameContent.PortalHelper.TryGoingThroughPortals(), Terraria.Mount.TryLanding(), and Terraria.Gore.Update().