Terraria Decompiled: Terraria.Collision.SwitchTiles
SwitchTiles()
static bool Terraria.Collision.SwitchTiles (Entity entity, Vector2 Position, int Width, int Height, Vector2 oldPosition, int objType) inline static
Definition at line 3299 of file Collision.cs.
        {
            int num = (int)(Position.X / 16f) - 1;
            int num2 = (int)((Position.X + (float)Width) / 16f) + 2;
            int num3 = (int)(Position.Y / 16f) - 1;
            int num4 = (int)((Position.Y + (float)Height) / 16f) + 2;
            if (num < 0)
            {
                num = 0;
            }
            if (num2 > Main.maxTilesX)
            {
                num2 = Main.maxTilesX;
            }
            if (num3 < 0)
            {
                num3 = 0;
            }
            if (num4 > Main.maxTilesY - 40)
            {
                num4 = Main.maxTilesY - 40;
            }
            for (int i = num; i < num2; i++)
            {
                for (int j = num3; j < num4; j++)
                {
                    if (Main.tile[i, j] != null)
                    {
                        int type = (int)Main.tile[i, j].type;
                        if (Main.tile[i, j].active() && (type == 135 || type == 210 || type == 443 || type == 442))
{
                            Vector2 vector;
                            vector.X = (float)(i * 16);
                            vector.Y = (float)(j * 16 + 12);
                            bool flag = false;
                            if (type == 442)
{
                                if (objType == 4)
{
                                    float num5 = 0f;
                                    float num6 = 0f;
                                    float num7 = 0f;
                                    float num8 = 0f;
                                    switch (Main.tile[i, j].frameX / 22)
{
                                    case 0:
                                        num5 = (float)(i * 16);
                                        num6 = (float)(j * 16 + 16 - 10);
                                        num7 = 16f;
                                        num8 = 10f;
                                        break;
                                    case 1:
                                        num5 = (float)(i * 16);
                                        num6 = (float)(j * 16);
                                        num7 = 16f;
                                        num8 = 10f;
                                        break;
                                    case 2:
                                        num5 = (float)(i * 16);
                                        num6 = (float)(j * 16);
                                        num7 = 10f;
                                        num8 = 16f;
                                        break;
                                    case 3:
                                        num5 = (float)(i * 16 + 16 - 10);
                                        num6 = (float)(j * 16);
                                        num7 = 10f;
                                        num8 = 16f;
                                        break;
                                    }
                                    if (Utils.FloatIntersect(num5, num6, num7, num8, Position.X, Position.Y, (float)Width, (float)Height) && !Utils.FloatIntersect(num5, num6, num7, num8, oldPosition.X, oldPosition.Y, (float)Width, (float)Height))
{
                                        Wiring.HitSwitch(i, j);
                                        NetMessage.SendData(59, -1, -1, null, i, (float)j, 0f, 0f, 0, 0, 0);
                                        return true;
                                    }
                                }
                                flag = true;
                            }
                            if (!flag && Position.X + (float)Width > vector.X && Position.X < vector.X + 16f && Position.Y + (float)Height > vector.Y && (double)Position.Y < (double)vector.Y + 4.01 && (oldPosition.X + (float)Width <= vector.X || oldPosition.X >= vector.X + 16f || oldPosition.Y + (float)Height <= vector.Y || (double)oldPosition.Y >= (double)vector.Y + 16.01))
{
                                if (type == 210)
{
                                    Wiring.HitSwitch(i, j);
                                    NetMessage.SendData(59, -1, -1, null, i, (float)j, 0f, 0f, 0, 0, 0);
                                }
                                else if (type == 443)
{
                                    if (objType == 1 || objType == 5)
{
                                        Wiring.HitSwitch(i, j);
                                        NetMessage.SendData(59, -1, -1, null, i, (float)j, 0f, 0f, 0, 0, 0);
                                    }
                                }
                                else
{
                                    int num9 = (int)(Main.tile[i, j].frameY / 18);
                                    bool flag2 = true;
                                    if ((num9 == 4 || num9 == 2 || num9 == 3 || num9 == 6 || num9 == 7) && objType != 5)
{
                                        flag2 = false;
                                    }
                                    if (num9 == 5 && (objType == 1 || objType == 4 || objType == 5))
{
                                        flag2 = false;
                                    }
                                    if (flag2)
{
                                        if (Main.netMode == 1 && objType == 5)
{
                                            NetMessage.SendData(13, -1, -1, null, Main.myPlayer, 0f, 0f, 0f, 0, 0, 0);
                                        }
                                        Wiring.HitSwitch(i, j);
                                        NetMessage.SendData(59, -1, -1, null, i, (float)j, 0f, 0f, 0, 0, 0);
                                        if (num9 == 7)
{
                                            WorldGen.KillTile(i, j, false, false, false);
                                            if (Main.netMode == 1)
{
                                                NetMessage.SendData(17, -1, -1, null, 0, (float)i, (float)j, 0f, 0, 0, 0);
                                            }
                                        }
                                        return true;
                                    }
                                }
                            }
                        }
                    }
                }
            }
            return false;
        }
References Terraria.Tile.active(), Terraria.Utils.FloatIntersect(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Wiring.HitSwitch(), int, Terraria.WorldGen.KillTile(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.NetMessage.SendData(), Terraria.Main.tile, Terraria.Tile.type, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Projectile.AI_149_GolfBall(), Terraria.Projectile.HandleMovement(), Terraria.Projectile.Update(), and Terraria.NPC.UpdateNPC().