Terraria Decompiled: Terraria.Collision.HurtTiles
HurtTiles()
static Collision.HurtTile Terraria.Collision.HurtTiles (Vector2 Position, int Width, int Height, Player player) inline static
Definition at line 3202 of file Collision.cs.
        {
            int num = (int)(Position.X / 16f) - 1;
            int num2 = (int)((Position.X + (float)Width) / 16f) + 2;
            int num3 = (int)(Position.Y / 16f) - 1;
            int num4 = (int)((Position.Y + (float)Height) / 16f) + 2;
            if (num < 0)
            {
                num = 0;
            }
            if (num2 > Main.maxTilesX)
            {
                num2 = Main.maxTilesX;
            }
            if (num3 < 0)
            {
                num3 = 0;
            }
            if (num4 > Main.maxTilesY - 40)
            {
                num4 = Main.maxTilesY - 40;
            }
            for (int i = num; i < num2; i++)
            {
                for (int j = num3; j < num4; j++)
                {
                    Tile tile = Main.tile[i, j];
                    if (tile != null && !tile.inActive() && tile.active())
                    {
                        Vector2 vector;
                        vector.X = (float)(i * 16);
                        vector.Y = (float)(j * 16);
                        int num5 = 16;
                        if (tile.halfBrick())
{
                            vector.Y += 8f;
                            num5 -= 8;
                        }
                        int num6 = 0;
                        if (TileID.Sets.Suffocate[(int)tile.type])
{
                            num6 = 2;
                        }
                        if (Position.X + (float)Width - (float)num6 >= vector.X && Position.X + (float)num6 <= vector.X + 16f && Position.Y + (float)Height - (float)num6 >= vector.Y - 0.5f && Position.Y + (float)num6 <= vector.Y + (float)num5 + 0.5f && Collision.CanTileHurt(tile.type, i, j, player))
{
                            if (tile.slope() > 0)
{
                                if (num6 > 0)
{
                                    goto IL_025F;
                                }
                                int num7 = 0;
                                if (tile.rightSlope() && Position.X > vector.X)
{
                                    num7++;
                                }
                                if (tile.leftSlope() && Position.X + (float)Width < vector.X + 16f)
{
                                    num7++;
                                }
                                if (tile.bottomSlope() && Position.Y > vector.Y)
{
                                    num7++;
                                }
                                if (tile.topSlope() && Position.Y + (float)Height < vector.Y + (float)num5)
{
                                    num7++;
                                }
                                if (num7 == 2)
{
                                    goto IL_025F;
                                }
                            }
                            return new Collision.HurtTile
{
                                type = (int)tile.type,
                                x = i,
                                y = j
                            };
                        }
                    }
                    IL_025F:;
                }
            }
            return new Collision.HurtTile
            {
                type = -1
            };
        }
References Terraria.Tile.active(), Terraria.Tile.bottomSlope(), Terraria.Collision.CanTileHurt(), Terraria.Tile.halfBrick(), Terraria.Tile.inActive(), int, Terraria.Tile.leftSlope(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Tile.rightSlope(), Terraria.Tile.slope(), Terraria.ID.TileID.Sets.Suffocate, Terraria.Main.tile, Terraria.Tile.topSlope(), Terraria.Tile.type, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Collision.AnyHurtingTiles(), and Terraria.Player.GetHurtTile().