Terraria Decompiled: System.Runtime.Remoting.Contexts.CrossContextChannel.ContextRestoreSink.SyncProcessMessage
SyncProcessMessage()
IMessage System.Runtime.Remoting.Contexts.CrossContextChannel.ContextRestoreSink.SyncProcessMessage (IMessage msg) inline
Implements System.Runtime.Remoting.Messaging.IMessageSink.
Definition at line 113 of file CrossContextChannel.cs.
            {
                IMessage message;
                try
                {
                    Context.NotifyGlobalDynamicSinks(false, msg, false, false);
                    Thread.CurrentContext.NotifyDynamicSinks(false, msg, false, false);
                    message = this._next.SyncProcessMessage(msg);
                }
                catch (Exception ex)
                {
                    message = new ReturnMessage(ex, (IMethodCallMessage)this._call);
                }
                finally
                {
                    if (this._context != null)
                    {
                        Context.SwitchToContext(this._context);
                    }
                }
                return message;
            }
References System.Runtime.Remoting.Contexts.CrossContextChannel.ContextRestoreSink._call, System.Runtime.Remoting.Contexts.CrossContextChannel.ContextRestoreSink._context, System.Runtime.Remoting.Contexts.CrossContextChannel.ContextRestoreSink._next, System.Threading.Thread.CurrentContext, System.Runtime.Remoting.Contexts.Context.NotifyGlobalDynamicSinks(), System.Runtime.Remoting.Contexts.Context.SwitchToContext(), and System.Runtime.Remoting.Messaging.IMessageSink.SyncProcessMessage().