Terraria Decompiled: FullSerializer.Internal.fsEnumConverter.TrySerialize
TrySerialize()
override fsResult FullSerializer.Internal.fsEnumConverter.TrySerialize (object instance, out fsData serialized, Type storageType) inline
Definition at line 35 of file fsEnumConverter.cs.
        {
            if (this.Serializer.Config.SerializeEnumsAsInteger)
            {
                serialized = new fsData(Convert.ToInt64(instance));
            }
            else if (fsPortableReflection.GetAttribute<FlagsAttribute>(storageType) != null)
            {
                long num = Convert.ToInt64(instance);
                StringBuilder stringBuilder = new StringBuilder();
                bool flag = true;
                foreach (object obj in Enum.GetValues(storageType))
                {
                    long num2 = Convert.ToInt64(obj);
                    if ((num & num2) != 0L)
                    {
                        if (!flag)
{
                            stringBuilder.Append(",");
                        }
                        flag = false;
                        stringBuilder.Append(obj.ToString());
                    }
                }
                serialized = new fsData(stringBuilder.ToString());
            }
            else
            {
                serialized = new fsData(Enum.GetName(storageType, instance));
            }
            return fsResult.Success;
        }
References FullSerializer.fsSerializer.Config, FullSerializer.Internal.fsPortableReflection.GetAttribute(), System.Enum.GetName(), System.Enum.GetValues(), System.L, System.obj, FullSerializer.fsConfig.SerializeEnumsAsInteger, FullSerializer.fsBaseConverter.Serializer, FullSerializer.fsResult.Success, and System.Convert.ToInt64().