Terraria Decompiled: Terraria.UI.UserInterface.ResetState
ResetState()
void Terraria.UI.UserInterface.ResetState () inline private
Definition at line 117 of file UserInterface.cs.
        {
            if (!Main.dedServ)
            {
                this.GetMousePosition();
                this.ImmediatelyUpdateInputPointers();
                if (this._lastElementHover != null)
                {
                    this._lastElementHover.MouseOut(new UIMouseEvent(this._lastElementHover, this.MousePosition));
                }
            }
            this.ClearPointers();
            this._lastElementHover = null;
            this._clickDisabledTimeRemaining = Math.Max(this._clickDisabledTimeRemaining, 200.0);
        }
References Terraria.UI.UserInterface._clickDisabledTimeRemaining, Terraria.UI.UserInterface._lastElementHover, Terraria.UI.UserInterface.ClearPointers(), Terraria.Main.dedServ, Terraria.UI.UserInterface.GetMousePosition(), Terraria.UI.UserInterface.ImmediatelyUpdateInputPointers(), System.Math.Max(), Terraria.UI.UIElement.MouseOut(), and Terraria.UI.UserInterface.MousePosition.
Referenced by Terraria.UI.UserInterface.RefreshState(), and Terraria.UI.UserInterface.SetState().