Terraria Decompiled: Terraria.UI.UserInterface.Update
Update()
void Terraria.UI.UserInterface.Update (GameTime time) inline
Definition at line 140 of file UserInterface.cs.
        {
            if (this._currentState == null)
            {
                return;
            }
            bool flag = FocusHelper.AllowUIInputs;
            if (!Main.gameMenu && PlayerInput.IgnoreMouseInterface)
            {
                flag = false;
            }
            this.GetMousePosition();
            UIElement uielement = (flag ? this._currentState.GetElementAt(this.MousePosition) : null);
            this._clickDisabledTimeRemaining = Math.Max(0.0, this._clickDisabledTimeRemaining - time.ElapsedGameTime.TotalMilliseconds);
            bool flag2 = this._clickDisabledTimeRemaining > 0.0;
            if (uielement != this._lastElementHover)
            {
                if (this._lastElementHover != null)
                {
                    this._lastElementHover.MouseOut(new UIMouseEvent(this._lastElementHover, this.MousePosition));
                }
                if (uielement != null)
                {
                    uielement.MouseOver(new UIMouseEvent(uielement, this.MousePosition));
                }
                this._lastElementHover = uielement;
            }
            if (!flag2)
            {
                this.HandleClick(this.LeftMouse, time, Main.mouseLeft && flag, uielement);
                this.HandleClick(this.RightMouse, time, Main.mouseRight && flag, uielement);
            }
            if (PlayerInput.ScrollWheelDeltaForUI != 0)
            {
                if (uielement != null)
                {
                    uielement.ScrollWheel(new UIScrollWheelEvent(uielement, this.MousePosition, PlayerInput.ScrollWheelDeltaForUI));
                }
                PlayerInput.ScrollWheelDeltaForUI = 0;
            }
            if (this._currentState != null)
            {
                this._currentState.Update(time);
            }
        }
References Terraria.UI.UserInterface._clickDisabledTimeRemaining, Terraria.UI.UserInterface._currentState, Terraria.UI.UserInterface._lastElementHover, Terraria.FocusHelper.AllowUIInputs, Microsoft.Xna.Framework.GameTime.ElapsedGameTime, Terraria.Main.gameMenu, Terraria.UI.UIElement.GetElementAt(), Terraria.UI.UserInterface.GetMousePosition(), Terraria.UI.UserInterface.HandleClick(), Terraria.GameInput.PlayerInput.IgnoreMouseInterface, Terraria.UI.UserInterface.LeftMouse, System.Math.Max(), Terraria.Main.mouseLeft, Terraria.UI.UIElement.MouseOut(), Terraria.UI.UIElement.MouseOver(), Terraria.UI.UserInterface.MousePosition, Terraria.Main.mouseRight, Terraria.UI.UserInterface.RightMouse, Terraria.UI.UIElement.ScrollWheel(), Terraria.GameInput.PlayerInput.ScrollWheelDeltaForUI, System.TimeSpan.TotalMilliseconds, and Terraria.UI.UIElement.Update().
Referenced by Terraria.GameContent.Creative.CreativeUI.Update(), Terraria.GameContent.UI.NewCraftingUI.UpdateUI(), and Terraria.Main.UpdateUIStates().