Terraria Decompiled: Terraria.UI.UserInterface.Draw
Draw()
void Terraria.UI.UserInterface.Draw (SpriteBatch spriteBatch, GameTime time) inline
Definition at line 215 of file UserInterface.cs.
        {
            this.Use();
            if (this._currentState != null)
            {
                if (this._isStateDirty)
                {
                    this._currentState.Recalculate();
                    this._isStateDirty = false;
                }
                this._currentState.Draw(spriteBatch);
            }
        }
References Terraria.UI.UserInterface._currentState, Terraria.UI.UserInterface._isStateDirty, Terraria.UI.UIElement.Draw(), Terraria.UI.UIElement.Recalculate(), and Terraria.UI.UserInterface.Use().
Referenced by Terraria.GameContent.Creative.CreativeUI.Draw(), Terraria.GameContent.UI.States.UICharacterSelect.Draw(), Terraria.GameContent.UI.States.UIWorldSelect.Draw(), Terraria.Main.DrawInterface_12_IngameFancyUI(), Terraria.Main.DrawMenu(), and Terraria.GameContent.UI.NewCraftingUI.DrawUI().