Terraria Decompiled: Terraria.UI.UserInterface.SetState
SetState()
void Terraria.UI.UserInterface.SetState (UIState state) inline
Definition at line 236 of file UserInterface.cs.
        {
            if (state == this._currentState)
            {
                return;
            }
            if (state != null)
            {
                this.AddToHistory(state);
            }
            if (this._currentState != null)
            {
                if (this._lastElementHover != null)
                {
                    this._lastElementHover.MouseOut(new UIMouseEvent(this._lastElementHover, this.MousePosition));
                }
                this._currentState.Deactivate();
            }
            this._currentState = state;
            this.ResetState();
            if (state != null)
            {
                this._isStateDirty = true;
                state.Activate();
                state.Recalculate();
            }
            this.IsVisible = this._currentState != null;
        }
References Terraria.UI.UserInterface._currentState, Terraria.UI.UserInterface._lastElementHover, Terraria.UI.UserInterface.AddToHistory(), Terraria.UI.UIElement.Deactivate(), Terraria.UI.UIElement.MouseOut(), Terraria.UI.UserInterface.MousePosition, Terraria.UI.UserInterface.ResetState(), and System.state.
Referenced by Terraria.GameContent.UI.States.UIWorldGenDebug.b__38_35(), Terraria.GameContent.UI.States.UIDebugCommandsList.b__4_0(), Terraria.GameContent.UI.States.UIDebugCommandsList.BuildPage(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.Click_Info(), Terraria.GameContent.UI.States.UICharacterCreation.Click_Naming(), Terraria.GameContent.UI.States.UICharacterCreation.Click_NamingAndCreating(), Terraria.GameContent.UI.States.UIWorldCreation.Click_NamingAndCreating(), Terraria.GameContent.UI.States.UIWorkshopHub.Click_OpenResourcePackPublishMenu(), Terraria.GameContent.UI.States.UIWorkshopHub.Click_OpenWorldImportMenu(), Terraria.GameContent.UI.States.UIWorkshopHub.Click_OpenWorldPublishMenu(), Terraria.GameContent.UI.States.UIWorldCreation.Click_SetName(), Terraria.GameContent.UI.States.UIWorldCreation.ClickAdvancedSeedMenu(), Terraria.GameContent.UI.States.UIWorldGenDebug.Close(), Terraria.GameContent.UI.NewCraftingUI.Close(), Terraria.WorldGen.CreateNewWorld(), Terraria.Main.DoUpdate(), Terraria.Main.DrawMenu(), Terraria.GameContent.UI.States.UIWorldCreationAdvanced.GoBack(), Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.GoBack(), Terraria.UI.UserInterface.GoBack(), Terraria.GameContent.UI.States.UIReportsPage.GoBackClick(), Terraria.GameContent.UI.States.UIResourcePackInfoMenu.GoBackClick(), Terraria.GameContent.UI.States.UIBestiaryTest.GoBackFromVirtualKeyboard(), Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem.GoBackHere(), Terraria.GameContent.UI.States.UIWorldCreation.GoBackHere(), Terraria.GameContent.UI.States.WorkshopPublishInfoStateForResourcePack.GoToPublishConfirmation(), Terraria.GameContent.UI.States.WorkshopPublishInfoStateForWorld.GoToPublishConfirmation(), Terraria.Main.GoToWorldSelect(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.HandleBackButtonUsage(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.HandleBackButtonUsage(), Terraria.GameContent.UI.States.UIWorkshopHub.HandleBackButtonUsage(), Terraria.GameContent.UI.States.UIWorkshopSelectResourcePackToPublish.HandleBackButtonUsage(), Terraria.GameContent.UI.States.UIWorkshopSelectWorldToPublish.HandleBackButtonUsage(), Terraria.GameContent.UI.States.UIWorkshopWorldImport.HandleBackButtonUsage(), Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem.ImportButtonClick_ImportWorldToLocalFiles(), Terraria.GameContent.Creative.CreativeUI.Initialize(), Terraria.GameContent.UI.States.UICharacterSelect.NewCharacterClick(), Terraria.GameContent.UI.States.UIWorldSelect.NewWorldClick(), Terraria.GameContent.UI.States.UICharacterCreation.OnCanceledNaming(), Terraria.GameContent.UI.States.UICharacterCreation.OnFinishedNaming(), Terraria.GameContent.UI.States.UICharacterCreation.OnFinishedNamingAndCreating(), Terraria.GameContent.UI.States.UIWorldGenDebug.Open(), Terraria.GameContent.UI.NewCraftingUI.Open(), Terraria.Main.OpenCharacterSelectUI(), Terraria.Main.OpenPlayerSelect(), Terraria.Main.OpenReportsMenu(), Terraria.Main.OpenResourcePacksMenu(), Terraria.GameContent.UI.States.UIWorldCreation.OpenSeedInputMenu(), Terraria.GameContent.UI.Elements.UIWrappedSearchBar.OpenVirtualKeyboardWhenNeeded(), Terraria.Main.OpenWorldSelectUI(), Terraria.GameContent.UI.Elements.UIWorkshopPublishResourcePackListItem.PublishButtonClick_ImportResourcePackToLocalFiles(), Terraria.GameContent.UI.Elements.UIWorkshopPublishWorldListItem.PublishButtonClick_ImportWorldToLocalFiles(), Terraria.GameContent.UI.Elements.UIWorkshopPublishResourcePackListItem.RejectionMenuExitAction(), Terraria.GameContent.UI.Elements.UICharacterListItem.RenameButtonClick(), Terraria.GameContent.UI.Elements.UIWorldListItem.RenameButtonClick(), Terraria.GameContent.UI.States.UIWorldCreationAdvanced.SecretSeedButton_OnLeftClick(), and Terraria.GameContent.UI.States.UIWorldGenDebug.UIWorldGenDebug().