Terraria Decompiled: Terraria.Lighting.AddLight
AddLight() [5/5]
static void Terraria.Lighting.AddLight (Vector2 position, Vector3 rgb) inline static
Definition at line 154 of file Lighting.cs.
        {
            Lighting.AddLight((int)(position.X / 16f), (int)(position.Y / 16f), rgb.X, rgb.Y, rgb.Z);
        }
References Terraria.Lighting.AddLight(), Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector3.X, Microsoft.Xna.Framework.Vector2.Y, Microsoft.Xna.Framework.Vector3.Y, and Microsoft.Xna.Framework.Vector3.Z.
Referenced by Terraria.GameContent.LeashedEntities.FireflyLeashedCritter.AddLight(), Terraria.WaterfallManager.AddLight(), Terraria.Lighting.AddLight(), Terraria.Lighting.AddLight(), Terraria.Lighting.AddLight(), Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.Projectile.AI_001(), Terraria.NPC.AI_001_Slimes(), Terraria.NPC.AI_002_FloatingEye(), Terraria.Projectile.AI_003_Boomerang(), Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_005_EaterOfSouls(), Terraria.Projectile.AI_007_GrapplingHooks(), Terraria.NPC.AI_007_TownEntities(), Terraria.Projectile.AI_019_Spears(), Terraria.Projectile.AI_026(), Terraria.NPC.AI_026_Unicorns(), Terraria.NPC.AI_037_Destroyer(), Terraria.Projectile.AI_062(), Terraria.NPC.AI_065_Butterflies(), Terraria.Projectile.AI_067_FreakingPirates(), Terraria.Projectile.AI_075(), Terraria.Projectile.AI_100_Medusa(), Terraria.Projectile.AI_105_SporeSac(), Terraria.NPC.AI_112_FairyCritter(), Terraria.Projectile.AI_113_TargetSticker(), Terraria.NPC.AI_117_BloodNautilus(), Terraria.NPC.AI_120_HallowBoss(), Terraria.Projectile.AI_120_StardustGuardian(), Terraria.NPC.AI_121_QueenSlime(), Terraria.NPC.AI_127_Pal(), Terraria.Projectile.AI_130_FlameBurstTower(), Terraria.Projectile.AI_138_ExplosiveTrap(), Terraria.Projectile.AI_140_MonkStaffT1(), Terraria.Projectile.AI_142_MonkStaffT2And3(), Terraria.Projectile.AI_147_Celeb2Rocket(), Terraria.Projectile.AI_157_SharpTears(), Terraria.Projectile.AI_165_Whip(), Terraria.Projectile.AI_166_Dove(), Terraria.Projectile.AI_167_SparkleGuitar(), Terraria.Projectile.AI_182_FinalFractal(), Terraria.Projectile.AI_190_NightsEdge(), Terraria.Projectile.AI_191_TrueNightsEdge(), Terraria.Projectile.AI_195_JimsDrone(), Terraria.Projectile.AI_196_Petal(), Terraria.Projectile.AI_199_MeteorOre(), Terraria.Projectile.AI_203_StormLightning(), Terraria.Projectile.AI_204_Digtoise(), Terraria.Projectile.AI_205_RemoteControlCar(), Terraria.Mount.AimAbility(), Terraria.Player.ApplyEquipFunctional(), Terraria.DelegateMethods.CastLight(), Terraria.DelegateMethods.CastLightOpen(), Terraria.DelegateMethods.CastLightOpen_StopForSolids(), Terraria.DelegateMethods.CastLightOpen_StopForSolids_ScaleWithDistance(), Terraria.Player.DashMovement(), Terraria.Main.DrawProjDirect(), Terraria.GameContent.Drawing.TileDrawing.DrawTrees(), Terraria.Projectile.EmitEnchantmentVisualsAt(), Terraria.DataStructures.ArmorSetBonuses.Benefits.Forbidden(), Terraria.Mount.Hover(), Terraria.Player.ItemCheck_EmitHeldItemLight(), Terraria.Player.ItemCheck_EmitUseVisuals(), Terraria.Projectile.LightningKillLambda_Step(), Terraria.Player.PlayerFrame(), Terraria.Projectile.ProjLight(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_BlueLightningSmall(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_LeafCrystalShot(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_StormLightning(), Terraria.DelegateMethods.SpreadLightOpen_StopForSolids(), Terraria.GameContent.PotionOfReturnGateHelper.Update(), Terraria.GameContent.VoidLensHelper.Update(), Terraria.Gore.Update(), Terraria.Player.Update(), Terraria.Graphics.Renderers.BloodyExplosionParticle.Update(), Terraria.Graphics.Renderers.GasParticle.Update(), Terraria.Player.UpdateArmorLights(), Terraria.Player.UpdateArmorSetsOld(), Terraria.Player.UpdateBuffs(), Terraria.Dust.UpdateDust(), Terraria.Mount.UpdateEffects(), Terraria.Mount.UpdateFrame(), Terraria.WorldItem.UpdateItem(), Terraria.WorldItem.UpdateItem_VisualEffects(), Terraria.Gore.UpdateLightningBunnySparks(), Terraria.NPC.UpdateNPC_BuffApplyVFX(), Terraria.NPC.UpdateNPC_CastLights(), Terraria.NPC.UpdateNPC_UpdateTrails(), Terraria.GameContent.LeashedEntities.EmpressButterflyLeashedCritter.VisualEffects(), Terraria.GameContent.LeashedEntities.FairyLeashedCritter.VisualEffects(), Terraria.GameContent.LeashedEntities.HellButterflyLeashedCritter.VisualEffects(), Terraria.GameContent.LeashedEntities.SnailLeashedCritter.VisualEffects(), and Terraria.Player.WingFrame().