Terraria Decompiled: Terraria.Lighting.GetColor9Slice
GetColor9Slice() [1/2]
static void Terraria.Lighting.GetColor9Slice (int centerX, int centerY, ref Color[] slices) inline static
Definition at line 290 of file Lighting.cs.
        {
            int num = 0;
            for (int i = centerX - 1; i <= centerX + 1; i++)
            {
                for (int j = centerY - 1; j <= centerY + 1; j++)
                {
                    Vector3 color = Lighting._activeEngine.GetColor(i, j);
                    int num2 = (int)(255f * color.X * Lighting.GlobalBrightness);
                    int num3 = (int)(255f * color.Y * Lighting.GlobalBrightness);
                    int num4 = (int)(255f * color.Z * Lighting.GlobalBrightness);
                    if (num2 > 255)
                    {
                        num2 = 255;
                    }
                    if (num3 > 255)
                    {
                        num3 = 255;
                    }
                    if (num4 > 255)
                    {
                        num4 = 255;
                    }
                    num4 <<= 16;
                    num3 <<= 8;
                    slices[num].PackedValue = (uint)(num2 | num3 | num4 | -16777216);
                    num += 3;
                }
                num -= 8;
            }
        }
References Terraria.Lighting._activeEngine, Terraria.Graphics.Light.ILightingEngine.GetColor(), Terraria.Lighting.GlobalBrightness, int, Microsoft.Xna.Framework.Vector3.X, Microsoft.Xna.Framework.Vector3.Y, and Microsoft.Xna.Framework.Vector3.Z.
Referenced by Terraria.Main.DrawBackground_DirtBackground(), Terraria.Main.DrawBackground_DrawMagmaLayer(), Terraria.Main.DrawBackground_DrawRockLayer(), Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile_SlicedBlock(), and Terraria.Main.OldDrawBackground().