Terraria Decompiled: Terraria.Lighting.GetColor
GetColor() [3/4]
static Color Terraria.Lighting.GetColor (Point tileCoords) inline static
Definition at line 217 of file Lighting.cs.
        {
            if (Main.gameMenu)
            {
                return Color.White;
            }
            return new Color(Lighting._activeEngine.GetColor(tileCoords.X, tileCoords.Y) * Lighting.GlobalBrightness);
        }
References Terraria.Lighting._activeEngine, Terraria.Graphics.Light.Color, Terraria.Main.gameMenu, Terraria.Graphics.Light.ILightingEngine.GetColor(), Terraria.Lighting.GlobalBrightness, Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.Projectile.AI_067_FreakingPirates(), Terraria.DataStructures.PlayerDrawSet.BoringSetup(), Terraria.Graphics.Renderers.BloodyExplosionParticle.Draw(), Terraria.Graphics.Renderers.FadingParticle.Draw(), Terraria.Graphics.Renderers.FadingPlayerShaderParticle.Draw(), Terraria.Graphics.Renderers.GasParticle.Draw(), Terraria.Graphics.Renderers.ItemTransferParticle.Draw(), Terraria.Graphics.Renderers.ShockIconParticle.Draw(), Terraria.Graphics.Renderers.LittleFlyingCritterParticle.Draw_ButterFly(), Terraria.Graphics.Renderers.LittleFlyingCritterParticle.Draw_Fly(), Terraria.GameContent.Drawing.TileDrawing.DrawAnyDirectionalGrass(), Terraria.Main.DrawBackground_DirtBackground(), Terraria.Main.DrawBackground_DrawMagmaLayer(), Terraria.Main.DrawBackground_DrawMagmaTransition(), Terraria.Main.DrawBackground_DrawRockLayer(), Terraria.Main.DrawBackground_SurfaceTransitionBackground(), Terraria.GameContent.LeashedEntities.LeashedCritter.DrawBubble(), Terraria.GameContent.UI.UIDust.DrawDust(), Terraria.Main.DrawDust(), Terraria.HitTile.DrawFreshAnimations(), Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawGhost(), Terraria.Main.DrawGore(), Terraria.Main.DrawGoreBehind(), Terraria.GameContent.Drawing.TileDrawing.DrawGrass(), Terraria.Main.DrawItem(), Terraria.Main.DrawKite(), Terraria.GameContent.Drawing.TileDrawing.DrawMasterTrophies(), Terraria.Main.DrawMultisegmentPet(), Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileGrassInWind(), Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileVinesInWind(), Terraria.Utils.DrawNotificationIcon(), Terraria.Main.DrawNPCDirect(), Terraria.Main.DrawNPCHousesInWorld(), Terraria.Main.DrawNPCs(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_27_HeldItem(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_38_EyebrellaCloud(), Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayerStoned(), Terraria.Main.DrawProj_DeadCellsFlintSlash(), Terraria.Main.DrawProj_Excalibur(), Terraria.Main.DrawProj_FishingLine(), Terraria.Main.DrawProj_FlailChains(), Terraria.Main.DrawProj_FlailChains_Old(), Terraria.Main.DrawProj_NightsEdge(), Terraria.Main.DrawProj_PiercingStarlight(), Terraria.Main.DrawProj_TerraBlade2(), Terraria.Main.DrawProj_TerraBlade2Shot(), Terraria.Main.DrawProj_TheHorsemansBlade(), Terraria.Main.DrawProj_TrueExcalibur(), Terraria.Main.DrawProj_TrueNightsEdge(), Terraria.Main.DrawProjDirect(), Terraria.Main.DrawRain(), Terraria.GameContent.Drawing.TileDrawing.DrawRisingVineStrip(), Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile(), Terraria.Main.DrawSmartCursor(), Terraria.Main.DrawSmartInteract(), Terraria.GameContent.Drawing.TileDrawing.DrawSpecialTilesLegacy(), Terraria.GameContent.Drawing.TileDrawing.DrawTeleportationPylons(), Terraria.Main.DrawTileCracks(), Terraria.Main.DrawTileInWater(), Terraria.GameContent.PotionOfReturnGateHelper.DrawToDrawData(), Terraria.GameContent.VoidLensHelper.DrawToDrawData(), Terraria.GameContent.Drawing.TileDrawing.DrawTrees(), Terraria.Main.DrawTwinsPet(), Terraria.GameContent.Drawing.TileDrawing.DrawVineStrip(), Terraria.Main.DrawWallOfFish(), Terraria.GameContent.Drawing.WallDrawing.DrawWalls(), Terraria.WaterfallManager.DrawWaterfall(), Terraria.Main.DrawWhip(), Terraria.Main.DrawWhip_BoneWhip(), Terraria.Main.DrawWhip_Constellation(), Terraria.Main.DrawWhip_CoolWhip(), Terraria.Main.DrawWhip_EelWhip(), Terraria.Main.DrawWhip_FireWhip(), Terraria.Main.DrawWhip_FlowerWhip(), Terraria.Main.DrawWhip_GenericWhip(), Terraria.Main.DrawWhip_MoonLordWhip(), Terraria.Main.DrawWhip_RainbowWhip(), Terraria.Main.DrawWhip_SlimeWhip(), Terraria.Main.DrawWhip_ThornWhip(), Terraria.Main.DrawWhip_WhipBland(), Terraria.Main.DrawWhip_WhipMace(), Terraria.Main.DrawWhip_WhipScythe(), Terraria.Main.DrawWhip_WhipSword(), Terraria.Main.DrawWires(), Terraria.Main.DrawWOFBody(), Terraria.Main.DrawWOFRopeToTheHungry(), Terraria.Main.DrawWOFTongueToPlayer(), Terraria.GameContent.Drawing.TileDrawing.DrawXmasTree(), Terraria.Player.GetHairColor(), Terraria.GameContent.Events.MoonlordDeathDrama.MoonlordPiece.GetLight(), Terraria.Testing.DebugUtils.GetTileDescription(), Terraria.GameContent.Drawing.TileDrawing.GetTileDrawData(), Terraria.Player.HeroicisWingDust(), Terraria.GameContent.DontStarveDarknessDamageDealer.IsPlayerSafe(), Terraria.Initializers.DyeInitializer.LoadLegacyHairdyes(), Terraria.Main.OldDrawBackground(), Terraria.Main.oldDrawWater(), Terraria.Dust.UpdateDust(), Terraria.NPC.UpdateNPC_CastLights(), and Terraria.GameContent.LeashedEntities.LeashedCritter.VisualEffects().