Terraria Decompiled: Terraria.Lighting.GetSubLight
GetSubLight()
static Vector3 Terraria.Lighting.GetSubLight (Vector2 position) inline static
Definition at line 138 of file Lighting.cs.
        {
            Vector2 vector = position / 16f - new Vector2(0.5f, 0.5f);
            Vector2 vector2 = new Vector2(vector.X % 1f, vector.Y % 1f);
            int num = (int)vector.X;
            int num2 = (int)vector.Y;
            Vector3 color = Lighting._activeEngine.GetColor(num, num2);
            Vector3 color2 = Lighting._activeEngine.GetColor(num + 1, num2);
            Vector3 color3 = Lighting._activeEngine.GetColor(num, num2 + 1);
            Vector3 color4 = Lighting._activeEngine.GetColor(num + 1, num2 + 1);
            Vector3 vector3 = Vector3.Lerp(color, color2, vector2.X);
            Vector3 vector4 = Vector3.Lerp(color3, color4, vector2.X);
            return Vector3.Lerp(vector3, vector4, vector2.Y);
        }
References Terraria.Lighting._activeEngine, Terraria.Graphics.Light.ILightingEngine.GetColor(), int, Microsoft.Xna.Framework.Vector3.Lerp(), Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.GameContent.Dyes.ReflectiveArmorShaderData.Apply(), and Terraria.GameInput.LockOnHelper.RefreshTargets().