Terraria Decompiled: Terraria.Lighting.GetColorClamped
GetColorClamped()
static Color Terraria.Lighting.GetColorClamped (int x, int y, Color oldColor) inline static
Definition at line 247 of file Lighting.cs.
        {
            if (Main.gameMenu)
            {
                return oldColor;
            }
            Vector3 vector = Lighting._activeEngine.GetColor(x, y);
            vector = Vector3.Min(Vector3.One, vector);
            return new Color(vector * oldColor.ToVector3());
        }
References Terraria.Lighting._activeEngine, Terraria.Graphics.Light.Color, Terraria.Main.gameMenu, Terraria.Graphics.Light.ILightingEngine.GetColor(), Microsoft.Xna.Framework.Vector3.Min(), Microsoft.Xna.Framework.Vector3.One, and Microsoft.Xna.Framework.Color.ToVector3().
Referenced by Terraria.DataStructures.PlayerDrawSet.BoringSetup(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_21_Head(), and Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_21_Head_TheFace_Eyelid().