Terraria Decompiled: Terraria.Lighting.NextLightMode
NextLightMode()
static void Terraria.Lighting.NextLightMode () inline static
Definition at line 200 of file Lighting.cs.
        {
            Lighting.Mode++;
            if (!Enum.IsDefined(typeof(LightMode), Lighting.Mode))
            {
                Lighting.Mode = LightMode.White;
            }
            Lighting.Clear();
        }
References Terraria.Lighting.Clear(), System.Enum.IsDefined(), and Terraria.Lighting.Mode.
Referenced by Terraria.Main.DoUpdate_F9_ToggleLighting(), and Terraria.Main.DrawMenu().