Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteValue
WriteValue()
void System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteValue (InternalPrimitiveTypeE code, object value) inline package
Definition at line 574 of file __BinaryWriter.cs.
        {
            switch (code)
            {
            case InternalPrimitiveTypeE.Boolean:
                this.WriteBoolean(Convert.ToBoolean(value, CultureInfo.InvariantCulture));
                return;
            case InternalPrimitiveTypeE.Byte:
                this.WriteByte(Convert.ToByte(value, CultureInfo.InvariantCulture));
                return;
            case InternalPrimitiveTypeE.Char:
                this.WriteChar(Convert.ToChar(value, CultureInfo.InvariantCulture));
                return;
            case InternalPrimitiveTypeE.Decimal:
                this.WriteDecimal(Convert.ToDecimal(value, CultureInfo.InvariantCulture));
                return;
            case InternalPrimitiveTypeE.Double:
                this.WriteDouble(Convert.ToDouble(value, CultureInfo.InvariantCulture));
                return;
            case InternalPrimitiveTypeE.Int16:
                this.WriteInt16(Convert.ToInt16(value, CultureInfo.InvariantCulture));
                return;
            case InternalPrimitiveTypeE.Int32:
                this.WriteInt32(Convert.ToInt32(value, CultureInfo.InvariantCulture));
                return;
            case InternalPrimitiveTypeE.Int64:
                this.WriteInt64(Convert.ToInt64(value, CultureInfo.InvariantCulture));
                return;
            case InternalPrimitiveTypeE.SByte:
                this.WriteSByte(Convert.ToSByte(value, CultureInfo.InvariantCulture));
                return;
            case InternalPrimitiveTypeE.Single:
                this.WriteSingle(Convert.ToSingle(value, CultureInfo.InvariantCulture));
                return;
            case InternalPrimitiveTypeE.TimeSpan:
                this.WriteTimeSpan((TimeSpan)value);
                return;
            case InternalPrimitiveTypeE.DateTime:
                this.WriteDateTime((DateTime)value);
                return;
            case InternalPrimitiveTypeE.UInt16:
                this.WriteUInt16(Convert.ToUInt16(value, CultureInfo.InvariantCulture));
                return;
            case InternalPrimitiveTypeE.UInt32:
                this.WriteUInt32(Convert.ToUInt32(value, CultureInfo.InvariantCulture));
                return;
            case InternalPrimitiveTypeE.UInt64:
                this.WriteUInt64(Convert.ToUInt64(value, CultureInfo.InvariantCulture));
                return;
            }
            throw new SerializationException(Environment.GetResourceString("Invalid type code in stream '{0}'.", new object[] { code.ToString() }));
        }
References System.Environment.GetResourceString(), System.Globalization.CultureInfo.InvariantCulture, System.Convert.ToBoolean(), System.Convert.ToByte(), System.Convert.ToChar(), System.Convert.ToDecimal(), System.Convert.ToDouble(), System.Convert.ToInt16(), System.Convert.ToInt32(), System.Convert.ToInt64(), System.Convert.ToSByte(), System.Convert.ToSingle(), System.Convert.ToUInt16(), System.Convert.ToUInt32(), System.Convert.ToUInt64(), System.value, System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteBoolean(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteByte(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteChar(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteDateTime(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteDecimal(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteDouble(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteInt16(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteInt32(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteInt64(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteSByte(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteSingle(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteTimeSpan(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteUInt16(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteUInt32(), and System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteUInt64().
Referenced by System.Runtime.Serialization.Formatters.Binary.MemberPrimitiveTyped.Write(), System.Runtime.Serialization.Formatters.Binary.MemberPrimitiveUnTyped.Write(), and System.Runtime.Serialization.Formatters.Binary.IOUtil.WriteWithCode().