Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteRectangleArray
WriteRectangleArray()
void System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteRectangleArray (NameInfo memberNameInfo, NameInfo arrayNameInfo, WriteObjectInfo objectInfo, NameInfo arrayElemTypeNameInfo, int rank, int[] lengthA, int[] lowerBoundA) inline package
Definition at line 399 of file __BinaryWriter.cs.
        {
            this.InternalWriteItemNull();
            BinaryArrayTypeEnum binaryArrayTypeEnum = BinaryArrayTypeEnum.Rectangular;
            object obj = null;
            int num = 0;
            BinaryTypeEnum binaryTypeInfo = BinaryConverter.GetBinaryTypeInfo(arrayElemTypeNameInfo.NItype, objectInfo, arrayElemTypeNameInfo.NIname, this.objectWriter, out obj, out num);
            if (this.binaryArray == null)
            {
                this.binaryArray = new BinaryArray();
            }
            for (int i = 0; i < rank; i++)
            {
                if (lowerBoundA[i] != 0)
                {
                    binaryArrayTypeEnum = BinaryArrayTypeEnum.RectangularOffset;
                    break;
                }
            }
            this.binaryArray.Set((int)arrayNameInfo.NIobjectId, rank, lengthA, lowerBoundA, binaryTypeInfo, obj, binaryArrayTypeEnum, num);
            long niobjectId = arrayNameInfo.NIobjectId;
            this.binaryArray.Write(this);
        }
References System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.binaryArray, System.Runtime.Serialization.Formatters.Binary.BinaryConverter.GetBinaryTypeInfo(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.InternalWriteItemNull(), System.Runtime.Serialization.Formatters.Binary.NameInfo.NIname, System.Runtime.Serialization.Formatters.Binary.NameInfo.NIobjectId, System.Runtime.Serialization.Formatters.Binary.NameInfo.NItype, System.obj, System.Runtime.Serialization.Formatters.Binary.BinaryArray.Set(), and System.Runtime.Serialization.Formatters.Binary.BinaryArray.Write().
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteArray().