Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteAssembly
WriteAssembly()
void System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteAssembly (Type type, string assemblyString, int assemId, bool isNew) inline package
Definition at line 554 of file __BinaryWriter.cs.
        {
            this.InternalWriteItemNull();
            if (assemblyString == null)
            {
                assemblyString = string.Empty;
            }
            if (isNew)
            {
                if (this.binaryAssembly == null)
                {
                    this.binaryAssembly = new BinaryAssembly();
                }
                this.binaryAssembly.Set(assemId, assemblyString);
                this.binaryAssembly.Dump();
                this.binaryAssembly.Write(this);
            }
        }
References System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.binaryAssembly, System.Runtime.Serialization.Formatters.Binary.BinaryAssembly.Dump(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.InternalWriteItemNull(), System.Runtime.Serialization.Formatters.Binary.BinaryAssembly.Set(), and System.Runtime.Serialization.Formatters.Binary.BinaryAssembly.Write().
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectWriter.GetAssemblyId().