Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteObject
WriteObject()
void System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteObject (NameInfo nameInfo, NameInfo typeNameInfo, int numMembers, string[] memberNames, Type[] memberTypes, WriteObjectInfo[] memberObjectInfos) inline package
Definition at line 212 of file __BinaryWriter.cs.
        {
            this.InternalWriteItemNull();
            int num = (int)nameInfo.NIobjectId;
            string text;
            if (num < 0)
            {
                text = typeNameInfo.NIname;
            }
            else
            {
                text = nameInfo.NIname;
            }
            if (this.objectMapTable == null)
            {
                this.objectMapTable = new Hashtable();
            }
            ObjectMapInfo objectMapInfo = (ObjectMapInfo)this.objectMapTable[text];
            if (objectMapInfo != null && objectMapInfo.isCompatible(numMembers, memberNames, memberTypes))
            {
                if (this.binaryObject == null)
                {
                    this.binaryObject = new BinaryObject();
                }
                this.binaryObject.Set(num, objectMapInfo.objectId);
                this.binaryObject.Write(this);
                return;
            }
            if (!typeNameInfo.NItransmitTypeOnObject)
            {
                if (this.binaryObjectWithMap == null)
                {
                    this.binaryObjectWithMap = new BinaryObjectWithMap();
                }
                int num2 = (int)typeNameInfo.NIassemId;
                this.binaryObjectWithMap.Set(num, text, numMembers, memberNames, num2);
                this.binaryObjectWithMap.Dump();
                this.binaryObjectWithMap.Write(this);
                if (objectMapInfo == null)
                {
                    this.objectMapTable.Add(text, new ObjectMapInfo(num, numMembers, memberNames, memberTypes));
                    return;
                }
            }
            else
            {
                BinaryTypeEnum[] array = new BinaryTypeEnum[numMembers];
                object[] array2 = new object[numMembers];
                int[] array3 = new int[numMembers];
                int num2;
                for (int i = 0; i < numMembers; i++)
                {
                    object obj = null;
                    array[i] = BinaryConverter.GetBinaryTypeInfo(memberTypes[i], memberObjectInfos[i], null, this.objectWriter, out obj, out num2);
                    array2[i] = obj;
                    array3[i] = num2;
                }
                if (this.binaryObjectWithMapTyped == null)
                {
                    this.binaryObjectWithMapTyped = new BinaryObjectWithMapTyped();
                }
                num2 = (int)typeNameInfo.NIassemId;
                this.binaryObjectWithMapTyped.Set(num, text, numMembers, memberNames, array, array2, array3, num2);
                this.binaryObjectWithMapTyped.Write(this);
                if (objectMapInfo == null)
                {
                    this.objectMapTable.Add(text, new ObjectMapInfo(num, numMembers, memberNames, memberTypes));
                }
            }
        }
References System.Collections.Hashtable.Add(), System.array, System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.binaryObject, System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.binaryObjectWithMap, System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.binaryObjectWithMapTyped, System.Runtime.Serialization.Formatters.Binary.BinaryObjectWithMap.Dump(), System.Runtime.Serialization.Formatters.Binary.BinaryConverter.GetBinaryTypeInfo(), int, System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.InternalWriteItemNull(), System.Runtime.Serialization.Formatters.Binary.ObjectMapInfo.isCompatible(), System.Runtime.Serialization.Formatters.Binary.NameInfo.NIassemId, System.Runtime.Serialization.Formatters.Binary.NameInfo.NIname, System.Runtime.Serialization.Formatters.Binary.NameInfo.NIobjectId, System.Runtime.Serialization.Formatters.Binary.NameInfo.NItransmitTypeOnObject, System.obj, System.Runtime.Serialization.Formatters.Binary.ObjectMapInfo.objectId, System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.objectMapTable, System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.objectWriter, System.Runtime.Serialization.Formatters.Binary.BinaryObject.Set(), System.Runtime.Serialization.Formatters.Binary.BinaryObjectWithMapTyped.Set(), System.Runtime.Serialization.Formatters.Binary.BinaryObjectWithMap.Set(), System.text, System.Runtime.Serialization.Formatters.Binary.BinaryObject.Write(), System.Runtime.Serialization.Formatters.Binary.BinaryObjectWithMap.Write(), and System.Runtime.Serialization.Formatters.Binary.BinaryObjectWithMapTyped.Write().
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write().