Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteArrayAsBytes
WriteArrayAsBytes()
void System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteArrayAsBytes (Array array, int typeLength) inline private
Definition at line 340 of file __BinaryWriter.cs.
        {
            this.InternalWriteItemNull();
            int i = 0;
            if (this.byteBuffer == null)
            {
                this.byteBuffer = new byte[this.chunkSize];
            }
            while (i < array.Length)
            {
                int num = Math.Min(this.chunkSize / typeLength, array.Length - i);
                int num2 = num * typeLength;
                Buffer.InternalBlockCopy(array, i * typeLength, this.byteBuffer, 0, num2);
                if (!BitConverter.IsLittleEndian)
                {
                    for (int j = 0; j < num2; j += typeLength)
                    {
                        for (int k = 0; k < typeLength / 2; k++)
{
                            byte b = this.byteBuffer[j + k];
                            this.byteBuffer[j + k] = this.byteBuffer[j + typeLength - 1 - k];
                            this.byteBuffer[j + typeLength - 1 - k] = b;
                        }
                    }
                }
                this.WriteBytes(this.byteBuffer, 0, num2);
                i += num;
            }
        }
References System.array, System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.byteBuffer, System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.chunkSize, System.Buffer.InternalBlockCopy(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.InternalWriteItemNull(), System.BitConverter.IsLittleEndian, System.Math.Min(), and System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteBytes().
Referenced by System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteSingleArray().