Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteSingleArray
WriteSingleArray()
void System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteSingleArray (NameInfo memberNameInfo, NameInfo arrayNameInfo, WriteObjectInfo objectInfo, NameInfo arrayElemTypeNameInfo, int length, int lowerBound, Array array) inline package
Definition at line 297 of file __BinaryWriter.cs.
        {
            this.InternalWriteItemNull();
            int[] array2 = new int[] { length };
            int[] array3 = null;
            object obj = null;
            BinaryArrayTypeEnum binaryArrayTypeEnum;
            if (lowerBound == 0)
            {
                binaryArrayTypeEnum = BinaryArrayTypeEnum.Single;
            }
            else
            {
                binaryArrayTypeEnum = BinaryArrayTypeEnum.SingleOffset;
                array3 = new int[] { lowerBound };
            }
            int num;
            BinaryTypeEnum binaryTypeInfo = BinaryConverter.GetBinaryTypeInfo(arrayElemTypeNameInfo.NItype, objectInfo, arrayElemTypeNameInfo.NIname, this.objectWriter, out obj, out num);
            if (this.binaryArray == null)
            {
                this.binaryArray = new BinaryArray();
            }
            this.binaryArray.Set((int)arrayNameInfo.NIobjectId, 1, array2, array3, binaryTypeInfo, obj, binaryArrayTypeEnum, num);
            long niobjectId = arrayNameInfo.NIobjectId;
            this.binaryArray.Write(this);
            if (Converter.IsWriteAsByteArray(arrayElemTypeNameInfo.NIprimitiveTypeEnum) && lowerBound == 0)
            {
                if (arrayElemTypeNameInfo.NIprimitiveTypeEnum == InternalPrimitiveTypeE.Byte)
                {
                    this.WriteBytes((byte[])array);
                    return;
                }
                if (arrayElemTypeNameInfo.NIprimitiveTypeEnum == InternalPrimitiveTypeE.Char)
                {
                    this.WriteChars((char[])array);
                    return;
                }
                this.WriteArrayAsBytes(array, Converter.TypeLength(arrayElemTypeNameInfo.NIprimitiveTypeEnum));
            }
        }
References System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.binaryArray, System.Runtime.Serialization.Formatters.Binary.BinaryConverter.GetBinaryTypeInfo(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.InternalWriteItemNull(), System.Runtime.Serialization.Formatters.Binary.Converter.IsWriteAsByteArray(), System.length, System.Runtime.Serialization.Formatters.Binary.NameInfo.NIname, System.Runtime.Serialization.Formatters.Binary.NameInfo.NIobjectId, System.Runtime.Serialization.Formatters.Binary.NameInfo.NIprimitiveTypeEnum, System.Runtime.Serialization.Formatters.Binary.NameInfo.NItype, System.obj, System.Runtime.Serialization.Formatters.Binary.BinaryArray.Set(), System.Runtime.Serialization.Formatters.Binary.Converter.TypeLength(), System.Runtime.Serialization.Formatters.Binary.BinaryArray.Write(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteArrayAsBytes(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteBytes(), and System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteChars().
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteArray(), and System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteObjectByteArray().