Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteNullMember
WriteNullMember()
void System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteNullMember (NameInfo memberNameInfo, NameInfo typeNameInfo) inline package
Definition at line 459 of file __BinaryWriter.cs.
        {
            this.InternalWriteItemNull();
            if (this.objectNull == null)
            {
                this.objectNull = new ObjectNull();
            }
            if (!memberNameInfo.NIisArrayItem)
            {
                this.objectNull.SetNullCount(1);
                this.objectNull.Dump();
                this.objectNull.Write(this);
                this.nullCount = 0;
            }
        }
References System.Runtime.Serialization.Formatters.Binary.ObjectNull.Dump(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.InternalWriteItemNull(), System.Runtime.Serialization.Formatters.Binary.NameInfo.NIisArrayItem, System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.objectNull, System.Runtime.Serialization.Formatters.Binary.ObjectNull, System.Runtime.Serialization.Formatters.Binary.ObjectNull.SetNullCount(), and System.Runtime.Serialization.Formatters.Binary.ObjectNull.Write().
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectWriter.CheckForNull().