Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteObjectString
WriteObjectString()
void System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteObjectString (int objectId, string value) inline package
Definition at line 284 of file __BinaryWriter.cs.
        {
            this.InternalWriteItemNull();
            if (this.binaryObjectString == null)
            {
                this.binaryObjectString = new BinaryObjectString();
            }
            this.binaryObjectString.Set(objectId, value);
            this.binaryObjectString.Write(this);
        }
References System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.binaryObjectString, System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.InternalWriteItemNull(), System.Runtime.Serialization.Formatters.Binary.BinaryObjectString.Set(), System.value, and System.Runtime.Serialization.Formatters.Binary.BinaryObjectString.Write().
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(), and System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteMemberString().