Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.InternalWriteItemNull
InternalWriteItemNull()
void System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.InternalWriteItemNull () inline private
Definition at line 531 of file __BinaryWriter.cs.
        {
            if (this.nullCount > 0)
            {
                if (this.objectNull == null)
                {
                    this.objectNull = new ObjectNull();
                }
                this.objectNull.SetNullCount(this.nullCount);
                this.objectNull.Dump();
                this.objectNull.Write(this);
                this.nullCount = 0;
            }
        }
References System.Runtime.Serialization.Formatters.Binary.ObjectNull.Dump(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.nullCount, System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.objectNull, System.Runtime.Serialization.Formatters.Binary.ObjectNull, System.Runtime.Serialization.Formatters.Binary.ObjectNull.SetNullCount(), and System.Runtime.Serialization.Formatters.Binary.ObjectNull.Write().
Referenced by System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteArrayAsBytes(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteAssembly(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteItem(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteItemEnd(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteItemObjectRef(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteJaggedArray(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteMember(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteMemberNested(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteMemberObjectRef(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteMemberString(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteNullItem(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteNullMember(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteObject(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteObjectByteArray(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteObjectString(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteRectangleArray(), and System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteSingleArray().