Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteMember
WriteMember()
void System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteMember (NameInfo memberNameInfo, NameInfo typeNameInfo, object value) inline package
Definition at line 432 of file __BinaryWriter.cs.
        {
            this.InternalWriteItemNull();
            InternalPrimitiveTypeE niprimitiveTypeEnum = typeNameInfo.NIprimitiveTypeEnum;
            if (memberNameInfo.NItransmitTypeOnMember)
            {
                if (this.memberPrimitiveTyped == null)
                {
                    this.memberPrimitiveTyped = new MemberPrimitiveTyped();
                }
                this.memberPrimitiveTyped.Set(niprimitiveTypeEnum, value);
                bool niisArrayItem = memberNameInfo.NIisArrayItem;
                this.memberPrimitiveTyped.Dump();
                this.memberPrimitiveTyped.Write(this);
                return;
            }
            if (this.memberPrimitiveUnTyped == null)
            {
                this.memberPrimitiveUnTyped = new MemberPrimitiveUnTyped();
            }
            this.memberPrimitiveUnTyped.Set(niprimitiveTypeEnum, value);
            bool niisArrayItem2 = memberNameInfo.NIisArrayItem;
            this.memberPrimitiveUnTyped.Dump();
            this.memberPrimitiveUnTyped.Write(this);
        }
References System.Runtime.Serialization.Formatters.Binary.MemberPrimitiveTyped.Dump(), System.Runtime.Serialization.Formatters.Binary.MemberPrimitiveUnTyped.Dump(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.InternalWriteItemNull(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.memberPrimitiveTyped, System.Runtime.Serialization.Formatters.Binary.MemberPrimitiveTyped, System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.memberPrimitiveUnTyped, System.Runtime.Serialization.Formatters.Binary.NameInfo.NIisArrayItem, System.Runtime.Serialization.Formatters.Binary.NameInfo.NIprimitiveTypeEnum, System.Runtime.Serialization.Formatters.Binary.NameInfo.NItransmitTypeOnMember, System.Runtime.Serialization.Formatters.Binary.MemberPrimitiveTyped.Set(), System.Runtime.Serialization.Formatters.Binary.MemberPrimitiveUnTyped.Set(), System.value, System.Runtime.Serialization.Formatters.Binary.MemberPrimitiveTyped.Write(), and System.Runtime.Serialization.Formatters.Binary.MemberPrimitiveUnTyped.Write().
Referenced by System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteItem(), and System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteKnownValueClass().