Terraria Decompiled: Terraria.GameContent.UI.States.UIEmotesMenu.RemoveSnapPointsOutOfScreen
RemoveSnapPointsOutOfScreen()
void Terraria.GameContent.UI.States.UIEmotesMenu.RemoveSnapPointsOutOfScreen (SpriteBatch spriteBatch, List< SnapPoint > pts) inline private
Definition at line 487 of file UIEmotesMenu.cs.
        {
            float num = 1f / Main.UIScale;
            Rectangle clippingRectangle = this._container.GetClippingRectangle(spriteBatch);
            Vector2 vector = clippingRectangle.TopLeft() * num;
            Vector2 vector2 = clippingRectangle.BottomRight() * num;
            for (int i = 0; i < pts.Count; i++)
            {
                if (!pts[i].Position.Between(vector, vector2))
                {
                    pts.Remove(pts[i]);
                    i--;
                }
            }
        }
References Terraria.GameContent.UI.States.UIEmotesMenu._container, System.Collections.Generic.List< T >.Count, Terraria.UI.UIElement.GetClippingRectangle(), Microsoft.Xna.Framework.Graphics.Position, System.Collections.Generic.List< T >.Remove(), and Terraria.Main.UIScale.
Referenced by Terraria.GameContent.UI.States.UIEmotesMenu.SetupGamepadPoints2().