Terraria Decompiled: Terraria.GameContent.UI.States.UIEmotesMenu.SetupGamepadPoints2
SetupGamepadPoints2()
void Terraria.GameContent.UI.States.UIEmotesMenu.SetupGamepadPoints2 (SpriteBatch spriteBatch) inline private
Definition at line 342 of file UIEmotesMenu.cs.
        {
            int num = 7;
            UILinkPointNavigator.Shortcuts.BackButtonCommand = 1;
            int num3;
            int num2 = (num3 = 3001);
            List<SnapPoint> snapPoints = this.GetSnapPoints();
            this.RemoveSnapPointsOutOfScreen(spriteBatch, snapPoints);
            UILinkPointNavigator.SetPosition(num2, this._backPanel.GetInnerDimensions().ToRectangle().Center.ToVector2());
            UILinkPoint uilinkPoint = UILinkPointNavigator.Points[num3];
            uilinkPoint.Unlink();
            uilinkPoint.Up = num3 + 1;
            UILinkPoint uilinkPoint2 = uilinkPoint;
            num3++;
            int num4 = 0;
            List<List<SnapPoint>> list = new List<List<SnapPoint>>();
            for (int i = 0; i < num; i++)
            {
                List<SnapPoint> emoteGroup = this.GetEmoteGroup(snapPoints, i);
                if (emoteGroup.Count > 0)
                {
                    list.Add(emoteGroup);
                }
                num4 += (int)Math.Ceiling((double)((float)emoteGroup.Count / 14f));
            }
            SnapPoint[,] array = new SnapPoint[14, num4];
            int num5 = 0;
            for (int j = 0; j < list.Count; j++)
            {
                List<SnapPoint> list2 = list[j];
                for (int k = 0; k < list2.Count; k++)
                {
                    int num6 = num5 + k / 14;
                    int num7 = k % 14;
                    array[num7, num6] = list2[k];
                }
                num5 += (int)Math.Ceiling((double)((float)list2.Count / 14f));
            }
            int[,] array2 = new int[14, num4];
            int num8 = 0;
            for (int l = 0; l < array.GetLength(1); l++)
            {
                for (int m = 0; m < array.GetLength(0); m++)
                {
                    SnapPoint snapPoint = array[m, l];
                    if (snapPoint != null)
                    {
                        UILinkPointNavigator.Points[num3].Unlink();
                        UILinkPointNavigator.SetPosition(num3, snapPoint.Position);
                        array2[m, l] = num3;
                        if (m == 0)
{
                            num8 = num3;
                        }
                        num3++;
                    }
                }
            }
            uilinkPoint2.Up = num8;
            for (int n = 0; n < array.GetLength(1); n++)
            {
                for (int num9 = 0; num9 < array.GetLength(0); num9++)
                {
                    int num10 = array2[num9, n];
                    if (num10 != 0)
                    {
                        UILinkPoint uilinkPoint3 = UILinkPointNavigator.Points[num10];
                        if (this.TryGetPointOnGrid(array2, num9, n, -1, 0))
{
                            uilinkPoint3.Left = array2[num9 - 1, n];
                        }
                        else
{
                            uilinkPoint3.Left = uilinkPoint3.ID;
                            for (int num11 = num9; num11 < array.GetLength(0); num11++)
{
                                if (this.TryGetPointOnGrid(array2, num11, n, 0, 0))
{
                                    uilinkPoint3.Left = array2[num11, n];
                                }
                            }
                        }
                        if (this.TryGetPointOnGrid(array2, num9, n, 1, 0))
{
                            uilinkPoint3.Right = array2[num9 + 1, n];
                        }
                        else
{
                            uilinkPoint3.Right = uilinkPoint3.ID;
                            for (int num12 = num9; num12 >= 0; num12--)
{
                                if (this.TryGetPointOnGrid(array2, num12, n, 0, 0))
{
                                    uilinkPoint3.Right = array2[num12, n];
                                }
                            }
                        }
                        if (this.TryGetPointOnGrid(array2, num9, n, 0, -1))
{
                            uilinkPoint3.Up = array2[num9, n - 1];
                        }
                        else
{
                            uilinkPoint3.Up = uilinkPoint3.ID;
                            for (int num13 = n - 1; num13 >= 0; num13--)
{
                                if (this.TryGetPointOnGrid(array2, num9, num13, 0, 0))
{
                                    uilinkPoint3.Up = array2[num9, num13];
                                    break;
                                }
                            }
                        }
                        if (this.TryGetPointOnGrid(array2, num9, n, 0, 1))
{
                            uilinkPoint3.Down = array2[num9, n + 1];
                        }
                        else
{
                            uilinkPoint3.Down = uilinkPoint3.ID;
                            for (int num14 = n + 1; num14 < array.GetLength(1); num14++)
{
                                if (this.TryGetPointOnGrid(array2, num9, num14, 0, 0))
{
                                    uilinkPoint3.Down = array2[num9, num14];
                                    break;
                                }
                            }
                            if (uilinkPoint3.Down == uilinkPoint3.ID)
{
                                uilinkPoint3.Down = uilinkPoint2.ID;
                            }
                        }
                    }
                }
            }
        }
References Terraria.GameContent.UI.States.UIEmotesMenu._backPanel, System.array, System.Math.Ceiling(), Microsoft.Xna.Framework.Rectangle.Center, System.Collections.Generic.List< T >.Count, Terraria.UI.Gamepad.UILinkPoint.Down, Terraria.GameContent.UI.States.UIEmotesMenu.GetEmoteGroup(), Terraria.UI.UIElement.GetInnerDimensions(), Terraria.UI.UIElement.GetSnapPoints(), Terraria.UI.Gamepad.UILinkPoint.ID, int, System.list, Terraria.UI.Gamepad.UILinkPointNavigator.Points, Terraria.UI.SnapPoint.Position, Terraria.GameContent.UI.States.UIEmotesMenu.RemoveSnapPointsOutOfScreen(), Terraria.UI.Gamepad.UILinkPointNavigator.SetPosition(), Terraria.UI.CalculatedStyle.ToRectangle(), Terraria.GameContent.UI.States.UIEmotesMenu.TryGetPointOnGrid(), and Terraria.UI.Gamepad.UILinkPoint.Unlink().
Referenced by Terraria.GameContent.UI.States.UIEmotesMenu.Draw().