Terraria Decompiled: Terraria.GameContent.Generation.ShapeRoot.DoRoot
DoRoot()
bool Terraria.GameContent.Generation.ShapeRoot.DoRoot (Point origin, GenAction action, double angle, double distance, double startingSize) inline private
Definition at line 20 of file ShapeRoot.cs.
        {
            double num = (double)origin.X;
            double num2 = (double)origin.Y;
            for (double num3 = 0.0; num3 < distance * 0.85; num3 += 1.0)
            {
                double num4 = num3 / distance;
                double num5 = Utils.Lerp(startingSize, this._endingSize, num4);
                num += Math.Cos(angle);
                num2 += Math.Sin(angle);
                angle += (double)GenBase._random.NextFloat() - 0.5 + (double)GenBase._random.NextFloat() * (this._angle - 1.5707963705062866) * 0.1 * (1.0 - num4);
                angle = angle * 0.4 + 0.45 * Utils.Clamp<double>(angle, this._angle - 2.0 * (1.0 - 0.5 * num4), this._angle + 2.0 * (1.0 - 0.5 * num4)) + Utils.Lerp(this._angle, 1.5707963705062866, num4) * 0.15;
                for (int i = 0; i < (int)num5; i++)
                {
                    for (int j = 0; j < (int)num5; j++)
                    {
                        if (!base.UnitApply(action, origin, (int)num + i, (int)num2 + j, new object[0]) && this._quitOnFail)
{
                            return false;
                        }
                    }
                }
            }
            return true;
        }
References Terraria.GameContent.Generation.ShapeRoot._angle, Terraria.GameContent.Generation.ShapeRoot._endingSize, Terraria.WorldBuilding.GenShape._quitOnFail, Terraria.WorldBuilding.GenBase._random, System.action, Terraria.Utils.Clamp(), System.Math.Cos(), int, Terraria.Utils.Lerp(), System.Math.Sin(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.Generation.ShapeRoot.Perform().