Terraria Decompiled: Terraria.GameContent.SecretSeedsTracker.PrepareInterface
PrepareInterface()
static void Terraria.GameContent.SecretSeedsTracker.PrepareInterface () inline static
Definition at line 18 of file SecretSeedsTracker.cs.
        {
            if (!SecretSeedsTracker._processedConfig)
            {
                SecretSeedsTracker._processedConfig = true;
                SecretSeedsTracker._seedsForInterface.Clear();
                using (List<string>.Enumerator enumerator = SecretSeedsTracker._seedsForConfig.GetEnumerator())
                {
                    while (enumerator.MoveNext())
                    {
                        WorldGen.SecretSeed secretSeed;
                        if (SecretSeedsTracker.SeedHasSecret(enumerator.Current, out secretSeed))
{
                            SecretSeedsTracker._seedsForInterface.Add(secretSeed);
                        }
                    }
                }
                SecretSeedsTracker._seedsForInterface = SecretSeedsTracker._seedsForInterface.Distinct<WorldGen.SecretSeed>().ToList<WorldGen.SecretSeed>();
                SecretSeedsTracker._seedsForConfig.Clear();
                SecretSeedsTracker._seedsForConfig.AddRange(SecretSeedsTracker._seedsForInterface.Select((WorldGen.SecretSeed x) => x.TextThatWasUsedToUnlock));
            }
            SecretSeedsTracker._seedsForConfig.Sort();
            SecretSeedsTracker._seedsForInterface.Sort((WorldGen.SecretSeed a, WorldGen.SecretSeed b) => a.TextThatWasUsedToUnlock.CompareTo(b.TextThatWasUsedToUnlock));
        }
References Terraria.GameContent.SecretSeedsTracker._processedConfig, Terraria.GameContent.SecretSeedsTracker._seedsForConfig, Terraria.GameContent.SecretSeedsTracker._seedsForInterface, System.Collections.Generic.List< T >.AddRange(), System.Collections.Generic.List< T >.Clear(), System.Collections.Generic.List< T >.GetEnumerator(), Terraria.GameContent.SecretSeedsTracker.SeedHasSecret(), and System.Collections.Generic.List< T >.Sort().
Referenced by Terraria.GameContent.UI.States.UIWorldCreation.PreparePreviouslyUnlockedSecretSeeds().