Terraria Decompiled: System.Security.AccessControl.RawSecurityDescriptor.ParseSddl
ParseSddl()
void System.Security.AccessControl.RawSecurityDescriptor.ParseSddl (string sddlForm) inline private
Definition at line 191 of file RawSecurityDescriptor.cs.
        {
            ControlFlags controlFlags = ControlFlags.None;
            int i = 0;
            while (i < sddlForm.Length - 2)
            {
                string text = sddlForm.Substring(i, 2);
                if (!(text == "O:"))
                {
                    if (!(text == "G:"))
                    {
                        if (!(text == "D:"))
{
                            if (!(text == "S:"))
{
                                throw new ArgumentException("Invalid SDDL.", "sddlForm");
                            }
                            i += 2;
                            this.SystemAcl = RawAcl.ParseSddlForm(sddlForm, false, ref controlFlags, ref i);
                            controlFlags |= ControlFlags.SystemAclPresent;
                        }
                        else
{
                            i += 2;
                            this.DiscretionaryAcl = RawAcl.ParseSddlForm(sddlForm, true, ref controlFlags, ref i);
                            controlFlags |= ControlFlags.DiscretionaryAclPresent;
                        }
                    }
                    else
                    {
                        i += 2;
                        this.Group = SecurityIdentifier.ParseSddlForm(sddlForm, ref i);
                    }
                }
                else
                {
                    i += 2;
                    this.Owner = SecurityIdentifier.ParseSddlForm(sddlForm, ref i);
                }
            }
            if (i != sddlForm.Length)
            {
                throw new ArgumentException("Invalid SDDL.", "sddlForm");
            }
            this.SetFlags(controlFlags);
        }
References System.Security.AccessControl.RawAcl.ParseSddlForm(), System.Security.Principal.SecurityIdentifier.ParseSddlForm(), System.Security.AccessControl.RawSecurityDescriptor.SetFlags(), and System.text.
Referenced by System.Security.AccessControl.RawSecurityDescriptor.RawSecurityDescriptor().