Terraria Decompiled: Terraria.GameContent.HairstyleUnlocksHelper.RebuildList
RebuildList()
void Terraria.GameContent.HairstyleUnlocksHelper.RebuildList () inline private
Definition at line 41 of file HairstyleUnlocksHelper.cs.
        {
            List<int> availableHairstyles = this.AvailableHairstyles;
            availableHairstyles.Clear();
            if (this._isAtCharacterCreation || this._isAtStylist)
            {
                for (int i = 0; i < 51; i++)
                {
                    availableHairstyles.Add(i);
                }
                availableHairstyles.Add(136);
                availableHairstyles.Add(137);
                availableHairstyles.Add(138);
                availableHairstyles.Add(139);
                availableHairstyles.Add(140);
                availableHairstyles.Add(141);
                availableHairstyles.Add(142);
                availableHairstyles.Add(143);
                availableHairstyles.Add(144);
                availableHairstyles.Add(147);
                availableHairstyles.Add(148);
                availableHairstyles.Add(149);
                availableHairstyles.Add(150);
                availableHairstyles.Add(151);
                availableHairstyles.Add(154);
                availableHairstyles.Add(155);
                availableHairstyles.Add(157);
                availableHairstyles.Add(158);
                availableHairstyles.Add(161);
                for (int j = 51; j < 123; j++)
                {
                    availableHairstyles.Add(j);
                }
                availableHairstyles.Add(134);
                availableHairstyles.Add(135);
                availableHairstyles.Add(146);
                availableHairstyles.Add(152);
                availableHairstyles.Add(153);
                availableHairstyles.Add(156);
                availableHairstyles.Add(159);
                availableHairstyles.Add(165);
                availableHairstyles.Add(160);
                for (int k = 166; k < 228; k++)
                {
                    availableHairstyles.Add(k);
                }
            }
            if (this._isAtStylist)
            {
                if (this._defeatedPlantera)
                {
                    availableHairstyles.Add(162);
                    availableHairstyles.Add(164);
                    availableHairstyles.Add(163);
                    availableHairstyles.Add(145);
                }
                if (this._defeatedMartians)
                {
                    availableHairstyles.AddRange(new int[] { 132, 131, 130, 129, 128, 127, 126, 125, 124, 123 });
                }
                if (this._defeatedMartians && this._defeatedMoonlord)
                {
                    availableHairstyles.Add(133);
                }
            }
        }
References Terraria.GameContent.HairstyleUnlocksHelper._defeatedMartians, Terraria.GameContent.HairstyleUnlocksHelper._defeatedMoonlord, Terraria.GameContent.HairstyleUnlocksHelper._defeatedPlantera, Terraria.GameContent.HairstyleUnlocksHelper._isAtCharacterCreation, Terraria.GameContent.HairstyleUnlocksHelper._isAtStylist, System.Collections.Generic.List< T >.Add(), System.Collections.Generic.List< T >.AddRange(), Terraria.GameContent.HairstyleUnlocksHelper.AvailableHairstyles, and System.Collections.Generic.List< T >.Clear().
Referenced by Terraria.GameContent.HairstyleUnlocksHelper.UpdateUnlocks().