Terraria Decompiled: System.Text.EncoderFallbackBuffer.InternalGetNextChar
InternalGetNextChar()
char System.Text.EncoderFallbackBuffer.InternalGetNextChar () inline package
Definition at line 54 of file EncoderFallbackBuffer.cs.
        {
            char nextChar = this.GetNextChar();
            this.bFallingBack = nextChar > '\0';
            if (nextChar == '\0')
            {
                this.iRecursionCount = 0;
            }
            return nextChar;
        }
References System.Text.EncoderFallbackBuffer.GetNextChar().
Referenced by System.Text.ASCIIEncoding.GetByteCount(), System.Text.Latin1Encoding.GetByteCount(), System.Text.UTF8Encoding.GetByteCount(), System.Text.UnicodeEncoding.GetByteCount(), System.Text.UTF32Encoding.GetByteCount(), System.Text.UTF8Encoding.GetBytes(), System.Text.ASCIIEncoding.GetBytes(), System.Text.Latin1Encoding.GetBytes(), System.Text.UnicodeEncoding.GetBytes(), and System.Text.UTF32Encoding.GetBytes().