Terraria Decompiled: System.Text.EncoderFallbackBuffer.InternalFallback
InternalFallback()
virtual unsafe bool System.Text.EncoderFallbackBuffer.InternalFallback (char ch, ref char * chars) inline package virtual
Definition at line 66 of file EncoderFallbackBuffer.cs.
        {
            int num = (chars - this.charStart) / 2 - 1;
            if (char.IsHighSurrogate(ch))
            {
                if (chars >= this.charEnd)
                {
                    if (this.encoder != null && !this.encoder.MustFlush)
                    {
                        if (this.setEncoder)
{
                            this.bUsedEncoder = true;
                            this.encoder._charLeftOver = ch;
                        }
                        this.bFallingBack = false;
                        return false;
                    }
                }
                else
                {
                    char c = (char)(*chars);
                    if (char.IsLowSurrogate(c))
                    {
                        if (this.bFallingBack)
{
                            int num2 = this.iRecursionCount;
                            this.iRecursionCount = num2 + 1;
                            if (num2 > 250)
{
                                this.ThrowLastCharRecursive(char.ConvertToUtf32(ch, c));
                            }
                        }
                        chars += 2;
                        this.bFallingBack = this.Fallback(ch, c, num);
                        return this.bFallingBack;
                    }
                }
            }
            if (this.bFallingBack)
            {
                int num2 = this.iRecursionCount;
                this.iRecursionCount = num2 + 1;
                if (num2 > 250)
                {
                    this.ThrowLastCharRecursive((int)ch);
                }
            }
            this.bFallingBack = this.Fallback(ch, num);
            return this.bFallingBack;
        }
References System.Text.EncoderFallbackBuffer.bFallingBack, System.Text.EncoderFallbackBuffer.charEnd, System.Text.EncoderFallbackBuffer.charStart, System.Text.EncoderFallbackBuffer.encoder, System.Text.EncoderFallbackBuffer.Fallback(), System.Text.EncoderFallbackBuffer.iRecursionCount, System.Text.EncoderNLS.MustFlush, System.Text.EncoderFallbackBuffer.setEncoder, and System.Text.EncoderFallbackBuffer.ThrowLastCharRecursive().
Referenced by System.Text.ASCIIEncoding.GetByteCount(), System.Text.Latin1Encoding.GetByteCount(), System.Text.UTF8Encoding.GetByteCount(), System.Text.UnicodeEncoding.GetByteCount(), System.Text.UTF32Encoding.GetByteCount(), System.Text.UTF8Encoding.GetBytes(), System.Text.ASCIIEncoding.GetBytes(), System.Text.Latin1Encoding.GetBytes(), System.Text.UnicodeEncoding.GetBytes(), and System.Text.UTF32Encoding.GetBytes().