Terraria Decompiled: Mono.DataConverter.PackContext.Add
Add()
void Mono.DataConverter.PackContext.Add (byte[] group) inline
Definition at line 920 of file DataConverter.cs.
            {
                if (this.buffer == null)
                {
                    this.buffer = group;
                    this.next = group.Length;
                    return;
                }
                if (this.align != 0)
                {
                    if (this.align == -1)
                    {
                        this.next = DataConverter.Align(this.next, group.Length);
                    }
                    else
                    {
                        this.next = DataConverter.Align(this.next, this.align);
                    }
                    this.align = 0;
                }
                if (this.next + group.Length > this.buffer.Length)
                {
                    byte[] array = new byte[Math.Max(this.next, 16) * 2 + group.Length];
                    Array.Copy(this.buffer, array, this.buffer.Length);
                    Array.Copy(group, 0, array, this.next, group.Length);
                    this.next += group.Length;
                    this.buffer = array;
                    return;
                }
                Array.Copy(group, 0, this.buffer, this.next, group.Length);
                this.next += group.Length;
            }
References Mono.DataConverter.Align(), Mono.DataConverter.PackContext.align, System.array, Mono.DataConverter.PackContext.buffer, System.Array.Copy(), System.Math.Max(), and Mono.DataConverter.PackContext.next.