Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.Features.DungeonTileClump.TileClump
TileClump()
bool Terraria.GameContent.Generation.Dungeon.Features.DungeonTileClump.TileClump (DungeonData data, int i, int j, double strength, int steps, int tileType = -1, int wallType = -1, bool generating = false) inline
Definition at line 34 of file DungeonTileClump.cs.
        {
            DungeonTileClumpSettings dungeonTileClumpSettings = (DungeonTileClumpSettings)this.settings;
            UnifiedRandom unifiedRandom = new UnifiedRandom(dungeonTileClumpSettings.RandomSeed);
            ushort? onlyReplaceThisTileType = dungeonTileClumpSettings.OnlyReplaceThisTileType;
            ushort? onlyReplaceThisWallType = dungeonTileClumpSettings.OnlyReplaceThisWallType;
            double num = strength;
            double num2 = (double)steps;
            Vector2D vector2D;
            vector2D.X = (double)i;
            vector2D.Y = (double)j;
            Vector2D vector2D2;
            vector2D2.X = (double)unifiedRandom.Next(-10, 11) * 0.1;
            vector2D2.Y = (double)unifiedRandom.Next(-10, 11) * 0.1;
            this.Bounds.SetBounds(i, j, i, j);
            while (num > 0.0 && num2 > 0.0)
            {
                if (vector2D.Y < 0.0 && num2 > 0.0 && tileType == 59)
                {
                    num2 = 0.0;
                }
                num = strength * (num2 / (double)steps);
                num2 -= 1.0;
                int num3 = Math.Max(0, Math.Min(Main.maxTilesX, (int)(vector2D.X - num * 0.5)));
                int num4 = Math.Max(0, Math.Min(Main.maxTilesX, (int)(vector2D.X + num * 0.5)));
                int num5 = Math.Max(0, Math.Min(Main.maxTilesY, (int)(vector2D.Y - num * 0.5)));
                int num6 = Math.Max(0, Math.Min(Main.maxTilesY, (int)(vector2D.Y + num * 0.5)));
                this.Bounds.UpdateBounds(num3, num4, num5, num6);
                if (generating)
                {
                    for (int k = num3; k < num4; k++)
                    {
                        for (int l = num5; l < num6; l++)
{
                            if (Math.Abs((double)k - vector2D.X) + Math.Abs((double)l - vector2D.Y) < strength * 0.5 * (1.0 + (double)unifiedRandom.Next(-10, 11) * 0.015) && (dungeonTileClumpSettings.AreaToGenerateIn == null || dungeonTileClumpSettings.AreaToGenerateIn.Contains(k, l)))
{
                                Tile tile = Main.tile[k, l];
                                if (!tile.active() || (!tile.actuator() && !tile.anyWire()))
{
                                    if (tileType != -1 && tile.active())
{
                                        if (onlyReplaceThisTileType != null && tile.type != onlyReplaceThisTileType.Value)
{
                                            goto IL_02C8;
                                        }
                                        Main.tile[k, l].type = (ushort)tileType;
                                        WorldGen.paintTile(k, l, 0, false, false);
                                    }
                                    if (wallType != -1 && (onlyReplaceThisWallType == null || tile.wall == onlyReplaceThisWallType.Value))
{
                                        Main.tile[k, l].wall = (ushort)wallType;
                                        WorldGen.paintWall(k, l, 0, false, false);
                                    }
                                }
                            }
                            IL_02C8:;
                        }
                    }
                }
                vector2D += vector2D2;
                vector2D2.X += (double)((float)unifiedRandom.Next(-10, 11) * 0.05f);
                if (vector2D2.X > 1.0)
                {
                    vector2D2.X = 1.0;
                }
                if (vector2D2.X < -1.0)
                {
                    vector2D2.X = -1.0;
                }
            }
            this.Bounds.CalculateHitbox();
            return true;
        }
References System.Math.Abs(), Terraria.Tile.active(), Terraria.Tile.actuator(), Terraria.Tile.anyWire(), Terraria.GameContent.Generation.Dungeon.Features.DungeonTileClumpSettings.AreaToGenerateIn, Terraria.GameContent.Generation.Dungeon.Features.DungeonFeature.Bounds, Terraria.GameContent.Generation.Dungeon.DungeonBounds.CalculateHitbox(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.Contains(), System.Math.Max(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, System.Math.Min(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.GameContent.Generation.Dungeon.Features.DungeonTileClumpSettings.OnlyReplaceThisTileType, Terraria.GameContent.Generation.Dungeon.Features.DungeonTileClumpSettings.OnlyReplaceThisWallType, Terraria.WorldGen.paintTile(), Terraria.WorldGen.paintWall(), Terraria.GameContent.Generation.Dungeon.Features.DungeonTileClumpSettings.RandomSeed, Terraria.GameContent.Generation.Dungeon.DungeonBounds.SetBounds(), Terraria.GameContent.Generation.Dungeon.Features.DungeonFeature.settings, Terraria.Main.tile, Terraria.Tile.type, Terraria.GameContent.Generation.Dungeon.DungeonBounds.UpdateBounds(), Terraria.Tile.wall, ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.GameContent.Generation.Dungeon.Features.DungeonTileClump.GenerateFeature().