Terraria Decompiled: Terraria.GameContent.TextureAssets.Item
Item
Asset<Texture2D> [] Terraria.GameContent.TextureAssets.Item = new Asset<Texture2D>[(int)ItemID.Count] static
Definition at line 534 of file TextureAssets.cs.
Referenced by Terraria.Main.DrawInterface_40_InteractItemIcon(), Terraria.Main.DrawItem(), Terraria.Main.DrawItem_GetBasics(), Terraria.UI.ItemSlot.DrawItemIcon(), Terraria.Main.DrawNPCExtras(), Terraria.Main.DrawPaladinsShieldBoundary(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_27_HeldItem(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_30_BladedGlove(), Terraria.Main.DrawProj_PiercingStarlight(), Terraria.Main.DrawProjDirect(), Terraria.Main.DrawProjWithStarryTrail(), Terraria.GameContent.UI.CustomCurrencySingleCoin.DrawSavingsMoney(), Terraria.GameContent.UI.Elements.UIDynamicItemCollection< TEntry >.DrawSelf(), Terraria.GameContent.Drawing.TileDrawing.DrawSpecialTilesLegacy(), Terraria.Main.DrawSplash_LoadingStar(), Terraria.Main.DrawWallOfFish(), Terraria.Item.GetDrawHitbox(), Terraria.Main.GetItemDrawFrame(), Terraria.Player.GetItemDrawFrame(), Terraria.Main.LoadContent_Deferred(), Terraria.Main.LoadItem(), Terraria.Initializers.AssetInitializer.LoadSplashAssets(), Terraria.Initializers.AssetInitializer.LoadTextures(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_SkeletonMerchantSearchesThroughBones(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_SantaItemExample(), and Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_PaladinsShieldHit().