Terraria Decompiled: Terraria.DataStructures.ArmorSetBonus.QueryCount
QueryCount()
ArmorSetBonus.QueryResult Terraria.DataStructures.ArmorSetBonus.QueryCount (ArmorSetBonus::QueryContext context) inline
Definition at line 28 of file ArmorSetBonus.cs.
        {
            ArmorSetBonus.QueryResult queryResult = default(ArmorSetBonus.QueryResult);
            this.TryCounting(context.HeadItem, this.Head, ref queryResult.ItemsFound, ref queryResult.ItemsNeeded);
            this.TryCounting(context.BodyItem, this.Body, ref queryResult.ItemsFound, ref queryResult.ItemsNeeded);
            this.TryCounting(context.LegItem, this.Legs, ref queryResult.ItemsFound, ref queryResult.ItemsNeeded);
            return queryResult;
        }
References Terraria.DataStructures.ArmorSetBonus.QueryResult.ItemsFound, Terraria.DataStructures.ArmorSetBonus.QueryResult.ItemsNeeded, and Terraria.DataStructures.ArmorSetBonus.TryCounting().
Referenced by Terraria.DataStructures.ArmorSetBonuses.GetCompleteSet(), and Terraria.Main.MouseText_DrawItemTooltip_GetLinesInfo().