Terraria Decompiled: Terraria.GameContent.TextureAssets.Extra
Extra
Asset<Texture2D> [] Terraria.GameContent.TextureAssets.Extra = new Asset<Texture2D>[(int)ExtrasID.Count] static
Definition at line 558 of file TextureAssets.cs.
Referenced by Terraria.GameContent.Animations.StardewValleyAnimation.ComposeAnimation(), Terraria.GameContent.Golf.FancyGolfPredictionLine.Draw(), Terraria.Mount.Draw(), Terraria.GameContent.Animations.Segments.EmoteSegment.Draw(), Terraria.Map.TeamBasedSpawnMapLayer.Draw(), Terraria.Map.TeleportPylonsMapLayer.Draw(), Terraria.Graphics.Renderers.BloodyExplosionParticle.Draw(), Terraria.Graphics.Renderers.PrettySparkleParticle.Draw(), Terraria.Graphics.Renderers.ShockIconParticle.Draw(), Terraria.GameContent.UI.EmoteBubble.Draw(), Terraria.GameContent.Events.ScreenObstruction.Draw(), Terraria.UI.ItemSlot.Draw(), Terraria.Graphics.Renderers.LittleFlyingCritterParticle.Draw_ButterFly(), Terraria.Graphics.Renderers.LittleFlyingCritterParticle.Draw_Fly(), Terraria.DataStructures.PlayerDrawLayers.DrawCompositeArmorPiece(), Terraria.Main.DrawDefenseCounter(), Terraria.Main.DrawElderEye(), Terraria.Main.DrawInterface_1_2_DrawEntityMarkersInWorld(), Terraria.Main.DrawInterface_3_LaserRuler(), Terraria.Main.DrawInterface_4_Ruler(), Terraria.Main.DrawInvasionProgress(), Terraria.Main.DrawInventory(), Terraria.Main.DrawItem(), Terraria.UI.ItemSlot.DrawItemIcon(), Terraria.PopupText.DrawItemTextPopups(), Terraria.Main.DrawKite(), Terraria.Main.DrawLoadoutButtons(), Terraria.Main.DrawMapIcons_LastGolfballHit(), Terraria.Main.DrawMapIcons_PotionOfReturnAppearAfterUsePosition(), Terraria.Main.DrawMapIcons_PotionOfReturnHomePosition(), Terraria.GameContent.Drawing.TileDrawing.DrawMasterTrophies(), Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileVinesInWind(), Terraria.Main.DrawNPCDirect(), Terraria.Main.DrawNPCDirect_Deerclops(), Terraria.Main.DrawNPCDirect_HallowBoss(), Terraria.Main.DrawNPCDirect_QueenSlimeWings(), Terraria.Main.DrawNPCExtras(), Terraria.Main.DrawPaladinsShieldBoundary(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_01_2_JimsCloak(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_01_FaceSkin(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_03_PortableStool(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_05_2_SafemanSun(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_05_ForbiddenSetRing(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_06_NormalHats(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_06_WebbedDebuffBack(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_08_Backpacks(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_08_FaceAcc(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_09_Wings(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_12_Skin_Composite(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_12_SkinComposite_BackArmShirt(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_13_Leggings(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_17_TorsoComposite(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_21_Head(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_21_Head_TheFace(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_22_FaceAcc(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_26_SolarShield(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_27_HeldItem(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_28_ArmOverItemComposite(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_33_FrozenOrWebbedDebuff(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_ChippysHeadband(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_JimsDroneRadio(), Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayerStoned(), Terraria.Main.DrawPrettyStarSparkle(), Terraria.Main.DrawProj_FairyQueenLance(), Terraria.Main.DrawProj_FlailChains(), Terraria.Main.DrawProj_FlailChains_Old(), Terraria.Main.DrawProj_Spear(), Terraria.Main.DrawProj_StardustGuardianPunching(), Terraria.Main.DrawProjDirect(), Terraria.Main.DrawProjWithStarryTrail(), Terraria.GameContent.UI.Elements.UIResourcePack.DrawSelf(), Terraria.GameContent.Drawing.TileDrawing.DrawSpecialTilesLegacy(), Terraria.Main.DrawSunAndMoon(), Terraria.GameContent.Drawing.TileDrawing.DrawTeleportationPylons(), Terraria.DataStructures.PlayerDrawLayers.DrawTiedBalloons(), Terraria.GameContent.PotionOfReturnGateHelper.DrawToDrawData(), Terraria.GameContent.VoidLensHelper.DrawToDrawData(), Terraria.Main.DrawTorchBiomeSwapIcon(), Terraria.Graphics.Capture.CaptureInterface.ModeChangeSettings.DrawWaterChoices(), Terraria.DataStructures.RichRoomCheckFeedback.EndScoring(), Terraria.DataStructures.RichRoomCheckFeedback.EndSpread(), Terraria.GameContent.Skies.MartianSky.GenerateUfos(), Terraria.GameContent.Animations.Segments.EmoteSegment.GetFrame(), Terraria.GameContent.PlayerQueenSlimeMountTextureContent.HandleUseRequest(), Terraria.GameContent.PlayerRainbowWingsTextureContent.HandleUseRequest(), Terraria.Mount.Initialize(), Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem.LoadTextures(), Terraria.GameContent.UI.Elements.UIWorkshopPublishResourcePackListItem.LoadTextures(), Terraria.GameContent.UI.Elements.UIWorkshopPublishWorldListItem.LoadTextures(), Terraria.Initializers.AssetInitializer.LoadTextures(), Terraria.GameContent.Skies.LanternSky.OnLoad(), Terraria.GameContent.Skies.PartySky.OnLoad(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_ClothierChasingTruffle(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_DryadTurningToTree(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_AnglerAndPirateTalkAboutFish(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_DemolitionistAndArmsDealerArguingThenNurseComes(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_DryadSayingByeToTavernKeep(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_GuideRunningFromZombie(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_MerchantAndTravelingMerchantTryingToSellJunk(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_SantaAndTaxCollectorThrowingPresents(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_SkeletonMerchantSearchesThroughBones(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_SteampunkerRepairingCyborg(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_WitchDoctorGoingToHisPeople(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_WizardPartyGirlDyeTraderAndPainterPartyWithBunnies(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_ZoologistAndPetsAnnoyGolfer(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_GuideEmotingAtRainbowPanel(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_PrincessAndEveryoneThanksPlayer(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_TinkererAndMechanic(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsBarrelExplosion(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsHeadEffect(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsMushroomBoiExplosion(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_Keybrand(), and Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_MoonLordWhipEye().