Terraria Decompiled: Terraria.GameContent.UI.NPCChatPanel.OverrideChatTextWithShenanigans
OverrideChatTextWithShenanigans()
void Terraria.GameContent.UI.NPCChatPanel.OverrideChatTextWithShenanigans (ref string chatTextToShow) inline private
Definition at line 203 of file NPCChatPanel.cs.
        {
            object obj = this.LocalPlayer.talkNPC != -1 && Main.CanDryadPlayStardewAnimation(this.LocalPlayer, Main.npc[this.LocalPlayer.talkNPC]);
            int num = 24;
            if (this.LocalPlayer.talkNPC != -1 && Main.npc[this.LocalPlayer.talkNPC].ai[0] == (float)num && NPC.RerollDryadText == 2)
            {
                NPC.RerollDryadText = 1;
            }
            object obj2 = obj;
            if (obj2 != null && NPC.RerollDryadText == 1 && Main.npc[this.LocalPlayer.talkNPC].ai[0] != (float)num && this.LocalPlayer.talkNPC != -1 && Main.npc[this.LocalPlayer.talkNPC].active && Main.npc[this.LocalPlayer.talkNPC].type == 20)
            {
                NPC.RerollDryadText = 0;
                chatTextToShow = (Main.npcChatText = Main.npc[this.LocalPlayer.talkNPC].GetChat());
                NPC.PreventJojaColaDialog = true;
            }
            if (obj2 != null && !NPC.PreventJojaColaDialog)
            {
                chatTextToShow = Language.GetTextValue("StardewTalk.PlayerHasColaAndIsHoldingIt");
            }
        }
References Terraria.NPC.active, Terraria.NPC.ai, Terraria.Main.CanDryadPlayStardewAnimation(), Terraria.NPC.GetChat(), Terraria.Localization.Language.GetTextValue(), Terraria.GameContent.UI.NPCChatPanel.LocalPlayer, Terraria.Main.npc, System.obj, Terraria.NPC.PreventJojaColaDialog, Terraria.NPC.RerollDryadText, Terraria.Player.talkNPC, and Terraria.NPC.type.
Referenced by Terraria.GameContent.UI.NPCChatPanel.PrepareText().