Terraria Decompiled: Terraria.GameContent.UI.NPCChatPanel.Draw
Draw()
void Terraria.GameContent.UI.NPCChatPanel.Draw () inline
Definition at line 61 of file NPCChatPanel.cs.
        {
            if (!this.CanHoldConversation())
            {
                this.Close();
                return;
            }
            this.PrepareText();
            this.PrepareInteractions();
            this.PrepareVirtualKeyboard();
            Color color = new Color(200, 200, 200, 200);
            int num = (int)((this.mouseTextColor * 2 + byte.MaxValue) / 3);
            Color color2 = new Color(num, num, num, num);
            Point point = new Point(500, 500);
            Rectangle rectangle = new Rectangle(Main.screenWidth / 2 - point.X / 2, 100, point.X, 30);
            rectangle.Height += 30 * this._textDisplayCache.AmountOfLines;
            rectangle.Height += 30 * this._neededInteractionLines + Math.Max(0, 2 * (this._neededInteractionLines - 1));
            Utils.DrawInvBG(Main.spriteBatch, rectangle, default(Color));
            this.DrawText(color2, rectangle);
            Main.DrawNPCPortrait(color, rectangle.TopLeft());
            Main.DrawNPCChatBottomRightItem(rectangle.BottomRight());
            if (!PlayerInput.IgnoreMouseInterface && rectangle.Contains(new Point(Main.mouseX, Main.mouseY)))
            {
                this.LocalPlayer.mouseInterface = true;
            }
            this.DrawButtons(rectangle, color2);
        }
References Terraria.GameContent.UI.NPCChatPanel._neededInteractionLines, Terraria.GameContent.UI.NPCChatPanel._textDisplayCache, Terraria.GameContent.UI.TextDisplayCache.AmountOfLines, Terraria.GameContent.UI.NPCChatPanel.CanHoldConversation(), Terraria.GameContent.UI.NPCChatPanel.Close(), Microsoft.Xna.Framework.Rectangle.Contains(), Terraria.GameContent.UI.NPCChatPanel.DrawButtons(), Terraria.Utils.DrawInvBG(), Terraria.Main.DrawNPCChatBottomRightItem(), Terraria.Main.DrawNPCPortrait(), Terraria.GameContent.UI.NPCChatPanel.DrawText(), Terraria.GameInput.PlayerInput.IgnoreMouseInterface, int, System.Math.Max(), Terraria.GameContent.UI.NPCChatPanel.mouseTextColor, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.GameContent.UI.NPCChatPanel.PrepareInteractions(), Terraria.GameContent.UI.NPCChatPanel.PrepareText(), Terraria.GameContent.UI.NPCChatPanel.PrepareVirtualKeyboard(), Terraria.Main.screenWidth, Terraria.Main.spriteBatch, and Microsoft.Xna.Framework.Point.X.