Terraria Decompiled: Terraria.GameContent.UI.NPCChatPanel.DrawButtons
DrawButtons()
void Terraria.GameContent.UI.NPCChatPanel.DrawButtons (Rectangle panelArea, Color chatColor) inline private
Definition at line 90 of file NPCChatPanel.cs.
        {
            UILinkPointNavigator.Shortcuts.NPCCHAT_ButtonsNew = true;
            UILinkPointNavigator.Shortcuts.NPCCHAT_ButtonsCount = this._interactions.Count;
            DynamicSpriteFont value = FontAssets.MouseText.Value;
            Vector2 vector = panelArea.BottomLeft() + new Vector2(30f, (float)(-22 * this._neededInteractionLines + Math.Max(0, 2 * (this._neededInteractionLines - 1)) - 4));
            int num = -1;
            int num2 = -1;
            float num3 = 0.9f;
            Rectangle rectangle = new Rectangle((int)vector.X, (int)vector.Y, 100, 22);
            foreach (NPCInteraction npcinteraction in this._interactions)
            {
                num++;
                byte mouseTextColor = this.mouseTextColor;
                chatColor = new Color((int)mouseTextColor, (int)((double)mouseTextColor / 1.1), (int)(mouseTextColor / 2), (int)mouseTextColor);
                if (num % 4 == 0)
                {
                    rectangle.X = (int)vector.X;
                    rectangle.Y = num / 4 * 22 + (int)vector.Y;
                }
                string text = npcinteraction.GetText();
                int num4 = 0;
                bool flag = npcinteraction.TryAddCoins(ref chatColor, out num4);
                float num5 = 1f;
                Vector2 vector2 = ChatManager.GetStringSize(value, text, new Vector2(num3), -1f);
                if (vector2.X > 260f)
                {
                    num5 *= 260f / vector2.X;
                }
                rectangle.Width = (int)(vector2.X * num5);
                bool flag2 = rectangle.Contains(new Point(Main.mouseX, Main.mouseY));
                Vector2 vector3 = new Vector2(flag2 ? 1.2f : num3);
                Vector2 vector4 = new Vector2(0f, vector2.Y * 0.5f);
                Color color = (flag2 ? Color.Brown : Color.Black);
                Vector2 vector5 = new Vector2((float)rectangle.Left, (float)rectangle.Center.Y);
                if (flag2)
                {
                    vector5.X -= (float)((int)((1.2f - num3) * (float)rectangle.Width * 0.5f));
                    vector2 *= 1.2f / num3;
                }
                if (flag2)
                {
                    num2 = num;
                }
                ChatManager.DrawColorCodedStringShadow(Main.spriteBatch, value, text, vector5, color, 0f, vector4, vector3 * num5, -1f, 2f);
                ChatManager.DrawColorCodedString(Main.spriteBatch, value, text, vector5, chatColor, 0f, vector4, vector3 * num5, -1f, false);
                UILinkPointNavigator.SetPosition(2500 + num, rectangle.Center.ToVector2());
                rectangle.X += rectangle.Width + 30;
                if (npcinteraction.ShowExcalmation)
                {
                    Utils.DrawNotificationIcon(Main.spriteBatch, vector5 + new Vector2(vector2.X * num5, 0f) + new Vector2(8f, 0f), 0f, false);
                }
                if (flag)
                {
                    ItemSlot.DrawMoney(Main.spriteBatch, "", (float)(rectangle.X - 45), (float)(rectangle.Y - 44), Utils.CoinsSplit((long)num4), true, false);
                    rectangle.X += 106;
                }
                if (!PlayerInput.IgnoreMouseInterface && flag2)
                {
                    this.LocalPlayer.mouseInterface = true;
                    this.LocalPlayer.releaseUseItem = false;
                    num2 = num;
                    if (Main.mouseLeft && Main.mouseLeftRelease)
                    {
                        Main.mouseLeftRelease = false;
                        npcinteraction.Interact();
                    }
                }
            }
            if (this._lastHovered != num2 && (!PlayerInput.UsingGamepad || num2 != -1))
            {
                SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
            }
            this._lastHovered = num2;
        }
References Terraria.GameContent.UI.NPCChatPanel._interactions, Terraria.GameContent.UI.NPCChatPanel._lastHovered, Terraria.GameContent.UI.NPCChatPanel._neededInteractionLines, Microsoft.Xna.Framework.Color.Black, Terraria.Utils.CoinsSplit(), Terraria.UI.Chat.ChatManager.DrawColorCodedString(), Terraria.UI.Chat.ChatManager.DrawColorCodedStringShadow(), Terraria.UI.ItemSlot.DrawMoney(), Terraria.Utils.DrawNotificationIcon(), Terraria.UI.Chat.ChatManager.GetStringSize(), Terraria.GameContent.NPCInteraction.GetText(), Terraria.GameInput.PlayerInput.IgnoreMouseInterface, int, Terraria.GameContent.NPCInteraction.Interact(), System.Math.Max(), Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.GameContent.FontAssets.MouseText, Terraria.GameContent.UI.NPCChatPanel.mouseTextColor, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Audio.SoundEngine.PlaySound(), Terraria.UI.Gamepad.UILinkPointNavigator.SetPosition(), Terraria.GameContent.NPCInteraction.ShowExcalmation, Terraria.Main.spriteBatch, System.text, Terraria.GameContent.NPCInteraction.TryAddCoins(), Terraria.GameInput.PlayerInput.UsingGamepad, System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.GameContent.UI.NPCChatPanel.Draw().