Terraria Decompiled: Terraria.GameContent.UI.NPCChatPanel.DrawText
DrawText()
void Terraria.GameContent.UI.NPCChatPanel.DrawText (Color textColor, Rectangle textArea) inline private
Definition at line 225 of file NPCChatPanel.cs.
        {
            Vector2 vector = textArea.TopLeft() + new Vector2(20f, 20f);
            DynamicSpriteFont value = FontAssets.MouseText.Value;
            string[] textLines = this._textDisplayCache.TextLines;
            int amountOfLines = this._textDisplayCache.AmountOfLines;
            for (int i = 0; i < amountOfLines; i++)
            {
                string text = textLines[i];
                if (text != null)
                {
                    if (this.allowRichText)
                    {
                        ChatManager.DrawColorCodedStringWithShadow(Main.spriteBatch, value, text, vector + new Vector2(0f, (float)(i * 30)), textColor, 0f, Vector2.Zero, Vector2.One, -1f, 2f);
                    }
                    else
                    {
                        Utils.DrawBorderStringFourWay(Main.spriteBatch, value, text, vector.X, vector.Y + (float)(i * 30), textColor, Color.Black, Vector2.Zero, 1f);
                    }
                }
            }
            if (!Main.editSign || textLines[amountOfLines - 1] == null)
            {
                return;
            }
            Vector2 vector2 = vector + new Vector2(0f, (float)((amountOfLines - 1) * 30));
            vector2.X += value.MeasureString(textLines[amountOfLines - 1]).X;
            string compositionString = Platform.Get<IImeService>().CompositionString;
            if (compositionString != null && compositionString.Length > 0)
            {
                float x = value.MeasureString(compositionString).X;
                if (x + vector2.X - vector.X > 460f)
                {
                    vector2 = vector + new Vector2(0f, (float)(amountOfLines * 30));
                }
                ChatManager.DrawColorCodedStringWithShadow(Main.spriteBatch, value, compositionString, vector2, Main.imeCompositionStringColor, 0f, Vector2.Zero, Vector2.One, -1f, 2f);
                Main.instance.SetIMEPanelAnchor(vector2 + new Vector2(0f, 54f), 0f);
                vector2.X += x;
            }
            int num = this.textBlinkerCount + 1;
            this.textBlinkerCount = num;
            if (num >= 20)
            {
                this.textBlinkerState = ((this.textBlinkerState == 0) ? 1 : 0);
                this.textBlinkerCount = 0;
            }
            if (this.textBlinkerState == 1)
            {
                ChatManager.DrawColorCodedStringWithShadow(Main.spriteBatch, value, "|", vector2, textColor, 0f, Vector2.Zero, Vector2.One, -1f, 2f);
            }
        }
References Terraria.GameContent.UI.NPCChatPanel._textDisplayCache, Terraria.GameContent.UI.NPCChatPanel.allowRichText, Terraria.GameContent.UI.TextDisplayCache.AmountOfLines, Microsoft.Xna.Framework.Color.Black, Terraria.Utils.DrawBorderStringFourWay(), Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.Main.editSign, Terraria.Main.imeCompositionStringColor, Terraria.Main.instance, Terraria.GameContent.FontAssets.MouseText, Microsoft.Xna.Framework.Vector2.One, Terraria.Main.SetIMEPanelAnchor(), Terraria.Main.spriteBatch, System.text, Terraria.GameContent.UI.NPCChatPanel.textBlinkerState, Terraria.GameContent.UI.TextDisplayCache.TextLines, System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.UI.NPCChatPanel.Draw().