Terraria Decompiled: System.Threading.WaitHandle.SignalAndWait
SignalAndWait() [2/3]
static bool System.Threading.WaitHandle.SignalAndWait (WaitHandle toSignal, WaitHandle toWaitOn, int millisecondsTimeout, bool exitContext) inline static
Definition at line 368 of file WaitHandle.cs.
        {
            if (toSignal == null)
            {
                throw new ArgumentNullException("toSignal");
            }
            if (toWaitOn == null)
            {
                throw new ArgumentNullException("toWaitOn");
            }
            if (-1 > millisecondsTimeout)
            {
                throw new ArgumentOutOfRangeException("millisecondsTimeout", Environment.GetResourceString("Number must be either non-negative and less than or equal to Int32.MaxValue or -1."));
            }
            int num = WaitHandle.SignalAndWaitOne(toSignal.safeWaitHandle, toWaitOn.safeWaitHandle, millisecondsTimeout, toWaitOn.hasThreadAffinity, exitContext);
            if (2147483647 != num && toSignal.hasThreadAffinity)
            {
                Thread.EndCriticalRegion();
                Thread.EndThreadAffinity();
            }
            if (128 == num)
            {
                WaitHandle.ThrowAbandonedMutexException();
            }
            if (298 == num)
            {
                throw new InvalidOperationException(Environment.GetResourceString("The WaitHandle cannot be signaled because it would exceed its maximum count."));
            }
            if (299 == num)
            {
                throw new ApplicationException("Attempt to release mutex not owned by caller");
            }
            return num == 0;
        }
References System.Threading.Thread.EndCriticalRegion(), System.Threading.Thread.EndThreadAffinity(), System.Environment.GetResourceString(), System.Threading.WaitHandle.hasThreadAffinity, System.Threading.WaitHandle.safeWaitHandle, System.Threading.WaitHandle.SignalAndWaitOne(), and System.Threading.WaitHandle.ThrowAbandonedMutexException().