Terraria Decompiled: System.Threading.WaitHandle.WaitOneWithoutFAS
WaitOneWithoutFAS()
bool System.Threading.WaitHandle.WaitOneWithoutFAS () inline package
Definition at line 177 of file WaitHandle.cs.
        {
            if (this.safeWaitHandle == null)
            {
                throw new ObjectDisposedException(null, Environment.GetResourceString("Cannot access a disposed object."));
            }
            long num = -1L;
            int num2 = WaitHandle.WaitOneNative(this.safeWaitHandle, (uint)num, this.hasThreadAffinity, false);
            if (num2 == 128)
            {
                WaitHandle.ThrowAbandonedMutexException();
            }
            return num2 != 258 && num2 != int.MaxValue;
        }
References System.Environment.GetResourceString(), System.Threading.WaitHandle.hasThreadAffinity, System.L, System.Threading.WaitHandle.safeWaitHandle, System.Threading.WaitHandle.ThrowAbandonedMutexException(), and System.Threading.WaitHandle.WaitOneNative().