Terraria Decompiled: System.Threading.WaitHandle.WaitAny
WaitAny() [3/5]
static int System.Threading.WaitHandle.WaitAny (WaitHandle[] waitHandles, int millisecondsTimeout, bool exitContext) inline static
Definition at line 267 of file WaitHandle.cs.
        {
            if (waitHandles == null)
            {
                throw new ArgumentNullException(Environment.GetResourceString("The waitHandles parameter cannot be null."));
            }
            if (waitHandles.Length == 0)
            {
                throw new ArgumentException(Environment.GetResourceString("Waithandle array may not be empty."));
            }
            if (64 < waitHandles.Length)
            {
                throw new NotSupportedException(Environment.GetResourceString("The number of WaitHandles must be less than or equal to 64."));
            }
            if (-1 > millisecondsTimeout)
            {
                throw new ArgumentOutOfRangeException("millisecondsTimeout", Environment.GetResourceString("Number must be either non-negative and less than or equal to Int32.MaxValue or -1."));
            }
            WaitHandle[] array = new WaitHandle[waitHandles.Length];
            for (int i = 0; i < waitHandles.Length; i++)
            {
                WaitHandle waitHandle = waitHandles[i];
                if (waitHandle == null)
                {
                    throw new ArgumentNullException(Environment.GetResourceString("At least one element in the specified array was null."));
                }
                if (RemotingServices.IsTransparentProxy(waitHandle))
                {
                    throw new InvalidOperationException(Environment.GetResourceString("Cannot wait on a transparent proxy."));
                }
                array[i] = waitHandle;
            }
            int num = WaitHandle.WaitMultiple(array, millisecondsTimeout, exitContext, false);
            if (128 <= num && 128 + array.Length > num)
            {
                int num2 = num - 128;
                if (0 <= num2 && num2 < array.Length)
                {
                    WaitHandle.ThrowAbandonedMutexException(num2, array[num2]);
                }
                else
                {
                    WaitHandle.ThrowAbandonedMutexException();
                }
            }
            GC.KeepAlive(array);
            return num;
        }
References System.array, System.Environment.GetResourceString(), System.Runtime.Remoting.RemotingServices.IsTransparentProxy(), System.GC.KeepAlive(), System.Threading.WaitHandle.ThrowAbandonedMutexException(), System.Threading.WaitHandle.waitHandle, and System.Threading.WaitHandle.WaitMultiple().
Referenced by System.Threading.RegisteredWaitHandle.Wait(), System.Threading.WaitHandle.WaitAny(), System.Threading.WaitHandle.WaitAny(), System.Threading.WaitHandle.WaitAny(), and System.Threading.WaitHandle.WaitAny().