Terraria Decompiled: System.Threading.WaitHandle.WaitMultiple
WaitMultiple()
static unsafe int System.Threading.WaitHandle.WaitMultiple (WaitHandle[] waitHandles, int millisecondsTimeout, bool exitContext, bool WaitAll) inline static private
Definition at line 477 of file WaitHandle.cs.
        {
            if (waitHandles.Length > 64)
            {
                return int.MaxValue;
            }
            int num = -1;
            SynchronizationContext synchronizationContext = SynchronizationContext.Current;
            int num2;
            try
            {
                if (exitContext)
                {
                    SynchronizationAttribute.ExitContext();
                }
                for (int i = 0; i < waitHandles.Length; i++)
                {
                    try
                    {
                    }
                    finally
                    {
                        bool flag = false;
                        waitHandles[i].SafeWaitHandle.DangerousAddRef(ref flag);
                        num = i;
                    }
                }
                if (synchronizationContext != null && synchronizationContext.IsWaitNotificationRequired())
                {
                    IntPtr[] array = new IntPtr[waitHandles.Length];
                    for (int j = 0; j < waitHandles.Length; j++)
                    {
                        array[j] = waitHandles[j].SafeWaitHandle.DangerousGetHandle();
                    }
                    num2 = synchronizationContext.Wait(array, false, millisecondsTimeout);
                }
                else
                {
                    IntPtr* ptr;
                    checked
                    {
                        ptr = stackalloc IntPtr[unchecked((UIntPtr)waitHandles.Length) * (UIntPtr)sizeof(IntPtr)];
                    }
                    for (int k = 0; k < waitHandles.Length; k++)
                    {
                        ptr[k] = waitHandles[k].SafeWaitHandle.DangerousGetHandle();
                    }
                    num2 = WaitHandle.Wait_internal(ptr, waitHandles.Length, WaitAll, millisecondsTimeout);
                }
            }
            finally
            {
                for (int l = num; l >= 0; l--)
                {
                    waitHandles[l].SafeWaitHandle.DangerousRelease();
                }
                if (exitContext)
                {
                    SynchronizationAttribute.EnterContext();
                }
            }
            return num2;
        }
References System.array, System.Threading.SynchronizationContext.Current, System.Runtime.InteropServices.SafeHandle.DangerousAddRef(), System.Runtime.InteropServices.SafeHandle.DangerousGetHandle(), System.Runtime.InteropServices.SafeHandle.DangerousRelease(), System.Runtime.Remoting.Contexts.SynchronizationAttribute.EnterContext(), System.Runtime.Remoting.Contexts.SynchronizationAttribute.ExitContext(), System.Threading.SynchronizationContext.IsWaitNotificationRequired(), System.Threading.WaitHandle.SafeWaitHandle, System.Threading.SynchronizationContext.Wait(), System.Threading.WaitHandle.Wait_internal(), and System.Threading.WaitHandle.WaitAll().
Referenced by System.Threading.WaitHandle.WaitAll(), and System.Threading.WaitHandle.WaitAny().