Terraria Decompiled: System.Threading.WaitHandle.WaitAll
WaitAll() [3/5]
static bool System.Threading.WaitHandle.WaitAll (WaitHandle[] waitHandles, int millisecondsTimeout, bool exitContext) inline static
Definition at line 194 of file WaitHandle.cs.
        {
            if (waitHandles == null)
            {
                throw new ArgumentNullException(Environment.GetResourceString("The waitHandles parameter cannot be null."));
            }
            if (waitHandles.Length == 0)
            {
                throw new ArgumentNullException(Environment.GetResourceString("Waithandle array may not be empty."));
            }
            if (waitHandles.Length > 64)
            {
                throw new NotSupportedException(Environment.GetResourceString("The number of WaitHandles must be less than or equal to 64."));
            }
            if (-1 > millisecondsTimeout)
            {
                throw new ArgumentOutOfRangeException("millisecondsTimeout", Environment.GetResourceString("Number must be either non-negative and less than or equal to Int32.MaxValue or -1."));
            }
            WaitHandle[] array = new WaitHandle[waitHandles.Length];
            for (int i = 0; i < waitHandles.Length; i++)
            {
                WaitHandle waitHandle = waitHandles[i];
                if (waitHandle == null)
                {
                    throw new ArgumentNullException(Environment.GetResourceString("At least one element in the specified array was null."));
                }
                if (RemotingServices.IsTransparentProxy(waitHandle))
                {
                    throw new InvalidOperationException(Environment.GetResourceString("Cannot wait on a transparent proxy."));
                }
                array[i] = waitHandle;
            }
            int num = WaitHandle.WaitMultiple(array, millisecondsTimeout, exitContext, true);
            if (128 <= num && 128 + array.Length > num)
            {
                WaitHandle.ThrowAbandonedMutexException();
            }
            GC.KeepAlive(array);
            return num != 258 && num != int.MaxValue;
        }
References System.array, System.Environment.GetResourceString(), System.Runtime.Remoting.RemotingServices.IsTransparentProxy(), System.GC.KeepAlive(), System.Threading.WaitHandle.ThrowAbandonedMutexException(), System.Threading.WaitHandle.waitHandle, and System.Threading.WaitHandle.WaitMultiple().
Referenced by System.Threading.WaitHandle.WaitAll(), System.Threading.WaitHandle.WaitAll(), System.Threading.WaitHandle.WaitAll(), System.Threading.WaitHandle.WaitAll(), and System.Threading.WaitHandle.WaitMultiple().