Terraria Decompiled: System.Threading.WaitHandle.WaitOneNative
WaitOneNative()
static unsafe int System.Threading.WaitHandle.WaitOneNative (SafeHandle waitableSafeHandle, uint millisecondsTimeout, bool hasThreadAffinity, bool exitContext) inline static private
Definition at line 440 of file WaitHandle.cs.
        {
            bool flag = false;
            SynchronizationContext synchronizationContext = SynchronizationContext.Current;
            int num;
            try
            {
                waitableSafeHandle.DangerousAddRef(ref flag);
                if (exitContext)
                {
                    SynchronizationAttribute.ExitContext();
                }
                if (synchronizationContext != null && synchronizationContext.IsWaitNotificationRequired())
                {
                    num = synchronizationContext.Wait(new IntPtr[] { waitableSafeHandle.DangerousGetHandle() }, false, (int)millisecondsTimeout);
                }
                else
                {
                    IntPtr intPtr = waitableSafeHandle.DangerousGetHandle();
                    num = WaitHandle.Wait_internal(&intPtr, 1, false, (int)millisecondsTimeout);
                }
            }
            finally
            {
                if (flag)
                {
                    waitableSafeHandle.DangerousRelease();
                }
                if (exitContext)
                {
                    SynchronizationAttribute.EnterContext();
                }
            }
            return num;
        }
References System.Threading.SynchronizationContext.Current, System.Runtime.InteropServices.SafeHandle.DangerousAddRef(), System.Runtime.InteropServices.SafeHandle.DangerousGetHandle(), System.Runtime.InteropServices.SafeHandle.DangerousRelease(), System.Runtime.Remoting.Contexts.SynchronizationAttribute.EnterContext(), System.Runtime.Remoting.Contexts.SynchronizationAttribute.ExitContext(), int, System.Threading.SynchronizationContext.IsWaitNotificationRequired(), System.Threading.SynchronizationContext.Wait(), and System.Threading.WaitHandle.Wait_internal().
Referenced by System.Threading.WaitHandle.InternalWaitOne(), and System.Threading.WaitHandle.WaitOneWithoutFAS().