Terraria Decompiled: Mono.Globalization.Unicode.CodePointIndexer.ToIndex
ToIndex()
int Mono.Globalization.Unicode.CodePointIndexer.ToIndex (int cp) inline
Definition at line 41 of file CodePointIndexer.cs.
        {
            for (int i = 0; i < this.ranges.Length; i++)
            {
                if (cp < this.ranges[i].Start)
                {
                    return this.defaultIndex;
                }
                if (cp < this.ranges[i].End)
                {
                    return cp - this.ranges[i].Start + this.ranges[i].IndexStart;
                }
            }
            return this.defaultIndex;
        }
References Mono.Globalization.Unicode.CodePointIndexer.defaultIndex, System.End, and Mono.Globalization.Unicode.CodePointIndexer.ranges.
Referenced by Mono.Globalization.Unicode.MSCompatUnicodeTable.Category(), Mono.Globalization.Unicode.SimpleCollator.Category(), Mono.Globalization.Unicode.NormalizationTableUtil.CbIdx(), System.Text.Normalization.GetCombiningClass(), System.Text.Normalization.GetPrimaryCompositeFromMapIndex(), System.Text.Normalization.GetPrimaryCompositeHelperIndex(), Mono.Globalization.Unicode.MSCompatUnicodeTable.IsIgnorable(), Mono.Globalization.Unicode.MSCompatUnicodeTable.Level1(), Mono.Globalization.Unicode.SimpleCollator.Level1(), Mono.Globalization.Unicode.MSCompatUnicodeTable.Level2(), Mono.Globalization.Unicode.SimpleCollator.Level2(), Mono.Globalization.Unicode.MSCompatUnicodeTable.Level3(), Mono.Globalization.Unicode.NormalizationTableUtil.MapIdx(), and Mono.Globalization.Unicode.NormalizationTableUtil.PropIdx().