Terraria Decompiled: System.Security.Cryptography.SHA1Managed.SHATransform
SHATransform()
static unsafe void System.Security.Cryptography.SHA1Managed.SHATransform (uint * expandedBuffer, uint * state, byte * block) inline static private
Definition at line 144 of file SHA1Managed.cs.
        {
            uint num = *state;
            uint num2 = state[1];
            uint num3 = state[2];
            uint num4 = state[3];
            uint num5 = state[4];
            Utils.DWORDFromBigEndian(expandedBuffer, 16, block);
            SHA1Managed.SHAExpand(expandedBuffer);
            int i;
            for (i = 0; i < 20; i += 5)
            {
                num5 += ((num << 5) | (num >> 27)) + (num4 ^ (num2 & (num3 ^ num4))) + expandedBuffer[i] + 1518500249U;
                num2 = (num2 << 30) | (num2 >> 2);
                num4 += ((num5 << 5) | (num5 >> 27)) + (num3 ^ (num & (num2 ^ num3))) + expandedBuffer[i + 1] + 1518500249U;
                num = (num << 30) | (num >> 2);
                num3 += ((num4 << 5) | (num4 >> 27)) + (num2 ^ (num5 & (num ^ num2))) + expandedBuffer[i + 2] + 1518500249U;
                num5 = (num5 << 30) | (num5 >> 2);
                num2 += ((num3 << 5) | (num3 >> 27)) + (num ^ (num4 & (num5 ^ num))) + expandedBuffer[i + 3] + 1518500249U;
                num4 = (num4 << 30) | (num4 >> 2);
                num += ((num2 << 5) | (num2 >> 27)) + (num5 ^ (num3 & (num4 ^ num5))) + expandedBuffer[i + 4] + 1518500249U;
                num3 = (num3 << 30) | (num3 >> 2);
            }
            while (i < 40)
            {
                num5 += ((num << 5) | (num >> 27)) + (num2 ^ num3 ^ num4) + expandedBuffer[i] + 1859775393U;
                num2 = (num2 << 30) | (num2 >> 2);
                num4 += ((num5 << 5) | (num5 >> 27)) + (num ^ num2 ^ num3) + expandedBuffer[i + 1] + 1859775393U;
                num = (num << 30) | (num >> 2);
                num3 += ((num4 << 5) | (num4 >> 27)) + (num5 ^ num ^ num2) + expandedBuffer[i + 2] + 1859775393U;
                num5 = (num5 << 30) | (num5 >> 2);
                num2 += ((num3 << 5) | (num3 >> 27)) + (num4 ^ num5 ^ num) + expandedBuffer[i + 3] + 1859775393U;
                num4 = (num4 << 30) | (num4 >> 2);
                num += ((num2 << 5) | (num2 >> 27)) + (num3 ^ num4 ^ num5) + expandedBuffer[i + 4] + 1859775393U;
                num3 = (num3 << 30) | (num3 >> 2);
                i += 5;
            }
            while (i < 60)
            {
                num5 += ((num << 5) | (num >> 27)) + ((num2 & num3) | (num4 & (num2 | num3))) + expandedBuffer[i] + 2400959708U;
                num2 = (num2 << 30) | (num2 >> 2);
                num4 += ((num5 << 5) | (num5 >> 27)) + ((num & num2) | (num3 & (num | num2))) + expandedBuffer[i + 1] + 2400959708U;
                num = (num << 30) | (num >> 2);
                num3 += ((num4 << 5) | (num4 >> 27)) + ((num5 & num) | (num2 & (num5 | num))) + expandedBuffer[i + 2] + 2400959708U;
                num5 = (num5 << 30) | (num5 >> 2);
                num2 += ((num3 << 5) | (num3 >> 27)) + ((num4 & num5) | (num & (num4 | num5))) + expandedBuffer[i + 3] + 2400959708U;
                num4 = (num4 << 30) | (num4 >> 2);
                num += ((num2 << 5) | (num2 >> 27)) + ((num3 & num4) | (num5 & (num3 | num4))) + expandedBuffer[i + 4] + 2400959708U;
                num3 = (num3 << 30) | (num3 >> 2);
                i += 5;
            }
            while (i < 80)
            {
                num5 += ((num << 5) | (num >> 27)) + (num2 ^ num3 ^ num4) + expandedBuffer[i] + 3395469782U;
                num2 = (num2 << 30) | (num2 >> 2);
                num4 += ((num5 << 5) | (num5 >> 27)) + (num ^ num2 ^ num3) + expandedBuffer[i + 1] + 3395469782U;
                num = (num << 30) | (num >> 2);
                num3 += ((num4 << 5) | (num4 >> 27)) + (num5 ^ num ^ num2) + expandedBuffer[i + 2] + 3395469782U;
                num5 = (num5 << 30) | (num5 >> 2);
                num2 += ((num3 << 5) | (num3 >> 27)) + (num4 ^ num5 ^ num) + expandedBuffer[i + 3] + 3395469782U;
                num4 = (num4 << 30) | (num4 >> 2);
                num += ((num2 << 5) | (num2 >> 27)) + (num3 ^ num4 ^ num5) + expandedBuffer[i + 4] + 3395469782U;
                num3 = (num3 << 30) | (num3 >> 2);
                i += 5;
            }
            *state += num;
            state[1] += num2;
            state[2] += num3;
            state[3] += num4;
            state[4] += num5;
        }
References System.Security.Cryptography.Utils.DWORDFromBigEndian(), System.Security.Cryptography.SHA1Managed.SHAExpand(), System.state, and System.U.
Referenced by System.Security.Cryptography.SHA1Managed._HashData().