Terraria Decompiled: Terraria.GameContent.UI.Elements.UICharacter.DrawSelf
DrawSelf()
override void Terraria.GameContent.UI.Elements.UICharacter.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 84 of file UICharacter.cs.
        {
            CalculatedStyle dimensions = base.GetDimensions();
            if (this._drawsBackPanel)
            {
                spriteBatch.Draw(this._texture.Value, dimensions.Position(), Color.White);
            }
            this._player.ResetEffects();
            this._player.ResetVisibleAccessories();
            this._player.UpdateMiscCounter();
            this._player.UpdateDyes();
            if (this.PrepareAction != null)
            {
                this.PrepareAction();
            }
            this._player.PlayerFrame();
            this.UpdateAnim();
            this.DrawPets(spriteBatch);
            Vector2 playerPosition = this.GetPlayerPosition(ref dimensions);
            Item item = this._player.inventory[this._player.selectedItem];
            this._player.inventory[this._player.selectedItem] = UICharacter._blankItem;
            Main.PlayerRenderer.DrawPlayer(Main.Camera, this._player, playerPosition + Main.screenPosition, 0f, Vector2.Zero, 0f, this._characterScale);
            this._player.inventory[this._player.selectedItem] = item;
        }
References Terraria.GameContent.UI.Elements.UICharacter._blankItem, Terraria.GameContent.UI.Elements.UICharacter._drawsBackPanel, Terraria.GameContent.UI.Elements.UICharacter._player, Terraria.GameContent.UI.Elements.UICharacter._texture, Terraria.Main.Camera, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.GameContent.UI.Elements.UICharacter.DrawPets(), Terraria.GameContent.UI.Elements.UICharacter.GetPlayerPosition(), Terraria.Player.inventory, System.item, Terraria.Player.PlayerFrame(), Terraria.Main.PlayerRenderer, Terraria.UI.CalculatedStyle.Position(), Terraria.GameContent.UI.Elements.UICharacter.PrepareAction, Terraria.Player.ResetEffects(), Terraria.Player.ResetVisibleAccessories(), Terraria.Main.screenPosition, Terraria.Player.selectedItem, Terraria.GameContent.UI.Elements.UICharacter.UpdateAnim(), Terraria.Player.UpdateDyes(), Terraria.Player.UpdateMiscCounter(), ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Color.White, and Microsoft.Xna.Framework.Vector2.Zero.