Terraria Decompiled: XPT.Core.Audio.MP3Sharp.Decoding.BitReserve.ReadBits
ReadBits()
int XPT.Core.Audio.MP3Sharp.Decoding.BitReserve.ReadBits (int n) inline package
Definition at line 30 of file BitReserve.cs.
        {
            this._Totbit += n;
            int num = 0;
            int num2 = this._BufByteIdx;
            if (num2 + n < 32768)
            {
                while (n-- > 0)
                {
                    num <<= 1;
                    num |= ((this._Buffer[num2++] != 0) ? 1 : 0);
                }
            }
            else
            {
                while (n-- > 0)
                {
                    num <<= 1;
                    num |= ((this._Buffer[num2] != 0) ? 1 : 0);
                    num2 = (num2 + 1) & 32767;
                }
            }
            this._BufByteIdx = num2;
            return num;
        }
References XPT.Core.Audio.MP3Sharp.Decoding.BitReserve._BufByteIdx, and XPT.Core.Audio.MP3Sharp.Decoding.BitReserve._Buffer.
Referenced by XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.Decode(), XPT.Core.Audio.MP3Sharp.Decoding.Huffman.Decode(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.GetLSFScaleData(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.HuffmanDecode(), and XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.ReadScaleFactors().