Terraria Decompiled: Terraria.GameContent.UI.Elements.GroupOptionButton.DrawSelf
DrawSelf()
override void Terraria.GameContent.UI.Elements.GroupOptionButton< T >.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 192 of file GroupOptionButton.cs.
        {
            if (this._hovered)
            {
                if (!this._soundedHover)
                {
                    SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                }
                this._soundedHover = true;
            }
            else
            {
                this._soundedHover = false;
            }
            CalculatedStyle dimensions = base.GetDimensions();
            Color color = this._color;
            float num = this._opacity;
            bool isSelected = this.IsSelected;
            if (this._UseOverrideColors)
            {
                color = (isSelected ? this._overridePickedColor : this._overrideUnpickedColor);
                num = (isSelected ? this._overrideOpacityPicked : this._overrideOpacityUnpicked);
            }
            Utils.DrawSplicedPanel(spriteBatch, this._BasePanelTexture.Value, (int)dimensions.X, (int)dimensions.Y, (int)dimensions.Width, (int)dimensions.Height, 10, 10, 10, 10, Color.Lerp(Color.Black, color, this.FadeFromBlack) * num);
            if (isSelected && this.ShowHighlightWhenSelected)
            {
                Utils.DrawSplicedPanel(spriteBatch, this._selectedBorderTexture.Value, (int)dimensions.X + this.InnerHighlightRim, (int)dimensions.Y + this.InnerHighlightRim, (int)dimensions.Width - this.InnerHighlightRim * 2, (int)dimensions.Height - this.InnerHighlightRim * 2, 10, 10, 10, 10, Color.Lerp(color, Color.White, this._whiteLerp) * num);
            }
            if (this._hovered)
            {
                Utils.DrawSplicedPanel(spriteBatch, this._hoveredBorderTexture.Value, (int)dimensions.X, (int)dimensions.Y, (int)dimensions.Width, (int)dimensions.Height, 10, 10, 10, 10, this._borderColor);
            }
            if (this._iconTexture != null)
            {
                Color color2 = this.IconColor;
                if (!this._hovered && !isSelected)
                {
                    color2 = Color.Lerp(color, color2, this._whiteLerp) * num;
                }
                spriteBatch.Draw(this._iconTexture.Value, new Vector2(dimensions.X + 1f, dimensions.Y + 1f) + this._iconOffset, this._iconFrame, color2, 0f, Vector2.Zero, this._iconScale, SpriteEffects.None, 0f);
            }
        }
References Terraria.GameContent.UI.Elements.GroupOptionButton< T >._BasePanelTexture, Terraria.GameContent.UI.Elements.GroupOptionButton< T >._color, Terraria.GameContent.UI.Elements.GroupOptionButton< T >._hovered, Terraria.GameContent.UI.Elements.GroupOptionButton< T >._hoveredBorderTexture, Terraria.GameContent.UI.Elements.GroupOptionButton< T >._iconFrame, Terraria.GameContent.UI.Elements.GroupOptionButton< T >._iconOffset, Terraria.GameContent.UI.Elements.GroupOptionButton< T >._iconScale, Terraria.GameContent.UI.Elements.GroupOptionButton< T >._iconTexture, Terraria.GameContent.UI.Elements.GroupOptionButton< T >._opacity, Terraria.GameContent.UI.Elements.GroupOptionButton< T >._overrideOpacityUnpicked, Terraria.GameContent.UI.Elements.GroupOptionButton< T >._overrideUnpickedColor, Terraria.GameContent.UI.Elements.GroupOptionButton< T >._selectedBorderTexture, Terraria.GameContent.UI.Elements.GroupOptionButton< T >._soundedHover, Terraria.GameContent.UI.Elements.GroupOptionButton< T >._UseOverrideColors, Terraria.GameContent.UI.Elements.GroupOptionButton< T >._whiteLerp, Microsoft.Xna.Framework.Color.Black, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Utils.DrawSplicedPanel(), Terraria.UI.CalculatedStyle.Height, Terraria.GameContent.UI.Elements.GroupOptionButton< T >.IconColor, Terraria.GameContent.UI.Elements.GroupOptionButton< T >.InnerHighlightRim, int, Terraria.GameContent.UI.Elements.GroupOptionButton< T >.IsSelected, Microsoft.Xna.Framework.Color.Lerp(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.GameContent.UI.Elements.GroupOptionButton< T >.ShowHighlightWhenSelected, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Color.White, Terraria.UI.CalculatedStyle.Width, Terraria.UI.CalculatedStyle.X, Terraria.UI.CalculatedStyle.Y, and Microsoft.Xna.Framework.Vector2.Zero.