Terraria Decompiled: System.Reflection.Emit.ILGenerator.FixupTokens
FixupTokens()
void System.Reflection.Emit.ILGenerator.FixupTokens (Dictionary< int, int > token_map, Dictionary< int, MemberInfo > member_map) inline package
Definition at line 1130 of file ILGenerator.cs.
        {
            for (int i = 0; i < this.num_token_fixups; i++)
            {
                int code_pos = this.token_fixups[i].code_pos;
                int num = (int)this.code[code_pos] | ((int)this.code[code_pos + 1] << 8) | ((int)this.code[code_pos + 2] << 16) | ((int)this.code[code_pos + 3] << 24);
                int num2;
                if (token_map.TryGetValue(num, out num2))
                {
                    this.token_fixups[i].member = member_map[num];
                    int num3 = this.code_len;
                    this.code_len = code_pos;
                    this.emit_int(num2);
                    this.code_len = num3;
                }
            }
        }
References System.Reflection.Emit.ILGenerator.code, System.Reflection.Emit.ILGenerator.code_len, System.Reflection.Emit.ILTokenInfo.code_pos, System.Reflection.Emit.ILGenerator.emit_int(), int, System.Reflection.Emit.ILTokenInfo.member, System.Reflection.Emit.ILGenerator.num_token_fixups, System.Reflection.Emit.ILGenerator.token_fixups, and System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue().
Referenced by System.Reflection.Emit.ConstructorBuilder.FixupTokens(), and System.Reflection.Emit.MethodBuilder.FixupTokens().