Terraria Decompiled: System.Reflection.Emit.ILGenerator.ll_emit
ll_emit()
void System.Reflection.Emit.ILGenerator.ll_emit (OpCode opcode) inline private
Definition at line 100 of file ILGenerator.cs.
        {
            int num;
            if (opcode.Size == 2)
            {
                byte[] array = this.code;
                num = this.code_len;
                this.code_len = num + 1;
                array[num] = opcode.op1;
            }
            byte[] array2 = this.code;
            num = this.code_len;
            this.code_len = num + 1;
            array2[num] = opcode.op2;
            switch (opcode.StackBehaviourPush)
            {
            case StackBehaviour.Push1:
            case StackBehaviour.Pushi:
            case StackBehaviour.Pushi8:
            case StackBehaviour.Pushr4:
            case StackBehaviour.Pushr8:
            case StackBehaviour.Pushref:
            case StackBehaviour.Varpush:
                this.cur_stack++;
                break;
            case StackBehaviour.Push1_push1:
                this.cur_stack += 2;
                break;
            }
            if (this.max_stack < this.cur_stack)
            {
                this.max_stack = this.cur_stack;
            }
            switch (opcode.StackBehaviourPop)
            {
            case StackBehaviour.Pop1:
            case StackBehaviour.Popi:
            case StackBehaviour.Popref:
                this.cur_stack--;
                return;
            case StackBehaviour.Pop1_pop1:
            case StackBehaviour.Popi_pop1:
            case StackBehaviour.Popi_popi:
            case StackBehaviour.Popi_popi8:
            case StackBehaviour.Popi_popr4:
            case StackBehaviour.Popi_popr8:
            case StackBehaviour.Popref_pop1:
            case StackBehaviour.Popref_popi:
                this.cur_stack -= 2;
                return;
            case StackBehaviour.Popi_popi_popi:
            case StackBehaviour.Popref_popi_popi:
            case StackBehaviour.Popref_popi_popi8:
            case StackBehaviour.Popref_popi_popr4:
            case StackBehaviour.Popref_popi_popr8:
            case StackBehaviour.Popref_popi_popref:
                this.cur_stack -= 3;
                break;
            case StackBehaviour.Push0:
            case StackBehaviour.Push1:
            case StackBehaviour.Push1_push1:
            case StackBehaviour.Pushi:
            case StackBehaviour.Pushi8:
            case StackBehaviour.Pushr4:
            case StackBehaviour.Pushr8:
            case StackBehaviour.Pushref:
            case StackBehaviour.Varpop:
                break;
            default:
                return;
            }
        }
References System.array, System.Reflection.Emit.ILGenerator.code, System.Reflection.Emit.ILGenerator.code_len, System.Reflection.Emit.ILGenerator.cur_stack, System.Reflection.Emit.ILGenerator.max_stack, System.Reflection.Emit.OpCode.op1, System.Reflection.Emit.OpCode.op2, System.Reflection.Emit.OpCode.Size, System.Reflection.Emit.OpCode.StackBehaviourPop, and System.Reflection.Emit.OpCode.StackBehaviourPush.
Referenced by System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), and System.Reflection.Emit.ILGenerator.Emit().