Terraria Decompiled: System.Reflection.Emit.ILGenerator.add_token_fixup
add_token_fixup()
void System.Reflection.Emit.ILGenerator.add_token_fixup (MemberInfo mi) inline private
Definition at line 51 of file ILGenerator.cs.
        {
            if (this.num_token_fixups == this.token_fixups.Length)
            {
                ILTokenInfo[] array = new ILTokenInfo[this.num_token_fixups * 2];
                this.token_fixups.CopyTo(array, 0);
                this.token_fixups = array;
            }
            this.token_fixups[this.num_token_fixups].member = mi;
            ILTokenInfo[] array2 = this.token_fixups;
            int num = this.num_token_fixups;
            this.num_token_fixups = num + 1;
            array2[num].code_pos = this.code_len;
        }
References System.array, System.Reflection.Emit.ILGenerator.code_len, System.Reflection.Emit.ILTokenInfo.code_pos, System.Reflection.Emit.ILTokenInfo.member, System.Reflection.Emit.ILGenerator.num_token_fixups, and System.Reflection.Emit.ILGenerator.token_fixups.
Referenced by System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), and System.Reflection.Emit.ILGenerator.Emit().