Terraria Decompiled: System.Reflection.Emit.ILGenerator.DefineLabel
DefineLabel()
virtual Label System.Reflection.Emit.ILGenerator.DefineLabel () inline virtual
Definition at line 360 of file ILGenerator.cs.
        {
            if (this.labels == null)
            {
                this.labels = new ILGenerator.LabelData[4];
            }
            else if (this.num_labels >= this.labels.Length)
            {
                ILGenerator.LabelData[] array = new ILGenerator.LabelData[this.labels.Length * 2];
                Array.Copy(this.labels, array, this.labels.Length);
                this.labels = array;
            }
            this.labels[this.num_labels] = new ILGenerator.LabelData(-1, 0);
            int num = this.num_labels;
            this.num_labels = num + 1;
            return new Label(num);
        }
References System.array, System.Array.Copy(), System.Reflection.Emit.ILGenerator.labels, and System.Reflection.Emit.ILGenerator.num_labels.
Referenced by System.Reflection.Emit.ILGenerator.BeginExceptionBlock(), and Newtonsoft.Json.Utilities.DynamicReflectionDelegateFactory.GenerateCreateMethodCallIL().