Terraria Decompiled: System.Reflection.Emit.ILGenerator.Init
Init()
void System.Reflection.Emit.ILGenerator.Init (byte[] il, int maxStack, byte[] localSignature, IEnumerable< ExceptionHandler > exceptionHandlers, IEnumerable< int > tokenFixups) inline package
Definition at line 1183 of file ILGenerator.cs.
        {
            this.SetCode(il, maxStack);
            if (exceptionHandlers != null)
            {
                Dictionary<Tuple<int, int>, List<ExceptionHandler>> dictionary = new Dictionary<Tuple<int, int>, List<ExceptionHandler>>();
                foreach (ExceptionHandler exceptionHandler in exceptionHandlers)
                {
                    Tuple<int, int> tuple = new Tuple<int, int>(exceptionHandler.TryOffset, exceptionHandler.TryLength);
                    List<ExceptionHandler> list;
                    if (!dictionary.TryGetValue(tuple, out list))
                    {
                        list = new List<ExceptionHandler>();
                        dictionary.Add(tuple, list);
                    }
                    list.Add(exceptionHandler);
                }
                List<ILExceptionInfo> list2 = new List<ILExceptionInfo>();
                foreach (KeyValuePair<Tuple<int, int>, List<ExceptionHandler>> keyValuePair in dictionary)
                {
                    ILExceptionInfo ilexceptionInfo = new ILExceptionInfo
                    {
                        start = keyValuePair.Key.Item1,
                        len = keyValuePair.Key.Item2,
                        handlers = new ILExceptionBlock[keyValuePair.Value.Count]
                    };
                    list2.Add(ilexceptionInfo);
                    int num = 0;
                    foreach (ExceptionHandler exceptionHandler2 in keyValuePair.Value)
                    {
                        ilexceptionInfo.handlers[num++] = new ILExceptionBlock
{
                            start = exceptionHandler2.HandlerOffset,
                            len = exceptionHandler2.HandlerLength,
                            filter_offset = exceptionHandler2.FilterOffset,
                            type = (int)exceptionHandler2.Kind,
                            extype = this.module.ResolveType(exceptionHandler2.ExceptionTypeToken)
                        };
                    }
                }
                this.SetExceptionHandlers(list2.ToArray());
            }
            if (tokenFixups != null)
            {
                List<ILTokenInfo> list3 = new List<ILTokenInfo>();
                foreach (int num2 in tokenFixups)
                {
                    int num3 = (int)BitConverter.ToUInt32(il, num2);
                    ILTokenInfo iltokenInfo = new ILTokenInfo
                    {
                        code_pos = num2,
                        member = ((ModuleBuilder)this.module).ResolveOrGetRegisteredToken(num3, null, null)
                    };
                    list3.Add(iltokenInfo);
                }
                this.SetTokenFixups(list3.ToArray());
            }
        }
References System.dictionary, System.Reflection.Emit.ExceptionHandler.ExceptionTypeToken, System.Reflection.Emit.ExceptionHandler.FilterOffset, System.Reflection.Emit.ExceptionHandler.HandlerLength, System.Reflection.Emit.ExceptionHandler.HandlerOffset, int, System.Reflection.Emit.ExceptionHandler.Kind, System.list, System.Reflection.Emit.ILGenerator.module, System.Reflection.Emit.ILGenerator.SetCode(), System.Reflection.Emit.ILGenerator.SetExceptionHandlers(), System.Reflection.Emit.ILGenerator.SetTokenFixups(), System.start, System.BitConverter.ToUInt32(), System.Reflection.Emit.ExceptionHandler.TryLength, and System.Reflection.Emit.ExceptionHandler.TryOffset.
Referenced by System.Reflection.Emit.ConstructorBuilder.SetMethodBody(), and System.Reflection.Emit.MethodBuilder.SetMethodBody().