Terraria Decompiled: System.Reflection.Emit.ILGenerator.GenerateDebugInfo
GenerateDebugInfo()
void System.Reflection.Emit.ILGenerator.GenerateDebugInfo (ISymbolWriter symbolWriter) inline package
Definition at line 1039 of file ILGenerator.cs.
        {
            if (this.sequencePointLists != null)
            {
                SequencePointList sequencePointList = (SequencePointList)this.sequencePointLists[0];
                SequencePointList sequencePointList2 = (SequencePointList)this.sequencePointLists[this.sequencePointLists.Count - 1];
                symbolWriter.SetMethodSourceRange(sequencePointList.Document, sequencePointList.StartLine, sequencePointList.StartColumn, sequencePointList2.Document, sequencePointList2.EndLine, sequencePointList2.EndColumn);
                foreach (object obj in this.sequencePointLists)
                {
                    SequencePointList sequencePointList3 = (SequencePointList)obj;
                    symbolWriter.DefineSequencePoints(sequencePointList3.Document, sequencePointList3.GetOffsets(), sequencePointList3.GetLines(), sequencePointList3.GetColumns(), sequencePointList3.GetEndLines(), sequencePointList3.GetEndColumns());
                }
                if (this.locals != null)
                {
                    foreach (LocalBuilder localBuilder in this.locals)
                    {
                        if (localBuilder.Name != null && localBuilder.Name.Length > 0)
{
                            SignatureHelper localVarSigHelper = SignatureHelper.GetLocalVarSigHelper(this.module as ModuleBuilder);
                            localVarSigHelper.AddArgument(localBuilder.LocalType);
                            byte[] signature = localVarSigHelper.GetSignature();
                            symbolWriter.DefineLocalVariable(localBuilder.Name, FieldAttributes.Public, signature, SymAddressKind.ILOffset, (int)localBuilder.position, 0, 0, localBuilder.StartOffset, localBuilder.EndOffset);
                        }
                    }
                }
                this.sequencePointLists = null;
            }
        }
References System.Reflection.Emit.SignatureHelper.AddArgument(), System.Collections.ArrayList.Count, System.Diagnostics.SymbolStore.ISymbolWriter.DefineLocalVariable(), System.Diagnostics.SymbolStore.ISymbolWriter.DefineSequencePoints(), System.Reflection.Emit.SequencePointList.Document, System.Reflection.Emit.SequencePointList.EndColumn, System.Reflection.Emit.SequencePointList.EndLine, System.Reflection.Emit.LocalBuilder.EndOffset, System.Reflection.Emit.SequencePointList.GetColumns(), System.Reflection.Emit.SequencePointList.GetEndColumns(), System.Reflection.Emit.SequencePointList.GetEndLines(), System.Reflection.Emit.SequencePointList.GetLines(), System.Reflection.Emit.SignatureHelper.GetLocalVarSigHelper(), System.Reflection.Emit.SequencePointList.GetOffsets(), System.Reflection.Emit.SignatureHelper.GetSignature(), System.Reflection.Emit.ILGenerator.locals, System.Reflection.Emit.LocalBuilder.LocalType, System.Reflection.Emit.ILGenerator.module, System.Reflection.Emit.LocalBuilder.Name, System.obj, System.Reflection.LocalVariableInfo.position, System.Reflection.Emit.ILGenerator.sequencePointLists, System.Diagnostics.SymbolStore.ISymbolWriter.SetMethodSourceRange(), System.Reflection.Emit.SequencePointList.StartColumn, System.Reflection.Emit.SequencePointList.StartLine, and System.Reflection.Emit.LocalBuilder.StartOffset.
Referenced by System.Reflection.Emit.ConstructorBuilder.GenerateDebugInfo(), and System.Reflection.Emit.MethodBuilder.GenerateDebugInfo().