Terraria Decompiled: System.Reflection.Emit.ILGenerator.Emit
Emit() [16/18]
virtual void System.Reflection.Emit.ILGenerator.Emit (OpCode opcode, SignatureHelper signature) inline virtual
Definition at line 821 of file ILGenerator.cs.
        {
            int token = this.token_gen.GetToken(signature);
            this.make_room(6);
            this.ll_emit(opcode);
            this.emit_int(token);
        }
References System.Reflection.Emit.ILGenerator.emit_int(), System.Reflection.Emit.TokenGenerator.GetToken(), System.Reflection.Emit.ILGenerator.ll_emit(), System.Reflection.Emit.ILGenerator.make_room(), and System.Reflection.Emit.ILGenerator.token_gen.