Terraria Decompiled: System.Reflection.Emit.ILGenerator.Emit
Emit() [4/18]
virtual void System.Reflection.Emit.ILGenerator.Emit (OpCode opcode, double arg) inline virtual
Definition at line 415 of file ILGenerator.cs.
        {
            byte[] bytes = BitConverter.GetBytes(arg);
            this.make_room(10);
            this.ll_emit(opcode);
            if (BitConverter.IsLittleEndian)
            {
                Array.Copy(bytes, 0, this.code, this.code_len, 8);
                this.code_len += 8;
                return;
            }
            byte[] array = this.code;
            int num = this.code_len;
            this.code_len = num + 1;
            array[num] = bytes[7];
            byte[] array2 = this.code;
            num = this.code_len;
            this.code_len = num + 1;
            array2[num] = bytes[6];
            byte[] array3 = this.code;
            num = this.code_len;
            this.code_len = num + 1;
            array3[num] = bytes[5];
            byte[] array4 = this.code;
            num = this.code_len;
            this.code_len = num + 1;
            array4[num] = bytes[4];
            byte[] array5 = this.code;
            num = this.code_len;
            this.code_len = num + 1;
            array5[num] = bytes[3];
            byte[] array6 = this.code;
            num = this.code_len;
            this.code_len = num + 1;
            array6[num] = bytes[2];
            byte[] array7 = this.code;
            num = this.code_len;
            this.code_len = num + 1;
            array7[num] = bytes[1];
            byte[] array8 = this.code;
            num = this.code_len;
            this.code_len = num + 1;
            array8[num] = bytes[0];
        }
References System.array, System.Reflection.Emit.ILGenerator.code, System.Reflection.Emit.ILGenerator.code_len, System.Array.Copy(), System.BitConverter.GetBytes(), System.BitConverter.IsLittleEndian, System.Reflection.Emit.ILGenerator.ll_emit(), and System.Reflection.Emit.ILGenerator.make_room().