Terraria Decompiled: System.Reflection.Emit.ILGenerator.Emit
Emit() [12/18]
virtual void System.Reflection.Emit.ILGenerator.Emit (OpCode opcode, MethodInfo meth) inline virtual
Definition at line 758 of file ILGenerator.cs.
        {
            if (meth == null)
            {
                throw new ArgumentNullException("meth");
            }
            if (meth is DynamicMethod && (opcode == OpCodes.Ldftn || opcode == OpCodes.Ldvirtftn || opcode == OpCodes.Ldtoken))
            {
                throw new ArgumentException("Ldtoken, Ldftn and Ldvirtftn OpCodes cannot target DynamicMethods.");
            }
            int token = this.token_gen.GetToken(meth, true);
            this.make_room(6);
            this.ll_emit(opcode);
            Type declaringType = meth.DeclaringType;
            if (declaringType != null && (declaringType.Module == this.module || meth is MethodOnTypeBuilderInst || meth is MethodBuilder))
            {
                this.add_token_fixup(meth);
            }
            this.emit_int(token);
            if (meth.ReturnType != typeof(void))
            {
                this.cur_stack++;
            }
            if (opcode.StackBehaviourPop == StackBehaviour.Varpop)
            {
                this.cur_stack -= meth.GetParametersCount();
            }
        }
References System.Reflection.Emit.ILGenerator.add_token_fixup(), System.Reflection.Emit.ILGenerator.cur_stack, System.Runtime.InteropServices._MethodInfo.DeclaringType, System.Reflection.Emit.ILGenerator.emit_int(), System.Reflection.MethodBase.GetParametersCount(), System.Reflection.Emit.TokenGenerator.GetToken(), System.Reflection.Emit.OpCodes.Ldftn, System.Reflection.Emit.OpCodes.Ldtoken, System.Reflection.Emit.OpCodes.Ldvirtftn, System.Reflection.Emit.ILGenerator.ll_emit(), System.Reflection.Emit.ILGenerator.make_room(), System.Type.Module, System.Reflection.MethodInfo.ReturnType, System.Reflection.Emit.OpCode.StackBehaviourPop, and System.Reflection.Emit.ILGenerator.token_gen.