Terraria Decompiled: System.Reflection.Emit.ILGenerator.Emit
Emit() [18/18]
virtual void System.Reflection.Emit.ILGenerator.Emit (OpCode opcode, Type cls) inline virtual
Definition at line 869 of file ILGenerator.cs.
        {
            if (cls != null && cls.IsByRef)
            {
                throw new ArgumentException("Cannot get TypeToken for a ByRef type.");
            }
            this.make_room(6);
            this.ll_emit(opcode);
            int token = this.token_gen.GetToken(cls, opcode != OpCodes.Ldtoken);
            if (cls is TypeBuilderInstantiation || cls is SymbolType || cls is TypeBuilder || cls is GenericTypeParameterBuilder || cls is EnumBuilder)
            {
                this.add_token_fixup(cls);
            }
            this.emit_int(token);
        }
References System.Reflection.Emit.ILGenerator.add_token_fixup(), System.Reflection.Emit.ILGenerator.emit_int(), System.Reflection.Emit.TokenGenerator.GetToken(), System.Type.IsByRef, System.Reflection.Emit.OpCodes.Ldtoken, System.Reflection.Emit.ILGenerator.ll_emit(), System.Reflection.Emit.ILGenerator.make_room(), and System.Reflection.Emit.ILGenerator.token_gen.