Terraria Decompiled: System.Reflection.Emit.ILGenerator.InternalEndClause
InternalEndClause()
void System.Reflection.Emit.ILGenerator.InternalEndClause () inline private
Definition at line 184 of file ILGenerator.cs.
        {
            switch (this.ex_handlers[this.cur_block].LastClauseType())
            {
            case -1:
            case 0:
            case 1:
                this.Emit(OpCodes.Leave, this.ex_handlers[this.cur_block].end);
                return;
            case 2:
            case 4:
                this.Emit(OpCodes.Endfinally);
                break;
            case 3:
                break;
            default:
                return;
            }
        }
References System.Reflection.Emit.ILGenerator.cur_block, System.Reflection.Emit.OpCodes.Endfinally, System.Reflection.Emit.ILGenerator.ex_handlers, and System.Reflection.Emit.OpCodes.Leave.
Referenced by System.Reflection.Emit.ILGenerator.BeginCatchBlock(), System.Reflection.Emit.ILGenerator.BeginExceptFilterBlock(), System.Reflection.Emit.ILGenerator.BeginFaultBlock(), System.Reflection.Emit.ILGenerator.BeginFinallyBlock(), and System.Reflection.Emit.ILGenerator.EndExceptionBlock().