Terraria Decompiled: System.Reflection.Emit.ILGenerator.Emit
Emit() [9/18]
virtual void System.Reflection.Emit.ILGenerator.Emit (OpCode opcode, Label[] labels) inline virtual
Definition at line 563 of file ILGenerator.cs.
        {
            if (labels == null)
            {
                throw new ArgumentNullException("labels");
            }
            int num = labels.Length;
            this.make_room(6 + num * 4);
            this.ll_emit(opcode);
            for (int i = 0; i < num; i++)
            {
                if (this.cur_stack > this.labels[labels[i].label].maxStack)
                {
                    this.labels[labels[i].label].maxStack = this.cur_stack;
                }
            }
            this.emit_int(num);
            if (this.fixups == null)
            {
                this.fixups = new ILGenerator.LabelFixup[4 + num];
            }
            else if (this.num_fixups + num >= this.fixups.Length)
            {
                ILGenerator.LabelFixup[] array = new ILGenerator.LabelFixup[num + this.fixups.Length * 2];
                Array.Copy(this.fixups, array, this.fixups.Length);
                this.fixups = array;
            }
            int j = 0;
            int num2 = num * 4;
            while (j < num)
            {
                this.fixups[this.num_fixups].offset = num2;
                this.fixups[this.num_fixups].pos = this.code_len;
                this.fixups[this.num_fixups].label_idx = labels[j].label;
                this.num_fixups++;
                this.code_len += 4;
                j++;
                num2 -= 4;
            }
        }
References System.array, System.Reflection.Emit.ILGenerator.code_len, System.Array.Copy(), System.Reflection.Emit.ILGenerator.cur_stack, System.Reflection.Emit.ILGenerator.emit_int(), System.Reflection.Emit.ILGenerator.fixups, System.Reflection.Emit.Label.label, System.Reflection.Emit.ILGenerator.labels, System.Reflection.Emit.ILGenerator.ll_emit(), System.Reflection.Emit.ILGenerator.make_room(), and System.Reflection.Emit.ILGenerator.num_fixups.