Terraria Decompiled: System.Reflection.Emit.ILGenerator.BeginCatchBlock
BeginCatchBlock()
virtual void System.Reflection.Emit.ILGenerator.BeginCatchBlock (Type exceptionType) inline virtual
Definition at line 205 of file ILGenerator.cs.
        {
            if (this.open_blocks == null)
            {
                this.open_blocks = new Stack(2);
            }
            if (this.open_blocks.Count <= 0)
            {
                throw new NotSupportedException("Not in an exception block");
            }
            if (exceptionType != null && exceptionType.IsUserType)
            {
                throw new NotSupportedException("User defined subclasses of System.Type are not yet supported.");
            }
            if (this.ex_handlers[this.cur_block].LastClauseType() == -1)
            {
                if (exceptionType != null)
                {
                    throw new ArgumentException("Do not supply an exception type for filter clause");
                }
                this.Emit(OpCodes.Endfilter);
                this.ex_handlers[this.cur_block].PatchFilterClause(this.code_len);
            }
            else
            {
                this.InternalEndClause();
                this.ex_handlers[this.cur_block].AddCatch(exceptionType, this.code_len);
            }
            this.cur_stack = 1;
            if (this.max_stack < this.cur_stack)
            {
                this.max_stack = this.cur_stack;
            }
        }
References System.Reflection.Emit.ILExceptionInfo.AddCatch(), System.Reflection.Emit.ILGenerator.code_len, System.Collections.Generic.Stack< T >.Count, System.Reflection.Emit.ILGenerator.cur_block, System.Reflection.Emit.ILGenerator.cur_stack, System.Reflection.Emit.OpCodes.Endfilter, System.Reflection.Emit.ILGenerator.ex_handlers, System.Reflection.Emit.ILGenerator.InternalEndClause(), System.Type.IsUserType, System.Reflection.Emit.ILGenerator.max_stack, System.Reflection.Emit.ILGenerator.open_blocks, and System.Reflection.Emit.ILExceptionInfo.PatchFilterClause().