Terraria Decompiled: System.Reflection.Emit.ILGenerator.BeginFaultBlock
BeginFaultBlock()
virtual void System.Reflection.Emit.ILGenerator.BeginFaultBlock () inline virtual
Definition at line 280 of file ILGenerator.cs.
        {
            if (this.open_blocks == null)
            {
                this.open_blocks = new Stack(2);
            }
            if (this.open_blocks.Count <= 0)
            {
                throw new NotSupportedException("Not in an exception block");
            }
            if (this.ex_handlers[this.cur_block].LastClauseType() == -1)
            {
                this.Emit(OpCodes.Leave, this.ex_handlers[this.cur_block].end);
                this.ex_handlers[this.cur_block].PatchFilterClause(this.code_len);
            }
            this.InternalEndClause();
            this.ex_handlers[this.cur_block].AddFault(this.code_len);
        }
References System.Reflection.Emit.ILExceptionInfo.AddFault(), System.Reflection.Emit.ILGenerator.code_len, System.Collections.Generic.Stack< T >.Count, System.Reflection.Emit.ILGenerator.cur_block, System.Reflection.Emit.ILGenerator.ex_handlers, System.Reflection.Emit.ILGenerator.InternalEndClause(), System.Reflection.Emit.OpCodes.Leave, System.Reflection.Emit.ILGenerator.open_blocks, and System.Reflection.Emit.ILExceptionInfo.PatchFilterClause().