Terraria Decompiled: System.Reflection.Emit.ILGenerator.label_fixup
label_fixup()
void System.Reflection.Emit.ILGenerator.label_fixup (MethodBase mb) inline package
Definition at line 1106 of file ILGenerator.cs.
        {
            for (int i = 0; i < this.num_fixups; i++)
            {
                if (this.labels[this.fixups[i].label_idx].addr < 0)
                {
                    throw new ArgumentException(string.Format("Label #{0} is not marked in method `{1}'", this.fixups[i].label_idx + 1, mb.Name));
                }
                int num = this.labels[this.fixups[i].label_idx].addr - (this.fixups[i].pos + this.fixups[i].offset);
                if (this.fixups[i].offset == 1)
                {
                    this.code[this.fixups[i].pos] = (byte)((sbyte)num);
                }
                else
                {
                    int num2 = this.code_len;
                    this.code_len = this.fixups[i].pos;
                    this.emit_int(num);
                    this.code_len = num2;
                }
            }
        }
References System.Reflection.Emit.ILGenerator.code, System.Reflection.Emit.ILGenerator.code_len, System.Reflection.Emit.ILGenerator.emit_int(), System.Reflection.Emit.ILGenerator.fixups, System.Format, System.Reflection.Emit.ILGenerator.labels, System.Reflection.MemberInfo.Name, System.Reflection.Emit.ILGenerator.num_fixups, and System.offset.
Referenced by System.Reflection.Emit.DynamicMethod.CreateDynMethod(), System.Reflection.Emit.ConstructorBuilder.fixup(), and System.Reflection.Emit.MethodBuilder.fixup().