Terraria Decompiled: System.Text.UnicodeEncoding.GetChars
GetChars() [2/3]
unsafe override int System.Text.UnicodeEncoding.GetChars (byte * bytes, int byteCount, char * chars, int charCount, DecoderNLS baseDecoder) inline package virtual
Reimplemented from System.Text.Encoding.
Definition at line 1009 of file UnicodeEncoding.cs.
        {
            UnicodeEncoding.Decoder decoder = (UnicodeEncoding.Decoder)baseDecoder;
            int num = -1;
            char c = '\0';
            if (decoder != null)
            {
                num = decoder.lastByte;
                c = decoder.lastChar;
            }
            DecoderFallbackBuffer decoderFallbackBuffer = null;
            byte* ptr = bytes + byteCount;
            char* ptr2 = chars + charCount;
            byte* ptr3 = bytes;
            char* ptr4 = chars;
            while (bytes < ptr)
            {
                if ((this.bigEndian ^ BitConverter.IsLittleEndian) && (chars & 7L) == null && (bytes & 7L) == null && num == -1 && c == '\0')
                {
                    ulong* ptr5 = (ulong*)(bytes - 7 + (IntPtr)(((long)(ptr - bytes) >> 1 < (long)(ptr2 - chars)) ? ((long)(ptr - bytes)) : ((long)(ptr2 - chars) << 1)) / 8);
                    ulong* ptr6 = (ulong*)bytes;
                    ulong* ptr7 = (ulong*)chars;
                    while (ptr6 < ptr5)
                    {
                        if ((9223512776490647552UL & *ptr6) != 0UL)
{
                            ulong num2 = (17870556004450629632UL & *ptr6) ^ 15564677810327967744UL;
                            if (((num2 & 18446462598732840960UL) == 0UL || (num2 & 281470681743360UL) == 0UL || (num2 & (ulong)(-65536)) == 0UL || (num2 & 65535UL) == 0UL) && ((18158790778715962368UL & *ptr6) ^ UnicodeEncoding.highLowPatternMask) != 0UL)
{
                                break;
                            }
                        }
                        *ptr7 = *ptr6;
                        ptr6++;
                        ptr7++;
                    }
                    chars = (char*)ptr7;
                    bytes = (byte*)ptr6;
                    if (bytes >= ptr)
                    {
                        break;
                    }
                }
                if (num < 0)
                {
                    num = (int)(*(bytes++));
                }
                else
                {
                    char c2;
                    if (this.bigEndian)
                    {
                        c2 = (char)((num << 8) | (int)(*(bytes++)));
                    }
                    else
                    {
                        c2 = (char)(((int)(*(bytes++)) << 8) | num);
                    }
                    num = -1;
                    if (c2 >= '\ud800' && c2 <= '\udfff')
                    {
                        if (c2 <= '\udbff')
{
                            if (c > '\0')
{
                                byte[] array;
                                if (this.bigEndian)
{
                                    array = new byte[]
{
                                        (byte)(c >> 8),
                                        (byte)c
                                    };
                                }
                                else
{
                                    array = new byte[]
{
                                        (byte)c,
                                        (byte)(c >> 8)
                                    };
                                }
                                if (decoderFallbackBuffer == null)
{
                                    if (decoder == null)
{
                                        decoderFallbackBuffer = this.decoderFallback.CreateFallbackBuffer();
                                    }
                                    else
{
                                        decoderFallbackBuffer = decoder.FallbackBuffer;
                                    }
                                    decoderFallbackBuffer.InternalInitialize(ptr3, ptr2);
                                }
                                char* ptr8 = chars;
                                bool flag = decoderFallbackBuffer.InternalFallback(array, bytes, ref ptr8);
                                chars = ptr8;
                                if (!flag)
{
                                    bytes -= 2;
                                    decoderFallbackBuffer.InternalReset();
                                    base.ThrowCharsOverflow(decoder, chars == ptr4);
                                    break;
                                }
                            }
                            c = c2;
                            continue;
                        }
                        if (c == '\0')
{
                            byte[] array2;
                            if (this.bigEndian)
{
                                array2 = new byte[]
{
                                    (byte)(c2 >> 8),
                                    (byte)c2
                                };
                            }
                            else
{
                                array2 = new byte[]
{
                                    (byte)c2,
                                    (byte)(c2 >> 8)
                                };
                            }
                            if (decoderFallbackBuffer == null)
{
                                if (decoder == null)
{
                                    decoderFallbackBuffer = this.decoderFallback.CreateFallbackBuffer();
                                }
                                else
{
                                    decoderFallbackBuffer = decoder.FallbackBuffer;
                                }
                                decoderFallbackBuffer.InternalInitialize(ptr3, ptr2);
                            }
                            char* ptr8 = chars;
                            bool flag2 = decoderFallbackBuffer.InternalFallback(array2, bytes, ref ptr8);
                            chars = ptr8;
                            if (!flag2)
{
                                bytes -= 2;
                                decoderFallbackBuffer.InternalReset();
                                base.ThrowCharsOverflow(decoder, chars == ptr4);
                                break;
                            }
                            continue;
                        }
                        else
{
                            if (chars >= ptr2 - 1)
{
                                bytes -= 2;
                                base.ThrowCharsOverflow(decoder, chars == ptr4);
                                break;
                            }
                            *(chars++) = c;
                            c = '\0';
                        }
                    }
                    else if (c > '\0')
                    {
                        byte[] array3;
                        if (this.bigEndian)
{
                            array3 = new byte[]
{
                                (byte)(c >> 8),
                                (byte)c
                            };
                        }
                        else
{
                            array3 = new byte[]
{
                                (byte)c,
                                (byte)(c >> 8)
                            };
                        }
                        if (decoderFallbackBuffer == null)
{
                            if (decoder == null)
{
                                decoderFallbackBuffer = this.decoderFallback.CreateFallbackBuffer();
                            }
                            else
{
                                decoderFallbackBuffer = decoder.FallbackBuffer;
                            }
                            decoderFallbackBuffer.InternalInitialize(ptr3, ptr2);
                        }
                        char* ptr8 = chars;
                        bool flag3 = decoderFallbackBuffer.InternalFallback(array3, bytes, ref ptr8);
                        chars = ptr8;
                        if (!flag3)
{
                            bytes -= 2;
                            decoderFallbackBuffer.InternalReset();
                            base.ThrowCharsOverflow(decoder, chars == ptr4);
                            break;
                        }
                        c = '\0';
                    }
                    if (chars >= ptr2)
                    {
                        bytes -= 2;
                        base.ThrowCharsOverflow(decoder, chars == ptr4);
                        break;
                    }
                    *(chars++) = c2;
                }
            }
            if (decoder == null || decoder.MustFlush)
            {
                if (c > '\0')
                {
                    byte[] array4;
                    if (this.bigEndian)
                    {
                        array4 = new byte[]
{
                            (byte)(c >> 8),
                            (byte)c
                        };
                    }
                    else
                    {
                        array4 = new byte[]
{
                            (byte)c,
                            (byte)(c >> 8)
                        };
                    }
                    if (decoderFallbackBuffer == null)
                    {
                        if (decoder == null)
{
                            decoderFallbackBuffer = this.decoderFallback.CreateFallbackBuffer();
                        }
                        else
{
                            decoderFallbackBuffer = decoder.FallbackBuffer;
                        }
                        decoderFallbackBuffer.InternalInitialize(ptr3, ptr2);
                    }
                    char* ptr8 = chars;
                    bool flag4 = decoderFallbackBuffer.InternalFallback(array4, bytes, ref ptr8);
                    chars = ptr8;
                    if (!flag4)
                    {
                        bytes -= 2;
                        if (num >= 0)
{
                            bytes--;
                        }
                        decoderFallbackBuffer.InternalReset();
                        base.ThrowCharsOverflow(decoder, chars == ptr4);
                        bytes += 2;
                        if (num >= 0)
{
                            bytes++;
                            goto IL_04C7;
                        }
                        goto IL_04C7;
                    }
                    else
                    {
                        c = '\0';
                    }
                }
                if (num >= 0)
                {
                    if (decoderFallbackBuffer == null)
                    {
                        if (decoder == null)
{
                            decoderFallbackBuffer = this.decoderFallback.CreateFallbackBuffer();
                        }
                        else
{
                            decoderFallbackBuffer = decoder.FallbackBuffer;
                        }
                        decoderFallbackBuffer.InternalInitialize(ptr3, ptr2);
                    }
                    char* ptr8 = chars;
                    bool flag5 = decoderFallbackBuffer.InternalFallback(new byte[] { (byte)num }, bytes, ref ptr8);
                    chars = ptr8;
                    if (!flag5)
                    {
                        bytes--;
                        decoderFallbackBuffer.InternalReset();
                        base.ThrowCharsOverflow(decoder, chars == ptr4);
                        bytes++;
                    }
                    else
                    {
                        num = -1;
                    }
                }
            }
            IL_04C7:
            if (decoder != null)
            {
                decoder._bytesUsed = (int)((long)(bytes - ptr3));
                decoder.lastChar = c;
                decoder.lastByte = num;
            }
            return (int)((long)(chars - ptr4));
        }
References System.array, System.Text.UnicodeEncoding.bigEndian, System.Text.DecoderFallback.CreateFallbackBuffer(), System.Text.Encoding.decoderFallback, System.Text.Decoder.FallbackBuffer, System.Text.UnicodeEncoding.highLowPatternMask, int, System.Text.DecoderFallbackBuffer.InternalFallback(), System.Text.DecoderFallbackBuffer.InternalInitialize(), System.Text.DecoderFallbackBuffer.InternalReset(), System.BitConverter.IsLittleEndian, System.L, System.Text.UnicodeEncoding.Decoder.lastByte, System.Text.UnicodeEncoding.Decoder.lastChar, long, and System.Text.DecoderNLS.MustFlush.