Terraria Decompiled: System.Text.UnicodeEncoding.GetByteCount
GetByteCount() [2/4]
unsafe override int System.Text.UnicodeEncoding.GetByteCount (char * chars, int count, EncoderNLS encoder) inline package virtual
Reimplemented from System.Text.Encoding.
Definition at line 330 of file UnicodeEncoding.cs.
        {
            int num = count << 1;
            if (num < 0)
            {
                throw new ArgumentOutOfRangeException("count", "Too many characters. The resulting number of bytes is larger than what can be returned as an int.");
            }
            char* ptr = chars;
            char* ptr2 = chars + count;
            char c = '\0';
            bool flag = false;
            ulong* ptr3 = (ulong*)(ptr2 - 3);
            EncoderFallbackBuffer encoderFallbackBuffer = null;
            if (encoder != null)
            {
                c = encoder._charLeftOver;
                if (c > '\0')
                {
                    num += 2;
                }
                if (encoder.InternalHasFallbackBuffer)
                {
                    encoderFallbackBuffer = encoder.FallbackBuffer;
                    if (encoderFallbackBuffer.Remaining > 0)
                    {
                        throw new ArgumentException(SR.Format("Must complete Convert() operation or call Encoder.Reset() before calling GetBytes() or GetByteCount(). Encoder '{0}' fallback '{1}'.", this.EncodingName, encoder.Fallback.GetType()));
                    }
                    encoderFallbackBuffer.InternalInitialize(ptr, ptr2, encoder, false);
                }
            }
            for (;;)
            {
                char c2;
                char* ptr5;
                if ((c2 = ((encoderFallbackBuffer == null) ? '\0' : encoderFallbackBuffer.InternalGetNextChar())) != '\0' || chars < ptr2)
                {
                    if (c2 == '\0')
                    {
                        if ((this.bigEndian ^ BitConverter.IsLittleEndian) && c == '\0' && (chars & 7L) == null)
{
                            ulong* ptr4;
                            for (ptr4 = (ulong*)chars; ptr4 < ptr3; ptr4++)
{
                                if ((9223512776490647552UL & *ptr4) != 0UL)
{
                                    ulong num2 = (17870556004450629632UL & *ptr4) ^ 15564677810327967744UL;
                                    if (((num2 & 18446462598732840960UL) == 0UL || (num2 & 281470681743360UL) == 0UL || (num2 & (ulong)(-65536)) == 0UL || (num2 & 65535UL) == 0UL) && ((18158790778715962368UL & *ptr4) ^ UnicodeEncoding.highLowPatternMask) != 0UL)
{
                                        break;
                                    }
                                }
                            }
                            chars = (char*)ptr4;
                            if (chars >= ptr2)
{
                                goto IL_027E;
                            }
                        }
                        c2 = *chars;
                        chars++;
                    }
                    else
                    {
                        num += 2;
                    }
                    if (c2 >= '\ud800' && c2 <= '\udfff')
                    {
                        if (c2 <= '\udbff')
{
                            if (c > '\0')
{
                                chars--;
                                num -= 2;
                                if (encoderFallbackBuffer == null)
{
                                    if (encoder == null)
{
                                        encoderFallbackBuffer = this.encoderFallback.CreateFallbackBuffer();
                                    }
                                    else
{
                                        encoderFallbackBuffer = encoder.FallbackBuffer;
                                    }
                                    encoderFallbackBuffer.InternalInitialize(ptr, ptr2, encoder, false);
                                }
                                ptr5 = chars;
                                encoderFallbackBuffer.InternalFallback(c, ref ptr5);
                                chars = ptr5;
                                c = '\0';
                                continue;
                            }
                            c = c2;
                            continue;
                        }
                        else
{
                            if (c == '\0')
{
                                num -= 2;
                                if (encoderFallbackBuffer == null)
{
                                    if (encoder == null)
{
                                        encoderFallbackBuffer = this.encoderFallback.CreateFallbackBuffer();
                                    }
                                    else
{
                                        encoderFallbackBuffer = encoder.FallbackBuffer;
                                    }
                                    encoderFallbackBuffer.InternalInitialize(ptr, ptr2, encoder, false);
                                }
                                ptr5 = chars;
                                encoderFallbackBuffer.InternalFallback(c2, ref ptr5);
                                chars = ptr5;
                                continue;
                            }
                            c = '\0';
                            continue;
                        }
                    }
                    else
                    {
                        if (c > '\0')
{
                            chars--;
                            if (encoderFallbackBuffer == null)
{
                                if (encoder == null)
{
                                    encoderFallbackBuffer = this.encoderFallback.CreateFallbackBuffer();
                                }
                                else
{
                                    encoderFallbackBuffer = encoder.FallbackBuffer;
                                }
                                encoderFallbackBuffer.InternalInitialize(ptr, ptr2, encoder, false);
                            }
                            ptr5 = chars;
                            encoderFallbackBuffer.InternalFallback(c, ref ptr5);
                            chars = ptr5;
                            num -= 2;
                            c = '\0';
                            continue;
                        }
                        continue;
                    }
                }
                IL_027E:
                if (c <= '\0')
                {
                    return num;
                }
                num -= 2;
                if (encoder != null && !encoder.MustFlush)
                {
                    return num;
                }
                if (flag)
                {
                    break;
                }
                if (encoderFallbackBuffer == null)
                {
                    if (encoder == null)
                    {
                        encoderFallbackBuffer = this.encoderFallback.CreateFallbackBuffer();
                    }
                    else
                    {
                        encoderFallbackBuffer = encoder.FallbackBuffer;
                    }
                    encoderFallbackBuffer.InternalInitialize(ptr, ptr2, encoder, false);
                }
                ptr5 = chars;
                encoderFallbackBuffer.InternalFallback(c, ref ptr5);
                chars = ptr5;
                c = '\0';
                flag = true;
            }
            throw new ArgumentException(SR.Format("Recursive fallback not allowed for character \\\\u{0:X4}.", c), "chars");
        }
References System.Text.EncoderNLS._charLeftOver, System.Text.UnicodeEncoding.bigEndian, System.count, System.Text.EncoderFallback.CreateFallbackBuffer(), System.Text.Encoding.encoderFallback, System.Text.Encoder.Fallback, System.Text.Encoder.FallbackBuffer, SR.Format(), System.Text.UnicodeEncoding.highLowPatternMask, System.Text.EncoderFallbackBuffer.InternalFallback(), System.Text.EncoderFallbackBuffer.InternalGetNextChar(), System.Text.Encoder.InternalHasFallbackBuffer, System.Text.EncoderFallbackBuffer.InternalInitialize(), System.BitConverter.IsLittleEndian, System.L, System.Text.EncoderNLS.MustFlush, and System.Text.EncoderFallbackBuffer.Remaining.