Terraria Decompiled: System.Text.UnicodeEncoding.GetBytes
GetBytes() [2/4]
unsafe override int System.Text.UnicodeEncoding.GetBytes (char * chars, int charCount, byte * bytes, int byteCount, EncoderNLS encoder) inline package virtual
Reimplemented from System.Text.Encoding.
Definition at line 513 of file UnicodeEncoding.cs.
        {
            char c = '\0';
            bool flag = false;
            byte* ptr = bytes + byteCount;
            char* ptr2 = chars + charCount;
            byte* ptr3 = bytes;
            char* ptr4 = chars;
            EncoderFallbackBuffer encoderFallbackBuffer = null;
            if (encoder != null)
            {
                c = encoder._charLeftOver;
                if (encoder.InternalHasFallbackBuffer)
                {
                    encoderFallbackBuffer = encoder.FallbackBuffer;
                    if (encoderFallbackBuffer.Remaining > 0 && encoder._throwOnOverflow)
                    {
                        throw new ArgumentException(SR.Format("Must complete Convert() operation or call Encoder.Reset() before calling GetBytes() or GetByteCount(). Encoder '{0}' fallback '{1}'.", this.EncodingName, encoder.Fallback.GetType()));
                    }
                    encoderFallbackBuffer.InternalInitialize(ptr4, ptr2, encoder, false);
                }
            }
            for (;;)
            {
                char c2;
                char* ptr10;
                if ((c2 = ((encoderFallbackBuffer == null) ? '\0' : encoderFallbackBuffer.InternalGetNextChar())) != '\0' || chars < ptr2)
                {
                    if (c2 == '\0')
                    {
                        if ((this.bigEndian ^ BitConverter.IsLittleEndian) && (chars & 7L) == null && (bytes & 7L) == null && c == '\0')
{
                            ulong* ptr5 = (ulong*)(chars - 3 + (((long)(ptr - bytes) >> 1 < (long)(ptr2 - chars)) ? ((long)(ptr - bytes) >> 1) : ((long)(ptr2 - chars))) * 2L / 8L);
                            ulong* ptr6 = (ulong*)chars;
                            ulong* ptr7 = (ulong*)bytes;
                            while (ptr6 < ptr5)
{
                                if ((9223512776490647552UL & *ptr6) != 0UL)
{
                                    ulong num = (17870556004450629632UL & *ptr6) ^ 15564677810327967744UL;
                                    if (((num & 18446462598732840960UL) == 0UL || (num & 281470681743360UL) == 0UL || (num & (ulong)(-65536)) == 0UL || (num & 65535UL) == 0UL) && ((18158790778715962368UL & *ptr6) ^ UnicodeEncoding.highLowPatternMask) != 0UL)
{
                                        break;
                                    }
                                }
                                *ptr7 = *ptr6;
                                ptr6++;
                                ptr7++;
                            }
                            chars = (char*)ptr6;
                            bytes = (byte*)ptr7;
                            if (chars >= ptr2)
{
                                goto IL_0488;
                            }
                        }
                        else if (c == '\0' && (this.bigEndian ^ BitConverter.IsLittleEndian) && ((byte*)chars & 7L) != (bytes & 7L) && (bytes & 1) == 0)
{
                            long num2 = (((long)(ptr - bytes) >> 1 < (long)(ptr2 - chars)) ? ((long)(ptr - bytes) >> 1) : ((long)(ptr2 - chars)));
                            char* ptr8 = (char*)bytes;
                            char* ptr9 = chars + num2 * 2L / 2L - 1;
                            while (chars < ptr9)
{
                                if (*chars >= '\ud800' && *chars <= '\udfff')
{
                                    if (*chars >= '\udc00' || chars[1] < '\udc00')
{
                                        break;
                                    }
                                    if (chars[1] > '\udfff')
{
                                        break;
                                    }
                                }
                                else if (chars[1] >= '\ud800' && chars[1] <= '\udfff')
{
                                    *ptr8 = *chars;
                                    ptr8++;
                                    chars++;
                                    continue;
                                }
                                *ptr8 = *chars;
                                ptr8[1] = chars[1];
                                ptr8 += 2;
                                chars += 2;
                            }
                            bytes = (byte*)ptr8;
                            if (chars >= ptr2)
{
                                goto IL_0488;
                            }
                        }
                        c2 = *chars;
                        chars++;
                    }
                    if (c2 >= '\ud800' && c2 <= '\udfff')
                    {
                        if (c2 <= '\udbff')
{
                            if (c > '\0')
{
                                chars--;
                                if (encoderFallbackBuffer == null)
{
                                    if (encoder == null)
{
                                        encoderFallbackBuffer = this.encoderFallback.CreateFallbackBuffer();
                                    }
                                    else
{
                                        encoderFallbackBuffer = encoder.FallbackBuffer;
                                    }
                                    encoderFallbackBuffer.InternalInitialize(ptr4, ptr2, encoder, true);
                                }
                                ptr10 = chars;
                                encoderFallbackBuffer.InternalFallback(c, ref ptr10);
                                chars = ptr10;
                                c = '\0';
                                continue;
                            }
                            c = c2;
                            continue;
                        }
                        else
{
                            if (c == '\0')
{
                                if (encoderFallbackBuffer == null)
{
                                    if (encoder == null)
{
                                        encoderFallbackBuffer = this.encoderFallback.CreateFallbackBuffer();
                                    }
                                    else
{
                                        encoderFallbackBuffer = encoder.FallbackBuffer;
                                    }
                                    encoderFallbackBuffer.InternalInitialize(ptr4, ptr2, encoder, true);
                                }
                                ptr10 = chars;
                                encoderFallbackBuffer.InternalFallback(c2, ref ptr10);
                                chars = ptr10;
                                continue;
                            }
                            if (bytes + 3 >= ptr)
{
                                if (encoderFallbackBuffer != null && encoderFallbackBuffer.bFallingBack)
{
                                    encoderFallbackBuffer.MovePrevious();
                                    encoderFallbackBuffer.MovePrevious();
                                }
                                else
{
                                    chars -= 2;
                                }
                                base.ThrowBytesOverflow(encoder, bytes == ptr3);
                                c = '\0';
                                goto IL_0488;
                            }
                            if (this.bigEndian)
{
                                *(bytes++) = (byte)(c >> 8);
                                *(bytes++) = (byte)c;
                            }
                            else
{
                                *(bytes++) = (byte)c;
                                *(bytes++) = (byte)(c >> 8);
                            }
                            c = '\0';
                        }
                    }
                    else if (c > '\0')
                    {
                        chars--;
                        if (encoderFallbackBuffer == null)
{
                            if (encoder == null)
{
                                encoderFallbackBuffer = this.encoderFallback.CreateFallbackBuffer();
                            }
                            else
{
                                encoderFallbackBuffer = encoder.FallbackBuffer;
                            }
                            encoderFallbackBuffer.InternalInitialize(ptr4, ptr2, encoder, true);
                        }
                        ptr10 = chars;
                        encoderFallbackBuffer.InternalFallback(c, ref ptr10);
                        chars = ptr10;
                        c = '\0';
                        continue;
                    }
                    if (bytes + 1 >= ptr)
                    {
                        if (encoderFallbackBuffer != null && encoderFallbackBuffer.bFallingBack)
{
                            encoderFallbackBuffer.MovePrevious();
                        }
                        else
{
                            chars--;
                        }
                        base.ThrowBytesOverflow(encoder, bytes == ptr3);
                    }
                    else
                    {
                        if (this.bigEndian)
{
                            *(bytes++) = (byte)(c2 >> 8);
                            *(bytes++) = (byte)c2;
                            continue;
                        }
                        *(bytes++) = (byte)c2;
                        *(bytes++) = (byte)(c2 >> 8);
                        continue;
                    }
                }
                IL_0488:
                if (c <= '\0' || (encoder != null && !encoder.MustFlush))
                {
                    goto IL_0500;
                }
                if (flag)
                {
                    break;
                }
                if (encoderFallbackBuffer == null)
                {
                    if (encoder == null)
                    {
                        encoderFallbackBuffer = this.encoderFallback.CreateFallbackBuffer();
                    }
                    else
                    {
                        encoderFallbackBuffer = encoder.FallbackBuffer;
                    }
                    encoderFallbackBuffer.InternalInitialize(ptr4, ptr2, encoder, true);
                }
                ptr10 = chars;
                encoderFallbackBuffer.InternalFallback(c, ref ptr10);
                chars = ptr10;
                c = '\0';
                flag = true;
            }
            throw new ArgumentException(SR.Format("Recursive fallback not allowed for character \\\\u{0:X4}.", c), "chars");
            IL_0500:
            if (encoder != null)
            {
                encoder._charLeftOver = c;
                encoder._charsUsed = (int)((long)(chars - ptr4));
            }
            return (int)((long)(bytes - ptr3));
        }
References System.Text.EncoderNLS._charLeftOver, System.Text.EncoderNLS._throwOnOverflow, System.Text.EncoderFallbackBuffer.bFallingBack, System.Text.UnicodeEncoding.bigEndian, System.Text.EncoderFallback.CreateFallbackBuffer(), System.Text.Encoding.encoderFallback, System.Text.Encoder.Fallback, System.Text.Encoder.FallbackBuffer, SR.Format(), System.Text.UnicodeEncoding.highLowPatternMask, int, System.Text.EncoderFallbackBuffer.InternalFallback(), System.Text.EncoderFallbackBuffer.InternalGetNextChar(), System.Text.Encoder.InternalHasFallbackBuffer, System.Text.EncoderFallbackBuffer.InternalInitialize(), System.BitConverter.IsLittleEndian, System.L, long, System.Text.EncoderFallbackBuffer.MovePrevious(), System.Text.EncoderNLS.MustFlush, and System.Text.EncoderFallbackBuffer.Remaining.