Terraria Decompiled: System.Text.UnicodeEncoding.GetCharCount
GetCharCount() [2/3]
unsafe override int System.Text.UnicodeEncoding.GetCharCount (byte * bytes, int count, DecoderNLS baseDecoder) inline package virtual
Reimplemented from System.Text.Encoding.
Definition at line 769 of file UnicodeEncoding.cs.
        {
            UnicodeEncoding.Decoder decoder = (UnicodeEncoding.Decoder)baseDecoder;
            byte* ptr = bytes + count;
            byte* ptr2 = bytes;
            int num = -1;
            char c = '\0';
            int num2 = count >> 1;
            ulong* ptr3 = (ulong*)(ptr - 7);
            DecoderFallbackBuffer decoderFallbackBuffer = null;
            if (decoder != null)
            {
                num = decoder.lastByte;
                c = decoder.lastChar;
                if (c > '\0')
                {
                    num2++;
                }
                if (num >= 0 && (count & 1) == 1)
                {
                    num2++;
                }
            }
            while (bytes < ptr)
            {
                if ((this.bigEndian ^ BitConverter.IsLittleEndian) && (bytes & 7L) == null && num == -1 && c == '\0')
                {
                    ulong* ptr4;
                    for (ptr4 = (ulong*)bytes; ptr4 < ptr3; ptr4++)
                    {
                        if ((9223512776490647552UL & *ptr4) != 0UL)
{
                            ulong num3 = (17870556004450629632UL & *ptr4) ^ 15564677810327967744UL;
                            if (((num3 & 18446462598732840960UL) == 0UL || (num3 & 281470681743360UL) == 0UL || (num3 & (ulong)(-65536)) == 0UL || (num3 & 65535UL) == 0UL) && ((18158790778715962368UL & *ptr4) ^ UnicodeEncoding.highLowPatternMask) != 0UL)
{
                                break;
                            }
                        }
                    }
                    bytes = (byte*)ptr4;
                    if (bytes >= ptr)
                    {
                        break;
                    }
                }
                if (num < 0)
                {
                    num = (int)(*(bytes++));
                    if (bytes >= ptr)
                    {
                        break;
                    }
                }
                char c2;
                if (this.bigEndian)
                {
                    c2 = (char)((num << 8) | (int)(*(bytes++)));
                }
                else
                {
                    c2 = (char)(((int)(*(bytes++)) << 8) | num);
                }
                num = -1;
                if (c2 >= '\ud800' && c2 <= '\udfff')
                {
                    if (c2 <= '\udbff')
                    {
                        if (c > '\0')
{
                            num2--;
                            byte[] array;
                            if (this.bigEndian)
{
                                array = new byte[]
{
                                    (byte)(c >> 8),
                                    (byte)c
                                };
                            }
                            else
{
                                array = new byte[]
{
                                    (byte)c,
                                    (byte)(c >> 8)
                                };
                            }
                            if (decoderFallbackBuffer == null)
{
                                if (decoder == null)
{
                                    decoderFallbackBuffer = this.decoderFallback.CreateFallbackBuffer();
                                }
                                else
{
                                    decoderFallbackBuffer = decoder.FallbackBuffer;
                                }
                                decoderFallbackBuffer.InternalInitialize(ptr2, null);
                            }
                            num2 += decoderFallbackBuffer.InternalFallback(array, bytes);
                        }
                        c = c2;
                    }
                    else if (c == '\0')
                    {
                        num2--;
                        byte[] array2;
                        if (this.bigEndian)
{
                            array2 = new byte[]
{
                                (byte)(c2 >> 8),
                                (byte)c2
                            };
                        }
                        else
{
                            array2 = new byte[]
{
                                (byte)c2,
                                (byte)(c2 >> 8)
                            };
                        }
                        if (decoderFallbackBuffer == null)
{
                            if (decoder == null)
{
                                decoderFallbackBuffer = this.decoderFallback.CreateFallbackBuffer();
                            }
                            else
{
                                decoderFallbackBuffer = decoder.FallbackBuffer;
                            }
                            decoderFallbackBuffer.InternalInitialize(ptr2, null);
                        }
                        num2 += decoderFallbackBuffer.InternalFallback(array2, bytes);
                    }
                    else
                    {
                        c = '\0';
                    }
                }
                else if (c > '\0')
                {
                    num2--;
                    byte[] array3;
                    if (this.bigEndian)
                    {
                        array3 = new byte[]
{
                            (byte)(c >> 8),
                            (byte)c
                        };
                    }
                    else
                    {
                        array3 = new byte[]
{
                            (byte)c,
                            (byte)(c >> 8)
                        };
                    }
                    if (decoderFallbackBuffer == null)
                    {
                        if (decoder == null)
{
                            decoderFallbackBuffer = this.decoderFallback.CreateFallbackBuffer();
                        }
                        else
{
                            decoderFallbackBuffer = decoder.FallbackBuffer;
                        }
                        decoderFallbackBuffer.InternalInitialize(ptr2, null);
                    }
                    num2 += decoderFallbackBuffer.InternalFallback(array3, bytes);
                    c = '\0';
                }
            }
            if (decoder == null || decoder.MustFlush)
            {
                if (c > '\0')
                {
                    num2--;
                    byte[] array4;
                    if (this.bigEndian)
                    {
                        array4 = new byte[]
{
                            (byte)(c >> 8),
                            (byte)c
                        };
                    }
                    else
                    {
                        array4 = new byte[]
{
                            (byte)c,
                            (byte)(c >> 8)
                        };
                    }
                    if (decoderFallbackBuffer == null)
                    {
                        if (decoder == null)
{
                            decoderFallbackBuffer = this.decoderFallback.CreateFallbackBuffer();
                        }
                        else
{
                            decoderFallbackBuffer = decoder.FallbackBuffer;
                        }
                        decoderFallbackBuffer.InternalInitialize(ptr2, null);
                    }
                    num2 += decoderFallbackBuffer.InternalFallback(array4, bytes);
                    c = '\0';
                }
                if (num >= 0)
                {
                    if (decoderFallbackBuffer == null)
                    {
                        if (decoder == null)
{
                            decoderFallbackBuffer = this.decoderFallback.CreateFallbackBuffer();
                        }
                        else
{
                            decoderFallbackBuffer = decoder.FallbackBuffer;
                        }
                        decoderFallbackBuffer.InternalInitialize(ptr2, null);
                    }
                    num2 += decoderFallbackBuffer.InternalFallback(new byte[] { (byte)num }, bytes);
                }
            }
            if (c > '\0')
            {
                num2--;
            }
            return num2;
        }
References System.array, System.Text.UnicodeEncoding.bigEndian, System.count, System.Text.DecoderFallback.CreateFallbackBuffer(), System.Text.Encoding.decoderFallback, System.Text.Decoder.FallbackBuffer, System.Text.UnicodeEncoding.highLowPatternMask, int, System.Text.DecoderFallbackBuffer.InternalFallback(), System.Text.DecoderFallbackBuffer.InternalInitialize(), System.BitConverter.IsLittleEndian, System.L, System.Text.UnicodeEncoding.Decoder.lastByte, System.Text.UnicodeEncoding.Decoder.lastChar, and System.Text.DecoderNLS.MustFlush.