Terraria Decompiled: System.Security.Cryptography.PasswordDeriveBytes.ComputeBaseValue
ComputeBaseValue()
byte[] System.Security.Cryptography.PasswordDeriveBytes.ComputeBaseValue () inline private
Definition at line 228 of file PasswordDeriveBytes.cs.
        {
            this._hash.Initialize();
            this._hash.TransformBlock(this._password, 0, this._password.Length, this._password, 0);
            if (this._salt != null)
            {
                this._hash.TransformBlock(this._salt, 0, this._salt.Length, this._salt, 0);
            }
            this._hash.TransformFinalBlock(EmptyArray<byte>.Value, 0, 0);
            this._baseValue = this._hash.Hash;
            this._hash.Initialize();
            for (int i = 1; i < this._iterations - 1; i++)
            {
                this._hash.ComputeHash(this._baseValue);
                this._baseValue = this._hash.Hash;
            }
            return this._baseValue;
        }
References System.Security.Cryptography.PasswordDeriveBytes._baseValue, System.Security.Cryptography.PasswordDeriveBytes._hash, System.Security.Cryptography.PasswordDeriveBytes._password, System.Security.Cryptography.PasswordDeriveBytes._salt, System.Security.Cryptography.HashAlgorithm.ComputeHash(), System.Security.Cryptography.HashAlgorithm.Hash, System.Security.Cryptography.HashAlgorithm.Initialize(), System.Security.Cryptography.HashAlgorithm.TransformBlock(), and System.Security.Cryptography.HashAlgorithm.TransformFinalBlock().
Referenced by System.Security.Cryptography.PasswordDeriveBytes.GetBytes().