Terraria Decompiled: System.Security.Cryptography.PasswordDeriveBytes.GetBytes
GetBytes()
override byte[] System.Security.Cryptography.PasswordDeriveBytes.GetBytes (int cb) inline
Definition at line 138 of file PasswordDeriveBytes.cs.
        {
            if (cb < 1)
            {
                throw new IndexOutOfRangeException("cb");
            }
            int num = 0;
            byte[] array = new byte[cb];
            if (this._baseValue == null)
            {
                this.ComputeBaseValue();
            }
            else if (this._extra != null)
            {
                num = this._extra.Length - this._extraCount;
                if (num >= cb)
                {
                    Buffer.InternalBlockCopy(this._extra, this._extraCount, array, 0, cb);
                    if (num > cb)
                    {
                        this._extraCount += cb;
                    }
                    else
                    {
                        this._extra = null;
                    }
                    return array;
                }
                Buffer.InternalBlockCopy(this._extra, num, array, 0, num);
                this._extra = null;
            }
            byte[] array2 = this.ComputeBytes(cb - num);
            Buffer.InternalBlockCopy(array2, 0, array, num, cb - num);
            if (array2.Length + num > cb)
            {
                this._extra = array2;
                this._extraCount = cb - num;
            }
            return array;
        }
References System.Security.Cryptography.PasswordDeriveBytes._baseValue, System.Security.Cryptography.PasswordDeriveBytes._extra, System.Security.Cryptography.PasswordDeriveBytes._extraCount, System.array, System.Security.Cryptography.PasswordDeriveBytes.ComputeBaseValue(), System.Security.Cryptography.PasswordDeriveBytes.ComputeBytes(), and System.Buffer.InternalBlockCopy().