Terraria Decompiled: System.Security.Cryptography.PasswordDeriveBytes.ComputeBytes
ComputeBytes()
byte[] System.Security.Cryptography.PasswordDeriveBytes.ComputeBytes (int cb) inline private
Definition at line 249 of file PasswordDeriveBytes.cs.
        {
            int num = 0;
            this._hash.Initialize();
            int num2 = this._hash.HashSize / 8;
            byte[] array = new byte[(cb + num2 - 1) / num2 * num2];
            using (CryptoStream cryptoStream = new CryptoStream(Stream.Null, this._hash, CryptoStreamMode.Write))
            {
                this.HashPrefix(cryptoStream);
                cryptoStream.Write(this._baseValue, 0, this._baseValue.Length);
                cryptoStream.Close();
            }
            Buffer.InternalBlockCopy(this._hash.Hash, 0, array, num, num2);
            num += num2;
            while (cb > num)
            {
                this._hash.Initialize();
                using (CryptoStream cryptoStream2 = new CryptoStream(Stream.Null, this._hash, CryptoStreamMode.Write))
                {
                    this.HashPrefix(cryptoStream2);
                    cryptoStream2.Write(this._baseValue, 0, this._baseValue.Length);
                    cryptoStream2.Close();
                }
                Buffer.InternalBlockCopy(this._hash.Hash, 0, array, num, num2);
                num += num2;
            }
            return array;
        }
References System.Security.Cryptography.PasswordDeriveBytes._baseValue, System.Security.Cryptography.PasswordDeriveBytes._hash, System.array, System.IO.Stream.Close(), System.Security.Cryptography.HashAlgorithm.Hash, System.Security.Cryptography.PasswordDeriveBytes.HashPrefix(), System.Security.Cryptography.HashAlgorithm.Initialize(), System.Buffer.InternalBlockCopy(), System.IO.Stream.Null, System.IO.Stream.Write(), and System.Security.Cryptography.CryptoStream.Write().
Referenced by System.Security.Cryptography.PasswordDeriveBytes.GetBytes().