Terraria Decompiled: Terraria.Graphics.Renderers.FadingParticle.Draw
Draw()
override void Terraria.Graphics.Renderers.FadingParticle.Draw (ref ParticleRendererSettings settings, SpriteBatch spritebatch) inline
Implements Terraria.Graphics.Renderers.IParticle.
Definition at line 47 of file FadingParticle.cs.
        {
            Vector2 vector = settings.AnchorPosition + this.LocalPosition;
            if (this.followPlayerIndex != -1)
            {
                vector += Main.player[this.followPlayerIndex].MountedCenter;
            }
            Color color = (this.fullbright ? this.ColorTint : this.ColorTint.MultiplyRGB(Lighting.GetColor(this.LocalPosition.ToTileCoordinates()))) * Utils.GetLerpValue(0f, this.FadeInNormalizedTime, this.timeSinceSpawn / this.timeTolive, true) * Utils.GetLerpValue(1f, this.FadeOutNormalizedTime, this.timeSinceSpawn / this.timeTolive, true);
            spritebatch.Draw(this._texture.Value, vector, new Rectangle?(this._frame), color, this.Rotation, this._origin, this.Scale, SpriteEffects.None, 0f);
        }
References Terraria.Graphics.Renderers.ABasicParticle._origin, Terraria.Graphics.Renderers.ABasicParticle._texture, Terraria.Graphics.Renderers.FadingParticle.ColorTint, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Graphics.Renderers.FadingParticle.FadeOutNormalizedTime, Terraria.Graphics.Renderers.FadingParticle.followPlayerIndex, Terraria.Lighting.GetColor(), Terraria.Utils.GetLerpValue(), Terraria.Graphics.Renderers.ABasicParticle.LocalPosition, Terraria.Player.MountedCenter, Terraria.Main.player, Terraria.Graphics.Renderers.ABasicParticle.Rotation, Terraria.Graphics.Renderers.ABasicParticle.Scale, Terraria.Graphics.Renderers.FadingParticle.timeSinceSpawn, Terraria.Graphics.Renderers.FadingParticle.timeTolive, and ReLogic.Content.Asset< T >.Value.