Terraria Decompiled: Mono.Security.Cryptography.BlockProcessor.Core
Core() [2/2]
void Mono.Security.Cryptography.BlockProcessor.Core (byte[] rgb, int ib, int cb) inline
Definition at line 51 of file BlockProcessor.cs.
        {
            int num = Math.Min(this.blockSize - this.blockCount, cb);
            Buffer.BlockCopy(rgb, ib, this.block, this.blockCount, num);
            this.blockCount += num;
            if (this.blockCount == this.blockSize)
            {
                this.transform.TransformBlock(this.block, 0, this.blockSize, this.block, 0);
                int num2 = (cb - num) / this.blockSize;
                for (int i = 0; i < num2; i++)
                {
                    this.transform.TransformBlock(rgb, num + ib, this.blockSize, this.block, 0);
                    num += this.blockSize;
                }
                this.blockCount = cb - num;
                if (this.blockCount > 0)
                {
                    Buffer.BlockCopy(rgb, num + ib, this.block, 0, this.blockCount);
                }
            }
        }
References Mono.Security.Cryptography.BlockProcessor.block, System.Buffer.BlockCopy(), Mono.Security.Cryptography.BlockProcessor.blockCount, Mono.Security.Cryptography.BlockProcessor.blockSize, System.Math.Min(), Mono.Security.Cryptography.BlockProcessor.transform, and System.Security.Cryptography.ICryptoTransform.TransformBlock().