Terraria Decompiled: System.Enum.EnumResult.GetEnumParseException
GetEnumParseException()
Exception System.Enum.EnumResult.GetEnumParseException () inline package
Definition at line 1064 of file Enum.cs.
            {
                switch (this.m_failure)
                {
                case Enum.ParseFailureKind.Argument:
                    return new ArgumentException(Environment.GetResourceString(this.m_failureMessageID));
                case Enum.ParseFailureKind.ArgumentNull:
                    return new ArgumentNullException(this.m_failureParameter);
                case Enum.ParseFailureKind.ArgumentWithParameter:
                    return new ArgumentException(Environment.GetResourceString(this.m_failureMessageID, new object[] { this.m_failureMessageFormatArgument }));
                case Enum.ParseFailureKind.UnhandledException:
                    return this.m_innerException;
                default:
                    return new ArgumentException(Environment.GetResourceString("Requested value '{0}' was not found."));
                }
            }
References System.Environment.GetResourceString(), System.Enum.EnumResult.m_failure, System.Enum.EnumResult.m_failureParameter, and System.Enum.EnumResult.m_innerException.
Referenced by System.Enum.Parse(), System.Enum.Parse< TEnum >(), System.Enum.EnumResult.SetFailure(), and System.Enum.EnumResult.SetFailure().