Terraria Decompiled: System.Security.Policy.FirstMatchCodeGroup.CopyNoChildren
CopyNoChildren()
FirstMatchCodeGroup System.Security.Policy.FirstMatchCodeGroup.CopyNoChildren () inline private
Definition at line 90 of file FirstMatchCodeGroup.cs.
        {
            return new FirstMatchCodeGroup(base.MembershipCondition, base.PolicyStatement)
            {
                Name = base.Name,
                Description = base.Description
            };
        }
References System.Security.Policy.CodeGroup.Description, System.Security.Policy.FirstMatchCodeGroup.FirstMatchCodeGroup(), and System.Security.Policy.CodeGroup.Name.
Referenced by System.Security.Policy.FirstMatchCodeGroup.Copy(), and System.Security.Policy.FirstMatchCodeGroup.ResolveMatchingCodeGroups().