Terraria Decompiled: Newtonsoft.Json.Utilities.JavaScriptUtils.ToEscapedJavaScriptString
ToEscapedJavaScriptString()
static string Newtonsoft.Json.Utilities.JavaScriptUtils.ToEscapedJavaScriptString (string value, char delimiter, bool appendDelimiters, StringEscapeHandling stringEscapeHandling) inline static
Definition at line 229 of file JavaScriptUtils.cs.
        {
            bool[] charEscapeFlags = JavaScriptUtils.GetCharEscapeFlags(stringEscapeHandling, delimiter);
            string text;
            using (StringWriter stringWriter = StringUtils.CreateStringWriter((value != null) ? value.Length : 16))
            {
                char[] array = null;
                JavaScriptUtils.WriteEscapedJavaScriptString(stringWriter, value, delimiter, appendDelimiters, charEscapeFlags, stringEscapeHandling, null, ref array);
                text = stringWriter.ToString();
            }
            return text;
        }
References System.array, Newtonsoft.Json.Utilities.StringUtils.CreateStringWriter(), Newtonsoft.Json.Utilities.JavaScriptUtils.GetCharEscapeFlags(), System.text, System.IO.StringWriter.ToString(), System.value, and Newtonsoft.Json.Utilities.JavaScriptUtils.WriteEscapedJavaScriptString().
Referenced by Newtonsoft.Json.JsonConvert.ToString().