Terraria Decompiled: Newtonsoft.Json.Utilities.JavaScriptUtils.WriteEscapedJavaScriptString
WriteEscapedJavaScriptString()
static void Newtonsoft.Json.Utilities.JavaScriptUtils.WriteEscapedJavaScriptString (TextWriter writer, string s, char delimiter, bool appendDelimiters, bool[] charEscapeFlags, StringEscapeHandling stringEscapeHandling, IArrayPool< char > bufferPool, ref char[] writeBuffer) inline static
Definition at line 73 of file JavaScriptUtils.cs.
        {
            if (appendDelimiters)
            {
                writer.Write(delimiter);
            }
            if (!string.IsNullOrEmpty(s))
            {
                int num = JavaScriptUtils.FirstCharToEscape(s, charEscapeFlags, stringEscapeHandling);
                if (num == -1)
                {
                    writer.Write(s);
                }
                else
                {
                    if (num != 0)
                    {
                        if (writeBuffer == null || writeBuffer.Length < num)
{
                            writeBuffer = BufferUtils.EnsureBufferSize(bufferPool, num, writeBuffer);
                        }
                        s.CopyTo(0, writeBuffer, 0, num);
                        writer.Write(writeBuffer, 0, num);
                    }
                    int num2;
                    for (int i = num; i < s.Length; i++)
                    {
                        char c = s.get_Chars(i);
                        if ((int)c >= charEscapeFlags.Length || charEscapeFlags[(int)c])
{
                            string text;
                            if (c <= '\\')
{
                                switch (c)
{
                                case '\b':
                                    text = "\\b";
                                    break;
                                case '\t':
                                    text = "\\t";
                                    break;
                                case '\n':
                                    text = "\\n";
                                    break;
                                case '\v':
                                    goto IL_012A;
                                case '\f':
                                    text = "\\f";
                                    break;
                                case '\r':
                                    text = "\\r";
                                    break;
                                default:
                                    if (c != '\\')
{
                                        goto IL_012A;
                                    }
                                    text = "\\\\";
                                    break;
                                }
                            }
                            else if (c != '\u0085')
{
                                if (c != '\u2028')
{
                                    if (c != '\u2029')
{
                                        goto IL_012A;
                                    }
                                    text = "\\u2029";
                                }
                                else
{
                                    text = "\\u2028";
                                }
                            }
                            else
{
                                text = "\\u0085";
                            }
                            IL_018C:
                            if (text == null)
{
                                goto IL_022D;
                            }
                            bool flag = string.Equals(text, "!");
                            if (i > num)
{
                                num2 = i - num + (flag ? 6 : 0);
                                int num3 = (flag ? 6 : 0);
                                if (writeBuffer == null || writeBuffer.Length < num2)
{
                                    char[] array = BufferUtils.RentBuffer(bufferPool, num2);
                                    if (flag)
{
                                        Array.Copy(writeBuffer, array, 6);
                                    }
                                    BufferUtils.ReturnBuffer(bufferPool, writeBuffer);
                                    writeBuffer = array;
                                }
                                s.CopyTo(num, writeBuffer, num3, num2 - num3);
                                writer.Write(writeBuffer, num3, num2 - num3);
                            }
                            num = i + 1;
                            if (!flag)
{
                                writer.Write(text);
                                goto IL_022D;
                            }
                            writer.Write(writeBuffer, 0, 6);
                            goto IL_022D;
                            IL_012A:
                            if ((int)c >= charEscapeFlags.Length && stringEscapeHandling != StringEscapeHandling.EscapeNonAscii)
{
                                text = null;
                                goto IL_018C;
                            }
                            if (c == '\'' && stringEscapeHandling != StringEscapeHandling.EscapeHtml)
{
                                text = "\\'";
                                goto IL_018C;
                            }
                            if (c == '"' && stringEscapeHandling != StringEscapeHandling.EscapeHtml)
{
                                text = "\\\"";
                                goto IL_018C;
                            }
                            if (writeBuffer == null || writeBuffer.Length < 6)
{
                                writeBuffer = BufferUtils.EnsureBufferSize(bufferPool, 6, writeBuffer);
                            }
                            StringUtils.ToCharAsUnicode(c, writeBuffer);
                            text = "!";
                            goto IL_018C;
                        }
                        IL_022D:;
                    }
                    num2 = s.Length - num;
                    if (num2 > 0)
                    {
                        if (writeBuffer == null || writeBuffer.Length < num2)
{
                            writeBuffer = BufferUtils.EnsureBufferSize(bufferPool, num2, writeBuffer);
                        }
                        s.CopyTo(num, writeBuffer, 0, num2);
                        writer.Write(writeBuffer, 0, num2);
                    }
                }
            }
            if (appendDelimiters)
            {
                writer.Write(delimiter);
            }
        }
References System.array, System.Array.Copy(), Newtonsoft.Json.Utilities.BufferUtils.EnsureBufferSize(), Newtonsoft.Json.Utilities.JavaScriptUtils.FirstCharToEscape(), Newtonsoft.Json.Utilities.BufferUtils.RentBuffer(), Newtonsoft.Json.Utilities.BufferUtils.ReturnBuffer(), System.s, System.text, Newtonsoft.Json.Utilities.StringUtils.ToCharAsUnicode(), and System.IO.TextWriter.Write().
Referenced by Newtonsoft.Json.Utilities.JavaScriptUtils.ToEscapedJavaScriptString(), and Newtonsoft.Json.JsonTextWriter.WriteEscapedString().