Terraria Decompiled: Terraria.GameContent.UI.Elements.UIIconTextButton.DrawSelf
DrawSelf()
override void Terraria.GameContent.UI.Elements.UIIconTextButton.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 60 of file UIIconTextButton.cs.
        {
            if (this._hovered)
            {
                if (!this._soundedHover)
                {
                    SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                }
                this._soundedHover = true;
            }
            else
            {
                this._soundedHover = false;
            }
            CalculatedStyle dimensions = base.GetDimensions();
            Color color = this._color;
            float opacity = this._opacity;
            Utils.DrawSplicedPanel(spriteBatch, this._BasePanelTexture.Value, (int)dimensions.X, (int)dimensions.Y, (int)dimensions.Width, (int)dimensions.Height, 10, 10, 10, 10, Color.Lerp(Color.Black, color, this.FadeFromBlack) * opacity);
            if (this._iconTexture != null)
            {
                Color color2 = Color.Lerp(color, Color.White, this._whiteLerp) * opacity;
                spriteBatch.Draw(this._iconTexture.Value, new Vector2(dimensions.X + dimensions.Width - (float)this._iconTexture.Width() - 5f, dimensions.Center().Y - (float)(this._iconTexture.Height() / 2)), color2);
            }
        }
References Terraria.GameContent.UI.Elements.UIIconTextButton._BasePanelTexture, Terraria.GameContent.UI.Elements.UIIconTextButton._color, Terraria.GameContent.UI.Elements.UIIconTextButton._hovered, Terraria.GameContent.UI.Elements.UIIconTextButton._iconTexture, Terraria.GameContent.UI.Elements.UIIconTextButton._opacity, Terraria.GameContent.UI.Elements.UIIconTextButton._soundedHover, Microsoft.Xna.Framework.Color.Black, Terraria.UI.CalculatedStyle.Center(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Utils.DrawSplicedPanel(), Terraria.UI.CalculatedStyle.Height, Microsoft.Xna.Framework.Color.Lerp(), Terraria.Audio.SoundEngine.PlaySound(), ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Color.White, Terraria.UI.CalculatedStyle.Width, Terraria.UI.CalculatedStyle.X, Microsoft.Xna.Framework.Vector2.Y, and Terraria.UI.CalculatedStyle.Y.