Terraria Decompiled: Terraria.GameContent.UI.Elements.UIIconTextButton.SetText
SetText()
void Terraria.GameContent.UI.Elements.UIIconTextButton.SetText (LocalizedText text, float textSize, Color color) inline
Definition at line 35 of file UIIconTextButton.cs.
        {
            if (this._title != null)
            {
                this._title.Remove();
            }
            UIText uitext = new UIText(text, textSize, false)
            {
                HAlign = 0f,
                VAlign = 0.5f,
                Top = StyleDimension.FromPixels(0f),
                Left = StyleDimension.FromPixelsAndPercent(10f, 0f),
                IgnoresMouseInteraction = true
            };
            uitext.TextColor = color;
            base.Append(uitext);
            this._title = uitext;
            if (this._iconTexture != null)
            {
                this.Width.Set(this._title.GetDimensions().Width + (float)this._iconTexture.Width() + 26f, 0f);
                this.Height.Set(Math.Max(this._title.GetDimensions().Height, (float)this._iconTexture.Height()) + 16f, 0f);
            }
        }
References Terraria.GameContent.UI.Elements.UIIconTextButton._iconTexture, Terraria.GameContent.UI.Elements.UIIconTextButton._title, Terraria.UI.StyleDimension.FromPixels(), Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.UI.UIElement.GetDimensions(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.IgnoresMouseInteraction, Terraria.UI.UIElement.Left, System.Math.Max(), Terraria.UI.UIElement.Remove(), Terraria.UI.StyleDimension.Set(), System.text, Terraria.UI.UIElement.Top, Terraria.UI.UIElement.VAlign, Terraria.UI.CalculatedStyle.Width, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.Elements.UIIconTextButton.UIIconTextButton().