Terraria Decompiled: Terraria.WorldBuilding.TileFont.VLineLabel
VLineLabel()
static void Terraria.WorldBuilding.TileFont.VLineLabel (Point start, int height, string text, TileFont::DrawMode mode, bool bottomText = false) inline static
Definition at line 96 of file TileFont.cs.
        {
            Point point = TileFont.MeasureString(text);
            for (int i = start.Y; i < start.Y + height; i++)
            {
                Main.tile[start.X, i].ResetToType(mode.ForegroundTile);
                WorldGen.TileFrame(start.X, i, false, false);
            }
            TileFont.DrawString(new Point(start.X - point.X / 2, bottomText ? (start.Y + height + 1) : (start.Y - point.Y - 1)), text, mode);
        }
References Terraria.WorldBuilding.TileFont.DrawString(), Terraria.WorldBuilding.TileFont.MeasureString(), System.mode, Terraria.Tile.ResetToType(), System.start, System.text, Terraria.Main.tile, Terraria.WorldGen.TileFrame(), and Microsoft.Xna.Framework.Point.X.