Terraria Decompiled: Terraria.WorldBuilding.TileFont.DrawString
DrawString()
static void Terraria.WorldBuilding.TileFont.DrawString (Point start, string text, TileFont::DrawMode mode) inline static
Definition at line 11 of file TileFont.cs.
        {
            Point point = start;
            foreach (char c in text)
            {
                if (c == '\n')
                {
                    point.X = start.X;
                    point.Y += 6;
                }
                byte[] array;
                if (TileFont.MicroFont.TryGetValue(c, out array))
                {
                    TileFont.DrawChar(point, array, mode);
                    point.X += 6;
                }
            }
        }
References System.array, Terraria.WorldBuilding.TileFont.DrawChar(), Terraria.WorldBuilding.TileFont.MicroFont, System.mode, System.start, System.text, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and Microsoft.Xna.Framework.Point.X.
Referenced by Terraria.WorldBuilding.TileFont.HLineLabel(), and Terraria.WorldBuilding.TileFont.VLineLabel().