Terraria Decompiled: Terraria.LinuxLaunch.Main
Main()
static void Terraria.LinuxLaunch.Main (string[] args) inline static private
Definition at line 12 of file LinuxLaunch.cs.
        {
            AppDomain.CurrentDomain.AssemblyResolve += delegate(object sender, ResolveEventArgs sargs)
            {
                string resourceName = new AssemblyName(sargs.Name).Name + ".dll";
                string text = Array.Find<string>(typeof(Program).Assembly.GetManifestResourceNames(), (string element) => element.EndsWith(resourceName));
                if (text == null)
                {
                    return null;
                }
                Assembly assembly;
                using (Stream manifestResourceStream = Assembly.GetExecutingAssembly().GetManifestResourceStream(text))
                {
                    byte[] array = new byte[manifestResourceStream.Length];
                    manifestResourceStream.Read(array, 0, array.Length);
                    assembly = Assembly.Load(array);
                }
                return assembly;
            };
            Environment.SetEnvironmentVariable("FNA_WORKAROUND_WINDOW_RESIZABLE", "1");
            Program.LaunchGame(args, true);
        }
References System.array, System.Reflection.Assembly.GetExecutingAssembly(), System.Reflection.Assembly.GetManifestResourceStream(), Terraria.Program.LaunchGame(), System.IO.Stream.Length, System.Reflection.Assembly.Load(), System.Reflection.AssemblyName.Name, System.ResolveEventArgs.Name, System.IO.Stream.Read(), and System.text.