Terraria Decompiled: Terraria.WorldBuilding.TileFont.DrawChar
DrawChar()
static void Terraria.WorldBuilding.TileFont.DrawChar (Point position, byte[] charData, TileFont::DrawMode mode) inline static private
Definition at line 31 of file TileFont.cs.
        {
            if (mode.HasBackground)
            {
                for (int i = -1; i < charData.Length + 1; i++)
                {
                    for (int j = -1; j < 6; j++)
                    {
                        Main.tile[position.X + j, position.Y + i].ResetToType(mode.BackgroundTile);
                        WorldGen.TileFrame(position.X + j, position.Y + i, false, false);
                    }
                }
            }
            for (int k = 0; k < charData.Length; k++)
            {
                int num = (int)charData[k] << 1;
                for (int l = 0; l < 5; l++)
                {
                    if ((num & 128) == 128)
                    {
                        Main.tile[position.X + l, position.Y + k].ResetToType(mode.ForegroundTile);
                        WorldGen.TileFrame(position.X + l, position.Y + k, false, false);
                    }
                    num <<= 1;
                }
            }
        }
References int, System.mode, Terraria.Tile.ResetToType(), Terraria.Main.tile, Terraria.WorldGen.TileFrame(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.WorldBuilding.TileFont.DrawString().