Terraria Decompiled: Terraria.WorldBuilding.TileFont.MeasureString
MeasureString()
static Point Terraria.WorldBuilding.TileFont.MeasureString (string text) inline static
Definition at line 60 of file TileFont.cs.
        {
            Point zero = Point.Zero;
            Point point = zero;
            Point point2 = new Point(0, 5);
            foreach (char c in text)
            {
                if (c == '\n')
                {
                    point.X = zero.X;
                    point.Y += 6;
                    point2.Y = point.Y + 5;
                }
                byte[] array;
                if (TileFont.MicroFont.TryGetValue(c, out array))
                {
                    point.X += 6;
                    point2.X = Math.Max(point2.X, point.X - 1);
                }
            }
            return point2;
        }
References System.array, System.Math.Max(), Terraria.WorldBuilding.TileFont.MicroFont, System.text, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and Microsoft.Xna.Framework.Point.Zero.
Referenced by Terraria.WorldBuilding.TileFont.HLineLabel(), and Terraria.WorldBuilding.TileFont.VLineLabel().