Terraria Decompiled: Newtonsoft.Json.Utilities.BufferUtils.EnsureBufferSize
EnsureBufferSize()
static char[] Newtonsoft.Json.Utilities.BufferUtils.EnsureBufferSize (IArrayPool< char > bufferPool, int size, char[] buffer) inline static
Definition at line 28 of file BufferUtils.cs.
        {
            if (bufferPool == null)
            {
                return new char[size];
            }
            if (buffer != null)
            {
                bufferPool.Return(buffer);
            }
            return bufferPool.Rent(size);
        }
References Newtonsoft.Json.IArrayPool< T >.Rent(), and Newtonsoft.Json.IArrayPool< T >.Return().
Referenced by Newtonsoft.Json.Utilities.JavaScriptUtils.WriteEscapedJavaScriptString().