Terraria Decompiled: Newtonsoft.Json.Utilities.BufferUtils.ReturnBuffer
ReturnBuffer()
static void Newtonsoft.Json.Utilities.BufferUtils.ReturnBuffer (IArrayPool< char > bufferPool, char[] buffer) inline static
Definition at line 19 of file BufferUtils.cs.
        {
            if (bufferPool != null)
            {
                bufferPool.Return(buffer);
            }
        }
References Newtonsoft.Json.IArrayPool< T >.Return().
Referenced by Newtonsoft.Json.Utilities.StringBuffer.Clear(), Newtonsoft.Json.JsonTextReader.Close(), Newtonsoft.Json.JsonTextWriter.CloseBufferAndWriter(), Newtonsoft.Json.Utilities.StringBuffer.EnsureSize(), Newtonsoft.Json.JsonTextReader.PrepareBufferForReadData(), and Newtonsoft.Json.Utilities.JavaScriptUtils.WriteEscapedJavaScriptString().