Terraria Decompiled: System.Variant.GetValue
GetValue()
object System.Variant.GetValue () inline
Definition at line 190 of file Variant.cs.
        {
            object obj = null;
            switch (this.vt)
            {
            case 2:
                return this.iVal;
            case 3:
                return this.lVal;
            case 4:
                return this.fltVal;
            case 5:
                return this.dblVal;
            case 8:
                return Marshal.PtrToStringBSTR(this.bstrVal);
            case 9:
            case 13:
                if (this.pdispVal != IntPtr.Zero)
                {
                    return Marshal.GetObjectForIUnknown(this.pdispVal);
                }
                return obj;
            case 11:
                return this.boolVal != 0;
            case 16:
                return this.cVal;
            case 17:
                return this.bVal;
            case 18:
                return this.uiVal;
            case 19:
                return this.ulVal;
            case 20:
                return this.llVal;
            case 21:
                return this.ullVal;
            }
            if ((this.vt & 16384) == 16384 && this.pdispVal != IntPtr.Zero)
            {
                obj = Variant.GetValueAt((int)(this.vt & -16385), this.pdispVal);
            }
            return obj;
        }
References System.Variant.bstrVal, System.Variant.bVal, System.Variant.cVal, System.Variant.dblVal, System.Variant.fltVal, System.Runtime.InteropServices.Marshal.GetObjectForIUnknown(), System.Variant.GetValueAt(), System.Variant.iVal, System.Variant.llVal, System.Variant.lVal, System.obj, System.Variant.pdispVal, System.Runtime.InteropServices.Marshal.PtrToStringBSTR(), System.Variant.uiVal, System.Variant.ullVal, System.Variant.ulVal, System.Variant.vt, and System.IntPtr.Zero.