Terraria Decompiled: System.Variant.SetValue
SetValue()
void System.Variant.SetValue (object obj) inline
Definition at line 11 of file Variant.cs.
        {
            this.vt = 0;
            if (obj == null)
            {
                return;
            }
            Type type = obj.GetType();
            if (type.IsEnum)
            {
                type = Enum.GetUnderlyingType(type);
            }
            if (type == typeof(sbyte))
            {
                this.vt = 16;
                this.cVal = (sbyte)obj;
                return;
            }
            if (type == typeof(byte))
            {
                this.vt = 17;
                this.bVal = (byte)obj;
                return;
            }
            if (type == typeof(short))
            {
                this.vt = 2;
                this.iVal = (short)obj;
                return;
            }
            if (type == typeof(ushort))
            {
                this.vt = 18;
                this.uiVal = (ushort)obj;
                return;
            }
            if (type == typeof(int))
            {
                this.vt = 3;
                this.lVal = (int)obj;
                return;
            }
            if (type == typeof(uint))
            {
                this.vt = 19;
                this.ulVal = (uint)obj;
                return;
            }
            if (type == typeof(long))
            {
                this.vt = 20;
                this.llVal = (long)obj;
                return;
            }
            if (type == typeof(ulong))
            {
                this.vt = 21;
                this.ullVal = (ulong)obj;
                return;
            }
            if (type == typeof(float))
            {
                this.vt = 4;
                this.fltVal = (float)obj;
                return;
            }
            if (type == typeof(double))
            {
                this.vt = 5;
                this.dblVal = (double)obj;
                return;
            }
            if (type == typeof(string))
            {
                this.vt = 8;
                this.bstrVal = Marshal.StringToBSTR((string)obj);
                return;
            }
            if (type == typeof(bool))
            {
                this.vt = 11;
                this.lVal = (((bool)obj) ? (-1) : 0);
                return;
            }
            if (type == typeof(BStrWrapper))
            {
                this.vt = 8;
                this.bstrVal = Marshal.StringToBSTR(((BStrWrapper)obj).WrappedObject);
                return;
            }
            if (type == typeof(UnknownWrapper))
            {
                this.vt = 13;
                this.pdispVal = Marshal.GetIUnknownForObject(((UnknownWrapper)obj).WrappedObject);
                return;
            }
            if (type == typeof(DispatchWrapper))
            {
                this.vt = 9;
                this.pdispVal = Marshal.GetIDispatchForObject(((DispatchWrapper)obj).WrappedObject);
                return;
            }
            try
            {
                this.pdispVal = Marshal.GetIDispatchForObject(obj);
                this.vt = 9;
                return;
            }
            catch
            {
            }
            try
            {
                this.vt = 13;
                this.pdispVal = Marshal.GetIUnknownForObject(obj);
            }
            catch (Exception ex)
            {
                throw new NotImplementedException(string.Format("Variant couldn't handle object of type {0}", obj.GetType()), ex);
            }
        }
References System.Format, System.Runtime.InteropServices.Marshal.GetIDispatchForObject(), System.Runtime.InteropServices.Marshal.GetIUnknownForObject(), System.Type.GetType(), System.Enum.GetUnderlyingType(), int, System.Type.IsEnum, long, System.obj, and System.Runtime.InteropServices.Marshal.StringToBSTR().
Referenced by System.Runtime.InteropServices.Marshal.GetNativeVariantForObject().