Terraria Decompiled: System.Variant.GetValueAt
GetValueAt()
static object System.Variant.GetValueAt (int vt, IntPtr addr) inline static
Definition at line 134 of file Variant.cs.
        {
            object obj = null;
            switch (vt)
            {
            case 2:
                obj = Marshal.ReadInt16(addr);
                break;
            case 3:
                obj = Marshal.ReadInt32(addr);
                break;
            case 4:
                obj = Marshal.PtrToStructure(addr, typeof(float));
                break;
            case 5:
                obj = Marshal.PtrToStructure(addr, typeof(double));
                break;
            case 8:
                obj = Marshal.PtrToStringBSTR(Marshal.ReadIntPtr(addr));
                break;
            case 9:
            case 13:
            {
                IntPtr intPtr = Marshal.ReadIntPtr(addr);
                if (intPtr != IntPtr.Zero)
                {
                    obj = Marshal.GetObjectForIUnknown(intPtr);
                }
                break;
            }
            case 11:
                obj = Marshal.ReadInt16(addr) != 0;
                break;
            case 16:
                obj = (sbyte)Marshal.ReadByte(addr);
                break;
            case 17:
                obj = Marshal.ReadByte(addr);
                break;
            case 18:
                obj = (ushort)Marshal.ReadInt16(addr);
                break;
            case 19:
                obj = (uint)Marshal.ReadInt32(addr);
                break;
            case 20:
                obj = Marshal.ReadInt64(addr);
                break;
            case 21:
                obj = (ulong)Marshal.ReadInt64(addr);
                break;
            }
            return obj;
        }
References System.Runtime.InteropServices.Marshal.GetObjectForIUnknown(), System.obj, System.Runtime.InteropServices.Marshal.PtrToStringBSTR(), System.Runtime.InteropServices.Marshal.PtrToStructure(), System.Runtime.InteropServices.Marshal.ReadByte(), System.Runtime.InteropServices.Marshal.ReadInt16(), System.Runtime.InteropServices.Marshal.ReadInt32(), System.Runtime.InteropServices.Marshal.ReadInt64(), System.Runtime.InteropServices.Marshal.ReadIntPtr(), System.Variant.vt, and System.IntPtr.Zero.
Referenced by System.Variant.GetValue().