Terraria Decompiled: Terraria.Testing.DebugOptions.SyncToJoiningPlayer
SyncToJoiningPlayer()
static void Terraria.Testing.DebugOptions.SyncToJoiningPlayer (int playerIndex) inline static
Definition at line 11 of file DebugOptions.cs.
        {
            if (DebugOptions.enableDebugCommands)
            {
                NetMessage.SendData(94, playerIndex, -1, NetworkText.FromLiteral("/showdebug"), 0, (float)(DebugOptions.Shared_ReportCommandUsage ? 1 : 0), 0f, 0f, 0, 0, 0);
                NetMessage.SendData(94, playerIndex, -1, NetworkText.FromLiteral("/setserverping"), 0, (float)DebugOptions.Shared_ServerPing, 0f, 0f, 0, 0, 0);
            }
        }
References Terraria.Testing.DebugOptions.enableDebugCommands, Terraria.Localization.NetworkText.FromLiteral(), Terraria.NetMessage.SendData(), Terraria.Testing.DebugOptions.Shared_ReportCommandUsage, and Terraria.Testing.DebugOptions.Shared_ServerPing.
Referenced by Terraria.NetMessage.SyncConnectedPlayer().