Terraria Decompiled: Newtonsoft.Json.Serialization.JsonDynamicContract.TrySetMember
TrySetMember()
bool Newtonsoft.Json.Serialization.JsonDynamicContract.TrySetMember (IDynamicMetaObjectProvider dynamicProvider, string name, object value) inline package
Definition at line 75 of file JsonDynamicContract.cs.
        {
            ValidationUtils.ArgumentNotNull(dynamicProvider, "dynamicProvider");
            CallSite<Func<CallSite, object, object, object>> callSite = this._callSiteSetters.Get(name);
            return callSite.Target.Invoke(callSite, dynamicProvider, value) != NoThrowExpressionVisitor.ErrorResult;
        }
References Newtonsoft.Json.Serialization.JsonDynamicContract._callSiteSetters, Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(), Newtonsoft.Json.Utilities.NoThrowExpressionVisitor.ErrorResult, Newtonsoft.Json.Utilities.ThreadSafeStore< TKey, TValue >.Get(), and System.value.
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateDynamic().