Terraria Decompiled: System.TimeZone.CalculateUtcOffset
CalculateUtcOffset()
static TimeSpan System.TimeZone.CalculateUtcOffset (DateTime time, DaylightTime daylightTimes) inline static package
Definition at line 126 of file TimeZone.cs.
        {
            if (daylightTimes == null)
            {
                return TimeSpan.Zero;
            }
            if (time.Kind == DateTimeKind.Utc)
            {
                return TimeSpan.Zero;
            }
            DateTime dateTime = daylightTimes.Start + daylightTimes.Delta;
            DateTime end = daylightTimes.End;
            DateTime dateTime2;
            DateTime dateTime3;
            if (daylightTimes.Delta.Ticks > 0L)
            {
                dateTime2 = end - daylightTimes.Delta;
                dateTime3 = end;
            }
            else
            {
                dateTime2 = dateTime;
                dateTime3 = dateTime - daylightTimes.Delta;
            }
            bool flag = false;
            if (dateTime > end)
            {
                if (time >= dateTime || time < end)
                {
                    flag = true;
                }
            }
            else if (time >= dateTime && time < end)
            {
                flag = true;
            }
            if (flag && time >= dateTime2 && time < dateTime3)
            {
                flag = time.IsAmbiguousDaylightSavingTime();
            }
            if (flag)
            {
                return daylightTimes.Delta;
            }
            return TimeSpan.Zero;
        }
References System.Globalization.DaylightTime.Delta, System.Globalization.DaylightTime.End, System.DateTime.IsAmbiguousDaylightSavingTime(), System.DateTime.Kind, System.L, System.TimeSpan.Ticks, and System.TimeSpan.Zero.
Referenced by System.CurrentSystemTimeZone.GetUtcOffset(), and System.TimeZone.IsDaylightSavingTime().