Terraria Decompiled: Terraria.Graphics.Effects.Filter.Apply
Apply()
void Terraria.Graphics.Effects.Filter.Apply (Vector2 textureSize, Vector2 sceneSize, Vector2 sceneOffset) inline
Definition at line 25 of file Filter.cs.
        {
            this._shader.UseSceneSize(sceneSize).UseSceneOffset(sceneOffset).UseImageSize0(textureSize)
                .Apply();
        }
References Terraria.Graphics.Effects.Filter._shader, Terraria.Graphics.Shaders.ScreenShaderData.Apply(), Terraria.Graphics.Shaders.ScreenShaderData.UseImageSize0(), Terraria.Graphics.Shaders.ScreenShaderData.UseSceneOffset(), and Terraria.Graphics.Shaders.ScreenShaderData.UseSceneSize().
Referenced by Terraria.Graphics.Effects.FilterManager.EndCapture().