Terraria Decompiled: System.Security.Claims.ClaimsIdentity.GetObjectData
GetObjectData()
virtual void System.Security.Claims.ClaimsIdentity.GetObjectData (SerializationInfo info, StreamingContext context) inline protected virtual
Reimplemented in System.Security.Principal.WindowsIdentity.
Definition at line 677 of file ClaimsIdentity.cs.
        {
            if (info == null)
            {
                throw new ArgumentNullException("info");
            }
            BinaryFormatter binaryFormatter = new BinaryFormatter();
            info.AddValue("System.Security.ClaimsIdentity.version", this.m_version);
            if (!string.IsNullOrEmpty(this.m_authenticationType))
            {
                info.AddValue("System.Security.ClaimsIdentity.authenticationType", this.m_authenticationType);
            }
            info.AddValue("System.Security.ClaimsIdentity.nameClaimType", this.m_nameType);
            info.AddValue("System.Security.ClaimsIdentity.roleClaimType", this.m_roleType);
            if (!string.IsNullOrEmpty(this.m_label))
            {
                info.AddValue("System.Security.ClaimsIdentity.label", this.m_label);
            }
            if (this.m_actor != null)
            {
                using (MemoryStream memoryStream = new MemoryStream())
                {
                    binaryFormatter.Serialize(memoryStream, this.m_actor, null, false);
                    info.AddValue("System.Security.ClaimsIdentity.actor", Convert.ToBase64String(memoryStream.GetBuffer(), 0, (int)memoryStream.Length));
                }
            }
            info.AddValue("System.Security.ClaimsIdentity.claims", this.SerializeClaims());
            if (this.m_bootstrapContext != null)
            {
                using (MemoryStream memoryStream2 = new MemoryStream())
                {
                    binaryFormatter.Serialize(memoryStream2, this.m_bootstrapContext, null, false);
                    info.AddValue("System.Security.ClaimsIdentity.bootstrapContext", Convert.ToBase64String(memoryStream2.GetBuffer(), 0, (int)memoryStream2.Length));
                }
            }
        }
References System.Runtime.Serialization.SerializationInfo.AddValue(), System.IO.MemoryStream.GetBuffer(), System.info, System.IO.MemoryStream.Length, System.Security.Claims.ClaimsIdentity.m_actor, System.Security.Claims.ClaimsIdentity.m_authenticationType, System.Security.Claims.ClaimsIdentity.m_bootstrapContext, System.Security.Claims.ClaimsIdentity.m_label, System.Security.Claims.ClaimsIdentity.m_nameType, System.Security.Claims.ClaimsIdentity.m_roleType, System.Security.Claims.ClaimsIdentity.m_version, System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(), System.Security.Claims.ClaimsIdentity.SerializeClaims(), and System.Convert.ToBase64String().