Terraria Decompiled: System.Security.Claims.ClaimsIdentity.Clone
Clone()
virtual ClaimsIdentity System.Security.Claims.ClaimsIdentity.Clone () inline virtual
Reimplemented in System.Security.Principal.GenericIdentity.
Definition at line 407 of file ClaimsIdentity.cs.
        {
            ClaimsIdentity claimsIdentity = new ClaimsIdentity(this.m_instanceClaims);
            claimsIdentity.m_authenticationType = this.m_authenticationType;
            claimsIdentity.m_bootstrapContext = this.m_bootstrapContext;
            claimsIdentity.m_label = this.m_label;
            claimsIdentity.m_nameType = this.m_nameType;
            claimsIdentity.m_roleType = this.m_roleType;
            if (this.Actor != null)
            {
                if (this.IsCircular(this.Actor))
                {
                    throw new InvalidOperationException(Environment.GetResourceString("Actor cannot be set so that circular directed graph will exist chaining the subjects together."));
                }
                if (!AppContextSwitches.SetActorAsReferenceWhenCopyingClaimsIdentity)
                {
                    claimsIdentity.Actor = this.Actor.Clone();
                }
                else
                {
                    claimsIdentity.Actor = this.Actor;
                }
            }
            return claimsIdentity;
        }
References System.Security.Claims.ClaimsIdentity.Actor, System.Security.Claims.ClaimsIdentity.ClaimsIdentity(), System.Security.Claims.ClaimsIdentity.Clone(), System.Environment.GetResourceString(), System.Security.Claims.ClaimsIdentity.IsCircular(), System.Security.Claims.ClaimsIdentity.m_authenticationType, System.Security.Claims.ClaimsIdentity.m_bootstrapContext, System.Security.Claims.ClaimsIdentity.m_instanceClaims, System.Security.Claims.ClaimsIdentity.m_label, System.Security.Claims.ClaimsIdentity.m_nameType, System.Security.Claims.ClaimsIdentity.m_roleType, and System.AppContextSwitches.SetActorAsReferenceWhenCopyingClaimsIdentity.
Referenced by System.Security.Claims.ClaimsIdentity.ClaimsIdentity(), System.Security.Claims.ClaimsIdentity.ClaimsIdentity(), System.Security.Claims.ClaimsIdentity.Clone(), and System.Security.Principal.WindowsIdentity.CloneAsBase().