Terraria Decompiled: System.Security.Claims.ClaimsIdentity.WriteTo
WriteTo() [2/2]
virtual void System.Security.Claims.ClaimsIdentity.WriteTo (BinaryWriter writer, byte[] userData) inline protected virtual
Definition at line 827 of file ClaimsIdentity.cs.
        {
            if (writer == null)
            {
                throw new ArgumentNullException("writer");
            }
            int num = 0;
            ClaimsIdentity.SerializationMask serializationMask = ClaimsIdentity.SerializationMask.None;
            if (this.m_authenticationType != null)
            {
                serializationMask |= ClaimsIdentity.SerializationMask.AuthenticationType;
                num++;
            }
            if (this.m_bootstrapContext != null && this.m_bootstrapContext is string)
            {
                serializationMask |= ClaimsIdentity.SerializationMask.BootstrapConext;
                num++;
            }
            if (!string.Equals(this.m_nameType, "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name", StringComparison.Ordinal))
            {
                serializationMask |= ClaimsIdentity.SerializationMask.NameClaimType;
                num++;
            }
            if (!string.Equals(this.m_roleType, "http://schemas.microsoft.com/ws/2008/06/identity/claims/role", StringComparison.Ordinal))
            {
                serializationMask |= ClaimsIdentity.SerializationMask.RoleClaimType;
                num++;
            }
            if (!string.IsNullOrWhiteSpace(this.m_label))
            {
                serializationMask |= ClaimsIdentity.SerializationMask.HasLabel;
                num++;
            }
            if (this.m_instanceClaims.Count > 0)
            {
                serializationMask |= ClaimsIdentity.SerializationMask.HasClaims;
                num++;
            }
            if (this.m_actor != null)
            {
                serializationMask |= ClaimsIdentity.SerializationMask.Actor;
                num++;
            }
            if (userData != null && userData.Length != 0)
            {
                num++;
                serializationMask |= ClaimsIdentity.SerializationMask.UserData;
            }
            writer.Write((int)serializationMask);
            writer.Write(num);
            if ((serializationMask & ClaimsIdentity.SerializationMask.AuthenticationType) == ClaimsIdentity.SerializationMask.AuthenticationType)
            {
                writer.Write(this.m_authenticationType);
            }
            if ((serializationMask & ClaimsIdentity.SerializationMask.BootstrapConext) == ClaimsIdentity.SerializationMask.BootstrapConext)
            {
                writer.Write(this.m_bootstrapContext as string);
            }
            if ((serializationMask & ClaimsIdentity.SerializationMask.NameClaimType) == ClaimsIdentity.SerializationMask.NameClaimType)
            {
                writer.Write(this.m_nameType);
            }
            if ((serializationMask & ClaimsIdentity.SerializationMask.RoleClaimType) == ClaimsIdentity.SerializationMask.RoleClaimType)
            {
                writer.Write(this.m_roleType);
            }
            if ((serializationMask & ClaimsIdentity.SerializationMask.HasLabel) == ClaimsIdentity.SerializationMask.HasLabel)
            {
                writer.Write(this.m_label);
            }
            if ((serializationMask & ClaimsIdentity.SerializationMask.HasClaims) == ClaimsIdentity.SerializationMask.HasClaims)
            {
                writer.Write(this.m_instanceClaims.Count);
                foreach (Claim claim in this.m_instanceClaims)
                {
                    claim.WriteTo(writer);
                }
            }
            if ((serializationMask & ClaimsIdentity.SerializationMask.Actor) == ClaimsIdentity.SerializationMask.Actor)
            {
                this.m_actor.WriteTo(writer);
            }
            if ((serializationMask & ClaimsIdentity.SerializationMask.UserData) == ClaimsIdentity.SerializationMask.UserData)
            {
                writer.Write(userData.Length);
                writer.Write(userData);
            }
            writer.Flush();
        }
References System.IO.BinaryWriter.Flush(), System.Security.Claims.ClaimsIdentity.m_actor, System.Security.Claims.ClaimsIdentity.m_authenticationType, System.Security.Claims.ClaimsIdentity.m_bootstrapContext, System.Security.Claims.ClaimsIdentity.m_instanceClaims, System.Security.Claims.ClaimsIdentity.m_label, System.Security.Claims.ClaimsIdentity.m_nameType, System.Security.Claims.ClaimsIdentity.m_roleType, System.IO.BinaryWriter.Write(), System.Security.Claims.Claim.WriteTo(), and System.Security.Claims.ClaimsIdentity.WriteTo().