Terraria Decompiled: System.Security.Claims.ClaimsIdentity.SafeAddClaims
SafeAddClaims()
void System.Security.Claims.ClaimsIdentity.SafeAddClaims (IEnumerable< Claim > claims) inline private
Definition at line 495 of file ClaimsIdentity.cs.
        {
            foreach (Claim claim in claims)
            {
                if (claim.Subject == this)
                {
                    this.m_instanceClaims.Add(claim);
                }
                else
                {
                    this.m_instanceClaims.Add(claim.Clone(this));
                }
            }
        }
References System.Security.Claims.Claim.Clone(), System.Security.Claims.ClaimsIdentity.m_instanceClaims, and System.Security.Claims.Claim.Subject.
Referenced by System.Security.Claims.ClaimsIdentity.ClaimsIdentity(), and System.Security.Claims.ClaimsIdentity.ClaimsIdentity().