Terraria Decompiled: System.Security.Claims.ClaimsIdentity.SerializeClaims
SerializeClaims()
string System.Security.Claims.ClaimsIdentity.SerializeClaims () inline private
Definition at line 737 of file ClaimsIdentity.cs.
        {
            string text;
            using (MemoryStream memoryStream = new MemoryStream())
            {
                new BinaryFormatter().Serialize(memoryStream, this.m_instanceClaims, null, false);
                text = Convert.ToBase64String(memoryStream.GetBuffer(), 0, (int)memoryStream.Length);
            }
            return text;
        }
References System.IO.MemoryStream.GetBuffer(), System.IO.MemoryStream.Length, System.Security.Claims.ClaimsIdentity.m_instanceClaims, System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(), System.text, and System.Convert.ToBase64String().
Referenced by System.Security.Claims.ClaimsIdentity.GetObjectData(), and System.Security.Claims.ClaimsIdentity.OnSerializingMethod().