Terraria Decompiled: System.Security.Claims.ClaimsIdentity.DeserializeClaims
DeserializeClaims()
void System.Security.Claims.ClaimsIdentity.DeserializeClaims (string serializedClaims) inline private
Definition at line 716 of file ClaimsIdentity.cs.
        {
            if (!string.IsNullOrEmpty(serializedClaims))
            {
                using (MemoryStream memoryStream = new MemoryStream(Convert.FromBase64String(serializedClaims)))
                {
                    this.m_instanceClaims = (List<Claim>)new BinaryFormatter().Deserialize(memoryStream, null, false);
                    for (int i = 0; i < this.m_instanceClaims.Count; i++)
                    {
                        this.m_instanceClaims[i].Subject = this;
                    }
                }
            }
            if (this.m_instanceClaims == null)
            {
                this.m_instanceClaims = new List<Claim>();
            }
        }
References System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(), System.Convert.FromBase64String(), and System.Security.Claims.ClaimsIdentity.m_instanceClaims.
Referenced by System.Security.Claims.ClaimsIdentity.Deserialize(), and System.Security.Claims.ClaimsIdentity.OnDeserializedMethod().