Terraria Decompiled: System.Security.Claims.ClaimsIdentity.Deserialize
Deserialize()
void System.Security.Claims.ClaimsIdentity.Deserialize (SerializationInfo info, StreamingContext context, bool useContext) inline private
Definition at line 920 of file ClaimsIdentity.cs.
        {
            if (info == null)
            {
                throw new ArgumentNullException("info");
            }
            BinaryFormatter binaryFormatter;
            if (useContext)
            {
                binaryFormatter = new BinaryFormatter(null, context);
            }
            else
            {
                binaryFormatter = new BinaryFormatter();
            }
            SerializationInfoEnumerator enumerator = info.GetEnumerator();
            while (enumerator.MoveNext())
            {
                string name = enumerator.Name;
                uint num = <PrivateImplementationDetails>.ComputeStringHash(name);
                if (num <= 959168042U)
                {
                    if (num <= 623923795U)
                    {
                        if (num != 373632733U)
{
                            if (num == 623923795U)
{
                                if (name == "System.Security.ClaimsIdentity.roleClaimType")
{
                                    this.m_roleType = info.GetString("System.Security.ClaimsIdentity.roleClaimType");
                                }
                            }
                        }
                        else if (name == "System.Security.ClaimsIdentity.label")
{
                            this.m_label = info.GetString("System.Security.ClaimsIdentity.label");
                        }
                    }
                    else if (num != 656336169U)
                    {
                        if (num == 959168042U)
{
                            if (name == "System.Security.ClaimsIdentity.nameClaimType")
{
                                this.m_nameType = info.GetString("System.Security.ClaimsIdentity.nameClaimType");
                            }
                        }
                    }
                    else if (name == "System.Security.ClaimsIdentity.authenticationType")
                    {
                        this.m_authenticationType = info.GetString("System.Security.ClaimsIdentity.authenticationType");
                    }
                }
                else if (num <= 1476368026U)
                {
                    if (num != 1453716852U)
                    {
                        if (num != 1476368026U)
{
                            continue;
                        }
                        if (!(name == "System.Security.ClaimsIdentity.actor"))
{
                            continue;
                        }
                        using (MemoryStream memoryStream = new MemoryStream(Convert.FromBase64String(info.GetString("System.Security.ClaimsIdentity.actor"))))
{
                            this.m_actor = (ClaimsIdentity)binaryFormatter.Deserialize(memoryStream, null, false);
                            continue;
                        }
                    }
                    else if (!(name == "System.Security.ClaimsIdentity.claims"))
                    {
                        continue;
                    }
                    this.DeserializeClaims(info.GetString("System.Security.ClaimsIdentity.claims"));
                }
                else if (num != 2480284791U)
                {
                    if (num == 3659022112U)
                    {
                        if (name == "System.Security.ClaimsIdentity.bootstrapContext")
{
                            using (MemoryStream memoryStream2 = new MemoryStream(Convert.FromBase64String(info.GetString("System.Security.ClaimsIdentity.bootstrapContext"))))
{
                                this.m_bootstrapContext = binaryFormatter.Deserialize(memoryStream2, null, false);
                            }
                        }
                    }
                }
                else if (name == "System.Security.ClaimsIdentity.version")
                {
                    info.GetString("System.Security.ClaimsIdentity.version");
                }
            }
        }
References System.Security.Claims.ClaimsIdentity.ClaimsIdentity(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(), System.Security.Claims.ClaimsIdentity.DeserializeClaims(), System.Convert.FromBase64String(), System.Runtime.Serialization.SerializationInfo.GetString(), System.info, System.Runtime.Serialization.SerializationInfoEnumerator.MoveNext(), System.name, System.Runtime.Serialization.SerializationInfoEnumerator.Name, and System.U.
Referenced by System.Security.Claims.ClaimsIdentity.ClaimsIdentity(), and System.Security.Claims.ClaimsIdentity.ClaimsIdentity().