Terraria Decompiled: System.Security.Claims.ClaimsIdentity.ClaimsIdentity
ClaimsIdentity() [10/14]
System.Security.Claims.ClaimsIdentity.ClaimsIdentity (IIdentity identity, IEnumerable< Claim > claims, string authenticationType, string nameType, string roleType, bool checkAuthType) inline package
Definition at line 76 of file ClaimsIdentity.cs.
        {
            this.m_instanceClaims = new List<Claim>();
            this.m_externalClaims = new Collection<IEnumerable<Claim>>();
            this.m_nameType = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name";
            this.m_roleType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role";
            this.m_version = "1.0";
            base..ctor();
            bool flag = false;
            bool flag2 = false;
            if (checkAuthType && identity != null && string.IsNullOrEmpty(authenticationType))
            {
                if (identity is WindowsIdentity)
                {
                    try
                    {
                        this.m_authenticationType = identity.AuthenticationType;
                        goto IL_0085;
                    }
                    catch (UnauthorizedAccessException)
                    {
                        this.m_authenticationType = null;
                        goto IL_0085;
                    }
                }
                this.m_authenticationType = identity.AuthenticationType;
            }
            else
            {
                this.m_authenticationType = authenticationType;
            }
            IL_0085:
            if (!string.IsNullOrEmpty(nameType))
            {
                this.m_nameType = nameType;
                flag = true;
            }
            if (!string.IsNullOrEmpty(roleType))
            {
                this.m_roleType = roleType;
                flag2 = true;
            }
            ClaimsIdentity claimsIdentity = identity as ClaimsIdentity;
            if (claimsIdentity != null)
            {
                this.m_label = claimsIdentity.m_label;
                if (!flag)
                {
                    this.m_nameType = claimsIdentity.m_nameType;
                }
                if (!flag2)
                {
                    this.m_roleType = claimsIdentity.m_roleType;
                }
                this.m_bootstrapContext = claimsIdentity.m_bootstrapContext;
                if (claimsIdentity.Actor != null)
                {
                    if (this.IsCircular(claimsIdentity.Actor))
                    {
                        throw new InvalidOperationException(Environment.GetResourceString("Actor cannot be set so that circular directed graph will exist chaining the subjects together."));
                    }
                    if (!AppContextSwitches.SetActorAsReferenceWhenCopyingClaimsIdentity)
                    {
                        this.m_actor = claimsIdentity.Actor.Clone();
                    }
                    else
                    {
                        this.m_actor = claimsIdentity.Actor;
                    }
                }
                if (claimsIdentity is WindowsIdentity && !(this is WindowsIdentity))
                {
                    this.SafeAddClaims(claimsIdentity.Claims);
                }
                else
                {
                    this.SafeAddClaims(claimsIdentity.m_instanceClaims);
                }
                if (claimsIdentity.m_userSerializationData != null)
                {
                    this.m_userSerializationData = claimsIdentity.m_userSerializationData.Clone() as byte[];
                }
            }
            else if (identity != null && !string.IsNullOrEmpty(identity.Name))
            {
                this.SafeAddClaim(new Claim(this.m_nameType, identity.Name, "http://www.w3.org/2001/XMLSchema#string", "LOCAL AUTHORITY", "LOCAL AUTHORITY", this));
            }
            if (claims != null)
            {
                this.SafeAddClaims(claims);
            }
        }
References System.Security.Claims.ClaimsIdentity.Actor, System.Security.Principal.IIdentity.AuthenticationType, System.Security.Claims.ClaimsIdentity.Claims, System.Security.Claims.ClaimsIdentity.ClaimsIdentity(), System.Security.Claims.ClaimsIdentity.Clone(), System.Environment.GetResourceString(), System.Security.Claims.ClaimsIdentity.IsCircular(), System.Security.Claims.ClaimsIdentity.m_bootstrapContext, System.Security.Claims.ClaimsIdentity.m_instanceClaims, System.Security.Claims.ClaimsIdentity.m_label, System.Security.Claims.ClaimsIdentity.m_nameType, System.Security.Claims.ClaimsIdentity.m_roleType, System.Security.Claims.ClaimsIdentity.m_userSerializationData, System.Security.Principal.IIdentity.Name, System.Security.Claims.ClaimsIdentity.SafeAddClaim(), System.Security.Claims.ClaimsIdentity.SafeAddClaims(), and System.AppContextSwitches.SetActorAsReferenceWhenCopyingClaimsIdentity.