Terraria Decompiled: Terraria.GameContent.UI.BigProgressBar.LunarPillarBigProgessBar.ValidateAndCollectNecessaryInfo
ValidateAndCollectNecessaryInfo()
bool Terraria.GameContent.UI.BigProgressBar.LunarPillarBigProgessBar.ValidateAndCollectNecessaryInfo (ref BigProgressBarInfo info) inline
Implements Terraria.GameContent.UI.BigProgressBar.IBigProgressBar.
Definition at line 11 of file LunarPillarBigProgessBar.cs.
        {
            if (info.npcIndexToAimAt < 0 || info.npcIndexToAimAt > Main.maxNPCs)
            {
                return false;
            }
            NPC npc = Main.npc[info.npcIndexToAimAt];
            if (!npc.active)
            {
                return false;
            }
            int bossHeadTextureIndex = npc.GetBossHeadTextureIndex();
            if (bossHeadTextureIndex == -1)
            {
                return false;
            }
            if (!this.IsPlayerInCombatArea())
            {
                return false;
            }
            if (npc.ai[2] == 1f)
            {
                return false;
            }
            Utils.Clamp<float>((float)npc.life / (float)npc.lifeMax, 0f, 1f);
            float num = (float)((int)MathHelper.Clamp(this.GetCurrentShieldValue(), 0f, this.GetMaxShieldValue())) / this.GetMaxShieldValue();
            this._cache.SetLife((float)npc.life, (float)npc.lifeMax);
            this._cache.SetShield(this.GetCurrentShieldValue(), this.GetMaxShieldValue());
            this._headIndex = bossHeadTextureIndex;
            return true;
        }
References Terraria.GameContent.UI.BigProgressBar.LunarPillarBigProgessBar._cache, Terraria.NPC.active, Terraria.NPC.ai, Microsoft.Xna.Framework.MathHelper.Clamp(), Terraria.Utils.Clamp(), Terraria.NPC.GetBossHeadTextureIndex(), Terraria.GameContent.UI.BigProgressBar.LunarPillarBigProgessBar.GetCurrentShieldValue(), Terraria.GameContent.UI.BigProgressBar.LunarPillarBigProgessBar.GetMaxShieldValue(), System.info, Terraria.GameContent.UI.BigProgressBar.LunarPillarBigProgessBar.IsPlayerInCombatArea(), Terraria.NPC.life, Terraria.NPC.lifeMax, Terraria.Main.maxNPCs, Terraria.Main.npc, Terraria.GameContent.UI.BigProgressBar.BigProgressBarCache.SetLife(), and Terraria.GameContent.UI.BigProgressBar.BigProgressBarCache.SetShield().