Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.FloodRoom
FloodRoom()
virtual void Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.FloodRoom (byte liquidType) inline virtual
Reimplemented in Terraria.GameContent.Generation.Dungeon.Rooms.GenShapeDungeonRoom, Terraria.GameContent.Generation.Dungeon.Rooms.LegacyDungeonRoom, Terraria.GameContent.Generation.Dungeon.Rooms.LivingTreeDungeonRoom, and Terraria.GameContent.Generation.Dungeon.Rooms.WormlikeDungeonRoom.
Definition at line 252 of file DungeonRoom.cs.
        {
            for (int i = this.InnerBounds.Left; i <= this.InnerBounds.Right; i++)
            {
                for (int j = this.InnerBounds.Center.Y; j <= this.InnerBounds.Bottom; j++)
                {
                    Tile tile = Main.tile[i, j];
                    if (!tile.active())
                    {
                        tile.liquid = byte.MaxValue;
                        tile.liquidType((int)liquidType);
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.Bottom, Terraria.GameContent.Generation.Dungeon.DungeonBounds.Center, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.InnerBounds, Terraria.GameContent.Generation.Dungeon.DungeonBounds.Left, Terraria.Tile.liquidType(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.Right, Terraria.Main.tile, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.GenerateEarlyDungeonFeaturesInRoom().