Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.GetHallwayConnectionPoint
GetHallwayConnectionPoint()
virtual ConnectionPointQuality Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.GetHallwayConnectionPoint (Vector2D otherRoomPos, out Vector2D connectionPoint) inline virtual
Reimplemented in Terraria.GameContent.Generation.Dungeon.Rooms.BiomeDungeonRoom.
Definition at line 162 of file DungeonRoom.cs.
        {
            if (this.settings.HallwayConnectionPointOverride != null)
            {
                ConnectionPointQuality connectionPointQuality = this.settings.HallwayConnectionPointOverride(this, otherRoomPos, out connectionPoint);
                if (this.settings.HallwayPointAdjuster != null)
                {
                    Vector2D vector2D = (otherRoomPos - connectionPoint).SafeNormalize(Vector2D.UnitX);
                    connectionPoint -= vector2D * (double)this.settings.HallwayPointAdjuster.Value;
                }
                return connectionPointQuality;
            }
            connectionPoint = this.GetRoomCenterForHallway(otherRoomPos);
            Vector2D vector2D2 = (otherRoomPos - connectionPoint).SafeNormalize(Vector2D.UnitX);
            if (-0.5 < vector2D2.Y && vector2D2.Y < 0.7 && WorldGen.genRand.Next(2) == 0)
            {
                while (this.IsInsideRoom(connectionPoint.ToPoint()))
                {
                    connectionPoint.Y += 1.0;
                }
                connectionPoint.Y -= 3.0;
            }
            else if (-0.7 < vector2D2.Y && vector2D2.Y < 0.5 && WorldGen.genRand.Next(3) == 0)
            {
                while (this.IsInsideRoom(connectionPoint.ToPoint()))
                {
                    connectionPoint.Y -= 1.0;
                }
                connectionPoint.Y += 3.0;
            }
            else
            {
                connectionPoint += WorldGen.genRand.NextVector2DCircularEdge(4.0, 4.0);
            }
            vector2D2 = (otherRoomPos - connectionPoint).SafeNormalize(Vector2D.UnitX);
            while (this.IsInsideRoom(connectionPoint.ToPoint()))
            {
                connectionPoint += vector2D2;
            }
            if (this.settings.HallwayPointAdjuster != null)
            {
                connectionPoint -= vector2D2 * (double)this.settings.HallwayPointAdjuster.Value;
            }
            return ConnectionPointQuality.Good;
        }
References Terraria.WorldGen.genRand, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.GetRoomCenterForHallway(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.HallwayConnectionPointOverride, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.HallwayPointAdjuster, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.IsInsideRoom(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.settings, ReLogic.Utilities.Vector2D.UnitX, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.GetHallwayConnectionPoints().