Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.GenerateEarlyDungeonFeaturesInRoom
GenerateEarlyDungeonFeaturesInRoom()
virtual void Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.GenerateEarlyDungeonFeaturesInRoom (DungeonData data) inline virtual
Reimplemented in Terraria.GameContent.Generation.Dungeon.Rooms.BiomeDungeonRoom, Terraria.GameContent.Generation.Dungeon.Rooms.BiomeRuggedDungeonRoom, Terraria.GameContent.Generation.Dungeon.Rooms.BiomeStructuredDungeonRoom, Terraria.GameContent.Generation.Dungeon.Rooms.GenShapeDungeonRoom, and Terraria.GameContent.Generation.Dungeon.Rooms.LivingTreeDungeonRoom.
Definition at line 54 of file DungeonRoom.cs.
        {
            UnifiedRandom unifiedRandom = new UnifiedRandom(this.settings.RandomSeed);
            if (data.Type != DungeonType.DualDungeon)
            {
                return;
            }
            if (unifiedRandom.Next(3) == 0)
            {
                DungeonWindowBasicSettings dungeonWindowBasicSettings = new DungeonWindowBasicSettings
                {
                    Style = this.settings.StyleData,
                    Closed = ((double)this.InnerBounds.Bottom > Main.worldSurface)
                };
                int width = this.InnerBounds.Width;
                int height = this.InnerBounds.Height;
                bool flag = true;
                int num = unifiedRandom.Next(3);
                if (num >= 1 && num <= 2 && (width <= 36 || height <= 15))
                {
                    num = 0;
                }
                if (num == 0 && (width <= 14 || height <= 10))
                {
                    flag = false;
                }
                if (flag)
                {
                    Point point = this.InnerBounds.Center;
                    if (num == 0 || num - 1 > 1)
                    {
                        int num2 = Math.Max(3, this.InnerBounds.Width / 3);
                        if (num2 % 2 == 0)
{
                            num2++;
                        }
                        dungeonWindowBasicSettings.Width = Math.Max(3, num2);
                        dungeonWindowBasicSettings.Height = Math.Max(5, this.InnerBounds.Height / 3);
                        DungeonWindow dungeonWindow = new DungeonWindowBasic(dungeonWindowBasicSettings);
                        point = this.GetRoomCenterForDungeonFeature(data, dungeonWindow);
                        if (this.CanGenerateFeatureAt(data, dungeonWindow, point.X, point.Y))
{
                            dungeonWindow.GenerateFeature(data, point.X, point.Y);
                        }
                    }
                    else
                    {
                        int num2 = Math.Min(7, Math.Max(3, this.InnerBounds.Width / 5));
                        if (num2 % 2 == 0)
{
                            num2++;
                        }
                        dungeonWindowBasicSettings.Width = Math.Max(3, num2);
                        dungeonWindowBasicSettings.Height = Math.Max(5, this.InnerBounds.Height / 3);
                        DungeonWindow dungeonWindow = new DungeonWindowBasic(dungeonWindowBasicSettings);
                        point = this.GetRoomCenterForDungeonFeature(data, dungeonWindow);
                        if (this.CanGenerateFeatureAt(data, dungeonWindow, point.X, point.Y))
{
                            dungeonWindow.GenerateFeature(data, point.X, point.Y);
                        }
                        dungeonWindowBasicSettings.Height -= 2;
                        dungeonWindow = new DungeonWindowBasic(dungeonWindowBasicSettings);
                        if (this.CanGenerateFeatureAt(data, dungeonWindow, point.X - num2 - 2, point.Y))
{
                            dungeonWindow.GenerateFeature(data, point.X - num2 - 2, point.Y);
                        }
                        dungeonWindow = new DungeonWindowBasic(dungeonWindowBasicSettings);
                        if (this.CanGenerateFeatureAt(data, dungeonWindow, point.X + num2 + 2, point.Y))
{
                            dungeonWindow.GenerateFeature(data, point.X + num2 + 2, point.Y);
                        }
                    }
                }
            }
            int liquidType = this.settings.StyleData.LiquidType;
            if (liquidType >= 0)
            {
                this.FloodRoom((byte)liquidType);
            }
        }
References Terraria.GameContent.Generation.Dungeon.DungeonBounds.Bottom, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.CanGenerateFeatureAt(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.Center, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.FloodRoom(), Terraria.GameContent.Generation.Dungeon.Features.DungeonFeature.GenerateFeature(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.GetRoomCenterForDungeonFeature(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.Height, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.InnerBounds, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.LiquidType, System.Math.Max(), System.Math.Min(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.RandomSeed, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.settings, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.StyleData, Terraria.GameContent.Generation.Dungeon.DungeonData.Type, Terraria.GameContent.Generation.Dungeon.DungeonBounds.Width, Terraria.Main.worldSurface, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.