Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.GenerateDungeonSquareRoom
GenerateDungeonSquareRoom() [1/2]
void Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.GenerateDungeonSquareRoom (DungeonData data, DungeonBounds innerBounds, DungeonBounds outerBounds, Vector2D currentPoint, ushort tileType, ushort wallType, int innerBoundsSize, int totalBoundsSize, bool genTiles = true, bool genWalls = true) inline
Definition at line 275 of file DungeonRoom.cs.
        {
            for (int i = -totalBoundsSize; i <= totalBoundsSize; i++)
            {
                int num = (int)currentPoint.X + i;
                for (int j = -totalBoundsSize; j <= totalBoundsSize; j++)
                {
                    int num2 = (int)currentPoint.Y + j;
                    Tile tile = Main.tile[num, num2];
                    if (Math.Abs(i) <= innerBoundsSize && Math.Abs(j) <= innerBoundsSize)
                    {
                        innerBounds.UpdateBounds(num, num2);
                        if (genWalls)
{
                            DungeonUtils.ChangeWallType(tile, wallType, true, this.settings.OverridePaintWall);
                        }
                    }
                    else if (!DungeonUtils.IsHigherOrEqualTieredDungeonWall(data, (int)tile.wall, (int)wallType))
                    {
                        outerBounds.UpdateBounds(num, num2);
                        if (genTiles)
{
                            DungeonUtils.ChangeTileType(tile, tileType, true, this.settings.OverridePaintTile);
                        }
                        if (genWalls && i > -totalBoundsSize && i < totalBoundsSize && j > -totalBoundsSize && j < totalBoundsSize)
{
                            DungeonUtils.ChangeWallType(tile, wallType, false, this.settings.OverridePaintWall);
                        }
                    }
                }
            }
        }
References System.Math.Abs(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.ChangeTileType(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.ChangeWallType(), int, Terraria.GameContent.Generation.Dungeon.DungeonUtils.IsHigherOrEqualTieredDungeonWall(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.OverridePaintTile, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.OverridePaintWall, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.settings, Terraria.Main.tile, Terraria.GameContent.Generation.Dungeon.DungeonBounds.UpdateBounds(), Terraria.Tile.wall, ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.