Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.GetRoomCenterForHallway
GetRoomCenterForHallway()
virtual Point Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.GetRoomCenterForHallway (Vector2D otherRoomPos) inline virtual
Reimplemented in Terraria.GameContent.Generation.Dungeon.Rooms.GenShapeDungeonRoom.
Definition at line 147 of file DungeonRoom.cs.
        {
            return this.Center;
        }
References Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.Center.
Referenced by Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.ConnectToBottomOfRoomOnly(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.ConnectToTopOfRoomOnly(), and Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.GetHallwayConnectionPoint().