Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.InnerBounds
InnerBounds
DungeonBounds Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.InnerBounds = new DungeonBounds()
Definition at line 362 of file DungeonRoom.cs.
Referenced by Terraria.GameContent.Generation.Dungeon.Rooms.BiomeRuggedDungeonRoom.BiomeRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeSquareDungeonRoom.BiomeRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeStructuredDungeonRoom.BiomeRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeDungeonRoom.BiomeRoom_FinishRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeDungeonRoom.CalculatePlatformsAndDoors(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.CalculatePlatformsAndDoors(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalEarlyDualDungeonFeatures.EarlyDungeonFeatures(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.FloodRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.GenShapeDungeonRoom.FloodRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeStructuredDungeonRoom.GenerateEarlyDungeonFeaturesInRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.GenerateEarlyDungeonFeaturesInRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.GenShapeDungeonRoom.GenerateEarlyDungeonFeaturesInRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.LivingTreeDungeonRoom.GenerateEarlyDungeonFeaturesInRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.LivingTreeDungeonRoom.GenerateLateDungeonFeaturesInRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.GenShapeDungeonRoom.GenShapeRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.GetFloodedRoomTileCount(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeDungeonRoom.GetProtectionTypeFromPoint(), Terraria.GameContent.Generation.Dungeon.Rooms.GenShapeDungeonRoom.GetRoomCenterForHallway(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalGroundFurniture.GroundFurniture_DualDungeons(), Terraria.GameContent.Generation.Dungeon.DungeonData.IsAnyRoomInSpot(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.IsInsideRoom(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalLateDualDungeonFeatures.LateDualDungeonFeatures_CleanOutEntrancesOfLiquids(), Terraria.GameContent.Generation.Dungeon.Rooms.LegacyDungeonRoom.LegacyRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.LivingTreeDungeonRoom.LivingTreeRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.RegularDungeonRoom.RegularRoom(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalTraps.Traps(), and Terraria.GameContent.Generation.Dungeon.Rooms.WormlikeDungeonRoom.WormlikeRoom().