Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.GenerateDungeonSquareRoom
GenerateDungeonSquareRoom() [2/2]
void Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.GenerateDungeonSquareRoom (DungeonData data, Vector2D currentPoint, ushort tileType, ushort tileCrackedType, ushort wallType, int innerBoundsSize, int outerBoundsSize, bool crackedBricks = false) inline
Definition at line 309 of file DungeonRoom.cs.
        {
            int num = innerBoundsSize + outerBoundsSize;
            for (int i = -num; i <= num; i++)
            {
                int num2 = (int)currentPoint.X + i;
                for (int j = -num; j <= num; j++)
                {
                    int num3 = (int)currentPoint.Y + j;
                    Tile tile = Main.tile[num2, num3];
                    if (Math.Abs(i) <= innerBoundsSize && Math.Abs(j) <= innerBoundsSize)
                    {
                        if (crackedBricks)
{
                            if ((tile.active() || !DungeonUtils.IsConsideredDungeonWall((int)tile.wall, false)) && num3 < Main.UnderworldLayer)
{
                                tile.ClearTile();
                                tile.wall = 0;
                                DungeonUtils.ChangeWallType(tile, wallType, false, this.settings.OverridePaintWall);
                                DungeonUtils.ChangeTileType(tile, tileCrackedType, false, this.settings.OverridePaintTile);
                            }
                        }
                        else
{
                            tile.ClearTile();
                            DungeonUtils.ChangeWallType(tile, wallType, false, this.settings.OverridePaintWall);
                        }
                    }
                    else if ((tile.active() && !DungeonUtils.IsHigherOrEqualTieredDungeonTile(data, (int)tile.type, (int)tileType)) || !DungeonUtils.IsConsideredDungeonWall((int)tile.wall, false))
                    {
                        tile.ClearTile();
                        tile.wall = 0;
                        DungeonUtils.ChangeTileType(tile, tileType, false, this.settings.OverridePaintTile);
                        if (i > -num && i < num && j > -num && j < num)
{
                            DungeonUtils.ChangeWallType(tile, wallType, false, this.settings.OverridePaintWall);
                        }
                    }
                    tile.liquid = 0;
                }
            }
        }
References System.Math.Abs(), Terraria.Tile.active(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.ChangeTileType(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.ChangeWallType(), Terraria.Tile.ClearTile(), int, Terraria.GameContent.Generation.Dungeon.DungeonUtils.IsConsideredDungeonWall(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.IsHigherOrEqualTieredDungeonTile(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.OverridePaintTile, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.OverridePaintWall, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.settings, Terraria.Main.tile, Terraria.Tile.type, Terraria.Main.UnderworldLayer, Terraria.Tile.wall, ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.