Terraria Decompiled: Terraria.GameContent.SmartCursorHelper.Step_Torch
Step_Torch()
static void Terraria.GameContent.SmartCursorHelper.Step_Torch (SmartCursorHelper::SmartCursorUsageInfo providedInfo, ref int fX, ref int fY) inline static private
Definition at line 2879 of file SmartCursorHelper.cs.
        {
            int reachableStartX = providedInfo.reachableStartX;
            int reachableStartY = providedInfo.reachableStartY;
            int reachableEndX = providedInfo.reachableEndX;
            int reachableEndY = providedInfo.reachableEndY;
            int screenTargetX = providedInfo.screenTargetX;
            int screenTargetY = providedInfo.screenTargetY;
            int type = providedInfo.item.type;
            if (type >= 0 && type < (int)ItemID.Count && ItemID.Sets.Torches[type] && fX == -1 && fY == -1)
            {
                SmartCursorHelper._targets.Clear();
                bool flag = !ItemID.Sets.WaterTorches[type];
                for (int i = reachableStartX; i <= reachableEndX; i++)
                {
                    for (int j = reachableStartY; j <= reachableEndY; j++)
                    {
                        Tile tile = Main.tile[i, j];
                        if ((!flag || tile.liquid <= 0) && (!tile.active() || TileID.Sets.BreakableWhenPlacing[(int)tile.type] || (Main.tileCut[(int)tile.type] && tile.type != 82 && tile.type != 83)))
{
                            bool flag2 = false;
                            for (int k = i - 8; k <= i + 8; k++)
{
                                for (int l = j - 8; l <= j + 8; l++)
{
                                    if (Main.tile[k, l] != null)
{
                                        Tile tile2 = Main.tile[k, l];
                                        if (TileID.Sets.Torches[(int)tile2.type])
{
                                            flag2 = true;
                                            break;
                                        }
                                    }
                                }
                                if (flag2)
{
                                    break;
                                }
                            }
                            if (!flag2 && SmartCursorHelper.IsValidSpotForTorch(i, j, tile))
{
                                SmartCursorHelper._targets.Add(new Point(i, j));
                            }
                        }
                    }
                }
                if (SmartCursorHelper._targets.Count > 0)
                {
                    float num = -1f;
                    Point point = SmartCursorHelper._targets[0];
                    for (int m = 0; m < SmartCursorHelper._targets.Count; m++)
                    {
                        float num2 = Vector2.Distance(new Vector2((float)SmartCursorHelper._targets[m].X, (float)SmartCursorHelper._targets[m].Y) * 16f + Vector2.One * 8f, providedInfo.mouse);
                        if (num == -1f || num2 < num)
{
                            num = num2;
                            point = SmartCursorHelper._targets[m];
                        }
                    }
                    if (Collision.InTileBounds(point.X, point.Y, reachableStartX, reachableStartY, reachableEndX, reachableEndY))
                    {
                        fX = point.X;
                        fY = point.Y;
                    }
                }
                SmartCursorHelper._targets.Clear();
            }
        }
References Terraria.GameContent.SmartCursorHelper._targets, Terraria.Tile.active(), System.Collections.Generic.List< T >.Add(), Terraria.ID.TileID.Sets.BreakableWhenPlacing, System.Collections.Generic.List< T >.Clear(), System.Collections.Generic.List< T >.Count, Terraria.ID.ItemID.Count, Microsoft.Xna.Framework.Vector2.Distance(), Terraria.Collision.InTileBounds(), Terraria.GameContent.SmartCursorHelper.IsValidSpotForTorch(), Terraria.Tile.liquid, Microsoft.Xna.Framework.Vector2.One, Terraria.Main.tile, Terraria.Main.tileCut, Terraria.ID.ItemID.Sets.Torches, Terraria.ID.TileID.Sets.Torches, Terraria.Tile.type, Terraria.ID.ItemID.Sets.WaterTorches, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.SmartCursorHelper.SmartCursorLookup().