Terraria Decompiled: System.Runtime.Remoting.Messaging.RemotingSurrogate.GetObjectData
GetObjectData()
virtual void System.Runtime.Remoting.Messaging.RemotingSurrogate.GetObjectData (object obj, SerializationInfo si, StreamingContext sc) inline virtual
Implements System.Runtime.Serialization.ISerializationSurrogate.
Definition at line 10 of file RemotingSurrogate.cs.
        {
            if (obj == null || si == null)
            {
                throw new ArgumentNullException();
            }
            if (RemotingServices.IsTransparentProxy(obj))
            {
                RemotingServices.GetRealProxy(obj).GetObjectData(si, sc);
                return;
            }
            RemotingServices.GetObjectData(obj, si, sc);
        }
References System.Runtime.Remoting.RemotingServices.GetObjectData(), System.Runtime.Remoting.RemotingServices.GetRealProxy(), System.Runtime.Remoting.RemotingServices.IsTransparentProxy(), and System.obj.