Terraria Decompiled: Terraria.GameContent.SmartCursorHelper.Step_BlocksFilling
Step_BlocksFilling()
static void Terraria.GameContent.SmartCursorHelper.Step_BlocksFilling (SmartCursorHelper::SmartCursorUsageInfo providedInfo, ref int fX, ref int fY) inline static private
Definition at line 2776 of file SmartCursorHelper.cs.
        {
            if (!Player.SmartCursorSettings.SmartBlocksEnabled)
            {
                return;
            }
            int type = providedInfo.item.type;
            if (type < 0 || type >= (int)ItemID.Count)
            {
                return;
            }
            int reachableStartX = providedInfo.reachableStartX;
            int reachableStartY = providedInfo.reachableStartY;
            int reachableEndX = providedInfo.reachableEndX;
            int reachableEndY = providedInfo.reachableEndY;
            int screenTargetX = providedInfo.screenTargetX;
            int screenTargetY = providedInfo.screenTargetY;
            if (!Player.SmartCursorSettings.SmartBlocksEnabled && providedInfo.item.createTile > -1 && SmartCursorHelper.AllowNormalBlockPlacementBehaviourForItemType(type) && Main.tileSolid[providedInfo.item.createTile] && !Main.tileSolidTop[providedInfo.item.createTile] && !Main.tileFrameImportant[providedInfo.item.createTile] && fX == -1 && fY == -1)
            {
                SmartCursorHelper._targets.Clear();
                bool flag = false;
                if (Main.tile[screenTargetX, screenTargetY].active())
                {
                    flag = true;
                }
                if (!Collision.InTileBounds(screenTargetX, screenTargetY, reachableStartX, reachableStartY, reachableEndX, reachableEndY))
                {
                    flag = true;
                }
                if (!flag)
                {
                    for (int i = reachableStartX; i <= reachableEndX; i++)
                    {
                        for (int j = reachableStartY; j <= reachableEndY; j++)
{
                            Tile tile = Main.tile[i, j];
                            if (!tile.active() || Main.tileCut[(int)tile.type] || TileID.Sets.BreakableWhenPlacing[(int)tile.type])
{
                                int num = 0;
                                if (Main.tile[i - 1, j].active() && Main.tileSolid[(int)Main.tile[i - 1, j].type] && !Main.tileSolidTop[(int)Main.tile[i - 1, j].type])
{
                                    num++;
                                }
                                if (Main.tile[i + 1, j].active() && Main.tileSolid[(int)Main.tile[i + 1, j].type] && !Main.tileSolidTop[(int)Main.tile[i + 1, j].type])
{
                                    num++;
                                }
                                if (Main.tile[i, j - 1].active() && Main.tileSolid[(int)Main.tile[i, j - 1].type] && !Main.tileSolidTop[(int)Main.tile[i, j - 1].type])
{
                                    num++;
                                }
                                if (Main.tile[i, j + 1].active() && Main.tileSolid[(int)Main.tile[i, j + 1].type] && !Main.tileSolidTop[(int)Main.tile[i, j + 1].type])
{
                                    num++;
                                }
                                if (num >= 2)
{
                                    SmartCursorHelper._targets.Add(new Point(i, j));
                                }
                            }
                        }
                    }
                }
                if (SmartCursorHelper._targets.Count > 0)
                {
                    float num2 = -1f;
                    float num3 = float.PositiveInfinity;
                    Point point = SmartCursorHelper._targets[0];
                    for (int k = 0; k < SmartCursorHelper._targets.Count; k++)
                    {
                        if (Collision.EmptyTile(SmartCursorHelper._targets[k].X, SmartCursorHelper._targets[k].Y, true))
{
                            Vector2 vector = new Vector2((float)SmartCursorHelper._targets[k].X, (float)SmartCursorHelper._targets[k].Y) * 16f + Vector2.One * 8f - providedInfo.mouse;
                            bool flag2 = false;
                            float num4 = Math.Abs(vector.X);
                            float num5 = vector.Length();
                            if (num4 < num3)
{
                                flag2 = true;
                            }
                            if (num4 == num3 && (num2 == -1f || num5 < num2))
{
                                flag2 = true;
                            }
                            if (flag2)
{
                                num2 = num5;
                                num3 = num4;
                                point = SmartCursorHelper._targets[k];
                            }
                        }
                    }
                    if (Collision.InTileBounds(point.X, point.Y, reachableStartX, reachableStartY, reachableEndX, reachableEndY) && num2 != -1f)
                    {
                        fX = point.X;
                        fY = point.Y;
                    }
                }
                SmartCursorHelper._targets.Clear();
            }
        }
References Terraria.GameContent.SmartCursorHelper._targets, System.Math.Abs(), Terraria.Tile.active(), System.Collections.Generic.List< T >.Add(), Terraria.GameContent.SmartCursorHelper.AllowNormalBlockPlacementBehaviourForItemType(), Terraria.ID.TileID.Sets.BreakableWhenPlacing, System.Collections.Generic.List< T >.Clear(), System.Collections.Generic.List< T >.Count, Terraria.ID.ItemID.Count, Terraria.Collision.EmptyTile(), Terraria.Collision.InTileBounds(), Microsoft.Xna.Framework.Vector2.Length(), Terraria.Player.SmartCursorSettings.SmartBlocksEnabled, Terraria.Main.tile, Terraria.Main.tileCut, Terraria.Main.tileFrameImportant, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Tile.type, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.SmartCursorHelper.SmartCursorLookup().