Terraria Decompiled: Terraria.GameContent.SmartCursorHelper.Step_MinecartTracks
Step_MinecartTracks()
static void Terraria.GameContent.SmartCursorHelper.Step_MinecartTracks (SmartCursorHelper::SmartCursorUsageInfo providedInfo, ref int focusedX, ref int focusedY) inline static private
Definition at line 1168 of file SmartCursorHelper.cs.
        {
            if ((providedInfo.item.type == 2340 || providedInfo.item.type == 2739) && focusedX == -1 && focusedY == -1)
            {
                SmartCursorHelper._targets.Clear();
                Vector2 vector = (Main.MouseWorld - providedInfo.Center).SafeNormalize(Vector2.UnitY);
                float num = Vector2.Dot(vector, -Vector2.UnitY);
                bool flag = num >= 0.5f;
                bool flag2 = num <= -0.5f;
                float num2 = Vector2.Dot(vector, Vector2.UnitX);
                bool flag3 = num2 >= 0.5f;
                bool flag4 = num2 <= -0.5f;
                bool flag5 = flag && flag4;
                bool flag6 = flag && flag3;
                bool flag7 = flag2 && flag4;
                bool flag8 = flag2 && flag3;
                if (flag5)
                {
                    flag4 = false;
                }
                if (flag6)
                {
                    flag3 = false;
                }
                if (flag7)
                {
                    flag4 = false;
                }
                if (flag8)
                {
                    flag3 = false;
                }
                bool flag9 = false;
                if (Main.tile[providedInfo.screenTargetX, providedInfo.screenTargetY].active() && Main.tile[providedInfo.screenTargetX, providedInfo.screenTargetY].type == 314)
                {
                    flag9 = true;
                }
                if (!flag9)
                {
                    for (int i = providedInfo.reachableStartX; i <= providedInfo.reachableEndX; i++)
                    {
                        for (int j = providedInfo.reachableStartY; j <= providedInfo.reachableEndY; j++)
{
                            Tile tile = Main.tile[i, j];
                            if (tile.active() && tile.type == 314)
{
                                bool flag10 = Main.tile[i + 1, j + 1].active() && Main.tile[i + 1, j + 1].type == 314;
                                bool flag11 = Main.tile[i + 1, j - 1].active() && Main.tile[i + 1, j - 1].type == 314;
                                bool flag12 = Main.tile[i - 1, j + 1].active() && Main.tile[i - 1, j + 1].type == 314;
                                bool flag13 = Main.tile[i - 1, j - 1].active() && Main.tile[i - 1, j - 1].type == 314;
                                if (flag5 && (!Main.tile[i - 1, j - 1].active() || Main.tileCut[(int)Main.tile[i - 1, j - 1].type] || TileID.Sets.BreakableWhenPlacing[(int)Main.tile[i - 1, j - 1].type]) && (flag10 || !flag11) && !flag12)
{
                                    SmartCursorHelper._targets.Add(new Point(i - 1, j - 1));
                                }
                                if (flag4 && (!Main.tile[i - 1, j].active() || Main.tileCut[(int)Main.tile[i - 1, j].type] || TileID.Sets.BreakableWhenPlacing[(int)Main.tile[i - 1, j].type]))
{
                                    SmartCursorHelper._targets.Add(new Point(i - 1, j));
                                }
                                if (flag7 && (!Main.tile[i - 1, j + 1].active() || Main.tileCut[(int)Main.tile[i - 1, j + 1].type] || TileID.Sets.BreakableWhenPlacing[(int)Main.tile[i - 1, j + 1].type]) && (flag11 || !flag10) && !flag13)
{
                                    SmartCursorHelper._targets.Add(new Point(i - 1, j + 1));
                                }
                                if (flag6 && (!Main.tile[i + 1, j - 1].active() || Main.tileCut[(int)Main.tile[i + 1, j - 1].type] || TileID.Sets.BreakableWhenPlacing[(int)Main.tile[i + 1, j - 1].type]) && (flag12 || !flag13) && !flag10)
{
                                    SmartCursorHelper._targets.Add(new Point(i + 1, j - 1));
                                }
                                if (flag3 && (!Main.tile[i + 1, j].active() || Main.tileCut[(int)Main.tile[i + 1, j].type] || TileID.Sets.BreakableWhenPlacing[(int)Main.tile[i + 1, j].type]))
{
                                    SmartCursorHelper._targets.Add(new Point(i + 1, j));
                                }
                                if (flag8 && (!Main.tile[i + 1, j + 1].active() || Main.tileCut[(int)Main.tile[i + 1, j + 1].type] || TileID.Sets.BreakableWhenPlacing[(int)Main.tile[i + 1, j + 1].type]) && (flag13 || !flag12) && !flag11)
{
                                    SmartCursorHelper._targets.Add(new Point(i + 1, j + 1));
                                }
                            }
                        }
                    }
                }
                if (SmartCursorHelper._targets.Count > 0)
                {
                    float num3 = -1f;
                    Point point = SmartCursorHelper._targets[0];
                    for (int k = 0; k < SmartCursorHelper._targets.Count; k++)
                    {
                        if ((!Main.tile[SmartCursorHelper._targets[k].X, SmartCursorHelper._targets[k].Y - 1].active() || Main.tile[SmartCursorHelper._targets[k].X, SmartCursorHelper._targets[k].Y - 1].type != 314) && (!Main.tile[SmartCursorHelper._targets[k].X, SmartCursorHelper._targets[k].Y + 1].active() || Main.tile[SmartCursorHelper._targets[k].X, SmartCursorHelper._targets[k].Y + 1].type != 314))
{
                            float num4 = Vector2.Distance(new Vector2((float)SmartCursorHelper._targets[k].X, (float)SmartCursorHelper._targets[k].Y) * 16f + Vector2.One * 8f, providedInfo.mouse);
                            if (num3 == -1f || num4 < num3)
{
                                num3 = num4;
                                point = SmartCursorHelper._targets[k];
                            }
                        }
                    }
                    if (Collision.InTileBounds(point.X, point.Y, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY) && num3 != -1f)
                    {
                        focusedX = point.X;
                        focusedY = point.Y;
                    }
                }
                SmartCursorHelper._targets.Clear();
            }
            if (providedInfo.item.type == 2492 && focusedX == -1 && focusedY == -1)
            {
                SmartCursorHelper._targets.Clear();
                bool flag14 = false;
                if (Main.tile[providedInfo.screenTargetX, providedInfo.screenTargetY].active() && Main.tile[providedInfo.screenTargetX, providedInfo.screenTargetY].type == 314)
                {
                    flag14 = true;
                }
                if (!flag14)
                {
                    for (int l = providedInfo.reachableStartX; l <= providedInfo.reachableEndX; l++)
                    {
                        for (int m = providedInfo.reachableStartY; m <= providedInfo.reachableEndY; m++)
{
                            Tile tile2 = Main.tile[l, m];
                            if (tile2.active() && tile2.type == 314)
{
                                if (!Main.tile[l - 1, m].active() || Main.tileCut[(int)Main.tile[l - 1, m].type] || TileID.Sets.BreakableWhenPlacing[(int)Main.tile[l - 1, m].type])
{
                                    SmartCursorHelper._targets.Add(new Point(l - 1, m));
                                }
                                if (!Main.tile[l + 1, m].active() || Main.tileCut[(int)Main.tile[l + 1, m].type] || TileID.Sets.BreakableWhenPlacing[(int)Main.tile[l + 1, m].type])
{
                                    SmartCursorHelper._targets.Add(new Point(l + 1, m));
                                }
                            }
                        }
                    }
                }
                if (SmartCursorHelper._targets.Count > 0)
                {
                    float num5 = -1f;
                    Point point2 = SmartCursorHelper._targets[0];
                    for (int n = 0; n < SmartCursorHelper._targets.Count; n++)
                    {
                        if ((!Main.tile[SmartCursorHelper._targets[n].X, SmartCursorHelper._targets[n].Y - 1].active() || Main.tile[SmartCursorHelper._targets[n].X, SmartCursorHelper._targets[n].Y - 1].type != 314) && (!Main.tile[SmartCursorHelper._targets[n].X, SmartCursorHelper._targets[n].Y + 1].active() || Main.tile[SmartCursorHelper._targets[n].X, SmartCursorHelper._targets[n].Y + 1].type != 314))
{
                            float num6 = Vector2.Distance(new Vector2((float)SmartCursorHelper._targets[n].X, (float)SmartCursorHelper._targets[n].Y) * 16f + Vector2.One * 8f, providedInfo.mouse);
                            if (num5 == -1f || num6 < num5)
{
                                num5 = num6;
                                point2 = SmartCursorHelper._targets[n];
                            }
                        }
                    }
                    if (Collision.InTileBounds(point2.X, point2.Y, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY) && num5 != -1f)
                    {
                        focusedX = point2.X;
                        focusedY = point2.Y;
                    }
                }
                SmartCursorHelper._targets.Clear();
            }
        }
References Terraria.GameContent.SmartCursorHelper._targets, Terraria.Tile.active(), System.Collections.Generic.List< T >.Add(), Terraria.ID.TileID.Sets.BreakableWhenPlacing, System.Collections.Generic.List< T >.Clear(), System.Collections.Generic.List< T >.Count, Microsoft.Xna.Framework.Vector2.Distance(), Microsoft.Xna.Framework.Vector2.Dot(), int, Terraria.Collision.InTileBounds(), Terraria.Main.tile, Terraria.Main.tileCut, Terraria.Tile.type, Microsoft.Xna.Framework.Vector2.UnitX, Microsoft.Xna.Framework.Vector2.UnitY, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.SmartCursorHelper.SmartCursorLookup().