Terraria Decompiled: Terraria.GameContent.SmartCursorHelper.Step_GrassSeeds
Step_GrassSeeds()
static void Terraria.GameContent.SmartCursorHelper.Step_GrassSeeds (SmartCursorHelper::SmartCursorUsageInfo providedInfo, ref int focusedX, ref int focusedY) inline static private
Definition at line 210 of file SmartCursorHelper.cs.
        {
            if (focusedX > -1 || focusedY > -1)
            {
                return;
            }
            int type = providedInfo.item.type;
            if (type < 0 || type >= (int)ItemID.Count || !ItemID.Sets.GrassSeeds[type])
            {
                return;
            }
            SmartCursorHelper._targets.Clear();
            for (int i = providedInfo.reachableStartX; i <= providedInfo.reachableEndX; i++)
            {
                for (int j = providedInfo.reachableStartY; j <= providedInfo.reachableEndY; j++)
                {
                    Tile tile = Main.tile[i, j];
                    bool flag = !Main.tile[i - 1, j].active() || !Main.tile[i, j + 1].active() || !Main.tile[i + 1, j].active() || !Main.tile[i, j - 1].active();
                    bool flag2 = !Main.tile[i - 1, j - 1].active() || !Main.tile[i - 1, j + 1].active() || !Main.tile[i + 1, j + 1].active() || !Main.tile[i + 1, j - 1].active();
                    if (tile.active() && !tile.inActive() && (flag || flag2))
                    {
                        bool flag3;
                        if (type <= 195)
{
                            if (type == 59)
{
                                goto IL_0172;
                            }
                            if (type - 194 > 1)
{
                                goto IL_0165;
                            }
                            flag3 = tile.type == 59;
                        }
                        else
{
                            if (type == 2171)
{
                                goto IL_0172;
                            }
                            if (type != 5214)
{
                                goto IL_0165;
                            }
                            flag3 = tile.type == 57;
                        }
                        IL_01A5:
                        if (flag3)
{
                            SmartCursorHelper._targets.Add(new Point(i, j));
                            goto IL_01BA;
                        }
                        goto IL_01BA;
                        IL_0172:
                        flag3 = tile.type == 0 || tile.type == 59;
                        goto IL_01A5;
                        IL_0165:
                        flag3 = tile.type == 0;
                        goto IL_01A5;
                    }
                    IL_01BA:;
                }
            }
            if (SmartCursorHelper._targets.Count > 0)
            {
                float num = -1f;
                Point point = SmartCursorHelper._targets[0];
                for (int k = 0; k < SmartCursorHelper._targets.Count; k++)
                {
                    float num2 = Vector2.Distance(new Vector2((float)SmartCursorHelper._targets[k].X, (float)SmartCursorHelper._targets[k].Y) * 16f + Vector2.One * 8f, providedInfo.mouse);
                    if (num == -1f || num2 < num)
                    {
                        num = num2;
                        point = SmartCursorHelper._targets[k];
                    }
                }
                if (Collision.InTileBounds(point.X, point.Y, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY))
                {
                    focusedX = point.X;
                    focusedY = point.Y;
                }
            }
            SmartCursorHelper._targets.Clear();
        }
References Terraria.GameContent.SmartCursorHelper._targets, Terraria.Tile.active(), System.Collections.Generic.List< T >.Add(), System.Collections.Generic.List< T >.Clear(), System.Collections.Generic.List< T >.Count, Terraria.ID.ItemID.Count, Microsoft.Xna.Framework.Vector2.Distance(), Terraria.ID.ItemID.Sets.GrassSeeds, Terraria.Tile.inActive(), Terraria.Collision.InTileBounds(), Terraria.Main.tile, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.SmartCursorHelper.SmartCursorLookup().