Terraria Decompiled: Terraria.GameContent.SmartCursorHelper.Step_AlchemySeeds
Step_AlchemySeeds()
static void Terraria.GameContent.SmartCursorHelper.Step_AlchemySeeds (SmartCursorHelper::SmartCursorUsageInfo providedInfo, ref int focusedX, ref int focusedY) inline static private
Definition at line 455 of file SmartCursorHelper.cs.
        {
            if (providedInfo.item.createTile == 82 && focusedX == -1 && focusedY == -1)
            {
                int placeStyle = providedInfo.item.placeStyle;
                SmartCursorHelper._targets.Clear();
                for (int i = providedInfo.reachableStartX; i <= providedInfo.reachableEndX; i++)
                {
                    for (int j = providedInfo.reachableStartY; j <= providedInfo.reachableEndY; j++)
                    {
                        Tile tile = Main.tile[i, j];
                        Tile tile2 = Main.tile[i, j + 1];
                        bool flag = !tile.active() || TileID.Sets.BreakableWhenPlacing[(int)tile.type] || (Main.tileCut[(int)tile.type] && tile.type != 82 && tile.type != 83) || WorldGen.IsHarvestableHerbWithSeed((int)tile.type, (int)(tile.frameX / 18), j);
                        bool flag2 = tile2.nactive() && !tile2.halfBrick() && tile2.slope() == 0;
                        if (flag && flag2)
{
                            if (placeStyle == 0)
{
                                if (tile2.type != 78 && tile2.type != 380 && tile2.type != 2 && tile2.type != 477 && tile2.type != 109 && tile2.type != 492)
{
                                    goto IL_0358;
                                }
                                if (tile.liquid > 0)
{
                                    goto IL_0358;
                                }
                            }
                            else if (placeStyle == 1)
{
                                if (tile2.type != 78 && tile2.type != 380 && tile2.type != 60)
{
                                    goto IL_0358;
                                }
                                if (tile.liquid > 0)
{
                                    goto IL_0358;
                                }
                            }
                            else if (placeStyle == 2)
{
                                if (tile2.type != 78 && tile2.type != 380 && tile2.type != 0 && tile2.type != 59)
{
                                    goto IL_0358;
                                }
                                if (tile.liquid > 0)
{
                                    goto IL_0358;
                                }
                            }
                            else if (placeStyle == 3)
{
                                if (tile2.type != 78 && tile2.type != 380 && tile2.type != 203 && tile2.type != 199 && tile2.type != 23 && tile2.type != 25)
{
                                    goto IL_0358;
                                }
                                if (tile.liquid > 0)
{
                                    goto IL_0358;
                                }
                            }
                            else if (placeStyle == 4)
{
                                if (tile2.type != 78 && tile2.type != 380 && tile2.type != 53 && tile2.type != 116)
{
                                    goto IL_0358;
                                }
                                if (tile.liquid > 0 && tile.lava())
{
                                    goto IL_0358;
                                }
                            }
                            else if (placeStyle == 5)
{
                                if (tile2.type != 78 && tile2.type != 380 && tile2.type != 57 && tile2.type != 633)
{
                                    goto IL_0358;
                                }
                                if (tile.liquid > 0 && !tile.lava())
{
                                    goto IL_0358;
                                }
                            }
                            else if (placeStyle == 6 && ((tile2.type != 78 && tile2.type != 380 && tile2.type != 147 && tile2.type != 161 && tile2.type != 163 && tile2.type != 164 && tile2.type != 200) || (tile.liquid > 0 && tile.lava())))
{
                                goto IL_0358;
                            }
                            SmartCursorHelper._targets.Add(new Point(i, j));
                        }
                        IL_0358:;
                    }
                }
                if (SmartCursorHelper._targets.Count > 0)
                {
                    float num = -1f;
                    Point point = SmartCursorHelper._targets[0];
                    for (int k = 0; k < SmartCursorHelper._targets.Count; k++)
                    {
                        float num2 = Vector2.Distance(new Vector2((float)SmartCursorHelper._targets[k].X, (float)SmartCursorHelper._targets[k].Y) * 16f + Vector2.One * 8f, providedInfo.mouse);
                        if (num == -1f || num2 < num)
{
                            num = num2;
                            point = SmartCursorHelper._targets[k];
                        }
                    }
                    if (Collision.InTileBounds(point.X, point.Y, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY))
                    {
                        focusedX = point.X;
                        focusedY = point.Y;
                    }
                }
                SmartCursorHelper._targets.Clear();
            }
        }
References Terraria.GameContent.SmartCursorHelper._targets, Terraria.Tile.active(), System.Collections.Generic.List< T >.Add(), Terraria.ID.TileID.Sets.BreakableWhenPlacing, System.Collections.Generic.List< T >.Clear(), System.Collections.Generic.List< T >.Count, Microsoft.Xna.Framework.Vector2.Distance(), Terraria.Tile.frameX, Terraria.Tile.halfBrick(), int, Terraria.Collision.InTileBounds(), Terraria.WorldGen.IsHarvestableHerbWithSeed(), Terraria.Tile.lava(), Terraria.Tile.liquid, Terraria.Tile.nactive(), Terraria.Tile.slope(), Terraria.Main.tile, Terraria.Main.tileCut, Terraria.Tile.type, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.SmartCursorHelper.SmartCursorLookup().