Terraria Decompiled: Terraria.GameContent.SmartCursorHelper.Step_Acorns
Step_Acorns()
static void Terraria.GameContent.SmartCursorHelper.Step_Acorns (SmartCursorHelper::SmartCursorUsageInfo providedInfo, ref int focusedX, ref int focusedY) inline static private
Definition at line 2033 of file SmartCursorHelper.cs.
        {
            int num = 9;
            int num2 = 14;
            int num3 = 20;
            if (providedInfo.item.type == 27 && focusedX == -1 && focusedY == -1 && providedInfo.reachableStartY > 20)
            {
                SmartCursorHelper._targets.Clear();
                for (int i = providedInfo.reachableStartX; i <= providedInfo.reachableEndX; i++)
                {
                    for (int j = providedInfo.reachableStartY; j <= providedInfo.reachableEndY; j++)
                    {
                        Tile tile = Main.tile[i, j];
                        Tile tile2 = Main.tile[i, j - 1];
                        Tile tile3 = Main.tile[i, j + 1];
                        Tile tile4 = Main.tile[i - 1, j];
                        Tile tile5 = Main.tile[i + 1, j];
                        Tile tile6 = Main.tile[i - 2, j];
                        Tile tile7 = Main.tile[i + 2, j];
                        Tile tile8 = Main.tile[i - 3, j];
                        Tile tile9 = Main.tile[i + 3, j];
                        if ((!tile.active() || Main.tileCut[(int)tile.type] || TileID.Sets.BreakableWhenPlacing[(int)tile.type]) && (!tile2.active() || Main.tileCut[(int)tile2.type] || TileID.Sets.BreakableWhenPlacing[(int)tile2.type]) && tile3.active() && WorldGen.SolidTile2(tile3))
{
                            bool flag = (tile4.active() && TileID.Sets.CommonSapling[(int)tile4.type]) || (tile5.active() && TileID.Sets.CommonSapling[(int)tile5.type]);
                            bool flag2 = flag || (tile6.active() && TileID.Sets.CommonSapling[(int)tile6.type]) || (tile7.active() && TileID.Sets.CommonSapling[(int)tile7.type]) || (tile8.active() && TileID.Sets.CommonSapling[(int)tile8.type]) || (tile9.active() && TileID.Sets.CommonSapling[(int)tile9.type]);
                            ushort num4 = tile3.type;
                            if (num4 <= 116)
{
                                if (num4 <= 53)
{
                                    if (num4 != 2 && num4 != 23)
{
                                        if (num4 != 53)
{
                                            goto IL_037D;
                                        }
                                        goto IL_034D;
                                    }
                                }
                                else if (num4 <= 109)
{
                                    if (num4 != 60)
{
                                        if (num4 != 109)
{
                                            goto IL_037D;
                                        }
                                    }
                                    else
{
                                        if (!flag2 && WorldGen.EmptyTileCheck(i - 2, i + 2, j - num2 + 1, j, 20))
{
                                            SmartCursorHelper._targets.Add(new Point(i, j));
                                            goto IL_037D;
                                        }
                                        goto IL_037D;
                                    }
                                }
                                else
{
                                    if (num4 != 112 && num4 != 116)
{
                                        goto IL_037D;
                                    }
                                    goto IL_034D;
                                }
                            }
                            else if (num4 <= 234)
{
                                if (num4 != 147 && num4 != 199)
{
                                    if (num4 != 234)
{
                                        goto IL_037D;
                                    }
                                    goto IL_034D;
                                }
                            }
                            else if (num4 <= 492)
{
                                if (num4 != 477 && num4 != 492)
{
                                    goto IL_037D;
                                }
                            }
                            else if (num4 != 633 && num4 - 661 > 1)
{
                                goto IL_037D;
                            }
                            if (!flag2 && tile4.liquid == 0 && tile.liquid == 0 && tile5.liquid == 0 && WorldGen.EmptyTileCheck(i - 2, i + 2, j - num + 1, j, 20))
{
                                SmartCursorHelper._targets.Add(new Point(i, j));
                                goto IL_037D;
                            }
                            goto IL_037D;
                            IL_034D:
                            if (!flag && tile.liquid == 0 && WorldGen.EmptyTileCheck(i, i, j - num3, j, 20))
{
                                SmartCursorHelper._targets.Add(new Point(i, j));
                            }
                        }
                        IL_037D:;
                    }
                }
                SmartCursorHelper._toRemove.Clear();
                for (int k = 0; k < SmartCursorHelper._targets.Count; k++)
                {
                    bool flag3 = false;
                    for (int l = -1; l < 2; l += 2)
                    {
                        Tile tile10 = Main.tile[SmartCursorHelper._targets[k].X + l, SmartCursorHelper._targets[k].Y + 1];
                        if (tile10.active())
{
                            ushort num4 = tile10.type;
                            if (num4 <= 116)
{
                                if (num4 <= 53)
{
                                    if (num4 != 2 && num4 != 23 && num4 != 53)
{
                                        goto IL_04A6;
                                    }
                                }
                                else if (num4 <= 109)
{
                                    if (num4 != 60 && num4 != 109)
{
                                        goto IL_04A6;
                                    }
                                }
                                else if (num4 != 112 && num4 != 116)
{
                                    goto IL_04A6;
                                }
                            }
                            else if (num4 <= 234)
{
                                if (num4 != 147 && num4 != 199 && num4 != 234)
{
                                    goto IL_04A6;
                                }
                            }
                            else if (num4 <= 492)
{
                                if (num4 != 477 && num4 != 492)
{
                                    goto IL_04A6;
                                }
                            }
                            else if (num4 != 633 && num4 - 661 > 1)
{
                                goto IL_04A6;
                            }
                            flag3 = true;
                        }
                        IL_04A6:;
                    }
                    if (!flag3)
                    {
                        SmartCursorHelper._toRemove.Add(SmartCursorHelper._targets[k]);
                    }
                }
                for (int m = 0; m < SmartCursorHelper._toRemove.Count; m++)
                {
                    SmartCursorHelper._targets.Remove(SmartCursorHelper._toRemove[m]);
                }
                SmartCursorHelper._toRemove.Clear();
                if (SmartCursorHelper._targets.Count > 0)
                {
                    float num5 = -1f;
                    Point point = SmartCursorHelper._targets[0];
                    for (int n = 0; n < SmartCursorHelper._targets.Count; n++)
                    {
                        float num6 = Vector2.Distance(new Vector2((float)SmartCursorHelper._targets[n].X, (float)SmartCursorHelper._targets[n].Y) * 16f + Vector2.One * 8f, providedInfo.mouse);
                        if (num5 == -1f || num6 < num5)
{
                            num5 = num6;
                            point = SmartCursorHelper._targets[n];
                        }
                    }
                    if (Collision.InTileBounds(point.X, point.Y, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY))
                    {
                        focusedX = point.X;
                        focusedY = point.Y;
                    }
                }
                SmartCursorHelper._targets.Clear();
            }
        }
References Terraria.GameContent.SmartCursorHelper._targets, Terraria.GameContent.SmartCursorHelper._toRemove, Terraria.Tile.active(), System.Collections.Generic.List< T >.Add(), Terraria.ID.TileID.Sets.BreakableWhenPlacing, System.Collections.Generic.List< T >.Clear(), Terraria.ID.TileID.Sets.CommonSapling, System.Collections.Generic.List< T >.Count, Microsoft.Xna.Framework.Vector2.Distance(), Terraria.WorldGen.EmptyTileCheck(), int, Terraria.Collision.InTileBounds(), Terraria.Tile.liquid, System.Collections.Generic.List< T >.Remove(), Terraria.WorldGen.SolidTile2(), Terraria.Main.tile, Terraria.Main.tileCut, Terraria.Tile.type, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.SmartCursorHelper.SmartCursorLookup().