Terraria Decompiled: Terraria.GameContent.SmartCursorHelper.Step_GemCorns
Step_GemCorns()
static void Terraria.GameContent.SmartCursorHelper.Step_GemCorns (SmartCursorHelper::SmartCursorUsageInfo providedInfo, ref int focusedX, ref int focusedY) inline static private
Definition at line 2224 of file SmartCursorHelper.cs.
        {
            WorldGen.GrowTreeSettings growTreeSettings;
            if (!WorldGen.GrowTreeSettings.Profiles.TryGetFromItemId(providedInfo.item.type, out growTreeSettings))
            {
                return;
            }
            if (focusedX == -1 && focusedY == -1 && providedInfo.reachableStartY > 20)
            {
                SmartCursorHelper._targets.Clear();
                for (int i = providedInfo.reachableStartX; i <= providedInfo.reachableEndX; i++)
                {
                    for (int j = providedInfo.reachableStartY; j <= providedInfo.reachableEndY; j++)
                    {
                        Tile tile = Main.tile[i, j];
                        Tile tile2 = Main.tile[i, j - 1];
                        Tile tile3 = Main.tile[i, j + 1];
                        Tile tile4 = Main.tile[i - 1, j];
                        Tile tile5 = Main.tile[i + 1, j];
                        Tile tile6 = Main.tile[i - 2, j];
                        Tile tile7 = Main.tile[i + 2, j];
                        Tile tile8 = Main.tile[i - 3, j];
                        Tile tile9 = Main.tile[i + 3, j];
                        if (growTreeSettings.GroundTest((int)tile3.type) && (!tile.active() || Main.tileCut[(int)tile.type] || TileID.Sets.BreakableWhenPlacing[(int)tile.type]) && (!tile2.active() || Main.tileCut[(int)tile2.type] || TileID.Sets.BreakableWhenPlacing[(int)tile2.type]) && (!tile4.active() || !TileID.Sets.CommonSapling[(int)tile4.type]) && (!tile5.active() || !TileID.Sets.CommonSapling[(int)tile5.type]) && (!tile6.active() || !TileID.Sets.CommonSapling[(int)tile6.type]) && (!tile7.active() || !TileID.Sets.CommonSapling[(int)tile7.type]) && (!tile8.active() || !TileID.Sets.CommonSapling[(int)tile8.type]) && (!tile9.active() || !TileID.Sets.CommonSapling[(int)tile9.type]) && tile3.active() && WorldGen.SolidTile2(tile3) && tile4.liquid == 0 && tile.liquid == 0 && tile5.liquid == 0 && WorldGen.EmptyTileCheck(i - 2, i + 2, j - growTreeSettings.TreeHeightMax, j, (int)growTreeSettings.SaplingTileType))
{
                            SmartCursorHelper._targets.Add(new Point(i, j));
                        }
                    }
                }
                SmartCursorHelper._toRemove.Clear();
                for (int k = 0; k < SmartCursorHelper._targets.Count; k++)
                {
                    bool flag = false;
                    for (int l = -1; l < 2; l += 2)
                    {
                        Tile tile10 = Main.tile[SmartCursorHelper._targets[k].X + l, SmartCursorHelper._targets[k].Y + 1];
                        if (tile10.active() && growTreeSettings.GroundTest((int)tile10.type))
{
                            flag = true;
                        }
                    }
                    if (!flag)
                    {
                        SmartCursorHelper._toRemove.Add(SmartCursorHelper._targets[k]);
                    }
                }
                for (int m = 0; m < SmartCursorHelper._toRemove.Count; m++)
                {
                    SmartCursorHelper._targets.Remove(SmartCursorHelper._toRemove[m]);
                }
                SmartCursorHelper._toRemove.Clear();
                if (SmartCursorHelper._targets.Count > 0)
                {
                    float num = -1f;
                    Point point = SmartCursorHelper._targets[0];
                    for (int n = 0; n < SmartCursorHelper._targets.Count; n++)
                    {
                        float num2 = Vector2.Distance(new Vector2((float)SmartCursorHelper._targets[n].X, (float)SmartCursorHelper._targets[n].Y) * 16f + Vector2.One * 8f, providedInfo.mouse);
                        if (num == -1f || num2 < num)
{
                            num = num2;
                            point = SmartCursorHelper._targets[n];
                        }
                    }
                    if (Collision.InTileBounds(point.X, point.Y, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY))
                    {
                        focusedX = point.X;
                        focusedY = point.Y;
                    }
                }
                SmartCursorHelper._targets.Clear();
            }
        }
References Terraria.GameContent.SmartCursorHelper._targets, Terraria.GameContent.SmartCursorHelper._toRemove, Terraria.Tile.active(), System.Collections.Generic.List< T >.Add(), Terraria.ID.TileID.Sets.BreakableWhenPlacing, System.Collections.Generic.List< T >.Clear(), Terraria.ID.TileID.Sets.CommonSapling, System.Collections.Generic.List< T >.Count, Microsoft.Xna.Framework.Vector2.Distance(), Terraria.WorldGen.EmptyTileCheck(), Terraria.WorldGen.GrowTreeSettings.GroundTest, int, Terraria.Collision.InTileBounds(), System.Collections.Generic.List< T >.Remove(), Terraria.WorldGen.GrowTreeSettings.SaplingTileType, Terraria.WorldGen.SolidTile2(), Terraria.Main.tile, Terraria.Main.tileCut, Terraria.WorldGen.GrowTreeSettings.TreeHeightMax, Terraria.WorldGen.GrowTreeSettings.Profiles.TryGetFromItemId(), Terraria.Tile.type, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.SmartCursorHelper.SmartCursorLookup().