Terraria Decompiled: Terraria.GameContent.SmartCursorHelper.Step_MulticolorWrench
Step_MulticolorWrench()
static void Terraria.GameContent.SmartCursorHelper.Step_MulticolorWrench (SmartCursorHelper::SmartCursorUsageInfo providedInfo, ref int focusedX, ref int focusedY) inline static private
Definition at line 1730 of file SmartCursorHelper.cs.
        {
            if (providedInfo.item.type == 3625 && focusedX == -1 && focusedY == -1)
            {
                SmartCursorHelper._targets.Clear();
                WiresUI.Settings.MultiToolMode multiToolMode = WiresUI.Settings.ToolMode;
                WiresUI.Settings.MultiToolMode multiToolMode2 = (WiresUI.Settings.MultiToolMode)0;
                if (Main.tile[providedInfo.screenTargetX, providedInfo.screenTargetY].wire())
                {
                    multiToolMode2 |= WiresUI.Settings.MultiToolMode.Red;
                }
                if (Main.tile[providedInfo.screenTargetX, providedInfo.screenTargetY].wire2())
                {
                    multiToolMode2 |= WiresUI.Settings.MultiToolMode.Blue;
                }
                if (Main.tile[providedInfo.screenTargetX, providedInfo.screenTargetY].wire3())
                {
                    multiToolMode2 |= WiresUI.Settings.MultiToolMode.Green;
                }
                if (Main.tile[providedInfo.screenTargetX, providedInfo.screenTargetY].wire4())
                {
                    multiToolMode2 |= WiresUI.Settings.MultiToolMode.Yellow;
                }
                multiToolMode &= ~WiresUI.Settings.MultiToolMode.Cutter;
                bool flag = multiToolMode == multiToolMode2;
                multiToolMode = WiresUI.Settings.ToolMode;
                if (!flag)
                {
                    bool flag2 = (multiToolMode & WiresUI.Settings.MultiToolMode.Red) > (WiresUI.Settings.MultiToolMode)0;
                    bool flag3 = (multiToolMode & WiresUI.Settings.MultiToolMode.Blue) > (WiresUI.Settings.MultiToolMode)0;
                    bool flag4 = (multiToolMode & WiresUI.Settings.MultiToolMode.Green) > (WiresUI.Settings.MultiToolMode)0;
                    bool flag5 = (multiToolMode & WiresUI.Settings.MultiToolMode.Yellow) > (WiresUI.Settings.MultiToolMode)0;
                    bool flag6 = (multiToolMode & WiresUI.Settings.MultiToolMode.Cutter) > (WiresUI.Settings.MultiToolMode)0;
                    for (int i = providedInfo.reachableStartX; i <= providedInfo.reachableEndX; i++)
                    {
                        for (int j = providedInfo.reachableStartY; j <= providedInfo.reachableEndY; j++)
{
                            Tile tile = Main.tile[i, j];
                            if (flag6)
{
                                if ((tile.wire() && flag2) || (tile.wire2() && flag3) || (tile.wire3() && flag4) || (tile.wire4() && flag5))
{
                                    SmartCursorHelper._targets.Add(new Point(i, j));
                                }
                            }
                            else if ((tile.wire() && flag2) || (tile.wire2() && flag3) || (tile.wire3() && flag4) || (tile.wire4() && flag5))
{
                                if (flag2)
{
                                    if (!Main.tile[i - 1, j].wire())
{
                                        SmartCursorHelper._targets.Add(new Point(i - 1, j));
                                    }
                                    if (!Main.tile[i + 1, j].wire())
{
                                        SmartCursorHelper._targets.Add(new Point(i + 1, j));
                                    }
                                    if (!Main.tile[i, j - 1].wire())
{
                                        SmartCursorHelper._targets.Add(new Point(i, j - 1));
                                    }
                                    if (!Main.tile[i, j + 1].wire())
{
                                        SmartCursorHelper._targets.Add(new Point(i, j + 1));
                                    }
                                }
                                if (flag3)
{
                                    if (!Main.tile[i - 1, j].wire2())
{
                                        SmartCursorHelper._targets.Add(new Point(i - 1, j));
                                    }
                                    if (!Main.tile[i + 1, j].wire2())
{
                                        SmartCursorHelper._targets.Add(new Point(i + 1, j));
                                    }
                                    if (!Main.tile[i, j - 1].wire2())
{
                                        SmartCursorHelper._targets.Add(new Point(i, j - 1));
                                    }
                                    if (!Main.tile[i, j + 1].wire2())
{
                                        SmartCursorHelper._targets.Add(new Point(i, j + 1));
                                    }
                                }
                                if (flag4)
{
                                    if (!Main.tile[i - 1, j].wire3())
{
                                        SmartCursorHelper._targets.Add(new Point(i - 1, j));
                                    }
                                    if (!Main.tile[i + 1, j].wire3())
{
                                        SmartCursorHelper._targets.Add(new Point(i + 1, j));
                                    }
                                    if (!Main.tile[i, j - 1].wire3())
{
                                        SmartCursorHelper._targets.Add(new Point(i, j - 1));
                                    }
                                    if (!Main.tile[i, j + 1].wire3())
{
                                        SmartCursorHelper._targets.Add(new Point(i, j + 1));
                                    }
                                }
                                if (flag5)
{
                                    if (!Main.tile[i - 1, j].wire4())
{
                                        SmartCursorHelper._targets.Add(new Point(i - 1, j));
                                    }
                                    if (!Main.tile[i + 1, j].wire4())
{
                                        SmartCursorHelper._targets.Add(new Point(i + 1, j));
                                    }
                                    if (!Main.tile[i, j - 1].wire4())
{
                                        SmartCursorHelper._targets.Add(new Point(i, j - 1));
                                    }
                                    if (!Main.tile[i, j + 1].wire4())
{
                                        SmartCursorHelper._targets.Add(new Point(i, j + 1));
                                    }
                                }
                            }
                        }
                    }
                }
                if (SmartCursorHelper._targets.Count > 0)
                {
                    float num = -1f;
                    Point point = SmartCursorHelper._targets[0];
                    for (int k = 0; k < SmartCursorHelper._targets.Count; k++)
                    {
                        float num2 = Vector2.Distance(new Vector2((float)SmartCursorHelper._targets[k].X, (float)SmartCursorHelper._targets[k].Y) * 16f + Vector2.One * 8f, providedInfo.mouse);
                        if (num == -1f || num2 < num)
{
                            num = num2;
                            point = SmartCursorHelper._targets[k];
                        }
                    }
                    if (Collision.InTileBounds(point.X, point.Y, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY))
                    {
                        focusedX = point.X;
                        focusedY = point.Y;
                    }
                }
                SmartCursorHelper._targets.Clear();
            }
        }
References Terraria.GameContent.SmartCursorHelper._targets, System.Collections.Generic.List< T >.Add(), System.Collections.Generic.List< T >.Clear(), System.Collections.Generic.List< T >.Count, Microsoft.Xna.Framework.Vector2.Distance(), Terraria.Collision.InTileBounds(), Terraria.Main.tile, Terraria.GameContent.UI.WiresUI.Settings.ToolMode, Terraria.Tile.wire(), Terraria.Tile.wire2(), Terraria.Tile.wire3(), Terraria.Tile.wire4(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.SmartCursorHelper.SmartCursorLookup().