Terraria Decompiled: Terraria.GameContent.SmartCursorHelper.Step_Platforms
Step_Platforms()
static void Terraria.GameContent.SmartCursorHelper.Step_Platforms (SmartCursorHelper::SmartCursorUsageInfo providedInfo, ref int focusedX, ref int focusedY) inline static private
Definition at line 1326 of file SmartCursorHelper.cs.
        {
            if (providedInfo.item.createTile >= 0 && TileID.Sets.Platforms[providedInfo.item.createTile] && focusedX == -1 && focusedY == -1 && !SmartCursorHelper.IsPlatform(providedInfo.screenTargetX, providedInfo.screenTargetY))
            {
                SmartCursorHelper._targets.Clear();
                SmartCursorHelper._points.Clear();
                for (int i = providedInfo.reachableStartX; i <= providedInfo.reachableEndX; i++)
                {
                    for (int j = providedInfo.reachableStartY; j <= providedInfo.reachableEndY; j++)
                    {
                        Point desiredDirectionFrom = SmartCursorHelper.GetDesiredDirectionFrom(providedInfo.mouse - new Point(i, j).ToWorldCoordinates(8f, 8f));
                        bool flag = !SmartCursorHelper.IsPlatform(i, j);
                        if (flag && desiredDirectionFrom.Y == 0 && Main.tile[i, j].active() && !WorldGen.SolidTile(i, j, false) && (SmartCursorHelper.IsPlatform(i - 1, j) || SmartCursorHelper.IsPlatform(i + 1, j)))
{
                            flag = false;
                        }
                        if (!flag)
{
                            int num = ((desiredDirectionFrom.X == desiredDirectionFrom.Y) ? 2 : ((desiredDirectionFrom.X == -desiredDirectionFrom.Y) ? 1 : 0));
                            if ((num == 0 || (int)Main.tile[i, j].slope() != num) && (desiredDirectionFrom.X != 0 || (!SmartCursorHelper.IsPlatform(i - 1, j + desiredDirectionFrom.Y) && !SmartCursorHelper.IsPlatform(i + 1, j + desiredDirectionFrom.Y))))
{
                                Tile tile = Main.tile[i + desiredDirectionFrom.X, j + desiredDirectionFrom.Y];
                                if ((!tile.active() || Main.tileCut[(int)tile.type]) && SmartCursorHelper.AllowedForContinuity(i + desiredDirectionFrom.X, j + desiredDirectionFrom.Y, 2))
{
                                    SmartCursorHelper._targets.Add(new Point(i + desiredDirectionFrom.X, j + desiredDirectionFrom.Y));
                                    SmartCursorHelper._points.Add(new Point(desiredDirectionFrom.X, desiredDirectionFrom.Y));
                                }
                            }
                        }
                    }
                }
                if (SmartCursorHelper._targets.Count > 0)
                {
                    float num2 = -1f;
                    float num3 = -1f;
                    Point point = SmartCursorHelper._targets[0];
                    Point point2 = SmartCursorHelper._points[0];
                    for (int k = 0; k < SmartCursorHelper._targets.Count; k++)
                    {
                        Point point3 = SmartCursorHelper._targets[k];
                        Point point4 = SmartCursorHelper._points[k];
                        Vector2 vector = providedInfo.mouse - SmartCursorHelper._targets[k].ToWorldCoordinates(8f, 8f);
                        float num4 = vector.Length();
                        float num5 = Vector2.Dot(vector, point4.ToVector2());
                        if (num2 == -1f || num4 < num2 || (num4 == num2 && num5 > num3))
{
                            num2 = num4;
                            num3 = num5;
                            point = point3;
                            point2 = point4;
                        }
                    }
                    if (Collision.InTileBounds(point.X, point.Y, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY))
                    {
                        focusedX = point.X;
                        focusedY = point.Y;
                        SmartCursorHelper._lockedDesiredDirection = new Point?(new Point(point2.X, point2.Y));
                        SmartCursorHelper._lockedContinuityCoords = new Point?(new Point(focusedX, focusedY));
                    }
                }
                SmartCursorHelper._targets.Clear();
                SmartCursorHelper._points.Clear();
            }
        }
References Terraria.GameContent.SmartCursorHelper._points, Terraria.GameContent.SmartCursorHelper._targets, Terraria.Tile.active(), System.Collections.Generic.List< T >.Add(), Terraria.GameContent.SmartCursorHelper.AllowedForContinuity(), System.Collections.Generic.List< T >.Clear(), System.Collections.Generic.List< T >.Count, Microsoft.Xna.Framework.Vector2.Dot(), Terraria.GameContent.SmartCursorHelper.GetDesiredDirectionFrom(), int, Terraria.Collision.InTileBounds(), Terraria.GameContent.SmartCursorHelper.IsPlatform(), Microsoft.Xna.Framework.Vector2.Length(), Terraria.ID.TileID.Sets.Platforms, Terraria.Tile.slope(), Terraria.WorldGen.SolidTile(), Terraria.Main.tile, Terraria.Main.tileCut, Terraria.Tile.type, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.SmartCursorHelper.SmartCursorLookup().