Terraria Decompiled: Terraria.GameContent.SmartCursorHelper.Step_ForceCursorToAnyMinableThing
Step_ForceCursorToAnyMinableThing()
static void Terraria.GameContent.SmartCursorHelper.Step_ForceCursorToAnyMinableThing (SmartCursorHelper::SmartCursorUsageInfo providedInfo, ref int fX, ref int fY) inline static private
Definition at line 2299 of file SmartCursorHelper.cs.
        {
            int reachableStartX = providedInfo.reachableStartX;
            int reachableStartY = providedInfo.reachableStartY;
            int reachableEndX = providedInfo.reachableEndX;
            int reachableEndY = providedInfo.reachableEndY;
            int screenTargetX = providedInfo.screenTargetX;
            int screenTargetY = providedInfo.screenTargetY;
            Vector2 mouse = providedInfo.mouse;
            Item item = providedInfo.item;
            if (fX != -1 || fY != -1)
            {
                return;
            }
            if (PlayerInput.UsingGamepad)
            {
                return;
            }
            Point point = mouse.ToTileCoordinates();
            int x = point.X;
            int y = point.Y;
            if (!Collision.InTileBounds(x, y, reachableStartX, reachableStartY, reachableEndX, reachableEndY))
            {
                return;
            }
            Tile tile = Main.tile[x, y];
            bool flag = tile.active() && WorldGen.CanKillTile(x, y) && (!Main.tileSolid[(int)tile.type] || Main.tileSolidTop[(int)tile.type]);
            if (flag && Main.tileAxe[(int)tile.type] && item.axe < 1)
            {
                flag = false;
            }
            if (flag && Main.tileHammer[(int)tile.type] && item.hammer < 1)
            {
                flag = false;
            }
            if (flag && !Main.tileHammer[(int)tile.type] && !Main.tileAxe[(int)tile.type] && item.pick < 1)
            {
                flag = false;
            }
            if (!flag)
            {
                return;
            }
            fX = x;
            fY = y;
        }
References Terraria.Tile.active(), Terraria.WorldGen.CanKillTile(), int, Terraria.Collision.InTileBounds(), System.item, Terraria.Main.tile, Terraria.Main.tileAxe, Terraria.Main.tileHammer, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Tile.type, Terraria.GameInput.PlayerInput.UsingGamepad, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.SmartCursorHelper.SmartCursorLookup().