Terraria Decompiled: Terraria.GameContent.SmartCursorHelper.Step_Pickaxe_MineShinies
Step_Pickaxe_MineShinies()
static void Terraria.GameContent.SmartCursorHelper.Step_Pickaxe_MineShinies (SmartCursorHelper::SmartCursorUsageInfo providedInfo, ref int fX, ref int fY) inline static
Definition at line 2347 of file SmartCursorHelper.cs.
        {
            int reachableStartX = providedInfo.reachableStartX;
            int reachableStartY = providedInfo.reachableStartY;
            int reachableEndX = providedInfo.reachableEndX;
            int reachableEndY = providedInfo.reachableEndY;
            int screenTargetX = providedInfo.screenTargetX;
            int screenTargetY = providedInfo.screenTargetY;
            Item item = providedInfo.item;
            Vector2 mouse = providedInfo.mouse;
            if (item.pick <= 0 || fX != -1 || fY != -1)
            {
                return;
            }
            SmartCursorHelper._targets.Clear();
            if (item.type != 1333 && item.type != 523)
            {
                bool flag = item.type != 4384;
            }
            int num = 0;
            for (int i = reachableStartX; i <= reachableEndX; i++)
            {
                for (int j = reachableStartY; j <= reachableEndY; j++)
                {
                    Tile tile = Main.tile[i, j];
                    Main.tile[i - 1, j];
                    Main.tile[i + 1, j];
                    Main.tile[i, j + 1];
                    if (tile.active())
                    {
                        int num2 = TileID.Sets.SmartCursorPickaxePriorityOverride[(int)tile.type];
                        if (num2 > 0)
{
                            if (num < num2)
{
                                num = num2;
                            }
                            SmartCursorHelper._targets.Add(new Point(i, j));
                        }
                    }
                }
            }
            SmartCursorHelper._targets2.Clear();
            foreach (Point point in SmartCursorHelper._targets2)
            {
                Tile tile2 = Main.tile[point.X, point.Y];
                if (TileID.Sets.SmartCursorPickaxePriorityOverride[(int)tile2.type] < num)
                {
                    SmartCursorHelper._targets2.Add(point);
                }
            }
            foreach (Point point2 in SmartCursorHelper._targets2)
            {
                SmartCursorHelper._targets.Remove(point2);
            }
            if (SmartCursorHelper._targets.Count > 0)
            {
                float num3 = -1f;
                Point point3 = SmartCursorHelper._targets[0];
                for (int k = 0; k < SmartCursorHelper._targets.Count; k++)
                {
                    float num4 = Vector2.Distance(new Vector2((float)SmartCursorHelper._targets[k].X, (float)SmartCursorHelper._targets[k].Y) * 16f + Vector2.One * 8f, mouse);
                    if (num3 == -1f || num4 < num3)
                    {
                        num3 = num4;
                        point3 = SmartCursorHelper._targets[k];
                    }
                }
                if (Collision.InTileBounds(point3.X, point3.Y, reachableStartX, reachableStartY, reachableEndX, reachableEndY))
                {
                    fX = point3.X;
                    fY = point3.Y;
                }
            }
            SmartCursorHelper._targets.Clear();
        }
References Terraria.GameContent.SmartCursorHelper._targets, Terraria.GameContent.SmartCursorHelper._targets2, Terraria.Tile.active(), System.Collections.Generic.List< T >.Add(), System.Collections.Generic.List< T >.Clear(), System.Collections.Generic.List< T >.Count, Microsoft.Xna.Framework.Vector2.Distance(), int, Terraria.Collision.InTileBounds(), System.item, Microsoft.Xna.Framework.Vector2.One, System.Collections.Generic.List< T >.Remove(), Terraria.ID.TileID.Sets.SmartCursorPickaxePriorityOverride, Terraria.Main.tile, Terraria.Tile.type, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.SmartCursorHelper.SmartCursorLookup().