Terraria Decompiled: Terraria.GameContent.SmartCursorHelper.Step_Axe
Step_Axe()
static void Terraria.GameContent.SmartCursorHelper.Step_Axe (SmartCursorHelper::SmartCursorUsageInfo providedInfo, ref int fX, ref int fY) inline static
Definition at line 2660 of file SmartCursorHelper.cs.
        {
            int reachableStartX = providedInfo.reachableStartX;
            int reachableStartY = providedInfo.reachableStartY;
            int reachableEndX = providedInfo.reachableEndX;
            int reachableEndY = providedInfo.reachableEndY;
            int screenTargetX = providedInfo.screenTargetX;
            int screenTargetY = providedInfo.screenTargetY;
            if (providedInfo.item.axe > 0 && fX == -1 && fY == -1)
            {
                float num = -1f;
                for (int i = reachableStartX; i <= reachableEndX; i++)
                {
                    for (int j = reachableStartY; j <= reachableEndY; j++)
                    {
                        if (Main.tile[i, j].active())
{
                            Tile tile = Main.tile[i, j];
                            if (Main.tileAxe[(int)tile.type] && !TileID.Sets.IgnoreSmartCursorPriorityAxe[(int)tile.type])
{
                                int num2 = i;
                                int num3 = j;
                                int type = (int)tile.type;
                                if (TileID.Sets.IsATreeTrunk[type])
{
                                    if (Collision.InTileBounds(num2 + 1, num3, reachableStartX, reachableStartY, reachableEndX, reachableEndY))
{
                                        if (Main.tile[num2, num3].frameY >= 198 && Main.tile[num2, num3].frameX == 44)
{
                                            num2++;
                                        }
                                        if (Main.tile[num2, num3].frameX == 66 && Main.tile[num2, num3].frameY <= 44)
{
                                            num2++;
                                        }
                                        if (Main.tile[num2, num3].frameX == 44 && Main.tile[num2, num3].frameY >= 132 && Main.tile[num2, num3].frameY <= 176)
{
                                            num2++;
                                        }
                                    }
                                    if (Collision.InTileBounds(num2 - 1, num3, reachableStartX, reachableStartY, reachableEndX, reachableEndY))
{
                                        if (Main.tile[num2, num3].frameY >= 198 && Main.tile[num2, num3].frameX == 66)
{
                                            num2--;
                                        }
                                        if (Main.tile[num2, num3].frameX == 88 && Main.tile[num2, num3].frameY >= 66 && Main.tile[num2, num3].frameY <= 110)
{
                                            num2--;
                                        }
                                        if (Main.tile[num2, num3].frameX == 22 && Main.tile[num2, num3].frameY >= 132 && Main.tile[num2, num3].frameY <= 176)
{
                                            num2--;
                                        }
                                    }
                                    while (Main.tile[num2, num3].active() && (int)Main.tile[num2, num3].type == type && (int)Main.tile[num2, num3 + 1].type == type && Collision.InTileBounds(num2, num3 + 1, reachableStartX, reachableStartY, reachableEndX, reachableEndY))
{
                                        num3++;
                                    }
                                }
                                if (tile.type == 80)
{
                                    if (Collision.InTileBounds(num2 + 1, num3, reachableStartX, reachableStartY, reachableEndX, reachableEndY))
{
                                        if (Main.tile[num2, num3].frameX == 54)
{
                                            num2++;
                                        }
                                        if (Main.tile[num2, num3].frameX == 108 && Main.tile[num2, num3].frameY == 36)
{
                                            num2++;
                                        }
                                    }
                                    if (Collision.InTileBounds(num2 - 1, num3, reachableStartX, reachableStartY, reachableEndX, reachableEndY))
{
                                        if (Main.tile[num2, num3].frameX == 36)
{
                                            num2--;
                                        }
                                        if (Main.tile[num2, num3].frameX == 108 && Main.tile[num2, num3].frameY == 18)
{
                                            num2--;
                                        }
                                    }
                                    while (Main.tile[num2, num3].active() && Main.tile[num2, num3].type == 80 && Main.tile[num2, num3 + 1].type == 80 && Collision.InTileBounds(num2, num3 + 1, reachableStartX, reachableStartY, reachableEndX, reachableEndY))
{
                                        num3++;
                                    }
                                }
                                if (tile.type != 323)
{
                                    if (tile.type != 72)
{
                                        goto IL_04C4;
                                    }
                                }
                                while (Main.tile[num2, num3].active() && ((Main.tile[num2, num3].type == 323 && Main.tile[num2, num3 + 1].type == 323) || (Main.tile[num2, num3].type == 72 && Main.tile[num2, num3 + 1].type == 72)) && Collision.InTileBounds(num2, num3 + 1, reachableStartX, reachableStartY, reachableEndX, reachableEndY))
{
                                    num3++;
                                }
                                IL_04C4:
                                float num4 = Vector2.Distance(new Vector2((float)num2, (float)num3) * 16f + Vector2.One * 8f, providedInfo.mouse);
                                if (num == -1f || num4 < num)
{
                                    num = num4;
                                    fX = num2;
                                    fY = num3;
                                }
                            }
                        }
                    }
                }
            }
        }
References Terraria.Tile.active(), Microsoft.Xna.Framework.Vector2.Distance(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.ID.TileID.Sets.IgnoreSmartCursorPriorityAxe, int, Terraria.Collision.InTileBounds(), Terraria.ID.TileID.Sets.IsATreeTrunk, Microsoft.Xna.Framework.Vector2.One, Terraria.Main.tile, Terraria.Main.tileAxe, and Terraria.Tile.type.
Referenced by Terraria.Projectile.AI_067_FreakingPirates_TryAssigningHelp(), and Terraria.GameContent.SmartCursorHelper.SmartCursorLookup().