Terraria Decompiled: Terraria.GameContent.SmartCursorHelper.Step_Walls
Step_Walls()
static void Terraria.GameContent.SmartCursorHelper.Step_Walls (SmartCursorHelper::SmartCursorUsageInfo providedInfo, ref int focusedX, ref int focusedY) inline static private
Definition at line 1102 of file SmartCursorHelper.cs.
        {
            int width = providedInfo.player.width;
            int height = providedInfo.player.height;
            if (providedInfo.item.createWall > 0 && focusedX == -1 && focusedY == -1)
            {
                SmartCursorHelper._targets.Clear();
                for (int i = providedInfo.reachableStartX; i <= providedInfo.reachableEndX; i++)
                {
                    for (int j = providedInfo.reachableStartY; j <= providedInfo.reachableEndY; j++)
                    {
                        Tile tile = Main.tile[i, j];
                        if (tile.wall == 0 && (!tile.active() || !Main.tileSolid[(int)tile.type] || Main.tileSolidTop[(int)tile.type]) && Collision.CanHitWithCheck(providedInfo.position, width, height, new Vector2((float)i, (float)j) * 16f, 16, 16, new Utils.TileActionAttempt(DelegateMethods.NotDoorStand)))
{
                            bool flag = false;
                            if (Main.tile[i - 1, j].active() || Main.tile[i - 1, j].wall > 0)
{
                                flag = true;
                            }
                            if (Main.tile[i + 1, j].active() || Main.tile[i + 1, j].wall > 0)
{
                                flag = true;
                            }
                            if (Main.tile[i, j - 1].active() || Main.tile[i, j - 1].wall > 0)
{
                                flag = true;
                            }
                            if (Main.tile[i, j + 1].active() || Main.tile[i, j + 1].wall > 0)
{
                                flag = true;
                            }
                            if (WorldGen.IsOpenDoorAnchorFrame(i, j))
{
                                flag = false;
                            }
                            if (flag)
{
                                SmartCursorHelper._targets.Add(new Point(i, j));
                            }
                        }
                    }
                }
                if (SmartCursorHelper._targets.Count > 0)
                {
                    float num = -1f;
                    Point point = SmartCursorHelper._targets[0];
                    for (int k = 0; k < SmartCursorHelper._targets.Count; k++)
                    {
                        float num2 = Vector2.Distance(new Vector2((float)SmartCursorHelper._targets[k].X, (float)SmartCursorHelper._targets[k].Y) * 16f + Vector2.One * 8f, providedInfo.mouse);
                        if (num == -1f || num2 < num)
{
                            num = num2;
                            point = SmartCursorHelper._targets[k];
                        }
                    }
                    if (Collision.InTileBounds(point.X, point.Y, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY))
                    {
                        focusedX = point.X;
                        focusedY = point.Y;
                    }
                }
                SmartCursorHelper._targets.Clear();
            }
        }
References Terraria.GameContent.SmartCursorHelper._targets, Terraria.Tile.active(), System.Collections.Generic.List< T >.Add(), Terraria.Collision.CanHitWithCheck(), System.Collections.Generic.List< T >.Clear(), System.Collections.Generic.List< T >.Count, Microsoft.Xna.Framework.Vector2.Distance(), Terraria.Collision.InTileBounds(), Terraria.WorldGen.IsOpenDoorAnchorFrame(), Terraria.DelegateMethods.NotDoorStand(), Terraria.Main.tile, Terraria.Utils.TileActionAttempt(), Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Tile.type, Terraria.Tile.wall, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.SmartCursorHelper.SmartCursorLookup().