Terraria Decompiled: Terraria.GameContent.SmartCursorHelper.Step_Hammers
Step_Hammers()
static void Terraria.GameContent.SmartCursorHelper.Step_Hammers (SmartCursorHelper::SmartCursorUsageInfo providedInfo, ref int focusedX, ref int focusedY) inline static private
Definition at line 1540 of file SmartCursorHelper.cs.
        {
            int width = providedInfo.player.width;
            int height = providedInfo.player.height;
            if (providedInfo.item.hammer > 0 && focusedX == -1 && focusedY == -1)
            {
                Vector2 vector = providedInfo.mouse - providedInfo.Center;
                int num = Math.Sign(vector.X);
                int num2 = Math.Sign(vector.Y);
                if (Math.Abs(vector.X) > Math.Abs(vector.Y) * 3f)
                {
                    num2 = 0;
                    providedInfo.mouse.Y = providedInfo.Center.Y;
                }
                if (Math.Abs(vector.Y) > Math.Abs(vector.X) * 3f)
                {
                    num = 0;
                    providedInfo.mouse.X = providedInfo.Center.X;
                }
                int num3 = (int)providedInfo.Center.X / 16;
                int num4 = (int)providedInfo.Center.Y / 16;
                SmartCursorHelper._points.Clear();
                SmartCursorHelper._endpoints.Clear();
                int num5 = 1;
                if (num2 == -1 && num != 0)
                {
                    num5 = -1;
                }
                int num6 = (int)((providedInfo.position.X + (float)(width / 2) + (float)((width / 2 - 1) * num)) / 16f);
                int num7 = (int)(((double)providedInfo.position.Y + 0.1) / 16.0);
                if (num5 == -1)
                {
                    num7 = (int)((providedInfo.position.Y + (float)height - 1f) / 16f);
                }
                int num8 = width / 16 + ((width % 16 == 0) ? 0 : 1);
                int num9 = height / 16 + ((height % 16 == 0) ? 0 : 1);
                if (num != 0)
                {
                    for (int i = 0; i < num9; i++)
                    {
                        if (Main.tile[num6, num7 + i * num5] != null)
{
                            SmartCursorHelper._points.Add(new Point(num6, num7 + i * num5));
                        }
                    }
                }
                if (num2 != 0)
                {
                    for (int j = 0; j < num8; j++)
                    {
                        if (Main.tile[(int)(providedInfo.position.X / 16f) + j, num7] != null)
{
                            SmartCursorHelper._points.Add(new Point((int)(providedInfo.position.X / 16f) + j, num7));
                        }
                    }
                }
                int num10 = (int)((providedInfo.mouse.X + (float)((width / 2 - 1) * num)) / 16f);
                int num11 = (int)(((double)providedInfo.mouse.Y + 0.1 - (double)(height / 2 + 1)) / 16.0);
                if (num5 == -1)
                {
                    num11 = (int)((providedInfo.mouse.Y + (float)(height / 2) - 1f) / 16f);
                }
                if (providedInfo.player.gravDir == -1f && num2 == 0)
                {
                    num11++;
                }
                if (num11 < 10)
                {
                    num11 = 10;
                }
                if (num11 > Main.maxTilesY - 10)
                {
                    num11 = Main.maxTilesY - 10;
                }
                int num12 = width / 16 + ((width % 16 == 0) ? 0 : 1);
                int num13 = height / 16 + ((height % 16 == 0) ? 0 : 1);
                if (num != 0)
                {
                    for (int k = 0; k < num13; k++)
                    {
                        if (Main.tile[num10, num11 + k * num5] != null)
{
                            SmartCursorHelper._endpoints.Add(new Point(num10, num11 + k * num5));
                        }
                    }
                }
                if (num2 != 0)
                {
                    for (int l = 0; l < num12; l++)
                    {
                        if (Main.tile[(int)((providedInfo.mouse.X - (float)(width / 2)) / 16f) + l, num11] != null)
{
                            SmartCursorHelper._endpoints.Add(new Point((int)((providedInfo.mouse.X - (float)(width / 2)) / 16f) + l, num11));
                        }
                    }
                }
                SmartCursorHelper._targets.Clear();
                while (SmartCursorHelper._points.Count > 0)
                {
                    Point point = SmartCursorHelper._points[0];
                    Point point2 = SmartCursorHelper._endpoints[0];
                    Point point3 = Collision.HitLineWall(point.X, point.Y, point2.X, point2.Y);
                    if (point3.X == -1 || point3.Y == -1)
                    {
                        SmartCursorHelper._points.Remove(point);
                        SmartCursorHelper._endpoints.Remove(point2);
                    }
                    else
                    {
                        if (point3.X != point2.X || point3.Y != point2.Y)
{
                            SmartCursorHelper._targets.Add(point3);
                        }
                        Main.tile[point3.X, point3.Y];
                        if (Collision.HitWallSubstep(point3.X, point3.Y))
{
                            SmartCursorHelper._targets.Add(point3);
                        }
                        SmartCursorHelper._points.Remove(point);
                        SmartCursorHelper._endpoints.Remove(point2);
                    }
                }
                if (SmartCursorHelper._targets.Count > 0)
                {
                    float num14 = -1f;
                    Point point4 = new Point(-1, -1);
                    for (int m = 0; m < SmartCursorHelper._targets.Count; m++)
                    {
                        if (!Main.tile[SmartCursorHelper._targets[m].X, SmartCursorHelper._targets[m].Y].active() || Main.tile[SmartCursorHelper._targets[m].X, SmartCursorHelper._targets[m].Y].type != 26)
{
                            float num15 = Vector2.Distance(new Vector2((float)SmartCursorHelper._targets[m].X, (float)SmartCursorHelper._targets[m].Y) * 16f + Vector2.One * 8f, providedInfo.Center);
                            if (num14 == -1f || num15 < num14)
{
                                num14 = num15;
                                point4 = SmartCursorHelper._targets[m];
                            }
                        }
                    }
                    if (point4.X != -1 && Collision.InTileBounds(point4.X, point4.Y, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY))
                    {
                        providedInfo.player.poundRelease = false;
                        focusedX = point4.X;
                        focusedY = point4.Y;
                    }
                }
                SmartCursorHelper._targets.Clear();
                SmartCursorHelper._points.Clear();
                SmartCursorHelper._endpoints.Clear();
            }
            if (providedInfo.item.hammer > 0 && focusedX == -1 && focusedY == -1)
            {
                SmartCursorHelper._targets.Clear();
                for (int n = providedInfo.reachableStartX; n <= providedInfo.reachableEndX; n++)
                {
                    for (int num16 = providedInfo.reachableStartY; num16 <= providedInfo.reachableEndY; num16++)
                    {
                        if (Main.tile[n, num16].wall > 0 && Collision.HitWallSubstep(n, num16))
{
                            SmartCursorHelper._targets.Add(new Point(n, num16));
                        }
                    }
                }
                if (SmartCursorHelper._targets.Count > 0)
                {
                    float num17 = -1f;
                    Point point5 = new Point(-1, -1);
                    for (int num18 = 0; num18 < SmartCursorHelper._targets.Count; num18++)
                    {
                        if (!Main.tile[SmartCursorHelper._targets[num18].X, SmartCursorHelper._targets[num18].Y].active() || Main.tile[SmartCursorHelper._targets[num18].X, SmartCursorHelper._targets[num18].Y].type != 26)
{
                            float num19 = Vector2.Distance(new Vector2((float)SmartCursorHelper._targets[num18].X, (float)SmartCursorHelper._targets[num18].Y) * 16f + Vector2.One * 8f, providedInfo.mouse);
                            if (num17 == -1f || num19 < num17)
{
                                num17 = num19;
                                point5 = SmartCursorHelper._targets[num18];
                            }
                        }
                    }
                    if (point5.X != -1 && Collision.InTileBounds(point5.X, point5.Y, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY))
                    {
                        providedInfo.player.poundRelease = false;
                        focusedX = point5.X;
                        focusedY = point5.Y;
                    }
                }
                SmartCursorHelper._targets.Clear();
            }
        }
References Terraria.GameContent.SmartCursorHelper._endpoints, Terraria.GameContent.SmartCursorHelper._points, Terraria.GameContent.SmartCursorHelper._targets, System.Math.Abs(), Terraria.Tile.active(), System.Collections.Generic.List< T >.Add(), System.Collections.Generic.List< T >.Clear(), System.Collections.Generic.List< T >.Count, Microsoft.Xna.Framework.Vector2.Distance(), Terraria.Collision.HitLineWall(), Terraria.Collision.HitWallSubstep(), int, Terraria.Collision.InTileBounds(), Terraria.Main.maxTilesY, Microsoft.Xna.Framework.Vector2.One, System.Collections.Generic.List< T >.Remove(), System.Math.Sign(), Terraria.Main.tile, Terraria.Tile.type, Terraria.Tile.wall, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Point.Y, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.GameContent.SmartCursorHelper.SmartCursorLookup().