Terraria Decompiled: Terraria.GameContent.SmartCursorHelper.IsValidSpotForTorch
IsValidSpotForTorch()
static bool Terraria.GameContent.SmartCursorHelper.IsValidSpotForTorch (int x, int y, Tile tileCache) inline static private
Definition at line 2950 of file SmartCursorHelper.cs.
        {
            if (tileCache.wall > 0)
            {
                return true;
            }
            if (TileID.Sets.Torches[(int)tileCache.type])
            {
                return false;
            }
            Tile tile = Main.tile[x - 1, y];
            if (tile.active() && (tile.slope() == 0 || tile.slope() % 2 != 1) && ((Main.tileSolid[(int)tile.type] && !Main.tileNoAttach[(int)tile.type] && !Main.tileSolidTop[(int)tile.type] && !TileID.Sets.NotReallySolid[(int)tile.type]) || TileID.Sets.IsBeam[(int)tile.type] || (WorldGen.IsTreeType((int)tile.type) && WorldGen.IsTreeType((int)Main.tile[x - 1, y - 1].type) && WorldGen.IsTreeType((int)Main.tile[x - 1, y + 1].type))))
            {
                return true;
            }
            Tile tile2 = Main.tile[x + 1, y];
            if (tile2.active() && (tile2.slope() == 0 || tile2.slope() % 2 != 0) && ((Main.tileSolid[(int)tile2.type] && !Main.tileNoAttach[(int)tile2.type] && !Main.tileSolidTop[(int)tile2.type] && !TileID.Sets.NotReallySolid[(int)tile2.type]) || TileID.Sets.IsBeam[(int)tile2.type] || (WorldGen.IsTreeType((int)tile2.type) && WorldGen.IsTreeType((int)Main.tile[x + 1, y - 1].type) && WorldGen.IsTreeType((int)Main.tile[x + 1, y + 1].type))))
            {
                return true;
            }
            Tile tile3 = Main.tile[x, y + 1];
            return tile3.active() && tile3.slope() == 0 && !tile3.halfBrick() && (((Main.tileSolid[(int)tile3.type] && !Main.tileSolidTop[(int)tile3.type]) || TileID.Sets.Platforms[(int)tile3.type]) && !TileID.Sets.NotReallySolid[(int)tile3.type]);
        }
References Terraria.Tile.active(), Terraria.Tile.halfBrick(), int, Terraria.ID.TileID.Sets.IsBeam, Terraria.WorldGen.IsTreeType(), Terraria.ID.TileID.Sets.NotReallySolid, Terraria.ID.TileID.Sets.Platforms, Terraria.Tile.slope(), Terraria.Main.tile, Terraria.Main.tileNoAttach, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.ID.TileID.Sets.Torches, Terraria.Tile.type, and Terraria.Tile.wall.
Referenced by Terraria.GameContent.SmartCursorHelper.Step_Torch().