Terraria Decompiled: Terraria.GameContent.SmartCursorHelper.Step_PumpkinSeeds
Step_PumpkinSeeds()
static void Terraria.GameContent.SmartCursorHelper.Step_PumpkinSeeds (SmartCursorHelper::SmartCursorUsageInfo providedInfo, ref int focusedX, ref int focusedY) inline static private
Definition at line 1029 of file SmartCursorHelper.cs.
        {
            if (providedInfo.item.createTile == 254 && focusedX == -1 && focusedY == -1)
            {
                SmartCursorHelper._targets.Clear();
                for (int i = providedInfo.reachableStartX; i <= providedInfo.reachableEndX; i++)
                {
                    for (int j = providedInfo.reachableStartY; j <= providedInfo.reachableEndY; j++)
                    {
                        Tile tile = Main.tile[i, j + 1];
                        Tile tile2 = Main.tile[i + 1, j + 1];
                        if ((double)j > Main.worldSurface - 2.0)
{
                            break;
                        }
                        bool flag = true;
                        if (!tile2.active() || !tile.active())
{
                            flag = false;
                        }
                        if (tile2.slope() > 0 || tile.slope() > 0 || tile2.halfBrick() || tile.halfBrick())
{
                            flag = false;
                        }
                        if (tile2.type != 2 && tile2.type != 477 && tile2.type != 109 && tile2.type != 492)
{
                            flag = false;
                        }
                        if (tile.type != 2 && tile.type != 477 && tile.type != 109 && tile.type != 492)
{
                            flag = false;
                        }
                        for (int k = i; k <= i + 1; k++)
{
                            for (int l = j - 1; l <= j; l++)
{
                                Tile tile3 = Main.tile[k, l];
                                if (tile3.active() && (tile3.type < 0 || tile3.type >= TileID.Count || Main.tileSolid[(int)tile3.type] || !WorldGen.CanCutTile(k, l, TileCuttingContext.TilePlacement)))
{
                                    flag = false;
                                }
                            }
                        }
                        if (flag)
{
                            SmartCursorHelper._targets.Add(new Point(i, j));
                        }
                    }
                }
                if (SmartCursorHelper._targets.Count > 0)
                {
                    float num = -1f;
                    Point point = SmartCursorHelper._targets[0];
                    for (int m = 0; m < SmartCursorHelper._targets.Count; m++)
                    {
                        float num2 = Vector2.Distance(new Vector2((float)SmartCursorHelper._targets[m].X, (float)SmartCursorHelper._targets[m].Y) * 16f + Vector2.One * 8f, providedInfo.mouse);
                        if (num == -1f || num2 < num)
{
                            num = num2;
                            point = SmartCursorHelper._targets[m];
                        }
                    }
                    if (Collision.InTileBounds(point.X, point.Y, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY))
                    {
                        focusedX = point.X;
                        focusedY = point.Y;
                    }
                }
                SmartCursorHelper._targets.Clear();
            }
        }
References Terraria.GameContent.SmartCursorHelper._targets, Terraria.Tile.active(), System.Collections.Generic.List< T >.Add(), Terraria.WorldGen.CanCutTile(), System.Collections.Generic.List< T >.Clear(), System.Collections.Generic.List< T >.Count, Microsoft.Xna.Framework.Vector2.Distance(), Terraria.Tile.halfBrick(), int, Terraria.Collision.InTileBounds(), Terraria.Tile.slope(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Tile.type, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.SmartCursorHelper.SmartCursorLookup().