Terraria Decompiled: Terraria.GameContent.SmartCursorHelper.Step_LawnMower
Step_LawnMower()
static void Terraria.GameContent.SmartCursorHelper.Step_LawnMower (SmartCursorHelper::SmartCursorUsageInfo providedInfo, ref int fX, ref int fY) inline static private
Definition at line 2975 of file SmartCursorHelper.cs.
        {
            int reachableStartX = providedInfo.reachableStartX;
            int reachableStartY = providedInfo.reachableStartY;
            int reachableEndX = providedInfo.reachableEndX;
            int reachableEndY = providedInfo.reachableEndY;
            int screenTargetX = providedInfo.screenTargetX;
            int screenTargetY = providedInfo.screenTargetY;
            if (providedInfo.item.type == 4049 && fX == -1 && fY == -1)
            {
                SmartCursorHelper._targets.Clear();
                for (int i = reachableStartX; i <= reachableEndX; i++)
                {
                    for (int j = reachableStartY; j <= reachableEndY; j++)
                    {
                        Tile tile = Main.tile[i, j];
                        if (tile.active() && (tile.type == 2 || tile.type == 109))
{
                            SmartCursorHelper._targets.Add(new Point(i, j));
                        }
                    }
                }
                if (SmartCursorHelper._targets.Count > 0)
                {
                    float num = -1f;
                    Point point = SmartCursorHelper._targets[0];
                    for (int k = 0; k < SmartCursorHelper._targets.Count; k++)
                    {
                        float num2 = Vector2.Distance(new Vector2((float)SmartCursorHelper._targets[k].X, (float)SmartCursorHelper._targets[k].Y) * 16f + Vector2.One * 8f, providedInfo.mouse);
                        if (num == -1f || num2 < num)
{
                            num = num2;
                            point = SmartCursorHelper._targets[k];
                        }
                    }
                    if (Collision.InTileBounds(point.X, point.Y, reachableStartX, reachableStartY, reachableEndX, reachableEndY))
                    {
                        fX = point.X;
                        fY = point.Y;
                    }
                }
                SmartCursorHelper._targets.Clear();
            }
        }
References Terraria.GameContent.SmartCursorHelper._targets, Terraria.Tile.active(), System.Collections.Generic.List< T >.Add(), System.Collections.Generic.List< T >.Clear(), System.Collections.Generic.List< T >.Count, Microsoft.Xna.Framework.Vector2.Distance(), Terraria.Collision.InTileBounds(), Microsoft.Xna.Framework.Vector2.One, Terraria.Main.tile, Terraria.Tile.type, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.SmartCursorHelper.SmartCursorLookup().