Terraria Decompiled: Terraria.GameContent.SmartCursorHelper.Step_ColoredWrenches
Step_ColoredWrenches()
static void Terraria.GameContent.SmartCursorHelper.Step_ColoredWrenches (SmartCursorHelper::SmartCursorUsageInfo providedInfo, ref int focusedX, ref int focusedY) inline static private
Definition at line 1881 of file SmartCursorHelper.cs.
        {
            if ((providedInfo.item.type == 509 || providedInfo.item.type == 850 || providedInfo.item.type == 851 || providedInfo.item.type == 3612) && focusedX == -1 && focusedY == -1)
            {
                SmartCursorHelper._targets.Clear();
                int num = 0;
                if (providedInfo.item.type == 509)
                {
                    num = 1;
                }
                if (providedInfo.item.type == 850)
                {
                    num = 2;
                }
                if (providedInfo.item.type == 851)
                {
                    num = 3;
                }
                if (providedInfo.item.type == 3612)
                {
                    num = 4;
                }
                bool flag = false;
                if (Main.tile[providedInfo.screenTargetX, providedInfo.screenTargetY].wire() && num == 1)
                {
                    flag = true;
                }
                if (Main.tile[providedInfo.screenTargetX, providedInfo.screenTargetY].wire2() && num == 2)
                {
                    flag = true;
                }
                if (Main.tile[providedInfo.screenTargetX, providedInfo.screenTargetY].wire3() && num == 3)
                {
                    flag = true;
                }
                if (Main.tile[providedInfo.screenTargetX, providedInfo.screenTargetY].wire4() && num == 4)
                {
                    flag = true;
                }
                if (!flag)
                {
                    for (int i = providedInfo.reachableStartX; i <= providedInfo.reachableEndX; i++)
                    {
                        for (int j = providedInfo.reachableStartY; j <= providedInfo.reachableEndY; j++)
{
                            Tile tile = Main.tile[i, j];
                            if ((tile.wire() && num == 1) || (tile.wire2() && num == 2) || (tile.wire3() && num == 3) || (tile.wire4() && num == 4))
{
                                if (num == 1)
{
                                    if (!Main.tile[i - 1, j].wire())
{
                                        SmartCursorHelper._targets.Add(new Point(i - 1, j));
                                    }
                                    if (!Main.tile[i + 1, j].wire())
{
                                        SmartCursorHelper._targets.Add(new Point(i + 1, j));
                                    }
                                    if (!Main.tile[i, j - 1].wire())
{
                                        SmartCursorHelper._targets.Add(new Point(i, j - 1));
                                    }
                                    if (!Main.tile[i, j + 1].wire())
{
                                        SmartCursorHelper._targets.Add(new Point(i, j + 1));
                                    }
                                }
                                if (num == 2)
{
                                    if (!Main.tile[i - 1, j].wire2())
{
                                        SmartCursorHelper._targets.Add(new Point(i - 1, j));
                                    }
                                    if (!Main.tile[i + 1, j].wire2())
{
                                        SmartCursorHelper._targets.Add(new Point(i + 1, j));
                                    }
                                    if (!Main.tile[i, j - 1].wire2())
{
                                        SmartCursorHelper._targets.Add(new Point(i, j - 1));
                                    }
                                    if (!Main.tile[i, j + 1].wire2())
{
                                        SmartCursorHelper._targets.Add(new Point(i, j + 1));
                                    }
                                }
                                if (num == 3)
{
                                    if (!Main.tile[i - 1, j].wire3())
{
                                        SmartCursorHelper._targets.Add(new Point(i - 1, j));
                                    }
                                    if (!Main.tile[i + 1, j].wire3())
{
                                        SmartCursorHelper._targets.Add(new Point(i + 1, j));
                                    }
                                    if (!Main.tile[i, j - 1].wire3())
{
                                        SmartCursorHelper._targets.Add(new Point(i, j - 1));
                                    }
                                    if (!Main.tile[i, j + 1].wire3())
{
                                        SmartCursorHelper._targets.Add(new Point(i, j + 1));
                                    }
                                }
                                if (num == 4)
{
                                    if (!Main.tile[i - 1, j].wire4())
{
                                        SmartCursorHelper._targets.Add(new Point(i - 1, j));
                                    }
                                    if (!Main.tile[i + 1, j].wire4())
{
                                        SmartCursorHelper._targets.Add(new Point(i + 1, j));
                                    }
                                    if (!Main.tile[i, j - 1].wire4())
{
                                        SmartCursorHelper._targets.Add(new Point(i, j - 1));
                                    }
                                    if (!Main.tile[i, j + 1].wire4())
{
                                        SmartCursorHelper._targets.Add(new Point(i, j + 1));
                                    }
                                }
                            }
                        }
                    }
                }
                if (SmartCursorHelper._targets.Count > 0)
                {
                    float num2 = -1f;
                    Point point = SmartCursorHelper._targets[0];
                    for (int k = 0; k < SmartCursorHelper._targets.Count; k++)
                    {
                        float num3 = Vector2.Distance(new Vector2((float)SmartCursorHelper._targets[k].X, (float)SmartCursorHelper._targets[k].Y) * 16f + Vector2.One * 8f, providedInfo.mouse);
                        if (num2 == -1f || num3 < num2)
{
                            num2 = num3;
                            point = SmartCursorHelper._targets[k];
                        }
                    }
                    if (Collision.InTileBounds(point.X, point.Y, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY))
                    {
                        focusedX = point.X;
                        focusedY = point.Y;
                    }
                }
                SmartCursorHelper._targets.Clear();
            }
        }
References Terraria.GameContent.SmartCursorHelper._targets, System.Collections.Generic.List< T >.Add(), System.Collections.Generic.List< T >.Clear(), System.Collections.Generic.List< T >.Count, Microsoft.Xna.Framework.Vector2.Distance(), Terraria.Collision.InTileBounds(), Terraria.Main.tile, Terraria.Tile.wire(), Terraria.Tile.wire2(), Terraria.Tile.wire3(), Terraria.Tile.wire4(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.SmartCursorHelper.SmartCursorLookup().