Terraria Decompiled: Terraria.GameContent.SmartCursorHelper.Step_Pickaxe_MineSolids
Step_Pickaxe_MineSolids()
static void Terraria.GameContent.SmartCursorHelper.Step_Pickaxe_MineSolids (Player player, Vector2 position, Vector2 Center, int width, int direction, SmartCursorHelper::SmartCursorUsageInfo providedInfo, List< Point > grappleTargets, ref int focusedX, ref int focusedY) inline static
Definition at line 2425 of file SmartCursorHelper.cs.
        {
            int height = player.height;
            float gravDir = player.gravDir;
            int whoAmI = player.whoAmI;
            if (providedInfo.item.pick > 0 && focusedX == -1 && focusedY == -1)
            {
                if (PlayerInput.UsingGamepad)
                {
                    Vector2 navigatorDirections = PlayerInput.Triggers.Current.GetNavigatorDirections();
                    Vector2 gamepadThumbstickLeft = PlayerInput.GamepadThumbstickLeft;
                    Vector2 gamepadThumbstickRight = PlayerInput.GamepadThumbstickRight;
                    if (navigatorDirections == Vector2.Zero && gamepadThumbstickLeft.Length() < 0.05f && gamepadThumbstickRight.Length() < 0.05f)
                    {
                        providedInfo.mouse = Center + new Vector2((float)(direction * 1000), 0f);
                    }
                }
                Vector2 vector = providedInfo.mouse - Center;
                int num = Math.Sign(vector.X);
                int num2 = Math.Sign(vector.Y);
                if (Math.Abs(vector.X) > Math.Abs(vector.Y) * 3f)
                {
                    num2 = 0;
                    providedInfo.mouse.Y = Center.Y;
                }
                if (Math.Abs(vector.Y) > Math.Abs(vector.X) * 3f)
                {
                    num = 0;
                    providedInfo.mouse.X = Center.X;
                }
                int num3 = (int)Center.X / 16;
                int num4 = (int)Center.Y / 16;
                SmartCursorHelper._points.Clear();
                SmartCursorHelper._endpoints.Clear();
                int num5 = 1;
                if (num2 == -1 && num != 0)
                {
                    num5 = -1;
                }
                int num6 = (int)((position.X + (float)(width / 2) + (float)((width / 2 - 1) * num)) / 16f);
                int num7 = (int)(((double)position.Y + 0.1) / 16.0);
                if (num5 == -1)
                {
                    num7 = (int)((position.Y + (float)height - 1f) / 16f);
                }
                int num8 = width / 16 + ((width % 16 == 0) ? 0 : 1);
                int num9 = height / 16 + ((height % 16 == 0) ? 0 : 1);
                if (num != 0)
                {
                    for (int i = 0; i < num9; i++)
                    {
                        if (Main.tile[num6, num7 + i * num5] != null)
{
                            SmartCursorHelper._points.Add(new Point(num6, num7 + i * num5));
                        }
                    }
                }
                if (num2 != 0)
                {
                    for (int j = 0; j < num8; j++)
                    {
                        if (Main.tile[(int)(position.X / 16f) + j, num7] != null)
{
                            SmartCursorHelper._points.Add(new Point((int)(position.X / 16f) + j, num7));
                        }
                    }
                }
                int num10 = (int)((providedInfo.mouse.X + (float)((width / 2 - 1) * num)) / 16f);
                int num11 = (int)(((double)providedInfo.mouse.Y + 0.1 - (double)(height / 2 + 1)) / 16.0);
                if (num5 == -1)
                {
                    num11 = (int)((providedInfo.mouse.Y + (float)(height / 2) - 1f) / 16f);
                }
                if (gravDir == -1f && num2 == 0)
                {
                    num11++;
                }
                if (gravDir == 1f && num == 0)
                {
                    num11++;
                }
                if (num11 < 10)
                {
                    num11 = 10;
                }
                if (num11 > Main.maxTilesY - 10)
                {
                    num11 = Main.maxTilesY - 10;
                }
                int num12 = width / 16 + ((width % 16 == 0) ? 0 : 1);
                int num13 = height / 16 + ((height % 16 == 0) ? 0 : 1);
                if (WorldGen.InWorld(num10, num11, 40))
                {
                    if (num != 0)
                    {
                        for (int k = 0; k < num13; k++)
{
                            if (Main.tile[num10, num11 + k * num5] != null)
{
                                SmartCursorHelper._endpoints.Add(new Point(num10, num11 + k * num5));
                            }
                        }
                    }
                    if (num2 != 0)
                    {
                        for (int l = 0; l < num12; l++)
{
                            if (Main.tile[(int)((providedInfo.mouse.X - (float)(width / 2)) / 16f) + l, num11] != null)
{
                                SmartCursorHelper._endpoints.Add(new Point((int)((providedInfo.mouse.X - (float)(width / 2)) / 16f) + l, num11));
                            }
                        }
                    }
                }
                SmartCursorHelper._targets.Clear();
                while (SmartCursorHelper._points.Count > 0 && SmartCursorHelper._endpoints.Count > 0)
                {
                    Point point = SmartCursorHelper._points[0];
                    Point point2 = SmartCursorHelper._endpoints[0];
                    Point point3;
                    if (!Collision.HitLine(point.X, point.Y, point2.X, point2.Y, num * (int)gravDir, -num2 * (int)gravDir, grappleTargets, out point3))
                    {
                        SmartCursorHelper._points.Remove(point);
                        SmartCursorHelper._endpoints.Remove(point2);
                    }
                    else
                    {
                        if (point3.X != point2.X || point3.Y != point2.Y)
{
                            SmartCursorHelper._targets.Add(point3);
                        }
                        Tile tile = Main.tile[point3.X, point3.Y];
                        if (!tile.inActive() && tile.active() && Main.tileSolid[(int)tile.type] && !Main.tileSolidTop[(int)tile.type] && !grappleTargets.Contains(point3))
{
                            SmartCursorHelper._targets.Add(point3);
                        }
                        SmartCursorHelper._points.Remove(point);
                        SmartCursorHelper._endpoints.Remove(point2);
                    }
                }
                SmartCursorHelper._toRemove.Clear();
                for (int m = 0; m < SmartCursorHelper._targets.Count; m++)
                {
                    if (!WorldGen.CanKillTile(SmartCursorHelper._targets[m].X, SmartCursorHelper._targets[m].Y))
                    {
                        SmartCursorHelper._toRemove.Add(SmartCursorHelper._targets[m]);
                    }
                }
                for (int n = 0; n < SmartCursorHelper._toRemove.Count; n++)
                {
                    SmartCursorHelper._targets.Remove(SmartCursorHelper._toRemove[n]);
                }
                SmartCursorHelper._toRemove.Clear();
                if (SmartCursorHelper._targets.Count > 0)
                {
                    float num14 = -1f;
                    Point point4 = SmartCursorHelper._targets[0];
                    Vector2 vector2 = Center;
                    if (Main.netMode == 1)
                    {
                        int num15 = 0;
                        int num16 = 0;
                        int num17 = 0;
                        for (int num18 = 0; num18 < whoAmI; num18++)
{
                            Player player2 = Main.player[num18];
                            if (player2.active && !player2.dead && player2.HeldItem.pick > 0 && player2.itemAnimation > 0)
{
                                if (player.Distance(player2.Center) <= 8f)
{
                                    num15++;
                                }
                                if (player.Distance(player2.Center) <= 80f && Math.Abs(player2.Center.Y - Center.Y) <= 12f)
{
                                    num16++;
                                }
                            }
                        }
                        for (int num19 = whoAmI + 1; num19 < 255; num19++)
{
                            Player player3 = Main.player[num19];
                            if (player3.active && !player3.dead && player3.HeldItem.pick > 0 && player3.itemAnimation > 0 && player.Distance(player3.Center) <= 8f)
{
                                num17++;
                            }
                        }
                        if (num15 > 0)
{
                            if (num15 % 2 == 1)
{
                                vector2.X += 12f;
                            }
                            else
{
                                vector2.X -= 12f;
                            }
                            if (num16 % 2 == 1)
{
                                vector2.Y -= 12f;
                            }
                        }
                        if (num17 > 0 && num15 == 0)
{
                            if (num17 % 2 == 1)
{
                                vector2.X -= 12f;
                            }
                            else
{
                                vector2.X += 12f;
                            }
                        }
                    }
                    for (int num20 = 0; num20 < SmartCursorHelper._targets.Count; num20++)
                    {
                        float num21 = Vector2.Distance(new Vector2((float)SmartCursorHelper._targets[num20].X, (float)SmartCursorHelper._targets[num20].Y) * 16f + Vector2.One * 8f, vector2);
                        if (num14 == -1f || num21 < num14)
{
                            num14 = num21;
                            point4 = SmartCursorHelper._targets[num20];
                        }
                    }
                    if (Collision.InTileBounds(point4.X, point4.Y, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY))
                    {
                        focusedX = point4.X;
                        focusedY = point4.Y;
                    }
                }
                SmartCursorHelper._points.Clear();
                SmartCursorHelper._endpoints.Clear();
                SmartCursorHelper._targets.Clear();
            }
        }
References Terraria.GameContent.SmartCursorHelper._endpoints, Terraria.GameContent.SmartCursorHelper._points, Terraria.GameContent.SmartCursorHelper._targets, Terraria.GameContent.SmartCursorHelper._toRemove, System.Math.Abs(), Terraria.Player.active, Terraria.Tile.active(), System.Collections.Generic.List< T >.Add(), Terraria.WorldGen.CanKillTile(), Terraria.Entity.Center, System.Collections.Generic.List< T >.Clear(), System.Collections.Generic.List< T >.Contains(), System.Collections.Generic.List< T >.Count, Terraria.GameInput.TriggersPack.Current, Terraria.Player.dead, Terraria.Entity.Distance(), Microsoft.Xna.Framework.Vector2.Distance(), Terraria.GameInput.PlayerInput.GamepadThumbstickLeft, Terraria.GameInput.PlayerInput.GamepadThumbstickRight, Terraria.GameInput.TriggersSet.GetNavigatorDirections(), Terraria.Player.gravDir, Terraria.Entity.height, Terraria.Player.HeldItem, Terraria.Collision.HitLine(), Terraria.Tile.inActive(), int, Terraria.Collision.InTileBounds(), Terraria.WorldGen.InWorld(), Terraria.Player.itemAnimation, Microsoft.Xna.Framework.Vector2.Length(), Terraria.Main.maxTilesY, Terraria.Main.netMode, Terraria.Item.pick, Terraria.Main.player, System.Collections.Generic.List< T >.Remove(), System.Math.Sign(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.GameInput.PlayerInput.Triggers, Terraria.Tile.type, Terraria.GameInput.PlayerInput.UsingGamepad, Terraria.Entity.whoAmI, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Point.Y, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.Projectile.AI_067_FreakingPirates_TryAssigningHelp(), and Terraria.GameContent.SmartCursorHelper.SmartCursorLookup().