Terraria Decompiled: Terraria.GameContent.SmartCursorHelper.Step_Pigronata
Step_Pigronata()
static void Terraria.GameContent.SmartCursorHelper.Step_Pigronata (SmartCursorHelper::SmartCursorUsageInfo providedInfo, ref int focusedX, ref int focusedY) inline static private
Definition at line 969 of file SmartCursorHelper.cs.
        {
            if (providedInfo.item.createTile == 454 && focusedX == -1 && focusedY == -1)
            {
                SmartCursorHelper._targets.Clear();
                for (int i = providedInfo.reachableStartX; i <= providedInfo.reachableEndX; i++)
                {
                    int num = providedInfo.reachableStartY;
                    while (num <= providedInfo.reachableEndY && (double)num <= Main.worldSurface - 2.0)
                    {
                        bool flag = true;
                        for (int j = i - 2; j <= i + 1; j++)
{
                            for (int k = num - 1; k <= num + 2; k++)
{
                                Tile tile = Main.tile[j, k];
                                if (k == num - 1)
{
                                    if (!WorldGen.SolidTile(tile))
{
                                        flag = false;
                                    }
                                }
                                else if (tile.active() && (!Main.tileCut[(int)tile.type] || tile.type == 454))
{
                                    flag = false;
                                }
                            }
                        }
                        if (flag)
{
                            SmartCursorHelper._targets.Add(new Point(i, num));
                        }
                        num++;
                    }
                }
                if (SmartCursorHelper._targets.Count > 0)
                {
                    float num2 = -1f;
                    Point point = SmartCursorHelper._targets[0];
                    for (int l = 0; l < SmartCursorHelper._targets.Count; l++)
                    {
                        float num3 = Vector2.Distance(new Vector2((float)SmartCursorHelper._targets[l].X, (float)SmartCursorHelper._targets[l].Y) * 16f + Vector2.One * 8f, providedInfo.mouse);
                        if (num2 == -1f || num3 < num2)
{
                            num2 = num3;
                            point = SmartCursorHelper._targets[l];
                        }
                    }
                    if (Collision.InTileBounds(point.X, point.Y, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY))
                    {
                        focusedX = point.X;
                        focusedY = point.Y;
                    }
                }
                SmartCursorHelper._targets.Clear();
            }
        }
References Terraria.GameContent.SmartCursorHelper._targets, Terraria.Tile.active(), System.Collections.Generic.List< T >.Add(), System.Collections.Generic.List< T >.Clear(), System.Collections.Generic.List< T >.Count, Microsoft.Xna.Framework.Vector2.Distance(), int, Terraria.Collision.InTileBounds(), Terraria.WorldGen.SolidTile(), Terraria.Main.tile, Terraria.Main.tileCut, Terraria.Tile.type, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.SmartCursorHelper.SmartCursorLookup().