Terraria Decompiled: Terraria.GameContent.SmartCursorHelper.SmartCursorLookup
SmartCursorLookup()
static void Terraria.GameContent.SmartCursorHelper.SmartCursorLookup (Player player) inline static
Definition at line 16 of file SmartCursorHelper.cs.
        {
            Main.SmartCursorShowing = false;
            if (!player.controlUseItem || !Main.SmartCursorIsUsed)
            {
                SmartCursorHelper._lockedDesiredDirection = null;
                SmartCursorHelper._lockedContinuityCoords = null;
            }
            if (!Main.SmartCursorIsUsed)
            {
                return;
            }
            SmartCursorHelper.SmartCursorUsageInfo smartCursorUsageInfo = new SmartCursorHelper.SmartCursorUsageInfo
            {
                player = player,
                item = player.inventory[player.selectedItem],
                mouse = Main.MouseWorld,
                position = player.position,
                Center = player.Center
            };
            float gravDir = player.gravDir;
            int tileTargetX = Player.tileTargetX;
            int tileTargetY = Player.tileTargetY;
            int tileRangeX = Player.tileRangeX;
            int tileRangeY = Player.tileRangeY;
            smartCursorUsageInfo.screenTargetX = Utils.Clamp<int>(tileTargetX, 10, Main.maxTilesX - 10);
            smartCursorUsageInfo.screenTargetY = Utils.Clamp<int>(tileTargetY, 10, Main.maxTilesY - 10);
            if (Main.tile[smartCursorUsageInfo.screenTargetX, smartCursorUsageInfo.screenTargetY] == null)
            {
                return;
            }
            bool flag = SmartCursorHelper.IsHoveringOverAnInteractableTileThatBlocksSmartCursor(smartCursorUsageInfo);
            SmartCursorHelper.TryFindingPaintInplayerInventory(smartCursorUsageInfo, out smartCursorUsageInfo.paintLookup, out smartCursorUsageInfo.paintCoatingLookup);
            int num = smartCursorUsageInfo.item.tileBoost;
            if (smartCursorUsageInfo.item.createWall > 0 || smartCursorUsageInfo.item.createTile > 0 || smartCursorUsageInfo.item.tileWand > 0)
            {
                num += player.blockRange;
            }
            TileReachCheckSettings.Simple.GetTileRegion(player, out smartCursorUsageInfo.reachableStartX, out smartCursorUsageInfo.reachableStartY, out smartCursorUsageInfo.reachableEndX, out smartCursorUsageInfo.reachableEndY, num);
            smartCursorUsageInfo.reachableStartX = Utils.Clamp<int>(smartCursorUsageInfo.reachableStartX, 10, Main.maxTilesX - 10);
            smartCursorUsageInfo.reachableEndX = Utils.Clamp<int>(smartCursorUsageInfo.reachableEndX, 10, Main.maxTilesX - 10);
            smartCursorUsageInfo.reachableStartY = Utils.Clamp<int>(smartCursorUsageInfo.reachableStartY, 10, Main.maxTilesY - 10);
            smartCursorUsageInfo.reachableEndY = Utils.Clamp<int>(smartCursorUsageInfo.reachableEndY, 10, Main.maxTilesY - 10);
            if (flag && smartCursorUsageInfo.screenTargetX >= smartCursorUsageInfo.reachableStartX && smartCursorUsageInfo.screenTargetX <= smartCursorUsageInfo.reachableEndX && smartCursorUsageInfo.screenTargetY >= smartCursorUsageInfo.reachableStartY && smartCursorUsageInfo.screenTargetY <= smartCursorUsageInfo.reachableEndY)
            {
                return;
            }
            SmartCursorHelper._grappleTargets.Clear();
            int[] grappling = player.grappling;
            int grapCount = player.grapCount;
            for (int i = 0; i < grapCount; i++)
            {
                Projectile projectile = Main.projectile[grappling[i]];
                int num2 = (int)projectile.Center.X / 16;
                int num3 = (int)projectile.Center.Y / 16;
                SmartCursorHelper._grappleTargets.Add(new Point(num2, num3));
            }
            int num4 = -1;
            int num5 = -1;
            if (!Player.SmartCursorSettings.SmartAxeAfterPickaxe)
            {
                SmartCursorHelper.Step_Axe(smartCursorUsageInfo, ref num4, ref num5);
            }
            SmartCursorHelper.Step_ForceCursorToAnyMinableThing(smartCursorUsageInfo, ref num4, ref num5);
            SmartCursorHelper.Step_Pickaxe_MineShinies(smartCursorUsageInfo, ref num4, ref num5);
            SmartCursorHelper.Step_Pickaxe_MineSolids(player, player.position, player.Center, player.width, player.direction, smartCursorUsageInfo, SmartCursorHelper._grappleTargets, ref num4, ref num5);
            if (Player.SmartCursorSettings.SmartAxeAfterPickaxe)
            {
                SmartCursorHelper.Step_Axe(smartCursorUsageInfo, ref num4, ref num5);
            }
            SmartCursorHelper.Step_ColoredWrenches(smartCursorUsageInfo, ref num4, ref num5);
            SmartCursorHelper.Step_MulticolorWrench(smartCursorUsageInfo, ref num4, ref num5);
            SmartCursorHelper.Step_Hammers(smartCursorUsageInfo, ref num4, ref num5);
            SmartCursorHelper.Step_ActuationRod(smartCursorUsageInfo, ref num4, ref num5);
            SmartCursorHelper.Step_WireCutter(smartCursorUsageInfo, ref num4, ref num5);
            SmartCursorHelper.Step_Platforms(smartCursorUsageInfo, ref num4, ref num5);
            SmartCursorHelper.Step_MinecartTracks(smartCursorUsageInfo, ref num4, ref num5);
            SmartCursorHelper.Step_Walls(smartCursorUsageInfo, ref num4, ref num5);
            SmartCursorHelper.Step_PumpkinSeeds(smartCursorUsageInfo, ref num4, ref num5);
            SmartCursorHelper.Step_GrassSeeds(smartCursorUsageInfo, ref num4, ref num5);
            SmartCursorHelper.Step_Moss(smartCursorUsageInfo, ref num4, ref num5);
            SmartCursorHelper.Step_Pigronata(smartCursorUsageInfo, ref num4, ref num5);
            SmartCursorHelper.Step_Boulders(smartCursorUsageInfo, ref num4, ref num5);
            SmartCursorHelper.Step_Torch(smartCursorUsageInfo, ref num4, ref num5);
            SmartCursorHelper.Step_LawnMower(smartCursorUsageInfo, ref num4, ref num5);
            SmartCursorHelper.Step_BlocksFilling(smartCursorUsageInfo, ref num4, ref num5);
            SmartCursorHelper.Step_BlocksLines(smartCursorUsageInfo, ref num4, ref num5);
            SmartCursorHelper.Step_PaintRoller(smartCursorUsageInfo, ref num4, ref num5);
            SmartCursorHelper.Step_PaintBrush(smartCursorUsageInfo, ref num4, ref num5);
            SmartCursorHelper.Step_PaintScrapper(smartCursorUsageInfo, ref num4, ref num5);
            SmartCursorHelper.Step_Acorns(smartCursorUsageInfo, ref num4, ref num5);
            SmartCursorHelper.Step_GemCorns(smartCursorUsageInfo, ref num4, ref num5);
            SmartCursorHelper.Step_EmptyBuckets(smartCursorUsageInfo, ref num4, ref num5);
            SmartCursorHelper.Step_Actuators(smartCursorUsageInfo, ref num4, ref num5);
            SmartCursorHelper.Step_AlchemySeeds(smartCursorUsageInfo, ref num4, ref num5);
            SmartCursorHelper.Step_PlanterBox(smartCursorUsageInfo, ref num4, ref num5);
            SmartCursorHelper.Step_ClayPots(smartCursorUsageInfo, ref num4, ref num5);
            SmartCursorHelper.Step_StaffOfRegrowth(smartCursorUsageInfo, ref num4, ref num5);
            if (num4 != -1 && num5 != -1)
            {
                Main.SmartCursorX = (Player.tileTargetX = num4);
                Main.SmartCursorY = (Player.tileTargetY = num5);
                Main.SmartCursorShowing = true;
            }
            SmartCursorHelper._grappleTargets.Clear();
        }
References Terraria.GameContent.SmartCursorHelper._grappleTargets, System.Collections.Generic.List< T >.Add(), Terraria.Player.blockRange, Terraria.Entity.Center, Terraria.Utils.Clamp(), System.Collections.Generic.List< T >.Clear(), Terraria.Player.controlUseItem, Terraria.Item.createTile, Terraria.Item.createWall, Terraria.Entity.direction, Terraria.DataStructures.TileReachCheckSettings.GetTileRegion(), Terraria.Player.grapCount, Terraria.Player.grappling, Terraria.Player.gravDir, int, Terraria.Player.inventory, Terraria.GameContent.SmartCursorHelper.IsHoveringOverAnInteractableTileThatBlocksSmartCursor(), System.item, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.item, Terraria.Main.MouseWorld, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.paintCoatingLookup, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.paintLookup, Terraria.Entity.position, Terraria.Main.projectile, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.reachableEndX, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.reachableEndY, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.reachableStartX, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.reachableStartY, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.screenTargetX, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.screenTargetY, Terraria.Player.selectedItem, Terraria.DataStructures.TileReachCheckSettings.Simple, Terraria.Player.SmartCursorSettings.SmartAxeAfterPickaxe, Terraria.Main.SmartCursorIsUsed, Terraria.GameContent.SmartCursorHelper.Step_Acorns(), Terraria.GameContent.SmartCursorHelper.Step_ActuationRod(), Terraria.GameContent.SmartCursorHelper.Step_Actuators(), Terraria.GameContent.SmartCursorHelper.Step_AlchemySeeds(), Terraria.GameContent.SmartCursorHelper.Step_Axe(), Terraria.GameContent.SmartCursorHelper.Step_BlocksFilling(), Terraria.GameContent.SmartCursorHelper.Step_BlocksLines(), Terraria.GameContent.SmartCursorHelper.Step_Boulders(), Terraria.GameContent.SmartCursorHelper.Step_ClayPots(), Terraria.GameContent.SmartCursorHelper.Step_ColoredWrenches(), Terraria.GameContent.SmartCursorHelper.Step_EmptyBuckets(), Terraria.GameContent.SmartCursorHelper.Step_ForceCursorToAnyMinableThing(), Terraria.GameContent.SmartCursorHelper.Step_GemCorns(), Terraria.GameContent.SmartCursorHelper.Step_GrassSeeds(), Terraria.GameContent.SmartCursorHelper.Step_Hammers(), Terraria.GameContent.SmartCursorHelper.Step_LawnMower(), Terraria.GameContent.SmartCursorHelper.Step_MinecartTracks(), Terraria.GameContent.SmartCursorHelper.Step_Moss(), Terraria.GameContent.SmartCursorHelper.Step_MulticolorWrench(), Terraria.GameContent.SmartCursorHelper.Step_PaintBrush(), Terraria.GameContent.SmartCursorHelper.Step_PaintRoller(), Terraria.GameContent.SmartCursorHelper.Step_PaintScrapper(), Terraria.GameContent.SmartCursorHelper.Step_Pickaxe_MineShinies(), Terraria.GameContent.SmartCursorHelper.Step_Pickaxe_MineSolids(), Terraria.GameContent.SmartCursorHelper.Step_Pigronata(), Terraria.GameContent.SmartCursorHelper.Step_PlanterBox(), Terraria.GameContent.SmartCursorHelper.Step_Platforms(), Terraria.GameContent.SmartCursorHelper.Step_PumpkinSeeds(), Terraria.GameContent.SmartCursorHelper.Step_StaffOfRegrowth(), Terraria.GameContent.SmartCursorHelper.Step_Torch(), Terraria.GameContent.SmartCursorHelper.Step_Walls(), Terraria.GameContent.SmartCursorHelper.Step_WireCutter(), Terraria.Main.tile, Terraria.Item.tileBoost, Terraria.Player.tileRangeX, Terraria.Player.tileRangeY, Terraria.Player.tileTargetX, Terraria.Player.tileTargetY, Terraria.Item.tileWand, Terraria.GameContent.SmartCursorHelper.TryFindingPaintInplayerInventory(), Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Player.Update().