Terraria Decompiled: System.IO.StringWriter.ToString
ToString()
override string System.IO.StringWriter.ToString () inline
Definition at line 190 of file StringWriter.cs.
        {
            return this._sb.ToString();
        }
References System.IO.StringWriter._sb, and System.Text.StringBuilder.ToString().
Referenced by Newtonsoft.Json.Linq.JRaw.Create(), Newtonsoft.Json.Linq.JsonPath.BooleanQueryExpression.EqualsWithStringCoercion(), Newtonsoft.Json.Serialization.TraceJsonReader.GetDeserializedJsonMessage(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.GetPropertyName(), Newtonsoft.Json.Serialization.TraceJsonWriter.GetSerializedJsonMessage(), Newtonsoft.Json.JsonConvert.SerializeObjectInternal(), Newtonsoft.Json.Utilities.JavaScriptUtils.ToEscapedJavaScriptString(), Newtonsoft.Json.Schema.JsonSchema.ToString(), Newtonsoft.Json.JsonConvert.ToString(), Newtonsoft.Json.JsonConvert.ToString(), Newtonsoft.Json.Linq.JToken.ToString(), and Newtonsoft.Json.JsonValidatingReader.WriteToken().