Terraria Decompiled: Microsoft.Xna.Framework.Graphics.TextureCube.DDSFromStreamEXT
DDSFromStreamEXT()
static TextureCube Microsoft.Xna.Framework.Graphics.TextureCube.DDSFromStreamEXT (GraphicsDevice graphicsDevice, Stream stream) inline static
Definition at line 194 of file TextureCube.cs.
        {
            TextureCube textureCube;
            using (BinaryReader binaryReader = new BinaryReader(stream))
            {
                SurfaceFormat surfaceFormat;
                int num;
                int num2;
                int num3;
                bool flag;
                Texture.ParseDDS(binaryReader, out surfaceFormat, out num, out num2, out num3, out flag);
                if (!flag)
                {
                    throw new FormatException("This file does not contain cube data!");
                }
                textureCube = new TextureCube(graphicsDevice, num, num3 > 1, surfaceFormat);
                byte[] array = null;
                if (stream is MemoryStream && ((MemoryStream)stream).TryGetBuffer(out array))
                {
                    for (int i = 0; i < 6; i++)
                    {
                        for (int j = 0; j < num3; j++)
{
                            int num4 = Texture.CalculateDDSLevelSize(num >> j, num >> j, surfaceFormat);
                            textureCube.SetData<byte>((CubeMapFace)i, j, null, array, (int)stream.Seek(0L, SeekOrigin.Current), num4);
                            stream.Seek((long)num4, SeekOrigin.Current);
                        }
                    }
                }
                else
                {
                    for (int k = 0; k < 6; k++)
                    {
                        for (int l = 0; l < num3; l++)
{
                            array = binaryReader.ReadBytes(Texture.CalculateDDSLevelSize(num >> l, num >> l, surfaceFormat));
                            textureCube.SetData<byte>((CubeMapFace)k, l, null, array, 0, array.Length);
                        }
                    }
                }
            }
            return textureCube;
        }
References System.array, Microsoft.Xna.Framework.Graphics.Texture.CalculateDDSLevelSize(), Microsoft.Xna.Framework.Graphics.GraphicsResource.graphicsDevice, System.L, Microsoft.Xna.Framework.Graphics.Texture.ParseDDS(), System.IO.BinaryReader.ReadBytes(), System.IO.MemoryStream.Seek(), and Microsoft.Xna.Framework.Graphics.TextureCube.
Referenced by Microsoft.Xna.Framework.Content.ContentManager.ReadAsset< T >().