Terraria Decompiled: System.Buffers.StandardFormat.ParseHelper
ParseHelper()
static unsafe bool System.Buffers.StandardFormat.ParseHelper (ReadOnlySpan< char > format, out StandardFormat standardFormat, bool throws = false) inline static private
Definition at line 94 of file StandardFormat.cs.
        {
            standardFormat = default(StandardFormat);
            if (format.Length == 0)
            {
                return true;
            }
            char c = (char)(*format[0]);
            byte b;
            if (format.Length == 1)
            {
                b = byte.MaxValue;
            }
            else
            {
                uint num = 0U;
                int i = 1;
                while (i < format.Length)
                {
                    uint num2 = (uint)(*format[i] - 48);
                    if (num2 > 9U)
                    {
                        if (!throws)
{
                            return false;
                        }
                        throw new FormatException(SR.Format("Characters following the format symbol must be a number of {0} or less.", 99));
                    }
                    else
                    {
                        num = num * 10U + num2;
                        if (num > 99U)
{
                            if (!throws)
{
                                return false;
                            }
                            throw new FormatException(SR.Format("Precision cannot be larger than {0}.", 99));
                        }
                        else
{
                            i++;
                        }
                    }
                }
                b = (byte)num;
            }
            standardFormat = new StandardFormat(c, b);
            return true;
        }
References SR.Format(), System.format, System.Buffers.StandardFormat.StandardFormat(), and System.U.
Referenced by System.Buffers.StandardFormat.Parse(), and System.Buffers.StandardFormat.TryParse().