Terraria Decompiled: Mono.Xml.SmallXmlParser.ReadUntil
ReadUntil()
string Mono.Xml.SmallXmlParser.ReadUntil (char until, bool handleReferences) inline private
Definition at line 163 of file SmallXmlParser.cs.
        {
            while (this.Peek() >= 0)
            {
                char c = (char)this.Read();
                if (c == until)
                {
                    string text = this.buffer.ToString();
                    this.buffer.Length = 0;
                    return text;
                }
                if (handleReferences && c == '&')
                {
                    this.ReadReference();
                }
                else
                {
                    this.buffer.Append(c);
                }
            }
            throw this.UnexpectedEndError();
        }
References System.Text.StringBuilder.Append(), Mono.Xml.SmallXmlParser.buffer, Mono.Xml.SmallXmlParser.Peek(), Mono.Xml.SmallXmlParser.Read(), Mono.Xml.SmallXmlParser.ReadReference(), System.text, System.Text.StringBuilder.ToString(), and Mono.Xml.SmallXmlParser.UnexpectedEndError().
Referenced by Mono.Xml.SmallXmlParser.ReadAttribute(), and Mono.Xml.SmallXmlParser.ReadContent().