Terraria Decompiled: Mono.Xml.SmallXmlParser.ReadContent
ReadContent()
void Mono.Xml.SmallXmlParser.ReadContent () inline
Definition at line 252 of file SmallXmlParser.cs.
        {
            if (this.IsWhitespace(this.Peek()))
            {
                if (this.buffer.Length == 0)
                {
                    this.isWhitespace = true;
                }
                this.HandleWhitespaces();
            }
            if (this.Peek() != 60)
            {
                this.ReadCharacters();
                return;
            }
            this.Read();
            int num = this.Peek();
            if (num != 33)
            {
                if (num != 47)
                {
                    string text;
                    if (num != 63)
                    {
                        this.HandleBufferedContent();
                        text = this.ReadName();
                        while (this.Peek() != 62 && this.Peek() != 47)
{
                            this.ReadAttribute(this.attributes);
                        }
                        this.handler.OnStartElement(text, this.attributes);
                        this.attributes.Clear();
                        this.SkipWhitespaces();
                        if (this.Peek() == 47)
{
                            this.Read();
                            this.handler.OnEndElement(text);
                        }
                        else
{
                            this.elementNames.Push(text);
                            this.xmlSpaces.Push(this.xmlSpace);
                        }
                        this.Expect(62);
                        return;
                    }
                    this.HandleBufferedContent();
                    this.Read();
                    text = this.ReadName();
                    this.SkipWhitespaces();
                    string text2 = string.Empty;
                    if (this.Peek() != 63)
                    {
                        for (;;)
{
                            text2 += this.ReadUntil('?', false);
                            if (this.Peek() == 62)
{
                                break;
                            }
                            text2 += "?";
                        }
                    }
                    this.handler.OnProcessingInstruction(text, text2);
                    this.Expect(62);
                    return;
                }
                else
                {
                    this.HandleBufferedContent();
                    if (this.elementNames.Count == 0)
                    {
                        throw this.UnexpectedEndError();
                    }
                    this.Read();
                    string text = this.ReadName();
                    this.SkipWhitespaces();
                    string text3 = (string)this.elementNames.Pop();
                    this.xmlSpaces.Pop();
                    if (this.xmlSpaces.Count > 0)
                    {
                        this.xmlSpace = (string)this.xmlSpaces.Peek();
                    }
                    else
                    {
                        this.xmlSpace = null;
                    }
                    if (text != text3)
                    {
                        throw this.Error(string.Format("End tag mismatch: expected {0} but found {1}", text3, text));
                    }
                    this.handler.OnEndElement(text);
                    this.Expect(62);
                    return;
                }
            }
            else
            {
                this.Read();
                if (this.Peek() == 91)
                {
                    this.Read();
                    if (this.ReadName() != "CDATA")
                    {
                        throw this.Error("Invalid declaration markup");
                    }
                    this.Expect(91);
                    this.ReadCDATASection();
                    return;
                }
                else
                {
                    if (this.Peek() == 45)
                    {
                        this.ReadComment();
                        return;
                    }
                    if (this.ReadName() != "DOCTYPE")
                    {
                        throw this.Error("Invalid declaration markup.");
                    }
                    throw this.Error("This parser does not support document type.");
                }
            }
        }
References Mono.Xml.SmallXmlParser.attributes, Mono.Xml.SmallXmlParser.buffer, System.Collections.Generic.Stack< T >.Count, Mono.Xml.SmallXmlParser.elementNames, System.Error, Mono.Xml.SmallXmlParser.Expect(), System.Globalization.Format, Mono.Xml.SmallXmlParser.HandleBufferedContent(), Mono.Xml.SmallXmlParser.handler, Mono.Xml.SmallXmlParser.HandleWhitespaces(), Mono.Xml.SmallXmlParser.IsWhitespace(), System.Text.StringBuilder.Length, Mono.Xml.SmallXmlParser.Peek(), System.Collections.Generic.Stack< T >.Peek(), System.Collections.Generic.Stack< T >.Pop(), System.Collections.Generic.Stack< T >.Push(), Mono.Xml.SmallXmlParser.Read(), Mono.Xml.SmallXmlParser.ReadAttribute(), Mono.Xml.SmallXmlParser.ReadCDATASection(), Mono.Xml.SmallXmlParser.ReadCharacters(), Mono.Xml.SmallXmlParser.ReadComment(), Mono.Xml.SmallXmlParser.ReadName(), Mono.Xml.SmallXmlParser.ReadUntil(), Mono.Xml.SmallXmlParser.SkipWhitespaces(), System.text, Mono.Xml.SmallXmlParser.UnexpectedEndError(), Mono.Xml.SmallXmlParser.xmlSpace, and Mono.Xml.SmallXmlParser.xmlSpaces.
Referenced by Mono.Xml.SmallXmlParser.Parse().