Terraria Decompiled: Mono.Xml.SmallXmlParser.ReadReference
ReadReference()
void Mono.Xml.SmallXmlParser.ReadReference () inline private
Definition at line 425 of file SmallXmlParser.cs.
        {
            if (this.Peek() == 35)
            {
                this.Read();
                this.ReadCharacterReference();
                return;
            }
            string text = this.ReadName();
            this.Expect(59);
            if (text == "amp")
            {
                this.buffer.Append('&');
                return;
            }
            if (text == "quot")
            {
                this.buffer.Append('"');
                return;
            }
            if (text == "apos")
            {
                this.buffer.Append('\'');
                return;
            }
            if (text == "lt")
            {
                this.buffer.Append('<');
                return;
            }
            if (!(text == "gt"))
            {
                throw this.Error("General non-predefined entity reference is not supported in this parser.");
            }
            this.buffer.Append('>');
        }
References System.Text.StringBuilder.Append(), Mono.Xml.SmallXmlParser.buffer, System.Error, Mono.Xml.SmallXmlParser.Expect(), Mono.Xml.SmallXmlParser.Peek(), Mono.Xml.SmallXmlParser.Read(), Mono.Xml.SmallXmlParser.ReadCharacterReference(), Mono.Xml.SmallXmlParser.ReadName(), and System.text.
Referenced by Mono.Xml.SmallXmlParser.ReadCharacters(), and Mono.Xml.SmallXmlParser.ReadUntil().