Terraria Decompiled: Mono.Xml.SmallXmlParser.ReadName
ReadName()
string Mono.Xml.SmallXmlParser.ReadName () inline
Definition at line 187 of file SmallXmlParser.cs.
        {
            int num = 0;
            if (this.Peek() < 0 || !this.IsNameChar((char)this.Peek(), true))
            {
                throw this.Error("XML name start character is expected.");
            }
            for (int i = this.Peek(); i >= 0; i = this.Peek())
            {
                char c = (char)i;
                if (!this.IsNameChar(c, false))
                {
                    break;
                }
                if (num == this.nameBuffer.Length)
                {
                    char[] array = new char[num * 2];
                    Array.Copy(this.nameBuffer, array, num);
                    this.nameBuffer = array;
                }
                this.nameBuffer[num++] = c;
                this.Read();
            }
            if (num == 0)
            {
                throw this.Error("Valid XML name is expected.");
            }
            return new string(this.nameBuffer, 0, num);
        }
References System.array, System.Array.Copy(), System.Error, Mono.Xml.SmallXmlParser.IsNameChar(), Mono.Xml.SmallXmlParser.nameBuffer, Mono.Xml.SmallXmlParser.Peek(), and Mono.Xml.SmallXmlParser.Read().
Referenced by Mono.Xml.SmallXmlParser.ReadAttribute(), Mono.Xml.SmallXmlParser.ReadContent(), and Mono.Xml.SmallXmlParser.ReadReference().