Terraria Decompiled: Mono.Xml.SmallXmlParser.ReadCharacters
ReadCharacters()
void Mono.Xml.SmallXmlParser.ReadCharacters () inline private
Definition at line 398 of file SmallXmlParser.cs.
        {
            this.isWhitespace = false;
            for (;;)
            {
                int num = this.Peek();
                if (num == -1)
                {
                    break;
                }
                if (num != 38)
                {
                    if (num == 60)
                    {
                        return;
                    }
                    this.buffer.Append((char)this.Read());
                }
                else
                {
                    this.Read();
                    this.ReadReference();
                }
            }
        }
References System.Text.StringBuilder.Append(), Mono.Xml.SmallXmlParser.buffer, Mono.Xml.SmallXmlParser.Peek(), Mono.Xml.SmallXmlParser.Read(), and Mono.Xml.SmallXmlParser.ReadReference().
Referenced by Mono.Xml.SmallXmlParser.ReadContent().