Terraria Decompiled: Mono.Xml.SmallXmlParser.HandleBufferedContent
HandleBufferedContent()
void Mono.Xml.SmallXmlParser.HandleBufferedContent () inline private
Definition at line 379 of file SmallXmlParser.cs.
        {
            if (this.buffer.Length == 0)
            {
                return;
            }
            if (this.isWhitespace)
            {
                this.handler.OnIgnorableWhitespace(this.buffer.ToString());
            }
            else
            {
                this.handler.OnChars(this.buffer.ToString());
            }
            this.buffer.Length = 0;
            this.isWhitespace = false;
        }
References Mono.Xml.SmallXmlParser.buffer, Mono.Xml.SmallXmlParser.handler, Mono.Xml.SmallXmlParser.isWhitespace, System.Text.StringBuilder.Length, and System.Text.StringBuilder.ToString().
Referenced by Mono.Xml.SmallXmlParser.Parse(), and Mono.Xml.SmallXmlParser.ReadContent().