Terraria Decompiled: Mono.Xml.SmallXmlParser.ReadAttribute
ReadAttribute()
void Mono.Xml.SmallXmlParser.ReadAttribute (SmallXmlParser::AttrListImpl a) inline private
Definition at line 504 of file SmallXmlParser.cs.
        {
            this.SkipWhitespaces(true);
            if (this.Peek() == 47 || this.Peek() == 62)
            {
                return;
            }
            string text = this.ReadName();
            this.SkipWhitespaces();
            this.Expect(61);
            this.SkipWhitespaces();
            int num = this.Read();
            string text2;
            if (num != 34)
            {
                if (num != 39)
                {
                    throw this.Error("Invalid attribute value markup.");
                }
                text2 = this.ReadUntil('\'', true);
            }
            else
            {
                text2 = this.ReadUntil('"', true);
            }
            if (text == "xml:space")
            {
                this.xmlSpace = text2;
            }
            a.Add(text, text2);
        }
References System.Error, Mono.Xml.SmallXmlParser.Expect(), Mono.Xml.SmallXmlParser.Peek(), Mono.Xml.SmallXmlParser.Read(), Mono.Xml.SmallXmlParser.ReadName(), Mono.Xml.SmallXmlParser.ReadUntil(), Mono.Xml.SmallXmlParser.SkipWhitespaces(), and System.text.
Referenced by Mono.Xml.SmallXmlParser.ReadContent().