Terraria Decompiled: Mono.Xml.SmallXmlParser.UnexpectedEndError
UnexpectedEndError()
Exception Mono.Xml.SmallXmlParser.UnexpectedEndError () inline private
Definition at line 25 of file SmallXmlParser.cs.
        {
            string[] array = new string[this.elementNames.Count];
            this.elementNames.CopyTo(array, 0);
            return this.Error(string.Format("Unexpected end of stream. Element stack content is {0}", string.Join(",", array)));
        }
References System.array, System.Collections.Generic.Stack< T >.CopyTo(), System.Collections.Generic.Stack< T >.Count, Mono.Xml.SmallXmlParser.elementNames, System.Error, and System.Globalization.Format.
Referenced by Mono.Xml.SmallXmlParser.Expect(), Mono.Xml.SmallXmlParser.ReadCDATASection(), Mono.Xml.SmallXmlParser.ReadContent(), and Mono.Xml.SmallXmlParser.ReadUntil().