Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.DungeonData.CanGenerateFeatureAt
CanGenerateFeatureAt()
bool Terraria.GameContent.Generation.Dungeon.DungeonData.CanGenerateFeatureAt (IDungeonFeature feature, int x, int y) inline
Definition at line 78 of file DungeonData.cs.
        {
            if (!WorldGen.InWorld(x, y, 5))
            {
                return false;
            }
            if (Main.tile[x, y].wall == 350)
            {
                return false;
            }
            if (this.dungeonEntrance.Bounds.Contains(x, y) && !this.dungeonEntrance.CanGenerateFeatureAt(this, feature, x, y))
            {
                return false;
            }
            for (int i = 0; i < this.protectedDungeonBounds.Count; i++)
            {
                if (this.protectedDungeonBounds[i].Contains(x, y))
                {
                    return false;
                }
            }
            for (int j = 0; j < this.dungeonFeatures.Count; j++)
            {
                IDungeonFeature dungeonFeature = this.dungeonFeatures[j];
                if (dungeonFeature is DungeonFeature)
                {
                    DungeonFeature dungeonFeature2 = (DungeonFeature)dungeonFeature;
                    if (dungeonFeature2.generated && dungeonFeature2.Bounds.Contains(x, y) && !dungeonFeature2.CanGenerateFeatureAt(this, feature, x, y))
                    {
                        return false;
                    }
                }
            }
            for (int k = 0; k < this.dungeonRooms.Count; k++)
            {
                DungeonRoom dungeonRoom = this.dungeonRooms[k];
                if (dungeonRoom.generated && dungeonRoom.OuterBounds.Contains(x, y) && !dungeonRoom.CanGenerateFeatureAt(this, feature, x, y))
                {
                    return false;
                }
            }
            return true;
        }
References Terraria.GameContent.Generation.Dungeon.Entrances.DungeonEntrance.Bounds, Terraria.GameContent.Generation.Dungeon.Features.DungeonFeature.Bounds, Terraria.GameContent.Generation.Dungeon.Features.DungeonFeature.CanGenerateFeatureAt(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.CanGenerateFeatureAt(), Microsoft.Xna.Framework.Contains, Terraria.GameContent.Generation.Dungeon.DungeonBounds.Contains(), System.Collections.Generic.List< T >.Count, Terraria.GameContent.Generation.Dungeon.DungeonData.dungeonEntrance, Terraria.GameContent.Generation.Dungeon.DungeonData.dungeonFeatures, Terraria.GameContent.Generation.Dungeon.DungeonData.dungeonRooms, Terraria.GameContent.Generation.Dungeon.Features.DungeonFeature.generated, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.generated, Terraria.WorldGen.InWorld(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.OuterBounds, Terraria.GameContent.Generation.Dungeon.DungeonData.protectedDungeonBounds, Terraria.Main.tile, and Terraria.Tile.wall.
Referenced by Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalBanners.Banners(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalBookshelves.Bookshelves(), Terraria.GameContent.Generation.Dungeon.DungeonData.CanGenerateFeatureInArea(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalGroundFurniture.GroundFurniture_ActuallyGenerateFurniture(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalLights.Lights(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalSpikes.Spikes(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalWallVariants.SpreadWallDungeon(), and Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalTraps.Traps().