Terraria Decompiled: Terraria.GameContent.Biomes.Desert.PitEntrance.PlaceAt
PlaceAt()
static void Terraria.GameContent.Biomes.Desert.PitEntrance.PlaceAt (DesertDescription description, Point position, int holeRadius, GenerationProgress progress, float progressMin, float progressMax) inline static private
Definition at line 20 of file PitEntrance.cs.
        {
            int num = holeRadius + 3;
            int num2 = num + holeRadius + 3;
            for (int i = -holeRadius - 3; i < holeRadius + 3; i++)
            {
                progress.Set((double)((float)(i + num) / (float)num2), (double)progressMin, (double)progressMax);
                for (int j = (int)description.Surface[i + position.X]; j <= description.Hive.Top + 10; j++)
                {
                    double num3 = (double)(j - (int)description.Surface[i + position.X]) / (double)(description.Hive.Top - description.Desert.Top);
                    num3 = Utils.Clamp<double>(num3, 0.0, 1.0);
                    int num4 = (int)(PitEntrance.GetHoleRadiusScaleAt(num3) * (double)holeRadius);
                    if (Math.Abs(i) < num4)
                    {
                        Main.tile[i + position.X, j].ClearEverything();
                    }
                    else if (Math.Abs(i) < num4 + 3 && num3 > 0.35)
                    {
                        Main.tile[i + position.X, j].ResetToType(397);
                    }
                    double num5 = Math.Abs((double)i / (double)holeRadius);
                    num5 *= num5;
                    if (Math.Abs(i) < num4 + 3 && (double)(j - position.Y) > 15.0 - 3.0 * num5)
                    {
                        Main.tile[i + position.X, j].wall = 187;
                        WorldGen.SquareWallFrame(i + position.X, j - 1, true);
                        WorldGen.SquareWallFrame(i + position.X, j, true);
                    }
                }
            }
            holeRadius += 4;
            for (int k = -holeRadius; k < holeRadius; k++)
            {
                int num6 = holeRadius - Math.Abs(k);
                num6 = Math.Min(10, num6 * num6);
                for (int l = 0; l < num6; l++)
                {
                    Main.tile[k + position.X, l + (int)description.Surface[k + position.X]].ClearEverything();
                }
            }
        }
References System.Math.Abs(), Terraria.Utils.Clamp(), Terraria.Tile.ClearEverything(), Terraria.GameContent.Biomes.Desert.DesertDescription.Desert, Terraria.GameContent.Biomes.Desert.PitEntrance.GetHoleRadiusScaleAt(), int, System.Math.Min(), Terraria.Tile.ResetToType(), Terraria.WorldBuilding.GenerationProgress.Set(), Terraria.WorldGen.SquareWallFrame(), Terraria.GameContent.Biomes.Desert.DesertDescription.Surface, Terraria.Main.tile, Microsoft.Xna.Framework.Rectangle.Top, Terraria.Tile.wall, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.Biomes.Desert.PitEntrance.Place().