Terraria Decompiled: System.IO.StreamWriter.FlushAsyncInternal
FlushAsyncInternal() [2/2]
static async Task System.IO.StreamWriter.FlushAsyncInternal (StreamWriter _this, bool flushStream, bool flushEncoder, char[] charBuffer, int charPos, bool haveWrittenPreamble, Encoding encoding, Encoder encoder, byte[] byteBuffer, Stream stream, CancellationToken cancellationToken) inline static private
Definition at line 857 of file StreamWriter.cs.
        {
            if (!haveWrittenPreamble)
            {
                _this.HaveWrittenPreamble_Prop = true;
                byte[] preamble = encoding.GetPreamble();
                if (preamble.Length != 0)
                {
                    await stream.WriteAsync(new ReadOnlyMemory<byte>(preamble), cancellationToken).ConfigureAwait(false);
                }
            }
            int bytes = encoder.GetBytes(charBuffer, 0, charPos, byteBuffer, 0, flushEncoder);
            if (bytes > 0)
            {
                await stream.WriteAsync(new ReadOnlyMemory<byte>(byteBuffer, 0, bytes), cancellationToken).ConfigureAwait(false);
            }
            if (flushStream)
            {
                await stream.FlushAsync(cancellationToken).ConfigureAwait(false);
            }
        }
References System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.IO.Stream.FlushAsync(), System.Text.Encoder.GetBytes(), System.Text.Encoding.GetPreamble(), and System.IO.Stream.WriteAsync().