Terraria Decompiled: System.IO.StreamWriter.Dispose
Dispose()
override void System.IO.StreamWriter.Dispose (bool disposing) inline protected virtual
Reimplemented from System.IO.TextWriter.
Definition at line 152 of file StreamWriter.cs.
        {
            try
            {
                if (this._stream != null && disposing)
                {
                    this.CheckAsyncTaskInProgress();
                    this.Flush(true, true);
                }
            }
            finally
            {
                if (!this.LeaveOpen && this._stream != null)
                {
                    try
                    {
                        if (disposing)
{
                            this._stream.Close();
                        }
                    }
                    finally
                    {
                        this._stream = null;
                        this._byteBuffer = null;
                        this._charBuffer = null;
                        this._encoding = null;
                        this._encoder = null;
                        this._charLen = 0;
                        base.Dispose(disposing);
                    }
                }
            }
        }
References System.IO.StreamWriter._stream, System.IO.StreamWriter.CheckAsyncTaskInProgress(), System.IO.Stream.Close(), System.IO.StreamWriter.Flush(), and System.IO.StreamWriter.LeaveOpen.
Referenced by System.IO.File.InternalWriteAllTextAsync().