Terraria Decompiled: System.IO.StreamWriter.FlushAsyncInternal
FlushAsyncInternal() [1/2]
Task System.IO.StreamWriter.FlushAsyncInternal (bool flushStream, bool flushEncoder, char[] sCharBuffer, int sCharPos, CancellationToken cancellationToken = default(CancellationToken)) inline private
Definition at line 841 of file StreamWriter.cs.
        {
            if (cancellationToken.IsCancellationRequested)
            {
                return Task.FromCanceled(cancellationToken);
            }
            if (sCharPos == 0 && !flushStream && !flushEncoder)
            {
                return Task.CompletedTask;
            }
            Task task = StreamWriter.FlushAsyncInternal(this, flushStream, flushEncoder, sCharBuffer, sCharPos, this._haveWrittenPreamble, this._encoding, this._encoder, this._byteBuffer, this._stream, cancellationToken);
            this._charPos = 0;
            return task;
        }
References System.IO.StreamWriter._byteBuffer, System.IO.StreamWriter._encoder, System.IO.StreamWriter._encoding, System.IO.StreamWriter._haveWrittenPreamble, System.IO.StreamWriter._stream, System.Threading.Tasks.Task< TResult >.CompletedTask, System.IO.StreamWriter.FlushAsyncInternal(), System.Threading.Tasks.Task< TResult >.FromCanceled(), and System.task.
Referenced by System.IO.StreamWriter.FlushAsync(), System.IO.StreamWriter.FlushAsyncInternal(), System.IO.StreamWriter.d__74.MoveNext(), System.IO.StreamWriter.WriteAsyncInternal(), System.IO.StreamWriter.WriteAsyncInternal(), and System.IO.StreamWriter.WriteAsyncInternal().