Terraria Decompiled: System.IO.StreamWriter.WriteAsyncInternal
WriteAsyncInternal() [2/3]
static async Task System.IO.StreamWriter.WriteAsyncInternal (StreamWriter _this, ReadOnlyMemory< char > source, char[] charBuffer, int charPos, int charLen, char[] coreNewLine, bool autoFlush, bool appendNewLine, CancellationToken cancellationToken) inline static private
Definition at line 659 of file StreamWriter.cs.
        {
            int num;
            for (int copied = 0; copied < source.Length; copied += num)
            {
                if (charPos == charLen)
                {
                    await _this.FlushAsyncInternal(false, false, charBuffer, charPos, cancellationToken).ConfigureAwait(false);
                    charPos = 0;
                }
                num = Math.Min(charLen - charPos, source.Length - copied);
                source.Span.Slice(copied, num).CopyTo(new Span<char>(charBuffer, charPos, num));
                charPos += num;
            }
            if (appendNewLine)
            {
                for (int i = 0; i < coreNewLine.Length; i++)
                {
                    if (charPos == charLen)
                    {
                        await _this.FlushAsyncInternal(false, false, charBuffer, charPos, cancellationToken).ConfigureAwait(false);
                        charPos = 0;
                    }
                    charBuffer[charPos] = coreNewLine[i];
                    charPos++;
                }
            }
            if (autoFlush)
            {
                await _this.FlushAsyncInternal(true, false, charBuffer, charPos, cancellationToken).ConfigureAwait(false);
                charPos = 0;
            }
            _this.CharPos_Prop = charPos;
        }
References System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.IO.StreamWriter.FlushAsyncInternal(), System.Math.Min(), and System.source.