Terraria Decompiled: System.IO.StreamWriter.FlushAsync
FlushAsync()
override Task System.IO.StreamWriter.FlushAsync () inline virtual
Reimplemented from System.IO.TextWriter.
Definition at line 804 of file StreamWriter.cs.
        {
            if (base.GetType() != typeof(StreamWriter))
            {
                return base.FlushAsync();
            }
            if (this._stream == null)
            {
                throw new ObjectDisposedException(null, "Can not write to a closed TextWriter.");
            }
            this.CheckAsyncTaskInProgress();
            Task task = this.FlushAsyncInternal(true, true, this._charBuffer, this._charPos, default(CancellationToken));
            this._asyncWriteTask = task;
            return task;
        }
References System.IO.StreamWriter._charBuffer, System.IO.StreamWriter._charPos, System.IO.StreamWriter._stream, System.IO.StreamWriter.CheckAsyncTaskInProgress(), System.IO.StreamWriter.FlushAsyncInternal(), and System.task.
Referenced by System.IO.StreamWriter.DisposeAsyncCore(), System.IO.File.InternalWriteAllTextAsync(), and System.IO.StreamWriter.d__33.MoveNext().