Terraria Decompiled: System.IO.StreamWriter.Init
Init()
void System.IO.StreamWriter.Init (Stream streamArg, Encoding encodingArg, int bufferSize, bool shouldLeaveOpen) inline private
Definition at line 125 of file StreamWriter.cs.
        {
            this._stream = streamArg;
            this._encoding = encodingArg;
            this._encoder = this._encoding.GetEncoder();
            if (bufferSize < 128)
            {
                bufferSize = 128;
            }
            this._charBuffer = new char[bufferSize];
            this._byteBuffer = new byte[this._encoding.GetMaxByteCount(bufferSize)];
            this._charLen = bufferSize;
            if (this._stream.CanSeek && this._stream.Position > 0L)
            {
                this._haveWrittenPreamble = true;
            }
            this._closable = !shouldLeaveOpen;
        }
References System.IO.StreamWriter._encoding, System.IO.StreamWriter._stream, System.IO.Stream.CanSeek, System.Text.Encoding.GetEncoder(), System.Text.Encoding.GetMaxByteCount(), and System.L.
Referenced by System.IO.StreamWriter.StreamWriter(), and System.IO.StreamWriter.StreamWriter().