Terraria Decompiled: System.IO.StreamWriter.Flush
Flush() [2/2]
void System.IO.StreamWriter.Flush (bool flushStream, bool flushEncoder) inline private
Definition at line 247 of file StreamWriter.cs.
        {
            if (this._stream == null)
            {
                throw new ObjectDisposedException(null, "Can not write to a closed TextWriter.");
            }
            if (this._charPos == 0 && !flushStream && !flushEncoder)
            {
                return;
            }
            if (!this._haveWrittenPreamble)
            {
                this._haveWrittenPreamble = true;
                ReadOnlySpan<byte> preamble = this._encoding.Preamble;
                if (preamble.Length > 0)
                {
                    this._stream.Write(preamble);
                }
            }
            int bytes = this._encoder.GetBytes(this._charBuffer, 0, this._charPos, this._byteBuffer, 0, flushEncoder);
            this._charPos = 0;
            if (bytes > 0)
            {
                this._stream.Write(this._byteBuffer, 0, bytes);
            }
            if (flushStream)
            {
                this._stream.Flush();
            }
        }
References System.IO.StreamWriter._byteBuffer, System.IO.StreamWriter._charBuffer, System.IO.StreamWriter._charPos, System.IO.StreamWriter._encoder, System.IO.StreamWriter._encoding, System.IO.StreamWriter._haveWrittenPreamble, System.IO.StreamWriter._stream, System.IO.Stream.Flush(), System.Text.Encoder.GetBytes(), System.ReadOnlySpan< T >.Length, System.Text.Encoding.Preamble, and System.IO.Stream.Write().