Terraria Decompiled: System.IO.StreamWriter.CheckAsyncTaskInProgress
CheckAsyncTaskInProgress()
void System.IO.StreamWriter.CheckAsyncTaskInProgress () inline private
Definition at line 16 of file StreamWriter.cs.
        {
            if (!this._asyncWriteTask.IsCompleted)
            {
                StreamWriter.ThrowAsyncIOInProgress();
            }
        }
References System.IO.StreamWriter._asyncWriteTask, System.Threading.Tasks.Task< TResult >.IsCompleted, and System.IO.StreamWriter.ThrowAsyncIOInProgress().
Referenced by System.IO.StreamWriter.Dispose(), System.IO.StreamWriter.Flush(), System.IO.StreamWriter.FlushAsync(), System.IO.StreamWriter.Write(), System.IO.StreamWriter.WriteAsync(), System.IO.StreamWriter.WriteAsync(), System.IO.StreamWriter.WriteAsync(), System.IO.StreamWriter.WriteAsync(), System.IO.StreamWriter.WriteLine(), System.IO.StreamWriter.WriteLine(), System.IO.StreamWriter.WriteLineAsync(), System.IO.StreamWriter.WriteLineAsync(), System.IO.StreamWriter.WriteLineAsync(), System.IO.StreamWriter.WriteLineAsync(), System.IO.StreamWriter.WriteLineAsync(), and System.IO.StreamWriter.WriteSpan().