Terraria Decompiled: Terraria.IO.FavoritesFile.IsFavorite
IsFavorite()
bool Terraria.IO.FavoritesFile.IsFavorite (FileData fileData) inline
Definition at line 43 of file FavoritesFile.cs.
        {
            if (!this._data.ContainsKey(fileData.Type))
            {
                return false;
            }
            string fileName = fileData.GetFileName(true);
            bool flag;
            return this._data[fileData.Type].TryGetValue(fileName, out flag) && flag;
        }
References Terraria.IO.FavoritesFile._data, System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), Terraria.IO.FileData.GetFileName(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and Terraria.IO.FileData.Type.