Terraria Decompiled: System.Security.Permissions.PublisherIdentityPermission.PublisherIdentityPermission
PublisherIdentityPermission() [1/2]
System.Security.Permissions.PublisherIdentityPermission.PublisherIdentityPermission (PermissionState state) inline
Definition at line 14 of file PublisherIdentityPermission.cs.
        {
            CodeAccessPermission.CheckPermissionState(state, false);
        }
References System.Security.CodeAccessPermission.CheckPermissionState(), and System.state.
Referenced by System.Security.Permissions.PublisherIdentityPermission.Cast(), System.Security.Permissions.PublisherIdentityPermission.Copy(), System.Security.Permissions.PublisherIdentityPermission.Intersect(), and System.Security.Permissions.PublisherIdentityPermission.Union().