Terraria Decompiled: System.Security.Permissions.PublisherIdentityPermission.Union
Union()
override IPermission System.Security.Permissions.PublisherIdentityPermission.Union (IPermission target) inline virtual
Reimplemented from System.Security.CodeAccessPermission.
Definition at line 101 of file PublisherIdentityPermission.cs.
        {
            PublisherIdentityPermission publisherIdentityPermission = this.Cast(target);
            if (publisherIdentityPermission == null)
            {
                return this.Copy();
            }
            if (this.x509 != null && publisherIdentityPermission.x509 != null)
            {
                if (this.x509.GetRawCertDataString() == publisherIdentityPermission.x509.GetRawCertDataString())
                {
                    return new PublisherIdentityPermission(this.x509);
                }
            }
            else
            {
                if (this.x509 == null && publisherIdentityPermission.x509 != null)
                {
                    return new PublisherIdentityPermission(publisherIdentityPermission.x509);
                }
                if (this.x509 != null && publisherIdentityPermission.x509 == null)
                {
                    return new PublisherIdentityPermission(this.x509);
                }
            }
            return null;
        }
References System.Security.Permissions.PublisherIdentityPermission.Cast(), System.Security.Permissions.PublisherIdentityPermission.Copy(), System.Security.Cryptography.X509Certificates.X509Certificate.GetRawCertDataString(), System.Security.Permissions.PublisherIdentityPermission.PublisherIdentityPermission(), and System.Security.Permissions.PublisherIdentityPermission.x509.