Terraria Decompiled: Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.FillSegments
FillSegments()
void Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.FillSegments (List< IAnimationSegment > segmentsList, out int endTime, bool inGame) inline
Definition at line 29 of file CreditsRollComposer.cs.
        {
            this._segments = segmentsList;
            int num = 0;
            int num2 = 80;
            Vector2 vector = Vector2.UnitY * -1f * (float)num2;
            int num3 = 210;
            Vector2 vector2 = vector + Vector2.UnitX * 200f;
            Vector2 vector3 = vector2;
            if (!inGame)
            {
                vector2 = (vector3 = Vector2.UnitY * 80f);
            }
            int num4 = num3 * 3;
            int num5 = num3 * 3;
            int num6 = num4 - num5;
            if (!inGame)
            {
                num5 = 180;
                num6 = num4 - num5;
            }
            num += num5;
            num += this.PlaySegment_TextRoll(num, "CreditsRollCategory_Creator", vector2).totalTime;
            num += num3;
            num += this.PlaySegment_Grox_GuideRunningFromZombie(num, vector2).totalTime;
            num += num3;
            vector2.X *= -1f;
            num += this.PlaySegment_TextRoll(num, "CreditsRollCategory_ExecutiveProducer", vector2).totalTime;
            num += num3;
            num += this.PlaySegment_Grox_MerchantAndTravelingMerchantTryingToSellJunk(num, vector2).totalTime;
            num += num3;
            vector2.X *= -1f;
            num += this.PlaySegment_TextRoll(num, "CreditsRollCategory_Designer", vector2).totalTime;
            num += num3;
            num += this.PlaySegment_Grox_DemolitionistAndArmsDealerArguingThenNurseComes(num, vector2).totalTime;
            num += num3;
            vector2.X *= -1f;
            num += this.PlaySegment_TextRoll(num, "CreditsRollCategory_Programming", vector2).totalTime;
            num += num3;
            num += this.PlaySegment_TinkererAndMechanic(num, vector2).totalTime;
            num += num3;
            vector2.X *= 0f;
            num += this.PlaySegment_TextRoll(num, "CreditsRollCategory_Graphics", vector2).totalTime;
            num += num3;
            num += this.PlaySegment_Grox_DryadSayingByeToTavernKeep(num, vector2).totalTime;
            num += num3;
            vector2 = vector3;
            vector2.X *= -1f;
            num += this.PlaySegment_TextRoll(num, "CreditsRollCategory_Music", vector2).totalTime;
            num += num3;
            num += this.PlaySegment_Grox_WizardPartyGirlDyeTraderAndPainterPartyWithBunnies(num, vector2).totalTime;
            num += num3;
            vector2.X *= -1f;
            num += this.PlaySegment_TextRoll(num, "CreditsRollCategory_Sound", vector2).totalTime;
            num += num3;
            num += this.PlaySegment_ClothierChasingTruffle(num, vector2).totalTime;
            num += num3;
            vector2.X *= -1f;
            num += this.PlaySegment_TextRoll(num, "CreditsRollCategory_Dialog", vector2).totalTime;
            num += num3;
            num += this.PlaySegment_Grox_AnglerAndPirateTalkAboutFish(num, vector2).totalTime;
            num += num3;
            vector2.X *= 0f;
            num += this.PlaySegment_TextRoll(num, "CreditsRollCategory_QualityAssurance", vector2).totalTime;
            num += num3;
            num += this.PlaySegment_Grox_ZoologistAndPetsAnnoyGolfer(num, vector2).totalTime;
            num += num3;
            vector2 = vector3;
            vector2.X *= -1f;
            num += this.PlaySegment_TextRoll(num, "CreditsRollCategory_BusinessDevelopment", vector2).totalTime;
            num += num3;
            num += this.PlaySegment_Grox_SkeletonMerchantSearchesThroughBones(num, vector2).totalTime;
            num += num3;
            vector2.X *= -1f;
            num += this.PlaySegment_TextRoll(num, "CreditsRollCategory_Marketing", vector2).totalTime;
            num += num3;
            num += this.PlaySegment_DryadTurningToTree(num, vector2).totalTime;
            num += num3;
            vector2.X *= -1f;
            num += this.PlaySegment_TextRoll(num, "CreditsRollCategory_PublicRelations", vector2).totalTime;
            num += num3;
            num += this.PlaySegment_Grox_SteampunkerRepairingCyborg(num, vector2).totalTime;
            num += num3;
            vector2.X *= 0f;
            num += this.PlaySegment_TextRoll(num, "CreditsRollCategory_Webmaster", vector2).totalTime;
            num += num3;
            num += this.PlaySegment_Grox_SantaAndTaxCollectorThrowingPresents(num, vector2).totalTime;
            num += num3;
            num += this.PlaySegment_TextRoll(num, "CreditsRollCategory_Playtesting", vector2).totalTime;
            num += num3;
            num += this.PlaySegment_Grox_WitchDoctorGoingToHisPeople(num, vector2).totalTime;
            num += num3;
            num += this.PlaySegment_TextRoll(num, "CreditsRollCategory_Localization", vector2).totalTime;
            num += num3;
            num += this.PlaySegment_TextRoll(num, "CreditsRollCategory_SpecialThanksto", vector2).totalTime;
            num += num3 * 2;
            num += this.PlaySegment_TextRoll(num, "CreditsRollCategory_Dedication", vector2).totalTime;
            num += num3;
            num += this.PlaySegment_PrincessAndEveryoneThanksPlayer(num, vector2).totalTime;
            num += num3;
            num += this.PlaySegment_TextRoll(num, "CreditsRollCategory_EndingNotes", vector2).totalTime;
            num += num6;
            this._endTime = num + 10;
            endTime = this._endTime;
        }
References Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer._endTime, Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_ClothierChasingTruffle(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_DryadTurningToTree(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_AnglerAndPirateTalkAboutFish(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_DemolitionistAndArmsDealerArguingThenNurseComes(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_DryadSayingByeToTavernKeep(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_GuideRunningFromZombie(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_MerchantAndTravelingMerchantTryingToSellJunk(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_SantaAndTaxCollectorThrowingPresents(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_SkeletonMerchantSearchesThroughBones(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_SteampunkerRepairingCyborg(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_WitchDoctorGoingToHisPeople(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_WizardPartyGirlDyeTraderAndPainterPartyWithBunnies(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_ZoologistAndPetsAnnoyGolfer(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_PrincessAndEveryoneThanksPlayer(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_TextRoll(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_TinkererAndMechanic(), and Terraria.GameContent.Animations.SegmentInforReport.totalTime.
Referenced by Terraria.GameContent.Skies.CreditsRollSky.EnsureSegmentsAreMade().