Terraria Decompiled: Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_SantaItemExample
PlaySegment_SantaItemExample()
SegmentInforReport Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_SantaItemExample (int startTime, Vector2 sceneAnchorPosition) inline private
Definition at line 845 of file CreditsRollComposer.cs.
        {
            sceneAnchorPosition += this.GetSceneFixVector();
            int num = 0;
            for (int i = 0; i < num; i++)
            {
                int num2 = (int)Main.rand.NextFromList(new short[] { 599, 1958, 3749, 1869 });
                Main.instance.LoadItem(num2);
                Asset<Texture2D> asset = TextureAssets.Item[num2];
                DrawData drawData = new DrawData(asset.Value, Vector2.Zero, null, Color.White, 0f, asset.Size() / 2f, 1f, SpriteEffects.None, 0f);
                Vector2 vector = Vector2.UnitY * -12f + Main.rand.NextVector2Circular(6f, 3f).RotatedBy((double)((float)(i - num / 2) * 6.2831855f * 0.1f), default(Vector2));
                Vector2 vector2 = Vector2.UnitY * 0.2f;
                Segments.AnimationSegmentWithActions<Segments.LooseSprite> animationSegmentWithActions = new Segments.SpriteSegment(asset, startTime, drawData, sceneAnchorPosition).Then(new Actions.Sprites.SimulateGravity(vector, vector2, Main.rand.NextFloatDirection() * 0.2f, 60)).With(new Actions.Sprites.Fade(0f, 60));
                this._segments.Add(animationSegmentWithActions);
            }
            Segments.AnimationSegmentWithActions<NPC> animationSegmentWithActions2 = new Segments.NPCSegment(startTime, 142, sceneAnchorPosition, this._originAtBottom).Then(new Actions.NPCs.ShowItem(30, 267)).Then(new Actions.NPCs.Wait(10)).Then(new Actions.NPCs.ShowItem(30, 600))
                .Then(new Actions.NPCs.Wait(10))
                .Then(new Actions.NPCs.ShowItem(30, 2))
                .Then(new Actions.NPCs.Wait(10));
            this._segments.Add(animationSegmentWithActions2);
            return new SegmentInforReport
            {
                totalTime = 170
            };
        }
References Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer._segments, System.Collections.Generic.List< T >.Add(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.GetSceneFixVector(), Terraria.Main.instance, int, Terraria.GameContent.TextureAssets.Item, Terraria.Main.LoadItem(), Terraria.Main.rand, Terraria.GameContent.Animations.Segments.AnimationSegmentWithActions< T >.Then(), ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Color.White, and Microsoft.Xna.Framework.Vector2.Zero.