Terraria Decompiled: Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.AddWavingNPC
AddWavingNPC()
void Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.AddWavingNPC (int npcType, Vector2 sceneAnchoePosition, int lookDirection, int fromTime, int duration, int timeToJumpAt) inline private
Definition at line 202 of file CreditsRollComposer.cs.
        {
            int num = 0;
            float num2 = 4f;
            float num3 = 0.2f;
            float num4 = num2 * 2f / num3;
            int num5 = NPCID.Sets.AttackType[npcType] * 6 + npcType % 13 * 2 + 20;
            int num6 = 0;
            if (npcType % 7 != 0)
            {
                num6 = 0;
            }
            bool flag = npcType == 663 || npcType == 108;
            bool flag2 = false;
            if (flag)
            {
                num6 = 180;
            }
            int num7 = 240;
            int num8 = lookDirection;
            int num9 = -1;
            int num10 = 0;
            if (npcType <= 227)
            {
                if (npcType != 54 && npcType != 107 && npcType != 227)
                {
                    goto IL_00B3;
                }
            }
            else if (npcType <= 353)
            {
                if (npcType != 229 && npcType != 353)
                {
                    goto IL_00B3;
                }
            }
            else if (npcType != 550 && npcType != 663)
            {
                goto IL_00B3;
            }
            num8 *= -1;
            IL_00B3:
            if (npcType - 207 <= 2 || npcType == 228 || npcType - 368 <= 1)
            {
                flag2 = true;
            }
            if (npcType <= 208)
            {
                if (npcType != 54)
                {
                    if (npcType != 107)
                    {
                        if (npcType == 208)
{
                            num9 = 127;
                        }
                    }
                    else
                    {
                        num9 = 0;
                    }
                }
                else
                {
                    num9 = 126;
                }
            }
            else if (npcType != 229)
            {
                if (npcType != 353)
                {
                    if (npcType == 368)
                    {
                        num9 = 15;
                    }
                }
                else
                {
                    num9 = 136;
                }
            }
            else
            {
                num9 = 85;
            }
            if (num9 != -1)
            {
                num10 = npcType % 6 * 20 + 60;
            }
            int num11 = duration - timeToJumpAt - num - num7;
            Segments.AnimationSegmentWithActions<NPC> animationSegmentWithActions = new Segments.NPCSegment(fromTime, npcType, sceneAnchoePosition, this._originAtBottom).Then(new Actions.NPCs.Fade(255)).With(new Actions.NPCs.Fade(-5, 51)).With(new Actions.NPCs.LookAt(num8));
            if (flag2)
            {
                animationSegmentWithActions.With(new Actions.NPCs.PartyHard());
            }
            animationSegmentWithActions.Then(new Actions.NPCs.Wait(num7)).Then(new Actions.NPCs.LookAt(lookDirection)).Then(new Actions.NPCs.Wait(timeToJumpAt))
                .Then(new Actions.NPCs.MoveWithAcceleration(new Vector2(0f, -num2), new Vector2(0f, num3), (int)num4))
                .With(new Actions.NPCs.Move(new Vector2(0f, 1E-05f), (int)num4))
                .Then(new Actions.NPCs.Wait(num11 - 90 + num5))
                .Then(new Actions.NPCs.Wait(90 - num5));
            if (num6 > 0)
            {
                animationSegmentWithActions.With(new Actions.NPCs.Blink(num6));
            }
            animationSegmentWithActions.Then(new Actions.NPCs.Fade(3, 85));
            if (npcType == 663)
            {
                this.AddEmote(sceneAnchoePosition, fromTime, duration, num5, 17, lookDirection);
            }
            if (num9 != -1)
            {
                this.AddEmote(sceneAnchoePosition, fromTime, num10, 0, num9, num8);
            }
            this._segments.Add(animationSegmentWithActions);
        }
References Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer._originAtBottom, Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer._segments, System.Collections.Generic.List< T >.Add(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.AddEmote(), Terraria.ID.NPCID.Sets.AttackType, System.E, Terraria.GameContent.Animations.Segments.AnimationSegmentWithActions< T >.Then(), and Microsoft.Xna.Framework.Graphics.Vector2.