Terraria Decompiled: Newtonsoft.Json.Converters.StringEnumConverter.WriteJson
WriteJson()
override void Newtonsoft.Json.Converters.StringEnumConverter.WriteJson (JsonWriter writer, object value, JsonSerializer serializer) inline
Definition at line 59 of file StringEnumConverter.cs.
        {
            if (value == null)
            {
                writer.WriteNull();
                return;
            }
            Enum @enum = (Enum)value;
            string text = @enum.ToString("G");
            if (!char.IsNumber(text.get_Chars(0)) && text.get_Chars(0) != '-')
            {
                string text2 = EnumUtils.ToEnumName(@enum.GetType(), text, this.CamelCaseText);
                writer.WriteValue(text2);
                return;
            }
            if (!this.AllowIntegerValues)
            {
                throw JsonSerializationException.Create(null, writer.ContainerPath, "Integer value {0} is not allowed.".FormatWith(CultureInfo.InvariantCulture, text), null);
            }
            writer.WriteValue(value);
        }
References Newtonsoft.Json.Converters.StringEnumConverter.AllowIntegerValues, Newtonsoft.Json.Converters.StringEnumConverter.CamelCaseText, Newtonsoft.Json.JsonWriter.ContainerPath, Newtonsoft.Json.JsonSerializationException.Create(), System.Enum, System.Globalization.CultureInfo.InvariantCulture, System.text, Newtonsoft.Json.Utilities.EnumUtils.ToEnumName(), System.Enum.ToString(), System.value, Newtonsoft.Json.JsonWriter.WriteNull(), and Newtonsoft.Json.JsonWriter.WriteValue().