Terraria Decompiled: Newtonsoft.Json.Converters.StringEnumConverter.ReadJson
ReadJson()
override object Newtonsoft.Json.Converters.StringEnumConverter.ReadJson (JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer) inline
Definition at line 82 of file StringEnumConverter.cs.
        {
            if (reader.TokenType != JsonToken.Null)
            {
                bool flag = ReflectionUtils.IsNullableType(objectType);
                Type type = (flag ? Nullable.GetUnderlyingType(objectType) : objectType);
                try
                {
                    if (reader.TokenType == JsonToken.String)
                    {
                        return EnumUtils.ParseEnumName(reader.Value.ToString(), flag, !this.AllowIntegerValues, type);
                    }
                    if (reader.TokenType == JsonToken.Integer)
                    {
                        if (!this.AllowIntegerValues)
{
                            throw JsonSerializationException.Create(reader, "Integer value {0} is not allowed.".FormatWith(CultureInfo.InvariantCulture, reader.Value));
                        }
                        return ConvertUtils.ConvertOrCast(reader.Value, CultureInfo.InvariantCulture, type);
                    }
                }
                catch (Exception ex)
                {
                    throw JsonSerializationException.Create(reader, "Error converting value {0} to type '{1}'.".FormatWith(CultureInfo.InvariantCulture, MiscellaneousUtils.FormatValueForPrint(reader.Value), objectType), ex);
                }
                throw JsonSerializationException.Create(reader, "Unexpected token {0} when parsing enum.".FormatWith(CultureInfo.InvariantCulture, reader.TokenType));
            }
            if (!ReflectionUtils.IsNullableType(objectType))
            {
                throw JsonSerializationException.Create(reader, "Cannot convert null value to {0}.".FormatWith(CultureInfo.InvariantCulture, objectType));
            }
            return null;
        }
References Newtonsoft.Json.Converters.StringEnumConverter.AllowIntegerValues, Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(), Newtonsoft.Json.JsonSerializationException.Create(), Newtonsoft.Json.Utilities.MiscellaneousUtils.FormatValueForPrint(), System.Nullable< T >.GetUnderlyingType(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.Utilities.ReflectionUtils.IsNullableType(), Newtonsoft.Json.Utilities.EnumUtils.ParseEnumName(), Newtonsoft.Json.JsonReader.TokenType, and Newtonsoft.Json.JsonReader.Value.