Terraria Decompiled: System.IO.BinaryReader.ReadInt16
ReadInt16()
virtual short System.IO.BinaryReader.ReadInt16 () inline virtual
Definition at line 167 of file BinaryReader.cs.
        {
            this.FillBuffer(2);
            return (short)((int)this.m_buffer[0] | ((int)this.m_buffer[1] << 8));
        }
References System.IO.BinaryReader.FillBuffer(), int, and System.IO.BinaryReader.m_buffer.
Referenced by System.Resources.ResourceReader._LoadObjectV1(), System.Resources.ResourceReader._LoadObjectV2(), Terraria.NetMessage.DecompressTileBlock(), Terraria.NetMessage.DecompressTileBlock_Inner(), Terraria.GameContent.BannerSystem.NetBannersModule.Deserialize(), Terraria.GameContent.Items.TagEffectState.NetModule.Deserialize(), Terraria.GameContent.LeashedEntity.NetModule.Deserialize(), Terraria.GameContent.NetModules.NetBestiaryModule.Deserialize(), Terraria.GameContent.NetModules.NetTeleportPylonModule.Deserialize(), Terraria.DataStructures.PlayerDeathReason.FromReader(), Terraria.IO.WorldFile.GetAllMetadata(), Terraria.MessageBuffer.GetData(), Terraria.GameContent.BannerSystem.Load(), Terraria.IO.WorldFile.LoadChests(), Terraria.IO.WorldFile.LoadDummies(), Terraria.IO.WorldFile.LoadFileFormatHeader(), Terraria.IO.WorldFile.LoadHeader(), Terraria.Map.MapHelper.LoadMapVersion1(), Terraria.Map.MapHelper.LoadMapVersion2(), Terraria.Map.MapHelper.LoadMapVersionCompressed(), Terraria.IO.WorldFile.LoadSigns(), Terraria.IO.WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), Terraria.IO.WorldFile.LoadWorldTiles(), Terraria.GameContent.LeashedEntities.LeashedCritter.NetReceive(), Terraria.GameContent.ExtraSpawnPointManager.Read(), Terraria.GameContent.Tile_Entities.TEDeadCellsDisplayJar.ReadExtraData(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.ReadExtraData(), Terraria.GameContent.Tile_Entities.TEFoodPlatter.ReadExtraData(), Terraria.GameContent.Tile_Entities.TEHatRack.ReadExtraData(), Terraria.GameContent.Tile_Entities.TEItemFrame.ReadExtraData(), Terraria.GameContent.Tile_Entities.TELeashedEntityAnchorWithItem.ReadExtraData(), Terraria.GameContent.Tile_Entities.TETrainingDummy.ReadExtraData(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.ReadExtraData(), Terraria.DataStructures.NPCFollowState.ReadFrom(), System.Resources.Win32IconFileReader.ReadIcons(), Terraria.DataStructures.TileEntity.ReadInner(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadInt16(), Terraria.GameContent.QuickStacking.ReadNetInventory(), Terraria.DataStructures.TrackedProjectileReference.TryReading(), Terraria.IO.WorldFile.ValidateWorld(), Terraria.GameContent.BannerSystem.ValidateWorld(), and Terraria.Audio.WAVAudioTrack.WAVAudioTrack().