Terraria Decompiled: System.IO.BinaryReader.ReadString
ReadString()
virtual string System.IO.BinaryReader.ReadString () inline virtual
Definition at line 263 of file BinaryReader.cs.
        {
            if (this.m_stream == null)
            {
                __Error.FileNotOpen();
            }
            int num = 0;
            int num2 = this.Read7BitEncodedInt();
            if (num2 < 0)
            {
                throw new IOException(Environment.GetResourceString("BinaryReader encountered an invalid string length of {0} characters.", new object[] { num2 }));
            }
            if (num2 == 0)
            {
                return string.Empty;
            }
            if (this.m_charBytes == null)
            {
                this.m_charBytes = new byte[128];
            }
            if (this.m_charBuffer == null)
            {
                this.m_charBuffer = new char[this.m_maxCharsSize];
            }
            StringBuilder stringBuilder = null;
            int chars;
            for (;;)
            {
                int num3 = ((num2 - num > 128) ? 128 : (num2 - num));
                int num4 = this.m_stream.Read(this.m_charBytes, 0, num3);
                if (num4 == 0)
                {
                    __Error.EndOfFile();
                }
                chars = this.m_decoder.GetChars(this.m_charBytes, 0, num4, this.m_charBuffer, 0);
                if (num == 0 && num4 == num2)
                {
                    break;
                }
                if (stringBuilder == null)
                {
                    stringBuilder = StringBuilderCache.Acquire(num2);
                }
                stringBuilder.Append(this.m_charBuffer, 0, chars);
                num += num4;
                if (num >= num2)
                {
                    goto Block_11;
                }
            }
            return new string(this.m_charBuffer, 0, chars);
            Block_11:
            return StringBuilderCache.GetStringAndRelease(stringBuilder);
        }
References System.Text.StringBuilderCache.Acquire(), System.Text.StringBuilder.Append(), System.IO.__Error.EndOfFile(), System.IO.__Error.FileNotOpen(), System.Text.Decoder.GetChars(), System.Environment.GetResourceString(), System.Text.StringBuilderCache.GetStringAndRelease(), System.IO.BinaryReader.m_charBuffer, System.IO.BinaryReader.m_charBytes, System.IO.BinaryReader.m_decoder, System.IO.BinaryReader.m_maxCharsSize, System.IO.BinaryReader.m_stream, System.IO.Stream.Read(), and System.IO.BinaryReader.Read7BitEncodedInt().
Referenced by System.Resources.ResourceReader._LoadObjectV1(), System.Resources.ResourceReader._LoadObjectV2(), System.Resources.ResourceReader._ReadResources(), System.Resources.ManifestBasedResourceGroveler.CreateResourceSet(), Terraria.NetMessage.DecompressTileBlock_Inner(), Terraria.Chat.ChatCommandId.Deserialize(), Terraria.Chat.ChatMessage.Deserialize(), Terraria.Localization.NetworkText.Deserialize(), Terraria.Testing.ChatCommands.DebugMessage.Deserialize(), Terraria.Player.Deserialize(), Terraria.Localization.NetworkText.DeserializeLiteral(), System.Threading.Thread.DeserializePrincipal(), System.Resources.ResourceReader.FindType(), Terraria.DataStructures.PlayerDeathReason.FromReader(), Terraria.IO.WorldFile.GetAllMetadata(), Terraria.MessageBuffer.GetData(), System.Security.Claims.ClaimsIdentity.Initialize(), System.Security.Claims.ClaimsPrincipal.Initialize(), System.Security.Claims.Claim.Initialize(), Terraria.GameContent.Bestiary.NPCKillsTracker.Load(), Terraria.GameContent.Bestiary.NPCWasChatWithTracker.Load(), Terraria.GameContent.Bestiary.NPCWasNearPlayerTracker.Load(), Terraria.GameContent.Creative.ItemsSacrificedUnlocksTracker.Load(), Terraria.Utilities.TileSnapshot.Load(), Microsoft.Xna.Framework.Content.ContentTypeReaderManager.LoadAssetReaders(), Terraria.IO.WorldFile.LoadChests(), Terraria.IO.WorldFile.LoadFooter(), Terraria.IO.WorldFile.LoadHeader(), Terraria.Map.MapHelper.LoadMapVersion1(), Terraria.Map.MapHelper.LoadMapVersion2(), Terraria.Map.MapHelper.LoadMapVersionCompressed(), Terraria.IO.WorldFile.LoadNPCs(), Terraria.Player.LoadPlayer(), Terraria.IO.WorldFile.LoadSigns(), System.Resources.ResourceReader.LoadString(), Terraria.IO.WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), Terraria.Main.OpenLegacySettings(), Terraria.Main.OpenRecent(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadDecimal(), Microsoft.Xna.Framework.Content.ContentReader.ReadExternalReference< T >(), Terraria.WorldBuilding.WorldGenSnapshot.ReadSnapshot(), Terraria.Testing.LockstepDebug.ReadStep(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadString(), System.Resources.ResourceReader.TypeNameFromTypeCode(), Terraria.IO.WorldFile.ValidateLoadNPCs(), Terraria.IO.WorldFile.ValidateWorld(), Terraria.GameContent.Bestiary.NPCKillsTracker.ValidateWorld(), Terraria.GameContent.Bestiary.NPCWasChatWithTracker.ValidateWorld(), Terraria.GameContent.Bestiary.NPCWasNearPlayerTracker.ValidateWorld(), and Terraria.GameContent.Creative.ItemsSacrificedUnlocksTracker.ValidateWorld().