Terraria Decompiled: System.IO.BinaryReader.ReadInt64
ReadInt64()
virtual long System.IO.BinaryReader.ReadInt64 () inline virtual
Definition at line 205 of file BinaryReader.cs.
        {
            this.FillBuffer(8);
            uint num = (uint)((int)this.m_buffer[0] | ((int)this.m_buffer[1] << 8) | ((int)this.m_buffer[2] << 16) | ((int)this.m_buffer[3] << 24));
            return (long)(((ulong)((int)this.m_buffer[4] | ((int)this.m_buffer[5] << 8) | ((int)this.m_buffer[6] << 16) | ((int)this.m_buffer[7] << 24)) << 32) | (ulong)num);
        }
References System.IO.BinaryReader.FillBuffer(), int, and System.IO.BinaryReader.m_buffer.
Referenced by System.Resources.ResourceReader._LoadObjectV1(), System.Resources.ResourceReader._LoadObjectV2(), Terraria.Player.Deserialize(), Terraria.IO.WorldFile.GetAllMetadata(), Terraria.IO.WorldFile.LoadHeader(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadInt64(), Newtonsoft.Json.Bson.BsonReader.ReadInt64(), and Terraria.IO.WorldFile.ValidateWorld().