Terraria Decompiled: System.IO.BinaryReader.ReadDecimal
ReadDecimal()
virtual decimal System.IO.BinaryReader.ReadDecimal () inline virtual
Definition at line 238 of file BinaryReader.cs.
        {
            this.FillBuffer(16);
            decimal num;
            try
            {
                int[] array = new int[4];
                Buffer.BlockCopy(this.m_buffer, 0, array, 0, 16);
                if (!BitConverter.IsLittleEndian)
                {
                    for (int i = 0; i < 4; i++)
                    {
                        array[i] = BinaryPrimitives.ReverseEndianness(array[i]);
                    }
                }
                num = new decimal(array);
            }
            catch (ArgumentException ex)
            {
                throw new IOException(Environment.GetResourceString("Decimal byte array constructor requires an array of length four containing valid decimal bytes."), ex);
            }
            return num;
        }
References System.array, System.Buffer.BlockCopy(), System.IO.BinaryReader.FillBuffer(), System.Environment.GetResourceString(), System.BitConverter.IsLittleEndian, System.IO.BinaryReader.m_buffer, and System.Buffers.Binary.BinaryPrimitives.ReverseEndianness().
Referenced by System.Resources.ResourceReader._LoadObjectV2().