Terraria Decompiled: System.IO.BinaryReader.ReadDouble
ReadDouble()
virtual double System.IO.BinaryReader.ReadDouble () inline virtual
Definition at line 231 of file BinaryReader.cs.
        {
            this.FillBuffer(8);
            return BitConverterLE.ToDouble(this.m_buffer, 0);
        }
References System.IO.BinaryReader.FillBuffer(), System.IO.BinaryReader.m_buffer, and Mono.Security.BitConverterLE.ToDouble().
Referenced by System.Resources.ResourceReader._LoadObjectV1(), System.Resources.ResourceReader._LoadObjectV2(), Terraria.IO.WorldFile.GetAllMetadata(), Terraria.IO.WorldFile.LoadHeader(), Terraria.IO.WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadDouble(), and Newtonsoft.Json.Bson.BsonReader.ReadDouble().