Terraria Decompiled: System.IO.BinaryReader.ReadChars
ReadChars()
virtual char[] System.IO.BinaryReader.ReadChars (int count) inline virtual
Definition at line 491 of file BinaryReader.cs.
        {
            if (count < 0)
            {
                throw new ArgumentOutOfRangeException("count", Environment.GetResourceString("Non-negative number required."));
            }
            if (this.m_stream == null)
            {
                __Error.FileNotOpen();
            }
            if (count == 0)
            {
                return EmptyArray<char>.Value;
            }
            char[] array = new char[count];
            int num = this.InternalReadChars(array, 0, count);
            if (num != count)
            {
                char[] array2 = new char[num];
                Buffer.InternalBlockCopy(array, 0, array2, 0, 2 * num);
                array = array2;
            }
            return array;
        }
References System.array, System.count, System.IO.__Error.FileNotOpen(), System.Environment.GetResourceString(), System.Buffer.InternalBlockCopy(), System.IO.BinaryReader.InternalReadChars(), System.IO.BinaryReader.m_stream, and System.EmptyArray< T >.Value.
Referenced by Microsoft.Xna.Framework.Audio.SoundEffect.FromStream(), and System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadChars().