Terraria Decompiled: System.IO.BinaryReader.FillBuffer
FillBuffer()
virtual void System.IO.BinaryReader.FillBuffer (int numBytes) inline protected virtual
Definition at line 612 of file BinaryReader.cs.
        {
            if (this.m_buffer != null && (numBytes < 0 || numBytes > this.m_buffer.Length))
            {
                throw new ArgumentOutOfRangeException("numBytes", Environment.GetResourceString("The number of bytes requested does not fit into BinaryReader's internal buffer."));
            }
            int num = 0;
            if (this.m_stream == null)
            {
                __Error.FileNotOpen();
            }
            if (numBytes == 1)
            {
                int num2 = this.m_stream.ReadByte();
                if (num2 == -1)
                {
                    __Error.EndOfFile();
                }
                this.m_buffer[0] = (byte)num2;
                return;
            }
            do
            {
                int num2 = this.m_stream.Read(this.m_buffer, num, numBytes - num);
                if (num2 == 0)
                {
                    __Error.EndOfFile();
                }
                num += num2;
            }
            while (num < numBytes);
        }
References System.IO.__Error.EndOfFile(), System.IO.__Error.FileNotOpen(), System.Environment.GetResourceString(), System.IO.BinaryReader.m_buffer, System.IO.BinaryReader.m_stream, System.IO.Stream.Read(), and System.IO.Stream.ReadByte().
Referenced by System.IO.BinaryReader.ReadBoolean(), System.IO.BinaryReader.ReadDecimal(), System.IO.BinaryReader.ReadDouble(), System.IO.BinaryReader.ReadInt16(), System.IO.BinaryReader.ReadInt32(), System.IO.BinaryReader.ReadInt64(), System.IO.BinaryReader.ReadSByte(), System.IO.BinaryReader.ReadSingle(), System.IO.BinaryReader.ReadUInt16(), System.IO.BinaryReader.ReadUInt32(), and System.IO.BinaryReader.ReadUInt64().