Terraria Decompiled: System.IO.BinaryReader.InternalReadChars
InternalReadChars()
unsafe int System.IO.BinaryReader.InternalReadChars (char[] buffer, int index, int count) inline private
Definition at line 347 of file BinaryReader.cs.
        {
            int i = count;
            if (this.m_charBytes == null)
            {
                this.m_charBytes = new byte[128];
            }
            while (i > 0)
            {
                int num = i;
                DecoderNLS decoderNLS = this.m_decoder as DecoderNLS;
                if (decoderNLS != null && decoderNLS.HasState && num > 1)
                {
                    num--;
                }
                if (this.m_2BytesPerChar)
                {
                    num <<= 1;
                }
                if (num > 128)
                {
                    num = 128;
                }
                int num2 = 0;
                byte[] array;
                if (this.m_isMemoryStream)
                {
                    MemoryStream memoryStream = this.m_stream as MemoryStream;
                    num2 = memoryStream.InternalGetPosition();
                    num = memoryStream.InternalEmulateRead(num);
                    array = memoryStream.InternalGetBuffer();
                }
                else
                {
                    num = this.m_stream.Read(this.m_charBytes, 0, num);
                    array = this.m_charBytes;
                }
                if (num == 0)
                {
                    return count - i;
                }
                int chars;
                checked
                {
                    if (num2 < 0 || num < 0 || num2 + num > array.Length)
                    {
                        throw new ArgumentOutOfRangeException("byteCount");
                    }
                    if (index < 0 || i < 0 || index + i > buffer.Length)
                    {
                        throw new ArgumentOutOfRangeException("charsRemaining");
                    }
                    byte[] array2;
                    byte* ptr;
                    if ((array2 = array) == null || array2.Length == 0)
                    {
                        ptr = null;
                    }
                    else
                    {
                        ptr = &array2[0];
                    }
                    fixed (char[] array3 = buffer)
                    {
                        char* ptr2;
                        if (buffer == null || array3.Length == 0)
{
                            ptr2 = null;
                        }
                        else
{
                            ptr2 = &array3[0];
                        }
                        chars = this.m_decoder.GetChars(ptr + num2, num, ptr2 + index, i, false);
                    }
                    array2 = null;
                }
                i -= chars;
                index += chars;
            }
            return count - i;
        }
References System.array, System.count, System.Text.Decoder.GetChars(), System.Text.DecoderNLS.HasState, System.index, System.IO.MemoryStream.InternalEmulateRead(), System.IO.MemoryStream.InternalGetBuffer(), System.IO.MemoryStream.InternalGetPosition(), System.IO.BinaryReader.m_2BytesPerChar, System.IO.BinaryReader.m_charBytes, System.IO.BinaryReader.m_decoder, System.IO.BinaryReader.m_isMemoryStream, System.IO.BinaryReader.m_stream, and System.IO.Stream.Read().
Referenced by System.IO.BinaryReader.Read(), System.IO.BinaryReader.Read(), and System.IO.BinaryReader.ReadChars().