Terraria Decompiled: System.IO.BinaryReader.ReadInt32
ReadInt32()
virtual int System.IO.BinaryReader.ReadInt32 () inline virtual
Definition at line 182 of file BinaryReader.cs.
        {
            if (this.m_isMemoryStream)
            {
                if (this.m_stream == null)
                {
                    __Error.FileNotOpen();
                }
                return (this.m_stream as MemoryStream).InternalReadInt32();
            }
            this.FillBuffer(4);
            return (int)this.m_buffer[0] | ((int)this.m_buffer[1] << 8) | ((int)this.m_buffer[2] << 16) | ((int)this.m_buffer[3] << 24);
        }
References System.IO.__Error.FileNotOpen(), System.IO.BinaryReader.FillBuffer(), int, System.IO.BinaryReader.m_buffer, System.IO.BinaryReader.m_isMemoryStream, and System.IO.BinaryReader.m_stream.
Referenced by System.Resources.ResourceReader._LoadObjectV1(), System.Resources.ResourceReader._LoadObjectV2(), System.Resources.ResourceReader._ReadResources(), Terraria.GameContent.CoinLossRevengeSystem.AddMarkerFromReader(), System.Resources.ResourceReader.AllocateStringForNameIndex(), System.Resources.ManifestBasedResourceGroveler.CreateResourceSet(), Terraria.NetMessage.DecompressTileBlock(), Terraria.GameContent.BannerSystem.NetBannersModule.Deserialize(), Terraria.GameContent.NetModules.NetAmbienceModule.Deserialize(), Terraria.GameContent.NetModules.NetLiquidModule.Deserialize(), Terraria.Player.Deserialize(), Terraria.GameContent.Drawing.ParticleOrchestraSettings.DeserializeFrom(), Terraria.Item.DeserializeFrom(), System.Threading.Thread.DeserializePrincipal(), Terraria.GameContent.CraftingRequests.NetCraftingRequestsModule.DeserializeRequest(), System.Resources.ResourceReader.FindPosForResource(), Microsoft.Xna.Framework.Audio.SoundEffect.FromStream(), Terraria.IO.WorldFile.GetAllMetadata(), Microsoft.Xna.Framework.Content.ContentManager.GetContentReaderFromXnb(), Terraria.MessageBuffer.GetData(), Terraria.IO.WorldFile.GetFileMetadata(), System.Resources.ResourceReader.GetResourceData(), System.Resources.ResourceReader.GetValueForNameIndex(), System.Security.Claims.ClaimsIdentity.Initialize(), System.Security.Claims.ClaimsPrincipal.Initialize(), System.Security.Claims.Claim.Initialize(), Terraria.Map.WorldMap.Load(), Terraria.GameContent.TownRoomManager.Load(), Terraria.GameContent.Bestiary.NPCKillsTracker.Load(), Terraria.GameContent.Bestiary.NPCWasChatWithTracker.Load(), Terraria.GameContent.Bestiary.NPCWasNearPlayerTracker.Load(), Terraria.GameContent.Creative.ItemsSacrificedUnlocksTracker.Load(), Terraria.GameContent.TreeTopsInfo.Load(), Terraria.GameContent.BannerSystem.Load(), Terraria.Utilities.TileSnapshot.Load(), Microsoft.Xna.Framework.Content.ContentTypeReaderManager.LoadAssetReaders(), Terraria.IO.WorldFile.LoadChests(), Terraria.IO.WorldFile.LoadDummies(), Terraria.IO.WorldFile.LoadFileFormatHeader(), Terraria.IO.WorldFile.LoadFooter(), Terraria.IO.WorldFile.LoadHeader(), Terraria.Map.MapHelper.LoadMapVersion1(), Terraria.Map.MapHelper.LoadMapVersion2(), Terraria.Map.MapHelper.LoadMapVersionCompressed(), Terraria.IO.WorldFile.LoadNPCs(), Terraria.Player.LoadPlayer(), Terraria.IO.WorldFile.LoadSigns(), Terraria.IO.WorldFile.LoadTileEntities(), Terraria.IO.WorldFile.LoadWeightedPressurePlates(), Terraria.IO.WorldFile.LoadWorld(), Terraria.IO.WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), Terraria.Main.OpenLegacySettings(), Terraria.Main.OpenRecent(), Microsoft.Xna.Framework.Graphics.Texture.ParseDDS(), Terraria.Utilities.TileSnapshot.TileStruct.Read(), Microsoft.Xna.Framework.Content.ModelReader.Read(), Microsoft.Xna.Framework.Content.Texture2DReader.Read(), Microsoft.Xna.Framework.Content.Texture3DReader.Read(), Microsoft.Xna.Framework.Content.TextureCubeReader.Read(), Microsoft.Xna.Framework.Content.VertexDeclarationReader.Read(), Terraria.GameContent.QuickStacking.ReadBlockedChestList(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.ReadDummySync(), System.Resources.Win32IconFileReader.ReadIcons(), Terraria.DataStructures.TileEntity.ReadInner(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadInt32(), Newtonsoft.Json.Bson.BsonReader.ReadInt32(), Terraria.GameContent.QuickStacking.ReadNetInventory(), Terraria.GameContent.Items.TagEffectState.NetModule.ReadSparseNPCTimeArray(), Terraria.IO.WorldFile.ValidateLoadNPCs(), Terraria.IO.WorldFile.ValidateWorld(), Terraria.GameContent.Bestiary.NPCKillsTracker.ValidateWorld(), Terraria.GameContent.Bestiary.NPCWasChatWithTracker.ValidateWorld(), Terraria.GameContent.Bestiary.NPCWasNearPlayerTracker.ValidateWorld(), Terraria.GameContent.Creative.ItemsSacrificedUnlocksTracker.ValidateWorld(), Terraria.GameContent.BannerSystem.ValidateWorld(), and Terraria.Audio.WAVAudioTrack.WAVAudioTrack().