Terraria Decompiled: System.IO.BinaryReader.ReadByte
ReadByte()
virtual byte System.IO.BinaryReader.ReadByte () inline virtual
Definition at line 133 of file BinaryReader.cs.
        {
            if (this.m_stream == null)
            {
                __Error.FileNotOpen();
            }
            int num = this.m_stream.ReadByte();
            if (num == -1)
            {
                __Error.EndOfFile();
            }
            return (byte)num;
        }
References System.IO.__Error.EndOfFile(), System.IO.__Error.FileNotOpen(), System.IO.BinaryReader.m_stream, and System.IO.Stream.ReadByte().
Referenced by System.Resources.ResourceReader._LoadObjectV1(), System.Resources.ResourceReader._LoadObjectV2(), System.Resources.ResourceReader._ReadResources(), Terraria.BitsByte.DecomposeBitsBytesChain(), Microsoft.Xna.Framework.Graphics.DxtUtil.DecompressDxt3Block(), Microsoft.Xna.Framework.Graphics.DxtUtil.DecompressDxt5Block(), Terraria.NetMessage.DecompressTileBlock_Inner(), Terraria.Localization.NetworkText.Deserialize(), Terraria.GameContent.BannerSystem.NetBannersModule.Deserialize(), Terraria.GameContent.Items.TagEffectState.NetModule.Deserialize(), Terraria.GameContent.LeashedEntity.NetModule.Deserialize(), Terraria.GameContent.NetModules.NetAmbienceModule.Deserialize(), Terraria.GameContent.NetModules.NetBestiaryModule.Deserialize(), Terraria.GameContent.NetModules.NetCreativePowerPermissionsModule.Deserialize(), Terraria.GameContent.NetModules.NetCreativeUnlocksPlayerReportModule.Deserialize(), Terraria.GameContent.NetModules.NetLiquidModule.Deserialize(), Terraria.GameContent.NetModules.NetParticlesModule.Deserialize(), Terraria.GameContent.NetModules.NetTeleportPylonModule.Deserialize(), Terraria.GameContent.UnbreakableWallScan.NetModule.Deserialize(), Terraria.Player.Deserialize(), Terraria.GameContent.Creative.CreativePowers.APerPlayerTogglePower.Deserialize_SyncEveryone(), Terraria.GameContent.NetModules.NetTextModule.DeserializeAsClient(), Terraria.GameContent.Drawing.ParticleOrchestraSettings.DeserializeFrom(), Terraria.Item.DeserializeFrom(), Terraria.Localization.NetworkText.DeserializeLiteral(), Terraria.GameContent.Creative.CreativePowers.APerPlayerTogglePower.DeserializeNetMessage(), Terraria.GameContent.Creative.CreativePowers.APerPlayerSliderPower.DeserializeNetMessage(), Terraria.Localization.NetworkText.DeserializeSubstitutionList(), Terraria.DataStructures.PlayerDeathReason.FromReader(), Terraria.IO.WorldFile.GetAllMetadata(), Microsoft.Xna.Framework.Content.ContentManager.GetContentReaderFromXnb(), Terraria.MessageBuffer.GetData(), Terraria.Utilities.TileSnapshot.Load(), Terraria.IO.WorldFile.LoadChests(), Terraria.IO.WorldFile.LoadFileFormatHeader(), Terraria.IO.WorldFile.LoadHeader(), Terraria.Map.MapHelper.LoadMapVersion1(), Terraria.Map.MapHelper.LoadMapVersion2(), Terraria.Map.MapHelper.LoadMapVersionCompressed(), Terraria.IO.WorldFile.LoadNPCs(), Terraria.Player.LoadTemporaryItemSlotContents(), Terraria.IO.WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), Terraria.IO.WorldFile.LoadWorldTiles(), Terraria.GameContent.LeashedEntities.LeashedCritter.NetReceive(), Terraria.GameContent.LeashedEntities.LeashedKite.NetReceive(), Terraria.GameContent.LeashedEntities.NormalButterflyLeashedCritter.NetReceive(), Terraria.GameContent.LeashedEntities.ShimmerFlyLeashedCritter.NetReceive(), Terraria.Social.Steam.NetSocialModule.OnLobbyChatMessage(), Terraria.Main.OpenLegacySettings(), Terraria.GameContent.ExtraSpawnPointManager.Read(), Terraria.DataStructures.TileEntity.Read(), System.IO.BinaryReader.Read7BitEncodedInt(), Terraria.Utils.Read7BitEncodedInt(), Microsoft.Xna.Framework.Content.ModelReader.ReadBoneReference(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadByte(), Newtonsoft.Json.Bson.BsonReader.ReadByte(), Microsoft.Xna.Framework.Content.ContentReader.ReadColor(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.ReadDummySync(), Terraria.GameContent.Tile_Entities.TEDeadCellsDisplayJar.ReadExtraData(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.ReadExtraData(), Terraria.GameContent.Tile_Entities.TEFoodPlatter.ReadExtraData(), Terraria.GameContent.Tile_Entities.TEHatRack.ReadExtraData(), Terraria.GameContent.Tile_Entities.TEItemFrame.ReadExtraData(), Terraria.GameContent.Tile_Entities.TELogicSensor.ReadExtraData(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.ReadExtraData(), System.Resources.Win32IconFileReader.ReadIcons(), Terraria.GameContent.Tile_Entities.TEHatRack.ReadItem(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.ReadItem(), Newtonsoft.Json.Bson.BsonReader.ReadLengthString(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.ReadPose(), Terraria.Utils.ReadRGB(), Terraria.GameContent.Items.TagEffectState.NetModule.ReadSparseNPCTimeArray(), Newtonsoft.Json.Bson.BsonReader.ReadString(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run(), Terraria.GameContent.TreeTopsInfo.SyncReceive(), Terraria.IO.WorldFile.ValidateLoadNPCs(), and Terraria.IO.WorldFile.ValidateWorld().