Terraria Decompiled: System.IO.BinaryReader.ReadBoolean
ReadBoolean()
virtual bool System.IO.BinaryReader.ReadBoolean () inline virtual
Definition at line 126 of file BinaryReader.cs.
        {
            this.FillBuffer(1);
            return this.m_buffer[0] > 0;
        }
References System.IO.BinaryReader.FillBuffer(), and System.IO.BinaryReader.m_buffer.
Referenced by System.Resources.ResourceReader._LoadObjectV2(), Terraria.GameContent.CoinLossRevengeSystem.AddMarkerFromReader(), Terraria.EquipmentLoadout.Deserialize(), Terraria.GameContent.BannerSystem.NetBannersModule.Deserialize(), Terraria.GameContent.UnbreakableWallScan.NetModule.Deserialize(), Terraria.Player.Deserialize(), Terraria.GameContent.Creative.CreativePowers.APerPlayerTogglePower.DeserializeNetMessage(), Terraria.GameContent.Creative.CreativePowers.ASharedTogglePower.DeserializeNetMessage(), Terraria.GameContent.CraftingRequests.NetCraftingRequestsModule.DeserializeResponse(), Terraria.IO.WorldFile.GetAllMetadata(), Terraria.MessageBuffer.GetData(), Terraria.GameContent.Events.DD2Event.Load(), Terraria.GameContent.Creative.CreativePowers.FreezeTime.Load(), Terraria.GameContent.Creative.CreativePowers.FreezeWindDirectionAndStrength.Load(), Terraria.GameContent.Creative.CreativePowers.FreezeRainPower.Load(), Terraria.GameContent.Creative.CreativePowers.StopBiomeSpreadPower.Load(), Terraria.GameContent.Creative.ItemsSacrificedUnlocksTracker.Load(), Terraria.GameContent.Creative.CreativePowers.GodmodePower.Load(), Terraria.GameContent.Creative.CreativePowers.FarPlacementRangePower.Load(), Terraria.IO.WorldFile.LoadFooter(), Terraria.GameContent.Creative.CreativePowerManager.LoadFromWorld(), Terraria.IO.WorldFile.LoadHeader(), Terraria.Map.MapHelper.LoadMapVersion1(), Terraria.IO.WorldFile.LoadNPCs(), Terraria.GameContent.Creative.CreativePowerManager.LoadToPlayer(), Terraria.IO.WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), Terraria.GameContent.LeashedEntities.LeashedCritter.NetReceive(), Terraria.Main.OpenLegacySettings(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadBoolean(), Terraria.GameContent.Tile_Entities.TELogicSensor.ReadExtraData(), Terraria.IO.WorldFile.ValidateLoadNPCs(), Terraria.IO.WorldFile.ValidateWorld(), Terraria.GameContent.Creative.CreativePowers.FreezeTime.ValidateWorld(), Terraria.GameContent.Creative.CreativePowers.FreezeWindDirectionAndStrength.ValidateWorld(), Terraria.GameContent.Creative.CreativePowers.FreezeRainPower.ValidateWorld(), Terraria.GameContent.Creative.CreativePowers.StopBiomeSpreadPower.ValidateWorld(), and Terraria.GameContent.Creative.CreativePowerManager.ValidateWorld().