Terraria Decompiled: System.IO.BinaryReader.ReadUInt32
ReadUInt32()
virtual uint System.IO.BinaryReader.ReadUInt32 () inline virtual
Definition at line 198 of file BinaryReader.cs.
        {
            this.FillBuffer(4);
            return (uint)((int)this.m_buffer[0] | ((int)this.m_buffer[1] << 8) | ((int)this.m_buffer[2] << 16) | ((int)this.m_buffer[3] << 24));
        }
References System.IO.BinaryReader.FillBuffer(), int, and System.IO.BinaryReader.m_buffer.
Referenced by System.Resources.ResourceReader._LoadObjectV1(), System.Resources.ResourceReader._LoadObjectV2(), Microsoft.Xna.Framework.Graphics.DxtUtil.DecompressDxt1Block(), Microsoft.Xna.Framework.Graphics.DxtUtil.DecompressDxt3Block(), Microsoft.Xna.Framework.Graphics.DxtUtil.DecompressDxt5Block(), Microsoft.Xna.Framework.Audio.SoundEffect.FromStream(), Terraria.IO.WorldFile.LoadHeader(), Terraria.GameContent.LeashedEntities.LeashedCritter.NetReceive(), Microsoft.Xna.Framework.Graphics.Texture.ParseDDS(), Terraria.IO.FileMetadata.Read(), Microsoft.Xna.Framework.Content.ModelReader.Read(), Microsoft.Xna.Framework.Content.ModelReader.ReadBoneReference(), Terraria.Utils.ReadPackedVector2(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadUInt32(), Microsoft.Xna.Framework.Graphics.X360TexUtil.SwapColor(), and Terraria.Audio.WAVAudioTrack.WAVAudioTrack().