Terraria Decompiled: System.IO.BinaryReader.InternalReadOneChar
InternalReadOneChar()
int System.IO.BinaryReader.InternalReadOneChar () inline private
Definition at line 431 of file BinaryReader.cs.
        {
            int num = 0;
            long num2 = 0L;
            if (this.m_stream.CanSeek)
            {
                num2 = this.m_stream.Position;
            }
            if (this.m_charBytes == null)
            {
                this.m_charBytes = new byte[128];
            }
            if (this.m_singleChar == null)
            {
                this.m_singleChar = new char[1];
            }
            while (num == 0)
            {
                int num3 = (this.m_2BytesPerChar ? 2 : 1);
                int num4 = this.m_stream.ReadByte();
                this.m_charBytes[0] = (byte)num4;
                if (num4 == -1)
                {
                    num3 = 0;
                }
                if (num3 == 2)
                {
                    num4 = this.m_stream.ReadByte();
                    this.m_charBytes[1] = (byte)num4;
                    if (num4 == -1)
                    {
                        num3 = 1;
                    }
                }
                if (num3 == 0)
                {
                    return -1;
                }
                try
                {
                    num = this.m_decoder.GetChars(this.m_charBytes, 0, num3, this.m_singleChar, 0);
                }
                catch
                {
                    if (this.m_stream.CanSeek)
                    {
                        this.m_stream.Seek(num2 - this.m_stream.Position, SeekOrigin.Current);
                    }
                    throw;
                }
            }
            if (num == 0)
            {
                return -1;
            }
            return (int)this.m_singleChar[0];
        }
References System.IO.Stream.CanSeek, System.Text.Decoder.GetChars(), System.L, System.IO.BinaryReader.m_charBytes, System.IO.BinaryReader.m_decoder, System.IO.BinaryReader.m_singleChar, System.IO.BinaryReader.m_stream, System.IO.Stream.Position, System.IO.Stream.ReadByte(), and System.IO.Stream.Seek().
Referenced by System.IO.BinaryReader.Read().