Terraria Decompiled: Terraria.GameContent.Biomes.GraniteBiome.BuildMagmaMap
BuildMagmaMap()
void Terraria.GameContent.Biomes.GraniteBiome.BuildMagmaMap (Point tileOrigin) inline private
Definition at line 41 of file GraniteBiome.cs.
        {
            this._sourceMagmaMap = new GraniteBiome.Magma[200, 200];
            this._targetMagmaMap = new GraniteBiome.Magma[200, 200];
            for (int i = 0; i < this._sourceMagmaMap.GetLength(0); i++)
            {
                for (int j = 0; j < this._sourceMagmaMap.GetLength(1); j++)
                {
                    int num = i + tileOrigin.X;
                    int num2 = j + tileOrigin.Y;
                    this._sourceMagmaMap[i, j] = GraniteBiome.Magma.CreateEmpty((double)(WorldGen.SolidTile(num, num2, false) ? 4 : 1));
                    this._targetMagmaMap[i, j] = this._sourceMagmaMap[i, j];
                }
            }
        }
References Terraria.GameContent.Biomes.GraniteBiome._sourceMagmaMap, Terraria.GameContent.Biomes.GraniteBiome._targetMagmaMap, Terraria.GameContent.Biomes.GraniteBiome.Magma.CreateEmpty(), Terraria.WorldGen.SolidTile(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.Biomes.GraniteBiome.Place().