Terraria Decompiled: Terraria.GameContent.Biomes.GraniteBiome.PlaceDecorations
PlaceDecorations()
void Terraria.GameContent.Biomes.GraniteBiome.PlaceDecorations (Point tileOrigin, Rectangle magmaMapArea) inline private
Definition at line 260 of file GraniteBiome.cs.
        {
            FastRandom fastRandom = new FastRandom(Main.ActiveWorldFileData.Seed).WithModifier(65440UL);
            for (int i = magmaMapArea.Left; i < magmaMapArea.Right; i++)
            {
                for (int j = magmaMapArea.Top; j < magmaMapArea.Bottom; j++)
                {
                    GraniteBiome.Magma magma = this._sourceMagmaMap[i, j];
                    int num = i + tileOrigin.X;
                    int num2 = j + tileOrigin.Y;
                    if (WorldGen.InWorld(num, num2, 10) && magma.IsActive)
                    {
                        WorldUtils.TileFrame(num, num2, false);
                        WorldGen.SquareWallFrame(num, num2, true);
                        FastRandom fastRandom2 = fastRandom.WithModifier(num, num2);
                        if (fastRandom2.Next(8) == 0 && GenBase._tiles[num, num2].active())
{
                            if (!GenBase._tiles[num, num2 + 1].active())
{
                                WorldGen.PlaceUncheckedStalactite(num, num2 + 1, fastRandom2.Next(2) == 0, fastRandom2.Next(3), false);
                            }
                            if (!GenBase._tiles[num, num2 - 1].active())
{
                                WorldGen.PlaceUncheckedStalactite(num, num2 - 1, fastRandom2.Next(2) == 0, fastRandom2.Next(3), false);
                            }
                        }
                        if (fastRandom2.Next(2) == 0)
{
                            Tile.SmoothSlope(num, num2, true, false);
                        }
                    }
                }
            }
        }
References Terraria.GameContent.Biomes.GraniteBiome._sourceMagmaMap, Terraria.WorldBuilding.GenBase._tiles, Terraria.Tile.active(), Terraria.Main.ActiveWorldFileData, Microsoft.Xna.Framework.Rectangle.Bottom, Terraria.WorldGen.InWorld(), Terraria.GameContent.Biomes.GraniteBiome.Magma.IsActive, Microsoft.Xna.Framework.Rectangle.Left, Terraria.Utilities.FastRandom.Next(), Terraria.WorldGen.PlaceUncheckedStalactite(), Microsoft.Xna.Framework.Rectangle.Right, Terraria.Tile.SmoothSlope(), Terraria.WorldGen.SquareWallFrame(), Terraria.WorldBuilding.WorldUtils.TileFrame(), Microsoft.Xna.Framework.Rectangle.Top, Terraria.Utilities.FastRandom.WithModifier(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.Biomes.GraniteBiome.Place().