Terraria Decompiled: Terraria.GameContent.Biomes.GraniteBiome.CleanupTiles
CleanupTiles()
void Terraria.GameContent.Biomes.GraniteBiome.CleanupTiles (Point tileOrigin, Rectangle magmaMapArea) inline private
Definition at line 212 of file GraniteBiome.cs.
        {
            ushort num = 180;
            if (WorldGen.drunkWorldGen)
            {
                num = 178;
            }
            List<Point16> list = new List<Point16>();
            for (int i = magmaMapArea.Left; i < magmaMapArea.Right; i++)
            {
                for (int j = magmaMapArea.Top; j < magmaMapArea.Bottom; j++)
                {
                    if (this._sourceMagmaMap[i, j].IsActive)
                    {
                        int num2 = 0;
                        int num3 = i + tileOrigin.X;
                        int num4 = j + tileOrigin.Y;
                        if (WorldGen.InWorld(num3, num4, 10) && WorldGen.SolidTile(num3, num4, false))
{
                            for (int k = -1; k <= 1; k++)
{
                                for (int l = -1; l <= 1; l++)
{
                                    if (WorldGen.SolidTile(num3 + k, num4 + l, false))
{
                                        num2++;
                                    }
                                }
                            }
                            if (num2 < 3)
{
                                list.Add(new Point16(num3, num4));
                            }
                        }
                    }
                }
            }
            foreach (Point16 point in list)
            {
                int x = (int)point.X;
                int y = (int)point.Y;
                WorldUtils.ClearTile(x, y, true);
                GenBase._tiles[x, y].wall = num;
            }
            list.Clear();
        }
References Terraria.GameContent.Biomes.GraniteBiome._sourceMagmaMap, Terraria.WorldBuilding.GenBase._tiles, Microsoft.Xna.Framework.Rectangle.Bottom, Terraria.WorldBuilding.WorldUtils.ClearTile(), Terraria.WorldGen.drunkWorldGen, int, Terraria.WorldGen.InWorld(), Microsoft.Xna.Framework.Rectangle.Left, System.list, Microsoft.Xna.Framework.Rectangle.Right, Terraria.WorldGen.SolidTile(), Microsoft.Xna.Framework.Rectangle.Top, Terraria.Tile.wall, Microsoft.Xna.Framework.Point.X, Terraria.DataStructures.Point16.X, Microsoft.Xna.Framework.Point.Y, and Terraria.DataStructures.Point16.Y.
Referenced by Terraria.GameContent.Biomes.GraniteBiome.Place().