Terraria Decompiled: Terraria.GameContent.Biomes.GraniteBiome.PlaceGranite
PlaceGranite()
void Terraria.GameContent.Biomes.GraniteBiome.PlaceGranite (Point tileOrigin, Rectangle magmaMapArea) inline private
Definition at line 162 of file GraniteBiome.cs.
        {
            bool flag = this.ShouldUseLava(tileOrigin);
            ushort num = 368;
            ushort num2 = 180;
            if (WorldGen.drunkWorldGen)
            {
                num = 367;
                num2 = 178;
            }
            for (int i = magmaMapArea.Left; i < magmaMapArea.Right; i++)
            {
                for (int j = magmaMapArea.Top; j < magmaMapArea.Bottom; j++)
                {
                    if (WorldGen.InWorld(tileOrigin.X + i, tileOrigin.Y + j, 10))
                    {
                        GraniteBiome.Magma magma = this._sourceMagmaMap[i, j];
                        if (magma.IsActive)
{
                            Tile tile = GenBase._tiles[tileOrigin.X + i, tileOrigin.Y + j];
                            double num3 = Math.Sin((double)(tileOrigin.Y + j) * 0.4) * 0.7 + 1.2;
                            double num4 = 0.2 + 0.5 / Math.Sqrt(Math.Max(0.0, magma.Pressure - magma.Resistance));
                            if (Math.Max(1.0 - Math.Max(0.0, num3 * num4), magma.Pressure / 15.0) > 0.35 + (WorldGen.SolidTile(tileOrigin.X + i, tileOrigin.Y + j, false) ? 0.0 : 0.5))
{
                                if (TileID.Sets.Ore[(int)tile.type])
{
                                    tile.ResetToType(tile.type);
                                }
                                else
{
                                    tile.ResetToType(num);
                                }
                                tile.wall = num2;
                            }
                            else if (magma.Resistance < 0.01)
{
                                WorldUtils.ClearTile(tileOrigin.X + i, tileOrigin.Y + j, false);
                                tile.wall = num2;
                            }
                            if (tile.liquid > 0 && flag)
{
                                tile.liquidType(1);
                            }
                        }
                    }
                }
            }
        }
References Terraria.GameContent.Biomes.GraniteBiome._sourceMagmaMap, Terraria.WorldBuilding.GenBase._tiles, Microsoft.Xna.Framework.Rectangle.Bottom, Terraria.WorldBuilding.WorldUtils.ClearTile(), Terraria.WorldGen.drunkWorldGen, Terraria.WorldGen.InWorld(), Terraria.GameContent.Biomes.GraniteBiome.Magma.IsActive, Microsoft.Xna.Framework.Rectangle.Left, Terraria.Tile.liquid, Terraria.Tile.liquidType(), System.Math.Max(), Terraria.ID.TileID.Sets.Ore, Terraria.GameContent.Biomes.GraniteBiome.Magma.Pressure, Terraria.Tile.ResetToType(), Terraria.GameContent.Biomes.GraniteBiome.Magma.Resistance, Microsoft.Xna.Framework.Rectangle.Right, Terraria.GameContent.Biomes.GraniteBiome.ShouldUseLava(), System.Math.Sin(), Terraria.WorldGen.SolidTile(), System.Math.Sqrt(), Microsoft.Xna.Framework.Rectangle.Top, Terraria.Tile.type, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.Biomes.GraniteBiome.Place().