Terraria Decompiled: Mono.Security.Uri.EscapeString
EscapeString() [2/2]
static string Mono.Security.Uri.EscapeString (string str, bool escapeReserved, bool escapeHex, bool escapeBrackets) inline static package
Definition at line 829 of file Uri.cs.
        {
            if (str == null)
            {
                return string.Empty;
            }
            StringBuilder stringBuilder = new StringBuilder();
            int length = str.Length;
            for (int i = 0; i < length; i++)
            {
                if (Uri.IsHexEncoding(str, i))
                {
                    stringBuilder.Append(str.Substring(i, 3));
                    i += 2;
                }
                else
                {
                    byte[] bytes = Encoding.UTF8.GetBytes(new char[] { str[i] });
                    int num = bytes.Length;
                    for (int j = 0; j < num; j++)
                    {
                        char c = (char)bytes[j];
                        if (c <= ' ' || c >= '\u007f' || "<>%\"{}|\\^`".IndexOf(c) != -1 || (escapeHex && c == '#') || (escapeBrackets && (c == '[' || c == ']')) || (escapeReserved && ";/?:@&=+$,".IndexOf(c) != -1))
{
                            stringBuilder.Append(Uri.HexEscape(c));
                        }
                        else
{
                            stringBuilder.Append(c);
                        }
                    }
                }
            }
            return stringBuilder.ToString();
        }
References System.Text.StringBuilder.Append(), System.Text.Encoding.GetBytes(), Mono.Security.Uri.HexEscape(), Mono.Security.Uri.IsHexEncoding(), System.length, System.Text.StringBuilder.ToString(), and System.Text.Encoding.UTF8.