Terraria Decompiled: Mono.Security.Uri.ToString
ToString()
override string Mono.Security.Uri.ToString () inline
Definition at line 805 of file Uri.cs.
        {
            if (this.cachedToString != null)
            {
                return this.cachedToString;
            }
            string text = (this.query.StartsWith("?") ? ("?" + this.Unescape(this.query.Substring(1))) : this.Unescape(this.query));
            this.cachedToString = this.Unescape(this.GetLeftPart(UriPartial.Path), true) + text + this.fragment;
            return this.cachedToString;
        }
References Mono.Security.Uri.cachedToString, Mono.Security.Uri.fragment, Mono.Security.Uri.GetLeftPart(), Mono.Security.Uri.query, System.text, and Mono.Security.Uri.Unescape().
Referenced by System.Security.Policy.ApplicationDirectoryMembershipCondition.Check(), Mono.Security.Uri.HexEscape(), Mono.Security.Uri.MakeRelative(), and System.Security.Policy.Url.Prepare().