Terraria Decompiled: Mono.Security.Uri.Parse
Parse() [2/2]
void Mono.Security.Uri.Parse (string uriString) inline private
Definition at line 976 of file Uri.cs.
        {
            if (uriString == null)
            {
                throw new ArgumentNullException("uriString");
            }
            if (uriString.Length <= 1)
            {
                throw new FormatException();
            }
            int num = uriString.IndexOf(':');
            if (num < 0)
            {
                if (uriString[0] == '/')
                {
                    this.ParseAsUnixAbsoluteFilePath(uriString);
                    return;
                }
                if (uriString.StartsWith("\\\\"))
                {
                    this.ParseAsWindowsUNC(uriString);
                    return;
                }
                throw new FormatException("URI scheme was not recognized, nor input string is not recognized as an absolute file path.");
            }
            else if (num == 1)
            {
                if (!char.IsLetter(uriString[0]))
                {
                    throw new FormatException("URI scheme must start with alphabet character.");
                }
                this.ParseAsWindowsAbsoluteFilePath(uriString);
                return;
            }
            else
            {
                this.scheme = uriString.Substring(0, num).ToLower(CultureInfo.InvariantCulture);
                if (!char.IsLetter(this.scheme[0]))
                {
                    throw new FormatException("URI scheme must start with alphabet character.");
                }
                for (int i = 1; i < this.scheme.Length; i++)
                {
                    if (!char.IsLetterOrDigit(this.scheme, i))
                    {
                        switch (this.scheme[i])
{
                        case '+':
                        case '-':
                        case '.':
                            break;
                        default:
                            throw new FormatException("URI scheme must consist of one of alphabet, digits, '+', '-' or '.' character.");
                        }
                    }
                }
                uriString = uriString.Substring(num + 1);
                num = uriString.IndexOf('#');
                if (!this.IsUnc && num != -1)
                {
                    this.fragment = uriString.Substring(num);
                    uriString = uriString.Substring(0, num);
                }
                num = uriString.IndexOf('?');
                if (num != -1)
                {
                    this.query = uriString.Substring(num);
                    uriString = uriString.Substring(0, num);
                    if (!this.userEscaped)
                    {
                        this.query = Uri.EscapeString(this.query);
                    }
                }
                bool flag = this.scheme == Uri.UriSchemeFile && uriString.StartsWith("///");
                if (uriString.StartsWith("//"))
                {
                    if (uriString.StartsWith("////"))
                    {
                        flag = false;
                    }
                    uriString = uriString.TrimStart(new char[] { '/' });
                    if (uriString.Length > 1 && uriString[1] == ':')
                    {
                        flag = false;
                    }
                }
                else if (!Uri.IsPredefinedScheme(this.scheme))
                {
                    this.path = uriString;
                    this.isOpaquePart = true;
                    return;
                }
                num = uriString.IndexOfAny(new char[] { '/', '\\' });
                if (flag)
                {
                    num = -1;
                }
                if (num == -1)
                {
                    if (this.scheme != Uri.UriSchemeMailto && this.scheme != Uri.UriSchemeNews && this.scheme != Uri.UriSchemeFile)
                    {
                        this.path = "/";
                    }
                }
                else
                {
                    this.path = uriString.Substring(num);
                    uriString = uriString.Substring(0, num);
                }
                num = uriString.IndexOf("@");
                if (flag)
                {
                    num = -1;
                }
                if (num != -1)
                {
                    this.userinfo = uriString.Substring(0, num);
                    uriString = uriString.Remove(0, num + 1);
                }
                this.port = -1;
                num = uriString.LastIndexOf(":");
                if (flag)
                {
                    num = -1;
                }
                if (num == 1 && this.scheme == Uri.UriSchemeFile && char.IsLetter(uriString[0]))
                {
                    num = -1;
                }
                if (num != -1 && num != uriString.Length - 1)
                {
                    string text = uriString.Remove(0, num + 1);
                    if (text.Length > 1 && text[text.Length - 1] != ']')
                    {
                        try
{
                            this.port = (int)uint.Parse(text, CultureInfo.InvariantCulture);
                            uriString = uriString.Substring(0, num);
                        }
                        catch (Exception)
{
                            throw new FormatException("Invalid URI: invalid port number");
                        }
                    }
                }
                if (this.port == -1)
                {
                    this.port = Uri.GetDefaultPort(this.scheme);
                }
                this.host = uriString;
                if (flag)
                {
                    this.path = "/" + uriString;
                    this.host = string.Empty;
                }
                else if (this.host.Length == 2 && this.host[1] == ':')
                {
                    this.path = this.host + this.path;
                    this.host = string.Empty;
                }
                else if (this.isUnixFilePath)
                {
                    uriString = "//" + uriString;
                    this.host = string.Empty;
                }
                else
                {
                    if (this.host.Length == 0)
                    {
                        throw new FormatException("Invalid URI: The hostname could not be parsed");
                    }
                    if (this.scheme == Uri.UriSchemeFile)
                    {
                        this.isUnc = true;
                    }
                }
                if (this.scheme != Uri.UriSchemeMailto && this.scheme != Uri.UriSchemeNews && this.scheme != Uri.UriSchemeFile && this.reduce)
                {
                    this.path = Uri.Reduce(this.path);
                }
                return;
            }
        }
References Mono.Security.Uri.EscapeString(), Mono.Security.Uri.GetDefaultPort(), Mono.Security.Uri.host, int, System.Globalization.CultureInfo.InvariantCulture, Mono.Security.Uri.IsPredefinedScheme(), Mono.Security.Uri.IsUnc, Mono.Security.Uri.isUnixFilePath, Mono.Security.Uri.ParseAsUnixAbsoluteFilePath(), Mono.Security.Uri.ParseAsWindowsAbsoluteFilePath(), Mono.Security.Uri.ParseAsWindowsUNC(), Mono.Security.Uri.path, Mono.Security.Uri.port, Mono.Security.Uri.query, Mono.Security.Uri.Reduce(), Mono.Security.Uri.scheme, System.text, Mono.Security.Uri.UriSchemeFile, Mono.Security.Uri.UriSchemeMailto, Mono.Security.Uri.UriSchemeNews, and Mono.Security.Uri.userEscaped.