Terraria Decompiled: Mono.Security.Uri.GetLeftPart
GetLeftPart()
string Mono.Security.Uri.GetLeftPart (UriPartial part) inline
Definition at line 599 of file Uri.cs.
        {
            switch (part)
            {
            case UriPartial.Scheme:
                return this.scheme + this.GetOpaqueWiseSchemeDelimiter();
            case UriPartial.Authority:
            {
                if (this.host == string.Empty || this.scheme == Uri.UriSchemeMailto || this.scheme == Uri.UriSchemeNews)
                {
                    return string.Empty;
                }
                StringBuilder stringBuilder = new StringBuilder();
                stringBuilder.Append(this.scheme);
                stringBuilder.Append(this.GetOpaqueWiseSchemeDelimiter());
                if (this.path.Length > 1 && this.path[1] == ':' && Uri.UriSchemeFile == this.scheme)
                {
                    stringBuilder.Append('/');
                }
                if (this.userinfo.Length > 0)
                {
                    stringBuilder.Append(this.userinfo).Append('@');
                }
                stringBuilder.Append(this.host);
                int num = Uri.GetDefaultPort(this.scheme);
                if (this.port != -1 && this.port != num)
                {
                    stringBuilder.Append(':').Append(this.port);
                }
                return stringBuilder.ToString();
            }
            case UriPartial.Path:
            {
                StringBuilder stringBuilder2 = new StringBuilder();
                stringBuilder2.Append(this.scheme);
                stringBuilder2.Append(this.GetOpaqueWiseSchemeDelimiter());
                if (this.path.Length > 1 && this.path[1] == ':' && Uri.UriSchemeFile == this.scheme)
                {
                    stringBuilder2.Append('/');
                }
                if (this.userinfo.Length > 0)
                {
                    stringBuilder2.Append(this.userinfo).Append('@');
                }
                stringBuilder2.Append(this.host);
                int num = Uri.GetDefaultPort(this.scheme);
                if (this.port != -1 && this.port != num)
                {
                    stringBuilder2.Append(':').Append(this.port);
                }
                stringBuilder2.Append(this.path);
                return stringBuilder2.ToString();
            }
            default:
                return null;
            }
        }
References System.Text.StringBuilder.Append(), Mono.Security.Uri.GetDefaultPort(), Mono.Security.Uri.GetOpaqueWiseSchemeDelimiter(), Mono.Security.Uri.host, Mono.Security.Uri.path, Mono.Security.Uri.port, Mono.Security.Uri.scheme, System.Text.StringBuilder.ToString(), Mono.Security.Uri.UriSchemeFile, Mono.Security.Uri.UriSchemeMailto, Mono.Security.Uri.UriSchemeNews, and Mono.Security.Uri.userinfo.
Referenced by Mono.Security.Uri.ToString().