Terraria Decompiled: Mono.Security.Uri.HexUnescape
HexUnescape()
static char Mono.Security.Uri.HexUnescape (string pattern, ref int index) inline static
Definition at line 686 of file Uri.cs.
        {
            if (pattern == null)
            {
                throw new ArgumentException("pattern");
            }
            if (index < 0 || index >= pattern.Length)
            {
                throw new ArgumentOutOfRangeException("index");
            }
            int num = 0;
            int num2 = 0;
            while (index + 3 <= pattern.Length && pattern[index] == '%' && Uri.IsHexDigit(pattern[index + 1]) && Uri.IsHexDigit(pattern[index + 2]))
            {
                index++;
                int num3 = index;
                index = num3 + 1;
                int num4 = Uri.FromHex(pattern[num3]);
                num3 = index;
                index = num3 + 1;
                int num5 = Uri.FromHex(pattern[num3]);
                int num6 = (num4 << 4) + num5;
                if (num == 0)
                {
                    if (num6 < 192)
                    {
                        return (char)num6;
                    }
                    if (num6 < 224)
                    {
                        num2 = num6 - 192;
                        num = 2;
                    }
                    else if (num6 < 240)
                    {
                        num2 = num6 - 224;
                        num = 3;
                    }
                    else if (num6 < 248)
                    {
                        num2 = num6 - 240;
                        num = 4;
                    }
                    else if (num6 < 251)
                    {
                        num2 = num6 - 248;
                        num = 5;
                    }
                    else if (num6 < 254)
                    {
                        num2 = num6 - 252;
                        num = 6;
                    }
                    num2 <<= (num - 1) * 6;
                }
                else
                {
                    num2 += num6 - 128 << (num - 1) * 6;
                }
                num--;
                if (num <= 0)
                {
                    IL_0154:
                    return (char)num2;
                }
            }
            if (num == 0)
            {
                int num3 = index;
                index = num3 + 1;
                return pattern[num3];
            }
            goto IL_0154;
        }
References Mono.Security.Uri.FromHex(), System.index, and Mono.Security.Uri.IsHexDigit().
Referenced by Mono.Security.Uri.Unescape().