Terraria Decompiled: Mono.Security.Uri.Parse
Parse() [1/2]
void Mono.Security.Uri.Parse () inline protected
Definition at line 866 of file Uri.cs.
        {
            this.Parse(this.source);
            if (this.userEscaped)
            {
                return;
            }
            this.host = Uri.EscapeString(this.host, false, true, false);
            this.path = Uri.EscapeString(this.path);
        }
References Mono.Security.Uri.EscapeString(), Mono.Security.Uri.host, Mono.Security.Uri.Parse(), Mono.Security.Uri.path, Mono.Security.Uri.source, and Mono.Security.Uri.userEscaped.
Referenced by Mono.Security.Uri.Parse(), Mono.Security.Uri.Uri(), Mono.Security.Uri.Uri(), and Mono.Security.Uri.Uri().