Terraria Decompiled: Microsoft.Xna.Framework.Graphics.EffectHelpers.SetLightingMatrices
SetLightingMatrices()
static EffectDirtyFlags Microsoft.Xna.Framework.Graphics.EffectHelpers.SetLightingMatrices (EffectDirtyFlags dirtyFlags, ref Matrix world, ref Matrix view, EffectParameter worldParam, EffectParameter worldInverseTransposeParam, EffectParameter eyePositionParam) inline static package
Definition at line 72 of file EffectHelpers.cs.
        {
            if ((dirtyFlags & EffectDirtyFlags.World) != (EffectDirtyFlags)0)
            {
                Matrix matrix;
                Matrix.Invert(ref world, out matrix);
                Matrix matrix2;
                Matrix.Transpose(ref matrix, out matrix2);
                worldParam.SetValue(world);
                worldInverseTransposeParam.SetValue(matrix2);
                dirtyFlags &= ~EffectDirtyFlags.World;
            }
            if ((dirtyFlags & EffectDirtyFlags.EyePosition) != (EffectDirtyFlags)0)
            {
                Matrix matrix3;
                Matrix.Invert(ref view, out matrix3);
                eyePositionParam.SetValue(matrix3.Translation);
                dirtyFlags &= ~EffectDirtyFlags.EyePosition;
            }
            return dirtyFlags;
        }
References Microsoft.Xna.Framework.Matrix.Invert(), Microsoft.Xna.Framework.Graphics.EffectParameter.SetValue(), Microsoft.Xna.Framework.Matrix.Translation, Microsoft.Xna.Framework.Matrix.Transpose(), and System.view.
Referenced by Microsoft.Xna.Framework.Graphics.BasicEffect.OnApply(), Microsoft.Xna.Framework.Graphics.EnvironmentMapEffect.OnApply(), and Microsoft.Xna.Framework.Graphics.SkinnedEffect.OnApply().