Terraria Decompiled: Microsoft.Xna.Framework.Graphics.EffectHelpers.SetMaterialColor
SetMaterialColor()
static void Microsoft.Xna.Framework.Graphics.EffectHelpers.SetMaterialColor (bool lightingEnabled, float alpha, ref Vector3 diffuseColor, ref Vector3 emissiveColor, ref Vector3 ambientLightColor, EffectParameter diffuseColorParam, EffectParameter emissiveColorParam) inline static package
Definition at line 95 of file EffectHelpers.cs.
        {
            if (lightingEnabled)
            {
                Vector4 vector = default(Vector4);
                Vector3 vector2 = default(Vector3);
                vector.X = diffuseColor.X * alpha;
                vector.Y = diffuseColor.Y * alpha;
                vector.Z = diffuseColor.Z * alpha;
                vector.W = alpha;
                vector2.X = (emissiveColor.X + ambientLightColor.X * diffuseColor.X) * alpha;
                vector2.Y = (emissiveColor.Y + ambientLightColor.Y * diffuseColor.Y) * alpha;
                vector2.Z = (emissiveColor.Z + ambientLightColor.Z * diffuseColor.Z) * alpha;
                diffuseColorParam.SetValue(vector);
                emissiveColorParam.SetValue(vector2);
                return;
            }
            diffuseColorParam.SetValue(new Vector4
            {
                X = (diffuseColor.X + emissiveColor.X) * alpha,
                Y = (diffuseColor.Y + emissiveColor.Y) * alpha,
                Z = (diffuseColor.Z + emissiveColor.Z) * alpha,
                W = alpha
            });
        }
References Microsoft.Xna.Framework.Graphics.EffectParameter.SetValue(), System.W, System.X, System.Y, and System.Z.
Referenced by Microsoft.Xna.Framework.Graphics.BasicEffect.OnApply(), Microsoft.Xna.Framework.Graphics.EnvironmentMapEffect.OnApply(), and Microsoft.Xna.Framework.Graphics.SkinnedEffect.OnApply().