Terraria Decompiled: Microsoft.Xna.Framework.Graphics.EffectHelpers.EnableDefaultLighting
EnableDefaultLighting()
static Vector3 Microsoft.Xna.Framework.Graphics.EffectHelpers.EnableDefaultLighting (DirectionalLight light0, DirectionalLight light1, DirectionalLight light2) inline static package
Definition at line 9 of file EffectHelpers.cs.
        {
            light0.Direction = new Vector3(-0.5265408f, -0.5735765f, -0.6275069f);
            light0.DiffuseColor = new Vector3(1f, 0.9607844f, 0.8078432f);
            light0.SpecularColor = new Vector3(1f, 0.9607844f, 0.8078432f);
            light0.Enabled = true;
            light1.Direction = new Vector3(0.7198464f, 0.3420201f, 0.6040227f);
            light1.DiffuseColor = new Vector3(0.9647059f, 0.7607844f, 0.4078432f);
            light1.SpecularColor = Vector3.Zero;
            light1.Enabled = true;
            light2.Direction = new Vector3(0.4545195f, -0.7660444f, 0.4545195f);
            light2.DiffuseColor = new Vector3(0.3231373f, 0.3607844f, 0.3937255f);
            light2.SpecularColor = new Vector3(0.3231373f, 0.3607844f, 0.3937255f);
            light2.Enabled = true;
            return new Vector3(0.05333332f, 0.09882354f, 0.1819608f);
        }
References Microsoft.Xna.Framework.Graphics.Vector3, and Microsoft.Xna.Framework.Vector3.Zero.
Referenced by Microsoft.Xna.Framework.Graphics.BasicEffect.EnableDefaultLighting(), Microsoft.Xna.Framework.Graphics.EnvironmentMapEffect.EnableDefaultLighting(), and Microsoft.Xna.Framework.Graphics.SkinnedEffect.EnableDefaultLighting().