Terraria Decompiled: Terraria.Chat.Commands.EmojiCommand.ProcessOutgoingMessage
ProcessOutgoingMessage()
void Terraria.Chat.Commands.EmojiCommand.ProcessOutgoingMessage (ChatMessage message) inline
Implements Terraria.Chat.Commands.IChatCommand.
Definition at line 49 of file EmojiCommand.cs.
        {
            if (Main.netMode != 2 && Main.LocalPlayer.dead)
            {
                message.Consume();
                return;
            }
            int num = -1;
            if (int.TryParse(message.Text, out num))
            {
                if (num < 0 || num >= EmoteID.Count)
                {
                    return;
                }
            }
            else
            {
                num = -1;
            }
            if (num == -1)
            {
                foreach (LocalizedText localizedText in this._byName.Keys)
                {
                    if (localizedText.EqualsCommand(message.Text))
                    {
                        num = this._byName[localizedText];
                        break;
                    }
                }
            }
            if (num != -1)
            {
                if (Main.netMode == 0)
                {
                    EmoteBubble.NewBubble(num, new WorldUIAnchor(Main.LocalPlayer), 360);
                    EmoteBubble.CheckForNPCsToReactToEmoteBubble(num, Main.LocalPlayer);
                }
                else
                {
                    NetMessage.SendData(120, -1, -1, null, Main.myPlayer, (float)num, 0f, 0f, 0, 0, 0);
                }
            }
            message.Consume();
        }
References Terraria.Chat.Commands.EmojiCommand._byName, Terraria.GameContent.UI.EmoteBubble.CheckForNPCsToReactToEmoteBubble(), Terraria.Chat.ChatMessage.Consume(), Terraria.GameContent.UI.EmoteID.Count, Terraria.Player.dead, Terraria.Localization.LocalizedText.EqualsCommand(), System.Collections.Generic.Dictionary< TKey, TValue >.Keys, Terraria.Main.LocalPlayer, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.GameContent.UI.EmoteBubble.NewBubble(), Terraria.NetMessage.SendData(), and Terraria.Chat.ChatMessage.Text.