Terraria Decompiled: System.Security.Cryptography.DES.IsSemiWeakKey
IsSemiWeakKey()
static bool System.Security.Cryptography.DES.IsSemiWeakKey (byte[] rgbKey) inline static
Definition at line 84 of file DES.cs.
        {
            if (!DES.IsLegalKeySize(rgbKey))
            {
                throw new CryptographicException(Environment.GetResourceString("Specified key is not a valid size for this algorithm."));
            }
            ulong num = DES.QuadWordFromBigEndian(Utils.FixupKeyParity(rgbKey));
            return num == 143554428589179390UL || num == 18303189645120372225UL || num == 2296870857142767345UL || num == 16149873216566784270UL || num == 135110050437988849UL || num == 16141428838415593729UL || num == 2305315235293957886UL || num == 18311634023271562766UL || num == 80784550989267214UL || num == 2234100979542855169UL || num == 16212643094166696446UL || num == 18365959522720284401UL;
        }
References System.Security.Cryptography.Utils.FixupKeyParity(), System.Environment.GetResourceString(), System.Security.Cryptography.DES.IsLegalKeySize(), and System.Security.Cryptography.DES.QuadWordFromBigEndian().
Referenced by System.Security.Cryptography.DESCryptoServiceProvider.CreateDecryptor(), System.Security.Cryptography.DESCryptoServiceProvider.CreateEncryptor(), System.Security.Cryptography.DESTransform.DESTransform(), System.Security.Cryptography.DESCryptoServiceProvider.GenerateKey(), and System.Security.Cryptography.DESTransform.GetStrongKey().