Terraria Decompiled: Terraria.GameContent.Tile_Entities.TEWeaponsRack.TryPlacing
TryPlacing()
static void Terraria.GameContent.Tile_Entities.TEWeaponsRack.TryPlacing (int x, int y, int type, int prefix, int stack) inline static
Definition at line 147 of file TEWeaponsRack.cs.
        {
            WorldGen.RangeFrame(x, y, x + 3, y + 3);
            TEWeaponsRack teweaponsRack;
            if (!TileEntity.TryGetAt<TEWeaponsRack>(x, y, out teweaponsRack))
            {
                int num = Item.NewItem(new EntitySource_TileBreak(x, y), x * 16, y * 16, 32, 32, 1, 1, false, 0, false);
                Main.item[num].SetDefaults(type);
                Main.item[num].Prefix(prefix);
                Main.item[num].stack = stack;
                NetMessage.SendData(21, -1, -1, null, num, 0f, 0f, 0f, 0, 0, 0);
                return;
            }
            if (teweaponsRack.item.stack > 0)
            {
                teweaponsRack.DropItem();
            }
            teweaponsRack.item = new Item();
            teweaponsRack.item.SetDefaults(type, null);
            teweaponsRack.item.Prefix(prefix);
            teweaponsRack.item.stack = stack;
            NetMessage.SendData(86, -1, -1, null, teweaponsRack.ID, (float)x, (float)y, 0f, 0, 0, 0);
        }
References Terraria.GameContent.Tile_Entities.TEWeaponsRack.DropItem(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.item, Terraria.Main.item, Terraria.Item.NewItem(), Terraria.WorldItem.Prefix(), Terraria.Item.Prefix(), Terraria.WorldGen.RangeFrame(), Terraria.NetMessage.SendData(), Terraria.WorldItem.SetDefaults(), Terraria.Item.SetDefaults(), System.stack, Terraria.Item.stack, and Terraria.WorldItem.stack.
Referenced by Terraria.IO.WorldFile.ConvertOldTileEntities(), and Terraria.GameContent.Tile_Entities.TEWeaponsRack.PlaceItemInFrame().