Terraria Decompiled: Terraria.GameContent.Tile_Entities.TEWeaponsRack.DropItem
DropItem()
void Terraria.GameContent.Tile_Entities.TEWeaponsRack.DropItem () inline
Definition at line 137 of file TEWeaponsRack.cs.
        {
            if (Main.netMode != 1)
            {
                Item.NewItem(new EntitySource_TileBreak((int)this.Position.X, (int)this.Position.Y), (int)(this.Position.X * 16), (int)(this.Position.Y * 16), 32, 32, this.item.type, 1, false, (int)this.item.prefix, false);
            }
            this.item = new Item();
        }
References Terraria.Main.netMode, and Terraria.Item.NewItem().
Referenced by Terraria.WorldGen.CheckWeaponsRack(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.Framing_CheckTile(), Terraria.WorldGen.KillTile(), and Terraria.GameContent.Tile_Entities.TEWeaponsRack.TryPlacing().