Terraria Decompiled: Microsoft.Xna.Framework.Media.VideoPlayer.Play
Play()
void Microsoft.Xna.Framework.Media.VideoPlayer.Play (Video video) inline
Definition at line 176 of file VideoPlayer.cs.
        {
            this.checkDisposed();
            if (this.impl != null)
            {
                this.impl.Dispose();
                this.impl = null;
            }
            this.impl = VideoPlayer.codecPlayers[video.Codec]();
            this.impl.IsLooped = this.IsLooped;
            this.impl.IsMuted = this.IsMuted;
            this.impl.Volume = this.Volume;
            this.impl.Play(video);
        }
References Microsoft.Xna.Framework.Media.VideoPlayer.checkDisposed(), Microsoft.Xna.Framework.Media.Video.Codec, Microsoft.Xna.Framework.Media.VideoPlayer.codecPlayers, System.IDisposable.Dispose(), Microsoft.Xna.Framework.Media.VideoPlayer.impl, Microsoft.Xna.Framework.Media.VideoPlayer.IsLooped, Microsoft.Xna.Framework.Media.VideoPlayer.IsMuted, Microsoft.Xna.Framework.Media.IVideoPlayerCodec.Play(), and Microsoft.Xna.Framework.Media.VideoPlayer.Volume.