Terraria Decompiled: Terraria.Social.WeGame.NetServerSocialModule.OnPacketRead
OnPacketRead()
bool Terraria.Social.WeGame.NetServerSocialModule.OnPacketRead (byte[] data, int size, RailID user) inline private
Definition at line 251 of file NetServerSocialModule.cs.
        {
            if (!this.IsActiveUser(user))
            {
                WeGameHelper.WriteDebugString("OnPacketRead IsActiveUser false", new object[0]);
                return false;
            }
            NetSocialModule.ConnectionState connectionState = this._connectionStateMap[user];
            if (connectionState == NetSocialModule.ConnectionState.Authenticating)
            {
                if (!this.TryAuthUserByRecvData(user, data, size))
                {
                    this.CloseAndUpdateUserState(user);
                }
                else
                {
                    this.OnAuthSuccess(user);
                }
                return false;
            }
            return connectionState == NetSocialModule.ConnectionState.Connected;
        }
References Terraria.Social.WeGame.NetSocialModule._connectionStateMap, Terraria.Social.WeGame.NetServerSocialModule.CloseAndUpdateUserState(), Terraria.Social.WeGame.NetServerSocialModule.IsActiveUser(), Terraria.Social.WeGame.NetServerSocialModule.OnAuthSuccess(), Terraria.Social.WeGame.NetServerSocialModule.TryAuthUserByRecvData(), and Terraria.Social.WeGame.WeGameHelper.WriteDebugString().