Terraria Decompiled: Terraria.Social.WeGame.NetServerSocialModule.CloseNetWorkSession
CloseNetWorkSession()
bool Terraria.Social.WeGame.NetServerSocialModule.CloseNetWorkSession (RailID remote_peer) inline private
Definition at line 51 of file NetServerSocialModule.cs.
        {
            bool flag = false;
            IRailNetwork railNetwork = rail_api.RailFactory().RailNetworkHelper();
            if (railNetwork != null)
            {
                flag = railNetwork.CloseSession(this._serverID, remote_peer) == 0;
            }
            return flag;
        }
References Terraria.Social.WeGame.NetServerSocialModule._serverID, rail.IRailNetwork.CloseSession(), rail.rail_api.RailFactory(), and rail.IRailFactory.RailNetworkHelper().
Referenced by Terraria.Social.WeGame.NetServerSocialModule.CloseAndUpdateUserState().