Terraria Decompiled: Terraria.Social.WeGame.NetServerSocialModule.Initialize
Initialize()
override void Terraria.Social.WeGame.NetServerSocialModule.Initialize () inline
Definition at line 347 of file NetServerSocialModule.cs.
        {
            base.Initialize();
            this._mode |= ServerMode.Lobby;
            this.RegisterRailEvent();
            this._reader.SetReadEvent(new WeGameP2PReader.OnReadEvent(this.OnPacketRead));
            if (Program.LaunchParameters.ContainsKey("-lobby"))
            {
                this._mode |= ServerMode.Lobby;
                string text = Program.LaunchParameters["-lobby"];
                if (!(text == "private"))
                {
                    if (!(text == "friends"))
                    {
                        Console.WriteLine(Language.GetTextValue("Error.InvalidLobbyFlag", "private", "friends"));
                    }
                    else
                    {
                        this._mode |= ServerMode.FriendsCanJoin;
                        this._lobby.Create(false);
                    }
                }
                else
                {
                    this._lobby.Create(true);
                }
            }
            if (Program.LaunchParameters.ContainsKey("-friendsoffriends"))
            {
                this._mode |= ServerMode.FriendsOfFriends;
            }
            this._client.Init("WeGame.Terraria.Message.Client", "WeGame.Terraria.Message.Server");
            this._client.OnConnected += this.OnConnected;
            this._client.OnMessage += this.OnWegameMessage;
            CoreSocialModule.OnTick += this._client.Tick;
            this._client.Start();
        }
References Terraria.Social.WeGame.NetServerSocialModule._client, Terraria.Social.WeGame.NetSocialModule._lobby, Terraria.Social.WeGame.NetSocialModule._reader, System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), Terraria.Social.WeGame.Lobby.Create(), Terraria.Localization.Language.GetTextValue(), Terraria.Social.WeGame.MessageDispatcherClient.Init(), Terraria.Program.LaunchParameters, Terraria.Social.WeGame.NetServerSocialModule.OnConnected(), Terraria.Social.WeGame.WeGameP2PReader.OnReadEvent(), Terraria.Social.WeGame.NetServerSocialModule.OnWegameMessage(), Terraria.Social.WeGame.NetServerSocialModule.RegisterRailEvent(), Terraria.Social.WeGame.WeGameP2PReader.SetReadEvent(), Terraria.Social.WeGame.MessageDispatcherClient.Start(), System.text, Terraria.Social.WeGame.MessageDispatcherClient.Tick(), and System.Console.WriteLine().