Terraria Decompiled: Terraria.Social.WeGame.NetServerSocialModule.GetRailFriendList
GetRailFriendList()
bool Terraria.Social.WeGame.NetServerSocialModule.GetRailFriendList (List< RailFriendInfo > list) inline private
Definition at line 135 of file NetServerSocialModule.cs.
        {
            bool flag = false;
            IRailFriends railFriends = rail_api.RailFactory().RailFriends();
            if (railFriends != null)
            {
                flag = railFriends.GetFriendsList(list) == 0;
            }
            return flag;
        }
References rail.IRailFriends.GetFriendsList(), System.list, rail.rail_api.RailFactory(), and rail.IRailFactory.RailFriends().