Terraria Decompiled: Terraria.Social.WeGame.NetServerSocialModule.OnCreateSessionRequest
OnCreateSessionRequest()
void Terraria.Social.WeGame.NetServerSocialModule.OnCreateSessionRequest (CreateSessionRequest data) inline private
Definition at line 102 of file NetServerSocialModule.cs.
        {
            if (!this._acceptingClients)
            {
                WeGameHelper.WriteDebugString(" - Ignoring connection from " + data.remote_peer.id_ + " while _acceptionClients is false.", new object[0]);
                return;
            }
            if ((this._mode & ServerMode.FriendsOfFriends) == ServerMode.None && !this.IsWeGameFriend(data.remote_peer))
            {
                WeGameHelper.WriteDebugString("Ignoring connection from " + data.remote_peer.id_ + ". Friends of friends is disabled.", new object[0]);
                return;
            }
            WeGameHelper.WriteDebugString("pass wegame friend check", new object[0]);
            this.AcceptAnUserSession(data.local_peer, data.remote_peer);
            this._connectionStateMap[data.remote_peer] = NetSocialModule.ConnectionState.Authenticating;
            if (this._connectionAcceptedCallback != null)
            {
                this._connectionAcceptedCallback(new SocialSocket(new WeGameAddress(data.remote_peer, "")));
            }
        }
References Terraria.Social.WeGame.NetServerSocialModule._acceptingClients, Terraria.Social.WeGame.NetServerSocialModule._connectionAcceptedCallback, Terraria.Social.WeGame.NetSocialModule._connectionStateMap, Terraria.Social.WeGame.NetServerSocialModule._mode, Terraria.Social.WeGame.NetServerSocialModule.AcceptAnUserSession(), rail.RailComparableID.id_, rail.CreateSessionRequest.local_peer, rail.CreateSessionRequest.remote_peer, and Terraria.Social.WeGame.WeGameHelper.WriteDebugString().
Referenced by Terraria.Social.WeGame.NetServerSocialModule.OnRailEvent().