Terraria Decompiled: Terraria.Social.WeGame.NetServerSocialModule.CloseAndUpdateUserState
CloseAndUpdateUserState()
void Terraria.Social.WeGame.NetServerSocialModule.CloseAndUpdateUserState (RailID remote_peer) inline private
Definition at line 75 of file NetServerSocialModule.cs.
        {
            if (!this._connectionStateMap.ContainsKey(remote_peer))
            {
                return;
            }
            WeGameHelper.WriteDebugString("CloseAndUpdateUserState, remote:{0}", new object[] { remote_peer.id_ });
            this.TerminateRemotePlayerSession(remote_peer);
            this.CloseNetWorkSession(remote_peer);
            this._connectionStateMap[remote_peer] = NetSocialModule.ConnectionState.Inactive;
            this._reader.ClearUser(remote_peer);
            this._writer.ClearUser(remote_peer);
        }
References Terraria.Social.WeGame.NetSocialModule._connectionStateMap, Terraria.Social.WeGame.NetSocialModule._reader, Terraria.Social.WeGame.NetSocialModule._writer, Terraria.Social.WeGame.WeGameP2PReader.ClearUser(), Terraria.Social.WeGame.WeGameP2PWriter.ClearUser(), Terraria.Social.WeGame.NetServerSocialModule.CloseNetWorkSession(), Terraria.Social.WeGame.NetServerSocialModule.TerminateRemotePlayerSession(), and Terraria.Social.WeGame.WeGameHelper.WriteDebugString().
Referenced by Terraria.Social.WeGame.NetServerSocialModule.Close(), Terraria.Social.WeGame.NetServerSocialModule.OnCreateSessionFailed(), Terraria.Social.WeGame.NetServerSocialModule.OnPacketRead(), and Terraria.Social.WeGame.NetServerSocialModule.UpdateUserStateBySessionAuthResult().