Terraria Decompiled: Terraria.Social.WeGame.NetServerSocialModule.OnCreateSessionFailed
OnCreateSessionFailed()
void Terraria.Social.WeGame.NetServerSocialModule.OnCreateSessionFailed (CreateSessionFailed data) inline private
Definition at line 124 of file NetServerSocialModule.cs.
        {
            WeGameHelper.WriteDebugString("CreateSessionFailed, local:{0}, remote:{1}", new object[]
            {
                data.local_peer.id_,
                data.remote_peer.id_
            });
            this.CloseAndUpdateUserState(data.remote_peer);
        }
References Terraria.Social.WeGame.NetServerSocialModule.CloseAndUpdateUserState(), rail.RailComparableID.id_, rail.CreateSessionFailed.local_peer, rail.CreateSessionFailed.remote_peer, and Terraria.Social.WeGame.WeGameHelper.WriteDebugString().
Referenced by Terraria.Social.WeGame.NetServerSocialModule.OnRailEvent().