Terraria Decompiled: Terraria.Social.WeGame.NetServerSocialModule.OnLobbyCreated
OnLobbyCreated()
void Terraria.Social.WeGame.NetServerSocialModule.OnLobbyCreated (RailID lobbyID) inline private
Definition at line 312 of file NetServerSocialModule.cs.
        {
            WeGameHelper.WriteDebugString("SetLocalPeer: {0}", new object[] { lobbyID.id_ });
            this._reader.SetLocalPeer(lobbyID);
            this._writer.SetLocalPeer(lobbyID);
            this._serverID = lobbyID;
            Action action = delegate
            {
                ReportServerID reportServerID = new ReportServerID
                {
                    _serverID = lobbyID.id_.ToString()
                };
                IPCMessage ipcmessage = new IPCMessage();
                ipcmessage.Build<ReportServerID>(IPCMessageType.IPCMessageTypeReportServerID, reportServerID);
                WeGameHelper.WriteDebugString("Send serverID to game client - " + this._client.SendMessage(ipcmessage).ToString(), new object[0]);
            };
            if (this._serverConnected)
            {
                action();
                return;
            }
            this._ipcConnetedAction = (Action)Delegate.Combine(this._ipcConnetedAction, action);
            WeGameHelper.WriteDebugString("report server id fail, no connection", new object[0]);
        }
References Terraria.Social.WeGame.NetServerSocialModule._client, Terraria.Social.WeGame.NetSocialModule._reader, Terraria.Social.WeGame.NetServerSocialModule._serverConnected, Terraria.Social.WeGame.NetServerSocialModule._serverID, Terraria.Social.WeGame.NetSocialModule._writer, System.Action(), System.action, System.Delegate.Combine(), rail.RailComparableID.id_, Terraria.Social.WeGame.MessageDispatcherClient.SendMessage(), Terraria.Social.WeGame.WeGameP2PReader.SetLocalPeer(), Terraria.Social.WeGame.WeGameP2PWriter.SetLocalPeer(), and Terraria.Social.WeGame.WeGameHelper.WriteDebugString().
Referenced by Terraria.Social.WeGame.NetServerSocialModule.NetServerSocialModule().