Terraria Decompiled: Terraria.Social.WeGame.NetServerSocialModule.OnAuthSuccess
OnAuthSuccess()
void Terraria.Social.WeGame.NetServerSocialModule.OnAuthSuccess (RailID remote_peer) inline private
Definition at line 275 of file NetServerSocialModule.cs.
        {
            if (!this._connectionStateMap.ContainsKey(remote_peer))
            {
                return;
            }
            this._connectionStateMap[remote_peer] = NetSocialModule.ConnectionState.Connected;
            int num = 3;
            byte[] array = new byte[num];
            array[0] = (byte)(num & 255);
            array[1] = (byte)((num >> 8) & 255);
            array[2] = 93;
            rail_api.RailFactory().RailNetworkHelper().SendReliableData(this._serverID, remote_peer, array, (uint)num);
        }
References Terraria.Social.WeGame.NetSocialModule._connectionStateMap, Terraria.Social.WeGame.NetServerSocialModule._serverID, System.array, rail.rail_api.RailFactory(), rail.IRailFactory.RailNetworkHelper(), and rail.IRailNetwork.SendReliableData().
Referenced by Terraria.Social.WeGame.NetServerSocialModule.OnPacketRead().