Terraria Decompiled: Terraria.Social.WeGame.NetServerSocialModule.AcceptAnUserSession
AcceptAnUserSession()
bool Terraria.Social.WeGame.NetServerSocialModule.AcceptAnUserSession (RailID local_peer, RailID remote_peer) inline private
Definition at line 28 of file NetServerSocialModule.cs.
        {
            bool flag = false;
            WeGameHelper.WriteDebugString("AcceptAnUserSession server:" + local_peer.id_.ToString() + " remote:" + remote_peer.id_.ToString(), new object[0]);
            IRailNetwork railNetwork = rail_api.RailFactory().RailNetworkHelper();
            if (railNetwork != null)
            {
                flag = railNetwork.AcceptSessionRequest(local_peer, remote_peer) == 0;
            }
            return flag;
        }
References rail.IRailNetwork.AcceptSessionRequest(), rail.RailComparableID.id_, rail.rail_api.RailFactory(), rail.IRailFactory.RailNetworkHelper(), and Terraria.Social.WeGame.WeGameHelper.WriteDebugString().
Referenced by Terraria.Social.WeGame.NetServerSocialModule.OnCreateSessionRequest().