Terraria Decompiled: Terraria.IO.Preferences.Save
Save()
bool Terraria.IO.Preferences.Save (bool canCreateFile = true) inline
Definition at line 188 of file Preferences.cs.
        {
            object @lock = this._lock;
            bool flag2;
            lock (@lock)
            {
                try
                {
                    if (this.OnSave != null)
                    {
                        this.OnSave(this);
                    }
                    if (!canCreateFile && !File.Exists(this._path))
                    {
                        return false;
                    }
                    Directory.GetParent(this._path).Create();
                    if (File.Exists(this._path))
                    {
                        File.SetAttributes(this._path, FileAttributes.Normal);
                    }
                    if (!this.UseBson)
                    {
                        string text = JsonConvert.SerializeObject(this._data, this._serializerSettings);
                        if (this.OnProcessText != null)
{
                            this.OnProcessText(ref text);
                        }
                        File.WriteAllText(this._path, text);
                        File.SetAttributes(this._path, FileAttributes.Normal);
                    }
                    else
                    {
                        using (FileStream fileStream = File.Create(this._path))
{
                            using (BsonWriter bsonWriter = new BsonWriter(fileStream))
{
                                File.SetAttributes(this._path, FileAttributes.Normal);
                                JsonSerializer.Create(this._serializerSettings).Serialize(bsonWriter, this._data);
                            }
                        }
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine(Language.GetTextValue("Error.UnableToWritePreferences", this._path));
                    Console.WriteLine(ex.ToString());
                    return false;
                }
                flag2 = true;
            }
            return flag2;
        }
References Terraria.IO.Preferences._data, Terraria.IO.Preferences._lock, Terraria.IO.Preferences._path, Terraria.IO.Preferences._serializerSettings, System.IO.DirectoryInfo.Create(), Newtonsoft.Json.JsonSerializer.Create(), System.IO.File.Create(), System.IO.File.Exists(), System.IO.Directory.GetParent(), Terraria.Localization.Language.GetTextValue(), Terraria.IO.Preferences.OnProcessText, Terraria.IO.Preferences.OnSave, Newtonsoft.Json.JsonSerializer.Serialize(), Newtonsoft.Json.JsonConvert.SerializeObject(), System.IO.File.SetAttributes(), System.text, System.Exception.ToString(), Terraria.IO.Preferences.UseBson, System.IO.File.WriteAllText(), and System.Console.WriteLine().
Referenced by Terraria.IO.Preferences.Put(), Terraria.Main.SaveSettings(), and Terraria.Main.TryPickingDefaultUIScale().