Terraria Decompiled: Terraria.IO.Preferences.Get< T >
Get< T >() [2/2]
T Terraria.IO.Preferences.Get< T > (string name, T defaultValue) inline
Definition at line 275 of file Preferences.cs.
        {
            object @lock = this._lock;
            T t;
            lock (@lock)
            {
                try
                {
                    object obj;
                    if (this._data.TryGetValue(name, out obj))
                    {
                        if (obj is T)
{
                            t = (T)((object)obj);
                        }
                        else if (obj is JObject)
{
                            t = JsonConvert.DeserializeObject<T>(((JObject)obj).ToString());
                        }
                        else if (typeof(T).IsEnum)
{
                            t = (T)((object)Convert.ChangeType(obj, Enum.GetUnderlyingType(typeof(T))));
                        }
                        else
{
                            t = (T)((object)Convert.ChangeType(obj, typeof(T)));
                        }
                    }
                    else
                    {
                        t = defaultValue;
                    }
                }
                catch
                {
                    t = defaultValue;
                }
            }
            return t;
        }
References Terraria.IO.Preferences._data, Terraria.IO.Preferences._lock, System.Convert.ChangeType(), Newtonsoft.Json.JsonConvert.DeserializeObject(), System.Enum.GetUnderlyingType(), System.obj, System.T, and System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue().
Referenced by Terraria.IO.Preferences.Get< T >().