Terraria Decompiled: System.DateTimeOffset.Parse
Parse() [1/4]
static DateTimeOffset System.DateTimeOffset.Parse (ReadOnlySpan< char > input, IFormatProvider formatProvider = null, DateTimeStyles styles = DateTimeStyles::None) inline static
Definition at line 508 of file DateTimeOffset.cs.
        {
            styles = DateTimeOffset.ValidateStyles(styles, "styles");
            TimeSpan timeSpan;
            return new DateTimeOffset(DateTimeParse.Parse(input, DateTimeFormatInfo.GetInstance(formatProvider), styles, out timeSpan).Ticks, timeSpan);
        }
References System.DateTimeOffset.DateTimeOffset(), System.Globalization.DateTimeFormatInfo.GetInstance(), System.input, System.DateTimeParse.Parse(), System.DateTime.Ticks, and System.DateTimeOffset.ValidateStyles().