Terraria Decompiled: System.DateTimeOffset.ValidateOffset
ValidateOffset()
static short System.DateTimeOffset.ValidateOffset (TimeSpan offset) inline static private
Definition at line 753 of file DateTimeOffset.cs.
        {
            long ticks = offset.Ticks;
            if (ticks % 600000000L != 0L)
            {
                throw new ArgumentException("Offset must be specified in whole minutes.", "offset");
            }
            if (ticks < -504000000000L || ticks > 504000000000L)
            {
                throw new ArgumentOutOfRangeException("offset", "Offset must be within plus or minus 14 hours.");
            }
            return (short)(offset.Ticks / 600000000L);
        }
References System.L, and System.offset.
Referenced by System.DateTimeOffset.DateTimeOffset(), System.DateTimeOffset.DateTimeOffset(), System.DateTimeOffset.DateTimeOffset(), System.DateTimeOffset.DateTimeOffset(), System.DateTimeOffset.DateTimeOffset(), System.DateTimeOffset.DateTimeOffset(), and System.DateTimeOffset.OnDeserialization().