Terraria Decompiled: System.Security.Util.Parser.ParseContents
ParseContents()
void System.Security.Util.Parser.ParseContents () inline private
Definition at line 311 of file Parser.cs.
        {
            TokenizerStream tokenizerStream = new TokenizerStream();
            this._t.GetTokens(tokenizerStream, 2, false);
            tokenizerStream.Reset();
            int num = this.DetermineFormat(tokenizerStream);
            tokenizerStream.GoToPosition(num);
            this._t.GetTokens(tokenizerStream, -1, false);
            tokenizerStream.Reset();
            int num2 = 0;
            this.GetRequiredSizes(tokenizerStream, ref num2);
            this._doc = new SecurityDocument(num2);
            int num3 = 0;
            tokenizerStream.Reset();
            for (short num4 = tokenizerStream.GetNextFullToken(); num4 != -1; num4 = tokenizerStream.GetNextFullToken())
            {
                if ((num4 & 16384) == 16384)
                {
                    short num5 = (short)((int)num4 & 65280);
                    if (num5 <= 17152)
                    {
                        if (num5 == 16640)
{
                            this._doc.AddToken(1, ref num3);
                            this._doc.AddString(tokenizerStream.GetNextString(), ref num3);
                            goto IL_019D;
                        }
                        if (num5 == 16896)
{
                            this._doc.AddToken(2, ref num3);
                            this._doc.AddString(tokenizerStream.GetNextString(), ref num3);
                            this._doc.AddString(tokenizerStream.GetNextString(), ref num3);
                            goto IL_019D;
                        }
                        if (num5 == 17152)
{
                            this._doc.AddToken(3, ref num3);
                            this._doc.AddString(tokenizerStream.GetNextString(), ref num3);
                            goto IL_019D;
                        }
                    }
                    else
                    {
                        if (num5 == 17408)
{
                            this._doc.AddToken(4, ref num3);
                            goto IL_019D;
                        }
                        if (num5 == 20480)
{
                            tokenizerStream.ThrowAwayNextString();
                            goto IL_019D;
                        }
                        if (num5 == 25344)
{
                            this._doc.AppendString(" ", ref num3);
                            this._doc.AppendString(tokenizerStream.GetNextString(), ref num3);
                            goto IL_019D;
                        }
                    }
                    throw new XmlSyntaxException();
                }
                IL_019D:;
            }
        }
References System.Security.Util.Parser._doc, System.Security.Util.Parser._t, System.Security.SecurityDocument.AddString(), System.Security.SecurityDocument.AddToken(), System.Security.SecurityDocument.AppendString(), System.Security.Util.Parser.DetermineFormat(), System.Security.Util.TokenizerStream.GetNextFullToken(), System.Security.Util.TokenizerStream.GetNextString(), System.Security.Util.Parser.GetRequiredSizes(), System.Security.Util.Tokenizer.GetTokens(), System.Security.Util.TokenizerStream.GoToPosition(), System.Security.Util.TokenizerStream.Reset(), and System.Security.Util.TokenizerStream.ThrowAwayNextString().
Referenced by System.Security.Util.Parser.Parser().