Terraria Decompiled: System.Security.Util.Parser.GetRequiredSizes
GetRequiredSizes()
void System.Security.Util.Parser.GetRequiredSizes (TokenizerStream stream, ref int index) inline private
Definition at line 17 of file Parser.cs.
        {
            bool flag = false;
            bool flag2 = false;
            bool flag3 = false;
            bool flag4 = false;
            int num = 1;
            SecurityElementType securityElementType = SecurityElementType.Regular;
            string text = null;
            bool flag5 = false;
            bool flag6 = false;
            int num2 = 0;
            for (;;)
            {
                short num3 = stream.GetNextToken();
                while (num3 != -1)
                {
                    switch (num3 & 255)
                    {
                    case 0:
                        flag4 = true;
                        flag6 = false;
                        num3 = stream.GetNextToken();
                        if (num3 == 2)
{
                            stream.TagLastToken(17408);
                            for (;;)
{
                                num3 = stream.GetNextToken();
                                if (num3 != 3)
{
                                    break;
                                }
                                stream.ThrowAwayNextString();
                                stream.TagLastToken(20480);
                            }
                            if (num3 == -1)
{
                                goto Block_9;
                            }
                            if (num3 != 1)
{
                                goto Block_10;
                            }
                            flag4 = false;
                            index++;
                            flag6 = false;
                            num--;
                            flag = true;
                            goto IL_03B9;
                        }
                        else if (num3 == 3)
{
                            flag3 = true;
                            stream.TagLastToken(16640);
                            index += SecurityDocument.EncodedStringSize(stream.GetNextString()) + 1;
                            if (securityElementType != SecurityElementType.Regular)
{
                                goto Block_12;
                            }
                            flag = true;
                            num++;
                            goto IL_03B9;
                        }
                        else
{
                            if (num3 == 6)
{
                                num2 = 1;
                                do
{
                                    num3 = stream.GetNextToken();
                                    switch (num3)
{
                                    case 0:
                                        num2++;
                                        break;
                                    case 1:
                                        num2--;
                                        break;
                                    case 3:
                                        stream.ThrowAwayNextString();
                                        stream.TagLastToken(20480);
                                        break;
                                    }
                                }
                                while (num2 > 0);
                                flag4 = false;
                                flag6 = false;
                                flag = true;
                                goto IL_03B9;
                            }
                            if (num3 != 5)
{
                                goto IL_02B3;
                            }
                            num3 = stream.GetNextToken();
                            if (num3 != 3)
{
                                goto Block_17;
                            }
                            flag3 = true;
                            securityElementType = SecurityElementType.Format;
                            stream.TagLastToken(16640);
                            index += SecurityDocument.EncodedStringSize(stream.GetNextString()) + 1;
                            num2 = 1;
                            num++;
                            flag = true;
                            goto IL_03B9;
                        }
                        break;
                    case 1:
                        if (flag4)
{
                            flag4 = false;
                            goto IL_03C4;
                        }
                        goto IL_02E0;
                    case 2:
                        num3 = stream.GetNextToken();
                        if (num3 == 1)
{
                            stream.TagLastToken(17408);
                            index++;
                            num--;
                            flag6 = false;
                            flag = true;
                            goto IL_03B9;
                        }
                        goto IL_0329;
                    case 3:
                        if (flag4)
{
                            if (securityElementType == SecurityElementType.Comment)
{
                                stream.ThrowAwayNextString();
                                stream.TagLastToken(20480);
                                goto IL_03B9;
                            }
                            if (text == null)
{
                                text = stream.GetNextString();
                                goto IL_03B9;
                            }
                            if (!flag5)
{
                                goto Block_5;
                            }
                            stream.TagLastToken(16896);
                            index += SecurityDocument.EncodedStringSize(text) + SecurityDocument.EncodedStringSize(stream.GetNextString()) + 1;
                            text = null;
                            flag5 = false;
                            goto IL_03B9;
                        }
                        else
{
                            if (flag6)
{
                                stream.TagLastToken(25344);
                                index += SecurityDocument.EncodedStringSize(stream.GetNextString()) + SecurityDocument.EncodedStringSize(" ");
                                goto IL_03B9;
                            }
                            stream.TagLastToken(17152);
                            index += SecurityDocument.EncodedStringSize(stream.GetNextString()) + 1;
                            flag6 = true;
                            goto IL_03B9;
                        }
                        break;
                    case 4:
                        flag5 = true;
                        goto IL_03B9;
                    case 5:
                        if (!flag4 || securityElementType != SecurityElementType.Format || num2 != 1)
{
                            goto IL_0397;
                        }
                        num3 = stream.GetNextToken();
                        if (num3 == 1)
{
                            stream.TagLastToken(17408);
                            index++;
                            num--;
                            flag6 = false;
                            flag = true;
                            goto IL_03B9;
                        }
                        goto IL_037C;
                    }
                    goto Block_1;
                    IL_03C4:
                    num3 = stream.GetNextToken();
                    continue;
                    IL_03B9:
                    if (flag)
                    {
                        flag = false;
                        flag2 = false;
                        break;
                    }
                    flag2 = true;
                    goto IL_03C4;
                }
                if (flag2)
                {
                    index++;
                    num--;
                    flag6 = false;
                }
                else if (num3 == -1 && (num != 1 || !flag3))
                {
                    goto IL_03F5;
                }
                if (num <= 1)
                {
                    return;
                }
            }
            Block_1:
            goto IL_03A8;
            Block_5:
            throw new XmlSyntaxException(this._t.LineNo);
            Block_9:
            throw new XmlSyntaxException(this._t.LineNo, Environment.GetResourceString("Unexpected end of file."));
            Block_10:
            throw new XmlSyntaxException(this._t.LineNo, Environment.GetResourceString("Expected > character."));
            Block_12:
            throw new XmlSyntaxException(this._t.LineNo);
            Block_17:
            throw new XmlSyntaxException(this._t.LineNo);
            IL_02B3:
            throw new XmlSyntaxException(this._t.LineNo, Environment.GetResourceString("Expected / character or string."));
            IL_02E0:
            throw new XmlSyntaxException(this._t.LineNo, Environment.GetResourceString("Unexpected > character."));
            IL_0329:
            throw new XmlSyntaxException(this._t.LineNo, Environment.GetResourceString("Expected > character."));
            IL_037C:
            throw new XmlSyntaxException(this._t.LineNo, Environment.GetResourceString("Expected > character."));
            IL_0397:
            throw new XmlSyntaxException(this._t.LineNo);
            IL_03A8:
            throw new XmlSyntaxException(this._t.LineNo);
            IL_03F5:
            throw new XmlSyntaxException(this._t.LineNo, Environment.GetResourceString("Unexpected end of file."));
        }
References System.Security.Util.Parser._t, System.Security.SecurityDocument.EncodedStringSize(), System.Security.Util.TokenizerStream.GetNextString(), System.Security.Util.TokenizerStream.GetNextToken(), System.Environment.GetResourceString(), System.index, System.Security.Util.Tokenizer.LineNo, System.Security.Util.TokenizerStream.TagLastToken(), System.text, and System.Security.Util.TokenizerStream.ThrowAwayNextString().
Referenced by System.Security.Util.Parser.ParseContents().