Terraria Decompiled: System.Security.Util.Parser.DetermineFormat
DetermineFormat()
int System.Security.Util.Parser.DetermineFormat (TokenizerStream stream) inline private
Definition at line 263 of file Parser.cs.
        {
            if (stream.GetNextToken() == 0 && stream.GetNextToken() == 5)
            {
                this._t.GetTokens(stream, -1, true);
                stream.GoToPosition(2);
                bool flag = false;
                bool flag2 = false;
                short num = stream.GetNextToken();
                while (num != -1 && num != 1)
                {
                    if (num != 3)
                    {
                        if (num != 4)
{
                            throw new XmlSyntaxException(this._t.LineNo, Environment.GetResourceString("Unexpected end of file."));
                        }
                        flag = true;
                    }
                    else
                    {
                        if (flag && flag2)
{
                            this._t.ChangeFormat(Encoding.GetEncoding(stream.GetNextString()));
                            return 0;
                        }
                        if (!flag)
{
                            if (string.Compare(stream.GetNextString(), "encoding", StringComparison.Ordinal) == 0)
{
                                flag2 = true;
                            }
                        }
                        else
{
                            flag = false;
                            flag2 = false;
                            stream.ThrowAwayNextString();
                        }
                    }
                    num = stream.GetNextToken();
                }
                return 0;
            }
            return 2;
        }
References System.Security.Util.Parser._t, System.Security.Util.Tokenizer.ChangeFormat(), System.Text.Encoding.GetEncoding(), System.Security.Util.TokenizerStream.GetNextString(), System.Security.Util.TokenizerStream.GetNextToken(), System.Environment.GetResourceString(), System.Security.Util.Tokenizer.GetTokens(), System.Security.Util.TokenizerStream.GoToPosition(), System.Security.Util.Tokenizer.LineNo, and System.Security.Util.TokenizerStream.ThrowAwayNextString().
Referenced by System.Security.Util.Parser.ParseContents().