Terraria Decompiled: Microsoft.Xna.Framework.Audio.WaveBank.WaveBank
WaveBank() [1/2]
Microsoft.Xna.Framework.Audio.WaveBank.WaveBank (AudioEngine audioEngine, string nonStreamingWaveBankFilename) inline
Definition at line 87 of file WaveBank.cs.
        {
            if (audioEngine == null)
            {
                throw new ArgumentNullException("audioEngine");
            }
            if (string.IsNullOrEmpty(nonStreamingWaveBankFilename))
            {
                throw new ArgumentNullException("nonStreamingWaveBankFilename");
            }
            this.bankData = TitleContainer.ReadToPointer(nonStreamingWaveBankFilename, out this.bankDataLen);
            FAudio.FACTAudioEngine_CreateInMemoryWaveBank(audioEngine.handle, this.bankData, (uint)(int)this.bankDataLen, 0U, 0U, out this.handle);
            this.engine = audioEngine;
            this.selfReference = new WeakReference(this, true);
            this.engine.RegisterPointer(this.handle, this.selfReference);
            this.IsDisposed = false;
        }
References Microsoft.Xna.Framework.Audio.WaveBank.bankDataLen, Microsoft.Xna.Framework.Audio.WaveBank.engine, FAudio.FACTAudioEngine_CreateInMemoryWaveBank(), Microsoft.Xna.Framework.Audio.AudioEngine.handle, Microsoft.Xna.Framework.Audio.WaveBank.handle, Microsoft.Xna.Framework.TitleContainer.ReadToPointer(), Microsoft.Xna.Framework.Audio.AudioEngine.RegisterPointer(), Microsoft.Xna.Framework.Audio.WaveBank.selfReference, and System.U.