Terraria Decompiled: Microsoft.Xna.Framework.Audio.WaveBank.WaveBank
WaveBank() [2/2]
Microsoft.Xna.Framework.Audio.WaveBank.WaveBank (AudioEngine audioEngine, string streamingWaveBankFilename, int offset, short packetsize) inline
Definition at line 106 of file WaveBank.cs.
        {
            if (audioEngine == null)
            {
                throw new ArgumentNullException("audioEngine");
            }
            if (string.IsNullOrEmpty(streamingWaveBankFilename))
            {
                throw new ArgumentNullException("streamingWaveBankFilename");
            }
            string text = FileHelpers.NormalizeFilePathSeparators(streamingWaveBankFilename);
            if (!Path.IsPathRooted(text))
            {
                text = Path.Combine(TitleLocation.Path, text);
            }
            this.bankData = FAudio.FAudio_fopen(text);
            FAudio.FACTStreamingParameters factstreamingParameters = default(FAudio.FACTStreamingParameters);
            factstreamingParameters.file = this.bankData;
            FAudio.FACTAudioEngine_CreateStreamingWaveBank(audioEngine.handle, ref factstreamingParameters, out this.handle);
            this.engine = audioEngine;
            this.selfReference = new WeakReference(this, true);
            this.engine.RegisterPointer(this.handle, this.selfReference);
            this.IsDisposed = false;
        }
References Microsoft.Xna.Framework.Audio.WaveBank.bankData, System.IO.Path.Combine(), Microsoft.Xna.Framework.Audio.WaveBank.engine, FAudio.FACTAudioEngine_CreateStreamingWaveBank(), FAudio.FAudio_fopen(), Microsoft.Xna.Framework.Audio.AudioEngine.handle, Microsoft.Xna.Framework.Audio.WaveBank.handle, System.IO.Path.IsPathRooted(), MonoGame.Utilities.FileHelpers.NormalizeFilePathSeparators(), Microsoft.Xna.Framework.TitleLocation.Path, Microsoft.Xna.Framework.Audio.AudioEngine.RegisterPointer(), Microsoft.Xna.Framework.Audio.WaveBank.selfReference, and System.text.