Terraria Decompiled: Newtonsoft.Json.Utilities.DateTimeParser.ParseTime
ParseTime()
bool Newtonsoft.Json.Utilities.DateTimeParser.ParseTime (ref int start) inline private
Definition at line 34 of file DateTimeParser.cs.
        {
            if (!this.Parse2Digit(start, out this.Hour) || this.Hour > 24 || !this.ParseChar(start + DateTimeParser.LzHH, ':') || !this.Parse2Digit(start + DateTimeParser.LzHH_, out this.Minute) || this.Minute >= 60 || !this.ParseChar(start + DateTimeParser.LzHH_mm, ':') || !this.Parse2Digit(start + DateTimeParser.LzHH_mm_, out this.Second) || this.Second >= 60 || (this.Hour == 24 && (this.Minute != 0 || this.Second != 0)))
            {
                return false;
            }
            start += DateTimeParser.LzHH_mm_ss;
            if (this.ParseChar(start, '.'))
            {
                this.Fraction = 0;
                int num = 0;
                for (;;)
                {
                    int num2 = start + 1;
                    start = num2;
                    if (num2 >= this._end || num >= 7)
                    {
                        break;
                    }
                    int num3 = (int)(this._text[start] - '0');
                    if (num3 < 0 || num3 > 9)
                    {
                        break;
                    }
                    this.Fraction = this.Fraction * 10 + num3;
                    num++;
                }
                if (num < 7)
                {
                    if (num == 0)
                    {
                        return false;
                    }
                    this.Fraction *= DateTimeParser.Power10[7 - num];
                }
                if (this.Hour == 24 && this.Fraction != 0)
                {
                    return false;
                }
            }
            return true;
        }
References Newtonsoft.Json.Utilities.DateTimeParser._end, Newtonsoft.Json.Utilities.DateTimeParser._text, Newtonsoft.Json.Utilities.DateTimeParser.Fraction, Newtonsoft.Json.Utilities.DateTimeParser.Hour, int, Newtonsoft.Json.Utilities.DateTimeParser.LzHH, Newtonsoft.Json.Utilities.DateTimeParser.LzHH_, Newtonsoft.Json.Utilities.DateTimeParser.LzHH_mm, Newtonsoft.Json.Utilities.DateTimeParser.LzHH_mm_, Newtonsoft.Json.Utilities.DateTimeParser.LzHH_mm_ss, Newtonsoft.Json.Utilities.DateTimeParser.Parse2Digit(), Newtonsoft.Json.Utilities.DateTimeParser.ParseChar(), Newtonsoft.Json.Utilities.DateTimeParser.Power10, and System.start.
Referenced by Newtonsoft.Json.Utilities.DateTimeParser.ParseTimeAndZoneAndWhitespace().