Terraria Decompiled: Newtonsoft.Json.Utilities.DateTimeParser.Parse
Parse()
bool Newtonsoft.Json.Utilities.DateTimeParser.Parse (char[] text, int startIndex, int length) inline
Definition at line 14 of file DateTimeParser.cs.
        {
            this._text = text;
            this._end = startIndex + length;
            return this.ParseDate(startIndex) && this.ParseChar(DateTimeParser.Lzyyyy_MM_dd + startIndex, 'T') && this.ParseTimeAndZoneAndWhitespace(DateTimeParser.Lzyyyy_MM_ddT + startIndex);
        }
References System.length, Newtonsoft.Json.Utilities.DateTimeParser.Lzyyyy_MM_dd, Newtonsoft.Json.Utilities.DateTimeParser.Lzyyyy_MM_ddT, Newtonsoft.Json.Utilities.DateTimeParser.ParseChar(), Newtonsoft.Json.Utilities.DateTimeParser.ParseDate(), Newtonsoft.Json.Utilities.DateTimeParser.ParseTimeAndZoneAndWhitespace(), System.startIndex, and System.text.
Referenced by Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTimeIso(), and Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTimeOffsetIso().