Terraria Decompiled: Newtonsoft.Json.Utilities.DateTimeParser.ParseDate
ParseDate()
bool Newtonsoft.Json.Utilities.DateTimeParser.ParseDate (int start) inline private
Definition at line 22 of file DateTimeParser.cs.
        {
            return this.Parse4Digit(start, out this.Year) && 1 <= this.Year && this.ParseChar(start + DateTimeParser.Lzyyyy, '-') && this.Parse2Digit(start + DateTimeParser.Lzyyyy_, out this.Month) && 1 <= this.Month && this.Month <= 12 && this.ParseChar(start + DateTimeParser.Lzyyyy_MM, '-') && this.Parse2Digit(start + DateTimeParser.Lzyyyy_MM_, out this.Day) && 1 <= this.Day && this.Day <= DateTime.DaysInMonth(this.Year, this.Month);
        }
References System.DateTime.DaysInMonth(), Newtonsoft.Json.Utilities.DateTimeParser.Lzyyyy, Newtonsoft.Json.Utilities.DateTimeParser.Lzyyyy_, Newtonsoft.Json.Utilities.DateTimeParser.Lzyyyy_MM, Newtonsoft.Json.Utilities.DateTimeParser.Lzyyyy_MM_, Newtonsoft.Json.Utilities.DateTimeParser.Month, Newtonsoft.Json.Utilities.DateTimeParser.Parse2Digit(), Newtonsoft.Json.Utilities.DateTimeParser.Parse4Digit(), Newtonsoft.Json.Utilities.DateTimeParser.ParseChar(), and Newtonsoft.Json.Utilities.DateTimeParser.Year.
Referenced by Newtonsoft.Json.Utilities.DateTimeParser.Parse().