Terraria Decompiled: System.Span.TryCopyTo
TryCopyTo()
bool System.Span< T >.TryCopyTo (Span< T > destination) inline
Definition at line 183 of file Span.cs.
        {
            bool flag = false;
            if (this._length <= destination.Length)
            {
                Buffer.Memmove<T>(destination._pointer.Value, this._pointer.Value, (ulong)((long)this._length));
                flag = true;
            }
            return flag;
        }
References System.Span< T >._length, System.Span< T >._pointer, System.destination, System.Span< T >.Length, and System.Buffer.Memmove().
Referenced by System.Memory< T >.TryCopyTo(), and System.ReadOnlyMemory< T >.TryCopyTo().