Terraria Decompiled: Terraria.Utilities.TileSnapshot.TileStruct.From
From()
static TileSnapshot.TileStruct Terraria.Utilities.TileSnapshot.TileStruct.From (Tile tile) inline static
Definition at line 419 of file TileSnapshot.cs.
            {
                TileSnapshot.TileStruct tileStruct = default(TileSnapshot.TileStruct);
                tileStruct._type = tile.type;
                ushort wall = tile.wall;
                tileStruct._sTileHeader = tile.sTileHeader;
                tileStruct._liquid = tile.liquid;
                tileStruct._bTileHeader = tile.bTileHeader;
                tileStruct._wall_bTileHeader3_packed = (ushort)((int)wall | ((int)(tile.bTileHeader3 & 224) << 8));
                if ((tileStruct._sTileHeader & 32) == 0)
                {
                    tileStruct._type = 0;
                    tileStruct._sTileHeader &= 35808;
                }
                else
                {
                    if (Main.tileFrameImportant[(int)tileStruct._type])
                    {
                        tileStruct._frameX = tile.frameX;
                        tileStruct._frameY = tile.frameY;
                    }
                    if ((tileStruct._sTileHeader & 29696) != 0 && !TileID.Sets.SaveSlopes[(int)tileStruct._type])
                    {
                        tileStruct._sTileHeader &= 35839;
                    }
                }
                if (wall == 0)
                {
                    tileStruct._bTileHeader &= 224;
                }
                if (tileStruct._liquid == 0)
                {
                    tileStruct._bTileHeader &= 159;
                }
                return tileStruct;
            }
References Terraria.Utilities.TileSnapshot.TileStruct._liquid, Terraria.Utilities.TileSnapshot.TileStruct._sTileHeader, Terraria.Utilities.TileSnapshot.TileStruct._type, Terraria.Tile.bTileHeader, Terraria.Tile.bTileHeader3, Terraria.Tile.frameX, Terraria.Tile.frameY, int, Terraria.Tile.liquid, Terraria.ID.TileID.Sets.SaveSlopes, Terraria.Tile.sTileHeader, Terraria.Main.tileFrameImportant, Terraria.Tile.type, and Terraria.Tile.wall.
Referenced by Terraria.Utilities.TileSnapshot.Compare(), Terraria.WorldBuilding.WorldGenerator.HashWorld(), Terraria.Utilities.TileSnapshot.SaveTiles(), and Terraria.Utilities.TileSnapshot.SwapTiles().