Terraria Decompiled: System.Security.Cryptography.RSA.TrySignData
TrySignData()
virtual bool System.Security.Cryptography.RSA.TrySignData (ReadOnlySpan< byte > data, Span< byte > destination, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding, out int bytesWritten) inline virtual
Definition at line 416 of file RSA.cs.
        {
            if (string.IsNullOrEmpty(hashAlgorithm.Name))
            {
                throw RSA.HashAlgorithmNameNullOrEmpty();
            }
            if (padding == null)
            {
                throw new ArgumentNullException("padding");
            }
            int num;
            if (this.TryHashData(data, destination, hashAlgorithm, out num) && this.TrySignHash(destination.Slice(0, num), destination, hashAlgorithm, padding, out bytesWritten))
            {
                return true;
            }
            bytesWritten = 0;
            return false;
        }
References System.destination, System.Security.Cryptography.RSA.HashAlgorithmNameNullOrEmpty(), System.Security.Cryptography.HashAlgorithmName.Name, System.Span< T >.Slice(), System.Security.Cryptography.RSA.TryHashData(), and System.Security.Cryptography.RSA.TrySignHash().