Terraria Decompiled: System.Security.Cryptography.RSA.FromXmlString
FromXmlString()
override void System.Security.Cryptography.RSA.FromXmlString (string xmlString) inline virtual
Reimplemented from System.Security.Cryptography.AsymmetricAlgorithm.
Definition at line 232 of file RSA.cs.
        {
            if (xmlString == null)
            {
                throw new ArgumentNullException("xmlString");
            }
            RSAParameters rsaparameters = default(RSAParameters);
            SecurityElement topElement = new Parser(xmlString).GetTopElement();
            string text = topElement.SearchForTextOfLocalName("Modulus");
            if (text == null)
            {
                throw new CryptographicException(Environment.GetResourceString("Input string does not contain a valid encoding of the '{0}' '{1}' parameter.", new object[] { "RSA", "Modulus" }));
            }
            rsaparameters.Modulus = Convert.FromBase64String(Utils.DiscardWhiteSpaces(text));
            string text2 = topElement.SearchForTextOfLocalName("Exponent");
            if (text2 == null)
            {
                throw new CryptographicException(Environment.GetResourceString("Input string does not contain a valid encoding of the '{0}' '{1}' parameter.", new object[] { "RSA", "Exponent" }));
            }
            rsaparameters.Exponent = Convert.FromBase64String(Utils.DiscardWhiteSpaces(text2));
            string text3 = topElement.SearchForTextOfLocalName("P");
            if (text3 != null)
            {
                rsaparameters.P = Convert.FromBase64String(Utils.DiscardWhiteSpaces(text3));
            }
            string text4 = topElement.SearchForTextOfLocalName("Q");
            if (text4 != null)
            {
                rsaparameters.Q = Convert.FromBase64String(Utils.DiscardWhiteSpaces(text4));
            }
            string text5 = topElement.SearchForTextOfLocalName("DP");
            if (text5 != null)
            {
                rsaparameters.DP = Convert.FromBase64String(Utils.DiscardWhiteSpaces(text5));
            }
            string text6 = topElement.SearchForTextOfLocalName("DQ");
            if (text6 != null)
            {
                rsaparameters.DQ = Convert.FromBase64String(Utils.DiscardWhiteSpaces(text6));
            }
            string text7 = topElement.SearchForTextOfLocalName("InverseQ");
            if (text7 != null)
            {
                rsaparameters.InverseQ = Convert.FromBase64String(Utils.DiscardWhiteSpaces(text7));
            }
            string text8 = topElement.SearchForTextOfLocalName("D");
            if (text8 != null)
            {
                rsaparameters.D = Convert.FromBase64String(Utils.DiscardWhiteSpaces(text8));
            }
            this.ImportParameters(rsaparameters);
        }
References System.Security.Cryptography.Utils.DiscardWhiteSpaces(), System.Convert.FromBase64String(), System.Environment.GetResourceString(), System.Security.Util.Parser.GetTopElement(), System.Security.Cryptography.RSA.ImportParameters(), System.Security.SecurityElement.SearchForTextOfLocalName(), and System.text.
Referenced by System.Security.Cryptography.RSACryptoServiceProvider.Common().