Terraria Decompiled: System.Security.Cryptography.RSA.ToXmlString
ToXmlString()
override string System.Security.Cryptography.RSA.ToXmlString (bool includePrivateParameters) inline virtual
Reimplemented from System.Security.Cryptography.AsymmetricAlgorithm.
Reimplemented in Mono.Security.Cryptography.RSAManaged.
Definition at line 286 of file RSA.cs.
        {
            RSAParameters rsaparameters = this.ExportParameters(includePrivateParameters);
            StringBuilder stringBuilder = new StringBuilder();
            stringBuilder.Append("<RSAKeyValue>");
            stringBuilder.Append("<Modulus>" + Convert.ToBase64String(rsaparameters.Modulus) + "</Modulus>");
            stringBuilder.Append("<Exponent>" + Convert.ToBase64String(rsaparameters.Exponent) + "</Exponent>");
            if (includePrivateParameters)
            {
                stringBuilder.Append("<P>" + Convert.ToBase64String(rsaparameters.P) + "</P>");
                stringBuilder.Append("<Q>" + Convert.ToBase64String(rsaparameters.Q) + "</Q>");
                stringBuilder.Append("<DP>" + Convert.ToBase64String(rsaparameters.DP) + "</DP>");
                stringBuilder.Append("<DQ>" + Convert.ToBase64String(rsaparameters.DQ) + "</DQ>");
                stringBuilder.Append("<InverseQ>" + Convert.ToBase64String(rsaparameters.InverseQ) + "</InverseQ>");
                stringBuilder.Append("<D>" + Convert.ToBase64String(rsaparameters.D) + "</D>");
            }
            stringBuilder.Append("</RSAKeyValue>");
            return stringBuilder.ToString();
        }
References System.Text.StringBuilder.Append(), System.Security.Cryptography.RSAParameters.D, System.Security.Cryptography.RSAParameters.DP, System.Security.Cryptography.RSAParameters.DQ, System.Security.Cryptography.RSAParameters.Exponent, System.Security.Cryptography.RSA.ExportParameters(), System.Security.Cryptography.RSAParameters.InverseQ, System.Security.Cryptography.RSAParameters.Modulus, System.Security.Cryptography.RSAParameters.P, System.Security.Cryptography.RSAParameters.Q, System.Convert.ToBase64String(), and System.Text.StringBuilder.ToString().
Referenced by System.Security.Cryptography.RSACryptoServiceProvider.OnKeyGenerated().