Terraria Decompiled: System.Security.Cryptography.RSA.VerifyData
VerifyData() [3/4]
virtual bool System.Security.Cryptography.RSA.VerifyData (ReadOnlySpan< byte > data, ReadOnlySpan< byte > signature, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding) inline virtual
Definition at line 436 of file RSA.cs.
        {
            if (string.IsNullOrEmpty(hashAlgorithm.Name))
            {
                throw RSA.HashAlgorithmNameNullOrEmpty();
            }
            if (padding == null)
            {
                throw new ArgumentNullException("padding");
            }
            int num = 256;
            checked
            {
                bool flag;
                for (;;)
                {
                    int num2 = 0;
                    byte[] array = ArrayPool<byte>.Shared.Rent(num);
                    try
                    {
                        if (this.TryHashData(data, array, hashAlgorithm, out num2))
{
                            flag = this.VerifyHash(new ReadOnlySpan<byte>(array, 0, num2), signature, hashAlgorithm, padding);
                            break;
                        }
                    }
                    finally
                    {
                        Array.Clear(array, 0, num2);
                        ArrayPool<byte>.Shared.Return(array, false);
                    }
                    num *= 2;
                }
                return flag;
            }
        }
References System.array, System.Array.Clear(), System.Security.Cryptography.RSA.HashAlgorithmNameNullOrEmpty(), System.Security.Cryptography.HashAlgorithmName.Name, System.Buffers.ArrayPool< T >.Shared, System.Security.Cryptography.RSA.TryHashData(), and System.Security.Cryptography.RSA.VerifyHash().