Terraria Decompiled: System.IO.Enumeration.FileSystemEnumerator.CloseDirectoryHandle
CloseDirectoryHandle()
void System.IO.Enumeration.FileSystemEnumerator< TResult >.CloseDirectoryHandle () inline private
Definition at line 77 of file FileSystemEnumerator.cs.
        {
            IntPtr intPtr = Interlocked.Exchange(ref this._directoryHandle, IntPtr.Zero);
            if (intPtr != IntPtr.Zero)
            {
                Interop.Sys.CloseDir(intPtr);
            }
        }
References System.IO.Enumeration.FileSystemEnumerator< TResult >._directoryHandle, System.Threading.Interlocked.Exchange(), and System.IntPtr.Zero.
Referenced by System.IO.Enumeration.FileSystemEnumerator< TResult >.DirectoryFinished(), System.IO.Enumeration.FileSystemEnumerator< TResult >.FileSystemEnumerator(), and System.IO.Enumeration.FileSystemEnumerator< TResult >.InternalDispose().