Terraria Decompiled: System.IO.Enumeration.FileSystemEnumerator.MoveNext
MoveNext()
unsafe bool System.IO.Enumeration.FileSystemEnumerator< TResult >.MoveNext () inline
Implements System.Collections.IEnumerator.
Definition at line 87 of file FileSystemEnumerator.cs.
        {
            if (this._lastEntryFound)
            {
                return false;
            }
            FileSystemEntry fileSystemEntry = default(FileSystemEntry);
            object @lock = this._lock;
            bool flag2;
            lock (@lock)
            {
                if (this._lastEntryFound)
                {
                    flag2 = false;
                }
                else
                {
                    byte[] entryBuffer;
                    byte* ptr;
                    if ((entryBuffer = this._entryBuffer) == null || entryBuffer.Length == 0)
                    {
                        ptr = null;
                    }
                    else
                    {
                        ptr = &entryBuffer[0];
                    }
                    for (;;)
                    {
                        this.FindNextEntry(ptr, (this._entryBuffer == null) ? 0 : this._entryBuffer.Length);
                        if (this._lastEntryFound)
{
                            break;
                        }
                        FileAttributes fileAttributes = FileSystemEntry.Initialize(ref fileSystemEntry, this._entry, this._currentPath, this._rootDirectory, this._originalRootDirectory, new Span<char>(this._pathBuffer));
                        bool flag3 = (fileAttributes & FileAttributes.Directory) > (FileAttributes)0;
                        bool flag4 = false;
                        if (flag3 && *this._entry.Name == 46 && (this._entry.Name[1] == 0 || (this._entry.Name[1] == 46 && this._entry.Name[2] == 0)))
{
                            if (!this._options.ReturnSpecialDirectories)
{
                                continue;
                            }
                            flag4 = true;
                        }
                        if (!flag4 && this._options.AttributesToSkip != (FileAttributes)0)
{
                            if ((this._options.AttributesToSkip & FileAttributes.ReadOnly) != (FileAttributes)0)
{
                                fileAttributes = fileSystemEntry.Attributes;
                            }
                            if ((this._options.AttributesToSkip & fileAttributes) != (FileAttributes)0)
{
                                continue;
                            }
                        }
                        if (flag3 && !flag4 && this._options.RecurseSubdirectories && this.ShouldRecurseIntoEntry(ref fileSystemEntry))
{
                            if (this._pending == null)
{
                                this._pending = new Queue<string>();
                            }
                            this._pending.Enqueue(Path.Join(this._currentPath, fileSystemEntry.FileName));
                        }
                        if (this.ShouldIncludeEntry(ref fileSystemEntry))
{
                            goto Block_21;
                        }
                    }
                    return false;
                    Block_21:
                    this._current = this.TransformEntry(ref fileSystemEntry);
                    flag2 = true;
                }
            }
            return flag2;
        }
References System.IO.Enumeration.FileSystemEnumerator< TResult >._currentPath, System.IO.Enumeration.FileSystemEnumerator< TResult >._entry, System.IO.Enumeration.FileSystemEnumerator< TResult >._entryBuffer, System.IO.Enumeration.FileSystemEnumerator< TResult >._lastEntryFound, System.IO.Enumeration.FileSystemEnumerator< TResult >._lock, System.IO.Enumeration.FileSystemEnumerator< TResult >._options, System.IO.Enumeration.FileSystemEnumerator< TResult >._originalRootDirectory, System.IO.Enumeration.FileSystemEnumerator< TResult >._pathBuffer, System.IO.Enumeration.FileSystemEnumerator< TResult >._pending, System.IO.Enumeration.FileSystemEnumerator< TResult >._rootDirectory, System.IO.EnumerationOptions.AttributesToSkip, System.Collections.Generic.Queue< T >.Enqueue(), System.IO.Enumeration.FileSystemEnumerator< TResult >.FindNextEntry(), System.IO.Enumeration.FileSystemEntry.Initialize(), System.IO.Path.Join(), System.IO.EnumerationOptions.RecurseSubdirectories, System.IO.EnumerationOptions.ReturnSpecialDirectories, System.IO.Enumeration.FileSystemEnumerator< TResult >.ShouldIncludeEntry(), and System.IO.Enumeration.FileSystemEnumerator< TResult >.TransformEntry().