Terraria Decompiled: System.IO.Enumeration.FileSystemEnumerator.FileSystemEnumerator
FileSystemEnumerator()
System.IO.Enumeration.FileSystemEnumerator< TResult >.FileSystemEnumerator (string directory, EnumerationOptions options = null) inline
Definition at line 14 of file FileSystemEnumerator.cs.
        {
            if (directory == null)
            {
                throw new ArgumentNullException("directory");
            }
            this._originalRootDirectory = directory;
            this._rootDirectory = PathInternal.TrimEndingDirectorySeparator(Path.GetFullPath(directory));
            this._options = options ?? EnumerationOptions.Default;
            this._directoryHandle = this.CreateDirectoryHandle(this._rootDirectory, false);
            if (this._directoryHandle == IntPtr.Zero)
            {
                this._lastEntryFound = true;
            }
            this._currentPath = this._rootDirectory;
            try
            {
                this._pathBuffer = ArrayPool<char>.Shared.Rent(4096);
                int readDirRBufferSize = Interop.Sys.GetReadDirRBufferSize();
                this._entryBuffer = ((readDirRBufferSize > 0) ? ArrayPool<byte>.Shared.Rent(readDirRBufferSize) : null);
            }
            catch
            {
                this.CloseDirectoryHandle();
                throw;
            }
        }
References System.IO.Enumeration.FileSystemEnumerator< TResult >._directoryHandle, System.IO.Enumeration.FileSystemEnumerator< TResult >._rootDirectory, System.IO.Enumeration.FileSystemEnumerator< TResult >.CloseDirectoryHandle(), System.IO.Enumeration.FileSystemEnumerator< TResult >.CreateDirectoryHandle(), System.IO.EnumerationOptions.Default, System.IO.Path.GetFullPath(), System.options, System.Buffers.ArrayPool< T >.Rent(), System.Buffers.ArrayPool< T >.Shared, System.IO.PathInternal.TrimEndingDirectorySeparator(), and System.IntPtr.Zero.