Terraria Decompiled: Terraria.Graphics.FinalFractalHelper.FinalFractalProfile.StripDust
StripDust()
void Terraria.Graphics.FinalFractalHelper.FinalFractalProfile.StripDust (Vector2 centerPosition, float rotation, Vector2 velocity) inline private
Definition at line 196 of file FinalFractalHelper.cs.
            {
                if (Main.rand.Next(9) == 0)
                {
                    int num = Main.rand.Next(1, 4);
                    for (int i = 0; i < num; i++)
                    {
                        Dust dust = Dust.NewDustPerfect(centerPosition, 278, null, 100, Color.Lerp(this.trailColor, Color.White, Main.rand.NextFloat() * 0.3f), 1f);
                        dust.scale = 0.4f;
                        dust.fadeIn = 0.4f + Main.rand.NextFloat() * 0.3f;
                        dust.noGravity = true;
                        dust.velocity += rotation.ToRotationVector2() * (3f + Main.rand.NextFloat() * 4f);
                    }
                }
            }
References Microsoft.Xna.Framework.Color.Lerp(), Terraria.Dust.NewDustPerfect(), Terraria.Main.rand, and Microsoft.Xna.Framework.Color.White.
Referenced by Terraria.Graphics.FinalFractalHelper.FinalFractalProfile.FinalFractalProfile().