Terraria Decompiled: Terraria.Graphics.FinalFractalHelper.FinalFractalProfile.FinalFractalProfile
FinalFractalProfile()
Terraria.Graphics.FinalFractalHelper.FinalFractalProfile.FinalFractalProfile (float fullBladeLength, Color color) inline
Definition at line 183 of file FinalFractalHelper.cs.
            {
                this.trailWidth = fullBladeLength / 2f;
                this.trailColor = color;
                this.widthMethod = null;
                this.colorMethod = null;
                this.dustMethod = null;
                this.widthMethod = new VertexStrip.StripHalfWidthFunction(this.StripWidth);
                this.colorMethod = new VertexStrip.StripColorFunction(this.StripColors);
                this.dustMethod = new FinalFractalHelper.SpawnDustMethod(this.StripDust);
            }
References Terraria.Graphics.FinalFractalHelper.SpawnDustMethod(), Terraria.Graphics.VertexStrip.StripColorFunction(), Terraria.Graphics.FinalFractalHelper.FinalFractalProfile.StripColors(), Terraria.Graphics.FinalFractalHelper.FinalFractalProfile.StripDust(), Terraria.Graphics.VertexStrip.StripHalfWidthFunction(), and Terraria.Graphics.FinalFractalHelper.FinalFractalProfile.StripWidth().