Terraria Decompiled: System.IO.EnumerationOptions.FromSearchOption
FromSearchOption()
static EnumerationOptions System.IO.EnumerationOptions.FromSearchOption (SearchOption searchOption) inline static package
Definition at line 61 of file EnumerationOptions.cs.
        {
            if (searchOption != SearchOption.TopDirectoryOnly && searchOption != SearchOption.AllDirectories)
            {
                throw new ArgumentOutOfRangeException("searchOption", "Enum value was out of legal range.");
            }
            if (searchOption != SearchOption.AllDirectories)
            {
                return EnumerationOptions.Compatible;
            }
            return EnumerationOptions.CompatibleRecursive;
        }
References System.IO.EnumerationOptions.Compatible, and System.IO.EnumerationOptions.CompatibleRecursive.
Referenced by System.IO.Directory.EnumerateDirectories(), System.IO.DirectoryInfo.EnumerateDirectories(), System.IO.Directory.EnumerateFiles(), System.IO.DirectoryInfo.EnumerateFiles(), System.IO.Directory.EnumerateFileSystemEntries(), System.IO.DirectoryInfo.EnumerateFileSystemInfos(), System.IO.Directory.GetDirectories(), System.IO.DirectoryInfo.GetDirectories(), System.IO.Directory.GetFiles(), System.IO.DirectoryInfo.GetFiles(), System.IO.Directory.GetFileSystemEntries(), and System.IO.DirectoryInfo.GetFileSystemInfos().