Terraria Decompiled: System.Security.Cryptography.DESTransform.ProcessBlock
ProcessBlock()
void System.Security.Cryptography.DESTransform.ProcessBlock (byte[] input, byte[] output) inline
Definition at line 150 of file DESTransform.cs.
        {
            Buffer.BlockCopy(input, 0, this.dwordBuff, 0, DESTransform.BLOCK_BYTE_SIZE);
            if (this.encrypt)
            {
                uint num = this.dwordBuff[0];
                uint num2 = this.dwordBuff[1];
                num ^= this.CipherFunct(num2, 0);
                num2 ^= this.CipherFunct(num, 1);
                num ^= this.CipherFunct(num2, 2);
                num2 ^= this.CipherFunct(num, 3);
                num ^= this.CipherFunct(num2, 4);
                num2 ^= this.CipherFunct(num, 5);
                num ^= this.CipherFunct(num2, 6);
                num2 ^= this.CipherFunct(num, 7);
                num ^= this.CipherFunct(num2, 8);
                num2 ^= this.CipherFunct(num, 9);
                num ^= this.CipherFunct(num2, 10);
                num2 ^= this.CipherFunct(num, 11);
                num ^= this.CipherFunct(num2, 12);
                num2 ^= this.CipherFunct(num, 13);
                num ^= this.CipherFunct(num2, 14);
                num2 ^= this.CipherFunct(num, 15);
                this.dwordBuff[0] = num2;
                this.dwordBuff[1] = num;
            }
            else
            {
                uint num3 = this.dwordBuff[0];
                uint num4 = this.dwordBuff[1];
                num3 ^= this.CipherFunct(num4, 15);
                num4 ^= this.CipherFunct(num3, 14);
                num3 ^= this.CipherFunct(num4, 13);
                num4 ^= this.CipherFunct(num3, 12);
                num3 ^= this.CipherFunct(num4, 11);
                num4 ^= this.CipherFunct(num3, 10);
                num3 ^= this.CipherFunct(num4, 9);
                num4 ^= this.CipherFunct(num3, 8);
                num3 ^= this.CipherFunct(num4, 7);
                num4 ^= this.CipherFunct(num3, 6);
                num3 ^= this.CipherFunct(num4, 5);
                num4 ^= this.CipherFunct(num3, 4);
                num3 ^= this.CipherFunct(num4, 3);
                num4 ^= this.CipherFunct(num3, 2);
                num3 ^= this.CipherFunct(num4, 1);
                num4 ^= this.CipherFunct(num3, 0);
                this.dwordBuff[0] = num4;
                this.dwordBuff[1] = num3;
            }
            Buffer.BlockCopy(this.dwordBuff, 0, output, 0, DESTransform.BLOCK_BYTE_SIZE);
        }
References System.Security.Cryptography.DESTransform.BLOCK_BYTE_SIZE, System.Buffer.BlockCopy(), System.Security.Cryptography.DESTransform.CipherFunct(), System.Security.Cryptography.DESTransform.dwordBuff, Mono.Security.Cryptography.SymmetricTransform.encrypt, and System.input.
Referenced by System.Security.Cryptography.DESTransform.ECB(), and System.Security.Cryptography.TripleDESTransform.ECB().