Terraria Decompiled: System.Security.AccessControl.ObjectSecurity.SidFromIR
SidFromIR()
static SecurityIdentifier System.Security.AccessControl.ObjectSecurity< T >.SidFromIR (IdentityReference identity) inline static package
Definition at line 643 of file ObjectSecurity.cs.
        {
            if (null == identity)
            {
                throw new ArgumentNullException("identity");
            }
            return (SecurityIdentifier)identity.Translate(typeof(SecurityIdentifier));
        }
References System.Security.Principal.IdentityReference.Translate().
Referenced by System.Security.AccessControl.CommonObjectSecurity.ModifyAccess(), System.Security.AccessControl.DirectoryObjectSecurity.ModifyAccess(), System.Security.AccessControl.CommonObjectSecurity.ModifyAudit(), System.Security.AccessControl.DirectoryObjectSecurity.ModifyAudit(), System.Security.AccessControl.ObjectSecurity< T >.PurgeAccessRules(), System.Security.AccessControl.ObjectSecurity< T >.PurgeAuditRules(), System.Security.AccessControl.ObjectSecurity< T >.SetGroup(), and System.Security.AccessControl.ObjectSecurity< T >.SetOwner().