Terraria Decompiled: System.Security.AccessControl.ObjectSecurity.GetOwner
GetOwner()
IdentityReference System.Security.AccessControl.ObjectSecurity< T >.GetOwner (Type targetType) inline
Definition at line 254 of file ObjectSecurity.cs.
        {
            this.ReadLock();
            IdentityReference identityReference;
            try
            {
                if (this.descriptor.Owner == null)
                {
                    identityReference = null;
                }
                else
                {
                    identityReference = this.descriptor.Owner.Translate(targetType);
                }
            }
            finally
            {
                this.ReadUnlock();
            }
            return identityReference;
        }
References System.Security.AccessControl.ObjectSecurity< T >.descriptor, System.Security.AccessControl.CommonSecurityDescriptor.Owner, System.Security.AccessControl.ObjectSecurity< T >.ReadLock(), System.Security.AccessControl.ObjectSecurity< T >.ReadUnlock(), and System.Security.Principal.SecurityIdentifier.Translate().