Terraria Decompiled: System.Security.AccessControl.ObjectSecurity.InternalAccessRuleFactory
InternalAccessRuleFactory()
virtual AccessRule System.Security.AccessControl.ObjectSecurity< T >.InternalAccessRuleFactory (QualifiedAce ace, Type targetType, AccessControlType type) inline package virtual
Reimplemented in System.Security.AccessControl.DirectoryObjectSecurity.
Definition at line 604 of file ObjectSecurity.cs.
        {
            return this.AccessRuleFactory(ace.SecurityIdentifier.Translate(targetType), ace.AccessMask, ace.IsInherited, ace.InheritanceFlags, ace.PropagationFlags, type);
        }
References System.Security.AccessControl.KnownAce.AccessMask, System.Security.AccessControl.ObjectSecurity< T >.AccessRuleFactory(), System.Security.AccessControl.GenericAce.InheritanceFlags, System.Security.AccessControl.GenericAce.IsInherited, System.Security.AccessControl.GenericAce.PropagationFlags, System.Security.AccessControl.KnownAce.SecurityIdentifier, and System.Security.Principal.SecurityIdentifier.Translate().
Referenced by System.Security.AccessControl.ObjectSecurity< T >.InternalGetAccessRules().