Terraria Decompiled: System.Security.AccessControl.ObjectSecurity.InternalGetAuditRules
InternalGetAuditRules()
AuthorizationRuleCollection System.Security.AccessControl.ObjectSecurity< T >.InternalGetAuditRules (bool includeExplicit, bool includeInherited, Type targetType) inline package
Definition at line 610 of file ObjectSecurity.cs.
        {
            List<AuthorizationRule> list = new List<AuthorizationRule>();
            this.ReadLock();
            try
            {
                if (this.descriptor.SystemAcl != null)
                {
                    foreach (GenericAce genericAce in this.descriptor.SystemAcl)
                    {
                        QualifiedAce qualifiedAce = genericAce as QualifiedAce;
                        if (!(null == qualifiedAce) && (!qualifiedAce.IsInherited || includeInherited) && (qualifiedAce.IsInherited || includeExplicit) && AceQualifier.SystemAudit == qualifiedAce.AceQualifier)
{
                            AuditRule auditRule = this.InternalAuditRuleFactory(qualifiedAce, targetType);
                            list.Add(auditRule);
                        }
                    }
                }
            }
            finally
            {
                this.ReadUnlock();
            }
            return new AuthorizationRuleCollection(list.ToArray());
        }
References System.Security.AccessControl.QualifiedAce.AceQualifier, System.Security.AccessControl.ObjectSecurity< T >.descriptor, System.Security.AccessControl.ObjectSecurity< T >.InternalAuditRuleFactory(), System.Security.AccessControl.GenericAce.IsInherited, System.list, System.Security.AccessControl.ObjectSecurity< T >.ReadLock(), System.Security.AccessControl.ObjectSecurity< T >.ReadUnlock(), and System.Security.AccessControl.CommonSecurityDescriptor.SystemAcl.