Terraria Decompiled: System.Security.AccessControl.ObjectSecurity.GetGroup
GetGroup()
IdentityReference System.Security.AccessControl.ObjectSecurity< T >.GetGroup (Type targetType) inline
Definition at line 231 of file ObjectSecurity.cs.
        {
            this.ReadLock();
            IdentityReference identityReference;
            try
            {
                if (this.descriptor.Group == null)
                {
                    identityReference = null;
                }
                else
                {
                    identityReference = this.descriptor.Group.Translate(targetType);
                }
            }
            finally
            {
                this.ReadUnlock();
            }
            return identityReference;
        }
References System.Security.AccessControl.ObjectSecurity< T >.descriptor, System.Security.AccessControl.CommonSecurityDescriptor.Group, System.Security.AccessControl.ObjectSecurity< T >.ReadLock(), System.Security.AccessControl.ObjectSecurity< T >.ReadUnlock(), and System.Security.Principal.SecurityIdentifier.Translate().