Terraria Decompiled: System.Collections.Generic.List.Clear
Clear()
void System.Collections.Generic.List< T >.Clear () inline
Implements System.Collections.Generic.ICollection< T >.
Definition at line 292 of file List.cs.
        {
            this._version++;
            if (RuntimeHelpers.IsReferenceOrContainsReferences<T>())
            {
                int size = this._size;
                this._size = 0;
                if (size > 0)
                {
                    Array.Clear(this._items, 0, size);
                    return;
                }
            }
            else
            {
                this._size = 0;
            }
        }
References System.Collections.Generic.List< T >._items, System.Collections.Generic.List< T >._size, System.Collections.Generic.List< T >._version, and System.Array.Clear().
Referenced by Terraria.NPC.AI_084_LunaticCultist(), Terraria.Projectile.AI_100_Medusa(), Terraria.Projectile.AI_156_BatOfLight(), Terraria.Projectile.AI_158_BabyBird(), Terraria.Projectile.AI_164_StormTigerGem(), Terraria.Main.AnglerQuestSwap(), ReLogic.Peripherals.RGB.ShaderSelector.BuildOperationsList(), Terraria.Collision.BuildTileContacts(), Terraria.GameContent.Events.BirthdayParty.CheckNight(), CsvHelper.Configuration.CsvPropertyNameCollection.Clear(), Mono.Xml.SmallXmlParser.AttrListImpl.Clear(), Terraria.DataStructures.TileEntity.Clear(), Terraria.GameContent.ExtraSpawnPointManager.Clear(), Terraria.GameContent.TownRoomManager.Clear(), Terraria.GameContent.UI.Chat.RemadeChatMonitor.Clear(), Terraria.GameContent.UI.Elements.UIList.Clear(), Terraria.Utilities.WeightedRandom< T >.Clear(), Terraria.GameContent.Tile_Entities.TETrainingDummy.ClearBoxes(), Microsoft.Xna.Framework.Audio.DynamicSoundEffectInstance.ClearBuffers(), Terraria.Chat.ChatHelper.ClearDelayedMessagesCache(), Terraria.GameContent.UI.States.UIWorldCreation.ClearSeed(), Terraria.GameContent.ObjectInteractions.TileSmartInteractCandidateProvider.ClearSelfAndPrepareForCheck(), Terraria.Main.ClearSmartInteract(), Terraria.GameContent.Drawing.TileDrawing.ClearSpecialBlockCounts(), Terraria.GameContent.Drawing.NextHorizonRenderer.CloudsStart(), Terraria.WorldGen.coatingColors(), Terraria.GameContent.ChromaHotkeyPainter.CollectBoundKeys(), Terraria.GameInput.PlayerInputProfile.CopyKeysFrom(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), Terraria.Graphics.Renderers.MapHeadRenderer.CreateOutlines(), Terraria.GameContent.Events.DD2Event.Difficulty_1_GetRequiredWaveKills(), Microsoft.Xna.Framework.Audio.SoundEffect.Dispose(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.Dispose(), Terraria.WorldGen.SecretSeed.DoRoundLandMasses(), Terraria.Main.DrawMenu(), Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayer(), Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayerHead(), Terraria.Graphics.Renderers.MapHeadRenderer.DrawPlayerHead(), Terraria.Graphics.Renderers.ReturnGatePlayerRenderer.DrawReturnGateInWorld(), Terraria.GameContent.PlayerHeadDrawRenderTargetContent.DrawTheContent(), Terraria.MapRenderer.DrawToMap(), Terraria.GameContent.Drawing.TileDrawing.DrawVoidLenses(), Terraria.GameContent.UI.States.UIWorldCreation.EnableSecretSeedOptions(), Terraria.GameContent.Skies.CreditsRollSky.EnsureSegmentsAreMade(), Terraria.Graphics.Renderers.StormLightningParticle.FetchFromPool(), Terraria.UI.ItemSorting.FillAmmoFromInventory(), Terraria.WorldGen.FillWallHolesInSpot(), Terraria.GameContent.UI.States.UIBestiaryTest.FilterEntries(), Terraria.Utils.FloodFillTile(), Terraria.WorldGen.Spread.Gem(), Terraria.GameContent.Biomes.Desert.DesertHive.ClusterGroup.Generate(), Terraria.GameContent.ExtraSpawnPointManager.GenerateExtraSpawns_Setup(), Terraria.WorldGen.GenerateWorld_SetupDungeonGenVars(), Terraria.GameContent.NearbyChests.GetBanksInRangeOf(), Terraria.GameContent.NearbyChests.GetChestsInRangeOf(), Terraria.Social.WeGame.IPCBase.GetPackList(), Terraria.GameContent.EmergencyStacking.GetPlayerViewRects(), Terraria.GameContent.UI.NewCraftingUI.GetReasonForRecipeNotAvailable(), Terraria.Main.GetRecipeRequirementsText(), Terraria.Main.InitializeItemAnimations(), Terraria.GameContent.UI.States.UIAchievementsMenu.InitializePage(), Terraria.Utilities.TileSnapshot.Load(), Terraria.IO.WorldFile.LoadHeader(), Terraria.Main.LoadPlayers(), Terraria.Main.LoadWorlds(), Terraria.WorldGen.Spread.Moss(), Terraria.GameInput.PlayerInput.MouseInput(), Terraria.GameContent.Events.BirthdayParty.NaturalAttempt(), CsvHelper.CsvWriter.NextRecord(), Terraria.GameContent.UI.States.UIWorldCreation.OnFinishedSettingSeed(), Terraria.GameContent.UI.States.UIWorkshopSelectResourcePackToPublish.PopulateEntries(), Terraria.GameContent.SecretSeedsTracker.PrepareInterface(), Terraria.Graphics.VertexStrip.PrepareStripWithProceduralPadding(), ReLogic.Peripherals.RGB.Razer.RazerKeyboard.Present(), Microsoft.Xna.Framework.Audio.DynamicSoundEffectInstance.QueueInitialBuffers(), Terraria.GameContent.QuickStacking.ReadBlockedChestList(), Terraria.GameContent.HairstyleUnlocksHelper.RebuildList(), Terraria.Social.Steam.WorkshopHelper.UGCBased.Downloader.Refresh(), Terraria.GameInput.LockOnHelper.RefreshTargets(), Terraria.GameContent.Bestiary.NPCWasNearPlayerTracker.Reset(), Terraria.Graphics.Renderers.MapHeadRenderer.Reset(), Terraria.WorldBuilding.StructureMap.Reset(), Terraria.WorldGen.Reset(), Terraria.GameContent.ExtraSpawnPointManager.ResetExtraSpawns(), Terraria.WorldGen.ResetGenerator(), Terraria.IO.WorldFile.ResetTemps(), Terraria.IO.WorldFile.ResetTempsToDayTime(), Terraria.Utilities.TileSnapshot.SaveTileEntities(), Terraria.GameContent.Bestiary.NPCWasNearPlayerTracker.ScanWorldForFinds(), Terraria.GameContent.NetModules.NetLiquidModule.SerializeForPlayer(), Terraria.GameInput.LockOnHelper.SetActive(), Terraria.IO.WorldFile.SetOngoingToTemps(), Terraria.IO.WorldFile.SetTempToOngoing(), Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid.SetupAvailabilityTest(), Terraria.GameContent.UI.States.UICharacterCreation.SetupGamepadPoints(), Terraria.GameContent.SmartCursorHelper.SmartCursorLookup(), Terraria.Player.SmartInteractLookup(), Terraria.UI.ItemSorting.Sort(), Terraria.Main.SortBabyBirdProjectiles(), Terraria.Projectile.SpawnFakeFishInWater(), Terraria.WorldGen.SpawnStormLightning(), Terraria.WorldGen.Spread.Spider(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalWallVariants.SpreadWallDungeon(), Terraria.GameContent.Events.DD2Event.StartInvasion(), Terraria.Projectile.StatusNPC(), Terraria.GameContent.SmartCursorHelper.Step_Acorns(), Terraria.GameContent.SmartCursorHelper.Step_ActuationRod(), Terraria.GameContent.SmartCursorHelper.Step_Actuators(), Terraria.GameContent.SmartCursorHelper.Step_AlchemySeeds(), Terraria.GameContent.SmartCursorHelper.Step_BlocksFilling(), Terraria.GameContent.SmartCursorHelper.Step_BlocksLines(), Terraria.GameContent.SmartCursorHelper.Step_Boulders(), Terraria.GameContent.SmartCursorHelper.Step_ClayPots(), Terraria.GameContent.SmartCursorHelper.Step_ColoredWrenches(), Terraria.GameContent.SmartCursorHelper.Step_EmptyBuckets(), Terraria.GameContent.SmartCursorHelper.Step_GemCorns(), Terraria.GameContent.SmartCursorHelper.Step_GrassSeeds(), Terraria.GameContent.SmartCursorHelper.Step_Hammers(), Terraria.GameContent.SmartCursorHelper.Step_LawnMower(), Terraria.GameContent.SmartCursorHelper.Step_MinecartTracks(), Terraria.GameContent.SmartCursorHelper.Step_Moss(), Terraria.GameContent.SmartCursorHelper.Step_MulticolorWrench(), Terraria.GameContent.SmartCursorHelper.Step_PaintBrush(), Terraria.GameContent.SmartCursorHelper.Step_PaintRoller(), Terraria.GameContent.SmartCursorHelper.Step_PaintScrapper(), Terraria.GameContent.SmartCursorHelper.Step_Pickaxe_MineShinies(), Terraria.GameContent.SmartCursorHelper.Step_Pickaxe_MineSolids(), Terraria.GameContent.SmartCursorHelper.Step_Pigronata(), Terraria.GameContent.SmartCursorHelper.Step_PlanterBox(), Terraria.GameContent.SmartCursorHelper.Step_Platforms(), Terraria.GameContent.SmartCursorHelper.Step_PumpkinSeeds(), Terraria.GameContent.SmartCursorHelper.Step_StaffOfRegrowth(), Terraria.GameContent.SmartCursorHelper.Step_Torch(), Terraria.GameContent.SmartCursorHelper.Step_Walls(), Terraria.GameContent.SmartCursorHelper.Step_WireCutter(), Terraria.Collision.StepConveyorBelt(), Terraria.GameContent.Events.DD2Event.StopInvasion(), Terraria.GameContent.QuickStacking.Transfer(), Terraria.GameContent.ItemDropRules.FromOptionsWithoutRepeatsDropRule.TryDroppingItem(), ReLogic.Peripherals.RGB.SteelSeries.SteelSeriesEventRelay.TryGetEventUpdateRequest(), ReLogic.Peripherals.RGB.SteelSeries.SteelSeriesKeyboard.TryGetEventUpdateRequest(), ReLogic.Peripherals.RGB.SteelSeries.SteelSeriesSecondaryDeviceByZone.TryGetEventUpdateRequest(), CsvHelper.Configuration.CsvPropertyMap.TypeConverterOption(), Terraria.GameContent.FixExploitManEaters.Update(), Terraria.UI.Gamepad.GamepadMainMenuHandler.Update(), Terraria.GameContent.Golf.FancyGolfPredictionLine.Update(), Terraria.GameContent.Events.MoonlordDeathDrama.Update(), Terraria.Animation.UpdateAll(), Terraria.GameContent.UI.EmoteBubble.UpdateAll(), Terraria.Map.MapUpdateQueue.UpdateAreas(), Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid.UpdateAvailability(), Terraria.GameContent.Tile_Entities.TELogicSensor.UpdateEndInternal(), Terraria.GameContent.UI.States.UICharacterSelect.UpdateFavoritesCache(), Terraria.GameContent.UI.States.UIWorldSelect.UpdateFavoritesCache(), Terraria.Player.UpdateNearbyInteractableProjectilesList(), Terraria.GameContent.TeleportPylonsSystem.UpdatePylonsListAndBroadcastChanges(), Terraria.GameContent.Tile_Entities.TELogicSensor.UpdateStartInternal(), Terraria.GameContent.UI.States.UIWorkshopWorldImport.UpdateWorkshopWorldList(), Terraria.WorldGen.Spread.Wall(), Terraria.WorldGen.Spread.Wall2(), Terraria.GameContent.Events.BirthdayParty.WorldClear(), and Terraria.GameContent.Events.MysticLogFairiesEvent.WorldClear().