Terraria Decompiled: System.Collections.Generic.List.IndexOf
IndexOf() [4/4]
int System.Collections.Generic.List< T >.IndexOf (T item, int index, int count) inline
Definition at line 623 of file List.cs.
        {
            if (index > this._size)
            {
                ThrowHelper.ThrowArgumentOutOfRange_IndexException();
            }
            if (count < 0 || index > this._size - count)
            {
                ThrowHelper.ThrowCountArgumentOutOfRange_ArgumentOutOfRange_Count();
            }
            return Array.IndexOf<T>(this._items, item, index, count);
        }
References System.Collections.Generic.List< T >._items, System.Collections.Generic.List< T >._size, System.count, System.index, System.Array.IndexOf(), System.item, System.ThrowHelper.ThrowArgumentOutOfRange_IndexException(), and System.ThrowHelper.ThrowCountArgumentOutOfRange_ArgumentOutOfRange_Count().