Terraria Decompiled: System.Collections.Generic.List.ToArray
ToArray()
T[] System.Collections.Generic.List< T >.ToArray () inline
Definition at line 956 of file List.cs.
        {
            if (this._size == 0)
            {
                return List<T>.s_emptyArray;
            }
            T[] array = new T[this._size];
            Array.Copy(this._items, 0, array, 0, this._size);
            return array;
        }
References System.Collections.Generic.List< T >._items, System.Collections.Generic.List< T >._size, System.array, System.Array.Copy(), and System.Collections.Generic.List< T >.s_emptyArray.
Referenced by Mono.Globalization.Unicode.MSCompatUnicodeTable.BuildTailoringTables(), Terraria.Net.NetGroupInfo.ComposeInfo(), Microsoft.Xna.Framework.Audio.SoundEffect.Dispose(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.Dispose(), System.MonoCustomAttrs.GetCustomAttributesData(), System.IO.File.InternalReadAllLinesAsync(), Microsoft.Win32.KeyHandler.LoadKey(), ReLogic.Peripherals.RGB.SteelSeries.SteelSeriesDeviceGroup.LoadSpecialRules(), Terraria.GameContent.UI.Chat.LegacyChatMonitor.NewText(), CsvHelper.CsvWriter.NextRecord(), Terraria.Social.WeGame.IPCBase.ProcessDataArriveEvent(), Terraria.WorldGen.Reset(), Terraria.GameContent.UI.States.UIEmotesMenu.SetupGamepadPoints(), Terraria.UI.ItemSorting.SetupWhiteLists(), Microsoft.Xna.Framework.Graphics.SpriteFont.SpriteFont(), Terraria.GameContent.UI.States.UIEmotesMenu.TryAddingList(), and Terraria.Localization.VariableText.TryCreate().