Terraria Decompiled: System.Collections.Generic.List.Sort
Sort() [1/4]
void System.Collections.Generic.List< T >.Sort () inline
Definition at line 908 of file List.cs.
        {
            this.Sort(0, this.Count, null);
        }
References System.Collections.Generic.List< T >.Count, and System.Collections.Generic.List< T >.Sort().
Referenced by Terraria.Projectile.AI_100_Medusa(), Mono.Globalization.Unicode.MSCompatUnicodeTable.BuildTailoringTables(), Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.CustomSort(), Terraria.ID.SoundID.FillAccessMap(), Terraria.Main.LoadPlayers(), Terraria.Main.LoadWorlds(), Terraria.GameContent.SecretSeedsTracker.PrepareInterface(), Terraria.GameContent.UI.States.UICharacterCreation.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIManageControls.SetupGamepadPoints(), System.Collections.Generic.List< T >.Sort(), Terraria.UI.ItemSorting.Sort(), System.Collections.Generic.List< T >.Sort(), Terraria.GameContent.UI.CustomCurrencySystem.TryPurchasing(), Terraria.Player.TryPurchasing(), and Terraria.GameContent.UI.Elements.UIList.UpdateOrder().