Terraria Decompiled: System.Collections.Generic.List.AddRange
AddRange()
void System.Collections.Generic.List< T >.AddRange (IEnumerable< T > collection) inline
Definition at line 249 of file List.cs.
        {
            this.InsertRange(this._size, collection);
        }
References System.Collections.Generic.List< T >._size, and System.Collections.Generic.List< T >.InsertRange().
Referenced by Terraria.DataStructures.EntryFilterer< T, U >.AddFilters(), FullSerializer.fsResult.AddMessages(), Terraria.DataStructures.EntrySorter< TEntryType, TStepType >.AddSortSteps(), Terraria.GameContent.ChromaHotkeyPainter.CollectBoundKeys(), System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.EventRegistrationTokenList.CopyTo(), Terraria.Graphics.Renderers.LegacyPlayerRenderer.CreateOutlines(), Terraria.Graphics.Renderers.MapHeadRenderer.CreateOutlines(), Terraria.GameContent.UI.States.UIWorldCreation.EnableSecretSeedOptions(), Terraria.GameContent.UI.States.UIBestiaryTest.FilterEntries(), Terraria.Social.WeGame.IPCMessage.GetBytes(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.GetRulesForNPCID(), Terraria.GameInput.PlayerInput.LockGamepadButtons(), FullSerializer.fsResult.Merge(), Terraria.GameContent.UI.NewCraftingUI.NewCraftingUI(), Terraria.GameContent.UI.States.UIWorkshopSelectResourcePackToPublish.PopulateEntries(), Terraria.GameContent.SecretSeedsTracker.PrepareInterface(), Terraria.Social.WeGame.IPCBase.ReadCallback(), Terraria.GameContent.HairstyleUnlocksHelper.RebuildList(), Terraria.IO.ResourcePackList.ResourcePackList(), Terraria.GameContent.UI.GameTipsProvider.RollAvailableTip(), Terraria.GameContent.NetModules.NetLiquidModule.SerializeForPlayer(), Terraria.IO.WorldFile.SetOngoingToTemps(), Terraria.GameContent.SecretSeedsTracker.SetstringsFromConfig(), Terraria.IO.WorldFile.SetTempToOngoing(), Terraria.Main.SetupDrawInterfaceLayers(), Terraria.UI.ItemSorting.Sort(), Terraria.GameContent.ItemDropRules.FromOptionsWithoutRepeatsDropRule.TryDroppingItem(), CsvHelper.Configuration.CsvPropertyMap.TypeConverterOption(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.UICreativeInfiniteItemsDisplay(), Steamworks.CallbackDispatcher.UnregisterAll(), and Terraria.Utils.WordwrapStringLegacy().