Terraria Decompiled: System.Collections.Generic.List.Contains
Contains() [2/2]
bool System.Collections.Generic.List< T >.Contains (T item) inline
Implements System.Collections.Generic.ICollection< T >.
Definition at line 312 of file List.cs.
        {
            return this._size != 0 && this.IndexOf(item) != -1;
        }
References System.Collections.Generic.List< T >.IndexOf().
Referenced by System.Globalization.DateTimeFormatInfoScanner.AddDateWordOrPostfix(), System.Globalization.DateTimeFormatInfoScanner.AddIgnorableSymbols(), Terraria.Projectile.AI_156_TryAttackingNPCs(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(), Terraria.GameContent.Events.DD2Event.ClearAllDD2EnergyCrystalsInChests(), Terraria.WorldGen.ClearBrokenTraps(), System.Collections.Generic.List< T >.Contains(), Terraria.GameContent.Drawing.TileDrawing.CrawlToBottomOfReverseVineAndAddSpecialPoint(), Terraria.GameContent.Drawing.TileDrawing.CrawlToTopOfVineAndAddSpecialPoint(), Terraria.GameContent.UI.States.UIManageControls.CreateElementGroup(), Terraria.GameInput.LockOnHelper.Draw(), Terraria.UI.ItemSorting.FillAmmoFromInventory(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.FillRooms(), Terraria.Player.FindItem(), Terraria.GameInput.PlayerInput.GamePadInput(), Terraria.GameContent.NearbyChests.GetBanksInRangeOf(), Terraria.Collision.HitLine(), Terraria.Main.InSmartCursorHighlightArea(), System.AppDomain.IsCompatibilitySwitchSet(), Terraria.DataStructures.EntryFilterer< T, U >.IsFilterActive(), Terraria.GameInput.PlayerInput.IsGamepadButtonLockedFromUse(), Terraria.Player.ItemCheck_TryPlacingWearablesOnMannequins(), Terraria.Main.LoadSettings(), Terraria.Main.NPCChatText_DoAnglerQuest(), Microsoft.Xna.Framework.Audio.DynamicSoundEffectInstance.Play(), Terraria.WorldGen.playWorldCallBack(), Microsoft.Xna.Framework.SDL2_FNAPlatform.PollEvents(), Microsoft.Xna.Framework.SDL3_FNAPlatform.PollEvents(), Terraria.GameContent.FixExploitManEaters.ProtectSpot(), Terraria.GameContent.ObjectInteractions.TileSmartInteractCandidateProvider.ProvideCandidate(), Microsoft.Xna.Framework.Content.ContentManager.ReadAsset< T >(), Microsoft.Xna.Framework.Content.ContentManager.RecordDisposable(), Terraria.Main.RegisterItemAnimation(), Terraria.NetMessage.SendData(), Terraria.DataStructures.MethodSequenceListItem.ShouldAct(), Terraria.UI.ItemSorting.Sort(), Terraria.Main.SortStardustDragonProjectiles(), Terraria.GameContent.FixExploitManEaters.SpotProtected(), Terraria.GameContent.SmartCursorHelper.Step_Pickaxe_MineSolids(), Terraria.GameContent.PortalHelper.SyncPortalsOnPlayerJoin(), Terraria.DataStructures.EntryFilterer< T, U >.ToggleFilter(), Terraria.WorldBuilding.WorldSeedOption_Everything.UpdateDependentState(), Terraria.GameContent.PressurePlateHelper.UpdatePlayerPosition(), and Terraria.GameContent.ChromaHotkeyPainter.PaintKey.UsesKey().