Terraria Decompiled: System.Collections.Generic.List.Insert
Insert() [2/2]
void System.Collections.Generic.List< T >.Insert (int index, T item) inline
Implements System.Collections.Generic.IList< T >.
Definition at line 637 of file List.cs.
        {
            if (index > this._size)
            {
                ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.index, ExceptionResource.ArgumentOutOfRange_ListInsert);
            }
            if (this._size == this._items.Length)
            {
                this.EnsureCapacity(this._size + 1);
            }
            if (index < this._size)
            {
                Array.Copy(this._items, index, this._items, index + 1, this._size - index);
            }
            this._items[index] = item;
            this._size++;
            this._version++;
        }
References System.Collections.Generic.List< T >._items, System.Collections.Generic.List< T >._size, System.Collections.Generic.List< T >._version, System.Array.Copy(), System.Collections.Generic.List< T >.EnsureCapacity(), System.index, System.item, and System.ThrowHelper.ThrowArgumentOutOfRangeException().
Referenced by Terraria.GameContent.UI.Chat.RemadeChatMonitor.AddNewMessage(), Terraria.Main.SortStardustDragonProjectiles(), Terraria.UI.Gamepad.GamepadMainMenuHandler.Update(), and Terraria.Utils.WordwrapStringLegacy().