Terraria Decompiled: System.Collections.Generic.List.InsertRange
InsertRange()
void System.Collections.Generic.List< T >.InsertRange (int index, IEnumerable< T > collection) inline
Definition at line 671 of file List.cs.
        {
            if (collection == null)
            {
                ThrowHelper.ThrowArgumentNullException(ExceptionArgument.collection);
            }
            if (index > this._size)
            {
                ThrowHelper.ThrowArgumentOutOfRange_IndexException();
            }
            ICollection<T> collection2 = collection as ICollection<T>;
            if (collection2 != null)
            {
                int count = collection2.Count;
                if (count > 0)
                {
                    this.EnsureCapacity(this._size + count);
                    if (index < this._size)
                    {
                        Array.Copy(this._items, index, this._items, index + count, this._size - index);
                    }
                    if (this == collection2)
                    {
                        Array.Copy(this._items, 0, this._items, index, index);
                        Array.Copy(this._items, index + count, this._items, index * 2, this._size - index);
                    }
                    else
                    {
                        collection2.CopyTo(this._items, index);
                    }
                    this._size += count;
                }
            }
            else
            {
                if (index < this._size)
                {
                    using (IEnumerator<T> enumerator = collection.GetEnumerator())
                    {
                        while (enumerator.MoveNext())
{
                            T t = enumerator.Current;
                            this.Insert(index++, t);
                        }
                        goto IL_00FB;
                    }
                }
                this.AddEnumerable(collection);
            }
            IL_00FB:
            this._version++;
        }
References System.Collections.Generic.List< T >._items, System.Collections.Generic.List< T >._size, System.Collections.Generic.List< T >._version, System.Collections.Generic.List< T >.AddEnumerable(), System.collection, System.Array.Copy(), System.Collections.Generic.ICollection< T >.CopyTo(), System.Collections.Generic.ICollection< T >.Count, System.count, System.Collections.Generic.IEnumerator< out T >.Current, System.Collections.Generic.List< T >.EnsureCapacity(), System.index, System.Insert, System.Collections.IEnumerator.MoveNext(), System.ThrowHelper.ThrowArgumentNullException(), and System.ThrowHelper.ThrowArgumentOutOfRange_IndexException().
Referenced by System.Collections.Generic.List< T >.AddRange().