Terraria Decompiled: System.Collections.Generic.List.RemoveAt
RemoveAt()
void System.Collections.Generic.List< T >.RemoveAt (int index) inline
Implements System.Collections.Generic.IList< T >.
Definition at line 830 of file List.cs.
        {
            if (index >= this._size)
            {
                ThrowHelper.ThrowArgumentOutOfRange_IndexException();
            }
            this._size--;
            if (index < this._size)
            {
                Array.Copy(this._items, index + 1, this._items, index, this._size - index);
            }
            if (RuntimeHelpers.IsReferenceOrContainsReferences<T>())
            {
                this._items[this._size] = default(T);
            }
            this._version++;
        }
References System.Collections.Generic.List< T >._items, System.Collections.Generic.List< T >._size, System.Collections.Generic.List< T >._version, System.Array.Copy(), System.index, and System.ThrowHelper.ThrowArgumentOutOfRange_IndexException().
Referenced by Microsoft.Xna.Framework.Content.ContentManager.AddContentManager(), Terraria.GameContent.UI.Chat.RemadeChatMonitor.AddNewMessage(), Terraria.Social.Base.WorkshopIssueReporter.AddReport(), Terraria.FrameSkipTest.CheckReset(), Terraria.UI.ChestUI.MoveCoins(), System.Collections.Generic.List< T >.Remove(), Microsoft.Xna.Framework.Content.ContentManager.RemoveContentManager(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.RemoveResourceReference(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDictionary(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDynamic(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeISerializable(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeMultidimensionalArray(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(), Terraria.UI.ItemSorting.Sort(), Terraria.GameContent.ItemDropRules.FromOptionsWithoutRepeatsDropRule.TryDroppingItem(), Terraria.GameContent.UI.CustomCurrencySystem.TryPurchasing(), Terraria.Player.TryPurchasing(), Microsoft.Xna.Framework.Audio.DynamicSoundEffectInstance.Update(), Terraria.Audio.SoundInstanceGarbageCollector.Update(), Terraria.UI.Gamepad.GamepadMainMenuHandler.Update(), Terraria.TestHighFPSIssues.Update(), Terraria.GameContent.Events.BirthdayParty.UpdateTime(), and Terraria.Utils.WordwrapStringLegacy().