Terraria Decompiled: System.Collections.Generic.List.Remove
Remove() [2/2]
bool System.Collections.Generic.List< T >.Remove (T item) inline
Implements System.Collections.Generic.ICollection< T >.
Definition at line 771 of file List.cs.
        {
            int num = this.IndexOf(item);
            if (num >= 0)
            {
                this.RemoveAt(num);
                return true;
            }
            return false;
        }
References System.Collections.Generic.List< T >.IndexOf(), and System.Collections.Generic.List< T >.RemoveAt().
Referenced by Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalBiomeChests.BiomeChests_DualDungeons(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.ConvertSpecializedHalls(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.ConvertSpecializedRooms(), Terraria.GameContent.UI.States.UIGamepadHelper.CullPointsOutOfElementArea(), Microsoft.Xna.Framework.Audio.SoundEffectInstance.Dispose(), Terraria.Main.DoUpdate(), Terraria.Projectile.DropGeodeGems(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalEarlyDualDungeonFeatures.EarlyDungeonFeatures(), Terraria.UI.ItemSorting.FillAmmoFromInventory(), Terraria.GameInput.PlayerInput.GamePadInput(), Terraria.GameContent.ExtraSpawnPointManager.GenerateExtraSpawns_TryFindSpawnRandomly(), Terraria.UI.ChestUI.MoveCoins(), Microsoft.Xna.Framework.Game.OnComponentRemoved(), Microsoft.Xna.Framework.Game.OnDrawOrderChanged(), Microsoft.Xna.Framework.Input.Touch.GestureDetector.OnReleased(), Microsoft.Xna.Framework.Game.OnUpdateOrderChanged(), Microsoft.Xna.Framework.SDL2_FNAPlatform.PollEvents(), Microsoft.Xna.Framework.SDL3_FNAPlatform.PollEvents(), Terraria.GameContent.Events.DD2Event.RaiseGoblins(), System.Collections.Generic.List< T >.Remove(), Terraria.DataStructures.TileEntity.Remove(), Terraria.GameContent.UI.Elements.UIList.Remove(), Terraria.Player.RemoveAnglerAccOptionsFromRewardPool(), ReLogic.Localization.IME.PlatformIme.RemoveKeyListener(), ReLogic.OS.Windows.WindowsMessageHook.RemoveMessageFilter(), Terraria.GameContent.UI.States.UIGamepadHelper.RemovePointsOutOfView(), Terraria.GameContent.UI.States.UIWorldCreation.RemoveSeedFromSeedMenu(), Terraria.GameContent.UI.States.UIEmotesMenu.RemoveSnapPointsOutOfScreen(), Terraria.GameContent.UI.GameTipsProvider.RollAvailableTip(), Terraria.GameContent.UI.States.UICharacterSelect.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIEmotesMenu.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIManageControls.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIWorkshopSelectResourcePackToPublish.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIWorkshopSelectWorldToPublish.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIWorkshopWorldImport.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIWorldSelect.SetupGamepadPoints(), Terraria.UI.ItemSorting.Sort(), Terraria.Main.SortStardustDragonProjectiles(), Terraria.NPC.SpawnStardustMark_StardustTower(), Terraria.NPC.SpawnStardustMark_StardustWorm(), Terraria.GameContent.SmartCursorHelper.Step_Acorns(), Terraria.GameContent.SmartCursorHelper.Step_GemCorns(), Terraria.GameContent.SmartCursorHelper.Step_Hammers(), Terraria.GameContent.SmartCursorHelper.Step_Pickaxe_MineShinies(), Terraria.GameContent.SmartCursorHelper.Step_Pickaxe_MineSolids(), Microsoft.Xna.Framework.Audio.SoundEffectInstance.Stop(), Terraria.DataStructures.EntryFilterer< T, U >.ToggleFilter(), Terraria.WorldGen.TriggerLunarApocalypse(), Terraria.GameContent.UI.CustomCurrencySingleCoin.TryPurchasing(), Steamworks.CallbackDispatcher.Unregister(), Steamworks.CallbackDispatcher.Unregister(), and Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid.UpdateAvailability().