Terraria Decompiled: System.Collections.Generic.List.Sort
Sort() [4/4]
void System.Collections.Generic.List< T >.Sort (int index, int count, IComparer< T > comparer) inline
Definition at line 920 of file List.cs.
        {
            if (index < 0)
            {
                ThrowHelper.ThrowIndexArgumentOutOfRange_NeedNonNegNumException();
            }
            if (count < 0)
            {
                ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.count, ExceptionResource.ArgumentOutOfRange_NeedNonNegNum);
            }
            if (this._size - index < count)
            {
                ThrowHelper.ThrowArgumentException(ExceptionResource.Argument_InvalidOffLen);
            }
            if (count > 1)
            {
                Array.Sort<T>(this._items, index, count, comparer);
            }
            this._version++;
        }
References System.Collections.Generic.List< T >._items, System.Collections.Generic.List< T >._size, System.Collections.Generic.List< T >._version, System.comparer, System.count, System.index, System.Array.Sort(), System.ThrowHelper.ThrowArgumentException(), System.ThrowHelper.ThrowArgumentOutOfRangeException(), and System.ThrowHelper.ThrowIndexArgumentOutOfRange_NeedNonNegNumException().