Terraria Decompiled: System.Collections.Generic.List.List
List() [3/4]
System.Collections.Generic.List< T >.List (IEnumerable< T > collection) inline
Definition at line 37 of file List.cs.
        {
            if (collection == null)
            {
                ThrowHelper.ThrowArgumentNullException(ExceptionArgument.collection);
            }
            ICollection<T> collection2 = collection as ICollection<T>;
            if (collection2 == null)
            {
                this._size = 0;
                this._items = List<T>.s_emptyArray;
                this.AddEnumerable(collection);
                return;
            }
            int count = collection2.Count;
            if (count == 0)
            {
                this._items = List<T>.s_emptyArray;
                return;
            }
            this._items = new T[count];
            collection2.CopyTo(this._items, 0);
            this._size = count;
        }
References System.Collections.Generic.List< T >._items, System.Collections.Generic.List< T >.AddEnumerable(), System.collection, System.Collections.Generic.ICollection< T >.CopyTo(), System.Collections.Generic.ICollection< T >.Count, System.count, System.Collections.Generic.List< T >.s_emptyArray, and System.ThrowHelper.ThrowArgumentNullException().