Terraria Decompiled: System.Collections.Generic.List.RemoveAll
RemoveAll()
int System.Collections.Generic.List< T >.RemoveAll (Predicate< T > match) inline
Definition at line 792 of file List.cs.
        {
            if (match == null)
            {
                ThrowHelper.ThrowArgumentNullException(ExceptionArgument.match);
            }
            int num = 0;
            while (num < this._size && !match(this._items[num]))
            {
                num++;
            }
            if (num >= this._size)
            {
                return 0;
            }
            int i = num + 1;
            while (i < this._size)
            {
                while (i < this._size && match(this._items[i]))
                {
                    i++;
                }
                if (i < this._size)
                {
                    this._items[num++] = this._items[i++];
                }
            }
            if (RuntimeHelpers.IsReferenceOrContainsReferences<T>())
            {
                Array.Clear(this._items, num, this._size - num);
            }
            int num2 = this._size - num;
            this._size = num;
            this._version++;
            return num2;
        }
References System.Collections.Generic.List< T >._items, System.Collections.Generic.List< T >._size, System.Collections.Generic.List< T >._version, System.Array.Clear(), System.match, and System.ThrowHelper.ThrowArgumentNullException().
Referenced by Terraria.GameContent.CraftingRequests.HandleRequest(), Terraria.GameContent.TownRoomManager.KickOut(), and Terraria.GameContent.TownRoomManager.SetRoom().