Terraria Decompiled: System.Collections.Generic.List.Add
Add() [2/2]
void System.Collections.Generic.List< T >.Add (T item) inline
Implements System.Collections.Generic.ICollection< T >.
Definition at line 209 of file List.cs.
        {
            this._version++;
            T[] items = this._items;
            int size = this._size;
            if (size < items.Length)
            {
                this._size = size + 1;
                items[size] = item;
                return;
            }
            this.AddWithResize(item);
        }
References System.Collections.Generic.List< T >._items, System.Collections.Generic.List< T >._size, System.Collections.Generic.List< T >._version, System.Collections.Generic.List< T >.AddWithResize(), and System.item.
Referenced by Terraria.Map.MapUpdateQueue.Add(), CsvHelper.Configuration.CsvPropertyNameCollection.Add(), Mono.Xml.SmallXmlParser.AttrListImpl.Add(), Terraria.Utilities.WeightedRandom< T >.Add(), Terraria.DataStructures.TileEntity.Add(), Terraria.GameContent.UI.Elements.UIList.Add(), Terraria.ObjectData.TileObjectData.addAlternate(), Microsoft.Xna.Framework.Content.ContentManager.AddContentManager(), System.Globalization.DateTimeFormatInfoScanner.AddDateWordOrPostfix(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.AddEmote(), Terraria.Initializers.ChromaInitializer.AddGameplayEvents(), System.Globalization.DateTimeFormatInfoScanner.AddIgnorableSymbols(), ReLogic.Localization.IME.PlatformIme.AddKeyListener(), FullSerializer.fsResult.AddMessage(), ReLogic.OS.Windows.WindowsMessageHook.AddMessageFilter(), Terraria.Recipe.AddMissing(), Terraria.Social.WeGame.IPCBase.AddPackToList(), NVorbis.Ogg.StreamPageReader.AddPage(), Terraria.WorldBuilding.StructureMap.AddProtectedStructure(), Terraria.Social.Base.WorkshopIssueReporter.AddReport(), Terraria.DataStructures.GeneralIssueReporter.AddReport(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.AddResourceReference(), Terraria.GameContent.UI.States.UIWorldCreation.AddSeedFromSeedmenu(), Terraria.GameContent.SecretSeedsTracker.AddSeedToTrack(), System.Runtime.Serialization.SafeSerializationEventArgs.AddSerializedState(), Terraria.WorldBuilding.StructureMap.AddStructure(), Terraria.ObjectData.TileObjectData.addSubTile(), Terraria.ObjectData.TileObjectData.addSubTile(), Terraria.ObjectData.TileObjectData.addSubTileRange(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.AddSymetricalCogsPair(), Terraria.Recipe.AddTileCountsAs(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.AddWavingNPC(), Terraria.NPC.AI(), Terraria.Projectile.AI_067_TigerSpecialAttack(), Terraria.NPC.AI_084_LunaticCultist(), Terraria.Projectile.AI_100_Medusa(), Terraria.GameContent.Events.DD2Event.AnnounceGoblinDeath(), ReLogic.Peripherals.RGB.ShaderSelector.ShaderGroup.AppendOperations(), Terraria.GameContent.UI.States.UIManageControls.AssembleBindPanels(), Terraria.GameContent.ChromaHotkeyPainter.PaintKey.Bind(), Terraria.DataStructures.PlayerDrawSet.BoringSetup(), Microsoft.Xna.Framework.Graphics.EffectParameter.BuildElementList(), Mono.Globalization.Unicode.MSCompatUnicodeTable.BuildTailoringTables(), Terraria.Collision.BuildTileContacts(), Terraria.Player.BuyItem(), Terraria.GameContent.UI.CustomCurrencyManager.BuyItem(), Terraria.Chat.ChatHelper.CacheMessage(), Terraria.GameContent.Tile_Entities.TELogicSensor.ChangeState(), Terraria.FrameSkipTest.CheckReset(), Terraria.WorldGen.ClearBrokenTraps(), Terraria.WorldGen.coatingColors(), FullSerializer.fsMetaType.CollectProperties(), Terraria.GameContent.Animations.StardewValleyAnimation.ComposeAnimation(), Terraria.IO.WorldFile.ConvertOldTileEntities(), System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.EventRegistrationTokenList.CopyTo(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), rail.RailConverter.Cpp2Csharp(), Terraria.GameContent.Drawing.TileDrawing.CrawlToBottomOfReverseVineAndAddSpecialPoint(), Terraria.GameContent.Drawing.TileDrawing.CrawlToTopOfVineAndAddSpecialPoint(), Terraria.Audio.LegacySoundPlayer.CreateInstance(), Terraria.GameContent.UI.States.UICreativePowersMenu.CreateMainPowerStrip(), Terraria.Graphics.Renderers.LegacyPlayerRenderer.CreateOutlines(), Terraria.Graphics.Renderers.MapHeadRenderer.CreateOutlines(), NVorbis.Ogg.PacketProvider.CreatePacket(), Terraria.IO.ResourcePackList.CreatePacksFromSavedJson(), Terraria.GameContent.UI.States.UICreativePowersMenu.CreatePersonalPowerStrip(), Terraria.GameContent.UI.States.UICreativePowersMenu.CreateTimePowerStrip(), Terraria.ID.SoundID.CreateTrackable(), Terraria.GameContent.UI.States.UICreativePowersMenu.CreateWeatherPowerStrip(), Terraria.GameContent.CraftingRequests.NetCraftingRequestsModule.DeserializeRequest(), Terraria.WorldGen.SecretSeed.DoExtraLiquidAddBubbleBlocks(), Terraria.WorldGen.SecretSeed.DoRoundLandMasses(), Microsoft.Xna.Framework.Game.Draw(), Terraria.Mount.Draw(), Terraria.GameContent.Drawing.NextHorizonRenderer.DrawCloud(), Terraria.Main.DrawMenu(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_12_Skin_Composite(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_12_SkinComposite_BackArmShirt(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_17_TorsoComposite(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_28_ArmOverItemComposite(), Terraria.Graphics.Renderers.MapHeadRenderer.DrawPlayerHead(), Terraria.GameContent.PotionOfReturnGateHelper.DrawToDrawData(), Terraria.GameContent.VoidLensHelper.DrawToDrawData(), Terraria.GameContent.Generation.Dungeon.Features.DungeonDropTrap.DungeonDropTrap(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalBanners.DungeonGlobalBanners(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalBasicChests.DungeonGlobalBasicChests(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalBiomeChests.DungeonGlobalBiomeChests(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalBookshelves.DungeonGlobalBookshelves(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalDoors.DungeonGlobalDoors(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalEarlyDualDungeonFeatures.DungeonGlobalEarlyDualDungeonFeatures(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalGroundFurniture.DungeonGlobalGroundFurniture(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalLateDualDungeonFeatures.DungeonGlobalLateDualDungeonFeatures(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalLights.DungeonGlobalLights(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalPaintings.DungeonGlobalPaintings(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalPlatforms.DungeonGlobalPlatforms(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalSpikes.DungeonGlobalSpikes(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalTraps.DungeonGlobalTraps(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalWallVariants.DungeonGlobalWallVariants(), Terraria.GameContent.Generation.Dungeon.Features.DungeonPillar.DungeonPillar(), Terraria.GameContent.Generation.Dungeon.Features.DungeonPitTrap.DungeonPitTrap(), Terraria.GameContent.Generation.Dungeon.Features.DungeonTileClump.DungeonTileClump(), Terraria.GameContent.Generation.Dungeon.Features.DungeonWindow.DungeonWindow(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalEarlyDualDungeonFeatures.EarlyDungeonFeatures(), Terraria.GameContent.UI.States.UIWorldCreation.EnableSecretSeedOptions(), Terraria.UI.ItemSorting.FillAmmoFromInventory(), Terraria.GameContent.Tile_Entities.TETrainingDummy.FillPlayerHitboxes(), Terraria.GameContent.ObjectInteractions.TileSmartInteractCandidateProvider.FillPotentialTargetTiles(), Terraria.WorldGen.FillWallHolesInSpot(), Terraria.Projectile.FillWhipControlPoints(), Terraria.GameContent.UI.CustomCurrencyManager.FindEmptySlots(), Terraria.Player.FindSharpTearsSpot(), System.Resources.ResourceWriter.FindTypeCode(), System.AggregateException.Flatten(), Terraria.Utils.FloodFillTile(), FullSerializer.fsConverterRegistrar.fsConverterRegistrar(), FullSerializer.fsSerializer.fsSerializer(), FullSerializer.Internal.fsTypeCache.fsTypeCache(), Terraria.WorldGen.Spread.Gem(), Terraria.GameContent.Biomes.Desert.DesertHive.ClusterGroup.Generate(), Terraria.GameContent.LightningGenerator.GenerateBolt(), Terraria.GameContent.ExtraSpawnPointManager.GenerateExtraSpawns_Setup(), Terraria.GameContent.ExtraSpawnPointManager.GenerateExtraSpawns_TryFindSpawnRandomly(), NVorbis.Huffman.GenerateTable(), Terraria.WorldGen.GenerateWorld_SetupDungeonGenVars(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GetAllRoomsInSpots(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GetAllRoomsNearSpot(), Terraria.GameContent.NearbyChests.GetBanksInRangeOf(), Terraria.GameContent.NearbyChests.GetChestsInRangeOf(), System.MonoCustomAttrs.GetCustomAttributesData(), Terraria.GameContent.FishDropRules.FishDropRuleList.GetDisplayableDrops(), Terraria.Player.GetDyeTraderReward(), Terraria.Collision.GetEntityEdgeTiles(), Terraria.GameContent.UI.Elements.AWorldListItem.GetIcons(), System.Threading.ThreadLocal< T >.IdManager.GetId(), Terraria.Recipe.GetIngredientsForOneCraft(), CsvHelper.Configuration.CsvClassMap< T >.GetMaxIndex(), Newtonsoft.Json.Utilities.EnumUtils.GetNamesAndValues< TUnderlyingType >(), Terraria.Main.GetRecipeRequirementsText(), FullSerializer.Internal.fsVersionManager.GetVersionImportPathRecursive(), Terraria.ObjectData.TileObjectData.Initialize(), Terraria.UI.AchievementAdvisor.Initialize(), Terraria.Main.Initialize_AlmostEverything(), Terraria.GameContent.UI.States.UIAchievementsMenu.InitializePage(), Microsoft.Xna.Framework.Graphics.Effect.INTERNAL_parseEffectStruct(), System.Attribute.InternalParamGetCustomAttributes(), System.IO.File.InternalReadAllLinesAsync(), System.RuntimeType.InvokeMember(), Terraria.GameContent.Tile_Entities.TELogicSensor.Kill(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalLateDualDungeonFeatures.LateDualDungeonFeatures(), Terraria.Initializers.LinkButtonsInitializer.Load(), Terraria.GameContent.TownRoomManager.Load(), Terraria.Utilities.TileSnapshot.Load(), Terraria.GameInput.PlayerInputProfile.Load(), Terraria.Main.LoadContent_Deferred(), Terraria.IO.WorldFile.LoadHeader(), Terraria.Main.LoadPlayers(), Terraria.Initializers.ChromaInitializer.LoadSpecialRulesFor_SecondaryDevice(), Terraria.Main.LoadWorlds(), Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GetHall(), Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GetRoom(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.MakeHall(), Terraria.WorldGen.Spread.Moss(), Terraria.GameInput.PlayerInput.MouseInput(), Terraria.GameContent.UI.Elements.UIDebugCommandItem.MouseOver(), Terraria.UI.ChestUI.MoveCoins(), Terraria.GameContent.Events.BirthdayParty.NaturalAttempt(), Terraria.GameContent.UI.NewCraftingUI.NewCraftingUI(), Terraria.Main.NPCChatText_DoAnglerQuest(), FullSerializer.Internal.fsTypeCache.OnAssemblyLoaded(), Terraria.GameContent.UI.States.UIWorldCreation.OnFinishedSettingSeed(), Microsoft.Xna.Framework.Input.Touch.GestureDetector.OnPressed(), Terraria.GameContent.ChromaHotkeyPainter.PaintKey.PaintKey(), Newtonsoft.Json.Linq.JsonPath.JPath.ParsePath(), Terraria.GameContent.Generation.ShapeBranch.Perform(), Microsoft.Xna.Framework.Audio.DynamicSoundEffectInstance.Play(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_DryadTurningToTree(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_DryadSayingByeToTavernKeep(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_SantaAndTaxCollectorThrowingPresents(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_SteampunkerRepairingCyborg(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_WitchDoctorGoingToHisPeople(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_GuideEmotingAtRainbowPanel(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_PrincessAndEveryoneThanksPlayer(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_SantaItemExample(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_TextRoll(), Microsoft.Xna.Framework.SDL2_FNAPlatform.PollEvents(), Microsoft.Xna.Framework.SDL3_FNAPlatform.PollEvents(), Terraria.GameContent.UI.States.UIDebugCommandsList.PopulateCommandsList(), Terraria.GameContent.UI.Elements.PowerStripUIElement.PowerStripUIElement(), Terraria.Graphics.VertexStrip.PrepareStripWithProceduralPadding(), NVorbis.Ogg.ContainerReader.ProcessNewStream(), NVorbis.VorbisReader.ProcessNewStream(), Terraria.GameContent.FixExploitManEaters.ProtectSpot(), Terraria.GameContent.ObjectInteractions.TileSmartInteractCandidateProvider.ProvideCandidate(), Terraria.GameContent.Creative.CreativePowers.APerPlayerTogglePower.ProvidePowerButtons(), Terraria.GameContent.Creative.CreativePowers.ASharedButtonPower.ProvidePowerButtons(), Terraria.GameContent.Creative.CreativePowers.ASharedTogglePower.ProvidePowerButtons(), Terraria.MapRenderer.QueueChange(), Terraria.DataStructures.PlayerDrawHeadLayers.QuickCDD(), Terraria.DataStructures.PlayerDrawHeadLayers.QuickCDD(), Terraria.UI.ChestUI.QuickStack(), Microsoft.Xna.Framework.Content.ModelReader.Read(), Newtonsoft.Json.JsonReader.ReadArrayElementIntoByteArrayReportDone(), Microsoft.Xna.Framework.Content.ContentManager.ReadAsset< T >(), Terraria.GameContent.QuickStacking.ReadBlockedChestList(), Microsoft.Xna.Framework.Content.ContentReader.ReadSharedResource< T >(), Terraria.GameContent.HairstyleUnlocksHelper.RebuildList(), Microsoft.Xna.Framework.Content.ContentManager.RecordDisposable(), Terraria.GameContent.Golf.GolfBallTrackRecord.RecordHit(), Terraria.Projectile.ReduceRemainingChumsInPool(), Terraria.Social.Steam.WorkshopHelper.UGCBased.Downloader.Refresh(), Terraria.GameInput.LockOnHelper.RefreshTargets(), Terraria.GameContent.Bestiary.BestiaryDatabase.Register(), Terraria.WorldBuilding.WorldGenerationOptions.Register< T >(), Terraria.Main.RegisterItemAnimation(), Terraria.Initializers.AssetInitializer.RegisterRenderTargetAsset(), Terraria.Animation.RemoveTemporaryAnimation(), ReLogic.Peripherals.RGB.Razer.RazerKeyboard.Render(), Terraria.GameContent.ItemDropRules.CommonDrop.ReportDroprates(), Terraria.GameContent.ItemDropRules.CommonDropWithRerolls.ReportDroprates(), Terraria.GameContent.ItemDropRules.DropOneByOne.ReportDroprates(), Terraria.GameContent.ItemDropRules.FromOptionsWithoutRepeatsDropRule.ReportDroprates(), Terraria.GameContent.ItemDropRules.ItemDropWithConditionRule.ReportDroprates(), Terraria.GameContent.ItemDropRules.MechBossSpawnersDropRule.ReportDroprates(), Terraria.GameContent.ItemDropRules.OneFromOptionsDropRule.ReportDroprates(), Terraria.GameContent.ItemDropRules.OneFromOptionsNotScaledWithLuckDropRule.ReportDroprates(), Terraria.GameContent.Events.MoonlordDeathDrama.RequestLight(), Terraria.WorldGen.Reset(), Terraria.UI.ChestUI.Restock(), Terraria.Utilities.TileSnapshot.SaveTileEntities(), Terraria.GameContent.Bestiary.NPCWasNearPlayerTracker.ScanWorldForFinds(), Terraria.GameContent.Biomes.Desert.DesertHive.ClusterGroup.SearchForCluster(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDictionary(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDynamic(), Newtonsoft.Json.Converters.XmlNodeConverter.SerializeGroupedNodes(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeISerializable(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeMultidimensionalArray(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(), System.AppDomain.SetCompatibilitySwitch(), Terraria.GameContent.TownRoomManager.SetRoom(), Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid.SetupAvailabilityTest(), Terraria.GameContent.UI.States.UICharacterCreation.SetupGamepadPoints(), Terraria.UI.ItemSorting.SetupWhiteLists(), Terraria.GameContent.Generation.Dungeon.Halls.SineDungeonHall.SineHall(), Terraria.WorldGen.SkyblockIsland(), Terraria.GameContent.SmartCursorHelper.SmartCursorLookup(), Terraria.UI.ItemSorting.Sort(), Terraria.Main.SortBabyBirdProjectiles(), Terraria.Main.SortStardustDragonProjectiles(), Microsoft.Xna.Framework.Audio.SoundEffectInstance.SoundEffectInstance(), Terraria.NPC.SpawnStardustMark_StardustTower(), Terraria.NPC.SpawnStardustMark_StardustWorm(), Terraria.WorldGen.SpawnStormLightning(), Terraria.WorldGen.Spread.Spider(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalWallVariants.SpreadWallDungeon(), Terraria.GameContent.SmartCursorHelper.Step_Acorns(), Terraria.GameContent.SmartCursorHelper.Step_ActuationRod(), Terraria.GameContent.SmartCursorHelper.Step_Actuators(), Terraria.GameContent.SmartCursorHelper.Step_AlchemySeeds(), Terraria.GameContent.SmartCursorHelper.Step_BlocksFilling(), Terraria.GameContent.SmartCursorHelper.Step_BlocksLines(), Terraria.GameContent.SmartCursorHelper.Step_Boulders(), Terraria.GameContent.SmartCursorHelper.Step_ClayPots(), Terraria.GameContent.SmartCursorHelper.Step_ColoredWrenches(), Terraria.GameContent.SmartCursorHelper.Step_EmptyBuckets(), Terraria.GameContent.SmartCursorHelper.Step_GemCorns(), Terraria.GameContent.SmartCursorHelper.Step_GrassSeeds(), Terraria.GameContent.SmartCursorHelper.Step_Hammers(), Terraria.GameContent.SmartCursorHelper.Step_LawnMower(), Terraria.GameContent.SmartCursorHelper.Step_MinecartTracks(), Terraria.GameContent.SmartCursorHelper.Step_Moss(), Terraria.GameContent.SmartCursorHelper.Step_MulticolorWrench(), Terraria.GameContent.SmartCursorHelper.Step_PaintBrush(), Terraria.GameContent.SmartCursorHelper.Step_PaintRoller(), Terraria.GameContent.SmartCursorHelper.Step_PaintScrapper(), Terraria.GameContent.SmartCursorHelper.Step_Pickaxe_MineShinies(), Terraria.GameContent.SmartCursorHelper.Step_Pickaxe_MineSolids(), Terraria.GameContent.SmartCursorHelper.Step_Pigronata(), Terraria.GameContent.SmartCursorHelper.Step_PlanterBox(), Terraria.GameContent.SmartCursorHelper.Step_Platforms(), Terraria.GameContent.SmartCursorHelper.Step_PumpkinSeeds(), Terraria.GameContent.SmartCursorHelper.Step_StaffOfRegrowth(), Terraria.GameContent.SmartCursorHelper.Step_Torch(), Terraria.GameContent.SmartCursorHelper.Step_Walls(), Terraria.GameContent.SmartCursorHelper.Step_WireCutter(), Microsoft.Xna.Framework.Audio.DynamicSoundEffectInstance.SubmitBuffer(), Microsoft.Xna.Framework.Audio.DynamicSoundEffectInstance.SubmitFloatBufferEXT(), NVorbis.TagData.TagData(), Terraria.TestHighFPSIssues.TapDraw(), Terraria.TestHighFPSIssues.TapUpdate(), Terraria.TestHighFPSIssues.TapUpdateEnd(), Terraria.GameContent.AmbientWindSystem.TestAirCloud(), Terraria.Modules.TileObjectAlternatesModule.TileObjectAlternatesModule(), Terraria.Modules.TileObjectSubTilesModule.TileObjectSubTilesModule(), Terraria.DataStructures.EntryFilterer< T, U >.ToggleFilter(), Terraria.Audio.SoundInstanceGarbageCollector.Track(), ReLogic.Peripherals.RGB.SteelSeries.SteelSeriesDeviceGroup.TrackDeviceAndAddItToList(), Terraria.Localization.VariableText.TryCreate(), ReLogic.Peripherals.RGB.SteelSeries.SteelSeriesEventRelay.TryGetEventUpdateRequest(), ReLogic.Peripherals.RGB.SteelSeries.SteelSeriesKeyboard.TryGetEventUpdateRequest(), ReLogic.Peripherals.RGB.SteelSeries.SteelSeriesSecondaryDeviceByZone.TryGetEventUpdateRequest(), Terraria.GameContent.UI.CustomCurrencySingleCoin.TryPurchasing(), Terraria.GameContent.UI.CustomCurrencySystem.TryPurchasing(), Terraria.Player.TryPurchasing(), FullSerializer.Internal.fsArrayConverter.TrySerialize(), FullSerializer.Internal.fsDictionaryConverter.TrySerialize(), CsvHelper.TypeConversion.TypeConverterOptions.TypeConverterOptions(), System.TimeZoneInfo.TZif_GenerateAdjustmentRule(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.UICreativeInfiniteItemsDisplay(), Terraria.GameContent.Golf.FancyGolfPredictionLine.Update(), Microsoft.Xna.Framework.Game.Update(), Terraria.GameContent.UI.EmoteBubble.UpdateAll(), Terraria.GameContent.UI.States.UICharacterSelect.UpdateFavoritesCache(), Terraria.GameContent.UI.States.UIWorldSelect.UpdateFavoritesCache(), Terraria.Player.UpdateNearbyInteractableProjectilesList(), Terraria.Player.UpdateTouchingTiles(), Terraria.GameContent.UI.States.UIWorkshopWorldImport.UpdateWorkshopWorldList(), Terraria.GameContent.AssetSourceController.UseResourcePacks(), Terraria.WorldGen.Spread.Wall(), Terraria.WorldGen.Spread.Wall2(), Terraria.Utils.WordwrapStringLegacy(), and CsvHelper.CsvWriter.WriteField().