Terraria Decompiled: System.Collections.Generic.Dictionary.ContainsKey
ContainsKey()
bool System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey (TKey key) inline
Implements System.Collections.Generic.IDictionary< TKey, TValue >.
Definition at line 285 of file Dictionary.cs.
        {
            return this.FindEntry(key) >= 0;
        }
References System.Collections.Generic.Dictionary< TKey, TValue >.FindEntry().
Referenced by Terraria.GameContent.UI.CustomCurrencySystem.Accepts(), Terraria.Graphics.Effects.EffectManager< T >.Activate(), Ionic.Zip.ZipFile.AddOrUpdateDirectoryImpl(), System.Runtime.Serialization.SerializationInfo.AddValueInternal(), Terraria.GameContent.Drawing.TileDrawing.CacheSpecialDraws_Part1(), Terraria.GameContent.Drawing.TileDrawing.CacheSpecialDraws_Part2(), ReLogic.Content.AssetReaderCollection.CanReadExtension(), Terraria.Social.Steam.NetClientSocialModule.CheckParameters(), Terraria.IO.FavoritesFile.ClearEntry(), System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), Terraria.IO.Preferences.Contains(), System.Collections.ObjectModel.KeyedCollection< TKey, TItem >.Contains(), Ionic.Zip.ZipFile.ContainsEntry(), Ionic.Zip.ZipOutputStream.ContainsEntry(), ReLogic.Reflection.IdDictionary.ContainsId(), ReLogic.Reflection.IdDictionary.ContainsName(), FullSerializer.fsSerializer.ConvertLegacyData(), CsvHelper.CsvReader.CreateReadRecordFunc(), CsvHelper.CsvWriter.CreateWriteRecordAction(), Terraria.Graphics.Effects.EffectManager< T >.Deactivate(), Terraria.Main.FindAnnouncementBoxStatus(), Terraria.GameContent.UI.ItemRarity.GetColor(), Terraria.WorldBuilding.Actions.TileScanner.GetCount(), FullSerializer.Internal.fsCyclicReferenceManager.GetReferenceObject(), Terraria.Graphics.Shaders.ArmorShaderDataSet.GetShaderFromItemId(), Terraria.Graphics.Shaders.HairShaderDataSet.GetShaderFromItemId(), Terraria.Graphics.Shaders.ArmorShaderDataSet.GetShaderIdFromItemId(), Terraria.Graphics.Shaders.HairShaderDataSet.GetShaderIdFromItemId(), Terraria.GameContent.Drawing.TileDrawing.GetTileDrawData(), ReLogic.Utilities.TypeInstanceCollection< BaseType >.Has(), ReLogic.Utilities.TypeInstanceCollection< BaseType >.Has< T >(), FullSerializer.fsContext.Has< T >(), ReLogic.Content.Sources.FileSystemContentSource.HasAsset(), Terraria.Initializers.LaunchInitializer.HasParameter(), Terraria.Wiring.HitWire(), Terraria.Social.Steam.NetServerSocialModule.Initialize(), Terraria.Social.WeGame.NetServerSocialModule.Initialize(), Ionic.Zip.ZipOutputStream.InsureUniqueEntry(), Microsoft.Xna.Framework.SDL2_FNAPlatform.INTERNAL_AddInstance(), Microsoft.Xna.Framework.SDL3_FNAPlatform.INTERNAL_AddInstance(), Terraria.IO.FavoritesFile.IsFavorite(), Terraria.Net.SteamAddress.IsLocalHost(), Terraria.Net.WeGameAddress.IsLocalHost(), FullSerializer.Internal.fsCyclicReferenceManager.IsReference(), Terraria.Program.LaunchGame(), Terraria.Main.LoadDedConfig(), FullSerializer.Internal.fsCyclicReferenceManager.MarkSerialized(), Terraria.WorldGen.nextCount(), Terraria.WorldGen.nextDirtCount(), Terraria.WorldBuilding.Actions.TileScanner.Output(), CsvHelper.CsvReader.ParseNamedIndexes(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.PrepareNPCNetIDsByTypeDictionary(), Ionic.Zip.ZipEntry.ReadDirEntry(), Terraria.GameInput.KeyConfiguration.ReadPreferences(), rail.RailCallBackHelper.RegisterCallback(), Terraria.IO.FavoritesFile.SaveFavorite(), Terraria.GameContent.Bestiary.NPCKillsTracker.SetKillCountDirectly(), Terraria.Program.SetupLogging(), Terraria.WorldGen.ShimmeratorNext(), rail.RailCallBackHelper.UnregisterCallback(), and ReLogic.Content.AssetChangeWatcher.UpdateSources().