Terraria Decompiled: System.Collections.Generic.Dictionary.ContainsValue
ContainsValue()
bool System.Collections.Generic.Dictionary< TKey, TValue >.ContainsValue (TValue value) inline
Definition at line 291 of file Dictionary.cs.
        {
            Dictionary<TKey, TValue>.Entry[] entries = this._entries;
            if (value == null)
            {
                for (int i = 0; i < this._count; i++)
                {
                    if (entries[i].hashCode >= 0 && entries[i].value == null)
                    {
                        return true;
                    }
                }
            }
            else if (default(TValue) != null)
            {
                for (int j = 0; j < this._count; j++)
                {
                    if (entries[j].hashCode >= 0 && EqualityComparer<TValue>.Default.Equals(entries[j].value, value))
                    {
                        return true;
                    }
                }
            }
            else
            {
                EqualityComparer<TValue> @default = EqualityComparer<TValue>.Default;
                for (int k = 0; k < this._count; k++)
                {
                    if (entries[k].hashCode >= 0 && @default.Equals(entries[k].value, value))
                    {
                        return true;
                    }
                }
            }
            return false;
        }
References System.Collections.Generic.Dictionary< TKey, TValue >._count, System.Collections.Generic.Dictionary< TKey, TValue >._entries, System.Collections.Generic.EqualityComparer< T >.Default, System.Default, System.Collections.Generic.EqualityComparer< T >.Equals(), and System.value.
Referenced by System.Resources.ResourceManager.AddResourceSet(), and System.Collections.Generic.Dictionary< TKey, TValue >.ValueCollection.Contains().