Terraria Decompiled: System.Collections.Generic.Dictionary.Add
Add() [2/3]
void IDictionary. System.Collections.Generic.Dictionary< TKey, TValue >.Add (object key, object value) inline private
Definition at line 1062 of file Dictionary.cs.
        {
            if (key == null)
            {
                ThrowHelper.ThrowArgumentNullException(ExceptionArgument.key);
            }
            ThrowHelper.IfNullAndNullsAreIllegalThenThrow<TValue>(value, ExceptionArgument.value);
            try
            {
                TKey tkey = (TKey)((object)key);
                try
                {
                    this.Add(tkey, (TValue)((object)value));
                }
                catch (InvalidCastException)
                {
                    ThrowHelper.ThrowWrongValueTypeArgumentException(value, typeof(TValue));
                }
            }
            catch (InvalidCastException)
            {
                ThrowHelper.ThrowWrongKeyTypeArgumentException(key, typeof(TKey));
            }
        }
References System.Add, System.key, System.ThrowHelper.ThrowArgumentNullException(), System.ThrowHelper.ThrowWrongKeyTypeArgumentException(), System.ThrowHelper.ThrowWrongValueTypeArgumentException(), and System.value.