Terraria Decompiled: System.Collections.Generic.Dictionary.GetObjectData
GetObjectData()
virtual void System.Collections.Generic.Dictionary< TKey, TValue >.GetObjectData (SerializationInfo info, StreamingContext context) inline virtual
Implements System.Runtime.Serialization.ISerializable.
Definition at line 367 of file Dictionary.cs.
        {
            if (info == null)
            {
                ThrowHelper.ThrowArgumentNullException(ExceptionArgument.info);
            }
            info.AddValue("Version", this._version);
            info.AddValue("Comparer", this._comparer ?? EqualityComparer<TKey>.Default, typeof(IEqualityComparer<TKey>));
            info.AddValue("HashSize", (this._buckets == null) ? 0 : this._buckets.Length);
            if (this._buckets != null)
            {
                KeyValuePair<TKey, TValue>[] array = new KeyValuePair<TKey, TValue>[this.Count];
                this.CopyTo(array, 0);
                info.AddValue("KeyValuePairs", array, typeof(KeyValuePair<TKey, TValue>[]));
            }
        }
References System.Collections.Generic.Dictionary< TKey, TValue >._buckets, System.Collections.Generic.Dictionary< TKey, TValue >._comparer, System.Collections.Generic.Dictionary< TKey, TValue >._version, System.Runtime.Serialization.SerializationInfo.AddValue(), System.array, System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Default, System.info, and System.ThrowHelper.ThrowArgumentNullException().