Terraria Decompiled: System.Collections.Generic.Dictionary.CopyTo
CopyTo() [2/3]
void System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo (KeyValuePair< TKey, TValue >[] array, int index) inline private
Definition at line 329 of file Dictionary.cs.
        {
            if (array == null)
            {
                ThrowHelper.ThrowArgumentNullException(ExceptionArgument.array);
            }
            if (index > array.Length)
            {
                ThrowHelper.ThrowIndexArgumentOutOfRange_NeedNonNegNumException();
            }
            if (array.Length - index < this.Count)
            {
                ThrowHelper.ThrowArgumentException(ExceptionResource.Arg_ArrayPlusOffTooSmall);
            }
            int count = this._count;
            Dictionary<TKey, TValue>.Entry[] entries = this._entries;
            for (int i = 0; i < count; i++)
            {
                if (entries[i].hashCode >= 0)
                {
                    array[index++] = new KeyValuePair<TKey, TValue>(entries[i].key, entries[i].value);
                }
            }
        }
References System.Collections.Generic.Dictionary< TKey, TValue >._count, System.Collections.Generic.Dictionary< TKey, TValue >._entries, System.array, System.count, System.index, System.key, System.ThrowHelper.ThrowArgumentException(), System.ThrowHelper.ThrowArgumentNullException(), System.ThrowHelper.ThrowIndexArgumentOutOfRange_NeedNonNegNumException(), and System.value.
Referenced by System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), and System.Collections.Generic.Dictionary< TKey, TValue >.GetObjectData().