Terraria Decompiled: System.Collections.Generic.Dictionary.TryGetValue
TryGetValue()
bool System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue (TKey key, out TValue value) inline
Implements System.Collections.Generic.IDictionary< TKey, TValue >.
Definition at line 777 of file Dictionary.cs.
        {
            int num = this.FindEntry(key);
            if (num >= 0)
            {
                value = this._entries[num].value;
                return true;
            }
            value = default(TValue);
            return false;
        }
References System.Collections.Generic.Dictionary< TKey, TValue >._entries, System.Collections.Generic.Dictionary< TKey, TValue >.FindEntry(), and System.value.
Referenced by Terraria.GameContent.ChumBucketProjectileHelper.AddChumLocation(), System.Globalization.DateTimeFormatInfoScanner.AddDateWordOrPostfix(), NVorbis.Ogg.ForwardOnlyPageReader.AddPage(), NVorbis.Ogg.PageReader.AddPage(), System.Resources.ResourceManager.AddResourceSet(), Terraria.Localization.LanguageManager.AddVariant(), Terraria.GameContent.Bestiary.UnlockableNPCEntryIcon.AdjustSpecialSpawnRulesForVisuals(), Terraria.GameContent.CoinLossRevengeSystem.CacheEnemy(), Terraria.GameContent.Items.WhipTagEffect.CanApplyTagToNPC(), FullSerializer.fsBaseConverter.CheckKey(), Terraria.Wiring.CheckLogicGate(), Terraria.Recipe.CollectItems(), System.Collections.ObjectModel.KeyedCollection< TKey, TItem >.ContainsItem(), Terraria.GameInput.TriggersSet.CopyInto(), ReLogic.Peripherals.RGB.Corsair.CorsairKeyboard.CorsairKeyboard(), Terraria.GameContent.UI.CustomCurrencySystem.CountCurrency(), Terraria.Graphics.TileBatch.CreateBatch(), System.Security.Cryptography.CryptoConfig.CreateFromName(), FullSerializer.fsBaseConverter.DeserializeMember< T >(), Terraria.GameContent.PressurePlateHelper.DestroyPlate(), Terraria.IngameOptions.Draw(), Terraria.Main.DrawBuffIcon(), Terraria.IngameOptions.DrawLeftSide(), Terraria.Main.DrawNPCPortrait(), Terraria.WorldBuilding.TileFont.DrawString(), Microsoft.Xna.Framework.Graphics.SpriteBatch.DrawString(), Terraria.Main.FindAnnouncementBoxStatus(), System.Runtime.Serialization.SerializationInfo.FindElement(), System.Reflection.Emit.ILGenerator.FixupTokens(), Microsoft.Xna.Framework.FNAPlatform.FNAPlatform(), Terraria.ID.NPCID.FromLegacyName(), Terraria.ID.ItemID.FromLegacyName(), Terraria.GameContent.UI.Chat.GlyphTagHandler.GenerateTag(), ReLogic.Utilities.TypeInstanceCollection< BaseType >.Get< T >(), FullSerializer.fsContext.Get< T >(), Terraria.IO.Preferences.Get< T >(), Terraria.Recipe.GetAvailableItemCount(), Terraria.Localization.LanguageManager.GetCategorySize(), Terraria.GameContent.ChumBucketProjectileHelper.GetChumsInLocation(), System.Globalization.EncodingTable.GetCodePageFromName(), ReLogic.Content.Sources.FileSystemContentSource.GetExtension(), ReLogic.Content.Sources.ZipContentSource.GetExtension(), System.Resources.ResourceManager.GetFirstResourceSet(), Terraria.Social.Steam.AchievementsSocialModule.GetFloatStat(), Terraria.Lang.GetGlobalSubstitution(), Terraria.Achievements.AchievementManager.GetIconIndex(), Terraria.Social.Steam.AchievementsSocialModule.GetIntStat(), Microsoft.Xna.Framework.SDL2_FNAPlatform.GetKeyFromScancode(), Microsoft.Xna.Framework.SDL3_FNAPlatform.GetKeyFromScancode(), Terraria.GameContent.Bestiary.NPCKillsTracker.GetKillCount(), Terraria.GameContent.Bestiary.CommonEnemyUICollectionInfoProvider.GetKillCountNeeded(), System.Threading.ExecutionContext.Reader.GetLocalValue(), Terraria.Localization.LocalizedText.GetPropertyLookupFunc(), FullSerializer.Internal.fsCyclicReferenceManager.GetReferenceId(), System.Resources.ResourceManager.GetResourceSet(), Terraria.GameContent.Creative.ItemsSacrificedUnlocksTracker.GetSacrificeCount(), Microsoft.Xna.Framework.GameServiceContainer.GetService(), NVorbis.TagData.GetTagMulti(), FullSerializer.Internal.fsTypeCache.GetType(), Newtonsoft.Json.Utilities.ConvertUtils.GetTypeCode(), Terraria.GameContent.Generation.PassLegacy.GetWeight(), Terraria.GameContent.UI.Chat.GlyphTagHandler.GlyphSnippet.GlyphSnippet(), System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(), ReLogic.Content.Sources.ZipContentSource.HasAsset(), Terraria.Wiring.HitWire(), Terraria.Recipe.HowManyTimesCanRecipeBeCrafted(), ReLogic.Utilities.TypeInstanceCollection< BaseType >.IfHas< T >(), ReLogic.Utilities.TypeInstanceCollection< BaseType >.IfHas< T, U >(), Terraria.Localization.LanguageManager.IndexedFromCategory(), Microsoft.Xna.Framework.SDL2_FNAPlatform.INTERNAL_RemoveInstance(), Microsoft.Xna.Framework.SDL3_FNAPlatform.INTERNAL_RemoveInstance(), System.Resources.ResourceManager.InternalGetResourceSet(), Terraria.IO.FavoritesFile.IsFavorite(), Newtonsoft.Json.Serialization.JsonPrimitiveContract.JsonPrimitiveContract(), Terraria.GameContent.Creative.ItemsSacrificedUnlocksTracker.Load(), Terraria.GameInput.PlayerInputProfile.Load(), Microsoft.Xna.Framework.Content.ContentManager.Load< T >(), Terraria.Audio.LegacyAudioSystem.LoadFromSources(), Terraria.Localization.LanguageManager.LoadLanguageFromFileTextJson(), Terraria.GameInput.PlayerInput.LockGamepadButtons(), Terraria.Wiring.LogicGatePass(), System.Security.Cryptography.CryptoConfig.MapNameToOID(), Microsoft.Xna.Framework.Graphics.SpriteFont.MeasureString(), Terraria.WorldBuilding.TileFont.MeasureString(), Microsoft.Xna.Framework.Graphics.SpriteFont.MeasureString(), Terraria.GameContent.PressurePlateHelper.MoveAwayFrom(), Terraria.GameContent.PressurePlateHelper.MoveInto(), Terraria.GameContent.UI.States.UIGamepadHelper.MoveToVisuallyClosestPoint(), System.Threading.ExecutionContext.OnAsyncLocalContextChanged(), Terraria.GameContent.Bestiary.NPCKillsTracker.OnPlayerJoining(), Terraria.GameContent.Bestiary.NPCWasChatWithTracker.OnPlayerJoining(), Terraria.GameContent.Bestiary.NPCWasNearPlayerTracker.OnPlayerJoining(), Microsoft.Xna.Framework.Audio.AudioEngine.OnXACTNotification(), ReLogic.Content.Sources.FileSystemContentSource.OpenStream(), ReLogic.Content.Sources.ZipContentSource.OpenStream(), Terraria.Player.PickAmmo_TryFindingSpecificMatches(), Microsoft.Xna.Framework.SDL2_FNAPlatform.PollEvents(), Microsoft.Xna.Framework.SDL3_FNAPlatform.PollEvents(), Microsoft.Xna.Framework.SDL2_FNAPlatform.ProgramInit(), Microsoft.Xna.Framework.SDL3_FNAPlatform.ProgramInit(), Terraria.Localization.LanguageManager.RandomFromCategory(), ReLogic.Content.AssetReaderCollection.Read< T >(), Terraria.WorldBuilding.WorldGenSnapshot.SnapshotGenVars.ReadJson(), Terraria.GameContent.Creative.ItemsSacrificedUnlocksTracker.RegisterItemSacrifice(), Terraria.GameContent.Bestiary.NPCKillsTracker.RegisterKill(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterToNPC(), System.Collections.ObjectModel.KeyedCollection< TKey, TItem >.Remove(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RemoveFromNPC(), ReLogic.Peripherals.RGB.Corsair.CorsairKeyboard.Render(), ReLogic.Peripherals.RGB.Logitech.LogitechKeyboard.Render(), ReLogic.Peripherals.RGB.Razer.RazerKeyboard.Render(), Terraria.GameContent.RGB.VirtualKeyboard.Render(), Terraria.Testing.DebugOverrides.Replace(), Terraria.Testing.DebugOverrides.Replace(), Terraria.NPC.SetDefaults(), System.Threading.ExecutionContext.SetLocalValue(), Terraria.GameContent.Creative.ItemsSacrificedUnlocksTracker.SetSacrificeCountDirectly(), Terraria.GameContent.CoinLossRevengeSystem.RevengeMarker.SpawnEnemy(), Terraria.Testing.QuickLoad.JoinWorld.Start(), Terraria.Net.Sockets.TcpSocket.StartListening(), Terraria.Recipe.SubtractOwnedItem(), Microsoft.Xna.Framework.SDL2_FNAPlatform.ToXNAKey(), Microsoft.Xna.Framework.SDL3_FNAPlatform.ToXNAKey(), Terraria.GameContent.UI.States.UICharacterCreation.TryAutoAssigningHair(), FullSerializer.Internal.fsTypeCache.TryDirectTypeLookup(), Terraria.Social.Base.AWorkshopEntry.TryGet< T >(), ReLogic.Reflection.IdDictionary.TryGetId(), ReLogic.Reflection.IdDictionary.TryGetName(), Terraria.GameContent.Creative.CreativeItemSacrificesCatalog.TryGetSacrificeCountCapToUnlockInfiniteItems(), Terraria.GameContent.Creative.ItemsSacrificedUnlocksTracker.TryGetSacrificeNumbers(), Terraria.GameContent.Creative.ItemsSacrificedUnlocksTracker.TryGetTeammateUnlockCredit(), System.Collections.ObjectModel.KeyedCollection< TKey, TItem >.TryGetValue(), Terraria.Localization.LanguageManager.TryGetVariation(), Terraria.Initializers.LaunchInitializer.TryParameter(), and Terraria.UI.ItemSorting.ItemSortingLayer.Validate().