Terraria Decompiled: System.Collections.Generic.Dictionary.TrimExcess
TrimExcess() [2/2]
void System.Collections.Generic.Dictionary< TKey, TValue >.TrimExcess (int capacity) inline
Definition at line 910 of file Dictionary.cs.
        {
            if (capacity < this.Count)
            {
                ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.capacity);
            }
            int prime = HashHelpers.GetPrime(capacity);
            Dictionary<TKey, TValue>.Entry[] entries = this._entries;
            int num = ((entries == null) ? 0 : entries.Length);
            if (prime >= num)
            {
                return;
            }
            int count = this._count;
            this.Initialize(prime);
            Dictionary<TKey, TValue>.Entry[] entries2 = this._entries;
            int[] buckets = this._buckets;
            int num2 = 0;
            for (int i = 0; i < count; i++)
            {
                int hashCode = entries[i].hashCode;
                if (hashCode >= 0)
                {
                    Dictionary<TKey, TValue>.Entry[] array = entries2;
                    int num3 = num2;
                    array[num3] = entries[i];
                    int num4 = hashCode % prime;
                    array[num3].next = buckets[num4] - 1;
                    buckets[num4] = num2 + 1;
                    num2++;
                }
            }
            this._count = num2;
            this._freeCount = 0;
        }
References System.Collections.Generic.Dictionary< TKey, TValue >._buckets, System.Collections.Generic.Dictionary< TKey, TValue >._count, System.Collections.Generic.Dictionary< TKey, TValue >._entries, System.array, System.capacity, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.count, System.Collections.HashHelpers.GetPrime(), System.Collections.Generic.Dictionary< TKey, TValue >.Initialize(), and System.ThrowHelper.ThrowArgumentOutOfRangeException().