Terraria Decompiled: System.Collections.Generic.Dictionary.Remove
Remove() [1/4]
bool ICollection< KeyValuePair< TKey, TValue > >. System.Collections.Generic.Dictionary< TKey, TValue >.Remove (KeyValuePair< TKey, TValue > keyValuePair) inline private
Definition at line 258 of file Dictionary.cs.
        {
            int num = this.FindEntry(keyValuePair.Key);
            if (num >= 0 && EqualityComparer<TValue>.Default.Equals(this._entries[num].value, keyValuePair.Value))
            {
                this.Remove(keyValuePair.Key);
                return true;
            }
            return false;
        }
References System.Default, System.Collections.Generic.EqualityComparer< T >.Equals(), System.Collections.Generic.Dictionary< TKey, TValue >.FindEntry(), System.Collections.Generic.KeyValuePair< TKey, TValue >.Key, System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), and System.Collections.Generic.KeyValuePair< TKey, TValue >.Value.
Referenced by NVorbis.Ogg.ForwardOnlyPageReader.AddPage(), NVorbis.Ogg.PageReader.AddPage(), Terraria.IO.FavoritesFile.ClearEntry(), CsvHelper.CsvReader.ClearRecordCache(), CsvHelper.CsvWriter.ClearRecordCache(), Terraria.GameContent.PressurePlateHelper.DestroyPlate(), Terraria.Wiring.HitWire(), Microsoft.Xna.Framework.SDL2_FNAPlatform.INTERNAL_RemoveInstance(), Microsoft.Xna.Framework.SDL3_FNAPlatform.INTERNAL_RemoveInstance(), Terraria.GameContent.PressurePlateHelper.MoveAwayFrom(), Microsoft.Xna.Framework.Audio.AudioEngine.OnXACTNotification(), Microsoft.Xna.Framework.Graphics.FNA3D.ReadImageStream(), ReLogic.Reflection.IdDictionary.Remove(), System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), ReLogic.Reflection.IdDictionary.Remove(), ReLogic.Utilities.TypeInstanceCollection< BaseType >.Remove< T >(), Ionic.Zip.ZipFile.RemoveEntry(), Newtonsoft.Json.Linq.JPropertyKeyedCollection.RemoveKey(), System.Collections.ObjectModel.KeyedCollection< TKey, TItem >.RemoveKey(), Microsoft.Xna.Framework.GameServiceContainer.RemoveService(), FullSerializer.fsSerializer.StripDeserializationMetadata(), rail.RailCallBackHelper.UnregisterCallback(), rail.RailCallBackHelper.UnregisterCallback(), Microsoft.Xna.Framework.Graphics.FNA3D.WriteJPGStream(), and Microsoft.Xna.Framework.Graphics.FNA3D.WritePNGStream().