Terraria Decompiled: System.Collections.Generic.Dictionary.Clear
Clear()
void System.Collections.Generic.Dictionary< TKey, TValue >.Clear () inline
Implements System.Collections.Generic.ICollection< T >.
Definition at line 270 of file Dictionary.cs.
        {
            int count = this._count;
            if (count > 0)
            {
                Array.Clear(this._buckets, 0, this._buckets.Length);
                this._count = 0;
                this._freeList = -1;
                this._freeCount = 0;
                Array.Clear(this._entries, 0, count);
            }
            this._version++;
        }
References System.Collections.Generic.Dictionary< TKey, TValue >._buckets, System.Collections.Generic.Dictionary< TKey, TValue >._count, System.Collections.Generic.Dictionary< TKey, TValue >._entries, System.Collections.Generic.Dictionary< TKey, TValue >._version, System.Array.Clear(), and System.count.
Referenced by Terraria.IO.Preferences.Clear(), Terraria.GameContent.Drawing.TileDrawing.ClearCachedTileDraws(), System.Collections.ObjectModel.KeyedCollection< TKey, TItem >.ClearItems(), Newtonsoft.Json.Linq.JPropertyKeyedCollection.ClearItems(), Terraria.GameContent.Drawing.TileDrawing.ClearLegacyCachedDraws(), CsvHelper.CsvReader.ClearRecordCache(), CsvHelper.CsvWriter.ClearRecordCache(), Terraria.GameInput.TriggersSet.CloneFrom(), Terraria.Recipe.CollectItemsToCraftWithFrom(), Terraria.WorldGen.countDirtTiles(), Terraria.WorldGen.countTiles(), ReLogic.Content.Sources.ZipContentSource.Dispose(), ReLogic.Utilities.TypeInstanceCollection< BaseType >.Dispose(), Terraria.Graphics.TileBatch.FlushLayered(), Terraria.Wiring.HitWire(), Terraria.Chat.Commands.EmojiCommand.Initialize(), Terraria.GameContent.Creative.CreativeItemSacrificesCatalog.Initialize(), Terraria.GameContent.UI.ItemRarity.Initialize(), Terraria.ID.ContentSamples.Initialize(), Terraria.IO.FavoritesFile.Load(), Terraria.Localization.LanguageManager.LoadLanguage(), Terraria.Main.LoadSettings(), Terraria.Wiring.LogicGatePass(), System.Security.Cryptography.CryptoConfig.CryptoHandler.OnEndParsing(), Terraria.GameContent.ChumBucketProjectileHelper.OnPreUpdateAllProjectiles(), Terraria.Wiring.PixelBoxPass(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.PrepareNPCNetIDsByTypeDictionary(), Terraria.GameInput.KeyConfiguration.ReadPreferences(), Terraria.ID.ContentSamples.RebuildBestiarySortingIDsByBestiaryDatabaseContents(), ReLogic.Content.Sources.FileSystemContentSource.Refresh(), ReLogic.Content.Sources.ZipContentSource.Refresh(), FullSerializer.fsContext.Reset(), Terraria.GameContent.Bestiary.NPCKillsTracker.Reset(), Terraria.GameContent.Creative.ItemsSacrificedUnlocksTracker.Reset(), Terraria.GameContent.PressurePlateHelper.Reset(), Terraria.GameInput.KeyConfiguration.SetupKeys(), Terraria.GameInput.TriggersSet.SetupKeys(), Terraria.UI.ItemSorting.SetupWhiteLists(), Terraria.WorldGen.Shimmerator(), Microsoft.Xna.Framework.Content.ContentManager.Unload(), rail.RailCallBackHelper.UnregisterAllCallback(), Terraria.GameContent.PressurePlateHelper.Update(), ReLogic.Content.AssetChangeWatcher.UpdateSources(), and Terraria.GameContent.Tile_Entities.TELogicSensor.UpdateStartInternal().