Terraria Decompiled: System.Collections.Generic.Dictionary.FindEntry
FindEntry()
int System.Collections.Generic.Dictionary< TKey, TValue >.FindEntry (TKey key) inline private
Definition at line 385 of file Dictionary.cs.
        {
            if (key == null)
            {
                ThrowHelper.ThrowArgumentNullException(ExceptionArgument.key);
            }
            int num = -1;
            int[] buckets = this._buckets;
            Dictionary<TKey, TValue>.Entry[] entries = this._entries;
            int num2 = 0;
            if (buckets != null)
            {
                IEqualityComparer<TKey> comparer = this._comparer;
                if (comparer == null)
                {
                    int num3 = key.GetHashCode() & int.MaxValue;
                    num = buckets[num3 % buckets.Length] - 1;
                    if (default(TKey) != null)
                    {
                        while (num < entries.Length && (entries[num].hashCode != num3 || !EqualityComparer<TKey>.Default.Equals(entries[num].key, key)))
{
                            num = entries[num].next;
                            if (num2 >= entries.Length)
{
                                ThrowHelper.ThrowInvalidOperationException_ConcurrentOperationsNotSupported();
                            }
                            num2++;
                        }
                    }
                    else
                    {
                        EqualityComparer<TKey> @default = EqualityComparer<TKey>.Default;
                        while (num < entries.Length && (entries[num].hashCode != num3 || !@default.Equals(entries[num].key, key)))
{
                            num = entries[num].next;
                            if (num2 >= entries.Length)
{
                                ThrowHelper.ThrowInvalidOperationException_ConcurrentOperationsNotSupported();
                            }
                            num2++;
                        }
                    }
                }
                else
                {
                    int num4 = comparer.GetHashCode(key) & int.MaxValue;
                    num = buckets[num4 % buckets.Length] - 1;
                    while (num < entries.Length && (entries[num].hashCode != num4 || !comparer.Equals(entries[num].key, key)))
                    {
                        num = entries[num].next;
                        if (num2 >= entries.Length)
{
                            ThrowHelper.ThrowInvalidOperationException_ConcurrentOperationsNotSupported();
                        }
                        num2++;
                    }
                }
            }
            return num;
        }
References System.Collections.Generic.Dictionary< TKey, TValue >._buckets, System.Collections.Generic.Dictionary< TKey, TValue >._comparer, System.Collections.Generic.Dictionary< TKey, TValue >._entries, System.comparer, System.Collections.Generic.EqualityComparer< T >.Default, System.Collections.IEqualityComparer.GetHashCode(), System.key, System.ThrowHelper.ThrowArgumentNullException(), and System.ThrowHelper.ThrowInvalidOperationException_ConcurrentOperationsNotSupported().
Referenced by System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), and System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue().