Terraria Decompiled: System.Collections.Generic.Dictionary.TryInsert
TryInsert()
bool System.Collections.Generic.Dictionary< TKey, TValue >.TryInsert (TKey key, TValue value, InsertionBehavior behavior) inline private
Definition at line 457 of file Dictionary.cs.
        {
            if (key == null)
            {
                ThrowHelper.ThrowArgumentNullException(ExceptionArgument.key);
            }
            this._version++;
            if (this._buckets == null)
            {
                this.Initialize(0);
            }
            Dictionary<TKey, TValue>.Entry[] array = this._entries;
            IEqualityComparer<TKey> comparer = this._comparer;
            int num = ((comparer == null) ? key.GetHashCode() : comparer.GetHashCode(key)) & int.MaxValue;
            int num2 = 0;
            ref int ptr = ref this._buckets[num % this._buckets.Length];
            int i = ptr - 1;
            if (comparer == null)
            {
                if (default(TKey) != null)
                {
                    while (i < array.Length)
                    {
                        if (array[i].hashCode == num && EqualityComparer<TKey>.Default.Equals(array[i].key, key))
{
                            if (behavior == InsertionBehavior.OverwriteExisting)
{
                                array[i].value = value;
                                return true;
                            }
                            if (behavior == InsertionBehavior.ThrowOnExisting)
{
                                ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(key);
                            }
                            return false;
                        }
                        else
{
                            i = array[i].next;
                            if (num2 >= array.Length)
{
                                ThrowHelper.ThrowInvalidOperationException_ConcurrentOperationsNotSupported();
                            }
                            num2++;
                        }
                    }
                }
                else
                {
                    EqualityComparer<TKey> @default = EqualityComparer<TKey>.Default;
                    while (i < array.Length)
                    {
                        if (array[i].hashCode == num && @default.Equals(array[i].key, key))
{
                            if (behavior == InsertionBehavior.OverwriteExisting)
{
                                array[i].value = value;
                                return true;
                            }
                            if (behavior == InsertionBehavior.ThrowOnExisting)
{
                                ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(key);
                            }
                            return false;
                        }
                        else
{
                            i = array[i].next;
                            if (num2 >= array.Length)
{
                                ThrowHelper.ThrowInvalidOperationException_ConcurrentOperationsNotSupported();
                            }
                            num2++;
                        }
                    }
                }
            }
            else
            {
                while (i < array.Length)
                {
                    if (array[i].hashCode == num && comparer.Equals(array[i].key, key))
                    {
                        if (behavior == InsertionBehavior.OverwriteExisting)
{
                            array[i].value = value;
                            return true;
                        }
                        if (behavior == InsertionBehavior.ThrowOnExisting)
{
                            ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(key);
                        }
                        return false;
                    }
                    else
                    {
                        i = array[i].next;
                        if (num2 >= array.Length)
{
                            ThrowHelper.ThrowInvalidOperationException_ConcurrentOperationsNotSupported();
                        }
                        num2++;
                    }
                }
            }
            bool flag = false;
            bool flag2 = false;
            int num3;
            if (this._freeCount > 0)
            {
                num3 = this._freeList;
                flag2 = true;
                this._freeCount--;
            }
            else
            {
                int count = this._count;
                if (count == array.Length)
                {
                    this.Resize();
                    flag = true;
                }
                num3 = count;
                this._count = count + 1;
                array = this._entries;
            }
            ref int ptr2 = (ref flag ? ref this._buckets[num % this._buckets.Length] : ref ptr);
            ref Dictionary<TKey, TValue>.Entry ptr3 = ref array[num3];
            if (flag2)
            {
                this._freeList = ptr3.next;
            }
            ptr3.hashCode = num;
            ptr3.next = ptr2 - 1;
            ptr3.key = key;
            ptr3.value = value;
            ptr2 = num3 + 1;
            return true;
        }
References System.Collections.Generic.Dictionary< TKey, TValue >._buckets, System.Collections.Generic.Dictionary< TKey, TValue >._comparer, System.Collections.Generic.Dictionary< TKey, TValue >._count, System.Collections.Generic.Dictionary< TKey, TValue >._entries, System.Collections.Generic.Dictionary< TKey, TValue >._freeCount, System.Collections.Generic.Dictionary< TKey, TValue >._freeList, System.Collections.Generic.Dictionary< TKey, TValue >._version, System.array, System.comparer, System.count, System.Collections.Generic.EqualityComparer< T >.Default, System.Default, System.Collections.Generic.EqualityComparer< T >.Equals(), System.Collections.Generic.Dictionary< TKey, TValue >.Initialize(), System.key, System.Collections.Generic.Dictionary< TKey, TValue >.Entry.next, System.Collections.Generic.Dictionary< TKey, TValue >.Resize(), System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(), System.ThrowHelper.ThrowArgumentNullException(), System.ThrowHelper.ThrowInvalidOperationException_ConcurrentOperationsNotSupported(), and System.value.
Referenced by System.Collections.Generic.Dictionary< TKey, TValue >.Add(), and System.Collections.Generic.Dictionary< TKey, TValue >.TryAdd().