Terraria Decompiled: System.Collections.Generic.Dictionary.Add
Add() [3/3]
void System.Collections.Generic.Dictionary< TKey, TValue >.Add (TKey key, TValue value) inline
Implements System.Collections.Generic.IDictionary< TKey, TValue >.
Definition at line 239 of file Dictionary.cs.
        {
            this.TryInsert(key, value, InsertionBehavior.ThrowOnExisting);
        }
References System.Collections.Generic.Dictionary< TKey, TValue >.TryInsert(), and System.value.
Referenced by Ionic.Zip.ZipOutputStream._InitiateCurrentEntry(), ReLogic.Reflection.IdDictionary.Add(), System.Collections.ObjectModel.KeyedCollection< TKey, TItem >.AddKey(), NVorbis.Ogg.ForwardOnlyPageReader.AddPage(), NVorbis.Ogg.PageReader.AddPage(), System.Resources.ResourceWriter.AddResource(), System.Resources.ResourceWriter.AddResource(), System.Resources.ResourceWriter.AddResource(), System.Resources.ResourceWriter.AddResourceData(), System.Resources.ResourceWriter.AddResourceInternal(), System.Resources.ResourceManager.AddResourceSet(), Microsoft.Xna.Framework.GameServiceContainer.AddService(), System.Runtime.Serialization.SerializationInfo.AddValueInternal(), Terraria.Player.BuyItem(), System.Security.Claims.Claim.Claim(), Terraria.GameInput.TriggersSet.CloneFrom(), Terraria.GameInput.PlayerInputProfile.ConditionalAdd(), Terraria.GameInput.PlayerInputProfile.ConditionalAddProfile(), Terraria.GameContent.UI.Minimap.MinimapFrameManager.CreateAndAdd(), System.Collections.ObjectModel.KeyedCollection< TKey, TItem >.CreateDictionary(), Terraria.Social.Steam.AchievementsSocialModule.GetFloatStat(), Terraria.Social.Steam.AchievementsSocialModule.GetIntStat(), Microsoft.Xna.Framework.SDL3_FNAPlatform.GetMicrophones(), Terraria.Wiring.HitWire(), System.Security.Cryptography.CryptoConfig.Initialize(), Terraria.GameContent.UI.ItemRarity.Initialize(), Microsoft.Xna.Framework.SDL2_FNAPlatform.INTERNAL_AddInstance(), Microsoft.Xna.Framework.SDL3_FNAPlatform.INTERNAL_AddInstance(), Ionic.Zip.ZipFile.InternalAddEntry(), Terraria.Localization.LanguageManager.LoadLanguageFromFileTextJson(), Terraria.IO.WorldFile.LoadWeightedPressurePlates(), Terraria.Wiring.LogicGatePass(), Terraria.WorldGen.nextCount(), Terraria.WorldGen.nextDirtCount(), CsvHelper.CsvReader.ParseNamedIndexes(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.PrepareNPCNetIDsByTypeDictionary(), Ionic.Zip.ZipFile.ReadCentralDirectory(), Microsoft.Xna.Framework.Graphics.FNA3D.ReadImageStream(), Ionic.Zip.ZipFile.ReadIntoInstance_Orig(), Terraria.GameInput.KeyConfiguration.ReadPreferences(), ReLogic.Utilities.TypeInstanceCollection< BaseType >.Register< T >(), rail.RailCallBackHelper.RegisterCallback(), Terraria.Achievements.AchievementManager.RegisterIconIndex(), Terraria.GameInput.PlayerInput.Reset(), Terraria.GameInput.PlayerInputProfile.Save(), Terraria.IO.FavoritesFile.SaveFavorite(), Terraria.GameInput.KeyConfiguration.SetupKeys(), Terraria.GameInput.TriggersSet.SetupKeys(), Terraria.UI.ItemSorting.SetupWhiteLists(), Terraria.WorldGen.ShimmeratorNext(), NVorbis.TagData.TagData(), Terraria.WorldBuilding.TileFont.TileFont(), Terraria.GameContent.RGB.VirtualKeyboard.VirtualKeyboard(), Microsoft.Xna.Framework.Graphics.FNA3D.WriteJPGStream(), Microsoft.Xna.Framework.Graphics.FNA3D.WritePNGStream(), and Terraria.GameInput.KeyConfiguration.WritePreferences().