Terraria Decompiled: Steamworks.SteamUser.GetSteamID
GetSteamID()
static CSteamID Steamworks.SteamUser.GetSteamID () inline static
Definition at line 24 of file SteamUser.cs.
        {
            InteropHelp.TestIfAvailableClient();
            return (CSteamID)NativeMethods.ISteamUser_GetSteamID(CSteamAPIContext.GetSteamUser());
        }
References Steamworks.CSteamAPIContext.GetSteamUser(), Steamworks.NativeMethods.ISteamUser_GetSteamID(), and Steamworks.InteropHelp.TestIfAvailableClient().
Referenced by Terraria.Social.Steam.AchievementsSocialModule.GetEncryptionKey(), Terraria.Social.Steam.WorkshopSocialModule.GetTemporaryFolderPath(), Terraria.Social.Steam.NetClientSocialModule.LaunchLocalServer(), Terraria.Social.Steam.NetSocialModule.OnLobbyChatMessage(), Terraria.Social.Steam.NetServerSocialModule.OnP2PSessionRequest(), Terraria.Social.Steam.AchievementsSocialModule.OnUserStatsReceived(), and Terraria.Social.Steam.WorkshopHelper.UGCBased.PublishedItemsFinder.Refresh().