Terraria Decompiled: Terraria.Graphics.Capture.CaptureInterface.ModeChangeSettings.Update
Update()
override void Terraria.Graphics.Capture.CaptureInterface.ModeChangeSettings.Update () inline
Definition at line 1695 of file CaptureInterface.cs.
            {
                if (!this.Selected)
                {
                    return;
                }
                if (CaptureInterface.JustActivated)
                {
                    return;
                }
                PlayerInput.SetZoom_UI();
                Point point = new Point(Main.mouseX, Main.mouseY);
                this.hoveredButton = -1;
                Rectangle rect = this.GetRect();
                this.inUI = rect.Contains(point);
                rect.Inflate(-20, -20);
                rect.Height = 16;
                int y = rect.Y;
                for (int i = 0; i < 7; i++)
                {
                    rect.Y = y + i * 20;
                    if (rect.Contains(point))
                    {
                        this.hoveredButton = i;
                        break;
                    }
                }
                if (Main.mouseLeft && Main.mouseLeftRelease && this.hoveredButton != -1)
                {
                    this.PressButton(this.hoveredButton);
                }
            }
References Microsoft.Xna.Framework.Rectangle.Contains(), Terraria.Graphics.Capture.CaptureInterface.ModeChangeSettings.GetRect(), Terraria.Graphics.Capture.CaptureInterface.ModeChangeSettings.hoveredButton, Microsoft.Xna.Framework.Rectangle.Inflate(), Terraria.Graphics.Capture.CaptureInterface.JustActivated, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.Main.mouseX, Terraria.Main.mouseY, Microsoft.Xna.Framework.Graphics.Point, Terraria.Graphics.Capture.CaptureInterface.ModeChangeSettings.PressButton(), Terraria.Graphics.Capture.CaptureInterface.CaptureInterfaceMode.Selected, Terraria.GameInput.PlayerInput.SetZoom_UI(), and Microsoft.Xna.Framework.Rectangle.Y.