Terraria Decompiled: System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.ConcurrentExclusiveTaskScheduler.TryExecuteTaskInlineOnTargetScheduler
TryExecuteTaskInlineOnTargetScheduler()
bool System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.ConcurrentExclusiveTaskScheduler.TryExecuteTaskInlineOnTargetScheduler (Task task) inline private
Definition at line 530 of file ConcurrentExclusiveSchedulerPair.cs.
            {
                Task<bool> task2 = new Task<bool>(ConcurrentExclusiveSchedulerPair.ConcurrentExclusiveTaskScheduler.s_tryExecuteTaskShim, Tuple.Create<ConcurrentExclusiveSchedulerPair.ConcurrentExclusiveTaskScheduler, Task>(this, task));
                bool result;
                try
                {
                    task2.RunSynchronously(this.m_pair.m_underlyingTaskScheduler);
                    result = task2.Result;
                }
                catch
                {
                    AggregateException exception = task2.Exception;
                    throw;
                }
                finally
                {
                    task2.Dispose();
                }
                return result;
            }
References System.Threading.Tasks.Task< TResult >.Dispose(), System.exception, System.Threading.Tasks.Task< TResult >.Exception, System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.ConcurrentExclusiveTaskScheduler.m_pair, System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.m_underlyingTaskScheduler, System.Threading.Tasks.Task< TResult >.Result, System.Threading.Tasks.Task< TResult >.RunSynchronously(), System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.ConcurrentExclusiveTaskScheduler.s_tryExecuteTaskShim, and System.task.
Referenced by System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.ConcurrentExclusiveTaskScheduler.TryExecuteTaskInline().