Terraria Decompiled: System.Security.SecureString.InsertAt
InsertAt()
void System.Security.SecureString.InsertAt (int index, char c) inline
Definition at line 130 of file SecureString.cs.
        {
            if (this.disposed)
            {
                throw new ObjectDisposedException("SecureString");
            }
            if (this.read_only)
            {
                throw new InvalidOperationException(Locale.GetText("SecureString is read-only."));
            }
            if (index < 0 || index > this.length)
            {
                throw new ArgumentOutOfRangeException("index", "< 0 || > length");
            }
            if (this.length >= 65536)
            {
                string text = Locale.GetText("Maximum string size is '{0}'.", new object[] { 65536 });
                throw new ArgumentOutOfRangeException("index", text);
            }
            try
            {
                this.Decrypt();
                int num = this.length + 1;
                this.length = num;
                this.Alloc(num, true);
                int num2 = index * 2;
                Buffer.BlockCopy(this.data, num2, this.data, num2 + 2, this.data.Length - num2 - 2);
                this.data[num2++] = (byte)(c >> 8);
                this.data[num2] = (byte)c;
            }
            finally
            {
                this.Encrypt();
            }
        }
References System.Security.SecureString.Alloc(), System.Buffer.BlockCopy(), System.Security.SecureString.data, System.Security.SecureString.Decrypt(), System.Security.SecureString.disposed, System.Security.SecureString.Encrypt(), Locale.GetText(), System.index, System.Security.SecureString.length, System.Security.SecureString.read_only, and System.text.