Terraria Decompiled: System.Security.SecureString.GetBuffer
GetBuffer()
byte[] System.Security.SecureString.GetBuffer () inline package
Definition at line 283 of file SecureString.cs.
        {
            byte[] array = new byte[this.length << 1];
            try
            {
                this.Decrypt();
                Buffer.BlockCopy(this.data, 0, array, 0, array.Length);
            }
            finally
            {
                this.Encrypt();
            }
            return array;
        }
References System.array, System.Buffer.BlockCopy(), System.Security.SecureString.data, System.Security.SecureString.Decrypt(), and System.Security.SecureString.Encrypt().