Terraria Decompiled: NVorbis.Mdct.MdctImpl.MdctImpl
MdctImpl()
NVorbis.Mdct.MdctImpl.MdctImpl (int n) inline
Definition at line 37 of file Mdct.cs.
            {
                this._n = n;
                this._n2 = n >> 1;
                this._n4 = this._n2 >> 1;
                this._n8 = this._n4 >> 1;
                this._ld = Utils.ilog(n) - 1;
                this._a = new float[this._n2];
                this._b = new float[this._n2];
                this._c = new float[this._n4];
                int i;
                int num = (i = 0);
                while (i < this._n4)
                {
                    this._a[num] = (float)Math.Cos((double)((float)(4 * i) * 3.1415927f / (float)n));
                    this._a[num + 1] = (float)(-(float)Math.Sin((double)((float)(4 * i) * 3.1415927f / (float)n)));
                    this._b[num] = (float)Math.Cos((double)((float)(num + 1) * 3.1415927f / (float)n / 2f)) * 0.5f;
                    this._b[num + 1] = (float)Math.Sin((double)((float)(num + 1) * 3.1415927f / (float)n / 2f)) * 0.5f;
                    i++;
                    num += 2;
                }
                num = (i = 0);
                while (i < this._n8)
                {
                    this._c[num] = (float)Math.Cos((double)((float)(2 * (num + 1)) * 3.1415927f / (float)n));
                    this._c[num + 1] = (float)(-(float)Math.Sin((double)((float)(2 * (num + 1)) * 3.1415927f / (float)n)));
                    i++;
                    num += 2;
                }
                this._bitrev = new ushort[this._n8];
                for (int j = 0; j < this._n8; j++)
                {
                    this._bitrev[j] = (ushort)(Utils.BitReverse((uint)j, this._ld - 3) << 2);
                }
            }
References NVorbis.Mdct.MdctImpl._a, NVorbis.Mdct.MdctImpl._b, NVorbis.Mdct.MdctImpl._bitrev, NVorbis.Mdct.MdctImpl._c, NVorbis.Mdct.MdctImpl._n2, NVorbis.Mdct.MdctImpl._n4, NVorbis.Mdct.MdctImpl._n8, NVorbis.Utils.BitReverse(), System.Math.Cos(), NVorbis.Utils.ilog(), and System.Math.Sin().