Terraria Decompiled: Terraria.GameContent.UI.Elements.UIBestiaryEntryGrid.FillBestiarySpaceWithEntries
FillBestiarySpaceWithEntries()
void Terraria.GameContent.UI.Elements.UIBestiaryEntryGrid.FillBestiarySpaceWithEntries () inline
Definition at line 66 of file UIBestiaryEntryGrid.cs.
        {
            base.RemoveAllChildren();
            this.UpdateEntries();
            int num;
            int num2;
            int num3;
            this.GetEntriesToShow(out num, out num2, out num3);
            this.FixBestiaryRange(0, num3);
            int atEntryIndex = this._atEntryIndex;
            int num4 = Math.Min(this._lastEntry, atEntryIndex + num3);
            List<BestiaryEntry> list = new List<BestiaryEntry>();
            for (int i = atEntryIndex; i < num4; i++)
            {
                list.Add(this._workingSetEntries[i]);
            }
            int num5 = 0;
            float num6 = 0.5f / (float)num;
            float num7 = 0.5f / (float)num2;
            for (int j = 0; j < num2; j++)
            {
                int num8 = 0;
                while (num8 < num && num5 < list.Count)
                {
                    UIElement uielement = new UIBestiaryEntryButton(list[num5], false);
                    num5++;
                    uielement.OnLeftClick += this._clickOnEntryEvent;
                    uielement.VAlign = (uielement.HAlign = 0.5f);
                    uielement.Left.Set(0f, (float)num8 / (float)num - 0.5f + num6);
                    uielement.Top.Set(0f, (float)j / (float)num2 - 0.5f + num7);
                    uielement.SetSnapPoint("Entries", num5, new Vector2?(new Vector2(0.2f, 0.7f)), null);
                    base.Append(uielement);
                    num8++;
                }
            }
        }
References Terraria.GameContent.UI.Elements.UIBestiaryEntryGrid._atEntryIndex, Terraria.GameContent.UI.Elements.UIBestiaryEntryGrid._clickOnEntryEvent, Terraria.GameContent.UI.Elements.UIBestiaryEntryGrid._lastEntry, Terraria.GameContent.UI.Elements.UIBestiaryEntryGrid._workingSetEntries, Terraria.GameContent.UI.Elements.UIBestiaryEntryGrid.FixBestiaryRange(), Terraria.GameContent.UI.Elements.UIBestiaryEntryGrid.GetEntriesToShow(), Terraria.UI.UIElement.Left, System.list, System.Math.Min(), Terraria.UI.StyleDimension.Set(), Terraria.UI.UIElement.SetSnapPoint(), Terraria.UI.UIElement.Top, and Terraria.GameContent.UI.Elements.UIBestiaryEntryGrid.UpdateEntries().
Referenced by Terraria.GameContent.UI.States.UIBestiaryTest.FillBestiarySpaceWithEntries(), Terraria.GameContent.UI.Elements.UIBestiaryEntryGrid.OffsetLibrary(), Terraria.GameContent.UI.Elements.UIBestiaryEntryGrid.Recalculate(), and Terraria.GameContent.UI.Elements.UIBestiaryEntryGrid.UIBestiaryEntryGrid().