Terraria Decompiled: NVorbis.Mdct.MdctImpl.CalcReverse
CalcReverse()
void NVorbis.Mdct.MdctImpl.CalcReverse (float[] buffer) inline package
Definition at line 74 of file Mdct.cs.
            {
                float[] array = new float[this._n2];
                int i = this._n2 - 2;
                int num = 0;
                int num2 = 0;
                int n = this._n2;
                while (num2 != n)
                {
                    array[i + 1] = buffer[num2] * this._a[num] - buffer[num2 + 2] * this._a[num + 1];
                    array[i] = buffer[num2] * this._a[num + 1] + buffer[num2 + 2] * this._a[num];
                    i -= 2;
                    num += 2;
                    num2 += 4;
                }
                num2 = this._n2 - 3;
                while (i >= 0)
                {
                    array[i + 1] = -buffer[num2 + 2] * this._a[num] - -buffer[num2] * this._a[num + 1];
                    array[i] = -buffer[num2 + 2] * this._a[num + 1] + -buffer[num2] * this._a[num];
                    i -= 2;
                    num += 2;
                    num2 -= 4;
                }
                float[] array2 = array;
                int j = this._n2 - 8;
                int num3 = this._n4;
                int num4 = 0;
                int num5 = this._n4;
                int num6 = 0;
                while (j >= 0)
                {
                    float num7 = array2[num3 + 1] - array2[num4 + 1];
                    float num8 = array2[num3] - array2[num4];
                    buffer[num5 + 1] = array2[num3 + 1] + array2[num4 + 1];
                    buffer[num5] = array2[num3] + array2[num4];
                    buffer[num6 + 1] = num7 * this._a[j + 4] - num8 * this._a[j + 5];
                    buffer[num6] = num8 * this._a[j + 4] + num7 * this._a[j + 5];
                    num7 = array2[num3 + 3] - array2[num4 + 3];
                    num8 = array2[num3 + 2] - array2[num4 + 2];
                    buffer[num5 + 3] = array2[num3 + 3] + array2[num4 + 3];
                    buffer[num5 + 2] = array2[num3 + 2] + array2[num4 + 2];
                    buffer[num6 + 3] = num7 * this._a[j] - num8 * this._a[j + 1];
                    buffer[num6 + 2] = num8 * this._a[j] + num7 * this._a[j + 1];
                    j -= 8;
                    num5 += 4;
                    num6 += 4;
                    num3 += 4;
                    num4 += 4;
                }
                int num9 = this._n >> 4;
                int num10 = this._n2 - 1;
                int n2 = this._n4;
                this.step3_iter0_loop(num9, buffer, num10 - 0, -this._n8);
                this.step3_iter0_loop(this._n >> 4, buffer, this._n2 - 1 - this._n4, -this._n8);
                int num11 = this._n >> 5;
                int num12 = this._n2 - 1;
                int n3 = this._n8;
                this.step3_inner_r_loop(num11, buffer, num12 - 0, -(this._n >> 4), 16);
                this.step3_inner_r_loop(this._n >> 5, buffer, this._n2 - 1 - this._n8, -(this._n >> 4), 16);
                this.step3_inner_r_loop(this._n >> 5, buffer, this._n2 - 1 - this._n8 * 2, -(this._n >> 4), 16);
                this.step3_inner_r_loop(this._n >> 5, buffer, this._n2 - 1 - this._n8 * 3, -(this._n >> 4), 16);
                int k;
                for (k = 2; k < this._ld - 3 >> 1; k++)
                {
                    int num13 = this._n >> k + 2;
                    int num14 = num13 >> 1;
                    int num15 = 1 << k + 1;
                    for (int l = 0; l < num15; l++)
                    {
                        this.step3_inner_r_loop(this._n >> k + 4, buffer, this._n2 - 1 - num13 * l, -num14, 1 << k + 3);
                    }
                }
                while (k < this._ld - 6)
                {
                    int num16 = this._n >> k + 2;
                    int num17 = 1 << k + 3;
                    int num18 = num16 >> 1;
                    int num19 = this._n >> k + 6;
                    int num20 = 1 << k + 1;
                    int num21 = this._n2 - 1;
                    int num22 = 0;
                    for (int m = num19; m > 0; m--)
                    {
                        this.step3_inner_s_loop(num20, buffer, num21, -num18, num22, num17, num16);
                        num22 += num17 * 4;
                        num21 -= 8;
                    }
                    k++;
                }
                this.step3_inner_s_loop_ld654(this._n >> 5, buffer, this._n2 - 1, this._n);
                int num23 = 0;
                int num24 = this._n4 - 4;
                int num25 = this._n2 - 4;
                while (num24 >= 0)
                {
                    int num26 = (int)this._bitrev[num23];
                    array2[num25 + 3] = buffer[num26];
                    array2[num25 + 2] = buffer[num26 + 1];
                    array2[num24 + 3] = buffer[num26 + 2];
                    array2[num24 + 2] = buffer[num26 + 3];
                    num26 = (int)this._bitrev[num23 + 1];
                    array2[num25 + 1] = buffer[num26];
                    array2[num25] = buffer[num26 + 1];
                    array2[num24 + 1] = buffer[num26 + 2];
                    array2[num24] = buffer[num26 + 3];
                    num24 -= 4;
                    num25 -= 4;
                    num23 += 2;
                }
                int num27 = 0;
                int num28 = 0;
                int num29 = this._n2 - 4;
                while (num28 < num29)
                {
                    float num30 = array2[num28] - array2[num29 + 2];
                    float num31 = array2[num28 + 1] + array2[num29 + 3];
                    float num32 = this._c[num27 + 1] * num30 + this._c[num27] * num31;
                    float num33 = this._c[num27 + 1] * num31 - this._c[num27] * num30;
                    float num34 = array2[num28] + array2[num29 + 2];
                    float num35 = array2[num28 + 1] - array2[num29 + 3];
                    array2[num28] = num34 + num32;
                    array2[num28 + 1] = num35 + num33;
                    array2[num29 + 2] = num34 - num32;
                    array2[num29 + 3] = num33 - num35;
                    num30 = array2[num28 + 2] - array2[num29];
                    num31 = array2[num28 + 3] + array2[num29 + 1];
                    num32 = this._c[num27 + 3] * num30 + this._c[num27 + 2] * num31;
                    num33 = this._c[num27 + 3] * num31 - this._c[num27 + 2] * num30;
                    num34 = array2[num28 + 2] + array2[num29];
                    num35 = array2[num28 + 3] - array2[num29 + 1];
                    array2[num28 + 2] = num34 + num32;
                    array2[num28 + 3] = num35 + num33;
                    array2[num29] = num34 - num32;
                    array2[num29 + 1] = num33 - num35;
                    num27 += 4;
                    num28 += 4;
                    num29 -= 4;
                }
                int num36 = this._n2 - 8;
                int num37 = this._n2 - 8;
                int num38 = 0;
                int num39 = this._n2 - 4;
                int num40 = this._n2;
                int num41 = this._n - 4;
                while (num37 >= 0)
                {
                    float num42 = array[num37 + 6] * this._b[num36 + 7] - array[num37 + 7] * this._b[num36 + 6];
                    float num43 = -array[num37 + 6] * this._b[num36 + 6] - array[num37 + 7] * this._b[num36 + 7];
                    buffer[num38] = num42;
                    buffer[num39 + 3] = -num42;
                    buffer[num40] = num43;
                    buffer[num41 + 3] = num43;
                    float num44 = array[num37 + 4] * this._b[num36 + 5] - array[num37 + 5] * this._b[num36 + 4];
                    float num45 = -array[num37 + 4] * this._b[num36 + 4] - array[num37 + 5] * this._b[num36 + 5];
                    buffer[num38 + 1] = num44;
                    buffer[num39 + 2] = -num44;
                    buffer[num40 + 1] = num45;
                    buffer[num41 + 2] = num45;
                    num42 = array[num37 + 2] * this._b[num36 + 3] - array[num37 + 3] * this._b[num36 + 2];
                    num43 = -array[num37 + 2] * this._b[num36 + 2] - array[num37 + 3] * this._b[num36 + 3];
                    buffer[num38 + 2] = num42;
                    buffer[num39 + 1] = -num42;
                    buffer[num40 + 2] = num43;
                    buffer[num41 + 1] = num43;
                    num44 = array[num37] * this._b[num36 + 1] - array[num37 + 1] * this._b[num36];
                    num45 = -array[num37] * this._b[num36] - array[num37 + 1] * this._b[num36 + 1];
                    buffer[num38 + 3] = num44;
                    buffer[num39] = -num44;
                    buffer[num40 + 3] = num45;
                    buffer[num41] = num45;
                    num36 -= 8;
                    num37 -= 8;
                    num38 += 4;
                    num40 += 4;
                    num39 -= 4;
                    num41 -= 4;
                }
            }
References NVorbis.Mdct.MdctImpl._a, NVorbis.Mdct.MdctImpl._b, NVorbis.Mdct.MdctImpl._bitrev, NVorbis.Mdct.MdctImpl._c, NVorbis.Mdct.MdctImpl._ld, NVorbis.Mdct.MdctImpl._n, NVorbis.Mdct.MdctImpl._n2, NVorbis.Mdct.MdctImpl._n4, NVorbis.Mdct.MdctImpl._n8, System.array, int, NVorbis.Mdct.MdctImpl.step3_inner_r_loop(), NVorbis.Mdct.MdctImpl.step3_inner_s_loop(), NVorbis.Mdct.MdctImpl.step3_inner_s_loop_ld654(), and NVorbis.Mdct.MdctImpl.step3_iter0_loop().
Referenced by NVorbis.Mdct.Reverse().