Terraria Decompiled: Terraria.GameContent.Golf.GolfHelper.HitGolfBall
HitGolfBall()
static void Terraria.GameContent.Golf.GolfHelper.HitGolfBall (Entity entity, Vector2 velocity, float roughLandResistance) inline static
Definition at line 208 of file GolfHelper.cs.
        {
            Vector2 bottom = entity.Bottom;
            bottom.Y += 1f;
            Point point = bottom.ToTileCoordinates();
            Tile tile = Main.tile[point.X, point.Y];
            if (tile != null && tile.active())
            {
                TileMaterial byTileId = TileMaterials.GetByTileId(tile.type);
                velocity = Vector2.Lerp(velocity * byTileId.GolfPhysics.ClubImpactDampening, velocity, byTileId.GolfPhysics.ImpactDampeningResistanceEfficiency * roughLandResistance);
            }
            entity.velocity = velocity;
            Projectile projectile = entity as Projectile;
            if (projectile != null)
            {
                projectile.timeLeft = 18000;
                if (projectile.ai[1] < 0f)
                {
                    projectile.ai[1] = 0f;
                }
                projectile.ai[1] += 1f;
                projectile.localAI[1] = 1f;
                Main.LocalGolfState.RecordSwing(projectile);
            }
        }
References Terraria.Tile.active(), Terraria.Projectile.ai, Terraria.Entity.Bottom, Terraria.GameContent.Metadata.TileGolfPhysics.ClubImpactDampening, Terraria.GameContent.Metadata.TileMaterials.GetByTileId(), Terraria.GameContent.Metadata.TileMaterial.GolfPhysics, Terraria.GameContent.Metadata.TileGolfPhysics.ImpactDampeningResistanceEfficiency, Microsoft.Xna.Framework.Vector2.Lerp(), Terraria.Projectile.localAI, Terraria.Main.LocalGolfState, Terraria.Main.tile, Terraria.Tile.type, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.Projectile.AI_150_GolfClubHelper(), and Terraria.GameContent.Golf.FancyGolfPredictionLine.Update().