Terraria Decompiled: Terraria.GameContent.UI.NewCraftingUI.ItemGrid.DrawSlot
DrawSlot()
override void Terraria.GameContent.UI.NewCraftingUI.ItemGrid.DrawSlot (SpriteBatch spriteBatch, NewCraftingUI::RecipeEntry entry, Vector2 pos, bool hovering) inline protected
Definition at line 938 of file NewCraftingUI.cs.
            {
                Item createItem = entry.Recipe.createItem;
                int num = 41;
                if (PlayerInput.UsingGamepad && NewCraftingUI.IsGridPoint(UILinkPointNavigator.CurrentPoint))
                {
                    ItemSlot.DrawSelectionHighlightForGridSlot = false;
                    UILinkPointNavigator.Shortcuts.ItemSlotShouldHighlightAsSelected = hovering;
                }
                else
                {
                    int index = entry.index;
                    int? selectedRecipeIndex = this.parent._selectedRecipeIndex;
                    ItemSlot.DrawSelectionHighlightForGridSlot = (index == selectedRecipeIndex.GetValueOrDefault()) & (selectedRecipeIndex != null);
                    UILinkPointNavigator.Shortcuts.ItemSlotShouldHighlightAsSelected = false;
                }
                if (hovering)
                {
                    this.parent._hoveredEntry = entry;
                    this.parent.HandleCraftSlot(entry, 41);
                }
                ItemSlot.Draw(spriteBatch, ref createItem, num, pos, entry.Available ? Color.White : NewCraftingUI.DisabledSlotColor);
            }
References Terraria.GameContent.UI.NewCraftingUI._selectedRecipeIndex, Terraria.UI.Gamepad.UILinkPointNavigator.CurrentPoint, Terraria.GameContent.UI.NewCraftingUI.DisabledSlotColor, Terraria.UI.ItemSlot.Draw(), Terraria.GameContent.UI.NewCraftingUI.HandleCraftSlot(), System.index, Terraria.GameContent.UI.NewCraftingUI.IsGridPoint(), Terraria.GameContent.UI.NewCraftingUI.ItemGrid.parent, Terraria.GameInput.PlayerInput.UsingGamepad, and Microsoft.Xna.Framework.Color.White.