Terraria Decompiled: Terraria.GameContent.Drawing.HorizonHelper.Test_DrawSmallTarget
Test_DrawSmallTarget()
void Terraria.GameContent.Drawing.HorizonHelper.Test_DrawSmallTarget (RenderTarget2D bigTarget, Rectangle sunSampleRect) inline private
Definition at line 75 of file HorizonHelper.cs.
        {
            GraphicsDevice graphicsDevice = Main.instance.GraphicsDevice;
            graphicsDevice.SetRenderTarget(bigTarget);
            Main.spriteBatch.Begin(SpriteSortMode.Immediate, new BlendState
            {
                ColorDestinationBlend = Blend.Zero,
                ColorSourceBlend = Blend.SourceAlpha,
                AlphaDestinationBlend = Blend.Zero,
                AlphaSourceBlend = Blend.SourceAlpha
            }, SamplerState.PointClamp, DepthStencilState.Default, RasterizerState.CullCounterClockwise);
            Main.spriteBatch.Draw(this._tinyTarget, new Rectangle(0, 0, sunSampleRect.Width, sunSampleRect.Height), Color.White);
            Main.spriteBatch.End();
            Main.spriteBatch.Begin();
            Main.spriteBatch.Draw(TextureAssets.MagicPixel.Value, new Rectangle(sunSampleRect.Left, sunSampleRect.Top, 1, sunSampleRect.Height), Color.Red);
            Main.spriteBatch.Draw(TextureAssets.MagicPixel.Value, new Rectangle(sunSampleRect.Right, sunSampleRect.Top, 1, sunSampleRect.Height), Color.Red);
            Main.spriteBatch.Draw(TextureAssets.MagicPixel.Value, new Rectangle(sunSampleRect.Left, sunSampleRect.Top, sunSampleRect.Width, 1), Color.Red);
            Main.spriteBatch.Draw(TextureAssets.MagicPixel.Value, new Rectangle(sunSampleRect.Left, sunSampleRect.Bottom, sunSampleRect.Width, 1), Color.Red);
            Main.spriteBatch.Draw(TextureAssets.MagicPixel.Value, new Rectangle(sunSampleRect.Width, 0, 1, sunSampleRect.Height), Color.Red);
            Main.spriteBatch.Draw(TextureAssets.MagicPixel.Value, new Rectangle(0, sunSampleRect.Height, sunSampleRect.Width, 1), Color.Red);
            byte[] array = new byte[1];
            this._pixelTarget.GetData<byte>(array);
            float num = (float)array[0] / 255f;
            Utils.DrawBorderString(Main.spriteBatch, string.Format("{0:F3}", num), new Vector2(10f, (float)(sunSampleRect.Height + 20)), Color.White, 1f, 0f, 0f, -1);
            Main.spriteBatch.End();
            graphicsDevice.SetRenderTarget(null);
        }
References Terraria.GameContent.Drawing.HorizonHelper._pixelTarget, Terraria.GameContent.Drawing.HorizonHelper._tinyTarget, System.array, Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(), Microsoft.Xna.Framework.Rectangle.Bottom, Microsoft.Xna.Framework.Graphics.RasterizerState.CullCounterClockwise, Microsoft.Xna.Framework.Graphics.DepthStencilState.Default, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Utils.DrawBorderString(), Microsoft.Xna.Framework.Graphics.SpriteBatch.End(), Microsoft.Xna.Framework.Game.GraphicsDevice, Microsoft.Xna.Framework.Rectangle.Height, Terraria.Main.instance, Microsoft.Xna.Framework.Rectangle.Left, Terraria.GameContent.TextureAssets.MagicPixel, Microsoft.Xna.Framework.Graphics.SamplerState.PointClamp, Microsoft.Xna.Framework.Color.Red, Microsoft.Xna.Framework.Rectangle.Right, Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetRenderTarget(), Terraria.Main.spriteBatch, Microsoft.Xna.Framework.Rectangle.Top, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Color.White, and Microsoft.Xna.Framework.Rectangle.Width.
Referenced by Terraria.GameContent.Drawing.HorizonHelper.UpdateSunVisibility().