Terraria Decompiled: Terraria.GameContent.Drawing.HorizonHelper.UpdateSunVisibility
UpdateSunVisibility()
void Terraria.GameContent.Drawing.HorizonHelper.UpdateSunVisibility (RenderTarget2D bigTarget) inline
Definition at line 37 of file HorizonHelper.cs.
        {
            this._targetUpToDate = false;
            if (!Main.ForegroundSunlightEffects || bigTarget == null)
            {
                return;
            }
            TimeLogger.StartTimestamp startTimestamp = TimeLogger.Start();
            GraphicsDevice graphicsDevice = Main.instance.GraphicsDevice;
            if (this._tinyTarget == null || this._tinyTarget.IsContentLost)
            {
                this._tinyTarget = new RenderTarget2D(graphicsDevice, this.SmallTextureSize, this.SmallTextureSize, true, SurfaceFormat.Alpha8, DepthFormat.None);
            }
            if (this._pixelTarget == null || this._pixelTarget.IsContentLost)
            {
                this._pixelTarget = new RenderTarget2D(graphicsDevice, 1, 1, false, SurfaceFormat.Alpha8, DepthFormat.None);
            }
            Rectangle rectangle = Utils.CenteredRectangle(Main.ReverseGravitySupport(Main.LastCelestialBodyPosition * Main.ScreenSize.ToVector2(), 0f), new Vector2((float)this.SampleAreaSize) * Main.BackgroundViewMatrix.RenderZoom);
            if (HorizonHelper.DebugSunVisibility)
            {
                this.Test_DrawSmallTarget(bigTarget, rectangle);
            }
            graphicsDevice.SetRenderTarget(this._tinyTarget);
            graphicsDevice.Clear(Color.Transparent);
            Main.spriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend, SamplerState.PointClamp, DepthStencilState.Default, RasterizerState.CullCounterClockwise);
            Main.spriteBatch.Draw(bigTarget, this._tinyTarget.Bounds, new Rectangle?(rectangle), Color.White);
            Main.spriteBatch.End();
            graphicsDevice.SetRenderTarget(this._pixelTarget);
            graphicsDevice.Clear(Color.White);
            Main.spriteBatch.Begin(SpriteSortMode.Immediate, this._horizonBlendState, SamplerState.LinearClamp, DepthStencilState.Default, RasterizerState.CullCounterClockwise);
            Main.spriteBatch.Draw(this._tinyTarget, this._pixelTarget.Bounds, Color.White);
            Main.spriteBatch.End();
            graphicsDevice.SetRenderTarget(null);
            this._targetUpToDate = true;
            TimeLogger.SunVisibility.AddTime(startTimestamp);
        }
References Terraria.GameContent.Drawing.HorizonHelper._pixelTarget, Terraria.GameContent.Drawing.HorizonHelper._tinyTarget, Microsoft.Xna.Framework.Graphics.BlendState.AlphaBlend, Terraria.Main.BackgroundViewMatrix, Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(), Microsoft.Xna.Framework.Graphics.Texture2D.Bounds, Terraria.Utils.CenteredRectangle(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.Clear(), Microsoft.Xna.Framework.Graphics.RasterizerState.CullCounterClockwise, Terraria.GameContent.Drawing.HorizonHelper.DebugSunVisibility, Microsoft.Xna.Framework.Graphics.DepthStencilState.Default, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.End(), Terraria.Main.ForegroundSunlightEffects, Microsoft.Xna.Framework.Game.GraphicsDevice, Terraria.Main.instance, Microsoft.Xna.Framework.Graphics.RenderTarget2D.IsContentLost, Terraria.Main.LastCelestialBodyPosition, Microsoft.Xna.Framework.Graphics.SamplerState.LinearClamp, Microsoft.Xna.Framework.Graphics.SamplerState.PointClamp, Terraria.Main.ReverseGravitySupport(), Terraria.GameContent.Drawing.HorizonHelper.SampleAreaSize, Terraria.Main.ScreenSize, Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetRenderTarget(), Terraria.GameContent.Drawing.HorizonHelper.SmallTextureSize, Terraria.Main.spriteBatch, Terraria.TimeLogger.Start(), Terraria.TimeLogger.SunVisibility, Terraria.GameContent.Drawing.HorizonHelper.Test_DrawSmallTarget(), Microsoft.Xna.Framework.Color.Transparent, and Microsoft.Xna.Framework.Color.White.