Terraria Decompiled: Terraria.GameContent.UI.States.UIManageControls.OnInitialize
OnInitialize()
override void Terraria.GameContent.UI.States.UIManageControls.OnInitialize () inline virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 25 of file UIManageControls.cs.
        {
            this._KeyboardGamepadTexture = Main.Assets.Request<Texture2D>("Images/UI/Settings_Inputs", 1);
            this._keyboardGamepadBorderTexture = Main.Assets.Request<Texture2D>("Images/UI/Settings_Inputs_Border", 1);
            this._GameplayVsUITexture = Main.Assets.Request<Texture2D>("Images/UI/Settings_Inputs_2", 1);
            this._GameplayVsUIBorderTexture = Main.Assets.Request<Texture2D>("Images/UI/Settings_Inputs_2_Border", 1);
            UIElement uielement = new UIElement();
            uielement.Width.Set(0f, 0.8f);
            uielement.MaxWidth.Set(600f, 0f);
            uielement.Top.Set(220f, 0f);
            uielement.Height.Set(-200f, 1f);
            uielement.HAlign = 0.5f;
            this._outerContainer = uielement;
            UIPanel uipanel = new UIPanel();
            uipanel.Width.Set(0f, 1f);
            uipanel.Height.Set(-110f, 1f);
            uipanel.BackgroundColor = new Color(33, 43, 79) * 0.8f;
            uielement.Append(uipanel);
            this._buttonKeyboard = new UIImageFramed(this._KeyboardGamepadTexture, this._KeyboardGamepadTexture.Frame(2, 2, 0, 0, 0, 0));
            this._buttonKeyboard.VAlign = 0f;
            this._buttonKeyboard.HAlign = 0f;
            this._buttonKeyboard.Left.Set(0f, 0f);
            this._buttonKeyboard.Top.Set(8f, 0f);
            this._buttonKeyboard.OnLeftClick += this.KeyboardButtonClick;
            this._buttonKeyboard.OnMouseOver += this.ManageBorderKeyboardOn;
            this._buttonKeyboard.OnMouseOut += this.ManageBorderKeyboardOff;
            uipanel.Append(this._buttonKeyboard);
            this._buttonGamepad = new UIImageFramed(this._KeyboardGamepadTexture, this._KeyboardGamepadTexture.Frame(2, 2, 1, 1, 0, 0));
            this._buttonGamepad.VAlign = 0f;
            this._buttonGamepad.HAlign = 0f;
            this._buttonGamepad.Left.Set(76f, 0f);
            this._buttonGamepad.Top.Set(8f, 0f);
            this._buttonGamepad.OnLeftClick += this.GamepadButtonClick;
            this._buttonGamepad.OnMouseOver += this.ManageBorderGamepadOn;
            this._buttonGamepad.OnMouseOut += this.ManageBorderGamepadOff;
            uipanel.Append(this._buttonGamepad);
            this._buttonBorder1 = new UIImageFramed(this._keyboardGamepadBorderTexture, this._keyboardGamepadBorderTexture.Frame(1, 1, 0, 0, 0, 0));
            this._buttonBorder1.VAlign = 0f;
            this._buttonBorder1.HAlign = 0f;
            this._buttonBorder1.Left.Set(0f, 0f);
            this._buttonBorder1.Top.Set(8f, 0f);
            this._buttonBorder1.Color = Color.Silver;
            this._buttonBorder1.IgnoresMouseInteraction = true;
            uipanel.Append(this._buttonBorder1);
            this._buttonBorder2 = new UIImageFramed(this._keyboardGamepadBorderTexture, this._keyboardGamepadBorderTexture.Frame(1, 1, 0, 0, 0, 0));
            this._buttonBorder2.VAlign = 0f;
            this._buttonBorder2.HAlign = 0f;
            this._buttonBorder2.Left.Set(76f, 0f);
            this._buttonBorder2.Top.Set(8f, 0f);
            this._buttonBorder2.Color = Color.Transparent;
            this._buttonBorder2.IgnoresMouseInteraction = true;
            uipanel.Append(this._buttonBorder2);
            this._buttonVs1 = new UIImageFramed(this._GameplayVsUITexture, this._GameplayVsUITexture.Frame(2, 2, 0, 0, 0, 0));
            this._buttonVs1.VAlign = 0f;
            this._buttonVs1.HAlign = 0f;
            this._buttonVs1.Left.Set(172f, 0f);
            this._buttonVs1.Top.Set(8f, 0f);
            this._buttonVs1.OnLeftClick += this.VsGameplayButtonClick;
            this._buttonVs1.OnMouseOver += this.ManageBorderGameplayOn;
            this._buttonVs1.OnMouseOut += this.ManageBorderGameplayOff;
            uipanel.Append(this._buttonVs1);
            this._buttonVs2 = new UIImageFramed(this._GameplayVsUITexture, this._GameplayVsUITexture.Frame(2, 2, 1, 1, 0, 0));
            this._buttonVs2.VAlign = 0f;
            this._buttonVs2.HAlign = 0f;
            this._buttonVs2.Left.Set(212f, 0f);
            this._buttonVs2.Top.Set(8f, 0f);
            this._buttonVs2.OnLeftClick += this.VsMenuButtonClick;
            this._buttonVs2.OnMouseOver += this.ManageBorderMenuOn;
            this._buttonVs2.OnMouseOut += this.ManageBorderMenuOff;
            uipanel.Append(this._buttonVs2);
            this._buttonBorderVs1 = new UIImageFramed(this._GameplayVsUIBorderTexture, this._GameplayVsUIBorderTexture.Frame(1, 1, 0, 0, 0, 0));
            this._buttonBorderVs1.VAlign = 0f;
            this._buttonBorderVs1.HAlign = 0f;
            this._buttonBorderVs1.Left.Set(172f, 0f);
            this._buttonBorderVs1.Top.Set(8f, 0f);
            this._buttonBorderVs1.Color = Color.Silver;
            this._buttonBorderVs1.IgnoresMouseInteraction = true;
            uipanel.Append(this._buttonBorderVs1);
            this._buttonBorderVs2 = new UIImageFramed(this._GameplayVsUIBorderTexture, this._GameplayVsUIBorderTexture.Frame(1, 1, 0, 0, 0, 0));
            this._buttonBorderVs2.VAlign = 0f;
            this._buttonBorderVs2.HAlign = 0f;
            this._buttonBorderVs2.Left.Set(212f, 0f);
            this._buttonBorderVs2.Top.Set(8f, 0f);
            this._buttonBorderVs2.Color = Color.Transparent;
            this._buttonBorderVs2.IgnoresMouseInteraction = true;
            uipanel.Append(this._buttonBorderVs2);
            this._buttonStyle = new UIKeybindingSimpleListItem(() => this.controllerGlyphStyle(), new Color(73, 94, 171, 255) * 0.9f);
            this._buttonStyle.VAlign = 0f;
            this._buttonStyle.HAlign = 1f;
            this._buttonStyle.Width.Set(100f, 0f);
            this._buttonStyle.Height.Set(30f, 0f);
            this._buttonStyle.MarginRight = 220f;
            this._buttonStyle.Left.Set(0f, 0f);
            this._buttonStyle.Top.Set(8f, 0f);
            this._buttonStyle.OnLeftClick += this.controllerGlyphButtonClick;
            uipanel.Append(this._buttonStyle);
            this._buttonProfile = new UIKeybindingSimpleListItem(() => PlayerInput.CurrentProfile.ShowName, new Color(73, 94, 171, 255) * 0.9f);
            this._buttonProfile.VAlign = 0f;
            this._buttonProfile.HAlign = 1f;
            this._buttonProfile.Width.Set(180f, 0f);
            this._buttonProfile.Height.Set(30f, 0f);
            this._buttonProfile.MarginRight = 30f;
            this._buttonProfile.Left.Set(0f, 0f);
            this._buttonProfile.Top.Set(8f, 0f);
            this._buttonProfile.OnLeftClick += this.profileButtonClick;
            uipanel.Append(this._buttonProfile);
            this._uilist = new UIList();
            this._uilist.Width.Set(-25f, 1f);
            this._uilist.Height.Set(-50f, 1f);
            this._uilist.VAlign = 1f;
            this._uilist.PaddingBottom = 5f;
            this._uilist.ListPadding = 20f;
            uipanel.Append(this._uilist);
            this.AssembleBindPanels();
            this.FillList();
            UIScrollbar uiscrollbar = new UIScrollbar(UIScrollbar.ColorTheme.Blue);
            uiscrollbar.SetView(100f, 1000f);
            uiscrollbar.Height.Set(-67f, 1f);
            uiscrollbar.HAlign = 1f;
            uiscrollbar.VAlign = 1f;
            uiscrollbar.MarginBottom = 11f;
            uipanel.Append(uiscrollbar);
            this._uilist.SetScrollbar(uiscrollbar);
            UITextPanel<LocalizedText> uitextPanel = new UITextPanel<LocalizedText>(Language.GetText("UI.Keybindings"), 0.7f, true);
            uitextPanel.HAlign = 0.5f;
            uitextPanel.Top.Set(-45f, 0f);
            uitextPanel.Left.Set(-10f, 0f);
            uitextPanel.SetPadding(15f);
            uitextPanel.BackgroundColor = new Color(73, 94, 171);
            uielement.Append(uitextPanel);
            UITextPanel<LocalizedText> uitextPanel2 = new UITextPanel<LocalizedText>(Language.GetText("UI.Back"), 0.7f, true);
            uitextPanel2.Width.Set(-10f, 0.5f);
            uitextPanel2.Height.Set(50f, 0f);
            uitextPanel2.VAlign = 1f;
            uitextPanel2.HAlign = 0.5f;
            uitextPanel2.Top.Set(-45f, 0f);
            uitextPanel2.OnMouseOver += this.FadedMouseOver;
            uitextPanel2.OnMouseOut += this.FadedMouseOut;
            uitextPanel2.OnLeftClick += this.GoBackClick;
            uielement.Append(uitextPanel2);
            this._buttonBack = uitextPanel2;
            base.Append(uielement);
        }
References Terraria.GameContent.UI.States.UIManageControls._buttonBorder1, Terraria.GameContent.UI.States.UIManageControls._buttonBorder2, Terraria.GameContent.UI.States.UIManageControls._buttonBorderVs1, Terraria.GameContent.UI.States.UIManageControls._buttonBorderVs2, Terraria.GameContent.UI.States.UIManageControls._buttonGamepad, Terraria.GameContent.UI.States.UIManageControls._buttonKeyboard, Terraria.GameContent.UI.States.UIManageControls._buttonProfile, Terraria.GameContent.UI.States.UIManageControls._buttonStyle, Terraria.GameContent.UI.States.UIManageControls._buttonVs1, Terraria.GameContent.UI.States.UIManageControls._buttonVs2, Terraria.GameContent.UI.States.UIManageControls._GameplayVsUIBorderTexture, Terraria.GameContent.UI.States.UIManageControls._GameplayVsUITexture, Terraria.GameContent.UI.States.UIManageControls._keyboardGamepadBorderTexture, Terraria.GameContent.UI.States.UIManageControls._KeyboardGamepadTexture, Terraria.GameContent.UI.States.UIManageControls._uilist, Terraria.UI.UIElement.Append(), Terraria.GameContent.UI.States.UIManageControls.AssembleBindPanels(), Terraria.Main.Assets, Microsoft.Xna.Framework.Graphics.Color, Terraria.GameContent.UI.States.UIManageControls.controllerGlyphButtonClick(), Terraria.GameContent.UI.States.UIManageControls.controllerGlyphStyle(), Terraria.GameInput.PlayerInput.CurrentProfile, Terraria.GameContent.UI.States.UIManageControls.FadedMouseOut(), Terraria.GameContent.UI.States.UIManageControls.FadedMouseOver(), Terraria.GameContent.UI.States.UIManageControls.FillList(), Terraria.GameContent.UI.States.UIManageControls.GamepadButtonClick(), Terraria.Localization.Language.GetText(), Terraria.GameContent.UI.States.UIManageControls.GoBackClick(), Terraria.UI.UIElement.Height, Terraria.GameContent.UI.States.UIManageControls.KeyboardButtonClick(), Terraria.UI.UIElement.Left, Terraria.GameContent.UI.States.UIManageControls.ManageBorderGamepadOff(), Terraria.GameContent.UI.States.UIManageControls.ManageBorderGamepadOn(), Terraria.GameContent.UI.States.UIManageControls.ManageBorderGameplayOff(), Terraria.GameContent.UI.States.UIManageControls.ManageBorderGameplayOn(), Terraria.GameContent.UI.States.UIManageControls.ManageBorderKeyboardOff(), Terraria.GameContent.UI.States.UIManageControls.ManageBorderKeyboardOn(), Terraria.GameContent.UI.States.UIManageControls.ManageBorderMenuOff(), Terraria.GameContent.UI.States.UIManageControls.ManageBorderMenuOn(), Terraria.GameContent.UI.States.UIManageControls.profileButtonClick(), Terraria.UI.StyleDimension.Set(), Terraria.UI.UIElement.SetPadding(), Terraria.GameContent.UI.Elements.UIList.SetScrollbar(), Terraria.GameContent.UI.Elements.UIScrollbar.SetView(), Terraria.GameInput.PlayerInputProfile.ShowName, Microsoft.Xna.Framework.Color.Silver, Terraria.UI.UIElement.Top, Microsoft.Xna.Framework.Color.Transparent, Terraria.UI.UIElement.UIElement(), Terraria.GameContent.UI.States.UIManageControls.VsGameplayButtonClick(), Terraria.GameContent.UI.States.UIManageControls.VsMenuButtonClick(), and Terraria.UI.UIElement.Width.