Terraria Decompiled: Terraria.GameContent.UI.States.UIManageControls.VsGameplayButtonClick
VsGameplayButtonClick()
void Terraria.GameContent.UI.States.UIManageControls.VsGameplayButtonClick (UIMouseEvent evt, UIElement listeningElement) inline private
Definition at line 850 of file UIManageControls.cs.
        {
            this._buttonVs1.SetFrame(this._GameplayVsUITexture.Frame(2, 2, 0, 0, 0, 0));
            this._buttonVs2.SetFrame(this._GameplayVsUITexture.Frame(2, 2, 1, 1, 0, 0));
            this.OnGameplay = true;
            this.FillList();
        }
References Terraria.GameContent.UI.States.UIManageControls._buttonVs1, Terraria.GameContent.UI.States.UIManageControls._buttonVs2, Terraria.GameContent.UI.States.UIManageControls._GameplayVsUITexture, Terraria.GameContent.UI.States.UIManageControls.FillList(), and Terraria.GameContent.UI.Elements.UIImageFramed.SetFrame().
Referenced by Terraria.GameContent.UI.States.UIManageControls.OnInitialize().