Terraria Decompiled: Terraria.GameContent.UI.States.UIManageControls.AssembleBindPanels
AssembleBindPanels()
void Terraria.GameContent.UI.States.UIManageControls.AssembleBindPanels () inline private
Definition at line 170 of file UIManageControls.cs.
        {
            List<string> list = new List<string>
            {
                "MouseLeft", "MouseRight", "Up", "Down", "Left", "Right", "Jump", "Grapple", "SmartSelect", "SmartCursor",
                "QuickMount", "QuickHeal", "QuickMana", "QuickBuff", "Throw", "Inventory", "ToggleCreativeMenu", "ViewZoomIn", "ViewZoomOut", "Loadout1",
                "Loadout2", "Loadout3", "NextLoadout", "PreviousLoadout", "ToggleCameraMode", "ArmorSetAbility", "Dash", "sp20", "sp9"
            };
            List<string> list2 = new List<string>
            {
                "MouseLeft", "MouseRight", "Up", "Down", "Left", "Right", "Jump", "Grapple", "SmartSelect", "SmartCursor",
                "QuickMount", "QuickHeal", "QuickMana", "QuickBuff", "LockOn", "Throw", "Inventory", "Loadout1", "Loadout2", "Loadout3",
                "NextLoadout", "PreviousLoadout", "ToggleCameraMode", "ArmorSetAbility", "Dash", "sp20", "sp9"
            };
            List<string> list3 = new List<string>
            {
                "HotbarMinus", "HotbarPlus", "Hotbar1", "Hotbar2", "Hotbar3", "Hotbar4", "Hotbar5", "Hotbar6", "Hotbar7", "Hotbar8",
                "Hotbar9", "Hotbar10", "sp10"
            };
            List<string> list4 = new List<string> { "MapZoomIn", "MapZoomOut", "MapAlphaUp", "MapAlphaDown", "MapFull", "MapStyle", "sp11" };
            List<string> list5 = new List<string> { "sp1", "sp2", "RadialHotbar", "RadialQuickbar", "sp12" };
            List<string> list6 = new List<string>
            {
                "sp3", "sp4", "sp5", "sp6", "sp7", "sp8", "sp14", "sp15", "sp16", "sp17",
                "sp18", "sp19", "sp13"
            };
            InputMode inputMode = InputMode.Keyboard;
            this._bindsKeyboard.Add(this.CreateBindingGroup(0, list, inputMode));
            this._bindsKeyboard.Add(this.CreateBindingGroup(1, list4, inputMode));
            this._bindsKeyboard.Add(this.CreateBindingGroup(2, list3, inputMode));
            inputMode = InputMode.XBoxGamepad;
            this._bindsGamepad.Add(this.CreateBindingGroup(0, list2, inputMode));
            this._bindsGamepad.Add(this.CreateBindingGroup(1, list4, inputMode));
            this._bindsGamepad.Add(this.CreateBindingGroup(2, list3, inputMode));
            this._bindsGamepad.Add(this.CreateBindingGroup(3, list5, inputMode));
            this._bindsGamepad.Add(this.CreateBindingGroup(4, list6, inputMode));
            inputMode = InputMode.KeyboardUI;
            this._bindsKeyboardUI.Add(this.CreateBindingGroup(0, list, inputMode));
            this._bindsKeyboardUI.Add(this.CreateBindingGroup(1, list4, inputMode));
            this._bindsKeyboardUI.Add(this.CreateBindingGroup(2, list3, inputMode));
            inputMode = InputMode.XBoxGamepadUI;
            this._bindsGamepadUI.Add(this.CreateBindingGroup(0, list2, inputMode));
            this._bindsGamepadUI.Add(this.CreateBindingGroup(1, list4, inputMode));
            this._bindsGamepadUI.Add(this.CreateBindingGroup(2, list3, inputMode));
            this._bindsGamepadUI.Add(this.CreateBindingGroup(3, list5, inputMode));
            this._bindsGamepadUI.Add(this.CreateBindingGroup(4, list6, inputMode));
        }
References Terraria.GameContent.UI.States.UIManageControls._bindsGamepad, Terraria.GameContent.UI.States.UIManageControls._bindsGamepadUI, Terraria.GameContent.UI.States.UIManageControls._bindsKeyboard, Terraria.GameContent.UI.States.UIManageControls._bindsKeyboardUI, System.Collections.Generic.List< T >.Add(), Terraria.GameContent.UI.States.UIManageControls.CreateBindingGroup(), and System.list.
Referenced by Terraria.GameContent.UI.States.UIManageControls.OnInitialize().