Terraria Decompiled: Terraria.GameContent.UI.States.UIManageControls.CreatePanel
CreatePanel()
UIElement Terraria.GameContent.UI.States.UIManageControls.CreatePanel (string bind, InputMode currentInputMode, Color color) inline
Definition at line 341 of file UIManageControls.cs.
        {
            uint num = <PrivateImplementationDetails>.ComputeStringHash(bind);
            if (num <= 1316519504U)
            {
                if (num <= 172078476U)
                {
                    if (num <= 121745619U)
                    {
                        if (num != 104968000U)
{
                            if (num == 121745619U)
{
                                if (bind == "sp7")
{
                                    return new UIKeybindingSliderItem(() => Lang.menu[203].Value + " (" + PlayerInput.CurrentProfile.RightThumbstickDeadzoneX.ToString("P1") + ")", () => PlayerInput.CurrentProfile.RightThumbstickDeadzoneX, delegate(float f)
{
                                        PlayerInput.CurrentProfile.RightThumbstickDeadzoneX = f;
                                    }, delegate
{
                                        PlayerInput.CurrentProfile.RightThumbstickDeadzoneX = UILinksInitializer.HandleSliderHorizontalInput(PlayerInput.CurrentProfile.RightThumbstickDeadzoneX, 0f, 0.95f, PlayerInput.CurrentProfile.InterfaceDeadzoneX, 0.35f);
                                    }, 1004, color);
                                }
                            }
                        }
                        else if (bind == "sp6")
{
                            return new UIKeybindingSliderItem(() => Lang.menu[202].Value + " (" + PlayerInput.CurrentProfile.LeftThumbstickDeadzoneY.ToString("P1") + ")", () => PlayerInput.CurrentProfile.LeftThumbstickDeadzoneY, delegate(float f)
{
                                PlayerInput.CurrentProfile.LeftThumbstickDeadzoneY = f;
                            }, delegate
{
                                PlayerInput.CurrentProfile.LeftThumbstickDeadzoneY = UILinksInitializer.HandleSliderHorizontalInput(PlayerInput.CurrentProfile.LeftThumbstickDeadzoneY, 0f, 0.95f, PlayerInput.CurrentProfile.InterfaceDeadzoneX, 0.35f);
                            }, 1003, color);
                        }
                    }
                    else if (num != 138523238U)
                    {
                        if (num != 155300857U)
{
                            if (num == 172078476U)
{
                                if (bind == "sp2")
{
                                    UIKeybindingToggleListItem uikeybindingToggleListItem = new UIKeybindingToggleListItem(() => Lang.menu[197].Value, () => PlayerInput.CurrentProfile.InputModes[InputMode.XBoxGamepad].KeyStatus["DpadRadial1"].Contains(Buttons.DPadUp.ToString()) && PlayerInput.CurrentProfile.InputModes[InputMode.XBoxGamepad].KeyStatus["DpadRadial2"].Contains(Buttons.DPadRight.ToString()) && PlayerInput.CurrentProfile.InputModes[InputMode.XBoxGamepad].KeyStatus["DpadRadial3"].Contains(Buttons.DPadDown.ToString()) && PlayerInput.CurrentProfile.InputModes[InputMode.XBoxGamepad].KeyStatus["DpadRadial4"].Contains(Buttons.DPadLeft.ToString()) && PlayerInput.CurrentProfile.InputModes[InputMode.XBoxGamepadUI].KeyStatus["DpadRadial1"].Contains(Buttons.DPadUp.ToString()) && PlayerInput.CurrentProfile.InputModes[InputMode.XBoxGamepadUI].KeyStatus["DpadRadial2"].Contains(Buttons.DPadRight.ToString()) && PlayerInput.CurrentProfile.InputModes[InputMode.XBoxGamepadUI].KeyStatus["DpadRadial3"].Contains(Buttons.DPadDown.ToString()) && PlayerInput.CurrentProfile.InputModes[InputMode.XBoxGamepadUI].KeyStatus["DpadRadial4"].Contains(Buttons.DPadLeft.ToString()), color);
                                    uikeybindingToggleListItem.OnLeftClick += this.RadialButtonClick;
                                    return uikeybindingToggleListItem;
                                }
                            }
                        }
                        else if (bind == "sp5")
{
                            return new UIKeybindingSliderItem(() => Lang.menu[201].Value + " (" + PlayerInput.CurrentProfile.LeftThumbstickDeadzoneX.ToString("P1") + ")", () => PlayerInput.CurrentProfile.LeftThumbstickDeadzoneX, delegate(float f)
{
                                PlayerInput.CurrentProfile.LeftThumbstickDeadzoneX = f;
                            }, delegate
{
                                PlayerInput.CurrentProfile.LeftThumbstickDeadzoneX = UILinksInitializer.HandleSliderHorizontalInput(PlayerInput.CurrentProfile.LeftThumbstickDeadzoneX, 0f, 0.95f, PlayerInput.CurrentProfile.InterfaceDeadzoneX, 0.35f);
                            }, 1002, color);
                        }
                    }
                    else if (bind == "sp4")
                    {
                        return new UIKeybindingSliderItem(() => Lang.menu[200].Value + " (" + PlayerInput.CurrentProfile.InterfaceDeadzoneX.ToString("P1") + ")", () => PlayerInput.CurrentProfile.InterfaceDeadzoneX, delegate(float f)
{
                            PlayerInput.CurrentProfile.InterfaceDeadzoneX = f;
                        }, delegate
{
                            PlayerInput.CurrentProfile.InterfaceDeadzoneX = UILinksInitializer.HandleSliderHorizontalInput(PlayerInput.CurrentProfile.InterfaceDeadzoneX, 0f, 0.95f, 0.35f, 0.35f);
                        }, 1001, color);
                    }
                }
                else if (num <= 222411333U)
                {
                    if (num != 188856095U)
                    {
                        if (num == 222411333U)
{
                            if (bind == "sp1")
{
                                UIKeybindingToggleListItem uikeybindingToggleListItem2 = new UIKeybindingToggleListItem(() => Lang.menu[196].Value, () => PlayerInput.CurrentProfile.InputModes[InputMode.XBoxGamepad].KeyStatus["DpadSnap1"].Contains(Buttons.DPadUp.ToString()) && PlayerInput.CurrentProfile.InputModes[InputMode.XBoxGamepad].KeyStatus["DpadSnap2"].Contains(Buttons.DPadRight.ToString()) && PlayerInput.CurrentProfile.InputModes[InputMode.XBoxGamepad].KeyStatus["DpadSnap3"].Contains(Buttons.DPadDown.ToString()) && PlayerInput.CurrentProfile.InputModes[InputMode.XBoxGamepad].KeyStatus["DpadSnap4"].Contains(Buttons.DPadLeft.ToString()) && PlayerInput.CurrentProfile.InputModes[InputMode.XBoxGamepadUI].KeyStatus["DpadSnap1"].Contains(Buttons.DPadUp.ToString()) && PlayerInput.CurrentProfile.InputModes[InputMode.XBoxGamepadUI].KeyStatus["DpadSnap2"].Contains(Buttons.DPadRight.ToString()) && PlayerInput.CurrentProfile.InputModes[InputMode.XBoxGamepadUI].KeyStatus["DpadSnap3"].Contains(Buttons.DPadDown.ToString()) && PlayerInput.CurrentProfile.InputModes[InputMode.XBoxGamepadUI].KeyStatus["DpadSnap4"].Contains(Buttons.DPadLeft.ToString()), color);
                                uikeybindingToggleListItem2.OnLeftClick += this.SnapButtonClick;
                                return uikeybindingToggleListItem2;
                            }
                        }
                    }
                    else if (bind == "sp3")
                    {
                        return new UIKeybindingSliderItem(() => Lang.menu[199].Value + " (" + PlayerInput.CurrentProfile.TriggersDeadzone.ToString("P1") + ")", () => PlayerInput.CurrentProfile.TriggersDeadzone, delegate(float f)
{
                            PlayerInput.CurrentProfile.TriggersDeadzone = f;
                        }, delegate
{
                            PlayerInput.CurrentProfile.TriggersDeadzone = UILinksInitializer.HandleSliderHorizontalInput(PlayerInput.CurrentProfile.TriggersDeadzone, 0f, 0.95f, PlayerInput.CurrentProfile.InterfaceDeadzoneX, 0.35f);
                        }, 1000, color);
                    }
                }
                else if (num != 339854666U)
                {
                    if (num != 356632285U)
                    {
                        if (num == 1316519504U)
{
                            if (bind == "sp15")
{
                                UIKeybindingToggleListItem uikeybindingToggleListItem3 = new UIKeybindingToggleListItem(() => Lang.menu[206].Value, () => PlayerInput.CurrentProfile.LeftThumbstickInvertY, color);
                                uikeybindingToggleListItem3.OnLeftClick += delegate(UIMouseEvent evt, UIElement listeningElement)
{
                                    if (PlayerInput.CurrentProfile.AllowEditing)
{
                                        PlayerInput.CurrentProfile.LeftThumbstickInvertY = !PlayerInput.CurrentProfile.LeftThumbstickInvertY;
                                    }
                                };
                                return uikeybindingToggleListItem3;
                            }
                        }
                    }
                    else if (bind == "sp9")
                    {
                        UIKeybindingSimpleListItem uikeybindingSimpleListItem = new UIKeybindingSimpleListItem(() => Lang.menu[86].Value, color);
                        uikeybindingSimpleListItem.OnLeftClick += delegate(UIMouseEvent evt, UIElement listeningElement)
{
                            string copyableProfileName = UIManageControls.GetCopyableProfileName();
                            PlayerInput.CurrentProfile.CopyGameplaySettingsFrom(PlayerInput.OriginalProfiles[copyableProfileName], currentInputMode);
                        };
                        return uikeybindingSimpleListItem;
                    }
                }
                else if (bind == "sp8")
                {
                    return new UIKeybindingSliderItem(() => Lang.menu[204].Value + " (" + PlayerInput.CurrentProfile.RightThumbstickDeadzoneY.ToString("P1") + ")", () => PlayerInput.CurrentProfile.RightThumbstickDeadzoneY, delegate(float f)
                    {
                        PlayerInput.CurrentProfile.RightThumbstickDeadzoneY = f;
                    }, delegate
                    {
                        PlayerInput.CurrentProfile.RightThumbstickDeadzoneY = UILinksInitializer.HandleSliderHorizontalInput(PlayerInput.CurrentProfile.RightThumbstickDeadzoneY, 0f, 0.95f, PlayerInput.CurrentProfile.InterfaceDeadzoneX, 0.35f);
                    }, 1005, color);
                }
            }
            else if (num <= 1400407599U)
            {
                if (num <= 1350074742U)
                {
                    if (num != 1333297123U)
                    {
                        if (num == 1350074742U)
{
                            if (bind == "sp17")
{
                                UIKeybindingToggleListItem uikeybindingToggleListItem4 = new UIKeybindingToggleListItem(() => Lang.menu[208].Value, () => PlayerInput.CurrentProfile.RightThumbstickInvertY, color);
                                uikeybindingToggleListItem4.OnLeftClick += delegate(UIMouseEvent evt, UIElement listeningElement)
{
                                    if (PlayerInput.CurrentProfile.AllowEditing)
{
                                        PlayerInput.CurrentProfile.RightThumbstickInvertY = !PlayerInput.CurrentProfile.RightThumbstickInvertY;
                                    }
                                };
                                return uikeybindingToggleListItem4;
                            }
                        }
                    }
                    else if (bind == "sp14")
                    {
                        UIKeybindingToggleListItem uikeybindingToggleListItem5 = new UIKeybindingToggleListItem(() => Lang.menu[205].Value, () => PlayerInput.CurrentProfile.LeftThumbstickInvertX, color);
                        uikeybindingToggleListItem5.OnLeftClick += delegate(UIMouseEvent evt, UIElement listeningElement)
{
                            if (PlayerInput.CurrentProfile.AllowEditing)
{
                                PlayerInput.CurrentProfile.LeftThumbstickInvertX = !PlayerInput.CurrentProfile.LeftThumbstickInvertX;
                            }
                        };
                        return uikeybindingToggleListItem5;
                    }
                }
                else if (num != 1366852361U)
                {
                    if (num != 1383629980U)
                    {
                        if (num == 1400407599U)
{
                            if (bind == "sp10")
{
                                UIKeybindingSimpleListItem uikeybindingSimpleListItem2 = new UIKeybindingSimpleListItem(() => Lang.menu[86].Value, color);
                                uikeybindingSimpleListItem2.OnLeftClick += delegate(UIMouseEvent evt, UIElement listeningElement)
{
                                    string copyableProfileName2 = UIManageControls.GetCopyableProfileName();
                                    PlayerInput.CurrentProfile.CopyHotbarSettingsFrom(PlayerInput.OriginalProfiles[copyableProfileName2], currentInputMode);
                                };
                                return uikeybindingSimpleListItem2;
                            }
                        }
                    }
                    else if (bind == "sp11")
                    {
                        UIKeybindingSimpleListItem uikeybindingSimpleListItem3 = new UIKeybindingSimpleListItem(() => Lang.menu[86].Value, color);
                        uikeybindingSimpleListItem3.OnLeftClick += delegate(UIMouseEvent evt, UIElement listeningElement)
{
                            string copyableProfileName3 = UIManageControls.GetCopyableProfileName();
                            PlayerInput.CurrentProfile.CopyMapSettingsFrom(PlayerInput.OriginalProfiles[copyableProfileName3], currentInputMode);
                        };
                        return uikeybindingSimpleListItem3;
                    }
                }
                else if (bind == "sp16")
                {
                    UIKeybindingToggleListItem uikeybindingToggleListItem6 = new UIKeybindingToggleListItem(() => Lang.menu[207].Value, () => PlayerInput.CurrentProfile.RightThumbstickInvertX, color);
                    uikeybindingToggleListItem6.OnLeftClick += delegate(UIMouseEvent evt, UIElement listeningElement)
                    {
                        if (PlayerInput.CurrentProfile.AllowEditing)
{
                            PlayerInput.CurrentProfile.RightThumbstickInvertX = !PlayerInput.CurrentProfile.RightThumbstickInvertX;
                        }
                    };
                    return uikeybindingToggleListItem6;
                }
            }
            else if (num <= 1433962837U)
            {
                if (num != 1417185218U)
                {
                    if (num == 1433962837U)
                    {
                        if (bind == "sp12")
{
                            UIKeybindingSimpleListItem uikeybindingSimpleListItem4 = new UIKeybindingSimpleListItem(() => Lang.menu[86].Value, color);
                            uikeybindingSimpleListItem4.OnLeftClick += delegate(UIMouseEvent evt, UIElement listeningElement)
{
                                string copyableProfileName4 = UIManageControls.GetCopyableProfileName();
                                PlayerInput.CurrentProfile.CopyGamepadSettingsFrom(PlayerInput.OriginalProfiles[copyableProfileName4], currentInputMode);
                            };
                            return uikeybindingSimpleListItem4;
                        }
                    }
                }
                else if (bind == "sp13")
                {
                    UIKeybindingSimpleListItem uikeybindingSimpleListItem5 = new UIKeybindingSimpleListItem(() => Lang.menu[86].Value, color);
                    uikeybindingSimpleListItem5.OnLeftClick += delegate(UIMouseEvent evt, UIElement listeningElement)
                    {
                        string copyableProfileName5 = UIManageControls.GetCopyableProfileName();
                        PlayerInput.CurrentProfile.CopyGamepadAdvancedSettingsFrom(PlayerInput.OriginalProfiles[copyableProfileName5], currentInputMode);
                    };
                    return uikeybindingSimpleListItem5;
                }
            }
            else if (num != 1517850932U)
            {
                if (num != 1534628551U)
                {
                    if (num == 3782285044U)
                    {
                        if (bind == "sp20")
{
                            UIKeybindingToggleListItem uikeybindingToggleListItem7 = new UIKeybindingToggleListItem(() => Language.GetTextValue("UI.DoubleTapDash"), () => Player.Settings.DashControl == Player.Settings.DashPreference.AllowDoubleTap, color);
                            uikeybindingToggleListItem7.OnLeftClick += delegate(UIMouseEvent evt, UIElement listeningElement)
{
                                Player.Settings.DashPreference dashControl = Player.Settings.DashControl;
                                if (dashControl == Player.Settings.DashPreference.AllowDoubleTap)
{
                                    Player.Settings.DashControl = Player.Settings.DashPreference.OnlyThroughHotkeys;
                                    return;
                                }
                                if (dashControl != Player.Settings.DashPreference.OnlyThroughHotkeys)
{
                                    return;
                                }
                                Player.Settings.DashControl = Player.Settings.DashPreference.AllowDoubleTap;
                            };
                            return uikeybindingToggleListItem7;
                        }
                    }
                }
                else if (bind == "sp18")
                {
                    return new UIKeybindingSliderItem(delegate
                    {
                        int hotbarRadialHoldTimeRequired = PlayerInput.CurrentProfile.HotbarRadialHoldTimeRequired;
                        if (hotbarRadialHoldTimeRequired == -1)
{
                            return Lang.menu[228].Value;
                        }
                        return Lang.menu[227].Value + " (" + ((float)hotbarRadialHoldTimeRequired / 60f).ToString("F2") + "s)";
                    }, delegate
                    {
                        if (PlayerInput.CurrentProfile.HotbarRadialHoldTimeRequired == -1)
{
                            return 1f;
                        }
                        return (float)PlayerInput.CurrentProfile.HotbarRadialHoldTimeRequired / 301f;
                    }, delegate(float f)
                    {
                        PlayerInput.CurrentProfile.HotbarRadialHoldTimeRequired = (int)(f * 301f);
                        if ((float)PlayerInput.CurrentProfile.HotbarRadialHoldTimeRequired == 301f)
{
                            PlayerInput.CurrentProfile.HotbarRadialHoldTimeRequired = -1;
                        }
                    }, delegate
                    {
                        float num2 = ((PlayerInput.CurrentProfile.HotbarRadialHoldTimeRequired == -1) ? 1f : ((float)PlayerInput.CurrentProfile.HotbarRadialHoldTimeRequired / 301f));
                        num2 = UILinksInitializer.HandleSliderHorizontalInput(num2, 0f, 1f, PlayerInput.CurrentProfile.InterfaceDeadzoneX, 0.5f);
                        PlayerInput.CurrentProfile.HotbarRadialHoldTimeRequired = (int)(num2 * 301f);
                        if ((float)PlayerInput.CurrentProfile.HotbarRadialHoldTimeRequired == 301f)
{
                            PlayerInput.CurrentProfile.HotbarRadialHoldTimeRequired = -1;
                        }
                    }, 1007, color);
                }
            }
            else if (bind == "sp19")
            {
                return new UIKeybindingSliderItem(delegate
                {
                    int inventoryMoveCD = PlayerInput.CurrentProfile.InventoryMoveCD;
                    return Lang.menu[252].Value + " (" + ((float)inventoryMoveCD / 60f).ToString("F2") + "s)";
                }, () => Utils.GetLerpValue(4f, 12f, (float)PlayerInput.CurrentProfile.InventoryMoveCD, true), delegate(float f)
                {
                    PlayerInput.CurrentProfile.InventoryMoveCD = (int)Math.Round((double)MathHelper.Lerp(4f, 12f, f));
                }, delegate
                {
                    if (UILinkPointNavigator.Shortcuts.INV_MOVE_OPTION_CD > 0)
                    {
                        UILinkPointNavigator.Shortcuts.INV_MOVE_OPTION_CD--;
                    }
                    if (UILinkPointNavigator.Shortcuts.INV_MOVE_OPTION_CD == 0)
                    {
                        float lerpValue = Utils.GetLerpValue(4f, 12f, (float)PlayerInput.CurrentProfile.InventoryMoveCD, true);
                        float num3 = UILinksInitializer.HandleSliderHorizontalInput(lerpValue, 0f, 1f, PlayerInput.CurrentProfile.InterfaceDeadzoneX, 0.5f);
                        if (lerpValue != num3)
{
                            UILinkPointNavigator.Shortcuts.INV_MOVE_OPTION_CD = 8;
                            int num4 = Math.Sign(num3 - lerpValue);
                            PlayerInput.CurrentProfile.InventoryMoveCD = (int)MathHelper.Clamp((float)(PlayerInput.CurrentProfile.InventoryMoveCD + num4), 4f, 12f);
                        }
                    }
                }, 1008, color);
            }
            return new UIKeybindingListItem(bind, currentInputMode, color);
        }
References Terraria.GameInput.PlayerInputProfile.AllowEditing, Microsoft.Xna.Framework.MathHelper.Clamp(), Terraria.GameInput.PlayerInputProfile.CopyGamepadAdvancedSettingsFrom(), Terraria.GameInput.PlayerInputProfile.CopyGamepadSettingsFrom(), Terraria.GameInput.PlayerInputProfile.CopyGameplaySettingsFrom(), Terraria.GameInput.PlayerInputProfile.CopyHotbarSettingsFrom(), Terraria.GameInput.PlayerInputProfile.CopyMapSettingsFrom(), Terraria.GameInput.PlayerInput.CurrentProfile, Terraria.Player.Settings.DashControl, Terraria.GameContent.UI.States.UIManageControls.GetCopyableProfileName(), Terraria.Utils.GetLerpValue(), Terraria.Localization.Language.GetTextValue(), Terraria.Initializers.UILinksInitializer.HandleSliderHorizontalInput(), Terraria.GameInput.PlayerInputProfile.HotbarRadialHoldTimeRequired, Terraria.GameInput.PlayerInputProfile.InputModes, int, Terraria.GameInput.PlayerInputProfile.InterfaceDeadzoneX, Terraria.UI.Gamepad.UILinkPointNavigator.Shortcuts.INV_MOVE_OPTION_CD, Terraria.GameInput.PlayerInputProfile.InventoryMoveCD, Terraria.GameInput.PlayerInputProfile.LeftThumbstickDeadzoneX, Terraria.GameInput.PlayerInputProfile.LeftThumbstickDeadzoneY, Terraria.GameInput.PlayerInputProfile.LeftThumbstickInvertX, Terraria.GameInput.PlayerInputProfile.LeftThumbstickInvertY, Microsoft.Xna.Framework.MathHelper.Lerp(), Terraria.Lang.menu, Terraria.GameInput.PlayerInput.OriginalProfiles, Terraria.GameContent.UI.States.UIManageControls.RadialButtonClick(), Terraria.GameInput.PlayerInputProfile.RightThumbstickDeadzoneX, Terraria.GameInput.PlayerInputProfile.RightThumbstickDeadzoneY, Terraria.GameInput.PlayerInputProfile.RightThumbstickInvertX, Terraria.GameInput.PlayerInputProfile.RightThumbstickInvertY, System.Math.Round(), System.Math.Sign(), Terraria.GameContent.UI.States.UIManageControls.SnapButtonClick(), Terraria.GameInput.PlayerInputProfile.TriggersDeadzone, Microsoft.Xna.Framework.Input.U, and Terraria.Localization.LocalizedText.Value.
Referenced by Terraria.GameContent.UI.States.UIManageControls.CreateElementGroup().