Terraria Decompiled: Terraria.GameContent.UI.States.UIManageControls.controllerGlyphStyle
controllerGlyphStyle()
string Terraria.GameContent.UI.States.UIManageControls.controllerGlyphStyle () inline private
Definition at line 896 of file UIManageControls.cs.
        {
            switch (GlyphTagHandler.GlyphStyle)
            {
            case -1:
                return Language.GetText("UI.ControllerGlyphAuto").Value;
            case 1:
                return Language.GetText("UI.ControllerGlyphPlayStation").Value;
            case 2:
                return Language.GetText("UI.ControllerGlyphSwitch").Value;
            }
            return Language.GetText("UI.ControllerGlyphXbox").Value;
        }
References Terraria.Localization.Language.GetText(), Terraria.GameContent.UI.Chat.GlyphTagHandler.GlyphStyle, and Terraria.Localization.LocalizedText.Value.
Referenced by Terraria.GameContent.UI.States.UIManageControls.b__29_0(), and Terraria.GameContent.UI.States.UIManageControls.OnInitialize().