Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteMethodCall
WriteMethodCall()
object[] System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteMethodCall (IMethodCallMessage mcm) inline private
Definition at line 131 of file ObjectWriter.cs.
        {
            string uri = mcm.Uri;
            string methodName = mcm.MethodName;
            string typeName = mcm.TypeName;
            object obj = null;
            object[] array = null;
            Type[] array2 = null;
            if (mcm.MethodBase.IsGenericMethod)
            {
                array2 = mcm.MethodBase.GetGenericArguments();
            }
            object[] args = mcm.Args;
            IInternalMessage internalMessage = mcm as IInternalMessage;
            if (internalMessage == null || internalMessage.HasProperties())
            {
                array = ObjectWriter.StoreUserPropertiesForMethodMessage(mcm);
            }
            if (mcm.MethodSignature != null && RemotingServices.IsMethodOverloaded(mcm))
            {
                obj = mcm.MethodSignature;
            }
            LogicalCallContext logicalCallContext = mcm.LogicalCallContext;
            object obj2;
            if (logicalCallContext == null)
            {
                obj2 = null;
            }
            else if (logicalCallContext.HasInfo)
            {
                obj2 = logicalCallContext;
            }
            else
            {
                obj2 = logicalCallContext.RemotingData.LogicalCallID;
            }
            return this.serWriter.WriteCallArray(uri, methodName, typeName, array2, args, obj, obj2, array);
        }
References System.Runtime.Remoting.Messaging.IMethodMessage.Args, System.array, System.Runtime.Remoting.Messaging.LogicalCallContext.HasInfo, System.Runtime.Remoting.Messaging.IInternalMessage.HasProperties(), System.Runtime.Remoting.RemotingServices.IsMethodOverloaded(), System.Runtime.Remoting.Messaging.IMethodMessage.LogicalCallContext, System.Runtime.Remoting.Messaging.CallContextRemotingData.LogicalCallID, System.Runtime.Remoting.Messaging.IMethodMessage.MethodBase, System.Runtime.Remoting.Messaging.IMethodMessage.MethodName, System.Runtime.Remoting.Messaging.IMethodMessage.MethodSignature, System.obj, System.Runtime.Remoting.Messaging.LogicalCallContext.RemotingData, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.serWriter, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.StoreUserPropertiesForMethodMessage(), System.Runtime.Remoting.Messaging.IMethodMessage.TypeName, System.Runtime.Remoting.Messaging.IMethodMessage.Uri, and System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteCallArray().
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize().