Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write
Write() [1/2]
void System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write (WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo) inline private
Definition at line 263 of file ObjectWriter.cs.
        {
            object obj = objectInfo.obj;
            if (obj == null)
            {
                throw new ArgumentNullException("objectInfo.obj", Environment.GetResourceString("Object cannot be null."));
            }
            Type objectType = objectInfo.objectType;
            long objectId = objectInfo.objectId;
            if (objectType == Converter.typeofString)
            {
                memberNameInfo.NIobjectId = objectId;
                this.serWriter.WriteObjectString((int)objectId, obj.ToString());
                return;
            }
            if (objectInfo.isArray)
            {
                this.WriteArray(objectInfo, memberNameInfo, null);
                return;
            }
            string[] array;
            Type[] array2;
            object[] array3;
            objectInfo.GetMemberInfo(out array, out array2, out array3);
            if (objectInfo.isSi || this.CheckTypeFormat(this.formatterEnums.FEtypeFormat, FormatterTypeStyle.TypesAlways))
            {
                memberNameInfo.NItransmitTypeOnObject = true;
                memberNameInfo.NIisParentTypeOnObject = true;
                typeNameInfo.NItransmitTypeOnObject = true;
                typeNameInfo.NIisParentTypeOnObject = true;
            }
            WriteObjectInfo[] array4 = new WriteObjectInfo[array.Length];
            for (int i = 0; i < array2.Length; i++)
            {
                Type type;
                if (array2[i] != null)
                {
                    type = array2[i];
                }
                else if (array3[i] != null)
                {
                    type = this.GetType(array3[i]);
                }
                else
                {
                    type = Converter.typeofObject;
                }
                if (this.ToCode(type) == InternalPrimitiveTypeE.Invalid && type != Converter.typeofString)
                {
                    if (array3[i] != null)
                    {
                        array4[i] = WriteObjectInfo.Serialize(array3[i], this.m_surrogates, this.m_context, this.serObjectInfoInit, this.m_formatterConverter, this, this.m_binder);
                        array4[i].assemId = this.GetAssemblyId(array4[i]);
                    }
                    else
                    {
                        array4[i] = WriteObjectInfo.Serialize(array2[i], this.m_surrogates, this.m_context, this.serObjectInfoInit, this.m_formatterConverter, this.m_binder);
                        array4[i].assemId = this.GetAssemblyId(array4[i]);
                    }
                }
            }
            this.Write(objectInfo, memberNameInfo, typeNameInfo, array, array2, array3, array4);
        }
References System.array, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.assemId, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.GetAssemblyId(), System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.GetMemberInfo(), System.Environment.GetResourceString(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.GetType(), System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.isArray, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.isSi, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.m_binder, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.m_context, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.m_formatterConverter, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.m_surrogates, System.obj, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.obj, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.objectId, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.objectType, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.Serialize(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.serObjectInfoInit, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.serWriter, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.ToCode(), System.Runtime.Serialization.Formatters.Binary.Converter.typeofObject, System.Runtime.Serialization.Formatters.Binary.Converter.typeofString, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteArray(), and System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteObjectString().
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteArrayMember(), and System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteMembers().