Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteMembers
WriteMembers()
void System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteMembers (NameInfo memberNameInfo, NameInfo memberTypeNameInfo, object memberData, WriteObjectInfo objectInfo, NameInfo typeNameInfo, WriteObjectInfo memberObjectInfo) inline private
Definition at line 408 of file ObjectWriter.cs.
        {
            Type type = memberNameInfo.NItype;
            bool flag = false;
            if (type == Converter.typeofObject || Nullable.GetUnderlyingType(type) != null)
            {
                memberTypeNameInfo.NItransmitTypeOnMember = true;
                memberNameInfo.NItransmitTypeOnMember = true;
            }
            if (this.CheckTypeFormat(this.formatterEnums.FEtypeFormat, FormatterTypeStyle.TypesAlways) || objectInfo.isSi)
            {
                memberTypeNameInfo.NItransmitTypeOnObject = true;
                memberNameInfo.NItransmitTypeOnObject = true;
                memberNameInfo.NIisParentTypeOnObject = true;
            }
            if (this.CheckForNull(objectInfo, memberNameInfo, memberTypeNameInfo, memberData))
            {
                return;
            }
            Type type2 = null;
            if (memberTypeNameInfo.NIprimitiveTypeEnum == InternalPrimitiveTypeE.Invalid)
            {
                type2 = this.GetType(memberData);
                if (type != type2)
                {
                    memberTypeNameInfo.NItransmitTypeOnMember = true;
                    memberNameInfo.NItransmitTypeOnMember = true;
                }
            }
            if (type == Converter.typeofObject)
            {
                flag = true;
                type = this.GetType(memberData);
                if (memberObjectInfo == null)
                {
                    this.TypeToNameInfo(type, memberTypeNameInfo);
                }
                else
                {
                    this.TypeToNameInfo(memberObjectInfo, memberTypeNameInfo);
                }
            }
            if (memberObjectInfo == null || !memberObjectInfo.isArray)
            {
                if (!this.WriteKnownValueClass(memberNameInfo, memberTypeNameInfo, memberData))
                {
                    if (type2 == null)
                    {
                        type2 = this.GetType(memberData);
                    }
                    long num = this.Schedule(memberData, flag, type2, memberObjectInfo);
                    if (num < 0L)
                    {
                        memberObjectInfo.objectId = num;
                        NameInfo nameInfo = this.TypeToNameInfo(memberObjectInfo);
                        nameInfo.NIobjectId = num;
                        this.Write(memberObjectInfo, memberNameInfo, nameInfo);
                        this.PutNameInfo(nameInfo);
                        memberObjectInfo.ObjectEnd();
                        return;
                    }
                    memberNameInfo.NIobjectId = num;
                    this.WriteObjectRef(memberNameInfo, num);
                }
                return;
            }
            if (type2 == null)
            {
                type2 = this.GetType(memberData);
            }
            long num2 = this.Schedule(memberData, false, null, memberObjectInfo);
            if (num2 > 0L)
            {
                memberNameInfo.NIobjectId = num2;
                this.WriteObjectRef(memberNameInfo, num2);
                return;
            }
            this.serWriter.WriteMemberNested(memberNameInfo);
            memberObjectInfo.objectId = num2;
            memberNameInfo.NIobjectId = num2;
            this.WriteArray(memberObjectInfo, memberNameInfo, memberObjectInfo);
            objectInfo.ObjectEnd();
        }
References System.Runtime.Serialization.Formatters.Binary.ObjectWriter.CheckForNull(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.CheckTypeFormat(), System.Runtime.Serialization.Formatters.Binary.InternalFE.FEtypeFormat, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.formatterEnums, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.GetType(), System.Nullable< T >.GetUnderlyingType(), System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.isArray, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.isSi, System.L, System.Runtime.Serialization.Formatters.Binary.NameInfo.NIprimitiveTypeEnum, System.Runtime.Serialization.Formatters.Binary.NameInfo.NItype, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.ObjectEnd(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.PutNameInfo(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Schedule(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.serWriter, System.Runtime.Serialization.Formatters.Binary.Converter.typeofObject, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.TypeToNameInfo(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteArray(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteKnownValueClass(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteMemberNested(), and System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteObjectRef().
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteMemberSetup().