Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize
Serialize()
void System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize (object graph, Header[] inHeaders, __BinaryWriter serWriter, bool fCheck) inline package
Definition at line 27 of file ObjectWriter.cs.
        {
            if (graph == null)
            {
                throw new ArgumentNullException("graph", Environment.GetResourceString("Object Graph cannot be null."));
            }
            if (serWriter == null)
            {
                throw new ArgumentNullException("serWriter", Environment.GetResourceString("Parameter '{0}' cannot be null.", new object[] { "serWriter" }));
            }
            this.serWriter = serWriter;
            this.headers = inHeaders;
            serWriter.WriteBegin();
            long num = 0L;
            bool flag = false;
            bool flag2 = false;
            IMethodCallMessage methodCallMessage = graph as IMethodCallMessage;
            if (methodCallMessage != null)
            {
                flag = true;
                graph = this.WriteMethodCall(methodCallMessage);
            }
            else
            {
                IMethodReturnMessage methodReturnMessage = graph as IMethodReturnMessage;
                if (methodReturnMessage != null)
                {
                    flag2 = true;
                    graph = this.WriteMethodReturn(methodReturnMessage);
                }
            }
            if (graph == null)
            {
                this.WriteSerializedStreamHeader(this.topId, num);
                if (flag)
                {
                    serWriter.WriteMethodCall();
                }
                else if (flag2)
                {
                    serWriter.WriteMethodReturn();
                }
                serWriter.WriteSerializationHeaderEnd();
                serWriter.WriteEnd();
                return;
            }
            this.m_idGenerator = new ObjectIDGenerator();
            this.m_objectQueue = new Queue();
            this.m_formatterConverter = new FormatterConverter();
            this.serObjectInfoInit = new SerObjectInfoInit();
            bool flag3;
            this.topId = this.InternalGetId(graph, false, null, out flag3);
            if (this.headers != null)
            {
                num = this.InternalGetId(this.headers, false, null, out flag3);
            }
            else
            {
                num = -1L;
            }
            this.WriteSerializedStreamHeader(this.topId, num);
            if (flag)
            {
                serWriter.WriteMethodCall();
            }
            else if (flag2)
            {
                serWriter.WriteMethodReturn();
            }
            if (this.headers != null && this.headers.Length != 0)
            {
                this.m_objectQueue.Enqueue(this.headers);
            }
            if (graph != null)
            {
                this.m_objectQueue.Enqueue(graph);
            }
            long num2;
            object next;
            while ((next = this.GetNext(out num2)) != null)
            {
                WriteObjectInfo writeObjectInfo;
                if (next is WriteObjectInfo)
                {
                    writeObjectInfo = (WriteObjectInfo)next;
                }
                else
                {
                    writeObjectInfo = WriteObjectInfo.Serialize(next, this.m_surrogates, this.m_context, this.serObjectInfoInit, this.m_formatterConverter, this, this.m_binder);
                    writeObjectInfo.assemId = this.GetAssemblyId(writeObjectInfo);
                }
                writeObjectInfo.objectId = num2;
                NameInfo nameInfo = this.TypeToNameInfo(writeObjectInfo);
                this.Write(writeObjectInfo, nameInfo, nameInfo);
                this.PutNameInfo(nameInfo);
                writeObjectInfo.ObjectEnd();
            }
            serWriter.WriteSerializationHeaderEnd();
            serWriter.WriteEnd();
            this.m_objectManager.RaiseOnSerializedEvent();
        }
References System.Collections.Queue.Enqueue(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.GetAssemblyId(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.GetNext(), System.Environment.GetResourceString(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.headers, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.InternalGetId(), System.L, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.m_binder, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.m_context, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.m_formatterConverter, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.m_objectManager, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.m_objectQueue, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.m_surrogates, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.ObjectEnd(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.PutNameInfo(), System.Runtime.Serialization.SerializationObjectManager.RaiseOnSerializedEvent(), System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.Serialize(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.serObjectInfoInit, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.serWriter, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.topId, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.TypeToNameInfo(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteBegin(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteEnd(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteMethodCall(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteMethodCall(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteMethodReturn(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteMethodReturn(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteSerializationHeaderEnd(), and System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteSerializedStreamHeader().
Referenced by System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize().