Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteArrayMember
WriteArrayMember()
void System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteArrayMember (WriteObjectInfo objectInfo, NameInfo arrayElemTypeNameInfo, object data) inline private
Definition at line 641 of file ObjectWriter.cs.
        {
            arrayElemTypeNameInfo.NIisArrayItem = true;
            if (this.CheckForNull(objectInfo, arrayElemTypeNameInfo, arrayElemTypeNameInfo, data))
            {
                return;
            }
            Type type = null;
            bool flag = false;
            if (arrayElemTypeNameInfo.NItransmitTypeOnMember)
            {
                flag = true;
            }
            if (!flag && !arrayElemTypeNameInfo.IsSealed)
            {
                type = this.GetType(data);
                if (arrayElemTypeNameInfo.NItype != type)
                {
                    flag = true;
                }
            }
            NameInfo nameInfo;
            if (flag)
            {
                if (type == null)
                {
                    type = this.GetType(data);
                }
                nameInfo = this.TypeToNameInfo(type);
                nameInfo.NItransmitTypeOnMember = true;
                nameInfo.NIobjectId = arrayElemTypeNameInfo.NIobjectId;
                nameInfo.NIassemId = arrayElemTypeNameInfo.NIassemId;
                nameInfo.NIisArrayItem = true;
            }
            else
            {
                nameInfo = arrayElemTypeNameInfo;
                nameInfo.NIisArrayItem = true;
            }
            if (!this.WriteKnownValueClass(arrayElemTypeNameInfo, nameInfo, data))
            {
                bool flag2 = false;
                if (arrayElemTypeNameInfo.NItype == Converter.typeofObject)
                {
                    flag2 = true;
                }
                long num = this.Schedule(data, flag2, nameInfo.NItype);
                arrayElemTypeNameInfo.NIobjectId = num;
                nameInfo.NIobjectId = num;
                if (num < 1L)
                {
                    WriteObjectInfo writeObjectInfo = WriteObjectInfo.Serialize(data, this.m_surrogates, this.m_context, this.serObjectInfoInit, this.m_formatterConverter, this, this.m_binder);
                    writeObjectInfo.objectId = num;
                    if (arrayElemTypeNameInfo.NItype != Converter.typeofObject && Nullable.GetUnderlyingType(arrayElemTypeNameInfo.NItype) == null)
                    {
                        writeObjectInfo.assemId = nameInfo.NIassemId;
                    }
                    else
                    {
                        writeObjectInfo.assemId = this.GetAssemblyId(writeObjectInfo);
                    }
                    NameInfo nameInfo2 = this.TypeToNameInfo(writeObjectInfo);
                    nameInfo2.NIobjectId = num;
                    writeObjectInfo.objectId = num;
                    this.Write(writeObjectInfo, nameInfo, nameInfo2);
                    writeObjectInfo.ObjectEnd();
                }
                else
                {
                    this.serWriter.WriteItemObjectRef(arrayElemTypeNameInfo, (int)num);
                }
            }
            if (arrayElemTypeNameInfo.NItransmitTypeOnMember)
            {
                this.PutNameInfo(nameInfo);
            }
        }
References System.Runtime.Serialization.Formatters.Binary.ObjectWriter.CheckForNull(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.GetAssemblyId(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.GetType(), System.Nullable< T >.GetUnderlyingType(), System.Runtime.Serialization.Formatters.Binary.NameInfo.IsSealed, System.L, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.m_binder, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.m_context, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.m_formatterConverter, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.m_surrogates, System.Runtime.Serialization.Formatters.Binary.NameInfo.NIassemId, System.Runtime.Serialization.Formatters.Binary.NameInfo.NIobjectId, System.Runtime.Serialization.Formatters.Binary.NameInfo.NItransmitTypeOnMember, System.Runtime.Serialization.Formatters.Binary.NameInfo.NItype, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.ObjectEnd(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.PutNameInfo(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Schedule(), System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.Serialize(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.serObjectInfoInit, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.serWriter, System.Runtime.Serialization.Formatters.Binary.Converter.typeofObject, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.TypeToNameInfo(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteItemObjectRef(), and System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteKnownValueClass().
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteArray(), and System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteRectangle().