Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteKnownValueClass
WriteKnownValueClass()
bool System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteKnownValueClass (NameInfo memberNameInfo, NameInfo typeNameInfo, object data) inline private
Definition at line 873 of file ObjectWriter.cs.
        {
            if (typeNameInfo.NItype == Converter.typeofString)
            {
                this.WriteString(memberNameInfo, typeNameInfo, data);
            }
            else
            {
                if (typeNameInfo.NIprimitiveTypeEnum == InternalPrimitiveTypeE.Invalid)
                {
                    return false;
                }
                if (typeNameInfo.NIisArray)
                {
                    this.serWriter.WriteItem(memberNameInfo, typeNameInfo, data);
                }
                else
                {
                    this.serWriter.WriteMember(memberNameInfo, typeNameInfo, data);
                }
            }
            return true;
        }
References System.Runtime.Serialization.Formatters.Binary.NameInfo.NIisArray, System.Runtime.Serialization.Formatters.Binary.NameInfo.NIprimitiveTypeEnum, System.Runtime.Serialization.Formatters.Binary.NameInfo.NItype, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.serWriter, System.Runtime.Serialization.Formatters.Binary.Converter.typeofString, System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteItem(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteMember(), and System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteString().
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteArrayMember(), and System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteMembers().