Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.ObjectWriter.GetNext
GetNext()
object System.Runtime.Serialization.Formatters.Binary.ObjectWriter.GetNext (out long objID) inline private
Definition at line 793 of file ObjectWriter.cs.
        {
            if (this.m_objectQueue.Count == 0)
            {
                objID = 0L;
                return null;
            }
            object obj = this.m_objectQueue.Dequeue();
            object obj2;
            if (obj is WriteObjectInfo)
            {
                obj2 = ((WriteObjectInfo)obj).obj;
            }
            else
            {
                obj2 = obj;
            }
            bool flag;
            objID = this.m_idGenerator.HasId(obj2, out flag);
            if (flag)
            {
                throw new SerializationException(Environment.GetResourceString("Object {0} has never been assigned an objectID.", new object[] { obj2 }));
            }
            return obj;
        }
References System.Collections.Queue.Count, System.Collections.Queue.Dequeue(), System.Environment.GetResourceString(), System.Runtime.Serialization.ObjectIDGenerator.HasId(), System.L, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.m_idGenerator, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.m_objectQueue, and System.obj.
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize().