Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.ObjectWriter.InternalGetId
InternalGetId()
long System.Runtime.Serialization.Formatters.Binary.ObjectWriter.InternalGetId (object obj, bool assignUniqueIdToValueType, Type type, out bool isNew) inline private
Definition at line 820 of file ObjectWriter.cs.
        {
            if (obj == this.previousObj)
            {
                isNew = false;
                return this.previousId;
            }
            this.m_idGenerator.m_currentCount = this.m_currentId;
            if (type != null && type.IsValueType && !assignUniqueIdToValueType)
            {
                isNew = false;
                int num = -1;
                int currentId = this.m_currentId;
                this.m_currentId = currentId + 1;
                return (long)(num * currentId);
            }
            this.m_currentId++;
            long id = this.m_idGenerator.GetId(obj, out isNew);
            this.previousObj = obj;
            this.previousId = id;
            return id;
        }
References System.Runtime.Serialization.ObjectIDGenerator.GetId(), System.Type.IsValueType, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.m_currentId, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.m_idGenerator, System.obj, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.previousId, and System.Runtime.Serialization.Formatters.Binary.ObjectWriter.previousObj.
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectWriter.GetAssemblyId(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Schedule(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(), and System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteString().