Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.ObjectWriter.GetAssemblyId
GetAssemblyId()
long System.Runtime.Serialization.Formatters.Binary.ObjectWriter.GetAssemblyId (WriteObjectInfo objectInfo) inline private
Definition at line 1026 of file ObjectWriter.cs.
        {
            if (this.assemblyToIdTable == null)
            {
                this.assemblyToIdTable = new Hashtable(5);
            }
            bool flag = false;
            string assemblyString = objectInfo.GetAssemblyString();
            string text = assemblyString;
            long num;
            if (assemblyString.Length == 0)
            {
                num = 0L;
            }
            else if (assemblyString.Equals(Converter.urtAssemblyString))
            {
                num = 0L;
            }
            else
            {
                if (this.assemblyToIdTable.ContainsKey(assemblyString))
                {
                    num = (long)this.assemblyToIdTable[assemblyString];
                    flag = false;
                }
                else
                {
                    num = this.InternalGetId("___AssemblyString___" + assemblyString, false, null, out flag);
                    this.assemblyToIdTable[assemblyString] = num;
                }
                this.serWriter.WriteAssembly(objectInfo.objectType, text, (int)num, flag);
            }
            return num;
        }
References System.Runtime.Serialization.Formatters.Binary.ObjectWriter.assemblyToIdTable, System.Collections.Hashtable.ContainsKey(), System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.GetAssemblyString(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.InternalGetId(), System.L, long, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.objectType, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.serWriter, System.text, System.Runtime.Serialization.Formatters.Binary.Converter.urtAssemblyString, and System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteAssembly().
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteArray(), and System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteArrayMember().