Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.ObjectWriter.CheckForNull
CheckForNull()
bool System.Runtime.Serialization.Formatters.Binary.ObjectWriter.CheckForNull (WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo, object data) inline private
Definition at line 922 of file ObjectWriter.cs.
        {
            bool flag = false;
            if (data == null)
            {
                flag = true;
            }
            if (flag && (this.formatterEnums.FEserializerTypeEnum == InternalSerializerTypeE.Binary || memberNameInfo.NIisArrayItem || memberNameInfo.NItransmitTypeOnObject || memberNameInfo.NItransmitTypeOnMember || objectInfo.isSi || this.CheckTypeFormat(this.formatterEnums.FEtypeFormat, FormatterTypeStyle.TypesAlways)))
            {
                if (typeNameInfo.NIisArrayItem)
                {
                    if (typeNameInfo.NIarrayEnum == InternalArrayTypeE.Single)
                    {
                        this.serWriter.WriteDelayedNullItem();
                    }
                    else
                    {
                        this.serWriter.WriteNullItem(memberNameInfo, typeNameInfo);
                    }
                }
                else
                {
                    this.serWriter.WriteNullMember(memberNameInfo, typeNameInfo);
                }
            }
            return flag;
        }
References System.Runtime.Serialization.Formatters.Binary.InternalFE.FEserializerTypeEnum, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.formatterEnums, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.isSi, System.Runtime.Serialization.Formatters.Binary.NameInfo.NIarrayEnum, System.Runtime.Serialization.Formatters.Binary.NameInfo.NIisArrayItem, System.Runtime.Serialization.Formatters.Binary.NameInfo.NItransmitTypeOnMember, System.Runtime.Serialization.Formatters.Binary.NameInfo.NItransmitTypeOnObject, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.serWriter, System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteDelayedNullItem(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteNullItem(), and System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteNullMember().
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteArrayMember(), and System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteMembers().