Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteArray
WriteArray()
void System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteArray (WriteObjectInfo objectInfo, NameInfo memberNameInfo, WriteObjectInfo memberObjectInfo) inline private
Definition at line 494 of file ObjectWriter.cs.
        {
            bool flag = false;
            if (memberNameInfo == null)
            {
                memberNameInfo = this.TypeToNameInfo(objectInfo);
                flag = true;
            }
            memberNameInfo.NIisArray = true;
            long objectId = objectInfo.objectId;
            memberNameInfo.NIobjectId = objectInfo.objectId;
            Array array = (Array)objectInfo.obj;
            Type elementType = objectInfo.objectType.GetElementType();
            WriteObjectInfo writeObjectInfo = null;
            if (!elementType.IsPrimitive)
            {
                writeObjectInfo = WriteObjectInfo.Serialize(elementType, this.m_surrogates, this.m_context, this.serObjectInfoInit, this.m_formatterConverter, this.m_binder);
                writeObjectInfo.assemId = this.GetAssemblyId(writeObjectInfo);
            }
            NameInfo nameInfo;
            if (writeObjectInfo == null)
            {
                nameInfo = this.TypeToNameInfo(elementType);
            }
            else
            {
                nameInfo = this.TypeToNameInfo(writeObjectInfo);
            }
            nameInfo.NIisArray = nameInfo.NItype.IsArray;
            NameInfo nameInfo2 = memberNameInfo;
            nameInfo2.NIobjectId = objectId;
            nameInfo2.NIisArray = true;
            nameInfo.NIobjectId = objectId;
            nameInfo.NItransmitTypeOnMember = memberNameInfo.NItransmitTypeOnMember;
            nameInfo.NItransmitTypeOnObject = memberNameInfo.NItransmitTypeOnObject;
            nameInfo.NIisParentTypeOnObject = memberNameInfo.NIisParentTypeOnObject;
            int rank = array.Rank;
            int[] array2 = new int[rank];
            int[] array3 = new int[rank];
            int[] array4 = new int[rank];
            for (int i = 0; i < rank; i++)
            {
                array2[i] = array.GetLength(i);
                array3[i] = array.GetLowerBound(i);
                array4[i] = array.GetUpperBound(i);
            }
            InternalArrayTypeE internalArrayTypeE;
            if (nameInfo.NIisArray)
            {
                if (rank == 1)
                {
                    internalArrayTypeE = InternalArrayTypeE.Jagged;
                }
                else
                {
                    internalArrayTypeE = InternalArrayTypeE.Rectangular;
                }
            }
            else if (rank == 1)
            {
                internalArrayTypeE = InternalArrayTypeE.Single;
            }
            else
            {
                internalArrayTypeE = InternalArrayTypeE.Rectangular;
            }
            nameInfo.NIarrayEnum = internalArrayTypeE;
            if (elementType == Converter.typeofByte && rank == 1 && array3[0] == 0)
            {
                this.serWriter.WriteObjectByteArray(memberNameInfo, nameInfo2, writeObjectInfo, nameInfo, array2[0], array3[0], (byte[])array);
                return;
            }
            if (elementType == Converter.typeofObject || Nullable.GetUnderlyingType(elementType) != null)
            {
                memberNameInfo.NItransmitTypeOnMember = true;
                nameInfo.NItransmitTypeOnMember = true;
            }
            if (this.CheckTypeFormat(this.formatterEnums.FEtypeFormat, FormatterTypeStyle.TypesAlways))
            {
                memberNameInfo.NItransmitTypeOnObject = true;
                nameInfo.NItransmitTypeOnObject = true;
            }
            if (internalArrayTypeE == InternalArrayTypeE.Single)
            {
                this.serWriter.WriteSingleArray(memberNameInfo, nameInfo2, writeObjectInfo, nameInfo, array2[0], array3[0], array);
                if (!Converter.IsWriteAsByteArray(nameInfo.NIprimitiveTypeEnum) || array3[0] != 0)
                {
                    object[] array5 = null;
                    if (!elementType.IsValueType)
                    {
                        array5 = (object[])array;
                    }
                    int num = array4[0] + 1;
                    for (int j = array3[0]; j < num; j++)
                    {
                        if (array5 == null)
{
                            this.WriteArrayMember(objectInfo, nameInfo, array.GetValue(j));
                        }
                        else
{
                            this.WriteArrayMember(objectInfo, nameInfo, array5[j]);
                        }
                    }
                    this.serWriter.WriteItemEnd();
                }
            }
            else if (internalArrayTypeE == InternalArrayTypeE.Jagged)
            {
                nameInfo2.NIobjectId = objectId;
                this.serWriter.WriteJaggedArray(memberNameInfo, nameInfo2, writeObjectInfo, nameInfo, array2[0], array3[0]);
                object[] array6 = (object[])array;
                for (int k = array3[0]; k < array4[0] + 1; k++)
                {
                    this.WriteArrayMember(objectInfo, nameInfo, array6[k]);
                }
                this.serWriter.WriteItemEnd();
            }
            else
            {
                nameInfo2.NIobjectId = objectId;
                this.serWriter.WriteRectangleArray(memberNameInfo, nameInfo2, writeObjectInfo, nameInfo, rank, array2, array3);
                bool flag2 = false;
                for (int l = 0; l < rank; l++)
                {
                    if (array2[l] == 0)
                    {
                        flag2 = true;
                        break;
                    }
                }
                if (!flag2)
                {
                    this.WriteRectangle(objectInfo, rank, array2, array, nameInfo, array3);
                }
                this.serWriter.WriteItemEnd();
            }
            this.serWriter.WriteObjectEnd(memberNameInfo, nameInfo2);
            this.PutNameInfo(nameInfo);
            if (flag)
            {
                this.PutNameInfo(memberNameInfo);
            }
        }
References System.array, System.Runtime.Serialization.Formatters.Binary.Array, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.CheckTypeFormat(), System.Runtime.Serialization.Formatters.Binary.InternalFE.FEtypeFormat, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.formatterEnums, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.GetAssemblyId(), System.Type.GetElementType(), System.Nullable< T >.GetUnderlyingType(), System.Type.IsArray, System.Type.IsPrimitive, System.Type.IsValueType, System.Runtime.Serialization.Formatters.Binary.Converter.IsWriteAsByteArray(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.m_binder, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.m_context, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.m_formatterConverter, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.m_surrogates, System.Runtime.Serialization.Formatters.Binary.NameInfo.NIisArray, System.Runtime.Serialization.Formatters.Binary.NameInfo.NIisParentTypeOnObject, System.Runtime.Serialization.Formatters.Binary.NameInfo.NIprimitiveTypeEnum, System.Runtime.Serialization.Formatters.Binary.NameInfo.NItransmitTypeOnMember, System.Runtime.Serialization.Formatters.Binary.NameInfo.NItransmitTypeOnObject, System.Runtime.Serialization.Formatters.Binary.NameInfo.NItype, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.obj, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.objectId, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.objectType, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.PutNameInfo(), System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.Serialize(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.serObjectInfoInit, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.serWriter, System.Runtime.Serialization.Formatters.Binary.Converter.typeofByte, System.Runtime.Serialization.Formatters.Binary.Converter.typeofObject, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.TypeToNameInfo(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteArrayMember(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteItemEnd(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteJaggedArray(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteObjectByteArray(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteObjectEnd(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteRectangle(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteRectangleArray(), and System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteSingleArray().
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(), and System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteMembers().