Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteMethodReturn
WriteMethodReturn()
object[] System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteMethodReturn (IMethodReturnMessage mrm) inline private
Definition at line 172 of file ObjectWriter.cs.
        {
            object returnValue = mrm.ReturnValue;
            object[] args = mrm.Args;
            Exception exception = mrm.Exception;
            object[] array = null;
            ReturnMessage returnMessage = mrm as ReturnMessage;
            if (returnMessage == null || returnMessage.HasProperties())
            {
                array = ObjectWriter.StoreUserPropertiesForMethodMessage(mrm);
            }
            LogicalCallContext logicalCallContext = mrm.LogicalCallContext;
            object obj;
            if (logicalCallContext == null)
            {
                obj = null;
            }
            else if (logicalCallContext.HasInfo)
            {
                obj = logicalCallContext;
            }
            else
            {
                obj = logicalCallContext.RemotingData.LogicalCallID;
            }
            return this.serWriter.WriteReturnArray(returnValue, args, exception, obj, array);
        }
References System.Runtime.Remoting.Messaging.IMethodMessage.Args, System.array, System.exception, System.Runtime.Remoting.Messaging.IMethodReturnMessage.Exception, System.Runtime.Remoting.Messaging.LogicalCallContext.HasInfo, System.Runtime.Remoting.Messaging.ReturnMessage.HasProperties(), System.Runtime.Remoting.Messaging.IMethodMessage.LogicalCallContext, System.Runtime.Remoting.Messaging.CallContextRemotingData.LogicalCallID, System.obj, System.Runtime.Remoting.Messaging.LogicalCallContext.RemotingData, System.Runtime.Remoting.Messaging.IMethodReturnMessage.ReturnValue, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.serWriter, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.StoreUserPropertiesForMethodMessage(), and System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteReturnArray().
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize().