Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteString
WriteString()
void System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteString (NameInfo memberNameInfo, NameInfo typeNameInfo, object stringObject) inline private
Definition at line 904 of file ObjectWriter.cs.
        {
            bool flag = true;
            long num = -1L;
            if (!this.CheckTypeFormat(this.formatterEnums.FEtypeFormat, FormatterTypeStyle.XsdString))
            {
                num = this.InternalGetId(stringObject, false, null, out flag);
            }
            typeNameInfo.NIobjectId = num;
            if (flag || num < 0L)
            {
                this.serWriter.WriteMemberString(memberNameInfo, typeNameInfo, (string)stringObject);
                return;
            }
            this.WriteObjectRef(memberNameInfo, num);
        }
References System.Runtime.Serialization.Formatters.Binary.ObjectWriter.CheckTypeFormat(), System.Runtime.Serialization.Formatters.Binary.InternalFE.FEtypeFormat, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.formatterEnums, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.InternalGetId(), System.L, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.serWriter, System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteMemberString(), and System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteObjectRef().
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteKnownValueClass().