Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write
Write() [2/2]
void System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write (WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo, string[] memberNames, Type[] memberTypes, object[] memberData, WriteObjectInfo[] memberObjectInfos) inline private
Definition at line 329 of file ObjectWriter.cs.
        {
            int num = memberNames.Length;
            NameInfo nameInfo = null;
            if (memberNameInfo != null)
            {
                memberNameInfo.NIobjectId = objectInfo.objectId;
                this.serWriter.WriteObject(memberNameInfo, typeNameInfo, num, memberNames, memberTypes, memberObjectInfos);
            }
            else if (objectInfo.objectId == this.topId && this.topName != null)
            {
                nameInfo = this.MemberToNameInfo(this.topName);
                nameInfo.NIobjectId = objectInfo.objectId;
                this.serWriter.WriteObject(nameInfo, typeNameInfo, num, memberNames, memberTypes, memberObjectInfos);
            }
            else if (objectInfo.objectType != Converter.typeofString)
            {
                typeNameInfo.NIobjectId = objectInfo.objectId;
                this.serWriter.WriteObject(typeNameInfo, null, num, memberNames, memberTypes, memberObjectInfos);
            }
            if (memberNameInfo.NIisParentTypeOnObject)
            {
                memberNameInfo.NItransmitTypeOnObject = true;
                memberNameInfo.NIisParentTypeOnObject = false;
            }
            else
            {
                memberNameInfo.NItransmitTypeOnObject = false;
            }
            for (int i = 0; i < num; i++)
            {
                this.WriteMemberSetup(objectInfo, memberNameInfo, typeNameInfo, memberNames[i], memberTypes[i], memberData[i], memberObjectInfos[i]);
            }
            if (memberNameInfo != null)
            {
                memberNameInfo.NIobjectId = objectInfo.objectId;
                this.serWriter.WriteObjectEnd(memberNameInfo, typeNameInfo);
                return;
            }
            if (objectInfo.objectId == this.topId && this.topName != null)
            {
                this.serWriter.WriteObjectEnd(nameInfo, typeNameInfo);
                this.PutNameInfo(nameInfo);
                return;
            }
            if (objectInfo.objectType != Converter.typeofString)
            {
                this.serWriter.WriteObjectEnd(typeNameInfo, typeNameInfo);
            }
        }
References System.Runtime.Serialization.Formatters.Binary.ObjectWriter.MemberToNameInfo(), System.Runtime.Serialization.Formatters.Binary.NameInfo.NIisParentTypeOnObject, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.objectId, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.objectType, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.PutNameInfo(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.serWriter, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.topName, System.Runtime.Serialization.Formatters.Binary.Converter.typeofString, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteMemberSetup(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteObject(), and System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteObjectEnd().