Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.ObjectWriter.StoreUserPropertiesForMethodMessage
StoreUserPropertiesForMethodMessage()
static object[] System.Runtime.Serialization.Formatters.Binary.ObjectWriter.StoreUserPropertiesForMethodMessage (IMethodMessage msg) inline static private
Definition at line 202 of file ObjectWriter.cs.
        {
            ArrayList arrayList = null;
            IDictionary properties = msg.Properties;
            if (properties == null)
            {
                return null;
            }
            MessageDictionary messageDictionary = properties as MessageDictionary;
            if (messageDictionary != null)
            {
                if (messageDictionary.HasUserData())
                {
                    int num = 0;
                    foreach (object obj in messageDictionary.InternalDictionary)
                    {
                        DictionaryEntry dictionaryEntry = (DictionaryEntry)obj;
                        if (arrayList == null)
{
                            arrayList = new ArrayList();
                        }
                        arrayList.Add(dictionaryEntry);
                        num++;
                    }
                    return arrayList.ToArray();
                }
                return null;
            }
            else
            {
                int num2 = 0;
                foreach (object obj2 in properties)
                {
                    DictionaryEntry dictionaryEntry2 = (DictionaryEntry)obj2;
                    if (arrayList == null)
                    {
                        arrayList = new ArrayList();
                    }
                    arrayList.Add(dictionaryEntry2);
                    num2++;
                }
                if (arrayList != null)
                {
                    return arrayList.ToArray();
                }
                return null;
            }
        }
References System.Collections.ArrayList.Add(), System.Runtime.Remoting.Messaging.MessageDictionary.HasUserData(), System.Runtime.Remoting.Messaging.MessageDictionary.InternalDictionary, System.obj, System.Runtime.Remoting.Messaging.IMessage.Properties, and System.Collections.ArrayList.ToArray().
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteMethodCall(), and System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteMethodReturn().