Terraria Decompiled: Terraria.GameContent.UI.Elements.UISlicedImage.SetSliceDepths
SetSliceDepths() [2/2]
void Terraria.GameContent.UI.Elements.UISlicedImage.SetSliceDepths (int top, int bottom, int left, int right) inline
Definition at line 49 of file UISlicedImage.cs.
        {
            this._leftSliceDepth = left;
            this._rightSliceDepth = right;
            this._topSliceDepth = top;
            this._bottomSliceDepth = bottom;
        }
Referenced by Terraria.GameContent.UI.States.UIWorldCreationAdvanced.AddDescriptionPanel(), Terraria.GameContent.UI.States.UIWorkshopHub.AddDescriptionPanel(), Terraria.GameContent.UI.States.UIWorldCreation.AddDescriptionPanel(), Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.AddDescriptionPanel(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.AddDescriptionPanel(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.AddUIList(), Terraria.GameContent.UI.States.UIReportsPage.BuildPage(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.CreateInsturctionsPanel(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.CreateStylizedCategoryPanel(), and Terraria.GameContent.UI.States.UICharacterCreation.MakeInfoMenu().