Terraria Decompiled: Terraria.GameContent.UI.States.UIBestiaryTest.AddSortAndFilterButtons
AddSortAndFilterButtons()
void Terraria.GameContent.UI.States.UIBestiaryTest.AddSortAndFilterButtons (UIElement innerTopContainer, UIBestiaryEntryInfoPage infoSpace) inline private
Definition at line 240 of file UIBestiaryTest.cs.
        {
            int num = 17;
            UIImageButton uiimageButton = new UIImageButton(Main.Assets.Request<Texture2D>("Images/UI/Bestiary/Button_Filtering", 1), null)
            {
                Left = new StyleDimension(-infoSpace.Width.Pixels - (float)num, 0f),
                HAlign = 1f
            };
            uiimageButton.SetHoverImage(Main.Assets.Request<Texture2D>("Images/UI/Bestiary/Button_Wide_Border", 1), null);
            uiimageButton.SetVisibility(1f, 1f);
            uiimageButton.SetSnapPoint("FilterButton", 0, null, null);
            uiimageButton.OnLeftClick += this.OpenOrCloseFilteringGrid;
            innerTopContainer.Append(uiimageButton);
            UIText uitext = new UIText("", 0.8f, false)
            {
                Left = new StyleDimension(34f, 0f),
                Top = new StyleDimension(2f, 0f),
                VAlign = 0.5f,
                TextOriginX = 0f,
                TextOriginY = 0f
            };
            uiimageButton.Append(uitext);
            this._filteringText = uitext;
            UIImageButton uiimageButton2 = new UIImageButton(Main.Assets.Request<Texture2D>("Images/UI/Bestiary/Button_Sorting", 1), null)
            {
                Left = new StyleDimension(-infoSpace.Width.Pixels - uiimageButton.Width.Pixels - 3f - (float)num, 0f),
                HAlign = 1f
            };
            uiimageButton2.SetHoverImage(Main.Assets.Request<Texture2D>("Images/UI/Bestiary/Button_Wide_Border", 1), null);
            uiimageButton2.SetVisibility(1f, 1f);
            uiimageButton2.SetSnapPoint("SortButton", 0, null, null);
            uiimageButton2.OnLeftClick += this.OpenOrCloseSortingOptions;
            innerTopContainer.Append(uiimageButton2);
            UIText uitext2 = new UIText("", 0.8f, false)
            {
                Left = new StyleDimension(34f, 0f),
                Top = new StyleDimension(2f, 0f),
                VAlign = 0.5f,
                TextOriginX = 0f,
                TextOriginY = 0f
            };
            uiimageButton2.Append(uitext2);
            this._sortingText = uitext2;
        }
References Terraria.UI.UIElement.Append(), Terraria.Main.Assets, Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Left, Terraria.GameContent.UI.States.UIBestiaryTest.OpenOrCloseFilteringGrid(), Terraria.GameContent.UI.States.UIBestiaryTest.OpenOrCloseSortingOptions(), Terraria.UI.StyleDimension.Pixels, Terraria.GameContent.UI.Elements.UIImageButton.SetHoverImage(), Terraria.UI.UIElement.SetSnapPoint(), Terraria.GameContent.UI.Elements.UIImageButton.SetVisibility(), Terraria.UI.UIElement.Top, Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.UIBestiaryTest.BuildPage().