Terraria Decompiled: Terraria.GameContent.UI.States.UIBestiaryTest.PairUpDown
PairUpDown()
void Terraria.GameContent.UI.States.UIBestiaryTest.PairUpDown (UILinkPoint upSide, UILinkPoint downSide) inline private
Definition at line 885 of file UIBestiaryTest.cs.
        {
            upSide.Down = downSide.ID;
            downSide.Up = upSide.ID;
        }
References Terraria.UI.Gamepad.UILinkPoint.ID.
Referenced by Terraria.GameContent.UI.States.UIBestiaryTest.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIBestiaryTest.SetupPointsForEntryGrid(), Terraria.GameContent.UI.States.UIBestiaryTest.SetupPointsForFilterGrid(), and Terraria.GameContent.UI.States.UIBestiaryTest.SetupPointsForSortingGrid().