Terraria Decompiled: Terraria.GameContent.UI.States.UIBestiaryTest.SetupPointsForSortingGrid
SetupPointsForSortingGrid()
void Terraria.GameContent.UI.States.UIBestiaryTest.SetupPointsForSortingGrid (ref int currentID, List< SnapPoint > pts, out int gridWidth, out int gridHeight, out UILinkPoint gridPoints[,]) inline private
Definition at line 826 of file UIBestiaryTest.cs.
        {
            List<SnapPoint> orderedPointsByCategoryName = UIBestiaryTest.GetOrderedPointsByCategoryName(pts, "SortSteps");
            int num;
            this._sortingGrid.GetEntriesToShow(out gridWidth, out gridHeight, out num);
            gridPoints = new UILinkPoint[gridWidth, gridHeight];
            for (int i = 0; i < orderedPointsByCategoryName.Count; i++)
            {
                int num2 = i % gridWidth;
                int num3 = i / gridWidth;
                UILinkPoint[,] array = gridPoints;
                int num4 = num2;
                int num5 = num3;
                int num6 = currentID;
                currentID = num6 + 1;
                array[num4, num5] = this.MakeLinkPointFromSnapPoint(num6, orderedPointsByCategoryName[i]);
            }
            for (int j = 0; j < gridWidth; j++)
            {
                for (int k = 0; k < gridHeight; k++)
                {
                    UILinkPoint uilinkPoint = gridPoints[j, k];
                    if (j < gridWidth - 1)
                    {
                        UILinkPoint uilinkPoint2 = gridPoints[j + 1, k];
                        if (uilinkPoint != null && uilinkPoint2 != null)
{
                            this.PairLeftRight(uilinkPoint, uilinkPoint2);
                        }
                    }
                    if (k < gridHeight - 1)
                    {
                        UILinkPoint uilinkPoint3 = gridPoints[j, k + 1];
                        if (uilinkPoint != null && uilinkPoint3 != null)
{
                            this.PairUpDown(uilinkPoint, uilinkPoint3);
                        }
                    }
                }
            }
        }
References Terraria.GameContent.UI.States.UIBestiaryTest._sortingGrid, System.array, System.Collections.Generic.List< T >.Count, Terraria.GameContent.UI.Elements.UIBestiarySortingOptionsGrid.GetEntriesToShow(), Terraria.GameContent.UI.States.UIBestiaryTest.GetOrderedPointsByCategoryName(), Terraria.GameContent.UI.States.UIBestiaryTest.MakeLinkPointFromSnapPoint(), Terraria.GameContent.UI.States.UIBestiaryTest.PairLeftRight(), and Terraria.GameContent.UI.States.UIBestiaryTest.PairUpDown().
Referenced by Terraria.GameContent.UI.States.UIBestiaryTest.SetupGamepadPoints().