Terraria Decompiled: Terraria.GameContent.UI.States.UIBestiaryTest.SetupGamepadPoints
SetupGamepadPoints()
void Terraria.GameContent.UI.States.UIBestiaryTest.SetupGamepadPoints (SpriteBatch spriteBatch) inline private
Definition at line 532 of file UIBestiaryTest.cs.
        {
            UILinkPointNavigator.Shortcuts.BackButtonCommand = 1;
            int num = 3000;
            int num2 = num;
            List<SnapPoint> snapPoints = this.GetSnapPoints();
            SnapPoint snapPoint = null;
            SnapPoint snapPoint2 = null;
            SnapPoint snapPoint3 = null;
            SnapPoint snapPoint4 = null;
            SnapPoint snapPoint5 = null;
            SnapPoint snapPoint6 = null;
            for (int i = 0; i < snapPoints.Count; i++)
            {
                SnapPoint snapPoint7 = snapPoints[i];
                string name = snapPoint7.Name;
                if (!(name == "BackPage"))
                {
                    if (!(name == "NextPage"))
                    {
                        if (!(name == "ExitButton"))
{
                            if (!(name == "FilterButton"))
{
                                if (!(name == "SortButton"))
{
                                    if (name == "SearchButton")
{
                                        snapPoint5 = snapPoint7;
                                    }
                                }
                                else
{
                                    snapPoint3 = snapPoint7;
                                }
                            }
                            else
{
                                snapPoint4 = snapPoint7;
                            }
                        }
                        else
{
                            snapPoint6 = snapPoint7;
                        }
                    }
                    else
                    {
                        snapPoint2 = snapPoint7;
                    }
                }
                else
                {
                    snapPoint = snapPoint7;
                }
            }
            UILinkPoint uilinkPoint = this.MakeLinkPointFromSnapPoint(num2++, snapPoint);
            UILinkPoint uilinkPoint2 = this.MakeLinkPointFromSnapPoint(num2++, snapPoint2);
            UILinkPoint uilinkPoint3 = this.MakeLinkPointFromSnapPoint(num2++, snapPoint6);
            UILinkPoint uilinkPoint4 = this.MakeLinkPointFromSnapPoint(num2++, snapPoint4);
            UILinkPoint uilinkPoint5 = this.MakeLinkPointFromSnapPoint(num2++, snapPoint3);
            this.searchButtonLink = this.MakeLinkPointFromSnapPoint(num2++, snapPoint5);
            this.PairLeftRight(uilinkPoint, uilinkPoint2);
            this.PairLeftRight(uilinkPoint2, uilinkPoint5);
            this.PairLeftRight(uilinkPoint5, uilinkPoint4);
            this.PairLeftRight(uilinkPoint4, this.searchButtonLink);
            uilinkPoint3.Up = uilinkPoint2.ID;
            UILinkPoint[,] array = new UILinkPoint[1, 1];
            if (this._filteringGrid.Parent != null)
            {
                int num3;
                int num4;
                this.SetupPointsForFilterGrid(ref num2, snapPoints, out num3, out num4, out array);
                this.PairUpDown(uilinkPoint2, uilinkPoint3);
                this.PairUpDown(uilinkPoint, uilinkPoint3);
                for (int j = num3 - 1; j >= 0; j--)
                {
                    UILinkPoint uilinkPoint6 = array[j, num4 - 1];
                    if (uilinkPoint6 != null)
                    {
                        this.PairUpDown(uilinkPoint6, uilinkPoint3);
                    }
                    UILinkPoint uilinkPoint7 = array[j, num4 - 2];
                    if (uilinkPoint7 != null && uilinkPoint6 == null)
                    {
                        this.PairUpDown(uilinkPoint7, uilinkPoint3);
                    }
                    UILinkPoint uilinkPoint8 = array[j, 0];
                    if (uilinkPoint8 != null)
                    {
                        if (j < num3 - 3)
{
                            this.PairUpDown(uilinkPoint5, uilinkPoint8);
                        }
                        else
{
                            this.PairUpDown(uilinkPoint4, uilinkPoint8);
                        }
                    }
                }
            }
            else if (this._sortingGrid.Parent != null)
            {
                int num3;
                int num4;
                this.SetupPointsForSortingGrid(ref num2, snapPoints, out num3, out num4, out array);
                this.PairUpDown(uilinkPoint2, uilinkPoint3);
                this.PairUpDown(uilinkPoint, uilinkPoint3);
                for (int k = num3 - 1; k >= 0; k--)
                {
                    UILinkPoint uilinkPoint9 = array[k, num4 - 1];
                    if (uilinkPoint9 != null)
                    {
                        this.PairUpDown(uilinkPoint9, uilinkPoint3);
                    }
                    UILinkPoint uilinkPoint10 = array[k, 0];
                    if (uilinkPoint10 != null)
                    {
                        this.PairUpDown(uilinkPoint4, uilinkPoint10);
                        this.PairUpDown(uilinkPoint5, uilinkPoint10);
                    }
                }
            }
            else if (this._entryGrid.Parent != null)
            {
                int num3;
                int num4;
                this.SetupPointsForEntryGrid(ref num2, snapPoints, out num3, out num4, out array);
                for (int l = 0; l < num3; l++)
                {
                    if (num4 - 1 >= 0)
                    {
                        UILinkPoint uilinkPoint11 = array[l, num4 - 1];
                        if (uilinkPoint11 != null)
{
                            this.PairUpDown(uilinkPoint11, uilinkPoint3);
                        }
                        if (num4 - 2 >= 0)
{
                            UILinkPoint uilinkPoint12 = array[l, num4 - 2];
                            if (uilinkPoint12 != null && uilinkPoint11 == null)
{
                                this.PairUpDown(uilinkPoint12, uilinkPoint3);
                            }
                        }
                    }
                    UILinkPoint uilinkPoint13 = array[l, 0];
                    if (uilinkPoint13 != null)
                    {
                        if (l < num3 / 2)
{
                            this.PairUpDown(uilinkPoint2, uilinkPoint13);
                        }
                        else if (l == num3 - 1)
{
                            this.PairUpDown(uilinkPoint4, uilinkPoint13);
                        }
                        else
{
                            this.PairUpDown(uilinkPoint5, uilinkPoint13);
                        }
                    }
                }
                UILinkPoint uilinkPoint14 = array[0, 0];
                if (uilinkPoint14 != null)
                {
                    this.PairUpDown(uilinkPoint2, uilinkPoint14);
                    this.PairUpDown(uilinkPoint, uilinkPoint14);
                }
                else
                {
                    this.PairUpDown(uilinkPoint2, uilinkPoint3);
                    this.PairUpDown(uilinkPoint, uilinkPoint3);
                    this.PairUpDown(uilinkPoint4, uilinkPoint3);
                    this.PairUpDown(uilinkPoint5, uilinkPoint3);
                }
            }
            List<UILinkPoint> list = new List<UILinkPoint>();
            for (int m = num; m < num2; m++)
            {
                list.Add(UILinkPointNavigator.Points[m]);
            }
            if (PlayerInput.UsingGamepadUI && UILinkPointNavigator.CurrentPoint >= num2)
            {
                this.MoveToVisuallyClosestPoint(list);
            }
        }
References Terraria.GameContent.UI.States.UIBestiaryTest._entryGrid, Terraria.GameContent.UI.States.UIBestiaryTest._filteringGrid, Terraria.GameContent.UI.States.UIBestiaryTest._sortingGrid, System.array, System.Collections.Generic.List< T >.Count, Terraria.UI.Gamepad.UILinkPointNavigator.CurrentPoint, Terraria.UI.UIElement.GetSnapPoints(), Terraria.UI.Gamepad.UILinkPoint.ID, System.list, Terraria.GameContent.UI.States.UIBestiaryTest.MakeLinkPointFromSnapPoint(), Terraria.GameContent.UI.States.UIBestiaryTest.MoveToVisuallyClosestPoint(), System.name, Terraria.UI.SnapPoint.Name, Terraria.GameContent.UI.States.UIBestiaryTest.PairLeftRight(), Terraria.GameContent.UI.States.UIBestiaryTest.PairUpDown(), Terraria.UI.UIElement.Parent, Terraria.UI.Gamepad.UILinkPointNavigator.Points, Terraria.GameContent.UI.States.UIBestiaryTest.searchButtonLink, Terraria.GameContent.UI.States.UIBestiaryTest.SetupPointsForEntryGrid(), Terraria.GameContent.UI.States.UIBestiaryTest.SetupPointsForFilterGrid(), Terraria.GameContent.UI.States.UIBestiaryTest.SetupPointsForSortingGrid(), and Terraria.GameInput.PlayerInput.UsingGamepadUI.
Referenced by Terraria.GameContent.UI.States.UIBestiaryTest.Draw().