Terraria Decompiled: Terraria.GameContent.UI.States.UIBestiaryTest.BuildPage
BuildPage()
void Terraria.GameContent.UI.States.UIBestiaryTest.BuildPage () inline private
Definition at line 40 of file UIBestiaryTest.cs.
        {
            base.RemoveAllChildren();
            int num = true.ToInt() * 100;
            UIElement uielement = new UIElement();
            uielement.Width.Set(0f, 0.875f);
            uielement.MaxWidth.Set(800f + (float)num, 0f);
            uielement.MinWidth.Set(600f + (float)num, 0f);
            uielement.Top.Set(180f, 0f);
            uielement.Height.Set(-220f, 1f);
            uielement.HAlign = 0.5f;
            base.Append(uielement);
            this.MakeExitButton(uielement);
            UIPanel uipanel = new UIPanel();
            uipanel.Width.Set(0f, 1f);
            uipanel.Height.Set(-90f, 1f);
            uipanel.BackgroundColor = new Color(33, 43, 79) * 0.8f;
            uielement.Append(uipanel);
            uipanel.PaddingTop -= 4f;
            uipanel.PaddingBottom -= 4f;
            int num2 = 24;
            UIElement uielement2 = new UIElement
            {
                Width = new StyleDimension(0f, 1f),
                Height = new StyleDimension((float)num2, 0f),
                VAlign = 0f
            };
            uielement2.SetPadding(0f);
            uipanel.Append(uielement2);
            UIBestiaryEntryInfoPage uibestiaryEntryInfoPage = new UIBestiaryEntryInfoPage
            {
                Height = new StyleDimension(12f, 1f),
                HAlign = 1f
            };
            this.AddSortAndFilterButtons(uielement2, uibestiaryEntryInfoPage);
            UIWrappedSearchBar uiwrappedSearchBar = new UIWrappedSearchBar(new Action(this.GoBackFromVirtualKeyboard), null, UIWrappedSearchBar.ColorTheme.Blue)
            {
                Width = new StyleDimension(uibestiaryEntryInfoPage.Width.Pixels, 0f),
                HAlign = 1f
            };
            uiwrappedSearchBar.CustomOpenVirtualKeyboard = new Action<UIState>(IngameFancyUI.OpenUIState);
            uiwrappedSearchBar.OnSearchContentsChanged += this.OnSearchContentsChanged;
            uiwrappedSearchBar.SetSearchSnapPoint("SearchButton", 0, null, null);
            uielement2.Append(uiwrappedSearchBar);
            int num3 = 20;
            UIElement uielement3 = new UIElement
            {
                Width = new StyleDimension(0f, 1f),
                Height = new StyleDimension((float)(-(float)num2 - 6 - num3), 1f),
                VAlign = 1f,
                Top = new StyleDimension((float)(-(float)num3), 0f)
            };
            uielement3.SetPadding(0f);
            uipanel.Append(uielement3);
            UIElement uielement4 = new UIElement
            {
                Width = new StyleDimension(0f, 1f),
                Height = new StyleDimension(20f, 0f),
                VAlign = 1f
            };
            uipanel.Append(uielement4);
            uielement4.SetPadding(0f);
            this.FillProgressBottomBar(uielement4);
            UIElement uielement5 = new UIElement
            {
                Width = new StyleDimension(-12f - uibestiaryEntryInfoPage.Width.Pixels, 1f),
                Height = new StyleDimension(-4f, 1f),
                VAlign = 1f
            };
            uielement3.Append(uielement5);
            uielement5.SetPadding(0f);
            this._bestiarySpace = uielement5;
            UIBestiaryEntryGrid uibestiaryEntryGrid = new UIBestiaryEntryGrid(this._workingSetEntries, new UIElement.MouseEvent(this.Click_SelectEntryButton));
            uielement5.Append(uibestiaryEntryGrid);
            this._entryGrid = uibestiaryEntryGrid;
            this._entryGrid.OnGridContentsChanged += this.UpdateBestiaryGridRange;
            uielement3.Append(uibestiaryEntryInfoPage);
            this._infoSpace = uibestiaryEntryInfoPage;
            this.AddBackAndForwardButtons(uielement2);
            this._sortingGrid = new UIBestiarySortingOptionsGrid(this._sorter);
            this._sortingGrid.OnLeftClick += this.Click_CloseSortingGrid;
            this._sortingGrid.OnClickingOption += this.UpdateBestiaryContents;
            this._filteringGrid = new UIBestiaryFilteringOptionsGrid(this._filterer);
            this._filteringGrid.OnLeftClick += this.Click_CloseFilteringGrid;
            this._filteringGrid.OnClickingOption += this.UpdateBestiaryContents;
            this._filteringGrid.SetupAvailabilityTest(this._originalEntriesList);
            this.UpdateBestiaryContents();
        }
References Terraria.GameContent.UI.States.UIBestiaryTest._filterer, Terraria.GameContent.UI.States.UIBestiaryTest._filteringGrid, Terraria.GameContent.UI.States.UIBestiaryTest._originalEntriesList, Terraria.GameContent.UI.States.UIBestiaryTest._sorter, Terraria.GameContent.UI.States.UIBestiaryTest._workingSetEntries, System.Action(), Terraria.GameContent.UI.States.UIBestiaryTest.AddBackAndForwardButtons(), Terraria.GameContent.UI.States.UIBestiaryTest.AddSortAndFilterButtons(), Terraria.UI.UIElement.Append(), Terraria.GameContent.UI.States.UIBestiaryTest.Click_CloseFilteringGrid(), Terraria.GameContent.UI.States.UIBestiaryTest.Click_CloseSortingGrid(), Microsoft.Xna.Framework.Graphics.Color, Terraria.GameContent.UI.States.UIBestiaryTest.FillProgressBottomBar(), Terraria.GameContent.UI.States.UIBestiaryTest.GoBackFromVirtualKeyboard(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.GameContent.UI.States.UIBestiaryTest.MakeExitButton(), Terraria.UI.UIElement.MaxWidth, Terraria.UI.UIElement.MinWidth, Terraria.UI.UIElement.MouseEvent(), Terraria.GameContent.UI.States.UIBestiaryTest.OnSearchContentsChanged(), Terraria.UI.IngameFancyUI.OpenUIState(), Terraria.UI.StyleDimension.Pixels, Terraria.UI.StyleDimension.Set(), Terraria.UI.UIElement.SetPadding(), Terraria.GameContent.UI.Elements.UIWrappedSearchBar.SetSearchSnapPoint(), Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid.SetupAvailabilityTest(), Terraria.UI.UIElement.Top, Terraria.UI.UIElement.UIElement(), Terraria.GameContent.UI.States.UIBestiaryTest.UpdateBestiaryContents(), Terraria.GameContent.UI.States.UIBestiaryTest.UpdateBestiaryGridRange(), Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.UIBestiaryTest.UIBestiaryTest().