Terraria Decompiled: Terraria.GameContent.UI.States.UIBestiaryTest.GetOrderedPointsByCategoryName
GetOrderedPointsByCategoryName()
static List< SnapPoint > Terraria.GameContent.UI.States.UIBestiaryTest.GetOrderedPointsByCategoryName (List< SnapPoint > pts, string name) inline static private
Definition at line 869 of file UIBestiaryTest.cs.
        {
            return (from x in pts
                where x.Name == name
                orderby x.Id
                select x).ToList<SnapPoint>();
        }
References System.name.
Referenced by Terraria.GameContent.UI.States.UIBestiaryTest.SetupPointsForEntryGrid(), Terraria.GameContent.UI.States.UIBestiaryTest.SetupPointsForFilterGrid(), and Terraria.GameContent.UI.States.UIBestiaryTest.SetupPointsForSortingGrid().