Terraria Decompiled: rail.IRailInGamePurchaseImpl.AsyncPurchaseProducts
AsyncPurchaseProducts()
virtual RailResult rail.IRailInGamePurchaseImpl.AsyncPurchaseProducts (List< RailProductItem > cart_items, string user_data) inline virtual
Implements rail.IRailInGamePurchase.
Definition at line 53 of file IRailInGamePurchaseImpl.cs.
        {
            IntPtr intPtr = ((cart_items == null) ? IntPtr.Zero : RAIL_API_PINVOKE.new_RailArrayRailProductItem__SWIG_0());
            if (cart_items != null)
            {
                RailConverter.Csharp2Cpp(cart_items, intPtr);
            }
            RailResult railResult;
            try
            {
                railResult = (RailResult)RAIL_API_PINVOKE.IRailInGamePurchase_AsyncPurchaseProducts(this.swigCPtr_, intPtr, user_data);
            }
            finally
            {
                RAIL_API_PINVOKE.delete_RailArrayRailProductItem(intPtr);
            }
            return railResult;
        }
References rail.RailConverter.Csharp2Cpp(), rail.RAIL_API_PINVOKE.delete_RailArrayRailProductItem(), rail.RAIL_API_PINVOKE.IRailInGamePurchase_AsyncPurchaseProducts(), rail.RAIL_API_PINVOKE.new_RailArrayRailProductItem__SWIG_0(), and System.IntPtr.Zero.