Terraria Decompiled: Terraria.GameContent.QuickStacking.ReadNetInventory
ReadNetInventory()
static QuickStacking.SourceInventory Terraria.GameContent.QuickStacking.ReadNetInventory (Player player, BinaryReader reader) inline static package
Definition at line 118 of file QuickStacking.cs.
        {
            QuickStacking.SourceInventory scratchInventory = QuickStacking.GetScratchInventory(player);
            Array.Clear(scratchInventory.transferBlocked, 0, scratchInventory.transferBlocked.Length);
            scratchInventory.numItems = reader.ReadInt32();
            for (int i = 0; i < scratchInventory.numItems; i++)
            {
                PlayerItemSlotID.SlotReference slotReference = new PlayerItemSlotID.SlotReference(player, (int)reader.ReadInt16());
                scratchInventory.slots[i] = slotReference;
                Item item = slotReference.Item;
                scratchInventory.items[i] = item;
            }
            return scratchInventory;
        }
References System.Array.Clear(), Terraria.GameContent.QuickStacking.GetScratchInventory(), System.item, Terraria.ID.PlayerItemSlotID.SlotReference.Item, Terraria.GameContent.QuickStacking.SourceInventory.items, Terraria.GameContent.QuickStacking.SourceInventory.numItems, System.IO.BinaryReader.ReadInt16(), System.IO.BinaryReader.ReadInt32(), Terraria.GameContent.QuickStacking.SourceInventory.slots, and Terraria.GameContent.QuickStacking.SourceInventory.transferBlocked.