Terraria Decompiled: rail.IRailBrowserHelperImpl.AsyncCreateBrowser
AsyncCreateBrowser() [2/3]
virtual IRailBrowser rail.IRailBrowserHelperImpl.AsyncCreateBrowser (string url, uint window_width, uint window_height, string user_data, CreateBrowserOptions options) inline virtual
Implements rail.IRailBrowserHelper.
Definition at line 41 of file IRailBrowserHelperImpl.cs.
        {
            IntPtr intPtr = ((options == null) ? IntPtr.Zero : RAIL_API_PINVOKE.new_CreateBrowserOptions__SWIG_0());
            if (options != null)
            {
                RailConverter.Csharp2Cpp(options, intPtr);
            }
            IRailBrowser railBrowser;
            try
            {
                IntPtr intPtr2 = RAIL_API_PINVOKE.IRailBrowserHelper_AsyncCreateBrowser__SWIG_1(this.swigCPtr_, url, window_width, window_height, user_data, intPtr);
                railBrowser = ((intPtr2 == IntPtr.Zero) ? null : new IRailBrowserImpl(intPtr2));
            }
            finally
            {
                RAIL_API_PINVOKE.delete_CreateBrowserOptions(intPtr);
            }
            return railBrowser;
        }
References rail.RailConverter.Csharp2Cpp(), rail.RAIL_API_PINVOKE.delete_CreateBrowserOptions(), rail.RAIL_API_PINVOKE.IRailBrowserHelper_AsyncCreateBrowser__SWIG_1(), rail.RAIL_API_PINVOKE.new_CreateBrowserOptions__SWIG_0(), System.options, rail.RailObject.swigCPtr_, and System.IntPtr.Zero.