Terraria Decompiled: Terraria.GameContent.QuickStacking.PackQuickStackableItems
PackQuickStackableItems()
static QuickStacking.SourceInventory Terraria.GameContent.QuickStacking.PackQuickStackableItems (Player player, bool includeVoidBag) inline static private
Definition at line 192 of file QuickStacking.cs.
        {
            QuickStacking.SourceInventory scratchInventory = QuickStacking.GetScratchInventory(player);
            Array.Clear(scratchInventory.transferBlocked, 0, scratchInventory.transferBlocked.Length);
            QuickStacking.AddQuickStackableItems(player, ref scratchInventory, PlayerItemSlotID.Inventory0 + 10, 40);
            if (player.useVoidBag() && includeVoidBag)
            {
                QuickStacking.AddQuickStackableItems(player, ref scratchInventory, PlayerItemSlotID.Bank4_0, player.bank4.maxItems);
            }
            return scratchInventory;
        }
References Terraria.GameContent.QuickStacking.AddQuickStackableItems(), Terraria.Player.bank4, Terraria.ID.PlayerItemSlotID.Bank4_0, System.Array.Clear(), Terraria.GameContent.QuickStacking.GetScratchInventory(), Terraria.ID.PlayerItemSlotID.Inventory0, Terraria.Chest.maxItems, Terraria.GameContent.QuickStacking.SourceInventory.transferBlocked, and Terraria.Player.useVoidBag().
Referenced by Terraria.GameContent.QuickStacking.QuickStackToNearbyBanks(), and Terraria.GameContent.QuickStacking.QuickStackToNearbyChests().