Terraria Decompiled: System.Collections.Generic.EnumerableHelpers.ToArray< T >
ToArray< T >() [1/2]
static T[] System.Collections.Generic.EnumerableHelpers.ToArray< T > (IEnumerable< T > source) inline static package
Definition at line 30 of file EnumerableHelpers.cs.
        {
            ICollection<T> collection = source as ICollection<T>;
            if (collection == null)
            {
                LargeArrayBuilder<T> largeArrayBuilder = new LargeArrayBuilder<T>(true);
                largeArrayBuilder.AddRange(source);
                return largeArrayBuilder.ToArray();
            }
            int count = collection.Count;
            if (count == 0)
            {
                return Array.Empty<T>();
            }
            T[] array = new T[count];
            collection.CopyTo(array, 0);
            return array;
        }
References System.Collections.Generic.LargeArrayBuilder< T >.AddRange(), System.array, System.collection, System.Array.CopyTo(), System.count, System.source, and System.Collections.Generic.LargeArrayBuilder< T >.ToArray().