Terraria Decompiled: Terraria.UI.Chat.ChatManager.DrawColorCodedString
DrawColorCodedString() [4/4]
static Vector2 Terraria.UI.Chat.ChatManager.DrawColorCodedString (SpriteBatch spriteBatch, DynamicSpriteFont font, string text, Vector2 position, Color baseColor, float rotation, Vector2 origin, Vector2 baseScale, float maxWidth = -1f, bool ignoreColors = false) inline static
Definition at line 280 of file ChatManager.cs.
        {
            Vector2 vector = position;
            Vector2 vector2 = vector;
            string[] array = text.Split(new char[] { '\n' });
            float x = font.MeasureString(" ").X;
            Color color = baseColor;
            float num = 1f;
            float num2 = 0f;
            string[] array2 = array;
            for (int i = 0; i < array2.Length; i++)
            {
                foreach (string text2 in array2[i].Split(new char[] { ':' }))
                {
                    if (text2.StartsWith("sss"))
                    {
                        if (text2.StartsWith("sss1"))
{
                            if (!ignoreColors)
{
                                color = Color.Red;
                            }
                        }
                        else if (text2.StartsWith("sss2"))
{
                            if (!ignoreColors)
{
                                color = Color.Blue;
                            }
                        }
                        else if (text2.StartsWith("sssr") && !ignoreColors)
{
                            color = Color.White;
                        }
                    }
                    else
                    {
                        string[] array4 = text2.Split(new char[] { ' ' });
                        for (int k = 0; k < array4.Length; k++)
{
                            if (k != 0)
{
                                vector.X += x * baseScale.X * num;
                            }
                            if (maxWidth > 0f)
{
                                float num3 = font.MeasureString(array4[k]).X * baseScale.X * num;
                                if (vector.X - position.X + num3 > maxWidth)
{
                                    vector.X = position.X;
                                    vector.Y += (float)font.LineSpacing * num2 * baseScale.Y;
                                    vector2.Y = Math.Max(vector2.Y, vector.Y);
                                    num2 = 0f;
                                }
                            }
                            if (num2 < num)
{
                                num2 = num;
                            }
                            DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, font, array4[k], vector, color, rotation, origin, baseScale * num, SpriteEffects.None, 0f);
                            vector.X += font.MeasureString(array4[k]).X * baseScale.X * num;
                            vector2.X = Math.Max(vector2.X, vector.X);
                        }
                    }
                }
                vector.X = position.X;
                vector.Y += (float)font.LineSpacing * num2 * baseScale.Y;
                vector2.Y = Math.Max(vector2.Y, vector.Y);
                num2 = 0f;
            }
            return vector2;
        }
References System.array, Microsoft.Xna.Framework.Color.Blue, ReLogic.Graphics.DynamicSpriteFontExtensionMethods.DrawString(), ReLogic.Graphics.DynamicSpriteFont.LineSpacing, System.Math.Max(), ReLogic.Graphics.DynamicSpriteFont.MeasureString(), Microsoft.Xna.Framework.Color.Red, System.text, Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.