Terraria Decompiled: Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow
DrawColorCodedStringWithShadow() [1/3]
static void Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow (SpriteBatch spriteBatch, DynamicSpriteFont font, string text, Vector2 position, Color baseColor, float rotation, Vector2 origin, Vector2 scale, float maxWidth = -1f, float spread = 2f) inline static
Definition at line 354 of file ChatManager.cs.
        {
            Color color = baseColor.MultiplyRGBA(Color.Black);
            if (maxWidth < 0f && !ChatManager.MayNeedParsing(text))
            {
                foreach (Vector2 vector in ChatManager.ShadowDirections)
                {
                    DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, font, text, position + vector * spread, color, rotation, origin, scale, SpriteEffects.None, 0f);
                }
                DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, font, text, position, baseColor, rotation, origin, scale, SpriteEffects.None, 0f);
                return;
            }
            List<TextSnippet> list = ChatManager.ParseMessage(text, baseColor);
            ChatManager.ConvertNormalSnippets(list);
            List<PositionedSnippet> list2 = ChatManager.LayoutSnippets(font, list, scale, maxWidth).ToList<PositionedSnippet>();
            ChatManager.DrawColorCodedStringShadow(spriteBatch, font, list2, position, color, rotation, origin, scale, spread);
            int num;
            ChatManager.DrawColorCodedString(spriteBatch, font, list2, position, rotation, origin, scale, out num, null);
        }
References Microsoft.Xna.Framework.Color.Black, Terraria.UI.Chat.ChatManager.ConvertNormalSnippets(), Terraria.UI.Chat.ChatManager.DrawColorCodedString(), Terraria.UI.Chat.ChatManager.DrawColorCodedStringShadow(), ReLogic.Graphics.DynamicSpriteFontExtensionMethods.DrawString(), Terraria.UI.Chat.ChatManager.LayoutSnippets(), System.list, Terraria.UI.Chat.ChatManager.MayNeedParsing(), Terraria.UI.Chat.ChatManager.ParseMessage(), Terraria.UI.Chat.ChatManager.ShadowDirections, and System.text.