Terraria Decompiled: Terraria.UI.Chat.ChatManager.LayoutSnippets
LayoutSnippets()
static IEnumerable< PositionedSnippet > Terraria.UI.Chat.ChatManager.LayoutSnippets (DynamicSpriteFont font, IEnumerable< TextSnippet > snippets, Vector2 scale, float maxWidth = -1f) inline static
Definition at line 121 of file ChatManager.cs.
        {
            int line = 0;
            Vector2 pos = Vector2.Zero;
            float uniqueDrawScale = Math.Min(scale.X, scale.Y);
            int i = 0;
            foreach (TextSnippet snippet in snippets)
            {
                Vector2 size;
                int num;
                if (snippet.UniqueDraw(true, out size, null, default(Vector2), default(Color), uniqueDrawScale))
                {
                    if (maxWidth >= 0f && pos.X + size.X > maxWidth)
                    {
                        pos.X = 0f;
                        pos.Y += (float)font.LineSpacing * scale.Y;
                        num = line;
                        line = num + 1;
                    }
                    yield return new PositionedSnippet(snippet, i, line, pos, size);
                    pos.X += size.X;
                }
                else
                {
                    string text = font.CreateWrappedText(snippet.Text, scale.X, maxWidth, pos.X, Language.ActiveCulture.CultureInfo);
                    int num2 = 0;
                    for (;;)
                    {
                        int sep = text.IndexOf('\n', num2);
                        int num3 = ((sep < 0) ? text.Length : sep) - num2;
                        if (num3 > 0)
{
                            string text2 = text.Substring(num2, num3);
                            size = font.MeasureString(text2) * scale;
                            yield return new PositionedSnippet(snippet.CopyMorph(text2), i, line, pos, size);
                            pos.X += size.X;
                        }
                        if (sep < 0)
{
                            break;
                        }
                        pos.X = 0f;
                        pos.Y += (float)font.LineSpacing * scale.Y;
                        num = line;
                        line = num + 1;
                        num2 = sep + 1;
                    }
                    text = null;
                }
                num = i;
                i = num + 1;
                size = default(Vector2);
                snippet = null;
            }
            IEnumerator<TextSnippet> enumerator = null;
            yield break;
            yield break;
        }
References Terraria.Localization.Language.ActiveCulture, Terraria.UI.Chat.TextSnippet.CopyMorph(), Terraria.Localization.GameCulture.CultureInfo, System.Math.Min(), System.text, Terraria.UI.Chat.TextSnippet.Text, Terraria.UI.Chat.TextSnippet.UniqueDraw(), Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.UI.Chat.ChatManager.DrawColorCodedString(), Terraria.UI.Chat.ChatManager.DrawColorCodedString(), Terraria.UI.Chat.ChatManager.DrawColorCodedStringShadow(), Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.UI.Chat.ChatManager.GetStringSize(), Terraria.GameContent.UI.Elements.UIText.InternalSetText(), and Terraria.Utils.WordwrapStringSmart().