Terraria Decompiled: System.Reflection.Emit.TypeBuilder.ResolveUserType
ResolveUserType()
static Type System.Reflection.Emit.TypeBuilder.ResolveUserType (Type t) inline static package
Definition at line 983 of file TypeBuilder.cs.
        {
            if (!(t != null) || (!(t.GetType().Assembly != typeof(int).Assembly) && !(t is TypeDelegator)))
            {
                return t;
            }
            t = t.UnderlyingSystemType;
            if (t != null && (t.GetType().Assembly != typeof(int).Assembly || t is TypeDelegator))
            {
                throw new NotSupportedException("User defined subclasses of System.Type are not yet supported.");
            }
            return t;
        }
References System.Type.Assembly, System.Type.GetType(), and System.Type.UnderlyingSystemType.
Referenced by System.Reflection.Emit.FieldBuilder.ResolveUserTypes(), System.Reflection.Emit.MethodBuilder.ResolveUserTypes(), System.Reflection.Emit.TypeBuilder.ResolveUserTypes(), System.Reflection.Emit.TypeBuilder.ResolveUserTypes(), System.Reflection.Emit.TypeBuilder.SetParent(), and System.Reflection.Emit.TypeBuilder.TypeBuilder().