Terraria Decompiled: System.Reflection.Emit.TypeBuilder.GetProperties
GetProperties()
override PropertyInfo[] System.Reflection.Emit.TypeBuilder.GetProperties (BindingFlags bindingAttr) inline
Implements System.Reflection.IReflect.
Definition at line 1482 of file TypeBuilder.cs.
        {
            if (this.is_created)
            {
                return this.created.GetProperties(bindingAttr);
            }
            if (this.properties == null)
            {
                return new PropertyInfo[0];
            }
            ArrayList arrayList = new ArrayList();
            foreach (PropertyBuilder propertyInfo in this.properties)
            {
                bool flag = false;
                MethodInfo methodInfo = propertyInfo.GetGetMethod(true);
                if (methodInfo == null)
                {
                    methodInfo = propertyInfo.GetSetMethod(true);
                }
                if (!(methodInfo == null))
                {
                    MethodAttributes attributes = methodInfo.Attributes;
                    if ((attributes & MethodAttributes.MemberAccessMask) == MethodAttributes.Public)
                    {
                        if ((bindingAttr & BindingFlags.Public) != BindingFlags.Default)
{
                            flag = true;
                        }
                    }
                    else if ((bindingAttr & BindingFlags.NonPublic) != BindingFlags.Default)
                    {
                        flag = true;
                    }
                    if (flag)
                    {
                        flag = false;
                        if ((attributes & MethodAttributes.Static) != MethodAttributes.PrivateScope)
{
                            if ((bindingAttr & BindingFlags.Static) != BindingFlags.Default)
{
                                flag = true;
                            }
                        }
                        else if ((bindingAttr & BindingFlags.Instance) != BindingFlags.Default)
{
                            flag = true;
                        }
                        if (flag)
{
                            arrayList.Add(propertyInfo);
                        }
                    }
                }
            }
            PropertyInfo[] array2 = new PropertyInfo[arrayList.Count];
            arrayList.CopyTo(array2);
            return array2;
        }
References System.Reflection.MethodBase.Attributes, System.Reflection.Emit.TypeBuilder.created, System.Reflection.Emit.PropertyBuilder.GetGetMethod(), System.Type.GetProperties(), System.Reflection.Emit.PropertyBuilder.GetSetMethod(), System.Reflection.Emit.TypeBuilder.is_created, and System.Reflection.Emit.TypeBuilder.properties.
Referenced by System.Reflection.Emit.EnumBuilder.GetProperties().