Terraria Decompiled: System.Reflection.Emit.TypeBuilder.TypeBuilder
TypeBuilder() [3/3]
System.Reflection.Emit.TypeBuilder.TypeBuilder (ModuleBuilder mb, string name, TypeAttributes attr, Type parent, Type[] interfaces, PackingSize packing_size, int type_size, Type nesting_type) inline package
Definition at line 75 of file TypeBuilder.cs.
            : this()
        {
            this.parent = TypeBuilder.ResolveUserType(parent);
            this.attrs = attr;
            this.class_size = type_size;
            this.packing_size = packing_size;
            this.nesting_type = nesting_type;
            this.check_name("fullname", name);
            if (parent == null && (attr & TypeAttributes.ClassSemanticsMask) != TypeAttributes.NotPublic && (attr & TypeAttributes.Abstract) == TypeAttributes.NotPublic)
            {
                throw new InvalidOperationException("Interface must be declared abstract.");
            }
            int num = name.LastIndexOf('.');
            if (num != -1)
            {
                this.tname = name.Substring(num + 1);
                this.nspace = name.Substring(0, num);
            }
            else
            {
                this.tname = name;
                this.nspace = string.Empty;
            }
            if (interfaces != null)
            {
                this.interfaces = new Type[interfaces.Length];
                Array.Copy(interfaces, this.interfaces, interfaces.Length);
            }
            this.pmodule = mb;
            if ((attr & TypeAttributes.ClassSemanticsMask) == TypeAttributes.NotPublic && parent == null)
            {
                this.parent = typeof(object);
            }
            this.table_idx = mb.get_next_table_index(this, 2, 1);
            this.fullname = this.GetFullName();
        }
References System.Reflection.Emit.TypeBuilder.check_name(), System.Array.Copy(), System.Reflection.Emit.ModuleBuilder.get_next_table_index(), System.Reflection.Emit.TypeBuilder.GetFullName(), System.Reflection.Emit.TypeBuilder.interfaces, System.name, System.Reflection.Emit.TypeBuilder.nesting_type, System.Reflection.Emit.TypeBuilder.packing_size, System.Reflection.Emit.TypeBuilder.parent, and System.Reflection.Emit.TypeBuilder.ResolveUserType().