Terraria Decompiled: System.Reflection.Emit.TypeBuilder.GetFullName
GetFullName()
TypeName System.Reflection.Emit.TypeBuilder.GetFullName () inline private
Definition at line 200 of file TypeBuilder.cs.
        {
            TypeIdentifier typeIdentifier = TypeIdentifiers.FromInternal(this.tname);
            if (this.nesting_type != null)
            {
                return TypeNames.FromDisplay(this.nesting_type.FullName).NestedName(typeIdentifier);
            }
            if (this.nspace != null && this.nspace.Length > 0)
            {
                return TypeIdentifiers.FromInternal(this.nspace, typeIdentifier);
            }
            return typeIdentifier;
        }
References System.TypeNames.FromDisplay(), System.TypeIdentifiers.FromInternal(), System.Type.FullName, System.TypeName.NestedName(), System.Reflection.Emit.TypeBuilder.nesting_type, System.Reflection.Emit.TypeBuilder.nspace, and System.Reflection.Emit.TypeBuilder.tname.
Referenced by System.Reflection.Emit.TypeBuilder.DefineNestedType(), and System.Reflection.Emit.TypeBuilder.TypeBuilder().