Terraria Decompiled: System.Reflection.Emit.TypeBuilder.RuntimeResolve
RuntimeResolve()
override Type System.Reflection.Emit.TypeBuilder.RuntimeResolve () inline package virtual
Reimplemented from System.Type.
Definition at line 1926 of file TypeBuilder.cs.
        {
            this.check_created();
            return this.created;
        }
References System.Reflection.Emit.TypeBuilder.check_created(), and System.Reflection.Emit.TypeBuilder.created.
Referenced by System.Reflection.Emit.ConstructorBuilder.RuntimeResolve(), System.Reflection.Emit.EnumBuilder.RuntimeResolve(), System.Reflection.Emit.GenericTypeParameterBuilder.RuntimeResolve(), and System.Reflection.Emit.MethodBuilder.RuntimeResolve().