Terraria Decompiled: System.Reflection.Emit.TypeBuilder.DefineNestedType
DefineNestedType() [8/8]
TypeBuilder System.Reflection.Emit.TypeBuilder.DefineNestedType (string name, TypeAttributes attr, Type parent, Type[] interfaces, PackingSize packSize, int typeSize) inline private
Definition at line 458 of file TypeBuilder.cs.
        {
            if (interfaces != null)
            {
                for (int i = 0; i < interfaces.Length; i++)
                {
                    if (interfaces[i] == null)
                    {
                        throw new ArgumentNullException("interfaces");
                    }
                }
            }
            TypeBuilder typeBuilder = new TypeBuilder(this.pmodule, name, attr, parent, interfaces, packSize, typeSize, this);
            typeBuilder.fullname = typeBuilder.GetFullName();
            this.pmodule.RegisterTypeName(typeBuilder, typeBuilder.fullname);
            if (this.subtypes != null)
            {
                TypeBuilder[] array = new TypeBuilder[this.subtypes.Length + 1];
                Array.Copy(this.subtypes, array, this.subtypes.Length);
                array[this.subtypes.Length] = typeBuilder;
                this.subtypes = array;
            }
            else
            {
                this.subtypes = new TypeBuilder[1];
                this.subtypes[0] = typeBuilder;
            }
            return typeBuilder;
        }
References System.array, System.Array.Copy(), System.Reflection.Emit.TypeBuilder.fullname, System.Reflection.Emit.TypeBuilder.GetFullName(), System.Reflection.Emit.TypeBuilder.interfaces, System.Reflection.Emit.TypeBuilder.parent, System.Reflection.Emit.TypeBuilder.pmodule, System.Reflection.Emit.ModuleBuilder.RegisterTypeName(), System.Reflection.Emit.TypeBuilder.subtypes, and System.Reflection.Emit.TypeBuilder.TypeBuilder().