Terraria Decompiled: System.Reflection.Emit.TypeBuilder.DefinePInvokeMethod
DefinePInvokeMethod() [3/3]
MethodBuilder System.Reflection.Emit.TypeBuilder.DefinePInvokeMethod (string name, string dllName, string entryName, MethodAttributes attributes, CallingConventions callingConvention, Type returnType, Type[] returnTypeRequiredCustomModifiers, Type[] returnTypeOptionalCustomModifiers, Type[] parameterTypes, Type parameterTypeRequiredCustomModifiers[][], Type parameterTypeOptionalCustomModifiers[][], CallingConvention nativeCallConv, CharSet nativeCharSet) inline
Definition at line 630 of file TypeBuilder.cs.
        {
            this.check_name("name", name);
            this.check_name("dllName", dllName);
            this.check_name("entryName", entryName);
            if ((attributes & MethodAttributes.Abstract) != MethodAttributes.PrivateScope)
            {
                throw new ArgumentException("PInvoke methods must be static and native and cannot be abstract.");
            }
            if (base.IsInterface)
            {
                throw new ArgumentException("PInvoke methods cannot exist on interfaces.");
            }
            this.check_not_created();
            MethodBuilder methodBuilder = new MethodBuilder(this, name, attributes, callingConvention, returnType, returnTypeRequiredCustomModifiers, returnTypeOptionalCustomModifiers, parameterTypes, parameterTypeRequiredCustomModifiers, parameterTypeOptionalCustomModifiers, dllName, entryName, nativeCallConv, nativeCharSet);
            this.append_method(methodBuilder);
            return methodBuilder;
        }
References System.Reflection.Emit.TypeBuilder.append_method(), System.Reflection.Emit.TypeBuilder.check_name(), System.Reflection.Emit.TypeBuilder.check_not_created(), and System.name.